### ISSUE TITLE
Manifest options not available with test_package

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1002]
I like `test_package` as my one-stop command for re-generating a package while developing it, and I like to check in a `manifests` directory with my recipe, as my package is built out of mostly externally built tools, but as of 0.19.2, I have to go down into the build/<package_id> directory and do a `conan install -m...` as a separate step.

Does my workflow make sense, and would it make sense to have a `-m` option on `test_package`?

**Comment by memsharded** [comment]
Yes, definitely, ``test_package`` is the reference command for creating packages. 
Yes, why not, I also think it makes sense to have ``-m`` in ``test_package`` too.

**Comment by memsharded** [comment]
Released in 0.21
