### ISSUE TITLE
[feature] C++23 support for "Visual Studio"

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#10020]
Even though C++23 was added in `settings.yml` for `msvc` it was not for `Visual Studio`. Could you please add it? There are some C++ features that already depend on this flag (i.e. native support for `std::format`).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Added, will be in 1.43
