### ISSUE TITLE
[feature] Extend --require-override to `conan info`

### ISSUE THREAD

**Issue by slietzau** [conan-io/conan#10023]
Essentially the same as #9392 but for `conan info`.

In our pipeline we use `conan info` to determine which packages need to be built and then build the packages with `conan install ... --build=<package> <additional_cmdline>` where we use the same `additional_cmdline` for both `conan info` and `conan install`. This doesn't work because `conan info` doesn't support the parameter yet.

Is it a sensible assumption that the same parameters regarding the dependency graph (profiles, options, settings, etc.) work for both `conan info` and `conan install` ?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by derived-coder** [comment]
Yeah, I would like to have this feature also with conan info

Here is the original MR: https://github.com/conan-io/conan/pull/9195/files

**Comment by derived-coder** [comment]
@memsharded
What needs to be done to implement it our self?
Where should we start?

**Comment by paulharris** [comment]
+1
Would like to see this implemented.
Perhaps also extend "conan install" to add a "conan install --info" to call "conan info" instead.
I use "conan info" to diagnose requirement override issues, incorrect package revision choices and package conflicts.
Note that you can't diagnose those problems from an install-folder, as the conan-install will fail before the folder is populated.

**Comment by memsharded** [comment]
--require-override has been removed in Conan 2, closing as not planned. Thanks for the feedback.
