### ISSUE TITLE
[question] How to obtain header-only lib for source distribution?

### ISSUE THREAD

**Issue by randrej** [conan-io/conan#10029]
I'm using Conan on a little project. One of the dependencies for the project is a [single-header, header-only lib](https://github.com/Taywee/args). Usually, I use the *cmake_find_package* generator and it works fine. Conan downloads the library into its system-wide library store, and generates a Findargs.cmake file in the build dir, which references that global path.

However, I now want to make a source distribution which includes this header-only lib.  The source distro has to work without downloading anything from the net, so Conan is out - all the files required for building (except shared libs) have to be packaged. Is there a way to do this (semi-)automatically? What came to my mind is to somehow extract the conan package path into a variable, copy the folder into the output dir, and then replace that path in the conan-generated FindLib.cmake.

Is there a better way? I just want to include the header-only lib in my source distribution...

I'm using [this method](https://jtanx.github.io/2019/08/22/cmake-dist-customisation/) for custom tailoring of the CPack source distr.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @randrej 

A couple of clarifications:

> Conan downloads the library into its system-wide library store, 

It is not a system-wide store. By default is per-user, but for concurrent systems like CI agents, each concurrent job should use its own store (with CONAN_USER_HOME env-var)

> However, I now want to make a source distribution which includes this header-only lib. 

Can you please clarify what you mean with "to make a source distribution"? Isn't that cloning the original git repo?


>  all the files required for building (except shared libs) have to be packaged. Is there a way to do this (semi-)automatically?

If you want to extract files from Conan packages to user space, I guess that you would be interested in the "deploy" functionality (``conan install -g deploy``, check https://docs.conan.io/en/latest/reference/generators/deploy.html), or having a look to the ``imports`` functionality (writing a conanfile that specifies what and how you want to import to your folder, conanfile.txt with https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#imports, or conanfile.py with https://docs.conan.io/en/latest/reference/conanfile/methods.html?#imports).

Please have a look to those and let me know if that helps.

**Comment by memsharded** [comment]
Closing this ticket as inactive.

Also, the deployers can collect all dependencies and create such a distribution, see https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html
