### ISSUE TITLE
[feature] gcc 11.2 released

### ISSUE THREAD

**Issue by alixinne** [conan-io/conan#10022]
GCC 11.2 was released in July 2021: https://gcc.gnu.org/pipermail/gcc/2021-July/236904.html

It has shipped in some distributions at least (Fedora 35 in my case).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Added in https://github.com/conan-io/conan/pull/10021, will be in 1.43
