### ISSUE TITLE
[bug] Unexpected message output contaminating conan inspect --raw

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#10034]
We're using `conan inspect --raw ...` to programmatically retrieve values from a conanfile. This used to work fine but started to fail some time ago. After some investigation I found that the output now contains an extra message before the line with the actual value:

```
Removing temporary .tgz files, they are stored in a different location now
8.0.0
```

This seems to be some kind of informational message regarding migration of .tgz files. I guess it's usually fine to print this, but in commands like `conan inspect` which are likely to be used for programmatic evaluation I'd recommend suppressing it.

**Comment by franramirez688** [comment]
Hi @jasal82 

Which conan version are you using? This message is only supposed to appear once and if you're using a version < `1.31.0`.
This kind of message normally appears when you execute the first time conan after installing a new version.
Is it showing that message all the time?

**Comment by jasal82** [comment]
Happens on 1.42.1. The problem is that we're installing a fresh version of Conan in each container instance. In the failing instance the `conan inspect` is run as the first command.

**Comment by franramirez688** [comment]
@jasal82 

Would it be possible to run before the `conan inspect` something like `conan -v` then you would get a clean output for the next command run, e.g., that `conan inspect --raw ...`?

For instance:

```bash
(conan) ➜  conan git:(782587926) conan -v
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: /Users/franchuti/.conan/settings.yml.new
WARN: ****************************************
Removing temporary .tgz files, they are stored in a different location now
Conan 'cacert.pem' is up to date...
Conan version 1.42.1
(conan) ➜  conan git:(782587926) conan inspect -a options open/0.1
options:
    fPIC: [True, False]
    shared: [True, False]
```

**Comment by memsharded** [comment]
A suggestion, the ``conan inspect`` contains a ``--json`` argument for this purpose: programmatic access. Is there any specific reason why you are not using the json output? It would be way mor convenient than parsing the stdout unstructured output

**Comment by jasal82** [comment]
@franramirez688 I've already implemented that workaround in our pipeline.
@memsharded I agree that using the json output would be the more powerful option, but in our case we're just trying to read the version, so we would then need a JSON parser in the pipeline to parse the single value from the JSON struct or use a regex. Is the extra message gone in the `--json` case?

**Comment by memsharded** [comment]
It is a ``--json=somefile.json`` argument, whatever appears in the terminal stdout is not stored in the json file. If the field is restricted to the version, then parsing that file should be relatively straightforward with a similar regex, probably not necessary a full json loader.
