### ISSUE TITLE
[question] How to apply options to the package and its dependencies?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#10048]
Hello,

assume I have:

App->LibA->LibB->LibC->LibD

[The actual situation is lot worse, lot more components, lot more complex graph]

I want to set fPIC from profile on LibB,C,D but not on LibA and LibB.

Can I do that without specifying all three libs manually in the profile? Is there a way to tell 

LibB*.fPIC=True

in profiles?
Thanks,

**Comment by AbrilRBS** [comment]
Hi. Sorry that this got lost in the sea of issues. Answering this for posterity before closing, but yes, options can be scoped per-package (Or in fact, per package pattern!) to only apply to specific packages - see https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns for the docs
