### ISSUE TITLE
[question] How do I pass a cmake option/defintion recursively through the dependency tree

### ISSUE THREAD

**Issue by ajrup** [conan-io/conan#10047]
I'm wondering if there is a way for conan to pass a cmake option/definition/configuration recursively through a dependency tree. Specifically, I have one header only library (let's call it libA) that will take a cmake option (I'm open to other alternatives) and will ultimately provide either a different header file or compile time switches (macros) in one header file.

This illustrates an example set of dependencies:
```
            bin
          /      \
       libC       libD
      /      \        \
   libB      libA      libA
   /
libA
```

All libraries in this scenario are managed from via conan. How do I configure "bin" in the above example to pass to all instances of libA that it should be built with option X, Y, or Z?

One constraint that I have is I would like to use the same source, but be able to compile it with different options. For example, I want to be able to compile "bin" for a development environment where libA uses option X, in test libA should use option Y, and in prod libA should use option Z. Because of this constraint, I would say that modifying my conanfile.txt (for "bin") is not ideal.

I would not be surprised if there's an easy way to do this and I'm just unaware of it, but any guidance would be appreciated! Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
It depends on how your actual dependency graph looks like. There are 2 possibilities:

- You are using ``private`` requires, and then libD, libC and libB can have different instances of libA. I hope it is not the case, these dependency graphs are typically challenging to maintain, and there can be many issues.
- The dependency graph is actually a diamond-like one, and all libD, libC and libB depends on the same instance of libA. This is the most typical scenario.

For the second one, I am not sure about the issue, but it typically is doing ``-o libA:myoption=myvalue`` while you are installing the dependency graph. Depending on your ``package_id()``, the default mode could be insufficient, I don't know if this is your actual issue. If you want to force to have different binaries of the consumer libraries and appplication, you might need to up your ``default_package_id_mode`` to something higher than the default one (which is semver, major-only package_id).


Please let me know if this makes help, and if you can clarify your current scenario.

**Comment by ajrup** [comment]
Still designing this library, so nothing has been set in stone (this tree was a quick mock up from my brain), but no, I was not planning on using `private`. So a diamond tree is accurate.

Ah ok - I will try the option you listed and report back. I'm guessing it will work and is just part of the learning curve for myself. I am using cmake-conan in "bin", so it looks like [this ](https://github.com/conan-io/cmake-conan#conan_cmake_run-options) is the appropriate mechanism to set the option.

**Comment by ajrup** [comment]
Yup, the simple "-o" option when installing was my solution. Thanks for the assistance :)
