### ISSUE TITLE
[question] How to run source with debugger? 

### ISSUE THREAD

**Issue by rl-enjoyer** [conan-io/conan#10055]
Hello, I've cloned the repo and have been trying to run the code with a debugger locally. With pycharm it does not work. The breakpoints are never hit, but changes I made to the files are taken when I run the debugger. 

I was wondering if there is a way to run conan with a debugger? Hopefully in pycharm or visual studio code.

Thanks. 

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by ziish** [comment]
For vscode and the python extension it works for me with this `launch.json`:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "conan",
      "type": "python",
      "request": "launch",
      "module": "conans.conan",
      "cwd": "/tmp/somecwd-you-want-to-use",
      "args": [
        "..../"
      ]
    }
  ]
}
```

**Comment by rl-enjoyer** [comment]
Thanks very much!!

When doing this I saw
![image](https://user-images.githubusercontent.com/11447537/142682951-9cb7b393-bc32-451a-bbd7-cdf2f02147c6.png)

So following https://stackoverflow.com/a/63271966/7945066

I added 

`      "env": { "PYTHONPATH": "${workspaceRoot}"}`

And that did it!! Thanks again.
