### ISSUE TITLE
[question] CMake: How to properly handle transitive dependencies INTERFACE_COMPILE_DEFINITIONS ?

### ISSUE THREAD

**Issue by NicolasIRAGNE** [conan-io/conan#10059]
Hello,

Conan version 1.42.1

I am currently trying to get our company software to build and I have run into a problem, and I'm not sure if it comes from a misunderstanding or not.

I have been able to reproduce the situation with simple examples using templates.
(For my actual packages I had been using cmake_find_package_multi but rewriting a simple example with CMakeDeps yielded the same problem)
So, I have two packages, ``foo`` and ``bar``. Package ``foo`` is a cmake_lib and ``bar`` is a cmake_exe. 

(The two packages have been created using ``conan new --template=cmake_[lib|exe]``)

foo/CMakeLists.txt:
```CMake
cmake_minimum_required(VERSION 3.15)
project(foo CXX)

add_library(foo src/foo.cpp)
target_link_libraries(foo PUBLIC FOODEFINE)
add_library(foo::foo ALIAS foo)

add_executable(test src/test.cpp)
target_link_libraries(test foo)

set_target_properties(foo PROPERTIES PUBLIC_HEADER "src/foo.h")
install(TARGETS foo DESTINATION "."
        PUBLIC_HEADER DESTINATION include
        RUNTIME DESTINATION bin
        ARCHIVE DESTINATION lib
        LIBRARY DESTINATION lib
        )

install(TARGETS test DESTINATION "."
        RUNTIME DESTINATION bin
        )

```

bar/CMakeLists.txt:
```CMake
cmake_minimum_required(VERSION 3.15)
project(bar CXX)

find_package(foo REQUIRED)

add_executable(bar src/bar.cpp src/main.cpp)

target_compile_definitions(bar PUBLIC BARDEFINE)

target_link_libraries(bar foo::foo)

install(TARGETS bar DESTINATION "."
        RUNTIME DESTINATION bin
        ARCHIVE DESTINATION lib
        LIBRARY DESTINATION lib
        )
```

``foo/src/test.cpp`` and ``bar/src/main.cpp`` both contain this main function:
```C++
int main()
{
    #ifdef BARDEFINE
    std::cout << "BARDEFINE is defined" << std::endl;
    #else
    std::cout << "BARDEFINE is not defined" << std::endl;
    #endif

    #ifdef FOODEFINE
    std::cout << "FOODEFINE is defined" << std::endl;
    #else
    std::cout << "FOODEFINE is not defined" << std::endl;
    #endif
}
```

Then building packages using ``conan create foo foo/1.0.0@usr/local`` and ``conan create bar bar/1.0.0@usr/local``

I have tried specifying both ``CMakeDeps`` and ``cmake_find_package_multi`` as generators, with the same result: the compile definitions are empty (other properties such as public headers look fine).

My expected output for running both resulting binaries would be:
```
/local/dev/cache/foo/1.0.0/py/local/package/b173bbda18164d49a449ffadc1c9e817f49e819d/bin/test
BARDEFINE is not defined
FOODEFINE is defined
/local/dev/cache/bar/1.0.0/py/local/package/5e331a8c961c9b958170db344adbaba2dc4ab7ea/bin/bar
BARDEFINE is defined
FOODEFINE is defined
```

Real output being:
```
/local/dev/cache/foo/1.0.0/py/local/package/b173bbda18164d49a449ffadc1c9e817f49e819d/bin/test
BARDEFINE is not defined
FOODEFINE is defined
/local/dev/cache/bar/1.0.0/py/local/package/5e331a8c961c9b958170db344adbaba2dc4ab7ea/bin/bar
BARDEFINE is defined
FOODEFINE is not defined
```

What am I doing wrong ? Is CMakeDeps not able to fetch the public compile definitions ?
Also, if I manually export the target inside my foo CMakeLists to a fooConfig.cmake (when using cmake install for example), the definitions are fine. However, I have not been able to tell my bar project to use this file.

Any links / documentation is welcome, I am fairly lost.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by NicolasIRAGNE** [comment]
I have missclicked and accidentally published the issue before finishing writing it and I cannot figure out how to delete it. I am currently editing it to finish my question. Sorry!

Edit: done 
Maybe I should have submitted this as a bug report ? I am not sure of what I am doing so I might as well just be using everything wrong so idk

**Comment by memsharded** [comment]
Hi @NicolasIRAGNE 

I am very sorry this was not responded back then, sometimes it happens when we are overwhelmed. We are trying to do some house-keeping and just seen this old question.
I guess you either managed to workaround or solve it or left it. Please let us know if you need some help or have any further question, otherwise this will be closed. Many thanks.

**Comment by NicolasIRAGNE** [comment]
Hello,

To be fair, I kinda forgot what this was about.
I might get into conan again soon, so maybe I will reopen this if I remember.

**Comment by memsharded** [comment]
No prob, we are just trying to keep the repo issues a bit organized, if possible. 
Sure, if you come back to conan, create new tickets as necessary, thanks!

**Comment by johannesn** [comment]
We are experiencing the same problem. In our Conan package A we have a library, that is build with a target_compile_definition(... PUBLIC ...) and the value is not propagated to the conan package B with the dependency to package A.

**Comment by memsharded** [comment]
Hi @johannesn 

The specific ``target_compile_definition(... PUBLIC ...)`` inside a given package does not guarantee the propagation of the transitive dependency to the consumers, because that is an internal "build" detail of the package, specific to that build system, but Conan recipe does not read the CMakeLists.txt.

The way Conan makes aware the consumers of transitive dependencies is via ``traits``. Depending on the ``package_type`` and the requires ``traits`` the visibility of headers and linkage of libraries is propagated downstream.

If you want to open a new ticket for further information, I'd recommend to try the:
- ``conan new cmake_lib -d name=depa -d version=0.1``
- ``conan new cmake_lib -d name=depb -d version=0.1 -d requires=depa/0.1``
- ....

To define a problem and work from there. Thanks!

**Comment by johannesn** [comment]
Hi @memsharded 

Thanks for the clarification. I'm new to c++ and assumed, that the compile definitions are somehow part of the compiled files and therefore should be used, when including the conan package. 

The idea to compile only selected parts of your code feels strange to me. Especially if after compilation I cannot tell which parts were compiled into a file (e.g. library) and which were not. But that is not your concern. 

Thanks!
