### ISSUE TITLE
[package] libcurl/7.79.1: Conan target changed from CONAN_PKG::libcurl to CONAN_PKG::CURL

### ISSUE THREAD

**Issue by wbitesi** [conan-io/conan#10061]
The CONAN_PKG::libcurl changed to CONAN_PKG::CURL. The package is included using libcurl/7.77.1 => Previously the conan package name was used for the target.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: libcurl/7.79.1 (looks like other versions are affected as well)
  * Operating System+version: Windows 10/Linux Debian
  * Compiler+version: MVC GCC
  * Docker image: **conanio/gcc9**
  * Conan version: **conan 1.33.0 and with 1.42.0
  * Python version: **Python 3.8 and 3.9

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)

* Clear conan cache (rm ~/.conan/data) to enforce fresh cache
* Build minimal sample program (attachment conan-curl-target-issue.zip)

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Library curl found /home/wolfgang/.conan/data/libcurl/7.79.1/_/_/package/f0c7e3b6bfdf043d1e63070037417f374650f024/lib/libcurl.a
-- Library ssl found /home/wolfgang/.conan/data/openssl/1.1.1l/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libssl.a
-- Library crypto found /home/wolfgang/.conan/data/openssl/1.1.1l/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libcrypto.a
-- Library z found /home/wolfgang/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libz.a
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /home/wolfgang/src/tests/conan-curl-target-issue/build
-- Conan: Compiler GCC>=5, checking major version 10
-- Conan: Checking correct version: 10
-- Configuring done
CMake Error at CMakeLists.txt:8 (add_executable):
  Target "main" links to target "CONAN_PKG::libcurl" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
gmake: *** [Makefile:179: cmake_check_build_system] Error 1
```

</details
[conan-curl-target-issue.zip](https://github.com/conan-io/conan-center-index/files/7560916/conan-curl-target-issue.zip)
>

**Comment by czoido** [comment]
As @SSE4 pointed out the problem is that the cmake_multi generator still listens to set_property.
We will release a 1.42.2 with this fix ASAP.
Thanks a lot.

**Comment by czoido** [comment]
Conan 1.42.2 has just been released including this fix, please @wbitesi could you check that everything runs as expected now?
Thanks!

**Comment by wbitesi** [comment]
The fix worked and now my build are running as previously. Thanks for the fast fix @czoido !
