### ISSUE TITLE
Conan appears to ignore options. sdl:iconv=false is ignored when building with MiniGW64 on Windows.

### ISSUE THREAD

**Issue by silktown-software** [conan-io/conan#10066]
I am using mingw64 on windows with cmake and conan.

The build for libiconv fails with mingw64 on Windows 10. SDL has an option to compile SDL without libiconv support but this fails.

I am using the following `CMakeLists.txt`

```cmake
cmake_minimum_required(VERSION 3.10)

project(HelloSDL VERSION 0.1 DESCRIPTION "Hello SDL" LANGUAGES CXX)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(HelloSDL src/01_hello_sdl.cpp)

target_link_libraries(HelloSDL ${CONAN_LIBS})
```

my `conanfile.txt`

```ini
[requires]
sdl/2.0.16

[options]
sdl2:iconv=False

[generators]
cmake
```

I am using the following profile to build

```ini
[build_requires]
[settings]
    os=Windows
    os_build=Windows
    arch=x86_64
    arch_build=x86_64
    compiler=gcc
    compiler.version=11.1
    compiler.libcxx=libstdc++11
    build_type=Debug
[options]
[env]
```

I am compiling using the following command in bash

```
$ conan  install .. --build=missing --profile=../profiles/mingw64
```

Is there anything specific I am doing wrong?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
It is possible that the recipes in ConanCenter do not fully support mingw building. In general they will have much better support for Visual Studio, because they are built and tested for it in ConanCenter CI.

Said that, it seems you have a typo:
```
[requires]
sdl/2.0.16

[options]
sdl2:iconv=False
```

sdl!=sdl2. The name should match, please try that.

**Comment by silktown-software** [comment]
https://conan.io/center/sdl?tab=overview

`sdl/2.0.1.6` is the correct version according to this.

**Comment by memsharded** [comment]
``sdl2:iconv=False`` => ``sdl:iconv=False``

**Comment by silktown-software** [comment]
Tried that. Works. :D

Feel pretty dumb. Thanks for the help.

**Comment by memsharded** [comment]
> Feel pretty dumb. Thanks for the help.

Glad to help, those things happen 😄
