### ISSUE TITLE
[question] Which generator should I use to get env vars from `env_info` of requirements with 2 profiles?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#10075]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Which generator provides all `env_info` of requirements (not build requirements) with 2 profiles?
Because currently `virtualenv` has env vars of build context and `virtualrunenv` host context. But I don’t see vars from `env_info` of requirements in `environment_run.sh.env` generated by `virtualrunenv`, only bin folders in `PATH`, and lib folders in `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH`.

Basically I want to automatically inject custom env vars defined in env_info of my requirements before calling the debugger in my IDE.
For example, `moltenvk` recipe defines `VK_ICD_FILENAMES` env var (https://github.com/conan-io/conan-center-index/blob/8e04e32a5ace9f606a294e796eb3b18cbe1bf5c9/recipes/moltenvk/all/conanfile.py#L163). This variable is required at runtime when MoltenVK shared lib is not in a standard location (which is the case when using conan in a dev context), otherwise Vulkan loader cannot find it. The workaround is to copy `MoltenVK_icd.json` and `MoltenVK.dylib` in some deterministic subfolder of the build folder of the project and define myself `VK_ICD_FILENAMES` (to point to absolute path of `MoltenVK_icd.json`) before calling my debugger, which is not a pleasant and transparent integration of conan. I would like a generic setup.

**Comment by SpaceIm** [comment]
Might be a duplicate of https://github.com/conan-io/conan/issues/9529?

**Comment by SpaceIm** [comment]
So I understand that experimental `VirtualRunEnv` should be used here. But it would require update in `moltenvk` recipe (and bump min conan version to 1.35.0, since `self.runenv_info` seems to have been added in https://github.com/conan-io/conan/commit/36bec562423011d42a9b111c7f31292ae364a3c1), something like this (but not yet, this generator is not even documented so highly experimental I guess):

```python
        if self.options.shared:
            moltenvk_icd_path = os.path.join(self.package_folder, "lib", "MoltenVK_icd.json")
            self.output.info("Prepending VK_ICD_FILENAMES environment variable in host context: {}".format(moltenvk_icd_path))
            self.runenv_info.prepend("VK_ICD_FILENAMES", moltenvk_icd_path)
```

**Comment by SpaceIm** [comment]
Hum, there is an issue in `VirtualRunEnv` (on Macos at least), the separator of variables values added through `self.runenv_info` is a space instead of colon in the generated file:

```shell
export VK_ICD_FILENAMES="/Users/spaceim/.conan/data/moltenvk/1.1.0/_/_/package/c76e5beadb233b7dc95e80dd5526429209decd10/lib/MoltenVK_icd.json $VK_ICD_FILENAMES"
```

Also, unlike `virtualrunenv`, there is no declarative .env file generated anymore, just a script. But a script is not always convenient to integrate in IDE. Some of them don't provide a convenient way to call a script before each call of the debbuger, and it's not even guaranteed that this call will happen in the same context than debugger execution, so env vars would be lost. But some IDE accept a .env file with list of vars.

**Comment by memsharded** [comment]
The generator is documented: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html. Yes, it is experimental, I'd probably recommend Conan 1.42 to start using them (experimentally), as the interface changed a little bit.

You can explicitly inject environment in python memory with ``EnvVars.apply()`` method: https://docs.conan.io/en/latest/reference/conanfile/tools/env/envvars.html.

You need to: ``self.runenv_info.prepend_path("VK_ICD_FILENAMES", moltenvk_icd_path)`` (note the **_path**), to explicitly tell that this is a path and should be concatenated with the path separator.

Regarding .env files, they are not produced yet, but they could probably easy be produced too. We wanted to make sure that the core use case is working robustly before augmenting it with integrations like IDEs. However, if you want to suggest which IDE is reading and managing that file, we could have a look at some point.

**Comment by SpaceIm** [comment]
Thanks for the answer, indeed it's documented 😄 

VSCode is not an IDE out of the box, but with proper extensions it can almost become a complete C/C++ IDE.
The debugger configuration file of the C/C++ extension in VSCode can take a `dotenv` file with env variables to inject. Unfortunately, there is no way to automatically source a script before debugger execution in the same context (you can call a process before, it's called `preLaunchTask` I think, but it is executed in a different context, so it's useless here).
There is also another famous VSCode extension for debugging, CodeLLDB. Injecting a `dotenv` is not yet implemented but there is a request for it: https://github.com/vadimcn/vscode-lldb/issues/506

A `dotenv` file like this works fine (more or less same file than the one generated by `virtualrunenv`, except that `virtualrunenv` cannot handle custom variables from `package_info()`, and it shouldn't put double quotes around each path):

```shell
PATH="/Users/spaceim/.conan/data/sdl/2.0.16/_/_/package/7b0f138e3751c7da83c9bb7a5f64ce1ada006029/bin:/Users/spaceim/.conan/data/moltenvk/1.1.0/_/_/package/c76e5beadb233b7dc95e80dd5526429209decd10/bin:/Users/spaceim/.conan/data/libiconv/1.16/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/bin:/Users/spaceim/.conan/data/glslang/8.13.3559/_/_/package/8153fd8a21c01f4b80b344ba12ac5a04b8e19473/bin:/Users/spaceim/.conan/data/spirv-cross/20200917/_/_/package/f2a8c7a77a405cfd85b7f802d5300af965b673be/bin:/Users/spaceim/.conan/data/spirv-tools/2020.5/_/_/package/7c05b3c5f62c2771e78b00d9f98a2ab73454741c/bin:$PATH"
LD_LIBRARY_PATH="/Users/spaceim/.conan/data/sdl/2.0.16/_/_/package/7b0f138e3751c7da83c9bb7a5f64ce1ada006029/lib:/Users/spaceim/.conan/data/moltenvk/1.1.0/_/_/package/c76e5beadb233b7dc95e80dd5526429209decd10/lib:/Users/spaceim/.conan/data/vulkan-loader/1.2.154.0/_/_/package/7b834c10ae27572a72c5624286d7a695c8ae1794/lib:/Users/spaceim/.conan/data/vulkan-validationlayers/1.2.154.0/_/_/package/2518711998450b3fa88cfaeca8201b2240b9bb77/lib:/Users/spaceim/.conan/data/libiconv/1.16/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/lib:/Users/spaceim/.conan/data/cereal/1.3.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib:/Users/spaceim/.conan/data/glslang/8.13.3559/_/_/package/8153fd8a21c01f4b80b344ba12ac5a04b8e19473/lib:/Users/spaceim/.conan/data/spirv-cross/20200917/_/_/package/f2a8c7a77a405cfd85b7f802d5300af965b673be/lib:/Users/spaceim/.conan/data/spirv-tools/2020.5/_/_/package/7c05b3c5f62c2771e78b00d9f98a2ab73454741c/lib:$LD_LIBRARY_PATH"
DYLD_LIBRARY_PATH="/Users/spaceim/.conan/data/sdl/2.0.16/_/_/package/7b0f138e3751c7da83c9bb7a5f64ce1ada006029/lib:/Users/spaceim/.conan/data/moltenvk/1.1.0/_/_/package/c76e5beadb233b7dc95e80dd5526429209decd10/lib:/Users/spaceim/.conan/data/vulkan-loader/1.2.154.0/_/_/package/7b834c10ae27572a72c5624286d7a695c8ae1794/lib:/Users/spaceim/.conan/data/vulkan-validationlayers/1.2.154.0/_/_/package/2518711998450b3fa88cfaeca8201b2240b9bb77/lib:/Users/spaceim/.conan/data/libiconv/1.16/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/lib:/Users/spaceim/.conan/data/cereal/1.3.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib:/Users/spaceim/.conan/data/glslang/8.13.3559/_/_/package/8153fd8a21c01f4b80b344ba12ac5a04b8e19473/lib:/Users/spaceim/.conan/data/spirv-cross/20200917/_/_/package/f2a8c7a77a405cfd85b7f802d5300af965b673be/lib:/Users/spaceim/.conan/data/spirv-tools/2020.5/_/_/package/7c05b3c5f62c2771e78b00d9f98a2ab73454741c/lib:$DYLD_LIBRARY_PATH"
DYLD_FRAMEWORK_PATH="$DYLD_FRAMEWORK_PATH"
VK_ICD_FILENAMES="/Users/spaceim/.conan/data/moltenvk/1.1.0/_/_/package/c76e5beadb233b7dc95e80dd5526429209decd10/lib/MoltenVK_icd.json:$VK_ICD_FILENAMES"
VK_LAYER_PATH="/Users/spaceim/.conan/data/vulkan-validationlayers/1.2.154.0/_/_/package/2518711998450b3fa88cfaeca8201b2240b9bb77/res/vulkan/explicit_layer.d:$VK_LAYER_PATH"
```

And on Windows:

```
PATH=C:\Users\spaceim\.conan\data\sdl\2.0.16\_\_\package\2b67e0983eee19fe2c9d0170ca245700b6ddb38d\bin;C:\Users\spaceim\.conan\data\vulkan-loader\1.2.198.0\_\_\package\314e6a85a9fbfe74d7936103986de73f2c8a8665\bin;C:\Users\spaceim\.conan_short\391909\1\bin;%PATH%
VK_LAYER_PATH=C:\Users\spaceim\.conan_short\095dc4\1\bin;%VK_LAYER_PATH%
```

My goal is to achieve non-intrusive and smooth integration of conan + CMake in VSCode:
- eventually one call to conan install managed by a generic "task" (a concept of VSCode), where some arguments like profile and build_type come from current "CMake Kits and Variant" (a concept of the CMake Tools extension).
- proper injection of build context env vars when CMake configure & build are called through CMake Tools extension (so that build_requirements are found and work fine when called by the build system). It could work if they implement https://github.com/microsoft/vscode-cmake-tools/issues/2265
- proper injection of host context env vars in host runtime processes (debugger, simple run of executables etc), so that you don't even need to import runtime files, or define yourself specific env vars.

Currently, the 2 last points are hard to achieve, I have workarounds, but it's tedious and not generic.

**Comment by johan-boule** [comment]
I've been reading through the documentation, and while virtualbuildenv and virtualrunenv seem to be mentionned, I don't know where Spacelm was able to find virtualenv. The latter seems to do what I want (i.e. acquiring cmake and running it as a build tool).

**Comment by SpaceIm** [comment]
`moltenvk` will be the first CCI recipe experimenting `self.runenv_info`: https://github.com/conan-io/conan-center-index/pull/8061/commits/6684a51ea85cdb9e4c12700189c529c93a5c8e77

**Comment by SpaceIm** [comment]
@memsharded 

To be sure to understand:
- `VirtualBuildEnv` aggregates `buildenv_info` variables of direct build_requirements + `runenv_info` of requirements (direct & transitive) of these build_requirements.
- `VirtualRunEnv` aggregates `runenv_info` of all requirements (direct & transitive).

It means that:
- when a recipe is pure library, env vars should go to `runenv_info`.
- when a recipe is a pure tool, env var should go to `buildenv_info`.
- when a recipe packages both tools & libraries, if an env var is in `runenv_info` (env var needed by the libraries), it may be required to also add it in `buildenv_info` if it's also needed by the tools (because tools link to the internal libraries of this recipe for example)? Question I asked for icu: https://github.com/conan-io/conan-center-index/pull/8287#discussion_r760696753
