### ISSUE TITLE
[feature] test package conanfile, `test_type` mechanism deprecation

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10073]
Conan has the `test_type` mechanism so we can specify in the conanfile of a `test package` the type of requirement that we want to test.
The `test_type` allows `test_type = "build_requires"` or `test_type="requires"` but that doesn't cover the current variety of requirements we could have in 2.0 with the requirements traits. 

So we want to introduce a mechanism in `1.X` to be prepared for the removal of `test_type` in Conan 2.0 to receive (injected) in the conanfile a variable with the reference to be tested (so in case the version is bumped we don't need to update the test_package for example) and then write the requirement explicitly, using that variable. Something like:

```
def MyTestPackage(ConanFile):

      def requirements(self):
          self.build_requires(self.testing_package_reference)

```

**Comment by memsharded** [comment]
This feature will solve https://github.com/conan-io/conan/issues/9606 too.
