### ISSUE TITLE
Improve gcc target detection

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#1007]
I was playing with a Raspberry pi (Ubuntu installed) when I noticed that conan auto-detectes the default setting `arch=armv7` based on `uname`, however the only compiler I've installed is `arm-linux-gnueabihf-gcc` so the actual architecture for compiled packages will be `armv7hf`.
There are two issues here:
- The auto-detection for default settings is not accurate which is inconvenient
- Binaries will be tagged with wrong architecture, causing problems for other users when shared

One solution is to check `gcc -dumpmachine` both for detection and when building, but parsing the output is opening a can of worms...

**Comment by lasote** [comment]
Sorry, we missed this issue:

> The auto-detection for default settings is not accurate which is inconvenient

Yes, it happens with special environments and it is almost impossible to cover all the cases. We really encourage the usage of profiles and `conan config install` feature and not relying on the autodetection, that should be considered as a "base", but it has to be reviewed once it is generated.

Thanks
