### ISSUE TITLE
[question] Environment variables in layout.ini

### ISSUE THREAD

**Issue by asanka424** [conan-io/conan#10081]
Hi. 
Is it possible to use environment variables in layout.ini file?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @asanka424 

It is not possible. However, I would recommend having a look at the new ``layout()`` method, that helps defining the package layout, and is the new proposal for editables, not the ``layout.ini``. It is still experimental, but I'd still recommend having a look.

**Comment by asanka424** [comment]
I am using conan workspace. so if I use layout() in conanfile.py, it will be only used in workspace mode?

**Comment by memsharded** [comment]
''layout()" is always used in recipes, and being in editable mode (which is what workspace do, should be enough.

Note however that ``conan workspace`` is a half-baked feature, it is not really matured, and we stopped working on it until the foundations were improved. Now the ``editable`` foundations are better with ``layout()`` but still workspaces didn't get enough priority to continue development, it will probably be in Conan 2.X, after 2.0 is out.

**Comment by asanka424** [comment]
ok. thanks for the update. I will take a look at layout()

**Comment by memsharded** [comment]
Closing this as outdated. Conan 2.0 dropped the layout.ini in favor of layout()  method.

Also Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
