### ISSUE TITLE
[bug] Package dependencies ignore my options

### ISSUE THREAD

**Issue by AlvaroFS** [conan-io/conan#10080]
I'm using `google-cloud-cpp` and `protobuf` which is at the same time a dependency in `google-cloud-cpp`. 
`protobuf` is built locally since it's missing from conan-center but `google-cloud-cpp` is downloaded since it is already there.
I'm using both of them as shared libraries but when I inspect the conaninfo.txt in the `google-gloud-cpp` package it is using `protobuf` as a static library.
It seems that the `package_id` doesn't takes into account the options of the package dependencies.

I think this is related to #9132

**Comment by franramirez688** [comment]
Hi @AlvaroFS 

Sorry for not answering this ticket 😞 
Closing this ticket as this problem should not happen in Conan 2.x anymore. It brings a new graph model which should avoid that scenario even without changing the `package_id_mode`.

Don't hesitate to reopen it if any problems/doubts come up again.
