### ISSUE TITLE
[bug] Conan search fails when searching for revisions in the special 'all' remote

### ISSUE THREAD

**Issue by MrPointer** [conan-io/conan#10097]
Seems like combining the `--revisions` and `--remote all` options in **conan search** can't be done, complaining that `all` is not a defined remote.

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux, Ubuntu 20.04, WSL
  * Compiler+version: ---
  * Conan version: 1.42.1
  * Python version: 3.9.5

### Steps to reproduce (Include if Applicable)

I'm not sure if this has something to do with disabling/removing the default conan repo in favor of a company-internal one (It has a proxy for external packages, i.e. it has an internet connection), but here's my **remotes.json** file for reference:
```
{
 "remotes": [
  {
   "name": "<remote>",
   "url": "https://<remote-url>/artifactory/api/conan/conan",
   "verify_ssl": true
  }
 ]
}
```

I've intentionally hidden the real remote name because it may be sensitive, company-specific information.

Given the above, whenever I'm trying to run `conan search <ref> --revisions --remote all` I get an error that remote `all` is not defined, but it's not happening without the `--revisions` option. In other words, `conan search <ref> --remote all` works fine.  
See further output below.

### Logs (Executed commands with output) (Include/Attach if Applicable)

I'm hiding the references as well, for the same reason I've hidden the remote name above. `<ref>` means a valid reference.

When executing `conan search <ref> --revisions --remote all`:
`ERROR: No remote 'all' defined in remotes`

When executing `conan search <ref> --revisions` and there's nothing in the cache:
`ERROR: Recipe not found: <ref>` - That's **expected!!!**

When executing `conan search <ref> --remote all`:
```
Existing packages for recipe <ref>:

Existing recipe in remote '<remote>':

    Package_ID: 007992511dcaed418239bdd20f63448fbac75310
        [options]
            debug: no
            strip: no
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 9
            os: Linux
        Outdated from recipe: False
  ...
  ...
  ...
```

Please ignore having `debug` as part of the options, I'm aware it's not the appropriate way to handle that.

**Comment by memsharded** [comment]
Hi @MrPointer 

I think this has already been fixed in Conan 2.0 (you can test the alpha Conan 2.0-alpha1, already available in PyPI), with ``conan list recipe-revisions zlib/1.2.11@ -r=*`` new cli. 

We are already focusing our efforts on 2.0, unless this is very problematic, I'd prefer to wait until 2.0. Can you manage to workaround this issue iterating the different remotes? Thanks!

**Comment by MrPointer** [comment]
@memsharded Thanks for the quick response! It's not a deal-breaker at all, I'll manage.  
That new cli looks promising, and the fact that the alpha version is already in PyPI is slick!  

Anyway, I guess we can close this now, thanks again!

**Comment by memsharded** [comment]
Thanks for the support @MrPointer!
Keep tuned for alpha releases, also the ``docs.conan.io`` already contains a 2.0-alpha version, at the moment almost empty, but we will gradually add new stuff there.
