### ISSUE TITLE
[bug] CMake unable to locate package configs if a user toolchain sets custom CMAKE_FIND_ROOT_PATH with package search mode ONLY

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#10103]
I've been trying to familiarize myself a bit with the new toolchain integration and set up a minimal project with a single dependency. Following the instructions in the documentation I used `CMakeDeps` to generate the package config for the dependency and `CMakeToolchain` for generating the toolchain file. Building the project with the native GCC works fine. In order to get cross-compilation working I then injected our own custom toolchain file by setting the `user_toolchain` property. This toolchain (which is based on a Yocto SDK) sets `CMAKE_FIND_ROOT_PATH` to the host and build scope sysroots in the SDK folder and also sets `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE` to `ONLY`.

This configuration breaks the build, CMake will report:

```
Could not find a package configuration file provided by "PkgA" with any
  of the following names:
  [...]
```

I've already stumbled across a similar problem in a totally different context, so I know what the root cause is: When `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE` is set to `ONLY` CMake will prefix *all* search paths with the sysroots, including any absolute paths. Conan injects all search paths for its own packages via the `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` variables. These will be prefixed as well, preventing the `find_XXX` macros from correctly resolving Conan-managed packages. The same problem exists with the other `FIND_ROOT_PATH` mode settings (program, library, include).

There are two obvious workarounds:

- Add the `NO_CMAKE_FIND_ROOT_PATH` to all `find_package` statements that should resolve to Conan-managed dependencies
- Set `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE` to `BOTH`

Both workarounds are impractical. Modified `find_package` statements are intransparent for the user and might have to be changed again if the dependency "ownership" changes. Setting the mode to `BOTH` could have unintended side effects, as we may be picking up packages from the build system scope instead of the toolchain sysroot, or masking configuration errors as a result.

Another workaround is to inject the paths for the dependencies and the path to the current list directory via the `CMAKE_FIND_ROOT_PATH` variable. The following modification in the `generate()` method fixes it for the current list dir only (still missing the Conan package directories, but it's enough to solve the problem that the CMakeDeps configs are not found):

```python
  tc = CMakeToolchain(self)
  tc.blocks["user_toolchain"].user_toolchain = self.user_info_build["toolchain"].USER_TOOLCHAIN_FILE
  tmp = tc.blocks["find_paths"].template
  tc.blocks["find_paths"].template = tmp + "\n set(CMAKE_FIND_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_FIND_ROOT_PATH})"
  tc.generate()
```

It should be discussed if it makes sense to always inject via the find root path instead of manipulating `CMAKE_PREFIX_PATH` and `CMAKE_MODULE_PATH`. However, I'm not sure if this could have other unwanted side-effects.

**Comment by SpaceIm** [comment]
There were many discussions in https://github.com/conan-io/conan/issues/9202 and issues/PR attached to this thread. https://github.com/conan-io/conan/issues/9427 is also connected in a sense.

Honestly I don't know yet how CMakeToolchain could be robust to all additional toolchains manipulating `CMAKE_FIND_ROOT_PATH_MODE_*` variables.

By robust I mean:
- find_package()/find_library()/find_file()/find_path() work out of the box, and only find files from host context.
- find_program() works out of the box, and only find programs from build context.
- regardless of `CMAKE_FIND_ROOT_PATH_MODE_*` which could be overridden.

**Comment by SpaceIm** [comment]
@jasal82 here is my proposal to improve the situation: https://github.com/conan-io/conan/issues/9427#issuecomment-993685376

> Another workaround is to inject the paths for the dependencies and the path to the current list directory via the `CMAKE_FIND_ROOT_PATH` variable.

Too fragile, it breaks `find_program()` (may find executables of host context instead of build context).

**Comment by lasote** [comment]
@jasal82 Did you find any fix/workaround since [this](https://github.com/conan-io/conan/pull/10186/files) was merged?

**Comment by jasal82** [comment]
Just tried again on 1.47.0 and the issue seems to be gone.

**Comment by lasote** [comment]
Then I'm closing this, feel free to comment or open a new one if some issue still remains. Thank all!
