### ISSUE TITLE
[feature] clear local cache of packages not on any remote

### ISSUE THREAD

**Issue by SvenStaehs** [conan-io/conan#10111]
We regularly want to remove packages that were only built locally from the local cache without losing the caching of packages pulled from remote.
Use cases:
- server builds that should start with a clean state without any chance of using a package built by some other server build on this agent
- developers who want to clean up their own cache from past local builds and free disk space
In both cases we want to keep the cache of already-released packages as they would otherwise be downloaded again from remote.

Suggestion would be to add a parameter to `conan remove`, maybe `--purge: purges packages from your local cache that are not available on any remote (anymore), including packages built locally and exported only to local cache. Cannot be used with --remote`

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @SvenStaehs 

While I understand the use case, it sounds a bit too specific to be provided built-in by Conan, at least at the moment. 
I am thinking that with the custom user commands and the published PythonAPI in 2.0, this might be very easy to implement, so please keep tuned for those capabilities too.

**Comment by memsharded** [comment]
Conan 2 has implemented a ``--lru`` flag that can remove packages not used in certain X time. This is a quite efficient way to keep the cache size under controlled while not removing packages that are frequently used.

The above case still seems a bit too specific, so I'd suggest implementing it in a Conan 2 custom command, which is a great feature. 

Closing as not planned, thanks very much again for the feedback.
