### ISSUE TITLE
[bug] [2.0] download_cache is not used

### ISSUE THREAD

**Issue by babariviere** [conan-io/conan#10115]
### Environment Details (include every applicable attribute)
  * Operating System+version: Nixos-21.11.20211122.263ef4c
  * Compiler+version: gcc (GCC) 10.3.0
  * Conan version: Conan version 2.0.0-alpha1
  * Python version: Python 3.8.2

### Steps to reproduce (Include if Applicable)

1. In `~/.conan2/conan.conf`, add `download_cache` option:
```conf
[storage]
download_cache = /tmp/conan-cache
```
2. Run `conan create .` on a package that download sources (`conan.tools.files.get`)
3. The cache is still empty

Also, note that these commands are not available with conan 2:
- `conan config get`
- `conan config set`

**Comment by memsharded** [comment]
Hi @babariviere 

Sorry this was not responded back then, this issue fell through the cracks :( Feel free to reopen or file a new one if you still have pending issues.

I hope that you found the issue, a couple of notes for other readers as well:

- Conan 2.0 configuration has moved to ``global.con`` and profiles ``[conf]``. Editing text files will not be done with Conan commands, too much of code, maintenance, support and docs to let users edit text files
- One of the potential issues that the cache is not caching things is if checksums are not provided. Only files that provide a checksum will be cached.

**Comment by babariviere** [comment]
Hi @memsharded,

No problem, I just found the way to do it. That's why I have closed the issue. But thanks for your response!

**Comment by memsharded** [comment]
Great to hear that, thanks for telling!
