### ISSUE TITLE
[Bug] Copying of .dll files under windows with $<TARGET_RUNTIME_DLLS:tgt> does not work

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#10120]
I have a CMake project where I link with `fmt::fmt` which is specified in the conanfile.py and installed and all cmake config files have been generated and beend used by CMake, so far all good. (I use `from conan.tools.cmake import CMakeDeps, CMakeToolchain, CMake`

I try to **copy all transitive dependencies** of my target `tgt` with https://cmake.org/cmake/help/git-stage/manual/cmake-generator-expressions.7.html#genex:TARGET_RUNTIME_DLLS

```cmake
add_executable(exe main.c)
target_link_libraries(exe PRIVATE otherTarget fmt::fmt)
add_custom_command(TARGET exe POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_RUNTIME_DLLS:exe> $<TARGET_FILE_DIR:exe>
  COMMAND_EXPAND_LISTS
  )
```

Strangely, the otherTarget.dll will be copyied to the Exe. But fmt::fmt `dll` is not copied, because something is either wrongly setup in the generated files? Conan however sets IMPORTED_LOCATION to the `.../lib/fmtd.lib` on the referencing targets of `fmt::fmt`, and I suspect CMake does not include it in `TARGET_RUNTIME_DLLS` because only `.dll` files are treated, ??

Does anybody know whats going on here?

**Comment by memsharded** [comment]
Quick question, are you aware of the ``imports()`` functionality in conan? You can easily do the copy of the dlls you want, with different configurations, directly in your conanfile.py or conanfile.txt

**Comment by gabyx** [comment]
Yes, I am aware, maybe we trigger that from cmake. 
But it would be nice since cmake supports this, why does it not work? I looked at the generated config files and I could only make sense of it by assuming the .dll is not set as IMPORTED_LOCATION (shared library fmt) but the .lib is. which is probably correct ...

**Comment by gabyx** [comment]
This seems to be a Bug because reading this https://gitlab.kitware.com/cmake/cmake/-/issues/22845
suggest that it needs `SHARED/STATIC` but `fmtTargets.cmake` uses only

```cmake
 if(NOT TARGET ${_LIB_NAME})
    # Create a micro-target for each lib/a found
    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
else()
    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
endif()
```

**Comment by gabyx** [comment]
The correct way would be in `cmakedeps_macros.cmake`:

```cmake
add_library(${_LIB_NAME} SHARED IMPORTED) # Depening on what it is...
set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_IMPLIB ${CONAN_FOUND_LIBRARY}) # WINDOWS only
set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION "..../.conan/data/fmt/8.0.1/_/_/package/de3fb398d17594c91d2197a6fe85db69711b417d/bin/fmtd.dll")
```

Would be nice if that could be fixed as soon as possible.

**Comment by gabyx** [comment]
Could we support by making a PR at  the right code location?

**Comment by xakod** [comment]
I faced the same issue with find_package generator. Sometimes recipes with CmakeDeps are broken and you need to use another generator.
