### ISSUE TITLE
[bug] conan info . --dry-build --graph=file.html build confusing vertical line

### ISSUE THREAD

**Issue by evandrocoan** [conan-io/conan#10121]
When build our project graph `conan info . --dry-build --graph=file.html`, I see a big line tying everything together. It makes quite confusing to understand if something depends or not on the other.

![image](https://user-images.githubusercontent.com/5332158/144484805-73e7fa47-8240-4138-9d09-38b791635b48.png)

When using the dot tool alternative, there is no such line and it makes quite clear to understand if something depends on another:
1. https://docs.conan.io/en/latest/extending/template_system/info_graph.html
1. `conan info . --dry-build --graph=file.dot`
1. `dot -Tpng file.dot > file.png`

![image](https://user-images.githubusercontent.com/5332158/144486300-395abc5e-c370-485f-ae03-b8778e503b7e.png)

Why the default `.html` graph have that big line tying almost everything together? How could I remove it?

### Environment Details (include every applicable attribute)
  * Operating System+version: Debian 9
  * Compiler+version: 6.3
  * Conan version: 1.42.2
  * Python version: 3.5

**Comment by memsharded** [comment]
Hi @evandrocoan 

That is not a random line, but a dependency among some of those packages depicted at the same level.

The ordering and layout of the packages is mostly controlled by the javascript library, and for some reason for a big enough number of packages, it doesn't do a great job.

Sounds very difficult to solve on our side. What is possible is to disable the "hiearchical mode" in the site, and from there, you can move freely all the packages, and that might help to see what is going on.

If there are some javascript experts out there that would like to improve this graph representation, it would be very welcome!

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2 with the improvements of the --format=html for `graph info` added in v2.2, which now looks miles better :)
