### ISSUE TITLE
[question] msvc version granularity

### ISSUE THREAD

**Issue by melak47** [conan-io/conan#10128]
MSVC versions are tracked as 192, 193, etc. with an additional compiler.update field (#10028).

How are recipes intended to handle this?
Let's say for example say we want to check for MSVC >= 19.29, because that corresponds to VS 16.11 when the /std:c++20 flag was added (roughly, it's kinda messy with VS 16.10 and 16.11 both shipping different versions of MSVC 19.29...).

We'd need to assemble a tools.Version or tuple of `(self.settings.compiler.version, self.settings.compiler.update)`, or something?

Or is the intent for conan-center recipes to just err on the side of caution and require VS 17 / MSVC 19.3X for C++20, and ignore the 19.2XY area of uncertain support?
(However even with 19.30, some C++20 features are still gated behind /std:c++latest before ABI stabilization...)

There are existing recipes on conan-center like `rangesnext`, which currently don't accept any VS version,
even though the code can work at least on MSVC 19.29 and later, with /std:c++latest...
but expressing that accurately in the recipe may not be possible.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I think something like ``if Version(self.settings.compiler.version) >= 192 and int(self.settings.compiler.update) >=9`` if this specific check is necessary would be good enough. You can also do things like ``if int(f"{self.settings.compilerversion}{self.settings.compiler.update}") >= 1929`` too.

Note, however, that in Conan 2.0 we are moving even more to the declarative/consumer definitions. If you want to use c++20, the profile should input ``settings.cppstd=c++20``, and in any case, if the compiler doesn't support it, Conan might raise an error. But it shouldn't be the responsibility of recipes to deduce c++ standard, only use it (this is a general design guideline, not an absolute truth, just some general ideas we are using while working in 2.0)
