### ISSUE TITLE
[question] Why go with ### instead of ##.# for the new msvc version format?

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#10130]
Up until [this change](https://github.com/conan-io/docs/pull/2314/files), the msvc compiler version format `##.#` matched the version format cl.exe prints to the screen when run with no arguments, which also matches what CMake prints to the screen during project configuration and what's stored in the `CMAKE_CXX_COMPILER_VERSION` variable. The conan versioning for gcc and clang are consistent in the version formatting that the compilers and CMake prints. Why the departure, especially since prior Conan versions already used `##.#`? It seems that the addition of the new `update` field could have still been done without changing the format of the `version` field.

Aside from the consistency arguments above, the previous format also made it easy to take the `CMAKE_CXX_COMPILER_VERSION` CMake variable and use a simple regex to set `-s compiler.version` in a CMake-embedded `conan install` call. Now it'll take an extra manipulation, which is a shame since it was [so clean before](https://github.com/ssrobins/sdl2-example/blob/bfdeb37649186c007ea03d3c6385fdf87438cdcf/CMakeLists.txt#L35).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Please look: https://github.com/conan-io/conan/pull/10057 and https://github.com/conan-io/conan/pull/10028

The issues are:

- We need some reasonable default binary compatibility. Including all the digits is too much, cannot handle that in ConanCenter for example
- The versions need to be comparable by default, and they were not (see https://github.com/conan-io/conan/issues/10017)

We found no other way than doing this to satisfy these 2 criteria

**Comment by ssrobins** [comment]
Ok, thanks!
