### ISSUE TITLE
[question] Compiling autotools projects for use in msvc

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#10142]
I've recently noticed that some projects that make use of autotools as there build system have ways of using their autotools scripts to compile binaries for windows. There's an autotools project that I would like to create a conan recipe for but I can't find any good docs on doing this.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
There is some (possibly slightly outdated) example in: https://docs.conan.io/en/latest/howtos/makefiles.html

The new tools, prepared for 2.0 will be: https://docs.conan.io/en/latest/reference/conanfile/tools/gnu.html
