### ISSUE TITLE
[question] Profile with a [conf] toolchain file, but dependencies find wrong compiler [1.42.0]

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#10145]
I have a conan profile:

```ini
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++
compiler.version=12
os=Macos
os_build=Macos
[conf]
tools.cmake.cmaketoolchain:user_toolchain = {{ os.path.join(profile_dir, "../../toolchains/macos/clang-libstdc++.cmake") }}
```

where we use `CMakeToolchain` and `CMakeDeps` internally in the conanfile.py.
The `clang-libstdc++.cmake` is the toolchain on mac which defines llvm clang over `brew`.

When we run
```shell
conan create \
    -pr:b "ourprofile" \
    -pr:h "ourprofile" \
    -s build_type=Debug \
    --test-folder tests/package \
    --build=missing
```

The creating fails when building the requirement `fmt` for example, because it finds an other compiler (`apple-clang`).
I guess thats because `fmt` uses another generator and our profile needs to be more specific. If we **add** 
```ini
[env]
CC=/usr/local/opt/llvm/bin/clang
CXX=/usr/local/opt/llvm/bin/clang++
```
then `fmt` will pick up the right compiler and will match with `ourprofile`.

Is this really the way to do it? Sad, but the toolchain file only knows this knowledge about CC and CXX values ...
Thanks for the advice. We are grateful.

**Comment by memsharded** [comment]
This is expected, ``cmaketoolchain:user_toolchain `` is for ``CMakeToolchain``, but the ``fmt`` package in ConanCenter is not using ``CMakeToolchain`` yet. Recipes in conan-center-index will be modernized to new tools, but that will take some time.

**Comment by gabyx** [comment]
Ok, thanks. So is that the workaround for the moment. What do you suggest?

**Comment by gabyx** [comment]
We use overrides in conan profiles like
```
[conf]
mypackage*:tools.cmake.cmaketoolchain:user_toolchain = [ ... ]
```
for packages with cmake toolchain ot override and using another toolchain and
and
```
[env]
mypackage*:CXX=...
```
overrides to adjust for packages which fo not have a cmake toolchain.

I think thats the indented way of doing it.

**Comment by memsharded** [comment]
Yes, except the modern, recommended way to manage environment (compatible with 2.0) is ``[buildenv]`` instead of ``[env]``

**Comment by gabyx** [comment]
Thanks a lot we are not yet at version 2.0 and still need to do this.

**Comment by memsharded** [comment]
``[buildenv]`` has been in Conan 1.X for a long time already, no need to do 2.0 for it. It is the recommended way in 1.X too.
