### ISSUE TITLE
[feature] Remove or increase length limit for package version?

### ISSUE THREAD

**Issue by artem-ogre** [conan-io/conan#10144]
We have a setup for internal development of a library where git branch is part of the package version value.
Error when using conan 1.35.1 says:
```
ERROR: Error parsing lockfile '<...>': 
Value provided for package version, '<long version containing branch name>' (type Version), is too long. 
Valid names must contain at most 51 characters.
```
Is there a technical reason for such a strict limit? If there isn't, is increasing the limit or removing entirely an options? It imposes a restriction on conan usages.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @artem-ogre 

yes, there are 2 reasons: the first one was avoiding excessive long paths, as the channels, etc are reflected in folders in package storage. This could be more or less avoided, and the new Conan cache for 2.0 will no longer use paths in storage, but having the package reference fields controlled in Conan 1.X was absolutely necessary, to be able to store paths in Windows with less than 260 characters (including the whole path, not only the Conan reference, that would be 4 x 50 = 200 characters).

But servers do need to store the channel in DBs, and then do several operations like searches, on tables that can have many millions of entries, so it was important that those could be indexed and kept to a known, reasonable limit. And 50 was chosen. Now changing that would be complicated at least, if not directly breaking. We might try to do something for Conan 2.0, but it is not guaranteed that it will be possible.

**Comment by AbrilRBS** [comment]
Conan 2 has bumped the max length of name and version to 100 chars each, which we think should be more than enough in both cases :)
