### ISSUE TITLE
[question] How to load own python module in conanfile.py local to the conanfile.py

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#10152]
In my `conanfile.py` I load a python module in the `set_version` and `configure` and `build` call

**Structure**: 

```shell
- ./repo/
       |- conanfile.py
       |- src-folder-to-build
       |- python/mymodule/__init__.py  
```

**conanfile.py**
```python

def assertConanModule(file):
     ....

class Test(Conanfile):
   def set_version(self):
       assertConanModule(self) # load a python mymodule into self.module
       self.module.do_something(self)

   def configure(self):
       assertConanModule(self) 
       self.module.do_something2(self)

   def build(self):
       assertConanModule(self) 
       self.module.do_something3(self)
```

The question is how do I locate the pyhton module.
When `conan install` is executed inside `repo` I can use 

```python
def assertConanModule(file):
     sys.path.append(os.path.join(os.path.dirname(__file__), "python"))
     file.module = importlib.import_module("mymodule")
```

But when `conan create` is executed this does not work?
When a user is referencing this package as dependency and builds it because he/she invokes `conan install --build=missing`
how the recipe `conanfile.py` still locate the module in `assertConanModule` ?

Thanks for the help! Really appreciated.

**Comment by gabyx** [comment]
I am also questioning, how this can work:
[/home/developer/.conan/data/base/v9.9.9-dirty/demo/testing/export/
](https://docs.conan.io/en/latest/howtos/capture_version.html#how-to-capture-package-version-from-scm-svn)
when calling `conan create`. The `self.recipe_folder` contains no Git repo at this point??

**Comment by gabyx** [comment]
I got this now working by properly exporting the python module (`export()`)


The remainig question ist: Is it correct that, in order to access the files next to the conanfile.py in **all cases**, one needs to maintain the same relative folder structure to the conanfile in the `export()`  function.

Then one can use.

`self.recipe_folder/path-to-my-module` and load it. Correct?

**Comment by memsharded** [comment]
Yes, exactly, that is the key, the relative layout should be the same in local folder and when exported to cache in order to work correctly.

Quick question: are you aware of the ``python_requires`` functionality? It allows this and beyond (like for example, controlling via version bumping when recipes that uses such python_require should rebuild binaries or not)

**Comment by gabyx** [comment]
Thats nice, thanks, we will probably in a later stage maybee include this feature. 
We anyway have a common cmake-module every project includes as (git submodule) in their folder, and take the scripts needed from there, and also export them to make the conanfile selfcontaining.
Thanks for confirming the relative layout. So far it works very well here.

**Comment by memsharded** [comment]
Thanks for the feedback. Ok, then I am closing this issue as resolved, don't hesitate to re-open or file a new one if you have further questions.
