### ISSUE TITLE
[bug] `self.copy` in a repository with a symlink starts to self-recurse and lead to high cpu/mem usage

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#10155]
I am still trying to trigger this. 

The repository https://github.com/gabyx/conan-hang 
should at the end trigger the `self.copy` recursion. So far it does not:
with
`cd tests/a && conan export . demo/testing`

If seen already bug reports in this direction which might be caused really by this.
I could trigger it in my setup by doing `self.copy("asd")` with an argument which was not even sensical.
That alone already triggered the deadly self-recursion.

Maybe that function gives you a hint where the problem might lie.

**Comment by memsharded** [comment]
Sorry this was not responded back then.

``self.copy`` was removed and replaced by ``copy()``, so I am closing this ticket as outdated, please report against the new ``copy()`` if necessary.
