### ISSUE TITLE
[question] Package dependency not propagated

### ISSUE THREAD

**Issue by TimZoet** [conan-io/conan#10162]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

```
Windows 10
Conan 1.43.0
CMake 3.22.0
Visual Studio 2019
```

I am currently experimenting with Conan. When trying to build an executable which depends on a package which in turn depends on another package, the dependency is not propagated, causing linking errors (and include directories are also missing, though I imagine this is the same problem). [Here](https://github.com/TimZoet/ConanPackageTest) is a minimal repository with which I can reproduce the problem. Its contents are:

- package1: no dependencies, exports a single static library.
- package2: depends on package1, exports a single static library.
- application: depends on package2.

From the root of the repository I run the following commands to export the packages and generate the application project:

```
conan export package1 timzoet/stable
conan export package2 timzoet/stable
mkdir build && cd build
conan install -s build_type=Debug ../application --build=missing
cmake ..\application -G "Visual Studio 16 2019"
```

Open the solution and build to see the linking errors:

```
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Build started: Project: app, Configuration: Debug x64 ------
2>Building Custom Rule C:/Users/timzo/dev/tmp/conanpackagetest/application/CMakeLists.txt
2>main.cpp
2>package2.lib(lib.obj) : error LNK2019: unresolved external symbol "void __cdecl pkg1::func1(void)" (?func1@pkg1@@YAXXZ) referenced in function "void __cdecl pkg2::func1(void)" (?func1@pkg2@@YAXXZ)
2>package2.lib(lib.obj) : error LNK2019: unresolved external symbol "void __cdecl pkg1::func2(void)" (?func2@pkg1@@YAXXZ) referenced in function "void __cdecl pkg2::func2(void)" (?func2@pkg2@@YAXXZ)
2>C:\Users\timzo\dev\tmp\conanpackagetest\build\Debug\app.exe : fatal error LNK1120: 2 unresolved externals
2>Done building project "app.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Indeed, the linker input of the app project contains only `path\to\package2.lib`. No mention of package1 anywhere.

Now, I imagine this is either a problem in the CMake of package1 and/or package2, or a problem in the conanfile of package2. However, I've been unable to pinpoint what exactly goes wrong. Any help would be greatly appreciated.

**Comment by memsharded** [comment]
Responded in https://github.com/TimZoet/ConanPackageTest/pull/1, please let me know. Thanks!

**Comment by TimZoet** [comment]
Thanks very much for your help! I added some notes to your pull request, but this definitely resolved my issues.

**Comment by memsharded** [comment]
Great to know, thanks for telling!

**Comment by TimZoet** [comment]
I'll also leave the repo up. I definitely had some trouble figuring out the 'right' way of doing things, so others might be helped by it.
