### ISSUE TITLE
[question] How to pass options from test_package to package build?

### ISSUE THREAD

**Issue by imaciejjablonski** [conan-io/conan#10179]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- I'm using conan 1.43 binary on windows 10

Hi, I'm having trouble passing option values from test_package to package build when calling `conan create`.

My packaging scenario is I have a repository with code that is built with msvc, but some parts are used as firmware code built with custom compilers. I'd like to have one recipe for both, which I'm trying to achieve by adding compilers to `.conan/settings.yml` and additionally with option `fw_platform` .

Simplified `conanfile.py`
```python
class PackageConanFile(ConanFile):
    name = 'my_package'
    settings = 'os', 'compiler', 'build_type', 'arch'

    options = {
        'fw_platform': [None, 'platform_a', 'platform_b'],
    }

    def log_value(self):
        func_name = inspect.stack()[1].function
        logging.info(f"""{type(self).__name__ + "." + func_name}()
            fw_platform={str(self.options.fw_platform)}""")

    def config_options(self):
        self.log_value()

    def configure(self):
        self.log_value()

    def validate(self):
        self.log_value()

    def build(self):
        self.log_value()
```

Simplified `test_package/conanfile.py`
```python
class PackageTestConanFile(ConanFile):
    name = 'my_package_test'
    settings = 'os', 'compiler', 'build_type', 'arch'

    options = {
        'fw_platform': [None, 'platform_a', 'platform_b'],
    }

    def log_value(self):
        func_name = inspect.stack()[1].function
        logging.info(f"""{type(self).__name__ + "." + func_name}()
            fw_platform={str(self.options.fw_platform)}""")

    def config_options(self):
        self.log_value()

    def configure(self):
        self.log_value()

    def validate(self):
        self.log_value()

    def test(self):
        self.log_value()

    def build(self):
        self.log_value()
```

After calling `conan create . my_package/1.0.0@maciek/devel -o fw_platform=platform_a` from repo's root I get following log:
```
INFO:root:PackageTestConanFile.config_options()
            fw_platform=platform_a
INFO:root:PackageTestConanFile.configure()
            fw_platform=platform_a
INFO:root:PackageConanFile.config_options()
            fw_platform=None
INFO:root:PackageConanFile.configure()
            fw_platform=None
INFO:root:PackageConanFile.validate()
            fw_platform=None
INFO:root:PackageTestConanFile.validate()
            fw_platform=platform_a
INFO:root:PackageConanFile.build()
            fw_platform=None
INFO:root:PackageTestConanFile.config_options()
            fw_platform=platform_a
INFO:root:PackageTestConanFile.configure()
            fw_platform=platform_a
INFO:root:PackageTestConanFile.build()
            fw_platform=platform_a
INFO:root:PackageTestConanFile.test()
            fw_platform=platform_a
```

Could you explain why value of `fw_platform` is set in test_package, but in `package` I get `None`? 

As far as I understood `None` value allows the option to have no value. I'd like to keep it that way instead deleting option, because I want to use it on msvc scenario to specify platform simulation.

**Comment by memsharded** [comment]
Can you please try using ``conan create . my_package/1.0.0@maciek/devel -o my_package:fw_platform=platform_a``?

Options are per-package, and the package they apply to needs to be specified (there might be some wildcards, that can be used, but better be explicit). In any case, are you sure the ``fw_platform`` is not a subsetting? Maybe it is a subsetting of the ``os`` setting or something? If it is kind of project wide, and recipes using it in a dependency graph should have the same value for ``fw_platform`` or it won't work, then it sounds it should be a setting.

**Comment by imaciejjablonski** [comment]
Using `-o my_package:fw_platform=platform_a` produces inverse log, package gets value but test_package doesn't, but that's understandable now. So this means `settings` are passed between `test_package` and `package` but options don't? 

How to test the different configurations of packages when I have other options? I've got e.g. `with_some_module` and to test it in CI should I provide special profiles for testing that will have `my_package:with_some_module=True`?

`fw_platform` actually is more of a compiler subsetting which would be fine if it wasn't used to specify simulation built with `msvc`. Eventually, I could modify `msvc` in setting.yml as well.

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

Now the ticket is outdated, because how the options are managed has changed in Conan 2.
It is not recommended anymore that ``test_package`` defines options for the package, but it can read their values with ``self.dependencies["mydep"].options`` and act accordingly.

Closing the ticket as outdated, please create new tickets for any further question. Thanks for your feedback.
