### ISSUE TITLE
[question] Conan 1.42.2 vs 1.43.0 for cmake target names

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#10170]
Why does Conan 1.42 
produce for

```python
  def build_requirements(self):
      self.build_requires("gtest/1.11.0", force_host_context=True)
```
a target `Gtest::gtest` (with `find_package(GTest CONFIG REQUIRED)`)
while
conan 1.43 produces only `gtest`.

I dont get that why this changed?

**Comment by gabyx** [comment]
Does that break with 1.43 because:

https://conan.io/center/gtest?tab=recipe

```
        self.cpp_info.components["libgtest"].set_property("cmake_target_name", "gtest")
```
instead of `GTest::gtest` ?

**Comment by memsharded** [comment]
Yes, that is what is happenning. We had to do a breaking change in the ``cmake_target_name`` property, as it was causing too many struggles in the migration of legacy generators like ``cmake_find_package``. 

Please read in https://docs.conan.io/en/latest/conan_v2.html#new-properties-model-for-the-cpp-info-in-conan-2-0-generators

The idea:

- ``cmake_target_name`` now only for ``CMakeDeps``
- ``cmake_target_name`` is always an absolute target name like ``Gtest::gtest``, to make it more flexible
- legacy generators like ``cmake_find_package`` will only listen to ``.names`` field in ``cpp_info``
- We introduced back the ``.names`` in ConanCenter recipes that had removed it
- We are fixing the ``cmake_target_name`` in ConanCenter as quickly as possible

**Comment by gabyx** [comment]
Thanks a lot, for the info! 
Thats very good to know. As a suggestion, maybe, include that it breaks ConanCenter  also in the Changelog, so that you dont need to answer such question anymore. Maybe you can later drop, the mention in the Changelog, as soon as it is fixed.

**Comment by memsharded** [comment]
> Thats very good to know. As a suggestion, maybe, include that it breaks ConanCenter also in the Changelog, so that you dont need to answer such question anymore. Maybe you can later drop, the mention in the Changelog, as soon as it is fixed.

Sure! We are actually writing some more detailed explanations, that we wanted to link, probably tomorrow. But feel free to send PRs for this kind of things too, the docs are open source, so this can be contributed quickly and easily too, and that helps too.

**Comment by gabyx** [comment]
Jup!

**Comment by czoido** [comment]
There's a PR already open for gtest to fix targets: https://github.com/conan-io/conan-center-index/pull/8324
And the guide PR is already open as well: https://github.com/conan-io/conan-center-index/pull/8415

**Comment by gabyx** [comment]
https://github.com/conan-io/docs/pull/2326

**Comment by gabyx** [comment]
Is there a collecting ticket which makes ConanCenter compatible with 1.43.0 ? So I could include it in the status banner in 
conan-io/docs#2326

**Comment by memsharded** [comment]
Closing this ticket as outdated, seems solved too, but please don't hesitate to create new tickets if necessary for any further question. Thanks!
