### ISSUE TITLE
[question] self.in_local_cache is always True during `conan export-pkg`?

### ISSUE THREAD

**Issue by RolfBippus** [conan-io/conan#10173]
I am following up on #8776

While self.in_local_cache is True or False in the build() method, it is always True in the package() method when using `conan export-pkg`. This seems illogical, since the sources do do change places. And the working dir is not in the local cache even though self.in_local_cache is True.

This is very unfortunate, since I try distinguish the place of the build depending on this, using a special build cache for out place builds with our scons based build environment.

Now in package() I am unable to identify the correct build place to collect the compiled artifacts.

Any ideas?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @RolfBippus 

I wonder if you have checked the new ``layout()`` functionality, in which you can define both the ``self.cpp.source`` and ``self.cpp.build`` information (https://docs.conan.io/en/latest/developing_packages/package_layout.html#declaring-the-layout). It is still experimental, but getting better, and will be very important for moving to 2.0.

**Comment by RolfBippus** [comment]
Hi @memsharded !

Thanks for the quick reply!
However I probably should have put my question into a larger context, sorry for that.

What I am actually trying to do, is to use a dedicated build folder that depends on the package_id irrespective of whether or not  building in the local cache, locally using development commands or when a package is editable. 

The reason being, that e.g. in editable mode I want to be able to compile with different settings but making sure the compiled artifacts end up in distinct build folders. Apart from that we are always having issues with disk quota, that actually does not allow to have the build on the same drive as the local source, thus relative to the working dir.

Now, when building in the local cache, things are fine. Source folder, build folder and package folder are uniquely defined (using the package id) by conan.

In editable mode however I am stuck:
- `self.info.package_id()` works fine in generate() or the Generator I use to generate the build scripts for using SCons. I use this to set the build dir accordingly to an out of place build cache (if `in_local_cache` is False).
- calling build() the build is done and the compiled artifacts are in my build folder (absolute path, somewhere, if `in_local_cache` is False)

But what comes next?
1. what would be the way to let the consuming package know where the build was put?
2. what would be the way to let package() know where the build went?
    
Using layout, I was only able to set the build folder to a folder relative to the working dir. I addition, this needed to be settings agnostic, since I was not able to access the package id here. In the layout() method `self.info` seems to be undefined. 

And as said, in package if `in_local_cache` seems to be always True, not allowing for any distinction either.

Or is there a fundamental flaw in what I am trying to do?

Rolf

**Comment by memsharded** [comment]
> What I am actually trying to do, is to use a dedicated build folder that depends on the package_id irrespective of whether or not building in the local cache, locally using development commands or when a package is editable.

This is exactly the purpose of ``layout()``. Check the ``cmake_layout()`` implementation for example, how it defines a different ``cmake-build-debug`` (for ``self.folders.build``) or ``Release`` folder, based on the current settings. You can easily extend this to have a ``build-release-amrv6-static-asan`` folder. This folder will be mapped correct to ``self.build_folder`` for packaging, consumption and usage, and will also correctly work for ``editables``.

**Comment by RolfBippus** [comment]
Thanks again for the quick reply.

> "You can easily extend this to have a `build-release-amrv6-static-asan` folder"

Thanks, yes, this would be the current solution!

I just thought it might be nice to use the package id instead, so in case I e.g. add settings to a package I do not have to remind myself to change the layout() method to take the new setting into account. 

On the other hand, I could probably create my own hash from the current settings and requirements. However I assume that these would not be fully complete at this point (in the layout() method), since otherwise the self.info.package_id() could also be available. But sufficiently complete to identify the build anyway.

What I also tried is to use the `package_info()` method, since I found it is called when doing `conan install` for the consuming package.
```
def package_info():
    if not self.in_local_cache:
        self.cpp_info.include_paths.append( my_include_path(self.info.package_id()) )
        self.cpp_info.lib_paths.append( my_lib_path(self.info.package_id()) )
```
It seems(?!) to work fine, delivering the correct information in conanbuildinfo.txt of the consuming package.

Although maybe this might be too much of a workaround or a misuse of `package_info()`?

**Comment by RolfBippus** [comment]
> On the other hand, I could probably create my own hash from the current settings and requirements.

The call sequence seems to be 
1. layout()
2. requirements()
3. package_id()

- Is there a reason for not calling `requirements()` and `package_id()` before `layout()`?
- The layout should not be needed by the other two, or...?
- And when calling layout() after the other two would yield the possibilty to have all package id related info correctly available?!

**Comment by memsharded** [comment]
Hi all,

We are moving forward in a different direction:

- ``in_local_cache`` has already been removed in Conan 2.0 (released in alpha.3). There will not be a functional equivalent
- There is now a stronger local flow, with native build in the user folders (with new ``generate()`` and new tools in ``conan.tools.xxx`` space.
- If some user wants to customize any specific behavior in their recipes, the recommendation would be to control it with a user ``[conf]``. This way it is not a function of where the thing happens, but fully controlled by the user.

With these suggestions, I think this question can be closed.

**Comment by RolfBippus** [comment]
Thanks!. We will need to migrate to 2.0 at some (near) future point in time anyway. So just important to be aware of  some of the "workarounds" we did so far which will become obsolete (or impossible) in 2.0.
