### ISSUE TITLE
[feature] [2.0] Custom CMake executable for conan.tools.cmake.CMake

### ISSUE THREAD

**Issue by babariviere** [conan-io/conan#10177]
Previously, we could set the CMake executable using this environment variable: `CONAN_CMAKE_PROGRAM`.
This could be used to create wrapper for CMake to inject definitions for all packages depending on another one.

As an example, we currently have this wrapper for android-ndk: https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/cmake-wrapper

I think something similar to what's done in CMakeToolchain can be done:
```python
def package_info(self):
    # This is what use CMakeToolchain to use a custom toolchain file
    self.conf_info["tools.cmake.cmaketoolchain:toolchain_file"] = "path/to/toolchain.cmake"

    # To mimic CMakeToolchain, we can have this to set a custom CMake executable
    self.conf_info["tools.cmake:cmake_program"] = "path/to/cmake"
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I see, I guess that adding something like that in conf is possible, but is it really necessary? I mean, as long as you put the cmake executable inside the ``bin`` (cpp_info.bindirs) folder of the package, it will be automatically put in the PATH for consumers (via ``VirtualBuildEnv`` when used as a build require. So no need to do anything special here. Am I missing something?

**Comment by memsharded** [comment]
By the way, it also seems that everything that is set by that cmake-wrapper should be already done built-in in ``CMakeToolchain`` (and if it is not done, then that could be fixed and improved, the idea is that CMakeToolchain support this Android building natively)

**Comment by babariviere** [comment]
> I see, I guess that adding something like that in conf is possible, but is it really necessary? I mean, as long as you put the cmake executable inside the `bin` (cpp_info.bindirs) folder of the package, it will be automatically put in the PATH for consumers (via `VirtualBuildEnv` when used as a build require. So no need to do anything special here. Am I missing something?

In this case, won't you have to rename `cmake-wrapper` into `cmake`? Plus, `cmake-wrapper` would have to be aware of where the "real" CMake executable is located. (if I am not wrong)

> By the way, it also seems that everything that is set by that cmake-wrapper should be already done built-in in `CMakeToolchain` (and if it is not done, then that could be fixed and improved, the idea is that CMakeToolchain support this Android building natively)

Is it possible to pass down `ANDROID_NATIVE_API_LEVEL` and other CMake variables with the toolchain?
These variables should be put in the `self.buildenv_info`, right?

~Also, I may be wrong, but taking the example of android-ndk, the `package_info` is called via the `build` context instead of the `host` context. I can't get the host settings to have, for example, the API level. Is this the expected behavior?
I may have done something wrong.~
Nevermind. 😅

**Comment by memsharded** [comment]
The current CMakeToolchain implements this template:

```cmake
 # New toolchain things
        set(ANDROID_PLATFORM {{ ANDROID_PLATFORM }})
        set(ANDROID_STL {{ ANDROID_STL }})
        set(ANDROID_ABI {{ ANDROID_ABI }})
        include({{ ANDROID_NDK_PATH }}/build/cmake/android.toolchain.cmake)
```
The ``ANDROID_NATIVE_API_LEVEL`` is an alias for ``ANDROID_PLATFORM``, which is already being set, so all good, it should work as is. These vaules are defined from settings, not necessary to define them in the package (they work also with a system installed Android NDK.

**Comment by babariviere** [comment]
I currently have this to setup these variables:

```python
def package_info(self):
  self.conf_info["tools.android:ndk_path"] = self.package_folder
  if self.context == "host":
	  self.buildenv_info.ANDROID_PLATFORM = "android-%s" % self.settings.os.api_level
	  self.buildenv_info.ANDROID_TOOLCHAIN = "clang"
	  self.buildenv_info.ANDROID_ABI = self._android_abi
```

Is it the correct way? I have to check for the context to be able to get the correct `api_level`.

**Comment by babariviere** [comment]
I think I should take a closer look at the implementation of conan. 😓 
Thanks for the support!

**Comment by memsharded** [comment]
> I think I should take a closer look at the implementation of conan. 😓
Thanks for the support!

Well, this is pretty new, and all the docs are complicated now with both the previous/stable/legacy integrations and the new ones living together... don't worry, feedback is very welcome, keep it asking things! :)
