### ISSUE TITLE
[question] Upload based on lock file

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10182]
Is there a way to specify the packages (recipe and/or binaries) to upload based on a lock file? Currently, it seems like I need to specify individual references (and packages ids if I only want to upload specific packages) which can be tedious to find and execute. It looks like I can do a pattern for the references but my dependencies don't have a common pattern. Since the lock file has all the information already, it seems like it would be nice to say that I want upload this package's recipe and binaries, and the package for all the dependencies based on the current settings/profile.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by maikelvdh** [comment]
Looking for similar kind of solution in order to utilise even better parallel upload threads!

**Comment by memsharded** [comment]
I think we should first allow multiple references in the ``upload`` command. Then, there could be a way to extract references from the lockfiles, but sounds that maybe it shouldn't be directly coupled, lets see what it makes sense.

So this sounds doable, just I don't know about the time scope, certainly we can do it for 2.0, as the UI is being re-designed anyway, but I don't know if we will get the resources for Conan 1.X. I'd recommend at the moment a small script that parses the lockfile json and calls ``upload`` for every reference there.

**Comment by nichmj01** [comment]
FYI: I wrote a script to do what I wanted for now like @memsharded suggested. 

Here it is in case anyone might find it helpful: [upload_from_lock.py.txt](https://github.com/conan-io/conan/files/7849709/upload_from_lock.py.txt)

It seemed to work on my machine on Windows, but YMMV.

**Comment by memsharded** [comment]
We have been discussing this, the current status is:

- Lockfiles are still evolving. Conan 2.0 has changed the lockfiles a lot, so things will not be possible in the same way.
- It is likely that in 2.0 the "build-order" json files could be better candidates for upload information
- Conan 2.0 will have custom user commands, that will be perfect to develop user extensions and it will very easy to implement this.

So we will not consider this as a built-in feature at the moment, and some automation on the user side is necessary. When we learn after 2.0 and see user commands, we might re-evaluate. Closing this at the moment, thanks!
