### ISSUE TITLE
Platform-dependent options in conanfile.txt

### ISSUE THREAD

**Issue by bschindler** [conan-io/conan#1018]
Hi 

This is more of a question than an issue, but I didn't find anything about this in the docs, here we go: 

So currently we have this in our conanfile.txt: 
[options]
Boost:shared=False

Is there a way to make this option platform dependent? We would like to do static linking on windows and dynamic linking on linux (because .a libraries usually cannot be embedded in a shared library because they would need to be compiled with -fPIC).

**Comment by memsharded** [comment]
Some static libraries (and conan packages) have the fPIC option too, to be able to embed them in shared libraries, check: https://www.conan.io/source/libjpeg-turbo/1.4.2/imazen/testing

If you want a more expressive or conditional conanfile.txt, you can use different approaches:
- Use different conanfiles.txt, with different name for different platforms, use ``-f`` option in install
- Use a ``conanfile.py`` instead, then implement the logic in ``def configure()`` method. Something like: 
```python
 if self.settings.os == "Windows": 
       self.options["Boost"].shared=False
```
  You don't need to implement all the methods of the conanfile.

**Comment by memsharded** [comment]
HI @bschindler ,

Did the above tip helped? As a rule of thumb, when a conanfile.txt is not enough for what you want to do, just upgrade it to a conanfile.py and you will be able to do much more.

Closing the issue, as it seems nothing to do from our side, please reopen if necessary. Thanks!

**Comment by bschindler** [comment]
Sorry for getting back so late. Yes this solves my issue. Thanks
