### ISSUE TITLE
Cross-compiling with cmake produces "Detected a mismatch for the compiler version between your conan profile"

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#10188]
Hello

I have a small example project set-up to use conan packages for cross compiling with cmake.

Here's my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.10.0 FATAL_ERROR)
include(${CMAKE_CURRENT_LIST_DIR}/conan.cmake)

conan_cmake_install(
        PATH_OR_REFERENCE ${CMAKE_CURRENT_LIST_DIR}/conanfile.txt
        PROFILE_HOST ${CMAKE_CURRENT_LIST_DIR}/profile.armhf-gcc8
        PROFILE_BUILD ${CMAKE_CURRENT_LIST_DIR}/profile.amd64-gcc7
        BUILD missing
)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)

project(conan-test LANGUAGES CXX)

conan_basic_setup(TARGETS NO_OUTPUT_DIRS)
```

my host profile in profile.armhf-gcc8:
```
[settings]
arch=armv7hf
os=Linux
build_type=Debug

compiler=gcc
compiler.version=8.3
compiler.libcxx=libstdc++11

[build_requires]
linaro-gcc/8.3.0
```

my build profile in profile.amd64-gcc7:
```
[settings]
arch=x86_64
os=Linux
build_type=Debug

compiler=gcc
compiler.version=7.5
compiler.libcxx=libstdc++11
```

my project conanfile.txt:
```
[requires]

[generators]
cmake

[options]
```

I have removed all required packages from the conanfile.txt for simplicity....this does not change the error
I have packaged linaro-gcc 8.3 into its own package and used it in build_requires as shown above.

The conanfile.py for my linaro package looks like this:
```
from conans import ConanFile, tools
import os

class LinaroGccConan(ConanFile):
    name = "linaro-gcc"
    version = "8.3.0"
    settings_build = "os", "arch"
    description = "<Description of LinaroGcc here>"
    url = "None"
    license = "None"
    author = "None"
    topics = None
    exports_sources = "toolchain.cmake"

    def build(self):
        url = ("https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz")
        tools.get(url)
        
    def package(self):
        self.copy("*")

    def package_info(self):
        path = os.path.join(self.package_folder, "gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf")
        self.env_info.PATH.append(os.path.join(path, "bin"))
        self.env_info.CC = os.path.join(path, "bin/arm-linux-gnueabihf-gcc")
        self.env_info.CXX = os.path.join(path, "bin/arm-linux-gnueabihf-g++")
        self.env_info.SYSROOT = os.path.join(path, "arm-linux-gnueabihf/libc")
        self.env_info.CONAN_CMAKE_SYSROOT = os.path.join(path, "arm-linux-gnueabihf/libc")
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH = os.path.join(path, "arm-linux-gnueabihf/libc")
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM = "NEVER"
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY = "ONLY"
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE = "ONLY"
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH_MODE_PACKAGE = "ONLY"

        self.env_info.CFLAGS   = "-fPIC            -mfloat-abi=hard -O0 -ggdb -Wall -Wno-psabi -Wno-unused-variable -Wno-unused-value -Wno-parentheses -Wno-format -Wno-sign-compare -Wno-deprecated-declarations -fvisibility=hidden -rdynamic"
        self.env_info.CXXFLAGS = "-fPIC -std=c++11 -mfloat-abi=hard -O0 -ggdb -Wall -Wno-psabi -Wno-unused-variable -Wno-unused-value -Wno-parentheses -Wno-format -Wno-sign-compare -Wno-deprecated-declarations -fvisibility=hidden -rdynamic"
```

When I run cmake it detects my native gcc compiler instead of recognising the linaro compiler configured, and produces the error shown in the subject from conanbuildinfo.cmake.

The "funny" things is that if I start to include packages in the [requires] section of conanfile.txt such as boost and openssl they are fetched and compiled just fine. It seems that the compiler config provided to/by conan does not carry over to cmake. I thought that this was exactly what conanbuildinfo.cmake is there for.

Help would be appreciated.
Thanks

Rgds 
Klaus

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Yes, in this case it seems it is a limitation of the ``cmake`` legacy integration. You might just disable the compiler version check defining the ``CONAN_DISABLE_CHECK_COMPILER`` cmake variable in your CMakeLists.txt. 

The new integrations (CMakeToolchain, CMakeDeps) will not be doing this check, so this will not be an issue moving forward, as it can be disabled, probably not worth trying to figure out a fix (that doesn't seem easy, because ``cmake`` integration was created before the build-host context feature, and thus is is simply not thought and ready for that model).

**Comment by klausholstjacobsen** [comment]
Thank you for the quick response.
I was not aware that using the cmake generator is considered legacy.

I am still in the investigation phase, so changing track is not a problem for me....yet.
One important information that i did not include in the OP is that I wish to use conan as a package manager, but not for compiling my project code. I am using "plain" cmake to build the project, and wish (for now) to continue to do so.

Defining `CONAN_DISABLE_COMPILER` is not a solution, as the detected compiler mismatch is correct.
I am simply looking for a way that allows me to define the build toolchain/profile once for use in both conan and cmake afterwards. 

Defining the toolchain in a package and using `[build_requires]` works well for building the packages included by conan, but the toolchain does not automatically carry over to my cmake project for build my project code.

Will the new approaches (CMakeToolchain and CMakeDeps) be a better choice? I cannot seem to find any useful info in the documentation regarding my usage scenario. The documentations focuses solely on using these generator inside package conanfile.py files.

Rgds
Klaus

**Comment by klausholstjacobsen** [comment]
I have been looking in `CMakeToolchain`.
The way I understand it is that I can actually use this generator in my linaro-gcc package to generate a toolchain file that fits this package (point to gcc and g++ etc provided by this package), and then use that toolchain in my plain cmake project for building.

The fun however stops when adding CMaketoolchan into conanfile.py
```
from conan.tools.cmake import CMakeToolchain
from conans import ConanFile, tools
import os

class LinaroGccConan(ConanFile):
    name = "linaro-gcc"
    version = "8.3.0"
    settings_build = "os", "arch"
    description = "<Description of LinaroGcc here>"
    url = "None"
    license = "None"
    author = "None"
    topics = None
    exports_sources = "toolchain.cmake"

    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["MYVAR"] = "MYVAR_VALUE"
        tc.preprocessor_definitions["MYDEFINE"] = "MYDEF_VALUE"
        tc.generate()
...
```

Error:
```
ERROR: linaro-gcc/8.3.0: Error in generate() method, line 17
	tc = CMakeToolchain(self)
	AttributeError: 'tuple' object has no attribute 'get_safe'
```

Is my understanding of the correct way of using the CMakeToolchain generator correct?
What am I missing since it produces the above error? The code is copied directly from the documentation.

Rgds
Klaus

**Comment by franramirez688** [comment]
Hi @klausholstjacobsen 

I think it could be coming from running the command without passing both profiles: `build` and `host`.
Did you run the command with the parameters `conan .......... -pr profile.armhf-gcc8 -pr:b profile.amd64-gcc7`?

In my case, I ran your previous `conanfile.py` like:

```bash
$ conan install .
.....

Traceback (most recent call last):
  .......
  File "/conan/conans/client/tools/oss.py", line 614, in get_build_os_arch
    return conanfile.settings_build.get_safe('os'), conanfile.settings_build.get_safe('arch')
AttributeError: 'tuple' object has no attribute 'get_safe'

ERROR: 'tuple' object has no attribute 'get_safe'
```
Definitely, yes, it's not an elegant way to show it so I was wondering if this happened on your side as well.

Anyway, it'd be useful to see the complete traceback so you can get it running `conan config set general.verbose_traceback=1` and run again the failing command.

**Comment by klausholstjacobsen** [comment]
Yes, I always use the build and host profile approach. 
I think the problem came from having "settings_build" instead of "settings"

Rgds 
Klaus

**Comment by memsharded** [comment]
I am closing this ticket as outdated, it refers to the legacy CMake integrations and the compiler checks with ``CONAN_DISABLE_CHECK_COMPILER``, that no longer exist in Conan2.

Please create new tickets if necessary for any further question, thanks for your feedback.
