### ISSUE TITLE
[bug] `cmakedeps_macros.cmake` should use IMPORTED_IMPLIB on Windows

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#10181]
### Environment Details (include every applicable attribute)
  * Conan version: 1.43

# `cmakedeps_macros.cmake`:

Line 39:

Instead of this

```cmake
add_library(${_LIB_NAME} UNKNOWN IMPORTED) // unknown is not good here anymore.
set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
```

One should use something like this:
```cmake
add_library(${_LIB_NAME} SHARED IMPORTED) # Depening on what it is...
if(WINDOWS)
   set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_IMPLIB ${CONAN_FOUND_LIBRARY})
   set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY}/../lib/lib.dll)
else()
   set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
endi()
```

This is necessary to make `$<TARGET_RUNTIME_DLLS:tgt>` work correctly. 
- https://gitlab.kitware.com/cmake/cmake/-/issues/22845
- See Question: https://github.com/conan-io/conan/issues/10120

**Comment by memsharded** [comment]
> add_library(${_LIB_NAME} SHARED IMPORTED) # Depening on what it is...

That is the thing, it is not obvious what type it is. Conan doesn't have that information, as libraries are simply modeled by name, so it is something that CMake should provide. Anyone knows a robust way to deduce the library type based on ``CONAN_FOUND_LIBRARY`` var results?

Also, I don't fully understand ``/../lib/lib.dll`` there. How are we supposed to do that for every different library name out there? This should be generic, it is a macro that is run for every single package and library within the package.

**Comment by gabyx** [comment]
@memsharded : Ok true, I thought, Conan has the information at hand if its a shared lib or static? 
Conan really doesnt know what the package contains?
How do you mean, something what CMake should provide. You also find `CONAN_FOUND_LIBRARY` so couldn't you find a DLL on windows too?

**Comment by memsharded** [comment]
> Conan really doesnt know what the package contains?

No, because in the ``package_info()`` only the lib names (as they appear in -lmylib) are defined, like ``self.cpp_info.libs = ["mylib"]``. This was done to simplify the package creators work. Conan might have the ``options.shared``, but even if that is defined you cannot guarantee that all libs inside will be shared, because there are many packages that contains a mix of static and shared libraries. And other packages might not declare at all the ``shared`` option.

> How do you mean, something what CMake should provide. You also find CONAN_FOUND_LIBRARY so couldn't you find a DLL on windows too?

We find ``CONAN_FOUND_LIBRARY`` from something like "zlib", "poco" or "mylib". We don't know it is a dll, and that is what CMake does. And CMake manages to find the right artifact for it. So probably something that CMake could help with, if it nows the rules to resolve "poco" to "poco.dll" or "poco.lib" or whatever, then it should probably be able to tell you: this is a dll or a lib (I don't know if CMake contains a higher level functionality, rather than just parsing CONAN_FOUND_LIBRARY in the case it contains the full path including the extension)

**Comment by gabyx** [comment]
Ok, thanks for the input so far. 

I think one should use `find_file` (according to that solution: https://discourse.cmake.org/t/find-library-wont-find-dlls/4050).
I suggest the following:

- **Windows:**
  - `find_library` to search for the .lib as normal -> CONAN_FOUND_LIBRARY.
  - `find_file` to search for a `.[dll|DLL]` with same filename and probably at the same locations where `CONAN_FOUND_LIBRARY` has been searched. 
    - if something is found, the `IMPORTED_IMPLIB` is set to the `.lib` file and `IMPORTED_LOCATION` to the `.dll` file. and type `SHARED`.
    - if nothing is found: we set only `IMPORTED_LOCATION` and  type `UNKNOWN`.

- **All other systems (unix, etc):**
  -  `find_library` to search for the `name` as normal -> `CONAN_FOUND_LIBRARY`
  -  If `CONAN_FOUND_LIBRARY` has extension `.so|dylib` -> set type SHARED
  -  otherwise set type UNKNOWN.
  
I think that would at least be an improvement to what is done now.

**See FindGTest.cmake:**
FindGTest.cmake does just set [SHARED if they detect .dll](https://github.com/Kitware/CMake/blob/3930c354f8d3669234c783505bc84dfe7ee9dcdb/Modules/FindGTest.cmake#L124)
and then set the [IMPORTED_IMPLIB](https://github.com/Kitware/CMake/blob/3930c354f8d3669234c783505bc84dfe7ee9dcdb/Modules/FindGTest.cmake#L164)
At least it seams they only need to define [SHARED](https://github.com/Kitware/CMake/blob/3930c354f8d3669234c783505bc84dfe7ee9dcdb/Modules/FindGTest.cmake#L286
) on Windows.


If you point me to the direction where conan_cmakedeps.cmake is generated I could add the above behavior in a PR.
I am quite experienced with CMake at the moment.


Questions: Is it possible to package static and shared libs for the same `name` (e.g. zlib.so and zlib.a)
I think not right?

**Comment by memsharded** [comment]
Hi @gabyx 

Yes, seems that what you suggest would be the way of moving forward. I hope it doesn't introduce any new subtle issues, with CMake it is always difficult to know...

I think the point to introduce the modifications for this would be here: https://github.com/conan-io/conan/blob/8fe7623b929d17c7e6f7f40bdd74e8a9c59d0822/conan/tools/cmake/cmakedeps/templates/macros.py#L56

> Questions: Is it possible to package static and shared libs for the same name (e.g. zlib.so and zlib.a)
I think not right?

Yes, it is possible to package them. Also, ``self.cpp_info.libs = ["zlib.a"]``, for example, to force the file (it is very unusual, but I think it can happen, and some user might be doing it). So inside a package you can find different things, but maybe the consumer is using only the static. Lets say that for example, one user packages 1 single package binary for static + shared for some reason (because the native build system creates both at the time, and didn't want to repeat the build twice, and was not aware of ``build_id()``), and then uses the option ``shared`` to select which one, directly adding the extension. Not great, but it can happen.

**Comment by gabyx** [comment]
Thanks, we will probably really have a look into this and, see if we can adapt the cmakedeps_macros as described and at the same time try to not break to much stuff (which is probably not the case when done as above).
We will report back.

**Comment by madebr** [comment]
I'm currently working on a [rewrite of the SDL_image cmake script](https://github.com/libsdl-org/SDL_image/pull/189) and am also facing this issue: `$<TARGET_FILE_NAME:XXX>` does not work on conan generated targets.
Among others, SDL_image's cmake script checks the `IMPORTED_LOCATION` and `IMPORTED_IMPLIB` properties (on Linux/Windows) to support dynamic loading (=not linking to a dependency, but doing `LoadLibrary`/`dlopen`)


> > add_library(${_LIB_NAME} SHARED IMPORTED) # Depening on what it is...
> 
> That is the thing, it is not obvious what type it is. Conan doesn't have that information, as libraries are simply modeled by name, so it is something that CMake should provide. Anyone knows a robust way to deduce the library type based on `CONAN_FOUND_LIBRARY` var results?

CMake allows the following syntax:

```cmake
add_library(${_LIB_NAME} UNKNOWN IMPORTED)
```

**Comment by memsharded** [comment]
Hi @madebr 

Yes, we know that CMake allows that syntax, this is what the Conan current cmake generators (``CMakeDeps``, ``cmake_find_package``,...) are already doing:
```cmake
                if(NOT TARGET ${_LIB_NAME})
                       # Create a micro-target for each lib/a found
                       add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                       set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                       list(APPEND _CONAN_ACTUAL_TARGETS ${_LIB_NAME})
                   else()
```

We have done some progress in https://github.com/conan-io/conan/pull/11111, targeted for Conan 2.0 (the risk of breaking is too high), and we are starting to define the targets as SHARED/STATIC/UKNOWN depending on the declared package type. That will help to improve this, with an explicit model and not depending that much on automatic detection of the library types, which is more fragile.

**Comment by madebr** [comment]
Completely understand about introducing this in conan 2.0.

About the explicit model, when/if you want to add a function to autodetect the dll accompanying an import library:
- with mingw, you can use `dlltool --identify <implib>` to " Report the name of the DLL associated with <implib>".
- with MSVC, you can do `dumpbin /headers <implib> | findstr dll` (+ some post processing)

**Comment by madebr** [comment]
I wrote the following cmake code to detect the associated dll for import libraries, it should be trivial to port these to python to allow autocompletion of these fields (using some helper function)

```cmake
function(win32_implib_identify_dll DEST implib)
    cmake_parse_arguments(ARGS "NOTFATAL" "" "" ${ARGN})
    if (CMAKE_DLLTOOL)
        execute_process(
            COMMAND "${CMAKE_DLLTOOL}" --identify "${implib}"
            RESULT_VARIABLE retcode
            OUTPUT_VARIABLE stdout
            ERROR_VARIABLE stderr)
        if (NOT retcode EQUAL 0)
            if (NOT ARGS_NOTFATAL)
                message(FATAL_ERROR "${CMAKE_DLLTOOL} failed.")
            else()
                set("${DEST}" "${DEST}-NOTFOUND" PARENT_SCOPE)
                return()
            endif()
        endif()
        string(STRIP "${stdout}" result)
        set(${DEST} "${result}" PARENT_SCOPE)
    elseif(MSVC)
        get_filename_component(CMAKE_C_COMPILER_DIRECTORY "${CMAKE_C_COMPILER}" DIRECTORY CACHE)
        find_program(CMAKE_DUMPBIN NAMES dumpbin PATHS "${CMAKE_C_COMPILER_DIRECTORY}")
        if (CMAKE_DUMPBIN)
            execute_process(
                COMMAND "${CMAKE_DUMPBIN}" "-headers" "${implib}"
                RESULT_VARIABLE retcode
                OUTPUT_VARIABLE stdout
                ERROR_VARIABLE stderr)
            if (NOT retcode EQUAL 0)
                if (NOT ARGS_NOTFATAL)
                    message(FATAL_ERROR "dumpbin failed.")
                else()
                    set(${DEST} "${DEST}-NOTFOUND" PARENT_SCOPE)
                    return()
                endif()
            endif()
            string(REGEX MATCH "DLL name[ ]+:[ ]+([^\n]+)\n" match "${stdout}")
            if (NOT match)
                if (NOT ARGS_NOTFATAL)
                    message(FATAL_ERROR "dumpbin did not find any associated dll for ${implib}.")
                else()
                    set(${DEST} "${DEST}-NOTFOUND" PARENT_SCOPE)
                    return()
                endif()
            endif()
            set(result "${CMAKE_MATCH_1}")
            set(${DEST} "${result}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "Cannot find dumpbin, please set CMAKE_DUMPBIN cmake variable")
        endif()
    else()
        if (NOT ARGS_NOTFATAL)
            message(FATAL_ERROR "Don't know how to identify dll from import library. Set CMAKE_DLLTOOL (for mingw) or CMAKE_DUMPBIN (for MSVC)")
        else()
            set(${DEST} "${DEST}-NOTFOUND")
        endif()
    endif()
endfunction()
```
This is tested on mingw@Linux + msvc@Windows

**Comment by memsharded** [comment]
This was finally approached by https://github.com/conan-io/conan/pull/11111, and targeted for 2.0 (included in released alpha.7), using model (``package_type``, to be completed with ``cpp_info.properties`` if necessary) instead of files detection. Lets build on top of alpha.7 for this, thanks!
