### ISSUE TITLE
[feature] Have a convention in global.conf to specify max number of cores

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#10191]
Recently ``tools.build:jobs`` was changed to default to the maximum number of cores
Maybe it would be better to explicitly allow it, like ``tools.build:jobs=MAX_CORES``. 

This would also apply to ``core.download:parallel`` and ``core.upload:parallel`` (when implemented, not yet available)

**Comment by memsharded** [comment]
Lets try to use jinja for global.conf.

**Comment by franramirez688** [comment]
This issue was closed by #10687 and it'll be released in Conan 1.46.
Now, you'll be able to put the `MAX_CORES` in a Python-like format.

```
tools.build:jobs={{os.cpu_count()}}
```
