### ISSUE TITLE
[question] information on python_requires after install

### ISSUE THREAD

**Issue by RolfBippus** [conan-io/conan#10196]
Hi.

I am trying to write some convenience scripts on top of conan.
For this purpose I want to check all required packages and their availability as well as the complete install process.

Since I work a lot with editables, I want/need to make sure, no requirement points to an editable in case I forgot to remove it.
(I hope the workspace option will make this obsolete in the future).

Thus, after having done an install, I check the requires section of conaninfo.txt and remove all relevant editables adding them back after I am finished. Works fine.

However, I cannot find information on the python_requires packages, which are just as important, since they also contain our build environment.
Is there a way to obtain the necessary python_requires packages other than parsing the output of `conan install`?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
New ``python_requires`` are part of the ``package_id``, but they couldn't be added to the ``conaninfo.txt`` without breaking. They will be there in 2.0.

At the moment, it might be possible to get it from the json file rathern than the terminal output, I don't know if that is what you mean (using ``conan install --json=file.json``). There is also the possibility of using lockfiles and parsing the lockfile (which is also json)

**Comment by RolfBippus** [comment]
That sounds great. So I'll keep that in mind when 2.0 comes up.

I cannot find the info in the json file, but it is definitely in the lockfile! So I'll use that.

Thanks a lot!
