### ISSUE TITLE
Conan doesn't work correctly with Artifactory access-tokens when created for a group instead of a user.

### ISSUE THREAD

**Issue by tru** [conan-io/conan#10190]
### Steps to reproduce
* Create a group in artifactory
* give that group access to your conan repo
* create a access token for that group: `jfrog rt atc --groups conan-deploy --expiry 0 conan-deploy`
* add the returned token in `CONAN_PASSWORD` [environment variable](https://docs.conan.io/en/latest/reference/env_vars.html)
* try `conan search` -> it will fail

It works if you create a token for your artifactory user instead `jfrog rt atc` this can be used correctly.

**Comment by tapia** [comment]
I just reproduced your issue. It seems like an Artifactory bug. I'll open an internal issue with them and come back to you with their response.

**Comment by memsharded** [comment]
I'd recommend to file a support ticket for JFrog Artifactory for this, it seems it is in the server side, nothing to do from the Conan client.
