### ISSUE TITLE
[bug] exelinkflags for components are not properly escaped in CMakeDeps generator

### ISSUE THREAD

**Issue by Novakov** [conan-io/conan#10200]
### Environment Details
  * Operating System+version: Windows 10 x64
  * Compiler+version: arm-none-eabi-gcc 8.3.1
  * Conan version: 1.43.0
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)
1. Create from following recipe:
```
from conans import ConanFile

required_conan_version = '1.43.0'

class Package(ConanFile):
    name = 'my-pkg'
    version = '1.0.0'
    url = 'https://example.org'
    license = 'DOES_NOT_MATTER'
    description = 'MY_PKG'
    settings = 'compiler', 'build_type', 'arch'
    options = {}
    generators = 'CMakeDeps'
    requires = ()

    def package_info(self):
        self.cpp_info.components['component'].exelinkflags = ['-Wl,-undefined=_startup']
        self.cpp_info.components['component'].libs = []
        self.cpp_info.components['component'].includedirs = []
```
2. Create CMake project with Ninja generator consuming `my-pkg` package
3. Add executable linking to `my-pkg::component`:
```
find_package(my-pkg)

add_executable(test src/main.cpp)
target_link_libraries(test PUBLIC my-pkg::component)
```
4. Try to build using `ninja test`
5. GCC/LD reports: `arm-none-eabi-g++.exe: error: "-Wl,-undefined=_startup": Invalid argument`

### Logs
Executed command line (as seen by `ninja -v`):
```
arm-none-eabi-g++.exe  -Wl,--build-id=none -Wl,-gc-sections -g -mcpu=cortex-m3 -mfloat-abi=soft -mthumb \"-Wl,-undefined=_startup\" -o test.elf -Wl,--start-group   CMakeFiles/test.dir/src/main.cpp.obj -Wl,--end-group
```

Escaped quotes around `-Wl,-undefined=_startup` are interpreted by GCC and invalid option is reported. 

If `exelinkflags` is specified for root `cpp_info` (`self.cpp_info.exelinkflags =  ['-Wl,-undefined=_startup']`) generated command line is correct. In `my-pkg-debug-arm_cortex-data.cmake` following lines are generated:
```
set(my-pkg_my-pkg_component_LINKER_FLAGS_DEBUG
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:"-Wl,-undefined=_startup">
)
```

Quotes in last line are escaped by CMake and passed to GCC. If `exelinkflags` is specified for root `cpp_info` link flags are passed indirectly by variable and no extra quotes are added:
```
# in my-pkg-debug-arm_cortex-data.cmake
set(my-pkg_EXE_LINK_FLAGS_DEBUG "-Wl,-undefined=_startup")

# In my-pkg-Target-debug.cmake
set(my-pkg_LINKER_FLAGS_DEBUG
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${my-pkg_SHARED_LINK_FLAGS_DEBUG}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${my-pkg_SHARED_LINK_FLAGS_DEBUG}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${my-pkg_EXE_LINK_FLAGS_DEBUG}>")
```

### Suggestion
Main different between component and root link flags is passing by variable for root link flags. I suppose that generating something like this:
```
set(my-pkg_my-pkg_component_LINKER_FLAGS_EXECUTABLE_DEBUG "-Wl,-undefined=_startup")
set(my-pkg_my-pkg_component_LINKER_FLAGS_DEBUG
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${my-pkg_my-pkg_component_LINKER_FLAGS_EXECUTABLE_DEBUG}>
)
```

would solve this issue.

**Comment by lasote** [comment]
The PR has been merged and it will be released in `1.44`. Thank you so much for this contribution!
