### ISSUE TITLE
Specifying options on a required dependent

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1020]
How do I specify that the current recipe requires another one, but with specific options on the dependent?

I tried `options = TheDependent:MyOption=True`, but that generates an error

I can, of course, specify them in the install command line, but I want them hard-coded in the recipe.

**Comment by tamboril** [comment]
Never mind.  Figured out `self.options['TheDependent'].MyOption = True`.

**Comment by memsharded** [comment]
I think you should be able to do it in:

```python
default_options = "TheDependent:MyOption=True"
```
If you don't need conditional logic, that would be fine. If you are setting it dynamically, yeah, you need the way you figured.

I have added some docs to make it easier, thanks for pointing this: http://docs.conan.io/en/latest/reference/conanfile.html#options-default-options

**Comment by unzap** [comment]
> default_options = "TheDependent:MyOption=True"

@memsharded how the default_options would look like if there are multiple dependencies and each of those have certain options that are needed?


    default_options = {"TheDependent1:Option1": "A",
                       "TheDependent2:Option1": "A",
                       "TheDependent3:Option1": "A",
                       "TheDependent1:Option2": "B",
                       "TheDependent2:Option2": "B",
                       "TheDependent3:Option2": "B",
                       }

**Comment by uilianries** [comment]
Hi @unzap !

Your `default_options` is right for multiple dependencies. I didn't find any example on docs, so we need to add an example there.
