### ISSUE TITLE
One step build using CMake

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#1021]
We have been using conan in some of our projects for a few weeks and we are liking it. The major issue we are having is that we should always run `conan install .` before building a project. This becomes an issue with our dependencies when they are under heavy development. 

It would be really nice if there was a way to simply call cmake and then have cmake call conan internally to create the conanbuildinfo.cmake file. 

Is this something you have any plans for? Do you have any suggestions on how we could integrate conan with our cmake setup such that it becomes a one step build for a clean environment?

**Comment by memsharded** [comment]
Hi Ali,
Thanks for your comment. You mean, like this https://github.com/conan-io/cmake-conan?

This is on-going community effort, still experimental, but usable. It automatically calls ``conan install`` directly from cmake. Please have a look and tell me.

**Comment by AliAskari** [comment]
Yes, that's exactly what I was looking for. I will try it during the weekend and let you know how it goes. Thank you.

**Comment by memsharded** [comment]
It seems that this might no longer be an issue, so closing it. But please reopen or comment if necessary. Thanks!
