### ISSUE TITLE
[bug] conans.AutoToolsBuildEnvironment does not respect os_build and arch_build from settings

### ISSUE THREAD

**Issue by t-8ch** [conan-io/conan#10212]
### Environment Details (include every applicable attribute)
  * Operating System+version: ArchLinux current
  * Compiler+version: gcc 11.1.0
  * Conan version: Current git head ( 1.24.0-1085-g106e54c9 )
  * Python version: Python 3.10.1

### Description

I'm trying to use an i686 toolchain on a x86_64 system to build i686 binaries.
However the `AutoToolsBuildEnvironment` ignores the `arch_build` setting I configured and instead always uses `x86_64` as build_arch.

I could override it with `settings_build` but I think this could work out of the box.

It seems the code in `AutoToolsBuildEnvironment._get_host_build_target_flags()` is also not sure about the current behavior.
```py
          if hasattr(self._conanfile, 'settings_build'):
              os_build, arch_build = get_build_os_arch(self._conanfile)
          else:
              # FIXME: Why not use 'os_build' and 'arch_build' from conanfile.settings?
              os_build = detected_os() or platform.system()
              arch_build = detected_architecture() or platform.machine()

```

**Comment by memsharded** [comment]
Hi @t-8ch 

Thanks for reporting this.

At this point, the ``AutoToolsBuildEnvironment`` is being superseded by ``AutotoolsDeps`` and ``AutotoolsToolchain`` from ``from conan.tools.gnu``, which is already experimentally available in latest Conan 1.X versions, and will become the only supported one in Conan 2.0 (already in alpha.2). Furthermore the ``os_build`` and ``arch_build`` is also superseded by the cross-build model using "build" and "host" profiles, which has also been in Conan 1.X for almost 2 years now, and will be also the one to use in Conan 2.0.

Unfortunately, unless such bug is a regression or it is badly affecting a large number of users, it is unlikely that it will get priority enough to get some developer time to fix it.

**Comment by t-8ch** [comment]
@memsharded Thanks! Then I'll look into the using the profiles.
