### ISSUE TITLE
[question] build_requires with build and host profiles

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#10215]
I have a project where I am using separate build and host profiles to cross compile (using conan create).  My project uses cmake, so I included that in the build_requires section of the build profile.  I discovered today, that this has been using a system installed version of cmake instead of a conan version.  Conan appears to ignore the build requires in the build profile.

After doing some testing I discovered that if I include the build_requires in the host profile, then conan will then download and use the requested version of cmake.  I find this very confusing because I am wanting a cmake package that is specific to my build profile settings.  I'm not sure if this is a bug or expected behavior.

In the section on build/host context it says "The build context ... typically includes all the dev tools like CMake."  It seems odd to me that I would have to declare info for the build context in the host profile.  

How do I know what belongs in the build profile vs the host profile?  I can find examples of host profiles in the docs, but can't find any examples of build profiles.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jsallay 

>  My project uses cmake, so I included that in the build_requires section of the build profile.

Actually, to use cmake to build libraries and executables in the host context, you should put "cmake/version" as ``build_requires`` in the "host" profile, so it applies to host packages.

If your build_requires themselves do need "cmake/version" to be built from sources (lets say, you have a ``gcc/1.0`` package that wraps a compiler and such compiler is built with ``cmake``, then you would need to put ``cmake/version`` as ``build_requires`` in the "build" profile.

**Comment by jsallay** [comment]
Thank you for the clarification.  So is that to say, for "normal" application code, most of the build profile sections are not applicable and I can just use the default profile?  

I feel like the role of the build profile could be made clearer in the documentation.  I talked with a co-worker about the issue and he was just as confused as I was.

On the cross-compiling page it talks about build, host, and target platforms.  I do not believe (but could be mistaken) that these do map cleanly to the concepts of build and host profiles and this is where I believe that the confusion stems. As an example:
**Cross building**: when the build and the host platform are different, it requires a cross compiler running in the build platform that generates binaries for the host platform.

I specify the cross compiler in the host profile for the build platform.

I understand that you are trying to explain the gnu definitions for cross-compilation, I just think it would be helpful to provide some more information on what belongs in the host vs build profiles.

**Comment by AbrilRBS** [comment]
Closing now that dual profile has been the norm for a while (And required in Conan 2!), and the documentation better reflects its usages :)
