### ISSUE TITLE
CMakeDeps should use the module file name to create Find<pkg>.cmake variables

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#10224]
CMakeDeps is creating some variables in module mode using the name of the package. Instead of that, using the file name is probably more expected. Now, for example, for **libcurl**, it would generate `libcurl_FOUND` and `libcurl_VERSION`. Probably `CURL_FOUND` and `CURL_VERSION` is a bit more expected ([but not perfect](https://cmake.org/cmake/help/latest/module/FindCURL.html)). As commented in the linked discussion, it's impossible for Conan to address all the cases for the declared variables in the official CMake modules, but at least we can try to provide those.

Related to: https://github.com/conan-io/conan-center-index/pull/8294#issuecomment-993690510
and: https://github.com/conan-io/conan-center-index/pull/8425#issuecomment-993726762

**Comment by SpaceIm** [comment]
What about `<name>_LIBRARIES` and `<name>_INCLUDE_DIRS`? They were available in `cmake_find_package` but I don't see these variables in Find files generated by CMakeDeps when `cmake_find_mode` is `both`.
It's important for proper emulation of official Find files.
