### ISSUE TITLE
[question] How to prevent dependencies from being propagated?

### ISSUE THREAD

**Issue by sboehmann** [conan-io/conan#10225]
I have a recipe with a number of dependencies. Dependent projects now naturally link against these dependencies. But in this particular case I don't want that. Not even if someone uses `CONAN_LIBS` or the files created by a Conan generator.

In the `package_info` I have already set `self.cpp_info.libs = []` to not propagate the libraries of this recipe. 
But how can I additionally also remove all dependencies?

**Comment by franramirez688** [comment]
~Perhaps, what you need is to declare them as `build_requires`. Have a look at this section from the Conan docs: https://docs.conan.io/en/latest/devtools/build_requires.html?highlight=build_requires~

Sorry, I just read your case again and my previous comment is not the solution. Using the `build_requires` for requirements that you don't want to propagate is not recommended at all. That mechanism is only recommended to declare purely tool requirements as `cmake` one.

**Comment by SpaceIm** [comment]
You can eventually play with `private` keyword, but sparingly: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#requires

**Comment by franramirez688** [comment]
By the way, this problem will be solved in Conan 2.x. If you want more information or you would like to start playing with it, you can check this thread https://github.com/conan-io/tribe/pull/26

**Comment by memsharded** [comment]
This was solved time ago by new generators and Conan 2
