### ISSUE TITLE
[bug] MSBuildDeps doesn't handle build requirements properly

### ISSUE THREAD

**Issue by slietzau** [conan-io/conan#10222]
The propertysheets generated by the MSBuildDeps generator are not consistent. In the example below a sheet `conan_swig_build_release_x64.props` is generated with the following content:

```xml
    <Import Condition="'$(conan_pcre_props_imported)' != 'True'" Project="conan_pcre.props"/>
```
However the file generated by Conan is named `conan_pcre_build.props`. My guess whould be that this line is the problem, but I'm not familiar with the code. It's just a guess :)
https://github.com/conan-io/conan/blob/0abf295555e5b573236a55f32608dc42b2723f7b/conan/tools/microsoft/msbuilddeps.py#L305

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 20H2
  * Compiler+version: MSVC
  * Conan version: 1.43.1
  * Python version: Python 3.8.0

### Steps to reproduce (Include if Applicable)

Create a `conanfile.py` with the content below, then run `conan install . -if build -pr:b build_profile -pr:h host_profile`:

```
from conans import ConanFile
from conan.tools.microsoft import MSBuildDeps


class MyTool(ConanFile):
    name = "mytool"
    version = "0.0.1"
    author = "me"
    settings = "os", "build_type", "compiler", "arch"

    build_requires = "swig/4.0.1"

    def generate(self):
        if self.settings.os == "Windows":
            # see https://docs.conan.io/en/1.37/reference/conanfile/tools/microsoft.html#conan-tools-microsoft
            ms = MSBuildDeps(self)
            ms.generate()
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

Command log:
```
(.env) PS D:\tmp\conan\imports_swig> conan install . -if build -pr:b windows-x86_64-vs-15-md-release -pr:h windows-x86_64-vs-15-mdd-debug
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=15
os=Windows
[options]
[build_requires]
[env]
CC=cl.exe
CXX=cl.exe
Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
[options]
[build_requires]
[env]
CC=cl.exe
CXX=cl.exe
conanfile.py (mytool/0.0.1): Installing package
Requirements
Packages
Build requirements
    bzip2/1.0.8 from 'conan-center' - Cache
    pcre/8.45 from 'vector-3rdparty-prod' - Cache
    swig/4.0.1 from 'vector-3rdparty-prod' - Cache
    zlib/1.2.11 from 'conan-io' - Cache
Build requirements packages
    bzip2/1.0.8:5be2b7a2110ec8acdbf9a1cea9de5d60747edb34 - Cache
    pcre/8.45:fb5d59739d4edb77a97120db5ef26603b7eba696 - Cache
    swig/4.0.1:114824d3d83f85c63472a6e170fa1d3f4b9d621a - Cache
    zlib/1.2.11:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: D:\dev\.conan\data\bzip2\1.0.8\_\_\package\5be2b7a2110ec8acdbf9a1cea9de5d60747edb34\bin
zlib/1.2.11: Already installed!
pcre/8.45: Already installed!
pcre/8.45: Appending PATH environment variable: D:\dev\.conan\data\pcre\8.45\_\_\package\fb5d59739d4edb77a97120db5ef26603b7eba696\bin
swig/4.0.1: Already installed!
swig/4.0.1: Appending PATH environment variable: D:\dev\.conan\data\swig\4.0.1\_\_\package\114824d3d83f85c63472a6e170fa1d3f4b9d621a\bin
conanfile.py (mytool/0.0.1): Applying build-requirement: swig/4.0.1
conanfile.py (mytool/0.0.1): Applying build-requirement: pcre/8.45
conanfile.py (mytool/0.0.1): Applying build-requirement: bzip2/1.0.8
conanfile.py (mytool/0.0.1): Applying build-requirement: zlib/1.2.11
conanfile.py (mytool/0.0.1): Generator txt created conanbuildinfo.txt
conanfile.py (mytool/0.0.1): Calling generate()
*** The 'msbuild' generator is EXPERIMENTAL ***
conanfile.py (mytool/0.0.1): Aggregating env generators
conanfile.py (mytool/0.0.1): Generated conaninfo.txt
conanfile.py (mytool/0.0.1): Generated graphinfo
```

**Comment by memsharded** [comment]
I'd like to understand better how you are using swig inside MSBuild. With ``MSBuildDeps`` (and the new graph model), build_requires (which are being renamed to ``tool_requires`` in Conan 1.44) are intended to be used as pure tools or executables, in MSBuild something like:

```xml
 <PropertyGroup Label="UserMacros" />

            <ItemGroup>
            <CustomBuild Include="data.txt">
              <FileType>Document</FileType>
              <Outputs>data.output.swig</Outputs>
              <Command>swig ....</Command>
            </CustomBuild>
          </ItemGroup>
```

Then, transitive dependencies of ``swig`` should probably not be generated as property sheets. If there is a library intended to be linked in the consumer, then it shouldn't be used as a ``build_require``, but as a ``require`` (and property sheets will be generated).

Could you please explain a bit more about your expected usage of swig package within MSBuild? Thanks!

**Comment by slietzau** [comment]
Thank you for the quick response! It's good to know that there will be a distinction between `tool_requires` and `build_requires` (which I suppose will be used for build requirements in the host system in the future?).

Regarding the current usage:
Our solution is quite big and `swig` is only used in one project (out of ~50). Because we are in the early stages of adopting conan, we are not building the solution through conan. Instead developers will simply open the solution and work with it. Because of that, we cannot rely on the environment variables being manipulated by conan such that `swig.exe` is found by msbuild. Our idea was to use the variables defined by the property sheet to locate the swig binary. However including the property sheet does not work because the swig property sheet has a dependency on `pcre` and the property sheet referenced has a different name than the generated property sheet.

referenced: `conan_pcre.props`
generated: `conan_pcre_build.props`

I hope this makes the problem more clear. If you have a better idea how we can use the swig binary without using a `virtual_build_env`, please let us know.

On a different note: Is it working as intended, that the `swig` package (which is somewhat standalone), injects the whole dependency tree (`pcre`, `bzip2` and `zlib`) into the consumers? For me it'd make more sense if `swig` would declare it's dependencies as `build_requirements` with `host_context=True`.

**Comment by memsharded** [comment]
> On a different note: Is it working as intended, that the swig package (which is somewhat standalone), injects the whole dependency tree (pcre, bzip2 and zlib) into the consumers? For me it'd make more sense if swig would declare it's dependencies as build_requirements with host_context=True.

This is one of the things that I was interested in. In Conan 2.0, there are already mechanisms to not propagate the dependencies of swig to the consumers. In this case, it will be able to generate only the swig properties sheet, without any other dependency and it will work. That is assuming you are using only the executable, and there is not any kind of swig.lib library to link with, in that case, the transitive libraries would be required.

That is connected with:

> Our solution is quite big and swig is only used in one project (out of ~50). Because we are in the early stages of adopting conan, we are not building the solution through conan. Instead developers will simply open the solution and work with it. Because of that, we cannot rely on the environment variables being manipulated by conan such that swig.exe is found by msbuild. Our idea was to use the variables defined by the property sheet to locate the swig binary. However including the property sheet does not work because the swig property sheet has a dependency on pcre and the property sheet referenced has a different name than the generated property sheet.

I'll check if it makes sense to directly drop the build_requires dependencies, as they shouldn't be necessary for consumption, maybe it is possible and is aligned with current implementation.

**Comment by slietzau** [comment]
@memsharded Thanks for the response and that you are looking into this.

However, you didn't comment on the apparent bug in the existing code where the generated filenames (`conan_pcre_build.props`) don't match the names the generated files are referenced by (`conan_pcre.props`).

Is this bug tolerated because it requires a specific setup to trigger it? If that's the case, it looks like we'd have to write our own `swig_wrapper` that strips the dependencies or transition to `tool_requires` and Conan 1.44

**Comment by memsharded** [comment]
Hi @slietzau 

Yes, I was waiting for your feedback regarding: 

> I'll check if it makes sense to directly drop the build_requires dependencies, as they shouldn't be necessary for consumption, maybe it is possible and is aligned with current implementation.

Which follows:

> This is one of the things that I was interested in. In Conan 2.0, there are already mechanisms to not propagate the dependencies of swig to the consumers. In this case, it will be able to generate only the swig properties sheet, without any other dependency and it will work. 

So my question was: can we safely drop the transitive dependencies of "swig" when it is a build-require, so they don't generate a ``.props`` file at all (and it don't reference such .props file)?

I am going to assume yes, and I am trying that approach in https://github.com/conan-io/conan/pull/10350 for next 1.45 release. It should be safe to restrict the propagation now, and if in the future there is some more complicated use case that requires it, we will investigate how to do it.

**Comment by franramirez688** [comment]
Thanks for reporting the issue @slietzau 
The fix is going to be released at the next Conan 1.45.

**Comment by slietzau** [comment]
@memsharded Sorry for the misunderstanding. For the `swig` package it's safe to drop the transitive dependencies. I'd assume for most packages used as `tool_requires` this should apply aswell since it's a hassle to get all the DLLs into place on windows.

Thanks for providing a fix!

**Comment by memsharded** [comment]
> @memsharded Sorry for the misunderstanding. For the swig package it's safe to drop the transitive dependencies. I'd assume for most packages used as tool_requires this should apply aswell since it's a hassle to get all the DLLs into place on windows.
>


For a build-require that is linked dynamically with transitive dependencies, (imaging pcre.dll), this will be an issue, it will not work out of the box. But as at the moment, the default is link statically, and specially like tools like this, dynamic linkage has little advantage, I prefer to be more restrictive, and block always transitive dependencies, to have the basic/default use case working correctly, and we can address the shared transitive dependencies later.

>Thanks for providing a fix!

No prob, looking forward your feedback when 1.45 is released!
