### ISSUE TITLE
[question] How to force `def source(self)` to run again?

### ISSUE THREAD

**Issue by evandrocoan** [conan-io/conan#10228]
I am editing the recipe directly on `~/.conan/data/somelib/1.0.21/channel/stable/export/conanfile.py`
```
    def source(self):
        release_name = "%s-%s" % (self.name, self.version)
        tools.get("{0}/{1}.zip".format(self.homepage, release_name))
        os.rename(release_name, self.source_subfolder)
        os.system('ls -la')
        raise
```
I am fixing a broken package, but after downloading it (completion of the `source()` step), the configure step fails with `./configure: No such file or directory`. Then, I would like to run the `os.system('ls -la')` on the source step to see where the files are going. But now I edited my recipe, the source step is not run anymore and it just fails with `./configure: No such file or directory`. How can I re-run the `source()` step?

**Comment by memsharded** [comment]
Hi @evandrocoan 

> ~/.conan/data/somelib/1.0.21/channel/stable/export/conanfile.py

Recipes cannot be modified on the cache. The cache is read-only, and modifying files there is undefined behavior. Please avoid doing that.

The ``source()`` method is designed to run just once, and once the "source" folder is in the cache, it will never be run again. The only way to force the re-download would be removing the package, so please try to remove the package from the cache and do the ``conan create`` or ``conan export`` again.

**Comment by evandrocoan** [comment]
I was searching and I found this `conan source . --source-folder=tmp/source`: https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html
> The strategy here is that you’re testing your source method in isolation, and downloading the files to a temporary sub-folder relative to the conanfile.py. This just makes it easier to get to the sources and validate them.

It indeed downloads the package each time I call it (with a different/or nonexistent directory), so it should be the solution as this is what I am trying to do:
> In the previous examples, we used the conan create command to create a package of our library. Every time it is run, Conan performs the following costly operations:
> 1. Copy the sources to a new and clean build folder.
> 1. Build the entire library from scratch.
> 1. Package the library once it is built.
> 1. Build the test_package example and test if it works.

> But sometimes, especially with big libraries, while we are developing the recipe, we cannot afford to perform these operations every time.

**Comment by memsharded** [comment]
> It indeed downloads the package each time I call it (with a different/or nonexistent directory), so it should be the solution as this is what I am trying to do:

Oh, yes, completely, sorry I didn't realize that you were not aware of the local flow. Indeed, touching things in the cache is not allowed, but it shouldn't be necessary, because for development, the local flow is better. Specially now that we are adding the ``layout()`` functionality to define the location of things in the local developer folder, that helps a lot to simplify things. Furthermore, it will also allow to set local developed packages as ``editable`` so you can depend on them directly from other packages also in your local user folders. Check the docs in: https://docs.conan.io/en/latest/developing_packages/editable_packages.html
