### ISSUE TITLE
[feature] [2.0] Explicit test package reference only

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10237]
When develop (1.44) is merged:

- Remove test_type
- Remove automatic injection of the reference being tested
- Change the "conan new" templates to use the new variable `self. tested_reference_str`

**Comment by memsharded** [comment]
> Remove automatic injection of the reference being tested

I guess you mean the automatic injection of the ``require`` being tested, and keep the injection of the reference being tested

**Comment by memsharded** [comment]
Closed by #10240
