### ISSUE TITLE
[bug] CMakeToolchain: CMAKE_MSVC_RUNTIME_LIBRARY needs policy CMP0091 NEW

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#10239]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.43.0
  * Python version: the one in CI of CCI

### Steps to reproduce (Include if Applicable)

- Visual Studio profile with static runtime
- generate conan toolchain file
- call cmake (cmake >= 3.15) with this toolchain file and a CMakeLists in which `cmake_minimum_required()` is lower than 3.15

=> `CMAKE_MSVC_RUNTIME_LIBRARY` is ignored, runtime is still the default (/MD).

### Logs (Executed commands with output) (Include/Attach if Applicable)

see https://c3i.jfrog.io/c3i/misc/logs/pr/8389/6-configs/windows-visual_studio/fmt/6.0.0//a79a557254fabcb77849dd623fed97c9c5ab7651-test.txt

https://github.com/conan-io/conan-center-index/pull/8389#issuecomment-998705187

**Comment by memsharded** [comment]
Would it be enough with:

```diff
diff --git a/conan/tools/cmake/toolchain.py b/conan/tools/cmake/toolchain.py
index 28dc05803..e5745e7d5 100644
--- a/conan/tools/cmake/toolchain.py
+++ b/conan/tools/cmake/toolchain.py
@@ -98,6 +98,7 @@ class VSRuntimeBlock(Block):
             {% set genexpr.str = genexpr.str +
                                   '$<$<CONFIG:' + config + '>:' + value|string + '>' %}
         {% endfor %}
+        cmake_policy(SET CMP0091 NEW)
         set(CMAKE_MSVC_RUNTIME_LIBRARY "{{ genexpr.str }}")
         """)
```

Can the policy be set always, without any issue?

**Comment by SpaceIm** [comment]
> Can the policy be set always, without any issue?

I would say yes.

You can still think about `CMakeLists` manipulating `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` to replace MT/MD by MT/MD and expecting some policy, but anyway when you use conan you shouldn't care of these kind of logic (I mean that whether this logic succeeds or silently fails shouldn't matter because conan user expects runtime from profile to be honored and it will be guaranteed by `CMAKE_MSVC_RUNTIME_LIBRARY`).

**Comment by memsharded** [comment]
> You can still think about CMakeLists manipulating CMAKE_C_FLAGS and CMAKE_CXX_FLAGS to replace MT/MD by MT/MD and expecting some policy, but anyway when you use conan you shouldn't care of these kind of logic (I mean that whether this logic succeeds or silently fails shouldn't matter because conan user expects runtime from profile to be honored and it will be guaranteed by CMAKE_MSVC_RUNTIME_LIBRARY).

Yes, if you are using the ``conan_toolchain.cmake`` and you don't want this, probably you want to deactivate the respective block in ``CMakeToolchain``

**Comment by lasote** [comment]
@SpaceIm Can a `cmake_minimum_required(VERSION 3.15)` be part of the toolchain file? I would say no, but not sure looking at the docs.

**Comment by memsharded** [comment]
It seems it shouldn't?, as this could change the behavior of users CMakeLists.txt regarding many other policies, not just this one.

**Comment by lasote** [comment]
On the other hand, `CMAKE_MSVC_RUNTIME_LIBRARY` works since 3.15, so... is the toolchain working with <3.15?

**Comment by memsharded** [comment]
No, cmake version should be > 3.15 and the toolchain will only work for >3.15. 

But if you compile a project with CMakeLists that declares ``cmake_minimum_required(... 3.10)``, it will not work, even if you have cmake 3.15 running, and the project should work with it, because the with that ``cmake_minimum_required()`` the policy to listen to ``CMAKE_MSVC_RUNTIME_LIBRARY`` is not activated...

**Comment by lasote** [comment]
But, is `cmake_minimum_required(... 3.10)` at the project, "correct" once you use the toolchain to build?

**Comment by SpaceIm** [comment]
> But, is `cmake_minimum_required(... 3.10)` at the project, "correct" once you use the toolchain to build?

A project shouldn't care of min CMake version of a toolchain.

**Comment by lasote** [comment]
Not the project, but the toolchain HAS a minimum required version.

**Comment by SpaceIm** [comment]
I would say conan toolchain shouldn't set a minimum version, only POLICY it relies on. If a user toolchain set a minimum version, it's also fine, POLICY of conan toolchain will ensure features it relies on.

**Comment by SpaceIm** [comment]
oh, I missed something: conan toolchain doesn't check CMAKE_VERSION, maybe it should like CMakeDeps.
