### ISSUE TITLE
[feature] Add timeout waiting for lockfile

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#10231]
You may be doing an operation which needs to get a lock. If it can't get one it will wait and print a message. In automation, you probably don't want to wait forever and normally is a sign of something wrong. So it would be nice to be able to specify a timeout to wait for a package lock. An environment variable would be ok here. e.g `CONAN_LOCK_WAIT_TIMEOUT`

- [ X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
We have considered this, but there are 2 major issues:

- The time in which a C++ package can be building is simply too high. 20-30mins or even 1 hr happens frequently. 5-10 minutes will be very usual. Those times are basically untractable from a UX point of view, no timeout will help a user waiting for a lock. For automation in CI, it is typically possible to put a limit on jobs, so they are automatically killed and reported.
- Conan doesn't do many of these locks, but using a third party library, fasteners, and some are implemented at the system level (with file locks), so it might not be easy to put a timeout on those.

Finally, Conan 2.0 new cache has dropped the locks at this stage, as the new cache has been done from scratch and locks need to be also completely re-thought and re-designed. We don't even know what will be possible or what not.

**Comment by memsharded** [comment]
Cache file-locks have been removed at this moment in 2.0. Even if we will try to make the cache in 2.0 concurrent, I am closing this as outdated, referring to Conan 1.X. Thanks for the feedback!
