### ISSUE TITLE
[test] [2.0] Validate listing of packages in remote generated with Conan 2.0

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#10233]
When Conan 2.0 is available, users may want to try to generate new packages (new pkg ids) and upload them to an existing remote with packages of Conan 1.X that are already there (a scenario that is likely to happen in ConanCenter)

We should verify that Conan 1.X is able to list or ignore packages created with 2.0 without issue and maybe it is helpful that the client 1.X is able to identify and mark 2.0 packages (although it won't be able to consume them).

**Comment by memsharded** [comment]
This was implemented in the merge of https://github.com/conan-io/conan/pull/10692 to develop2 branch. 
Can be closed, client side seems to be ready to merge conan1 and conan2 binaries in the same server repo.
