### ISSUE TITLE
[bug] BazelDeps doesn't support Windows

### ISSUE THREAD

**Issue by photex** [conan-io/conan#10236]
Currently the generator for BazelDeps assumes a Posix style environment. 

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: msvc 2019 / 2022
  * Conan version: 1.43.2
  * Python version: 3.?

### Steps to reproduce (Include if Applicable)

Create a simple conanfile.txt that uses the BazelDeps generator on Windows.

Early attempts to fix this are at the PR #10235

**Comment by AbrilRBS** [comment]
This was fixed in Conan 1.47 but never closed, thanks a lot for taking the time to create a PR, we appreciated it :)
