### ISSUE TITLE
[feature] Unify patterns

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10248]
Review all application to see where Conan accept inputs with patterns and unify the behavior. Some of the "inconsistencies" detected right now:

- `--build`: Accepts * at any point of the string matching the reference, also the NAME, also the NAME/VERSION (without using *)
- `-o`: Accepts literal  "*" meaning "all", also NAME but not NAME/VERSION. You cannot use `foo*` or similar
- `-s`: Accepts * at any point of the string matching the reference, also the NAME, and also the NAME/VERSION (without using *)

The behavior should be: A valid reference or `fnmatch`.  That means `-ozlib:shared=True` is not valid anymore and it should be `-o "zlib/*:shared=True`). But `-s zlib/1.2.11:shared=True` would be still valid, as it is a valid reference.

**Comment by memsharded** [comment]
Try to remove the dependency to ``self.develop`` for the "consumer" patterns ``&``

**Comment by lasote** [comment]
Review the "!" pattern, it is requested.
Related:
https://github.com/conan-io/conan/pull/10197

**Comment by lasote** [comment]
Review also patterns in "conf" and "env"

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/10587
