### ISSUE TITLE
[question] platform-independent include_dir for conan packages

### ISSUE THREAD

**Issue by nilsnolde** [conan-io/conan#10246]
I'm sure this is a noob question, but for the life of me I couldn't find a ready answer.. 

I build python bindings to a c++ project, which has boost installed via conan. when I build & install that c++ project to then build the bindings with `setup.py` pip can't find the boost headers by default of course. I'll need to tell it where to find the boost include dir. which is easy enough manually, but I'd like a more robust CI-ready setup where I ideally retrieve the conan include_dir. 

I'm right now on windows and there it's at `C:\.conan\bc7df6\1\include`. is there a platform-agnostic way to get the include_dir for conan dependencies (like env var or so)? or I need to somehow include a conanfile.txt or import conan to setup.py?

**Comment by memsharded** [comment]
Hi @nilsnolde 

The way to get information for consumers is via generators and the ``generate()`` method.
There are built-in generators like ``-g json`` that will dump a json file, probably with a bunch of information, you might try it.

You can also try adding something like this in your ``conanfile.py``:

```python
def generate(self):
      include_dir = self.dependencies["boost"].cpp_info.includedirs
      # This is going to change in 1.45, at the moment includedirs is relative, so you might need too:
      package_folder = self.dependencies["boost"].package_folder
      # then, do whatever you want with that information, dump to a txt file, a py file...
```

This will be automatically called and executed when running ``conan install .``

**Comment by nilsnolde** [comment]
thanks a ton for the quick response @memsharded , as always!

hm, not sure how that makes me find out the conan include dir for libs when they were installed by dependencies of the project I'm working with. if you have the patience, I'll describe a little more:

this is the project: https://github.com/gis-ops/valhalla-py/blob/master/setup.py. it's wrapping valhalla (a [c++ library](https://github.com/valhalla/valhalla)) and expects it to be installed on the build system. when I build the valhalla dependency on the build system to install it, it pulls and installs its own `boost` dependency via conan. I added [this part](https://github.com/valhalla/valhalla/blob/bc4b2754cd022e394abba6bd9f4017e5f48f5bd3/CMakeLists.txt#L136-L159) to valhalla's cmake setup to do that with [this `conanfile.txt`](https://github.com/valhalla/valhalla/blob/master/conanfile.txt).

so it's valhalla which knows about the conan dependency, but not my downstream python wrapper. the relevant part of the setup.py is:
```python
if platform == "win32":
    if not VCPKG_ROOT:
        print("ERROR. Set the environment variable VCPKG_ROOT to the absolute path of the vcpkg root directory.")
        sys.exit(1)
    include_dirs.extend([
        r'C:\Program Files (x86)\valhalla\include',
        str(Path(VCPKG_ROOT).joinpath('installed', 'x64-windows', 'include').resolve()),
        r'C:\.conan\bc7df6\1\include'  # TODO: remove this once we know how to get conan's include dir
    ])
```

the last line is what I'd need to provide dynamically. are you saying that I'd need to provide a conan recipe for this python wrapper as well? then use the `json` generator which I can parse in the setup.py to get to conan's include dir? 

I was hoping for an easier way. I really only need the include dir, it's all header-only. not that familiar yet with conan, this just feels very basic to me and I wonder why I can't figure it out.. (apart from brute-force scanning directories or so)

**Comment by memsharded** [comment]
Ok, I think there are a few things here:

- You have a ``find_package(ZLib)`` above that code, that means that your CMakeLists will probably try to locate ZLib in your system, and will find it.
- If you later depend on Conan Boost package, it will bring a transitive dependency to ZLib Conan package, having 2 Zlibs there, might be problematic. You typically want to do the Installation of Conan packages first, then the ``find_packages()``
- You might want to use one of the more modern Conan generators like ``cmake_find_package`` (or better ``cmake_find_package_multi`` or to be prepared for the 2.0 future (already in alpha stage), the ``CMakeDeps``). These will generate ``boost-config.cmake`` files in your folder, so adding that folder to CMAKE_MODULE_PATH, CMAKE_PREFIX_PATH, should make the ``find_package(Boost)`` work transparently, you shouldn't need to be guessing about that include dirs.

Does this help? Probably I am missing something in your setup or expectations, but depending on Boost is easy, you shouldn't need to do that.

**Comment by nilsnolde** [comment]
right, very good point about order of configuration in the cmakelists.txt, thanks! 

the problem is not within cmake, it works quite well installing the boost header libraries I need to build the c++ project. the problem is that the python project, which wraps this c++ project, has no conan setup itself. but in order for the `setup.py` to build the `.pyd` or `.so` python extension, it still does need access to the boost headers from that c++ dependency. 

I'd need a cross-platform way to know the conan include directory inside the `setup.py` of a project which doesn't have any conan setup itself, e.g. by environment variable (or I need to have a conan setup for that project too, even if I don't actually use conan directly?). so that's where I'm stuck. I think I'm making this much more complex than it has to be..

**Comment by nilsnolde** [comment]
basically it comes down to: can conan be used as a generic package manager which installs libraries in generic locations (at least not machine/version dependent), so that projects, which are not conan-based/not using conan, can also use these libraries? 

or do all projects which want to use libraries from conan, need to have a conan setup? 

and even if I included conan somehow in the setup of the python project I actually wouldn't be sure how to use that either so that the setup.py&pybind11-based build would see the include dir of conan.

**Comment by memsharded** [comment]
Hi @nilsnolde 

> basically it comes down to: can conan be used as a generic package manager which installs libraries in generic locations (at least not machine/version dependent), so that projects, which are not conan-based/not using conan, can also use these libraries?

Not in generic, arbitrary, locations. But the location of the packages is well known, and can be provided when "conan install" in different and flexible ways, from generating "boost-config.cmake" with the right location, or with a custom ``generate()`` method you can put in your ``conanfile.py`` (just replace your conanfile.txt with a conanfile.py containing this code), and that you can write the location of boost in any file with any format that you want.

You might also want to use the ``imports()`` or ``deploy()`` or ``-g deploy`` functionalities to get a copy of the artifacts from the cache to your current user folder, when you execute "conan install".

> or do all projects which want to use libraries from conan, need to have a conan setup?

Not sure what you mean, if you want the libraries from conan, you should call "conan install" to get them?


> I'd need a cross-platform way to know the conan include directory inside the setup.py of a project which doesn't have any conan setup itself, e.g. by environment variable (or I need to have a conan setup for that project too, even if I don't actually use conan directly?). so that's where I'm stuck. I think I'm making this much more complex than it has to be..

You can do it, as long as it executes after the "conan install", that will give you the location of the packages. Or try to use one of the imports/deploy strategies above? In any case, it seems that this should execute after Conan has installed the packages, so it seems that it is not possible in your case execute the "conan install" inside cmake, because that happens after the setup?

**Comment by memsharded** [comment]
Conan 2.0 now has deployers, that can definitely put libraries in arbitrary locations, see: https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html

I am marking this question as staled, it will be closed soon if you don't have any further question, many thanks!
