### ISSUE TITLE
Configure firewall proxy to Conan build system

### ISSUE THREAD

**Issue by alexaagithuber** [conan-io/conan#10242]
I am trying to compile a SDK released on GitHub to integrate Alexa skills. GitHub link of the SDK is: https://github.com/alexa/alexa-auto-sdk

Readme says that SDK can be compiled using their builder tool which is based on Conan build system. Since my system works under a firewall, I will have to provide proxy config to bypass it for the builder tool to work.

I tried adding in ~/.conan/.conan.conf, but it does not work. I also did not find any documentation on how to configure proxy so that dependencies are downloaded by the package manager.
Can someone please help me where do I add the proxy configuration for Conan build system.

**Comment by lasote** [comment]
Hi, yes, the way to configure the proxies is at the [conan.conf at ~/.conan](https://docs.conan.io/en/latest/reference/config_files/conan.conf.html#proxies) 

Could you paste here some traces to see at which point is the Alexa build failing?

**Comment by alexaagithuber** [comment]
Following is the error thrown:

ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

**Comment by alexaagithuber** [comment]
And I have specified the proxy config under [proxies] in ~/.conan/conan.conf.
One interesting thing is, conan inspect poco/1.9.4 works and prints the inspection log. Since conan inspect works, I am sure my proxy config is correct.

**Comment by lasote** [comment]
I would need more lines to see the context of the build process:

> ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

**Comment by alexaagithuber** [comment]
There are no much logs printed other than the above. I'm not quite sure on the information that might help you to further triage this issue.
This issue is easily reproducible where you can git clone the Alexa SDK from https://github.com/alexa/alexa-auto-sdk and run the below command:
.builder/build.py -p linux --arch=x86_64

Note: Your system must have proxy enabled for Conan to hit this issue.

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

I am closing this ticket as outdated now, as Conan 2 defines new ``global.conf`` mechanism to defines things like proxies. So please create an updated ticket for this against Conan 2.X if necessary with the following details:

- ``conan version`` output details
- the necessary files like ``conanfile`` to reproduce the issue
- the exact ``conan`` commands that reproduces the issue
- The full output of that ``conan command``
- The defined ``global.conf`` configuration.

Many thanks for your feedback.
