### ISSUE TITLE
[question] Conan 2.0 not working with old released packages?

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#10245]
Hi,

The documentation here: https://docs.conan.io/en/latest/conan_v2.html
mentions e.g. that:

> - Use the from conan import ConanFile import instead of the legacy from conans ... 
> - Use generators and helpers only from conan.tools.xxxx space. All the other ones are going to be removed.
> - Do not use self.deps_cpp_info, self.deps_env_info or self.deps_user_info. Use the self.dependencies access to get information about dependencies.

Does this mean that old conan packages (created during the 1.x era) can not be used anymore when people start using Conan 2.0?
Will the 2.x conan client throw an error (invalid import etc.) when running e.g. "conan search"/"conan info" from Artifactory?

If this is the case then consider  the following case:
- Release conan packages are created and uploaded to Artifactory and used by customers
- The recipes are part of the module .git repository + using: `revision_mode = "scm"`
- There is no "easy" way to rebuild the released conan packages, one would need to rebuild all past releases including the changes in the recipes for Conan 2.0 support, test those and prepare a new release (bump the patch level version) from each of those.
- Should the older releases be removed from Artifactory if Conan 2.0 is unable to install those packages?
- What if some customers are switching to Conan 2.0 with slower pace so we'd need to support both Conan 1.x and 2.x users at the same time?

I hope that backwards compatibility is supported by Conan 2.0 in the recipes so that older released conan packages published already  
 via Artifactory does not get broken?

**Comment by memsharded** [comment]
Hi @iiknd 

You can find more details here: https://github.com/conan-io/tribe/blob/main/design/013-migration-path.md

In short:

- There is a syntax in Conan 1.X latest that will be compatible with 2.0, but recipes should be updated in 1.X to use that latest compatible syntax, for example legacy generators will be removed, and only integrations from ``from conan.tools.xxxx`` will survive
- Conan 2.0 packages will have a different package_id than the ones in 1.X, the idea is that they will be able to co-exist in the same server repo (given that the recipe has been upgraded to a 1.X&2.0 compatible syntax), without collision.
- Conan 1.X and 2.0 will co-exist in time, also for us, as the migration of ConanCenter with +1100 recipes will take some time. Probably no user has a bigger repo than that to migrate
- Artifactory might need a couple of minor fixes (yet to be done) to provide the right support for 2.0. At the moment it is only possible to evaluate 2.0-alpha with ``conan_server``

**Comment by AbrilRBS** [comment]
Closing as answered now that Conan 2 has been going for a while. Note that in Conan Center Index, we had little trouble supporting both pipelines at once with the compatible syntax between both versions, and in general users at scale have not complained about the current approach :)
