### ISSUE TITLE
[feature] 'copy' method add 'recursive' parameter

### ISSUE THREAD

**Issue by bigcat26** [conan-io/conan#10251]
I need to package some header files from the source directory but I did'nt want any header files from sub-directories of that directory. It would be nice to add a 'recursive' paramater with default value 'true' to 'copy' method.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @bigcat26 

Is this for the ``package()`` method? You know that you can also do a direct ``shutil.copyxxxx`` (or any other Python copy function), using the ``self.build_folder`` and ``self.package_folder`` as source and target? If you are using CMake, using ``cmake.install()`` can also solve this for you.

**Comment by bigcat26** [comment]
Hi @memsharded 

Good, I'll have a try.
