### ISSUE TITLE
[question] CMakeDeps: COMPONENTS check?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#10258]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

It seems that config file generated by `CMakeDeps` doesn't perform any check among `COMPONENTS` in `find_package()`. Is it intended or not yet implemented? Seems to be intended, it's controlled by `check_components_exist` in CMakeDeps, False by default, really surprising: https://github.com/conan-io/conan/pull/9206#issuecomment-875514043.

To reproduce: In test_package of `poco` recipe:
- In `conanfile.py`, replace `cmake_find_package_multi` by `CMakeDeps`
- In `CMakeLists.txt`, add random COMPONENTS in `find_package()`: `find_package(Poco REQUIRED ${POCO_COMPONENTS} Foo Bar CONFIG)`
- Then call `conan create . poco/1.11.1@`, CMake won't complain during configuration of test_package.
With `cmake_find_package_multi`, it fails to find these random components (and it's the expected behavior): `Conan: Component 'Foo' NOT found in package 'Poco'`. It's worth noting that `cmake_find_package_multi` doesn't properly handle `OPTIONAL_COMPONENTS` (it fails also if an optional component is not found, which is not good).

I think that whether check among `<find_or_config_filename>_FIND_COMPONENTS` is performed or not should be controlled in `package_info()` of the recipe itself, not by downstream recipes which are not supposed to have this kind of control and may not know what is the good behavior, since in CMake it's an upstream decision to create config files with components checks (it's not the default but it's recommended: https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#generating-a-package-configuration-file).

Also I see that currently, when `check_components_exist`, COMPONENT is expected to be target name exactly (with the namespace), it's a bad default.

**Proposal**

COMPONENT name should be:
- by default: last string of `cmake_target_name` split by `::` (if it's not namespace, it should be `cmake_target_name`). `cmake_target_name.split("::")[-1]` should handle all cases.
- a new property (`cmake_component_name`?) should allow to define a custom component name, or an array of components (in some specific cases, multiple `COMPONENTS` can point to the same target, see [`FindCURL.cmake`](https://cmake.org/cmake/help/latest/module/FindCURL.html), it means that `COMPONENTS` don't mean "some target" but a feature). Indeed, COMPONENT name is not always the same name than target name (see `SFML` or `OpenCV` for example).
  Why not relying on `cmake_target_aliases` here to indirectly define desired COMPONENTS? Because it would create an undesirable target.

Possible implementation:
- for each component (and if its `cmake_component_name` is an array, loop into this array): set the variable `<cmake_file_name>_<cmake_component_name>_FOUND` to `TRUE`.
- in config file, call `check_required_components(<cmake_file_name>)`

From standard CMake macro (and usually called at the end) in default config files generated by `configure_package_config_file()`:

```cmake
macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()
```

But basically, config files generated by conan should honor all keywords and recommendations of https://cmake.org/cmake/help/latest/command/find_package.html#basic-signature.

**Comment by memsharded** [comment]
It is not implemented yet, but mostly intended. If a CMakeLists.txt line works without error if it works without error against the upstream config.cmake file, that is good enough, specially if it is going to make the CMakeDeps implementation way more complex and difficult to maintain. The goal of CMakeDeps was to provide a transparent integration with **positive compatibility** (if it works in the upstream, it should work with Conan) for the majority of cases (if CMakeDeps is able to correctly implement the compatibility of 98% of the open source libraries in ConanCenter, that could be enough), not to provide a 100% functionally equivalent replacement for 100% of the open source libraries out there.

So, honestly, that seems a lot of work (not only in Conan client, but also to do in recipes in ConanCenter), for something that is basically a minor UX protection (if the component really is not there, something will fail later, missing it at build time), so overall seems it is not worth, at least at this moment, we better use our energy in some other more productive things. Lets ask @czoido and @franramirez688, they can also estimate better what would be the effort.

**Comment by SpaceIm** [comment]
@memsharded Fair enough, but I believe that component names should be correct at least, so that markdown generator can display the correct suggestions.

**Comment by ledocc** [comment]
Same issue on my side,
Why my build fail ... after investigation ... cmake do not warning me that a components was not found ...
search why Qt5Config.cmake say nothing ... search why CMakeDeps generator do not implement this check ...
And like @SpaceIm, I found a pseudo check controled by check_components_exists but that not do what I am looking for.

We need this check by component to not waste time for this kind of issue.

@SpaceIm proposition seem good, and will not take a long time to do. I can provide a implementation if you ok with that.

conan-center-index correction will be done in next step.

thought ?

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/17302 for next Conan 2.10, in the new ``CMakeDeps`` generator.

Note this generator is at the moment under a dev-testing feature flag, which is the config ``-c tools.cmake.cmakedeps:new=will_break_next`` that will change at each release to discourage production usage.
Please give it a try when 2.10, looking forward to hearing your feedback. We will use feedback from users to get this feature out of dev-testing stage, as it is a very big one (the new CMakeDeps generator is completely new, from scratch, fixing many pending issues), it requires some pre-release testing and feedback.

Thanks very much!
