### ISSUE TITLE
:id packages requires are wrong

### ISSUE THREAD

**Issue by tom1lee** [conan-io/conan#10257]
Hi, i'm not pro coder... May I receive your help please

### Environment Details (include every applicable attribute)
  * Operating System+version: Mac Monterey 12.1
  * Compiler+version: Clang 13.0.0
  * Conan version: 1.44.0
  * Python version: 3.9.9

### Steps to reproduce (Include if Applicable)
...
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

WARN: harfbuzz/2.8.0: requirement freetype/2.11.0 overridden by qt/6.2.1 to freetype/2.10.4 
libgettext/0.20.1: WARN: Recipe 'libgettext/0.20.1' is deprecated in favor of 'gettext'. Please, consider changing your requirements.
conanfile.txt: Installing package
Requirements
    brotli/1.0.9 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    double-conversion/3.1.5 from 'conancenter' - Cache
    freetype/2.10.4 from 'conancenter' - Cache
    glib/2.70.0 from 'conancenter' - Cache
    harfbuzz/2.8.0 from 'conancenter' - Cache
    inja/3.3.0 from 'conancenter' - Cache
    libelf/0.8.13 from 'conancenter' - Cache
    libffi/3.4.2 from 'conancenter' - Cache
    libgettext/0.20.1 from 'conancenter' - Cache
    libiconv/1.16 from 'conancenter' - Cache
    libpng/1.6.37 from 'conancenter' - Cache
    libpq/13.2 from 'conancenter' - Cache
    nlohmann_json/3.9.1 from 'conancenter' - Cache
    odbc/2.3.9 from 'conancenter' - Cache
    opengl/system from 'conancenter' - Cache
    openssl/1.1.1l from 'conancenter' - Cache
    pcre/8.45 from 'conancenter' - Cache
    pcre2/10.37 from 'conancenter' - Cache
    qt/6.2.1 from 'conancenter' - Cache
    rapidxml/1.13 from 'conancenter' - Cache
    sqlite3/3.36.0 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
Packages
    brotli/1.0.9:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc - Missing
    bzip2/1.0.8:f2848f95be36a5d770fc8e833993b621f703b507 - Cache
    double-conversion/3.1.5:1aff124b71f6d938138ecd7179ff075f4304a85d - Missing
    freetype/2.10.4:926ec86ec76de2940f5d319a90b247e8ad515ede - Missing
    glib/2.70.0:661510ba2a3bb5cb6ec64426bb5d4230ef99a46b - Missing
    harfbuzz/2.8.0:63cbb23fb88a41d66c0d0c46dcbe2ca503cfead3 - Missing
    inja/3.3.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    libelf/0.8.13:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc - Missing
    libffi/3.4.2:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc - Missing
    libgettext/0.20.1:093defb2b8902dbb1cd5737e8d24a7f794ccc2d9 - Missing
    libiconv/1.16:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc - Missing
    libpng/1.6.37:aa5d2c35e57d031363e527ecb0b07150ed151373 - Missing
    libpq/13.2:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc - Missing
    nlohmann_json/3.9.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    odbc/2.3.9:a378317c51ebc76840b3893182ac29a3ab19e036 - Missing
    opengl/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    openssl/1.1.1l:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc - Missing
    pcre/8.45:a86359bb8915e4a8a57e48ce80b6c346f70f9755 - Missing
    pcre2/10.37:821b78acf7d26281b12b22529d6ac5e59961c3af - Missing
    qt/6.2.1:9c39a041ef08c69eb3a82026999134a5b7aecf3b - Missing
    rapidxml/1.13:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    sqlite3/3.36.0:105a8d60f8f74509af4922daa14b32b1e2ace8ac - Missing
    zlib/1.2.11:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc - Cache

Installing (downloading, building) binaries...
ERROR: Missing binary: brotli/1.0.9:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc
ERROR: Missing binary: double-conversion/3.1.5:1aff124b71f6d938138ecd7179ff075f4304a85d
ERROR: Missing binary: freetype/2.10.4:926ec86ec76de2940f5d319a90b247e8ad515ede
ERROR: Missing binary: glib/2.70.0:661510ba2a3bb5cb6ec64426bb5d4230ef99a46b
ERROR: Missing binary: harfbuzz/2.8.0:63cbb23fb88a41d66c0d0c46dcbe2ca503cfead3
ERROR: Missing binary: libelf/0.8.13:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc
ERROR: Missing binary: libffi/3.4.2:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc
ERROR: Missing binary: libgettext/0.20.1:093defb2b8902dbb1cd5737e8d24a7f794ccc2d9
ERROR: Missing binary: libiconv/1.16:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc
ERROR: Missing binary: libpng/1.6.37:aa5d2c35e57d031363e527ecb0b07150ed151373
ERROR: Missing binary: libpq/13.2:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc
ERROR: Missing binary: odbc/2.3.9:a378317c51ebc76840b3893182ac29a3ab19e036
ERROR: Missing binary: openssl/1.1.1l:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc
ERROR: Missing binary: pcre/8.45:a86359bb8915e4a8a57e48ce80b6c346f70f9755
ERROR: Missing binary: pcre2/10.37:821b78acf7d26281b12b22529d6ac5e59961c3af
ERROR: Missing binary: qt/6.2.1:9c39a041ef08c69eb3a82026999134a5b7aecf3b
ERROR: Missing binary: sqlite3/3.36.0:105a8d60f8f74509af4922daa14b32b1e2ace8ac

### Logs (Executed commands with output) (Include/Attach if Applicable)

Trying to build github repository ... Like this:

cd <repos>
mkdir build && cd build
conan install ..

Then failed !

**Comment by memsharded** [comment]
Hi @tom1lee 

There is a final message after what you posted there. Could you please post that part of the message too?

**Comment by tom1lee** [comment]
> Hi @tom1lee
> 
> There is a final message after what you posted there. Could you please post that part of the message too?

Thanks @memsharded, below the end of the message.
I went to see the address "More info at 'https: //docs.conan.io / ...
But that didn't help me!
In the meantime, thanks to the founder of the program I'm trying to install on mac! (https://github.com/dfleury2/boss-rc500-editor)
The solution was to modify /.conan/profiles/default with compiler.version = 12 iso compiler.version = 13!

brotli/1.0.9: WARN: Can't find a 'brotli/1.0.9' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.version=13.0, os=Macos
- Options: fPIC=True, shared=False
- Dependencies: 
- Requirements: 
- Package ID: e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc

ERROR: Missing prebuilt package for 'brotli/1.0.9', 'double-conversion/3.1.5', 'freetype/2.10.4', 'glib/2.70.0', 'harfbuzz/2.8.0', 'libelf/0.8.13', 'libffi/3.4.2', 'libgettext/0.20.1', 'libiconv/1.16', 'libpng/1.6.37', 'libpq/13.2', 'odbc/2.3.9', 'openssl/1.1.1l', 'pcre/8.45', 'pcre2/10.37', 'qt/6.2.1', 'sqlite3/3.36.0'
Use 'conan search brotli/1.0.9 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=missing'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

**Comment by memsharded** [comment]
Hi, from that link: https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package

> This means that the package recipe czmq/4.2.0@ exists, but for some reason there is no precompiled package for your current settings. Maybe the package creator didn’t build and shared pre-built packages at all and only uploaded the package recipe, or they are only providing packages for some platforms or compilers. E.g. the package creator built packages from the recipe for Visual Studio 14 and 15, but you are using Visual Studio 16. 

The explanation: ConanCenter still didn't build all the binaries for apple-clang 13, it is an ongoing thing (take into account there are thousand recipes to build, multiple versions, +130 different binaries for each, so it takes time). In the meantime, using the previous compiler version will find those binaries.

As the link and the message also say, you could also try building them from source with ``--build=missing`` or similar argument.

**Comment by tom1lee** [comment]
@memsharded 
Thank you for your answers. Now conan install is working perfectly.
I now have to look at linker errors in Qt6 under the make command.
I will try the approach with conan install --build = missing and compiler.version = 13
Is this the correct command ?
And I will close this post.

**Comment by memsharded** [comment]
> I will try the approach with conan install --build = missing and compiler.version = 13
Is this the correct command ?

It depends on what you need. If you are fine with version=12, then maybe not necessary to waste computation, and keep with 12. If you really need to update to version=13, then yes, definitely, building from source with ``--build=missing`` is typically the way to go, and it will be necessary at the moment, probably during a while until ConanCenter builds them all. If for some reason you need to cache your binaries (production, CI, etc), then you could use ArtifactoryCE (it is free) to store such binaries and depend on those, instead of re-building them from source every time.

**Comment by tom1lee** [comment]
@memsharded 
I succeeded perfectly to conan install in the build with compiler.version = 13.0 using --build = missing
(One hour of binaries deployment)
But I get the exact same linker error message from make
So the compiler version is not the problem !
Definitely, conan works perfectly, and this post is no longer valid.
Many thanks for all.

In case:
[ 61%] Linking CXX executable BossRc500
Undefined symbols for architecture x86_64:
  "qt_static_plugin_QXcbIntegrationPlugin()", referenced from:
      StaticQXcbIntegrationPluginPluginInstance::StaticQXcbIntegrationPluginPluginInstance() in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sources/BossRc500/BossRc500] Error 1
make[1]: *** [sources/BossRc500/CMakeFiles/BossRc500.dir/all] Error 2
make: *** [all] Error 2

**Comment by memsharded** [comment]
Happy to hear that it worked (the Conan part)

Regarding the linker error, that is more difficult to know, because it requires the whole project, with the build scripts, and the environment, etc to reproduce. I would say that this kind of ``Undefined symbols for architecture x86_64:`` error is typically a mismatch in the compilation flags, Conan was using the ``x86_64`` architecture, and trying to pass its best this definition to all packages. But if some of them ignored the flag, hardcoding something else, or maybe the consumer code is not properly injecting the Conan configuration, and build with/for another architecture, then the mismatch happens. I will try to look for this differences in architectures, commands like "objdump" (dumpbin in Win) could help to debug this.

Feel free to close the issue if you think it is responded, and do not hesitate to open new ones if you have further questions.

**Comment by tom1lee** [comment]
Many thanks @memsharded ! All is well !
