### ISSUE TITLE
[bug] AutoToolsBuildEnvironment does not recognize target x86_64-w64-mingw32 properly

### ISSUE THREAD

**Issue by leonschenk** [conan-io/conan#10267]
### Environment Details (include every applicable attribute)
  * Operating System+version: Dockerfile conanio/gcc11:latest
  * Compiler+version: Gcc 11.1
  * Conan version: 1.37.2
  * Python version: 3.7.5

### Steps to reproduce (Include if Applicable)
Create a package that is to be used as build requirement and requires the target to be according to the host profile of the package that you want to build.
Expected target is x86_64-w64-mingw32.
 - target os: Windows
 - target arch: x86_64
 - target compiler: gcc

However AutoToolsBuildEnvironment is using the compiler from the host profile, which might be a different one (theoretically) or left out completely (my case, because it is not important for the generated executable).
The following is now used to circumvent this behavior (in the conanfile): 

```
    def _get_target_settings(self):
        _os_target, _arch_target = get_target_os_arch(self)
        if hasattr(self, 'settings_target'):
            if (self.settings_target is not None):
                return _os_target, _arch_target, self.settings_target.get_safe('compiler')
        return _os_target, _arch_target, None

    def package_id(self):
        target_os, target_arch, target_compiler = self._get_target_settings()

        self.info.settings.target_os = target_os
        self.info.settings.target_arch = target_arch
        self.info.settings.target_compiler = target_compiler

    def build(self):
        autotools = AutoToolsBuildEnvironment(self)
        target_os, target_arch, target_compiler = self._get_target_settings()
        target_gnu = get_gnu_triplet(target_os, target_arch, target_compiler)
        autotools.configure(configure_dir=self.folders.source_folder,args=['--disable-multilib'], target=target_gnu)
        autotools.make()
```

I suggest the compiler used for determining the target gnu_triplet is the settings_target compiler.

**Comment by memsharded** [comment]
Sorry this was not responded back then.

I am closing this ticket as outdated, ``AutoToolsBuildEnvironment`` does not exist any more, it was replaced by modern alternatives like ``AutotoolsToolchain`` time ago. Please report against the new generators if necessary, thanks for your feedback.
