### ISSUE TITLE
[bug] self.copy("symlink", symlinks=True) copies the file instead of the symlink

### ISSUE THREAD

**Issue by evandrocoan** [conan-io/conan#10270]
### Environment Details (include every applicable attribute)
  * Operating System+version: Debian 9
  * Compiler+version: 6.3
  * Conan version: 1.42.2
  * Python version: 3.6.13

### Steps to reproduce (Include if Applicable)

Create a recipe with:
```python
    def package(self):
        self.run("ln -s somelib.so somelib.so.3")
        self.copy("somelib.so.3", dst="lib", keep_path=False, symlinks=True)
        self.copy("somelib.so", dst="lib", keep_path=False)
```

It will copy `somelib.so.3` as a file instead of a symlink (bad for space). If I replace `self.copy("somelib.so.3", ...` with `self.copy("somelib.so.*",`, it does correctly copy the symlink instead of the file it points to.

I first tried without the `symlinks=True` and the problem was the same, instead of copying the symlink, it was copying the file the symlink was pointing to.

**Comment by memsharded** [comment]
Sorry this was not responded back then.

I am closing this ticket as solved/outdated, the ``self.copy()`` does not exist anymore, the new ``copy()`` function will handle symlinks differently. Please create new tickets against the new ``copy()`` function if necessary.
