### ISSUE TITLE
[question] ConanException running command using self.run

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10276]
In the build step of my conanfile, I run an external application (Incredibuild on Windows) using self.run(). However, it seems to generate a ConanException with the message: "Error 1936026729 while executing ...".

Is that error number being generated by the application I'm running or from conan?

This issue seems to have stared recently (seen with conan version 1.44.0) as it's worked before. The other oddity is that it fails the first time but then works fine the second time, and the console output printed to the screen from Incredibuild seems to be that everything was successful. When I run Incredibuild manually I don't see any issues so not sure if it's doing some weird when it returns.

One thing of note is that I am running conan build when this happens (I can't run conan create) but using conan create with the exact same build step (I'm using python_requires) on another project works without issue.

Can you point me to where in the code where to find the implementation for self.run? Maybe I can dig around and figure something out. My current work around is to catch the exception and just run the command again.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @nichmj01 

That message is printed from the code:
```
 else:
            retcode = _run(command, env)

        if not ignore_errors and retcode != 0:
            raise ConanException("Error %d while executing %s" % (retcode, command))
```
and that contains the return code from the executable being called. It would be great to check Incredibuild return codes, and check if 1936026729 makes sense. Also, is Incredibuild doing some other output before that error?

The class to check for the final real execution is ``ConanRunner()`` class, if you want to have a look.

Also, it would be really useful to revert to 1.43, and check again. We haven't change anything relevant in ``self.run()`` or ``ConanRunner()`` but it would be great to know if it is a regression to be fixed.

**Comment by nichmj01** [comment]
> Also, it would be really useful to revert to 1.43, and check again. We haven't change anything relevant in self.run() or ConanRunner() but it would be great to know if it is a regression to be fixed.

Reverted to 1.43.0 and the problem still occurs. Also I tried a much older version (v1.27.1) and it still happened so that seems to indicate this is something with Incredibuild.

> Also, is Incredibuild doing some other output before that error?

Incredibuild is printing a bunch of output to stdout (or possible stderr, I can't tell right now) but the output makes it seem like everything it good. I'll reach out to Incredibuild about the error code and try to chase the error if I have time.

**Comment by memsharded** [comment]
> Reverted to 1.43.0 and the problem still occurs. Also I tried a much older version (v1.27.1) and it still happened so that seems to indicate this is something with Incredibuild.

Ok, thanks for telling. Please let us know how it goes, and don't hesitate to re-open if you think we could help with something more.

**Comment by nichmj01** [comment]
Just an FYI for anyone in the future. The issue was confirmed to be with the version of Incredibuild (IB) I was using via their support (it was returning an incorrect error code). Updating to a newer version of IB fixed it.

**Comment by memsharded** [comment]
Thanks for following up and reporting @nichmj01!
