### ISSUE TITLE
[question] Workspace Layout file set absolutepath by parameter

### ISSUE THREAD

**Issue by stefaneicher** [conan-io/conan#10278]
Hi,

https://docs.conan.io/en/latest/developing_packages/workspaces.html#out-of-source-builds

Is there a way I can set a relative path in my workspace layout file to the top of my git repo like this?

[build_folder]
{{top of repo}}/build/{{reference.name}}/{{settings.build_type}}

[includedirs]
src

[libdirs]
{{top of repo}}/build/{{reference.name}}/{{settings.build_type}}/lib

Regards Stefan

Background:

I have one git repo with multiple conan recipes like this and would like to collect all build results in one folder.
With that, I can simply delete all build states by just be deleting the build folder. And it is also easy and intuitive to understand.
.
|-- build
|   |-- gcc
|   |-- iar
|   `-- clang
|-- group1
|   |-- recepie1
|   |   `-- conanfile.py
|   `-- recepie2
|       `-- conanfile.py
`-- group2
    |-- recepie3
    |   `-- conanfile.py
    `-- recepie4
        `-- conanfile.py
Currently, we set a hard-coded absolute path. Which unfortentualy is dependent on the checkout location.

[build_folder]
/workspace/build/{{reference.name}}/{{settings.build_type}}

[includedirs]
src

[libdirs]
/workspace/build/{{reference.name}}/{{settings.build_type}}/lib

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
A quick couple of comments:

- The layout external files have been removed in 2.0-alpha. They are replaced with the ``layout()`` method (already available in 1.X latests versions)
- The ``workspace`` command has been removed in 2.0-alpha. We are still working hard to stabilize and improve the ``layout()`` method as a foundation block for workspaces, and once everything is looking good (after 2.0), we will resume work on the workspace feature.

**Comment by stefaneicher** [comment]
Hi memsharded,

Thanks for your reply. I tested a bit with the layout() feature but in the project, we first need to update conan.
I would be curious about what the conan 2.0 workspace feature would look like. Can you send me some Infos or a link to information about conan 2.0 workspaces?

In our project, I will just now update our build.py in which we orchestrate the build of our packages.
We have for example 10 or 20 packages. That must get built for 
- arm-gcc, releases and debug
- arm iar, releases and debug
- x86 clang, releases and debug (for unittests)

I think about extending our https://github.com/disroop/mumoco.
Obviously, my wish list would continue that I would like to be able to create an IDE integration for this tool by extending
 https://github.com/disroop/vs-code-conan.

Here we talk already once about https://github.com/disroop/vs-code-conan
https://github.com/conan-io/conan/issues/8322#issuecomment-759119595

In case you would be interested in a exchange let me know!

**Comment by stefaneicher** [comment]
Hi Diego, 
Thanks for the great exchange and discussion yesterday!
Can you send me a link to the feature where I can register my own commands like "conan disroop-install" ?
If it is in conan 2.0 just send me a link to a unittest.
Regards Stefan

**Comment by memsharded** [comment]
Sure, have a look to https://github.com/conan-io/conan/blob/develop2/conans/test/integration/command_v2/custom_commands_test.py

(and all the new commands https://github.com/conan-io/conan/tree/develop2/conans/cli/commands)

**Comment by stefaneicher** [comment]
perfect thanks!
