### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [conan-io/conan#10289]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by memsharded** [comment]
Sorry this was not responded back then @JamieSlome 

This is being closed by an update to the README: https://github.com/conan-io/conan/pull/17506, that links to the JFrog page to disclose vulns, conan.io is an option that can be selected in the report. Many thanks for reporting!
