### ISSUE TITLE
[feature] Allow multiple recipe revisions to be cached

### ISSUE THREAD

**Issue by Vhab** [conan-io/conan#10284]
As conan-center has been moving rather fast, often with breaking changes on existing versions, we've started using lock files and revision pinning.

However, as we have multiple projects and multiple development teams on different cycles, the contents of lockfiles don't always end up pinning on the same revision of a recipe.

This is entirely fine, as these projects all build fine with their own set of dependencies at specific revisions.

But this is where the problem comes in, working on 2 projects concurrently requires constant rebuilding/installing of conan dependencies as only a single revision of a recipe can be cached.

This is incredibly cumbersome and time consuming.

So right now we're stuck with either not pinning dependencies and deal with regular breakage. Or pin revisions but deal with constant cache invalidation if 2 projects happened to have pinned on different revisions.

A good solution would be for the cache to support multiple revisions concurrently.

**Comment by memsharded** [comment]
Hi @Vhab 

Yes, we know about this. We have already implemented and released an multi-revision Conan cache in 2.0-alpha. We didn't manage to do it in 1.X because it is too challenging to do it without breaking. We are very looking forward to release 2.0 betas and GA this year.

**Comment by memsharded** [comment]
I think this can be closed as implemented and released in 2.0-alpha. Thanks!
