### ISSUE TITLE
[feature] package_info/CMakeDeps: provide a way to propagate interface C and C++ min standard (c_std_yy/cxx_std_yy) in imported targets 

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#10281]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Properly written CMakeLists of C and C++ libraries propagate interface c_std & cxx_std compile feature in imported targets. It would be nice if there was a way to properly set this compile feature in `package_info()` so that imported targets in `CMakeDeps` inherit this useful information.

For example:

```python
def package_info(self):
    self.cpp_info.set_property("cmake_target_name", "foo::bar")
    self.cpp_info.set_property("cmake_compile_features", ["cxx_std_17"])
```

then in config file generated by `CMakeDeps` there would be:

```cmake
set_target_properties(foo::bar PROPERTIES INTERFACE_COMPILE_FEATURES "cxx_std_17")
```

**Comment by SpaceIm** [comment]
@memsharded @lasote Is it a feature you could consider in `set_property` for `CMakeDeps`?

**Comment by memsharded** [comment]
> @memsharded @lasote Is it a feature you could consider in set_property for CMakeDeps?

Why would be this necessary, if the cppstd is already an input setting, and recipes can raise ``ConanInvalidConfiguration`` if the input setting is not satisfying the minimum?

**Comment by SpaceIm** [comment]
> if the cppstd is already an input setting

That's the point, and if it is not in input settings? Anyway it's a nice feature because it allows to write CMakeLists honoring "usage requirements only" principle, and why not providing config files closed to good practices?
If I'm not using any C++17 feature in my executable, but I'm including a header of a dependency with some C++17 stuff, I shouldn't have to write target_compile_features(myapp PRIVATE cxx_std_17), it should come from interface compile feature of my dependency.

**Comment by SpaceIm** [comment]
@memsharded are you still against this feature? compiler.cppstd is not mandatory in conan v1 nor v2. So a build with these profiles without explicit compiler.cppstd may fail.

Here is a typical example in https://github.com/conan-io/conan-center-index/pull/16356

openMVG requires at least C++11 by itself. But it depends on ceres-solver which may require C++14 at consume time (depends on ceres-solver version). If ceres-solver target was properly defined by CMakeDeps (ie properly defining interface compile feature cxx_std_14), it would work out of the box.
But currently I have to inject some tedious manual logic to force C++14 in openMVG depending on valid_min_cppstd() and ceres-solver version: https://github.com/conan-io/conan-center-index/blob/ca205359c6fb817ae3a22fc61f1be12f1fe7509c/recipes/openmvg/all/conanfile.py#L106-L110
It's always a mess to assume internal details of dependencies in downstream recipes, and it defeats the purpose of CMake targets.

**Comment by memsharded** [comment]
> @memsharded are you still against this feature? compiler.cppstd is not mandatory in conan v1 nor v2. So a build with these profiles without explicit compiler.cppstd may fail.

Yes, ``compiler.cppstd`` is mandatory in Conan 2.0. It is the input needed for all ``validate()`` methods that want to enforce it, it is used in the default ``compatibility.py`` and it is defined both in the default auto-detected profiles and the profiles that are used in ConanCenter.

The way to move forward in 2.0 is to define ``compiler.cppstd`` in the profiles, not necessary to propagate downstream in the graph, and just ``validate()`` raising if cppstd is not enough is the recommended approach.

Closing this issue as not planned.

**Comment by SpaceIm** [comment]
> Yes, compiler.cppstd is mandatory in Conan 2.0

I don't understand, conan v2 works fine without compiler.cppstd defined in my profile.

**Comment by memsharded** [comment]
Yes, it is not mandatory to define it in the profiles, there are users with pure C projects, that wouldn't want this mandated, and it will be a blocker for them.
But it is mandatory to define it if you want correct ``cppstd`` handling by recipes. The strong recommendation for profiles in 2.0 is to define ``cppstd`` unless you are building pure C projects only.

**Comment by SpaceIm** [comment]
Ok. I hope you'll change your mind in the future regarding this issue, so that CMake targets can be properly modeled.

**Comment by ilya-lavrenov** [comment]
Also faced with this issue here https://github.com/conan-io/conan-center-index/pull/20774
- OpenVINO requires C++11 in public API
- Whisper.cpp does not set any CXX standard 

Hence, during their joint compilation, whisper.cpp files cannot be compiled, because no information about required C++ standard is provided from OpenVINO.

I suppose Conan can propagate this info to multiple generators.

**Comment by memsharded** [comment]
Hi @ilya-lavrenov 

I have reviewed https://github.com/conan-io/conan-center-index/pull/20774#pullrequestreview-1700714667.

The approach that conan follows is not propagating cppstd requirements down the graph, but the ``cppstd`` is an input definition, and as such, recipes should use it, or raise a ``ConanInvalidConfiguration`` error if not possible. The ``settings.compiler.cppstd`` should be defined in Conan 2.0, it is not recommended to not specify it.
