### ISSUE TITLE
[bug] Problem with revision after migration to new Artifactory server

### ISSUE THREAD

**Issue by tofDou** [conan-io/conan#10296]
### Environment Details (include every applicable attribute)
  * Artifactory version 7.17
  * Conan version 1.29

### Explanation
After a server migration (From CE community) to Commercial one, we decided to activate revision in our centralized  conan conf file.
Then all "old" packages are now with a recipe revision 0 as expected. New Versions of packages are now associated with their git commitID since we choose SCM mode for revision. So far, so good.
After the migration we clean all local caches in order that no scories exists.
On certain machines (dev or CI machines) and not often, we have trouble with certain conan packages that are installed.
When looking forward and using `conan search PackageName --revision,` theses defect packages are installed but with a bad revision number (a hash or a commit id or something else that doesn't match with existing revision on the artifactory server).
When using the same command with the` --raw` option, a "(No Time) is displayed after the revision number".
The workaround is to remove the package locally with `conan remove PackageRef` and then `conan install` works fine.
The problem is that it is a workaround, that it's not easily reproductible and not possible at all for CI jobs...

PS: Before the migration, I didn't find the way to disable revision in Artifactory server (that the first reason why i choose to enable it in the conan configuration. Without this enabled, I was not allowed to upload a conan packages without revision in the new server), is that normal or did I miss something?

**Comment by memsharded** [comment]
Hi @tofDou 

> When looking forward and using conan search PackageName --revision, theses defect packages are installed but with a bad revision number (a hash or a commit id or something else that doesn't match with existing revision on the artifactory server).

I would say that it is possible that the client caches have not been completely cleared. What method did you use to clean them? A regular ``conan remove`` will not be enough, there might be some remaining metadata. I would suggest doing a hard removal of both the ``.conan`` cache folder (and the "short paths" cache folder in Windows, typicall ``C:/.conan``).

**Comment by tofDou** [comment]
Indeed, I use the conan remove "*" command

**Comment by tofDou** [comment]
An idea where these bad revision numbers comes from?
I remember strange behaviour in the conan output during the` conan install` process in my jenkins job. 
Something like:
ThalesCscApi/1.23.1@rcs/testing: WARN: The package ThalesCscApi/1.23.1@rcs/testing:72bd89dac18f3a55cee258572a91e169b359df3b doesn't belong to the installed recipe revision, removing folder
14:11:08.855 conanfile.py (MediaAccessLayer_Core/7.0.3): ERROR: Missing binary: ThalesCscApi/1.23.1@rcs/testing:72bd89dac18f3a55cee258572a91e169b359df3b
14:11:08.855 >>> ComponentConanFile._get_recipe_build_requires(): ...
14:11:08.855 conanfile.py (MediaAccessLayer_Core/7.0.3): >>> ComponentConanFile.build_requirements(): Platform=pc_x86_win32_vs2019
14:11:08.855 conanfile.py (MediaAccessLayer_Core/7.0.3): >>> ComponentConanFile.build_requirements(): component_requires=
14:11:08.855 conanfile.py (MediaAccessLayer_Core/7.0.3): >>> ComponentConanFile.build_requirements(): component_requires_force=None
14:11:08.855 conanfile.py (MediaAccessLayer_Core/7.0.3): >>> ComponentConanFile.build_requirements(): requires:
14:11:08.855 
14:11:08.855 
14:11:08.855 conanfile.py (MediaAccessLayer_Core/7.0.3): Installing package
14:11:08.855 Requirements
14:11:08.855     ThalesCscApi/1.23.1@rcs/testing from local cache - No remote
14:11:08.855 Packages
14:11:08.855     ThalesCscApi/1.23.1@rcs/testing:72bd89dac18f3a55cee258572a91e169b359df3b - Missing
14:11:08.855 
14:11:08.855 Cross-build from 'Windows:x86_64' to 'Windows:x86'
14:11:08.855 Installing (downloading, building) binaries...
14:11:08.855 
14:11:08.855 ThalesCscApi/1.23.1@rcs/testing: WARN: Can't find a 'ThalesCscApi/1.23.1@rcs/testing' package for the specified settings, options and dependencies:
14:11:08.856 - Settings: arch=x86, os=Windows, platform=pc_x86_win32, platform.sdkVersion=vs2019
14:11:08.856 - Options: component_build_requires_force=None, component_requires_force=None, platform_force=None, platform_provided_version=None, platform_sdkVersion_force=None, release=False, shared=None, use_platform_provided_version=None
14:11:08.856 - Dependencies: 
14:11:08.856 - Requirements: 
14:11:08.856 - Package ID: 72bd89dac18f3a55cee258572a91e169b359df3b
14:11:08.856 
14:11:08.856 ERROR: Missing prebuilt package for 'ThalesCscApi/1.23.1@rcs/testing'
14:11:08.856 Try to build from sources with "--build=ThalesCscApi"

Then, when i try to look forward on the CI machine:
```
conan search ThalesCscApi/1.23.1@rcs/testing --revision

Revisions for 'ThalesCscApi/1.23.1@rcs/testing':
c70416fc9b14caa6e5a990903dee800f (No time)
```

**Comment by tofDou** [comment]
On this particular package ThalesCscApi/1.23.1@rcs/testing, only a "0" revision was present on the server.
The `conan remove ThalesCscApi/1.23.1@rcs/testing` solves the problem.

**Comment by memsharded** [comment]
> An idea where these bad revision numbers comes from?
I remember strange behaviour in the conan output during the conan install process in my jenkins job.
Something like:

Yes, the revisions are stored in a json file "metadata.json" in the cache. There is also an automatic migration in the cache that runs when Conan is upgraded, and it will probably use the default "content" hash strategy, instead of the SCM one that is unknown by the cache stored packages. So if the cache folder is not completely removed, maybe some of these files were trailing and the migration partly applied or something like that.

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you, and now Conan 2 has mandatory revisions, issues like this can not manifest, thanks a lot for taking the time to report the problem :)
