### ISSUE TITLE
[question] Why is /v1/conans/search so slow? Is there a faster alternative?

### ISSUE THREAD

**Issue by jtbandes** [conan-io/conan#10298]
Hello,
I've made a [pull request](https://github.com/badges/shields/pull/7460) to shields.io to add a `conan` badge that shows the latest version of a package, like this:

`<img src="https://shields.io/conan/v/zeromq">` → <img width="90" src="https://user-images.githubusercontent.com/14237/148507164-7b59e074-4004-4add-a018-f10c77f51cd9.png">

The shields.io badge service is used by many packages on GitHub from other package managers such as npm, pypi, [and more](https://shields.io/category/version). It provides a version indicator at a glance that can be easily added to any project's README.

This is implemented by querying `https://center.conan.io/v1/conans/search?q=${packageName}`. However, **this query seems to be quite slow** and I was wondering if there is any better API that can be used to improve the search speed, given that I only need the **latest** package version?

Some informal measurements taken using `time conan search -r conancenter ${packageName}`:

Searching for `boost` took >10sec on the first try, and subsequent requests were ~4-5 sec.
Searching for `nlohmann_json` seems to be <1sec.
Searching for `poco` was >10sec the first time, and subsequent requests are ~1sec.
Searching for small, unpopular libraries (e.g. `absent`) seem to be <1sec.

**Comment by memsharded** [comment]
Hi @jtbandes 

Thanks for reporting. We are aware of this issue, and up to our knowledge some work was done in the backend server supporting ConanCenter, and it was in the queue for deployment. I am not sure atm if this has a expected date or not, I'll check.

**Comment by jtbandes** [comment]
Hi @memsharded, did you learn anything about the ETA for these improvements?

**Comment by memsharded** [comment]
Yes, it seems this is already released in Artifactory 7.29: https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.29 (search for Conan).

We don't know yet when it will be deployed to cloud (and subsequently update the ConanCenter backend), we will report as soon as we know it.

**Comment by jtbandes** [comment]
Still not rolled out I guess 😬 
```
$ time conan search -r conancenter boost
Existing package recipes:
...
conan search -r conancenter boost  0.22s user 0.07s system 0% cpu 1:53.27 total

$ time conan search -r conancenter boost
Existing package recipes:
...
conan search -r conancenter boost  0.20s user 0.07s system 1% cpu 26.687 total
```

**Comment by memsharded** [comment]
Hi @jtbandes 

They have been rolled out, but apparently (and unfortunately) they are not enough yet. So we will need to push it again to the Artifactory team, we will keep you posted, thanks for following up.

**Comment by memsharded** [comment]
Update: team keep working on this, now with a new approach that seems to be definitive, so it is planned that some of the next Artifactory releases will improve and fix this.

**Comment by memsharded** [comment]
This has been finally fixed. ``conan search zlib* -r=conancenter`` now works fast against ConanCenter

Artifactory 7.41 contains the fixes, so if you are experiencing this in your own instance, please upgrade.

**Comment by jtbandes** [comment]
Thanks! @jgsogo are you planning to make a PR to shields.io to use this API instead of scraping files from github?

**Comment by jgsogo** [comment]
> Thanks! @jgsogo are you planning to make a PR to shields.io to use this API instead of scraping files from github?

The plan is to provide a dedicated API for this purpose, but meanwhile, maybe now the search is fast enough to provide this integration.
