### ISSUE TITLE
[question] ERROR 'pkgconf' with a custom recipe

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#10297]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I have the recipe:
```python
import os
from conans import ConanFile, tools, AutoToolsBuildEnvironment
from conans.errors import ConanInvalidConfiguration

required_conan_version = ">=1.40.1"

class LibUsbMuxdConan(ConanFile):
    name = "libusbmuxd"
    generators = "pkg_config", "markdown

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "shared": [True, False], 
    }
    default_options = {
        "shared": False,
    }

    def config_options(self):
        if self.settings.os == "Windows":
            ConanInvalidConfiguration("Unable to build LibUsbMuxd on Windows")

    def build_requirements(self):
        self.requires("pkgconf/1.7.4")
        self.requires("libtool/2.4.6")
        self.requires("automake/1.16.2")
        self.requires("autoconf/2.69")
    
    def requirements(self):
        self.requires("libplist/2.2.0")
    
    def source(self):
        tools.get(**self.conan_data["sources"][self.version], strip_root=True, destination=".")

    def build(self):
        autotools = AutoToolsBuildEnvironment(self)
        autotools.configure()
        autotools.make()
    
    def package(self):
        autotools = AutoToolsBuildEnvironment(self)
        autotools.configure()
        autotools.install()
        
    def package_info(self):
        self.cpp_info.names["cmake_find_package"] = "libusbmuxd"
        self.cpp_info.names["cmake_find_package_multi"] = "libusbmuxd"
        self.cpp_info.names["pkg_config"] = "libusbmuxd"
        self.cpp_info.libs = ["libusbmuxd"]
```
but whenever I try and do `conan create` on it I end up getting:
```
libusbmuxd/2.0.2: ERROR: Generator pkg_config(file:None) failed
'pkgconf'
ERROR: 'pkgconf'
```
or
```
libusbmuxd/2.0.2: ERROR: Generator markdown(file:None) failed
'pkgconf'
ERROR: 'pkgconf'
```
but what's weird is that's only if I'm building it clean, if I have a failed build in `~/.conan/data` it works without any issues. What's wrong here?

**Comment by memsharded** [comment]
Is it possible that there is a typo here?:

```
generators = "pkg_config", "markdown
```
It seems it is missing the quotes.

**Comment by wbehrens-on-gh** [comment]
@memsharded That appears to just be a copy paste issue, it was closed for me

**Comment by memsharded** [comment]
I am trying to see where it could be failing, but as I am missing most of the data, I cannot try. I'd recommend the following:

- Start stripping the recipe to reduce the unnecessary parts. Probably the ``source()``, ``build()``, ``package()`` are unnecessary, as the failure seems to happen in the "generators" step, which is done earlier.
- Try what happens running locally ``conan install`` (one or several times), as opposed to create.
- Try removing the other dependencies, leave only the ``pkgconf`` one. Also try with a system installed ``pkg-config`` instead.
- It is confusing that you are using all those inside ``build_requirements()`` as regular ``requires``. This might be related to the issue you are seeing, ``requires`` must be in the ``requirements()`` method only.

**Comment by wbehrens-on-gh** [comment]
What do I use in build_requirements rather then requires()? is there a build_requires() method?

**Comment by memsharded** [comment]
Yes, something like:

```python
def build_requirements(self):
     self.build_requires("xxxx")
```
In modern Conan 1.44, you can use ``tool_requires = "cmake/3.14"`` as attribute and ``self.tool_requires("xxxx")`` inside ``build_requirements()`` method.

**Comment by wbehrens-on-gh** [comment]
just running conan install locally does give the same error, but just like with conan create it's only occasionally, I've also switched to using build_requires().

**Comment by wbehrens-on-gh** [comment]
I appears the error was in another package that didn't have the build_requires() set properly
