### ISSUE TITLE
[bug] Exposing cmake variables via CMakeDeps in conan 1.44 not working

### ISSUE THREAD

**Issue by Wuestenschiff** [conan-io/conan#10291]
Sorry for cross posting but I am not sure where this belongs to.

I have Trouble with protobuf recipe no longer exporting `protobuf_PROTOC_EXECUTABLE`. I already reported a bug on the recipe with an example Project: https://github.com/conan-io/conan-center-index/issues/8625

But as this works on conan 1.43 and also works with another generator like cmake_find_package it seems this could also be a conan bug, so I wanted to bring attention to it here as well.

**Comment by sburton84** [comment]
I believe this sounds like the same issue described in https://github.com/conan-io/conan/issues/10282 and https://github.com/conan-io/conan/issues/10272

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/8820 may fix this issue.

**Comment by Wuestenschiff** [comment]
Thx @SpaceIm  seems fixed!
