### ISSUE TITLE
Does conan support "latest" version for package uploads?

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#103]
Hi,

More of a question really. Let's imagine I'm uploading a package off of CI (say travis). Would it be possible to have a "fake" version like say ```latest``` which would always correspond to the git commit of the  CI checkout? I wouldn't want to pin this version, but for it to be continually moving so that if other CI builds depended on it, they would always get the last one that got uploaded (but crucially, they would be able to know which one it was in case the build broke).

Many thanks for your time.

Marco

**Comment by lasote** [comment]
Hi Marco

You can upload with travis an special channel named maybe "ci".
Conan allows to override the packages without any restriction so it can be done. Those packages in "ci" channel will be override in every commit. You can change the channel to "stable" later. In version 0.7 we will release a "conan copy" command and a new option for "conan install". It will allow to download all the packages from a channel, then you will be able to rename the channel and upload them again. (Something like a simplified binary pull request)

By the way, I'm currently working (I hope to release it and write docs soon) in a tool that helps to auto generate multiple packages using CI (tested with travis and appveyor). I have tested with zlib, opensssl and Boost and works great. There is an example: https://travis-ci.org/lasote/conan-boost

I don't know if I have answered your question. Let me know if you have any doubts.

Thanks!

**Comment by mcraveiro** [comment]
Sounds like it's exactly what I need!! :-D thanks, I'll wait for the tool!

**Comment by lasote** [comment]
I already have a very beta version here: 

https://github.com/conan-io/conan-package-tool

Great if you can try it! :D

**Comment by mcraveiro** [comment]
Hi Luis,

Wow, looks cool! Right, I don't want to sound too negative here, because this looks like an amazing piece of work and lord knows how hard it is to get products/features out. Having said that, I just want you to understand my use case / circumstances: the problem I have is that I have very little spare time to play with my open source project. One of the reasons why I loved conan was because it required 5 mins to grok it and another 10 mins to implement it. I was hoping the upload solution would be similar to the download/install solution - some kind of very trivial TXT file with properties (or ideally a section on that very same file). However, from looking at the docs above, I will have to parse them properly before I can start using it. If you can come up with a TL;DR explanation that is along the lines of "copy here, change it to your project/username, done" you stand to gain more users because there are quite a few developers of open source projects in my circumstances (short of time and in need of solutions that just work). In addition, this and #115 will make adding conan support *very* non-intrusive, which means people should be more willing to accept patches for conan support directly on their projects. I think this is an important thing in order to increase the library ecosystem.

Just my 2 Angolan Kwanzas at any rate... :-)

**Comment by lasote** [comment]
Hi Marco! I release few days ago a new version of conan package tools. It has been simplified and now the CI integration is much simpler. (And the readme too)
Earlier next week we will release the 0.8 version. A conan install --update (or -u) option will be available too. Maybe it will be useful too for your needs.
