### ISSUE TITLE
How can we configure a large project with multiple subfolders and .c and .h files to build with conan and cmake

### ISSUE THREAD

**Issue by NIKHILJIND** [conan-io/conan#10305]
example project structure is 

project->source->folder1->folderA->inc->one.h
                                                                  ->two.h
                                                                  ->three.h
                                                         ->src->first.c(include header and .c files from folder2 and folder3 also)
                                                                  ->second.c(include header and .c files from folder2 and folder3 also)
                          ->folder2..................
                          ->folder3..............

**Comment by memsharded** [comment]
Hi @NIKHILJIND 

First important thing is that Conan is not a build system, so the CMake part is something that you need to figure out first. There are no conventions there, but something common would be:

- Put a ``CMakelists.txt`` in the root of your project, with ``add_directory(source)``
- Put another ``CMakeLists.txt`` in the ``source`` folder. You might repeat this pattern for every subfolder.
- Put a ``conanfile.py`` in the root of the project, declaring how to package things. You can check the docs.conan.io about how to create packages, and there are also other learning resources like free training courses if you need.

**Comment by NIKHILJIND** [comment]
Hi @memsharded 
Thanks for your reply,
I am new to all of this stuff.
In the project which I want to build, there are already makfiles present to build the project. Can I consume that make files directly or I have to use cmake or another generator while using conan for package management.

**Comment by memsharded** [comment]
> there are already makfiles present to build the project. Can I consume that make files directly

Yes, you don't need to port your project to CMake to use Conan. There are integrations with different build systems, including autotools/makefile. This is a bit outdated, but something you can check: https://docs.conan.io/en/latest/howtos/makefiles.html

Whether you port your project to CMake is a different kind of decision, and depend on many factors, like expertise, the time to deliver, resources, long time maintenance and support, etc, etc. In any case, I think it you don't know enough CMake, to start learning it a bit better. Then, if you are interested in packaging, I'd recommend also to do the free Conan training to understand better what Conan does. The C++ ecosystem is complex, and Conan needs to adapt to that fact, but that also implies that there are a bunch of things to learn.

**Comment by memsharded** [comment]
Closing as responded back then, but please don't hesitate to create new tickets if you have any further question. Thanks for your feedback.
