### ISSUE TITLE
[feature] Tool: is_msvc helper

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#10306]
Our friend and great contributor SpaceIm is using a new detection which I believe could be part of the mainstream:

```python
@property
def _is_msvc(self):
    return str(self.settings.compiler) in ["Visual Studio", "msvc"]
```

This property can be largely re-used, when checking on `validate()` or any other condition.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @uilianries 

Yes, makes sense, specially to try to have clean recipes for migrating to 2.0 (only msvc will remain there). 
Do you want to contribute this? I guess it will be a tool in ``conan.tools.build``?

**Comment by uilianries** [comment]
@memsharded Yes, I can do it of course.

> I guess it will be a tool in conan.tools.build?

Build so far is only related to CPU, however, [visual.py](https://github.com/conan-io/conan/blob/develop/conan/tools/microsoft/visual.py) has all Visual Studio information there. I would suggest `conan.tools.visual` in this case.

**Comment by memsharded** [comment]
> Build so far is only related to CPU, however, visual.py has all Visual Studio information there. I would suggest conan.tools.visual in this case.

``conan.tools.visual`` is not public/documented. In any case it should be ``conan.tools.microsoft``. Yes, it makes sense too. I was thinking where all the possible configuration checks would be, like we don't know if it is "microsoft" yet, we are checking, and this was a generic "check", but I agree, it will feel cleaner in ``conan.tools.microsoft``.

**Comment by SSE4** [comment]
I think we also need a helper(s) for compiler runtime:
https://github.com/conan-io/conan-center-index/pull/8801/files#diff-d67d36ebb633f3e920a34cd24c6c92ac12ab88b1f1db0a694841133faeb10fe5R783-R791
```
    @property
    def _runtime(self):
        if self.settings.compiler == "Visual Studio":
            return self.settings.compiler.runtime
        else:
            return "M{}{}".format(
                "T" if self.settings.compiler.runtime == "static" else "D",
                "d" if self.settings.compiler.runtime_type == "Debug" else "",
            )
```
it's pretty widespread among CCI recipes already
(and one more helper could return runtime in a form of MultiThreaded[Debug][Dll], which is also frequently needed)

**Comment by memsharded** [comment]
``msvc_runtime_flag()`` is already in ``visual.py`` and made available via ``conan.tools.microsoft``
