### ISSUE TITLE
[bug] pkg_config generator doesn't listen global cpp_info.set_property, only components

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#10309]
### Environment Details (include every applicable attribute)
  * Operating System+version: Macos Monterey
  * Compiler+version: apple-clang 13.0
  * Conan version: 1.44.0
  * Python version: 3.9.9

### Steps to reproduce (Include if Applicable)

- use this revision of openjpeg recipe: https://github.com/conan-io/conan-center-index/tree/5196876e5c9bbe9ca9de12db9a2e7d9b5fbf627f/recipes/openjpeg/all, where there is `self.cpp_info.set_property("pkg_config_name", "libopenjp2")` but not `self.cpp_info.names["pkg_config"] = "libopenjp2"`.
- add `pkg_config` generator to test_package
- call `conan create . openjpeg/2.4.0@`
- you'll see that there is no `libopenjp2.pc` file in build folder of test package, just `openjpeg.pc` which is wrong.

It doesn't fit to migration guidelines in CCI: https://github.com/conan-io/conan-center-index/pull/8415#discussion_r781689513

**Comment by czoido** [comment]
Thanks for reporting @SpaceIm , I'm assigning this to 1.44.1 to be fixed ASAP.

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/10312 
To be released very soon in 1.44.1 and 1.43.3
