### ISSUE TITLE
[question] package only found if remote is specified explicitly

### ISSUE THREAD

**Issue by simue** [conan-io/conan#10324]
Hi,
I'd like to better understand, why a certain package/recipe is only found, if the remote to search on, is specified explicitly. And also, why this is only needed for some packages.

See terminal output for better understanding:
```
simue@DevPC:~/repos/training/dds-wrapper-example$ conan search fastrtps
There are no packages matching the 'fastrtps' pattern
simue@DevPC:~/repos/training/dds-wrapper-example$ conan search fastdds
Existing package recipes:

fastdds/2.4.0@group/stable
simue@DevPC:~/repos/training/dds-wrapper-example$ conan search fastdds -r vsdk
Existing package recipes:

fastdds/2.3.2@group/stable
fastdds/2.4.0@group/stable
simue@DevPC:~/repos/training/dds-wrapper-example$ conan search fastrtps -r vsdk
Existing package recipes:

fastrtps/1.9.4@group/stable
fastrtps/1.10.0@group/stable
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by simue** [comment]
Oh wow, what an rtfm moment...
Must have missed the following "Unless a remote is specified only the local cache is searched."

**Comment by memsharded** [comment]
Hi @simue 

We are aware this default is not the best. We have already changed ``conan search`` in Conan 2.0 to look in remotes by default.
Cheers!
