### ISSUE TITLE
[feature] Git repo-based recipe-only remotes

### ISSUE THREAD

**Issue by CD3** [conan-io/conan#10328]
Thanks for the wonderful project, it has been a joy to use.

I think it would be very useful to have remotes that store only package recipes and could be hosted on GitHub. I currently have a git repo with recipes for many of my projects [here](https://github.com/CD3/cd3-conan-packages), and it includes a simple python script that exports all of the recipes to the local cache. The first time I run `conan install` with one of these packages, it gets compiled from source and cached locally, so future installs don't have to do anything.

I have tried to use the free Artifactory subscription, but I do not generate enough traffic for them to keep the account active. Me and my students are pretty much the only people using the libraries on a regular basis, and after one `conan install`, conan does not have to download anything from Artifactory anymore.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @CD3 

Yes, there is some ongoing idea of using the conan-center-index repo layout and use it in a more integrated way, which seems the use case you are suggesting. The only thing is that at the moment the priority is Conan 2.0, and this will need to wait after that.

> I have tried to use the free Artifactory subscription, but I do not generate enough traffic for them to keep the account active. Me and my students are pretty much the only people using the libraries on a regular basis, and after one conan install, conan does not have to download anything from Artifactory anymore.

There is a very simple trick for this: create a scheduled Github action that downloads a file (directly from the URL, without using Conan) from your Artifactory every 5 days, and you will be good. I have seem other users doing it, and it seems a relatively easy thing to do.

**Comment by CD3** [comment]
I suspected you may already be thinking about it, and the Conan- enter repos seemed like a logical place to start. I'll wait for 2.0 and look forward to the progress.

And thanks for the Artifactory tip, I didn't think of using actions.
