### ISSUE TITLE
[question] package_revision_mode and conan-center/external dependencies

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10329]
We've recently decided to set the default_package_id_mode = package_revision_mode to alleviate some issues we were running into with binary compatibility (applications unexpectedly crashing using binaries pulled using conan), and that has caused a number of external dependencies (most pulled from conan-center) to need be rebuilt, with at least one failing to build. Given that the application worked with default_package_id_mode = semver_direct_mode and it's mainly our code that could change and cause issues I'm wondering if there's a way to prevent the dependencies we're pulling from conan-center from rebuilding with package_revision_mode.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by nichmj01** [comment]
I was able to get all the dependencies built so this is no longer an issue. 

Maybe doing something with compatible packages (https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#compatible-packages) would have also addressed the issue but for now I don't have the time to investigate/figure out how that mechanism works.

**Comment by memsharded** [comment]
Hi @nichmj01 I think you would be interested in reading https://github.com/conan-io/tribe/pull/30, we are proposing to remove ``package_revision_mode`` in 2.0. ``recipe_revision_mode`` should be more than enough for tracking any possible source change and requiring binaries to be rebuilt, without going to the package revision level.

**Comment by nichmj01** [comment]
Hey @memsharded: Thanks for pointing to that post and the suggestion to use `recipe_revision_mode`. I didn't wrap my head around it initially and needed to really experiment with how `package_revision_mode` works but now I see that `package_revision_mode` is way more restrictive than I understood. A behavior similar to that of `recipe_revision_mode` is what I was really looking for.

Ideally what I would like is to have package_id be based on a hash of the actual source files that are used during the build. If you export your sources in the recipe and use revision_mode = hash, I think this works as I would like as it seems the RREV is based on the contents of the export and export_sources folders. The downside of this is that we have to export the source with the package which we would prefer not to do. Instead, we use the scm attribute to point to the commit in a git repo but this causes the RREV to change since the commit # (scm revision) in the exported recipe (or in the exported conandata.yml) changes, even if the changes are unrelated to building the final binary (such as a CHANGELOG update). In addition, it's fairly convenient to be able to connect the package RREV to the commit # so we currently use revision_mode = scm. Which has the same issue as using revision_mode = hash and scm = {} together; the RREV changes for every commit.

Any thoughts on how I can have the package point to the source in the git repo but have the package id only change if the source used to build actually changed?

Maybe this should be a new question?
