### ISSUE TITLE
[bug] VirtualBuildEnv generated `sh` files broken when there are spaces before `=` in profile

### ISSUE THREAD

**Issue by ThomasKes** [conan-io/conan#10334]
`sh` files generated by VirtualBuildEnv generator are broken, when the profile contains environment variable definitions where the `=` character is surrounded by spaces.

### Environment Details
  * Conan version: 1.44.0
  * Python version: 3.6.9

### Steps to reproduce
Create profile with buildenv section and spaces before the `=` sign:
```bash
$ echo "[buildenv]" > profile
$ echo "CXX = clang++" >> profile
$ touch conanfile.txt
$ conan install . -g VirtualBuildEnv -pr profile
Configuration:
[settings]
[options]
[build_requires]
[env]
[buildenv]
CXX = clang++

conanfile.txt: Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator 'VirtualBuildEnv' calling 'generate()'
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
$ . conanbuild.sh
Capturing current environment in deactivate_conanbuildenv.sh
Configuring environment variables
-bash: export: `= clang++': not a valid identifier
```

### Possible Fix

Strip whitespaces in `ProfileEnvironment::loads()`:
```
diff --git a/conan/tools/env/environment.py b/conan/tools/env/environment.py
index 07545fb3..cef8ee4d 100644
--- a/conan/tools/env/environment.py
+++ b/conan/tools/env/environment.py
@@ -450,6 +450,10 @@ class ProfileEnvironment:
                 else:
                     pattern, name = None, pattern_name[0]

+                # strip whitespaces before/after =
+                name = name.strip()
+                value = value.strip()
+
                 # When loading from profile file, latest line has priority
                 env = Environment()
                 if method == "unset":
```

**Comment by memsharded** [comment]
This seems a possible fix, but there could be a potential problem: some user really wanting to have a environment variable that really starts with a space. The current approach supports this, not sure if it is a very common use case, but I have seen very unexpected things out there.

**Comment by ThomasKes** [comment]
> This seems a possible fix, but there could be a potential problem: some user really wanting to have a environment variable that really starts with a space.

Okay. Just omit the `value.strip()`. It's not necessary to fix the bug.
