### ISSUE TITLE
[bug] conan.conf proxies not working for downloading source tarball

### ISSUE THREAD

**Issue by praetorian20** [conan-io/conan#10330]
### Environment Details
  * Operating System+version: CentOS 7.8
  * Compiler+version: gcc 9.1
  * Conan version: 1.44
  * Python version: 3.6

Hello,
I'm trying to build google benchmark library from behind a firewall. I have 2 proxies configured in artifactory, one for conan-center in remotes.txt (this works) and another for github.com. The benchmark recipe is successfully fetched from the conan-center proxy but the step where the tarball is downloaded fails, it's still trying to fetch from github.com instead of my proxy URL. Am I configuring the proxy incorrectly in `conan.conf`?

This is my `conan install` command

```
CONAN_USER_HOME=$(pwd)/build build/conan-venv/bin/conan install --remote=conan-center --build=outdated --profile=build/conan_pkg/profile --install-folder=build/conan_pkg build/conan_pkg/conanfile.txt
```

This is the `[proxies]` section in `build/.conan/conan.conf`

```
[proxies]
https =
  github.com = https://artifactory.xyz.com/artifactory/github-mirror
```
I've also tried changing the scheme to `http` and having both `http` and `https` listed, none them are working. This is the output I get from the conan install command above.

```
conanfile.txt: Installing package
Requirements
    benchmark/1.6.0 from 'conan-center' - Cache
Packages
    benchmark/1.6.0:c4e0c4261b06258cf42aed6006043e5a0ddcc875 - 
Installing (downloading, building) binaries...
benchmark/1.6.0: WARN: Build folder is dirty, removing it: /path/to/conan-build/build/.conan/data/benchmark/1.6.0/_/_/build/c4e0c4261b06258cf42aed6006043e5a0ddcc875
benchmark/1.6.0: WARN: Trying to remove corrupted source folder
benchmark/1.6.0: WARN: This can take a while for big packages
benchmark/1.6.0: Configuring sources in /path/to/conan-build/build/.conan/data/benchmark/1.6.0/_/_/source
ERROR: Error downloading file https://github.com/google/benchmark/archive/v1.6.0.tar.gz: 'HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /google/benchmark/archive/v1.6.0.tar.gz (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))'
Waiting 5 seconds to retry...
ERROR: benchmark/1.6.0: Error in source() method, line 43
        tools.get(**self.conan_data["sources"][self.version], destination=self._source_subfolder, strip_root=True)
        ConanException: Error downloading file https://github.com/google/benchmark/archive/v1.6.0.tar.gz:  'HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /google/benchmark/archive/v1.6.0.tar.gz (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))'
```

conanfile.txt

```
[requires]
benchmark/1.6.0@

[build_requires]

[generators]
CMakeDeps

[options]

[imports]
```

And the profile I'm using

```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=9.1
compiler.libcxx=libstdc++
compiler.cppstd=17
build_type=RelWithDebInfo
[options]
[build_requires]
[env]
PATH=[/path/to/conan-build/build/conan-venv/bin]
```

**Comment by memsharded** [comment]
Sorry this was not responded back then.

``conan.conf`` was removed in Conan 2, there is a new ``global.conf`` now, also ``tools.get`` doesn't exist anymore, I am closing this ticket as outdated, please create new tickets if necessary.

**Comment by phbaer** [comment]
Is there any way to work around this issue? We're seeing the same (but for the kernel headers). We cannot currently use Conan 2, so we're stuck with Conan 1 and a corporate proxy (with TLS interception).

I would just need to get the download request proxied but it doesn't work (set via conan config and environment):

05:06:08  linux-headers-generic/6.5.9: Configuring sources in /root/.conan/data/linux-headers-generic/6.5.9/_/_/source/src
05:09:01  linux-headers-generic/6.5.9: .linux-headers-generic/6.5.9: ERROR: Download failed, check server, possibly try again
05:09:01  HTTPSConnectionPool(host='cdn.kernel.org', port=443): Read timed out.
05:09:01  linux-headers-generic/6.5.9: Waiting 5 seconds to retry...
05:11:49  linux-headers-generic/6.5.9: .ERROR: linux-headers-generic/6.5.9: Error in source() method, line 41
05:11:49  	get(self, **self.conan_data["sources"][self.version], strip_root=True)
05:11:49  	ConanConnectionError: Download failed, check server, possibly try again
05:11:49  HTTPSConnectionPool(host='cdn.kernel.org', port=443): Read timed out.

**Comment by memsharded** [comment]
Hi @phbaer 

This issue is closed, it might be better to open a new one.
How was this working before? Did it suddenly start failing?
If it is only failing for ``linux-headers-generic`` download and not other packages, it might be something that needs to be allowed-listed in your network configuration, from our experience, it is very common that the network admins have filters and need to be updated to include some urls.

Also, please be aware that moving to Conan 2 should be a priority, note for example that ConanCenter stopped receiving updates for Conan 1 last week: https://blog.conan.io/2024/09/30/Conan-Center-will-stop-receiving-updates-for-Conan-1.html

**Comment by phbaer** [comment]
@memsharded, you're totally right... with upgrading and opening a new ticket.

We do have TLS interception enabled and this infrastructure also has changed recently. Nonetheless, developers often have to disconnect the VPN so that packages can be downloaded.

This specific issue did not appear before because we did not build qt for Linux with Conan before.

An upgrade to Conan 2 is currently under investigation but won't happen soon. I just wondered if there was a way to pass the proxy and CA cert info to the download handler ... it seems to be ignored.

Will open a new ticket when time allows. Thanks a lot for the prompt response! :)

**Comment by memsharded** [comment]
> We do have TLS interception enabled and this infrastructure also has changed recently. Nonetheless, developers often have to disconnect the VPN so that packages can be downloaded.

Yes, this is the typical case of a VPN that interferes with downloads. The recommended solution is request to IT to allow-list the necessary domains in the VPN (there are orgs that do not allow to disable the VPN at all).

> An upgrade to Conan 2 is currently under investigation but won't happen soon. I just wondered if there was a way to pass the proxy and CA cert info to the download handler ... it seems to be ignored.

For Conan 1:

https://docs.conan.io/en/1.65/howtos/use_tls_certificates.html#how-to-manage-ssl-tls-certificates

In Conan 2 they are proper confs:
```
$ conan config list cert
core.net.http:cacert_path: Path containing a custom Cacert file
core.net.http:client_cert: Path or tuple of files containing a client cert (and key)
```
