### ISSUE TITLE
[feature] Make it possible to forward profile when using `conan search`

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#10352]
I would like to search a package via specifying the profile.
e.g:
`conan search zlib/1.2.11@ -pr gcc7 -r my_remote `

instead of specifying via `-q` again the the information from the profile

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
Marking as solved in Conan 2.2.0 implemented by https://github.com/conan-io/conan/pull/15697, where you can list packages in `conan list` passing the `--profile` argument :)
