### ISSUE TITLE
Consider overrides of ``test_requires`` in profiles

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#10353]
Following https://github.com/conan-io/conan/issues/10353, we would need to consider how to override recipes ``test_requires`` from profiles.

cc / @SeanSnyders

**Comment by memsharded** [comment]
An approach that I would like to comment in the meantime (while this issue is discussed and evaluated), that could be worth checking for your use case @SeanSnyders is the following:

- If different ``gtest`` versions can be used and are valid as ``test_requires`` of a given recipe, lets define that as a valid version range, and define in the recipe: ``test_requires = "gtest/[>=1.0 <=2.0]"`` for example for all valid 1.X versions of gtest
- With this definition, by default, it will resolve to the latest valid gtest in the range
- If a developer (or even CI) want to try a different version, it is typically enough to install the specific version in the cache, ``conan install gtest/1.3@``, and then, let the dependency resolution work and test it.

**Comment by SeanSnyders** [comment]
@memsharded Thanks for creating a new issue on this topic. I think your original issue post here should probably be linking to #10304 and not this issue itself?

Then to your second comment, the described approach can work, but does implicitly depend on the environment - which for practical usage is sometimes difficult to ensure. I would love a more explicit approach, like locking to a specific version through a command line argument or profile.

I think it probably practically a good approach to use version ranges for requirements where one is pretty sure the project team of that requirement is pedantic about semver. Using that in combo then with an explicit versioning in a profile will let 'anyone' easily _and with less side-effects_ test things out for themselves without breaking the original recipe creator's intent with the version range.
Situations we come across is to 'sell' a new version of a library to other teams and if that is easily achieved then the testing phase is easier for them and the adoption easier. This is valid for normal requirements, but also for toolchain/development requirements like `gtest` or somesuch. In the end of the day a "test" requirement is just another product used in a different part of creating another product.
Keeping toolchain requirements up to date is sometimes even more difficult to 'sell' as there is no apparent benefit for the product to be created/compiled with a new toolchain if what worked before still works. So making it easier to test (and thus roll out) new versions of the toolchain dependencies is a win for that.
I can tell a project team to "use this profile in your normal conan usage" to test out if things work for your project. Pretty explicit. If I have to tell them to "please clean your cache, and do this, do that, etc", the barrier becomes too much. And they are naturally weary of doing anything to break their current project flow.

Hope this makes some sense?

**Comment by jwillikers** [comment]
I agree completely with @SeanSnyders. Managing a large number of dependencies using the same testing frameworks is made more manageable by being able to override `test_requires` across projects. I'd rather just use `requires` with its downsides just to make the requirement easier to manage. And `gtest` doesn't actually adhere to semver but expects consumer's to live at head, i.e. a Git commit hash. This wouldn't work with version ranges and thus your workaround, @memsharded.

**Comment by memsharded** [comment]
I have been giving this a try, and it seems it is simply too big of a change to be done in 1.X scope.

There will be another way that this can be achieve in 2.0 (already released in alpha.6):

- The "override" can be added to a lockfile with the ``conan lock add`` command
- The lockfile can be applied to commands.
- It is necessary that the locked version falls in a defined version range in the recipe. We know this can be challenging for some packages with weird versioning, but that is a different problem, and we will try to implement some extension mechanism that allows for customizing versioning schemas

So moving this to Conan 2.X scope. Thanks for the feedback!

**Comment by jwillikers** [comment]
@memsharded Thanks for responding. I've also opened a related concern in issue #10847 related to dependency conflicts between dependencies that are regular requires and dependencies of a `test_requires` package. Would the lockfile approach address that problem?

**Comment by memsharded** [comment]
Conan 2 added the ``[replace_requires]`` in profiles that allows for temporary overriding of some dependencies.
Still, a better approach is adequate versioning with version-ranges and lockfiles for reproducibility, the ``[replace_requires]`` should be considered as a temporary workaround/force for dependencies.

I am adding a test that shows that ``[replace_requires]`` works for ``test_requires`` too that will close this ticket.
