### ISSUE TITLE
[2.x] conan list packages

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10354]
The "conan list packages" help say `If the reference doesn't include the recipe revision, the command will retrieve all the package IDs for the most recent revision.` but it is not working like that, the revision has to be specified always and that is not a very comfortable UI.

The use-case of the old 'conan search foo/1.0 -q "os=Windows"' is not supported anymore in `conan search` (only recipes) nor `conan list packages`. In case of recovering that use case, consider this: https://github.com/conan-io/conan/issues/10352

**Comment by memsharded** [comment]
The previous ``--table=table.html`` was removed too. It was very useful functionality, for the same purpose of the --query parameter. Consider the functionality there too.

**Comment by memsharded** [comment]
This was fixed in 2.0.X with the ``conan list <pattern>`` new syntax, also the ``-p <query>`` works now, and the ``--format=json`` works too. Closing.
