### ISSUE TITLE
[question] Is it possible to use gcc as the compiler on windows?

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan#10369]
Looking at the packages in the conan center, if you select the option "windows" for the OS they all select VS as the compiler.

Moreover trying to manually set the compiler to gcc through a bash terminal returns the following:

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

```
conan install . -if winblows_build -s compiler="gcc"
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: : 'settings.compiler.libcxx' value not defined
```

Can conan handle this use case at all?

**Comment by memsharded** [comment]
Hi @Makogan 

You need to fully specify your gcc compiler in your settings. In your case you are missing the compiler version and compiler libcxx definitions. You can pass ``-s compiler.version=7 -s compiler.runtime=libstdc++11`` to your command line (but I recommend creating a ``win_gcc`` profile and using it.

**Comment by Makogan** [comment]
Thank you!
