### ISSUE TITLE
[question] Setting conan environment variables inside conanfile

### ISSUE THREAD

**Issue by pasrom** [conan-io/conan#10360]
Is it good practice to set conan environment variables inside the conanfile? For example:
```
os.environ["CONAN_SKIP_BROKEN_SYMLINKS_CHECK"] = "True"
```
or
```
def package_info(self):
        self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "share", "buildroot", "toolchainfile.cmake")
```

Thank you!

**Comment by memsharded** [comment]
Hi @pasrom 

You mean for the consumers of the current package? 

yes, defining the ``os.environ`` directly is a bad practice, please don't do that. That pollutes the global environment for all recipes and Conan. 

You have different mechanisms to define information for consumers. I'd recommend using the more modern ``self.buildenv_info`` (and in general all the tools in this section: https://docs.conan.io/en/latest/reference/conanfile/tools.html), to define the environment. Then, you might want to check the  new build-system integrations (for cmake, check: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html). These new integrations use ``[conf]`` as a way to pass information, not environment variables. You might want to use the ``tools.cmake.cmaketoolchain:user_toolchain`` conf to define  the user toolchain (which can be passed via ``conf_info`` to consumers). All these new tools are experimental, but they are the future, as they will be the ones in 2.0, and the other will be removed, and 2.0 is already in alpha stage.

**Comment by pasrom** [comment]
@memsharded, thank you for your quick reply.

Using `tools.cmake.cmaketoolchain:user_toolchain` works great.

Setting `os.environ["CONAN_SKIP_BROKEN_SYMLINKS_CHECK"] = "True"` was intended only for building the "toolchain conan package", because it throughs an error in the packaging step. I will investigate a little further to build a MEW and create a new issue.

**Comment by memsharded** [comment]
Good, nice to hear it is working fine.

Regarding symlinks, you might want to check the new 1.44 release blog post: https://blog.conan.io/2022/01/17/New-conan-release-1-44.html

It presents one of the new features: tool to handle symlinks. Because in the future, all the logic that now the ``self.copy()`` is trying to do inside ``package()`` will be dropped, and symlinks will be packaged as-is, even if they are broken.
