### ISSUE TITLE
Consider not using the CACHE in conan install

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1036]
There is the issue https://github.com/conan-io/conan/issues/1015, which is creating problems due to the caching. But not only because of this. 

It is true, that caching of settings/options/env is necessary for build, source, package, etc conan commands. But maybe ``conan install`` should always make explicit the inputs, via command line. "Explicit is better than implicit". Same for ``conan test_package``.

Even if this can break something, it is extremely easy to fix, just provide a profile or settings in the command line, i.e. nothing to fix inside conan, just in the conan command invocation by users.

What do you think?

**Comment by tru** [comment]
Yeah I am for this. This was really hard to find and debug when I ran into it the other day.

**Comment by sztomi** [comment]
Me too, I regularly test a package with different settings and I often run into a situation where I just end up deleting the whole package directory.

> But maybe conan install should always make explicit the inputs, via command line

I'd say it should work with defaults, but if the settings are provided, conan should use those. Is this what you mean by this?

**Comment by sztomi** [comment]
OK now I understand, in this case I fully support not using a cache, that is more intuitive.

**Comment by memsharded** [comment]
@sztomi Cool, thanks!

**Comment by SSE4** [comment]
yep, I've run into the same issue with cached conaninfo.txt which was very hard to debug (I've spent several hours until found problem via procmon) - so yep, I think it makes sense to avoid such caching

**Comment by memsharded** [comment]
So we consistently agree, perfect. Yes, sure, it will be removed for next 0.21 release.

**Comment by memsharded** [comment]
Released in 0.20.2
