### ISSUE TITLE
[feature] default cppinfo.builddirs

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10362]
- Remove the default "" from cppinfo.buildirs
- Clean the CMakeDeps code so it is not necessary to clear the root folders to avoid setting them to the CMAKE_PREFIX_PATH (PR SpaceIm)
- Document the migration path: Remove the '' from builddirs or use assign and not append.

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/10394
