### ISSUE TITLE
[question] How to use CONAN_V2_MODE for only one package

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#10375]
In our   libA with `conanfile.py` we have a 
`os.environ["CONAN_V2_MODE"] = "1"`
but that is to intrusive, I think because when libA is used as a dependency, suddenly the env variable is set and pollutes other dependency conanfile.py...

My question is, how can we activate CONAN_V2_MODE for only one receipt (conanfile.py) ?

**Comment by memsharded** [comment]
Hi @gabyx 

Not, it is not possible, that env-var is global, doesn't work at the recipe level.

In any case, it would be much better, now that the alpha release is already in PyPI, to start preparing a separate CI job or something that runs it in parallel and reports. That will be the real Conan v2 Mode  :)
