### ISSUE TITLE
[question] conan package without prebuilt binaries

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#10376]
Hi,

Is it possible to deploy a conan package which only contains the recipe?
So that every time someone use a package he must rebuild it on his own system?
Has this something to do with the [*default_package_id_mode*](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#default-package-id-mode)?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Of course you can upload only the recipe to the server, so users will be forced to build from source in their systems. Just avoid using the ``--all`` flag in ``conan upload``.

That is the basic, there might be other possibilities, like the in-recipe ``build_policy = "missing"`` (or ``always``) that forces the build from source when necessary or always, but those have other side issues (like ``always`` really blocks uploading binaries, and it will require modifying the recipe to allow it)

**Comment by snailcatcher** [comment]
Thanks for your answer.
Actually I think asked the wrong question.
The real problem is, that I want to install a package without building it and without having a valid prebuild for my system.

I think it is possible to do something like that by marking a package as *header_only*, but I'm not sure what side effects this would have. Is there a better solution? I want the system on which I run the *conan install* to decide whether I need a prebuild package or not.

**Comment by memsharded** [comment]
I am not sure what is exactly your use case. Indeed marking things as "header_only" doesn't sound a good approach.

Using ``conan info`` does actually brings only the recipes, computes the dependency graph and reports information without actually fetching or installing binaries. Is this what you want?

**Comment by snailcatcher** [comment]
Not exactly, but I got the problem, that the client can not decide which build it should use if there a multiple possible matches.
But I think I kind of found what I was looking for here:
https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html

But there is one thing I don't get. I think I do not use conan like it was intended to work.
My build process looks like a *header_only* package with unittests, like here: https://docs.conan.io/en/latest/howtos/header_only.html#with-unit-tests
But our packages contain C source files, header files and a .lib file, for transitiv dependencies.

On some of my systems I want to use the header and source files and on some other I want to use the header and lib files.
Is this even possible?

**Comment by memsharded** [comment]
> On some of my systems I want to use the header and source files and on some other I want to use the header and lib files.
Is this even possible?

It might be possible, certainly not the most common approach, but I think you can:

- When you do ``package()``, package also the sources inside a ``src`` folder in the final package.
- Consumers always have access to the folder something like ``os.path.join(self.dependencies["mypkg"].package_folder, "src")`` will give you that location, which you can use in the ``build()`` method of the consumers.
- Of course you really need to be very careful with duplicated symbols and similar problems, if in the same dependency graph you have packages that link the provided binary library, and some other packages that build and embed that source code, unless you have strict isolation (via shared libraries and hidden symbols), you will end with duplicated symbols, won't you?

If you are talking about completely different products (dependency graphs), then you might instead use a package ``options = {"source-only": [True, False]}. When that option is True you only package the sources (and can declare ``self.info.header_only()`` to avoid having multiple package binaries), and when it is False, then you package the normal pre-compiled binary.

**Comment by snailcatcher** [comment]
What you mentioned in your last sentence is a good solution for my use case.
Thanks a lot for clarification of the mechanism.
I will close this issue now.
