### ISSUE TITLE
PYTHONPATH could be automatically handled

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1037]
Refactoring `tools.environment_append` context manager to manage `PYTHONPATH` variable.
That way PYTHONPATH would be set automatically before `source`, `build`, `package` and `imports` from self.env_info objects.

**Comment by memsharded** [comment]
Ok, doesn't sound bad. In the past I proposed an explicit activation for the PYTHONPATH for consumers, a conservative approach, just to make sure we were not messing with the paths. I think it could be done, I would like to get the feedback of @tru here, what do you think? Better explicit in conan recipes or automatic by conan?
