### ISSUE TITLE
[bug] Transitive dependencies not working when defining layout() method

### ISSUE THREAD

**Issue by JonathanGirardeau** [conan-io/conan#10377]
### Environment Details
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc version 9.3.0
  * Conan version: 1.44.1
  * Python version: 3.8.10

### Steps to reproduce 
I have started defining layout method in order to use the editable mode with my packages. Unfortunately, it breaks the compilation.
I have reproduced the issue in a minimized scope:   
- "main" package depends on "dep" package
- "dep" package depends on "spdlog" package (a log lib which can be found in conan center)

I create the package "dep":
`conan create . user/channel -s build_type=Release`

I install the package "main":
`conan install . --install-folder cmake-build-release-linux-x86_64 -s build_type=Release`

I build the package "main":
`conan build . -bf=cmake-build-release-linux-x86_64 -if=cmake-build-release-linux-x86_64`

I get this build error:
```
[ 50%] Building CXX object CMakeFiles/main.dir/code/src/main/Main.cpp.o
/usr/bin/c++  -D_GLIBCXX_USE_CXX11_ABI=0 -isystem /home/developer/.conan/data/dep/0.0.0/user/channel/package/421a8345663de82d75acc93ba82ec83e610716b6/include  -m64 -O3 -DNDEBUG   -std=c++17 -o CMakeFiles/main.dir/code/src/main/Main.cpp.o -c /mnt/development/bug-conan-transitive-deps/main/code/src/main/Main.cpp
In file included from /mnt/development/bug-conan-transitive-deps/main/code/src/main/Main.cpp:2:
/home/developer/.conan/data/dep/0.0.0/user/channel/package/421a8345663de82d75acc93ba82ec83e610716b6/include/dep/Dep.hpp:4:10: fatal error: spdlog/spdlog.h: No such file or directory
    4 | #include <spdlog/spdlog.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

```
It seems the dependencies of "dep" are not used in the compilation command.

"main" conanfile.py:
```
from conans import ConanFile, CMake, tools

class MainConan(ConanFile):
    name = "main"
    version = "0.0.0"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    exports = "CMakeLists.txt"
    exports_sources = "code/src/*"
    requires = [("dep/0.0.0@user/channel")]

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def build(self):
        cmake = CMake(self)
        cmake.verbose = True
        cmake.configure(source_folder=".")
        cmake.build()
```
"dep" conanfile.py:

```
from conans import ConanFile, CMake, tools

class DepConan(ConanFile):
    name = "dep"
    version= "0.0.0"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}
    generators = "cmake"
    exports = "CMakeLists.txt"
    exports_sources = "code/src/*"
    requires = [("spdlog/1.9.0")]

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
    
    def layout(self):
        pass
     
    def build(self):
        cmake = CMake(self)
        cmake.verbose = True
        cmake.configure(source_folder=".")
        cmake.build()

    def package(self):
        self.copy("*.h", dst="include", src="code/src/")
        self.copy("*.hpp", dst="include", src="code/src/")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["dep"]
```
I only defined the layout method here because it seems to trigger the issue. If I remove the layout method from the "dep" conanfile.py, and recreate the "dep" package, the build would succeed.

Here is the git repository to reproduce the issue yourself:
[bug-conan-transitive-deps](https://github.com/JonathanGirardeau/bug-conan-transitive-deps)

**Comment by memsharded** [comment]
Hi @JonathanGirardeau 

It seems that you are using the old ``cmake`` integration. Note that the generators and helpers that do correctly understand the ``layout()`` are those in ``from conan.tools.cmake import CMake`` (and ``CMakeToolchain`` and ``CMakeDeps``, from: https://docs.conan.io/en/latest/reference/conanfile/tools.html)

It is very possible that the old integrations do not follow the layout, and thus might not find the generated files, for example. A good starting point for the new integrations is the ``conan new hello/0.1 --template=cmake_lib``.

**Comment by JonathanGirardeau** [comment]
Hello @memsharded 

Thanks for the quick answer, indeed I used the old `cmake` generator and it seems to misunderstand the `layout()`.
I followed the example `conan new hello/0.1 --template=cmake_lib` and it works :+1:
