### ISSUE TITLE
Unable to connect to conan-center=https://conan.bintray.com

### ISSUE THREAD

**Issue by brucemioo** [conan-io/conan#10371]
### Environment Details (include every applicable attribute)
  * Operating System+version:Ubuntu 18.04.6 LTS
  * Compiler+version:cmake version 3.10.2 +GCC 8.4.0
  * Conan version:Conan version 1.35.2
  * Python version:Python 3.6.9

### Steps to reproduce (Include if Applicable)
conan search "lz4/1.9.1" -r=all

### Logs (Executed commands with output) (Include/Attach if Applicable)

ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

I try to run pcl for android compile script and got same error.
I find certificate is expired and invalid when i open "https://conan.bintray.com" url with brower. but "https://status.bintray.com/" certificate is valid and certificate is *.bintray.com.

Is certificate expired? or any other problems?

**Comment by brucemioo** [comment]
someone submit same issues.

**Comment by memsharded** [comment]
As a reference for other readers: bintray remote closed some time ago. The remote is "conancenter": https://center.conan.io
