### ISSUE TITLE
[question] Offline Build

### ISSUE THREAD

**Issue by maldag** [conan-io/conan#10379]
I was reading through your issues regarding doing an offline build with fixed dependencies. It would be a great feature if I'd be able to use a local git-mirror where I'd export all source files once downloaded. That would be the yocto way, which works very well for them.

So say I've installed some packages in my project and use a proxy remote for that, I'll get the metainformation of the packages as well as the export, but not the used sources which are usually held externally. If I'd get the chance to build git-source-bundles from my local cache I'd be able to store them on a git mirror / http file server / repo manager / whatever. When trying to build offline I'd like to proxy the git-clone commits in the repo mirrors by the offline mirror.

This would be a transparent solution with minimum redundance. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @maldag 

Yes, this is a feature that we have considered, mirroring or backuping sources. There was some initial attempt in https://github.com/conan-io/conan/pull/8211, was looking good, but then it was delayed for other priorities. We will most likely continue with this idea post 2.0, so if you want please track that ticket (and I can close this one as duplicated? I think the original PR captures the problem well enough)
