### ISSUE TITLE
Prevent a package from being added several times to requirements

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#1038]
It's possible that a package is getting added serveral times to the requirements/packages.

E.g.
> electric-fence/2.2.0@lasote/stable from conan.io
electric-fence/2.2.0@lasote/stable from conan.io

> electric-fence/2.2.0@lasote/stable:82b1dd29b2e9143665c77ef477100c690d719cbf
electric-fence/2.2.0@lasote/stable:82b1dd29b2e9143665c77ef477100c690d719cbf

As a consequence it's noticing later that installing it one time is fully enough

> electric-fence/2.2.0@lasote/stable: Installing package 82b1dd29b2e9143665c77ef477100c690d719cbf
electric-fence/2.2.0@lasote/stable: Looking for package 82b1dd29b2e9143665c77ef477100c690d719cbf in remote 'conan.io' 
Downloading conanmanifest.txt
[==================================================]                  
Downloading conaninfo.txt
[==================================================]                  
Downloading conan_package.tgz
[==================================================]                  
electric-fence/2.2.0@lasote/stable: Package installed 82b1dd29b2e9143665c77ef477100c690d719cbf
electric-fence/2.2.0@lasote/stable: Already installed!

Conan should prevent duplicate entries to the requirements lists in the first place.

**Comment by memsharded** [comment]
But who is adding it twice to conanfile.txt/py? The user, writing it twice? I think there was a check for that some time ago, don't know what happened to it, I have to check it.

**Comment by Croydon** [comment]
@memsharded It's not a direct dependencies of ours. But it seems to be twice a dependency of two our depedencies.

**Comment by memsharded** [comment]
That is weird. I should check it. Is it possible that some of them are using ``private`` dependencies? in that case, it makes sense. Private are private, they are duplicated in the graph. If it happens that they match in all settings/options => same binary package ID, then it will not require to build it twice. But otherwise, they are treated as separate items in the graph.

**Comment by memsharded** [comment]
I have checked the code, and it is already detecting duplicated requirements. Your above setup might come from ``private`` dependencies, in that case, it makes sense. Did you manage to check it? Please do and tell us. Thanks!

**Comment by lasote** [comment]
Yes, I think that's the case, electric-fence is private from opensssl, at least from some versions.

**Comment by Croydon** [comment]
Sorry, for the delayed answer. Yes, we are using OpenSSL which has electric-fence as a private dep.
However, I don't understand why the package is reused in the later step 

> "electric-fence/2.2.0@lasote/stable: Already installed!"

when it's private.
What's the difference between private and non-private?

I also don't see yet where the second electic-fence is coming from, is there a way to let Conan display a dep tree? Would simplify it a lot.

**Comment by lasote** [comment]
Run `conan info` and paste the output.

**Comment by memsharded** [comment]
You will soon (0.21) get at graph display with ``conan info --graph`` thanks to @austinjmorlan

**Comment by memsharded** [comment]
So, it seems this issue really isn't one, so if there is nothing else required from our side, maybe it can be closed.
