### ISSUE TITLE
[bug] Libraries in lib64 are not exported to libdir

### ISSUE THREAD

**Issue by ashley-b** [conan-io/conan#10393]
I have a library using modern CMake install syntax with no destination set so it uses the system lib path which on my system is lib64.
When I install/consume this recipe I can see the lib is set correctly but the libdir is empty.
I think this is related to the following issue #3369, #3488.

I have found two workarounds, so I keep the CMake script portable.

* Force CMake to install to lib for conan
```
def generate(self):
  tc = CMakeToolchain(self)
  tc.variables["CMAKE_INSTALL_LIBDIR"] = "lib"
  tc.generate()
```
*OR*
* Tell conan were to find it.
```
def package_info(self):
  self.cpp_info.libdirs = ['lib','lib64']
```
I feel this is some thing conan should be able to take care of

### Environment Details
  * Fedora release 35
  * gcc (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)
  * Conan version:  1.44.1
  * Python 3.10.1

**Comment by memsharded** [comment]
Conan tries to be agnostic about all these platform specific issues, and it should be kept agnostic, and instead provide tools to handle things. Take into account for example that this might happen in Fedora but not Ubuntu, but Conan has no representation or model that you are running in Fedora. Conan wraps the build systems, if the build system is doing a different thing in a different platform, Conan should be informed about it, we have tried Conan "guessing" or trying to be smart about those things in the past, and it always leads to fragile and confusing behavior.

If some system is packaging to a different folder, indeed there are mechanisms to handle that, depends on what you prefer:

- You can tell your build system, CMake in this case to output to a different folder
- You can tell your ``package()`` method to pick from a different folder (if using ``self.copy()``) or doing a rename (if using ``cmake.install()``)
- You can tell your ``package_info()`` the name of ``libdirs``. In this case it could be more conceptually correct to do something like ``if x64-arch: self.cpp_info.libdirs = ["lib64"] else: self.cpp_info.libdirs = ["lib"]``

The latest seems the less clean, and it should probably be addressed in the build and package steps.

**Comment by ashley-b** [comment]
Thanks for the reply.
To give some more back story, This recipe is using the "cmake" generator and it works. It seams to set CMAKE_INSTALL_LIBDIR=lib regardless of arch setting.

Its only since I try migrating my recipe to use the new CMakeToolchain and CMakeDeps generators it stopped setting CMAKE_INSTALL_LIBDIR and as a result is not setting the LIBDIR

**Comment by memsharded** [comment]
I see, indeed the previous integration was setting a lot of things:

```python
            if self._conanfile.package_folder:
                definitions["CMAKE_INSTALL_PREFIX"] = self._conanfile.package_folder
                definitions["CMAKE_INSTALL_BINDIR"] = DEFAULT_BIN
                definitions["CMAKE_INSTALL_SBINDIR"] = DEFAULT_BIN
                definitions["CMAKE_INSTALL_LIBEXECDIR"] = DEFAULT_BIN
                definitions["CMAKE_INSTALL_LIBDIR"] = DEFAULT_LIB
                definitions["CMAKE_INSTALL_INCLUDEDIR"] = DEFAULT_INCLUDE
                definitions["CMAKE_INSTALL_OLDINCLUDEDIR"] = DEFAULT_INCLUDE
                definitions["CMAKE_INSTALL_DATAROOTDIR"] = DEFAULT_SHARE
```
It was decided to remove them, because they would be messing with possible user values (lets say, consumer only projects, that they want to install to system locations), but lets have a second look at this.

**Comment by memsharded** [comment]
Lets try the ``CMakeToolchain`` to define it (CMAKE_INSTALL_LIBDIR only at the moment, which is the evidence that we have that is necessary, no need to do all variables), because trying to manage the variability of Linux distros and the lib64 folder seems complicated and fragile

**Comment by lasote** [comment]
Related with #10430 
It might be necessary to adjust in AutotoolsToolchain (apart from the prefix that should be always set) the "lib" and probably "bin" (to avoid sbin) prefixes.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/10672 is changing the default install folders, obtained from ``cpp_info`` information.
It is important that this is defined in the ``layout()`` method to be taken into account.
