### ISSUE TITLE
[suggestion] Make documentation for integrating conan into bazel more clear

### ISSUE THREAD

**Issue by kkpattern** [conan-io/conan#10399]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Currently, the [documentation](https://docs.conan.io/en/latest/integrations/build_system/bazel.html) for integrating conan into bazel is missing the `conan install .` instruction. For someone coming from the bazel side that is not so familiar with conan, one may have a hard time understanding how the `conandeps:dependencies.bzl` is generated.

The documentation also doesn't mention put `BazelDeps` in the generators.

We can update the document like this :

---

If you want to declare Conan dependencies in your project, you must do it, as usual, in the conanfile.py file with BazelDeps as the generator. For example:

```python
class BazelExampleConan(ConanFile):
    name = "bazel-example"
    ....
    requires = "boost/1.76.0"
    generators = "BazelDeps"
```

Then, execute the following command to generate the actual Bazel dependencies.

```bash
conan install .
```

This will generate a directory named conandeps which contains all the conan dependencies.

Then, tell Bazel to use that dependencies by adding this to the WORKSPACE file:

```
load("@//conandeps:dependencies.bzl", "load_conan_dependencies")
load_conan_dependencies()
```

---

If this is OK, I'd like to create a PR for this.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/10812 has provided an improved integration, including ``conan new --template=bazel_lib`` templates, which will really help to document and help getting onboarded the integration. Will be documented for 1.47, so closing this.
