### ISSUE TITLE
[question] Get the name of the package tested in the test_package recipe

### ISSUE THREAD

**Issue by foundry-markf** [conan-io/conan#10396]
Hi,

So far, all of our recipes specify their `name` attribute.

I've been experimenting with omitting this from the recipe, and specifying it on the `conan create` command line (i.e. a full package reference on the cmd line). This works fine. The broader context is being able to reuse recipes in some niche areas, which currently call for a separate (virtually identical) recipe.

The trouble I hit was in the test_package for what I was looking at. Often, we need to pull out options from the package being tested in order to configure the test, and of course, the name used in `self.options["..."].some_option` is no longer fixed.

I had a poke around the Conan source to see if there was a property on the recipe to get the principle dependency for the test_package. There didn't seem to be one dedicated for it on the test_package itself, but since I could see `self.requires`, populated by Conan itself, I could iterate it in the test_package recipe in order to see these, e.g.

```
for pkg_name, _ in self.requires.iteritems():
   ...
```

If the test_package doesn't specify any additional requirements, this suffices, but I feel there could be some ambiguity there in the more general sense, i.e. which name is of the package being tested when there are many?

I had a look through Conan Centre recipes too, and could only see literal strings being used in this context again.

Did I miss a property for this purpose?
What do you think to my workaround?

Thanks,
Mark

P.S. Realise that the `Requirements` class subclasses `OrderedDict`, but I didn't want to assume I knew the order if changes happen in the future. I can use `pkg_name_tested = next(iter(self.requires))` if that assumption could hold.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @foundry-markf 

We have changed in 1.44 the way ``test_package`` is supposed to work. Please have a look to https://docs.conan.io/en/latest/conan_v2.html#explicit-test-package-requirement, and ``self.tested_reference_str``

**Comment by foundry-markf** [comment]
Yay, it's been pre-empted! I hadn't seen that change go in. Thanks!

**Comment by memsharded** [comment]
Cool, then, can this issue be closed? Did you already try it?

**Comment by foundry-markf** [comment]
Tested just now.

(env38) D:\dev\SharedTech\gitlab-ci\recipes>conan --version
Conan version 1.44.1

with this in the test package recipe

```
        pkg_name_tested = next(iter(self.requires)) # code I previous had working
        assert pkg_name_tested == self.tested_reference_str.split("/")[0] # just added now
```

If it was the reference itself available, rather than the string representation, I suspect I could've used a `name` property? But, easy enough to get it from the string.

So yes, happy to close. Thanks!

**Comment by memsharded** [comment]
> If it was the reference itself available, rather than the string representation, I suspect I could've used a name property? But, easy enough to get it from the string.

Yes, this is the reason we called the property ``self.tested_reference_str``, to leave option for a future reference ``self.tested_reference``, because it was also confusing doing ``self.requires(self.tested_reference)`` (our first design), and having ``requires()`` complain that it wasn't a string, and ``str()`` and ``repr()`` have different meanings for a reference (the one to be used is actually ``self.requires(repr(self.tested_reference))``.


So yes, lets attach to the string ``self.tested_reference_str`` at the moment, it seems to be working and simple enough, if this keeps happening we will re-consider to add the reference too. Thanks!
