### ISSUE TITLE
[feature][MesonToolchain] Improve Android cross-compilation

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#10407]
Cross-compiling for Android requires some extra definitions (check this test https://github.com/conan-io/conan/blob/develop/conans/test/functional/toolchains/meson/test_cross_compilation.py#L154)

We should manage some basic built-in flags as we already did in this PR for Apple cross-compilation: https://github.com/conan-io/conan/pull/10174

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/10908
