### ISSUE TITLE
[feature] More centralized `conf` variables definition

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#10406]
We're using a bunch of times this piece of code:

```python
xxxx_conf_value = conanfile.conf["xxxx.xxxx.xxxx:key"]
```
But we're not listing or centralizing these conf-keys so it could become a mess to use/know any of the existing flags. For instance, this PR https://github.com/conan-io/conan/pull/10405

**Comment by memsharded** [comment]
Overkill at this moment, lets wait
