### ISSUE TITLE
[feature] Packages in editable mode should support force-building

### ISSUE THREAD

**Issue by jkuebart** [conan-io/conan#10400]
Let's suppose we have a setup like this.

`lib0/conanfile.py`:
```
from conans import ConanFile

class Lib0Conan(ConanFile):
    name = "lib0"

    def build(self):
        print("build lib0")
```

`lib1/conanfile.py`:
```
from conans import ConanFile

class Lib1Conan(ConanFile):
    name = "lib1"
    requires = "lib0/[>=0]",

    def build(self):
        print("build lib1")
```

`app/conanfile.py`:
```
from conans import ConanFile

class AppConan(ConanFile):
    name = "app"
    requires = "lib1/[>=0]",

    def build(self):
        print("build app")
```

That is, three packages `app -> lib1 -> lib0`.

We can then build all three packages using the sequence
```
conan export lib0 /0.0@
conan export lib1 /0.0@
conan install -b missing -if app/build app /0.0@
conan build -bf app/build
```
The packages `lib0` and `lib1` will be built in the correct order during the `install` step.

If we wanted to force rebuilding of `lib0` and all the dependencies up to `app`, we could use the command
```
conan install -b cascade -b lib0 -if app/build app /0.0@
conan build -bf app/build
```
Conan would automatically rebuild `lib0` and `lib1` in the correct order during the `install` step.

Now suppose if we wanted to work on `lib0`, so we put it into editable mode:
`layout.ini`:
```
[build_folder]
build
```
```
conan editable add --layout layout.ini lib0 lib0/0.0
```
If we now wanted to rebuild `lib0` and all the dependencies up to `app`, we might again want to use the command
```
conan install -b cascade -b lib0 -if app/build app /0.0@
```
However, we get:
```
Configuration:
[settings]
[…]
[options]
[build_requires]
[env]

Version ranges solved
    Version range '>=0' required by 'conanfile.py (app/0.0)' resolved to 'lib1/0.0' in local cache
    Version range '>=0' required by 'lib1/0.0' resolved to 'lib0/0.0' in local cache

ERROR: No package matching 'lib0' pattern found.
conanfile.py (app/0.0): Installing package
Requirements
    lib1/0.0 from local cache - Cache
    lib0/0.0 from user folder - Editable
Packages
    lib1/0.0:05746cd31217bad4d11fc68ffdcbbfcf3d202f0a - Cache
    lib0/0.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Editable

Installing (downloading, building) binaries...
lib0/0.0: Generator txt created conanbuildinfo.txt
lib0/0.0: Aggregating env generators
lib0/0.0: Generated conaninfo.txt
lib0/0.0: Generated graphinfo
lib0/0.0: Generated conanbuildinfo.txt
lib1/0.0: Already installed!
conanfile.py (app/0.0): Generator txt created conanbuildinfo.txt
conanfile.py (app/0.0): Aggregating env generators
conanfile.py (app/0.0): Generated conaninfo.txt
conanfile.py (app/0.0): Generated graphinfo
```

This seems disappointing, because according to the message
```
ERROR: No package matching 'lib0' pattern found.
```
it is not possible to force-build dependencies that are in editable mode. Instead, we have to build them manually in correct dependency order using
```
conan build -bf lib0/build lib0
```

Especially in conjunction with `-b cascade` it would be extremely useful to be able to force-build dependencies that are in editable mode.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by anderson-dev** [comment]
This would be very useful and time-saving! I was surprised this was not the case as well.

Editable packages already call `generate()` to recalculate dependencies based on settings/options of the downstream project, why not call `build()` also?

**Comment by memsharded** [comment]
This has been implemented 😄 

Sorry this was not tracked properly. Conan 2.0-alpha.6 has included an ``--build=editable`` that will do exactly this, call the ``build()`` method of the editables (in the right build order).

I am closing this as implemented in alpha.6, please test it and report if necessary. Thanks!
