### ISSUE TITLE
Feature: show amount of MB to download / already up/downloaded when uploading/installing packages

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/conan#1041]
Like already asked in issue #19, I want to get the amount of bytes in a human readable format when "conan install" or "conan upload" commands in order to be able to estimate the remaining time. Would be nice if the time estimation is also shown, calculated based on the transfer rate.

**Comment by memsharded** [comment]
Yes, this could be an improvement and shouldn't be very difficult, so lets try. Notes for implementer:
- Make sure it works in different OSs, terminal output works different
- It shouldn't mess when doing output to terminals not supporting line re-write, like CI (travis, appveyor), or just redirecting output to file.

**Comment by CodingSpiderFox** [comment]
will this be implemented any time soon?

**Comment by memsharded** [comment]
Hi! It was not planned yet, we left it open as easy, to see if some contributor helped. Let's try to implement it for 0.24 (not high priority)

**Comment by memsharded** [comment]
Released in 0.25

**Comment by CodingSpiderFox** [comment]
Great, thanks!
