### ISSUE TITLE
[bug] settings.yml deemed changed on update

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#10420]
### Environment Details (include every applicable attribute)
  * Operating System+version: Win 10 x64
  * Compiler+version:
  * Conan version:
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)
Several times since initially installing 1.30, after updating conan I have had issues with settings.yml not being able to be updated for some reason and a settings.yml.new be created.
The thing is sometimes (such as with #10412 ) it is required to have the latest settings.yml.
I have never ever touched the settings.yml manually, nor knowingly though conan commands.

For some reason, updating to newer settings.yml on update does not always work correctly.
I did skip quite a few version between sporadic updates (and I would assume most people do), maybe that has something to do with it? If only the previous versions settings.yml is upgradable, then skipping a release that changes the settings.yml would probably cause this issue.

**Comment by AbrilRBS** [comment]
Sorry for the lack of communication, we should have circled back to this issue way sooner. Closing this as stale for Conan 1, as v2 has a better and more robust migration scheme (And the addition of `user_settings.yml` so users don't need to modify the original settings anymore!)

Thanks either way for taking the time to create the issue at that point, we appreciated it :)
