### ISSUE TITLE
[lock] Provide .lock mechanism for version ranges

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1042]

**Comment by petermbauer** [comment]
I was thinking of projects/packages going through different maturity stages. In the development stage you want the project to use the latest available features and bugfixes so you use version ranges and want your dependencies package to use version ranges as well. When all features are implemented, the testing phase starts where you want to use the exact same versions of all packages to be used for the project builds until e.g. a bug is found and you use an override to make use of the new Bugfix version.
This would mean to define the exact versions of all packages as overrides in the project package when moving to the testing phase, which is quite cumbersome.
Thus it would be great to be able to use the information from the conanbuildinfo.txt generated by one conan install as kind of lockfile for further builds so the exact same versions are used except overrides are defined.
Is this issue the placeholder for such a feature?

**Comment by memsharded** [comment]
Yes, @petermbauer exactly this. Sorry for not providing a detailed description.

The only important thing to take into account for this feature is that it is difficult to provide a single .lock file for the general case. Conditional dependencies are used, so there are different dependency graphs for different OS, for example. So it could be that the .lock file could be valid per-configuration, in a similar way to how manifests work.

**Comment by jnnnnn** [comment]
We are implementing this ourselves by having the conanfile.py load dependencies from a separate file (`requires.lock.yml` if present, otherwise ranged dependencies from `requires.yml`). It would be great if this was part of conan itself.

**Comment by marco-m** [comment]
> We are implementing this ourselves by having the conanfile.py load dependencies from a separate file (requires.lock.yml if present, otherwise ranged dependencies from requires.yml and generate the lockfile).

@jnnnnn any chance you could publish this ? (CC @siu)

**Comment by dobrypd** [comment]
Hi All!

Recently I was working on this problem. 
I've created a script that creates and uses lock file:
https://gist.github.com/dobrypd/71e118d284d56cb076df045d934a8bd1

I have a plan for this week to fork conan and introduce it. @memsharded what do you think about it? Does it make sense to create PR with it? 

To be clear, the script doesn't resolve all problems with version ranges. It just locks the version / update lock and uses lock. Moreover it is usable only with assumption that recipe doesn't change with the same version (it can be done by adding recipe revision to the version).

**Comment by dobrypd** [comment]
@memsharded  can it be staged to "queue"?

**Comment by kenfred** [comment]
This feature is discussed in more detail in other threads: [here](https://github.com/conan-io/conan/issues/101#issuecomment-327861606) (#101) and [here](https://github.com/conan-io/conan/issues/798#issuecomment-468290913) (#798).

Since those threads are closed, I'm assuming this will be the primary issue to track the revisions lock feature.

**Comment by dobrypd** [comment]
That's really good to hear!

I would suggest to push it even further and move to https://github.com/conan-io/conan/pull/4513 as my proposal is already implemented. Feedback will be highly appreciated.

I am already using my fork and lockfiles on daily basis, so I can share some insides. (To have little overview, the dependency graph of project that I am using it with has little more than 30 nodes and 4 levels of dependency.)

**Comment by memsharded** [comment]
This was released in Conan 1.17, documented here: https://docs.conan.io/en/latest/versioning/lockfiles.html Please try and and report in new issues if necessary, thanks!

**Comment by marco-m** [comment]
@memsharded once, more, thanks! ❤️

**Comment by memsharded** [comment]
Thanks very much to you and everyone in this thread, your ideas, feedback, help and contributions are so appreciated. Really useful. 😃
