### ISSUE TITLE
[bug][2.0] test_package folder is never cleared 

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#10422]
Hello,

I came across several issues playing around with `tool_requires` like `libcxx`/`android-ndk`, and I've recently had a lot of build failures in the `test_package` step.

It seems that the `cmake-build-release` folder is never cleared, which causes build errors when building the same package with a different profile right after (especially in a CI script).

For instance, I'm creating `libressl` with `ios-armv8` and `ios-armv7` profiles. The latter fails with the following error:

```
ld: warning: ignoring file /Users/marvin/.conan2/p/ecbd84013ff89eda/p/lib/libtls.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64
ld: warning: ignoring file /Users/marvin/.conan2/p/ecbd84013ff89eda/p/lib/libssl.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64
ld: warning: ignoring file /Users/marvin/.conan2/p/ecbd84013ff89eda/p/lib/libcrypto.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture armv7:
  "_SSL_CTX_new", referenced from:
      _main in test.c.o
  "_SSL_library_init", referenced from:
      _main in test.c.o
  "_SSLv23_client_method", referenced from:
      _main in test.c.o
ld: symbol(s) not found for architecture armv7
```

Looking in the `cmake-build-release` folder, `conan/libressl-release-armv8-data.cmake` is still around, as is the `CMakeFiles` folder.

I don't know exactly if this file is responsible of the build failure, but I've "fixed" the problem by removing `cmake-build-release` each time.

But this is very annoying in a CI script, so maybe there's something to be done in Conan?

### Environment Details (include every applicable attribute)
  * Conan version: 2.0.0a2

**Comment by memsharded** [comment]
We consciously removed the "magic" behaviors around the ``test_package`` functionality, leaving it as close to a pure consumer project as possible. That includes using the layout() and not doing any other special treatment of the build folders.

We need to discuss this scenario. There are several possibilities:
- Request the user to clean the ``test_package/build`` folder
- Customize the ``test_package/conanfile.py`` ``layout()`` method to include the desired  variants (it can be something as simple as a one liner ``self.folders.build = f"cmake-{self.settings.build_type}-{self.settings.arch}"``
- Conan doing an active ``shutil.rmtree`` of the build folder before testing. This sounds good, but we realized it is also very convenient that the build folder is not removed between runs, that makes fixing things in the ``test_package`` much faster (incremental builds).

**Comment by theodelrieu** [comment]
>we realized it is also very convenient that the build folder is not removed between runs

I think the folder removal should be the default behavior. It could be prevented by an explicit option, a bit like `cmake.verbose = True` is required when one wants to debug something.

**Comment by czoido** [comment]
Closed by: https://github.com/conan-io/conan/pull/10599
