### ISSUE TITLE
[bug] Failed conan config install

### ISSUE THREAD

**Issue by jeremy-coulon** [conan-io/conan#10421]
I have custom conan settings in my private gitlab instance.
I run `conan config install` to install these settings.
Everything was working fine with conan v1.40.4 but it fails with conan v1.44.1
It looks like conan is trying to save my file in `E:\\nosave\\.conan\\tmp_config_install\\archive.zip?sha=v1.44.1` (which is not a valid filename) instead of `E:\\nosave\\.conan\\tmp_config_install\\archive.zip`

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: VS 2019
  * Conan version: 1.44.1
  * Python version: 3.8.2

### Steps to reproduce (Include if Applicable)
```
conan config install https://gitlab.myorg.com/api/v4/projects/open-tools%2Fconan-config/repository/archive.zip?sha=v1.44.1
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Trying to download  https://gitlab.myorg.com/api/v4/projects/open-tools%2Fconan-config/repository/archive.zip?sha=v1.44.1
Downloading archive.zip?sha=v1.44.1:   0%|          | 0.00/3.46k [00:00<?, ?B/s]ERROR: Download failed, check server, possibly try again
[Errno 22] Invalid argument: 'E:\\nosave\\.conan\\tmp_config_install\\archive.zip?sha=v1.44.1'
Waiting 0 seconds to retry...
Downloading archive.zip?sha=v1.44.1:   0%|          | 0.00/3.46k [00:00<?, ?B/s]ERROR: Download failed, check server, possibly try again
[Errno 22] Invalid argument: 'E:\\nosave\\.conan\\tmp_config_install\\archive.zip?sha=v1.44.1'
Waiting 0 seconds to retry...
Downloading archive.zip?sha=v1.44.1:   0%|          | 0.00/3.46k [00:00<?, ?B/s]ERROR: Failed conan config install: Error while installing config from https://gitlab.myorg.com/api/v4/projects/open-tools%2Fconan-config/repository/archive.zip?sha=v1.44.1
Download failed, check server, possibly try again
[Errno 22] Invalid argument: 'E:\\nosave\\.conan\\tmp_config_install\\archive.zip?sha=v1.44.1'
```

**Comment by jeremy-coulon** [comment]
It fails with conan v1.41.0 too

Probably related to https://github.com/conan-io/conan/pull/9530

**Comment by memsharded** [comment]
Hi @jeremy-coulon 

If you are using a git repo, you know that you can directly use the ``git`` clone address to retrieve it and use it?
Also, have you tried the ``--type`` argument? You can specify it as a ``url`` for a zip, I think the final part of the URL is confusing it.

**Comment by jeremy-coulon** [comment]
Thanks for the tip.

Adding `--type url` doesn't work.

I am not sure that I can use a git address. What I need is to checkout a specific git tag.

**Comment by memsharded** [comment]
Maybe for the git address you can use the ``--args`` argument to pass the git clone ``--branch <tag_name>`` that you want to use?

**Comment by memsharded** [comment]
In any case, it seems the problem is in:

```python
zippath = os.path.join(tmp_folder, os.path.basename(config.uri))
```
For some reason the parsing of the uri is not removing the ``?sha`` part from ``config.uri``. We need to check if this is expected or not

**Comment by jeremy-coulon** [comment]
`--args "--branch <tag_name>"` works for me. Thank you.

**Comment by memsharded** [comment]
Trying a potential fix for the issue: https://github.com/conan-io/conan/pull/10423
