### ISSUE TITLE
[bug] tool_requires doesn't work if used in a profile

### ISSUE THREAD

**Issue by datalogics-kam** [conan-io/conan#10427]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 11.6.1
  * Compiler+version: apple-clang 13.0
  * Conan version: 1.44.1
  * Python version: 3.9.7

### Steps to reproduce (Include if Applicable)

Create a profile with `tool_requires` and try to use it.

```
# Intended for tools that are platform agnostic, like CMake. Windows specific
# tools could go in another profile that includes this one.
[tool_requires]
cmake/[~=3.21]@
```

See: https://github.com/conan-io/conan/blob/develop/conans/client/profile_loader.py#L163; `tool_requires` isn't in the allowed fields list.

But it's [documented](https://docs.conan.io/en/latest/reference/profiles.html#profile-composition) that `tool_requires` can be used. I was going to see if it fixed another problem we're having, but I can put it back to `build_requires`.

### Logs (Executed commands with output) (Include/Attach if Applicable)

(part of what our added value build system does)

```
conan lock create /private/var/folders/03/f8w5w_3s0xg5m1jphq243j_r0000gx/T/tmpbts5yt8s/conanfile.txt --lockfile-out /private/var/folders/03/f8w5w_3s0xg5m1jphq243j_r0000gx/T/tmpbts5yt8s/buildinfo.lock --build never --profile:host apple-clang-13.0-intel-cppstd-14 --profile:host build_tools --settings:host build_type=Debug --settings:host arch=x86_64 --settings:host one-of-our-products:build_type=Release
ERROR: Error reading 'build_tools' profile: ConfigParser: Unrecognized field 'tool_requires'
```

**Comment by memsharded** [comment]
Hi @datalogics-kam 

It seems the profile still uses ``[build_requires]`` syntax, not ``tool_requires``. I don't recall if it was explicit decission not to add it, but I think it might be needed for helping to the 2.0 migration, as in 2.0 it has been renamed to ``[tool_requires]``

**Comment by lasote** [comment]
Yup, looks like I forgot to enable it.
