### ISSUE TITLE
AutotoolsToolchain could use "res" as datadir instead of "share", to align with ConanCenter

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#10430]
Following conan-io/conan-center-index#9091 (comment), it could be that changing the default toolchain ``datadir`` to "res" instead of "share" would be more aligned with ConanCenter requested layouts, lets check it.

_Originally posted by @memsharded in https://github.com/conan-io/conan/issues/8476#issuecomment-1022130033_

**Comment by ericLemanissier** [comment]
My personal take on this is that using `share` folder would allow to simplify a lot of recipes which have to manually move some resources to the `res` folder, which is non-standard.

**Comment by lasote** [comment]
Looks necessary to adjust in AutotoolsToolchain always the "prefix" and probably also the "lib" to avoid "lib64" and "bin" to avoid "sbin", and of course the "datarootdir" to "res" or "share". 
In the cppinfo model, only one of "res"/"share" should be kept.

Related https://github.com/conan-io/conan/issues/10393

**Comment by SpaceIm** [comment]
I agree with @ericLemanissier, I don't understand why in the first place `res` has been chosen instead of `share`.

**Comment by memsharded** [comment]
Because it was chosen like 6 years ago, and my bias as Windows developer put there ``res``. The ``cpp_info.resdirs`` is called ``resdirs`` no ``sharedirs`` for same reason. There is simply no good default for everyone. Windows devs will probably not love if we change the ``resdirs = ["share"]`` default.

**Comment by memsharded** [comment]
New Autotools now use the defined ``cpp_info.resdirs`` as the default for autotools based install, implemented in https://github.com/conan-io/conan/pull/10672, will be in next 1.46
