### ISSUE TITLE
[question] Package links against all dependent components instead of one

### ISSUE THREAD

**Issue by wer14** [conan-io/conan#10435]
I'm trying to link against a specific Qt5 component `qtCore` for example. But for some reason `conan` links against all components that `Qt` declares. As a result I end up with a include list in a `.vcxproj` file That contains all components that Qt has.

> ...
> ..\..\..\..\.conan\f2d3ec\1\include\QtWebEngine
> ..\..\..\..\.conan\f2d3ec\1\include\QtWebEngineWidgets
> ..\..\..\..\.conan\f2d3ec\1\include\QtPrintSupport
> ..\..\..\..\.conan\f2d3ec\1\include\QtWebEngineCore
> ..\..\..\..\.conan\f2d3ec\1\include\QtPositioning
> ..\..\..\..\.conan\f2d3ec\1\include\QtWebChannel
> ...

```
class LinkAgainstQtCoreOnly(ConanFile):
    def requirements(self):
        self.requires("qt/5.12.4")

    def package_info(self):
        self.cpp_info.requires = ['qtCore']

```

The [docs ](https://docs.conan.io/en/latest/creating_packages/package_information.html)say below code snippet would work:

```
class Library(ConanFile):
    name = 'library'
    requires = "openssl/1.0.2u"

    def package_info(self):
        self.cpp_info.requires = ['openssl::ssl']
```

> In the previous example, the ‘library’ package and transitively all its consumers will link only with the component ssl from the openssl package.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gmikhaile 

Which consumer integration are you using? Not all of them might support components at the moment. It would be good to have a more detailed ``LinkAgainstQtCoreOnly`` with the generators used, the ``conan install`` command and seeing what files Conan is generating for the Qt dependency.

**Comment by wer14** [comment]
> Hi @gmikhaile
> 
> Which consumer integration are you using? Not all of them might support components at the moment. It would be good to have a more detailed `LinkAgainstQtCoreOnly` with the generators used, the `conan install` command and seeing what files Conan is generating for the Qt dependency.

**Conan version: 1.43**

**Minimal reproducible example: conan install .**

```
from conans import ConanFile

class LinkAgainstQtCoreOnly(ConanFile):
    generators = "qmake"

    def requirements(self):
        self.requires("qt/5.15.2")

    def package_info(self):
        self.cpp_info.requires = ['qtCore']
```

**Contetnts of conanbuildinfo.pri:**

> CONAN_INCLUDEPATH += "E:/.conan/fd5a22/1/include" \
>     "E:/.conan/fd5a22/1/include/QtNetwork" \
>     "E:/.conan/fd5a22/1/include/QtSql" \
>     "E:/.conan/fd5a22/1/include/QtTest" \
>     "E:/.conan/fd5a22/1/include/QtPrintSupport" \
>     "E:/.conan/fd5a22/1/include/QtWidgets" \
>     "E:/.conan/fd5a22/1/include/QtOpenGL" \
>     "E:/.conan/fd5a22/1/include/QtOpenGLExtensions" \
>     "E:/.conan/fd5a22/1/include/QtGui" \
>     "E:/.conan/fd5a22/1/include/QtConcurrent" \
>     "E:/.conan/fd5a22/1/include/QtXml" \
>     "E:/.conan/fd5a22/1/include/QtCore" \
> ...

**Files were generated:**

- conanbuildinfo.pri
- conanbuildinfo.txt
- conaninfo.txt
- graph_info.json

**Comment by memsharded** [comment]
Hi @gmikhaile 

yes, this is totally expected. The qmake integration is not multi-component yet. In fact, this integration still has not been modernized to be ready to be ported to Conan 2.0 (that is, to move it to the ``from conan.tools.qt`` package). Sometimes this modernization includes the multi-component support, if there is enough demand for it (so far only CMakeDeps and PkgConfigDeps got it), which doesn't seem the case yet for QMake.

**Comment by memsharded** [comment]
In any case, @gmikhaile if you are interested in this integration and want to try to contribute it, it would be very welcome. The fact that we don't have enough time for it doesnt mean that it cannot be done.

**Comment by wer14** [comment]
> In any case, @gmikhaile if you are interested in this integration and want to try to contribute it, it would be very welcome. The fact that we don't have enough time for it doesnt mean that it cannot be done.

Thank you for your proposition, I work with conan on my daily job, on my free time I do other stuff.

**Comment by memsharded** [comment]
> Thank you for your proposition, I work with conan on my daily job, on my free time I do other stuff.

Sure, I was not suggesting that you do it in your free time, if this is important for your job, maybe is it something that you can do on office hours as part of your job? Many Conan contributors collaborate that way, just getting permission from their companies to collaborate in some open-source projects they use.
