### ISSUE TITLE
[question] Error when using PkgConfigDeps generator

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan#10438]
I don;t know if this is a bug or user error.

I have this recipe:
```
from distutils.command.build_clib import build_clib
import os
from conans import ConanFile, tools, Meson
from conans.tools import OSInfo
from conans.tools import os_info, SystemPackageTool

class ConanFileNeverEngine(ConanFile):
    generators = "PkgConfigDeps"

    settings = {
        "os": None,
        "compiler" : None,
        "cppstd": None,
        "build_type" : None}

    def generate(self):
        self.output.error("asaaaaaaaaaaaa")
        pc = PkgConfigDeps(self)
        pc.generate()

    def layout(self):
        build_dir = '_'.join([str(self.settings.compiler).lower().replace(' ', '_'), str(self.settings.build_type).lower()])
        self.folders.build = f'build{build_dir}'
        self.folders.generators = self.folders.build
        self.folders.imports = self.folders.build
        self.folders.source = "src"
 ```

If I do conan install I get the error:
```
ERROR: conanfile.py: Error in generate() method, line 34
        pc = PkgConfigDeps(self)
        NameError: name 'PkgConfigDeps' is not defined
```

But this seems very similar to what the docs say one must do:

https://docs.conan.io/en/latest/reference/conanfile/tools/gnu/pkgconfigdeps.html

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Makogan** [comment]
I forgot to include the PkgConfigDeps python module

**Comment by memsharded** [comment]
Hi @Makogan 

You also have it duplicated, in the ``generators = "PkgConfigDeps"`` and in the ``generate()`` method. You should use one of the ways, not both.

**Comment by memsharded** [comment]
Other tips:

- Constraining the settings as you do with a dict ``{os: None...}`` is not recommended. You can remove all settings with ``settings = None``, but this is probably not recommended either, as that means that you only have 1 binary for all platforms, compilers and architectures, which is rarely the case, except for header-only libraries.
- Recall that there are more modern integrations for build systems than ``from conans import ConanFile, tools, Meson```. The modern one will be imported as ``from conan.tools.meson import MesonToolchain, Meson``
