### ISSUE TITLE
[bug] Failure for concurrent CI publishing

### ISSUE THREAD

**Issue by philipp-kaiser** [conan-io/conan#10450]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: -
  * Conan version: 1.44.1
  * Python version: Python 3.8

### Our Usecase

We use conan to publish our pre-build libraries (built by rust for different targets) for different targets: Win-x8664, Linux-x8664, Linux-armv7, Linux-armv8, ...
We do not have a real build step with conan, as we are only copying the libraries and its headers to correct positions ('include', 'lib', 'bin'). Finally we are forcing the OS and ARCH by export commands. This is working fine.

### Steps to reproduce (Include if Applicable)

We are building all targets in parallel on our CI. CI is calling upload command whenever it's ready, meaning we are uploading different target packages to the same recipe (recipe is identical). Sometimes we get following error. This is not 100% reproducible. Seems to be some concurrency problem.

My Guess:
Before upload, conan tries to read the `conanmanifest.txt` on repository to get the timestamp (checking whether upload is newer or not). But it's possible to get some point in time, where this file is currently written, therefore returning empty String, resulting in following error. Is it possible to make the repository thread safe, by adding a lock mechanism?

Current Workaround:
We need to `--force` upload to avoid this problem (seems to work so far), but i would like to check if there is already a package for this target to avoid overriding.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Commands:
`conan export-pkg .  -f -s os=${conanOs} -s arch=${conanArch}`
`conan upload --all --check -no recipe -c -r xxx xxx/0.0.0-xxx`

```
ERROR: xxx/0.0.0-xxx: Upload recipe to 'xxx' failed: invalid literal for int() with base 10: ''. [Remote: xxx]
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/conans/client/remote_manager.py", line 283, in _call_remote
	    return self._auth_manager.call_rest_api_method(remote, method, *args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/conans/client/rest/auth_manager.py", line 40, in call_rest_api_method
	    ret = getattr(rest_client, method_name)(*args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/conans/client/rest/rest_client.py", line 77, in get_recipe_manifest
	    return self._get_api().get_recipe_manifest(ref)
	  File "/usr/local/lib/python3.8/dist-packages/conans/client/rest/rest_client_v1.py", line 85, in get_recipe_manifest
	    return FileTreeManifest.loads(contents[CONAN_MANIFEST])
	  File "/usr/local/lib/python3.8/dist-packages/conans/model/manifest.py", line 78, in loads
	    the_time = int(tokens[0])
	ValueError: invalid literal for int() with base 10: ''
```

**Comment by memsharded** [comment]
Hi @Kaiser1989 

Yes, I think you are right and that is the root cause.
This is most likely already solved in Conan 2.0 (already in alpha.3), because Conan does no longer check the server manifest or timestamp. But instead, it uses the revisions. If the revision is in the server, nothing will be uploaded (by default, without -f)

In the meantime, I would recommend the following flow:

- conan export + conan upload (only recipe). As first step.
- Then do the parallel "building" or ``export-pkg`` in your case + upload.

I think that should alleviate the problem till we get to 2.0

**Comment by philipp-kaiser** [comment]
Tanks for your response,
in our case, it's not exactly clear, which task will finish first and therefore will first upload the recipe. I think we need to stay with our force solution.
Is there any good and solid solution, to ask the repository if the package already exists? Seems the `remote search` endpoint is not yet implemented.

**Comment by memsharded** [comment]
> in our case, it's not exactly clear, which task will finish first and therefore will first upload the recipe. I think we need to stay with our force solution.

I mean, you can guarantee it, just by running a job at the beginning that does a ``conan export`` (note it is not an ``export-pkg``, just an ``export``), and then uploading the recipe only. That task should take only a couple of seconds. And only after that you launch the parallel jobs for ``export-pkg``.

**Comment by philipp-kaiser** [comment]
Thanks, I will try that while waiting for Conan 2.0 ;)
