### ISSUE TITLE
[feature] Clarify how to change location for conan_paths.cmake

### ISSUE THREAD

**Issue by OleksandrKvl** [conan-io/conan#10459]
As you all know, the typical CMake workflow is `cd project && mkdir build && cd build && cmake .. && cmake --build .`. In CMakeLists.txt of my projects I always prohibit in-source builds (build without creating `build` folder, directly in the project root). I used `exports_sources` approach with:
```python
    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder=".", build_folder="build")
        cmake.build()
```
and spent hours trying to make it work because Conan generates `cmake_paths.cmake` outside of the `build` directory. Documentation for `cmake_paths` says:

> The folder containing the conan_paths.cmake (**self.install_folder when used in a recipe**) is also included, so any custom file will be located too. Check cmake_find_package generator generator.

so I tried to adjust `self.install_folder` without any success. I don't know if it's possible at all, is it?

Then I found the `layout()` method. It says

> self.folders.generators: To specify a subfolder where to write the files from the generators and the toolchains. (e.g the xx-config.cmake files from the CMakeDeps)

and [suggests](https://docs.conan.io/en/latest/developing_packages/package_layout.html#example-everything-together) this:

```python
     def layout(self):
         self.folders.source = "src"
         build_type = str(self.settings.build_type).lower()
         self.folders.build = "cmake-build-{}".format(build_type)
         self.folders.generators = os.path.join(self.folders.build, "conan")
```

I copy-pasted it and finally my build works. But I don't understand how, it makes `self.folders.generator` to point into something like `cmake-build-release/conan`. I see no such folder after build and Conan files are located directly in `cmake-build-release` (otherwise it wouldn't work because documentation suggests `include(${CMAKE_BINARY_DIR}/conan_paths.cmake)`). It's very unclear what's going on here. Actually, commenting that last line doesn't break the build...

After all I found the `cmake_layout()`, now it works and my conanfile.py looks good.
Can you please clarify what's the proper way to do this? I also don't understand why `layout()` is experimental if it's absolutely vital to build canonical CMake projects, is it possible to use some non-experimental feature to achieve my goals?
And one more thing, it would be so nice to have in docs a tutorial how to gracefully integrate canonical CMake projects with Conan. I'm now on this path and it's pretty painful even though I watched all your courses and read the docs...

**Comment by memsharded** [comment]
Hi @OleksandrKvl 

I think the main issue is that the old generators do not follow the layout. It was too difficult to do it without breaking, so the new layout() only applies to the generators in the new ``from conan.tools.xxxx`` domains.
The new generators, in this case the ``CMakeToolchain`` has implemented the ``cmake_paths`` functionality, will indeed follow the ``generators`` folder as expected.

**Comment by OleksandrKvl** [comment]
Do you mean that `cmake_paths` uses only `folders.build` but not `folders.generators` and that's why it works now? Ok but is there any other non-experimental or "right" way to set the path for `conan_paths.cmake`?

**Comment by memsharded** [comment]
> Can you please clarify what's the proper way to do this? I also don't understand why layout() is experimental if it's absolutely vital to build canonical CMake projects, is it possible to use some non-experimental feature to achieve my goals?

It is experimental because it is pretty new, still a bit unstable, so we might need to do breaking changes to it. Also, because it also  can only work fully with other experimental generators like CMakeDeps and CMakeToolchain. All these components together is what implement the "canonical" and "transparent" cmake integration, something that the previous integration (cmake, cmake_paths, etc) couldn't provide (at least without breaking).

> And one more thing, it would be so nice to have in docs a tutorial how to gracefully integrate canonical CMake projects with Conan. I'm now on this path and it's pretty painful even though I watched all your courses and read the docs...

Yes, we know. The project contains now 2 implementations:
- The legacy one that is mostly used in docs and is the one used in the courses. These ones was simply not capable of providing a transparent CMake integration
- The modern one, Conan 2.0 ready, still experimental

We try to warn the users to not mix both, for example this is the warning note in the ``layout`` docs:
https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html

``` 
This is an experimental feature subject to breaking changes in future releases. 
The layout() feature will be fully functional only in the new build system integrations (in the conan.tools space). 
If you are using other integrations, they might not fully support this feature.
```


> Do you mean that cmake_paths uses only folders.build but not folders.generators and that's why it works now? 

yes, the ``folders.build`` has been mapped to ``self.build_folder`` that the legacy generators were already using, so that part is ok. But the ``generators`` folder is completely new, and introducing it is the thing that would be breaking.

> Ok but is there any other non-experimental or "right" way to set the path for conan_paths.cmake?

I think you might try with the ``--install-folder=xxx`` cli argument, have you tried that one?

**Comment by OleksandrKvl** [comment]
Thanks for the detailed answer,

> I think you might try with the `--install-folder=xxx` cli argument, have you tried that one?

I got this problem during `conan create .` call. AFAIK, `--install-folder` is only for `conan install`, isn't it?

**Comment by memsharded** [comment]
> I got this problem during conan create . call. AFAIK, --install-folder is only for conan install, isn't it?

Yes, that is true, sorry, didn't realize it was for ``conan create``. ``--install-folder`` not in create.

There could be something that you could try as a workaround: use the ``generate()`` method to change location of the generated ``cmake_paths.cmake`` file, like an ``os.rename()``

**Comment by OleksandrKvl** [comment]
I think that my main fallacy was that I thought Conan is already super-stable and super-integrated with everything because it's been there for years so I tried to rely on non-experimental approaches :) I will continue to use `cmake_layout()` for now and will switch to `CMakeToolchain` in the future. I'm leaving this issue open but since my problem has been resolved feel free to close it if you don't plan to update related documentation, thanks for you help :)

**Comment by memsharded** [comment]
> I think that my main fallacy was that I thought Conan is already super-stable and super-integrated with everything because it's been there for years so I tried to rely on non-experimental approaches :) 

Yes, you are right. The "stable" build system integrations were "frozen" like 4 years ago, and they were lacking features (like transparent integration) and sometimes had some bad defaults. But as they were frozen, they had some difficult to fix things without breaking, so they are stable, but not that good. So we tried to solve all those problems in the new integrations, so we could introduce them without breaking the others, but then the transition and mixing the two approaches is making the whole of it a bit messy and confusing.

We are very focused on 2.0, now in writing the new 2.0 docs, so I think we will better focus on getting that out as soon as possible, I think this one can be closed. Thanks very much for all the feedback! :)
