### ISSUE TITLE
[feature] `ConfDefinition` more powerful

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#10451]
Replicate the `ProfileEnvironment` class in terms of being able to append, prepend, unset or define values.

The idea is to get this flow running:

**profile**
```
.....

[conf]
tools.build.flags:CXX_FLAGS+=flag1
tools.build.flags:CXX_FLAGS=+flag4
tools.build.flags:C_FLAGS=!flag2
tools.build.flags:LD_FLAGS=flag1 flag2 flag3
```

**Comment by memsharded** [comment]
Implemented by https://github.com/conan-io/conan/pull/10537
