### ISSUE TITLE
[develop2] Create "mocks" for 1.X -> 2.0 transition

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#10455]
Some mocks to allow 1.X syntax might be necessary:

- cpp_info.names and cpp_info.filenames

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/10585 will close this, if there is any other field that needs to be added, please tell.

**Comment by czoido** [comment]
Closed by: https://github.com/conan-io/conan/pull/10585
