### ISSUE TITLE
Feature: show amount of time taken by build

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/conan#1045]
As a developer, I want to see, how long it took from the start of the command "conan build" until the process exited.

**Comment by memsharded** [comment]
I think this feature is already implemented by the logger. If you enable it, you will get full logs with lots of information, also the build times:

```
{"_action": "PACKAGE_BUILT_FROM_SOURCES", "_id": "libcurl/7.50.3@lasote/testing:7f185c3240cef8b455b50571c65930ea3069fb08", "duration": 66.54091906547546, "log": null, "time": 1488296702.184204}
```
Moreover, it is specifically designed as json, so it is easy to parse and create reports/extract data easily.

Read about it here: http://docs.conan.io/en/latest/howtos/logging_and_debugging.html

**Comment by CodingSpiderFox** [comment]
Thx. Will try that
