### ISSUE TITLE
[feature] better error output with custom generators

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#10465]
When one writes a custom generator, and there are syntax errors, they are quite hard to catch:

```
conanfile.py (myapp/1.0.0): Generator txt created conanbuildinfo.txt
conanfile.py (myapp/1.0.0): ERROR: Generator my_generator(file:None) failed
unexpected ']'
ERROR: unexpected ']'
```

Some additional context in the error message (e.g. line numbers) would extremely help during the development stage.

**Comment by memsharded** [comment]
Have you tried definining ``CONAN_VERBOSE_TRACEBACK`` env-var? I think that should show a full trace.

In conan 2.0, errors in generators will show the full traceback, always.
