### ISSUE TITLE
[question] Ship buildable-from-sources projects

### ISSUE THREAD

**Issue by vdsbenoit** [conan-io/conan#10479]
### Context
We use conan to package our company libraries. We have a private conan registry where we store them. Some of our libraries depends on others of our private libraries. 

### Issue
In some cases, we need to share projects with collaborators who are external to the company. These collaborators do not have access to our conan registry. 

### Overall question
If we need to share a project that depends on some other internal projects (i.e. conan dependencies) to an external collaborator, how could we ship our project in a self-contained way? I mean, how could we enable our collaborators to build from source ? 

Prior using conan, we used to attach the dependencies inside the repository and configure CMake to use them. 

### External registry
We could upload our libraries to an external private registry the collaborators have access to.

**Outcome:** some legal reasons, we cannot upload our private conan packages to an external registry. 

### conan install & conan build
I thought about installing the dependencies of my project in a `.build` directory:
````bash
conan install . --install-folder .build 
````
Then ship my project to our collaborators with the `.build` directory and ask them to run
````bash
conan build . --build-folder .build
````

**Outcome:** it does not work. The files in `.build` point to file from the conan cache, which is local.

### Deploy generator
I then thought the [deploy generator](https://docs.conan.io/en/latest/reference/generators/deploy.html) could be a good track. Thus I tried 
````bash
conan install . --install-folder .build -g=deploy
````

**Outcome:** it does not work. The `.build/conanbuildinfo.cmake` file still contains paths to the conan cache, which is local.

### VirtualEnv
I read about the [Virtual Environments](https://docs.conan.io/en/latest/mastering/virtualenv.html#virtual-environment-generator).

**Outcome:** the virtual environments do not bundle the packages. They point to the conan cache too.

### Conclusion

A solution could be an option that creates a kind of self-contained virtual env. I mean something similar to the current virtual env but that would point to binaries included in the virtual env directory.

## Other existing GitHub issues

I have searched for other issues on this topic. I found #1061. However, the goal there is to ship self-contained binaries, not the source code. 

---

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @vdsbenoit 

We are aware of this. One of the root causes is that there is no general, robust, collision-free "deploy" output. The only place where binaries will certainly not conflict is the Conan cache.

So even if it is possible to ``deploy`` them to a user folder, that doesn't scale. For example: how many different binaries are being distributed to the final user, just Release ones? Or maybe Debug and Release ones? Or maybe 64 and 32 bits and Debug and Release 4 combinations? How should those binary artifacts be put in the user folder so they don't conflict? In the Conan cache the "package_id" will manage to do it. Furthermore there are also projects that can depend on different versions of the same library (privately or build-requires) without conflict. That is also a problem when trying to "deploy" things. In cross-build scenarios (for example cross building from Windows to some embedded device), you might need the "build" version of protobuf package (for protoc compiler) and the "host" version of protobuf (for the library), and they will also conflict and would need some specific layout.

The result is that the deploy functionality, at the moment is limited to extracting and copying files, but the other generators, like ``CMakeDeps`` will always refer to the cache. We have thought some different approaches, but at the moment nothing really good and general enough. If you need to automate this today, I would try something like:

- Use the ``generate()`` method of the final end consumer, to implement automation that will run at ``conan install``
- Use the ``CMakeDeps`` generator inside ``generate()`` to generate the xxx-config.cmake files, as the first thing
- The generated xxx-config.files have better structure, it contains a single XXX_PACKAGE_FOLDER variable that you can probably easily search & replace for in thev``generate()`` method after the ``CMakeDeps().generate()``
- You can probably use the ``self.dependencies`` way to navigate dependencies to extract exactly the files that you want and copy them to local folder in exactly the way you want.

This might involve a bit of coding inside your consumer conanfile.py, but I think it can work relatively well and not that difficult to implement. We will keep working on this problem, but it will take time.

**Comment by vdsbenoit** [comment]
@memsharded,

Thanks a lot for this clear explanation! I better understand why such things are not much featured in conan now. 

I haven't had the chance to test what you've suggested yet but I will keep it in mind. Thank you for that too!

Alternatively, I think I'll propose to ship the sources from every dependency to the collaborators and ask them to rebuild all of them in order to feed their local conan cache. 

I'm closing this ticket as I believe you have answered my question.

**Comment by memsharded** [comment]
Hi @vdsbenoit 

Thanks for the feedback!

In any case, please note that the above was mainly an explanation of why the current state and the challenges. But I also told that we will keep working on it 😄  Please have a look and track https://github.com/conan-io/conan/pull/10507, this might end in a new deploy functionality in Conan 2.0, that will basically implement your request above. The trick there is to be able to move the potential collision logic down to the final "deployer", as it clearly cannot be implemented internally by Conan, so feedback on that feature if it keeps moving forward will be greatly appreciated.

**Comment by vdsbenoit** [comment]
I've just had a look. That's indeed what I thought about when writing this ticket ! I'll try to follow up on this feature 🙂
