### ISSUE TITLE
open-source conan.io search page

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#1048]
there is conan server available, that's true, but it acts just like web-service for conan command-line client and as package storage. if I am running my own conan server in my corporate network, it would be nice to have conan search frontend for users, like [https://www.conan.io/search?q=*](https://www.conan.io/search?q=*), so users can search for packages in web-browser without need to use "conan search -q" command line syntax. I am not sure, if it's possible to open source at least partially conan.io web site, especially the search page?

**Comment by CodingSpiderFox** [comment]
+1

**Comment by lasote** [comment]
Sorry, this is not possible. If you are interested in having a web UI including search capabilities, you can already use Artifactory.
