### ISSUE TITLE
BazelDeps failing when using absolute (system) folders

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#10481]
Looks like for some packages, we have:

```
p= /usr/include/freetype2 base_path= /home/mboujema/.conan/data/xorg/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
```
assertions fails then:
```
        def _relativize_path(p, base_path):
            # TODO: Very fragile, to test more
            assert os.path.isabs(p), "{} is not absolute".format(p)
            assert p.startswith(base_path)

            return p[len(base_path):].replace("\\", "/").lstrip("/")
 ```

I'm guessing we need to remove the preffix only if its there

_Originally posted by @mohabouje in https://github.com/conan-io/conan/issues/10476#issuecomment-1027035172_

**Comment by mohabouje** [comment]
Could be related:
```
conanfile.py (tijara-conan-integration/0.0.1): ERROR: Traceback (most recent call last):
  File "/home/mboujema/.local/lib/python3.9/site-packages/conans/client/generators/__init__.py", line 174, in write_generators
    generator.generate()
  File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 27, in generate
    content = self._get_dependency_buildfile_content(dependency)
  File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 129, in _get_dependency_buildfile_content
    "libdir": cpp_info.libdirs[0],
IndexError: list index out of range
```

**Comment by mohabouje** [comment]
> Could be related:
> 
> ```
> conanfile.py (tijara-conan-integration/0.0.1): ERROR: Traceback (most recent call last):
>   File "/home/mboujema/.local/lib/python3.9/site-packages/conans/client/generators/__init__.py", line 174, in write_generators
>     generator.generate()
>   File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 27, in generate
>     content = self._get_dependency_buildfile_content(dependency)
>   File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 129, in _get_dependency_buildfile_content
>     "libdir": cpp_info.libdirs[0],
> IndexError: list index out of range
> ```

Simple example to replicate this:

```
from conans import ConanFile
from conan.tools.google import BazelToolchain, BazelDeps


class ConanIntegration(ConanFile):
    name = "conan-integration"
    version = "0.0.1"
    generators = ['BazelDeps', 'BazelToolchain']
    requires = [
        'glfw/3.3.6',
    ]

    def layout(self):
        self.folders.generators = "conandeps"

```

**Comment by franramirez688** [comment]
@mohabouje 
Did this PR https://github.com/conan-io/conan/pull/10484 solve the issue? Asking to know if we can close it.

**Comment by mohabouje** [comment]
It works well for me, probably we are missing some corner cases but I haven't found any other so far
