### ISSUE TITLE
[bug] Checks for the build TYPE do not work

### ISSUE THREAD

**Issue by cajus** [conan-io/conan#10487]
### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora 35
  * Compiler+version: gcc 11
  * Conan version: 1.44.1
  * Python version: 3.10.2

### Steps to reproduce

I need to check whether a build is static or not. For Qt, this works like this:

```
find_package(Qt6 6.2 COMPONENTS Core REQUIRED)

get_target_property(target_type Qt6::Core TYPE)
if(target_type STREQUAL STATIC_LIBRARY)
    message("Yey, Qt is static!")
else()
    message("Non static Qt :-(")
endif()
```

Using the _conan-center-index_ packages, this always returns `INTERFACE_TYPE` and the check does not work. See conan-io/conan-center-index/issues/9224, which has a simple test case attached.

**Comment by memsharded** [comment]
This seems duplicated with: https://github.com/conan-io/conan/issues/10181

And trying to be addressed in https://github.com/conan-io/conan/pull/10497. However that PR is still red, this seems it is not an easy feature.

I think we can close this one as duplicated, and follow on https://github.com/conan-io/conan/issues/10181
