### ISSUE TITLE
[question] Conan cannot find `zlib` although it has installed it

### ISSUE THREAD

**Issue by amirmasoudabdol** [conan-io/conan#10496]
I'm new Conan and I'm finding my way around things rather alright; however, there are some random issues that I have no idea how to deal with.

For instance I have this `conanfile.txt` that installs the `zlib` for me. I can run the `conan install ..` successfully and all my packages are being installed, and I can confirm that by checking the `.conan` folder. When I run the `cmake ..`, in the log I see that Conan is finding all the packages that is installed except the `zlib` and it prints out this message, `Library zlib not found in package, might be system one`. 

```
[requires]
libiconv/1.16
libarchive/3.5.2
zlib/1.2.11
zstd/1.5.2
jsoncpp/1.9.5
openssl/1.1.1m

[generators]
cmake
```

I'm using Conan version 1.44.1 and cmake version 3.22.2, and I'm doing all that on Windows 11, and VS2022, and MSVC 19.30, and this is my profile,

```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=msvc
compiler.version=193
build_type=Release
compiler.cppstd=17
compiler.runtime=static
[options]
[conf]
[build_requires]
[env]
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @amirmasoudabdol 

It might be something in your build system CMakeLists.txt , it would be great to share the full details to reproduce
Also a couple of recommendations:

- Use better ``compiler="Visual Studio"`` and compiler.version=17, the old integrations like ``cmake`` use it
- Try to reduce the problem to the very mininum, that really helps to debug things. If you can leave only the zlib dep, please do it.

**Comment by amirmasoudabdol** [comment]
Thanks! That indeed helped, and it also resolved some problem that I had with installing Boost! :-)

**Comment by memsharded** [comment]
Great, happy to hear it is solved!
