### ISSUE TITLE
[question] How CMake variables like "INTERFACE_LINK_LIBRARIES" should be passed from dependency to consumer package ?

### ISSUE THREAD

**Issue by JonathanGirardeau** [conan-io/conan#10491]
Hello, 

Here is my example:
Package `foo` (executable) depends on package `spdlog` (log package can be found on conan-center). In **Android** build (cross-build), `spdlog` package needs to link with `log` library, so there is a `target_link_libraries(spdlog PUBLIC log)` in its `CMakeLists.txt`. My problem is when I try to build package `foo` in Android, I got a link error regarding the functions defined in `log` library.

I found a workaround: I added `target_link_libraries(foo PUBLIC log)` in `foo` `CMakeList.txt`. However I don't think it is the right way to handle this issue.

I guess my issue is about passing `CMake` variables like `INTERFACE_LINK_LIBRARIES` from dependencies to consumer package, how is it supposed to be done with `conan` ?
My second guess is if there is a way to do it, it would only work if the dependency and the consumer packages are built with `CMake`, right ?

**Comment by memsharded** [comment]
> I guess my issue is about passing CMake variables like INTERFACE_LINK_LIBRARIES from dependencies to consumer package, how is it supposed to be done with conan ?

The information in Conan is passed via the ``package_info()`` method. It is fully abstracted from the build system. You should be filling the ``cpp_info.libdirs``, ``cpp_info.system_libs``, ``cpp_info.libs``, ``cpp_info.cxxflags`` etc. That information is propagated to the consumers, and the consumers "generators" will translate that information to the build system it is using. 

> My second guess is if there is a way to do it, it would only work if the dependency and the consumer packages are built with CMake, right ?

No. As stated above, Conan decouples from the build system. Every package can use its own build system, and everything should work, being able to replace a consumer build system transparently. The key is defining correctly the ``cpp_info`` of the package (and a correct implementation of the consumer generators for the consumer build system)

**Comment by JonathanGirardeau** [comment]
Thanks for the answer, I think it is more clear for me.

Conan makes the transmission of the information fully abstracted from the build system, it is cool. 
However conan can not detect dependencies expressed in `CMakelists.txt` like `target_link_libraries(foo PUBLIC log)`. 
So in my example I should manually add `cpp_info.system_libs = ["log"]` in the `spdlog` recipe to express dependency to system library `log`, right ?

**Comment by memsharded** [comment]
> However conan can not detect dependencies expressed in CMakelists.txt like target_link_libraries(foo PUBLIC log).

Yes, there is some preliminary work to use CMake File API, but it is not there yet. And parsing user CMakeLists to extract that kind of information is simply not feasible, it would be very complicated and super fragile. So it relies on a bit of repetition, needing to declare things explicitly in ``package_info()``, but:

- it is typically not very difficult, only challenging with some third party open source libraries packaging many different components with inter-dependencies. For your own packages that you know what is being packaged, it is relatively straightforward.
- It is a one-time effort, once it is working it is very little effort over time to maintain it (only in case something changes in the library generated artifacts).

> So in my example I should manually add cpp_info.system_libs = ["log"] in the spdlog recipe to express dependency to system library log, right ?

Yes, exactly that is the idea. There are more advanced approaches, that can be useful in more complex scenarios, and it is wrapping a system library with a ``log/system`` Conan package, that is empty, and only serves as a proxy for the system installed library. But it allows to encapsulate some logic and configuration, so it can be convenient. Again, only for more complex use cases, you are probably perfectly ok with ``cpp_info.system_libs``
