### ISSUE TITLE
Best way to parameterize the version

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1049]
Just wanted to get an opinion on this.  As part of a continuous build pipeline, the conan package building step will have the version given by the CI system in an environment variable.  It seems I can't do:

        version = os.environ['VARIABLE_VERSION']

in my `conanfile.py`; so the only thing I can come up with is to use perl or something to _generate_ the `conanfile.py` from a template and then export the generated file.

Is there a better way?

John

P.S. - Nice job on 0.20.  I really like the fixes to environment vars.

**Comment by memsharded** [comment]
Thanks for the feedback, glad you liked the 0.20, tons of effort into it. Still some minor issues, we have to polish (maybe some minor release too), but yes, it is a huge improvement. Keep giving feedback and contributing and we will keep conan improving :)

Actually I think the ``version`` field is just necessary for the ``conan export`` command, all the rest of the process, the version is already encoded as the model (as in the folders layout). So I think you might use your approach of ``os.environ['VARIABLE_VERSION']`` with VARIABLE_VERSION just set on the environment before the export, what is failing when you tried to do it?

**Comment by claasd** [comment]
Hi, 
we are setting the version based on a environment variable. We append the build id from jenkins to the user-defined version:
```python
def version_name(version):
    build_name = "-build." + os.getenv("BUILD_ID", "local")
    return version + build_name;

class MyPackageConan(ConanFile):
    name = "MyPackage"
    version= version_name("1.1.0-alpha")
```
when exporting, the package has the version `1.1-alpha-build.22` if the variable is set, `1.1-alpha-build.local` otherwise.
You probably can adjust this to your needs.

**Comment by tamboril** [comment]
Thank you.  I verified this works and is only used during export.  It is safe to have the variable missing from the environment upon install.  I think the error I was having was not setting the variable on install, and the key was missing in the `os.environ` dict.  I just changed it to a `os.environ.get(key, default)` instead, and the default value is safely ignored at install time.  `getenv()` looks even more apropriate.

**Comment by memsharded** [comment]
Not directly, but you can do it. Some hints:

- Have a global function in the recipe, that generates a "requires.txt".
- Make that function to fail gently and do nothing when it doesn't find the necessary things you have in your folder when you "export".
- Call that function in global namespace
- Do a ``exports`` of that ``requires.txt``
- In your ``requirements()`` method, load the ``requires.txt`` file (will be in the local cache), and define the ``self.requires()`` with the values in it.

**Comment by sourcedelica** [comment]
Ahh - nice.  I will try that out.
