### ISSUE TITLE
[bug] Profile includes prefer $HOME/.conan/profiles folder over the folder of the importing profile

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#10499]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux/Ubuntu20
  * Conan version: 1.42.2
  * Python version: 3.9.5

In my env I have had old deprecated profile hanging here
`~/.conan/profiles/linux-base-profile`

```
~/temp/linux-base-profile  # notice the filename matches with the one under conan home
~/temp/linux-profile
    include(linux-base-profile)
```
    
```
$ mkdir ~/temp/build && cd ~/temp/build
$ conan install <foo> --profile ../linux-profile
```

From the output I can see that include() actually loads the settings & options from ~/.conan/profiles/linux-base-profile, not from
~/temp/linux-base-profile?
When I delete the (deprecated) profile from ~/.conan/profiles/ it works as expected.

I would still expect that the search order should have the folder of the importing profile prioritized?

**Comment by memsharded** [comment]
Hi @iiknd 

I am investigating this with this test:

```python
def test_profile_local_folder_priority():
    """ The local folder include(profile) must have priority over a file with same name in cache
    """
    client = TestClient()
    client.save({"profiles/default": "include(./otherprofile)",
                 "profiles/otherprofile": "[settings]\nos=AIX",
                 "conanfile.txt": ""})
    save(os.path.join(client.cache.profiles_path, "otherprofile"), "[settings]\nos=FreeBSD")

    client.run("install . -pr=profiles/default")
    print(client.out)
    assert "os=AIX" in client.out
```

It seems that Conan wants the ``include()`` explicit. If you use ``include(./something)`` it will understand it relative to the current profile. It is true that in that case, it shouldn't probably fallback to the local relative one if it doesn't exist in the cache.

This sounds risky to change in 1.X, we will probably break some other users that rely on that. If we are changing this, I'd prefer to target it to 2.0.

**Comment by iiknd** [comment]
Hi @memsharded 

> If you use include(./something) it will understand it relative to the current profile

Thanks, this approach works for me :+1: From my behalf targeting it to 2.0 is ok.

**Comment by memsharded** [comment]
Moving it to 2.0-alpha.5 scope, doing https://github.com/conan-io/conan/pull/10677 to discuss this change there.

**Comment by memsharded** [comment]
We have finally decided keeping the explicit behavior, see summary in https://github.com/conan-io/conan/pull/10677#issuecomment-1067398533. This issue will be closed when the PR is merged (with some tests that capture more explicitly this behavior)

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/10677
