### ISSUE TITLE
[feature] Move file tools to "conan"

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10502]
There are still some "file" related tools not migrated to "conan".
- Some of them are probably overacting regarding the encoding, probably in some situations, inherited from python2. As we really don't know what is py2 legacy and what is necessary, try to simplify is something looks weird or too much, maybe always, all, utf-8?
- Some others maybe are not very used, take a look at conan-center and if they are not used better to postpone and migrate later.

**Comment by lasote** [comment]
I'll keep updating this comment:

**Not moved, not very used** Add to migration guide
- human_size
- untargz (only as internal usage of unzip)
- check_with_algorithm_sum (only as internal usage of sha1, md5, sha256)
- replace_path_in_file (There is some usage in c3i but probably could be omitted)
- replace_prefix_in_pc_file
- remove_files_by_mask: Rename to **remove_files(pattern, folder)**
- unix2dos
- dos2unix
- which (shutil.which)

**To be moved**
- unzip
- check_sha1
- check_md5
- check_sha256
- replace_in_file (Review encodings argument)
- collect_libs

**Comment by uilianries** [comment]
@lasote What did happen to `remove_files_by_mask`? I can't find it under `conan.tools.files`. Also, `remove_files` does not exist. What's the idea behind?

**Comment by lasote** [comment]
@uilianries it has been replaced by ``rm``

```python
def rm(conanfile, pattern, folder, recursive=False):
    """
    Utility functions to remove files matching a ``pattern`` in a ``folder``.

    :param conanfile: The current recipe object. Always use ``self``.
    :param pattern: Pattern that the files to be removed have to match (fnmatch).
    :param folder: Folder to search/remove the files.
    :param recursive: If ``recursive`` is specified it will search in the subfolders.
    """
```

**Comment by uilianries** [comment]
As an Linux user, I have to say it's a beautiful name.
