### ISSUE TITLE
[feature] Support for Xcode 13.3 (currently in beta)

### ISSUE THREAD

**Issue by janosvitok** [conan-io/conan#10509]
Xcode 13.3 (still in beta) reports clang version as 13.1.6, so equivalent of #9642 is needed.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @janosvitok 

Do you have any link with info about it? In the usual https://gist.github.com/yamaya/2924292, still not there, in the apple release notes nothing either. I would like to know, just in case, if apple-clang 13.1 brings any change in defaults (like default cppstd), not likely but better check if possible.

**Comment by janosvitok** [comment]
https://gist.github.com/yamaya/2924292?permalink_comment_id=4051431#gistcomment-4051431 mentions Xcode 13.3 Beta 1

Here are official release notes: https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3-release-notes

https://en.wikipedia.org/wiki/Xcode

How do I find default cppstd?

**Comment by SSE4** [comment]
> How do I find default cppstd?

something like `clang++ -x c++ -dM -E /dev/null | grep __cplusplus` could help

**Comment by janosvitok** [comment]
This is the full output of the command:
[apple-clang-13.1.6.txt](https://github.com/conan-io/conan/files/8018139/apple-clang-13.1.6.txt)

```c++
#define __cplusplus 199711L  // c++98
#define __cpp_exceptions 199711L // c++98
#define __cpp_impl_destroying_delete 201806L // c++20
#define __cpp_rtti 199711L // c++98
#define __cpp_threadsafe_static_init 200806L // c++11
```

**Comment by janosvitok** [comment]
Xcode 13.3 beta 2 same #defines. See also https://gist.github.com/yamaya/2924292?permalink_comment_id=4063803#gistcomment-4063803

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/10608 is adding new Apple SDK version information in default settings.

I am postponing this to next 1.47 release until https://github.com/conan-io/conan/pull/10608 is merged, because new Apple settings will also need to take new SDK versions into account.

In the meantime, users can add ``13.1`` to their settings.yml if they need to.

**Comment by janosvitok** [comment]
Xcode 13.3 RC: 

```
bash-3.2$ xcrun clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
#defines are the same.

**Comment by H-G-Hristov** [comment]
Xcode 13.3 is released. We need support for compiler version `13.1`.

**Comment by janosvitok** [comment]
> Xcode 13.3 is released. We need support for compiler version `13.1`.

For workaround see [above](https://github.com/conan-io/conan/issues/10509#issuecomment-1054529284): 

> In the meantime, users can add `13.1` to their settings.yml if they need to.
