### ISSUE TITLE
[bug] BazelDeps does not work with shared libraries

### ISSUE THREAD

**Issue by mohabouje** [conan-io/conan#10508]
It is hard-coded in the BazelDeps.py class. I've done a quick fix on my fork but I do have some other pull request open with previous fixes.

Putting this hear to help with the milestone for version 1.46

Possible fix: https://github.com/mohabouje/conan/commit/84621b5791ebb790ecc26745f3835d1b32168ac1

**Comment by AbrilRBS** [comment]
Closing as solved back when! Sorry for not closing them on time :)
