### ISSUE TITLE
[feature] scm migrate to "conan" namespace

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10503]
- Simplify architecture (superclasses and other magic)
- Remove the "no-auto" use case: Defining fixed fields just to avoid doing a manual clone/checkout. Deprecate in the migration guide the usage of revision != "auto" or whatever is needed.
- Expose simple tools (moving to conan) for Git, SVN, and internally, for the scm feature, use whatever we need (do not break).

**Comment by memsharded** [comment]
This has been already done: Conan 1.45 got the new ``tools.scm.Git`` helper that will implement the ``scm`` behavior. All the other ``scm`` magic and classes has been removed.
