### ISSUE TITLE
[question] Possible to map compatible package_ids?

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10512]
We created a some packages using `package_revision_mode` and are now moving to using `recipe_revision_mode`. The mode switch has caused the package_ids to change but I'd really like to not to have to rebuild all the packages since we know they're binary compatible and some of the builds take hours. 

I've tried playing with [compatible packages](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#compatible-packages) but I couldn't get it to work for what I think I need. That section demonstrates mapping compiler version, etc which doesn't seem to apply here since all the settings/options are the same?

I also tried playing with changing the [package_id mode](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#using-package-id-for-package-dependencies) for the dependencies, but without success.

If we have: 
`AppX --> LibX --> LibB --> LibA` 

which was built using `package_revision_mode` to get:
`AppX --> LibX:123 --> LibB:224 --> LibA:332`

Changing to `recipe_revision_mode` gets an entirely new package chain:
`AppX --> LibX:456 --> LibB:983 --> LibA:111` 

I think what I'd like to be able to do is to do something the in LibX recipe such that we get: 
`AppX --> LibX:789 --> LibB:224 --> LibA:332` 

to avoid having to rebuild LibB (and LibA). It's okay if LibX has to rebuild.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Have you tried something like this?

```python
def package_id(self):   
    compatible_pkg = self.info.clone()
    compatible_pkg.requires.package_revision_mode()
    self.compatible_packages.append(compatible_pkg)
```

If not, please try and let me know.

**Comment by nichmj01** [comment]
Hi @memsharded,
This didn't seem to work. Wasn't quite sure where to put this so I added it to the LibX package to try it out. It didn't seem to change anything.

To walk through the test I ran in case I might have done something wrong there:

1. Set `default_package_id_mode=package_revision_mode` in `conan.conf`
2. Create packages ('conan create') for LibA, LibB, and LibX
    - All packages are now in the cache and all AppX `requires` are found
3. Set `default_package_id_mode=recipe_revision_mode` in `conan.conf`
    - LibB, and LibX package_ids change due to change of mode; their packages are missing
    - LibA package_id doesn't change since it has no dependencies; it's package is in the cache
    - AppX can't be built
4. Add suggested change to LibX and export new LibX recipe
    - LibX RREV changes since the recipe changed
    - LibX, LibB, and LibA package_ids don't change

**Comment by memsharded** [comment]
Oh, I think I understand what is happening. Introducing changes in the recipes to add ``package_id()`` new logic, changes the recipe revision anyway, which by itself requires a rebuild. It is not possible at the moment to introduce such change without requiring a rebuild. (we are working to try to introduce binary compatibility outside of the recipes, but that won't be in 1.X ,only 2.0).

So it seems that re-building things is necessary. At least it is not something that you need to do all at once, you can create a separate build with the recipe_revision_mode to start creating and uploading the new binaries, that will not disrupt the main usage with package_revision_mode. Take advantage of idle times in CI if possible, and then do the real switch only when all binaries are there.

**Comment by nichmj01** [comment]
> Introducing changes in the recipes to add package_id() new logic, changes the recipe revision anyway, which by itself requires a rebuild.

I would expect LibX and its downstreams to need to rebuild because LibX's RREV changed and its downstreams will need to rebuild as their package_ids now use the new RREV.

LibB still needing to rebuild is the weird part for me. By setting adding `requires.package_revision_mode()` to the compatible_packages I was expecting that the package_id for LibB calculated using `package_revision_mode` would be compatible which it could find. This compatible LibB package_id would be the one it had at the end of Step 2 above since nothing about LibA has changed. I'm just using `conan info` to look at the graph and not rebuilding everything after every change so maybe I'm misreading the output. 

Instead, it seems like the LibB package_id is still being calculated using `recipe_revision_mode`, (which I think makes sense) but it's not saying that LibB:package_revision_package_id is compatible can understand. If I use `self.info.requires.package_revision_mode()` then the package_id of LibX and its downstream are affected so it seems like the use of this approach affects the way the package_id of the current package and it's downstreams are calculated but not the way that the required package_id of the upstreams are calculated.

##### `default_package_id_mode=package_revision_mode`

Packages and Dependencies
* `LibA#1:1#1`
* `LibB#1:1#1 --> LibA#1:1#1`
* `LibX#1:1#1 --> LibB#1:1#1 --> LibA#1:1#1`
* `AppX --> LibB#1:1#1 --> LibA#1:1#1`

In cache:
* `LibA#1:1#1`
* `LibB#1:1#1`
* `LibX#1:1#1`


##### Switch to `default_package_id_mode=recipe_revision_mode`

Packages and Dependencies
* `LibA#1:1#1`
* `LibB#1:2 --> LibA#1:1#1`
* `LibX#1:2 --> LibB#1:2 --> LibA#1:1#1`
* `AppX --> LibX#1:2 --> LibB#1:2 --> LibA#1:1#1`

In cache:
* `LibA#1:1#1`
* `LibB#1:1#1`
* `LibX#1:1#1`

`LibX#1:2` and `LibB#1:2` are missing

##### Modify `LibX` to add `compatible_packages` (as above)

Packages and Dependencies
* `LibA#1:1#1`
* `LibB#1:2 --> LibA#1:1#1`
* `LibX#2:1 --> LibB#1:2 --> LibA#1:1#1` (_**or**_ `LibB#1:1#1 --> LibA#1:1#1` because of compatible_packages?)
* `AppX --> LibX#2:1 --> LibB#1:2 --> LibA#1:1#1`

In cache:
* `LibA#1:1#1`
* `LibB#1:1#1`
* `LibX#1:1#1`

`LibX#2:1` and `LibB#1:2` are missing. Presumably `LibX#2:1` should be able to use `LibB#1:1#1` but the output from `conan info` doesn't give any indication of such?


##### Modify `LibX` to set `self.info.requires`

I was curious what would happen if I did:
``` python
def package_id(self):   
    self.info.requires.package_revision_mode()
```

Packages and Dependencies
* `LibA#1:1#1`
* `LibB#1:2 --> LibA#1:1#1`
* `LibX#2:Unknown --> LibB#1:2 --> LibA#1:1#1`
* `AppX --> LibX#2:Unknown --> LibB#1:2 --> LibA#1:1#1`

In cache:
* `LibA#1:1#1`
* `LibB#1:1#1`
* `LibX#1:1#1`

`LibX#2:Unknown` and `LibB#1:2` are missing.

**Comment by nichmj01** [comment]
This is mostly curiosity at this point, and getting a deeper understanding. We're going to do as you suggest and build all the packages using recipe_revision_mode and then do a switch over when all of those are packages are built.

**Comment by nichmj01** [comment]
We rebuilt everything so this issue went away. Having more control over specifying `package_id` compatibility would've been useful and maybe it will make it into v2.0.
