### ISSUE TITLE
[bug]  --require-overrid does not affect package id

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#10517]
When injecting an override using ` --require-overrid` options, final package id is not affected.

### Environment Details
  * Operating System+version: Macos catalina
  * Compiler+version: apple-clang 12.0
  * Conan version: 1.45.0
  * Python version: 3.8.6

### Steps to reproduce

Starting with this conan file:

```
from conans import ConanFile

class DemoConan(ConanFile):
    name = "demo"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"

    def requirements(self):
        self.requires("zlib/1.2.11")

    def build(self):
        pass

    def package(self):
        pass

```

1.  Create a conan package using the command `conan create .`
2.  Get package info using the command `conan search demo/1.0.0@` 

The output in my case was:
```
$ conan search demo/1.0.0@
Existing packages for recipe demo/1.0.0:

    Package_ID: 67aa9f5e6ea3981f9d0d24414d21a4c9ff0fc4f2
        [settings]
            arch: x86_64
            build_type: Release
            compiler: apple-clang
            compiler.libcxx: libc++
            compiler.version: 12.0
            os: Macos
        [requires]
            zlib/1.2.11:647afeb69d3b0a2d3d316e80b24d38c714cc6900
        Outdated from recipe: False
```

3. Create the same conan package but with overrides using the command: `conan create . --require-overrid zlib/1.2.8` 
4. Get package info using the command `conan search demo/1.0.0@` 
The output in my case was:

```
$ conan search demo/1.0.0@
Existing packages for recipe demo/1.0.0:

    Package_ID: 67aa9f5e6ea3981f9d0d24414d21a4c9ff0fc4f2
        [settings]
            arch: x86_64
            build_type: Release
            compiler: apple-clang
            compiler.libcxx: libc++
            compiler.version: 12.0
            os: Macos
        [requires]
            zlib/1.2.8:647afeb69d3b0a2d3d316e80b24d38c714cc6900
        Outdated from recipe: False
```

requires are being correctly updated, but Package_ID is the same `67aa9f5e6ea3981f9d0d24414d21a4c9ff0fc4f2`

**Comment by memsharded** [comment]
Hi @boussaffawalid 

This is completely expected. Doing an override or changing the upstream version do not change the ``package_id`` unless you change the package_id_mode. You can do it directly on the ``package_id()`` method or using the configuration default ``default_package_id_mode``. But unless you change it, the binary will depend on "semver_direct_mode" which means that ``zlib/1.X.Y`` is the string that is going to be hashed into the package_id, and thus, the binary will be the same (binary compatible) for both 1.2.8 and 1.2.11

**Comment by boussaffawalid** [comment]
@memsharded I just tried that and it works as expected, thank you!

**Comment by memsharded** [comment]
Great to know. Then I think, this can be closed as solved. A note for the future: The default package_id computation will change in 2.0, taking advantage of the new "requirement traits" and "package types" that convey more information, being more accurate for many cases that today are not handled.

**Comment by boussaffawalid** [comment]
Thanks for the info, right now none of the existing package_id mode worked for us for we had to use a custom one
```
    def package_id(self):
        for r in self.info.requires._data.values():
            if r._indirect:
                r.unrelated_mode()
            else:
                r.full_package_mode()
```
