### ISSUE TITLE
[question] Conan keeps uploading to Artifactory port 80 instead of 443 when using HTTPS

### ISSUE THREAD

**Issue by sssilver** [conan-io/conan#10510]
Hi,

I'm deploying my own Artifactory through the jfrog/artifactory-cpp-ce Helm chart: 
```
  $ helm upgrade --install artifactory -f ./values-artifactory-cpp-ce.yaml --namespace artifactory --set postgresql.postgresqlPassword=<censored> jfrog/artifactory-cpp-ce
```

My `./values-artifactory-cpp-ce.yaml` contents:
```yaml
# ...

access:
  accessConfig:
    security:
      tls: true

artifactory:
  accessConfig:
    security:
      tls: true
```

Then I configure Artifactory, create the repository named `conan`, set permissions, and add it as a remote to my Conan (notice the `https` prefix in the URL):
```
  $ conan remote add myrepo https://artifactory.example.com/artifactory/api/conan/conan
```

When I finally try to upload a package to my repo, I get the following errors:
```
  $ conan upload "entt/3.9.0" -r myrepo --all -c
Uploading to remote 'myrepo':
Uploading entt/3.9.0 to remote 'myrepo'                                                  
Please log in to "myrepo" to perform this action. Execute "conan user" command.
Please enter a password for "myrepo-github" account: 
ERROR: 
Error uploading file: conan_export.tgz, 'HTTPSConnectionPool(host='artifactory.example.com', port=80): Max retries exceeded with url: /artifactory/api/conan/conan/v1/files/_/entt/3.9.0/_/0/export/conan_export.tgz (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))'
ERROR: 
Error uploading file: conanfile.py, 'HTTPSConnectionPool(host='artifactory.example.com', port=80): Max retries exceeded with url: /artifactory/api/conan/conan/v1/files/_/entt/3.9.0/_/0/export/conanfile.py (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))'
ERROR: 
Error uploading file: conanmanifest.txt, 'HTTPSConnectionPool(host='artifactory.example.com', port=80): Max retries exceeded with url: /artifactory/api/conan/conan/v1/files/_/entt/3.9.0/_/0/export/conanmanifest.txt (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))'
ERROR: entt/3.9.0: Upload recipe to 'myrepo' failed: Execute upload again to retry upload the failed files: conan_export.tgz, conanfile.py, conanmanifest.txt. [Remote: myrepo]

ERROR: Errors uploading some packages
```

Notice four things:
  1. For some reason Conan's `HTTPSConnectionPool` is attempting to connect to port 80 rather than 443
  2. If I add the remote through an `http` schema rather than `https`, everything works
  3. The dashboard works great via HTTPS in the browser
  4. I don't know if this is relevant, but the host is behind Cloudflare with strict SSL turned on

I expect uploading to my Artifactory remote via HTTPS to work successfully. Why does Conan keep going to the remote port 80 despite the HTTPS prefix in the remote URL?

I've been banging my head against this for a few days. Is this a Conan issue? Is my Artifactory misconfigured? What am I missing? All guidance is appreciated.

**Comment by memsharded** [comment]
Hi @sssilver 

I honestly have no idea what could be the issue. I would say that this is mostly a server configuration issue for a couple of reasons:

- If it was something in the client side, it would have been reported more often. Https is widely use for Conan, even the ConanCenter is https://center.conan.io
- Conan code does not contain any logic regarding this. It just uses the URL provided by Artifactory SetMeUp. (By the way, have you tried explicitly setting the port, like ``conan remote add my repo https://artifactory.example.com/artifactory/api/conan/conan:443``? Not saying it is a solution, but might be worth checking to see what happens

It might be worth to do another test with an Artifactory in the FreeTier, which is also under Https, with exactly that Conan client in the same machine that you are testing, to try to rule out some possible issue in the client side. Please let me know how it goes.

**Comment by memsharded** [comment]
Issue in jfrog repo: https://github.com/jfrog/charts/issues/1575

**Comment by memsharded** [comment]
Quick update. The Artifactory SetMeUp doesn't use any port, and it doesn't need it to use https. A normal line is ``conan remote add <REMOTE> https://<url>/artifactory/api/conan/conan-local``

**Comment by memsharded** [comment]
Seems somone more expert in the Artifactory helm chart is responding https://github.com/jfrog/charts/issues/1575#issuecomment-1031796662. I think we can close this, at the moment it doesn't seem a Conan client issue at all, lets follow conversation in https://github.com/jfrog/charts/issues/1575. Thanks!
