### ISSUE TITLE
[question] Locking some dependencies in a "Dependency Package"

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10514]
We have a package that functions to collect all our dependencies so that each project doesn't have to reference them separately. This helps ensure projects are at least starting with the same, known working dependencies. Some of the recipes/packages listed in the Deps package are controlled internally and some are managed externally.

For example:
```
App --> DepsPkg --> InternalA --> ExternalZ
                --> InternalB
                --> ExternalY
```

We are currently not using version ranges for anything. We would like to "lock" the external dependencies to specific revisions as we have run into issue with the recipes changing and causing version conflicts. However, we would like the internal dependencies to use the latest recipe revision so that the latest revision is always used. 

I'm pretty sure we could probably do this by specifying the RREV for all the external packages in the DepsPkg to get something like:

```
App --> DepsPkg --> InternalA --> ExternalZ#123
                --> InternalB
                --> ExternalY#234
```

But the challenge is that the dependency graph is very deep so we'd have to figure out the RREV for all the external dependencies to specify them. There may also be differences based on the profile in use.

I feel like I might be able to do something with lock files but I'm not 100% sure on how to accomplish this. 

One option would be to forgo the DepsPkg and provide a lockfile for each project with all the dependencies but having to call `conan install --lockfile=XXX` is likely going to get some push back. That also requires us to push a new lockfile out to projects if a dependency changes so ideally, consumers would just reference the DepsPkg and they would not have to worry about lockfiles.

I'm thinking along the lines of creating a base lockfile and exporting it with DepsPkg and parsing it in a build step or something?

Any thoughts?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> I feel like I might be able to do something with lock files but I'm not 100% sure on how to accomplish this.

I think this might be challenging with lockfiles, at least with 1.X lockfiles seems not possible. The thing is that lockfiles will capture the full snapshot of the dependency graph, including all revisions for all packages. It is not possible to lock some packages while letting others "free".

Even if you capture a lockfile that locks ExternalZ to be applied when building InternalA, when you try to apply that downstream to DepsPkg or App, it will most likely fail because you are not locking InternalX packages in the lockfile.


Maybe, if you can have some common place where you can put the External revisions, and that Internal recipes have access to it, then you could use that definition in the ``requires()`` method dynamically, no need to hardcode it in the recipes. Leveraging the ``conandata.yml`` file, or maybe having some ``def export()`` logic that capture those external revisions at package creation time, could help to use a "centralized" place of external recipe revisions to use.

**Comment by nichmj01** [comment]
> Maybe, if you can have some common place where you can put the External revisions

The challenge I think I have is figuring out the complete list of external dependencies and their revision numbers; especially across our profiles and with different settings. For example, looking at some lock files I generated, on windows there are 34 dependencies, and on linux there are 40 dependencies with the default options. We control 5 of the recipes in the graph. 

Maybe I can create a base lockfile to capture the external dependencies and parse the lockfile? This is likely to be brittle but maybe a good starting point? 

I think a base lockfile is supposed to contain all the dependencies regardless or profile so it can always be used later to create a complete lockfile? I'm not sure this is what I'm seeing though.


> Maybe, if you can have some common place where you can put the External revisions (...)

I had a similar thought. My initial uncertainty is related to the issue above. Assuming I can figure out all the external revisions and the combination of dependencies based on the settings and options, it feels like the DepsPkg would need to manage that in the `requirements()` method.

For example: 
Let's say we have a simple tree:

On Windows:
```
App --> DepsPkg --> InternalA --> ExternalZ
                --> InternalB
                --> ExternalY
```

On Linux:
```
App --> DepsPkg --> InternalA --> ExternalZ
                --> InternalB
                --> ExternalY --> ExternalX
```

such that ExternalX is only needed when building for Linux.

DepsPkg would need to check the OS being built for and only include ExternalX as a requirement when building for Linux. (Even though I'm specifying the revision for ExternalY it could pull the latest revision of ExternalX with some unknown effect). This seems pretty burdensome to have DepsPkg to do all this management.


I played with this a little and wondered if I could get conan to figure out the dependency graph for me and then I could maybe replace the calculated `requires` in the `requirements()` method.

Something like this:

``` python
    requires = [
        "InternalA /1.0.0",
        "InternalB/1.0.0",
        "ExternalY /1.0.0"
    ]

    def requirements(self):
        # Read the required revisions for all packages from the lock file
        lock_file = os.path.join(base_path, "base.lock")  

        # Read the names of the packages that can be "free"
        exceptions_file = os.path.join(base_path, "exceptions.json")  

        # Filter out the "free" packages
        locked_requirements = lockLoader.get_locked_references(lock_file, exceptions_file)  
        
        # Replace the conan calculated requires with the one pulled from the lockfile
        for item in locked_requirements:
            ref = ConanFileReference.loads(item)
            self.requires.override(ref)  
```

This is using the internal `ConanFileReference` and `override()` method so probably brittle to future changes, but does seem to work? Anything else I should be careful of trying to use this approach (other than the API changing)? Since I can modify the requirements in this method, we may don't know the full graph as yet?

**Comment by nichmj01** [comment]
@memsharded Any thoughts on using this code?

``` python
ref = ConanFileReference.loads(item)
self.requires.override(ref)  
```

This bit us today. Two recipes we depend on from conan-center changed and since they're low down in the dependency tree it required a few things to rebuild.

I like the override approach but I think it won't be as difficult to dynamically add requirements() based on the OS as I originally thought if you think that is a more maintainable solution.

**Comment by nichmj01** [comment]
To update anyone who stumbles upon this:

I decided to build the requirements manually in the `requirements()` method. I have the dependencies listed in json files for each operating system, with the RREVs called out:

Example:
``` json
[
    "boost/1.65.0@mechaspin/testing#956087708ff8a3a6d68c7d0f2f4ae9d0",
    "brotli/1.0.9#6fc2cda04f57470ce73d72d7f694507a",
    "bzip2/1.0.8#b056f852bd2d5af96fc7171aadfd6c0b",
    "double-conversion/3.1.5#e6d82cd98d314b09b337b750429e8bc1"
]
```
These json files are exported with the recipe and in the conanfile.py, I load the relevant json file based on the OS and set them `using self.requires()`

``` python
    settings = {"os"}

    options = {
        "locked": [True, False]
    }

    default_options = {
        "locked": True,
    }

    exports = "requirements*"

    def requirements(self):
        base_dependencies = self._get_references(self.recipe_folder, "base.json")
        if not self.options.locked:
            base_dependencies = self._remove_revision(base_dependencies)

        for dep in base_dependencies:
            self.requires(dep)

        if self.options.locked:
            filename = self._get_filename(self.settings)
            dependencies = self._get_references(self.recipe_folder, filename)
            for dep in dependencies:
                self.requires(dep, override=True)
```

I found that `self.requires()` has a parameter called `override` which seems to do something similar to what I was doing before with `self.requires.override(ref)` but `self.requires(dep, override=True)` seems safer since it's part of the public interface. `override=True` will only override existing requirements, so if a package is specified that isn't actually needed it seems like it will do nothing. However, it will generate an error if the package is a direct dependency (I think, I can't remember the details for when I saw an error). As such, I have a file listing the direct dependencies (base.json) and another file listing the packages to override.

I also added the `locked` option (which defaults to True) to give myself the ability to use the latest RREV for all packages if necessary.

So far this is working as we need it. The only downside is that we get a bunch of warnings about the overrides similar to #5730. 

``` bash
WARN: libtiff/4.0.9: requirement zlib/1.2.11 overridden by my_package/1.0.0@user/channel to zlib/1.2.11
```

Which is a bit noisy and doesn't add any insight since the RREV isn't printed.
