### ISSUE TITLE
[question] packages that cannot exist for this configuration

### ISSUE THREAD

**Issue by FaiqueAli** [conan-io/conan#10528]
Hello everyone,
I am trying to build a c++  application using gcc on Windows with the following configurations.
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

I am getting following error with conan install command.

Command: conan install . -g qmake

Error:
ERROR: There are invalid packages (packages that cannot exist for this configuration):
libpq/13.3: Invalid ID: static mingw build is not possible

looking for help to resolve this issue .
Thanks in advance.

**Comment by lasote** [comment]
Looks like that is a limitation of the library, at least the recipe from conan-center-index is blocking that configuration: https://github.com/conan-io/conan-center-index/blob/df49d7b444a7100ee5ebeaaf858ef766cd57acc9/recipes/libpq/all/conanfile.py#L73
I think the message is wrong because it is raising the exception when "shared" but complains about "static".

The way to solve it, it depends, you could try to set an option like:

```
[options]
libpq:shared=False
```

but it depends on what you are trying to achieve and what are your dependencies.

**Comment by FaiqueAli** [comment]
hi, thanks for the reply,
currently, my conanfile has this value 

[options]
#libpq:with_openssl=True
*:shared=True

but by setting  up libpq:shared=False did not resolved the issue.

[options]
#libpq:with_openssl=True
libpq:shared=False


I am getting following error


----------------------------------------------
conanfile.txt: Installing package
Requirements
    libpq/13.3 from 'conancenter' - Cache
Packages
    libpq/13.3:2af389744c9359a88f48705607388dba92ee989e - Missing

Installing (downloading, building) binaries...
ERROR: Missing binary: libpq/13.3:2af389744c9359a88f48705607388dba92ee989e

libpq/13.3: WARN: Can't find a 'libpq/13.3' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=11, os=Windows
- Options: shared=False, with_openssl=False
- Dependencies:
- Requirements:
- Package ID: 2af389744c9359a88f48705607388dba92ee989e

ERROR: Missing prebuilt package for 'libpq/13.3'
Use 'conan search libpq/13.3 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=libpq'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
---------------------------------------------

**Comment by memsharded** [comment]
The error message is telling you:

- there is no precompiled binary for that configuration in ConanCenter. ConanCenter cannot build every possible binary out there, it already builds around +100 binaries for each package, but using configuration (settings/options) different from the mainstream, will require building from source
- You can ``--build=missing`` or ``--build=libpq`` to build from source missing binaries. Building from source might require at some point some extra tools installed, depending on the specific package

My recommendation in general is: ConanCenter builds packages for VisualStudio in Windows, but not Mingw/gcc. In general, the support for VisualStudio will be much much better than for Mingw. Given that VisualStudio Community now is completely free, if possible use it, things will probably be much smoother. Same for static linkage. In general, static linkage is well more tested than shared one, so it is recommended to use it.

**Comment by FaiqueAli** [comment]
Thank you very much for the prompt response,
Finally, I managed to work it using visual studio compiler settings.

 Thanks :)

**Comment by memsharded** [comment]
> Finally, I managed to work it using visual studio compiler settings.

Happy to hear that you managed to make it work. Thanks for following up!
