### ISSUE TITLE
Regression in --build behaviour

### ISSUE THREAD

**Issue by mropert** [conan-io/conan#1053]
Hello,

I've noticed a small regression with the new version 0.20.
Before we used to be able to do this: ```conan test_package --build=outdated --build=Boost .```
It meant "rebuild any outdated package *and* rebuild Boost anyway".

Today I can only specify ```--build=outdated``` (or ```missing```) if it's the only ```--build``` argument.
Else ```outdated``` is interpreted as the name of a package.

**Comment by memsharded** [comment]
Great, thanks for reporting. We have an open branch for minor fixes in 0.20.2, will try to check this to include it in the minor release.

**Comment by memsharded** [comment]
Submitted a PR to fix it: https://github.com/conan-io/conan/pull/1054
You might try running from the source branch in the meantime we release the 0.20.2 minor version

**Comment by lasote** [comment]
Relased minor.

**Comment by KindDragon** [comment]
Doesn't fix issue with `--build=missing` (ver 0.20.2).
`--build=missing --build=Pkg` return for me error `ERROR: No package matching 'missing*' patter`

**Comment by memsharded** [comment]
It seems I did another stupid mistake, sorry. Will probably release a minor tomorrow, I will try to add a fix for this.

**Comment by lasote** [comment]
Sorry, the fix for that problem requires a feature more than a quick fix, we've scheduled for next 0.21.0.

**Comment by KindDragon** [comment]
Ok 😕

**Comment by memsharded** [comment]
Yeah, sorry, but the thing is that the --build behavior for special values like "missing" is not intended to be chained with package names patterns. Even if it wouldn't fail, it won't work as expected, so changing that would also be breaking behavior, so we are trapped anyway. If you check the PR, you will see that it is not small, so it will introduce risks of breaking other things, more time is needed to stabilize it.
