### ISSUE TITLE
[question] Requires do not propogate env_info ?

### ISSUE THREAD

**Issue by sandeshhardikar** [conan-io/conan#10538]
Hello,
I am trying to use tool_requires functionality from **1.45.0-dev**

quoting From the [conan docs](https://docs.conan.io/en/latest/devtools/build_requires.html?highlight=context#build-and-host-contexts)
> Tool requirements in the host context will propagate like any other requirement:
cpp_info: all information will be available in the deps_cpp_info["xxx"] object.
env_info: won’t be propagated.

This means that if i have a `tool_requires`  forcefully in `host` scope the `env_info` wont be propogated , but the `requires` dependency should still be able to propogate `env_info` .

From [package_info documentation](https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-package-info) propogation of `env_info` does not seem to work for me.

Here are the steps to reproduce
```
# build and package mylib
conan install --profile:host=myhostprofile --profile:build=default --install-folder build .
cd build
conan build ..
conan package ..
conan export-pkg .. conan/stable

# consume it another recipe as above and try to print
 class OtherConan(ConanFile):
    name = "OtherLib"
    version = "1.0"
    requires = "mylib/1.6.0@conan/stable"

    def build(self):
        self.output.warn(self.deps_env_info["mylib"].othervar)

ERROR: conanfile.py (OtherLib/1.0): Error in build() method
        self.output.warn(self.deps_env_info["mylib"].othervar)
        KeyError: 'mylib'
```
please let me know if i have misunderstood the documentation in someway or you need more info on how to reproduce the issue.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @sandeshhardikar 

No, when using the new model and the build&host context, other access is also implemented:

- You need to define ``buildenv_info`` and ``runenv_info`` in the recipes ``package_info()`` methods
- These are collected by the ``VirtualBuildEnv`` and ``VirtualRunEnv`` generators, that you can declare in the consumer recipes if you want (or use a new ``conf`` ``tools.env.virtualenv:auto_use=True`` to enable them by default, as this will be the default in 2.0)
- You can explicitly access your dependencies information via ``self.dependencies`` new accessor (it has filters for "build", "host", etc if you want) https://docs.conan.io/en/latest/reference/conanfile/dependencies.html

**Comment by sandeshhardikar** [comment]
Hi @memsharded ,

Thanks for the super fast reply, yet again. I am not sure if i understood you completely , so again few set of clarifications.
>No, when using the new model and the build&host context, other access is also implemented

- you mean the `env_info` does not get propagated for `requires` dependency when using `build` and `host` profile ? The documentation [here ](https://docs.conan.io/en/latest/mastering/virtualenv.html#virtualenv-generator) suggests, it should work seamlessly. worth adding a note about `build` and `host` profile ? 

>You need to define buildenv_info and runenv_info in the recipes package_info() methods

- I defined the following `self.buildenv_info.othervar = "OTHER VALUE"` in the `package_info` method of my library.
- Consumed it in my other conan package as `requires` and set the generator to `virtualbuildenv`, I now have my `environment_build.sh.env` but without `othervar ` variable.
- Also after reading the usecase of [VirtualBuildEnv](https://docs.conan.io/en/latest/mastering/virtualenv.html#virtualbuildenv-environment) i dont think it fits my usecase. I will describe my usecase at the end of my comment.

>You can explicitly access your dependencies information via self.dependencies new accessor
hmm, as per the documentation this can only work in `generate` and `validate` method , so probably not useful to me at the moment.

**usecase**

- we have a package for `partition_configuration` which currently defines some `partition sizes` ex: `self.env_info.PARTITION_SIZE_1="0x100000000"` in the form of `env_info` variable. 
- This is consumed by other conan package as `requires` and it creates a build file based on `self.deps_env_info['partition_package'].PARTITION_SIZE_1`
- The above approach works seamlessly well.

we now have a problem when we want to do the transition to `build and host profile` and cannot access `env_info` variables.

Any suggestions/hints from your side ?

**Comment by memsharded** [comment]
Hi @sandeshhardikar 

It seems you are using some incorrect syntax, please check the docs twice. Instead of ``self.buildenv_info.othervar = "OTHER VALUE"`` the syntax is something like:

```python
self.buildenv_info.define("othervar", "OTHER VALUE")
```

So the operations (define ,append, prepend, unset) and type (normal or path) are fully defined.

Then, if you don't want the VirtualBuildEnv, no necessary to use it, you can always access ``self.dependencies["partition_package"].buildenv_info`` directly if necessary. Or instead of creating a file, you can get the vars like:

```python
def generate(self):
    v = VirtualBuildEnv(self)
    myvars = v.vars()
    myvars.get("othervar")
```

Note in general it is prefer to use the ``generate()`` method to prepare the build environment, creating build files as necessary, so later ``build()`` can use them very transparently.

**Comment by sandeshhardikar** [comment]
Thanks @memsharded , I can move forward now. I will re-open this issue or create a new one if i hit further blockers when transiting to `build` and `host` profiles.
