### ISSUE TITLE
[feature] Generate nice website to list all my recipes (remote/local)

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#10533]
I would like to have a human friendly readable page (like https://conan.io/center/allpackages) that shows me all available packages and it's version. Otherwise it is very "hard" for consumers in a big company, which packages are available.

My suggestion:
1. generate a static website like `conan info . --graph=file.html` but for all recipes. UI like conan center website
2. Implement this UI in artifactory. In order to get more buying customers.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @derived-coder 

We won't implement this feature as requested, it is out of scope (you can always do this feature request to Artifactory).

What will be possible is:

- We are trying to improve some performance issues over the ``conan search`` query to Artifactory, that is slow and even can timeout
- Conan 2.0 will have a custom commands framework and access to the Python API. With it, users can do any kind of graphical frontend they want, quite easily (like the graph html output, but for listing packages)

The first thing is tracked in other tickets, and the second is already implemented and released in Conan 2.0-alpha.3. So I think we can close this ticket.

**Comment by czoido** [comment]
Conan 2.0 is already released so it's now possible to create a custom command for doing this.  Please check: https://docs.conan.io/2/reference/extensions/custom_commands.html

Also the performance search in Artifactory has been fixed for the reference part, so closing the issue.

Feel free to reopen if you have more questions.
