### ISSUE TITLE
[question] Continuous Checks Fialing

### ISSUE THREAD

**Issue by AbhijithGanesh** [conan-io/conan#10545]
I came to check the project for good first contributions but saw the checks failing, Is this related to `python-2.7` or is it a check-fail which got merged by mistake.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @AbhijithGanesh 

It is not clear what do you mean. Can you please link to the failing PR? As the CI does test many different tools (cmake, visual, meson, autotools, baze, etc, etc) sometimes some glitches may break a build randomly. But we typically relaunch if this happens. You need to point to the specific build that is broken.

**Comment by AbhijithGanesh** [comment]
I was talking about this https://ci.conan.io/job/ConanTestSuite/job/develop/684/display/redirect

**Comment by AbhijithGanesh** [comment]
I am wondering why the build test is failing for `python-2.7`

**Comment by memsharded** [comment]
Oh, thanks for pointing that out!

Yes, the test suite that runs for PR is not as comprehensive as the one that runs in develop. Sometimes there are small things like this that would be temporarily broken. Not a big deal, we usually fix it very quickly.

**Comment by AbhijithGanesh** [comment]
Thanks for clarifying, It caught my attention and I'd like to know if patching these minor issues would come under good first issues, if it does , I'd like to contribute

**Comment by memsharded** [comment]
You won't typically have time for this, I already submitted a fix. Better look for officially labeled ``good first issue`` tickets.

**Comment by AbhijithGanesh** [comment]
Cool then, I got my questions resolved.
