### ISSUE TITLE
[question] How to use Boost with GCC on MacOS

### ISSUE THREAD

**Issue by TorstenRobitzki** [conan-io/conan#10543]
I try to use Conan to build software that has some nasty dependencies to GCC on my Mac. That's my `conanfile.txt`:

    [requires]
    boost/1.73.0

    [generators]
    cmake

I created an empty build folder and execute `conan` from within it: `conan install --settings compiler=gcc --settings compiler.version=9.3 --settings compiler.libcxx=libstdc++11 --settings build_type=Debug --build missing ..`

One of the determined dependencies is `bzip2/1.0.8`. While `conan` tries to build `bzip2`, it seems like the `bzip2` recipe is not  considering the configured compiler:

    bzip2/1.0.8: Configuring sources in /Users/todi/.conan/data/bzip2/1.0.8/_/_/source
    Downloading bzip2-1.0.8.tar.gz completed [791.04k]                                       

    bzip2/1.0.8: Copying sources to build folder
    bzip2/1.0.8: Building your package in /Users/todi/.conan/data/bzip2/1.0.8/_/_/build/f79896e3c4f536ceaf3e9844c09efa8f19061889
    bzip2/1.0.8: Generator cmake created conanbuildinfo.cmake
    bzip2/1.0.8: Aggregating env generators
    bzip2/1.0.8: Calling build()
    -- The C compiler identification is AppleClang 13.0.0.13000029
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Conan: called by CMake conan helper
    -- Conan: called inside local cache
    -- Conan: Adjusting output directories
    -- Conan: Using cmake global configuration
    -- Conan: Adjusting language standard
    -- Conan: Adjusting fPIC flag (ON)
    -- This project seems to be plain C, using 'AppleClang' compiler
    CMake Error at conanbuildinfo.cmake:581 (message):
      Incorrect 'gcc', is not the one detected by CMake: 'AppleClang'
    Call Stack (most recent call first):
      conanbuildinfo.cmake:140 (conan_check_compiler)
      CMakeLists.txt:7 (conan_basic_setup)

Used Conan version is 1.45.0. Is this a reasonable approach to build with a different compiler? What do I have to do, to be able to use different compilers on a certain platform?

TIA Torsten

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SpaceIm** [comment]
There is no magic in `--settings compiler=gcc`, it's just a promise you make to conan that gcc will be used by any underlying build system called by the recipe. You have to honor this promise yourself, for example by setting CC & CXX env vars in profile to point to gcc & g++, because it's not the default compiler on mac.

**Comment by TorstenRobitzki** [comment]
Ah ok. That makes sense. My hope / expectation was, that I could use Conan to install compilers along with other packages and to build software with specific versions of that compilers.

**Comment by SpaceIm** [comment]
It's also possible, you have to create a recipe packaging this compiler. Then it could be used as a build requirement.

**Comment by TorstenRobitzki** [comment]
Thanks for the tipp, I will look into this.
