### ISSUE TITLE
[bug] Source files not copied on export using the `scm` attribute on Windows

### ISSUE THREAD

**Issue by j-brent** [conan-io/conan#10551]
The path to the source files used by scm contains forward slashes, which causes it to be misinterpreted by Windows.  This results in none of the source files actually being copied to `scm_source`, and an entirely new and spurious empty folder being created elsewhere. The relevant line in the log output below is `SCM: Getting sources from folder: /c/dev/my-app`.

```console
c:\dev\my-app>conan export . --ignore-dirty
Exporting package recipe
my-app/0.1.0: Repo origin deduced by 'auto': git@github.com:me/my-app.git
my-app/0.1.0: SCM: Getting sources from folder: /c/dev/my-app
my-app/0.1.0: A new conanfile.py version was exported
my-app/0.1.0: Folder: C:\Users\me\.conan\data\my-app\0.1.0\_\_\export
my-app/0.1.0: Exported revision: 0d41497c7n579f0591699e19c136197e70cb86d1
```

After running the above command, the `scm_source` folder 
	`C:\Users\me\.conan\data\my-app\0.1.0\_\_\scm_source` 
which should have been populated with the contents of 
	`C:\dev\my-app`
is in fact empty, and a new empty folder 
	`C:\c\dev\my-app` 
has been created. Notice the extra `\c` after `C:`.

Note that the contents of the folder
	`C:\Users\me\.conan\data\my-app\0.1.0\_\_\export`
are as expected, which is not surprising since the path printed on the console uses backslashes.

Given all of this I am fairly confident that the problem is caused by the differing use of forward slashes and backslashes. I have also tried passing the path explicitly to the `export` command
```console
conan export "C:\dev\my-app" --ignore-dirty
```
but the log message is the same as above, with forward slashes in the path
```console
my-app/0.1.0: SCM: Getting sources from folder: /c/dev/my-app
```
and I get the exact same outcome.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Enterprise - Version: 20H2 -  OS Build: 19042.1466
  * Compiler+version: MSVC v142
  * Conan version: 1.44.0
  * Python version: 3.9.6

**Comment by memsharded** [comment]
Hi @j-brent 

How does your conanfile.py looks like? can you please share it (at least the exports, exports_sources, the scm and source(), just in case). Also the .gitignore in your repo, and what files are in there (the .gitignore is actually used to avoid exporting unwanted files)

**Comment by j-brent** [comment]
Hi @memsharded 
I have created a minimal project that reproduces the issue. Here is a link to the repository: https://github.com/j-brent/hello. It's a fork of the HelloConan example, with minimal modifications, so I hope it should be familiar to you.

**Comment by memsharded** [comment]
Thanks very much @j-brent for putting together a reproducible case.

The thing is that I have just tried, carefully following your README instructions, and it is working correctly here.
I have no idea what could it be, quick question, I guess if you don't pass ``--ignore-dirty`` does it work correctly? Or still same error?

**Comment by j-brent** [comment]
Hi @memsharded. In response to your question, I got the same behavior without the `--ignored-dirty` flag. 

[SOLUTION] It turns out the issue occurred because `C:\cygwin64\bin` was in my path variable before `C:\Program Files\Git\cmd`, so the wrong version of `git.exe` was called. So it wasn't an issue with conan at all. To be honest I'm not quite sure why `C:\cygwin64\bin` should be in the path variable at all, so I will just remove it altogether for now.

Thanks so much for taking the time to look into this. I only hope that this conversation might be helpful for someone else who stumbles into the same problem.

**Comment by memsharded** [comment]
> SOLUTION] It turns out the issue occurred because C:\cygwin64\bin was in my path variable before C:\Program Files\Git\cmd, so the wrong version of git.exe was called. So it wasn't an issue with conan at all. To be honest I'm not quite sure why C:\cygwin64\bin should be in the path variable at all, so I will just remove it altogether for now.

> Thanks so much for taking the time to look into this. I only hope that this conversation might be helpful for someone else who stumbles into the same problem.

Thanks to you for following up and reporting the solution!

Regarding the interactions with Windows subsystems like cygwin, I'd like to take the chance and comment about the new build system integrations behavior wrt Windows subsystems:

- The integrations will be less "smart" and not try to autodetect subsystems. Instead things should be explicit.
- There are new conf items, like ``tools.microsoft.bash:subsystem`` and ``tools.microsoft.bash:path`` intended to explicitly define the subsystem to use and the path to the used bash. 
- Also, relying on the ``setting`` ``os.subystem: [None, cygwin, msys, msys2, wsl]`` for Windows will be more used (note this setting is for building to target those subsystems, not the same as when only using the ``bash`` of some subsystem to run autotools and do a native target build, that will run on the native Windows.
