### ISSUE TITLE
[question] Does some 

### ISSUE THREAD

**Issue by initlifeinc** [conan-io/conan#10556]
I Found Gitlab already try support Conan integration in mars 2020
https://about.gitlab.com/blog/2020/03/31/conan-c-cpp-package-management-integration/

It seems Conan is a excellent C++ Package Management Tool，
But i'm a little confused why I don't hear from large companies or some famous applications around me trying to use it, Why?
Maybe i'm the one who has no information about these, maybe they have already use Conan but just is i don't known。

**So if it is exist, can i known who are using Conan. If not, Why Conan cannot become a popular C++ Package Management Tools？Does somebody give me some reasons? Thanks**

(maybe vcpkg is also good to choose, but I still think open source Conan can be the winner as i known)

**Comment by memsharded** [comment]
Please read for example about the Tribe, you will see big companies using it there: https://conan.io/tribe.html

You also want to read: https://blog.conan.io/2022/01/04/conan-stats-2021.html. That blog post include a link to the ISO C++ survey: https://isocpp.org/files/papers/CppDevSurvey-2021-04-summary.pdf, please have a look at that too. Join the CppLang Slack, the #conan channel there is consistently one of the most active ones in the whole C++ community. There are literally many thousands of companies, including a lot of the Fortune 500 ones, using Conan in production. Conan is used for mobile phones SW, health devices, cars, both traditional and autonomous, navigation SW, finance, etc. We have started to write some more specific success stories in https://conan.io/user-stories.html, but that takes time, we are working in the next 2 now.

**Comment by initlifeinc** [comment]
It's sounds very great!

I hope we will see some success stories and their success usage to integrate with existing c++ project.
