### ISSUE TITLE
[question] Export a package from local cache to directory/zip

### ISSUE THREAD

**Issue by district10** [conan-io/conan#10555]
Given an existing package in local cache, how to export this specific package to directory?

As suggested in <https://media.jfrog.com/wp-content/uploads/2021/05/25084434/conan-cheatsheet.pdf>, I can use `conan install zlib/1.2.11@ -g deploy` to deploy zlib to current directory. But... how to skip dependency libs and `deploy_manifest.txt`? I only need this one package.

A walk-around is:

```
cp -rf $(conan info zlib/1.2.11@ -j --paths | python3 -c 'import json, sys; print(json.load(sys.stdin)[-1]["package_folder"])') output_dir
```

But this is not clean.

Any suggestions?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @district10 

Isn't it much simpler to do a ``-g deploy`` then a ``rm ...`` or a ``cp`` to a different place, then ``rm`` the rest, to remove what you don't want? That is completely straightforward and easy to understand, what is the problem with that?

**Comment by district10** [comment]
@memsharded I'm currently using this. It's just a little bit heavy, especially when your current conan package is quite small, but your dependency libs are big.

When `conan upload` a package, it will create a tarball, can we have a speciall upload routine, just to export this tarball to directory?

BTW, I'm archiving every conan package created on each commit on CI, that's where the need came from.

**Comment by memsharded** [comment]
> When conan upload a package, it will create a tarball, can we have a speciall upload routine, just to export this tarball to directory?

Not now, in 1.X, as things are very coupled. In Conan 2.0, there will be access to the python API and there will be more access to these routines, so it might be possible to implement this.

> BTW, I'm archiving every conan package created on each commit on CI, that's where the need came from.

One possible way is to archive things in a specialized server, like Artifactory. This has some advantages, for example, it is very efficient, as it has de-duplication of files, so even archiving the whole build, including dependencies, so you can have a full snapshot of your package AND dependencies there, and it will not take extra space. A possible approach is to create one repo per build, but it is also possible to use just one "build" repo, and upload the packages there. Enabling Conan package ``revisions`` will take care that every commit will create a new revisions, so they are all stored, referenced and usable in the server, just by requiring explicitly the revision that you want.

**Comment by district10** [comment]
@memsharded Thanks for quick reply.

We're using artifactory actually. But uploading every conan package for each commit is too noisy (and the package name will be like `package/semantic_version_git_hash@xxx/stable`). This will flooding `conan search -r all | grep <my_package>`.

Maybe we can create multiple artifactory conan repository, upload to `conan-nighty` for each commit, `conan-release` for serious package release.

**Comment by memsharded** [comment]
> package/semantic_version_git_hash@xxx/stable). This will flooding conan search -r all | grep <my_package>.

You might be interested in the recipe revision using the ``revision_mode = "scm"`` in your recipes, so the revision captured matches the git commit. That means that packages are ``pkg/semantic_version@user/stable#revision``, (by default the latest revision in the server is used), and that enables faster CI flows, as consumers of a package doesn't need to be modified to use the lastest revision in the server, and they can ``require = "pkg/semantic_version@user/stable"``. As always, this is a trade-off between speed and control, balanced by the amount of automation is delegated to Conan or to other automation in the CI.


> Maybe we can create multiple artifactory conan repository, upload to conan-nighty for each commit, conan-release for serious package release.

Yes, this is a recommended practice in general (for package management, other languages too, not only Conan), we have some hints in: https://docs.conan.io/en/latest/versioning/lockfiles/ci.html#repositories

**Comment by memsharded** [comment]
Conan 2 implemented ``conan cache save/restore`` commands, closing this ticket as implemented in Conan 2
