### ISSUE TITLE
[bug] should_configure, should_build, and should_install are not considered in conan.tools.gnu.Autotools generator

### ISSUE THREAD

**Issue by JonathanGirardeau** [conan-io/conan#10557]
### Environment Details
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc 9.3.0
  * Conan version: 1.44.1
  * Python version: 3.8.10

### Steps to reproduce
Hello,

The conan doc says we can use `-c`, `-b`, `-i` and `-t` options in `build` command  to execute only some steps.
When I tried to use them, it seems they have no effect.
I noticed conan.tools.gnu.Autotools generator does not consider `should_configure`, `should_build`, and `should_install` attributes, I think that' why options (`-c`, `-b`, `-i` and `-t`) has no effect in may case.

**Comment by memsharded** [comment]
Hi @JonathanGirardeau 

No, those args are not used, and they will not be used in the new generators.
They were intended in the past for ``conan build`` doing different steps. The focus with the new integrations is to use a native integration, not using ``conan build`` except for testing the recipe, but not for building. The ``generate()`` method is in charge to prepare the build, so the user can just call their build system natively (calling cmake, make, opening VS or whatever other tools they use natively)

According to that, all the ``should_xxx`` have been removed in Conan 2.0, there is no plan to keep them.

**Comment by JonathanGirardeau** [comment]
Thanks for the answer. 
I think the features you don't plan to support (like `should_xxx`) should be tagged as "deprecated" in the documentation. It would prevent new users from using these features. 
In my opinion, the `conan build` command is easier to use than the "native commands". With "native commands" you have to know what build system to use and you have to run 2 commands (./configure and make or cmake and make). 
To use "native commands", I have to run `conanbuild.sh` script before ? I saw it exports environment variables but I didn't see the `configure_args`. Does it mean I have to write by my self the arguments for the `configure` command ?

**Comment by memsharded** [comment]
> In my opinion, the conan build command is easier to use than the "native commands". With "native commands" you have to know what build system to use and you have to run 2 commands (./configure and make or cmake and make).

Yes, but the push by the users to achieve a more "transparent" integration with the build systems has been clear, and we are following that. While the ``conan build`` command will stay for convenience, the granularity provided by the ``should_xxx`` seems that no longer make sense.

> To use "native commands", I have to run conanbuild.sh script before ? I saw it exports environment variables but I didn't see the configure_args. Does it mean I have to write by my self the arguments for the configure command ?

Yes, the environment captures everything. ``generate()`` puts everything into files, so everything is explicit. No ``configure_args`` are injected dynamically anymore in the ``build()`` method by the new ``Autootools`` helper, which now barely calls ``.configure`` and ``make`` without arguments. It is generally easy to activate an environment and be able to open an IDE within that, than having an IDE having to call ``conan build`` for actually build things.

**Comment by JonathanGirardeau** [comment]
Thanks for the answer
