### ISSUE TITLE
[question] 'in_local_cache' value when doing 'conan export-pkg'

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#10569]
Hi,

What is the expected value of `self.in_local_cache` on execution of the _layout()_ method when calling the `conan export-pkg` command without  `–package-folder` option?
I would expect `self.in_local_cache == True` since I'm working locally on a package (the artefacts being packaged are in local build and source folders, not in cache).

TIA

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by marausch** [comment]
Sorry!
I've seen right now that my question is similar to [#10173](https://github.com/conan-io/conan/issues/10173).
Anyways, it is not completely a duplicate of if because I'm trying to distinguish `in_local_cache` _True_ or _False_ in the _layout()_ method instead of _package()_.

**Comment by memsharded** [comment]
Yes, seems the same, closing this one, and follow-up on the other.
