### ISSUE TITLE
When old conan versions are removed from pip?

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#1056]
Pip is advertised  as a preferred way to install Conan, however it seems to be that installation pinned versions from pip is not reliable. https://pypi.python.org/pypi/conan contains only the latest patch release for any minor version before 0.20.x, i.e. `pip install  conan==0.19.2` fails.

When using downloaded installer we can at least cache it locally, so if it is gone from public server it is not fatal. I think only the most broken releases (e.g. containing serious security flaws) should be removed.

At least, I'd like to know exact policy.

**Comment by memsharded** [comment]
Yes, you are right. This was a failure in our release process.
From now on, versions will not be removed from PyPI, unless something is really critical.

**Comment by memsharded** [comment]
It seems nothing to do here, the policy for keeping all older releases has been properly implemented. Thanks for pointing this out.
