### ISSUE TITLE
[question] How to merge python_requires similar to recipe options and settings?

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#10565]
Using `python_requires` with a base class, this base class also has its own `python_requires`.
But the specification of `python_requires` in the derived class overwrites the base class's `python_requires` and thus looses the base class' information.

The suggested approach for this merging of recipes is via the `init()` method, but it seems that at this time the `python_requires` object has already been created (a `PyRequires` object) from the string representation as defined in the recipe.

How to merge `python_requires` similar to recipe `options` and `settings` when using `python_requires`?

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @SeanSnyders 

I have this test with transitive ``python_requires`` and also using the ``python_requires_extend`` to extend the base classes. Could you please clarify your issue within this test: https://github.com/conan-io/conan/pull/10568? Thanks!

**Comment by memsharded** [comment]
Hi, 

I have been checking your feedback in https://github.com/conan-io/conan/pull/10568.

It seems that what you are trying to achieve is not possible, and unfortunately, it will not be possible, as it is a chicken and egg problem:

- python-requires are evaluated the very first thing, even before the ``init()`` method is called (the ``init()`` method was actually born to be able to access/update/merge things from the ``python-required`` recipe)
- If the used ``python_requires`` does not directly evaluate its own ``python_requires``, the evaluation will stop there. Whatever is in other classes rather than the ``ConanFile`` derived one, will not be expanded.
- Trying to update them in the ``init()`` will not work, as the evaluation of ``python_requires`` already happened.

So the only possibilities for multiple inheritance is:

- Put the ``python_requires`` directly in the ``ConanFile`` derived classes
- Avoid multiple levels, and do multiple parallel explicit ``python_requires`` when needed. In general, as recommended by the docs:
  ```python-requires can python-require other recipes too, but this should probably be limited to very few cases, we recommend to use the simplest possible structure.```

**Comment by SeanSnyders** [comment]
Hi @memsharded Thanks for the reply.

Hmmm... having read your reply a few times and have it muddle over in my mind, I am still a bit confused on the pertinent points you are trying to convey.

I am actually not trying to do multiple inheritance. I am trying to access class(es) defined via `python_requires` **from within** the same class where it is defined in.

The Conan docs state that you do not derive from `ConanFile` in the base class that you want to extend your recipe from.
Okay, done that in my example (and in my actual project). Check.

Then I tried to access this class (a helper class, a normal pure python class) from within the class where it is defined via the `self.python_requires[<package_name>].module.<class_name>()` such that I can access the actual class generically as resolved through the defined dependency specification in `python_requires`.

I have updated my example to reflect this. It is now more akin to my actual project. My original changes might have been a red herring as to putting the logic in the `init()` method of the consumer class. The access is actually in the base recipe class (which do not derive from `ConanFile`) and is not specifically needed in the `init()` thereof, but later in the Conan method flow. For this conversation example below, I put it in the `generate()` method.
When I saw that this dependency was not in the `self.python_requires` object, I thought I had to also merge it like `settings` and `options` and thus trying to access it in the `init()` method to do this merge. This sparked the original question for this issue.

**`company/conanfile.py`**:
```python
from conans import ConanFile
class CompanyConanFile(ConanFile):
    name = "company"
    version = "1.0"

class CompanyBase(object):

    python_requires = "project/1.0"

    def msg1(self):
        return "company"
    def msg2(self):
        return "company"

    def init(self):
        self.output.info(f"---CompanyBase.init()---")
        self.output.info("Executing CompanyBase.init() specific logic...")
        for (k,v) in self.python_requires.items():
            self.output.info(f"self py_req: {k}")

    def generate(self):
        self.output.info(f"---CompanyBase.generate()---")
        self.output.info("Executing CompanyBase.generate() specific logic...")
        for (k,v) in self.python_requires.items():
            self.output.info(f"self py_req: {k}")
        # would want to access the transitive python_requires class 'ProjectBase' from project
        project_req_name = 'project'
        #project = self.python_requires[project_req_name].module.ProjectBase()
        #self.output.info(project.msg1())
        try:
            project_req = self.python_requires[project_req_name]
        except KeyError:
            raise ConanException(f"Project requirement with name '{project_req_name}' does not seem to be available. Check correct requirements.")
```

**`project/conanfile.py`**:
```python
from conans import ConanFile
class ProjectConanFile(ConanFile):
    name = "project"
    version = "1.0"

class ProjectBase(object):
    def msg1(self):
        return "project"
```

**`consumer/conanfile.py`**:
```python
from conans import ConanFile

class ConsumerConanFile(ConanFile):
    name = "consumer"
    version = "1.0"
    python_requires = "company/1.0"
    python_requires_extend = "company.CompanyBase"

    def init(self):
        self.output.info(f"---ConsumerConanFile.init()---")
        # up-call
        self.output.info(f"Up-calling from ConsumerConanFile.init()...")
        super().init()

        self.output.info("Executing ConsumerConanFile.init() specific logic...")
        for (k,v) in self.python_requires.items():
            self.output.info(f"self py_req: {k}")

    def generate(self):
        self.output.info(f"---ConsumerConanFile.generate()---")
        # up-call
        self.output.info(f"Up-calling from ConsumerConanFile.generate()...")
        super().generate()

        self.output.info("Executing ConsumerConanFile.generate() specific logic...")
        self.output.info("Msg1:{}!!!".format(self.msg1()))
        self.output.info("Msg2:{}!!!".format(self.msg2()))
```

Running in the folder where these recipes are defined in their respective folders:
`mkdir build && cd build`
and then
`conan export ../company && conan export ../project && conan install ../consumer`

gives me this output:
```
$ conan export ../company && conan export ../project && conan install ../consumer
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
company/1.0: A new conanfile.py version was exported
company/1.0: Folder: /Users/ssnyder/Development/TmpConanData/company/1.0/_/_/export
company/1.0: Using the exported files summary hash as the recipe revision: f6358cb057f305e2b71e16df38cab2d7 
company/1.0: Exported revision: f6358cb057f305e2b71e16df38cab2d7
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
project/1.0: A new conanfile.py version was exported
project/1.0: Folder: /Users/ssnyder/Development/TmpConanData/project/1.0/_/_/export
project/1.0: Using the exported files summary hash as the recipe revision: 32acc7d49543eb033443af4f5fd7f4d9 
project/1.0: Exported revision: 32acc7d49543eb033443af4f5fd7f4d9
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

: ---ConsumerConanFile.init()---
: Up-calling from ConsumerConanFile.init()...
: ---CompanyBase.init()---
: Executing CompanyBase.init() specific logic...
: self py_req: company
: Executing ConsumerConanFile.init() specific logic...
: self py_req: company
conanfile.py (consumer/1.0): Installing package
Requirements
Python requires
    company/1.0
Packages

Installing (downloading, building) binaries...
conanfile.py (consumer/1.0): Generator txt created conanbuildinfo.txt
conanfile.py (consumer/1.0): Calling generate()
conanfile.py (consumer/1.0): ---ConsumerConanFile.generate()---
conanfile.py (consumer/1.0): Up-calling from ConsumerConanFile.generate()...
conanfile.py (consumer/1.0): ---CompanyBase.generate()---
conanfile.py (consumer/1.0): Executing CompanyBase.generate() specific logic...
conanfile.py (consumer/1.0): self py_req: company
ERROR: conanfile.py (consumer/1.0): Error in generate() method, line 23
	super().generate()
while calling 'generate', line 31
	project_req = self.python_requires[project_req_name]
	ConanException: 'project' is not a python_require
```

**Comment by memsharded** [comment]
The key is this:

```python
from conans import ConanFile
class CompanyConanFile(ConanFile):
    name = "company"
    version = "1.0"

class CompanyBase(object):

    python_requires = "project/1.0"

    def msg1(self):
        return "company"
    def msg2(self):
        return "company"
```

The ``CompanyBase.python_requires`` is just a class attribute, not processed by Conan at all.

If this ``company/1.0`` package is being required as ``python_requires`` by other ``consumer`` recipe, the ``python_requires`` have already been processed and expanded. But ``project/1.0`` was not part of that. You can access it, but you will access only the string, but you will never be able to access the ``Project`` python-requires because it has not been fetched or parsed at all. It doesn't exist, you cannot access the ``Project`` base class not because you don't have access via the interface, but because the class don't even exists.

For ``python_requires = "project/1.0"`` to be processed, it needs to be declared in ``CompanyConanFile`` (extending ConanFile), not in ``CompanyBase``

**Comment by SeanSnyders** [comment]
>The `CompanyBase.python_requires` is just a class attribute, not processed by Conan at all.

So why can it not be included to be processed as part of the Conan extension mechanism?
I'd like that to be the case and use Conan dependency resolution give me the correct final version of this dependency.
I do not necessarily want to derive a `ConanFile` recipe from this, I just want to use functionality from this bag-of-tricks in python files published as a Conan package. To my reading of Conan docs, this is the use-case, no?

>For `python_requires = "project/1.0"` to be processed, it needs to be declared in `CompanyConanFile` (extending ConanFile), not in CompanyBase

Conan documentation recommends not extending from `ConanFile` for the base class, as noted before. Any comment on this in light of this specific situation?

What I really want is simple.
I have a bag of tricks coded in python file(s) published as a Conan package.
I have a class that makes use of these tricks that is intended to be a base class for recipes.
All my final product recipes extend from this base class.
My final product recipes specify this base class as a `python_requires` and then extends from this base class via `python_requires_extend`.

How do I access the correct version/dependency of this bag of tricks in my base class?

I also looked into using plain python `import` to pull in this bag-of-tricks, as is noted by Conan docs (https://docs.conan.io/en/1.42/extending/python_requires.html#resolution-of-python-requires) to be supported.
I could not get this to work either. I also could not find examples of this mechanism working in the documentation.
![image](https://user-images.githubusercontent.com/1384135/154194507-33fe25c9-2513-439f-86db-3e725e089b60.png)

**Comment by SeanSnyders** [comment]
I have solved it by having my base recipe class to derived from `ConanFile` (as you suggested) instead of not (as suggested by the Conan docs).
The example below is now able to pull in the `project/1.0` dependency from within the `ConanBase` recipe.

Overall I think there needs to be more thought given to how developers will build systems around Conan - i.e. giving correct flexibility and making it possible to extend, encapsulate, etc in logical ways.
For example, I am not sure why the merging of `options` and `settings` is not a default behaviour (but could be altered through recipe developers if they need to).
Maybe some food for thought for Conan 2.0.

**`company/conanfile.py`**:
```python
from conans import ConanFile
class CompanyBase(ConanFile):
    name = "company"
    version = "1.0"

    python_requires = "project/1.0"

    def msg1(self):
        return "company"
    def msg2(self):
        return "company"

    def init(self):
        self.output.info(f"---CompanyBase.init()---")
        self.output.info("Executing CompanyBase.init() specific logic...")
        for (k,v) in self.python_requires.items():
            self.output.info(f"self py_req: {k}")

    def generate(self):
        self.output.info(f"---CompanyBase.generate()---")
        self.output.info("Executing CompanyBase.generate() specific logic...")
        for (k,v) in self.python_requires.items():
            self.output.info(f"self py_req: {k}")

        # would want to access the transitive python_requires class 'ProjectBase' from project
        project_req_name = 'project'
        try:
            project_req = self.python_requires[project_req_name]
        except KeyError:
            raise ConanException(f"Project requirement with name '{project_req_name}' does not seem to be available. Check correct requirements.")
        project = self.python_requires[project_req_name].module.ProjectBase()

        self.output.info(f"message1 from project: {project.msg1()}")
```

**`project/conanfile.py`**:
```python
from conans import ConanFile
class ProjectConanFile(ConanFile):
    name = "project"
    version = "1.0"

class ProjectBase(object):
    def msg1(self):
        return "project"
```

**`consumer/conanfile.py`**:
```python
from conans import ConanFile

class ConsumerConanFile(ConanFile):
    name = "consumer"
    version = "1.0"
    python_requires = "company/1.0"
    python_requires_extend = "company.CompanyBase"

    def init(self):
        self.output.info(f"---ConsumerConanFile.init()---")
        # up-call
        self.output.info(f"Up-calling from ConsumerConanFile.init()...")
        super().init()

        self.output.info("Executing ConsumerConanFile.init() specific logic...")
        for (k,v) in self.python_requires.items():
            self.output.info(f"self py_req: {k}")

    def generate(self):
        self.output.info(f"---ConsumerConanFile.generate()---")
        # up-call
        self.output.info(f"Up-calling from ConsumerConanFile.generate()...")
        super().generate()

        self.output.info("Executing ConsumerConanFile.generate() specific logic...")
        self.output.info("Msg1:{}!!!".format(self.msg1()))
        self.output.info("Msg2:{}!!!".format(self.msg2()))
```

Running in the folder where these recipes are defined in their respective folders:
`mkdir build && cd build`
and then
`conan export ../project && conan export ../company && conan install ../consumer`

gives me this **successful** output:
```
conan export ../project && conan export ../company && conan install ../consumer
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
project/1.0: A new conanfile.py version was exported
project/1.0: Folder: /Users/ssnyder/Development/TmpConanData/project/1.0/_/_/export
project/1.0: Using the exported files summary hash as the recipe revision: 5258ed82c2c37a8eec4fc8ab498b0a3c 
project/1.0: Exported revision: 5258ed82c2c37a8eec4fc8ab498b0a3c
: ---CompanyBase.init()---
: Executing CompanyBase.init() specific logic...
: self py_req: project
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
company/1.0: A new conanfile.py version was exported
company/1.0: Folder: /Users/ssnyder/Development/TmpConanData/company/1.0/_/_/export
company/1.0: Using the exported files summary hash as the recipe revision: 412c4b17a9514ecd7dd3ccd575ac8988 
company/1.0: Exported revision: 412c4b17a9514ecd7dd3ccd575ac8988
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

: ---CompanyBase.init()---
: Executing CompanyBase.init() specific logic...
: self py_req: project
: ---ConsumerConanFile.init()---
: Up-calling from ConsumerConanFile.init()...
: ---CompanyBase.init()---
: Executing CompanyBase.init() specific logic...
: self py_req: company
: Executing ConsumerConanFile.init() specific logic...
: self py_req: company
conanfile.py (consumer/1.0): Installing package
Requirements
Python requires
    company/1.0
    project/1.0
Packages

Installing (downloading, building) binaries...
conanfile.py (consumer/1.0): Generator txt created conanbuildinfo.txt
conanfile.py (consumer/1.0): Calling generate()
conanfile.py (consumer/1.0): ---ConsumerConanFile.generate()---
conanfile.py (consumer/1.0): Up-calling from ConsumerConanFile.generate()...
conanfile.py (consumer/1.0): ---CompanyBase.generate()---
conanfile.py (consumer/1.0): Executing CompanyBase.generate() specific logic...
conanfile.py (consumer/1.0): self py_req: company
conanfile.py (consumer/1.0): message1 from project: project
conanfile.py (consumer/1.0): Executing ConsumerConanFile.generate() specific logic...
conanfile.py (consumer/1.0): Msg1:company!!!
conanfile.py (consumer/1.0): Msg2:company!!!
conanfile.py (consumer/1.0): Aggregating env generators
conanfile.py (consumer/1.0): Generated conaninfo.txt
conanfile.py (consumer/1.0): Generated graphinfo
```

**Comment by memsharded** [comment]
> So why can it not be included to be processed as part of the Conan extension mechanism?

Because it is not possible to know. The flexibility is high, and even if we always recommend users to keep things as simple and flat as possible, they will always do unexpected things that would break badly in different ways, and drive us down the rabbit hole. A very simple scenario, someone putting 2 different base classes in same ``python-requires``:

```python
class VSRecipe(object):
      python_requires = "only_visual/1.0"

class CMakeRecipe(object):
      python_requires = "only_cmake/1.0"

class PythonRequire(ConanFile):
      name = "myrecipe"
      version = "0.1"
```

And then some recipes will do ``python_requires_extend = "myrecipe.CMakeRecipe"`` and others will do ``python_requires_extend = "myrecipe.VSRecipe"``. Doing any automatic expansion of ``python_requires`` over all the classes defined in the file will crash or result in wrong results.


We really put a thought on these things, we work very hard thinking about these issues. Let me clarify some of the ideas:

> For example, I am not sure why the merging of options and settings is not a default behaviour (but could be altered through recipe developers if they need to).

Implementing things as built-in as default behavior tend to be more blocking than the opposite. There will always be a relevant amount of users wanting to do the opposite ("don't merge the options automatically, I only want to apply some for xyz reasons"), and if you have already merged as default, then it is more likely that you are blocking those users, which will struggle to find a way to opt-out. We try to make Conan as explicit as possible, and actually Conan 2.0 is doing a good step further in that direction.

> Conan documentation recommends not extending from ConanFile for the base class, as noted before. Any comment on this in light of this specific situation?

I am checking https://docs.conan.io/en/latest/extending/python_requires.html, and  I don't see a explicit recommendation to do that. The examples and explanation uses a different class, because it is cleaner to see that the functionality of the ``source()``, ``build()``, methods is used only by the consumer, but not in the python-require itself. In general it looks cleaner this way, but for some cases, specially everything that is class-attribute, there might be exceptions (the docs is listing some in the "limitations" section), in this case, it ``python_requires`` is a Conanfile class level attribute, not functional and to work correctly it needs to be defined in a Conanfile derived class. I will add that to the docs to make it clear.

What is explicitly said is:

> python-requires can python-require other recipes too, but this should probably be limited to very few cases, we recommend to use the simplest possible structure.

This is probably one of the most important points, and maybe we want to make a highlight note at the beginning. It is not expected that the ``python_requires`` mechanism would be as flexible as standard python inheritance, and things like multiple inheritance will always be challenging. The challenge of extending from Python code that is not even in your machine and needs to be fetched from a server while the current Python module file is being evaluated is big. We are happy about its current form, and we don't intend to try to make it more complex to support more complicated structures, because we know from experience this has later a negative net effect, with more bugs, more support tickets, less happy developers, more difficult to evolve code... We have been there a lot of times already, and I'd say the current ``python_requires``  proposal is a good trade-off between functionality offered to users and effort to maintain it.

**Comment by SeanSnyders** [comment]
A good reply, thanks, and it really opens up a discourse.

Hopefully we will not hit a more complex situation where Conan will be a blocker with respect to including reusable python modules. I hear what you are saying about complexity. I am not advocating more complexity, I am asking for better usage. The engineering challenge is to make the solution not complex.
A large part of pulling in correct reusable python modules, via e.g. `python_requires`, is in my mind very similar in net effect to the purpose of using Conan for resolving dependencies. So handling python module conflicts should be very much in line with handling dependency (and their version) conflicts in current Conan.

In comparison, for creating reusable CMake-only components, I'd define normal Conan dependencies for these CMake-only Conan packages and build their dependency graph that way. No implicit `python_requires` mechanism in the code itself that needs to be processed thus making it "complex".
The correct CMake components (functions, etc) are then available in my CMake projects to be used.
For this scenario, Conan does its job of dependency management and resolution, and Conan's implemented mechanism of loading CMake modules as defined by the generators kick in.
Maybe there should be a "python module import" generator that can decouple the specification of python modules to depend on and some way to nicely import these where/how required?

With regards to the documentation, the list of limitations are quite complex.
I'd definitely vote to make the documentation as explicit as possible and with plentiful examples showing what to do and *what not to do* - especially in light of every limitation noted.

Thanks again for all the communication. I appreciate it.

**Comment by SeanSnyders** [comment]
Actually, just trying to update my project with having the base recipe class derive from `ConanFile` and I hit a snag:
how to decouple the reusable bits (base recipe python classes, reusable cmake bits, etc) from the recipe that packages these reusable bits?

Conan does not allow more than one class that derives from `ConanFile` in the `conanfile.py` file.
So the suggestion does not work to solve access to the `python_requires` python modules in the base recipe (e.g. the `project/1.0` in `BaseRecipe` as defined in the example below:


**`company/conanfile.py`**:
```python
from conans import ConanFile
from conan.tools.cmake import CMakeDeps

class CompanyReusableConanMagicPackage(ConanFile):
    name = "Reusable"
    version = "1.0"
    settings = "build_type"
    generators = "CMakeDeps"

    exports_sources = "ReusableConfig.cmake", "src/cmake/**",

    def generate(self):
        cmakeDeps = CMakeDeps(self)
        cmakeDeps.build_context_activated = ["Reusable"]
        cmakeDeps.build_context_build_modules = ["Reusable"]
        cmakeDeps.generate()

    def package(self):
        self.copy(f"ReusableConfig.cmake", keep_path=False)
        self.copy(f"*", dst="cmake", src="src/cmake", keep_path=True)

    def package_info(self):
        self.cpp_info.build_modules["cmake"].append("ReusableConfig.cmake")
        self.cpp_info.build_modules["cmake_paths"].append("ReusableConfig.cmake")
        self.cpp_info.build_modules["cmake_find_package"].append("ReusableConfig.cmake")
        self.cpp_info.build_modules["CMakeDeps"].append("ReusableConfig.cmake")


class BaseRecipe(object):

    python_requires = "project/1.0"

    def init(self):
        self.output.info(f"---BaseRecipe.init()---")
        self.output.info("Executing BaseRecipe.init() specific logic...")
        for (k,v) in self.python_requires.items():
            self.output.info(f"self py_req: {k}")

    def generate(self):
        self.output.info(f"---BaseRecipe.generate()---")
        self.output.info("Executing BaseRecipe.generate() specific logic...")
        for (k,v) in self.python_requires.items():
            self.output.info(f"self py_req: {k}")

        # would want to access the transitive python_requires class 'ProjectBase' from project
        project_req_name = 'project'
        try:
            project_req = self.python_requires[project_req_name]
        except KeyError:
            raise ConanException(f"Project requirement with name '{project_req_name}' does not seem to be available. Check correct requirements.")
        project = self.python_requires[project_req_name].module.ProjectBase()

        self.output.info(f"message1 from project: {project.msg1()}")

```

**Comment by SeanSnyders** [comment]
As I noted in a previous comment regarding a python module importer 'generator', I have implemented a workaround by setting python module paths via the `user_info` attribute in the `package_info()` method of my recipes that export reusable python modules.
I then use normal `build_requires` to resolve my dependencies, and thus are able to import modules from my dependencies where the recipes have a base class that does not derive from `ConanFile`. The python module path set in the `user_info` is available through the `user_info_build` attribute in the recipe.

This circumvents the limited `python_requires` as discussed in this thread.
I might roll this into a custom generator and make it more generic as mentioned before.
