### ISSUE TITLE
[question] How to deploy a package using version range using commands?

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#10572]
Hi,

I have a required package `MyPkg` of many versions. 
In my script, I need to **deploy** it referencing it **via package range**, for instance `[>0.0.2 <0.0.8]`.

My question is: 
**How to deploy the required package `MyPkg` using conan commands specifying a version range?**

N.B.
1. I know that I can use `conan install` with _a specific version_ to deploy a package, e.g. ```conan install MyPkg/0.0.2@ --install-folder /my/folder```, but I don't find a way to use it _with version range_, 
2. I tried to use `conanfile.txt` with `[requires]` has the package with version range, e.g. `MyPkg/[>0.0.2 <0.0.8]` or `MyPkg/[>0.0.2 <0.0.8]@`, then using `conan install .  --install-folder myif`, but it doesn't deploy, it only does like:
```CMD
Installing (downloading, building) binaries...
MyPkg/0.0.3: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
```
While, using `conan install MyPkg/0.0.3@ --install-folder myif`, deploys it:
```CMD
Installing (downloading, building) binaries...
MyPkg/0.0.3: Already installed!
Aggregating env generators
MyPkg/0.0.3 deploy(): Copied 1 '.lib' file: MyPkg.lib
```

Thanks,

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Bassem-Ramzy 

Haven't you tried something like:

```bash
$ conan install "zlib/[>0.0]@"
```
That should work, you can use a version range directly in your command line too

**Comment by Bassem-Ramzy** [comment]
Wow, great, it works, thanks a lot.
