### ISSUE TITLE
Support Artifactory Access Tokens for CI Integration

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1057]
Hi,

I have made use of Artifactory [access tokens](https://www.jfrog.com/confluence/display/RTF/Access+Tokens) for uploads interactively by doing a `conan user` and pasting in the encrypted password.  

But when I run the build in a docker container, I would prefer to use the authentication header instead of a specific user.  I could store it in a file or pass it on the command line or an environment variable.  My workaround is to build the docker image with a `.conan/.conan.db` resulting from having done the `conan user`, above.

This would take some doing to affect the HTTP headers, but it would be really nice for CI pipelines.

So this would be ideal:

```
conan upload --auth-file=ci_upload.tok ...
conan upload --auth-tok="32984723938sfkajshu6*#82981234"...
```

**Comment by lasote** [comment]
Sorry, I don't understand it well, are you using (hacking) something special from Artifactory access tokens or you are just using `conan user` command? Artifatory, as well as conan open source server, returns a token after a simple HTTP authentication with user and password. 

Your issue is that you want to authenticate directly with the token instead of pre-authenticate with user and pasword right?

**Comment by tamboril** [comment]
I'm using an access token as the password for the `conan user` so that conan stores it in its database, and I'm building my docker image with that database (`.conan-db`) pre-installed.  Because the build is automated, I cannot have a prompt.

My CI system (GoCD) has the ability to have non-displayed ("secure") environment variables; so it would be nice to set it up in the CI system and have `conan upload` use the token from the environment.

**Comment by lasote** [comment]
You can use the `conan user {user} -p {password}` to avoid the user input. I'm using that in CI with travis and appveyor with the "secure" environment variables.

**Comment by tamboril** [comment]
OK.  I think that's a good solution. Thanks.

**Comment by tamboril** [comment]
From the docs, it looks like `artifacts.properties` supports custom headers; so in theory the `upload` command should be able to use a Bearer authentication token, with no user, from that file.  But I can't seem to get it to work (a `ping` does work with `curl`).  Conan prompts me for a user name.

I've tried this with and without quotes (artifacts.properties):
```
Authorization="Bearer 29238382...."
Authorization=Bearer 29238382...
```

**Comment by lasote** [comment]
It doesn't work like that. The artifacts.properties only set custom properties for PUT requests. A conan upload contains two requests, the first is calling the conan server (or artifactory) to authorize the upload by generating an internal temporary token, the second is the PUT request and is only a signed url, so authentication can't be managed with `artifacts.properties`.
