### ISSUE TITLE
Feature: Get project URL from checkout when creating new conan package

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/conan#1058]
I wanted to create a new package for JUCE 4.3.1. 

So I created a new git repo for that:
https://github.com/CodingSpiderFox/juce-conan
I cloned it to my computer. 
Then I executed "conan new JUCE/4.3.1@CodingSpiderFox/stable -t"
which create this conanfile:

    from conans import ConanFile, CMake, tools
    import os

    class JuceConan(ConanFile):
        name = "JUCE"
        version = "4.3.1"
        license = "<Put the package license here>"
        url = "<Package recipe repository url here, for issues about the package>"
        settings = "os", "compiler", "build_type", "arch"
        options = {"shared": [True, False]}
        default_options = "shared=False"
        generators = "cmake"

    def source(self):
        self.run("git clone https://github.com/memsharded/hello.git")
        self.run("cd hello && git checkout static_shared")
        # This small hack might be useful to guarantee proper /MT /MD linkage in MSVC
        # if the packaged project doesn't have variables to set it properly
        tools.replace_in_file("hello/CMakeLists.txt", "PROJECT(MyHello)", '''PROJECT(MyHello)
        include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
        conan_basic_setup()''')

    def build(self):
        cmake = CMake(self.settings)
        shared = "-DBUILD_SHARED_LIBS=ON" if self.options.shared else ""
        self.run('cmake hello %s %s' % (cmake.command_line, shared))
        self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.copy("*.h", dst="include", src="hello")
        self.copy("*hello.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["hello"]

It would be nice if the repository URL is read automatically from git or svn info and assigned to the "url" member variable

**Comment by memsharded** [comment]
It might be possible to issue a ``git remote -v`` command, capture the output, get the first remote if more than one, and then use the URL. Implement for SVN too. But doesn't it looks like too much, for something you should have already typed, then able to copy & paste?

```bash
$ git clone https://github.com/CodingSpiderFox/juce-conan
$ cd juce-conan
$ conan new Juce/4.3.1@user/channel -t
# copy the URL from above
$ vim conanfile.py # or code/sublime/notepad...
# paste the URL
```
Basically it will add a bunch of code to ``conan export`` (then it has to be tested, manage error cases, etc), to avoid a copy & paste? IMHO that sounds like too overkill of a feature.

**Comment by lasote** [comment]
I agree, too much code for avoid copying the URL, and a package creation is not a task that you repeat so many times.
