### ISSUE TITLE
[feature] Allow marking remotes as disabled by default in 'remotes.txt'

### ISSUE THREAD

**Issue by slietzau** [conan-io/conan#10580]
We are using Artifactory and have different repositories for package maturity levels. For example, there is one repository we use for branch and Pull Request builds. By default this should be disabled because packages in there are not yet stable. However in some cases it's essential to develop a feature that spans multiple packages and requires consuming not-yet-released versions of packages for development.
In this situation we'd like to enable our `-dev` remote. But in almost all other situations we'd like to keep it disabled, but still configured so that our developers can easily activate it.

Of course, it would be possible for the developers to manually configure the `-dev` remote but we are using `config_install_interval` to force a periodic update of the conan configuration and that resets all remotes.

Summarizing we would like a way to configure a default enabled/disabled state for remotes which is not enforced when performing a conan config install. This ensures the remote is available but does not reset a users manual configuration.

If you have other ideas how to solve this, please put them forward.

We already thought about having a different conan configuration for the development environment (which includes the `-dev` remotes by default). But this is problematic in combination with `config_install_interval` since there will be multiple configurations which override each other and the order suddenly becomes important and I just expect this setup to fail spectacularly for colleagues that are not yet familiar with every detail of conan.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This might be possible, we have considered to remove the ``remotes.txt`` file from ``conan config install`` and use a full ``remotes.json`` file for that. Such file should contain the full state, including the "disabled" flag.

Let's consider this, the only problem is that it is unlikely to happen in 1.X, it is a bit risky of breaking, I am initially targeting this for 2.0.

**Comment by slietzau** [comment]
Thanks for the quick response. I'm glad this is on the table for Conan 2.0.

Do you have any hints how to go about this in the immediate future? To me it looks like our only option is to include all possible remotes in the list of remotes distributed in `remotes.txt` and then only let the user authenticate to those he whishes to use.

**Comment by memsharded** [comment]
> Summarizing we would like a way to configure a default enabled/disabled state for remotes which is not enforced when performing a conan config install. This ensures the remote is available but does not reset a users manual configuration.

This was not considered so far. We were thinking about allowing the full remotes.json specification, and dropping the remotes.txt, but doing a full replacement of the remotes. What you are suggesting implies "merging" the current information with the incoming one, and that is challenging: what properties should be kept and what properties should be updated? if a user changed the URL but kept the remote name, then should that be respected? And if the user changed the ``verify_ssl``? Why only the disabled state? 

> Do you have any hints how to go about this in the immediate future? To me it looks like our only option is to include all possible remotes in the list of remotes distributed in remotes.txt and then only let the user authenticate to those he whishes to use.

Yes, I think so, that is the only possibility at the moment.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/10598 will use ``remotes.json`` files in ``conan config install``, and that includes remotes enabled/disabled. Merging of the upstream configuration with the user (modified) cache one is not intended at the moment.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/10598

**Comment by stefansli** [comment]
@memsharded Would it be possibel to backport this to 1.X? I'm thinking about allowing `remots.json` files to be present but only if `remotes.txt` doesn't exist aswell. So one could only use either of them. Would that work? Or does that break some kind of backward compatibility?

In my opinion such a feature would be great so the same conan config can be used for both 1.X and 2.0
