### ISSUE TITLE
[question] Why settings are passed incorrectly to CMake when not including `compiler`?

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#10593]
Hi,
When building my project on Windows, using CMake, with recipe like:
```PYTHON
    name = "mylib"
    settings = "os", "build_type", "arch", "compiler"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```
For one of different settings: `Release` build type, and `x86` architecture, using the following command:
```CMD
conan create . -s build_type=Release -s arch=x86
```
The library is built as planned (having "compiler" in the settings), however, if the settings doesn't have `compiler`, like:
```PYTHON
    settings = "os", "build_type", "arch"
```
It builds for `x86_64`-`debug` instead. 

My code is also built for Linux, and it's assumed to be compiler-independent, and I want to exclude `compiler` from the settings as it is not matched on Linux with different compiler version, while my code compiles on both (e.g. compiler versions  8 & 9).

So my questions is: 
**How to exclude "compiler" from settings, while conan still passes the rest of settings to CMake correctly?**

Or, the root-cause question: 
**How to have the package compatible with range of compiler versions, while having "compiler" in settings?**, 
which I understand that, by design, we can't.

N.B. the configuration displayed is:
```CMD
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, the ``CMake`` and other build system integrations, if they are building, they need a compiler defined, or they will fail.
So it is necessary to leave the ``settings = "compiler"`` there, and if you want to achieve some binary compatibility, use the ``package_id()`` method, something like:

```python
def package_id(self):
     self.info.settings.compiler = "any"
```
Will assume the binary created can be consumed by any compiler (it might need doing something similar for the compiler subsettings too)

**Comment by Bassem-Ramzy** [comment]
OK, thanks
