### ISSUE TITLE
Rename CMAKE_SHARED_LINK_FLAGS

### ISSUE THREAD

**Issue by dragly** [conan-io/conan#106]
I couldn't find any CMake documentation for CMAKE_SHARED_LINK_FLAGS which shows up when generating conanbuildinfo.cmake. Is this a typo that should be [CMAKE_SHARED_LINKER_FLAGS](https://cmake.org/cmake/help/v3.0/variable/CMAKE_SHARED_LINKER_FLAGS.html)?

I'm not currently conan with CMake myself, so I haven't tested if it causes any errors at the moment.

**Comment by lasote** [comment]
Yes, it seems a bug. I have assigned to 0.7 milestone.
