### ISSUE TITLE
long version numbers failing to resolve

### ISSUE THREAD

**Issue by kent-at-multiscale** [conan-io/conan#1060]
I've been creating packages for third-party libraries. I use the third-party library version number, and append a build number to the end to distinguish between different builds using different recipes.

zlib/1.2.11-1
...
zlib/1.2.11-5
...
zlib/1.2.11-9

When I got to 10, things stopped working. I can upload just fine, but in a consumer project it fails to download the zlib package:
`ERROR: Can't find a 'zlib/1.2.11-10@user/channel' package for the specified options and settings`
But it did download the conanfile.py for the package.

When I do `conan search -r myrepo "zlib/1.2.11-10@user/channel"`, it says there are no packages for that pattern. But when I do `conan search -r myrepo "*"`, zlib/1.2.11-10@user/channel shows up in the list.

**Comment by kent-at-multiscale** [comment]
I tried replacing the dash with a dot, same result.

**Comment by memsharded** [comment]
Very weird indeed. Are you using version-ranges to consume it? Could be some semantic treatment of the "-10", which is not treated as a number but as a string, so depending on your expresion could be "smaller" than "2".

**Comment by kent-at-multiscale** [comment]
I was thinking the dash may have been interpreted as a range of some sort, so I tried replacing it with a period and the behavior was identical. Later in the day it worked fine. Tonight it has broken again.

I am wondering if there could be an intermittent bug in the conan server code, or possibly a protocol version mismatch. My client is 0.20.0, I'll ask ops what version the server is in the morning.

**Comment by memsharded** [comment]
Please upgrade to 0.20.2, we have already released minors fixing a few regressions (that is almost impossible to avoid when doing such big releases).

I think there shouldn't be server related, as the server doesn't explicitely model or manage versions. But who knows. Please ask, and tell if it happens again, reopen the issue and we will have a look. Thanks for reporting.

**Comment by kent-at-multiscale** [comment]
This issue has resurfaced. It is not consistent, but when it does happen it seems to apply to all clients for that one particular package version/build, and it remains in effect for hours. I was able to resolve the aforementioned zlib/1.2.11-10 yesterday afternoon, then that evening it failed again. It is still failing today. I have asked ops to upgrade the conan server to see if that has any effect.

**Comment by memsharded** [comment]
Ok, I will try to run some extended tests. 
One important thing would be client versions. If you upgrade to conan 0.20, packages generated with it might have issues with 0.19, so you need to upgrade all your conan clients using those packages to 0.20 too. Please check that all clients are upgraded to 0.20.

**Comment by kent-at-multiscale** [comment]
Yes, all the clients in question are using Conan 0.20.2 now.

**Comment by lasote** [comment]
Hi! I'm reviewing old issues. I would like to know if it works now. We have some users even using a git commit SHA as part of the version without any issue. So I assume it is solved now. Feel free to reopen the issue if it still persists.
