### ISSUE TITLE
Make ``self.export_folder`` available to export hooks

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#10604]
Now it is only local to the ``export()`` method.

Hi @memsharded,

This looks to be a very useful function and one we were literally about to look at implementing ourselves. However can I ask you to consider an additional usage scenario: 

We would like to capture to some data in the `conandata.yml` for all our package recipes (literally 100s) when running in CI, and so were planning on using a `post_export` hook. I've checked and the passed `conanfile` arg doesn't have the `export_folder` attribute available for this hook type, hence this new function wouldn't be usable in this scenario. 

Does it sound reasonable to add support for this use case?

_Originally posted by @santhonisz in https://github.com/conan-io/conan/issues/10586#issuecomment-1040864807_

**Comment by AbrilRBS** [comment]
Closing as solved in 2.0, as shown in https://github.com/conan-io/conan/blob/develop2/conans/test/integration/hooks/hook_test.py#L20 `conanfile.export_folder` is now available in `post_export()` (But further work would be needed to make it available in `pre_export`, even though I don't think that's a use-case we would want to support)
