### ISSUE TITLE
[feature] Ask before system package installation

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#10605]
I think it is more user friendly when the user gets asked whether a conan recipe should install some system packages or not.
So the config here: `tools.system.package_manager:mode` https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html#conan-tools-system-package-manager-config
should be extended with the option: `"ask"`
In this mode, the user gets asked whether conan should install system packages, which he can interactively accept or decline.
Setting some global config somewhere is too complicated and might also sometime not the right value depending on the packages which are getting installed. The new mode should be also the default.

What do you think?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This was solved time ago with new modes for system_package_manager:mode. Closing as solved.
