### ISSUE TITLE
[question] SDK like dependency - is it a requirement or a tool requirement?

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#10603]
Hi,

I'm currently creating an application for QNX and the QNX SDP (Software Development Platform) is provided as Conan package. At present the QNX SDP is provided as tool requirement (previously known as build requirement) as it contains many tools that just run on the host platform and it supports different architectures (at least in theory). However, many of the binaries and libraries that are provided by the QNX SDP will also be added to the target.

This is what the Conan documentation says about tool requirements:

> tool_requires are designed for packaging tools, utilities that only run at build-time, but are not part of the final binary code. 
> Anything that is linked into consumer packages like all type of libraries (header only, static, shared) most likely are not tool_requires > but regular requires

From this point of view it is a requirement, but my personal feeling is that the classification of tool requirement is correct.
Anyway, I'm not 100% sure, so I would like to hear your opinion on that topic. I guess in general the question has nothing to do with QNX, it could be probably any SDK that is provided as Conan package.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gpxricky 

Yes, that is a point. I think you want to track ongoing work in https://github.com/conan-io/conan/pull/10347, and as we already have the PR and an original issue (https://github.com/conan-io/conan/issues/10317), I think we could close this one and follow up in those? Thanks!

**Comment by gpxricky** [comment]
Closing it as it is a duplicate.
