### ISSUE TITLE
[feature] Linter for recipes "Conan 2 like"

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10607]
- to be used in conan-center-index
- imports from "conan"
- "self.copy" => "copy(self)"
- ...

@conan-io/barbarians @uilianries @SSE4

**Comment by jgsogo** [comment]
list of generators -> "CMakeDeps", "CMakeToolchain",... meson and autotools ones

**Comment by memsharded** [comment]
First stage implemented in https://github.com/conan-io/conan/pull/10746

Lets wait until it is implemented in ConanCenter, and see how it starts to work, and then we will add more checks
