### ISSUE TITLE
[bug] Conan upload is broken

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#10615]
Conan skips the recipe upload when the config is in `semver_direct_mode` + a package was already uploaded with recipe revision mode enabled.

This is very hidden, so you only get the error later when trying to consume the package.
You get an error like this:
`ERROR: Missing binary: dbus/1.12.20:fb2ae32c85d50c7776ed05b57cc10f2bc374880b`

The problematic recipe is the `dbus` in my case: See how the `export` folder for revision `0` is missing.
Although the package is there, however, the recipe is missing.
![image](https://user-images.githubusercontent.com/42534866/154696437-75f6b582-e189-43da-8413-a40e205cd9d5.png)

I upload my package like the conan docu suggest:
```
conan upload dbus/1.12.20@:fb2ae32c85d50c7776ed05b57cc10f2bc374880b -r my-remote --confirm
```
This should upload the binary+recipe. https://docs.conan.io/en/latest/reference/commands/creator/upload.html 

However: It will only upload the package and not the recipe anymore.

Background:

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04 bionic
  * Compiler+version: gcc9
  * Conan version: 1.45.0
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
Upload a conan package with following settings:
```
default_package_id_mode=recipe_revision_mode
revisions_enabled=True
full_transitive_package_id=1
```

Afterwards, create from the same recipe, with no changes another package, but wit following conan conf settings:
```
default_package_id_mode = semver_direct_mode
```

Upload it with the package id, like:
```
conan upload dbus/1.12.20@:fb2ae32c85d50c7776ed05b57cc10f2bc374880b -r my-remote --confirm
```

Also an upload of just the recipe will be skipped.
```
$conan upload dbus/1.12.20@:fb2ae32c85d50c7776ed05b57cc10f2bc374880b -r my-remote --confirm
Uploading to remote 'my-remote':
Uploading dbus/1.12.20 to remote 'my-remote'
Compressing recipe...
Recipe is up to date, upload skipped
Uploading package 1/1: fb2ae32c85d50c7776ed05b57cc10f2bc374880b to 'my-remote'
Compressing package...
Uploading conan_package.tgz -> dbus/1.12.20:fb2a
Uploading conaninfo.txt -> dbus/1.12.20:fb2a
Uploading conanmanifest.txt -> dbus/1.12.20:fb2a

$conan upload dbus/1.12.20@ -r my-remote --confirm
Uploading to remote 'my-remote':
Uploading dbus/1.12.20 to remote 'my-remote'
Recipe is up to date, upload skipped
```

Do it better in from within own docker images, like I did.

**Comment by memsharded** [comment]
Quick question: When you say:

> Afterwards, create from the same recipe, with no changes another package, but wit following conan conf settings:

Is that full conan.conf? because if it is, you are missing the ``revisions_enabled=True``. You cannot change the ``revisions_enabled`` status on and off in the same cache, you need to use the same value, or if you change you need to start from a clean cache.

**Comment by derived-coder** [comment]
that is the full config for the mode where revision are not enabled. Lets call it config for conan 1.x
**Conan 1.x config:**
```
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = critical            # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
default_profile = default
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO
request_timeout = 60                  # environment CONAN_REQUEST_TIMEOUT (seconds)
default_package_id_mode = semver_direct_mode # environment CONAN_DEFAULT_PACKAGE_ID_MODE
config_install_interval = 1d

[storage]
path = ./data

[proxies]

[hooks]
attribute_checker
```


Here is the new config for conan 2.0 ready, with revisions enabled.
**Conan 2.0 config:**
```
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = critical            # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
default_profile = gcc-7.0-linux-x86_x64-release
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO
request_timeout = 60                  # environment CONAN_REQUEST_TIMEOUT (seconds)
default_package_id_mode = recipe_revision_mode
revisions_enabled = True
full_transitive_package_id = 1
config_install_interval = 2d

[storage]
path = ./data

[proxies]

[hooks]
attribute_checker
```

Remark: I do not have an environment, where I switch back and forth in the config. Everything is setup from scratch, all the time. Thanks to docker.

Background is the movement to conan 2.0.
So I have a CI job, which creates conan packages from the CCI with these two configs, in parallel. And of course for some reason the job with _conan-2.0_ config is one time faster than the job with the _conan 1.x_ config, then the upload of the recipe will not be done anymore. This is a major blocker for us.

**Comment by memsharded** [comment]
Just to double check, just in case:

> Remark: I do not have an environment, where I switch back and forth in the config. Everything is setup from scratch, all the time. Thanks to docker.

Those docker instances, use their own private cache, they do not share the cache via a mount or anything like that?

**Comment by derived-coder** [comment]
Yes, nothing is shared. Config will be freshly installed all the time. No preexisting local cache,etc.

**Comment by memsharded** [comment]
I have been having a look at this, and this are my findings:

- The revision system is not prepared in the client and server sides, to go back and forth between using revisions and not using revisions
- The upgrade from not-revisions to revisions is the expected path, but once a repository start getting revisions, it is not expected to return back to not using revisions.
- The behaviors between different servers might vary, but I have obtained different errors using different servers.

The solution would be:
- Don't upload packages without revisions once you have started to use revisions
- If you need to do that, don't do it to the same repo that you are uploading revisions to, but use another dedicated repository
- I'd probably try going the other way, when starting to create packages with revisions, upload those packages with revisions to a new repo, and the builds without revisions to the previous repo. Once things are looking good, do the swap.

**Comment by derived-coder** [comment]
Thanks for looking into this. Your solutions are workarounds, is there no fix possible? When yes, why?
I do not see there the problem is. Is it on both sides?

**Comment by derived-coder** [comment]
@memsharded 
Do you declare this as a bug to be fixed any time?

**Comment by memsharded** [comment]
> Do you declare this as a bug to be fixed any time?

No, I don't think so. The revisions system is not designed to keep continuously playing without revisions. If you use revisions, you should keep using revisions, but not mix both things in the same server repository. As commented above, the upgrade is intended to be in one direction from "without revision" to "with revisions". If you need to keep uploading both with and without, use different repositories.
