### ISSUE TITLE
Cannot build package because it is already locked in the input lockfile

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#10613]
Have a working project with consumer conanfile.txt:

```
[requires]
paho-mqtt-c/1.3.9
gtest/1.11.0
libbacktrace/cci.20210118
boost/1.73.0
openssl/1.1.1k
log4cplus/2.0.5
libssh2/1.9.0
xerces-c/3.2.3
libcurl/7.70.0
protobuf/3.12.4
libmicrohttpd/0.9.59
libarchive/3.5.2
bluez/5.62
ncurses/6.2
gcc_8.5.0_glibc_2.27_x86_64/0.0.1

[generators]
cmake
b2

[options]
boost:without_stacktrace=True
log4cplus:unicode=False
log4cplus:fPIC=True
log4cplus:shared=True
```

profile:
```
[settings]
arch=x86_64
os=Linux
build_type=Debug

compiler=gcc
compiler.version=8.5
compiler.glibc=2.27
compiler.libcxx=libstdc++11

[build_requires]
gcc_8.5.0_glibc_2.27_x86_64/0.0.1
```

Create a lock file with:
```
conan lock create conanfile.txt --profile:build my-profile --profile:host my-profile --remote my-remote --lockfile-out=my-lock-file
```
lockfile attached!
If I then delete my conan data dir and re-run conan install (now with lock file argument
[lockfile.txt](https://github.com/conan-io/conan/files/8096956/lockfile.txt)
) to re-create everything from scratch I get this:

```
ERROR: Cannot build 'bzip2/1.0.8#b056f852bd2d5af96fc7171aadfd6c0b' because it is already locked in the input lockfile
CMake Error at build-system/conan.cmake:638 (message):
  Conan install failed='1'
```

What could be wrong?

Rgds
Klaus

**Comment by klausholstjacobsen** [comment]
I have created a demo consumer project to re-create the problem.
First build the required toolchain packages from here:
https://github.com/klausholstjacobsen/conan-packages

Then build the demo consumer project from here:
https://github.com/klausholstjacobsen/demo-project

The demo project file ./build-system/build-system.cmake contains the line below which will make the system fail:
```
conan_cmake_install(
        PATH_OR_REFERENCE ${CMAKE_CURRENT_LIST_DIR}/platforms/conanfile.${DC_PLATFORM}
        #PROFILE_HOST ${CMAKE_CURRENT_LIST_DIR}/platforms/profile.${DC_PLATFORM}
        #PROFILE_BUILD ${CMAKE_CURRENT_LIST_DIR}/platforms/profile.amd64-gcc8
        LOCKFILE ${CMAKE_CURRENT_LIST_DIR}/platforms/lockfile.${DC_PLATFORM}
        BUILD missing UPDATE
)
```

If I remove the use of the lockfile and use the line below instead everything works.
```
conan_cmake_install(
        PATH_OR_REFERENCE ${CMAKE_CURRENT_LIST_DIR}/platforms/conanfile.${DC_PLATFORM}
        PROFILE_HOST ${CMAKE_CURRENT_LIST_DIR}/platforms/profile.${DC_PLATFORM}
        PROFILE_BUILD ${CMAKE_CURRENT_LIST_DIR}/platforms/profile.amd64-gcc8
        BUILD missing UPDATE
)
```
I hope the demo project can help you getting closer to helping me.

Rgds
Klaus

**Comment by klausholstjacobsen** [comment]
Hello

It's just me talking to myself again. :-)
My most recent discovery is that the lockfiles work if i have uploaded all binary packages and not only recipes to my remote.

Maybe that is the way lockfiles are supposed to work? Maybe lockfiles were never meant to work when having to build packages locally.

Can somebody knowledgeable confirm?

Rgds
Klaus

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Sorry this wasn't responded back then, sometimes the work load is too high and some tickets fall through the cracks.

This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!

**Comment by klausholstjacobsen** [comment]
Yes this is an old one. I don't even remember posting it :-)
