### ISSUE TITLE
[question] Access VirtualBuildEnv in test

### ISSUE THREAD

**Issue by babariviere** [conan-io/conan#10628]
Hello,

I am currently trying to package the android NDK.
In the tests, we are trying to test the env variable provided by android NDK to check that they are correctly set, and that the executables can be run.

Since there is a change on how the env variables are transmitted to packages (now via self.dependencies), we are trying to access them with the `VirtualBuildEnv`. But, it needs `self.dependencies` and it is inaccessible in tests.

Here is a small reproducible case:

[virtual-env.zip](https://github.com/conan-io/conan/files/8115432/virtual-env.zip)

Conan version:
```
$ conan --version
Conan version 1.45.0
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Note: Start using ``from conan import ConanFile`` when possible

Yes, in Conan 1.X, the ``test()`` method doesn't have access to the dependencies information. This is architectural, it wasn't possible to change it in 1.X. What you need to do (and in any case, it is the recommended way), is to handle the dependencies information in the ``generate()`` method. Do what you need to do there, and prepare the ground for the later ``build()`` and ``test()`` methods, that will use the files generated in the ``generate()`` method.

```python
    def generate(self):
        vc = VirtualBuildEnv(self)        # retrieve env from dependencies buildenv
        print(vc.environment().dumps())

    def test(self):
        pass
```

In Conan 2.0, this has been changed. The ``test()`` method has access to to the ``self.dependencies`` and your code works (you can try with the 2.0.0-alpha4. However, in the general case, it is still recommended to handle dependencies information in the ``generate()`` method as much as possible.

**Comment by babariviere** [comment]
> Note: Start using from conan import ConanFile when possible

It was generated with `conan new` 😄 

> Yes, in Conan 1.X, the test() method doesn't have access to the dependencies information. This is architectural, it wasn't possible to change it in 1.X. What you need to do (and in any case, it is the recommended way), is to handle the dependencies information in the generate() method. Do what you need to do there, and prepare the ground for the later build() and test() methods, that will use the files generated in the generate() method.

In this case, how can I access individual env variables in the test?
Like this:

```python
import os
from conan import ConanFile
from conan.tools.env.virtualbuildenv import VirtualBuildEnv


class HelloCcTestConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "VirtualBuildEnv"

    def build_requirements(self):
        self.tool_requires(self.tested_reference_str)

    def test(self):
        vc = VirtualBuildEnv(self)        # retrieve env from dependencies buildenv
        self.run("%s --version", vc.vars()["CC"])
```

Since we want to test if the binary works or no.
As you said, it works in 2.0, but we are trying to:
- migrate recipes to 2.0
- then backport them to 1.45 to make the migration minimal

But we should probably wait for 2.0 anyway 😄

**Comment by memsharded** [comment]
> It was generated with conan new

Try ``conan new hello/0.1 --template=cmake_lib`` :) 

> In this case, how can I access individual env variables in the test?
Like this:

First, try to avoid having 2 instances of ``VirtualBuildEnv``, you are using it as a ``generator`` (which file you are not using).
Then, have you considered using the generated file. Just by having ``generators = "VirtualBuildEnv"``, you will get a ``.bat`` or ``.sh`` script there in your folder. Your ``test()`` will load the file in ``self.run()`` by default, if it was able to find it (maybe that is the issue? Maybe the ``layout()`` could help here). So:

```python
def test(self):
      self.run("set") # this works in my Windows! It will display CC=hello
      self.run("'echo $CC' --version")  # whatever syntax in Linux to use the var
```
Could work (if you do the shell correctly, of course, that is just the idea)

Another alternative is to generate in the ``generate()`` method as many helper files as necessary to test things, you could get there the ``VirtualBuildEnv(self).vars()`` variables, and for each one generate a shell script. The ``test()`` method will just execute this shell scripts.

**Comment by babariviere** [comment]
@memsharded Will try that out, thanks!

**Comment by babariviere** [comment]
Well, your solution works! I should have thought of that... Thanks!
