### ISSUE TITLE
Architecture support in SystemPackageTool

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#1062]
Hi,

I've only tried this on Ubuntu so far: apt-get will use 64-bit libs by default when I do an `install()`. If I'm building a conan package with `-s arch=x86` it will not be able to use the 64-bit lib. apt-get will install the 32-bit version if I append the package name with `:i386`, so I suggest support this in SystemPackageTool directly:

```
installer = SystemPackageTool()
installer.install('package', settings=self.settings)
```

**Comment by lasote** [comment]
It's a good idea, people would have to execute first `sudo dpkg --add-architecture i386` to enable the x86 packages, but I think we can avoid doing that automatically and let the user do it if he want to do it.
For other architectures (I don't know the exact mapping and the availability) should be the same, so for a `armhf` you can append `:armhf`
It looks like for several package in a apt ubuntu repository you can find these different architectures:

`amd64 arm64 armhf i386 powerpc s390x`

To be honest, the matching of our ARM settings with those architectures is unknown for me... 

``[x86, x86_64, ppc64le, ppc64, armv6, armv7, armv7hf, armv8]``

**Comment by Croydon** [comment]
We do have the very same confusion about ARM architecture mappings over at Bincrafters

https://github.com/bincrafters/community/issues/704

//cc @izzyreal @uilianries

**Comment by uilianries** [comment]
I missed this issue, so I've opened https://github.com/conan-io/conan/issues/5026

If we just think about Ubuntu it's pretty easy, but it's not true when an user is running Arch Linux or Fedora, for example.

**Comment by Croydon** [comment]
I guess this is done via https://github.com/conan-io/conan/pull/5215

**Comment by memsharded** [comment]
There is a new system package tool integration in https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html, it implements the ``arch`` suffix support, please check it and report issues against it, thanks! (closing this)
