### ISSUE TITLE
[bug] PkgConfigDeps: component version not honored

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#10629]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Monterey
  * Compiler+version: apple-clang 13.0
  * Conan version: 1.45.0
  * Python version: 3.9.10

### Steps to reproduce (Include if Applicable)

- `conan install ffmpeg/4.4@ -g PkgConfigDeps`
- inspect pc files, all versions are set to 4.4 => not good
- `conan install ffmpeg/4.4@ -g pkg_config`
- inspect pc files, many versions are different because ffmpeg recipe set version of each component with a custom value => good

### Logs (Executed commands with output) (Include/Attach if Applicable)

For example here the content of `libavdevice.pc` (avdevice is a component of ffmpeg)

from `PkgConfigDeps` generator:

```
prefix=/Users/spaceim/.conan/data/ffmpeg/4.4/_/_/package/90fa4cf4928013c69bdbdd0bf4bac261ff5e5328
libdir1=${prefix}/lib
includedir1=${prefix}/include

Name: libavdevice
Description: Conan component: libavdevice
Version: 4.4
Libs: -L"${libdir1}" -lavdevice -framework CoreFoundation -framework Foundation -framework CoreGraphics -framework OpenGL -framework AppKit -framework AVFoundation -framework CoreAudio -F /Users/charpentiera/.conan/data/ffmpeg/4.4/_/_/package/90fa4cf4928013c69bdbdd0bf4bac261ff5e5328/Frameworks 
Cflags: -I"${includedir1}" 
Requires: libavutil libavfilter libswscale libavformat libavcodec libswresample libpostproc
```

from `pkg_config` generator:

```
prefix=/Users/spaceim/.conan/data/ffmpeg/4.4/_/_/package/90fa4cf4928013c69bdbdd0bf4bac261ff5e5328
libdir=${prefix}/lib
includedir=${prefix}/include

Name: ffmpeg-libavdevice
Description: Conan package: ffmpeg-libavdevice
Version: 58.13.100
Libs: -L"${libdir}" -lavdevice  -Wl,-rpath,"${libdir}" -framework CoreFoundation -framework Foundation -framework CoreGraphics -framework OpenGL -framework AppKit -framework AVFoundation -framework CoreAudio
Cflags: -I"${includedir}"
Requires: libavutil libavfilter libswscale libavformat libavcodec libswresample libpostproc
```

**Comment by franramirez688** [comment]
@SpaceIm I have opened this PR https://github.com/conan-io/conan/pull/10633 to be able to set that custom version for each component. Now, we don't have the field `cpp_info.version` anymore in Conan 2.0 so that's the reason to propose this new mechanism.
