### ISSUE TITLE
[question] Do conan profiles overwrite default settings

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#10623]
Hey guys.
I'm using a conan profile to perform a cross build to an embedded target. The embedded compiler is gcc 10
My cross building profile looks like this
```

[settings]
os=Arduino
os.board=ANY
arch=armv7
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Debug

[env]
PATH=[/home/.../Linux/gcc-10.2.1,/home/.../Linux/gcc-10.2.1/bin]
```

However when executing conan install

`Conan executing: /usr/local/bin/conan install . --build missing --profile /home/jenkins/agent/workspace/conan-arm-none-eabi-toolchain`
```

Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
 CC and CXX: /home/jenkins/agent/workspace/t3xx_2025/toolchains/Linux/gcc-10.2.1/bin/arm-none-eabi-gcc, /home/jenkins/agent/workspace/t3xx_2025/toolchains/Linux/gcc-10.2.1/bin/arm-none-eabi-g++ 
Found gcc 10.2
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
 'libstdc++' for backwards compatibility.

Your compiler is likely using the new CXX11 ABI by default (libstdc++11).
If you want Conan to use the new ABI for the default profile, run:
  $ conan profile update settings.compiler.libcxx=libstdc++11 default
 Or edit '/root/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************


Default settings
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++
build_type=Release

 *** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


```

=>so my question: My profile explicitly sets compiler.libcxx=libstdc++11. Why is still the value from the default setting used?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
That is the default detected profile.

The important profile is the one that is listed later, in the ``install`` or ``create`` output, you will see your current profile. That one is only the result of the "default" auto-detected profile, but if you pass the ``--profile=myprofile`` arg, you will see yours. Please paste the entire output beyond that autodetection.

It might be also possible to completely skip auto-detection or do it separately:
- call ``conan profile new --detect`` first, before your other commands, to separate clearly that autodetection
- try to use ``--profile:build=myprofilebuild --profile:host=myprofilehost`` to fully define your build and host profiles (recommended for cross-compiling), if the default profile is not included, that might skip the default profile autodetection

**Comment by ghost** [comment]
@memsharded thank you after explicitly creating n build profile with `conan profile new --detect` and then using
```
conan_cmake_install(
      PATH_OR_REFERENCE
      .
      BUILD
      missing
      PROFILE_BUILD
      ${BUILD_PROFILE_NAME}
      PROFILE_HOST
      ${CONAN_PROFILE_PATH}
    )
```

it worked after a while.

What took me some time was that [env] values are not passed to a custom cmake toolchain file. This means specifying the cross compiler via CC and CXX in the [env] section did not work for me.
After adding the cross compiler path in the environment of the CMakePresets.json I was able to fix this.

=>I'm not sure if this is a bug, I'll create a new issue with a small sample project.

Thx for your fast help :)
