### ISSUE TITLE
[bug] ERROR: HTTPSConnectionPool when accessing center.conan.io remote

### ISSUE THREAD

**Issue by forry** [conan-io/conan#10620]
Hi, don't know if this is the right place to report but it seems the conan client is unable to connect to center.io . First it failed during the conan install, but I use the search command as the example here. According to the https://status.conan.io/ everything is operational. Our other remote hosted on our server is running fine. I have no proxy or svn just a normal home connection, but it doesn't work for my colleagues too.

Thanks
forry

### Environment Details (include every applicable attribute)
  * Conan version: 1.45
  * Python version: Python 3.7.4

### Steps to reproduce (Include if Applicable)
conan search boost -r=conan

### Logs (Executed commands with output) (Include/Attach if Applicable)
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ResponseError('too many 502 error responses')). [Remote: conan]

**Comment by ilyamt-tandemg** [comment]
I report having the same issue across several countries.
Conan version: 1.44.0

**Comment by forry** [comment]
Ok, it seems that after I filed the issue it is now working again. But still, I leave it here since this means that there might be something not ok with the remote.

**Comment by memsharded** [comment]
It seems it could be a temporary glitch in the CDN infra. 
Now things seem normal on our end, please report if you see these failures again.

**Comment by memsharded** [comment]
Seems things are ok now, closing
