### ISSUE TITLE
[question] Link errors for indirect dependencies

### ISSUE THREAD

**Issue by anderson-dev** [conan-io/conan#10636]
I'm using visual_studio generator and msbuild-based sln/vcxproj projects. Due to VS conan extension, I have to have my conanbuildinfo.props file in x64/Debug/.conan and I've ensured that it is being exported to source.

Project A is a static library that has tool_requires for catch2 since I want to run the unit tests (in Tests subdir). I export both the project src as well as the tests folder then run conan build to build both the project as well as the tests then I execute the compiled tests.exe console app. However, I do not package the tests.exe console app as part of the prebuilt binary.

Project B is a console app that imports Project A.

If I build and export Project A in local cache then build Project B everything works as expected. Though, when I build Project B with no pre-built binary available (only the recipe) for Project A, when using `--build missing`, an on-the-fly build takes place. During building and linking of Catch2WithMain.lib with the Project A Tests, a linker error occurs and conan install fails because it can't find the Catch2WithMain.lib file. I also notice that no other libs or libpaths are passed to the link.exe linker.

Is there something I'm missing in regards to ensuring that libpaths/libs are able to be accessed during a `--build missing` scenario?

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> Project A is a static library that has tool_requires for catch2 since I want to run the unit tests (in Tests subdir). I export both the project src as well as the tests folder then run conan build to build both the project as well as the tests then I execute the compiled tests.exe console app. However, I do not package the tests.exe console app as part of the prebuilt binary.

I suggest to use ``test_requires`` for catch2, as it is different from a ``tool_requires`` (cmake, toolchains, etc)

> If I build and export Project A in local cache then build Project B everything works as expected. Though, when I build Project B with no pre-built binary available (only the recipe) for Project A, when using --build missing, an on-the-fly build takes place. During building and linking of Catch2WithMain.lib with the Project A Tests, a linker error occurs and conan install fails because it can't find the Catch2WithMain.lib file. I also notice that no other libs or libpaths are passed to the link.exe linker.

I think this can be an effect of the extension that is able to pull dynamically the .props with the properties. The extension only works as a consumer, and from the IDE, but it will not work for creating packages. The .props need to be actually added to the .vcproj files in order to create a package from it.


Also, I would like to advocate for the more modern and powerful ``MSBuildDeps`` generator (and ``MSBuildToolchan``), if I haven't yet, please have a look at those, they are the futures ones for Conan 2.0, and are already available in Conan 1.X

**Comment by anderson-dev** [comment]
Thanks for your suggestions.
I've avoided those generators specifically because they are marked with "experimental" warnings. As I'm depending on conan for implementation of a CI system for my group I'm trying to stay with stable, official api. Also, my coworkers are not great with command-line so they are partial toward using the VS extension. However, it looks like I'm going to have to transition them to command-line by writing them some make scripts to avoid argument typos and mistakes as VS extension seems completely incompatible with how conan works currently. See below:

 Based on the interrupted build folder in the local cache, it looks like it generates a new conanbuildinfo.props in the root. However, the msbuild projects import the conanbuildinfo.props in the x64/$(config)/.conan folders where vs conan extension expects them. When I package, I always use `conan install . -if x64/$(config)/.conan`

Things work fine during CI build of the project itself when I run `conan install . -if x64/$(config)/.conan` . Pulling pre-built binaries work fine as well but I'd prefer to have the debug versions build on demand. But apparently there is no way to honor that install folder during an on-the-fly build as a dependency of another project when having the install folder in `x64/$(config)/.conan`

**Comment by anderson-dev** [comment]
I've decided to try and transition our packages to using `MSBuildToolchain` in order to avoid this on-demand build install folder mismatch issue. So far, when specifying `MSBuildToolchain` as the generator, it creates the conantoolchain.props and requisite conantoolchain_$(config)_$(arch).props file. However, I would expect to see libpaths etc to my dependencies but it appears to be blank:

conanfile.py:
```
from conans import ConanFile, MSBuild, tools

class ConanPackageInfo(ConanFile):
    name = "message-queue-manager"
    url = 'https://gitea.xenonet.com/edot/message-queue-manager.git'
    description = "Manages/persists local address book records for subsequent recall"
    license = "Xenotran"
    settings = "os", "compiler", "build_type", "arch"
    generators = "MSBuildToolchain"
    exports_sources = "MessageQueueManager/*", "Tests/*", "MessageQueueManager.sln"
    default_options = {"catch2:with_main": True, "boost:shared": True}
    default_user = "xenotran"
    default_channel = "stable"

    def build_requirements(self):
        self.test_requires("catch2/[>2.0.0 <3.0.0]")

    # Required Packages (https://conan.io/center/)
    def requirements(self):
        self.requires("boost/1.77.0")

    def imports(self):
        self.copy("*.dll", dst="bin", src="bin") # From bin to bin
        self.copy("*.dylib*", dst="bin", src="lib") # From lib to bin

    def build(self):
        msbuild = MSBuild(self)
        msbuild.build("MessageQueueManager.sln", upgrade_project=False, use_env=False, verbosity="normal")
        
    def package(self):
        self.copy("*.h", dst="include", src="MessageQueueManager/include")
        self.copy("*.lib", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

conantoolchain.props:
```
<?xml version="1.0" ?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ImportGroup Label="PropertySheets">
		<Import Condition="'$(Configuration)' == 'Debug' And '$(Platform)' == 'x64'" Project="conantoolchain_debug_x64.props"/>
	</ImportGroup>
	<PropertyGroup Label="ConanPackageInfo">
		<ConanPackageName>message-queue-manager</ConanPackageName>
		<ConanPackageVersion/>
	</PropertyGroup>
</Project>
```

conantoolchain_debug_x64.props:
```
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>
         ;%(PreprocessorDefinitions)
      </PreprocessorDefinitions>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <LanguageStandard></LanguageStandard>
      <MultiProcessorCompilation>True</MultiProcessorCompilation>
      <ProcessorNumber>8</ProcessorNumber>
    </ClCompile>
    <ResourceCompile>
      <PreprocessorDefinitions>
         ;%(PreprocessorDefinitions)
      </PreprocessorDefinitions>
    </ResourceCompile>
  </ItemDefinitionGroup>
  <PropertyGroup Label="Configuration">
    <PlatformToolset>v142</PlatformToolset>
  </PropertyGroup>
</Project>
```

**Comment by anderson-dev** [comment]
`MSBuildDeps` seems to be work, but I like the less cluttered `MSBuildToolchain`. Any idea why it doesn't work as expected?

**Comment by memsharded** [comment]
``MSBuildToolchain`` purpose is just to map the current package settings to MSBuild. It is very unrelated to dependencies.
``MSBuildDeps`` is the one in charge of managing dependencies information.

They have different purposes and goals, very orthogonal. They are separated to allow the necessary flexibility that many users neeed.

**Comment by anderson-dev** [comment]
I'm still getting a link error with Catch2WithMain.lib after converting to `MSBuildDeps`

1. Changed generator to "MSBuildDeps" in `conanfile.py` for `Project A`
1. `conan install .`
13. Added `conandeps.props` to all projects and their configurations in sln
1. `conan build .`
1. built successfully
1. unit tests ran successfully
1. `conan export-pkg . $(PACKAGE_NAME)/$(PACKAGE_VERSION)@${PACKAGE_USER)/${PACKAGE_CHANNEL}`
1. exported package successfully
1. changed `Project B` dependency to the previously exported `Project A` package
1. `conan install . --build missing -s build_type=Debug`
1.  link error looking for "Catch2WithMain.lib"
1. verified that the interrupted build folder for `Project A` in cache did re-generate all props files for boost and catch2 dependencies

It may be expected, but I noticed that the `conan_imports_manifest.txt` contains boost deps but nothing for catch2

Link statement when building `Project A` prior to packaging:
```
Link:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\T
         ools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OU 
         T:"C:\Users\aflorence\source\repos\xeno\edot\message-queue-manager\x6 
         4\Release\Tests.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:C:/Users/aflore 
         nce/.conan/data/catch2/2.13.8/_/_/package/ccb9844807d54b8a8b61fa615c7 
         e8b50a6f0638f/lib /LIBPATH:C:/.conan/d588d39/1/lib /LIBPATH:C:/Users/ 
         aflorence/.conan/data/bzip2/1.0.8/_/_/package/d16a91eadaaf5829b928b12 
         d2f836ff7680d3df5/lib /LIBPATH:C:/Users/aflorence/.conan/data/zlib/1. 
         2.11/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/lib kernel3 
         2.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib she 
         ll32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib Catc 
         h2WithMain.lib ole32.lib dbgeng.lib bcrypt.lib boost_log_setup.lib bo 
         ost_log.lib boost_locale.lib boost_iostreams.lib boost_graph.lib boos 
         t_fiber_numa.lib boost_fiber.lib boost_coroutine.lib boost_contract.l 
         ib boost_wave.lib boost_unit_test_framework.lib boost_type_erasure.li 
         b boost_timer.lib boost_thread.lib boost_random.lib boost_prg_exec_mo 
         nitor.lib boost_nowide.lib boost_json.lib boost_filesystem.lib boost_ 
         chrono.lib boost_wserialization.lib libboost_test_exec_monitor.lib bo 
         ost_stacktrace_windbg_cached.lib boost_stacktrace_windbg.lib boost_st 
         acktrace_noop.lib boost_serialization.lib boost_regex.lib boost_progr 
         am_options.lib boost_math_tr1l.lib boost_math_tr1f.lib boost_math_tr1 
         .lib boost_math_c99l.lib boost_math_c99f.lib boost_math_c99.lib libbo 
         ost_exception.lib boost_date_time.lib boost_context.lib boost_contain 
         er.lib boost_atomic.lib bz2.lib zlib.lib /MANIFEST /MANIFESTUAC:"leve 
         l='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Users 
         \aflorence\source\repos\xeno\edot\message-queue-manager\x64\Release\T 
         ests.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /LTC 
         GOUT:"x64\Release\Tests.iobj" /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB 
         :"C:\Users\aflorence\source\repos\xeno\edot\message-queue-manager\x64 
         \Release\Tests.lib" /MACHINE:X64     x64\Release\MessageQueueManagerT 
         ests.obj
         x64\Release\ChapMessageTests.obj
         "C:\Users\aflorence\source\repos\xeno\edot\message-queue-manager\x64\ 
         Release\EDOTMQM.lib"
```

No libpaths appear to be passed to link.exe when `Project B` imports and attempts to build `Project A`:
```
Link:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\T
         ools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OU 
         T:"C:\Users\aflorence\.conan\data\message-queue-manager\1.5.0-conan-m 
         sbuild-2-0-transition.4\xenotran\stable\build\41d2b4518a7ef64d687103a 
         4c56e63e89d48342e\x64\Debug\Tests.exe" /INCREMENTAL /ILK:"x64\Debug\T 
         ests.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comd 
         lg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odb 
         c32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAcce 
         ss='false'" /manifest:embed /DEBUG /PDB:"C:\Users\aflorence\.conan\da 
         ta\message-queue-manager\1.5.0-conan-msbuild-2-0-transition.4\xenotra 
         n\stable\build\41d2b4518a7ef64d687103a4c56e63e89d48342e\x64\Debug\Tes 
         ts.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C 
         :\Users\aflorence\.conan\data\message-queue-manager\1.5.0-conan-msbui 
         ld-2-0-transition.4\xenotran\stable\build\41d2b4518a7ef64d687103a4c56 
         e63e89d48342e\x64\Debug\Tests.lib" /MACHINE:X64 x64\Debug\MessageQueu 
         eManagerTests.obj
         x64\Debug\ChapMessageTests.obj
         "C:\Users\aflorence\.conan\data\message-queue-manager\1.5.0-conan-msb 
         uild-2-0-transition.4\xenotran\stable\build\41d2b4518a7ef64d687103a4c 
         56e63e89d48342e\x64\Debug\EDOTMQM.lib"
     4>LINK : fatal error LNK1104: cannot open file 'Catch2WithMain.lib' [C:\U
       sers\aflorence\.conan\data\message-queue-manager\1.5.0-conan-msbuild-2- 
       0-transition.4\xenotran\stable\build\41d2b4518a7ef64d687103a4c56e63e89d 
       48342e\Tests\Tests.vcxproj]
```

**Comment by memsharded** [comment]
A couple of quick questions/hints:

- When using the new tools, please use the ``from conan.tools.microsoft import MSBuild``, not the legacy one. All the new integrations are always imported ``from conan.tools.xxxx`` (note the singular). Also possible to do ``from conan import ConanFile``.
- Why ``conan install . --build missing -s build_type=Debug`` is actually building something? You only exported the ``Release`` version in the previous ``conan export-pkg``? If that is the case, does it work if you do ``conan install . --build=<yourpkg> --build_type=Release``? 
- ProjectB is mostly irrelevant likely? Can you reproduce with ``conan install projectA/version@ --build=projectA``?

**Comment by anderson-dev** [comment]
> * When using the new tools, please use the `from conan.tools.microsoft import MSBuild`, not the legacy one. All the new integrations are always imported `from conan.tools.xxxx` (note the singular). Also possible to do `from conan import ConanFile`.

converting `from conans import ConanFile, MSBuild, tools` to `from conan import ConanFile, tools` and `from conan.tools.microsoft import MSBuild` resulted in complaints about my passed "upgrade_project", "use_env", and "verbosity" args. After removing those settings, I received error: `'msbuild' is not recognized as an internal or external command,
operable program or batch file`. Reverted to original namespace statement to be able to perform your subsequent requests:

> * Why `conan install . --build missing -s build_type=Debug` is actually building something? You only exported the `Release` version in the previous `conan export-pkg`? If that is the case, does it work if you do `conan install . --build=<yourpkg> --build_type=Release`?

I'm publishing pre-built binaries for only Release builds and intend for Debug builds to be built on-the-fly saving space and so our devs can debug using the pdb files successfully. Same link error.

> * ProjectB is mostly irrelevant likely? Can you reproduce with `conan install projectA/version@ --build=projectA`?

Yes. Same link error

**Comment by anderson-dev** [comment]
Is it necessary to specify every requires library in package_info()? or only those I build myself?

That is the only possibility that I can think of to explain why `conan build` works fine but I can't build from a published recipe.

**Comment by memsharded** [comment]
> Is it necessary to specify every requires library in package_info()? or only those I build myself?

The ``package_info()`` of the projectA package is irrelevant here, as it is information to the consumers, and it is failing to build the package itself.

I haven't asked before, but I would guess that a regular ``conan create .`` for projectA also fails with the same link error, it should, as it would be equivalent to a ``conan export`` + ``conan install projectA/version@ --build=projectA``

**Comment by anderson-dev** [comment]
okay I got that project building; I was trying to be fancy by injecting the reference to `conandeps.props` using a `Directory.Build.props`. I confirmed it built successfully when exporting it to source but ultimately decided to manually add props file to each project and not have to export that file. So now calling `conan install` on Project B, Project A recipe is referenced, built on-the-fly according to build policy, and linked properly.

**Comment by anderson-dev** [comment]
However, after showing that all this now works to my devs, they complained about having all the generated files cluttering up the root directory of the repo rather than tucked into the sln output folder like before `x64/Debug/.conan`, back when I was following the Conan VS extension default install folder expectations.

It seems like we're back to the same scenario:
1. Generate `conandeps.props` et al for Project A via `conan install . -if x64/Debug/.conan -s build_type=Debug` and `conan install . -if x64/Release/.conan`
2. Add `conandeps.props` to Project A for msbuild import for Debug/Release configurations pointing to their respective output folders `x64/Release/.conan` and `x64/Debug/.conan`
3. `conan build . -if x64/Release/.conan`
4. `conan export-pkg . ProjectA/$(PROJECT_VERSION)@$(PACKAGE_USER)/$(PACKAGE_CHANNEL) -if x64/Release/.conan`
5. Project B runs `conan install . -if x64/Debug/.conan --build missing -s build_type=Debug`; Project A's recipe will be used to build on-the-fly but the generated props files will be created at the root of Project A's build folder
6. Because Project A is expecting to import its `conandeps.props` and related files from the `x64/Debug/.conan` folder, the generated props files at the root, while correct, would not be used during compilation causing the link errors we've seen.

So, what use is specifying `--install-folder` if it doesn't use that setting for all dependencies built as a result Project B's invocation? Are msbuild-based Conan projects expected to generate all of its conan deps in the root in order for `--build missing` to work properly?

**Comment by memsharded** [comment]
Hi @anderson-dev 

I would recommend to have a look to the ``layout()`` functionality. There is already a ``vs_layout()`` experimental helper (see https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html, but it is not documented yet) that could help with MSBuild projects. It allows to define a cleaner local layout by defining for example the ``self.folders.generators`` location in the ``layout()`` recipe method directly.

**Comment by anderson-dev** [comment]
Though cautious, I'm open to embrace some of these tools/helpers as suggested even though marked as "experimental" but I'm unable to even build if I switch to the required namespace.

If I use the `conan.tools.microsoft` namespace as previously suggested for the MSBuild helper, I can no longer build: `'msbuild' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by memsharded** [comment]
> If I use the conan.tools.microsoft namespace as previously suggested for the MSBuild helper, I can no longer build: 'msbuild' is not recognized as an internal or external command, operable program or batch file.

The ``msbuild`` helper works under a VS prompt. That prompt is activated with a ``vcvars.bat`` command, and Conan should generate it with the ``MSBuildToolchain`` (look for it in the generators folder). Combined with ``VirtualBuildEnv``, its injection should be pretty automatic. Do you have some recipe or project that we could have a look?

**Comment by anderson-dev** [comment]
hmm previously `from conans import ConanFile, MSBuild, tools` activated vcvars and worked fine

```
from conans import ConanFile, MSBuild, tools

class ConanPackageInfo(ConanFile):
    name = "message-queue-manager"
    url = 'https://gitea.xenonet.com/edot/message-queue-manager.git'
    description = "Manages/persists local address book records for subsequent recall"
    license = "Xenotran"
    settings = "os", "compiler", "build_type", "arch"
    generators = "MSBuildToolchain"
    exports_sources = "MessageQueueManager/*", "Tests/*", "MessageQueueManager.sln"
    default_options = {"catch2:with_main": True, "boost:shared": True}
    default_user = "xenotran"
    default_channel = "stable"

    def build_requirements(self):
        self.test_requires("catch2/[>2.0.0 <3.0.0]")

    # Required Packages (https://conan.io/center/)
    def requirements(self):
        self.requires("boost/1.77.0")

    def imports(self):
        self.copy("*.dll", dst="bin", src="bin") # From bin to bin
        self.copy("*.dylib*", dst="bin", src="lib") # From lib to bin

    def build(self):
        msbuild = MSBuild(self)
        msbuild.build("MessageQueueManager.sln", upgrade_project=False, use_env=False, verbosity="normal")
        
    def package(self):
        self.copy("*.h", dst="include", src="MessageQueueManager/include")
        self.copy("*.lib", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

**Comment by memsharded** [comment]
> from conans import ConanFile, MSBuild

The legacy ``MSbuild`` helper is doing things differently. 
The new ``from conan.tools.microsoft import MSBuild`` will use the created (created by the MSBuildToolchain)  .bat files to activate the VS prompt to locate msbuild.

In general, the legacy helpers ``from conans import xxx`` shouldn't be used together with the new integrations like ``MSBuildToolchain`` or ``MSBuildDeps``

**Comment by anderson-dev** [comment]
so is this correct for a minimal MSBuild package recipe that compiles/packages using the new tools?:

```
from conan import ConanFile, tools
from conan.tools.microsoft import MSBuild

class ConanPackageInfo(ConanFile):
    name = "my-app"
    url = 'webhost.com/my-package.git'
    description = "some description"
    license = "some license"
    settings = "os", "compiler", "build_type", "arch"
    generators = "MSBuildToolchain", "MSBuildDeps"

def build_requirements(self):
        self.test_requires("catch2/[~2]")

    # Required Packages (https://conan.io/center/)
    def requirements(self):
        self.requires("boost/1.77.0")

    def imports(self):
        self.copy("*.dll", dst="..", src="bin") # From bin to outdir

    def build(self):
        msbuild = MSBuild(self)
        msbuild.build("MyApp.sln")

    def package(self):
        self.copy("*.h", dst="include", src="MyApp/include")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.pdb", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

**Comment by anderson-dev** [comment]
I've added vs_layout and think the [defaults ](https://github.com/conan-io/conan/blob/develop/conan/tools/microsoft/layout.py)seem to make sense

However, MSBuild could no longer find my sln until I added `self.folders.build = "."` in the layout method. Now it seems the paths in conandeps.props are not aware of the new layout:
```
C:\Users\aflorence\source\repos\xeno\edot\message-queue-manager\conandeps.props(4,3 
): error MSB4019: The imported project "C:\Users\aflorence\source\repos\xeno\edot\m 
essage-queue-manager\conan_boost.props" was not found. Confirm that the expression  
in the Import declaration "conan_boost.props" is correct, and that the file exists  
on disk.
```

```
from conan import ConanFile, tools
from conan.tools.microsoft import MSBuild
from conan.tools.layout import vs_layout


class ConanPackageInfo(ConanFile):
    name = "message-queue-manager"
    url = 'https://gitea.xenonet.com/edot/message-queue-manager.git'
    description = "Manages/persists local address book records for subsequent recall"
    license = "Xenotran"
    settings = "os", "compiler", "build_type", "arch"
    generators = "MSBuildToolchain", "MSBuildDeps"
    exports_sources = "MessageQueueManager/*", "Tests/*", "MessageQueueManager.sln"
    default_options = {"catch2:with_main": True, "boost:shared": True}
    default_user = "xenotran"
    default_channel = "stable"

    def layout(self):
        vs_layout(self)
        self.folders.build = "."

    def build_requirements(self):
        self.test_requires("catch2/[>2.0.0 <3.0.0]")

    # Required Packages (https://conan.io/center/)
    def requirements(self):
        self.requires("boost/1.77.0")

    def imports(self):
        self.copy("*.dll", dst="bin", src="bin") # From bin to bin
        self.copy("*.dylib*", dst="bin", src="lib") # From lib to bin

    def build(self):
        msbuild = MSBuild(self)
        msbuild.build("MessageQueueManager.sln")
        
    def package(self):
        self.copy("*.h", dst="include", src="MessageQueueManager/include")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.pdb", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

**Comment by anderson-dev** [comment]
projects were still using the previous conandeps.props at root, changed the projects to import the one generated in the `$(OutDir)/generators` folder.

Now an error in package:
`conans.tools` supports collect_libs but `conan.tools` does not? What's the recommended alternative?

**Comment by anderson-dev** [comment]
Last question to put this issue to bed: Can I still use `conan.tools.collect_libs` or is it discouraged?

**Comment by anderson-dev** [comment]
reverting to `conans.tools.collect_libs` until it is ported to the new integrations
