### ISSUE TITLE
[bug] VS2022 fails with "conan_split_version Macro invoked with incorrect arguments"

### ISSUE THREAD

**Issue by helmesjo** [conan-io/conan#10630]
### Environment Details (include every applicable attribute)
  * Package Name/Version: **bzip2/1.0.8**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2022 (17.1.0)**
  * Python version: **3.9.7**
  * CMake version: **3.21.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MTd
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CC=cl.exe
CXX=C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe
```

### Steps to reproduce (Include if Applicable)
Build it using above settings. In my case it was detected when building `bzip2/1.0.8`, but doesn't seem to necessarily be related to the packaged itself.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
bzip2/1.0.8: Configuring sources in C:\Users\username\.conan\data\bzip2\1.0.8\_\_\source

bzip2/1.0.8: Copying sources to build folder
bzip2/1.0.8: Building your package in C:\Users\username\.conan\data\bzip2\1.0.8\_\_\build\b71e99789552e8241cf7105925713e6e50251117
bzip2/1.0.8: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.8: Aggregating env generators
bzip2/1.0.8: Calling build()
-- Selecting Windows SDK version 8.1 to target Windows .
-- The C compiler identification is MSVC 19.31.31104.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting language standard
CMake Error at conanbuildinfo.cmake:438 (conan_split_version):
  conan_split_version Macro invoked with incorrect arguments for macro named:
  conan_split_version
Call Stack (most recent call first):
  conanbuildinfo.cmake:591 (check_compiler_version)
  conanbuildinfo.cmake:141 (conan_check_compiler)
  CMakeLists.txt:7 (conan_basic_setup)
-- Configuring incomplete, errors occurred!
See also "C:/Users/username/.conan/data/bzip2/1.0.8/_/_/build/b71e99789552e8241cf7105925713e6e50251117/CMakeFiles/CMakeOutput.log".
bzip2/1.0.8: bzip2/1.0.8: ERROR: Package 'b71e99789552e8241cf7105925713e6e50251117' build failed

bzip2/1.0.8: WARN: Build folder C:\Users\username\.conan\data\bzip2\1.0.8\_\_\build\b71e99789552e8241cf7105925713e6e50251117
ERROR: bzip2/1.0.8: Error in build() method, line 67
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 61
	self._cmake.configure()
	ConanException: Error 1 while executing cd C:\Users\username\.conan\data\bzip2\1.0.8\_\_\build\b71e99789552e8241cf7105925713e6e50251117 && cmake -G "Visual Studio 17 2022" -A "x64" -DCONAN_LINK_RUNTIME="/MTd" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="17" -DCONAN_CXX_FLAGS="/MP20" -DCONAN_C_FLAGS="/MP20" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\username\.conan\data\bzip2\1.0.8\_\_\package\b71e99789552e8241cf7105925713e6e50251117" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DBZ2_VERSION_STRING="1.0.8" -DBZ2_VERSION_MAJOR="1" -DBZ2_BUILD_EXE="True" -Wno-dev C:\Users\username\.conan\data\bzip2\1.0.8\_\_\build\b71e99789552e8241cf7105925713e6e50251117
CMake Error at cmake/conan-environment.cmake:182 (message):
  Conan: 'conan install <args>' failed: 1

Call Stack (most recent call first):
  cmake/conan-environment.cmake:73 (conan_generate_config)
  CMakeLists.txt:43 (conan_initialize)
-- Configuring incomplete, errors occurred!
```

</details>

**Comment by memsharded** [comment]
I am trying to reproduce this, but at the moment I am stuck at a different error:
```
 The build tools for Visual Studio 2019 (Platform Toolset = 'v142') cannot be found.
```
Not sure why this is happening (I just installed VS 2022, which seems to work fine).
UPDATE: I was using cmake 3.21.0, it seems this was fixed in 3.21.3

Just to make sure, which Conan version are you using?

**Comment by memsharded** [comment]
I couldn't reproduce this. I have just tried it, with latest Conan 1.45, putting your above profile and:

```bash
$ conan install bzip2/1.0.8@ --build --profile=vs2022
```
The package builds and packages correctly:

```
bzip2/1.0.8: Calling build()
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.31.31104.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting language standard
-- This project seems to be plain C, using 'MSVC' compiler
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
....
```

I don't know if it could be some difference on how the Enterprise version is being reported and making it fail, but I cannot try that here, don't have the enterprise version.

**Comment by helmesjo** [comment]
@memsharded I'm on 1.45 (tried 1.44 before that as well).

**Comment by helmesjo** [comment]
@memsharded Yeah I do use enterprise (sort of very vaguely stated I realized), and I'm leaning towards that being the culprit. I'll try Community and see.

Either way, in `macro(conan_split_version VERSION_STRING MAJOR MINOR)` you expect a string, so all invocations of this macro should quote the argument (which it currently doesn't).

**Comment by helmesjo** [comment]
Output from VS2022 Enterprise is fine though: `${CMAKE_CXX_COMPILER_VERSION} == 19.31.31105.0`

**Comment by helmesjo** [comment]
Manually including `conanbuildinfo.cmake` and invoking the function triggers no error.

```cmake
include("C:/Users/MyUser/.conan/data/bzip2/1.0.8/_/_/build/b71e99789552e8241cf7105925713e6e50251117/conanbuildinfo.cmake")

conan_split_version(${CMAKE_CXX_COMPILER_VERSION} VERSION_MAJOR VERSION_MINOR)
```

**Comment by helmesjo** [comment]
Alright, found the problem. I have a `toolchain.cmake` file that sets things up for (in this case) "Windows + x86_64 + MSVC". The culprit was `set(CMAKE_CXX_COMPILER_ID "MSVC")`, this makes bzip for some unknown reason fail with the above mentioned error. The interesting thing is that if I don't set it in my toolchain file, it still gets the exact same value assigned to it. So something in this chain of invocations doesn't like that it's set in the toolchain (maybe it's stored as a special "global" value or something, no clue).

Should also mention that I invoke `conan install` from within my cmake scripts using the following:

```
    execute_process(
        COMMAND
        # Install dependencies.
        conan install "${arg_CONAN_FILE}"
            --settings=compiler=${CONAN_COMPILER}
            --settings=compiler.verison=${CONAN_COMPILER_VERSION}
            --settings=arch=${CONAN_ARCH}
            --settings=arch_build=${CONAN_HOST_ARCH}
            --settings=build_type=${CONAN_BUILD_TYPE}
            --settings=os_build=${CONAN_OS}
            --settings=os=${CONAN_OS}
            --install-folder=${arg_DEPENDENCIES_PATH}
            ${CONAN_BUILD}
            ${CONAN_LIBSTD}
            ${CONAN_COMPILER_CC}
            ${CONAN_COMPILER_CXX}
            ${CONAN_COMPILER_RUNTIME}
        RESULT_VARIABLE EXIT_CODE
    )
```

Ignore the details above, other than it working for previous versions of VS.

**Comment by helmesjo** [comment]
Opening `"C:/Users/MyUser/.conan/data/bzip2/1.0.8/_/_/build/b71e99789552e8241cf7105925713e6e50251117/` in a terminal and running `cmake --build .` with `set(CMAKE_CXX_COMPILER_ID "MSVC")` in the `CMakeLists.txt` file triggers the error.

Problem is that if `CMAKE_CXX_COMPILER_ID` is defined, then `CMAKE_CXX_COMPILER_VERSION` is assumed to be defined (which it isn't in this case since CMake detects this as a "C project" and only sets `CMAKE_C_COMPILER_VERSION`.

The erroneous code (making too many assumptions) in the generated `conanbuildinfo.cmake` is this:
```
    if(NOT DEFINED CMAKE_CXX_COMPILER_ID)
        if(DEFINED CMAKE_C_COMPILER_ID)
            conan_message(STATUS "This project seems to be plain C, using '${CMAKE_C_COMPILER_ID}' compiler")
            set(CMAKE_CXX_COMPILER_ID ${CMAKE_C_COMPILER_ID})
            #set(CMAKE_CXX_COMPILER_VERSION ${CMAKE_C_COMPILER_VERSION})
        else()
            message(FATAL_ERROR "This project seems to be plain C, but no compiler defined")
        endif()
    endif()
```

For now I guess I'll define `CONAN_DISABLE_CHECK_COMPILER` to skip this dancing part.

**Comment by helmesjo** [comment]
@memsharded Any progress on this? Was a while since I looked at it, but from _past me_ above it looks like the issue was found in the conan generated script.

**Comment by memsharded** [comment]
Hi @helmesjo 

The truth is that we are no longer prioritizing things related to ``cmake`` generator and ``conanbuildinfo.cmake``, but working on ``CMakeDeps`` and ``CMakeToolchain`` integrations to be 2.0 ready. (conan 2.0 beta is expected very soon).

As ``CONAN_DISABLE_CHECK_COMPILER`` seems enough to avoid this, it is probably not worth the effort.

**Comment by helmesjo** [comment]
@memsharded Alright, fair enough! Will close this.
