### ISSUE TITLE
Refused connection

### ISSUE THREAD

**Issue by ecambio** [conan-io/conan#1063]
Hi, 
I was just trying to configure a package repo using conan.io
Locally (server and client both running on the same machine) everything works properly but trying the same procedure on a remote machine it returns the following error (from client console)  : 

`conan upload NIA/0.1@demo/stable --all -r=testrepo
Uploading NIA/0.1@demo/stable
Uploading conanmanifest.txt
ERROR: HTTPConnectionPool(host='localhost', port=9300): Max retries exceeded wit
h url: /v1/files/NIA/0.1/demo/stable/export/conanmanifest.txt?signature=eyJhbGci
OiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW8iLCJyZXNvdXJjZV9wYXRoIjoiTkl
BLzAuMS9kZW1vL3N0YWJsZS9leHBvcnQvY29uYW5tYW5pZmVzdC50eHQiLCJmaWxlc2l6ZSI6NDA4LCJ
leHAiOjE0ODg1MzI2OTh9.-0kZWuhB4Y2T_nfSKQPQqx3YpxidwZEGqemKP9YwyH0 (Caused by New
ConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at
0x0306CCD0>: Failed to establish a new connection: [Errno 10061] No connection c
ould be made because the target machine actively refused it',))
Waiting 5 seconds to retry...
`

On the server console it prompts the following message : 
`conan_server
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:9300/
Hit Ctrl-C to quit.

10.48.138.121 - - [03/Mar/2017 09:51:13] "GET /v1/conans/NIA/0.1/demo/stable/digest HTTP/1.1" 404 0
10.48.138.121 - - [03/Mar/2017 09:51:13] "GET /v1/users/check_credentials HTTP/1.1" 200 4
10.48.138.121 - - [03/Mar/2017 09:51:13] "GET /v1/conans/NIA/0.1/demo/stable HTTP/1.1" 404 0
10.48.138.121 - - [03/Mar/2017 09:51:13] "POST /v1/conans/NIA/0.1/demo/stable/upload_urls HTTP/1.1" 200 1018`

The server machine is also running other remote services without any issue.
Could you pls give me a clue about how to find the cause of this error?

Thank you in advance!

**Comment by memsharded** [comment]
What do you have in your ``server.conf``?
In the docs (http://conanio.readthedocs.io/en/latest/server.html#server-parameters), it reads:

> Server settings are defined with host_name and port. You must use the machine’s IP where you are running your server (or domain name), something like host_name: 192.168.1.100. This IP (or domain name) has to be visible (and resolved) by the conan client, so take it in account if your server has multiple network interfaces.

Did you change ``host_name`` to the machine IP?
Also if you have the server behind a proxy or something, please tell.

**Comment by ecambio** [comment]
Hi, thank you for your quick reply!
Yes I did it, but I think that the log from server shows that the dns resolution works properly.. isn't it?
Regarding the proxy no, there is no proxy.

**Comment by ecambio** [comment]
Hi, the issue has been fixed simply setting the _host_name_ with the machine host name.
Thank you very much for your help!
