### ISSUE TITLE
[feature] Autotools + PkgConfigDeps - a canonical way to set PKG_CONFIG_PATH?

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10639]
from https://github.com/conan-io/conan-center-index/pull/9488

if I use Autotools in conjunction with PkgConfigDeps, who is responsible to set PKG_CONFIG_PATH?
right now I had to add:
```
        tc = AutotoolsDeps(self)
        tc.environment.define("PKG_CONFIG_PATH", self.source_folder)  # is it really needed?
        tc.generate()
```
which is kinda ugly
if it doesn't make sense to fill it out of the box, it's probably worth to at least document, as in reality, almost every autotools-based recipe discover its dependencies via `pkg-config`.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Lets make it part of AutotoolsToolchain, indeed, it should work out of the box:

- Add the ``generators_folder`` to ``AutotoolsToolchain`` environment
- PkgConfigDeps and AutotoolsDeps are most likely mutually exclusive, I don't think they should be mixed
