### ISSUE TITLE
[feature] [2.0] exports_sources management

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10643]
Currently, by default, in the cache, we are copying the `source folder` to the `build folder` unless the `no_copy_source=True`, but _always_, the `self.source_folder` and `self.build_folder` points to the right location.

It might be worth it to explore if the `exports_sources` could have a similar mechanism. Maybe, by default they could be copied to the `base source folder` but unless `self.no_copy_exports_sources=True`.  And of course, a `self.exports_sources_folder` will point to the right location. 

**Note**: Maybe we should start by declaring the `self.exports_sources_folder` variable pointing to the `folders.base_source` to have a "pointer" for the user that, for example, wants to know where are the patches exported and then implement the "optional" copy mechanism, because at the end of the day, typically if you export all the sources, you don't want to skip the copy and if you are just exporting some source files, the copy is cheap so the benefit might not worth it.

**Comment by memsharded** [comment]
Conan 1.46 introduced ``def base_source_folder(self):`` that points to the base source folder for this purpose. For two reasons:

- The ``exports_sources_folder`` was already used, with different meaning (used in ``export_sources()`` method to point to the cache), and it was creating conflicts
- The ``exports_source_folder`` was a bit confusing in the local flow.

But I agree the above seems reasonable, so lets think about it.

**Comment by lasote** [comment]
Probably this could be addressed later if necessary, I would move this to 2.X. This is enough for now.

**Comment by lasote** [comment]
Let's try to use `self.exports_sources_folder`, this variable already exists to point to the cache during and export.
