### ISSUE TITLE
[question] How to tell "conan source" what version I want

### ISSUE THREAD

**Issue by eliasreid** [conan-io/conan#10646]
Is there a way to pass the package version to `conan source` command? https://docs.conan.io/en/latest/reference/commands/development/source.html

For example, if I want to download the sources for PackageA, I would expect an option similar to:
`conan source --source-folder=/tmp/PackageA-src/ . --version=1.0.0`

Is there a way to do this or step that I am missing?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @eliasreid 

No, this is not possible at the moment. It is a known limitation of Conan 1.X local flow. The version should be defined in the ``conanfile.py``.

This is being fixed in 2.0, see recent https://github.com/conan-io/conan/pull/10638, adding the ``--version`` argument.
