### ISSUE TITLE
Package depending on a variant of itself

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1064]
Can a package depend on a variant of itself but with different options?

I have a build that takes a long time, and I am trying to make a way that creates
different packages from the same build artifacts.  I tried dynamic requirements, but it seems 
as though that creates a loop:

```
    def requirements(self):
        if not self.options.fullsource:
            self.requires('{}/{}@{}/{}'.format(self.name, self.version, self.user, self.channel))
            self.options['MoneyCore'].fullsource = True

ERROR: Loop detected: MyPkg/0.0.0.100@jharris/testing
```

**Comment by memsharded** [comment]
No, I am afraid it is not possible. There can't be loops in the graph (this is a common constraint of package managers, Maven wouldn't allow them either). That includes depending on yourself.

If you are trying to create packages from the same build artifacts, then, what you are looking for is the new ``build_id()`` method. Unfortunately that doesn't allow dependencies between the different package binaries.

What would be exactly the problem you are trying to solve? Could you explain a bit further or put an example? Thanks

**Comment by tamboril** [comment]
Sure.  Mainly compile time, but also the deisre to have the _exact_ same binary artifacts packaged in different ways.  I need a few different packages made from the same compilation.  For instance, For the debug build, I want one package with full source, one with just headers and libs for developer use, and one with just binaries for deployment.  They all come from the same compilation, but with different (conan) options. As it  is now, the different options result in a whole new build, because it's a different directory.

Maybe I can conditioally not run the build and then package from the (pseudo-)upstream's build area.

**Comment by tamboril** [comment]
Actually, it looks as though `build_id()` is _exactly_ what I need.  I will try it.

**Comment by memsharded** [comment]
Ok, let me know how it goes or if you have any question regarding it.

**Comment by tamboril** [comment]
OK, I got it working like I wanted.  This feature was very timely, and quite useful, as I really wanted to avoid unnecessary rebuilds _and_ eliminate potentially different binaries (if the source contained timestamps or macros that were location dependent).

The only suggestion I have is to mention in the docs that in addition to intercepting `settings`, you can also intercept `options`, as in:

```
    def build_id(self):
        self.info_build.options.runtime = 'X'
        self.info_build.options.fullsource = 'X'
```

**Comment by memsharded** [comment]
Excellent, very glad that such feature could solve your issue, thanks go to @claasd for suggesting and promoting it.

Good suggestion, just added it to the docs: http://docs.conan.io/en/latest/reference/conanfile.html#build-id
