### ISSUE TITLE
[bug] temporary directories not removed

### ISSUE THREAD

**Issue by scddev** [conan-io/conan#10658]
* Conan version: 1.45.0

https://github.com/conan-io/conan/blob/1.45.0/conans/client/conf/compiler_id.py#L186
https://github.com/conan-io/conan/blob/1.45.0/conans/util/runners.py#L79

Both methods just create the directory but do not cleanup afterwards.

This seems to have been added between 1.44.1 and 1.45.0.

Maybe replace with `with tempfile.TemporaryDirectory() as ...`.

**Comment by memsharded** [comment]
Thanks for reporting! This was fixed in https://github.com/conan-io/conan/pull/10663, and will be in next 1.46
