### ISSUE TITLE
[bug] conan_server v1/v2 confusion

### ISSUE THREAD

**Issue by codedump** [conan-io/conan#10657]
Hello everyone,

I think this is a bug -- at the very least one in the documentation if nothing else. If I'mjust being clumsy and/or missing something important, please let me know so I can move/post this to "questions". (Also I'd really appreciate a hint on **what** I'm missing :-) )

I'm trying to configure and run a `conan_server`. Short symtoms, for every URL except for `/v1/ping` I receive a 404 in the style of:
```
    Error: 404 Not Found
    Sorry, the requested URL 'http://localhost:9300/v1/conans/search' caused an error:
    Not found: '/conans/search'
```

Now this is a page generated by the `conan_server` itself, mind you. The server process itself shows this in the logs:
```
    [2022-02-24 13:04:52 +0000] [29] [DEBUG] GET /v1/conans/search
```

If I try the same with `/v2/conans/search`, everything seems to work, i.e. I receive a page which looks like it has some functionality.

Trying to use the remote with the `conan` client also fails:

```
    $ conan search -r tst
    ERROR: 404: Not Found. [Remote: tst]
    $ conan remote list
    tst: http://192.168.8.243:9300 [Verify SSL: False]
```

But the `conan_server` log shows that the server itself is, indeed, reachable, it just fails "internally" with 404:
```
    [2022-02-24 13:10:28 +0000] [29] [DEBUG] GET /v1/ping
    [2022-02-24 13:10:28 +0000] [29] [DEBUG] GET /v1/conans/search
```

The environment I'm using is fairly easy to reproduce, I have a conan server Docker image over at [GitLab](https://gitlab.com/codedump2/conansrv-image). But for the sake of completeness, here the details.

### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora 35
  * Compiler+version: gcc (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)
  * Conan version: 1.44.1
  * Python version: 3.10.1

#### Using the conan server Docker image via podman

  - Run the `conan_server`, for example from the image above:
    ```
        $ git clone https://gitlab.com/codedump2/conansrv-image
        $ podman build -t conansrv-image -f conansrv-image/Dockerfile
        $ ./conansrv-image/run.sh
    ```
  - Connect to the server; verify that `/v1/ping` works, and `/v1/conans/search` fails:
    ```
        $ curl http://localhost:9300/v1/ping && echo yes
        yes
        $ curl http://localhost:9300/v1/conans/search || echo no
        no
    ```

#### Alternative way of running `conan_server` directly

  - Write config file:
    ```
    $ cat > ~/.conan_server/server.conf << EOF
    [server]
    jwt_secret: 3yp5m2GLQUSMCTBx 
    jwt_expire_minutes: 120
    ssl_enabled: False
    port: 9300
    public_port: 9300
    host_name: localhost
    store_adapter: disk
    authorize_timeout: 1000
    disk_storage_path: /home/jinkies/.conan_server//data
    disk_authorize_timeout: 1800
    updown_secret: KFVycNk5xkvc/3Mm
    
    [write_permissions]
    */*@*/*: *
    
    [read_permissions]
    */*@*/*: *

    [users]
    jinkies: s3cr3t
    EOF
    ```

  - Run conan server with `gunicorn`:
    ```
    gunicorn -b 0.0.0.0:9300 \
	 -w 4 \
	 -t 1000 \
	 --log-level debug \
	 conans.server.server_launcher:app
    ```

  -  Verity that `/v1/ping` works, but `/v1/conans/search` fails:
      ```
     $ curl http://localhost:9300/v1/ping/ && echo yes
     yes
     $ curl http://localhost:9300/v1/conans/search || echo no
     no
     ```

### Logs

The full serverlog:
```
$ gunicorn -b 0.0.0.0:9300 -w 4 -t 1000 --log-level debug conans.server.server_launcher:app
[2022-02-24 13:28:32 +0000] [21] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:9300']
  backlog: 2048
  workers: 4
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 1000
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
 logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: conans.server.server_launcher:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fd29d3a84c0>
  on_reload: <function OnReload.on_reload at 0x7fd29d3a85e0>
  when_ready: <function WhenReady.when_ready at 0x7fd29d3a8700>
  pre_fork: <function Prefork.pre_fork at 0x7fd29d3a8820>
  post_fork: <function Postfork.post_fork at 0x7fd29d3a8940>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fd29d3a8a60>
  worker_int: <function WorkerInt.worker_int at 0x7fd29d3a8b80>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fd29d3a8ca0>
  pre_exec: <function PreExec.pre_exec at 0x7fd29d3a8dc0>
  pre_request: <function PreRequest.pre_request at 0x7fd29d3a8ee0>
  post_request: <function PostRequest.post_request at 0x7fd29d3a8f70>
  child_exit: <function ChildExit.child_exit at 0x7fd29d3a9090>
  worker_exit: <function WorkerExit.worker_exit at 0x7fd29d3a91b0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fd29d3a92d0>
  on_exit: <function OnExit.on_exit at 0x7fd29d3a93f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-02-24 13:28:32 +0000] [21] [INFO] Starting gunicorn 20.1.0
[2022-02-24 13:28:32 +0000] [21] [DEBUG] Arbiter booted
[2022-02-24 13:28:32 +0000] [21] [INFO] Listening at: http://0.0.0.0:9300 (21)
[2022-02-24 13:28:32 +0000] [21] [INFO] Using worker: sync
[2022-02-24 13:28:32 +0000] [22] [INFO] Booting worker with pid: 22
[2022-02-24 13:28:32 +0000] [23] [INFO] Booting worker with pid: 23
***********************
Using config: /home/jinkies/.conan_server/server.conf
Storage: /home/jinkies/.conan_server/data
Public URL: http://localhost:9300/v2
PORT: 9300
***********************
[2022-02-24 13:28:32 +0000] [24] [INFO] Booting worker with pid: 24
[2022-02-24 13:28:32 +0000] [25] [INFO] Booting worker with pid: 25
[2022-02-24 13:28:32 +0000] [21] [DEBUG] 4 workers
***********************
Using config: /home/jinkies/.conan_server/server.conf
Storage: /home/jinkies/.conan_server/data
Public URL: http://localhost:9300/v2
***********************
Using config: /home/jinkies/.conan_server/server.conf
PORT: 9300
***********************
Storage: /home/jinkies/.conan_server/data
Public URL: http://localhost:9300/v2
PORT: 9300
***********************
***********************
Using config: /home/jinkies/.conan_server/server.conf
Storage: /home/jinkies/.conan_server/data
Public URL: http://localhost:9300/v2
PORT: 9300
***********************
[2022-02-24 13:28:36 +0000] [22] [DEBUG] GET /v1/conans/search
[2022-02-24 13:28:37 +0000] [24] [DEBUG] GET /favicon.ico
[2022-02-24 13:28:39 +0000] [23] [DEBUG] GET /v1/conans/search
[2022-02-24 13:28:39 +0000] [23] [DEBUG] GET /favicon.ico
[2022-02-24 13:28:49 +0000] [23] [DEBUG] GET /v1/ping
[2022-02-24 13:28:49 +0000] [23] [DEBUG] GET /v1/conans/search
```

**Comment by memsharded** [comment]
I haven't tried it, but maybe your ``disk_storage_path: /home/jinkies/.conan_server//data`` with the double slash is the problem here?

**Comment by codedump** [comment]
> I haven't tried it, but maybe your `disk_storage_path: /home/jinkies/.conan_server//data` with the double slash is the problem here?

I've just tried to change that -- same result.

But in any case: `/v2/conans/search` behaves as it should, with or without the double `//`.

What also makes me wonder is the server's error message:

```
    Sorry, the requested URL 'http://localhost:9300/v1/conans/search' caused an error:
    Not found: '/conans/search'
```

Note that the server recognizes that the "requested URL" was `/v1/conans/search`, but fails for `/conans/search`. It sounds to me like some internal URL mangling of the Conan Server application forgot to take into account that a `/v1` is prepended to the URLs, and tries to forward the request to an `/conans/...` entry point and fails.

This doesn't seem to happen for `/v2`.

Is there any way to make the Conan client use v2 API? Is that even useful? If not, what's the thing with v1 versus v2?

**Comment by memsharded** [comment]
Yes, v2 is the future. It is enabled with ``conan config set general.revisions_enabled=True``. It will become the only api in Conan 2.0 (which is already in alpha)

**Comment by memsharded** [comment]
(Also, if you are struggling with the conan_server, until we can have a look, you might try the free ArtifactoryCE, you can use it for free, even for private packages, and it contains a bunch of interesting things like a Web UI, better permissions, it scales better...)

**Comment by codedump** [comment]
> Yes, v2 is the future. It is enabled with `conan config set general.revisions_enabled=True`. It will become the only api in Conan 2.0 (which is already in alpha)

Ok, so this apparently at least makes the server responsive:
```
    $ conan config set general.revisions_enabled=True
    $ conan search -r tst
    There are no packages
```

Server log (apparently the ping is still requested via `v1`, but the search is done via `v2` and it behaves as it should):
```
    [2022-02-24 15:02:59 +0000] [23] [DEBUG] GET /v1/ping
    [2022-02-24 15:02:59 +0000] [23] [DEBUG] GET /v2/conans/search
```

As to the ArtifactoryCE: I've briefly considered that, but I'm not setting this up for me personally, I'm doing this for corporate use (a small-ish development team). We already have the Nexus artifact server running for other purposes and we're going to keep it. But Nexus falls on its nose with regards to (authoritative) serving of Conan packages.

Installing another giant artifactory just for Conan seems like a bad decision maintenance-wise, we're really reluctant to go the ArtifactoryCE way. This is why the plan to go now was to use `conan_server`, and eventually preface it by the Nexus Conan proxy, which seems to work fine, should we run into performance or feature problems.

I'll do some more testing as to whether v2 works for production.

Please let me know if there's anything else I can do to help with debugging v1.

Cheers

**Comment by codedump** [comment]
> I'll do some more testing as to whether v2 works for production.

...aaand I'm back, seems like `v2` is a dead end for now:
```
    $ conan user -r tst -p s3cr3t jinkies 
    ERROR: b'\n
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n
        <html>\n
            <head>\n
                <title>Error: 404 Not Found</title>\n
                <style type="text/css">\n
                          html {background-color: #eee; font-family: sans;}\n
                          body {background-color: #fff; border: 1px solid #ddd;\n
                          padding: 15px; margin: 15px;}\n
                         pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}\n
                </style>\n
            </head>\n
            <body>\n
            <h1>Error: 404 Not Found</h1>\n
            <p>Sorry, the requested URL <tt>&#039;http://192.168.8.243:9300/v1/users/authenticate&#039;</tt>\n
                 caused an error:</p>\n
            <pre>Not found: &#039;/users/authenticate&#039;</pre>\n
        </body>\n
    </html>\n'

    Invalid server response, check remote URL and try again. [Remote: tst]
```

Apparently `general.revisions_enabled=True` does not equal `v2`, it's a weird mix of `v1` and `v2`, and the v1 part always fails except for `ping`.

**Comment by lasote** [comment]
After a lot of debugging I finally realized what is going on, [here](https://gitlab.com/codedump2/conansrv-image/-/blob/master/Dockerfile) you are installing the pip package "conan_server", which is the server for the `conan v2` version (still alpha). The 1.X conan server comes with the "conan" pip package. Just change to "pip install conan" and it should work.

Please, confirm that it is working and close the issue in that case. Thanks.

**Comment by codedump** [comment]
@lasote 

Yes, that works now.

Thank you very much for your friendly help! :-) Is there any way I can buy you a coffee?

Cheers
