### ISSUE TITLE
[feature] AutotoolsToolchain : reconsider default_configure_install_args default to True?

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10650]
from https://github.com/conan-io/conan-center-index/pull/9488

without `default_configure_install_args = True`, Autotools will try to install into `/usr`, and will eventually fails in most of the cases (as it requires root access). or if it doesn't fail, it will pollute the system (potentially, overriding system packages?).
I think, practically, every actual recipe will have to add `default_configure_install_args = True` in order to work correctly (install filess to the package folder).

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Related https://github.com/conan-io/conan/issues/10430

I think at least it should adjust the ``--prefix``, about the rest of variables, probably too: https://github.com/conan-io/conan/issues/10430 and https://github.com/conan-io/conan/issues/10393

**Comment by memsharded** [comment]
Changed to True in https://github.com/conan-io/conan/pull/10672, will be released in 1.46
