### ISSUE TITLE
Conan is mistaken about my xcode version

### ISSUE THREAD

**Issue by beatboxio** [conan-io/conan#10669]
My conan install is failing reporting that my xcode version is not "xcode 12 or higher", but I'm using 13.

I'm using the following conanfile.txt:
```

[requires]
sdl/2.0.20
boost/1.78.0

[generators]
cmake
```

When I run the conan install command, I get the following output:

```
conanfile.txt: Installing package
Requirements
    boost/1.78.0 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conan-center' - Cache
    libbacktrace/cci.20210118 from 'conancenter' - Cache
    libiconv/1.16 from 'conan-center' - Cache
    sdl/2.0.20 from 'conancenter' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    boost/1.78.0:c4194498ccd62223a5ff00fea57b4a976343c0a7 - Cache
    bzip2/1.0.8:32bef4803d4b079e983ecb27f105881e778bc5a7 - Cache
    libbacktrace/cci.20210118:f74366f76f700cc6e991285892ad7a23c30e6d47 - Cache
    libiconv/1.16:f74366f76f700cc6e991285892ad7a23c30e6d47 - Cache
    sdl/2.0.20:INVALID - Invalid
    zlib/1.2.11:f74366f76f700cc6e991285892ad7a23c30e6d47 - Cache

Installing (downloading, building) binaries...
**ERROR: There are invalid packages (packages that cannot exist for this configuration):
sdl/2.0.20: Invalid ID: sdl/2.0.20 requires xcode 12 or higher**
```
I'm using the following versions:

```
macOs Monterey (12.2.1) 
XCode 13.2.1
conan 1.45.0
Python 3.8.2
cmake 3.17.0
```

I have looked at the recipe on the conan site: https://conan.io/center/sdl?tab=recipe&os=Macos

But I am not able to see how it's getting the xcode version wrong, and I don't know where to begin.

And I see the check in the recipe only applies to SDL > 2.0.16. Conan install works fine with 2.0.16 but I need the newer version.

If anyone has any help in getting started in tracking this down I would really be grateful.

By the way, I'm not a professional, so I recognize this is likely user error.

**Comment by czoido** [comment]
Hi @beatboxio,
That is probably because you have the wrong `compiler.version` in your _default_ profile.
Do a `conan profile show default` and if you see that `compiler.version=12.0` is defined and update it to`13.0`. The file is usually in the _profiles_ folders of your Conan home (get the location with `conan config home`)

**Comment by beatboxio** [comment]
Yes it turns out my compiler.version=11.0

Thanks for that clue.

I have just tried changing it manually to 12.0 but it stopped conan install from working with a new error.

```
bzip2/1.0.8: ERROR: Error downloading binary package: 'bzip2/1.0.8:75fe66fbfe61230e9fcbb361f13b6b3baa483e0a'
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

```
Changing it back to 11.0 reverts to the previous error.  

Is there a more standard way to change the compiler version?  Some conan config command I should be using to update it?

**Comment by czoido** [comment]
You are getting that error because you are using bintray that was shut down some time ago, the official Conan remote is `https://center.conan.io` now. Please check: https://docs.conan.io/en/latest/faq/troubleshooting.html?highlight=bintray#error-httpsconnectionpool-host-conan-bintray-com-port-443

You can list your remotes with: 
`conan remote list`
to add conancenter to your remotes:
`conan remote add conancenter https://center.conan.io`

You could overwrite your default profile with a new auto-detected one with: `conan profile new default --detect --force`

**Comment by beatboxio** [comment]
OK thank you very much.  I removed that remote.  I had already added the new one.

I got some promising output that creating a new profile noticed the new clang version:

conan profile new default --detect --force
Found apple-clang 13.0

But I get a new error that seems like something is still trying to go to bintray_conan_repo


ERROR: Permission denied for user: 'None'. [Remote: bintray_conan_repo]


Here's my remote list:

conan remote list                  

conancenter: https://center.conan.io [Verify SSL: True]
bintray_conan_repo: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]

If I remove the bincrafters as well, I get this error:

ERROR: Missing prebuilt package for 'boost/1.78.0', 'bzip2/1.0.8', 'libbacktrace/cci.20210118'
Use 'conan search bzip2/1.0.8 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=boost --build=bzip2 --build=libbacktrace'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

**Comment by czoido** [comment]
Repos at `bintray.com` does not exist any more, do a `conan remote remove bintray_conan_repo`

**Comment by beatboxio** [comment]
Thank you for all the help.  It just worked.

In the end I could not even install boost because it said binaries don't exist.  Looking on the site, I saw that indeed boost was not built apparently for 13.0.  

I manually changed my compiler to 12.0 in the file you showed me earlier and now SDL and SDL_TTF both seem to have installed fine!   

Thank you again.

**Comment by czoido** [comment]
> Thank you for all the help. It just worked.
> 
> In the end I could not even install boost because it said binaries don't exist. Looking on the site, I saw that indeed boost was not built apparently for 13.0.
> 
Glad it worked.
Conan center index does not have binaries for 13.0, you can always build locally using `conan install .... --build=missing` this will build all the libraries you don't have binaries for.
