### ISSUE TITLE
[question] Is there a way to control the size of Conan cache?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#10667]
Hi,
we bumped into the situation on our CI system that Conan's cache practically grows endlessly over time.
Is there a plan / way to "garbage collect" - via Conan itself (e.g. a command line extension to conan, or a separate python script packages into the Conan distribution, I don't know) - the cache? I mean like erase the oldest N entries to make sure that the cache's size doesn't go above X Gb?
Thanks,

**Comment by czoido** [comment]
Hi @harsszegi,

Yes, that's something we are discussing to include in Conan 2.X. some kind of  least-recently-used removal for Conan packages.  Also, that could be added as an extension with a custom command, or some similar mechanism.

**Comment by harsszegi** [comment]
Aok, thanks a lot for the info!

**Comment by memsharded** [comment]
Conan has finally implemented this in https://github.com/conan-io/conan/pull/14054, it has been merged it will be in next 2.0.14 release!
