### ISSUE TITLE
Rename conan targets with (cmake generator)

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#1066]
At the moment targets for cmake are name `CONAN_PK::mytarget`. Sometimes i want to use my custom created target instead of the conan one (f.e. If i use a local dev version), but in cmake there is no way to rename or alias an imported target , so the only useable way would be to set an option in conan to rename the target created by conan.

Is there a way to do that?

**Comment by memsharded** [comment]
Not sure if I understand your use case. If you want to use your own custom target instead of the conan one, you can just create it, right? You already have all the variables defined, per package, so it is very easy to create your own target. Check the corresponding code in ``conanbuildinfo.cmake``, it should be straightforward to extract from there and adapt at your will.

Another option could be just to declare a new target and make it depend on the ``CONAN_PKG::mytarget``, so it will inherit the properties.

**Comment by tonka3000** [comment]
I'm already using your option one. I will try the second option because it is much easier (less code).

**Comment by memsharded** [comment]
But could you please elaborate a bit further about why you need a custom target name, and you cannot use the provided one? Maybe there is a legitimate need for it, we just want to understand the use case, sometimes there are things that can be improved elsewhere. When you are talking about "use a local dev version", what do you mean with it? Thanks for your feedback!

**Comment by tonka3000** [comment]
Hey,

sorry for the late response.

The reason why we want to use custom names is f.e. backward compatibility. The are many good find_package recipes in cmake, and sometimes we use conan to build the dependency and find the files via find_package (we use that f.e. with Qt where we need many extra script from the cmake's find_package module).

Second reason: We have some libs (both developed by us) which depends on each other, so most of the time we have local change and i want to use it in my second project locally, which is very handy with the classic cmake find_package approach, with conan this is not so easiy. This is general a problem for us, because sometimes we want to use latest dev commit (instead of tags, which works well for 3rdparty libs where the conanfile is not in the repo from the code), but we don't know which is best practice for supporting also latest dev state. We don't want to change our conanfile.py everytime (for a commit or another channel) because that make developing much harder. If you have any advice i would be very thankful.

Greetings
Tonka

**Comment by memsharded** [comment]
Why don't you use FindCMake files in your conan packages? That would be the easiest way. They are quite simple to write, and you can keep both the compatibility with conan packages and without them.

Please have a look to: http://conanio.readthedocs.io/en/latest/integrations/cmake.html#find-packages, and tell me if this could help.

This would be the approach for locating libraries cmake-style in a generic fashion (conan and not conan). Regarding the issue of using the latest dev commit, I am not sure what is the problem. You can use packages for the latest dev-commit, they can be overwritten and ``install --update`` to get the latest version. Please provide a bit more detail about this issue.

**Comment by tonka3000** [comment]
> Why don't you use FindCMake files in your conan packages? That would be the easiest way. They are quite simple to write, and you can keep both the compatibility with conan packages and without them.

> Please have a look to: http://conanio.readthedocs.io/en/latest/integrations/cmake.html#find-packages, and tell me if this could help.

That is what i'm already doing. I create my targets in my custom FindXXX.cmake files if the CONAN_PKG::MYPKG is not present. I know that i could only use FindXXX.cmake files, but i think conan could make life so much easier, because the only thing i have to do is to replace the CONAN_PKG::MYPKG with my custom one and everything is fine.

For me, there are 2 scenarios:
1. I have a local dev version of a 3rdparty lib, so here i can only use the FindXXX.cmake files which make totally sense, because there is not commit in any repo.
2. I have a dev version, which is commited and pushed to a remote repository, but no tag is "on it".  My problem: I can build the binary locally and push the binaries to conan, which works fine, but that package are used by so many different compiler that it is very hard to compile every possible combination on every commit and so it would be nice to compile it from source. Most conan packages i've see depend on tags, which is fine, but in this scenario thats a problem for me. I want to push my conan package to a conan remote (to a f.e. latest commit from dev branch to the dev channel and tagged on master branch to stable) and let the user compile it, so if he/she use my package, they compile from source, but i have no good idea how to manage this, because on ever commit i have to change my conanfile.py file (mainly for the source/build function: dev channel has a different branch and commit to fetch as the stable branch), so that i can fetch the correct commit in the case of an "compile from source". Firstly i use a template engine to create my "local" conanfile.py, but in the case where i manage the creation of my package and the use of other conan packages in one file in the repo, it getting really hard to start, because the user always have to create the "real" conanfile.py via the template engine, then make the conan install stuff and the create project with the cmake generator just for installing 3rdparty packages.
It would be awesome if there where a possibility to override/inject some properties from the conanfile on export () on the fly which are properties. Something like
`conan export ...... -commit aefd5fskdf` (channel is already controllable via the environment variable as far as i know)
Is there already any kind of such functionality?

Sorry for the long post, it's really hard to explain it by text.

**Comment by memsharded** [comment]
Maybe the "ANY" value for options might help. So something like:

- Add ``build_policy="missing"`` to your recipe. This is useful if the default policy is that and you don't want to specify it all the time in the command line for this package
- Set a package version to "develop"
- Add a package option ``commit="ANY"``, with default value "None"
- Use the package option in the ``build()`` step of your recipe, to checkout the desired commit prior to building (or don't, if value is None, then you will get the HEAD)

Now you can depend on that package, and point to any specific commit as an option:
```bash
$ conan install -o MyPkg:commit=ad456ad77655ad
```

I think this is a different thing from the "targets" one, but I'd propose trying to solve this first, because it is more "core", and once the work flows are defined, we can go back to the cmake issues.

In any case, I agree this is hard to explain, so if you feel it is necessary to jump to a chat or something, please write us an email.

**Comment by tonka3000** [comment]
Correct me if i'm wrong, but adding a commit option will produce "spam" in my local conan cache if i change the commit everytime?

**Comment by memsharded** [comment]
It will produce a different package binary for each different commit, that is right. It is not your intended behavior? I thought you wanted to be able to package the specific commit you wanted. If you want just the HEAD version of the development branch, no problem, just don't add the option, and you will get it after "git cloning" your sources. If you want to force the build from sources every time you install, you can add ``build_policy="always"``. 

Also if the packages are being re-generated and uploaded to the server, they can be updated in the client with ``conan install --update`` (if you don't use ``--update``, it will just use the current package in your conan local cache).
