### ISSUE TITLE
[feature] Meson + PkgConfigDeps - a canonical way to set PKG_CONFIG_PATH? 

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10670]
essentially the same as #10639, but for `Meson`

right now I need to use something like:
```
def generate(self):
    tc = MesonToolchain(self)
    tc.project_options["pkg_config_path"] = self.source_folder
    ...
    tc.generate()
```

I'd prefer if it worked out of the box

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This is already implemented in the ``MesonToolchain``:

```python
self.pkg_config_path = self._conanfile.generators_folder
```

And in the template
```
[built-in options]
    ...
    {% if pkg_config_path %}pkg_config_path = '{{pkg_config_path}}'{% endif %}
```

Is it that it is being applied in the wrong section, should it be in ``project options``?

**Comment by SSE4** [comment]
nope, it seems to be built-in:
https://mesonbuild.com/Machine-files.html#cross-and-native-file-reference
perhaps, it's not in 1.45, only in 1.46? I'll check it and let you know

**Comment by SSE4** [comment]
okay, sorry for the noise, it works as expected, it wasn't finding pkg-config files for a different reason (recipe didn't set `pkg_config_name` property).
