### ISSUE TITLE
[question] How to package only my DLL?

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#10682]
Hi,
I have a project that builds a library using its own scripts (that are not conan) for Windows/Linux Release/Debug x86_64/x86 combinations.

I want to create a package using Conan that has a binary package for every settings of the library, with _only the library file_ in it. As the library is already built in the project build folder, I don't need it to be built by conan, and I don't want to export its source code in the package.

How to do that?
Thanks,

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Bassem-Ramzy 

I think you are looking for the ``export-pkg`` functionality: https://docs.conan.io/en/latest/creating_packages/existing_binaries.html#packaging-pre-built-binaries

Recipe will contain the ``package()`` and ``package_info()`` methods, no need to provide sources, build or anything like that.
Note that the ``settings`` field is still necessary, that will allow to model the different binaries you are creating.

Please have a look and let us know.

**Comment by Bassem-Ramzy** [comment]
Yes, it works. Thanks a lot
