### ISSUE TITLE
incorrect variable names in conanbuildinfo.cmake

### ISSUE THREAD

**Issue by kent-at-multiscale** [conan-io/conan#1068]
I was looking in the `conanbuildinfo.cmake` file generated by the cmake generator and noticed something very strange. In the top part where each package defines its flags and libraries and directories, it defines a variable of the form `CONAN_C_FLAGS_PACKAGE`. However, that variable is never used anywhere. Instead, there are references to `CONAN_CFLAGS_PACKAGE`. That can't be right, can it?

**Comment by memsharded** [comment]
Certainly, it seems that those variables, should be used in the definition of targets, instead of the CONAN_CFLAGS_PACKAGE one. So this is a mistake.

**Comment by memsharded** [comment]
Fixed and released in 0.20.3
