### ISSUE TITLE
[question] MesonToolchain + AutotoolsDeps - how to propagate an environment?

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10683]
in Meson world, most of the dependencies are found via pkg-config (*.pc files).
however, not all the libraries provide .pc files, and in these cases, dependencies found by other means (e.g. environment variables like `SDL2_CONFIG`/`FREETYPE_CONFIG`, or just library name is well known so it's directly linked via -`l`)
for these dependencies, it might use [find_library](https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerfind_library) over [dependency](https://mesonbuild.com/Reference-manual_functions.html#dependency) : https://gitlab.gnome.org/GNOME/glib/-/blob/2.71.2/meson.build#L2078
this obviously requires compiler flags for this dependency to be set (`-I`, `-L` and -`l`, most commonly).
`AutotoolsDeps` already can set and generate required environment variables (`CFLAGS`/`LDFLAGS`) that meson could theoretically pick, but it's not fully clear how to propagate them to the `MesonToolchain`, so it saves them to the cross/native file.
studying how `AutotoolsDeps` work in conjunction with `Autotools`:
- `AutotoolsDeps` generates `conanautotoolsdeps.sh` with environment variables
- `conanbuild.sh` somehow sources `conanautotoolsdeps.sh` (for me it's not fully clear how does it know what it needs to source the file)
- `conanfile.run` uses `conanbuild.sh` internally

for `Autotools` it works, as it uses `self.run("configure ...")`, while for `MesonToolchain` it doesn't - as it doesn't run anything during the writing of the cross/native file.

trying the following:
```
        tc = AutotoolsDeps(self)
        tc.generate()
        with tools.environment_append(tc.vars()):
            tc = MesonToolchain(self)
            ...
            tc.generate()
```
doesn't help. it's due to the fact `MesonToolchain` creates its own `VirtualBuildEnv` instance from scratch, and I don't see any possibility of how to inject env there.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SSE4** [comment]
I got an another [attempt](https://github.com/conan-io/conan-center-index/pull/11053) to migrate `GLib` to `MesonToolchain`. in order to propagate the environment from `AutoToolsDeps` to `MesonToolchain` I had to add a followiing line:
```
self.buildenv.compose_env(tc.environment)
```
but I suppose it should be automatic?
it's required to make e.g. the following code work (https://github.com/GNOME/glib/blob/main/meson.build#L2038):
```
libintl = cc.find_library('intl', required : false)
```
if it helps, I can prepare a minimal reproducible example, or test case

**Comment by memsharded** [comment]
I don't fully get the big picture.

The idea is that information from dependencies lives in its own environment file, while the toolchains are focused on translating the current settings/options/configuration to the build system. Following this design, the information from ``AutotoolsDeps`` shouldn't be propagated to ``MesonToolchain`` at all. They will just generate 2 different environment scripts, and they will be source one after the other. 
I guess that I am missing some specifics about how meson works.

**Comment by SSE4** [comment]
> 
> The idea is that information from dependencies lives in its own environment file

that's fine to generate these dependencies to their own environment files. the problem is more about how to connect all these pieces together. meson itself doesn't know about these environment files, and won't read anything from them. it only reads from native/cross files we generate from toolchain. that's what we currently use to propagate information from conan layer to meson layer. so, perhaps, `MesonToolchain` should learn to read from these files?

> while the toolchains are focused on translating the current settings/options/configuration to the build system. 

that's obviously, not enough, as meson for instance should be aware about include directories of each dependency (otherwise, compiler won't find headers).

> Following this design, the information from `AutotoolsDeps` shouldn't be propagated to `MesonToolchain` at all. 

then it will be impossible to build real packages such as `GLib`. the information should be somehow propagated to meson, one way or another.

> They will just generate 2 different environment scripts, and they will be source one after the other. 

okay, but who is responsible to merge these 2 environment scripts? recipe itself? or should it be somehow automatic by conan?

> I guess that I am missing some specifics about how meson works.

maybe. there are two ways how we can proceed:

1. try to make some real recipe (e.g. `GLib`) to build sucessfully via `MesonToolchain` to understand what's missiing
2. I can extract "minimal reproducible example" from GLib, and write some test(s) that illustrate missing points

**Comment by SSE4** [comment]
I made a simple, minimal reproducible example to illustrate the big picture. see my other comment: https://github.com/conan-io/conan/issues/11398#issuecomment-1147381047
