### ISSUE TITLE
A require and build_require dependency must use the same build options?

### ISSUE THREAD

**Issue by gdray-dev** [conan-io/conan#10690]
A single package listed as both a build and compile dependency has to use the same build options for creating both packages. These will not be the same package in a cross compile environment.

This issue seems like a defect although it may not be a serious one.   It does impact cross compile builds in the sense that it just might not be possible to build the host and target platform using the same build options.  Or it may be very annoying to have to artificially compile the build environment in a number of ways just to allow compiling target environments in multiple ways.

Example:

    requires = ["protobuf/3.6.1@scm/stable"]
    build_requires = ["protobuf/3.6.1@scm/stable"]

Now my build machine is Windows 64-bit OS and I only build protobuf as shared=False
My target is an embedded Linux platform and I want to build the target code with shared=True

In this case, Conan fails in it's attempt to find all pre-built dependencies.  I did not build a version of Windows 64-bit OS protobuf that used shared libraries.  This example can be worked around if I do build a shared=True version of protobuf for Windows but ... why do I have to?

Perhaps the set of packages that are used as both a requires and build_requires is limited enough that the work-around is to simply build them in all variants on both platforms.  But the ideal would be to have a single build profile that is not impacted by the option variants of the target platform.   There could be cases where this might even be required although I can't provide you one myself.

A second work-around would be to artificially rename the build_requires package. Though it seems a lot of work was put into combining the build (protoc) and compile (protobuf headers/libraries) parts of the protobuf package into a single package.

    requires = ["protobuf/3.6.1@scm/stable"]
    build_requires = ["protoc/3.6.1@scm/stable"]

Am I missing a better work-around?  Does this issue rise to the level of a defect that is worth fixing?  The fix would seem non-trivial as maybe a build_requires_defualt would be required or more complex syntax on targetted options like build:protobuf:share=False

I have not tested what would happen if I put the default option into the -pr:b build profile.  This might be a partial work-around but I didn't want protobuf to be part of the profile as it is not used extensively in all packages. Just a few.

Thanks for any comments / feedback.

**Comment by memsharded** [comment]
At the moment I think the only possibility is trying to add the option to the profile (the build profile). You might be able to add the option even if you don't add the ``build_require`` in the profile like:

mybuild_profile
```
[options]
protobuf:myoption=myvalue
```
That will only apply to protobuf in the build context.

Conan 2.0 will have a mechanism to define options per dependency directly in recipes if desired, but this will not be possible in 1.X.

Please try the above, and let us know how it goes.

**Comment by gdray-dev** [comment]
I was going to say that I hope 2.0 allows distinguishing between build use of a dependency and compile use of one with respect to options.  But I believe declaring the desired value of the option in the build profile appears to work well enough.

Putting the option setting in the build profile allowed me to change the version of the package used for building.  I could also specify either protobuf:shared = True/False in my client package and the build profile value was still used for my build requirement (GOOD).  I also tried changing the option on the command line.  Unfortunately, this changed both the build and compile time dependency and re-introduced the problem.

I think for 1.X this is good enough.

Thanks.

**Comment by memsharded** [comment]
Thanks for following up

> Unfortunately, this changed both the build and compile time dependency and re-introduced the problem.

Sure you used the ``-o:b protobuf:option=build_value -o:h protobuf:option=host_value``? syntax? It is necessary to specify the ``build`` in the command line too.

**Comment by gdray-dev** [comment]
Oh no, you're right, I messed up and only used -o instead of -o:b so it was user error on my part in that test.  Thanks for pointing it out.
