### ISSUE TITLE
[question] How to set sysroot with new CMake generators ?

### ISSUE THREAD

**Issue by JonathanGirardeau** [conan-io/conan#10699]
Hello,

I use CMAKE related variables to set sysroot in my custom profile:
```
[env]
CONAN_CMAKE_SYSROOT=...
```
But it seems it has no effect with new CMake generators (CMakeToolchain, etc), how I am supposed to set sysroot ?

**Comment by jwillikers** [comment]
With `CMakeToolchain`, you'll need to add it to the generated CMake toolchain file by setting the CMake variable(s) i.e. `CMAKE_SYSROOT`. The easiest way to do this is to set the CMake variable in the `generate` method in the Conanfile.

```python
def generate(self):
  tc = CMakeToolchain(self)
  tc.variables["CMAKE_SYSROOT"] = "/my/sys/root/"
  tc.generate()
```

**Comment by JonathanGirardeau** [comment]
Thanks for the answer. 
I don't think it is a good practice to hard code the `sysroot` path in the recipe of a package. Usually the `sysroot` path depends on the conan profile used and the computer you are using to build. So I think the right place to set the `sysroot` path is in profile files located in `~/.conan/profiles/`.

**Comment by czoido** [comment]
Hi @JonathanGirardeau,
You may use the `[conf]` section of the profiles to define that information and later get the value of the sysroot in the generate method... You can have a look at the docs about `[conf]` here: https://docs.conan.io/en/latest/reference/config_files/global_conf.html#configuration-in-your-profiles

**Comment by JonathanGirardeau** [comment]
Hello @czoido,
Thanks for the tip, I finally use a cmake toolchain file to set `CMAKE_SYSROOT` variable:
```
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR arm)
SET(CMAKE_SYSROOT <path to sysroot>)
```
And I reference the toolchain in my profile:
```
[conf]
tools.cmake.cmaketoolchain:user_toolchain=<path to my cmake toolchain>
```
I think it is cleaner than adding in all my recipes a code to check whether MY_SYSROOT configuration variable exists and set CMAKE_SYSROOT variable to the same value.
