### ISSUE TITLE
[bug] using conan.tools.meson generates cpp_std with two single quotes

### ISSUE THREAD

**Issue by hstejas** [conan-io/conan#10705]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 21.10
  * Compiler+version: gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
  * Conan version:   1.45.0
  * Python version: 3.9.7

#### Library A uses meson
- Create a new project with `conan new abc/v1 --template=meson_lib`, (some changes were done to adapt to existing code)
- `conan create .` # works OK no errors, release mode, cpp_std is not specified

#### Library B uses cmake (https://github.com/conan-io/cmake-conan)
- add abc/v1 to conanfile.txt
- genrators is `cmake_find_package`
- `CMakeLists.txt` has `set(CMAKE_CXX_STANDARD 20)`

### Logs (Executed commands with output) (Include/Attach if Applicable)
Fails during cmake configure
> [cmake] ERROR: Malformed value in machine file variable 'cpp_std'.

generated `conan_meson_native.ini` has (notice '' is not ")
```
[built-in options]
buildtype = 'debugoptimized'

default_library = 'static'

b_ndebug = 'true'

cpp_std = ''c++1z'' 
backend = 'ninja' 
```

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/10707, it will be released in 1.46, today or tomorrow.
Thanks for reporting!
