### ISSUE TITLE
[question] Conan Upload all binaries after build

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#10718]
Hey,
i managed to set up conan to download and build all packages locally.
Now to save some time I'd like to upload all packages (recipe + binaries).

The upload should be done periodically on a Windows CI and Linux CI machine.

Now when calling  
`conan upload "*" --all -r conan -c`

However I'm getting lot's of error messages

```
Uploading tinyxml/2.6.2 to remote 'conan'    
ERROR: tinyxml/2.6.2: Upload recipe to 'conan' failed: invalid literal for int() with base 10: ''. [Remote: conan]

```

This is repeated for all packages.

So Ive got 2 questions: 
1. How can I upload all packages (recipe + binaries)?
2. Is this (conan upload "*"...) the correct way to do this in a CI step for multiple platforms or is there a better approach?

Thank you guys for helping. So far conan works nicely with cmake :)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Ju1He1 

This error is weird, I have seen it happening before when something is corrupted in the cache package storage.
One of the cases this can happen is if by accident the Conan cache is moved to the same location of the "short-paths" cache, that is ``C:/.conan`` folder in Windows.

Is this the case? does it happen in Windows only or in other systems?

**Comment by ghost** [comment]
Hey James
Thx for your quick feedback.

To avoid any cache corruption issues i now did the following

clean local cache
full rebuild locally
call `conan upload "*" --all -r conan -c`

but now I'm getting this error for all packages in my local cache
```

Error uploading file: conanmanifest.txt, 'b'''
Uploading tinyxml/2.6.2 to remote 'conan'                                       
Uploading conan_export.tgz -> tinyxml/2.6.2
ERROR:
Error uploading file: conan_export.tgz, 'b'''
Uploading conan_sources.tgz -> tinyxml/2.6.2
ERROR:
Error uploading file: conan_sources.tgz, 'b'''
Uploading conanfile.py -> tinyxml/2.6.2
ERROR:
Error uploading file: conanfile.py, 'b'''
Uploading conanmanifest.txt -> tinyxml/2.6.2

```
I'm using the default cache location
C:/users/xxx/.conan


How can I investigate this problem further? Is there a way to get a more detailed error message?

**Comment by memsharded** [comment]
A few questions:

- Can you share your ``conan.conf``? Also if you have any other kind of configuration via env-vars or something, please share
- In which platforms does this happen? Only Windows, right? Do the uploads work in other platforms?
- Can you reproduce the error in different Windows machines, or is it just in one specific machine?
- What happens if you do: ``conan new hello/0.1 -m=cmake_lib`` + ``conan create .`` + ``conan upload hello* ...``? Still the same?
- Which server are you using? Can you share your ``conan remote list``?
- Can you download packages from that server without issues?

**Comment by ghost** [comment]
Hey James,
thx for your feedback. 
I did some tests. Linux (WSL2) showed the same problem.
This was quite confusing. After a while I checked our Nexus settings. 
=>Turns out: Nexus hat a setting to forbid redeployment. After disabling this setting It worked

Thak you James again for your quick help

**Comment by memsharded** [comment]
> This was quite confusing. After a while I checked our Nexus settings.

Great, happy that you found the root cause, maybe you want to report them (Nexus) to improve the error message when this happens, instead of the empty one, that would have helped I guess. 

Thanks for following up and reporting the cause!
