### ISSUE TITLE
[question] Example for new CMakeDeps Generator with CMake Components

### ISSUE THREAD

**Issue by dotChris90** [conan-io/conan#10724]
Hello Conan team, 

i just was looking into your new CmakeDeps generator, which is  - as far as i understand - the only generator which will survive for conan 2.0 (or at least will be the preferred way of doing things). 

I like the new approach very much because now we no longer need to "inject" conan dependencies via a cmake file and so no longer touch existing projects. Great so far. ;) 

But now my question - with CMakeDeps i am able to include existing conan packages and can see even the targets / components of each package during the build. 

But now : is there an example how a package that just using CMakeDeps (and not cmake_find_package) shall package it's components? Where is the border between CMakeLists and Conanfile.py? I would like to understand in conan 2.0 what is responsiblity of the conanfile.py and what is responsibility of CMakeLists. Is the install(EXPORT) the prefered way? Is the FindABC.cmake file generated by conan and and the Abc-Targets.cmake file done by CMakeLists? 

**So to make it short : is there an example for new CMakeDeps and conan 2.0 with multiple components?**

**Comment by memsharded** [comment]
Hi @dotChris90 

> But now : is there an example how a package that just using CMakeDeps (and not cmake_find_package) shall package it's components? Where is the border between CMakeLists and Conanfile.py? I would like to understand in conan 2.0 what is responsiblity of the conanfile.py and what is responsibility of CMakeLists. Is the install(EXPORT) the prefered way? Is the FindABC.cmake file generated by conan and and the Abc-Targets.cmake file done by CMakeLists?

I am not sure what you mean. The definitions of the components is aimed to be independent of the consumer generator used by consumer. So the package that is creating several libraries and want to define components will define in its ``package_info()`` some ``self.cpp_info.components["mycomponent"]....``. You can find many of these in the ``conan-center-index`` repository containing all packages for ConanCenter, have you checked it? Also, the idea of this definition is that it is independent of the build-system used to build from sources. In fact you can define a package with components that you are just creating from some vendor pre-compiled closed source libraries. Then, the consumer decides which build system it wants to use, and the generators provide that information, irrespective of the build system used to build the dependency.

A different story is if you want to reuse directly the xxx-config.cmake files generated by your build. In that case, you could even leave your ``package_info()`` very empty, do not use ``CMakeDeps`` at all, and just by using ``CMakeToolchain`` to help locating the packages xxxx-config.cmake, it could work. Depending on your needs, this might be a valid approach. The main disadvantages are that it completely couples everything to cmake, there will be some cmake limitations (like for example not being able to manage multi-config environments, like Visual Studio that can change Debug/Release directly from the IDE, will not be possible).

**Comment by dotChris90** [comment]
Hello, 

In the conan-center the recipses always following the pattern 
   self.cpp_info.components[conan_component].names["cmake_find_package"] = compname 

So basically : mention the cmake_find_package generator - my question just was about "is this for the new CMakeDeps also required" like "component["abc"].names["CMakeDeps"] or no longer required? 

But let me try it out again - i though before i had an error "lib for target cannot be found" but will upload an example next time and ask here more precise. ;)

**Comment by memsharded** [comment]
Hi @dotChris90 

I understand a bit better now.
I think this sections of the help might be useful:
- https://docs.conan.io/en/latest/conan_v2.html#new-properties-model-for-the-cpp-info-in-conan-2-0-generators
- https://docs.conan.io/en/latest/migrating_to_2.0/properties.html#properties-migration

The main point is that the modern way to define custom target names is the ``.set_property("cmake_target_name", ...)``, if that is not defined the consumers ``CMakeDeps`` will not create the correct target names. It is very possible that a few of these properties are still missing in ConanCenter recipes too.

**Comment by dotChris90** [comment]
hey cool exactly this i was asking myself. 
And how in conan 2.0 it is planned to connect a library like let's say 'libabc.so" to a component? 
Is there a set_property mechanism for this? 

If it's under construction ^^ it's ok - i just saw there exist an alpha version of 2.0 and want to understand the 2.0 process and prefered way for package_info

**Comment by memsharded** [comment]
> And how in conan 2.0 it is planned to connect a library like let's say 'libabc.so" to a component?
Is there a set_property mechanism for this?

No, that is part of the core definition:
```python
self.cpp_info.components["mycomp"].libs = ["abc"]
```

The current "modern" mechanisms existing in latest 1.X will be good to migrate to 2.0.

**Comment by dotChris90** [comment]
ok just last question : 
I have created a new project with conan new and "-m cmake_lib" see https://github.com/dotChris90/CMakeDepsWithComponents/blob/main/conanfile.py

now i added a 2nd lib - so 2nd component in my cmake and added this new target to install area in CmakeLists. 

then i did in conanfile 

```
 def package_info(self):
        self.cpp_info.components["cde"].libs = ["cde"]
        self.cpp_info.components["fgh"].libs = ["fgh"]
```

but i get in test_package 

Library 'fgh' not found in package.  If 'fgh' is a system library, declare
  it with 'cpp_info.system_libs' property

Now stupid question - if i want to follow the default "generators approach" (this mean i dont have existing cmake files or Findcde files or whatever - so i do absolute do not need adjust my conanfile to cmake files and all i want is : tell other CMakeDeps generators my targets)  and i am fine with "cde::cde" and "cde::fgh" as targets. What i missing?

**Comment by memsharded** [comment]
Hi @dotChris90 

Yes, you are missing the directories. When defining components, there are no default includedirs, libdirs, etc, so they need to be declared:

```python
    def package_info(self):
        self.cpp_info.components["cde"].libs = ["cde"]
        self.cpp_info.components["cde"].libdirs = ["lib"]
        self.cpp_info.components["cde"].includedirs = ["include"]
        self.cpp_info.components["fgh"].libs = ["fgh"]
        self.cpp_info.components["fgh"].libdirs = ["lib"]
        self.cpp_info.components["fgh"].includedirs = ["include"]
```
With that I have been able to build your project (thanks very much for putting together the repo, that really helps to try things and understand what is failing).

**Comment by dotChris90** [comment]
@memsharded  

thanks for your help here - yes it totally works now! awesome! It's so simple and logical if you know it .... 
I though before that cmake_layout already handle this also for components because was mentioned here --> https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake_layout.html?highlight=libdirs
But you are right - why it should? each component can have it's own sub directories and own include directories and all. so it's just logical to define this folders for each component. 

I will close the ticket in 1,2 days - just 1 small last question - is there an example in documentation and i just didn't see it? or you guys think it could be beneficial that the cmake_lib template (for conan new command) could have 2 targets instead of just 1? just was a general question. it's up to you I now know what i did wrong :) 

And should this be done in package_info or layout method? 

thanks a lot!!!! to be honest - awesome easy if you know how it to do.

**Comment by memsharded** [comment]
> thanks for your help here - yes it totally works now! awesome! It's so simple and logical if you know it ....

Yeah, the thing is that the documentation at this stage is not great, it has accumulated some legacy over the years, and is mixing the legacy and the modern features. We are working hard for better docs in 2.0.

> But you are right - why it should? each component can have it's own sub directories and own include directories and all. so it's just logical to define this folders for each component.

Yes, that is totally the design criteria why components don't default dirs, because it is likely/expected that they can have different dirs.

> I will close the ticket in 1,2 days - just 1 small last question - is there an example in documentation and i just didn't see it? or you guys think it could be beneficial that the cmake_lib template (for conan new command) could have 2 targets instead of just 1? just was a general question. it's up to you I now know what i did wrong :)

I'd say that we want to keep that template relatively simple as it is. Then maybe we want to add other templates, like ``cmake_lib_components``, or just better docs/examples (part of the effort in 2.0 docs are better full examples).

> And should this be done in package_info or layout method?

While possible in the ``package_info()``, in the ``layout()`` method might be better for supporting other cases like ``editable`` packages.

> thanks a lot!!!! to be honest - awesome easy if you know how it to do.

Yes, that is our fault, hopefully the effort in 2.0 docs will pay off.

Thanks for all the feedback!

**Comment by dotChris90** [comment]
i close the issue because resolved. thanks again.
