### ISSUE TITLE
[bug] self.copy : PermissionDenied copying symlinks on Windows

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10726]
from https://github.com/conan-io/conan-center-index/issues/9633

NOTE : it needs so called `Developer Mode` to be enabled as exaplined here: https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/, in order to get symbolic links creation available for non-admin

### Environment Details (include every applicable attribute)
  * Operating System+version: `Windows 10 21H1 19043.1526`
  * Compiler+version: `Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30706 for x86`
  * Conan version: `conan 1.45.0`
  * Python version: `Python 3.9.7`

### Steps to reproduce (Include if Applicable)

run:
```
$ conan install meson/0.60.2@ --build meson
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: Traceback (most recent call last):
  File "c:\conan\conan\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "c:\conan\conan\conans\client\conanfile\package.py", line 52, in _call_package
    conanfile.package()
  File "C:\Users\sse4\.conan\data\meson\0.60.2\_\_\export\conanfile.py", line 46, in package
    self.copy(pattern="*", dst="bin", src=self._source_subfolder)
  File "c:\conan\conan\conans\client\file_copier.py", line 84, in __call__
    fs = self._copy(src_folder, pattern, src, dst, links, ignore_case, excludes,
  File "c:\conan\conan\conans\client\file_copier.py", line 103, in _copy
    copied_files = self._copy_files(files_to_copy, src, dst, keep_path, symlinks)
  File "c:\conan\conan\conans\client\file_copier.py", line 240, in _copy_files
    shutil.copy2(abs_src_name, abs_dst_name)
  File "C:\Users\sse4\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 443, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\sse4\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sse4\\.conan\\data\\meson\\0.60.2\\_\\_\\source\\source_subfolder\\test cases\\frameworks\\35 boost symlinks\\boost\\include\\boost'
```

broken link looks like:
```
03/07/2022  02:12 AM    <SYMLINKD>     boost [../Cellar/boost/0.3.0/include/boost]   
```

might be related to https://bugs.python.org/issue13702

**Comment by memsharded** [comment]
> NOTE : it needs so called Developer Mode to be enabled as exaplined here

What can Conan do here? If this mode needs to be enabled, then there is little we can do, right? Isn't it possible to tweak the Meson recipe so it doesn't require symlinks? Why the test cases would be relevant (``test cases\\frameworks\\35 boost symlinks\\boost\\include\\boost``, maybe the tests could be excluded?

**Comment by SSE4** [comment]
I don't know, maybe nothing. maybe it should skip these broken symlinks, or maybe fix them.
meson is very first recipe where I have seen this issue. and luckily, they are not essential, and can be safely ignored/removed.
but if there are other packages that suffer from that issue, and they actually need these symlinks to work, it's definetely something to be addressed.
