### ISSUE TITLE
[question] How to differentiate the command used to call `package()` method (`create`/`export-pkg`)?

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#10720]
Based on answer of #10682

Is there any way for `package()` method to determine whether it's called from `conan create` or `conan export-pkg`? 

I have a case where I seek to use _one recipe file_ to do two functions:
1. Build the code, and package both the source and the binaries. This is the case when called by `conan create`.
2. Only package the source and binaries _directly_ from the directory containing the binaries, _without build_. This is the case when called by `conan export-pkg`.

As far as I understand:
- When using `conan create`: package will `self.copy` from conan build binary folder.
- When using  `conan export-pkg`: package will `self.copy` from the project directory (host context).

Apart from the complicated code in the recipe to handle that, is there any way to differentiate between them in the `package()` method, so _`package()` method decides where to get the files from (conan build/host project)_?

Of course the simpler solution is to have two recipes, one for each case. But what if I "wish" to have both in one recipe?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Bassem-Ramzy 

Could you clarify? With the new layouts, the idea is that the same ``package()`` method is valid for both cases:
```bash
$ conan new hello/0.1 -m=cmake_lib
$ conan create . # works
$ conan install .
$ conan build .
$ conan export-pkg . # Also works and package correctly
```

Note: The "host" context is Conan terminology is not the same as the "local" user folders, if that is what you meant.

**Comment by Bassem-Ramzy** [comment]
You are right, by "host" I mean "local" user folders.

I actually want to support the case when I do **`conan export-pkg` only**, without calling neither `conan create` nor `conan build` previously. So, it exports the files from my local directory, that have been built using another tool.

As, when I do:
```CMD
$ conan new hello/0.1 -m=cmake_lib
$ conan export-pkg .
```
I get, 
```CMD
ERROR: 
	FileNotFoundError: [Errno 2] No such file or directory: '/home/bassem/Documents/T1/cmake-build-release'
```
Which makes sense, since I haven't called neigther `create` nor `build`.

What I need to do is:
1. Using my recipe on "my/local/folder":
```CMD
$ conan create .
$ conan export-pkg .
```
Here, `package()` method exports the binaries from ".conan/data/folders".
2. The other scenario I need the same recipe to support:
```CMD
$ cd my/local/folder
$ my-custom-build-command
$ conan export-pkg .
```
Here, `package()` should be aware it's called without previous call to `create/build`, accordingly, it exports the binaries from "my/local/folder" instead.

So, the question is: can `package()`/the recipe differentiate between the two cases, and accordingly decide which folder to get the files from? 

Thanks,

**Comment by memsharded** [comment]
> I actually want to support the case when I do conan export-pkg only, without calling neither conan create nor conan build previously. So, it exports the files from my local directory, that have been built using another tool.

This is indeed very doable, and the main use case of ``export-pkg``.

> $ conan create .
$ conan export-pkg .

This doesn't make much sense. The ``conan create`` builds the package in the cache directly, it is not necessary/doesn't make sense to do an ``export-pkg`` after a create. Did you mean a ``conan install`` + ``conan build`` + ``conan export-pkg``?

I am missing something here.

It is possible to encode the relative layout of the binaries you want to package for different platforms in the ``package()`` method, so you can use the ``package()`` method for building in the cache for some platform, example, Windows, and for others to do an ``export_pkg()``:

```python
def package(self):
     if self.settings.os == "Windows":
          # this is a regular cache build, with build(), etc
          cmake = CMake(self)
          cmake.install()
     else: # other platforms are export-pkg
          # lets say that you have the binaries in "linux/armv8", "Macos/x86_64" folders
          copy(self, "*", src="{}/{}".format(self.settings.os, self.settings.arch), ...)
```

Likewise, I think you might be able to define your own ``conf`` and use it:
```python
def package(self):
      if self.conf.get("user.mycompany.packaging:export-pkg"):
             # code for export-pkg
      else:
             # normal code for build() in local cache
```
then something like ``conan .... -c user.mycompany.packaging:export-pkg=1``

You might also want to explore, if you haven't yet, the definition of the ``layout()`` method, specifically where the ``self.folders.build`` and ``self.cpp.build``, those encode where the things are found, in the local user folders.

**Comment by Bassem-Ramzy** [comment]
Thanks James for the various solutions. 
I will check my model accordingly.

**Comment by memsharded** [comment]
Great, do not hesitate to re-open or submit a new issue if you have any further question deriving from those hints.
