### ISSUE TITLE
[bug] Dependencies in recipe self.deps_cpp_info not available at generate() time

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#10735]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.15.7
  * Compiler+version: n/a
  * Conan version: 1.45.0
  * Python version: 3.9

### Goal
Similar to issue comment https://github.com/conan-io/conan/issues/10304#issuecomment-1009722203 I also need the dependency information available at `generate()` time such that I can correctly initialise the `CMakeToolchain` generator using **meta info from the dependency**, e.g. something like this:
```
generate(self):
  ...
  target_name = self.deps_cpp_info[<dep>].components[<component>].names["cmake_target_name"]
  tc = CMakeToolchain(self)
  tc.variables["<dep>_TARGET_NAME"] = target_name
  ...
```

and use that set variable from the `CMakeToolchain` in my `CMakeLists.txt` file, e.g. in this case, such that I am always going to use the correct target name from my dependency when I am trying to link to it.

### Steps to reproduce (Include if Applicable)

Use recipe and profile below and call command in terminal:
`conan install . -if=build-debug -pr:h default -pr:h test_deps.profile -pr:b default`

You will see output of `self.deps_cpp_info` having zero elements:
```
conanfile.py: self.deps_cpp_info [0]: odict_items([])
```

`conanfile.py`
```python
from conans import ConanFile

class DependenciesCheck(ConanFile):

    def validate(self):
        self.output.info(f"Running validate...")
        self.output.info(f"self.dependencies [{len(self.dependencies.items())}]: {self.dependencies}")
        for require, dependency in self.dependencies.items():
            self.output.info("Dependency is direct={}: {}".format(require.direct, dependency.ref))

    def generate(self):
        self.output.info("Running generate...")
        self.output.info(f"self.dependencies [{len(self.dependencies.items())}]: {self.dependencies}")
        for require, dependency in self.dependencies.items():
            self.output.info("Dependency is direct={}: {}".format(require.direct, dependency.ref))

        self.output.info(f"self.deps_cpp_info [{len(self.deps_cpp_info.dependencies)}]: {self.deps_cpp_info.dependencies}")
        for name, dep in self.deps_cpp_info.dependencies:
            self.output.info("Dependency {}: {}".format(name, dep))

```
`test_deps.profile`
```
[settings]
[options]
[build_requires]
cmake/3.19.4
gtest/1.11.0#a35bd6be75af15855a7c8c861888cd90
benchmark/1.6.0#abc2853305ae1834eb47ccb84a715c81
[env]
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
conan install . -if=build-debug -pr:h default -pr:h test_deps.profile -pr:b default
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
*: cmake/3.19.4, gtest/1.11.0, benchmark/1.6.0
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

conanfile.py: Running validate...
conanfile.py: self.dependencies [0]: <conans.model.dependencies.ConanFileDependencies object at 0x10379e560>
conanfile.py: Installing package
Requirements
Packages
Build requirements
    benchmark/1.6.0 from 'conancenter' - Cache
    cmake/3.19.4 from 'conancenter' - Cache
    gtest/1.11.0 from 'conancenter' - Cache
    openssl/1.1.1k from 'conancenter' - Cache
Build requirements packages
    benchmark/1.6.0:2f7a9fc6a21fda7cdeaab303f436ee769d8e964c - Cache
    cmake/3.19.4:cf36af68367ac960cc1360ef3ea3c735fa475414 - Cache
    gtest/1.11.0:9e8e90672d7a216fdaac8d6a37a0bbd4a25f56a6 - Cache
    openssl/1.1.1k:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Cache

Installing (downloading, building) binaries...
benchmark/1.6.0: Already installed!
gtest/1.11.0: Already installed!
openssl/1.1.1k: Already installed!
cmake/3.19.4: Already installed!
cmake/3.19.4: Appending PATH environment variable: /Users/ssnyder/Development/ConanData_1450_ConanBase_090/cmake/3.19.4/_/_/package/cf36af68367ac960cc1360ef3ea3c735fa475414/bin
conanfile.py: Applying build-requirement: cmake/3.19.4
conanfile.py: Applying build-requirement: gtest/1.11.0
conanfile.py: Applying build-requirement: benchmark/1.6.0
conanfile.py: Applying build-requirement: openssl/1.1.1k
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Calling generate()
conanfile.py: Running generate...
conanfile.py: self.dependencies [4]: <conans.model.dependencies.ConanFileDependencies object at 0x103825930>
conanfile.py: Dependency is direct=True: cmake/3.19.4
conanfile.py: Dependency is direct=True: gtest/1.11.0
conanfile.py: Dependency is direct=True: benchmark/1.6.0
conanfile.py: Dependency is direct=False: openssl/1.1.1k
conanfile.py: self.deps_cpp_info [0]: odict_items([])
conanfile.py: Aggregating env generators
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
```

**Comment by memsharded** [comment]
This is totally expected. The ``generate()`` will only support the new ``self.dependencies`` access to dependencies. The ``self.deps_cpp_info`` has already been removed in 2.0, as it has some problems, one of them is that it evaluates later in the process, and is way more limited than ``self.dependencies``

**Comment by SeanSnyders** [comment]
Ok, so how to obtain meta data (as given in my example in the original post) from dependencies that are now mandated to be set for generators like `CMakeToolchain` and `CMakeDeps` ?

**Comment by memsharded** [comment]
I am not sure what are you trying to accomplish with:

```
target_name = self.deps_cpp_info[<dep>].components[<component>].names["cmake_target_name"]
  tc = CMakeToolchain(self)
  tc.variables["<dep>_TARGET_NAME"] = target_name
```
Why do you need to do that? Why not using the ``CMakeDeps`` generator? For most cases you wouldn't need to pass anything to ``CMakeToolchain``. The goal of ``CMakeToolchain`` is not to manage information of dependencies, that is the goal of ``CMakeDeps``. ``CMakeToolchain`` is mostly designed to map the current settings/options/project configuration to CMake.


In any case, you have examples in the docs of ``self.dependencies``: https://docs.conan.io/en/latest/reference/conanfile/dependencies.html

```python
def generate(self):
    cpp_info = self.dependencies["mydep"].cpp_info
    cpp_info.includedirs
    cpp_info.libdirs

    cpp_info.components["mycomp"].includedirs
    cpp_info.components["mycomp"].libdirs
```

**Comment by SeanSnyders** [comment]
I am using *experimental* `CMakeDeps` and `CMakeToolchain` to accomplish practical usage of Conan somewhere in no-mans land in-between legacy Conan 1 and new-and-unstable Conan 2.

I have in `CMakeLists.txt` the following (using `CMakeDeps` to generate me the Conan-CMake helper files for defining targets, etc):
```
....
find_package(${DEP_TARGET_NAME} CONFIG REQUIRED)
....
...
if(TARGET ${DEP_TARGET_NAME})
        target_link_libraries("${EXE_NAME}" ${DEP_TARGET_NAME})
```

Now due to circumstances somewhere via bugs in Conan 1.42 and where the target names where not correctly set, capitalisation were incorrect and platform dependent, in conjunction with ConanCenter upgrading recipes to support the latest Conan version and thus breaking/not working with older versions of Conan for these specific issues,
I am trying to insulate projects from this again whilst using latest Conan 1.45.0.

So instead of me hardcoding the target name of the dependency in the `target_link_libraries()` CMake function - which might be stable *for now*, I thought I can rather use the variable coming from the Conan recipe of the dependency due to the recipe creator having to set it in its `package_info()` for the _new-skool_`CMakeDeps` and `CMakeToolchain` generators.

**Comment by memsharded** [comment]
Understood. Then you might want to access things something like: ``self.dependencies["mydep"].cpp_info.components["mycomp"].get_property("cmake_target_name")``

**Comment by SeanSnyders** [comment]
Ok, I think that route can work, but not through the accessor syntax you provided.

One cannot access `self.dependencies["mydep"]` directly. The dict accessor is not working for that as the underlying keys are dicts themselves representing `conans.model.dependencies.Requirement` objects.
There is a `self.dependencies.get()` method, but this does not work as it constructs a default `Requirement` object that does not match anything in the dict. There seems no 'search' / 'matching' functionality, even though there seems to be something like that implemented via `UserRequirementsDict.filter()` and used through`UserRequirementsDict._get_require()` and on top layer by `UserRequirementsDict.get()`
But then, I see nowhere in Conan codebase the use of `self.dependencies.get()`. So not sure that this code-path is actually working. No tests.

**---EDITED---**

What I got to work is this:
```
        dep_filter = lambda dep_items, req_name: list([k[1] for k in dep_items if req_name in k[0].ref.name])
        result = dep_filter(self.dependencies.items(), "mydep")
        assert(len(result) == 1)
        
        dep = result[0]
        dep_cmake_target_name = dep.cpp_info.get_property("cmake_target_name")
        self.output.info(f"dep_cmake_target_name: {dep_cmake_target_name}")
```

Is there a better way I am not aware of....?

**Comment by memsharded** [comment]
Sorry @SeanSnyders this was not followed up back then.

> One cannot access self.dependencies["mydep"] directly.`

The ``self.dependencies["mydep"]`` syntax is thoroughly used in Conan and extensively covered in our test suite. So we would like to have some reproducible example that illustrate what you mean. If this is no longer an issue, please let us know, many thanks!

**Comment by memsharded** [comment]
Closing as stale
