### ISSUE TITLE
[question] Why does the meson build helper still use arch_build?

### ISSUE THREAD

**Issue by avetiso** [conan-io/conan#10733]
Conan version: 1.45.0.
OS: MacOS 12.2.1 ARM
Meson version: 0.61.2

If I've understood correctly, arch_build is not used in cross-compiling since 1.24.

Here's some output from attempts to cross compile a very simple base64 encoder/decoder (when cross compiling meson it runs the build twice, not quite sure why):

First build:
```
Configuration:
[settings]
arch=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os.version=10.12
os_build=Macos
[options]
[build_requires]
[env]
```

Second build:
```
[settings]
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=iOS
os.version=11.0
os_build=Macos
[options]
[build_requires]
[env]
```

Repro steps: kick off a cross-build using the meson helper by providing a cross file as an arg to meson.configure().

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Recipes must use the new integrations in https://docs.conan.io/en/latest/reference/conanfile/tools.html

The legacy integrations cannot remove support for ``arch_build``, because Conan has the committement to not breaking, code that was working in a previous release shouldn't break in a new release. 

Also the best way to start trying the new integrations is with a template, like ``conan new hello/0.1 --template=meson_lib``

**Comment by avetiso** [comment]
> Recipes must use the new integrations in https://docs.conan.io/en/latest/reference/conanfile/tools.html
> 
> The legacy integrations cannot remove support for `arch_build`, because Conan has the committement to not breaking, code that was working in a previous release shouldn't break in a new release.
> 
> Also the best way to start trying the new integrations is with a template, like `conan new hello/0.1 --template=meson_lib`

Does this there will not be a meson integration where cross compilation can be done using the 1.24+ method of doing it where arch_build is not present? 

FWIW, I run into the same problem even with the templated meson_lib conanfile. One the second pass, there is no "arch", there is only "arch_build" and you run into this:

```
Configuration:
[settings]
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=iOS
os.version=11.0
os_build=Macos
[options]
[build_requires]
[env]

ERROR: base64/1.0.0-5@mx/stable: 'settings.arch' value not defined
conan create . mx/stable -u -pr ios-debug -s os.version=11.0 -s compiler.version=13.0
Error: Command returned pid 51664 exit 1
```

Pardon my cluelessness, I just don't see how I'm suppose to cross-compile and process the same conanfile twice when in the first pass we use `arch` and the second time it uses `arch build`. Are you aware of any projects or examples where this is exercised?

**Comment by memsharded** [comment]
> Does this there will not be a meson integration where cross compilation can be done using the 1.24+ method of doing it where arch_build is not present?

Not sure I follow. All the new integrations will not use ``arch_build`` at all, but they will use the build & host profiles (like ``--profile:build=mybuildprofile  --profile:host=myhostprofile``). You can completely drop the ``arch_build``, don't use it in recipes, don't define it in profiles, it shouldn't be used at all.

**Comment by avetiso** [comment]
> > Does this there will not be a meson integration where cross compilation can be done using the 1.24+ method of doing it where arch_build is not present?
> 
> Not sure I follow. All the new integrations will not use `arch_build` at all, but they will use the build & host profiles (like `--profile:build=mybuildprofile --profile:host=myhostprofile`). You can completely drop the `arch_build`, don't use it in recipes, don't define it in profiles, it shouldn't be used at all.

Was just about to reply, but I chatted with an engineer here who set up a lot of our conan infra and he explained to me the source of my error. I appreciate your time! I'll close this out.
