### ISSUE TITLE
[question] Multiple Binary Artifacts For Same Revision

### ISSUE THREAD

**Issue by anderson-dev** [conan-io/conan#10748]
I used to be able to call `conan export-pkg` once for a `Release` artifact and then `conan export-pkg -s build_type=Debug` for a `Debug` artifact. This would export pre-built binaries for both `Debug` and `Release` configurations for my consumers. After I recently enabled revisions support, each call now creates a new revision resulting in only one pre-built artifact being consumable at a time.

How would I now export N binary artifacts for the same package recipe after enabling revision support?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> recently enabled revisions support, each call now creates a new revision resulting in only one pre-built artifact being consumable at a time.

In theory, if nothing differently was exported in the recipe, the recipe revision should be the same, and you should be able to create the 2 different binaries for that same recipe revision. There might something in the recipe that is changing the exported recipe revision,  it would be necessary to see the recipe and have something that we can reproduce to know.

**Comment by anderson-dev** [comment]
Maybe due to my using version range syntax in the recipe?:

```
from conans import ConanFile, MSBuild, tools
from conans.errors import ConanInvalidConfiguration

class ConanPackageInfo(ConanFile):
    name = "xmpp-msbuild"
    url = 'https://gitea.xenonet.com/edot/xmpp-msbuild.git'
    description = "No Description"
    license = ""
    settings = "os", "compiler", "build_type", "arch"
    generators = "visual_studio"
    default_sources = "x64/Debug/.conan/conanbuildinfo.props", "x64/Release/.conan/conanbuildinfo.props"
    exports_sources = default_sources + ("ProxyClientWrapper/*", "Tests/*", "Xmpp.sln")
    default_options = {"catch2:with_main": True, "boost:shared": True, "qt:shared": True}
    default_user = "aflorence"
    default_channel = "stable"

    def build_requirements(self):
        self.test_requires("catch2/[>2.0.0 <3.0.0]")

    # Required Packages (https://conan.io/center/)
    def requirements(self):
        self.requires("boost/1.77.0")
        self.requires("qt/5.15.2")
        self.requires(f"core/[<2, include_prerelease={self.channel == 'testing'}]@{self.user}/{self.channel}")

    def imports(self):
        self.copy("*.dll", dst="..", src="bin")
        self.copy("*.dylib*", dst="..", src="lib")

    def build(self):
        raise ConanInvalidConfiguration("Only manual builds from VS currently")
        msbuild = MSBuild(self)
        msbuild.build("xmpp-msbuild.sln", upgrade_project=False, use_env=False, verbosity="normal")
        
    def package(self):
        self.copy("*.h", dst="include", src="ProxyClientWrapper/include")
        self.copy("*.h", dst="include", src="vendor-qxmpp/src/base")
        self.copy("*.h", dst="include", src="vendor-qxmpp/src/client")
        self.copy("*.h", dst="include", src="vendor-qxmpp/src/server")
        self.copy("*.h", dst="include", src="vendor-qxmpp/build/src/base")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*/ProxyClientWrapper.pdb", dst="lib", keep_path=False)
        self.copy("*/qxmpp.pdb", dst="lib", keep_path=False)
        self.copy("*/ProxyClientWrapper.dll", dst="bin", keep_path=False)
        self.copy("*/qxmpp.dll", dst="bin", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

**Comment by memsharded** [comment]
It seems that you are exporting a different thing each time. The key might be:
```python
 default_sources = "x64/Debug/.conan/conanbuildinfo.props", "x64/Release/.conan/conanbuildinfo.props"
 exports_sources = default_sources + ("ProxyClientWrapper/*", "Tests/*", "Xmpp.sln")
```

If you don't do the ``conan install`` for the 2 configuration first, the first time it will only export one .props file, while the second time it will export 2 .props file. The final exported recipe is different and consequently it will have a different revision. In all effects, it is the same as having different source code. You can see what is being exported and what is the difference by comparing the different ``export/conanmanifest.txt`` file in your Conan cache after the export.

More importantly, exporting the .props file is an anti-pattern and bad practice. The generated files are temporary, they are generated on the fly when necessary as defined by the Conan generators. They are specific to a given machine and are not relocatable to other machines, or to other locations and as such, cannot and shouldn't be packaged.

Also, you shouldn't be mixing the legacy ``MSBuild`` with ``MSBuildToolchain``, but using the ``from conan.tools.microsoft import MSBuild`` one.

**Comment by anderson-dev** [comment]
In interest of feedback and to help those that are new to using Conan for a MSBuild/MSVC based shop:

Unfortunately, the exporting of conanbuildinfo.props was sort of a chicken or egg problem. Way back in July 2021 I recognized a potential [issue ](https://github.com/conan-io/conan/issues/9330) where the VS Conan extension that I'd introduced to my devs generated and expected `conanbuildinfo.props` to be in the `x64/$(BuildConfig)/.conan` folder.

If the transient files were not committed to the repo, people cloning the repo would see the project not load and when regenerating them via the Conan VS extension, it would add a duplicate import statement resulting in a compile time warning that it was trying to import the same file multiple times. In order to address the compiler warning I had to commit these "transient" files to the repo to avoid confusion on the part of my team. This resulted in more confusion seeing the file change and git wanting to track those changes all the time but it was better than the difficult to explain the mounting compiler warnings.

I then ran into issues where devs could only use pre-built binaries as the builds from recipe would fail finding `x64/$(BuildConfig)/.conan/conanbuildinfo.props`. My CI system worked because I made use of the `--install-folder` option but the build=missing policy for dependent MSBuild packages always generated the `conanbuildinfo.props` file in the root where the VS Conan extension and msbuild did not see it. This is why I started needing to export the file to sources so builds would work.

It seemed to work for a while but then certain projects, especially those using shared dlls, would start failing leading to the next [issue](https://github.com/conan-io/conan/issues/10636). When conan attempted to build the recipe it placed its generated `conanbuildinfo.props` file at the root where the project could not see it resulting in having to convert to the "experimental" Conan 2.0 MSBuild integrations and the new `layout(self)` method recommended in the previously mentioned issue.

At this point I've instructed my dev team to uninstall and discontinue using the VS Conan extension as it is seems entirely incompatible with Conan proper and have developed custom make scripts to help them do installs properly and will be converting all our projects to the new Conan 2.0 MSBuild integrations very soon. This has been a very painful onboarding, but after many months of research, testing, going back to the drawing board, and a lot of help here and there from @memsharded I've finally achieved a fully working Conan MSBuild integration. Hopefully this feedback and journey can be of help to those MSVC shops that are interested in Conan. It is very capable and I love it but, at least with Conan 1.x, it really didn't guide me to the correct implementation path mostly because of the conflict between Conan and the Conan VS extension.

**Comment by anderson-dev** [comment]
Thanks I was able to copy the resulting export/conanmanifest.txt and compare against each other. This revealed that `exports_sources = "ProxyClientWrapper/*"` was picking up the intermediate build folder for that project (i.e. MyProject/x64/Debug/* and MyProject/x64/Release/*). Obviously that build folder contained different files depending on build config so I am now having to be very specific and do 
```
exports_sources = "ProxyClientWrapper.vcxproj",
        "ProxyClientWrapper/src", 
        "ProxyClientWrapper/include", 
        "ProxyClientWrapper/doc"
```

The multiple artifacts for the same recipe capability is now restored.

@memsharded Thanks for all your help to set me straight. I've discussed my dilemma with your mentioned anti-pattern of exporting `conanbuildinfo.props` to sources in the previous reply if interested in how I was led down that path. I'll be converting everything to the new Conan 2.0 MSBuild integrations using the `vs_layout` helper soon and I believe I'll finally be on a correct path going forward.

**Comment by memsharded** [comment]
Hi @anderson-dev 

Now I understand better where you come from, and the issues generated from the VS extension.

It is totally true that we haven't been able to keep maintaining and improving that extension, it seems it never got a lot of usage so it was de-prioritized and 2.0 is now taking most of the efforts, and we cannot put time in the VS extension at this moment. Work on it will probably resume some time after 2.0, but I think your decision right now is the best one, certainly with those scripts you will have more control, things will be more explicit and debuggable in case something doesn't work.

Also, the new tooling MSBuildDeps/Toolchain, is better architectured and more flexible and powerful, but there might be still a couple of rough edges until fully stabilized. For example, we are changing the ``vs_layout()`` in https://github.com/conan-io/conan/pull/10760, for next 1.47 release, while adding extra testing for a new ``conan new --template=msbuild_lib`` that can help a lot to debug and understand issues we realized that ``vs_layout()`` could be improved. Please keep an eye on 1.47 and future releases, and keep the feedback coming! 

Happy to know that you managed to get your binaries under the same revision again.
Thanks very much for all the feedback!
