### ISSUE TITLE
[feature] 2.0 Custom commands layers

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10741]
The custom commands might be namespaced if they exist in different folders under the `extensions/command` folder. For example, if I do a `conan config install`, being "jfrog" a company name and "conancom" a community around the Conan project, and install two folders: `extensions/command/jfrog` and `extensions/command/conancom`, the commands would look like:

`conan jfrog:foo -arg --args2` and `conan conancom:bar -arg --args2`

**Comment by czoido** [comment]
Closed by: https://github.com/conan-io/conan/pull/10739
