### ISSUE TITLE
[question] Why does 'conan source' calls the export() method?

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#10758]
Hi,

I've observed that the `export()` method of my recipe is called when I run `conan source` for package development flow.
I'm a little bit confused why this is the case? I would have expected that the `source()` method is called, but I wonder why the `export()` method is called too. I'm using `self.copy` there and it now copies files to the source folder which does not make sense for me.

Maybe you are able to shed some light on this as I'm interested in the reason for this behaviour?

Many thanks for clarification.
Markus

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This is some legacy.

If you define the ``layout()`` method, the ``conan source`` will not do it. It will do the ``export_source()`` method though, that couldn't be removed yet, in 1.X.

Conan 2.0 has already removed this, the ``conan source`` command will not do absolutely anything regarding exports.

**Comment by gpxricky** [comment]
Okay, thanks for clarification ;).
