### ISSUE TITLE
[bug] 2.0 Verify that "conan test" is creating the `test_output` folder

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10754]
The same as "conan create" that creates a "test_output" folder inside the "test_package", looks like "conan test" creates a "build" one. Tested on windows with latest develop2

**Comment by memsharded** [comment]
But Conan 1.X does not create the ``test_output`` folder, even for ``conan create``.
The ``test_output`` has been introduced only in Conan 2.0, not 1.X. Should we backport this feature? Seems not trivial.

**Comment by lasote** [comment]
Wrong milestone. I saw this behavior in 2.0 (unless I was mistaken)

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/10795
