### ISSUE TITLE
[question] Is it possible to integrate Conan package with a non-Conan one?

### ISSUE THREAD

**Issue by gouriano** [conan-io/conan#10761]
Hello,
Let us say my Conan package optionally can use non-Conan one - which is absent in Conan (eg, CMake one), but present on my local system.
The price - rebuilding my package locally - is not too high.
The question though is how to integrate them so that Conan would "understand" that my package now uses something else?
Is it at all possible?

**Comment by memsharded** [comment]
Hi @gouriano 

Yes, it is possible, there are several approaches:

- Conan has the ``system_requirements()`` method in case you want Conan to call a system package manager, to install things in the system.
- You can create a "proxy" system recipe, that doesn't contain anything, but just models the system installed package. There are a few of them in ConanCenter, you can check for example the "opengl/system" or the "x11/system" packages in ConanCenter.

The second approach is necessary if you want some explicit modeling in Conan, and Conan knowing that dependency exists. The first one is a bit simpler and more pragmatic. In any case, what you should take into account is not to merge, it is not possible to use both the "openssl" system package and an actual openssl/version Conan package.

**Comment by gouriano** [comment]
Thank you, it helps.
Just... there is no "openssl/system", right?
I am looking [here](https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/config.yml)
(it would be nice to have one)

**Comment by memsharded** [comment]
No, there isnt, there is a real openssl one, with its version. Once there is a real package in ConanCenter, it doesn't make sense to use a proxy one, because it cannot and it will not be used. This is related to the caution mentioned above: it is not possible to mix the Conan package and the system package, that will create duplicate symbols or other issues. So all other packages in ConanCenter use the ConanCenter real openssl package.

**Comment by memsharded** [comment]
Closing this ticket as responded back then.

As extra info, Conan 2 now has other features like the ``[replace_requires]`` that allows to globally opt-in/opt-out certain dependencies, and injecting system wrapper recipes to replace the regular ones if necessary (like in some sysroot cases).

Please create new tickets for any further question, thanks for your feedback.
