### ISSUE TITLE
[bug] Cannot use `qt6_wrap_cpp` and `qt6_wrap_ui` after installing Qt with `CMakeDeps`.

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#10769]
# Problem Description

I want to use [`qt6_wrap_cpp`](https://doc.qt.io/qt-6/qt-wrap-cpp.html) and [`qt6_wrap_ui`](https://doc.qt.io/qt-6/qt-wrap-ui.html) commands provided by Qt in `CMakeLists.txt`. However, the output shows the following error:

```bash
Unknown CMake command "qt6_wrap_cpp".
```

**PLUS:** The reason why I try to use `qt6_wrap_cpp` and `qt6_wrap_ui` is because I cannot use `set(CMAKE_AUTOMOC on)` and `set(CMAKE_AUTOUIC on)`. Even though I use it, the output still shows the following warning:

```bash
CMake Warning (dev) in source/QtProjectTest/CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target QtProjectTest.  AUTOMOC,
  AUTOUIC and AUTORCC disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

If the above two are bugs when using Conan generator, `CMakeDeps`, to install Qt, can Conan fix them?

# My Try: Search in install directory

I looked for the install directory of Qt, `C:\.conan\179b29\1`, and then I **indeed** found what I want in its install directory.

- For `qt6_wrap_cpp`, I found it in `Qt6CoreMacros.cmake` about 188~231 line.

  ```bash
  C:\.conan\179b29\1\lib\cmake\Qt6Core\Qt6CoreMacros.cmake
  ```

- For `qt6_wrap_ui`, I found it in `Qt6WidgetsMacros.cmake` about 44~69 line.

  ```bash
  C:\.conan\179b29\1\lib\cmake\Qt6Widgets\Qt6WidgetsMacros.cmake
  ```

However, I still cannot use those Qt-specific CMake commands when using the <font color="red">**Qt installed by Conan**</font>. I've tried the same configuration with the <font color="red">**Qt installed by Qt Official Installer**</font>, it worked successfully, though.

# My Try: add `COMPONENTS Core`

According to the Qt Online Documentation of [`qt6_wrap_cpp`](https://doc.qt.io/qt-6/qt-wrap-cpp.html), this command is defined in the `Core` component of the `Qt6` package. However, even though I add `COMPONENTS Core` in `find_package()`, it didn't work, either.

```cmake
find_package(qt CONFIG COMPONENTS Core REQURIED)
```

# Screenshots

![img1](https://user-images.githubusercontent.com/71438617/158164507-b9853c11-fdb2-4011-b7e4-d0ab5a36740e.png)
![img2](https://user-images.githubusercontent.com/71438617/158164511-77e5f831-29aa-4f3d-8cff-9a7cbfd4404a.png)
![img3](https://user-images.githubusercontent.com/71438617/158164514-bb959a66-d93d-436c-a5c0-45eb0aaeff8f.png)
![img4](https://user-images.githubusercontent.com/71438617/158164502-28a25866-20d6-4fc0-848a-01df48b19dc2.png)

# Here is my example code

[CMakeDeps-qt.zip](https://github.com/conan-io/conan/files/8244375/CMakeDeps-qt.zip)

# Platform and Version

- **VSCode**: 1.65.2
- **CMake Tools**: 1.9.2
- **CMake**: 3.21.2
- **Conan**: 1.45.0
- **Conan CMake**: develop

**Comment by memsharded** [comment]
This is complicated to know what is happening with the ``cmake-conan`` stuff. I would recommend starting by checking:

- That the ``xxxx-config.cmake`` files are generated locally (actually there should be a bunch of them, one for every dependency)
- Check that the generated ``.cmake`` files contain the include to the corresponding ``xxxMacros.cmake`` file (the ones that you located in the cache)
- Check that the ```xxxx-config.cmake`` is the one actually being used when building and that it is not picking another one found elsewhere (in the cmake, in the system, in another Qt installation in your computer, etc)

**Comment by hwhsu1231** [comment]
@memsharded , what else information do I need to provide?

**Comment by hwhsu1231** [comment]
@memsharded, I found that this bug is **specific to `CMakeDeps` generator**.

It looks like `qt-config.cmake` files generated locally by `CMakeDeps` generator didn't properly include the corresponding `xxxMacros.cmake` files. However, after I modified the generator to `cmake_find_package_multi` and reconfigured the project, the error disappeared. That is, it successfully include `xxxMacros.cmake` files.

According to this [article](https://blog.conan.io/2021/10/19/New-CMake-Transparent-Integration-Guide.html) from Conan Blog, there will be only `CMakeToolchain` and `CMakeDeps` generators after the release of **Conan 2**. So `cmake_find_package_multi` will be abandoned in the future.

![reply2_img2](https://user-images.githubusercontent.com/71438617/158415750-6c0aba7c-dc19-4ca3-9c59-e599dec04ff5.png)

**Comment by hwhsu1231** [comment]
I don't know why, but it looks like this bug has been fixed after some modifications of [conan-center-index](https://github.com/conan-io/conan-center-index) from the issue: https://github.com/conan-io/conan-center-index/issues/9794. So I will close this issue.

**NOTE:** I notice that the filename of `*-config.cmake` files has been changed. (from `qt-config.cmake` to `Qt6Config.cmake`) So the only thing need to be modified is to change `find_package(qt ...)` into `find_package(Qt6 ...)`.

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/158932640-cdc8c9f7-bc1d-488c-bbfc-b428010f123f.png)
