### ISSUE TITLE
conan test_package doesn't see options

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#1076]
Hi, it seems that "conan test_package" command doesn't see options any more, e.g. I've cloned the following repo: https://github.com/lasote/conan-zlib
and got the following
```
C:\projects\conan>git clone https://github.com/lasote/conan-zlib.git zlib_lasote
Cloning into 'zlib_lasote'...
remote: Counting objects: 424, done.
remote: Compressing objects: 100% (6/6), done.
8                     1% (302/424)
Receiving objects: 100% (424/424), 63.55 KiB | 0 bytes/s, done.
Resolving deltas: 100% (241/241), done.
Checking connectivity... done.

C:\projects\conan\zlib_lasote>conan export lasote/stable
zlib/1.2.8@lasote/stable: A new conanfile.py version was exported
zlib/1.2.8@lasote/stable: Folder: C:\Users\SSE4\.conan\data\zlib\1.2.8\lasote\stable\export

C:\projects\conan\zlib_lasote>conan test_package -o shared=False
ERROR: C:\projects\conan\zlib_lasote\test_package\conanfile.py: 'options.shared' doesn't exist
Possible options are []

C:\projects\conan\zlib_lasote>conan install zlib/1.2.8@lasote/stable -o shared=False
Requirements
    zlib/1.2.8@lasote/stable from conan.io
Packages
    zlib/1.2.8@lasote/stable:63da998e3642b50bee33f4449826b2d623661505

zlib/1.2.8@lasote/stable: Already installed!
```

so, "conan install" works, but "conan test_package" doesn't, any ideas?

**Comment by memsharded** [comment]
When you are using ``conan test_package`` you are using the consuming project, and then ``shared`` doesn`t apply to it. You have to use:

```bash
$ conan test_package -o zlib:shared=False
```
This is the recommended way to use options even for the ``conan install`` case.

**Comment by SSE4** [comment]
@memsharded yep, it worked - thanks a lot, pls close this issue

**Comment by EricBackus** [comment]
I understand what you're saying about how test_package is running a different project (with a different conanfile.py). But the effect of this is not very friendly. I think it would be better if the command-line options that work for conan install also worked identically for conan test_package. It seems quite unlikely to me that the package test project needs many options, while the main project which is being tested really might have many options.

**Comment by memsharded** [comment]
Hi @EricBackus 

Not sure what you mean. I think that the options for ``conan install`` should work exactly the same as the options passed to ``conan test_package``. In both cases the recommended way is using the ``-o zlib:shared=False``, with the package name prefix. So it is always made explicit to which package the option applies. 

Conan might still support the bare ``-o option=value`` for backward compatibility, but it is not recommended. I have just submitted a PR to the docs to ensure it uses ``-o PkgName:option=value`` in all parts of the docs.

Thanks for your feedback!

**Comment by Firefly35** [comment]
Hi, sometimes asking for an option (typically shared=True) for some packages should not lead to an error even when the package doesn't provide a definition for it.

Indeed, even when providing shared=True or shared=False to a template header only library has no impact hence conan shouldn't complain and exit when it is the case (or maybe a flag such as ignore-undeclared-option could be used to install package not declaring the option without failure).

Often, for the shared=True/False option, it can often be a global option used for all dependencies, and  having the option explicitely defined only for a few specific dependencies when those dependencies don't match the global option set.
