### ISSUE TITLE
[feature] one application one lib folder

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#10763]
Like `nodejs`, a lib can be installed locally or globally easily and intuitively.

**Comment by memsharded** [comment]
Sorry, nodejs is very very different to c++, cannot compare.
Also, this feature request makes no sense, this is not a valid feature request. Feature requests should be way more detailed, explaining well what is the current behavior, the desired one, with clear and concise examples, and the rationale of it. 
Closing.
