### ISSUE TITLE
[feature] List recipe revision in `conan install` Requirements

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10773]
We've been specifying the recipe revision in our requires package references to avoid recipe changes to packages we pull from external sources (such as conan center) from triggering a recompile of items that take a long time (we're using `package_id_mode=recipe_revision_mode`).

It would be convenient if the list of requirements listed when running `conan install` could list the recipe revision numbers as well as the name, version etc so that we can easily identify if the correct revisions are being used. 

Example:
Instead of this: `MyPackage/1.0.0 from 'myserver' - Cache`
We get this: `MyPackage/1.0.0#abd3832 from 'myserver' - Cache`

Currently, the only way I know to check the recipe revisions that were pulled are to either use `conan info` or look in the generated `conan.lock` file.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, this is already done this way in Conan 2.0 (released alpha).

It couldn't be changed in 1.X, because there are users parsing the output, and it would break them.
Please try the Conan 2.0 alpha and report if necessary, otherwise I think this can be closed as implemented.

**Comment by nichmj01** [comment]
@memsharded Good to know it'll be supported in 2.0.0. I think it's still too early for us to move to 2.0.0 unfortunately. We also just started using conan 1.X and trying to move to 2.0.0 at this point will get a lot of push back unless it's extremely seamless and low effort.

Possibly could be added to 1.X as a configurable option that someone could turn on and therefore an intentional breakage? I understand that may be more work than is worthwhile though especially as you are working on 2.0.0.

**Comment by memsharded** [comment]
> I think it's still too early for us to move to 2.0.0 unfortunately. We also just started using conan 1.X and trying to move to 2.0.0 at this point will get a lot of push back unless it's extremely seamless and low effort.

Yes, it is not expected to move now, only to be tested. It is alpha stage, until General Availability (GA) it will not be recommended to upgrade. We expect that Conan 2.0 will be a big improvements, with many very useful features and better solutions, so the efforts to migrate will pay off. The most important part in the upgrade is to upgrade the recipes during 1.X to modern features that will be supported in 2.0. There will be a recipe-syntax subset that will be 1.X-2.0 compatible.

> Possibly could be added to 1.X as a configurable option that someone could turn on and therefore an intentional breakage? I understand that may be more work than is worthwhile though especially as you are working on 2.0.0.

Yes, sounds a bit too much, we prefer not to touch 1.X unless it is necessary to prepare for 2.0 transition.
