### ISSUE TITLE
Different requirements for build vs. install

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1077]
How would you do this: To build a package B for runtime, it requires a full suite of compiler tools from package A (option runtime=false), but to install B for runtime, it only requires a few runtime libraries from package A (option runtime=true).  I don't want to cause an installation of B on a deployment box to pull in the full A package, because it's just a runtime configuration.

Is there a way to have different requirements when building than when installing with `--build=never`?

After reading about `private` requirements, It would work if I could extend that concept to the options of those requirements.  That is, if I could say that "A with option runtime=false" was a private requirement and "A with option runtime=true" was not private, then B would correctly only propagate the runtime=true variant of A.

**Comment by memsharded** [comment]
The approach I prefer is install build/compiler tools (only needed to build from sources the package), decoupled, in a different conanfile, using virtualenvs to activate/deactivate the tools. 

I know it is not the perfect, fully automatic workflow in which each package can declare its own build tools, but where to put the limit? For example, does it make sense to depend on Visual Studio, then have a package to install Visual Studio? Besides not being feasible, I think it might not be the best approach, as build-tools typically collide with the consumers dev environment. For example, should I make my package recipes depend on gcc (MinGW) or CMake. Both have conan packages, so I can do that. But I think that the consumer of my recipes will definitely have CMake and Mingw installed, and they will not want my package installing another instance of CMake or Mingw as conan packages.

Related: https://github.com/conan-io/conan/issues/662, https://github.com/conan-io/conan/issues/543, https://github.com/conan-io/conan/issues/451

**Comment by tamboril** [comment]
Thanks for the suggestion.  I think I can make it work like that.  I think it could also work if I made two separate packages for my build tools (one for building, one for runtime), and require the one for building with `private` specified.  I think this would overcome the problem of needing both values of options at different visibility.

Because I use gcc on Linux only, it's easy to wrap up the entire compiler into a package; same with cmake.  So my build tools are neatly versioned along with the artifacts they're used to produce.

**Comment by memsharded** [comment]
Ok, cool. I think I will review again the "build_requirements" issue. Thanks for the feedback.

**Comment by claasd** [comment]
How about an additional  requirement type?
I for example use common cmake configs that I distribute via conan. 
These requirements are only needed when building, not when the package is consumed by a server package.

Currently, I use private dependencies, but this becomes very annoying, because I see the cmake config package 10-20 times in the requirements when installing a package.

Suggestion:
```python
requirements =  ("OtherPackage",
                           ("build_package", "build"),
                           ("PrivatePackage", "private"))
```

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/issues/1141 has proposed a new way, which I thing it can be great. Please have a look and tell!

**Comment by memsharded** [comment]
Hi @tamboril 

I think this was implemented by ``build_requires``. Have you had the chance to use them? They can now be defined both in ``profiles`` and also in package recipes (``build_requires`` attribute and ``build_requirements()`` method).

So I think this issue can be closed now, but please reopen if necessary. Thanks very much.

**Comment by tamboril** [comment]
Yes.  I successfully used the profile-based `build_requires`.  I didn't know you could do it from recipes, too.
I'll try that the next time I'm working on packaging.  Our packages are fairly stable, now.

**Comment by memsharded** [comment]
Yes, they were initially implemented only in profiles, then extended to be able to use them from recipes too. Right now in improving some issues with build_requires using different options.

So good, I think the issue can remain closed, just open a new one if you encounter any issue next time you are packaging. Cheers.
