### ISSUE TITLE
[question] deploy method implementation with new conan.tools.files.copy

### ISSUE THREAD

**Issue by dornbirndevelops** [conan-io/conan#10779]
Hello,

At the moment I am revisiting some package recipes of mine to make them somewhat ready for Conan 2.X.
A recipe that provides an application currently contains a deploy method like below.

```python
def deploy(self):
        # Deploy the executables from this package
        self.copy("*", src="bin", dst="bin")
        # Deploy the shared libs from this package
        self.copy("*.so*", src="lib", dst="bin")
        # Deploy all the shared libs from dependencies
        self.copy_deps("*.dll", src="bin", dst="bin")
        self.copy_deps("*.so*", src="lib", dst="bin")
```

The [migration guide](https://docs.conan.io/en/latest/conan_v2.html#self-copy-disappears-from-recipes) states that self.copy will be deprecated.

While it is straight forward to replace the first two `copy` lines, I could not figure out a substitution for the dependencies.
**How could a new deploy method look like?**
FTR: I tried the `deploy` generator, but this one unfortunately puts each dependency into separate folders.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The ``deploy()`` method has been completely removed in 2.0.

The approaches will be 2, depending on what you need:

- Implement what you want in the ``generate()`` method, which is called at ``install`` time (for consumers only). ``generate()`` method can visit dependencies via ``self.dependencies``
- Implement a user ``deployer`` as an extension, put it in the Conan cache (or install it with ``conan config install``) and call it with ``conan install .... --deploy=mydeployer``. Such deployers will get the ``conanfile`` as argument, and you can easily traverse dependencies too with ``conanfile.dependencies`` to implement the behavior you need. There are already a couple of built-in deployers to test too. Docs are still missing, but the PR is https://github.com/conan-io/conan/pull/10507 if you want to have a look.

**Comment by dornbirndevelops** [comment]
> * Implement what you want in the `generate()` method, which is called at `install` time (for consumers only). `generate()` method can visit dependencies via `self.dependencies`

Due to the deprecation of the `imports` method, I already specified a `generate` that looks like this currently:
```python
def generate(self):
        breakpoint()
        CMakeToolchain(self).generate()
        CMakeDeps(self).generate()
        bindir = join(self.build_folder, self.cpp.build.bindirs[0])
        for dep in self.dependencies.values():
            copy(self, "*.dll", dep.cpp_info.bindirs[0], bindir)
            copy(self, "*.dylib*", dep.cpp_info.libdirs[0], bindir)
            copy(self, "*.so*", dep.cpp_info.libdirs[0], bindir)
```
I added a `breakpoint()` statement to see at which time it is being called.
On Conan 1.46.0, the `generate` method only seems to be called during the build-phase of the application, but not during deployment (e.g. via `conan install package/1.0.0@ --build=package -if=install -of=output`). Is this only going to work for 2.X?


> * Implement a user `deployer` as an extension, put it in the Conan cache (or install it with `conan config install`) and call it with `conan install .... --deploy=mydeployer`. Such deployers will get the `conanfile` as argument, and you can easily traverse dependencies too with `conanfile.dependencies` to implement the behavior you need. There are already a couple of built-in deployers to test too. Docs are still missing, but the PR is [New Conan 2.0 deployers #10507](https://github.com/conan-io/conan/pull/10507) if you want to have a look.

Nice, I will check it out once the required dependencies from conan center are satisfied with the 2.X client.

**Comment by gpxricky** [comment]
@memsharded 

I wonder if there is a way to recreate the current behavior with the 2.x approach? I guess the deployer will just get a limited `conanfile` (e.g. no python_requires resolved), where I can't call methods like the `deploy` method?
What else can be the solution to recreate the current behavior?

**Comment by memsharded** [comment]
@dornbirndevelops 

> conan install package/1.0.0@ --build=package -if=install -of=output

Yes, that is true, that will not execute the ``generate()`` method of ``package/1.0.0``, as that method is to generate the build environment for package/1.0.0, not for its consumers. To be more explicit about the behavior, the CLI in 2.0 is:

```
conan install --requires=package/1.0.0
```
To make explicit it is the equivalent to having a local conanfile with a requires section (it was always this way, also in 1.X, but this makes it a bit more evident).

So for that case, it might be necessary a deployer in 2.0, yes.

@gpxricky 

> I wonder if there is a way to recreate the current behavior with the 2.x approach? I guess the deployer will just get a limited conanfile (e.g. no python_requires resolved), where I can't call methods like the deploy method?
What else can be the solution to recreate the current behavior?

The ``conanfile`` will be a full one, if it has ``python_requires`` they would have been evaluated. You might call into some recipe method too, if that is what you want. But what we have discovered is that in many many cases, the recipe ``deploy()`` method was doing something like the above commented:
```
bindir = join(self.build_folder, self.cpp.build.bindirs[0])
        for dep in self.dependencies.values():
            copy(self, "*.dll", dep.cpp_info.bindirs[0], bindir)
            copy(self, "*.dylib*", dep.cpp_info.libdirs[0], bindir)
            copy(self, "*.so*", dep.cpp_info.libdirs[0], bindir)
```

And this is very generic, so it is more convenient, flexible and easy to maintain to put it in an external ``deployer``, that will be common to all possible packages. But still, if you want to access the ``conanfile`` attributes or methods, it seems possible.
