### ISSUE TITLE
[feature] Local current folder in `layout` method

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#10781]
Hi,

the documentation of the `layout` method (https://docs.conan.io/en/latest/reference/conanfile/methods.html#layout) mentions that the folders are relative to the local current folder when calling `conan build`, etc. I probably misunderstood that, but the *local current folder* seems to be the folder where the recipe file is located. I don't know if it is clear for everyone else, but I thought about the current working directory first.

I guess it is fine for quite all users to use the recipe folder. However, what happens, if the recipe is located in a subdirectory? Image the following directory structure:

```
<my project folder>
|__ recipe
   |__ conanfile.py
|__ src
   |__ CMakeLists.txt
   |__ ...
```

Configuring a layout that is based on the `my project folder` instead of the `recipe` folder might require differentiation between local cache builds or not:

```
def layout(self):
    if self.in_local_cache:
        self.folders.source = "src"
        self.folders.build = "build"
    else:
        self.folders.source = "../src"
        self.folders.build = "../build"
```

I wouldn't request to change the current behavior as it fits for 99% of the users. However, would it be an idea to introduce an additional folder like `self.folders.base` or `self.folders.root` that only applies for non-cache builds?

```
def layout(self):
    self.folders.base = ".."
    self.folders.source = "src"
    self.folders.build = "build"
```

Is it too fancy or only have-baked to add something like this just for the remaining 1% of users (who might even have additional requirements for that topic)? My guess is yes, however I have still created that issue to discuss and document the decision.

Best regards,
Markus

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gpxricky 

I think you might have missed latest 1.46 changelog (https://docs.conan.io/en/latest/changelog.html)

- Feature: Adding self.base_source_folder for exports_sources explicit layouts. [#10654](https://github.com/conan-io/conan/pull/10654) . Docs [here](https://github.com/conan-io/docs/pull/2418)
- Feature: Adding root to layout model to allow conanfile.py in subfolders. [#10654](https://github.com/conan-io/conan/pull/10654) . Docs [here](https://github.com/conan-io/docs/pull/2418)

I think what you describe was exactly implemented in those, but please have a look and let us know, thanks!

**Comment by gpxricky** [comment]
Oh man, what a shame! I'm sorry. That's exactly what I was requesting.

**Comment by gpxricky** [comment]
@memsharded It seems that `self.folders.generators` does not support `self.folders.root`. Check comment in #10826 for details
