### ISSUE TITLE
[bug] cmake_build_modules property no longer working as of conan 1.43

### ISSUE THREAD

**Issue by ma30002000** [conan-io/conan#10782]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: cmake 3.18.4
  * Conan version: 1.43.0
  * Python version: 3.9.7

### Steps to reproduce (Include if Applicable)
- a conan package is used to ship *.cmake files to target project
- "Injection" of cmake files no longer work as of conan 1.43 (works with 1.42.2)

- pkg/conanfile.py:

```
from conans import ConanFile
from glob import glob
from os import path

class SharedCmakeFiles(ConanFile):
    name = "cmake-hello"
    version = "1.0.0"
    settings = None
    exports_sources = "cmake/*"

    def package(self):
        self.copy("*.cmake", src="cmake", keep_path=False)

    def package_info(self):
        cmake_files = [path.relpath(file, self.package_folder) for file in glob("{folder}/*.cmake".format(folder=self.package_folder))]

        self.output.info("Auto-including .cmake files: " + ' '.join(cmake_files))
        self.cpp_info.set_property('cmake_build_modules', cmake_files)
```

- pkg/msg.cmake
```
macro(msg)
message(STATUS "Hello from macro")
endmacro()
```

- consumer/conanfile.py
```
from conans import ConanFile, tools

class TrsConan(ConanFile):
    def requirements(self):
        self.requires("cmake-hello/[>=1.0]")
```

- consumer/CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}")
include(conan)

project(test-hello)

conan_cmake_run(CONANFILE conanfile.py BASIC_SETUP CMAKE_TARGETS KEEP_RPATHS)

msg()

```

Build package:
```
cd pkg
conan create .
```

Build target project
```
cd consumer
mkdir cmake.tmp
cd cmake.tmp
cmake .. -DCMAKE_BUILD_TYPE=Debug

```

### Logs (Executed commands with output) (Include/Attach if Applicable)
1.42.2:
```
[...]
-- Hello from macro
[...]
```

1.43:
```
[...]
CMake Error at CMakeLists.txt:10 (msg):
  Unknown CMake command "msg".
[...]
```

For some reason, CONAN_BUILD_MODULES_PATHS_CMAKE-HELLO is no longer set in conanbuildinfo.cmake.

**Comment by memsharded** [comment]
Hi @ma30002000 

This is expected (documented in https://docs.conan.io/en/latest/conan_v2.html#new-properties-model-for-the-cpp-info-in-conan-2-0-generators):

- ``cmake_build_modules`` is used for the new generators only (``CMakeDeps``)
- Legacy generators will use the attributes approach (``cpp_info.names``, ``cpp_info.build_modules``)
- So new and legacy generators use completely different definitions
- The integration that is being used via the ``cmake-conan`` integration is the legacy ``cmake_find_package`` one

At some point in previous versions it was partially used, but after some conversations with the ConanCenter package contributors it was decided to keep them decoupled, because otherwise too many things were being broken.

**Comment by ma30002000** [comment]
Thank you for the quick reply. Sticking to legacy works when setting the cpp_info.build_modules attribute.
I would also try out switching to the "new" model. However, if I change the following lines in CMakeList.txt
```
conan_cmake_autodetect(settings)
conan_cmake_install(PATH_OR_REFERENCE .. SETTINGS ${settings} GENERATOR CMakeDeps)

```
I get 
```
ERROR: Error in generator 'CMakeDeps': 'settings.build_type' doesn't exist
'settings' possible configurations are none
CMake Error at conan.cmake:638 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:14 (conan_cmake_install)
```

even though with generator "cmake" ist works. What else am I doing wrong?

**Comment by memsharded** [comment]
You need to add the correct ``settings`` to your ``conanfile.py``, including the ``build_type``

**Comment by ma30002000** [comment]
Thanks, I think we can close this issue.
