### ISSUE TITLE
[question] Define options in python_requires

### ISSUE THREAD

**Issue by kevinpoulet** [conan-io/conan#10789]
Hello,

I currently have a base recipe. I would like to add some options that are shared by all recipes that inherit it.

I have found #6612 and the last comment mentions the `init()` method. The `init()` code being shared, I defined it in the base recipe.

The base options, and the associated default values, are stored in prefixed class attributes to not be overwritten with consumer defined options.

The `init()` method then merges the `(default_)options` with the prefixed attributes and assign them back to `(default_)options`. 

Running `conan inspect` does list the added options and their default values, but trying to access them, for instance in the `build()` method, results in a `ConanException: option doesn't exist` followed by the list of possible options where the base options are indeed absent.

The `python_requires` attribute "way" is used in the consumer. The tests took place on Windows 10, Python 3.9.2, Conan 1.44.1.

### Temporary solution

Temporarily, the `(default_)options` are directly set in the base recipe attributes. As expected, this does not work for consumers with options of their own. 

Thanks in advance.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry @kevinpoulet that this ticket was not responded back then, sometimes the load is just too much, and some issues and tickets fall through the cracks :(

Hopefully you have found a solution for this.

Don't hesitate to ping or comment in old questions to revive them if necessary. Thanks!

**Comment by kevinpoulet** [comment]
No problem, I closed it to do housekeeping. 

I will update the Conan usage when migrating to V2. If the need arises, I'll create a separate issue to better reflect the situation.

Thank you.
