### ISSUE TITLE
[question] generating conaninfo.txt

### ISSUE THREAD

**Issue by kevinpoulet** [conan-io/conan#10790]
Hello,

I was looking into retrieving dependency tree information (names, versions, options, ...) and having those information exposed to the built project (currently applications, i.e. final consumer).

As far as I can tell, Conan doesn't currently have a Python API that could be used by a script to inspect a given recipe configuration from "outside".

Currently, I added a Python script in a base recipe for all applications, that is ran at the beginning of the `build()` method (I don't think this impact the following issue but just in case).

The script then parses the `conaninfo.txt` file to extract the dependency tree information.

The issue is that this file in only present in local build folder (`build/` in source directory) but absent when building in the local repository (`conan install ... --build outdated`).

Thanks in advance.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @kevinpoulet 

I am not sure what is exactly what you are trying to achieve, but it seems there could be much better ways to achieve it:

- The ``generate()`` method have access to ``self.dependencies`` information (https://docs.conan.io/en/latest/reference/conanfile/dependencies.html), you can navigate it and dump whatever information you want to any file you want. This method is generated at ``install()`` time.
- The ``conan info`` command can give you information about the dependency graph too

The first way seems what you want to do,  please have a look.

**Comment by kevinpoulet** [comment]
Hello,

I overlooked the `generate()` method. It indeed looks promising. I also missed the dependencies attribute (that being said, it was a while back, maybe dependencies wasn't out yet). I'll close the issue for now, I should be fine with those.

To clarify, the goal is to generate a file that would contain information relative to the dependency tree in a specific format. This is used by custom scripts during the build step of the application package and also stored in the package for future use.

Thank you.

**Comment by memsharded** [comment]
> To clarify, the goal is to generate a file that would contain information relative to the dependency tree in a specific format. This is used by custom scripts during the build step of the application package and also stored in the package for future use.

Yes, seems totally the case. I would probably try to put the code in a ``python_requires``, then use it and call one function like ``create_file(self)`` passing the current conanfile in the consumer ``generate()`` method. In this way you can reuse it for all packages very easily. (this is the way custom generators are now recommended)

**Comment by kevinpoulet** [comment]
As a side note, is there a documentation for the API itself?

For instance, I tried printing the dependency `options` and it returned `conans.model.options.Options`. I was able to find the class in the Conan source but I'm having trouble finding out how to retrieve information like the name and value and if there are other information that could prove useful.

Thanks in advance.
