### ISSUE TITLE
[question] tools.apple:sdk_path not a config option

### ISSUE THREAD

**Issue by avetiso** [conan-io/conan#10791]
Conan 1.46
Meson 0.61.2

Here, the conan docs are saying that I can define `tools.apple:sdk_path` in my conan.conf file under the `[conf]` section. 

https://docs.conan.io/en/latest/reference/conanfile/tools/apple.html#

However, `conan config list` lists no such option. I have attempted to define this sdk_path in conan.conf in ~/.conan under `[conf]`, as well as under the `[options]` section of my conan profile for the profile I'm passing to conan create using `conan create . -pr:b=ios-armv8-debug`.

However, I always fail at this spot in `meson/toolchain.py` (starting at line 155):

```
        # SDK path is mandatory for cross-building
        sdk_path = conanfile.conf.get("tools.apple:sdk_path")
        if not sdk_path and self.cross_build:
            raise ConanException("You must provide a valid SDK path for cross-compilation.")
```

Why is the meson integration requesting an option that doesn't exist?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Conf is declared:

- In global.conf file (https://docs.conan.io/en/latest/reference/config_files/global_conf.html)
- In profiles in section ``[conf]``  (https://docs.conan.io/en/latest/reference/profiles.html#tools-configurations)
- In command line in ``-c tools.apple:sdk_path=<path>`` (``conan install -h``)

So it seems you are incorrectly defining it in ``[options]``

**Comment by avetiso** [comment]
> Conf is declared:
> 
> * In global.conf file (https://docs.conan.io/en/latest/reference/config_files/global_conf.html)
> * In profiles in section `[conf]`  (https://docs.conan.io/en/latest/reference/profiles.html#tools-configurations)
> * In command line in `-c tools.apple:sdk_path=<path>` (`conan install -h`)
> 
> So it seems you are incorrectly defining it in `[options]`

I've created a global.conf with exactly these contents:

```
[conf]
tools.apple:sdk_path=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
```

`conan config list` now returns an error:  'Error in Conan initialization: Bad conf definition: [conf]'

If I add it to my already existing conan.conf, there is no error, but `conan config list` still doesn't report the option.

```
➜  .conan conan config list | grep apple
tools.apple.xcodebuild:verbosity: Verbosity level for xcodebuild: 'verbose' or 'quiet
```

I have also tried adding it to the profile that is the cross build (from macos to ios, armv8). Here is the profile:

```
include(ios-base)

[settings]
arch=armv8
build_type=Debug
#os.sdk=iphoneos
#os.sdk_version=15.2

[conf]
tools.apple:sdk_path=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
```

ios-base is:

```
[settings]
os=iOS
os.version=8.0
os_build=Macos
compiler=apple-clang
compiler.libcxx=libc++
[options]
[build_requires]
[env]
```

The latter two attempts result in the same error, the meson toolchain complaining that an SDK path must be defined.

**Comment by avetiso** [comment]
Found my issue. Swapped the build and host profiles inadvertently.

**Comment by memsharded** [comment]
Yes, ``global.conf`` does not contain the ``[conf]`` header, that is only for the profiles.
