### ISSUE TITLE
[question] Impact of a remote with error "Trying to modify locked package"

### ISSUE THREAD

**Issue by aurelienrb** [conan-io/conan#10809]
Hello,

I just understood what causes my CI pipeline to fail from time to time with the error `ERROR: Trying to modify locked package xxx`

Here's what I do:

```
conan remove -f mypkg/*
conan export-pkg ./conan 1.0.0@ci/testing --source-folder . --build-folder ./build -s build_type=RelWithDebInfo
conan upload --all --confirm -r myartifactory mypkg/*
```

The first time it works fine and well: the package is exported on our internal Artifactory 👍 

When I run again my CI to do test some changes on my recipe, `conan export-pkg` completes as usual... before failing with `ERROR: Trying to modify locked package mypkg/1.0.0@ci/testing`

It took me a while to understand why clearing the conan cache with `conan remove` had no effect. And I just found the reason why : I need to clear the packages on Artifactory itself.

So Conan detects this packages already exists on Artifactory while performing the `conan export-pkg` (and not `conan upload`).

My expectation was to be able to override an existing package on a remote. Or at least to fail to do it when running `conan upload`. I am surprised `conan export-pkg` performs this check, and as a user feedback I can say it is quite hard to guess and understand.

How does it work? Why is it talking about a lock when a  package exists on a remote? (this is confusing because the doc talks about locks as local files). Why is this check done when building a local package?

Thanks for your help 😃

**Comment by memsharded** [comment]
Hi @aurelienrb 

I am very sorry this was not responded back then. 
Now the ticket is quite outdated, as Conan 2 has completely changed lockfiles (for the better, much simpler and powerful).

I am closing this ticket as outdated then, please create new tickets for any further question you might have. Thanks for your feedback!
