### ISSUE TITLE
[feature] Settings available but not declared

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#10813]
It is typical to read settings because you need to know the value (during build) but you don't want that setting to be declared in the recipe, because in case the consumer doesn't specify the setting you want to be able to locate a built binary.

**Comment by memsharded** [comment]
> It is typical to read settings because you need to know the value (during build) but you don't want that setting to be declared in the recipe, because in case the consumer doesn't specify the setting you want to be able to locate a built binary.

In Conan 2.0, not defining a settings value is not an error unless it is actually used by some helper. So the approach would be:
- If the settings is to be used somewhere in the recipe, declare it in ``settings = ``
- Read the setting when needed, like in ``build()`` method. If ``build()`` method needs a non-``None`` value, then raise (what many Conan built-in helpers do)
- If the package binary does not depend on that setting, remove it in ``package_id()``.

So I think we can close this ticket. Implementing access to profile settings from recipes would be complicated, and opening to new possible unexpected and dangerous side effects, and the above seems to address correctly the issue.
