### ISSUE TITLE
[feature] Support Conan version and semver handling in profile template render context

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#10818]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

As reference, see https://github.com/conan-io/conan/issues/10802

It would be good to have the Conan version available in the profile jinja template render context to be able to do better logic in profiles, especially with breaking changes introduced via new versions of Conan.

Having semver testing functionality and the Conan version available for use in the template will prevent workarounds with only the `os` python module available as stated in that issue above:
```
{% set fd = os.popen("conan --version", 'r', 1) %}
{% set output = fd.read() %}
{% set rc = fd.close() %}
{% set version_str = output.replace("Conan version", "") %}
{% set version_numbers = version_str.split(".") %}
{% set version_numbers_len = version_numbers | length %}
{% if version_numbers_len >= 2 %}
    {% set conan_version_major = version_numbers[0] | int %}
    {% set conan_version_minor = version_numbers[1] | int %}
{% else %}
    {% set conan_version_major = None %}
    {% set conan_version_minor = None %}
{% endif %}

{% if conan_version_major == 1 and conan_version_minor >= 46 %}
    tools.cmake.cmaketoolchain:user_toolchain=["$ENV{CONAN_CMAKE_TOOLCHAIN_FILE}"]
{% else %}
    tools.cmake.cmaketoolchain:user_toolchain=$ENV{CONAN_CMAKE_TOOLCHAIN_FILE}
{% endif %}
```

**Comment by danicriss** [comment]
Silly workaround in the meantime

```
{% set command_output_stream = os.popen("conan --version") %}
{% set conan_version_reply = command_output_stream.read() %} # i.e. `Conan version 2.0.1`
{% set conan_version = conan_version_reply.split(" ")[2] %}
{% set conan_version_major = conan_version.split(".")[0] | int %}
{% if conan_version_major < 2 %}
{% 	set conan_v2_or_greater = False %}
{% else %}
{% 	set conan_v2_or_greater = True %}
{% endif %}
```

**Comment by memsharded** [comment]
Agree that this could be helpful, sorry that this was not managed earlier.
Adding it in https://github.com/conan-io/conan/pull/13377 for next 1.60 (and Conan 2.0.2)

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13377 for 1.60
