### ISSUE TITLE
[suggestion] toolset support for `msvc` compiler

### ISSUE THREAD

**Issue by MarcelRaad** [conan-io/conan#10815]
Continuing from https://github.com/conan-io/tribe/pull/32#issuecomment-1070639667:

I'm currently using the non-default `v141_xp` and `ClangCL` toolsets with the `Visual Studio` compiler and the `CMake` and `MSBuild` build helpers from `conans`. I've just started trying to switch to the `msvc` compiler and the new build helpers from `conan.tools`. Unfortunately, I haven't found a way to specify a toolset there.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @MarcelRaad 

I have added support for ``_xp`` toolsets in https://github.com/conan-io/conan/pull/10808 for the ``msvc`` compiler.
It would be great if you could have a look, ideally running Conan from my PR source branch, and report.

Regarding ClangCL, that would need some more thinking, but I believe adding xp toolsets as a start sounds good.

**Comment by MarcelRaad** [comment]
Thanks, sounds good, I'll have a look! Might take me a while though as I'm not very familiar with Python development yet. (Edit: your README.rst is great though, so it will probably not take that long 👍 )

**Comment by memsharded** [comment]
> Thanks, sounds good, I'll have a look! Might take me a while though as I'm not very familiar with Python development yet. (Edit: your README.rst is great though, so it will probably not take that long 👍 )

Yes, the ``git clone`` + ``git checkout <branch>`` + ``pip install -e .`` works quite well. Looking forward your feedback!

**Comment by MarcelRaad** [comment]
Tested with the new CMake build helper + Visual Studio 2022 (17.0) + v141_xp toolset and it works great. Thanks a lot! 👍

**Comment by memsharded** [comment]
Excellent, thanks for the feedback @MarcelRaad !

**Comment by memsharded** [comment]
I am going to open a new issue for the clang toolsets.
