### ISSUE TITLE
[bug] Wrong install_folder when using layout() method and package development flow

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#10826]
Hi,

I think there is a bug that sets the `self.install_folder` attribute to the recipe folder when the `layout` method is defined and the package development flow is used.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: -
  * Conan version: 1.46.0
  * Python version: 3.8.9

### Steps to reproduce (Include if Applicable)

- Use the following `conanfile.py`:

  ```
  #!/usr/bin/env python3
  # -*- coding: utf-8 -*-

  from conan import ConanFile

  class TestRecipe(ConanFile):
      name = "test"

      def layout(self):
          pass

      def generate(self):
          self.output.warn(f"INSTALL_FOLDER: {self.install_folder}")
  ```

- Create the install files using `conan install <path_to_conanfile> test/dev@user/testing --install-folder <some_install_folder>`

- Observed output: `INSTALL_FOLDER: <abs_path_to_conanfile>`

- Expected output: `INSTALL_FOLDER: <abs_some_install_folder>`

Removing the `layout` method from the recipe above leads to the following result:

- Observed output: `INSTALL_FOLDER: <abs_some_install_folder>`

- Expected output: `INSTALL_FOLDER: <abs_some_install_folder>`
 
Best regards,
Markus

**Comment by gpxricky** [comment]
It seems that I need to specify `self.folders.generators` in the `layout()` method. However, please be aware that this folder does not seem to support `self.folders.root` - it always seems to be relative to the `conanfile.py`.

**Comment by gpxricky** [comment]
@memsharded 

It is even stranger. The root folder seems to be applied when running the `build` method, but it seems to be relative when running the `generate` method:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from conan import ConanFile
from pathlib import Path

class TestRecipe(ConanFile):
    name = "test"

    def layout(self):
        self.folders.root = ".."
        self.folders.build = "build"
        self.folders.generators = "gen"

    def generate(self):
        self.output.warn(f"INSTALL_FOLDER: {self.generators_folder}")
        self.output.warn(f"BUILD_FOLDER: {self.build_folder}")

    def build(self):
        self.output.warn(f"INSTALL_FOLDER: {self.generators_folder}")
        self.output.warn(f"BUILD_FOLDER: {self.build_folder}")
```

Output of `conan install` command (package development flow) is:

```
conanfile.py (test/None): Calling generate()
conanfile.py (test/None): WARN: INSTALL_FOLDER: c:\path_to_conanfile\gen
conanfile.py (test/None): WARN: BUILD_FOLDER: c:\path_to_conanfile\build
```

Output of `conan build` command (package development flow) is:

```
conanfile.py (test/None): Calling build()
conanfile.py (test/None): WARN: INSTALL_FOLDER: c:\path_to_conanfile\..\gen
conanfile.py (test/None): WARN: BUILD_FOLDER: c:\path_to_conanfile\..\build
```

**Comment by memsharded** [comment]
Yes, apparently it is working only in some cases, I am checking it, thanks for reporting

**Comment by memsharded** [comment]
You are right, apparently it was covered by tests, but really it was lacking some checks. I have fixed it and submitted https://github.com/conan-io/conan/pull/10842 for next 1.47 release.
