### ISSUE TITLE
[bug] self.env_info not resolved in consumer

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#10827]
Hi,

I'm not sure if it is a bug, but `self.env_info` seems to behave differently when comparing version 1.38.0 with 1.45.0 or 1.46.0. See below for an example. Is this a bug or is this desired?

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: -
  * Conan version: 1.38.0, 1.45.0, 1.46.0
  * Python version: 3.8.9

### Steps to reproduce (Include if Applicable)

- Create the following recipe `env_provide/conanfile.py`:

  ```
  #!/usr/bin/env python3
  # -*- coding: utf-8 -*-
  
  from conan import ConanFile
  from pathlib import Path
  
  class TestRecipe(ConanFile):
      name = "env_provide"

      def build(self):
          Path(self.build_folder, "test.txt").touch()

      def package(self):
          self.copy("test.txt")

      def package_info(self):
          self.env_info.TEST_TXT = "MY_TEST_TXT"
  ```

- Create the following recipe `env_consume/conanfile.py`:

  ```
  #!/usr/bin/env python3
  # -*- coding: utf-8 -*-
  
  from conan import ConanFile
  from pathlib import Path
  import os

  class TestRecipe(ConanFile):
      name = "env_consume"
      requires = "env_provide/dev@user/testing"

      def build(self):
          self.output.warn(f"TEST_TXT: {self.deps_env_info.TEST_TXT}")
          self.output.warn(f"TEST_TXT: {os.getenv('TEST_TXT')}")
          Path(self.build_folder, "test.txt").touch()

      def package(self):
          self.copy("test.txt")
  ```

- Create the Conan package for `env_provide`:

  ```
  conan create <path_to_env_provide> env_provide/dev@user/testing
  ```

- Create the Conan package for `env_consume`:

  ```
  conan create <path_to_env_consume> env_consume/dev@user/testing
  ```

- Check output

Using Conan version 1.45.0 or 1.46.0 the output is as follows:

```
env_consume/dev@user/testing: WARN: TEST_TXT: []
env_consume/dev@user/testing: WARN: TEST_TXT: None
```

However, using Conan 1.38.0 the output is as expected (at least for me ;)):

```
env_consume/dev@user/testing: WARN: TEST_TXT: MY_TEST_TXT
env_consume/dev@user/testing: WARN: TEST_TXT: MY_TEST_TXT
```

I have checked the changelog, but haven't found something that would indicate that the change of the behavior is desired. So, I guess it is a bug, isn't it?

Best regards,
Markus

**Comment by memsharded** [comment]
Quick question, are you using the ``--profile:build`` somehow, defined in the default config, or passed in command line in some ``-s:b ...`` or ``--profile:build`` argument that you are not showing? That would explain it.

**Comment by gpxricky** [comment]
@memsharded You are right, I've added a default build profile to `global.conf`. However, why does it affect the definition or usage of environment variables? And how to fix it if I need to have a build profile (which is recommended by the Conan 2.x migration guide)?

**Edit:** when removing the build profile from the `global.conf` it works fine in version 1.46.0. I just don't get the point why it influences the behavior and how to solve it when build profiles are actually used... :-(

**Comment by memsharded** [comment]
> @memsharded You are right, I've added a default build profile to global.conf. However, why does it affect the definition or usage of environment variables? And how to fix it if I need to have a build profile (which is recommended by the Conan 2.x migration guide)?

The usage of the build profile opts-in into a new behavior, the resolution of the dependency graph in 2 contexts: the "build" context for tools and the "host" context for libraries. With this new mechanism:

- The ``cpp_info`` propagates in the host context: You can only link headers and libraries that are in the same host context you are compiling for, but not in the build context. Example: cross building from Windows ("build") to a RaspberryPI (Linux ,"host"). You are building an "app/1.0" to run on the RPI. You can only link libraries that are in the "host" context, but you cannot build a library in the "build" (Windows) context into the app
- The ``env_info`` propagates from the build context. Environment variables is the mechanism that ``build_requires`` or ``tool_requires`` use to pass information to their consumers. So ``env_info`` is propagated only in the "build" context.

This was the first step towards the build/host context solution, but it was a bit limited. 
The new ``self.dependencies`` and environment model improves this with:
- Defining ``buildenv_info`` and ``runenv_info`` to distinguish between things for build time or for runtime
- New ``VirtualBuildEnv`` and ``VirtualRunEnv`` generators, that can gather information correctly from both contexts

Have a look to https://docs.conan.io/en/latest/reference/conanfile/tools/env.html for more info.

**Comment by gpxricky** [comment]
@memsharded

Many thanks for clarification. I have had a quick look into the documentation, but haven't understood everything. Need to do some tests for my own to understand it, probably.

In short: to solve my issue, the only way to do this is to change dependencies that provide environment variables to be a `tool_requires`? In my real example, this dependency is a SDK like dependency and therefore provides headers, libraries and binaries but also environment variables (#10347). So I would require both, `cpp_info` and `env_info`, I guess which seems to be impossible when using a build profile...

**Comment by memsharded** [comment]
> In short: to solve my issue, the only way to do this is to change dependencies that provide environment variables to be a tool_requires? In my real example, this dependency is a SDK like dependency and therefore provides headers, libraries and binaries but also environment variables (https://github.com/conan-io/conan/pull/10347). So I would require both, cpp_info and env_info, I guess which seems to be impossible when using a build profile...

The possibilities are:
- Not use the build and host profile, just the host one
- Using the build profile, and not using the new environment tools, yes, you would need to convert it to tool_requires
- Using the build profile, and using the new environment tools, you can define the ``buildenv_info`` and ``runenv_info`` in your host dependencies, and you will get them via the new generators

Using the new environment tools is recommended, as it will be the tools that will remain in Conan 2.0.

For an SDK package, it is true that there is still a grey area, as it is both a build&host package at the same time. The initial effort in https://github.com/conan-io/conan/pull/10347, is to start defining correct package_ids. but after that, managing the build information both cpp and environment will follow. 

At the moment, you might try this:

- Use the build profile
- Use the same SDK package both as ``tool_requires``. That will get the environment part automatically
- access the ``self.dependencies["mysdk"].cpp_info`` information directly in the ``generate()`` method of the consumers. Maybe  do your own generator? the key here is how the information from the SDK is passed to the build. Because the typical ``CMakeDeps`` integration, for example, will not work as in general SDKs are not expected to be used via ``find_package()``.

If you can provide a bit more information about how you are consuming the SDK ``cpp_info``, please, we could think about it.

**Comment by gpxricky** [comment]
@memsharded 

I've ended up with the following solution:

env_provide/conanfile.py:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from conans import ConanFile
from pathlib import Path

class TestRecipe(ConanFile):
    name = "env_provide"

    def build(self):
        Path(self.build_folder, "test.txt").touch()

    def package(self):
        self.copy("test.txt")

    def package_info(self):
        self.buildenv_info.append("TEST_TXT", "TEST_TXT_BUILD")
```

env_consume/conanfile.py:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from conan import ConanFile
import os
from pathlib import Path
from .environment import BuildEnv

class TestRecipe(ConanFile):
    name = "env_consume"

    requires = "env_provide/dev@user/testing"

    @property
    def build_environment(self):
        return BuildEnv(self).vars()

    def build(self):
        with self.build_environment.apply():
            self.output.warn(f"TEST_TXT: {os.getenv('TEST_TXT')}")

        Path(self.build_folder, "test.txt").touch()

    def package(self):
        self.copy("test.txt")
```

env_consume/environment.py:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from conan.tools.env import Environment, VirtualBuildEnv
import json
from pathlib import Path

class BuildEnv(VirtualBuildEnv):
    @property
    def filename(self):
        return Path(
            self._conanfile.generators_folder,
            f"{self._filename}.json"
        )

    def vars(self, scope="build"):
        if self.filename.exists():
            return self._load_json(scope)

        build_env = self.environment()
        return build_env.vars(self._conanfile, scope=scope)


    def generate(self, scope="build"):
        build_env = self.environment()
        self._save_json(build_env.vars(self._conanfile, scope=scope))


    def _save_json(self, vars):
        with self.filename.open("w") as file:
            json.dump(dict(vars.items()), file, indent=2)


    def _load_json(self, scope):
        with self.filename.open("r") as file:
            content = json.load(file)

        build_env = Environment()
        for name, value in content.items():
            build_env.define(name, value)
        return build_env.vars(self._conanfile, scope=scope)
```

**Comment by gpxricky** [comment]
@memsharded Question is, if something like above should be integrated into Conan in the future or if it violates any architectural decisions or is just to specifically? At least for me, the `VirtualBuildEnv` is not sufficient as I need to have the variables available directly inside the `build` method of the recipe.

**Comment by memsharded** [comment]
``env_info`` no longer exists in Conan 2, closing as outdated
