### ISSUE TITLE
Version range behavior

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1083]
In version 0.20.2, how is conan selecting `0.0.0.100` over `0.1.3.2` below?  Even as a python string comparison, 0.1* should be greater than 0.0*.

`Version range '>0.1.3.0' required by 'None' resolved to 'MyPkg/0.0.0.100@jharris/testing'`

```
# Specifies the requirements of this project on specific conan packages

[requires]
MyPkg/[>0.1.3.0]@jharris/testing

[options]
MyPkg:fullsource=True
```

[update] Well, it seems to work if I have 0.1.3.2 in my cache.  But how do I get it to check against the newer versions in the remote?

**Comment by memsharded** [comment]
You should provide the ``--update`` arg, which is the general approach for updating old versions from the current local cache with the remote ones.

**Comment by tamboril** [comment]
That was it.  I had tried that, but when I was using `--update`, I was requiring `~=0.1.3` to select `0.1.3.2` from the remote, which it would not.  But I needed to require `~=0.1.3.0`, in which case, it did correctly pull from the remote when I specified `--update`.

**Comment by memsharded** [comment]
Good!
