### ISSUE TITLE
[question] Globally defining ABI compatibility between various compiler versions?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#10831]
I'm switching my development to VS2022. The Conan way to do that is rebuilding all binary packages for VS2022 (including CCI ones - note that CCI doesn't provide VS2022 binaries yet). But Microsoft guarantees binary compatibility of its newer compilers with older ones starting with VS2015: https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017

Can this compatibility be declared in Conan? Something like `compatible_packages` but global for all packages? I would like to use VS2019/VS2017/VS2015 binary package if no VS2022 binary is available.

**Comment by memsharded** [comment]
Not in 1.X, but we are proposing it for 2.0 https://github.com/conan-io/conan/pull/10241

**Comment by db4** [comment]
@memsharded Can we also handle glibc/libstdc++ compatibility in a similar way? Say we add glibc/libstdc++ version settings to conan and globally declare that packages built agains older glibc versions are compatible?

**Comment by memsharded** [comment]
> @memsharded Can we also handle glibc/libstdc++ compatibility in a similar way? Say we add glibc/libstdc++ version settings to conan and globally declare that packages built agains older glibc versions are compatible?

Yes, it will be possible to do that, relatively straightforwardly. It is likely that we won't add it by default, because at the moment it will result in a lot of pressure on the servers (the protocol doesn't support this operation efficiently, it will need to be improved). But users wanting that control will be able to do it easily.

**Comment by memsharded** [comment]
By the way, this is already released in Conan 2.0-alpha.6 some days ago. So I think this could be closed as implemented in alpha.6, and new issues can be opened (at the moment the docs is a work in progress, but checking the tests associated to https://github.com/conan-io/conan/pull/10241 could be enough to get an idea and start testing it)

**Comment by db4** [comment]
> > @memsharded Can we also handle glibc/libstdc++ compatibility in a similar way? Say we add glibc/libstdc++ version settings to conan and globally declare that packages built agains older glibc versions are compatible?
> 
> Yes, it will be possible to do that, relatively straightforwardly. It is likely that we won't add it by default, because at the moment it will result in a lot of pressure on the servers (the protocol doesn't support this operation efficiently, it will need to be improved).

It would be great. Right now CCI binaries are not compatible with various "official" Conan docker images, see https://github.com/conan-io/conan-docker-tools/issues/391. Specifying glibc explicitly in the package ID could solve this.

OK, I'm closing the issue and will try to experiment with Conan 2.0

**Comment by uilianries** [comment]
@db4 glibc is an old topic but well discussed on Conan. If you do a quick search for glibc on our issues, you will find more people asking the same. The thing is, you can do it as a custom setting, but for official packages it would become a nightmare to generate all packages. To have an idea, we generate around +100 packages for a single c++ project in Conan Center. now, multiple for X times according the glibc versions. There is a documentation how to make it possible: https://docs.conan.io/en/latest/extending/custom_settings.html#custom-settings

**Comment by db4** [comment]
@uilianries 
> now, multiple for X times according the glibc versions.

No way. You just use the only image with old enough Glibc at CCI and its binaries can be consumed as "compatible" when more recent glibc is required. (Provided glibc versions compatibility is declared globally that should be possible with Conan 2.0)

If a user needs a binary with incompatible glibc - well, the binary should be built from sources. But that's much better than an unexpected error during link/run time. That's what I have now with various CCI binaries that were built with an unspecified glibc version.

**Comment by memsharded** [comment]
Yes, conanCenter shouldn't build all the combinations for glibc. It should build just one, a compatible old one is a good choice. Then, the new compatibility can fallback to it even when a more modern glibc version is explicitly required. 

The "default" new global compatibility is now under investigation. The new possibilities of the global compatibility.py can be powerful, but also maybe easily abused. We need to consider the different implications, we cannot guarantee that we will provide a default glibc compatibility. But at least the possibility of doing it and managing it for your own binaries in a way more efficient way than in the past will be possible.
