### ISSUE TITLE
[bug] Wrong auto detected arch setting for Raspberry Pi 4b

### ISSUE THREAD

**Issue by StellaSmith** [conan-io/conan#10841]
see related [issue in cci](https://github.com/conan-io/conan-center-index/issues/9866)

Seems like Conan generates the default profile with `arch=armv7`. While this kinda makes sense since the raspberry os has exclusively been a 32bit os up until recently, this is no longer the case nowdays

### Environment Details (include every applicable attribute)
  * Operating System+version: **Raspberry Pi OS 64bit Lite 11 (bullseye)**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.46.2**
  * Python version: **Python 3.9.2**

### Steps to reproduce (Include if Applicable)
```sh
conan profile new --detect default
```

**Comment by memsharded** [comment]
Can you please report what Python ``platform.machine()`` is returning on that RPI?

**Comment by StellaSmith** [comment]
Seems to report `'aarch64'`

**Comment by memsharded** [comment]
Weird. The code for detection is already:

```python
    elif "aarch64" in machine:
        return "armv8"
```
So it seems it should return armv8.

Is Conan running on the same Python env?

Please note, that in any case, the auto-detection is not to be relied on. The recommended practice for production is to use your own defined profiles files (and you can manage them with ``conan config install`` if you want). Conan 2.0 is removing the automatic detection and requiring a explicit ``conan profile detect`` always, and it will contain warnings that such an output is not stable.

**Comment by StellaSmith** [comment]
Hmm, and now can't reproduce the error. I'm pretty sure I never touched the `arch` setting so it must had come from the autodetection.
Well, since i can't reproduce it i will close this issue, assuming it was an error on my part.

**Comment by memsharded** [comment]
> Hmm, and now can't reproduce the error. I'm pretty sure I never touched the arch setting so it must had come from the autodetection.

It could be that the auto-detection was ran some time ago, in an older Conan version or something like that.
