### ISSUE TITLE
[bug] components in cpp_info seem to have no default directories

### ISSUE THREAD

**Issue by JonathanGirardeau** [conan-io/conan#10859]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc version 9.3.0
  * Conan version: 1.44.1
  * Python version: 3.8.10

I started to use components to fix an issue with link order of libraries of a package. Unfortunately it seems the usual default values of cpp_info are not set anymore.

I create a pkgB, it contains 2 librairies libB1 and libB2. pkgB requires pkgA, libB2 requires libB1.
```
class PkgBConan(ConanFile):
[...]
    requires = [("pkgA/1.2.3")]
[...]
    def package(self):
        self.copy("*.a", dst="lib", keep_path=False)
[...]
    def package_info(self):
        self.cpp_info.components["B1"].libs = ["libB2"]
        self.cpp_info.components["B2"].libs = ["libB2"]
        self.cpp_info.components["B2"].requires = ["B1"]
```
When I try to build pkgC that requires pkgB, it seems libdirs, includedirs, dependencies, etc of pkgB are empty. I use CMakeDeps generator and variables in pkgB-release-x86_64-data.cmake are empty:
```
set(pkgB_INCLUDE_DIRS_RELEASE )
set(pkgB_LIB_DIRS_RELEASE )
[...]
set(pkgB_pkgB_B1_INCLUDE_DIRS_RELEASE )
set(pkgB_pkgB_B1_LIB_DIRS_RELEASE )
[...]
set(pkgB_pkgB_B2_INCLUDE_DIRS_RELEASE )
set(pkgB_pkgB_B2_LIB_DIRS_RELEASE )
```
I don't understand why cpp_info variable are not set with default values (libdirs=["lib"], includedirs=["include"] etc) as soon as I start to use component.

1.As I understand from conan docs, I need to explicitly set all components dependencies, even if I set the dependency on the package: _"The requires list has to be populated explicitly with the list of components from other packages to use"_. So I must add in `package_info()`: 
```
        self.cpp_info.components["B1"].requires = ["pkgA"]
        self.cpp_info.components["B2"].requires = ["pkgA"]
```
Is it right ?

2. I found in conan docs that components has the same default directories than cpp_info so why directories (ibdirs, includedirs etc) are empty when I try to build pkgC ?
_"The interface of the Component object is the same as the one used by the cpp_info object and has the same default directories."_

**Comment by memsharded** [comment]
Hi @JonathanGirardeau 

This is by design. When having components it is typical that they are build in different directories, they have includes in different directories, etc.  So components need to define their ``libdirs``, ``includedirs``, etc explicitly, as they are not defaulted to anything.

In any case, the lib order in ``self.cpp_info.libs`` should be respected in consumers for linking. If that is the issue, if you could report it with something we can reproduce, we could have a look at it.

**Comment by JonathanGirardeau** [comment]
Thank u @memsharded for the quick answer.

Ok, it is not really convenient in my case but I understand. However I think the doc should be modified because this sentence seems to say the opposite: "The interface of the Component object is the same as the one used by the cpp_info object and has the same default directories." (https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info-attributes-reference).

You mean I can just set self.cpp_info.libs in the right order instead of using components ?

**Comment by memsharded** [comment]
> "The interface of the Component object is the same as the one used by the cpp_info object and has the same default directories." (https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info-attributes-reference).

That seems it could be some bad explanation (probably a language issue) in the docs. Up to my knowledge components never had a default value for directories, I think it pretends to say that it has the same ``includedirs``, ``libdirs`` attributes.


> You mean I can just set self.cpp_info.libs in the right order instead of using components ?

Yes, absolutely, that is the goal, and if not, should be investigated. Components should only be necessary for some advanced cases, like very big frameworks with multiple libraries that can be linked separately

**Comment by JonathanGirardeau** [comment]
I finally just set self.cpp_info.libs in the right order and stop trying to setup components, it works :+1:

**Comment by boussaffawalid** [comment]
I had the same issue, the documentation mentioned that```The interface of the Component object is the same as the one used by the cpp_info object and has the same default directories.``` and that was confusing,  I expected `libdirs` to be defaulted to `lib` and `bindirs` to be defaulted to `bin`

maybe just updating the documentation here, even though I think having default values in components make sense.
