### ISSUE TITLE
[bug] ConanException: Duplicated requirement ignition-cmake/2.10.0 != ignition-cmake/2.10.0

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10853]
from https://github.com/conan-io/conan-center-index/pull/9872

if `test_package` uses an explicit requires like:
```
    def requirements(self):
        self.requires("ignition-cmake/2.10.0@")
```
it fails with the weird error message:
```
ConanException: Duplicated requirement ignition-cmake/2.10.0 != ignition-cmake/2.10.0
```
however, for sure it's the same requirements.
therefore, it should be either no error at all, or error message has to be different (as requirement is equal)

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by memsharded** [comment]
It is not clear how the linked issue relates, I only see there:

```python
def requirements(self):
         self.requires(self.tested_reference_str)
```

Could you provide an example starting with a ``conan new hello/0.1 -m=cmake_lib`` template, please?

**Comment by SSE4** [comment]
> It is not clear how the linked issue relates, I only see there:
> 
> ```python
> def requirements(self):
>          self.requires(self.tested_reference_str)
> ```
> 
> Could you provide an example starting with a `conan new hello/0.1 -m=cmake_lib` template, please?

he already pushed more commits. it's:
https://github.com/conan-io/conan-center-index/blob/b5e8fb0cd9556f7f718a064b4c15c75c6f059b16/recipes/ignition-cmake/all/test_package/conanfile.py

**Comment by memsharded** [comment]
Oh, I see. 

Yes, if they do a explicit ``self.requires("ignition-cmake/2.10.0@")`` and Conan itself is injecting its own one, they will collide and raise. This is expected.

I don't think fixing this message is worth it:
- Already documented and recommended the way to go, with ``test_type = "explicit"``
- Conan 2.0 already stopped injecting the reference
- The ``conan new`` templates are updated with this
