### ISSUE TITLE
Conan simdjson install failed

### ISSUE THREAD

**Issue by meftunca** [conan-io/conan#10851]
### Environment Details (include every applicable attribute)
  * Operating System+version: Macos Big Sur
  * Compiler+version:
    Homebrew clang version 13.0.1
    Target: x86_64-apple-darwin20.6.0
    Thread model: posix
    InstalledDir: /usr/local/opt/llvm/bin 
  * Conan version:  1.46.2
  * Python version: 3.9

### Logs (Executed commands with output) (Include/Attach if Applicable)
conan install .. -s build_type=Release
Error Message:
ERROR: Missing binary: simdjson/1.0.2:0ceb8568b902441fd2e44492a2a13034b8c85355
ERROR: Missing prebuilt package for 'simdjson/1.0.2'

**Comment by memsharded** [comment]
Hi @meftunca 

It didn't fail, it just doesn't have a precompiled binary for your configuration.
Please read the whole error message. You are removing some important parts of the message, like the URL that guides you to an explanation and solution of what is happening, or the recommendation to build from source when this happens.

**Comment by meftunca** [comment]
@memsharded  it's done. Thanks :)
