### ISSUE TITLE
[bug] MSBuildToolchain doesn't work as intended when using vs_layout

### ISSUE THREAD

**Issue by anderson-dev** [conan-io/conan#10869]
When I use `vs_layout` as [suggested](https://github.com/conan-io/conan/issues/9330#issuecomment-1046322806), all deps props are generated in x64/$(BuildConfig)/generators folder which works well. However, `conantoolchain.props` is also placed there instead of somewhere agnostic to the current $(BuildConfig). As a result, when I add the individual Debug/Release conantoolchain.props files, if the VS IDE opens defaulting to a $(BuildConfig) that is not the one that was used for `conan install`, the project fails to load.

Correct me if I'm wrong, but isn't the purpose of `conantoolchain.props` to "switch" the current $(BuildConfig) to the one that conan installed with so that the project loads correctly? If so, it seems like `vs_layout` is incompatible with `MSBuildToolchain`

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 21H2
  * Compiler+version: N/A
  * Conan version: 1.45.0
  * Python version: N/A

### Steps to reproduce (Include if Applicable)
1. use the default `vs_layout` in the `layout` method of conanfile.py
2. generate both debug/release deps
3. add `x64/Debug/generators/conantoolchain.props` to the Debug config of the project
3. add `x64/Release/generators/conantoolchain.props` to the Release config of the project
4. `git clean -Xdf`
5. `conan install . user/channel`
6. `conandeps.props`, `conantoolchain.props`, and `conantoolchain_release_x64.props` are created in the `x64/Release/generators` folder
7. open VS IDE
8. because VS defaults to `Debug` build config, it fails to load the project due to `x64/Debug/generators/conantoolchain_debug_x64.props` not being found

**Comment by memsharded** [comment]
Could you please try using my source branch in https://github.com/conan-io/conan/pull/10760? That PR should fix it, as commented in https://github.com/conan-io/conan/issues/9330#issuecomment-1076097283. 
It will be released soon in 1.47

**Comment by anderson-dev** [comment]
I wasn't able to clone and test with the PR that you referenced yet, but I overrode the settings to match the changes you made to vs_layout:
```
def layout(self):
        vs_layout(self)

        # temp workaround until Conan 1.47 is released
        if self.settings.arch != "x86":
            arch = msbuild_arch(self.settings.arch)
            base = os.path.join(arch, str(self.settings.build_type))
        else:
            base = str(self.settings.build_type)
        self.folders.build = "."
        self.folders.generators = "conan"
        self.folders.outdir = base
```

This resolves the issue now that the `conantoolchain.props` & `conandeps.props` are generated to the same folder regardless of build_type.

However, would you be open to exposing the `base` variable of `vs_layout` as something like `self.folders.outdir` as seen above so when importing or packaging, it uses the correct build_type dependent folders? Otherwise imported dlls are in the wrong folder and packaging sometimes packages debug versions of my built artifacts when creating a release package or vice versa.

Something like this:
```
def imports(self):
        self.copy("*.dll", dst=self.folders.outdir, src="bin")

def package(self):
        # pick up only artifacts for specific build_type
        self.copy("*.lib", src=self.folders.outdir, dst="lib", keep_path=False)
        self.copy("*.dll", src=self.folders.outdir, dst="bin", keep_path=False)
```

**Comment by memsharded** [comment]
Wouldn't it make sense to use the ``self.cpp.build.bindirs`` directories? (it is a list, you can use the ``[0]`` first element). 

Also a couple of quick hints towards future:
- ``self.copy`` is being replaced by ``from conan.tools.files import copy`` (available in 1.X)
- ``imports()`` will dissapear in Conan 2.0. Import operations will be explicit ``copy()`` in the ``generate()`` methods.

**Comment by anderson-dev** [comment]
yes makes sense; Is it guaranteed to always be the first element?

will progressively look into transitioning to 2.0 stuff thanks

**Comment by memsharded** [comment]
> yes makes sense; Is it guaranteed to always be the first element?

That, only the recipe creator knows. They can have more than 1 bindirs, and if that is the case, they should decide to which of them they want to put the other binaries to.

In practice, I have never seen more than 1 ``bindirs`` folder, so yes, that should be good enough.
