### ISSUE TITLE
[question] tool_requirement through virtualrunenv for separated host and build profiles

### ISSUE THREAD

**Issue by bukulin** [conan-io/conan#10863]
# General Description
I have a fairly big multi-platfom cmake project with >1000 targets where most of the runtime and tool (formerly build) requirements are handled with conan. I've reached a point where I want to install cmake with conan, as well. (Up to this point everything went well, the whole conan project is great including the documentation! Thanks guys!)

So my problem is, that I want to use Release version of cmake even for a Debug build profile. This is crucial for me, because CMake configuration and generation takes around 17 minutes with Debug version of CMake versus 2 minutes with Release version of CMake on a decent machine. The solution seems to be easy, because I can separate host and build profiles. **However** if I use virtualrunenv generator, the cmake tool does not appear in PATH.

# System Details
conan versions checked:
* 1.44.0
* 1.46.0

build OSs checked:
* Windows 10 Enterprise (conan installed with its own installer)
* Linux (gentoo, linux-5.15.23, python-3.9.9, pip-21.3.1, conan installed with pip)

# Simplified Example
`conanfile.txt`:
```
[requires]
zlib/1.2.11

[tool_requires]
cmake/3.22.3

[generators]
cmake_paths
virtualrunenv

[options]
zlib:shared=True
```

Installing the dependencies:
```
...\build_cross> conan install --profile:host=default_debug --profile:build=default ../
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    zlib/1.2.11:ff82a1e70ba8430648a79986385b20a3648f8c19 - Cache
Build requirements
    cmake/3.22.3 from 'conan-center' - Cache
Build requirements packages
    cmake/3.22.3:0a420ff5c47119e668867cdb51baff0eca1fdb68 - Cache

Installing (downloading, building) binaries...
cmake/3.22.3: Already installed!
cmake/3.22.3: Appending PATH environment variable: d:\work\.conan\data\cmake\3.22.3\_\_\package\0a420ff5c47119e668867cdb51baff0eca1fdb68\bin
zlib/1.2.11: Already installed!
conanfile.txt: Applying build-requirement: cmake/3.22.3
conanfile.txt: Generator virtualrunenv created activate_run.bat
conanfile.txt: Generator virtualrunenv created deactivate_run.bat
conanfile.txt: Generator virtualrunenv created environment_run.bat.env
conanfile.txt: Generator virtualrunenv created activate_run.ps1
conanfile.txt: Generator virtualrunenv created deactivate_run.ps1
conanfile.txt: Generator virtualrunenv created environment_run.ps1.env
conanfile.txt: Generator virtualrunenv created activate_run.sh
conanfile.txt: Generator virtualrunenv created deactivate_run.sh
conanfile.txt: Generator virtualrunenv created environment_run.sh.env
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator cmake_paths created conan_paths.cmake
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
```

After activating the run environment CMake's bindir is not injected into the `PATH`:
```
PS ...\build_cross> .\activate_run.ps1
(conanrunenv) PS D:\work\snippets\conan_tool_requires\build_cross> (Get-Command cmake).Path
c:\bin\cmake-3.13.4-win64-x64\bin\cmake.exe    # <- this is the installed version of cmake, not the one required through conan
```

If I do not discriminate host and build profiles, everithing works as expected:
```
PS ...\build> conan install ../
# ...
PS ...\build> .\activate_run.ps1
(conanrunenv) PS ...\build> (get-command cmake).Path
d:\work\.conan\data\cmake\3.22.3\_\_\package\0a420ff5c47119e668867cdb51baff0eca1fdb68\bin\cmake.exe   # <- this is OK
```

# Related documentation
I've checked the following pages:
https://docs.conan.io/en/latest/devtools/build_requires.html
https://docs.conan.io/en/latest/devtools/create_installer_packages.html

# Questions
1) Is that somehow possible to inject bindirs of required tools from a build (i.e. not hots) requirement chain? 
1) This paragraph in the documentation is very similar: https://docs.conan.io/en/latest/devtools/create_installer_packages.html#using-the-tool-packages-in-your-system, but I think I have to declare CMake in the `tool_requires` section not in the `requires` section, considering the deployment. Is that right?

Any help, suggestion is highly appreciated, thank you in advance!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @bukulin 

It seems you are using only ``virtualrunenv``, while ``cmake`` is a ``tool_require``. It is intended to run at **build time**. So you should be declaring the ``VirtualBuildEnv`` generator (not the upper case, to use the modern one) instead. Please try that and let me know.

**Comment by bukulin** [comment]
Hi @memsharded 

The `VirtualBuildEnv` does its job perfectly, and works pretty well on linux with bash and on windows with cmd. But the command interpreter of our choice is PowerShell on windows. I'm not a windows/PS expert by any means, but I tried to inject variables from bat files into a PS environment and I failed. :)

The old set of virtual environment generators (`virtualbuildenv`, `virtualrunenv`) do support PS. Is there an intention to implement such a support for the new virtual environment generators (`VirtualBuildEnv`, `VritualRunEnv`)? Or can I implement it without the modification of the installed conan source?

**Comment by memsharded** [comment]
Hi @bukulin 

Yes, the ``VirtualBuildEnv`` generator already can generate PS. The part that is not automatic is "selecting" PS as output format and consuming it. We will be working on it when possible. In the meantime you might try with:

```python
def generate(self):
     vb = VirtualBuildEnv(self)
     envvars = vb.vars()
     envvars.save_ps1("myenv.ps")
```
Applying it automatically in ``self.run()`` is still not there. The issue you want to track is https://github.com/conan-io/conan/issues/9898 (we might close this, if the question was solved, and follow up on the other one)

**Comment by bukulin** [comment]
Great! Thank you for the help!
