### ISSUE TITLE
c语言依赖管理终于找到你

### ISSUE THREAD

**Issue by jiftle** [conan-io/conan#1086]
很开心，c语言依赖管理终于有了。

**Comment by memsharded** [comment]
Glad that you liked the project. Please take into account:
- The project language is English. Many of us are not native speakers, but it is fine. Please communicate in English.
- Github issues are more related to real questions, feature requests and bug reports. For general feedback and discussion, better in twitter
Thanks for your feedback!

**Comment by jiftle** [comment]
thank you , I very like this project. china developer like it.
