### ISSUE TITLE
[question] [1.46.2] build dependencies not detectable in json output

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#10876]
When building missing dependencies while installing conan dependencies I am also using the --json parameter to be able to determine which dependencies have been built from source.
Some recipes have build dependencies that are also built from source, which will also be listed in the created json output. However there appears to be no way (that I have seen?) to tell them apart from actual dependencies of the built package.

I would like to be able to determine only the actual dependencies that were built from source (ie. those that conan install would have to pull) once the building of the missing packages is done. Is there currently a definitive way to do this, if not can we get that?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Have you tried the ``conan info`` command? That should report the "context" of each package in the graph, and you can have more info with its json too.

**Comment by Sil3ntStorm** [comment]
That looks interesting, especially the dry-build option. Looks as though it can tell beforehand which packages need to be built as well. And if there are remotes that have it.
Should work out just fine, thanks.
