### ISSUE TITLE
[bug] While system_requirement method, recipe fails due to an expectation of an older version of Jninja2

### ISSUE THREAD

**Issue by selsiddharthsingh** [conan-io/conan#10870]
### Environment Details 
  * Operating System+version: Windows 10 Enterprise/10.0.19043
  * Conan version: 1.46.2
  * Python version: 3.8.10

### Steps to reproduce
Adding a system_requirement method with the above conan version in a conanfile.py and executing the recipe.
System requirement is trying to install python serial package.

```
def system_requirements(self):
        import pip
        if hasattr(pip, "main"):
            pip.main(["install", "serial"])
```

It is expecting version <3 >=2.9 but conan 1.46.2 installs Jninja2-3.0.3
Recipe fails with error:
```
conanfile.py: ERROR: while executing system_requirements(): The 'Jinja2<3,>=2.9' distribution was not found and is required by conan
ERROR: Error in system requirements
```

### Logs 
- Conan output for conan install
```
Cross-build from 'Windows:x86_64' to 'None:armv8a'
Installing (downloading, building) binaries...
cli-tools/1.0@fenix/approved: Already installed!
fenix-tools/1.0.33@fenix/approved: Already installed!
gcc-aarch64-elf/8.3.0@arm/approved: Already installed!
libfftfixture/1.0.8@fenix/approved: Already installed!
conanfile.py: Applying build-requirement: cli-tools/1.0@fenix/approved
conanfile.py: Applying build-requirement: gcc-aarch64-elf/8.3.0@arm/approved
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Generator virtualenv created activate.bat
conanfile.py: Generator virtualenv created deactivate.bat
conanfile.py: Generator virtualenv created environment.bat.env
conanfile.py: Generator virtualenv created activate.ps1
conanfile.py: Generator virtualenv created deactivate.ps1
conanfile.py: Generator virtualenv created environment.ps1.env
conanfile.py: Generator virtualenv created activate.sh
conanfile.py: Generator virtualenv created deactivate.sh
conanfile.py: Generator virtualenv created environment.sh.env
conanfile.py: Generator make created conanbuildinfo.mak
conanfile.py: Aggregating env generators
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
conanfile.py: ERROR: while executing system_requirements(): The 'Jinja2<3,>=2.9' distribution was not found and is required by conan
ERROR: Error in system requirements
```

**Comment by selsiddharthsingh** [comment]
This is the issue with the dependency I was installing and not with conan

**Comment by memsharded** [comment]
Hi @selsiddharthsingh 

This is not a bug per-se. Conan is requiring some Jinja version and the other package that you are trying to install from ``system_requirements()`` is incompatible with it. 

In the general case, I would try to avoid that, ``system_requirements()`` might help with some ``apt-get`` installation, for example, but having Conan itself modify the python environment that it is running inside, is dangerous. For Python packages, I would try to pre-install them together with Conan, to detect earlier possible inconsistencies.

**Comment by selsiddharthsingh** [comment]
Hi @memsharded, I also thought that it is due the package incompatibility, but the package I am downloading is not dependent on Jninja. So that is a bit weird. But your point of conan editing the environment it is running is good, I will keep python packages installation outside conan. Thanks for the reply.

**Comment by memsharded** [comment]
Yes, there is something weird there. Because ``requirements.txt`` contains:

```
Jinja2>=2.9, <3.0.0;python_version<='2.7'
MarkupSafe<=2.0.1;python_version<='2.7'
Jinja2>=3.0, <4.0.0;python_version>='3'
```
So the jinja<3 only applies for Py27, which shouldn't be the case if you are running Py38. There might be something in the way ``pip.main`` executes.

In any case, if you can keep that outside of Conan, I think that overall will be simpler, so maybe not worth to investigate this further.

**Comment by selsiddharthsingh** [comment]
I agree. Closing this.
