### ISSUE TITLE
[feature] Support config set for global.conf

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#10883]
So far, it's only possible to read properties from [global.conf](https://docs.conan.io/en/latest/reference/config_files/global_conf.html) using the command conan [config](https://docs.conan.io/en/latest/reference/commands/consumer/config.html).

It would be nice adding edit support too. We do not need a new subcommand, only a new argument:

    conan config set --global tools.cmake.cmaketoolchain:generator=Ninja

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
We don't plan to add plain text file edition capabilities with Conan commands anymore. At most we will give a command that return the path to the file. ``conan config list`` does not read global.conf, not any other command displays the file.

**Comment by uilianries** [comment]
So users will need to edit and read using the old fashion way, cat and echo ?

**Comment by memsharded** [comment]
> So users will need to edit and read using the old fashion way, cat and echo ?

This is more or less the idea, yes. Why building a custom CLI functionality for editing text files? It seems a bit cumbersome. 
In any case, those files should be very rarely edited by users, and ``conan config install`` should manage them.

**Comment by uilianries** [comment]
Good enough. Thank you for clarifying this.
