### ISSUE TITLE
[bug] get_safe errors out when not defined

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#10887]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 x64
  * Compiler+version: VS 2022
  * Conan version: 1.46.2
  * Python version: 3.9.7

### Steps to reproduce (Include if Applicable)
The following code in a recipe will cause a warning when used with a profile that does not specify compiler.cppstd option.
```
def configure(self):
    min_cppstd = "17"
    print(self.settings.get_safe("compiler.cppstd"))
    if self.settings.get_safe("compiler.cppstd"):
        print('test')
        tools.check_min_cppstd(self, min_cppstd)
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=msvc
compiler.runtime_type=Release
compiler.version=193
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

None
ERROR: test/0.0.1: 'settings.compiler.cppstd' value not defined
```

**Comment by Sil3ntStorm** [comment]
Okay so this only happens with the old profile that was created with an earlier conan version that detected VS2022 as msvc 193. Current conan versions again detect it as Visual Studio 17. With such a profile this error does not appear even if the value is not set:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

Yes, this is expected. Initially we wanted to introduce the ``msvc`` new compiler setting, but it was a bit too aggresive, because it only works well with the new integrations. So it was reverted back to ``Visual Studio``.

``msvc`` and Conan 2.0 will require to have defined the ``cppstd`` value explicitly, as opposed to 1.X which can be undefined.
So not really a bug, but different behaviors of the 2.0-ready things.

**Comment by Sil3ntStorm** [comment]
I just find it weird that a get_safe function, which supposedly checks but not fails on unset is supposed to well, not throw the hands in the air if the thing that it is supposed to check for happens.
But I don't know the conan internals, so I guess that's just the way it is then. Once conan 2.0 eventually lands this might not be an issue anymore, provided it actually checks for all the other things before throwing such error.
I just assumed it would be a generic function which doesn't know about deeper things.

**Comment by memsharded** [comment]
I don't think it is really failing in the ``get_safe()`` call, it is failing in another validation inside Conan internals. You can check by adding another print() to your code, to see it is not raising there, but the method executes without problems

**Comment by Sil3ntStorm** [comment]
I think I did that after posting the issue, not sure anymore.
