### ISSUE TITLE
[question] Profile option depending on build type?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#10881]
Hi,

I have a strange issue.  For our packages in release mode we set some extra package options - which add some release specific tinkering to the package (e.g. digital signature). How can I set this package option in a profile?
E.g. is there a way to specify a profile option depending on the build_type? Or should I simply remove the option if build_type != Debug in configure()?

**Comment by memsharded** [comment]
Hi @harsszegi 

Not fully sure what you mean, the title might be misleading. If you want to apply some logic directly in the profiles, you can use the profile .jinja extension, and write jinja templates (can use conditionals, variables, loops...)

If something is purely conditional to the build_type, then maybe it is not an option? The option should in theory be mostly decoupled from the settings. But yes, if an option doesn't apply for some settings, you can remove it, even before it gets a value, in ``config_options()`` method. But if that needs to be done in all recipes, not completely sure. Maybe it is a custom settings and not an option? 

If you can elaborate a bit more about the option you are thinking of, which values, and which constraints, etc, that might help us to understand.

**Comment by harsszegi** [comment]
@memsharded Practically it is really a “digital signature” kind of thingie. We are producing 3 flavors, release, release+signature, debug.
Obviously release+debug don’t have signature,release-signature does have. From consumers’ perpective only release-signature and debug should match (from package id’s perspective).
This option needs to be in a profile as we have several consumers who needs to consume the release-signature variant of the mentioned package, but they themselves don’t need to do any kind of digital-signature stuff. So this option in the profile would only help the consumers, so that the proper package_id for the package having digital signature would be generated during conan install. And obviously we want to prevent that consumers “by default” would consume a pure “release” variant of the package (without digital signature).

**Comment by memsharded** [comment]
> Practically it is really a “digital signature” kind of thingie. We are producing 3 flavors, release, release+signature, debug.

Have you considered adding a ``releasesigned`` in settings.yml ``build_type``?

> From consumers’ perpective only release-signature and debug should match (from package id’s perspective).

Is this a typo? You mean release and release-signature? What is the match, should they have an identical package_id? (I don't think so, if they are different artifacts)

> This option needs to be in a profile as we have several consumers who needs to consume the release-signature variant of the mentioned package, but they themselves don’t need to do any kind of digital-signature stuff. So this option in the profile would only help the consumers, so that the proper package_id for the package having digital signature would be generated during conan install. 

Is the consumption "all or nothing"? Should all the installed packages be signed, or is it ok if only some are?

> And obviously we want to prevent that consumers “by default” would consume a pure “release” variant of the package (without digital signature).

What kind of prevention? Maybe just not releasing/publishing the bare ``release`` binaries, and only releasing the ``releasesigned`` binaries?

Do you have control of the consumers machines? Are they your developers/users? Have you considered adding hooks to validate if installed packages are signed or not?

**Comment by harsszegi** [comment]
> Have you considered adding a `releasesigned` in settings.yml `build_type`?

Why we haven't really added a new releasesigned target is that we have only a handful of packages requiring digital dignature out of the ~100 we use.

> Is this a typo? You mean release and release-signature? What is the match, should they have an identical package_id? (I don't think so, if they are different artifacts)

Well what I wanted to say is of course that a debug build of the consumer should pick the debug variant of the digitally-signed-package, and the release version of the consumer should pick the release-signed version of the digitally-signed-package. So YES, it should NEVER match the unsigned release variant.

Signing the "final release" package can only be done by a handful of people and the CI obviously. But still we have developer who would like to try out their changes in the package and they would like to see it in the consumer of the package.
This we would like to allow only via some tinkering, e.g. if the "signed" option for the package would be forcefully set to false
from the commandline (from the consumer).

> 
> Is the consumption "all or nothing"? Should all the installed packages be signed, or is it ok if only some are?

Nope, among the dependencies of the consumer only this single package is signed, the rest ~20 packages are not.

> 
> What kind of prevention? Maybe just not releasing/publishing the bare `release` binaries, and only releasing the `releasesigned` binaries?

Yes, precisely. We want to make sure that when the consumer package is built by the CI it must never consume a digitally
unsigned package.

> 
> Do you have control of the consumers machines? Are they your developers/users? Have you considered adding hooks to validate if installed packages are signed or not?

Yes, we have control over everything, packages, profiles, CI, anything.

**Comment by harsszegi** [comment]
Thanks, closing it

**Comment by memsharded** [comment]
> Yes, we have control over everything, packages, profiles, CI, anything.

If you have full control, maybe I would explore the new ``profile.py`` plugin and using user ``hooks``.
