### ISSUE TITLE
[bug] conan.tools.microsoft.msvc_runtime_flag doesn't work for clang-cl (returns an empty value)

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10892]
see https://github.com/conan-io/conan-center-index/issues/9834

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Version 21H2 (OS Build 19044.1586)
  * Compiler+version: clang version 13.0.0
  * Conan version: Conan version 1.47.0-dev
  * Python version: Python 3.9.7

### Steps to reproduce (Include if Applicable)

```
git clone https://github.com/conan-io/conan-center-index.git
conan create conan-center-index/recipes/openssl/1.x.x openssl/1.1.1m@ -pr ms_clang_cl -k
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
Configuration for profile ms_clang_cl:

[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.runtime=MD
compiler.version=13
os=Windows
[options]
[conf]
[build_requires]
*: ninja/1.10.2
[env]
PATH=['"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\Llvm\\bin"']
CC=clang-cl
CXX=clang-cl
CONAN_CMAKE_GENERATOR=Ninja
CONAN_CMAKE_MAKE_PROGRRAM=ninja

```

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/10898 adds support for clang ``runtime`` following the new ``msvc`` model.
