### ISSUE TITLE
[feature] cld2 package

### ISSUE THREAD

**Issue by ehartford** [conan-io/conan#10897]
requesting cld2 package
https://packages.ubuntu.com/focal/libcld2-dev
https://github.com/CLD2Owners/cld2

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @ehartford 

This request should be done to the https://github.com/conan-io/conan-center-index repo.

Please read the readme there and follow the guidelines to request this library. Thanks!
