### ISSUE TITLE
[question] What is the recommended project directory structure for multiple recipes?

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#10899]
Hi,

If I have a (closed-source) project that has more than one recipe, for instance, 1. a full package with source code, 2. a distributable package (bin) that has only precompiled binaries, and 3. a headers package that has the shared headers _only_ (for other projects to include while developing).
What is the best practice of the _project directory structure_ for those three recipes?

BTW, could you please share an example of an open-source project (e.g. on github) that has a similar (or even more complex) case?

Thanks,

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Bassem-Ramzy 

We are trying to implement best practices for layouts in the ``conan new`` templates. For example the ``conan new hello/0.1 -m=cmake_lib`` template would be a canonical example for case 1). For case 3), the legacy ``conan new -b`` aimed to cover that case, but now it is obsolete. But it should be just a simplified version of the ``cmake_lib`` template of case 1).

For those cases, the built-in layouts, like ``cmake_layout()`` or ``vs_layout()`` would be the implementation of the layout of such project directory structure.

That is for each individual recipe.
For the global project/repo, the conan-center-index repo is a typical example, just using folders, each folder containing one package, and each folder containing its own conanfile. I am not sure if this helps with your question
