### ISSUE TITLE
[bug] set(CONAN_DISABLE_CHECK_COMPILER True) Not work!!!

### ISSUE THREAD

**Issue by sirlordt** [conan-io/conan#10890]
I try to compile mongo c++ driver but not work i always get the same error.

I try the combinations

set(CONAN_DISABLE_CHECK_COMPILER True) #not work
set(CONAN_DISABLE_CHECK_COMPILER TRUE) #not work
set(CONAN_DISABLE_CHECK_COMPILER "TRUE") #not work
set(CONAN_DISABLE_CHECK_COMPILER "True") #not work
set(CONAN_DISABLE_CHECK_COMPILER 1) #not work
set(CONAN_DISABLE_CHECK_COMPILER "1") #not work

Please look the screenshot to more details.

Before of 

include(${CMAKE_BINARY_DIR}/conan.cmake)

![image](https://user-images.githubusercontent.com/4441192/160201127-72ac9ba6-f51d-4406-8543-476b156f18ae.png)

After 

include(${CMAKE_BINARY_DIR}/conan.cmake)

![image](https://user-images.githubusercontent.com/4441192/160201655-d01099b0-e109-4e0a-851a-f20032de38c7.png)

**Comment by sirlordt** [comment]
Fixed!!! i deleted the build folder. And regenerated full build folder.

set(CONAN_DISABLE_CHECK_COMPILER True CACHE BOOL "" FORCE )

**Comment by memsharded** [comment]
Glad that you found how to solve it. 
Yes, the CMake cache can be tricky. I often remove it and start from scratch if something is behaving weirdly with Cmake.
