### ISSUE TITLE
[bug] Conan does not work on macOS 12.1 and latest 12.3

### ISSUE THREAD

**Issue by SimplyLiz** [conan-io/conan#10896]
I've tried Conan on my MacBook Air m1 with macOS Monterey 12.1 and it didn't work because it could not find os version 12.1

```
ERROR: Invalid setting '12.1' is not a valid 'settings.os.version' value.
Possible values are ['None', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15', '11.0', '12.0', '13.0']
```

I then updated to macOS 12.3 and now it still doesn't work. but now because of compiler version
```
-- Conan executing: /opt/homebrew/bin/conan install . --build missing --settings build_type=RelWithDebInfo --settings compiler=apple-clang --settings compiler.version=13.1 --settings compiler.libcxx=libc++ --settings os.version= --settings arch=x86_64
ERROR: Invalid setting '' is not a valid 'settings.os.version' value.
Possible values are ['None', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15', '11.0', '12.0', '13.0']
```

### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Monterey 12.3 (latest) - M1 (arm64-apple-darwin21.4.0)
  * Compiler+version: Apple clang version 13.1.6 (clang-1316.0.21.2) 
  * Conan version: 1.46.2
  * Python version: I've updated to Python 3.9.10. (also tried with system python3 3.8.9)

### Steps to reproduce (Include if Applicable)
Not sure about that, Conan is part Cytopia and it detects stuff automatically.
Here's the command and with the autodetected settings.
conan install sdl2 --build missing --settings build_type=RelWithDebInfo --settings compiler=apple-clang --settings compiler.version=13.1 --settings compiler.libcxx=libc++ --settings os.version=12.1 --settings arch=x86_64

### Logs (Executed commands with output) (Include/Attach if Applicable)

-- Using conan: ON
Using /opt/homebrew/bin/sccache for speeding up build
-- Adding Conan dependency SDL2
-- Adding Conan dependency SDL2_image
-- Adding Conan dependency SDL2_ttf
-- Adding Conan dependency ZLIB
-- Adding Conan dependency LibNoise
-- Adding Conan dependency LIBPNG
-- Adding Conan dependency OpenAL
-- Adding Conan dependency VorbisFile
-- Adding Conan dependency Angelscript
-- Configuring packages for RelWithDebInfo
-- Release only libraries:
-- Executing Conan:         REQUIRES sdl/2.0.20;sdl_image/2.0.5;sdl_ttf/2.0.18;zlib/1.2.11;libnoise/1.0.0;libpng/1.6.37;openal/1.19.1;vorbis/1.3.7;angelscript/2.35.0
        GENERATORS cmake_multi
        BUILD_REQUIRES

        OPTIONS
        SETTINGS build_type=RelWithDebInfo;compiler=apple-clang;compiler.version=13.1;compiler.libcxx=libc++;os.version=;arch=x86_64

-- Conan: checking conan executable
-- Conan: Found program /opt/homebrew/bin/conan
-- Conan: Version found Conan version 1.46.2
-- Conan executing: /opt/homebrew/bin/conan install . --build missing --settings build_type=RelWithDebInfo --settings compiler=apple-clang --settings compiler.version=13.1 --settings compiler.libcxx=libc++ --settings os.version= --settings arch=x86_64
ERROR: Invalid setting '' is not a valid 'settings.os.version' value.
Possible values are ['None', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15', '11.0', '12.0', '13.0']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
CMake Error at cmake/conan.cmake:651 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/DependenciesFunctions.cmake:245 (conan_cmake_install)
  cmake/DependenciesFunctions.cmake:258 (_conan_install)
  CMakeLists.txt:172 (resolve_conan_dependencies)

-- Configuring incomplete, errors occurred!

**Comment by SimplyLiz** [comment]
sorry. seems that the bug was on our side

**Comment by memsharded** [comment]
> sorry. seems that the bug was on our side

No prob, happy to hear that it is solved now

**Comment by ryanvickr** [comment]
Hey, I seem to be running into this issue again. Was this ever resolved?

**Comment by memsharded** [comment]
Hi @ryanvickr 

Apparently it was never an issue and it was something specific to the user side. You might want to create a new ticket with your specific details. Thanks!

**Comment by ryanvickr** [comment]
Sounds good - I think the issue is that there's only a Linux Conan config for `wasmer`!
