### ISSUE TITLE
[bug] Permission denied for user: 'None'

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan#10902]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 11 21H2 + Windows subsystem for Android + Termux
  * Compiler+version: clang 13.0.0
  * Conan version: 1.46.0
  * Python version: 3.10.1

### Steps to reproduce (Include if Applicable)

```
conan install fmt/8.0.1@_/_
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
DEBUG :conan_api.py   [176]: INIT: Using config '/data/data/com.termux/files/home/.conan/conan.conf' [2022-03-28 19:38:12,389]
DEBUG :tracer.py      [156]: CONAN_API: install_reference(settings=None,options=None,env=None,conf=None,profile_names=None,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None, conf=None),remote_name=None,verify=None,manifests=None,manifests_interactive=None,build=None,update=False,generators=None,install_folder=None,lockfile=None,lockfile_out=None,lockfile_node_id=None,is_build_require=False,require_overrides=None) [2022-03-28 19:38:12,391]
DEBUG :profile_loader.py[120]: PROFILE LOAD: /data/data/com.termux/files/home/.conan/profiles/default [2022-03-28 19:38:12,394]
DEBUG :profile_loader.py[120]: PROFILE LOAD: /data/data/com.termux/files/home/.conan/profiles/default [2022-03-28 19:38:12,453]
Configuration:
[settings]
arch=armv8
arch_build=armv8
build_type=Debug
compiler=clang
compiler.libcxx=c++_shared
compiler.version=13
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

fmt/8.0.1: Not found in local cache, looking in remotes...
fmt/8.0.1: Trying with 'conancenter'...
DEBUG :rest_client_common.py[160]: REST: ping: https://center.conan.io/v1/ping [2022-03-28 19:38:12,469]
DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.ForbiddenException'> [2022-03-28 19:38:12,752]
ERROR: Permission denied for user: 'None'. [Remote: conancenter]

```

content in CONAN_TRACE_FILE:

```
{"_action": "COMMAND", "name": "install_reference", "parameters": {"build": null, "conf": null, "env": null, "generators": null, "install_folder": null, "is_build_require": false, "lockfile": null, "lockfile_node_id": null, "lockfile_out": null, "manifests": null, "manifests_interactive": null, "options": null, "profile_build": [null, null, null, null, null], "profile_names": null, "remote_name": null, "require_overrides": null, "settings": null, "update": false, "verify": null}, "time": 1648467492.3912942}
{"_action": "REST_API_CALL", "duration": 0.2817251682281494, "headers": {"User-Agent": "Conan/1.44.0 (Linux 5.10.43-2-windows-subsystem-for-android-wsa+; Python 3.10.1; x86_64)", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1648467492.7517993, "url": "https://center.conan.io/v1/ping"}
{"_action": "EXCEPTION", "class": "ForbiddenException", "message": "Permission denied for user: 'None'. [Remote: conancenter]", "time": 1648467492.7623036}
```

**Comment by memsharded** [comment]
It seems that you previously tried some kind of auth for ConanCenter? Please try removing your auths with ``conan user --clean`` and retry

**Comment by xyz1001** [comment]
I tried but not work.
![image](https://user-images.githubusercontent.com/14332136/160394500-c9e25ac3-d000-413d-bcb4-4cd1e2728876.png)

**Comment by memsharded** [comment]
Do you have any kind of network configuration like proxies, VPN, firewalls, zscaler...?
If you do, can you please try in a different network?

Things that could help to know what is happening:

- Testing in another machine in the same network. Specifically, I would start trying with a native Conan installation in the system (Linux, Win, OSX), to rule out some ``Android + Termux`` interaction
- Testing in the same machine in other networks
- Are you in some country that could have some network access limitations?
- Checking if that happens with other packages too
- Checking if you can access conan.io/center on the browser
- Do the ``conan search zlib* -r=conancenter`` works?

**Comment by xyz1001** [comment]
1. I have another Mac Mini. It works. There are no network configurations. 
2. I tried other network and not work.
3. conan is ok under WSL2 and Win11 on the same PC.
4. Test on my Android phone (One plus 5) with Termux is ok.
5. It hanppens with any package.
6. It is ok to access conan.io/center on the browser.
7. `conan search zlib* -r=conancenter` also do not work. It has same error.

**Comment by memsharded** [comment]
I don't know what can be happening in that subsystem to be honest. I cannot see who would be returning a ForbiddenException in the flow.

I would try a manual removal of your local cache (the ``<userhome>/.conan`` folder), and then retrying, just in case the ``conan user --clean`` is not working as expected.

Then, I would try running my own ArtifactoryCE instance (you can get it from the downloads page), locally, and see if it works, or fail with same error (still trying to figure out if it is a client issue, or there might be other factor to rule out)

**Comment by xyz1001** [comment]
It do not work to removal of my local cache.

There is a private conan server in my company, and it works well.

**Comment by memsharded** [comment]
> There is a private conan server in my company, and it works well.

So from that computer, with that Conan installation, you can access your private Conan server without any issue (which server is it?), but it will not work with ConanCenter?

Regarding my previous question: Are you in some country that could have some network access limitations? 

I am lacking ideas how to debug this issue, it seems something very specific of your local setup

**Comment by xyz1001** [comment]
conan is ok under WSL2 and Win11 on the same PC with same network. So it might not be network access limitations.

**Comment by memsharded** [comment]
This is challenging to debug from our side at the moment, we don't have any Win11, nor Android WSL, and it really seems something very specific to that setup. This will need to wait until someone with that setup can put some time and investigate further.

**Comment by xyz1001** [comment]
It could be caused by UA. This command will produce this problem.
```
curl -k -i --raw -o 0.dat  -H "Host: center.conan.io" -H "User-Agent: Conan/1.44.0 (Linux 5.10.43-2-windows-subsystem-for-android-wsa+; Python 3.10.4; x86_64)" -H "Accept-Encoding: gzip, deflate" -H "Accept: */*" -H "Connection: keep-alive" -H "X-Client-Anonymous-Id: e4bd9be7890f3e526e2ce857f3c9202df67dfa6f" -H "X-Client-Id: " "https://center.conan.io/v1/ping"
```
The response is
```
HTTP/2 403
server: nginx/1.21.4
date: Wed, 30 Mar 2022 02:13:55 GMT
content-type: text/html
content-length: 153
via: 1.1 google
cache-status: miss
cache-id: HKG-4ee15f8e
alt-svc: clear

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.21.4</center>
</body>
</html>
```

If I change the UA to `Conan/1.44.0 (Linux 5.10.43-2; Python 3.10.4; x86_64)`, it is ok.
```
HTTP/2 200
server: nginx/1.21.4
date: Wed, 30 Mar 2022 02:14:21 GMT
content-length: 0
x-conan-server-version: 0.20.0
x-conan-server-capabilities: complex_search,checksum_deploy,revisions,matrix_params
cache-control: private
via: 1.1 google
cache-status: miss
cache-id: HKG-4ee15f8e
alt-svc: clear
```

**Comment by memsharded** [comment]
Great finding @xyz1001 

This definitely seems the culprit, that android subsystem replacing the UA to ``5.10.43-2-windows-subsystem-for-android-wsa+``

The thing here is that such layer of ConanCenter is not managed by us, it is basically Google infra, and I have no idea if that can be relaxed, but I suspect it cannot. I don't know if reporting to Microsoft (it seems that Android subystem is managed directly by them) could make sense for this.

In any case, it seems this is not a Conan client bug, and we cannot do anything here on the client side to fix it. Maybe transfer it to conan-center-index repo, if that could be checked there.

**Comment by xyz1001** [comment]
You are right. I will transfer this to conan-center-index repo. Thanks for your advice.

**Comment by dfox-coventor** [comment]
@xyz1001 --  I see this discussion is closed, but i'm having a similar problem intermittently with conan 1.60.2 on both linux and windows on an in-network artifactory instance.  What does "UA" Stand for?

**Comment by memsharded** [comment]
Hi @dfox-coventor 

"UA" is User-Agent header  for http requests (we use ``"Conan/%s (%s)" % (client_version, platform_info)`` as User Agent)

Maybe if you keep seeing it, it would be good to create a new ticket with the new details, this has been closed for one year and a half, it could be something different. Thanks!
