### ISSUE TITLE
[bug] Pylint plugin does not accept python_requires from conans

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#10907]
The [pylint_plugin](https://github.com/conan-io/conan/blob/develop/conans/pylint_plugin.py) tries to enforce the use of `conan` instead of `conans`, which will become our future main module. However, some modules are still available only from `conans`, the `python_requies` is one example. In case we use warning as error, it will fail. For instance:

```python
from conan import ConanFile
from conans import python_requires 

base = python_requires("name/version")

class TestConan(ConanFile):
    name = "consumer"
    version = "version"
```

```
export CONAN_PYLINT_WERR=1
conan create . consumer/version@user/channel
...
[HOOK - hooks/recipe_linter.py] pre_export(): consumer.py:2:0: E9000: Using deprecated imports from 'conans'.
```

We need to improve the pylint plugin, or, advance with the module porting.

As workaround, it can be ignore by adding `# pylint: disable=E9000` at line 2.

**Comment by memsharded** [comment]
``from conans import python_requires`` has been deprecated a long time ago, superseded by attribute definition of ``python_requires = ....`` as class attribute.

Those python_requires should not be used anymore, I am perfectly fine if the pylint does not accept them.
