### ISSUE TITLE
[feature] Make build_info time format compatible with JFrog CLI

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#10910]
I'm having trouble using JFrog CLI commands which use build_info (such as [build-append](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-AggregatingPublishedBuilds)) because Conan uses a [time format](https://github.com/conan-io/conan/blob/develop/conans/build_info/build_info.py#L244) different from the [format expected by JFrog](https://github.com/jfrog/build-info-go/blob/56b486ab4b8acca44c1a874a8a771b0cd9c2dac8/entities/buildinfo.go#L17).

Error message from:
```
> jf rt build-append aggregating-build 10 published-build 1
20:19:07 [🔵Info] Running Build Append command...
20:19:09 [🚨Error] parsing time "2022-03-24T17:34:56.000Z" as "2006-01-02T15:04:05.000-0700": cannot parse "Z" as "-0700"
```

**Comment by memsharded** [comment]
This is weird, this used to work. But it is true that Conan build info hasn't been updated in a while, and it is possible that build-info spec might have changed.

This will probably need to wait after 2.0 is out, in the meantime, I'd suggest a script or something that changes those times

**Comment by memsharded** [comment]
Conan 2 got a completely new ``conan art:xxx`` extensions commands in https://github.com/conan-io/conan-extensions, including commands to generate an updated build-info.

Closing this as solved, please open new tickets in that repository if necessary, thanks for the feedback.
