### ISSUE TITLE
[bug] conan install --update should fall back to local-cache if unreachable remote

### ISSUE THREAD

**Issue by anderson-dev** [conan-io/conan#10918]
We use `conan-center` for official packages but our private packages are exclusive to our artifactory server accessible only via VPN. Our developers are often in a disconnected state working mostly from local-cache and `conan-center` for official packages. I thought I'd make use of the `--update` option to ensure they get our latest private packages, however, unless they are currently connected to VPN, it fails entirely. I would expect it to simply fall back to using valid packages already in local-cache and only fail if there are no valid packages meeting requires criteria to be found.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: msbuild 16.11.2.50704
  * Conan version: 1.45.0
  * Python version: 3.10.0

### Steps to reproduce (Include if Applicable)
1. `conan remote add` a working artifactory server remote connection
1. export a private package `upstream/0.1.0` locally
1. make some change to it and bump the version to `upstream/0.2.0`
1. export and publish to artifactory server
1. `conan remove upstream/0.2.0` to simulate a user who has not received the latest version yet from remote
1. make artifactory server no longer able to be reached (i.e. change url or bring it down)
1. `conan new hello/0.1.0`
1. insert requirement for "upstream/[~0]"
1. `conan install . --update` (should fall back to using existing `upstream/0.1.0` in local-cache but connection error stops it in its tracks)
1. use `conan remote remove` to remove your artifactory server remote
1. `conan install . --update` (falls back to using `upstream/0.1.0` in local-cache as it should)

### Logs (Executed commands with output) (Include/Attach if Applicable)

with VPN connected
```
❯ conan install . xenotran/stable --update
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
[conf]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
[conf]

bzip2/1.0.8: WARN: Can't update, no package in remote
catch2/2.13.8: WARN: Can't update, no package in remoteVersion ranges solved
    %s versions not found in remotes
    Version range '<2, include_prerelease=False' required by 'conanfile.py (grate/None@xenotran/stable)' resolved to 'message-queue-manager/1.8.26@xenotran/stable' in local cache
    catch2/* versions found in 'conancenter' remote    
    Version range '~2' required by 'conanfile.py (grate/None@xenotran/stable)' resolved to 'catch2/2.13.8' in 
remote 'conancenter'

conanfile.py (grate/None@xenotran/stable): Installing package
Requirements
    boost/1.77.0 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    message-queue-manager/1.8.26@xenotran/stable from local cache - No remote
    zlib/1.2.11 from 'conancenter' - Cache
Packages
    boost/1.77.0:847654ce15b50bdbb96596fa75b793c981bdc204 - Cache
    bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
    message-queue-manager/1.8.26@xenotran/stable:031f3e634eb2c9302789dfaa70370c3f4ed5009c - Cache
    zlib/1.2.11:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
Build requirements
    catch2/2.13.8 from 'conancenter' - Cache
Build requirements packages
    catch2/2.13.8:ccb9844807d54b8a8b61fa615c7e8b50a6f0638f - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: C:\Users\aflorence\.conan\data\bzip2\1.0.8\_\_\package\d16a91eadaaf5829b928b12d2f836ff7680d3df5\bin
catch2/2.13.8: Already installed!
zlib/1.2.11: Already installed!
boost/1.77.0: Already installed!
boost/1.77.0: Disabled magic autolinking (smart and magic decisions)
message-queue-manager/1.8.26@xenotran/stable: Already installed!
conanfile.py (grate/None@xenotran/stable): Applying build-requirement: catch2/2.13.8
conanfile.py (grate/None@xenotran/stable): Generator 'MSBuildDeps' calling 'generate()'
*** The 'msbuild' generator is EXPERIMENTAL ***        
conanfile.py (grate/None@xenotran/stable): Generator 'MSBuildToolchain' calling 'generate()'
conanfile.py (grate/None@xenotran/stable): MSBuildToolchain created conantoolchain_release_x64.props
conanfile.py (grate/None@xenotran/stable): MSBuildToolchain writing conantoolchain.props
conanfile.py (grate/None@xenotran/stable): Generator txt created conanbuildinfo.txt
conanfile.py (grate/None@xenotran/stable): Aggregating 
env generators
conanfile.py (grate/None@xenotran/stable): Generated conaninfo.txt
conanfile.py (grate/None@xenotran/stable): Generated graphinfo
```
with VPN disconnected
```
❯ conan install . xenotran/stable --update
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
[conf]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
[conf]

ERROR: HTTPSConnectionPool(host='artifactory.xenonet.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/ping (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:852)'),))

Unable to connect to conan-local=https://artifactory.xenonet.com/artifactory/api/conan/conan-local
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
 ~  source  repos  xeno  edot  grate  master  
 3.10.0  ERROR 
```

**Comment by memsharded** [comment]
Hi @anderson-dev 

This is by design, and we are not considering to change it. If you have some remote defined, it is expected to be active. Conan will never fallback or skip a given remote that is not responding, or not reachable. In that case, it should be explicitly disabled ``conan remote disable``. This is for all "install" operations (for example the ``search`` might not error). But all the ``install``, ``create``, etc, that will download from the remote something if the remote was available will error. The reason for this is that this behavior can easily hide network failures, configuration errors, and other problems, silently producing unexpected results.

**Comment by anderson-dev** [comment]
Gotcha. That makes sense for an unexpected down server on the open network but we are purposely disconnected from vpn while working. I've worked around it by specifying an explicit argument to my make script for the devs to say they are connected to vpn and wish to pull latest packages `make build PACKAGE_UPDATE=1`. Not pretty but it works

Hopefully I have the time to make things a little more smart and test if vpn is currently connected and enable/disable --update argument to conan when it would potentially work or not.
