### ISSUE TITLE
[feature] Use [imports] with includes instead of excludes

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#10914]
Hi there,

I wonder if it is possible to use the [imports] in the `conanfile.txt` with includes instead of excludes.
I have a use case like this:

```txt
...
[imports]
., * -> . @ folder=True, ignore_case=True, keep_path=True, excludes=bin lib ... ... ...
```

but this will be the much better solution:
```txt
...
[imports]
., * -> . @ folder=True, ignore_case=True, keep_path=True, includes=include src
```

And actually I can imagine that there are many use cases out there like mine.

I did this as feature request because I can not find something in the documentation about this: https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports

**Comment by memsharded** [comment]
Hi @snailcatcher 

but isnt it the first argument in the line?

```
[imports]
include, * -> . @ folder=True, ignore_case=True, keep_path=True
src, * -> . @ folder=True, ignore_case=True, keep_path=True
```

In any case, ``imports`` are being removed in 2.0, we will not add new features to it. It will be replaced by explicit ``copy()`` in the ``generate()`` method.

**Comment by snailcatcher** [comment]
Hi @memsharded 

not exactly, because it need the `include` and `src` folder inside a folder named like the package. If you do it like you described this will not be the case it just copies the files from inside these folders.

Can you give an example or the documentation page where I can find the `copy/generate` stuff? I did not find something via the search function.

If you want to drop the `imports` in conan 2.0, it would be nice if there is a hint in the documentation. I think your last paragraph with a link will be enough. I you can tell me where to find it in the docs I will be happy to contribute this hint.

Thanks

**Comment by lasote** [comment]
Hi, now there is available this guide to migrate to 2.0, https://docs.conan.io/en/latest/conan_v2.html#methods-that-disappear-in-2-0-self-imports
The section is going to be improved soon when we release the new 1.47.

**Comment by snailcatcher** [comment]
Hi @lasote 
So this means that there is no way in conan 2.0 to copy files with a `conanfile.txt` instead of a `conanfile.py`?

**Comment by lasote** [comment]
Nope. it has to be conanfile.py. Check here also how easy is to migrate to it: https://docs.conan.io/en/2.0-alpha/tutorial/consuming_packages/getting_started/the_flexibility_of_conanfile_py.html

**Comment by snailcatcher** [comment]
Hey @lasote & @memsharded 
I change my `conanfile` and use the generate method. This is working pretty good.
Even though it is a bit more complicated to use the python version of the `conanfile` it actually like the flexibility.
Thanks for the explanation.
