### ISSUE TITLE
[question] Conditional shared lib build using MSBuildToolchain

### ISSUE THREAD

**Issue by anderson-dev** [conan-io/conan#10912]
Is there a recommended way to conditionally build an msbuild project as either a static lib or shared dll using `shared=True`?

According to my research, the recommendation is to create DebugShared and ReleaseShared configs respectively that define the output type as DLL and that define a macro that will be checked at build time to determine whether to declare export/import decls. In my `conanfile.py`, if the `shared=True` option is specified, I'm appending "Shared" to the MSBuild helper configuration.

```
msbuild = MSBuild(self)
if self.options.shared:
    msbuild.build_type = f"{self.settings.build_type}Shared"
msbuild.build("ProxyClientWrapper.sln")
```

```
#if defined (BUILD_SHARED_LIBS)
#if defined(MQM_DLLEXPORT)
#define  MQM_DECLSPEC __declspec(dllexport)
#else
#define  MQM_DECLSPEC __declspec(dllimport)
#endif /* MQM_DLLEXPORT */
#else  /* !defined (BUILD_SHARED_LIBS) */
#define MQM_DECLSPEC
#endif
```

This all should work but `conantoolchain.props` only checks for Debug/Release so the DebugShared/ReleaseShared builds never pull in conan dependencies preventing build. Is there another recommendation on how to handle this use case with conan option shared=True?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @anderson-dev 

The ``MSBuildToolchain`` also contains a ``MSBuildToolchain.configuration`` attribute that should be used in the ``generate()`` method to customize the project configurations, following the same logic. Apparently, it is not clearly documented, just something vaguely generic:

> A conantoolchain_<config>.props file, that will be conditionally included from the previous conantoolchain.props file based on the configuration and platform, e.g.: conantoolchain_release_x86.props

But not that it can be set using ``configuration`` attribute. Please try it, and if it works, we will document it.

**Comment by anderson-dev** [comment]
Thanks again @memsharded I'm really moving now!

That worked! I had to specify the configuration attribute for both `MSBuildToolchain` and `MSBuildDeps` in the `generate()` method as suggested and append "Shared" to my `self.cpp.build.bindirs[0]` in the `layout()` method.

It turns out this typical use case was [documented](https://docs.conan.io/en/1.44/reference/conanfile/tools/microsoft.html#msbuilddeps) for `MSBuildDeps` but not for `MSBuildToolchain`.

**Comment by memsharded** [comment]
> That worked! I had to specify the configuration attribute for both MSBuildToolchain and MSBuildDeps in the generate() method as suggested and append "Shared" to my self.cpp.build.bindirs[0] in the layout() method.

Great! Happy to hear that :)
