### ISSUE TITLE
[question] CMakeDeps vs RelWithDebInfo?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#10915]
`cmake` generator allows the following trick:
```
    cmake = CMake(self)
    if self.settings.build_type=="Release":
        cmake.build_type = 'RelWithDebInfo'
    cmake.configure()
    cmake.build()
```
So I can use Release binaries of dependencies for RelWithDebInfo build of my own code. With `CMakeDeps` generator this no longer works. Generated files use CMake generator expressions that select include directories, libraries, etc. only for CMake build matching Conan build_type:
```
set_property(TARGET some_pkg::some_pkg
             PROPERTY INTERFACE_INCLUDE_DIRECTORIES
             $<$<CONFIG:Release>:${some_pkg_INCLUDE_DIRS_RELEASE}> APPEND)
```
Is there any way around it?

**Comment by memsharded** [comment]
Have you tried using ``-s mypkg:build_type=RelWithDebInfo -s build_type=Release``?

**Comment by db4** [comment]
> Have you tried using `-s mypkg:build_type=RelWithDebInfo -s build_type=Release`?

OK, I'll try to, thanks. Maybe you also have an idea of how to do the same for a CMake consumer project? I need to generate a Visual Studio solution that uses Release dependencies for RelWithDebInfo configuration (and also have Release and Debug configs)

**Comment by memsharded** [comment]
The ``&`` should be the identifier for the consumer, when the the consumer has no name, so maybe ``-s &:build_type=RelWithDebInfo -s build_type=Release`` could work

**Comment by db4** [comment]
Yes, that works. Thank you!

**Comment by memsharded** [comment]
Great! Yes, the idea is that it shouldn't be necessary to hack this kind of things in recipes, but it should be possible to define it in configuration.

**Comment by ktrNozomi** [comment]
> The `&` should be the identifier for the consumer, when the the consumer has no name, so maybe `-s &:build_type=RelWithDebInfo -s build_type=Release` could work

@memsharded Very appreciated for this answer!! Btw, may I ask where does the documentation state about this? I'm using with conan 2.x

**Comment by memsharded** [comment]
It is in https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns

**Comment by ktrNozomi** [comment]
@memsharded Thx bro! You are the real hero!
