### ISSUE TITLE
[feature] Modernize `add_definitions`

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#10929]
Change all the `add_definitions` occurrences in `conan.tools.cmake` by `add_compile_definitions`.

Following [CMake documentation](https://cmake.org/cmake/help/latest/command/add_definitions.html):

```
Note This command has been superseded by alternatives:
* Use add_compile_definitions() to add preprocessor definitions.
* Use include_directories() to add include directories.
* Use add_compile_options() to add other options.
```

**Comment by SeanSnyders** [comment]
Definitely needing on this change, as old CMake `add_definitions` used in the CMakeToolchain cannot handle strings properly for the value of the definition.

**Comment by SeanSnyders** [comment]
Further investigation seems that there is some support lacking from Conan still to be able to handle complex string situations:
https://github.com/conan-io/conan/issues/11043
