### ISSUE TITLE
[question] Custom generator - how to access conandata.yml?

### ISSUE THREAD

**Issue by sboehmann** [conan-io/conan#10926]
I am currently writing my own Conan generator similar to the Markdown generator, except that I need to create a Docbook file. 
I can get most of the needed information, but I also need to access the license, homepage, and some information only defined in our conandata.yml. 

Is there any way to access the conandata.yml?

Many thanks for your help.

**Comment by memsharded** [comment]
Hi @sboehmann 

In the current recipe, the conandata.yml is accessed via ``self.conan_data``. But maybe you refer to access the ``conandata`` of the dependencies? It is right now not exposed in the interface. You can access the private member via ``self.dependencies["mydep"]._conanfile.conan_data`` (or iterate all deps) to try it. Please tell me if that is what you want, we might add it to the public interface.

**Comment by sboehmann** [comment]
Hi @memsharded 

indeed, I want to access the `conandata` of a dependency. Sadly, your hint doesn't work. My generator currently has this loop:
```
def content(self):
     for pkg_name, cpp_info in self.deps_build_info.dependencies:
        name = pkg_name
        desc = cpp_info.description
        homepage = ...?
        conandata = ...?
```

**Comment by memsharded** [comment]
But ``self.deps_build_info`` is obsolete now, that only exists in the legacy Generator class.

Try to iterate directly ``self.dependencies`` in your ``generate()`` method instead. That should work.

To modernize custom generators the path is:

- Put them as an independent class in a ``python_require``
- No inheritance. The convention is to have a ``generate()`` method, but that is not mandatory for user generators
- Do a ``python_requires=`` in your consumer
- Instance the class explicitly in the ``generate()`` method.

It is a bit less magic, and a bit more explicit, but this way it avoids a couple of very buggy behaviors.

**Comment by sboehmann** [comment]
Ok, thanks!

However, how should one know that? [Custom generator](https://docs.conan.io/en/latest/reference/generators/custom.html#custom-generator) and [How to create and share a custom generator with generator packages](https://docs.conan.io/en/latest/howtos/custom_generators.html#dyn-generators) still explain it the way I did it. ;) Did I miss something? Is this for Conan 2.0? When did it become obsolete?

**Comment by memsharded** [comment]
Yes, those are Conan 1.X docs, which we are not removing, but many of the things in 1.X have already been replaced by 2.0 ready (available in 1.X) alternatives, explained somewhere else.

> However, how should one know that? 

Conan 2.0 alpha is already there, docs are available in https://docs.conan.io/en/2.0-alpha/index.html

Then, the migration guide in Conan 1.X should also help giving some guidelines of what is being removed and what needs to be upgraded: https://docs.conan.io/en/latest/conan_v2.html

It is likely that it is still missing some things, it seems this Generators thing is not explicited there, we should added it.

**Comment by memsharded** [comment]
Hi @sboehmann 

Conan 2 already exposed the dependencies ``.conan_data`` interface some time ago: https://docs.conan.io/2/reference/conanfile/methods/generate.html#dependencies-interface

I am closing this ticket as solved in Conan 2, please don't hesitate to create new tickets for any further question. Thanks!
