### ISSUE TITLE
[question] conan install without defining all the related parameters for the package id

### ISSUE THREAD

**Issue by stefaneicher** [conan-io/conan#10922]
Hi,

can you give me a tip on how I can run conan install simply to get a precompiled artifact without defining all the related parameters for the package id?

Background: We produce executable firmware in many variations (multiple compilers, debug, release, different options) but only one must be propagated to the testing department.

I would like to send them a "oneliner" about how they can get the newest artifact from artifactory but they must and should not know anything about profiles and options or settings.

So in best is could send the something like

"conan install -if=. --build=never awsomefirmware/4.1.1@conan/stable --binary-package-id=c6d75a933080ca17eb7f076813e7fb21aaa740f2".

--binary-package-id is just made up for illustration.

I do not want that them recompile anything.

Regards Stefan

**Comment by memsharded** [comment]
Hi @stefaneicher 

I think you are looking for the ``conan download`` command. Have you tried it? It seems basically what you need.
It is different from install in:

- It only retrieves that specific package, not transitive dependencies.
- It will not call generators, deployers, etc, only downloads the artifacts.

but it seems what you want.

**Comment by stefaneicher** [comment]
Hi Diego,

ok perfect thanks for your answer!

Grus Stefan
