### ISSUE TITLE
[question] How to set profiles for test package when using `conan create`

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#10925]
Hi,

I have created a Conan recipe including a test package.

However, when running `conan create` with different profiles than the default profile, then Conan 1.46.0 raises the following error:

```
test-recipe/dev@user/channel (test package): Running test()
...
Installing (downloading, building) binaries...
ERROR: Missing binary: test-recipe/dev@user/channel:f02a74a6a00afffd2c7ee691ced3276d5d33260c
...
test-recipe/dev@user/channel: WARN: Can't find a 'test-recipe/dev@user/channel' package for the specified settings, options and dependencies:
- Settings: ...
- Options: ...
- Dependencies: ...
- Requirements: ...
- Package ID: f02a74a6a00afffd2c7ee691ced3276d5d33260c
...
ERROR: Missing prebuilt package for 'test-recipe/dev@user/channel'
...
```

**Edited:**
By the way: when running `conan test` I get the identical error even if I set `--profile:host` and `--profile:build` explicitly.

Is there any (hidden) way to set the proper profiles for the test package?

Many thanks for your help.

Best regards,
Markus

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The test_package gets the full profiles in the same way the main conanfile does.

There might be something else there. You can try with the ``conan new hello/0.1 -m=cmake_lib`` template, that already contains a ``test_package`` and it should build with different profiles without problems. Or you are passing ``--build=xxx`` to the ``conan create`` and not adding ``--build=missing`` or ``--build=pkg``?

**Comment by gpxricky** [comment]
@memsharded 

You are right, the error was coming from my implementation in the `test()` method which was trying to install the referenced module via

```
# Deploy the package and verify the installation
install = Path("").resolve().joinpath("install")
reference = self.requires["test-recipe"].ref
self.run(f"conan install {reference} --install-folder {install}")
```

and obviously uses the default profile there (somehow related to #9193).

**Comment by jruehle** [comment]
@gpxricky How did you end-up solving this? Meaning, how did you pass the profile from `conan create` to your test package's `conan install ` command? I am having the same trouble of creating a test_package integration to test the deploy step of my main package.

Thanks for your help.

**Comment by memsharded** [comment]
Hi @jruehle. The ``test_package`` functionality don't fire the ``deploy()`` function. That is only fired for a ``conan install mypkg/version@`` direct installation, iirc.
