### ISSUE TITLE
[bug] CMakeToolchain boolean variables are cached as strings

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#10936]
### Environment Details
  * Operating System+version: macos
  * Compiler+version: clang 
  * Conan version: 1.46.2
  * Python version: 3.7

### Steps to reproduce

using this generate method
```
    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["FOO"] = True
        tc.variables["BAR"] = False
        tc.generate()
```

I got these results the `conan_toolchain.cmake` 

```
set(FOO ON CACHE STRING "Variable FOO conan-toolchain defined")
set(BAR OFF CACHE STRING "Variable BAR conan-toolchain defined")
```

However I expect these to be Boolean, something like
```
set(FOO ON CACHE BOOL "Variable FOO conan-toolchain defined")
set(BAR OFF CACHE BOOL "Variable BAR conan-toolchain defined")
```

**Comment by lasote** [comment]
Thanks for reporting, I open a PR to solve it.
