### ISSUE TITLE
Handling Linux distribution-specific binaries

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#1093]
I am currently working on a spike solution for our company infrastructure  using Conan. What i did not get so far is how distribution-specifics are handled. E.g. Qt5 has dependencies to libs like gstreamer and there are even modules like QWebengine that depend on Kernel features (v4l) not available in older Distributions like RHEL 6 so i doubt the binaries built on e.g. Ubuntu would work as expected.
Is this something that needs to be handled with a package-specific setting reflecting the distribution or is there a better way for avoiding wrong/incompatible binaries being shared between developers?
Thanks a lot for the great work and for answering this in advance.

**Comment by memsharded** [comment]
Yes, you are very right. The default settings for conan.io is a tradeoff between being overly detailed and the opposite. We didn't include details for differentiating distros, as for the majority of cases, especially in OSS, it is not necessary.

In the enterprise environment, it is different, and specifically the differentiation and binary incompatibility problems between RH6 and 7 (or between different versions of glibc, if you prefer) are an issue, and it is totally necessary to support both. Fortunately it is easy to customize, and there are a few users that are doing something like:

- If using mainly linux platforms, you can add a setting in your default ``settings.yml``, at the root level, something like:
```yaml
os: [Windows, Linux, Macos, Android, iOS, FreeBSD, SunOS]
distro: [RH6, RH7]
```
You can add more distros, or even have ``None`` as a distro value.
- If you have a more complex hierachy of OS and want to model them more accurately, you could do:
```yaml
os:
      Windows:
      Linux:
           distro: [RH6, RH7]
      Macos:
           codename: [Mavericks, Yosemite]
```
The only thing you have to manage is that your team shares the same settings.yml. Does this answer your question? Cheers!

**Comment by petermbauer** [comment]
Yes, thanks a lot, reassuring to know that this is the way to go.

**Comment by yangcha** [comment]
> Yes, you are very right. The default settings for conan.io is a tradeoff between being overly detailed and the opposite. We didn't include details for differentiating distros, as for the majority of cases, especially in OSS, it is not necessary.
> 
> In the enterprise environment, it is different, and specifically the differentiation and binary incompatibility problems between RH6 and 7 (or between different versions of glibc, if you prefer) are an issue, and it is totally necessary to support both. Fortunately it is easy to customize, and there are a few users that are doing something like:
> 
> * If using mainly linux platforms, you can add a setting in your default `settings.yml`, at the root level, something like:
> 
> ```yaml
> os: [Windows, Linux, Macos, Android, iOS, FreeBSD, SunOS]
> distro: [RH6, RH7]
> ```
> 
> You can add more distros, or even have `None` as a distro value.
> 
> * If you have a more complex hierachy of OS and want to model them more accurately, you could do:
> 
> ```yaml
> os:
>       Windows:
>       Linux:
>            distro: [RH6, RH7]
>       Macos:
>            codename: [Mavericks, Yosemite]
> ```
> 
> The only thing you have to manage is that your team shares the same settings.yml. Does this answer your question? Cheers!
Is this profile a valid one based on your second settings.yml?
```
[settings]
    os=Linux
    os.distro = RH6
    os_build=Linux
    arch=x86_64
    arch_build=x86_64
    compiler=gcc
    compiler.version=7
    compiler.libcxx=libstdc++
    build_type=Release
[options]
[build_requires]
[env]
```
Or should I add a line?
```
os_build.distro = RH6
```

**Comment by Bassem-Ramzy** [comment]
@memsharded 
Is this still the same practice in both version 2.0 & 1.58?

**Comment by memsharded** [comment]
Hi @Bassem-Ramzy 

Yes, adding your own custom settings is the way to go both in 2.0 and 1.58.

Conan 2.0 contains some good improvements that can help manage this:
- New ``settings_user.yml`` file that can contain only the additions to ``settings.yml``, easier to maintain, and can also be distributed with ``conan config install``
- New ``compatibility.py`` plugin that can define binary compatibility mode, and that you can customize to define your own rules for your own ``distro`` or other custom settings that you want to use.

**Comment by danielpomfjuk** [comment]
@memsharded Hi,

I've been trying to utilize this feature and feel like either there is a bug or I'm doing something wrong.

Context:
We are building our software on both Ubuntu and AlmaLinux. They have different versions of libc and libstd, which means we cannot use the same cache for them. We have one remote repo set up, and our Alma build in CI keeps pulling in the Ubuntu cache and failing to build.

To mitigate this, I have added an extra setting through settings_user.yml:

```yml
distro: [AlmaLinux-8.10, Ubuntu-20.04]
```
And in our recipes, I am adding the setting to be taken into account when generating the package ID:

```bash
settings = "os", "arch", "compiler", "build_type", "distro"
```

this is the output of a build with distro set to "Ubuntu-20.04"
```bash
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=10
distro=Ubuntu-20.04
os=Linux
[buildenv]
CC=clang
CXX=clang++


soltrack/2.2: Package '5b077c31c249420302c245fad24dd1e6a90d5ccc' built
soltrack/2.2: Build folder /home/.conan2/p/b/soltr27b40ca78e3f3/b/build/Release
soltrack/2.2: Generating the package
soltrack/2.2: Packaging in folder /home/.conan2/p/b/soltr27b40ca78e3f3/p
soltrack/2.2: Calling package()
soltrack/2.2: package(): Packaged 1 '.h' file: SolTrack.h
soltrack/2.2: package(): Packaged 1 '.a' file: libSolTrack.a
soltrack/2.2: Created package revision dfdb120d17d1e80b2674d5ae3c0fa6df
soltrack/2.2: Package '5b077c31c249420302c245fad24dd1e6a90d5ccc' created
soltrack/2.2: Full package reference: soltrack/2.2#3ae3e7be2e72a577e4e59ef8555bff86:5b077c31c249420302c245fad24dd1e6a90d5ccc#dfdb120d17d1e80b2674d5ae3c0fa6df
soltrack/2.2: Package folder /home/.conan2/p/b/soltr27b40ca78e3f3/p
```

this is the output of a build with distro set to "AlmaLinux-8.10"
```bash
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=10
distro=AlmaLinux-8.10
os=Linux
[buildenv]
CC=clang
CXX=clang++

...

soltrack/2.2: Package '13a0489fc766fc7aa81d8b9d082daec41de84bf7' built
soltrack/2.2: Build folder /home/.conan2/p/b/soltr890c33f43a1b6/b/build/Release
soltrack/2.2: Generating the package
soltrack/2.2: Packaging in folder /home/.conan2/p/b/soltr890c33f43a1b6/p
soltrack/2.2: Calling package()
soltrack/2.2: package(): Packaged 1 '.h' file: SolTrack.h
soltrack/2.2: package(): Packaged 1 '.a' file: libSolTrack.a
soltrack/2.2: Created package revision 38d9ed4fcb169fb1c36b7d1f501b3cb6
soltrack/2.2: Package '13a0489fc766fc7aa81d8b9d082daec41de84bf7' created
soltrack/2.2: Full package reference: soltrack/2.2#3ae3e7be2e72a577e4e59ef8555bff86:13a0489fc766fc7aa81d8b9d082daec41de84bf7#38d9ed4fcb169fb1c36b7d1f501b3cb6
soltrack/2.2: Package folder /home/.conan2/p/b/soltr890c33f43a1b6/p
```

As you can see, the ID in both is soltrack/2.2#3ae3e7be2e72a577e4e59ef8555bff86. If I remove distro from the list of settings in the recipe, it generates a different ID, but it’s still the same for both builds. This indicates that the setting is being taken into account, although changing it does nothing.

Could you please advise if I missed anything?

**Comment by memsharded** [comment]
Hi @danielpomfjuk 

This is a closed ticket, and it might not be related, it is generally better to open a new ticket for these issues.

Then, for the ``distro`` case, it is generally more convenient to model it as a ``sub-setting``, not as a ``setting``, see https://docs.conan.io/2/reference/config_files/settings.html#adding-new-sub-settings:

- No need to modify recipes
- With a ``null`` accepted value it is backward compatible, not breaking existing packages with existing ``package_id``. Generally you would want to do ``distro: [null, AlmaLinux-8.10, Ubuntu-20.04]``
- Better checking and consistency (not possible to define ``os=Windows, distro=xxxx``



Then, the ``soltrack/2.2#3ae3e7be2e72a577e4e59ef8555bff86`` is not the ``package_id``. That is the ``recipe-revision``, it changes when you modify the recipe. Check https://docs.conan.io/2/tutorial/versioning/revisions.html


The right way to see the different binaries, is after the second build for the other distro, do:

```
$ conan list "soltrack/2.2:*"
```
and you will see the different ``package_id`` created for the different distros. To learn more about the ``package_id`` model, you can read https://docs.conan.io/2/reference/binary_model.html, but make sure to distinguish between the ``recipe-revision`` and the ``package_id``. ``conan list "soltrack/*#*:*"`` is the way to list all your local revisions and package-ids for each revision.

**Comment by danielpomfjuk** [comment]
@memsharded Thank you for such a swift response! I checked, and the package IDs are indeed different. Our current thinking is that since the packages built from ConanCenter, or their transient dependencies, do not take distro into account, having a shared remote cache will not work. Sooner or later, they will share a package that won’t work for one of them because it was built on the other. We are going to set up two separate remote repositories, one for each distro.

Thanks again for your assistance 🙏

**Comment by memsharded** [comment]
> @memsharded Thank you for such a swift response! I checked, and the package IDs are indeed different. Our current thinking is that since the packages built from ConanCenter, or their transient dependencies, do not take distro into account, having a shared remote cache will not work. Sooner or later, they will share a package that won’t work for one of them because it was built on the other. We are going to set up two separate remote repositories, one for each distro.

But this is not necessary! You really don't need to have 2 separate repositories, if you are using the ``distro`` subsetting, things will work using just one repository.

The recommendation for this kind of case is, following https://docs.conan.io/2/devops/using_conancenter.html:
- Build your binaries from ``conan-center-index`` Github repo, not use them directly from ConanCenter
- Build them with your ``distro`` subsetting for your maintained distros
- Upload them to the same server repository
- Users will automatically get the right ones for their ``distro`` defined in their profiles.

That will be much better than configuring different repos.
