### ISSUE TITLE
[bug] Rewrite lock file, get the binary is wrong

### ISSUE THREAD

**Issue by DDkuang** [conan-io/conan#10944]
### Environment Details (include every applicable attribute)
  * Operating Ubuntu+20.04:
  * Compiler+version: gcc 10.2
  * Conan version: 1.46.2
  * Python version: 3.8.10

Conanfile.py :
```python
from conans import ConanFile, tools
import os
required_conan_version = ">=1.33.0"
class LibaConan(ConanFile):
    name = "liba"
    settings = "os", "arch", "compiler", "build_type", "platform"
    keep_imports = True

    def configure(self):
        if self.options.shared:
            self.options["libsodium"].shared = True
            self.options["libuv"].shared = True

    def requirements(self):
        self.requires("cpcore/[> 2.4.20 < 2.5.0]@liware/stable")
        self.requires("libuv/1.42.0")

    def deploy(self):
        self.copy("*", src="lib", dst="lib", symlinks=True)
        self.copy("*", src="bin", dst="bin")
        self.copy("*", src="etc", dst="etc")

    def imports(self):
        self.copy("*", src="lib", dst="lib",
                  excludes=self.no_import_to_yocto_lib)
        self.copy("*", src="bin", dst="bin",
                  excludes=self.no_import_to_yocto_bin)
        self.copy("*", src="etc", dst="etc")

    def package(self):
        self.copy("*", src="lib", dst="lib", symlinks=True)
        self.copy("*", src="bin", dst="bin")
        self.copy("*", src="etc", dst="etc")
        self.copy("version*", src="", dst="etc")
```

### Steps to reproduce 
1. `conan lock create conanfile.py --user=liware --channel=stable --lockfile-out=base.lock --base`
2. `conan lock create conanfile.py --user=liware --channel=stable --lockfile=base.lock --lockfile-out=release.lock --profile=x64`
3. `conan create . 1.0.0@liware/stable --lockfile=release.lock`
4. Replace ref liba/1.0.0@liware/stable to liba/llatest@liware/stable from release.lock,save to release_daily.lock
5. Update the third-party dependent version. Increase the version of `cpcore` to 2.4.35.
Attention： 
liba/llatest@liware/stable already exists at the artifactory, but the dependency information is lower than the current release.lock.
release.lock 
The version recorded in the release.lock:
cpcore/2.4.33@liware/stable

6. `conan lock install release_daily.lock -if ./install_dir`
7. `cpcore --version`. 

Expect：
version = 2.4.33

Reality：
version = 2.4.35

My workaround：
`conan create . latest@liware/stable --lockfile=release_daily.lock`
`Conan Upload liba/latest@liware/stable -r conan_remote --all`
`conan remove "*" -f`
`conan lock install release_daily.lock`

Result:
`cpcore --version`
version = 2.4.33 ,The version is right.

``

**Comment by memsharded** [comment]
Hi @DDkuang 

Not sure I fully understand your flow, so first a couple of notes and questions:

> Replace ref liba/1.0.0@liware/stable to liba/llatest@liware/stable from release.lock,save to release_daily.lock

As a general idea, a lockfile in Conan 1.X is a snapshot of a real dependency graph. Replacing something there might not work as expected if that is not a possible real state/graph that can be computed.
Also, the thing is that for declared version ranges, something that fits in that range is necessary. The textual ``latest`` version does not validate as a valid version in the range ``[> 2.4.20 < 2.5.0]``. It doesn't matter if you put it in the lockfile, if its not a "reachable" state, it will not be used.

> Update the third-party dependent version. Increase the version of cpcore to 2.4.35.

This is not clear what you are doing. Can you please clarify? The ``Attention：`` output that you are showing, is that Conan terminal output? I cannot see where Conan would be outputting that.

**Comment by DDkuang** [comment]
This is not output. The latest version of cpcore on artifactory is 2.4.35.  The cpcore in release.lock is 2.4.33. 
release.lock like this:
`
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "liba/1.0.0@liware/stable",
    "requires": [
     "1",
     "25"
    ],
    "path": "conanfile.py",
    "context": "host"
   }
}
`
Replaces the package name of nodes 0 and save to release_daily.lock
`
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "liba/latest@liware/stable",
    "requires": [
     "1",
     "25"
    ],
    "path": "conanfile.py",
    "context": "host"
   }
}
`

run
`conan install liba/latest@liware/stable -l release_daily.lock`

The terminal output cpcore is 2.4.33, actual cpcore is 2.4.35.

**Comment by memsharded** [comment]
Lockfiles have been completely revamped in Conan2, closing this as outdated, please create new tickets as necessary, thanks for the feedback.
