### ISSUE TITLE
[question] How to scope all conan files under some directory

### ISSUE THREAD

**Issue by netheril96** [conan-io/conan#10946]
I tried setting `CONAN_USER_HOME` to `D:\Codes` and setting `storage.path` to `D:\Codes\conan\data`, but conan always write files into `D:\.conan`. I want to scope all its file under the same place so that I can easily remove all of them and start over in a fresh state.

**Comment by memsharded** [comment]
Hi @netheril96 

The conan short-home cache is necessary to host in Windows those packages that have long paths that will not fit in the normal cache. There ae a couple of ways to disable that:

- Remove the ``short_paths=True`` attribute in the Conan recipes
- Define the CONAN_USER_HOME_SHORT=None ("None" as text) (or the ``[general]`` ``user_home_short=None`` in conan.conf, to disable the feature. Note that some packages with long paths that defined ``short_paths=True`` might still fail if they don't fit in the maximum path length.

Finally, Conan 2.0 (now in alpha.6 release), completely remove the short_paths feature, so everything will be in a single folder.

**Comment by netheril96** [comment]
That is a very nice and responsive answer! Hope it can be added to the FAQ though.
