### ISSUE TITLE
[question] conan install -u

### ISSUE THREAD

**Issue by Wizradus** [conan-io/conan#10957]
Hi guys.

I need a little help or explanation for command `conan install -u`.
I didn't find much information about this. Only that: 
_Will check the remote and in case a newer version and/or revision of the dependencies exists there, it will install those in the local cache. When using version ranges, it will install the latest version that satisfies the range. Also, if using revisions, it will update to the latest revision for the resolved version range._
I would like to know more how it work, because I tried to simulate situation that we have newer version of package in artifactory, but I was not successful. Which files are compared to know if local conan cache should be updated from remote or not.

Thanks in advance.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by boussaffawalid** [comment]
I don't know about version ranges, but for fixed version, with `-u` conan will check remote server for a newer package build for the same recipe version. 

For example: let's say you depend on `lib/1.0`, and that `lib/1.0` exist in your local cache.
* Without -u: conan will use the version from your local cache without checking remote server
* With -u: conan will check remote server for latest package (latest build) of `lib/1.0`. 

-u is needed because with conan you would upload a new package build with the same version as in remote.

**Comment by Wizradus** [comment]
Thanks bousafwalid. 
Do you have idea how I can simulate this behavior? What file I can to change locally to enforce update from remote?
Still don't have idea how conan decide that package in remote is newer than in cache.

Thanks

**Comment by boussaffawalid** [comment]
@Wizradus from conan docs https://docs.conan.io/en/latest/reference/commands/consumer/install.html

```
  -u, --update          Will check the remote and in case a newer version
                        and/or revision of the dependencies exists there, it
                        will install those in the local cache. When using
                        version ranges, it will install the latest version
                        that satisfies the range. Also, if using revisions, it
                        will update to the latest revision for the resolved
                        version range.
```

* For fixed version: probbaly conan uses timestamp to decide which version is latest (this is just my guess)
* For version range: it will install the latest version that satisfies the range.

Do you have idea how I can simulate this behavior ? I'm not sure I understand this question.

**Comment by Wizradus** [comment]
Well... @boussaffawalid I read this notice in documentation. I know that conanmanifest.txt is crucial for this process. 
I see any number in connanmanifest.txt on the top, what is probably some timestamp + file names and their hashes.
But what I exactly want to know how to in any way initiate this update manually on my computer.
I tried change this num in conanmanifest.txt but without any luck.

**Comment by lasote** [comment]
Yes. the `conanmanifest.txt` contains a timestamp that is used to see if there are updates. That mechanism has been replaced in Conan 2.0 (alpha) with the revisions mechanism.

**Comment by Wizradus** [comment]
Hola @lasote!
Can I to take somewhere details about current and future changes of this process?

**Comment by lasote** [comment]
Well, there are no specific docs for this but Conan 2 will use only [revisions](https://docs.conan.io/en/latest/versioning/revisions.html). So the update process will be based on the "latest" revision available on a server. The timestamp won't be taken into account anymore. Also, FYI, if the same recipe revision exists in several remotes, the binary packages will be searched in all of them.

**Comment by Wizradus** [comment]
OK. Thanks for the info.
