### ISSUE TITLE
`conan source` command behaves differently when given reference to cache vs path

### ISSUE THREAD

**Issue by CausticYarn** [conan-io/conan#1095]
I am not entirely sure whether this is a bug or expected behavior, but I notice that when I use `conan export` and then use `conan source MyPackage/1.2@user/channel`, it pulls just the exported files and then feteches the source, which makes sense since it is pulling files from the local cache which only contains the exported files. 

However, when I use a path, e.g. `conan source .\my_package` it pulls all files and folders in the path I point to, and then fetches the source.  This was actually very confusing to me when I tried to use conan source in a subdirectory of the path containing the conanfile.py and it creates an additional subdirectory of the same name as the subdirectory I am in. 

I am not sure if there is a production use case for this behavior; I am mostly using `conan source` to test my recipe so this is not a priority issue.

**Comment by memsharded** [comment]
Yes, you were right, it is a bit weird that the local ``conan source`` is copying all files, not only the export. Submitted a PR, was not intended for next release, but as this might be considered a bug, it might get into it. Thanks very much for reporting!

**Comment by memsharded** [comment]
Hi @CausticYarn, this has been released in conan 0.21, please try it. thanks!
