### ISSUE TITLE
[bug] markdown - needs to install system packages and run pkg-config

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10969]
might be also related to https://github.com/conan-io/conan/issues/10967
it's pretty annoying that markdown generator requires user to install system packages, in case if package depends on something like `opengl/system` or `xorg/system`. it would be nice to skip that.
```
ERROR: egl/system: Error in package_info() method, line 75
	self._fill_cppinfo_from_pkgconfig('egl')
while calling '_fill_cppinfo_from_pkgconfig', line 24
	if not pkg_config.provides:
	ConanException: pkg-config command ['pkg-config', '--print-provides', 'egl', '--print-errors'] failed with error: Command 'pkg-config --print-provides egl --print-errors' returned non-zero exit status 1.
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
```

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by lasote** [comment]
Absolutely annoying, but I think the issue is introducing the `_fill_cppinfo_from_pkgconfig` in the `package_info()`, a generator need to know the package info from the whole dependency graph, if we are using the "collect_libs" or that pkg-config stuff, it is inevitable.
