### ISSUE TITLE
[bug] Improve mingw support

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#10963]
### Environment Details (include every applicable attribute)
  * Operating System+version: Wingows 10
  * Compiler+version: gcc version 11.2.0 (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders)
  * Conan version: 1.47.0

### Steps to reproduce (Include if Applicable)
install mingw using choco:
choco install mingw -y

add new profile mingw:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=win32
compiler.version=11.2
cppstd=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja
CC=gcc
CXX=g++

create new repository from examples:
conan new hello/0.1 -m=cmake_lib

try to build it:
conan create . --build missing -pr mingw

The build is ok, but the example executable can't be executed

**Comment by AndreyMlashkin** [comment]
[mingw_log.txt](https://github.com/conan-io/conan/files/8416165/mingw_log.txt)

**Comment by lasote** [comment]
Hi, looks like the error `3221225781` implies a missing DLL. Given that you are building a static one from the "hello" library, I would say there is something related to the MinGW installation. Would be great to know which DLL is not found so we can try to figure out if we can fix something in Conan. 
You can try to run `dumpbin /imports C:\Users\Administrator\sources\conan_test\test_package\cmake-build-release\conan\example.exe` or use any of this tools to try to locate it: https://www.raymond.cc/blog/check-what-dll-or-ocx-dependency-files-is-needed-for-a-software/

**Comment by AndreyMlashkin** [comment]
As I said, I am using MinGW from choco.

And here is the output:
dumpbin /imports C:\Users\Administrator\sources\conan_test\test_package\cmake-build-release\conan\example.exe
Microsoft (R) COFF/PE Dumper Version 14.29.30141.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\Administrator\sources\conan_test\test_package\cmake-build-release\conan\example.exe
LINK : fatal error LNK1181: cannot open input file 'C:\Users\Administrator\sources\conan_test\test_package\cmake-build-release\conan\example.exe'

**Comment by lasote** [comment]
Is the executable in that location? `C:\Users\Administrator\sources\conan_test\test_package\cmake-build-release\conan\example.exe`

**Comment by AndreyMlashkin** [comment]
Oh, no, it's one up. Here we go:

>dumpbin /imports C:\Users\Administrator\sources\conan_test\test_package\cmake-build-release\example.exe
Microsoft (R) COFF/PE Dumper Version 14.29.30141.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\Administrator\sources\conan_test\test_package\cmake-build-release\example.exe

File Type: EXECUTABLE IMAGE

  Section contains the following imports:

    libstdc++-6.dll
             14000C1E8 Import Address Table
             14000C050 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                         757 _ZNSo9_M_insertIlEERSoT_
                         771 _ZNSolsEi
                        142B _ZNSt8ios_base4InitC1Ev
                        142D _ZNSt8ios_base4InitD1Ev
                        151A _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_x
                        1556 _ZSt4cout

    KERNEL32.dll
             14000C220 Import Address Table
             14000C088 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                         11B DeleteCriticalSection
                         13F EnterCriticalSection
                         1BB FreeLibrary
                         276 GetLastError
                         28B GetModuleHandleA
                         2C6 GetProcAddress
                         2E7 GetStartupInfoA
                         37C InitializeCriticalSection
                         3D8 LeaveCriticalSection
                         3DC LoadLibraryA
                         572 SetUnhandledExceptionFilter
                         582 Sleep
                         5A5 TlsGetValue
                         5D4 VirtualProtect
                         5D6 VirtualQuery
                         630 __C_specific_handler

    msvcrt.dll
             14000C2A8 Import Address Table
             14000C110 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          52 __getmainargs
                          53 __initenv
                          54 __iob_func
                          5C __lconv_init
                          62 __set_app_type
                          64 __setusermatherr
                          74 _acmdln
                          7C _amsg_exit
                          8E _cexit
                          9E _commode
                          FF _fmode
                         14B _initterm
                         267 _onexit
                         41F abort
                         421 calloc
                         42E exit
                         442 fprintf
                         449 free
                         456 fwrite
                         486 malloc
                         48E memcpy
                         490 memset
                         4AE signal
                         4C5 strlen
                         4C8 strncmp
                         4EC vfprintf

  Summary

        1000 .CRT
        1000 .bss
        1000 .data
        1000 .debug_abbrev
        1000 .debug_aranges
        1000 .debug_info
        1000 .debug_line
        1000 .debug_line_str
        1000 .debug_str
        1000 .edata
        1000 .eh_frame
        1000 .idata
        1000 .pdata
        2000 .rdata
        1000 .reloc
        3000 .text
        1000 .tls
        1000 .xdata

**Comment by lasote** [comment]
I have no idea if that is related but the profile doesn't look good for using the new generators (CMakeToolchain and CMakeDeps). The generator Ninja has to be specified with a `conf` instead of an environment variable, also the `arch_build` and `os_build` have been deprecated for the new generators too. I'll try to debug in my windows machine tomorrow to see what I get.
The profile could look more like this:

```
   [settings]
    os=Windows
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.exception=seh
    compiler.libcxx=libstdc++11
    compiler.threads=win32
    compiler.version=11.2
    cppstd=17
    [options]
    [build_requires]
    [env]
    CC=gcc
    CXX=g++
    [conf]
    tools.cmake.cmaketoolchain:generator=Ninja
```

**Comment by AndreyMlashkin** [comment]
I have resolved the issue thanks to @SSE4 
https://github.com/conan-io/conan-center-index/issues/10119

**Comment by AndreyMlashkin** [comment]
The solution is to use full path in the build profile:

[settings]
os=Windows
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=11.2
cppstd=17
[options]
[build_requires]
[env]
CC=C:\ProgramData\chocolatey\bin\gcc.exe
CXX=C:\ProgramData\chocolatey\bin\g++.exe
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
