### ISSUE TITLE
[question] Using cmake_find_package with a project in editable mode

### ISSUE THREAD

**Issue by lbakman** [conan-io/conan#10973]
Conan version: 1.47.0
OS: Rocky 8.5
Compiler: G++ 8.5.0

Hi

I am sure I am missing something obvious, but I can't get cmake_find_package to work with a library project in editable mode. 

I have a multi component project (similar in structure to Poco), that I am developing. Until now I have produced *Config.cmake files for each of these components and installed these with the libraries.

In my consuming project, I have used the "cmake_paths" generator, to get the PATHS setup to my *Config*.cmake so I can consume my multi component project using (in cmake): find_package(MyPackage COMPONENTS Component1 Component2).

This has worked so far, but I wanted to move towards a setup where I define my components, in the package_info() method, using the self.cpp_info.components, and discard my *Config.cmake files entirely.

If I do this, and I install my multicomponent package to ~/.conan/data everything seems to work as expected. The "FindMyPackage.cmake" file generated by the consuming project, contains all my componens and the appropriate paths to include folders and libraries.

On the other hand, if I set my library project into editable mode, the generated "FindMyPackage.cmake" file no longer contains any paths to include files or libraries. Dependencies and Library names seems to be in order - it is only the paths that are missing.

Any help or pointers are very welcome.

My layout ini file looks like this:
```
[includedirs]
cmake-build-{{settings.build_type | lower}}/include

[libdirs]
cmake-build-{{settings.build_type | lower}}/lib64

[build_folder]
cmake-build-{{settings.build_type | lower}}
```

Funnily enough, the generated FindMyPackage.cmake does pick up on the build_folder for CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH. 

My package_info() method looks similar to this:

```
self.cpp_info.set_property("cmake_file_name", "MyPackage")
self.cpp_info.set_property("cmake_target_name", "MyPackage")
self.cpp_info.names["cmake_find_package"] = "MyPackage"

self.cpp_info.components["mypackage_base"].set_property("cmake_target_name", "Base")
self.cpp_info.components["mypackage_base"].names["cmake_find_package"] = "Base"
self.cpp_info.components["mypackage_base"].libs = ["MyPackageBase"]
self.cpp_info.components["mypackage_base"].requires = ["poco::poco"]

self.cpp_info.components["mypackage_service"].set_property("cmake_target_name", "Service")
self.cpp_info.components["mypackage_service"].names["cmake_find_package"] = "Service"
self.cpp_info.components["mypackage_service"].libs = ["MyPackageService"]
self.cpp_info.components["mypackage_service"].requires = ["mypackage_base"]
```

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @lbakman 

Just a couple of quick notes:

- ``cmake_find_package`` has been removed in 2.0. Replaced by CMakeDeps and CMakeToolchain (already available in 1.X)
- Defining the layouts in external files has been removed in 2.0. Replaced by ``layout()`` method (already available in 1.X)
- Editable packages are well tested with the ``layout()`` method, it should work out of the box with a template ``conan new hello/0.1 --template=cmake_lib``
- It is possible that components + editables are not that well tested with ``layout()``. If you give it a try, reports welcome.

**Comment by lbakman** [comment]
Thank you for the suggestions.
I will try tomorrow and get back with the results.

**Comment by lbakman** [comment]
Hi

I have created two test repositories to try this out, using the cmake_lib template. I am not completely done, but so far it works when I am using a single libary project, but experiencing the exact same problem as above with a multi library/component project. 

If interested, the projects are located here:
- [conan_single_layut](https://github.com/lbakman/conan_single_layout)
- [conan_multi_layout](https://github.com/lbakman/conan_multi_layout)

FYI: I have a dependency on poco/1.11.1 to make it similar to my "real" project.

I will continue to look at it tomorrow, but if anyone has any input on what could cause the xyz_INCLUDE_DIRS_DEBUG and xyz_LIB_DIRS_DEBUG to be empty in the multi component situation when using editable mode I would be very grateful.

Regards Lau

**Comment by memsharded** [comment]
Hi @lbakman 

I think I know where the issue is. When defining components, their layout for editable mode needs to be defined also in the ``layout()`` method and not only in the ``package_info()`` method, because that is valid only for the final packaged package.

So something like this would be necessary:

```python
def layout(self):
        self.folders.source = "my_sources"
        self.folders.build = "my_build"

        self.cpp.build.components["foo"].includedirs = ["my_include_foo"]
        self.cpp.build.components["foo"].libdirs = ["my_libdir_foo"]
        self.cpp.build.components["foo"].libs = ["hello_foo"]
        self.cpp.build.components["foo"].objects = ["myobjs/myobject.o"]
```

I thinks this might be our fault, because I can't find this in our docs, you might find hints of using ``self.cpp.build.libdirs``, but not the equivalent for components. Please let us know how it goes if you can give it a try. It is tested in our test suite, so it should work.

**Comment by lbakman** [comment]
Thank you so much for the help. That last bit did the trick. I did have to setup package.components as well, but in the end I got it working.

My layout for a single component looks like this now:

```
self.cpp.package.components["LibA"].includedirs = ["include"]
self.cpp.package.components["LibA"].libdirs = ["lib"]
self.cpp.source.components["LibA"].includedirs = ["LibA/include"]
self.cpp.build.components["LibA"].includedirs = ["LibA/include"]  # Generated includes
self.cpp.build.components["LibA"].libdirs = ["LibA"]
```

I am sure improvements can be made to my layout or package_info, but so far it seems to work.

I am leaving my test projects up, if anyone wants to check them out.
