### ISSUE TITLE
[question] Can I pass CMake variables from a package using CMakeDeps / CMakeToolchain?

### ISSUE THREAD

**Issue by realbogart** [conan-io/conan#10976]
Using CMakeDeps & CMakeToolchain:
Is there a way to pass custom CMake variables from a package that can then be used in the consumer CMake scripts?

I have packages that include some extra utility files that I want to use later in my project. 

Ideally I would just want to call:

`find_package(my_package)`

and have that automatically set up a CMake variable called `MY_PACKAGE_SPECIAL_UTILITY_PATH` specified in a Conan recipe. I know that it can be solved using build modules, but is there an easier way?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Yes, you can declare a [property](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#properties) `cmake_build_modules` at the `package_info()` of the `my_package` recipe, with `.cmake` files with the code you want, so these files declared will be automatically included when you call `find_package(my_package)`.


```python
def package_info(self):
    self.cpp_info.set_property("cmake_build_modules",[os.path.join("cmake", "other.cmake")])
```

**Comment by realbogart** [comment]
Thank you for your quick reply @lasote ! 

As mentioned in my original message, I already knew about the build module way. So this is the only way to do it? I was hoping to avoid packaging an extra build module file. I guess it's not too bad though.

**Comment by lasote** [comment]
Oh, sorry I didn't read it properly. If you want that variable to be automatically declared when `find_package`, there is no other way. You can pass general information, for example with `self.conf_info` but you would need to take that information in the consumer `generate()` method and use it to set a variable to the toolchain.

**Comment by realbogart** [comment]
No worries. Thank you for your help!
