### ISSUE TITLE
[bug] Adding AWS-CPP-SDK fails on Linux

### ISSUE THREAD

**Issue by ayeganov** [conan-io/conan#10977]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux thebeast 5.4.0-105-generic Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
  * Compiler+version: g++ (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
  * Conan version: 1.47.0
  * Python version: 3.8.1

### Steps to reproduce (Include if Applicable)

Use the conanfile below. The important bit is the `text-to-speech` option being set to True.

```
from conans import ConanFile, CMake


class SampleFile(ConanFile):
    name = "SampleFile"
    settings = "os", "compiler", "build_type", "arch"
    exports = "*"
    build_policy = "missing"
    requires = (
        "aws-sdk-cpp/1.9.100",
    )
    generators = "cmake"
    default_options = { "libcurl:with_ntlm": False,
                        "aws-sdk-cpp:sns": True,
                        "aws-sdk-cpp:text-to-speech": True,
                      }

    def build(self):
        cmake = CMake(self)
        self.run(f"cmake --build . {cmake.build_config} -j8")
```

Run the install command:

`conan install .. --build=missing`

### Logs (Executed commands with output) (Include/Attach if Applicable)

Downloading pulseaudio-14.2.tar.xz completed [1905.57k]                                  

ERROR: pulseaudio/14.2: Error in source() method, line 89
	tools.get(**self.conan_data["sources"][self.version], strip_root=True, destination=self._source_subfolder)
	ReadError: file could not be opened successfully

### Root Cause

The downloaded pulseaudio file `pulseaudio-14.2.tar.xz` eventually gets handed to gzip to be opened, but it fails due to the magic number check in gzip.py:

```
    def _read_gzip_header(self):
        magic = self._fp.read(2)
        if magic == b'':
            return False

        if magic != b'\037\213':
            raise BadGzipFile('Not a gzipped file (%r)' % magic)
```

**Comment by lasote** [comment]
If I get it correctly there is an issue unzipping the `pulseaudio-14.2.tar.xz`, right?
Could you try this simple recipe and run a `conan create .`?

```python

from conans import ConanFile, CMake, tools


class LibConan(ConanFile):
    name = "lib"
    version = "1.0"

    def source(self):
        tools.get("https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-14.2.tar.xz")

```

**Comment by ayeganov** [comment]
@lasote 

Here is the output from your recipe:

```
╰─❯ conan create .
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
lib/1.0: A new conanfile.py version was exported
lib/1.0: Folder: /home/..../.conan/data/lib/1.0/_/_/export
lib/1.0: Exported revision: 064ba3cefc1c7ad82b5409691c025541
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

lib/1.0: Forced build from source
Installing package: lib/1.0
Requirements
    lib/1.0 from local cache - Cache
Packages
    lib/1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build

Installing (downloading, building) binaries...
lib/1.0: Configuring sources in /home/ainindza/.conan/data/lib/1.0/_/_/source
Downloading pulseaudio-14.2.tar.xz completed [1905.57k]                                  

ERROR: lib/1.0: Error in source() method, line 9
	tools.get("https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-14.2.tar.xz")
	ReadError: file could not be opened successfully
```

**Comment by lasote** [comment]
I tried in a docker image of Ubuntu 20 and it works without any issue. Might it be an issue on your network?

**Comment by ayeganov** [comment]
Definitely not a network issue. I used `tar xf` manually on the file and it worked fine. I am able to download lots of other packages and none of them fail except this specific one.

**Comment by lasote** [comment]
So, you can uncompress with `tar xf` the file downloaded with Conan? (to discard a "downloader" issue).

**Comment by ayeganov** [comment]
@lasote yes.

**Comment by lasote** [comment]
Could you check the `md5sum` of the downloaded file? I got `1efc916251910f1e9d4df7810e3e69f8` but I can perfectly unzip the file with Conan :S

**Comment by ayeganov** [comment]
╰─❯ md5sum pulseaudio-14.2.tar.xz 
1efc916251910f1e9d4df7810e3e69f8  pulseaudio-14.2.tar.xz

**Comment by SSE4** [comment]
can you try to run? `python -c "import lzma"`
we had a similar isssue in our CI in the past, it turned out problem was in incorrect python installatiion (without lzma module)
see also https://github.com/conan-io/conan-center-index/pull/9609

**Comment by ayeganov** [comment]
@SSE4 you nailed it! When I don't have `lzma` it fails.

**Comment by lasote** [comment]
Kudos @SSE4
