### ISSUE TITLE
[bug] Backslashes in path not handled properly by 'output_dirs' block of CMakeToolchain

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#10982]
In the _layout()_ method, the string we use to define the _outdir for includedirs_ is a windows path with backslashes like `inc\Fboot`:
>  `self.cpp.package.includedirs = ["inc\Fboot"]`

The generated _conan_toolchain.cmake_ contains the following line in the part corresponding to the _output_dirs_ block of _CMakeToolchain_:
> `set(CMAKE_INSTALL_INCLUDEDIR "inc\Fboot")`

where the backslash is then interpreted as an escape character instead of a path separator.
Is this a bug or are we using it wrongly?

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Conan version: 1.46.0
  * Python version: 3.10.0

**Comment by franramirez688** [comment]
Hi @marausch 

The problem is you're not escaping the backslash properly in your python code. Anyway, you can use both a backslash or a simple slash. For instance:

```python
self.cpp.package.includedirs = ["inc\\Fboot"]  # put double backslash

# Or

self.cpp.package.includedirs = ["inc/Fboot"]  # slash
```
I guess that it's going to make the trick. Conan is managing these paths internally so it's making all the transformations needed for CMake.

**Comment by marausch** [comment]
Thank you, Francisco1

In fact, we need to use os.path.join() and we convert the native (on windows) backslash like this:

self.cpp.package.includedirs = pathlib.Path(os.path.join("inc", modulename)).as_posix()

We thought that this solution was just a workaround to a problem because it seems that all other paths found in conan_toolchain.cmake have slashes instead of backslashes (but these are all generated by Conan, I guess).

BR,
Mch


--
Best regards | Mit freundlichen Grüßen | Ystävällisin terveisin | Med venlig hilsen | Cordialement | Distinti saluti
Michael Rausch
R&D Software Engineer, Control Platform

Danfoss Srl
Via Roma 2
39014 Burgstall (Südtirol), Italy
Tel: +39 0473 671970
E-mail: ***@***.******@***.***>
http://www.danfoss.com<http://www.danfoss.com/>



Classified as Business
