### ISSUE TITLE
Improve "conan help profile" with "delete" information

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#10989]
I think it would be good to add info into the conan help profile printout,
conan profile delete --> "command not available by design, please manually delete from XYZ"

Without that information, I tried to use "conan profile remove" (which was also suggested by a helpful Slacker)
But "remove" only removes keys, not entire profiles.

Without the suggested information, the user's eye will naturally find 'remove', try it, and confusion happens.
In terms of UI, I find if users have a 'greyed out button' they don't punch other buttons hoping it will work.

**Comment by czoido** [comment]
Hi @paulharris,
That command has changed for 2.0, because we don't want conan to do operations like just editing files through the command line so at least that mistake won't happen in 2.0.
For 1.0 maybe we could add some note to the documentation or something, thanks a lot for your suggestion!

**Comment by paulharris** [comment]
I'll just close this and wait for 2.0 :)
