### ISSUE TITLE
Conan check --require-override is possible with multiple packages

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#10987]
Having a version range dependency like

requires = "demo_test/[~1.0]"

means that the conan recipe will take the latest version it can find of the demo_test package in major version 1 and minor version 0. Conan provides the argument --require-override so that it is possible to override the dependency and specific a concrete version like --require-override=demo_test/1.0.6.

Now the question is if it is possible to use multiple require-override when creating a conan package. e.g.

name = "demo_new"
version = "1.0.0"
requires = "demo_test/[~1.0]", "demo_test2/[~1.0]"

and use the require-override multiple times:

conan create . --require-override=demo_test/1.0.6 --require-override=demo_test2/1.0.4

Conan allows for such use of multiple require-override?

**Comment by memsharded** [comment]
Hi @Srikanthnetha47 

Yes, ``--require-override`` argument has an "append" action, it should be able to provide multiple values. Did you try and it didn't work?

**Comment by ghost** [comment]
Yes i tried, its works for me now.
