### ISSUE TITLE
[feature] do not fail `conan info` on conflicts

### ISSUE THREAD

**Issue by fukanchik** [conan-io/conan#10993]
I run conan info trying to find what of my dependencies `requires` package ncbi-cxx-toolkit-public/26.0.1.
However conan info fails before printing dependency tree:
$ conan info ..
ncbi-cxx-toolkit-core/0.0.0: Analyzing requirements. Please wait...
Package requires  lmdb/0.9.29@#3bdb51ff4c3649bd865ee3857f0f2e07
Package requires  libdb/5.3.28@#355aa134e9ee1bda60fa224f8b54c913
Package requires  lzo/2.10@#76a80652793ae478a12f6f9a8eb17a89
Package requires  bzip2/1.0.8@#493645787acdd3909523a6a2773b1b36
Package requires  pcre/8.45@#b6bae758d36ca2050bb8527ea408eb75
Package requires  libmysqlclient/8.0.25@#bbe62517865849c442c032cc7aecfd57
Package requires  libuv/1.42.0
Package requires  zlib/1.2.11@#683857dbd5377d65f26795d4023858f9
Package requires  libnghttp2/1.45.1@#cef166f78349143079e1c667d823b25a
WARN: ncbi-cxx-toolkit-core/0.0.0: requirement openssl/1.1.1l overridden by your conanfile to openssl/1.1.1m 
WARN: pcre/8.45: requirement bzip2/1.0.8 overridden by ncbi-cxx-toolkit-core/0.0.0 to bzip2/1.0.8 
WARN: pcre/8.45: requirement zlib/1.2.12 overridden by ncbi-cxx-toolkit-core/0.0.0 to zlib/1.2.11 
WARN: libmysqlclient/8.0.25: requirement zlib/1.2.11 overridden by ncbi-cxx-toolkit-core/0.0.0 to zlib/1.2.11 
WARN: ncbi-cxx-toolkit-public/26.0.1: requirement openssl/1.1.1l overridden by xdb/0.0.1 to openssl/1.1.1m 
WARN: cassandra-cpp-driver/2.15.3: requirement libuv/1.41.1 overridden by ncbi-cxx-toolkit-public/26.0.1 to libuv/1.42.0 
WARN: cassandra-cpp-driver/2.15.3: requirement openssl/1.1.1k overridden by ncbi-cxx-toolkit-public/26.0.1 to openssl/1.1.1m 
WARN: minizip/1.2.11: requirement zlib/1.2.12 overridden by cassandra-cpp-driver/2.15.3 to zlib/1.2.11 
ERROR: Conflict in ncbi-cxx-toolkit-public/26.0.1:
    'ncbi-cxx-toolkit-public/26.0.1' requires 'libnghttp2/1.46.0' while 'ncbi-cxx-toolkit-core/0.0.0' requires 'libnghttp2/1.45.1'.
    To fix this conflict you need to override the package 'libnghttp2' in your root package.
Just a moment...

I know there is a conflict, thank you very much, conan. What I am trying to find here is which one of dependencies in my dependency tree introduced ncbi-cxx-toolkit-public/26.0.1. I do not use it directly.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, it is true that in 1.X it is difficult to diagnose conflicts in large graphs. I am making sure in https://github.com/conan-io/conan/pull/10994 that ``conan graph info`` will work even when there are conflicts, and we will later work on the UX too to display more info in the output to help. 

Thanks for reporting!

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/10994 implemented this. ``conan graph info`` is no longer crashing (in Conan 2.0-alpha.7 to be released) for graphs with conflicts, so it might still report requires, etc. The output still needs to be improved, but the main feature was enabled with that PR. Lets work later on the UI and error reporting.

**Comment by fukanchik** [comment]
thanks!

**Comment by xzxzzxzxzca** [comment]
Any plans for the 1.* branch? It looks like some packages are not conan2 compatible and thus force sticking to conan1 for a while. I'm facing the same problem of trying to figure out the dependency conflict and I can't upgrade yet, I'm afraid.

**Comment by memsharded** [comment]
No, I am afraid that this would be breaking in Conan 1.X, so it is not possible to provide it there, and adding opt-ins or other similar things,  would be too much effort for the value in any case.
