### ISSUE TITLE
Artifactory uploads do not contain properties from artifacts.properties

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1099]
Not sure what's going on here, but with a `~/.conan/artifacts.properties` file containing:
```
artifact_property_test.property=Hello
artifact_property_build.number=1234
```
, I see no properties being set on the uploaded artifact in Artifactory (at any level of depth).  I debugged a little, and the return value of `ClientCache.read_put_headers(self)` seems to be correct.  It's just that after the upload (with or without `--all`), there are no properties shown in Artifactory (just the usual conan info).

**Comment by lasote** [comment]
I think it's available in the latest Artifactory version 5.1.2. What Artifactory version do you have?

**Comment by tamboril** [comment]
5.0.0

**Comment by tamboril** [comment]
It works with Artifactory 5.1.3, at least on all the files.  Package properties are not set.

**Comment by lasote** [comment]
Yes, the properties in Artifactory are file level, there is no "package properties" concept.
