### ISSUE TITLE
[question] Can I build conan2 package with conan1 packages using conan 2.0?

### ISSUE THREAD

**Issue by wer14** [conan-io/conan#10992]
Can I build conan2 package with conan1 packages using conan 2.0?

> If you want to migrate to 2.0, there are several things you will need to change:
> 
> The recipes have to be updated to be compatible with Conan 2.0. There are 2.0 features ported to Conan 1.X so you can get a compatible recipe with 2.0 using Conan 1.X.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @gmikhaile,
What that means is that you can update your current recipes that work in conan1 so that they work also in conan2. That is to allow transition to conan 2.0.
