### ISSUE TITLE
[bug] python exception when consuming editable package with CMakeDeps

### ISSUE THREAD

**Issue by n-morales** [conan-io/conan#11005]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux Mint 20.3
  * Compiler+version: gcc 11.2
  * Conan version: 1.47.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
1. Create a conanfile.py, omitting the `layout()` and using the CMakeDeps/CMakeToolchain generator
2. `conan editable add /path/to/package package-name@channel/stable`
3. List the package as a dependency in another project using CMakeDeps/CMakeToolchain
4. Run conan install, it fails

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: package-name@channel/stable: Error in generate() method, line 45
        tc.generate()
        TypeError: expected str, bytes or os.PathLike object, not NoneType
```

After some python debugging, I found that what was happening is that `self.folders.generators` is `None`, causing the error. Either this should be made clear that you have to define it, or it is a problem with editable packages. This issue doesn't show up with just installing the first package. The workaround is to define `self.folders.generators` in the `layout()` method.

**Comment by n-morales** [comment]
FWIW I found a hack to workaround this, by adding the following to the editable package's conanfile:
```py
  @property
  def generators_folder(self):
      return self.folders.generators_folder if self.folders.generators_folder is not None else ""
```

**Comment by lasote** [comment]
Sorry I cannot reproduce the issue, I tried with an empty `layout()` and without `layout()` method, could you provide an example?

**Comment by lasote** [comment]
Reading [this](https://github.com/conan-io/conan/issues/11006), just note, that the old editable layouts file are deprecated and won't work when the `layout()` method is declared, nor the new generators like CMakeDeps and CMakeToolchain.

**Comment by n-morales** [comment]
> Sorry I cannot reproduce the issue, I tried with an empty `layout()` and without `layout()` method, could you provide an example?

Thank you for the quick response! I thought that they `layout()` function was the key -- I will come up with a minimal reproducer and post it here.

> Reading [this](https://github.com/conan-io/conan/issues/11006), just note, that the old editable layouts file are deprecated and won't work when the `layout()` method is declared, nor the new generators like CMakeDeps and CMakeToolchain.

Ahh that makes sense. I was using the editable layouts in the past, and didn't realize they were deprecated.

**Comment by memsharded** [comment]
Closing this ticket as inactive and outdated. Conan 2 editables and CMakeDeps will not have this issue. Don't hesitate to create new tickets for any further question or issue, thanks for your feedback.
