### ISSUE TITLE
[bug] conan install command fails to find prebuilt binaries after revisions_enabled changed in config

### ISSUE THREAD

**Issue by apyvovar** [conan-io/conan#11002]
Conan version: any; OS: any.

Steps to reproduce:
1. disable conan package revisions: `conan config set general.revisions_enabled=False`
2. remove `some_package` from cache
3. execute `conan install <some_package> <some_package_options>`
4. enable conan package revisions: `conan config set general.revisions_enabled=True`
5. execute `conan install <some_package> <some_OTHER_package_options> --build=never`

Result:
`ERROR: Missing prebuilt package for 'some_package'` and 
```
Build requirements packages
    <some_package>:<hash> - Missing
```

Expected:
IMO conan should handle change of `revisions_enabled` by updating conanfile.py in cache to regarding package  revisions or at least indicate the actual core problem in error message. Current error message of `Missing prebuilt package` package is IMO confusing and misleading in this case.

**Comment by memsharded** [comment]
Hi @apyvovar 

Conan migrations only happen on a version upgrade, it is simply too complicated to do it on configuration changes. Also, revisions would be too complicated to implement for an automatic migration.

That indeed results in error messages that are not that helpful, I agree.

As this is no longer an issue in Conan 2.0, which is close to enter the beta stage (already at alpha.6), I am labeling this as a "question", as it would be a very big effort to change that for Conan 1.X for the value. Thanks very much for reporting anyway!

**Comment by memsharded** [comment]
Closing as outdated, Conan 2 has been out for more than 1 year
