### ISSUE TITLE
[feature] less verbose output in CMakeDeps

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#11001]
I think CMakeToolchain is too verbose and it would be better to skip these messages.

![Screen Shot 2022-04-09 at 11 12 40 AM](https://user-images.githubusercontent.com/7117696/162567546-37d83801-4b81-43b7-a15b-36374c874d82.png)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This is a ``CMakeDeps`` issue, not a ``CMakeToolchain`` one, updating the title

**Comment by memsharded** [comment]
We might change how libs are found in CMakeDeps code. Better don't touch this at this moment, it can wait until that is figured out. Also, probably the way is not just removing those messages, but using a different log level like DEBUG

**Comment by memsharded** [comment]
Those outputs were removed some time ago, closing this ticket as solved.
