### ISSUE TITLE
[question] How can I crosscompile to iOS with cmake?

### ISSUE THREAD

**Issue by SimplyLiz** [conan-io/conan#11008]
I've tried the steps described here:
https://docs.conan.io/en/1.45/integrations/cross_platform/ios.html

Which leads to:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/7029836/162708824-640611d6-a782-4d45-9456-84742e6188e3.png">

I then downloaded a iOS toolchain file. I don't know which one to use, since the documentation is really unspecific about it, so I googled and found this one:
https://github.com/leetal/ios-cmake

Calling cmake with the toolchain file `cmake -GXcode -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake -DPLATFORM=OS64 ..`

just leads to
```
CMake Error at build_test/conanbuildinfo_multi.cmake:31 (message):
  Framework library Cocoa not found in paths:
Call Stack (most recent call first):
  build_test/conanbuildinfo_release.cmake:229 (conan_find_apple_frameworks)
  build_test/conanbuildinfo_multi.cmake:1463 (include)
  cmake/DependenciesFunctions.cmake:259 (include)
  CMakeLists.txt:86 (resolve_conan_dependencies)
  ```

I do have all the necessary frameworks, and I can build swiftUI projects with Xcode just fine.

Is there any documentation on how I can cross build my cmake project for iOS with Conan? I really don't know how I could get this to work. :-/

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
The way to do it is using the [CMakeToolchain](https://docs.conan.io/en/1.45/integrations/cross_platform/ios.html#use-built-in-conan-toolchain) (the only supported in the coming Conan 2.0) In your profile you have to declare the compiler or include the "default" one:

```
include(default)
[settings]
...

```

**Comment by SimplyLiz** [comment]
Thank you for the quick reply. 

I copied the profile from the documentation ,so it has `include(default`
```
include(default)

[settings]
os=iOS
os.version=9.0
arch=armv7

[tool_requires]
darwin-toolchain/1.0@theodelrieu/stable
```

but it still doesn't work.

Is there somewhere a working example i can use for the current conan version? 
Also, what is `os.version=9.0` supposed to mean?  iOS version? The latest one is 15.4.1
My Mac is M1 with latest macOS, xcode and of course conan.

**Comment by lasote** [comment]
Run this:

```
conan new lib/1.0 --template cmake_lib
```

Create a **ios_profile** with (validate your system values):

```
[settings]
os=iOS
os.version=12.0
os.sdk=iphoneos
arch=armv8
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
```

Apply host and build profiles and create the iOS binary for the default example library:

```
conan create . --profile:host=ios_profile --profile:build=default
```

**Comment by SimplyLiz** [comment]
Thank you! Your profile seems to work, I've added it in my conan_cmake_install call and now it does something.. (fails with openal, but that's something different).
Could you maybe update the documentation? This helped me a lot :)

**Comment by paulocoutinhox** [comment]
Hi,

I recommend you check my project:
https://nativium.github.io/

Have everything about this ready to use for all platforms.

**Comment by 11janson** [comment]
Thanks. It works for me too.
