### ISSUE TITLE
[bug] Characters are not escaped in pkg config generators

### ISSUE THREAD

**Issue by StellaSmith** [conan-io/conan#11013]
https://github.com/conan-io/conan/blob/6739257c4e83943d736aa3eea9544281dce03c2e/conans/client/generators/pkg_config.py#L118-L122

see conan-io/conan-center-index#10257

**Comment by lasote** [comment]
Hi, from [here](https://github.com/conan-io/conan-center-index/pull/10257) `self.cpp_info.defines.append("IMGUI_USER_CONFIG='\"imgui_user_config.h\"'")` you are escaping the value of the define, in the generator we cannot do that as the define is a whole string unless we probe that escaping everything also works, something like this?:


```
lines.append("Cflags: %s" % _concat_if_not_empty( 
     [include_dirs_flags, 
      cpp_info.cxxflags, 
      cpp_info.cflags, 
      ['-D"%s"' % d for d in cpp_info.defines]])) 
```

Another alternative could be replacing `"` with `\"` or stuff like that, but it is difficult to say what would work, we would need to investigate creating a package with a similar "define" and reusing with Meson and CMake.

**Comment by StellaSmith** [comment]
I think that doing something like the following could work:
```py
lines.append("Cflags: %s" % _concat_if_not_empty( 
     [include_dirs_flags, 
      cpp_info.cxxflags, 
      cpp_info.cflags, 
      ["-D%s" % shlex.quote(d) for d in cpp_info.defines]])) 
```

**Comment by lasote** [comment]
thanks, we will make sure with a couple of test with Meson and CMake.

**Comment by lasote** [comment]
Let's try something like https://github.com/conan-io/conan/pull/11039

**Comment by czoido** [comment]
Hi @StellaSmith,

Could you have a try to the changes in #11073 to check if that solves your problem.

You could try them installing conan from the PR branch using: 

`pip install git+https://github.com/czoido/conan.git@escape_pkg_config`
