### ISSUE TITLE
[feature] parse_conanfile at public ConanAPI

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#11012]
We are going to need something similar to the old "conan inspect" command. It could be a custom command but we need a public API to call. There are methods in the `conan_api.graph` to load conanfiles but they process the settings and I guess when we inspect attributes we just want the pure python ones. (raw settings dict, for example).

This code might work but it is using internal implementation (`parse_conanfile`):

```python
from conans.cli.command import conan_command, COMMAND_GROUPS
from conans.cli.output import ConanOutput
from conans.client.loader import parse_conanfile


@conan_command(group=COMMAND_GROUPS['creator'])
def inspect(conan_api, parser, *args, **kwargs):
    """
    Return the specified attribute of an attribute
    """
    parser.add_argument("path", help="Path to a folder containing a recipe (conanfile.py)")
    parser.add_argument("attribute", help="Attribute of the conanfile to read")
    args = parser.parse_args(*args)

    _, conanfile = parse_conanfile(args.path)
    ret = getattr(conanfile, args.attribute)
    out = ConanOutput()
    out.write(str(ret))

```

Where it should live (at which subAPI) that function?

**Comment by memsharded** [comment]
I think one of the most important things is to make this command a bit more limited than it used to be. In 1.X, if the ``inspected`` reference doesn't exist in the cache, it will downloaded to be able to read and parse it. We might want to reduce the old command so it never downloads.

It also worked on an ambiguous local path conanfile.py and cache recipe-reference. We probably want to disambiguate that too.

**Comment by lasote** [comment]
Does that mean we are introducing "conan inspect" in the core again? This issue was created to implement something in the Conan API that could make a custom command work, your concerns are about the command.

**Comment by memsharded** [comment]
> Does that mean we are introducing "conan inspect" in the core again? This issue was created to implement something in the Conan API that could make a custom command work, your concerns are about the command.

Yes, my concerns are about the command, or having a new API that mimics the previous command behavior. So I don't want any of those, not the command that can actually download from the server to inspect, nor the API that will download from the server to inspect.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/11136
