### ISSUE TITLE
[bug] os.version is not passed to objective C compiler/linker flags

### ISSUE THREAD

**Issue by bkarasm** [conan-io/conan#11019]
I noticed this issue when I tried to install glib/2.72.0 from conan center on MacOS with ` -s os.version=10.12 `. I found out that produced glib libraries does not contain minimum version applied as I specified. 

After digging into meson generated ` build.ninja ` I noticed that ` -mmacosx-version-min=10.12 ` flag is NOT added to ` objc_COMPILER ` and `objc_LINKER ` set of flags. Not sure if this is Conan or Meson issue.

### Environment Details (include every applicable attribute)
  * Operating System+version: MacOS 12.2.1
  * Compiler+version: apple-clang 12.0.0
  * Conan version: 1.47.0
  * Python version: 3.9.8

### Steps to reproduce (Include if Applicable)
Command used to install glib: ` conan install glib/2.72.0@ -s os.version=10.12 -o glib:shared=True --build missing `

Output of the ` otool -l libglib-2.0.0.dylib `:
```
...
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 11.1
      sdk 11.1
   ntools 1
     tool 3
  version 609.8
...
```

**Comment by franramirez688** [comment]
Hi @bkarasm,

Thanks for reporting it but `glib` recipe is using the legacy `Meson` builder and we're not maintaining it anymore because we're in the process of migrating step by step every Conan 1.x one to Conan 2.x so they'll be using the new `conan.tools` generators like the new `MesonToolchain` asap.
The new `MesonToolchain` is adding that flag automatically so that problem should be solved.

**Comment by kambala-decapitator** [comment]
I'm seeing a similar issue with Boost: `os.version` seems to have been ignored during the build, although not sure if it's related to objc and/or link flags.

```
> vtool -show-build /Users/kambala/.conan/data/boost/1.79.0/_/_/package/4ce36ef959ecd1c98e211c772ca31b2a9c9c2e61/lib/libboost_locale.dylib
/Users/kambala/.conan/data/boost/1.79.0/_/_/package/4ce36ef959ecd1c98e211c772ca31b2a9c9c2e61/lib/libboost_locale.dylib:
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACOS
    minos 12.0
      sdk 12.3
   ntools 1
     tool LD
  version 764.0
```

but in my profile I have `os.version=10.13`. I also see that the build command did have the needed flag:

> boost/1.79.0: WARN: b2 -q target-os=darwin architecture=x86 address-model=64 binary-format=mach-o abi=sysv --layout=system --user-config=/Users/kambala/.conan/data/boost/1.79.0/_/_/source/source_subfolder/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=on boost.locale.iconv.lib=libiconv threading=multi visibility=hidden link=shared variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-filesystem --with-iostreams --with-locale --with-log --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure toolset=clang-darwin pch=on -sICONV_PATH=/Users/kambala/.conan/data/libiconv/1.17/_/_/package/695abc271c487ea9fb8409de6f2960c1c0be9cdd linkflags="-stdlib=libc++" cxxflags="-fPIC -stdlib=libc++ **-mmacosx-version-min=10.13** -DBOOST_STACKTRACE_ADDR2LINE_LOCATION=/usr/bin/addr2line" install --prefix=/Users/kambala/.conan/data/boost/1.79.0/_/_/package/4ce36ef959ecd1c98e211c772ca31b2a9c9c2e61 -j6 --abbreviate-paths -d0 --debug-configuration --build-dir="/Users/kambala/.conan/data/boost/1.79.0/_/_/build/4ce36ef959ecd1c98e211c772ca31b2a9c9c2e61"

Other libraries were built correctly, for example:

```
> vtool -show-build /Users/kambala/.conan/data/ffmpeg/4.4/_/_/package/ef8e71b8a0af027ee62fc961c8282392ede5f251/lib/libavcodec.58.134.100.dylib
/Users/kambala/.conan/data/ffmpeg/4.4/_/_/package/ef8e71b8a0af027ee62fc961c8282392ede5f251/lib/libavcodec.58.134.100.dylib:
Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 12.3
```

macOS 12.5, conan 1.51.2 from pip, Xcode 13.4.1 (clang 13).

Opened https://github.com/conan-io/conan-center-index/issues/12328

**Comment by AbrilRBS** [comment]
This was fixed a while ago but the issue was never closed, if a similar issue ever resurfaces, feel free to reopen/create a new issue :)
