### ISSUE TITLE
[bug] CMake `CMAKE_GENERATOR_PLATFORM` is not set when building with `-s arch=x86` & `compiler.version=14`

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#11018]
### Environment Details (include every applicable attribute)
  * Operating System+version:
  ```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19044 N/A Build 19044
```
  * Compiler+version:
 ```
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24245 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```
  * Conan version:
  ```
  Conan version 1.46.0
  ```
  * Python version:
```
Python 3.7.8
```
  * CMake version:
```
cmake version 3.21.3
```
### Steps to reproduce (Include if Applicable)
1. Use `CMake` in `build()` method in the recipe file:
```
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```
2. In the `default` profile, use `compiler.version=14` 
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=14
build_type=Release
distro=None

[options]
[build_requires]
[env]
```
3. Create the package for `x86`:
```
conan create . -s arch=x86
```

4. `CMAKE_GENERATOR_PLATFORM` is empty, and my `CMakeListst.txt` file can't detect that the arch is `x86`.

### Logs (Executed commands with output) (Include/Attach if Applicable)
Conan configuration: 
```
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
distro=None
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```
CMake configuration:
```
-- Selecting Windows SDK version  to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.0.24245.0
-- The CXX compiler identification is MSVC 19.0.24245.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
```

While `CMAKE_GENERATOR_PLATFORM` =`Win32` in the following cases:
- `default` profile has `compiler.version=16`, uses `Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped`
- `default` profile has `compiler.version=17`.
- `cmake` normal command `cmake -B ./build/bf -G "Visual Studio 14 2015" -A Win32`

**Any workaround to detect the `x86` architecture in CMake with `compiler.version=14`?**

--

**Comment by memsharded** [comment]
Could you please clarify which build system integration are you using? I mean, what is the import for ``cmake = CMake(self)``? Is it the ``from conan.tools.cmake import CMake`` one or the legacy one?

Can we reproduce this with a ``conan new hello/0.1 --template=cmake_lib``?

**Comment by Bassem-Ramzy** [comment]
I'm using:
```py
from conans import ConanFile, CMake
```

**Comment by memsharded** [comment]
Ok, that is the legacy one. Using the new one in theory solves this issue.

**Comment by Bassem-Ramzy** [comment]
Yes, this one works, thanks.
BTW, must I use `generate()` method with this wrapper? Without it I get error `conanbuild.conf does not exist. Please, make sure that it was not generated in another folder`.

**Comment by memsharded** [comment]
> BTW, must I use generate() method with this wrapper? Without it I get error conanbuild.conf does not exist. Please, make sure that it was not generated in another folder.

``generate()`` method for the ``generators = "CMakeToolchain", "CMakeDeps"`` will be called automatically, creating the ``conanbuild.conf``. ``CMake`` should find it, if it didn't probably there is some discrepancy, and ``layout()`` method could solve it. (``CMake`` expects to find it in the ``generators_folder``
