### ISSUE TITLE
[question] option `shared` in profile for creating a package

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#11026]
When `conan create`, I'd like shared builds.
1. Is it ok to set it in a profile?
2. which one as below is right?
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
compiler.cppstd=17
build_type=Debug
[options]
shared=True
[build_requires]
[env]
```
or
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
compiler.cppstd=17
build_type=Debug
[options]
*:shared=True
[build_requires]
[env]
```
3. recipe, profile, conanfile.txt all can set option `shared`, who override who?

**Comment by AbrilRBS** [comment]
Sorry that we didn't get back to you sooner - I'll answer for posterity in case anyone ever has the same questions as you had:
> 1) Is it ok to set it in a profile?

It's in fact recommended if you plan to have any kind of traceability and reproducibility to store the profiles you use, and in those have all the options necessary, but it's also possible to set it in the CLI with the same syntax using the `-o` arguments

> 2) which one as below is right?

While this mostly depends on your use-case, for Conan Center Index we have found great success setting the shared option uniformly across the graph, so `*:shared=True` is probably the way to go

> 3) recipe, profile, conanfile.txt all can set option shared, who override who?

The base profile files have the least priority, followed by the CLI options, and then the ones set by the recipes. The intra recipe overwriting is a bit more complex, check https://docs.conan.io/2/knowledge/faq.html#defining-options-for-dependencies-in-conanfile-py-recipes-doesn-t-work for extra info


Hope this helps anyone that stumbles upon this issue - should any other questions remain, please feel free to create a new issue, we're always happy to help (And again, sorry for the radio silence) :)
