### ISSUE TITLE
[question] How to require a lib in a C++17

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#11023]
profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
cppstd=17
[options]
[build_requires]
[env]
```

e.g.
conan recipe `Ra` is for `liba`, `liba` needs C++17,  and `liba` depends on `poppler`.
If `liba` in C++ 17 links to `poppler` in C++ 11, `poppler` will not work properly, it must link to `poppler` in C++ 17.
When `conan`  searches binary in remote, it discards C++ standard, doesn't it? i.e. if binaries in C++ 11 exists, the binaries will be downloaded, regardless of the C++ standard in the profile.

UPDATE
It's likely that if add `cppstd` to `settings` as below, the dependencies will also respect `cppstd`, right?
```py
settings = ("os", "compiler", "build_type", "arch", "cppstd")
```

**Comment by franramirez688** [comment]
Hi @playgithub 

Several points here.
Putting `cppstd` as a general setting is deprecated, you should put `compiler.cppstd` instead.
Apart from that, you can use the `--build missing` option with your `conan install` or `conan create` commands to force a local build in case of the binaries are you trying to look for are not there.

**Comment by playgithub** [comment]
> Putting `cppstd` as a general setting is deprecated, you should put `compiler.cppstd` instead.

Fine

> Apart from that, you can use the `--build missing` option with your `conan install` or `conan create` commands to force a local build in case of the binaries are you trying to look for are not there.

OK, I know about `--build missing`.
At first I'm not sure if the dependecies respect `compiler.cppstd`,
after testing, the codes below will make all the dependencies (include trnasitive dependencies) be built in C++ 17, right?
```python
settings = ("os", "compiler", "build_type", "arch")
...
compiler.cppstd=17
```

**Comment by memsharded** [comment]
If the code you refer you are putting ``compiler.cppstd=17`` in the ``conanfile.py``, no, that will not work. That needs to go in the profile. If you meant the profile, yes, that information will be propagated to all packages in the graph. A different story is if the recipes are correct and honor the settings, some recipe might fail to do it correctly, or could have the cppstd hardcoded in the build scripts.

**Comment by playgithub** [comment]
OK, tests are in need.
