### ISSUE TITLE
[feature] Enhancements for `msbuild_lib/_exe`

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#11024]
I have a couple of suggestions to be added to `msbuild_lib/_exe` templates:

* Add the toolchain props `conantoolchain.props` to the `*.vcxproj` to be imported automatically.
* It would be nice to be able to select the `PlatformToolset` (now, we're writing `v141` by default).

**Comment by memsharded** [comment]
> It would be nice to be able to select the PlatformToolset (now, we're writing v141 by default).

Yes, make sense. Though the final value for the PlatformToolset should actually be the one defined by the ``conantoolchain.props``. Maybe it is possible to omit it entirely and have it defined by the toolchain only?

> Add the toolchain props conantoolchain.props to the *.vcxproj to be imported automatically.

You mean directly adding the toolchain.props to the .vcxproj directly in the template or having the MSBuild helpers doing a "replace" modifying live the .vcxproj when it runs in the recipe?

**Comment by franramirez688** [comment]
> Yes, make sense. Though the final value for the PlatformToolset should actually be the one defined by the conantoolchain.props. Maybe it is possible to omit it entirely and have it defined by the toolchain only?

I guess the easiest way is to omit it. Another option could be if it's already set in the user profile, could we inject that one?

> You mean directly adding the toolchain.props to the .vcxproj directly in the template or having the MSBuild helpers doing a "replace" modifying live the .vcxproj when it runs in the recipe?

Yeah, I meant directly adding it to the `.vcxproj ` file.

**Comment by memsharded** [comment]
Ok, so good for me:

- the toolset can be omitted if loaded from Conan one, lets try it
- Good, add the toolchain.props to the .vcxproj file directly

**Comment by franramirez688** [comment]
Closed by https://github.com/conan-io/conan/pull/11101
