### ISSUE TITLE
[bug] --require-override does not work for local dev workflow 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#11030]
`--require-override` works when creating conan package, `conan create` but it fail for local development workflow when running `conan install <source_dir>`

### Environment Details
  * Conan version: 1.47.0

### Steps to reproduce
using this conanfile.py
```
class DemoConan(ConanFile):
    name = "demo"
    version = "1.0.0"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    def requirements(self):
        self.requires("openssl/3.0.2")

    def build(self):
        pass

    def package(self):
        pass
```

`conan create . --require-override  openssl/3.0.1` works as expected. However, when running `conan install <source_dir> --require-override  openssl/3.0.1`  I got this error

```
ERROR: conanfile.py (demo/1.0.0): Error in requirements() method, line 45
	self.requires("openssl/3.0.2")
	ConanException: Duplicated requirement openssl/3.0.1 != openssl/3.0.2
```

**Comment by boussaffawalid** [comment]
I tried with this fix https://github.com/conan-io/conan/pull/10046/files and it resolve the issue.

@memsharded  based on https://github.com/conan-io/conan/pull/10046#issuecomment-1066676745, this is replaced by a lockfiles approach for conan 2. 

but what about conan 1. ? we still use conan 1.0 and right now this feature is buggy. Is it possible to include this fix for conan 1. ?

**Comment by memsharded** [comment]
``--require-override`` no longer exist in Conan 2, closing ticket as outdated
