### ISSUE TITLE
[question] How to force upload conan package without the binary package[only upload recipe]?

### ISSUE THREAD

**Issue by initlifeinc** [conan-io/conan#11034]
The background is we have our remote binary file storage service, we don't want to use Artifactory CE to store recipes and binary packages. 
Because it will costs too much Artifactory Ce storage. we just want to let it to manager recipes only.

**So how can i invoke "conan upload ...." command or other commands to upload recipe but not with packages?**
Do you think it is a feature to support? If yes, I maybe try to add an argument to do that.

I find there is a param --skip-upload, but it is a function to skip all uploads to only do the check things.
It seems we should not force upload binaries to conan remote services like Artifactory CE?

**Comment by memsharded** [comment]
Hi @initlifeinc 

If you don't specify the ``--all`` or the ``-p=packageID``, it will only upload the recipe. Are you seeing a different behavior when running ``conan upload`` without the ``--all``?

Also regarding the ``--force``, I guess you are not using revisions yet? If you are using revisions, what is the use case of forcing?

**Comment by initlifeinc** [comment]
@memsharded 
Thanks to reply, I finally find the reason why it still upload binary packages is that i specify `-q` to only upload the corresponding conan recipes(I hope do it but actually it makes conan upload command to upload with packages...) which is just built on CI machine.

I ever thought `-q` is to query all recipes and packages in the first step, only the result after query will be calculated to upload all with packages or only recipes(by `--all`). but it seems `--all` and `-q` are all used to query packages, if `-q` is specify but `--all` is not specify, upload package behavior is still working.

```
# TODO: This search of binary packages has to be improved, more robust
# So only real packages are retrieved
if all_packages or query:
    if all_packages:
        query = None
    # better to do a search, that will retrieve real packages with ConanInfo
    # Not only "package_id" folders that could be empty
    package_layout = self._cache.package_layout(ref.copy_clear_rev())
    packages = search_packages(package_layout, query)
    packages_ids = list(packages.keys())
elif package_id:
    packages_ids = [package_id, ]
else:
    packages_ids = []
```

Thanks again!

**Comment by memsharded** [comment]
Hi @initlifeinc 

Yes, that would explain it. The ``--query`` is a query over binary parameters, selecting package binaries. When the query argument is provided, it will upload those binaries. The behavior that you are copying in code has evolved in Conan 2.0 to:

```python
        if ":" in expression or package_query:
            # We are uploading the selected packages and the recipes belonging to that
            prefs = self.conan_api.search.package_revisions(expression, query=package_query)
            if not prefs:
                raise ConanException("There are no packages matching {}".format(expression))
            ret.add_prefs(prefs)
```
Which means that if the query cannot find any binary, it will raise a hard error, being more explicit about the intent.

Is it clarified now the behavior? Is it working now for you, if you don't add the ``-q``, you will get the expected behavior, right? If so, I think we can close the issue. Thanks!

**Comment by initlifeinc** [comment]
@memsharded Yes, it is working now for me！
