### ISSUE TITLE
Error with cmake_multi

### ISSUE THREAD

**Issue by birsoyo** [conan-io/conan#1103]
While trying to use cmake_multi I am getting the following error.
`PROJECT: 
ERROR: Generator cmake_multi(file:None) failed
__init__() takes exactly 2 arguments (1 given)`

It looks like in cmake_multi.py the CppInfo is constructor is missing a parameter (https://github.com/conan-io/conan/blob/develop/conans/client/generators/cmake_multi.py#L13)

Perhaps it should be `result = CppInfo(config_info.rootpath)`?

**Comment by memsharded** [comment]
Yes, it seems a bug. 
I'd say that it is because you are using both multi-configuration packages (with ``self.cpp_info.debug.libs``) and ``cmake_multi`` generator, and this is a non typical use-case:

- ``cmake_multi`` is intended for end consumers, consuming single-configuration packages. All the packaging approach is single-conf, and just the end-user install both debug/release packages and mix them at build time with this special generator, to be able to switch from the IDE.
- Multi-configuration packages, defined with ``self.cpp_info.<config>`` shouldn't require the ``cmake_multi`` generator, they should work with the normal ``cmake`` one.

We will check to see if we can fix this. Thanks very much for reporting.

**Comment by memsharded** [comment]
Fixed, new tests added. It will be released in next 0.21, can be run from develop branch now.

**Comment by birsoyo** [comment]
I think I didn't do it intentionally. I was also using cmake-conan, it chose cmake_multi generator. Perhaps I did something wrong, I will look into it more. 

I was trying to port complex cmake based project (WebKit) to use conan for its dependencies from my repository instead of their prebuild binary downloads (for windows).

Almost all my dependencies (cairo, libpng, harfbuzz, freetype etc) are multi config conan recipes. 
I am using 
- Visual Studio 2017 x64
- CMake 3.7.2
- WebKit (master)
- cmake_conan (master)
- conan  (0.20.3)
- conan_package_tools (0.2.37)

**Comment by memsharded** [comment]
Yes, you are right, it is the cmake-conan helper that is doing that, automatically, when you are in Win VS, and don't specify a CMAKE_BUILD_TYPE, it will use the cmake-multi generator. You were not doing anything wrong, it was indeed a bug, great that you discovered and reported it :)

I think I would use only ``cmake-multi`` as end-user, if I have to open my VS IDE and develop. For all automated processes, I'd rather go with the ``cmake`` normal generator, and single-config builds.

> Almost all my dependencies (cairo, libpng, harfbuzz, freetype etc) are multi config conan recipes.

I am not sure that we are using the same terms: Multi-config packages are those that package both debug and release artifacts in the same final binary. You might be interested in having a look to: http://blog.conan.io/2017/03/07/Supporting-Different-C-C++-Package-Paradigms-with-conan.html

The packages you are talking about are single-conf, they will have a different final package binary for debug and for release.

We are also re-writing the docs, hopefully it will be more clear. In the meantime, if things are not clear enough, please do not hesitate to ask. 

Thanks very much again! Cheers.

**Comment by birsoyo** [comment]
> I am not sure that we are using the same terms: Multi-config packages are those that package both debug and release artifacts in the same final binary.

I am using my own recipes for those projects that packages debug/release builds into the same (one) package (like lib/freeimage.lib/pdb and lib/freeimaged.lib/pdb etc). I am hoping I understood the concept correctly and this kind of package is called multi-config package :). 

I also have other changes from the conan.io provided recipes like generating pdbs,  link time code generation (/LTCG) for release builds, among other things.

These recipes are done out of curiosity. I wanted to see which build/packaging strategy would work best for me. 

Currently I am leaning towards 'Build once, package many' strategy according to the link you provided.

Thanks.

**Comment by memsharded** [comment]
Ah ok! That is great, I thought you were using packages from conan.io which are usually single-config.
My mistake, you understood it perfectly :) and if you already did such things, then you already have a great grasp of conan. Good job.

**Comment by memsharded** [comment]
This has been released in conan 0.21, please upgrade and report if necessary. Thanks!
