### ISSUE TITLE
[question] using cmake.install() in package() will do another unnecessary compilation

### ISSUE THREAD

**Issue by mohamedAlaaK** [conan-io/conan#11037]
Hello,

Consider this part of conan file

```
def configure_cmake(self):
    cmake = CMake(self)
    cmake.configure()
    return cmake

def build(self):
    cmake = self.configure_cmake()
    cmake.build()

def package(self):
    cmake = self.configure_cmake()
    cmake.install()
```

When we run the conan build command a compilation would be done in the build folder
Then running conan export-pkg would do another compilation because cmake.install() is called with ( i think different sources )

Is there a way to use the existing build folder in the package() method to do cmake.install() ? or do you have another solution to the problem ?

**Comment by mohamedAlaaK** [comment]
I worked around the issue by making the package() method look like this
```
def package(self):
        self.run("cmake --install . --prefix="+self.package_folder)
```
This will install to the package folder without making another compilation. But of course it's not the cleanest solution out there.

**Comment by memsharded** [comment]
Hi @mohamedAlaaK 

Yes, I think all of this has been improved with the modern Conan ``layout()`` and the new integrations ``CMakeToolchain``, ``CMake``, etc. You can try it with the ``conan new hello/0.1 --template=cmake_lib`` template. For example, the new ``from conan.tools.cmake import CMake`` implementation is basicaly the ``cmake --install`` that you are doing.

**Comment by boussaffawalid** [comment]
You need to set this cmake variable 
https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_INSTALL_ALL_DEPENDENCY.html
