### ISSUE TITLE
[bug] settings.compiler == "msvc" compares as enum and crashes

### ISSUE THREAD

**Issue by GregDomjan** [conan-io/conan#11031]
Unclear if here is right place to raise, or maybe it's package error?

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 21H1
  * Compiler+version: VS 2019
  * Conan version: 1.47.0
  * Python version:

### Steps to reproduce (Include if Applicable)

conanfile.txt
```
[requires]
openssl/1.0.2u
[generators]
MSBuildDeps
[options]
openssl:shared=True
```

> 14/04/2022 9:12:32 PM: [Conan.VisualStudio] Calling process 'C:\Program Files\Conan\conan\conan.exe' with arguments 'install C:\Data\foo\conanfile.txt -g visual_studio --install-folder C:\Data\foo\bin\Win32\Release\.conan -s arch=x86 -s build_type=Release -s compiler.toolset=v142 -s compiler.version=16 -s compiler.runtime=MT  --build=missing --update'
14/04/2022 9:12:33 PM: Configuration:
14/04/2022 9:12:33 PM: [settings]
14/04/2022 9:12:33 PM: arch=x86
14/04/2022 9:12:33 PM: arch_build=x86_64
14/04/2022 9:12:33 PM: build_type=Release
14/04/2022 9:12:33 PM: compiler=Visual Studio
14/04/2022 9:12:33 PM: compiler.runtime=MT
14/04/2022 9:12:33 PM: compiler.toolset=v142
14/04/2022 9:12:33 PM: compiler.version=16
14/04/2022 9:12:33 PM: os=Windows
14/04/2022 9:12:33 PM: os_build=Windows

### Logs (Executed commands with output) (Include/Attach if Applicable)

14/04/2022 9:12:48 PM: ERROR: openssl/1.0.2u: Error in build() method, line 775
14/04/2022 9:12:48 PM: 	self._make()
14/04/2022 9:12:48 PM: while calling '_make', line 691
14/04/2022 9:12:48 PM: 	args = " ".join(self._configure_args)
14/04/2022 9:12:48 PM: while calling '_configure_args', line 510
14/04/2022 9:12:48 PM: 	'"%s"' % (self._target if self._full_version >= "1.1.0" else self._ancestor_target),
14/04/2022 9:12:48 PM: while calling '_ancestor_target', line 442
14/04/2022 9:12:48 PM: 	compiler = "Visual Studio" if self.settings.compiler == "msvc" else self.settings.compiler
14/04/2022 9:12:48 PM: 	ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value.
14/04/2022 9:12:48 PM: Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc']
14/04/2022 9:12:48 PM: Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

**Comment by GregDomjan** [comment]
A hack of the openssl conanfile.py to convert enum to string avoids attempt at converting the "msvc" string to enum?
`        compiler = "Visual Studio" if self.settings.compiler.value == "msvc" else self.settings.compiler`

**Comment by memsharded** [comment]
Hi @GregDomjan 

It seems for some reason you are missing the new ``msvc`` compiler in your settings.yml? If that is the case, please remove your ``settings.yml`` file from your cache and let it be regenerated with the new ones.

The ``msvc`` compiler setting was introduced some time ago, as proposed by the Tribe, to replace the ``Visual Studio`` one. Conan 2.0 has already dropped the ``Visual Studio``. For this to happen, it is necessary to transition first to the new build system integrations (ones from ``from conan.tools.cmake, from conan.tools.microsoft, etc``

**Comment by GregDomjan** [comment]
Thanks for the directions @memsharded 
I had installed conan in 2020 to experiment and only started to look again recently, had used the msi upgrade but don't recall the original install type.
Had not noticed that per-user config had a `settings.yml.new` for changes to `settings.yml`

**Comment by memsharded** [comment]
Yes, an installation from 2020 would explain it, thanks for following up!
