### ISSUE TITLE
[bug] is_msvc is not supported by Conan 2.0

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#11045]
The [is_msvc](https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html#conan-tools-microsoft-is-msvc) helps to detect between `Visual Studio` and `msvc` compiler, however, on Conan 2.0, only `msvc` is available, which makes that tool method impossible to be used:

```
ERROR: Invalid setting 'Visual Studio' is not a valid 'settings.compiler' value.
Possible values are ['apple-clang', 'clang', 'gcc', 'intel-cc', 'mcst-lcc', 'msvc', 'qcc', 'sun-cc']
```

As it's a new tool, it could be adapted to work with both Conan 1.x and 2.x. Otherwise, it would be necessary replace all calls to a new condition on recipes, like `if self.settings.os == "Windows" and self.settings.compiler == "msvc"`

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows
  * Compiler+version: Visual Studio/msvc
  * Conan version: 2.0.0a6
  * Python version: 3.7.13

### Steps to reproduce (Include if Applicable)

Build the follow recipe on Windows:

```python
from conan.tools.microsoft import is_msvc
from conan.errors import ConanInvalidConfiguration
from conan import ConanFile

class FooBar(ConanFile):
    def configure(self):
        if not is_msvc(self):
            raise ConanInvalidConfiguration("Only supported by Visual Studio and msvc.")
```

     conan create . --name=foo --version=0.0.1 -pr:h=default -pr:b=default

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: Invalid setting 'Visual Studio' is not a valid 'settings.compiler' value.
Possible values are ['apple-clang', 'clang', 'gcc', 'intel-cc', 'mcst-lcc', 'msvc', 'qcc', 'sun-cc']
```

**Comment by memsharded** [comment]
Have you updated to latest Conan 2.0-alpha? The current implementation is:
```python
return settings.get_safe("compiler") == "msvc"
```
so it shouldn't raise anymore.

**Comment by uilianries** [comment]
Yes, I'm running 2.0.0a6.

Let me check again, because I running both version 1.x and 2.x here.

**Comment by uilianries** [comment]
True, indeed it only checks msvc compiler. It should be a cached version.

The current implementation is listed here: https://github.com/conan-io/conan/blob/develop2/conan/tools/microsoft/visual.py#L187
