### ISSUE TITLE
[question] Will `conan install` command modify the `PATH` environment variable in the current shell?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#11040]
I noticed that there are some messages when running `conan install` command:

```
bzip2/1.0.8: Appending PATH environment variable: C:\.conan\a06b72\1\bin
jbig/20160605: Appending PATH environment variable: C:\.conan\f9c8e3\1\bin
libiconv/1.16: Appending PATH environment var: C:\.conan\1c71d0\1\bin
protobuf/3.17.1: Appending PATH environment variable: C:\.conan\fc2f0b\1\bin
...
```

What is the purpose of these messages? Does it mean that Conan will append those `bin` directory to the `PATH` environment variable in the current shell? But I've tried to use `echo %PATH%` to print it out after installing. It didn't show those directories.

![image](https://user-images.githubusercontent.com/71438617/163795518-464ed0ac-cde6-4e92-a3ab-6a2300a60d13.png)

**Comment by czoido** [comment]
Hi @hwhsu1231,

Those messages do not come from Conan itself but from the Conan recipes in Conan Center, please check: https://github.com/conan-io/conan-center-index/blob/28818cbc07c4b42415a19c310dcac36f7b48f8d7/recipes/bzip2/all/conanfile.py#L123
I guess the intention is just to highlight that those paths will be added to the PATH when consuming those recipes. It will not modify the PATH after the Conan execution but just while consuming those packages. Please check the Conan documentation about adding paths to the environment in Conan recipes in the [Conan documentation](https://docs.conan.io/en/latest/mastering/envvars.html#automatic-environment-variables-inheritance).

An additional comment: the way of handling environment has been improved and now we recommend using the [conan.tools.env](https://docs.conan.io/en/latest/reference/conanfile/tools/env.html) to handle this. Please check the new way of handling the environment for Conan here: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html

**Comment by hwhsu1231** [comment]
@czoido,

I was thinking that we need to find **DLL** files on Windows when adding `xxx:shared=True` option. Although Conan provides **[imports](https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports)** section in `conanfile.txt` or `conanfile.py` to copy those DLL files to where our executables locate, is it possible to use `PATH` to find thoses DLL files without doing this copying action?

**Comment by czoido** [comment]
> @czoido,
> 
> I was thinking that we need to find **DLL** files on Windows when adding `xxx:shared=True` option. Although Conan provides **[imports](https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports)** section in `conanfile.txt` or `conanfile.py` to copy those DLL files to where our executables locate, is it possible to use `PATH` to find thoses DLL files without doing this copying action?

Yes, you could use the VirtualRunEnv generator, to generate scripts that will add those paths to the PATH and after sourcing those generated scripts the system will find the dll's for those libraries, please check the [VirtualRunEnv documentation](https://docs.conan.io/en/latest/reference/conanfile/tools/env/virtualrunenv.html) for more detailed information.

**Comment by memsharded** [comment]
Closing as staled
