### ISSUE TITLE
[bug] Two profile approach on build_requires

### ISSUE THREAD

**Issue by Lyvsain** [conan-io/conan#11044]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04 on WSL 2
  * Compiler+version: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1), --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib
  * Conan version: 1.43.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
Conan profile x86
```
Configuration for profile x86:

[settings]
os=Linux
os_build=Linux
arch=x86
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
```
- Create a project with libtools/1.2.4 as build_requires
- Install the project 
`conan install . -pr x86 --build=missing`

### Logs (Executed commands with output) (Include/Attach if Applicable)
I got an error on building m4 related to 32 bits cross build :
```
../source_subfolder/lib/sigsegv.c:977:28: error: 'struct vma_struct' has no member named 'is_near_this'
  977 |                       : vma.is_near_this (addr, &vma))
      |                            ^
```
The configure line of m4 launch by conan is as follow : 
` > source_subfolder/configure '--prefix=/home/dev/.conan/data/m4/1.4.19/_/_/package/6173abd988ee2e3159da6cce836868055fdb1cb4' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' --build=x86_64-linux-gnu --host=x86-linux-gnu`
I cloned m4 and tried to do execute the command manually, same error. I've been digging a little and it's seems that the configure cannont find the stack direction wich set the  STACK_DIRECTION=0 and therefore the function `is_near_this` is not defined. 
``` 
configure:46360: checking for stack direction
configure:46455: result: unknown
```

Did i set up everything right to cross build from GCC x86_64 to x86 ?

**Comment by memsharded** [comment]
Hi @Lyvsain 

I'd recommend using the 2 profiles approach, like ``conan install --profile:build=mygccx86_64 --profile:host=mygcc86``. 
Said that, this might be a recipe issue, in that case we want to move it to conan-center-index repo.

**Comment by Lyvsain** [comment]
Hi @memsharded !

You recommandation seems to works, everything was able to build in 32bits on my environement but today I got something weird about build_requires. My project needs GoogleTest for unit testing so I made it as a build_requirement : 
``` 
[requires]

[build_requires]
gtest/1.10.0

[generators]
cmake_find_package
``` 

If I run the install in 64bits, everything fine : 
```
$ conan install -pr default .
Configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
Packages
Build requirements
    gtest/1.10.0 from 'conancenter' - Cache
Build requirements packages
    gtest/1.10.0:7320405f83ec32d8556b524cdda87ee295bb7b84 - Cache

Installing (downloading, building) binaries...
gtest/1.10.0: Already installed!
conanfile.txt: Applying build-requirement: gtest/1.10.0
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator cmake_find_package created FindGTest.cmake
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
```
But then, when following your recommendation to use the two profiles approach, it does not generate the FindGTest.cmake with the same recipe : 
```
$ conan install -pr:b default -pr:h x86 .
Configuration (profile_host):
[settings]
arch=x86
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
Packages
Build requirements
    gtest/1.10.0 from 'conancenter' - Cache
Build requirements packages
    gtest/1.10.0:7320405f83ec32d8556b524cdda87ee295bb7b84 - Cache

Cross-build from 'Linux:x86_64' to 'Linux:x86'
Installing (downloading, building) binaries...
gtest/1.10.0: Already installed!
conanfile.txt: Applying build-requirement: gtest/1.10.0
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
```

What am I missing there ?

**Comment by memsharded** [comment]
Hi @Lyvsain 

Yes, this is because a test framework, under the 2 profiles approach, shouldn't be a ``build_require``. We have renamed them to ``tool_requires`` in latest versions, to illustrate that those requirements are mostly for executable tools, like ``cmake``, or a compiler. But ``gtest`` or a testing library, is basically a regular library that should live in the "host" context to be able to link correctly, not in the "build" context. ``build_requires`` live in the "build" context. So the correct context "host" can be achieve by putting gtest as regular ``requires``.

For a ``conanfile.txt`` is not a big issue, because it is a consumer only. For a package ``conanfile.py``, you can now model it explicitly as ``self.test_requires("gtest....")`` inside ``build_requirements()`` method.

Please let me know if this helps.

**Comment by Lyvsain** [comment]
@memsharded thinking about it; it does make sense !

I still have some issues with other packages but i'll open then in conan-cener-index :)

Thanks !
