### ISSUE TITLE
[bug] conan ignores HOME env var -> uses %userprofile% on windows

### ISSUE THREAD

**Issue by cr-dani-koretsky** [conan-io/conan#11047]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 20H2 build 19042.1586
  * Compiler+version: Visual studio 2017 (not relevant for the bug)
  * Conan version: 1.44.1
  * Python version: 3.10.1

### Steps to reproduce (Include if Applicable)

1. Set env var HOME to some arbitrary path like 'C:\\MyName\\home'
2. Execute a conan install command
3. Command succeeds -> but instead of installing in 'C:\\MyName\\home' it seems to install in %userprofile%..
4. I even double checked that python `import os; os.environ.get("HOME")` returns the right path..

Shouldn't CONAN_USER_HOME default to HOME when not set, before falling back to %userprofile% or some other default?

**Comment by memsharded** [comment]
Hi @cr-dani-koretsky 

The HOME variable is not defined in Windows, the default is to use ``%userprofile%``: https://superuser.com/questions/607105/is-the-home-environment-variable-normally-set-in-windows

So this doesn't seem a bug, but working fine, as designed.
