### ISSUE TITLE
[bug] Support complex strings as definitions in CMakeToolchain

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#11043]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

As per https://github.com/conan-io/conan/issues/10929, CMake now requires `add_compile_definitions()` instead of `add_definitions()` but Conan still does not support correct formatting of the definition construction when strings are complex and contain spaces and/or escaped string quotes `\"`.

The jinja template needs updating to check if the `value` of the item that is set via `CMakeToolchain.preprocessor_definitions[key] = value` is complex and adapt the resulting string that is sent to CMake's `add_compile_definitions()` accordingly.

I am currently working around this via an updated jinja template for CMakeToolchian to remove the wrapped string quotes and wrap the whole definition as a string to be able to have my value correctly interpreted.
_(note: example shown only for plain non-config/generator expressions versions of the preprep definitions)_

``` python
cmaketoolchain = CMakeToolchain(self)
# for Conan < 1.48.0
cmaketoolchain._template = cmaketoolchain._template.replace("add_definitions(-D{{ it }}={{ value }})", "add_compile_definitions(\"{{ it }}={{ value[1:-1] }}\")")
# for Conan >= 1.48.0
cmaketoolchain._template = cmaketoolchain._template.replace("add_definitions({{ it }}={{ value }})", "add_compile_definitions(\"{{ it }}={{ value[1:-1] }}\")")
```

To be able to use it as follows:
```
api_def_value = "extern \\\"C\\\""
cmaketoolchain.preprocessor_definitions["MY_API"] = api_def_value
```

That creates correct definition on (osx) clang compiler:
```
c++ -DMY_API="extern \"C\""  ....
```

**Comment by SeanSnyders** [comment]
A better approach to my workaround would be to create my own extension Block in the CMakeToolchain, but this support should probably be a native support by Conan.
Can this be viewed as a bug especially due to the `Variables.quote_preprocessor_strings()` method in Conan?

**Comment by SeanSnyders** [comment]
Please test with:
```
cmaketoolchain.preprocessor_definitions["escape"] = "partially \\\"escaped\\\""
cmaketoolchain.preprocessor_definitions["spaces"] = "me you"
cmaketoolchain.preprocessor_definitions["foobar"] = "bazbuz"
cmaketoolchain.preprocessor_definitions["answer"] = 42
```

Using current implementation from https://github.com/conan-io/conan/issues/10929 (slated to be released as part of Conan 1.48.0 and which uses CMake `add_compile_definitions()`), it gives with `apple_clang` and CMake 3.19.4:
```
-Danswer=42 -Descape="\"partially \"escaped\"\"" -Dfoobar=\"bazbuz\" -Dspaces="\"me you\""
```
which results in error:
```
<command line>:6:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier
      [-Wreserved-user-defined-literal]
#define escape "partially "escaped""
```

The Conan `Variables.quote_preprocessor_strings()` code from https://github.com/franramirez688/conan/blob/874a853f881c523f5383171d91f5b8dc2c21e073/conan/tools/cmake/toolchain/toolchain.py#L45 
wraps string values in `"` but this is already handled by CMake itself (https://cmake.org/cmake/help/latest/command/add_compile_definitions.html):
`CMake will automatically escape the value correctly for the native build system (note that CMake language syntax may require escapes to specify some values).`

and thus results in double quotation and thus escaping of the `"` on CMake's side when generating actual platform-specific build commands.

If I extend `CMakeToolchain` by adding my own block:
```
class ComplexStringPreprocessorDefinitionBlock:
    template = textwrap.dedent("""
        # Preprocessor definitions for complex string values
        {% for it, value in preprocessor_definitions.items() %}
        add_compile_definitions(\"{{ it }}={{ value }}\")
        {% endfor %}                
        """)

    preprocessor_definitions = OrderedDict()

    def context(self):
        return {"preprocessor_definitions": self.preprocessor_definitions}

cmaketoolchain.blocks["complex_string_preproc_defs"] = ComplexStringPreprocessorDefinitionBlock
```
and use that to add the same test values as above
```
  cmaketoolchain.blocks["complex_string_preproc_defs"].preprocessor_definitions["complex_escaped"] = "partially \\\"escaped\\\""
  cmaketoolchain.blocks["complex_string_preproc_defs"].preprocessor_definitions["complex_spaces"] = "me you"
  cmaketoolchain.blocks["complex_string_preproc_defs"].preprocessor_definitions["complex_foobar"] = "bazbuz"
  cmaketoolchain.blocks["complex_string_preproc_defs"].preprocessor_definitions["complex_answer"] = 42
```
it gives with `apple_clang` and CMake 3.19.4:
```
-Dcomplex_answer=42 -Dcomplex_escaped="partially \"escaped\"" -Dcomplex_foobar=bazbuz -Dcomplex_spaces="me you"
```
which compiles fine, and as can be seen, CMake wraps the string values appropriately where required.

**Please update this issue from a FEATURE to a BUG report.**

**Comment by lasote** [comment]
Related https://github.com/conan-io/conan/pull/11039

**Comment by SeanSnyders** [comment]
Also probably have to look into how `ConanFile.cpp_info.defines` handles the situation and support complex strings there as well.

**Comment by czoido** [comment]
Hi @SeanSnyders,
I have [opened a PR](https://github.com/conan-io/conan/pull/11057) that I think solves the issue with this, can you please check if that solves your issue?
