### ISSUE TITLE
canon website not available for developer in Iran ! 

### ISSUE THREAD

**Issue by Maziar123** [conan-io/conan#11068]
I am single developer in Iran

I don't under stand why opensource tools such as canon **not available for everyone**  in Iran

I think this is [**"Modern racism"** ](https://pearnkandola.com/diversity-and-inclusion-hub/bias/what-is-modern-racism)

**Comment by lasote** [comment]
Hi @Maziar123!

We didn't know, this is the first time it is reported, never happened in any country before.
**Everybody** is very welcome here. Let's investigate what is going on with the infrastructure team and will report as soon I have an answer.

**Comment by memsharded** [comment]
But lets make sure what are all the possible blockers here:

- Can you install Conan with ``pip install conan``? At least you can run Conan from source, as you have access to github?
- What sites can't you see? All of them? conan.io? Can you see docs.conan.io? Can you see blog.conan.io?
- Does ``conan install`` can fetch packages from the default conancenter remote?

**Comment by Maziar123** [comment]
https://conan.io/
Error: Forbidden
Your client does not have permission to get URL / from this server.

the site only can open with vpn in Iran !

the https://docs.conan.io can open successfully

**Comment by lasote** [comment]
The JFrog team reported that there is nothing on our side blocking any country. But they pointed out that there might be blocks to some countries from some of the cloud providers. We are really sorry but I'm not sure if we can do something about that.

**Comment by Maziar123** [comment]
Then You choose bad cloud ....

**Comment by Maziar123** [comment]
> The JFrog team reported that there is nothing on our side blocking any country. But they pointed out that there might be blocks to some countries from some of the cloud providers. We are really sorry but I'm not sure if we can do something about that.

accessing global site for usual people is not forbidden in **ANY LAW** . and this blocking Forbidden in over two command of national united law ...

then you choose cloud with modern racism orientation

sorry But if you don't change it have same thing as any racist ...
