### ISSUE TITLE
[question] Conan Search fails with error "invalid version number: '1'"

### ISSUE THREAD

**Issue by NightWulfe** [conan-io/conan#11064]
Running `conan search` is fails with error "Invalid version number: '1'". I think this may be related to #10473?

If there's some configuration option I'm missing, I apologize. Conan is still pretty new to me. My conan.conf file is the default except for `storage.path` (See below).

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 11 (21H2, OS Build 22000.613)
  * Compiler+version: VS 2022 (Compiler version 17.1.4)
  * Conan version: 1.47.0
  * Python version: ?

### Steps to reproduce (Include if Applicable)

  * Install Conan 1.47.0
  * Alter the conan `storage.path` configuration to `E:/.conan` in ~/conan.conf
  * Run `conan install . --build missing --profile ./x86-debug` in my project directory (conanfile.txt and x86-debug profile below)
  * Run `conan search`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
D:/temp/repro>  conan search
ERROR: Package 2772c8 has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
```

My conanfile.txt:
```
[requires]
boost/1.78.0

[generators]
visual_studio

[options]
boost:shared=False
```

My x86-debug profile:
```
[settings]
os=Windows
compiler=Visual Studio
compiler.version=17
arch=x86
build_type=Debug
compiler.runtime=MDd

[options]

[build_requires]

[env]
```

**Comment by memsharded** [comment]
Hi @NightWulfe 

Yes, this is likely a misconfiguration because of the ``short_paths`` feature, and using the storage path in the same location that ``short_paths`` will store its packages. To solve it, clean your caches and configure it:

- Remove the E:\.conan and possible C:\.conan folders
- Remove the userhome/.conan folder
- Set the storage.path to other folder rather than X:\.conan
- Try again

In general it is better to leave the storage.path per user, as different users in the same machine can have different packages, different permissions to access packages, etc. Also, the cache is not designed for concurrency, so each user and process should have its own cache.

Please let me know how it goes.

**Comment by NightWulfe** [comment]
Thank you, @memsharded. You pointed me in the right direction. I misunderstood the documentation for `user_home_short`. Is "current drive letter", in the documentation for `user_home_short`, selected when I run `conan install`, or is it selected from the `storage.path` configuration option?

Regardless, I set `user_home_short` to `None` to disable short paths entirely. If this becomes a problem I can select another more appropriate path. 

I moved the path because I don't have enough space on my primary drive where my profile data is stored. I'm not concerned with per-user profiles on this machine as it's not shared with any other developers, but I'll keep your points in mind if that situation ever comes up.

Thanks again!

**Comment by memsharded** [comment]
> Regardless, I set user_home_short to None to disable short paths entirely. If this becomes a problem I can select another more appropriate path.

Sure, this is fine, as long as some recipe or library doesn't really need a shortened path, in that case it could fail.

> I moved the path because I don't have enough space on my primary drive where my profile data is stored. I'm not concerned with per-user profiles on this machine as it's not shared with any other developers, but I'll keep your points in mind if that situation ever comes up.

Yes, that is one of the common reasons to change the storage.

Good news is that Conan 2.0 has simplified things, removing the "short_paths" feature completely, so the whole cache will be located in CONAN_HOME, and this "invalid version number: 1" will stop happening. Maybe we can close this issue as a question? Thanks!

**Comment by NightWulfe** [comment]
Works for me, thank you.
