### ISSUE TITLE
[feature] 3rd party library lifecycle walkthrough ... aka editable mode for boost CCI

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#11069]
Hi,

I'm sending this here as I assume it would require changes to conan's core or documentation.

The CCI recipe for boost will not work in editable mode without some manual changes, AND you are forced to set the -pf package folder to ".".

This is because boost recipe's "def package_info(self)" uses tools.collect_libs() which only searches the "package folder".
But, consumers of the editable package cannot seem to use any other package folder EXCEPT the base folder of the package.

I would've thought conan editable add ... -of FOLDER would've allowed you to use FOLDER as the package folder... or something like that.
But I could not find some method of changing what boost-recipe saw as the package folder when in 'editable' mode.

I've been fighting with conan for ages on this.
I feel like I am fighting against the grain of the design, but I have yet to see a youtube or blog post or documentation that details how conan users go through the process of using a 3rd party library that is buggy and requires work.
Especially a library that has a non-cmake and/or a non-trivial recipe.

Proper walk-throughs would be awesome if put in the CCI alongside the recipes, if each library needs a different approach.
If each library can be done the same way, then surely we can automate it in some fashion?

Something like (may be inaccurate, I think I got most of it):
- build your program with standard provided CCI library
- discover some problem with library, switch to using git version of library (perhaps a branch, or someone's fork from github).  Compile it using existing CCI conan recipe (hacked/adjusted if required).
  - clone the upstream library
  - copy-paste ALL of the recipe files into the cloned repo
  - edit conanfile.py
    - change "source_subfolder" to "" (as the source will be alongside the recipe)
    - apply current CCI patches
      - Can be done via conan:
      - Comment out the get-source part of source(self), leave the patch lines.
      - Edit conandata.py and remove "source_subfolder" from the patch entries.
      - Run conan install . lib/version@ -bf build -if build ;; conan source . -if build
    - Comment out all of source(self) function (and add 'pass' line)
    - Comment out the patches line in export_sources(self)
    - (for conan create to work - needed later) Add self.copy(stuff) for all of the sources that is required to build the library.
  - conan install . library/version@user/channel -if build-whatever -o lib:option=whatever -pr=profile
  - conan build . -bf build-whatever -pf .
    - Note that "-pf ." is very important for editable packages - my complaint above - and be aware that the generated 'package files' will be polluting the source files!  Hope that you have no overlapping folders!  I was lucky with boost.
  - conan editable add . library/version@user/channel
- NOW you can consume this library.  Be sure to use the same lib:option=whatever options in your consumer, and the same @user/channel.
- Once all done, commit your changes and push upstream.  You will have to avoid committing the CCI patches and other pollution that was added in the source tree.   Alternatively, you can capture changes in a patch and send to CCI.  Not sure what the easiest way would be to do this.
- Now the long road of maintaining your fork until patches are accepted upstream...
- Disable editable, and use "conan create" to build and publish the library to your cache.  Use "conan upload" to send to your artifactory / conan_server.
- IF maintaining a git fork: watch CCI and upstream for future changes.  Fold into your fork.
- IF maintaining extra patches: watch CCI for changes to recipe and fold those changes in.
- HOW to watch is unclear.  Folding in is unclear.

Those are my thoughts as a new conan user.
What do experienced conans actually do?

I know what to do when following a git branch and manually building, but conan CCI is adding another layer of complexity due to the additional patches and the not-well-supported (IMHO) editable mode for CCI packages.

I see huge potential for conan, but this is a thorny issue I'd love to see improved on... or at least talked about with some complex examples!
boost and QT are huge packages, and I need to be able to edit, rebuild (quickly), iterate and distribute to co-programmers efficiently.  I can't be the only one wondering how this is done in a conan-world...

**Comment by memsharded** [comment]
Hi @paulharris 

I think the Conan features are already there to greatly improve the editable experience. Basically the new integrations, together with ``generate()`` and specially ``layout()``. You can see them:

- In the docs: https://docs.conan.io/en/latest/developing_packages/editable_packages.html. Note this section is new.
- In a live demo in Meetup: https://youtu.be/VzUJQw89U7o?t=2517. Note this is using almost standard ``conan new hello/0.1 --template=cmake_lib`` recipes.

It is true that ConanCenter hasn't still upgrade to this modern features, but it will mostly have to to be able to upgrade to Conan 2.0, which is already in alpha. So eventually, the whole editable experience will improve also for ConanCenter recipes.

I would suggest to try these new features, with basic examples, give feedback to make sure things work robustly for the more complex cases too, and lets keep building from there.

**Comment by paulharris** [comment]
I'll wait to see it working after the upgrades for 2.0 :)
