### ISSUE TITLE
[question] search / install package for any revisions matching my config

### ISSUE THREAD

**Issue by vdsbenoit** [conan-io/conan#11071]
# Short question
Is there a way to perform a `conan search` or `conan install` that would go through all the revisions until it finds a revision where binaries were pre-built for the requested configuration ?

# Context
We started using revisions recently. Previously, when people had some CRLF in their sources files, it would make outdated packages as [explained here in the documentation](https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine) as soon as they make conan packages for both Linux & Windows. It was relatively okay to detect it and to fix it. 

However, now we started using revisions, when people face this situation, and they only find half of the package they have just uploaded (i.e. for one OS only) when they perform a `conan search` or `conan install`. The root cause of this issue is quite hard to to detect IMO. It is possible to find out what is going wrong with `conan search <ref> --revisions` and then  `conan search <ref>#rev --table=table.html`  but it is not straightforward at all.

# Proposed solution
Would it be possible for the conan resolver to go through all the revisions until it finds a revision where binaries were pre-built for the requested configuration (settings/options) ? For instance : 
````bash
conan search foo/0.1@user/stable --all-revs --profile linux-gcc7
````

# Added value
That would fix the issue described here above, but that would also fix all the other use cases were partial builds are performed after a minor `conanfile` update (e.g. support a new configuration).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
Hi! Sorry that we didn't get back to you on a timely fashion - This is not something that was feasible to support in Conan 1, but good news, a few releases ago, Conan 2 launched the `--filter` syntax for `conan list`, which allows for exactly this!

For example, this query would show every revision with zlib binaries that build with `shared=True`

`conan list "zlib/1.3.1#*:*" --filter-options="shared=True" -r=conancenter` ([Docs here](https://docs.conan.io/2/reference/commands/list.html#filtering-packages)) Then you can mix this feature with the [pkglist feature](https://docs.conan.io/2/examples/commands/pkglists.html) to act on the resulting binaries :)
