### ISSUE TITLE
[question] "private" package options?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11075]
Hi,

As defined in https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html, there is a known bug for
semver_direct_mode, that generating a package ID for a given package includes all of the options of all of its dependendencies.

Is there a way to "hijack" this? Meaning can I define somehow "private" (""build_requires"") package options that are not relevant
for the consumer? Or do I have to manually overrule the package ID all the time and patch out the effect of "known-bug" by hand?
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

No, I think there is no workaround. You can do a``self.info.options.pop("mydep")`` in the ``package_id()`` method of the consumer to be independent of the dependency ``mydep`` options completely, but yes, you need to modify the recipe.

Conan 2.0 already removed this behavior, options of dependencies are not part of the ``package_id`` of consumers

**Comment by harsszegi** [comment]
Understood, thanks a lot @memsharded, closing it.
