### ISSUE TITLE
[bug] Bazel generator picked up the wrong lib file for cyrus-sasl/2.1.27

### ISSUE THREAD

**Issue by czrocklee** [conan-io/conan#11081]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: g++11.1
  * Conan version: 1.47.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
`conan install cyrus-sasl/2.1.27@ -g BazelDeps`

from generated file `cyrus-sasl/BUILD`, it imported a wrong static target `lib/sasl2` instead of `lib/libsasl2.a`

> cc_import(
>     name = "sasl2_precompiled",
>     static_library = "lib/sasl2"
> )

### Logs (Executed commands with output) (Include/Attach if Applicable)

I suppose the culprit is coming from the particular layout for the cyrus sasl lib folder:

```
/root/.conan/data/cyrus-sasl/2.1.27/_/_/package/0a740ecae2955fd815c6f6030b83c788d6d066a4/lib
├── libsasl2.a
└── sasl2
    ├── libanonymous.a
    ├── libcrammd5.a
    ├── libdigestmd5.a
    ├── libotp.a
    ├── libplain.a
    └── libscram.a
```
The `sasl2` subfolder(contains all the plugins for various authentication mechanisms) happends to share the same name with the lib which is chosen according to [here](https://github.com/conan-io/conan/blob/develop/conan/tools/google/bazeldeps.py#L167). Hornestly I don't know the best way to handle those generated plugins (may need to update the recipe) but for the generator, simply filtering out the dirs inside the loop may help IMHO.

**Comment by memsharded** [comment]
Submitted a fix in https://github.com/conan-io/conan/pull/11090, thanks for reporting! Targeted for next 1.48
