### ISSUE TITLE
[bug] CMakePresets.json contains binaryDir set to null

### ISSUE THREAD

**Issue by chausner** [conan-io/conan#11084]
When using the new `CMakePresets.json` output generated by CMakeToolchain, the attribute `binaryDir` is set to `null` which is invalid according to the official [CMakePresets schema](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#schema). Also, when I try to load the CMakePresets.json with the CMake Tools extension of VS Code, it fails due to that line.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 11
  * Compiler+version: MSVC 17.1.4
  * Conan version: 1.47
  * Python version: 3.9.6

### Steps to reproduce (Include if Applicable)
Run:
```shell
conan install soxr/0.1.3@ --generator CMakeDeps --generator CMakeToolchain --build=missing
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
The following `CMakePresets.json` is generated:
```json
{
    "version": 3,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 15,
        "patch": 0
    },
    "configurePresets": [
        {
            "name": "default",
            "displayName": "Default Config",
            "description": "Default configure using 'Visual Studio 17 2022' generator",
            "generator": "Visual Studio 17 2022",
            "cacheVariables": {},
            "toolchainFile": "[...]\\conan_toolchain.cmake",
            "binaryDir": null
        }
    ],
    "buildPresets": [
        {
            "name": "default",
            "configurePreset": "default"
        }
    ],
    "testPresets": [
        {
            "name": "default",
            "configurePreset": "default"
        }
    ]
}
```

/cc @lasote

**Comment by lasote** [comment]
Thanks for reporting. I'll take a look for next release.

**Comment by lasote** [comment]
I investigated a bit: The `binaryDir` is null during a `conan install <reference>` because it is read from the `conanfile.build_folder` and it is not available in that case (as we are not building any package). I see that the `binaryDir` is optional so I'm going to skip setting it when the value is `null`.
