### ISSUE TITLE
[bug] Generated CMakePresets.json does not set build configuration

### ISSUE THREAD

**Issue by chausner** [conan-io/conan#11085]
The generated `CMakePresets.json` does not work out-of-the-box with the CMake Tools extension of VS Code.
It does not specify the build configuration which, according to the CMakePresets.json is optional, but VS Code seems to require it.
If it is not specified, it assumes the build configuration to be "Debug" which leads to build errors when `conan install` was previously called with `-s build_type=Release`.

I am not sure if the problem lies on the Conan side or the CMake Tools extension.
If it is something that needs to be improved or fixed in VS Code, I can also report it to them.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 11
  * Compiler+version: MSVC 17.1.4
  * Conan version: 1.47
  * Python version: 3.9.6

### Steps to reproduce (Include if Applicable)
1. Run:
   ```shell
   conan install soxr/0.1.3@ --generator CMakeDeps --generator CMakeToolchain --build=missing
   ```
2. Remove "binaryDir: null` from the generated `CMakePresets.json` to workaround #11084 
3. Add a dummy `CMakeLists.txt`:
   ```cmake
   cmake_minimum_required(VERSION 3.22)
   project(soxrtest CXX)

   find_package(soxr)
   add_executable(soxrtest soxrtest.cpp)
   target_link_libraries(soxrtest PRIVATE soxr::core)
   ```
4. Add a dummy `soxrtest.cpp`:
   ```cpp
   #include <soxr.h>

   int main() {
       return 0;
   }
   ```
5. Open folder in VS Code with the CMake Tools extension installed
6. Attempt to build the CMake target. It will fail (`soxr.h` not found) and a warning is displayed.

### Logs (Executed commands with output) (Include/Attach if Applicable)
The CMake Tools extension fails to compile and prints the following warning:
```
[cpptools] The build configurations generated do not contain the active build configuration. Using "Debug" for CMAKE_BUILD_TYPE instead of "null" to ensure that IntelliSense configurations can be found
```

### Workarounds

I have found the following two workarounds:
- Running `conan install` with `-s build_type=Debug` makes the compilation succeed, the warning remains, though.
- Adding `"configuration": "Release"` to `CMakePresets.json` fixes compilation and makes the warning disappear:
  ```json
      "buildPresets": [
        {
            "name": "default",
            "configurePreset": "default",
            "configuration": "Release"
        }
    ],
  ```

Maybe the CMakeToolchain generator could detect which build types have been installed via `conan install` and generate appropriate build presets in `CMakePresets.json` with the `configuration` attribute set?

/cc @lasote

**Comment by lasote** [comment]
Not sure about this one. In this case, as `msvc` is `multiconfig` you could run the `conan install` for `debug` and `release` configurations and conan will manage to keep the cmake target with both installed configurations:

```
conan install soxr/0.1.3@ --generator CMakeDeps --generator CMakeToolchain --build=missing
conan install soxr/0.1.3@ --generator CMakeDeps --generator CMakeToolchain --build=missing -s build_type=Debug
```

So, the configuration in a `multiconfig` build system like the `msvc` one,  is something you typically select in the IDE, it doesn't make much sense to set it to something in a `conan install` because you will "break" the multi-configuration behavior. We could set it to the latest executed `conan install` but feels weird. I didn't try the visual studio code extension in windows but it should have a "button" or something to select the configuration, you just need to install both with Conan and enjoy ;)

**Comment by chausner** [comment]
> So, the configuration in a multiconfig build system like the msvc one, is something you typically select in the IDE, it doesn't make much sense to set it to something in a conan install because you will "break" the multi-configuration behavior.

I think this might be a limitation of VS Code then. It does not find an explicit `configuration` in `CMakePresets.json` and thus simply assumes it's a Debug build. There is a way to switch between multiconfigs but it only offers the "default" build preset that Conan writes into `CMakePresets.json`. There does not seem to be a way to explicitly tell it that it's Debug or Release.

> We could set it to the latest executed conan install but feels weird.

What I meant is, running the first `conan install` with `-s build_type=Release` could maybe generate
```json
"buildPresets": [
      {
          "name": "Release",
          "configurePreset": "default",
          "configuration": "Release"
      }
  ],
```
Then, when additionally running `conan install` with `-s build_type=Debug`, it would add another build preset to the existing file, so that it contains:
```json
"buildPresets": [
      {
          "name": "Release",
          "configurePreset": "default",
          "configuration": "Release"
      },
      {
          "name": "Debug",
          "configurePreset": "default",
          "configuration": "Debug"
      },
  ],
```

This would allow VS Code to correctly recognize that there are two build configs. Does that make any sense?

**Comment by lasote** [comment]
> Does that make any sense?

Yes it does. Let me do some test.
