### ISSUE TITLE
[question] Can conan get requirements from remote without downloading the pacakge?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#11086]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, instead of doing ``conan install`` command, you can use the ``conan info`` command, that constructs the dependency graph, but it will not fetch the binary packages.
