### ISSUE TITLE
[feature] tool `check_max_cppstd`

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#11080]
there is already a tool [check_min_cppstd](https://docs.conan.io/en/latest/reference/tools.html?highlight=check_min_cppstd#tools-check-min-cppstd). we may also need going forward similar tool `check_max_cppstd`. many old libraries are not compatible with modern C++ standard (e.g. due to usage of things like `auto_ptr`, `bind2nd`, etc.).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Seems a valid request. As a new feature, I'd recommend targeting it directly to ``develop2`` branch, for 2.0

**Comment by MathPlayer** [comment]
I created the PR(s) to add the max tools.
It gets a bit tricky with the docs since the existing example for the min tool is based on libfmt, which does not really have a problem with the latest standards.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/11610, will be in beta.2
