### ISSUE TITLE
[question] Can I create package with cmake generator?

### ISSUE THREAD

**Issue by Kidsunbo** [conan-io/conan#11089]
Hi, I create a library with `conan new demo/0.1 --template=cmake_lib` and I alse use the `conanfile.py` to consume other library when developing. I am used to using `conanfile.txt` but it seems that `conanfile.py` can have the same functionality when developing a library.

In the `CMakeLists.txt`, I use `CONAN_LIBS` so `generators="cmake"` and `requires="boost/1.78.0"` is added to `conanfile.py`. But when I type `conan create . demo/mine`, there is an error occured.

```
ERROR: kieserver-redis/0.1.0: Error in build() method, line 41
        cmake = CMake(self)
        ConanException: Usage of toolchain is only supported with 'cmake_find_package' or 'cmake_find_package_multi' generators
```

I can walk around it in the following steps:

1. delete layout(self) and generate(self)
2. delete `from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout` and add `from conans import CMake`.

Then everything works fine.

I have thought that `layout(self)` and `conan.tools.cmake` are newer feature of conan. So how could I use them if I want to create a library and use `conanfile.py` with generators `cmake` at the same time?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Kidsunbo 

> In the CMakeLists.txt, I use CONAN_LIBS so generators="cmake"

No, you cannot use this generator together with the modern ones (``CMakeDeps``, ``CMakeToolchain``), which are the ones used by the template you are using, and will be the ones that continue in 2.0. ``cmake`` generator has been removed in Conan 2.0 already, you shouldn't use ``from conans import CMake`` with the other imports.

You need to move to the new native ``find_package(mypkg ...)`` in your CMakeLists.txt, instead of using CONAN_LIBS, making the CMakeLists.txt Conan-agnostic. Have a look inside the ``test_package`` folder to see how it is used.

**Comment by Kidsunbo** [comment]
> 

Thanks @memsharded , what a pity CONAN_LIBS will be removed. I like this one. Why not keep this?

**Comment by memsharded** [comment]
> Thanks @memsharded , what a pity CONAN_LIBS will be removed. I like this one. Why not keep this?

Because the majority of users pushed for a "native" modern CMake integration using ``find_package()`` and CMake targets instead of old-style variables. And it makes sense to maintain 1 way to do things, doing the same thing in different ways is confusing, a maintenance burden, etc.

**Comment by Kidsunbo** [comment]
> > Thanks @memsharded , what a pity CONAN_LIBS will be removed. I like this one. Why not keep this?
> 
> Because the majority of users pushed for a "native" modern CMake integration using `find_package()` and CMake targets instead of old-style variables. And it makes sense to maintain 1 way to do things, doing the same thing in different ways is confusing, a maintenance burden, etc.

Yeah that makes sense. So for the same reason I cannot use `[generators] cmake` in `conanfile.txt` as well in 2.0, am I right?

**Comment by Kidsunbo** [comment]
OK, I find the document of 2.0. Thanks.
