### ISSUE TITLE
[question] How do you integrate a conan subproject?

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan#11099]
Say that I have a small project A that handles its own dependencies through conan. This project is not released under any packaging tool it's a local library for internal use.

Say a new project B is started that depends on A, obviously B transitively depends on anything A depends on. When doing conan install, how can I configure conan to transitively install all dependencies of A so that B can compile?

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> Say a new project B is started that depends on A, obviously B transitively depends on anything A depends on. When doing conan install, how can I configure conan to transitively install all dependencies of A so that B can compile?

But this mean that you want to depend on "project A"?. If you want to depend on it, you have to create a package for it, so you can do a ``requires = "project_a/version"`` and get its transitive dependencies? Depending on a package without creating a package is not possible. You might work in parallel with ``editables`` in both ``project A`` and ``project B``, but you still need a ``conanfile.py`` recipe in ``project A``, define it as a package with ``conan editable`` command, etc.

**Comment by Makogan** [comment]
Ok so I have to export B as a package through conan essentially. Thank you.

**Comment by memsharded** [comment]
> Ok so I have to export B as a package through conan essentially. Thank you.

You can avoid the ``conan export`` or ``conan create`` altogether, by using ``conan editable``. But yes, a more detailed ``conanfile.py`` is necessary for this to work, the basic ``conanfile.txt`` will not be enough. You can have a look to https://docs.conan.io/en/latest/developing_packages/editable_packages.html for a tutorial on the feature.
