### ISSUE TITLE
[bug] Missing CMAKE_SYSROOT in CMakeToolchain generated file conan_toolchain.cmake

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#11093]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: clang-13
  * Conan version: 1.44.1
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
We have a sysroot package which sets `self.cpp_info.sysroot=<val>`.
When running `conan install . -g CMakeToolchain` the resulting `conan_toolchain.cmake` does not contain the value for `CMAKE_SYSROOT`. During the build it was specified correctly via `-DCMAKE_SYSROOT=<val>`.

The `CMAKE_SYSROOT` should be set via the `CMAKE_TOOLCHAIN_FILE`, so it is a bug that it is missing inside the toolchain file generated by conan.

**Comment by memsharded** [comment]
Yes, I can confirm the new integration doesn't implement yet the management of sysroot.
This should be added. Not sure what is the best approach, in theory the information about dependencies comes from ``CMakeDeps``, but now they follow the ``find_package()`` native integration, I agree that probably it fits more naturally in the ``CMakeToolchain``.

**Comment by memsharded** [comment]
Implemented with a ``conf`` in https://github.com/conan-io/conan/pull/11317, already merged, will be in 1.49.
