### ISSUE TITLE
[question] How to properly switch a profile between MD and MDd for Visual Studio

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#11109]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

So I have this profile:
```
include(default)

[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MD

[options]

[build_requires]

[conf]
tools.microsoft.msbuild:max_cpu_count={{os.cpu_count()}}
tools.build:processes={{os.cpu_count()}}
tools.gnu.make:jobs={{os.cpu_count()}}
tools.ninja:jobs={{os.cpu_count()}}

[options]

[env]
CONAN_CPU_COUNT={{os.cpu_count()}}
```

but whenever I try and build I project for debug I get an error basically saying that the binaries I'm trying to link against and the ones I'm currently compiling aren't compatible due to one being `MD` and the other being `MDd`. I'm currently using the `cmake_find_package` generator for my project and switching the profile to use `MDd` works but gives me the opposite error in release, even when I pass `-s build_type=Release/Debug` to Conan it doesn't update the `compiler.runtime` option. Is there an easy way to have this update from command-line or will I have to have 2 separate profiles for release and debug?

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

There are a couple of approaches:

- If you are using dynamic runtime, which is the default, you can leave it not specified in the profile. It will get the MD or MDd value correctly ,depending on the ``build_type`` (this is a bit hardcoded in 1.X, it will be a plugin in 2.0)
- If you specify it in the profile, when you switch to Debug in command line, you need to do both ``-s build_type=Debug -s compiler.runtime=MDd``
- For the ``msvc`` new compiler setting, the definition has changed to ``compiler.runtime=static|dynamic``, and then ``compiler.runtime_type`` will be also automatically assigned to ``Debug`` or ``Release`` based on ``build_type``, if it is not specified directly in the profile.

For the default dynamic runtime, which seems your case, it seems the first alternative is what you are looking for, please try and let us know.
