### ISSUE TITLE
[question] semver_direct_mode() bug

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#11106]
Hi,

The documentation mentions a bug in current implementation of the semver_direct_mode()
https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=semver_direct_mode

Is there any workaround for this?

C -> B -> A -> icu

How to define it so that C and B depend on A using recipe_revision mode and A depends on icu at full_package_mode?

The documentation says that all the direct and indirect dependencies are shown in self.info.requires. Does it mean that every leaf module needs to define the needed revision mode for icu although the icu is not a direct dependency for those?

**Comment by MTomBosch** [comment]
@memsharded Can you tell us if the mentioned bug is/will be fixed in Conan 2.0?

**Comment by memsharded** [comment]
The ``package_id`` computation and the ``package_id`` modes were completely redesigned and improved in Conan 2.
Closing this ticket as solved, please create new ones for any question or issue regarding to Conan 2 new behavior, thanks for the feedback.
