### ISSUE TITLE
[question] Is there a way to add library without modifying CMakeLists.txt in Conan 2.0?

### ISSUE THREAD

**Issue by Kidsunbo** [conan-io/conan#11107]
In Conan 1.47, there is `cmake` generator which is in the tutorial of conan. After adding serveral lines of CMake code, I could only modify `conanfile.txt` to add libraries. It works pretty well when developing with VSCode and Clion. All I need to pay attention to is only `conanfile.txt`.  New added library will be appended to `CONAN_LIBS` automaticlly, which is extremelly convenient. 

It seems that the `cmake` generator has been removed in Conan 2.0. `cmake_find_package` and `cmake_paths` are the only ways to work with. But each time I modify the libraries, I have to modify CMakeLists.txt as well, find package, check existence, link to my target which is pretty tedious, when linking with many libraries, the `target_link_libraries` will be lengthy.

Is there a way like `cmake` generator to inject a variable which contains all the libraries I need into my CMakeLists.txt in Conan 2.0?

Thanks.
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Kidsunbo 

No, sorry, the way the 2.0 CMakeDeps integration work is the CMake native one, and that means adding a ``find_package()`` to your CMakeLists.txt. We liked the simplicity of the ``cmake`` generator, but the users feedback towards a fully transparent and native integration (that is, using ``find_package()`` was quite big, so we had to go that way.
