### ISSUE TITLE
[feature] option description in recipes

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#11108]
It would be useful to have a brief description of what an option does inside the recipe.

Sometimes it is hard to understand what an option does in a recipe. Some contributors of ConanCenter add comments to clarify but there is no native way of providing a description for an option.

For example, something like this:

```
options = {
    "shared": {
        "values": [True, False],
        "decription": "this is the option description"},
    "build_type": {
        "values": [True, False],
        "description": "another description"}
}
```

And provide this information via `conan inspect --json output.json` or similar so it can be retrieved from the command line.
This could be useful to show usage of recipe options in a future Conan Center webpage as well.

**Comment by memsharded** [comment]
I think that way of defining options would be very disruptive, it is a new and incompatible format of defining things, will be breaking things backwards badly, etc.

I'd suggest something less risky, like adding a new dict with descriptions:
```python
options_description = {
    "shared": "Define if the library is dynamic (True) or static (False)",
    "fPIC": "Activate the Position Independent Code",
}
```
The risk with this approach would be orders of magnitude smaller.

**Comment by memsharded** [comment]
This is not necessary for 1.49, just a nice to have. Moving it to 2.0-beta.1

**Comment by memsharded** [comment]
Closed in https://github.com/conan-io/conan/pull/11295
