### ISSUE TITLE
[Question] Apple Clang 13.0 != Apple Clang 13.1

### ISSUE THREAD

**Issue by NoWiseMan** [conan-io/conan#11104]
Hallo,

we are very surprised that conan now treats Apple Clang 13.0 compatible with 13.1.
Both versions are based on a different Clang version (Clang 13 vs. Clang 14).
Clang has a semi-annual release cycle and Xcode has an annual cycle with new minor releases for about every iOS version.
But every year one of the minor Xcode releases is a major update. These major updates incorporate most of the changes from the last Clang release. This year, that was Xcode 13.3 (you can recognize these "major" Xcode changes by Apple raising the OS requirements to the latest macOS version).

Since we use conan, it was easy to update all our internal and external C/C++ libraries by simply creating a new profile and running our CI with that profile for all our libraries (conan install ... not conan create). However, with the changes in conan 1.46.1, we did not get any new packages since conan now declares apple clang 13.0 and 13.1 as equivalent. We think this is a very questionable decision. Yes, they could be compatible and use the same ABI, but is that guaranteed? New clang versions always bring many improvements, fix code generation issues, add new warnings, etc.

We know that for running a Conan repo there are some aspects that speak for 13.0 and 13.1 as compatible compiler versions. Since we run our own Artifactory instance, it makes more sense for us to treat these two versions as different. This is because we want all our C/C++ libraries to be built with the same clang version. 

With some small changes we can have both.
Specifying the compiler version as

`compiler.version = 13
`
should treat conan 13.0 and 13.x as compatible 

Specifying the compiler version as
`compiler.version = 13.0
`
conan should treat 13.0 and 13.x as different versions

Is this something that can be implemented?
Or can you suggest a better way than an additional option for differentiation?

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11231
