### ISSUE TITLE
conan create failed for non git repo

### ISSUE THREAD

**Issue by redradist** [conan-io/conan#11118]
When I try manually to create package from non git repository, folders with sources and conanfile.py, I got the following error:
```console
Exporting package recipe
ERROR: 'C:\Users\<USER>\Downloads\compile-time-regular-expressions-3.6' is not a valid 'git' repository or 'git' not found.
```

Is there a way to create package from non git repo folder ?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, packages can be created from a non git repo folder. Simplest example is ``conan new hello/0.1 -m=cmake_lib``, then ``conan create``. It will work, even if that is not done inside a git repo.

**Comment by redradist** [comment]
@memsharded 
I figured out why this failed, it was due to `scm` attribute, see https://github.com/hanickadot/compile-time-regular-expressions/blob/main/conanfile.py#L15
I think it is intended behavior, I am closing this issue ...
