### ISSUE TITLE
[question] Is there a way to execute "conan create" withou re-downloading and re-unzip?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#11121]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I am constructing a recipe of libtorch, it's a large file (about 1.62G). And every time I change conanfile.py and conan create to test, it would download and unzip all over again, so could it be possible to cancel this step?

**Comment by czoido** [comment]
Hi @Tumb1eweed,
For testing purpouses you could use the --keep-source argument for the conan create. That way the source folder in the cache will be preserved even if you modify the recipe.

```
  -k, -ks, --keep-source
                        Do not remove the source folder in the local cache,
                        even if the recipe changed. Use this for testing
                        purposes only
```

**Comment by memsharded** [comment]
I would also recommend having a look at the local flow, using ``conan install``, ``conan source``, ``conan build`` commands, to develop locally, make sure things build (incremental builds also). Then trying only ``conan create`` as a very final check once everything is looking good, like end-to-end check of all steps.

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed, For testing purpouses you could use the --keep-source argument for the conan create. That way the source folder in the cache will be preserved even if you modify the recipe.
> 
> ```
>   -k, -ks, --keep-source
>                         Do not remove the source folder in the local cache,
>                         even if the recipe changed. Use this for testing
>                         purposes only
> ```

Thanks, -k is useful.
