### ISSUE TITLE
[bug] conan sh environment fails to generate deactivation_file on ubuntu-20.04

### ISSUE THREAD

**Issue by jellespijker** [conan-io/conan#11122]
### Environment Details (include every applicable attribute)
  * Github VM Ubuntu-20.04 
  * Ubuntu-20.04
  * Compiler N/A
  * up until 1.48
  * 3.10.4

### Steps to reproduce (Include if Applicable)
- Create an Virtual Run, Build or custom environment and save a script.
- Activate that VirtualEnvironment activation script with `source` or `.` on a bash shell
- it fails when running `echo echo Restoring environment >> "{deactivate_file}"`

### Logs (Executed commands with output) (Include/Attach if Applicable)

See the output of this GitHub action:
https://github.com/Ultimaker/Uranium/runs/6198574161?check_suite_focus=true

The script was generated with the following python_requires
https://github.com/Ultimaker/conan-ultimaker-index/blob/CURA-9177_Fix_CI_CD/recipes/PythonVirtualEnvironment/conanfile.py

with this recipe:
https://github.com/Ultimaker/Uranium/blob/CURA-9177_Fix_CI_CT/conanfile.py

In this workflow
https://github.com/Ultimaker/Uranium/blob/b9f291e0af04554ec2d584bb44bfe5c2378e5aea/.github/workflows/unit-tests.yml#L84

It works on most Linux and MacOS shells on which I use this, it just fails on the GitHub VM Ubuntu-20.04 and latest.

> Note:  
> Putting quote marks  around the `echo "echo Restoring environment" >> "{deactivate_file}"` fixes it.
> This seems like a nice first PR for me for your awesome product ;-) Expect my first contribution soon

**Comment by jellespijker** [comment]
On second thought I think this might not be a Conan issue, since the pipeline still fails even when I use my Conan fork with the suggested changes.

It might just be that I need to read-up on Github Action yaml syntax.

**Comment by memsharded** [comment]
Summary: this was not an issue, but https://github.com/conan-io/conan/pull/11123 was merged anyway, as it was safe and looked like an improvement
