### ISSUE TITLE
[feature] XCodeDeps support Conan Components

### ISSUE THREAD

**Issue by maikelvdh** [conan-io/conan#11125]
Currently the XcodeDeps is not supporting Conan components which is resulting in having all components added to the generated xcconfig context. It would be good to split the xcconfig creation in separate files per component to allow more granular selection of components to be utilised on consuming side.

**Comment by memsharded** [comment]
Same applies for MSBuildDeps, not split into components yet

**Comment by czoido** [comment]
Thanks @maikelvdh  for the suggestion, I'm adding this to the 1.49 milestone so that we can consider if components support for  both MSBuildDeps  and XcodeDeps could make it into that release.
