### ISSUE TITLE
[question] How to export Conan packages for usage within an SDK 

### ISSUE THREAD

**Issue by lucabonifacio** [conan-io/conan#11132]
Let's assume that we have a consumer that builds some libraries and for that it needs some Conan packages.

Now, let's say I would like to provide the libraries within an SDK and build other applications using CMake. For that I need to provide:
- binaries,
- includes,
- and CMake package config files generated by making usage of `CMakePackageConfigHelpers`.

What about the Conan dependencies? Copying the generated CMake files wouldn't work because all the paths are using the Conan cache location. Is there a way to export the Conan dependencies and control the install prefix?

I have seen there is the `deploy()` method, but I don't see how to fulfill my requirements.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @lucabonifacio 

The Conan 2.0 new deployers ``--deploy=full_deploy`` for example, will create a copy of the packages in the cache to the user folder, and what is more important, it will point the generated ``xxx-config.cmake`` files by ``CMakeDeps`` (or any other generator) to that user folder, not to the local cache.

Please try this feature with the latest released 2.0-alpha.7, feedback will be very appreciated!

**Comment by memsharded** [comment]
Hi @lucabonifacio 

I think this has been implemented in Conan 2.0, already released in alpha. Keep tuned for the docs, and looking forward your feedback if you try it! Closing this at the moment, as implemented.

If you need some workaround for this in 1.X, I would recommend:
- You can use the ``generate()`` method to visit ``self.dependencies``, and do a copy of the files you want to do. You can generate the files you need with ``CMakeDeps(self).generate()``
- after that, try to patch or search/replace the paths to point to the copied locations, instead of the cache ones.

Might need some work, but seems doable.

**Comment by rainman110** [comment]
@memsharded Just a feedback to the functionality in Conan 2.0:

From the users point of view it practically does not work yet, as there seems to be always at least one (transitive) dependency, whose recipe is not yet ready for 2.0. This makes it almost impossible to have conan install successfully running through.

**Comment by memsharded** [comment]
> From the users point of view it practically does not work yet, as there seems to be always at least one (transitive) dependency, whose recipe is not yet ready for 2.0. 

But those are different things. Yes, the recipes for dependencies need to be ready for 2.0. But they need to be ready anyway before getting to try to ``--deploy``, if you cannot build/install it, certainly you will not be able to collect the dependencies in a deployment, but that doesn't mean that the feature does not work. Maybe if you want to experiment the feature, you could try the ``--deploy``  with some subset of recipes that would already be 2.0 ready, and not your whole project.

**Comment by rainman110** [comment]
You are right, these are different things. I simply wanted to play around with this feature and tried to install separately different libraries - not a whole project. The problem still was, that many recipes are either not yet ready ( as you already know), or they are ready but pull in some dependencies which are not ready yet.

This should be no criticism but I simply wanted to share my probably obvious experiences as a Conan user.

Keep up the great work, I am totally looking forward to the 2.0 release.

**Comment by memsharded** [comment]
Thanks for the feedback. 
If you want to try it, maybe the repo we are using in the 2.0 docs can be useful, please check https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html, and trying some commands with those packages might be better than trying with ConanCenter at this moment, until everything gets to speed there.

**Comment by rainman110** [comment]
Thanks for the tip with the v2-only package repo. I am gonna try this!
