### ISSUE TITLE
[question] How to get package requirements, including tool requirements?

### ISSUE THREAD

**Issue by spectras** [conan-io/conan#11138]
I am currently using `conan info` to retrieve the dependency graph of packages (in order to generate CI pipelines).

This is on the "building" side of things. Thus, tool requirements are also required - for instance, if a package tool_requires `flex`, I need to have `flex` built before building that package.

I looked in other commands as well, and I do not find a way to get a build dependency graph for a package. Did I miss something?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @spectras 

Have you checked the ``--dry-build`` argument for ``conan info``? The thing is that the UI for it has accumulated some legacy, so the ``--build`` argument is used for other purpose. But ``--dry-build`` will do the same as ``conan install --build``, it should pull build-requires into your graph too. Please check and let me know.

**Comment by spectras** [comment]
Hello @memsharded. That was it!

Playing with it a bit, I even realized this nice property:
- `--dry-build=*` will pull the complete graph.
- `--dry-build=missing` will pull the complete *require* graph plus only the branches of the tool graph that are required for packages that lack a binary package.

Thanks for the fast answer! I can now generate my CI job graph matching conan deps graph, building one package per job, exactly as I wanted.

**Comment by memsharded** [comment]
Excellent, happy to hear that it is solved.
We know the UI was not the most intuitive, so we have fixed it so it will be ``conan graph info .... --build=missing`` for Conan 2.0 (also the graph will always be complete by default in 2.0).

Thanks for following up and closing!
