### ISSUE TITLE
[question] How make conan invisible to  library users

### ISSUE THREAD

**Issue by yooouxin** [conan-io/conan#11131]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I use conan with  cmake generator to develop my library such as mylib and export  cmake  targets to user.
When build mylib  , I use CONAN_PKG::fmt in CMakeLists.txt,but when user link cmake target mylib,it also links to target CONAN_PKG::fmt,when user don't use conan,cmake configure failed.
I can't make CONAN_PKG::fmt PRIVATE in cmake,because mylib may export some C++ template in header files which use <fmt/fmt.h>,must visible to users.
How can I make CONAN_PKG::fmt invisible to library users?
I notice that conanfile.txt can use [imports] to gather actual libraries and headers ,but can't handle cmake targets

**Comment by memsharded** [comment]
Hi @yooouxin 

I am not fully sure I got your problem, but I would like to clarify one thing for other users, just in case:

When you have a dependency graph, like ``app``->``mylib``->``fmt``, it depends on the library type how the linkage requirements are propagated:

- If ``mylib`` and ``fmt`` are static libraries, then **both** linkage requirements need to be propagated down to the ``app`` when it is being linked. It is not possible to "hide" it, or make it invisible. It is still necessary to install ``fmt`` dependency for the users of ``mylib``, this cannot be avoided. Static linkage is probably the most common, the most convenient to developers, and recommended for most cases
- Only if ``mylib`` is a shared library, ``fmt`` a static one, and absolutely all of ``fmt`` is an implementation detail of ``mylib``, that is, nothing escapes via de API (not referenced in public headers), or ABI, and the consumer of ``mylib`` already have the precompiled binary of the shared library, it is possible to "hide" the dependency of ``fmt``.

Also, a note, with ``CMakeDeps`` and ``CMakeToolchain``, you can get a fully CMake transparente integration, which won't require ``CONAN_PKG::xxxx`` anymore, but it will use ``find_package(xxxx)`` and ``target_link_libraries()`` and it will also handle transitive dependencies transparently, that is the users of ``mylib`` will only need ``find_package(mylib)``, but they will not need ``find_package(fmt)``. Maybe is this what you want?

**Comment by yooouxin** [comment]
Hi @memsharded
Thanks for quick reply.

Maybe my quesion was inappropriate.
think this case:
`mylib` is a header-only library,and use `fmt` in header files.
When I wrote `mylib`'s CMakeLists,I must export fmt's header files like this:
```
target_link_libraries(mylib
PUBLIC
CONAN_PKG::fmt # or find_package and just fmt here
)
```
But if app don't use conan as package manager,`CONAN_PKG::fmt` can't found by cmake.

So my question is how make `CONAN_PKG::fmt`  available even though user don't use conan.

I'm not sure CMakeDeps or CMakeToolchain would help this case ?

**Comment by memsharded** [comment]
It is not possible. If you have a library that is header only and depends on fmt, your users needs fmt. You cannot avoid that.

What you can avoid is that they need to install fmt with Conan, they could install with other means. Yes, use ``CMakeDeps`` and ``CMakeToolchain`` for that, as that will create a ``CMakeLists.txt`` for your ``mylib`` project that doesn't have anything Conan specific in it, it will be pure CMake, and it will work with ``fmt`` installed by other means not Conan.

**Comment by yooouxin** [comment]
@memsharded 
Thanks.
Another question:

Use `[imports]` in conanfile.txt can install fmt's header and library to a folder as runtime library.

Is it any possible to make xxx-config.cmake generated by  `CMakeDeps` available for user which don't use conan?

So that I can provide a complete sdk include cmake package files,runtime libraries and my library.

**Comment by memsharded** [comment]
> So that I can provide a complete sdk include cmake package files,runtime libraries and my library.

that is challenging. You would basically need to package every possible fmt binary for every possible platform, compiler, configuration that your users might need, or it would be broken. Furthermore, packaging fmt binary in the sdk, if it is being linked into your consumers applications, can lead to conflicts, linking errors if your consumers happen to be using ``fmt`` library (maybe a slightly different version) directly, which is a very real possibility.

It is possible to have the ``xxx-config.cmake`` files created by ``CMakeDeps`` to point to a user folder, but only with Conan 2.0, which is still in ``alpha`` stage, it will move to ``beta`` soon. It works using the ``--deployer=mydeployer`` functionality. But still, this doesn't solve your issue, because you cannot just redistribute all possible flavors of binaries for fmt that easily, and the possibility of conflicts commented above is real. This is the reason why a package and dependency manager like Conan exists.

**Comment by memsharded** [comment]
Closing this ticket as old and stale.

Furthermore, Conan 2 has implemented many new features that could be used for this use case, read for example https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html
