### ISSUE TITLE
[question] Upload fails when uploading "same" package from different platform

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#11140]
Hi,
I have a project that provides a DLL for Windows and .a library for Linux from the same project files. 
The recipe has "os" in settings.
So, for the project package, I have a binary package for Windows, and a binary package for Linux.

To build the packages, I build the Windows package on Windows and upload it, _then_ I do the same for Linux (after copying/git pull the latest project files).

Starting with Windows for example, Windows package is uploaded, then Linux package is uploaded as well, but:
1. Windows package has `Outdated from recipe: True`.
2. Updating _then_ the files on Windows (_for the same recipe version_), then trying to upload it, I get error `Upload recipe to 'xyz' failed: Remote recipe is newer than local recipe:` While this works if the package is created on only one platform.

My question is: 

**What is the best approach to upload both Windows & Linux binary-packages to the same package _version_ without having the above two issues**

Thanks

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi  @Bassem-Ramzy 

This is 99% of the time a different line endings in Windows vs Linux, using CRLF in Windows and LF in Linux. As the git checkout does actually modify the files, the resulting hash of the recipe changes, and this is how you get the "outdated from recipe". You can see the same effect activating revisions in that you get a new, different revision in different platforms

You can get more details in https://docs.conan.io/en/latest/faq/using.html?#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine, including hints to use git configuration or gitattributes to have the same line endings in all platforms.
