### ISSUE TITLE
[bug] Setting CMAKE_TOOLCHAIN_FILE to conan_toolchain.cmake make vscode-cmake-tool not work.

### ISSUE THREAD

**Issue by Kidsunbo** [conan-io/conan#11142]
I use VSCode to write a executable. And I use `CMakeDeps` and `CMakeToolchain` generators. After setting `CMAKE_TOOLCHAIN_FILE` to `conan_toolchain.cmake`, the command `CMake: Run Without Debuging` does not work. I have no idea it's due to Conan or vscode-cmake-tool. But when removing `CMAKE_TOOLCHAIN_FILE`, everything works fine. 

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.04 (docker)
  * Compiler+version: g++ 11.2
  * Conan version: 1.47
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)
1. Start a new docker and use VSCode to open it.
2. Start a new project with conan and with `CMakeDeps` and `CMakeToolchain` generators.
3. Set `CMAKE_TOOLCHAIN_FILE` to `conan_toolchain.cmake` above `project(demo)` (using `cmake_kits.json` is the same).
4. Put `find_package(something REQUIRED)` to `CMakeLists.txt` and it can compile with `CMake: Build` but `CMake: Run Without Debuging`.
### Logs (Executed commands with output) (Include/Attach if Applicable)
No log

**Comment by memsharded** [comment]
Hi @Kidsunbo 

It would be great if we could reduce a little bit the scope of the steps to reproduce:

- Is docker really necessary? Is this an issue that you see if working natively, that is in Windows?
- Are the dependencies really necessary? Because if it is a CMakeToolchain issue, the CMakeDeps should be totally irrelevant, specially for running. I would suggest to try with the ``conan new hello/0.1 --template=cmake_lib``, that would help to be sure is not nothing related to other things
- What are the error messages that you see while running the "CMake: Run"?
- If it builds correctly, the .exe should be there, can you please try to run it from the terminal directly, and report what are the error messages?

**Comment by Kidsunbo** [comment]
> Hi @Kidsunbo
> 
> It would be great if we could reduce a little bit the scope of the steps to reproduce:
> 
> * Is docker really necessary? Is this an issue that you see if working natively, that is in Windows?
> * Are the dependencies really necessary? Because if it is a CMakeToolchain issue, the CMakeDeps should be totally irrelevant, specially for running. I would suggest to try with the `conan new hello/0.1 --template=cmake_lib`, that would help to be sure is not nothing related to other things
> * What are the error messages that you see while running the "CMake: Run"?
> * If it builds correctly, the .exe should be there, can you please try to run it from the terminal directly, and report what are the error messages?

1. Actually, it's not necessary to docker. I just found this problem when I am using docker. I don't have PC but a Mac, and it's the same when working natively on my Mac.
2. Thanks for you remind, I find that the dependencies are not necessary. As you said, `conan_toolchain.cmake` is about `CMakeToolchain` rather than `CMakeDeps`. I use `conan new hello/0.1 --template=cmake_lib` to generate a project and open the folder as workspace with VSCode. After typing `command`+`shift`+`p` and type `CMake: Build Target`, it can find the target named `hello`. (ps: it's a lib so I can't use `CMake: Run`). For now, conan does not join the process but generating some code. Then I delete `layout()` function because cmake tools for vscode seems to only recognize `build` as build folder by default. After typing `conan install .. -pr:b=default` in `build` folder and add `set(CMAKE_TOOLCHAIN_FILE ${CMAKE_BINARY_DIR}/conan_toolchain.cmake)` before `program(hello)`. Then typing `CMake: Build Target` could not find target named `hello`. But it can still generate the binary successfully if I type the name `hello` manually.
3. There is no error message. Just nothing happened. As I mentioned above. If I type the name of the target manually, it works.
4. The executable can be built correctly with `CMake: Build`(not `CMake: Build Target`). And it works pretty well.
5. After removing the toolchain file, every command works.

It's not a blocking problem, but it's not convenient when developing with CMakeToolchain generator.

**Comment by memsharded** [comment]
> It's not a blocking problem, but it's not convenient when developing with CMakeToolchain generator.

Good to know. Are the CMake presets interesting to you? Because, the CMakeToolchain, specially the ``CMakePresets.json`` generation is getting many improvements in 1.48 (to be released tomorrow, check the different PR related to "Presets" in https://github.com/conan-io/conan/milestone/198?closed=1), I think it is worth waiting for it, and trying the Presets integration directly.

**Comment by Kidsunbo** [comment]
> > It's not a blocking problem, but it's not convenient when developing with CMakeToolchain generator.
> 
> Good to know. Are the CMake presets interesting to you? Because, the CMakeToolchain, specially the `CMakePresets.json` generation is getting many improvements in 1.48 (to be released tomorrow, check the different PR related to "Presets" in https://github.com/conan-io/conan/milestone/198?closed=1), I think it is worth waiting for it, and trying the Presets integration directly.

Sounds good. I will try it tomorrow.

**Comment by memsharded** [comment]
No need to close the issue until it is clear that it is solved. Don't hesitate to re-open after trying, or open a new one if you think the new Presets flow is different enough for a new ticket. Thanks!

**Comment by Kidsunbo** [comment]
> No need to close the issue until it is clear that it is solved. Don't hesitate to re-open after trying, or open a new one if you think the new Presets flow is different enough for a new ticket. Thanks!

Alright, the toolchain way seems not work as I said. I reopen this and try it with 1.48.

**Comment by Kidsunbo** [comment]
Hi @memsharded 
I found that with Conan 1.48, cmake tools for VSCode works perfectly even though it still doesn't work with Conan 1.47. But it's enough that it works with newer version. Thanks.

**Comment by memsharded** [comment]
Yes, these integrations are relatively stable now, but still experimental, it is expected that they keep improving from release to release, fixing bugs, etc., but might not get backports patches to older releases, because that experimental status.
