### ISSUE TITLE
[question] Android profile targeting the wrong compiler

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#11146]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
```ini
include(default)

api_level=16
target_host=arm-linux-androideabi
clang_host=armv7a-linux-androideabi
android_ndk={{os.getenv("ANDROID_NDK")}}
android_root=$android_ndk/platforms/android-$api_level/arch-arm

[settings]
arch=armv7
build_type=Release
compiler=clang
compiler.libcxx=c++_shared
compiler.version=8
os=Android
os.api_level=$api_level

[conf]
tools.android:ndk_path=$android_ndk

[options]

[env]
ANDROID_NDK_ROOT=$android_ndk
CONAN_CMAKE_SYSROOT=$android_root
CONAN_CMAKE_ANDROID_NDK=$android_ndk
PATH=[$android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
LD=$target_host-ld
STRIP=$target_host-strip
RANLIB=$target_host-ranlib
CC=$clang_host$api_level-clang
CXX=$clang_host$api_level-clang++

LDFLAGS=-llog
```

I have the above profile, as you can see the c compiler variable is `CC=$clang_host$api_level-clang` yet when I build I get 
```
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/opt/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.
```

I checked and made sure that `/opt/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang` exists and that it's not just a symlink. Is there something being set that's overriding the environment variable?

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

The recipe that you are using, and the build system integration used are critical to understand what is happening. 
With the new ``CMakeToolchain`` you should only need ``tools.android:ndk_path``, and the correct ``settings``, but most likely you can get rid of many of the other ``[env]`` definitions. 

Could you please try with the ``conan new hello/0.1 --template=cmake_lib`` recipe and report? Thanks!

**Comment by wbehrens-on-gh** [comment]
I was able to build `hello/0.1`, the package that is giving me that error though is `ade/0.1.1f` from conan center.

**Comment by memsharded** [comment]
> ade/0.1.1f from conan center.

Yes, that is possible, packages from ConanCenter have not upgraded yet to the new toolchains and integrations, and they might not be fully prepared to cross-build to Android.
