### ISSUE TITLE
[bug] deactivate.ps1 does not work because of DYLD_FRAMEWORK_PATH

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan#11145]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 11 (10.0.22000)
  * Compiler+version: None
  * Conan version: 1.47
  * Python version: Python 3.10.3

### Steps to reproduce (Include if Applicable)
In a windows powershell console:
- start from template `conan new hello/0.1 --template=cmake_lib`
- add any build requirement like 
```python
    def build_requirements(self):
        self.tool_requires("cmake/3.20.0")
```
- launch conan install with host an build profile `conan install . -if build --profile:host=default --profile:build=default -g virtualenv`
- launch activate.ps1, then deactivate.ps1.
You get several errors:
`Cannot find path 'Env:\DYLD_FRAMEWORK_PATH' because it does not exist`
same with DYLD_LIBRARY_PATH and LD_LIBRARY_PATH

Workaround, before type:
`Set-Item env:DYLD_FRAMEWORK_PATH -Value "None"`
`Set-Item env:DYLD_LIBRARY_PATH -Value "None"`
`Set-Item env:LD_LIBRARY_PATH -Value "None"`

From what I understand DYLD_FRAMEWORK_PATH is used only by OSX and LD_LIBRARY_PATH only by linux so it should not be in the ps1 script.

**Comment by memsharded** [comment]
Hi @fdgStilla 

I think this has been solved with the new environment management, have a look to the new tools in: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html

The new templates also use this new environment management, so starting with ``conan new hello/0.1 --template=cmake_lib`` would be a good starting point to reproduce and report problems, if you see it persisting (it shouldn't I just check the code and it is doing:

```python
    if os_name and not os_name.startswith("Windows"):
        if cpp_info.libdirs:
            libdirs = _handle_paths(cpp_info.libdirs)
            dyn_runenv.prepend_path("LD_LIBRARY_PATH", libdirs)
            dyn_runenv.prepend_path("DYLD_LIBRARY_PATH", libdirs)
        if cpp_info.frameworkdirs:
            dyn_runenv.prepend_path("DYLD_FRAMEWORK_PATH", _handle_paths(cpp_info.frameworkdirs))
```
So clearly DYLD_FRAMEWORK should not appear anymore in Windows.

**Comment by fdgStilla** [comment]
I added how to reproduce from the conan template in the initial description.

**Comment by memsharded** [comment]
Hi @fdgStilla 

Yes, you need to use the new ``-g VirtualRunEnv`` generator, that is the modern one, the ``-g virtualenv`` has already been removed from 2.0. If you want the generator to output powershell, then also add ``-c tools.env.virtualenv:powershell=True``, as the default is to generate only ``.bat`` files.

**Comment by fdgStilla** [comment]
Ok thanks I will try that
