### ISSUE TITLE
[feature] set CMAKE_CROSSCOMPILING within CMakeToolchain 

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#11157]
conan knows, that we are cross_building or not. This information should be forwarded to cmake when using CMakeToolchain generator, so in `conan_toolchain.cmake` the cmake-variable `CMAKE_SYSTEM_NAME` should be set (which will set `CMAKE_CROSSCOMPILING` to `TRUE/FALSE` accordingly).

Ref: https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING.html

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
The `CMAKE_SYSTEM_NAME` should be adjusted automatically already. Could you provide the profiles you are using and the Conan version? Please note that the `--profile:build` has to be specified too.


FYI. You can write a `[conf]` entry in your profile to help deduce the `CMAKE_SYSTEM_NAME`, but as I said, it should be working.

```
[settings]
...
[conf]
tools.cmake.cmaketoolchain:system_name=Linux

```
