### ISSUE TITLE
[question] How a package can force an option value

### ISSUE THREAD

**Issue by JonathanGirardeau** [conan-io/conan#11152]
Hello,

Here is an example:
Package A has an option `with_feature`, with no default value. 
Package B requires package A, but it works only if option `A:with_feature=True`.
Package C depends on package B. I don't want to set in package C the value of option `A:with_feature`, I want it to be defaulted to `True` because C depends on B.

I tried this in package B recipe:
`default_options = {"A:with_feature":'True'}`

But it has no effect when I do `conan install` of package C, I got this error:
`'with_feature' value not defined`

How can I enforce (at least default) the value of an option so any package that depends on my package has no need to choose option value ?

**Comment by SpaceIm** [comment]
recipe B:

```python
from conans import ConanFile
from conans.errors import ConanInvalidConfiguration


class BConan(ConanFile):
    (...)

    def configure(self):
        self.options["A"].with_feature = True

    def requirements(self):
        self.requires("A/x.y.z")

    def validate(self):
        if not self.options["A"].with_feature:
            raise ConanInvalidConfiguration("B requires A:with_feature=True")
```

**Comment by JonathanGirardeau** [comment]
Thank u @SpaceIm  for your answer.
It raises an error when package C set `A:with_feature=False`, it is a good point. However I would like that package C has not to  explicit `A:with_feature` value.

I have noticed a behavior of conan: If I do not explicit A:with_feature value in C recipe or in command `conan install` of package C

1. With this order of dependencies:
```
class CConan(ConanFile):
    (...)
    requires = [("A/1.0.0"),
                ("B/1.0.0")]
```
I got an errror:
`ERROR: A/1.0.0: 'with_feature' value not defined`

2. With this order of dependencies:
```
class CConan(ConanFile):
    (...)
    requires = [("B/1.0.0"),
                ("A/1.0.0")]
```
It works.

So my new question is: Can I rely on `self.requires` order to solve my issue ? 
Is there a good practice for `self.requires` order ? Upstream packages first ?

**Comment by memsharded** [comment]
This ticket was referring to Conan 1, which is now deprecated.

Conan 2 has introduced new ways to manage options values for dependencies, and their priorities, including the definition of "important" option values with the ``!`` syntax. Please see https://docs.conan.io/2/reference/conanfile/attributes.html#default-options

Closing this ticket as outdated,  please create new tickets for any further question or issue, thanks for the feedback!
