### ISSUE TITLE
Not able to build package without settings

### ISSUE THREAD

**Issue by JD31** [conan-io/conan#11159]
### Environment Details (include every applicable attribute)
  * Conan version: 1.42.2

### Steps to reproduce (Include if Applicable)
I am trying to do a recipe to deploy a data. It is not os / compiler specific.
Basically the recipe has just a name and a version, then the build step is retrieving the data from an url.
Then the package method actually packages it as desired.
It is very straight forward and is nearly working but my issue is that the default settings from the current platform are always added.

> 
> conan create . conan/stable
> 
> Exporting package recipe
> MissionPlusNViewerJS/2022.2.1@navblue/testing: A new conanfile.py version was exported
> MissionPlusNViewerJS/2022.2.1@navblue/testing: Folder: C:\Users\jerome.desfieux\.conan\data\MissionPlusNViewerJS\2022.2.1\navblue\testing\export
> MissionPlusNViewerJS/2022.2.1@navblue/testing: Exported revision: 52ff2646e5cb72d4a923fc1e7a5038d4
> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> os=Windows
> os_build=Windows
> [options]
> [build_requires]
> [env]
> 

I would like settings attributes to be empty.
I tried 'settings: None' in the recipe but it doesn't help...

**Comment by memsharded** [comment]
Hi @JD31 

Package recipes that are building things, need to know the os, the compiler, the build_type, the architecture to build that thing. It is impossible to build them if you are not defining the settings.

Only things that doesn't need to be compiled, like a header-only library, can remove the ``settings``.

Even if ``then the build step is retrieving the data from an url.``, the thing that you are downloading from the internet is already built for an OS and architecture, so it sounds like at least the ``settings = "os", "arch"`` are still necessary, aren't they?

Also, the message that you are seeing in the output, is not the settings applied to the recipe. Those are the general input settings. If the recipe don't define ``settings``, it will not use ``settings`` at all.

**Comment by JD31** [comment]
Thank you for your quick help!

> Package recipes that are building things, need to know the os, the compiler, the build_type, the architecture to build that thing. It is impossible to build them if you are not defining the settings.
> 
> Only things that doesn't need to be compiled, like a header-only library, can remove the settings.
> 
> Even if then the build step is retrieving the data from an url., the thing that you are downloading from the internet is already built for an OS and architecture, so it sounds like at least the settings = "os", "arch" are still necessary, aren't they?

It is absolutely not OS linked. It is close to a header only solution.

> Also, the message that you are seeing in the output, is not the settings applied to the recipe. Those are the general input settings. If the recipe don't define settings, it will not use settings at all.

OK. Perfect. That was confusing me.
So I guess if I try to install this dependency through a mac without settings defined, I would be able to retrieve it ?

**Comment by memsharded** [comment]
> OK. Perfect. That was confusing me.
So I guess if I try to install this dependency through a mac without settings defined, I would be able to retrieve it ?

Yes, exactly. Installing this package that you have removed the ``settings``, can be done for all inputs, when not defining settings, when defined settings for Mac, for Linux, etc., because other packages in the graph will need to have settings defined. In other words, the ``package_id`` for this package will always the same, resolving to the same artifacts, irrespective of the input settings.

Does this help?

**Comment by JD31** [comment]
Yes. I confirm it works as described. Thanks a lot.
