### ISSUE TITLE
[bug] Conan 1.48.0 breaks CMakeDeps / CMakeToolchain

### ISSUE THREAD

**Issue by MiSo1289** [conan-io/conan#11167]
### Environment Details
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: GCC 9
  * Conan version: 1.48.0
  * Python version: 3.8.10
  * CMake version: 3.22.2

### Steps to reproduce
`conanfile.txt`:
```
[requires]
fmt/8.1.1

[generators]
CMakeDeps
CMakeToolchain
```

`CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.16)
project(reproduction)

find_package(fmt REQUIRED)

add_executable(reproduction)
target_link_libraries(reproduction PRIVATE fmt::fmt)
target_sources(reproduction PRIVATE main.cpp)
```

`main.cpp`:
```c++
#include <fmt/format.h>

int main() {}
```

### Logs (Executed commands with output)

```console
$ mkdir build && cd build
$ conan install .. -pr:b=default
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
*:fPIC=True
*:shared=False
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
*:fPIC=True
*:shared=False
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    fmt/8.1.1 from 'conan-center' - Cache
Packages
    fmt/8.1.1:4eb2d280e3273c9ab04b4c51b456b2a272ff6fc3 - Cache

Installing (downloading, building) binaries...
fmt/8.1.1: Already installed!
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
$ cmake .. --toolchain=conan_toolchain.cmake
-- Using Conan toolchain: /root/repro/build/conan_toolchain.cmake
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'fmt::fmt'
-- Configuring done
-- Generating done
-- Build files have been written to: /root/repro/build
$ VERBOSE=1 make
/usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake -S/root/repro -B/root/repro/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake -E cmake_progress_start /root/repro/build/CMakeFiles /root/repro/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/root/repro/build'
make  -f CMakeFiles/reproduction.dir/build.make CMakeFiles/reproduction.dir/depend
make[2]: Entering directory '/root/repro/build'
cd /root/repro/build && /usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake -E cmake_depends "Unix Makefiles" /root/repro /root/repro /root/repro/build /root/repro/build /root/repro/build/CMakeFiles/reproduction.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/root/repro/build'
make  -f CMakeFiles/reproduction.dir/build.make CMakeFiles/reproduction.dir/build
make[2]: Entering directory '/root/repro/build'
[ 50%] Building CXX object CMakeFiles/reproduction.dir/main.cpp.o
/usr/bin/c++   -m64 -MD -MT CMakeFiles/reproduction.dir/main.cpp.o -MF CMakeFiles/reproduction.dir/main.cpp.o.d -o CMakeFiles/reproduction.dir/main.cpp.o -c /root/repro/main.cpp
/root/repro/main.cpp:2:10: fatal error: fmt/format.h: No such file or directory
    2 | #include <fmt/format.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/reproduction.dir/build.make:76: CMakeFiles/reproduction.dir/main.cpp.o] Error 1
make[2]: Leaving directory '/root/repro/build'
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/reproduction.dir/all] Error 2
make[1]: Leaving directory '/root/repro/build'
make: *** [Makefile:91: all] Error 2
```

### Other
It can be seen that the include path to the package is not added to the build command.

Can be reproduced with other packages (I also tried `nlohmann_json/3.10.5`).

The issue is not present with conan 1.47.0

**Comment by ghost** [comment]
SDL2 suffers also from this on Windows
```
c:\workspace>cd cpp-cmake-conan-base

c:\workspace\cpp-cmake-conan-base>rd /s /q build
The system cannot find the file specified.

c:\workspace\cpp-cmake-conan-base>conan install -if build .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    gtest/1.11.0 from 'conancenter' - Cache
    sdl/2.0.20 from 'conancenter' - Cache
Packages
    gtest/1.11.0:3f7b6d42d6c995a23d193db1f844ed23ae943226 - Cache
    sdl/2.0.20:d5963496fcfc7c5a7f3d13f39a26a3b3997af667 - Cache

Installing (downloading, building) binaries...
gtest/1.11.0: Already installed!
sdl/2.0.20: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo

c:\workspace\cpp-cmake-conan-base>cd build

c:\workspace\cpp-cmake-conan-base\build>cmake -DBUILD_TESTING=TRUE ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'SDL2::SDL2-static'
-- Conan: Component target declared 'SDL2::SDL2main'
-- Conan: Target declared 'sdl::sdl'
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'gtest::gtest'
-- Configuring done
CMake Error at src/CMakeLists.txt:28 (target_link_libraries):
  Target "base" links to:

    SDL2::SDL2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

c:\workspace\cpp-cmake-conan-base\build>cmake -DBUILD_TESTING=TRUE ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19044.
-- Conan: Component target declared 'SDL2::SDL2-static'
-- Conan: Component target declared 'SDL2::SDL2main'
-- Conan: Target declared 'sdl::sdl'
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'gtest::gtest'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/workspace/cpp-cmake-conan-base/build

c:\workspace\cpp-cmake-conan-base\build>cmake --build .
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/workspace/cpp-cmake-conan-base/src/CMakeLists.txt
  application.cpp
C:\workspace\cpp-cmake-conan-base\src\application.cpp(3): fatal error C1083: Cannot open include file: 'SDL2/SDL.h': No
 such file or directory [C:\workspace\cpp-cmake-conan-base\build\src\base.vcxproj]
```

**Comment by memsharded** [comment]
@codehavik I don't think it is the same problem, in the case of @MiSo1289, it is finding the target, ``Conan: Target declared 'fmt::fmt'``, but in your case it is that there is a misalignment in the target name ``SDL2::SDL2`` vs ``sdl::sdl``. That could be a recipe issue, I recommend submitting in a separate issue.

@MiSo1289 just tried in Windows, couldn't reproduce, moving to Linux to try it now. Thanks very much for the detailed report and code.

**Comment by ghost** [comment]
@memsharded Do you know if there is an intent to use common CMake targets in conan? I mean generally SDL2::SDL2 is the target provided by cmake and it would be great to work like this. I mean, I use conan only for pulling the dependencies and I'd like to use conan in a non-intrusive way? And sorry for the confusion, I am pretty new with conan. I will add this comment to a separate issue (if it's an issue at all). The relevant sample project is public for everyone to see: https://github.com/codehavik/cpp-cmake-conan-base

**Comment by memsharded** [comment]
@MiSo1289 

Conan 1.48, got a minor modification to ``CMakeToolchain``. Now ``CMAKE_BUILD_TYPE`` is not hardcoded in the ``conan_toolchain.cmake``, but instead needs to be defined in the command line (``-DCMAKE_BUILD_TYPE=Release``) or in the ``CMakePresets.json`` that we are generating now, please check it, if using latest CMake, it can be very convenient.

This change was done because defining the build type inside a toolchain is not a best practice, it was put there for convenience, but it is closer to the developer experience to define it in the cli or in the presets.

**Comment by memsharded** [comment]
@codehavik 

Yes, you are right, packages in ConanCenter have a mechanism to map to the upstream target names, with is ``self.info.set_property("cmake_target_name", "SDL2::SDL2")``. It is likely that the ``sdl`` package recipe in ConanCenter has not added this mechanism yet for the modern ``CMakeDeps`` integration. It makes sense to report it there (in ``conan-center-index`` repo), if not already reported.

**Comment by ghost** [comment]
@memsharded Thanks for helping me out! I really appreciate it. Good luck!

**Comment by MiSo1289** [comment]
@memsharded 

Thanks for the info, I can confirm that adding `-DCMAKE_BUILD_TYPE=Debug` fixes the issue; I will also try with the preset. Still, maybe the toolchain file could detect this and warn about a missing build type setting, instead of silently failing to append any flags to the targets?

**Comment by MiSo1289** [comment]
@memsharded Also, passing `--preset Debug` to CMake does not work when using a separate build directory, because CMake expects the preset file to be found in the source directory; any workarounds?

**Comment by memsharded** [comment]
> @memsharded Also, passing --preset Debug to CMake does not work when using a separate build directory, because CMake expects the preset file to be found in the source directory; any workarounds?

Latest Conan can generate a ``CMakeUserPresets.json`` in the CMakeLists.txt directory if not existing, that can be used, and an ``include()`` to the Conan presets can be done there if already existing. Otherwise, it is necessary to copy the ``<generators_folder>/CMakePresets.json`` to the source folder, because CMake for some reason won't allow specifying another location for the presets file (maybe it makes sense to continue requesting this to CMake project directly), and Conan cannot generate the presets file in the source, as that would be dirty, and it has risk of destroying user info.

**Comment by MiSo1289** [comment]
@memsharded Ok, thanks very much for info.

**Comment by memsharded** [comment]
Creating #11168 to follow up on a possible warning to avoid this

**Comment by SpaceIm** [comment]
> @codehavik I don't think it is the same problem, in the case of @MiSo1289, it is finding the target, `Conan: Target declared 'fmt::fmt'`, but in your case it is that there is a misalignment in the target name `SDL2::SDL2` vs `sdl::sdl`. That could be a recipe issue, I recommend submitting in a separate issue.
> 
> @MiSo1289 just tried in Windows, couldn't reproduce, moving to Linux to try it now. Thanks very much for the detailed report and code.

@codehavik had 2 issues, and the second one is indeed related to this issue, and it comes from conan 1.48.0. Targets generated by CMakeDeps or cmake_find_package* don't propagate their properties when CMAKE_BUILD_TYPE of consumer project doesn't match the one of the dependencies.

**Comment by ghost** [comment]
@SpaceIm But could you please suggest which generator should I use if I just want to use conan for providing dependencies on my workstation? The cmake build system shall manage the rest: generating the solution, setting up the compiler, etc... I am really confused now :( As far as I understand, CMakeDeps is the best for such scenario or cmake_find_package

**Comment by SpaceIm** [comment]
Just set `CMAKE_BUILD_TYPE` properly during CMake configuration.

**Comment by SpaceIm** [comment]
@memsharded Do we also have to enforce `CMAKE_BUILD_TYPE` when CMake is called with `CMakeToolchain` + `CMake` helper? In source code, `CMake` helper comments claim that only `--config Release` is passed for multi-config generators, but what about single-config generators?

**Comment by memsharded** [comment]
> @memsharded Do we also have to enforce CMAKE_BUILD_TYPE when CMake is called with CMakeToolchain + CMake helper? In source code, CMake helper comments claim that only --config Release is passed for multi-config generators, but what about single-config generators?

In single-config generators, ``CMake`` is passing ``-DCMAKE_BUILD_TYPE``, extracted from the ``CMakePresets.json`` file. It is more idiomatic than having it defined in the toolchain.cmake file.
