### ISSUE TITLE
[feature] Allow to disable CMakeDeps or PkgConfigDeps in `package_info()`

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11165]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Would it make sense to add a switch in `package_info()` to neutralize `CMakeDeps` or `PkgConfigDeps` of the recipe itself at consume time so that it would allow smoother integration of recipes packaging CMake config files & pkgconfig files with conan-center like recipes (where these files are deleted) in a dependency graph?

**Comment by memsharded** [comment]
I think this is the already existing ``self.cpp_info.set_property("cmake_find_mode", "none")``:

```python
            cmake_find_mode = dep.cpp_info.get_property("cmake_find_mode")
            cmake_find_mode = cmake_find_mode or FIND_MODE_CONFIG
            cmake_find_mode = cmake_find_mode.lower()
            # Skip from the requirement
            if cmake_find_mode == FIND_MODE_NONE:
                # Skip the generation of config files for this node, it will be located externally
                continue
```

**Comment by SpaceIm** [comment]
Oh, interesting, I've missed this feature. Thanks. Closing this issue.
