### ISSUE TITLE
[bug] "packages in build_requires not appearing in build-order.json" 

### ISSUE THREAD

**Issue by rakeshnarayanaswamy** [conan-io/conan#11160]
### Environment Details (include every applicable attribute)
  * Operating System+version: window 10 
  * Compiler+version:  ghs
  * Conan version: 1.47
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
1) conan lock create --reference {pkga/0.1.1@user/test} --locked-out={path to lock file} --build {pkga/0.1.1@user/test} --build {" --build ".join(refs.keys())}
  #the refs is a dictionary with some list of packages pkga depends on and they needs to be rebuilt
2)conan lock build-order {path to lock file created in step1} --json=build_order.json

build_order.json contains the packages in the order they needs to be built but it does not contains the packages listed under "build_requires"/"tool_requires" of pkga recipe.

**Comment by memsharded** [comment]
Hi @rakeshnarayanaswamy 

I would need a bit more details about that, because I cannot reproduce. 
For example:

```bash
$ conan lock create --reference=iceoryx/2.0.0 --build=iceoryx
```
Results in something like:
```json
{                                                            
 "graph_lock": {                                             
  "nodes": {                                                 
   "1": {                                                    
    "ref": "iceoryx/2.0.0#c7d33aa51c2972c3fde4696da6b39d7a", 
    "options": "shared=False\ntoml_config=True",             
    "package_id": "c8d37e54e0375e8696f9752d588aa89d6646390a",
    "requires": [                                            
     "2"                                                     
    ],                                                       
    "build_requires": [                                      
     "3"                                                     
    ],                                                       
    "context": "host"                                        
   },                                                        
   "2": {                                                    
    "ref": "cpptoml/0.1.1#12b5e5296b0c6253b702129eae332f88", 
    "options": "",                                           
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "prev": "5edc49bb237ae9a204e09361ab505960",              
    "context": "host"                                        
   },                                                        
   "3": {                                                    
    "ref": "cmake/3.16.2#5feb011f815049c2d39e4363faed970e",  
    "options": "with_openssl=False",                         
    "package_id": "0a420ff5c47119e668867cdb51baff0eca1fdb68",
    "context": "host"                                        
   }                                                         
  },                                                         
  "revisions_enabled": true                                  
 },                                                                                                               
```
As it can be seen, it contains the ``cmake``, which is a build_require of ``iceoryx``, and then:
```bash
$ conan lock build-order conan.lock --json=build_order=build.json
[[('cmake/3.16.2@#5feb011f815049c2d39e4363faed970e', '0a420ff5c47119e668867cdb51baff0eca1fdb68', 'host', '3')], [('iceoryx/2.0.0@#c7d33aa51c2972c3fde4696da6b39d7a', 'c8d37e54e0375e8696f9752d588aa89d6646390a', 'host', '1')]]
```

**Comment by rakeshnarayanaswamy** [comment]
Hi sir,
the below is the content of lock file created in my case, pkg5 is under build_requires of pkg1 which supposed to be rebuilt but its prev attribute is set (I dont understand it because the pkg5 sources are modified) 
interestingly same pkg, pkg5 is also repeated two times in the lock file under both( 5 & 6) (shouldn't it be under one number say 5 even if it is being consumed by both pkg1 and pkg3)

{
 "graph_lock": {
  "nodes": {
   "1": {
    "ref": "pkg1/0.1.1@ntc/testing",
    "options": "variant=08\npkg3:FOO_STATE=OFF",
    "package_id": "9bc59e4a48ab195f1b564ff077876cae7e4d3b9b",
    "python_requires": [
     "yxz/0.1.1@ntc/testing"
    ],
    "requires": [
     "2",
     "3",
     "4"
    ],
    "build_requires": [
     "6"
    ],
    "context": "host"
   },
   "2": {
    "ref": "pkg2/0.1.1@ntc/testing",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "context": "host"
   },
   "3": {
    "ref": "pkg3/0.1.1@ntc/testing",
    "options": "FOO_STATE=OFF",
    "package_id": "0e5bce2c1b2adf184228b1522b7daff342e57c52",
    "python_requires": [
     "xyz/0.1.1@ntc/testing"
    ],
    "requires": [
     "2"
    ],
    "build_requires": [
     "5"
    ],
    "context": "host"
   },
   "4": {
    "ref": "pkg4/0.1.1@ntc/testing",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "prev": "0",
    "context": "host"
   },
   "5": {
    "ref": "pkg5/0.1.1@ntc/testing",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "prev": "0",
    "context": "host"
   },
   "6": {
    "ref": "pkg5/0.1.1@ntc/testing",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "prev": "0",
    "context": "host"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=rh850\narch_build=x86_64\nbuild_type=Release\ncompiler=ghs\ncompiler.version=comp_201517_1fp\nos=RTAOS\nos_build=Windows\n[options]npkg1:variant=08\npkg3:FOO_STATE=OFF\n[build_requires]\n[env]\n"
}

below is build-order.json, pkg5 is missing (probably because prev attribute is set ) but primary question even when sources of pkg5 is modified why its prev attribute is set

[
 [
  [
   "pkg2/0.1.1@ntc/testing",
   "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
   "host",
   "2"
  ]
 ],
 [
  [
   "pkg3/0.1.1@ntc/testing",
   "0e5bce2c1b2adf184228b1522b7daff342e57c52",
   "host",
   "3"
  ]
 ],
 [
  [
   "pkg1/0.1.1@ntc/testing",
   "9bc59e4a48ab195f1b564ff077876cae7e4d3b9b",
   "host",
   "1"
  ]
 ]
]

**Comment by memsharded** [comment]
The key is here:
```
"6": {
    "ref": "pkg5/0.1.1@ntc/testing",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "prev": "0",
    "context": "host"
   }
```
These packages have defined the ``prev: 0``, they define their package-revision. That means that when you computed the graph, you didn't specify something like ``--build=pkg5``, and it is using pre-compiled binaries (it is locking the binary with package revision = 0). You need to say that you want to build those packages too when you capture the lockfile.

**Comment by rakeshnarayanaswamy** [comment]
Hi Sir,
I got the reason , actually pkg5 is packaging some files like (.js etc ) so potentially this package is not building any source files , no build method in the pkg5 recipe so we set build_policy to "never" , probably thats the reason even after mentioning this pkg5 in --build , this was appearing with prev .. after removing line build_policy = never , the issue is solved.

However there is a contradiction here
conan documentation says  if we are not building any sources and for header-only packages then build_policy can be never and then such recipes must be executed with conan export-pkg command.
but if we give build_policy= never in recipe then conan lock create wont consider this package for build when provided with --build.....

**Comment by memsharded** [comment]
I am not sure about that, can you provide the link with those sentences?
Because ``build_policy = "never"`` is intended exactly for ``export-pkg``, and yes, that means that if you define it, this package will not participate in any "build", or in any "build-order", because this package, basically cannot be built.

Does this make sense?

**Comment by rakeshnarayanaswamy** [comment]
hi Sir,

https://docs.conan.io/en/latest/mastering/policies.html the link explains about build_policies  and says for packages exporting some files build_policy will be never...
but then with this property , conan should also have allowed the user to pass such package to conan lock create  command ..
may be not to --build but some thing like --export-pkg (my proposal)

does it makes sense?

**Comment by memsharded** [comment]
That is not the intent of the ``build-order`` command, which is intended for CI, and re-building and integrating changes from developers to recipes and code. As the ``export-pkg`` packages cannot be integrated in the same flow (basically running ``conan install <pkg-ref> --build=<pkg-ref>``, that works for packages building from source with the ``build()`` method), then those packages are created just once, and then they should never be re-built, because they don't build from sources. Why would you want to do a new ``export-pkg`` if you are guaranteed to obtain exactly the same result? 

This is basically the purpose of the ``build_policy = "never"``, if you want it to be in the build order, you can just remove the ``build_policy`` from the recipe, and then you will get the behavior that you want? Am I missing something here? Thanks for your feedback!

**Comment by rakeshnarayanaswamy** [comment]
Hi Sir, 

Thanks for your explanation , I agree with your argument except for  "why would you want to do a new export-pkg if you are guaranteed to obtain exactly the same result ?"
The answer is , if we add new files to the source folder(say new .js file) or modify the recipe then we need to re export-pkg .

But for now I will remove build_policy attribute so that build-order will show it in the .json file , so that will do re export-pkg again.

Thanks again for your quick responses , I appreciate it.
