### ISSUE TITLE
Mingw - error while executing conan install

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#1116]
Hello,

On a Windows machine with Visual Studio 2015 and MinGW installed at the same time, having deleted my .conan directory and executing conan from msys, I see that conan correctly detects that I have a gcc compiler as well as Visual Studio:

```
It seems to be the first time you've ran conan
Auto detecting your dev setup to initialize conan.conf
Found Visual Studio 9
Found Visual Studio 14
Found gcc 5.3
Default conan.conf settings
        os=Windows
        arch=x86_64
        compiler=Visual Studio
        compiler.version=14
        compiler.runtime=MD
        build_type=Release
```
I leave the conan.conf file as generated by default, and then for a package, I execute the following from within msys, trying to tell conan to prepare a mingw build, so to speak:

` conan install .. -s compiler=gcc -s compiler.version=4.9 -s compiler.libcxx=libstdc++`

But I the the following error:

```
ERROR: None: Error in package_info() method, line 116
        if self.settings.compiler.runtime != "MT":
        'settings.compiler.runtime' doesn't exist for 'gcc'
'settings.compiler' possible configurations are ['exception', 'threads', 'version']
```
I have also tried replacing the VS associated values in conan.conf with the settings passed by the conan install command mentioned above, but I still get the same error. Am I doing something wrong here? I am using conan version  0.20.3

Thanks!

Dimitri

**Comment by memsharded** [comment]
The error is in the package recipe. If you are checking the runtime, you first have to check the compiler, so try:
```python
if self.settings.compiler=="Visual Studio" and self.settings.compiler.runtime != "MT":
    # whatever you wanted to do for MT
```

Runtime is a nested setting, it only exist for Visual Studio, so you can only check it when the compiler is Visual Studio. This is precisely a mechanism to make sure that you are not applying some logic that you didn't want to (like applying that for VS runtime MD to that Mingw build).

**Comment by dimi309** [comment]
My fault :) I got it now. Thanks a lot!
