### ISSUE TITLE
[feature] [package_id] Unify `ConanInfo.dumps()` and `ConanInfo.package_id`

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#11164]
Ideally `ConanInfo.package_id()` should call internally to `self.dumps` and that's it. Basically, the idea is to have something like the following function:

```python
    def package_id(self):
        """
        The package_id of a conans is the sha1 of its specific requirements, options, settings,
        some configurations,...
        """
        text = self.dumps()
        package_id = sha1(text.encode())
        return package_id
```
Depends on: https://github.com/conan-io/conan/issues/11162

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11183
