### ISSUE TITLE
[bug] CONAN_CMAKE_PROGRAM is ignored by conan.tools.cmake.CMake

### ISSUE THREAD

**Issue by ZbigniewRA** [conan-io/conan#11177]
`CONAN_CMAKE_PROGRAM` environment variable is ignored by `conan.tools.cmake.CMake`.

### Environment Details (include every applicable attribute)
  * Operating System+version: Any (tested on Ubuntu 18.04)
  * Compiler+version: Any
  * Conan version: 1.48.0
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)
Set `CONAN_CMAKE_PROGRAM` variable. Observe that it is ignored in `conan install` for packages using `conan.tools.cmake.CMake`.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
export CONAN_CMAKE_PROGRAM=/home/jenkins-node/cmake-3.21.1/bin/cmake
...
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.21 or higher is required.  You are running version 3.10.2
```

Relevant code is in `\conan\conan\tools\cmake\cmake.py`:
```
        self._cmake_program = "cmake"  # Path to CMake should be handled by environment
```

**Comment by franramirez688** [comment]
Hi @ZbigniewRA 

Yes, you're right. New `conan.tools.cmake.CMake` is not using it anymore, and it doesn't even exist in Conan 2.0. I'd try to propose something else to be able to configure this variable.

**Comment by franramirez688** [comment]
Hi @ZbigniewRA 

After discussing the issue, we think that there are two ways to solve this issue (without adding an additional variable like was done in the legacy CMake build helper through the `CONAN_CMAKE_PROGRAM` one):

* Prepend directly the `cmake` path to your current path.
* Prepend the `cmake` path through the `[buildenv]` section in your profile. For instance:
```
        [buildenv]
        PATH=+(path)/Users/myuser/mycmake/bin
```
This is the same case as the `Meson` build helper that we're assuming that the `meson` script should be in the path too.

Closing the issue, but if you have another use case to be discussed don't hesitate to open the issue again or comment it here.
