### ISSUE TITLE
[question] Is there a way to invoke the deploy() method traversing the package dependencies?

### ISSUE THREAD

**Issue by jjcmru** [conan-io/conan#11174]
I like the **deploy**() method, which serves as the self-contained way to deploy a custom set of files of a Conan package.  However, in order to invoke the method to deploy files of each of the dependencies, I, as far as I know, have to call the _conan install_ command for every dependency separately. I wonder whether there is a simpler way to invoke the **deploy**() method of each of its dependencies, simply based on the dependency info in the _conanfile.txt_ or _conanfile.py_.

I understand that **imports**() method will traverse the dependency graph to perform the copy operation based on the file filters. But it requires the knowledge of the internal details of its dependencies to construct the proper file filters

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jjcmru 

No, there is no general way to run the ``deploy()`` method of every recipe in the dependency graph.

Actually, I would like to comment that we have learned that the ``deploy()`` method was not enough for many cases, and we have decided to go another route in Conan 2.0, I can briefly summarize here for some awareness of the close future:
- ``deploy()`` method dissapears
- ``deployers`` are python scripts, that live in the Conan cache, and can be installed with ``conan config install``
- ``deployers`` can be called for any package, and for the full dependency graph, with ``conan install .... --deploy=mydeployer``
- There are a couple of built-in deployers, for common operations

All of this is already released in the 2.0-alpha.6 latest release.

**Comment by jjcmru** [comment]
@memsharded 
Thanks a lot for your explanation. I like what way Conan 2.0 is going. 
Do you know where I can find the Conan programming API document? For example, when I implement conanfile.py, I want to know what is available from the "self" object in Conan space and other environment variables made available by Conan.
Thanks!

**Comment by memsharded** [comment]
Yes, @jjcmru the docs that you need to check is the "reference" section here: https://docs.conan.io/en/latest/reference/conanfile.html
