### ISSUE TITLE
ERROR: Loop detected in context host: 'nvidia_cg/3.1.0013' requires 'nvidia_cg/3.1.0013' which is an ancestor too

### ISSUE THREAD

**Issue by pdigiglio** [conan-io/conan#11187]
I'm making a conan package for NVIDIA's [CG](https://developer.nvidia.com/cg-toolkit-download) precompiled binaries by following the steps in [this page](https://docs.conan.io/en/latest/creating_packages/existing_binaries.html#packaging-pre-built-binaries) of the Conan documentation.

**Note:** I'm posting this issue as a question because I'm not sure it's a bug.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

### Environment Details (include every applicable attribute)
  * Operating System+version: _Windows 10 Pro_
  * ~Compiler+version:~
  * Conan version: 1.46.2
  * Python version: 3.9.12
  * Terminal: _MinTTY 3.6.1 (x86_64-pc-msys) [Windows 19044]_ and _PowerShell_

### Steps to reproduce

Here's what I did.

I created a new recipe:

```
$ conan new nvidia_cg/3.1.0013 --bare --test
File saved: conanfile.py
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/example.cpp
```

After customizing my recipe, I `cd` to the folder where I keep the binary files and call `conan export-pkg` to create the package:
```
$ cd windows/x64/
$ tree
.
+-- bin
¦   +-- cg.dll
¦   +-- cgD3D10.dll
¦   +-- cgD3D11.dll
¦   +-- cgD3D9.dll
¦   +-- cgGL.dll
¦   +-- cgc.exe
¦   +-- cgfxcat.exe
¦   +-- cginfo.exe
¦   +-- glut32.dll
+-- include
¦   +-- Cg
¦   ¦   +-- cg.h
¦   ¦   +-- cgD3D10.h
¦   ¦   +-- cgD3D11.h
¦   ¦   +-- cgD3D9.h
¦   ¦   +-- cgGL.h
¦   +-- GL
¦       +-- glut.h
+-- lib
    +-- cg.lib
    +-- cgD3D10.lib
    +-- cgD3D11.lib
    +-- cgD3D9.lib
    +-- cgGL.lib
    +-- glut32.lib

5 directories, 21 files
$ conan export-pkg ../../conanfile.py nvidia_cg/3.1.0013@ -s os=Windows -s arch=x86_64 -o nvidia_cg:shared=False
Exporting package recipe
nvidia_cg/3.1.0013: A new conanfile.py version was exported
nvidia_cg/3.1.0013: Folder: D:\conan_user_home\.conan\data\nvidia_cg\3.1.0013\_\_\export
nvidia_cg/3.1.0013: Using the exported files summary hash as the recipe revision: d0115b04f4c80e50364c6f0eafa9dba3
nvidia_cg/3.1.0013: Exported revision: d0115b04f4c80e50364c6f0eafa9dba3
nvidia_cg/3.1.0013: Forced build from source
Packaging to ca33edce272a279b24f87dc0d4cf5bbdcffbc187
nvidia_cg/3.1.0013: Generating the package
nvidia_cg/3.1.0013: Package folder D:\conan_user_home\.conan\data\nvidia_cg\3.1.0013\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187
nvidia_cg/3.1.0013: Calling package()
nvidia_cg/3.1.0013 package(): Packaged 6 '.dll' files
nvidia_cg/3.1.0013 package(): Packaged 3 '.exe' files: cgc.exe, cgfxcat.exe, cginfo.exe
nvidia_cg/3.1.0013 package(): Packaged 6 '.h' files
nvidia_cg/3.1.0013 package(): Packaged 6 '.lib' files
nvidia_cg/3.1.0013: Package 'ca33edce272a279b24f87dc0d4cf5bbdcffbc187' created
nvidia_cg/3.1.0013: Created package revision c4e1990e707e29e5ae326d86db8d9f9b
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
```

At this point, I can see the package being created into my data folder. However, when I test my package I get the following error:

```
$ conan test ../../conanfile.py nvidia_cg/3.1.0013@ -s os=Windows -s arch=x86_64 -o nvidia_cg:shared=False
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
nvidia_cg:shared=False
[build_requires]
[env]

ERROR: Loop detected in context host: 'nvidia_cg/3.1.0013' requires 'nvidia_cg/3.1.0013' which is an ancestor too
```

I'm stuck here and I can't figure out what's going on.

My recipe is this:
```py
from conans import ConanFile, tools
from conans.errors import ConanInvalidConfiguration


class NvidiaCgConan(ConanFile):
    name = "nvidia_cg"
    version = "3.1.0013"
    settings = "os", "arch"
    description = ""
    url = "https://developer.nvidia.com/cg-toolkit-download"
    license = ""
    author = ""
    topics = None
    options = {
        "shared": [True, False]
    }
    default_options = {
        "shared": False
    }

    def package(self):
        self.copy(pattern='*.h', src='include', dst='include', keep_path=True)
        self.copy(pattern="*", src="bin", dst="bin")
        if self.settings.os == "Windows":
            if not self.options.shared:
                # Also export .lib files
                self.copy(pattern="*.lib", src="lib", dst="lib")
        else:
            raise ConanInvalidConfiguration(f"Unsupported os: {self.settings.os}. ")

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

I've looked at issue #9599 already but the bug there seems to be related to a user-written function `get_dependencies`, which is not my case.

**Comment by jcar87** [comment]
Hi @pdigiglio and thanks for reporting this issue!!

Looking at the commands you have pasted, there are two `conanfile.py` files:

```
$ conan new nvidia_cg/3.1.0013 --bare --test
File saved: conanfile.py
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/example.cpp
```

One for for the recipe of the package itself, and another one for the test package, which implements the `test()` method. In your case, `conan export` needs to be passed the path to the recipe itself, and `conan test` needs to be passed the path to the `test_package/conanfile.py` file (docs [here](https://docs.conan.io/en/latest/reference/commands/creator/test.html)).

Is there any chance that when you are calling `conan test`, the path to the _recipe_ is being passed, instead of the path to the `conanfile.py` for the _test_ package?

```
conan test ../../conanfile.py nvidia_cg/3.1.0013@ -s os=Windows -s arch=x86_64 -o nvidia_cg:shared=False
                   ^^^^^^^
                          (this should be the `test_package/conanfile.py`)
```

**Comment by pdigiglio** [comment]
Hi @jcar87, thanks to you for your reply.

> Is there any chance that when you are calling `conan test`, the path to the _recipe_ is being passed, instead of the path to the `conanfile.py` for the _test_ package?

That's the issue. I'm sorry I missed that from the help page I linked (and from the one you linked too).

I'm closing this issue.
Thanks very much again.
