### ISSUE TITLE
[question] Why does `conan search --revisions <ref>` require access to the remote?

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#11181]
I can do `conan search --revisions` and it appears (as expected) to be an offline operation just listing the contents of the cache
> xz_utils/5.2.4#0
> zlib/1.2.11#b3eaf63da20a8606f3d84602c2cfa854
> zlib/1.2.12#82202701ea360c0863f1db5008067122

and even `conan search --revisions <pattern>` works, e.g. `conan search --revisions zlib`
> zlib/1.2.11#b3eaf63da20a8606f3d84602c2cfa854
> zlib/1.2.12#82202701ea360c0863f1db5008067122

But if I make it a fully-qualified ref e.g. `conan search --revisions zlib/1.2.12@` it seems to want to connect to the associated remote (which, in this case, requires me to be on VPN)

ERROR: HTTPSConnectionPool(host='repository.deere.com', port=443): Max retries exceeded with url: /artifactory/api/conan/jdps-focus-desktop-tools-conan-local/v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025FCE7DFD00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Yet if I do establish network access, it only shows the revision I have locally, not the other ones available on the remote. It seems weird that filtering to a subset of the information suddenly needs network access that retrieving the whole list did not.

Probably related, it does not seem to be possible to do `conan search --revisions --remote <name>` to get a similar list-with revisions of the remote; am I missing any easy way to find out whether I have locally-cached recipes that are outdated (remote has a newer recipe revision)?

**Comment by AbrilRBS** [comment]
Hi @puetzk sorry for the lack of communication regarding this issue. It came at a time we were focusing on releasing Conan 2, so Conan 1 issues got less atenttion, but we should have had to at least communicate it a bit better (anything at all!)

Closing as no longer relevant in Conan 2, which has explicit behaviour as to where it's looking for in both `conan search` and `conan list`. If no `--remote=foobar` is passed, then the query is considered to be done to the local cache :)
