### ISSUE TITLE
[question] What step can we use parellel

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#11192]
- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

For example, in package step, I want to copy multiple sources to destination, can I use some methods to speed up the package step? As well as source step.

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

There is nothing built-in in Conan to speed up these steps. But those are python methods, you can do very much anything that you would like to do, like running something with ``self.run("your fast copy command")``, or maybe launching threads. 
But in general I think it would not be worth the effort, those steps might not be very fast, but they are done from time to time, mostly in CI, and are still relatively small compared to the slowest build from source step.
