### ISSUE TITLE
[bug] Problem when build with Bitcode enabled

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#11191]
### Environment Details (include every applicable attribute)
  * Operating System+version: macos mont
  * Compiler+version: clang 13
  * Conan version: 1.48
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)

1. Build:
`conan install openssl/1.1.1k@ -c:h tools.apple:enable_bitcode=True  -pr:h conan/profiles/nativium_ios_profile --build`

2. Check: 
`otool -l apps/app_rand.o | grep bitcode`

When check, it need show:

```
  sectname __bitcode
```

The generated compiler command don't include `-fembed-bitcode`:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -I. -Iinclude -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -fno-common -O3 -fPIC -mios-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -arch armv7 -O3 -fPIC -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/4ac31d5d0c1627657f3e62f1b22936dec2100590/res\"" -DENGINESDIR="\"/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/4ac31d5d0c1627657f3e62f1b22936dec2100590/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DNDEBUG  -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
```

Profile:

```
include(default)

[settings]
os=iOS
os.version=9.0
arch=armv7
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
conan install openssl/1.1.1k@ -c:h tool.enable_bitcode=True -pr:h conan/profiles/nativium_ios_profile --build
Configuration:
[settings]
arch=armv7
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=iOS
os.version=9.0
os_build=Macos
[options]
[build_requires]
[env]
[conf]
tool.enable_bitcode=True

openssl/1.1.1k: Forced build from source
Installing package: openssl/1.1.1k
Requirements
    openssl/1.1.1k from 'conancenter' - Cache
Packages
    openssl/1.1.1k:4ac31d5d0c1627657f3e62f1b22936dec2100590 - Build

Cross-build from 'Macos:x86_64' to 'iOS:armv7'
Installing (downloading, building) binaries...
openssl/1.1.1k: WARN: Build folder is dirty, removing it: /Users/paulo/.conan/data/openssl/1.1.1k/_/_/build/4ac31d5d0c1627657f3e62f1b22936dec2100590
openssl/1.1.1k: Copying sources to build folder
openssl/1.1.1k: Building your package in /Users/paulo/.conan/data/openssl/1.1.1k/_/_/build/4ac31d5d0c1627657f3e62f1b22936dec2100590
openssl/1.1.1k: Generator txt created conanbuildinfo.txt
openssl/1.1.1k: Aggregating env generators
openssl/1.1.1k: Calling build()
openssl/1.1.1k: using target: conan-Release-iOS-armv7-apple-clang-13 -> iphoneos-cross
openssl/1.1.1k: my %targets = (
    "conan-Release-iOS-armv7-apple-clang-13" => {
        inherit_from => [ "iphoneos-cross" ],
        cflags => add("-O3 -fPIC -mios-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -arch armv7"),
        cxxflags => add("-O3 -fPIC -mios-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -arch armv7"),
        defines => add("NDEBUG"),
        includes => add(),
        lflags => add(""),
        
        
        
        cc => "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang",
        cxx => "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++",
        ar => "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar",
        ranlib => "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib",
        perlasm_scheme => "ios32",
    },
);

openssl/1.1.1k: ['"conan-Release-iOS-armv7-apple-clang-13"', 'no-shared', '--prefix="/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/4ac31d5d0c1627657f3e62f1b22936dec2100590"', '--openssldir="/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/4ac31d5d0c1627657f3e62f1b22936dec2100590/res"', 'no-unit-test', 'threads', 'PERL=perl', 'no-tests', '--release', '-fPIC']
Configuring OpenSSL version 1.1.1k (0x101010bfL) for conan-Release-iOS-armv7-apple-clang-13
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _all
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -I. -Iinclude -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -fno-common -O3 -fPIC -mios-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -arch armv7 -O3 -fPIC -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/4ac31d5d0c1627657f3e62f1b22936dec2100590/res\"" -DENGINESDIR="\"/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/4ac31d5d0c1627657f3e62f1b22936dec2100590/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DNDEBUG  -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -I. -Iinclude -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -fno-common -O3 -fPIC -mios-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -arch armv7 -O3 -fPIC -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/4ac31d5d0c1627657f3e62f1b22936dec2100590/res\"" -DENGINESDIR="\"/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/4ac31d5d0c1627657f3e62f1b22936dec2100590/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DNDEBUG  -MMD -MF apps/apps.d.tmp -MT apps/apps.o -c -o apps/apps.o apps/apps.c
```

**Comment by memsharded** [comment]
Hi @paulocoutinhox 

This is expected, if you are using ``openssl/1.1.1k@`` recipe from ConanCenter, those recipes have not still updated to use the new Conan 1.48, neither to use the new build system integrations, which are the ones that implement the logic for those ``conf`` flags  like ``tools.apple:enable_bitcode=True``. 

So this doesn't seem a Conan issue, I think we can close it and we should wait for ``conan-center-index`` to catch up

**Comment by paulocoutinhox** [comment]
Hi,

I have problem with other recipes too:
https://github.com/conan-io/conan-center-index/issues/10961

What can i do to help?

Thanks.

**Comment by franramirez688** [comment]
Hi @paulocoutinhox 

The problem is exactly the same as @memsharded said above (https://github.com/conan-io/conan/issues/11191#issuecomment-1120301634).
Those recipes are using legacy generators instead of `CMakeToolchain` which is the new one that contains this _bitcode_ logic.

To see how it works, you can try it easily by creating your own _mytest_ recipe and running the `conan create`:

```bash
$ mkdir conan_test && cd conan_test
$ conan new mytest/1.0 -m cmake_lib
$ conan create . -c tools.apple:enable_bitcode=True
```
That `mytest/1.0` recipe is using the new generators (including the `CMakeToolchain` one):
```python
    # ...
    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
```
Checking the library created now:

```bash
$ otool -l [PATH_TO_CONAN_DATA_LIB]/libmytest.a | grep bitcode
  sectname __bitcode
```
And there it is.

**Comment by paulocoutinhox** [comment]
Hi,

I understand, but have anything that we can do to improve it?

Without a solution, i will need still use my own toolchain:
https://github.com/nativium/nativium/blob/main/conan/darwin-toolchain/conanfile.py#L128-L131

How we can improve conan?

Thanks.

**Comment by memsharded** [comment]
> How we can improve conan?

For sure, keep the feedback coming :) 

The solution is there, and seems to be working good, with the new integrations. So the challenge will be to modernize the recipes in ConanCenter to use the new tools, and for sure the best way is to contribute to the ``conan-center-index`` repository. Forking the repo, trying to modernize recipes that you might depend on, and then doing either:

- Report here in this repo, if something in the new tools is not working as expected
- Contribute the changes to ConanCenter if the recipe works fine with the changes.

ConanCenter is a bit behind the Conan release, so features like ``Bitcode`` might still not be available in ConanCenter. But the challenge is to move things to ``CMakeToolchain``, once that it is done, it will be as easy as updating the Conan version to enjoy this new feature.

**Comment by paulocoutinhox** [comment]
Hi,

There is any update to conan itself that will fix this for every package?

To you understand, my projects https://github.com/nativium/nativium and https://github.com/ezored/ezored is used by many users, so i don't know what everybody uses. There is something that fix it for all?

For example, i use `openssl` and it's recipe was modernized, but don't accept conan bitcode configuration:
https://github.com/conan-io/conan-center-index/tree/master/recipes/openssl

Im still using my toolchain until it be fixed definitively.

I will keep this issue opened to test when things move.

Thanks.

**Comment by paulocoutinhox** [comment]
Hi,

This is solved? Any update to this @memsharded?

Thanks

**Comment by memsharded** [comment]
Hi @paulocoutinhox 

No, the recipe for openssl still hasn't been modernized with the new build helpers that take into account this configuration.
You can see it from the ``from conans import ConanFile, AutoToolsBuildEnvironment, tools``. All the new integrations are in ``from conan.tools.xxx`` (note the singular)

**Comment by paulocoutinhox** [comment]
Hi @memsharded,

This only replace is enough?

Thanks.

**Comment by paulocoutinhox** [comment]
Hi @memsharded,

With the dependencies with conan v2 support this flags will work?

Thanks.

**Comment by memsharded** [comment]
Hi @paulocoutinhox 

You mean the new added confs?
```
"tools.apple:enable_bitcode": "(boolean) Enable/Disable Bitcode Apple Clang flags",
    "tools.apple:enable_arc": "(boolean) Enable/Disable ARC Apple Clang flags",
    "tools.apple:enable_visibility": "(boolean) Enable/Disable Visibility Apple Clang flags",
```

Yes, they have been designed and added to stay in 2.0 too.

**Comment by paulocoutinhox** [comment]
I mean all the dependencies. With v2 and all dependencies converted to conan v2, will support these flags?

**Comment by memsharded** [comment]
That is the idea. We implement those confs in our built-in build system integrations. Still ConanCenter recipes sometimes are deviating from those built-in integrations and doing their own stuff, typically to workaround weird build system setups. It will be the responsibility of the recipes to correctly implement these ``confs`` mapping from Conan conf to the package build system, and some recipes might occasionally fail to do so, but that should be reported to the specific recipes in ConanCenter.

**Comment by paulocoutinhox** [comment]
Thanks, i will wait all the recipes be updated to remove it from my project.
