### ISSUE TITLE
[develop2] Implement a json formatter for conan commands

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#11198]
It would be useful in ci to get certain information for commands like `export`, `create`... with a json output that provides information like: created recipe revision, package id, package revision...

Let's begin with `conan export` that should be straightforward, then consider adding for other commands.

TODO:

- [X] conan export .. --format json
- [x] conan create .. --format json
- [x] conan install .. --format json
- [x] conan export-pkg .. --format json

**Comment by memsharded** [comment]
Partially implemented by https://github.com/conan-io/conan/pull/11427

Lets do the same for ``conan install``, ``conan export-pkg`` commands too for beta-2

**Comment by franramirez688** [comment]
Closed by https://github.com/conan-io/conan/pull/11548
