### ISSUE TITLE
[question] Is it possible in conan v2 to encode in a recipe that version of a specific tool_requires can be overridden?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11193]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

When a library has a requirement like `protobuf` and uses `protoc` executable at build time to generate source code from `.proto` files, `protobuf` version in `requires` and `tool_requires` must be the same, and if version is overridden by downstream (even patch version), this recipe should generate a new package id and override `protobuf` version in tool_requires, not only requires.
AFAIK, there is no way to achieve such logic in conan v1. Is it possible in conan v2? Is it possible to encode this behavior in a recipe so that it can work out of the box for consumers?

For example:

```python
from conans import ConanFile

class FooConan(ConanFile):
    name = "foo"
    version = "1.0.0"

    def requirements(self):
        self.requires("protobuf/3.20.0")

    def build_requirements(self):
        self.tool_requires("protobuf/3.20.0") # here an option could tell that this version must always follow the one in requires

    def package_id(self):
        # some logic to always encode protobuf version in package id regardless of user policy
```

```python
from conans import ConanFile

class BarConan(ConanFile):
    name = "bar"
    version = "1.0.0"

    def requirements(self):
        self.requires("foo/1.0.0")
        self.requires("protobuf/3.19.0", override=True)
```

`conan install bar/1.0.0 -b missing` would trigger a new build of foo/1.0.0 package, with a different package id than the one relying on protobuf/3.20.0, where protobuf is 3.19.0 in tool_requires.

**Comment by SpaceIm** [comment]
It seems quite similar than https://github.com/conan-io/conan/issues/11010 (but it's not exactly the same problem, it's closer to https://github.com/conan-io/conan/issues/11010#issuecomment-1108859548)

**Comment by memsharded** [comment]
Please see the test in https://github.com/conan-io/conan/pull/11194. In summary:

Conan 2.0 allows overriding of upstream tool_requires, for that to happen:
- The package using that tool_require should declare it as ``visible=True``, so the downstream has visibility over them
- The downstream consumer can do a ``self.requires(..., override=True, build=True, headers=False, libs=False)`` (this UX could be improved allowing ``self.tool_requires(..., override=True)``, but that is just a easy syntax improvement)
- The evolution of host and build requires is still independent, if you want to override both, you need to override both explicitly.

**Comment by memsharded** [comment]
Any feedback for https://github.com/conan-io/conan/pull/11194? this is planned to be merged soon, and it will close this ticket as solved.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/11194, which verifies that ``tool_requires("pkg/0.1", visible=True`` can be overriden from dowstream with ``tool_requires("pkg/0.2", override=True)``
