### ISSUE TITLE
Extract linked library dependency information from CMake

### ISSUE THREAD

**Issue by azriel91** [conan-io/conan#112]
CMake already knows what libraries should be transitively linked when linking a target. For existing libraries this would include OS-dependent linker flags etc. I would like to not have this information duplicated in the `conanfile`, as it is easy to miss updating one and not the other; or for out-of-source-conanfile projects, you have to keep up to date with the build scripts which is not fun.

I nearly managed to make conan extract that information from the build directory, write it to a file, and package up that file, so that when running `conan install`, it can read this file and add it to the `cpp_info.libs` during the `package_info` method.

However it fails because [`package_info` is run](https://github.com/conan-io/conan/blob/dc532d47ffdb8096a30069238c6024a1ce0ca910/conans/client/installer.py#L69) [before building](https://github.com/conan-io/conan/blob/dc532d47ffdb8096a30069238c6024a1ce0ca910/conans/client/installer.py#L71).

It probably makes sense to do it in that order, but conan should be able to do the linked library extraction without users having to munge it in `conanfile.py`

Here was my attempt:
1. Extract the dependency information from cmake:
   
   ``` python
   # conanfile.py
   
       build_dir = 'build'
       linked_libraries_filename = 'cppmicroservices_linked_libraries.txt'
   
       def build(self):
           if not os.path.isdir(self.name):
               self.source()
           option_defines = ' '.join("-D%s=%s" % (option, val) for (option, val) in self.options.iteritems())
           self.run("cmake {src_dir} -B{build_dir} {defines}".format(src_dir=self.name,
                                                                     build_dir=self.build_dir,
                                                                     defines=option_defines))
           self.run("cmake --build {build_dir}".format(build_dir=self.build_dir))
   
           linked_libraries_file_path = "{conan_dir}/{build_dir}/{filename}".format(conan_dir=self.conanfile_directory,
                                                                                    build_dir=self.build_dir,
                                                                                    filename=self.linked_libraries_filename)
           with open(linked_libraries_file_path, 'w') as linked_libraries_file:
               linked_libraries_file.write('\n'.join(self._get_linker_libraries()))
               linked_libraries_file.close()
   
       def _get_linker_libraries(self):
           # Extract dependencies for the CppMicroServices library, to be appended to self.cpp_info.libs
           # See http://stackoverflow.com/a/31940106/1576773
           self.run("cmake --graphviz={build_dir}/cppmicroservices.dot {build_dir}".format(build_dir=self.build_dir), False)
   
           dependencies = None
           try:
               output_deps = cStringIO.StringIO()
               command = "sed -n 's/.*label=\"\\(.*\\)\"\\s.*/\\1/p' {build_dir}/cppmicroservices.dot.{lib}".format(build_dir=self.build_dir,
                                                                                                                    lib=self.name)
               self.run(command, output_deps)
               dependencies = output_deps.getvalue().split()
           finally:
               output_deps.close()
               self.run("rm -f {build_dir}/cppmicroservices.dot*".format(build_dir=self.build_dir))
           return dependencies
   ```
2. Package it in `package`:
   
   ``` python
       def package(self):
           # Linked libraries file
           self.copy(self.linked_libraries_filename, dst='.', src=self.build_dir)
   ```
3. Read it in `package_info`:
   
   ``` python
       def package_info(self):
           linked_libraries_file_path = "%s/%s" % (self.cpp_info.rootpath, self.linked_libraries_filename)
           # FAILS HERE
           with open(linked_libraries_file_path, 'rb') as linked_libraries_file:
               # Warning: This reads the whole file into memory, but we expect it to be small
               self.cpp_info.libs = linked_libraries_file.read().split()
   ```

**Comment by azriel91** [comment]
Updated previous post (code was incorrect in some places).

Implementation can be seen at [CppMicroServices-conan/conanfile.py](https://github.com/azriel91/CppMicroServices-conan/blob/retrieve-linked-libraries-from-cmake/conanfile.py).

`cppmicroservices_linked_libraries.txt` is correctly generated and packaged, but running `conan info` would cause it to fail if the appropriate lines are uncommented.

**Comment by lasote** [comment]
Hi, 
I understand the problem, it's not the first time that almost the same issue is reported.
The package_info information is propagated in the build graph before build, and when all graph is processed conan calls build method in the nodes with the propagated information. I think the only way to fix this problem should be process the graph in order and building the nodes before calculate the entire info. But I'm sure this way can appear other problems. Maybe @memsharded have a better overall vision about that.

Anyway, I'm agree that duplicate dep library names in conanfile and cmake is not a good thing but:

1. In many cases those libraries you link against will be another conan requires, if don't there are just very common system libraries like maybe -lm or -lpthread.
2. The problem of forget updating the conanfile.py when your library has new deps won't be often I think, and can be easily fixed integrating the test folder with a good set of test.

**Comment by memsharded** [comment]
This issue has been addressed. 
From conan 0.13, the ``package_info()`` is run **after** the package, so it can scan the directory for library names.

Furthermore, it is also possible to use the ``cmake install`` to implement the ``package()`` method, so things doesn't have to be repeated.

So marking this as fixed, and closing, but please re-open if necessary. Thanks!
