### ISSUE TITLE
[bug] CMakeDeps generates a MODULE require instead of CONFIG

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#11201]
See other bug report below,
a simple project requiring Freetype will fail as Freetype will call
find_dependency(brotli REQUIRE MODULE),
but brotli does not have a MODULE finder, only a CONFIG finder.

> RE my comment, "it isn't so simple as disabling that flag"
> 
> For my example, if you do a conan install, and then comment out that flag, it does find Freetype::Freetype, but it then fails to find Brotli (looking for Findbrotli.cmake)
> 
> ```
> CMake Error at /build/msrap2/devenv/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):                                                                                                    
> No "Findbrotli.cmake" found in CMAKE_MODULE_PATH.
> Call Stack (most recent call first):
> build/FindFreetype.cmake:25 (find_dependency)
> CMakeLists.txt:5 (find_package)
> 
> FindFreetype.cmake:25 is:
>        find_dependency(${_DEPENDENCY} REQUIRED ${${_DEPENDENCY}_FIND_MODE}) 
> which ends up calling
> find_package(brotli REQUIRED;MODULE)
> ```

Seems to be a bug in `CMakeDeps`, and it should be reported to conan client. It doesn't make sense that `CMakeDeps` generate a module file for `freetype` recipe calling `find_dependency(brotli REQUIRED MODULE)`, since `brotli` recipe doesn't have `cmake_find_mode` set to `both`. It should call `find_dependency(brotli REQUIRED CONFIG)`.

_Originally posted by @SpaceIm in https://github.com/conan-io/conan-center-index/issues/10687#issuecomment-1120980081_

**Comment by paulharris** [comment]
I have narrowed this down further.
Note this is in combination with this bug:
#10387 Desire to remove CMAKE_FIND_PACKAGE_PREFER_CONFIG ON
I am using profile: [conf] tools.cmake.cmaketoolchain:find_package_prefer_config = False to force this behaviour.  It is required, as described in other bugs.

[See conan.tools.cmake.utils.get_file_name() ](https://github.com/conan-io/conan/blob/81ac7d7905897c1487404f5431e48f3172822fe6/conan/tools/cmake/utils.py#L10-L19)
It accepts a parameter "forced_module_mode", which is only used once in the conan code.
This function will return the MODULE filename (cmake_module_file_name) when the dependency uses find_mode=MODULE, or forced_module_mode=True

Lets look at Fontconfig, which includes Freetype *as a module*, which then depends on libuuid.
libuuid is a very simple module, and does *not* declare a cmake_find_mode at all.  It implicitly assumes it will be imported via CONFIG.
KEY POINT: Freetype import => MODULE,    libuuid => CONFIG.

[See conan.tools.cmake.cmakedeps.templates.target_data._get_dependencies_find_modes()](https://github.com/conan-io/conan/blob/81ac7d7905897c1487404f5431e48f3172822fe6/conan/tools/cmake/cmakedeps/templates/target_data.py#L179-L198)
This function will call get_find_mode() and get_file_name().
get_file_name() will call get_find_mode() internally.
Both need to return consistent results for importing as CONFIG, or importing as MODULE.

-----

As the code stands now, we are not setting forced_module_mode for get_file_name(), so:
When Fontconfig imports Freetype:
get_find_mode() --> returns "both".
  In get_file_name(), find=both() will result in the CONFIG filename (cmake_file_name)
  In _get_dependencies_find_modes(), "both" results in "default".
What is "default"?  Fontconfig is importing as a MODULE, so self.find_module_mode == True, so default = "MODULE".
Which results in Fontconfig importing Freetype inconsistently:
find_package(freetype MODULE)

------

If I adjust the code, and change ALL calls to get_file_name() to:
get_file_name(dep, forced_module_mode=self.find_module_mode)
Then we get the correct result for Freetype,
get_find_name() will return the MODULE filename (due to the forced flag),
and "default" will translate to MODULE (same as before),
so we get
find_package(Freetype MODULE)

------

However, it doesn't work for libuuid (required by Freetype)
Freetype is importing as a MODULE, but even with the force-flag,
get_file_name() will return cmake_file_name, as libuuid does not have cmake_module_file_name.
so, filename --> CONFIG style.
For libuuid, get_find_mode() returns None, as libuuid does not declare cmake_find_mode at all.
"None" translates to default_value, as per the comment:
`When the dependency is "both" or not defined, we use the one is forced by self.find_module_mode (creating modules files -> modules, config -> config)`

However, this means we get a MODULE find mode mixed with a CONFIG style.
ie find_package(libuuid MODULE)
And the find_package() will fail.

KEY POINT: It is wrong to assume a find mode when a package does not explicitly declare a mode.

------

So, what to do ...

We could assume "None" means "use CONFIG" aka NO_MODULE.  This would be correct for libuuid, not sure about others.

We could assume "None" means "FIND_MODE_NONE".
We don't want this, it won't generate any find-files, and the package will be located "externally" (ie /usr/include I suppose).

We could throw an error if `cmake_find_mode` is not explicitly defined by a package.

Or, what I've done to try, is to guess based on the existence of cmake_file_name and cmake_module_file_name.
I don't know if this is correct, and I don't like guessing (I'd rather be strict), but I don't have the capacity to run a test on all the packages at this time, to check how many packages are missing the declaration.

Running tests now, posting before I lose this text.

**Comment by paulharris** [comment]
Further to this, with these changes, a Boost consumer MUST include boost like so:
find_package (Boost CONFIG)
as the package name has a capital letter, so CMake assumes it is a MODULE,
but the boost package only generates CONFIG mode, no MODULE finders.

So I feel like the Boost package is doing the wrong thing here.
Correct?

**Comment by paulharris** [comment]
Sorry again, I've tested further and the problem still exists.
I've created a PR to make it easier to test the problem.

Test case: conan-io/conan-center-index#10825
Discussion on the reasons behind the bug: conan-io/conan#11201
My proposed fix: conan-io/conan#11217

**Comment by paulharris** [comment]
@jcar87 I've been using unpatched conan 1.48.1 for a while now, all working :)

So I think we can close this issue off.  Thanks!

**Comment by jcar87** [comment]
HI @paulharris! Thanks for trying out the new release and for your feedback!

This issue has also uncovered https://github.com/conan-io/conan/issues/11261, which still affects the ability to consume Fontconfig  (as per your [PR](https://github.com/conan-io/conan-center-index/pull/10825) here) from conan center with the generated module (instead of a package) - although mileage may vary depending on whether or not the filesystem is case sensitive and the transitive dependencies have different names or not.

**Comment by paulharris** [comment]
Ok good, I've found all this uppercase/lowercase stuff is full of possible stuff-ups for the poor programmer.
I wish we could alert/error/warn/explode when someone uses find_package(WronGcase) or even, in cmake, if (WRONGcapiTals)
Especially when some packages are lowercase, some are upper, and some change from one to the other...  Too much is implied...

**Comment by jcar87** [comment]
Yeah I think there's two things that could help:
* on case-insensitive filesystems, CMake itself will issue a warning when you call `find_package(SomeCase)` but the set `_FOUND` variable of the found package does not match the name `find_package` was called with. 

* Once we have a fix for this: https://github.com/conan-io/conan/issues/11263 - if any transitive dependency is found with the wrong name, the first call to `find_package` will result in the package not being found - so this will be a cmake error now (if it was called with `REQUIRED`). However on case sensitive filesystems I believe there won't be many hints as to why this happened.

Having recipes that set the module and the config names to _different_ values (including different case conventions) can ultimately lead to diamond dependency problems that cannot be solved. When there are conflicting conventions with regards to the name of the package (or the targets they generate), this gets in the way of having a set of packages that are self-consistent.  Maintaining two conventions simultaneously will be problematic even if conan tries to do the right thing.

**Comment by paulharris** [comment]
I haven't absorbed everything, so I'll show my ignorance here...

it sounds like the ol' problem of requesting a CONFIG and getting the MODULE finder, or vice versa.
If you find_package(configname) and end up in the module finder, or vice versa, could the finder check the name of what was passed to find_package?  And then fail (or do something else)?
I'd rather fail-fast myself, if the consuming CMakeLists.txt needs to be fixed, it should be very obvious what is wrong and why...

If it is a case-insensitive file system, then the finder should perhaps return a "nothing to see here" if it detects it was found incorrectly...  then hopefully cmake will look for the other-case-style files?

re recipes with different values - isn't that very common practice currently?
