### ISSUE TITLE
[feature][develop2] Review ``conf`` separation for "core" and "tools"

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11205]
We need to review the ``conf`` separation for ``core.xxxx`` and ``tools.xxx``.
For example, for computing the package_id, we have:

```
unknown_mode = new_config.get("core.package_id:default_unknown_mode", default="semver_mode")
    non_embed_mode = new_config.get("core.package_id:default_non_embed_mode", default="minor_mode")
    # recipe_revision_mode already takes into account the package_id
    embed_mode = new_config.get("core.package_id:default_embed_mode", default="full_mode")
    python_mode = new_config.get("core.package_id:default_python_mode", default="minor_mode")
    build_mode = new_config.get("core.package_id:default_build_mode", default=None)
```
Initially it meant that ``core`` could only be defined in ``global.conf`` but apparentely not anymore:

- Check what happens when ``core.xxxx`` conf is defined in cli or profiles
- What happens when both "build" and "host" profile define the same ``core`` conf
- Check that ``tools.xxxx`` confs also work in ``global.conf``

**Comment by franramirez688** [comment]
> * Check what happens when core.xxxx conf is defined in cli or profiles

* If `core` is defined directly in profiles, it raises an exception: `ERROR: Error reading 'profile2' profile: [conf] 'core.xxxxxxxxx' not allowed in profiles`.
* If `core` is defined via cli, it works but it's overriding the `global.conf` value (if exists):

**global.conf**
```bash
core.build.flags:ccflags=["-Wall"]
core.whatever=XXXXX
```
Running: `conan install . -c "core.build.flags:ccflags+=-Werror"  -c "core.build.flags:ccflags+=-XXXX"'`
Result:
**Profile host**
```
[settings]
.......
[conf]
core.build.flags:ccflags=['-Werror', '-XXXX']
core.whatever=XXXXX
```

> * What happens when both "build" and "host" profile define the same core conf

As I said before, it only works via cli and overriding the value:

**global.conf**
```bash
core.build.flags:ccflags=["-Wall"]
core.whatever=XXXXX
```
Running: `conan install . -c:h "core.build.flags:ccflags+=-Werror"  -c:h "core.build.flags:ccflags+=-XXXX"' -c:b "core.build.flags:ccflags+=-NEW"'`

Results:
**Profile host**
```
[settings]
.......
[conf]
core.build.flags:ccflags=['-Werror', '-XXXX']
core.whatever=XXXXX
```

**Profile build**
```
[settings]
.......
[conf]
core.build.flags:ccflags=['-NEW']
core.whatever=XXXXX
```

> * Check that tools.xxxx confs also work in global.conf

Exactly, it works as profiles flow:

**global.conf**
```bash
tools.build.flags:ccflags=["-Wall"]
```
Running: `conaninstall . -c:h "tools.build.flags:ccflags+=-Werror"  -c:h "tools.build.flags:ccflags+=-XXXX" -c:b "tools.build.flags:ccflags+=-NEW"'`

Results:
**Profile host**
```
[settings]
.......
[conf]
tools.build.flags:ccflags=['-Wall', '-Werror', '-XXXX']
```

**Profile build**
```
[settings]
.......
[conf]
tools.build.flags:ccflags=['-Wall', '-NEW']
```

**Comment by memsharded** [comment]
Have you tested that those ``core`` values are actually used in the application?
I think they will not, it seems there is a hole in the CLI that allows defining them, without erroring, but I am not sure they will be effective in the Conan internal code, which would be confusing.

**Comment by franramirez688** [comment]
If I got it correctly, yes, the application considers those ones. For example, I changed one configuration in `CMakeToolchain` so I named it `core.build:defines`. If I pass a new value via CLI, the result is that the generator is using that value internally.

**Comment by memsharded** [comment]
But ``core`` configurations are to be read in the Conan internals, not in recipes. Yes, it will be visible for recipe code, but not for those internals. You can try with ``"core:required_conan_version"``. The thing is that in 2.0 there are way more ``core`` ones than in 1.X, so it might become relevant.

**Comment by franramirez688** [comment]
Oh, yes, you're right. Those cases are not being considered.

**Comment by franramirez688** [comment]
Closing this. Superseded by https://github.com/conan-io/conan/issues/11346
