### ISSUE TITLE
Class "model.Username" does not allow to use names in format "User.Name"

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#1121]
There is an error when I try to enter username

```
conan upload -r my_server "MyPackage*/*"
Enter.... : User.Name
Error ...
```

**Comment by memsharded** [comment]
Yes, that is true, the regex restrict it. Seems an inconsistency/bug, but we have to check, maybe there is some other constraint to be taken into account (@lasote ?)
Besides entering the user name, were you allowed to create a package with a "." in it? Were you allowed to create a conan.io user with a dot in it?

**Comment by DmitrySokolov** [comment]
I am trying to use LDAP to authenticate users. 
I do not use packages with a "." in them.

**Comment by memsharded** [comment]
cc/ @uilianries , who had the basics for Ldap auth, now they could be put in a plugin with new conan 0.21 authentication plugins.

Will check about the "." criteria when possible, thanks for reporting.

**Comment by uilianries** [comment]
Hi there!

I have started LDAP support here: https://github.com/uilianries/conan/tree/feature/ldap

Regards.

**Comment by memsharded** [comment]
Hi @DmitrySokolov 

We have had a look to this issue, and it is good as-is. Usernames shouldn't contain dots. This can produce problems with integration with other systems, so we think it is much better to keep this restriction for usernames.

It might be necessary to improve the consistency of the application of this restriction, we have added it for next release: https://github.com/conan-io/conan/issues/1125. Thanks!
