### ISSUE TITLE
[question][develop2] Review encodings auto detection with BOM

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11228]
Something that I think is worth reviewing is the following:

```python
def _detect_encoding(text):
    import codecs
    encodings = {codecs.BOM_UTF8: "utf_8_sig",
                 codecs.BOM_UTF16_BE: "utf_16_be",
                 codecs.BOM_UTF16_LE: "utf_16_le",
                 codecs.BOM_UTF32_BE: "utf_32_be",
                 codecs.BOM_UTF32_LE: "utf_32_le",
                 b'\x2b\x2f\x76\x38': "utf_7",
                 b'\x2b\x2f\x76\x39': "utf_7",
                 b'\x2b\x2f\x76\x2b': "utf_7",
                 b'\x2b\x2f\x76\x2f': "utf_7",
                 b'\x2b\x2f\x76\x38\x2d': "utf_7"}
```

We are using the BOM in ``decode_text()`` to detect the encoding. It feels a bit too magic for me.

**Comment by SSE4** [comment]
there is no magic, everything is straighforward. just read BOM to determine the text file encoding, then use it to properly decode the file.

**Comment by memsharded** [comment]
I disagree that such a code have to be used in the ``decode_text()`` helper that is used mainly in the Conan HTTP Api, because the encoding shouldn't be detected from BOMs, but it should be already defined by the protocol (utf-8). Also when loading Conan files (conaninfo.txt, conanmanifest.txt, etc...) which would be the majority of cases, same, we should define the encoding of those files (utf-8) and respect it.

So for most usages, this shouldn't be detected. In which cases this auto-detection is necessary?

**Comment by SSE4** [comment]
that's to be defined where to apply on case by case basis in the codebase.
if it's a file downloaded from HTTP (`conanmanifest.txt`?), then encoding should be obtained from HTTP headers (`Content-Type`, `charset`). it could be also defined by the protocol, but specifying `Accept` and/or `Accept-Charset` might be needed to enforce it to be compatible with all HTTP servers.
if it's a file created/edited by user (`conanfile.txt`, `profile`, `settings.yml`, `conan.conf`, etc.), then it could be in an arbitrary encoding, depends on user's system and text editor (e.g. on Windows systems certain editors, like `notepad.exe`, tend to default to UTF16LE with BOM). removing a detection here may result in a massive breakage and complaints about conan misreading a configuration.
if it's a machine-writable file, which is not expected to be edited by user in a majority of cases (`lockfile`, `metadata.json`, `conaninfo.txt`, etc.), conan probably is aware of the encoding it uses to create these files.

**Comment by czoido** [comment]
As a note, this comes from:
https://github.com/conan-io/conan/issues/5504

**Comment by memsharded** [comment]
Let's do an attempt to clean this, see what would break, try different scenarios, like a conanfile.py/.txt with different encodings, see what breaks and how, etc.

**Comment by SSE4** [comment]
I am not sure what to clean, where is just one function, not sure if it can be reduced 🤔 
the test trying few different `conanfile.txt` encodiings (UTF8, UTF8BOM, UTF16LE, UTF16BE) already exists: https://github.com/conan-io/conan/pull/5506/files#diff-a1619b72518081b56c2b1f4206affc2403b09b83bcdb80415079844ae977c74cR11
you may try commenting out lines https://github.com/conan-io/conan/pull/5506/files#diff-a1a04cdac76067761287a688f6d467bfce0da4f08dd1ac24f23cd367c8b99f14R59-R75 and see if test still passes
if it doesn't, it will be a breakage for users

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11384
