### ISSUE TITLE
[question] Is there a regular pattern for global target?

### ISSUE THREAD

**Issue by Kidsunbo** [conan-io/conan#11225]
Hi, I use `CMakeDeps` and `CMakeToolchain` generators for a CMake project with `boost/1.78.0`. For conan installed boost, it has a global target `boost::boost`. But for the one not installed with conan, there isn't.

Is this global target imports all the built components by default? Unlike `Boost::boost`, which is only an alias of `Boost::headers`.

Is this target provided for convenience? Even though I prefer this target, but it seems to be provided by Conan only. I still want my project can be used by consumers with/without Conan. So should I use normal target which original `boost` brings for this purpose?

And I notice that for most libraries, the global target is `<project_name>::<project_name>` or `<project_name>::<library_name>`. But for `glfw3`, the gloabl target is only `glfw`. Is there a regular pattern for global target? Or maybe I need to read `use it` for global target everytime I use it.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> Is this target provided for convenience? Even though I prefer this target, but it seems to be provided by Conan only. I still want my project can be used by consumers with/without Conan. So should I use normal target which original boost brings for this purpose?

Exactly, this is for convenience. If you want your code to still be used without installing Boost with Conan, then you shouldn't be  using this target.

> And I notice that for most libraries, the global target is <project_name>::<project_name> or <project_name>::<library_name>. But for glfw3, the gloabl target is only glfw. Is there a regular pattern for global target? Or maybe I need to read use it for global target everytime I use it.

Yes, the recipe itself defines its names, to be as close as possible to the "upstream" names (target and file names provided by Cmake or the library itself). There is no official pattern, this is up to each project convention. Conan only tries to follow their naming.

**Comment by Kidsunbo** [comment]
> > Is this target provided for convenience? Even though I prefer this target, but it seems to be provided by Conan only. I still want my project can be used by consumers with/without Conan. So should I use normal target which original boost brings for this purpose?
> 
> Exactly, this is for convenience. If you want your code to still be used without installing Boost with Conan, then you shouldn't be using this target.
> 
> > And I notice that for most libraries, the global target is <project_name>::<project_name> or <project_name>::<library_name>. But for glfw3, the gloabl target is only glfw. Is there a regular pattern for global target? Or maybe I need to read use it for global target everytime I use it.
> 
> Yes, the recipe itself defines its names, to be as close as possible to the "upstream" names (target and file names provided by Cmake or the library itself). There is no official pattern, this is up to each project convention. Conan only tries to follow their naming.

Thanks. That makes sense.

**Comment by Kidsunbo** [comment]
Hi @memsharded 
I've noticed that for `CMakeDeps` generator, if `cmake_target_name` and `cmake_file_name` are missing in `package_info` method. The `cmake_target_name` will be default to `<project_name>::<project_name>` and `cmake_file_name` will be `<project_name>`.
Is this guarenteed or just a behaviour of current version?

**Comment by Kidsunbo** [comment]
I've found the source code for default name. https://github.com/conan-io/conan/blob/e8237a0981158ea7a7bce7153acefced7905f677/conan/tools/cmake/cmakedeps/templates/__init__.py#L79
Is this the right place to give out the default target name and file name?
