### ISSUE TITLE
[question] Do stuff in`imports` only when the recipe changes

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#11230]
When calling `conan install`, is there a way to obtain the path to the current `conanfile.py` inside `imports` function?

We would like to hash the `conanfile.py` and compare it to some hash on the disk (inside imports folder) to only do extensive **imports** copy operations if the `conanfile.py` has changed.
Could we use `self.info.package_id()`  which should also change when someone modifies requirements?
So far `self.info.package_id()` does not change in `imports`.

**Comment by memsharded** [comment]
I think the ``self.recipe_folder`` is always defined within a ``conanfile.py``, have you tried that one?

**Comment by memsharded** [comment]
The ``imports()`` method has been made legacy in Conan 1.X by explicit ``copy()`` in ``generate()`` and removed in Conan 2.0. Closing this ticket, please create new tickets as necessary, thanks!
