### ISSUE TITLE
Server backward compability

### ISSUE THREAD

**Issue by kolis** [conan-io/conan#1123]
Do you have some kind of policy on backward compability? I uploaded a new package from a `0.20.3` client to a `0.19.2` server, without any apparent error. But when searching for the package using `conan search` the new package was not listed. I spent some time debugging this and finally I noticed that the `conaninfo.txt` has a new entry, the `[env]` section. If I remove this then the package show up.

This was a bit frustrating to troubleshoot.

Full backward compability is definitely preferred, but I understand that sometimes it is hard to maintain. But then it would be very helpful to get some error message from the server during upload.

**Comment by lasote** [comment]
Hi @kolis 
I understand your concerns, we always try to keep the compatibility but sometimes is hard to control everything and the future changes. In that case we couldn't manage to solve the incompatibility, we announced that problem in the changelog of 0.20.0. http://docs.conan.io/en/latest/changelog.html

```
0.20.0 (27-February-2017)
NOTE: It is important that if you upgrade to this version, all the clients connected to the same remote, should upgrade too. Packages created with conan>=0.20.0 might not be usable with conan older conan clients.
```
