### ISSUE TITLE
CMake warns about unused CONAN_EXPORTED flag

### ISSUE THREAD

**Issue by fjcalzado** [conan-io/conan#1124]
The current behaviour regarding Issue #888 is:

`CONAN_EXPORTED` flag is added by default in `cmake.command_line`, and thus, everytime I run a `conan install` command I get CMake throwing the following warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CONAN_EXPORTED
```
which is forcing me to a fake use CONAN_EXPORTED flag in CMake just to hide the warning, eventhough I really do not need that flag.

Could you add any `CONAN_EXPORTED` flag usage in `conanbuildinfo.cmake` to avoid this warning?

**Comment by lasote** [comment]
It has been released in conan 0.22.0. Report with any problem, thanks!
