### ISSUE TITLE
[question] Is it possible to call conan 2.0 install without a profile?

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#11257]
I'm trying to employ functionality of `conan_cmake_autodetect(settings)`, conan says that i need a default profile in order to run `install`, however, all needed parameters are passed into `install` command inline, so there's no need in a profile

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**UPD**  
I've created an empty default profile  
```ini
[settings]
[options]
[tool_requires]
[env]
```
And it seems conan allows me to use it

**Comment by memsharded** [comment]
Both Conan 1 and Conan 2 require a profile, if not specified in the command line. The difference is that Conan 2 will not automatically create a default profile if it doesn't exist, requiring an explicit ``conan profile detect`` command.

**Comment by xahon** [comment]
I mean that maybe it would be better to allow profileless run of conan allowing user to set all the arguments via CLI. I have a profile that is nearly empty (only os and os_build are there now) and it seems to be redundant if we have appropriate CLI arguments for them as well. The main point of that is to automate conan "preparing" for cmake builds with its `conan_cmake_autodetect()` which is intended to override your default profile completely. A flow of starting using package with conan will be narrowed to just `pip install conan` command for new developers that want to use projects with `conan_cmake_autodetect()` inside them

**Comment by memsharded** [comment]
I see. It might be worth discussing the default for 2.0.

**Comment by memsharded** [comment]
We have checked this, the conclusion is that the following should work:
```
conan install .
conan install . -s build_type=Debug
```
And in both cases it should do the same, for exactly the same configuration, just switching the ``build_type`` setting to Debug
Which means that when the ``--profile`` argument is not specified it will be defaulted to the ``default`` one, even if the ``--settings``, ``--options`` or other cli arguments are provided, the default profile will still be applied, unless another profile is explicitly defined.

For users that would want to have a different default, they can define an ``empty`` profile (a blank file should be enough), and pass it explicitly with ``-pr=empty``. This could be made the default profile too via configuration if desired, and force the ``--profile=default`` to be always explicit.

**Comment by AbrilRBS** [comment]
Closing this as solved, feel free to reopen/create a new issue should you have any other questions or requests, thanks!
