### ISSUE TITLE
[bug] conan install example doesn't work

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#11254]
### Environment Details (include every applicable attribute)
  * Operating System+version: Redhat Enterprise Linux 7.9
  * Compiler+version: gcc 11
  * Conan version: 1.48
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)
In the `conan install` [build options documentation](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#build-options) it says you can do this:

`--build=!zlib --build` Build all packages from source, except for zlib.

However, when i tried that I would get "binary missing errors...use --build=XXX" errors for the non-excluded libraries. The workaround was to do:
```
conan install myconanfile.py --build=!abc --build=*
```
Not sure if that's a conan build, or a documentation bug

**Comment by memsharded** [comment]
I'd say that it is correct for the default ``semver_mode``. I guess that you are using some other mode, that implies that when zlib is built, all its consumers also need to be rebuilt?

**Comment by rconde01** [comment]
Hmm...let me lay it out in more detail:

`conanfile.py`
```
def MyApp(ConanFile):
   def requirements(self):
     self.requires("libA/1.0")
     self.requires("libB/1.0")
     self.requires("libC/1.0")
```

I expect that if I do:
```
conan install conanfile.py --build=!libA --build
```
That `libB` and `libC` would be built, based on the documentation. But I have to do:
```
conan install conanfile.py --build=!libA --build=*
```

Side question - does the order or the `--build` specs matter? how is the final list of "things to build" created?

**Comment by memsharded** [comment]
I see. No, if the 3 libraries are not dependent on each other, it shouldn't matter, and the order shouldn't matter. If they depend on each other, then yes, the order matters. Conan expands depth-first, and it orders things to install/build according the resulting sorted topologic order of the graph.

I think the difference is that ``--build`` without arguments work slightly different that ``--build=*`` for the negation, as it is pattern based (and ``--build`` is build "all", not build according a pattern "*" that would eventually build all). Does this make sense?

**Comment by rconde01** [comment]
1. I think the distinction is confusing...but I kinda get it - but would you say the example in the docs is wrong then?
2. So focusing on patterns, i'm wondering are all positive patterns applied before negatives? e.g.
```
conan install . --build=* --build=!zlib
```
could be different than:
```
conan install . --build=!zlib --build=* 
```
depending on how things are applied.

**Comment by memsharded** [comment]
This was changed in Conan 2, how the ``--build`` is processed, processing first the exclusion patterns, then the regular patterns, not matter the order in the command line. Closing as solved, please create new tickets if necessary, thanks for the feedback.
