### ISSUE TITLE
[bug] `settings.yml.new` of an old conan version sometimes generated when `settings.yml` has been modified

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11259]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Montery
  * Compiler+version: apple-clang 13.1
  * Conan version: 1.48.0
  * Python version: 3.9.12

### Steps to reproduce (Include if Applicable)

- install conan with homebrew
- slightly modify `settings.yml` (for example add a key under apple-clang)
- sometimes conan commands generate a `settings.yml.new` of an old conan version (I see that apple-clang versions 13 and 13.1 are missing, but there is 13.0, I guess it's the `settings.yml` of conan 1.47.0)
- remove this `settings.yml.new`
- call a conan command again, `settings.yml.new` is generated again but now it's correct (ie it's the correct `settings.yml` of 1.48.0).
- remove this file again
- call a conan command again, ok no more creation of `settings.yml.new`
- wait few hours/days, and it may happen again

**Comment by memsharded** [comment]
The only way I see so far in code is that the homebrew update of Conan is kind of failing to regenerate Conan .pyc files or something like that and still running an older version. I wonder if this happens with a regular ``pip install`` installation.

In any case, this migration mechanism for settings has been removed in 2.0, probably not worth investing to much time to investigate it.

**Comment by SpaceIm** [comment]
I think it's a side effect of this VSCode extension I've tried: https://github.com/afri-bit/vsconan. Each time this extension is loaded in side bar of VSCode, this issue occurs.
