### ISSUE TITLE
[question] mysterious linker verbosity

### ISSUE THREAD

**Issue by blackencino** [conan-io/conan#11253]
At some point in the distant past (a year ago?), I remember making some change in something somewhere in my configuration that caused all of the libraries found by conan to be printed out with every build. I cannot for the life of me remember what this was, and I'm desperate to turn it off. 

I'm on Windows 10, using msvc 16.11.14 (most recent patch), conan 1.48, cmake 3.23.1, ninja.  

Things I've tried: nuking .conan directory, reinstalling all of the above ^^^, recopying conan.cmake, conan.conf, settings.yml from scratch... nothing works. There's nothing in either the User or System environment variables that seems relevant.

Here's an example of what the output from every single linker step is. Any help would be greatly appreciated.

```
[29/51] Linking CXX executable CMakeFiles\adaptive_scarab_static_vector_test.dir\cmake_device_link.obj
scarab_static_vector_test.cpp.obj
EmldCore_AbcMeshesScene.lib
EmldCore_ParallelUtil.lib
EmldCore_SpatialSubd.lib
EmldCore_TriMesh.lib
EmldCore_Util.lib
noise.lib
shallow_weaver.lib
sph2d_box.lib
sph_common.lib
util.lib
wisp.lib
z_index.lib
gtest_main.lib
gmock_main.lib
gmock.lib
gtest.lib
tbb.lib
tbbmalloc.lib
libboost_contract.lib
libboost_coroutine.lib
libboost_fiber_numa.lib
libboost_fiber.lib
libboost_context.lib
libboost_graph.lib
libboost_iostreams.lib
bz2.lib
libboost_log_setup.lib
libboost_log.lib
libboost_locale.lib
libboost_math_c99.lib
libboost_math_c99f.lib
libboost_math_c99l.lib
libboost_math_tr1.lib
libboost_math_tr1f.lib
libboost_math_tr1l.lib
libboost_nowide.lib
libboost_program_options.lib
libboost_random.lib
libboost_regex.lib
libboost_stacktrace_noop.lib
libboost_stacktrace_windbg.lib
libboost_stacktrace_windbg_cached.lib
ole32.lib
dbgeng.lib
libboost_timer.lib
libboost_type_erasure.lib
libboost_thread.lib
libboost_atomic.lib
libboost_chrono.lib
libboost_container.lib
libboost_date_time.lib
libboost_unit_test_framework.lib
libboost_prg_exec_monitor.lib
libboost_test_exec_monitor.lib
libboost_exception.lib
libboost_wave.lib
libboost_filesystem.lib
libboost_wserialization.lib
libboost_serialization.lib
bcrypt.lib
Alembic.lib
IlmImfUtil-2_5.lib
IlmImf-2_5.lib
Imath-2_5.lib
Half-2_5.lib
IexMath-2_5.lib
IlmThread-2_5.lib
Iex-2_5.lib
libhdf5_hl_cpp.lib
libhdf5_cpp.lib
libhdf5_hl.lib
libhdf5.lib
zlib.lib
spdlog.lib
fmt.lib
cudart.lib
cuda.lib
cudadevrt.lib
cudart_static.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
```

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by blackencino** [comment]
An additional piece of information - another sibling project that also uses the same build tools does not exhibit this problem, which suggests that whatever it is, it's lurking in the project itself. I realize this may be straying from conan questions.

**Comment by memsharded** [comment]
Can you try sharing the conanfile.py recipe for that specific package that is printing that information? (if private you can try emailing it to info@conan.io).

This seems a quite challenging issue to investigate in any case. To be honest, no idea of what could it be.

**Comment by blackencino** [comment]
Hey folks, I was able to diagnose this with a great deal of help from my coworkers. It is caused by the Nvidia CUDA compiler on Windows - when nvcc has the "-dlink" flag set for device linking, it prints out all of the libraries it sees during linking. There's no way to turn this off, other than to not use device linking of kernels.

**Comment by memsharded** [comment]
Great that you found it, thanks for following up!
