### ISSUE TITLE
[question] Is it possible to `require` conan 1.x packages from conan 2.x recipe?

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#11258]
Currently, I can't add a requirement on a conan 1.x package because it can't find `conans` package which is downloaded after `pip install conan` but I already have installed `pip install conan --pre` and can't install 1.x version along with 2.x because pip does not allow to install multiple versions of the same package

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I am not sure what you mean. You should use different Python virtualenvs to install Conan 1.X and Conan 2.0, do not install them in the same environment. You might also try to use ``pipx`` tool for this. Is this your question?

**Comment by thorsten-klein** [comment]
I think this will be possible if your conanfile.py is written to be compatible with 1.X and 2.X both
(e.g. tool_requires instead of build_requires, etc...)

Most likely you can only reach this compatibility between a really new 1.X (e.g. >1.47) and 2.X
