### ISSUE TITLE
[question] What is the major difference between conan2 and conan1

### ISSUE THREAD

**Issue by evan0greenup** [conan-io/conan#11256]
- [* ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

What is the difference between conan version 2 and 1?

Will conan 2 be back-compatible with conan 1?

**Comment by memsharded** [comment]
Hi @evan0greenup 

You want to read:

- Migration guide: https://docs.conan.io/en/latest/conan_v2.html
- Tribe 2.0 design discussions: https://github.com/conan-io/tribe (and https://conan.io/tribe.html)
   - This include things like discussions about compatibility: https://github.com/conan-io/tribe/blob/main/design/013-migration-path.md
- For the current 2.0 docs: https://docs.conan.io/en/2.0-alpha/index.html

**Comment by AbrilRBS** [comment]
Closing this as solved, feel free to reopen/create a new issue should you have any other questions or requests, thanks!
