### ISSUE TITLE
[bug] apply_conandata_patches() doesn't work with conan install+source+build

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#11255]
I've found a CCI recipe that can be used for the test.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc9
  * Conan version: 1.48.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
```
git clone https://github.com/conan-io/conan-center-index
cd conan-center-index/recipes/faac/all
conan install . 1.30@ -if build --build=missing
conan sources . -if build -sf build
conan build . -if build -sf build -bf build
```

Error message:
```
conanfile.py (faac/1.30): Calling build()
ERROR: conanfile.py (faac/1.30): Error in build() method, line 106
	apply_conandata_patches(self)
	TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by paulharris** [comment]
It works if you replace the apply_conandata_patches(self) with the standard `for patch` loop.

**Comment by paulharris** [comment]
Note that even the loop doesn't work with
```
conan install . 1.30@ -if install
conan source . -if install -sf src
conan build . -if install -sf src -bf build
```

**Comment by memsharded** [comment]
``apply_conandata_patches()`` is a new ``conan.tools`` it is intended to work with the ``layout()`` and the new build system integrations for the local flow. I'd recommend to setup a repro case starting with the ``conan new hello/0.1 --template=cmake_lib``
