### ISSUE TITLE
[bug] system_libs are linked before objects causing undefined references

### ISSUE THREAD

**Issue by dvirtz** [conan-io/conan#11269]
I have a recipe which includes compiled objects which depend on system libraries so I produce the following package info
```
    def package_info(self):
        self.cpp_info.objects = [os.path.join("lib", o) for o in objects]
        self.cpp_info.system_libs = ["pthread", "dl"]
```

however, the CMake config files produced link the system libs before the objects, which, on some systems, makes the linker not find the required symbols:
```
(.text+0x191a89): undefined reference to `pthread_setaffinity_np'
(.text+0x191aba): undefined reference to `dlsym'
```

seems like the order should be reversed in https://github.com/conan-io/conan/blob/0eb405bde999d5b7b8e706b206940d2e24aa828e/conan/tools/cmake/cmakedeps/templates/target_configuration.py#L117-L120

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: GCC 8
  * Conan version: 1.44.1

### Steps to reproduce (Include if Applicable)
see above

**Comment by memsharded** [comment]
Thanks for reporting, trying in https://github.com/conan-io/conan/pull/11272 to see if this change could break something

**Comment by memsharded** [comment]
Merged https://github.com/conan-io/conan/pull/11272, will be included in next 1.49 release

**Comment by EstebanDugueperoux2** [comment]
Hello,

I have the same issue with glog, do you have a workaround waiting 1.49 release?

Regards.

**Comment by memsharded** [comment]
We plan to branch 1.49 today if possible. I don't think there is any reasonable workaround, beyond redefining targets variables directly in your consumer CMakeLists.txt after the ``find_package()``

**Comment by dvirtz** [comment]
what I did was to modify the recipe to use link flags to link the objects as those are added before system libs
```
        # use linkflags instead of objects due to https://github.com/conan-io/conan/issues/11269
        self.cpp_info.sharedlinkflags = [os.path.join(self.package_folder, "lib", o) for o in objects]
        self.cpp_info.exelinkflags = self.cpp_info.sharedlinkflags
```

**Comment by EstebanDugueperoux2** [comment]
Hi @dvirtz,

Thanks for the tips,
Do you put this snippet in package_info method of conanfile.py of consumer? For example in my case, in conanfile.py of glog consumer?

**Comment by dvirtz** [comment]
> Hi @dvirtz,
> 
> Thanks for the tips,
> Do you put this snippet in package_info method of conanfile.py of consumer? For example in my case, in conanfile.py of glog consumer?

no, I put it in the package_info of the package exporting those objects, so maybe this is not relevant if you don't control the dependency

**Comment by levenkov** [comment]
It seems that this bug is still reproducable in case of `self.cpp_info.component["foo"].system_libs = ...`
