### ISSUE TITLE
Use `DESTDIR={selfpackage_folder}` rather than `--prefix={self.package_folder}`

### ISSUE THREAD

**Issue by mattyclarkson** [conan-io/conan#11264]
Settng the `--prefix` to the package folder can result in the prefix getting baked into some open source projects and lead to unrelocatable packages.

An idiom for autotools projects that results in more commonly relocatable packages is to do:

```
./configure --prefix=/
make
make DESTDIR=<package-dir> install
```

That will result in the same layout as this but avoids _most_ baking of the prefix paths, there are still a few projects that use `DESTDIR` to bake in paths. Most projects use relative paths.

_Originally posted by @mattyclarkson in https://github.com/conan-io/conan/pull/10978#discussion_r870134071_

**Comment by czoido** [comment]
Hi @mattyclarkson,
Thanks a lot for reporting this, I have opened a PR to follow that flow: https://github.com/conan-io/conan/pull/11284
