### ISSUE TITLE
[bug] Static libraries produced with visual studio 17.2 do not appear to be always compatible with ones produced by earlier 17 versions

### ISSUE THREAD

**Issue by drussel** [conan-io/conan#11260]
### Environment Details (include every applicable attribute)
  * Windows 10,11
  * Visual studio 17.2
  * Conan 1.47, 1.48
  * Python version: 3.X

### Steps to reproduce (Include if Applicable)
We have an intel tbb package (static build) that if built with 17.2 won't link with 17.1 built artifacts (and vice versa). If built with 17.2, the error in 17.1 is for missing `__std_init_once_link_alternate_names_and_abort`. However conan treats these two as equivalent. We had seen this sort of thing with an earlier pair of versions in the 17 series too and worked around that by upgrading everything in sync.

According to https://docs.microsoft.com/en-us/visualstudio/releases/2022/compatibility, binary compatibility is best effort.

It looks like conan may be moving to use msvc build types with a finer granularity (perhaps to solve this problem), but I can't find documentation on this (and it seems to be evolving rapidly).

**Comment by memsharded** [comment]
Hi @drussel 

Yes, the new model for VS is the ``msvc`` compiler in https://github.com/conan-io/conan/blob/f9215513368e576a82f071ab5d7b4cf990d156ca/conans/client/conf/__init__.py#L111, that models both the major compiler version (190, 191, 192) and then it allows the "update":
- For most users, and this is what ConanCenter will do, it is not necessary to specify the update. This works well in the general case of using the same update, or using only upgrading updates, but not with downgraded versions. But that is fine for most situations where users only move forward the VS updates
- For users that want full control also over the update, they can specify that ``compiler.update`` in their profile settings, and they will get a different binary for each update.


It is important to know that:
- The new ``msvc`` model is still not widely used. ConanCenter is still using the ``Visual Studio`` one
- The new ``msvc`` model might need the new build system integrations (the ones in https://docs.conan.io/en/latest/reference/conanfile/tools.html), the legacy ones might not work well with it. So it is necessary to upgrade first to these before moving to ``msvc``
- ConanCenter recipes will do this upgrade while preparing for Conan 2.0
- This ``msvc`` compiler setting will be the one that will live in 2.0, the ``Visual Studio`` one will be removed.

If in the meantime you want to differentiate binaries for the ``Visual Studio`` compiler, you can always add some ``update`` or ``minor`` to your ``settings.yml`` to control the generated binaries.

**Comment by drussel** [comment]
When I use `msvc` with version `193` and update `2`, if there is no build already there, it picks `arch: x86_64,  build_type: Release, compiler: Visual Studio, compiler.runtime: MD, compiler.version: 17` as a "compatible" version, tries to use it resulting in a linker error. Is there a way to disable the inaccurate compatibility check?

**Comment by memsharded** [comment]
Yes, there is a conf you can use exactly for deactivating this: ``core.package_id:msvc_visual_incompatible`` (Put it in the ``global.conf`` file in your cache, doable with ``conan config install`` too)

**Comment by nmoreaud** [comment]
`compiler.version.update` should have done the trick: https://docs.conan.io/2.0/reference/config_files/settings.html#compilers
However, with this configuration:
```ini
[settings]
compiler=msvc
compiler.version=193
compiler.version.update=3
```

I obtain:
```
ERROR: 'settings.compiler.version.update' doesn't exist for '193'
'settings.compiler.version' possible configurations are none
```

**Comment by nmoreaud** [comment]
@memsharded `core.package_id:msvc_visual_incompatible` seems to be only for Conan 1.X.
Do you have a solution for Conan 2?

**Comment by nmoreaud** [comment]
The documentation seems to be wrong; `compiler.version.update` should probably be spelled `compiler.update`
I still have a linker incompatibility with icu.

**Comment by memsharded** [comment]
You are right, the docs in https://docs.conan.io/2.0/reference/config_files/settings.html#compilers needs to be fixed, Ill fix the docs now.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/docs/commit/ad2baa680e4a1cb1cb4149fb4da9895ebf8f6727

**Comment by memsharded** [comment]
The ``core.package_id:msvc_visual_incompatible`` is a configuration for making ``Visual Studio`` and ``msvc`` compiler settings have distinct binaries while in Conan 1.X. As ``Visual Studio`` compiler setting has been removed in 2.0, this has no longer any sense, so it has been removed too in 2.0. There is no alternative, because there is no such ``Visual Studio`` compiler in 2.0 anymore.

**Comment by memsharded** [comment]
Otherwise, I think we can close this issue:

- The default 2.0 compatibility is without update, works well assuming a "moving forward" policy with VS updates, that is binaries built with an update are only used with higher updates, not lower. This seems to work good enough at scale with ConanCenter binaries too
- For users wanting to detail and have the ``compiler.update`` too for msvc, it is already built-in in the default settings.yml, so it is just a matter of defining it in the profiles.
