### ISSUE TITLE
Can I upload package with different compiler setting?

### ISSUE THREAD

**Issue by sbellus** [conan-io/conan#11262]
Can I upload package with different compiler setting?

I build only shared library of my package. It is not necessary for package consumer to  use the same compiler.
I compile with intel compiler, but want to upload package with compiler setting "any".
The relevant setting for consumer are only  os, arch, distro.

How can I achieve it?

**Comment by memsharded** [comment]
Hi @sbellus 

You can do "settings erasure" in ``package_id()`` method, something like:

```python
def package_id(self):
     del self.info.settings.compiler
```

This will make that all the compiler settings and subsettings will be removed, resulting always in the same identical ``package_id``. If you re-build the package with a new compiler or version, it will still result in the same ``package_id``, overwriting it.
There are other approaches to achieve this, but I think this is the simplest and what you are interested in at the moment.

**Comment by sbellus** [comment]
Thank you, the solution is ok.
