### ISSUE TITLE
Conditionally add `--enable-shared`/`--enable-static` configure flags.

### ISSUE THREAD

**Issue by mattyclarkson** [conan-io/conan#11265]
Unconditionally adding these prevents using the `--enable-option-checking=fatal` option with projects that do not support these flags. For example, `make` and `m4` do not understand these flags.

_Originally posted by @mattyclarkson in https://github.com/conan-io/conan/pull/10978#discussion_r870131250_

**Comment by czoido** [comment]
Hi @mattyclarkson,
Thanks a lot for reporting this, I have opened a PR to fix this: https://github.com/conan-io/conan/pull/11284
