### ISSUE TITLE
[bug] VirtualRunEnv: conanrun.sh stop in set -e mode

### ISSUE THREAD

**Issue by dfleury2** [conan-io/conan#11266]
Hi,
Debian 11, conan latest master, python 3.9.

Using the new VirtualRunEnv, if your "shell" environment has the 'set -e' activated, when `printenv` is used with an empty variable, it returns 1 and the script calling it just stop on error.

A patch could be in conan/tools/env/environment.py, replace
```
value=$(printenv $v)
```
by something like
```
value=$(printenv $v || true)
```
to avoid `Command failed with exit code 1` symptom.
Regards,

**Comment by memsharded** [comment]
Don't know enough about shell to understand what ``value=$(printenv $v || true)`` is doing, it is actually restoring correctly the variable value if we add it, or just not failing? Because probably it is better to locally make it work with ``set +e`` or something like that?

**Comment by dfleury2** [comment]
`printenv` command exit 1 for empty variable (like LD_LIBRARY_PATH can be), in this case, the shell will execute the || (OR) branch, which is `true` then the exit code of the "globale" command will be 0 instead of 1.
for non-empty variables, nothing change.
In both cases, value will be either the variable value or empty.

Yes, I put `set +e` global CI/CD script but it's not always possible due to permissions on CI/CD pipeline.

**Comment by memsharded** [comment]
I was thinking of explicitly adding the `set +e` in the Conan script instead. You mean that this would be blocked and not work because of CI/CD permissions?

**Comment by dfleury2** [comment]
Oh, yes, may be adding `set +e` inside `conanrun.sh`or `conanrunenv-....sh` will work too. But I do not know the effect at global scope. This is why I have proposed the `|| true` which is more local, with no global side effet.

I thought you were speaking about changing the CI/CD script directly instead of one of the conan generated scripts.
When I said it would block on CI/CD it was for the CI/CD scripts, not the conan ones.
I do not see any reason the CI/CD can block the `set +e`inside the conan scripts.

**Comment by memsharded** [comment]
Trying to check the existence of the variable instead of the value in https://github.com/conan-io/conan/pull/11361, lets see how it goes

**Comment by memsharded** [comment]
Proposing slightly different variant in https://github.com/conan-io/conan/pull/11361, could you please @dfleury2 have a look? There was a case not managed, when a variable was set, but set to an empty string (not unset)

**Comment by dfleury2** [comment]
Hi,
seems ok to me. But no way to effectively test it on my side.
Tjanks
