### ISSUE TITLE
[question] How to package XXXConfig.cmake in conan package while using it in runtime?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#11273]
The situation is like this:
I want to build a conan recipe for libtorch, and libtorch has its own XXXConfig.cmake in /share/cmake, and how can I defind package function in conan to use this in-built config.cmake and in runtime?

**Comment by memsharded** [comment]
Not much to do:

- Just package the xxxConfig.cmake inside the package
- Depending on where you put it, you might need to add it to the ``builddirs``, like ``self.cpp_info.builddirs.append(os.path.join("hello", "cmake"))``
- You can use the ``CMakeToolchain`` in the consumer side (https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html), that will add those paths to the necessary CMake paths, so your xxxConfig.cmake inside the package is found and used.

**Comment by Tumb1eweed** [comment]
> Not much to do:
> 
> * Just package the xxxConfig.cmake inside the package
> * Depending on where you put it, you might need to add it to the `builddirs`, like `self.cpp_info.builddirs.append(os.path.join("hello", "cmake"))`
> * You can use the `CMakeToolchain` in the consumer side (https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html), that will add those paths to the necessary CMake paths, so your xxxConfig.cmake inside the package is found and used.

Thanks, I try this now.

**Comment by Tumb1eweed** [comment]
> Not much to do:
> 
> * Just package the xxxConfig.cmake inside the package
> * Depending on where you put it, you might need to add it to the `builddirs`, like `self.cpp_info.builddirs.append(os.path.join("hello", "cmake"))`
> * You can use the `CMakeToolchain` in the consumer side (https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html), that will add those paths to the necessary CMake paths, so your xxxConfig.cmake inside the package is found and used.

If I have three packages, and two of it should use cmake_find_package as generator, last one should use CMakeToolchain as generator, how should i write this in conanfile.txt?

**Comment by memsharded** [comment]
It doesn't work that way. ``cmake_find_package`` is a generator for dependencies while ``CMakeToolchain`` is about the current package ``settings``, not dependencies, and adding paths to find files, but not actually defining the dependencies information.

You shouldn't mix generators, if you are using ``CMakeToolchain``, you should use ``CMakeDeps`` (it is an evolved improved version of ``cmake_find_package``).

**Comment by Tumb1eweed** [comment]
> It doesn't work that way. `cmake_find_package` is a generator for dependencies while `CMakeToolchain` is about the current package `settings`, not dependencies, and adding paths to find files, but not actually defining the dependencies information.
> 
> You shouldn't mix generators, if you are using `CMakeToolchain`, you should use `CMakeDeps` (it is an evolved improved version of `cmake_find_package`).

Is there any example about using CMakeToolchain or CMakeDeps? In creator view and consumer view.

**Comment by memsharded** [comment]
Sure, the ``conan new hello/0.1 --template=cmake_lib`` gives you a working example (the ``CMakeDeps`` usage is in the ``test_package/conanfile.py``, but you can easily extrapolate that to the package ``conanfile.py``).

**Comment by Tumb1eweed** [comment]
> conan new hello/0.1 --template=cmake_lib

How should i use in conanfile.txt to consume package with CMakeToolchain generator?

**Comment by memsharded** [comment]
```
[requires]
...
[generators]
CMakeToolchain
CMakeDeps
```

**Comment by Tumb1eweed** [comment]
> Not much to do:
> 
> * Just package the xxxConfig.cmake inside the package
> * Depending on where you put it, you might need to add it to the `builddirs`, like `self.cpp_info.builddirs.append(os.path.join("hello", "cmake"))`
> * You can use the `CMakeToolchain` in the consumer side (https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html), that will add those paths to the necessary CMake paths, so your xxxConfig.cmake inside the package is found and used.

After I use generators "CMakeDeps" for conan package and write those paths in package_info
```
    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
        self.cpp_info.includedirs.append(
            os.path.join("include", "torch", "csrc", "api", "include")
        )
        configs_cmake = ["ATen", "Caffe2", "Gloo", "Tensorpipe", "Torch"]
        for config in configs_cmake:
            print(os.path.join("share", "cmake", config))
            self.cpp_info.builddirs.append(os.path.join(self.package_folder, "share", "cmake", config))
```
I use conan install and still can't find any toolchain file like (https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html) said, is it because my conan version is only 1.48? I get warnings like:
```
conanfile.txt: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
```

**Comment by Tumb1eweed** [comment]
> ```
> [requires]
> ...
> [generators]
> CMakeToolchain
> CMakeDeps
> ```

Very helpful! Thank you.

**Comment by chl1123** [comment]
Have you written the recipe for libtorch? I also want to use libtorch based on Conan2, there is no libtorch in ConanCenter yet. Can you share the following experience?

**Comment by Tumb1eweed** [comment]
> Have you written the recipe for libtorch? I also want to use libtorch based on Conan2, there is no libtorch in ConanCenter yet. Can you share the following experience?

Of course, but maybe it is of little use, I use binary package in x86 and build from source in arm64.

```
    def source(self):
        if self.settings.arch == "x86_64":
                self._download_from_ftp(
                    "libtorch-cxx11-abi-shared-with-deps-1.9.0+cu111.zip",
                    self.source_folder,
                )

        if self.settings.arch == "armv8":
            git = tools.Git()
            git.clone(
            "https://github.com/pytorch/pytorch.git", "v1.9.0")
            self.run("git submodule sync")
            self.run("git submodule update --init --recursive")

    def build(self):
        if self.settings.arch == "x86_64":
            return
        if self.settings.arch == "armv8":
            env_build = RunEnvironment(self)
            with tools.environment_append(env_build.vars):
                self.run("python3 {source}/tools/build_libtorch.py".format(source=self.source_folder))
                # cuda = self.dependencies["cuda"]
                # nccl = self.dependencies["nccl"]
                # cmake.definitions["NCCL_INCLUDE_DIR"] = nccl.package_folder + "/include"
                # cmake.definitions["NCCL_LIB_DIR"] = nccl.package_folder + "/lib"
                # cmake.definitions["CUDA_BIN_PATH"] = cuda.package_folder + "/lib"
                # cmake.definitions["CUDA_TOOLKIT_ROOT_DIR"] = cuda.package_folder
                # cmake.definitions["CUDA_INCLUDE_DIR"] = cuda.package_folder + "/include"
                # cmake.definitions["CUDNN_INCLUDE_DIR"] = cuda.package_folder + "/include"
                # cmake.definitions["CUDNN_LIB_DIR"] = cuda.package_folder + "/lib64"
                # cmake.definitions["CUDA_HOST_COMPILER"] = "cc"
                # cmake.definitions["USE_CUDA"] = 1
                # cmake.definitions["USE_NNPACK"] = 1
                # cmake.definitions["BUILD_TORCH"] = "ON"
                # cmake.definitions["USE_OPENCV"] = "ON"
                # cmake.definitions["USE_NCCL"] = "ON"
                # cmake.definitions["USE_KINETO"] = "OFF"
                # cmake.definitions["CMAKE_BUILD_TYPE"] = "Release"
                # cmake.definitions["CMAKE_CXX_STANDARD"] = 14

    def requirements(self):
        self.requires("cudatoolkit/11.1.1")

    def package(self):
        if self.settings.arch == "x86_64":
            self.copy("*", dst="include", src=self.source_folder + "/include")
            self.copy(
                "*",
                dst="include",
                src=self.source_folder + "/include/torch/csrc/api/include",
            )
            self.copy("*.so*", dst="lib", src=self.source_folder + "/lib")
            self.copy("*", dst="share", src=self.source_folder + "/share")
        if self.settings.arch == "armv8":
            self.copy("*", dst="include", src=self.source_folder + "/torch/include")
            self.copy(
                "*",
                dst="include",
                src=self.source_folder + "/include/torch/csrc/api/include",
            )
            self.copy("*.so*", dst="lib", src=self.build_folder + "/build/lib/")
            self.copy("*", dst="share", src=self.source_folder + "/torch/share/")

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
        self.cpp_info.includedirs.append(
            os.path.join("include", "torch", "csrc", "api", "include")
        )
        self.cpp_info.sharedlinkflags = []
        for lib in ['torch_cpu', 'torch_cuda', 'torch_cuda_cu', 'torch_cuda_cpp', 'torch']:
            self.cpp_info.sharedlinkflags.append(
                f"-Wl,--no-as-needed,{os.path.join(self.package_folder, 'lib', 'lib'+lib+'.so')}",
            )
        self.cpp_info.sharedlinkflags.append("-Wl,-as-needed")
        self.env_info.LD_LIBRARY_PATH.append(os.path.join(self.package_folder, "lib"))

```

I write cudatoolkit recipe as well. And informing you in advance, compile libtorch in arm64 takes a life time~(5-6 hours if I remember correctly)
