### ISSUE TITLE
[bug] tool.collect_libs behaves differently on mac and linux

### ISSUE THREAD

**Issue by DS-Serafin** [conan-io/conan#11282]
Mac and Linux both creaete symlinks without package version and libs with package version.

Linux: libmylib.so -> llibmylib.so.X.Y.Z
Mac: libmylib.dylib -> llibmylib.X.Y.Z.dylib

tools.collect_libs with make a os.path.splitext and check if the extension is a valid lib extension. Both symlinks are fine:
 libmylib.so  -> ext = .so (valid and listed)
 libmylib.dylib -> ext = .dylib (valid and listed)
 
The actualy libs however behave defferntly:
 libmylib.so.X.Y.Z -> ext = .Z (not valid is discarded
 libmylib.X.Y.Z.dylib -> ext = .dylib (valid and listed)

Not sure what the corect behaviour should be probaly both should be listed in both cases. But behaving like this is clearly a bug

**Comment by gabyx** [comment]
Jeah, `collect_lib` should collect all libs (even symlinks) and also it should report
a list of (`fileName`, `path`) instead of only the filenames, to allow the user to check other stuff on these files... discarding symlinks.

On linux the additional check:

```python
".so." in name
```
should be done...

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan/pull/11527 implements a consistent behavior. But it keeps only the most generic lib name since `collect_libs` usually aims to populate `self.cpp_info.libs` in `package_info()`.
