### ISSUE TITLE
[question] Remotes unreachable although Ping was still working.

### ISSUE THREAD

**Issue by tungnguyen279** [conan-io/conan#11288]
I am installing conan-file. And somehow i can't retrieve data from remote server. The Ping command for this server still works. 
Here is the notifications of the problem. 

**eem_mlbevo_toolchain/0.4@eem_mlbevo/testing: Not found in local cache, looking in remotes...
eem_mlbevo_toolchain/0.4@eem_mlbevo/testing: Trying with 'ee-conan-toolchain'...
ERROR: Failed requirement 'eem_mlbevo_toolchain/0.4@eem_mlbevo/testing' from 'conanfile.py (eem_mlbevo_integration/0.1@eem_mlbevo/testing)'
ERROR: HTTPSConnectionPool(host='nexus.edag.de', port=443): Max retries exceeded with url: /nexus/repository/ee-conan-toolchain/v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5e492f4450>, 'Connection to 10.10.1.10 timed out. (connect timeout=10.0)'))**

**_Unable to connect to ee-conan-toolchain=https://nexus.edag.de/nexus/repository/ee-conan-toolchain
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again._**

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This looks like a server configuration issue. As you are using nexus, that is a server that we don't manage, we cannot know what is happening, so you would need to report the issue to their respective issue tracker. 

You can also try with ArtifactoryCE from the https://conan.io/downloads.html page, which is free for Conan usage.

**Comment by memsharded** [comment]
Closing this ticket, not a Conan one, but a server (nexus) one.
