### ISSUE TITLE
[question] CI builds fail if recipe has not changed

### ISSUE THREAD

**Issue by anderson-dev** [conan-io/conan#11297]
Currently, our CI pipeline consists of source pull, restore (conan install), build/test (conan build), package (conan export-pkg), publish (conan publish), and finalize stages. If someone kicks off a build more than once accidentally, the first build job goes through all stages just fine but each subsequent job fails due to a stderr when `conan export-pkg` is run. The packaging step fails because the recipe/package already exists in conan cache.

Once this failing job has happened, our PRs are unable to satisfy build checks. Our developers then attempt to rebuild failing each time until I either skip the package/publish steps or force overwrite (which I avoid and don't ever need in any other case as we use revisions). Is there a recommended way to prevent a hard fail if the recipe/package is present and has not changed? Or maybe some way to check whether they differ prior and only export-pkg if they are different?

Conan version: 1.45.0

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by anderson-dev** [comment]
If recipe is the same but at least one upstream package is new, the package exports successfully but promotion from one channel to another (conan copy) fails because that recipe already exists as well. I could check to see if recipe exists first but then recipe revisions would be non-functional.

I imagine I'll have the same issue for conan publish if both recipe/package haven't changed

**Comment by memsharded** [comment]
> If recipe is the same but at least one upstream package is new, the package exports successfully but promotion from one channel to another (conan copy) 

An important note about this: ``conan copy`` has been removed from Conan 2.0. Packages must be immutable, and ``conan copy`` is violating that. To implement "stages" the recommended way is to leave the packages user/channel constant, and use different remote repositories, and run promotions (copies) from one remote repository to another one.

**Comment by anderson-dev** [comment]
1. I see the milestone applied; does that imply that you're able to reproduce or already aware of the issue? Is there anything else you need from me to triage?
2. Are there any plans to address/backport this in 1.x?
3. Would specifying `--force` for `conan export-pkg` be a suitable workaround, for now, considering I already auto-increment version with every git commit and have revisions turned on? In other words, if I were to always specify `--force`, if the recipe or package changed it would simply be a revision as normal and `--force` would only be consequential if there were no changes to recipe/package so it would overwrite the existing recipe/package with exactly the same contents so it would effectively be a no-op other than timestamps... or am I naively mistaken?

**Comment by memsharded** [comment]
Hi @anderson-dev 

We are creating a new ``--build-missing=<pattern>`` build mode that could be useful for your use case, if I understood it correctly, but I would like to check if I really did:

- It seems you are trying to avoid re-building something that was already built. Before even building it.
- The idea is that if a given recipe-revision already has a precompiled binary for a configuration (a given ``package_id``), then it doesn't need to rebuild it again.
- That happens in CI only, developers do not upload packages, they only consume
- Have you considered doing a ``conan export``, then ``conan info`` or ``conan search --revisions`` to see if a package already exists? Have you tried any other mean to see if the binary exist?

Thanks!

**Comment by memsharded** [comment]
The ``--build=missing:<pattern>`` feature has been added and merged in beta.1. It will allow to skip building some binary which already exists in the cache or in the remotes, in a simple way (doing it with ``conan export`` + ``conan info`` is also possible, but requires more effort).

So I am closing this as implemented in beta.1 (to be released soon), feedback welcome!

**Comment by anderson-dev** [comment]
We have been able to move forward with specifying --force as a workaround. I believe even if I were to do `conan export` I would still need --force because the recipe did not change.

Maybe there would be a way to determine whether the recipe changed before attempting to export a recipe to avoid the failure in the case of exporting a recipe that turns out to be the same hash? idk

**Comment by anderson-dev** [comment]
should I create a new issue and try to give more detailed reproduction steps? I don't see how the `--build=missing:<pattern>` feature is relevant here.
