### ISSUE TITLE
[feature] Adds GCC 9.4 in the list of compilers supported in the settings file

### ISSUE THREAD

**Issue by Xav83** [conan-io/conan#11291]
Hello Conan devs :slightly_smiling_face: 

First of all, thanks for your amazing work ! I love how conan simplify my work on the daily basis !

I come to you today with this issue which I don't know if I should categorize it as a feature request or a bug:
- **Adds GCC 9.4 in the list of compilers supported, in the settings file.**

## Context

On a project I am working on (currently private, but it will hopefully soon be open source :slightly_smiling_face:), I am in charge of setting some DevOps processes, and I am configuring a Azure Pipelines process to check the compilation of this project with different compilers.

On the Ubuntu environments available on Azure Pipelines, several versions of the `gcc` compiler are available. For all the versions available there are no compilation problem, except for the version `9.4`, which is not recognized by conan as a valid version, displaying the following message:
```log
ERROR: Invalid setting '9.4' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '6.5', '7', '7.1', '7.2', '7.3', '7.4', '7.5', '8', '8.1', '8.2', '8.3', '8.4', '9', '9.1', '9.2', '9.3', '10', '10.1', '10.2', '10.3', '11', '11.1', '11.2', '12']
```
I was able to reproduce this issue on all the Ubuntu environment of Azure Pipelines: Ubuntu `18.4`, `20.4` and `22.04`.
I am also using the latest release of conan to date: the version `1.48.0`.

For information, the release `9.4` of the compiler `gcc` has been release June 1, 2021 ([GNU releases website](https://gcc.gnu.org/releases.html)). .

If you need more information, or have some question to me, don't hesitate to ask :slightly_smiling_face: 
I am going to try to create a PR this afternoon with the modifications related to this issue, but it will need your reviews, since this is the first time I interact with conan source code :smile:

Finally, if you need me to create a small repository, with a Azure Pipelines process reproducing this issue, please notify me, I will be able to set it up quickly :wink: 

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

PS: This is not relevant to this issue at all, but if you have already see my name, it may be because I am also the maintainer of [conan chocolatey package](https://community.chocolatey.org/packages/conan) :wink:

**Comment by memsharded** [comment]
Hi @Xav83 

Thanks very much for your report!
Indeed that compiler version is missing in our default settings.yml, no need for more details, thanks.

Lets add it, if you want to do it, that is perfect, don't worry this is an easy one: 😄 
- Add it to the default settings.yml (in ``conans/client/conf/__init__.py``)
- Add a new migration in ``conans/client/migration_settings.py`` for the ``1.49`` next release, copying and pasting the last settings and adding there the ``9.4`` too.
- This one doesn't need tests, and there are already tests that will check that the migration is OK.

In case you don't know it, until this is merged and released next 1.49, you can add 9.4 to your own settings.yml in a git repo, and update it with the ``conan config install`` command.

And thanks very much for maintaining the Conan chocolatey package! 😃 😃 😃

**Comment by Xav83** [comment]
Thanks a lot for all those information @memsharded ! Those helped me a lot! :heart: 

So I have created the Pull Request #11296 with the modification you described. :slightly_smiling_face:

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11296
