### ISSUE TITLE
vcvars_command not returning empty string

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1130]
Concatenation like:

```python
build_command = tools.build_sln_command(self.settings, "%s\\glew.sln" % path)
command = "%s && %s" % (tools.vcvars_command(self.settings), build_command)
self.run(command)
```

will fail if vcvars is already set, as ``vcvars_command()`` returns an empty string. It should be checked by the recipe before concat, which is a bit annoying. 

I suggest returning a non-empty string (like ``echo "some msg"``), or maybe having a VS helper that will wrap both lines for simplicity.

cc/ @dimi309

**Comment by dimi309** [comment]
Thanks!
