### ISSUE TITLE
[question] Manually configuring (or disabling) the /MPxx flag for MSVC profiles?

### ISSUE THREAD

**Issue by mvhv** [conan-io/conan#11302]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

### Question
With an MSVC profile CMakeToolchain generator creates a `conan_toolchain.cmake` file that sets the number of compilation processes by setting the `/MP` flag like so:
```cmake
string(APPEND CONAN_CXX_FLAGS " /MP12")
string(APPEND CONAN_C_FLAGS " /MP12")
# snip
  string(APPEND CMAKE_CXX_FLAGS_INIT " ${CONAN_CXX_FLAGS}")
# snip
  string(APPEND CMAKE_C_FLAGS_INIT " ${CONAN_C_FLAGS}")
```
How can I modify/disable this functionality? (Obviously aside from manually editing the lines or wrapping the toolchain in my own toolchain.)

### Background
I have a project that relies heavily on PCL, which isn't yet available as a Conan recipe, so it needs to be built manually. I'm attempting to use Conan to set up the CMake toolchain for the PCL dependencies so I can avoid fragmentation as much as possible when I directly use those third-party deps in my own project. It's straightforward enough with a `conanfile.txt` like so:
```ini
[requires]
zlib/1.2.12
boost/1.78.0
eigen/3.4.0
flann/1.9.2
qhull/8.0.1

[generators]
CMakeDeps
CMakeToolchain
```
And using a default profile:
```ini
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

This configuration on a 6 core CPU with HT gives me the /MP12 flag, which is sensible, but unfortunately this breaks some of the PCL scripts because they assume that if you've set any non-default flags you've set every required flag and don't want any additional added.

I can work around this by wrapping the toolchain and modifying `CMAKE_<LANG>_FLAGS_INIT` or by manually setting all required flags, but with CUDA/Ninja etc., that might be a maintainability issue, so wanted to figure out if I can simply disable this from the Conan side. Alternatively I'm open to any other obvious solution if there's something I missed.

**Comment by mvhv** [comment]
Alright, I've partially answered this question myself. The documentation for CMakeToolchain mentions a parallel ["block"](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#extending-and-customizing-cmaketoolchain) avaliable for extension, and that is where the /MP flag is set. Is there any way to disable that "block" with configuration, or does that mean disabling it would require extending/modifying the generator directly?

**Comment by mvhv** [comment]
Okay, this clears up the last part of my own question. I can see [here](https://github.com/conan-io/conan/blob/0a27518b5f3617a6730df97965a1e0f4e8409e07/conan/tools/cmake/toolchain/blocks.py#L279) that the `ParallelBlock` simply checks for the number of logical threads as a template parameter, and there is a TODO indicating that a config check should be added.

Closing this question now and I'll open a feature request instead.

**Comment by memsharded** [comment]
Hi @mvhv 

The number of build jobs used in this block is controlled by ``tools.build:jobs`` conf, have you tried that one?

**Comment by mvhv** [comment]
Hi @memsharded 

Yeah, I did find that parameter, but it doesn't solve the problem because `tools.build:jobs=x` always results in `/MPx` being added to the flags, with a default lookup of number of CPU cores for a non-int value.

It seems like it should be a non-issue, but the problem it's that it's the only block in the CMakeToolchain generator that will always modify the default `CMAKE_CXX_FLAGS` no matter the value. This breaks some fragile downstream CMake configurations that either assume or check for defaults.

I know the ideal solution is to make those downstream configs made more flexible, but considering this block is the only one that can't be configured around on the Conan side, it makes sense to me that it should have a toggle.

**Comment by memsharded** [comment]
I think that ``tools.build:jobs=0`` will simply not define that flags, please try it and let me know

**Comment by mvhv** [comment]
@memsharded Ahh, you're right... Thanks for that, it seems like I was just thinking too hard about it.

I was looking at `conan.tools.build.cpu.build_jobs()` and focusing on the defaults for `None` but I overlooked how [this](https://github.com/conan-io/conan/blob/0a27518b5f3617a6730df97965a1e0f4e8409e07/conan/tools/cmake/toolchain/blocks.py#L280) obvious if statement falls through on 0.

Thanks.
