### ISSUE TITLE
[feature] add should_patch in addition to should_build and friends

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#11300]
Docs: https://docs.conan.io/en/1.48/reference/conanfile/attributes.html#attribute-build-stages

First, it is confusing that the docs specifically say:
```
def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
    cmake.install()
    cmake.test()
If nothing is specified, all four methods will be called. But using command line arguments, this can be changed:   etc etc
```
But this isn't working for me and my cmake-based build() functions.
In the next paragraph, it implies only Autotools and Meson are supported... so why use a cmake example if it doesn't actually work with cmake (or at least state that lack of support).

-----

Second, why is there an cmake.install() call in build(self) ? I thought that typically is done in def package() ?    Ditto for the cmake.test() call.    What should be the correct pattern going forward?

-----

Next, I like these flags, but there is one step that is typically bundled in the build() step - applying patches to the source.
If the user is doing each step locally, then they are likely repeating steps while iterating through changes (ie steps: configure and build)
So the source() and patch() likely only needs to be done once.

We aren't patching in the source() function, but in the build function(),
so I feel like it should really look like:

```
def build(self):
    if self.should_patch:
        apply_conandata_patches(self)

    cmake = CMake(self)
    if self.should_configure:
        cmake.configure()
    if self.should_build:
        cmake.build()
    if self.should_install:
        cmake.install()
    if self.should_test:
        cmake.test()
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
In Conan 2.0, all these ``should_xxx`` arguments and behaviors have been removed, deprecated in favor of the local developer flow (just ``conan install`` + native build system) and ``conf`` items.

So I don't think it is worth adding this at this stage. Thanks for the suggestion.

**Comment by paulharris** [comment]
Ok sounds good!  I'll close this then.
