### ISSUE TITLE
[feature] Allow to use conanfile as a options source

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#11314]
Sometimes you want to perform an operation on a single package that is dependent on options. But those options are stored in your consumer conanfile.py (or I suppose alternatively conanfile.txt). It is undesirable to manually copy those options out. It would be convenient if you could say something like: `--options-from conanfile.py` which would get your configured options and apply to the operation.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I think this sounds a bit too specific to be made a command line argument, that is the typical thing that users rarely know that it even exists. It could also have some complexities, for example, when options exists in the consumer that doesn't exist in the package that you want to apply those, Conan would raise an error ``option "xxxx" doesn't exist in package "yyyy"``. Not evident at all.

**Comment by rconde01** [comment]
Hmmm...maybe alternatively you can create a separate options file and allow specifying multiple for `conan install`. Then you could specify all your package option files for the two contexts without having to maintain two separate copies. 

Alternatively, maybe you could have an argument to `conan install` which says `build just this one package and necessary dependencies. Don't install anything else`

**Comment by memsharded** [comment]
> Hmmm...maybe alternatively you can create a separate options file and allow specifying multiple for conan install. Then you could specify all your package option files for the two contexts without having to maintain two separate copies.

You can with profiles. Profiles can compose, you can always do ``conan install .... -pr=myprofile -pr=myoptionsprofile``

**Comment by rconde01** [comment]
Interesting. Thanks for the idea.

**Comment by czoido** [comment]
Closing this as I think the profile composition feature covers this use case. Also Conan 2.0 provides [more extensions capabilities](https://docs.conan.io/2/reference/extensions.html).
Please feel free to reopen if you have more questions.
