### ISSUE TITLE
[question] How can I use new  (Conan 2.0) CMake, CMakeToolchain, CMakeDeps  and cmake_layout together ?

### ISSUE THREAD

**Issue by dkumsh** [conan-io/conan#11313]
Currently I am using conan 1.48.

The following recipe works except that it ignores generator **Ninja**  and uses make instead.

```python
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake, cmake_layout

    def generate(self):
        CMakeToolchain(self, generator="Ninja").generate()
        CMakeDeps(self).generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        CMake(self).install()
```
If I try to switch to use layout:
```python
    def layout(self):
        cmake_layout(self)
```
after adding these two lines I get the following errors:

```log
platform-cpp/1.0.0: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan/data/platform-cpp/1.0.0/_/_/build/7f0d27bcdd1b0b01a4f225a668de6ab381c54124/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/platform-cpp/1.0.0/_/_/package/7f0d27bcdd1b0b01a4f225a668de6ab381c54124" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan/data/platform-cpp/1.0.0/_/_/build/7f0d27bcdd1b0b01a4f225a668de6ab381c54124/."
CMake Warning:
  Ignoring extra path from command line:

   "/root/.conan/data/platform-cpp/1.0.0/_/_/build/7f0d27bcdd1b0b01a4f225a668de6ab381c54124/."


CMake Error: The source directory "/root/.conan/data/platform-cpp/1.0.0/_/_/build/7f0d27bcdd1b0b01a4f225a668de6ab381c54124" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
platform-cpp/1.0.0: 
platform-cpp/1.0.0: ERROR: Package '7f0d27bcdd1b0b01a4f225a668de6ab381c54124' build failed
platform-cpp/1.0.0: WARN: Build folder /root/.conan/data/platform-cpp/1.0.0/_/_/build/7f0d27bcdd1b0b01a4f225a668de6ab381c54124/cmake-build-release

JSON file created at '/build/create.json'
ERROR: platform-cpp/1.0.0: Error in build() method, line 46
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan/data/platform-cpp/1.0.0/_/_/build/7f0d27bcdd1b0b01a4f225a668de6ab381c54124/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/platform-cpp/1.0.0/_/_/package/7f0d27bcdd1b0b01a4f225a668de6ab381c54124" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan/data/platform-cpp/1.0.0/_/_/build/7f0d27bcdd1b0b01a4f225a668de6ab381c54124/."
```
Under `~/.conan/data/platform-cpp/1.0.0/_/_/build/7f0d27bcdd1b0b01a4f225a668de6ab381c54124#` directory 
I can see the following tree:
```
./build
./build/generators
```
`./build/` contains only `generators` subdirectory.
`./build/generators` contains many `*.cmake` files. for project dependencies and `CMakePresets.json`

Can someone  explain please what am I doing wrong here. and how can I use new CMake, CMakeToolchain, CMakeDeps  and layout together ?

And second question is why make is used not Ninja?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dkumsh 

I guess that you managed to solve it. Some hints, also for other readers:

- It is possible that the location of the sources was relevant. The ``cmake_layout()`` assumes the sources are in a certain place (but it can be changed with a parameter for the function)
- It is not necessary to hardcode ``generator="Ninja"`` in the recipe, there is a ``conf`` to change this and control it from the profile or command line if desired
- A good starting point with something that works is ``conan new hello/0.1 --template=cmake_lib``
