### ISSUE TITLE
ERROR "Profile not found" but the list command is showing them

### ISSUE THREAD

**Issue by fl0wm0ti0n** [conan-io/conan#11315]
Hello,

conan doesnt find profiles, but with "conan profile list" it can find some. See exemple:

```
flow@lightmachine:~/temp/hello_world$ conan profile list
apple-clang-10-macos-toolchain
clang-6.0-linux-x86
clang-6.0-linux-x86-toolchain
clang-6.0-linux-x86_64
clang-6.0-linux-x86_64-toolchain
clang-6.0-macos-x86_64
default
gcc-7.3.0-linux-aarch64
gcc-7.3.0-linux-aarch64-toolchain
gcc-7.3.0-linux-x86_64
gcc-7.3.0-linux-x86_64-toolchain
gcc-8.2.0-linux-aarch64
gcc-8.2.0-linux-aarch64-toolchain
flow@lightmachine:~/temp/hello_world$
flow@lightmachine:~/temp/hello_world$
flow@lightmachine:~/temp/hello_world$ conan profile show clang-6.0-linux-x86_6
ERROR: Profile not found: clang-6.0-linux-x86_6
flow@lightmachine:~/temp/hello_world$ sudo conan install ./hello_world/ -pr clang-6.0-linux-x86_64
[sudo] password for flow:
ERROR: Profile not found: clang-6.0-linux-x86_64
flow@lightmachine:~/temp/hello_world$
```

OS: WSL2 - Debian 9 (Stretch)

How it works: 
`flow@lightmachine:~/temp/hello_world$ sudo conan install . -pr ~/.conan/profiles/clang-6.0-linux-x86_64`

**Comment by memsharded** [comment]
Hi @fl0wm0ti0n 

the first case is expected, there is typo in the name ``clang-6.0-linux-x86_6``. I guess that if you use the correct name, still happens?

I would say this is an issue of paths and ``userhome`` folder resolution related to WSL2. 

What does ``conan config home`` shows there?

**Comment by memsharded** [comment]
Issue transferred to the Conan repo, doesn't seem an issue with the docs, but with Conan itself

**Comment by fl0wm0ti0n** [comment]
> Hi @fl0wm0ti0n
> 
> the first case is expected, there is typo in the name `clang-6.0-linux-x86_6`. I guess that if you use the correct name, still happens?
> 
> I would say this is an issue of paths and `userhome` folder resolution related to WSL2.

yeah also correct written it happened, i tried it many times

> What does `conan config home` shows there?

unfortunately i deleted the WSL2 Distro with Conan installed. Cause i destroyed it and i dont need it anymore.

But these were the Steps i did before:

2. sudo apt-get install zlib1g-dev
3. sudo apt install libssl-dev
4. sudo apt install libncurses5-dev
5. sudo apt install libsqlite3-dev
6. sudo apt install libreadline-dev
7. sudo apt install libtk8.6
8. sudo apt install libgdm-dev
9. sudo apt install libdb4o-cil-dev
10. sudo apt install libpcap-dev
11. all debian steps in getting started here  https://github.com/includeos/IncludeOS

for example:
$ apt-get install python3-pip python3-dev git cmake clang-6.0 gcc nasm make qemu
$ pip3 install setuptools wheel conan psutil jsonschema
$ **conan config install https://github.com/includeos/conan_config.git**

i did all conan steps without and with sudo, cause i registered some behavior. for example the profiles are saved in the home dir. maybe there is the root of the problem..

if i did everything without sudo, from begin. some other error i get, it described here https://github.com/includeos/IncludeOS/issues/2214 (i think the error there is a conan related error)

**Comment by memsharded** [comment]
Hi @fl0wm0ti0n 

Yes, this could be related to some messing of folders with the sudo/root installations.
As this is not possible to reproduce from our side, and you already deleted that faulty installation, I think it is not longer worth investigating this. If this happens to you again in other installation, please let us know. Thanks!
