### ISSUE TITLE
[question] using build_modules  for library and runtime linking to executable in consumer package

### ISSUE THREAD

**Issue by ggulgulia** [conan-io/conan#11312]
## Short Description
When I use ` self.cpp_info.components[lib_name].build_modules["cmake_find_package"]` in the conan recipe and consume this in another reicpe, I face runtime error in executable linking to the library created with the former recipe.
#### For conan recipe of  `A`: 
* `libA` provides information about `build_modules` in `pkg_info`:
    ```
    def package_info(self):
        lib_name = f"A{version_major}
        self.cpp_info.names["cmake_find_package"] = lib_name
         ...
        self.cpp_info.components[lib_name].build_modules["cmake_find_package"].append(self._module_file_rel_path)
    ```

* The recipe builds successfully :heavy_check_mark: 
*  and the `test_package` for `A` also executes successfully :heavy_check_mark: 
 

#### For conan recipe of  `B`:
* Reicpe of `A` is listed as a requirement for recipe of `B`:
   ```
   def requirements(self):
       self.requires("A")
   ```
*  `package_info` for `B`:
    ```
    def package_info(self):
        lib_name = f"B{version_major}
        self.cpp_info.names["cmake_find_package"] = lib_name
         ...
        self.cpp_info.components[lib_name].requires = ["A::A"]
    ```

* The recipe builds successfully :heavy_check_mark: 

* In the `test_package` of recipe `B` the executable fails to link to the shared library of `A` and I see the following error:
   - Assuming the major version of library `A` being 6 and that of `B` being 5 
 
 ``` 
 /path/to/repository/recipes/B/all/test_package/build/ef44ae3cb0b7943825b49b1b0426c7d3df566f6f/bin/test_package: error while
 loading shared libraries:  libA6.so6: cannot open shared object file: No such file or directory
                                      
ERROR: A/5.3.0@user/testing (test package): Error in test() method, line 25
raise RuntimeError("test package did not run successfully")
   ```
* When I checked which libraries the executable in `B`'s test package links against using `ldd`, the result also indicates that directory to `libA6.so.6` is not found:
* 
```
       ldd test_package/build/ef44ae3cb0b7943825b49b1b0426c7d3df566f6f/bin/test_package 
        linux-vdso.so.1 (0x00007ffcc07e3000)
        libB.so. =>$HOME/.conan/data/B/5.3.0/user/testing/package/bc1b09737d5ad6a2976fda7a85d4f8ecae9ff98c/lib/libB5.so.5 (0x00007f5082f4e000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5082bc5000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f50829ad000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f50825bc000)
        libA6.so.6 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f508239d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f50837ee000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5081fff000)
```  
* When I comment the line ` self.cpp_info.components[lib_name].build_modules` in recipe A, the executable in `test_package` of B links to the shared library of A correctly.
* From what I noticed in the existing conan recipes, the test_package don't define any additional runtime information for an upstream package that uses `build_modules`, so I'm guessing I don't need to define additional runtime dependency in the conanfile.py for test_package of recipe `B`
* Using `self.env_info.LD_LIBRARY_PATH.extend([os.path.join(self.package_folder, "lib")])`  in the recipe of `A` seems to solve the runtime linking issues, but I don't see any other recipes in CCI using it.

#### Question:
* What information am I missing in recipe `A` which prevents linking of shared library with the executable during runtime created in `test_package` of `B` ?
* Do I need to add some information in recipe `B` to correctly link with `libA6.so.6` ?

**Comment by SpaceIm** [comment]
What is the content of test package conanfile?

Your transitive shared lib is not found likely because `LD_LIBRARY_PATH` has not been populated before running the executable.

You should have `self.run(<exe_path>, run_environment=True)`, note the `run_environment=True`.

**Comment by ggulgulia** [comment]
hi, 
there was indeed a problem in the `test_package` of recipe `B`. I was using `subprocess.Popen` to run the executable which is required in our organization to fail CI jobs if test did not run:

```
 def test(self):
        if not tools.cross_building(self):
            bin_path = os.path.join("bin", "test_package")
            test = Popen(os.path.abspath(bin_path), stdout = PIPE)
            testout = test.communicate()[0].decode('ascii')
            test.wait()
            if "Hello from B test package" not in testout:
                raise RuntimeError("test package did not run successfully")
```

using `self.run(<exe_path> run_environment=True)` worked and the test_package for recipe B ran linking correctly to `libA6.so.6.`
