### ISSUE TITLE
[develop2] [feature] Add ``prev``, ``settings``, ``options`` to ``conan graph info`` output

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11327]
Now the serialization of the information is missing some fields.

Verify that subsettings are also dumped.

**Comment by SeanSnyders** [comment]
As per feature request #11362, this command should also return relevant information that would fully describe the state for consumption of the package. This should include details/info from `conanfile.cpp_info` (amongst others) as is constructed via the `package_info()` method.
This would enable the consumption of Conan packages in toolchains that do not depend on Conan itself.

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/11417

The serialization of the full ``cpp_info`` remains open. Moving to next iteration.

**Comment by franramirez688** [comment]
Since https://github.com/conan-io/conan/pull/11434 was merged, full `cpp_info` is now serialized so we can close the issue. It will be released in the next _Conan 2.0.0-beta1_ version.
