### ISSUE TITLE
[bug] [security] conan depends on vulnerable pyjwt (Key confusion through non-blocklisted public key formats)

### ISSUE THREAD

**Issue by SimonHeybrock** [conan-io/conan#11324]
See https://github.com/advisories/GHSA-ffqj-6fqr-9h24. This recommends update to pyjwt>=2.4.0, but conan (from PyPI) depends on pyjwt<2.0.0.

Recommended read: https://iscinumpy.dev/post/bound-version-constraints/.

**Comment by memsharded** [comment]
Did a quick check on this vuln, summary:

- Conan client do not depend on this, only ``conan_server`` side. Recommended to use ArtifactoryCE in most cases in production
- The usage of ``pyjwt`` done in ``conan_server`` explicitly specifies the decoding algorithm, so apparently and fortunately, it seems it won't be affected by this vulnerability.
- Conan 2.0 has done the necessary code changes to upgrade, lets make sure we constraint >2.4.0

Thanks very much for reporting this!

**Comment by SimonHeybrock** [comment]
Can you clarify please, are you saying this will not be fixed for the `conan` PyPI package before a 2.0 release? Are you recommending alternative ways of installation instead?

**Comment by memsharded** [comment]
> Can you clarify please, are you saying this will not be fixed for the conan PyPI package before a 2.0 release? Are you recommending alternative ways of installation instead?

Are you using ``conan_server``? If you are not, then you are not affected, ``conan`` application does not depend on Pyjwt at all.

Even if you are using ``conan_server``, you are not affected by this vulnerability, as the algorithm is explicitly defined in code, and the vulnerability is when this is not defined. Also ``conan_server`` does not have any security embedded in it, it totally relies on having some other security layers in front of it anyway. If you would still want to patch it, then the fix that need to be backported is this one: https://github.com/conan-io/conan/pull/8952/files

**Comment by SimonHeybrock** [comment]
I don't think I am using `conan_server`, but apparently `pip install conan` installs `pyjwt` nevertheless. Is there a package that does not include/require it?

**Comment by memsharded** [comment]
> I don't think I am using conan_server, but apparently pip install conan installs pyjwt nevertheless. Is there a package that does not include/require it?

because ``conan_server`` is in the ``pip install conan`` bundle too, everything is distributed together, it doesn't have a specific pip package. If not using ``conan_server`` the ``pyjwt`` can be even removed just after the installation

**Comment by SimonHeybrock** [comment]
Ok, basically this makes the `conan` PyPI package unusable then, since we are getting a dependabot alert when adding it to our requirements:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/12912489/170683277-d6dffefa-caab-4aeb-a89e-e8c00056ed2a.png">

Will need to look into alternative installation options.

**Comment by memsharded** [comment]
Can't you mark that vulnerability as "not affected" and resolve it?

**Comment by SimonHeybrock** [comment]
Probably in this case, but I would need to ensure that no other of our dependencies also uses `pyjwt`, as well as ensuring that we never add a *new* dependency in the future that uses `pyjwt`. So I don't have a good feeling about this.

**Comment by memsharded** [comment]
As this is a declared vuln, maybe we can try to backport the 2.0 fix, and if ``conan_server`` users are broken, the vulnerability reason should probably be enough to explain. Trying in https://github.com/conan-io/conan/pull/11350, lets see how it goes.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/11350 merged, next 1.49 release (to be released this week), will update pyjwt version
