### ISSUE TITLE
[bug] Conan --update does not work; will not downloaded updated version

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#11320]
Doing:
`conan install qt/5.15.2@  --update`
will give me:
```
`WARN: libpng/1.6.37: requirement zlib/1.2.11 overridden by freetype/2.11.1 to zlib/1.2.12 `
```

I have my own artifactory and uploaded some cci recipe+binaries there.
Now I wanted to install Qt.
I have this libpng `libpng/1.6.37` already in my local cache available, which depends on old `zlib/1.2.11`
However, upstream I updated all recipes to depend on newest `zlib/1.2.12` so in artifactory I have all recipe up to date.

even doing: `conan install libpng/1.6.37@  --update`.
will not update the recipe to latest version.
```
Installing package: libpng/1.6.37
Requirements
    libpng/1.6.37 from local cache - No remote
    zlib/1.2.11 from 'my-remote' - Cache
Packages
    libpng/1.6.37:7929d8ecf29c60d74fd3c1f6cb78bbb3cb49c0c7 - Cache
    zlib/1.2.11:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache

Installing (downloading, building) binaries...
zlib/1.2.11: Already installed!
libpng/1.6.37: Already installed!
Aggregating env generators
```

My conan conf:
```
default_package_id_mode = semver_direct_mode
```

### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 18.04
  * Compiler+version: gcc9
  * Conan version: 1.46.0
  * Python version: 3.6.9

![image](https://user-images.githubusercontent.com/42534866/170061080-720f1705-6aaa-4d00-a1cc-d49ffe78f63f.png)

**Comment by memsharded** [comment]
It seems this behavior is correct and the expected one.
It seems you disconnected the ``libpng`` package in your cache from the remote, read the message: `` libpng/1.6.37 from local cache - No remote``.

It hasn't a remote defined, so it cannot update. Maybe you removed the ``remote`` at some point or something like that, but if you installed the ``libpng/1.6.47`` from the remote, it should be able to update. You might also try to explicitly provide a ``--remote=xxxx`` argument to define it.

**Comment by derived-coder** [comment]
Doing `conan install libpng/1.6.37@ --update --remote ...` has fixed it. Now I got the latest recipe. Thanks.

Where can I see in the conan cache which package is connected with which remote? There must be some file I guess?

**Comment by memsharded** [comment]
> Where can I see in the conan cache which package is connected with which remote? There must be some file I guess?

``conan remote list_ref`` will display the existing remotes associations (check the ``conan remote --help`` for other related commands). The information is stored in some mestadata json files inside the cache, for each package, better use the command.

**Comment by derived-coder** [comment]
okay, found it.

What was the reason behind this? To say, when no remote is defined, we will not overwrite the package with some upstream version?

**Comment by memsharded** [comment]
> What was the reason behind this? To say, when no remote is defined, we will not overwrite the package with some upstream version?

yes, the rationale is that if the package was not installed from a remote, it cannot be updated from that remote.

**Comment by derived-coder** [comment]
thanks
