### ISSUE TITLE
[question] Setting output_folder of editable using yaml workspace file

### ISSUE THREAD

**Issue by FranzPoize** [conan-io/conan#11322]
Hello !
I'm working with workspace using a workspace yaml file and I'm trying to make it work with the new layout function. I am also using a base conanfile class using the python_requires_extend.

This is my base conanfile class
```python
def shred_basic_layout(conanfile, src_folder="."):
    conanfile.folders.build = os.path.join("..", "build_ws")
    if conanfile.settings.get_safe("build_type"):
        conanfile.folders.build = os.path.join(conanfile.folders.build, str(conanfile.settings.build_type))
    conanfile.folders.generators = os.path.join(conanfile.folders.build, "conan")
    conanfile.cpp.build.bindirs = ["."]
    conanfile.cpp.build.libdirs = ["."]
    conanfile.folders.source = src_folder

class ShredBaseConanFile(object):
    def layout(self):
        shred_basic_layout(self)
```
This is just a modified version of the basic_layout

In my conanfile I just set the python_requires_extend to ShredBaseConanFile.

When I run `conan workspace install` with the old version (i.e just using the layout file) all the files generated by my generators where written to the `build_folder` however when I use the layout function only the files generated by the `new_gen` generators (in my case CMakeToolchain) are placed in the build folder. All the `old_gen` generator (in my case cmake_paths and cmake_find_package_multi or cmake_find_package) write their files in the base_folder.

If I'm not mistaken the output_folder of the `old_gen` generators is taken from `conanfile.install_folder` which in turns is `self.folders.base_install`. 

From `conans/client/installer.py` line 481
```python
# New editables mechanism based on Folders
        if hasattr(conanfile, "layout"):
            output = conanfile.output
            output.info("Rewriting files of editable package "
                        "'{}' at '{}'".format(conanfile.name, conanfile.generators_folder))
            self._generator_manager.write_generators(conanfile, conanfile.install_folder,
                                                     conanfile.generators_folder, output)
```

For editables with a layout the install_folder is set to the output_folder of the editable

From `conans/client/installer.py` line 470
```python
if hasattr(conanfile, "layout"):
            conanfile.folders.set_base_folders(base_path, package_layout.output_folder)
```

Using the workspace yaml I did not find a way to set the output_folder of an editable. Is there any way to do so ?

**Comment by memsharded** [comment]
Hi @FranzPoize 

Workspace feature has been on hold for quite a long time now, as it was half baked, and it had a few challenges with the poor experience managing the underlying "editables"
The feature has been even removed in 2.0, some time after it, we will resume work on it, but at the moment it was more a problem than a solution. The recommended way would be to fully script the management of the set of packages to be managed, using the new ``editables`` features, with the layout. It will probably be a relatively simple script, while keeping full flexibility and control. Conan 2.0 also includes some further improvements, for example, it will be possible to directly build editable dependencies from the consumers, with incremental builds, that will probably help too.

**Comment by FranzPoize** [comment]
Is it okay if I close this because we switched to the new gen generator for all our editables and we don't have this issue anymore.

I want to say that we still love the workspace feature, please don't kill it :D

**Comment by memsharded** [comment]
We are finally resuming work on workspace in Conan 2, sorry for the long delay, see the current PR: https://github.com/conan-io/conan/pull/17272, which implements exactly what you are requesting here, we are aiming for next Conan 2.10 release this month.

Also, the ticket that we are using to centralize feedback for Conan 2 workspaces is https://github.com/conan-io/conan/issues/15992, please track/follow that one, so you get notifications from it, lets close this ticket and continue there. Thanks very much for your feedback.

**Comment by memsharded** [comment]
The new Conan 2 ``Workspace`` feature is already out there. Please give it a try, and create new tickets for any question, issue or suggestion.

It is in incubating: https://docs.conan.io/2/incubating.html, so please give your feedback in https://github.com/conan-io/conan/issues/18263 even if everything works smoothly and you have no other comments. Thanks for your feedback!
