### ISSUE TITLE
[bug] bazeldeps skip lib incorrectly if filename both starts and ends with lib

### ISSUE THREAD

**Issue by kkpattern** [conan-io/conan#11331]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version:
  * Conan version: 1.48.1
  * Python version: 3.10.1

### Steps to reproduce (Include if Applicable)
If a lib filename both starts and ends with lib, when use conan install with bazel generator, the lib will be incorrectly skipped.
For example, if I have a lib named `libxxx.lib`, the generated bazel BUILD file won't contains this lib.

The bug if caused in `_get_lib_file_paths` in `conan/tools/google/bazeldeps.py`:

```python
    def _get_lib_file_paths(self, libdirs, lib):
        for libdir in libdirs:
            if not os.path.exists(libdir):
                self._conanfile.output.warning("The library folder doesn't exist: {}".format(libdir))
                continue
            files = os.listdir(libdir)
            for f in files:
                full_path = os.path.join(libdir, f)
                if not os.path.isfile(full_path):  # Make sure that directories are excluded
                    continue
                name, ext = os.path.splitext(f)
                if ext in (".so", ".lib", ".a", ".dylib", ".bc"):
                    if ext != ".lib" and name.startswith("lib"):
                        name = name[3:]
                if lib == name:
                    return full_path
        self._conanfile.output.warning("The library {} cannot be found in the "
                                       "dependency".format(lib))
```

In our case, the lib is named `libacsdk.lib`, the `name` is `acsdk`, so the `if lib == name` will never be true.

One possible fix is test if the `lib` is equal to `f`(filename) before normalize the lib name. Like this:

```python
    def _get_lib_file_paths(self, libdirs, lib):
        for libdir in libdirs:
            if not os.path.exists(libdir):
                self._conanfile.output.warning("The library folder doesn't exist: {}".format(libdir))
                continue
            files = os.listdir(libdir)
            for f in files:
                full_path = os.path.join(libdir, f)
                if not os.path.isfile(full_path):  # Make sure that directories are excluded
                    continue
               # if filename is equal to lib, I think we should return it.
               if lib == f:
                    return full_path
                name, ext = os.path.splitext(f)
                if ext in (".so", ".lib", ".a", ".dylib", ".bc"):
                    if ext != ".lib" and name.startswith("lib"):
                        name = name[3:]
                if lib == name:
                    return full_path
        self._conanfile.output.warning("The library {} cannot be found in the "
                                       "dependency".format(lib))
```

If this fix is OK I can create a pull request.

**Comment by kkpattern** [comment]
We found another case the bazeldeps incorrectly skip a lib. So the root cause is not filename both starts and ends with lib, but the lib name is not "standard". But both cases can be fixed with the:

```python
if lib == f:
    return full_path
```

**Comment by memsharded** [comment]
Yes, @kkpattern if you want to submit a PR, that would be great.
If possible, try to add some test for it, if you can't or need help, please ask.

Thanks!

Note to us: We probably want to have a look, because other integrations might also assume the same and might benefit from this too
