### ISSUE TITLE
[dev2][feature] `conf` review and improvements

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#11346]
Several points here:
* Fix the wrong behavior about writing `-c core.xxx="whatever"` via CLI. This should raise an error because those configurations are not used by the profiles. Could we add another option like `-c:global core.xxxxx="whatever"`?
* Centralize all the existing configurations (`tools.xxx` and `core.xxx`) in one place (a python list, dict, whatever), and raise an error if `conf.get("xxxxx")` is not declared there (except for `user.xxxx` configurations).
* Perhaps, we should bring the `conan config list` command back to show all the available configurations. 

_Related to https://github.com/conan-io/conan/issues/11205_

**Comment by datalogics-kam** [comment]
> Perhaps, we should bring the `conan config list` command back to show all the available configurations.

I _just_ used that to verify the name of a configuration variable without resorting to the doc, so I would find it handy.

**Comment by memsharded** [comment]
> I just used that to verify the name of a configuration variable without resorting to the doc, so I would find it handy.

Yes, agree, lets restore this (or even better, an improved version of this with patterns would be great, like ``conan config list *cmake*``)

**Comment by lasote** [comment]
FYI, these ones are missing from the conf:

```
 unknown_mode = new_config.get("core.package_id:default_unknown_mode", default="semver_mode")
    non_embed_mode = new_config.get("core.package_id:default_non_embed_mode", default="minor_mode")
    # recipe_revision_mode already takes into account the package_id
    embed_mode = new_config.get("core.package_id:default_embed_mode", default="full_mode")
    python_mode = new_config.get("core.package_id:default_python_mode", default="minor_mode")
    build_mode = new_config.get("core.package_id:default_build_mode", default=None)
```

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11575
