### ISSUE TITLE
[bug] C compiler unable to create executables with nearly identical profiles

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#11340]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc 8
  * Conan version: 1.48.1
  * Python version: 3.8.10

### Profile
```ini
include(default)

api_level=16
target_host=i686-linux-androideabi
android_ndk={{os.getenv("ANDROID_NDK")}}
android_root=$android_ndk/platforms/android-$api_level/arch-x86

[settings]
arch=x86
build_type=Release
compiler=clang
compiler.libcxx=c++_shared
compiler.version=8
os=Android
os.api_level=$api_level

[options]

[conf]
tools.android:ndk_path=$android_ndk
tools.microsoft.msbuild:max_cpu_count={{os.cpu_count()}}
tools.build:processes={{os.cpu_count()}}
tools.build:processes={{os.cpu_count()}}
tools.gnu.make:jobs={{os.cpu_count()}}
tools.ninja:jobs={{os.cpu_count()}}

[env]
CONAN_CPU_COUNT={{os.cpu_count()}}
ANDROID_NDK_ROOT=$android_ndk
CONAN_CMAKE_SYSROOT=$android_root
CONAN_CMAKE_ANDROID_NDK=$android_ndk
CONAN_CMAKE_FIND_ROOT_PATH=$android_ndk/platforms/android-$api_level
CONAN_CMAKE_TOOLCHAIN_FILE=$android_ndk/build/cmake/android.toolchain.cmake

# Set toolchain
PATH=[$android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
LD=$target_host-ld
STRIP=$target_host-strip
RANLIB=$target_host-ranlib
CC=$target_host$api_level-clang
CXX=$target_host$api_level-clang++

# Flags
LDFLAGS=-llog
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
checking whether to enable maintainer-specific portions of Makefiles... no
checking for i686-linux-android-gcc... i686-linux-androideabi16-clang
checking whether the C compiler works... no
configure: error: in `/home/wbehrens@staudertech.local/.conan/data/libjpeg/9d/_/_/build/1016b0a10db23083447e439f4d329f19eba99d4c':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

I have a nearly identical profile for building for Android arm yet when I copied it and changed it to compile for x86 I get the above error.

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

We would need to have something that we can reproduce, if you could please attach some conanfile & build scripts that reproduces this error, that would be very useful. It is very likely that this issue is caused by some specifics of a recipe or by the specifics of the build system of the library.

**Comment by wbehrens-on-gh** [comment]
This is using the libjpeg/9d recipe in conan-center but I have another custom recipe that just hangs when it tries to compile with this profile.

**Comment by memsharded** [comment]
And what is the command to reproduce? are you using the recommended 2 profiles (build/host)?

It is likely that this could be an issue of the recipe, because they haven't upgraded yet to the new build system integrations. It would be better to report Conan issues, if it could be reproduced with some of the new templates, like ``conan new hello/0.1 --template=cmake``.

**Comment by wbehrens-on-gh** [comment]
I get `ERROR: Template doesn't exist: home/wbehrens@staudertech.local/.conan/templates/command/new/cmake` when I run that command

**Comment by wbehrens-on-gh** [comment]
> And what is the command to reproduce? are you using the recommended 2 profiles (build/host)?
> 
> It is likely that this could be an issue of the recipe, because they haven't upgraded yet to the new build system integrations. It would be better to report Conan issues, if it could be reproduced with some of the new templates, like `conan new hello/0.1 --template=cmake`.

I got one to generate using the cmake_lib template and building with `conan create . hello/0.1 -pr:b=default -pr:h=path/to/Android_x86.jinja`

but this gives me
```
Exporting package recipe
hello/0.1@hello/0.1 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
hello/0.1@hello/0.1 exports_sources: Copied 1 '.cpp' file: hello.cpp
hello/0.1@hello/0.1 exports_sources: Copied 1 '.h' file: hello.h
hello/0.1@hello/0.1: A new conanfile.py version was exported
hello/0.1@hello/0.1: Folder: /home/wbehrens@staudertech.local/.conan/data/hello/0.1/hello/0.1/export
hello/0.1@hello/0.1: Exported revision: 4fc80e430f8244be40256fab755f8c43
Configuration (profile_host):
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=c++_shared
compiler.version=8
os=Android
os.api_level=16
os_build=Linux
[options]
[build_requires]
[env]
ANDROID_NDK_ROOT=None
AR=i686-linux-androideabi-ar
AS=i686-linux-androideabi-as
CC=i686-linux-androideabi16-clang
CHOST=i686-linux-androideabi
CONAN_CMAKE_ANDROID_NDK=None
CONAN_CMAKE_FIND_ROOT_PATH=None/platforms/android-16
CONAN_CMAKE_SYSROOT=None/platforms/android-16/arch-x86
CONAN_CMAKE_TOOLCHAIN_FILE=None/build/cmake/android.toolchain.cmake
CONAN_CPU_COUNT=16
CXX=i686-linux-androideabi16-clang++
LD=i686-linux-androideabi-ld
LDFLAGS=-llog
PATH=[None/toolchains/llvm/prebuilt/linux-x86_64/bin]
RANLIB=i686-linux-androideabi-ranlib
STRIP=i686-linux-androideabi-strip
[conf]
tools.android:ndk_path=!
tools.microsoft.msbuild:max_cpu_count=16
tools.build:processes=16
tools.gnu.make:jobs=16
tools.ninja:jobs=16

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

hello/0.1@hello/0.1: Forced build from source
hello/0.1@hello/0.1 (test package): Installing package
Requirements
    hello/0.1@hello/0.1 from local cache - Cache
Packages
    hello/0.1@hello/0.1:33d5316e40ea213a2473ff5d851587b8a1a34541 - Build

Cross-build from 'Linux:x86_64' to 'Android:x86'
Installing (downloading, building) binaries...
hello/0.1@hello/0.1: Configuring sources in /home/wbehrens@staudertech.local/.conan/data/hello/0.1/hello/0.1/source/.
hello/0.1@hello/0.1: Copying sources to build folder
hello/0.1@hello/0.1: Building your package in /home/wbehrens@staudertech.local/.conan/data/hello/0.1/hello/0.1/build/33d5316e40ea213a2473ff5d851587b8a1a34541
hello/0.1@hello/0.1: Generator txt created conanbuildinfo.txt
hello/0.1@hello/0.1: Calling generate()
ERROR: hello/0.1@hello/0.1: Error in generate() method, line 33
        tc.generate()
        ConanException: CMakeToolchain needs tools.android:ndk_path configuration defined
```

**Comment by wbehrens-on-gh** [comment]
my bad I didn't have the ndk variable set, setting the ANDROID_NDK env variable it builds the hello package with no issue. I'm not sure where the problem is? could it be an issue in the autotools helper? is there a template for autotools I could test on? @memsharded

**Comment by franramirez688** [comment]
Hi @WilliamBehrens 

Yes, we have a couple of them. You can try `autotools_lib` and/or `autotools_exe`. For instance:

```bash
conan new hello/1.0 -m autotools_lib
```
Notice that these templates are using the new generators `AutotoolsToolchain`, `Autotools`, and `AutotoolsDeps ` (see more information [here](https://docs.conan.io/en/latest/reference/conanfile/tools/gnu.html)), but, as I can see, `libjpeg/9d` uses the legacy ones so you can get unexpected errors.

We're working hard on the new Conan 2.0 that will use those new generators by default, so, at some point, all the recipes will be ready to use and up to date.

**Comment by wbehrens-on-gh** [comment]
well I realized one of my problems, the target_host should be `i686-linux-android` not `i686-linux-androideabi`. but that only gets me so far because no the issue I'm getting is a linker error 
![image](https://user-images.githubusercontent.com/35979547/171216031-f7abfffb-2f9c-4062-a31e-54beafa75a02.png)


so it's building packages just not for the right architecture?
