### ISSUE TITLE
[feature] Support "Variable Substitution" in `conanfile.txt`. (for `imports` section)

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#11349]
## Problem Description

This issue is related to that: https://github.com/conan-io/conan/issues/7438

If we use **Multi-Config** generator of CMake (for example `Ninja Multi-Config`), there will be at least 2 generated output directories by default (Debug, Release,...).

If we want to install 2 different configurations (**Debug** and **Release**), then we have to run `conan install` command **twice** with `--settings build_type=Debug` and `--settings build_type=Release`, respectively. 

However, the destination of `imports` section in `conanfile.txt` seems to be **HARD-CODED**. For example:

```
[imports]
bin, *.dll    -> ./Debug/bin
lib, *.dylib* -> ./Debug/bin
```

## Feature Request

Therefore, I suggest that `conanfile.txt` introduces some **"Variable Substitutions"**, which allow us to use them in 
[`imports`](https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports) section. For example:

```
[imports]
bin, *.dll    -> ./${build_type}/bin
lib, *.dylib* -> ./${build_type}/bin
```

The idea comes from the workaround of @anton-danielsson mentioned in comment: https://github.com/conan-io/conan/issues/7438#issuecomment-711290419. He uses `conanfile.py`, instead.

> ```python
> def imports(self):
>     self.copy("*.dll", str(self.settings.build_type), "bin")
>     self.copy("*.dll", str(self.settings.build_type), "lib")
>     self.copy("*.dylib", str(self.settings.build_type), "lib")
> ```

As we can see, python will access the value of the member, `self.settings.build_type`.

## Environment and Version

- OS version: **Windows 11**
- Conan version: **Conan 1.48.1**
- Python version: **Python 3.9.2**

**Comment by memsharded** [comment]
Hi @hwhsu1231 

I am sorry, but we will not add extra logic to the ``conanfile.txt``. These are intended to be a very simple solution, for basic cases. It doesn't make sense to invent an extra custom DSL that needs to be documented, users need to learn, when there is a more general, flexible, documented and most importantly, standard (because it is Python code) solution to it, which is using a ``conanfile.py``.

Thanks for the feedback and the suggestion.
