### ISSUE TITLE
[bug] CI tests broken or inconsistent - unchanged recipe from CCI now won't build

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#11356]
Please refer to PR https://github.com/conan-io/conan-center-index/pull/10983

I've been hitting my head against the wall, wondering why my only-slightly-modified HDF5 recipe won't pass the CI tests.

Now I see that the existing CCI recipe won't pass the CI.   I've pushed a PR with a trivial change (in the description) and the recipe fails to pass the CI.

It was able to pass only 26 days ago, in https://github.com/conan-io/conan-center-index/pull/10552

I first attempted to rebuild the original recipe in #10836 ... 
That time the CI built and older version of HDF5, and now I see a completely new error.
```
/home/conan/w/prod/BuildSingleReference/.conan/data/hdf5/1.10.5/_/_/package/1ea8e52079662e1f84321eeeac304c752fdf6af4/lib/libhdf5_debug.so: undefined reference to `H5libhdf5_settings'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is very frustrating, as this isn't even the issue I was struggling with ... now I have more issues to deal with.

My struggles have been related to the new version of HDF5 linking zlib, and the fact that HDF5 wasn't linking to it at all.
Even more confusing, I don't even know why it was able to successfully build+test on some of the linux CIs, and not others.

WHY: When building HDF5 would NOT link zlib into the shared lib, instead it (seemed to) add it to a list of libraries that any linker of the shared library would link to.   BUT, conan's CI/CCI builds all libraries as static, so a shared-hdf5 would link a static zlib.    The consumer programs (like "mirror_server", in hdf5) would not link to zlib at all.    I think.
It is hard to tell because it would build ok on some platforms.

Example:
https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/10836/9-linux-gcc/hdf5/1.12.1//summary.json
Filter Shared=true, build_type=Release, version=1 (to see both 10 and 11)
It compiled with:
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
[options]
hdf5:shared=True
```
But failed with:
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
hdf5:shared=True
```

**Comment by memsharded** [comment]
Sorry this was not responded back then.

ConanCenter CI has completely changed, I am closing this as solved, or please create new tickets in the ``conan-center-index`` repo, thanks for your feedback.
