### ISSUE TITLE
[feature] conan info to return package_info related data

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#11362]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Collecting information from an existing conan package through `conan info` returns some useful information but not everything that could be required relating to the consumption of a package.

Could it also return information from the recipe data in `cpp_info` that is created for package consumption in the `package_info()` method?

We are trying to bridge build toolchains where some libraries are packaged as conan packages but need to be consumed without conan. We are thus 'inspecting' a conan package to collect the necessary information to be able to correctly use it in a different toolchain.

**Comment by memsharded** [comment]
Hi @SeanSnyders 

We have an issue for next beta.1 here: https://github.com/conan-io/conan/issues/11327 that plans to add extra information to the output of ``conan graph info`` (equivalent to ``conan info`` in Conan 2.0). I'd suggest to comment in that issue to ask for this, and follow up there, I don't think this will be possible to scope for Conan 1.X.

**Comment by SeanSnyders** [comment]
Thanks @memsharded, I added a comment in that issue you mentioned.

Would there be a workaround for Conan 1.x to be able to extract this resolved information?
This is quite a critical step in our situation to be able to gradually migrate to using Conan packages whilst still supporting our existing toolchains.

**Comment by SeanSnyders** [comment]
Hi @memsharded, would love some insight into workaround(s) for Conan 1.x.

Can I load and evaluate the recipe in question? Maybe create a custom generator to write out `cpp_info` and then specify that generator in a `conanfile.txt` run it with the recipe in question and then ingest its output, etc?

**Comment by memsharded** [comment]
> Can I load and evaluate the recipe in question? 

Individual recipes can't be evaluated in isolation, only as part of the dependency graph.
In Conan 1.X you can access the dependencies information in the ``generate()`` method of a consumer ``conanfile.py`` via ``self.dependencies``, which is something you can iterate, access the ``self.dependencies["mypkg"].cpp_info`` structure too. You can put the code that iterates and return the cpp_info in your desired format in a ``python_requires``, then call it in the consumer ``generate()`` method.

**Comment by SeanSnyders** [comment]
If I do not have access to the package to add in this `python_requires` or change its code, could I do it in some other way as I originally described?

- `pkgA` is the package I want to get the `cpp_info` of.
- Create a custom generator, e.g. `CppInfoGenerator`, that extracts this information into a file in my format of choice. As all generators are run during a package `generate()` method, this would give the generator access to `self.conanfile.deps_cpp_info` as per Conan [custom generator docs](https://docs.conan.io/en/latest/reference/generators/custom.html#custom-generator).
- Create a `conanfile.txt` that specifies `pkgA` as a requirement and `CppInfoGenerator` as a generator.
- `conan install` using that `conanfile.txt`.
- use the file that `CppInfoGenerator` produced.

Could this work?

**Comment by memsharded** [comment]
Yes, the solution I was suggesting is basically the same, but just with modern tools:

- Use ``self.dependencies`` instead of ``deps_cpp_info``
- Use a ``conanfile.py`` instead of a ``conanfile.txt``, with a ``generate()`` method and the ``python_require``

It should work, yes.

**Comment by memsharded** [comment]
``conan graph info`` in Conan 2.0 returns way more information than this.

Closing this ticket as implemented in Conan 2
