### ISSUE TITLE
[bug] `conan list packages` is broken

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#11370]
### Environment Details (include every applicable attribute)
  * Operating System+version: `21H2 (OS Build 19044.1706)`
  * Compiler+version: N/A
  * Conan version: `←[1m←[32mConan version 2.0.0-alpha7←[0m `
  * Python version: `Python 3.9.7`

### Steps to reproduce (Include if Applicable)

run `conan list packages zlib/1.2.11@#latest -r conanv2`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
conan list packages zlib/1.2.11@#latest -r conanv2
←[1m←[34mconanv2:←[0m
←[1m←[31m  ERROR: 500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. [Remote: conanv2]←[0m 
```

**Comment by memsharded** [comment]
This is a known issue with Artifactory server. Needs to be addressed in the server, so it will take some time.

**Comment by beenjohn** [comment]
Hi @memsharded, is there any progress on this ticket, or is it still in the queue? It appears to affect conan download in 2.X as well.

**Comment by memsharded** [comment]
Yes, still in the queue, sorry, not labeled as critical atm.
The current workaround would be to download all binaries to cache, then list them on the cache, or use Artifactory API to query folders matching package-ids.

**Comment by SSE4** [comment]
@memsharded what's the replacement command, if `conan list packages` still broken?

**Comment by memsharded** [comment]
> use Artifactory API to query folders matching package-ids.

I think that downloading binaries will be too heavy, I would try the API

**Comment by memsharded** [comment]
Or, if you can clarify the full process, why do you need to query all existing ``package_ids``, then maybe we could try to figure out alternatives

**Comment by SSE4** [comment]
> Or, if you can clarify the full process, why do you need to query all existing `package_ids`, then maybe we could try to figure out alternatives

to understand, which package_ids have to be built on CI, and which could be safely skipped, cause already built.

**Comment by SSE4** [comment]
> I think that downloading binaries will be too heavy, I would try the API

is there a (one-liner) curl command to obtain them or something? or to be investigated?

**Comment by memsharded** [comment]
> to understand, which package_ids have to be built on CI, and which could be safely skipped, cause already built.

If you are doing some other ``conan graph info`` commands, for the active profiles (I recall that it was being used), that doesn't provide the information if needs to be built or not?

> is there a (one-liner) curl command to obtain them or something? or to be investigated?

I don't know, to be investigated

**Comment by SSE4** [comment]
> If you are doing some other `conan graph info` commands, for the active profiles (I recall that it was being used), that doesn't provide the information if needs to be built or not?

if it doesn't communicate to the remotes, it has no idea if they are available in that remote.
(in generic case, there are two different remotes - one is to consume dependencies from the conan center index. another one is to upload build results. the latter is a temporary repository, which is used to promote binaries later. if you do N builds of the same commit, it might take several iteration until all the possible configurations are already built).

**Comment by memsharded** [comment]
> if it doesn't communicate to the remotes, it has no idea if they are available in that remote.

If the job is running in a clean cache, it is impossible that the binary exist if it is not in the remote. If it is not running in a clean cache, but the cache is reused for the same commit, then it is fine, the binary will be there anyway for later upload? You are trying to define if a package should be built or not. If the package exists, no matter where, then it doesn't need to be built?

**Comment by SSE4** [comment]
> If the job is running in a clean cache, it is impossible that the binary exist if it is not in the remote. If it is not running in a clean cache, but the cache is reused for the same commit, then it is fine, the binary will be there anyway for later upload? You are trying to define if a package should be built or not. If the package exists, no matter where, then it doesn't need to be built?

I'll try to be more specific, maybe it will shed some light...
there are several remotes:
1. `conan-center` - it's the one where packages (dependencies) are downloaded from. read-only.
2. `PR-XXX` - a temporary repository to upload built artifacts. write-only. later, it will be promoted into `conan-center`, but it's only after PR is merged. once promoted, repository is deleted.

then, imagine we have `zlib` binaries on conan-center. and we're trying to build `boost`, which depends on `zlib`.
now imagine we are building 100 configurations.
eventually, PR failed (due to some infrastructure error) after building 40 packages, and these 40 packages exist in `PR-XXX`.
we re-try PR build to build 60 missing packages, but we have to identify what are these 60 package IDs we still need to build?
we obviously, don't want to build all 100, as it's a waste of time (recipe didn't change between these two CI runs).

so, if I run `conan graph info` in the clean cache (as we run builds in docker containers, cache is always clean), it will say all 100 of them are missing. but it will report 100 package IDs for all our configurations, and it's completely fine. let's say it's `List<PackageID> A`, and it's size is 100.
now, as a next step, we run `conan list packages -r PR-XXX` to find out what are the package IDs on `PR-XXX` remote. that should report `List<PackageID> B`, and it's expected size is 40.
finally, we compute `List<PackageID> C = A - B`, which should result in 60 missing packages.

as `conan graph info` runs on clean cache, and only with `conan-center` remote (it doesn't know about `PR-XXX`, and doesn't need to know about it at that step), it obviously cannot report list B - it can only report list A. and it's fine, that's the information needed to be computed on that particular step.

then `conan list packages` runs against a *different* remote (PR-XXX), and reports list B.

these two commands run in different (isolated) parts of code, and don't know about each other. changing `conan graph info` to be aware of a secondary remote is possible, but it requires a significant changes in architecture. also, it breaks some design principles, like single responsibility.

given all of the above in mind, there should be some command (conan client, or curl, it doesn't matter much) which acts as a drop-in replacement for `conan list packages`.

**Comment by memsharded** [comment]
> so, if I run conan graph info in the clean cache (as we run builds in docker containers, cache is always clean), it will say all 100 of them are missing. but it will report 100 package IDs for all our configurations, and it's completely fine. let's say it's List<PackageID> A, and it's size is 100.

I am not sure about this. ``conan graph info`` also resolves against remotes. If the right remote is defined, it will tell you that such binary, with such package_id exists or not. It will not say that 100 of them are missing, it will tell you that 60 are missing. You need to pass the ``--build=missing`` arg, but it should work. 

> as conan graph info runs on clean cache, and only with conan-center remote (it doesn't know about PR-XXX, and doesn't need to know about it at that step), it obviously cannot report list B - it can only report list A. and it's fine, that's the information needed to be computed on that particular step.

Why not adding the ``PR-XXX`` remote? You are passing it to the ``conan list packages`` as an argument, so it seems it is available information.

> these two commands run in different (isolated) parts of code, and don't know about each other. changing conan graph info to be aware of a secondary remote is possible, but it requires a significant changes in architecture. also, it breaks some design principles, like single responsibility.

If adding a new ``conan graph info`` as a replacement of ``conan list packages`` is still too slow (I don't care about other parts of the CI), then the only possibility would be trying with Artifactory API/AQL or the like.

**Comment by SSE4** [comment]
> Why not adding the `PR-XXX` remote? You are passing it to the `conan list packages` as an argument, so it seems it is available information.

it is possible, just may need some adjustments in code. e.g. remote might not always exist at that point. also, we have a code to cache package ID computation in .json file, so `conan graph info` doesn't run for second re-build (right now).

in other words, do I understand correctly that `conan list packages` replacement could be implemented on top of `conan graph info` (with some loop)? if so, why not implement it in conan client (e.g. `conan list-packages2`)?

otherwise, every user will have to figure it out, how to write that replacement on his own, which might be time consuming, and easy to make a mistake.

**Comment by memsharded** [comment]
> in other words, do I understand correctly that conan list packages replacement could be implemented on top of conan graph info (with some loop)? if so, why not implement it in conan client (e.g. conan list-packages2)?

It is impossible to loop over all possible infinite combinations of profiles that you need to feed to ``conan graph info`` to deduce the existing ``package_ids``.

> otherwise, every user will have to figure it out, how to write that replacement on his own, which might be time consuming, and easy to make a mistake.

This will be fixed in the server. Not every user use this feature. The best would be to provide them with an Artifactory query they could run.

**Comment by jgsogo** [comment]
(conan-center-index context)

There are at least to places where we want the list of package-ids. 
 * One of them is to know which packages to build. We have computed the pkg-ids (we compute them or retrieve from a cache), and we want to check which ones are already available in the remote. Here `conan graph info` could be a replacement, although iterating all the profiles will take longer than one single call to `conan list`... and this call cannot be cached, we need to query the remote for the packages that are available at that moment.
 * Another place where we need this feature is when we are going to _promote_ the packages to ConanCenter from the temporal repository. Due to some issues we had with Artifactory in the past, we promote the recipe first and then the packages one by one. Here we need to know which packages (folders) are in the remote. Here we don't use profiles, we just _promote_ all packages that are available (this approach has some advantages).
 
IMHO, if `conan list` doesn't work yet, using JFrog CLI can be the easiest alternative. It is very simple to list the directories under a given entry. The only drawback is that JFrog CLI cannot check anything (package integrity,...) it will just list folder names.

I agree that the _workaround_ could be documented (or even implemented behind the scenes in the Conan client) while Artifactory fixes this API endpoint.

**Comment by memsharded** [comment]
Fixed in https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.52 Artifactory 7.52, closing this issue.
