### ISSUE TITLE
[bug] V2 CLI outputs hashes that cannot be used in commands

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#11371]
### Environment Details (include every applicable attribute)
  * Operating System+version: `21H2 (OS Build 19044.1706)`
  * Compiler+version: N/A
  * Conan version: `←[1m←[32mConan version 2.0.0-alpha7←[0m `
  * Python version: `Python 3.9.7`

### Steps to reproduce (Include if Applicable)

apperently, CLI outputs "short hashes" (are they documented somewhere?):
```
Uploading zlib/1.2.12#87a7:1f7e#e97a

Uploading conan_package.tgz -> zlib/1.2.12#87a7:1f7e#e97a

Uploading conaninfo.txt -> zlib/1.2.12#87a7:1f7e#e97a

Uploading conanmanifest.txt -> zlib/1.2.12#87a7:1f7e#e97a
```
but trying to use them in CLI results in nothing:
```
conan list package-revisions zlib/1.2.12#87a7:1f7e -r conanv2
←[1m←[34mconanv2:←[0m
There are no matching package references
```
the one has to figure out what is the "real hash" and use it in CLI:
```
conan list package-revisions zlib/1.2.12#87a7211557b6690ef5bf7fc599dd8349:1f7e2290f74b199613e6b961a37f4b1bffd2dc9f  -r conanv2
←[1m←[34mconanv2:←[0m
←[1m←[37m  zlib/1.2.12#87a7211557b6690ef5bf7fc599dd8349:1f7e2290f74b199613e6b961a37f4b1bffd2dc9f#e97a0ff46effe89e7f91479505585dcf (2022-05-12 12:17:13 UTC)←[0m
←[1m←[37m  zlib/1.2.12#87a7211557b6690ef5bf7fc599dd8349:1f7e2290f74b199613e6b961a37f4b1bffd2dc9f#2d792f1dda3f12027eb1fa847ba072db (2022-05-05 10:39:08 UTC)←[0m
←[1m←[37m zlib/1.2.12#87a7211557b6690ef5bf7fc599dd8349:1f7e2290f74b199613e6b961a37f4b1bffd2dc9f#5574506f8fed03e0ba6cb71c849e3872 (2022-04-21 11:04:47 UTC)←[0m
```
that's not something easy and obvious, especially for newcomers.
either CLI should accept short hashesh, or always output real hashes, that can be used successfully in CLI.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11412
