### ISSUE TITLE
[question] Access Control Lists

### ISSUE THREAD

**Issue by joshvazquez** [conan-io/conan#11375]
I'm running Conan server with a custom authenticator. Can I also control the [read/write permissions](https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#permissions-parameters) with a custom authorizer? Or do the permissions have to be listed explicitly in the server.conf? I want to defer to our authorization system to get up-to-date permissions per user.

Could I just modify [this](https://github.com/conan-io/conan/blob/develop/conans/server/launcher.py#L32-L39) to allow loading a custom authorizer plugin like it currently does for authentication plugins? And would that be a contribution you are interested in?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @joshvazquez 

The current authorizer is a bit more hardcoded than the authenticator, indeed. But even if not a similar plugin mechanism is defined for permissions, the ``Authorizer`` abstract base class is there, deriving from it and replacing the ``BasicAuthorizer`` one in the launcher seems easy doable.

I am not sure the contribution would be of high value for other users, it of course depends on the risk of breaking something and possible future maintenance. To be honest, at the moment we are a bit swamped trying to get 2.0 out, so if it is something that can wait, maybe better if you can gain experience using that for a while, before submitting it. Thanks anyway!

**Comment by joshvazquez** [comment]
Thanks for your response. I was able to set up a custom authorizer modeled after the Authorizer ABC and successfully allow and deny requests using my class.

This can wait, so I will work on it internally for now.

Thanks!

**Comment by memsharded** [comment]
Closing this as not planned at the moment.
