### ISSUE TITLE
[question] options are not propagated when using python_requires & python_requires_extend

### ISSUE THREAD

**Issue by pasrom** [conan-io/conan#11373]
As it can be seen in the test below, when using options with multiple levels of python_requires, they are not propagated downwards.
Could this be a limitation mentioned in [docs](https://docs.conan.io/en/1.48/extending/python_requires.html#limitations)? When yes, is there a better workaround as defining the option explicitly for the package (`-o logic-build:shared=False`)?

### Environment Details
  * Operating System+version: Ubuntu 20.04.4 LTS
  * Compiler+version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  * Conan version: 1.48.1
  * Python version:  3.8.10

### Steps to reproduce
```
import textwrap

from conans.test.utils.tools import TestClient

def test_python_requires_leveled_w_options():
    client = TestClient()
    conanfile = textwrap.dedent("""
        from conans import ConanFile

        class LogicBuild(object):
            version = "2.0.0"
            name = "logic-build"
            options = {
                "shared" : ["True", "False"],
            }

        class BaseLogicBuild(ConanFile):
            name = "base-logic-build"
        """)
    client.save({"conanfile.py": conanfile})
    client.run("export . base-logic-build/0.1.0@user/channel")

    conanfile = textwrap.dedent("""
        from conans import ConanFile

        class LogicBuild(ConanFile):
            python_requires = "base-logic-build/0.1.0@user/channel"
            python_requires_extend = "base-logic-build.LogicBuild"
        """)
    client.save({"conanfile.py": conanfile})
    client.run("create . @user/channel -o shared=False")

    conanfile = textwrap.dedent("""
        from conans import ConanFile

        class PackageBuild(object):
            version = "1.0.0"
            name = "package-build"
            options = {
                "shared" : ["True", "False"],
            }

            def requirements(self):
                self.requires("logic-build/2.0.0@user/channel")

        class BasePackageBuild(ConanFile):
            name = "base-package-build"
        """)
    client.save({"conanfile.py": conanfile})
    client.run("export . base-package-build/0.1.0@user/channel")

    conanfile = textwrap.dedent("""
        from conans import ConanFile

        class PackageBuild(ConanFile):
            python_requires = "base-package-build/0.1.0@user/channel"
            python_requires_extend = "base-package-build.PackageBuild"
        """)
    client.save({"conanfile.py": conanfile})
    # works
    client.run("create . @user/channel -o shared=False -o logic-build:shared=False")
    # does not work
    client.run("create . @user/channel -o shared=False")
```

### Logs

> E           Exception: 
E           ------------------------ Command failed (unexpectedly): ------------------------
E           create . @user/channel -o shared=False
E           ----------------------------------- Output: ------------------------------------
E           [HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
E           [HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
E           [HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
E           Exporting package recipe
E           package-build/1.0.0@user/channel: The stored package has not changed
E           package-build/1.0.0@user/channel: Exported revision: d0a9bc37ca54a801eb43831dd9484366
E           Configuration:
E           [settings]
E           arch=x86_64
E           arch_build=x86_64
E           build_type=Release
E           compiler=gcc
E           compiler.libcxx=libstdc++
E           compiler.version=9
E           os=Linux
E           os_build=Linux
E           [options]
E           shared=False
E           [build_requires]
E           [env]
E           
E           ERROR: logic-build/2.0.0@user/channel: 'shared' value not defined
E           
E           --------------------------------------------------------------------------------

**Comment by memsharded** [comment]
Hi @pasrom 

I am not sure why this would be an error. ``logic-build/2.0.0@user/channel`` has a ``shared`` option defined in it, that doesn't have a default, so it really needs a value to be passed on the command line (or profile).

You could as well define a ``default_options = {"shared": False}`` in the ``base-logic-build`` recipe.

**Comment by pasrom** [comment]
@memsharded thank you for your quick reply.
Yes, you are right, that is better suited as question.
I think i got it now, thank you again.
