### ISSUE TITLE
[question] semver_direct_mode dependency with user/channel included

### ISSUE THREAD

**Issue by sct2010** [conan-io/conan#11389]
Hi all,

I am looking for some input to handle our workflow correctly. In general we use conan with the semver_direct_mode for the package id. In general we follow the semver idea with our official builds and this works as expected.

Recently we introduced developer snapshot builds and ran into a dependency issue. Let me explain how I implemented:
As soon as a developer builds a package, it creates a version 9999.0.0-alpha.x. To distinguish the different developer packages, we decided to do so by setting the user/channel to dev/issueNr. So far everything works as expected. The problem starts when we build different dependency trees. Lets me show an example with a simple graph:

```
App -> libA -> libB
     \----------> libB
```
In the example, our devs are only working on the `App` and `libB`. `libA` is available in the artifactory as `libA/0.8.3@company/release` and depends on `libB/0.6.0@company/release`. The conanfile of the libs have a requires similar to `("libB/[~0.6.0-alpha || ~9999.0.0-alpha]@company/release"),`

Developer A starts working on Issue Nr 12 and builds a custom `libB` and wants to us it in the `App`. Now the packages involved are as follows:
```
App/9999.0.0-alpha.1@dev/12
  -> libA/0.8.3@company/release -> libB/9999.0.0-alpha.1@dev/12
  -> libB/9999.0.0-alpha.1@dev/12
```

After a while developer B starts to work on another issue (90) and builds also a custom version of the `App` and `libB`. When he wants to build the app, the following happens:
1. He builds a custom `libB/9999.0.0-alpha.1@dev/90`
2. He starts building the app and does a conan install. Unfortunately it starts downloading the `libA/0.8.3@company/release` with depends on `libB/9999.0.0-alpha.1@dev/12` instead of building a new one depending on `libB/9999.0.0-alpha.1@dev/90`.
We end with something like this
```
App/9999.0.0-alpha.1@dev/90
  -> libA/0.8.3@company/release  -> libB/9999.0.0-alpha.1@dev/12
  -> libB/9999.0.0-alpha.1@dev/90
```

The issue is, in the semver_direct_mode the user/channel is not included in the packageID. Therefore conan can not distinguish between the two `libB` and has already a `libA`.

Is it possible to keep the semver_direct_mode behavior and also include the user/channel? How can I achieve this?

Regards Tobias

**Comment by memsharded** [comment]
Hi @sct2010 

Please, let me first clarify about user/channel, specially moving forward: user/channel in 2.0 should be considered immutable. The ``conan copy`` command disappear. The ``channel`` shouldn't be used for promotion of quality packages, but instead multiple server repositories, and running promotions, (copies of immutable packages from one repo to another) is the recommended mechanism.

Regarding your question, adding specifically the user/channel to the default mode is possible, but there is not direct built-in mode. The syntax would be:

```python
def package_id(self):
     mydep = self.info.requires["mydep"]
     mydep.user = mydep.full_user
     mydep.channel = mydep.full_channel
```

If you need for all deps, you can iterate ``self.info.requires.pkg_names``

**Comment by sct2010** [comment]
Hi @memsharded

Thanks for your feedback. We are not using `conan copy` in our workflow. the generated `dev` packages are only to build an installer of a feature branch for our testing team. As soon as the code gets merged, these packages gets thrown away.

The approach works for us. Thanks.
