### ISSUE TITLE
[develop2][feature] review output system, define levels (debug, trace)

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11393]
``ConanOutput`` always output everything, in different colors.

- Do we want to define outputs with different Debug/Trace levels?
- Control them with some kind of ``--verbose`` (https://github.com/conan-io/conan/issues/5765) or ``--logging=debug``?
- Should that propagate to build system integrations? (like ``CMake.build()`` be more verbose?
- What to do with the current ``tracer.py``, that is still there in develop2?

**Comment by SSE4** [comment]
it would be also nice to have:
- `--silent` (no messages)
- `--dry-run` (just display what's going on to be executed, but don't actually execute anything)
- `--trace` (full trace of functions called, to help debugging)

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11522
