### ISSUE TITLE
[question] Generator Question

### ISSUE THREAD

**Issue by Connor-A** [conan-io/conan#11392]
Hey Guys,

I've read through the documentation on generators + creating my own packages, but there are details that are still a bit fuzzy. I'm not terribly familiar with make + cmake, or similar tools.

What *exactly* is conan's relationship with the generator? In the tutorial we has a cmake.lists file. What would have happened if I listed make as my generator when I attempted to build the package? Do specific packages only support specific generators?

When I create my own conan packages, will they always need some cmake.lists analog for conan to utilize? If there is any reading that might help clear this up I'd appreciate it. I think the tutorial is assuming the reader is fairly familiar with cmake.

**Comment by memsharded** [comment]
Hi @Connor-A 

Conan supports multiple build systems, like CMake, Makefiles, MSBuild (Visual Studio projects), etc.
Each build system has a different way to get the information for dependencies:

- CMake will use ``find_package()`` in their CMakeLists.txt
- Makefiles will get environment variables like LIBDIRS, LIBS, etc
- MSBuild needs to be passed .props files with the information to locate the dependencies, include-dirs, lib-dirs, etc

Conan generators create those specific files, for the build system you plan to use:
- CMakeDeps generator will generate xxxx-config.cmake files so they can be found by ``find_package()``
- MSBuildDeps will create .props files that you can add to your VS projects
- etc

Conan does not decide your build system. You have your build system and you let Conan know it, so Conan can generate the right files for your build system.

**Comment by memsharded** [comment]
Hi @Connor-A 

Did the above clarified a bit your question? Please let me know if you any further question, or feel free to close the issue. Thanks!

**Comment by Connor-A** [comment]
@memsharded Sorry for the late response! I think I understand what you're saying.

To reiterate, some build processes depend on additional files that would likely have been provided by your dependencies if conan was not sitting in between the source you are building and the dependency.

Conan is able to dynamically generate these additional files. It must generate the files based on which build system you are using to build your source code.

The real advantage of this seems to be the ability to mix + match build systems across multiple dependencies.

Am I interpreting everything correctly?

**Comment by memsharded** [comment]
> To reiterate, some build processes depend on additional files that would likely have been provided by your dependencies if conan was not sitting in between the source you are building and the dependency.

That is super unlikely to happen in many build systems. For example, I don't know any project that provide files to be used by Visual Studio natively.

> The real advantage of this seems to be the ability to mix + match build systems across multiple dependencies.

Yes, exactly. ConanCenter contains packages built with a large variaty of build systems: autotools, meson, cmake, scons, visual, cmake, etc. Conan can abstract away the build system for the consumers. We think this is a very good decoupling, letting every package have their own build system, and that would allow for example to do an easy migration from one build system to another, because it can be done one package at a time.

**Comment by Connor-A** [comment]
Thanks for explaining this all to me! I think I've got a good grasp of it now.

**Comment by memsharded** [comment]
Great! Happy to help, don't hesitate to submit more tickets if you have further questions.
