### ISSUE TITLE
[question] How to avoid test_package polluting its source folder when using cmake_layout?

### ISSUE THREAD

**Issue by cyreon** [conan-io/conan#11399]
Hello,

First of all, let me apologize if I duplicate this question but I am pretty new to this conan feature and I am very happy to the improvements you're doing in the last few weeks.

My question is how can I generate everything under build/ folder even in test_package?

Here is my conanfile.py for reference.

```
from conan import ConanFile
from conan.tools.build import cross_building
from conan.tools.cmake import CMake, cmake_layout
from os.path import join

class TemplateppIntegrationRecipe(ConanFile):
  settings = "os", "compiler", "build_type", "arch"
  generators = "CMakeToolchain", "CMakeDeps"

  def layout(self):
    cmake_layout(self)

  def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()

  def test(self):
    if not cross_building(self):
      exec = join(self.cpp.build.bindirs[0], "integration")
      self.run(exec, run_environment=True)

```

When I execute this `conan test . templatepp/0.4.0@user/channel -pr:b default --build missing` extra files are generated such as conanbuildinfo.txt, conaninfo.txt, graph_info.json etc... It would be better if all these generated files were placed under build/ or whatever folder you provide.

I see you have open pull request regarding cmake_layout such as this https://github.com/conan-io/conan/pull/11391/files.
Is this PR intends to solve this issue?

In the meantime, I will use the "legacy" workflow to run test_package.

Thank you very much for your kind help.

Regards,

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by cyreon** [comment]
OK, I think I understand.

cmake_layout is still experimental feature. Good luck and keep up the good work! I am looking forward to use cmake_layout soon.

**Comment by memsharded** [comment]
Hi @raygerlabs 

yes, all these files ``conanbuildinfo.txt, conaninfo.txt, graph_info.json`` are legacy, and have already been removed in Conan 2.0. ``cmake_layout()`` does the right thing for the "modern" generated files, but not for those legacy ones, so I guess we will be good in 2.0.
