### ISSUE TITLE
[bug] conan build --missing does not respect inner dependency options

### ISSUE THREAD

**Issue by theartful** [conan-io/conan#11396]
I have this conanfile.txt
```
[requires]
gtk/3.24.24
freetype/2.12.1

[options]
gtk:shared=True
cairo:shared=True
pango:shared=True
glib:shared=True
gdk-pixbuf:shared=True
atk:shared=True

[generators]
pkg_config
```
running `conan install .. --build=missing` I was surprised to find it fetch dependencies from conencenter. I checked the configuration for `pango` for example, and I find out that `glib:shared=False`, even though I set it to be shared.

Now we have a situation where gtk links against a shared glib, while pango/cairo link against static glib.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc 9.4
  * Conan version: 1.49
  * Python version: 3.8.10

### Logs (Executed commands with output) (Include/Attach if Applicable)
[conan_install.log](https://github.com/conan-io/conan/files/8837412/conan_install.log)

**Comment by theartful** [comment]
I read about package id modes, which seem to do what I want.
But I think there should be something specific for shared vs static, so that if a library changes its type, all libraries that depend on it are rebuilt.
For example in the class `RequirementInfo`, why not add `shared` as part of the information to compute the ID alongside the version? The only other alternative is to use full_package_mode which is a bit extreme.

**Comment by SSE4** [comment]
seems to be somehow related to #9712. it seems like dependency option is erased from the package ID by default, which is wrong.

**Comment by theartful** [comment]
Yeah it's exactly the case as #9712. Closing as duplicate then.
