### ISSUE TITLE
[question] Is the artifactory "start me up" prompt wrong?

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#11404]
I'm trying to add an artifactory as a Conan remote by following the steps in the "set me up" prompt and after running `conan remote add myremote https://artifacts.example.com:8081/artifactory/api/conan/myremote` I then add myself using `conan user -p <password> -r myremote will` and it takes a long time before eventually just giving the error:
```
ERROR: HTTPSConnectionPool(host='artifacts.example.com', port=8081): Max retries exceeded with url: /artifactory/api/conan/myremote/v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0be3803cd0>, 'Connection to artifacts.example.com timed out. (connect timeout=60.0)'))

Unable to connect to myremote=https://artifacts.example.com:8081/artifactory/api/conan/myremote
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

This seems a network or configuration issue.
As a first step to rule out possible client issues, I would try to download the ArtifactoryCE locally in your computer, and try teh same process. I have done it tones of times, the default ArtifactoryCE configuration works out of the box for me.

If that works, it could be a "artifacts.example.com" server configuration issue, to check the permissions, the possible frontend (nginx) configuration, the https, etc.

**Comment by wbehrens-on-gh** [comment]
It appears after a bit of messing around the remote works with http but not https. Though accessing the artifactory ui on port 8082 through https works just fine

**Comment by memsharded** [comment]
> It appears after a bit of messing around the remote works with http but not https. Though accessing the artifactory ui on port 8082 through https works just fine

Artifactory configuration doesn't serve https by default for the packages APIs (it might do for the web UI). But I am not an Artifactory expert. Is this an ArtifactoryCE instance? If it is a paid one, maybe you can get some assistance from JFrog support?
