### ISSUE TITLE
[bug] `cmake.test()` cannot execute

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#11405]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.04 on WSL
  * Compiler+version: CMake 3.23.1
  * Conan version: 1.49.0
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)

Put `cmake.test()` and run `conan build .` with `Ninja Multi-Config` as a generator.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
conanfile.py (mp-units/0.8.0): CMake command: cmake --build "/home/mpusz/repos/units/build-gcc-11" --config Release '--' '-j12'
[308/308] Linking CXX executable test/unit_test/runtime/Release/unit_tests_runtime
conanfile.py (mp-units/0.8.0): CMake command: cmake --build "/home/mpusz/repos/units/build-gcc-11" --config Release '--target' 'RUN_TESTS' '--' '-j12'
ninja: error: unknown target 'RUN_TESTS'
ERROR: conanfile.py (mp-units/0.8.0): Error in build() method, line 172
        cmake.test()
        ConanException: Error 1 while executing cmake --build "/home/mpusz/repos/units/build-gcc-11" --config Release '--target' 'RUN_TESTS' '--' '-j12'
```

CMake target `RUN_TESTS` is not available. `test` target works correctly but Conan does not use it for some reason.

**Comment by memsharded** [comment]
Yes, sounds that the test target is not taking into account ``Ninja Multi-Config`` generator. Seems the fix could be easy.
