### ISSUE TITLE
[question] Using dependencies with AutotoolsToolchain generator

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#11406]
I've made a recipe that used the AutotoolsToolchain helper/generator but I also has dependencies on some other packages. I was wondering which dependency generator should be used along side it (AutotoolsDeps, PkgConfigDeps) since pkg_config is apparently being deprecated 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @WilliamBehrens 

You can use either AutotoolsDeps or PkgConfigDeps. It'll depend on your preference of using `pkg-config` or not. Here, you can find out [some basic functional tests](https://github.com/conan-io/conan/blob/develop/conans/test/functional/toolchains/gnu/autotools/test_basic.py) using them if it helps.
