### ISSUE TITLE
[feature] Add relative path support to Git SCM tool

### ISSUE THREAD

**Issue by nmasseyKM** [conan-io/conan#11408]
When trying to setup Conan packaging with the target source in a git submodule relative to the recipe, I was receiving
empty commit ids. Upon further investigation, it seems that the current assumption is that the folder path to `Git()`
will be absolute. A minor adjustment allows relative paths to be used as well: since the git command always `chdir`s to the
target git folder, we can perform the rev-parse relative to the current directory and receive the expected behavior.

Note that the current default value of "." is a relative path, which suggests that other relative paths should work.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11407. 

Thanks for contributing it! Will be released in next 1.50 (and be part of Conan 2.0 beta, as we merge develop->develop2 continously)
