### ISSUE TITLE
[feature] Support PyYAML 6.0 (for Python >= 3.6)

### ISSUE THREAD

**Issue by beutlich** [conan-io/conan#11418]
Is there a possibility to update the PyYAML dependency to support version 6.0 (for Python >= 3.6)? Thank you!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @beutlich 

But this was recently added in 1.49, have you upgraded to it? Can you please try it? Thanks!

**Comment by beutlich** [comment]
Confirmed. Duplicate of #10759 and resolved by v1.49.0. Thank you!
