### ISSUE TITLE
[bug] missing shared and fPIC in test_package/conanfile.py

### ISSUE THREAD

**Issue by stefaneicher** [conan-io/conan#11422]
If I create a now conan package with
conan new -c -t -s sotest/snapshot@eicher/development
the generated test_package has no options shared and fPIC and therefore this fails

 conan create -pr:b=clang-linux-release -pr:h=clang-linux-debug \
 -o shared=True  \
 -o fPIC=True  \
 . snapshot@eicher/development

I used conan 1.49

**Solution:** 
Also add  in the test_package/conanfile.py
options = {"shared": [True, False], "fPIC": [True, False]}
default_options = {"shared": False, "fPIC": True}

**Bash**
#!/bin/bash
cd "$(dirname "$0")" || exit

set -e
clear

conan --version
rm -rf ./sotest
mkdir sotest
cd sotest
conan new -c -t -s sotest/snapshot@eicher/development

 conan create -pr:b=clang-linux-release -pr:h=clang-linux-debug \
 -o shared=True  \
 -o fPIC=True  \
 . snapshot@eicher/development

**Log**
...
ERROR: /workspace/sotest/test_package/conanfile.py: option 'fPIC' doesn't exist
Possible options are []

**Comment by memsharded** [comment]
Hi @stefaneicher 

But the purpose of the ``test_package`` is to test that the package has been correctly created. For that reason, the ``test_package`` always generate an executable that links with whatever library is built, but the executable itself is not ``shared``, or shouldn't define ``fPIC``.

A different story is the failing application of cli options. If you want to specify the options of the package, the general, recommended approach is to specify the package name, like: ``-o pkg:option=value``. Not specifying the name is a shortcut that can be convenient in some cases like ``conan install``, but it has issues like this one. You might also try to use the ``-o &:option=value``, where the ``&`` specifies the "package" being processed.

**Comment by stefaneicher** [comment]
hi @memsharded 

ok thanks for the info!

I guess to correct way then would be to do run:

mkdir sotest
cd sotest
conan new -c -t -s sotest/snapshot@eicher/development
conan create -o sotest:shared=True  -o sotest:fPIC=True . snapshot@eicher/development

This works without any modifications.

**Comment by memsharded** [comment]
Yes, exactly, making things that explicit is always better, as clearly not specifying the package name before the options makes things ambiguous, as you have experienced.
