### ISSUE TITLE
[question] IncludeDirectories variable not defined for gtest with MSBuildDeps generator

### ISSUE THREAD

**Issue by isaacda** [conan-io/conan#11425]
I have been using the `gtest/1.11` conan package with visual studio successfully, using the visual_studio generator. I am trying switch over to the new MSBuildDeps generator. After running the conan install command, the gtest include files are not found. The reason they are not found is that the include directory for gtest is not defined in any of the generated ` conan_gtest_build*.props` files.

Here is my conanfile.txt
```
[requires]
gtest/1.11.0

[generators]
MSBuildDeps
MSBuildToolchain
```

Here is my conan install command:
```
conan install . -pr vs2019 -pr:b vs2019 -s build_type=Release -if .\PropertySheets\conaninfo_Release
```

I am using conan 1.45.0. 

It seems that I must be missing some new setting required by MSBuildDeps, but I haven't been able find anything on the internet. Thanks for your help.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by isaacda** [comment]
This was my error. I had originally had the `gtest/1.11.0` package listed under [build-requires] section in the conanfile.txt. After moving it to the [requires] section, the proper project variables are defined. This #8170 gave me a hint, so I moved `gtest` package to [required]. I must have not re-ran conan install, because now it's working. Thanks

**Comment by memsharded** [comment]
Hi @isaacda 

yes, it makes sense. We might create a ``[test_requires]`` section in ``conanfile.txt``, which is pure syntactic sugar (no different behavior), but it will make a little clearer the intent.
