### ISSUE TITLE
What does it mean " Removing the local binary packages from different recipe revisions" ?

### ISSUE THREAD

**Issue by RReymann** [conan-io/conan#11428]
While executing following conan commands :

- conan create --keep-source --test-folder Tests/PackageTest --env:build WITH_TESTS=ON --env:build ENABLE_SCA=OFF --profile:build pr_v140_x86_64_debug --profile:host pr_v140_x86_64_debug . jkstester/1.42.0@artetest/dev
- conan create --keep-source --test-folder Tests/PackageTest --env:build WITH_TESTS=ON --env:build ENABLE_SCA=OFF --profile:build pr_v140_x86_64_release --profile:host pr_v140_x86_64_release . jkstester/1.42.0@artetest/dev

I did not understand while my local conan cache does only keep the latest build package corresponding to the second conan create command. The first local package generated by the first create command will be removed !!

`E:\Git\cpp-jkstester>conan create --keep-source --test-folder Tests/PackageTest --env:build WITH_TESTS=ON --env:build ENABLE_SCA=OFF --profile:build pr_v140_x86_64_release --profile:host pr_v140_x86_64_release . jkstester/1.42.0@artetest/dev
Exporting package recipe
jkstester/1.42.0@artetest/dev exports_sources: Copied 5 files
jkstester/1.42.0@artetest/dev exports_sources: Copied 15 '.txt' files
jkstester/1.42.0@artetest/dev exports_sources: Copied 3 '.lock' files: conan.lock, conan.lock, conan.lock
jkstester/1.42.0@artetest/dev exports_sources: Copied 2 '.py' files: conanfile.py, conanfile.py
jkstester/1.42.0@artetest/dev exports_sources: Copied 3 '.json' files: graph_info.json, graph_info.json, graph_info.json
jkstester/1.42.0@artetest/dev exports_sources: Copied 1 '.md' file: README.md
jkstester/1.42.0@artetest/dev exports_sources: Copied 1 '.ini' file: test.ini
jkstester/1.42.0@artetest/dev exports_sources: Copied 6 '.cpp' files
jkstester/1.42.0@artetest/dev exports_sources: Copied 3 '.h' files: Fibonacci.h, TestRunner.h, FibonacciTest.h
jkstester/1.42.0@artetest/dev exports_sources: Copied 2 '.exe' files: jksTesterd.exe, jksTester.exe
jkstester/1.42.0@artetest/dev: A new conanfile.py version was exported
jkstester/1.42.0@artetest/dev: Folder: E:\Conan\.conan\data\jkstester\1.42.0\artetest\dev\export
jkstester/1.42.0@artetest/dev: Using the exported files summary hash as the recipe revision: 2d718c315677180b65f7b3b52fcce3ef
jkstester/1.42.0@artetest/dev: Removing the local binary packages from different recipe revisions
jkstester/1.42.0@artetest/dev: Exported revision: 2d718c315677180b65f7b3b52fcce3ef
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.toolset=v140
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.toolset=v140
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
ENABLE_SCA=OFF
WITH_TESTS=ON
jkstester/1.42.0@artetest/dev: Validating environment ...
jkstester/1.42.0@artetest/dev: Selecting following generator: ('CMakeToolchain', 'CMakeDeps')
jkstester/1.42.0@artetest/dev: Forced build from source`

Any idea why the first package is removed despite using different profiles ?

Cheers
Renaud
- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @RReymann 

There is a limitation in the Conan 1.X cache, is that it can only contain 1 revision at a time. For some reason, the recipe that is produced with those commands is different (you can read it in the output ``jkstester/1.42.0@artetest/dev: Exported revision: 2d718c315677180b65f7b3b52fcce3ef``, and compare between the 2 runs). As the cache can only contain 1 revision, it will remove the previous one.

Now the key is to know what could be causing such difference in revisions, as it is not expected. Maybe if you can share the resulting ``conanmanifest.txt`` that ends in the ``export`` folder in your cache after the 2 commands, we could try to think where the difference could come from. Is there something else in your ``conanfile.py`` or your exported files that would be different between the 2 commands?

**Comment by RReymann** [comment]
Hi,

Please find copied below the content of both files. (Unable to attach it due to security limitation :-( )

**Debug:**
`1654857356
conanfile.py: 626e98cb59f669c9566b991363d488ac
export_source/.gitappconfig: f22e8ca70ffb5cc131b32c5bdf4dfb20
export_source/.gitignore: 8eeffc28d46558b825997c6d7b01e70a
export_source/CMakeLists.txt: d11a2fe68c0b481cb53a2979755f5a5d
export_source/Jenkinsfile: 0489f75de06f9545a41316f21ad72dbe
export_source/Path: 16af5aded3165749feabcdde35453225
export_source/README.md: c7406f64961db3ff1206d250f7fea024
export_source/Src/CMakeLists.txt: b60221821aa5c81636e700ebddbbf082
export_source/Src/JksTester/CMakeLists.txt: cdd98890c12c2e379901f5bc68f3dc5c
export_source/Src/JksTester/main.cpp: 9f34093837c3cc0e02b68818ac12621b
export_source/Src/LibJksTester/CMakeLists.txt: dc85af3018fac181cbd1fcba610c2779
export_source/Src/LibJksTester/Fibonacci.cpp: 360a66b15bfab7f8537f14f942cb22be
export_source/Src/LibJksTester/Fibonacci.h: bc807d4bb9156c8a35602eaa296f6171
export_source/Tests/CMakeLists.txt: 3de97dc0b3cace2d3ebad7d6d5d08188
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/bin/jksTesterd.exe: a32b54b323614671a0a1ead80ee81491
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conan.lock: 16a19063ce54598a40e2e226aae20c06
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conan_imports_manifest.txt: c77488c95c3ccc545ef5595b5423d585
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conanbuildinfo.txt: 8c28649d7a64d5a2b9a8b1b56bdef233
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conaninfo.txt: e8f616f0c090eda82d23c6215d534d59
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/graph_info.json: 397cf4809eec912e5411162a5c68dc59
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/bin/jksTester.exe: c617194018e0a10150a844ccfc270c8c
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/conan.lock: ccc394f0ae0d5db09d0f55a509b76136
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/conan_imports_manifest.txt: fb98e40c57f4691bced9ed762f95b6a8
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/conanbuildinfo.txt: b72337ce4467b8e770de6c15ab2ff625
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/conaninfo.txt: 563e14f12942fddb0614aca1b6533783
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/graph_info.json: 10a2b1e2b9bb31c4c81aaa8969db984d
export_source/Tests/PackageTest/conanfile.py: 70ba86a798f82afb8c5ea0240d402e42
export_source/Tests/SystemTest/CMakeLists.txt: a63e9754a43c31bfab12b0fcbaba05df
export_source/Tests/SystemTest/TestRunner.cpp: ae7f9a6b53b1bf3d55a2fe0668e47aa6
export_source/Tests/SystemTest/TestRunner.h: 956d367dff6da87db517307809f66b6c
export_source/Tests/SystemTest/main.cpp: 3bd7e328ae25e9f30f90e149ead4a31c
export_source/Tests/UnitTest/CMakeLists.txt: 834cade980bd2fa453fd947033a5a63f
export_source/Tests/UnitTest/FibonacciTest.cpp: e50e802b5290dce03fb20c0bccc0b0a6
export_source/Tests/UnitTest/FibonacciTest.h: f5c22793e3e6984a1918b36178b32dfd
export_source/Tests/UnitTest/main.cpp: 3bd7e328ae25e9f30f90e149ead4a31c
export_source/conan.lock: 35a9763a332b0da460bd1e471ee58e5d
export_source/conanbuildinfo.txt: 13beecf71def69df914ba21529d1dcd8
export_source/conanfile.py: 626e98cb59f669c9566b991363d488ac
export_source/conaninfo.txt: fc338b9a107e15ea310624fe787a3c85
export_source/graph_info.json: 1336ec1dd6bbabeb1772ac22ef74db36
export_source/profiles/pr_v140_x86_64_custom: 8ec713dd0b3eaabdc403ea5f9b5e7da4
export_source/test.ini: a3d96f93675067900c17cc88f9e81c71`

**Release:**

`1654857408
conanfile.py: 626e98cb59f669c9566b991363d488ac
export_source/.gitappconfig: f22e8ca70ffb5cc131b32c5bdf4dfb20
export_source/.gitignore: 8eeffc28d46558b825997c6d7b01e70a
export_source/CMakeLists.txt: d11a2fe68c0b481cb53a2979755f5a5d
export_source/Jenkinsfile: 0489f75de06f9545a41316f21ad72dbe
export_source/Path: 16af5aded3165749feabcdde35453225
export_source/README.md: c7406f64961db3ff1206d250f7fea024
export_source/Src/CMakeLists.txt: b60221821aa5c81636e700ebddbbf082
export_source/Src/JksTester/CMakeLists.txt: cdd98890c12c2e379901f5bc68f3dc5c
export_source/Src/JksTester/main.cpp: 9f34093837c3cc0e02b68818ac12621b
export_source/Src/LibJksTester/CMakeLists.txt: dc85af3018fac181cbd1fcba610c2779
export_source/Src/LibJksTester/Fibonacci.cpp: 360a66b15bfab7f8537f14f942cb22be
export_source/Src/LibJksTester/Fibonacci.h: bc807d4bb9156c8a35602eaa296f6171
export_source/Tests/CMakeLists.txt: 3de97dc0b3cace2d3ebad7d6d5d08188
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/bin/jksTesterd.exe: 4444511c81a0f7b9a05c793f65d17796
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conan.lock: acda1cf8da6a30a73f29e4d581566942
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conan_imports_manifest.txt: 6da2cb61a0168d98475e44e71c90ff6b
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conanbuildinfo.txt: 8c28649d7a64d5a2b9a8b1b56bdef233
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conaninfo.txt: e8f616f0c090eda82d23c6215d534d59
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/graph_info.json: 397cf4809eec912e5411162a5c68dc59
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/bin/jksTester.exe: c617194018e0a10150a844ccfc270c8c
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/conan.lock: ccc394f0ae0d5db09d0f55a509b76136
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/conan_imports_manifest.txt: fb98e40c57f4691bced9ed762f95b6a8
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/conanbuildinfo.txt: b72337ce4467b8e770de6c15ab2ff625
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/conaninfo.txt: 563e14f12942fddb0614aca1b6533783
export_source/Tests/PackageTest/build/903ffca0b8dd86bddcf33b40e4c9b7ae9d0bcb94/graph_info.json: 10a2b1e2b9bb31c4c81aaa8969db984d
export_source/Tests/PackageTest/conanfile.py: 70ba86a798f82afb8c5ea0240d402e42
export_source/Tests/SystemTest/CMakeLists.txt: a63e9754a43c31bfab12b0fcbaba05df
export_source/Tests/SystemTest/TestRunner.cpp: ae7f9a6b53b1bf3d55a2fe0668e47aa6
export_source/Tests/SystemTest/TestRunner.h: 956d367dff6da87db517307809f66b6c
export_source/Tests/SystemTest/main.cpp: 3bd7e328ae25e9f30f90e149ead4a31c
export_source/Tests/UnitTest/CMakeLists.txt: 834cade980bd2fa453fd947033a5a63f
export_source/Tests/UnitTest/FibonacciTest.cpp: e50e802b5290dce03fb20c0bccc0b0a6
export_source/Tests/UnitTest/FibonacciTest.h: f5c22793e3e6984a1918b36178b32dfd
export_source/Tests/UnitTest/main.cpp: 3bd7e328ae25e9f30f90e149ead4a31c
export_source/conan.lock: 35a9763a332b0da460bd1e471ee58e5d
export_source/conanbuildinfo.txt: 13beecf71def69df914ba21529d1dcd8
export_source/conanfile.py: 626e98cb59f669c9566b991363d488ac
export_source/conaninfo.txt: fc338b9a107e15ea310624fe787a3c85
export_source/graph_info.json: 1336ec1dd6bbabeb1772ac22ef74db36
export_source/profiles/pr_v140_x86_64_custom: 8ec713dd0b3eaabdc403ea5f9b5e7da4
export_source/test.ini: a3d96f93675067900c17cc88f9e81c71`

The diff between both files shows following lines 
`export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/bin/jksTesterd.exe: 4444511c81a0f7b9a05c793f65d17796
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conan.lock: acda1cf8da6a30a73f29e4d581566942
export_source/Tests/PackageTest/build/050285e47350406bd9af85ab758a57796bde3ff4/conan_imports_manifest.txt: 6da2cb61a0168d98475e44e71c90ff6b`

Cheers,
Renaud

**Comment by memsharded** [comment]
Ok, thanks very much.

I think I see what is happening. You have some ``imports`` (or ``deploy()`` there. The first command is importing things, modifying your current folder. The second command is exporting these files again, resulting in a different exported source.

You should make your ``exports_sources`` more restrictive to make sure you include only the necessary files. If necessary, there is even a ``export_source()`` method that might be a bit more explicit. Please try that and let me know.

**Comment by RReymann** [comment]
Hi,

Thx for your help. Adapting the export_sources method to be more restrictive has fixed our issue.

I really appreciate your help. Thx again.

Cheers,
Renaud

**Comment by memsharded** [comment]
> I really appreciate your help. Thx again.

Happy to help and know that the issue is solved 😄
