### ISSUE TITLE
[question] Uploading only built packages with conan upload

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#11431]
I ran `conan upload "*" -r remote --all -c` to upload all the packages in my local cache to a remote that I have. The issue is that this uploads all versions of the package even the ones that aren't built for anything. I was wondering if there was a way to only upload the versions of packages that are built?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jcar87** [comment]
Hi @WilliamBehrens - 

The `upload` command as you are invoking it will indeed find all recipe references (the wildcard `"*"` will match all recipes), and it will  upload both recipes _and_ existing packages as well (with `--all`). 

I'm not entirely sure what you mean by the versions of packages that are built. If you are running an earlier command, for example `conan create` or `conan install` that are causing packages to be built, you can use the `--json` flag to output the results to a json file from which you can extract the package ID(s) of what was just build. 

For example:
```
conan install zlib/1.2.12@install zlib/1.2.12@ --remote conancenter --build=zlib --json output.json -ozlib:shared=True
```
this will generate a json output like this after creating the package:

```
{
  "error": false,
  "installed": [
    {
      "recipe": {
        "id": "zlib/1.2.12",
        "downloaded": false,
        "exported": false,
        "error": null,
        "remote": null,
        "time": "2022-06-13T15:59:11.681294",
        "dependency": true,
        "name": "zlib",
        "version": "1.2.12",
        "user": null,
        "channel": null
      },
      "packages": [
        {
          "id": "d0c219631d7c692d7a95436cf4e11fe2891dc312",
          "...":"..."
        }
```

You could then parse this file programmatically to retrieve the specific references you want to upload.
