### ISSUE TITLE
[bug] 'Missing prebuilt package' situation ERROR message contains misleading/incomplete remedy suggestion

### ISSUE THREAD

**Issue by mandree** [conan-io/conan#11438]
### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora Linux 36 on amd64 aka x86_64
  * Compiler+version: 12.1.1
  * Conan version: 1.49.0
  * Python version: 3.10.4

### Steps to reproduce

- Follow example from https://docs.conan.io/en/latest/getting_started.html all the way from the start on a fresh install (in doubt, rename your ~/.conan first)
- Step no. 5 - the `conan install ..` fails as per the logs below at the very end (but that's just to give context where exactly this happens - it is expected that not each and every requisite will be in conancenter)

#### `Requested improvements`

Specifically, `Use 'conan search bzip2/1.0.8 --table=table.html -r=remote' and open the table.html file to see available packages` is misleading because:

1. **it lacks the trailing @ to turn bzip2/1.0.8 into a reference** and should add it if there is no `@user/channel` suffix
2. it should specify I need to replace the `-r=remote` by one my remote repositories' names and how to list them, 

```
[_build]$ conan search bzip2/1.0.8 --table=table.html -r=remote
ERROR: '--table' argument can only be used with a reference
[_build]$ conan search bzip2/1.0.8@ --table=table.html -r=remote
ERROR: No remote 'remote' defined in remotes
[_build]$ conan search bzip2/1.0.8@ --table=table.html -r=conancenter
```
The latter takes ages but actually succeeds. Of course I can `--build=missing` but this report is about the two issues in the error messages that should be improved.

### Logs (Executed commands with output) (Include/Attach if Applicable)

**NOTE: none of this below is wrong, except for the misleading Use conan search... suggestion!**

**This just serves to render context!**

```
[md5]$ mkdir _build
[md5]$ cd _build
[_build]$ conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

pcre/8.45: Not found in local cache, looking in remotes...
```
(...finds a lot of packages...)
```
Installing (downloading, building) binaries...
ERROR: Missing binary: bzip2/1.0.8:3cfc45772763dad1237052f26c1fe8b2bae3f7d2
ERROR: Missing binary: expat/2.4.8:a1ba772dbe13186199f7ecf8dde362ba9613ecf7
ERROR: Missing binary: openssl/1.1.1n:2a19826344ff00be1c04403f2f8e7008ed3a7cc6
ERROR: Missing binary: pcre/8.45:a5d8037b071e974a1b1afa8f847335f76f3ce3ec
ERROR: Missing binary: poco/1.9.4:a64cba69d8cf30ed29e6c57b803718d4623c1c00
ERROR: Missing binary: sqlite3/3.38.1:668a23a956a1ae835b578205ecc8274cfd29ae40
ERROR: Missing binary: zlib/1.2.12:2a19826344ff00be1c04403f2f8e7008ed3a7cc6

bzip2/1.0.8: WARN: Can't find a 'bzip2/1.0.8' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=12, os=Linux
- Options: build_executable=True, fPIC=True, shared=False
- Dependencies: 
- Requirements: 
- Package ID: 3cfc45772763dad1237052f26c1fe8b2bae3f7d2

ERROR: Missing prebuilt package for 'bzip2/1.0.8', 'expat/2.4.8', 'openssl/1.1.1n', 'pcre/8.45', 'poco/1.9.4', 'sqlite3/3.38.1', 'zlib/1.2.12'
Use 'conan search bzip2/1.0.8 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=missing'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

**Comment by memsharded** [comment]
Hi @mandree 

These have already been improved in Conan 2.0, the error message will be: ``conan list packages %s --format=html -r=remote > table.html``, which already fixes the above 2 things:
- The @ is actually no longer necessary
- The remote is explicit

I am marking these as done in 2.0, thanks for the suggestions!

**Comment by mandree** [comment]
This will want fixing in 1.x, too, unless 2.0 will be the release after 1.49.0.

**Comment by memsharded** [comment]
Conan 2.0-beta is the next release, yes.
