### ISSUE TITLE
[bug] 1.49.0: KeyError: 'include' in CMakeToolchain generator

### ISSUE THREAD

**Issue by AndWass** [conan-io/conan#11436]
### Environment Details (include every applicable attribute)
  * Operating System+version: docker container running ubuntu:latest
  * Compiler+version: g++ 11
  * Conan version: 1.49.0
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)
Create a folder containing the following files:
  * Empty `CMakeLists.txt`
  * Empty `CMakePresets.json`
  * `CMakeUserPresets.json` containing only `{}` (an empty file will give a different error)

Create a `conanfile.py` with the following content:

```python
from conan import ConanFile


class Recipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain"

    def layout(self):
        self.folders.generators = "conan"
```

run `conan install .`

### Logs (Executed commands with output) (Include/Attach if Applicable)

Output using 1.49.0:

```
root@167b965bb085:~# conan install -pr:b=default -pr:h=default .
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py: Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Generator 'CMakeToolchain' calling 'generate()'
conanfile.py: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/conans/client/generators/__init__.py", line 177, in write_generators
    generator.generate()
  File "/usr/local/lib/python3.10/dist-packages/conan/tools/cmake/toolchain/toolchain.py", line 178, in generate
    write_cmake_presets(self._conanfile, toolchain, self.generator)
  File "/usr/local/lib/python3.10/dist-packages/conan/tools/cmake/presets.py", line 124, in write_cmake_presets
    if preset_path not in data["include"]:
KeyError: 'include'

ERROR: Error in generator 'CMakeToolchain': 'include'
```

Output using 1.48.2:

```
root@167b965bb085:~# conan install -pr:b=default -pr:h=default .
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py: Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py: Generator 'CMakeToolchain' calling 'generate()'
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Aggregating env generators
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
```

**Comment by AndWass** [comment]
Removing `def layout(): ...` from `conanfile.py` also makes it work.

**Comment by lasote** [comment]
I think we should probably "mark" the `CMakeUserPresets.json`  with a comment like we do in migrations in develop2 branch. If we don't have the file marked, skip to append contents, because the structure might be unknown and we could be destroying users changes.

**Comment by memsharded** [comment]
> I think we should probably "mark" the CMakeUserPresets.json with a comment like we do in migrations in develop2 branch. If we don't have the file marked, skip to append contents, because the structure might be unknown and we could be destroying users changes.

Yes, agree, but json files are not easy to mark with comments, unless CMake will not fail because of adding some extra fields in the json.

**Comment by sykhro** [comment]
> unless CMake will not fail because of adding some extra fields in the json.

CMakePresets have a "vendor" section so that third party tools can add their information there.

**Comment by jcar87** [comment]
Resolved in https://github.com/conan-io/conan/pull/11452
