### ISSUE TITLE
[bug] conan asks for password when CONAN_NON_INTERACTIVE=True

### ISSUE THREAD

**Issue by sobczyk** [conan-io/conan#11433]
This issue surfaced when our artifactory instance slowed down.
Most probably the token stored in conan.db expired, and caused this.

password and username are also present in environment.

### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu focal
  * Compiler+version: n/a
  * Conan version: 1.48
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)

* pull dependencies from remote (authenticate)
* wait for auth token to expire
* try upload with CONAN_NON_INTERACTIVE

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
/usr/local/bin/conan upload MyPackage/1.0 --no-overwrite recipe --all --remote remote --confirm --retry 4 --retry-wait 10
Uploading to remote 'remote':
Uploading MyPackage/1.0 to remote 'remote'                                  
Please log in to "remote" to perform this action. Execute "conan user" command.
Please enter a password for "uploader_accnt" account: 
```

**Comment by memsharded** [comment]
I am doing a code review, trying to understand how this is happening, and I cannot find a reason.

Is it possible that you have defined ``general.non_interactive=False`` in your ``conan.conf``?

**Comment by sobczyk** [comment]
My initial conan.conf is:
```
[general]
required_conan_version = >=1.39
```

**Comment by sobczyk** [comment]
it gets to [conans/client/rest/auth_manager.py#L49](https://github.com/conan-io/conan/blob/173cbc6143133c83ed1ecb9b5315d3ca787a846a/conans/client/rest/auth_manager.py#L49)
without checking for non-interactivity.
the "method_name" that gets called must throw AuthenticationException

**Comment by memsharded** [comment]
yes, but that is an "out", that is not a problem, it should not error. But the actual "input", in ``input_user, input_password = self._user_io.request_login(remote.name, user)`` is the thing that is protected by the non-interactive and should raise. The surprising thing is that it is not raising an error.

**Comment by sobczyk** [comment]
OK, the issue is a false positive, process that ran conan, cleaned up all environment variables, including the non-interaction one
