### ISSUE TITLE
[bug] conan.tools.cmake.CMake helper does not consider should_ configure/build/test/install

### ISSUE THREAD

**Issue by dornbirndevelops** [conan-io/conan#11430]
### Environment Details
  * Operating System+version: Windows 10 Build 19044
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.49.0
  * Python version: 3.10.0

### Steps to reproduce

in conanfile.py
```python
# implementation (did work as intended with cmake helper from conans)
def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
    cmake.test()
    cmake.install()
```

run command (intention is to configure only)
```sh
conan build path/to/recipe -bf=build -c
```

result: configure, build, test and install phase are executed.

current workaround:
```python
def build(self):
    cmake = CMake(self)
    if self.should_configure:
        cmake.configure()
    if self.should_build:
        cmake.build()
    if self.should_test:
        cmake.test()
    if self.should_install:
        cmake.install()
```

**Comment by memsharded** [comment]
This is expected:

- ``should_xxxx`` are removed in Conan 2.0
- The expectation is to replace it with dev flow (``conan install`` + native build system), or ``conf``.
- The new integrations in ``conan.tools`` like CMakeToolchain, etc, do not listen to those ``should_xxxx`` anymore.

**Comment by dornbirndevelops** [comment]
thank you for the quick response.

> * The expectation is to replace it with dev flow (`conan install` + native build system), or `conf`.

is this new intended dev flow documented somewhere?

**Comment by memsharded** [comment]
Yes, for example the updated page for editables: https://docs.conan.io/en/latest/developing_packages/editable_packages.html, already use this ``conan install`` + ``cmake ...`` flow

**Comment by dornbirndevelops** [comment]
ok, thank you very much for the quick response.
I will have a look 👍🏼
