### ISSUE TITLE
[bug] PkgConfigDeps raises exception when generating for packages in editable mode and has defined layout()

### ISSUE THREAD

**Issue by phillipcaofph** [conan-io/conan#11435]
PkgConfigDeps raises exception when generating for packages in editable mode and has defined layout()

I've dug deeper and found the exception is located in https://github.com/conan-io/conan/blob/485b78e1c59edda5f510449f08565ae753eae3b8/conan/tools/gnu/pkgconfigdeps/pc_files_templates.py#L90

It looks like other places such as https://github.com/conan-io/conan/blob/485b78e1c59edda5f510449f08565ae753eae3b8/conan/tools/cmake/cmakedeps/templates/target_data.py#L48 is handling this case specifically by setting if undefined. I've found that setting it to "." works better than "" for the case of PkgConfigDeps.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: N/A
  * Conan version: 1.48.1
  * Python version: 3.9.6

### Steps to reproduce (Include if Applicable)

1. PkgA uses PkgConfigDeps generator and requires PkgB which has layout() defined and is set to editable.
2. Run conan install

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
❯ conan install .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7.1
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.py (PkgA/1.0.0): Installing package
Requirements
    PkgB/1.0.0 from user folder - Editable
Packages
    PkgB/1.0.0:1606b0974992581e3485744de0a3163088c87205 - Editable
PkgB/1.0.0: Generated conan.lock
conanfile.py (PkgA/1.0.0): Generator txt created conanbuildinfo.txt
conanfile.py (PkgA/1.0.0): Calling generate()
Generate pkgconfig files
ERROR: conanfile.py (PkgA/1.0.0): Error in generate() method, line 56
        pc.generate()
        AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by memsharded** [comment]
Done a PR to fix it https://github.com/conan-io/conan/pull/11440.
I have kept the same ``""`` default instead of ``"."``, it shoudn't matter, as it shouldn't be used (the paths are absolute), and to be consistent with other generators. If there is something failing, better know it, have a test that reproduce it.
