### ISSUE TITLE
[question] Conan error settings.comipler is not defined. Am I stupid?

### ISSUE THREAD

**Issue by NeoCortex97** [conan-io/conan#11444]
I tried to use conan to add rtmidi to my project and conan sends me the folloging error message:
```
ERROR: rtmidi/5.0.0: 'settings.compiler' value not defined
```
I cannot find how to fix this, Am I stupid for missing this part in the coumentation, or is the package broken?  
Sorry that I cannot give any more details so far!

EDIT:  
Sorry, seems like a classic rtfm problem. I looked in the troubleshooting section and found the -s switch.

But my Problem is not that simple, because it misses `settings.compiler.libcxx` now. Do I really need to find all that stuff by hand and specify it in every call of conan install?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @NeoCortex97 

I think you're looking for the [Conan profiles documentation](https://docs.conan.io/en/latest/reference/profiles.html).
It'll solve your problem of having to put the same settings, configuration, etc. every time.

**Comment by franramirez688** [comment]
@NeoCortex97 

By the way, I think you should use a `default` profile. If you use a `default` profile, you won't even need to put the `-pr myprofile` parameter in your CLI every time.

Normally, this default profile is in `~/.conan/profiles/default`, and looks like this:

```
$ cat ~/.conan/profiles/default
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```
Furthermore, you can use this Conan command to create a new `default` one:

```
$ conan profile new default --detect
Found apple-clang 12.0
Profile created with detected settings: /Users/myuser/.conan/profiles/default
```
If you want to recreate it in case that it already exists, you could use `conan profile new default --detect --force`.

After that, I recommend you review that created profile to verify whether the settings are the good ones that you want to use.

**Comment by memsharded** [comment]
Hi @NeoCortex97 

Any feedback regarding the above? Did you make it work?

**Comment by memsharded** [comment]
Inactive, closing.
