### ISSUE TITLE
[bug] Framework dirs that do not exist

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#11442]
See comment from @SSE4 https://github.com/conan-io/conan-center-index/pull/11139#issuecomment-1153556092

It looks like PkgConfigDeps and AutotoolDeps are creating `-F <framework-directory>` links to folders that don't even exist.

Check if there could be any other folders like this one.

**Comment by memsharded** [comment]
> It looks like PkgConfigDeps and AutotoolDeps are creating -F <framework-directory> links to folders that don't even exist.

With new tools, if the folder doesn't exist, it is the responsibility of the recipe to not declare it @lasote?

**Comment by franramirez688** [comment]
Then, it looks like it's expected behavior, isn't it? Closing the issue then. Thanks for the clarification @memsharded

**Comment by franramirez688** [comment]
Finally, it has been implemented by https://github.com/conan-io/conan/pull/11455. It'll be released in the next Conan 1.50.
