### ISSUE TITLE
[bug] OpenSSL Cannot load recipe

### ISSUE THREAD

**Issue by daimend** [conan-io/conan#11448]
### Environment Details (include every applicable attribute)
  * Operating System+version: Win 11 and OSX 12
  * Compiler+version: msvc and clang
  * Conan version: 1.48 and 1.49
  * Python version: 3.9.4 and 3.9.13

### Steps to reproduce (Include if Applicable)

Doesn't seem to matter which platform/OS, which environment (local or virtual), or which versions of the toolsets/dependencies are installed; OpenSSL always fails (have even tried forcing other versions of OpenSSL)... same exact error regardless.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Trying to clone repo: https://github.com/conan-io/conanclientcert.git
Repo cloned!
Copying file cacert.pem to C:\Users\x\.conan\.
Copying file LICENSE to C:\Users\x\.conan\.
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=msvc
compiler.runtime_type=Debug
compiler.version=193
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: openssl/1.1.1l: Cannot load recipe.
Error loading conanfile at 'C:\Users\x\.conan\data\openssl\1.1.1l\_\_\export\conanfile.py': Unable to load conanfile in C:\Users\x\.conan\data\openssl\1.1.1l\_\_\export\conanfile.py
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\x\.conan\data\openssl\1.1.1l\_\_\export\conanfile.py", line 2, in <module>
    from conan.tools.microsoft import is_msvc, msvc_runtime_flag
ImportError: cannot import name 'is_msvc' from 'conan.tools.microsoft'

**Comment by memsharded** [comment]
Hi @daimend 

Are you completely sure you are running latest Conan? Can you check ``conan --version`` just before the above?
Because it seems that you are not in the latest Conan version, that error happens for older Conan versions.

**Comment by japj** [comment]
I have this same with conan 1.44.1.0,

I guess the minimum (from https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/1.x.x/conanfile.py#:~:text=required_conan_version%20%3D%20%22%3E%3D1.47.0%22) is 1.47.0 now

I would have expected a failure stating that 1.44.1 needs to be updated
(from the ImportError this is not exactly clear)

**Comment by memsharded** [comment]
Hi @japj 

Indeed this message could be improved. There is already a ticket for this in https://github.com/conan-io/conan/issues/11239, so I am closing this as duplicate (it is not clear that it will get enough priority to be fixed in the 1.X scope, but at least better track the other issue, as it is more complete and already outlines the possible approach to implement.  Thanks!
