### ISSUE TITLE
Adding prop sheets to MSVS with non standard config names

### ISSUE THREAD

**Issue by fittyCent** [conan-io/conan#11450]
I did a `conan install` with a `conanfile.py` file and profiles with build type set to `Release` - that generated some prop sheets. These prop sheets work great if I'm adding them to a project whose config name is `Release`. I do have a project config named `Release DLL` and adding the sheet to that, doesn't work. The vars are not added correctly so it can't find the include paths to the conan package.

I checked the generated prop sheet (`conan_libcurl.props`) and it says 
`<Import Condition="'$(Configuration)' == 'Release' And '$(Platform)' == 'x64'" Project="conan_libcurl_debug_x64.props"/>`
Same goes with the prop sheets of libcurl's deps.

Looks like it's targeting a config named `Release` and therefore it didn't work for my project config named `Release DLL`. Is there a way to create a profile such that when I run `conan install` against it, it generates prop sheets that target `Release DLL` instead of `Release`?

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @fittyCent 

There is a ``MSBuildDeps.configuration`` that you can tweak in your ``generate()`` to replace the standard ``Release`` one.

Please check https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html#custom-configurations for further details.

**Comment by fittyCent** [comment]
Thanks! Here's what I did:

profile file looks like:
```
[settings]
...
...
[options]
configuration=Custom Config Name
```

in the conanfile.py:
```
ms = MSBuildDeps(self)
if self.options.configuration != 'None':
  ms.configuration = self.options.configuration
ms.generate()
```

Now I can use the profiles to generate multiple prop sheets for multiple projects.

**Comment by memsharded** [comment]
Ok, that seems to be good. But if you have things like ``options = {"shared": ...`` then maybe you want to encode that as the final ``configuration`` (the configuration as a function of already existing settings and options like "shared") to avoid artificial extra combinations. For a consumer-only case it might not be relevant, but if at some point so want to create packages for it, then having the correct binary model is also important, so please take it into account.

**Comment by fittyCent** [comment]
Thanks for the tip, I'll keep that in mind. I'm just writing a consumer-only conanfile.

Thanks for the awesome work. I've been moving more and more projects toward using it.
