### ISSUE TITLE
Profile include statement

### ISSUE THREAD

**Issue by tru** [conan-io/conan#1145]
I would like to make it possible to include one profile in the other. There is several reasons for this:

1) linux-x86_64 and linux-x86 could share several CFLAGS and it would be unnecessary with a lot of code duplication there
2) With the suggested #1141 it would be hugely beneficial to be able to include the whole part that handles buildtools and centralize that into one file

I think a simple pre-processor include before parsing the file is the simplest and most straight-forward way. Another possible solution would be able to use some kind of templating in the profiles and then have config file where you specify the keys.

The second one is more powerful for sure it could do something like this:

```
include(BuildTools)
[settings]
compiler={build_tools_compiler}

[env]
CC={build_tools_compiler_path}
CFLAGS={common_cflags} -DFOO
```

but I am not picky :)

**Comment by memsharded** [comment]
I'd suggest go for the most powerful, I wouldn't say it is much more difficult to implement.
Lets see if others give feedback.

**Comment by lasote** [comment]
I like the feature but I want to ensure that it's needed. I mean, with #1141, the tools can and should export the right environment variables/cpp_info needed for that tool. So I'm wondering if a profile with `[build_requires]` will still have many variable declarations to make this feature useful.

**Comment by memsharded** [comment]
I would say it is not only about the tools, but also about other items. Any key=value should be supported. So if you have lots of fixed options that you are sharing among different profiles, and changing only the settings and env-vars, you might want to put all option in a common file.

**Comment by lasote** [comment]
@memsharded any user reported that problem with a lot of options? (just asking)

**Comment by memsharded** [comment]
Agree. Most likely we should move forward this feature request to 0.23, and wait until the new [build_requires] are released, tested and get more feedback about usage. Being mostly UX rather than functional, no big issue to postpone it.
