### ISSUE TITLE
[question] Should conan lockfiles not also store transitive dependency information?

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#11466]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Using Conan 1.49.0.

We are trying to create a lock file for a specific package, but only the first level requirements that is specified by that package is put into the lockfile.
We are expecting that the full dependency graph *including transitives* are represented in this lockfile. Otherwise how is full reproducibility ensured?

The situation arises:
`pkgA` --req-> `pkgB` --req-> `pkgC`.
1.  Running `conan lock` on `pkgA` provides locking information for `pkgB`, but not for `pkgC`.
2. The revision of `pkgC` changes (out of our control)
3. We build `pkgA` with the lockfile generated in step `1` (after that revision change of `pkgC` in step `2`), we get different behaviour for `pkgA`.

=> Not fully reproducible.

What is the rationale here? Feels like Conan lockfiles fails in its intention?

**Comment by memsharded** [comment]
Hi @SeanSnyders 

Definitely a lockfile should contain the full locking information for all transitive dependencies. This seems sufficiently tested, are you completely sure this is the behavior? Is it possible that instead of ``requires`` you are using ``build_requires`` (or ``tool_requires``)?

**Comment by SeanSnyders** [comment]
@memsharded Thanks for the quick response. Let me cycle back with the team and get more details. You might be correct in that this is a `build_requires` situation.

**Comment by SeanSnyders** [comment]
This seems to have been a hiccup in the project for this specific team in question.
Closing this.
