### ISSUE TITLE
[question] is there a way to have SCM not copy all submodule content?

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#11467]
When using the scm with auto it appears that all content of the local repository are copied recursively upon using conan create. When dealing with a big repository this operation will take a LONG time, especially on windows due to several 10s of thousands of files having to be copied. It takes around 5 minutes on Linux systems, but around 20+ minutes on Windows.
Now most of these files are within submodules and don't have to be copied as they could just be retrieved from git instead. At least as long as there are no local changes within the submodule. For some reason that appears to be quite a bit faster than copying a large number of small files.

Is there a way that within the recipe you can opt not to collect the submodule sources and grab them at later (e.g. configure) time through git? Alternatively can conan be told to do so when creating the package?

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

We have recently introduced a new way of handling ``scm``, which is more explicit and flexible:
- The ``scm`` attribute dissapear
- The capture of scm url and commit, happens explicitly in ``def export()`` method
- The captured url and commit are added explicitly in the ``export()`` method to ``conandata.yml``
- The fetch of the source code, with scm clone/checkout is also explicit in the ``source()`` method, from the ``conandata.yml`` stored data

This way allows to fine control the behavior that you want. Please have a look to: 
- https://docs.conan.io/en/latest/reference/conanfile/tools/scm.html
- https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature

**Comment by Sil3ntStorm** [comment]
Thanks, I will check that tomorrow.

As for the last section I would suggest rewriting that to be more explicit as to what is removed in conan 2.0. On first read it read as though the feature described on that very page is to be removed in conan 2.0, when (at least I assume) the features described on that page are there to remain, but the scm attribute of a conanfile is to be removed in conan 2.0.

**Comment by memsharded** [comment]
Clarified in https://github.com/conan-io/docs/pull/2595. In any case, the information is better summarized in the migration guide: https://docs.conan.io/en/latest/conan_v2.html

**Comment by memsharded** [comment]
``scm`` deprecated in 1.X, removed in 2.0, closing this ticket as outdated.
