### ISSUE TITLE
[question] How to retreive reports generated by CMake

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan#11475]
Hello,

I'm in a CI context (Gitlab CI), and have CMake which generates some tests results and coverage reports in XML files.
My CI instructions consists to call "conan create ." then "conan upload". 
I search a mean to retreive the path to these XML files reports in a genery way, for example a way to retreive "~/.conan/data/myPackage/x.y.z/user/channel/build/packageId/tests/gtests-*.xml" path, to copy them to initial git clone to inform Gitlab CI which files to use to have report in Gitlab UI.

I have look for "conan get", "conan inspect" without success.

Do you have some tips for this use case?

Regards.

**Comment by memsharded** [comment]
Hi @EstebanDugueperoux2 

If you would like to have these files as part of the package, then you need to package them. Probably something like:

```python
from conan.tools.files import copy
def package(self):
      build_logs= os.path.join(self.package_folder, "build_logs")
      build_folder= os.path.join(self.build_folder, "path", "to", "xmls")
      copy(self, "*.xml", build_folder, build_logs, keep_path=False)
```

That would make the logs part of the Conan package. Not sure that is what you want. These kind of files often are part of the CI
Probably the approach you are looking for is to use a ``post_build()`` Conan hook. You can write a script that will execute after your ``build()`` method, and can do whatever you want, like copying those xml files to the folder your CI defines. This hook also has the advantage that will be used for all packages, without needing to touch the ``package()`` method.

**Comment by EstebanDugueperoux2** [comment]
Hi @memsharded

Indeed hook seems a good solution.
#4694 issue talks about that also.

**Comment by EstebanDugueperoux2** [comment]
Then I try to prototype my hook to copy my gtest results to the original git clone:

```
import os
import shutil

def post_build(output, conanfile, **kwargs):
    output.warn("Copy tests results to source folder")
    output.warn("output: %s" % output)
    output.warn("conanfile: %s" % conanfile)
    output.warn("conanfile.source_folder: %s" % conanfile.source_folder)
    output.warn("conanfile.build_folder: %s" % conanfile.build_folder)
    # output.warn("conanfile.recipe_folder: %s" % conanfile.recipe_folder)
    
    output.warn("kwargs: %s" % kwargs)
    output.warn("conanfile.in_local_cache: %s" % conanfile.in_local_cache)
    
    for file in os.listdir(conanfile.build_folder):
      output.warn("file: %s" % file)
      if file.endswith(".xml"):
        output.warn("copy {0} to {1}".format(file, recipe_folder))
        shutil.copy(file, recipe_folder)
```

But `conanfile.recipe_folder` doesn't seems a known attribute, while it is in the documentation https://docs.conan.io/en/latest/reference/conanfile/attributes.html#recipe-folder and I use conan latest release (1.49.0).
In addition recipe_folder doesn't corresponds to the git clone where I execute "conan create".
Do you have an attribute corresponding to the source?

And finally, as my conan package use test_package (https://docs.conan.io/en/1.44/reference/commands/creator/test.html), I get following values if I don't add `-tf None` to `conan create` invocation:

```
[HOOK - copy_test_results.py] post_build(): WARN: conanfile: jupiter2g/20.3.0@unite/testing (test package)
[HOOK - copy_test_results.py] post_build(): WARN: conanfile.source_folder: /export/home/workingArea/dev/jupiter2g/test_package
[HOOK - copy_test_results.py] post_build(): WARN: conanfile.build_folder: /export/home/workingArea/dev/jupiter2g/test_package/build/367e4b945b1eaf83ff7ae454299ec38a23554f61
[HOOK - copy_test_results.py] post_build(): WARN: kwargs: {'conanfile_path': '/export/home/workingArea/dev/jupiter2g/test_package/conanfile.py'}
[HOOK - copy_test_results.py] post_build(): WARN: conanfile.in_local_cache: False
```

On which condition I could skip my hook on test_package invocation?


Regards.

**Comment by memsharded** [comment]
Hi @EstebanDugueperoux2 

The thing is that the ``build()`` method does not necessarily have access at all to the git repo. For example, if you use ``conan install  mypkg/version@ --build=mypkg``, that doesn't build the package from a repo, it can download the recipe from the server, then build it in the cache, retrieving the sources (stored with ``exports_sources``, or in the ``source()`` method).

So it is necessary to store the tests somewhere else, or doing a local ``git clone`` inside the hook, and adding them there.
However, I would reconsider that approach, because I feel that storing the tests results in the original source git repo is not the best:
- It can increase a lot the size of the repo, specially if you do multiple builds.
- It is not really source code that needs to be versioned. For generated logs, files, etc., using scm is not the best, IMHO
- It can affect the package itself. For example, if you decide to use the ``scm`` feature in the recipes, for better reproducibility, then, everytime you do a new commit to store the test results, you would be creating a new recipe revision, and enter an infinite loop

If I had to implement this, I would try creating a zip of those test results, and uploading them to an Artifactory generic repository, using something that I could track, like the name_version_revision of the package, the timestamp, the CI job number...

**Comment by EstebanDugueperoux2** [comment]
In fact I don't want to version these tests results but I want to have them in a fixed path to be retreived by my CI pipeline.
Once on a fixed path, following CI tasks can access them to upload them to SonarQube, Gitlab CI artifacts, ... .

**Comment by EstebanDugueperoux2** [comment]
To compare with the way I do for a Java deliverable build with Maven:

- I have maven-surefire-plugin which generate JUnit results in target/ folder;
- Optionnally jacoco-maven-plugin to generate coverage report in target/ folder;
- And maven-sonar-plugin which access these reports to upload them to Sonarqube.

And as my CI pipeline is based on Docker, this is done in a simple Docker image including maven and with all dependencies in a cache through Docker volume.

If I want to do the same with conan, firstly I can access my report files with `conanfile.build_folder` attribute.
It remains to use/find a python module being able to sonar-scanner task, invoked from `post_build` hook, while using an official conan Docker image,.

**Comment by EstebanDugueperoux2** [comment]
And why https://docs.conan.io/en/latest/reference/conanfile/attributes.html#recipe-folder is not resolvable in a hook?
Is it a bug?

**Comment by memsharded** [comment]
The problem with ``recipe_folder`` is that even if it is resolved (I will have a look, that might be a bug), it will not be pointing to the user folder git repo. When it is in the cache the ``recipe_folder`` is a folder inside the cache, containing a copy of the ``conanfile.py``.

**Comment by EstebanDugueperoux2** [comment]
Ok then according to what you say and what is written in doc (https://docs.conan.io/en/latest/reference/conanfile/attributes.html#recipe-folder), I imagine when invoking the first time "conan create" with an empty cache recipe_folder is set to local folder, i.e. git clone in my case, and for following invocation, i.e. with cache non empty recipe_folder is set to ~/.conan/data/recipeName/recipeVersion/user/channel/export/.

In pre_export hook, conanfile_path and conanfile.recipe_folder references my git clone, then I could use this value in my post_build hook.
I noticed that conanfile.in_local_cache is always True even in the beginning of pre_export hook.
I'm beginner in Python but is it possible to share this conanfile.recipe_folder between pre_export and post_build hooks with a global var?

Thanks for your great support and your good job about conan, a great tool.

**Comment by memsharded** [comment]
It is only pointing to the user git repo folder in the ``export`` operation. After that, subsequent operations, like ``build()`` operates on the exported recipe, not the user folder one.

> I'm beginner in Python but is it possible to share this conanfile.recipe_folder between pre_export and post_build hooks with a global var?

No, it is not a matter of implementation, is more a flow and definition thing. If you try to capture the user folder in the ``export`` time, that would still be broken, if your package builds later without the repo (which might happen in CI or when adding a new architecture to build binaries), then the "folder" you are pointing to doesn't exist at all. 
The most important point is understanding that a ``build()`` in the cache is no longer attached to the original git repo folder at all, it is a new entity in the realm of packages (recipes and binaries), and its byproducts (test results, logs, etc) should be treated in the same way, not as source, but as "artifacts", and stored in some artifact storage. Maybe it makes sense that the hook just copies those files to another folder in the machine, defined by convention? Then other tools, later, after the build can access those files, check them, scan them, zip them and upload them, etc, but that could be decoupled from the hook and Conan and be done as a later operation?

A note about Conan 2.0: ``self.in_local_cache`` and ``self.develop`` variables have been removed, better not rely on them.


> Thanks for your great support and your good job about conan, a great tool.

Thanks, and happy to help :)

**Comment by EstebanDugueperoux2** [comment]
I agree, a better solution could be to define a convention.
Now the difficulty is to choose a folder generated, corresponding to my CI execution without collision with another CI execution.
In my Gitlab CI Docker context, perhaps ~/.cache/ci/$CI_JOB_ID/ where my hook will copy the analysis results.

Thanks.

**Comment by EstebanDugueperoux2** [comment]
A least remark, I hope, why post_build hook is called only during test_package when this last exists?
Is it a bug?

**Comment by EstebanDugueperoux2** [comment]
Finally for the specific case of Google tests results, a better solution can be to use GTEST_OUTPUT environment variable.
In context of Gitlab CI, it gives:

```
variables:
  GTEST_OUTPUT: "xml:$CI_PROJECT_DIR/tests_results/"

myJob:
  script:
    - conan create .
    - conan upload XXX
  artifacts:
    reports:
      junit: tests_results/*
```

**Comment by memsharded** [comment]
Yes, something like ``~/.cache/ci/$CI_JOB_ID/`` sounds good, and if GTEST_OUTPUT is good, then even better :)
