### ISSUE TITLE
[feature] CMakeToolchain: declare `cacheVariable` to be stored in CMakePresets

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#11476]
Proposal something like:

```
toolchain = CMakeToolchain(self)
toolchain.cache_variables = {"first_variable": {
          "type": "BOOL",
          "value": "OFF"
        }}
```

To discuss, names and interface.
https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

NOTE: `CMake` conan build helper parses that CMakePreset.json and pass variables with `-D` to the command line.

**Comment by memsharded** [comment]
How is multiconfig achieved? With ``if something: toolchain.cache_variables = ....``?

**Comment by lasote** [comment]
It cannot be managed for multi-config generators, even if you introduce the `if something:` that goes in the same "configure preset" that is common in the multi-config generators: (1 configure: 2 builds)
