### ISSUE TITLE
[feature] Using conan build when installed using `--output-folder`

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#11482]
Currently, I can't see a way to invoke `conan build` to build a library if it has been installed using `--output-folder` in conan 2.0. To illustrate:

```bash
$ conan new libfoo/0.1.0 --template=cmake_lib
$ conan install . --output-folder build
```
This results in the following structure:

```bash
.
├── CMakeLists.txt
├── CMakeUserPresets.json
├── build
│   └── build
│       └── generators
│           ├── CMakePresets.json
│           └── conan_toolchain.cmake
├── conanbuildinfo.txt
├── conanfile.py
├── conaninfo.txt
├── conan.lock
├── graph_info.json
├── include
│   └── libfoo.h
├── src
│   └── libfoo.cpp
└── test_package
    ├── CMakeLists.txt
    ├── conanfile.py
    └── src
        └── example.cpp
```
These are my various attempts to build from this structure using `conan build`:

```bash
$ conan build .
Using lockfile: '/home/user/projects/conan-cmake-example-lib/conan.lock'
Using cached profile from lockfile
conanfile.py (libfoo/0.1.0): Calling build()
ERROR: conanfile.py (libfoo/0.1.0): Error in build() method, line 36
        cmake = CMake(self)
        FileNotFoundError: [Errno 2] No such file or directory: '/home/user/projects/conan-cmake-example-lib/build/generators/CMakePresets.json'

```
```bash
$ conan build . --build-folder build
ERROR: conanbuildinfo.txt file not found in /home/user/projects/conan-cmake-example-lib/build
It is required for this command
You can generate it using 'conan install'
```
As far as I understand, this is the limit at which I can go before I start using deprecated features (`--install-folder`?). If I do use `--install-folder`, I can get this to "work" as follows:

```bash
$ conan build . --install-folder . --build-folder build
Using lockfile: '/home/user/projects/conan-cmake-example-lib/conan.lock'
Using cached profile from lockfile
conanfile.py (libfoo/0.1.0): Calling build()
conanfile.py (libfoo/0.1.0): CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/user/projects/conan-cmake-example-lib/build/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/user/projects/conan-cmake-example-lib/."
-- Using Conan toolchain: /home/user/projects/conan-cmake-example-lib/build/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The CXX compiler identification is Clang 13.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091


-- Build files have been written to: /home/user/projects/conan-cmake-example-lib/build/cmake-build-release
conanfile.py (libfoo/0.1.0): CMake command: cmake --build "/home/user/projects/conan-cmake-example-lib/build/cmake-build-release" '--' '-j24'
[ 50%] Building CXX object CMakeFiles/libfoo.dir/src/libfoo.cpp.o
[100%] Linking CXX static library liblibfoo.a
[100%] Built target libfoo
```

If the `--install-folder` command is deprecated, then this will cease to work. It does seem that this can be built directly with cmake:
```bash
$ cmake --preset Release
$ cmake --build --preset Release
```
So we can be confident that there is at least some utility to the `--output-folder` command. Noting that not all developers may wish to invoke cmake directly and would prefer to use `conan build` where possible, I'm proposing the addition of an `--output-folder` flag to `conan build`, such that all that would be required to trigger a build is:

```bash
$ conan install . --output-folder build
$ conan build . --output-folder build --build-folder build
$ conan build . --build-folder build # Assumes --output-folder == --build-folder if --output-folder is not specified
```
This would bring the `conan build` interface back inline with the way `--install-folder` is treated.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jsrivaya** [comment]
conan 2 introduces layouts in conanfile.

> self.folders.build (Defaulted to ""): Specifies a subfolder where the files from the build are. The self.build_folder attribute and the current working directory inside the build(self) method will be set with this subfolder. It is used in the cache when running conan create (relative to the cache source folder) as well as in a local folder when running conan build (relative to the local current folder).

```python
def layout(self):
    ...
    self.folders.source = "src"
    self.folders.build = "build"

    # In the local folder (before a conan create) the artifacts can be found:
    self.cpp.source.includedirs = ["my_includes"]
    self.cpp.build.libdirs = ["lib/x86_64"]
    self.cpp.build.libs = ["foo"]

    # In the Conan cache, we packaged everything at the default standard directories, the library to link
    # is "foo"
    self.cpp.package.libs = ["foo"]
```

https://docs.conan.io/2.0/reference/conanfile/methods/layout.html

**Comment by franramirez688** [comment]
Hi @samuel-emrys 

Sorry, but I'm likely missing something. You referred to Conan 2.0 but you're using Conan 1.x commands in your issue explanation, i.e., Conan 2.x workflow is working fine:

```
$ conan new cmake_lib -d name=hello -d version=1.0.0
$ conan install . -of build
# ...
$ conan build . -of build
# ....
[ 50%] Building CXX object CMakeFiles/hello.dir/src/hello.cpp.o
[100%] Linking CXX static library libhello.a
[100%] Built target hello
```
So, did you mean that Conan 1.x workflow is not such clear when using install (using -of folder) + build?

**Comment by samuel-emrys** [comment]
@franramirez688 I raised this issue over a year ago when Conan 2 was still in beta.. I don't remember raising this explicitly, but I'm assuming I was trying to use the Conan 1 flow of install + build with an output folder, which has replacements now. I think at the time, layout hadn't matured as much as it has now.

**Comment by franramirez688** [comment]
Oh, my bad. I did not realize about the date 😮‍💨 
I saw a new comment here and I thought it was new haha
Closing the issue then. Thanks!
