### ISSUE TITLE
[bug] Specifying `--output-folder` does not move all generated files to the specified folder

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#11483]
### Environment Details (include every applicable attribute)
  * Operating System+version: Arch Linux
  * Compiler+version: clang 13.0.0
  * Conan version: 1.49.0
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)
When running `conan install` with the `--output-folder` flag, a number of files are generated in the root of the project, as demonstrated below:

```bash
$ conan new libfoo/0.1.0 --template=cmake_lib
$ conan install . --output-folder build
```
Which results in the following structure:

```bash
.
├── build
│   └── build
│       └── generators
│           ├── CMakePresets.json
│           └── conan_toolchain.cmake
├── CMakeLists.txt
├── CMakeUserPresets.json
├── conanbuildinfo.txt
├── conanfile.py
├── conaninfo.txt
├── conan.lock
├── graph_info.json
├── include
│   └── libfoo.h
├── src
│   └── libfoo.cpp
└── test_package
    ├── CMakeLists.txt
    ├── conanfile.py
    └── src
        └── example.cpp
```

Now, I understand that `conaninfo.txt` and `graph_info.json` have been deprecated (maybe `conan.lock` too?) and so won't be generated outputs in Conan 2.0, but `conanbuildinfo.txt` doesn't appear to have been deprecated, yet it appears in the project root. This is in spite of the help text for `conan install`:

```bash
$ conan install --help
...
  -of OUTPUT_FOLDER, --output-folder OUTPUT_FOLDER
                        The root output folder for generated and build files
...
```
Which certainly seems to indicate that all generated files should be placed in the output folder. It would be good if the above were honoured and these files were directed to the folder specified by `--output-folder` - I'd prefer not to have generated files in my project root.

Moving at least `conanbuildinfo.txt` to the directory specified by `--output-folder` would (at least superficially, until an `--output-folder` option is added to the `conan build` interface) resolve my interface concerns raised in #11482.

**Comment by memsharded** [comment]
This is outdated, Conan 2 no longer generates those files, all files will go to the output folder. Closing as solved in 2.0
