### ISSUE TITLE
[feature] A way to suppress generation of superfluous files?

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#11484]
Currently, using the `CMakeToolchain` generator, a number of files are generated in the project root that serve no purpose:
* `conaninfo.txt`
* `graph_info.json`
* `conan.lock` (? not sure if this has been deprecated)

It would be good to have a way of either suppressing the output of these and other deprecated/superfluous files where they just add clutter, or at a minimum, add the ability to move them along with other generated files out of the project root as per #11483

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
These files have already been removed in Conan 2.0.
But it was not possible to get rid of them in Conan 1.X, as that would be breaking some users, so they are still there, cluttering a bit the folders, we know it, but so far that was a minor thing compared to the risk of breaking. And as we are already into 2.0, beta is being released this week, the extra effort of adding opt-outs and workarounds is not worth it.

**Comment by samuel-emrys** [comment]
> we are already into 2.0, beta is being released this week

Thanks for the update. Do you have any estimates for when 2.0 well be out of pre-release?

**Comment by memsharded** [comment]
It depends on the feedback, there is not a closed deadline. But I guess at least a few beta releases will follow, like 3-4 (which roughly translate to months)
