### ISSUE TITLE
[bug] ConanException: compiler.version setting required for vcvars not defined

### ISSUE THREAD

**Issue by Hyderman** [conan-io/conan#11481]
### Environment Details (include every applicable attribute)
  * Operating System+version: windows 11
  * Compiler+version: clang 14
  * Conan version: 
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)
Conanfile.txt : 
 ```
[requires]
 poco/1.11.2

 [generators]
 cmake
```
command :
```
conan install .. -pr=clang --build=missing
```

profile :
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=14
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
CC=C:\Tools\msys64\mingw64\bin\clang
CXX=C:\Tools\msys64\mingw64\bin\clang++
```
Error : 
```
openssl/1.1.1o: Applying build-requirement: strawberryperl/5.30.0.1
openssl/1.1.1o: Applying build-requirement: nasm/2.15.05
openssl/1.1.1o: WARN: Build folder is dirty, removing it: C:\Users\logan\.conan\data\openssl\1.1.1o\_\_\build\740ddc0b690a0b53f67532814015d0310d7d742a
openssl/1.1.1o: Copying sources to build folder
openssl/1.1.1o: Building your package in C:\Users\logan\.conan\data\openssl\1.1.1o\_\_\build\740ddc0b690a0b53f67532814015d0310d7d742a
openssl/1.1.1o: Generator txt created conanbuildinfo.txt
openssl/1.1.1o: Aggregating env generators
openssl/1.1.1o: Calling build()
openssl/1.1.1o: 
openssl/1.1.1o: ERROR: Package '740ddc0b690a0b53f67532814015d0310d7d742a' build failed
openssl/1.1.1o: WARN: Build folder C:\Users\logan\.conan\data\openssl\1.1.1o\_\_\build\740ddc0b690a0b53f67532814015d0310d7d742a
ERROR: openssl/1.1.1o: Error in build() method, line 742
        with tools.vcvars(self.settings) if self._use_nmake else tools.no_op():
        ConanException: compiler.version setting required for vcvars not defined
```

**Comment by memsharded** [comment]
Hi @Hyderman 

Can you please specify the Conan version you are using? This is critical to debug what could be happening.
Then, please try to reduce the case to the minimal reproducible case. I think requiring directly openssl in your conanfile could be enough, and it is not necessary to require ``poco`` and all its transitive dependencies.

I have being trying to reproduce, without success. I am getting different errors like: 
```
NMAKE : fatal error U1077: 'C:\ws\LLVM\clang13\bin\clang.EXE' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\nmake.exe"' : return code '0x2'Stop.
openssl/1.1.1o:
```

It is possible that the openssl recipe is not prepared to build with clang on Windows. If that is the case, we would need to move this to the ConanCenter index repo.

**Comment by Hyderman** [comment]
My conan version is 1.49.
I'm following the tutorial so i don't really need to use poco now.
I tried to use gcc:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```
Other things i use:
* IDE: Clion
* MSYS2 with mingw64

I can download openssl with gcc but i block at an other step:
```
libpq/14.2: 
libpq/14.2: ERROR: Package '7e4fe5e99aec5cc8f78973ab8ce64613ed35677c' build failed
libpq/14.2: WARN: Build folder C:\Users\logan\.conan\data\libpq\14.2\_\_\build\7e4fe5e99aec5cc8f78973ab8ce64613ed35677c
ERROR: libpq/14.2: Error in build() method, line 180
	autotools = self._configure_autotools()
while calling '_configure_autotools', line 100
	self._autotools.configure(args=args)
	ConanException: Error 1 while executing /c/users/logan/.conan/data/libpq/14.2/_/_/build/7e4fe5e99aec5cc8f78973ab8ce64613ed35677c/source_subfolder/configure --without-readline --without-zlib --without-openssl --prefix=C:/Users/logan/.conan/data/libpq/14.2/_/_/package/7e4fe5e99aec5cc8f78973ab8ce64613ed35677c 
```

**Comment by memsharded** [comment]
Hi @Hyderman 

I would like to recommend 2 different approaches to learn Conan in Windows:
- Using the recommended default compiler in Windows, which is Visual Studio. The community edition is completely free and easy to install. All the recipes in ConanCenter are built with Visual Studio, but not Mingw, so their support for Mingw might be limited.
- Use docker, this is the approach done by the free video training in https://academy.jfrog.com/path/conan, to use gcc under Linux, because this combination is also built by default in ConanCenter

Said that, this is an error in other recipe, not ``openssl``. I am trying to reproduce, with this:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
msys2/cci.latest
```
conanfile.txt:
```
[requires]
libpq/14.2
```
Then
```
conan install .. --profile=myprofile --build=missing
```

As you can see, I am using the ``msys2/cci.latest``, which helps getting the same msys2 environment, this is what we use in ConanCenter.

The error that I am seeing is:
```
checking for int timezone... yes
checking types of arguments for accept()... configure: error: could not determine argument types
```
You cut the output, so the error is not visible, is this the error that you are getting? In that case, this totally seems like ``libpq`` recipe build system might need a patch to be able to build in mingw. If that is the case, we can transfer this to ``conan-center-index`` repo.

**Comment by Hyderman** [comment]
Hi @memsharded

I have the same error than you,
I tried with wsl and it works perfectly. I will try with docker and msvc later.
Thanks.

**Comment by memsharded** [comment]
Great to know.

If later you still want to use mingw, and some recipe in ConanCenter is not building correctly, the best way is to report it to the ``conan-center-index`` repo. The community of contributors is doing a fantastic job there.
