### ISSUE TITLE
[question] package_info method is not working as expected

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#11499]
Hello Conan Folks, I have set up host profile and build profile I use a default one. I have set up cmake toolchain repo where I am setting up the necessary compiler and linker flags. But the package_info method seems to work in a loop and doesnot work as expected. I am not sure what i am doing wrong.

```python
def package_info(self):
        if self.settings_target.os == "Windows" and self.settings_target.arch == "ndp":
            self.env_info.CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "src", "ndp.cmake")
            self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "src", "ndp.cmake")
        elif self.settings_target.os == "Windows" and self.settings_target.arch == "kdp":
            self.env_info.CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "src", "kdp.cmake")
            self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "src", "kdp.cmake")
        else:
            print("No target settings defined")
        print("Using '" + self.env_info.CMAKE_TOOLCHAIN_FILE + "' as CMake toolchain file")
```
I use : `conan create . 1.0.0@test/devel  -pr:b=default -pr:h=kdp` it does pick and print the correct toolchain file but in the end also fails with:
```
Error in package_info() method, line 32
        if self.settings_target.os=="Windows" and self.settings_target.arch == "kdp":
        AttributeError: 'NoneType' object has no attribute 'os'
```

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @maitrey 

Yes, I guess that we're missing some important notes at the documentation level. I'll add some lines there to keep it clearer.

Let me show you how to use it correctly through this example:

**mac**
```
[settings]
os=Macos
arch = x86_64
build_type = Release
compiler=apple-clang
compiler.version=12.0
compiler.cppstd=14
compiler.libcxx=libc++
```
**ios**
```
[settings]
os=iOS
os.version = 14.3
os.sdk = iphoneos
arch = armv7
build_type = Release
compiler=apple-clang
compiler.version=11.0
compiler.cppstd=14
compiler.libcxx=libc++

[tool_requires]
libcxx/0.1
```
**conanfile.py**
```python
from conan import ConanFile
from conan.tools.files import save, copy


class Pkg(ConanFile):
    name = "libcxx"
    version = "0.1"
    settings = "os", "arch", "compiler", "build_type"

    def build(self):
        # HERE IT MUST USE THE SETTINGS-TARGET for CREATING THE BINARIES
        arch = self.settings_target.arch
        os_ = self.settings_target.os
        phone_sdk = self.settings_target.get_safe("os.sdk") or ""
        save(self, f"lib/libcxx-{arch}", f"libcxx{phone_sdk}-{os_}-{arch}!")

    def package(self):
        copy(self, "*", src=self.build_folder, dst=self.package_folder)

    def package_info(self):
        arch = self.settings_target.arch
        self.cpp_info.libs = [f"libcxx-{arch}"]
```

Now, you can create this package as a `build require`: `conan create . -pr:b=macos -pr:h=ios --build-require`.

Notice that, in Conan 2.X, if you want to avoid adding the `--build-require` param at the end of that command line, you'll have to add a `test_package/conanfile.py` instead because this one defines the consumption relation.

**Comment by maitrey** [comment]
Hello @franramirez688 , Thank you very much for your reply. But I just want to clarify before implementing as above. So my profile settings are very lean. I only have a default profile that comes with conan and two additional ones : kdp and ndp . Both of them contain `[tool_requires]
toolchain/2.0.0` . In the toolchain package  , I have cmake files defined which contains the compiler and linker flags. Offcourse with this approach , I fall into the trap that toolchain repo is highly dependent on the profiles. Also, in case a new profile is introduced then the toolchain repo needs to be released together.  Can you suggest if my approach is the optimal way to proceed forward? Also, in the above example what does the method save  does actually?

**Comment by franramirez688** [comment]
Hi @maitrey 

I think it would be great if you provide a minimal example of what you're trying locally.
It'd be really useful for me to understand your case and talk about best practices.

Anyway, your project is running executing: `conan create . 1.0.0@test/devel -pr:b=default -pr:h=kdp --build-require`? It's just to clarify if it worked or not.

Talking about the `save` tool, you can have a look at all the tools available: https://docs.conan.io/en/latest/reference/conanfile/tools/files.html

**Comment by maitrey** [comment]
Hi @franramirez688 , Thank you again for your reply. So here is the way I am trying to set up: 
Example profile: 
```
standalone_toolchain= D:/tools/kdp

[settings]
os=Windows
arch=kdp
arch_build=x86_64
compiler=kdp-gcc
compiler.version= v1.0.0
build_type=Release

[env]
PATH=[$standalone_toolchain/bin]
LICENSE_SERVER="8080@mylocallicenseserver.com"

[conf]
tools.cmake.cmaketoolchain:generator=MinGW Makefiles

[tool_requires]
cmaketoolchain/2.0.0@test/devel
 ```

cmaketoolchain contains a src directory where I have different cmake files Example of src/kdp.cmake:

```cmake
set(CMAKE_SYSTEM_NAME               Windows)
set(CMAKE_SYSTEM_PROCESSOR          kdp)

set(CMAKE_AR                        D:/tools/kdp-ar.exe CACHE INTERNAL "")
set(CMAKE_READELF_COMPILER          D:/tools/kdp-readelf.exe CACHE INTERNAL "")
set(CMAKE_C_COMPILER                D:/tools/kdp-gcc.exe CACHE INTERNAL "")
set(CMAKE_LINKER                    D:/tools/kdp-gcc.exe CACHE INTERNAL "")
set(CMAKE_OBJCOPY                   D:/tools/kdp-objcopy.exe CACHE INTERNAL "")
set(CMAKE_RANLIB                    D:/tools/kdp-ranlib.exe CACHE INTERNAL "")
set(CMAKE_OBJDUMP                   D:/tools/kdp-objdump.exe CACHE INTERNAL "")
set(CMAKE_STRIP                     D:/tools/kdp-strip.exe CACHE INTERNAL "")

set(CMAKE_C_FLAGS                   "-O2 -g -W -Wall -Wcast-align" CACHE INTERNAL "")

set(CMAKE_C_FLAGS_DEBUG             "" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_RELEASE           "" CACHE INTERNAL "")
set(CMAKE_EXE_LINKER_FLAGS          "-Wl" CACHE INTERNAL "")


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
message(STATUS "Using CMAKE_C_COMPILER         - ${CMAKE_C_COMPILER}")
message(STATUS "Using CMAKE_LINKER             - ${CMAKE_LINKER}")
```

And here is the contents of conanfile.py:

```python
from conan import ConanFile
import os

class MyCmakeToolchain(ConanFile):
    name = "cmaketoolchain"
    version = "2.0.0"
    description = "CMake Toolchain"
    topics = ("cmake")
    settings = "os", "arch", "build_type"
      
  def build(self):
        pass

    def package(self):
        self.copy("*.cmake", src="src", dst="src", keep_path=True)
        
    def package_id(self):
        # The package id will always be the same, irrespective of the settings.
        # more info https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info-header-only
        self.info.header_only()

    def package_info(self):
        if self.settings_target.os == "Windows" and self.settings_target.arch == "ndp":
            self.env_info.CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "src", "ndp.cmake")
            self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "src", "ndp.cmake")
        elif self.settings_target.os == "Windows" and self.settings_target.arch == "kdp":
            self.env_info.CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "src", "kdp.cmake")
            self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "src", "kdp.cmake")
        else:
            print("No target settings defined")
        print("Using '" + self.env_info.CMAKE_TOOLCHAIN_FILE + "' as CMake toolchain file")
```
I am using conan 1.47.0 and with this set up the conan create command fails. But conan create with --build-require passes. The reason for having cmake toolchain in one repo is that we donot need to set this in every repository.

**Comment by maitrey** [comment]
Would it be a better idea to put everything in profiles and maintain different profiles instead?

**Comment by maitrey** [comment]
If I switch to putting everything in profiles, I end up with MinGW options added by cmake , resulting in error:
bin/ld.exe: error: [50186] unrecognized option '--out-implib'
This comes from  - C:\Program Files\CMake\share\cmake-3.21\Modules\Platform\Windows-GNU.cmake.
````
set(CMAKE_${lang}_CREATE_SHARED_LIBRARY
    "<CMAKE_${lang}_COMPILER> <CMAKE_SHARED_LIBRARY_${lang}_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_${lang}_FLAGS> -o <TARGET> -Wl,--out-implib,<TARGET_IMPLIB> ${CMAKE_GNULD_IMAGE_VERSION} <OBJECTS> <LINK_LIBRARIES>")
  set(CMAKE_${lang}_LINK_EXECUTABLE
    "<CMAKE_${lang}_COMPILER> <FLAGS> <CMAKE_${lang}_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> -Wl,--out-implib,<TARGET_IMPLIB> ${CMAKE_GNULD_IMAGE_VERSION} <LINK_LIBRARIES>")
````
In this case, I donot use cmaketoolchain and have everything in profile like:
````
target_host=D:/tools/kdp/bin/kdp-
standalone_toolchain=D:/tools/kdp
cc_compiler=kdp-gcc

[settings]
os=Windows
arch=kdp
arch_build=x86_64
compiler=kdp-gcc
compiler.version= v1.0.0
build_type=Release

[env]
PATH=[$standalone_toolchain/bin]
LICENSE_SERVER="8080@mylocallicenseserver.com"
CC=$target_host-gcc.exe
LD=$target_host-gcc.exe
AR=$target_host-ar.exe
AS=$target_host-as
RANLIB=$target_host-ranlib
STRIP=$target_host-strip
CFLAGS=-O2 -g -W -Wall -Wcast-align
LDFLAGS=-Wl

[conf]
tools.cmake.cmaketoolchain:generator=MinGW Makefiles

**Comment by franramirez688** [comment]
Hi @maitrey 

Sorry for the delay!

I think it's fine to have every common variable in your `conanfile.py`, so it'll be easily centralized and managed.
Besides that, I guess that you're not using the [CMakeToolchain Conan generator](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html), are you? I think it'd help you a lot to simplify things via Conan recipe. For instance, you could have something like this:

```python
import os

from conan import ConanFile
from conan.tools.cmake import CMakeToolchain


class MyCmakeToolchain(ConanFile):
    name = "cmaketoolchain"
    version = "2.0.0"
    description = "CMake Toolchain"
    topics = ("cmake")
    settings = "os", "arch", "build_type"

    def generate(self):
        tc = CMakeToolchain(self)
        # Have a look at https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#variables
        # tc.variables["MYVAR"] = "MyValue"  # it is like set(MYVAR MyValue) in CMake
        tc.generate()

    def package(self):
        self.copy("*.cmake", src="src", dst="src", keep_path=True)
        
    def package_id(self):
        # The package id will always be the same, irrespective of the settings.
        # more info https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info-header-only
        self.info.header_only()

    def package_info(self):
        if self.settings_target.os == "Windows" and self.settings_target.arch == "ndp":
            self.conf_info.define("tools.cmake.cmaketoolchain:user_toolchain", [os.path.join(self.package_folder, "src", "ndp.cmake")])
        elif self.settings_target.os == "Windows" and self.settings_target.arch == "kdp":
            self.conf_info.define("tools.cmake.cmaketoolchain:user_toolchain", [os.path.join(self.package_folder, "src", "kdp.cmake")])
        else:
            print("No target settings defined")
        print("Using '" + self.conf_info.get("tools.cmake.cmaketoolchain:user_toolchain", check_type=str) + "' as CMake toolchain file")
```
As you can see, we're injecting via [conf](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#conf) your own cmake toolchain so it'll be automatically used by the consumers.

Anyway, there is another point about the `env_info` and `[env]` settings in your profile. The `[env]` and `self.env_info` are deprecated. Now, it's recommended to use `[buildenv]` in profiles, and `self.buildenv_info` (build time environment information) and `self.runenv_info` (runtime environment information) in your recipes.

So, taking back your original recipe:

```python
from conan import ConanFile
import os

class MyCmakeToolchain(ConanFile):
    name = "cmaketoolchain"
    version = "2.0.0"
    description = "CMake Toolchain"
    topics = ("cmake")
    settings = "os", "arch", "build_type"
      
  def build(self):
        pass

    def package(self):
        self.copy("*.cmake", src="src", dst="src", keep_path=True)
        
    def package_id(self):
        # The package id will always be the same, irrespective of the settings.
        # more info https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info-header-only
        self.info.header_only()

    def package_info(self):
        if self.settings_target.os == "Windows" and self.settings_target.arch == "ndp":
            self.buildenv_info.define("CMAKE_TOOLCHAIN_FILE", os.path.join(self.package_folder, "src", "ndp.cmake"))
            self.buildenv_info.define("CONAN_CMAKE_TOOLCHAIN_FILE", os.path.join(self.package_folder, "src", "ndp.cmake"))
        elif self.settings_target.os == "Windows" and self.settings_target.arch == "kdp":
            self.buildenv_info.define("CMAKE_TOOLCHAIN_FILE", os.path.join(self.package_folder, "src", "kdp.cmake"))
            self.buildenv_info.define("CONAN_CMAKE_TOOLCHAIN_FILE", os.path.join(self.package_folder, "src", "kdp.cmake"))
        else:
            print("No target settings defined")
        print("Using '" + str(self.buildenv_info.vars(self).get("CMAKE_TOOLCHAIN_FILE")) + "' as CMake toolchain file")
```

For more information about Conan [Environment variables](https://docs.conan.io/en/latest/reference/conanfile/tools/env.html).

**Comment by maitrey** [comment]
Hello @franramirez688 , Thanks again for your reply.  I was not using the[ CMakeToolchain Generator](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html) .
 Is it advisable to keep both profiles and cmaketoolchain files? Also, somehow for any bugfix or any new change there is a tight coupling. I anyhow would have to maintain a build and host profile. I am wondering if it is better to put everything into profiles. I would like to know any pros or cons for keeping in a repo and maintaining via conan recipes versus keeping everything in profiles. Also, I am missing the documentation for buildenv and runtime env settings in conan profile. I looked here : https://docs.conan.io/en/latest/reference/profiles.html .

**Comment by franramirez688** [comment]
Hi @maitrey 

I think it'll depend on the variability of your projects:

* Profiles are pretty helpful to share common things easily. Things that are variables, build environment, requirements, etc. that don't need any additional process.  It's the most straightforward way for sure.
* Recipes as toolchains are needed when you need something more powerful or need to customize some parts of the code because of the limitation of the plain texts in profiles.

So, in the end, there is not a "better recommended" way to proceed because it'll depend on your needs, and, if the profiles are enough, then it's a perfectly valid solution. Besides that, profiles could be even composed, so you can have as many as you want, adapted to your system, architecture, etc. In your case, you could have one for `ndp`, another one for `kdp`, and so on. For instance, you could have this structure of the profiles:

**common**

```
target_host_kdp=D:/tools/kdp/bin/kdp-
standalone_toolchain_kdp=D:/tools/kdp
cc_compiler_kdp=kdp-gcc

[settings]
os=Windows
arch_build=x86_64
build_type=Release

[buildenv]
LICENSE_SERVER="8080@mylocallicenseserver.com"
CFLAGS=-O2 -g -W -Wall -Wcast-align
LDFLAGS=-Wl

[conf]
tools.cmake.cmaketoolchain:generator=MinGW Makefiles
```

**kdp_profile**
```
include(common)

[settings]
arch=kdp
compiler=kdp-gcc
compiler.version= v1.0.0

[buildenv]
PATH=[$standalone_toolchain_kdp/bin]
CC=$target_host_kdp-gcc.exe
LD=$target_host_kdp-gcc.exe
AR=$target_host_kdp-ar.exe
AS=$target_host_kdp-as
RANLIB=$target_host_kdp-ranlib
STRIP=$target_host_kdp-strip
```

>  Also, I am missing the documentation for buildenv and runtime env settings in conan profile. I looked here : https://docs.conan.io/en/latest/reference/profiles.html .

You're completely right. I'll try to make a PR to add that part in the profiles section. Thanks for letting us know.

**Comment by maitrey** [comment]
Hello @franramirez688 , Thanks a lot for taking care of my issue.

**Comment by maitrey** [comment]
Since all my questions were answered, I would like to close the issue. Thanks!
