### ISSUE TITLE
"conan remove" command -p argument position sensitive

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1149]
In 0.21.0, it looks as though the `-p [package]` argument only works if it is a trailing argument:

```
conan remove -p 58daff96da1443a7302b9eedaca08a76f74870ab LocalGcc/6.1@jharris/testing
usage: conan remove [-h] [-p [PACKAGES [PACKAGES ...]]]
                    [-b [BUILDS [BUILDS ...]]] [-s] [-f] [-r REMOTE]
                    [-q QUERY]
                    pattern
conan remove: error: too few arguments
```

```
conan remove LocalGcc/6.1@jharris/testing -p 58daff96da1443a7302b9eedaca08a76f74870ab
Are you sure you want to delete "58daff96da1443a7302b9eedaca08a76f74870ab" packages from 'LocalGcc/6.1@jharris/testing' (yes/no): yes
```

**Comment by memsharded** [comment]
This is because of the underlying system arg parsing and the python library we are using. I think it will work (it works here at least) if you use ``-p=63da998e3642b50bee33f4449826b2d623661505`` with the ``=``. Please try.

**Comment by danimtb** [comment]
This has been open for a while and there has been many improvements in conan CLI. Tested with conan 1.4.4 and worked: `conan remove zlib/1.2.11@conan/stable -p f82a8f7ab675cec593ac94689330a88c378b5f62`

**Comment by memsharded** [comment]
The original question is still there:

```
(conan) λ conan remove -p 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 lib/1.0@user/channel
ERROR: Please specify a pattern to be removed ("*" for all)
```

Still, not something that conan can fix, because the argparsing understand the ID as a positional argument, as ``-p`` without arguments is possible, to specify "all" packages

The correct command line is with =
```
(conan) λ conan remove -p=5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 lib/1.0@user/channel
ERROR: Please specify a pattern to be removed ("*" for all)
```

So it was OK to close the issue, conan can't fix this easily, it is an argparse thing.
