### ISSUE TITLE
[question] How i can easy modify&debug source code of a conan library?

### ISSUE THREAD

**Issue by initlifeinc** [conan-io/conan#11496]
i create a conan package and integrate into my application.

but if i have a problem which is hard to fix, i hope i can integrate the source code of this conan library with application and then i could modify the source code, run and debug application, and repeat these two steps. it is a easy way for me to quick modify and check whether i fix the issue. i can see a way to use "conan source" and "conan build" to build local, but i don't known how to easy debug without change the library search path. it seems cmakebuildinfo.cmake is always use package in conan cache folder.

so  How i can easy modify&debug source code of a conan library? only modify some to change the library link from conan cache folder to my local source code folder.

**Comment by memsharded** [comment]
If you are going to heavily work on some recipe, it is probably recommended to use the ``editable`` feature.
You will also need to modernize the recipe, and use ``layout()``, ``generate()``, and the ``CMakeDeps`` ``CMakeToolchain`` new integrations. A good starting point is ``conan new hello/0.1 --template=cmake_lib``.

You can check: https://docs.conan.io/en/latest/developing_packages/editable_packages.html

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
