### ISSUE TITLE
[question] How can I get other conan package's info in current recipe?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#11500]
- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

For example, I am writing a recipe for A, and A requires B and C(also as conan package), and I need to get B and C's lib and header file location in A's recipe, how can i get it？

**Comment by memsharded** [comment]
Use:
```
self.dependencies["mydep"].cpp_info
```
Recall the recommend way to do this is in the ``generate()`` method of the consumer, to "prepare" the build with the information it needs.

See https://docs.conan.io/en/latest/reference/conanfile/dependencies.html
