### ISSUE TITLE
[question] How to handle changes in profiles?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11501]
Hi guys,

what is the canonical way of handling package options? I mean we usually define profiles which set the certain package options in them.
How to handle the case if a given package introduces a new option? If I add this to the same profile, consumers using the old version of the same package (without the new option) would epic-fail as Conan would complain that the given option does not exist (correctly) in the package. To create new profiles seems a bit of an overengineering to me, as that would introduce NxM kinda problem.
Please advise,

**Comment by memsharded** [comment]
Hi @harsszegi 

The compatible way to introduce new options, or new settings, without breaking, is to let them have a ``None`` value. For example:

```python
options = {"myoption": [None, "value1", "value2"]
```
With old profiles, not defining the ``myoption`` it will not fail. It will not change ``package_id`` either. New profiles can define the new values.

**Comment by harsszegi** [comment]
Awesome, thanks a lot!

**Comment by harsszegi** [comment]
Just a quick remark though. I might misunderstadning something.

I develop package "foo".
I release version 1.0.0 with 

options = {
 bar1: [None, "val1", "val2"]
}

However when I want to release 2.0.0 I need to add a new option, e.g.:

options = {
 bar1: [None, "val1", "val2"]
 bar2: [None, "val3", "val4"]
}

Until 1.0.0 the profile only contained foo:bar1=val1
I need to add (for 2.0.0 consumers) foo:bar2=val3 as well

However this breaks 1.0.0 consumers surely.
Are you saying the proposed way is to:
a.) backport foo:bar2 as a "dummy" option to 1.0.0 as well and release a new 1.0.1 and  enforce all consumers to switch to 1.0.1
OR
b.) create new profiles which include option for "foo:bar1" and "foo:bar2" as well and use that profile for 2.0.0 consumers, but keep the old profile for 1.0.0 consumers

Thanks

**Comment by memsharded** [comment]
> However this breaks 1.0.0 consumers surely.

Yes, you are right, if you need to keep the compatibility with older versions backwards, then you can do what you suggest, backport it. To make it not affect the ``package_id``, you might want to ``del self.info.options.bar2`` in the ``package_id()`` method. You might not need to create a new ``1.0.1``, as if the new option is not used at all, then it has no effect, it would be like adding a comment to the recipe, not worth to bump the version.

Other possible approach that you could try:
- Defining options pattern-based, won't break recipes that don't declare the option, like ``*:bar2=val3`` will not break recipes that do not declare ``bar2`` option

**Comment by harsszegi** [comment]
Awesome, thanks a lot @memsharded
