### ISSUE TITLE
[question] How to generate multiple packages out of one build and conanfile?

### ISSUE THREAD

**Issue by stlu1022** [conan-io/conan#11502]
Hello folks,

We are trying to generate multiple packages out of one build and conan file similar to [Package Approaches](https://docs.conan.io/en/latest/creating_packages/package_approaches.html) with the difference that we don't want to use build_type to differentiate since we need a debug and release version of each package. 

What would be the right way to generate multiple packages out of one build? 

Thank you in advance.

**Comment by memsharded** [comment]
Hi @stlu1022 

Using the ``build_type`` setting is exactly the way to generate multiple package "binaries". You keep the setting, and then do:
```
conan create .  # This defaults to Release
conan create . -s build_type=Debug
```
Conan package binaries are single-configuration, because that has multiple advantages as scale, you can build way more configurations in the same way:
```
conan create . -s build_type=RelWithDebInfo
conan create . -s build_type=Debug -o mypkg*:shared=True
conan create . -s compiler=gcc -s compiler.version=7 -s arch=armv8 ...
conan create . -s compiler=msvc -s compiler.version=191 ....
```
Also other reasons as performance (get only the binaries you need for a given build), security (less possibilities to deploy/disclose/release a debug binary), etc.

**Comment by stlu1022** [comment]
Hi @memsharded,

Thank you for the quick answer! 

Sorry if I haven't described our problem properly.

Our problem is that we need multiple seperate package binaries with the exact same settings.
Like this:
                                                       
Debug build for a shared library: 
-> Package 1 - containing .so (Debug)
-> Package 2 - containing *.hpp(Debug)

We also need the same thing for a release build accordingly.

**Comment by memsharded** [comment]
So you are packaging separately the headers and the binaries? that means that you want to have something like ``mypkg_headers/version`` and ``mypkg_libs/version`` as separate packages, and ``requires`` them independently? Why?

**Comment by stlu1022** [comment]
yes, we would need to separate it in sub-packages and "require" both on demand. When collecting components to compose all what is needed to create the target release, only the "mypkg_lib"s would be "required".

For legal reasons and access restrictions, we have to separate them. Basically external entities shall have access to the binary parts but not the source code (here headers)

**Comment by memsharded** [comment]
> For legal reasons and access restrictions, we have to separate them. Basically external entities shall have access to the binary parts but not the source code (here headers)

But are you planning to distribute to the ``external`` entities with Conan? If you are not, then it is not relevant, you can use Conan for your internal development, then you extract the artifacts you want to distribute, for example with an ``imports`` of just the libraries and not the headers. But no need to create complicated package structures for development time.

If you want to have a quick chat to discuss these things, feel free to write to info@conan.io, we can talk in the CppLang slack, or do a zoom or something.

**Comment by stlu1022** [comment]
Hi James,

I wrote an email a while ago (I used my company email though). I'm not sure if it got through. We would love to set up a short meeting.

**Comment by memsharded** [comment]
Hi @stlu1022 

I am afraid it didn't get through, I have check the spam folders too, I don't know what could have happened.
Could you please retry? Thanks!

**Comment by stlu1022** [comment]
Hi James, I tried again with my private email. Did it get through this time?

**Comment by memsharded** [comment]
After some clarification, it seems this is a case for:

- ``build_id()`` to make possible to build one time, and package those exact same artifacts in different variants
- Use of custom settings to drive the process and variants at will

I think this question can be closed now as responded, please don't hesitate to re-open or create new issues for any further questions, and we will keep in touch too!

**Comment by stlu1022** [comment]
Thank you so much :)
