### ISSUE TITLE
[bug] cmake_layout generate several build folders

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#11506]
We juste tried `conan_layout` with Conan version 1.49.0

We keep the conanfile in a "/conan/" subfolder, at the root of the repo.
So we have the following layout method:

    def layout(self):
        cmake_layout(self, src_folder="..")

Yet, after running `conan install`, it appears there are two build folders:
* One at the root of the repository (the one we expected)
* Another one in `/conan/build`, containing the `generators` subfolder. We expected this to be at `/build/generators` instead.

**Comment by franramirez688** [comment]
Hi @Adnn 

I cannot reproduce the issue. Let's try it with a clean example:

```bash
$ mkdir myproject && cd myproject
$  conan new hello/1.0 -m cmake_lib
$ mkdir conan && cd conan
$ mv ../conanfile.py ./
$ # now, replace the cmake_layout function with cmake_layout(self, src_folder="..") in your editor
$ conan install .
$ # Or even stay in the root project and run: conan install conan/conanfile.py (it works as well)
```
In my case, I can see only the `./conan/build/` folder.
Let me know if it's running OK on your side as well. If yes, then let's see your recipe to check if there could be another problem. The root build folder has the same content as the `./conan/build` one?

**Comment by Adnn** [comment]
But should not the build folder be `./build`, instead of `./conan/build`?

We were expecting the `build` folder to be created relative to the `src_folder` that was explicitly provided.

**Comment by franramirez688** [comment]
That build folder will be created next to the conanfile.py regardless of the `src_folder`. If you really want to change that build location you have to use the `[-of  DIR]` param:

```
$ conan install . -of ..
# Now, the build folder will be located in ../ root folder
```

**Comment by Adnn** [comment]
Thank you @franramirez688 for this clarification, we expected the build folder to be relative to `src_folder`, hence our confusion.

Sorry for the noise, I am closing this issue.
