### ISSUE TITLE
[bug] Problems when try use conan on M1

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#11518]
### Environment Details (include every applicable attribute)
  * Operating System+version: macos mojave m1 processor
  * Compiler+version: clang 13
  * Conan version: latest
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)

```
git clone https://github.com/nativium/nativium.git
cd nativium
python3 nativium.py conan setup   
python3 nativium.py target ios setup 
python3 nativium.py target ios build
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

Hi, i have some problems when try use conan in M1. I don't know if is a conan problem or cmake problem. I tried different cmake versions, but the error is the same:

```
python3 nativium.py target ios build
[INFO] Running "build" on target "ios"...
[INFO] Building for: armv7/Debug...
Using lockfile: '/Users/paulo/Developer/workspaces/nativium/build/ios/Debug/ios/armv7/conan/conan.lock'
Using cached profile from lockfile
conanfile.py (nativium/None): Calling build()
CMake Error at /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/Platform/iOS-Initialize.cmake:4 (message):
  
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
  is not an iOS SDK
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:53 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/paulo/Developer/workspaces/nativium/build/ios/Debug/ios/armv7/target/CMakeFiles/CMakeOutput.log".
ERROR: conanfile.py (nativium/None): Error in build() method, line 91
	cmake.configure()
	ConanException: Error 1 while executing cd '/Users/paulo/Developer/workspaces/nativium/build/ios/Debug/ios/armv7/target' && cmake -G "Xcode" -DCMAKE_OSX_ARCHITECTURES="armv7" -DCMAKE_SYSTEM_NAME="iOS" -DCMAKE_SYSTEM_VERSION="9.0" -DCMAKE_OSX_DEPLOYMENT_TARGET="9.0" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="13" -DCONAN_LIBCXX="libc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/Users/paulo/Developer/workspaces/nativium/build/ios/Debug/ios/armv7/target/package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE="BOTH" -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY="BOTH" -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE="BOTH" -DNATIVIUM_DEPLOYMENT_TARGET="9.0" -DNATIVIUM_PLATFORM_ARCH="armv7" -DCMAKE_BUILD_TYPE="Debug" -DNATIVIUM_PROJECT_NAME="nativium" -DNATIVIUM_PRODUCT_NAME="Nativium" -DNATIVIUM_ARCH="armv7" -DNATIVIUM_GROUP="ios" -DNATIVIUM_TARGET="ios" -DNATIVIUM_BUILD_TYPE="Debug" -DNATIVIUM_VERSION="1.0.0" -DNATIVIUM_VERSION_CODE="1" -DNATIVIUM_ENTRYPOINT="" -Wno-dev '/Users/paulo/Developer/workspaces/nativium'
COMMAND: conan build /Users/paulo/Developer/workspaces/nativium/conan/recipe/conanfile.py --source-folder /Users/paulo/Developer/workspaces/nativium --build-folder /Users/paulo/Developer/workspaces/nativium/build/ios/Debug/ios/armv7/target --install-folder /Users/paulo/Developer/workspaces/nativium/build/ios/Debug/ios/armv7/conan
WORKING DIR: /Users/paulo/Developer/workspaces/nativium/build/ios/Debug/ios/armv7/target
[ERROR] Command execution has failed
```

**Comment by paulocoutinhox** [comment]
Im trying debug and understand where is the problem. On cmake side i post here:
https://gitlab.kitware.com/cmake/cmake/-/issues/23662

And on conan i will post here.

When i print the environment variable here:
https://github.com/conan-io/conan/blob/19718de898cecc8cc9df70a12cb03db294261f2e/conans/client/build/cmake_flags.py#L298

```
print("===========", os.getenv("SDKROOT") ,"==============")
```

Is shows MacOS SDK:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

**Comment by paulocoutinhox** [comment]
I "found" the problem. When i print my python `os.environ` is shows:

```
python3 -c 'import os; print(os.environ["SDKROOT"])'
```

Shows:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

But is not listed in my environment variables when i use `printenv`:

```
printenv | grep SDKROOT
```

What can be wrong?

**Comment by paulocoutinhox** [comment]
I think that the python 3.8.9 `that come` with the macos monterey 12.4 has this variable `embed`.

Because when i install python3 from `brew`, this environment variable don't exists:

```
brew install python@3.10
/opt/homebrew/opt/python@3.10/bin/python3 -c 'import os; print(os.environ["SDKROOT"])'

# error, SDKROOT don't exists
```

I tested here with `three different macbooks` and python3 `native` from monterey already come with environment vars and the brew installation come without it.

**Comment by paulocoutinhox** [comment]
Conan only works, if i set this environment variable equal empty string.

**Comment by paulocoutinhox** [comment]
I tested on macos monterey 12.4 and 12.3.1 and the same problem exists.

**Comment by jcar87** [comment]
This is an issue with the system's `python3` on macOS (specifically the `/usr/bin/python3`). It is the equivalent of doing `xcrun python3`, which locates an xcode or Command Line Tools installation. It is the documented behaviour of `xcrun` to actually define the `SDKROOT` variable (and it will default to the macOS SDK unless told otherwise). You can read more about this [here](https://macops.ca/developer-binaries-on-os-x-xcode-select-and-xcrun/), or the `man xcrun` and `man xcode-select` manpages.

So this variable isn't necessarily embedded, however it certainly causes issues: in this case, a `conan` run from that python3 interpreter will pass that variable down to the process tree, unless the variable was overridden somewhere (a `tool_requires` or a conan profile).

A way to bypass this would be to launch the "real" python3 directly (you can get the path with `xcrun --find python3`). If that one is invoked directly, `SDKROOT` will not be defined and you will observe the same behaviour as with homebrew's python

`$(xcrun --find python3) -c 'import os; print(os.environ["SDKROOT"])'` 

My advice in this particular case would be to have the conan profile, or the tool requires, specify this variable so that conan can pass the correct value when calling CMake.  
I believe that in the nativium tool, this file: https://github.com/nativium/nativium/blob/main/conan/darwin-toolchain/conanfile.py could query the correct SDK path and correctly set the `SDKROOT` environment variable for conan to propagate when CMake is invoked.

**Comment by paulocoutinhox** [comment]
Hi,

How i can get the correct SDKROOT from conan?

If conan can return it, i can set with something like this:

```
self.env_info.SDKROOT = self.xyz.sdkroot()
```

Thanks.

**Comment by paulocoutinhox** [comment]
@theodelrieu You have this problem with your toolchain? Can you help me with this? I want make the minimum to solve this.

**Comment by paulocoutinhox** [comment]
Hi,

Im trying to solve it, but when i put this lines to my conanfile from darwin-package:

```
def package_info(self):
        # Sysroot
        print("++++++++++++++++++", self.settings.os)
        xcrun = tools.XCRun(self.settings)
        sysroot = xcrun.sdk_path

        self.cpp_info.sysroot = sysroot
        common_flags = ["-isysroot%s" % sysroot]

        self.env_info.CONAN_CMAKE_OSX_SYSROOT = sysroot
        self.env_info.SDKROOT = sysroot

        print("--------------------------",sysroot)
```

It shows:

```
++++++++++++++++++ Macos
-------------------------- /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk
```

But im compiling for armv7 / iOS:

```
python3 nativium.py target ios setup
[INFO] Running "setup" on target "ios"...
[INFO] Building for: armv7/Debug...
Configuration (profile_host):
[settings]
arch=armv7
arch_build=armv8
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=iOS
os.version=9.0
os_build=Macos
[options]
nativium_arch=armv7
nativium_group=ios
nativium_product_name=Nativium
nativium_project_name=nativium
nativium_target=ios
nativium_version=1.0.0
nativium_version_code=1
darwin-toolchain:enable_bitcode=True
[build_requires]
*: darwin-toolchain/1.0.0@nativium/stable
[env]

Configuration (profile_build):
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

conanfile.py (nativium/None): Installing package
Requirements
Packages
Build requirements
    darwin-toolchain/1.0.0@nativium/stable from local cache - No remote
Build requirements packages
    darwin-toolchain/1.0.0@nativium/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Cross-build from 'Macos:armv8' to 'iOS:armv7'
Installing (downloading, building) binaries...
darwin-toolchain/1.0.0@nativium/stable: Already installed!
++++++++++++++++++ Macos
-------------------------- /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk
```

**Comment by paulocoutinhox** [comment]
I solved by myself removing this env variable in my bootstrap file:
https://github.com/nativium/nativium/blob/5425ca3f53fe506076dcbfaf1ff3fd954235c3d9/core/util.py#L24

**Comment by paulocoutinhox** [comment]
I changed my solution after find the correct property from conan for target settings:

Nativium:
https://github.com/nativium/nativium/blob/main/conan/darwin-toolchain/conanfile.py#L84-L92

Thanks.
