### ISSUE TITLE
[question] How can I pass conan_include_dirs to parent scope?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#11513]
- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Circumstances like this:
package A relies on glog, gflags, pakcage B relies on eigen, proj, and package C relies on B, I need to pass A's and B's include directories to C, but when I use target_link_directories(... ${CONAN_INCLUDE_DIRS}), it seems useless, C still can't find glog/gflags/proj/eigen's header files.

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

We are missing tons of details here. Like what generators are being used (NOTE: the ``cmake`` generator is deprecated, recommended to move to ``CMakeDeps``, ``CMakeToolchain`` and ``CMake``, all in ``from conan.tools.cmake import xxx``), how your full CMakeLists.txt looks like, how your ``conanfile`` looks like, the output you got when doing ``conan install``, etc.

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed
> 
> We are missing tons of details here. Like what generators are being used (NOTE: the `cmake` generator is deprecated, recommended to move to `CMakeDeps`, `CMakeToolchain` and `CMake`, all in `from conan.tools.cmake import xxx`), how your full CMakeLists.txt looks like, how your `conanfile` looks like, the output you got when doing `conan install`, etc.

Why transfer cmake generator to CMakeDeps, CMakeToolchain and CMake？

**Comment by memsharded** [comment]
Because ``cmake`` generator has been deprecated, and already removed in Conan 2.0 (already released in beta). Only ``CMakeDeps``, ``CMakeToolchain`` do remain in Conan 2.0.
