### ISSUE TITLE
[bug] Unable to install Jfrog artifactory CE on WSL2

### ISSUE THREAD

**Issue by hmluqman** [conan-io/conan#11517]
I am following this [tutorial ](https://levelup.gitconnected.com/conan-package-manager-tutorial-bfb308ddd7a) about Conan Package Manager. I am unable to install artifactory service. 
### Environment Details
  * WSL2 (Ubuntu 20.04):
  * Conan version: 1.49.0
  * Python version: 3.8.10

### Logs (Executed commands with output)

I tried to install debian package download from Conan [website](https://conan.io/downloads.html)
`sudo dpkg -i jfrog-artifactory-cpp-ce-7.39.4.deb`

- Conan command output
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

If I follow the source code method i.e using tar ball

```
tar xvf jfrog-artifactory-cpp-ce-7.5.7-linux.tar.gz
cd artifactory-cpp-ce-7.5.7/app/bin
sudo bash installService.sh
```
Then trying to find service status using init based service command

```
sudo service artifactory status
artifactory: unrecognized service
```
Can somebody help here?

**Comment by memsharded** [comment]
Hi @hmluqman 

I don't think this is an Artifactory bug, but it is simply not supported platform, I don't see running Artifactory in WSL anywhere.

Please run ArtifactoryCE natively in Windows, Linux or using docker.

**Comment by hmluqman** [comment]
> Hi @hmluqman
> 
> I don't think this is an Artifactory bug, but it is simply not supported platform, I don't see running Artifactory in WSL anywhere.
> 
> Please run ArtifactoryCE natively in Windows, Linux or using docker.

**Comment by hmluqman** [comment]
@memsharded  You could be right. The WSL2 is init based system. On this Artifactory official installation [page ](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DebianInstallation) under section **Run Artifactory as a Service** is describing to run the service in init based system. I am not sure why is it not possible to run the service in WSL2.

**Comment by memsharded** [comment]
> You could be right. The WSL2 is init based system. On this Artifactory official installation [page ](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DebianInstallation)under section Run Artifactory as a Service is describing to run the service in init based system. I am not sure why is it not possible to run the service in WSL2.

Yes, in theory, it could. But there are too many moving pieces, DBs, JVM, etc, that probably any minor subtle differences is enough to make it not working.


In any case, if you are reading a somewhat outdated (2020) tutorial, I'd recommend keeping an eye on the official docs too.

Some utilities like ``conan new hello/0.1 --template=cmake_lib`` can help creating a modernized Conan recipe, that will be Conan 2.0 (already released beta) ready.
