### ISSUE TITLE
[develop2] [question] Reconsider ``CachedFileDownloader``?

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11515]
Maybe ask for feedback to the Tribe? I am not fully convinced about the value, maybe retire it in 2.0 while we investigate concurrency in the cache?

**Comment by SSE4** [comment]
is it possible to move custom downoaders to extensions/plugins?

**Comment by lasote** [comment]
> is it possible to move custom downoaders to extensions/plugins?

I think it is worth trying to think about it, I'll take a look. That way, we can remove it with (almost) no rejection from the users. That plugin can be contributed "externally" to conan code base.

**Comment by memsharded** [comment]
One thing to consider is that if we get good cache concurrency, this might not be necessary at all.
I have been having a look, it seems that with the multi-revision cache, and immutability it might be a bit easier to achieve more robust cache concurrency. (also fasteners got ReadersWriter lock)

**Comment by lasote** [comment]
> One thing to consider is that if we get good cache concurrency, this might not be necessary at all.

What about a different recipe revision downloading the same boost sources zip? Is it something the concurrency would solve?

**Comment by memsharded** [comment]
> What about a different recipe revision downloading the same boost sources zip? Is it something the concurrency would solve?

Not really, but this cache was born mostly trying to solve the pain of limited concurrency in the cache while installing Conan packages (big binaries).

**Comment by lasote** [comment]
Ok, then it is not worth it to try to "pluginize" it.

**Comment by memsharded** [comment]
Closed by #11650 

Discussion and feedback to re-enable it in 2.X follows in https://github.com/conan-io/conan/issues/11658
