### ISSUE TITLE
[develop2] Think new codebase layout

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11521]
We're maintaining `develop` and `develop2` branches and the conflicts are huge, so we'll have to keep it till we freeze 1.x and merge `develop2` -> `develop`. After that, we'll update all the imports from docs.

_Originally posted by @franramirez688 in https://github.com/conan-io/docs/pull/2607#discussion_r905832887_

**Comment by memsharded** [comment]
We need to move the public parts, like ``conans.cli`` to final ``conan.xxx`` namespace. So we need to outline the final structure. Not change it yet completely (conflicts develop->develop2), but maybe we can move ``conans.cli`` for a start.

**Comment by SSE4** [comment]
how about re-importing via a namespace alias, e.g. `conan.cli` -> `conans.cli`?

**Comment by lasote** [comment]
Tasks:

- Move `cli` to `conan`
- Remove `output` from cli
- Asset from `api/helpers/` to `_internals`
- conan.py and setup.py try to move to cli

**Comment by memsharded** [comment]
Closed by #11630
