### ISSUE TITLE
[bug] Old ABI compatibility warning has 83 columns

### ISSUE THREAD

**Issue by rbanffy** [conan-io/conan#11524]
### Environment Details (include every applicable attribute)
  * Operating System+version: Debian under WSL
  * Compiler+version: 11.3.0-3
  * Conan version: 1.49.0
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)

Installed conan via Pip on a virtual environment, on a terminal window set to 80x25 (because my eyes aren't getting any younger) and the warning message overflowed by just 3 columns.

It ended up a bit ugly (see capture below)

![image](https://user-images.githubusercontent.com/184714/175636119-0ecfba2f-b57e-4d2f-8340-6ace27efc321.png)

If you think this is a valid issue, I can offer a patch to make the warning either 80 columns or query the terminal about the window size and resize error messages accordingly.

**Comment by memsharded** [comment]
Hi @rbanffy 

Thanks very much for offering to fix this.

The thing is that we have already moved our efforts to Conan 2.0, and this warning has been removed already in 2.0. So unless there is something really broken, we prefer not touching it (it creates an added burden of merging from Conan 1.X branches to Conan 2.0 branches, conflicts, etc)

If you want to give it a try, https://docs.conan.io/en/2.0 docs are already there.

I think we can close this issue as won't fix. Thanks again for reporting!
