### ISSUE TITLE
MSBuildDeps Generator - Traits Support

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#11520]
Hi there,

I've been experimenting with the latest Conan 2.0.0-beta1 release - it's looking great! 

I was wondering if you could clarify if/when requirement traits support is coming the `MSBuildDeps` generator; currently is appears that transitive dependencies are always still included in the generated `.props` files and the various requirement traits don't impact the generated files e.g. in the `AdditionalIncludeDirectories` property etc.

Thanks!

**Comment by memsharded** [comment]
Hi @santhonisz 

Yes, you are right, some of the traits behavior are only applied to the ``CMake`` generators at the moment.
It totally makes sense to apply them to ``MSBuildDeps``, lets do it, thanks for the feedback.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/11680, will be in next beta.2

It also includes support for components.
