### ISSUE TITLE
[question] full_package_mode also include build requirement in package id 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#11539]
Hello,

Im trying to switch to `full_package_mode` for all packages, so I started defining the `package_id` method bellow for all recipe 

```
    def package_id(self):
        self.info.requires.full_package_mode()
``` 

First, I built meson with 1.11 and then when I tried to build pkgconf with ninja 1.10.2 I got this error

```
'pkgconf/1.7.4-g8709fbd@pmi/stable' requires 'ninja/1.10.2-gb935597@pmi/stable' 
while 'meson/0.62.2-g899c5b6@pmi/stable' requires 'ninja/1.11.0-gde9ebb3@pmi/stable'.
```

Is it expected that full_package_mode also include build requirements when computing package id  ?

**Comment by memsharded** [comment]
Hi @boussaffawalid 

In Conan 1.X, as mentioned for example in https://github.com/conan-io/tribe/pull/20, it is impossible to factor the ``build_requires`` into the ``package_id`` of the consumers. You can also see an explanation in: https://www.youtube.com/watch?v=kKGglzm5ous. 
There is a tricky workaround for this, that is to introduce a duplicate ``python_requires`` to the same package, that is not used for anything but for this.

For Conan 2.0, the discussion is still ongoing in https://github.com/conan-io/tribe/pull/36, but initially ``build_requires`` will not be part of the ``package_id`` by default, but it will be possible to configure in ``conf`` if they do, and how they do it.

Also, as a hint, instead of changing all recipes ``package_id()`` method, why don't you change the global default configuration instead?

**Comment by boussaffawalid** [comment]
@memsharded at first I thought about changing the global configuration, but then I released this is a breaking change.

Old branches will not compile anymore. We won't be able to recompile old releases without rebuilding the whole dependency graph.  Also old branches will not recompile anymore. This will be very painful for developers that compile some packages manually and uses other packages from CI.  

So I had to to implement `package_id` for all recipe (using python_requires) to avoid any surprises.

**Comment by boussaffawalid** [comment]
@memsharded about the tricky workaround using `python_requires`, how to implement it ? is there any example

**Comment by memsharded** [comment]
> Old branches will not compile anymore. We won't be able to recompile old releases without rebuilding the whole dependency graph. Also old branches will not recompile anymore. This will be very painful for developers that compile some packages manually and uses other packages from CI.

But you can keep the previous configuration for the old branches, and have a new configuration for the new builds. Using ``conan config install`` you can define different zip files, or different branches of the configuration origin repo.

> @memsharded about the tricky workaround using python_requires, how to implement it ? is there any example

Yes: https://docs.conan.io/en/latest/devtools/build_requires.html#making-tool-requires-affect-the-consumers-package-id

**Comment by boussaffawalid** [comment]
@memsharded I'm confused now, I want the package to be **independent** from build_requirements not dependent.

If I got it right, I should just switch from `build_requirements` to `tool_requires` and conflicts in build requirements won't happen anymore.  So even I use `full_package_mode` I will be able to different tool_requires versions. Or am I missing something here?

**Comment by memsharded** [comment]
Both in Conan 1.X and 2.0, by default, ``build_requires`` or ``tool_requires``, do not affect the consumers ``package_id`` at all.

It seems that the error that you are referring above is a version conflict, nothing to do with ``package_id``. Sorry I was confused by the context and the title.

Using the 2 profiles approach, can reduce the number of version conflicts that happen between the host and build context, in case there are dependencies in both contexts.

**Comment by memsharded** [comment]
Conan 2 allows build-requires to affect package_id now, closing as solved in Conan 2.
