### ISSUE TITLE
[question] Is the conan_server API documented somewhere?

### ISSUE THREAD

**Issue by knzivid** [conan-io/conan#11544]
[This page](https://docs.conan.io/en/1.46/uploading_packages/running_your_server.html) on conan_server mentions that it implements _Conan remote repositories_. Is this a protocol that's documented on wiki? I could not find anything on search engines. I see [gitlab](https://gitlab.com/gitlab-org/gitlab/-/blob/dc43147c35d236f98cdca1a2129cb5e31eae0e3c/ee/lib/api/conan_packages.rb) and gitea implement their own server, and I am wondering how difficult it is to implement a toy conan server. This is not meant for production use, but to learn more about conan remotes. 

Any help is appreciated :)

**Comment by uilianries** [comment]
Hello @knzivid The Conan Server API is not documented and will not be. As it's an internal feature, the protocol can be changed without affecting the users, so Conan does not guarantee any API compatibility.

The Gitlab did a reverse engineer to get that protocol, they needed to study the code. Well, it's FOSS under MIT license, so people can do what they want :)

The best option is running [Artifactory](https://conan.io/downloads.html), which has a public API well defined: https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API

Regards.

**Comment by knzivid** [comment]
Thanks

**Comment by uilianries** [comment]
@knzivid some clarification:

- You can play with the protocol, because it's stable enough;
- For future evolution, Conan will use endpoints to separate the API version, so it may not break users;
