### ISSUE TITLE
[question] contradiction between x86 vs i386/i686 

### ISSUE THREAD

**Issue by hoxnox** [conan-io/conan#11547]
settings.xml suppose to have only x86, but gcc use a different term for that arch - i368 or i686
I have x86_64 machine and i386 compiler with the following conan profile:

```
processor=i386
target_host=$processor-pc-linux-musl
toolchain=/opt/$processor-pc-linux-musl
cc_compiler=gcc
cxx_compiler=g++
...
[settings]
arch_build=x86_64
arch=x86
...
[env]
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain/$processor-pc-linux-musl/sysroot
CONAN_CMAKE_SYSTEM_NAME=Linux
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
STRIP=$target_host-strip
```

There are packages, that relies on `host` (for example m4) and expect i?86, but conan gives them `x86` and everything goes wrong.

On the other hand, I can set arch=i386, but conan is unhappy, because there is no such value in `settings.yml`. Even if I add it manually, I'll have problems with packages, that rely on x86 in their conanfile.py (tbb for example).

You can reproduce this. Make conanfile with both m4 and tbb as a dependencies and try to build it in the following docker container `hoxnox/builder:i386`. You'll have to play with arch=x86 and arch=i386 every time. 

How should I solve this problem?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The Conan architecture being ``x86`` is correct, and then, depending on the platform, the build system, the compiler, etc, it might be necessary to map that architecture to the specific expected values as ``i386``. That is the responsibility of the build system integrations.

The recipes from ConanCenter haven't upgraded yet to the modern build system integrations that will remain in Conan 2.0, so it would be better to reproduce this with a simple recipe. Now with ``conan new hello/0.1 --template=cmake_lib|autotools_lib|msbuild_lib|....`` it is easy to get a modern integration working recipe. Please try that, and if it is working, then we should transfer this issue to ``conan-center-index`` repo, for that specific package, so they can fix it there.

**Comment by hoxnox** [comment]
Ok, got it. The right way is to have arch=x86 and fix the recipe. Thanks.
