### ISSUE TITLE
[feature] Add `IMPORTED_LOCATION` property for IMPORTED targets created by `CMakeDeps` generator.

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#11540]
This issue is related to: https://github.com/conan-io/conan-center-index/issues/11403

According to the Documentation of CMake, there is a generator expression called [`TARGET_RUNTIME_DLLS`](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_RUNTIME_DLLS), which is introduced in CMake version **3.21**. The value of `$<TARGET_RUNTIME_DLLS:tgt>` is determined by the target property [`IMPORTED_LOCATION`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LOCATION.html) of `tgt`.

With the help of this `TARGET_RUNTIME_DLLS`, we can easily copy those **RUNTIME** dependencies to the output directory with `add_custom_command()` on **Windows** platform. For example:

```cmake
find_package(fmt CONFIG REQUIRED)
find_package(OpenCV CONFIG REQUIRED)
find_package(Qt6 CONFIG REQUIRED)

add_executable(exe main.cpp)

target_link_libraries(exe 
  PRIVATE 
    fmt::fmt
    opencv_core
    opencv_imgproc
    Qt6::Core
    Qt6::Gui)

add_custom_command(TARGET exe POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy 
          $<TARGET_RUNTIME_DLLS:exe> 
          $<TARGET_FILE_DIR:exe>
  COMMAND_EXPAND_LISTS)
```

However, it seems that it only provide 5 types of target properties for now:

- `INTERFACE_LINK_LIBRARIES`
- `INTERFACE_LINK_OPTIONS`
- `INTERFACE_INCLUDE_DIRECTORIES`
- `INTERFACE_COMPILE_DEFINITIONS`
- `INTERFAEC_COMPILE_OPTIONS`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/176092538-9e124d78-8d99-4cb3-93f8-66040e9c71c6.png)

**Comment by hwhsu1231** [comment]
Besides, if it is possible, I hope Conan can also provide other target properties related to `IMPORTED_` prefix:

- [`IMPORTED_LOCATION_<CONFIG>`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LOCATION_CONFIG.html)
- [`IMPORTED_IMPLIB`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_IMPLIB.html#imported-implib)
- [`IMPORTED_IMPLIB_<CONFIG>`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_IMPLIB_CONFIG.html)
- [`IMPORTED_LIBNAME`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LIBNAME.html)
- [`IMPORTED_LIBNAME_<CONFIG>`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LIBNAME_CONFIG.html)
- [`IMPORTED_SONAME`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_SONAME.html)
- [`IMPORTED_SONAME_<CONFIG>`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_SONAME_CONFIG.html)

**Comment by memsharded** [comment]
This has been already solved, at least IMPORTED_LOCATION and IMPORTED_IMPLIB, in https://github.com/conan-io/conan/pull/11111 for Conan 2.0 (and released in beta.1), so I am considering this ticket solved.

Feedback for 2.0-beta is very welcome.

Also, for advanced deployment cases, Conan 2.0 provides a great new feature, the ``deployers`` that will certainly help with those cases of "collect all the runtime files" from dependencies in a very powerful, flexible and maintainable way, I'd strongly recommend to give it a try once documented in 2.0.

Thanks!

**Comment by hwhsu1231** [comment]
@memsharded Execuse me.

Does Conan 2.0 support [`IMPORTED_LOCATION_<CONFIG>`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LOCATION_CONFIG.html) target property for IMPORTED library targets as well?

Because recently I found that `IMPORTED_LOCATION_<CONFIG>` is more important and useful than `IMPORTED_LOCATION` when it comes to **copying RUNTIME dependencies on Windows**. See more details on this [topic](https://discourse.cmake.org/t/what-is-the-recommended-correct-value-of-imported-location-for-imported-library-targets/6081/5?u=hwhsu1231) in CMake Discourse.

**Comment by rainman110** [comment]
@memsharded Is there any chance to get the `IMPORTED_LOCATION` property also from the conan 1.5 series by the CMakeDeps  generator?

I'd like to install some the the dependency dlls, but I cannot get the location of the library, since it is defined as an `INTERFACE` target.
