### ISSUE TITLE
[feature] .conanrc to specify repo-local workflow

### ISSUE THREAD

**Issue by blackliner** [conan-io/conan#11542]
Coming from a discussion with @memsharded:

Conan currently does not support **implicit** configuration of the `conan` cache (templates, hooks, packages etc), but only explicitly by setting a env variable [CONAN_USER_HOME](https://docs.conan.io/en/latest/reference/env_vars.html?highlight=conan_user_home#conan-user-home).

This request is about introducing a `.conanrc` called file that will be placed at the root of a repository, and contains useful metainformation, like `local_user_home=True` etc. Any `conan` CLI call will end up traversing the `PWD` until it finds such an `.conanrc` file and use it.

This will allow us to make the repository the real source of truth, instead of relying on a central cache. This can be an issue for example if you are working on different projects that use different, conflicting hooks.

This idea is heavily inspired by bazel's [.bazelrc](https://bazel.build/docs/bazelrc), and can be expanded to other use-cases:
- define custom path to `.conan/config`, so it utilizes the repos filesystem instead of creating a new one, making `conan config install` calls obsolete. This would cover pofiles, hooks, remotes, templates...

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Lets do it in 2 steps:

- Recover the ``storage.path`` configuration in the home global.conf
- Define a .conanrc that contains env-var CONAN_HOME to define the location of the home (can be relative path to the .conanrc file, to define a local home per project)

**Comment by memsharded** [comment]
Both features, the necessary storage-path configuration and the ``.conanrc`` file to define the home location, have been merged, and will be available in beta.2
