### ISSUE TITLE
[question] Mixing shared and static linking

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#11551]
Hello,

I have a project that depends on qt and openssl.
Qt links openssl statically and I need to link openssl dynamically. 

I tried defining this in my project recipe.

```
    default_options = {
        "shared": True,
        "openssl:shared": True
```
and also tried:

```
    def config_options(self):
        self.options["openssl"].shared = True
```

But I always end up with with a `Missing binary` error as conan was looking for qt that was compiled with  `"openssl:shared": True`

Is there a way to mix static and shared linking of the same dependency in the same project ?

**Comment by memsharded** [comment]
You cannot link an artifact with two different variants of the same library.
If Qt links openssl statically, and Qt is a shared library, and openssl is a pure implementation detail, it could be kind of embedded, making it private. But in general it is a bad idea, you don't want your application to believe that it is using the modern openssl/2.0 version that your executable is using as s shared library, while in reality, Qt might be using an ancient openssl/1.0 that is embedded in the Qt shared libraries as an implementation detail.

The fact that there is a ``Missing binary`` shouldn't be an issue, is it? It means that ConanCenter didn't built it, but Qt needs to be built to link openssl as a shared library (the current default of ConanCenter regarding this is not ideal, Conan 2.0 build will build by default shared libraries linking other shared libraries, not static).

**Comment by memsharded** [comment]
Closing this as responded back then, and staled.
