### ISSUE TITLE
[question] Shorter Lock File?

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#11550]
I'm currently running into an issue when using lock files in the Jenkins environment related to character length limitations in the Linux environment. I am wondering if there is a way to generate shorter/more concise lock files.

Use case:

1. Developer pushes source code (of a Conan package) in a repo that contains many Conan packages (conanfile.py and source code are co-located)
2. Jenkins multi-branch pipeline (MBP) runs for the repo; it uses a lock file and the build order feature to determine what needs to be built (we are not traditionally versioning; the Git branch is used in the package reference and is used like a version)
3. Child jobs are kicked off with as much parallelization as possible; the lock file is passed from the parent repo MBP to the child job that builds the actual Conan package

The problem is with the passing of the lock file from the parent MBP to the child MBP that builds the Conan package. Since Jenkins does not support file parameters, I pass the lock file as a text parameter. The child job then creates a physical file using the text. The cause of our issue is that Jenkins puts all parameters in the environment; our lock file has become so large that we are now surpassing the allowed character length for a Linux environment variable.

Is there a way to create a less verbose lock file? Doesn't the child only need the various hashes to identify the specific package?

Note: I tried some Jenkins community-suggested workarounds to clear out the environment variable for the parameter but the workaround does not work when loading a library from within the pipeline.

Thanks!

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @radonish 

Some things that you can try:

- Use only the ``base`` lockfiles, they contain less information, but maybe could be enough? You might need to create the full lockfile on the child MBP to apply it, but might work
- Upload the lockfiles to an Artifactory generic repo (or other similar file solution if not using Artifactory), based on a path like the CI job number. This is relatively easy to do, and it is kind of nice, having a repo there with files that act as a "DB of the CI" process beyond the CI itself.
- I would investigate a bit further, if Jenkins doesnt' support it natively, I'd say there must exist some plugin that allows passing files around in Jenkins.

Lockfiles in Conan 2.0 will also be much much simpler, but even though, passing things around in environment or arguments doesn't sound like a general good approach for CI, I would keep trying on defining a mechanism that allows sharing files among your CI pipelines.

**Comment by radonish** [comment]
@memsharded, thank you for your suggestions. I will look at potentially using a base lockfile to start with. I was planning on looking at using Artifactory longer-term.

**Comment by memsharded** [comment]
Ok. Also, you can try a git repo to store things in branches (one branch per CI job), as storage of things for CI. It is super simple setup and pretty solid and effective.

I think we can close this question as responded, but feel free to re-open or create a new ticket if necessary, thanks!
