### ISSUE TITLE
[bug] self.copy(src=*, dst=*, symlinks=True) wouldn't work when src directory is a symlink

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#11567]
### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 18.04
  * Compiler+version: gcc 7
  * Conan version: 1.49.0
  * Python version: 3.6

**Comment by czoido** [comment]
Hi @Tumb1eweed, 

Could you please provide more information on how to reproduce the case? The code in the title does not seem correct, as the function is of the form showed in the docs: https://docs.conan.io/en/latest/reference/conanfile/methods.html#package

```
self.copy(pattern, dst="", src="", keep_path=True, symlinks=None, excludes=None, ignore_case=True)
```
Are you using the tool correctly?

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed,
> 
> Could you please provide more information on how to reproduce the case? The code in the title does not seem correct, as the function is of the form showed in the docs: https://docs.conan.io/en/latest/reference/conanfile/methods.html#package
> 
> ```
> self.copy(pattern, dst="", src="", keep_path=True, symlinks=None, excludes=None, ignore_case=True)
> ```
> 
> Are you using the tool correctly?

the command is:
self.copy("*", dst="lib64", src=self.source_folder + "/cudatoolkit/libcurand/lib64/", symlinks=True)
I try to copy from cuda

**Comment by czoido** [comment]
Hi @Tumb1eweed,
If I'm understanding correctly, would a `conan create` on this recipe reproduce your case? For me at least this is working. Maybe I'm missing something?

```python
from conans import ConanFile, tools
class testSymLinkFolderConan(ConanFile):
    name = "somepackage"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"

    def build(self):
        self.run("mkdir real")
        self.run("ln -s real symlink_folder")
        tools.save("real/somefile.txt", "Hello")

    def package(self):
        self.copy("*", dst="lib64", src=self.source_folder + "/symlink_folder/", symlinks=True)
        assert "Hello" in tools.load(f"{self.package_folder}/lib64/somefile.txt")
```

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed, If I'm understanding correctly, would a `conan create` on this recipe reproduce your case? For me at least this is working. Maybe I'm missing something?
> 
> ```python
> from conans import ConanFile, tools
> class testSymLinkFolderConan(ConanFile):
>     name = "somepackage"
>     version = "1.0"
>     settings = "os", "compiler", "build_type", "arch"
> 
>     def build(self):
>         self.run("mkdir real")
>         self.run("ln -s real symlink_folder")
>         tools.save("real/somefile.txt", "Hello")
> 
>     def package(self):
>         self.copy("*", dst="lib64", src=self.source_folder + "/symlink_folder/", symlinks=True)
>         assert "Hello" in tools.load(f"{self.package_folder}/lib64/somefile.txt")
> ```

yes, something like that, or you can download cudatoolkit to see its directory "libcurand/lib64"

**Comment by sbudenkov** [comment]
I see the same problem with cudnn and tensorrt.

**Comment by memsharded** [comment]
Hi all,

``self.copy`` has been deprecated and replaced by the ``copy()`` free function ``from conan.tools.files import copy`` some time ago in 1.X, and completely removed in 2.0.

I am closing this issue as outdated, if there are any issues with the new ``copy()`` please submit a new ticket (preferably for Conan 2.0, but 1.X also possible). Note that the ``copy()`` might do less things, specially less manipulation of symlinks, and there are other new, explicit methods in ``from conan.tools.files.symlinks``. Thanks!
