### ISSUE TITLE
[bug] copy files are not preserving symbolic links

### ISSUE THREAD

**Issue by JhaSujata** [conan-io/conan#11566]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04LTS (wsl1)
  * Compiler+version: gcc + 10
  * Conan version: 1.49.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
conan new pgsql/$version@qi/common --bare

###conan_settings="-s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=10 -s compiler.libcxx=libstdc++"

conan export-pkg . pgsql/$version@qi/common $conan_settings --force
conan upload pgsql/$version@qi/common -r $repo --all

conan install <conanfile name> -s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=10 -s compiler.libcxx=libstdc++

**Comment by czoido** [comment]
Hi @JhaSujata,
You can pass the parameter `symlinks` to `conans.tools.copy` to activate symlink copying. Please check the docs: https://docs.conan.io/en/latest/reference/conanfile/methods.html#package

Please, be aware that for Conan 2.0 compatible recipes you must use the [conan.tools.files.copy()](https://docs.conan.io/en/latest/reference/conanfile/tools/files/basic.html#conan-tools-files-copy) (note the namespace **conan**, not **conans**). Please read the note about symlinks handling in 2.0 and 1.X compatible recipes and in the [migration guide](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#symlinks):

> Conan won’t alter any symlink while exporting or packaging files. If any manipulation to the symlinks is required, the package [conan.tools.files.symlinks](https://docs.conan.io/en/latest/reference/conanfile/tools/files/symlinks.html#conan-tools-files-symlinks) contains some tools to help with that.

**Comment by JhaSujata** [comment]
Hi @czoido ,

I am providing the parameters like below

`
from conans import ConanFile, tools

class PgsqlConan(ConanFile):
    name = "pgsql"
    version = "12.4"
    settings = "os", "compiler", "build_type", "arch"
    description = "<Description of Pgsql here>"
    url = "None"
    license = "None"
    author = "None"
    topics = None`
   ` 
    def copySymlinks(self):
    tools.copy()

    def package(self):
        #self.copy("*")
        self.copy("libpq.a",dst="bin",src="bin/pgsql/linux")
        self.copy("libpgport.a",dst="bin",src="bin/pgsql/linux")
        self.copy("libpgcommon.a",dst="bin",src="bin/pgsql/linux")
        self.copy("libpq.so.5.12",dst="bin",src="bin/pgsql/linux",symlinks=True)
        self.copy("libpq.so.5",dst="bin",src="bin/pgsql/linux",symlinks=True)
        self.copy("libpq.so",dst="bin",src="bin/pgsql/linux")
        self.copy("*.h", dst="include", src="include")
 

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)`
        
        
but still , it is copying the full size for symbolic links as well.

**Comment by czoido** [comment]
Hi @JhaSujata,
Is the problem is that the symlinks are absolute? In that case you may want to use the [new copy tool](https://docs.conan.io/en/latest/reference/conanfile/tools/files/basic.html#conan-tools-files-copy) and the [absolute_to_relative_symlik()](https://docs.conan.io/en/latest/reference/conanfile/tools/files/symlinks.html#conan-tools-files-symlinks-absolute-to-relative-symlinks)
If that's not the case, could you please explained the problem with more details?
Thanks a lot.

**Comment by czoido** [comment]
Hi @JhaSujata ,
Can it be that you are missing the `symlinks=True` for `libpq.so`?

**Comment by JhaSujata** [comment]
Hi @czoido ,
Thanks for the follow up.

I tried with both the options
1. Providing absolute path for symlinks files
2. Setting symlinks=True for libpq.so

`def package(self):
        #self.copy("*")
        self.copy("libpq.a",dst="bin",src="lib/linux")
        self.copy("libpgport.a",dst="bin",src="lib/linux")
        self.copy("libpgcommon.a",dst="bin",src="lib/linux")
        self.copy("libpq.so.5.12",dst="bin",src="/mnt/d/GitHub/core-libraries/core-libraries/3rd_party/pgsql/lib/linux",symlinks=True)
        self.copy("libpq.so.5",dst="bin",src="/mnt/d/GitHub/core-libraries/core-libraries/3rd_party/pgsql/lib/linux",symlinks=True)
        self.copy("libpq.so",dst="bin",src="/mnt/d/GitHub/core-libraries/core-libraries/3rd_party/pgsql/lib/linux",symlinks=True)
        self.copy("*.h", dst="include", src="include")
 
`

But still, none of them worked. However, I noticed that the once the package is created, it still preserves the symlinks but something happens while uploading because when I install again, I find all the symlink files are nothing but copy of original file.
Below is the list of commands I am using for recipe creation, packaging and uploading :
`$conan new pgsql/$version@qi/common --bare
$conan export-pkg . pgsql/$version@qi/common $conan_settings --force
$conan upload pgsql/$version@qi/common -r $repo --all`

**Comment by JhaSujata** [comment]
Hi @czoido ,

I was invoking all the conan commands via a script. So, the conanfile was not getting updated with the symlinks parameter, hence,  symlinks was not working.

Thanks you for the support.
