### ISSUE TITLE
[question] Headless Conan windows installer

### ISSUE THREAD

**Issue by kingudk** [conan-io/conan#11568]
Hi

In our build environment we are starting to use conan for handling dependencies on C/C++ libraries and soon also for internal publication. We need to be able to build both for Linux and Windows environments and our build tools are within container images (for both platforms).
Getting a Linux image ready (with gcc, cmake and conan) was not much of a hassle. On the windows side I have an image with both msbuild and cmake, so I'm just missing conan there. There is an exe-based installer available but it seem to insist on a GUI. Giving it "\q" or "\quiet" does not make it go away. 
My question is therefore: 
1) Is there a way to run the exe based windows installer without the GUI (so I can get it installed by command line in the windows docker image)
2) If 1) is not possible, is the only way around then to install python3 and pip in the windows image and install conan via pip?

Thanks in advance. 
Regards 
Kim

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @kingudk,
The Conan installer is created with Innosetup so you can try the arguments on its documentation and that should work to remove all message boxes and warnings during the installation of Conan (check `/SP-`, `/SILENT`, `/VERYSILENT`, `/SUPPRESSMSGBOXES`...). Check the [docs of Inno Setup](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline) for more details.
Nevertheless, the [recommended way of installing Conan](https://docs.conan.io/en/latest/installation.html#install-with-pip-recommended) is using pip and installing in a virtual environment. In fact, we are not generating windows installers for Conan 2.0 yet.
Thanks a lot for the question, hope that this helps!

**Comment by kingudk** [comment]
Hi @czoido 
Thanks for getting back so quickly!
It did the trick `conan-win-64.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES`. 
I guess I'll go with that for now, and see how it should be revised for Conan 2.0. 
2.0 will bring about other things that will be challenging, especially if cmake-conan is discontinued, but that is another discussion. Something that I might bring up after the summer holidays.

**Comment by memsharded** [comment]
I would like to bring another possibility for other users with similar needs, to install Conan without pip/python: the ``pyinstaller.py`` file in the root of the repo is able to create the Conan independent executable. It is likely that you can take it and put it in the docker image, without needing to use the installer.

I think we can close this ticket now as resolved, thanks!
