### ISSUE TITLE
[bug] CMakeDeps+CMakeToolchain does not respect build_modules

### ISSUE THREAD

**Issue by Ahajha** [conan-io/conan#11561]
Editing `self.cpp_info.build_modules` for the CMakeDeps and CMakeToolchain generators does not seem to work, I'm not sure if this is a bug or if I need to be using it differently. Also, if this is a bug, I would like to know if there is a workaround for now.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.04
  * Compiler+version: GCC 10.3
  * Conan version: 1.50
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)
I have 4 files:
```cmake
# test.cmake
function(TestMessage)
message(NOTICE "Hello from test.cmake")
endfunction()
```
```python3
# conanfile.py
from conan import ConanFile

class TestConan(ConanFile):
    name = "test"    
    exports_sources = "test.cmake"
    
    def package(self):
        self.copy("test.cmake", src=".", dst=".")
    
    def package_info(self):
        self.cpp_info.build_modules["CMakeDeps"].append("test.cmake")
        self.cpp_info.build_modules["CMakeToolchain"].append("test.cmake")
        self.cpp_info.build_modules["cmake_find_package"].append("test.cmake")
        self.cpp_info.build_modules["cmake_find_package_multi"].append("test.cmake")
```
```cmake
# test_package/CMakeLists.txt
cmake_minimum_required(VERSION 3.15)
project(test_package)

find_package(test REQUIRED)
TestMessage()
```
```python3
# test_package/conanfile.py
from conans import ConanFile, CMake, tools
import os

class TestPackageConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    #generators = "CMakeDeps", "CMakeToolchain"
    generators = "cmake_find_package_multi"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def test(self):
        pass
```
I am running
```
conan create . 1.0.0@test/test -pr:b default
```
As is, this works, but swapping the generators in `test_package/conanfile.py` to CMakeDeps and CMakeToolchain fails. The `find_package` works, but it cannot find `TestMessage()`.

**Comment by lasote** [comment]
Yes, the `build_modules` has been removed in Conan 2.0 and, in the new generators (CMakeDeps, CMakeToolchain...) you have to use `self.cpp_info.set_property("cmake_build_modules",  ["test.cmake"])`. 
I recommend reading the migration guide to be ready to have "Conan 2.0" compatible recipes, this section talks about these "cpp_info" changes: https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#new-properties-model

**Comment by Ahajha** [comment]
Thank you for the quick reply! I had seen the migration guide before, but I guess I missed that part. That change fixed it!
