### ISSUE TITLE
[bug] Errors for incompatible option values for dependencies only shown for specific requires order

### ISSUE THREAD

**Issue by foundry-markf** [conan-io/conan#11571]
I was investigating a Conan recipe setup that I expected to result in an error, because a dependency was being requested (directly and indirectly) with different option values. Instead, I saw no error, and the dependency was configured not how the top-level recipe asked for it, but from how the indirect dependency configured it.

The only difference is that the `self.requires` order is changed.

I was expecting that the order of requirements would not be significant, so can't explain this.

### Environment Details (include every applicable attribute)
  * Operating System+version: Observed on Mac (10.14) and Windows (10)
  * Compiler+version: Independent of compiler
  * Conan version: 1.48-1.50
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)
I've created a gist as a significantly cut down reproducible of what I saw today: https://gist.github.com/foundry-markf/c2b459405b8c3aab78645171cedf6ef4

Run `./build.sh`

### Logs (Executed commands with output) (Include/Attach if Applicable)
My log from Mac is included in the gist: https://gist.github.com/foundry-markf/c2b459405b8c3aab78645171cedf6ef4#file-mf_log-txt

Output from `conan search` to determine which configuration of the dependent library had been chosen in the unexpectedly succeeding case: https://gist.github.com/foundry-markf/c2b459405b8c3aab78645171cedf6ef4#file-mf_search_log-txt

**Comment by memsharded** [comment]
Hi @foundry-markf 

We have been investigating this, and trying different approaches:

- Indeed in Conan 1.X the conflict is order-dependent. The way and order the dependencies are evaluated affects the possible conflicts
- The problem still persisted in Conan 2.0, in different ways, and it was a bit more manageable, but still very confusing.
- We have tried a few ways to improve the potential options conflicts detection both in 1.X and 2.0, and we have concluded that it is not worth the fragility and complexity.

So we are going with the following approach for 2.0:
- Definitions of options for dependencies in conanfile.py recipes are a prioritized but not conflicting definition. The order of evaluation of the graph might produce different results in some situations.
- Thus, options never conflict, they will get different values based on the priorities:
   - Consumers always have higher priority than dependencies
   - Profile and command line definitions always have top priority. No matter what recipes say, if a profile define some values, they will be assigned, even if they are incompatible with values defined by recipes ``configure()`` or ``default_options``
   - In case of same level dependencies (diamonds), the first one to expend (the first one in ``requires``) will have precedence
- If there is some recipe that cannot work at all with some specific options of its dependencies, it should check it in their ``validate()`` method via ``self.dependencies`` and raise a ``ConanErrorConfiguration`` exception

This ticket is being closed by #11583 for Conan 2.0-beta.2. Please let us know if you have any further question

**Comment by foundry-markf** [comment]
Hi @memsharded , thanks for the response (sorry for my late reply, as have been away).

Appreciate that you looked into this and have some suggestions for 2.x. I hope having an order of precedence will be enough to squash this sort of case.

A few questions:
1. would it be fair to say that Conan 1.x will continue with the observed behaviour, and not expect to be changed?
2. are there some new public docs that can be referred to describing this gotcha in 1.x and 2.x behaviour (so I'm not linking my peers to this issue, and for other Conan users to be aware of)?

Thanks.
