### ISSUE TITLE
Support for apple-clang 8.1

### ISSUE THREAD

**Issue by sunxfancy** [conan-io/conan#1157]
There is a new version of clang in mac, please add supporting for it.

```
Invalid setting '8.1' is not a valid 'settings.compiler.version' value.
```

**Comment by memsharded** [comment]
Good, we will add it to the defaults settings.
Just in case, in the meantime you can add it to your settings.yml to keep working. Check: http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting

**Comment by sunxfancy** [comment]
Thanks for your reply, good solution.

**Comment by dimi309** [comment]
I upvote this issue 👍

**Comment by memsharded** [comment]
No need to upvote @dimi309 , it is already in the 0.22 milestone :) :) :)

**Comment by dimi309** [comment]
Sorry, just got a little excited :rofl:

**Comment by ilovezfs** [comment]
In the future it would be nice not to make compiler version checks fatal as it just leads to pointless failures downstream gets to chase.

**Comment by memsharded** [comment]
@ilovezfs the thing is that the input settings have to be validated against the predefined settings, otherwise each user will input non-standard settings and package hashes would never match. So the PR to homebrew failed because 8.1 is still not in the conan settings.yml file, we will add it for next release. 

So, in my opinion, the inconvenience of having this checks in place is very small compared with the chaos that would happen if inputs settings are not validated.

**Comment by ilovezfs** [comment]
Given how long Xcode 8.3 has been available in beta, that's not particularly convincing.

**Comment by memsharded** [comment]
We add new versions to settings.yml as soon as they are requested, and release as soon as possible. We can't monitor everything, is the community that requests such inclusions.

**Comment by ilovezfs** [comment]
> We can't monitor everything

This is why you should not hard code foreseeable failures to speculatively fix bugs that don't even exist yet. If every package in Homebrew required upstream to do a version bump whenever a new Xcode came out, we'd have chaos.

**Comment by lasote** [comment]
> This is why you should not hard code foreseeable failures to speculatively fix bugs that don't even exist yet

@ilovezfs are you a conan user? Do you think a setting mismatch is speculative? or just guessing? Just asking...

**Comment by dimi309** [comment]
How about a strict control up to the latest version and then treating anything above that the same way as the latest one by default, allowing any increment?

The thing is, in some cases like Visual Studio (2017 is also not supported by the way, as far as I've been able to tell) it is easy to install the old toolchain in parallel and wait. In cases like clang, which gets upgraded together with Xcode, the solution is less obvious and the issue can block work, which can be a problem if the developer has grown to count on conan.io.

I think there is an opportunity for conan to become more popular than the "hand made" projects constructed with automake, Xcode or Visual Studio. Its advantage is the package management, so removing the disadvantage of blocked builds can help a lot in that direction, by increasing trust.

**Comment by dimi309** [comment]
Another idea might be being more permissive with versions locally but maintaining a strict control on conan.io, to avoid problems on the published packages. Maybe even having a parameter allowing users to control the strict/not strict aspect when they set up conan on their own infrastructure. Ok I'm stopping now. I'm getting ahead of myself 🐤

**Comment by dimi309** [comment]
In any case these are just suggestions. I mean no offense. You guys are doing great work and you're making it available to us for free. (And, personally, I'm just working on some home-made projects for kicks, so I am not blocked or stressed or anything 😆 )

**Comment by memsharded** [comment]
This would also be a chaos. As we cannot know in advance the future versions, there is no way to provide both validation and hash-uniqueness. It is a fact, it is not possible to have both things simultaneously. You either balance towards having wrong hashes for package binaries or towards enforcing validation. We have clearly balanced towards validation, as we definitely don't want to have a mess on package binary hashes, that would render conan unusable.
So having from time to time to add latest versions to settings.yml is just a small inconvenience, and we do it as soon as it is requested. Definitely it doesn't block our users.

**Comment by dimi309** [comment]
I understand. That works too and I can see the benefits. I was just
brainstorming. I guess we have to keep in mind that with Conan we have a
detailed registry of packages. Not just local builds where anything goes
since you can just erase everything and start over.

**Comment by lasote** [comment]
It has been released in conan 0.22.0. Thanks!

**Comment by ilovezfs** [comment]
Thanks: https://github.com/Homebrew/homebrew-core/pull/12587.

**Comment by dimi309** [comment]
Thanks!
