### ISSUE TITLE
[question] Conan 2.0 Custom Generators

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#11589]
I have a few custom generators that help support pre-conan setups, defining extra environment variables and such.  I am attempting to upgrade these to conan 2.0, but it appears that custom generators are not supported in conan 2.0.  Looking at `conans/client/loader.py`, it requires all custom generators to be a subclass of `conans.model.conan_file.Generator`  but the 2.0 generators (like VirtualRunEnv) don't use that base class.

Presently, if a user wants to use this custom generator, then they run a command such as
```
conan install package/version@ -g my_generator
```
I asked on the slack page and was told that custom generators are planned to go away in conan 2.0.  Is there a way to produce the above behavior in conan 2.0.  I know that I could include a generator in the conanfile, but it is only needed in certain circumstances and its use is orthogonal to the recipe.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jsallay 

Custom generators had some flaws in the 1.X approach, like for example, different versions of the same generator inside a Conan package overwriting each other without any control or warning. 
Conan 2.0 has taken a more explicit approach:

- The code is still shared via a Conan package, that can be ``conan export``
- That package is required via a ``python_requires``
- The code is explicitly called in the ``generate()`` method
- Generators must work on the ``self.dependencies`` attribute, as others like ``deps_cpp_info`` have been removed

For things that are to be used in consuming only and command line, there is a new concept in Conan 2.0, deployers:

- Deployers are python scripts that live in the Conan cache
- They can be shared and installed with ``conan config install``
- They can be called with ``conan install ... --deploy=mydeployer``
- They operate over ``self.dependencies`` too. 
- They can implement copy (old ``imports`` and ``deploy`` operations), but also change the final package folder, so generator like CMakeDeps point to the copied user folder and not the Conan cache.

**Comment by jsallay** [comment]
Deployers sound like what I want.  I think it makes a lot of sense to break it out this way.  Is there any documentation on the deployers?  I can't find any.

**Comment by memsharded** [comment]
No, not yet, we are working on the docs, but not there yet. Your best bet would be to have a look to the tests: 

- https://github.com/conan-io/conan/blob/develop2/conans/test/functional/command/test_install_deploy.py

**Comment by samuel-emrys** [comment]
@memsharded do you have a similar link to some examples of how to create custom generators (not deployers)? Will this approach work now?

**Comment by memsharded** [comment]
There is no explicit examples, but there exist docs for ``python_requires`` in https://docs.conan.io/en/latest/extending/python_requires.html.

The approach to use ``python_requires`` to implement a generator is basically (code not tested, just the idea):

- Create a generator like class inside a ``python_require``, something like:
   ```python
   from conan import ConanFile
   class MyGenerator:
          def __init__(self, conanfile):
                  self._conanfile = conanfile
          def generate(self):
                  for dep in self._conanfile.dependencies....
                         ...
                  # save files to be used in the build
   class MyTool(ConanFile):
          name = "tool"
          version = "0.1"
   ```
- Reuse it like:
   ```python
   from conan import ConanFile
   class Pkg(ConanFile):
          python_requires = "tool/0.1"
          def generate(self):
                generator = self.python_requires["tool"].module.MyGenerator(self)
                generator.generate()
    ```

**Comment by samuel-emrys** [comment]
> There is no explicit examples, but there exist docs for ``python_requires`` in https://docs.conan.io/en/latest/extending/python_requires.html.
> 
> The approach to use ``python_requires`` to implement a generator is basically (code not tested, just the idea):
> 
> - Create a generator like class inside a ``python_require``, something like:
>    ```python
>    from conan import ConanFile
>    class MyGenerator:
>           def __init__(self, conanfile):
>                   self._conanfile = conanfile
>           def generate(self):
>                   for dep in self._conanfile.dependencies....
>                          ...
>                   # save files to be used in the build
>    class MyTool(ConanFile):
>           name = "tool"
>           version = "0.1"
>    ```
> - Reuse it like:
>    ```python
>    from conan import ConanFile
>    class Pkg(ConanFile):
>           python_requires = "tool/0.1"
>           def generate(self):
>                 generator = self.python_requires["tool"].module.MyGenerator(self)
>                 generator.generate()
>     ```

This question might be stretching the scope of this ticket, but is there a way to consume a python_requires package from a generator as defined above?

I've got a python class that I'd like to share with consumers, but the generator also needs to be aware of it, and I'm struggling to work out how I can make the same definition available to both - it seems that python_requires can only be consumed from a derived class of ConanFile. Any ideas would be appreciated.

**Comment by samuel-emrys** [comment]
For completeness, what would be nice is a way to share python_requires with generators, something _like_ this (though obviously not this, because generators can't see python_requires):
```python
class MyCommonClass:
    def func(self):
        return "123"
        
class MyCommonClassPkg(ConanFile):
       name = "commonpkg"
       version = "0.1"
```

```python
from conan import ConanFile
class MyGenerator:
       python_requires = "commonpkg/0.1"
       def __init__(self, conanfile):
               self._conanfile = conanfile
       def generate(self):
               obj = self.python_requires["commonpkg"].module.MyCommonClass(self)
               obj.f()
               for dep in self._conanfile.dependencies....
                      ...
               # save files to be used in the build
class MyTool(ConanFile):
       name = "tool"
       version = "0.1"
```

And both could then be reused:

```python
from conan import ConanFile
class Pkg(ConanFile):
       python_requires = "tool/0.1", "commonpkg/0.1"
       def generate(self):
             obj = self.python_requires["commonpkg"].module.MyCommonClass(self)
             obj.f()
             generator = self.python_requires["tool"].module.MyGenerator(self)
             generator.generate()
```

This would be nice to be able to have semantic separation between common functionality, and build system specific functionality as is the case with generators. Each generator will target a specific build system, but what they're generating over is likely to be common amongst them, which is particularly useful when what they're iterative over _isn't_ the dependencies available in `self.dependencies`

The quick way around this seems to be just to include the functional dependency with the generators, all in one python_requires:
```python
from conan import ConanFile

class MyCommonClass:
    def func(self):
        return "123"

class MyGenerator:
       python_requires = "commonpkg/0.1"
       def __init__(self, conanfile):
               self._conanfile = conanfile
       def generate(self):
               obj = self.python_requires["commonpkg"].module.MyCommonClass(self)
               obj.f()
               for dep in self._conanfile.dependencies....
                      ...
               # save files to be used in the build
class MyTool(ConanFile):
       name = "tool"
       version = "0.1"
```

Which can then be used as follows:
```python
from conan import ConanFile
class Pkg(ConanFile):
       python_requires = "tool/0.1"
       def generate(self):
             obj = self.python_requires["tool"].module.MyCommonClass(self)
             obj.f()
             generator = self.python_requires["tool"].module.MyGenerator(self)
             generator.generate()
```
This isn't quite as nice, because, whilst I'm presenting this abstractly, "tool" might be an apt descriptor for `MyCommonClass`, but not a good one for `MyGenerator`, because `MyGenerator` is likely to be more specific, i.e. `MyCMakeGenerator` or `MyMesonGenerator`. There's no easy way to tell which generators become available to you by having `python_includes = "tool/0.1"` - it would be much clearer if you could make a statement like `python_includes = "tool/0.1", "CMakeTool/0.1", "MesonTool/0.1"`, or something.

I feel like I've rambled a bit here, so if I've been unclear let me know. The TLDR is that it would be good to have a way of sharing python code with generators, not just classes derived from `ConanFile`.

**Comment by memsharded** [comment]
I have added a test in https://github.com/conan-io/conan/pull/11605 to illustrate how this can be done. Basically, use Python flexibility:

```python
from conan import ConanFile

        class MyGenerator:
            common = None
            def __init__(self, conanfile):
                self.conanfile = conanfile
            def generate(self):
                self.conanfile.output.info("VALUE TOOL: {}!!!".format(MyGenerator.common.mycommon()))

        class Tool(ConanFile):
            name = "tool"
            version = "0.1"
            python_requires = "common/0.1"
            def init(self):
                MyGenerator.common = self.python_requires["common"].module
```

We can put the ``python_require`` in the way it belongs, in the ``Tool(ConanFile)``, but make it available to different parts of the classes and functions to be reused.
