### ISSUE TITLE
[question] How to handle multi config package with dependencies  

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#11584]
Hello,

I have a project that depends on both `qt` and `openssl`

* qt package was created with multiconfiguration=True, this means one qt package that contains both debug and release binaries. in this case qt package does not depend on build_type. (2 configs -> 1 package)
* zlib in the other hand is 1 config -> 1 package, this means we have two different packages one for debug and another for release.
* For my project, I'm trying to create two different packages, one for release and one for debug.
 
When I tried to build my project in release mode, everything works as expected. (I'm assuming here that qt package was created using the default zlib config (release)).
However, when I tried to build in debug mode, I got an error `ERROR: Missing prebuilt package for 'qt`, This is probably because conan was looking for qt package that was built with debug zlib. 

* Is my reasoning correct ? 
* How to make a build_type independent package depends on dependencies with multiple build types. 
* Is there any solution for this ? 

Thanks

**Comment by memsharded** [comment]
Hi @boussaffawalid 

Yes, I think so, this is the current ``package_id()`` in the qt recipe:

```python
def package_id(self):
        del self.info.options.cross_compile
        del self.info.options.sysroot
        if self.options.multiconfiguration and self._is_msvc:
            if self.settings.compiler == "Visual Studio":
                if "MD" in self.settings.compiler.runtime:
                    self.info.settings.compiler.runtime = "MD/MDd"
                else:
                    self.info.settings.compiler.runtime = "MT/MTd"
            else:
                self.info.settings.compiler.runtime_type = "Release/Debug"
```
Which means, that the recipe is not discarding the ``self.info.settings.build_type``, and it seems it should if is multi-configuration.


In any case, I don't think that multi-config packages are a good idea. We did remove support for multi-config packages in Conan 2.0, I think that the qt package with that option activated might have some rough edges and unexpected behavior, specially when consumed with modern integrations like CMakeDeps that dropped support for multi-config packages already.

**Comment by memsharded** [comment]
Closing as responded and staled.
