### ISSUE TITLE
[question] Linux VirtualEnv ps1 files

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#11588]
On Linux systems, if I run `conan install ... -g virtualrunenv` it produces `.sh` and `.ps1` scripts.
```
ls
activate_run.ps1  activate_run.sh  deactivate_run.ps1  deactivate_run.sh  environment_run.ps1.env  environment_run.sh.env
```
It is my understanding that the ps1 files are only useful on windows.  Why are they produced on Linux systems?  Looking at `https://github.com/conan-io/conan/blob/develop/conans/client/generators/virtualenv.py` I see that `.bat` scripts are only produced in windows environments.  Should the ps1 files function in the same way or do they provide some value on Linux?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jsallay 

You might want to check the new ``VirtualBuildEnv`` and ``VirtualRunEnv``, they are available in Conan 1.X, they have replaced the others completely in 2.0 (they ``virtualrunenv`` has been removed in 2.0, for example). These new generators only generate the files that you need. Check: https://docs.conan.io/en/latest/reference/conanfile/tools.html

**Comment by jsallay** [comment]
Perfect.  That's exactly what I wanted.  Thank you.
