### ISSUE TITLE
[question] Can I invoke "conan upload" using infos from recipe of current directory

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan#11582]
Hello,

I have a continuous integration composed of 3 instructions:

```
export PACKAGE_VERSION=`conan inspect . --raw version`
conan create . $USER/$CHANNEL --profile .conan/profiles/gcc7
conan upload myPackage/$PACKAGE_VERSION@$USER/$CHANNEL --confirm --parallel --all -r $ARTIFACTORY_REPOSITORY
```

Is it possible to simplify that by letting conan upload deduce package name and version from recipe of current directory?

If no, make it sense to ask that through a feature request?

Regards.

**Comment by jcar87** [comment]
Hi @EstebanDugueperoux2, thanks for raising this as an issue.

The `conan upload` command operates on references that exist in the local cache, that is - they have already been exported to the cache.

Whereas `conan create .` operates on a recipe in the current directory - it will implicitly export it to the Conan cache.

Letting `conan upload` deduce from the local directory would give way to potential mismatches between the version of the recipe in the local directory, vs the recipe as it exists in the cache. 

However, in Conan 2.0, currently in beta - you have the option to get json formatted output from the CLI commands (see "What's new" [here](https://docs.conan.io/en/2.0/whatsnew.html#new-cli)). This would allow you to run `conan create` and capture the specific reference of the recipe, and package IDs that have been created, so that you have the most accurate information to subsequently call `conan upload`.

**Comment by EstebanDugueperoux2** [comment]
Hi @jcar87,

Thanks for your answer.
Taking https://github.com/EstebanDugueperoux2/opencascade_test example, I try to get version as you indicated with conan 2.0.0-beta1, I execute "conan create . --format json" but get following stacktrace:

```
-------- Computing dependency graph ----------
Graph root
    opencascade_test/0.0.1 (test package): /home/estebandugueperoux/git/opencascade_test/test_package/conanfile.py
Requirements
    opencascade_test/0.0.1#f1273b186faf9103113d6386de704487 - Cache
Resolved version ranges
    gtest/[~1.11.0]: gtest/1.11.0
Graph error
    Package 'gtest/1.11.0' not resolved: gtest/1.11.0: Cannot load recipe.
Error loading conanfile at '/home/estebandugueperoux/.conan2/p/081148d8ea3f0a46/e/conanfile.py': Unable to load conanfile in /home/estebandugueperoux/.conan2/p/081148d8ea3f0a46/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/estebandugueperoux/.conan2/p/081148d8ea3f0a46/e/conanfile.py", line 2, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (/home/estebandugueperoux/.local/lib/python3.10/site-packages/conans/__init__.py)


-------- Computing necessary packages ----------
ERROR: Package 'gtest/1.11.0' not resolved: gtest/1.11.0: Cannot load recipe.
Error loading conanfile at '/home/estebandugueperoux/.conan2/p/081148d8ea3f0a46/e/conanfile.py': Unable to load conanfile in /home/estebandugueperoux/.conan2/p/081148d8ea3f0a46/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/estebandugueperoux/.conan2/p/081148d8ea3f0a46/e/conanfile.py", line 2, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (/home/estebandugueperoux/.local/lib/python3.10/site-packages/conans/__init__.py)

```

Then I understand that conan 2.x doesn't supports package dependency with reference to conan 1.x syntax.
I try again by removing dependencies to gtest package and get a json document in stdout that I can parse with jq to get only version but there is no version attribute in this JSON document.
With conan 1.50.0, there is "--json JSON" option to write to a json file but in my case it remains worse than calling `export PACKAGE_VERSION=`conan inspect . --raw version``.
The best could be to have a single call to build, test and upload as we do with Maven when calling `mvn deploy` which invoke preceeding phases.

Regards.

**Comment by memsharded** [comment]
There is a syntax in Conan 1.X that will be compatible with Conan 2.0. But the recipes in ConanCenter haven't still updated to this new syntax.

> The best could be to have a single call to build, test and upload as we do with Maven when calling mvn deploy which invoke preceeding phases.

For that, the best possibility in 2.0 might be the new custom user commands. You can easily implement your own ``conan create_and_upload`` command that do what you want. You can have a look to: https://docs.conan.io/en/2.0/reference/commands/custom_commands.html

**Comment by EstebanDugueperoux2** [comment]
Hi @memsharded,

thanks for the information, but I prefer stay in the standard use of conan for better maintainability.

Regards.
