### ISSUE TITLE
[bug] MesonToolchain: Doesn't configure the default install destination directories as expected

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#11596]
### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora Linux 36
  * Compiler+version: GCC 12
  * Conan version: 1.50.0
  * Python version: 3.10.5

### Steps to reproduce (Include if Applicable)

Using the MesonToolchain, create any package on a RHEL system which uses `lib64` instead of `lib` or which packages anything in the default `datadir`, `mandir`, `localedir`, or `infodir`.

Many Conan recipes expect recipes to install libraries under the `lib` directory and under the `res` directory during the `package` step. MesonToolchain and/or Meson could configure these defaults with how Conan expects these directories to be organized, but it doesn't do that at the moment.

Things may be installed under `lib64` on RHEL systems and many things end up in the `share` directory.

Right now, the workaround I use is to configure `MesonToolchain` with `project_options` to set `libdir`, `datadir`, `localedir`, `mandir`, and `infodir` as appropriate.

I had to open the PR conan-io/conan-center-index#11347 to fix man pages being installed to an incorrect location in the package method.
See conan-io/conan-center-index#11610 and conan-io/conan-center-index#11580 for instances where this has been necessary.

**Comment by SSE4** [comment]
might be related to #9713 @franramirez688 ?

**Comment by franramirez688** [comment]
Closed by https://github.com/conan-io/conan/pull/11618
It'll be released in the next Conan 1.51 version.
