### ISSUE TITLE
Can't find a package with "conan search" but can install it with "conan install"

### ISSUE THREAD

**Issue by dmitry-zakablukov** [conan-io/conan#1159]
Good day!

I am experiencing a strange behavior of conan.
My conan.conf is as follows:
```
[storage]
path = ~/.conan/data

[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = 50                  # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
compression_level = 9       # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True     # environment CONAN_SYSREQUIRES_SUDO

[settings_defaults]

arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=6.3
os=Linux
```

If I have no local copy of a package, then I am not able to find it:
```
user@ubuntu ~/.conan $ conan search zlib/1.2.11@company/stable
There are no packages for pattern 'zlib/1.2.11@company/stable'
```

But! I can install it. My `conanfile.txt' is as follows:
```
[requires]
protobuf/3.2.0@passware/stable
AapGenerator/1.1@passware/stable

[generators]
visual_studio
scons
aap
```
And the installation command is:
```
user@ubuntu ~/workspace/protobuf $ conan install conanfile.txt -s build_type=Debug -s arch=x86 --update --build AapGenerator
protobuf/3.2.0@company/stable: Not found, looking in remotes...
protobuf/3.2.0@company/stable: Trying with 'conan.io'...
protobuf/3.2.0@company/stable: Trying with 'company'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Downloading conan_export.tgz
[==================================================]
zlib/1.2.11@company/stable: Not found, looking in remotes...
zlib/1.2.11@company/stable: Trying with 'conan.io'...
zlib/1.2.11@company/stable: Trying with 'company'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Downloading conan_export.tgz
[==================================================]
AapGenerator/1.1@company/stable: Not found, looking in remotes...
AapGenerator/1.1@company/stable: Trying with 'conan.io'...
AapGenerator/1.1@company/stable: Trying with 'company'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Requirements
    AapGenerator/1.1@company/stable from company
    protobuf/3.2.0@company/stable from company
    zlib/1.2.11@company/stable from company
Packages
    AapGenerator/1.1@company/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    protobuf/3.2.0@company/stable:c99a5f772408d9179133d50298d0e5fb4a065446
    zlib/1.2.11@company/stable:d0cbae41de95c42d955c5485d51cc35a5887f31f

AapGenerator/1.1@company/stable: WARN: Forced build from source
AapGenerator/1.1@company/stable: Building your package in /home/dimaz/.conan/data/AapGenerator/1.1/company/stable/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
AapGenerator/1.1@company/stable: Configuring sources in /home/dimaz/.conan/data/AapGenerator/1.1/company/stable/source
AapGenerator/1.1@company/stable: Copying sources to build folder
AapGenerator/1.1@company/stable: Generated txt created conanbuildinfo.txt

AapGenerator/1.1@company/stable: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' built
AapGenerator/1.1@company/stable: Build folder /home/dimaz/.conan/data/AapGenerator/1.1/company/stable/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
AapGenerator/1.1@company/stable: Generated conaninfo.txt
AapGenerator/1.1@company/stable: Generated conanbuildinfo.txt
AapGenerator/1.1@company/stable: Generated conanenv.txt
AapGenerator/1.1@company/stable: Generating the package
AapGenerator/1.1@company/stable: Package folder /home/dimaz/.conan/data/AapGenerator/1.1/company/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
AapGenerator/1.1@company/stable package(): WARN: No files copied!
AapGenerator/1.1@company/stable: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
zlib/1.2.11@company/stable: Installing package d0cbae41de95c42d955c5485d51cc35a5887f31f
zlib/1.2.11@company/stable: Looking for package d0cbae41de95c42d955c5485d51cc35a5887f31f in remote 'company'
Downloading conanmanifest.txt
[==================================================]
Downloading conaninfo.txt
[==================================================]
Downloading conan_package.tgz
[==================================================]
zlib/1.2.11@company/stable: Package installed d0cbae41de95c42d955c5485d51cc35a5887f31f
protobuf/3.2.0@company/stable: Installing package c99a5f772408d9179133d50298d0e5fb4a065446
protobuf/3.2.0@company/stable: Looking for package c99a5f772408d9179133d50298d0e5fb4a065446 in remote 'company'
Downloading conanmanifest.txt
[==================================================]
Downloading conaninfo.txt
[==================================================]
Downloading conan_package.tgz
[==================================================]
protobuf/3.2.0@company/stable: Package installed c99a5f772408d9179133d50298d0e5fb4a065446
PROJECT: Generated visual_studio created conanbuildinfo.props
PROJECT: Generated scons created SConscript_conan
PROJECT: Generated aap created conanbuildinfo.aap
PROJECT: Generated conaninfo.txt
```

After that, I can find the package, but only in local cache:
```
user@ubuntu ~/.conan $ conan search zlib/1.2.11@company/stable
Existing packages for recipe zlib/1.2.11@company/stable:

    Package_ID: d0cbae41de95c42d955c5485d51cc35a5887f31f
        [options]
            shared: False
        [settings]
            arch: x86
            build_type: Debug
            compiler: gcc
            compiler.version: 6.3
            os: Linux
        outdated from recipe: False
```

How can I help you to fix this problem?

Best regards, Dmitry.

**Comment by memsharded** [comment]
I am not sure about the issue. By default ``conan search`` searches only in the local cache. The output is good, nothing before install, the package after install. 

If you want to search your remote, add it to the command:

```bash
$ conan search zlib/1.2.11@company/stable -r=company
```

Could this be the issue?

**Comment by dmitry-zakablukov** [comment]
@memsharded ,
Ok, if it looks in local cache, then the output is correct. Nevertheless, I can't find the package in my remote:
```
user@ubuntu ~ $ conan search zlib/1.2.11@company/stable -r company -q "compiler=gcc and compiler.version=6.3"
There are no packages for reference 'zlib/1.2.11@company/stable' matching the query 'compiler=gcc and compiler.version=6.3'
```

If I don't specify a query, then I can't find any gcc 6.3 packages neither. But still able to install it...

**Comment by memsharded** [comment]
That is weird, could be a bug. What remote are you using, conan_server or Artifactory? Which versions?

**Comment by dmitry-zakablukov** [comment]
@memsharded , we are using conan_server v0.18.1 on Linux. Which one is up-to-date? Maybe the new one could help us.

**Comment by memsharded** [comment]
Maybe, if you upgraded your clients to > 0.20, you might check: http://docs.conan.io/en/latest/changelog.html#february-2017

So, yes, please, upgrade the server to latest and check if works, and please tell me. Thanks!

**Comment by dmitry-zakablukov** [comment]
@memsharded , upgrading to v0.21.1 helped. Thank you for your help!

**Comment by memsharded** [comment]
Great, thanks for upgrading and telling!

**Comment by shelper** [comment]
@memsharded  i am using latest conan 1.56 and got similar issue, not sure if there is still a bug, but it only searches with exact match, no wildchar match

see 
![image](https://user-images.githubusercontent.com/546163/211980990-f8c45ab5-e1cd-4f4c-b5cc-72acadc21f9e.png)

**Comment by memsharded** [comment]
That might depend on the server, what ``ett-release`` remote server are you using?

**Comment by shelper** [comment]
artifactory

**Comment by memsharded** [comment]
That is weird, I cannot reproduce it here, seems to be working fine.
Can you please check in your Artifactory repo, in the root, it should have a ``.conan`` folder with a ``packages.ref.json`` inside. That file, you can download it, and should contain the references in your repo, is that the case? If not, you might try to remove the file, it will be regenerated next time ``conan search`` needs it.

**Comment by shelper** [comment]
humm, i could not find the .conan folder in the repo root
see image below, also it only happens with this opencv package, for other packages it works, see the screenshot below as well.
![image](https://user-images.githubusercontent.com/546163/212092272-3ab8c6cc-29c9-4860-a0e7-69cc5e808e5e.png)
![image](https://user-images.githubusercontent.com/546163/212092688-63c7074d-ffb5-49ec-a337-8729030d34a5.png)

**Comment by memsharded** [comment]
Do you know which Artifactory version are you running? That folder was introduced a few releases ago to optimize the speed of ``conan search``, so I thought it could be related. 
If that is not the reason, I have no idea. 

Do the same queries, in that machine, but against ``-r conancenter`` work? Can you please try it?

**Comment by shelper** [comment]
using -r conancenter everything works. 
artifactory Enterprise Plus 7.38.10 rev 73810900 
i can live with that, just want to report what i encountered

**Comment by memsharded** [comment]
Yes, great to know and thanks for reporting it.
I think it might something specific to your Artifactory setup, maybe the configuration of an Nginx in front of it, or something like that, that could be affecting the http requests?

Are you planning an Artifactory upgrade soon? Artifactory 7.41 is the version containing the above optimization, it would be great to know if that fixes something after update.

**Comment by shelper** [comment]
i will keep you updated, but i am not in the team that maintains artifactory
thanks though
