### ISSUE TITLE
[bug] Read timeout accessing conancenter via conan CLI

### ISSUE THREAD

**Issue by bbossola** [conan-io/conan#11602]
### Environment Details (include every applicable attribute)
Operating System+version: Ubuntu 18.04.6 LTS
Conan CLI version: 1.50.0

### Steps to reproduce (Include if Applicable)
Just run a simple inspect command using conancenter: 
```
$ conan inspect -r=conancenter openssl/1.1.1k

ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ReadTimeoutError("HTTPSConnectionPool(host='center.conan.io', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

We get the same timeout if we run a simple curl to the ping endpoint:
```
$ curl https://center.conan.io/v1/ping
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.21.4</center>
</body>
</html>
```

**Comment by bbossola** [comment]
![image](https://user-images.githubusercontent.com/186370/178153543-4670eff2-9e5a-48be-8bf2-cb3bcc3d65d8.png)
Status page says everything is fine

**Comment by ilyamt-tandemg** [comment]
Can confirm that center.conan.io is not accessible for us as well.

**Comment by loachfish** [comment]
ping center.conan.io
```
PING center.conan.io (34.107.244.196) 56(84) bytes of data.
64 bytes from 196.244.107.34.bc.googleusercontent.com (34.107.244.196): icmp_seq=1 ttl=116 time=78.9 ms
64 bytes from 196.244.107.34.bc.googleusercontent.com (34.107.244.196): icmp_seq=2 ttl=116 time=69.2 ms
64 bytes from 196.244.107.34.bc.googleusercontent.com (34.107.244.196): icmp_seq=3 ttl=116 time=74.9 ms
64 bytes from 196.244.107.34.bc.googleusercontent.com (34.107.244.196): icmp_seq=4 ttl=116 time=79.3 ms
```

view center.conan.io with Chrome, a text is download which contents:
```
Please, visit https://conan.io/center/
```

**Comment by bbossola** [comment]
@loachfish 

> ping center.conan.io
> 
This is the machine, not the underlying service. The machine appears to be up and running.



> view center.conan.io with Chrome, a text is download which contents:
> ```
> Please, visit https://conan.io/center/
> ```
This is the nginx reverse proxy, not the underlying service. The nginx proxy appears to be up and running

**Comment by memsharded** [comment]
Thanks very much for reporting, we are having a look. Please track the pinned issue: https://github.com/conan-io/conan/issues/11604

**Comment by memsharded** [comment]
Check https://github.com/conan-io/conan/issues/11604, service should be back to normal now. Thanks again for reporting!
