### ISSUE TITLE
[bug] XcodeGen frameworkdirs is not working, FRAMEWORK_SEARCH_PATHS empty 

### ISSUE THREAD

**Issue by oeichenwei** [conan-io/conan#11616]
`XcodeGen` generator will not consume `frameworkdirs` and correctly put into `FRAMEWORK_SEARCH_PATHS`.
xcode generator is correct.
I investigate the code and it was a simple typo error and can be fixed by one line change:
https://github.com/oeichenwei/conan/commit/6a809a7cc881d35451a12b3c6fa6cc0ab8f4ff02

### Environment Details (include every applicable attribute)
  * Operating System+version: Macos + 12.4
  * Compiler+version: Xcode 13.3.1
  * Conan version: Conan version 1.48.0
  * Python version: Python 3.10.4 

### Steps to reproduce (Include if Applicable)

in conanfile.txt:
```
[generators]
 XcodeDeps
```
in conan.py
```
            self.cpp_info.frameworkdirs.append(self.package_folder)
            self.cpp_info.frameworks.append("MyFramework")
```

**Comment by czoido** [comment]
Hi @oeichenwei ,
Thanks for reporting, luckily this PR https://github.com/conan-io/conan/pull/11615 will solve the issue. This is targeting develop2 but it will be merged to the next Conan release too. Here is the PR to develop, should be released in 1.51: https://github.com/conan-io/conan/pull/11617
