### ISSUE TITLE
No Conan package/recipe for Visual Studio 2022

### ISSUE THREAD

**Issue by gprosch** [conan-io/conan#11611]
There is no package on Conan for Visual Studio 2022 (msvs v17 toolset v143).  Build missing does not work because there does not appear to be a recipe.  The following error message is emitted:

ERROR: libsodium/1.0.18: Invalid configuration: Unsupported msvc version: 17

**Comment by memsharded** [comment]
This doesn't seem a Conan issue, but a ConanCenter recipe issue.
Can you please post your full output, that includes the profile you are using for it, and the command you are using too?

**Comment by gprosch** [comment]
My humblest apologies, I submitted this to the wrong site.  I meant to submit to libsodium.  Please delete this.

**Comment by memsharded** [comment]
It could be a valid report in the ConanCenter recipe, feel free to submit an issue to conan-center-index repo if you think that something can be improved in the recipe there.
Closing this, thanks!
