### ISSUE TITLE
Add htpasswd repository to public list

### ISSUE THREAD

**Issue by d-schiffner** [conan-io/conan#1161]
Hi conan-team,

following PR #935, i created a own repository where my htpasswd middleware has been added. It should be added to the public repo, if possible, and furher enhanced.

You can find it here:
https://github.com/d-schiffner/conan-htpasswd

Best regards

Daniel

**Comment by memsharded** [comment]
Hi Daniel,

I think that you might want to add a license to your repo, just in case. 
One of the main reasons for the plugin-based architecture, is to decouple maintenance and support for different authenticators, and putting them into the main public repo will impose some expectations on our side, that right now we cannot fulfill. 

In any case, of course we want to have this plugin used an further enhanced, so I think the best will be to add it to the conan-docs, which is clearly the entry point for people looking for this functionality, not the repo. I have already submitted a PR: https://github.com/conan-io/docs/pull/183

Thanks very much for developing this plugin! Cheers.

**Comment by memsharded** [comment]
The documentation is already live, and the plugin is already linked there. Thanks again!
