### ISSUE TITLE
[feature] apply same flags for test_package as for parent recipe

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#11638]
If  you use some compilation flags in the build profile, they only applied to a recipe, but not to the test recipe.
I have the following lines in my build profile:
sqlite3:CFLAGS=-fsanitize=address,undefined,leak,integer -march=native -mtune=native
sqlite3:CXXFLAGS=-fsanitize=address,undefined,leak,integer -march=native -mtune=native
sqlite3:LDFLAGS=-fsanitize=address,undefined,leak,integer -march=native -mtune=native

If I call 
`conan-center-index/recipes/sqlite3/all$ conan create . sqlite3/3.38.5@andrei/test --build missing`
I get these errors:
```
/usr/bin/ld: sqlite3.c:(.text+0x3fbb8c): undefined reference to `__asan_report_store4'
/usr/bin/ld: sqlite3.c:(.text+0x3fbc07): undefined reference to `__ubsan_handle_pointer_overflow'
/usr/bin/ld: sqlite3.c:(.text+0x3fbc3d): undefined reference to `__ubsan_handle_type_mismatch_v1'
/usr/bin/ld: sqlite3.c:(.text+0x3fbc7e): undefined reference to `__ubsan_handle_type_mismatch_v1'
/usr/bin/ld: sqlite3.c:(.text+0x3fbcc6): undefined reference to `__asan_report_store4'
/usr/bin/ld: sqlite3.c:(.text+0x3fbd38): undefined reference to `__ubsan_handle_pointer_overflow'
/usr/bin/ld: sqlite3.c:(.text+0x3fbd6e): undefined reference to `__ubsan_handle_type_mismatch_v1'
```
That happens, because arch of recipe and test_recipe does not match.
Is there any way how could I adress specific test_recipe?
I dont want just to use wildcad in this case

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I guess you are defining those flags in the ``env`` section of your profile.
The problem with env-vars is that not all build systems listen to environment variables. CMake for example will ignore them, and I think that the ``test_package`` of recipes in ConanCenter are almost always using CMake to test.

Conan has introduced a new mechanism in ``conf`` that will be used in all build system new integrations, ``tools.build:cxxflags``, ``tools.build:cflags``, etc. This requires using the new integrations, check for example https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#conf. Recipes in ConanCenter will be moving to the new integrations in the following months to be 2.0 compatible.

**Comment by BlueSolei** [comment]
I have the same issue with the `CC` and `CXX` env vars.  
I build my package with: `conan create . mfc_strings/0.1 -pr:b=clang13 -pr:h=clang13`  
the result is that `mfc_strings` package is built with `clang-13` but the `test_package` is built with `GCC(/usr/bin/c++)`  
`GCC` is the default in my Ubuntu.  

@AndreyMlashkin, @memsharded,
**I actually find that I can fix it** simply by changing the attribute [apply_env](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=apply_env#apply-env) from `False` (default) to `True`, in `test_package/conanfile.py`.  this value is `False` in the scaffolded project generated from the template `cmake_lib` 
You can actually just remove the attribute altogether, as the default is `True`.  

Here is the [output of `conan create`](https://github.com/conan-io/conan/files/9124789/conan_create_output.txt)
Here is my [clang13.profile](https://github.com/conan-io/conan/files/9124812/clang13.profile.txt)  

also, @memsharded, in order not to use env var, I wish to use the new `[conf]` block, can you tell me the syntax of how to set `CMAKE_CXX_COMPILER` in the `[conf]` block?  
I tried to do:
```py
[conf]
tools.cmake.cmaketoolchain:generic_system={CMAKE_CXX_COMPILER: /usr/bin/clang++-13}
```
but in the generated `conan_toolchain.cmake`, CMAKE_CXX_COMPILER is not set :-(

**Comment by memsharded** [comment]
Hi @BlueSolei 

``apply_env`` goes back to the legacy way of managing the environment, so might not be the best approach.

the new ``tools.build:cxxflags`` configuration is an abstraction as not all build systems listen to env-vars for these. But for CC/CXX, if the build system is listening to those, it is perfectly valid to do:

```
[buildenv]
CC=....
CXX=....
```
Then the recipes should use the ``VirtualBuildEnv``. 
Have you tried this approach?

The idea is:
- From Conan to Tool (like cmake): Use env-vars via ``buildenv``
- From Conan to Conan (like CMakeToolchain): Use ``conf``.

**Comment by memsharded** [comment]
This is solved in Conan 2. Closing the ticket, but please don't hesitate to create new tickets if necessary to report against Conan 2, thanks for the feedback.
