### ISSUE TITLE
How to publish Jenkins build info for conan packages with Artifactory plugin

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/conan#1163]
How can I publish the build metadata info with a conan package using the Jenkins Artifactory plugin?

Because I don't see which files are uploaded, I cannot create an upload spec like shown here:

https://github.com/JFrogDev/project-examples/blob/master/jenkins-pipeline-examples/resources/props-upload.json

For nuget packages this worked quite well but how do I do it for conan packages?

**Comment by lasote** [comment]
Today Jenkins Artifactory Plugin 2.10.1 has been released,. The team is working to update the documentation so it will be available soon:

Conan support - The Artifactory Pipeline DSL now includes APIs for running Conan builds. You can now package, download and upload your Conan packages with Artifactory and Jenkins.

**Comment by CodingSpiderFox** [comment]
Thanks for letting me know. Please tell me when the documentation is done.

**Comment by memsharded** [comment]
Please check: https://wiki.jenkins-ci.org/display/JENKINS/Artifactory+-+Working+With+Pipeline+Jobs+in+Jenkins#Artifactory-WorkingWithPipelineJobsinJenkins-ConanBuildswithArtifactory

**Comment by CodingSpiderFox** [comment]
Thanks!

Tried it. Did not work for us. Issue was already opened: JENKINS-44045
