### ISSUE TITLE
conan package creation - version management

### ISSUE THREAD

**Issue by piniSolomon** [conan-io/conan#11639]
hi guys,
I'm new to Conan and I'm having trouble understanding how to handle the versioning of the packages I'm creating, specifically, I want to increment the patch version number (major.minor.patch) automatically and **update** it in the conanfile.py file
As a reference while using **npm** I have the option to do ```npm version patch``` and then the package.json file is updated with the incremented version and it can be committed to git. (the file is rewritten to file-system)

**Comment by memsharded** [comment]
Hi @piniSolomon 

There is no built-in command for this, you need to open the ``conanfile.py`` and modify the ``version`` attribute.
You have different ways of automating the version if you want, like ``set_version()`` method can read the version from a branch, or from a file, etc. There is no built-in commands for several reasons, like many recipes won't have semver compatible versions (fail), some recipes don't have version at all (get it from cli-fail), some versions have some dynamically defined version with ``set_version()`` (fail). Too much complexity for the value.

Conan 2.0 custom user commands will allow you to define your own commands easily, if that is important for your flow.

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
