### ISSUE TITLE
[question] Can't use layouts when also using generators

### ISSUE THREAD

**Issue by purplefishies** [conan-io/conan#11644]
Starting with the example editable project from https://github.com/conan-io/examples.git

```
cd examples/features/editable/cmake
perl -i -ne 's/add /add --layout=\$(readlink -f layout.ini) /g;print;' build.sh
# Now run the build.sh
./build.sh
```

If I look for the marker directory BLAHHHH I can't find it anywhere.  The code

```
    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
```

Makes the layout file get ignored.

I don't know how to get past this issue since I need to be able to configure the library location ( layout ) for an editable package AND I need to be able to use the generated conan_toolchain.cmake.

If I commented out the "def generate" ...section, then the layout works BUT I don't have the generated conan_toolchain.cmake file

Thanks for any help

[layout.txt](https://github.com/conan-io/conan/files/9112835/layout.txt)

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @purplefishies 

Yes, that way of specifying editables with external layout files is legacy and deprecated. The modern way to specify layouts is with the ``layout()`` methods. Templates like ``conan new hello/0.1 -m=cmake_lib`` already contain it, and can be made ``conan editable add`` out of the box, no need of external files. 

The documentation for editable packages was also updated some time ago, please have a look to https://docs.conan.io/en/latest/developing_packages/editable_packages.html, it contains a fully functional example.

**Comment by purplefishies** [comment]
So, my problem is that I am having to deal with a legacy project that started with pkg_config and then moved to conan. I am trying to make it an editable package while I do some editing to it .  

So, the example you gave
```
conan new hello/0.1 -m=cmake_lib
```
Doesn't work for me because 
1. The editable package has a different directory structure ( no include directory, headers are interspersed with the .cpp files  )  
2. The library's ( the one marked editable)  CMakeLists.txt file builds the output library into a location that is unique
 ( it's not built under build/Debug/libfoo.so   nor under  build/Debug/lib/libfoo.so , but instead it builds to build/Debug/PackageName/src ) 


So the workspace approach looks like it might work, but I'd really like to get the same functionality without using a workspace

I'm currently working in my Performance Testing library directory and I want to use an editable package  but be able to specify and tweak the library and includedirs locations using a layout file  similar to layout_gcc in the examples.

**Comment by memsharded** [comment]
I am not talking about workspaces at all, I am just talking about editables and layouts.

If you have a different directory structure, you have to write your ``layout()`` method, and specify where things are. The external file is not working anymore for new generators and integrations, and it has been completely removed in Conan 2.0.

You can check:
- https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html
- https://docs.conan.io/en/latest/developing_packages/package_layout.html#package-layout

**Comment by purplefishies** [comment]
So, is there an example way to setup the template for the 
```
def layout(self):
...
```

For instance, I can't configure or augment the equivalent of the build directories that are chosen which in my case would be 

build/Debug .

This corresponds to a template entry of 
```
build/{{settings.build_type}}
```
In my previous message, I mentioned that the library is getting built in a strange location , which would be 
build/{{settings.build_type}}/PackageName/src

I would like to append a directory onto this ( PackageName/src ) . However, when I've added libdir entries in def layout, it applies the  **src** location which is different than the build location.

**Comment by memsharded** [comment]
You can customize the build folder, in a very similar way, something like `` conanfile.folders.build = "build/{}".format(self.settings.build_type)``

Maybe having a look at the actual implementation of ``cmake_layout()`` in https://github.com/conan-io/conan/blob/develop/conan/tools/cmake/layout.py can be helpful too

**Comment by purplefishies** [comment]
What is the best practice way of doing that ? Configuring at the conanfile.py level ? 

I saw that there's a way to customize it through custom_conf but I can't find any examples to add multiple values without changing the layout.py file .

**Comment by purplefishies** [comment]
OK, got what you were saying.  I just did 

```{conanfile.py}
def layout(): 
    cmake_layout(self,src_folder="DIR")
    # Followed by 
    self.folders.build += "PACKAGE/src"
```
