### ISSUE TITLE
[feature] scripted remotes for recipes

### ISSUE THREAD

**Issue by tsondergaard** [conan-io/conan#11646]
When `conan` is building the dependency graph it will use remotes to pull down recipes that are not already in the cache or with the `--update` argument it will check for newer recipes in remotes.  I think it would be useful if it was possible to extend this mechanism so scripts could be used as an alternative to a remote to obtain recipes. It could look something like this:

~/.conan/remotes.json:
```json
{
 "remotes": [
  {
   "name": "fetch-recipes",
   "type": ""export-script",
   "command": "/opt/conan-git-helper/pull-recipe-from-git"
  },
  {
   "name": "conancenter",
   "url": "https://center.conan.io",
   "verify_ssl": true
  }
 ]
}
```

In the remotes.json above there is a new `type` field for remotes and the type `"export-script"` runs a script to obtain the recipe instead of downloading it via http. **The use case for this is to be able to use the `conan install` and `conan info` mechanism for building a full dependency graph without first having populated either the conan cache or a remote with all the necessary recipes**. Instead the recipes are pulled on-demand from a git repository via the provided export-script. For `"export-script"` type remotes there would be a `command` property specifying a command that conan will execute with the relevant parameters to identify the desired recipe. The configured script could be expected to run e.g. `conan export` to populate the cache and return 0 to indicate success.

With such a setup a CI pipeline could be provided with a conanfile.txt or conanfile.py and it would be easy to populate first the conan cache with all the relevant dependencies and then upload them to a conan repository. That way git becomes the direct source of truth and remote artifactory instances only a destination for recipes and binaries.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @tsondergaard 

I think you want to follow the ongoing idea in https://github.com/conan-io/conan/pull/10433. It is very early, and at the moment it is on-hold, until 2.0 is out of beta, but we will continue work after it at some point.

Please check it, and I think we can close this and track the PR instead, thanks!

**Comment by tsondergaard** [comment]
I agree, I will follow the PR. Closing this issue
