### ISSUE TITLE
Reconsider header & lib traits effects on compiler flags

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11642]
Latest changes in https://github.com/conan-io/conan/pull/11615, mimic the same behavior already done for CMakeDeps:

- If the dependency doesn't have traits ``libs=True or headers=True``, then the compiler flags  (from ``cpp_info``) are also dropped (besides the ``includedirs`` and ``libs``, etc)
- In general the dependencies that have all main traits to False, are discarded (BINARY_SKIP), so they are not considered or iterated in ``self.dependencies``
- But it is possible that some dependency has trait ``run=True``

It might be necessary to consider cases of toolchains, or packages with build-scripts that might also define ``package_info()`` with flags for consumers.

**Comment by lasote** [comment]
Just for reference, in `CMakeDeps` is implemented in target_data and looks like this:

```
      if require and not require.libs and not require.headers:
          self.defines = ""
          self.compile_definitions = ""
          self.cxxflags_list = ""
          self.cflags_list = ""
          self.sharedlinkflags_list = ""
          self.exelinkflags_list = ""
          self.objects_list = ""
```

We agreed on introducing the same for other generators, one by one. Only if a use case with tool-requires need that propagation we would study how to solve it.

**Comment by memsharded** [comment]
Just checked ``MSBuildDeps``, it needs some work:
```python
 fields = {
            'name': name,
            'root_folder': package_folder,
            'bin_dirs': join_paths(cpp_info.bindirs) if require.run else "",
            'res_dirs': join_paths(cpp_info.resdirs),
            'include_dirs': join_paths(cpp_info.includedirs) if require.headers else "",
            'lib_dirs': join_paths(cpp_info.libdirs) if require.libs else "",
            'libs': "".join([add_valid_ext(lib) for lib in cpp_info.libs]) if require.libs else "",
            # TODO: Missing objects
            'system_libs': "".join([add_valid_ext(sys_dep) for sys_dep in cpp_info.system_libs]),
            'definitions': "".join("%s;" % d for d in cpp_info.defines),
            'compiler_flags': " ".join(cpp_info.cxxflags + cpp_info.cflags),
            'linker_flags': " ".join(cpp_info.sharedlinkflags + cpp_info.exelinkflags),
            'dependencies': ";".join(deps),
            'host_context': not build
        }
```

**Comment by memsharded** [comment]
This is consistent atm, the flags are skipped in all generators if the headers and libs artifacts are skipped.
