### ISSUE TITLE
[question] Packing builds with different profiles into one container

### ISSUE THREAD

**Issue by Sebastian-Setzer** [conan-io/conan#11657]
Hi,
our use-case is an embedded system with different kinds of CPUs inside (32 bit and 64 bit). The software to run on those has to be built with different settings.
In the end, we need them all in one container.

Right now, it looks like conan doesn't support this use case, in the sense that you can have a "container" package that "requires" the other packages which have been built with different settings. Because settings are global in conan.

I'm aware that you can specify different settings for packages matching some pattern.
But that stops working as soon as you have a diamond dependency graph, where the package common to both parts has to be built with different settings.

So, no way to do that with "requires" dependencies? We can only work around conan in some way?
- Use some other tool than conan to built the container in the end
- Use conan to build the container, but don't "require" the dependencies - just "tools.get()" them

Regards,
Sebastian

**Comment by memsharded** [comment]
Hi @Sebastian-Setzer 

I am not sure if I fully understand your use case. One thing is how Conan manages packages at development time, for this case the approach is indeed 1 binary for each different configuration, including different architectures.

And the "deployment" or final installation case is typically different. You can ``conan install`` as many configurations as you want, and use some ``-g deploy``, or maybe some recipe with an ``imports()`` method to get the Conan packages and its dependencies, and copy/install the files that you want. This task is also improved in Conan 2.0 with the new ``deployers`` tools.

Please let me know if this helps, or provide more details to clarify. Thanks!

**Comment by Sebastian-Setzer** [comment]
Hi @memsharded ,
yes, we could just "deploy" both parts separately. But they belong together - there is a communication channel between the two different cores, and both sides must have a compatible version.

In addition to that, our deployment tool gets one "container" (=package, ZIP file, ...) for both parts. It would be nice to generate that from conan as well, so that we don't need yet another mechanism to handle binary packages.
I think, this part we can solve by calling two other conan instances from the container-conan (just using `run()`).

But with `run("conan...")` we can't use the normal version resolution as with `requires`, so that's a bit sad.

Regards,
Sebastian

**Comment by Sebastian-Setzer** [comment]
What works, by the way, is to use options instead of settings. But:
- Each package has to pass on these options to its dependencies
- This is not how conan is intended to be used... everyone else is using settings to chose the compiler.

So if there's nothing else, I would prefer the `run("conan...")`solution.

**Comment by memsharded** [comment]
So, do you mean that you need to install **different** packages, in a consistent way, but for different architectures? Or it is the same package, the binaries for different architectures? In the first case, the per-package settings would help, and you might be able to deploy with one single ``conan install``. Using profile files is the recommended approach for production, and they can use some power features, like jinja templating if necessary, not sure if that might help.

**Comment by Sebastian-Setzer** [comment]
Yes, different packages. Different architecture and different sources as well. But they may have common dependencies (same source, but must be compiled for different architectures) - that's what I meant with diamond structure. And that's where per-package settings don't work anymore.

**Comment by lasote** [comment]
Is this issue something that a lock file (applied to all `conan install` of all different architectures) locking the versions of the "common recipes" could solve?

**Comment by Sebastian-Setzer** [comment]
> Is this issue something that a lock file ... could solve?

I don't think so - a lock file only helps to reproduce the same thing later on, right?

**Comment by lasote** [comment]
I was thinking of the locks for Conan 2, which are simpler and more powerful. I'm not fully sure I've understood the issue, but if you generate a lock for configuration 1 and then apply it to configuration 2, the common parts should be resolved to the same recipe versions/revisions.

**Comment by Sebastian-Setzer** [comment]
>  the common parts should be resolved to the same recipe versions/revisions.

But that's the opposite of what I want - I want them to be built with different toolchains. Or am I misunderstanding something?

**Comment by Sebastian-Setzer** [comment]
Anyway, I don't have that use case anymore - we won't be using conan at all, as far as I can tell (switching to a different package manager)
So, maybe keep it in mind for conan 2.0 design - I don't think we're the only ones using the hybrid ARM boards. But don't worry about me...

**Comment by memsharded** [comment]
> But that's the opposite of what I want - I want them to be built with different toolchains.

The lockfile in 2.0 will lock the recipe and revision part, but will allow to be used for different toolchains (different configurations/profiles in Conan syntax). So applying the same lockfile guarantee that the sources origins (recipes and sources) have the same versions and revisions, but the binaries can be different, built with different toolchains.

**Comment by memsharded** [comment]
Thanks for the feedback!
