### ISSUE TITLE
[feature] Add support of custom ConanFile classes 

### ISSUE THREAD

**Issue by lo1ol** [conan-io/conan#11665]
Hi! We continue to integrate conan to our projects. Our organization has custom settings.yml, compability rules and restrictions. So this rules has to be written inside each project's conanfile.

To avoid duplication of this rules, we are thinking about distribution them with conan config inside directory `user_utils`. Here is an example:
```python
from conans import ConanFile
from conans.errors import ConanException

from os import path
import re


class RutokenConanFile(ConanFile):
    settings = "os", "compiler", "arch", "build_type", "libc"

    def config_options(self):
        if self.settings.get_safe("os") == "Windows":
            build_type = self.settings.get_safe("build_type")
            if build_type is not None:
                self.settings.compiler.runtime = "MTd" if  build_type == "Debug" else "MT"

    def package_id(self):
        if self.settings.get_safe("compiler") == "Visual Studio":
            del self.info.settings.compiler.version

            extract_msvc_version = re.compile(r"^(?:clang\d*v|v)(\d+)(.*)")

            def get_msvc_version_and_attr(t):
                if t == "ClangCL":
                    return "142", None

                res = extract_msvc_version.match(t)
                if not res:
                    return None, None
                if not res.group(2):
                    return res.group(1), None
                return res.group(1), res.group(2)

            orig_toolset = str(self.settings.compiler.toolset)
            orig_version, orig_attr = get_msvc_version_and_attr(orig_toolset)

            if orig_version is None:
                raise ConanException("Unknown VS toolset %s" % orig_toolset)

            # values_range returns older version at beginning
            # newer version more compatiable then older
            for toolset in self.settings.compiler.toolset.values_range[::-1]:
                if toolset == orig_toolset:
                    continue

                version, attr = get_msvc_version_and_attr(toolset)
                if version is None:
                    continue

                # v141_xp compatiable with v141 and v140_xp
                # v141 compatiable only with v140
                if orig_version >= version and (attr is None or orig_attr == attr):
                    compat_pkg = self.info.clone()
                    compat_pkg.settings.compiler.toolset = toolset
                    self.compatible_packages.append(compat_pkg)
```

So, now I can use this custom ConanFile inside any our project's conanfile. I do it so:
```python
import sys
from os import path
sys.path.append(path.join(path.expanduser('~'), ".conan/user_utils"))

from rutokenconanfile import RutokenConanFile


class RtcryptConanfile(RutokenConanFile):
    settings = "os", "compiler", "arch", "build_type", "libc"
    options = {"use_cprocsp": [True, False]}
    default_options = {"use_cprocsp": True}

    def build_requirements(self):
        if self.options.use_cprocsp:
            self.tool_requires("cprocsp/5.0.11732@rutoken/stable")

    def package(self):
        self.copy("*", excludes="tests", src=self.build_folder)

    def package_id(self):
        super().package_id(self)
        del self.info.options.use_cprocsp
```

I'm very like that this conanfile is distributed with corresponding settings and may be very customizable. Only one thing disappoint me. It is using of `sys.path.append`. I think that conan must add custom ConanFile class to path by itself.

Also, we can distribute some custom tools by the same way.

What do you think about adding feature of distribution and using custom tools and custom ConanFile classes to conan 1.0 and 2.0?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @lo1ol 

This functionality has been addressed by ``python_requires``, you can have a look in https://docs.conan.io/en/latest/extending/python_requires.html

In our experience there is a very big problem with the approach of having it in the path (you can do it easily by putting that into a regular Python pip package, and installing that package, then having your recipes ``import`` from it), in a global way: recipes do really affect the resulting binaries. You can change a recipe and you want to be able to control if that means that all packages using it should be rebuilt or not. This is implemented in the ``python_requires`` and their effect (minor_mode, only minor version bumps require rebuilds) in the ``package_id`` of the consumers.

We had a similar problem with the custom generators in the cache (global too), and they have been already removed in Conan 2.0, and the recommendation will be to use ``python_requires``

**Comment by lo1ol** [comment]
Thank you for so fast answer! We are try to use python_requires)
