### ISSUE TITLE
[Question] Get RREV

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#11664]
How can I get the resulting RREV of a conanfile.py, without needing to export the package at all (e.g. if it is very huge)?

I currently do it by creating some "manifest_str" containing the md5 of each file. E.g. it looks:
```
conanfile.py: f45f28c0c78146ce11bf9127f0de07b3
myfile: 4a14b907748ec7efd3e66c14e791b423

```

Then I call:
`RREV = model.manifest.FileTreeManifest.loads("1\n"+manifest_str)`

The smart thing with this approach is, that I can store the md5 sums of all the exports_sources files and create the `manifest_str` without the actual file needing to be present.

Is there any official way how to get the RREV without actually exporting the package?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Hi.
First of all, I wouldn't recommend using internal/non-documented classes like `model.manifest.FileTreeManifest` or Conan can break your recipe at any release.

There is no general way to do that because the revision could depend on the "export" you are doing (export() method, export attribute) so there is no way to predict the revision without calculating it in the general case.

If you are using git it might be better to use the `revision_mode="scm"` and you could check the commit to know the revision it will take. Check https://docs.conan.io/en/latest/reference/conanfile/attributes.html#revision-mode

**Comment by thorsten-klein** [comment]
@lasote Thanks a lot for your answer!
In our case the `revision_mode="scm"` is not possible .

Background:
We have a collection of `conanfile.py`, which are stored and maintained in one repository (similar to your conan-center-index repository).
When we commit our changes at conanfile.py, there should only be a new revision created from this package, and not from any other package.
With `revision_mode="scm"` ALL packages would get a new revision.

That is the reason, why I calculate the resulting RREV of each conanfile.py by reproducing same logic like conan internally does (= create the export-manifest and calculate the hash).

**Comment by lasote** [comment]
I don't know what else could you do to get it.
Why do you need the revision in advance?

**Comment by thorsten-klein** [comment]
We need the revision in order to have reproducible builds. 
Otherwise we would affect old builds, if we make changes at any `conanfile.py`.
e.g. a build `requires("mylib/1.0.0@our/release")`, then it may be the newest revision at the time of building. This may be different then in case of a build at a later point of time.

Alternatively we would have to maintain the revision manually via `version` (e.g. 1.2.3-r1, 1.2.3-r2,..), but this is not what we want.

**Comment by lasote** [comment]
I totally get why you want to use `revisions` I was wondering why you need to obtain it (but not do an export). Let's say you know that the `revision` of a `conanfile.py` will be `xxxxx`. What is the `xxxxx` used for?

**Comment by thorsten-klein** [comment]
We export all of our sources together with the conanfile.py in order to be independent from any 3rd party server (Big difference between your conan-center, where you rely on some external url where you download source code from)

The `exports_sources` may be a very big source code (e.g. gcc) >100MB.
We do not want to blindly download the `exports_sources`, in order to `conan export` the package and obtain the RREV.
Instead we want to check in advance, if the RREV is already existing remote. 
If yes, then we do not need to waste any time at all (respectively any network bandwith) in order to download anything.

So it is something like:
```
RREV=$( get_RREV "mylib/1.0.0/conanfile.py" )
if exists_recipe_remote "mylib/1.0.0@foo/bar#RREV" ; then
    if exists_package_id_remote "mylib/1.0.0@foo/bar#RREV" -p $package_id; then
        exit 0 # nothing to do at all
    else
        conan download "mylib/1.0.0@foo/bar#RREV" --recipe # download the recipe from remote
    fi
else
    # only in this case we need to download the exports_sources
    download mylib/1.0.0/exports_sources.txt
    conan export mylib/1.0.0/conanfile.py foo/bar # exports mylib/1.0.0@foo/bar#RREV to local cache
fi

# now the conan recipe is present in the local cache in any case
conan install mylib/1.0.0@foo/bar#RREV --build=missing
conan upload mylib/1.0.0@foo/bar#RREV -p $package_id
```

**Comment by lasote** [comment]
Thanks, I start to understand the issue. 
So, would it be possible to have an `exports_source()` method doing the `download mylib/1.0.0/exports_sources.txt` but maybe with an environment variable that skips that download? I don't love the environment variable either but I cannot guess anything else:

```python
class LibConan(ConanFile):
    name = "lib"
    version = "1.0"

    def export_sources(self):
        if not os.getenv("SKIP_EXPORT"):
            self.output.info("DOWNLOADING THE BIG ZIPFILE")
 ```

So regular export:

```
conan export .
Exporting package recipe
lib/1.0: Calling export_sources()
lib/1.0: DOWNLOADING THE BIG ZIPFILE
lib/1.0: The stored package has not changed
lib/1.0: Exported revision: 241dd2157fd122539a76dd458cd722be
```

Skipping the sources:

```
SKIP_EXPORT=1 conan export .    
Exporting package recipe
lib/1.0: Calling export_sources()
lib/1.0: The stored package has not changed
lib/1.0: Exported revision: 241dd2157fd122539a76dd458cd722be
```

**Comment by thorsten-klein** [comment]
Nice idea, but I think this does not work. As soon as the downloaded file is really copied to export_source folder, the recipe revision will change. In your example you do only some output and this does not affect the `conanmanifest.txt`.

Extended example:
```
class LibConan(ConanFile):
    name = "lib"
    version = "1.0"

    def export_sources(self):
        if os.getenv("FAST_MODE"):
            self.output.info("BLINDLY ADD BIG ZIPFILE WITH ITS MD5 TO CONANMANIFEST TXT WITHOUT DOWNLOADING")
            self.add_to_conanmanifest_txt("myfilename.zip", md5="e5d695597e9fa520209d1b41edad2a27")
            return

        if not os.path.exists("myfilename.zip"):
            self.output.info("DOWNLOADING THE BIG ZIPFILE")
            tools.download("http://someurl/somefile.zip", os.path.join(self.export_sources_folder, "myfilename.zip"), md5="e5d695597e9fa520209d1b41edad2a27")
        else:
            self.output.info("COPYING THE BIG ZIPFILE WITH IS PRESENT LOCALLY")
            self.run("cp myfilename.zip %s" % self.export_sources_folder)
```

But this will result in a broken package, if we run `conan export` having the env var `FAST_MODE` set (because the actual export_source file is really missing). So this is exactly the reason why IMHO there should be the possibility to get the RREV without doing the actual `conan export`.

What do you think if the md5 of each `self.exports_sources` can be (optionally) stored?
```
exports_sources = ["myfile.zip:e5d695597e9fa520209d1b41edad2a27"]
```

If all the md5sums are known, it is possible to calculate the RREV (e.g. via `conan info --only rrev`). 
Additionally there could also be a check internally that the md5sum of the `self.exports_sources` are really matching.
This could even be implemented in conan 1.x since its behavior will not be changed in case the `:md5` is omitted.

**Comment by lasote** [comment]
> Nice idea, but I think this does not work.

Yeah, of course, sorry for the noise.

> What do you think if the md5 of each self.exports_sources can be (optionally) stored?

Honestly, I think the flow you are doing is hacky, I totally get why are you doing it but it is not supported, I wouldn't want to introduce "patches" like the `md5` hardcoded to support it because eventually you still need such a bunch of logic to avoid downloading the files.

If we solve this (I don't know how yet) I think we should do it right.
I'll ask @memsharded, maybe he has some idea.

By the way, going back to the:

> We export all of our sources together with the conanfile.py in order to be independent from any 3rd party server

Can't you store the zipfile in an internal Artifactory server and just use `tools.get` to get it always from there? Is it really needed to have the sources in the recipe?

**Comment by thorsten-klein** [comment]
> Can't you store the zipfile in an internal Artifactory server and just use tools.get to get it always from there? Is it really needed to have the sources in the recipe?

IMHO a conan package is broken/useless, if it is not self-contained. It may happen, that people cannot rebuild it at any time later from source. And such a broken conan package is a high risk for any running project.

If we rely on any server different than the conan remote (any 3rd party server or even internal server), the server may go down or move (temporarily or permanently). With an internal server, people from outside do not have access at all.

Use case / example: 
in 5 years we will have to add a security patch to an existing package (backport). Or we have a new hardware platform (=new conan settings). As a result we need to rebuild packages from source. But where do we get the source code from if the download link is not working anymore? We can only hope, that someone has a copy stored locally....

Out of interest: How do you actually handle this in your conan-center? 
What happens if a security patch is required for [dbus 1.12.20](https://github.com/conan-io/conan-center-index/tree/master/recipes/dbus), but the source code tar.gz got removed from [their server](https://dbus.freedesktop.org/releases/dbus/)? What happens, if you introduce some new conan settings, for which you want to create prebuilt packages?
Does your CI fail? How to fix it? 
Where do you get the `dbus-1.12.20.tar.gz` file from then? 

So as a result this is really a critical point (and actually the reason why we have our own conan-center instead of using yours).
We must ensure, that our conan packages are self-contained and available for anybody at any time. Even if we switch to another artifactory, we do not have any problem in future: the conan package is self-contained and still works - there is no need for any modification.

**Comment by lasote** [comment]
I get it, but many companies have an internal server (or private cloud) as storage, like Artifactory, that supports also Conan packages, to store there all the internal needed files. In a generic repository, you can store anything (e.g zipped files). 

Setting an appropriate backup policy it doesn't matter if the sources are stored in the conan server, actually you would store the conan packages in the same server as the ZIP files.

My concern is that you are trying to mix the two approaches that Conan support, on one hand, you want to benefit from revisions not attached to the source code (maybe just the SHA of the file downloaded) to optimize the times, and on the other hand you want to have the sources exported to "keep them safe". I don't think this is the correct path to follow, these "altered" flow you are following will make everything harder.

About conan-center, we usually rely on the sources to be available on the internet, checking the hash, of course. But in some cases with problematic servers or disappeared code, we store the zip files in the Artifactory that is storing everything under the scenes. Actually, it should be possible to create a ["remote" repository](https://www.jfrog.com/confluence/display/JFROG/Repository+Management#:~:text=Local%20Repositories%20page.-,Remote%20Repositories,the%20caching%20and%20proxying%20behavior.) in Artifactory that acts automatically as a cache of the zips from the internet.

**Comment by thorsten-klein** [comment]
@lasote yes this wie also have of course. Nevertheless it may happen, that someone by accident removes some files during housekeeping (e.g. `https://our.conan.center/artifactory/conan/sources/dbus-1.12.20.tar.gz`). This breaks then some of the conan packages (e.g. `https://our.conan.center/artifactory/conan/userA/dbus/1.12.20/channel`) - very hard to predict for the person removing a file at a different place (at `/sources/`)
The critical point here is also: This may be noticed first after 4 years (if nobody has tried to build this package from source until then) and then there is no backup in artifactory anymore.

Additionally the conan packages can not be uploaded to another artifactory. There is some modification required to adapt the download link (e.g. `https://their.conan.center`). This will lead to another RREV then. 

> on one hand, you want to benefit from revisions not attached to the source code

Do I really want this? For me the source code must have an impact on the revision (RREV). 
Otherwise people may exchange the underlying source code tar.gz file, which will lead to non-reproducible packages (or a broken package if the hashsum is checked in `source()`).

**Comment by lasote** [comment]
> Nevertheless it may happen, that someone by accident removes some files during housekeeping, that someone by accident removes some files

IMO That should be controlled with correct permissions (write but not delete) and maybe a different repository to store the sources. What would happen if someone decide to remove the Conan package itself? 

> Do I really want this? For me the source code must have an impact on the revision (RREV).

Yes, sure, I didn't explain correctly. I meant that you want the better from external sources and the better from exported sources and that is not supported.

**Comment by thorsten-klein** [comment]
> IMO That should be controlled with correct permissions (write but not delete) and maybe a different repository to store the sources. What would happen if someone decide to remove the Conan package itself?

Yes, indeed. So actually you MUST not remove any file at all in an artifactory. 
Nevertheless my second argument is still valid that the conan package is tightly coupled to the artifactory itself - it cannot be uploaded to another artifactory.


> If we solve this (I don't know how yet) I think we should do it right.

I am completely open for any solution :-) I only wanted to point out that it is quite a valid use case to get the RREV without exporting a package at all. This may also be helpful for editable mode also (Ref: #11689 ).
