### ISSUE TITLE
Improve default visualisation options for the HTML generated with --graph

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#1166]
Hi guys,

I played a bit today with the new `--graph` feature included in conan 0.21.0. At first I was a bit confused, because I obtained something like this just after opening the **html** file:

![defaultview](https://cloud.githubusercontent.com/assets/102645/24525181/af9837de-1599-11e7-8426-19d206d74aca.jpg)

That graph was not showing for sure the dependencies of my project. I could not move the different nodes in all the directions, just from left to right, and therefore I could not see the real dependencies. I had to ask @memsharded about this, and then I realised that in the top-right corner of the screen there is a tiny link called _"Show/hide controls"_ that allows you to play with all the different options, so I could finally something cooler like this:

![changesortmethod](https://cloud.githubusercontent.com/assets/102645/24525294/0bbe421a-159a-11e7-8b7c-deb2735b0d26.jpg)

It would be nice to find other default options fitting better with complex projects having more than few dependencies. I am sure it would save some precious minutes to other conan users ;)

**Comment by memsharded** [comment]
You are totally right, most likely we cannot make it into the 0.22, but lets improve it for the next 0.23 release.

**Comment by lasote** [comment]
It has been released in conan 0.22.0, Thanks!
