### ISSUE TITLE
[bug] system package failure on dnf and yum

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#11661]
[alma linux](https://github.com/bincrafters/system-packages-checks/runs/7368984232?check_suite_focus=true#step:6:214), [centos](https://github.com/bincrafters/system-packages-checks/runs/7368984251?check_suite_focus=true#step:6:184) and [fedora](https://github.com/bincrafters/system-packages-checks/runs/7368984210?check_suite_focus=true#step:6:206) fail with `ERROR: while executing system_requirements(): Error 100 while executing yum check-update -y`. This error code signals that there are some update available, so it should be ignored (it was ignored in the previous system package handler)
cf https://github.com/conan-io/conan/blob/f9215513368e576a82f071ab5d7b4cf990d156ca/conans/client/tools/system_pm.py#L348 and https://github.com/conan-io/conan/blob/f9215513368e576a82f071ab5d7b4cf990d156ca/conans/client/tools/system_pm.py#L317

### Environment Details (include every applicable attribute)
  * Operating System+version: linux
  * Compiler+version:
  * Conan version: 1.50
  * Python version:

**Comment by czoido** [comment]
Hi @ericLemanissier,
Thanks for reporting, yes, we overlooked that return code for dnf/yum in the new implementation. Will be fixed for 1.51
