### ISSUE TITLE
[bug] missing exports_sources when doing conan inspect

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#11663]
It seems that exports_sources is not considering the methods from conanfile.py

`$ cat conanfile.py`
```
from conans import ConanFile, CMake, tools

class ConanRecipe(ConanFile):
    name = "libA"
    version = "1.0.0"

    exports_sources = ["foo"] 

    def export_sources(self):
        self.exports_sources += ["bar"] 

```

`$ conan inspect conanfile.py -a exports_sources`

Actual:
```
exports_sources: ['foo']
```

Expected:
```
exports_sources: ['foo','bar']
```

**Comment by lasote** [comment]
The methods are not meant to modify the sibling attribute. The `export_sources` method will run while doing a `conan export` or `conan create`. The command `conan inspect` only loads the python class to read the attributes, so the `exports_sources` is not called at all.

**Comment by thorsten-klein** [comment]
@lasote  Thanks a lot for your answer! Would you then recommend to use a `@property` decorator for `exports_sources` instead of having all logic in `export_sources()` method?

**Comment by lasote** [comment]
Not so sure it will work either, it is possible that we only load the class and not the instance of the conanfile. You could try.

**Comment by thorsten-klein** [comment]
If I use `@property` the `inspect` seems to return the correct list of files.
