### ISSUE TITLE
conanbuildinfo uses cmake 3 specific features

### ISSUE THREAD

**Issue by theirix** [conan-io/conan#1167]
Hello!
I thought conan required cmake to be at least 2.8. Version 3.x is not mentioned anywhere in documentation. But recently I saw "add_compile_options" in a generated conanbuildinfo.cmake file which brokes 2.8 build (rhel 6). Could we please make it work with cmake 2.8 again?

**Comment by memsharded** [comment]
CMake 2.8.12 supports ``add_compile_options``: https://cmake.org/cmake/help/v2.8.12/cmake.html#command:add_compile_options

Most docs examples will use ``cmake_minimum_required ( VERSION 2.8.12 )``, I guess that the version in Rhel6 is older, right? 
I am sorry that it broke your build, we will check if it is possible to fix, but doesn't seem easy without breaking support for multi-config (Debug/Release) packages. 
Thanks for reporting!

**Comment by theirix** [comment]
The cause for the problem was a dangling cmake of version 2.8.11 (sic!) in `/usr/local/bin`. Also I really forgot about `add_compile_options` existence in 2.8.12. So it was my fault, sorry for the erroneous report.

**Comment by memsharded** [comment]
No worries! Happy that you were able to fix it. Thanks for telling.
