### ISSUE TITLE
 Check for working C compiler: - broken

### ISSUE THREAD

**Issue by himansu2906** [conan-io/conan#11674]
Hello All,

I am new to conan and currently trying to create library package and I am using gcc compiler.

whenever I am trying to create package it is giving following error

but if I am building this library with cmake command, it is building perfectly fine.

I am not able to set cross compile setting for with Conan.

if anyone can guild how can cross compile with  with Conan.

**Comment by memsharded** [comment]
Hi @himansu2906 

Can you please try sharing your conanfile.py and your CMakeLists.txt?
Another thing to try is to start with a "hello world" simple package, created with ``conan new hello/0.1 -m=cmake_lib``, and see if you are able to build with that compiler. It is possible that such compiler has something specific (like gcc 3.4 is really old and the Conan toolchain is producing some incompatible flag, because it is designed and tested with more modern compilers.

Also, please, do not share the output as images, but copy and paste the whole output as text (Github has utilities to hide it, so it doesn't clutter the whole issue), not trimming it, but the whole command output. Thanks!

**Comment by himansu2906** [comment]
below are the content of cmakefile.txt and conanfile.py
cmakefile.txt :
cmake_minimum_required(VERSION 3.23)


set (CMAKE_TOOLCHAIN_FILE=~/tricore-gcc.cmake)
set (CMAKE_C_COMPILER "C:/HighTec/TriCore_v3_4_7_3/bin/tricore-gcc.exe")

project(variant1)
#add_compile_options(-std=c++11)
# Source-files (.C) and include paths provided through the cmake CLI (-D option) 
file(STRINGS ${srcfilelist} sourcefilelist)
file(STRINGS ${inclist} includelist)

add_library(${exefile} ${sourcefilelist})
include_directories(${includelist})
add_compile_options(
    -Wall
    -g3
	-O2
	-funit-at-a-time
	-mtc13
	-W
	-mcpu=tc1796
	-DEEPROM_EXTERN
	-DMEDIUMCab2
	-DNEOB_DCT
	-DDCTVariant)
    
add_definitions(
	-DSRC14_34_31
	-DDCT
	-DUDS_AGCO_KEY
	-DSiE_EXTERNAL_CONFIG
	-DSECOND_FLASH_USED
	-DNO_COM_MODULE
	-DSTORAGE_CLASS=)

conanfile.py :
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout


class headlandConan(ConanFile):
    name = "headland"
    version = "0.1"

    # Optional metadata
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of headland here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake_find_package_multi", "gcc", "txt"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "common/efg_H2M2S2_platform/headland/source/*", "common/efg_H2M2S2_platform/headland/include/*"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
  
        tc.generate()

    def build(self):

        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["headland"]
        
        bin_folder = os.path.join(self.package_folder, r"C:\HighTec\TriCore_v3_4_7_3\bin")
        self.env_info.CC = os.path.join(bin_folder, "tricore-gcc.exe")
        self.env_info.CXX = os.path.join(bin_folder, "tricore-g++.exe")
        self.env_info.SYSROOT = self.package_folder

**Comment by memsharded** [comment]
Ok, I start to understand where the issues could be. Let me explain them:

- First, the toolchain is not to be written in the file. The lines:
  ```cmake
  set (CMAKE_TOOLCHAIN_FILE=~/tricore-gcc.cmake)
  set (CMAKE_C_COMPILER "C:/HighTec/TriCore_v3_4_7_3/bin/tricore-gcc.exe")
  ```
  Shoudn't be in your CMakeLists.txt. This is not related to Conan, but good CMake practices
- Then, if the ``tricore-gcc.cmake`` toolchain is necessary to build, then you can pass it your profile, defining it as a ``conf`` ``tools.cmake.cmaketoolchain:user_toolchain=tricore-gcc.cmake`` file. The idea is that it is something external to the build files and the packages. Some builds/binaries will be using that profile, and some builds can be using a different compilers, but the configuration for compiler, etc, should not be hardcoded in recipes or CMakeLists.txt, but external, as configuration (in this case, Conan profile files is the recommended way)
- Finally, the information you are putting in ``package_info()`` is useless. That is information for the consumers, about your own package, not about setting the environment for yourself.

**Comment by memsharded** [comment]
As a general recommendation, if you haven't yet I would recommended learning first a bit of the basics. Creating simple Conan packages, for different variants, but for mainstream, native compilers like Visual Studio or regular gcc. Reuse those packages. Use profile files to define configurations, etc. Then when you grasp the basics, you can then start more advanced stuff, as defining other non mainstream compilers, etc. If you like videos, then this free course might help a bit: https://academy.jfrog.com/path/conan

**Comment by himansu2906** [comment]
Hello,

Thank you for quick response,
I made below changes in default profile of conan


[conf]
tools.cmake.cmaketoolchain:user_toolchain=["C:/Users/h.yadav/Desktop/Conan/Packages/New_Packages/efg_devops_toolchain/M2_Restructuration/tricore-gcc.cmake"]

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=3.4
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

**following output is coming after trying to create conan package, now it is recognizing compiler but unable to build**

Exporting package recipe
headland/0.1@user/testing exports_sources: Copied 1 '.txt' file: CMakeLists.txt
headland/0.1@user/testing: A new conanfile.py version was exported
headland/0.1@user/testing: Folder: C:\Users\h.yadav\.conan\data\headland\0.1\user\testing\export
headland/0.1@user/testing: Exported revision: 52ad49d2670c2dc4c79dc32fe890d959
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=3.4
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
[conf]
tools.cmake.cmaketoolchain:user_toolchain=['C:/Users/h.yadav/Desktop/Conan/Packages/New_Packages/efg_devops_toolchain/M2_Restructuration/tricore-gcc.cmake']

headland/0.1@user/testing: Forced build from source
Installing package: headland/0.1@user/testing
Requirements
    headland/0.1@user/testing from local cache - Cache
Packages
    headland/0.1@user/testing:81df8f266218f6fef8f6668c364c4b9dd112820d - Build

Installing (downloading, building) binaries...
headland/0.1@user/testing: Configuring sources in C:\Users\h.yadav\.conan\data\headland\0.1\user\testing\source\.
headland/0.1@user/testing: Copying sources to build folder
headland/0.1@user/testing: Building your package in C:\Users\h.yadav\.conan\data\headland\0.1\user\testing\build\81df8f266218f6fef8f6668c364c4b9dd112820d
headland/0.1@user/testing: Generator gcc created conanbuildinfo.gcc
headland/0.1@user/testing: Generator txt created conanbuildinfo.txt
headland/0.1@user/testing: Calling generate()
headland/0.1@user/testing: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
headland/0.1@user/testing: Aggregating env generators
headland/0.1@user/testing: Calling build()
headland/0.1@user/testing: CMake command: cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/build/81df8f266218f6fef8f6668c364c4b9dd112820d/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/package/81df8f266218f6fef8f6668c364c4b9dd112820d" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\Users\h.yadav\.conan\data\headland\0.1\user\testing\build\81df8f266218f6fef8f6668c364c4b9dd112820d\."
-- Using Conan toolchain: C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/build/81df8f266218f6fef8f6668c364c4b9dd112820d/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 3.4.5
-- The CXX compiler identification is GNU 3.4.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/HighTec/TriCore_v3_4_7_3/bin/tricore-gcc.exe
-- Check for working C compiler: C:/HighTec/TriCore_v3_4_7_3/bin/tricore-gcc.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/HighTec/TriCore_v3_4_7_3/bin/tricore-gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/build/81df8f266218f6fef8f6668c364c4b9dd112820d/build/Release/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/MinGW/bin/mingw32-make.exe -f Makefile cmTC_f20b0/fast && C:/MinGW/bin/mingw32-make.exe  -f CMakeFiles\cmTC_f20b0.dir\build.make CMakeFiles/cmTC_f20b0.dir/build
    mingw32-make.exe[1]: Entering directory 'C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/build/81df8f266218f6fef8f6668c364c4b9dd112820d/build/Release/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_f20b0.dir/testCCompiler.c.obj
    C:\HighTec\TriCore_v3_4_7_3\bin\tricore-gcc.exe -D_GLIBCXX_USE_CXX11_ABI=0  -m64  -o CMakeFiles\cmTC_f20b0.dir\testCCompiler.c.obj -c C:\Users\h.yadav\.conan\data\headland\0.1\user\testing\build\81df8f266218f6fef8f6668c364c4b9dd112820d\build\Release\CMakeFiles\CMakeTmp\testCCompiler.c
    cc1.exe: error: invalid option `64'
    CMakeFiles\cmTC_f20b0.dir\build.make:76: recipe for target 'CMakeFiles/cmTC_f20b0.dir/testCCompiler.c.obj' failed
    mingw32-make.exe[1]: *** [CMakeFiles/cmTC_f20b0.dir/testCCompiler.c.obj] Error 1
    mingw32-make.exe[1]: Leaving directory 'C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/build/81df8f266218f6fef8f6668c364c4b9dd112820d/build/Release/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_f20b0/fast' failed
    mingw32-make.exe: *** [cmTC_f20b0/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:20 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/build/81df8f266218f6fef8f6668c364c4b9dd112820d/build/Release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/build/81df8f266218f6fef8f6668c364c4b9dd112820d/build/Release/CMakeFiles/CMakeError.log".
headland/0.1@user/testing:
headland/0.1@user/testing: ERROR: Package '81df8f266218f6fef8f6668c364c4b9dd112820d' build failed
headland/0.1@user/testing: WARN: Build folder C:\Users\h.yadav\.conan\data\headland\0.1\user\testing\build\81df8f266218f6fef8f6668c364c4b9dd112820d\build/Release
ERROR: headland/0.1@user/testing: Error in build() method, line 45
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/build/81df8f266218f6fef8f6668c364c4b9dd112820d/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/h.yadav/.conan/data/headland/0.1/user/testing/package/81df8f266218f6fef8f6668c364c4b9dd112820d" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\Users\h.yadav\.conan\data\headland\0.1\user\testing\build\81df8f266218f6fef8f6668c364c4b9dd112820d\."

**Comment by memsharded** [comment]
Is it possible to get this tricore-gcc.exe compiler from somewhere to be able to test it?

A couple of further notes:
- ``generators = "cmake_find_package_multi", "gcc", "txt"`` are useles, you shouldn't be using them here. If anything, try with the new ``CMakeDeps``, when you have dependencies (not this case).
- Your ``package_info()`` can be removed, according to the above comments.
- Need to confirm if you removed the definition of toolchain from your CMakeLists.txt or not.

**Comment by himansu2906** [comment]
please find below compiler zip.
[](url
[TriCore_v3_4_7_3.zip](https://github.com/conan-io/conan/files/9151395/TriCore_v3_4_7_3.zip)
)

I have removed package_info() from conanfile.py file and also removed definition of toolchain from CmakeLists.txt file.

content of conanfile.py and CmakeLists.txt are as below:
**conanfile.py:**

from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout


class headlandConan(ConanFile):
    name = "headland"
    version = "0.1"

    # Optional metadata
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of headland here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "common/efg_H2M2S2_platform/headland/source/*", "common/efg_H2M2S2_platform/headland/include/*"

    

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
              
        
        tc.generate()
        

    def build(self):

        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    **CmakeLists.txt :** 
cmake_minimum_required(VERSION 3.23)

#set (PRJ_ROOTPATH "%~dp0")

#set (VARIANT_NAME M2)
#set (TOOL_DIR "C:/Tools")
#set (VARIANTPATH "${PRJ_ROOTPATH}variants/${VARIANT_NAME}")
#set (CMAKE_BUILDPATH build_temp)
#set (MINGWMAKE_BINPATH "C:/MinGW/bin/mingw32-make.exe")
#set (FILELISTSPATH "${VARIANTPATH}/test/filelists")
#set (CMAKE_BIN "C:/Program Files/CMake/bin/cmake.exe")
#set (CMAKE_PRJPATH "${VARIANTPATH}/cmake")
#set (srcfilelist "${FILELISTSPATH}/HeadLand_lib.txt")
#set (inclist "${FILELISTSPATH}/Common_IncludeDirectoryLists.txt")
#set (exefile "${VARIANT_NAME}")
#set (CMAKE_TOOLCHAIN_FILE=~/tricore-gcc.cmake)
#set (CMAKE_C_COMPILER "C:/HighTec/TriCore_v3_4_7_3/bin/tricore-gcc.exe")


project(variant1)
#add_compile_options(-std=c++11)
# Source-files (.C) and include paths provided through the cmake CLI (-D option) 
file(STRINGS ${srcfilelist} sourcefilelist)
file(STRINGS ${inclist} includelist)

add_library(${exefile} ${sourcefilelist})
include_directories(${includelist})
add_compile_options(
    -Wall
    -g3
	-O2
	-funit-at-a-time
	-mtc13
	-W
	-mcpu=tc1796
	-DEEPROM_EXTERN
	-DMEDIUMCab2
	-DNEOB_DCT
	-DDCTVariant)
    
add_definitions(
	-DSRC14_34_31
	-DDCT
	-DUDS_AGCO_KEY
	-DSiE_EXTERNAL_CONFIG
	-DSECOND_FLASH_USED
	-DNO_COM_MODULE
	-DSTORAGE_CLASS=)

**Comment by himansu2906** [comment]
@memsharded : do you have any update for me on the issue?

**Comment by memsharded** [comment]
I am trying to reproduce this, but due to not knowing about this specific compiler, it is being very complex.

I would need to reproduce, first the basic CMake example, without Conan:
- A very simple, the very minimal ``CMakeLists.txt`` that builds the very minimal executable from a very simple source code.
- The exact command line that you are using with CMake to build it.
- The full output of the build (as text, not image)
- If the build and the command line require any other file, like a toolchain file, that file is also needed (as reduced and minimal as possible)

Then, for Conan, I would need specification of the full profile, for example:
- ``os`` (of the target system, is it Linux?)
- ``arch`` (the architecture of the target system)

**Comment by himansu2906** [comment]
Hello @memsharded ,

Please find attached simple hello library creation project with Tricore compiler.

[hello.zip](https://github.com/conan-io/conan/files/9218951/hello.zip)

following commands inside build 

>cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=tricore-gcc.cmake ..

>cmake --build . 

output is present in build folder itself.

Regarding Conan:
OS: windows
arch: x86

Please let me know if more information is required.

Thanks & Regards,
Himanshu Yadav

**Comment by memsharded** [comment]
Hi @himansu2906 

I have managed to make it work, indeed the toolchain was the piece that I was missing. Find attached a working example: [tricore-example.zip](https://github.com/conan-io/conan/files/9221388/tricore-example.zip)

Need to:

- In the ``tricore`` profile, need to specify the full path to the tricore-gcc.cmake toolchain instead of ``tools.cmake.cmaketoolchain:user_toolchain=["<path-to-toolchain>/tricore-gcc.cmake"]`` (there could be ways to make this relative, using jinja syntax, but lets keep it simple.
- Have tricore tools and mingw in the path. I hadn't them so I also used a ``[buildenv]`` section in the profile to add it to the path with the ``PATH=+(path)<path-to-tricore>`` syntax, and also I did the same to put Mingw in the path. If you have them, no need to do this
- ``conan create . -pr=tricore``

That should run the creation of a package (a library), and also the "consuming" and testing of that library by an executable application inside the ``test_package`` folder.

The changes I had to to are:

- I added ``"3.4"`` to the possible ``settings.yml`` (this file is in the Conan cache, in your ``<userhome>/.conan`` (this file can be managed in production with ``conan config install``, so it is not necessary to do this manual change)
- The piece that the tricore compiler was not liking that Conan was defining in the ``conan_toolchain.cmake`` was the flags. I discarded them from the conan toolchain with:
  ```python
      def generate(self):
        tc = CMakeToolchain(self)
        tc.blocks.remove("arch_flags")
        tc.generate()
  ```
- I added the ``generators = "VirtualBuildEnv"`` in the recipe, to make sure the environment (from my ``[buildenv]`` section) is injected correctly.
- As it is not possible to run the binary in Windows, I just check in ``test_package/conanfile.py`` the existence of the file:
  ```python
  def test(self):
        # we cannot run it
        cmd = os.path.join(self.cpp.build.bindirs[0], "example.elf")
        # Just check its existence
        assert os.path.isfile(cmd)
   ```

Just a note, the ``profile`` that is being passed with ``-pr=tricore`` should be the "host" profile (the one the binary will run). As it has the ELF extension, maybe it shouldnt be ``Windows``, but ``Linux``?

Please try it and let me know. Thanks!

**Comment by himansu2906** [comment]
Hello @memsharded ,

Thank you very much for your input, now I am successfully able to create package. 👍 

I have just one last question regrading generated library file(.a file). it is being generated in build/release folder instead of package folder, is it okay that .a file gets generated in build/release instead of package folder.

PFB output:

[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
Headland/0.1 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
Headland/0.1: A new conanfile.py version was exported
Headland/0.1: Folder: C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\export
Headland/0.1: Exported revision: 83e3169fafceb0ce2dd6604548c54e49
Configuration:
[settings]
arch=x86
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=3.4
os=Windows
[options]
[build_requires]
[env]
[conf]
tools.cmake.cmaketoolchain:user_toolchain=['C:/Users/h.yadav/Desktop/Conan/working_example/tricore-gcc.cmake']

Headland/0.1: Forced build from source
Installing package: Headland/0.1
Requirements
    Headland/0.1 from local cache - Cache
Packages
    Headland/0.1:210375de6cfaa2628183ee1d1d6cbaa69365a9ec - Build

Cross-build from 'Windows:x86_64' to 'Windows:x86'
Installing (downloading, building) binaries...
Headland/0.1: Configuring sources in C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\source\.
Headland/0.1: Copying sources to build folder
Headland/0.1: Building your package in C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\build\210375de6cfaa2628183ee1d1d6cbaa69365a9ec
Headland/0.1: Generator 'VirtualBuildEnv' calling 'generate()'
Headland/0.1: Calling generate()
Headland/0.1: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
Headland/0.1: Aggregating env generators
Headland/0.1: Calling build()
Headland/0.1: CMake command: cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="C:/Users/h.yadav/.conan/data/Headland/0.1/_/_/build/210375de6cfaa2628183ee1d1d6cbaa69365a9ec/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/h.yadav/.conan/data/Headland/0.1/_/_/package/210375de6cfaa2628183ee1d1d6cbaa69365a9ec" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\build\210375de6cfaa2628183ee1d1d6cbaa69365a9ec\."
Capturing current environment in C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\build\210375de6cfaa2628183ee1d1d6cbaa69365a9ec\build/generators\deactivate_conanbuildenv-release-x86.bat
Configuring environment variables
-- C:/Users/h.yadav/Desktop/Conan/Packages/New_Packages/efg_devops_toolchain/M2_Restructuration/variants/M2/test/filelists/HeadLand_lib.txt=
-- Using Conan toolchain: C:/Users/h.yadav/.conan/data/Headland/0.1/_/_/build/210375de6cfaa2628183ee1d1d6cbaa69365a9ec/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 3.4.5
-- The CXX compiler identification is GNU 3.4.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/HighTec/TriCore_v3_4_7_3/bin/tricore-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/HighTec/TriCore_v3_4_7_3/bin/tricore-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091
    CMAKE_SH


-- Build files have been written to: C:/Users/h.yadav/.conan/data/Headland/0.1/_/_/build/210375de6cfaa2628183ee1d1d6cbaa69365a9ec/build/Release
Headland/0.1: CMake command: cmake --build "C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\build\210375de6cfaa2628183ee1d1d6cbaa69365a9ec\build/Release" -- -j8
Capturing current environment in C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\build\210375de6cfaa2628183ee1d1d6cbaa69365a9ec\build/generators\deactivate_conanbuildenv-release-x86.bat
Configuring environment variables
[ 25%] Building C object CMakeFiles/headland.dir/2baab7841d12fc4975c1b03d0e83f6af/variants/common/efg_H2M2S2_platform/headland/source/HDL_management.c.obj
[ 50%] Building C object CMakeFiles/headland.dir/2baab7841d12fc4975c1b03d0e83f6af/variants/common/efg_H2M2S2_platform/headland/source/HDL_mgtContext.c.obj
[ 75%] Building C object CMakeFiles/headland.dir/2baab7841d12fc4975c1b03d0e83f6af/variants/common/efg_H2M2S2_platform/headland/source/HDL_private.c.obj
[100%] Linking C static library libheadland.a
[100%] Built target headland
Headland/0.1: Package '210375de6cfaa2628183ee1d1d6cbaa69365a9ec' built
Headland/0.1: Build folder C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\build\210375de6cfaa2628183ee1d1d6cbaa69365a9ec\build/Release
Headland/0.1: Generated conaninfo.txt
Headland/0.1: Generated conanbuildinfo.txt
Headland/0.1: Generating the package
Headland/0.1: Package folder C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\package\210375de6cfaa2628183ee1d1d6cbaa69365a9ec
Headland/0.1: Calling package()
Headland/0.1: CMake command: cmake --install "C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\build\210375de6cfaa2628183ee1d1d6cbaa69365a9ec\build/Release" --prefix "C:/Users/h.yadav/.conan/data/Headland/0.1/_/_/package/210375de6cfaa2628183ee1d1d6cbaa69365a9ec"
Capturing current environment in C:\Users\h.yadav\.conan\data\Headland\0.1\_\_\build\210375de6cfaa2628183ee1d1d6cbaa69365a9ec\build/generators\deactivate_conanbuildenv-release-x86.bat
Configuring environment variables
-- Install configuration: "Release"
Headland/0.1 package(): WARN: No files in this package!
Headland/0.1: Package '210375de6cfaa2628183ee1d1d6cbaa69365a9ec' created
Headland/0.1: Created package revision b7e6261181a9cf6b1d4b17bc50ef9410

**Comment by himansu2906** [comment]
Hi @memsharded,

do you have any update on above question regarding no ".a files" being generated in package folder.

**Comment by memsharded** [comment]
yes, the build executed by the ``build()`` method happens in a "build" folder in the cache.
The ``package()`` method has the responsibility of copying the desired package artifacts from the "build" folder to the "package" folder. This can be done in different ways:
- With something like ``CMake()`` install method ``cmake.install()`` in the ``package()`` method, if the CMakeLists.txt contains correct install instructions
- With ``from conan.tools.files import copy`` and explicit ``copy(self, ...)`` calls inside ``package()`` method.

**Comment by maitrey** [comment]
Hello @memsharded , 
Sorry for hijacking your issue.
We use the same compiler , 
Do you see any potential issues if we define the profiles like this:
`target_host=C:/hightec_ifx/bin/tricore
standalone_toolchain=C:/hightec_ifx/
cc_compiler=tricore-gcc

[settings]
os=RTAOS
arch=tc39xx
arch_build=x86_64
compiler=tricore-gcc
build_type=Release

[env]
PATH=[$standalone_toolchain/bin]
CC=$target_host-gcc.exe
LD=$target_host-gcc.exe
AR=$target_host-ar.exe
AS=$target_host-as
RANLIB=$target_host-ranlib
STRIP=$target_host-strip
CFLAGS=-O2 -g -W -Wall -Wcast-align -Wcast-qual -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wfloat-equal -Wredundant-decls -Wstrict-prototypes -Wundef -Wunsuffixed-float-constants -mversion-info -Wmissing-declarations -Winline -Werror-implicit-function-declaration -Wno-bad-function-cast -Wsign-compare -finline -mcpu=tc39xx -maligned-data-sections -fmessage-length=0 -fno-builtin-memcpy -fno-builtin-memcmp -fno-builtin-memset -fno-builtin-strlen -fno-common
LDFLAGS=-lgcc -mcpu=tc39xx -mfixed-sda -Wl,-r -nostdlib -Wl,--cref -Wl,-no-demangle,-demangle=none -Wl,--extmap=a -ferror-numbers 

[conf]
tools.cmake.cmaketoolchain:generator=MinGW Makefiles`

One more additional question would be : How are profiles handling absolute and relative linking ?  Thanks in advance for answering my question. Its probably even a cmake question as LDFLAGS is an environment variable in cmake.

**Comment by memsharded** [comment]
I don't see any apparent issue, if it works for you, besides using the legacy ``[env]`` management instead of the new integrations, that you should use to be 2.0 ready:
- New environment management via ``[buildenv]`` and ``VirtualBuildEnv``
- New passing of flags to new generators like CMakeToolchain, there is new ``conf`` like ``tools.build:cflags``. In this case if only using this compiler, the environment ``[buildenv]`` could work.

Check https://docs.conan.io/en/latest/reference/conanfile/tools.html for more info

**Comment by maitrey** [comment]
It so far works for me . Actually sometime back in another issue, I requested to update the documentation for build env and runtime env which was mentioned as new feature in 2.0. See here:  https://github.com/conan-io/conan/issues/11499#issuecomment-1165447155 . And I still cannot find it. Perhaps I am missing checking , could you please be kind to forward me the exact link ?

**Comment by memsharded** [comment]
Yes, we are going to add some more docs for exactly this in 1.52 release soon.

**Comment by maitrey** [comment]
Sorry to bother you again : One more additional question would be : How are profiles handling absolute and relative linking ? Thanks in advance for answering my question. Its probably even a cmake question as LDFLAGS is an environment variable in cmake. We have both absolute linking and relative linking as we have execute in place microcontroller.

**Comment by memsharded** [comment]
> How are profiles handling absolute and relative linking ? Thanks in advance for answering my question. Its probably even a cmake question as LDFLAGS is an environment variable in cmake. We have both absolute linking and relative linking as we have execute in place microcontroller.

This is not something handled by profiles, it depends on compiler, build systems, etc. Note that CMake does not necessarily always listen to env-vars (maybe only with Makefiles generators?). You can define user ``conf`` if you need it, or maybe it is something that you want to create custom settings to model it, and then pass that setting to your build scripts. But Conan doesn't have anything built-in for it.

**Comment by memsharded** [comment]
Closing this ticket as outdated and inactive, please create new tickets against latest Conan 2.X if necessary for any further question or issue. Thanks for your feedback.
