### ISSUE TITLE
Python Base class version conflict leads to error.

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#11685]
Python Base class version conflict leads to error.

We get following error in our pipelines when installing dependencies. For one dependency we get following error.

Error loading conanfile at '/<conan package cache dep ref>/export/conanfile.py': Conflict in py_requires conan-base/1.0.0@ci/tools - conan-base/1.2.0@ci/tools

Does it mean that the whole dependency tree must use the very same python base class in all recipes of the tree?

### Environment Details (include every applicable attribute)
  * Linux
  * 3.8
  * Conan client 1.48

### Steps to reproduce (Include if Applicable)
Run a a Conan install command with certain dependencies that all have a

python_requires = "conan-base/<version>@ci/tools"
python_requires_extend = "conan-base.Base"

**Comment by memsharded** [comment]
Hi @MTomBosch 

It seems your issue is incomplete, can you please provide more details to reproduce.
Conan packages can have different ``python_requires``, in the same graph, that is not an issue, this test  works:
```python
def test_different_versions_used():
    c = TestClient()
    c.save({"conanfile.py": GenConanfile("tool", "1.0")})
    c.run("export .")
    c.save({"conanfile.py": GenConanfile("tool", "1.1")})
    c.run("export .")
    conanfile = textwrap.dedent("""
        from conan import ConanFile
        class Pkg(ConanFile):
            name = "depa"
            version = "1.0"
            python_requires = "tool/1.0"
        """)
    c.save({"conanfile.py": conanfile})
    c.run("create .")
    conanfile = textwrap.dedent("""
        from conan import ConanFile
        class Pkg(ConanFile):
            name = "depb"
            version = "1.0"
            python_requires = "tool/1.1"
            requires = "depa/1.0"
        """)
    c.save({"conanfile.py": conanfile})
    c.run("create .")
    print(c.out)
```
It is possible that you have conflicting transitive ``python_requires`` dependencies, but much more detail is needed. Please try to provide a reproducible case for it, thanks.

**Comment by MTomBosch** [comment]
Unfortunately the issue is no more appearing at the moment. But the hint with conflicting transitive python_requires dependencies makes sense and we will try to enforce the problem using such a setup.

**Comment by memsharded** [comment]
Ok, then I think we can close it at the moment.

The general recommendation for ``python_requires`` is to keep them as simple as possible. Avoid multiple inheritance, avoid transitive python_requires, etc.

**Comment by MTomBosch** [comment]
Fair enough.
