### ISSUE TITLE
[question] How to modify the default directory of Binary Packages?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#11690]
By default, Conan will install or build packages into `C:\.conan` directory on Windows. 

However, `C:\` drive is usually the **SYSTEM DISK**, which might not have enough memory spaces. Besides, the total size of **BINARY PACKAGES** are extremely **HUGE**. Take mine for example. It is about **52.2 GB**.

Therefore, I want to modify it to somewhere else, for example `D:\.conan`. How to do it?

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/180415432-8c72a8a7-2425-40d5-af6a-f1eb8df5e4e0.png)
![image](https://user-images.githubusercontent.com/71438617/180416342-d2cf51ec-af6c-4a06-b19f-f4b289f0f198.png)

**Comment by memsharded** [comment]
You can use CONAN_USER_HOME and CONAN_USER_HOME_SHORT to specify the folders: https://docs.conan.io/en/latest/reference/env_vars.html?highlight=conan_user_home#conan-user-home

Yes, folders can be big, if your compiled binaries are big.
