### ISSUE TITLE
[question] Pass a PATH to be used by consumer

### ISSUE THREAD

**Issue by Facon** [conan-io/conan#11699]
I would like to now how can I pass a path to some executables from an installed packaged.

Let's say that I have installed a package AAA that contains the following structure:
.conan/data/AAA/1.0/\_/\_/package/_HASH_/
├───tools
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└───linux
├───include
└────lib
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└───linux
.conan/data/AAA/1.0/\_/\_/package/_HASH2_/
├───tools
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└───windows
├───include
└────lib
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└───windows

The package can be used as normal, but I would like to now how the consumer can use the tools inside the tools folder for CMake's add_custom_command.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Facon 

With new tooling is:
```python
def package_info(self):
     self.buildenv_info.append_path("PATH", <path>)
     # where path can do os.path.join(self.package_folder, ...) for example
```
Then on the consumer side, use the ``VirtualBuildEnv`` generator.
That would add that to the path, which will be in a file that you (as developer) can activate or source, and that Conan will automatically use in the ``self.run(...)`` commands.
