### ISSUE TITLE
[feature] New CMake helper variable definitions

### ISSUE THREAD

**Issue by db4** [conan-io/conan#11694]
Standard CMake helper defines a number of variables like CONAN_EXPORTS, CONAN_IN_LOCAL_CACHE etc. that I use in my projects. Now I'm trying to switch to CMake transparent integration/CMakeDeps/CMakeToolchain generators so I have to use CMake helper from conan.tools.cmake. But it defines neither CONAN_EXPORTS nor CONAN_IN_LOCAL_CACHE. Is it possible to define them in the new CMake helper as well?

**Comment by memsharded** [comment]
Hi @db4 

Conan 2.0 has change a bit the design, and the criteria is that it should be possible to do exactly the same build in the user folder and in the cache. There are several mechanisms for this:
- Better representation of the layout with ``layout()`` method, and helpers like ``cmake_layout()`` to achieve the exact same relative location of files and folders. If there is something related to locations, it should be addressed with this.
- Making sure that the ``cmake`` command line receives the same arguments when called by the developer and when called by conan. So the environment has been made more explicit in ``VirtualBuildEnv`` new generator, for example, and the new flows in which ``generate()`` generate all the necessary files, that are use later in the ``build()`` method.

In the same line, there shouldn't be any distinction between building something in the cache or in the user folder. If there is some behavior that needs to be controlled explicitly for the build, like building and running tests (or not), it should use an explicit ``conf``. For example, for this case, we are using the ``conf`` called ``tools.build:skip_test``. In the same spirit, users can define any ``user.myteam.mybuilds:apply_sanitizer`` or whatever other flag that would control aspects of the build. Still, they should be applicable both for developer local builds and for builds in the Conan cache.

Please let me know if you have any question.

**Comment by db4** [comment]
@memsharded Now I understand your design goals better. Thanks.
