### ISSUE TITLE
conan search does not work with the most intuitive "pattern"

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#117]
If you do not know that you can look the syntax up with ``conan search -h``, you are pretty much lost as a beginner trying to find something:
```
$ conan search sqlite3
There are no packages matching the sqlite3 pattern
$ conan search sqlite3/*
Existing packages info:

sqlite3/3.10.2@TyRoXx/stable
    Package_ID: 755fc07adbed235a7d3eadec4b6882d4912f09bc
            (x86_64, Release, gcc, 4.8, Linux)
```
If nothing is found, the command should print some kind of help text, maybe the standard ``--help``.
Alternatively the search command could just search for individual words as I expected it. The web site already works like I would expect it: https://www.conan.io/search?q=sqlite3

**Comment by memsharded** [comment]
+1

**Comment by lasote** [comment]
Fixed and deployed!
