### ISSUE TITLE
[question] full_package_mode mode and transitive dependencies

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11704]
Hi,

I'm a bit puzzled about full_package_mode and consumers. I have two questions.

a.) If I have A->B->C, and I set full_package_mode for C within B's packageid(), does it mean that A's packageid will also be changed automatically? Or should I do full_package_mode for B in A, too?

b.) Isn't there a way to specify in the "dependee" (C) directly that whenever C is consumed by anybody it should consume C in full_package_mode (or any other mode I set for C)

Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

> a.) If I have A->B->C, and I set full_package_mode for C within B's packageid(), does it mean that A's packageid will also be changed automatically? Or should I do full_package_mode for B in A, too?

Yes, when you define a mode in a recipe ``package_id()`` it only defines how things affect to that specific package, as it doesn't make sense for the consumer (for example if A is a header only library, it doesn't mean that it should have a different package for each one of its dependencies versions varying on full_package_mode)

If you want to change things globally, you can change the defaults in ``conf``, not in recipes

> b.) Isn't there a way to specify in the "dependee" (C) directly that whenever C is consumed by anybody it should consume C in full_package_mode (or any other mode I set for C)

Only in Conan 2.0, we will introduce this possibility: https://github.com/conan-io/conan/pull/11441

**Comment by harsszegi** [comment]
Awesome, thanks a lot @memsharded
