### ISSUE TITLE
[feature] Another change to CMakePresets naming

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#11705]
Right now the CMake Preset configuration is named with a small first letter (i.e. `release`, `debug`, ...). However, `conan install` requires the first letter to be uppercase for `build_type`. This makes build scripting a lot harder.

Example:

```
conan install . -s build_type=Release
cmake --preset release
cmake --build --preset release
```

The above is inconsistent and cannot easily work with variables provided by the CI services. It would be much better if for i.e. GitHub actions we could do something like that:

```
conan install . -s build_type=${{ matrix.build_type }}
cmake --preset ${{ matrix.build_type }}
cmake --build --preset ${{ matrix.build_type }}
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
I think it is better to keep the names lowercase, when the name is composed with other settings/options (e.g `apple-clang-shared_true`)  the name is very weird and easy to mistype otherwise. 
I would say any CI scripting should have a `lowercase()` function available, otherwise an issue should be open on it.

**Comment by mpusz** [comment]
I can live with that 😉 Just wanted to ensure it was discussed.

**Comment by mpusz** [comment]
Actually it seems it is not that easy on GitHub actions: https://github.com/community/community/discussions/10553 😢

**Comment by lasote** [comment]
Yeah, upvoted. 👍🏼

**Comment by lasote** [comment]
I'm closing this for now, thanks for your help trying the presets
