### ISSUE TITLE
[question] How can a custom generator find export_sources "origin_folder"?

### ISSUE THREAD

**Issue by thorntonryan** [conan-io/conan#11717]
### Question

Is there a way for a generator to obtain the "origin_folder" / originating folder of an exported `conanfile.py` that's being processed?

The [recipe_folder](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#recipe-folder) is close, but may not be under SCM if `export_sources` is used.

Thanks for your support!

### Context
I have a custom generator that attempts to dynamically capture SCM information from custom call to `git describe` and `tools.Git()` and generate a `git-describe.cmake` file with various bits of meta data (e.g. hash, tag, dirty, commits from last tag, etc).

The goal is to drive both Conan's package version and also CMake's PROJECT_VERSION from a tag in SCM.

It's meant to be used in both a package's `set_version` and `generate` methods:
```python
def set_version(self):
    foo = mygenerator(self)
    self.version = foo.version
def generate(self):
    foo = mygenerator(self)
    foo.generate()
```

_I'm attempting to augment the basic approach outlined in the doc [How to dynamically define the name and version of a package](https://docs.conan.io/en/latest/howtos/capture_version.html)._

So, the generator would like to know the location where `conanfile.py` _originated_ from in order to leverage things like `tools.Git(folder=conanfile.recipe_folder)` on an actual repository in order to obtain git tag information.

The generator works for packages created from source using `conan create` or if using `conan install` to install the package requirements in a build folder and build outside of Conan.

However, I'm struggling to get the generator to work with packages that rely on `export_sources`.

Packages using `export_sources` fail because the package contents are copied to a temporary folder outside of SCM prior to generating, etc.

This means my custom generator receives a `conanfile.py` that lives outside of SCM, where quite obviously, `tools.Git(folder=conanfile.recipe_folder)` can't be leveraged.

### Workarounds

One idea I tried that worked was to have my generator generate the files in `set_version` and include the generated files alongside the other `export_sources`

But this seems like a Bad Idea <sup>TM</sup>.

#### 🏆 conandata.yml

I noticed that the doc for [conan.tools.files.update_conandata()](https://docs.conan.io/en/latest/reference/conanfile/tools/files/basic.html#conan-tools-files-update-conandata) has a blurb that sounds eerily similar to what I'm trying to do:

> This helper can only be used within the export() method, it can raise otherwise. One application is to capture in the conandata.yml the scm coordinates (like Git remote url and **commit**), **to be able to recover it later** in the source() method and **have reproducible recipes that can build from sources without actually storing the sources in the recipe**.

This is basically what I'm hoping to do. Capture SCM details once. And then later recover them in my generator. And then generate a *.cmake file with what I've found.

I'm betting I could smuggle information into my generator using `update_conandata` and recover it using `self.conan_data["sources"]["mydata"]`.

_Perhaps I could either smuggle the "originating" conanfile.py's path, or whatever Git details I wished to record_

I've just never seen it suggested to pass information to generators in this way, so I'm a little leery of it.

_Edit: Update_

Darn. This approach won't work because `conanfile.conan_data` seemingly isn't available inside the `generate` method. The `conandata.yml` file is produced with the right key, but I can't consume it through public Conan API.

_Edit: Update 2_
Well. This approach *will work*, but only by convention. I can have  my generator look for a `conandata.yml` and use that if it finds it, then fall back to `conanfile.recipe_folder`.

May still be preferable because at least leveraging `conan_data.yml` in this way is supported for _some_ methods. Still less than ideal, so I'm hoping there's another better solution available.

This approach seems related to:
https://github.com/conan-io/conan/issues/10926

_Edit: Update 3_

Honestly not sure what I was thinking in the first update, `conanfile.conan_data` is available inside `generate`.

See https://github.com/conan-io/conan/issues/11717#issuecomment-1198572246 for a proposed resolution.

<details>
<summary>layout</summary>

I've also wondered if maybe the new package [layout](https://docs.conan.io/en/latest/reference/conanfile/methods.html#layout) might offer a better way to describe what I'm attempting.
</details>

<details>
<summary>userinfo</summary>

By convention, I suppose could probably smuggle the "origin_folder" via [user_info](https://docs.conan.io/en/latest/reference/conanfile/methods.html#user-info).
</details>

---

Anyways, thanks for your help and support!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Just a quick clarification: When a generator of a consumer runs, there is absolutely no guarantee that there will be ``exports_sources`` of the dependencies it is using. In most cases, that folder will not exists, when packages are downloaded from servers, the ``exports_sources``, ``sources``, ``build`` folders are not even created, and sources are not downloaded.

So the only things that really make sense for consumers (and generators) are ``recipe_folder`` and ``package_folder``

**Comment by memsharded** [comment]
BTW, I know that ``conandata`` and ``recipe_folder`` are not available via the ``self.dependencies`` interface that generators should use. We will definitely add them soon.

**Comment by MariaMozgunova** [comment]
Can I take this issue?

**Comment by memsharded** [comment]
Sure, thanks @MariaMozgunova, assigned.

**Comment by thorntonryan** [comment]
Thank you for following up! I'm wondering if I've confused matters a little because of my poor framing of the problem.

> BTW, I know that conandata and recipe_folder are not available via the self.dependencies interface that generators should use. We will definitely add them soon.

Thinking about this some more. I'm not sure that would help.

Because I'm not really interested on the `conandata` for my recipes' dependencies... but on the `conandata` for the package I'm currently creating/building.

I think I would need to see `conanfile.conandata` available in the recipe's `generate` step. That way it could be fed into a custom generator at construction by passing the `conanfile`.

For example:
```
class Pkg(ConanFile):
...
def generate(self):
    foo = mygenerator(self) # <---
    foo.generate()
```
This way my generator could use conanfile.conandata for *this* conanfile (i.e. Pkg).

A custom generator is a close fit, but maybe not the best fit?

---

By way of analogy, I'm trying to create a custom generator that exposes some of the same types of information the `cmake` generator provided but are no longer present in `CMakeDeps` / `CMakeToolChain`.

The `cmake` generator provided a `CONAN_PACKAGE_NAME` / `CONAN_PACKAGE_VERSION` variables, which some of our projects use to feed into CMake's `project(${CONAN_PACKAGE_NAME} VERSION ${CONAN_PACKAGE_VERSION})`. 

This way you could build your project with the same version as the Conan package -- and thus define your version details in one place.

I'd like to extend that concept by defining our version as a git tag and dynamically feeding that into *both* Conan/CMake.

The goal is to let the git tag drive the package version and exe/library version.

---

My generator is perhaps closest in spirit to the `CMakeToolChain` generator. And I could probably even use it by setting appropriate [preprocessor_definitions](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html?highlight=cmaketoolchain#preprocessor-definitions) and adding additional [variables](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html?highlight=cmaketoolchain#variables) or [cache_variables](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#cache-variables).

But I think I'd run into the same problems. By the time the generators run, depending on what type of recipe you're using, `recipe_folder` may no longer be in a folder managed by SCM, so you couldn't use `tools.Git(folder=recipe_folder)`.

I'd have to dynamically set these additional `CMakeToolChain` properties (e.g. Git hash, tag, etc.) within `set_version` or maybe `export()`?

Doing toolchain stuff in `set_version` *seems* odd, but maybe that's the best way if I need to include dynamic information from SCM?

**Comment by thorntonryan** [comment]
> BTW, I know that conandata and recipe_folder are not available via the self.dependencies interface that generators should use. We will definitely add them soon.

Again, thank you for the gracious response!

I don't wish to cause unnecessary work. Part of me wonders if I'm trying to do something that's simply a bad fit conceptually for a Conan generator.

Maybe I should instead frame the problem as:
"How do I inject dynamic version information from `tools.Git()` into the `CMakeToolChain` generator?"

**Comment by thorntonryan** [comment]
Can't construct a `CMakeToolChain` object in `set_version` because `conf` doesn't exist. So that won't work either.

And I think I'd probably run into the same scenario -- that `set_version` runs on the originating Conanfile.py, but `generate` may not. So I don't think it's even possible to share a `CMakeToolChain` created early enough to use in `set_version` then later re-use it in `generate`.

**Comment by memsharded** [comment]
Hi @thorntonryan 

I think this is mostly about the process, that needs to run decouple in multiple stages. When packages can be consumed without sources or build at all, just consume the binaries, things need to be prepared for that.

Maybe these ideas can help:

- Whatever needs to be captured from the original source folder, what you ``git clone``, and then ``conan create``, needs to be capture in the ``export`` stage. You might use the ``export()`` and ``export_sources()`` method to extract the information that you need from the Git repo. This could be a useful example: https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature
- The ``generate()`` method runs before the build, and one of the last steps when a ``conan install`` happens. This method can recover data from the ``conan_data``, to prepare the build, create build scripts with it, etc. The ``generate()`` method responsibility is to prepare the build, and for that, it can do different "generation" tasks:
   - Get information from dependencies, so they can be located by the build, as ``CMakeDeps`` do
   - Get some files from the dependencies, maybe ``copy()`` them locally if necessary (should not be done if possible to avoid, but sometimes the only way is to copy them). This would be the replacement of the legacy ``imports()`` in Conan 2.0
   - Convert Conan configuration like ``settings`` and ``options`` into something the build system can understand, like ``CMakeToolchain`` does.
   - It could be the right place to call an automatic code generation tool that creates source code files (but note that those files do not belong to the "source" stage, but to the "build" stage.
  
 Note that this typically do not include operations over the source of the package itself. It is not the typical place to apply patches (that should be the ``source()`` method if the patch is the same for all configurations). Information about the source code, specifically meta-information about the source code, as info that comes from the Git repo containing the source code might not be available here. So it needs to be done earlier in the process, in a 2-step approach.

Please let me know if this clarifies something

**Comment by thorntonryan** [comment]
Thanks @memsharded !

> This could be a useful example: https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature

Yes. That example is very very helpful.

>  Information about the source code, specifically meta-information about the source code, as info that comes from the Git repo containing the source code might not be available here. So it needs to be done earlier in the process, in a 2-step approach.

I think I finally understand. Leveraging `conan_data` is the right path to pursue conceptually.

> This method [generate] can recover data from the conan_data

Eureka! And _that's_ the key insight.

`set_version` can leverage `tools.Git(folder=self.recipe_folder)` but not `update_conandata`

And `generate` can leverage `self.conan_data` (from user data added in `export`), but `generate` can't always use `tools.Git(folder=self.recipe_folder)`

I now see what I was doing wrong. I have to take different approaches depending on _which_ method I'm in.

I was after `conanfile.conan_data` and that *is already* defined in the `generate` step.

So I think my original question was malformed. And this issue can be closed.

Thank you for your support!

---

As a followup, what's the reason we restrict `update_conandata` to `export`?

If I could use `update_conandata` from `set_version`, then I could retrieve my SCM meta data *once*, capture it in `conandata.yml`, and then have my generator find it using `conanfile.conan_data`.

I don't actually expect my SCM details to change between `set_version` and `export`, but ideally, I was hoping to call `tools.Git().get_revision()` and friends only once if possible.

**Comment by thorntonryan** [comment]
> As a followup, what's the reason we restrict update_conandata to export?

https://github.com/conan-io/conan/blob/5251fbcabf9b84e4983db93d546999360e2b05a9/conan/tools/files/conandata.py#L11-L12

Presumably the `conanfile.export_folder` isn't yet known during `set_version` for some reason.

**Comment by memsharded** [comment]
yes, ``set_name()`` and ``set_version()`` methods should be able to run, and they do run, for ``conan install`` as a consumer, because that information might be needed for the local behavior of the ``conanfile.py`` as consumer. The ``export_folder`` is not even defined, it doesn't exist, as the recipe is just local and it is not being exported to the local cache. 

The ``update_conandata()`` operates directly on the cache copy of ``conandata.yml``. But in theory you can still modify the ``conandata.yml`` locally, before being exported. It is a yaml file, if you check the implementation of the ``update_conandata()`` it is not complex, so doing that yourself in your recipe seems doable. It is not very elegant, as it will be modified or written every time you do a ``conan install``, but it might work.

**Comment by thorntonryan** [comment]
Interesting.

It sounds like generating a `conandata.yml` locally from within `set_version` is really the only way to support building such a package through both `conan create` and `conan install`. _Since `export` isn't called during `conan install`_

My generator could then look for an accompanying `conandata.yml` file located at the `conanfile.recipe_folder`. When using `conan install`, it would find the local `conandata.yml`. And when using `conan create`, it would find the exported `conandata.yml` copy alongside the exported recipe in the `export_folder`.

Indeed, not very elegant, but it should work.

**Comment by thorntonryan** [comment]
Thanks @memsharded!

You've certainly spent a considerable amount of time helping me and walking me through the Conan workflow. I'm always amazed at how quickly the Conan dev team responds to and answers community questions. It's very very impressive. So thank you for your time and efforts! Both in developing such a quality tool, but also in engaging with and supporting the community! 

The difficulty to achieve what I'm after is perhaps telling. For more complicated libraries, we often separate producer/consumer recipes. But for simpler libraries, we often leave them combined into a single recipe.

Hosting a package recipe external to the library source code is certainly the approach conan-center takes, and also helps avoid this chicken/egg problem of dynamically obtaining/assigning SCM version details and injecting them into CMake and my package version.

Anyway, thanks again for taking the time to walk me through this!

Feel free to close this issue. I consider my question answered.

**Comment by thorntonryan** [comment]
To put a bow on this, I can do:

```diff
import os

import yaml

from conans.errors import ConanException
from conans.util.files import load, save

-def update_conandata(conanfile, data):
+def update_local_conandata(conanfile, data):
-   """
-   this only works for updating the conandata on the export() method, it seems it would
-   be plain wrong to try to change it anywhere else
-   """
-   if not hasattr(conanfile, "export_folder") or conanfile.export_folder is None:
-      raise ConanException("The 'update_conandata()' can only be used in the 'export()' method")
-   path = os.path.join(conanfile.export_folder, "conandata.yml")
+   path = os.path.join(conanfile.recipe_folder, "conandata.yml")
    if os.path.exists(path):
        conandata = load(path)
        conandata = yaml.safe_load(conandata)
    else:  # File doesn't exist, create it
        conandata = {}

    def recursive_dict_update(d, u):
        for k, v in u.items():
            if isinstance(v, dict):
                d[k] = recursive_dict_update(d.get(k, {}), v)
            else:
                d[k] = v
        return d

    recursive_dict_update(conandata, data)
    new_content = yaml.safe_dump(conandata)
    save(path, new_content)
```

And then something like:

```diff
class Pkg(ConanFile):
    def set_version(self):
        git = tools.Git(folder = self.recipe_folder)
        describe= git.run("describe --tags --long --dirty=-dirty --always --match=v*")

!       update_local_conandata(self,
            { 
                "git": {
                    "describe": f"{describe}",
                }
            }
        )   
        self.version = tag

    def generate(self):
            tc= CMakeToolChain(self)
!           tc.cache_variables["GIT_DESCRIBE"] = self.conan_data["git"]["describe"]
            tc.generate()        
```

This will work for both `conan create` and `conan install` and allow me to dynamically set both my Conan package version and also my CMake project version.

**Comment by thorntonryan** [comment]
Also, quite obviously now, the way to recover `CONAN_PACKAGE_NAME` and `CONAN_PACKAGE_VERSION` from the `cmake` generator's `conanbuildinfo.cmake` is simply:

```python
    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["CONAN_PACKAGE_NAME"] = self.name
        tc.cache_variables["CONAN_PACKAGE_VERSION"] = self.version
        tc.generate()
 ```

**Comment by memsharded** [comment]
Yes, you are right. Just a clarification, if you are only using it to asign the ``self.version``, this doesn't need to go to the ``conandata`` too. The ``set_version`` only executes locally, and at ``export`` time. Once it is in the cache, the version ``self.version`` will be the correct one, because the ``set_version()`` will not be executed and the version will be recovered from the cache metadata instead. So if it is just the version, no need to add it to the ``conandata.yml`` at all.

Thanks for your kind words, we love to help! :)
