### ISSUE TITLE
Revise flow for package source development

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1171]
There are some requests asking for best practices about how to develop source code of packages, and flows will be different if using ``source()`` or ``exports_sources``. I think this issue deserves more attention, not sure if in code, or in documentation.

As an example @jmmut suggest (https://github.com/conan-io/conan/issues/1168#issuecomment-290977750) that the default ``build()`` method created in the ``conan new`` command might not work for development and local ``conan build`` command, while the next works:

```python
 def build(self):
        cmake = CMake(self.settings)
        cmake.configure(self, source_dir=self.conanfile_directory, build_dir="./")
        cmake.build(self)
```
Probably, it deserves changing the ``conan new`` template.

**Comment by sixten-hilborn** [comment]
Hi, minor note: `source_dir` does not need to be specified as the default value is `conanfile_directory`.
Explicitly using source_dir was a workaround to avoid a warning message (#711 which has now been fixed).
I propose this form as the "default" for test_package:
 ```python
def build(self):
    cmake = CMake(self.settings)
    cmake.configure(self, build_dir=".")
    cmake.build(self)
```

Changing `configure` to use build_dir="." as default would make this `build()` method even more compact, however I'm not convinced that is a good idea.

I also think this should be considered (passing self to CMake's constructor):
 ```python
def build(self):
    cmake = CMake(self)
    cmake.configure(build_dir=".")
    cmake.build()
```

**Comment by memsharded** [comment]
Starting checking this. There are 2 scenarios:
- Recipe inside code repo
- Recipe in its own repo.

Some initial observations:
- The local ``conan source`` method might be useful to clone exactly the same starting point. 
- The ``export`` part of the ``conan source`` is unnecessary and even annoying. We don't want to move sources around in user spaces
- The local ``conan package`` might require an extra parameter, so it can manage to address both the recipe directory and the build directory, and they don't need to be the same.
- It is necessary to modernize the recipe generated with ``conan new`` using the new ``cmake.configure()``, and ``self.conanfile_directory``.
- The recipe in its own repository has the problem that it cannot address the source code (as ``conanfile_directory`` will point to the recipe, but the user could probably clone the source in a sibling folder. Maybe some ``self.build_directory`` or ``self.source_folder`` (related to https://github.com/conan-io/conan/issues/350), makes sense.
