### ISSUE TITLE
"private" requirements propagated

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1172]
While waiting for the `build_requires` feature (#1141), I'm trying a workaround based on `private` requirements.

I set up the simplest test I could to make sure it worked, and I can't see where adding `private` makes any difference at all.

I made three packages with `conan new`: `pkg1`, `pkg2`, and `pkg3`.  So `pkg2` requires `pkg1` with `private=True`, and `pkg3` requires `pkg2` normally (or privately--doesn't make a difference).  I would expect that `pkg1` does not propagate to `pkg3`, but it does.

I tried both syntax variants for requirements in `pkg2`'s conanfile.py:

      requires = (('pkg1/1.0@jharris/testing', 'private'),)

and

      def config(self):
            self.requires('pkg1/1.0@jharris/testing', private=True)

But the `private` attribute has no efffect that I can tell:

```
conan install pkg3/1.0@jharris/testing
pkg1/1.0@jharris/testing: Not found, looking in remotes...
pkg1/1.0@jharris/testing: Trying with 'dv-moneycore-conan'...
ERROR: Unable to find 'pkg1/1.0@jharris/testing' in remotes
```

```
conan info pkg3/1.0@jharris/testing
pkg1/1.0@jharris/testing
    ID: 836a3c2c8def6b3df97cf8910d95331724750f45
    BuildID: None
    Remote: None
    URL: <Package recipe repository url here, for issues about the package>
    License: <Put the package license here>
    Updates: Version not checked
    Creation date: 2017-04-03 07:45:07
    Required by:
        pkg2/1.0@jharris/testing
pkg2/1.0@jharris/testing
    ID: 297cd6714f77c3b9046c4573235dd44a3f94ae60
    BuildID: None
    Remote: None
    URL: <Package recipe repository url here, for issues about the package>
    License: <Put the package license here>
    Updates: Version not checked
    Creation date: 2017-04-03 07:45:13
    Required by:
        pkg3/1.0@jharris/testing
    Requires:
        pkg1/1.0@jharris/testing
pkg3/1.0@jharris/testing
    ID: 250e1f4d56dad6f34dc74674691f4fc42d1713eb
    BuildID: None
    Remote: None
    URL: <Package recipe repository url here, for issues about the package>
    License: <Put the package license here>
    Updates: Version not checked
    Creation date: 2017-04-03 07:46:39
    Required by:
        None
    Requires:
        pkg2/1.0@jharris/testing
```

**Comment by memsharded** [comment]
Yes, this is a known behavior of "private" requirements. The recipes are always retrieved. "private" means basically:
- It the package binary exists, then the dependency binary will not be retrieved nor built.
- Build information (include dirs, libraries, flags) is not propagated downstream
- They are not overriden by downstream dependencies
- Different versions/username-channel might exist in the same dependency graph if they are private.
I think the private requirements will be superseded by the [build_requires] feature, so far it looks really promising.

**Comment by claasd** [comment]
Hi,
it seems that the private requirements are also taken into account when creating the package id. Is this correct?

**Comment by memsharded** [comment]
Yes, they are. A private header embedded in a consumer .cpp definitely changes the binary, so even if private, it affects the package ID. 
Just in case, because private requirements are largely considered for build tools, have you checked the new ``build_requires``?

**Comment by claasd** [comment]
The build_requires are only possible to set at the user's machine, right? In this case, they do not serve my purpose.

Of course the private dependencies should affect the package id. My problem is with private dependencies in a dependency chain.
I will open an new ticket for it.

**Comment by memsharded** [comment]
Yes, they are defined at the user's machine, because they are intended for toolchains, dev tools, etc, that are supposed to be orthogonal to the package main responsibilites, so they are plugged-in by consumers at will.
