### ISSUE TITLE
[feature] add cli_args to cmake.configure()

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#11725]
I want to be able to add --trace to the cmake arguments during configure, to try and debug a recipe problem.

ie cmake.configure(cli_args="--trace")

The old cmake tools had "args",
the new cmake has cli_args, but only for cmake.build().

**Comment by memsharded** [comment]
This specific feature, controlling the verbosity of build systems, won't be in arguments in recipes, it doesn't make sense to hardcode it. It will be passed via ``conf``.

**Comment by AbrilRBS** [comment]
Closing this as solved:
* CMake integration functions now all have a `cli_args` argument to pass arbitrary arguments
* `tools.build:verbosity` and `tools.compilation:verbosity` confs allow to set the verbosity directly from the conf

Hope this is useful for your user-case :)
