### ISSUE TITLE
[question] cmake_find_package_multi cant't generate xxxVersion.cmake with Version Number?

### ISSUE THREAD

**Issue by crystalsky** [conan-io/conan#11724]
- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I Want Use Some package with cmake command :  find_package(xxx version CONFIG REQIRED) in project
Some Follows Blow:
1. use the conan create command to create library , to create package and upload the package to artifactor
2. I modify the conanfile.txt and add the reqires
3. Then , In the another project, I Use conan install with with generator cmake_find_package_mutli
4. some reqired package with file xxxConfigVersion/xxxCOnfig/xxxTargets.cmake are generate in the build directory
5. so I create the cmakelist.txt To Find the package with version varible
6. cmake error:  Could not find a configuration file for package "xxx" that exactly matches requestd version "x.x.x"
7. So I see the package xxxConfigVersion.cmake: set(PACKAGE_VERSION "None")
8. This problem has not happen in gtest/glog package which has the version num in the configverson.cmake
9. what i should do to fixed this problem??????

-

**Comment by memsharded** [comment]
Hi @crystalsky 

The ``cmake_find_package_multi`` is deprecated, use ``CMakeDeps`` generator, and it will generate the ``xxxxVersion.cmake`` file.

**Comment by crystalsky** [comment]
thanks , It works ok......
1. I found the CMakeDeps will generate the package cmake files to the buildfolder/generators
2. This folders is auto create by conan
3. How to modify the folder of the CMakeDeps Generator?
