### ISSUE TITLE
[question] CMakeDeps Folder Is Auto Create? How Can I Config The Output Folder?

### ISSUE THREAD

**Issue by crystalsky** [conan-io/conan#11737]
- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

- I found the CMakeDeps will generate the package cmake files to the buildfolder/generators
- This folders is auto create by conan
- How to modify the folder of the CMakeDeps Generator?

**Comment by memsharded** [comment]
Hi @crystalsky 

Change it in the ``layout()`` method of the consuming ``conanfile.py`` https://docs.conan.io/en/latest/developing_packages/package_layout.html#package-layout

**Comment by memsharded** [comment]
Closing this question as responded, please re-open or create a new ticket if necessary.
