### ISSUE TITLE
Can I change the user/channel of requirement when using "conan copy"

### ISSUE THREAD

**Issue by liao-zhihan** [conan-io/conan#11738]
Hello, I  am now using Conan (version 1.38) to mange my C++ library. 
In my project, there are some libraries which are stored in "user1/stable", but now I want to change it to "user2/stable" for some special reason.
According to the doc of Conan, I tried the "conan copy" command to change the "user" of my packages and upload them to conan-remote, but I found this command did not change the "user" information of the required package (lib_E/xx@user2/stable is still require lib_F/xx@user1/stable).
So, is there any way that can update the user/channel of the required package info and need not to do a rebuild?

**Comment by memsharded** [comment]
Hi @liao-zhihan 

Please do not use the ``conan copy`` anymore. It has already been removed from Conan 2.0 and is discouraged in Conan 1.X. What you are seeing, that the ``requires`` are not automatically renamed, is one of undesired side effects of this rename.

The way to approach this is:
- Packages are immutable, and package names are immutable. You can use user/channel, but that name last forever, you cannot change it.
- The way to run "promotions" of stages is to setup several server repositories, like the "staging" repository, and the "develop" repository. When package sin the staging repository are ready, they can be copied to the "develop" repository, but with the exact same name, user and channel.

**Comment by liao-zhihan** [comment]
Thanks for your quick reply!
I think the second suggestion can solve my problem.
