### ISSUE TITLE
[bug] Conan 1.51 breaks tools.SystemPackageTool()

### ISSUE THREAD

**Issue by db4** [conan-io/conan#11736]
### Environment Details (include every applicable attribute)
  * Docker image: conanio/gcc8
  * Conan version: 1.51

After upgrading to Conan 1.51 all recipes that use `tools.SystemPackageTool()` fail to update/install system packages. For example (trying to build wxwidgets/3.1.5@bincrafters/stable):
```
xorg/system: ERROR: while executing system_requirements(): System requirements: 'libfontenc-dev, libxaw7-dev, libxkbfile-dev, libxmu-dev, libxmuu-dev, libxpm-dev, libxres-dev, libxss-dev, libxt-dev, libxtst-dev, libxv-dev, libxvmc-dev, libxcb-render-util0-dev, libxcb-xkb-dev, libxcb-icccm4-dev, libxcb-image0-dev, libxcb-keysyms1-dev, libxcb-xinerama0-dev, xkb-data, uuid-dev' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'
ERROR: Error in system requirements
```
I believe it's a bug: `tools.system.package_manager:mode` should affect only new `conan.tools.system.package_manager`, not old `tools.SystemPackageTool()`. For the latter we already have `CONAN_SYSREQUIRES_MODE` environment variable (set to `enabled` in  my case)

**Comment by czoido** [comment]
Hi @db4,

The Conan Center Index [xorg recipe](https://github.com/conan-io/conan-center-index/tree/master/recipes/xorg) was recently migrated to new `conan.tools.system.package_manager` that's why you need to set that configuration. Please, try yo set `tools.system.package_manager:mode=install` and check if that works.

Depending on the configuration of your platform, you may also need to use `tools.system.package_manager:sudo` to install with sudo. 

Please, [check the docs](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#new-tools-for-managing-system-package-managers) about the changes introduced by these tools.

Hope this helps.

**Comment by db4** [comment]
@czoido Thanks for the reply. Many recipes (including CCI) still use `tools.SystemPackageTool()`. Immediate switch to `conan.tools.system.package_manager` is not an option. Why break old functionality? BTW, [SystemPackageTool docs](https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool) don't mention that it now relies on `tools.system.package_manager:mode` and `tools.system.package_manager:sudo` settings.

**Comment by czoido** [comment]
Hi @db4,
[SystemPackageTool](https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool) is not relying in those variables, `tools.system.package_manager:mode` and `tools.system.package_manager:sudo` are just affecting `conan.tools.system.package_manager`. If you are using some recipes with `SystemPackageTool` and others with `conan.tools.system.package_manager`, you should define both the environment variables that affect `SystemPackageTool` and the conf that affect `conan.tools.system.package_manager`, but be aware that the new ones don't affect the current ones and viceversa.

**Comment by db4** [comment]
Ahh, sorry. Indeed, that's CCI xorg recipe that needs new package manager and new settings. Closing the issue.
