### ISSUE TITLE
[question] What is difference between "Requirements" and "Dependencies"?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#11758]
One of our pipelines failed because a dependency package binary could not be found. The message looked like this:

```
ERROR: Missing binary: lib/latest@ci/baselines:67705c48ea367aead5d27983ade6f563eb1abcde
lib/latest@ci/baselines: WARN: Can't find a 'lib/latest@ci/baselines' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, compiler=gcc, compiler.cppstd=14, compiler.libcxx=libstdc++, compiler.version=9.3
- Options: ...
- Dependencies: core-types/latest@ci/baselines, json-parser-lib/2.0.0@vrte-ci/stable
- Requirements: core-types/latest, json-parser-lib/2.Y.Z
- Package ID: 67705c48ea367aead5d27983ade6f563eb1abcde
```

Now I am wondering what the difference here is between the "Dependencies" and the "Requirements".

**Comment by czoido** [comment]
Hi @MTomBosch,

The main difference is that the Requirements are expressed in the form that they are used for the package ID calculation, so if you change the package_id_mode from `semver_direct_mode` to other modes like `major_mode`, `recipe_revision_mode`, etc. you will get the same dependencies but the requirements will appear in a different form.

**Comment by MTomBosch** [comment]
Thank you.
