### ISSUE TITLE
[feature] Provide a GUI program for Conan.

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#11757]
### Feature Request

Provide a GUI program, for example `conan-gui`, for users to install/uninstall packages or do other operations. 

Just like CMake, we can use either [`cmake`](https://cmake.org/cmake/help/latest/manual/cmake.1.html) or [`cmake-gui`](https://cmake.org/cmake/help/latest/manual/cmake-gui.1.html) to compile the source codes. After all, GUI is more friendly than CLI in some situations.

**Comment by czoido** [comment]
Hi @hwhsu1231,

We don't have this in the roadmap in the short/mid term as we are really busy developing Conan 2.0 and that feature has not been demanded a lot by the community. Just as a note, as we are documenting the Conan API in 2.0 it should be easier to do a GUI wrapper around Conan functionalities... so maybe some contributor that wants that feature too is eager to contribute something like that as an external tool in the future...

Anyway, thanks a lot for the suggestion!

**Comment by memsharded** [comment]
User @markfinal created https://pypi.org/project/cruiz/1.3.2/
Check https://github.com/markfinal/cruiz
