### ISSUE TITLE
[question] 2.0 Recipes

### ISSUE THREAD

**Issue by beenjohn** [conan-io/conan#11751]
Is there somewhere to see 2.X recipes? I'm converting some internal projects to use 2.X, but some examples of the current gold standard would be greatly beneficial. Preferably one that uses autotools.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @beenjohn,

There are some recipes that have been modernized in Conan Center Index, and for example I can confirm that the [fmt](https://github.com/czoido/conan-center-index/tree/master/recipes/fmt) recipes is compatible with both 2.0 and 1.x.

Also, we have a fork where we are porting some recipes to 2.0 to be used in the new documentation we are writing. In that fork there are some recipes that have been migrated:

- [base64](https://github.com/czoido/conan-center-index/tree/master/recipes/base64)
- [egl](https://github.com/czoido/conan-center-index/tree/master/recipes/egl)
- [fmt](https://github.com/czoido/conan-center-index/tree/master/recipes/fmt)
- [gtest](https://github.com/czoido/conan-center-index/tree/master/recipes/gtest)
- [nasm](https://github.com/czoido/conan-center-index/tree/master/recipes/nasm)
- [strawberryperl](https://github.com/czoido/conan-center-index/tree/master/recipes/strawberryperl)
- [zlib](https://github.com/czoido/conan-center-index/tree/master/recipes/zlib)

**base64** and **nasm** use the 2.0 [Autotools tools](https://docs.conan.io/en/2.0/reference/tools/gnu.html).

Those packages are uploaded to a Conan repository that you can add by doing:

```
conan remote add conanv2 https://conanv2beta.jfrog.io/artifactory/api/conan/conan --index 0
```

For more information about 2.0 recipes, please check:
- [Conan migration guide to v2](https://docs.conan.io/en/latest/conan_v2.html)
- [Conan documentation for 2.0](https://docs.conan.io/en/2.0/index.html)
- We also talked about the 2.0 documentation structure in the latest release blogpost. You can have a look [here](https://blog.conan.io/2022/07/14/New-conan-release-1-50.html).

Hope this helps.

**Comment by beenjohn** [comment]
That helps a ton. Thank you!

**Comment by paulharris** [comment]
Hi @czoido, I had a problem building nasm with the msvc compiler (rather than Visual Studio) because of a compiler test within the recipe.

I thought I'd upgrade the package to conan v2, but I see in here the upgrade has already been done to the recipe... somewhere?
