### ISSUE TITLE
[feature] Backport support for `remotes.json` in conan config install to 1.X

### ISSUE THREAD

**Issue by stefansli** [conan-io/conan#11777]
Would it be possibel to backport support for installing a `remotes.json` to 1.X?
I'd suggest to allow `remots.json` files to be present but only if `remotes.txt` doesn't exist aswell. So one could only use either of them. Would that work? Or does that break some kind of backward compatibility?

In my opinion such a feature would be great so the same conan config can be used for both 1.X and 2.0

It would also provide more flexibility for users that already use multiple repositories for different "stages" of a recipe.

_Originally posted by @vectorsli in https://github.com/conan-io/conan/issues/10580#issuecomment-1200912221_

**Comment by franramirez688** [comment]
Hi @vectorsli 

Thanks for the issue.
I tend to say that it's not going to be possible because of maintainability issues (new tests, new possible bugs, breaking changes, etc.). Anyway, let me discuss it with the team.

**Comment by memsharded** [comment]
Backport in https://github.com/conan-io/conan/pull/11936 merged, so this will be in next 1.52
