### ISSUE TITLE
[bug] transitive dependencies missing in `cmake_find_package_multi` if direct dependency recipe based on conan v2 and no components

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11789]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Montery
  * Compiler+version: AppleClang 13
  * Conan version: 1.51.0
  * Python version: 3.9.13

### Steps to reproduce (Include if Applicable)

- Create a conan v2 recipe foo with:
  - CMakeToolchain, CMakeDeps, cmake_layout
  - at least one dependency bar
  - No components in package_info() (just one lib basically), and no explicit self.cpp_info.requires
- In this recipe, create a test_package based on `cmake_find_package_multi`
- call conan create . foo/version

You should see that config file of foo lacks bar injection.
If you use CMakeDeps in test_package instead of cmake_find_package_multi, you can see bar in foo config file.
If self.cpp_info.requires in foo recipe is explicitly populated with bar::bar, then foo config file generated by cmake_find_package_multi is fine.

see https://github.com/conan-io/conan-center-index/pull/12063#issuecomment-1206317836 or https://github.com/conan-io/conan-center-index/pull/12030#issuecomment-1205252247

**Comment by franramirez688** [comment]
Hi @SpaceIm 

Thanks for the issue! This one would be already solved by https://github.com/conan-io/conan/pull/11790.
Now, the `bar` dependency appears as expected:

```cmake
# Library dependencies
include(CMakeFindDependencyMacro)

if(NOT bar_FOUND)
    if(${CMAKE_VERSION} VERSION_LESS "3.9.0")
        find_package(bar REQUIRED NO_MODULE)
    else()
        find_dependency(bar REQUIRED NO_MODULE)
    endif()
else()
    message(STATUS "Dependency bar already found")
endif()
```
This fix will be soon in 1.51.1.
