### ISSUE TITLE
[bug] Recipe based on `conan.tools.cmake.CMake` don't support `conan create -kb`

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11785]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Montery
  * Compiler+version: AppleClang 13
  * Conan version: 1.51.0
  * Python version: python 3.9.13

### Steps to reproduce (Include if Applicable)

- checkout https://github.com/conan-io/conan-center-index/pull/12049 implementing conan v2 to aaplus recipe
- run `conan create . aaplus/2.41@` => OK
- then run `conan create -kb . aaplus/2.41@` => it fails

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
aaplus/2.41: Won't be built as specified by --keep-build
aaplus/2.41: Building your package in /Users/spaceim/.conan/data/aaplus/2.41/_/_/build/fda1365e7d041895647cf341d9a0f9fe5cf32361
aaplus/2.41: Generated conaninfo.txt
aaplus/2.41: Generated conanbuildinfo.txt
aaplus/2.41: Generating the package
aaplus/2.41: Package folder /Users/spaceim/.conan/data/aaplus/2.41/_/_/package/fda1365e7d041895647cf341d9a0f9fe5cf32361
aaplus/2.41: Calling package()
ERROR: aaplus/2.41: Error in package() method, line 89
	cmake = CMake(self)
	TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/issues/11785 to be released soon in 1.51.1
