### ISSUE TITLE
[bug] Cryfs claims mount is successful yet fails to mount - no error

### ISSUE THREAD

**Issue by gr211** [conan-io/conan#11782]
```
cryfs ~/encrypted-cryfs ~/Documents/pcloud-clear

CryFS Version 0.11.2

Password: 
Deriving encryption key (this can take some time)...done

----------------------------------------------------
Filesystem configuration:
----------------------------------------------------
- Filesystem format version: 0.10
- Created with: CryFS 0.10.0
- Last opened with: CryFS 0.11.2
- Cipher: aes-256-gcm
- Blocksize: 16384 bytes
- Filesystem Id: D26FF40381A234F63C47994090CE5D07
----------------------------------------------------

Mounting filesystem. To unmount, call:
$ cryfs-unmount "/home/xxx/Documents/pcloud-clear"
```

then

```
cryfs-unmount /home/xxx/Documents/pcloud-clear

CryFS Version 0.11.2
Unmounting CryFS filesystem at "/home/rgallet/Documents/pcloud-clear".
Error: Could not unmount filesystem
```

I tried with a new directory and mount point. Also tried with compiled-from-source cryfs. Same results.

I'm running arch linux. The commands I issue have no changed. But obviously Arch is a rolling distro, so something there must have broken it. Yet it is not something cryfs seems to notice.

**Comment by czoido** [comment]
Hi @gr211,

Could you please explain how is this related with Conan? It seems a problem in the cryfs tool?

Thanks!

**Comment by gr211** [comment]
ho my bad, was late. :-( apologies

**Comment by czoido** [comment]
> ho my bad, was late. :-( apologies

No worries! 😄

**Comment by Goblin80** [comment]
For future reference:

after examining `journalctl`, it happens to be a problem with the locale 

```
cryfs[XXXXX]: Crashed: locale::facet::_S_create_c_locale name not valid
```
Make sure to `export LC_ALL=en_US.UTF-8;` in your .bashrc
