### ISSUE TITLE
[question] conan v2: Shallow clone with conan.tools.scm.Git

### ISSUE THREAD

**Issue by Corristo** [conan-io/conan#11797]
With the conan v1 `scm` feature it was possible to perform a shallow clone, which can save quite a lot of time when cloning a large repository such as llvm or chromium. Is there a way to do the same with the new `Git` tool?

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @Corristo,

Thanks a lot for the feedback, I agree this is a valid feature for the git tool. I'm marking this as a feature and assign to 1.52 milestone.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/11921, will be in 1.52.

**Comment by Corristo** [comment]
Wow that was quick. Thank you very much.
