### ISSUE TITLE
[feature] conan v2: provide a simple method to delete settings in `configure()`

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11792]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

According to https://docs.conan.io/en/1.51/migrating_to_2.0/recipes.html#settings, in conan v2 we have to protect deletion of settings in `configure()` with try/except.
It's not very elegant, and might become really ugly in complex recipes. I don't know what the is type of a `settings`, but maybe add a member function allowing something like `self.settings.del_safe("compiler.libcxx")`?

And at least for C recipes, some helper function to only keep pure C stuff from settings.compiler would be helpful and more elegant: `self.is_pure_c()`?

**Comment by lasote** [comment]
Please, read my comments at https://github.com/conan-io/conan/issues/11802 
Both are very similar questions.

**Comment by SpaceIm** [comment]
closed by https://github.com/conan-io/conan/pull/12094
