### ISSUE TITLE
[feature] Implement `get_safe` in develop for self.info objects

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#11802]
In Conan 2.X there is `get_safe` over `self.info.settings` and `self.info.options` but there is not in Conan 1.X.
It is needed when, for example, there is a `header_only` option and you need to check in the validate some stuff.

Related https://github.com/conan-io/conan/issues/11786

**Comment by uilianries** [comment]
Labels bug, type: feature

![bug](https://user-images.githubusercontent.com/4870173/183413984-ad806d60-17e8-4000-b3f3-c6835bf2b962.jpg)

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/11803
