### ISSUE TITLE
[bug] wrong install command for the Chocolatey system package manager

### ISSUE THREAD

**Issue by todorico** [conan-io/conan#11808]
The Chocolatey SystemPackageManager install command should use  `{tool} install --yes {packages}` instead of `{tool} --install --yes {packages}` which does not work in `conan/tools/system/package_manager.py`.

![diff](https://user-images.githubusercontent.com/32455999/183424930-d56f58f5-1a8b-4fc6-ad86-9af220bf0eef.png)

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Conan version: 1.51
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)

1. Create a recipe that will install packages with the Chocolatey package manager
2. Watch it fail because the `--install` option is not recognized.

**Comment by czoido** [comment]
Hi @todorico,

Thanks a lot for reporting. We'll fix this in 1.51.1 that will be released very soon.

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/11810 to be released in 1.51.1
