### ISSUE TITLE
[bug] No module named 'conan.errors' error occurs on the latest release 

### ISSUE THREAD

**Issue by YevhenServetnykSD** [conan-io/conan#11814]
### Environment Details (include every applicable attribute)
  * Operating System+version: win 10
  * Compiler+version: -
  * Conan version: 1.51 x64 ([conan-win-64.exe](https://github.com/conan-io/conan/releases/download/1.51.0/conan-win-64.exe)), also reproducing in rel 1.50.0 
  * Python version: used from installer

### Steps to reproduce (Include if Applicable)
1 run: `conan install boost/1.76.0@`
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: boost/1.76.0: Cannot load recipe.
Error loading conanfile at 'C:\Users\Admin\.conan\data\boost\1.76.0\_\_\export\conanfile.py': Unable to load conanfile in C:\Users\Admin\.conan\data\boost\1.76.0\_\_\export\conanfile.py
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Admin\.conan\data\boost\1.76.0\_\_\export\conanfile.py", line 8, in <module>
    from conan.errors import ConanException, ConanInvalidConfiguration
ModuleNotFoundError: No module named 'conan.errors'

expected behavior: 
 'conan.errors' are found(were introduced in [1.47.0 (31-Mar-2022)](https://github.com/conan-io/conan/releases/tag/1.47.0))

**Comment by jcar87** [comment]
Hi @YevhenServetnykSD  - thanks for reporting this issue.

The Boost recipe has recently been updated in Conan Center Index to use functionality from more recent versions of Conan. We have identified an issue with our binary installers where some files required to resolve those imports were missing. 

We are shortly going to release `1.51.1` to address this issue. In the meantime, I would recommend using Conan as installed with `pip`, which should not be displaying this erroneous behaviour. Apologies for this!

**Comment by YevhenServetnykSD** [comment]
@jcar87 sure, thanks for fast response I saw that pr [boost](https://github.com/conan-io/conan-center-index/pull/12024/files), I just wondered if the issues with build on my side. Because according to release notes everything should work fine)
I'll close the as soon as I test it locally

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/11817 to be released very soon in 1.51.1
Thanks a lot for reporting!
