### ISSUE TITLE
[bug] Deprecated generators do not produce versions (in newer recipes)

### ISSUE THREAD

**Issue by Flow-It** [conan-io/conan#11812]
The issue was already described for the fmt recipe (see https://github.com/conan-io/conan-center-index/issues/11822)

Updated recipes cannot be used with the "old" generators like `cmake` or `pkg_config` because the version will not be set. This bug report describes the usage of the `pkg_config` generator, but it applies to other generators as well. The correct library version is still referenced, but the build system that parses the .pc file can not read a version and will therefore fail on a version check. A workaround is to skip the version check in the build system, but that is not recommended.

A proper fix is to switch to the new generators (here `PkgConfigDeps`)

However:

- I haven't checked if all recipes properly support the `PkgConfigDeps` generator
- Updating dependencies (either by manually updating the version or by using a range in the first place) without also updating the generator will lead to this bug.

Even while being deprecated, the `cmake` and `pkg_config` (and all the others where this bug occurs) should write out the package version properly.

### Environment Details (include every applicable attribute)
  * Operating System+version: Arch Linux
  * Conan version: 1.51.0
  * Python version: 3.10.5

### Steps to reproduce (Include if Applicable)

Create a conanfile.txt
```
[requires]
fmt/9.0.0

[generators]
pkg_config
```

And for comparison use the new generator:
```
[requires]
fmt/9.0.0

[generators]
PkgConfigDeps
```
See the bold markings in the logs for the difference.

### Logs (Executed commands with output)

With the `pkg_config` generator:
<pre>
$ conan install .
$ cat fmt.pc

Name: fmt
Description: Conan package: fmt
Version: <b>None</b>
Requires: _fmt
</pre>

And with the `PkgConfigDeps` generator:

<pre>
$ conan install .
$ cat fmt.pc

Name: fmt
Description: Conan package: fmt
Version: <b>9.0.0</b>
Requires: fmt-_fmt
</pre>

**Comment by czoido** [comment]
Hi @Flow-It,

Thanks a lot for reporting. The underlying issue for this is the same that the one for this one: https://github.com/conan-io/conan/issues/11784

This will be fixed by this PR: https://github.com/conan-io/conan/pull/11790 that is going to be released very soon (probably tomorrow) in 1.51.1

I'm closing this as resolved, please feel free to reopen or open more issues if you continue to have this problem after 1.51.1
