### ISSUE TITLE
[feature] Conan tools.scm.Version became very difficult to use

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#11821]
With the introduction of the new [tools.scm.Version](https://docs.conan.io/en/latest/reference/conanfile/tools/scm/other.html#version), it no longer parses `semver` as described on the documentation, but also makes users life harder. Comparing both `Version` behavior, we have:

```python
from conans import tools as tools_legacy
from conan.tools import scm

VERSION = "1.2.3"

if __name__ == "__main__":
    legacy_version = tools_legacy.Version(VERSION)
    print(f"Legacy Version: {legacy_version}")
    print(f"Major: {legacy_version.major} - Minor: {legacy_version.minor} - Patch: {legacy_version.patch}")

    version = scm.Version(VERSION)
    print(f"New version: {version}")
    print(f"Major: {version.major(fill=False)} - Minor: {version.minor(fill=False)} - Patch: {version.patch()}")
    print(f"Major: {version[0]} - Minor: {version[1]} - Patch: {version[2]}")
```

Output:

```
Legacy Version: 1.2.3
Major: 1 - Minor: 2 - Patch: 3
New version: 1.2.3
Major: 1 - Minor: 1.2 - Patch: 1.2.3
Major: 1 - Minor: . - Patch: 2
```

So far, we needed to dig an index to parse and use what we want: https://github.com/conan-io/conan-center-index/pull/12083#pullrequestreview-1064201491

My suggestion is adding a pattern support to `Version` where we could extend it:

    version = Version('1.2.3', pattern='semver')
    version.major # Yes, it's a property, not a method.

Or, we could provide new classes, with Version as the base:

```python
from conan.tools.scm import SemVersion

version = SemVersion('1.2.3')
version.major # Yes, it's a property, not an method.
```

- [ X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Actually, I saw there is a mismatch between Conan 1.X and Conan 2.X. In Conan 2.X is worked like the old `Version` but the new one is not. So this is something we need to fix. Thanks
