### ISSUE TITLE
[bug] centos9: package manager detected as "yum", but should be "dnf

### ISSUE THREAD

**Issue by huso113** [conan-io/conan#11829]
* Operating System+version: Centos 9 Stream
  * Compiler+version: GCC 11.3
  * Conan version: 1.50.0
  * Python version: 3.9.13

 In /usr/local/lib/python3.9/site-packages/conans/client/tools/oss.py:
```
    @property
    def with_yum(self):
        return self.is_linux and self.linux_distro in ("pidora", "fedora", "scientific", "centos",
                                                       "redhat", "rhel", "xenserver", "amazon",
                                                       "oracle", "amzn", "almalinux", "rocky")

    @property
    def with_dnf(self):
        return self.is_linux and self.linux_distro == "fedora" and which('dnf')
```

Centos moved from yum to dnf in some stage, why not just:
```
    @property
    def with_yum(self):
       return self.is_linux and and which('yum')

    @property
    def with_dnf(self):
        return self.is_linux and and which('dnf')
```
### Steps to reproduce (Include if Applicable)
Build any package with "def system_requirements(self):" on Centos9
- It will detect package manager as 'yum' but it not installed

**Comment by memsharded** [comment]
Hi @huso113 

It seems you are using the legacy tool. Please use the new one in https://docs.conan.io/en/latest/reference/conanfile/tools/system.html, which should fix that, and also provide better configuration to custom configure the desired system package manager to use.

**Comment by memsharded** [comment]
Closing as stale, please create new tickets if necessary, thanks!
