### ISSUE TITLE
[question] Distinguish between conan install and conan create

### ISSUE THREAD

**Issue by Viatorus** [conan-io/conan#11833]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Is it somehow possible if the conanfile is invoked by a `conan install` command or a `conan create` command?

I would like to use the distinction to decide if it is a developer environment, where the dependencies are installed or the package creation and than, for example, change some configurations.

Specifically, I would like to read a file which is located inside the project.
If I do a `conan install`, the file lies next to to the `conanfile.py`. But if I do a `conan create`, the file lies in the folder `export_sources` and the `conanfile.py` is inside `export`.

```py
def configuration(self):
   config = read_file_in_project_folder(PATH_TO_FILE)
   # ...
```

**Comment by czoido** [comment]
Hi @Viatorus,

You can access the location of the file regardless of if you use `conan install` or `conan create` using the `self.source_folder `attribute. That should point to the local folder when doing a conan `install` and to the Conan cache for the conan `create`. For that to work correctly I would recommend you to use the Conan https://docs.conan.io/en/latest/developing_packages/package_layout.html#package-layout feature.

Hope this helps. Thanks a lot for the question.

**Comment by czoido** [comment]
@Viatorus,

I think that is also worth notting that if you want to modify what your recipe does under certain conditions you can also use the conan `[conf]` feature. You can define your own user configuration with something like: `user.<configurationmame>:<attributename>=value` and use it inside the recipe at your convinience.
You can pass that in the command line with the `-c` argument:

```
conan install . -c user.whatever:name=value
conan create . -c user.whatever:name=other_value
...
```

**Comment by Viatorus** [comment]
Thank you for your anwser!

`self.source_folder` is None in `def configure(self)` but I will look into the package-layout feature and in to the [conf] feature.

**Comment by memsharded** [comment]
Closing as staled, please create new tickets if necessary, thanks!
