### ISSUE TITLE
Post-install actions

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#1183]
I am creating a package for Qt v5.
Qt binaries contain hard-coded paths, so it will not work if copied to another directory.
To make it work you should either create the `qt.conf` file (with new paths) near the `qmake` or patch Qt binaries with `qtbinpatcher` (3rd-party tool).

Is it possible to add a kind of post-install actions?
I understand that for security reasons it would be dangerous to run any unchecked scripts during install.

I think in this case it will be enough to replace some vars in a template file and then copy it to the package dir. For instance:
```python
class Qt5Conan(ConanFile):
    exports = "qt.conf.templ", ...
    templates = ("qt.conf.templ", "bin/qt.conf"), ...
```
```ini
# qt.conf.templ
[Paths]
Prefix = {package_dir}
```

Or add a method like `ConanFile.imports()`, that will copy files from `export` to `package`, and provide full paths to storage dirs
```python
class Qt5Conan(ConanFile):
    exports = "qt.conf", ...

    def exports_copy(self):
        self.copy("qt.conf", src="", dst="bin")
        conf = self.get_file_path("bin/qt.conf")
        with open(conf, ...):
            # replace some content
```

Related issues:
https://github.com/conan-io/wishlist/issues/2
https://github.com/osechet/conan-qt/issues/6

**Comment by memsharded** [comment]
I have been lately thinking about adding some post-install method, but still a few unknowns. Being it a security issue is not a stopper, after all, the package recipes are python scripts, so they can run python code in other methods too. From the security point of view, basically you shouldn't use untrusted package recipes in any case.

About a method changing files in the package folder, that might have some issues, because package contents are hashed and have manifests. So modifying packages will produce a mismatch with the manifest. It might work locally, but for example it will stop re-uploads. Would it be possible to copy the ``qt.conf`` file to user space (with imports, for example), modify it locally and use it from there?

**Comment by DmitrySokolov** [comment]
> From the security point of view...

I mean do not launch any 3rd-party executable files bundled in a package during install.


> About a method changing files in the package folder...

I mean generating a file, so all files in a package will remain unchanged. And yes, I see errors when I try to upload a package with untracked files. I think you could use the same way that Git/Hg uses for tracking files. Having untracked files in working copy does not fail a commit.

User can install multiple Qt versions, for different target devices and platforms. So having just one `qt.conf` in user space will raise another issue how to switch between Qt versions.

**Comment by DmitrySokolov** [comment]
I tried to generate `qt.conf` file in `def  build()` but it becomes a part of a package and when I try to install this package on other host `qt.conf` has wrong paths.

I tried to generate `qt.conf` file in `def  imports()` but this method is called before `build()` (so result is the same).
```
conan test_package
...
Qt5/5.7.1-1@itc/stable: WARN: Forced build from source
Qt5/5.7.1-1@itc/stable: Building your package in D:/.conan\v6yb8l\1
Qt5/5.7.1-1@itc/stable: Configuring sources in D:/.conan\s4tayf\1
Qt5/5.7.1-1@itc/stable: Copying sources to build folder
Qt5/5.7.1-1@itc/stable: Generated txt created conanbuildinfo.txt
# ----- imports() called
Qt5/5.7.1-1@itc/stable: Creating qt.conf
Qt5/5.7.1-1@itc/stable:   D:\.conan\ks07yr\1\bin\qt.conf
# ----- build() called
Qt5/5.7.1-1@itc/stable: Packaging '5.7.1-windows-x86_64-msvc2013' libs
Qt5/5.7.1-1@itc/stable:   lib dir: C:\Dev\Libs\Qt5\lib\5.7.1-windows-x86_64-msvc2013
Qt5/5.7.1-1@itc/stable:   src dir: C:\Dev\Libs\Qt5\src
...
```
Why `import()` is called before the build?

**Comment by memsharded** [comment]
But the user-space qt.conf is a temporary one, for building, exactly the way as other files like ``conanbuildinfo.cmake``. Those are generated files that are created in user space at ``conan install`` time. When you switch to a different Qt version, you have to do a ```conan install``, so this could work. Maybe the solution is to write a generator, you know that you can write your own generators? http://docs.conan.io/en/latest/howtos/dyn_generators.html#dyn-generators

Generating the file at build() time, will become part of the package, that is true.

You are also right, the ``imports()`` method is designed to retrieve the binary dependencies, like dll, or even exes from the package binaries. Imagine that your package has to generate some protobuf stubs from some .proto file. You can depend on the "Protobuf" package, then ``imports()`` the executable ``protoc`` to run it locally. It is not designed for doing post-install tasks. Most likely the ``imports()`` method can be superseded with the new environments variables management.

Please have a look to the generators approach, I think it could be a very convenient and elegant solution.

**Comment by DmitrySokolov** [comment]
> When you switch to a different Qt version, you have to do a `conan install`, so this could work.

I think it is not suitable for multi-configurations
http://docs.conan.io/en/latest/manage_deps/workflows.html#multi-configuration

> You are also right, the imports() method is designed to retrieve the binary dependencies...

I think I did not catch the idea. According to
http://docs.conan.io/en/latest/packaging/packaging.html#the-package-creation-process 
> the imports feature will copy artifacts from the local cache into user space

```
Test> conan test_package

Test/1.0@itc/stable: A new conanfile.py version was exported
Test/1.0@itc/stable: Folder: D:\Users\Dmitry\.conan\data\Test\1.0\itc\stable\export
Requirements
    Test/1.0@itc/stable from local
Packages
    Test/1.0@itc/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

Test/1.0@itc/stable: WARN: Forced build from source
Test/1.0@itc/stable: Building your package in D:\Users\Dmitry\.conan\data\Test\1.0\itc\stable\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Test/1.0@itc/stable: Configuring sources in D:\Users\Dmitry\.conan\data\Test\1.0\itc\stable\source
Test/1.0@itc/stable: --- source() ---
Test/1.0@itc/stable: Copying sources to build folder
Test/1.0@itc/stable: Generated txt created conanbuildinfo.txt
Test/1.0@itc/stable: --- imports() ---
Test/1.0@itc/stable: --- build() ---

Test/1.0@itc/stable: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' built
Test/1.0@itc/stable: Build folder D:\Users\Dmitry\.conan\data\Test\1.0\itc\stable\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Test/1.0@itc/stable: Generated conaninfo.txt
Test/1.0@itc/stable: Generated conanbuildinfo.txt
Test/1.0@itc/stable: Generated conanenv.txt
Test/1.0@itc/stable: Generating the package
Test/1.0@itc/stable: Package folder D:\Users\Dmitry\.conan\data\Test\1.0\itc\stable\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Test/1.0@itc/stable: --- package() ---
Test/1.0@itc/stable package(): WARN: No files copied!
Test/1.0@itc/stable: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
Test/1.0@itc/stable: --- package_info() ---
```
`imports()` is called before `build()`. There are no binaries in the local cache at that moment.

```
TestProject> conan install

Requirements
    Test/1.0@itc/stable from local
Packages
    Test/1.0@itc/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

Test/1.0@itc/stable: Already installed!
Test/1.0@itc/stable: --- package_info() ---
PROJECT: Generated qmake created conanbuildinfo.pri
PROJECT: Generated conaninfo.txt
```
So, when using packages in your project `imports()` does not called at all.

**Comment by DmitrySokolov** [comment]
I will try custom generators.

**Comment by memsharded** [comment]
> I think it is not suitable for multi-configurations

Why not? The approach described there has 2 different "conan install", one with ``-s build_type=Debug`` and other with ``-s build_type=Release``. Each one will generate its own, custom qt.conf to point to the respective Debug or Release package.

> the imports feature will copy artifacts from the local cache into user space

The thing about the imports is that it imports artifacts from the dependencies, the upstream packages, not for the package itself. It is a consumer feature. For example:
- you write a ``conanfile.py`` recipe, local in your userspace, with just some requirements (LibA and LibB) and an ``imports()`` method.
- you call ``conan install`` over your local recipe. Dependencies are installed
- ``imports()`` of your local conanfile.py is executed and then the binaries (typically .dlls, .exes) from LibA and LibB are copied to your local user folder.

So it is not related with the ``build()`` method. If you create a package LibC, that depends on LibA and LibB, and it has an imports, it will execute the ``imports()`` method **before** calling LibC ``build()``. The example I told you is that LibC requires LibA and LibB to perform some build task (as generating source code with some application living in LibA and LibB)

Imports are mostly for end-consumer conanfile.txt and conanfile.py, just to extract for example all the .dlls from the local cache if you want to redistribute to your users the final complete app.

**Comment by DmitrySokolov** [comment]
I see. So, there is no way to copy `*.dll` into app's build dir like this?
```
cd project/build
conan install ..
```
And I should create a proxy package to gather all needed binaries in an app's build dir?
```
# conanfile.py
class ProxyPackage(ConanFile):
    requires = "list of packages"
    build_policy = "missing"

    def imports(self):
        # copy binaries from requires
```
```
cd project/ProxyPackage
conan export user/stable
cd project/build
conan install -p "ProxyPackage/1.0/usrer/stable"
```

I tried generators, but `qt.conf` should be placed near `qmake`, so it can not be used from a user space. Fortunately, `qt.conf` understands relative paths, so I made it the part of Qt5 package (added creation of `qt.conf` in `def build()`).
```ini
[Paths]
Prefix = ..
```
So, there is no need for post-install actions for `qt.conf`. But consider using in packages, for instance, COM components (AtciveX). You need to run `regsvr32 component.dll` after installing a package.

**Comment by memsharded** [comment]
Yes, it is possible! :)
When you do ``conan install ..`` you are calling a conanfile.txt or conanfile.py. In either case you can have an ``imports`` that will copy the DLLs of all your dependencies that you are adding to ``requires``. But the imports is in your consumer conanfile, not in the packages you are requiring. And you don't need a proxy package, you can add it to your project conanfile. Probably I didn't explain myself properly, please write us to info@conan.io and if you want to chat.

**Comment by osechet** [comment]
As I mention it in one issue of my [conan-qt](https://github.com/osechet/conan-qt) package, I think the problem qith the `qt.conf` file is a build problem not a dependency problem. Even when you don't use Conan in a Qt project, you have to bundle a `qt.conf` file with your application. The problem cannot be solve with Conan. If you use CMake, it is easy to keep a `qt.conf.in` file with your source code and ask CMake to create the correct `qt.conf` file using variables.

**Comment by Thilo1** [comment]
Unfortunately the company i work with is using Qt < v5 and the company is quite big so it won't happen soon that they change to Qt > v5.

What can i do to fix the file "qt.conf" in ~/.conan/data/Qt/4.8/.../package.../23234ff...  so that the path inside qt.conf is valid after a consumer did "conan install" ? Is it possible at all?

I can write the conan-recipe for the qt-conan-package that is used there, so i am willing to try everything that you advise to me.

**Comment by memsharded** [comment]
Hi @Thilo1 

This thread is from some time ago. Since then, conan got the ``deploy()`` method, which is a post-install action for ``conan install <pkg-ref>`` command, please check if that could help: http://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy

Also, if you could summarize your issue with some minimal complete example, like a short recipe, the output, etc., it would be more useful, right now it is a bit hard to figure out exactly the issue.

Many thanks!

**Comment by Thilo1** [comment]
Simply put, i need to modify a file in a package after "conan install"
This means the contents of the package on the local machine "~/.conan/.../somepackage"  and the contents of the package on the conan-server would be not identical.
I think this is a conflict between how conan works and my need.
I will now follow the issue @jgsogo referenced above.

**Comment by jgsogo** [comment]
Maybe we can close this and focus our efforts in #2619 💪
