### ISSUE TITLE
[feature] Configure basic build folder name for cmake_layout

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#11838]
Currently, `cmake_layout()` defines _build_ as the basename for a build folder in layout.py:

    build_folder = "build" if not subproject else os.path.join(subproject, "build")

However, this default collides with some of our projects that already have a _build_ folder that contains some scripts and other stuff relevant for building. 

Would it be possible to add a config setting to override the default name, e.g. _tools.cmake.cmake_layout:build_folder_basename_?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @fschoenm,

Thanks a lot for the suggestion. Please note that you can define your own layout in the recipes or modify the existing `cmake_layout` with something like:

```
    def layout(self):
        cmake_layout(self)
        self.folders.build = "mycustombuild"
```

Anyway I'll mark this as a look into so we the team can discuss about this.

**Comment by fschoenm** [comment]
Hi @czoido,

while that's true and I looked into it, you'd also need to define `self.folders.generators` and then ideally you'd also need to handle subprojects and custom build folder naming (like `cmake_layout()` does) because these folders all depend on the (hard-coded) base folder.

It would IMO also be fine to add a new argument `build_folder` to `cmake_layout()` (like `src_folder`) to change it.

**Comment by czoido** [comment]
Hi @fschoenm,

We will implement a new `build_folder` argument for the `cmake_layout` in the next Conan release (1.52).

Thanks a lot for the feedback
