### ISSUE TITLE
[feature] Access to license and homepage for dependencies in conanfile.py

### ISSUE THREAD

**Issue by Setre14** [conan-io/conan#11836]
For some automated license report we would need to have access to the attributes `description`, `license` and `homepage` which can be set in the conan recipe.
As self.deps_cpp_info, self.deps_env_info or self.deps_user_info will be removed in conan 2.0, this should probably be added to [self.dependencies](https://docs.conan.io/en/latest/reference/conanfile/dependencies.html#dependencies-interface).
> Do not use self.deps_cpp_info, self.deps_env_info or self.deps_user_info, these have been removed in 2.0.

During this change it would be great to just have access to all attributes for the dependencies

**Comment by czoido** [comment]
Hi @Setre14,

Thanks a lot for the suggestion. I think it will be useful to make those accessible. I'm marking this as a feature for the next (1.52) release.

**Comment by memsharded** [comment]
It was pending to add ``recipe_folder`` and ``conan_data`` access too, lets add all of them.

**Comment by jwillikers** [comment]
Awesome, really glad to see this has landed!
