### ISSUE TITLE
[bug] Object of type PackageOption is not JSON serializable

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#11848]
* Conan version: 1.51.1
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)

In `generate()`, we attempt to use an option to set a `cache_variables`, as:

    def generate(self):
        toolchain = CMakeToolchain(self)
        toolchain.cache_variables["BUILD_tests"] = self.options.build_tests
        toolchain.generate()

### Logs 

The command:

    conan install conan/ -pr:h myprofile -pr:b build/Windows -o build_tests=True

Results in:

```
ERROR: conanfile.py (entity/None): Error in generate() method, line 66
        toolchain.generate()
        TypeError: Object of type PackageOption is not JSON serializable
```

Side note: the proble is not present if we were to assign `variables` instead of `cache_variables`.

**Comment by czoido** [comment]
Hi @Adnn,

Thanks a lot for reporting the issue. I can reproduce the issue and I'm adding this to be fixed for the next release (1.52)
In the meantime you could do:

```
toolchain.cache_variables["BUILD_tests"] = str(self.options.build_tests)
```

Thanks!

**Comment by memsharded** [comment]
A side note: Deciding to build or not to build tests recommended way is not using ``options``, but using ``conf``. There is a built-in conf ``tools.build:skip_tests`` that could be leveraged to implement this. The main difference is that ``conf`` by default is not part of the ``package_id``, and ``options`` are, so if we assume that tests are not packaged, that ``option.build_tests`` should be removed in the ``package_id()`` method.

**Comment by czoido** [comment]
Hi @Adnn,

Besides the previous comment, that would be the best approach to handle skipping tests in your recipes. The best way to pass the values of generic options to the toolchain is to explicitly cast the value of the option in the recipe. If you do:

- `str(self.options.myoption)` It will return the value of the option as a string and passed as a string to CMake
- `bool(self.options.myoption)` It will return the value of the option as a bool, if the option is `"True"` then converted to `True` (bool) and passed as `"ON/OFF"` to CMake

Hope this helps. I'm closing this but please feel free to reopen if you have more questions or this does not solve your issue.
