### ISSUE TITLE
[bug] Using 'conan build --configure' with new CMake helper causes cmake --build to be called

### ISSUE THREAD

**Issue by foundry-markf** [conan-io/conan#11847]
I noticed when trying out the transition between CMake helpers, that the `--configure` switch to `conan build` was behaving differently, in that the new CMake tooling just carries on after the configure/generation phase into calling `cmake --build`.

The `--configure` flag was used in some example code to stop after an IDE project is generated, since the idea is that the user opens that in the IDE, rather than compiling the project on the command line.

### Environment Details (include every applicable attribute)
  * Operating System+version: Mac (10.14)
  * Compiler+version: Xcode 10.1
  * Conan version: 1.51.1
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)
I've cut down the original reproducible into a simpler gist

https://gist.github.com/foundry-markf/ac831076c782e0e0aaced021904df0b5

Running the runme.sh bash script, executes the same Conan recipe with different options in order to switch between the two CMake helpers.

I haven't tried this on another OS, but the original much larger sample was behaving the same on a Windows box with VisualStudio generators.

Thanks

**Comment by dornbirndevelops** [comment]
Hi @foundry-markf,
I had a similar [question](https://github.com/conan-io/conan/issues/11430) ~2 months ago.
It seems intentional from what I've understood.

**Comment by memsharded** [comment]
Yes, the whole idea is that ``conan build`` is no longer in the normal developer flow. Instead, it should be replaced with ``conan install`` + ``cmake ...`` (or other build system native commands). This is the reason why the ``generate()`` method now is the responsible to "prepare" the build, and many things have been moved to files instead of in-memory by the ``build()`` method, so the build is the same in all cases.

The ``--configure`` argument to ``conan build`` has already been removed in 2.0. The command ``conan build`` is intended to execute the ``build()`` method completely. If there is some aspect of the build that could be controlled by the user, it should be done with ``conf``, like the ``tools.build:skip_tests`` conf to skip running tests. I don't think that a conf should be used to restrict the functionality in ``build()`` method to do only a configure but not a build, but instead, native commands will be recommended.

**Comment by foundry-markf** [comment]
@dornbirndevelops Thanks! I hadn't spotted that in an earlier search as I wasn't using the `should_xyz` properties.

@memsharded Thanks too! I had completely forgotten about that tribe proposal (back in Feb '21) (which I did upvote!) that does mention improved IDE integration, which is what I was doing in this report (skip the build after configure, and load straight into Xcode/VisualStudio).

All in all, I need to have a think on our workflows, as I'm still in 1.x mode, and as we have a variety of native build systems used in the recipes in our library stack, and how it may affect those developers who previously didn't need to care about the details of running different native build systems, if they are using local workflow.

**Comment by johnmcfarlane** [comment]
Hi, I'm still trying to wrap my head around the changes to `conan install` and `conan build`. The `cmake.configure()` call in my `build` method now invokes this command:

```sh
cmake \
  -G "Unix Makefiles" \
  -DCMAKE_TOOLCHAIN_FILE="build-directory/conan_toolchain.cmake" \
  -DCMAKE_INSTALL_PREFIX="build-directory" \
  -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" \
  -DCMAKE_BUILD_TYPE="Release" \
  "project-directory"
```

Are you saying that in the new workflow, configuring the build system (without actually building) involves calling this explicitly, and providing some/all of those parameters?

**Comment by memsharded** [comment]
It depends.

With modern CMake, it should be just ``cmake --preset conan-release`` or something like that. Are you using cmake>=3.23?

If not possible to use presets, then the above can be simplified in many cases:
- The Unix Makefiles is the default in Linux systems, can be skipped if you are in Linux
- The ``CMAKE_POLICY_DEFAULT`` is just a precaution if using some projects with lower ``cmake_minimum_required()`` than 3.15. As the necessary CMake version for Conan 2.0 is 3.15, having a ``cmake_minimum_required(VERSION 3.15)`` is recomended anyway
- The ``CMAKE_INSTALL_PREFIX`` is not necessary in most cases, Conan 2.0 doesn't have a ``conan package`` method, so it will not be called

So in practice, developer command should be typically something like:
```
cmake <project-dir> -DCMAKE_TOOLCHAIN_FILE=build-directory/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
```

**Comment by memsharded** [comment]
The modern flow with ``conan install`` + ``cmake --preset`` is working very well, this is the recommended flow now, closing the ticket as outdated.
