### ISSUE TITLE
Setting settings in configure() method, not available in build() method

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#1185]
I wanted to set some settings in configure method, if not given from command line (eg. set default compiler version). Here is example conanfile:

    import conans

    class ConanFileInst(conans.ConanFile):
        settings = 'compiler'
        options = {'opt' : [1, 2]}
        
        def configure(self):
            self.options.opt = 2
            if self.settings.compiler == 'gcc':
                self.settings.compiler['gcc'].remove(('libcxx', 'threads', 'exception'))
                if not self.settings.compiler.version:
                    self.settings.compiler.version = '6.2'
            print(self.settings.values_list)
            print(self.options.values)
            
        def build(self):
            print(self.settings.values_list)
            print(self.options.values)

After calling ```conan install -s compiler=gcc``` I get following output from my prints:

    [('compiler', 'gcc'), ('compiler.version', '6.2')]
    opt=2

If I call ```conan build``` afterwards, I get:

    [('compiler', 'gcc')]
    opt=2

So the compiler version gets "reverted", but overridden option gets propagated to build() method . Is this desired behaviour? How to reconfigure settings so it will be available for me in the build() method?

**Comment by memsharded** [comment]
Hi @omicronns,

No, settings are not meant to be defaulted by the recipes, as it is something that only makes sense in the context of the user machine. You cannot say that the default compiler is Visual Studio, as it will make no sense in Linux. ``configure`` method can be used for "removing" or raising errors for not implemented settings, but not for assigning values to it. That is the main different with options. Options can be defaulted by the package recipe.

So settings can be defaulted:
- In your ``<username>./conan/conan.conf`` file, system-wide settings for your user. They will be applied by default if not overriden by the command line.
- In the command line: ``conan install -s compiler=gcc``
- The best one: In profiles. Check http://docs.conan.io/en/latest/mastering/profiles.html. This is the most convenient, robust and ordered way to define configurations, not only for settings, but for options, environment variables (settings can be set per package, like ``Pkg:compiler=gcc``), and soon we will introduce ``build_requires`` into profiles too.

**Comment by omicronns** [comment]
Hi @memsharded 

Thank you for your answer. So maybe conan should check if settings was changed, and raise an error if so? Because provided example did not raised any errors, even that there was no compiler.version availible at the build() method call.

**Comment by memsharded** [comment]
I think conan will complain if one package does not have defined its settings. Try these steps:
- ``conan new Pkg/0.1@user/channel -t``
- Remove your ``[setting_defaults]`` in ``<userhome>/.conan/conan.conf``
- `` conan test_package``
- Now try leaving all values of ``[settings_defaults]`` and only remove the ``compiler.version``
- ``conan test_package``
