### ISSUE TITLE
[bug] "PermissionError: [Errno 13] Permission denied" on windows platform

### ISSUE THREAD

**Issue by initlifeinc** [conan-io/conan#11877]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows
  * Compiler+version:
  * Conan version: 1.48.2
  * Python version: 2.7.17rc1

### Steps to reproduce (Include if Applicable)
cannot reproduce, only appear 2 times

### Logs (Executed commands with output) (Include/Attach if Applicable)
when run "conan install .. --build=outdated",
after download several packages, it will failed with following error message: 
`ERROR: videoconf/0.0.1@user/channel: Error in package() method, line 30
        self.copy("*")
        PermissionError: [Errno 13] Permission denied: 'C:\\Users\\l366901\\.conan\\data\\videoconf\\0.0.1\\user\\channel\\build\\646b4443d8c3d67ac7dd2cad293a745d9b3e7baa\\videoconf.zip'`

yes, in package() method, only one line code,
`self.copy("*")`

after it failed, i can rerun install command for lots time, and each time it will raise a same error but for a different package. and the above package is successfully processed.

So the question is why it is appeared, and how to solve it.

**Comment by memsharded** [comment]
Hi @initlifeinc 

It seems you are using some legacy and unsupported things:

- Python 2.7 support has been finally completely removed in 1.49, after being declared for a long time unsupported (it was only possible declaring an env-var to workaround the restriction
- The ``self.copy()`` has to be replaced by the ``copy(self, ...)`` tool
- The ``outdated`` only makes sense when not using revisions. Revisions are the recommended approach for a long time now, and they are already always used in 2.0.

It also seems that this behavior could be associated to the specifics of that ``videoconf`` package, so it might be something in that recipe, or in the sources of that package.

To workaround what you are seeing, probably the easiest is to remove your Conan cache folder ``<userhome>/.conan`` and start over.

**Comment by initlifeinc** [comment]
> Python 2.7 support has been finally completely removed in 1.49, after being declared for a long time unsupported (it was only possible declaring an env-var to workaround the restriction
> The self.copy() has to be replaced by the copy(self, ...) tool

OK, got it, but still be not sure why it raise this error. this error seems easy to appear after delete the whole <userhome>/.conan on windows platform 

for delete the whole cache folder, I think this operation is very heavy because we hope use a custom conan remote repo, it seems delete ./conan/data is a simple way to clear cache. am i right?

> The outdated only makes sense when not using revisions. Revisions are the recommended approach for a long time now, and they are already always used in 2.0.

i want to publish a version named with snapshot, which means this version could be updated, and i will use upload --force to force update recipe. and then i hope user could install with the newest version. 
now i use the oudated option, but as you say, it seems i miss understand. So how can we always use the latest version for a package when invoke conan install command(use conan 1.4x or 1.5x version)

**Comment by memsharded** [comment]
> OK, got it, but still be not sure why it raise this error. this error seems easy to appear after delete the whole /.conan on windows platform

The Python implementation of things like ``shutil.rmtree``, ``shutil.copy`` etc might be slightly different in Python 2.7 and in Python >= 3.6


> or delete the whole cache folder, I think this operation is very heavy because we hope use a custom conan remote repo, it seems delete ./conan/data is a simple way to clear cache. am i right?

Yes, removing ``./conan/data`` will remove the packages, but not the rest of the cache configuration. In any case, if you have custom configuration, the recommended way is to use ``conan config install``, so you can easily completely remove a cache, and then re-configure it quickly to the same state calling ``conan config install``.


> now i use the oudated option, but as you say, it seems i miss understand. So how can we always use the latest version for a package when invoke conan install command(use conan 1.4x or 1.5x version)

When using ``revisions`` the latest revision is always used by default, no need to do anything explicitly. But using revisions will not just overwrite the previous recipe or binary packages, but instead it creates a new internal revision number/hash. Servers can store multiple revisions, keeping the history of changes done to recipes. When using revisions, the ``outdated`` should never happen, because a new change in a recipe causes a recipe revision that will contain its own binaries, that by definition can never be outdated.

**Comment by initlifeinc** [comment]
> Yes, removing ./conan/data will remove the packages, but not the rest of the cache configuration. In any case, if you have custom configuration, the recommended way is to use conan config install, so you can easily completely remove a cache, and then re-configure it quickly to the same state calling conan config install

Yes, I have already create a git to store configuration and ask the team to re-configuration by calling `conan config install`


> When using revisions the latest revision is always used by default, no need to do anything explicitly. But using revisions will not just overwrite the previous recipe or binary packages, but instead it creates a new internal revision number/hash. Servers can store multiple revisions, keeping the history of changes done to recipes. When using revisions, the outdated should never happen, because a new change in a recipe causes a recipe revision that will contain its own binaries, that by definition can never be outdated.

It seems if i add --update in command `conan install`, it will always update to latest recipe?

**Comment by memsharded** [comment]
Closing this ticket as outdated, the Conan cache has been completely redesigned in Conan 2, using always revisions and a DB, this shouldn't be an issue, but please create new tickets if necessary.
