### ISSUE TITLE
[question] [env] from profiles is not applied when generate() is called?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11871]
Hi,
I'm experimenting with CMakeToolchain + generate(). Almost everything appears to be fine, meaning package options, etc. are seen properly during generate, however it appears if I have an [env] section in the profile, it is not applied to the running environment, meaning os.environ() will not contain the changes [env] in a profile would apply. The strange part that Conan dumps - obviously - the proper environment variables in the beginning of conan install.

Am I doing something wrong?
Thanks,

**Comment by harsszegi** [comment]
Meh, self.env is still usable which contains the values from the profile

**Comment by memsharded** [comment]
``self.env`` dissapears in Conan 2.0, better also start moving to the new solution. In this case, most likely ``[buildenv]`` in profiles and ``VirtualBuildEnv`` generator in recipes: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html

**Comment by harsszegi** [comment]
Awesome, thanks a lot @memsharded  for the info!
