### ISSUE TITLE
[question] tools.microsoft.MSBuild how to customize build_type and platform

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#11875]
So, the older [MSBuild](https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html#build) has custom platform, build_type and others based on `build()` parameters.

However, the new [MSBuild](https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html#msbuild) is based on public attributes.

Based on a real [Pull request](https://github.com/bincrafters/conan-center-index/blob/c024fe53ed2ad283a1b9521f12daa7f4d54880d9/recipes/libusb/all/conanfile.py), both build_type and platform need to be customized, because the project does not follow a regular situation.

Looking [msbuild.py](https://github.com/conan-io/conan/blame/develop/conan/tools/microsoft/msbuild.py), all attributes are public and the documentation also expose them, but platform, for instance, has extra steps, which difficult its default usage + custom value. For instance:

```python
msbuild = MSBuild(self)
msbuild.platform = "Win32" if self.settings.arch == "x86" else msbuild.platform
```

So the main question is: Is it correct use `MSBuild` attributes to customize its values, or, will it be updated. Usually, we don't consume attributes from tools, it's considered "internal".

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Yes, the attributes `msbuild.build_type` and `msbuild.platform` are public, accessible, and customizable. I will open a PR to the docs to clarify it.
