### ISSUE TITLE
[question] layout usage: Is it correct to use according to the source?

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#11876]
Considering a case where a project builds on Windows with .sln files only and on Linux it uses autotools only, we could find:

```python
def layout(self):
    if is_msvc(self):
        msvc_layout(self)
    else:
        basic_layout(self, source_folder="src")
```

As it affects the source folder (mutable), and the documentation does not show an example where more than one layout is used, the question is: It correct to use a layout according to the build helper? 

Related to https://github.com/conan-io/conan-center-index/pull/12179/files#r945299362

/cc @SpaceIm 
 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, it is perfectly valid to have conditional layouts, if different build systems with different layouts are used under different conditions, as long as the rest of the build, package, package_info, etc methods are consistent.

**Comment by memsharded** [comment]
Closing this question as responded.
