### ISSUE TITLE
[feature]  Strict mode for lockfile creation that fails if no PREV is available

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#11887]
We maintain our own remote with custom packages and use lockfiles to ensure reproducible builds. When a developer wants to update a package or add a new one, they're expected to use our CI/CD infrastructure to publish a new conan package to our remote and then update the lockfiles on the repos that consume conan packages. 
This usually works but there is a frequent issue: sometimes when a lockfiles gets re-created we end up with a node that has no `prev` on it. This is usually because the dev did somenthing wrong on the `conanfile`. 
This situation is hard to catch since our lockfiles are pretty big and not all of our developers are big on conan, so they don't know what they're looking at.
In our case if you commit a lockfile that has (at least) one node without PR, the CI/CD builds that validate PRs fail since there's no package available upstream and we don't use `--build=missing`.

I was wondering if we could add a `--strict` switch to the lockfile creation command that errors out if there is no package available for a given reference, that way we can catch this issues ASAP.

Thanks!

**Comment by memsharded** [comment]
Hi @ericriff 

You  need to have a look at lockfiles in 2.0. They implement explicitly a ``--lockfile-partial`` mode to specify that the lockfile is not strict (as by default, they will be strict). They also simplify a lot of things regarding lockfiles management.

You can check the tribe proposal in https://github.com/conan-io/tribe/pull/34, and some initial docs in https://docs.conan.io/en/2.0/tutorial/consuming_packages/intro_to_versioning.html#lockfiles. Please try them and let us know.

**Comment by ericriff** [comment]
I saw that conversation. I'm exited to have the new lockfiles since they seem way better that what we have now. Regardless, that's a conan 2.0 solution.
What about 1.x?

**Comment by memsharded** [comment]
> What about 1.x?

I am afraid, it is extremely unlikely that we will develop new features like this one in 1.X. And specially lockfiles are very complicated in 1.X. Conan 1.X dev is mostly only regressions, and backports of recipe tools and syntax that will allow the recipe migration/compatibility between 1.X/2.0.

**Comment by ericriff** [comment]
Good to know. No problem.
is there an ETA for 2.0? So we can start preparing.

**Comment by memsharded** [comment]
We are about to do 2.0-beta.3, it is getting ready quickly, I'd expect a couple of releases more until GA. It might require a bit more time to let ConanCenter catch-up and update a reasonable amount of recipes, but otherwise the Conan client will be ready soon.

**Comment by ericriff** [comment]
Awesome! Exiting times ahead of us.
Thanks for the info :)
