### ISSUE TITLE
Duplicated requirement for version range

### ISSUE THREAD

**Issue by theirix** [conan-io/conan#1188]
I created a few recipes that used version ranges for dependencies using semantic versioning. In the following example `libcurl` depends to `libssh2/[~=1.8]@theirix/stable` and `libssh2` depends to `zlib/[~=1.2]@lasote/stable`. Also I have fixed `zlib` at 1.2.11 in the project conanfile.  The package `OpenSSL/1.0.2k@lasote/stable` depends strictly on `zlib/1.2.11@lasote/stable`. See a gist for a complete dependency list.

I am expecting that the dependency graph resolves strictly to `zlib/1.2.11` but it is failing with:
`Duplicated requirement zlib/1.2.11@lasote/stable != zlib/[~=1.2]@lasote/stable
`

Should it really fail or is it a bug?

[Test conanfile](https://gist.github.com/theirix/40c7730ad45da64576a4a4dfbb484f81). All other recipes are from conan.io.

Full output:
```
libcurl/7.52.1@theirix/stable requirement zlib/[~=1.2]@lasote/stable overriden by your conanfile to zlib/1.2.11@lasote/stable
libcurl/7.52.1@theirix/stable requirement libssh2/[~=1.8]@theirix/testing overriden by your conanfile to libssh2/1.8.0@theirix/stable
Version range '~=1.2' required by 'libcurl/7.52.1@theirix/stable' valid for downstream requirement 'zlib/1.2.11@lasote/stable'
Version range '~=1.8' required by 'libcurl/7.52.1@theirix/stable' valid for downstream requirement 'libssh2/1.8.0@theirix/stable'
libssh2/1.8.0@theirix/stable requirement zlib/[~=1.2]@lasote/stable overriden by libcurl/7.52.1@theirix/stable to zlib/1.2.11@lasote/stable
libssh2/1.8.0@theirix/stable requirement OpenSSL/[>1.0.2a,<1.0.3]@lasote/stable overriden by libcurl/7.52.1@theirix/stable to OpenSSL/1.0.2k@lasote/stable
Version range '~=1.2' required by 'libssh2/1.8.0@theirix/stable' valid for downstream requirement 'zlib/1.2.11@lasote/stable'
Version range '>1.0.2a,<1.0.3' required by 'libssh2/1.8.0@theirix/stable' valid for downstream requirement 'OpenSSL/1.0.2k@lasote/stable'
ERROR: libssh2/1.8.0@theirix/stable: Duplicated requirement zlib/1.2.11@lasote/stable != zlib/[~=1.2]@lasote/stable
```

**Comment by memsharded** [comment]
Thanks very much for reporting this. Also for the good report, details, and gist.
Yes, it seems a bug, lets try to fix it before next release (though my first look, it doesn't seem simple :( )

**Comment by memsharded** [comment]
I have just tried, and didn't reproduce the issue. Which version of conan are you running? If an old one, could you please try to update? Thanks!

**Comment by theirix** [comment]
It's very strange. I was running 0.21.1 on my mac. Now I rerun test at the clean system without packages and with conan 0.21.2 and got the same error. Log is [here](https://gist.github.com/theirix/a17764135074fd901e6370956beedd3d).
Empty `~/.conan/data` should reproduce it clearly.

**Comment by memsharded** [comment]
I think I know what is happening. I have tried for Mac, able to reproduce it (the dependencies are different for different OSs). The issue is, that conditional requirements for version ranges should be defined in the ``requirements()`` method, not in the ``configure()`` method:

```python
    def requirements(self):
        if self.options.enable_zlib:
            self.requires.add("zlib/[~=1.2]@lasote/stable", private=False)
            self.options["zlib"].shared = self.options.shared
        if self.options.crypto_backend == "OpenSSL":
            self.requires.add("OpenSSL/[>1.0.2a,<1.0.3]@lasote/stable", private=False)
            self.options["OpenSSL"].shared = self.options.shared
```
This happens in your libssh2 library, but I know it is also the way it is done in the OpenSSL package, I will notify OpenSSL package author asap.

**Comment by memsharded** [comment]
Reported to: https://github.com/lasote/conan-openssl/issues/22

**Comment by theirix** [comment]
Thanks for the hint. I'll try to fix my packages accordingly.

**Comment by memsharded** [comment]
The packages for OpenSSL have been updated to account for this. Have you managed to try with your recipes too? Thanks!

**Comment by theirix** [comment]
Yes, thanks! I updated both libssh2 and libcurl. Now dependencies are resolved without errors so the original problem solved. Only one problem remains (https://github.com/lasote/conan-openssl/issues/23) that blocks travis builds of these packages with shared OpenSSL.

**Comment by memsharded** [comment]
Great! thanks for telling
