### ISSUE TITLE
[question] Release date for 1.51.3 including the bugfix #11860

### ISSUE THREAD

**Issue by SirCosty** [conan-io/conan#11890]
- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

When will be the next release including the bugfix of 
Prevent mutation of conan_data structure in apply_conandata_patches #11860

**Comment by lasote** [comment]
Hi, the thing is https://github.com/conan-io/conan/pull/11860 is assigned to 1.52, we have to check if we port it to 1.51.3
About the release date, we planned to release ASAP but new bugs continue to appear. I guess it will be released this week.

**Comment by SirCosty** [comment]
> Hi, the thing is #11860 is assigned to 1.52, we have to check if we port it to 1.51.3 About the release date, we planned to release ASAP but new bugs continue to appear. I guess it will be released this week.

Would be nice to have it as soon as posible because is a blocker for me right now 
Thanks

**Comment by lasote** [comment]
Today or tomorrow first thing is the current plan.
