### ISSUE TITLE
[question] Differentiate between different types of tests 

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#11898]
Dear Conan Folks, I am sorry I am asking a second question today. We have many different types of test :  unit tests, integration tests,  tests on hardware, system tests. However conan provides only one method to trigger it : https://docs.conan.io/en/latest/reference/commands/creator/test.html 
We also need to execute tests with our pipelines. Is there any easy way to differentiate between the different types of tests with conan otherwise everything is invoked by conan create. So this is quiet confusing when a user is looking at jenkins results but everything is executed in one step build + test and not pinpointing perhaps to what step has exactly failed.
Could you please help me with best practices ? 

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @maitrey 

Note the ``conan test`` command, and the ``test_package`` functionlity that can be triggered by ``conan create`` only intend to be used for testing the package:
- Check that the necessary headers have been copied
- Check that the libs have been copied
- Basic binary architecture/compatibility check, linking and running some simple exe.

But not for building and running unit/integration or other kind of functional tests for the code itself. For those:
- They should be built and run in the ``build()`` method of the recipe
- They can be controlled, like other aspects, with conf, like ``tools.build:skip_tests`` can be used to avoid running tests.

**Comment by maitrey** [comment]
Thanks for answering this one. We have some internal legacy in our systems due to which we cannot use the test feature directly. However, understood that build + all kind of tests is triggered by build method. Also that it is possible to skip executing the tests.
