### ISSUE TITLE
[question] Best way to build a platform/variant agnostic package

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#11895]
Dear Conan Folks, I have a package that contains some scripts that I will be using for running pre-build steps. Since these scripts will be used by multiple other packages I need to move them to its own package. Currently , I am setting up an environment variable in order that the package location can be known to the one that consumes it  by:
`def package_info(self):
        self.env_info.SCRIPT_UTILITIES = os.path.join(self.package_folder) `

But in order to build it I donot specify and target compiler as this is a generic package.
 conan create . test/devel -pr:b=default
Are there any side effects to using it like this example for transitive dependencies? Or Is there any other way to handle platform/variant agnostic packages?
I am asking as many of the experimental features(example: CMakeDeps, CMakeToolChain) insist to use both host and build profiles,
- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @maitrey 

If your package is platform agnostic, it is typically enough to just remove the ``settings = ...`` declaration in the recipe, and you can ``conan create`` it without specifying any profile at all.

Then, a couple of details:
- If you put the scripts inside a ``bin`` folder, they will be automatically added to the PATH env-var in consumers with the right generators, so it might not be necessary to define env-vars in ``package_info``, but generators like ``VirtualBuildEnv`` will automatically add them
- If adding other custom env-vars, the recommended modern way is ``self.buildenv_info`` instead, and consume it with ``VirtualBuildEnv`` generators.

**Comment by maitrey** [comment]
Perfect , both solutions work for me ! Thanks for your reply.

**Comment by maitrey** [comment]
Could you please provide any example of such a package in conan-2.0.5? I checked inside this:  https://github.com/conan-io/conan-center-index.git  but could not find any?

**Comment by memsharded** [comment]
I don't think we have any example for that out of the box, but if you are struggling with something specific, please let us know
