### ISSUE TITLE
Re-introduce the CLICOLOR_FORCE environment variable (or equivalent) in 2.0

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#11892]
Hi there,

I just noticed that in Conan 2.0 the `CLICOLOR_FORCE` environment variable was removed as part of https://github.com/conan-io/conan/pull/11421. While I completely understand and respect the decision to adopt the standardised `NO_COLOR` approach to disabling colored output, the problem is that our (Windows) CI environments such as TeamCity won't default to using color as they have no TTY attached when running builds e.g. the stdout/stderr streams are captured for reporting in the CI system. In Conan 1.x we could elect to force the colored output, but now we will seemingly no longer have that ability?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12028, will be in beta.3
