### ISSUE TITLE
[question] conan.tools.apple import looks confuse 

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#11894]
The new [Apple tools](https://docs.conan.io/en/latest/reference/conanfile/tools/apple.html) is bit confuse to be imported. For instance, if I need to import the old version of [conans.tools.is_apple_os](https://docs.conan.io/en/latest/reference/tools.html#tools-is-apple-os), now I need to import:

    from conan.tools.apple.apple import is_apple_os

Also, it's not documented yet on https://docs.conan.io/en/latest/reference/conanfile/tools/apple.html, so, it's even weird when importing something which is not documented, and looks be an internal module, because the namespace is duplicated.

It would be great if it was possible to reduce the apple import to only:

    from conan.tools.apple import is_apple_os

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
That module is private. We have a comment:

```
# Keep everything private until we review what is really needed and refactor passing "conanfile"
# from conan.tools.apple.apple import XCRun
# from conan.tools.apple.apple import apple_dot_clean
# from conan.tools.apple.apple import is_apple_os
# from conan.tools.apple.apple import apple_sdk_name
# from conan.tools.apple.apple import apple_deployment_target_flag
# from conan.tools.apple.apple import to_apple_arch
```

So, at least we need to provide an interface of `is_apple_os` with the conanfile as an argument.

**Comment by SpaceIm** [comment]
See also https://github.com/conan-io/conan/issues/11865
