### ISSUE TITLE
[question] Backport #11896 to 1.50.3

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#11907]
The related fix to solved the problem of importing `is_apple_os`. However, on Conan Center Index, if using 1.50.2, it won't work. Is is possible to release 1.50.3 with that hotfix?

Related to https://github.com/conan-io/conan/issues/11906

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
I think it is not worth it. You can keep the old `tool.is_apple_os` until you deploy `1.51.X`

**Comment by uilianries** [comment]
Done. 

https://github.com/conan-io/conan-center-index/pull/12341
https://github.com/conan-io/conan-center-index/pull/12340
https://github.com/conan-io/conan-center-index/pull/12335
