### ISSUE TITLE
[question] conan info does not list tool_requires

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#11900]
Dear Conan Folks, conan info lists the dependency graph , so it lists what is specified as requires in the conan recipes. However it does not list the tool_requires.  Also the package that is used as tool_requires doesnot list who is dependendent on it in the conan info.
Is this an intended  feature or a bug ?
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @maitrey 

You need to pass the ``--dry-build=...`` arguments, with the same values you would provide to ``conan install`` or ``conan create``  argument ``--build``. 

The asymmetry comes from historical reasons, but it has been fixed in 2.0, with ``conan graph info --build=xxxx`` syntax

**Comment by maitrey** [comment]
Do you mean like this : conan info  --dry-build=test/6.1.0@testing/devel -pr:b=default -pr:h=ndp

**Comment by memsharded** [comment]
It seems you are missing the root reference, similar to ``conan install``. Something like using ``.`` for the current local ``conanfile.py``:
```
conan info . --dry-build=test -pr:b=default -pr:h=ndp
```

**Comment by maitrey** [comment]
Hi James, Sorry for the late reply. It works but in the end also gives an error: 
ERROR: No package matching 'test' pattern found.

**Comment by memsharded** [comment]
Are you sure that you have a ``test/version..`` package? Can you try with ``--dry-build=test*`` instead?

**Comment by maitrey** [comment]
conan info . --dry-build=test* -pr:b=default -pr:h=ndp results in:
ERROR: No package matching 'test*' pattern found.

But indeed I can see the package along with the dependency graph just this error in the end is confusing.

**Comment by memsharded** [comment]
Oh, I see what you mean, if you can see the package in the dependency graph, that error message should be harmless, and it has been already removed in 2.0

**Comment by maitrey** [comment]
thanks , then closing this one as well.
