### ISSUE TITLE
[bug] base lockfile don't work when requires and build_requres zlib/1.2.11 meanwhile

### ISSUE THREAD

**Issue by wjswjq** [conan-io/conan#11916]
### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 20.04
  * Compiler+version: gcc-10
  * Conan version: 1.48.1
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
1. pkga requires and build_requires protobuf/3.14.0
2. pkgb requires pkga
3. create pkga in pkga folder
`conan create .`
4. create pkgb base lock in pkgb folder
`conan lock create -pr:h=x64 -pr:b=x64 conanfile.py --lockfile-out conan_b.lock --base`
5. use pkgb base lockfile to create pkga lockfile in pkga folder (error ocurrs when host and build package ids are different)
`conan lock create -pr:h=x64 -pr:b=x64 conanfile.py -l conan_b.lock --lockfile-out conan_a.lock -s build_type=Debug`
6. conanfile.py for pkga
```
from conans import ConanFile, CMake
required_conan_version = ">=1.28"
class PkgaConan(ConanFile):
    name = "pkga"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    generators = "cmake"
    exports_sources = "src/*"
    requires = "protobuf/3.14.0"
    build_requires = "protobuf/3.14.0"

    def package(self):
        self.copy("*", dst=".", src=".")

    def deploy(self):
        self.copy("*", dst="bin", src="bin", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["pkga"]
```
7. conanfile.py for pkgb
```
from conans import ConanFile, CMake
required_conan_version = ">=1.28"
class PkgbConan(ConanFile):
    name = "pkgb"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    generators = "cmake"
    exports_sources = "src/*"
    requires = "pkga/[>0.0]"

    def package(self):
        self.copy("*", dst=".", src=".")

    def deploy(self):
        self.copy("*", dst="bin", src="bin", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["pkgb"]
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
conan/pkga# conan lock create -pr:h=x64 -pr:b=x64 conanfile.py -l conan_b.lock --lockfile-out conan_a.lock -s build_type=Debug                                      
_conanfile.py (pkga/0.1): WARN: Build-require 'protobuf' cannot be found in lockfile
ERROR: 'zlib/1.2.11#683857dbd5377d65f26795d4023858f9' package-id '19729b9559f3ae196cad45cb2b97468ccb75dcd1' doesn't match the locked one '75e99b627c196b65c439728670655ec3c366b334'_

**Comment by memsharded** [comment]
Hi @wjswjq 

I think this is a duplicated of https://github.com/conan-io/conan/issues/11749, closing it, please track the other issue. Thanks!
