### ISSUE TITLE
[bug] `install` method of `conan.tools.meson.Meson` calls `meson setup --reconfigure` before installing

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11910]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Monterey
  * Compiler+version: AppleClang 13
  * Conan version: 1.51.2
  * Python version: 3.10.6

### Steps to reproduce (Include if Applicable)

- checkout a recipe based on `conan.tools.meson.MesonToolchain` & `conan.tools.meson.Meson` (for example in https://github.com/conan-io/conan-center-index/pull/12300)
- run `conan create`

During install step, an unnecessary reconfiguration is executed (it can be quite long depending on the project). So the behavior differs from CMake helper where no reconfiguration is done when install method is called.

### Logs (Executed commands with output) (Include/Attach if Applicable)

https://c3i.jfrog.io/c3i/misc/logs/pr/12300/1-linux-gcc/dav1d/1.0.0//79ab1d7c838f7fd4d71114687478abc26e7bc7ef-build.txt

**Comment by franramirez688** [comment]
Hi @SpaceIm 

As you can read in this comment https://github.com/conan-io/conan/pull/11920#discussion_r951531831, there is nothing to improve here because the `package_folder` can change (depending on the local flow), and it has to be passed to the install always, so that `reconfigure` is necessary...

(Suggestion/Question) Maybe, it could be better in these cases to use the `copy()` function instead to avoid that reconfiguration.

**Comment by eli-schwartz** [comment]
But according to the original report, the cmake helper does not need to do any such thing? Why not?

**Comment by jcar87** [comment]
> But according to the original report, the cmake helper does not need to do any such thing? Why not?

CMake allows overriding the install prefix when calling the `cmake --install` command to perform the installation (docs [here](https://cmake.org/cmake/help/v3.24/manual/cmake.1.html#install-a-project)). This is what we use in the newer CMake integration. 

With CMake-generated projects, one could also do `make install`/`ninja install` or `cmake --build . --target install`, and changing the `CMAKE_INSTALL_PREFIX` would require invoking CMake again to reconfigure and re-generate the project. 

This is similar to defining the `DESTDIR` (docs [here](https://www.gnu.org/prep/standards/html_node/DESTDIR.html)) environment variable when calling `make install` in GNU-compliant projects,  so calling `./configure --prefix=` is not needed.

One caveat that is worth mentioning, is that some projects take the value of the install prefix and embed it in compiled code - calling `cmake --install . --prefix=` or `DESTDIR=xx make install` will not cause the build tool to override what has already been compiled, whereas re-configuring the project with the new path would.

**Comment by eli-schwartz** [comment]
> One caveat that is worth mentioning, is that some projects take the value of the install prefix and embed it in compiled code - calling `cmake --install . --prefix=` or `DESTDIR=xx make install` will not cause the build tool to override what has already been compiled, whereas re-configuring the project with the new path would.

That's ***exactly*** why DESTDIR exists, because prefix is ***semantically*** information that can be embedded in compiled code, and DESTDIR is, semantically, not allowed to be embedded in compiled code.

**Comment by franramirez688** [comment]
As far as I tested locally, adding the `DESTDIR` is not avoiding the reconfigure process, so I'm afraid we can't improve this now.

**Note**: another issue is to add that `DESTDIR` or the `--destdir xxxx` param (since Meson 0.57) in the Meson helper. That's a new issue and it could be done for sure.
