### ISSUE TITLE
[bug] Conan deletes recipe from cache if `conan download` is unable to find recipe

### ISSUE THREAD

**Issue by iaavo** [conan-io/conan#11914]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: N/A
  * Conan version: 1.51.3
  * Python version: 3.9.12

### Steps to reproduce (Include if Applicable)

```sh
conan new testbug/1.0.0
conan export .
conan download testbug/1.0.0@_/_ --remote conancenter  # this will delete the recipe from the local cache, since testbug/1.0.0 does not exist on conancenter
conan inspect testbug/1.0.0   # does not find the testbug/1.0.0 package recipe
```

If you use `export-pkg` then the package folder will remain in the cache after `download`

**Comment by memsharded** [comment]
Hi @iaavo 

Thanks very  much for reporting this issue.

This seems bad UX, but also not critical. When running a ``conan download`` of a given package, it seems that Conan 1.X is assuming that it is not in the cache, and if it is, it has to be replaced with the downloaded one, which seems expected. So ``conan download`` is assumed to be a destructive command for local cache package.

I think it is not worth trying to change this in 1.X scope, but I'd like this to be tested against 2.0, and if it is still the case (maybe it is not, as Conan 2.0 is using revisions by default, this might not happen), then we could try to have a deeper look.

**Comment by iaavo** [comment]
Hi @memsharded 

Thanks for the quick reply. I agree it's definitely not a critical issue. Though it did cause a few headscratches on my end as I kept wondering why my local cache is ending up in an inconsistent state (since the `export` folder gets deleted, but the `package` folder remains as does the `metadata.json` file). 

I think the issue would be resolved if it was at least mentioned in the documentation of the `conan download` that it will delete the recipe in the local cache if it does not find the recipe to be downloaded.

**Comment by memsharded** [comment]
This should be solved in Conan 2, closing the ticket as outdated.
