### ISSUE TITLE
[bug] Says one revision but uses incorrect revision

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan#11913]
### Environment Details (include every applicable attribute)
  * Linux Debian Bullseye
  * clang 11
  * conan 1.48.2
  * python 3.10

### Steps to reproduce (Include if Applicable)
This morning our conan build went wrong
we require `xxhash/0.8.1@#285da44b24e11d9f36f7d0fc23a1734a`
build says
```
xxhash/0.8.1: Downloaded recipe revision 285da44b24e11d9f36f7d0fc23a1734a
ERROR: xxhash/0.8.1: Cannot load recipe.
Error loading conanfile at '/opt/wire/.conan/data/xxhash/0.8.1/_/_/export/conanfile.py': Current Conan version (1.48.2) does not satisfy the defined one (>=1.50.0).
```
but `285da44b24e11d9f36f7d0fc23a1734a` revision does not have that requirement yet   `bbf2867eb2cfe186d9bc857da8e00752` does

**Comment by memsharded** [comment]
This is super weird, and it seems it will be really difficult to reproduce.
I guess that if you remove the package, either with ``conan remove`` or removing the cache, it will be fixed. 
Maybe if you pass the ``--update`` it will be fixed. Does it happen now all the time if you repeat the last command? (is it a install, a create, a info command?)

Can you please share the ``metadata.json`` file that you can find inside the cache folder for that package?

**Comment by Ignition** [comment]
Maybe false alarm...I think devops forgot `CONAN_REVISIONS_ENABLED=1`

**Comment by Ignition** [comment]
I'll try to reproduce locally, but this was on a CI machine I don't have access to.
But either way, strange to say it downloaded `285da44b24e11d9f36f7d0fc23a1734a` but use `bbf2867eb2cfe186d9bc857da8e00752`

**Comment by Ignition** [comment]
Maybe need for a warning ie. `requested 285da44b24e11d9f36f7d0fc23a1734a but revisions isn't enabled`

**Comment by memsharded** [comment]
Ok, great to hear that, please keep us posted.
