### ISSUE TITLE
[feature] Port `stdcpp_library()` to conan v2

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11912]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

There are 47 recipes in conan-center relying on `stdcpp_library()` (mainly to append C++ standard lib to system_libs in package_info() for C++ static libs with C API).

**Comment by SSE4** [comment]
that might be better to change UX in v2 to return a list of libraries, just in case. on certain platforms, several libraries might be required in future (libc++, libc++abi, libsupc++, libc++fs, atomic and so on).
