### ISSUE TITLE
[feature] add support for per recipe config in profile

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#11918]
Hello,

According to https://docs.conan.io/en/latest/reference/profiles.html, it is possible to define per recipe options, settings and env vars in a profile. 
```
[settings]
zlib:compiler=clang

[env]
zlib:CC=$CLANG/clang
```

It we be also great if we can define config per recipe as well, something like
```
[conf]
*:tools.cmake.cmaketoolchain:generator=Ninja
zlib:tools.cmake.cmaketoolchain:generator=Visual Studio 16 2019
```
The reason is, when doing cascade build, we need to use different generators for different dependencies.

**Comment by franramirez688** [comment]
Hi @boussaffawalid 

I believe that it's already possible to do that. Have you already tried it? Perhaps it's something missing in the documentation, or we'd need to add that behavior.

**Comment by boussaffawalid** [comment]
@franramirez688 I tried it and it is just ignored

**Comment by memsharded** [comment]
This is weird. There are several tests in https://github.com/conan-io/conan/blob/develop/conans/test/integration/configuration/conf/test_conf_profile.py like https://github.com/conan-io/conan/blob/81d4fed6a98dc95640d8043a4390dc51832200b3/conans/test/integration/configuration/conf/test_conf_profile.py#L80 that seems to validate that this works

It seems you are missing the ``zlib*`` pattern. New matching requires the ``*``, it will not match ``zlib:...``. Please try it.

**Comment by boussaffawalid** [comment]
First test:
```
[conf]
zlib:tools.cmake.cmaketoolchain:generator=Visual Studio 16 2019
*:tools.cmake.cmaketoolchain:generator=Ninja
```
==> Does not work

---
Second test:
```
[conf]
*:tools.cmake.cmaketoolchain:generator=Ninja
zlib:tools.cmake.cmaketoolchain:generator=Visual Studio 16 2019
```
==> It works

I seems like the order of config matters, per recipe config needs to be defined after global config.

**Comment by franramirez688** [comment]
Yes, it works as expected then.

**Comment by boussaffawalid** [comment]
Maybe just update the documentation. Thanks.
