### ISSUE TITLE
[feature] `is_msvc`: add an argument to check compiler from `settings_build` instead of `settings`

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11926]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

When `is_msvc` is used in `build_requirements`, it might mean under the hood a recipe logic related to compiler from build profile (for example here: https://github.com/conan-io/conan-center-index/blob/9fb9007dd2319906d3a5c1be9e60529f3ac02c66/recipes/gsoap/all/conanfile.py#L48-L56, with an unusual 2 profiles like msvc in build profile and mingw in host profile, this recipe would break). But `is_msvc` always checks compiler from host profile.
It would be useful to add an additional optional argument to check compiler from build profile instead.

**Comment by memsharded** [comment]
And this is exactly what we were commenting the other day @jcar87 

Still @SpaceIm  for a ``tool_requires``, the ``self.settings`` from its "host" received profile will be the "build" profile.
It is just in ConanCenter that the 2 profiles are not used yet that this not works properly.

**Comment by SpaceIm** [comment]
Thanks for the quick answer @memsharded 

I've updated my issue with an example.

So let's say we have such code in a recipe:

```python
    def build_requirements(self):
        if is_msvc(self):
            self.tool_requires("winflexbison/2.5.24")
        else:
            self.tool_requires("bison/3.7.6")
            self.tool_requires("flex/2.6.4")
```

The true logic I would like is:

```python
    def build_requirements(self):
        if self.settings_build.compiler in ["msvc", "Visual Studio"]:
            self.tool_requires("winflexbison/2.5.24")
        else:
            self.tool_requires("bison/3.7.6")
            self.tool_requires("flex/2.6.4")
```

Are you sure that there are equivalent. I know that `winflexbison`, `bison` & `flex` will be called with build profile, but I still think that the branching logic in the parent recipe is different in these 2 examples.

**Comment by memsharded** [comment]
Oh, now I see what you mean, is not in the dependency package itself, but to generate the condition.
Lets have a look and think what would be the best interface, as this will happen with other tools too, not only this one.
