### ISSUE TITLE
[question] apply_conandata_patches handling some types

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11923]
Current implementation is:
```python
    if isinstance(patches, dict):
        assert conanfile.version, "Can only be applied if conanfile.version is already defined"
        entries = patches.get(str(conanfile.version), [])
    elif isinstance(patches, Iterable):
        entries = patches
    else:
        return
```
So it will silently skip ``patches`` field in conandata.yml with unexpected types? If the type is a string (possible user mistake), it will fail uglyly as considered ``Iterable``?

**Comment by memsharded** [comment]
Lets force to be dict or list, or raise an error otherwise

**Comment by SSE4** [comment]
I think it's not that "pythonic" to check for the specific types here, it would be better to just check if given type implements a trait/concept we need (like Iterable).
we shouldn't unnecessarily restrict users who like/need/want to write a generator/co-routine returning patches.

**Comment by memsharded** [comment]
@SSE4 ``def apply_conandata_patches(conanfile):`` takes the information always from ``conan_data``, so it cannot implement such generator or co-routine.

Besides that, the concept ``Iterable`` will be true for strings, and it will try to use every one of the characters of the string as an input, and produce an ugly and difficult to understand error message.
