### ISSUE TITLE
[bug] Cached login expires

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#11925]
We use baselined VMs to do our build/test. During the vm configuration, we set the user/pass via `conan user` using a artifactory token which we set not expire (although this still shows 365 days expiration...but I digress). However, we are finding that the login still seems to expire (maybe after 30 days?). We can launch the baseline, login again using the same token, and then it continues to work...so it doesn't appear to be a problem with the token. Is there a way to prevent this?

### Environment Details (include every applicable attribute)
  * Operating System+version: Both Windows 10 and RHEL 7
  * Compiler+version: n/a
  * Conan version: 1.48
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)
1. login to remote using non-expiring token
2. wait 30 days
3. login stops working

**Comment by memsharded** [comment]
Hi @rconde01 

There are 2 tokens involved here:
- The server token you are using as "password" to auth
- A "jwt" token that is stored and cached to avoid using the main password or token over and over at every API request, which would be super annoying

The jwt had an issue in Artifactory and it never expired IIRC, so it was a security issue. Now it is defaulted to 30 days. I think this can also be changed in some Artifactory configuration, but I am not sure it is great to make it non-expiring, as that  wouldn't be a security best practice.

That means there is nothing in the client related to expiring tokens, everything is server side. What you could do is to define the conan CONAN_PASSWORD env-var with the token value, and it will re-auth from the client when necessary.

**Comment by Nekto89** [comment]
@memsharded is there some way to give user a better error in case of token expiration? Currently our Artifactory instance doesn't ask explicitly for credentials so user sees "ERROR: Unable to find 'library/version@user/channel#recipehash' in remotes ?".

maybe conan can store expiration date for "jwt" token?

**Comment by Nekto89** [comment]
maybe conan can store expiration date for "jwt" token?

**Comment by tbsuht** [comment]
> is there some way to give user a better error in case of token expiration? Currently our Artifactory instance doesn't ask explicitly for credentials so user sees "ERROR: Unable to find 'library/version@user/channel#recipehash' in remotes

@memsharded this is the same problem we face on developer machines. and it always takes some minutes to recognize that you didn't use a wrong package reference but the login expired. Is there a way to signal this to the user?

Also when using `conan user` this will show something like this:
```
Current user of remote '...' set to: '...' [Authenticated]
```
which states that you are authenticated although the token expired.

**Comment by memsharded** [comment]
The ``conan remote auth`` command was introduced in Conan 2.0 to force a real authentication in the servers, forcing users to re-enter credentials if necessary or erroring. That would be useful for that.

Otherwise, if it is important for developers to be authenticated in the servers, it would be recommended to disable anonymous read access from those servers.

**Comment by memsharded** [comment]
> is there some way to give user a better error in case of token expiration? Currently our Artifactory instance doesn't ask explicitly for credentials so user sees "ERROR: Unable to find 'library/version@user/channel#recipehash' in remotes ?".

PR #17127 will throw an authentication challenge (of fail if ``non_interactive``) it the token expires, solving the issues above. Still this can also be changed in the server side configuration by disabling anonymous usage all together.

Marking this ticket to be closed by #17127 for next Conan 2.9, thanks for the feedback.

**Comment by memsharded** [comment]
This was closed by https://github.com/conan-io/conan/pull/17127, which will be in next Conan 2.9
