### ISSUE TITLE
[feature] Revoke or Expire Login Tokens

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#11932]
I have a use case where I am installing conan packages in a docker image.  In the docker file, we log into the remote (with credentials) and logout.  I am using docker build secrets, so I can ensure that the artifactory password is not leaked in the image.  However, it is more difficult to prevent the leaking of the login token.

My understanding is that when I run `conan user ...` or `conan remote login ...`, conan will authenticate to artifactory.  Artifactory creates an access token that expires in 30 days (possibly set by user-invitation-token-expiry-secs in artifactory access yml).  It does not appear that the expiry time is controllable from conan nor can I revoke the token from conan.  Logging out of the remote does appear to remove the token from the local db.

A typical user would write a Dockerfile with (in conan v2.0):
```
RUN conan remote login ...
RUN conan install ...
RUN conan remote logout ...
```

In docker, every layer is accessible in an image.  Thus, even though the access token wouldn't be accessible in the final layer, it would be in previous layers.

It would be nice to have more control over these tokens from the conan command line.  I'm guessing the easiest way to do it would be to add an `expires-in` parameter to `conan remote login`.
```
conan remote login <remote> <user> --expires-in=30m
```

It would also be acceptable to allow for token revocation from the command line.
```
conan remote revoke <remote>
```

I'm open to other possibilities.  The goal just being to make it easier to protect access tokens.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jsallay 

Just a clarification. The token that Conan stores is a JWT token, exclusively for the Conan API, it is not a full artifactory access token/login token. Conan will never store a user password or access token, only the JWT token generated by the Conan server API.

Revoking tokens or defining of expiration time in the client seems challenging, as the client does not generate the tokens, so it should forward the expiration time to the server and the server use it (or not, according to its own rules). This is orders of magnitude more difficult, as there is no server API for it, so it means changing the server API, and servers need to implement it. I don't think this will be in scope.

I would expect that ``conan remote logout`` (I guess that you are talking and using Conan 2.0-beta.2?) will effectively remove the token from the Conan cache, and hopefully that, together with the definition of expire time in the server, that can be shortened to less than 30 days, would be enough for a reasonable security.

**Comment by jsallay** [comment]
Thanks for the clarification about the JWT token.  I was assuming that it was storing the access token.  I had hoped that it would be easier since there is are curl commands for managing tokens in artifactory (.https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API?_gl=1*ig5gjv*_ga*NTc0MjM4MzcxLjE2Mjc1ODQ4NjU.*_ga_SQ1NR9VTFJ*MTY2MTE4MjYzMy42Ny4xLjE2NjExODMzNjQuNjAuMC4w#ArtifactoryRESTAPI-AccessTokens).

I am sure that using the JWT token complicates the use case.

To be clear, in a "normal" environment, `conan remote logout` will be sufficient.  The issue comes from using a docker image.  Every command in a Dockerfile becomes a layer.  Each layer is accessible independently.  So having `RUN conan remote logout` in the Dockerfile will remove the JWT token from the final image, but the token is still accessible from looking at a previous layer.

**Comment by memsharded** [comment]
> I am sure that using the JWT token complicates the use case.

Yes, but it is not only that it is JWT, it is even if was a normal access token. Conan has its best integration with Artifactory, because Artifactory implements the Conan protocol. But such protocol is agnostic of the server, it cannot implement calls like that Curl call that will only work with Artifactory, and not the other servers, and it should be implemented in the Conan protocol via a new http api (probably means versioning the api), and that requires a lot of effort in server implementors, which would take many months in the best case.

I am thinking, but I don't see any possible way that we could avoid that effect in the docker layers. The only practical possibility that I see is configuring Artifactory with a relatively short-lived JWT token.

**Comment by jsallay** [comment]
Thanks, now I understand.  That makes sense.  I have discovered that Artifactory has a vault plugin that produces short lived credentials which fits my use case.  https://github.com/jfrog/artifactory-secrets-plugin

I'll go ahead and close the issue.  Thanks.

**Comment by memsharded** [comment]
Thanks for the feedback!
