### ISSUE TITLE
[question] Use Release version of for other Configuration

### ISSUE THREAD

**Issue by pcbk** [conan-io/conan#11947]
We have added another configuration that should use Release Packages, there is no need to build other version of packages, we just added extra logging flags to the added Config that should use Release packages.

We are using cmake_find_package_multi for windows/MSVC builds and when we build our own config there is no Includes or links set up since there is no: XYZTarget-myconf.cmake. How can I get my Config to use Release?

Also tried CMakeDeps instead of cmake_find_package_multi but cannot find any setting for this issue

**Comment by memsharded** [comment]
Hi @pcbk 

When you install, you specify the packages you want to install with ``conan install ... -s build_type=Release``. That will make the dependencies to be Release packages. If you need the consumer to use a different type than the dependencies, you need to tell it something like: ``conan install ... -s &:build_type=MyConf``. Have you tried that?

**Comment by pcbk** [comment]
Hi, but I don't want to build all packages with Config MyConf, just want my project to use Config Release when building Config MyConf, so there is a:

set_property(TARGET gtest::gtest
             PROPERTY INTERFACE_LINK_LIBRARIES
             $<$<CONFIG:**MyConf**>:${gtest_LIBRARIES_TARGETS_**RELEASE**} ${gtest_OBJECTS_**RELEASE**}> APPEND)

genereated

**Comment by memsharded** [comment]
Dont worry about the name. The generated files contain the names of the **consumer** build type, because CMake is evaluated for the consumer build_type, not the dependencies. If you follow the paths defined in the files, the "MYCONF" configuration they will be pointing to the Release dependencies.

**Comment by pcbk** [comment]
tried: conan install ../conanfile_windows.txt -s &:build_type=MyConf
get: conan install: error: argument -s/--settings: expected 1 argument
ERROR: Exiting with code: 2

**Comment by pcbk** [comment]
Now I got it to work! I added:
```
build_type=Release
&:build_type=MyConf
```
to the Profile file for MyConf and got a XYZTarget-myconf.cmake generated! Thanks!

**Comment by memsharded** [comment]
Great to know that it is working now! 
The first error could be because of command line parsing, you can try quoting, like ``-s "&:build_type=MyConf" -s build_type=Release``. In any case, it is better to have things in profile files than in command line, so good job.
