### ISSUE TITLE
Installing openssl-1.1.1q: "certificate verify failed: unable to get local issuer certificate"

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#11965]
Hello
conan client 1.50.2
OS: Ubuntu 22.04.1 WSL

When trying to install openssl-1.1.1q i get this error:
```
openssl/1.1.1q: ERROR: Error downloading file https://www.openssl.org/source/openssl-1.1.1q.tar.gz: 'HTTPSConnectionPool(host='www.openssl.org', port=443): Max retries exceeded with url: /source/openssl-1.1.1q.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'
openssl/1.1.1q: Waiting 5 seconds to retry...
openssl/1.1.1q: WARN: Could not download from the URL https://www.openssl.org/source/openssl-1.1.1q.tar.gz: Error downloading file https://www.openssl.org/source/openssl-1.1.1q.tar.gz: 'HTTPSConnectionPool(host='www.openssl.org', port=443): Max retries exceeded with url: /source/openssl-1.1.1q.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'. Trying another mirror.
openssl/1.1.1q: ERROR: Error downloading file https://www.openssl.org/source/old/openssl-1.1.1q.tar.gz: 'HTTPSConnectionPool(host='www.openssl.org', port=443): Max retries exceeded with url: /source/old/openssl-1.1.1q.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'
openssl/1.1.1q: Waiting 5 seconds to retry...
wopenssl/1.1.1q: WARN: Could not download from the URL https://www.openssl.org/source/old/openssl-1.1.1q.tar.gz: Error downloading file https://www.openssl.org/source/old/openssl-1.1.1q.tar.gz: 'HTTPSConnectionPool(host='www.openssl.org', port=443): Max retries exceeded with url: /source/old/openssl-1.1.1q.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'. Trying another mirror.
ERROR: openssl/1.1.1q: Error in source() method, line 248
        get(self, **self.conan_data["sources"][self.version],
        ConanException: All downloads from (2) URLs have failed.
```

When trying `wget  https://www.openssl.org/source/openssl-1.1.1q.tar.gz` the file is received as expected.
I am on a coorporate network behind zscaler, but as wget works I expect that is not the problem here.

What could be wrong?

Rgds
Klaus

**Comment by memsharded** [comment]
Yes, this is typically a zscaler configuration issue. We have experienced this ourselves, and was solved by IT adding the configuration to zscaler. It is possible that in your case there is already some configuration exception explicitly for wget

**Comment by klausholstjacobsen** [comment]
Thansk for the info.
What do you exactly mean by "adding the configuration to zscaler"?
What should I exactly ask my IT to add to the zscaler configuration?

**Comment by memsharded** [comment]
We send them the URL, like ``https://www.openssl.org/`` to make the exception.

**Comment by klausholstjacobsen** [comment]
Are we this problem is about adding https::www.openssl.org to a whitelist.
The error I am seeing is "unable to get local issuer certificate".
To me that indicates that another certificate store is used than the one installed on the system.
I do have the zscaler root certificate installed in /etc/ssl/certs

Downloading the file manually with python also works fine;
```
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.get('https://www.openssl.org/source/openssl-1.1.1p.tar.gz')
>>> f = open('my.tar.gz', 'wb')
>>> f.write(r.content)
9860217
>>>
```

Could this be an issue with conan using another certificate store than the system one? 
Just guessing....I am not much of a certificate guy!

**Comment by memsharded** [comment]
Uhmm, is it possible that you have still a legacy cert in your system? Can you please make sure to remove the ``cacert.pem`` file in your Conan cache and retry?

**Comment by klausholstjacobsen** [comment]
SUCCESS!!!!!!!!!!!!!!

There was a cacert.pem file in the .conan dir.
Removed it....it didn't help.

Created a symlink to the system certificate store `ln -s /etc/ssl/certs/ca-certificates.crt $HOME/.conan/cacert.pem` and presto, conan could download the file.

Is this symlink the way forward or is there a better way to get conan to use certificates installed on the system?

**Comment by memsharded** [comment]
Excellent!!! 👏 

> Is this symlink the way forward or is there a better way to get conan to use certificates installed on the system?

I think it is in your case and while in Conan 1.X. Maybe you have some custom certificates installed in your machine?

Conan 2.0 has already removed this file, so the system ones should automatically work without issues.

**Comment by klausholstjacobsen** [comment]
Yes, I have custom certificates installed.
I will stick with the symlink approach for now.

Thx!
