### ISSUE TITLE
[feature] MSBuild add upgrade_project again

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#11967]
Continuing https://github.com/conan-io/conan/issues/11966

The new [MSBuild](https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html#msbuild) didn't port `upgrade_project` attribute from old [MSBuild](https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html#build).

Motivation: I started to port [xz_utils](https://github.com/conan-io/conan-center-index/pull/12308) recipe and it comes with .sln files, and when need to build using the new MSBuild, the expected SDK version is older, and it would be great if I could update the .sln file automatically.

I think it should be a MSBuild attribute as it should not change:

    msbuild = MSBuild(self)
    msbuild.upgrade_project = True (default True)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I didn't like very much the default previous ``True``, that was running a ``devenv /upgrade`` always, and it had to add an env-var to disable it, but that would be global with its own disadvantages. I don't think that is the expectation from most users that use MSBuild for their own projects.

I am thinking of making it an opt-in method to ``MSBuildToolchain``, to be called ``MSBuildToolchain.update_project()``, wdyt? This way it runs at ``generate()`` time, so it would be good for developer flow too.

**Comment by uilianries** [comment]
@memsharded Yes, it sounds good, as it's a single usage option and it's more related to generate than msvc commands.

**Comment by memsharded** [comment]
It doesn't seem that natural to run this in the ``generate()`` method as part of ``MSBuildToolchain``.
I am checking the implementation, and happens to be trivial:

```python
 command.append('devenv "%s" /upgrade &&' % project_file)
```

I think this can be implemented in recipes directly without issues:
```python
def build(self):
     self.run("devenv myproject.sln /upgrade")
     ...
```

I think this should be enough atm for ConanCenter recipes, and if we receive further feedback from other users regarding this feature, we would reconsider adding this built-in.

**Comment by uilianries** [comment]
What about VirtualBuildEnv? Does it require `conanbuild` env by default?

**Comment by memsharded** [comment]
``self.run()`` defaults to ``self.run(..., env=["conanbuild.bat|sh"])``, being ``conanbuildenv`` script generated by ``VirtualBuildEnv``, and automatically added to ``conanbuild`` aggregator. So as long as ``self.run()`` is executed after ``generate()`` of ``VirtualBuildEnv`` (explicit or implicit via ``auto_use`` conf), it should work

**Comment by uilianries** [comment]
@memsharded Excellent then. I would be great an example on docs.conan.io, just in case people arrive to the same situation.
