### ISSUE TITLE
add the `PKG_CONFIG_PATH` via CMake build helper or even CMakeToolchain

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#11962]
In https://github.com/conan-io/conan-center-index/pull/12241 there was some wonky code to get the pkg_config support in CMake to work with the new generators 

Part of the conversation (and linking to the solutions) seems like it could be continued here

***

> For some reason, pkg_check_modules tries to find .pc files not in the generator_folder, but in the generator_folder/lib/pkgconfig.

After digging deeper into it, I figured out that CMake is adding the suffix `lib/pkgconfig` to the `CMAKE_PREFIX_PATH` (pointing to the `package_folder` where the `*.pc` files are created). You can have a look at the issue https://gitlab.kitware.com/cmake/cmake/-/issues/18150

> I thought the PkgConfigDeps generator should resolve that (via env vars maybe), but it doesn't

Yes, you're right, but it should not be necessary as far as CMake should use that `CMAKE_PREFIX_PATH` by default. As I said above, CMake is adding that suffix, so it's getting failed because there are no PC files there.

> is this the right way to use CMakeToolchain and PkgConfigDeps generators together?

Given that information, I tend to say that yes, it could be one way to solve that issue, and I think there could be another workaround like:

```python
    def build(self):
        pkg_lib_folder = os.path.join(self.generators_folder, "lib", "pkgconfig")
        copy(self, "*.pc", self.generators_folder, pkg_lib_folder)
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```
Anyway, we could discuss if it could be a chance to create a mechanism to add the `PKG_CONFIG_PATH` via CMake build helper or even CMakeToolchain to avoid those workarounds.

_Originally posted by @franramirez688 in https://github.com/conan-io/conan-center-index/pull/12241#discussion_r955000431_

**Comment by jwillikers** [comment]
I'm trying to support cross-compilation of the `glib` Conan package and ran into problems with the test package, which uses `pkg_check_modules` to link against `glib`. The test package consistently finds the system's PkgConfig files in this scenario instead of those provided by Conan. If I just use the CMake targets from the CMake config modules, cross-compilation works. I think this may be related to this issue.

**Comment by prince-chrismc** [comment]
Seems the workaround is not enough for all cases https://github.com/conan-io/conan-center-index/pull/13113/files#diff-8289c891f895abff6d3967ba098831643a3e8fa06472013c3ade6704c9206cb9R112-R117

**Comment by franramirez688** [comment]
@memsharded A few points about this issue and its possible solutions to discuss them:

* Via `CMakeToolchain`: adding this line `set(ENV{PKG_CONFIG_PATH} {{ package_folder }} )
` directly.
* Via `cmake-presets`: adding to the `environment` section the variable `PKG_CONFIG_PATH` (I have read some problems about its usage but am not 100% sure).
* Via `CMake` build helper: running the environment variable before the cmake command, i.e.,  `PKG_CONFIG_PATH=pc/folder/ cmake xxxxxxxxx`.
* Via `VirtualBuildEnv`: perhaps, if there would be a kind of method to add it automatically easily. This way could be applied by any other tool as well.

I don't really know what could be the "best way" so I'd prefer to discuss it before starting any draft.
