### ISSUE TITLE
[develop2] deployers that could run after generators

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11978]
Lets say that we want to relativize all paths in generated files from CMakeDeps, so we get a relocatable folder with all we need. There are 2 options:
- Make the ``CMakeDeps`` automatically relativize paths when possible
- Run something **after** the generators that relativize paths in files

the problem is that deployers run always before generators (so they can change the base folders, so generators use the deployed folders and not the cache ones). We could think of "post" deployers, or maybe lets call "installers". For example if we want to automate the zip of everything, including the CMakeDeps generated files, it needs to run after the generators. 
The implementation would be very similar to ``deployers`` just differ in the running point.

**Comment by lasote** [comment]
I see a challenge in both alternatives, we would need to implement it for each generator we need to support, it doesn't look like something that we can make work for all of them. Are you suggesting only for `CMakeDeps`?

Edit: I got a bit lost on the purpose of this issue. If this is about running post-deployers, that's simple and doable but the challenges would be moved to the custom implementation of the post-deploy. If we would like to get the generators kind of prepared for that use case then the challenges would be in our side.

**Comment by memsharded** [comment]
Probably this is not worth, the request hasn't been done by users.

Most likely custom commands are used for any advanced deployment use case, and that allows any arbitrary order and complex operations. Closing as not planned
