### ISSUE TITLE
[question] Create a package from a pre-built binary

### ISSUE THREAD

**Issue by valeriomoroni95** [conan-io/conan#11984]
I'm pretty new in the Conan world and I'm using it in order to accomplish to some specifications for my master thesis.
My use case scenario could be resumed as follows:
- I have a c++ code and, once compiled locally without Conan, but with CMake, I've to package it in order to upload it on Artifactory, on a local remote.
- I've tried to follow many guidelines on the documentation, but I wasn't able to understand how I've to package my binary, since everything I read concerns the default "Hello" example.
- The question is: how should I customise the "conanfile.py" to make it suitable for me? Is the conanfile.py the only file I need to write or is it necessary to have any others? Is there a pipeline to follow so that I can create my package each time from this scenario? Are there many Conan commands which I'm missing?

These are the information written in the "conaninfo.txt":

[settings]
    arch=x86_64
    build_type=Release
    compiler=apple-clang
    compiler.libcxx=libc++
    compiler.version=11.0
    os=Macos

Thank you very much for your help! I appreciate it a lot.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @valeriomoroni95 

If you have pre-compiled binaries, then you need to read: https://docs.conan.io/en/latest/creating_packages/existing_binaries.html

- If you have the binary local in your folder, then use ``conan export-pkg`` command
- If you have the binary somewhere else, like in an http server, you can download that binary in the ``build()`` method, and run a normal ``conan create``

**Comment by valeriomoroni95** [comment]
Thank you very much @memsharded!

It helped me a lot. Where can I learn where to customise the recipes, in order to apply this pattern to each package I'll need to create?

**Comment by memsharded** [comment]
The main general learning resources how to write recipes are the docs, the free courses in the academy https://academy.jfrog.com/path/conan, and maybe the recipes in https://github.com/conan-io/conan-center-index are also interesting for more advanced (sometimes very advanced, as these contain the most difficult to package third parties out there) use cases.

In the docs, for specifics about the ``package()`` method, for example, always go to: https://docs.conan.io/en/latest/reference.html. If you want to be sure of using the new tooling, check the https://docs.conan.io/en/latest/conan_v2.html

**Comment by memsharded** [comment]
Sorry, I accidentally closed. Feel free to close it yourself when you think it is responded.

**Comment by valeriomoroni95** [comment]
Thank you so much @memsharded!
