### ISSUE TITLE
[question] CMakeToolchain & layout: how to run CMake twice with different variables & build folder?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11985]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In conan-center, if shared=True `spirv-cross` recipe needs to run the build twice with different build folder & variables, to build both the library and tools (because tools can't link to shared lib, so the second build forces static build and the build of tools, while the first one builds shared libs only and disables tools): https://github.com/conan-io/conan-center-index/blob/304d808ff74d68da12802fb88417a255d5de269e/recipes/spirv-cross/all/conanfile.py#L88-L137

How to achieve the same logic with layout & CMakeToolchain?

**Comment by memsharded** [comment]
Why not limiting the binary to static linkage only? What is the use case of using such a package that contains a .dll, but an .exe that is not using that .dll at all? As the executable app doesn't make sense in the host context together with the library, and the library cannot be linked from build context, I don't see a real reason to not limit it.

**Comment by SpaceIm** [comment]
Because tools of spirv-cross rely on private symbols of spirv-cross libraries, but spirv-cross libraries are perfectly usable by external consumers relying on public symbols.

Moreover you can't know in which context consumers will use this recipe, and since conan-center has decided to package libraries & tools together, there is no other choice.

It makes the recipe consistent for consumers with default options: either shared or static libs, and tools packaged (always linked to static libs, but who cares?).

**Comment by memsharded** [comment]
> Moreover you can't know in which context consumers will use this recipe, and since conan-center has decided to package libraries & tools together, there is no other choice.

I think this was probably not the best approach, I didn't think it back then, and I still think today that many things would probably be way easier for us and for users if we packaged tools and libraries in separate packages, as other systems (debian, or protobuf itself are doing for protoc, for example) have been doing before Conan.

> It makes the recipe consistent for consumers with default options: either shared or static libs, and tools packaged (always linked to static libs, but who cares?).

How it is consistent for consumers to ``conan install spirv/version@ -o spirv*:shared=True``, to get an executable that doesn't depend on the shared library? What if they deploy it to some production thinking the shared library is part of the final release?

**Comment by SpaceIm** [comment]
> How it is consistent for consumers to `conan install spirv/version@ -o spirv*:shared=True`, to get an executable that doesn't depend on the shared library? What if they deploy it to some production thinking the shared library is part of the final release?

I think most users wouldn't care, and if they do they can check the runtime dependencies of their executable, because anyway nothing says that all executables packaged in a recipe link to all shared libraries packaged together (it can be none, only 1, 2 or all, and it's orthogonal to this issue). Most users would prefer by far to have tools if they have specified such option in a recipe, regardless of shared option.

**Comment by jcar87** [comment]
I have reviewed the build scripts of the library upstream, and from what I can see, the upstream scripts support setting  _both_ `SPIRV_CROSS_SHARED` and `SPIRV_CROSS_STATIC` to `ON`/`True`, and in particular the latter one is required to be enabled if `SPIRV_CROSS_CLI` is enabled.  Unlike many other libraries, this one generates two different sets of library names for static and shared and can coexist in the same build tree.

I see either of the two options as a possibility:

A) If `self.options.build_executable=True`, but the preconditions to build it are not true, make this an error condition and make validation fail. If building the executable requires `self.options.shared=False` and _also_ requires  some of the sub-libraries to be enabled, simply don't allow the build to continue. This is in line with the upstream build scripts, which will _fail_ the CMake configuration if the right settings are not enabled. I fail to see a case where the recipe should go above and beyond to configure CMake a second time when the upstream scripts already have error conditions for this. With Conan 2, for _executables_ we would expect the consumer to declare this as a build requires, so the build requires could have the `build_executable=True` and whichever compatible options needed to produce it. 

B) There is one case where if all the subcomponents are enabled, the upstream build scripts support building the _shared_ library, as well as the static subcomponents and the executable. So we could make it such that if  `self.options.build_executable` is set to `True`,  `self.options.build_executable=True`, and all other preconditions are true, we can implicitly enable `SPIRV_CROSS_STATIC` and then remove all the generated static-lib files in in the `package` method to abide by the Conan Center policy of only having one build variant per package.

**Comment by SpaceIm** [comment]
I didn't expect to argue about the logic of this recipe.
It has to do with conan-center policies:
- having tools disabled by default in a recipe due to static/shared is annoying because conan-center recipes should provide a pre-built binary these tools, and if not it may lead to issues in c3i build of other libraries having such kind of recipe in tool_requires (because c3i doesn't allow `-b missing`).
- libraries and tools are not separate recipes.
- shared & static not packaged together

These constraints have precedence over upstream internal build logic details.

> we can implicitly enable SPIRV_CROSS_STATIC and then remove all the generated static-lib files in in the package method to abide by the Conan Center policy of only having one build variant per package.

Yes, but I've implemented this logic in this recipe to exactly avoid further manipulation, because we have seen many times that removing either static or shared libs in package folder was fragile (and may not scale).

I would say they are workaround sure. So to go back to my initial question, I guess the answer is no?

**Comment by memsharded** [comment]
> having tools disabled by default in a recipe due to static/shared is annoying because conan-center recipes should provide a pre-built binary these tools, and if not it may lead to issues in c3i build of other libraries having such kind of recipe in tool_requires (because c3i doesn't allow -b missing).

How many other recipes require this package in ConanCenter as ``tool_requires``? I  can only find 2 other recipes with a regular ``requires``, not ``tool_requires``.
And if any of them did, lets recall that the default is also static libraries ``shared=False``, so even if some other package in ConanCenter wanted to use it as ``tool_requires``, it wouldn't be a problem either. Only if some users decided to define ``spirv:shared=True`` in their own private builds "build" profile (quite unlikely, isn't it), then, they will be told, "spirv executable doesn't work with shared=True". I think it is more than an acceptable tradeoff if it reduces the complexity of the recipe, the build time, etc.

>  So to go back to my initial question, I guess the answer is no?

Well, the ``layout()`` is exactly once per-configuration, it is not possible to define 2 different layouts for the same configuration. Also the ``generate()`` execute once per configuration, but the files it create can be totally defined by the user, if what you want to do is to create 2 different builds. You can call the ``cmaketoolchain.generate()``, copy to another location the generated scripts, then do a different ``cmaketoolchain2.generate()``, and you keep track of that so in the ``build()`` method, you can try with the ``build_script_folder`` argument, or creating your own ``self.run("cmake ...")`` command lines.  But Conan does not have built-in functionality for such a case.

**Comment by memsharded** [comment]
Closing as not planned atm.
