### ISSUE TITLE
[feature] Apple platforms - weak frameworks

### ISSUE THREAD

**Issue by kambala-decapitator** [conan-io/conan#11992]
Conan has convenient way to list frameworks to link against:

    self.cpp_info.components["..."].frameworks

Standard way to pass weak framework to linker doesn't work:

    self.cpp_info.components["..."].exelinkflags.append("-weak_framework CoreHaptics")

it's translated into

    -weak_framework  -lCoreHaptics

The only other (and working) way is using `-Wl,-weak_framework,CoreHaptics`, but it's rather tedious to type manually.

There can be multiple solutions:

- extend link flags properties to accept some kind of `ArgGroup` type
- add new `weak_frameworks` property similar to the existing `frameworks`
- extend `frameworks` property to accept some kind of `AppleFramework` type that would have an `is_weak` property
- just create a helper function like `linked_weak_framework(framework)` that would return `f"-Wl,-weak_framework,{framework}"`

This was briefly discussed in https://github.com/conan-io/conan-center-index/pull/12472#issuecomment-1224500256 and next comment.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @kambala-decapitator 

I'm not sure, but could it work if you put something like this?

```python
self.cpp_info.components["..."].exelinkflags.extend(["-weak_framework", "CoreHaptics"])
```

**Comment by kambala-decapitator** [comment]
@franramirez688 unfortunately, it's translated into the same incorrect flags as given in issue description:

```
[2/2] Linking CXX executable bin/test_package.app/test_package
FAILED: bin/test_package.app/test_package 
: && /Applications/Xcode13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -stdlib=libc++ -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode13.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -miphoneos-version-min=12.0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/test_package.dir/test_package.cpp.o -o bin/test_package.app/test_package  /Users/kambala/.conan/data/sdl/2.0.20/_/_/package/65553c176e6fcd7a27f83d72c6727d465a7ee564/lib/libSDL2main.a  /Users/kambala/.conan/data/sdl/2.0.20/_/_/package/65553c176e6fcd7a27f83d72c6727d465a7ee564/lib/libSDL2.a  -Xlinker -framework -Xlinker CoreVideo  -Xlinker -framework -Xlinker CoreAudio  -Xlinker -framework -Xlinker AudioToolbox  -Xlinker -framework -Xlinker AVFoundation  -Xlinker -framework -Xlinker Foundation  -Xlinker -framework -Xlinker QuartzCore  -Xlinker -framework -Xlinker UIKit  -Xlinker -framework -Xlinker OpenGLES  -Xlinker -framework -Xlinker GameController  -Xlinker -framework -Xlinker CoreMotion  -Xlinker -framework -Xlinker CoreGraphics  -Xlinker -framework -Xlinker CoreBluetooth  -Xlinker -framework -Xlinker Metal  /Users/kambala/.conan/data/libiconv/1.17/_/_/package/75bedc3bc6e140e570eea4ae41811a6642a16929/lib/libiconv.a  /Users/kambala/.conan/data/libiconv/1.17/_/_/package/75bedc3bc6e140e570eea4ae41811a6642a16929/lib/libcharset.a  -weak_framework  -lCoreHaptics && :
ld: framework not found -lCoreHaptics
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
ERROR: sdl/2.0.20 (test package): Error in build() method, line 21
	cmake.build()
	ConanException: Error 1 while executing cmake --build '/Users/kambala/dev/other/conan-center-index/recipes/sdl/all/test_package/build/0b7f6133efa2c510ac66b9d645b86cf2133fd9ff' '--' '-j6'
```

**Comment by franramirez688** [comment]
@kambala-decapitator which is the Conan generator that you're using?

**Comment by kambala-decapitator** [comment]
@franramirez688 I was testing on SDL package, I see it uses legacy CMake integration: https://github.com/conan-io/conan-center-index/blob/master/recipes/sdl/all/test_package/conanfile.py#L7

the command I used was:

```
CONAN_LOGGING_LEVEL=DEBUG CONAN_PRINT_RUN_COMMANDS=1 \
  conan create . sdl/2.0.20@ \
    --build=missing \
    --profile:build=default \
    --profile:host=ios-arm64 \
    -o "sdl/*:vulkan=False"
```

**Comment by franramirez688** [comment]
@kambala-decapitator 
We're making an enormous effort to migrate all the recipes to a Conan 2.x compatible format, so we're not maintaining the legacy generators anymore (only security bugs).

I think it would work fine with the new CMakeDeps if you add:
```python
self.cpp_info.components["..."].exelinkflags.extend(["-weak_framework", "CoreHaptics"])
```
We're encouraging everyone to use the new `conan.tools` generators so we can move forward with the next upcoming Conan 2.0.

**Comment by kambala-decapitator** [comment]
@franramirez688 changed SDL's test package to use CMakeDeps: yes, you're absolutely right, it works!

I guess the issue can be closed then?

**Comment by franramirez688** [comment]
@kambala-decapitator 

That's great news! So glad to hear it!

> I guess the issue can be closed then?

Yes, I think so.
