### ISSUE TITLE
[bug] command `conan profile path` sends final output to stderr, not stdout

### ISSUE THREAD

**Issue by thejohnfreeman** [conan-io/conan#11996]
The [documentation](https://docs.conan.io/en/2.0/whatsnew.html#new-cli) for the new CLI says this:

> The new CLI also sends all the information, warning, and error messages to stderr, while keeping the final result in stdout, ...

`conan profile path default` sends its only output, the desired path, to stderr, not stdout.

### Environment Details
  * Operating System+version: Ubuntu 22.04
  * Conan version: 2.0.0-beta2
  * Python version: 3.9.13

### Steps to reproduce

```
> conan profile path default >/dev/null
/home/jfreeman/.conan2/profiles/default
> conan profile path default 2>/dev/null
```

**Comment by memsharded** [comment]
Yes, it seems that this was lost somehow, maybe in one of the latest changes around the logging levels and the output.

Need to check with the team:
- Is the ``cli_out_write()`` still the recommended way in commands to output to stdout
- What part of what commands will be considered output and what not
- What to do with the ``text`` formatters in some commands
- Should the returned object by command be formatted by default to stdout with a ``str()`` or ``repr()``

**Comment by memsharded** [comment]
Rules (for maintainers team):
- If the command has any formatters, it cannot have ``cli_out_write`` or any printing to stdout from the command itself, everything has to happen via formatters.
- If commands has formatter like json, most likely it won't have a "text" formatter, because of stability of output

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/12054, will be in beta.3
