### ISSUE TITLE
[bug] `MesonToolchain` not compatible with meson < 0.55.0

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11997]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Monterey
  * Compiler+version: apple-clang 13.0
  * Conan version: 1.51.3
  * Python version: 3.10.6

### Steps to reproduce (Include if Applicable)

- checkout https://github.com/conan-io/conan-center-index/tree/1822d1c4c9dc431423d4583705914b98325a687d/recipes/meson/all (the first commit of https://github.com/conan-io/conan-center-index/pull/12727, migrating meson recipe to conan v2)
- run `conan create . meson/0.53.2@`

test_package (relying on `MesonToolchain`) fails, but it works for all version >= 0.55.0

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: Malformed value in cross file variable c_args.
```

**Comment by memsharded** [comment]
This is not a bug, this in on-purpose. MesonToolchain is only intended to support latest Meson versions.
Supporting/working with Meson 0.55 should be more than enough, that Meson version is 2 years old now, given it is still a 0.X (non stable release, it is more than enough)

**Comment by SpaceIm** [comment]
Ok, I've removed these old versions from meson recipe in CCI.

**Comment by SpaceIm** [comment]
I believe it would be worth to document the minimum meson version for which `CMakeToolchain` can generate a compatible native or cross-build file (in https://docs.conan.io/en/latest/reference/conanfile/tools/meson/mesontoolchain.html)
