### ISSUE TITLE
[question] Remove package revisions that have not been used for a certain period of time

### ISSUE THREAD

**Issue by Zvicii** [conan-io/conan#11990]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

My ~/.conan/data directory comtinues to grow, and some packages or some revisions of the packages are no longer required.
Is it possible for me to set a expire ttl for cached package revisions? When ttl is  reached, conan removes them automatically.

**Comment by memsharded** [comment]
Yes, Conan 2.X will implement some ``remove`` functionality based on LRU timestamps.

**Comment by Zvicii** [comment]
> Yes, Conan 2.X will implement some `remove` functionality based on LRU timestamps.

looking forward to it.

**Comment by memsharded** [comment]
At the moment, there are no LRU timestamps at all, so if anything you can do a ``conan search -revisions`` that will list the revisions timestamps and remove the old ones.

**Comment by memsharded** [comment]
Re-opening, to have this in the 2.X milestone backlog

**Comment by memsharded** [comment]
PR https://github.com/conan-io/conan/pull/14054 will close this as implemented, hopefully next Conan 2.0.14

**Comment by memsharded** [comment]
Conan has finally implemented this in https://github.com/conan-io/conan/pull/14054, it has been merged it will be in next 2.0.14 release!
