### ISSUE TITLE
[question] Artifactory cleanup for Conan artifactory?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11995]
Hi,

do you have any suggestion how to do cleanup on Artifactory servers? How does one cleanup "old" packages on Jfrog Artifactory repos?
Or does it have to be routed to Jfrog?
Thanks,

**Comment by memsharded** [comment]
Yes, this is mostly an Artifactory question. 
The Conan client knows how to remove things, by their reference. But it has no concept of "old" in Artifactory, what does "old" mean? Note that those packages might not have been created or uploaded by this Conan client.
But Artifactory has probably some properties, timestamps, that can be queried via their API or something like that for this purpose.

**Comment by harsszegi** [comment]
Thanks @memsharded !

**Comment by boussaffawalid** [comment]
@harsszegi you may find this useful https://github.com/devopshq/artifactory-cleanup#how-to-clean-up-conan-repository

**Comment by harsszegi** [comment]
Awesome, thanks a lot @boussaffawalid !!!
