### ISSUE TITLE
Must specify settings.build_type in build:host profile. Why?

### ISSUE THREAD

**Issue by chulup** [conan-io/conan#11994]
I can't find full description of settings that must be put into host profile vs build profile (I'm on conan 1.51.3).
It was a surprise for me when Conan required settings.build_type to be put in host profile. Why should it be there and not build profile?

Also I would be glad to find full docs on host profile and build profile.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
At the moment, the docs for the build/host profile are a bit scattered around, some links that might help:
- https://docs.conan.io/en/latest/reference/profiles.html#build-profiles-and-host-profiles
- https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer

The documentation in 2.0 will be much clearer about this, and will start introducing the build/host profiles topic very early in the tutorial, check https://docs.conan.io/en/2.0/tutorial/consuming_packages/cross_building_with_conan.html

The thing is that if the settings are needed or not, depends on the recipes using them. In your case, it seems some recipe in the host context needs to know the ``build_type``, to build itself, or to generate some files or information according to it.
The same could happen for a ``tool_requires`` recipe, for a recipe that lives in the "build" context and needs to build itself. Then it will probably need to know if it has to be built in Debug or Release mode and will request this setting to be defined in the "build" profile too.

**Comment by chulup** [comment]
Thank you.
It seems I have to provide build_type in both profile:host and profile:build by your links.
