### ISSUE TITLE
[Feature request] Allow installing through Homebrew on OS X

### ISSUE THREAD

**Issue by ldionne** [conan-io/conan#12]
It would be nice if we could install conan via [Homebrew](http://brew.sh) on OS X instead of downloading a `.pkg`.

**Comment by rhl-** [comment]
to start achieving this you can first create a separate homebrew tap, and then as it is popular, request it to be merged in..

**Comment by memsharded** [comment]
Yes, I think is  good idea to have it in brew. Maybe not necessary to creat a new tap, but use homebrew cask? what do you think about it?

**Comment by ldionne** [comment]
Personally, I would just create a formula and request it to be merged in Homebrew's main trunk, but I wouldn't care if it was in a tap too.

Homebrew casks are for .app applications, not simple command-line utilities. Clearly, `conan` is the latter, which brings me to a separate issue. Right now, conan installs a _bunch of stuff_ into your `/Applications/conan` directory, which is really bad-behaved for a command line utility on OS X. It would be preferable for it to be a self-standing executable (like every single command line tool I know), and to leave the `/Applications` folder alone.

Without exageration, I almost wet my pants when I saw this:
![conan-wtf](https://cloud.githubusercontent.com/assets/700834/11644540/f201581a-9d1a-11e5-91cc-a610e1147196.png)

This is definitely not the canonical way of installing command-line utilities on OS X.

**Comment by ldionne** [comment]
By the way, if you provide me with a sensibly-packaged command-line utility, I don't mind creating the Homebrew formula. I've done it before, and I think it might be easier for me since you guys don't seem to be on OS X.

**Comment by memsharded** [comment]
We are using pyinstaller to create the conan client application from a bunch of python files. All those files are packaged there by pyinstaller and are required to run the application. It is true that pyinstaller can create a "single executable" file, but it is kind of fake, as it is just a container for all those files, explodes it for every invocation, and then delete those temporary files. The result: it is sensible slower as command than the "exploded" installation, so we chose the "exploded" one for the installer, and as it lives inside a "conan" folder, having there lots of files didn't feel a problem.

Also, the installer contains 2 executables, the client and the server, not just one. Most of the shared libraries included within that installation folder are shared by both client and server, so embedding them duplicated in client and server could probably cause issues while on the fly exploding them to run.

Thanks very much for your offer, please tell me what you think about the above issues, so we could try to provide both versions of the packaged command line utility, so you can try yourself and check if the loss in speed for the single file executable is acceptable.

**Comment by rhl-** [comment]
In the last homebrew community has been reluctant to take any packages and only those that are widely used. That's why I suggested the tap.

**Comment by memsharded** [comment]
As a first step, we will release the pyinstaller (creation of the binaries from python sources) stuff asap, so anybody can easily create binaries for their platform, and package creators can also create packages from such binaries for their respective systems.

**Comment by ldionne** [comment]
Sorry for the late reply; I had my end-of-semester exams.

Actually, perhaps a good option would be to make conan available through PyPI? So basically, one could just use `pip install conan` instead of doing what the documentation says [here](http://docs.conan.io/en/latest/installation.html).

Then, it would probably be straightforward to create a Homebrew formula that uses `pip` to install conan, or even not provide a Homebrew formula at all. I'm not sure yet what's the best way to go for Python formulas on Homebrew; I know it's possible, but I think they recommend handling dependencies manually (and not relying on `pip`), which would be a pain (and I'm not sure it's worth it).

Plus, having the package available through PyPI will benefit not only OS X users, but everyone. What do you think?

**Comment by bjoernpollex** [comment]
@ldionne FWIW I like the pip approach. Homebrew would be the most convenient, but pip already goes a long way, especially when used with [pipsi](https://github.com/mitsuhiko/pipsi). I'd like to help if such an effort were to be undertaken.

**Comment by memsharded** [comment]
Thanks @ldionne for your interest, no need to apologize for late replies. Yes, I definitely think that providing a pip package is a good thing and should be easy to provide. Let's do both (releasing the creation of binaries from python and the pip package) for next release if possible. @bjoernpollex, thanks, we will probably try to address the pip package Monday or Tuesday, post here our progress. Feel free to advance things and propose, PR..., whatever contribution is valuable.

**Comment by ldionne** [comment]
@memsharded I just installed conan through pip, and it seems to work well. Do you know how can I uninstall what was installed by pyinstaller?

**Comment by memsharded** [comment]
Sure. Besides the Applications/conan folder, the only thing that the installer does is:

sudo ln -s -f /Applications/conan/conan /usr/local/bin/conan
sudo ln -s -f /Applications/conan/conan_server /usr/local/bin/conan_server

So removing Applications/conan folder and those 2 links, the system should be clean. 
User conf and cached binaries packages are stored in ~/.conan. You might want to remove it too, though not necessary.

**Comment by ldionne** [comment]
Thanks! No need to remove `~/.conan`, since this is still used by the pip installation, correct?

**Comment by memsharded** [comment]
You are welcome. Yes, it is used by any installation of conan (source, pip, binary), no need to remove it, but if you remove it, it will be regenerated by next conan command. 

I meant that typically there is no problem to remove this folder, unless you have made explicit changes to the default configuration files that live there, or you don't want to lose the local package binaries in the cache, because you have not uploaded them to a server yet.

**Comment by memsharded** [comment]
any feedback about the "pip install conan". Is it enough, or still a homebrew package should be the way to go?

**Comment by ldionne** [comment]
Installing through `pip` seems to work fine. It is sufficient for my needs, and I'd be OK with closing this issue. We can always reopen it if someone _really_ wants a Homebrew package.

**Comment by memsharded** [comment]
Great, thanks for your feedback!

**Comment by lasote** [comment]
The brew package is available since 0.8.
