### ISSUE TITLE
[question] how to find out all aliases defined for a given package?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#12001]
Hi,
is there a way to figure out what aliases are defined for a given package?
E.g. 
a.) if the given package is an alias itself, then what "real" package it points to, and to get all other aliases created on the "real" package
b.) if the given package is not an alias itself, then list of aliases created to point to this package

Is there any way to get that info?
Thanks,

**Comment by harsszegi** [comment]
Hi, any update on this? Thanks

**Comment by memsharded** [comment]
Hi @harsszegi 

There is no "inverse" model to alias, so it is very difficult to know which alias point to a given real package. Same issue as with symlinks, it is necessary to do a search in the space, but the problem with Conan is that the search space with all versions and all revisions, this might be very heavy.

To know if a package is an alias itself, a ``conan inspect`` could help.

**Comment by harsszegi** [comment]
Awesome, thanks @memsharded
