### ISSUE TITLE
[bug] Missing `pkgconfigdeps` in Conan 1.52.0

### ISSUE THREAD

**Issue by dheater** [conan-io/conan#12007]
Attempting to install `wayland/1.21.0` fails with conan version 1.52.0 (released yesterday).  It does work if I downgrade back to conan version 1.51.1.

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: gcc/11
  * Conan version: 1.52
  * Python version: 3.9.13

### Steps to reproduce (Include if Applicable)

Run `conan install wayland/1.22.0@` with conan version 1.52.0

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
# conan install wayland/1.21.0@
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: wayland/1.21.0: Cannot load recipe.
Error loading conanfile at '/root/.conan/data/wayland/1.21.0/_/_/export/conanfile.py': Unable to load conanfile in /root/.conan/data/wayland/1.21.0/_/_/export/conanfile.py
  File "/opt/python/3.9.13/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/.conan/data/wayland/1.21.0/_/_/export/conanfile.py", line 5, in <module>
    from conan.tools.gnu.pkgconfigdeps.pc_files_creator import get_pc_files_and_content
ModuleNotFoundError: No module named 'conan.tools.gnu.pkgconfigdeps.pc_files_creator'; 'conan.tools.gnu.pkgconfigdeps' is not a package
```

**Comment by memsharded** [comment]
Duplicated of https://github.com/conan-io/conan/issues/12000?

**Comment by memsharded** [comment]
(in short, a recipe bug for using private, not documented Conan imports)

**Comment by franramirez688** [comment]
Hi @dheater

You can check this issue https://github.com/conan-io/conan-center-index/issues/12722 where it's already opened the discussion. Hopefully, https://github.com/conan-io/conan-center-index/pull/12771 will fix the problem very soon.

**Comment by dheater** [comment]
Close as duplicate
