### ISSUE TITLE
[question] tools.build.build_jobs can not parse conf.tools.build:jobs

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12005]
When using Conan conf to extract `build:jobs` based on `os.cpu_count()`, Conan fails due an unexpected type, it wanted int, but received string.

This feature it's documented on Docs:

https://docs.conan.io/en/latest/reference/config_files/global_conf.html#configuration-file-template

https://docs.conan.io/en/latest/reference/conanfile/tools/build.html#conan-tools-build-build-jobs

Related to https://github.com/conan-io/conan-center-index/issues/12737

/cc @blockspacer

### Environment Details (include every applicable attribute)
  * Operating System+version: OSX
  * Compiler+version: N/A
  * Conan version: 1.52.0
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)

```python
from conan import ConanFile
from conan.tools.build import build_jobs

class FooConan(ConanFile):
    def configure(self):
        cpucount = build_jobs(self)
        self.output.info(f"**** CPUCOUNT: {type(cpucount)}")
        self.output.info(f"**** CPUCOUNT: {cpucount}")
```

    conan profile update 'conf.tools.build:jobs={{os.cpu_count()}}' default 
    conan create . foo/0.1@  -pr:b=default -pr:h=default

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
foo/0.1: Exported revision: e32b23a17d67db859472a46a6ceb3e0b
Configuration (profile_host):
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
[conf]
tools.build:jobs={{os.cpu_count()}}

Configuration (profile_build):
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
[conf]
tools.build:jobs={{os.cpu_count()}}

ERROR: Traceback (most recent call last):
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/client/conanfile/configure.py", line 27, in run_configure_method
    conanfile.configure()
  File "/Users/uilian/.conan/data/foo/0.1/_/_/export/conanfile.py", line 10, in configure
    cpucount = build_jobs(self)
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conan/tools/build/cpu.py", line 9, in build_jobs
    njobs = conanfile.conf.get("tools.build:jobs",
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/model/conf.py", line 246, in get
    raise ConanException("[conf] {name} must be a {type}-like object. "
conans.errors.ConanException: [conf] tools.build:jobs must be a int-like object. The value '{{os.cpu_count()}}' introduced is a str object
```

**Comment by memsharded** [comment]
Doesn't seem a bug, but the replacement of the template is not being done, because the profile doesn't have the ``jinja`` extension. Please rename the profile file.

**Comment by blockspacer** [comment]
> Doesn't seem a bug, but the replacement of the template is not being done, because the profile doesn't have the `jinja` extension. Please rename the profile file.

I do not understand how to enable jinja extension in profile. 
Are there any examples in docs?

**Comment by memsharded** [comment]
Hi @blockspacer 

yes, sorry I failed to properly explain. I mean the file extension. You need to opt-in using something like ``myprofile.jinja`` (this will not be necessary in 2.0, but it was necessary in 1.X to avoid breaking).

The docs are in https://docs.conan.io/en/latest/reference/profiles.html#profile-templates

**Comment by uilianries** [comment]
Now it makes sense. Also, the documentation only points `global.conf` not profile.

**Comment by blockspacer** [comment]
Thanks, ill try to use myprofile.jinja

BTW, it may be good idea to link https://docs.conan.io/en/latest/reference/profiles.html#profile-templates near info about global.conf in documentation.

**Comment by memsharded** [comment]
Good, let us know if you have any further issue when using the file extension.
We are already rewriting the docs from scratch in 2.0, it should be much clearer there (besides the extension no longer necessary)
