### ISSUE TITLE
[bug] `package_folder` is `None` if conanfile defines `layout(self)`

### ISSUE THREAD

**Issue by b1ackviking** [conan-io/conan#12010]
When I define the `layout(self)` in the conanfile.py like this:

https://github.com/b1ackviking/cpp-project-template/blob/2825b98da0d635142335b24beb4a89011d2d27a5/conanfile.py#L13-L14

And use `conan build` command to build the project, I get `TypeError` exception thrown from the `cmake.install()` calling `mkdir` with `package_folder` is `None` (see the stack trace in the attached logs).

https://github.com/b1ackviking/cpp-project-template/blob/2825b98da0d635142335b24beb4a89011d2d27a5/conanfile.py#L39-L45

https://github.com/conan-io/conan/blob/6fc624d4c1ec165618f9426172b2b0ec569b4de4/conan/tools/cmake/cmake.py#L132-L133

line 57 throws `TypeError` here:

https://github.com/conan-io/conan/blob/50daee071f84000abd2ee956140885ed8d83e849/conan/tools/files/files.py#L55-L59

because the `package_folder` is left undefined here:

https://github.com/conan-io/conan/blob/50daee071f84000abd2ee956140885ed8d83e849/conans/client/cmd/build.py#L46-L54

https://github.com/conan-io/conan/blob/6fc624d4c1ec165618f9426172b2b0ec569b4de4/conans/model/layout.py#L54-L64

### Environment Details
  * Operating System+version: Arch Linux (kernel 5.19.5)
  * Compiler+version: GCC 12, Clang 14 (not relevant)
  * Conan version: 1.52.0
  * Python version: 3.10.6

#### Broken example (defining `layout(self)`)

```bash
# note the branch that is being cloned
git clone -b layout https://github.com/b1ackviking/cpp-project-template.git
cd cpp-project-template
# you can skip the next step if you already have conan available in PATH
pipenv install --dev && pipenv shell
# note that I have GCC 12 as a default compiler in my system, your setup may be different
conan install -if build -pr:b default -pr:h default -pr:h conan/gcc-12 -c:h tools.cmake.cmaketoolchain:generator=Ninja -c:h tools.build:skip_test=True -s build_type=Debug -b missing .
conan build -if build .
```

#### Working example (without using `layout`)

```bash
# note the branch that is being cloned
git clone -b main https://github.com/b1ackviking/cpp-project-template.git
cd cpp-project-template
# you can skip the next step if you already have conan available in PATH
pipenv install --dev && pipenv shell
# note that I have GCC 12 as a default compiler in my system, your setup may be different
conan install -if build -pr:b default -pr:h default -pr:h conan/gcc-12 -c:h tools.cmake.cmaketoolchain:generator=Ninja -c:h tools.build:skip_test=True -s build_type=Debug -b missing .
conan build -bf build .
```

### Logs

```bash
(cpp-project-template) ➜  cpp-project-template git:(layout) conan install -if build -pr:b default -pr:h default -pr:h conan/gcc-12 -c:h tools.cmake.cmaketoolchain:generator=Ninja -c:h tools.build:skip_test=True -s build_type=Debug -b missing .
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:skip_test=True

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py: Installing package
Requirements
    fmt/9.1.0 from 'conancenter' - Cache
Packages
    fmt/9.1.0:0d8b943d676dc202f180a2598d04457e173d7b97 - Cache

Installing (downloading, building) binaries...
fmt/9.1.0: Already installed!
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Calling generate()
conanfile.py: Aggregating env generators
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
(cpp-project-template) ➜  cpp-project-template git:(layout) conan build -if build .Using lockfile: '/home/b1ack/projects/cpp-project-template/build/conan.lock'
Using cached profile from lockfile
conanfile.py: Calling build()
conanfile.py: CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/home/b1ack/projects/cpp-project-template/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DBUILD_TESTING="OFF" -DCMAKE_BUILD_TYPE="Debug" "/home/b1ack/projects/cpp-project-template/."
-- Using Conan toolchain: /home/b1ack/projects/cpp-project-template/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: Component target declared 'fmt::fmt'
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091


-- Build files have been written to: /home/b1ack/projects/cpp-project-template/build/Debug
conanfile.py: CMake command: cmake --build "/home/b1ack/projects/cpp-project-template/build/Debug" '--' '-j6'
[2/2] Linking CXX executable src/example
conanfile.py: ERROR: self.package_folder is None
Traceback (most recent call last):
  File "/home/b1ack/projects/cpp-project-template/conanfile.py", line 41, in build
    cmake.install()
  File "/home/b1ack/.local/share/virtualenvs/cpp-project-template-LkjBCrE5/lib/python3.10/site-packages/conan/tools/cmake/cmake.py", line 133, in install
    mkdir(self._conanfile, self._conanfile.package_folder)
  File "/home/b1ack/.local/share/virtualenvs/cpp-project-template-LkjBCrE5/lib/python3.10/site-packages/conan/tools/files/files.py", line 62, in mkdir
    if os.path.exists(path):
  File "/usr/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
(cpp-project-template) ➜  cpp-project-template git:(layout) 
```

**Comment by memsharded** [comment]
Hi @b1ackviking 

It doesn't seem a bug, but intended behavior.

The reason is: https://github.com/b1ackviking/cpp-project-template/blob/8eccefa761d2336af88c03a16ecb6b13db725ce7/conanfile.py#L36

With the new ``layout()`` feature, there is no ``package_folder`` defined inside the ``build()`` method. You need to move the ``cmake.install()`` feature to the ``package()`` method.

**Comment by b1ackviking** [comment]
Hi @memsharded 

Thanks for a quick reply!

I have just tried moving the `cmake.install()` call to the `package()` method. It works, but it does not solve my use-case anymore because I am not allowed to call `conan package` when `layout()` is present:

```bash
(cpp-project-template) ➜  cpp-project-template git:(layout) ✗ conan package -if build .
Using lockfile: '/home/b1ack/projects/cpp-project-template/build/conan.lock'
Using cached profile from lockfile
ERROR: The usage of the 'conan package' local method is disabled when using layout(). Use 'export-pkg' to test if the recipe is packaging the files correctly or use the cpp.info.local object if you are going to use this package as editable package.
```

As you can see in the conanfile at the repository, I am not building a proper conan package (using `conan create` with name/version) to make it consumable. But rather, I am using conan to drive the build process of the application at a high level. Previously (before using `layout()`), I could build the procject with `conan install <args> && conan build <args>` and have all final build artifacts copied to the `build/package` directory. This is useful both in development of an application and in CI pipelines (at work, we just point to this directory, and GitLab CI makes a zip archive from it).

The error message suggests using `conan export-pkg` or use `cpp.info.local`. I need to execute `cmake.install()` locally, I don't need to create and export the package to the cache. I thought that `if self.should_install:` in the `build()` method is the right place for that. But I am confused now. And I could not find any references for the `cpp.info.local` in docs or in the conan repository.

Also, I have just found the #10414 PR mentioning similar kind of issue. Am I understanding correctly from the comments, that conan deprecates using `package()` (and the installation step in general) locally? What is the correct way to achieve this?

**Comment by memsharded** [comment]
Hi @b1ackviking 

Yes, let me explain a little bit the rationale: the idea is that the developer flow uses the "native" tools more. That is, the devs should do ``conan install ....`` and then move directly to ``cmake ...``. With the new integrations, like the generation of CMakePresets, this should be way easier. 

For the local install case, the challenge is that the package folder was really not defined. In the past it was kind of artificially hardcoded to ``package``, but that was colliding with some users that wanted to do a system installation. So the final answer that would satisfy more users is to not be in the middle. Users that want to define a local package can do something like ``-DCMAKE_INSTALL_PREFIX=package``.

This is also the reason why the ``conan package`` and the ``should_install`` (all ``should_xxx``) have been removed in Conan 2.0, as the only value that they had was to call the ``package()`` method that contained a ``cmake.install()``, that does a ``cmake --install`` internally. Too many layers when developers or CI can just call ``cmake --install`` directly, a command that they know and control all the behavior without Conan being a limitation in the middle.

Please let me know if this makes sense. Thanks!

**Comment by b1ackviking** [comment]
Thank you for the answer @memsharded !

Knowing the reasoning behind these changes in 2.0 makes it clear to me why conan works this way. It is also a bit sad, because I almost got conan working as a build driver. But I surely understand that supporting every day changing CMake (and many other build tools) build process is a moving target. Distinguishing between the package manager responsibilities and the local development process makes perfect sense to me.

> With the new integrations, like the generation of CMakePresets, this should be way easier.

One of the reasons for using conan to build the project was to make it easier to work with. Especially for a less skilled person who is new to C++ development. Removing additional complexity is beneficial in that case. Now, as CMakePresets gets wide adoption, and CMakeToolchain generator provides a simple way to use it, I will move towards making it a default in my projects.

Thank you once again for the detailed explanation of the topic!

**Comment by memsharded** [comment]
Thanks for the feedback!

Just to be clear, the ``conan build`` command hasn't been removed in 2.0 for this reason. Actually, it is a bit more powerful, because it does a ``conan install + build()`` in one step, very convenient for developers wanting to use this behavior. So this can be still be used as a build driver. The only missing piece would be the ``package`` step, it was too artificial, but probably that is not as valuable or common as the ``conan build`` driver case.
