### ISSUE TITLE
[question] How to view profiles in 2.0

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12018]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In 1.x I am very used to `conan profile show default` to view my profile

In 2.0, the show subcommand does not offer anything  which would be able to give me the whole contents.

```sh
$ conan profile show --name default
usage: conan profile [-h] [-v [V]] [--logger] {detect,list,path,show} ...
conan profile: error: unrecognized arguments: --name default
ERROR: Exiting with code: 2
$ conan profile show -h            
usage: conan profile show [-h] [-v [V]] [--logger] [-o OPTIONS_HOST] [-o:b OPTIONS_BUILD] [-o:h OPTIONS_HOST] [-pr PROFILE_HOST] [-pr:b PROFILE_BUILD] [-pr:h PROFILE_HOST]
                          [-s SETTINGS_HOST] [-s:b SETTINGS_BUILD] [-s:h SETTINGS_HOST] [-c CONF_HOST] [-c:b CONF_BUILD] [-c:h CONF_HOST]

options:
  -h, --help            show this help message and exit
  -v [V]                Level of detail of the output. Valid options from less verbose to more verbose: 

```

**Comment by memsharded** [comment]
Hi @prince-chrismc 

The idea is that Conan 2.0 has dropped what would be pure file handling functionality, like just listing a text file, or editing a text file.
The new command does show the resulting profile, as it would be composed and evaluated (including jinja syntax) by the command line. But it can be used to show the default profile with
```
conan profile show -pr=default
```

**Comment by prince-chrismc** [comment]
How is this for a summary https://github.com/prince-chrismc/docs/commit/59442ab5558ebe7ca6d7d4013a6131e1e4c7ca23?

I'd love to open a PR (maybe move the issue) 😸 if I understand correctly!

**Comment by memsharded** [comment]
Closing this issue as responded (``conan profile show -pr=default``), but sure, feel free to open a PR to the docs if you think that clarifies. Not necessarily in the line of https://github.com/prince-chrismc/conan-docs/commit/59442ab5558ebe7ca6d7d4013a6131e1e4c7ca23, it is not necessary to compare the commands with 1.X or explain the evolution or design. Just describe the functionality in a self-contained and complete way.
