### ISSUE TITLE
[question] How to install dependency on build stage with QBS

### ISSUE THREAD

**Issue by ddkurguzikova** [conan-io/conan#12026]
I have a solution with many projects, for one of them I need to install conan package, but only if this project will be chosen to build.
I build my projects with QBS. 
I tried to use Probes.ConanfileProbe in qbs file, but it seems that conan installs the package while resolving the project. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @ddkurguzikova 

Can you please elaborate more, it is not clear what you are asking. 
It seems this is more related to qbs than to Conan, I have no idea what ``Probes.ConanfileProbe`` is, it seems something specific to your project.

**Comment by ddkurguzikova** [comment]
Hi @memsharded 
Thank you for your answer!
