### ISSUE TITLE
[bug][conan v2] Command download with package query not working

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#12029]
After trying several `conan download` commands, the package query flag does not work as expected:

```
$ conan download expat/2.2.10 -p os=Linux -r ccv2stg
ERROR: Specify a recipe revision or a wildcard. e.g: expat/2.2.10#*

$ conan download expat/2.2.10#* -p os=Linux -r ccv2stg
ERROR: 500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. [Remote: ccv2stg]

$ conan download expat/2.2.10#b9c4334d77b84fb5e9ee403d262e8072 -p os=Linux -r ccv2stg
ERROR: 500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. [Remote: ccv2stg]
```

Note `ccv2stg` remote is a repository in Artifactory with conan v2-beta2 generated packages uploaded.

Also, it will be very useful to have a way to download all pacakges, for example providing a query like `-p *`.

**Comment by czoido** [comment]
This is related to https://github.com/conan-io/conan/issues/11370
It's the same problem internally and will need to be addressed in the server, so it will take some time.
Maybe this can have a workaround using the Artifactory API for the moment...

**Comment by SSE4** [comment]
@memsharded we also need a replacement for `conan download`

**Comment by memsharded** [comment]
``conan download`` works if not using the query. The replacement would be to use exact ``package_id`` downloads, and results in the same replacement as the other issue: a query to obtain all ``package_id`` for a given revision

**Comment by memsharded** [comment]
Fixed in https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.52 Artifactory 7.52, closing this issue.

**Comment by lexknuther** [comment]
Are there any workarounds for this?  The fix for this hasn't trickled down to self-hosted Artifactory version yet.

**Comment by memsharded** [comment]
@lexknuther 

It is a bit challenging, not a simple workaround, but it would be something like this:

- Do an Artifactory api call to list all the subfolders for the desired given recipe revision
- For each one, get the index.json inside it to list the package revisions
- For every latest package revision, fetch the ``conaninfo.txt``, and compare it with your query, item by item
- Issue the specific download command for each matching one

this would be too much implementation detail for a workaround IMHO, I think it makes sense to wait until the fix lands in the self-hosted Artifactory.
