### ISSUE TITLE
Checksum verification

### ISSUE THREAD

**Issue by valeriomoroni95** [conan-io/conan#12025]
Hi everyone!

I'm working with Conan in my master dissertation in order to have an open source C++ package manager.
My use-case scenario is the following: 

1:  I locally receive pre-existing binaries to package.
2: Once packaged, I locally run this command to capture the manifests of all recipes and package binaries for the dependencies of my project: `$ conan install . --manifests`
3: I inspect the content of the _conanmanifest.txt_ and I see this:    _nameofthefile: md5 checksum_
4: I upload the package on Artifactory to verify the two MD5 checksums, the one I got in the above point 3 with the corresponding generated during the upload by Artifactory itself.

The problem is that they don't match at all.

I try to explain better what should be the pipeline to be followed in my thesis:

1. Package locally the prebuilt binaries.
2. Calculate the checksums associated with them, in this "pre-upload" phase.
3. Upload the package on Artifactory, verifying the checksums are still the same: 
    - If so, OK.
    - If not, abort the operation.
4. Once the package is uploaded and the above checks are right, download the package from Artifactory.
5. Calculate again the checksums on the downloaded package and verify if these ones are the same of those calculated in the pre-upload phase.
    - If so, OK.
    - If not, abort the operation.
    

I'm pretty new in the Conan world, is there an easiest way to succeed in doing all of these operations which I'm missing?
Thank everyone so much, in advance. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @valeriomoroni95 

> 4: I upload the package on Artifactory to verify the two MD5 checksums, the one I got in the above point 3 with the corresponding generated during the upload by Artifactory itself.

Are you talking about the ``conan_package.tgz`` checksum, for example? the uploaded artifacts are what the ``conanmanifests.txt`` says, but zipped, so it is a different thing, they will not match. You need to read the contents of the tgz files, not the file itself.

If validating the manifests again at install time, against the previous pre-upload phase, that is built-in, you can use the ``--verify`` argument.

**Comment by valeriomoroni95** [comment]
Hi @memsharded and thank you for the answer.

I'm talking about, for example, the _conanfile.py_, as you can see in the screen. 
<img width="983" alt="Schermata 2022-09-05 alle 16 24 49" src="https://user-images.githubusercontent.com/28839535/188471084-fd5c0a7c-5da0-43ff-ae28-b15c0390c903.png">

Talking about the `--verify` argument, I've used it after I've downloaded the package again from Artifactory.
Is there an easiest way to achieve checksum verification with Conan and Artifactory? Months ago I read about hooks, I don't know if, in my case, they could be useful, because I need to automate the checksum verification during upload and download phase (that's why , at the moment, I divided this task in steps, as in the previous comment).

Thank you so so much for your help!

**Comment by memsharded** [comment]
I have just checked, and that checksum matches in my case. Can you please check the ``conanmanifests.txt`` content as just downloaded from the Artifactory? Not against the file in the Conan cache.

Then, if it matches, maybe it is possible that you have already locally created a new revision or something like that? Just to make sure, try:

- Create a new ``conan new checksums/1.0 -m=cmake_lib``
- ``conan create .``
- ``conan upload checksums* -r=myrepo --all -c``

Make sure to do no more than that. Then please share what you find in your Artifactory.

**Comment by valeriomoroni95** [comment]
Yes, you're right, it matches now.

I've followed your instructions and I share with you what I got (comparing the downloaded conanmanifest.txt against what I have in Artifactory:
- MD5 checksums for _conanfile.py_ match.
- MD5 checksums for _conaninfo.txt_ match.
- export_source/CMakeLists.txt: e3ac11dff9c116c75c1dbf4661545dd5
   export_source/include/checksums.h: 0736b93171891e4463d6e11d63905a2f
   export_source/src/checksums.cpp: 133a4c7f7612856ca7cc8e11eb7ad4f6
   include/checksums.h: 0736b93171891e4463d6e11d63905a2f
   lib/libchecksums.a: 91e262e4d6a57f305cca7de4b781664a

   I can't check these ones because, on the Artifactory, only the tgz checksums are shown (for _conan_package.tgz_ and for             _conan_sources.tgz_) and, if I read the contents of these files, no checksum is provided.

 
<img width="983" alt="Schermata 2022-09-05 alle 17 37 24" src="https://user-images.githubusercontent.com/28839535/188483120-907857a0-167f-4bbe-972a-4c8929aa1f4f.png">

**Comment by memsharded** [comment]
Yes, whatever checksums you want to validate inside the .tgz, you need to download and unzip the .tgz. And this is what the client already does with ``--verify`` argument.

**Comment by valeriomoroni95** [comment]
Thank you so so much! 
So, in order to validate those checksums, which command should I run from CLI, with `--verify` argument?

**Comment by memsharded** [comment]
``conan install ... --verify`` command.

**Comment by valeriomoroni95** [comment]
Running that command I got this error: "ERROR: Manifest folder does not exist /Users/Valerio/Desktop/checksums/.conan_manifests".

I tried to run `$ conan install . --manifests`, it seems to work but the ".conan_manifests" folder still doesn't exist.

**Comment by memsharded** [comment]
Please try:

```bash
$ conan install zlib/1.2.11@ --manifests
# folder is created, ``ls -al``
# you can conan remove the cache if you want to, to force re-download
$ conan remove "*" -f
$ conan install zlib/1.2.11@ --verify
Manifests : C:\Users\memsharded\conanws\kk\.conan_manifests
Manifest for 'zlib/1.2.11': OK
Manifest for 'zlib/1.2.11:3fb49604f9c2f729b85ba3115852006824e72cab': OK
```

**Comment by valeriomoroni95** [comment]
@memsharded Brilliant!

Now it works! Thank you so much for your help, it helped me a lot 💯
