### ISSUE TITLE
[Binary Linters] Check libcxx in consumers conanfile

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1202]
Compiler and compiler version are checked by conanbuildinfo.cmake.
Using a different ``libcxx`` version will produce link errors. 

Analyze if some check or some easier way to define libcxx in your project is possible.

Read: https://github.com/memsharded/conan-protobuf/issues/7#issuecomment-293444423

**Comment by owend** [comment]
I'm a new user both of this tool and cmake, and it's not immediately obvious that there's a difference between the capabilities of conanfile.txt and conanfile.py for setting options and how exactly the settings flow from there to the cmake generator.  Perhaps an improvement to the docs?

If I do want to define libcxx=stdc++11 globally in my project (and for all dependencies built from source and linked to my project) what's the best recommended way to do that?  Thanks!

**Comment by lasote** [comment]
For global behavior (for all projects) you can change the default settings in your `conan.conf`.
For only one project I recommend you to use a conan profile:

 http://docs.conan.io/en/latest/mastering/profiles.html

The setting to adjust is `compiler.libcxx` with the value `libstdc++11`

**Comment by memsharded** [comment]
This can be addressed with:
- hooks that the binary for actual libcxx information
- the profile plugin in 2.0 that checks profile correctness
