### ISSUE TITLE
[bug] Brew shouldn't be used with sudo

### ISSUE THREAD

**Issue by agagniere** [conan-io/conan#12035]
While I seldom use brew it would seem that it refuses to install packages with super user privileges.
If that is indeed the case, then maybe the sudo setting of the package manager should be ignored when using brew.

Is there a known situation where the possibility to run brew with sudo is desired ?
What do you think about removing this ability ?

### Environment Details
  * __Operating System:__ macOS `11.6.8`
  * __Conan version:__ `1.52.0`
  * __Python version:__ CPython `3.10.6`
  * __Brew version:__ Homebrew `3.5.10`

(In fact the exact environment is the Github Action macos runner, [all details can be found here](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md))

### Steps to reproduce

Create a conanfile that installs system packages with brew, e.g.:
```python
from conan import ConanFile
from conan.tools.system.package_manager import Apt, Brew

class FooConan(ConanFile):

    def system_requirements(self):
        Apt(self).install(["help2man", "ghostscript"], update=True, check=True)
        Brew(self).install(["help2man", "ghostscript"], update=True, check=True)
```

Use a profile that enables sudo for the package manager, e.g.:
```console
$ conan profile update conf.tools.system.package_manager:mode=install default
$ conan profile update conf.tools.system.package_manager:sudo=True default
```

Then create the package:
```console
$ conan create .
```

### Logs

```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
foo/system: ERROR: while executing system_requirements(): Command 'sudo brew update' failed
ERROR: Error in system requirements
```

### Brew documentation

https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad
> Homebrew refuses to work using sudo.

### Possible workarounds
* Users conditionally enable sudo depending on the package manager expected to be used
* Conan package creators conditionally delete/modify the sudo setting depending on the package manager expected to be used

While these would work, it makes little sense to even allow brew to be run with sudo, as it seems to never make sense

### Possible patch
https://github.com/conan-io/conan/blob/develop/conan/tools/system/package_manager.py#L201
```python
class Brew(_SystemPackageManagerTool):
    tool_name = "brew"
    install_command = "{sudo}{tool} install {packages}"
    update_command = "{sudo}{tool} update"
    check_command = 'test -n "$({tool} ls --versions {package})"'
```
could be modified to :
```python
class Brew(_SystemPackageManagerTool):
    tool_name = "brew"
    install_command = "{tool} install {packages}"
    update_command = "{tool} update"
    check_command = 'test -n "$({tool} ls --versions {package})"'
```

Thank you for your time.

**Comment by memsharded** [comment]
Thanks for the detailed feedback.

It would seem that it makes sense to have brew ignore ``conf.tools.system.package_manager:sudo``, if by default brew will error, and if for some exceptional case, it would be necessary, to re-enable it with ``conf.tools.system.package_manager:sudo_break`` or something the like.

Brew/OSX users, please feedback.

**Comment by czoido** [comment]
Hi @agagniere ,
Thanks a lot for the detailed explanations. I guess that it would make sense to just not activate sudo for MacOS as the default `conf.tools.system.package_manager:sudo` mode is `False`. If this is not blocking for you I think it would be better to leave it as it is now to be coherent with the rest of package managers and just using a profile that does not enable the sudo conf. WDYT?

**Comment by agagniere** [comment]
Well technically that would work, which is why I listed it in the possible workarounds.

But that would essentially be putting the responsibility to know the package managers specifics on the end user, which defeats the purpose of Conan and its `tools.system.package_manager`, doen't it ?

Also do you want your tool to have an option, that, when turned on and used, guarantees a failure 100% of the time to OSX users ?

### Going back to technicalities,
I could indeed write in my CI/CD script:
```bash
conan profile update conf.tools.system.package_manager:sudo=$( test $(uname -s) = "Darwin" && echo False || echo True) default
```
and ask my (imaginary) users to not set the `sudo` option when depending from my package if their system uses Homebrew for package management.

But why am I even using Conan for that ? I could directly write in my CI/CD scipts:
```bash
$( [ $(uname -s) = "Darwin" ] && echo brew || echo sudo apt-get -yq ) install ghostscript
```
and ask my (still imaginary) users to make sure the `ghostscipt` package is installed on their system before depending on my package.

In both cases, it puts a burden on the end-user, that needs to know how to use their package manager.

### About Conan code

Why would we want the Brew-specific code ([conan/tools/system/package_manager.py#L201](https://github.com/conan-io/conan/blob/develop/conan/tools/system/package_manager.py#L201)) to have `{sudo}` ?
```python
class Brew(_SystemPackageManagerTool):
    tool_name = "brew"
    install_command = "{sudo}{tool} install {packages}"
    update_command = "{sudo}{tool} update"
    check_command = 'test -n "$({tool} ls --versions {package})"'
```
If `{sudo}` is not empty, then the update and install commands will fail, no matter what.
We know that for sure from official brew documentation.

Then why even include this `{sudo}` ?
What cost is there to not include it ?

## Conclusion

I understand that your tool works fine as it is today and that there is no incentive to change it.

On my side I am only experimenting with Conan and my packages have no users, so there are no consequences either way.

I have no strong opinion about what should be done here, I tried to make the case that it would be more conceptually satisfying for Conan to handle those specificities for us, but realize it is subjective.

Thank you for your time

**Comment by czoido** [comment]
Hi @agagniere,
Thanks for your response.
The main motivation is that, if tomorrow, for whatever reason a new brew version accepts using sudo again (even if that's unlikely) then all the Conan versions that removed the sudo would not be able to use that argument. I'm not completely against ignoring sudo with brew but thats the point that makes me doubt a bit.

**Comment by memsharded** [comment]
Hi @agagniere 

I would like to highlight that the recommended way to use configuration in production is not using command line, or auto detected profile, but using actual profile files distributed with ``conan config install``. 

A few notes:
- Conan 2.0 has dropped the auto-detection of profile. It will keep a ``conan profile detect`` explicit command to create a new one, but all commands will fail if a previous profile doesn't exist, instead of creating it on the fly.
- The output of ``conan profile detect`` is declared unstable in 2.0. It will be able to change in new releases. 
- The ``conan profile update`` command disappears in 2.0, it is not possible to edit profiles that way, but all commands that their exclusive functionality is editing a text file have been removed in 2.0.

So then, it is not a task of the CI to figure out the ``conf`` value. But the ``myosx`` profile will simply not put that conf at all, while your linux profiles will probably add that ``sudo`` ``conf``.

It is not

> and ask my (imaginary) users to not set the sudo option when depending from my package if their system uses Homebrew for package management.

You don't have to ask them, those users will not have that ``conf`` enabled in OSX either, and their brew will not use sudo, why would they add such an opt-in?

**Comment by agagniere** [comment]
Hi @czoido,
I understand your point now, that despite the likelihood of Brew allowing and then enforcing sudo being infinitesimally low, it is still a possibility, and your top priority is retro-compatibility.

I'm guessing that for now I will put the logic of deleting the sudo setting if needed in the conanfile that calls brew.


Hi @memsharded,
Thank you for the heads up.
Indeed, I will have to rethink how I handle configuration with those new constraints.


Thank you both
