### ISSUE TITLE
[bug] MAP_IMPORTED_CONFIG_* does not work in CMakeDeps

### ISSUE THREAD

**Issue by alex-700** [conan-io/conan#12041]
Hello, sorry for unformatted issue!

In #11788 @lasote changed the way how dependencies handled by introducing new targets ([here](https://github.com/conan-io/conan/blame/develop/conan/tools/cmake/cmakedeps/templates/target_configuration.py#L70) and [here](https://github.com/conan-io/conan/blame/develop/conan/tools/cmake/cmakedeps/templates/target_configuration.py#L150)). It seems that these targets were forgotten to mark `IMPORTED`.

The specific problem: this change breaks our build, where we are using dependencies with `build_type=Release`, while building consumer with any other `build_type` (e.g. `RelWithDebInfo`). We are doing this by carefully maintain the `CMAKE_MAP_IMPORTED_CONFIG_*` in consumer.

**Comment by lasote** [comment]
Hi, can you please confirm the Conan version you are using? I made a test and it is apparently working ok.

**Comment by alex-700** [comment]
Currently, I checked on the latest version (1.52.0).

I'm pretty sure, that this behavior was introduced in #11788. Some time ago I checked on other versions: on 1.51.x it is failed, on 1.50.x it is working as expected.

The test should be something like `A -> B -> C` (A is not depends on C directly), `B` and `C` compiled with build_type=Release, `A` is consumer (specify `CMAKE_MAP_IMPORTED_CONFIG` and build in Debug). Actual behavior, that A is not linked with target C::C (e.g headers of C, included in B can not be found during A compilation).

**Comment by lasote** [comment]
Thanks, I've been able to reproduce the issue. I will come back with a fix.

**Comment by lasote** [comment]
Have you tried to mark as `IMPORTED` the mentioned targets? Does it work for you? My test is still failing.

**Comment by alex-700** [comment]
Yes, I patched conan==1.52.0 locally by adding `IMPORTED` in these two places. And it worked in my case.

**Comment by lasote** [comment]
Still not able to make the test pass. 
My test is [here](https://github.com/conan-io/conan/compare/develop...lasote:feature/test_cmakedeps_config_mapping?expand=1). It is testing: app -> talk -> hello
I'm creating hello and talk for Release and building the app for Debug.
Would you mind taking a look in case you see that I'm doing something wrong (for example in the cmake mapping).
Thanks.

**Comment by lasote** [comment]
Ok, I got something working doing `set(CMAKE_MAP_IMPORTED_CONFIG_DEBUG Release)` and adjusting the `IMPORTED_LOCATION` to `IMPORTED_LOCATION_XXX` (in the `macros.py` of the CMakeDeps). I'm seeing if I broke any other tests and will discuss this with the team.
