### ISSUE TITLE
[question] How can I activate PATH in CMakeToolchain and CMakeDeps

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#12047]
- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

the situation like this:
I have a package(cuda), set compiler's path(nvcc) by self.env_info.PATH.append(os.path.join(self.package_folder, "bin"));
and the second package(libtorch), need this compiler, and I use conan-cmake (generators is cmake), it can perfectly detect this compiler's location, but when I use CMakeToolchain and CMakeDeps, it can't.

**Comment by memsharded** [comment]
The new integrations like CMakeToolchain and CMakeDeps are designed to work with the new environment:

- Define ``self.buildenv_info.append_path(...)`` to define it
- Use ``VirtualBuildEnv`` generator in your consumer recipe

Check: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html
