### ISSUE TITLE
[bug] Conan reports "Error copying sources to build folder" even though all files were succesfully copied!

### ISSUE THREAD

**Issue by luistorrescisneros** [conan-io/conan#12042]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 2022
  * Compiler+version: MSBuild for .NET 17.3.0.37102
  * Conan version: 1.52.0
  * Python version: 3.10.6

### Steps to reproduce (Include if Applicable)
1. Create conan recipe with export_sources, build, and package methods
2. Run conan create . --profile conanprofile (see profile below) 

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Logs (Executed commands with output) (Include/Attach if Applicable)

ERROR: [('C:\\Users\\ContainerAdministrator\\.conan\\data\\datadictionary\\0.0.0.0\\klondike-b-datadictionary\\test\\source\\ThirdParty\\DocbookTools\\docbook-xsl-1.78.1\\webhelp\\docs\\common\\jquery\\theme-red
mond\\images\\ui-bg_flat_0_aaaaaa_40x100.png'), "[Errno 2] No such file or directory: 'C:\\\\Users\\\\ContainerAdministrator\\\\.con
an\\\\data\\\\datadictionary\\\\0.0.0.0\\\\klondike-b-datadictionary\\\\test\\\\build\\\\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b\\\\ThirdParty\\\\DocbookTools\\\\docbook-xsl-1.78.1\\\\webhelp\\\\template\\\\com
mon\\\\jquery\\\\theme-redmond\\\\images\\\\ui-icons_d8e7f3_256x240.png'")]
Error copying sources to build folder

**Comment by czoido** [comment]
Hi @luistorrescisneros,
Maybe this could be related to the path of the files exceeding the path size limitation in Windows? You can check the section in the Conan docs about this topic: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#short-paths maybe that gives you some hints.
Hope this helps.

**Comment by luistorrescisneros** [comment]
Hi @czoido ,

yup you are right. A couple of minutes ago I set 

`
conan config set general.use_always_short_paths=1
`

and it worked.

Thanks for your input

Luis

**Comment by czoido** [comment]
I'm glad it helped @luistorrescisneros,
Besides setting the short_paths to 1 in Conan you could also try to enable the long paths at system level: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later
I'm closing this as it seems solved but please feel free to reopen or open more issues if you have more questions. Thanks!

**Comment by luistorrescisneros** [comment]
That sounds great! I will try it also. 👍

Thanks for your time
