### ISSUE TITLE
[feature] self.cpp_info.exes

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#12048]
If a package is packaging executables (a `tool_require`or even python entry points as proposed [here](https://github.com/conan-io/conan/pull/11601/files)) would be nice to model it in the `cpp_info` so the generators can use that information to do something, for example, `CMakeDeps` could create targets for calling the executables but there might be more use cases.

**Comment by memsharded** [comment]
We had issue https://github.com/conan-io/conan/issues/7240, seems duplicated?
