### ISSUE TITLE
conan_imports_manifest.txt is written to installation prefix

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#1204]
Could you change `conan imports` behavior so that conan_imports_manifest.txt is written to the working directory of conan process instead of path specified in `-d` argument? I use it as a part of `make install` procedure and it pollutes installation prefix with implementation detail of installation process.

Compare with cmake's `install_manifest.txt` which is generated in build direcotry, not installation prefix.

https://cmake.org/Wiki/RecipeAddUninstallTarget

I've tried naive approach but it didn't work

```diff
diff --git a/conans/client/importer.py b/conans/client/importer.py
index c979d25..1e5861b 100644
--- a/conans/client/importer.py
+++ b/conans/client/importer.py
@@ -63,7 +63,7 @@ def run_imports(conanfile, dest_folder, output):
             abs_path = os.path.join(dest_folder, f)
             file_dict[f] = md5sum(abs_path)
         manifest = FileTreeManifest(date, file_dict)
-        save(os.path.join(dest_folder, IMPORTS_MANIFESTS), str(manifest))
+        save(IMPORTS_MANIFESTS, str(manifest))
     return copied_files
```

**Comment by lasote** [comment]
I don't reach to understand the prefix pollution, a naive question: `-d $(pwd)` or `-d ./` or something like that produces the same problem?

**Comment by annulen** [comment]
I cannot use `-d .` because I need to install into specified prefix

**Comment by memsharded** [comment]
I am not sure about this request. The current implementation will import the files and generate the manifest in the same directory. Such directory can be the current one, if nothing is specified, or the "--dest" destination one, if specified. 

The rationale for this is that it makes sense to keep the manifest together with the artifacts that have been imported. If two different imports (for two different settings, like architectures, or build_type) are consecutively done with different ``--dest`` arg, like ``-d debug`` ``-d release``, the manifest dumped to the current working directory will be overwritten and the former lost. The command is an "imports", designed to bring artifacts from the local conan cache to user space, not to install system wide. So the concept of a system clean install is not clear.

A new argument like ``--manifest-dest`` could be added, but IMHO it seems overkill UI for something that can be done with just a ``mv`` command. Maybe I am missing something, could you please explain?

**Comment by annulen** [comment]
>The command is an "imports", designed to bring artifacts from the local conan cache to user space, not to install system wide

My initial request about imports command was about getting a helper to avoid writing install (or packaging, which is really the same thing) code for each imported library.

**Comment by memsharded** [comment]
Sure, the utility of ``imports`` is that you can say: "I want to retrieve all DLLs of all my dependencies, and put them in my folder my_dlls", without having to worry that each package recipe has to define some install or deploy mechanism. 

However, still not sure about your request regarding the ``conan_imports_manifest.txt`` file. In the previous example, the logical thing is that the manifest is stored inside "my_dlls" together with the imported dlls, that way it will allow for a clean imports, undo-imports for multiple configurations (e.g. my_32bits_dlls, and my_64bits_dlls folders)

**Comment by macdew** [comment]
I appreciate that this item is marked as inactive/obsolete, but having a flag to control this file creation would help me as well. I use conan imports as part of a cmake / cpack sequence and as a result, the file conan_imports_manifest.txt always appears inside my installer/distribution.  I have to delete it manually every time, but now I'm trying to automate my release process further and I just don't know how to block this file from appearing in cpack...

**Comment by Kaylx** [comment]
I too suffer from `conan_imports_manifest.txt` appearing in my CMake/CPack generated package file.
I've tried removing the file using a [CPACK_PRE_BUILD_SCRIPTS](https://cmake.org/cmake/help/latest/module/CPack.html?#variable:CPACK_PRE_BUILD_SCRIPTS) but had no luck.
If anyone has solved this problem. Please let me know.

**Comment by memsharded** [comment]
imports have been removed in 2.0, closing this issue as outdated
