### ISSUE TITLE
[bug] scm field replacement indentation mismatch

### ISSUE THREAD

**Issue by AshleighAdams** [conan-io/conan#12045]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: N/A
  * Conan version: 1.48.1
  * Python version: (inbuilt)

### Steps to reproduce (Include if Applicable)

Create a super conanfile froma python requires:

```py
from conans import ConanFile

class BaseConanFile(object):
	url = "auto"
	scm = {
		"type": "git",
		"url": "auto",
		"revision": "auto",
		"submodule": "recursive",
	}

class Package(ConanFile):
	name = "base-conanfile"
	version = "0.1.0"
```

Use that python requires from a separate repo/conanfile:

```py
from conans import ConanFile

required_conan_version = ">=1.42.0"

class Package(ConanFile):
	name = "snip-pkg"
	python_requires = "base-conanfile/0.1.0"
	python_requires_extend = "base-conanfile.BaseConanFile"
```

Derive from that base conanfile, have the python file use tab indentation instead of spaces, then `conan create` it, an error will be output.

### Logs

```
...snip...
ERROR: snip-pkg/1.1.1-alpha.3+git.f6f8a82@local/test: Cannot load recipe.
Error loading conanfile at 'D:\.conan\.conan\data\snip-pkg\1.1.1-alpha.3+git.f6f8a82\local\test\export\conanfile
.py': Unable to load conanfile in D:\.conan\.conan\data\snip-pkg\1.1.1-alpha.3+git.f6f8a82\local\test\export\con
anfile.py
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\.conan\.conan\data\snip-pkg\1.1.1-alpha.3+git.f6f8a82\local\test\export\conanfile.py", line 10
    name = "snip-pkg"
                    ^
TabError: inconsistent use of tabs and spaces in indentation
```

Resulting recipe with mismatched indentation:

```py
from conans import ConanFile

required_conan_version = ">=1.42.0"

class Package(ConanFile):
 scm = {"revision": "f6f8a8266fc28195ac06b83ae5caa47c2b11b635",
           "submodule": "recursive",
           "type": "git",
           "url": "ssh://git@snipsnip.git"}
	name = "snip-pkg"
	python_requires = "base-conanfile/0.1.0"
	python_requires_extend = "base-conanfile.BaseConanFile"
```

**Comment by memsharded** [comment]
Hi @AshleighAdams 

It seems you are using a deprecated legacy feature. 
The first inmediate/easy workaround is to define: ``conan config set general.scm_to_conandata=1`` (better, put it into your conan.conf). That makes Conan to put the scm information in conandata.yml instead of modifying the source code of conanfile.py on the fly. This has been the recommended approach for a long time.

But if you really want to modernize your recipe and be Conan 2.0 ready, you need to drop the ``scm`` attribute, and use this approach instead: https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature

**Comment by AshleighAdams** [comment]
@memsharded Ah I see, thanks for the heads up! Would you recommend we change that definition across our team? We have a large history of recipes, so if this will play nice with those we'll do that for a short term fix, and lookat modernizing further down the line.

**Comment by memsharded** [comment]
> @memsharded Ah I see, thanks for the heads up! Would you recommend we change that definition across our team? We have a large history of recipes, so if this will play nice with those we'll do that for a short term fix, and lookat modernizing further down the line.

This should be contained in the recipes, so in theory it shouldn't break to enable that configuration and let future builds to take it into account. But it is also true if you can workaround the bug, by fixing the spaces/tabs thing, then maybe that would be even easier, and wait until the new ``tools.scm import Git`` solution

**Comment by AshleighAdams** [comment]
@memsharded I think in that case we'd be happy to switch to using `scm_to_conandata`, I'll leave this bug open in case you wish to address/track the mismatch issue, otherwise feel free to close it!

**Comment by memsharded** [comment]
Yes, at this stage, with alternative better solutions, this will not be fixed, and fortunately and as recommended in the docs, it seems that most users have started to use the ``scm_to_conandata``. Closing it, thanks for the feedback!
