### ISSUE TITLE
[feature] select latest recipe revision matching client version

### ISSUE THREAD

**Issue by codetent** [conan-io/conan#12043]
If currently a recipe is updated on the remote index, the new revision will be automatically selected independent of the conan client version.
This is especially a problem if the newer recipe is no longer compatible with an older conan client.
In this case, it is displayed that the recipe requires a newer client version or in the worst case that some imports cannot be found (because the min. conan version is usually after the imports in the recipe).

Wouldn't it be better to not select always the latest but the latest compatible recipe revision?

This would probably require that instead of `_resolve_latest_ref` either all are resolved (probably inefficient because the recipes must all be fetched?) or conan starts from the latest one and continues with older ones if the checked one is incompatible:
https://github.com/conan-io/conan/blob/develop/conans/client/remote_manager.py#L105

Is there currently another alternative than updating conan or locking the recipe revisions?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @codetent 

> Wouldn't it be better to not select always the latest but the latest compatible recipe revision?

Sorry, but this is not possible. The complexity that something like this implies is just huge, it cannot be done.

There are other different ways to approach this (by the way, this is not a problem unique to Conan, but also happens to other package managers):
- Use your own server in production where you store a copy of the  packages you use. For Conan you can use the ArtifactoryCE for free
- Pin exact recipe revisions in your recipe ``requires``. Probably a bit verbose and not very practical, but is doable.
- Use lockfiles to pin exact revisions. Lockfiles in 1.X can be a bit challenging, they are much improved and simplified in 2.0.

The first approach is recommended in any case, for any other technology (npm, pip, docker, maven, etc, etc), do not depend on central public repositories in production, and it is recommended despite a lockfile based solution is also used.

**Comment by codetent** [comment]
Hi @memsharded

Thanks for your fast answer! 😃

- Currently, I'm already having an artifactory instance from which the packages are pulled but it acts just as a mirror for the conan index. Never thought of that but it could work that you have an isolated registry where you pull in the changes manually from the conan index. Unfortunately this also requires some manual management and could be risky if you update a recipe and developers are still using older client versions.
- `requires`: That's what we are currently doing but I think this only works for the direct dependencies. I guess in this case dependencies of dependencies are not pinned. A workaround would be to flatten the dependency graph and specify everything in the requires but this would make the recipe probably harder to maintain
- I think using a base lockfile and deriving one for each configuration from it would definitely be an option. Unfortunately the base  is not only pinning the version of the dependencies but also of the main node including the current version. This would mean that you cannot directly version control the base lockfile if the version is computed dynamically. Is the behavior different in conan 2.x or am I just using lockfiles wrongly?

**Comment by memsharded** [comment]
> Currently, I'm already having an artifactory instance from which the packages are pulled but it acts just as a mirror for the conan index. Never thought of that but it could work that you have an isolated registry where you pull in the changes manually from the conan index. Unfortunately this also requires some manual management and could be risky if you update a recipe and developers are still using older client versions.

yes, there is always a tradeoff between effort, speed, and risk of breaking.
If this is to be done without risk of breaking it is done in 2 steps:
- First pull the latest packages to another, testing Artifactory repo.
- Test your code works against that repo. If something is broken, either reject the upgrade or work to update the code that uses the new updated dependencies, or just update the Conan client if that fixes it.
- When ready, copy the packages of that other repo to the main "development" repo.

This way, all the other developers can keep working against stable dependencies, until everyone updates to the necessary Conan version, and move forward without breaking. But yes, this needs some effort and automation


> requires: That's what we are currently doing but I think this only works for the direct dependencies. I guess in this case dependencies of dependencies are not pinned. A workaround would be to flatten the dependency graph and specify everything in the requires but this would make the recipe probably harder to maintain

yes, exactly this requires to declare transitive depndencies, but not necessarily flatten, as overrides (``override=True`` in requires), can force the upstream dependency without flattenning. But yes, this is the reason I commented this won't be the most practical approach.

> I think using a base lockfile and deriving one for each configuration from it would definitely be an option. Unfortunately the base is not only pinning the version of the dependencies but also of the main node including the current version. This would mean that you cannot directly version control the base lockfile if the version is computed dynamically. Is the behavior different in conan 2.x or am I just using lockfiles wrongly?

yes, conan 2.0 lockfiles are much different. Lockfiles are by default "base", and they can be used directly, without deriving per-configuration lockfiles. It also doesn't matter what is the main node, and partial lockfiles can be also applied.

**Comment by codetent** [comment]
Ok thank you for your suggestions!
I guess for now I'm probably going with the second approach as it is for now the simplest approach
... and I'm looking forward to see the first stable release of conan 2.0 with all the changes :-)

**Comment by codetent** [comment]
Just a follow up question for specifying the recipe revision in the recipe: does this also work for build requirements (with `override`)?

**Comment by memsharded** [comment]
> Just a follow up question for specifying the recipe revision in the recipe: does this also work for build requirements (with override)?

build-requires are totally private in 1.X, so they cannot be overriden by other recipes, but they can be overriden by the profile ``[tool_requires]`` section

In Conan 2.0, ``tool_requires`` are still private by default, but they can be made visible with the ``visible=True`` trait, and that will allow to override them from downstream (and also to conflict if they try to provide different versions).


The original feature request is not implementable, impossible because it means to solve a NP-hard problem, which is intractable in practice. So I guess we can close this ticket?

**Comment by codetent** [comment]
Yes I guess I have to wait until Conan 2.0 for solving the issue cleanly... Until then having an isolated artifactory instance helps a bit to reduce such issues.
Thanks @memsharded
