### ISSUE TITLE
[question] conan config install throws an error : ERROR: Failed conan config install: remotes.json install is not supported yet. Use 'remotes.txt'

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#12051]
Dear Conan Folks,
I am using conan 1.51.1. 
My use-case is:
- I am setting CONAN_USER_HOME in  pipeline.
- Using conan config install I am specifying a git repository which contains profiles and settings.yml 
 Strangely it throws an error:
- ERROR: Failed conan config install: remotes.json install is not supported yet. Use 'remotes.txt'
I donot have remotes.json and remotes.txt. I have only remotes.json.
What is the reason for this error?
- [ X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @maitrey,

Thanks for your question. `remotes.json` should work [since Conan 1.52](https://docs.conan.io/en/latest/changelog.html#aug-2022). 
Could you try to update and see if that works?

**Comment by maitrey** [comment]
Hi @czoido , 
The remotes.json was always used atleast since June this year for me. What was changed in between I was wondering.
I read the changelog of 1.52 and it says to support remotes.json in 1.x:
https://github.com/conan-io/conan/pull/11936/files/77f4615c27ef872c6a9f2acba0db2ce500584ed9#diff-ec0b7bc999395ce1a47093a8f5f143e0e3dfe54fe984b9f49c2ead6dcceb3ebeL113  
Could you please explain as I am not able to understand fully ? 
After upgrading to 1.52, it obiviously works, Thanks!

**Comment by czoido** [comment]
Hi @maitrey,
But did you always have just the `remotes.json` file in your git repository or you have recently added it there? The `remotes.json` was supported internally in Conan but the installation via `conan config install` was not supported until 1.52 and if should have failed. So you could manually copy it and use it but the `conan config install` failed with that file. Does it make sense?

**Comment by maitrey** [comment]
As far as I remember , I used conan config install for the initial set up in our CI test nodes. I hope I remember right. Anyhow, it works for me now.

**Comment by czoido** [comment]
Ok, I'm glad it works now. 
I'll close this as it seems solved. Thanks a lot!
