### ISSUE TITLE
[question] Can conan package be used for deployment (time) of 'conaned' components?

### ISSUE THREAD

**Issue by whitefluffypenguin** [conan-io/conan#12059]
Hi there,
We have different runtime components (with version) packed in isolated conan packages. Is it possible to use conan of conans package to aggregate certain versions of these components together in conan of component conans (for example: stating in conan file runtime dependent conans, i.e. what version of component conan to package and where to take it from) to deploy it later in deployment time?

**Comment by memsharded** [comment]
Hi @whitefluffypenguin 

It seems you might be interested in ``imports`` and ``deploy`` feature in 1.X. With them you can:
- Write a recipe with ``imports()`` or ``deploy()`` methods, with ``requires`` to the deps you want
- Code the ``imports`` or ``deploy()`` method to ``copy()`` the files, e.g. *.dll that you want

Under Conan 2.0, this would be instead (both methods above removed):
- Use ``--deploy`` deployers to run a python script that collects what you want.
- Use ``generate()`` method of a recipe to collect what you want from dependencies, and re-package them. Use requirement traits to be able to use the binary of the package that "re-packaged" the thing, without needing to retrieve all the binaries of the dependencies.

**Comment by whitefluffypenguin** [comment]
Hi Memsharded,
Thanks for answering so promptly!
Small clarification - with both versions the recipe file of conan of conans is able to include the list of dependent packages, their versions and directives where to get them from?

**Comment by memsharded** [comment]
Yes, in both cases, one single ``conanfile.py`` with some declared ``requires`` will fetch, download and unzip them in the Conan cache for a ``conan install`` operation, including their transitive dependencies. 

All the deployment operations in both versions start after that, once the full dependencies have been downloaded to the Conan cache. The deployment/import operations are copies from Conan cache to user space folders in both 1.X and 2.0 versions. (The opposite flow is called ``export``, when something is copied from user space to the Conan cache, and this happens at package creation time (``conan create`` or ``conan export-pkg`` or ``conan export``), when user recipes are copied to the cache to be reusable from others)

**Comment by whitefluffypenguin** [comment]
Great answer. Thanks for supporting!

**Comment by whitefluffypenguin** [comment]
If someone has additional deployment properties to set (like various versions or strings) - is it possible to use recipe file syntax for setting and parser for reading them?

**Comment by memsharded** [comment]
> If someone has additional deployment properties to set (like various versions or strings) - is it possible to use recipe file syntax for setting and parser for reading them?

I guess you can put them in ``conandata.yml``, and then deployers can access it via ``self.dependencies["mydep"].conan_data``

**Comment by whitefluffypenguin** [comment]
Got it - thank you!

**Comment by whitefluffypenguin** [comment]
Hi Memsharded,

I am trying to implement the proposed solution. 
I have pre-created 'first' and 'second' component packages,
And I have created the deployment 'ConanOfConans' package like this:

from conans import ConanFile

class ConanOfConans(ConanFile):
    name = "conan_of_conans"
    version = "1.0.0-1"
    user = "test"
    channel = "channel"

    def requirements(self):
        self.requires("first/1.0.0-1@test/channel")
        self.requires("second/1.0.0-2@test/channel")

    def deploy(self):
        self.copy_deps("*.txt", dst="w:/temp/20221024/first_folder", root_package="first")
        self.copy_deps("*.txt", dst="w:/temp/20221024/second_folder", root_package="second")

I was able to deploy into user folders running "conan install conan_of_conans/1.0.0-1@test/channel" command.
Is this the method you recommended or you meant to something else?
Is 'conan install' the only command that runs 'deploy' stage at the end?

**Comment by memsharded** [comment]
> Is this the method you recommended or you meant to something else?

Yes, this is good for conan 1.X. In Conan 2.0 we created some new explicit ``--deploy=mydeployer`` feature that allows to define your own deployers which is more extensible. In Conan 2.0 it is also possible to move the functionality to the ``generate()`` method with ``copy()`` util instead, because the ``deploy()`` method will be dropped. But as the consumer recipe is pretty simple is not a big deal

> Is 'conan install' the only command that runs 'deploy' stage at the end?

Yes, the ``deploy()`` method only runs if you apply a ``conan install`` over that exact recipe directly. For transitive dependencies, even if they have a ``deploy()`` method, it will not be executed.

**Comment by whitefluffypenguin** [comment]
Thanks! Will try Conan 2.0 as well. How soon will conan 1.X (with deploy() method) be dropped? The ability to deploy the transitive dependencies is important to us.

**Comment by memsharded** [comment]
Conan 1.X will still be maintained and supported for a while after 2.0 final release, to keep helping in the transition 1.X->2.0. I'd expect at least around 6 months of them co-existing.

But writing a ``deployer`` should be a relatively easy task, and you can already start trying it in the beta.

**Comment by AbrilRBS** [comment]
Closing as solved with the v2 release, let us know if you faced any issues with the transition and writing your desired deployers, thanks!
