### ISSUE TITLE
[bug] 2.X Dnf Package Manager Noarch

### ISSUE THREAD

**Issue by beenjohn** [conan-io/conan#12056]
The Dnf/Yum package manager fails to install .noarch packages due to forced insertion of the architecture. It's possible to work around this by providing an arch_types map of {"...": "noarch"}, but this is cumbersome when installing multiple packages of noarch/arch-specific.

It would be nice to have a noarch flag of some sort to override the default behavior.

**Comment by memsharded** [comment]
You mean ``Yum(arch_names={your own dict})`` argument in the constructor, don't you?

Can you clarify, you want the ``noarch`` packages even if the ones for the current architecture exist? Also assuming the current architecture is defined.

Can you also elaborate a bit more about `` but this is cumbersome when installing multiple packages of noarch/arch-specific.``? Will be there a mix of packages? Depends on what, only the recipe knows?

**Comment by beenjohn** [comment]
Yes that's correct for the override. The issue I'm facing is with the help2man package that doesn't have an architecture specific version.

Cumbersome is an exaggeration on my part, but basically it requires:
`noarch_arches = {'arch1': 'noarch', 'arch2': 'noarch'}`
`Yum(self, arch_names=noarch_arches).install(noarch_package_list)`
`Yum(self).install(arch_package_list)`

vs something like:
`yum=Yum(self)`
`yum.install(noarch_package_list, noarch=True)`
`yum.install(arch_package_list)`

From looking at the source of package_manager it doesn't seem that either approach really saves resources, so maybe this isn't really a big issue after all. The only (miniscule) inconvenience is when 'arch3' becomes relevant we'd have to update the noarch_arches dict for each recipe. Not a big deal IMO.

I mainly posted because I saw a 'To Do' comment in the code (conan.tools.system.package_manger) referencing arch_type specification.

**Comment by beenjohn** [comment]
Alternatively in the recipe:
`from collections import defaultdict`
`Yum(self, arch_names=defaultdict(lambda: "noarch", {})).install(...)`

I'm ok with whatever you all feel is the right path for conan. Feel free to close as desired.
