### ISSUE TITLE
[question] Migrating msvc/ninja profile PATH environment configuration to CMakeToolchain 

### ISSUE THREAD

**Issue by ineb** [conan-io/conan#12052]
Hello,
i am trying to compile ``zlib/1.2.12`` under Windows which is my first package that uses the new CMakeToolchain mechanism.
My current profile looks like
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.version=15
[env]
VisualStudioVersion=15
CONAN_CMAKE_GENERATOR=Ninja
PATH = [{{ os.getenv("MSVC1416_CL_PATH") }}]
INCLUDE = [{{ os.getenv("MSVC1416_INCLUDE_PATH") }}]
LIB = [{{ os.getenv("MSVC1416_LIB_PATH") }}]
```
I use environment variables to configure the Generator via ``CONAN_CMAKE_GENERATOR`` and imbue PATH, INCLUDE and LIB so my compiler can be discovered. My profiles is a ``.jinja`` template, therefore ``{{ os.getenv("MSVC1416_CL_PATH") }}`` is being resolved to a full path where my compiler is located.

My question is how can i migrate my profile to work with the CMakeToolchain mechanism?

The first problem i got was
```
CMake Error at CMakeLists.txt:4 (project):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.
```

and i fixed it by specifying the generator via:
```
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

But now i am looking at:
```

zlib/1.2.12@just/testing: Calling generate()
ERROR: zlib/1.2.12@just/testing: Error in generate() method, line 67
	tc.generate()
	ConanException: VS non-existing installation: Visual Studio 15
```

which makes sense i guess, since my compiler can not be discovered if anything in ``[env]`` is ignored. How can i tell the toolchain where my msvc compiler is located?

Thanks for any hints!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @ineb 

So sorry for the delay in replying to your issue. Did you get the way to make it run?

Anyway, let me explain something about the new generators. `Visual Studio` compiler is deprecated so you should use `msvc` instead (more information [here](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html#msvc)).

One likely profile could be something like this:

```
        [settings]
        os=Windows
        compiler=msvc
        compiler.version=190
        compiler.runtime=dynamic
        compiler.runtime_type=Release
        compiler.cppstd=14
        build_type=Release
        arch=x86_64
        [conf]
        tools.cmake.cmaketoolchain:generator=Ninja
        tools.microsoft.msbuild:vs_version = 15
```
Let me know your current status so I'll try to help you with anything.
I also recommend you read the [Conan migration guide to 2.0](https://docs.conan.io/en/latest/conan_v2.html) that could help you with any other related issues.

**Comment by ineb** [comment]
For now i keep using an older version of zlib/1.2.12 without the new CMakeToolchain mechanism
