### ISSUE TITLE
 [feature] Support for Xcode 14.0 (currently RC)

### ISSUE THREAD

**Issue by janosvitok** [conan-io/conan#12063]
It's that time of year again... Xcode 14 is approaching (currently RC)

Related PRs:
https://github.com/conan-io/conan/pull/10797
https://github.com/conan-io/conan/pull/9642

Related issues:
https://github.com/conan-io/conan/issues/10509
https://github.com/conan-io/conan/issues/9641

XCode 14.0 RC reports compiler version as "14.0".

I'll create a PR in a few minutes.

In conan 1.47 the condition was lifted that only major number must match; now the major one has changed.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by ftheirs** [comment]
Hi @czoido! I've seen that this feature was merged some days ago but I'd like to know if there is an ETA for the new conan release 😃
I'm having some issues because of the Xcode version and I need to update conan.

**Comment by janosvitok** [comment]
@ftheirs: If you need just get past the version check, you can manually add the version to your .conan/settings.yml file.
