### ISSUE TITLE
Revisit behaviour of revision_mode=scm when export or exports_sources are modified

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#12069]
Discuss what is the desired behaviour in the case of [this test](https://github.com/conan-io/conan/blob/527d2f4edf552b6ca0cc15661294da85a15e2443/conans/test/functional/revisions_test.py#L809-L818)  for Conan 2.0:
- Create a package with scm revision mode. The recipe revision is the hash of the last commit
- Modify the recipe
- Create again, the revision stays the same but the test checks that the changes are applied in the recipe

**Comment by memsharded** [comment]
Lets raise an error if the ``revision_mode="scm"`` and the export is dirty

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12267
