### ISSUE TITLE
[feature] Clang 16 has C++ std 17

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#12066]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hi,

Clang 16 has C++ std 17:
https://www.phoronix.com/news/LLVM-Clang-16-Default-GNU17

Diff:
https://reviews.llvm.org/rGe321c8dd2cea8365045ed44ae1c3c00c6a977d2e

Im posting because someone ask sometime ago, so i don't know if need change something for conan. I can make a PR if need.

**Comment by czoido** [comment]
Hi @paulocoutinhox,

Thank you so much for reporting. We'll change that in the default cppstd for Clang 16.
