### ISSUE TITLE
[bug] Cannot upload package to local nexus server

### ISSUE THREAD

**Issue by liorko87** [conan-io/conan#12078]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.04.1
  * Compiler+version: gcc 11.2.0
  * Conan version: 1.52
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)
I created a `conanfile.py` at my computer. I followed the tutorial https://docs.conan.io/en/1.52/index.html. When I'm trying to upload the package I'm receiving this error:

```
conan upload mypackage/1.0 --all -r myremote
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
Are you sure you want to upload 'mypackage/1.0' to 'myremote'? (yes/no): y
Are you sure you want to upload 'mypackage/1.0@mypackage/package' to 'myremote'? (yes/no): y
Uploading to remote 'myremote':
Uploading mypackage/1.0 to remote 'myremote'                                        
Uploading mypackage/1.0@mypackage/package to remote 'myremote'
ERROR: mypackage/1.0: Upload recipe to 'myremote' failed: 404: Not Found. [Remote: myremote]
ERROR: mypackage/1.0@mypackage/package: Upload recipe to 'myremote' failed: 404: Not Found. [Remote: myremote]
ERROR: Errors uploading some packages

```

**Comment by memsharded** [comment]
Hi @liorko87 

I am afraid that we cannot do much here, we do not maintain the nexus server. I would recommend to submit a report to their repository instead, thanks!

**Comment by liorko87** [comment]
Hi @memsharded
AFAIU the error is at the Nexus server?

**Comment by memsharded** [comment]
> AFAIU the error is at the Nexus server?

yes, I think so. You can always try locally with an ArtifactoryCE (free, you can get it in our download page), just in case to rule out something weird in your Client setup.

**Comment by liorko87** [comment]
After a conversation with Nexus support, the issue was using conan proxy repository instead of conan hosted repository.
