### ISSUE TITLE
Setting values in settings.yml and in default profile related to compiler version.

### ISSUE THREAD

**Issue by himansu2906** [conan-io/conan#12090]
Hello Team,

I am using old version of compiler (gcc, ver: 3.4) for my project, so to use conan, we had to update default profile and settings.yaml file with version number of old compiler.

default profile:
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86
compiler=gcc
compiler.version=3.4
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

settings.yaml value in compiler section: added 3.4 as version number in compiler version

**issue:** we want to update these file automatically with desired value with the help of CLI commands or by any other method so that it can be easily integrated in DevOps pipeline without manual intervention.

Thanks & Regards,
Himanshu

**Comment by memsharded** [comment]
Hi @himansu2906 

We have a command specifically for this: ``conan config install``.

You put the things you want in a github repo (including settings.yml, profiles, remotes, conf, etc), or in a zip file in a http server, and install it your developer machines and CI with one single command ``conan config install <url>``

**Comment by memsharded** [comment]
First, overriding ``default`` profile is not great, because it will change from machine to machine. You want to use your own named ``osx``, ``linux_xyz``, etc profiles in the general case.

The profiles should be in a "profiles" folder

**Comment by himansu2906** [comment]
Hi, 
even if I am renaming the file and putting in profile folder inside config folder, it is not copying files to profiles folder.
it is creating another folder config inside **.conan folder**  and putting all the profile files inside that.

**Comment by memsharded** [comment]
If you are putting things in a repo, then you don't name the root folder the "config" folder. The layout of the repo or zip to ``conan config install`` should be the same as the Conan cache, that means a ``profiles`` folder in the root.

**Comment by memsharded** [comment]
Closing the ticket as staled, I guess that you managed to make it work putting it in the right folder.
If not, please re-open or create a new ticket for any further question. Thanks!
