### ISSUE TITLE
[bug] Filenames generated by MSBuildDeps changed in 1.52.0

### ISSUE THREAD

**Issue by stefansli** [conan-io/conan#12098]
#11826 Causes a breaking change if the generated property files for dependencies are referenced directly instead of the general `conandeps.props`. We are doing this to link specific dependencies only into the projects that need the dependency.
This bug prevents us from updating to newer Conan versions because a "big bang" update for all developers and CI systems would be required.

Old file: `conan_dep-with-dash.props`
New file: `conan_dep_with_dash.props`

### Environment Details (include every applicable attribute)
  * Compiler+version: Visual Studio / MSBuild
  * Conan version: 1.52.0

### Logs

Error message:
```
The imported project "conan\generated\conan_dep-with-dash.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by stefansli** [comment]
While experimenting with a fix locally I also found this bug:
https://github.com/conan-io/conan/blob/45d2f85c09d3ab91618787911b39965ee4e17db1/conan/tools/microsoft/msbuilddeps.py#L49

Here the unmodified component name is used with breaks when a dependency has a transitive dependency on a component that contains forbidden symbols.

**Comment by stefansli** [comment]
@memsharded Any word on this? If this is not considered a bug, please close.

**Comment by memsharded** [comment]
Hi @vectorsli 

I am trying to understand why ``conan_dep-with-dash.props`` name worked for you. We changed this because the special chars were breaking the xml files, I am not sure why they were not breaking in your case, is it that only the ``+`` is breaking, but not the ``-``?

**Comment by stefansli** [comment]
Thanks for the response.

This is the `conan_dep-with-dash.props` generated with Conan 1.51.3:

```xml
<?xml version="1.0" ?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ImportGroup Label="PropertySheets">
		<Import Condition="'$(Configuration)' == 'Debug' And '$(Platform)' == 'Win32'" Project="conan_deb-with-dash_debug_win32.props"/>
		<Import Condition="'$(Configuration)' == 'Release' And '$(Platform)' == 'Win32'" Project="conan_deb-with-dash_release_win32.props"/>
		<Import Condition="'$(Configuration)' == 'Debug' And '$(Platform)' == 'x64'" Project="conan_deb-with-dash_debug_x64.props"/>
		<Import Condition="'$(Configuration)' == 'Release' And '$(Platform)' == 'x64'" Project="conan_deb-with-dash_release_x64.props"/>
	</ImportGroup>
	<PropertyGroup>
		<conan_deb-with-dash_props_imported>True</conan_deb-with-dash_props_imported>
	</PropertyGroup>
</Project>
```

We have been using these generated property sheets since Conan 1.39.0 and never had a Problem. We are using Visual Studio 2019 if that makes a difference.

**Comment by memsharded** [comment]
Do you have other packages that depend on such ``conan_dep-with-dash.props`` file? Or is it just 1-level dependency? Can you share the files of the consumers of dep, that should use the ``conan_deb-with-dash_props_imported`` as a value?

**Comment by stefansli** [comment]
Let's use a real-world example: `xerces-c`

In one of the generated property sheets there is this line:
```xml
    <Import Condition="'$(conan_xerces-c_props_imported)' != 'True'" Project="conan_xerces-c.props"/>
```
I guess that's what you wanted to know. I didn't look at the full dependency graph so I have no idea how deep `xerces-c` is involved. To answer your question, we have multiple dependencies with dashes in their name at different levels in the dependency graph.

**Comment by stefansli** [comment]
@memsharded According to the information I found, `[-._]` are allowed symbols for XML Tags. Only the first symbol of a tag may not be `[.-]`.

**Comment by memsharded** [comment]
Trying to avoid the filenames substitution in https://github.com/conan-io/conan/pull/12141.

Maybe just that the filenames changed is not enough reason, as it is experimental, but I think that if ``-`` doesn't break, better not replace it, as it will avoid other potential issues as collisions with ``+.`` substitutions.
