### ISSUE TITLE
Build once and split to many pacakages

### ISSUE THREAD

**Issue by Reonaydo** [conan-io/conan#1209]
Hello.
Is it possible to split one build to many packages? I want store executabes and libraries in different pacakges.

**Comment by lasote** [comment]
Yes, take a look to this section: 

http://conanio.readthedocs.io/en/latest/packaging/package_info.html?highlight=Build_id#build-once-package-many

**Comment by Reonaydo** [comment]
I read this. But I see here only how build one package with different options one time. Not different pacakges with different names. Can I define multimple package names via build_id ?

**Comment by lasote** [comment]
No. The build process only generate packages for the same package name.
In conan 0.22 (not released yet) we have prepared a `conan package_files` command to create packages from binaries directly from your disk, you could manage the build script without Conan and call that command N times to package the binaries.
https://github.com/conan-io/docs/blob/develop/reference/commands/package_files.rst

**Comment by memsharded** [comment]
Hi @Reonaydo 

Now, with the ``conan package_files`` command including a call to the ``package()`` method it is much easier: you can have your binaries, executables and libraries in your user folder, then write as many package recipes, for different packages as you want. Then directly export the binaries to the conan cache. Have you tried this approach?

**Comment by lasote** [comment]
Feel free to open the issue if you have more information.
