### ISSUE TITLE
[question] Best way to validate checksums 

### ISSUE THREAD

**Issue by valeriomoroni95** [conan-io/conan#12093]
Hi everyone! 
I'm opening a new issue about this argument because I need to understand which is the best way to validate checksums through Conan.
I have to follow this pipeline:
1. I receive pre built ".a" and ".h" files which I have to package in order to be uploaded, subsequently, on Artifactory.
2. I need to calculate checksums on each ".a" and ".h" file, in a pre-upload phase, and keep their value since they will be further rechecked in the download phase.
3. Once in Artifactory, the checksums are automatically calculated on the ".tgz", not on each file, so I can't use that value because it won't match directly with the checksum I calculated before.
4. When I decide to download the package I need to check if checksums are still the same of the above point 2.

If everything goes right, then OK, if (at any time) checksum get corrupted ---> abort the operation and report the error.

Which is the best way to do this? I don't know if it's better to use hooks, the `conan install [stuff] --verify` command or something else which I'm totally missing.

I'm currently using Conan version 1.52.0. 
Thank everyone in advance!  

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @valeriomoroni95 

It is not clear why the checksums for the files stored in the ``conanmanifests.txt`` are not good enough, maybe you can use them?

If not, you probably need to create your own file with the checksums, there are a few ways to do this:

- In the ``package()`` method directly
- In a ``post-package`` hook


It also depends a bit on how you are packaging those artifacts if they are prebuilt. Are you using the ``conan export-pkg`` command? Or ``conan create`` and fetching them from elsewhere?

**Comment by valeriomoroni95** [comment]
Hi @memsharded and thank you again for the answer,

I'll try to explain it better now. 
To package those artifacts I'm using the `conan export-pkg` command, creating a basic _conanfile.py_ in which I only use two methods, `package()` and `package_info()`. In the first one I specify that I need to copy ".a" and ".h" files.

Basically what I have to do consist in verifying that the checksums bounded to each file are the same and never change, both in upload and download phases. 
I'm a beginner in the Conan world, so I don't know if it's better to generate these checksums with the `conan install --manifests`, once the artifacts are packaged, or do it in another way. The same problem occurs in the download phase, where I don't know if it's better to use the `conan install [stuff] --verify` command or a hook.
These functionalities have to work, at the moment, locally, but further on they will be integrated in a Jenkins pipeline, so these checks need to be easy to automate and integrate.
For all of these reasons I have to keep this process as simple as possible, trying to reduce the necessary steps.

I don't know if it appears a little bit clearer now, I hope you understand.
Thank you so much in advice :)

**Comment by memsharded** [comment]
This seems a bit weird use case tbh, the security of Conan comes mostly because users use they own private Artifactory instance to host their packages, with access control, security, etc. If that is compromised, no matter what is done in the recipes and packages, because the attackers could replace the packages completely, including the checksums, etc.

Because the file checksums are already there, ``conanmanifests.txt`` files, they are created at package creation time and uploaded automatically. You could use a ``post`` hook to force the validation of those manifests.

So if it is related to security and the conanmanifests.txt is not enough, the approach would be:

- Have a ``post_package`` hook that capture the checksums, and store them elsewhere, not in the Conan package, that wouldn't make sense
- Have a ``post_download_package`` hook that would capture again the checksums of the downloaded artifacts, and validate them against the other storage of the previously package checksums.

**Comment by valeriomoroni95** [comment]
Yes, you're definitely right. My use case is just a basic approach trying to integrate Security in a DevOps pipeline already in use, but it doesn't guarantee absolute protection.

In any case, I suppose using hooks is the best option for my needs. Are there any python function which is already defined to create checksums? And to validate them afterwards? I think I read something about this in the documentation (I apologise for the banal questions, it's very important for me to understand well the steps I have to follow).

**Comment by memsharded** [comment]
Hi @valeriomoroni95 

Sorry this was not followed back then, sometimes load is too high and some tickets fall through the cracks.

Conan 2 is now out for 1 year, and it contains new features like package signing: https://docs.conan.io/2/reference/extensions/package_signing.html

Still, if security is a concern, the most recommended approach would still be the one of building your own packages from the recipes and store the binaries in your private repo, as recommended in https://docs.conan.io/2/devops/using_conancenter.html

I think we can close this issue as outdated, but please don't hesitate to create new tickets for any further question. Thanks!
