### ISSUE TITLE
[feature] fastbuild support

### ISSUE THREAD

**Issue by dev-joss** [conan-io/conan#12105]
Support fastbuild .bff generation for integration with fastbuild build system. https://www.fastbuild.org/docs/home.html

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by dev-joss** [comment]
Similar to visual studio .props files, I would expect conan to generate a .bff file with variables populated with the various dependency paths

**Comment by memsharded** [comment]
As we are lacking FastBuild expertise, I'd recommend interested users on this build system to give it a try, and set up a repo that contains a package recipe intended to be ``python_require``d with:

- A ``FastBuildDeps`` generator
- A ``FastBuildToolchain`` generator
- A ``FastBuild`` command wrapper

We might be able to give feedback and guidance, but it is unlikely that we will be able to put time in this after 2.0 (2.X), and that is a few months from now.

**Comment by memsharded** [comment]
Closing this as not planned at the moment.
If you want to contribute it, we will help, but it seems there is not enough users demand to make this a priority from our side. Thanks for the feedback!
