### ISSUE TITLE
[question] Conan download cache 0 revision packages does not work!

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#12109]
We have set up a Conan download cache to reduce the created traffic from the Artifactory instance to our CI/CD build machines.
Recently we have switched from using local Conan repositories as dependency package repositories to using a single virtual repository that contains all the local repositories.
Now we are facing again very high traffic from the Artifactory instance to our CI/CD build machines that I cannot explain to myself.

I am guessing that after switching from the local repos to the virtual one that the download cache is then invalidated since I read somewhere that in the filename of the download cache files the URL from where the package files were downloaded is embedded.

Is that guess correct?

Could it potentially also be that the download cache is not working at all when using virtual repositories instead of local repositories.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jellespijker** [comment]
I have noticed the same behavior. With a fresh cache directory btw.

**Comment by MTomBosch** [comment]
Can someone from Conan dev confirm that? 
If so that would be a huge problem for us since the only reason to move to a virtual repo was to workaround a bug in Conan 1.x where version ranges are not properly resolved if no virtual repo is used. And the bug is only fixed in Conan 2.0 that is not even released yet and even if so we cannot move to 2.0 so fast.

The issue is: https://github.com/conan-io/conan/issues/3113

**Comment by lasote** [comment]
It is probably that the data stored in the cache used when you had the local repository is not working if you change to a virtual, because the URL would change (Still I need to take a look at the cache key and the URLs that are used in a virtual repository).
But, are you saying that once you get the cache populated again with the "virtual repository" contents the cache is not working anymore? Could you confirm? So, you install a package twice and the cache is not hit?

**Comment by lasote** [comment]
FYI, the cache in Conan 2.0 is removed, we are waiting for feedback here: https://github.com/conan-io/conan/issues/11658

**Comment by MTomBosch** [comment]
I would understand that the cache would need to be filled again because the URL changes (from local to virtual) but looking at our numbers of downloaded packages I have a little bit the feeling the cache is not working at all with virtual remotes.

**Comment by jellespijker** [comment]
https://github.com/conan-io/conan/issues/11658#issuecomment-1246348893

> We also rely heavily on caching downloads between pipeline runs on our GitHub Actions.
https://github.com/Ultimaker/Cura/blob/d69819a24e89af2b35266b25c5bc91561048bb78/.github/workflows/conan-package-create.yml#L80
> 
> Mind you I'm not sure if this is really needed in our case, but since I can't see the actual bandwidth usage in our Artifactory Enterprise Edition it seemed like the most logical thing to enable as some defensive bandwidth limiting strategy.

**Comment by MTomBosch** [comment]
Ok. I have now found a reason for the huge number of downloaded package. The download cache was not enabled due to internal infrastructure issues. This might be the reason for the high number of downloaded packages.

Nevertheless it would be good if someone from the Conan dev team can either confirm or decline the above statement from @jellespijker .

**Comment by jellespijker** [comment]
> Nevertheless it would be good if someone from the Conan dev team can either confirm or decline the above statement from @jellespijker .

I will do a quick test myself as well, since my statement was based on observing some behavior while busy working on other tickets, and filing it in the back of my mind with the label :should_investigate:

**Comment by jellespijker** [comment]
I think this is a non-issue for Conan v1 and it works as expected. I got confused with the downloading of sources from secondary locations.

**Comment by MTomBosch** [comment]
Ok. Thanks for the info. I will still try it out on my machine too since our traffic was yesterday so huge again that the only explanation is that no cache is in place (which is). Will post an update once I have some news from my testing.

**Comment by MTomBosch** [comment]
@lasote I have figured out that there is a single tool (build require) that is creating 50 % of our download traffic. Now comes the fun fact. This tool was not uploaded with a revision but still has the default 0 revision since it was uploaded before we switched the conan configuration to use revisions. Could it be that in this constellation (usage of a virtual remote, enabled revisions but the biggest tool in use has only a default 0 revision) the download cache is not working for this tool?
I will do some black box testing but maybe someone can also dig into the src code to check my guess.

**Comment by MTomBosch** [comment]
I just tested and I can say that this is definitely (one or the) reason for the high traffic. The tool is always downloaded even if it is in the package cache. Question is now only if the revision is the root cause or something else.

**Comment by MTomBosch** [comment]
All packages that are downloaded over and over again are once with revision 0 whereas the others are nicely cached by the download cache. Can we change this ticket into a bug since this is not what was documented nor what can be expected (acc. to the documentation)?

**Comment by memsharded** [comment]
I think this is by design: When you enable the revisions, the protocol starts to use revisions, and drop file checksums. But as the old package with revision 0 is not being revisioned, it can be re-uploaded by another client with disabled revisions, changing its content and overwriting the file. So the client with revisions enabled can only be safe assuming that revisions=0 cannot be cached.

**Comment by MTomBosch** [comment]
It was not clear to me that the "checksum" for the file is the package/recipe revision itself and not some additional checksum that Artifactory is computing on its own for every uploaded file.

**Comment by memsharded** [comment]
> It was not clear to me that the "checksum" for the file is the package/recipe revision itself and not some additional checksum that Artifactory is computing on its own for every uploaded file.

Artifactory is not involved here, the cache also works for ``files.download()`` downloading from the internet. For Conan-server protocol, the revisions are checksums, and they are directly in the url, so Conan v2 protocol was directly leveraging that.

**Comment by MTomBosch** [comment]
Ok. Understood. Thanks for the clarification. If the doc related to the download cache would clearly mention that this would be a big help for other people that are interested in the download cache mechanisms.
