### ISSUE TITLE
[feature] conan.tools.gnu.Autotools.autoreconf: add a `working_dir` argument

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12103]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In `autoreconf()` method of `conan.tools.gnu.Autotools`, the working directory in which autoreconf is called is hardcoded to `conanfile.source_folder` (by the way it's not documented): https://github.com/conan-io/conan/blob/c5516cf408a69f55ea4c2d97d29ed82fbe728b30/conan/tools/gnu/autotools.py#L64-L65

But `configure.ac` may not be in root source code folder (example: `capnproto` recipe in CCI).

Could you add a `working_dir` argument to `autoreconf()` method (defaulted to `self.source_folder`) to change this working directory?

**Comment by SpaceIm** [comment]
@memsharded would it be possible to consider this feature? It would be useful in https://github.com/conan-io/conan-center-index/pull/12938

**Comment by prince-chrismc** [comment]
Thinking out loud, but the CMake layout has a "subfolder" https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake_layout.html#cmake-layout?highlights=subproject where to pull up the `CMakeLists.txt` I wonder if there's a layout here that could be doing the same?

**Comment by SpaceIm** [comment]
fixed by https://github.com/conan-io/conan/pull/13403 I guess
