### ISSUE TITLE
[question] Very simple conan package for header-only library

### ISSUE THREAD

**Issue by JeffHough** [conan-io/conan#12108]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I have a very simple header-only library (only a single file) which has functional cmake, and I would like to package it with conan. Building it on my own computer with cmake, I am able to include this package in my other projects as:

```
find_package(stl_reader REQUIRED)
...
target_link_libraries(<some_project> INTERFACE stl_reader::stl_reader)
```
I have tried to leverage this cmake, and created the following conan recipe for the library:
```
from conans import tools, ConanFile
from conan.tools.cmake import CMakeDeps, CMakeToolchain, CMake

class StlreaderConan(ConanFile):
    name = "stl_reader"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"
    options = { "fPIC": [True, False]}
    default_options = {"fPIC": True}
    generators = ["CMakeDeps", "CMakeToolchain"]

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def source(self):
        git = tools.Git(folder="stl_reader")
        git.clone("https://github.com/JeffHough/stl_reader.git", "add-cmake")

    def build(self):
        cmake = CMake(self)
        cmake.configure(build_script_folder="stl_reader")
        cmake.build()

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()

        # This writes all the config files (xxx-config.cmake)
        deps = CMakeDeps(self)
        deps.generate()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["stl_reader"]
```
But I get the following errors when I run cmake with the generated `conan_toolchain.cmake` file:
```
-- Conan: Target declared 'stl_reader::stl_reader'
CMake Error at build/generators/cmakedeps_macros.cmake:39 (message):
  Library 'stl_reader' not found in package.  If 'stl_reader' is a system
  library, declare it with 'cpp_info.system_libs' property
```
I am not sure why the project is unable to find the `stl_reader` target when installed through conan? I think I must be misunderstanding how the `self.cpp_info.libs` line works, but I am not sure. 

Thanks so much for your help!

**Comment by memsharded** [comment]
Hi @JeffHough 

Let me suggest a few fixes:

- Don't declare ``self.cpp_info.libs``, that is only for compiled libraries, header-only library doesn't need it
- You don't need ``CMakeDeps`` if you dont have dependencies
- Drop the ``options`` and ``default_options``
- Add a ``package_id()`` method, that does a ``self.info.clear()``
- Recommended to use tags or commits for the source ``git.clone("https://github.com/JeffHough/stl_reader.git", "add-cmake")``, but not something like a branch that is a moving thing. Actually, to package your own library, it is typically better to have your recipe in the source repo too, instead of having it in separate repo.

**Comment by JeffHough** [comment]
Hi @memsharded 

Thank you for your quick response! I've implemented all of your suggestions (other than the name of a branch in the git.clone call - I know a commit hash would be better, but right now the library is always somewhat in flux and I want the most up-to-date version on that particular branch).

I am no longer getting the errors I was getting before. However, I am having a different issue now - when I try to build my larger project, it claims to not be able to find the header files of the library I imported using the above conan recipe. Specifically I am getting the following error:

```
No such file or directory
#include <stl_reader/stl_reader.h>
```

Despite the fact that `stl_reader/stl_reader.h` is clearly contained in the `include` folder of the conan package.

[edit] - also to clarify, everything still works as expected if I just build the package using cmake and `find(stl_reader REQUIED)` to some install directory - so I _think_ the issue must still be isolated to how I am creating the conan package.

**Comment by memsharded** [comment]
> Thank you for your quick response! I've implemented all of your suggestions (other than the name of a branch in the git.clone call - I know a commit hash would be better, but right now the library is always somewhat in flux and I want the most up-to-date version on that particular branch).

But package management doesn't work that way. Once the source is there and the package is there, it should be considered immutable. Otherwise you could be basically overwriting contents without changing the name of the package, and consumers of the package will no be aware of the changes and still use the previous versions. A few things can go wrong with this approach.


The other issue now not finding the header could be a problem in the consumer, missing something. Do you have the conanfile and CMakeLists of the consumer so we could have a look?

**Comment by JeffHough** [comment]
Sure - I'll cut things down a little bit to the relavent portions, since I cannot share company code.

From the `conanfile.py` of the consumer:
```
from conans import ConanFile, tools
from conan.tools.cmake import CMakeDeps, CMakeToolchain, CMake
from conan.tools.layout import cmake_layout
import os

class ConsumerConan(ConanFile):
    name = "consumer"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"
    generators = ["CMakeDeps", "CMakeToolchain"]
    options = {
      "shared": [True, False], 
      "fPIC": [True, False], 
      "enable_testing": [True, False], 
      "enable_benchmarking": [True, False],}
    default_options = {
      "shared": False, 
      "fPIC": True, 
      "enable_testing": True,
      "enable_benchmarking": True,}
    exports_sources = ["**/**", "CMakeLists.txt", "Config.cmake.in"]
    requires = [
      ... lists out a bunch of other requirements...
      "stl_reader/1.0.0@mae-robotics/testing",
    ]

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def requirements(self):
      ... some if statements for optional dependencies (gtest, for example) ...

    def generate(self):
        tc = self._configure_cmake_toolchain()
        tc.generate()

        dep = CMakeDeps(self)
        dep.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def layout(self):
        cmake_layout(self)

    def package_info(self):
        self.cpp_info.libs = [... lists out the compiled libraries ...]

    def _configure_cmake_toolchain(self):
      tc = CMakeToolchain(self)
      ... sets a bunch of cmake variables ...
      return tc
```

And the relavent portions of CMakeLists.txt file:
```
project(consumer)
cmake_minimum_required(VERSION 3.16)

... some other `find_package` commands ...
find_package(stl_reader 1.0.0 CONFIG REQUIRED)

# different options we can run with:
option(BUILD_SHARED_LIBRARY "Do you want to build the consumer as a shared library?" OFF)
... some other options, related to things like whether to run tests, etc ...

if(BUILD_SHARED_LIBRARY)
  set(CONSUMER_BUILD_TYPE SHARED)
else()
  set(CONSUMER_BUILD_TYPE STATIC)
endif()

add_library(consumer
  ${CONSUMER_BUILD_TYPE}
  ... lists out some source files ...
)

target_include_directories(
  consumer
  PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>
)

target_compile_features(consumer PUBLIC c_std_99 cxx_std_11)

  target_compile_options(consumer
    PRIVATE
    -Wall
    -Wextra
    -Wpedantic
    -Wshadow
    -Wnon-virtual-dtor
    -Wpedantic
    -Wold-style-cast
    -Wcast-align
    -Wunused
    -Woverloaded-virtual

    # -Wsign-conversion
    -Wmisleading-indentation
    -Wduplicated-cond
    -Wduplicated-branches
    -Wnull-dereference
    -Wuseless-cast
    -Wdouble-promotion
  )

target_link_libraries(consumer
  PUBLIC
  ... lists out a bunch of other requirements ...
  INTERFACE
  stl_reader::stl_reader
)

... bunch of the usual cmake install commands, versioning etc for the consumer...
```

Does anything about these files stick out to you?

**Comment by memsharded** [comment]
Yes, the requirement to stl_reader in the consumer is not ``INTERFACE``, but ``PUBLIC`` or ``PRIVATE``. Interface means you don't use it, just your users (the consumers of ``consumer``) use it.

A couple of other hints:
- Don't use an option like ``"enable_testing": [True, False], `` if the testing doesn't actually produce a final different package. ``conf``, like ``tools.build:skip_test`` are preferred for these use cases.
- You have duplicated ``generators = ["CMakeDeps", "CMakeToolchain"]`` and then in ``generate()`` method. Use only one of them.

**Comment by JeffHough** [comment]
Ah yes, that did it! Thanks for the additional tips too - I am still very new with conan, and somewhat new with cmake, so it is very much appreciated.

**Comment by memsharded** [comment]
> Ah yes, that did it! Thanks for the additional tips too - I am still very new with conan, and somewhat new with cmake, so it is very much appreciated.

Great! 👏 Happy that you manage to make it work. Sure, don't hesitate to ask here for questions and support, we love to help as much as we can.
