### ISSUE TITLE
[feature] Option description

### ISSUE THREAD

**Issue by maksim-petukhou** [conan-io/conan#12112]
Are there any plans to add the ability to set a description for an option? Most of the time, options are self-explanatory, but when it's not the case and a library is a complex one you have to read recipe comments (or worse, the logic) to know exactly what an option does. [See](https://github.com/conan-io/conan-center-index/blob/9f24b5b7ead7db1f64329a7098bf6eeab63f9e99/recipes/boost/all/conanfile.py#L84) `boost` recipe options or [openssl](https://github.com/conan-io/conan-center-index/blob/a10e63147ecccad4bf0c9a61b6ff222f9f30fb6c/recipes/openssl/1.x.x/conanfile.py#L78) recipe options in conan-center for example. And it would be great to see the option's description when using `conan inspect`. 

I also have to mention that cache variables in CMake (which are widely used to control how a library is going to be built and Сonan options often duplicate them) do have descriptions ([see](https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry) `docstring`). 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @maksim-petukhov,

Thanks a lot for the suggestion, in fact this is already a Conan 2.0 feature. See: https://github.com/conan-io/conan/pull/11295 and https://github.com/conan-io/conan/issues/11108

You can use it like:

```
from conan import ConanFile
...
class Pkg(ConanFile):
    ...
    options = {"shared": [True, False, None], "fpic": [True, False, None]}
    options_description = {"shared": "Some long explanation about shared option",
                           "fpic": "Yet another long explanation of fpic"}
    ...
```

I'm closing this as the feature is already implemented, but please feel free to reopen or open another issue if you have any questions.

Thanks!

**Comment by maksim-petukhou** [comment]
@czoido That's great! Btw, I searched for `option description` beforehand but GitHub didn't show #11108 :)
