### ISSUE TITLE
[question] Why isnt cross compiling easier with Conan.

### ISSUE THREAD

**Issue by ohunter** [conan-io/conan#12118]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

From my understanding, Conan tries to simplify the mess that is C++ package management so that the developers of applications and libraries may focus on their own functionality and bugs instead of wrestling with their build system. That is great, but there are a few things that make me wonder whether some parts of the design of Conan is thought through. I think the idea of using profiles to specify various parameters which may affect the building of a project for a given target is a neat way of doing it. However; setting it up for cross compiling quite a mess once the dependency management becomes non-trivial.

Lets say I have a project that which I generally compile for Linux, but it is also distributed on Windows so I need to run CI on it. Creating a profile that uses mingw instead of gcc or clang is simple enough and the build process remains largely the same as I only have to configure my build system of choice to cross compile correctly (use `CMAKE_TRY_COMPILE_TARGET_TYPE` with cmake for instance).

Now if I want to add a dependency I don't want to worry about how that is built. Given that there doesn't exist a precompiled version of that library in any artifactory that I have access to I'm going to have to compile it myself. That is fair enough, but when doing so I dont think that I should have to worry about how the dependency is built other than having to set a few flags for the various features i want the build to support. The package maintainer should also not have to care about what toolchain I want to use as long as it can compile C/C++. If both use the same build system this is generally fine as the toolchain configuration applies to all dependencies (depending on your build system this may or may not be true, but for the sake of the discussion lets assume that).

Now lets say that I want to use a dependency that doesn't use the same build system that I am using. Conan seems to support this just fine as long as you have both build systems installed (which is a fair assumption imo). What it doesn't seem to support is the cross compilation of the aforementioned dependency out of the box.

Cmake (among other build systems) ensure that the compiler being used is a valid compiler for the language being used. Generally it does so by compiling a short program and then executing it and checking if the return value is correct. Logically when cross compiling; this does not work. Cmake allows the user to influence this by checking what the `CMAKE_TRY_COMPILE_TARGET_TYPE` value is set to. I am not sure how other build systems do it but I can't imagine them not supporting this type of modification of their behavior.

Based on [this](https://github.com/conan-io/conan/issues/4706) issue it seems like the current solution is that all library developers need to add a check for whether their project is being cross compiled; even when Conan knows that it is being cross compiled (it tells you in the terminal). This is not a good solution as it either forces upstream updates of every single package available through Conan, or forces the application developer to modify their dependency before using it. Another solution could be to specify it in whatever toolchain description for the build system that you're cross compiling. But doing so would mean that you need to know which build system your dependencies use, which build system your dependencies' dependencies use, ect. Also, you're already informing Conan of this in your profile so it makes no sense that you would need to inform all the targets in various manners.

Conan doesn't really care about what build system projects use and it shouldn't. As such I would argue that when a project uses Conan; it shouldn't have to care about what build system its dependencies use. Given my very limited experience with Conan, I would argue that this is the intention. Then why does Conan, which knows which build system is in use and that knows it is cross compiling something, not inform the build system that is shouldn't test the compiler or that it should test the compiler in a different manner?

**Comment by memsharded** [comment]
Hi @ohunter 

Conan can make it trivial to cross-compile something, depending of course on the capabilities of the underlying build system, and also the quality of the build scripts of a given project. As Conan is not a build system, and it mostly wraps build systems, there is little it can do if the project does not provide for it.

But for example, lets take a simple CMake project, that we can create with ``conan new hello/0.1 -m=cmake_lib``, and then with a profile like:

```
[settings]
os=Android
os.api_level=23
arch=armv7
compiler=clang
compiler.version=12
compiler.libcxx=c++_static
build_type=Release

[conf]
tools.android:ndk_path=C:\ws\android\android-ndk-r23b
tools.cmake.cmaketoolchain:generator=Ninja
```
Then a ``conan create . -pr=android_profile -pr:b=default`` will correctly manage to cross-compile that package to Android.


Your question above is too broad, and it would probably be much better if it could be split in several, smaller and very practical questions, about different aspects, because it also seems that there are some misunderstandings, like:

> Now lets say that I want to use a dependency that doesn't use the same build system that I am using. Conan seems to support this just fine as long as you have both build systems installed (which is a fair assumption imo). What it doesn't seem to support is the cross compilation of the aforementioned dependency out of the box.

This is, to use dependencies that uses a different build system that the one you are using, it is not necessary to have that build system installed. The default mode of Conan is fetching and installed the compiled binaries, and for that it doesn't need the build system at all. Only if it doesn't find a pre-compiled binary, Conan will error and tell the user they can opt-in to build the package from sources with ``--build=missing`` or ``--build=pkgname``, and only in that case, having that build system might be necessary. Actually in some cases, if the package itself has the build system declared as a ``tool_require``, it is not necessary to have the build system installed at the system level, as Conan will manage to use it from a COnan package that it will download.

**Comment by ohunter** [comment]
Hi, thanks for the quick reply. Although it seems that I could have been clearer in the original post. As for my question being too broad, I can see how the title is quite broad but the content presented in the question is as specific as it can be given my current understanding of Conan.
> Conan can make it trivial to cross-compile something, depending of course on the capabilities of the underlying build system, and also the quality of the build scripts of a given project. As Conan is not a build system, and it mostly wraps build systems, there is little it can do if the project does not provide for it.

Right. I am not saying it is a build system in any way, However; I would argue that Conan should do more than it currently does as a project shouldn't care about what compiler it'll be compiled with at some later date.


> This is, to use dependencies that uses a different build system that the one you are using, it is not necessary to have that build system installed. The default mode of Conan is fetching and installed the compiled binaries, and for that it doesn't need the build system at all. Only if it doesn't find a pre-compiled binary, Conan will error and tell the user they can opt-in to build the package from sources with `--build=missing` or `--build=pkgname`, and only in that case, having that build system might be necessary. 

Essentially what I am arguing is that if you have a dependency which has no precompiled version of the library for the configured profile. My example of this is a profile configured to cross compile stuff using `mingw` on Linux for Windows:
```
[settings]
os=Windows
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
build_type=Release
[env]
CC=/usr/bin/x86_64-w64-mingw32-gcc
CXX=/usr/bin/x86_64-w64-mingw32-g++
```
Using the profile above there are more than likely next to 0 existing precompiled libraries out there so any dependency you might use you would have to build yourself. As a result the dependency would need to be built no matter if the build system is preinstalled or fetched by Conan. What is important is that these build systems may test the compiler's functionality as outlined in the original question. [CMake](https://cmake.org/cmake/help/latest/command/try_compile.html#command:try_compile) and [Meson](https://mesonbuild.com/Compiler-properties.html) both do this which makes me think that it is not unreasonable to assume that other build systems do it as well. There are ways to influence their behavior when doing so (like `CMAKE_TRY_COMPILE_TARGET_TYPE` for cmake) but it makes no sense to put that burden on the dependency developer as that would require every dependency available through Conan to updated with such a fix (I'm not saying that dependencies shouldn't be allowed to check for this as well but that shouldn't be the requirement). 

This isn't an issue if all your dependencies use the same build system as the top level project would have to address this itself and since the configuration of the build system is applied to all instances of that build system it'd be resolved. However; if you have a dependency that does not use the same build system you would then have to configure their build system as well as yours. The same applies to your dependency's dependencies.

**Comment by memsharded** [comment]
Yes, it is true that not all build systems behave the same wrt different inputs, in this case as the environment variables ``CC`` and ``CXX``. The other ``settings`` should indeed be mapped from Conan to the different build systems if the packages are correct, but this env-var is something that Conan doesn't process, it goes to the environment. If some build system like Meson, or some project with non standard Makefiles (hardcoded compiler) doesn't listen to these env-vars properly, it will fail to cross compile.

That means that we need some further abstractions over the compiler that we haven't done yet, and that we are considering for example in https://github.com/conan-io/conan/issues/9962, that will be discussed. The idea is that if we add for example a ``conf`` which is ``tools.build:compiler`` for example, that is something that Conan can use and map to the different build system in the way they would understand.

**Comment by ohunter** [comment]
It is not the compiler that needs to be influenced but rather the build systems. If a build system checks whether the compiler it has been configured to use can compile a program correctly similar to that of cmake and meson, the build system should be informed that the default way of doing so is not correct when cross compiling occurs. This behavior should not be up to the project maintainer to implement as they have no way of knowing which compiler their project will be compiled with in the future.

**Comment by memsharded** [comment]
> It is not the compiler that needs to be influenced but rather the build systems.

Yes, this is what I am saying, the user defines the compiler, and that definition of the compiler is "injected" (Conan integrations are the ones that should do it, not recipe authors) to influence the build systems.

**Comment by ohunter** [comment]
Yes, but this should require no additional abstractions over the compiler. That seems like the wrong way to solve this. If I want to compile my stuff with some obscure compiler that Conan has never encountered before that would mean that the abstractions wouldn't exist for that compiler.

**Comment by memsharded** [comment]
> Yes, but this should require no additional abstractions over the compiler. That seems like the wrong way to solve this. If I want to compile my stuff with some obscure compiler that Conan has never encountered before that would mean that the abstractions wouldn't exist for that compiler.

I honestly don't understand what you mean. Please lets get things down to code and real examples.

What I am suggesting is something like a profile like this:
```
[conf]
tools.build:compiler_c=/usr/bin/x86_64-w64-mingw32-gcc
tools.build:compiler_cxx=/usr/bin/x86_64-w64-mingw32-g++
```

This can be passed to build systems that will use that compiler that the user defined. That would solve the issue that some build systems are not listening to CC, CXX env-vars. (for some build systems, the env-vars approach works well, our users have been cross-compiling happily using that approach without any issue)

**Comment by ohunter** [comment]
Ok, it seems like we want to address different issues here. The issue you are describing is that the build system doesn't listen to the conventional environment flags. I have not encountered that myself, but I can see how that is something that you would want to handle. The issue I would like to solve is that the build systems themselves need to be informed that testing the configured compiler has to be done differently. Without that, your solution only fixes half of the problem.

**Comment by ohunter** [comment]
I'm working on a minimum project to show what I mean more closely as I am generally terrible at explaining stuff.

**Comment by eli-schwartz** [comment]
> Conan. What is important is that these build systems may test the compiler's functionality as outlined in the original question. [CMake](https://cmake.org/cmake/help/latest/command/try_compile.html#command:try_compile) and [Meson](https://mesonbuild.com/Compiler-properties.html) both do this which makes me think that it is not unreasonable to assume that other build systems do it as well. There are ways to influence their behavior when doing so (like `CMAKE_TRY_COMPILE_TARGET_TYPE` for cmake)

Meson will, at configure time, log various stuff as it configures... one of those things is "Build type: XXX build", either "native" or "cross". During cross builds, unless an exe_wrapper (such as qemu-user) is also specified, Meson knows that it shouldn't try to sanity check the test program by running it.

It *will* still sanity test the native compiler if you have both native/cross targets in the same project.

Cross builds *have* to be set up via `--cross-file=path/to/cross-machinefile.ini`, so conan would need to know that it's a cross build and write the machine file out with the values for `tools.build:compiler_*`, among other things.

**Comment by ohunter** [comment]
I do feel like this is somewhat besides the question, but that is a good point. Although I suspect that there would be more complications with this approach due to how these build systems configure their toolchains. CMake, Meson, and Bazel all do this when configuring the project. Yet all of them have different requirements in terms of the tooling they need to have set up. I've done a fair bit of cross compiling for armv6-M and doing so with cmake versus bazel is night and day. This is why I believe that the first step with this would be to inform the build system at hand on how it should test the compiler (if at all).
