### ISSUE TITLE
[question] How to change the generator in `CMakePresets.json` generated by `CMakeToolchain` generator?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12113]
### Problem Description

If we execute `conan install` command with `CMakeToolchain` generator, there will be a `CMakePresets.json` file in the install folder. However, I noticed that the default generator in it is `Visual Studio 16 2019` when the environment is on **Windows** and the compiler is **MSVC**.

If I want to change it to for example `Ninja Multi-Config` generator, what should I do?

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/190143370-829c157d-88cb-4af9-ba3a-03dc94ae2c72.png)

**Comment by franramirez688** [comment]
Hi @hwhsu1231,

You can use this configuration `tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"` in your `profile`, in your `global.conf` file, or even via CLI with the `-c ` option.

**profile**
```
[conf]
tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"
```
Or:
**global.conf**
```
tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"
```

**Comment by hwhsu1231** [comment]
Got it. Thanks.
