### ISSUE TITLE
[bug] upload to artifactory fails

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#12111]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.04
  * Compiler+version: clang 14
  * Conan version: 1.52.0

### Steps to reproduce (Include if Applicable)
I have the following script to validate if build image for our CI is valid:
conan install zlib/1.2.12@ -r conancenter --build "zlib" --build missing -pr:h default -pr:b default --build missing
conan install zlib/1.2.12@ -r conancenter --build "zlib" -pr:h android_host -pr:b default --build missing

conan config set general.revisions_enabled=1
conan remote add artifactory https://reactivereality.jfrog.io/artifactory/api/conan/conan
conan user -p [MASKED] -r artifactory build_agent

conan upload '*' --all -r artifactory -c

### Logs (Executed commands with output) (Include/Attach if Applicable)

```++ source login_artifactory.sh build_agent [MASKED]
+++ set -e
+++ conan config set general.revisions_enabled=1
+++ conan remote add artifactory https://reactivereality.jfrog.io/artifactory/api/conan/conan
+++ conan user -p [MASKED] -r artifactory build_agent
Changed user of remote 'artifactory' from 'None' (anonymous) to 'build_agent'
+ source upload_recipe_to_remote.sh
++ set -e
++ source upload_recipe_to_artifactory.sh
+++ set -e
+++ conan upload '*' --all -r artifactory -c
Uploading to remote 'artifactory':

Uploading android-ndk/r25 to remote 'artifactory'                                        

Uploading cmake/3.24.0 to remote 'artifactory'                                           
Recipe is up to date, upload skipped

Uploading mypackage/1.0@demo/testing to remote 'artifactory'                             
Recipe is up to date, upload skipped

Uploading ninja/1.11.0 to remote 'artifactory'                                           

Uploading openssl/1.1.1q to remote 'artifactory'                                         
Recipe is up to date, upload skipped

Uploading zlib/1.2.12 to remote 'artifactory'                                            
Recipe is up to date, upload skipped

Uploading package 1/1: 5c09c752508b674ca5cb1f2d327b5a2d582866c8 to 'artifactory'         
Package is up to date, upload skipped

Uploading package 1/1: 48bdbfca0d97597c4cd2165da9b13473fca82b4a to 'artifactory'         
Compressing package...
Package is up to date, upload skipped

Uploading package 1/1: 24d596ecc3e7cfef35630620092c5615473ba82a to 'artifactory'         
Compressing package...
Uploading conan_package.tgz -> openssl/1.1.1q:24d5
Uploading conaninfo.txt -> openssl/1.1.1q:24d5
Uploading conanmanifest.txt -> openssl/1.1.1q:24d5

Uploading package 1/2: 058b5a2a5cbdf58a6a40855ea3a1b23e6a92ded5 to 'artifactory'         
Compressing package...
Package is up to date, upload skipped

Uploading package 2/2: 323eae4e1a804669bfea9d96feda948b70cdddbb to 'artifactory'         
Compressing package...
Package is up to date, upload skipped
ERROR: android-ndk/r25: Upload recipe to 'artifactory' failed: 404: Not Found. [Remote: conancenter]
The 'android-ndk/r25' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.


ERROR: ninja/1.11.0: Upload recipe to 'artifactory' failed: 404: Not Found. [Remote: conancenter]
The 'ninja/1.11.0' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.


ERROR: Errors uploading some packages
```

**Comment by AndreyMlashkin** [comment]
[full_log.txt](https://github.com/conan-io/conan/files/9564604/full_log.txt)

Here is the full log

**Comment by lasote** [comment]
Do you have the remote `conancenter` set up? By the way I don't see the upload in the full log.

**Comment by AndreyMlashkin** [comment]
[full_log.txt](https://github.com/conan-io/conan/files/9565013/full_log.txt)
Oh, strange, it's a totally different log file. Here we go

**Comment by AndreyMlashkin** [comment]
> Do you have the remote `conancenter` set up? By the way I don't see the upload in the full log.

Sure, I have it. It's enabled by default
```android-ndk/r25: Retrieving from server 'conancenter' 
android-ndk/r25: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
android-ndk/r25: Downloaded recipe revision 0```

**Comment by memsharded** [comment]
I think the main issue could be enabling the revisions after downloading things. Please try:

- Clean the cache completely
- ``conan config set general.revisions_enabled=1``
- Download the packages
- Upload them

Revisions are not intended to be changed between operations, they should be enabled always for the same cache.

**Comment by AndreyMlashkin** [comment]
Yes, that helped, thank you!

**Comment by AndreyMlashkin** [comment]
However, it would be cool to document somewhere, that it's not safe to chage general.revisions_enabled, when your cache is not empty,
