### ISSUE TITLE
[bug] fPIC is not forwarded anymore when using CMake tools

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#12127]
The fPIC compiler switch seems to be not forwarded anymore to cmake when using the cmake tools.

```
Building CXX object CMakeFiles/test-lib.dir/lib_a.cpp.o
/usr/bin/g++    -O3 -DNDEBUG   -o CMakeFiles/test-lib.dir/lib_a.cpp.o -c /home/user/.conan/data/conan-test/1.0.0/company/stable/source/lib_a.cpp
[100%] Linking CXX static library libtest-lib.a
```

I have following test case:
[conan-fpic-test-case.zip](https://github.com/conan-io/conan/files/9575984/conan-fpic-test-case.zip)

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux ubuntu 18.04 
  * Compiler+version: gcc7 
  * Conan version: 1.52.0
  * Python version: 3.6.9

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
> cd '/home/user/.conan/data/conan-test/1.0.0/company/stable/mbitionuser  build/66c5327ebdcecae0a01a863939964495fa019a06' &&
 cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" 
 -DCONAN_COMPILER_VERSION="7" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" 
 -DCONAN_LIBCXX="libstdc++11" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/home/user/.conan/data/conan-test/1.0.0/
 company/stable/package/66c5327ebdcecae0a01a863939964495fa019a06" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin"
  -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" 
  -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" 
  -DCMAKE_MODULE_PATH="/home/user/.conan/data/conan-test/1.0.0/company/stable/build/
  66c5327ebdcecae0a01a863939964495fa019a06" -DCMAKE_PREFIX_PATH="/home/user/.conan/data/conan-test/1.0.0/company/stable/
  build/66c5327ebdcecae0a01a863939964495fa019a06" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" 
  -DCMAKE_VERBOSE_MAKEFILE="ON" -Wno-dev '/home/user/.conan/data/conan-test/1.0.0/company/stable/source'
  
```

**Comment by czoido** [comment]
Hi @derived-coder,

I would say your CMakeLists.txt is missing something like:

```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```

Hope this helps

**Comment by derived-coder** [comment]
But CMake should be conan agnostic. The "way" I was told there should be no `if (conan)` or something like that in consumer build scripts.

**Comment by czoido** [comment]
> But CMake should be conan agnostic. The "way" I was told there should be no `if (conan)` or something like that in consumer build scripts.

That's the idea with the [new tools](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html)  that you integrate seamlessly with CMake, but your example is using the [cmake generator](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_generator.html) (that's why you need to include those lines) that we are recommending not to use any more and will dissapear in 2.0. Please check the docs about that, I would also recommend that you use the Conan built-in templates as a starting point for modern-style Conan recipes. You can use that simply doing:

```
conan new hello/0.1 --template=cmake_lib
```

**Comment by derived-coder** [comment]
okay using the new generator is the way to go. Thanks for clarification.
