### ISSUE TITLE
[bug] `conan create` fails to build the module for the first time

### ISSUE THREAD

**Issue by lukokr-aarch64** [conan-io/conan#12123]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04.4 LTS
  * Compiler+version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  * Conan version: 1.51.3
  * Python version: Python 3.8.10

### Steps to reproduce (Include if Applicable)
On a brand new recipie with a test package:
```
conan create package/sysroot sysroot/0.0.0@build+conan/main -pr:b=default -pr:h=default
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
I am seeing
```
ERROR: No package matching 'sysroot' pattern found.
```
And the test_package is seemingly happy to proceed regardless.
Full log: [conan.log](https://github.com/conan-io/conan/files/9572518/conan.log)

There are two ways to work around this issue, the first is to use:
```
conan export package/sysroot sysroot/0.0.0@build+conan/main  
conan install sysroot/0.0.0@build+conan/main --build=sysroot  
```
Which builds correctly, the second is to rename the test_package `mv test_package __test_package` in which case the `create` 
cmd also works correctly.

Happy to provide any debugging needed, please let me know if I have missed something here.

**Comment by lukokr-aarch64** [comment]
I think you can close this, seems to be an error on my part. I was missing:
```
        self.test_requires(self.tested_reference_str)
```
In my test package 👍

**Comment by memsharded** [comment]
Thanks @lukokr-aarch64 for reporting and following up with the fix 👍
