### ISSUE TITLE
[feature] Update distro requirement  to <=1.7.0

### ISSUE THREAD

**Issue by bkmgit** [conan-io/conan#12139]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
Latest version of Distro is 1.7.0, it would be good to support this in requirements.txt as breaking changes seem to be few, 
see https://github.com/python-distro/distro/blob/master/CHANGELOG.md

**Comment by czoido** [comment]
Thanks a lot for the contribution. It will be available in Conan 1.53
