### ISSUE TITLE
[question] Bitcode support is deprecated

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#12136]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I don't know if is relevant, but i will post only to conan team know it.

Apple deprecated Bitcode support after Xcode 14.

Release notes of Xcode 14:
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

```
Deprecations

Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.” The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols for past bitcode submissions remain available for download. (86118779)
```

Some discuss:
https://stackoverflow.com/questions/72543728/xcode-14-deprecates-bitcode-but-why

It still works but with warning:
https://www.techrepublic.com/article/demise-of-bitcode-future-security/

Flutter remove it too:
https://github.com/flutter/flutter/issues/107887

If it is not relevant, close pls.

**Comment by czoido** [comment]
Hi @paulocoutinhox,

Thanks a lot for the info. I think everything should be fine as enabling bitcode is an opt-in and by default it's not added. Anyway, it's nice to be aware, thanks!

**Comment by paulocoutinhox** [comment]
Ok, i will close since everybody knows about this. Thanks.
