### ISSUE TITLE
Documentation: Version and Channel recommendations

### ISSUE THREAD

**Issue by nunojpg** [conan-io/conan#1213]
Conan packages become more usable if they become predictable and consistent.

I have a hard time figuring out when is it supposed to use channels stable/testing/ci.

For example, if I'm packaging bleeding edge for CI, which should be version next, would you recommend that it is packed as next@ci or master@ci?

Essentially I think a style guide for deciding what to call Versions and Channels should be something quick to do (if you know what you are doing, so not me), and would be really of use before the number of packages start exploding.

Thanks,
Nuno

**Comment by memsharded** [comment]
Agree, but I think there is nothing to do on development, so I have submitted the issue to docs: https://github.com/conan-io/docs/issues/195
