### ISSUE TITLE
[question] How to set extra MSBuild properties in the MSBuildToolchain?

### ISSUE THREAD

**Issue by jellespijker** [conan-io/conan#12142]
I'm trying to modernize the cpython recipe in CCI that means porting to the MSbuild, MSBuildDeps and MSBuildToolchain generators. The current recipe passes an additional property `"IncludeExternals": "true"` https://github.com/conan-io/conan-center-index/blob/f85db3e60973cb076e694a1264946e29e82e66c5/recipes/cpython/all/conanfile.py#L395 to the build command; translating into an extra argument `/p:IncludeExternals="true"`.  There is an open FR which asks for allowing extra compiler flags to be passed https://github.com/conan-io/conan/issues/7653 but I can't seem to figure out how to set extra properties such at these, in the Toolchain. What is the preferred method to do so?

Current state of the PR https://github.com/conan-io/conan-center-index/pull/12470

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @jellespijker,

The current implementation of the MSBuildToolchain does not allow adding custom properties that can later be passed to the build system like other integrations do. I think we can mark this for the 1.53 to be added as a feature or at least to consider it. Thanks a lot for the reporting.

**Comment by jellespijker** [comment]
Great thx.

In the meantime I will just patch the `Directory.Build.props`
```python
replace_in_file(self, self.source_path.joinpath("PCbuild", "Directory.Build.props"), "</Project>",
                textwrap.dedent(f"""  <PropertyGroup>
                                        <IncludeExternals>true</IncludeExternals>
                                        <PlatformToolset>{msvc_version_to_toolset_version(self.settings.compiler.version)}</PlatformToolset>
                                      </PropertyGroup>
                                    </Project>"""), runtime_library)
```
