### ISSUE TITLE
[feature] Replace deprecated imp module with importlib

### ISSUE THREAD

**Issue by dheater** [conan-io/conan#12148]
The `imp` module was deprecated with Python 3.4 and is scheduled for removal with Python 3.12.

The minimum Python version supported by Conan is now 3.6, so we can now replace the last remaining instance of `imp` without needed any conditional statements.

Suggested replacement: https://csatlas.com/python-import-file-module/

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Already fixed in 2.0, thanks!
