### ISSUE TITLE
[bug] `conan create -kb` doesn't inject `tools.microsoft.bash:subsystem` config from `tool_requires`

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12154]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: MinGW 9 / gcc 11.2
  * Conan version: 1.52.0
  * Python version: 3.10.2

### Steps to reproduce (Include if Applicable)

- checkout https://github.com/conan-io/conan-center-index/pull/13038/commits/4e40e8ad67eb2d53bbe43949d7201d08b9d8651e (from https://github.com/conan-io/conan-center-index/pull/13038).
- on a windows machine call: `conan create . xz_utils/5.2.5@ -pr mingw_profile` (it should fail due to https://github.com/conan-io/conan/issues/12153)
- edit conanfile to add this workaround for https://github.com/conan-io/conan/issues/12153: `autotools.install(args=[f"DESTDIR={unix_path(self, self.package_folder)}"])`
- now call `conan create . xz_utils/5.2.5@ -pr mingw_profile -kb`

Be sure to not have `tools.microsoft.bash:subsystem` or `tools.microsoft.bash:path` set globally or in profile (they should come from `msys2` recipe which is in `tool_requires` of `xz_utils` recipe).

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: xz_utils/5.2.5: Error in package() method, line 149
        autotools.install(args=[f"DESTDIR={unix_path(self, self.package_folder)}"])
        ConanException: The config 'tools.microsoft.bash:subsystem' is needed to run commands in a Windows subsystem
```

**Comment by memsharded** [comment]
Note: ``--keep-build`` is deprecated and no longer recommended. If this issue doesn't happen without ``-kb``, then it can be closed as solved in 2.0.

**Comment by SpaceIm** [comment]
Is it documented somewhere? I don't see anything in https://docs.conan.io/en/latest/reference/commands/creator/create.html. What is the successor of `-kb`? It's very useful to test `package()` method without building everything again.

**Comment by memsharded** [comment]
Not explicitly documented in the migration guide, as it is more focused on the recipes, not all commands, but it can be added.

No successors, builds in the cache will always be clean, it will not keep a previous build just for the package. The alternative is a local ``conan export-pkg`` working from local flow (``conan install`` + native build system), which is the recommended approach.

**Comment by memsharded** [comment]
Closing as outdated, --keep-build removed in 2.0
