### ISSUE TITLE
[bug] CMakeToolchain reaches KeyError: 'buildPresets' when cmake_layout is missing

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12158]
Using `CMakeToolchain` without `cmake_layout` may cause an exception from Conan which is not useful for users:

```
catch2/3.0.1: Calling generate()
catch2/3.0.1: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
ERROR: catch2/3.0.1: Error in generate() method, line 102
	tc.generate()
	KeyError: 'buildPresets'
```

Full log: https://github.com/conan-io/conan-center-index/pull/13037#issuecomment-1252464349

Related to this recipe:

https://github.com/conan-io/conan-center-index/blob/bb058e289cb18125c84cb73a1dc8e4863ea5d5d4/recipes/catch2/3.x.x/conanfile.py

@SSE4 did a search and found that [presets.py](https://github.com/conan-io/conan/blob/cd98a1660fecfae60746e471d611bc7f939669a4/conan/tools/cmake/presets.py#L155) should be associated to it, and buildPresets is part of Json presets from CMake: https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: GCC 10
  * Conan version: 1.51.3
  * Python version: 3.7
  * Docker image: conanio/gcc10:1.51.3

### Steps to reproduce (Include if Applicable)

- Copy the recipe listed on the description and try to build on Linux

### Logs (Executed commands with output) (Include/Attach if Applicable)

Log is listed on CI result from CCI. The link is listed on the description.

**Comment by SSE4** [comment]
as CMake doc specifies, `buildPresets` is an optional field. the code should be tolerant for that missing key.

**Comment by SSE4** [comment]
also, adding an empty layout method changes nothing, same exception happens

**Comment by SSE4** [comment]
CMakePresets.json, might be useful:
```
cat /home/sse4/.conan/data/catch2/3.0.1/_/_/source/CMakePresets.json
{
    "version": 3,
    "configurePresets": [
        {
            "name": "basic-tests",
            "displayName": "Basic development build",
            "description": "Enables development build with basic tests that are cheap to build and run",
            "cacheVariables": {
                "CATCH_DEVELOPMENT_BUILD": "ON"
            }
        },
        {
            "name": "all-tests",
            "inherits": "basic-tests",
            "displayName": "Full development build",
            "description": "Enables development build with examples and ALL tests",
            "cacheVariables": {
                "CATCH_BUILD_EXAMPLES": "ON",
                "CATCH_BUILD_EXTRA_TESTS": "ON",
                "CATCH_BUILD_SURROGATES": "ON",
                "CATCH_ENABLE_CONFIGURE_TESTS": "ON"
            }
        }
    ]   
}
```

**Comment by cspanier** [comment]
I also just hit this bug. [Here](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) you can find the specification of the file format, which states:

> buildPresets
> 
> An optional array of Build Preset objects. This is allowed in preset files specifying version 2 or above.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/12874, for next 1.57
