### ISSUE TITLE
[question] should tools.microsoft.msbuild:vs_version come from build context, rather than host?

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#12171]
It looks like `compiler = msvc` and `conan.tools.microsoft.VCVars` does have support for using MSVC "down level toolsets" (e.g. using the VS2019 compiler, but installed as part of VS2022). 

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: Visaul Studio 2022 17.3, with v142 toolset installed
  * Conan version: 1.52.0
  * Python version: 3.10.7

### Logs (Executed commands with output) (Include/Attach if Applicable)

conan new --template=cmake_exe VCVars/0.1

conan create . --settings:host compiler=msvc --settings:host compiler.version=192 --settings:host compiler.cppstd=20 --settings:host compiler.runtime=dynamic --profile:build default

>  ConanException: VS non-existing installation: Visual Studio 16

conan create . --settings:host compiler=msvc --settings:host compiler.version=192 --settings:host compiler.cppstd=20 --settings:host compiler.runtime=dynamic --profile:build default --conf:build tools.microsoft.msbuild:vs_version=17

> ConanException: VS non-existing installation: Visual Studio 16

conan create . --settings:host compiler=msvc --settings:host compiler.version=192 --settings:host compiler.cppstd=20 --settings:host compiler.runtime=dynamic --profile:build default --conf:host tools.microsoft.msbuild:vs_version=17

> -- The CXX compiler identification is MSVC 19.29.30146.0

`[conf]tools.microsoft.msbuild:vs_version` (and really most of other conf entries under tools.microsoft, except for maybe `tools.microsoft.msbuildtoolchain:compile_options`) are about locating the the version of msbuild.exe/vcvarsall.bat to use as build tools. So I would have expected these to come from the build context, rather than the host one.

It's likely not a big deal in practice; realistically one probably installed MSVC system-wide, in which case it makes sense to put these in global.conf (and hence into both contexts), rather than in a profile or a coming from a tool_requires package. I hit this when I was just messing around with various cross-arch and down-level compiler settings just to understand what now worked. But found it surprising that they came from --conf:host, so I figured I'd at least ask if this was on purpose.

It would be, as far as I know, still technically possible to package MSVC as a tool_requires. Copying the VC\ folder worked in the past, and even used to specifically be documented and legal per the "Visual C++ BuildServer files" part of the licensing, e.g. https://learn.microsoft.com/en-us/visualstudio/releases/2013/2013-redistribution-vs#visual-c-buildserver-files. But this was never commonly done, and from VS2015 on up the permission to redistribute was replaced by the [Visual Studio Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) installer.

**Comment by memsharded** [comment]
This is a very good observation @puetzk, let see if this makes sense:

- We are cross building in a Windows Intel x68_64 machine to a ARM target, an application "myapp"
- We want that application to be built with VS 17 2022 with older v142 toolset.
- The application has a ``cmake`` ``tool_require``, and we want to build that ``cmake.exe`` with VS 16 2019 and even older v141, because the cmake codebase has some hardcoded defines and it won't compile with more modern setup.

The profiles would be:
**profile_host**
```
[settings]
compiler=msvc
compiler.version=192
compiler.cppstd=20 
compiler.runtime=dynamic

[conf]
tools.microsoft.msbuild:vs_version=17
```

**profile_build**
```
[settings]
compiler=msvc
compiler.version=191
compiler.cppstd=11
compiler.runtime=dynamic

[conf]
tools.microsoft.msbuild:vs_version=16
```

So the configuration is not the ``build`` one, even if it is referring to a "build" tool. It is the ``host`` one because that is the configuration we want to use to build a package in the ``host`` context.

Does this clarify a bit the question?

**Comment by puetzk** [comment]
Thanks. The mindset I had was thinking of this as a cross-compile from vs2022 to vs2019 (or whatever versions). The other one was the thinking of MSVC as a tool_requires, even though in practice it probably isn't acually being fetched by conan. But if it was (and back in the VS2013 days it wasn't that rare to just unzip the VC folder on a buildserver), you'd likely want that package to provide tools.microsoft.msbuild:installation_path via it's conf_info. Which (I was wrongly thinking), would end up in the build context.

But what I was missing is that ConanFile.conf does not truly belong to *either* context - each recipe in the graph has its own conf values, and they are potentially all different from *any* of the profiles, and from each other. Each recipe's self.conf is initialized based on global.conf and its the profile it's being built for, but tool_requires are copied in separately and additional to that.

https://docs.conan.io/en/latest/reference/conanfile/attributes.html#conf
>all the conf entries declared in the [[conf] section of the profiles](https://docs.conan.io/en/latest/reference/profiles.html#profiles-tools-conf) in addition of the declared [self.conf_info](https://docs.conan.io/en/latest/reference/config_files/global_conf.html#conf-in-recipes) entries from the first level tool requirements. 

So they are just a new kind of thing, that crosses the the build/host separation via self.dependencies, but only one level deep (they are gathered off direct build_requirements, but not transitive requirements-of-build_requirements). So my thought experiement of tool_requires = "msvc/..." would actually have worked fine.

What also *didn't* work, and threw me off after decided to try the simpler MSVC case first, is that we have a [build_requires]toolchain/... package in our profile, which has options that turn around and pull in various other pieces (sysroot, compiler, cmake toolchain files, etc) as its own requirements, to stitch together a kit for compiling to those settings. And the conf_info from those pieces was *not* showing up.  But that's because conf_info is not transitive, not because it's in the build context.

Presumably the solution to that is that this toolchain meta-package needs to explicitly copy conf_info things (like assembling tools.cmake.cmaketoolchain:user_toolchain) that it wants to propagate upward.

Which could be as simple as 
```py
def package_info(self):
    self.conf_info.compose_conf(self.dependencies["cmake-modules"].conf_info)
```

Though not quite that simple, since compose_conf is not documented, and https://docs.conan.io/en/latest/reference/conanfile/dependencies.html says
> At the moment, this information should only be used in generate() and validate() methods. Any other use, please submit a Github issue.

So I guess toolchain should know exactly which conf values it's passing through, store the information during generate() and then read it back in for it's package_info. Or something like that. Or refactor more; the reason for the intermediate package is really just to be have a place to hang some minor python logic code to choose is needed for a given group of settings, and I suppose that could probably be done within the profile now that this supports jinja templates and `{% import`.
