### ISSUE TITLE
[question] Version range smart search available? 

### ISSUE THREAD

**Issue by JackOfAllBugs** [conan-io/conan#12179]
I am looking to use version ranges for several of my development packages to get each of their latest versions, but I want to restrict the version search by the version of their primary shared dependency. 

```
[requires]
shared_package/2.3.4
pkgA/[>=1.0.0]
pkgB/[>=1.0.0]
pkgC/[>=1.0.0]
```

So if we have `pkgA/1.0.0` and `pkgA/1.1.0` built with `shared_package/2.3.4`, but `pkgA/1.2.0` built with `shared_package/3.0.0`, I would like conan's version range resolution to select `pkgA/1.1.0`.

Is this currently possible, or is there another way to achieve the same result?

**Comment by memsharded** [comment]
Hi @JackRenner 

I am afraid this is not possible. Such "smart" dependency resolution is an algorithm that requires backtracking and is known to be NP-hard. Given that the resolution of every node in the graph requires frequently to download, unzip, install, load and interpret a python or several python files, and evaluate a few methods of that python file, that makes this problem intractable in practice.

It is also true that in practice, users have versioning and continuous integration strategies to control how new versions are managed, typically either being conservative or trying to continuously move forward. In your scenario, different approaches could happen:
- ``pkg_a/1.2.0`` (use lowercase to be 2.0 ready), tries to depend on ``shared_package/3.0.0``, but it fails to integrate in the final product (your conanfile.txt), so it is rejected, and it is forced to continue on the ``shared_package/2.3.4`` version. 
- When the final product tries to integrate, detects the version conflict, and decides to move forward all dependencies to ``shared_pakage/3.0.0``. It might need to create new binaries for some packages, and some might need code changes
- The developers of the final product decide to explicitly limit ``pkg_a/[>=1.0.0 <1.2.0]``

**Comment by JackOfAllBugs** [comment]
Dang. I figured that this would be challenging to implement and use practically. I appreciate the response, and everyone's hard work on conan, its a fantastic tool!

**Comment by memsharded** [comment]
> Dang. I figured that this would be challenging to implement and use practically. I appreciate the response, and everyone's hard work on conan, its a fantastic tool!

Thanks for your kind words and following up with feedback on this issue! :)
