### ISSUE TITLE
[question] Is it safe to use self.package_path? ? 

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12173]
Related to https://github.com/conan-io/docs/issues/2753

The `self.package_path` is not documented but looks stable and it uses `Path` library, which is easier than `os.path` usage. 

/cc @jellespijker 

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
After syncing with the team, we are going to deprecate this.
Even if it is slightly more convenient for some users there are some downsides:
- it is ugly for an api to have duplicated things, it can be confusing for users
- The api inputs cannot be ``Path`` objects in general, as Conan internally uses old-style paths
- This cannot be changed, it would be breaking. It can be "fixed" and add adaptors in the definition points, but this surely be fragile and require time to polish, creating some instability.
- Users might have issues if they obtain ``Path`` objects via the Conan interface, but Conan failing when passing those objects as inputs.

As this was never really documented, it will be marked for deprecation and removed in few releases. Users wanting to use ``Path`` in their recipes can perfectly do ``Path(self.xxxx_folder)``, it is very simple and explicit in the recipe.
