### ISSUE TITLE
[question] CMakeToolchain and custom block: how to control position of the block & avoid boilerplate?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12189]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In conan-center, there are several conan v1 recipes with arbitrary logic in the CMakeLists wrapper (usually to avoid big patches, or improve robustness). Sometimes this custom code strongly relies on stuff previously defined (options, system processor etc).

So two questions for migration of these recipes to `CMakeToolchain`:

- Since `CMakeToolchain` set options, system processor etc, how to ensure that our custom logic is appended after all built-in blocks? Indeed, I've tested and my custom block was added right before Variables blocks.

- How to avoid this boilerplate:

   ```python
   def generate(self):
       tc = CMakeToolchain(self)
       class MyGenericBlock:
           template = textwrap.dedent("""\
               if(NOT TARGET glslang)
                   add_library(glslang INTERFACE) # fake target for upstream CMakeLists (glslang required by tests only)
               endif()
           """)

           def context(self):
               return {}

       tc.blocks["custom_block"] = MyGenericBlock
       tc.generate()
   ```

   why can't we simply do:

   ```python
   def generate(self):
       tc = CMakeToolchain(self)
       tc.blocks["custom_block"] = textwrap.dedent("""\
           if(NOT TARGET glslang)
               add_library(glslang INTERFACE) # fake target for upstream CMakeLists (glslang required by tests only)
           endif()
       """)
       tc.generate()
   ```

**Comment by memsharded** [comment]
Closing as not planned, not worth trying to simplify the full case, this is very edge case, the full class definition is necessary.
