### ISSUE TITLE
[bug] Error message tells me to run a command that doesn't work.

### ISSUE THREAD

**Issue by rnikander** [conan-io/conan#12183]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 13.0 Ventura (beta)
  * Compiler+version: Apple clang 14.0
  * Conan version: 1.52.0
  * Python version: 3.9.6

### Steps to reproduce (Include if Applicable)

I'm trying to follow the Getting Started documentation. I get to the step that asks me to run `conan install ..`, and I get this error:

> ERROR: Invalid setting '14' is not a valid 'settings.compiler.version' value.
Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1', '10.0', '11.0', '12.0', '13', '13.0', '13.1']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

Following the troubleshooting docs, I add "14" to the settings.yml file for the Apple's new clang version. I rerun `conan install ..`. I get a new error:

> ERROR: Missing prebuilt package for 'bzip2/1.0.8', 'expat/2.4.8', 'openssl/1.1.1q', 'pcre/8.45', 'poco/1.9.4', 'sqlite3/3.39.2', 'zlib/1.2.12'
Use 'conan search bzip2/1.0.8 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=missing'

If I do what it says and run `conan search bzip2/1.0.8 --table=table.html -r=remote`, I get an error:

> ERROR: '--table' argument can only be used with a reference

So much for "Getting Started"...

**Comment by memsharded** [comment]
Hi @rnikander 

That is true, it is necessary to add a missing ``@``, so ``conan search bzip/1.0.8@ --table=table.html -r=remote``

Thanks for reporting, we will fix it.

**Comment by rnikander** [comment]
Thanks! And with `conan install ... --build=missing` now everything in that "getting started" section works for me. Sweet.

**Comment by memsharded** [comment]
> Thanks! And with conan install ... --build=missing now everything in that "getting started" section works for me. Sweet.

Perfect!

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/12184, it will be released in next 1.53
