### ISSUE TITLE
[question] Is there a conan v2 build helper to honor profile in nmake builds?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12188]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In conan v1, to ensure that we honor profile in nmake build, we have this kind of pattern:

```python
            with tools.vcvars(self):
                with tools.environment_append(VisualStudioBuildEnvironment(self).vars):
                    self.run("nmake -f makefile.vc)
```

For vccars, there is `conan.tools.microsoft.VCVars` we can call in `generate()`, but how to properly populate `CL` & `LIB` so that build_type, runtime, `tools.build:cflags`, `tools.build:cxxflags`, `tools.build:defines` etc from profile are honored?

**Comment by SpaceIm** [comment]
@memsharded @lasote Nothing planned for NMake builds in conan v2? There are now at least 3 conan-center recipes more or less broken for msvc after a migration to conan v2, since they don't propagate build_type at build time, and even vc runtime for some of them, as well as stuff like `tools.build.cflags`, `tools.build.cxxflags`, `tools.build.ldflags`. libjpeg is built with NMake, it has been migrated and I suspect that it doesn't fully behave as expected. It's an important recipe.

**Comment by memsharded** [comment]
Hi @SpaceIm 

It is possible to directly create an environment script with ``Environment`` in the ``generate()`` method, and define there the necessary variables that such recipes need. I guess it might require a few lines of code, but if it is just CL and LIB env-vars, probably not that much. Probably we could have a specific generator for NMake, but seems a bit corner case, we don't have enough experience with it, and it also probably depends on the specific ``makefile.vc`` files, so the best would be to have working recipes first, and then extract from there the common knowledge into a tool/generator, depending on how it looks like. But it also depends on the need:

- Do those recipes have transitive dependencies they need to handle? I think probably not?
- Is just the ``build_type`` and ``runtime`` or something else used?
- `` it has been migrated and I suspect that it doesn't fully behave as expected.`` Do you have a bit more insights on what could be failing? I am fine with extra flags like ``tools.build:cxxflags`` not handled yet, it can be added later, but if some core binary compatibility is broken, it would be great to prioritize it.

**Comment by SpaceIm** [comment]
`VisualStudioBuildEnvironment` was the conan v1 build helper for NMake, it was handling at least build_type, runtime and dependencies. There is already a source of inspiration for a conan v2 build helper: https://github.com/conan-io/conan/blob/0b011fbd8f1f12b8a7c15a6716742ae0c7ece337/conans/client/build/visual_environment.py

That's a lot of code for a recipe, and this build helper relies on important methods not exposed in conan API like `build_type_flags`.

> Do those recipes have transitive dependencies they need to handle? I think probably not?

Not in recipes I've listed, but there are other conan-center recipes relying on NMake and with transitive dependencies.

> Is just the `build_type` and `runtime` or something else used?

Well, first there should be a clear conan specification of all the profile settings/conf etc which have to be honored in a build managed by conan.

For me a conan build should at least honor:

- flags induced by `settings.compiler.build_type`
- `settings.compiler.runtime`
- `settings.compiler.libcxx` (not relevant for NMake)
- host `settings.os`
- host `settings.arch`
- `tools.build.cflags`, `tools.build.cxxflags`, `tools.build.exelinkflags` & `tools.build.sharedlinkflags`
- `tools.build:jobs` (if supported by build system)

+ provide a mechanism to inject necessary cflags & ldflags with include dirs, interface definition, libdirs and libs of requirements

> `it has been migrated and I suspect that it doesn't fully behave as expected`. Do you have a bit more insights on what could be failing? I am fine with extra flags like `tools.build:cxxflags` not handled yet, it can be added later, but if some core binary compatibility is broken, it would be great to prioritize it.

In `libjpeg` recipe, build_type is not honored, so nothing would fail, but the build lies on the level of optimization a user should expect.

In `libmp3lame`, runtime & build_type are not honored, there are warnings at consume time with MD runtime in profile because the build is done with MT runtime: https://github.com/conan-io/conan-center-index/pull/13791#discussion_r1008586781

**Comment by memsharded** [comment]
Then, my proposal would be a new modern NMake dedicated generator.

**Comment by SpaceIm** [comment]
Current workaround: https://github.com/conan-io/conan-center-index/blob/62eb54fcf0911713889682f4e62927acaf4a82d9/recipes/libmp3lame/all/conanfile.py#L83-L89.
Not sure it works properly for `compiler=msvc`, and I guess it doesn't honor `tools.build.cflags` etc since it's a conan v1 build helper. But at least runtime & build_type flags are injected.
`settings.arch` is manually honored by replacing `/machine:I386` by `/machine:X64` or `/machine:ARM64` when needed in upstream `Makefile.MSVC` (again it's something which shouldn't be hardcoded in a Makefile, and conan build helper should inject these flags in case of cross-build: https://learn.microsoft.com/fr-fr/cpp/build/reference/machine-specify-target-platform?view=msvc-170).

**Comment by paulharris** [comment]
Is there some kind of time line for this?
I'm wondering because I want to start linking my stuff on Windows, so it feels like I have a few complex pathways thanks to the (half) upgraded recipes:
* link with recipes as-is and suffer possible link issues
* manually use older recipes (pre-upgrades)
* use @SpaceIm's patch and try to fix them up before the real solution comes
* wait for new Generator

**Comment by paulharris** [comment]
And, are we able to add a test that checks the correct runtime libs are actually linked?
ie via linter or some fail-fast linker error trick?
Incorrect linker errors are a pain to debug, and it would be great if CCI recipes can be relied onto do things right.  Close the door on this possibility!

**Comment by memsharded** [comment]
> Incorrect linker errors are a pain to debug, and it would be great if CCI recipes can be relied onto do things right. Close the door on this possibility!

I thought that some conan-center hooks were already checking the binaries for this kind of information with ``dumpbin``, but just checked and nop. It is worth to open a ticket in the hooks repo and request it, or even contribute it.

> Is there some kind of time line for this?

No timeline, it shouldn't be a huge effort, just a few hours, but we are right now overwhelmed so can't guarantee.

**Comment by SpaceIm** [comment]
> Current workaround: https://github.com/conan-io/conan-center-index/blob/62eb54fcf0911713889682f4e62927acaf4a82d9/recipes/libmp3lame/all/conanfile.py#L83-L89.

Actually it doesn't work, so here is another one: https://github.com/conan-io/conan-center-index/blob/9de5b6f3c7920b0a09dc9b94f2227ab3706abc08/recipes/libmp3lame/all/conanfile.py#L81-L89

It gives me build type & runtime flags in CL env var: `set "CL=-MD -O2 -Ob2"`

**Comment by memsharded** [comment]
I am proposing part of the effort here in https://github.com/conan-io/conan/pull/12516. It implements just the toolchain, not the dependencies management, that will go to another generator. Please review, and testing and feedback is very welcome!

**Comment by SpaceIm** [comment]
Thanks !

> For me a conan build should at least honor:
> * flags induced by `settings.compiler.build_type`
> * `settings.compiler.runtime`
> * `settings.compiler.libcxx` (not relevant for NMake)
> * host `settings.os`
> * host `settings.arch`
> * `tools.build.cflags`, `tools.build.cxxflags`, `tools.build.exelinkflags` & `tools.build.sharedlinkflags`
> * `tools.build:jobs` (if supported by build system)

@memsharded @franramirez688 I just want to mention that https://github.com/conan-io/conan/pull/12516 has not fully implemented what I think is a fully conformant basic conan generator for a build system:
- `tools.build.cflags`, `tools.build.cxxflags`, `tools.build.sharedlinkflags` & `tools.build.exelinkflags` handling
- maybe `tools.build:jobs`?
-  Injection of `settings.os` & `settings.arch` if cross-building.

**Comment by memsharded** [comment]
> @memsharded @franramirez688 I just want to mention that https://github.com/conan-io/conan/pull/12516 has not fully implemented what I think is a fully conformant basic conan generator for a build system:

- These generators are special, up to my knowledge they are exclusively aimed for ConanCenter, never seen users using it in production. I do not plan to make it a fully conformant one yet, lets get the minimum developed, used in ConanCenter, tested, and we will see how it goes.
- They are very limited in expressivity, just 3 env-vars CL, LIB, _LINK_. I prefer not to add any extra stuff like ``tools.build:xxxx`` until it is clear that the basic uses cases are satisfied. This is a very recent feature yet, and not all build systems will use it, for example, very popular libraries like openssl or boost do not inject these extra flags yet.
- Regarding ``os`` and ``arch`` not sure what you mean. The previous ``VisualStudioBuildEnvironment`` integration didn't do anything regarding those settings, it is not clear what should be passed to the compiler to cross compile.

**Comment by SpaceIm** [comment]
> Regarding os and arch not sure what you mean. The previous VisualStudioBuildEnvironment integration didn't do anything regarding those settings, it is not clear what should be passed to the compiler to cross compile.

I guess it's already handled by `VCVars` generators actually.

`tools.build:jobs` can be honored by injecting `/MP<build_jobs>` in `CL`, or just `/MP` if `tools.build:jobs` is not set (for consistency with other build systems).
