### ISSUE TITLE
[question] Is get_property("cmake_file_name") of dependencies always defined?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12187]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In `self.dependencies[lib].cpp_info` or `self.dependencies[lib].cpp_info.components[comp]`, is `get_property()` of either `cmake_find_mode`/`cmake_file_name`/`cmake_module_file_name`/`cmake_target_name`/`cmake_module_target_name`/`pkg_config_name` always defined (not None) regardless of wheter `package_info()` of this dependency/component has explicitly defined these properties?

In source code of conan I see sometimes tests to check whether these values are None.

**Comment by memsharded** [comment]
Sorry this was not responded back then. 
Those are ``None`` if not defined by the recipe.
