### ISSUE TITLE
Execute GTest/Unit Test as a part of a build (not a test_package test question)

### ISSUE THREAD

**Issue by ujjwal1002** [conan-io/conan#12198]
I am just trying my hand at Conan-IO+CMake, I am trying to execute UnitTests at build time and Conan/CMake is just not able to find the test executable. I have included my conanfile.py and CMakeLists.txt in the question itself.

Conanfile.py

from conans import ConanFile, CMake, tools
from conan.tools.cmake import CMakeToolchain,CMakeDeps
from conan.tools.layout import cmake_layout

class MylibConan(ConanFile):
    name = "mylib"
    version = "1.0.0"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of Mylib here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False],}
    default_options = {"boost:shared":False,"shared": False, "fPIC": True} # if shared is true, we would have this as a shared library
    
    generators="cmake","cmake_find_package","json","virtualenv"
    exports_sources = (
        "CMakeLists.txt"
    )
    no_copy_source = True
    #The below method would be triggered iff you unset the no_copy_source variable
    #def export_source(self):
    #    self.copy("*")
    @property
    def _cmake(self):
        cmake = CMake(self)
        return cmake
    def requirements(self):
        self.requires("gtest/1.12.1")
    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
    def generator(self): #Preprocessor
        tc = CMakeToolchain(self,generator='Ninja')
        tc.generate()
        CMakeDeps(self).generate() #creates findBoost.cmake
    def test(self):
        self.run("bin/runUnitTests")
    def build(self):
        cmake = CMake(self,generator='Ninja')
        cmake.configure(source_folder=self.source_folder)
        cmake.build()
        cmake.test(output_on_failure=True)
        # Explicit way:
        # self.run('cmake %s/hello %s'
        #          % (self.source_folder, cmake.command_line))
        # self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self._cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["hello"]

The following is my CMakeLists.txt file located in the same folder. This is the only CMakeFile in the entire project. I have included only the relevant portions

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
enable_testing()

find_package(GTest REQUIRED)

add_executable(runUnitTests UniteTest.cpp)
target_link_libraries(runUnitTests GTest::gtest)
add_test(runUnitTests runUnitTests)

I get the following error Message. Any ideas on how can I remedy this?

**Test project <project_location>/build
    Start 1: runUnitTests
Could not find executable runUnitTests
Looked in the following places:
runUnitTests
runUnitTests.exe
Release/runUnitTests
Release/runUnitTests.exe
Debug/runUnitTests
Debug/runUnitTests.exe
MinSizeRel/runUnitTests
MinSizeRel/runUnitTests.exe
RelWithDebInfo/runUnitTests
RelWithDebInfo/runUnitTests.exe
Deployment/runUnitTests
Deployment/runUnitTests.exe
Development/runUnitTests
**Development/runUnitTests.exe**
Unable to find executable: runUnitTests
1/1 Test #1: runUnitTests .....................Not Run   0.00 sec**

**Comment by memsharded** [comment]
Hi @ujjwal1002 

It seems you are using the legacy wrapper: ``from conans import ConanFile, CMake, tools``. You should use the new one too, to work with CMakeDeps and CMakeToolchain: ``from conan.tools.cmake import CMake``. You should also drop the legacy ``cmake`` and ``cmake_find_package`` integrations, and the ``include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)``, that is replaced for the toolchain and ``find_package()`` calls.

Then, a few extra hints:
- You don't want to use ``gtest`` as a regular requires, but ``self.test_requires()`` instead
- The ``test()`` method only works for ``test_package/conanfile.py``, not for regular packages
- Typically it is not necessary to hardcoded the ``CMakeToolchain(self,generator='Ninja')`` generator, you can leave the system default one and inject the one you want via ``conf`` in your profile with ``tools.cmake.cmaketoolchain:generator``
- You can drop the ``def _cmake(self):`` idiom, with the new integration it is fine to create a ``CMake()`` instance in every method.
- ``"boost:shared":False`` is the default already, you can drop it too.

**Comment by ujjwal1002** [comment]
Thanks @memsharded , are these best practices compiled somewhere? I wish to continue learning and it seems that such nuggets will definitely help me a lot!

**Comment by memsharded** [comment]
Sorry for not following up back then @ujjwal1002 

We are compiling some general best practices in https://docs.conan.io/2/knowledge/guidelines.html, and also the docs in Conan 2 are now sprinkled with ``Best practices`` notes whenever necessary, and also the tutorial explains things better.

I am closing this as responded and outdated, but please create new tickets if necessary. Thanks for the feedback!
