### ISSUE TITLE
[bug] Xcode generator is using "Unix Makefiles"

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#12195]
When i use generator equal `Xcode`, the preset file (CMakePresets.json) add two configurations, one with `unix makefiles` and other with `Xcode`. But when build with conan, it is selecting `unix makefiles`.

I put a log on my recipe file to print a message when system is apple and change the generator:

https://github.com/paulocoutinhox/conan-cmake-v2/blob/main/conan/recipe/conanfile.py#L76

and

https://github.com/paulocoutinhox/conan-cmake-v2/actions/runs/3120268476/jobs/5060717162#step:11:427

The log showing that it happen:

https://github.com/paulocoutinhox/conan-cmake-v2/actions/runs/3120268476/jobs/5060717162#step:11:554

The `CMakePresets.json` content:

```
{
    "version": 3,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 15,
        "patch": 0
    },
    "configurePresets": [
        {
            "name": "debug",
            "displayName": "'debug' config",
            "description": "'debug' configure using 'Unix Makefiles' generator",
            "generator": "Unix Makefiles",
            "cacheVariables": {
                "CMAKE_POLICY_DEFAULT_CMP0091": "NEW",
                "CMAKE_BUILD_TYPE": "Debug"
            },
            "toolchainFile": "/Users/paulo/Developer/workspaces/cpp/conan-cmake-v2/build/os-system/os-arch/conan/generators/conan_toolchain.cmake",
            "binaryDir": "/Users/paulo/Developer/workspaces/cpp/conan-cmake-v2/build/os-system/os-arch/target"
        },
        {
            "name": "default",
            "displayName": "'default' config",
            "description": "'default' configure using 'Xcode' generator",
            "generator": "Xcode",
            "cacheVariables": {
                "CMAKE_POLICY_DEFAULT_CMP0091": "NEW"
            },
            "toolchainFile": "/Users/paulo/Developer/workspaces/cpp/conan-cmake-v2/build/os-system/os-arch/conan/generators/conan_toolchain.cmake",
            "binaryDir": "/Users/paulo/Developer/workspaces/cpp/conan-cmake-v2/build/os-system/os-arch/target"
        }
    ],
    "buildPresets": [
        {
            "name": "debug",
            "configurePreset": "default",
            "configuration": "Debug"
        }
    ],
    "testPresets": []
}
```

When i use `Ninja` instead of `Xcode` in the same place of my conan recipe file, it use Ninja correctly:

```
conanfile.py (hello/0.1): CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/Users/paulo/Developer/workspaces/cpp/conan-cmake-v2/build/os-system/os-arch/conan/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "/Users/paulo/Developer/workspaces/cpp/conan-cmake-v2/."
```

But when use Xcode:

```
conanfile.py (hello/0.1): CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/Users/paulo/Developer/workspaces/cpp/conan-cmake-v2/build/os-system/os-arch/conan/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "/Users/paulo/Developer/workspaces/cpp/conan-cmake-v2/."
```

### Environment Details (include every applicable attribute)
  * Operating System+version: macos latest
  * Compiler+version: clang 13
  * Conan version: 1.52
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)

```
git clone https://github.com/paulocoutinhox/conan-cmake-v2.git
cd conan-cmake-v2
make ios
```

**Comment by paulocoutinhox** [comment]
What is most strange, is that if i comment this line:

```
generators = "CMakeToolchain", "CMakeDeps"
```

of my conanfile.py, everything works.

Im confused and don't understand what is wrong.

Can anyone help me?

**Comment by prince-chrismc** [comment]
Seems a little odd Conan adds two configs with the same name 😕 

***


You should be able to configure this with ur profile or from the cli

https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#conf

> `tools.cmake.cmaketoolchain:generator` CMake generator to be used by cmake CLI. See all the CMake generators [here](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#cmake-generators).

**Comment by paulocoutinhox** [comment]
Yes, but it add xcode build for all dependencies, what is a problem because not all dependencies are compatible.

There isn't a fix?

**Comment by prince-chrismc** [comment]
You should be able to use the same syntax for options and do `-c lib:*/cmake...` but I've never tried

**Comment by paulocoutinhox** [comment]
Yes, but this is not the real problem. Each dependency has their way to be
compiled.

The real problem is conan generate two presets.

**Comment by prince-chrismc** [comment]
Conan allows you to add configuration to the present, so you can have release and debug is you wish.

***

You can at a recipe level set the toolchain generator. But the global applies to all packages.

https://github.com/conan-io/conan/blob/45d2f85c09d3ab91618787911b39965ee4e17db1/conan/tools/cmake/toolchain/toolchain.py#L202-L205

**Comment by memsharded** [comment]
I think the issue is:

```
generators = "CMakeToolchain", "CMakeDeps"
```

You have declared generators twice. The attribute ones will use the standard configuration, while the ones in ``generate()``, you are overriding the default CMake generator, then it ends with 2 different configs.

You need to remove that line.
