### ISSUE TITLE
[bug][2.0] core.net.http:no_proxy_match has no effect

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#12201]
Our conan remote cannot be reached via the company proxy. So I created a global.conf with the following content:

```
core.net.http:no_proxy_match="conan.team.company.com"
```

conan seems to ignore that setting and use a proxy after all:

```
$ conan search -vvv -r conan \* 
=> _action: CONAN_API, name: remotes.list, parameters: {'pattern': 'conan', 'only_active': True}
=> _action: CONAN_API, name: search.recipes, parameters: {}
conan:
  ERROR: HTTPSConnectionPool(host='conan.team.company.com', port=443): Max retries exceeded with url: /v1/ping (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.04
  * Compiler+version:
  * Conan version: 2.0.0-beta3
  * Python version:

### Steps to reproduce (Include if Applicable)
1. Add remote that cannot be reached via proxy.
2. Add `core.net.http:no_proxy_match` setting to global. conf.
3. Perform conan action to access remote.

**Comment by ma30002000** [comment]
Any updates here?

**Comment by fschoenm** [comment]
This seems to have multiple issues:

1. `core.net.http:no_proxy_match` only works if you don't use the system proxy, i.e. you have to configure `core.net.http:proxies` for it to even be considered. 
2. The value has to be a list, which is documented but not checked. It just silently fails if you accidentally use a string. It would actually be helpful to also allow a string for single values but at least there should be an error.
3. The match is not calculated against the host name of the URL but the complete URL including the path, which does not make a lot of sense (and is also not how it works in any other NO_PROXY configuration as far as I know). It's not possible to define proxies for different paths on the same server. Please change it to only check against the hostname.
4. `fnmatch()`, which you're using, only matches the **complete** value. This is also not how NO_PROXY usually works. Most (all?) implementations automatically match subdomains (see https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/ for reference.) Only in conan you have to set `*.company.com` instead of `company.com`.

(I tried all that on Windows. Not sure if it behaves differently on Linux.)

**Comment by fschoenm** [comment]
Another point:

If `core.net.http:clean_system_proxy=True` is **not** set, all of the above still doesn't work. Not sure what happens internally, but the configured proxies in _global.conf_ are not used, the `no_proxy_match` is evaluated but not applied, and the system proxy is used after all.
