### ISSUE TITLE
[question] Any recommendation for managing conanfile.py of multiple git repo&versions?

### ISSUE THREAD

**Issue by wyl1232792** [conan-io/conan#12214]
# Background:

I have some git projects, and a simple conanfile for each of them, placed at the root of repository which runs git clone, dependency install, cmake build and package.
For example, the following conanfile.py is 

```
# conanfile.py in {PROJECT_DIR}
class MyConan(ConanFile):

    name = "MyPackage"
    version = "0.1"
    requires = [......]

    def source(self):
        pass # run git clone with "-b v0.1"

    def build(self):
        pass # build with cmake

    def package(self):
        ........
```

There is a painful workflow that when the main branch code changes, I'll modify the version string in conanfile.py from "0.1" -> "0.2" for example. And finally tag "v0.2" on the commit. 

# Questions  
I'm asking for the best practice. 
- Can I simpify somehow for avoiding changing conanfile.py all the time?
- Should conanfiles be managed in a centuralized repository or placed separately in code bases?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @wyl1232792 

Yes, you can use the ``set_version()`` method, to automate the definition of the version from whatever source you like, git, a file, etc. Have a look to: https://docs.conan.io/en/latest/reference/conanfile/methods.html#set-name-set-version and https://docs.conan.io/en/latest/howtos/capture_version.html#capture-version

**Comment by memsharded** [comment]
Did the above helped?

Regarding:

> Should conanfiles be managed in a centuralized repository or placed separately in code bases?

It depends:
- for managing third party dependencies, a centralized repo with all recipes, like conan-center-index, makes more sense
- For your own libraries and packages, having a ``conanfile.py`` in every repo that will create a package works better in general.

Please let me know if this makes sense. Could we close this issue?

**Comment by memsharded** [comment]
Closing this issue as responded, please re-open or file a new ticket if necessary. Thanks!
