### ISSUE TITLE
[question] Pipeline failures due to changes in packages

### ISSUE THREAD

**Issue by fittyCent** [conan-io/conan#12212]
My build pipeline failed after some time. I've made sure that the build image installs conan 1.50 and that it uses the lock file that was generated from the last successful conan install. So installing conan packages, I use `conan install . --lockfile=<lock file name>`. However after a few weeks, the pipeline broke again with this message:

```
ERROR: hiredis/1.0.2: Cannot load recipe.
Error loading conanfile at '/root/.conan/data/hiredis/1.0.2/_/_/export/conanfile.py': Unable to load conanfile in /root/.conan/data/hiredis/1.0.2/_/_/export/conanfile.py
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.conan/data/hiredis/1.0.2/_/_/export/conanfile.py", line 3, in <module>
    from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, rmdir
ImportError: cannot import name 'export_conandata_patches' from 'conan.tools.files' (/usr/local/lib/python3.8/dist-packages/conan/tools/files/__init__.py)
```

hiredis here is not listed in my conanfile.py. It's a dependency if redis-plus-plus which is listed in conanfile.py. Therefore I can't even lock down the revision of hiredis...

Using the latest version of conan (1.52 instead of 1.50) installs the packages without issue but something breaks during compilation. Is there a way to lock everything down so I don't have to fix a conan issue from time to time? 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @fittyCent 

This is unexpected. Indeed ``export_conandata_patches`` is a Conan 1.52 feature, and that updated dependency shouldn't be loaded if you are using a lockfile, because lockfiles lock dependencies and transitive dependencies. Can you please share the contents of the lockfile that you are applying, so we can try to reproduce?

**Comment by fittyCent** [comment]
Ah, glad that wasn't a silly question. Here's the lock file:

```
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "project_setup/0.1.0",
    "options": "hiredis:fPIC=True\nhiredis:shared=False\nhiredis:with_ssl=False\nredis-plus-plus:build_async=False\nredis-plus-plus:fPIC=True\nredis-plus-plus:shared=False\nredis-plus-plus:with_tls=False",
    "requires": [
     "1"
    ],
    "path": "conanfile.py",
    "context": "host"
   },
   "1": {
    "ref": "redis-plus-plus/1.2.3",
    "options": "build_async=False\nfPIC=True\nshared=False\nwith_tls=False\nhiredis:fPIC=True\nhiredis:shared=False\nhiredis:with_ssl=False",
    "package_id": "1ff2d8950185053e3b5f25c92726a9d5f09be25d",
    "prev": "0",
    "requires": [
     "2"
    ],
    "context": "host"
   },
   "2": {
    "ref": "hiredis/1.0.2",
    "options": "fPIC=True\nshared=False\nwith_ssl=False",
    "package_id": "6af9cc7cb931c5ad942174fd7838eb655717c709",
    "prev": "0",
    "context": "host"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++11\ncompiler.version=9\nos=Linux\n[options]\n[build_requires]\n[env]\n"
}

```


here's the conanfile.py
```
from conans import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain
from conan.tools.microsoft import MSBuildDeps

class ProjectSetupConan(ConanFile):
    name = 'project_setup'
    version = '0.1.0'
    settings = 'arch', 'os', 'build_type', 'compiler'

    def requirements(self):
        self.requires('redis-plus-plus/1.2.3')

    def generate(self):
        if self.settings.os == 'Windows':
            MSBuildDeps(self).generate()
        elif self.settings.os == 'Linux':
            CMakeDeps(self).generate()
            CMakeToolchain(self).generate()

    def layout(self):
        self.folders.generators = 'conan'

```

**Comment by memsharded** [comment]
That was useful.
The problem is this one:

```
 "2": {
    "ref": "hiredis/1.0.2",
    "options": "fPIC=True\nshared=False\nwith_ssl=False",
    "package_id": "6af9cc7cb931c5ad942174fd7838eb655717c709",
    "prev": "0",
    "context": "host"
   }
```
There is no recipe revision there. When you captured the lockfile you didn't have revisions enabled. That means that the revision is not defined and it is not locked. So changes to the ConanCenter recipes create new revisions, that your lockfile will get, because it is locking just the ``1.0.2`` version, but not the revision.

**Comment by fittyCent** [comment]
From what I understand, I'd specify a revision in the conanfile.py file by adding a revision hash after version number:
```
    def requirements(self):
        self.requires('redis-plus-plus/1.2.3#23a0ade1c897edb1673ee333be2264b4')
```

I just tried this and did a conan install. A lock file is created and there's no revision info in it and `revisions_enabled` in the lock file is false.

Two questions:
1. How do I enable revisions in lock files?
2. I tried all redis-plus-plus revisions and none of them work with conan 1.50. Probably because it's pulling the latest version of its hiredis dependency? Any way to get it to work with conan 1.50 again?

**Comment by memsharded** [comment]
You need to enable it in your ``conan.conf`` file, under ``[general]`` add ``revisions_enabled=True``. It can also be done with ``conan config set general.revisions_enabled=True``.

Please try:
- Completely remove the packages in your cache
- Enable revisions as suggested above
- Try again

**Comment by fittyCent** [comment]
I got `revisions_enabled` set correctly and lock file is showing that it's enabled.

However I still can't get conan 1.50 to install redis-plus-plus because it's still trying to pull the latest version of hiredis (this doesn't work with conan 1.50).

What I did to get conan to pull an earlier version of hiredis:
- clear all conan package cache
- uninstall conan 1.50. Install 1.52
- enable revision. Added revision number for redis-plus-plus (710614f878253ae67bfff6319fa01b3c)
- ran conan install. Went fine and generated a conen.lock file.
- edited conan.lock file so that hiredis points to an older revision (370dad964286cadb1f15dc90252e8ef3)
- deleted cache, installed conan 1.50, enabled revisions.
- run conan install with lock file.

What I'm getting now is this
```
redis-plus-plus/1.2.3: Not found in local cache, looking in remotes...
redis-plus-plus/1.2.3: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.25k]
Downloading conanfile.py completed [5.29k]
Downloading conan_export.tgz completed [0.31k]
Decompressing conan_export.tgz completed [0.00k]
redis-plus-plus/1.2.3: Downloaded recipe revision 710614f878253ae67bfff6319fa01b3c
hiredis/1.0.2: Not found in local cache, looking in remotes...
hiredis/1.0.2: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.30k]
Downloading conanfile.py completed [4.50k]
Downloading conan_export.tgz completed [0.29k]
Decompressing conan_export.tgz completed [0.00k]
hiredis/1.0.2: Downloaded recipe revision 370dad964286cadb1f15dc90252e8ef3
conanfile.py (simutils_setup/0.1.0): Installing package
Requirements
    hiredis/1.0.2 from 'conancenter' - Downloaded
    redis-plus-plus/1.2.3 from 'conancenter' - Downloaded
Packages
    hiredis/1.0.2:6af9cc7cb931c5ad942174fd7838eb655717c709 - Missing
    redis-plus-plus/1.2.3:1ff2d8950185053e3b5f25c92726a9d5f09be25d - Download

Installing (downloading, building) binaries...
ERROR: Missing binary: hiredis/1.0.2:6af9cc7cb931c5ad942174fd7838eb655717c709

hiredis/1.0.2: WARN: Can't find a 'hiredis/1.0.2' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=9, os=Linux
- Options: fPIC=True, shared=False, with_ssl=False
- Dependencies:
- Requirements:
- Package ID: 6af9cc7cb931c5ad942174fd7838eb655717c709

ERROR: Missing prebuilt package for 'hiredis/1.0.2'
Use 'conan search hiredis/1.0.2 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=hiredis'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

I checked conancenter and hiredis/1.0.2:6af9cc7cb931c5ad942174fd7838eb655717c709 does in fact exist for the settings I used.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/2008303/193010829-f92034af-d223-4c82-9795-c85845b625cb.png">


Any ideas?

**Comment by memsharded** [comment]
Could you please share your lockfile, after the edition of ``hiredis`` to pin the old revision?

**Comment by fittyCent** [comment]
Here it is:
```
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "project_setup/0.1.0",
    "options": "hiredis:fPIC=True\nhiredis:shared=False\nhiredis:with_ssl=False\nredis-plus-plus:fPIC=True\nredis-plus-plus:shared=False\nredis-plus-plus:with_tls=False",
    "requires": [
     "1"
    ],
    "path": "conanfile.py",
    "context": "host"
   },
   "1": {
    "ref": "redis-plus-plus/1.2.3#710614f878253ae67bfff6319fa01b3c",
    "options": "fPIC=True\nshared=False\nwith_tls=False\nhiredis:fPIC=True\nhiredis:shared=False\nhiredis:with_ssl=False",
    "package_id": "1ff2d8950185053e3b5f25c92726a9d5f09be25d",
    "prev": "be77d7b0068284cf7e0d99a2abb075d6",
    "requires": [
     "2"
    ],
    "context": "host"
   },
   "2": {
    "ref": "hiredis/1.0.2#370dad964286cadb1f15dc90252e8ef3",
    "options": "fPIC=True\nshared=False\nwith_ssl=False",
    "package_id": "6af9cc7cb931c5ad942174fd7838eb655717c709",
    "prev": "d299c500e88e0f92b5f9ad47103af552",
    "context": "host"
   }
  },
  "revisions_enabled": true
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++11\ncompiler.version=9\nos=Linux\n[options]\n[build_requires]\n[env]\n"
}
```

**Comment by memsharded** [comment]
You might try to invalidate the ``prev`` too. When you changed the recipe revision to an older one, the package revision was left the same. And it is impossible that such package revision exist for that older recipe revision. Try removing the ``prev`` field completely.

**Comment by fittyCent** [comment]
Ah I didn't know what `prev` meant. I did try to set it to `"0"` previously but that didn't work. Removing it completely did work. Thanks a lot for your help James!

**Comment by memsharded** [comment]
Super happy that it worked! 😄 

Lockfiles are a bit challenging to use and understand in 1.X, but we are very excited about the improvements done with lockfiles in 2.0, hopefully this will be much, much easier. If at some point you want to give them a try and give feedback, they are released in the beta.3 and some docs also there too: https://docs.conan.io/en/2.0/tutorial/consuming_packages/intro_to_versioning.html#lockfiles  Thanks!

**Comment by fittyCent** [comment]
Yeah I'll give beta a try on another project soon. I'm glad the lockfiles exist and that they're work great when used correctly. My pipeline is looking sturdier thanks to you guys.
