### ISSUE TITLE
[feature] Add options based on the version of a recipe

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12211]
This is from https://github.com/conan-io/conan-center-index/pull/13184#issuecomment-1260176736.

Currently the work flow we have resembles:

- `init`
- `config_options`
- "apply profiles"
- `configure`

The problem is conancenter uses `conan info` to learn about the available options but these do not take into account the version **AND** give users meaningful error messages

👉 Currently CCI allows users to pass options that are completely ignored so "I want this lib shared" does not actually mean you'll get a shared lib 😱 

### Adding it in `init`

we  do not have `self.version` at this point

```py
class PackageConan(ConanFile):
    name = "package"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"fPIC": [True, False]}
    default_options = {"fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/*", "include/*"

    def init(self):
        print(self.version)
        if Version(self.version) >= "0.2.0":
            self.options["shared"] = [True, False]
            self.default_options["shared"] = False
```

Sadly the version here being passed at the CLI is not known to the recipe

```sh
$ conan export . 0.1.0@
None
$ conan export . 0.2.0@
None
```

### Removing it from `config_options`

```py
class PackageConan(ConanFile):
    name = "package"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False],"fPIC": [True, False]}
    default_options = {"shared":  False,"fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/*", "include/*"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
        if Version(self.version) < "0.2.0":
            del self.options.shared
```

Makes the option completely unavailable in 0.2.0 (which is currently how CCI determines which are available)

```sh
$ conan inspect package/0.1.0@
name: package
version: 0.1.0
url: None
homepage: None
license: None
author: None
description: None
topics: None
generators: ['txt']
exports: None
exports_sources: ('CMakeLists.txt', 'src/*', 'include/*')
short_paths: False
apply_env: True
build_policy: None
revision_mode: hash
settings: ('os', 'compiler', 'build_type', 'arch')
options:
    fPIC: [True, False]
    shared: [True, False]
default_options:
    fPIC: True
    shared: False
deprecated: None
$ conan inspect package/0.2.0@
name: package
version: 0.2.0
url: None
homepage: None
license: None
author: None
description: None
topics: None
generators: ['txt']
exports: None
exports_sources: ('CMakeLists.txt', 'src/*', 'include/*')
short_paths: False
apply_env: True
build_policy: None
revision_mode: hash
settings: ('os', 'compiler', 'build_type', 'arch')
options:
    fPIC: [True, False]
    shared: [True, False]
default_options:
    fPIC: True
    shared: False
deprecated: None
```

`conan info` correctly fails

```sh
$ conan info package/0.1.0@ -o package:shared=True
ERROR: package/0.1.0: option 'shared' doesn't exist
Possible options are ['fPIC']
```

### using `configure`

```py
class PackageConan(ConanFile):
    name = "package"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False],"fPIC": [True, False]}
    default_options = {"shared":  False,"fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/*", "include/*"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if Version(self.version) < "0.2.0":
            del self.options.shared
```

The option is incorrectly available for 0.1.0

```sh
$ conan inspect package/0.1.0@
name: package
version: 0.1.0
url: None
homepage: None
license: None
author: None
description: None
topics: None
generators: ['txt']
exports: None
exports_sources: ('CMakeLists.txt', 'src/*', 'include/*')
short_paths: False
apply_env: True
build_policy: None
revision_mode: hash
settings: ('os', 'compiler', 'build_type', 'arch')
options:
    fPIC: [True, False]
    shared: [True, False]
default_options:
    fPIC: True
    shared: False
deprecated: None
$ conan inspect package/0.2.0@
name: package
version: 0.2.0
url: None
homepage: None
license: None
author: None
description: None
topics: None
generators: ['txt']
exports: None
exports_sources: ('CMakeLists.txt', 'src/*', 'include/*')
short_paths: False
apply_env: True
build_policy: None
revision_mode: hash
settings: ('os', 'compiler', 'build_type', 'arch')
options:
    fPIC: [True, False]
    shared: [True, False]
default_options:
    fPIC: True
    shared: False
deprecated: None
```

however this allows passing the option in (incorrectly to 0.1.0 where this does not exist)

```sh
$ conan info package/0.1.0@ -o package:shared=True
package/0.1.0
    ID: 0094e5ca692951fde1f9889e7498de22717262dd
    BuildID: None
    Context: host
    Remote: None
    Provides: package
    Recipe: Cache
    Revision: 4c221dc4b5c1214bcb9a4b99c3635aca
    Package revision: None
    Binary: Missing
    Binary remote: None
    Creation date: 2022-09-28 15:45:57 UTC
$ conan info package/0.2.0@ -o package:shared=True
package/0.2.0
    ID: 98e27508f54bda7aede57f76ae1de7dab93fe8c1
    BuildID: None
    Context: host
    Remote: None
    Provides: package
    Recipe: Cache
    Revision: 4c221dc4b5c1214bcb9a4b99c3635aca
    Package revision: None
    Binary: Missing
    Binary remote: None
    Creation date: 2022-09-28 15:46:02 UTC
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @prince-chrismc 

> The problem is conancenter uses conan info to learn about the available options but these do not take into account the version AND give users meaningful error messages

I would need more info about this. Why is ConanCenter using ``conan info`` to learn about the options? In theory all packages in ConanCenter are built with the default options? I guess it is for ``shared``? Maybe ``inspect`` is a better proxy for this?

Also, how it is called? ``conan info mypkg/version@`` will give you the info of that exact version, but I guess it is not the case, and applied over the local ``conanfile``? 

>  Currently CCI allows users to pass options that are completely ignored so "I want this lib shared" does not actually mean you'll get a shared lib

I though that this kind of divergence over the recipe is exactly when we wanted ``conan-center-index`` layout to be used, and define a new folder for the new versions in which the recipe changes. The ``all`` folder and a shared recipe should be used as long as the recipe is the same. If it isn't, then the design of ``conan-center-index`` tells to create a new folder, rather than introducing version conditionals in the recipe.

**Comment by prince-chrismc** [comment]
> Why is ConanCenter using `conan info` to learn about the options?

To list the options and find the ones that are supported, shared and header only are the ones I learnt about (fpic is default)

> Maybe `inspect` is a better proxy for this?

From what i played with, That command does not list the options, but computes the package info. Perhaps  there's a flag to list more?

CCI does not know which profile to apply yet so it "wants" a command with no profile or settings. Just the support options.

> how it is called? `conan info mypkg/version@` will give you the info of that exact version...

I am not 100% sure maybe @danimtb can confirm...
I believe it `conan export` the recipe for the version so it should be the full reference from the cache... that how I was testing it

**Comment by AbrilRBS** [comment]
We don't have this problem in CCI anymore, and the recommended approach has been to delete the option in `config_options` for a while now, which has worked wonderfuly, closing as solved
