### ISSUE TITLE
[feature] Add user_info support to the make generator

### ISSUE THREAD

**Issue by vajdaz** [conan-io/conan#12225]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Currently only `cmake`, `cmake_multi` and `txt` generators support `user_info` variables. I would like to use such variables with the make generator.

After looking into the sources, there seems to be a quite easy implementation, Here is my first litter (without test and docs yet): https://github.com/conan-io/conan/compare/develop...vajdaz:conan:feature/user-info-in-make-generator

The problem is, it does not support multiline string values. Adding support for that [would be quite difficult](https://www.gnu.org/software/make/manual/html_node/Multi_002dLine.html)

Is there a need for this feature?
Is it worth do put more efforts in this (add testing and adjust docs)?
Do we need multiline support? The `txt` generator does not support multiline, too (see #5794).
What do you think?

**Comment by memsharded** [comment]
Hi @vajdaz 

All those generators are considered legacy and deprecated, and they have been removed in Conan 2.0.

Same happens with the ``make`` generator, it has been removed. So a couple of hints:
- First step is to migrate to the new ``Autotools`` integration: https://docs.conan.io/en/latest/reference/conanfile/tools/gnu.html
- ``user_info`` has also been dropped in 2.0. In theory there are other ways to transfer information to consumers, so better report the use case against 2.0 with details, in a new issue.

**Comment by vajdaz** [comment]
Hi @memsharded 

I see. Thanks for the info. Then I close this issue.

**Comment by vajdaz** [comment]
> All those generators are considered legacy and deprecated, and they have been removed in Conan 2.0.
> 
> Same happens with the `make` generator, it has been removed. So a couple of hints:
> 

Hi @memsharded 

After locking into how `AutotoolsDeps` and `AutotoolsToolchain` generators work, it seems, I have a problem and need an advice.

I develop a legacy SW with Imake/GNU Make based build system. My application has a long list of dependencies that I would like to satisfy with Conan. With the `make` generator I am able to include the generated `conanbuildinfo.mak` in all of my Makefile files and control in every build directory which dependency I include/link/etc, because each dependency has its own make variable with the package name as a postfix.

With `AutotoolsDeps` and `AutotoolsToolchain` I have only cumulated `CXXFLAGS`, `LDFLAGS`, `LIBS`, etc variables. Therefore, no differentiation between packages is possible any more.But I don't want to have all include paths to be set in all of my build directories, or link all libraries in the link steps of all build targets.

How can achieve my goal without the  `make` generator in Conan 2.0?
