### ISSUE TITLE
[question] package_id with dependencies conan 2.0

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#12224]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I have a case where I depend on a library that has a lot of options (like Boost).  Most of the options determine weather a component is built or not.  My library only uses the "main" component.  The presence or lack of the other components doesn't impact my library at all as they are contained in separate .so or .a files.

In conan 1.0 I use the package_id method to modify the options and requirements of this dependency so that my library works no matter what options are included.  This does not appear to be possible in 2.0.  As a simple example:
```
def package_id(self):
  # Not a real example, but gives the idea.
  self.info.requires[<dep>].package_id = "ANY"
```
It looks like self.info is not populated with the dependencies at this point.  I'm not sure if this is a bug or intentional design.  Is there a better way to achieve what I am looking for?  There are a few different common sets of options in the dependency library.  I would like to maintain one version of my library that can be used with any of the sets of options.

**Comment by memsharded** [comment]
Hi @jsallay 

Conan 2.0 has dropped by default the influence of dependencies options in the consumers ``package_id``, instead it will use:

- A ``full_mode``, including the dependency ``recipe_revision`` and ``package_id``, if the native binary is being "embedded" (like when a shared library is linking a static library
- A ``minor_mode``, not including the dependency ``package_id``, if the binary is not being embedded, (like a static library that depends on another static library)

I am adding the test in https://github.com/conan-io/conan/pull/12233, that shows how this can be achieved, please see the full test, but this is the summary:

```python
def package_id(self):
      if self.dependencies["pkg"].package_type == "static-library":
          self.output.info("EMBED MODE!!")
          self.info.requires["pkg"].package_id = None
          self.info.options["pkg"].affect = self.dependencies["pkg"].options.affect
```

- We remove the influence of the full ``package_id`` on the consumer: ``self.info.requires["pkg"].package_id = None``
- We add the specific options we know will affect my binary: ``self.info.options["pkg"].affect = self.dependencies["pkg"].options.affect``

Please let me know if this helps.

**Comment by jsallay** [comment]
I think I understand.  I have a case with shared libraries.  Which I believe means that `minor_mode` will be used to include it.  So by default none of the options will matter for determining my package id.  Do the dependency settings factor into the package_id at all or is it really just the major and minor versions?

**Comment by memsharded** [comment]
Yes, all scenarios that do not embed the binary artifacts in the consumer will be ``minor_mode`` by default, meaning it will not depend on ``package_id``, nor the ``options`` of the dependencies. If there are some options that you know will affect (maybe some preprocessor definitions that affect the public API headers), then that could be factored-in as shown in the test of the PR.

The dependency settings would typically affect only the ``package_id`` of the dependency, but not the consumer one (they will do via its own logic, but not because of being from the dependency, in case the dependency has different settings)

**Comment by jsallay** [comment]
Great.  Thank you.   I'll go ahead and close this.  This was one of my last steps in porting our code to 2.0.  Once there is a fix for https://github.com/conan-io/conan/issues/12027 in, I believe that we will have our whole code base working in the 2.0 beta.  Thanks for your help.

**Comment by memsharded** [comment]
Fantastic, thanks for the feedback!
