### ISSUE TITLE
[question] Did you consider all the consequences of some depreciations in Conan 2.x?

### ISSUE THREAD

**Issue by vajdaz** [conan-io/conan#12227]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In Conan 2.0 both, `make` generator and `user_info` [will not be available any more](https://github.com/conan-io/conan/issues/12225#issuecomment-1264482707).

First, the `make` generator creates make variables that are separated by dependencies by means of make variable name postfixes. E.g. if my requirements contain `openssl` and `protobuf`, in the generated `conanbuildinfo.mak` there will be make variables  `CONAN_INCLUDE_DIRS_OPENSSL` and `CONAN_INCLUDE_DIRS_PROTOBUF` containing the inlcude paths of the packages.

Second, the `txt` generatror creates sections for `user_info` configuration entries. E.g. if the `conanfile.py` of my package `mypackage` adds `user_info` attributes in `package_info()`, after a package installation the `conanbuildinfo.txt` will contain:

```
[USER_mypackage]
my_attribute = my_value
```

I have a use case, where I have to integrate Conan into an imake / GNU Make based legacy build system, and I use both of the mentioned features to succesfully achieve that.

With Conan 2.0 I will lose both of the features.

The first loss I can circumvent by postproocessing `conanbuildinfo.txt` by myself after `conan install`, and create a file similar to `conanbuildinfo.mak` from `conanbuildinfo.txt` with own scripting.

However, there is no workaround for the second loss. I can put custom build config info into `config_info`, but that info does not appear in `conanbuildinfo.txt` any more.

`AutotoolsDeps` and `AutotoolsToolchain` generators do not solve my problem, because they cumulate the build configuration settings of all packages into one make variable (e.g. `CXXFLAGS`), so the buildsystem integration cannot pick the build coniguration setting of a specific dependenncy.

* Do you plant to support `user_config` instead of `user_info` the `txt` generator?
* Is there any architectural need of dropping the `make` generator? The implementation is quite simple, the maintenance costs should be not that big.
* Any other ideas how to achieve my use case with Conan 2.x in the future?

**Comment by memsharded** [comment]
Hi @vajdaz 

Yes, we have consider them. We have been working in Conan 2.0 for more than one year now, we have used the https://conan.io/tribe.html Tribe 2.0 to discuss and have feedback from users and we talk to users every day to discuss use cases.

> The first loss I can circumvent by postproocessing conanbuildinfo.txt by myself after conan install, and create a file similar to conanbuildinfo.mak from conanbuildinfo.txt with own scripting.

This is not the recommended way. Instead, the recommended way for custom integrations is to put the file generating code in a ``python_require`` and call it explicitly in your ``generate()`` methods. 
We are leaving the "standard" integrations as built-ins in Conan 2.0, and using the autotools conventions is the most standard way that can be achieved in the GNU ecosystem. There is also the ``PkgConfigDeps`` integration. 
Implementing such a generator is relatively simple, I can do it in a couple of hours. I know it is not that evident for all users, so please count with our help to assist you in that. Also, I am not against adding new generators as built-ins, but they should have some evidence of being useful for a significant amount of users. The maintenance costs are bigger than it seems, specially when not supported/used by enough users and not having enough feedback.

It is important to note that all these can be done in Conan 1.X, to have a smooth transition to 2.0 without breaking recipes.

> However, there is no workaround for the second loss. I can put custom build config info into config_info, but that info does not appear in conanbuildinfo.txt any more.

This is the thing we would like to understand your use case, but with details, the real config to use. What build config are you passing from one ``tool_requires`` to its consumers? How are the consumers expected to use that information? Why not env-vars? Maybe another custom generator is best suited?

**Comment by vajdaz** [comment]
Hi @memsharded 

thanks for the hint! Now I  see how my custom generator should be implemented. `PkgConfigDeps` is a good idea, too. However, an includable Makefile fits better for my needs.

If I am in the context of my `ConanFile` derived class, I also can access `user_config`, of course. So my second problem is solved, too,

About  the use case. We have some packages that contain more thant one static libraries and they have circular dependencies. The idea would be signal this situation in `user_config`. Then the generator altorithm would add package dependent make variables into the generated makefile which would contain `--start-group` and `--end-group` linker options for marked packages. The build system would then automatically put those make variables around the `-l<libname>` options by using the appropriate make variables.

Thank you for your very quick and professional answers. Extra thanks fo offering assistance. I see, I have to learn a lot about Conan. With such a top community support this will be easy.

I thinnk, my questions are answered, and I have a plan how to implement my use case. If you have no additional comments on my use case, I will close this question.

**Comment by vajdaz** [comment]
Hi @memsharded 

one question about custom generators, or the `Generator` class:

The custom generator seems only to access the `user_info` of the dependencies via `deps_user_info`, but not the `conf_info` of them. So, when I use `conf_info` instead of `user_info` in the package `conanfile.py` to propagate user data, as proposed by the docs, I still cannot access the info in a generator. Is this correct? If yes, the question is still open: How wil I be able to transport custom data from the package `conanfile.py` to any generator and access that custom data during install time?

**Comment by memsharded** [comment]
> About the use case. We have some packages that contain more thant one static libraries and they have circular dependencies. The idea would be signal this situation in user_config. Then the generator altorithm would add package dependent make variables into the generated makefile which would contain --start-group and --end-group linker options for marked packages. The build system would then automatically put those make variables around the -l<libname> options by using the appropriate make variables.

Thanks for the insights, this is interesting. It is not the first time the ``--start-group``, ``--end-group`` thing appears, we might try to give it some higher level modeling in Conan at some point.


> Thank you for your very quick and professional answers. Extra thanks fo offering assistance. I see, I have to learn a lot about Conan. With such a top community support this will be easy.

Thanks very much for your understanding. We know it is difficult when things are deprecated and removed, and it requires an extra effort from users. We are positive it will be for the better for all users, and we are very excited about what Conan 2.0 is bringing


> one question about custom generators, or the Generator class:

> The custom generator seems only to access the user_info of the dependencies via deps_user_info, but not the conf_info of them. So, when I use conf_info instead of user_info in the package conanfile.py to propagate user data, as proposed by the docs, I still cannot access the info in a generator. Is this correct? If yes, the question is still open: How wil I be able to transport custom data from the package conanfile.py to any generator and access that custom data during install time?

You are a bit in the wrong direction, sorry for not providing better guidance earlier. You are seeing the old docs, for writing a 2.0-ready generator you need to have a look to the new generators in the ``conan.tools.xxxx`` folders, like ``AutotoolsDeps`` or ``PkgConfigDeps``. They will be using the ``self.dependencies`` access for dependencies which is way more flexible and complete than the previous ``deps_cpp_info``. This interface has access to ``conf_info``, please have a look to: https://docs.conan.io/en/latest/reference/conanfile/dependencies.html

Lets keep this issue open a bit more, unless until you have the new generator in the good direction, and then we can close and use new issues for further conversation. Thanks!

**Comment by vajdaz** [comment]
With your guide, I could implement a very easy custom generator (less than 100 LOC) that can now replace the `make` generator (in my project at least, because it is not a general/portable solution). It not only creates make variables for inlcude dirs, library dirs, etc., but also for `conf_info` user declared attributes. So, this implementation is now Conan 2.0 ready.

I have one remark on the topic. Non of the existing built-in generators seem to do something with `conf_info`, so there was no "best practice" how to access it. To be able to access it, I had to save a reference to the `ConanFile` object in the `__init__` function of my custom generator. Without that I did not find a way to access `conf_info` using the existing data attributes and functions inherited from the base class `Generator`. What is the intended way to access `conf_info` from a custom generator that is derived from `Generator`?

**Comment by vajdaz** [comment]
I have two libs, libA and libB. libA requires libB. A package consumer has a `conanfile.py` that requires libA and libX How can I programmatically access the the list of the common include directories of libA and libB in a custom generator? A am not interested in the aggregated include dirs of all required packages (libA, libB, libX), but only in the direct and indirect requirements of libA.

**Comment by memsharded** [comment]
> I have one remark on the topic. Non of the existing built-in generators seem to do something with conf_info, so there was no "best practice" how to access it. 

Yes, the ``conf_info`` of ``tool_requires`` is now automatically passed to consumers, and aggregated into its ``conf``. Not explicitly used by other generators, but implicitly, as other generators will read a conf that might have been defined by such ``tool_requires`` dependency.

It is true that we are trying to learn about use cases. We know that this ``conf`` as a mechanism to pass custom information from tool-requires to consumers is probably the most popular one. But if your use case doesn't fit into this, please let us know.

> What is the intended way to access conf_info from a custom generator that is derived from Generator?

Recall that modern generators should not derive from ``Generator`` at all. They are just one class that receives a ``conanfile`` as first argument, and have a ``generate()`` method with no arguments (or defaulted arguments).


> I have two libs, libA and libB. libA requires libB. A package consumer has a conanfile.py that requires libA and libX How can I programmatically access the the list of the common include directories of libA and libB in a custom generator? A am not interested in the aggregated include dirs of all required packages (libA, libB, libX), but only in the direct and indirect requirements of libA.

You mean something like this?:
```python
class MyGenerator:
    def __init__(self, conanfile):
         self._conanfile = conanfile
    def generate(self):
         for d in self._conanfile.dependencies.host.values():  # Only host have includes, but not build context
              includedirs = d.cpp_info.includedirs
              # do something with it
```

**Comment by vajdaz** [comment]
If I don't derive from `Generator`, I get an error `ERROR: Invalid generator` (generator class is in a separate package, used with `python_requires` in the consumer `conanfile.py`).

No, I mean soemthing like this:

```
      consumer conanfile.py -> (requires = "libA/1.0", "libX/1.0")
        /   \
       /    libX
      /
   libA -> (requires = "libB/1.0")
   /
libB
```

When the packages are in the cache...
`libA`'s include dir is `~/.conan/.../libA/.../include`
`libB`'s include dir is `~/.conan/.../libB/.../include`
`libX`'s include dir is `~/.conan/.../libX/.../include`

What I want to achieve in the generator is to see the relationship: "Because of my requirement **`libA`** I need to include both, `~/.conan/.../libA/.../include` **AND** `~/.conan/.../libB/.../include`"

If I do this...
```python
        for require, dependency in self._conanfile.dependencies.items():
            aggr_cpp_info = dependency.cpp_info.aggregated_components()
            # do something with
            require.ref
            # and
            aggr_cpp_info.includedirs
```
...then I can iterate over all aggregated requirements and see all their include directories. But I can't see the cumulated include directories of the requirement `libA` with all of its indirect requirements (without that of `libX`!).

**Comment by vajdaz** [comment]
Some additional info to the previous comment about the use case. I have a legacy imake/GNU Make base build system. The source tree contains several subprojects, which have their own build configuration. But all these sub-projects share the same consumer `conanfile.py`, which contains the requirements of all of the subprojects. A single subproject may only depend on one of them (e.g. subproject1 only depends on `libA`, but not `libX`. My generator should create make variables for each direct dependency, which contains the aggregated include paths of that dependency like this:

```
MY_GENERATED_INCLUDE_DIRS_LIBA = /home/me/.conan/.../libA/.../include /home/me/.conan/.../libB/.../include

MY_GENERATED_INCLUDE_DIRS_LIBB = /home/me/.conan/.../libB/.../include

MY_GENERATED_INCLUDE_DIRS_LIBX = /home/me/.conan/.../libX/.../include

```
Then I can create imake macros in the imake rules files like this:

```
#define ConanIncludeOptions(package_name)  $(addprefix -I, $(Concat(MY_GENERATED_INCLUDE_DIRS_,package_name)))
```

and use it in the `Imakefile` file of a subproject that depends on `libA` like this:

```
ADDITIONAL_INCLUDES = ConanIncludeOptions(LIBA)
```

**Comment by memsharded** [comment]
> If I don't derive from Generator, I get an error ERROR: Invalid generator (generator class is in a separate package, used with python_requires in the consumer conanfile.py).

Because custom generators are not intended to be called by name (``generators = "Something"``), but instead explicitly:
```python
def generate(self):
     mygen = self.python_requires["mypyrequires"].module.MyGenerator(self)
     mygen.generate()
```

This is what allows also user customization from the consumer side, as you can do:
```python
def generate(self):
     mygen = self.python_requires["mypyrequires"].module.MyGenerator(self, optional_arg1=123)
     mygen.other_optional_thing = "something"
     mygen.generate(another_optional_arg=[1, 2, 3])
```

For knowing the dependencies of each dependency, the ``.dependencies`` exists for them, so something like this?:
```python
def generate(self):
      for d in self.dependencies.host.values():
           transitives = [t.ref.name for r in d.dependencies.host.values()]
```

**Comment by vajdaz** [comment]
Thanks! Now my generator works as I wanted it, and it is Conan 2.0 ready, too.

I discovered, that you also can transport custom  info from the package maintainer to the installer by using the `set_property()` and `get_propery()` of `cpp_info`.

What is the difference between adding a custom property to `cpp_info` with `set_property()` and defining a `config_info` with `define()`? When should I use the first, when the second?

**Comment by memsharded** [comment]
> Thanks! Now my generator works as I wanted it, and it is Conan 2.0 ready, too.

Excellent! Happy to hear that.

> What is the difference between adding a custom property to cpp_info with set_property() and defining a config_info with define()? When should I use the first, when the second?

``cpp_info`` properties are intended to complement all the ``cpp_info`` C++ including and linking information (similar to ``includedirs``, ``libs``, ``libdirs``, ``defines``, ``cxxflags``), with specifics for build systems and related stuff, but core information how to consume the C/C++ artifacts in the package

The ``conf`` system is generally used for controlling details about how the build system integrations behave: if a build system should be more or less verbose, if things should be downloaded in parallel, the location of some tool like android ndk path, etc, etc. Even if it has some configs like ``tools.build:cxxflags`` they have a different meaning and intention than the ``cxxflags`` that a package can define to its consumers via ``cpp_info``. The config ``tools.build:cxxflags`` is a mean to inject extra flags to the build, like a toolchain, while the ``cpp_info.cxxflags`` try to pass some flags that "if you don't use these flags, you will not be able to link correctly against this library" (this latter cpp_info.cxxflags is pretty exceptional).

**Comment by vajdaz** [comment]
Thanks for all the information and the help you gave. I have no more questions about this topic, so I close the issue.
