### ISSUE TITLE
[bug] self.cpp_info.builddirs default value causes CMAKE_PREFIX_PATH to be mutated during find_package

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#12237]
The CMakeDeps generator generates CMake config files with this statement:

https://github.com/conan-io/conan/blob/develop/conan/tools/cmake/cmakedeps/templates/target_configuration.py#L89-L91
```
        set(CMAKE_MODULE_PATH {{ '${' }}{{ pkg_name }}_BUILD_DIRS{{ config_suffix }}} {{ '${' }}CMAKE_MODULE_PATH})
        set(CMAKE_PREFIX_PATH {{ '${' }}{{ pkg_name }}_BUILD_DIRS{{ config_suffix }}} {{ '${' }}CMAKE_PREFIX_PATH})
```

Where `<pkg_name>_BUILD_DIRS_<build_type>` points to the root of the package by default, as these are the contents of `cpp_info.builddirs`.

In a scenario where we are:
* cross building 
* have the same dependency as a `requires` and a `tool_requires`, and this dependency contains at least one library (for the `requires` and an executable to be invoked at build time (the `tool_requires`)

if the consumer CMakeLists calls `find_package()` for the library, followed by `find_program()` for the executable, the first call (`find_package()`) will alter `CMAKE_PREFIX_PATH` in a way that the subsequent `find_program()` call will find the executable for the `host` profile, rather than for the `build` profile.

There should be little reason for a generated `-config.cmake` file to alter the value of `CMAKE_PREFIX_PATH` if the dependency has already been found (i.e. the file is being parsed by CMake), and where needed, `CMakeToolchain` already handles that logic.

**Comment by memsharded** [comment]
> There should be little reason for a generated -config.cmake file to alter the value of CMAKE_PREFIX_PATH if the dependency has already been found (i.e. the file is being parsed by CMake), and where needed, CMakeToolchain already handles that logic.

The origin of this feature was allowing users doing an ``include(somecmakefile)`` with ``somecmakefile`` inside the dependency ``builddirs``, after a ``find_package()``. This will still be possible with the paths defined in ``CMakeToolchain``? I'd say the above case would still happen?

**Comment by jcar87** [comment]
Currently investigating this:

@memsharded  - for the specific use case of being able to do `include(a-cmake-module)`, where `a-cmake-module.cmake` is a file that exists inside a package, only `CMAKE_MODULE_PATH` would need to be updated. This issue is specific to `CMAKE_PREFIX_PATH`, which once mutated, alters the behaviour of every subsequent `find_*` call in CMake.

The `cpp_info` property that affects this is `builddirs` - however the behaviour is different in Conan 1.x and Conan 2.0:
* Conan 1.x: the default is the root of the package folder - this is part of what causes the issues as this happens implicitly
* Conan 2.x: the default is empty

The migration [docs](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#changed-cpp-info-default-values)  mention that that in Conan 1.x we can get Conan 2.x behaviour if the `layout()` method is used, but I've tried this on a toy recipe and I can see that in Conan 1.x the `builddirs` property is always initialised to the root of the package folder, whether a `layout()` is declared or not.

There is also a newer attribute, `cmake_build_modules`, which is only documented [here](https://docs.conan.io/en/2.0/reference/tools/cmake/cmakedeps.html?highlight=cmake_build_modules). I think arguably this attribute is much better named, but it doesn't behave exactly the same, as it will automatically `include()` the files as part of solving `find_package()`.

I think we need to understand which use cases are impacted here.

From the consumer's `CMakeLists.txt` view, I believe we have 3 cases:

1. We want to call `find_package()`, and the consumer wants to call `include()` explicitly afterwards, for a CMake module that exists in the package.
```
find_package(FooBar)
include(foobarutility)
```
This would require updating `CMAKE_MODULE_PATH` somewhere in the generated config files for the dependency. Theoretically this could also be done in the toolchain file rather than the generated config files, with the difference that `include(foobarutility)` would be callable without find_package. I think to remove any doubt it would be good to see examples of this pattern out in the wild / ConanCenter.

2. We want to call `find_package()`, and we want that call to include `.cmake` files inside the package (perhaps generated by CMake)
```
find_package(FooBar)
```
This is the case when the generated FooBar config files (generated by Conan), need to `include()` .cmake files that exist in the package itself. This is transparent to the consumer. In this case I think we wouldn't need to update `CMAKE_MODULE_PATH` at all, as the file could be referenced directly (since Conan knows where it lives relative to the root of the package).


I think there's a third case, where a package may contain its own generated `-config.cmake` files and the user wants to use those instead of the Conan generated ones. While we do discourage, I think this should be possible at the user's risk. 
It is *only* in this instance where I see a case of updating `CMAKE_PREFIX_PATH`, but it wouldn't have to happen in the files generated by `CMakeDeps`, it would have to be `CMakeToolchain`.


My summary:
In Conan 2, `cpp_info.builddirs` is empty by default and its opt-in - it covers a narrow use case at best (although I could be wrong). I think it could have a better name (it's not "build directory" the way it is typically understood). 

I fail to see _any_ case in which we may want the files generated by `CMakeDeps` to update the value of `CMAKE_PREFIX_PATH`.

**Comment by SpaceIm** [comment]
> > There should be little reason for a generated -config.cmake file to alter the value of CMAKE_PREFIX_PATH if the dependency has already been found (i.e. the file is being parsed by CMake), and where needed, CMakeToolchain already handles that logic.
> 
> The origin of this feature was allowing users doing an `include(somecmakefile)` with `somecmakefile` inside the dependency `builddirs`, after a `find_package()`. This will still be possible with the paths defined in `CMakeToolchain`? I'd say the above case would still happen?

It won't be possible after https://github.com/conan-io/conan/pull/12229 (without conan toolchain), it's the responsibility of `CMakeToolchain` to manipulate CMAKE_PREFIX_PATH / CMAKE_MODULE_PATH.
