### ISSUE TITLE
[feature] Allow users to enable verbose Makefile in CMakeToolchain

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12239]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Same feature request than https://github.com/conan-io/conan/issues/9772, but for `CMakeToolchain`.

The idea would be to inject `set(CMAKE_VERBOSE_MAKEFILE ON)` in CMakeToolchain if a specific conf is enabled.

Maybe a common conf could be shared to enable verbosity to all build systems supporting this kind of feature.

**Comment by memsharded** [comment]
Existing ones:

"tools.microsoft.msbuild:verbosity": "Verbosity level for MSBuild: 'Quiet', 'Minimal', 'Normal', 'Detailed', 'Diagnostic'",
"tools.apple.xcodebuild:verbosity": "Verbosity level for xcodebuild: 'verbose' or 'quiet",
