### ISSUE TITLE
[bug] Bazel generator add tools and build dependencies as bazel deps 

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#12236]
### Environment Details (include every applicable attribute)
  * Operating System+version: Any
  * Compiler+version: Not relevant
  * Conan version: 1.51.2 and 1.52.0 , but maybe all since the bazel generator exists
  * Python version: 3.10.6 , but not relevant

### Steps to reproduce (Include if Applicable)

Install / use a package like `mongo-c-driver` and use the bazel generator to get a bazel file

```
    deps = [
        # do not sort
        ":mongoc-static-1.0_precompiled",
        ":bson-static-1.0_precompiled",
        "@openssl",
        "@snappy",
        "@zlib",
        "@zstd",
        "@icu",
        "@pkgconf",
    ],
```

`"@pkgconf"` is a tool and build requirement. 

Please have a look at the recipe:
https://github.com/conan-io/conan-center-index/blob/5225f30ee00d5f295419dc632cd29d4491a9d394/recipes/mongo-c-driver/all/conanfile.py#L94

Such build or tool requirements should not be on the list of dependencies.  They might not even exist in case of cross-compiling.

**Comment by czoido** [comment]
Hi @a4z,

Thanks for reporting, I'll mark as an issue and we will have a look for the next release.

**Comment by a4z** [comment]
I just rebuilt mongo-c-driver and still got `@pkgconf` in the final BUILD file
Seems the complexity of this issue is not that low ...  

Huge thanks for keeping up on the issue!  ❤️ Looking forward to 1.55. release!
