### ISSUE TITLE
`AR` and `RANLIB` variables are not being picked up when `CMakeToolchain` is being used

### ISSUE THREAD

**Issue by szigetics** [conan-io/conan#12232]
I built the `fmt` recipe ( https://github.com/conan-io/conan-center-index/tree/master/recipes/fmt ) for WebAssembly using emsdk 3.1.14 ( https://github.com/conan-io/conan-center-index/tree/master/recipes/emsdk ) .

When I try to use the built package, I receive build errors about missing symbols : 
```
em++: warning: /Users/myUser/.conan/data/fmt/8.1.1/jenkins-clt/stable/package/93b09e919707eae1e87c217c1903aef1ceda69e2/lib/libfmt.a: archive is missing an index; Use emar when creating libraries to ensure an index is created [-Wemcc]
em++: warning: /Users/myUser/.conan/data/fmt/8.1.1/jenkins-clt/stable/package/93b09e919707eae1e87c217c1903aef1ceda69e2/lib/libfmt.a: adding index [-Wemcc]
error: undefined symbol: _ZN3fmt2v86detail12format_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE (referenced by top-level compiled C/C++ code)
warning: Link with `-sLLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: __ZN3fmt2v86detail12format_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail12format_floatIeEEiT_iNS1_11float_specsERNS1_6bufferIcEE (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail12format_floatIeEEiT_iNS1_11float_specsERNS1_6bufferIcEE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail13error_handler8on_errorEPKc (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail13error_handler8on_errorEPKc may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail14snprintf_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail14snprintf_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail14snprintf_floatIeEEiT_iNS1_11float_specsERNS1_6bufferIcEE (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail14snprintf_floatIeEEiT_iNS1_11float_specsERNS1_6bufferIcEE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail18decimal_point_implIcEET_NS1_10locale_refE (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail18decimal_point_implIcEET_NS1_10locale_refE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail18thousands_sep_implIcEENS1_20thousands_sep_resultIT_EENS1_10locale_refE (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail18thousands_sep_implIcEENS1_20thousands_sep_resultIT_EENS1_10locale_refE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail18throw_format_errorEPKc (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail18throw_format_errorEPKc may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail9dragonbox10to_decimalIdEENS2_10decimal_fpIT_EES5_ (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail9dragonbox10to_decimalIdEENS2_10decimal_fpIT_EES5_ may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v86detail9dragonbox10to_decimalIfEENS2_10decimal_fpIT_EES5_ (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v86detail9dragonbox10to_decimalIfEENS2_10decimal_fpIT_EES5_ may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN3fmt2v87vformatENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE (referenced by top-level compiled C/C++ code)
warning: __ZN3fmt2v87vformatENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

By modifying the `fmt` recipe to build in verbose mode ( `self.run("VERBOSE=1 cmake --build .")` ) I could see that indeed : it is the `/usr/bin/ar` which is being used, instead of the `emar` from emsdk ( /Users/myUser/.conan/data/emsdk/2.0.16/jenkins-clt/stable/package/cf186363a0bf37e3a91ee26c25ea5d664ac71fa5/bin/upstream/emscripten/emar ) .

Reason of this : 
Now there are 2 CMake helpers available :
1.: https://docs.conan.io/en/latest/reference/build_helpers/cmake.html
2.: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake.html
This second one is the newer one. **This newer one doesn't pick up the `AR` variable.**

Could you please fix this issue?

**Comment by jcar87** [comment]
Hi @szigetics  - thank you for reporting this issue.

From what I can see, while the `emsdk` recipe defines the `AR` variable in the build environment: https://github.com/conan-io/conan-center-index/blob/master/recipes/emsdk/all/conanfile.py#L164

My understanding is that CMake itself does *not* pay attention to the `AR` environment variable if it is defined, and I dont think it ever has: https://gitlab.kitware.com/cmake/cmake/-/issues/18277#note_447059

For CMake, I believe this would have to be defined as the `CMAKE_AR` variable,  although I cannot find in the CMake documentation what the recommended way is to override it. I'm assuming this would have to go in a toolchain file, and indeed the `emsdk` recipe does set a setting for the `CMakeToolchain` generator to load a custom toolchain that is part of `emsdk`:
https://github.com/conan-io/conan-center-index/blob/master/recipes/emsdk/all/conanfile.py#L155

That file includes these lines:
```
if ("${CMAKE_AR}" STREQUAL "")
  set(CMAKE_AR "${EMSCRIPTEN_ROOT_PATH}/emar${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ar")
endif()
```

So I suspect that either:
1) This file is not being loaded by the Conan generated `conan_toolchain.cmake`
or
2) `CMAKE_AR` is already defined by the time it reaches those lines, and does not enter the conditional.

Would you be able to confirm if either of these scenarios is happening? thanks!

**Comment by SpaceIm** [comment]
Works fine for me: https://github.com/conan-io/conan-center-index/issues/13292#issuecomment-1266914791

**Comment by szigetics** [comment]
> Hi @szigetics - thank you for reporting this issue.
> 
> From what I can see, while the `emsdk` recipe defines the `AR` variable in the build environment: https://github.com/conan-io/conan-center-index/blob/master/recipes/emsdk/all/conanfile.py#L164
> 
> My understanding is that CMake itself does _not_ pay attention to the `AR` environment variable if it is defined, and I dont think it ever has: https://gitlab.kitware.com/cmake/cmake/-/issues/18277#note_447059
> 
> For CMake, I believe this would have to be defined as the `CMAKE_AR` variable, although I cannot find in the CMake documentation what the recommended way is to override it. I'm assuming this would have to go in a toolchain file, and indeed the `emsdk` recipe does set a setting for the `CMakeToolchain` generator to load a custom toolchain that is part of `emsdk`: https://github.com/conan-io/conan-center-index/blob/master/recipes/emsdk/all/conanfile.py#L155
> 
> That file includes these lines:
> 
> ```
> if ("${CMAKE_AR}" STREQUAL "")
>   set(CMAKE_AR "${EMSCRIPTEN_ROOT_PATH}/emar${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ar")
> endif()
> ```
> 
> So I suspect that either:
> 
> 1. This file is not being loaded by the Conan generated `conan_toolchain.cmake`
>    or
> 2. `CMAKE_AR` is already defined by the time it reaches those lines, and does not enter the conditional.
> 
> Would you be able to confirm if either of these scenarios is happening? thanks!

I tested this, and I confirm that #2 is happening.

More details : 
Here is how I tested it : 
I modified the .conan/data/emsdk/3.1.14/jenkins-clt/stable/package/cf186363a0bf37e3a91ee26c25ea5d664ac71fa5/bin/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake file : 
I wrapped the section with some log entries : 
```
message("1 !!! CMAKE_AR} : ${CMAKE_AR}")
if ("${CMAKE_AR}" STREQUAL "")
  set(CMAKE_AR "${EMSCRIPTEN_ROOT_PATH}/emar${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ar")
endif()
message("2 !!! CMAKE_AR} : ${CMAKE_AR}")
```
and I triggered a new build using the unmodified conan recipe of `fmt` : 
```
conan create recipes/fmt/all fmt/8.1.1@jenkins-clt/stable --build=missing -s arch=wasm -s build_type=Release --profile:build=default -s:b arch=x86_64 -s:b compiler.version=13.1 -s:h arch=wasm -s:h os=Emscripten -s:h compiler=clang -s:h compiler.version=15 -s:h compiler.libcxx=libc++ --profile:host=wasm --build="fmt*"
```
and I got this (printed multiple times with the same values) : 
```
1 !!! CMAKE_AR : /usr/bin/ar
2 !!! CMAKE_AR : /usr/bin/ar
```

At least the environment variable has the correct value : 
```
message("!!! ENV_AR : $ENV{AR}")
```
=>
```
!!! ENV_AR : /Users/myUser/.conan/data/emsdk/3.1.14/jenkins-clt/stable/package/cf186363a0bf37e3a91ee26c25ea5d664ac71fa5/bin/upstream/emscripten/emar
```

Maybe the `emsdk` conan recipe should patch the `upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake` (toolchain file) like the following? 
From
```
# Specify the compilers to use for C and C++
if ("${CMAKE_C_COMPILER}" STREQUAL "")
  set(CMAKE_C_COMPILER "${EMSCRIPTEN_ROOT_PATH}/emcc${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten emcc")
endif()
if ("${CMAKE_CXX_COMPILER}" STREQUAL "")
  set(CMAKE_CXX_COMPILER "${EMSCRIPTEN_ROOT_PATH}/em++${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten em++")
endif()

if ("${CMAKE_AR}" STREQUAL "")
  set(CMAKE_AR "${EMSCRIPTEN_ROOT_PATH}/emar${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ar")
endif()

if ("${CMAKE_RANLIB}" STREQUAL "")
  set(CMAKE_RANLIB "${EMSCRIPTEN_ROOT_PATH}/emranlib${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ranlib")
endif()

if ("${CMAKE_C_COMPILER_AR}" STREQUAL "")
  set(CMAKE_C_COMPILER_AR "${CMAKE_AR}" CACHE FILEPATH "Emscripten ar")
endif()
if ("${CMAKE_CXX_COMPILER_AR}" STREQUAL "")
  set(CMAKE_CXX_COMPILER_AR "${CMAKE_AR}" CACHE FILEPATH "Emscripten ar")
endif()
if ("${CMAKE_C_COMPILER_RANLIB}" STREQUAL "")
  set(CMAKE_C_COMPILER_RANLIB "${CMAKE_RANLIB}" CACHE FILEPATH "Emscripten ranlib")
endif()
if ("${CMAKE_CXX_COMPILER_RANLIB}" STREQUAL "")
  set(CMAKE_CXX_COMPILER_RANLIB "${CMAKE_RANLIB}" CACHE FILEPATH "Emscripten ranlib")
endif()
```
to 
```
# Specify the compilers to use for C and C++
if ("${CMAKE_C_COMPILER}" STREQUAL "" OR (NOT "${CMAKE_C_COMPILER}" STREQUAL "$ENV{CC}"))
  set(CMAKE_C_COMPILER "${EMSCRIPTEN_ROOT_PATH}/emcc${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten emcc" FORCE)
endif()
if ("${CMAKE_CXX_COMPILER}" STREQUAL "" OR (NOT "${CMAKE_CXX_COMPILER}" STREQUAL "$ENV{CXX}"))
  set(CMAKE_CXX_COMPILER "${EMSCRIPTEN_ROOT_PATH}/em++${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten em++" FORCE)
endif()

if ("${CMAKE_AR}" STREQUAL "" OR (NOT "${CMAKE_AR}" STREQUAL "$ENV{AR}"))
  set(CMAKE_AR "${EMSCRIPTEN_ROOT_PATH}/emar${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ar" FORCE)
endif()

if ("${CMAKE_RANLIB}" STREQUAL "" OR (NOT "${CMAKE_RANLIB}" STREQUAL "$ENV{RANLIB}"))
  set(CMAKE_RANLIB "${EMSCRIPTEN_ROOT_PATH}/emranlib${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ranlib" FORCE)
endif()

if ("${CMAKE_C_COMPILER_AR}" STREQUAL "" OR (NOT "${CMAKE_C_COMPILER_AR}" STREQUAL "$ENV{AR}"))
  set(CMAKE_C_COMPILER_AR "${CMAKE_AR}" CACHE FILEPATH "Emscripten ar" FORCE)
endif()
if ("${CMAKE_CXX_COMPILER_AR}" STREQUAL "" OR (NOT "${CMAKE_CXX_COMPILER_AR}" STREQUAL "$ENV{AR}"))
  set(CMAKE_CXX_COMPILER_AR "${CMAKE_AR}" CACHE FILEPATH "Emscripten ar" FORCE)
endif()
if ("${CMAKE_C_COMPILER_RANLIB}" STREQUAL "" OR (NOT "${CMAKE_C_COMPILER_RANLIB}" STREQUAL "$ENV{RANLIB}"))
  set(CMAKE_C_COMPILER_RANLIB "${CMAKE_RANLIB}" CACHE FILEPATH "Emscripten ranlib" FORCE)
endif()
if ("${CMAKE_CXX_COMPILER_RANLIB}" STREQUAL "" OR (NOT "${CMAKE_CXX_COMPILER_RANLIB}" STREQUAL "$ENV{RANLIB}"))
  set(CMAKE_CXX_COMPILER_RANLIB "${CMAKE_RANLIB}" CACHE FILEPATH "Emscripten ranlib" FORCE)
endif()
```

Using this update, I have a passing build.

**Comment by szigetics** [comment]
FYI : 
https://github.com/emscripten-core/emscripten/issues/17992#issuecomment-1268656848
=>
https://github.com/emscripten-core/emscripten/pull/17997

So in newer `emsdk` versions this will probably be fixed.
( Of course previous `emsdk` versions will still have to be fixed using the same solution. )

**Comment by jcar87** [comment]
Hi @szigetics  - thanks for chasing this upstream with `emscripten-core`, looks like you've identified a good improvement to the CMake toolchain.

It may still be worthwhile verifying how `CMAKE_AR` had a value before it reached there - I'm assuming if this went unnoticed for so long, not everybody is experiencing this issue.

A way of doing this could be to add a `variable_watch` in a CMakeLists.txt that is being configured with the conan-generated toolchain - note it would need to be placed before `project()` or `enable_language()` . 

For example:
```
cmake_minimum_required(VERSION 3.15)

macro(print_variable_watch VAR ACCESS VALUE LISTFILE STACK)
    message("${VAR} ---------------------------------------------")
    message("${VAR} access: ${ACCESS}")
    message("${VAR} value: ${VALUE}")
    message("${VAR} access in ${LISTFILE}")
    message("${VAR} access stack in ${STACK}")
    message("${VAR} ----------------------------------------------")
endmacro()

variable_watch(CMAKE_AR print_variable_watch)


project(MyProject LANGUAGES C CXX)
```

This should print all internal script files CMake is using to locate and set `CMAKE_AR`.

**Comment by jcar87** [comment]
I'm closing this issue as it seems like CMake does not pick up the `AR` environment variable (so there's nothing we can do), and it looks like the `user_toolchain` conf is being propagated correctly and there may be an issue with the upstream toolchain itself. 

Please feel free to reopen this issue if there's anything related to it that we can help with! Thanks for helping us make the Conan and ConanCenter experience better :)
