### ISSUE TITLE
[question] How to set package_manager:mode

### ISSUE THREAD

**Issue by steffenroeber** [conan-io/conan#12240]
I'm trying to install xorg/system like:
conan install xorg/system@

There I get an error like
`xorg/system: ERROR: while executing system_requirements(): System requirements: 'libx11-dev, libx11-xcb-dev, libxaw7-dev, libxcomposite-dev, libxcursor-dev, libxdamage-dev, libxext-dev, libxfixes-dev, libxi-dev, libxinerama-dev, libxkbfile-dev, libxmu-dev, libxmuu-dev, libxpm-dev, libxrandr-dev, libxrender-dev, libxres-dev, libxss-dev, libxt-dev, libxtst-dev, libxv-dev, libxvmc-dev, libxxf86vm-dev' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'
ERROR: Error in system requirements
`
if a append -c, all is fine. Also adding it to a profile works as expected. What I don't get is to make it working with conan.conf or globals .conf file.
I added 
`[tools]
system.package_manager:mode = install
system.package_manager:sudo = True
`
to conan.conf file, but then even `conan get tools.system.package_manager:mode` shows an error. So, is there any way to set these values in a .conf files?

**Comment by czoido** [comment]
Hi @steffenroeber,

I think the error is related to adding the `[tools]` section to the _global.conf_ file. That file does not need sections. Could you try to add just the plain configurations without `[tools]` to the file and check if that works? Hope this helps. I think we should probably document this better as it can be a source of confusion.

**Comment by steffenroeber** [comment]
The [tools] sections was auto added by conan config set command
If I remove it completely from conan.conf and have it only in globals.conf. then
conan config get tools.system.package_manager
shows
ERROR: 'tools' is not a section of conan.conf
and conan install shows same error as before. It looks like as if globals.conf is not uses by conan get or conan install command at all.

**Comment by steffenroeber** [comment]
globals.conf file looks like:
```
tools.system.package_manager:mode = install
tools.system.package_manager:sudo = True

```

**Comment by czoido** [comment]
Hi @steffenroeber,

`conan config get/set` does not work with the _global.conf_ file, it must be edited or viewed with external tools. Thinking in 2.0 we don't provide commands that do just plain text editing or to get values from files, si it's normal that you get that error with `conan config get tools.system.package_manager`, for the conan install error, could it be that the `[tools] `section is still there in the _conan.conf_ file?

For me having a _global.conf_ file in _~/.conan/global.conf_ with this content:

```
conan@ad331c3fdacb:~$ cat ~/.conan/global.conf
tools.system.package_manager:mode = install
tools.system.package_manager:sudo = True
```

is working as expected.

**Comment by steffenroeber** [comment]
Yes, I only have this global.conf entries.
But 
conan install xorg/system@
shows the error anyway.
I use 1.52.0

**Comment by czoido** [comment]
Hi @steffenroeber,

Could you please provide the output for `conan install xorg/system@ -r conancenter` and also the contents of your `~/.conan/global.conf` and `~/.conan/conan.conf` files?
Thanks!

**Comment by steffenroeber** [comment]
```
ubuntu@ubuntu2004:~$ conan install xorg/system@ -r conancenter
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: xorg/system
Requirements
    xorg/system from 'conancenter' - Cache
Packages
    xorg/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
dpkg-query: no packages found matching libx11-dev
dpkg-query: no packages found matching libx11-xcb-dev
dpkg-query: no packages found matching libxaw7-dev
dpkg-query: no packages found matching libxcomposite-dev
dpkg-query: no packages found matching libxcursor-dev
dpkg-query: no packages found matching libxdamage-dev
dpkg-query: no packages found matching libxext-dev
dpkg-query: no packages found matching libxfixes-dev
dpkg-query: no packages found matching libxi-dev
dpkg-query: no packages found matching libxinerama-dev
dpkg-query: no packages found matching libxkbfile-dev
dpkg-query: no packages found matching libxmu-dev
dpkg-query: no packages found matching libxmuu-dev
dpkg-query: no packages found matching libxpm-dev
dpkg-query: no packages found matching libxrandr-dev
dpkg-query: no packages found matching libxrender-dev
dpkg-query: no packages found matching libxres-dev
dpkg-query: no packages found matching libxss-dev
dpkg-query: no packages found matching libxt-dev
dpkg-query: no packages found matching libxtst-dev
dpkg-query: no packages found matching libxv-dev
dpkg-query: no packages found matching libxvmc-dev
dpkg-query: no packages found matching libxxf86vm-dev
xorg/system: ERROR: while executing system_requirements(): System requirements: 'libx11-dev, libx11-xcb-dev, libxaw7-dev, libxcomposite-dev, libxcursor-dev, libxdamage-dev, libxext-dev, libxfixes-dev, libxi-dev, libxinerama-dev, libxkbfile-dev, libxmu-dev, libxmuu-dev, libxpm-dev, libxrandr-dev, libxrender-dev, libxres-dev, libxss-dev, libxt-dev, libxtst-dev, libxv-dev, libxvmc-dev, libxxf86vm-dev' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'
ERROR: Error in system requirements
ubuntu@ubuntu2004:~$ 
```
```
cat ~/.conan/conan.conf
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = critical            # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
default_profile = default
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO
request_timeout = 60                  # environment CONAN_REQUEST_TIMEOUT (seconds)
default_package_id_mode = semver_direct_mode # environment CONAN_DEFAULT_PACKAGE_ID_MODE

[storage]
path = ./data

[proxies]

[hooks]
attribute_checker
```


```
conan --version
Conan version 1.52.0
```

**Comment by steffenroeber** [comment]
```
cat ~/.conan/globals.conf 
tools.system.package_manager:mode = install
tools.system.package_manager:sudo = True

```

**Comment by czoido** [comment]
Hi @steffenroeber,

Please, check the name of the file, it's `global.conf` not `globals.conf`

**Comment by steffenroeber** [comment]
Damn...Thank you. With this renaming it works.

**Comment by czoido** [comment]
Great! I'm glad it worked. Closing this as it seems solved.
