### ISSUE TITLE
[feature] conan 2.0 - Git::get_commit unexpected behavior

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#12242]
I am using the documented replacement for `scm` mode.  My recipe includes:
```
def export(self):
        git = Git(self, self.recipe_folder)
        scm_url, scm_commit = git.get_url_and_commit()
        update_conandata(self,  {"sources": {"commit": scm_commit, "url": scm_url}})

    def source(self):
       git = Git(self)
       sources = self.conan_data["sources"]
       url = sources["url"]
       git.clone(url=url, target=".")
       git.checkout(commit=sources["commit"])
```
My project structure has a top level "all" folder with the conanfile.py in it.  I also have a src folder with the code in it.  I change the code in the src and commit.  I then attempt to run `conan create all`.  This clones an old version of the repo - not the recently commited code.  Upon inspection, the `Git` object is using `self.recipe_folder` as the root when searching for commits rather than the root folder of the repo.  I'm not sure if this is intentional or not.

Looking at the source, I can change the export function to:
```
def export(self):
        git = Git(self, self.recipe_folder)
        git.folder = git.get_repo_root()
        scm_url, scm_commit = git.get_url_and_commit()
        update_conandata(self,  {"sources": {"commit": scm_commit, "url": scm_url}})
```
It's a little odd to need this extra step.  It does not appear to me that I have access to any useful folders in the export function other than the `recipe_folder`.  It would be nice to have a way to specify that I want to use the repo root in the Git constructor.  I plan to change my code far more often than the recipe.  I would guess that this would trip up many users.
- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jsallay 

I think you need to define the ``self.folders.root`` in the ``layout()`` method, if the ``conanfile.py`` is not in the root of the project, maybe this doc: https://docs.conan.io/en/latest/developing_packages/package_layout.html#example-conanfile-in-subfolder, and also this test could help: https://github.com/conan-io/conan/blob/54f1221bad7beb54f45521c36217448442cb5a7e/conans/test/functional/tools/scm/test_git.py#L363

**Comment by jsallay** [comment]
I see.  Thanks.  Though I do think that using the repo root is the behavior that a typical user would want.  It would be nice if it were the default for the Git object.  I.e.

```
class Git(object):
    def __init__(self, conanfile, folder=None):
        self._conanfile = conanfile
        if folder is None:
            self.folder = conanfile.recipe_folder
            self.folder = self.get_repo_root()
        else:
            self.folder = folder
```
    
If not this then I think it would be useful to define `get_repo_root` outside the class or as a `classmethod`.  That way I could write my code as:

```
from conan.tools.scm import Git, get_repo_root
...
    def export(self):
        git = Git(self, get_repo_root(self))
        ...
```

**Comment by memsharded** [comment]
> I see. Thanks. Though I do think that using the repo root is the behavior that a typical user would want. It would be nice if it were the default for the Git object. I.e.

We are not sure about this. For repos containing multiple projects, which is a very common thing, the important one is the current subfolder, and not the repo root. The most common use case by far is having the ``conanfile.py`` in the root, and only some users will put it in a subfolder. But many users have repos with multiple conan packages inside, so it seems the current default is the good one, and users that want another one should opt-in into that.

In any case, defining the ``self.folders.root`` is still necessary if need to escape the current folder to the parent one (and to siblings folder containing common code), irrespective of what the base folder is used for ``Git``

**Comment by jsallay** [comment]
You convinced me.  I'll go ahead and close this issue.
