### ISSUE TITLE
Change Conan 2.0 conan inspect syntax

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#12247]
Related with: https://github.com/conan-io/conan/pull/12235#discussion_r987589228

`conan inspect` has a subcommand path that I think we should reconsider. The motivation for adding this is having path subcommand as an approach to leave the possibility open for the future to inspect references in the cache and in remotes. You have to call:

```
conan inspect path conanfile.py 
```

instead of 

```
conan inspect conanfile.py
```

Maybe we should consider using a syntax more aligned with other commands, something like:

```
conan inspect conanfile.py
conan inspect --reference=zlib/1.2.11 --> goes to the local cache
```

I would leave the inspect on remote case for users to implement their own using custom commands or maybe:

```
conan inspect --reference=zlib/1.2.11 --cache --> goes to the local cache
conan inspect --reference=zlib/1.2.11 --remote=remote --> goes to the remote
```

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12263
