### ISSUE TITLE
[question] Making tool_requires affect the consumers package-ID - possible to avoid patching recipes?

### ISSUE THREAD

**Issue by szigetics** [conan-io/conan#12244]
WebAssembly (Emscripten, emsdk conan recipe) is quite sensitive even to non-major version changes.

My WebAssembly packages recently got broken by re-building them with a new emsdk version (I switched from 2.0.14 to 3.1.14).
I could fix my conan packages, by cleaning my conan server, and re-building every packages using the new emsdk version again.

I am almost sure that this was caused by the build_requires not affecting the consumer package id as described here : 
https://docs.conan.io/en/latest/devtools/build_requires.html#making-tool-requires-affect-the-consumers-package-id 

So I would like to make my 
```
[tool_requires]
emsdk/3.1.14@jenkins/stable
```
affect the consumer package id. 
As I see at the moment this would require patching all the conan recipes.

Would it be possible to achieve this **without** having to patch all the conan recipes that I am building? Is there a generic solution for this?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @szigetics 

It has been made possible in 2.0.
In Conan 1.X is not possible, if you want to see a detailed explanation why, you can see https://youtu.be/kKGglzm5ous?t=1804

The only workaround in 1.X is https://docs.conan.io/en/latest/devtools/build_requires.html#making-tool-requires-affect-the-consumers-package-id
