### ISSUE TITLE
[question] Is self.conf_info available at generate()?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#12257]
Hi,

  The question fits in the title: Is self.conf_info available at generate()?

We need it to use our custom provided configuration entries, but it seems `self.conf_info` is an empty `OrderedDict` at this point.

**Comment by memsharded** [comment]
``self.conf_info`` is information for consumers, and it is only to be defined in ``package_info()``, but never for reading it.

Consumers receive in its own ``self.conf`` the ``conf_info`` of its direct ``tool_requires`` dependencies only, but not from the rest.
Another mechanism to pass information to consumers, if it is information about the C++ artifacts, is the ``self.cpp_info.set_property()`` mechanism in ``package_info()``

**Comment by Adnn** [comment]
Thank you @memsharded , I think I am getting confused.

What we are trying to achieve is to read values from `conan.conf` file `[conf]` section. We wanted to use the conf entries to pass configurations that should not change the package id (such as "Warning as error" compilation flag).

**Comment by memsharded** [comment]
Yes, then you just want to read ``self.conf`` in your ``generate()``
The other case is more exceptional, because some ``tool_requires`` sometimes might want to define some conf to its consumer, but that is not the main case.

**Comment by Adnn** [comment]
Ha, thank you again! Most of the examples in the documentation were using `self.conf_info`, we misunderstood the intention.

Is there a global file, handle by `conan config install`, where we can set our `[conf]` entries? We tried with `conan.conf`, but it does not seem to work.

**Comment by memsharded** [comment]
``global.conf`` can be used for that.

**Comment by Adnn** [comment]
Is this file handled by `conan config install`? ([the documentation](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install) does not seems to mention it)

**Comment by memsharded** [comment]
Yes, everything in the folder used by ``conan config install`` should be installed in the cache and later used.

**Comment by Adnn** [comment]
I'll close this question, as I actually needed the functionality of `self.conf` object, which is available at `generate()`.
