### ISSUE TITLE
[question] Is the python API stable?

### ISSUE THREAD

**Issue by dev-joss** [conan-io/conan#12252]
I am wondering if the python API is stable and usable in production. I would like to write some automation and avoid having to interface with the conan command line tool. Using the Conan API class would be much better.

However I can't see any references to it in the documentation so I am unsure whether it is a public / stable API suitable for use.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @eclazi,

The Conan Python API is not stable or documented for 1.X, so we recommend not to use it, but it will be for Conan 2.0. You can check the reference for the Conan 2.0 API here: https://docs.conan.io/en/2.0/reference/python_api.html it's not fully documented yet, but we are working on it.

One of the most powerful Conan 2.0 features is the possibility to write your own custom commands using that API, you can check an example of how to do that here: https://docs.conan.io/en/2.0/examples/extensions/commands/clean/custom_command_clean_revisions.html

Hope that helps

**Comment by czoido** [comment]
I'm closing this, please feel free to reopen if you have any more questions
Thanks for the feedback!
