### ISSUE TITLE
[bug] Lock file has duplicate entries

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#12250]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: n/a
  * Conan version: 1.53
  * Python version: 3.10.1

### Steps to reproduce (Include if Applicable)

1. Extract the attached zip to a directory
2. cd to that directory
3. Enable conan revisions (it seems like an issue anyway, but this is how i'm running)
4. run `conan lock create conanfile_lock_duplicates.py --profile mac_m1_relwithdebinfo --update --lockfile-out my.lock --base --build`
5. inspect `my.lock`. There are multiple entries (same version and revision) which occur more than once (some up to 4 times) e.g. `automake`, `autoconf`, `m4`, `libtool`, `pkgconfig`, `gnu-config`

[conan_lock_duplicates_bug.zip](https://github.com/conan-io/conan/files/9718660/conan_lock_duplicates_bug.zip)

**Comment by memsharded** [comment]
This is expected.
In Conan 1.X the lockfile is a snapshot of the full dependency graph, every node in the graph.
``build_requires`` are private per consumer, each package using it will have its own instance of the ``build_require``, and that means a different node in the graph, and consequently a different entry in the lockfile.

Conan 2.0 lockfiles have greatly simplified lockfiles, I suggest giving them a try: https://docs.conan.io/en/2.0/tutorial/consuming_packages/intro_to_versioning.html#lockfiles

**Comment by rconde01** [comment]
Ok…guess I hadn’t noticed it before. I’m eager to transition to conan 2.0 when it’s released…but I can’t use v2 lock files until then right?

**Comment by memsharded** [comment]
> Ok…guess I hadn’t noticed it before. I’m eager to transition to conan 2.0 when it’s released…but I can’t use v2 lock files until then right?

No, you cant, they are very different to those in 1.X, not possible to backport at all.

In any case, the 1.X lockfiles with those duplicated entries shouldnt be an issue in general for 1.X per se.
