### ISSUE TITLE
[bug] 2nd level subdirectory of dir specified in [imports] in conanfile.txt is not copied to target dir.

### ISSUE THREAD

**Issue by deivse** [conan-io/conan#12256]
I'm using a simple `conanfile.txt` for installing dependencies, etc. I also copy the includes libs and licenses into my project folder, this is my `[imports]` section in the conan file:
```
[imports]
include,  * -> ../third-party/include
lib,      * -> ../third-party/lib
licenses, * -> ../third-party/licenses
```

One of the packages I depend on is `spdlog`. All the files from it's include folder are copied correctly, except one subfolder. 
In the spdlog package's source subfolder there is this folder: `src_subfolder/spdlog/include/spdlog/fmt/bundled`. All other files are copied correctly, howether this subfolder is not copied to my project's folder after calling `conan install $conanfile_dir -if $build_dir`. Here's a screenshot, as you can see, all files are there except the `bundled` dir: 
![Screenshot from 2022-10-06 14-11-07](https://user-images.githubusercontent.com/76527282/194309394-447cc59e-239a-415a-8a2c-e448644e1a58.png)

I'm not sure if that's a coincidence, but that's the only "2nd level" subdirectory in `src_subfolder/spdlog/include/spdlog/`.

### Environment Details
  * Ubuntu 22.04.1 LTS
  * Conan version: 1.53.0[conanfile.txt](https://github.com/conan-io/conan/files/9724664/conanfile.txt)
  * Python version: 3.10.6
  * Spdlog package version: spdlog/1.10.0

PS: sorry in advance if this is desired behavior and I'm just missing something.

I'm attaching my full conanfile.txt just in case: 
```
[requires]
nng/1.5.2
spdlog/1.10.0
fmt/8.1.1
openblas/0.3.17
fftw/3.3.9
glm/cci.20220420

[generators]
cmake
cmake_find_package
cmake_find_package_multi

[options]
fftw:precision=single
fftw:simd=avx2
openblas:build_lapack=True
spdlog:shared=False

[imports]
include,  * -> ../third-party/include
lib,      * -> ../third-party/lib
licenses, * -> ../third-party/licenses
```

**Comment by memsharded** [comment]
Hi @deivse 

The ``[imports]`` feature has been already removed in Conan 2.0, and there is already another approach available in Conan 1.X that can be used to implement something equivalent. It would be like:

- Convert the ``conanfile.txt`` to ``conanfile.py``
- Add a ``generate()`` method to it.
- In the ``generate()`` method iterate your dependencies with ``for d in self.dependencies.values()``, and you can call the (also new) ``copy(self, ....)`` method, to copy things as you want.

It could look something like this:
```python
def generate(self):
      for dep in self.dependencies.values():
          copy(self, "*", dep.package_folder, os.path.join(self.build_folder, dep.ref.name))
```

The solution is a bit more verbose, but it is also way more explicit, lets magic, and more control to do whatever you need.

**Comment by deivse** [comment]
Hey, @memsharded, thanks for the reply. I guess I will switch to using a `conanfile.py` instead, definitely agree on the "less magic" part. The behaviour of the `[imports]` feature still seems strange to me in this particular case, but if it's on it's way to deprecation, I very much understand how that wouldn't be a priority :)

**Comment by memsharded** [comment]
> Hey, @memsharded, thanks for the reply. I guess I will switch to using a conanfile.py instead, definitely agree on the "less magic" part. The behaviour of the [imports] feature still seems strange to me in this particular case, but if it's on it's way to deprecation, I very much understand how that wouldn't be a priority :)

Yes, definitely, we realized this when we had to look constantly ourselves to the docs and implementation to be able to write a ``[imports]`` section correctly in the ``conanfile.txt``. It is just too obscure and custom, and as it can already be replaced in 1.X by a more explicit solution, we prefer to focus our resources in other priorities, yes :)

**Comment by memsharded** [comment]
``imports`` have been deprecated in 1.X and removed in 2.0, please read https://docs.conan.io/1/migrating_to_2.0/recipes.html#removed-imports-method, closing this ticket as outdated
