### ISSUE TITLE
[feature] allow configuring user-toolchain for CMakeToolchain from profiles, not just from global.conf

### ISSUE THREAD

**Issue by insi-eb** [conan-io/conan#12268]
Currently, setting a user-toolchain for the new CMakeToolchain class is only possible from the global.conf, not from the profiles, which kind of defeats the cross-compiling use-case. For a reasonable cross-compiling use-case, I'd expect to be able to set user-toolchains also via the profiles, so the host profile selects automatically a known good platform configuration in the form of an existing toolchain file.
We currently have a profile for each targeted cross platform that defines a working CMake toolchain via CMAKE_TOOLCHAIN/CONAN_CMAKE_TOOLCHAIN_FILE environment variables, building for each platform until now just required us to select the right host profile for the platform and everything worked. All the platform-specifics were encapsulated nicely in the toolchain files.

With the recent changes on conan-center-index and this missing feature, we cannot build any recent conan-center recipes anymore.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Not sure what you mean. Both
```
conan config list
tools.cmake.cmaketoolchain:toolchain_file: Use other existing file rather than conan_toolchain.cmake one
tools.cmake.cmaketoolchain:user_toolchain:...
```
Can also be set in profiles.

**Comment by insi-eb** [comment]
ah - I've edited the wrong profile file when trying this out 🤦

the CMakeToolchain documentation indicates though, that this only really works in global.conf [here](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#using-a-custom-toolchain-file):
> The configuration tools.cmake.cmaketoolchain:user_toolchain=["<filepath>"] **can be defined in the [global.conf]**(https://docs.conan.io/en/latest/reference/config_files/global_conf.html#global-conf) but also creating a Conan package for your toolchain and using self.conf_info to declare the toolchain file:

**Comment by memsharded** [comment]
>  can be defined in the [global.conf]

Yes, the idea is that by default it would be defined in profiles, but in some cases it is also possible to be defined in global.conf too.

In any case, the Conan 2.0 docs are being written from scratch, I think it will be way more clear. Thanks!
