### ISSUE TITLE
[question] How to generate custom content for PkgConfigDeps that is compatible with pkg_config

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#12279]
When migrating from `pkg_config` to `PkgConfigDeps`, custom content frequently breaks because it uses the fairly standard variable `libdir` but `PkgConfigDeps` defines this as `libdir1`. Would it be possible to change the default name to `libdir` when there is only one library directory? This would solve the issue in all cases that I've seen on CCI so far.

CCI issue: conan-io/conan-center-index#12890

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jwillikers** [comment]
Update, looks like we probably need to use `libdir` and `includedir` even when using multiple of such directories for dependencies which still expect to find those variables.

**Comment by franramirez688** [comment]
Hi @jwillikers! Sorry, I just realized this one.

I have a question about this issue. Regardless of changing `libdir1` to `libdir` (the same for `includedir`), what about the cases that we're defining several `includedirN` and `libdirN`? Sorry for the basic question, but which is the use case to use that `libdir` and `includedir`?

**Comment by franramirez688** [comment]
Closing this issue as it was already solved by https://github.com/conan-io/conan/pull/13623

UPDATED: Released since Conan v2.0.8 (actually, it was since v2.0.7, but a bug appeared, and it was solved by the next one).

**Comment by jwillikers** [comment]
@franramirez688 Awesome, thank you!
