### ISSUE TITLE
[question] What causes a new Recipe Revision to be created?

### ISSUE THREAD

**Issue by dillydill123** [conan-io/conan#12270]
I have a recipe in which I'm building for multiple profiles. When building with two different profiles it's calculating a different recipe revision for each. After looking online and trying to understand the issue, I learned that the conanmanifest.txt file is what is used to calculate this recipe revision, which also depends on exports sources. However, my conanmanifest.txt for each profile is the same (besides the timestamp). So is there anything additional that is used to compute the recipe revision? I would expect conan to create the same recipe revision for each profile because the conanmanifest.txt file is the same.

I'm using conan 1.52

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dillydill123 

Yes, it should definitely be the same, as it is computing the ``recipe_revision`` from that conanmanifest.txt checksums. Are you sure it is identical? One of the common causes is endlines, which might be different in Linux and Windows.

Other things to be checked: 
- if ``revisions_enabled`` is configured
- Try to clean the cache between both operations, in case it is something getting dirty in the cache

**Comment by dillydill123** [comment]
Thank you for the reply @memsharded. I think I discovered the issue. In my project, there is another conan recipe which is called and imports some code before the main `conan create` call. This creates a conan_imports_manifest which is being included as part of the packaging of my main recipe. My idea is that the conan_imports_manifest has a different timestamp, which causes a different checksum, which causes the checksum of the conan manifest of the main recipe to have a different value (which I did not notice before). So I deleted the conan_imports_manifest and now it uses the same package revision.

**Comment by memsharded** [comment]
Thanks @dillydill123 for following up and reporting.

Indeed, if the ``exports`` is not restrictive enough (like ``exports = "*"), then if something changes locally, it will export a different thing, and end in a different revision.

Besides removing the ``conan_imports_manifests``, and possibly other temporary files, it is recommended to use a restrictive ``exports`` expression, explicitly adding what needs to be added and nothing more.
