### ISSUE TITLE
[bug] In some situations, Conan requires you to override a package when it is already overridden

### ISSUE THREAD

**Issue by Ahajha** [conan-io/conan#12274]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10, Ubuntu 22.04
  * Conan version: 1.52, 1.53, 2.0 beta3
  * Python version: 3.9 (Windows) 3.10 (Ubuntu)

### Steps to reproduce (Include if Applicable)

See here for a (hopefully) minimum reproducible example: https://github.com/Ahajha/build-vs-normal-reqs-conan
(There might be some simplification that can be done, but I reduced it a lot from how I originally found it)

Essentially, I have a very specific stacking of packages, which ends in some packages being present in both the build and host contexts. This results in the following error:

```
ERROR: Conflict in pkg2/1.0.0@build-req-repro/test:
    'pkg2/1.0.0@build-req-repro/test' requires 'pkg1/1.0.0@build-req-repro/test' while 'pkg3/1.0.0@build-req-repro/test' requires 'pkg1/1.1.0@build-req-repro/test'.
    To fix this conflict you need to override the package 'pkg1' in your root package.
```
This is unfortunately not helpful, since pkg1 is already specified in both `requirements()` and `build_requirements()`.

1. The intended behavior (for this case specifically) should certainly be that pkg1 1.1.0 is used.
2. Is it possible to make this work? In my situation, I can change any of the recipes.

Thanks in advance!

**Comment by prince-chrismc** [comment]
This sounds very close to the limitation in the 1.x graph resolve that it can not see the `requires` and `build_requires` at the same time so you need to define two different profiles to resolve the conflict.

Host profile could be

```
[requires]
pkg1/1.1.0@build-req-repro/test
```

and we will need a build profile as well

```
[build_requires]
pkg1/1.1.0@build-req-repro/test
```

***

I see you mentioned 2.0 beta in the description, but I have not played with that so I am not sure if that is the only option (but it should still work)

**Comment by Ahajha** [comment]
I believe this is no longer an issue in Conan v2 if you use `test_requires` in `requirements()`.
