### ISSUE TITLE
[bug] tools.can_run() doesn't work for cross-compiled recipes with test cases that simply execute a binary

### ISSUE THREAD

**Issue by jave27** [conan-io/conan#12281]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS+12.6, but compiling for `armv8`
  * Compiler+version: clang-14.0.0
  * Conan version: 1.53.0-dev
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)

1. Checkout conan-center-index
2. Apply the attached patch to convert `yasm`'s recipe to use `can_run` instead of `conans.tools.cross_building`.
3. `cd recipes/yasm/all`
4. `conan create . yasm/1.3.0@ -s build_type=Release -s arch=armv8`

### Notes ###

This actually appears to be a regression from `conans.tools.cross_building` to `conan.tools.cross_building`. These two functions return different values in `recipes/yasm/all/test_package/conanfile.py`.
```
from conan.tools.build import cross_building
from conans import tools

class TestPackageConan(ConanFile):
    settings = "os", "arch", "compiler", "build_type"

    def test(self):
        print(tools.cross_building(self, skip_x64_x86=True))
        print(cross_building(self, skip_x64_x86=True))
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

Trimmed log down to fit.

**Comment by jave27** [comment]
Looks like my log got eaten. Here's the relevant bit:
```
yasm/1.3.0 package(): Packaged 4 files: yasm, vsyasm, ytasm, COPYING
yasm/1.3.0 package(): Packaged 1 '.txt' file: BSD.txt
yasm/1.3.0 package(): Packaged 29 '.h' files
yasm/1.3.0 package(): Packaged 1 '.a' file: libyasm.a
yasm/1.3.0: Package '3eb32b976fb0626f3c40a8b87ace72156aa44204' created
yasm/1.3.0: Created package revision 7fc08e0a0d331374a78b23b54cc6ee23
yasm/1.3.0: Appending PATH environment variable: /Users/jason/.conan/data/yasm/1.3.0/_/_/package/3eb32b976fb0626f3c40a8b87ace72156aa44204/bin
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
[HOOK - conan-center.py] post_package_info(): [LIBRARY DOES NOT EXIST (KB-H054)] OK
[HOOK - conan-center.py] post_package_info(): [INCLUDE PATH DOES NOT EXIST (KB-H071)] OK
yasm/1.3.0 (test package): Generator txt created conanbuildinfo.txt
yasm/1.3.0 (test package): Aggregating env generators
yasm/1.3.0 (test package): Generated conaninfo.txt
yasm/1.3.0 (test package): Generated graphinfo
Using lockfile: '/Users/jason/src/conan/conan-center-index/recipes/yasm/all/test_package/build/4bb60c1818929a4ea9521e4c011053e4a1eb6a38/conan.lock'
Using cached profile from lockfile
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
yasm/1.3.0 (test package): Calling build()
yasm/1.3.0 (test package): WARN: This conanfile has no build step
yasm/1.3.0 (test package): Running test()
/bin/sh: /Users/jason/.conan/data/yasm/1.3.0/_/_/package/3eb32b976fb0626f3c40a8b87ace72156aa44204/bin/yasm: Bad CPU type in executable
ERROR: yasm/1.3.0 (test package): Error in test() method, line 10
	self.run("yasm --help", run_environment=True)
	ConanException: Error 126 while executing DYLD_LIBRARY_PATH="/Users/jason/.conan/data/yasm/1.3.0/_/_/package/3eb32b976fb0626f3c40a8b87ace72156aa44204/lib" DYLD_FRAMEWORK_PATH="" yasm --help
```
[can_run.diff.txt](https://github.com/conan-io/conan/files/9748196/can_run.diff.txt)

**Comment by memsharded** [comment]
Hi @jave27 

All the new tools and every thing new related with cross-compiling (like ``from conan.tools.build import cross_building``) needs to use the 2 profiles approach. You can read a clean summary in 2.0 docs: https://docs.conan.io/en/2.0/tutorial/consuming_packages/cross_building_with_conan.html, but it is already working and should be applied in Conan 1.X. Just make sure to specify the "build" profile too:
```bash
$ conan create .....  -pr:b=default -s build_type=Release -s arch=armv8
```
By default ``-s`` is equivalent to ``-s:h`` and applies to "host" context, like ``-pr=xxx`` is equivalent to ``-pr:h=xxx``

**Comment by jave27** [comment]
Got it, thank you. That works here. This ticket can be closed then.
