### ISSUE TITLE
Conan `remove` left several Gb in X:\.conan\ folder

### ISSUE THREAD

**Issue by KindDragon** [conan-io/conan#1229]
Command `conan remove * -f` left several Gb in X:\\.conan\ folder

**Comment by memsharded** [comment]
I have checked, that indeed I also had some garbage in my "short_paths" location in Windows, despite I had cleaned my cache with ``conan remove "*"``.

I have tried to reproduce with tests. I have tried to reproduce manually (using boost, that was one of the offending packages in my short_paths home). I have reviewed the code, and check for inconsistencies. So far, no success, this is really annoying. I don't know what else to try, but I'll keep checking. 
I have thought about forcing a complete removal, but it is not possible, as long as users can command ``conan remove "*" -b -f``, to remove, for example, just the build folders. We could add an ugly hack, but I'd certainly prefer to know why is this happening, maybe it is a consequence of a subtle bug that might affect elsewhere.

**Comment by memsharded** [comment]
Hi @KindDragon 
Still unable to figure out. Also, I removed my folder after the firsts check, and now, I cannot do further checks. So, if you haven't removed yours, I would love to know a bit more:
- Which kind of folders are they. Are they source, build or package folders? 
- From which packages? Your own? Some packages from conan.io?

If you have removed your folder, please, next time you detect this, check it and tell me. I will also keep an eye on this.

**Comment by memsharded** [comment]
Moving it forward to 0.24, it is not critical, and we would need more time to gather information and try to reproduce. If possible will bring it back, but 0.23 is already packed.

**Comment by KindDragon** [comment]
Ok

**Comment by memsharded** [comment]
I have fixed one possible "leak" in https://github.com/conan-io/conan/pull/1513/files#diff-e03758f339e32f517ce59fbf982bbb74R37

However, I have not been able to identify other sources. Will move this forward, and see how it goes.

**Comment by memsharded** [comment]
Still unable to identify the leak. I have been checking my shorts-paths folder since then, but no leak so-far.
I will keep the issue open to stay vigilant, but won't assign a milestone(release) until getting some more data or way to reproduce.

**Comment by lasote** [comment]
I was playing too with Boost/short paths in Windows and everything was clean.

**Comment by danimtb** [comment]
Closing this as solved as last action was not able to reproduce the "remove leak" after the fix. Thanks!
