### ISSUE TITLE
[bug] link error when using spdlog/1.10.0

### ISSUE THREAD

**Issue by yushb0602** [conan-io/conan#12299]
### Environment Details (include every applicable attribute)
  * Ubuntu 22.04.1 LTS
  * gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  *  1.53.0
  * Python 3.10.6 
  
When I simply use spdlog library
```
[requires]
spdlog/1.10.0
nlohmann_json/3.11.2
[generators]
#cmake_find_package
cmake
[options]
```
And run `conan install ../cppsrc --build=missing' successfully.

But I meet the following  link error when simply use `  spdlog::info("Welcome to spdlog! {}", 22);`
I have tried the same version https://github.com/gabime/spdlog  called original version, it works
After I replace the ~/.conan/data/spdlog/1.10.0/_/_/package/1c95f3b798496bf6c8742af389f9a13ba08ce98a/lib/libspdlog.a with above original version.  It works.
I notice these two libspdlog.a are different size.

the logs:

fmt/8.1.1: Already installed!
spdlog/1.10.0: Already installed!
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generator cmake_find_package created Findspdlog.cmake
conanfile.txt: Generator cmake_find_package created Findnlohmann_json.cmake
conanfile.txt: Generator cmake_find_package created Findfmt.cmake
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
*****CMAKE_FIND_ROOT_PATH is /usr
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /opt/OGic-2/build
-- Conan: Compiler GCC>=5, checking major version 11
-- Conan: Checking correct version: 11
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/OGic-2/build
cp: cannot stat 'bin/ogic': No such file or directory
[ 50%] Building CXX object CMakeFiles/test.dir/testcases/testjson.cpp.obj
[100%] Linking CXX executable bin/test
/usr/bin/ld: CMakeFiles/test.dir/testcases/testjson.cpp.obj: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<char const*, char const*&, int&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<char const*&>::type, fmt::v8::type_identity<int&>::type>, char const*&&, char const*&, int&)':
/home/shuibao/.conan/data/fmt/8.1.1/_/_/package/3bb43d390932310d9ef00e9986e41f02509d79e8/include/fmt/core.h:3119: undefined reference to `fmt::v8::vformat[abi:cxx11](fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
/usr/bin/ld: CMakeFiles/test.dir/testcases/testjson.cpp.obj: in function `void spdlog::logger::log_<int>(spdlog::source_loc, spdlog::level::level_enum, fmt::v8::basic_string_view<char>, int&&)':
/home/shuibao/.conan/data/spdlog/1.10.0/_/_/package/1c95f3b798496bf6c8742af389f9a13ba08ce98a/include/spdlog/logger.h:375: undefined reference to `spdlog::logger::err_handler_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/shuibao/.conan/data/spdlog/1.10.0/_/_/package/1c95f3b798496bf6c8742af389f9a13ba08ce98a/include/spdlog/logger.h:375: undefined reference to `spdlog::logger::err_handler_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/shuibao/.conan/data/spdlog/1.10.0/_/_/package/1c95f3b798496bf6c8742af389f9a13ba08ce98a/include/spdlog/logger.h:375: undefined reference to `spdlog::logger::err_handler_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by memsharded** [comment]
Hi @yushb0602 

It seems that there could be an error in your configuration, and you are using ``compiler.libcxx=libstdc++``, but you are actually using in your compiler ``libstdc++11``.

please check: https://docs.conan.io/en/latest/getting_started.html, the *important* note:

> If you are using GCC compiler >= 5.1, Conan will set the compiler.libcxx to the old ABI for backwards compatibility. In the context of this getting started example, this is a bad choice though: Recent gcc versions will compile the example by default with the new ABI and linking will fail without further customization of your cmake configuration. You can avoid this with the following commands:

> $ conan profile new default --detect  # Generates default profile detecting GCC and sets old ABI
> $ conan profile update settings.compiler.libcxx=libstdc++11 default  # Sets libcxx to C++11 ABI
You will find more information in [How to manage the GCC >= 5 ABI](https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html#manage-gcc-abi).


Also, the ``cmake`` generator is already legacy, you want to read https://docs.conan.io/en/latest/conan_v2.html, to start using modern tools, like ``CMakeDeps`` and ``CMakeToolchain`` instead of ``cmake``, to be 2.0-ready because it is happening soon.

**Comment by yushb0602** [comment]
Yes. It works.   I'll try conan_v2

**Comment by memsharded** [comment]
> Yes. It works. I'll try conan_v2

No need to move to 2.0 now, it is still in beta. But we have backported all the necessary things to allow an easy upgrade, to 1.X. You have ``CMakeDeps``, ``CMakeToolchain`` and other tools in latest 1.X already.
