### ISSUE TITLE
[bug] Default cppstd not working due to non-existent `_cppstd_default`

### ISSUE THREAD

**Issue by mzukovec** [conan-io/conan#12298]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2022
  * Conan version: 1.53.0
  * Python version: 3.8

### Description
Conan v1.53.0 default cppstd is not working. It returns `None` due to the call of the non-existent `_cppstd_default` method.

See the [definition](https://github.com/conan-io/conan/blob/1.53.0/conan/tools/build/cppstd.py#L63):
```python
def default_cppstd(conanfile, compiler=None, compiler_version=None):
    """
    Get the default ``compiler.cppstd`` for the "conanfile.settings.compiler" and "conanfile
    settings.compiler_version" or for the parameters "compiler" and "compiler_version" if specified.
    :param conanfile: The current recipe object. Always use ``self``.
    :param compiler: Name of the compiler e.g. gcc
    :param compiler_version: Version of the compiler e.g. 12
    :return: The default ``compiler.cppstd`` for the specified compiler
    """
    from conans.client.conf.detect import _cppstd_default
    compiler = compiler or conanfile.settings.get_safe("compiler")
    compiler_version = compiler_version or conanfile.settings.get_safe("compiler.version")
    if not compiler or not compiler_version:
        raise ConanException("Called default_cppstd with no compiler or no compiler.version")
    return _cppstd_default(compiler, Version(compiler_version))
```

Method `_cppstd_default` does not exist anywhere, therefore `None` is always returned.

**Comment by mzukovec** [comment]
After re-checking, this seems to be dead code, since it's not really used anywhere. Is this some future feature?

Please let me know if this issue should be closed.

**Comment by memsharded** [comment]
No, please don't close it, the idea is that this function was there as part of the upgrade of tools, but you are right this code is not even tested, so we should have a look.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/12446, will be in 1.54 soon
