### ISSUE TITLE
[bug] min version check fails when it should not

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#12305]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: N/A
  * Conan version: 1.53.0
  * Python version: 3.10.7

### Steps to reproduce (Include if Applicable)
Have a conanfile.py which contains `required_conan_version = '>= 1.50'` after the import statements.

Attempt to run it using 1.53.0 and it prints 
Current Conan version (1.53.0) does not satisfy the defined one ('>= 1.50').

**Comment by memsharded** [comment]
I am trying, but this seems to work correctly here (it is also checked in the test suite), not sure what could be failing in your side.

It is weird that in your case it is quoting the `` ('>= 1.50').``, because in my output it doesn't look like that, but:
```
Current Conan version (1.53.0) does not satisfy the defined one (>= 1.54).
```
(I had to use 1.54, otherwise it works)

**Comment by Sil3ntStorm** [comment]
nevermind. This appears to be an issue in the conan install from chocolatey. Installing conan using pip and it works as expected.

**Comment by memsharded** [comment]
Ok, then maybe we can close this issue, if you have filed a ticket to chocolatey, it would be fine to link it here for reference. Thanks!

**Comment by Sil3ntStorm** [comment]
https://github.com/chocolatey-community/chocolatey-packages/issues/2012
