### ISSUE TITLE
[feature] Support rendering the distro library in global.conf

### ISSUE THREAD

**Issue by wadimklincov** [conan-io/conan#12308]
Hi,

would it be possible to also forward the `distro` library in `global.conf`? My use case is selecting default profiles based on the Linux distribution, but unfortunately `platform` only gained support for parsing `/etc/os-release` in [3.10](https://docs.python.org/3/library/platform.html#platform.freedesktop_os_release) and I wasn't able to find any feasible alternative prior to that.

Thank you!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This seems a valid use case, and it should be easy to provide, let's give it a try and check with the team.

**Comment by memsharded** [comment]
Feature merged, it will be in next 1.54

**Comment by wadimklincov** [comment]
Awesome, thanks a lot for the quick implementation!
