### ISSUE TITLE
[question] Correct usage of requirements

### ISSUE THREAD

**Issue by steffenroeber** [conan-io/conan#12302]
Hi,
imagine you have a recipe that needs for example a static lib like zlib as a requirement at build time.
This lib is then only needed to build your recipe. I would put such a requirements into the build_requirements step.
In your docu is stated that this is not intended because only build tools should be used there.
But, if I put zlib into requirements(), then zlib recipe is needed if I install my built package  later.
So, I tried to make zlib private, but this did not solved the problem, because still, zlib is search if I try to install my built recipe.
This become even more complicated, if zlib has own dependencies, that only are needed at build time but must in this approach be provided at install time.
Is there something I do wrong?

**Comment by memsharded** [comment]
Hi @steffenroeber 

Yes, indeed the docs in https://docs.conan.io/en/latest/devtools/build_requires.html try to clarify this a bit: ``build_requires`` or ``tool_requires`` are exclusively for tools, required at build time, like ``cmake`` or something like that.

Yes, that means that libraries are needed, but they are needed in many cases, for example if zlib is a static library, and it is required by other static libraries, when you install those, zlib will still be necessary, and the package needs to be fetched and used in linking. There are only some cases, like when the consumer is a shared library that uses zlib strictly as an implementation detail, that zlib will not be required downstream. It is true that for those cases, Conan 1.X does not handle this, and will still download zlib. Using ``private`` is not recommended either in 1.X as a general solution for this.

The good news is that Conan 2.0 has addressed these issues. Even if the docs are not complete yet, the beta.4 is out, you can try it https://docs.conan.io/en/2.0/index.html, and to learn more about the new dependencies model you can watch this talk at ACCU: https://www.youtube.com/watch?v=kKGglzm5ous

**Comment by steffenroeber** [comment]
Ok. Thank you for fast clarification.
