### ISSUE TITLE
[bug] virtualenv + build with two profiles does not work

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#12329]
### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu:latest
  * Compiler+version: gcc 11 and 10.02
  * Conan version: latest

### Steps to reproduce (Include if Applicable)
git clone git@github.com:AndreyMlashkin/minimalistic_conan_docker.git
cd minimalistic_conan_docker
docker build.

### Logs (Executed commands with output) (Include/Attach if Applicable)

 216c552ea5ba
Step 2/11 : RUN   apt-get update &&   apt-get install -y python3 python3-pip
 ---> Using cache
 ---> 7e182ff23d42
Step 3/11 : RUN pip3 install conan
 ---> Using cache
 ---> c9034751fa78
Step 4/11 : RUN apt-get update && apt-get install -y make gcc g++ cmake
 ---> Using cache
 ---> bf24faea9af3
Step 5/11 : COPY build_profile /root/.conan/profiles/build_profile
 ---> Using cache
 ---> f5807b54a01f
Step 6/11 : COPY requirements.txt requirements.txt
 ---> Using cache
 ---> 8a91ae72e657
Step 7/11 : RUN conan install requirements.txt --build missing -g virtualenv -pr build_profile
 ---> Using cache
 ---> ac272df030c2
Step 8/11 : RUN apt-get remove -y make gcc g++
 ---> Using cache
 ---> 592c3278d6f7
Step 9/11 : COPY host_profile /root/.conan/profiles/host_profile
 ---> Using cache
 ---> 4d8e7e33b5fe
Step 10/11 : RUN ls -l -a && chmod +x activate.sh && . ./activate.sh && cmake --help && echo $CC && echo $CXX && conan install zlib/1.2.12@ --build zlib -pr:b=host_profile -pr:h=host_profile --build missing
 ---> Running in 373f9b3f97d5
/root/.conan/data/gcc/10.2.0/_/_/package/62dc4bccd4f53b2b80985003a91278369abf3a4b/bin/gcc-10.2.0
/root/.conan/data/gcc/10.2.0/_/_/package/62dc4bccd4f53b2b80985003a91278369abf3a4b/bin/g++-10.2.0
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=10.2
os=Linux
os_build=Linux
[options]
*:shared=False
cmake:with_openssl=False
[build_requires]
*: gcc/10.2.0, make/4.3, cmake/3.24.1
[env]
CMAKE_MAKE_PROGRAM=make
Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=10.2
os=Linux
os_build=Linux
[options]
*:shared=False
cmake:with_openssl=False
[build_requires]
*: gcc/10.2.0, make/4.3, cmake/3.24.1
[env]
CMAKE_MAKE_PROGRAM=make
zlib/1.2.12: Not found in local cache, looking in remotes...
zlib/1.2.12: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
zlib/1.2.12: Downloaded recipe revision 0
zlib/1.2.12: Forced build from source
WARN: mpfr/4.1.0: requirement gmp/6.2.1 overridden by mpc/1.2.0 to gmp/6.2.0 
zlib/1.2.11: Forced build from source
Installing package: zlib/1.2.12
Requirements
    zlib/1.2.12 from 'conancenter' - Downloaded
Packages
    zlib/1.2.12:30b88e95da2480aa597d26d85ba6f64038dcf40f - Build
Build requirements
    cmake/3.24.1 from 'conancenter' - Cache
    gcc/10.2.0 from 'conancenter' - Cache
    gmp/6.2.0 from 'conancenter' - Cache
    m4/1.4.19 from 'conancenter' - Cache
    make/4.3 from 'conancenter' - Cache
    mpc/1.2.0 from 'conancenter' - Cache
    mpfr/4.1.0 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
Build requirements packages
    cmake/3.24.1:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache
    gcc/10.2.0:62dc4bccd4f53b2b80985003a91278369abf3a4b - Cache
    gmp/6.2.0:449e527ce175490ba11c311028c9de6c454c619d - Build
    m4/1.4.19:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache
    make/4.3:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache
    mpc/1.2.0:c85de02642e2f4278d35ceee0e20ee832ddf4d22 - Build
    mpfr/4.1.0:391fe236ce3998076d9584f892788bce90ab14e0 - Build
    zlib/1.2.11:30b88e95da2480aa597d26d85ba6f64038dcf40f - Build

Installing (downloading, building) binaries...
cmake/3.24.1: Already installed!
cmake/3.24.1: Appending PATH environment variable: /root/.conan/data/cmake/3.24.1/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin
m4/1.4.19: Already installed!
m4/1.4.19: Appending PATH environment variable: /root/.conan/data/m4/1.4.19/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin
make/4.3: Already installed!
make/4.3: Creating CONAN_MAKE_PROGRAM environment variable: /root/.conan/data/make/4.3/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin/make
Downloading conan_sources.tgz
zlib/1.2.11: Configuring sources in /root/.conan/data/zlib/1.2.11/_/_/source/src
zlib/1.2.11: 
zlib/1.2.11: Copying sources to build folder
zlib/1.2.11: Building your package in /root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f
zlib/1.2.11: Generator txt created conanbuildinfo.txt
zlib/1.2.11: Calling generate()
zlib/1.2.11: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
zlib/1.2.11: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f/build/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
zlib/1.2.11: Aggregating env generators
zlib/1.2.11: Calling build()
zlib/1.2.11: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/zlib/1.2.11/_/_/package/30b88e95da2480aa597d26d85ba6f64038dcf40f" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f/src"
-- Using Conan toolchain: /root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f/build/Release/CMakeFiles/CMakeOutput.log".
zlib/1.2.11: 
zlib/1.2.11: ERROR: Package '30b88e95da2480aa597d26d85ba6f64038dcf40f' build failed
zlib/1.2.11: WARN: Build folder /root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f/build/Release
ERROR: zlib/1.2.11: Error in build() method, line 88
	cmake.configure()
	ConanException: Error 1 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/zlib/1.2.11/_/_/package/30b88e95da2480aa597d26d85ba6f64038dcf40f" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan/data/zlib/1.2.11/_/_/build/30b88e95da2480aa597d26d85ba6f64038dcf40f/src"
The command '/bin/sh -c ls -l -a && chmod +x activate.sh && . ./activate.sh && cmake --help && echo $CC && echo $CXX && conan install zlib/1.2.12@ --build zlib -pr:b=host_profile -pr:h=host_profile --build missing' returned a non-zero code: 1

-->

**Comment by AndreyMlashkin** [comment]
As you can see from the logs, CC and CXX variables are set correctly:
/root/.conan/data/gcc/10.2.0/_/_/package/62dc4bccd4f53b2b80985003a91278369abf3a4b/bin/gcc-10.2.0
/root/.conan/data/gcc/10.2.0/_/_/package/62dc4bccd4f53b2b80985003a91278369abf3a4b/bin/g++-10.2.0

But nevertheless got 
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set,

**Comment by memsharded** [comment]
Hi @AndreyMlashkin 

I am very sorry this was not followed up back then.
I am closing this issue as outdated, as it is related to the legacy Conan 1 environment integrations. Please don't hesitate to create a new ticket if necessary for any question. Thanks for your feedback!
