### ISSUE TITLE
[question] Conan 2.0: Using `is_msvc` fails in validate trying access settings

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12321]
https://github.com/conan-io/conan-center-index/pull/13525#issuecomment-1281430889

```py
    def validate(self):
        if is_msvc(self) and self.info.options.shared:
            raise ConanInvalidConfiguration(f"{self.ref} shared not supported by Visual Studio")
```

gives a `ConanException: 'self.settings' access in 'validate()' method is forbidden`

https://github.com/conan-io/conan/blob/a1abe135c6ecb646e0eaad6ab99aa22600b1858e/conan/tools/microsoft/visual.py#L288

- is this expected (it's the default 1.x convention)?
- should this type of check be done in `valdiate_build`?

**Comment by AbrilRBS** [comment]
`self.info` access in `validate`/`validate_build` is kept for backwards compatibility, but the recommended approach is not to use it, and directly access the necessary information, and keep `self.info` exclusively for the `package_id()` method.

Closing as solved now that the behaviour has been clarified and the mentioned error removed
