### ISSUE TITLE
[feature] install system packages without architecture

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#12320]
Currently, recipes with arch settings trying to install system packages always install the system package with architecture matching the profile. This makes xorg/system fail on some distros (alma, Fedora and Centos), because some of the system packages do not have an architecture:
the failures:
- https://github.com/bincrafters/system-packages-checks/actions/runs/3266259888/jobs/5369817368#step:6:191
- https://github.com/bincrafters/system-packages-checks/actions/runs/3266259888/jobs/5369817556#step:6:180
- https://github.com/bincrafters/system-packages-checks/actions/runs/3266259888/jobs/5369816469#step:6:263
- https://github.com/bincrafters/system-packages-checks/actions/runs/3266259888/jobs/5369819520#step:6:238
- https://github.com/bincrafters/system-packages-checks/actions/runs/3266259888/jobs/5369819717#step:6:198
- https://github.com/bincrafters/system-packages-checks/actions/runs/3266259888/jobs/5369817145#step:6:244

these two system packages have no arch, cf!
- https://almalinux.pkgs.org/9/almalinux-appstream-x86_64/xkeyboard-config-devel-2.33-2.el9.noarch.rpm.html
- https://almalinux.pkgs.org/9/almalinux-crb-x86_64/xorg-x11-xtrans-devel-1.4.0-8.el9.noarch.rpm.html

We could consider adding a method like `_SystemPackageManagerTool.install_archless(...)` ? Or an automatic fallback to archless if there is no existing package for the setting's arch ?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
But wouldn't ``install_archless()`` fail in the system that use the architecture?
Does those distributions lack the specific architecture packages for all packages or just a few? If they are missing all architecture packages, then it seems it should be a ``conf`` that enables opting-out of the architecture behavior?

**Comment by ericLemanissier** [comment]
for the two packages which currently fail (`xorg-x11-xtrans-devel` and `xkeyboard-config-devel`), they are `.noarch` on all distros using `dnf` or `yum` (https://pkgs.org/search/?q=xorg-x11-xtrans-devel and https://pkgs.org/search/?q=xkeyboard-config-devel). They are `.noarch` because they only contain text files.
I am currently testing all the system packages currently on CCI:
- https://github.com/conan-io/conan-center-index/pull/13565
- https://github.com/conan-io/conan-center-index/pull/13566
- https://github.com/conan-io/conan-center-index/pull/13567
- https://github.com/conan-io/conan-center-index/pull/13568
- https://github.com/conan-io/conan-center-index/pull/13569
- https://github.com/conan-io/conan-center-index/pull/13570
- https://github.com/conan-io/conan-center-index/pull/13571

EDIT: the failures I got in https://bincrafters.github.io/system-packages-checks/ are on:
- vaapi and vdpau, which is the exact same failure as xorg/system, because vaapi and vdpau's test recipe require xorg/system
- glu on jammy and kinetic is unrelated

So in the end I feel confident that calling `dnf.install_archless(["xorg-x11-xtrans-devel", "xkeyboard-config-devel"])` and `yum.install_archless(["xorg-x11-xtrans-devel", "xkeyboard-config-devel"])` in xorg/system would fix the problem without breaking CCI packages

**Comment by jothalha** [comment]
Just as an fyi the arch check also fails on ubuntu jammy for xorg for the same reason if the packages are already installed:

```
dpkg-query: no packages found matching xtrans-dev:amd64
dpkg-query: no packages found matching xkb-data:amd64
```

would be good to have a `install_archless` method for apt as well

**Comment by ericLemanissier** [comment]
This is linked to https://github.com/conan-io/conan-center-index/issues/13588

**Comment by ericLemanissier** [comment]
Actually, `xtrans` and `xkeyboard-config` system packages have no arch on all the system package managers handled by conan, so I created [`xtrans/system`](https://github.com/conan-io/conan-center-index/pull/13595) and [`xkeyboard-config/system`](https://github.com/conan-io/conan-center-index/pull/13594) recipes without arch setting. a dedicated `install_archless` is not actually needed

**Comment by czoido** [comment]
We close this, although we know that is not completely addressed in https://github.com/conan-io/conan/pull/12349
There's a workaround to install packages without architecture using: 

```
Apt(self, arch_names={}).install(["archless-package"], update=True, check=True)
```

But I'll open a new issue to improve UX for this.
