### ISSUE TITLE
[bug] Conan 1.X: prefer build_requires from direct/indirect dependencies over build_requires from profiles

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#12327]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: clang-13
  * Conan version: 1.44.1
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
==> mybin.py <==
```
import os

from conans import ConanFile

class ConanRecipe(ConanFile):
    name = "mybin"
    version = "1.0.0"

    def build(self):
        pass
        
    def package(self):
        os.makedirs(os.path.join(self.package_folder, "bin"), exist_ok=True)
        self.run("cd %s/bin && echo 'echo mybin' > mybin; chmod +x mybin" % self.package_folder)
```

==> myproject.py <==
```
import os

from conans import ConanFile

class ConanRecipe(ConanFile):
    name = "myproject"
    version = "1.0.0"

    def build_requirements(self):
        self.build_requires("mybin/1.0.0")
    
    def build(self):
        print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
        self.run("mybin")
        print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
        self.run("which -a mybin")
 ```
       
==> sysroot.py <==
```
import os

from conans import ConanFile

class ConanRecipe(ConanFile):
    name = "sysroot"
    version = "1.0.0"

    def build(self):
        pass
        
    def package(self):
        os.makedirs(os.path.join(self.package_folder, "bin"), exist_ok=True)
        self.run("cd %s/bin && echo 'echo sysroot' > mybin; chmod +x mybin" % self.package_folder)
```

==> sysroot.profile <==
```
[build_requires]
sysroot/1.0.0
```

==> run.sh <==
```
#!/bin/bash

set -ex

conan export sysroot.py
conan export mybin.py
conan export myproject.py test/test

rm -rf build && mkdir build
cd build

conan install myproject/1.0.0@test/test -pr:h=../sysroot.profile -pr:b=../sysroot.profile --build=missing --build=myproject
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
myproject/1.0.0@test/test: Calling build()
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
sysroot
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/home/EU.BSHG.COM/kleint/.docker-build-scripts/conan_cache/.conan/data/sysroot/1.0.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mybin
/home/EU.BSHG.COM/kleint/.docker-build-scripts/conan_cache/.conan/data/mybin/1.0.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mybin

```

As you can see the `mybin` executable from `sysroot/1.0.0` (profile) is first in `PATH` although a package containing `mybin` was specified as a `build_requirement` in the conanfile.py.

**Comment by czoido** [comment]
Hi @thorsten-klein,

Maybe [using patterns for the tool_requires](https://docs.conan.io/en/latest/devtools/build_requires.html#declaring-tool-requirements) in the profile could cover your case?
Something like ignoring the `tool_requires` for _myproject_ using this syntax:

```
 [tool_requires]
 ! myproject*: sysroot/1.0.0
```

**Comment by thorsten-klein** [comment]
@czoido thank you for the fast reply. Your approach does not work since I need other applications from the sysroot (I have not done this in my minimal example).

Did you check my pull request #12328? What do you think about this?

**Comment by czoido** [comment]
> @czoido thank you for the fast reply. Your approach does not work since I need other applications from the sysroot (I have not done this in my minimal example).
> 
> Did you check my pull request #12328? What do you think about this?

Hi @thorsten-klein,

I'm afraid it's risky to change that at this point in Conan 1.X, it may potentially break users that rely on that behaviour. I can give you some ideas that may help, one would be to use the [buildenv_info](https://docs.conan.io/en/latest/reference/conanfile/tools/env/virtualbuildenv.html#virtualbuildenv) in the `package_info` method, prepending or appending to the `PATH` the path of the folder where the binaries are. Also you should have to remove the default binary dirs or add the binaries to a different folder so they are not added in the order dictated by the graph resolution. For example for _sysroot.py_:

```
    def package_info(self):
        bindir = os.path.join(self.package_folder, "bin")
        self.buildenv_info.append_path("PATH", bindir)
        self.cpp_info.bindirs = []
```

and for _mybin.py_:

```
    def package_info(self):
        bindir = os.path.join(self.package_folder, "bin")
        self.buildenv_info.prepend_path("PATH", bindir)
        self.cpp_info.bindirs = []
```

Then using `-c tools.env.virtualenv:auto_use=True` when invoking Conan so that the environment files are generated automatically.

I made a full working example here: https://github.com/czoido/test_conan_envs where mybin is found first (check that if you invert the prepend and append it picks sysroot again).

Would this help you?

**Comment by thorsten-klein** [comment]
`-c tools.env.virtualenv:auto_use=True` seems to do the trick. can I do it also anyhow without this but specifying `generators = "virtualenv"` in the conanfile.py? This seems not to work then :-(

**Comment by czoido** [comment]
> `-c tools.env.virtualenv:auto_use=True` seems to do the trick. can I do it also anyhow without this but specifying `generators = "virtualenv"` in the conanfile.py? This seems not to work then :-(

@thorsten-klein  you could use:

- `generators = "VirtualBuildEnv"` in myproject
- or set `tools.env.virtualenv:auto_use=True` in the [global.conf](https://docs.conan.io/en/latest/reference/config_files/global_conf.html)

You can read more about that in the [Conan v2 migration guide](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html?highlight=virtualenv%20auto_use#the-environment-management)

**Comment by thorsten-klein** [comment]
+1
