### ISSUE TITLE
[feature] Consider porting conans.tools.cppstd_flag to Conan 2.0

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12324]
#### Suggestion

Port `conans.tools.cppstd_flag` to `conan.tools.build.cppstd_flag`

#### Why?

Some projects use a limited build script which require our manual intervention, passing all needed compiler flags, including `libcxx`, `cppstd`, `build_type`, `fPIC`, ... For those cases, we need to honor the `cppstd` version from the profile with what will be used by the compiler.

As a real example from CCI: https://github.com/conan-io/conan-center-index/pull/13552/files#diff-a3929dbede89f0e2d22b994ee16d101290e2d32f05767c52cc580a4edf1d950eR198

As we need to translate `cppstd` to the compiler flag, `cppstd_flag` would help us.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
https://docs.conan.io/2/reference/tools/build.html#conan.tools.build.flags.cppstd_flag already there
