### ISSUE TITLE
what method and at what stage is responsible for compression

### ISSUE THREAD

**Issue by whitefluffypenguin** [conan-io/conan#12337]
Hi there,
I have created the simple recipe, exported hierarchy into local cache export folder, created a package (copied all files into local cache package folder). Now i need to upload the package into artifactory and was thinking to compress files hierarchy prior to that. I searched in the reference and couldn't find any zip/archive/compress related functionality (btw found the unzip method). What do i miss?

**Comment by memsharded** [comment]
Hi @whitefluffypenguin 

All the artifacts that are uploaded to the server are automatically compressed (and decompressed when downloaded), so it is not necessary to do anything. The ``unzip()`` and other methods exists to unzip sources that are retrieved from internet, like third parties, but it is not necessary for the Conan package artifacts.

**Comment by whitefluffypenguin** [comment]
Interesting, so if I work with artifactory the compression will run on "conan upload" and decompression will run on "conan install"? Is it possible to specify type of archive, compression rate? Does it mean the local cache has to have at least one (per package) plain instance of files hierarchy in the package cache folder at any given time?

**Comment by memsharded** [comment]
> Interesting, so if I work with artifactory the compression will run on "conan upload" and decompression will run on "conan install"?

Yes

> Is it possible to specify type of archive, compression rate?

There is one config (``compression_level``) to define the compression rate, but the format is always ``tgz`` (best balance for fast unzipping, which is the most common, repeated operation)

> Does it mean the local cache has to have at least one (per package) plain instance of files hierarchy in the package cache folder at any given time?

Yes, the cache will always have a plain instance of files, the ``tgz`` is just an artifact for upload/install, but doesn't exist from the consumer perspective.

**Comment by whitefluffypenguin** [comment]
Thank you! We use jenkins for ci with number of agents configured that run multiple jobs. Is it recommended each agent uses its own cache folder or it is better to share the cache folder somehow in between the agents (following mentioned space requirements)?

**Comment by memsharded** [comment]
The cache is not designed for concurrency, so each job should have their own separate cache. They could use the "file download cache", which is concurrent (at the machine level), and can highly reduce the traffic to the servers. Otherwise, for separate agent machines, the best is to put the server as close to the agents as possible.

**Comment by whitefluffypenguin** [comment]
Understood - thank you!

**Comment by whitefluffypenguin** [comment]
One more clarification - is it not possible to share single "file download cache" between multiple machines (like multiple jenkins agents)?

**Comment by memsharded** [comment]
> One more clarification - is it not possible to share single "file download cache" between multiple machines (like multiple jenkins agents)?

That is complicated. The file download cache is using for synchornization system file locks, and up to our knowledge they might not be as robust as desired: https://superuser.com/questions/612736/which-network-file-systems-do-not-implement-locking-correctly. Maybe for some systems, like Linux, they work, but it is very possible that trying to use it for different OSs would fail.

**Comment by whitefluffypenguin** [comment]
Thank you!

**Comment by memsharded** [comment]
Ticket https://github.com/conan-io/conan/issues/15840 will track progress on Conan 2 cache concurrency, we can close this ticket and follow up there. Thanks!
