### ISSUE TITLE
profile detail in artifactory and include function in conanfile.txt

### ISSUE THREAD

**Issue by himansu2906** [conan-io/conan#12330]
Basically I have 2 different question.
1. Does Artifactory store detail of the profile? scenario (We want to be able to find with which profile, a project was built in ten years from now.)
2. we have following structure of the project, where we have **common** and **variation_point 1** and **variation_point 2** and each folder contains different source header and conanfile.txt file for dependencies.

> while building variation_point 1 we want to add conanfile.txt dependencies of variation_point 1 and common and same while building variation_point 2, adding conanfile.txt of variation_point 2 and common.
> but when we install dependencies from conanfile.txt while building in sequential manner, conanbuildinfo.cmake gets updated with last conan install call.
> we want to merger common and variation_point 1's conanfile.txt while building variation_point 1 and Variation_point 2 and common's conanfile.txt while building variation_point 2. 
is there any possibility to add these conanfile.txt while installing dependencies?

**Comment by czoido** [comment]
Hi @himansu2906,

Thanks for the questions:

- About 1: You could get the information of the settings and options from the `conan search` command. You can use like:

`conan search package/version@ -r=remote` and it will output the information on the terminal or with the _--table_ argument `conan search package/version@ -r=remote --table=info.html` that will render all the information about the packages to an html page.

- About 2: I would need a reproducible example for this. More details about the project structure, the generators used,...

Hope this helps

**Comment by himansu2906** [comment]
hello @czoido 

for second question, we have following project structure:
![image](https://user-images.githubusercontent.com/109611178/196942103-f4d51c4a-9607-436a-a3a9-766fb6a1ad30.png)

we want to change the variation while building the project and we to add dependencies of common and SRC36 conanfile.txt while building SRC36 and same for SRC14

but we have not found way to merge conanfile.txt dependencies.

**Comment by AbrilRBS** [comment]
Closing, as we didn't hear back from you in a while regarding point 2 - the `conan search` (Or `conan list` for Conan 2) answer still stands though :)
