### ISSUE TITLE
[question] Example profiles for `--profile:host` and `--profile:build` when using MSVC compilers?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12339]
Typically, there are about 4 types of MSVC compilers:

```
%VCToolsInstallDir%\bin\Hostx64\x64\cl.exe
%VCToolsInstallDir%\bin\Hostx64\x86\cl.exe
%VCToolsInstallDir%\bin\Hostx86\x64\cl.exe
%VCToolsInstallDir%\bin\Hostx86\x86\cl.exe
```

According to the [documentation](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#host-settings-os-build-arch-build-os-target-and-arch-target), using `arch` and `arch_build` for cross-compiling is not recommended. Instead, it is encouraged to use `--profile:host` and `--profile:build` to specify two profiles, respectively.

Can Conan Official or someone provide the basic examples of **Host Profile** and **Build Profile** when using these 4 types of MSVC compilers?

1.  Using `-T host=x64 -A x64` argument with Visual Studio generator.
2.  Using `-T host=x64 -A Win32` argument with Visual Studio generator.
3.  Using `-T host=x86 -A x64` argument with Visual Studio generator.
4.  Using `-T host=x86 -A Win32` argument with Visual Studio generator.

**Comment by memsharded** [comment]
Hi @hwhsu1231 

Using ``arch_build`` is the legacy way of cross-compiling or defining build context. The new way, introduced at least a couple of years is using the "build" and "host" profiles. You can read more about it here: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#using-tool-requires

Please have a look, and maybe you want to reformulate your question based on this approach?

**Comment by hwhsu1231** [comment]
@memsharded I've refomulated my question.

**Comment by memsharded** [comment]
The toolset architecture itself can be controlled with ``tools.cmake.cmaketoolchain:toolset_arch=value`` configuration, and that will be added to the ``conan_toolchain.cmake`` toolchain CMAKE_GENERATOR_TOOLSET, in the form of ``xxx, host=value``.

The settings ``arch`` is mapped to ``CMAKE_GENERATOR_PLATFORM`` inside the ``conan_toolchain.cmake``

The idea is to minimize the commands that users needs to pass in the command line, and just pass the ``conan_toolchain.cmake`` file

**Comment by hwhsu1231** [comment]
According to this [documentation](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#conf), since `tools.cmake.cmaketoolchain:toolset_arch=value` appends `,host=value` to CMAKE_GENERATOR_TOOLSET variable of `conan_toolchain.cmake` file, it will only affect **Visual Studio** generator. Am I correct?

![image](https://user-images.githubusercontent.com/71438617/196848787-c0c39189-843f-478a-8175-4aa0018e351e.png)

**Comment by hwhsu1231** [comment]
So does that mean choosing which MSVC compiler of the above 4 types is **NOT** related to **Host Profile** and **Build Profile**?

**Comment by memsharded** [comment]
> According to this [documentation](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#conf), since tools.cmake.cmaketoolchain:toolset_arch=value appends ,host=value to CMAKE_GENERATOR_TOOLSET variable of conan_toolchain.cmake file, it will only affect Visual Studio generator. Am I correct?

Yes, as you indicated in your question, this is for the Visual Studio generator.

> So does that mean choosing which MSVC compiler of the above 4 types is NOT related to Host Profile and Build Profile?

It takes the information from host profile and ``conf``. But even if the "build" profile is not explicitly used for this, its existence will trigger different behaviors, so it is strongly recommended to use it always, as this is the mode Conan 2.0 will always operate.

**Comment by hwhsu1231** [comment]
@memsharded 

Based on what the Conan 2.0 [documentation](https://docs.conan.io/en/2.0/tutorial/consuming_packages/cross_building_with_conan.html#conan-two-profiles-model-build-and-host-profiles) said, Conan will use **default** profile as the `--profile:build` (if we don't specify). Since there are 4 types(**x64**, **x64_x86**, **x86_x64**, **x86**) of MSVC compilers and at least 2 basic build type(**Debug**, **Release**), it is better to specify the **SAME** profile for `--profile:host` and `--profile:build` when using one of them. For example:

- If I define a profile called **win32-msvc-x64-debug**, then the arguments of `conan install` should be:
  
  ```
  --profile:host win32-msvc-x64-debug
  --profile:build win32-msvc-x64-debug
  ```

- If I define another profile called **win32-msvc-x86-release**, then the arguments of `conan install` should be:

  ```
  --profile:host win32-msvc-x86-release
  --profile:build win32-msvc-x86-release
  ```

- ...etc

Am I correct?

**Comment by hwhsu1231** [comment]
@memsharded 

There is one more thing I want to confirm:

For **Hostx64/x64/cl.exe**

-   Correspond to `vcvarsall.bat x64` command. (on **cmd.exe**)
-   `-T host=x64` corresponds to `--conf tools.cmake.cmaketoolchain:toolset_arch=x64`
-   `-A x64` corresponds to `--settings arch=x86_64`

For **Hostx64/x86/cl.exe**

-   Correspond to `vcvarsall.bat x64_x86` command. (on **cmd.exe**)
-   `-T host=x64` corresponds to `--conf tools.cmake.cmaketoolchain:toolset_arch=x64`
-   `-A Win32` corresponds to `--settings arch=x86`

For **Hostx86/x64/cl.exe**

-   Correspond to `vcvarsall.bat x86_x64` command. (on **cmd.exe**)
-   `-T host=x86` corresponds to `--conf tools.cmake.cmaketoolchain:toolset_arch=x86`
-   `-A x64` corresponds to `--settings arch=x64`

For **Hostx86/x86/cl.exe**

-   Correspond to `vcvarsall.bat x86` command. (on **cmd.exe**)
-   `-T host=x86` corresponds to `--conf tools.cmake.cmaketoolchain:toolset_arch=x86`
-   `-A Win32` corresponds to `--settings arch=x86`

Am I correct?

**Comment by memsharded** [comment]
> --profile:host win32-msvc-x64-debug
--profile:build win32-msvc-x64-debug

No, not really.

Do you want your CMake, your compiler, your toolchains, that is, everything that is a ``tool_require`` to run ``Debug`` executables? Typically no. So in most cases ``--profile:build`` would be a ``Release`` build.


Regarding the correspondences:

> Correspond to vcvarsall.bat x64 command. (on cmd.exe)
-T host=x64 corresponds to --conf tools.cmake.cmaketoolchain:toolset_arch=x64
-A x64 corresponds to --settings arch=x86_64


More or less, but not exactly. The mapping is not to command line arguments like ``-T .... -A``, but instead to CMake variables inside the generated ``conan_toolchain.cmake``. The result would be the same, but it is critical to pass the ``conan_toolchain.cmake`` to the cmake invocation

**Comment by hwhsu1231** [comment]
> No, not really.
> 
> Do you want your CMake, your compiler, your toolchains, that is, everything that is a `tool_require` to run `Debug` executables? Typically no. So in most cases `--profile:build` would be a `Release` build.

@memsharded 

If I want to use **Hostx64\x86\cl.exe**, then I write the following **Host Profile** (`win32-msvc2019-x64_x86-debug`). Is it correct?

```ini
[settings]
os=Windows
arch=x86
build_type=Debug
compiler=msvc
compiler.version=192
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.cppstd=14
[conf]
tools.cmake.cmaketoolchain:generator=Visual Studio 16 2019
tools.cmake.cmaketoolchain:toolset_arch=x64
```

If so, then what content of **Build Profile** should I have? 

1. Do I just need to replace all the `Debug` with `Release` in Build Profile?
2. Do I have to fill those `compiler` settings and `tools` configurations in Build Profile?
3. Conan will choose `default` profile as its default Build Profile. The following is the `default` profile in my computer. Can I directly use this `default` profile for those 4 types of MSVC compilers with both `Debug` and `Release` build types?

   ```ini
   [settings]
   os=Windows
   os_build=Windows     # [Q:] Should be deprecated in Conan 2.0, right?
   arch=x86_64
   arch_build=x86_64    # [Q:] Should be deprecated in Conan 2.0, right?
   build_type=Release
   [options]
   [build_requires]
   [env]
   ```

**Comment by hwhsu1231** [comment]
@memsharded 

I want to close this issue. But before doing so, I need to figure out what settings or contents (at least) I should specify for **Build Profiles** when doing **Native Building** with **MSVC** compilers. So that I can summarize this issue.

**Comment by hwhsu1231** [comment]
> Yes, there is a method to disable the warning, to pass the `-pr:b=default` profile.

@memsharded 

Based on what you said in https://github.com/conan-io/conan/issues/12271#issuecomment-1272085355, this is why I want to confirm what I should fill in **Build** profiles explicitly. It is because my `default` profile is printed as the following. Excluding `os_build` and `arch_build` which would be deprecated in Conan 2.0, it seems that we only need to fill the following 3 settings:

- `os=Windows`
- `arch=x86_64`
- `build_type=Release`

```cmd
C:\Users\hwhsu1231>conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

**Comment by memsharded** [comment]
Sorry @hwhsu1231 this was not followed up back then.

Yes, the above default profile removing the ``os_build`` and ``arch_build`` which do not exist anymore, is good for the "build" context for most cases.

Unless there is no pre-compiled binary for some of the tools that need to run in the "build" context, then, it will also need efinition of the ``compiler`` settings to use to build that tool.

I am closing this ticket as solved, but please don't hesitate to create a new ticket if necessary for any further question or issue. Thanks for your feedback!
