### ISSUE TITLE
[bug] The VirtualBuildEnv and VirtualRunEnv never clean the deactivate script

### ISSUE THREAD

**Issue by Bearwolves** [conan-io/conan#12344]
Quoted from https://github.com/conan-io/conan/issues/10979#issuecomment-1091155807
> You are right, in .bat it doesn't happen because it has:
> ```
> echo @echo off > "{deactivate_file}"
> echo echo Restoring environment >> "{deactivate_file}"
> ```
> So the first line removes the previous content of the file. Why this wouldn't be enough to do the same for .sh? That would be simple and remove the issue, wouldn't it?

We would be happy to have this simple thing for shell being fixed. It's really weird to have multiple prints of `Restoring environment` and unset while activating/deactivating the VirtualBuildEnv and/or VirtualRunEnv sequentially multiple time. That would align the behavior with Windows.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Conan version: 1.53.0
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
See https://github.com/conan-io/conan/issues/10979#issue-1193563400

### Logs (Executed commands with output) (Include/Attach if Applicable)
See https://github.com/conan-io/conan/issues/10979#issue-1193563400

**Comment by memsharded** [comment]
Hi @Bearwolves 

It is not fully clear to me if this is a different ticket than https://github.com/conan-io/conan/issues/10979#issuecomment-1091155807. Do you mean just removing the messages?

We removed some messages in https://github.com/conan-io/conan/pull/12168, I am fine with removing those too.

**Comment by Bearwolves** [comment]
@memsharded : Thanks for the fast answer!
Issue is that `deactivate_conanbuildenv.sh` (or related to os/arch) is never overwritten as it's done in batch.

Batch => https://github.com/conan-io/conan/blob/develop/conan/tools/env/environment.py#L281
Shell => https://github.com/conan-io/conan/blob/develop/conan/tools/env/environment.py#L353

**Comment by memsharded** [comment]
Oh I see what you mean, basically this for the .sh?

```diff
- echo "echo Restoring environment" >> "{deactivate_file}"
+ echo "echo Restoring environment" > "{deactivate_file}"
```

Definitely seems a bug, yes, should be simple to solve. Would you like to send a PR yourself to fix it?
