### ISSUE TITLE
[bug] MSBuildDeps generates invalid property file (dot replacement for component requirement)

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#12347]
Generated props file contains link to another props without dot replacement

`conan_hello_hello_withdot2_release_x64.props`:
```
...
<Import Condition="'$(conan_hello_hello.withdot_props_imported)' != 'True'" Project="conan_hello_hello.withdot.props"/>
...
```
actual name on disk:
`conan_hello_hello_withdot.props`

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 11
  * Compiler+version: VS2022
  * Conan version: 1.53.0
  * Python version: 3.9.1

### Steps to reproduce (Include if Applicable)
`mkdir hellopkg && cd hellopkg && conan new hello/0.1 --template=cmake_lib`
replace implementation of `package_info ` in conanfile.py with 
```
self.cpp_info.components["hello.withdot"].libs = ["hello"]
self.cpp_info.components["hello.withdot2"].libs = ["hello"]
self.cpp_info.components["hello.withdot2"].requires = ["hello.withdot"]
```
conan export . hello/0.1@testdot/channel
mkdir temp && cd temp && conan install -g MSBuildDeps --build=missing hello/0.1@testdot/channel

**Comment by schreibubi** [comment]
Seeing something similar when having a dependency on grpc:

In file conan_grpc_grpc___error_details_release_x64.props:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
    <Import Condition="'$(conan_grpc_grpc++_props_imported)' != 'True'" Project="conan_grpc_grpc++.props"/>
```

The actual filename of the file it wants to import is conan_grpc_grpc__.props. Seems like #11826 changed the filenames on disk, but not all locations where the filenames are referenced.

**Comment by Nekto89** [comment]
same problem with hyphen - might be important for minizip-ng/double-conversion libraries



```    
self.cpp_info.components["hello.withdot"].libs = ["hello"]
self.cpp_info.components["hello-withhyphen"].libs = ["hello"]
self.cpp_info.components["hellousage"].requires = ["hello.withdot", "hello-withhyphen"]
```
```
<ImportGroup Label="PropertySheets">
  <Import Condition="'$(conan_hello_hello.withdot_props_imported)' != 'True'" Project="conan_hello_hello.withdot.props"/>
  <Import Condition="'$(conan_hello_hello-withhyphen_props_imported)' != 'True'" Project="conan_hello_hello-withhyphen.props"/>
</ImportGroup>
```

**Comment by memsharded** [comment]
Proposing #12365 fix, please have a look and if you can try it from source that would be great.

**Comment by schreibubi** [comment]
This change fixes the issue for me. Thanks!

**Comment by Nekto89** [comment]
> Proposing #12365 fix, please have a look and if you can try it from source that would be great.

Seems to be working

**Comment by TSS-THa** [comment]
Will there be a bugfix release of 1.53 including this? Currently installing grpc with the MSBuildDeps generator breaks our projects as it is generating not existing property sheet names it tries to import.

**Comment by memsharded** [comment]
Hi @TSS-THa 

In theory, 1.54 is due very soon, so probably not. Also because this is not a regression or similar, apparently this never worked with MSBuildDeps, or was it working in 1.52?

**Comment by TSS-THa** [comment]
Hi @memsharded 

Thanks for the quick reply.

If 1.54 is due very soon that's also fine. Is there any ETA on it? Couldn't find a roadmap anywhere.

In 1.52 I had similar issues with the c-ares package grpc depends on, so I updated and found 1.53 solved that, but introduced another issue with grpc this time.

I'm currently working on a project to migrate the legacy Conan configurations we have on our huge mono-repo to make them ready for where Conan is heading and this is a quite big hurdle as I now can not test the automation anymore as I need to fix the generated files first.

I guess for the time being I'll automate the fixing of the generated property sheets too and just remove it when 1.54 is there and resolving that issue.

We are coming from project specific conanfiles in this huge multi-project repo and using the visual-studio-multi generator which causes all kinds of issues.

**Comment by memsharded** [comment]
We typically release the last days of every month, with some flexibility. As this 1st Nov is holiday here, it is possible that it will be delayed to 2-3rd of November.

**Comment by TSS-THa** [comment]
That's perfect. It's a holiday here too, so I'll work around those few days.
