### ISSUE TITLE
[feature] Add warning about things that will dissapear in 2.X from 2.0

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#12345]
We currently provide some "fake" attributes in the ConanFile for 2.0 in order to not break compatibility with 1.X recipes. For example `.names` and `.filenames`. But these attributes will dissapear at some point in Conan 2.X and we want users to be aware that these things will throw errors before they get them. The idea is start to output warning messages when those attributes are used and make them errors if `required_conan_version>=2.0`

Related to: https://github.com/conan-io/conan/issues/12334

**Comment by franramirez688** [comment]
Closes by https://github.com/conan-io/conan/pull/12351
