### ISSUE TITLE
[bug] MSVC runtime MultiThreadedDebugDLL with "conan install -s compiler.runtime=MTd"

### ISSUE THREAD

**Issue by schoetbi** [conan-io/conan#12348]
### Environment Details
  * Operating System+version: Windows 10
  * Compiler+version: Microsoft Visual Studio 2019 (16.7.28)
  * Conan version: Conan version 1.53.0
  * Cmake version: cmake version 3.22.2

### Steps to reproduce

- Checkout [flatbuffers ](https://github.com/google/flatbuffers/tree/v22.9.24) repository Tag v22.9.24
- Run `conan install -s build_type=Debug -s compiler.runtime=MTd .`
- Run `conan build .`

In the produced flatbuffers.vcxproj the runtime is: `<RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>`. I expected `<RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>`
```xml
<ClCompile>
      <AdditionalIncludeDirectories>C:\USRTMP\dev\OpenSource\flatbuffers\include;C:\USRTMP\dev\OpenSource\flatbuffers\grpc;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AssemblerListingLocation>$(IntDir)</AssemblerListingLocation>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <DisableSpecificWarnings>4512;4316;4456</DisableSpecificWarnings>
      <ExceptionHandling>Sync</ExceptionHandling>
      <InlineFunctionExpansion>Disabled</InlineFunctionExpansion>
      <Optimization>Disabled</Optimization>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <UseFullPaths>false</UseFullPaths>
      <WarningLevel>Level4</WarningLevel>
      <PreprocessorDefinitions>%(PreprocessorDefinitions);WIN32;_WINDOWS;FLATBUFFERS_LOCALE_INDEPENDENT=1;CMAKE_INTDIR="Debug"</PreprocessorDefinitions>
      <ObjectFileName>$(IntDir)</ObjectFileName>
    </ClCompile>
```

When running `cmake  -G "Visual Studio 16 2019" -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDebug .` I get
`<RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>`
```xml
<ClCompile>
      <AdditionalIncludeDirectories>C:\USRTMP\dev\OpenSource\flatbuffers\include;C:\USRTMP\dev\OpenSource\flatbuffers\grpc;C:\USRTMP\dev\OpenSource\flatbuffers\tests;C:\USRTMP\dev\OpenSource\flatbuffers\samples;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AssemblerListingLocation>$(IntDir)</AssemblerListingLocation>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <DisableSpecificWarnings>4512;4316;4456</DisableSpecificWarnings>
      <ExceptionHandling>Sync</ExceptionHandling>
      <InlineFunctionExpansion>Disabled</InlineFunctionExpansion>
      <Optimization>Disabled</Optimization>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
      <UseFullPaths>false</UseFullPaths>
      <WarningLevel>Level4</WarningLevel>
      <PreprocessorDefinitions>%(PreprocessorDefinitions);WIN32;_WINDOWS;FLATBUFFERS_LOCALE_INDEPENDENT=1;CMAKE_INTDIR="Debug"</PreprocessorDefinitions>
      <ObjectFileName>$(IntDir)</ObjectFileName>
    </ClCompile>
```
I also reported the [issue in the flatbuffers project](https://github.com/google/flatbuffers/issues/7592) to have a workaround, however I think that there are also changes needed in the conan project itself.

**Comment by memsharded** [comment]
Hi @schoetbi 

I think a bit of extra information is necessary: I am missing the ``conanfile.py`` recipe information. You are pointing to the flatbuffers project, but in order to make a Conan package out of it, a ``conanfile.py`` is necessary. Are you using the recipe from ConanCenter? What is your consumer conanfile? What generators are you using? Thanks!

**Comment by schoetbi** [comment]
@memsharded I use the `conanfile.py` in the [flatbuffers ](https://github.com/google/flatbuffers/blob/v22.9.24/conanfile.py) project and want to create a conan package for flatbuffers to be consumed in my project. But the consumption is not the problem since during the creation process the compiler runtime is not what I have expected. I want to build a package for MSVC2019/static/Debug using `conan install -s build_type=Debug -s compiler.runtime=MTd .` but get MDd instead.

**Comment by memsharded** [comment]
That conanfile.py dates back from 2018. You probably want to use the community maintained one in ConanCenter? https://github.com/conan-io/conan-center-index/tree/master/recipes/flatbuffers/all

The process to contribute open source third party dependencies has changed in this time, a lot, and now is way more efficient and easy to maintain by the community, check the activity in https://github.com/conan-io/conan-center-index

**Comment by schoetbi** [comment]
I see, maybe it makes sense to remove the old recipe from the flatbuffers project. 

I added flatbuffers 22.9.24 to the [`conandata.yml` ](https://github.com/schoetbi/conan-center-index/commit/654407af97291dba4555857ab2c244b41fa65abf). Then I created the required packages with

 ```
conan create all/conanfile.py flatbuffers/22.9.24@  -s build_type=Release -s compiler.runtime=MD
conan create all/conanfile.py flatbuffers/22.9.24@  -s build_type=Debug -s compiler.runtime=MDd
conan create all/conanfile.py flatbuffers/22.9.24@  -s build_type=Release -s compiler.runtime=MT
conan create all/conanfile.py flatbuffers/22.9.24@  -s build_type=Debug -s compiler.runtime=MTd
```
Seems to work. Should I create a PR?

**Comment by memsharded** [comment]
> I see, maybe it makes sense to remove the old recipe from the flatbuffers project.

Yes, but that is outside of our control, I guess it needs to be reported and discussed with the flatbuffers maintainers. Maybe @prince-chrismc has better idea about this?

> Seems to work. Should I create a PR?

Yes, sure, that would be great. Please read the docs at https://github.com/conan-io/conan-center-index, due to security reasons, there is a bit of process, first you need to request access, and in a couple of days typically it will be granted, so your PRs will be built.

**Comment by schoetbi** [comment]
@memsharded Thank you for your help. I just created a comment to get access and will create a PR.
