### ISSUE TITLE
[bug] conan 2 list subcommands: -r and -c are not mutually exclusive

### ISSUE THREAD

**Issue by antze-k** [conan-io/conan#12346]
In develop2 branch, in conan/cli/commands/list.py:

```py
def _add_remotes_and_cache_options(subparser):
    remotes_group = subparser.add_mutually_exclusive_group()
    remotes_group.add_argument("-r", "--remote", default=None, action=Extender,
                               help="Remote names. Accepts wildcards")
    subparser.add_argument("-c", "--cache", action='store_true', help="Search in the local cache")
```

Shouldn't the last line be remotes_group.add_argument instead?

**Comment by memsharded** [comment]
Hi @antze-k 

Both arguments are not mutually exclusive, the ``conan list`` command can list things from the cache and from remotes, simultaneously. Probably it is just the ``remotes_group`` which seems unnecessary? Do you want to do a PR to fix it yourself?

**Comment by antze-k** [comment]
Sure, will take a bit closer look then.

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/12350
