### ISSUE TITLE
build_requires for recipes

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1234]
Current implementation of build_requires is only for profiles.
I think it can be added to recipes for must-have build requires, so recipes don't depend on client-side definition of build_requires.

Proposal:

```python

class Pkg(ConanFile):
      build_requires = "tool/..@user/channel", ...

      def build_requirements(self):
            # for conditional requirements
```

That probably could serve @claasd related to https://github.com/conan-io/conan/issues/1172

**Comment by claasd** [comment]
Hi,

how will these build requires affect my package_ids? currently we use private dependencies for must-have build requirements, and my package_ids change all the time due to different versions of the same private requirement.

**Comment by memsharded** [comment]
They wont affect at all to package_ids, they will be totally independent. They will not be in "requires" or "package_id()".

For your current problem, I guess you know you can just remove the private require in ``package_id()``, so it doesn't affect at all your id, do you?

**Comment by claasd** [comment]
How? I tried the `self.info.requires["MyPrivatePackage"].unrelated_mode()`. But this does not solve the problem I have. Is there another way?

**Comment by memsharded** [comment]
So even with the ``unrelated_mode()`` are you getting different package_ids when the dependency version changes? That is weird, I cannot reproduce.
Maybe you could try to completely remove:

```python
self.info.requires.remove("MyPrivatePackage")
```
It is possible that the private requirement has options and they are being changed? Then in that case, this might help:
```python
self.info.requires.remove("MyPrivatePackage")
self.info.options.pop("MyPrivatePackage")
```
Sure the UI could be improved (however, probably with build_requires the problem might be gone), with a single function or just same delete interface for info.requires and info.options

**Comment by claasd** [comment]
Hi,
remove is working like a charm the way I want it to!

The problem I encountered was with complex dependencies, each package using a private dependency to one base version (CMakeMacros). When one package used a different version, the package id of the last package changed (as did the number of needed CMakeMacros packages), even with unrelated_mode.

If you want, I can provide a test case.

**Comment by memsharded** [comment]
Good to know it. 
Yes, I am trying, but cannot find why ``unrelated_mode()`` is not working for you, it should have the same effect on the package-id than removing it. If you could do it with a lot of effort, it would be good to have a test case. But in any case, I'd say it is not high priority, my bet is that ``build_requires`` will make a better approach for that use case. Right now can be already done in the profiles, next version will allow to add them in the recipes, but the good thing is that they will be manageable (override version, defines settings) from the downstream consumer. Much more convenient than the current "private" approach, and you will not have to worry about messing with the package_id.
