### ISSUE TITLE
[feature] Ability to debug a recipe

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#12356]
I think it would be nice to be able to easily debug a recipe, even when exporting the recipe.

Setting a break point inside your python conan recipe and be able to step inside the code makes it possible to increase the understanding of conan itself.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Usually, I use PyCharm IDE. It's possible to run a Conan command and attach to the process. Of course, it's not what you suggested, but breaks a leg.

**Comment by madebr** [comment]
Me too!  :fist_right:

But are you able to set a breakpoint in your recipe, run `conan create` and have the debugger stop?

**Comment by uilianries** [comment]
@madebr Need to configure a bunch of stuff. Another option is: Open conan client on PyCharm and add a recipe as a new test, then you can easily debug. Again, you can see it's not so straightforward. So your feature request is much better than what we have now. Usually, I use `self.info.warn` (Yes, old print messages) in recipes, but we know for some cases, we waste much time trying to find something with prints.

**Comment by jcar87** [comment]
Hi @madebr - your ability to use a debugger to stop at a breakpoint in a Conan recipe will vary depending on the Conan command you are running.

In particular for `conan create`, the recipe will be first copied to the local Conan cache, so breakpoints in your local copy of `conanfile.py` will not work.

You can work around this by first running `conan export`, then locate and open the _exported_ `conanfile.py` inside the Conan cache, and run `conan create` again. If you have configured your IDE to debug the `conans.conan` module, it should successfully stop at breakpoints.

For example, if I were to export a recipe from Conan Center Index:

```
all % conan export . 1.2.12@
Exporting package recipe
zlib/1.2.12 exports: File 'conandata.yml' found. Exporting it...
zlib/1.2.12 exports: Copied 1 '.yml' file: conandata.yml
zlib/1.2.12: Calling export_sources()
zlib/1.2.12: A new conanfile.py version was exported
zlib/1.2.12: Folder: /Users/luisc/.conan/data/zlib/1.2.12/_/_/export
zlib/1.2.12: Exported revision: bb959a1d68d4c35d0fba4cc66f5bb25f
```

The following file is one I can set breakpoints in:
```
/Users/luisc/.conan/data/zlib/1.2.12/_/_/export/conanfile.py
```



Another alternative, without having to find the `conanfile.py` as it is exported into the cache, is to add `breakpoint()` calls in the recipe. If the interpreter is debugging when you call `conan create`, it should stop in the correct file.

**Comment by madebr** [comment]
Thanks for the `breakpoint()` workaround. It's not perfect, but works during development.

**Comment by jcar87** [comment]
Thanks @madebr  - hope that works :) Will close the issue as there appears there is a way of doing this, feel free to reopen if something does not work.
