### ISSUE TITLE
[bug] Help for Conan 2 "source" command appears to be incorrect

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12358]
The help text for the Conan 2.0 "source" command summary reads:

> Install + calls the build() method

whereas I believe it should say 

> Calls the source() method

Additionally, it is confusing as to whether the "path" positional argument is optional or required. By observation, it appears to be required, but the help syntax shows it as optional (if one follows the convention that brackets denote optional arguments). Thus, it might be clearer if:

> usage: conan source [-h] [-v [V]] [--logger] [--name NAME] [--version VERSION]
>                     [--user USER] [--channel CHANNEL]
>                     [path]

were changed to

> usage: conan source [-h] [-v [V]] [--logger] [--name NAME] [--version VERSION]
>                     [--user USER] [--channel CHANNEL]
>                     path

or

> usage: conan source [-h] [-v [V]] [--logger] [--name NAME] [--version VERSION]
>                     [--user USER] [--channel CHANNEL]
>                     \<path\>

### Environment Details (include every applicable attribute)
  * Operating System+version: all
  * Compiler+version: all
  * Conan version: 2.0.0-beta4
  * Python version: all

### Steps to reproduce (Include if Applicable)

conan-2.0 --help

or

conan-2.0 source --help

### Logs (Executed commands with output) (Include/Attach if Applicable)

> $ conan-2.0 source --help
> usage: conan source [-h] [-v [V]] [--logger] [--name NAME] [--version VERSION]
>                     [--user USER] [--channel CHANNEL]
>                     [path]
> 
> Install + calls the build() method
> 
> positional arguments:
>   path               Path to a folder containing a recipe (conanfile.py or
>                      conanfile.txt) or to a recipe file. e.g.,
>                      ./my_project/conanfile.txt.
> 
> optional arguments:
>   -h, --help         show this help message and exit
>   -v [V]             Level of detail of the output. Valid options from less
>                      verbose to more verbose: -vquiet, -verror, -vwarning,
>                      -vnotice, -vstatus, -v or -vverbose, -vv or -vdebug, -vvv
>                      or -vtrace
>   --logger           Show the output with log format, with time, type and
>                      message.
>   --name NAME        Provide a package name if not specified in conanfile
>   --version VERSION  Provide a package version if not specified in conanfile
>   --user USER        Provide a user if not specified in conanfile
>   --channel CHANNEL  Provide a channel if not specified in conanfil
> (conan-2.0)

**Comment by memsharded** [comment]
Hi @System-Arch 

Yes, that message is definitely wrong. If you want to contribute a quick fix PR yourself, you can do it, thanks for reporting!

The other messages are a bit more difficult to change, because it is not Conan who is displaying it that way, but the Python ``argparse`` library.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12361
