### ISSUE TITLE
[question] Build-time only ConanInvalidConfiguration for a tool requirement

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#12352]
- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

The `mold` linker can only be built with GCC 10 or newer, and that's being enforced with the `validate()` method:
https://github.com/conan-io/conan-center-index/blob/86de5edf37c74befdcd1a318bee352d15a01e675/recipes/mold/all/conanfile.py#L32-L33

This makes sense when you're actually building the mold package, but it also prevents it from being consumed by a project being built with an older GCC.
In my case, I build my project with GCC 8 and I'm including `mold` as a `build_requirement`, but conan complains about it:
```
Installing (downloading, building) binaries...
ERROR: There are invalid packages (packages that cannot exist for this configuration):
mold/1.5.1: Invalid ID: GCC version 10 or higher required
```

I'm wondering if there is a way of enforcing this only at compile-time and not at consumption time.
The package already removes the compiler from the build ID  with
```py
    def package_id(self):
        del self.info.settings.compiler
```

Thanks!

**Comment by memsharded** [comment]
Hi @ericriff 

Are you aware of the new ``validate_build()`` method, that will only raise if the package is going to be built?
There are still some corner cases with all the validate methods between 1.X and 2.0, but this sounds it could help in your case.

**Comment by ericriff** [comment]
Duh
I was not aware of this method. I missed it on the docs.
Conan is changing too fast, I can't keep up haha.
I'll check it out

**Comment by AbrilRBS** [comment]
Closing as solved, as the `validate_method` method was implemented to solve issues like these :)
