### ISSUE TITLE
Using Conan with Neovim CoC (Conquest of Completion)

### ISSUE THREAD

**Issue by darius-grauslys** [conan-io/conan#12369]
I want to use Neovim for my C++ development, and CoC is a great alternative to YouCompleteMe. However the Conan documentation only specifies YouCompleteMe as one of it's vim-like generators. Is there any support for CoC?

**Comment by memsharded** [comment]
Hi @WearsomeKarma 

No, there is no generator for CoC, but it should be relatively easy to build one if you know how it works, and getting inspiration from the existing generators. Some hints:

- Use a custom generator in Conan 1.X, but if you want to prepare the code to be easily adaptable for Conan 2.0, make sure it iterates the dependencies with the new ``conanfile.dependencies`` https://docs.conan.io/en/latest/reference/conanfile/dependencies.html
- Custom generators in that form will be removed in 2.0. Instead the new ``deployers`` is the recommended way. The code inside it will be practically the same, but it will be invoked with ``conan install .... --deploy=mycoc``

**Comment by darius-grauslys** [comment]
Hi @memsharded 

In short I was trying to set up neovim to use a c++ language server and detect the packages loaded in by conan. My initial confusion was that conan had to give something to CoC.

Turns out I missed the part where I needed compile_commands.json:
https://github.com/neoclide/coc.nvim/wiki/Language-servers

So by including -DCMAKE_EXPORT_COMPILE_COMMANDS=1 it worked, but _only_ if I included -DCMAKE_BUILD_TYPE=Release - otherwise the packages would not be included into the build commands.

Do you know why this is required? I tried with -DCMAKE_BUILD_TYPE=Debug and it wouldn't export the required compile commands.

**Comment by memsharded** [comment]
The CMAKE_BUILD_TYPE is necessary, because Conan dependencies are installed with ``build_type=Debug|Release|...``. In single-config generators like Linux makefiles (from CMake), the CMAKE_BUILD_TYPE argument is necessary to align with the right build of the dependencies.

Does this clarify it? At the moment it seems there is no action on the conan side, so I guess we can close this issue?

**Comment by perseoGI** [comment]
Hi @darius-grauslys,
As this issue is quite old, and native LSP is now included within Neovim, I was guessing if you are still having this issue...

**Comment by darius-grauslys** [comment]
Hi I think its safe to close the issue.

**Comment by perseoGI** [comment]
> Hi I think its safe to close the issue.

I'm closing this issue then, any other doubt do no hesitate on asking. I'm also a Neovim developer.
Some known problem related with the autocompletion using Neovim are related to how Conan is installed.

If installed via `homebrew` on MacOS, `pacman` on Arch, etc. the build in LSP may not found the sources to autocomplete.
It is recommended to instal Conan via `pipx`, `pyenv` or a local python environment. 
I'll investigate why that happen when I do get some spare time.
