### ISSUE TITLE
[develop2] Consider transitive_headers=True for header-only

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12364]
As all header files are public, and their dependencies headers will be exposed too, `self.requires(..., transitive_headers=True)` should be defaulted. It could managed by the package ID.

A follow question, should it be considered for `transitive_libs` too?

/cc @SpaceIm 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/12380, testing and feedback welcome!
