### ISSUE TITLE
[bug] Setting package_type = "application" results in ERROR during packaging if compiler.cppstd setting is removed

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12370]
While porting the nasm CCI recipe to Conan 2.0, I encountered an unexpected error of the form:

> ERROR: 'settings.compiler.cppstd' doesn't exist for 'msvc'
> 'settings.compiler' possible configurations are ['runtime', 'runtime_type', 'toolset', 'update', 'version']

One of the underlying causes is deleting the compiler.cppstd setting in the recipe configure() method as instructed here: https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=rm_safe#settings

After extensive debugging using print statements, I discovered that the error is coming from the app_compat.py plugin as removing the package_type declaration from the recipe eliminates the error. I suspect that the compatibility logic needs to be enhanced to consider the case where we are building an application from C code thus making this setting irrelevant.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 22H2
  * Compiler+version: msvc (Visual Studio 2019)
  * Conan version: 2.0.0-beta4
  * Python version: 3.7.9

### Steps to reproduce (Include if Applicable)

conan-2.0 export-pkg -pr:b tools.jinja -pr:h tools.jinja --name nasm --version 2.15.05 .

### Logs (Executed commands with output) (Include/Attach if Applicable)

Here's the output from running this command along with my embedded diagnostics

> conan-2.0 export-pkg -pr:b tools.jinja -pr:h tools.jinja --name nasm --version 2.15.05 .
> WE ARE HERE IN EXPORT_PKG
> WE ARE HERE 1 IN CMD_EXPORT
> WE ARE HERE 2 IN CMD_EXPORT
> WE ARE HERE 2 IN EXPORT_PKG
> WE ARE HERE 2.5 IN EXPORT_PKG
> WE ARE HERE 3 IN EXPORT_PKG
> WE ARE HERE 3.3 IN EXPORT_PKG
> WE ARE HERE IN ANALYZE_BINARIES
> WE ARE HERE 1 IN ANALYZE_BINARIES
> WE ARE HERE 2 IN ANALYZE_BINARIES
> COMPAT FILE is C:\Users\marc\.conan2\extensions\plugins\compatibility\compatibility.py
> WE ARE HERE 3 IN ANALYZE_BINARIES
> IN EVALUATE_GRAPH
> AFTER BUILDMODE
> IN BIG ELSE
> IN BIG ELSE AFTER EP_ID
> BEFORE EVALUTE_NODE
> IN EVALUATE_NODE
> IN EVALUATE_NODE AFTER PROCESS_NODE
> AFTER EVALUTE_NODE
> IN BIG ELSE
> IN BIG ELSE AFTER EP_ID
> BEFORE EVALUTE_NODE
> IN EVALUATE_NODE
> IN EVALUATE_NODE AFTER PROCESS_NODE
> IN EVALUATE_NODE BEFORE PCP
> IN PCP 1
> IN COMPATIBLES
> IN COMPATIBLES 1
> IN COMPATIBLES 1A
> ENTERING COMPATIBLE_INFOS
> COMPATIBLE_INFOS - BEFORE SETTINGS
> COMPATIBLE_INFOS - AFTER SETTINGS
> COMPATIBLE_INFOS - BEFORE UPDATE SETTINGS
> nasm/2.15.05: Exporting package recipe
> nasm/2.15.05 exports: File 'conandata.yml' found. Exporting it...
> nasm/2.15.05: Copied 1 '.yml' file: conandata.yml
> nasm/2.15.05 exports: Copied 1 '.yml' file: conandata.yml
> nasm/2.15.05: Copied 1 '.patch' file: 2.15.05-0001-disable-newly-integrated-dependency-tracking.patch
> nasm/2.15.05 exports_sources: Copied 1 '.patch' file: 2.15.05-0001-disable-newly-integrated-dependency-tracking.patch
> nasm/2.15.05: Using the exported files summary hash as the recipe revision: e1b1c4d40eccb31bcc3ecf8420bd676d
> nasm/2.15.05: A new conanfile.py version was exported
> nasm/2.15.05: Folder: C:\Users\marc\.conan2\p\d325a5ee1494825b\e
> nasm/2.15.05: Exported revision: e1b1c4d40eccb31bcc3ecf8420bd676d
> ERROR: 'settings.compiler.cppstd' doesn't exist for 'msvc'
> 'settings.compiler' possible configurations are ['runtime', 'runtime_type', 'toolset', 'update', 'version']

Here's the Conan 2.0 nasm recipe that I am working on. It works as expected if I comment out the package_type declaration.

> from conan import ConanFile
> from conan.tools.files import chdir, copy, get, rmdir, apply_conandata_patches, replace_in_file
> from conan.tools.gnu import AutotoolsToolchain, Autotools
> from conan.tools.layout import basic_layout
> from conan.tools.microsoft import is_msvc, VCVars
> import os
> import shutil
> 
> required_conan_version = ">=1.53.0"
> 
> class NASMConan(ConanFile):
>     name = "nasm"
>     package_type = "application"
>     url = "https://github.com/conan-io/conan-center-index"
>     homepage = "http://www.nasm.us"
>     description = "The Netwide Assembler, NASM, is an 80x86 and x86-64 assembler"
>     license = "BSD-2-Clause"
>     settings = "os", "arch", "compiler", "build_type"
>     topics = ("nasm", "installer", "assembler")
> 
>     exports_sources = "patches/*" 
> 
>     def configure(self):
>         self.settings.rm_safe("compiler.libcxx")
>         self.settings.rm_safe("compiler.cppstd")
>         if is_msvc(self, build_context=True):
>             self.conf.define("tools.gnu:make_program", "nmake")
> 
>     def build_requirements(self):
>         if self.settings_build.os == "Windows":
>             self.build_requires("strawberryperl/5.30.0.1")
> 
>     def layout(self):
>         basic_layout(self, src_folder="src")
> 
>     def source(self):
>         get(self, **self.conan_data["sources"][self.version],
>              destination=self.source_folder, strip_root=True)
> 
>     def generate(self):
>         if is_msvc(self, build_context=True):
>             ms = VCVars(self)
>             ms.generate()
>         tc = AutotoolsToolchain(self)
>         if self.settings.arch == "x86":
>             tc.extra_cflags = ["-m32"]
>         elif self.settings.arch == "x86_64":
>             tc.extra_cflags = ["-m64"]
>         tc.generate()
> 
>     def package_id(self):
>         del self.info.settings.compiler
> 
>     def build(self):
>         apply_conandata_patches(self)
>         autotools = Autotools(self)
>         with chdir(self, self.source_folder):
>             if not os.path.exists("config/config.h.in"):
>                 if not os.path.exists("configure"):
>                     self.run("sh autogen.sh")
>                 autotools.configure()
>         if is_msvc(self, build_context=True):
>             with chdir(self, self.source_folder):
>                 autotools.make(args=["/f {}".format(os.path.join("Mkfiles", "msvc.mak"))])
>                 shutil.copy("nasm.exe", "nasmw.exe")
>                 shutil.copy("ndisasm.exe", "ndisasmw.exe")
>         else:
>             autotoos.configure()
>             # GCC9 - "pure" attribute on function returning "void"
>             replace_in_file(self, "Makefile", "-Werror=attributes", "")
>             autotools.make()
> 
>     def package(self):
>         print("INVOKING PACKAGE METHOD %s" % self.build_folder)
>         copy(self, "LICENSE", self.source_folder, os.path.join(self.package_folder, "licenses"), keep_path=False)
>         if is_msvc(self, build_context=True):
>             copy(self, "*.exe", self.source_folder, os.path.join(self.package_folder, "bin"), keep_path=False)
>         else:
>             autotools = Autotools(self)
>             autotools.install()
>             rmdir(self, os.path.join(self.package_folder, "share"))
> 
>     def package_info(self):
>         bin_path = os.path.join(self.package_folder, "bin")
>         self.output.info("Appending PATH environment variable: {}".format(bin_path))
>         self.runenv_info.PATH.append(bin_path)
>         self.cpp_info.libdirs = []
>         self.cpp_info.includedirs = []

**Comment by memsharded** [comment]
I have been checking this, manage to reproduce practically the same issue.
The analysis is good, many thanks.

I have been trying to do a fix, but I am struggling because of a couple of complicated details:

The ``compatibility.py`` for apps, intends to be able to provide a default compatibility when only ``os`` and ``arch`` are defined, but in that case:
```python
def configure(self):
    self.settings.rm_safe("compiler.libcxx")
    self.settings.rm_safe("compiler.cppstd")
```
Will actually fail to remove the ``compiler.cppstd``, because that only works when the ``compiler`` is defined and it has a value. If this settings is not removed, the ``compatibility.py`` does not have a way to know if it should provide a value or not, it is impossible to know.

Potential solutions and approaches:
-It seems we want ``self.settings.rm_safe("compiler.cppstd")`` to actually remove all ``cppstd`` subsetting of all compilers, irrespective of the ``compiler`` value. This seems complicated and probably fragile
- A long standing idea to define something like ``languages = "C"`` class attribute. That could be used to decide to propose a ``cppstd`` default or not in the default ``compatibility.py``

Assigning @czoido for their feedback too.

**Comment by memsharded** [comment]
Trying the approach of ``rm_safe()`` actually removing all possible settings in https://github.com/conan-io/conan/pull/12379

**Comment by memsharded** [comment]
This has been solved by https://github.com/conan-io/conan/pull/12484, because ``app_compat`` has been removed.

I will check what from https://github.com/conan-io/conan/pull/12379 could make sense to keep
