### ISSUE TITLE
[bug] Conan 2 source command has implicit dependency on default profile

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12371]
I typically specify profiles using a combination of conan config install and -pr:b and -pr:h command line options to ensure precise control over what Conan is using/doing. As a result, I never use, and thus avoid having, a default profile. Unfortunately, this approach runs into difficulties when trying to run the Conan 2.0 source command, as doing so results in the following error:

> $ conan-2.0 source --name nasm --version 2.15.05 .
> ERROR: The default host profile 'C:\Users\marc\.conan2\profiles\default' doesn't exist.
> You need to create a default profile (type 'conan profile detect' command)
> or specify your own profile with '--profile:host=<myprofile>'

I don't believe the source command actually references anything from the default profile and thus I suspect that it is an oversight (or common code path) that is causing this error. If the source command actually requires a profile, it would be nice if it accepted ---profile:host command as suggested in the error message. Unfortunately, one gets:

> $ conan-2.0 source --profile:host=tools.jinja --name nasm --version 2.15.05 .
> usage: conan source [-h] [-v [V]] [--logger] [--name NAME] [--version VERSION]
>                     [--user USER] [--channel CHANNEL]
>                     [path]
> conan source: error: unrecognized arguments: --profile:host=tools.jinja
> ERROR: Exiting with code: 2

That said, not requiring one at all seems like the cleaner solution.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 22H2
  * Compiler+version: msvc (Visual Studio 2019)
  * Conan version: 2.0.0-beta4
  * Python version: 3.7.9

### Steps to reproduce (Include if Applicable)

conan-2.0 source --name nasm --version 2.15.05 .

### Logs (Executed commands with output) (Include/Attach if Applicable)

> $ conan-2.0 source --name nasm --version 2.15.05 .
> ERROR: The default host profile 'C:\Users\marc\.conan2\profiles\default' doesn't exist.
> You need to create a default profile (type 'conan profile detect' command)
> or specify your own profile with '--profile:host=<myprofile>'

**Comment by czoido** [comment]
Hi @System-Arch,
Thanks a lot for reporting, I think this is something to be solved in the next beta release, adding to the beta5 milestone.

**Comment by czoido** [comment]
Thanks for reporting.
Closed by: https://github.com/conan-io/conan/pull/12475 to be released in beta5
