### ISSUE TITLE
[question] How to create a virtual like  package of `libjpeg` & `libjpeg-turbo`?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12374]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In conan-center, there is a very old wish to provide a virtual package of `libjpeg`. There are 3 well-known implementations of libjpeg: `libjpeg`, `libjpeg-turbo`, `mozjpeg`.

Currently each recipe is responsible of the implementation selection, it's tedious and leads to lot of discrepancy and illformed dependency graph (2 or 3 implementations in the same dependency graph => broken).
We would like to delegate this selection to only one virtual recipe, so that it could ensure coherency of the dependency graph (only one implementation).

Basically something like this:

```python
from conan import ConanFile, conan_version
from conan.tools.scm import Version

required_conan_version = ">=1.52.0"


class VirtualLibjpegConan(ConanFile):
    name = "virtual-libjpeg"
    description = "Proxy recipe to select either libjpeg, libjpeg-turbo or mozjpeg"
    license = "MIT"
    topics = ("proxy", "virtual", "libjpeg", "libjpeg-turbo", "mozjepg")
    homepage = "https://github.com/conan-io/conan-center-index"
    url = "https://github.com/conan-io/conan-center-index"

    settings = "os", "arch", "compiler", "build_type"
    options = {
        "impl": ["libjpeg", "libjpeg-turbo", "mozjpeg"],
    }
    default_options = {
        "impl": "libjpeg-turbo",
    }

    @property
    def _impl_version(self):
        return {
            "libjpeg": "9e",
            "libjpeg-turbo": "2.1.4",
            "mozjpeg": "4.1.1",
        }[str(self.options.impl)]

    def layout(self):
        pass

    def requirements(self):
        self.requires(f"{self.options.impl}/{self._impl_version}", transitive_headers=True, transitive_libs=True)

    def package_id(self):
        self.info.clear()

    def source(self):
        pass

    def build(self):
        pass

    def package(self):
        pass

    def package_info(self):
        if self.options.impl != "libjpeg": # libjpeg recipe already owns these names
            self.cpp_info.set_property("cmake_find_mode", "both")
            self.cpp_info.set_property("cmake_file_name", "JPEG")
            self.cpp_info.set_property("cmake_target_name", "JPEG::JPEG")
            if Version(conan_version).major < 2:
                self.cpp_info.names["cmake_find_package"] = "JPEG"
                self.cpp_info.names["cmake_find_package_multi"] = "JPEG"
        self.cpp_info.bindirs = []
        self.cpp_info.includedirs = []
        self.cpp_info.libdirs = []
        if self.options.impl == "libjpeg":
            self.cpp_info.requires = ["libjpeg::libjpeg"]
        elif self.options.impl == "libjpeg-turbo":
            self.cpp_info.requires = ["libjpeg-turbo::jpeg"]
        elif self.options.impl == "mozjpeg":
            self.cpp_info.requires = ["mozjpeg::libjpeg"]
```

I see one main issue with such virtual recipe and current conan behavior: if a recipeA depends on this virtual recipe, the underlying recipe implementation is not anymore a direct dependency of recipeA, so I suspect package id issues.
How to design this virtual recipe so that any recipe having it as a direct dependency would behave as if either libjpeg, libjpeg-turbo or mozjpeg would be considered a direct dependency?

**Comment by AbrilRBS** [comment]
Closing as solved with Conan 2, which implements the [`[replace_requires]` functionality](https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires) for cases like these.

The eventual idea is to remove all the "with_xxx" from CCI that just switch between versions of _api compatible_ packages (That is, only if the replacement is transparent to the recipe beyond which requirement to pull from)
