### ISSUE TITLE
[bug] 2.0 check_component_requires and ConanFileDependencies

### ISSUE THREAD

**Issue by beenjohn** [conan-io/conan#12372]
In relation to https://github.com/conan-io/conan/issues/12027 and https://github.com/conan-io/conan/pull/12280:

Similar to the dependency graph in issue #12027 I have a transitive dependency identical to a direct dependency. It looks to me like new function conans.model.build_info.check_component_requires is checking for direct dependencies conflicts with cpp_info via the ConanFileDependencies interface. 

The issue i'm seeing is a I have:

```
...
self.requires("packageA/0.0.1")    # This package also requires boost/1.76.0
self.requires("boost/1.76.0")
...
self.cpp_info.component["component"].requires(["boost::boost"])
```
Output: `ERROR: packageB/0.0.1: required component package 'boost::' not in dependencies`

I'm a little unclear of exactly where the traits for the dependencies are set, but the transitive dependency appears to be overwriting the list entry for the direct entry. From debugging, conanfile.dependencies["boost/1.76.0"].direct = False which is getting thrown out by the filter call in check_component_requires.

I'm not sure if this is expected behavior or not, but it seems like the entries conanfile.dependencies should |= some of the traits (run, libs, headers, direct, etc.) if there is a duplicate dependency.

### Environment Details (include every applicable attribute)
`conan profile show`
```
Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os.distro=Ubuntu20.04
[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True
```
`python3 --version`
`Python 3.8.10`

**Comment by beenjohn** [comment]
From further inspection, this change to requires.aggregate(...) fixes the issue for me:
```
--- requires.py	2022-10-24 17:59:55.657001602 +0000
+++ requires.py 2022-10-24 18:00:53.529600419 +0000
@@ -227,6 +227,7 @@
         self.run = self.run or other.run
         self.visible |= other.visible
         self.force |= other.force
+        self.direct |= other.direct
         if not other.test:
             self.test = False  # it it was previously a test, but also required by non-test
         # TODO: self.package_id_mode => Choose more restrictive?

```
Is this something I should submit a PR for or is the requires.direct trait intentionally left out of the aggregate function?

**Comment by memsharded** [comment]
Hi @beenjohn 

Yes, I guess that the above PRs don't fix the issue, have you tried updating just in case? they have been already merged into the ``develop2`` branch.

If that is the case, sure, please send a PR. The most important part of it is the test, but don't worry if it is not fully clear, just send the fix and we can try to collaborate and add the tests to your branch.

**Comment by jsallay** [comment]
We just upgraded to 2.0.0-beta4.  It looks like both of those fixes were merged into there, so we are running with them.

**Comment by beenjohn** [comment]
I'll get you a PR as soon as possible. From testing with the current unittest (t1, t2, t3) I was able to generate a reproducer. If you do:

```
class t3Conan(ConanFile):
    name = "t3"
    version = "0.1.0"
    generators = "CMakeDeps"
    requires = "t2/0.1.0", "t1/0.1.0"
...
```
Everything works fine.

```
class t3Conan(ConanFile):
    name = "t3"
    version = "0.1.0"
    generators = "CMakeDeps"
    requires = "t1/0.1.0", "t2/0.1.0"
...
```
You get `ERROR: t3/0.1.0: required component package 't1::' not in dependencies`. Basically ordering matters which makes sense for the above fix.

If you change t3Conan in https://github.com/conan-io/conan/blob/develop2/conans/test/integration/test_components_error.py to `requires = "t1/0.1.0", "t2/0.1.0"` the error should occur.

**Comment by memsharded** [comment]
Sounds great, then just copy & paste and change the test, or do parameterize it, as you prefer. Thanks!

**Comment by beenjohn** [comment]
PR should be ready. I'm still learning github PRs so let me know what else you need from me. I'm not exactly sure what to update for docs on this change.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12388, will be in beta.5
