### ISSUE TITLE
[question] Is `compiler.toolset` of `msvc` in `settings.yml` imcomplete (1.53.0)?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12384]
### Problem Descriptions

According to the [documentation](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html#msvc), `msvc` is intended to deprecate `Visual Studio`. However, as we can see in the following screeshot, `Visual Studio` has more options in `compiler.toolset` than `msvc`. I was wondering that:

- Is `compiler.toolset` of `msvc` in `settings.yml` imcomplete?
- If not, then what is the purpose?

![image](https://user-images.githubusercontent.com/71438617/197554123-43c33fa3-0fc4-40f0-83b7-277315609f73.png)

### Environments and Versions

- Conan Version: **Conan 1.53.0**

**Comment by memsharded** [comment]
Hi @hwhsu1231 

All the ``clang`` related toolchains have been moved to a different way to be defined, under ``compiler=clang`` in Windows.
Check the latest blog: https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html

Also, the way for MSVC compiler, to use another toolset, you can set ``conf``:
- ``tools.microsoft.msbuild:vs_version``
- ``tools.cmake.cmaketoolchain:generator``

To force a certain VS version (the ``toolset`` will be selected from the ``compiler.version`` of the ``msvc`` compiler

**Comment by hwhsu1231** [comment]
@memsharded Thanks for your replies.

Do you mean that we only need to specify `--settings compiler.toolset=xxx` when we use those **XP-related** toolset arguments in `-T`?

**Comment by memsharded** [comment]
> Do you mean that we only need to specify --settings compiler.toolset=xxx when we use those XP-related toolset arguments in -T?

Yes. In other cases the equivalent of ``-T`` is deduced from a combination of the other settings like ``compiler=clang`` and the ``confs`` above. There is no mapping for the ``LLVM-vsXXX`` toolsets though, we have struggled to find good documentation and usages, if you are relying on them, please let us know, and provide details about it.

**Comment by hwhsu1231** [comment]
I think this question is solved, so I'll close it.
