### ISSUE TITLE
[bug] Header-only packages can't be created without an empty generate method when using a layout

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#12383]
### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora 37
  * Compiler+version: GCC 12.2.1
  * Conan version: 1.53.0
  * Python version: 3.11.0rc2

### Steps to reproduce (Include if Applicable)

Create a header-only library without a `generator` or `generate` method.
Define a layout in the layout method, i.e. `basic_layout(self)`.
Run `conan create` to create a package.
The build will fail unless the following methd is added.

```python
def generate(self):
    pass
```

An explicit example can be found in conan-io/conan-center-index#13728.
This effects several other CCI packages where an empty `generate` method has been added as a workaround.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
nlohmann_json/3.11.2: Building your package in /var/home/jordan/.conan/data/nlohmann_json/3.11.2/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
nlohmann_json/3.11.2: Generator txt created conanbuildinfo.txt
Traceback (most recent call last):
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/command.py", line 2216, in run
    method(args[0][1:])
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/command.py", line 380, in create
    info = self._conan.create(args.path, name=name, version=version, user=user,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/conan_api.py", line 388, in create
    create(self.app, ref, graph_info, remotes, update, build_modes,
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/cmd/create.py", line 72, in create
    install_build_and_test(app, test_conanfile_path,
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/cmd/test.py", line 35, in install_build_and_test
    install_folder, conanfile = deps_install(app=app,
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/manager.py", line 94, in deps_install
    installer.install(deps_graph, remotes, build_modes, update, profile_host, profile_build,
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/installer.py", line 317, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/installer.py", line 466, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/installer.py", line 559, in _handle_node_cache
    pref = self._build_package(node, output, keep_build, remotes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/installer.py", line 602, in _build_package
    pref = builder.build_package(node, keep_build, self._recorder, remotes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/installer.py", line 227, in build_package
    self._build(conanfile, pref)
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/installer.py", line 138, in _build
    write_toolchain(conanfile, conanfile.generators_folder, self._output)
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/generators/__init__.py", line 257, in write_toolchain
    with chdir(path):
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/var/home/jordan/.local/lib/python3.11/site-packages/conans/client/tools/files.py", line 27, in chdir
    os.chdir(newdir)
FileNotFoundError: [Errno 2] No such file or directory: '/var/home/jordan/.conan/data/nlohmann_json/3.11.2/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/build-debug/conan'
```

**Comment by uilianries** [comment]
@jwillikers Thank you!

**Comment by memsharded** [comment]
I have been able to reproduce with this test:
```python
def test_basic_layout_no_generators():
    c = TestClient()
    conanfile = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.layout import basic_layout
        class Pkg(ConanFile):
            name = "pkg"
            version = "0.1"
            settings = "os", "compiler", "build_type", "arch"
            def layout(self):
                basic_layout(self)
        """)
    c.save({"conanfile.py": conanfile})
    c.run("create . -c tools.env.virtualenv:auto_use=True")
```
Note that it is necessary to define ``tools.env.virtualenv:auto_use=True`` otherwise it doesn't fail. But this is not being defined yet in ConanCenter, up to my knowledge, is it?

**Comment by jwillikers** [comment]
I don't think it fails in CCI, only locally. I wasn't aware that `tools.env.virtualenv:auto_use=True` was having an effect, but my settings have that enabled.

**Comment by memsharded** [comment]
> I don't think it fails in CCI, only locally. I wasn't aware that tools.env.virtualenv:auto_use=True was having an effect, but my settings have that enabled.

Ok, that makes sense, thanks!

**Comment by SSE4** [comment]
> I don't think it fails in CCI, only locally. I wasn't aware that `tools.env.virtualenv:auto_use=True` was having an effect, but my settings have that enabled.

what exactly is `auto_use`? search in docs only shows 3 places where it is mentioned briefly, e.g. this [paragraph](https://docs.conan.io/en/latest/reference/profiles.html?highlight=auto_use#buildenv):
```
The use of this [buildenv] section requires using the VirtualBuildEnv generator in your recipe, or putting the configuration tools.env.virtualenv:auto_use=True in your profile.
```
so, does it mean usage of `[buildenv]` section in profile is only activated via `auto_use` (and otherwise, `buildenv` is no-op)?

or other [paragraph](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html?highlight=auto_use#the-environment-management):
```
By default, these generators are automatically declared in Conan 2.0 but you have to explicitly declare them in Conan 1.X otherwise you can set tools.env.virtualenv:auto_use=True in the global.conf.
```
okay, I can set `auto_use` within `global.conf`, but what's the effect of it? it's never actually explained...

last [place](https://docs.conan.io/en/latest/reference/conanfile/tools/env/virtualrunenv.html?highlight=auto_use) is:
```
# VirtualBuildEnv and VirtualRunEnv can be avoided if "tools.env.virtualenv:auto_use" is defined
    # (it will be defined in Conan 2.0)
```
does it mean `auto_use` also affects on `generators` property, always appending `VirtualBuildEnv` and `VirtualRunEnv` to the list? e.g. `generators = "cmake"` actually means `generators = "cmake", "VirtualBuildEnv", "VirtualRunEnv"` if `auto_use=True`?

**Comment by memsharded** [comment]
I think the paragraphs you pasted above were clear enough, and like the first one is even highlighted with an ``important`` notice:

> The use of this ``[buildenv]`` section requires using the ``VirtualBuildEnv`` generator in your recipe,
    or putting the configuration ``tools.env.virtualenv:auto_use=True`` in your profile.

That means that either you declare the ``VirtualBuildEnv`` generator in your recipe explicitly, or you do it implicitly with the ``auto_use`` configuration.  What is exactly not clear about that note? Do you want to explicitly add your line with ``generators = ...`` there?

**Comment by SSE4** [comment]
> That means that either you declare the `VirtualBuildEnv` generator in your recipe explicitly, or you do it implicitly with the `auto_use` configuration. What is exactly not clear about that note? Do you want to explicitly add your line with `generators = ...` there?

it's not fully clear what happens with `buildenv` if none of the conditions mentioned satisfied, is it just silently ignored?
anyway, it would be better if `auto_use` had its own section describing effects of True/False values, it's pretty hard to deduce it now from these pieces without looking at code. like the following:

auto_use = True:
- `[buildenv]` profile section parsing is activated
- both `VirtualBuildEnv` and `VirtualRunEnv` appended to the `generators` attribute of the conan file (e.g. `generators = "cmake"` actually means `generators = "cmake", "VirtualRunEnv", "VirtualRunEnv"`)

auto_use = False:
- `[buildenv]` profile section is silently ignored with no error, if `VirtualBuildEnv` generator wasn't defined in recipe

and as we can see from this issue, there is a third side effect of `auto_use` - it causes an empty `generate` method to behave differently from recipe with no `generate` method at all.
