### ISSUE TITLE
[question] When to specify which `compiler.cppstd` settings for MSVC compiler?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12387]
### Problem Descriptions

Recently, I tried to redesign the implementation of `conan_cmake_autodetect()` for MSVC compiler in [cmake-conan](https://github.com/conan-io/cmake-conan). It is because `msvc` will deprecate `Visual Studio` in Conan 2.X according to the [documentation](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html#msvc). And I noticed that there is a required settings, called `compiler.cppstd`. If we don't specify this settings, then Conan will report an error like this:

```cmd
ERROR: fmt/6.1.2: 'settings.compiler.cppstd' value not defined
```

However, I was wondering that:

1. What is the corresponding CMake variable to `compiler.cppstd` settings? Is it [CMAKE_CXX_STANDARD](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html)?
2. If the **1st** question is **YES**, then what should we do if this variable is **EMPTY**?
3. If the **1st** question is **NO**, then what is it or how to specify the suitable `compiler.cppstd` for MSVC compiler?
4. Why does `compiler.cppstd` miss **C++11** Standard for MSVC compiler?

![image](https://user-images.githubusercontent.com/71438617/197580339-bacf818e-6eb1-4ab2-ab7b-fbf01fa97911.png)

**Comment by memsharded** [comment]
> What is the corresponding CMake variable to compiler.cppstd settings? Is it [CMAKE_CXX_STANDARD]
(https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html)?

Yes

> If the 1st question is YES, then what should we do if this variable is EMPTY?

This variable shouldn't be empty. If the ``compiler.cppstd`` doesnt exist (can be removed for C packages), it will not exist at all, not being defined as empty


> Why does compiler.cppstd miss C++11 Standard for MSVC compiler?

Because it is not a supported setting for MSVC compiler. If you check their documentation, or from the IDE, C++11 is not a standard that can be defined for MSVC.

**Comment by hwhsu1231** [comment]
> This variable shouldn't be empty. If the `compiler.cppstd` doesnt exist (can be removed for C packages), it will not exist at all, not being defined as empty

@memsharded 

The problem is that it seems fine when `CMAKE_CXX_STANDARD` is **EMPTY** in the CMakeLists.txt.

The follwing is the example CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.9)
project(FormatOutput CXX)
message("CMAKE_CXX_STANDARD_REQUIRED = ${CMAKE_CXX_STANDARD_REQUIRED}")
message("CMAKE_CXX_STANDARD = ${CMAKE_CXX_STANDARD}")
```

The following is its Terminal Log:

<details><summary>Click to expand</summary>

```cmd
F:\GitRepo\cmake-conan>md build

F:\GitRepo\cmake-conan>cd build

F:\GitRepo\cmake-conan\build>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_CXX_STANDARD_REQUIRED = 
CMAKE_CXX_STANDARD =
-- Configuring done
-- Generating done
-- Build files have been written to: F:/GitRepo/cmake-conan/build
```

</details>

In that case, how to specify `compiler.cppstd` for MSVC compiler?

**Comment by memsharded** [comment]
If you are using VS>= 2015, the default is already c++14, so it should be ``compiler.cppstd=14``

**Comment by hwhsu1231** [comment]
So your suggestion is to specify a **DEFAULT** C++ standard if `CMAKE_CXX_STANDARD` is not given?

For example:

```cmake
if(CMAKE_CXX_STANDARD)
  set(_CONAN_SETTING_COMPILER_CPPSTD ${CMAKE_CXX_STANDARD})
else()
  if(NOT MSVC_VERSION VERSION_LESS 1900)
    # VS >= 2015, specify C++14 standard by default.
    set(_CONAN_SETTING_COMPILER_CPPSTD 14)
  endif()
endif()
```

Then what about VS < 2015?

**Comment by memsharded** [comment]
> So your suggestion is to specify a DEFAULT C++ standard if CMAKE_CXX_STANDARD is not given?

It is not that CMAKE_CXX_STANDARD is not given. It is the ``CMakeToolchain`` that defines this variable.
If you are talking about cmake-conan integration, that is a different story. The cmake-conan integration should definitely define ``compiler.cppstd=14``, even if the ``CMAKE_CXX_STANDARD`` is not defined, because that defines the binary compatibility, and becomes part of the ``package_id``. 


> Then what about VS < 2015?

Those use cppstd=98 by default

**Comment by hwhsu1231** [comment]
So is the following mechanism suitable?

```cmake
if(CMAKE_CXX_STANDARD)
    set(_CONAN_SETTING_COMPILER_CPPSTD ${CMAKE_CXX_STANDARD})
else()
    if(MSVC_VERSION VERSION_LESS 1900)
        # VS < 2015, specify C++98 standard by default.
        set(_CONAN_SETTING_COMPILER_CPPSTD 98)
    else()
        # VS >= 2015, specify C++14 standard by default.
        set(_CONAN_SETTING_COMPILER_CPPSTD 14)
    endif()
endif()
```

**Comment by memsharded** [comment]
Yes, looks good

**Comment by hwhsu1231** [comment]
> It is not that CMAKE_CXX_STANDARD is not given. It is the `CMakeToolchain` that defines this variable.

Do you mean that `--settings compiler.cppstd=14` will make `CMakeToolchain` generate the `conan_toolchain.cmake`, which has the following line:

```cmake
set(CMAKE_CXX_STANDARD 14)
```

**Comment by memsharded** [comment]
> Do you mean that --settings compiler.cppstd=14 will make CMakeToolchain generate the conan_toolchain.cmake, which has the following line:

Yes, exactly

**Comment by hwhsu1231** [comment]
I think this question is solved, so I'll close it.
