### ISSUE TITLE
[question] How can I provide a CMAKE FLAG in recipe (not option), for providing diffrent sdk

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#12389]
I need to provide two kinds of API implementation in library A.so and library B.so, so I need to provide a flag so that I can use this flag to decide which library to link when I link those libraries.

**Comment by jcar87** [comment]
Hi @Tumb1eweed  - how would you feed this flag to CMake _without_ using Conan? for example when building this manually yourself.

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed - how would you feed this flag to CMake _without_ using Conan? for example when building this manually yourself.

But I need to provide two kinds of API in this conan pacakge.
To be specific, library A provides a simple network communication, and librarys B provide a more complex communication, for different kinds of usage, I need to provide those libraries both, but I can't just package into conan package all, in that case linking "target::target" doesn't know which library to link, so I need to provide a flag to distinct two library when linking.

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

Sorry this was not followed up back then.

The way to pass information to the CMake build is via variables, which can be defined in the CMakeToolchain:
- https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#customization

Those configurations of course can also be conditional, like applied depending on some ``self.options`` values.

**Comment by memsharded** [comment]
I am closing this ticket as outdated, but please re-open or create a new ticket if you have any further question. Thanks for your feedback!
