### ISSUE TITLE
[feature] filter what is built by --build=missing and --build=outdated

### ISSUE THREAD

**Issue by heili77** [conan-io/conan#12381]
Currently there is only an exclusion feature for `--build=missing` and/or `--build=outdated` with pattern `--build=!pattern`.

In my case I want to limit the built packages to a specific list of users. `--build=pattern` is not applicable, as the matching packages are built no matter if the package is missing or outdated. With the exclusion pattern I would need to list all possible users in my project which are not in my list of allowed users.

So I would request a feature for filtering the list of packages to be built by pattern. 
I want to use it like this:
```
conan install . --build=outdated --build=missing --build_filter=*/*@user1/* --build_filter=*/*@user2/* --build_filter=*/*@user3/*
```
or maybe with regex
```
conan install . --build=outdated --build=missing --build_filter=.*/.*@(user1|user2|user3)/.* 
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @heili77 

Yes, this has already been implemented in Conan 2, with ``--build=missing:<pattern>`` syntax. If you want to start testing, it we have already released several betas, and it is getting very close for final release.

**Comment by memsharded** [comment]
This is already included in the released betas, closing.
