### ISSUE TITLE
ERROR: <some package> Cannot load recipe. . . ImportError: cannot import name 'export_conandata_patches'

### ISSUE THREAD

**Issue by gazzatav** [conan-io/conan#12392]
### Environment Details
  * Ubuntu 18.04
  * gcc (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0
  * Conan 1.53.3
  * Python 3.6.9
## Config:

```
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = 50                  # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
default_profile = default
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO
request_timeout = 60                  # environment CONAN_REQUEST_TIMEOUT (seconds)
default_package_id_mode = semver_direct_mode # environment CONAN_DEFAULT_PACKAGE_ID_MODE
revisions_enabled = True

[storage]
path = /home/gary/Repo/ConanData

[proxies]

[hooks]
attribute_checker
```
## Profile:

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-11
CXX=/usr/bin/g++-11
```

### Steps to reproduce (Include if Applicable)
conan install -r conanio bzip2/1.0.6@
OR
conan install -r conanio bzip2/1.0.8@
OR
conan install  -r conanio zlib/1.2.12@
OR
conan install -pr=c++20 -r conanio poco/1.12.2@ (fails because of zlib/1.2.12)
e.t.c.
### Logs (Executed commands with output) (Include/Attach if Applicable)

```
→ conan install -pr=c++20 -r conanio zlib/1.2.12@
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-11
CXX=/usr/bin/g++-11
ERROR: zlib/1.2.12: Cannot load recipe.
Error loading conanfile at '/home/gary/Repo/ConanData/zlib/1.2.12/_/_/export/conanfile.py': Unable to load conanfile in /home/gary/Repo/ConanData/zlib/1.2.12/_/_/export/conanfile.py
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gary/Repo/ConanData/zlib/1.2.12/_/_/export/conanfile.py", line 3, in <module>
    from conan.tools.files import apply_conandata_patches, export_conandata_patches, get, load, replace_in_file, save
ImportError: cannot import name 'export_conandata_patches'

```
I have tried Conan version 1.52 and 1.53 with no success so I went back to 1.51.3.  This seems to happen with packages that many other packages depend on. I'm not a python expert and do not understand what it is trying to tell me (if anything).  I checked in my ConanData directory for the failed packages and  there is a conanfile.py in their respective export directories, so I do not undersand the error where it says `Error loading conanfile at '/home/gary/Repo/ConanData/zlib/1.2.12/_/_/export/conanfile.py`.  

This problem means I cannot rebuild older projects with different settings from before.  It fails with my default profile (gcc-7) or the newer.

**Comment by czoido** [comment]
Hi @gazzatav,
Thanks for reporting. The problem seems to be that the Conan version you are using does not support `export_conandata_patches` That tool was introduced in Conan 1.52.0 so if you are using Conan>=1.52 it should work. A couple of questions:

- Did you install Conan via pip or any other install method?
- Can you verify before running `conan install` that `conan --version` returns a version>=1.52?

Thanks a lot.

**Comment by jcar87** [comment]
HI @gazzatav 

I would first advise to try with a conan installed inside a virtual environment:
```
python3 -m venv conan-venv
source conan-venv/bin/activate
pip install pip wheel --upgrade
pip install conan
```
and then try the commands again. Alternatively you can launch the python interpreter in this environment and simply run the following in the prompt:
```
from conan.tools.files import apply_conandata_patches, export_conandata_patches, get, load, replace_in_file, save
```

If that succeeds without errors, there's probably something corrupted about your Conan installation. If that is the case, I would advise trying (outside a virtual environment, or within the same virtual environment you've been using):
```
grep -m1 "" $(which conan)
```

This will print the python3 interpreter used when you invoke `conan` - if you launch that as a prompt, and try to run the import line above, you should be able to see the error you are getting in the recipes. This would be indicative of a corrupted installation if `conan--version` reports a version greater than 1.52.

**Comment by gazzatav** [comment]
@czoido Hi and thanks for responding.  I already tried upgrading to 1.52 and 1.53 with but with both of those I had the crashing version command so I rolled back.  I used the command: `sudo python3 -m pip install -U conan` then rolled back to 1.52 with `sudo python3 -m pip install conan==1.52` and finally back to 1.51.3.  You'll see I've used sudo and I don't know if that's a good thing with python, opinions online seem to vary.

Currently:

```
conan --version
Conan version 1.51.3

grep -m1 "" $(which conan)
#!/usr/bin/python3
```

**Comment by gazzatav** [comment]
@jcar87 Hi, thanks for your suggestions.  I tried the first one and it failed like this:

```
python3 -m venv conan-venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/gary/conan-venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

So I did what it told me and ran the commands you gave, the result is success as below so what do I do to make this permanent?  Do I need to uninstall some stuff and start again?

```

conan install -pr c++20 -r conanio bzip2/1.0.6@
WARN: Migration: Updating settings.yml
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-11
CXX=/usr/bin/g++-11
Installing package: bzip2/1.0.6
Requirements
    bzip2/1.0.6 from 'conanio' - Cache
Packages
    bzip2/1.0.6:c32092bf4d4bb47cf962af898e02823f499b017e - Download

Installing (downloading, building) binaries...
bzip2/1.0.6: Retrieving package c32092bf4d4bb47cf962af898e02823f499b017e from remote 'conanio' 
Downloading conanmanifest.txt completed [0.32k]                                          
Downloading conaninfo.txt completed [0.44k]                                              
Downloading conan_package.tgz completed [97.75k]                                         
Decompressing conan_package.tgz completed [0.00k]                                        
bzip2/1.0.6: Package installed c32092bf4d4bb47cf962af898e02823f499b017e
bzip2/1.0.6: Downloaded package revision 231ef9539efbb425c8c87d01b89ed021
Aggregating env generators
○ glook3 in ~ 
→ conan --version
Conan version 1.53.0
```

**Comment by uilianries** [comment]
@gazzatav I recommend you using [pyenv](https://github.com/pyenv/pyenv) if possible. It's very easy to [install](https://github.com/pyenv/pyenv-installer#install) and much more flexible than using the native python offered by Ubuntu.

Also, to be sure about which python x conan you are using, you can try:

    python3 -m conans.conan install -r conanio bzip2/1.0.6@
    
Passing a target module, instead calling `conan` directly, you guarantee which Python is related.

**Comment by gazzatav** [comment]
@uilianries thank you for the great advice about using pyenv.  I was a bit reluctant to try it at first, hence the delay in my reply. When I had read through it, realised how it works and that it didn't **depend** on python, I gave it a go and it seems to be generally a really good way to control python installations and not only for conan.
In an unrelated task I'm setting up a toolchain for baremetal compilation, which has a dependency on a version of python which is not on my system, so it looks like it will help with that as well.

**Comment by memsharded** [comment]
> When I had read through it, realised how it works and that it didn't depend on python, I gave it a go and it seems to be generally a really good way to control python installations and not only for conan.
In an unrelated task I'm setting up a toolchain for baremetal compilation, which has a dependency on a version of python which is not on my system, so it looks like it will help with that as well.

Yes, exactly, using pyenv (or other virtualenv tools) is extremely recommended for the installation and usage of any python-based tool, not just Conan, because the dependency management in Python is not designed for installing multiple different things (tools, etc) in the same Python installation.

If this finally solves the question maybe we can close this issue? Thanks!

**Comment by gazzatav** [comment]
@memsharded Thanks, yes, closing - just wanted to leave it open a while in case of any other useful comments.
