### ISSUE TITLE
[feature] Add a 'tool_options' section to conanfile

### ISSUE THREAD

**Issue by AlexRamallo** [conan-io/conan#12394]
As a follow on from [this discussion](https://github.com/conan-io/conan-center-index/issues/13708), I think it'd be helpful to be able to specify separate options for the build/host profile from a conanfile without resorting to separate profiles.

If you have a conanfile like this:
```
[requires]
flatbuffers/2.0.8
[tool_requires]
flatbuffers/2.0.8
[options]
flatbuffers:shared=True
```
It's unclear which package is affected by that option. ~~Currently, the only way to add separate options (unless I'm mistaken?) is to add them to profiles.~~

I think since dual profiles are the new normal in Conan, either a `tool_options` (or similar) feature should be supported in conanfile.txt/py, or the `options` section should be removed entirely, and options should only be specified in profiles.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AlexRamallo** [comment]
After some further testing, it seems I was a bit premature in assuming the dual profile trick works. It seems (at least in Conan 1.53.0) that Conan completely ignores the options in your build profile. It does display the options in your build profile (when you run `conan install` and it prints the profiles), but it ignores them, and doesn't even throw up an error if you list an invalid option.

So at the moment there doesn't appear to be any way to do this, or am I mistaken?

**Comment by SpaceIm** [comment]
quite similar issue (but in command line): https://github.com/conan-io/conan/issues/10425

**Comment by memsharded** [comment]
This was solved some time ago in Conan 2:

- ``default_build_options`` allow defining options only for tool-requires
- ``self.tool_requires(..., options=....)`` allow to define options

Closing as solved, please create new tickets against latest Conan 2.X if necessary, thanks for the feedback.
