### ISSUE TITLE
Are hyphened (1.2.23-4) package versions supported in finding compilation runtime dependants?

### ISSUE THREAD

**Issue by whitefluffypenguin** [conan-io/conan#12395]
Hi there,

Are hyphened (1.2.23-4) package versions supported in finding compilation runtime dependants?

**Comment by czoido** [comment]
Hi @whitefluffypenguin,

Thanks for the question. If you are using version ranges Conan will not take into account the pre-release version unless you add the include_prerelease option like:

```
[>1.0 <2.1, include_prerelease=True]            # Would e.g. accept "1.2.23-4" as match
```
Please check the Conan documentation [about version ranges](https://docs.conan.io/en/latest/versioning/version_ranges.html?highlight=include_prerelease#version-ranges) for more information.

**Comment by whitefluffypenguin** [comment]
Thank you - trying!

**Comment by czoido** [comment]
Hi @whitefluffypenguin,
I'm closing this as it seems solved. Please feel free to reopen if you have more questions.
Thanks!
