### ISSUE TITLE
[bug] 301 Moved Permanently in response to conan upload's PUT requests results in a 409 Conflict for URL

### ISSUE THREAD

**Issue by bloxgate** [conan-io/conan#12396]
**Update:** The below happens when a 301 redirect is returned in response to the PUT requests for the files being uploaded. Changing the conan remote's URL to match the one in the 301 allows the upload to proceed normally.

When uploading a package from Ubuntu a 409 Conflict for URL is received when the conanmanifest.txt file is uploaded. Copying the package to a MacOS environment with the same version of conan and an identical conan.conf allows the package to be uploaded just fine after deleting whatever managed to make it before the previous failure off of artifactory.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.04 / MacOS Monterey 12.5.1
  * Compiler+version: GCC 11.3.0
  * Conan version: 1.51.0 (Ubuntu & Mac). I've also separately checked that the issue happens when 1.53.0 is installed on the Ubuntu machine
  * Python version: 3.8.15 & 3.10.6 (Ubuntu) / 3.8.13 (MacOS)

This is a relatively fresh Ubuntu install (installed last night), that I've since installed Qt 6, build-essentials, git, and cmake on. There are already zstd/1.5.0 packages for Windows and MacOS in the artifactory I'm using.

I've attached a copy of my profile.
[profile_ubuntu22.04.txt](https://github.com/conan-io/conan/files/9862276/profile_ubuntu22.04.txt)

### Steps to reproduce (Include if Applicable)
- Run Python Black on zstd/1.5.0's conanfile.py
- Create a package for `zstd/1.5.0` 
- Run `conan upload zstd/1.5.0@ -r ... --all`
- Recieve a 409 error
- Delete whatever half uploaded mess made it to Artifactory
- Copy ~/.conan/data/zstd to a MacOS system
- Run `conan upload zstd/1.5.0@ -r ... --all`
- Package is uploaded successfully

### Logs (Executed commands with output) (Include/Attach if Applicable)

(References to my employer have been replaced with `...`) Ubuntu: 
```
conan create /home/gregory/.../src_build/zstd/1.5.0/conanfile.py zstd/1.5.0@_/_ --profile /home/gregory/.../_util/conan/profile_ubuntu22.04 --build missing 
Exporting package recipe
zstd/1.5.0 exports: File 'conandata.yml' found. Exporting it...
zstd/1.5.0 exports: Copied 1 '.yml' file: conandata.yml
zstd/1.5.0 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
zstd/1.5.0 exports_sources: Copied 1 '.patch' file: 0001-cmake-install-dll.patch
zstd/1.5.0: The stored package has not changed
zstd/1.5.0: Using the exported files summary hash as the recipe revision: 798e1a11cf63a9f4ce1a389b64d72de4 
zstd/1.5.0: Exported revision: 798e1a11cf63a9f4ce1a389b64d72de4
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: zstd/1.5.0
Requirements
    zstd/1.5.0 from '...' - Cache
Packages
    zstd/1.5.0:dfbe50feef7f3c6223a476cd5aeadb687084a646 - Cache

Installing (downloading, building) binaries...
zstd/1.5.0: Already installed!
conan upload zstd/1.5.0@ -r ... --all
Uploading to remote '...':
Uploading zstd/1.5.0 to remote '...'                                         
Compressing conan_export.tgz completed [1 files]                                         
Compressing conan_sources.tgz completed [2 files]                                        
Recipe is up to date, upload skipped
Uploading package 1/1: dfbe50feef7f3c6223a476cd5aeadb687084a646 to '...'     
Uploaded conanmanifest.txt -> zstd/1.5.0:dfbe [0.31k]                                    
ERROR: 409 Client Error: Conflict for url: https://....jfrog.io/artifactory/api/conan/.../v2/conans/zstd/1.5.0/_/_/revisions/798e1a11cf63a9f4ce1a389b64d72de4/packages/dfbe50feef7f3c6223a476cd5aeadb687084a646/revisions/71464c91c8fbe9533d27297fc7b82ef1/files/conanmanifest.txt
Waiting 5 seconds to retry...
Uploaded conanmanifest.txt -> zstd/1.5.0:dfbe [0.31k]                                    
ERROR: 
Error uploading file: conanmanifest.txt, '409 Client Error: Conflict for url: https://....jfrog.io/artifactory/api/conan/.../v2/conans/zstd/1.5.0/_/_/revisions/798e1a11cf63a9f4ce1a389b64d72de4/packages/dfbe50feef7f3c6223a476cd5aeadb687084a646/revisions/71464c91c8fbe9533d27297fc7b82ef1/files/conanmanifest.txt'
ERROR: zstd/1.5.0:dfbe50feef7f3c6223a476cd5aeadb687084a646: Upload package to '...' failed: Execute upload again to retry upload the failed files: conanmanifest.txt. [Remote: ...]

ERROR: Errors uploading some packages

```

**Comment by bloxgate** [comment]
After a bit more digging, I've found the following error in the artifactory logs:
```
2022-10-25T18:31:04.107Z [jfrt ] [WARN ] [bc52bd7180613b14] [.r.ArtifactoryResponseBase:144] [http-nio-8443-exec-6] - Sending HTTP error code 409: Checksum policy 'LocalRepoChecksumPolicy: CLIENT' rejected the artifact '...:_/zstd/1.5.0/_/798e1a11cf63a9f4ce1a389b64d72de4/package/dfbe50feef7f3c6223a476cd5aeadb687084a646/71464c91c8fbe9533d27297fc7b82ef1/conanmanifest.txt'. Checksums info: ChecksumsInfo{checksums={SHA-1=ChecksumInfo{type=SHA-1, original='13eeda26c45f26c8024ca7cf6d5742a1d32240fe', actual='da39a3ee5e6b4b0d3255bfef95601890afd80709'}, MD5=ChecksumInfo{type=MD5, original='null', actual='d41d8cd98f00b204e9800998ecf8427e'}, SHA-256=ChecksumInfo{type=SHA-256, original='null', actual='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'}}}
```

It appears its not happy with the SHA-1 sum of `13eeda26c45f26c8024ca7cf6d5742a1d32240fe`. However I'm quite confused as to why as this is the same sum that the file has on the MacOS system:
#### MacOS
```
> shasum -a 1 conanmanifest.txt
13eeda26c45f26c8024ca7cf6d5742a1d32240fe  conanmanifest.txt
```

#### Ubuntu
```
> sha1sum conanmanifest.txt
13eeda26c45f26c8024ca7cf6d5742a1d32240fe  conanmanifest.txt
```

I can further see that there _is_ actually a conanmanifest.txt file uploaded after it "failed" that has the same sums as my local copies, even though it claimed to have failed:
![image](https://user-images.githubusercontent.com/2079324/197858945-78a1b97b-0e6c-407b-804e-4966eac14d1f.png)

**Update:**
It appears that the "actual" hash (`da39a3ee5e6b4b0d3255bfef95601890afd80709`) being calculated on artifactory is the hash of an empty file, as seen in this example that produces a matching hash:
```
>>> import hashlib
>>> h = hashlib.sha1()
>>> h.update(b'')
>>> print(h.hexdigest())
da39a3ee5e6b4b0d3255bfef95601890afd80709
```

I'm guessing that something isn't being uploaded right

**Comment by ivanmilov** [comment]
I got the same issue today.

OS: Sonoma 14.6.1
Conan version: 2.7.0
Python version: 3.12.5



```
❯ mkdir dummy_pkg
❯ cd dummy_pkg
❯ conan new cmake_lib -d name=dummy_lib -d version=0.0.1
File saved: CMakeLists.txt
File saved: conanfile.py
File saved: include/dummy_lib.h
File saved: src/dummy_lib.cpp
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/src/example.cpp

❯ conan export .

======== Exporting recipe to the cache ========
dummy_lib/0.0.1: Exporting package recipe: /Users/dev/dummy_pkg/conanfile.py
dummy_lib/0.0.1: Copied 1 '.py' file: conanfile.py
dummy_lib/0.0.1: Copied 1 '.txt' file: CMakeLists.txt
dummy_lib/0.0.1: Copied 1 '.h' file: dummy_lib.h
dummy_lib/0.0.1: Copied 1 '.cpp' file: dummy_lib.cpp
dummy_lib/0.0.1: Exported to cache folder: /Users/dev/.conan2/p/dummyef5e882e2caba/e
dummy_lib/0.0.1: Exported: dummy_lib/0.0.1#7e9876241a2dd7a15f537ae4b499c974 (2024-09-02 14:05:04 UTC)

❯ conan upload dummy_lib -r=<MyRemote> --only-recipe

Found 1 pkg/version recipes matching dummy_lib in local cache

======== Uploading to remote <MyRemote> ========

-------- Checking server existing packages --------
dummy_lib/0.0.1: Checking which revisions exist in the remote server

-------- Preparing artifacts for upload --------
dummy_lib/0.0.1: Compressing conan_sources.tgz

-------- Uploading artifacts --------
dummy_lib/0.0.1: Uploading recipe 'dummy_lib/0.0.1#7e9876241a2dd7a15f537ae4b499c974' (3.0KB)
WARN: network: 409 Client Error: Conflict for url: https://artifactory.<MyServer>>.com:443/artifactory/api/conan/<MyRemote>/v2/conans/dummy_lib/0.0.1/_/_/revisions/7e9876241a2dd7a15f537ae4b499c974/files/conan_sources.tgz
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conan_sources.tgz, '409 Client Error: Conflict for url: https://artifactory.<MyServer>>.com:443/artifactory/api/conan/<MyRemote>/v2/conans/dummy_lib/0.0.1/_/_/revisions/7e9876241a2dd7a15f537ae4b499c974/files/conan_sources.tgz'
WARN: network: 409 Client Error: Conflict for url: https://artifactory.<MyServer>>.com:443/artifactory/api/conan/<MyRemote>/v2/conans/dummy_lib/0.0.1/_/_/revisions/7e9876241a2dd7a15f537ae4b499c974/files/conanfile.py
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conanfile.py, '409 Client Error: Conflict for url: https://artifactory.<MyServer>>.com:443/artifactory/api/conan/<MyRemote>/v2/conans/dummy_lib/0.0.1/_/_/revisions/7e9876241a2dd7a15f537ae4b499c974/files/conanfile.py'
WARN: network: 409 Client Error: Conflict for url: https://artifactory.<MyServer>>.com:443/artifactory/api/conan/<MyRemote>/v2/conans/dummy_lib/0.0.1/_/_/revisions/7e9876241a2dd7a15f537ae4b499c974/files/conanmanifest.txt
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conanmanifest.txt, '409 Client Error: Conflict for url: https://artifactory.<MyServer>>.com:443/artifactory/api/conan/<MyRemote>/v2/conans/dummy_lib/0.0.1/_/_/revisions/7e9876241a2dd7a15f537ae4b499c974/files/conanmanifest.txt'
ERROR: Execute upload again to retry upload the failed files: conan_sources.tgz, conanfile.py, conanmanifest.txt. [Remote: <MyRemote>]
```

**Comment by memsharded** [comment]
Hi @bloxgate 

Sorry this was not followed up back then.

Thanks @ivanmilov for the feedback.

I have no idea what could be happening. I guess this is some special configuration on the server side. If you are customers of JFrog cloud, it might be worth submitting a ticket to their support (and please follow up here)

Otherwise, it would be great if we could have a way to reproduce it locally, for example using the ArtifactoryCE from our downloads page: https://conan.io/downloads, and specifying any special configuration necessary to reproduce, like permissions, policies, or whatever other thing that changes from the default configuration.

**Comment by ivanmilov** [comment]
Hi [memsharded](https://github.com/memsharded)

I am sorry, I accidentally added my remote without `s` in `https`. Re-adding it with `secure` helped.

**Comment by memsharded** [comment]
That makes sense, thanks for the follow up @ivanmilov 

Any other feedback @bloxgate ?

**Comment by bloxgate** [comment]
Yes, that may have been what was happening for me as well. That would explain why I was getting a 301 Moved Permanently - JFrog cloud likely has a redirect from HTTP -> HTTPS setup.

It's been nearly 2 years and we haven't had this happen again since then, so I don't remember much on any additional details.

**Comment by memsharded** [comment]
Ok, thanks very much for the feedback.

Then it seems safe to close this ticket by now, if it happens again or if you have any other issue, please create a new ticket. Thanks!
