### ISSUE TITLE
Deal with different libstdc++, libc++ settings

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#124]
From https://github.com/conan-io/conan/issues/86, pointed out by @weatherhead99.
We are currently not handling (it can be done with custom options in packages, I guess) the different std libraries. This requires some analysis.

**Comment by weatherhead99** [comment]
couple of comments
1) on thinking about this further, it probably is a pretty rare case - I believe it's only relevant on Clang (GCC /MSVC can't use other standard libraries?), and then I think only on linux (I don't think there's stdlibc++ on OSX?) , so not sure it's worth bothering about beyond setups where it happens to become an issue

2) This could be the thin end of a very thick wedge - at what point does conan actually delegate knowing things to the buildsystem? If we want conan to know about all the compiler options, etc, then it basically becomes almost as complicated as the buildsystem itself.  I do think what's really needed is not necessarily reporting every possible option, but at least being very robust towards option changes, i.e. searching through a list of conan packages, I should at least know that there's a difference between a  clang/libc++ package and a clang/libstdc++ package, but not necessarily what that difference is, after all, we could end up needing to know the difference between a clang/libc++/address-sanitizer/PIC package and a clang/libstdc++/noPIC package, where does it end?

**Comment by mathieu** [comment]
Just some information, on MacOSX there is the same problem.
The way we handle this is by settings a minimum OS X version, clang then chooses the correct lib.
For exemple up to 10.7 there was only stdc++ and from 10.8 and up there are both stdc++ and c++ (the later required for c++0x and up).

This is how I handle it in zlib for example :
```
class ZlibConan(ConanFile):
    name = "zlib"
    version = "1.2.8"
    ZIP_FOLDER_NAME = "%s-%s" % (name, version)
    generators = "cmake"
    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "minosx": ['10.7', '10.8', '10.9', '10.10', '10.11']
    }
    default_options = "shared=False", "minosx=10.7"
    exports = ["CMakeLists.txt", "FindZLIB.cmake"]

[...]

        if self.settings.os == "Linux" or self.settings.os == "Macos":
            self.run("cd %s &&  mkdir _build" % self.ZIP_FOLDER_NAME)
            cd_build = "cd %s && cd _build" % self.ZIP_FOLDER_NAME
            arch = "-m32 " if self.settings.arch == "x86" else ""
            minosx = "-mmacosx-version-min=%s" % self.options.minosx if self.settings.os == "Macos" else ""
            self.run("cd %s && CFLAGS='%s %s -mstackrealign -fPIC -O3' ./configure" % (self.ZIP_FOLDER_NAME, arch, minosx))
            if self.settings.os == "Macos":

```

**Comment by memsharded** [comment]
I have commented in related issue https://github.com/conan-io/conan/issues/138 about a possible solution, please check it and give feedback if possible.
