### ISSUE TITLE
[question] Where is the `compiler.runtime_version=v143` settings of `clang` compiler?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12400]
### Problem Descriptions

According to the [article](https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html) of Conan Blog, ClangCL has its own profile settings:

> **vs_clang.profile**
> 
> ```ini
> [settings]
> os=Windows
> arch=x86_64
> build_type=Release
> compiler=clang
> compiler.version=14
> compiler.cppstd=gnu14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.runtime_version=v143
> 
> [conf]
> tools.env.virtualenv:auto_use=True
> tools.cmake.cmaketoolchain:generator=Visual Studio 17
> ```

However, I noticed that the profile uses `compiler.runtime_version=v143`, which **DOESN'T EXIST** in `settings.yml` (1.53.0).

![image](https://user-images.githubusercontent.com/71438617/198045860-95799898-ffb1-4948-b1e3-dc5cfa339fc9.png)

**Comment by jcar87** [comment]
Hi @hwhsu1231  - thanks for reporting this issue.

The `compiler.runtime_version` is defined in the `settings.yml` that comes with Conan 1.53.0:
```
    clang:
        version: ["3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "4.0",
                  "5.0", "6.0", "7.0", "7.1",
                  "8", "9", "10", "11", "12", "13", "14", "15", "16"]
        libcxx: [None, libstdc++, libstdc++11, libc++, c++_shared, c++_static]
        cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, 23, gnu23]
        runtime: [None, MD, MT, MTd, MDd, static, dynamic]
        runtime_type: [None, Debug, Release]
        runtime_version: [None, v140, v141, v142, v143]
```

Bear in mind that sometimes when you come from an earlier version of Conan where a `settings.yml` already existed in your Conan home directory, Conan will preserve the existing file instead of overwriting it if has any user modifications.

```
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: /Users/luisc/.conan/settings.yml.new
WARN: ****************************************
```

I would advise you to check if `settings.yml.new` exists and see if it has the correct settings, and then apply them to your settings.yml file.

**Comment by hwhsu1231** [comment]
@jcar87 Thansk for your replies.

However, I found that the `WARN: Migration: Updating settings.yml` message doesn't pop up after running `pip install conan --upgrade`. Even though I first **UNINSTALL** the Conan by running `pip uninstall conan` and then **REINSTALL** Conan by running `pip install conan --upgrade`, the message still doesn't pop up and the `settings.yml.new` isn't created.

Instead, there is an DEPRECATION message shows up:

```cmd
  DEPRECATION: conan is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for conan ... done
```

<details><summary>Click to expand Install Logs</summary>

```cmd
C:\Users\hwhsu1231>pip uninstall conan
Found existing installation: conan 1.53.0
Uninstalling conan-1.53.0:
  Would remove:
    c:\python\python310\lib\site-packages\conan-1.53.0-py3.10.egg-info
    c:\python\python310\lib\site-packages\conan\*
    c:\python\python310\lib\site-packages\conans\*
    c:\python\python310\scripts\conan-script.py
    c:\python\python310\scripts\conan.exe
    c:\python\python310\scripts\conan_build_info-script.py
    c:\python\python310\scripts\conan_build_info.exe
    c:\python\python310\scripts\conan_server-script.py
    c:\python\python310\scripts\conan_server.exe
Proceed (Y/n)? y
  Successfully uninstalled conan-1.53.0

C:\Users\hwhsu1231>pip install conan --upgrade
Collecting conan
  Using cached conan-1.53.0.tar.gz (772 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests<3.0.0,>=2.25 in c:\python\python310\lib\site-packages (from conan) (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.26.6 in c:\python\python310\lib\site-packages (from conan) (1.26.12)
Requirement already satisfied: colorama<0.5.0,>=0.3.3 in c:\python\python310\lib\site-packages (from conan) (0.4.5)
Requirement already satisfied: PyYAML<=6.0,>=3.11 in c:\python\python310\lib\site-packages (from conan) (6.0)
Requirement already satisfied: patch-ng<1.18,>=1.17.4 in c:\python\python310\lib\site-packages (from conan) (1.17.4)
Requirement already satisfied: fasteners>=0.14.1 in c:\python\python310\lib\site-packages (from conan) (0.18)
Requirement already satisfied: six<=1.16.0,>=1.10.0 in c:\python\python310\lib\site-packages (from conan) (1.16.0)
Requirement already satisfied: node-semver==0.6.1 in c:\python\python310\lib\site-packages (from conan) (0.6.1)
Requirement already satisfied: pygments<3.0,>=2.0 in c:\python\python310\lib\site-packages (from conan) (2.13.0)
Requirement already satisfied: tqdm<5,>=4.28.1 in c:\python\python310\lib\site-packages (from conan) (4.64.1)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\python\python310\lib\site-packages (from conan) (2.8.2)
Requirement already satisfied: bottle<0.13,>=0.12.8 in c:\python\python310\lib\site-packages (from conan) (0.12.23)
Requirement already satisfied: pluginbase>=0.5 in c:\python\python310\lib\site-packages (from conan) (1.0.1)
Requirement already satisfied: PyJWT<3.0.0,>=2.4.0 in c:\python\python310\lib\site-packages (from conan) (2.5.0)
Requirement already satisfied: Jinja2<4.0.0,>=3.0 in c:\python\python310\lib\site-packages (from conan) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python\python310\lib\site-packages (from Jinja2<4.0.0,>=3.0->conan) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\python\python310\lib\site-packages (from requests<3.0.0,>=2.25->conan) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\python310\lib\site-packages (from requests<3.0.0,>=2.25->conan) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\python\python310\lib\site-packages (from requests<3.0.0,>=2.25->conan) (2.1.1)
Installing collected packages: conan
  DEPRECATION: conan is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for conan ... done
Successfully installed conan-1.53.0
```

</details>

**Comment by hwhsu1231** [comment]
@jcar87 

And I noticed that the [Documentation](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html) doesn't have:

- `runtime_type`
- `runtime_version`

Either.

![image](https://user-images.githubusercontent.com/71438617/198180940-06c7ec5d-346c-490a-86a8-cb2777caaa83.png)

**Comment by hwhsu1231** [comment]
@jcar87 I found a way to regenerate the `settings.yml`.

- First, delete the `settings.yml` directly.
- Second, run the `conan config init` command.

And then, there will be a whole new `settings.yml`.

![image](https://user-images.githubusercontent.com/71438617/198455372-4523a027-dbe0-4439-ad07-4e35369079b8.png)

**Comment by hwhsu1231** [comment]
@jcar87 

What's your opinion about the method that I proposed?

> * First, delete the `settings.yml` directly.
> * Second, run the `conan config init` command.

Suppose that we accidentally deleted the `settings.yml.new` or this file wasn't created after upgrading Conan. What should we do to regenerate a suitable `settings.yml` for the current version? Is this method proper?

- If so, I think this issue can be closed.
- If not, what's the problem or side effect? 
- If there exist other methods, then what are they?

**Comment by jcar87** [comment]
Hi @hwhsu1231  - thank you for troubleshooting this further. I have opened an issue to look into the warning from pip, and we will be amending the documentation to reflect the current settings.

Please bear in mind that once you have Conan installed, `settings.yml` lives in your home directory (typically `~/.conan/`). These files are _not_ removed when doing a pip uninstall, and they are not modified by an upgrade or a reinstall. After an upgrade or a reinstall, in very limited circumstances the next time you run the `conan` command, Conan may perform some updates to the files in `~/.conan` if it deems it safe to do so, but generally Conan will not overwrite user configuration.

`conan config init` is the right solution to re-generate files that are missing. If you call it with `--force`, it will re-generate and overwrite all configuration files - this carries the risk of overwriting any custom configurations you may have had.

Will be closing this issue as it appears to be resolved, but feel free to reopen it if you have further related questions.
