### ISSUE TITLE
[question] Binary modes considering options (binary compatibility issue)

### ISSUE THREAD

**Issue by ngrodzitski** [conan-io/conan#12406]
I have a library `Foo` which has an option `XXX=True | False` this option affects a definition of some structs (technically we define a macro and then alternate content with `#ifdef-#else`) thus `Foo:XXX=True` and `Foo:XXX=False` version of a library are binary incompatible (and that is not something I can change any time soon). 

CI creates/uploads the package with default value for the option: `Foo:XXX=True`.

So the issue with it comes when something depends on `Foo`. Because binaries stored in the registry are considered according to semver (let's consider `settings = "os", "compiler", "build_type", "arch"` are fixed). So a potential library/application `Bar` that depends on `Foo/1.2.3` will get into troubles when running `conan install <params> -o Foo:XXX=False`  because Conan will find ready to go binaries for `Foo/1.2.3` and bring them to client. 

And here we have binaries from registry for `Foo/1.2.3` which were compiled with default option `Foo:XXX=True`, and a `Bar`  that is going to be compiled with `Foo:XXX=False` and will act like it has a binary different version of `Foo` .

My real usecase is a bit more complicated but I believe it maps to the model I've described.

The above can be avoided with (must be present for libs that depends on `Foo`):
```py
    def package_id(self):
        self.info.requires["Foo"].full_package_mode()
```

And what is even worse here is that when a lib depends on smth that depends on `Foo` then it should reintroduce `full_package_mode`:

```py
    def package_id(self):
        self.info.requires["SmthThatDependsOnFoo"].full_package_mode()
```

All this also implies that I can't have the benefits of semver in cases this dirty options is the same. 

For example, consider we have have the following libs: `Baz1` depending on `Foo/1.2.3`, `Baz2` depending on `Foo/1.2.5`, and `Baz3` depending on `Foo/1.3.0` (and pre-compiled binaries are in registry). Then we have an app which uses `Baz1,2,3`. And just take the latest version of `Foo`. If all `Baz` libs apply `full_package_mode` for Foo it means that when getting requirements for our app Conan will run rebuild for `Baz1` and `Baz2` which is unnecessary if `Foo:XXX=True` - default option.

Is there something like the following (or some approach that achieves the same affect):

```py
    def package_id(self):
        self.info.options["XXX"].adjusts_abi_mode()
```

which I can do in `Foo`'s conanfile and it would add an additional "dimension" when considering binaries, thus perfectly doing semver if option value is the same.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by ngrodzitski** [comment]
Asking the same question on slack I was suggested to use:
```py
def package_id():
    self.info.options = self.info.full_options
```

On which I found no documentation (and https://github.com/conan-io/docs/issues/1074 suggests that I indeed shouldn't have succeeded in it).

**Comment by memsharded** [comment]
Hi @ngrodzitski 

This is a complicated issue. I have one observation about:

> If all Baz libs apply full_package_mode for Foo it means that when getting requirements for our app Conan will run rebuild for Baz1 and Baz2 which is unnecessary if Foo:XXX=True - default option

The thing is that if you define ``full_package_mode`` dependency, and if the version of the dependency changes, even if the options is still the same value, the ``full_package_mode`` captures the version changes. It means that probably some header in the library changed between versions. It is not necessary that the option changes to have to recompiled the binary. Even for API compatible changes, it might be necessary to rebuild, this is what the ``full_package_mode`` means.

Maybe, if you want to control it that way, you can go further and try something in the line of:

```python
def package_id(self):
     if self.dependencies["foo"].options.myoption: 
            self.info.requires["foo"].full_package_mode()
     else:
            self.info.requires["foo"].minor_mode()
```

I'd also recommended watching: https://www.youtube.com/watch?v=kKGglzm5ous (all of it, but specially minute 59), to understand what will be the new ``package_id`` defaults and configuration for Conan 2.0

**Comment by memsharded** [comment]
Closing the ticket as responded/staled, please create new tickets for any further question, now that Conan 2 new binary model is the mainstream one.
