### ISSUE TITLE
Process end unexpectedly: build and packages kept dirty

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1240]
It seems that ``extractall`` function of python tarfile is not raising error with ``errorlevel`` == 1

**Comment by lasote** [comment]
Also we should need to control if the install process ends unexpectedly.

**Comment by lasote** [comment]
Removed from 0.23, not clear implementation and no very common situation. The implementation is not very clean, we should have a conan_dirty file in the package/build directory and only but the proxy.py module is using the condition of package folder existence to do things, even remove the package folder if wants to perform an update. Having a `packages/SHA.dirty_file` feels also dirty.

If `conan cleanup` command is implemented the user could clean the corrupted packages before or after an execution.

**Comment by jgsogo** [comment]
I think that this one will be solved once cached files contents are checked #3821. @lasote, closing this one?
