### ISSUE TITLE
[feature] conan.tools.cmake: cmake.test() lost output_on_failure option

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#12407]
The old conans.CMake had an [output_on_failure ](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#test) keyword argument that [set CTEST_OUTPUT_ON_FAILURE=1 in the envionment](https://github.com/conan-io/conan/blob/4cfd5af2f6e1ead79ce173aebf61b50dbe440a81/conans/client/build/cmake.py#L348), but the new 2.0 conan.tools.cmake.CMake helper has lost this feature.

Any chance of getting this back? Or (even better) something like a `[conf]tools.cmake.ctest:verbosity=quiet|verbose|failure` which could be set globally rather than in each recipe (i.e. on CI I'd always prefer failures to produce useful console output).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @puetzk,

Thanks a lot for the feedback. I think it could be useful to have control over this verbosity as a configuration so I'm adding this for consideration for the next release. I also wanted to suggest that you may use the `[buildenv]` section in the profile to set this environment variable easily, with a profile like this for example:

```
# testprofile
include(default)
[buildenv]
CTEST_OUTPUT_ON_FAILURE=1
```

And using the confs:
- `tools.build:skip_test` to control building the tests
- `tools.env.virtualenv:auto_use` to apply the buildenv automatically

So you can do this to get the output

```
conan create . -pr=./test_profile -c tools.env.virtualenv:auto_use=True -c tools.build:skip_test=False
```

**Comment by czoido** [comment]
Hi @puetzk,
After having a look at this we have concluded that this should be set with the [VirtualBuildEnv](https://docs.conan.io/en/latest/reference/conanfile/tools/env/virtualbuildenv.html) feature as it would be very challenging to manage all the CMake configurations inside Conan. I'm closing this but please feel free to reopen if you have any more questions.
Thanks a lot for the suggestion.

**Comment by puetzk** [comment]
OK. I hadn't thought of doing it through `[buildenv]`, since my mental model was "run `ctest`", which isn't a build step.

But, conan runs everything through `cmake --build <build_folder> --target test` rather than `ctest`. Given that, I can see how applying `[buildenv]` is consistent.
https://github.com/conan-io/conan/blob/5bf9aacedf9cc71c52ef548b079285715b51ba10/conan/tools/cmake/cmake.py#L149-L158
And setting `[buildenv]` is no harder than setting `[conf]`, so leaving no reason for conan to have a special way to set `CTEST_OUTPUT_ON_FAILURE`. And in any case there would be no way for it to implement `tools.cmake.ctest:verbosity=verbose` when going through `make test`.

**Comment by schwaerz** [comment]
looks like I have to use the following snippet in Conan2 to run the tests with the output on failure option set:

Is the `tools.environment_append()` really gone for good? Would have required less code.

```py
        environment = env.Environment()
        environment.define("CTEST_OUTPUT_ON_FAILURE", "1")
        envvars = environment.vars(self)
        with envvars.apply():
            cmake.test(cli_args=["--verbose"])
```
