### ISSUE TITLE
[question] can conan build everything from source only once?

### ISSUE THREAD

**Issue by Zvicii** [conan-io/conan#12414]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
-

I'm building an excutable for linux system with low version, so I have to build conan dependencies from source instead of downloading the binaries from conan center (so the `GLIBC` require is consistent with my local build env).

So I specify conan install with `--build` option. But it builds everything everytime.
Is it possible to specify `--build missing` while ignoring existing binaries from `conan center`?
So it only builds them the first time.

**Comment by memsharded** [comment]
Hi @Zvicii 

There is no way to achieve exactly that in the way you want to do it, via cli arguments.

But you give a very valuable hint about the reasons to achieve better binary compatibility.
If you want to do that, the best way is to explicitly model it:
- Define some custom setting, typically a subsetting of the ``os=Linux``, like ``glibc`` or ``distro`` or something like that: https://docs.conan.io/en/latest/extending/custom_settings.html#adding-new-sub-settings
- Define that value in your profiles or in command line: ``-s os.distro=mydistro``

This approach will guarantee:
- You will not be reusing the binaries from ConanCenter, but forcing the rebuild from source (--build=missing)
- They will not need to be rebuilt again from source with ``--build=missing``
- The best part: you can store your custom binaries you built in your own server (ArtifactoryCE is completely free to use, but you also have the conan_server, or the JFrog FreeTier), so you don't need to rebuild them from source again and again
- It will scale better for different linux distros that have different glibc versions, and it will be future-proof too
