### ISSUE TITLE
conan package manager project help

### ISSUE THREAD

**Issue by niuzhi** [conan-io/conan#12410]
Hello, I am currently learning to use conan as a C/C++ package manager, and I have completed the study of the official tutorial. Currently, I want to use a complex project using conan as a package management to facilitate my learning. Can the community help provide some open source The project of the Conan package manager, I searched for a long time in github, but did not find a suitable project. thanks

**Comment by czoido** [comment]
Hi @niuzhi,

Welcome to the Conan community!

In case you have not seen it, there's a Conan series in the JFrog Academy: https://academy.jfrog.com/path/conan some parts are a bit obsolete but most of the concepts are still valid
Also, although is still a work in progress we have a whole new tutorial section focused in 2.0: https://docs.conan.io/en/2.0/tutorial.html
The examples repo also could be useful: https://github.com/conan-io/examples (this is for 1.X)
We also have a dedicated examples repo for 2.0: https://github.com/conan-io/examples2 (also work in progress)

And a couple of projects using Conan, they are not super-complex but may help to understand some concepts:

- https://github.com/froglets/flappy-frog
- https://github.com/czoido/tensorflow-cpp-conan-example
- https://github.com/czoido/imgui-opencv

Please, do not hesitate to ask any questions you have.

**Comment by AbrilRBS** [comment]
Closing because we did not hear back from you - If anyone needs help, feel free to open an issue/contact us in slack, we are always happy to help!
