### ISSUE TITLE
[bug] PATH for build dependencies is not appended

### ISSUE THREAD

**Issue by jasuramme** [conan-io/conan#12415]
Conan failing on installation with error NASM not found

It seems that in some cases conan doesn't add build tools folder to the PATH variable. I submitted one case how to reproduce it. For some reason we faced that in azure cloud running on azure agent we have the same issue calling following command as a script, but everything works fine when you run it with bash shell inside azure job...
Hopefully it is the same case with described below.

### Environment Details (include every applicable attribute)
  * OS Name: Microsoft Windows 10 Pro 10.0.19044 N/A Build 19044
  * Compiler+version: MSVC 19.29.30146 for x64
  * Conan version: 1.53.0
  * Python version: v3.10.8:aaaf517,

### Steps to reproduce (Include if Applicable)
Conan file contents:

[requires]
zlib/1.2.12
openssl/1.1.1q
jwt-cpp/0.6.0
picojson/cci.20210117
gtest/1.12.1
libcurl/7.77.0
minizip-ng/3.0.2

[build_requires]

[generators]
cmake_find_package_multi

[options]

- place conanfile.txt to the current folder
- pip install conan
- mkdir tmp
- cd tmp
- conan install ../ --build missing -s os=Windows -s os_build=Windows -s arch=x86_64 -s arch_build=x86_64 -s compiler="Visual Studio" -s compiler.version=16 -s compiler.runtime=MD -s build_type=RelWithDebInfo --generator cmake_find_package_multi

### Logs (Executed commands with output) (Include/Attach if Applicable)
$ conan install ../ --build missing -s os=Windows -s os_build=Windows -s arch=x86_64 -s arch_build=x86_64 -s compiler="Visual Studio" -s compiler.version=16 -s compiler.runtime=MD -s build_type=RelWithDebInfo --generator cmake_find_package_multi

...

nasm/2.15.05: Created package revision b694b9c2a16133545e18358971a7a245
openssl/1.1.1q: Applying build-requirement: strawberryperl/5.30.0.1
openssl/1.1.1q: Applying build-requirement: nasm/2.15.05
Downloading conan_sources.tgz
openssl/1.1.1q: Configuring sources in C:\Users\user_user\.conan\data\openssl\1.1.1q\_\_\source
openssl/1.1.1q:
openssl/1.1.1q: Copying sources to build folder
openssl/1.1.1q: Building your package in C:\Users\user_user\.conan\data\openssl\1.1.1q\_\_\build\75ed07303f056424be45ffb582032fe7ad980a95
openssl/1.1.1q: Generator txt created conanbuildinfo.txt
openssl/1.1.1q: Aggregating env generators
openssl/1.1.1q: Calling build()
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.20
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
openssl/1.1.1q: using target: VC-conan-RelWithDebInfo-Windows-x86_64-Visual Studio-16 -> VC-WIN64A
openssl/1.1.1q: my %targets = (
    "VC-conan-RelWithDebInfo-Windows-x86_64-Visual Studio-16" => {
        inherit_from => [ "VC-WIN64A" ],
        cflags => add("-Zi -O2 -Ob1 -MD"),
        cxxflags => add("-Zi -O2 -Ob1 -MD"),
        defines => add("NDEBUG"),
        includes => add(),
        lflags => add(""),

    },
);

openssl/1.1.1q: ['"VC-conan-RelWithDebInfo-Windows-x86_64-Visual Studio-16"', 'no-shared', '--prefix="C:\\Users\\user_user\\.conan\\data\\openssl\\1.1.1q\\_\\_\\package\\75ed07303f056424be45ffb582032fe7ad980a95"', '--openssldir="C:\\Users\\user_user\\.conan\\data\\openssl\\1.1.1q\\_\\_\\package\\75ed07303f056424be45ffb582032fe7ad980a95\\res"', 'no-unit-test', 'threads', 'PERL=C:\\Users\\user_user\\.conan\\data\\strawberryperl\\5.30.0.1\\_\\_\\package\\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\\bin\\perl.exe', 'no-tests', '--release', 'no-md2']
WARN: replace_in_file didn't find pattern '/MTd ' in 'Configurations\10-main.conf' file.
WARN: replace_in_file didn't find pattern '/MTd"' in 'Configurations\10-main.conf' file.
Configuring OpenSSL version 1.1.1q (0x1010111fL) for VC-conan-RelWithDebInfo-Windows-x86_64-Visual Studio-16
Using os-specific seed configuration

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

NASM not found - make sure it's installed and available on %PATH%
openssl/1.1.1q:
openssl/1.1.1q: ERROR: Package '75ed07303f056424be45ffb582032fe7ad980a95' build failed
openssl/1.1.1q: WARN: Build folder C:\Users\user_user\.conan\data\openssl\1.1.1q\_\_\build\75ed07303f056424be45ffb582032fe7ad980a95
ERROR: openssl/1.1.1q: Error in build() method, line 767
        self._make()
while calling '_make', line 689
        self.run('{perl} ./Configure {args}'.format(perl=self._perl, args=args), win_bash=self._win_bash)
        ConanException: Error 1 while executing C:\Users\user_user\.conan\data\strawberryperl\5.30.0.1\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\perl.exe ./Configure "VC-conan-RelWithDebInfo-Windows-x86_64-Visual Studio-16" no-shared --prefix="C:\Users\user_user\.conan\data\openssl\1.1.1q\_\_\package\75ed07303f056424be45ffb582032fe7ad980a95" --openssldir="C:\Users\user_user\.conan\data\openssl\1.1.1q\_\_\package\75ed07303f056424be45ffb582032fe7ad980a95\res" no-unit-test threads PERL=C:\Users\user_user\.conan\data\strawberryperl\5.30.0.1\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\perl.exe no-tests --release no-md2

**Comment by memsharded** [comment]
Hi @jasuramme 

I am having a look, some quick hints while building:

- The ``cmake_find_package_multi`` generator has been removed in 2.0, and it has already been superseded in 1.X by ``CMakeDeps``. 
- The ``os_build``, ``arch_build`` approach has been deprecated long time ago, instead the recommended way is using the 2 profiles: ``--profile:build=default -profile:host=myprofile`` (or ``-s:h`` and ``-s:b`` for settings in host and build)

**Comment by memsharded** [comment]
Here it is working fine with (isolating from the other dependencies):

```
conan install openssl/1.1.1q@ -s compiler.version=16 -s build_type=RelWithDebInfo --build=missing -pr:b=default
```
Can you please run this command in your setup, and paste the full output?

**Comment by jasuramme** [comment]
Hi @memsharded and thanks for your answer!
There is a log, I'm not sure if it is very useful.
`conan install openssl/1.1.1q@ -s compiler.version=16 -s build_type=RelWithDebInfo --build=missing -pr:b=default`
[log_conan.txt](https://github.com/conan-io/conan/files/9898100/log_conan.txt)
To be honest if I run conan like that:
`conan install openssl/1.1.1q@ --build missing -s os=Windows -s os_build=Windows -s arch=x86_64 -s arch_build=x86_64 -s compiler="Visual Studio" -s compiler.version=16 -s compiler.runtime=MD -s build_type=RelWithDebInfo --generator cmake_find_package_multi`
I have the same behavior. All works fine. The bug is some corner case dependent on install path and shell from which you run conan.
The main issue we had is our azure pipeline failing. And we fixed it by running conan within bash shell instead of cmd and adjusting install script. 
For example we were running conan (some old setup) with this command:
`conan ../../../ --build missing -s os=Windows -s os_build=Windows -s arch=x86_64 -s arch_build=x86_64 -s compiler="Visual Studio" -s compiler.version=16 -s compiler.runtime=MD -s build_type=RelWithDebInfo --generator cmake_find_package_multi`
and I found that changing this backwards path ../../../ with if fixes the bug in some cases. So we started to run conan from another folder with -if flag
`conan . -if --build missing -s os=Windows -s os_build=Windows -s arch=x86_64 -s arch_build=x86_64 -s compiler="Visual Studio" -s compiler.version=16 -s compiler.runtime=MD -s build_type=RelWithDebInfo --generator cmake_find_package_multi`
And as I mentioned before, it somehow dependant on the shell... I didn't manage to reproduce it on local machine, but in azure cloud the latest command fails with cmd (script in azure yaml pipelines) and works with bash... 
That's not urgent bug for us, since we are managed to run it at least for now. But I think it can disappoint some users with old long-running setups, that's why I've applied this bug report.

> The cmake_find_package_multi generator has been removed in 2.0, and it has already been superseded in 1.X by CMakeDeps.
> The os_build, arch_build approach has been deprecated long time ago, instead the recommended way is using the 2 profiles: > --profile:build=default -profile:host=myprofile (or -s:h and -s:b for settings in host and build)

Thanks for that information, I'm just starting to work with conan and I will try to update our running command accordingly. 
BTW cmake_find_package_multi is marked as experimental in the official documentation. Should it be obsolete? I'm not very experienced conan user, so I fell confused with that a little bit... https://docs.conan.io/en/latest/reference/generators/cmake_find_package_multi.html

Many thanks!

**Comment by jasuramme** [comment]
Update:
if I install single openssl package it works fine even in azure cmd.

**Comment by memsharded** [comment]
Yes, definitely worth reporting. But yes, this also seems difficult to reproduce, as it highly depends on the environment.
It would be good to try to reproduce in azure, by gradually reducing the ``conanfile.txt``, and checking if some other dependency is affecting things.

One of the possible things that can cause issues is env-vars lengths in Windows, and there might be also some varying limits depending on the shell. If many dependencies are appending values to env-vars, at some point it might overflow and skip values (https://github.com/conan-io/conan/issues/9565 is related). Maybe it is worth checking your PATH env-var in azure, specially if you have other setup that might be adding many things to the PATH?

**Comment by memsharded** [comment]
I am closing this ticket as inactive, if there is any pending question or issue, please don't hesitate to re-open or create new tickets for any further question. Thanks for the feedback!
