### ISSUE TITLE
[feature] Make self.dependencies available for test_package

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12411]
When creating a test package for a Conan tool package, there are few ways to validate its package.
One way checking its output, like its version and comparing from the package:

```python
def test(self)
    output = io.StringIO()
    self.run("foo --version", env="conanrun", output=output)
    current_version = str(output.getvalue())
    require_version = str(self.deps_cpp_info["foo"].version)
    assert required_version == current_version
```

In case we try to use `self.dependencies["foo"]`, it returns `None`.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @uilianries!

I think this issue is duplicated. Have a look at https://github.com/conan-io/docs/issues/2794

**Comment by memsharded** [comment]
Hi @uilianries 

I am afraid, this is not possible in 1.X, by design. The ``build()`` and ``test()`` methods execute locally, without re-constructing the dependency graph. So it is basically impossible to fill the ``self.dependencies`` when they are executing.

The approach would be similar to the one that recipe should use:
- Access ``self.dependencies`` in the ``generate()`` method, do whatever is necessary, save the versions in a file, or whatever
- Access the generated files in the ``build()`` and ``test()`` methods as necessary

**Comment by uilianries** [comment]
@franramirez688 @memsharded Thank you both!

**Comment by SSE4** [comment]
how about:
- add a new toolchain/generator to save `self.dependencies` information to a .json file
- add a new helper to reconstruct information from the `build`/`test` method

it may look like:

```
def generate(self):
    from conan.tools.json import JsonDependenciesGenerator
    tc = JsonDependenciesGenerator(self)
    tc.generate()

...

def test(self):
    from conan.tools.json import JsonDependenciesLoader
    dependencies = JsonDependenciesLoader(self)
    if dependencies["tinyspline"].options.cxx:
        # do something 
    
```

**Comment by memsharded** [comment]
I think that checking the dependencies in a ``test_package``, needed to actually navigate the dependencies in the ``test()`` method is a smell. The ``test_package`` is designed to test the integrity and correctness of the current package, if it has been built successfully, if it packaged all the headers and libs, or the executables, etc. Checking for example a specific option value of a dependency seems a bit too much.

And if an option of a dependency is strictly necessary, it is also possible in just a couple of lines of the ``generate()`` method to save it in a json file that ``test`` can recover, but serializing the whole dependency graph in a new generator seems also a bit overkill for the purpose, and introduces yet another generator to maintain, document, test, and guarantee stability for the future years, this will not be added unless there would be way more evidence of its need.

**Comment by uilianries** [comment]
Closing this one as it's duplicated with https://github.com/conan-io/docs/issues/2794
