### ISSUE TITLE
[bug] conan install generates CMake Preset for the wrong profile

### ISSUE THREAD

**Issue by torfinnberset** [conan-io/conan#12428]
I am trying out the feature to let conan generate CMake Presets. However, it is not working as expected for me when I specify a different `build` and `host` profile. 

I am expecting that running the install command would generate a cmake preset for the `build` context, but instead it generates it for the `host` context. 

I created a small and complete example (see below) that demonstrates this behavior. 

### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 12.6
  * Compiler+version: clang 15.0.3
  * Conan version: 1.53.0
  * Python version: 3.10.6

### Steps to reproduce (Include if Applicable)

See example project in https://github.com/torfinnberset/conan-cmake-preset-error

```
conan install . \
  --build=missing \
  -pr:b ./conan/profile/macos-clang-x86_64-debug \
  -pr:h ./conan/profile/macos-clang-x86_64-release \
  -if ./build/macos-clang-x86_64

# This fails; a preset has only been generated for macos-clang-x86_64-release
source ./build/macos-clang-x86_64/activate.sh && cmake --preset macos-clang-x86_64-debug 
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

Log in https://github.com/torfinnberset/conan-cmake-preset-error/blob/main/README.md

**Comment by torfinnberset** [comment]
Ugh, I think I mixed up the meaning of the `build` and `host` contexts. 

In my mind the `host` context was the host from where I was running conan, and the `build` context was what I was building for... apparently it's the opposite.

**Comment by memsharded** [comment]
> In my mind the host context was the host from where I was running conan, and the build context was what I was building for... apparently it's the opposite.

Yes, Conan follows the GNU naming, which I agree it is not that intuitive, but it is kind of standard in the GNU world:
- "build" is the current build machine
- "host" is the machine that will run the code that we are building
