### ISSUE TITLE
tools.build_sln_command does not find devenv

### ISSUE THREAD

**Issue by Brunni** [conan-io/conan#1242]
Hi,

I have some issue, with the build_sln_command. I have some simple VS solution, which I want to build. (no cmake).

When I use this:
```
if self.settings.compiler == "Visual Studio":
   build_comman = tools.build_sln_command(self.settings, "MySolution.sln")
```
The result is:
```
Der Befehl "devenv" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```
which is German for: "The comman devenv was not found." It is not in my path variable and I don't want to put it there, as this should work on other machines as well.

How do I fix this issue properly?

**Comment by Brunni** [comment]
Oh damn. I just found the solution: http://conanio.readthedocs.io/en/latest/reference/tools.html

Sorry for bothering!

**Comment by memsharded** [comment]
No worries! :)
