### ISSUE TITLE
[question] What's the difference between `gnu11` and `11` in `compiler.cppstd` setting?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12425]
### Problem Description

I noticed that there are some value with **gnu** prefix in `compiler.cppstd` setting. For example: **gnu98**, **gnu11**, **gnu14**, **gnu17**, **gnu20**, and **gnu23**. I was wondering what is the difference between **gnu11** and **11** in `compiler.cppstd` setting? Or are they the **SAME**?

![image](https://user-images.githubusercontent.com/71438617/198871932-969846eb-9235-4d88-a79f-042206e92bf9.png)

**Comment by memsharded** [comment]
Hi @hwhsu1231 

No, they are not the same. The ``gnu11`` enables the GNU specific extensions, while the ``11`` is the C++11 standard, without the GNU extensions enabled.

**Comment by hwhsu1231** [comment]
@memsharded 

So `gnuxx` is related to [CMAKE_CXX_EXTENSIONS](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_EXTENSIONS.html), right?

And the [0.18.1](https://github.com/conan-io/cmake-conan/blob/df0f64a0920eab35033b17cc1104aa8b37af204f/conan.cmake#L131-L133) version of cmake-conan detect `compiler.cppstd` like the following:

```cmake
if(USING_CXX)
    set(_CONAN_SETTING_COMPILER_CPPSTD ${CMAKE_CXX_STANDARD})
endif()
```

What do you think about the following mechanism:

```cmake
if (USING_CXX)
    if (CMAKE_CXX_EXTENSIONS)
        set(_CONAN_SETTING_COMPILER_CPPSTD gnu${CMAKE_CXX_STANDARD})
    else ()
        set(_CONAN_SETTING_COMPILER_CPPSTD ${CMAKE_CXX_STANDARD})
    endif ()
endif ()
```

**Comment by memsharded** [comment]
> So gnuxx is related to [CMAKE_CXX_EXTENSIONS](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_EXTENSIONS.html), right?

Yes

> What do you think about the following mechanism:

yes, I'd say it looks good

**Comment by memsharded** [comment]
Closing this issue as responded.
