### ISSUE TITLE
[bug] compiling automake fails on macOS if "--profile:build" is specified

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#12429]
### Environment Details
  * Operating System+version: macOS 12.6 (Apple silicon)
  * Compiler+version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  * Conan version: 1.53.0
  * Python version: 3.8.9

### Steps to reproduce (Include if Applicable)
* Create and use the new empty `CONAN_USER_HOME`: `export CONAN_USER_HOME=$PWD/local-conan-home`
* From conan-center-index root, invoke `conan create recipes/automake/all/ 1.16.5@ --profile:host default --profile:build default`
-> This command fails with
```
configure: error: Autoconf 2.65 or better is required.
    Please make sure it is installed and in your PATH.
```

Interestingly, the command succeeds if I remove `--profile:build default` from the invocation.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Full output of the command can be found here: https://gist.githubusercontent.com/mkoviazin/f9392089e71492922c020dc4a4194055/raw/72d333f39c2da394397aa2bf260639c0e86c9db5/gistfile1.txt

### Additional notes
* While testing it to report, I noticed thatthe issue is somewhat random. Sometimes this check does succeed, sometimes it doesn't. For me it takes a couple of attempts to trigger this failure. And the sequence of commands is always the same: remove the folder `CONAN_USER_HOME` points to and then call `conan create`
* I can't reproduce the issue when `--profile:build` is not specified
* On custom Conan remote, the issue seems to be reproduced more consistently. Omitting `--profile:build` from the invocation seems to fix the issue there as well

I could not check that with Conan2 since the recipe uses `conans` module.

**Comment by ghost** [comment]
Printing `os.environ` in the failed builds showed that indeed `autoconf` directory doesn't get propagated to `PATH`

**Comment by ghost** [comment]
Ping? Can anyone comment on this?

**Comment by hassec** [comment]
FWIW, the same problem shows up when trying to build in the msys2 subsystem on Windows.

**Comment by memsharded** [comment]
It seems this was a legacy recipe issue (not a conan issue) from ConanCenter.
This should have been fixed some time ago, as the 2 profiles are always used in Conan 2 builds, so I am closing this as outdated.
Sorry this was not responded back them, sometimes the load is very high, not always possible to respond all tickets.
