### ISSUE TITLE
CONAN_V2_MODE and the `imports` method

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#12439]
Hi there,

Just a quick question - when using the `CONAN_V2_MODE` env var mode on the latest 1.53.0 release, I've noticed that no error is raised if a recipe defines the the `imports` method. As this has been removed in 2.0 I expected an error to be raised in this case.

As a background we have a lot of recipes that use the `imports` method and raising and it would be very beneficial if activating `CONAN_V2_MODE` raised an error so we could more easily detect these recipes required (futher) migration work in automated systems.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @santhonisz 

Since we started with the late alphas and betas, that can be used to test things with a complete release, we have no longer maintained the ``CONAN_V2_MODE`` env-var functionality. It might contain a few checks, but the new ``deployers`` that deprecate ``imports()`` is relatively new in the betas, so no new checks have been added.

**Comment by santhonisz** [comment]
Thanks for the quick feedback @memsharded  - I guess it's safe to say we shouldn't really be relying on `CONAN_V2_MODE` to catch (all) 2.0-compatibility issues in that case.

**Comment by memsharded** [comment]
> Thanks for the quick feedback @memsharded - I guess it's safe to say we shouldn't really be relying on CONAN_V2_MODE to catch (all) 2.0-compatibility issues in that case.

Yes, definitely. The team has been putting some other helpers, like these linters: https://github.com/conan-io/conan-center-index/tree/master/linter, that might help to catch some 2.0-readiness issues. Still nothing beats actually running things against a 2.0-beta version.

**Comment by santhonisz** [comment]
All good and thanks for the heads up re the linters 👍🏼
