### ISSUE TITLE
tools.download seems not to use configured proxy

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#1243]
Hi,

I am living behind a corporate firewall. While I can use conan.io with setting the proxies, I cannot use receipts that use tools.download. 
Is tools.download using the proxy?

Thanks, Claas

**Comment by memsharded** [comment]
You are right, tools.downloads is not using the proxies configuration.
Try to use the global configuration via environment variables, like those described in http://conanio.readthedocs.io/en/latest/reference/config_files/conan.conf.html#proxies while we have a look how to inject the configured proxies in tools.downloads. Thanks for reporting.

**Comment by claasd** [comment]
Very low priority

**Comment by memsharded** [comment]
Thanks for help prioritizing!

**Comment by memsharded** [comment]
Hi @claasd 

Now ``tools`` are using the global requests object (and also the output object), so the proxies should work now (released in 0.24). Please check, thanks!
