### ISSUE TITLE
[question] conan 2 editable/recipe development flow for third-party

### ISSUE THREAD

**Issue by petr-polezhaev** [conan-io/conan#12438]
Hello

I have a development conan wrapper that is meant to be called from the vscode to [perform incremental development steps](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html). I.e. call `source`, if it succeeded, call `build`, etc. This is to simplify development of recipes with custom patches, so you can just hit the Run/Debug key and seamlessly debug your conanfile with local breakpoints and without repeating the potentially costly previous step. This is used to develop out-of-the-source-tree recipes for third-party libraries that are not in the conan-center or need custom patches

In conan 1 this is working using `conan editable` (which seems to be mostly unchanged in conan 2) to avoid copying the `conanfile.py` (so the debug breakpoints work as expected) and calling `conan source`, `conan build`, etc commands with some file marker management. One important part of this was the fact that all "artifacts" produced by those commands were confined to a single `.temp` directory, ignored by the VCS. The reason why this is important, because the flow was encouraging developers to test their packages often and early - which means you can hit the build button before you made your `layout` setup

And that has two problems with conan 2:

1. In conan 2 there is no `command package` folder, so the final install is never made and the package_info in the conanfile points to invalid location. The [migration guide](https://docs.conan.io/en/latest/migrating_to_2.0/commands.html#removed-conan-package) recommends using `conan export-pkg` instead, which works, but this means the whole `editable` thing is no longer valid? Because where would it point then?
2. The `command source` command doesn't have the `--output-folder` argument. Yet the `build` command does and uses it as a prefix for the `layout` setup. Yet the source directory now can only be the `conanfile` directory and the default layout setup means unpacking sources into `.`. I.e. if you didn't specify the `layout` and didn't explicitly set `src_folder=` to something else, running the script will unpack a bunch of "junk" right into your working space, making it quite annoying to cleanup.

So, the questions are
- How the editable/development flow is supposed to work now? Is `editable` even supported or is it deprecated and shouldn't be used?
- Is `source` lacking `--output-folder` simply a missing feature (considering the `build` has it and both are part of the layout) or a deliberate design decision? Am I expected to always specify `src_folder` in the layout if I am using fetched sources?
- If I am supposed to use fetched sources with `src_folder` layout, is it possible to check that the conanfile has the correct layout setup before calling the `conan source` on it? I know this is possible with the hooks or the custom commands, but I'd rather avoid using those
- Since the conan 2 now has an official public api, is this (such a wrapper script) is something that is meant to use the api and I need to implement the custom versions of the `source` and `build` (since it should use `source` results) commands?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @petr-polezhaev 

> In conan 2 there is no command package folder, so the final install is never made and the package_info in the conanfile points to invalid location. The [migration guide](https://docs.conan.io/en/latest/migrating_to_2.0/commands.html#removed-conan-package) recommends using conan export-pkg instead, which works, but this means the whole editable thing is no longer valid? Because where would it point then?

Yes, while working in editable, the only important part is the "build" state. The "package" is not used by the editable at all. So the part of testing the ``package()`` method is a different thing. It can be tested with the ``export-pkg``, and it doesn't change anything at all in the ``editable``, dependencies using the editable will use the user folder, not the cache copy, but the cache package can be checked by just inspecting the folder after the ``export-pkg``.

> How the editable/development flow is supposed to work now? Is editable even supported or is it deprecated and shouldn't be used?

It is not deprecated at all, in fact, it should be improved wrt to the previous implementation via the built-in ``layout()`` method.

> Is source lacking --output-folder simply a missing feature (considering the build has it and both are part of the layout) or a deliberate design decision? Am I expected to always specify src_folder in the layout if I am using fetched sources?

It is deliberate. The ``--output-folder`` is intended for build artifacts, and will contain different folders for different configurations (Release/Debug, shared/static, etc, depending on the ``layout()``)

> If I am supposed to use fetched sources with src_folder layout, is it possible to check that the conanfile has the correct layout setup before calling the conan source on it? I know this is possible with the hooks or the custom commands, but I'd rather avoid using those

The source should have a relative known location to the ``conanfile.py`` as specified in ``layout()``, but it doesn't need to be necessarily ``.``, rather the opposite, it will typically be a folder like ``src`` or something like that.

> Since the conan 2 now has an official public api, is this (such a wrapper script) is something that is meant to use the api and I need to implement the custom versions of the source and build (since it should use source results) commands?

Sorry, this is not clear what you mean, could you please clarify?


In any case, it is possible that the default ``cmake_layout()`` is simply not optimized for third-party development (because editables in general is not intended for third-party packages, because code in third parties is not developed, so it is not necessary to develop it simultaneously to other packages), but customizing the ``layout()`` method could work. It could help to make very concrete examples with minimal recipes to communicate the intention, the desired behavior and the obtained one, etc.

**Comment by petr-polezhaev** [comment]
Thank you for your comments

Based on your response and some additional research I've made a minimal-ish example of what I wanted to achieve: https://github.com/petr-polezhaev/conan-editable-test
(it's very jank and simplisitic, obviously - just to illustrate the concept and issues I've encountered)

While doing so I've realized a few misconceptions I had about the editable mode and how it is different from the normal flow. I was under impression that it is basically the same thing as `conan create`, but "in-place". Now I realize that it doesn't make sense, as the point is to be able to compile the code with the host project/other libraries - so it needs to work the build artifacts directly and requires a separate layout/package_info-like setup

The fact that you can't set the source directory for out-of-source recipes is still a bit a annoying for when you don't need to tamper with sources, but I managed to make a validation for it in a hook. Hooks require installation, so that's not ideal - but I can do the same using the api, which is probably what I will use for the real script (as it should be python)

Overall I'll have to rethink the whole flow, where the editable is a rare opt-in thing that requires an advanced setup by the developer, instead of a default option. By default the script should use source/build/export-pkg flow, which is more work with cleaning up old revisions, updating the host app files, etc - which is why I was trying to avoid it in the first place

Anyway, I think I understand the intended flow much better now, thank you

**Comment by memsharded** [comment]
> Overall I'll have to rethink the whole flow, where the editable is a rare opt-in thing that requires an advanced setup by the developer, instead of a default option. 

Well, I think that not that advanced. The ``conan new hello/0.1 -m=cmake_lib`` that contains a simple ``cmake_layout()`` works directly as editable. Just type ``conan editable add . hello/0.1`` and it works out of the box. Furthermore Conan 2.0 already has some extra features, like being able to build in place editables if needed ``--build=editable`` which also helps managing projects with editables more conveniently. Even if the workspace feature has been temporarily remove in 2.0, setting up a full IDE project with several editables might be a task that can be done in a couple of minutes with a few clicks, like shown in https://youtu.be/VzUJQw89U7o?t=2563

Totally true that still editables are intended for simultaneous working on the code, not really a third-parties use case where the code is not edited. For that, it is true that the use case is more what we call the "local flow", being able to do ``conan install`` + ``conan source`` + ``conan build`` + ``conan export-pkg``. In Conan 2.0, the ``conan install`` step is also redundant, and it is possible to test the whole "build" part with just ``conan build`` (it will do an install internally), and to test the whole "package" part with ``conan export-pkg`` and optionally testing the package if desired with ``conan test``

**Comment by petr-polezhaev** [comment]
> Well, I think that not that advanced

Oh, I didn't mean it in that sense. I am trying to port Unreal Engine third-parties (+ a few custom ones) for a rather large project to use conan (as it's a pain to change and recompile those manually using a slightly unmaintained batch scripts). So I have to compete against the idea of everything already working and you just need to manually do few things versus learning new things, essentially. Which is why I am trying to lower the entry barrier as much as possible. Editable setup sounds like "advanced" part of it, not to overwhelm new people with all the stuff - also since now I understand it's mostly useful only for the cases where you do actually make changes to the library and need to test them - there are only one or two of such libraries currently. So it's not something everyone even needs to know how to do right away

Once you understand how it works it is indeed quite simple - you just need to set the layout and your infos correctly so they are correct for both package and build phases. Which might be trivial or might be not - that really depends on the library/tool you are trying to package. If the library really expects to be installed and compiles to all over the place and it's not cmake where you can set the paths - it might require a special treatment here and there.
