### ISSUE TITLE
[bug] Bazel BUILD file should not include build-context dependencies

### ISSUE THREAD

**Issue by sburton84** [conan-io/conan#12444]
This relates to my [previous change](https://github.com/conan-io/conan/pull/10686) which added transitive dependencies to Bazel `BUILD` files. When a dependency which has build-time dependencies is added, it adds the build-context dependencies as well, even though these are only needed for building the dependency, not for using it.

### Environment Details
  * Operating System+version: Ubuntu 21.04
  * Compiler+version: GCC 10.4
  * Conan version: 1.53.0
  * Python version: Python 3.10.6

### Steps to reproduce (Include if Applicable)

Add a dependency on libCurl and run the Bazel generator. The first time it runs, it generates dependencies like this:

```
    deps = [
        # do not sort
    ":curl_precompiled",
    "@openssl",
    "@zlib",
    "@c-ares",
    "@libtool",
    "@pkgconf",
    "@automake",
    "@autoconf",
    "@m4",
    ],
```

The dependencies such as `autoconf` and `m4` are things used for building the libCurl library but are not dependencies which are needed to link against it, so should not be included here.

Running a second time without any other changes will, now the libCurl library has already been built, then generate the appropriate deps:

```
    deps = [
        # do not sort
    ":curl_precompiled",
    "@openssl",
    "@zlib",
    "@c-ares",
    ],
```

PR that fixes this at #12445

**Comment by czoido** [comment]
Related to: https://github.com/conan-io/conan/issues/12236
