### ISSUE TITLE
Improve UX to install system packages without architecture

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#12448]
Provide a better way of forcing installing packages without the architecture appended to the package name even if you are cross-compiling. Currently you can do:

```
Apt(self, arch_names={}).install(["archless-package"], update=True, check=True)
```

Passing arch_names as an empty dictionary in the constructor will make that the name resolution skips adding the architecture for all cases (cross-compiling and not). But that is ugly and probably we want to pass a new argument to cover this case. 

Related to: https://github.com/conan-io/conan/issues/12320

**Comment by memsharded** [comment]
The workaround is a proper solution, not that much of a workaround, so closing this as solved.
