### ISSUE TITLE
Migration process to new msvc compiler settings in 2.0

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#12442]
Hi there,

I was seeking some clarification around the migration process to using the new `msvc` compiler settings in 2.0 in light of the removal of the `Visual Studio` compiler settings. Forgive me if this has been asked before - I've searched both here and on the Conan Center repo for an answer and can't seem to find one.

I understand that as all Conan Center packages that support MSVC are currently built using the `Visual Studio` compiler settings, they cannot be consumed by a recipe when using `msvc` under 2.0.  For example, I can't currently build a new 2.0 project that depends on `boost/x.y.z` from Conan Center using the `msvc` compiler setting.

I also gather there is no ability to use the existing `Visual Studio`-built packages via the `compatibility.py` extension, as the `Visual Studio` settings have been completely removed from the `settings.yml` e.g. any attempt to configure them as compatible would raise a settings error.

So I guess my first question is what is the expectation for managing the transition to the new compiler settings. Do you expect to rebuild the entire Conan Center universe to produce `msvc`-built versions of all existing packages (where appropriate)? If so, is there a timeline for when this is this expected to occur (I assume after the 2.0-recipe-compatibility uplift that is currently underway)? 

Secondly, our large enterprise organisation has literally hundreds of (500+) Conan recipes for private packages that are all built with the `Visual Studio` compiler settings - ownership of these are spread across multiple teams in different geographic regions.These packages are often shared among teams as well i.e. common frameworks etc.

Are we too expected to rebuild every one of these using the `msvc` settings if we want to move to 2.0? If this is the case then a major hindrance is the current approach in 1.x of allowing `msvc` to have a `compatible_packages` fallback to `Visual Studio`, but not the other way round. This means the migration to `msvc` must be done in a specific order as we can't just update dependencies at will because they will no longer function with `Visual Studio`-built consumers (unless we build them twice, which we would **_really_** like to avoid as they are literally the same binaries with different settings - there's a build cost involved etc). While we could define a `compatibility` method in the recipes to handle this, it is quite cumbersome compared the global `compatibility.py` extension approach that is available in 2.0 (base classes present the same challenge in that all recipes must be updated).

Any clarification and/or advice you can provide in this regards would be greatly appreciated.

Cheers.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @santhonisz 

> I understand that as all Conan Center packages that support MSVC are currently built using the Visual Studio compiler settings, they cannot be consumed by a recipe when using msvc under 2.0. For example, I can't currently build a new 2.0 project that depends on boost/x.y.z from Conan Center using the msvc compiler setting.

Yes, there is a fallback to help in the transition. When using ``msvc`` setting, there is a "compatible-package" fallback that will try to use the equivalent old ``Visual Studio`` binary if you still didn't built the ``msvc`` one (but use the ``msvc`` if available)

> So I guess my first question is what is the expectation for managing the transition to the new compiler settings. Do you expect to rebuild the entire Conan Center universe to produce msvc-built versions of all existing packages (where appropriate)? If so, is there a timeline for when this is this expected to occur (I assume after the 2.0-recipe-compatibility uplift that is currently underway)?

Yes. All packages have new ``package_id``s, for all configurations, not only VS, in Conan 2.0. The binaries have different ``package_ids``, so they do not conflict, as many things around ``package_ids`` have changed, including the default package-id-modes. You can upload binaries for 1.X and 2.0 to the server, and they will not conflict with each other. Conan 1.X will still report and use Conan 1.X created binaries, and omit 2.0 ones. But it is still necessary to build binaries with 2.0, it will not be able to reuse 1.X created binaries.

**Comment by santhonisz** [comment]
Thanks as always for the feedback @memsharded ; that clears things up quite a bit.
