### ISSUE TITLE
[question] Is the behavior of tested_requirements_str correct?

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12450]
It appears that a recipe reference that contains a name, version, and recipe revision will be represented in tested_requirements_str as:

> name/version#RREV

rather than as:

> name/version@#RREV

which is what I was expecting based on my understanding of references. e.g. documented as "The full reference and the package ID of the dependencies, pkg/version@user/channel#RREV:pkg_id ..." but vague on what if any separators should be present when aspects of the ID are missing.

If this is indeed a bug, it results from the stringification logic in /conans/model/recipe_ref.py, which only adds the "@" if there is a user as part of the RecipeReference object. It would be more consistent if the "@" were added for any suffix (user/channel and/or RREV).

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @System-Arch 

Yes, it is correct, ``name/version#RREV`` is the correct way to express a recipe revision without user and channel, and it is the canonical way moving forward, and the only way in 2.0. There are some contexts in which the legacy ``name/version@#RREV`` way is necessary to not break some code, but as the former works well in the context of ``test_package`` (it works as an input to ``self.requires()``), this seems to be good.

**Comment by System-Arch** [comment]
Hi @memsharded,

Thanks for clarifying. This might be good to document (unless it already is and I missed it).

On a related note, it might be useful to publish an API for "cracking" a ref (e.g., to extract the name, version, etc.). It looked to me like the Conanfile implementation is meant to be private or is it okay to instantiate a RecipeReference object in something like a test_package Conan file?

Thanks

**Comment by memsharded** [comment]
It will be part of the API, and it will be fully documented in 2.0. ``self.ref.name``, ``self.ref.version`` (and also for dependencies like ``self.dependencies["dep"].ref.version``, it is already documented in https://docs.conan.io/en/latest/reference/conanfile/dependencies.html

**Comment by System-Arch** [comment]
Great! Thanks
