### ISSUE TITLE
[feature] Define CMake toolchain variables in global/profile conf

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#12454]
While it is already possible to [set CMake toolchain variables in the generate method](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#variables), in some cases it makes sense to set these at a global or profile level, when they relate directly to the profile settings.

For example, if I am using a host profile which using a Tasking compiler, I would also want to specify the compiler toolset by injecting the [CMAKE_TASKING_TOOLSET](https://cmake.org/cmake/help/latest/variable/CMAKE_TASKING_TOOLSET.html) variable.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @GordonJess,
Thanks a lot for the suggestion, I'm marking this as a look-into so the team can discuss if this feature, of being able to set additional CMake variables from the conf would make sense. From what I understand it would be something like:

```
[settings]
os=Linux
compiler=gcc
...
[conf]
tools.cmake.cmaketoolchain:variables+=["CMAKE_TASKING_TOOLSET =SmartCode"]
```

**Comment by czoido** [comment]
Hi @GordonJess,
Thinking again about this issue, I think that the best way of setting custom variables in the toolchain is using the [tools.cmake.cmaketoolchain:user_toolchain](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html) configuration. Using this you can add your custom code to the toolchain. You could add something like this in your profile:

```
include(default)
[conf]
tools.cmake.cmaketoolchain:user_toolchain+=$PROFILE_DIR/mytoochain.cmake
```

Using `$PROFILE_DIR` can reference a file that is at the same leven that your profile, but you could use an absolute path as well.

Hope this helps.

**Comment by czoido** [comment]
Closing this issue as this could be solved by using `user_toolchain`. Please feel free to reopen if you have more questions regarding this.
