### ISSUE TITLE
[feature] CMake dependency provider

### ISSUE THREAD

**Issue by vasama** [conan-io/conan#12459]
CMake version 3.24 added support for [dependency providers](https://cmake.org/cmake/help/latest/command/cmake_language.html#dependency-providers). Are there any plans for an official conan dependency provider?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by omergoktas** [comment]
It would be nice if the CMake integration in Conan v2.0 is revisited while it is still in the beta phase, since the existing generators, CMakeDeps and CMakeToolchain, might get significantly impacted by the potential change.

**Comment by memsharded** [comment]
As approved by the Tribe, Conan should have CMake 3.15 compatibility, so it is not possible to rely on something that is only available in latest CMake. It might be possible to have some opt-ins or improved ways leveraging some of the latest CMake features, but there should be always a fallback, like what we are doing with the Presets.

So far it doesn't seem that dependency providers have a nice fallback. Furthermore, it also doesn't solve many issue, as it is something that is synchronous to the ``find_package()`` invocation, so the problems of dependency graph resolution (conflicts, versions overriding, configuration overriding, etc), cannot be addressed by this model provided by the dependency providers.

So I don't see any viable approach at the moment. Adding @jcar87 and @czoido for further discussion.

**Comment by memsharded** [comment]
The cmake-conan new integration for Conan 2.0 in https://github.com/conan-io/cmake-conan/tree/develop2 is already using the new CMake dependency providers.

This seems the right usage for this feature, not directly in the Conan client, closing this ticket as solved.
