### ISSUE TITLE
[feature] Add support for TASKING compilers

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#12456]
> The settings.yml file is not perfect nor definitive and surely incomplete. Please share any suggestion in the Conan issue tracker with any missing settings and values that could make sense for other users.

Now that CMake 3.25 has [added built-in support for TASKING compilers](https://cmake.org/cmake/help/latest/release/3.25.html#id6), I think it also makes sense for Conan to support them.  I realise it is possible to extend `settings.yml` on my own, but cross-compilers for embedded systems are a bit trickier and users may implement it differently (which becomes a big problem when it comes to delivery between supplier and customer).  Therefore, I would propose that Conan offer an official solution.

As an example of the difficulties, I am currently facing issues because Conan sets CMAKE_SYSTEM_PROCESSOR based on `arch`, but CMake uses CMAKE_SYSTEM_PROCESSOR to select a CPU device (see [here](https://gitlab.kitware.com/cmake/cmake/-/issues/24115)).  I expect some collaboration is needed between both parties to get it right.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was not responded back then.

Support for tricore was added in Conan 2: https://docs.conan.io/2/examples/cross_build/tricore.html

If other compilers or architectures are necessary, it would be good to get new tickets, specifying the detailed compilers, compiler names, architectures, and necessary compiler flags. 

So I am closing this ticket as partially solved, partially outdated. Thanks for your feedback.
