### ISSUE TITLE
[bug] buildenv vs runenv for cmake.test() helper.

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#12462]
Follow-up to #12407

I can see now why conan applies `[buildenv]` to this its `cmake.test` helper (since it's really `cmake --build <build_folder> --target test`), but it feels like many cases with shared libraries would also want the `[runenv]`. For example, they might need to find .dll files from libraries that were in requires. I would expect most test content to be pretty indifferent to the buildenv (unless doing something unusual, for example testing a header-only library by calling `$(CC) -fsyntax-only`).

But tests that call executable you just built (which linked to stuff in requires) don't seem that exotic. So I tested this, and it's indeed not working. I'm surprised I never hit that for real, but I guess I don't have *all* that many shared-library dependencies, and the one that is common (zlib1.dll) is kind of accidentally working because git for windows puts one in PATH, and I mostly live in git-bash.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 200H2
  * Compiler+version: Visual Studio 2022 
  * Conan version: 1.53.0
  * Python version: 3.10.7

### Steps to reproduce (Include if Applicable)

`conan create conanfile.py -pr conanprofile.txt`

<details>
<summary>conanfile.py</summary>

```py
from conan import ConanFile
from conan.tools.cmake import CMake

class CTestConan(ConanFile):
    name = "ctest"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    default_options = {"zlib:shared": True}
    generators = "CMakeToolchain", "CMakeDeps"
    requires = "zlib/1.2.12"

    exports_sources = "CMakeLists.txt", "main.cpp"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        cmake.test()
        # self.run("ctest", cwd=self.build_folder, run_environment=True)
        #self.run("ctest", cwd=self.build_folder, env=["conanbuild","conanrun"])

    def package_info(self):
        self.cpp_info.libs = ["hello"]
```
</details>

<details>
<summary>CMakeLists.txt</summary>

```cmake
cmake_minimum_required(VERSION 3.23)
project(test LANGUAGES CXX)

find_package(ZLIB)

add_executable(main main.cpp)
target_link_libraries(main ZLIB::ZLIB)

enable_testing()
add_test(NAME main COMMAND main)
add_test(NAME zlib1 COMMAND where zlib1.dll)
add_test(NAME env COMMAND ${CMAKE_COMMAND} -E environment)
```
</details>

<details>
<summary>main.cpp</summary>

```c++
#include <zlib.h>
int main() {
	z_stream zs = {};
	inflateInit(&zs);
	inflateEnd(&zs);
}
```
</details>

<details>
<summary>conanprofile.txt</summary>

```ini
[buildenv]
BUILDENV=1
[runenv]
RUNENV=1
[conf]
tools.env.virtualenv:auto_use=True
```
</details>

### Logs (Executed commands with output) (Include/Attach if Applicable)

If run from cmd (with no other zlib1.dll already in PATH from some random place), main fails with Exit code 0xc0000135 (STATUS_DLL_NOT_FOUND) and <build_folder>/Testing/Temporary/LastTest.log shows 

> 1/3 Test: main Exit code 0xc0000135

> 2/3 Test: zlib1
> Command: "C:/Windows/System32/where.exe" "zlib1.dll"
> Output:
> INFO: Could not find files for the given pattern(s).

> 3/3 Test: env
> Command: "C:/Program Files/CMake/bin/cmake.exe" "-E" "environment"
> BUILDENV=1

but no `RUNENV=1` -- so `[buildenv]` was applied, but not `[runenv]`. This is what I expected from #12407, but it seems like we would want `[runenv]` too when running tests.

---

If run from git-bash instead of cmd, all 3 tests "pass", but the _build_folder_/Testing/Temporary/LastTest.log shows that this is because we found zlib1 from mingw64:

> 3/3 Test: zlib1
> Command: "C:/Windows/System32/where.exe" "zlib1.dll"
> Output:
>C:\Program Files\Git\mingw64\bin\zlib1.dll

And that's why main.exe succeeded, that was enough to make a simple executable load and close enough to not crash. But we've mismatched versions/settings/options pretty much freely, since conan had no part in picking this one.

---

If I replace the `cmake.test()` with a `self.run("ctest", cwd=self.build_folder, run_environment=True)`, then PATH gets `%CONAN_USER_HOME%\.conan\data\zlib\1.2.12\_\_\package\ad5261bf6074807e7189c351b0f79b113bf2f6c0\bin`, and so main.exe gets the correct zlib1.dll. But it still doesn't get the `[runenv]RUNENV=1`, so apparently `run_environment=True` still does not pick up the profile's `[runenv]`?

If I try to get both by passing a list, i.e.`self.run("ctest", cwd=self.build_folder, env=["conanbuild","conanrun"])`, I unexpected get neither `[buildenv]` nor `[runenv]`.

The documentation at https://docs.conan.io/en/latest/reference/conanfile/other.html#output-and-running says this should work
> the environment or list of environment activations scripts to pre-pend to the given `command`. 

but the code to force a single `str` into into a list:

https://github.com/conan-io/conan/blob/5bf9aacedf9cc71c52ef548b079285715b51ba10/conans/model/conan_file.py#L441

will just end up in its `else []` case if the caller actually anything other than `str`

### Suggested fix

So it seems like Conanfile.run(env=...) should be fixed to recognize `isinstance(list)` (as is already documented), and then CMake.test -> CMake._build should pass in `env=["conanbuild","conanrun"]`, rather than just "conanbuild".

https://github.com/conan-io/conan/blob/5bf9aacedf9cc71c52ef548b079285715b51ba10/conan/tools/cmake/cmake.py#L157-L158
https://github.com/conan-io/conan/blob/5bf9aacedf9cc71c52ef548b079285715b51ba10/conan/tools/cmake/cmake.py#L127

**Comment by czoido** [comment]
Hi @puetzk,
Thanks a lot for reporting and the detailed instructions.
I could reproduce the bug in how the environments are passed, so we will fix that.
Also, I'm marking this as look-into for the next release and we will check your suggestion of adding the runenv to the run command by default.

**Comment by puetzk** [comment]
>  Also, I'm marking this as look-into for the next release and we will check your suggestion of adding the runenv to the run command by default.

I don't know that it should be the default for all run commands, but I do think that CMake.test() should probably be adding it (which means passing it along through CMake._build() into ConanFile.run().

**Comment by memsharded** [comment]
> I don't know that it should be the default for all run commands, but I do think that CMake.test() should probably be adding it (which means passing it along through CMake._build() into ConanFile.run().

Yes, it shouldn't be added to all commands by default, most commands are just "build" command, and only exceptionally, some will run "run" or "test" commands, that need the "runenv" from the host context.

I think this makes sense. It would even make sense to have the ``cmake.test()`` default to use only ``conanrun``, it is likely that most of the build tools are not necessary for running the tests, maybe just only ``cmake`` itself if it is a ``tool_require``.

**Comment by puetzk** [comment]
> It would even make sense to have the cmake.test() default to use only conanrun

I think I'd rather see keeping `conanbuild` and adding `conanrun`, rather than replacing it. For one thing, it's more compatible with the status quo. And `cmake.test()` is done through `cmake --build --target test`, so it uses not only cmake, but also ninja/jom/whatever make program is underneath that; it really is running the build machinery.

I do have a few cases of header-only libraries whose "tests" involve using the compiler, and in the case of template metaprogramming sometimes `WILL_FAIL` and `PASS_REGULAR_EXPRESSION` to check the behavior of static_assert or concept errors. It wouldn't be a great hardship if unusual usage like that has to specifically ask for the build environment to be available, though.

But most of all, I think the conclusion to #12407 suggests keeping buildenv (or reopening that issue, I gues). It feels much weirder to encourage putting things like `CTEST_OUTPUT_ON_FAILURE=1` into the runenv, when that's also the environment for something just consuming the resulting package (which doesn't care about its tests).

**Comment by memsharded** [comment]
> I think I'd rather see keeping conanbuild and adding conanrun, rather than replacing it. For one thing, it's more compatible with the status quo. And cmake.test() is done through cmake --build --target test, so it uses not only cmake, but also ninja/jom/whatever make program is underneath that; it really is running the build machinery.

Yes, I see that. My main concern here was also some eventual dependencies that such ``tool_requires`` might have, for example, ``cmake`` depending on ``openssl``. If for some reason the priority is not the right one, it is possible that the tests will run using the openssl shared library from the "build" context, rather than the one from the "host" context, which might also be a different version. Same with other popular libraries of the build context like zlib. At least, if the default doesn't include ``conanbuild`` environment, the user will be a bit more aware of this when adding it?

**Comment by puetzk** [comment]
yeah, I agree with runenv being given priority over (i.e. applied after) buildenv if both are used. Better to give the test executables the libs we meant to be testing, and hope ctest can work with that, rather than vice-versa.

If you want to eliminate the buildenv from cmake.test(), that would seem (at least to me) to suggest having the helper run `ctest` instead of  `cmake --build --target test`. Then it's consistent again - no build, no buildenv, no need to care which generator was used (currently to figure out the target name), and no need for msbuild/ninja/whatever to be in PATH. You would just need a ctest executable accessible from the runenv (probably from the inherited PATH, but it could be from a test_requires if necessary). Since everything was found in the host runenv, the call should be skipped unless [conan.tools.build.can_run](https://docs.conan.io/en/latest/reference/conanfile/tools/build.html?highlight=can_run#conan-tools-build-can-run) indicates that we can in fact run host binaries.

Going through cmake --build --target test is mostly just doing that anyway - it does hard-code the absolute path to ctest, but it's the copy right right next to `cmake`. Since we required `cmake` to be in PATH, `ctest` will be too, unless there's specifically a buildenv vs runenv with differnet cmake/ctest in PATH. Which would presumably be intentional, directly addressing the concern about cmake itself needing some of the same requirements as this recipe.

When doing something unusual (like testing a header-only library by building non-ALL targets) you'd have to be explicit about wanting the buildenv.

That does seem like it better respects the build/host distinction. I think that would make #12407 relevant again, though (if you aren't going through make, the conf settings would feed into the `ctest --verbose` or `--output-on-failure` CLI flags, rather than having anything to do with either set of environment variables.

Of course, one can already just ignore the existence of `CMake.test()` and have the recipe do `self.run(f"ctest -C {self.settings.build_type} --test-dir {self.build_folder} ...")`. But having a cmake.test() implementing the best practices helps keep recipse consistent; if everybody rolls their own code, some will forget about things like `[conf]tools.build:skip_test`, `tools.build.cross_building:can_run`, the build folder layout, passing --config = settings.build_type. And any evolution over time becomes a real mess.

**Comment by memsharded** [comment]
> yeah, I agree with runenv being given priority over (i.e. applied after) buildenv if both are used. Better to give the test executables the libs we meant to be testing, and hope ctest can work with that, rather than vice-versa.

I agree

So, these are the alternatives, to discuss with the team:
- ``cmake.test()`` adds both ``virtualbuildenv`` and ``virtualrunenv``, with the later higher priority
- ``cmake.test()`` uses only ``virtualrunenv``, using internally ``ctest`` instead of ``cmake``
- Maybe we could consider explicitly ``cmake.ctest()`` as a explicit opt-in into this later behavior, while keeping ``cmake.test()`` with the former.

**Comment by memsharded** [comment]
Fix proposed in https://github.com/conan-io/conan/pull/12580

**Comment by memsharded** [comment]
Merged https://github.com/conan-io/conan/pull/12580, ready for 1.55
