### ISSUE TITLE
[feature] Make cmake_layout available from only one place

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12461]
For now, we can import `cmake_layout` from both points:

- from conan.tools.layout import cmake_layout
- from conan.tools.cmake import cmake_layout

The documentation is inclined to use `cmake` only: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake_layout.html

However, importing from `conan.tools.layout` does not result in errors, nor warnings, but is not documented.

It would be great if was possible to import only from `cmake` module, to avoid prone errors.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
We decided to leave it to avoid breaking unnecessarily in 1.X. It has been removed already in 2.0.

But if everyone things that we should remove it, lets do it.

**Comment by AbrilRBS** [comment]
Closing, as we ended up deciding not to break 1.X, as we've shifted focus to Conan 2
