### ISSUE TITLE
CMake can't find .pc files generated by PkgConfigDeps

### ISSUE THREAD

**Issue by joastoe** [conan-io/conan#12460]
I just updated conan to version 1.53.0 and am surprised that my .pc files generated with PkgConfigDeps into build/generators folder are not found by CMake anymore when calling conan create.

If I define PKG_CONFIG_PATH manually before, all goes fine. But obviously this is something I rather don't want to do.

Has anyone a hint where I have to dig?

Thanks

**Comment by czoido** [comment]
Hi @joastoe,
Thanks for reporting. This is duplicated from: https://github.com/conan-io/conan/issues/11962
Closing this, please follow in the other issue, it's already being considered for 1.55
