### ISSUE TITLE
[feature] Add more config in `conf` in order to provide a canonical way to set path to compiler, linker etc

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12474]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Currently, there is no canonical way to ensure that a specific compiler will be used when different versions of the same compiler or even different compilers are installed on build machine.
`compiler` values in profile are just a promise of conan user to conan client/recipe, an implicit contract that this compiler and this version will be found by underlying build system. `CC`, `CXX`, `LD`, `AR` etc env vars are just GNU conventions and they are not understood by all build systems.

Therefore I advice to add config like these ones (not necessarily these names):

- `tools.c.compiler:path`
- `tools.cxx.compiler:path`
- `tools.linker:path`
- `tools.archiver:path`

and also these ones for example:
- `tools.fortran.compiler:path`
- `tools.python.interpreter:path`
- `tools.perl.interpreter:path`
- some conf for CUDA maybe

To ensure than these paths are honored, conan build helpers would intercept these values and inject whatever env var or specific variable understood by underlying build system.

For example:
- `AR` env var is not understood by CMake, so if `tools.archiver:path` is set, it would be translated to `CMAKE_AR` CMake variable in `CMakeToolchain`).
- `tools.c.compiler:path` would be translated to `CC` env var in `AutotoolsToolchain`, and on Windows this value would be curated: converted to unix path and eventually each folder translated to their short name to avoid spaces in paths (it's what CMake does sometimes). Why curated? Because underlying build system should be an internal detail, users should be able to specify the native path format to their tool and not worry about its underlying usage.

Moreover, when using a custom build system in a recipe, it would provide a consistent way to honor paths eventually specified by users.
A recipe could even conditionally avoid to add a `tool_requires` if path of related tool is already filled by user in config (`cpython` may not be needed in tool_requires if `tools.python.interpreter:path` is set).

The idea would be to listen these config at top priority, then eventually their GNU equivalent (because it was more or less expected by conan users that CC/CXX/LD/AR etc in profile should be honored, even though there is absolutely no guarantee that a random build system can honor this wish out of the box), then eventually some default assumption based on compiler settings in profile, then let underlying build system uses its default detection mechanism.

**Comment by memsharded** [comment]
Lets considered this closed by https://github.com/conan-io/conan/pull/12556

If some extra cases with user demand appears, like the linker (it seems the configuration is really neglegible compared with compilers), then we can always re-open and add them.
