### ISSUE TITLE
[bug] Adding `-s` prevents `rsync` from running

### ISSUE THREAD

**Issue by mattyclarkson** [conan-io/conan#12479]
In `conan.tools.compiler.build_type_flags` we [automatically add](https://github.com/conan-io/conan/blob/75329f63d45fbfa6542c6e7f252a15320bd3b63e/conan/tools/_compilers.py#L157) `-s` into `CFLAGS`/`CXXFLAGS`.

That is documented as:

> -s: Remove all symbol table and relocation information from the executable.

Doing this with the `rsync` build results in:

> ERROR: rsync: error while loading shared libraries: unexpected PLT reloc type 0x00

It seems odd that we are _always_ adding `-s` to our release build flags.

There is a comment in the file:

>             # FIXME: It is not clear that the "-s" is something related with the build type
>             # cmake is not adjusting it
 >            # -s: Remove all symbol table and relocation information from the executable.

Should we "`FIXME`" by removing it?

**Comment by memsharded** [comment]
Yes, I am having a look at this, and checked CMake source code, and couldn't find this as being set-up by default. Might be removed, this want to mimic the CMake defaults for Release/Debug, etc.

I am trying to check the history of CMake, but https://github.com/Kitware/CMake/blob/f3bbb37b253a1f4a26809d6f132b3996aa2e16fc is now broken. It is possible that CMake had that flag back in 2018, and no longer provides it as default, but I have been quickly looking for that change without success.

**Comment by memsharded** [comment]
Did some history investigation, this ``-s`` seems was not enough justified to be introduced in the first place.

https://github.com/conan-io/conan/pull/12518 removes this, but only for the "modern" integrations, legacy ones are left as-is, better not touch them.
