### ISSUE TITLE
[feature] Autotools.install() should permit overriding the "install" target

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12470]
Autotoos.install() is documented as an "alias" of ``self.make(target="install")`` but it would be nice if it permitted the target (i.e., "install") to be overridden with a target argument. My use case is that many recipes prefer to use the "install_sw" Makefile target rather than the "install" target. To do so, requires switching to the Autotools.make() method, but this approach requires having to explicitly specify the DESTDIR option that is obtained for free with the install() method.

Additionally, some Makefiles don't do well with parallel execution (-j > 1) during the install phase, and thus it would be nice if AutotoolsToolchain supported an additional attribute called "install_args" analogous to "make_args" as the only place one can disable parallel execution today is via make_args and that affects both the "make" and "install" Autotools methods

If these suggestions were deemed acceptable, I'd be happy to submit a change that implements them. Thanks.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @System-Arch,
Thanks a lot for the suggestion, I think this makes sense, we will add the feature for the next release.
