### ISSUE TITLE
[bug] [develop2] Drop compatibility.py ``app_compat``

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#12483]
There is a problem with the 2.0 compatibility.py default application compability:

- It tries to provide a fallback that allows requiring an ``package_type="application"`` with only ``os`` and ``arch`` defined in the settings in the profile or cli.
- It works nicely for packages without transitive dependencies, proposing a fallback to the default compiler of each OS, latest version
- But for ``application`` with transitive dependencies it fails with the ``compiler`` or ``compiler.version`` error message, because the ``compatibility.py`` only provides the fallback for applications, but not for regular libraries

The solutions could be:
- Apply the fallback to all packages, always. Make sure of course that it only fallbacks for not defined settings. Not sure what is the value, compared with just explicitly defining in the profile the default desired settings
- Drop the ``app_compat`` part completely.

A similar, alternative effect could be achieved by using the ``profile plugin`` to fill the voids in a profile, and that might also save some extra API calls maybe?

**Comment by czoido** [comment]
Closed by: https://github.com/conan-io/conan/pull/12484
