### ISSUE TITLE
conanbuildinfo.txt parsing misinterprets underscores in package names

### ISSUE THREAD

**Issue by BenchMasterFlash** [conan-io/conan#1248]
In a conanfile I used a dependency named something like `Component_A_1` and some others named like `ComponentB`. I tried to get all the include and binary dirs at build time from the `self.deps_cpp_info` object. But I only got all the dirs of `Component_A_1` and none of the others. After some research I just renamed `Component_A_1` to `ComponentA1` and everything worked fine. Currently I'm using Conan 0.21.0.

**Comment by memsharded** [comment]
Released in 0.23.
