### ISSUE TITLE
Does a modification in the Conf section value result in a different profile?

### ISSUE THREAD

**Issue by himansu2906** [conan-io/conan#12481]
We have 2 profile with similar settings but different compiler flags value inside conf section.

Our objective is to construct libraries using various combinations of compiler flags.

Issue faced :Changes to the value of the conf section are not recognized as changes to the profile.

could you please guild us how can we proceed?

**Comment by memsharded** [comment]
Hi @himansu2906 

This is not possible in Conan 1.X, unfortunately, there is no mechanism for adding "confs" to the ``package_id`` of the binaries. Conan 2.0 provide a new configuration ``tools.info.package_id:confs``, that define which other ``confs`` will be part of the ``package_ids``.

In Conan 1.X (and probably in Conan 2.0 too), the approach to follow would be to add an appropriate higher level model or abstraction in the form of custom settings/or subsettings, in which every different value of the setting represents a given combination of compiler flags. You can make your recipes to inject the flags when that setting value is defined too, if you don't want to also add the flags in the profiles. This higher level abstraction allows to manage a bit better cases that would unnecessarily produce a different binary, like changing the order of flags, or adding some flags that will not have an effect on the binary compatibility, like compiler warnings.

**Comment by himansu2906** [comment]
Hi @memsharded 

do you have example for me where we can add settings as a compiler flags in recipe file? that would help us find better approach.

**Comment by memsharded** [comment]
Yes, in the section: https://docs.conan.io/en/latest/extending/custom_settings.html#adding-new-settings

You can see, for settings:
```python
class Pkg(ConanFile):
    settings = "os", "compiler", "build_type", "arch", "distro"

    def build(self):
        cmake = CMake(self)
        if self.settings.distro == "CentOS":
            # cmake.definitions["SOME_CENTOS_FLAG"] = "Some CentOS Value"
            # With modern CMake integration
            cmake.variables["SOME_CENTOS_FLAG"] = "Some CentOS Value"
```

Something very similar would be done for a subsetting

**Comment by himansu2906** [comment]
Hello @memsharded 

Thank 

As shown below, we are executing custom commands to create the library. (we are not running )

![image](https://user-images.githubusercontent.com/109611178/200839430-d9e6f3a5-c8a1-4e40-96ae-d63f36b011f3.png)

but we want to pass Flags, definition of profile to custom build command, how can we pass these flags, definition to custom build function?

**Comment by memsharded** [comment]
Hi @himansu2906 

Sorry we didn't follow up there.
It seems your recipe had some potential issues:

- Reading ``platform.system()`` instead of using ``self.settings`` or ``self.settings_build`` is probably not correct in many cases
- Using ``subprocess.call()`` instead of ``self.run()`` is also not expected. The ``self.run()`` is the correct way to call subprocesses from Conan recipes
- The PROJECT_ROOT_PATH is most likely not necessary, specially if it is just the ``cwd``


For customizing CMake projects, you might want to check the ``CMakeToolchain`` docs: https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#customization

You can also define ``[conf]`` in your profile for ``tools.build:cxxflags`` and this can also inject flags to ``CMakeToolchain`` without modifying the recipe.

**Comment by thorsten-klein** [comment]
Info what I am doing as a workaround until we move to conan 2.x:

```
    def package_id(self):
        self.info.settings.find_package_prefer_config = self.conf.get("tools.cmake.cmaketoolchain:find_package_prefer_config", check_type=bool)
```

With this I get different `package_id` according to the conf `tools.cmake.cmaketoolchain:find_package_prefer_config`.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, and with the possible workarounds for Conan 1 mentioned here, thanks everyone!
