### ISSUE TITLE
[feature] Put settings_target from XCRun public

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#12485]
Hi,

Can the property settings_target be public inside class XCRun?

Here:
https://github.com/conan-io/conan/blob/develop/conan/tools/apple/apple.py#L89-L95

Like the line `self.sdk = sdk`, we can do `self.settings = settings`?

It let us get the correct settings data when use class XCRun.

Thanks.

**Comment by memsharded** [comment]
Hi @paulocoutinhox 

We thought that adding the new ``use_settings_target`` was enough to handle the different cases, why would you need to pass different settings values? The needed one are either the "build" or "host" settings, and in the case of a cross-toolchain ``tool_requires``, the final "host" ones, which are the ``settings_target`` in that context.

**Comment by paulocoutinhox** [comment]
Don't need change nothing, just make it public.

Because today we can't get any settings data from XCRun class, because the settings are private/internal.

Or i can get the settings defined inside XCRun from any place?

**Comment by memsharded** [comment]
> Don't need change nothing, just make it public.

Not sure what you mean, the ``self.settings`` are public, also ``self.settings_build`` and ``self.settings_target``. You can read it from the recipe itself, no need to read it from inside the XCRun?

The ``.sdk`` is probably a bit legacy, I am not sure why it is also public, if it is already available in ``settings`` too.

**Comment by paulocoutinhox** [comment]
Im talking about specifically XCRun class only:

```
class XCRun(object):

    def __init__(self, conanfile, sdk=None, use_settings_target=False):
        """sdk=False will skip the flag
           sdk=None will try to adjust it automatically
           target_settings=True try to use settings_target in case they exist"""

        # FIXME: 2.0: remove "hasattr()" condition
        settings = conanfile.settings
        if use_settings_target and hasattr(conanfile, "settings_target") and conanfile.settings_target is not None:
            settings = conanfile.settings_target

        if sdk is None and settings:
            sdk = apple_sdk_name(settings)
        self.sdk = sdk
```

To we don't need repeat the logic to get correct settings, we can set a property called `settings` with the `final settings` data, in the same way that we have `sdk`.

Instead of we need repeat the same logic, we can only do things like:

```
xcrun = XCRun(self, use_settings_target=True)
sysroot = xcrun.sdk_path
settings = xcrun.settings
```

See one example:
https://github.com/nativium/nativium/blob/main/conan/darwin-toolchain/conanfile.py#L92-L103

**Comment by memsharded** [comment]
Oh, yes, now I think I understand what you mean. I think it is fine, assigning it for next 1.55

**Comment by paulocoutinhox** [comment]
https://github.com/conan-io/conan/pull/12486

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12486
