### ISSUE TITLE
Define abstract env-vars in package_info() for editable and unix_path

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#12499]
Comes from https://github.com/conan-io/conan/issues/12192#issuecomment-1308589581_

Some packages want to define env-vars with paths, and they often use ``self.package_folder`` for it, so this is broken for ``editable`` packages, for example, in which ``package_folder=None``. It also doesn't work for other abstractions over paths as ``unix_paths``, which depend on the consumer, not the package creator.

Let's investigate some mechanism that allow to define abstract env-vars for PATHs that are resolved better in the consumer side.

**Comment by franramirez688** [comment]
This issue is related to https://github.com/conan-io/conan/issues/12477

**Comment by SpaceIm** [comment]
> It also doesn't work for other abstractions over paths as `unix_paths`, which depend on the consumer, not the package creator.

Did https://github.com/conan-io/conan/pull/12598 fix this specific issue?
