### ISSUE TITLE
[question] How to apply patch to dependency from conanfile

### ISSUE THREAD

**Issue by xakod** [conan-io/conan#12492]
How to apply patch to dependency of current package?
For example, I wanna have one conanfile.py for my project. Conanfile should apply patches to dependencies. How it can be? 
I couldn't find something related here https://docs.conan.io/en/1.52/reference/conanfile/tools/files/patches.html#conan-tools-files-patch
Thanx
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Jihadist 

It is not possible to apply patches to dependencies directly from a consumer. That should be done in the recipes of the dependencies directly.
