### ISSUE TITLE
non-interactive `conan remove "*"` not working

### ISSUE THREAD

**Issue by sykhro** [conan-io/conan#12498]
### Environment Details
  * Operating System+version: Microsoft Windows 11 Pro 10.0.22000 N/A Build 22000
  * Conan version: Conan version 1.53.0
  * Python version: 3.9.13

### Steps to reproduce
1. Run `conan remove "*" -s -b -f`
2. Observe that nothing happens
3. Run `conan remove <name_of_a_package> -s -b"
4. Prompt for removal is displayed, all packages are still there

### Logs (Executed commands with output) (Include/Attach if Applicable)
None

**Comment by memsharded** [comment]
Hi @sykhro 

Not sure if I get the issue. The ``-s`` and ``-b`` arguments are used to request removing only the ``source`` folder and the ``build`` folder, which are temporary folders to build from source. But it doesn't remove the packages at all. If you want to remove the packages you need to not specify neither of those arguments. Is this the question?

**Comment by sykhro** [comment]
I might have misunderstood the `--help` as it seemed like that would remove only binaries. Does `remove` without flags also implicitly delete source and build folders?
```
Removes packages or binaries matching pattern from local cache or remote.

It can also be used to remove the temporary source or build folders in the
local conan cache. [...]
  -b [BUILDS ...], --builds [BUILDS ...]
                        By default, remove all the build folders or select one, specifying the package ID
[...]
  -s, --src             Remove source folders
  ```

**Comment by memsharded** [comment]
> Does remove without flags also implicitly delete source and build folders?

Yes, ``conan remove "*" -f`` or ``conan remove <pkg> -f`` will remove also the build and source folders, together with the package itself.

**Comment by sykhro** [comment]
I see, imo it might be worth stressing that `-s` removes *only* the source folders in the help label (same goes for `-b`). Thanks for the quick reply
