### ISSUE TITLE
[question] cmake/graphviz to have target dependencies graph

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan#12496]
Hi conan community,

I try to analyse cmake targets dependencies on an existing project using cmake (https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html) and freshly integrated with conan.
I would like to pass "--graphviz=" parameter to cmake invocation from cmake.configure() but https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake.html#configure doesn't provides a cli_args parameter as in cmake.build() method.
Would it be possible to have a cli_args parameter for configure method?
Would it be compatible with toolchain used from CMakeToolChain?

Regards.

**Comment by czoido** [comment]
Hi @EstebanDugueperoux2,

Thanks a lot for the suggestion, I'm adding this to the 1.55 to consider adding an argument to the CMake build helper via the configure method.

**Comment by czoido** [comment]
New argument `cli_args` in `configure` method will be available in Conan 1.55. Thanks a lot for the feedback @EstebanDugueperoux2
