### ISSUE TITLE
[question] When cross-compiling with tool_requires, how to correctly fill settings

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#12490]
I'm trying to make sense of the conan documentation about how to use a cross compiler (with `tool_requires`) wrapped in a conan package, however I think I'm missing some parts of the picture.

One piece of the puzzle is how to get the settings of the package that is cross compiled. This information should be available from the cross-compiler package itself because it knows for which os/platform/arch/... it can compile binaries (e.g. Linux x86_64). But I only know how to specify the settings manually or via profile when creating a package.

Is there a conan way to automatically define these settings from the toolchain package for the packages it is used to build?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SpaceIm** [comment]
You may want to take a look at `android-ndk` recipe and how `self.settings_target` is used: https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/conanfile.py

When a recipeA is used as a tool_requires of a recipeB, `self.settings_target` is equal to the target (called host in conan) settings of recipeB, so it's the information you want to rely on in recipeA if it's a cross-compiler.

So if you have recipeA (your cross-compiler) in tool_requires of a host profile when you cross-build recipeB:

attribute values of recipeA:
- self.settings_build: settings of build profile
- self.settings: settings of build profile
- self.settings_target: settings of host profile

attributes of recipeB:
- self.settings_build: settings of build profile
- self.settings: settings of host profile
- self.settings_target: None

**Comment by fschoenm** [comment]
Thanks @SpaceIm, that seems to be the information I was missing.
