### ISSUE TITLE
[question] Which settings does `CMAKE_HOST_SYSTEM_XXX` variables correspond to, Host or Build?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12503]
First of all, according to my conprehension,

- `CMAKE_SYSTEM_XXX` corresponds to **Host** Settings.
- `CMAKE_HOST_SYSTEM_XXX` corresponds to **Build** Settings.

Suppose that I'm working on **Windows** platform. And I want to cross-compile an executable which can be runned on **Linux** platform.

Based on what [Conan 2.0 documentation](https://docs.conan.io/en/2.0/tutorial/consuming_packages/cross_building_with_conan.html#conan-two-profiles-model-build-and-host-profiles) said, we should specify:

- **Windows** settings on **Build** Profile.
- **Linux** settings on **Host** Profile.

Based on what [Master CMake documentation](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#toolchain-files) said, we should specify:

- **Windows** settings for `CMAKE_HOST_SYSTEM_XXX` variables. (CMake will autodetect)
- **Linux** settings for `CMAKE_SYSTEM_XXX` variables. (We have to specify if cross-compiling)

What confused me is that there is a **HOST** word in `CMAKE_HOST_SYSTEM_XXX`. Therefore, I want to confirm whether my conprehension is correct?

**Comment by jcar87** [comment]
Hi @hwhsu1231 - your comprehension is correct - the "host" variables in CMake are autodetected and should match the "build" settings from Conan. 

I appreciate it is confusing. Conan uses the same terminology as GNU for build and host, while other tools refer to "the machine that is performing the build" as "host" .

**Comment by hwhsu1231** [comment]
@jcar87 

Thanks for your replies. BTW, there is another question confusing me (https://github.com/conan-io/conan/issues/12339). That is, what settings or contents (**at least**) I should specify for **Build** Profiles when doing **Native Building** with **MSVC** compilers.
