### ISSUE TITLE
[question] `transitive_headers` not working as expected

### ISSUE THREAD

**Issue by Linux13524** [conan-io/conan#12504]
I have the following situation: 
- I have a library `base` that depends on a library `audio` which depends on the `dr_wav` library.
- The `base` library includes the `audio.hpp` from the `audio` library which again includes the `dr_wav.h` header.

So there is a transitive header dependency to `dr_wav` from `base` and also from the `test_package` of the `audio` library.

```mermaid
graph TD;
    base-->audio;
    audio-->dr_wav;
    test_package_audio[audio test_package]-->audio;
    base-. transitive_headers .->dr_wav;
    test_package_audio-. transitive_headers .->dr_wav;
```

This works and builds fine when defining the `dr_wav` requires in `audio` with the `transitive_headers` option: `self.requires("drwav/0.13.7", transitive_headers=True)`

But now I also have a `test_package` for `base` which depends transitively on the `dr_wav.h` header:

```mermaid
graph TD;
    base-->audio;
    audio-->dr_wav;
    test_package_base[base test_package]-->base;
    test_package_base-. transitive_headers .->audio;
    test_package_base-. transitive_headers .->dr_wav;
```

I enabled the `transitive_headers` option also for the `audio` library dependency in `base`: `self.requires("audio/1.0.0", transitive_headers=True)`  
Now the `base test_package` can find the `audio.hpp` header file, but not the `dr_wav.h`. 
I also checked the `CMakeDeps` generated files in the `test_package` and the `drwav-release-x86_64-data.cmake` file does not include the header directory:

```cmake
set(drwav_INCLUDE_DIRS_RELEASE )
set(drwav_RES_DIRS_RELEASE )
set(drwav_DEFINITIONS_RELEASE )
set(drwav_SHARED_LINK_FLAGS_RELEASE )
set(drwav_EXE_LINK_FLAGS_RELEASE )
set(drwav_OBJECTS_RELEASE )
set(drwav_COMPILE_DEFINITIONS_RELEASE )
set(drwav_COMPILE_OPTIONS_C_RELEASE )
set(drwav_COMPILE_OPTIONS_CXX_RELEASE )
set(drwav_LIB_DIRS_RELEASE "${drwav_PACKAGE_FOLDER_RELEASE}/lib")
set(drwav_BIN_DIRS_RELEASE )
set(drwav_LIBRARY_TYPE_RELEASE STATIC)
set(drwav_IS_HOST_WINDOWS_RELEASE 0)
set(drwav_LIBS_RELEASE dr_wav)
set(drwav_SYSTEM_LIBS_RELEASE )
set(drwav_FRAMEWORK_DIRS_RELEASE )
set(drwav_FRAMEWORKS_RELEASE )
set(drwav_BUILD_DIRS_RELEASE )
set(drwav_NO_SONAME_MODE_RELEASE FALSE)
```

Am I missing something or could this even be a bug? I would expect transitive headers to be transitive over more than one dependency.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

EDIT:

Implementation of minimal example from above can be found here: https://github.com/Linux13524/conan-transitive-headers

**Comment by memsharded** [comment]
Hi @Linux13524 

Quick question, which exact version of Conan are you using?

**Comment by Linux13524** [comment]
Oh, sorry, I forgot to add. It is the newest v2: **2.0.0-beta4**

**Comment by memsharded** [comment]
I am doing a "core graph" test, and apparently the "header" trait is ok:
```python
 def test_four_levels_transitive_headers(self):
        # app -> libc/0.1 -> libb0.1  -> liba0.1
        self.recipe_cache("liba/0.1")
        self.recipe_conanfile("libb/0.1",
                              GenConanfile().with_requirement("liba/0.1", transitive_headers=True))
        self.recipe_conanfile("libc/0.1",
                              GenConanfile().with_requirement("libb/0.1", transitive_headers=True))
        consumer = self.recipe_consumer("app/0.1", ["libc/0.1"])

        deps_graph = self.build_consumer(consumer)

        self.assertEqual(4, len(deps_graph.nodes))
        app = deps_graph.root
        libc = app.dependencies[0].dst
        libb = libc.dependencies[0].dst
        liba = libb.dependencies[0].dst

        self._check_node(app, "app/0.1", deps=[libc])
        self._check_node(libc, "libc/0.1#123", deps=[libb], dependents=[app])
        self._check_node(libb, "libb/0.1#123", deps=[liba], dependents=[libc])
        self._check_node(liba, "liba/0.1#123", dependents=[libb])

        # node, headers, lib, build, run
        _check_transitive(app, [(libc, True, True, False, False),
                                (libb, True, True, False, False),
                                (liba, True, True, False, False)])
```

Is there any other characteristic that could be affecting? Like some being static/shared libraries? Package-types?

**Comment by Linux13524** [comment]
I just created an minimal example here: https://github.com/Linux13524/conan-transitive-headers

It implements the setup I described above with the same names. You can reproduce the problem with this:

```
git clone https://github.com/Linux13524/conan-transitive-headers.git
cd conan-transitive-headers
cd audio
conan create . --build missing  # build missing to build dr_wav
cd ../base
conan create .
```

It gives the following error for me:

```
In file included from /home/lkloeckner/.conan2/p/180438dd2f08ea77/p/include/base.hpp:3,
                 from /home/lkloeckner/tmp/conan-transitive-headers/base/test_package/src/base_test.cpp:1:
/home/lkloeckner/.conan2/p/4aafde520e0fb698/p/include/audio.hpp:3:10: fatal error: dr_wav.h: No such file or directory
```

**Comment by memsharded** [comment]
Thanks very  much for the details and the reproducible case! :) 

That really helped to investigate and debug the issue. Indeed there was one bug that appears in multi-level transitive dependencies (at least 4 levels, with 3 (the majority of our testing) was not enough). I have proposed a fix and a bunch of new testing in https://github.com/conan-io/conan/pull/12508, hopefully for next beta.5

**Comment by Linux13524** [comment]
Cool! Thanks for solving it so quickly! :)

**Comment by czoido** [comment]
Thanks for reporting @Linux13524, the fix: https://github.com/conan-io/conan/pull/12508 was merged and will be in next beta to be released soon.

**Comment by Linux13524** [comment]
I can confirm the beta5 with the fix works fine. Thanks again!

**Comment by memsharded** [comment]
Thanks to you @Linux13524 ! Testing and giving feedback for the 2.0 is really appreciated!
