### ISSUE TITLE
[question] conan reports  option 'no_main' doesn't exist when issue import

### ISSUE THREAD

**Issue by lijie-jiang** [conan-io/conan#12510]
My script to first install requirements and then import packages. But it throw an error and exit when import.
```
ERROR: /tmp/runtime/ifdocker-runtime/conan_import.py: option 'no_main' doesn't exist
Possible options are []
```
Below is my instructions:
```
conan install  conanfile.py --install-folder=${build_dir} -pr:b=x86_64 -pr:h=${build_arch} -s build_type=${build_type} -s platform=${platform} --build -g json --build=missing
conan imports --install-folder=${build_dir} --import-folder=${install_dir} conan_import.py
```
Below is part of my conan_import.py file:
```
import os
from conans import ConanFile, tools

class PackageImportConan(ConanFile):
  def imports(self):
    self.copy("*", src="lib", dst="libs")
    self.copy("*", src="conf", dst="conf")
    self.copy("*", src="bin", dst="bin")
```
And my conanfile.py file:
```
class ExampleConan(ConanFile):
    name = "example"
    version = get_version()
    branch = "master"
    generators = "cmake", "cmake_find_package", "cmake_paths"
    settings = "os", "arch", "compiler", "build_type", "platform"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "no_main": [True, False],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
        "no_main": False,
    }
```
Thanks for any reply. Conan version is below:
`Conan version 1.53.0`
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @lijie-jiang 

I think there might be some misconception in how the ``imports`` work:

- The first ``conan install  conanfile.py`` install the dependencies only of ``conanfile.py``, but doesn't create a package for the ``conanfile`` itself
- You are trying to reuse the install folder of one ``conanfile.py`` for another ``conan_imports.py`` conanfile. It doesn't work that way. You need to do the ``conan install`` + ``conan imports`` over the same conanfile.py.

Also, as we are going to deprecate some of those features in Conan 2.0, I'd recommend the following:

- To be ready for 2.0, it is better to drop ``imports()`` method, and use a ``generate()`` method.
- The ``self.copy()`` is replaced by ``copy(self, ...)`` from ``from conan.tools.files import copy``
- The ``"cmake", "cmake_find_package", "cmake_paths"`` generators are replaced by ``CMakeToolchain`` and ``CMakeDeps``

**Comment by lijie-jiang** [comment]
> Hi @lijie-jiang
> 
> I think there might be some misconception in how the `imports` work:
> 
> * The first `conan install  conanfile.py` install the dependencies only of `conanfile.py`, but doesn't create a package for the `conanfile` itself
> * You are trying to reuse the install folder of one `conanfile.py` for another `conan_imports.py` conanfile. It doesn't work that way. You need to do the `conan install` + `conan imports` over the same conanfile.py.
> 
> Also, as we are going to deprecate some of those features in Conan 2.0, I'd recommend the following:
> 
> * To be ready for 2.0, it is better to drop `imports()` method, and use a `generate()` method.
> * The `self.copy()` is replaced by `copy(self, ...)` from `from conan.tools.files import copy`
> * The `"cmake", "cmake_find_package", "cmake_paths"` generators are replaced by `CMakeToolchain` and `CMakeDeps`

Hello memsharded,
Much appreciated it. For now I could use the same conanfile.py to generate a new package from the imported objects. I would also consider to use generated method instead of import().
