### ISSUE TITLE
Adding framework flags to exelinkflags breaks CMake target link flags.

### ISSUE THREAD

**Issue by tru** [conan-io/conan#1251]
In my main conanfile:

```
  def package_info(self):
    if self.settings.os == "Macos":
      self.cpp_info.sharedlinkflags = ["-framework Foundation"]
      self.cpp_info.exelinkflags = self.cpp_info.sharedlinkflags
```

in my test package file:

```
PROJECT(PackageTest)
cmake_minimum_required(VERSION 2.8.12)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

ADD_EXECUTABLE(test test.cpp)
TARGET_LINK_LIBRARIES(test CONAN_PKG::pkg)
```

generated build fails with:

```
ld: framework not found -lFoundation
```

looking at the link line something weird happens:
```
-framework -lFoundation -framework -lFoundation
```

**Comment by jgsogo** [comment]
This has been working for several releases, we broke it and fix it again in `1.27.1` (https://github.com/conan-io/conan/pull/7322). I think it is time to close this issue.

Just in case someone arrives at this issue, there is a field dedicated to frameworks: `cpp_info.frameworks = ['Foundation']`
