### ISSUE TITLE
[feature] 2.0 "skip confirmation" and "overwrite/delete" in the CLI should be consistent

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12523]
Currently in 2.0 beta 5 theres are a few command flags that are still very awkward and each command has it's own special meanings. For example

```sh
$ conan upload -h
  --force               Force the upload of the artifacts even if the revision already exists in
                        the server
  --check               Perform an integrity check, using the manifests, before upload
  -c, --confirm         Upload all matching recipes without confirmation
```

```sh
$ conan remove -h
  -f, --force           Remove without requesting a confirmation
```

***

These two are the same, the upload cmd is missing the short hand `-f` and remove has a different meaning 🙈 

```sh
$ conan new -h
  -f, --force           Overwrite file if exists
```

```sh
$ conan profile detect -h
  -f, --force           Overwrite file if exists
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The shortcut for ``-f`` can definitely be added.
What do you suggest to improve the UI? ``conan remove -c``?

**Comment by prince-chrismc** [comment]
Definitely should be `-c`

I think remove could have both for UX. It's  a common convention with `rm -f` it could be an alias for convience?

**Comment by memsharded** [comment]
> I think remove could have both for UX. It's a common convention with rm -f it could be an alias for convience?

This was our rationale.

But something that we are trying to do in 2.0 is remove ambiguity or redundancy. Having 2 different args to do exactly the same is not great, I'd prefer to chose one and use that one always. Lets get the team opinion too.

**Comment by prince-chrismc** [comment]
Lets commit to `-c` for confirm them 👍

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/12636
