### ISSUE TITLE
[bug] 2.0 Can't compile `zlib` with `clang` on `Windows`

### ISSUE THREAD

**Issue by MLIOSBond** [conan-io/conan#12527]
### Environment Details (include every applicable attribute)
  * Operating System+version: `Windows 10`
  * Compiler+version: 

```
clang version 15.0.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

  * Conan version: `Conan version 2.0.0-beta4`
  * Python version: `Python 3.7.3`

### Steps to reproduce (Include if Applicable)

So I'm learning Conan by going through [tutorials][1] one by one. I reached up to [linking the application dependencies as shared libraries][2]. In that tutorial the docs show us how to use shared libs (`zlib` in the example) via Conan.
I tried running the suggested command to get/build the lib:

```bash
conan install . --output-folder=build --build=missing --options=zlib/1.2.11:shared=True
```

but `clang` can't recognize the `-i` parameter:

```
clang: error: unknown argument: '-i'
```

The source of the error is in the following code block in `zlib`: [CMakeLists.txt][3] (`zlib` github repository, line [146][4] in particular).

Actually the `github` repository is fine. I guess that the following Conan patch in `zlib` breaks `clang` (the same code block in the Conan `zlib`):

```cmake
if(WIN32 AND NOT MSVC) # <--- 'if(MINGW)' in the original repository
    # This gets us DLL resource information when compiling on MinGW.
    if(NOT CMAKE_RC_COMPILER)
        set(CMAKE_RC_COMPILER windres.exe)
    endif()

    add_custom_command(OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/zlib1rc.obj
                       COMMAND ${CMAKE_RC_COMPILER}
                            -D GCC_WINDRES
                            -I ${CMAKE_CURRENT_SOURCE_DIR}
                            -I ${CMAKE_CURRENT_BINARY_DIR}
                            -o ${CMAKE_CURRENT_BINARY_DIR}/zlib1rc.obj
                            -i ${CMAKE_CURRENT_SOURCE_DIR}/win32/zlib1.rc)
    set(ZLIB_DLL_SRCS ${CMAKE_CURRENT_BINARY_DIR}/zlib1rc.obj)
endif()
```

Note if I comment this code block entirely in the downloaded (by Conan) source code and simply `cd` into that `src` directory &mdash; I can build `zlib` just fine with the following command (`CMakeCache.txt` is previously generated by Conan):

```bash
cd "/c/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/src"
cmake -S . -B ../build/Release -G Ninja
cmake --build ../build/Release
```

Am I missing something?

### Logs (Executed commands with output) (Include/Attach if Applicable)

<details>
  <summary>Console log</summary>
    
  ```
  D:\Programs\projects\my\conan-learning\examples2\tutorial\consuming_packages\different_configurations>conan install . --output-folder=build-shared --build=missing --options=zlib/*:shared=True
  
  -------- Input profiles --------
  Profile host:
  [settings]
  arch=x86_64
  build_type=Release
  compiler=clang
  compiler.cppstd=gnu14
  compiler.libcxx=libstdc++11
  compiler.version=15
  os=Windows
  [options]
  zlib/*:shared=True
  [conf]
  tools.cmake.cmaketoolchain:generator=Ninja
  
  Profile build:
  [settings]
  arch=x86_64
  build_type=Release
  compiler=clang
  compiler.cppstd=gnu14
  compiler.libcxx=libstdc++11
  compiler.version=15
  os=Windows
  [conf]
  tools.cmake.cmaketoolchain:generator=Ninja
  
  
  -------- Computing dependency graph --------
  Graph root
      conanfile.txt: D:\Programs\projects\my\conan-learning\examples2\tutorial\consuming_packages\different_configurations\conanfile.txt
  Requirements
      zlib/1.2.11#8b23adc7acd6f1d6e220338a78e3a19e - Cache
  Build requirements
      cmake/3.19.8#7c53e8476ea7485f06e2b463d88f6787 - Cache
  
  -------- Computing necessary packages --------
  Requirements
      zlib/1.2.11#8b23adc7acd6f1d6e220338a78e3a19e:2232cfb4105d66c5d7b6ec6826e144eb6fd0956e - Build
  Build requirements
      cmake/3.19.8#7c53e8476ea7485f06e2b463d88f6787:522dcea5982a3f8a5b624c16477e47195da2f84f#0d69223fe2448b1584890b407123254a - Cache
  
  -------- Installing packages --------
  
  -------- Installing (downloading, building) binaries... --------
  cmake/3.19.8: Already installed!
  cmake/3.19.8: Appending PATH environment variable: C:\Users\user\.conan2\p\6fc1381a4bdce242\p\bin
  zlib/1.2.11: Copying sources to build folder
  zlib/1.2.11: Building your package in C:\Users\user\.conan2\p\tmp\a29936c339fab5f6\b
  zlib/1.2.11: Calling generate()
  zlib/1.2.11: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
  zlib/1.2.11: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\Users\user\.conan2\p\tmp\a29936c339fab5f6\b\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
  zlib/1.2.11: Aggregating env generators
  zlib/1.2.11: Calling build()
  zlib/1.2.11: CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\Users\user\.conan2\p\tmp\a29936c339fab5f6\b\src"
  zlib/1.2.11: RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\Users\user\.conan2\p\tmp\a29936c339fab5f6\b\src"
  -- Using Conan toolchain: C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/build/generators/conan_toolchain.cmake
  -- Conan toolchain: Setting BUILD_SHARED_LIBS = ON
  -- The C compiler identification is Clang 15.0.3 with GNU-like command-line
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of off64_t
  -- Check size of off64_t - failed
  -- Looking for fseeko
  -- Looking for fseeko - not found
  -- Looking for unistd.h
  -- Looking for unistd.h - not found
  -- Renaming
  --     C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/src/zconf.h
  -- to 'zconf.h.included' because this file is included with zlib
  -- but CMake generates it automatically in the build directory.
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/build/Release
  zlib/1.2.11: CMake command: cmake --build "C:\Users\user\.conan2\p\tmp\a29936c339fab5f6\b\build\Release" -- -j12
  zlib/1.2.11: RUN: cmake --build "C:\Users\user\.conan2\p\tmp\a29936c339fab5f6\b\build\Release" -- -j12
  [1/17] Generating zlib1rc.obj
  FAILED: zlib1rc.obj C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/build/Release/zlib1rc.obj
  cmd.exe /C "cd /D "C:\Users\user\.conan2\p\tmp\a29936c339fab5f6\b\build\Release" && clang -D GCC_WINDRES -I "C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/src" -I "C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/build/Release" -o "C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/build/Release/zlib1rc.obj" -i "C:/Users/user/.conan2/p/tmp/a29936c339fab5f6/b/src/win32/zlib1.rc""
  clang: error: unknown argument: '-i'
  ninja: build stopped: subcommand failed.
  zlib/1.2.11: ERROR:
  Package '2232cfb4105d66c5d7b6ec6826e144eb6fd0956e' build failed
  zlib/1.2.11: WARN: Build folder C:\Users\user\.conan2\p\tmp\a29936c339fab5f6\b\build\Release
  ERROR: zlib/1.2.11: Error in build() method, line 90
          cmake.build()
          ConanException: Error 1 while executing
  ```
  
</details>

[1]: https://docs.conan.io/en/2.0/tutorial/consuming_packages.html
[2]: https://docs.conan.io/en/2.0/tutorial/consuming_packages/different_configurations.html#modifying-options-linking-the-application-dependencies-as-shared-libraries
[3]: https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/CMakeLists.txt#L134-L148
[4]: https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/CMakeLists.txt#L146

**Comment by memsharded** [comment]
Hi @MLIOSBond 

Some things that I would like to check:

- Are you sure you are using the recipe ``zlib`` from the 2.0 repo, and not from ConanCenter? Even the ``zlib`` recipe we have in the temporary repo for 2.0, might not be fully ready for 2.0
- For that it would be great to first validate that things are working for a simple "hello world" project. Please try your setup, building a ``conan new cmake_lib -d name=hello -d version=0.1``, then ``conan create .``. That way we can think if it is a Conan bug or a zlib recipe issue
- It also seems that your profile is not fully correct. Did you read the recent blog post: https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html? If the clang flavour is the one targeting "msvc" compatibility, then ``compiler.libcxx=libstdc++11`` shouldn't be defined, but still ``compiler.runtime`` and others. Please check that and try configuring your profile accordingly

**Comment by MLIOSBond** [comment]
I should've stated upfront that I'm a complete beginner in Conan, and I don't fully understand Conan terminology yet.

* As I said, I'm a complete beginner. How can I verify that I'm using 2.0 repo instead of ConanCenter? Will this command do that?

  ```bash
  conan remote add conanv2 https://conanv2beta.jfrog.io/artifactory/api/conan/conan --index 0
  ```

  If it will, then yes &mdash; I did everything the [tutorial][1] suggests. Also as I'm only going through tutorials, I don't yet understand what a recipe is.

* Note that this [tutorial][1] works perfectly fine with my setup (`zlib` static lib and a compressor example). I'm 99% sure that the bug is in the recipe (even though at this point I don't know what it is). The bug is likely in the patched (by Conan) root CMakeLists.txt, line 134, because if I comment it out &mdash; everything works as the tutorial goes further. In the [original repo][2]
it's `if(MINGW)`, but `if(WIN32 AND NOT MSVC)` in the patched one. `clang` enters that branch and receives an invalid/unknown `-i` argument.



  <details>
    <summary> Anyway, running `conan new <...>` and then `create` gives me the following log </summary>
      
    ```bash
    $ cd /d/Programs/projects/my/conan-learning/hello-world
    
    $ conan new cmake_lib -d name=hello -d version=0.1
    File saved: CMakeLists.txt
    File saved: conanfile.py
    File saved: include/hello.h
    File saved: src/hello.cpp
    File saved: test_package/CMakeLists.txt
    File saved: test_package/conanfile.py
    File saved: test_package/src/example.cpp
    
    $ ls -al
    total 5
    drwxr-xr-x 1 user 197121    0 Nov 14 07:30 ./
    drwxr-xr-x 1 user 197121    0 Nov 14 07:05 ../
    -rw-r--r-- 1 user 197121  235 Nov 14 07:30 CMakeLists.txt
    -rw-r--r-- 1 user 197121 1316 Nov 14 07:30 conanfile.py
    drwxr-xr-x 1 user 197121    0 Nov 14 07:30 include/
    drwxr-xr-x 1 user 197121    0 Nov 14 07:30 src/
    drwxr-xr-x 1 user 197121    0 Nov 14 07:30 test_package/
    
    $ conan create .
    Exporting the recipe
    hello/0.1: Exporting package recipe
    hello/0.1: Copied 1 '.txt' file: CMakeLists.txt
    hello/0.1: Copied 1 '.cpp' file: hello.cpp
    hello/0.1: Copied 1 '.h' file: hello.h
    hello/0.1 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
    hello/0.1 exports_sources: Copied 1 '.cpp' file: hello.cpp
    hello/0.1 exports_sources: Copied 1 '.h' file: hello.h
    hello/0.1: Using the exported files summary hash as the recipe revision: 16434eda3b0dd870e218e270e2677b8a
    hello/0.1: A new conanfile.py version was exported
    hello/0.1: Folder: C:\Users\user\.conan2\p\192426f9dec92eae\e
    hello/0.1: Exported revision: 16434eda3b0dd870e218e270e2677b8a
    
    -------- Input profiles --------
    Profile host:
    [settings]
    arch=x86_64
    build_type=Release
    compiler=clang
    compiler.cppstd=gnu14
    compiler.libcxx=libstdc++11
    compiler.version=15
    os=Windows
    [conf]
    tools.cmake.cmaketoolchain:generator=Ninja
    
    Profile build:
    [settings]
    arch=x86_64
    build_type=Release
    compiler=clang
    compiler.cppstd=gnu14
    compiler.libcxx=libstdc++11
    compiler.version=15
    os=Windows
    [conf]
    tools.cmake.cmaketoolchain:generator=Ninja
    
    
    -------- Computing dependency graph --------
    Graph root
        virtual
    Requirements
        hello/0.1#16434eda3b0dd870e218e270e2677b8a - Cache
    
    -------- Computing necessary packages --------
    hello/0.1: Forced build from source
    Requirements
        hello/0.1#16434eda3b0dd870e218e270e2677b8a:72913234111272f5ee983e191f2a4b7d970b24f8 - Build
    
    -------- Installing packages --------
    
    -------- Installing (downloading, building) binaries... --------
    hello/0.1: Copying sources to build folder
    hello/0.1: Building your package in C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b
    hello/0.1: Calling generate()
    hello/0.1: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
    hello/0.1: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
    hello/0.1: Aggregating env generators
    hello/0.1: Calling build()
    hello/0.1: CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/.conan2/p/tmp/f873033fafa810ca/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/user/.conan2/p/tmp/f873033fafa810ca/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b\."
    hello/0.1: RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/.conan2/p/tmp/f873033fafa810ca/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/user/.conan2/p/tmp/f873033fafa810ca/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b\."
    -- Using Conan toolchain: C:/Users/user/.conan2/p/tmp/f873033fafa810ca/b/build/generators/conan_toolchain.cmake
    -- Conan toolchain: C++ Standard 14 with extensions ON
    -- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
    -- The CXX compiler identification is Clang 15.0.3 with GNU-like command-line
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        CMAKE_POLICY_DEFAULT_CMP0091
    
    
    -- Build files have been written to: C:/Users/user/.conan2/p/tmp/f873033fafa810ca/b/build/Release
    hello/0.1: CMake command: cmake --build "C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b\build\Release" -- -j12
    hello/0.1: RUN: cmake --build "C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b\build\Release" -- -j12
    [1/2] Building CXX object CMakeFiles/hello.dir/src/hello.cpp.obj
    CLANG_~1: warning: argument unused during compilation: '-stdlib=libstdc++' [-Wunused-command-line-argument]
    [2/2] Linking CXX static library hello.lib
    hello/0.1: Package '72913234111272f5ee983e191f2a4b7d970b24f8' built
    hello/0.1: Build folder C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b\build\Release
    hello/0.1: Generated conaninfo.txt
    hello/0.1: Generating the package
    hello/0.1: Temporary package folder C:\Users\user\.conan2\p\tmp\f873033fafa810ca\p
    hello/0.1: Calling package()
    hello/0.1: CMake command: cmake --install "C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b\build\Release" --prefix "C:/Users/user/.conan2/p/tmp/f873033fafa810ca/p"
    hello/0.1: RUN: cmake --install "C:\Users\user\.conan2\p\tmp\f873033fafa810ca\b\build\Release" --prefix "C:/Users/user/.conan2/p/tmp/f873033fafa810ca/p"
    -- Install configuration: "Release"
    -- Installing: C:/Users/user/.conan2/p/tmp/f873033fafa810ca/p/lib/hello.lib
    -- Installing: C:/Users/user/.conan2/p/tmp/f873033fafa810ca/p/include/hello.h
    hello/0.1 package(): Packaged 1 '.h' file: hello.h
    hello/0.1 package(): Packaged 1 '.lib' file: hello.lib
    hello/0.1: Package '72913234111272f5ee983e191f2a4b7d970b24f8' created
    hello/0.1: Created package revision ce092ff68bf80d56f39b4851b5ac6981
    hello/0.1: Full package reference: hello/0.1#16434eda3b0dd870e218e270e2677b8a:72913234111272f5ee983e191f2a4b7d970b24f8#ce092ff68bf80d56f39b4851b5ac6981
    hello/0.1: Package folder C:\Users\user\.conan2\p\9542354841c49b50\p
    
    -------- test_package: Computing dependency graph --------
    Graph root
        hello/0.1 (test package): D:\Programs\projects\my\conan-learning\hello-world\test_package\conanfile.py
    Requirements
        hello/0.1#16434eda3b0dd870e218e270e2677b8a - Cache
    
    -------- test_package: Computing necessary packages --------
    Requirements
        hello/0.1#16434eda3b0dd870e218e270e2677b8a:72913234111272f5ee983e191f2a4b7d970b24f8#ce092ff68bf80d56f39b4851b5ac6981 - Cache
    
    -------- test_package: Installing packages --------
    
    -------- Installing (downloading, building) binaries... --------
    hello/0.1: Already installed!
    
    -------- Testing the package --------
    hello/0.1 (test package): Writing generators to D:\Programs\projects\my\conan-learning\hello-world\test_package\test_output\build\generators
    hello/0.1 (test package): Generator 'CMakeToolchain' calling 'generate()'
    hello/0.1 (test package): Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
    hello/0.1 (test package): If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G Ninja -DCMAKE_TOOLCHAIN_FILE=D:\Programs\projects\my\conan-learning\hello-world\test_package\test_output\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
    hello/0.1 (test package): Generator 'CMakeDeps' calling 'generate()'
    hello/0.1 (test package): Aggregating env generators
    
    -------- Testing the package: Building --------
    hello/0.1 (test package): Calling build()
    hello/0.1 (test package): CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="D:/Programs/projects/my/conan-learning/hello-world/test_package/test_output/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="D:/Programs/projects/my/conan-learning/hello-world/test_package/test_output" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "D:\Programs\projects\my\conan-learning\hello-world\test_package\."
    hello/0.1 (test package): RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="D:/Programs/projects/my/conan-learning/hello-world/test_package/test_output/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="D:/Programs/projects/my/conan-learning/hello-world/test_package/test_output" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "D:\Programs\projects\my\conan-learning\hello-world\test_package\."
    -- Using Conan toolchain: D:/Programs/projects/my/conan-learning/hello-world/test_package/test_output/build/generators/conan_toolchain.cmake
    -- Conan toolchain: C++ Standard 14 with extensions ON
    -- The CXX compiler identification is Clang 15.0.3 with GNU-like command-line
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Conan: Target declared 'hello::hello'
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        CMAKE_POLICY_DEFAULT_CMP0091
    
    
    -- Build files have been written to: D:/Programs/projects/my/conan-learning/hello-world/test_package/test_output/build/Release
    hello/0.1 (test package): CMake command: cmake --build "D:\Programs\projects\my\conan-learning\hello-world\test_package\test_output\build\Release" -- -j12
    hello/0.1 (test package): RUN: cmake --build "D:\Programs\projects\my\conan-learning\hello-world\test_package\test_output\build\Release" -- -j12
    [1/2] Building CXX object CMakeFiles/example.dir/src/example.cpp.obj
    CLANG_~1: warning: argument unused during compilation: '-stdlib=libstdc++' [-Wunused-command-line-argument]
    [2/2] Linking CXX executable example.exe
    clang++: warning: argument unused during compilation: '-stdlib=libstdc++' [-Wunused-command-line-argument]
    
    -------- Testing the package: Running test() --------
    hello/0.1 (test package): Running test()
    hello/0.1 (test package): RUN: .\example
    hello/0.1: Hello World Release!
      hello/0.1: _M_X64 defined
      hello/0.1: __x86_64__ defined
      hello/0.1: _MSC_VER1921
      hello/0.1: _MSVC_LANG201402
      hello/0.1: __cplusplus201402
      hello/0.1: __clang_major__15
    
    $ test_package/test_output/build/Release/example.exe
    hello/0.1: Hello World Release!
      hello/0.1: _M_X64 defined
      hello/0.1: __x86_64__ defined
      hello/0.1: _MSC_VER1921
      hello/0.1: _MSVC_LANG201402
      hello/0.1: __cplusplus201402
      hello/0.1: __clang_major__15
    ```

* My profile might be incorrect because when I run `conan profile detect --force` the first time (as the [tutorial][1] suggests) &mdash; it didn't detect my profile correctly, and it doesn't say what to do if the profile is incorrect. So I just googled and tried a bunch of combinations (took someone's gcc profile from Linux and tweaked it to make it work on clang) &mdash; and it worked just fine.

  I'll read the blogpost you linked and I'll try to configure my profile a bit later, thanks for that! (Perhaps the first tutorial should have a link to that article in the case when Conan can't detect the profile?)

  But as I said earlier: the bug is extremely likely in the patched `zlib` CMakeLists.txt (line 134) provided by Conan &mdash; everything compiles fine if I remove/comment out that `if` block completely.

---

A general question: how should one approach Conan? I'm just going through [docs][3] one by one. Is there a different approach?

[1]: https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html#build-a-simple-cmake-project-using-conan
[2]: https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/CMakeLists.txt#L134
[3]: https://docs.conan.io/en/2.0/index.html

**Comment by memsharded** [comment]
> I should've stated upfront that I'm a complete beginner in Conan, and I don't fully understand Conan terminology yet.

If you are a completely beginner, I'd probably recommend a bit of a different approach:

- If you are in Windows, try to stick to the ``msvc`` compilers initially, and then move to ``clang``, because there might be different issues, specially related to open source libraries and packages that might have some issues with clang in Windows, as it is not that mainstream (getting there, but not yet)
- Probably start a bit with the Conan 1.X if you are going to be using a bunch of ConanCenter recipes, as most of them are not that ready for 2.0 (we are on it). Of course we are super happy if you are already using 2.0, that is great, but be aware that for ConanCenter recipes, might take a bit longer.
- Yes, the command ``conan remote add conanv2 https://conanv2beta.jfrog.io/artifactory/api/conan/conan --index 0`` is necessary. Also, you can ``conan remote remove conancenter`` to make sure that you are not pulling things accidentally from ConanCenter. ``conan remote list`` will give you the list of remotes.

> Note that this [tutorial](https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html#build-a-simple-cmake-project-using-conan) works perfectly fine with my setup (zlib static lib and a compressor example). I'm 99% sure that the bug is in the recipe (even though at this point I don't know what it is). The bug is likely in the patched (by Conan) root CMakeLists.txt, line 134, because if I comment it out — everything works as the tutorial goes further. In the [original repo](https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/CMakeLists.txt#L134)
it's if(MINGW), but if(WIN32 AND NOT MSVC) in the patched one. clang enters that branch and receives an invalid/unknown -i argument.

Yes, totally, it is very possible. That should be reported in the ``conan-center-index`` repo, the only issue is that the community is right now focused on 2.0 migration, so fixing things to support Clang in Windows, might take longer (months). In any case the feedback is super appreciated and valuable to keep improving recipes there.

> My profile might be incorrect because when I run conan profile detect --force the first time (as the [tutorial](https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html#build-a-simple-cmake-project-using-conan) suggests) — it didn't detect my profile correctly, and it doesn't say what to do if the profile is incorrect. So I just googled and tried a bunch of combinations (took someone's gcc profile from Linux and tweaked it to make it work on clang) — and it worked just fine.

> I'll read the blogpost you linked and I'll try to configure my profile a bit later, thanks for that! (Perhaps the first tutorial should have a link to that article in the case when Conan can't detect the profile?)

Yes, the auto-detect of profile is not to be trusted. Clang detection in Windows specially might not be good at all. For "production" the recommended is to store your profiles in one repo and use ``conan config install`` to distribute it (that also is useful to distribute remotes, settings, hooks, and all other conan extensions and conf)

> A general question: how should one approach Conan? I'm just going through [docs](https://docs.conan.io/en/2.0/index.html) one by one. Is there a different approach?

It is true that the current state now in the 1.X->2.0 transition is a bit messy, because Conan 1.X docs are a bit too messy, and the 2.0 docs are new and clean, but they are still lacking a lot of information.
If you like video format, the free Academy courses (only 1.X atm) are pretty good.

**Comment by MLIOSBond** [comment]
As a side question: is it possible to completely avoid using `msvc` on Windows when using Conan?

I tried setting the profile in the correct way (as suggested in the [article][1]), but I get the following error even in the [first tutorial][2]:
```
ERROR: zlib/1.2.11: Error in generate() method, line 68
        tc.generate()
        ConanException: VS non-existing installation: Visual Studio 17
```

<details>
  <summary>Log</summary>

  ```
  D:\Programs\projects\my\conan-learning\examples2\tutorial\consuming_packages\simple_cmake_project>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  **********************************************************************
  ** Visual Studio 2017 Developer Command Prompt v15.9.11
  ** Copyright (c) 2017 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x64'
  
  D:\Programs\projects\my\conan-learning\examples2\tutorial\consuming_packages\simple_cmake_project>conan install . --output-folder=build-llvm --build=missing
  
  -------- Input profiles --------
  Profile host:
  [settings]
  arch=x86_64
  build_type=Release
  compiler=clang
  compiler.cppstd=gnu14
  compiler.runtime=dynamic
  compiler.runtime_type=Release
  compiler.runtime_version=v143
  compiler.version=15
  os=Windows
  [conf]
  tools.cmake.cmaketoolchain:generator=Ninja
  
  Profile build:
  [settings]
  arch=x86_64
  build_type=Release
  compiler=clang
  compiler.cppstd=gnu14
  compiler.runtime=dynamic
  compiler.runtime_type=Release
  compiler.runtime_version=v143
  compiler.version=15
  os=Windows
  [conf]
  tools.cmake.cmaketoolchain:generator=Ninja
  
  
  -------- Computing dependency graph --------
  Graph root
      conanfile.txt: D:\Programs\projects\my\conan-learning\examples2\tutorial\consuming_packages\simple_cmake_project\conanfile.txt
  Requirements
      zlib/1.2.11#8b23adc7acd6f1d6e220338a78e3a19e - Cache
  
  -------- Computing necessary packages --------
  Requirements
      zlib/1.2.11#8b23adc7acd6f1d6e220338a78e3a19e:c1242107167bc33e52b05abcd4c020933248f924 - Build
  
  -------- Installing packages --------
  
  -------- Installing (downloading, building) binaries... --------
  zlib/1.2.11: Copying sources to build folder
  zlib/1.2.11: Building your package in C:\Users\user\.conan2\p\tmp\cc299642a1607b7e\b
  zlib/1.2.11: Calling generate()
  ERROR: zlib/1.2.11: Error in generate() method, line 68
          tc.generate()
          ConanException: VS non-existing installation: Visual Studio 17
  ```

</details>

Probably my installation of VS is broken, but I don't feel like installing it at the moment (that's why I'm using `clang`)

[1]: https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html
[2]: https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html

**Comment by memsharded** [comment]
> As a side question: is it possible to completely avoid using msvc on Windows when using Conan?

Just it is totally possible, it is perfectly fine to use gcc (mingw), or some of the clang flavors (msys2) that doesn't need msvc at all. A different story is that the recipes in ConanCenter will work with these, sometimes the build system scripts might not be prepared at all to handle these compilers, so it really depends on the library itself. Some have the compilers hardcoded in their scripts, so they might even require patching to work (Many recipes in ConanCenter apply patches to build scripts to make sure they can be built in different OSs, even with the mainstream compilers)

My recommendation @MLIOSBond is always starting from a template ``conan new hello/0.1 -m=cmake_lib``, to make sure that the setup, installation, profiles is working then only trying to build other more complex libraries.

> Probably my installation of VS is broken, but I don't feel like installing it at the moment (that's why I'm using clang)

Well, that also depends on the clang flavor. The LLVM/CLang still needs VS17 installed, it is only if you move to Msys2/Clang that VS17 is not needed. But it is also true that Msys2/Clang support by third party libraries build scripts will certainly be worse in the general case. From your profiles it really seems that you are aiming to use LLVM/CLang, and for that you totally need VS17 correctly installed

>  I don't feel like installing it at the moment 

I'd recommend not trying to avoid it. Not sure what is your C++ experience in Windows, but if you are developing in Windows, this is the mainstream compiler by far, you better start with it, specially if you still intend to use recipes from ConanCenter, and only start trying it later when gained more experience.

**Comment by MLIOSBond** [comment]
Well, fair enough. I'll consider installing it then.

I'll update this thread on the next weekend based on the results. Thanks a lot!

**Comment by MLIOSBond** [comment]
@memsharded so I installed VS 2022 and was able to complete [the tutorial][1] without any errors.

The `conan profile detect --force` command found the right profile.

Also I used `Ninja` as `CMake` generator instead of `Visual Studio 2022` (it worked fine).

---

I'm curious: should I close this issue or should we wait until [the tutorial][1] works as well on `Windows` with `clang`?

[1]: https://docs.conan.io/en/2.0/tutorial/consuming_packages/different_configurations.html

**Comment by memsharded** [comment]
> @memsharded so I installed VS 2022 and was able to complete [the tutorial](https://docs.conan.io/en/2.0/tutorial/consuming_packages/different_configurations.html) without any errors.

Excellent, thanks for reporting

> I'm curious: should I close this issue or should we wait until [the tutorial](https://docs.conan.io/en/2.0/tutorial/consuming_packages/different_configurations.html) works as well on Windows with clang?

I think the best is to close it atm, because this would need to be transferred to ``conan-center-index`` repository, but as 2.0 is not GA yet, it is unlikely to get prioritized enough. I'd recommend to re-submit this repor to ``conan-center-index`` after 2.0 is finally released. Closing this now, many thanks for the feedback!
