### ISSUE TITLE
[question][2.0] Failed to use "conan inspect <pkg>/<version>" command to inspect the package?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12532]
### Problem Description

Before Conan 2.0, I usually use `conan inspect` command to check all the available options of a package. For example, running `conan inspect glew/2.2.0` command:

<details><summary>Click to expand logs</summary>

```cmd
C:\Users\hwhsu1231>conan --version
Conan version 1.54.0

C:\Users\hwhsu1231>conan inspect glew/2.2.0
name: glew
version: 2.2.0
url: https://github.com/conan-io/conan-center-index
homepage: http://github.com/nigels-com/glew
license: MIT
author: None
description: The GLEW library
topics: ('glew', 'opengl', 'wrangler', 'loader', 'binding')
generators: ['txt']
exports: None
exports_sources: None
short_paths: False
apply_env: True
build_policy: None
revision_mode: hash
settings: ('os', 'arch', 'compiler', 'build_type')
options:
    fPIC: [True, False]
    shared: [True, False]
    with_egl: [True, False]
default_options:
    fPIC: True
    shared: False
    with_egl: False
deprecated: None
```

</details>

However, I found that this command failed with Conan 2.0:

<details><summary>Click to expand logs</summary>

```cmd
C:\Users\hwhsu1231>conan --version
Conan version 2.0.0-beta5

C:\Users\hwhsu1231>conan inspect glew/2.2.0
ERROR: Conanfile not found at C:\Users\hwhsu1231\glew\2.2.0
```

</details>

After searching in the repository, I found this issue and its related PR: 

- Issue: https://github.com/conan-io/conan/issues/12247
- PR: https://github.com/conan-io/conan/pull/12263

According to the issue and the PR, there are some changes about `conan inspect` command syntax. However, it still failed with the following example commands. What should I do to reproduce the usage of `conan inspect` command of Conan 1.0 when using Conan 2.0?

```cmd
C:\Users\hwhsu1231>conan inspect --reference=glew/2.2.0 --remote=conancenter
usage: conan inspect [-h] [-f FORMAT] [-v [V]] [--logger] path
conan inspect: error: the following arguments are required: path
ERROR: Exiting with code: 2
```

```cmd
C:\Users\hwhsu1231>conan inspect --reference=glew/2.2.0 --cache
usage: conan inspect [-h] [-f FORMAT] [-v [V]] [--logger] path
conan inspect: error: the following arguments are required: path
ERROR: Exiting with code: 2
```

### Environments and Versions

- OS+version: **Windows 11**
- Conan version: **2.0.0-beta5**

**Comment by AbrilRBS** [comment]
Hi! Sorry about the radio silence. I guess you've solved this by now, but posting here for posterity:
`conan inspect` needs a path in Conan 2 - This works well in conjunction with `conan cache path` to get specific folders for any reference in the current cache

Closing this as solved, feel free to reopen/create a new issue should you have any other questions or requests, thanks!
