### ISSUE TITLE
[question] How to distinguish header files with the same name of different packages

### ISSUE THREAD

**Issue by shudingbo** [conan-io/conan#12530]
How to distinguish header files with the same name of different packages
- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
My programe deps two package，which contain header files with the same name。
```
// libA
- include
  - utils.h
```
```
// libB
- include
  - utils.h
```

My programe hwo to distinguish the utils.h??

**Comment by memsharded** [comment]
Hi @shudingbo 

Following C++ good practices, the actual recommendation (that not all of open source libraries would follow), is that headers should be put in a folder with the name of the package/library:
```
include/liba/utils.h
include/libb/utils.h
```
And the include paths ``-I``, should only define down to the ``include`` folder, so the source inclusion happens with:
```cpp
#include "liba/utils.h"
#include "libb/utils.h"
```

**Comment by shudingbo** [comment]
> Hi @shudingbo
> 
> Following C++ good practices, the actual recommendation (that not all of open source libraries would follow), is that headers should be put in a folder with the name of the package/library:
> 
> ```
> include/liba/utils.h
> include/libb/utils.h
> ```
> 
> And the include paths `-I`, should only define down to the `include` folder, so the source inclusion happens with:
> 
> ```c++
> #include "liba/utils.h"
> #include "libb/utils.h"
> ```

@memsharded Thanks for you reply.
We used the way you said before. Now we want to use **conan** management library, but there is no relevant way to put them under different libx in conan.  
``` 
[requires]
liba/0.1
libb/0.1
```

```cpp
#include <liba/utils.h>     // <--- the liba prefix， conan create it?
#include <libb/utils.h>

int main(){
  // something
}

```
-----
i find conanbuildinfo.cmake file, the liba like this, no **liba** prefix
```
set(CONAN_INCLUDE_DIRS_LIBA "E:/conan/data/tt2/0.1/ccc/testing/package/7b82171aee5e0ec7cbf75fafd1c7eff292107dd0/include")
```

How can I config?

**Comment by memsharded** [comment]
This is not something that the package consumers can do, this is a responsibility of the package creator, the recipe writer for ``liba`` and ``libb``. 

They should make sure that their ``package()`` method does the right thing and put the headers file inside a ``liba`` folder, it is typically changing the ``copy(...)`` calls to include the package name.

**Comment by shudingbo** [comment]
> This is not something that the package consumers can do, this is a responsibility of the package creator, the recipe writer for `liba` and `libb`.
> 
> They should make sure that their `package()` method does the right thing and put the headers file inside a `liba` folder, it is typically changing the `copy(...)` calls to include the package name.

I Get it.  Thanks more
