### ISSUE TITLE
[bug] conan creates default profile even if it is explicitly not used

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#12548]
### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu latest
  * Compiler+version: 11.2.0-1ubuntu1
  * Conan version: 1.54.0

### Steps to reproduce (Include if Applicable)
clone this project: https://github.com/AndreyMlashkin/minimalistic_conan_docker
run:
docker build .

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
Step 7/11 : RUN conan install requirements.txt --build missing -g virtualenv --profile:build=build_profile --profile:host=build_profile
 ---> Running in fc97e24628fc
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
Found gcc 11
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit /root/.conan/profiles/default and set compiler.libcxx=libstdc++11

************************************************************************************



Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=gcc
	compiler.version=11
	compiler.libcxx=libstdc++
	build_type=Release
*** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
*:shared=False
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
*:shared=False
[build_requires]
[env]

```

**Comment by AndreyMlashkin** [comment]
[full_log.txt](https://github.com/conan-io/conan/files/10014076/full_log.txt)

**Comment by memsharded** [comment]
Hi @AndreyMlashkin 

It seems there is some misconfiguration in your setup. That is not running 2.0, but it is running 1.X. 

You need to change ``RUN pip3 install conan`` in your dockerfile?

**Comment by AndreyMlashkin** [comment]
Oh, yes, sorry, I have experimented with conan2, but not all recipes from my example are ready for it, so I have back-switched to 1.54.0. I have updated the description

**Comment by AndreyMlashkin** [comment]
Conan v2 does not have this missfunction indeed.

**Comment by memsharded** [comment]
Ok, I see.  But it is not a bug, in Conan 1.X, the default profile is expected to be there, even if not directly used, due to some legacy. It was changed in 2.0 to not create it, but it cannot be changed in 1.X, as it would be breaking.

**Comment by AndreyMlashkin** [comment]
Ok, I see
