### ISSUE TITLE
[question] get RREV from dependencies inside conanfile

### ISSUE THREAD

**Issue by pasrom** [conan-io/conan#12541]
We are using `revision_mode = "scm"` for all our dependencies and we want to get the revision (=git commit id) from the dependencies inside the conanfile. Is there a possibility to achieve this?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @pasrom 

Not it is not possible. The ``recipe_revision`` is a property of the recipe, in isolation. It is the hash (or commit) of the sources, the ``conanfile.py`` and other possible files that form the recipe (might include ``exported`` sources). This is computed at ``export`` time, and the dependency graph is not resolved at all in this point, there are not dependencies.

It seems that you are interested in the ``recipe_revision_mode`` for ``package_id``. The way that the dependencies affect the consumers is not that they affect to their sources (the sources of the consumer are immutable, and that is defined and captured by a fixed ``recipe_revision`` no matter the dependencies), but the dependencies affect to the compiled binaries, and that is captured by the ``package_id``. By changing the ``package_id_mode`` to ``recipe_revision_mode``, you are making the revisions of the dependencies to be part of the ``package_id`` of the consumer.  

This talk about Conan 2.0 also includes good descriptions about "package_id_modes", and how they will be improved in 2.0: https://www.youtube.com/watch?v=kKGglzm5ous

**Comment by pasrom** [comment]
@memsharded, thank you for your quick reply.

I would like to use the commit id's from dependencies to save them in a proprietary format (package) for later use (to easy find out which commit produced this dependency, if possible without using conan).

Could I use [`self.info`](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=requirementinfo#using-package-id-for-package-dependencies) (e.g. `self.info.requires["my_lib"].full_recipe_revision`) to get the `full_recipe_revision`?

**Comment by memsharded** [comment]
Yes, you can collect information from dependencies, there are 2 possible places: the ``generate()`` method and the ``package()`` method. Most likely it makes sense in the ``generate()`` method, but depends on the use case.

Check https://docs.conan.io/en/latest/reference/conanfile/dependencies.html for more information, but basically, you can iterate the ``self.dependencies``, and for each one, you can access its full ``ref``, which includes the full recipe revision (``dep.ref.revision``). You can save all that information in a file, and if you make sure that file is ``package()`` packaged, then it will be part of the final binary package.

**Comment by memsharded** [comment]
Note also, that for achieving that, you don't really need to use the ``recipe_revision = "scm"``, but you can do the following:

- Eeach recipe, when it is "created", it can store in its ``conandata.yml`` the url and the commit that originated it, check: https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature
- Then, the consumer can easily iterate the ``dependencies`` as described above, and for each one access its full ``dep.conan_data``, so they can get from it the commit (and also the URL of the repo)

**Comment by pasrom** [comment]
Thank you for all your assistance.
