### ISSUE TITLE
[question] Review ``conan cache path``

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#12549]
I have been writing the docs for it, trying it manually, and found it quite confusing, I have been struggling a bit to use it, eg:

```
conan cache path zlib/1.2.12#6758146baf425dc62ecc5246a1e955e4:2401fa1d188d289bb25c37cfa3317e13e377a351#latest
C:\Users\memsharded\.conan2\p\8a18fc6015f5b185\e
```
Even if you provide the full path, it will still return the path to the ``export`` folder of the conanfile.py, not the package folder, and  it was surprising
```
conan cache path zlib/1.2.12#6758146baf425dc62ecc5246a1e955e4:2401fa1d188d289bb25c37cfa3317e13e377a351 --folder=package
ERROR: '--folder package' requires a valid package reference
```
The problem here is that it is missing ``#latest`` as ``package_revision``, but it is challenging to get that.

**Comment by czoido** [comment]
Closed by: https://github.com/conan-io/conan/pull/12554
