### ISSUE TITLE
[bug] tools.get() doesnt download my tarball and yet doesnt give any error

### ISSUE THREAD

**Issue by Hash17** [conan-io/conan#12545]
### Environment Details (include every applicable attribute)
  * Ubuntu 18.04.6 LTS VM
  * Conan version: 1.54.0
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
conan create -pr profile-name . package/0.2@user/testing

#tools,download from my recipe:
tools.download(download_uri, path_to_save_file_to, auth=(artifactory_user, token))

ofcourse user and token are defined

**Comment by Hash17** [comment]
I wrote a description but i cant see it unless i click on edit, so am writing it again

So am trying to use tools,get() to download a certain tarball which i know it exists for sure, remote artifactory where the tarball exists is part of ~/.conan/remotes.json, conan searh with -r=remote-name finds the package, the package is 2G and when i run my recipe it finishes in 1 second without errors, i checked ~/.conan/data/package-name/source, it is empty, same for build and package. my guess here it could be maybe timeout or credential issue or even if the remote name is wrong, why doesnt i get any error like HTTP 403,404,,,etc? i dont want to use md5 i just want there to be an error if tools.get() failed to download in general



### Environment Details (include every applicable attribute)
  * Ubuntu 18.04.6 LTS VM
  * Conan version: 1.54.0
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
conan create -pr profile-name . package/0.2@user/testing

#tools,download from my recipe:
tools.download(download_uri, path_to_save_file_to, auth=(artifactory_user, token))

ofcourse user and token are defined

**Comment by memsharded** [comment]
Hi @Hash17 

It is not fully clear if you are trying to download a tarball from an Artifactory Conan repo. 
If you are trying to do that, it might make sense, this is undefined behavior, Conan packages can only be used via the Conan APIs, fetching one of the Conan tarballs directly from a recipe is not possible.

If you are trying to download a tarball from an Artifactory generic repository, that should indeed be possible. But it is not connected at all to the Conan ``-r=remote``

It would be needed a bit more of details, like the conanfile with at least the full ``source()`` methods, with all the values, like the URL (except the token, of course), and if you are using ``export()`` or anything related, please also clarify.

**Comment by Hash17** [comment]
Hi @memsharded 

oh okay, I just checked and i was trying to download a tarball from a private conan repository which i have permission to access, . I understood what you said and it makes perfect sense to upload it to a generic type repository. which brings me to the next question:

If the tarball is hosted in a private generic repository, is there a way for tools.download() or tools,get() to return an error if the download failed for any reason? for example if i gave it a wrong artifactory remote or file not found or authentication failed for the user ...etc ?

----------------------------------
btw, am very impressed by how fast you replied, i see your name also all over the issues as i tried to find out if someone asked the question before, super thank you for your efforts.

**Comment by memsharded** [comment]
> If the tarball is hosted in a private generic repository, is there a way for tools.download() or tools,get() to return an error if the download failed for any reason? for example if i gave it a wrong artifactory remote or file not found or authentication failed for the user ...etc ?

Yes, absolutely, both methods should fail and raise an Exception that would end in a command line error (including exit error code) reporting the original error (auth, url, connection...).


> btw, am very impressed by how fast you replied, i see your name also all over the issues as i tried to find out if someone asked the question before, super thank you for your efforts.

Thanks, we do our best, supporting users is a priority for us, though sometimes it is very challenging, this year we will reach around 5000 Pull Requests and several thousands issues too (just in 2022), so it is becoming more and more difficult to respond to all quick, sometimes even respond at all...

**Comment by Hash17** [comment]
Thank you so much for the explanation, and good luck with this huge amount of PRs
