### ISSUE TITLE
[bug] Conan 2.0 shared-library and package_id

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#12558]
### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 20.04
  * Compiler+version: N/A
  * Conan version: 2.0 beta-5
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
This is a doozy.  Here are the conan classes used for a minimal reproducer.
```
class TaConan(ConanFile):
    name = "ta"
    version = "0.1.0"

class T0Conan(ConanFile):
    name = "t0"
    version = "0.1.0"
    requires = "ta/0.1.0"

class T1Conan(ConanFile):
    name = "t1"
    version = "0.1.0"
    package_type = "shared-library"

    def requirements(self):
        self.requires("ta/0.1.0", transitive_libs=True)
        self.requires("t0/0.1.0")

class T2Conan(ConanFile):
    name = "t2"
    version = "1.0.0"
    requires = "t1/0.1.0"

class T3Conan(ConanFile):
    name = "t3"
    version = "1.0.0"
    requires = "t1/0.1.0", "t2/1.0.0"

```
Building all of these conanfiles fails with the error shown below in the logs section.  If I change the order of the requires on T3, then it builds successfully.
```
class T3Conan(ConanFile):
    name = "t3"
    version = "1.0.0"
    #requires = "t1/0.1.0", "t2/1.0.0"
    requires = "t2/1.0.0", "t1/0.1.0"
```
Digging through the code.  It turns out that the package id is calculated to be different for t2 depending on the order of the requires.  To make things more interesting, I found that if I remove `package_type = "shared-library"` from t1, then it is able to build successfully independent of the order of the requres.  So it looks like there is some odd interaction between the package_type and the package_id.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Exporting the recipe
t3/1.0.0: Exporting package recipe
t3/1.0.0 exports: File 'conandata.yml' found. Exporting it...
t3/1.0.0: Copied 1 '.yml' file: conandata.yml
t3/1.0.0 exports: Copied 1 '.yml' file: conandata.yml
t3/1.0.0: Using the exported files summary hash as the recipe revision: 0de9ebf982f8ed66d092825ab2567fb2 
t3/1.0.0: A new conanfile.py version was exported
t3/1.0.0: Folder: /root/.conan2/p/bc5e004bb33423f1/e
t3/1.0.0: Exported revision: 0de9ebf982f8ed66d092825ab2567fb2

-------- Input profiles --------
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os.distro=Ubuntu20.04
[conf]
tools.build.jobs=6
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os.distro=Ubuntu20.04
[conf]
tools.build.jobs=6
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True

-------- Computing dependency graph --------
Graph root
    virtual
Requirements
    t0/0.1.0#898e9c2840a6848cfaf33dbc921998f3 - Cache
    t1/0.1.0#75600b3ea233959473a9ddceb193fd93 - Cache
    t2/1.0.0#8945c20619a4b76474dd83e0bf329b83 - Cache
    t3/1.0.0#0de9ebf982f8ed66d092825ab2567fb2 - Cache
    ta/0.1.0#73937b752c7ee8c79a992fe615ca5c47 - Cache

-------- Computing necessary packages --------
t3/1.0.0: Forced build from source
Requirements
    t0/0.1.0#898e9c2840a6848cfaf33dbc921998f3:372df9826562a53efb855b2c4b9bc39147f7708b#ebb34e4142f3927d2c9522b8b3aac258 - Skip
    t1/0.1.0#75600b3ea233959473a9ddceb193fd93:7f766323e69ec7daba3491a91039a0ff2316b95a#1b57ecdace0e28b6e3d545cd1bd411b7 - Cache
    t2/1.0.0#8945c20619a4b76474dd83e0bf329b83:e4d9232fa6b8cf56680e0735c3d4d71fafddd0c9 - Missing
    t3/1.0.0#0de9ebf982f8ed66d092825ab2567fb2:560e915a780cf57e88f1dd85ab482af0ee1bbc06 - Build
    ta/0.1.0#73937b752c7ee8c79a992fe615ca5c47:da39a3ee5e6b4b0d3255bfef95601890afd80709#0ba8627bd47edc3a501e8f0eb9a79e5e - Cache

-------- Installing packages --------

-------- Installing (downloading, building) binaries... --------
ERROR: Missing binary: t2/1.0.0:e4d9232fa6b8cf56680e0735c3d4d71fafddd0c9

t2/1.0.0: WARN: Can't find a 't2/1.0.0' package binary 'e4d9232fa6b8cf56680e0735c3d4d71fafddd0c9' for the configuration:
[requires]
t1/0.1.0

ERROR: Missing prebuilt package for 't2/1.0.0'
Use 'conan list packages t2/1.0.0 --format=html -r=remote > table.html' and open the table.html file to see available packages
Or try to build locally from sources with '--build=t2/1.0.0'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

**Comment by memsharded** [comment]
Hi @jsallay 

Thanks for the detailed instructions. I am trying to reproduce, and moved that to a unit test:
```python
import textwrap

from conans.test.assets.genconanfile import GenConanfile
from conans.test.utils.tools import TestClient


def test_error_package_id():
    c = TestClient()
    t1 = textwrap.dedent("""
        from conan import ConanFile
        class T1Conan(ConanFile):
            name = "t1"
            version = "0.1.0"
            package_type = "shared-library"

            def requirements(self):
                self.requires("ta/0.1.0", transitive_libs=True)
                self.requires("t0/0.1.0")
        """)
    c.save({"ta/conanfile.py": GenConanfile("ta", "0.1.0"),
            "t0/conanfile.py": GenConanfile("t0", "0.1.0").with_requires("ta/0.1.0"),
            "t1/conanfile.py": t1,
            "t2/conanfile.py": GenConanfile("t2", "1.0.0").with_requires("t1/0.1.0"),
            "t3/conanfile.py": GenConanfile("t3", "0.1.0").with_requires("t1/0.1.0", "t2/1.0.0")})
    c.run("create ta")
    c.run("create t0")
    c.run("create t1")
    c.run("create t2")
    c.run("create t3")

    c.save({"t3/conanfile.py": GenConanfile("t3", "0.1.0").with_requires("t2/1.0.0", "t1/0.1.0")})
    c.run("create t3")
```
But apparently it is working fine. 
Is it possible that there is some other detail missing? I am not sure what else to try...

**Comment by jsallay** [comment]
It turns out that this was a mistake on my part.  I swear that I upgraded to beta5, but looking in my container I was still running beta4.  It appears that it is working just fine in beta5.  I apologize for the confusion.

**Comment by memsharded** [comment]
No prob, thanks for telling!
