### ISSUE TITLE
[question] How does Conan know a revision is the latest?

### ISSUE THREAD

**Issue by foundry-markf** [conan-io/conan#12553]
Just trying to resolve an internal question at work.

- how does Conan interpret the 'latest' recipe revision? (where revisions are enabled)

For example, if you **don't** pin a self.requires(X/Y#pin), which revision does Conan pick up.

I thought they were chronologically ordered, as per the output from `conan search -rev`.

However, looking at the implementation on https://github.com/conan-io/conan/blob/develop/conans/server/revision_list.py, it looks like it's just a list ordering (via the append in add_revision), and it just so happens to concide with a 'now' timestamp.

So, the latest revision is just what happens to be at the head of the list? The chronological ordering is just a side-effect?

Thanks,
Mark

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, it is both, the latest revision is the "chronologically" latest one, which happens to be also the last one in the list, because the revision time is assigned when it is added to the list. With ``conan search --revisions`` you should also be able to display the list with timestamps.

**Comment by iaavo** [comment]
so is the revision timestamp determined at upload time (server-side) or at creation time (client-side)?

**Comment by memsharded** [comment]
> so is the revision timestamp determined at upload time (server-side) or at creation time (client-side)?

Server-side upload time, we tested a few alternatives and it was the one that made more sense.

**Comment by AbrilRBS** [comment]
Closing as solved, thanks a lot for your question :)
