### ISSUE TITLE
Question about authentication plugin

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1255]
Hi!

I have written a LDAP plugin [here](https://github.com/uilianries/conan-ldap-authentication), but, now I have a couple of doubts:  

1) I need to configure some LDAP parameters, as DN, CN, ... So, I could create the section *[ldap]* in *~/.conan_server/server.conf*, or I could create a new file, only to configure the plugin. In your opinion, which is a better option?  

2) I tried to get  *~/.conan_server/server.conf* path, by some method or variable, but, didn't find, however, I found at conan/conans/server/conf/__init__.py:34.  
If I choose to load LDAP configuration, by *server.conf*, I'll need to create same path.join, but won't be dynamic. Is there some way to find this path, dynamically?

Regards.

**Comment by memsharded** [comment]
1. I'd say that it is better to have its own configuration. It would allow to directly install the plugin with a customized configuration for teams, so a single step instead of two.

2. To get the folder, would the following work?:

```python
from conans.paths import conan_expand_user
user_folder = conan_expand_user("~")
filepath= os.path.join(user_folder, '.conan_server', 'server.conf')
```
Cheers

**Comment by uilianries** [comment]
1) I agree. Today, I'm using separated config file.

2) It works, but I'm looking for some property, e.g.
```python
# get conan_server dir by property
conan_server_dir = conan.server.config.dir
conan_server_file = conan.server.config.file_name
```
I could use conan server dir or plugin dir to put the config file.
I see the plugin as a customer, so, I think that could be better if the plugin doesn't solve where is conan dir.

**Comment by lasote** [comment]
Maybe we could inject the server settings in a dict to the plugin instance or something similar

**Comment by memsharded** [comment]
Yes, could be done. @uilianries, if you are using method 1), not an urgent issue, right? Or do you need the server.conf for something else?

**Comment by uilianries** [comment]
Right, It's not an urgent issue. For now, I could get server path directly, no problem.  
I just think about more like an API, where the customer (in this case, the plugin), get this information from an abstract layer.

Thanks, guys. Have a nice weekend.
