### ISSUE TITLE
[bug] export-pkg command gets confused by negated [tool_requires] specifications

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12561]
The Conan 2.0 export-pkg command is incorrectly reporting an issue with a negated [tool_requires] package.

### Environment Details (include every applicable attribute)
  * Operating System+version: Debian 10
  * Compiler+version: gcc 8
  * Conan version: 2.0-beta5
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)

Run the following command:

> conan-2.0 export-pkg -pr:b tools.jinja -pr:h tools.jinja --name openssl --version 1.1.1s .

where tools.jinja redirects to:

> [settings]
> os=Linux
> arch=x86_64
> compiler=gcc
> compiler.version=8
> compiler.libcxx=libstdc++11
> build_type=Release
> [options]
> cmake*:bootstrap=True
> [tool_requires]
> !openssl*:cmake/3.24.2

The critical factor here is the last line in this profile. If I comment that line out, the issue goes away. From a cursory look at the Conan 2.0 source code, it appears to me that the negation logic is only being applied to the build mode (see ./conans/client/graph/build_mode.py) but should also be applied to the corresponding export-pkg logic.

### Logs (Executed commands with output) (Include/Attach if Applicable)

> conan-2.0 export-pkg -pr:b tools.jinja -pr:h tools.jinja --name openssl --version 1.1.1s .
> openssl/1.1.1s: Exporting package recipe
> openssl/1.1.1s exports: File 'conandata.yml' found. Exporting it...
> openssl/1.1.1s: Copied 1 '.yml' file: conandata.yml
> openssl/1.1.1s exports: Copied 1 '.yml' file: conandata.yml
> openssl/1.1.1s: Calling export_sources()
> openssl/1.1.1s: Copied 1 '.patch' file: 1.1.1-tvos-watchos.patch
> openssl/1.1.1s: Using the exported files summary hash as the recipe revision: b304462aeda9923b735e6b37368c233e
> openssl/1.1.1s: A new conanfile.py version was exported
> openssl/1.1.1s: Folder: /home/marc/.conan2/p/2db3dadc688d3901/e
> openssl/1.1.1s: Exported revision: b304462aeda9923b735e6b37368c233e
> cmake/3.24.2: Not found in local cache, looking in remotes...
> ERROR: Package 'cmake/3.24.2' not resolved: No remote defined

**Comment by System-Arch** [comment]
Digging a little deeper, it appears that call flow in export_pkg  looks roughly like:

> call conan_api.graph.load_graph()
> reports errors
> calls conan_api.graph.analyze_binaries()
> reports errors.

The error is occurring from the first call. This call differs from that used in the build and install commands, which do not show this problem, because it is using conan_api.graph.load_root_virtual_conanfile() whereas the others appear to use conan_api.graph.load_root_consumer_conanfile().

As an experiment, I tried replacing one with the other, which leads to an error on line 38 in conan/api/subapi/export.py where the code tries to access the first element of the deps_graph nodes property. Interestingly, this code is preceded by a dubious comment of the form:

>         # The graph has to be loaded with build_mode=[ref.name], so that node is not tried
>         # to be downloaded from remotes
>         # passing here the create_reference=ref argument is useful so the recipe is in "develop",
>         # because the "package()" method is in develop=True already
> 
>         # this is a bit tricky, but works. The root (virtual), has only 1 neighbor,
>         # which is the exported pkg
>         # TODO: Seems this could be changed, loading conanfile from cache, but locally setting
>         #   to local folder?

And, hence, I am wondering if the current approach is working more by coincidence than design.

**Comment by System-Arch** [comment]
Closing now that the fix has been merged into develop2

**Comment by memsharded** [comment]
Yes, closed by https://github.com/conan-io/conan/pull/12655, for beta.7, thanks!
