### ISSUE TITLE
[bug] Missing LIB_DIRS in CMakeDeps <PACKAGE>-config.cmake

### ISSUE THREAD

**Issue by Bearwolves** [conan-io/conan#12564]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Conan version: 1.54.0
  * Python version: 3.6.9

### Logs (Executed commands with output) (Include/Attach if Applicable)
CMakeDeps generates following variables in a `dummy-example-config.cmake` files into the build folder.

```CMake
set(dummy-example_VERSION_STRING "6.1.0")
set(dummy-example_INCLUDE_DIRS ${dummy-example_INCLUDE_DIRS_DEBUG} )
set(dummy-example_INCLUDE_DIR ${dummy-example_INCLUDE_DIRS_DEBUG} )
set(dummy-example_LIBRARIES ${dummy-example_LIBRARIES_DEBUG} )
set(dummy-example_DEFINITIONS ${dummy-example_DEFINITIONS_DEBUG} )
```

missing

```CMake
set(dummy-example_LIB_DIRS ${dummy-example_LIB_DIRS_DEBUG} )
```

If I want to access the information, I need to use the `build_type` in the CMake variable which is undesirable ^^'
```CMake
target_link_directories (dummy-app PUBLIC
  ${dummy-example_LIB_DIRS_DEBUG}
)
```

Usage of LIB_DIRS in our `CMakeLists.txt` would be following

```CMake
target_link_directories (dummy-app PUBLIC
  ${dummy-example_LIB_DIRS}
)

target_link_libraries (dummy-app
  dummy-example
)
```

I took a look at the code/template, it's a one liner adding. I'm willing to create the PR, if the request is fine!
```CMake
set({{ file_name }}_LIB_DIRS {{ '${' + pkg_name + '_LIB_DIRS' + config_suffix + '}' }} )
```
https://github.com/conan-io/conan/blob/develop/conan/tools/cmake/cmakedeps/templates/config.py#L64

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jcar87** [comment]
Hi @Bearwolves - thank you for reporting this issue. 

From what I can see, CMake specifies that legacy find modules would specify a variable called (`xxx_LIBRARY_DIRS`) and not `_LIB_DIRS`. The state of these variables is unfortunate: despite CMake's best efforts, there is no uniform convention on what exact names these variables should have. We would be inclined to only follow CMake's own documented recommendations in this instance, so if we were to define this variable, we would use `_LIBRARY_DIRS`. 

On the other hand, bear in mind that legacy variables that would be defined in CMake modules are discouraged in favour of using imported targets. One of the challenges in this case, is that variables are not well suited for this specific case, when there may be "multiple" build directories for different configurations - as is supported by the `CMakeDeps` generator.

Out of curiosity, if what you're trying to do is:
```
target_link_directories (dummy-app PUBLIC
  ${dummy-example_LIB_DIRS}
)

target_link_libraries (dummy-app
  dummy-example
)
```

A rough equivalent using the imported targets provided would be:
```
target_link_libraries(dummy-app PUBLIC dummy::dummy
```
(or something similar, assuming that `dummy::dummy` is a CMakeDeps-generated imported target).


Is there a specific reason that you can't use the imported targets? That said, we would consider adding a variable like `_LIBRARY_DIRS_DEBUG` or `_LIBRARY_DIRS_RELEASE` if that _is_ recommended by CMake or there is prior art in using them.

**Comment by Bearwolves** [comment]
@jcar87 : I'm completely open about the notation. I just want to make it work 👼 

I tried initially with the target as you mention but without success with the version 1.54.0. May be I missed something?
Could you have a look at https://github.com/Bearwolves/cmake-deps-bug-12564/blob/main/app/CMakeLists.txt .

If I add my fix and following configuration, it works:
* https://github.com/Bearwolves/cmake-deps-bug-12564/blob/main/app/CMakeLists.txt#L9
* https://github.com/Bearwolves/cmake-deps-bug-12564/blob/main/app/CMakeLists.txt#L14

Without (the current default state) I get following log although the target is declared via conan
```bash
...
-- Conan: Target declared 'conan-libs::conan-libs' 
...
[ 50%] Building CXX object CMakeFiles/hello_exe.dir/src/main.cpp.o
/usr/bin/c++ -D_GLIBCXX_USE_CXX11_ABI=0 -I/home/XXX6XXX/wp/cmake-deps-usage/app/conan-libs::conan-libs -m64 -O3 -DNDEBUG -MD -MT CMakeFiles/hello_exe.dir/src/main.cpp.o -MF CMakeFiles/hello_exe.dir/src/main.cpp.o.d -o CMakeFiles/hello_exe.dir/src/main.cpp.o -c /home/XXX6XXX/wp/cmake-deps-usage/app/src/main.cpp
/home/XXX6XXX/wp/cmake-deps-usage/app/src/main.cpp:1:10: fatal error: hellolib1.h: No such file or directory
 #include "hellolib1.h"
```

It seems the target is not replaced correctly ` -I/home/XXX6XXX/wp/cmake-deps-usage/app/conan-libs::conan-libs`. Is it a misconfiguration from my side ? I had a look at your conan2.0 examples and couldn't spot anything problematic yet...
https://github.com/conan-io/examples2/blob/bcf6a29a1975208ed12dce2c78e401d4925674ee/tutorial/consuming_packages/conanfile_py/CMakeLists.txt

If I use `cpp.info.libs` as in the conan2.0 examples, it works with following configuration:
```CMake
target_include_directories(hello_exe PUBLIC
    ${conan-libs_INCLUDE_DIRS}
)

target_link_libraries(hello_exe PUBLIC
    conan-libs::conan-libs
)
```

But then it links with the absolute path of the library. 
```shell
[100%] Linking CXX executable hello_exe
/home/ber6abt/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/hello_exe.dir/link.txt --verbose=1
/usr/bin/c++ -m64 -O3 -DNDEBUG -m64 CMakeFiles/hello_exe.dir/src/main.cpp.o -o hello_exe   -L/home/ber6abt/wp/cmake-deps-usage/app/conan-libs::conan-libs  -Wl,-rpath,/home/ber6abt/wp/cmake-deps-usage/app/conan-libs::conan-libs:/data/ber6abt/.conan/data/conan-libs/0.1.0/_/_/package/0ab9fcf606068d4347207cc29edd400ceccbc944/lib: /data/ber6abt/.conan/data/conan-libs/0.1.0/_/_/package/0ab9fcf606068d4347207cc29edd400ceccbc944/lib/libhellolib1.so 
```

Any help would be appreciated!

**Comment by Bearwolves** [comment]
@jcar87: Any update here?

**Comment by memsharded** [comment]
Hi @Bearwolves 

Sorry that we couldn't follow up on this, our tasks keep piling up and often we cannot attend everything as we would like.
Are you sure you want to close this as not-planned? Did you manage to make it work using targets? Feel free to re-open if there are still pending issues, or open a new ticket focused on your problems with using the targets. Many thanks.
