### ISSUE TITLE
[feature] `build_modules` in 2.0 fails with error instead of a nice migration warnings 

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12560]
deprecated `build_modules` causes 2.0 to fail where it should output a warnings -- This can be see with the `cpp_info.names` and `cpp_info.user_info` attributes but not this one.

Post-op from playing with #12555 

```
json-schema-validator/2.1.0: Full package reference: json-schema-validator/2.1.0#986a89f6a3344cc556dca7c0b062b212:158b7151fbfbfa9ccd829110c8d4cfff48dad2b3#748e6457403877ef605821d6b2a42d17
json-schema-validator/2.1.0: Package folder /Users/christopherm/user-management/backend/.conan2_home/p/2f777ef816571596/p
WARN: The use of 'cpp_info.names' is deprecated in Conan 2.0 and will be removed in Conan 2.X. Please, update your recipes unless you are maintaining compatibility with Conan 1.X
WARN: The use of 'cpp_info.names' is deprecated in Conan 2.0 and will be removed in Conan 2.X. Please, update your recipes unless you are maintaining compatibility with Conan 1.X
ERROR: json-schema-validator/2.1.0: Error in package_info() method, line 128
	self.cpp_info.build_modules["cmake_find_package"] = [self._module_file_rel_path]
	AttributeError: '_Component' object has no attribute 'build_modules'
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by prince-chrismc** [comment]
It would also be nice to make the warning optional with a conf setting... It's extremely noisy 🙊 

![image](https://user-images.githubusercontent.com/16867443/202640037-11f0e84c-3fc1-40b8-a6c9-c61135e30914.png)

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12578

**Comment by kielby** [comment]
> It would also be nice to make the warning optional with a conf setting... It's extremely noisy 🙊
> 
> ![image](https://user-images.githubusercontent.com/16867443/202640037-11f0e84c-3fc1-40b8-a6c9-c61135e30914.png)

@prince-chrismc was a conf setting ever introduced to control the warning messages?

**Comment by memsharded** [comment]
2.0 warnings have been reduced in https://github.com/conan-io/conan/pull/13319 for 2.0.2
