### ISSUE TITLE
[bug] 2.0 Help message

### ISSUE THREAD

**Issue by MarkoMin** [conan-io/conan#12568]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04LTS
  * Compiler+version: gcc 9.4.0
  * Conan version: 2.0.0-beta5
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
conan --help

### Logs (Executed commands with output) (Include/Attach if Applicable)

Last line of "--help" output says: "Conan commands. Type "conan help \<command\>" for help", which gives an error when called. Shouldn't it be "conan \<command\> --help" ?

**Comment by memsharded** [comment]
You are right, that should be changed. If you want to contribute a PR yourself, that would be great, otherwise, we will fix it for next beta.6. Thanks for reporting!

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/12569 will be in beta.6
