### ISSUE TITLE
[question] Source of Contribution License - Contributor License Agreement

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#12570]
I've been reviewing the [Contributor License Agreement](https://cla-assistant.io/conan-io/conan) to better understand the license conditions under which contributions are made. This is the relevant extract from the CLA:

> Your contribution is either your original creation, based upon previous work that, to the best of your knowledge, is covered under an appropriate open source license and you have the right under that license to submit that work with modifications, whether created in whole or in part by you, or you have clearly identified the source of the contribution and any license or other restriction (like related patents, trademarks, and license agreements) of which you are personally aware.

I guess what I'm looking for is an answer to the following questions:

1. Does "appropriate open source license" here mean that conan mandate contributions are made under the MIT license?
2. If not, how can the LICENSE associated with individual contributions be included with a contribution/the repository as required?

## Context

If contributions were to be distributed under the Apache-2.0 License, as an example, that license would have to be included along with the contribution:

>    4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

> **(a) You must give any other recipients of the Work or**
>           **Derivative Works a copy of this License; and**

If there's no mechanism to do this, I would think that this does mean that there's an implicit requirement for contributions to be under the MIT license, as otherwise conan itself wouldn't be redistributable under the MIT license only.

Whatever the answer is here it's fine, but I think it would be useful to provide some clarity around what the warranty is provided and what liability is adopted for contributions as a result of signing the CLA. 

Crosspost of https://github.com/conan-io/conan-center-index/issues/14315 as this question is relevant, individually, to each repository

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @samuel-emrys 

> Does "appropriate open source license" here mean that conan mandate contributions are made under the MIT license?

Yes, this is what it means. The contributions will be under the repo MIT license, this is what the CLA is for. Otherwise, the burden imposed to users of the tool, that would probably had to validate many different licenses (as there are hundreds of contributors), would be too much, and in practice it could also mean a no-go for some users, specially in restricted enterprise environments.

>  I would think that this does mean that there's an implicit requirement for contributions to be under the MIT license, as otherwise conan itself wouldn't be redistributable under the MIT license only.

My understanding is that it is not implicit, the CLA itself is an explicit mechanism to require that. I'd prefer not to have to modify the CLA text either, it is a standard one, so probably modifying it, is not an evident thing.

**Comment by samuel-emrys** [comment]
Thanks for the clarification @memsharded - really appreciate it. I'm not a lawyer, but it would have helped me understand the requirements more clearly if it had have been explicitly indicated in the CLA that contributions must be made under the MIT license. The alternative interpretation (that I don't see excluded in the existing language) might be that a different _but compatible_ license would also be acceptable.

Regardless, I'm grateful for your clarification. Can I assume, given the identical language in the license/CLA, that this also applies to the [conan-center-index](https://github.com/conan-io/conan-center-index/issues/14315) repository?

**Comment by memsharded** [comment]
> Regardless, I'm grateful for your clarification. Can I assume, given the identical language in the license/CLA, that this also applies to the https://github.com/conan-io/conan-center-index/issues/14315 repository?

Yes, all Conan repos use the same CLA and same MIT license, so it will apply to ``conan-center-index`` repository too.
