### ISSUE TITLE
[bug] conan does full git submodule checkout to conan cache with "shallow" scm setting

### ISSUE THREAD

**Issue by insi-eb** [conan-io/conan#12576]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: n/a
  * Conan version: 1.53
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)
* have a repo with a large submodule
* configure scm in a conanfile.py to have "shallow" flag on submodule
* run conan to check out this repo to conan cache (e.g. via conan install)
* check checked out repo: it has a full submodule checkout, not a shallow one

### Logs (Executed commands with output) (Include/Attach if Applicable)
n/a

### Fix
add "--depth=1" to the "submodule update --init" git call at https://github.com/conan-io/conan/blob/develop/conans/client/tools/scm.py#L221

**Comment by memsharded** [comment]
Hi @insi-eb 

Thanks for the report. 

I'd like to point out that the ``scm`` feature has already been removed in Conan 2.0, and it has already landed a replacement in Conan 1.X, so it can be used in 1.X. This feature is intended to provide much better control on how things are managed around the scm, making explicit the whole process. I would recommend to have a look to https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature, and try to migrate to it, as it will be a necessary step anyway for 2.0 (which is now very close, we are preparing to release beta.6, which aims to be the last one)

**Comment by memsharded** [comment]
Closing this ticket as outdated, ``scm`` declared legacy in 1.X (replaced by explicit export+source with ``Git``), and removed in Conan 2. Please create new tickets for any further question.
