### ISSUE TITLE
[question] Gracefully overwriting user of delivered package

### ISSUE THREAD

**Issue by domfellner** [conan-io/conan#12583]
Hi community, 

I get a delivery of lets say two dependent packages (say `libA/1.0.0@ernie/stable` which in turn requires `libB/1.0.0@ernie/stable`), but for some compliance reasons I as a consumer need to modify the user in the references to be `bert` instead of `ernie` (or by some means put `bert` prominently in the reference). I thought of repackaging the packages using export-pkg on the original package_folder and patching the delivered recipes and (god forgive me) lockfiles to require `@bert/stable` packages with their new revisions.

Is there some easier way to tackle this, e.g. defining package overrides downstream which only affect the user? I could add `self.requires("libA/1.0.0@bert/stable", override=True)` in my consuming package, but this would always need to match the correct version of the dependency, wouldn't it?

Thanks in advance for any help!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @domfellner 

> Is there some easier way to tackle this, e.g. defining package overrides downstream which only affect the user? I could add self.requires("libA/1.0.0@bert/stable", override=True) in my consuming package, but this would always need to match the correct version of the dependency, wouldn't it?

I am afraid is not possible, because there is not enough information at evaluation time to define only the variation, and propagating only the variation would be too much of a challenge, a quite complicated feature. So it is necessary to define the whole thing, including version, yes.

I'd like to comment that looking at the future and 2.0, the user/channel part will be less relevant than in 1.X, and it should be considered always as an immutable and core part of the package name, but doing any kind of management, promotion, overriding, etc, based mostly in user/channel will be discouraged. It doesn't seem the case in your comment, as you describe it as an occasional exceptional workaround, but just in case.

**Comment by domfellner** [comment]
Thanks for your answer @memsharded even if it's negative as I already feared.

We are usually propagating packages via remotes, not references, as it's regarded best practice and leaves packages unmodified. In this special case though we are required to add some prominent tag to the reference which cannot be done by the delivering team as it's only our consumer's need, not theirs.

We might as well combine all delivered packages into one wrapping one using the imports() method and name it accordingly, so we don't have to mess around with the existing references and lockfiles. Let's see what turns out to be the best way to deal with our rather special case. Thanks for your support!

**Comment by memsharded** [comment]
> We are usually propagating packages via remotes, not references, as it's regarded best practice and leaves packages unmodified. In this special case though we are required to add some prominent tag to the reference which cannot be done by the delivering team as it's only our consumer's need, not theirs.

I see. Then yes, I guess your only workaround is checking first the version of the dependency, then replacing the user in the override, but checking the dependency will be needed

> We might as well combine all delivered packages into one wrapping one using the imports() method and name it accordingly, so we don't have to mess around with the existing references and lockfiles. Let's see what turns out to be the best way to deal with our rather special case. Thanks for your support!

A note about this, regarding being 2.0 ready: the ``imports()`` method has been removed. The alternative is doing the imports via explicit ``copy()`` calls in the ``generate()`` method. It should be quite similar, just a bit more explicit.
