### ISSUE TITLE
[question] logic 'behind conan config home's output?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#12581]
Hey,

we are using the output of 'conan config home' in scripts to figure out the "base config directory" for Conan.
This gets harder and harder, as between releases the settings.yml migration output changes. E.g. before 1.54 
they were displayed as warning (e.g. "WARN:" was before them). With 1.54. This is kept, but there is a line 
displaying some migration related message without WARN:

E.g. if you upgrade from 1.53.0 to 1.54.0 and run "conan config home" for the first time, migration code will kick in and
will "ruin" the output of "conan config home".

Yeah I know I could use "--json" and move the output to a temporary json, then parse up the json, etc. but honestly 
just to fetch the actual Conan configuration home, this would be a kinda over-engineering.

Or even better, is there any way to disable migration of settings as a whole?
Any thoughts on this?
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

Yes, this has been already addressed in 2.0, with a much simpler logic:
- The ``settings.yml`` contains a first line with a comment ``# This file was generated by Conan. Remove this comment if you edit this file or Conan``
- If you modify things and remove the comment, nothing will be migrated, nothing will happen, ever. 
- If you leave the comment the file will be systematically upgraded with every new release

Still, if you are managing custom settings, which seems the case, the recommended approach is to put them in a repo and use ``conan config install`` to distribute changes

**Comment by harsszegi** [comment]
Aok, thanks!
