### ISSUE TITLE
[bug] 'Sqlite3Conan' object has no attribute 'env_info' in conan-2.0.0b5

### ISSUE THREAD

**Issue by obsgolem** [conan-io/conan#12584]
All relevant details of this bug are in https://github.com/conan-io/conan-center-index/issues/14361.

**Comment by memsharded** [comment]
Hi @obsgolem 

You are right, there is a bug there, I am submitting https://github.com/conan-io/conan/pull/12585 to fix it asap. 
Many thanks for reporting!

**Comment by obsgolem** [comment]
Just FYI, there is a similar issue https://github.com/conan-io/conan-center-index/issues/14365

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12585

**Comment by memsharded** [comment]
and https://github.com/conan-io/conan/pull/12578 will care about the ``build_modules`` too
