### ISSUE TITLE
[question] Handling object files

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#12595]
Dear Conan Folks,

Some of my packages provide only object files. Therefore, I am using self.cpp_info.component.objects to set the path to the obj files.
How do I access the object files from a consuming package?
Is it okay to use: PkG_OBJECTS_RELEASE?
I could find the documentation for the self.cpp_info.component.objects https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=self%20cpp_info%20components%20objects 
But not how shall it be used in the consumer context?
Could anyone please help?

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @maitrey,

Thanks for your question. I have uploaded a simple example here: https://github.com/czoido/conan-objects-example/tree/main

It's a `myobject/1.0` package that creates an object file and it's consumed by the test package. Some relevant parts:

Provide the info for consumers in package_info:
```
    ...
    def package_info(self):
        self.cpp_info.objects = ['lib/myobject.o']
```

In the consumer side (test_package CMakeListst.txt) you can just use `target_link_libraries` with the target name:

```
target_link_libraries(example myobject::myobject)
```

Hope this helps

**Comment by maitrey** [comment]
Yeah this works ! Thank you !

**Comment by maitrey** [comment]
One question though: Is it allowed to use Pkg_LIBRARIES instead of Pkg::Pkg ?

**Comment by czoido** [comment]
> One question though: Is it allowed to use Pkg_LIBRARIES instead of Pkg::Pkg ?

Sorry, I did not answer the question. The problem for that is that it may change in the future, only documented things should be used and in general we don't document internal CMake variables on purpose, so the best thing would be not using that.

**Comment by maitrey** [comment]
Okay got it and if I have in the package_info self.cpp_info.includedirs = ['include'] . Is it allowed to use in the consuming package Pkg_INCLUDE_DIRS?

**Comment by czoido** [comment]
> Okay got it and if I have in the package_info self.cpp_info.includedirs = ['include'] . Is it allowed to use in the consuming package Pkg_INCLUDE_DIRS?

I would also not recommend it, we only documented [that variable](https://docs.conan.io/en/latest/reference/generators/cmake_find_package.html#cmake-find-package) for the `cmake_find_package` generator. It would be better to use CMake targets and also we are recommending to move to [CMakeDeps](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html) as `cmake_find_package` will dissapear in 2.0.

**Comment by maitrey** [comment]
If I have a package with only includes , how to use it in consumer context? Honestly , I have not tried like this : Pkg::Pkg with target_include_directories

**Comment by czoido** [comment]
There should be nothing different for header only libraries, just link the consumer with the target using something like:

```
target_link_libraries(${PROJECT_NAME} PRIVATE package::package)
```

I recommend that you play a bit with the conan templates, for example, create a new project with:

```
conan new foo/1.0 --template cmake_lib     
```
It will generate a project that uses modern CMake integrations and from that you can start modifying the generated files.

**Comment by maitrey** [comment]
Got it Many thanks!
