### ISSUE TITLE
[bug] Running conan create throws an error

### ISSUE THREAD

**Issue by Drllap** [conan-io/conan#12594]
I get an error when running `conan create`.
``ERROR: path is on mount '\\\\?\\D:', start on mount 'C:'``

Don't know if it is relevant, but the source code is on the `D:`.

### Environment Details
  * Windows 10
  * Conan version 1.53.0
  * Python 3.9.12

### Logs
Running command: `conan create . <name>/test -pr=d64 `.
Output:
```
...
<conan-packet-name>/1.0.0@<name>/test: WARN: Build folder is dirty, removing it: C:\.conan\3b51c6\1
<conan-packet-name>/1.0.0@<name>/test: Configuring sources in C:\.conan\b1a615\1
ERROR: path is on mount '\\\\?\\D:', start on mount 'C:'
```

**Comment by czoido** [comment]
Hi @Drllap,
Thanks for reporting. We would need some more data to reproduce this issue and understand what's happening, can you give a simplified example of your recipe file that produces the same error? Maybe something starting from a template like `conan new foo/1.0 --template cmake_lib` and then modifying it to produce the same error.

**Comment by czoido** [comment]
Checking this again I think this is probably something related to short_paths in Windows and the fact that in some parts of the code we have calls to `relpath` to get relative routes and it breaks if you are working in a diferent unit: `D:` instead of `D:`
Did you check if the problem persists when moving the sources to `C:` ?

**Comment by Drllap** [comment]
> Did you check if the problem persists when moving the sources to `C:` ?

Yes, tried to copy the folder to `~` and build there, works fine

**Comment by Drllap** [comment]
tried running 
```
conan new foo/1.0 --template cmake_lib
conan create . palli/test -pr=d64
```
That works fine

And tried to replace the template recipe with the one that is giving me problems and it sill workes.

**Comment by Drllap** [comment]
@czoido I think I have something:
I have `exports_sources = "*"` in my recipe and a `compile_commands.json` in my source root folder. If I remove either one the errors goes away.

**Comment by czoido** [comment]
> @czoido I think I have something: I have `exports_sources = "*"` in my recipe and a `compile_commands.json` in my source root folder. If I remove either one the errors goes away.

I think that there's not much we can do on our side for this, the best would be to have the Conan cache in the same unit that you have your sources in.

**Comment by Drllap** [comment]
@czoido So I take it you know whats happening?

**Comment by czoido** [comment]
> @czoido So I take it you know whats happening?

The error comes from doing a python `relpath` if you have a subfolder with sources that point to D: it's not possible for Conan to calculate the relative paths correctly. I think that would be the problem...
