### ISSUE TITLE
mark headers as "SYSTEM" headers to silence warnings

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#126]
Many libraries generate tons of warnings in public headers. WebSocket++ uses auto_ptr for example and many Boost libraries truncate integers implicitly (-Wconversion). To consume these libraries you have to treat them as system headers because GCC won't emit warnings in these.

This is how Conan currently sets the include directories:
```CMake
include_directories(${CONAN_INCLUDE_DIRS})
```

This is how you would add them as "system" headers to silence warnings:
```CMake
include_directories(SYSTEM ${CONAN_INCLUDE_DIRS})
```

Is there a reason it is not already done this way?
This issue may apply to configurations other than CMake/GCC, too, but this is the most important one for me.

**Comment by memsharded** [comment]
No, no reason, good catch. Just added it, ran tests, and did a PR, probably it will be included in 0.7
