### ISSUE TITLE
[bug] MesonToolchain __init__ fails on native builds

### ISSUE THREAD

**Issue by mcsquared** [conan-io/conan#12619]
When trying to do a plain native build of a meson project, the MesonToolchain helper fails at line 156 in `conan/tools/meson/toolchain.py` with a "non-iterable" TypeError:
```
        if cross_building(conanfile, skip_x64_x86=True):
            .....
        else:
            if "Visual" in compiler or compiler == "msvc":
                default_comp = "cl"
                default_comp_cpp = "cl"
            elif "clang" in compiler:
                default_comp = "clang"
                default_comp_cpp = "clang++"
            elif compiler == "gcc":
                default_comp = "gcc"
                default_comp_cpp = "g++"
```
It's the dictionary search in the else-part that raises the TypeError.

As a consequence 'conan_meson_native.ini' does not get written, which affects subsequent conan methods which rely on the helper classes from `conan.tools.meson`.

Cross builds are doing fine as there are handled separately.

### Environment Details
  * Operating System: Fedora Workstation 36 x86_64
  * Compiler: GCC 12.2.1
  * Conan version: 1.54
  * Python version: 3.10.8

Default profile:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
conanfile.py
```
...

def generate(self):
    tc = MesonToolchain(self)

...
```
```
conan install . -if <install-folder> -pr:b=default -pr:h=default
```

### Command Line Output
```
ERROR: conanfile.py (mylib/None): Error in generate() method, line 15
	tc = MesonToolchain(self)
	TypeError: argument of type 'NoneType' is not iterable
```

**Comment by memsharded** [comment]
Hi @mcsquared 

I am having a look at this, but the only way this could fail if the compiler is not defined (the recipe must have ``settings = "os", "compiler", "build_type", "arch"`` in order for this to work fine. Can you please check your recipe, just in case?

If that is the case, it is true that the ``MesonToolchain`` could report a nicer error, but that would be a minor UX thing, defining the compiler and other settings is necessary for the toolchain helper to work.

**Comment by mcsquared** [comment]
Hello @memsharded 

You're right. The compiler setting is missing in the recipe.

I added some kind of "distro" or "platform" subsetting for "os" for some customized buildroot platforms which, in my case, implies some specific compiler and other fixed settings. So I left out the "compiler" setting. As far I understand the package_id() method, this should have been enough to generate at least an unique package id for those platforms.

Solved adding the "compiler" setting to the recipe. Explicit is better than implicit

Thanks!

**Comment by memsharded** [comment]
> I added some kind of "distro" or "platform" subsetting for "os" for some customized buildroot platforms which, in my case, implies some specific compiler and other fixed settings.

Yes, the settings always need to be explicit, it really doesn't matter that for some distros it implies some default compiler, there is always a future chance of using another compiler, and it is better to model things explicitly.


I think I will submit a quick PR to raise a clear error if compiler is not defined, thanks for the feedback!
