### ISSUE TITLE
support for 4 digit versions. 

### ISSUE THREAD

**Issue by mkjkec2005** [conan-io/conan#12613]
Is there a plan to support 4 digit versions MAJOR.MINOR.PATCH.MICRO? I saw some related posts but it was not very clear on the support.

**Comment by memsharded** [comment]
Yes, this has been implemented in Conan 2.0, it is already available in the released betas.
Actually, it supports any number of digits, not just 4.

**Comment by mkjkec2005** [comment]
Thank you. Can I have a link to the relevant documentation (package id modes) to try this out?

**Comment by memsharded** [comment]
``package_id_modes`` haven't changed. This is mostly a thing for semvers and version-ranges.
It might be added, like a ``micro_mode`` or something like that, is this what you are looking for?

**Comment by mkjkec2005** [comment]
yes, kind of micro_mode.
