### ISSUE TITLE
[question] Writing to CMakeUserPresets.json - a good idea?

### ISSUE THREAD

**Issue by andioz** [conan-io/conan#12617]
I'm playing with the Conan 2.0 tutorial. One of the first things I'm puzzled is, that with the very first example a `CMakeUserPresets.json` file is generated **outside** the build folder (and only updated if it exists). I'm sure this is intended and required, but I'm not sure if this is something a user would expect?

* Every generated file is expected to go into the build folder
* `CMakeUserPresets.json` is in `.gitignore`, at least in your example project
* I guess should be in `.gitignore` in customer projects too, because of absolute paths
* Therefore, the user will not recognize the silent update

So, even if I'm just starting with V 2.0, I wonder: is it a good idea to add/modify any file outside the build folder or the cache directory?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jcar87** [comment]
Hi @andioz  - thanks for asking this question.

The `CMakeUserPresets.json` is generated in the project's root source folder (that is, next to `CMakeLists.txt`) as that's required for it to be understood by CMake.
This particular file is also intended to _not_ be checked into source control, as advised in the CMake documentation [here](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html). 

What this file does is enable a workflow like this for example:
```
conan install . -s build_type=Debug
cmake . --preset debug
```

Paired with the features from `cmake_layout`, the CMake preset will contain information as to which subfolder to build the project in, and will configure the CMake project such that it finds the dependencies from Conan, as well as set the build type for you. So it provides convenience.

Conan will not overwrite a `CMakeUserPresets.json` if one already existed and was not generated by Conan, so users are still free to have their own. In Conan 1.55 it will also be possible to suppress the generation of this file altogether.

**Comment by andioz** [comment]
Hi @jcar87,

Thanks for the quick and details response. I see, there will be no other chance for such a convenience file. Conan is doing it's best to support the user, and an option to suppress the generation/update of a file is a good thing (maybe an opt-in would be better?).

But in any case, I this "special" feature deserves a prominent place in the documentation, help text and command line output! I'm not sure, but I have not seen such an information so far.

Many thanks for your explanation. I will close this issue, having it may be useful for others looking for the same thing.
