### ISSUE TITLE
[question] ImportError: cannot import name 'Cmake' from 'conan' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/__init__.py)

### ISSUE THREAD

**Issue by KurtWAndrews** [conan-io/conan#12612]
[ConanIssue.zip](https://github.com/conan-io/conan/files/10097052/ConanIssue.zip)

I'm trying to convert my conanfile.txt to a conanfile.py and I'm getting the error in the subject line.

I've looked at at least three or 4 different examples that talk about changing conanfile.txt to conanfile.py, in the documentation, and I've tried a few changes to the py file on my own just because I like to be a little more specific about initializing lists in python. Nothing I've tried has helped.  I can't find anything in the __init__.py file related to CMake, but that's the way it was installed.  I've attached an archive with everything I could think of that might help debug the issue. 

I'm still too new to this to fully understand what's going on, but I did sort of get boost to build with the conanfile.txt.  I just don't know where it put the final libraries and headers that my project needs.  I had to build it from scratch with the connan --build option.  I'd really rather be able to just build the boost module I need instead of the whole thing and I'd like to be able to use python to do that since I think it would give me a finer grain of control.  First I just need to know why the conanfile.py isn't working.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
It seems you are doing a minor typo, it is ``CMake`` instead of ``Cmake``.

Also, it seems you are using some generators that have been removed already in Conan 2.0.
If you want to start with a recipe in conanfile.py that is modern, I'd recommend to do:

```bash
$ conan new hello/0.1 -m=cmake_lib
```
There are other templates too, like ``cmake_exe``, ``msbuild_lib``, ``msbuild_exe``, for different build systems. They are a full package recipe, so if it is only for consuming you might remove some bits, like the ``test_package`` subfolder or the ``package_info()`` method.

**Comment by memsharded** [comment]
This is the section of the docs that contains the new integrations that will survive in Conan 2.0: https://docs.conan.io/en/latest/reference/conanfile/tools.html

Also this section is a good start to check for other recommendations regarding your recipes: https://docs.conan.io/en/latest/conan_v2.html

**Comment by memsharded** [comment]
Closing this question as responded, but please re-open or create a new ticket if there are any further issues. Thanks!
