### ISSUE TITLE
[bug] remove_broken_symlinks is broken for symlinks in nested folders

### ISSUE THREAD

**Issue by oxygene** [conan-io/conan#12629]
I'm using conan 1.54.

I'm packaging a binary sysroot for use as `tools_requires` for cross compilation. The sysroot is provided "as-is" and it happens to have many valid relative symlinks (quite normal for shared libraries inside a linux sysroot). It also has some broken symlinks. However, those are not essential and can be removed.

I've used `remove_broken_symlinks` for this task, but unfortunately, it seems to be buggy and removes many valid symlinks from subfolders as well.

https://github.com/conan-io/conan/blob/release/1.54/conan/tools/files/symlinks/symlinks.py#L45

If I read the code correctly, it tries to generate a path based on `base_folder` from relative symlinks by joining `base_folder` with `link_target`. However, if `link_target` comes from a subfolder, it is meant to be relative to that subfolder. So I guess the fix would be to use `os.path.join(os.path.dirname(fullpath), link_target)` instead.

**Comment by memsharded** [comment]
I confirm that @maikelvdh is also experiencing this bug, lets have a look.

**Comment by memsharded** [comment]
Thanks very much for your report and details, that was very useful. I have been able to submit https://github.com/conan-io/conan/pull/12876, tentatively for next 1.57 release.
