### ISSUE TITLE
Artifactory bloat issues with multiple Conan packages (versions/revision). 

### ISSUE THREAD

**Issue by mkjkec2005** [conan-io/conan#12625]
We have 80+ repos (components) that change frequently and are interdependent (changing one component will result in multiple versions of other dependent components). Artifactory is our binary storage repository. Now that we plan to migrate to Conan, we are concerned about the storage requirements in Artifactory as we will be generating N Conan package versions daily due to direct or transitive dependencies. Do we have a recommendation on how this can be optimized?

**Comment by memsharded** [comment]
Hi @mkjkec2005 

This is more of a generic binary server/Artifactory question, the same issues happens for any other package type, specially heavy ones. The strategies for managing this are several:

- Use multiple repos for your binaries, do not upload everything to just one repo. CI builds go to a "build" repo, and only packages are moved to another "develop" repo when finally merged. Then packages are copied from the "develop" repo to other "release" repos.
- The retention policies on each repo will be different, the "build" repo is usually easily wiped, the "develop" repo can remove  old versions, and typically you don't want to remove things from the "release" repo
- In general, package-revisions should never happen, if you have more than one package revision it is an indicator that something can be improved in the process. Many times, old recipe-revisions can be more easily discarded than versions, as by default the latest recipe-revision is considered the good one
- There might be some more advanced techniques in the server, like Artifactory plugins that could check the timestamp or the artifacts or something like that. You might want to check other specific Artifactory resources.

**Comment by mkjkec2005** [comment]
Thank you. Regarding - In general, package revisions should never happen, I think you are referring to PREV. 
Could you please elaborate - _if you have more than one package revision it is an indicator that something can be improved in the process._

**Comment by memsharded** [comment]
> Could you please elaborate - if you have more than one package revision it is an indicator that something can be improved in the process.

A package binary is represented by a ``package_id``. This value encapsulates everything that defines a binary, from settings, options to versions (and revisions if wanted) of the dependencies. That is the full model. If there exist a given ``package_id`` for a given recipe revision, then there is absolutely no reason why that binary should be rebuilt from sources. The recipe revision captures all variability of the source, as the recipe revision is either the hash of the contents or the git commit. And the ``package_id`` captures all the configuration and dependencies information. If nothing changes, that binary should never be re-built from sources. And if it was re-built from sources, in a perfect world with deterministic C++ builds, it should give exactly the same package-revision that was already there. As the world is not perfect and C++ builds are in general not deterministic, that will cause an unnecessary new package-revision that will use computation resources and more storage and bloat without a reason. The core of ``package_id`` definition is to have a representation of when a binary should be built or not from sources.

**Comment by memsharded** [comment]
I am closing this ticket as responded back then, but please create new tickets for any further question you might have regarding  this. Thanks for the feedback!
