### ISSUE TITLE
[question] MSVC+Ninja with CMake on Conan 2.0

### ISSUE THREAD

**Issue by computerquip** [conan-io/conan#12634]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I appear to be having some issues figuring out how to use any generator outside of the "Visual Studio *" generators with CMake. I'd *like* to use Ninja but it seems to automatically define CMAKE_GENERATOR_PLATFORM which prevents this.

How am I *supposed* to accomplish this?

**Comment by computerquip** [comment]
Never mind I guess, spent an hour on this, suddenly it stopped generating CMAKE_GENERATOR_PLATFORM and Ninja started working. I swear I didn't change anything but 🤷 .

**Comment by computerquip** [comment]
Actually, it turns out this is caused by the "arch" setting after looking at the code. Something must have been stale. It's not clear from the documentation what "arch" actually does but I assume it's for cross-compiling which I don't need at the moment but it's not ideal.

**Comment by memsharded** [comment]
Hi @computerquip 

The ``arch`` setting (actually all of them, ``settings = "os", "compiler", "arch", "build_type"``) are necessary for most cases, and most of the Conan build integrations will require all of them.

It doesn't matter that it is only apparently needed for cross-compilation, it is always needed, for example, to know that it is a native build and not a cross-compilation. Conan, and specially Conan 2.0 will never try to guess the configuration or the setup, everything has to be explicit.
