### ISSUE TITLE
Detect that package was built locally from sources

### ISSUE THREAD

**Issue by Tobulus** [conan-io/conan#12638]
Hi,

I'm trying to automate a debugging use case (remote target) which looks like this:

A project with multiple dependencies managed by conan. If I want to debug the project a script copies the projects binaries and its dependencies to the remote target and starts a debugging session. The dependencies are built by our CI so I do whats recommended in the [Conan documentation](https://docs.conan.io/en/latest/using_packages/debugging.html) and build the dependencies on the developer machine so that the debugger has no problems finding the sources.

The problem: I need a way to detect that a dependency was built on the developer machine so that this needs to happen only once. Is there already a command which does that or provides the info?

**Comment by memsharded** [comment]
Hi @Tobulus 

I guess that you could check the cache, and if there is a "build" folder there, it was built from source. You might get the paths to something with the ``conan info --paths`` command. 

In any case, isn't this an information that you already have? it was the machine the one that decided to build something from source, explicitly, then it might be possible to save that into a json file in the machine or something like that?

**Comment by Tobulus** [comment]
_build_folder_ seems also set for packages prebuilt/downloaded by/from the CI.

Sure, in general its possible to store this somewhere in the project. But there are always scenarios to break this: e.g. if packages are manually removed from the conan cache the info in those files is outdated/wrong.

**Comment by memsharded** [comment]
> build_folder seems also set for packages prebuilt/downloaded by/from the CI.

In theory the folder should not even exist, but if it exists, then it should be empty. Maybe checking for folder empty is good enough.

**Comment by Tobulus** [comment]
Thanks thats helpful!

One more problem: I'm reading the dependencies from the conanbuildinfo.json. The entries contain the name and version of the dependency but not the user/channel. Why is that? Any way to get the full dependency reference that can bei used with _conan info_?

**Comment by memsharded** [comment]
If packages don't have user/channel, then they will be printed as ``pkg/version`` or ``pkg/version@``. In some cases it might be necessary to use them as ``conan install pkg/version@``. In any case it should be necessary to use the ``_/_`` when no user and channel are defined.

For reading dependencies information, it is better not to rely on ``conanbuildinfo.json``, because that is being removed in 2.0 too. You can navigate your dependencies in the ``generate()`` method accessing the ``self.dependencies`` attribute: https://docs.conan.io/en/latest/reference/conanfile/dependencies.html

**Comment by Tobulus** [comment]
> If packages don't have user/channel, then they will be printed as pkg/version or pkg/version@. In some cases it might be necessary to use them as conan install pkg/version@. In any case it should be necessary to use the _/_ when no user and channel are defined.

I have a dependency which has a user and channel. But in the conanbuildinfo.json, only the name and version is listed. And the version doesn't contain the user/channel. So from the information available i can't construct a reference for the _conan info_ command.

> You can navigate your dependencies in the generate() method accessing the self.dependencies attribute: https://docs.conan.io/en/latest/reference/conanfile/dependencies.html

The whole json generator is removed in 2.0? Wasn't aware of that, is that already documented in the migration guide?

What I did now is adding a generate() method to my recipe which looks someway like this:

```
with open('file.json', "w") as f:
            output = []
            for require, dependency in self.dependencies.items():
                if require.direct and not require.test and not require.build:
                    output.append({'ref':dependency.ref,
                                   'package_folder':dependency.package_folder})
            f.write(json.dumps(output))
```
This can be easily read by the debugging scripts containing all required informations. :)
So in principal the way to go is to generate the output myself? Hope that is as intended.

**Comment by memsharded** [comment]
> The whole json generator is removed in 2.0? Wasn't aware of that, is that already documented in the migration guide?

It is mentioned in https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#the-generate-method, linking the main page for the new generators: https://docs.conan.io/en/latest/reference/conanfile/tools.html#conan-tools


> So in principal the way to go is to generate the output myself? Hope that is as intended.

Well, in Conan 2.0 there are also other new mechanisms, that could automate that, like the new ``--deploy=mydeployer``, which allows to define custom python scripts similar to that, and then it can be applied to any ``conan install`` command over any package, without needing to add that to every ``generate()`` in every ``conanfile.py``.

Also, commands like ``conan graph info``, ``conan install``, ``conan create`` will have a ``--format=json`` output, that will output the information from the whole graph, so most likely the ``ref`` and the ``package_folder`` information will be there.

**Comment by Tobulus** [comment]
But whats the way for Conan 1.x? I can't use the json generator as it doesn't output user/channel information of dependencies. 

Then there is the _--json_ option of the install command which provides everything I need BUT the option can't(?) be set using the cmake wrapper which is required for me.

So I have to output that stuff in the generate() method?

**Comment by memsharded** [comment]
Yes, if you are restricted because using the cmake wrapper (this is one of the things I don't love about cmake wrapper. You can probably add it to the conan.cmake file, it should be pretty straightforward though), then I guess writing your own ``generate()`` would be the way to go.

**Comment by Tobulus** [comment]
I adjusted the wrapper :)
Thanks for supporting!

**Comment by memsharded** [comment]
You are welcome, glad that you were able to make it work.

I am closing this ticket as responded, but please feel free to open new ones for any further question. Thanks!
