### ISSUE TITLE
[question] Use dependency CMake binary in build() and package()

### ISSUE THREAD

**Issue by Lapenkov** [conan-io/conan#12647]
Hello,

I have a `tool_dependency` on CMake and would like to use that custom CMake binary in `build()` and `package()` according to https://docs.conan.io/en/latest/howtos/cmake_install.html#reuse-cmake-install

I can't find a single way to obtain path to that binary. It's either available in `build()` or `package()`.
I've tried:
- deps_cpp_info - unavailable in `package()`
- dependencies - unavailable in `build()`
- env() - unavailable in `package()`

I can't wrap my head around this. How do I get CMake binary in my local conan cache across different conanfile.py methods?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Lapenkov 

Ideally, the path to your cmake inside ``tool_requires`` shouldn't be necessary to make it explicit. Just using the ``VirtualBuildEnv`` generator, and it will put it in your path in both ``build()`` and ``package()`` method (together with other tools, posssible DLLs that you need, etc. The idea is that you shouldn't need to do this manually.


If you still want access to dependencies, you can do it via ``self.dependencies`` inside the ``generate()`` method. You get the paths there, and then write a file or something similar, to make it available to the other methods. Also ``build()`` method might have access to ``self.dependencies``, but just not in the local ``conan build`` command in 1.X. It will have access with both ``conan create`` and ``conan build`` in 2.0.

**Comment by Lapenkov** [comment]
Hmmm, `VirtualBuildEnv` doesn't seem to help. Here's my conanfile (simplified):
```
...
class MyConan(ConanFile):
    name = ...
    description = ...
    settings = "os", "arch", "compiler", "build_type"

    generators = ("VirtualBuildEnv")

    def configure_cmake(self):
        """
        Configures a CMake object that can be reused in different conan methods.
        """
        cmake = CMake(self)

        cmake_toolchain_path = os.path.join(self.folders.generators, "conan_toolchain.cmake")
        cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = cmake_toolchain_path

        cmake.configure()
        return cmake

   def generate(self):
        tc = CMakeToolchain(self)
        ...
        tc.generate()

        deps = CMakeDeps(self)
        deps.generate()

    
    def build(self):
        cmake = self.configure_cmake()
        cmake.parallel = True
        cmake.build()
        cmake.test(args=['--', 'ARGS=-j 4 --repeat until-pass:3'], output_on_failure=True)

    def package(self):
        cmake = self.configure_cmake()
        cmake.install()
```

Command
```
conan export-pkg -f -l=conan.lock . <package_ref>
```
picks system cmake.

**Comment by Lapenkov** [comment]
I can see `Generator 'VirtualBuildEnv' calling 'generate()'` in the install log

**Comment by Lapenkov** [comment]
Disregard, it works. Thanks!

**Comment by memsharded** [comment]
Good!

Just one extra tip: do not use ``CMake`` helper from ``from conans import CMake``, but you should migrate to the new one in ``from conan.tools.cmake import CMake``, the same as CMakeToolchain, CMakeDeps.
