### ISSUE TITLE
[bug] When cross building AutotoolsToolchain does not pass --build option if there is any configure argument with "build" in its name

### ISSUE THREAD

**Issue by ovostrikov** [conan-io/conan#12642]
### Environment Details
  * Operating System+version: WSL Ubuntu 20.04
  * Compiler+version: clang 15
  * Conan version: 1.54
  * Python version: 3.8

### Steps to reproduce
`conan new at/1.0.0 -t -m autotools_lib`

Edit the conanfile `generate` method to add

```
    def generate(self):
        at_toolchain = AutotoolsToolchain(self)
        at_toolchain.configure_args.append(f"--with-cross-build=some_path")
        at_toolchain.generate()
```
Create `cross-build-profile` file

```
include(default)
[settings]
os=Emscripten
os_build=Linux
arch=wasm
arch_build=x86_64
```

Run

```
conan create . --profile=cross-build-profile --profile:build=default -tf=None  > log.txt
grep '\--build' log.txt
```

### Expected result
The '--build=x86_64-linux-gnu' option should be present:

` >  '--disable-shared' '--enable-static' '--prefix=/' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--with-cross-build=some_path' '--host=wasm32-local-emscripten' '--build=x86_64-linux-gnu'`

### Actual result
The '--build=x86_64-linux-gnu' option is missing

`'--disable-shared' '--enable-static' '--prefix=/' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--with-cross-build=some_path' '--host=wasm32-local-emscripten'`

### Possible cause
[AutotoolsToolchain checks that `build` option has not been set yet.](https://github.com/conan-io/conan/blob/f37e5ede19adc102ec36304d5d1a9479daf5eba2/conan/tools/gnu/autotoolstoolchain.py#L189) However, since it's a simple substring check, existing `with-cross-build` option fails this check

### Example of affected recipe
[ICU ](https://github.com/conan-io/conan-center-index/blob/master/recipes/icu/all/conanfile.py#L141:~:text=if%20cross_building(self)%3A,%7Bbase_path%7D%22) cross builds incorrectly because of this in some cases.

**Comment by franramirez688** [comment]
Hi @ovostrikov 

Thanks for reporting it because, indeed, it's a bug. I'll open a PR fixing this for the next release.

**Comment by SpaceIm** [comment]
Something like this should be sufficient:

```patch
--- a/conan/tools/gnu/autotoolstoolchain.py
+++ b/conan/tools/gnu/autotoolstoolchain.py
@@ -186,8 +186,11 @@ class AutotoolsToolchain:
         configure_args.extend(self.configure_args)
         user_args_str = args_to_string(self.configure_args)
         for flag, var in (("host", self._host), ("build", self._build), ("target", self._target)):
-            if var and flag not in user_args_str:
-                configure_args.append('--{}={}'.format(flag, var))
+            if var:
+                arg = f"--{flag}="
+                if arg not in user_args_str:
+                    arg += var
+                    configure_args.append(arg)
 
         args = {"configure_args": args_to_string(configure_args),
                 "make_args":  args_to_string(self.make_args),
```
