### ISSUE TITLE
[question] How to properly manage compiler upgrade?

### ISSUE THREAD

**Issue by dkumsh** [conan-io/conan#12640]
I am having difficulties to upgrade c++ compiler. 
Let me try to explain the issue though I do not fully understand what is going on.

Currently I am using conan 1.52.

Here is the **profile** I use:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10.3
compiler.libcxx=libstdc++11
build_type=Release
[options]
date:use_system_tz_db=True
[conf]
[build_requires]
*: cmake/[>=3.23.1]
[env]
CMAKE_CXX_COMPILER_LAUNCHER=/usr/bin/ccache
CCACHE_PREFIX=distcc
CMAKE_MAKE_PROGRAM=/usr/bin/ninja
```
I am using semver_mode:
```
default_package_id_mode = semver_mode
revisions_enabled = 1
```
I have an internal project requiring some 3rd party dependencies.
3rd party dependencies are uploaded to the internal JFrog artifactory with user/channel = `_/_`

I upgraded the compiler (from g++ 10.3 to gcc++ 12.2) and re-built 3rd party dependencies (same versions and in the same user/channel = `_/_`).

After this, when I try to build the internal project with the old (10.3) compiler, it somehow picked a mysql/8.0.28 library built with g++ 12.2, then it attempted to pull recursively dependencies  of mysql and did not find them and started re-building them and failed. 

When I manually removed mysql/8.0.28 package built with g++ 12.2 the pipeline picked mysql/8.0.28  built with 10.3 and this fixed the failure.

I guess I am doing something wrong here. I expected that if I build my project with 10.3 it would pull only those dependencies which are also built with 10.3. 

I wonder if you could recommend how to manage the compiler upgrade for 3rd party libs and for their consumers without breaking any pipelines?
 
- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dkumsh 

> After this, when I try to build the internal project with the old (10.3) compiler, it somehow picked a mysql/8.0.28 library built with g++ 12.2, then it attempted to pull recursively dependencies of mysql and did not find them and started re-building them and failed.

How do you verify that this package ``mysql/8.0.28`` was built with 12.2? If you can please copy here the internal ``conaninfo.txt`` inside the binary that is being pulled, it should be clearly showing ``compiler.version=12.2``.

If you can do a ``conan search mysql/8.0.28 -r=yourremote``, that should also display the different binaries you have built for the different configurations, and the ``package_ids``. Then we can compare that with the output you have when doing ``conan install`` for your own project (please share that output too).

**Comment by davidebenato** [comment]
hi @memsharded 
thank you for your support. I work with @dkumsh and we just collected a bit more information.

Here is how we reproduced the problem, this time the problem shows with another library (arrow)

We had a valid `arrow/7.0.0` package built and stored in our artifactory that was built against `gcc 10.3`
We rebuilt the package with `gcc12`, and now, when we do a `conan search` for that package, in a `gcc 10.3` context, we receive the wrong recipe. 

my conan profile:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10.3
compiler.libcxx=libstdc++11
build_type=Release
[options]
date:use_system_tz_db=True
[build_requires]
*: cmake/[>=3.23.1]
[env]
```

and the search that returns the recipe with `compiler.version: 12` 
```
conan search arrow/7.0.0@ -r gsr
Existing packages for recipe arrow/7.0.0:

Existing recipe in remote 'gsr':

    Package_ID: 6c2fbc7681c246a51f96eac71182c96136d96e4b
        [options]
            cli: False
            compute: auto
            dataset_modules: False
            deprecated: True
            encryption: False
            fPIC: True
            filesystem_layer: False
            gandiva: False
            hdfs_bridgs: False
            parquet: True
            plasma: False
            runtime_simd_level: max
            shared: False
            simd_level: default
            with_backtrace: False
            with_boost: False
            with_brotli: False
            with_bz2: False
            with_csv: False
            with_cuda: False
            with_flight_rpc: False
            with_gflags: False
            with_glog: False
            with_grpc: False
            with_hiveserver2: False
            with_jemalloc: False
            with_json: False
            with_llvm: auto
            with_lz4: False
            with_openssl: False
            with_orc: False
            with_protobuf: False
            with_re2: True
            with_s3: False
            with_snappy: False
            with_utf8proc: auto
            with_zlib: False
            with_zstd: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 12
            os: Linux
        [requires]
            boost/1.77.0:83fcf0af66d2d8b7b7d60ef6c249b03c5b0dc744
            bzip2/1.0.8:3cfc45772763dad1237052f26c1fe8b2bae3f7d2
            libbacktrace/cci.20210118:2a19826344ff00be1c04403f2f8e7008ed3a7cc6
            libevent/2.1.12:fc397aedff33f10a79b59bd27bbf707923621ce2
            openssl/1.1.1n:2a19826344ff00be1c04403f2f8e7008ed3a7cc6
            re2/20211101:174df609440df17baf334e1f5953cca909f2ae18
            thrift/0.15.0:80289d2408076e67c7217a8fb8635c3c871593f6
            xsimd/8.0.3:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
            zlib/1.2.12:2a19826344ff00be1c04403f2f8e7008ed3a7cc6
        Outdated from recipe: False
```

We then deleted the gcc12 package manually from artifactory and we confirmed that the gcc10.3 package was still present on the artifactory side by looking at it from the artifactory gui. 

After this we can't find it anymore via command line:
```
:~$ conan search arrow/7.0.0@ -r gsr
Existing packages for recipe arrow/7.0.0:

Existing recipe in remote 'gsr':

There are no packages for reference 'arrow/7.0.0', but package recipe found.
```

You can find in the attachments the two conaninfo files, for the package being built with gcc10.3 and 12. 
I can see the compiler version mentioned there.
I am quite confused. 
I wonder if we are doing something wrong on our side. 

thank you in advance for your help

[conaninfo (1).txt](https://github.com/conan-io/conan/files/10131683/conaninfo.1.txt)
[conaninfo.txt](https://github.com/conan-io/conan/files/10131684/conaninfo.txt)

**Comment by memsharded** [comment]
Hi @davidebenato 

There is certainly something weird there. When you create and upload 2 different binaries with 2 different compiler versions, you should definitely get 2 different package_ids there. When doing a ``conan search <ref> -r=remote``, you should be able to list simultaneously the 2 binaries.

The only explanation that I can see is that you did some changes somehow to the recipe between runs (adding more exported files or something), so you end in the server with:
```
arrow/7.0.0
     revision1
          package_id1 (gcc 10.3)
     revision2
          package_id2 (gcc 12)
```

the idea is that when building from the same recipe, only one recipe revision should be there, and 2 binaries with 2 package_ids inside. Then you can perfectly decide to use one or the other without conflicts, no need to remove them. You can also install them both at the same time in the Conan cache.

So can you please confirm that both package_ids are under the same recipe revision?

**Comment by davidebenato** [comment]
I think we are on a good track. 
On the newer arrow version I did upgrade a third party dependency: 
```
self.requires("boost/1.77.0")
```
but I didn't update the version of the package itself. 

So we have:
```
gcc10.3
arrow/7.0.0
 //depends on
boost/1.73.0
```

I then pushed:
```
gcc12
arrow/7.0.0
 //depends on
boost/1.77.0
```

So I assume the package revision was bumped, and when trying to build with gcc10.3, conan looks at the latest revision, which wasn't built for 10.3.


How do you suggest to approach it? 
I assume bumping the versions of the libraries to something more specific would help:
```
arrow/7.0.0.12
```
Alternatively I could rebuild all the existing packages with updates base library dependencies, and then update to gcc12 with the same package revision.

If you confirm that's what's happening, we have a way forward.

**Comment by memsharded** [comment]
Good!

> but I didn't update the version of the package itself.

yes, I think it is the core issue. You did some changes to the recipe, but never built the other configuration. 
Conan resolves always to the latest recipe revision (or a fixed revision if specified). It builds the dependency graph, evaluates everything, and then check for configurations and binaries. But it cannot choose a recipe revision based on the binary existence for a given configuration (that would require backtracking and will be computationally intractable)

> How do you suggest to approach it?

The basic idea is that when a recipe changes (either the recipe or the source code), all the different configurations need to be built from those changes.  You can solve a bug in the code for example, or package a missing .lib. You need to build with that fix all the different binary configurations, in your case, both gcc 10.3 and 12, so the fixes remain consistent for all binary configurations.

**Comment by dkumsh** [comment]
Thanks a lot for your help!

**Comment by memsharded** [comment]
You are welcome! :) 

Then, that was the issue? Mystery solved? Please let me know if this ticket can be closed, and don't hesitate to open new tickets for any further question.

**Comment by dkumsh** [comment]
We have a project (TP for third party) which builds all third party libraries and uploads them to the artifactory. Let's call
Then consuming projects point to these artefacts (in the coanafile.py) and they expect these artifacts to be present in the artifactory.
In the  

We switched the compiler from 10.3 to 12.2, updated conan profile and then built the TP project with the new compiler.
 
The the issue was after this all the existing versions of the artifacts updated and the consuming project (which is still using gcc 10.3)  could not find the dependencies built with g++ 10.3 in the remote artifactory (as they were already updated with the ones built by g++ 12.2).   

At least for now we :
1. Understand what was going on
2. Have a workaround

As a workaround we 
1. pined the dependencies in the consuming projects to exact versions: <name>/<ver>@<rrev>:<prev>
2. then we can freely build and upload new third party dependencies without breaking existing projects
3. once we are happy with the new artifacts, we can  switch the compiler version for the consumer projects and then remove pinning in conanfiles.

I wonder if there is a better approach?

**Comment by memsharded** [comment]
> The the issue was after this all the existing versions of the artifacts updated and the consuming project (which is still using gcc 10.3) could not find the dependencies built with g++ 10.3 in the remote artifactory (as they were already updated with the ones built by g++ 12.2).

The real issue is that dependencies could not be found. The real reason is that there were changes in the recipes, that created a new recipe revision. It is perfectly fine to add a new profile for 12.2, get the binaries built for the new profile with existing recipes, and upload the new binaries to Artifactory that will be side by side to the previous gcc 10.3 binaries.

> I wonder if there is a better approach?

Another possibility is that you always build your third party packages for the active profiles. If you add a new gcc 12.2, and you fire a build of your project, you fire it for all your active profiles, including gcc 10.3. You can use things like ``--build=missing`` to avoid rebuilding existing ones, if there were existing binaries and the recipe didn't change, Conan will not build it. It is not necessary to pin exact versions or revisions if you want to keep updating continuously, but the binaries for all active profiles/configurations when a recipe change needs to be built.

**Comment by dkumsh** [comment]
Thanks again, we are going to try these suggestions.
