### ISSUE TITLE
Specify target folder for install rather than $CWD

### ISSUE THREAD

**Issue by TheJare** [conan-io/conan#1265]
## Suggestion
Provide options to specify the target folder where `conan install` will create generated files.
* in the conanfile.txt itself
* from the command line 

## Rationale
To keep project folders clean, it is desirable that generated files from build systems go to their own folders, not mixed with the source folders. Thus, it should be expected for the `conanbuildinfo.cmake` and `conaninfo.txt` to go to a different folder than the `conanfile.txt`. However, `conan install` will create these files in the current directory, so in order to give them their own folder, the user must `mkdir` and `cd` to it manually. This seems really unergonomic, in particular when the project's `CMakeLists.txt` will have to refer to the generated `conanbuildinfo.cmake` file in that folder... which the user has had to create on their own, with possibly a different name than given in the `CMakeLists.txt`

**Comment by memsharded** [comment]
Hi @TheJare,

The current design rationale is that all commands (``install``, ``build``, ``source``, ``package``, etc) works in $CWD, trying to provide a uniform behavior for all of them. 

``conan install`` is executed in a temporary user build folder, which will be cmake ``CMAKE_BINARY_DIR`` folder, and CMakeLists.txt usually include conanbuildinfo.cmake with ``include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)``, and this works fine. Could you please clarify a bit further the issue with these cmake paths?

Thanks for your feedback. It is useful as right now we are reviewing all path related issues, check this open PR: https://github.com/conan-io/conan/pull/1259/files#diff-ecc7c2162dace776bac94fc2ba5cec58R468, where commands are getting ``--build_folder``, ``--source_folder`` to indicate paths. We might add more (or maybe provide ``install`` with the target ``--build_folder`` argument). Please tell me about the above, and we will try to include in ongoing work for next release. Thanks!

**Comment by TheJare** [comment]
@memsharded 

Yeah the approach you describe works of course. CMake also tends to default to $CWD as target (other than those "undocumented" command line arguments -B and -H) so it may makes sense to mimic that behaviour. I'm not really a cmake user, so I'm probably just coming with a different mindset that having arguments and never needing to rely on $CWD seems more ergonomic.

**Comment by memsharded** [comment]
Thanks for the feedback. What do you think @lasote? Maybe it makes sense to add some ``--cwd`` argument to commands?

**Comment by lasote** [comment]
I'm not sure, CMake uses exactly the same way to change the build directory (mkdir + cd + cmake ..). Let's check if adding the `cwd` arguments keeps the code clean enough, if don't I think is not so critical.

**Comment by memsharded** [comment]
Fixed. Not only this, but major improvements over the whole api, now featuring a python api (still internal, will be documented after stabilizing)
