### ISSUE TITLE
[question] 2.0.0b6, trying to create a cross-compile toolchain, using documentation example fails parsing.

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#12658]
Using this example as a conan2 profile (from https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#cross-building-examples-profiles):

```
target_host=arm-linux-gnueabihf
standalone_toolchain=C:/sysgcc/raspberry
cc_compiler=gcc
cxx_compiler=g++

[settings]
os=Linux
arch=armv7 # Change to armv6 if you are using Raspberry 1
compiler=gcc
compiler.version=6
compiler.libcxx=libstdc++11
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/$target_host
CONAN_CMAKE_SYSROOT=$standalone_toolchain/$target_host/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
LD=$target_host-ld
STRIP=$target_host-strip
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
CXXFLAGS=-I"$standalone_toolchain/$target_host/lib/include"
```

I am getting:

```
+ conan install . --build=missing -pr:b=default -pr:h=arm
ERROR: Error reading 'arm' profile: Error while parsing line 0: 'target_host=arm-linux-gnueabihf'
```

Are conan2 profiles requiring a different syntax?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @hpe-ykoehler 

We have removed the custom variable replace in Conan 2.0, in favor of jinja2 template syntax.
This has been introduced for profiles in Conan 1.X so you can already migrate to it, to be 2.0 ready.

Have a look to it in https://docs.conan.io/en/latest/reference/profiles.html#profile-templates

Thanks for reporting.

**Comment by hpe-ykoehler** [comment]
Ok, I read about that profile templates but it was not clear from the 2.0 migration document that this profile template feature was now mandatory for 2.0. 

I would recommend that this be clarified in the 2.0 migration guide.  In general, things that were in 1.x optional but mandatory in 2.0 should be somehow highlighted in some way.

https://docs.conan.io/en/2.0/whatsnew.html

**Comment by hpe-ykoehler** [comment]
Is there an example on how to set env in profile ?  Somehow I only see [settings] as the only block allowed in profile.  I am unclear how to set the CC/CXX and other cross-compiling variables in conan2.0

**Comment by memsharded** [comment]
> Is there an example on how to set env in profile ? Somehow I only see [settings] as the only block allowed in profile. I am unclear how to set the CC/CXX and other cross-compiling variables in conan2.0

Yes, you can generally define environment with the modern tooling as described in: https://docs.conan.io/en/latest/reference/profiles.html#buildenv, (with ``[buildenv]`` in profiles, with ``self.buildenv_info`` in recipes)

Conan 1.55 also introduced new ``tools.build:compiler_executables`` as an abstract way to define compiler path, even for systems that might not listen to CC/CXX env-vars (CMakeToolchain will map that to CMAKE_CXX_COMPILER for example)

**Comment by memsharded** [comment]
Closing this question as responded, please re-open or create a new ticket if there are further issues.
