### ISSUE TITLE
Conan 2.0 - Are formatters supported with multiple arguments?

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12668]
I have a custom command that returns a list of good package and a list of bad packages. The first parts works perfectly. However when I went to add the second return + arg it's not being passed to my formatter 😭 

My command:

![image](https://user-images.githubusercontent.com/16867443/206001640-7d4bbf70-adbf-4bd7-bdf7-e1f4ddc7f700.png)
![image](https://user-images.githubusercontent.com/16867443/206001843-c2224fd5-b74d-4b36-80ff-4e21f0806d2e.png)

This is the line that is not passing my formatter (but my python is not good enough to sort that out) the second arg
https://github.com/conan-io/conan/blob/a58212142a8919ce97a8ba45cad20eaed90c6975/conan/cli/command.py#L144

Looking in the code base I exclusively find example taking only 1 arg
https://github.com/conan-io/conan/blob/d23c1b4631a297112d67ed2e6adb3a961b58d2c6/conans/cli/commands/user.py#L7

**Comment by prince-chrismc** [comment]
Is it safe for user to use https://github.com/conan-io/conan/blob/d23c1b4631a297112d67ed2e6adb3a961b58d2c6/conans/cli/commands/user.py#L9 as well that would be very nice!

**Comment by prince-chrismc** [comment]
And lastly here is my code https://github.com/prince-chrismc/conan-center-index/commit/375b5ec1412c0d6654284376e822c77e925d7038

**Comment by memsharded** [comment]
Yes, it is possible. Look for ``CommandResult`` return class in existing commands.

Then, your formatters can take any arguments. Only arguments matching ``CommandResult`` fields will be passed, making it very convenient. The ``conan_api`` is always automatically available:


```python
return CommandResult({"graph": deps_graph,
                          "field_filter": args.filter,
                          "package_filter": args.package_filter})

def format_graph_info(graph, field_filter, package_filter):

def format_graph_html(graph, conan_api):

def format_graph_dot(graph, conan_api):

def format_graph_json(graph):
```


I still need to check if it is possible to avoid the ``CommandResult`` completely (and return just a tuple), but didn't have time to investigate:

**Comment by prince-chrismc** [comment]
My workaround was to use a `dict` so I believe a `tuple` would work.
I'll need to checkout the `CommandResult` 👍

**Comment by prince-chrismc** [comment]
Playing with The `CommandResult` I found an awkward UX thing. It only works if I override the default `"text"` 

```log
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/cli.py", line 170, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/command.py", line 144, in run
    self._format(conan_api, self._parser, info, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/command.py", line 103, in _format
    formatter(**kwargs)
TypeError: BaseConanCommand.__init__.<locals>.<lambda>() missing 1 required positional argument: 'x'

ERROR: BaseConanCommand.__init__.<locals>.<lambda>() missing 1 required positional argument: 'x'
```

The default formatter takes only 1 arg `x` which is not matched

```py
class BaseConanCommand(object):
    def __init__(self, method, formatters=None):
        self._formatters = {"text": lambda x: None}
```

which seems to my problem, I got it working by overriding that default https://github.com/prince-chrismc/conan-center-index/commit/ea34f93770ab87d611d0e8a47f2b01cb022f7862 with

```py

@conan_command(group="Conan Center Index", formatters={"text": lambda exported, failures: None, "json": output_json, "md": output_markdown})
def export_all_versions(conan_api, parser, *args):
```

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12682
