### ISSUE TITLE
[question] How to build MacOS Universal2 with a mix on Universal2 and non-Universal2 Conan packages

### ISSUE THREAD

**Issue by rkeithhill-keysight** [conan-io/conan#12667]
Does anybody have any experience creating Conan pkgs for Apple Universal2/fat binaries i.e. those that contain both `x86_64` & `arm64` code?  The recommended approach seems to be to remove the arch setting to indicate a pkg is "any architecture": https://github.com/conan-io/conan-extensions/issues/59  That isn't quite true for Universal2 as it only supports `x86_64` and `arm64` architectures.  However, you can't specify multiple architectures for the Conan arch setting and as of 1.54, `universal2` is not a recognized arch setting.

CMake supports building Universal2 (fat) binaries and static libs quite nicely with this one setting:
```cmake
set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64" CACHE STRING "" FORCE)
```

This will compile each source file with `-arch arm64 -arch x86_64` producing fat o files that can be linked into either fat binaries or fat static libs.  Pretty neat but once you introduce other Conan pkgs into the picture, particularly source-only packages that don't build universals libs directly, things fall apart.  Since Conan drives the CMake build process and there is no Conan arch to specify you want a fat lib, the best you can do AFAICT is run `conan install` twice: once for the `x86_64` and again for `arm64`.  But when you go to build your source, you have to specify either arch=x86_64 or arch=x64 when referencing those pkgs (think gtest or poco).  You can't remove the arch setting for those pkgs, arch is a required setting. If you do, Conan won't find a matching recipe.  So if you pick arch=x86_64 you wind up with a conanbuildinfo.cmake that references the gtest x86_64 architecture and then fails to build a fat o file because it can't find the arm64 version e.g.:

```
ld: warning: ignoring file /Users/hillr/.conan/data/gtest/1.8.1-1/conan/stable/package/05e7d98d1302d7e4c4029b91efa8810e5bf7de58/lib/libgmockd.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

So, unless the Conan src pkg you need to build knows how to build for Universal2, I'm not sure how you get Conan to tell CMake, "Hey, for this here gtest pkg, when you link to it, refer to the libs in BOTH the x86_64 **and** arm64 recipes".  I don't know of a way to do that.  It's looking like the best way to build is to build separately for `x86_64` and `arm64` and then at the end create a fat lib (or binary) from each build.  What's frustrating is that you can do this from the command line easily.  It is very simple to build an x86_64 binary against a fat static lib or an arm64 binary against that same fat lib or a fat binary against that same fat lib.  Put Conan into the mix and that simplicity seems to evaporate. 😢 

Is there something I'm missing that would make Conan get on board with Universal2 builds?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by benthevining** [comment]
Is there any update on this issue? What is the recommended way to work with universal binaries while using Conan? Is it simply not supported?

**Comment by petermbauer** [comment]
I am also be interested in this

**Comment by AbrilRBS** [comment]
Hi! In Conan 2 we have finally implemented support for these kind of binaries, please check https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#support-for-universal-binaries-in-macos, we are happy to hear your feedback in it if you end up using it! :)

Closing as solved for now, don't hesitate to reopen/create a new issue if you need to though!
