### ISSUE TITLE
[feature] Move common `package_info` cases to functions

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#12662]
While learning from @uilianries and @jcar87 the review process at conan-index-center, I asked if there was a way to reduce the boilerplate needed in `package_info`, that is, in the same way that `layout` has `basic_layout`, `cmake_layout` etc, if (for example) header-only libraries had a tool function that meant
```py
self.cpp_info.bindirs = []
self.cpp_info.libdirs = []
```
so it didn't need to be defined every time in every recipe.

This issue is a request for such functionality in a way that reduces repetition, as the answer was "no, and you should probably open an issue requesting it" :)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
In Conan 2.0, we have explicit model for ``package_type = "header-library"``. Besides what you suggest, it is possible to use that information for the clearing settings/options with ``self.info.clear()`` in ``package_id()``

**Comment by AbrilRBS** [comment]
That makes lots of sense, thanks! I'll ask Uilian see if I misunderstood anything or if he meant something different :)
