### ISSUE TITLE
[question] Why conan v2 wants to give precedence to user defined config over usage requirement of recipe?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12669]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In source code, I see logic giving precedence to config from user over optional arguments of build helpers.

For example in generator attribute of CMakeToolchain: https://github.com/conan-io/conan/blob/d23c1b4631a297112d67ed2e6adb3a961b58d2c6/conan/tools/cmake/toolchain/toolchain.py#L206-L213

Let's consider a recipe whose generator MUST be Ninja. This recipe would add ninja to build requirement, and force Ninja in CMakeToolchain constructor. But if user defines another generator in `tools.cmake.cmaketoolchain:generator`, it will break the build.
You could answer that it's a good behavior, user has to change its user defined generator explicitly. But let's say user has to build 50 recipes in its dependency graph, one MUST be built with Ninja, and another MUST not be built with Ninja, so user would have to specify in command line a different generator per recipe, it's a terrible user experience (imagine the combinatory explosion of recipes usage requirements that users could have to define in command line to be able to build their dependency graph).
Recipes always know better than user when something must be forced (a usage requirement), obviously it must be used sparingly in recipes, but when it has to be done I believe recipes should have precedence over user defined configs.

**Comment by AbrilRBS** [comment]
Hi! Sorry for the radio silence - answering here just for posterity, I know that you know by now that this is a fundamental design concept. Recipes should check in their `validate()`/`validate_build()` methods for these kinds of restrictions and raise accordingly

Closing this as solved, feel free to reopen/create a new issue should you have any other questions or requests, thanks!

**Comment by SpaceIm** [comment]
Thanks for answering.

I know it's a fundamental design concept of conan v2. While I can understand that users want their settings, custom build flags and recipes options to be honored, I think that underlying CMake generator is really an internal detail, it's just a wish, and nobody cares if recipe silently fallbacks to another one if it's absolutely necessary and can avoid build to fail.
What is better in these 2 approaches:

A conanfile with dozens of dependencies.

- conan design:

  ```
  conan install . -b missing
  ```

  recipeA reports ConanInvalidConfiguration because it knows that it fails with Ninja and Visual Studio compiler.

  So user tries another command:

  ```
  conan install . -b missing -c "recipeA/*:tools.cmake.cmaketoolchain:generator=Visual Studio 17 2022"
  ```

  now recipeB also raises, and again user has to update its command:

  ```
  conan install . -b missing -c "recipeA/*:tools.cmake.cmaketoolchain:generator=Visual Studio 17 2022" -c "recipeB/*:tools.cmake.cmaketoolchain:generator=Visual Studio 17 2022"
  ```

  and again and again until it succeeds. User will have to document somewhere all these special cases, maybe a huge conan command. And it will be probably hard for users to integrate these conf to IDE conan plugins.
  

- recipe can override CMake generator:

  ```
  conan install . -b missing
  ```

  It succeeds out of the box, user doesn't waste its time. Yes some libs may have been built with MSBuild instead of Ninja (only when it was mandatory), but it works, and who cares? Anyway you can't control underlying build system used by recipes, so not always having control over CMake generator is not really important.

In ginkgo recipe, I had to write this: https://github.com/conan-io/conan-center-index/blob/234dc7a3a124bdf4ff893fbc2bbb7073a013eace/recipes/ginkgo/all/conanfile.py#L104-L154 (I even display a warning message to notify users that `tools.cmake.cmaketoolchain:generator=Ninja` can't be honored in this recipe for this combination of settings & options).
