### ISSUE TITLE
option does not exists

### ISSUE THREAD

**Issue by vvavrychuk** [conan-io/conan#1266]
Output is

    conan install --build Poco -o cxx_14=true
    ERROR: 'options.cxx_14' doesn't exist
    Possible options are []

even so looking on https://www.conan.io/source/Poco/1.7.3/lasote/stable I see option existing.

conanfile is

    [requires]
    Poco/1.7.3@lasote/stable
    [generators]
    gcc

Conan version 0.22.3

**Comment by memsharded** [comment]
Please try:

```bash
conan install --build Poco -o Poco:cxx_14=True
```
Note uppercase ``True`` too.

**Comment by vvavrychuk** [comment]
It works. Thanks.

**Comment by memsharded** [comment]
Great, thanks for updating!
