### ISSUE TITLE
[question] when to use self.info.settings instead of self.settings

### ISSUE THREAD

**Issue by dovydas-girdvainis** [conan-io/conan#12671]
Helo everyone, 

in the *The validate() method* section, [conan v2 migration guide](https://docs.conan.io/en/1.55/migrating_to_2.0/recipes.html#the-validate-method) states that we need to:

 > always use `self.info.settings` and ` self.info.options`  instead of `self.settings` and `self.options` 

Does this mean that **ALL** calls to `self.settings` and `self.options`  should be reworked into  `self.info.settings` and ` self.info.options` or should it only be the calls to `self.settings` and `self.options`  within the `validate()` method scope?

[cmake_package](https://github.com/conan-io/conan-center-index/blob/master/docs/package_templates/cmake_package/all/conanfile.py) example only uses `self.info.*` within the validate method, so I am guessing it is supposed to be done only within the `validate()` method scope, but the way docu is formulated, implies that any call to `self.settings` and `self.options`  should be done via the `self.info.*` field.

Could you clarify this for me, please?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @saukijan 

We finally managed to settle down this in latest releases (1.55 and 2.0-beta.6), the final approach should be:

- ``validate()`` and ``validate_build()`` should use ``self.settings and self.options``
- Only ``package_id()`` should use ``self.info.settings`` and ``self.info.options``

We need to update the templates, thanks for pointing this out!

**Comment by dovydas-girdvainis** [comment]
Thanks for the clarification!
