### ISSUE TITLE
Question about imports in conanfile.py

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#1267]
Hi everyone,

I'm using this in a conanfile **.txt** for a project destined only for building locally (not a package):

```
[imports]
bin, *.dll -> ./bin
shaders, * -> ./bin/resources/shaders
```
If I were to use a conanfile **.py**, is there an equivalent way to copy the dlls and other resources from my requirements to my bin directory?

**Comment by memsharded** [comment]
Hi @dimi309,

Yes, conanfile.py has their own ``imports()`` method, check here: http://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

Basically something like:
```python
def imports(self):
   self.copy("*.dll", "", "bin")
   self.copy("*.dylib", "", "lib")
```

**Comment by dimi309** [comment]
Ah! I didn't find that myself (sorry..). Thanks a million!

**Comment by memsharded** [comment]
No worries :)
