### ISSUE TITLE
[question] how to check package version in Conan v2

### ISSUE THREAD

**Issue by dovydas-girdvainis** [conan-io/conan#12670]
Hello, I am working on [Package/open62541: bump to v1.3.4](https://github.com/conan-io/conan-center-index/pull/14537#top)
 and I am not certain what is the proper way of checking the configured Conan package version in v2.

Some package options are version specific and will not work for all versions. Previously I used [`tools.Version()`](https://docs.conan.io/en/1.55/reference/tools.html#tools-version) from the `conans.tools` module to check the `self.version` field, but that is no longer available. 

I looked around other recipes for examples and found in [libpqxx](https://github.com/conan-io/conan-center-index/blob/master/recipes/libpqxx/all/conanfile.py) that I could use `from conan.tools.scm import Version`  the same way as the old  `conans.tools.Version`, but sadly there is no documentation available for `conan.tools.scm` module in conan v2 tools docu so I am unsure if this is the intended use. 

Could you clarify this a bit for me?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @saukijan 

Yes, the docs for 2.0 is a work in progress, so it might not contain many things that are already in 1.X docs. 
From the Conan 1.X docs, it is safe to assume that:
- https://docs.conan.io/en/latest/reference/conanfile/tools.html
- https://docs.conan.io/en/latest/conan_v2.html

Is good to be used as it will stay in Conan 2.0

**Comment by dovydas-girdvainis** [comment]
Thank you!
