### ISSUE TITLE
[question] 2.0 Migration how to check MSVC version without raising an error

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12680]
To have a recipe that works for 1.x and 2.0 we need to check both `"Visual Studio"` and `"msvc"` however each uses a different version scheme so both need to be check individually.

For example 

https://github.com/conan-io/conan-center-index/blob/e72e91ee19975973e7ca1a4d8e2b714be60b0175/recipes/jsoncpp/all/conanfile.py#L73-L74

would become

```py
        if (self.settings.compiler == "Visual Studio" and self.settings.compiler.version == "11") or \
           (self.settings.compiler == "msvc" and self.settings.compiler.version == "100"): # might be wrong versions its too old
```

But in 2.0 this would still produce the error for using an unknown compiler.

```log
jsoncpp/1.9.5: Error in build() method, line 79
	self._patch_sources()
while calling '_patch_sources', line 73
	if self.settings.compiler == "Visual Studio" and self.settings.compiler.version == "11":
	ConanException: Invalid setting 'Visual Studio' is not a valid 'settings.compiler' value.
Possible values are ['sun-cc', 'gcc', 'msvc', 'clang', 'apple-clang', 'intel-cc', 'qcc', 'mcst-lcc']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

Typically we would use https://docs.conan.io/en/1.53/reference/conanfile/tools/microsoft.html#check-min-vs but that raises an except which is not the required effect here

**Comment by prince-chrismc** [comment]
There's an example in CCI that does this https://github.com/conan-io/conan-center-index/blob/e72e91ee19975973e7ca1a4d8e2b714be60b0175/recipes/libbacktrace/all/conanfile.py#L86

Which fails with the develop2 branch 😄

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan/issues/11158#issuecomment-1252341119

**Comment by prince-chrismc** [comment]
Oh I would like the opposite, only care about msvc ver not the IDE

**Comment by SpaceIm** [comment]
Not a good idea, such function would become useless in conan v2, while a function returning IDE version from msvc version would still be useful (see libvpx recipe in conan-center for example).

**Comment by memsharded** [comment]
Closing as outdated.
