### ISSUE TITLE
[question] Should Conan 2.0 export-pkg command process package_info?

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12685]
I'm seeing an issue when trying to run the export-pkg command on Windows. More specifically, during the export-pkg process, the conanfile.py method is called (as expected), which, in turn, calls Autotools.install. The issue arises due to the fact that this call needs the msys2 toolchain, which is specified in the recipe as a tool_requires in the build_requirements() method.

The msys2 package is available in the local cache, having been placed their when the standalone build command was run. However, it is not being found when the package() method is called in the export-pkg command because the conf settings ("tools.microsoft.bash:subsystem" and "tools.microsoft.bash:path"), which the msys2 recipe's package_info() method sets, have not been reestablished. Is this an oversight in the implementation of export-pkg or an incorrect use of package_info? If the latter, what is the recommended strategy and, if the former, let me know and I can turn this into a bug report.

As an aside, it seems to me that in Conan 2.0, where as I understand it, the package_folder is not available until the package() method is invoked, the package() method should be viewed as a build step and thus permitted to depend on tool_requires dependencies for its actions.

Thanks.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by System-Arch** [comment]
Hi @memsharded,

I believe this is a manifestation of the same issue reported in #12154 where again the tool_requires conf_info settings are not being honored during packaging. In my case, the failure mode looks like:

> conan-2.0 export-pkg -pr:b tools.jinja -pr:h tools.jinja --name m4 --version 1.4.19 .
> m4/1.4.19: Exporting package recipe
> m4/1.4.19 exports: File 'conandata.yml' found. Exporting it...
> m4/1.4.19: Copied 1 '.yml' file: conandata.yml
> m4/1.4.19 exports: Copied 1 '.yml' file: conandata.yml
> m4/1.4.19: Calling export_sources()
> m4/1.4.19: Using the exported files summary hash as the recipe revision: bc35d9ab817a28d0d6fa4e50252000c7
> m4/1.4.19: A new conanfile.py version was exported
> m4/1.4.19: Folder: C:\Users\marc\.conan2\p\a4957b36fa366362\e
> m4/1.4.19: Exported revision: bc35d9ab817a28d0d6fa4e50252000c7
> Packaging to 723257509aee8a72faf021920c2874abc738e029
> conanfile.py (m4/1.4.19): Generating the package
> conanfile.py (m4/1.4.19): Temporary package folder C:\Users\marc\.conan2\p\tmp\5a926c85e3b898b7\p
> conanfile.py (m4/1.4.19): Calling package()
> conanfile.py (m4/1.4.19): Copied 1 file: COPYING
> ERROR: conanfile.py (m4/1.4.19): Error in package() method, line 120
>         autotools.install(args=[f"DESTDIR={unix_path(self, self.package_folder)}"])
>         ConanException: win_bash=True but tools.microsoft.bash:subsystem configuration not defined

Is this bug? Shouldn't Conan should be able to handle this situation? Thanks.

**Comment by memsharded** [comment]
Are you sure you are testing this in 2.0? It seems that the ``msys2`` package is not working yet for 2.0.

**Comment by memsharded** [comment]
I fixed msys2 (I saw that you have a PR for conan-center-index), and managed to reproduce this.
Indeed ``export-pkg`` is doing some assumptions that exclude ``tool_requires`` for the ``package()`` method. 
I will be proposing a fix soon, many thanks for reporting.

**Comment by System-Arch** [comment]
Hi @memsharded,
Thank you digging into this issue and developing a fix. I dropped your changes into my build environment and confirmed that they do indeed address the problem I was seeing. This will enable me to remove the workaround I had added to the recipe. Thanks again.

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/12769 will be in beta8
