### ISSUE TITLE
[question] How to overrite tool_requires ? 

### ISSUE THREAD

**Issue by dotChris90** [conan-io/conan#12686]
Hello, 

just want to understand how to overrite tool_requires? 
To be very precise i am using conan 1.55 and include this method to conanfile.py

`def build_requirements(self):
        self.tool_requires("doxygen/1.9.1")
        self.tool_requires("cppcheck/2.7.4")`

and get error 
'pcre/8.45' requires 'zlib/1.2.13' while 'doxygen/1.9.1' requires 'zlib/1.2.12'. 

The reason is quite easy - i want to include cppcheck and doxygen to project and cannot do because they conflicting each other - now question : how to handle this? at the normal requriements method i simply can overrite it by add it as a requirement but how to handle here? i read that the overriding was excluded for build_requirements but i didnt see any solution.   

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dotChris90 

Sorry this question was not responded back then, the repo can be be very busy some times, so some tickets are buried in the backlog, and we have been busy with 2.0 launch too.

Did you find some answers to this? Thanks!
