### ISSUE TITLE
[question] LIB_DIRS variables in V1 have build type suffix (LIB_DIRS_RELEASE) in V2?

### ISSUE THREAD

**Issue by joshvazquez-amzn** [conan-io/conan#12684]
This could be something very easy that I have overlooked. I wrote a simple conanfile.py using `conans.ConanFile` and `conans.CMake` as well as the generator `cmake_find_package`. My `CMakeLists.txt` had lines like this referencing other Conan packages in my `requires`:
```
find_package(foo REQUIRED)
include_directories(${foo_INCLUDE_DIRS})
link_directories(${foo_LIB_DIRS})
```
I use `conan create`. Upon converting this recipe to Conan V2 format using `conan.ConanFile` and `conan.tools.cmake.CMake` as well as the generators `conan.tools.cmake.CMakeToolchain` and `conan.tools.cmake.CMakeDeps`, I started getting linker errors that only went away when I updated my `link_directories` commands after realizing that the `LIB_DIRS` variables no longer existed but `LIB_DIRS_RELEASE` variables were there instead.

Although both versions of the recipe run CMake with `CMAKE_BUILD_TYPE=Release`, the suffix is only there when building from the V2 recipe. Is this difference documented anywhere?

Interestingly, for gtest I also had to change `include_directories(${GTest_INCLUDE_DIRS})` to `include_directories(${gtest_INCLUDE_DIRS_RELEASE})`. Not only did the case change but the `_RELEASE` suffix is needed here whereas on my other dependencies it is only on `LIB_DIRS`. Is this behavior recipe-specific?

Conan 1.55.0

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by joshvazquez-amzn** [comment]
#12222 Related?

**Comment by joshvazquez-amzn** [comment]
Minimal example:
CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.16)
project(reproduction)

find_package(nng REQUIRED)
include_directories(${nng_INCLUDE_DIRS})
link_directories(${nng_LIB_DIRS})

add_executable(reproduction)
target_link_libraries(reproduction PRIVATE nng)
target_sources(reproduction PRIVATE main.cpp)
```

conanfile.py:
```
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps
from conan.tools.files import copy

class Repro(ConanFile):
    name = "repro"
    version = "0.1"
    requires = "nng/1.5.2"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def export_sources(self):
        copy(self, "CMakeLists.txt", self.recipe_folder, self.export_sources_folder)
        copy(self, "main.cpp", self.recipe_folder, self.export_sources_folder)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()
```

main.cpp:
```
#include <nng/nng.h>

int main() {}
```

```
$ conan create .
...
/usr/bin/ld: cannot find -lnng
collect2: error: ld returned 1 exit status
...
```

**Comment by memsharded** [comment]
Hi @joshvazquez-amzn 

The legacy ``cmake`` and ``cmake_find_package`` generators are single-config, while the new ``CMakeDeps`` is multi-config. That means that the  generation of files always include the build_type.

The thing is that those variables are actually not intended for public usage (in the modern ``CMakeDeps`` generator), but instead use the package public targets. Is there any reason why using the targets won't work? Have you tried that?

**Comment by joshvazquez-amzn** [comment]
I'm not very experienced with CMake, but doing that worked, thanks!
```
cmake_minimum_required(VERSION 3.16)
project(reproduction)

find_package(nng REQUIRED)

add_executable(reproduction)
target_link_libraries(reproduction PRIVATE nng::nng)
target_sources(reproduction PRIVATE main.cpp)
```

**Comment by memsharded** [comment]
> I'm not very experienced with CMake, but doing that worked, thanks!

Perfect, I am very happy that it worked! :) 

Yes, that is the idea of "modern CMake", that is all about targets. Not needing to worry about individual properties like includedirs, libdirs, but the target includes all the related information for that specific library, including its includedirs.
