### ISSUE TITLE
[feature] Follow XDG Base Directory Specification on Linux

### ISSUE THREAD

**Issue by xvitaly** [conan-io/conan#12690]
Follow [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Linux, BSD, etc.

Configs should be stored in `$XDG_CONFIG_HOME/.conan2` and caches in `$XDG_CACHE_HOME/.conan2`.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by xvitaly** [comment]
On Windows it should be `%APPDATA%\conan2` for configs and `%LOCALAPPDATA%\conan2` for caches.

**Comment by memsharded** [comment]
This is a duplicated of https://github.com/conan-io/conan/issues/2526, closing this issue as duplicated, follow up the existing issue, please. Thanks!
