### ISSUE TITLE
[develop2] ``package_id`` cannot access ``self.options`` or ``self.settings``, even for read-only

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#12693]
``self.options`` and ``self.settings`` have validation, so they are better for expressions like ``if self.settings.compiler == "gcc"`` inside ``package_id()`` method, because they can detect typos and other mistakes, while ``self.info.xxxx`` allows modification, but doesn't contain any validation.
But Conan 2.0 is now raising while trying to read ``self.settings`` and ``self.options``

- Do we want to allow read-only of ``self.settings`` and ``self.options``
- Keep the current behavior, and restrict to ``self.info`` inside ``package_id()``

**Comment by maxtruxa** [comment]
> But Conan 2.0 is now raising while trying to read `self.settings` and `self.options`

Looking a bit back in time, this behavior was first introduced with b5d9426d0371798a82282d97642c1919fd725665, reverted with dd3ff9663bf10c14073da3898af837e6f1876cbb and then reintroduced with ee0f42e740896106ffa40ee21cc44715e99bfd8b.

Can you offer any insight into the motivation behind the change? Trying to prevent people from shooting themselves in the foot by modifying stuff from `package_id()`?

**Comment by memsharded** [comment]
> Can you offer any insight into the motivation behind the change? Trying to prevent people from shooting themselves in the foot by modifying stuff from package_id()?

Yes, the part of forbidding its access is exactly to avoid user errors, but precisely not for shooting themselves in the foot, if the error is that evident, it is less of an issue. But this one is typically more complex to understand the side effects, or analyze why ``compatibility()`` for example doesn't work as expected.

It is true that we have been iterating back and forth, because we didn't manage to find an adequate solution and it was challenging to analyze all aspects of Conan 1.X and 2.0 simultaneously and also the transition between both.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12776
