### ISSUE TITLE
Prevent -L library search paths being added for header-only packages?

### ISSUE THREAD

**Issue by thoughton** [conan-io/conan#1269]
Hi,

I've just created my first Conan package, so I'm still very much learning the basics.

It's a simple package for a header-only library, and I created it using the `conan new -i -t` command.

Pretty much everything is working brilliantly, but the only thing that's slightly bothering me is that when I build a program that depends on my new package, I receive the following warning from the linker:

`ld: warning: directory not found for option '-L~/.conan/data/linmath/latest/thoughton/testing/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib'`

Of course for a header-only package it makes sense that there's no lib binary in the package, and no "lib" directory for it.

So I was just wondering whether there's any way of either suppressing this path being added to the generated build files (in my case CMake and Makefiles), or alternatively always creating the lib directory even though it's empty?

Thanks in advance!

**Comment by thoughton** [comment]
PS. Here's a link to the github repository of my package: https://github.com/thoughton/conan-linmath
And here's the package itself on Conan.io: https://www.conan.io/source/linmath/latest/thoughton/testing

**Comment by memsharded** [comment]
Hi @thoughton !

The default is to add the "lib" directory to it, and the impact on linker performance is usually small.
If you want to not being included, just add to your recipe package_info:

```python
def package_info(self):
     self.cpp_info.libdirs = []
     # self.cpp_info.bindirs = [] # to avoid binary directories being added to some generators like visual_studio
```

Please try this and tell me. Cheers!

**Comment by thoughton** [comment]
Hi @memsharded, thanks for the quick response!

Your suggestion worked like a charm - thank you! 👍

**Comment by memsharded** [comment]
Excellent, thanks for telling :)
