### ISSUE TITLE
[feature] Support list type as option value

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#12700]
For those cases where more than one value is possible for an option, it would be great accepting a list and as its value. For instance:

```python
class FooConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "instructions": [None, "ANY"]}
    default_options = {"shared": False, "instructions": ["avx", "sse2", "sse4"]}
```

The `instructions` will be converted to a string, as it will be a `PackageOption` which converts any content to a string, so we would need to convert again to a list in the code in case need to access one of those values.

So far we can't use such feature, we need to create a single option for each value, which seems be too much, depending the situation. The OptionValue is smart enough right now to support boolean, string and integer, right now.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @uilianries 

I am a bit concerned of the added complexity that bringing the ``list`` type to options values will bring:
- Options are defined in ``conaninfo.txt`` that is uploaded, evaluated in the server side, downloaded back
- Options can be defined in profiles, and in cli args, but those formats only understand text, so in a profile ``["arch1", "arch2"]`` is *not* a list, but a string. Then it needs to evaluate (``eval``), but that opens the doors to any other type, including booleans, dicts, etc. 
- Options are returned by commands like ``conan graph build-order``, as json objects.
- The assumption that all options (and settings) values are always ``str`` strings is quite ingrained in the code, and allowing there multiple Python types (boolean, list, dicts, tuples, sets...) would break that assumption.

I am not saying it is impossible, but it seems that allowing a list there will bring tons of related edge cases, and could have multiple side unexpected effects, and introduce instability. Are there many similar use cases in other ConanCenter recipes?

**Comment by uilianries** [comment]
> Are there many similar use cases in other ConanCenter recipes?

A few.

https://github.com/conan-io/conan-center-index/pull/14597/files#diff-f6c5d2d813e11b0de0b86d011c47e546640d0f395678d09737de367e1d5da28bR24

https://github.com/conan-io/conan-center-index/blob/66f9091a2da1166ec51c4a265c4b91b2fd3eba11/recipes/dlib/all/conanfile.py

https://github.com/conan-io/conan-center-index/blob/d1c696963a72d02cb18c6497f886c56b2fbc5e13/recipes/botan/all/conanfile.py

https://github.com/conan-io/conan-center-index/blob/15b9a6cfc4c664901e8b144851eeb4b69c42854d/recipes/libvpx/all/conanfile.py

https://github.com/conan-io/conan-center-index/blob/133f7e3081a502d3fdb83a856d2c43b5673c7668/recipes/ffmpeg/all/conanfile.py#L72

https://github.com/conan-io/conan-center-index/blob/864494907926ccebf230f129b7c351e432ffec48/recipes/libfabric/all/conanfile.py#L17

https://github.com/conan-io/conan-center-index/blob/f3b046d14179cbf7732435855a7774f467b3cb3d/recipes/llvm-core/all/conanfile.py#L32

Most of them a support multiple values to a same option. So there is two main usages, accept `"ANY"` and the string passed as value is split like `str().split(",")`. A second option is listing all possible values in separated options for each value.

**Comment by memsharded** [comment]
Thanks for the links. I see some nice solutions there using dicts. There is a clear advantage using multiple options instead of a single option that has a list of values, and it is that the ``package_id`` will be more deterministic, as Conan orders the options, while allowing a list of values will change the ``package_id`` for every different order of the values, even if the semantics are the same.

Lets have a look and think about the possibility.

**Comment by czoido** [comment]
In my personal opinion, although I agree with @uilianries that it would be a nice feature that would improve some recipes I also think adding types support for Options would be too much increase in complexity (for all the reasons already mentioned) to just save some lines of code in a small percentage of recipes... so I would opt to not implement this until there's a significant amount of recipes that need this.

**Comment by czoido** [comment]
I'm closing this as it looks that in the end we all agree on not implementing.
