### ISSUE TITLE
[question] Moving conanbuildinfo_multi.* files to another directory

### ISSUE THREAD

**Issue by KingKiller100** [conan-io/conan#12708]
Conan Version: 1.55.0

Hi guys,

I've read through the documents but I'm struggling to find the answer I'm looking for. 

I have a C++ project using visual studio multi pros generator. I also use the msbuild deps and toolchains. Using the documentation about the layout() stage, I have tried to move the generated files into a subdirectory to keep the folder tidy whilst I'm working on the project. I have noticed that no matter what I try, the buildinfo.props files are always generated in the root folder, even though the rest of the generated deps and toolchain files all go to my subfolder. I'm perplexed if this is an intentional feature of conan or not.

Please let me know what I am doing wrong or if what I want is not possible?

Snippet of my conanfile.py below of how I attempt to change the directory of the generated files

```python
def layout(self):
		self.folders.root = "../.."
		self.folders.subprojects = f"build/{self.name}"
		self.folders.build = f"build/{self.name}"
		self.folders.generators = f"build/{self.name}/generated"
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @KingKiller100 

Quick observation about:

> I have a C++ project using visual studio multi pros generator. 

If you are using the ``MSBuildDeps`` and ``MSBuildToolchain`` generators (recommended), you shouldn't be using the ``visual_studio[_multi]``, ones they are mutually exclusive. Make sure that you don't import ``from conans`` but ``from conan.tools.microsoft``, including the ``MSBuild`` wrapper.

Only the files from the new generators follow the ``layout()``, legacy generators don't. Please try that and let us know.

**Comment by KingKiller100** [comment]
Okay, I will update my packages to utilize the new generators.

Cheers
