### ISSUE TITLE
[bug] autotools.configure() uses --host and --build when cross-compiling

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#12705]
https://github.com/conan-io/conan/blob/d23c1b4631a297112d67ed2e6adb3a961b58d2c6/conan/tools/gnu/autotoolstoolchain.py#L188

```
        for flag, var in (("host", self._host), ("build", self._build), ("target", self._target)):
            if var and flag not in user_args_str:
                configure_args.append('--{}={}'.format(flag, var))
```

The old conans autotools_environment.py had parameters to set `build=False` host=False`, to prevent the configure script from being called with --host and --build.
That seems like a useful thing for one problematic recipe: libvpx
It has a custom configure script that does not handle --host and --build.

One way to workaround this is to patch the script so it accepts and ignores these parameters.
This sounds fragile.

The other way is to generate my own call to the configure script.
This seems appropriate and simpler than adding more cruft to the conan core.
https://github.com/conan-io/conan-center-index/pull/13799

So, I thought I should raise this to see what you guys thought.

**Comment by SpaceIm** [comment]
related to https://github.com/conan-io/conan/issues/12546

**Comment by franramirez688** [comment]
Hi @paulharris @SpaceIm 

Yeah, good point! I opened a PR some time ago that added those parameters at `__init__()` time so I think you could easily override/prune those ones whenever you want. Have a look at https://github.com/conan-io/conan/pull/12645 
Could it do the trick? Or would you need anything else?

**Comment by paulharris** [comment]
Looks ok to me, I'm still new to the conan codebase,
so I'd have to scan through the args and remove (or only keep) the items that start with --host= and --target=

Seems logical to me ... :)  Might be nice to have a "remove_starting_with()" method to make that simple.
I suppose the only further problem is if AutotoolsToolChain decides to add more parameters that aren't supported, that would retrospectively break the recipe.  But still nicer than having to craft the run() call in the recipe.

**Comment by franramirez688** [comment]
Yes, I think it could be reasonable to have a little helper to prune those arguments. Indeed, your comment is related to @SpaceIm's one https://github.com/conan-io/conan/pull/12645#issuecomment-1350801061

Let me propose something in that PR.

**Comment by franramirez688** [comment]
@paulharris 

Only to clarify the issue's title, it says _always_, but it's only happening when `cross-compiling`, isn't it?

**Comment by franramirez688** [comment]
I have proposed something like this in my previously mentioned PR:

```python
at = AutotoolsToolchain(self)
# Pruning values if None is passed as a flag value
at.update_configure_args({"--build": None, "--host": None})
```

**EDITED**: It was a dictionary in the end.

**Comment by paulharris** [comment]
I like it :)  but the first one ... if you only want to prune host, then if you don't specify 'build' then it would call with build=None due to default arguments?
ie `at.update_configure_args( host=None )` would also prune build ?

**Comment by franramirez688** [comment]
> I like it :) but the first one ... if you only want to prune host, then if you don't specify 'build' then it would call with build=None due to default arguments? ie `at.update_configure_args( host=None )` would also prune build ?

Not at all. You pass only the arguments that you want to change, the rest of them are unaffected.
For instance:

```python
at = AutotoolsToolchain(self)
# at.configure_args -> ['--host=wasm32-local-emscripten', '--build=x86_64-linux-gnu', '--target=aarch64-linux-android']
at.update_configure_args({"--host": None, "--target": "my_triplet"})
# configure_args -> ['--build=x86_64-linux-gnu', '--target=my_triplet']
```

EDITED: It was a dictionary in the end.

**Comment by franramirez688** [comment]
Closed by https://github.com/conan-io/conan/pull/12884

Finally, it'll be something like this:

```python
at = AutotoolsToolchain(self)
at.update_configure_args({"--build": None,   # remove --build flag
                          "--host": "whatever"  # update existing --host one
})
```
