### ISSUE TITLE
[bug] conan get doesn't produce same recipe as in remote one

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#12716]
### Environment details

* Operating System+version: ubuntu 22.04
* Compiler+version: clang 14.0
* Conan version: 1.55
* Python version: 3.10.7

### Steps to reproduce

I'm using openscenegraph recepie, but it works on other:

1. conan export conanfile.py openscenegraph/3.4.2@
2. conan get openscenegraph/3.4.2@ --raw > /tmp/conanfile.py
3. diff /tmp/conanfile.py conanfile.py
```
545d544
<
```
If revisions enabled, then the conan will calculate different hash from original recipe hash.

**Comment by memsharded** [comment]
Hi @mshaposhnikov-elvees 

Thanks for reporting.
The ``conan get`` command was never envisioned as a way of actually retrieving exact files, but just a convenient way to display files for users. So it happens that the printing is using ``writeln`` appending an extra LF

I have proposed a fix in https://github.com/conan-io/conan/pull/12717, but please be aware, better dont rely on ``conan get`` for this purpose, the ``conan get`` command is actually being removed in Conan 2.0. It will be replaced by a command that returns the folders in which files are located in the cache
