### ISSUE TITLE
[question] `conf_info` and `test_requires`

### ISSUE THREAD

**Issue by mattyclarkson** [conan-io/conan#12710]
### What is your question?

I have a system root package that does the following:

```py
    def package_info(self) -> None:
        self.conf_info.define("tools.build:sysroot", f"{self.package_path}")
```

I want to test that this is working, so use the following in the corresponding `test_package/conanfile.py`:

```py
    def build_requirements(self) -> None:
        assert self.tested_reference_str is not None
        self.test_requires(self.tested_reference_str)
```

However, the `tools.build:sysroot` is not applied to the configuration for my test package.

I cannot therefore test the package in the way it will be used.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mattyclarkson 

``test_requires`` are packages that live in the "host" context, they will have the same profile, settings, etc than the final application, and if we are running them, we would be running them in the host context. The only difference with normal ``requires`` is that they don't need to be released with our application, and that they do not propagate to downstream consumers.

Something containing a ``sysroot``, seems that is more like a ``tool_requires``, not a ``test_requires``, in the same way a compiler is a ``tool_require`` (and often sysroots come together with the compiler).

Also, the default propagation of ``conf_info`` to consumers ``conf`` only happen from first level ``tool_requires``, other relations need to navigate the ``self.dependencies....conf_info`` explicitly to get those values.

Have you considered doing that as a ``tool_requires``?

**Comment by mattyclarkson** [comment]
Understood. I was misinterpreting the documentation, thanks for the helpful clarification.

**Comment by mattyclarkson** [comment]
Follow-up question: using `tool_requires` will put the `sysroot` package into the build context.

However, the build of the sysroot context requires packages in the host context (i.e. `glibc`/`linux-headers`).

Adding this as a `self.requires` within the `sysroot` package with add them to the graph in the build context but I need them in the host context.

Essentially, I need the following:

```
def build_requirements(self) -> None:
    self.host_requires("glibc/{self.settings_target.libc.version}")
    self.host_requires("linux-headers/{self.settings_target.os.version}")

def package(self) -> None:
    # copy over the `glibc`/`linux-headers` host packages
```

`host_requires` doesn't exist but `build_requires(..., force_host_context=True)` does.

`force_host_context` is being removed in Conan 2.

How do I add a build requirement that is built in the host context?

**Comment by mattyclarkson** [comment]
Seems like `test_requires` _should_ do this:

```
def build_requirements(self) -> None:
    self.test_requires("glibc/{self.settings_target.libc.version}")
    self.test_requires("linux-headers/{self.settings_target.os.version}")

def package(self) -> None:
    # copy over the `glibc`/`linux-headers` host packages
```

However, the build of `glibc`/`linux-headers` still fail `assert self.context == "host"`.

**Comment by mattyclarkson** [comment]
@memsharded I've found the problem in the `graph_builder.py` and fixed it up in #12715

We are not respecting the `force_host_context` that `test_requires` creates.

**Comment by memsharded** [comment]
> However, the build of the sysroot context requires packages in the host context (i.e. glibc/linux-headers).

The view of Conan is that such ``sysroot`` package with its binaries, headers, etc is designed and compiled to "run" in your build machine, not in your host machine. Your host machine will already contain such sysroot, won't it? So the ``sysroot`` files are needed there mostly at compile time, but they are not part of your product.

The toolchain case, containing compilers plus other files like headers, libs, sysroot, is a special case that lies in between the build-requires/tool-requires and the regular requires. Based on the most common use cases, it was decided that the best way to handle those would be via ``tool_requires/build_requires``, even if they contain some binaries that are compiled for the "host" context. 

Probably the important bit is that while building the "toolchain`` package itself, the "host" context becomes for that particular package build the "target" context, and there is a ``self.settings_target`` field that contains that information and that can be leveraged to build such sysroot. Conan 2.0 will even make possible to make this ``self.settings_target`` part of the ``package_id``.

**Comment by mattyclarkson** [comment]
I agree that the `sysroot` should be compiled for the `host` to run on the `build` machine.

I understand that at build time the `sysroot` package `host` becomes the `target`.

This requires that I build the linux headers, glibc, etc all within that recipe.

We went a slightly alternative root, we split up the constituent parts of the sysroot building into smaller, well defined, concise packages.

The hope was to generate `linux-headers`, `glibc-bootstrap-headers`, `glibc` in separate packages and pull them all together via the Conan graph.

The `sysroot` package just requires the individual packages and pulls the relevant parts into it's own package at build time.

This works perfectly if I use the `sysroot` package as a `host` package because all the dependencies get built for the target.

Switching to including the `sysroot` package as `tool_requires` (which is totally the correct way to do it) means that the nested `linux-headers`, `glibc` get built for the build machine not the target machine.

It seems there is no mechanism in Conan to get a host package once you're in the build context, either from within `requirements`/`build_requirements`.

Ideally, I would be able to do the following in the `sysroot` package:

```py
def build_requirements(self) -> None:
    self.host_requires("glibc/{self.settings_target.libc.version}")
    self.host_requires("linux-headers/{self.settings_target.os.version}")
```

Then I can keep the benefit of concise, individual packages and build them up in to a sysroot package.

Aside: we build the compiler separately, it is not part of the sysroot, we can then use modern compilers and target older system roots.

**Comment by mattyclarkson** [comment]
I would be happy to contribute that API, if the project would accept that concept.
