### ISSUE TITLE
[bug] AssertionError: export_folder / export_sources_folder is None in package()

### ISSUE THREAD

**Issue by Chnossos** [conan-io/conan#12713]
### Environment details

* Operating System+version: **Fedora 33**
* Compiler+version: **GCC 10**
* Conan version: `1.55.0`
* Python version: `3.9.9`

### Steps to reproduce

I want to create an zip archive during package(). In this archive, I want to add a script I've exported using `exports = "file.py"` (or `exports_sources = "file.py"`), but inside `package(self)` both `self.export_folder` and `self.export_sources_folder` are `None`, so I cannot get my file back.

1. Export a file that will not get copied during build, like a `.py` script
2. Try to copy it from the `package(self)` method execution like so:
   ```python
   # Either...
   exports = "file.py"
   copy(self, "file.py", self.export_path, self.package_path)
   # ...or
   exports_sources = "file.py"
   copy(self, "file.py", self.export_sources_path, self.package_path)
   ```

### Logs

```
        AssertionError: `export_folder` is `None`
```

Or

```
        AssertionError: `export_sources_folder` is `None`
```

**Comment by memsharded** [comment]
Hi @Chnossos 

This is expected. The ``exports`` is an abstraction that works only on the ``export`` stage. But the necessary sources (``exports_sources``) are then copied to the ``source`` folder. This is the folder that should be referenced in the ``package()`` method, not the exports ones. 

If something is an ``export`` only, that means that such a file is part of the recipe, but never part of the package, so this should and won't be packaged. If you want something to be packaged, it has to be at least part of the ``export_sources``. This is the folder that should be referenced in the ``package()`` method, not the exports ones. 

Please try using the ``self.source_folder`` instead and let us know.

**Comment by Chnossos** [comment]
Hi @memsharded

Thank you for the quick answer. I first looked at the `export` and `export_sources` folder because I had a strange behavior where my file was in `export_sources` folder but didn't get moved to `source` folder, so I thought I had to get it from there.

Removing the data folder with `conan remove -f <project>` then using `self.source_folder` did the trick, thank you.

**Comment by memsharded** [comment]
> Removing the data folder with conan remove -f <project> then using self.source_folder did the trick, thank you.

Great, thanks for telling!
