### ISSUE TITLE
[question] Conan equivlent of dotnet's PackageReference?

### ISSUE THREAD

**Issue by AshleighAdams** [conan-io/conan#12714]
### What is your question?

In dotnet land, a NuGet reference can be added by both package name and version, or a path to the csproj like so:

```xml
  <ItemGroup>
    <ProjectReference Include="..\Veldrid\Veldrid.csproj" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.4" />
  </ItemGroup>
```

This allows multiple packages within a single repo, which then from outside, resolves to the package name and version it was at the time the nuget was built:

https://www.nuget.org/packages/Veldrid.ImageSharp/4.9.0-beta2 (click on Dependencies tab)

Is there a Conan equivalent or recomended way to emulate this behavior?

I know the following also isn't supported, but it would be nice if Conan had something just as simple and powerful:

```py
	def requirements(self):
		self.requires("boost/1.80.0", private=True)
		self.requires("../other-pkg/conanfile.py", private=True)
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @AshleighAdams 

In Conan there is no way to directly reference another conanfile.py by name, it follows instead the Python ``pip`` "editable" mode.
You keep the reference as ``pkg/vesrsion``, and in your folder containing that package you type: ``conan editable add . pkg/version``.

You can read more about editables in: https://docs.conan.io/en/latest/developing_packages/editable_packages.html, a couple of notes:

- The new ``layout()`` method is necessary
- They work mostly with the new integrations, like ``CMakeToolchain``, but not with the legacy like ``cmake`` or ``cmake_find_package``

You can see a live demo of it, and how multiple packages in editable mode can be added to VS IDE in https://youtu.be/VzUJQw89U7o?t=2770. Conan 2.X will try to further automate the manual steps, but at the moment it is recommended to not use the Conan 1.X ``workspace`` feature, as it is deprecated.

**Comment by AshleighAdams** [comment]
Hey, sorry if I wasn't clear, I'm not neccissarilly talking about editable type of workflows, but rather supporting multiple packages from a single repository, where it acts as if the above sample were to be replaced with this instead upon being exported:

```py
	def requirements(self):
		self.requires("boost/1.80.0", private=True)
		self.requires("other-pkg/[^1.2.3]", private=True)
```

Where `other-pkg/1.2.3` may be obtained from `../other-pkg/conanfile.py`'s computed name and version and so on.

**Comment by memsharded** [comment]
No prob, let me clarify a few concepts:

- The unit of work for conan is the "package", defined by one ``conanfile.py``. There is not such a concept of source repository, and packages can be create from code that is not even in  git repo (see the ``conan new hello/0.1 -m=cmake_lib && conan create .`` that will create a Conan package without a git repo)
- It doesn't matter if the packages are in the same git repository or in multiple different git repositories, for Conan they are multiple sibling folders each one with a ``conanfile.py`` inside.
- Until a ``conanfile.py`` and its associated files are exported into the Conan cache (which happens with the ``conan export`` or ``conan create`` commands), that ``conanfile.py`` is not a Conan package, and Conan has no mechanism to know about it
- The other possible way to let Conan be aware that in a certain user folder there is a Conan package is explicitly telling it with the ``conan editable`` command. Using it allows Conan to reference that package from that folder.
- The ``workspace`` feature, is the thing that allowed to tie together multiple editable projects into a single "workspace" meta-project, without needing to go one by one calling the ``conan editable`` command. This command exists in 1.X, but it was not  very mature and not enough flexible to satisfy many users needs, so we decided to drop it. 
- At the moment the recommended way to setup a workspace would be a small script that calls ``conan editable`` for the adequate folders. After Conan 2.0 is released, at some point we will resume work on the workspace feature to hopefully bring it back in a better way to 2.X


As a side note, please be aware that ``private`` dependencies are not very encouraged in Conan 1.X, and they probably should only be used in exceptional situations.

**Comment by memsharded** [comment]
If there is no further question, I think we can close this issue, please re-open or submit new issues for further questions.
For tracking progress (future, 2.X roadmap) about the workspaces for Conan 2, please track this ticket: https://github.com/conan-io/conan/issues/12466 Thanks for the feedback!
