### ISSUE TITLE
[question] cmake_find_package generator puts Find<Package>.cmake file build/Release directory

### ISSUE THREAD

**Issue by r3use** [conan-io/conan#12725]
### What is your question?

Hi!

I'm trying to package some libraries using conan 1.55.0 under Linux. The libraries already exist and use CMake as their build system and are consuming their dependencies using find_package. So I set up different repositories for the conan recipes and use the cmake_find_package generator.

When building a library having a dependency, I get the following error.

`CMake Error at CMakeLists.txt:7 (find_package):
  By not providing "FindLibraries.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Libraries", but CMake did not find one.`

Inspecting the build directory, I see that FindLibraries exists, but is located in build/Release instead of build/generators, which I think is causing the issue.

Any idea on what could cause this?

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by r3use** [comment]
I did some tests today and I get the same error when building the example features/editable/cmake/hello from https://github.com/conan-io/examples.

Attached output of 'cmake .. --debug-find' and tree of the build directory.

[cmake_out.zip](https://github.com/conan-io/conan/files/10253391/cmake_out.zip)
[tree_out.txt](https://github.com/conan-io/conan/files/10253392/tree_out.txt)

**Comment by r3use** [comment]
I figured it out.

I had to use the CMakeDeps generator to generate the dependencies. After that it worked fine.

**Comment by memsharded** [comment]
Hi @r3use 

I am glad that you found out the solution, sorry I couldn't respond earlier to save you some time.

Yes, exactly ``CMakeDeps`` is the new generator that is the modern one necessary to adopt in Conan 1.X to be 2.0 ready, and the one that we have been maintaining and putting our dev efforts.

In general, the generators and tools you want to use in your recipes are the ones in https://docs.conan.io/en/latest/reference/conanfile/tools.html, not others, that is, all your imports should be ``from conan.xxxx``, not ``from conans``. You can also read https://docs.conan.io/en/latest/conan_v2.html to see many other tips to use the new tools and not legacy ones.
