### ISSUE TITLE
[bug] `fix_apple_shared_install_name()` fails if there is a subfolder in bin folder

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12727]
### Environment details

* Operating System+version: macOS Monterey
* Compiler+version: apple-clang 14
* Conan version: 1.55.0
* Python version: 3.10.9

### Steps to reproduce

build a recipe creating a subfolder in bin folder & calling fix_apple_shared_install_name() in package()

### Logs

```
ERROR: xapian-core/1.4.19: Error in package() method, line 134
	fix_apple_shared_install_name(self)
	CalledProcessErrorWithStderr: Command 'otool -hv /Users/spaceim/.conan/data/xapian-core/1.4.19/_/_/package/fecdf3b9eb7fa1cc93253eb65f840989ddd93cd3/bin/share' returned non-zero exit status 1.
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't map file: /Users/spaceim/.conan/data/xapian-core/1.4.19/_/_/package/fecdf3b9eb7fa1cc93253eb65f840989ddd93cd3/bin/share (Invalid argument)
```

**Comment by AbrilRBS** [comment]
Hi! Nice catch! We've now identified the issue and have submitted a fix in the linked PR. Thanks for taking the time to open the report :)
