### ISSUE TITLE
Conan does not set define `CMAKE_SYSTEM_VERSION` when "os.api_level" specified

### ISSUE THREAD

**Issue by KindDragon** [conan-io/conan#1272]

**Comment by Soccertrash** [comment]
Any solution yet? I've run in the same issue.

**Comment by lasote** [comment]
Hi, sorry for not answering this issue, we missed it. You can adjust it by setting `CONAN_CMAKE_SYSTEM_VERSION`. 
You are right, for Android it should be adjusted to the api_level, so we will add this to the 1.4 milestone.

reference: https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android
