### ISSUE TITLE
[bug] Cannot access version of components with  `conanfile.dependencies`: '_NewComponent' object has no attribute 'version'

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12728]
### Environment details

* Operating System+version: macOS Monterey
* Compiler+version: apple-clang 14
* Conan version: 1.55.0
* Python version: 3.10.9

### Steps to reproduce

In a recipe with a dependency having components, try to get version of a component: `self.dependencies[deps].cpp_info.components[component].version` (I've also tried `self.dependencies[deps].cpp_info.components[component].ref.version`).

opencv recipe needs to access custom versions of ffmpeg components. In conan v1 its `self.deps_cpp_info["ffmpeg"].components[component].version` and it works.

### Logs

```
	ffmpeg_component_version = self.dependencies["ffmpeg"].cpp_info.components[component].version
	AttributeError: '_NewComponent' object has no attribute 'version'
```

**Comment by memsharded** [comment]
Hi @SpaceIm 

Thanks for your report. The new modeling from dependencies will not have a explicit version for components as attributes. All the other things not modeled directly with the current existing attributes and consumed by the built-in generators, can be modeled as properties, with ``.set_property()`` like ``cmake_target_name`` and others.

``PkgConfigDeps`` is already consuming a ``component_version`` property, so I guess this is the property to be defined.

**Comment by SpaceIm** [comment]
Interesting. So conan-center should set `component_version` property of each `ffmpeg` component first, then `opencv` could query version of each component with `self.dependencies["ffmpeg"].cpp_info.components[component].get_property("component_version")`?

On a related topic, I'm also wondering if this is not a property `CMakeDeps` could listen for https://github.com/conan-io/conan/issues/12726.
