### ISSUE TITLE
[question] Is it possible to customize lib version in CMake config file generated by `CMakeDeps`?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12726]
### What is your question?

In `vulkan-headers` recipe of conan-center, version in CMake config file generated by CMakeDeps must be "sanitized" to really follow upsteam CMake config file content (always `x.y.z` while we may have "sdk version" like `1.3.236.0` in conan-center). It's important because build system of a downstream recipe (`vulkan-validationlayers`) relies on this version in CMake config file to inject this value into a manifest file. If this value doesn't exactly follow this `x.y.z` convention, it leads to an illformed manifest file which will break logic of another library at runtime (`Vulkan-Loader`) when it tries to find validation layers.
see https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4973

So is it possible to change this version in `package_info()`? Something like this in `vulkan-headers` recipe for example:

```python
def package_info():
    vk_version = Version(self.version)
    self.cpp_info.set_property("cmakedeps_version", f"{vk_version.major}.{vk_version.minor}.{vk_version.patch}")
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @SpaceIm 

There is nothing in the ``cpp_info`` for this very specific need. Also, it doesn't look right to force this from one package to all its consumers, as some might want or need to use the full package version specification. If the consumers like ``vulkan-validationlayers`` don't want to use the full package version they can use a different one. I guess this might be possible to do a ``replace`` in ``generate()`` after the ``CMakeDeps.generate()``

**Comment by SpaceIm** [comment]
> Also, it doesn't look right to force this from one package to all its consumers, as some might want or need to use the full package version specification

I though that the goal of `CMakeDeps` was to properly emulate upstream CMakeLists, and if it fails in this task it looks wrong to me. Recipe always know better than consumers what should be the content of CMake config or pkgconfig files.

> I guess this might be possible to do a replace in generate() after the CMakeDeps.generate()

It's fragile and it means that we have to patch forever. Actually it took me quite a lot of time to understand this bug (because interaction between 3 libraries are involved, and the final consequence is seen at runtime), and find that it was coming from emulation of vulkan-headers config file by CMakeDeps.

Why PkgConfigDeps has this feature and CMakeDeps should not have it?

**Comment by memsharded** [comment]
This was solved some time ago with property ``system_package_version`` or ``package_version``.
