### ISSUE TITLE
[bug] AutotoolsToolchain does not call vcvars when compiler is Visual Studio 2012

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#12739]
### Environment details

* Operating System+version: Windows
* Compiler+version: Visual C++ from Visual Studio 2012
* Conan version: 1.55

### Steps to reproduce

May need further investigation, but it appears recipes that use the new `AutotoolsToolchain` integration do not end up loading vcvars at all when the compiler is from Visual Studio 2012.

Note that this may be expected - as per https://github.com/conan-io/tribe/blob/main/design/032-msvc_support.md, for VS 2012 only CMake integrations are covered. However we may be able to improve the experience (e.g. point the user to invoke the conan commands from within a VS shell).

### Logs

`autotools.configure()` inside a `build()` method will fail with an error pointing to look at `config.log`, which shows that `cl` cannot be located in the current environment.

**Comment by memsharded** [comment]
Closing this ticket as not planned (support for VS 2012) at the moment.
