### ISSUE TITLE
[feature] Explicit errors with CLI `conan graph info`

### ISSUE THREAD

**Issue by lukasberbuer** [conan-io/conan#12735]
### What is your suggestion?

Errors with `conan graph info` are hidden in the stderr output, e.g.:
```
Graph error
    Package 'libiconv/1.17' not resolved: libiconv/1.17: Cannot load recipe.
Error loading conanfile at 'C:\Users\Lukas\.conan2\p\41879da388a50bdc\e\conanfile.py': Unable to load conanfile in C:\Users\Lukas\.conan2\p\41879da388a50bdc\e\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Lukas\.conan2\p\41879da388a50bdc\e\conanfile.py", line 18, in <module>
    from conans.tools import get_gnu_triplet
ModuleNotFoundError: No module named 'conans.tools'
```

The exit code is `0` and implies success. Why isn't the behaviour with `allow_error=False` ([see code](https://github.com/conan-io/conan/blob/develop2/conan/cli/commands/graph.py#L147)) default? This would propagate the exceptions -> exit code `1`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lukasberbuer 

The idea of the new ``conan graph info`` in 2.0 is that it is resilient to graph errors, so it is easier to investigate when something is broken in a large dependency graph. The intention is that it is possible to use the ``html`` formatter, for example, to print the graph, and it will show in red the broken packages, which might really help to debug situations with hundreds (or thousands, a number that some of our users are already approaching) of packages.

It is true that not all errors are equal, and a recipe error is probably not the same as a conflict error between versions. Maybe something in between, like having a clearer error summary at the end of the command, but still not raising, so it allows to print the html? Or maybe raising after the html is saved?

**Comment by memsharded** [comment]
Potential improvement in https://github.com/conan-io/conan/pull/12737

**Comment by lukasberbuer** [comment]
Hi @memsharded

Thank you for the explanation. I just tested your solution #12737 and it fits my expectations perfectly. 🙏
