### ISSUE TITLE
[question] `build_requires` in `conanfile.txt` deprecated? (v2)

### ISSUE THREAD

**Issue by lukasberbuer** [conan-io/conan#12731]
### What is your question?

Conan v2 gives me `ConfigParser: Unrecognized field 'build_requires'` for `conan graph info conanfile.txt`.
A `conanfile.py` with `build_requires` seems to work.

Is the `build_requires` section deprecated in favor of `tool_requires` for v2?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lukasberbuer 

Yes, please use ``[tool_requires]`` in ``conanfile.txt`` and ``self.tool_requires("...")`` in ``conanfile.py`` (the method ``build_requirements()`` was not renamed, but there are other subtle details. We might try to rename it too.

``[tool_requires]`` is also already available in Conan 1.X, so you can use it already there too.

**Comment by lukasberbuer** [comment]
Thank you for the fast response @memsharded! 👍
