### ISSUE TITLE
[feature] Non-hidden conan dir

### ISSUE THREAD

**Issue by ulzu** [conan-io/conan#12740]
### What is your suggestion?

Hi. I want to put conan cache dir into a custom location which it would use _without_ creating a hidden `.conan` dir on top of it.
Instead of `CONAN_USER_HOME` env variable, let me have `CONAN_CACHE_PATH` or similar.

Please do not force users to use external file management conventions. If I wanted to hide it, I can put the dot in, myself.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @plaukiu 

Thanks very much for your suggestion.
This has already been implemented in 2.0. The CONAN_HOME env-var will point directly to the cache, without creating an extra ``.conan`` folder. In 1.X it will not be possible as it would be breaking behavior.

**Comment by memsharded** [comment]
Good, I think this can be closed now as implemented and released in the betas, testing welcome!
