### ISSUE TITLE
[question] No packages matching, but it exists in the remote.

### ISSUE THREAD

**Issue by dongdongkuang123** [conan-io/conan#12749]
### How to ensure that user information is always valid?

In my ubuntu20.04 docker

```
root@xxx:~/workspace/apps# conan search "ph_bind*" -r=mycompany
There are no packages matching the 'ph_bind*' pattern
```
When login again, packages is matching.
```
root@xxx:~/workspace/apps# conan user -p password -r mycompany username
root@xxx:~/workspace/apps# conan search "ph_bind*" -r=mycompany
ph_bind/0.0.4@xxxx/stable
ph_bind/0.0.5@xxxx/stable
ph_bind/1.0.0@xxxx/stable
ph_bind/1.0.1@xxxx/stable
ph_bind/1.0.2@xxxx/stable
ph_bind/1.0.3@xxxx/stable
ph_bind/1.0.4@xxxx/stable
```
 In ubuntu20.04 DockerFile, use `conan user -p password -r mycompany username --skip-auth` to save user info.
**How to ensure that user information is always valid？Because I find that it recurs every once in a while.**
**I need to set anything up on Artifactory?**
- user
```
root@xxx:~/workspace/apps# conan user
Current user of remote 'mycompany' set to: 'username' [Authenticated]
Current user of remote 'conancenter' set to: 'None' (anonymous)
```
- profile
```
root@xxx:~/workspace/apps# conan profile show default
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
platform=default
[options]
[conf]
[build_requires]
[env]
```
- config
```
root@xxx:~/workspace/apps# cat ~/.conan/conan.conf
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = critical            # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
default_profile = default
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = False               # environment CONAN_SYSREQUIRES_SUDO
request_timeout = 30                  # environment CONAN_REQUEST_TIMEOUT (seconds)
default_package_id_mode = semver_direct_mode # environment CONAN_DEFAULT_PACKAGE_ID_MODE
retry = 2                             # environment CONAN_RETRY
retry_wait = 5                        # environment CONAN_RETRY_WAIT (seconds)
sysrequires_mode = enabled          # environment CONAN_SYSREQUIRES_MODE (allowed modes enabled/verify/disabled)
verbose_traceback = True           # environment CONAN_VERBOSE_TRACEBACK
revisions_enabled = True
cache_no_locks = True               # environment CONAN_CACHE_NO_LOCKS

[storage]
path = ./data

[proxies]

[hooks]
attribute_checker
```
- version
```
root@xxx:~/workspace/apps# conan --version
Conan version 1.54.0
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
> How to ensure that user information is always valid？Because I find that it recurs every once in a while.
I need to set anything up on Artifactory?

This is basically a security thing, and yes, it depends on the server side.
One of the recommended security practices in servers is not showing non-authenticated users the existence or not of resources. So servers will return 404 for those things: "not found" instead of 403 "forbidden" or 401 "not authenticated". This is because in the general case, servers could give access to some packages inside a repo and not to others, so it doesn't make sense to error for anonymous users.

I think you might be able to fully disable anonymous access, and then it will prompt for credentials for ``conan search`` commands if user is not authenticated.

**Comment by dongdongkuang123** [comment]
> In ubuntu20.04 DockerFile, use conan user -p password -r mycompany username --skip-auth to save user info.

Thanks for your reply. Sorry, I can't make it clear enough，Conan user information has been saved in my ubuntu20.04 docker. I can access the conan remote normally and `conan search "ph_bind*" -r=mycompany` successfully.  **_When docker is used normally one month later_**，`conan search , install ...` can not do work. I must be login again, like `conan user -p password -r mycompany username` , then `conan search , install ...` work successful.

Of course, if my docker restarts, I have to log in again, then I can use the `conan search , install ...`. So I'm guessing if there is a login expiration policy.

**Comment by memsharded** [comment]
> Of course, if my docker restarts, I have to log in again, then I can use the conan search , install .... So I'm guessing if there is a login expiration policy.

yes, logins do not last forever. Actually Conan doesn't store the password, it stores a JWT token, that the server will expire from time to time (depending on the server configuration), also for security reasons, and it will be necessary to re-authenticate.

**Comment by dongdongkuang123** [comment]
Thank you very much for your help confirming the answer.
