### ISSUE TITLE
cmake.configure arguments

### ISSUE THREAD

**Issue by MikeRavenelle** [conan-io/conan#12745]
Conan Version: 1.53.0

I am having issues passing arguments into the cmake.configure() method defined at: https://docs.conan.io/en/1.53/reference/build_helpers/cmake.html#configure

I am appending a list of arguments and then passing it into cmake.Configure.

Example:

```
configure_args = []
configure_args.append("-debug" if self.settings.build_type == "Debug" else "-release")
```
**I have tried** 
```
cmake.configure(configure_args)
cmake.configure(self, configure_args)
```
**Result**: TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
```
cmake.configure(args=configure_args)
cmake.configure(self, args=configure_args)
```
**Result**: TypeError: CMake.configure() got an unexpected keyword argument 'args'

I am at a loss of what the configure method wants.

**Comment by memsharded** [comment]
Hi @MikeRavenelle 

Maybe you are reading the legacy helper docs? 
the new ``CMake`` helper (``from conan.tools.cmake import CMake``) doesn't have such arguments. Can you shared your conanfile.py? 

You can read in https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake.html#configure, the new helper contains a ``cli_args`` argument.

**Comment by MikeRavenelle** [comment]
I can't share my conanfile.py at this moment but I tried what you suggested.

My Imports are:

```
import shutil
import pathlib
import conans
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout
```

```
cmake = CMake(self)
cmake.configure(self, cli_args=configure_args)
cmake.build()
```

I get this error when using cli_args.

`TypeError: CMake.configure() got an unexpected keyword argument 'cli_args'`

**Comment by memsharded** [comment]
Oh, I see, you are right, this is the signature, in 1.55:
```python
 def configure(self, variables=None, build_script_folder=None, cli_args=None):
```
I see that you are in 1.53, seems that you need to upgrade to get it, please try that. Thanks!

**Comment by memsharded** [comment]
Closing this ticket as solved, please create new tickets for any further question, thanks.
