### ISSUE TITLE
[feature] Ability for Conan remotes to serve "announcements" to clients

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#12750]
### What is your suggestion?

As a Conan remote maintainer, I would like to be able to serve announcement messages that clients see when they perform operations that connect to the remote. 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Interesting idea, but not planned at the moment, closing.
