### ISSUE TITLE
[question] Editable packages with relative paths

### ISSUE THREAD

**Issue by edwardvandevorst-philips** [conan-io/conan#12758]
### What is your question?

Hi, I have a question about editable packages and layouts. I was looking at the example https://github.com/conan-io/examples.git `features/editable/cmake` and I was wondering how to deal with subdirectories in projects.

Let say be restructured to this:

```
say/components/include/say.h
say/components/src/say.cpp
say/components/CMakeLists.txt (with the project say))
say/CMakeLists.txt (with just add_subdirectory(say))
say/conanfile.py (as before except export_source=components)
```

Without further modifications, the editable mode does not work anymore, because it cannot find the library (which is in a components folder, and header).

So I changed to conanfile.py layout section to

```
    def layout(self):
        cmake_layout(self)
        self.cpp.build.libdirs = ["components"]
        self.cpp.source.includedirs = ["components/include"]
```

And this works. Is this the intended way to make this work?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @edwardvandevorst-philips 

Yes, that is totally correct. The idea is that it is necessary to model and inform the layout() where the headers and libraries are located in your local folder. If adding extra folder structure that results in headers located in different directories, and libraries located in different folders too, it is necessary to model that.

**Comment by edwardvandevorst-philips** [comment]
thanks, very helpful

**Comment by edwardvandevorst-philips** [comment]
@memsharded Might be nice that it could be tested in test_package that the package supports editable mode. Not a showstopper.

**Comment by memsharded** [comment]
> @memsharded Might be nice that it could be tested in test_package that the package supports editable mode. Not a showstopper.

It does in Conan 2.0. You can put a package in ``editable`` mode, do a ``conan create`` over it, and it will be built and tested locally with ``test_package``
