### ISSUE TITLE
[bug] Gstreamer(maybe others) that depends on glib fail to install when -pr:b profile is present

### ISSUE THREAD

**Issue by larshg** [conan-io/conan#12768]
### Environment details

* Operating System+version: Windows 10 
* Compiler+version: Visual studio 2022 17.4
* Conan version: 1.56
* Python version: 3.10

### Steps to reproduce

1. conan install --build missing -pr=default -pr:b=default gstreamer/1.19.2@

I don't have the knowhow yet, to easily strip to minimal recipe.

### Logs

```
Program glib-mkenums mkenums found: NO

source_subfolder\gst\meson.build:206:0: ERROR: Program 'glib-mkenums mkenums' not found or not executable
```

Or see build log from attempt to upgrade to 1.20.4:
https://c3i.jfrog.io/c3i/misc/logs/pr/13537/23-configs/macos-m1-clang/gstreamer/1.20.4//d31ea363b40f110b8d00a09956aa9a1654162a80-build.txt

**Comment by memsharded** [comment]
This could be a recipe question, not a Conan issue, lets bring our ConanCenter experts

**Comment by larshg** [comment]
I can try find another recipe that depends on glib and see if it makes the same error?

**Comment by jcar87** [comment]
Hi @larshg  - looking into this currently. Thanks for providing a link to the logs from Conan Center CI! 
If this happens with other recipes please let us know as well :)

**Comment by uilianries** [comment]
It seems be a component missing in glib package, but first time that someone needs it.

**Comment by larshg** [comment]
https://github.com/conan-io/conan-center-index/issues/14125
This issue mentions the same, so kinda of a dublicate, but the logs shows the error about libpcre2-8, which seems to be solved.

Yeah, its a bit harder than first anticipated, since it needs to use that specific component as well and not just glib 😁 

It works if you omit the -pr:b profile.

**Comment by larshg** [comment]
https://github.com/conan-io/conan-center-index/issues/8023 Mention the same error, but it suddenly just worked (currently trying to install pango, but 1.48.5 failed with meson saying cl.exe could compile a simple program...
Currently trying with 1.50.10.

**Comment by larshg** [comment]
Pango fail to build as well:

Program glib-mkenums mkenums found: NO

source_subfolder\pango\meson.build:87:0: ERROR: Program 'glib-mkenums mkenums' not found or not executable

A full log can be found at C:\Users\glla\.conan\data\pango\1.50.10\_\_\build\64d1c3b6bae8172aaa72bce4b75e8e4e1065954b\build_subfolder\meson-logs\meson-log.txt

Got same error, so it happens for at least two recipes.

**Comment by jcar87** [comment]
Hi @larshg - thanks for following up with the investigation!

The particular component `glib-mkenums` is an executable. While it is currently part of the contents of the `glib` package, the `package_info()` logic is oriented to C++ consumers. The `gstreamer` build scripts are looking for this with the`find_program` rather than via pkg-conf. 

in this instance it looks like `gstreamer` and other consumers in a similar situation, should list glib as both a requirement (for the libraries), and a tool requirement (for the executable it needs at build time).

**Comment by jcar87** [comment]
> Hi @larshg - thanks for following up with the investigation!
> 
> The particular component `glib-mkenums` is an executable. While it is currently part of the contents of the `glib` package, the `package_info()` logic is oriented to C++ consumers. The `gstreamer` build scripts are looking for this with the`find_program` rather than via pkg-conf.
> 
> in this instance it looks like `gstreamer` and other consumers in a similar situation, should list glib as both a requirement (for the libraries), and a tool requirement (for the executable it needs at build time).


Looking into this for a proper fix.

**Comment by ericLemanissier** [comment]
The fix should be to add glib build_requirements of gstreamer. This is needed because gstreamer needs to run some glib tool during its build.
EDIT: woopsie, this exactly what jcar87 wrote in the message above, which I somehow missed, sorry !

**Comment by SpaceIm** [comment]
Trick to avoid glib both in requirements & build requirements in case of native build (to avoid the mess of build requirements versions not overridable, or with 1 profile versions conflicts between requirements & build requirements):

```python
def requirements(self):
    self.requires("glib/...")

def build_requirements(self):
    if hasattr(self, "settings_build") and cross_building(self):
        self.tool_requires("glib/...")

def generate(self):
    if hasattr(self, "settings_build") and cross_building(self):
        VirtualBuildEnv(self).generate()
    else:
        VirtualRunEnv(self).generate(scope="build")
```

**Comment by larshg** [comment]
> Trick to avoid glib both in requirements & build requirements in case of native build (to avoid the mess of build requirements versions not overridable, or with 1 profile versions conflicts between requirements & build requirements):
> 
> ```python
> def requirements(self):
>     self.requires("glib/...")
> 
> def build_requirements(self):
>     if hasattr(self, "settings_build") and cross_building(self):
>         self.tool_requires("glib/...")
> 
> def generate(self):
>     if hasattr(self, "settings_build") and cross_building(self):
>         VirtualBuildEnv(self).generate()
>     else:
>         VirtualRunEnv(self).generate(scope="build")
> ```

Indeed this works

**Comment by larshg** [comment]
Running test fails:
gstreamer/1.20.5 (test package): Running test()
ERROR: gstreamer/1.20.5 (test package): Error in test() method, line 17
        self.run(bin_path, run_environment=True)
        ConanException: Error 3221225781 while executing bin\test_package
        
But I guess we can conclude it was recipe error and the issue could be moved to the conan-center-index repo.

**Comment by larshg** [comment]
After updating with changes from the two other PRs for gstreamer, the test runs succesful.
