### ISSUE TITLE
[dev2][list] Show latest revisions for several recipes/package_ids

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#12766]
```
$ conan list "zlib/1.2.18#:*#"
Local Cache:
  zlib
    zlib/1.2.18#12714b06f016d106937a277a3d6ea272 (2022-12-21 16:58:43 UTC)
      PID: b1d267f77ddd5d10d06d2ecf5a6bc433fbb7eeed (2022-12-21 16:58:44 UTC)
        settings:
          arch=x86_64
          build_type=Release
          compiler=apple-clang
          compiler.cppstd=gnu11
          compiler.libcxx=libc++
          compiler.version=14
          os=Macos
        options:
          fPIC=True
          shared=False
```

Shouldn't it return the last package revision for each package id as we are adding the `#` in the end?

_Originally posted by @czoido in https://github.com/conan-io/conan/issues/12756#issuecomment-1362786553_

--------------------------

Right now, we don't have any way to show all the latest RREV/PREV for all the recipes/package_ids. Would it be interesting to implement it?

Example:

```
conan list zlib/*#* -> shows all the RREVs
conan list zlib/1.2.11 -> shows the latest RREV
conan list zlib/*#(latest) -> should show the latest RREV for each recipe ????
```
If it's ok, the same should be done for PREVs

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/12781
