### ISSUE TITLE
[question] How to generate less generic CMake preset configure & build names?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12763]
### What is your question?

Currently, config & build names set in generated CMakePresets files are too generic, they seem to be based on build_type only.

So let's say I want to work in my IDE which automatically scans CMakeUserPresets.json generated/updated by conan in root folder, to tell me available presets.
Now to setup my dependencies once, I call repeatedly `conan install . -if <build_folder> <specific profile/settings values>` where build folder is specific to a settings (not only build type, I may want to compile with different compilers, so for example each tuple compiler/build type has its specific build folder).
CMakeUserPresets.json is updated to include CMakePresets.json generated by conan in each build folder, but several presets will share the same generic release or debug name, regardless of compiler I've used.

How to customize this name so that it can be based on more settings values?

It's also not very clear from documentation that CMakePresets generated by conan are mostly unusable without a layout (and default cmake_layout creates generic build folders, so it doesn't allow to have multiple build folders specific to build type with a single configuration generator).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi! Thanks for your question, I find it quite interesting.
While I can't offer much help in resolving it, I'm dedicating some of my time to improve the docs where I can,
so I'd be happy if you could point me to specific instances where the docs were unclear, to see if I can do something about them while we wait for someone else to answer your original question

Thanks! :)

**Comment by memsharded** [comment]
Hi!

The default presets follow the same convention as CMake, just differentiate Debug and Release.
Conan provides ``tools.cmake.cmake_layout:build_folder_vars:`` conf, that allows to define which other settings and options become part of the preset, so adding different compilers, compiler versions, shared/static, etc is possible.

**Comment by SpaceIm** [comment]
Thanks, I missed this `tools.cmake.cmake_layout:build_folder_vars`. I'll try to experiment a little bit more with presets. I'm still struggling to setup something working out of the box in a IDE with a simple conanfile.txt, without polluting root folder, and a conan v1 client.

**Comment by memsharded** [comment]
> Thanks, I missed this tools.cmake.cmake_layout:build_folder_vars. I'll try to experiment a little bit more with presets. I'm still struggling to setup something working out of the box in a IDE with a simple conanfile.txt, without polluting root folder, and a conan v1 client.

You might want to add a ``[layout]`` section with ``cmake_layout`` in the ``conanfile.txt`` to avoid polluting the root folder.

**Comment by SpaceIm** [comment]
I've already tried to add cmake_layout to [layout], but with conan v1 client (1.56.0) there are few files created in folder where conan is invoked: conan.lock, conanbuildinfo.txt, conaninfo.txt and graph_info.json into root folder.

Simple example:

conanfile.txt

```ini
[requires]
zlib/1.2.13
[generators]
CMakeToolchain
CMakeDeps
VirtualBuildEnv
[layout]
cmake_layout
```

```
conan install .
```

Moreover it creates a generic `build` folder without build type in the name (and if I try to add build type through `tools.cmake.cmake_layout:build_folder_vars`, it complains that it's already managed), so I don't really understand how to have multiple build folder with different build type while using a Single configuration generator.

**Comment by memsharded** [comment]
CMakeToolchain and CMakeDeps are multi-config by architecture, even if you manage a single config ``cmake_layout`` will still propose the same layout ``build/Release``. If you want another custom behavior, you need to implement your own layout.

**Comment by SpaceIm** [comment]
Oops I was a little bit confused. Now I see the subfolder build_type in build folder, once cmake configuration is executed. So if I understand correctly, I should assume that conan will be able to share in the same generators folder, files generated by different invocation of `conan install -s build_type=...`, without disturbing CMake?
While it may be true for CMakeDeps, I hardly doubt that it works for CMakeToolchain since their content is overridden after each conan invocation with hardcoded paths to bindirs, libdirs, includedirs folders for `CMAKE_LIBRARY_PATH`, `CMAKE_INCLUDE_PATH`, `CMAKE_PROGRAM_PATH`, `CMAKE_PREFIX_PATH`, `CMAKE_MODULE_PATH`.

**Comment by memsharded** [comment]
> While it may be true for CMakeDeps, I hardly doubt that it works for CMakeToolchain since their content is overridden after each conan invocation with hardcoded paths to bindirs, libdirs, includedirs folders for CMAKE_LIBRARY_PATH, CMAKE_INCLUDE_PATH, CMAKE_PROGRAM_PATH, CMAKE_PREFIX_PATH, CMAKE_MODULE_PATH.

All CMake ``find_xxx`` stuff is not multi-config, and doesn't allow generator expressions, so it is single-config. That is a known limitation, and there is nothing that can be done to avoid it, except avoid relying on that as much as possible, as that shouldn't be necessary in most cases.

**Comment by SpaceIm** [comment]
Why conan doesn't create a generator folder per conan settings flavor to not share the same generators folder, so that presets can point to these specific & non-conflicting toolchain, Find module files, conanbuild.sh etc? It would be robust to single & multi config generators, and avoid to call conan again after a switch to a different preset in IDE?

**Comment by memsharded** [comment]
It is already doing that for single-config generators, the toolchain will be specific for "Release" and "Debug", only in multi-config the toolchain will be shared (and suffer the above limitations)

**Comment by SpaceIm** [comment]
Thus, maybe I'm missing something.

 global.conf:

```ini
core:default_profile=default
core:default_build_profile=default
tools.cmake.cmaketoolchain:generator=Ninja
```

conanfile.txt

```ini
[requires]
zlib/1.2.13
[generators]
CMakeToolchain
CMakeDeps
VirtualBuildEnv
[layout]
cmake_layout
```

Install dependencies for Release & Debug:

```
conan install . -s build_type=Release -b missing
conan install . -s build_type=Debug -b missing
```

Resulting layout:

```
build/
  Debug/ (after a CMake configuration of debug Presets)
  generators/
  Release/ (after a CMake configuration of release Presets)
```

`CMakePresets.json` generated by conan in generators folder:

```json
{
    "version": 3,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 15,
        "patch": 0
    },
    "configurePresets": [
        {
            "name": "release",
            "displayName": "'release' config",
            "description": "'release' configure using 'Ninja' generator",
            "generator": "Ninja",
            "cacheVariables": {
                "CMAKE_POLICY_DEFAULT_CMP0091": "NEW",
                "CMAKE_BUILD_TYPE": "Release"
            },
            "toolchainFile": "/Users/spaceim/test_presets/build/generators/conan_toolchain.cmake",
            "binaryDir": "/Users/spaceim/test_presets/build/Release"
        },
        {
            "name": "debug",
            "displayName": "'debug' config",
            "description": "'debug' configure using 'Ninja' generator",
            "generator": "Ninja",
            "cacheVariables": {
                "CMAKE_POLICY_DEFAULT_CMP0091": "NEW",
                "CMAKE_BUILD_TYPE": "Debug"
            },
            "toolchainFile": "/Users/spaceim/test_presets/build/generators/conan_toolchain.cmake",
            "binaryDir": "/Users/spaceim/test_presets/build/Debug"
        }
    ],
    "buildPresets": [
        {
            "name": "release",
            "configurePreset": "release"
        },
        {
            "name": "debug",
            "configurePreset": "debug"
        }
    ],
    "testPresets": []
}
```

Theses presets share the same `conan_toolchain.cmake` whose content depends on the last conan invocation (Debug in this example), even for a single configuration generator like Ninja.

**Comment by memsharded** [comment]
I see, yes, you are right, ``conan_toolchain.cmake`` is always common to both. 
We might want to revisit this, thanks for the feedback.

**Comment by memsharded** [comment]
Update: we changed this in 1.57 already, it was labeled as a bug. The single configuration projects will have a different folder, a different generated CMakePresets and a different generated ``conan_toolchain.cmake``

This fix, together with the functionality of ``tools.cmake.cmake_layout:build_folder_vars``, and the fixes in recent PR https://github.com/conan-io/conan/pull/12925 will mark this issue as closed for 1.58

Thanks again for the feedback!

**Comment by SpaceIm** [comment]
Thanks.

One question: can it break an attempt to patch conan toolchain in a recipe with `os.path.join(self.generators_folder, "conan_toolchain.cmake")` or is there still the guarantee that `self.generators_folder` always reference all generated files for a given settings? `abseil` recipe is doing something like this in conan-center.

**Comment by memsharded** [comment]
``self.generators_folder`` should be correct.

In any case, patching the generated ``conan_toolchain.cmake`` seems an anti-pattern. This would be the approach:
- First check why ``CMakeToolchain`` default is not that. Would this affect all the recipes in ConanCenter, and they will require the same workaround in every ``conanfile.py``? Probably report it. I have checked the implementation of CMakeToolchain and it seems to be doing the right thing.
- If the recipe is an exception and it needs some special customization, use the CMakeToolchain customization points. In this case something like:
```python
def generate(self):
    tc = CMakeToolchain(self)
    tc.blocks["generic_system"].values["cmake_system_processor"] = "myvalue" 
    tc.generate()
```
(Still, do not add this to every recipe in ConanCenter, having to do so sounds not correct)

**Comment by SpaceIm** [comment]
@memsharded overriding a specific value of a a block may not be enough, there is a missing feature to allow injecting arbitrary CMake code at the end (or after a specific block) of `conan_toolchain.cmake`.

For example in `abseil` recipe, we want to set `CMAKE_SYSTEM_PROCESSOR` in case of cross-build only if it is not already defined in conan toolchain. Overriding `cmake_system_processor` value in `generic_system` block is not the same logic (it would override `CMAKE_SYSTEM_PROCESSOR` defined in an hypothetical user toolchain because `generic_system` block comes after `user_toolchain` block).
Actually I realize that conan toolchain will always define a `CMAKE_SYSTEM_PROCESSOR` in case of cross-build, so these logic required with legacy `cmake` generator may be obsolete.
