### ISSUE TITLE
[question] Statical linking to boost using cmake not possible in windows

### ISSUE THREAD

**Issue by 18Lukas18** [conan-io/conan#12788]
## Problem
I am trying to build an application using boost (static link). However I always get the following linking error:
```
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
```
It is worth to mention that I am using the conan CMakeDeps generator, since other cmake generator are not going to be supported in conan 2.0.

## Environment Details
- OS: Microsoft Windows 10 Pro Build 19044
- Compiler: Visual Studio Professional 2022 Release - x86_amd64
- Conan version: 1.54.0
- Python version: 3.10.6

## Steps to reproduce
conanfile.py:
```
from json import tool
from conans import ConanFile, CMake, tools

class BoostConan(ConanFile):
   settings = ["os", "compiler", "build_type", "arch"]
   requires = ["boost/1.80.0"]
   generators = ["CMakeDeps"]
   default_options = {"boost:shared": False}
```

conan profile file msvc_mtd:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.runtime=MTd
compiler.version=17
build_type=Debug
[options]
[build_requires]
[env]
```

conan install command:
```
conan install --update --build=missing .. --profile=../conanProfiles/msvc_mtd
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.24)

set(TARGET_NAME Application)

set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME ON)

list(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}")
find_package(Boost CONFIG REQUIRED)

set(
    SRC_FILES
    src/main.cpp
    src/FileA.cpp
    src/FileB.cpp
    src/FileC.cpp
)
add_executable(${TARGET_NAME} ${SRC_FILES})
target_include_directories(${TARGET_NAME} PUBLIC ./inc)

target_link_libraries(${TARGET_NAME} ${Boost_LIBRARIES})

set_property(TARGET ${TARGET_NAME} PROPERTY CXX_STANDARD 20)
```

## Further information
There is one thing that I cannot understand: when I am trying to output the `target_type` of boost libraries i.e.
```
get_target_property(target_type Boost::log TYPE)
message("target_type: ${target_type}")
```
or 
```
get_target_property(target_type ${Boost_LIBRARIES} TYPE)
message("target_type: ${target_type}")
```
I will get `INTERFACE_LIBRARY`. Actually I would expect the output to be `STATIC_LIBRARY`. Does anyone has an idea to solve to problem I am facing. i am grateful for any help.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @18Lukas18 

Thanks very much for your report.
It seems there is a discrepancy between the VS runtime of your dependencies and your current project VS runtime.
You are using ``compiler.runtime=MTd`` for your dependencies, but it seems there is nothing in your current project to set that value. The profile is used for your dependencies, but it will not be magically injected via dependencies into your current project.

To pass the profile configuration to your current project, including also the location of the dependencies generated .cmake files, the recommended way is to use ``CMakeToolchain`` generator. It will generate a ``conan_toolchain.cmake`` file (you can pass via ``-DCMAKE_TOOLCHAIN_FILE=...``, or the generator also generates ``CMakePresets`` files if you like that and you can use more modern CMake versions).
Please try using that file and let us know.

> I will get INTERFACE_LIBRARY. Actually I would expect the output to be STATIC_LIBRARY. Does anyone has an idea to solve to problem I am facing. i am grateful for any help.

yes, this is expected, as CMakeDeps don't have enough information about the type of the library, it is not that simple to provide it. We are working on improving this, but it is quite complex, so it will take a while.

**Comment by 18Lukas18** [comment]
Hi @memsharded,

thank you very much. I could make a step forward now. I am able to build an .exe (using Boost) and execute it in an environment without conan or boost. 
However if I am trying to build a .lib file (let say MyLib.lib) and link it to an .exe (let say MyApp.exe) I will get linking errors while building MyApp.exe as follows:
```
Error	LNK2019	unresolved external symbol "public: __cdecl boost::log::v2s_mt_nt6::attribute_set::~attribute_set(void)" 
(??1attribute_set@v2s_mt_nt6@log@boost@@QEAA@XZ) referenced in function "public: __cdecl boost::log::v2s_mt_nt6::sources::basic_logger<char,class boost::log::v2s_mt_nt6::sources::severity_channel_logger_mt<enum boost::log::v2s_mt_nt6::trivial::severity_level,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct boost::log::v2s_mt_nt6::sources::multi_thread_model<class boost::log::v2s_mt_nt6::aux::light_rw_mutex> >::~basic_logger<char,class boost::log::v2s_mt_nt6::sources::severity_channel_logger_mt<enum boost::log::v2s_mt_nt6::trivial::severity_level,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct boost::log::v2s_mt_nt6::sources::multi_thread_model<class boost::log::v2s_mt_nt6::aux::light_rw_mutex> >(void)" 
(??1?$basic_logger@DV?$severity_channel_logger_mt@W4severity_level@trivial@v2s_mt_nt6@log@boost@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@sources@v2s_mt_nt6@log@boost@@U?$multi_thread_model@Vlight_rw_mutex@aux@v2s_mt_nt6@log@boost@@@2345@@sources@v2s_mt_nt6@log@boost@@QEAA@XZ)	MyLibTest	C:\dev\TestProjects\MyLibTest\MyLib.lib(LevelLogger.obj)	1	
``` 
Do you have any idea? Maybe it is not possible to link MyLib.lib directly to MyApp.exe and I have to package MyLib.lib using conan?

## Step to reproduce
conanfile.py:
``` 
from json import tool
from conans import ConanFile, CMake, tools

class BoostConan(ConanFile):
   settings = ["os", "compiler", "build_type", "arch"]
   requires = ["boost/1.80.0"]
   generators = ["CMakeDeps", "CMakeToolchain"]
   default_options = {"boost:shared": False}
``` 

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.24)

set(TARGET_NAME Application)

list(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}")
find_package(Boost CONFIG REQUIRED)

set(
    SRC_FILES
    src/FileA.cpp
    src/FileB.cpp
    src/FileC.cpp
)
add_library(${TARGET_NAME} ${SRC_FILES})
target_include_directories(${TARGET_NAME} PUBLIC ./inc)

target_link_libraries(${TARGET_NAME} ${Boost_LIBRARIES})

set_property(TARGET ${TARGET_NAME} PROPERTY CXX_STANDARD 20)
set_property(TARGET ${TARGET_NAME} PROPERTY POSITION_INDEPENDENT_CODE ON)

install(TARGETS ${TARGET_NAME} DESTINATION lib)
```

CMake commands:
```
cd build
cmake ../CMakeLists.txt -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"
cmake --build . --target ALL_BUILD
```

**Comment by memsharded** [comment]
Hi @18Lukas18 again

I think the problem might be this line: ``target_link_libraries(${TARGET_NAME} ${Boost_LIBRARIES})``. 
In general it is recommended to use targets instead of plain libraries, so ``target_link_libraries(... Boost::Boost)`` (or ``boost::boost``, I don't know the casing of the target by heart)

As the system is Windows, it is also important to say the ``cmake --config Release`` to specify which configuration you want to build (and it should match the installed one).

Other question: is the ``boost-log`` the only missing one? are you depending on other linked libraries from boost, but those are not giving linking errors?

It would be good to get the full output of your commands, the ``conan install`` output, the ``cmake`` configure output and the ``cmake`` build output, maybe there are some other hints there about what could be happening.

**Comment by 18Lukas18** [comment]
Hi @memsharded,

I think I ve figured it out. If I build libraries (e.g. MyLib.lib) that has static links to other libraries (e.g. Boost) managed by conan, Boost will not be "stored" inside MyLib.lib. It is more like MyLib.lib has a reference to boost. So if I want to (static) link MyLib.lib to an Application (e.g. App.exe) I have to export MyLib.lib to the conan cache and then use conan to generate cmake config files for building App.exe. 
So in my understanding conan does not support the use case that boost is "stored" inside MyLib.lib. Can you confirm that?

Many many thanks in advance.

**Comment by memsharded** [comment]
> I think I ve figured it out. If I build libraries (e.g. MyLib.lib) that has static links to other libraries (e.g. Boost) managed by conan, Boost will not be "stored" inside MyLib.lib. It is more like MyLib.lib has a reference to boost. So if I want to (static) link MyLib.lib to an Application (e.g. App.exe) I have to export MyLib.lib to the conan cache and then use conan to generate cmake config files for building App.exe.
So in my understanding conan does not support the use case that boost is "stored" inside MyLib.lib. Can you confirm that?

Yes, this is not something particular to Conan, but something general about how static libraries work. Static libraries do not really link at all with other static libraries, they have just   a reference to them, so when linking executables it is totally necessary to have the direct dependencies static libraries and the transitive static libraries. Conan cannot do anything to avoid this, this is intrinsic to the compilation model of static libraries.
It is true that I have seen some very exceptional cases of developers creating a big static library "re-packaging" other static libraries, but that would be probably discouraged as a not great thing by many people.

**Comment by 18Lukas18** [comment]
Hi @memsharded,

thank you for your help. I d like to close this issue since it is solved.
