### ISSUE TITLE
[question] how to copy include folder that is at the same level as src folder

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#12783]
### What is your question?

I have a project that has a layout where i put some public header files in the `include/` folder in project root, so it becomes the same level as `src/`. 
```
.
├── CMakeLists.txt
├── build
├── conanfile.py
├── include
├── src
```
I setup the project and it builds well, but when I try to create packages i got error saying could not find the folder `include/`, e.g,. 
within `~/.conan/data/mypackage/1.0.0.0/_/_/build/d243708b1be465d7e20cd592a7f40a4aa99ae97a/`. So how can I setup my project with conan where the `include` folder is at the same level as the `src` folder?

and the second question, In my `conanfile.py`, i have 
``` python
    def package(self):
        self.copy("*.hpp", src="include", dst="include") # headers are not copied to .../package/hash#/include
        self.copy("*.hpp", dst="include", src="src") # headers are copied to .../package/hash#/include
```
I checked the document and i believe that here `src="include"` implies this `include` folder should be in `src`, which is not the case i have. I feel this is misleading, or maybe i missed something here?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by Chnossos** [comment]
Have you exported the folder as well?

```python
exports_sources = "CMakeLists.txt", "src/*", "include/*"
```

**Comment by memsharded** [comment]
Hi @shelper 

I'd need a bit more information about this:
- A minimal recipe to reproduce
- The commands used to reproduce

Note that many things affect to what you finally get in the package, like the ``layout()``, the ``exports``, the ``build()``, the ``package()``, etc.

Quick hint: ``self.copy()`` is superseded by the new ``from conan.tools.files import copy``, I'd recommend start using the later, please check: https://docs.conan.io/en/latest/conan_v2.html

Also, the layout that you are describing is basically the default one created by the modern template: ``conan new hello/0.1 -m=cmake_lib``. That is a fully operational recipe and code, you can just ``conan create .`` it, and it should work.

**Comment by shelper** [comment]
it works, thanks!
