### ISSUE TITLE
Conan search crash / invalid recipe manifest

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1279]
Conan is crashing on some of my locally cached packages when trying to run `conan info` or `conan search` on them.

I traced it in a debugger, and it is throwing in `FileTreeManifest.loads():71` as it tries to parse a file with these contents:

```
1493992004
conanfile.py: cf9fad4b546fea5943d08e7da7401177
1493992004
conanfile.py: cf9fad4b546fea5943d08e7da7401177
```

Line 71 in 0.22.2 is:  `filename, file_md5 = md5line.split(": ")`
It seems the file is not expected to have two timestamp/MD5 entries.

I don't know how my manifest got that way.  It's only like that for some packages, I think the ones built on our CI server.  Those are built by first doing a `conan remove *` followed by a `conan export...`.

**Comment by tamboril** [comment]
Something went wrong in my local cache.  Removing the offending packages and re-downloading them from Artifactory cleared up the issue.  But I need to figure out what I did that corrupted the manifest file.  It isn't just a second `conan export`; that works fine (and correctly shows an `outdated from recipe: True`).

**Comment by memsharded** [comment]
Yes, it seems that something went crazy and appended a new manifest to the file, instead of overwriting it. Certainly, I'd love to know what happened. I will have a quick look to the codebase to try to figure out, but doesn't look evident at first sight. Please update then if you are able to reproduce, thanks for reporting.

**Comment by memsharded** [comment]
Could concurrency be an issue? Like simultaneously building and downloading from the remote the same package?

**Comment by tamboril** [comment]
I could rule that out, because one of the bad packages is _only_ built on the CI server, and all I ever do locally is consume it.  It's one that I never built locally.

**Comment by tamboril** [comment]
Although...it could be being download twice concurrently.  CLion parallelizes its CMake runs, and my CMakeFiles install conan packages.

**Comment by memsharded** [comment]
That could make sense. I personally don't like too much https://github.com/conan-io/cmake-conan, if it is the thing that you are using, as I much prefer to keep control invoking conan myself, exactly the same I do with git, always in the terminal, I don't like IDE integrations very much.

**Comment by tamboril** [comment]
In my CMake, I'm just running `conan install` using `execute_process()`.  But I think the IDE can run those in parallel when first generating the makefiles, one instance for each configuration (Debug, Release, ..., etc.)

**Comment by tamboril** [comment]
I will try a file lock from CMake (there's a command for that in the language), and see whether it
happens again.

Thanks.

**Comment by memsharded** [comment]
Good, just reopen if it happens again. Thanks!
