### ISSUE TITLE
[bug] flag -std=c++2a is deprecated in gcc 12

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#12794]
### Environment details

* Operating System+version: Linux
* Compiler+version: gcc 12.2
* Conan version: 2.0.0-beta7
* Python version: 3.10

### Steps to reproduce

```python
from conan.tools.build.flags import cppstd_flag
```

(Alternatively try any generator using this, like AutotoolsToolchain or NMakeToolchain)

```
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++
compiler.version=12
os=Linux
```

Results in flag `-std=c++2a` which is according to the documentation is deprecated: https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html#C-Dialect-Options

It should be `-std=c++20` instead.

**Comment by memsharded** [comment]
Thanks for reporting @ytimenkov 

Checking this for 1.57 too. 
Note that ``from conan.tools.build.flags import cppstd_flag`` is not a public documented import, shouldn't be used directly.
