### ISSUE TITLE
[question] CMakeDeps doesn't generate CMake config files for `tool_requires` in single profile mode

### ISSUE THREAD

**Issue by peterazmanov** [conan-io/conan#12790]
### Environment details

* Ubuntu 22.04, 5.15.0-56:
* Conan 1.56 or later
* Python 3.10.6

### Steps to reproduce

1. Run the following test (I placed it in `conans/test/integration/toolchains/cmake/cmakedeps/test_cmakedeps.py`)
``` python
def test_single_profile_tool_requires():
    c = TestClient()
    example = textwrap.dedent("""
        import os
        from conan import ConanFile
        class Example(ConanFile):
            name = "example"
            version = "1.0"
            tool_requires = "game/1.0"
            generators = "CMakeDeps"
            settings = "build_type"
            def build(self):
                assert os.path.exists("game-config.cmake")
            """)
    c.save({"game/conanfile.py": GenConanfile("game", "1.0").with_settings("build_type"),
            "example/conanfile.py": example,
            "example/test_package/conanfile.py": GenConanfile().with_requires("example/1.0")
                                                               .with_test("pass")})
    c.run("create game")
    c.run("create example")

    assert "example/1.0: Package '4024617540c4f240a6a5e8911b0de9ef38a11a72' created" in c.out
```
2. Test fails on assertion inside `build`, expected outcome - test passes as it used to do in versions prior to 1.56.

After https://github.com/conan-io/conan/pull/12675/ conan started to apply `build_context_activated` logic in single profile mode too. Perhaps I don't fully understand separate contexts and this behavior is expected?

### Logs

[TestFailureMessage.log](https://github.com/conan-io/conan/files/10305570/TestFailureMessage.log)

**Comment by memsharded** [comment]
Hi @peterazmanov 

Thanks very much for your report.
However, it seems this is not a bug, this is by design. The ``CMakeDeps`` and all the other modern generators even output a ``WARNING`` saying that it is necessary to use the 2 profiles, and that it will even eventually raise an error if not. The management of ``tool_requires`` is one of those features that will not work without providing both profiles.

**Comment by peterazmanov** [comment]
> The CMakeDeps and all the other modern generators even output a WARNING saying that it is necessary to use the 2 profiles, and that it will even eventually raise an error if not.

Fair enough, thanks )
