### ISSUE TITLE
[question] How can I get Conan to include the current project paths in the build and run environments

### ISSUE THREAD

**Issue by stefanroels** [conan-io/conan#12800]
### What is your question?

I am trying to convert our software to a number of Conan packages. Each package has one or more libraries and one or more executables. I am using traditional makefiles to build our software and I include the 'CONAN_INCLUDE_DIRS' in our makefiles to allow the build to find the headers.

When I generate the package, the paths for all the dependencies are set, but I cannot see the include files for the "local" libraries in our executables. I have been able to hack them into the make system with a custom makefile generator based on the "make" generator.

The next problem I run into is that when I try to run the application (either from the conanfile, using `self.run("bin/run_tests", run_environment=True)` or from the command line (using `source activate_run.sh` before running), the `LD_LIBRARY_PATH` does not contain the path to the locally generated library.

How can I make Conan treat the current package the same way as the dependencies when generating the environment and conanbuildinfo files?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @stefanroels 

Thanks for your report.

The first important feedback is that it seems you are using some of the legacy integrations, and you should be using the modern ones instead from: https://docs.conan.io/en/latest/reference/conanfile/tools.html. 
And you should be having a look to: https://docs.conan.io/en/latest/conan_v2.html

There are helpers like ``conan new hello/0.1 -m=autotools_lib`` that will produce a fully working autotools based recipe and example code.

> When I generate the package, the paths for all the dependencies are set, but I cannot see the include files for the "local" libraries in our executables. I have been able to hack them into the make system with a custom makefile generator based on the "make" generator.

Yes, the ``generate()`` and generators generate include and link information for dependencies only. But Conan is not a build system, so the current "consumer" project, has to be setup as it typically needs to be done for every project when not using Conan. The project include dirs, libraries, dirs, flags, etc, has to be written in the Makefiles or build scripts. 
In general, besides the dependencies information it is also necessary to inject the flags that match the current Conan ``settings``, this might be done with ``AutotoolsToolchain``.

> The next problem I run into is that when I try to run the application (either from the conanfile, using self.run("bin/run_tests", run_environment=True) or from the command line (using source activate_run.sh before running), the LD_LIBRARY_PATH does not contain the path to the locally generated library.

The environment generators also have new modern alternatives, please check the docs here: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html

In a similar way, Conan will not be setting this path, note the typical flow would be:
```bash
$ conan install .   # get dependencies, generate information to locate dependencies
$ . conanbuild.sh  # depending on the system, activate the environment to locate dependencies
$ make ...
```

It might be possible to use the ``generate()`` method, and a custom ``Environment()`` to generate extra environment information to point to local folders, where the libs will be located, but this is not done automatically (many times it might not be necessary, local builds can work fine with rpaths, or other mechanisms)

Please let me know if this helps and if you have any further question.

**Comment by stefanroels** [comment]
Thank you for your reply. I understand the fact that Conan is a tool aimed at managing the dependencies, but I had hoped that it could also set the paths needed for the current project. I will just have to use a custom generator to solve my problems. I have already implemented a custom generator to adjust the conanbuildinfo.mak file, but I will also have to create one for the environment.

I will also have a look at the conan V2, as you suggest.
