### ISSUE TITLE
[bug] self.source_folder has the dot '.' character at the end, leading to an invalid path string

### ISSUE THREAD

**Issue by famastefano** [conan-io/conan#12805]
### Environment details

- Operating System+version: **Windows 10 Pro 19045.2364**
- Conan version: **1.56.0**
- Python version: **3.10.8**

### Steps to reproduce

Just print the attribute, in my case I did it in the `def build(self)` method.
```python
print(f"Source folder: {self.source_folder}")
```

**Comment by memsharded** [comment]
Hi @famastefano 

Yes, it is a ``.``, but I am not sure this is a bug, or that is an invalid path. Everything works fine with this path, I am adding your print in the ``build()`` method of ``conan new hello/0.1 -m=cmake_lib``, it is printing it, and the dot is visible at the end, like ``C:\Users\memsharded\.conan\data\hello\0.1\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\.`` but everything works fine. I have tried several Python path related functions like ``join``, ``makedirs``, etc, and they also seems to work fine with that path.

What error are you seeing on your side?

**Comment by famastefano** [comment]
Hi @memsharded,
hmm, I wrongly used it, so I mistakenly thought it was an error when I made some tests.
Sorry, I'm a beginner with Python as I've never used it before conan :(

Closing as not a bug, sorry :P

**Comment by memsharded** [comment]
> hmm, I wrongly used it, so I mistakenly thought it was an error when I made some tests.
Sorry, I'm a beginner with Python as I've never used it before conan :(

No problem, and don't be afraid or hesitate to open tickets for questions because of not enough Python expertise :)
