### ISSUE TITLE
Having build_requires set conditional options on requirements

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1280]
Summary: `configure(self)` overwrites options from profile during building

My package has a conditional regular dependency on the `runtime=True` option of a compiler package, so that when my package is installed, so will the compiler runtime shared libs.  No problem.

But when I _build_ my package, I need `build_requires` to pull in the `runtime=False` option of the upstream compiler package (i.e. full compiler package).

So in my profile, in the `[options]` section, I set `LocalGcc:runtime=False`, but that setting is overwritten during the build process when `configure(self)` is called, and I set that compiler option to `True`.

I managed to work around it with an environment variable (`BUILD_IN_PROGRESS`) in the profile, 
which I check for in `configure(self)` by retrieving it from `self.env`.

Is there a declarative way to say, "set option unless building"?

Thanks,

John

**Comment by lasote** [comment]
Hi, 
Sorry I don't get it. Could you explain all the package names involved and their relations? LocalGcc is a build require?

**Comment by memsharded** [comment]
Yeah, I think I understood it, let me check:
- You depend on the same package both as a normal ``requires`` and also as a ``build_requires``
- You want to use different options for if, when you are building.

So if this is the case, the issue is that just one set of options is propagated along the dependency graph, and such is evaluated at the graph construction step.

The good news are that actually, the dependency graph for build_requires is isolated from the normal one, so it should be easy to proxy the package for build needs. I would try something like:
- Create a ``LocalGccBuild`` package that requires ``LocalGcc``
- Make that package hardcode the ``LocalGcc:runtime=False`` option.
- Use that package for ``build_requires``

Please tell me if this makes sense.

**Comment by tamboril** [comment]
I'll try it and let you know, but it seems like it would be a diamond graph during the build with conflicting dependencies: the regular dependency on LocalGcc directly with `runtime=True` and a `build_requires` dependency on LocalGcc indirectly with `LocalGcc:runtime=False`.

**Comment by tamboril** [comment]
This only worked on a first-order package, which correctly showed the different requirements for build and non-build.  But a second-order package that depended on the first did not work.

I also tried scopes, but I could not get anything to show up in `self.scopes`.  I tried a `[scopes]` section in the profile I used to build, and also a `--scope foo=bar` on the `conan install` command line, the `self.scopes` was always empty (checked in debugger, too).

So I guess I'm going back to my environment variable solution, since it seems to be able to reach back to second-order dependencies and prevent the option from being overridden.

**Comment by memsharded** [comment]
So the second order package will also have a ``runtime`` option that is not being set? I think it should be possible, as the diamond is not a thing here, they are in fact separate and isolated dependency graphs. Could you please outline a bit further your package layout? Something like:

```
MyProject -(build_require)-> LocalGccBuild -> LocalGcc(runtime=False) -> Other(other option?)
MyProject -(require)-> LocalGcc(runtime=True) -> Other?
```
Thanks!

**Comment by tamboril** [comment]
I just found out that the requirements shown in `conan search`  are not 
necessarily the same as those shown in `conan info`.  The ones output by
`conan info` seem correct.

I will try to sort out the graph among my three situations: building, consuming runtime, 
and consuming normal and report back here.

**Comment by memsharded** [comment]
Yes, ``conan search`` shows the full cache, everything is installed.
``conan info`` shows your dependency graph (build_requires excluded).

**Comment by tamboril** [comment]
Here is what was confusing.  `search` says that package d3dd requires boost:f0b8 and LocalGcc:42d5, but
conan info says that package leatherman:d3dd requires boost:8557 and LocalGcc:31bf.

```
$ conan search leatherman/0.12.1@puppetlabs/external2
    Package_ID: d3dd1b970b6c2c408d5758e48b285e4de54ebf0e
        [options]
            runtime: False
            shared: True
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: gcc
            compiler.version: 6.3
            os: Linux
        [requires]
            Boost/1.61.dv01@boost/external2:f0b8f93238ad9005f11bc335deda02ab7e0a5c2f
            LocalGcc/6.3@gnu/external:42d5dcede3771fe50c02146644066f7f33812d03
        outdated from recipe: False

$ conan info leatherman/0.12.1@puppetlabs/external2

Boost/1.61.dv01@boost/external2
    ID: 85574189bfd43d290591283c30ae424ffd9e0dd3
    BuildID: None
    Remote: None
    URL: https://ms-dv-gh-1.priv.dvtrading.co/dv-core-dev/conan-recipes
    License: Boost Software License
    Updates: Version not checked
    Creation date: 2017-05-11 08:55:31
    Required by:
        leatherman/0.12.1@puppetlabs/external2
    Requires:
        LocalGcc/6.3@gnu/external
LocalGcc/6.3@gnu/external
    ID: 31bf4db1aa3ef29b5d36327b6eb90d6afcd98b09
    BuildID: None
    Remote: (snip)
(snip)
leatherman/0.12.1@puppetlabs/external2
    ID: d3dd1b970b6c2c408d5758e48b285e4de54ebf0e
    BuildID: 936e90ac48127919a7518b67bc766e372ac27328
    Remote: None
    URL: https://ms-dv-gh-1.priv.dvtrading.co/dv-core-dev/conan-recipes
    License: http://www.apache.org/licenses/LICENSE-2.0
    Updates: Version not checked
    Creation date: 2017-05-11 10:16:52
    Required by:
        None
    Requires:
        Boost/1.61.dv01@boost/external2
```

**Comment by memsharded** [comment]
Is the output of  ``conan info`` truncated, or it doesn't show the dependency to ``LocalGcc``? Is the ``LocalGcc`` a ```build_require`` only? I would like to know a bit further of the requirements declaration, the ``package_id()`` (if any). Also there could be a bug with ``build_id()`` maybe?

If you prefer to share in slack, please tell me at info@conan.io and I'll send you an invite.

**Comment by tamboril** [comment]
I think I just tried to get way too clever with my dynamic requirements, making single packages have too different personalities.  I'm overhauling my packages now to eliminate the `runtime` option 
completely, and it's much simpler.  At the end of my dependency chain, I will make a separate "runtime" package that pulls together binaries from all the `build_requires` of its parent "full development" package.

**Comment by memsharded** [comment]
Sounds a good approach, just let us know if you need something from us. Could this issue be closed then? Thanks very much.
