### ISSUE TITLE
conanfile.py self.run("./configure") doesn't work with mingw - msys on Windows

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#1281]
Hi everyone,

I've just noticed that, on Windows, when placing the command `self.run("./configure")` in a conanfile.py and running `conan test_package` in mingw/msys, the error "configure - unrecognised command" is produced. This is the case anyway when using a Windows command line and executing ./configure by hand, even when MinGW has been placed in the path. But ./configure does work on Windows when executed from msys.

**Comment by lasote** [comment]
Hi! 
Have you tried the `tools.run_in_windows_bash_tool`? It will run the command in a bash shell from your MSYS.

http://conanio.readthedocs.io/en/latest/mastering/build.html
http://conanio.readthedocs.io/en/latest/reference/tools.html#run-in-windows-bash-tool

**Comment by memsharded** [comment]
Might be windows issue. You can try also ``self.run(".\configure")``.
If that is the issue, you might want to use something like ``os.sep.join([".", "configure"])``
I think that ``run_in_windows_bash`` does not change the slash, but maybe the bash understand it.

**Comment by dimi309** [comment]
Hi guys,

`self.run(".\configure")` didn't work. `tools.run_in_windows_bash_tool` worked (I really should read the documentation more carefully. Sorry.. 😦 ). Now I have another problem, but I think that this one is not conan related. `Configure` produces the error:

```
configure: error: C compiler cannot create executables
See `config.log' for more details
```
Thanks a lot for your help in any case.

**Comment by memsharded** [comment]
Thanks for telling, no worries :)

**Comment by dimi309** [comment]
Sorry to reopen this but I've just realised that even though the above mentioned error (C compiler cannot create executables) is returned when calling ./configure via `run_in_windows_bash` in conanfile.py, it doesn't occur if I just open msys and execute ./configure from within the ogg repository, without using conan. This is not urgent for me or anything (I can live without mingw builds 😄 ), but I thought to let you know, in case it can help towards future improvements.

**Comment by dimi309** [comment]
I have a bit more information about this. You can reproduce the problem if you clone the [mingw branch](https://github.com/dimi309/conan-packages/tree/mingw) of my conan-packages repository, and then execute from within it (with conan configured for gcc builds on Windows):

```
cd ogg
conan test_package
```
The error produced while the package executes `configure` via `run_in_windows_bash` is this:

```
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/c/users/user/.conan/data/ogg/1.3.2/coding3d/testing/build/cd3e418e619287a431ed81161646f9073dcb193e/libogg-1.3.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
... and further down we see:

```
ogg/1.3.2@coding3d/testing: WARN: ConanException: Error 77 while executing bash --login -c ^"cd \^"/c/users/user/.conan/data/ogg/1.3.2/coding3d/testing/build/cd3e418e619287a431ed81161646f9073dcb193e\^" ^&^& cd libogg-1.3.2 ^&^& ./configure ^"
ERROR: ogg: Error 77 while executing bash --login -c ^"cd \^"/c/users/user/.conan/data/ogg/1.3.2/coding3d/testing/build/cd3e418e619287a431ed81161646f9073dcb193e\^" ^&^& cd libogg-1.3.2 ^&^& ./configure ^"

```

As the error information indicates, I've checked inside config.log (located in the downloaded ogg package in /c/users/user/.conan/data/ogg/1.3.2/coding3d/testing/build/cd3e418e619287a431ed81161646f9073dcb193e/libogg-1.3.2 after the package failed to be built, and I've noticed this:

```
 configure:3324: gcc -V >&5
gcc.exe: error: unrecognized command line option '-V'
```

The gcc -V option does not work it seems in a case-sensitive environment. I've tried running it in msys and it returns an error. `gcc -v` works. This however, comes from within the package's configure script, not conan. But perhaps conan sets some conditions that makes the script try to run it like this? I've tried to run this by hand, and it works, both from a windows cmd prompt with mingw and msys in the path and it works:

`bash --login -c ^"cd \^"/c/users/user/.conan/data/ogg/1.3.2/coding3d/testing/build/cd3e418e619287a431ed81161646f9073dcb193e\^" ^&^& cd libogg-1.3.2 ^&^& ./configure ^" `

After it had completed successfully, when I checked inside config.log I saw this, instead of gcc -V (mentioned above):

configure:3086: result: gcc
configure:3315: checking for C compiler version
configure:3324: **gcc --version** >&5
gcc.exe (GCC) 5.3.0

**Comment by dimi309** [comment]
I've made a bit more progress. The [latest commit](https://github.com/dimi309/conan-packages/commit/c1f70c8366ebc6b9ecfdc088ad69ab71718b27b9) executes configure via run_in_windows_bash, but independently from the AutoToolsBuildEnvironment. In the conanfile.py build method, if not building with Visual Studio, I check if I am on Windows and just execute run_in_windows_bash configure and then make directly:

https://github.com/dimi309/conan-packages/blob/mingw/ogg/conanfile.py

The build is then successfully completed. So it seems that some environment setting set up by AutoToolsBuildEnvironment (which I am still using for macos and linux) does indeed make configure select the gcc -V command mentioned above. 

Of course, life is hard, so CMake, which I use for testing the package does not like seeing sh in the path any more:

```
 CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  C:/MinGW/msys/1.0/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.
```
... which is a pity because run_in_windows_bash, or even executing sh or bash directly via self.run likes msys very much. But this ogg's and my problem, not yours or conan's. Either we use configure, in which case we need msys, or we use CMake. We can't have it both ways. All things considered, including the horrid MinGW build delays, I'm beginning to wonder if it's worth supporting MinGW in this life, from a philosophical perspective 😆

**Comment by lasote** [comment]
😆  Thanks for the feedback, I'll try to take a look to the mysterious ``-V`` and see if you can do some trick with the **sh** in the path. I'm sure we can improve it. And sure, MinGW is a good thing, do not give up! Some of our users are building the Windows libraries from Linux using a cross building MinGW, can you imagine to build your cross platform software all in Linux? It's a dream for me hahaha.

**Comment by dimi309** [comment]
Thanks @lasote!
I'm sure I'll figure it out in the end. I've been talking about dropping mingw for years but I always come back :laughing: Building on Linux for Windows would indeed be a very good thing :smiley:

**Comment by dimi309** [comment]
Got it!  OGG now works with MinGW but it needs msys/bin in the path in order to get built and it builds the test with MSYS Makefiles, in order to avoid the above mentioned CMake error: https://github.com/dimi309/conan-packages/blob/mingw/ogg/test_package/conanfile.py

Notice the replacement:

```
def build(self):
        cmake = CMake(self.settings)
        cmdline = cmake.command_line
        if self.settings.os == "Windows" and self.settings.compiler == "gcc":
            cmdline = cmdline.replace('-G "MinGW Makefiles"', '-G "MSYS Makefiles"')
        self.run('cmake "%s" %s' % (self.conanfile_directory, cmdline))
        self.run("cmake --build . %s" % cmake.build_config)
```

I don't know if there's a way to choose MSYS through the CMake generator. If so, let me know 🤓

**Comment by dimi309** [comment]
Of course until the -V problem is solved (either you figure it out or I manage to make my first pull request to conan that is not about the documentation 😄 ) I cannot continue with the VORBIS library package, because it needs OGG and, in order to reference it, I suppose I would need to build with the AutoToolsBuildEnvironment:

```
env = AutoToolsBuildEnvironment(self)
                with tools.environment_append(env.vars):
... etc.
```
... which is what I avoid in the case of OGG's MinGW build in order to avoid the -V issue...

**Comment by dimi309** [comment]
I've just made some tests and figured out that it was the -m64 flag in CPPFLAGS, LDFLAGS and CFLAGS within AutoToolsBuildEnvironment.vars that was causing the -V problem. I don't know if this happens because I have the default version of MinGW, which I think is basically a 32-bit thing and, without paying attention, I was building with arch=x86_64, especially because the GLEW library could be built under these conditions (of course it doesn't require msys). I suppose that in that case my version of mingw could build a 64 bit binary, or it was just building a 32-bit one anyway.

In any case, even though I have not finished adding mingw support to all packages, I can now advance without needing any changes in conan. I don't know if the information I have provided is useful or if I just took up a lot of your time for nothing. If the latter is the case, sorry ☹️ Feel free to close this issue, if you don't believe that there is any purpose in looking into it.

**Comment by uilianries** [comment]
Hi!

I got the same problem when I try to build libusb:

```
def build(self):
    if self.settings.os == "Windows" and self.settings.compiler == "gcc":
        env_build = AutoToolsBuildEnvironment(self)
        env_build.fpic = True
            with environment_append(env_build.vars):
                with chdir(self.release_name):
                    env_build.configure()
                    env_build.make(args=["all"])
                    env_build.make(args=["install"])
```
The output is:
```
libusb/1.0.21@uilianries/testing: Calling build()
'.' is not recognized as an internal or external command,
operable program or batch file.
libusb/1.0.21@uilianries/testing test package:
libusb/1.0.21@uilianries/testing: ERROR: Package '123a080f55dc9e51bd128e4eff28cc4bfef3ac09' build failed
libusb/1.0.21@uilianries/testing: WARN: Build folder C:\cygwin\home\Uilian Ries\.conan\data\libusb\1.0.21\uilianries\testing\build\123a080f55dc9e51bd128e4eff28cc4bfef3ac09
ERROR: libusb/1.0.21@uilianries/testing: Error in build() method, line 66
        env_build.configure()
        ConanException: Error 1 while executing ./configure
```
Here is the full log: https://ci.appveyor.com/project/uilianries/conan-libusb/build/1.0.104/job/cqw6esjh5mhd7qfj

The same line work on Linux and Mac

**Comment by lasote** [comment]
Thanks! will take a look

**Comment by uilianries** [comment]
Hi! I solved my case, but I done some steps:  
first, I used `tools.run_in_windows_bash` to solve "./configure", after that,   
I got some new errors during *make* command,  the cause was Windows environment variables, that use \ as separator, as result, all paths were stripped by bash. As solution, I replaced all \\ by /. I tried to use `tools.unix_path`, but it didn't work in such case and I didn't investigate. The complete solution is that:

```python
def _run_cmd(self, command):
    if self.settings.os == "Windows":
            tools.run_in_windows_bash(self, tools.unix_path(command))
    else:
        self.run(command)

def build(self):
    env_build = AutoToolsBuildEnvironment(self)
    env_build.fpic = True
    # Solve Windows path on MingW
    unix_environment = {}
    for key, value in env_build.vars.items():
        unix_environment[key] = value.replace("\\", "/")
    with tools.environment_append(unix_environment):
        with tools.chdir(self.release_name):
            self._run_cmd("./configure")
            self._run_cmd("make")
```
As final step, I used `CONAN_BASH_PATH` on AppVeyor job.  
You can see the complete solution here: https://github.com/uilianries/conan-libusb/blob/release/1.0.21/conanfile.py

I found 2 non-trivial points, first, is to replace all path separator for Cygwin, maybe Conan could solve this point, but I did not find any smart way to made such magic. Second, `CONAN_BASH_PATH` is treated by Conan and is documented on docs, but it is used by conan-package-tools and is not referenced.

Regards.

**Comment by dimi309** [comment]
For me things have gotten much simpler. The master branches of the ogg and vorbis libraries now use cmake for the builds. This means that I can now build them in mingw without needing to run ./configure any more, and hence not requiring msys. I have published these latest versions and they work fine. So as far as I am concerned, this is not an issue any more. Please feel free to close it if you think that, also after @uilianries' solution, it does not need to be investigated further.

**Comment by memsharded** [comment]
I am not fully sure that the PR #1917 by @lasote really addresses MSYS building issues now

**Comment by sourcedelica** [comment]
Something related to this topic: `self.run(cwd='relative')` runs in a cwd relative to the build directory (when in `build()`).  But `tools.run_in_windows_bash(self, cmd, 'relative')` runs in a cwd relative to the directory that you ran the `conan` command in.   It would be nice for it to be consistent.

**Comment by lasote** [comment]
@sourcedelica I'll check it, could you open a different issue to not lose the track? Thanks

**Comment by ericLemanissier** [comment]
I confirm on an other project that ./configure works only in tools.run_in_windows_bash
It looks like the -V is actually not a problem : https://superuser.com/questions/846768/gcc-unrecognized-command-line-options-v-and-qversion-with-autoconf

I noticed a problem when using AutoToolsBuildEnvironment flags and defines variables:
```python
            env_build = AutoToolsBuildEnvironment(self)
            env_build.flags += "-O3"
            env_build.defines += "SQLITE_HAS_CODEC"
            with tools.environment_append(vars):
                tools.run_in_windows_bash(self, "./configure")
```
fails because it generates the following flags:
`- O 3  -DS -DQ -DL -DI -DT -DE -D_ -DH -DA -DS -D_ -DC -DO -DD -DE -DC`

One last thing which makes compilation fail is #1943, because path to compiler is not appended to path inside bash environment. environment variable CC gives full path to compiler, and is present in bash environment, but it seems it is not enough
