### ISSUE TITLE
[bug] FileDownloader compares checksum on artifact possibly recoded by `requests`

### ISSUE THREAD

**Issue by mejdys** [conan-io/conan#12813]
### Environment details

* Operating System+version: Tested on macOS and Linux
* Compiler+version: N/A
* Conan version: Tested on 1.53 and 1.56
* Python version: 3.10.9
* `requests` version: 2.28.1

### Steps to reproduce

On the example of recent [breakage](https://github.com/conan-io/conan-center-index/issues/13417#issuecomment-1367939502) in `libjpeg` recipe:

1. Download the sources of the library and check the checksum
```bash
% wget http://ijg.org/files/jpegsrc.v9d.tar.gz
--2022-12-30 15:19:41--  http://ijg.org/files/jpegsrc.v9d.tar.gz
Resolving ijg.org (ijg.org)... 2001:8d8:100f:f000::2f6, 217.160.0.3
Connecting to ijg.org (ijg.org)|2001:8d8:100f:f000::2f6|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1030917 (1007K) [application/gzip]
Saving to: ‘jpegsrc.v9d.tar.gz’

jpegsrc.v9d.tar.gz                         100%[=======================================================================================>]   1007K  5,54MB/s    in 0,2s    

2022-12-30 15:19:42 (5,54 MB/s) - ‘jpegsrc.v9d.tar.gz’ saved [1030917/1030917]

% sha256sum jpegsrc.v9d.tar.gz 
2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a  jpegsrc.v9d.tar.gz
```
2. Observe the filesize (ca 1MB) and the sha (2303a6...)
3. Create a simple recipe that just downloads the sources
```python
from conan import ConanFile
from conan.tools.files import get

class LibjpegConan(ConanFile):
    def source(self):
        get(self, url="http://ijg.org/files/jpegsrc.v9d.tar.gz",
        	sha256="2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a",
            destination=self.source_folder, strip_root=True)
```
4. Test the recipe
```bash
% conan source . 
conanfile.py: Configuring sources in /Users/me/Downloads/bug-report
Downloading jpegsrc.v9d.tar.gz completed [4040.00k]
ERROR: conanfile.py: Error in source() method, line 6
	get(self, url="http://ijg.org/files/jpegsrc.v9d.tar.gz",
	ConanException: sha256 signature failed for 'jpegsrc.v9d.tar.gz' file. 
 Provided signature: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a  
 Computed signature: 83d4b17eb45588c6e19405b99038a137c78fe179d8d2f80b7b0f16450d581c31
```

conan expects a surprising signature (83d4b...) inconsistent with that of the server artifact. It also reports a different filesize (ca 4MB). It's because Conan's FileDownloader [relies](https://github.com/conan-io/conan/blob/develop/conans/client/downloaders/file_downloader.py#L94) on `requests` [default behavior](http://docs.python-requests.org/en/latest/community/faq/#encoded-data) of decoding whatever possible. It means:
- recipe authors are forced to put a checksum not observed on the actual server artifact
- recipe is fragile and may break if the server configuration (w.r.t. metadata) changes or client's set of libraries is different (changing what `requests` can decode themselves)

**Comment by memsharded** [comment]
Hi @mejdys 

This is quite surprising.
I can indeed reproduce with the file that you are linking for jpeg, but I am also checking some other files, and they obtain the correct checksum:
```
ZLIB
    url: "https://zlib.net/fossils/zlib-1.2.13.tar.gz"
    sha256: "b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30"
BOOST
      - "https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.bz2"
      - "https://sourceforge.net/projects/boost/files/boost/1.81.0/boost_1_81_0.tar.bz2"
    sha256: "71feeed900fbccca04a3b4f2f84a7c217186f28a940ed8b7ed4725986baf99fa"
OPENCV
    - url: "https://github.com/opencv/opencv/archive/refs/tags/4.5.5.tar.gz"
      sha256: "a1cfdcf6619387ca9e232687504da996aaa9f7b5689986b8331ec02cb61d28ad"

```
So it seems this works in most cases, and it could be something special to the libjpeg sources only? Is that server doing something unusual to serve it?
If I download http://ijg.org/files/jpegsrc.v9d.tar.gz with my browser, I am also getting 
the checksum ``83d4b17eb45588c6e19405b99038a137c78fe179d8d2f80b7b0f16450d581c31``, so this checksum seems the correct one and not ``2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a`` ? For some reason the server is doing something different when you download via wget or curl.

**Comment by memsharded** [comment]
Got some new insight: https://github.com/mxe/mxe/issues/2104#issuecomment-1001232759

It could happen that the file in one server and the file in the CDN might have different checksums 🤦 
Depending on how the client side resolves the URL, it seems it might resolve in different locations, obtaining a different file. It seems it is not something on the Conan client, but on the jpeg infrastructure, which seems broken.

**Comment by mejdys** [comment]
@memsharded, thanks for having a look so quickly!

I am consistently getting `2303a6...` (& 1MB) with my browser (Firefox) and `wget`, as opposed to `83d4b1...` (& 4MB) reported by conan. I also hacked conan to [disable](https://stackoverflow.com/questions/25749345/how-to-download-gz-files-with-requests-in-python-without-decoding-it/62202093#62202093) `requests` default behavior, and serve the content as downloaded originally, and then checksum verification works OK (i.e. conan also reports `2303a6...`).

However, I now tested Safari, and it actually downloads 4 MB (& `83d4b1...`). But I also wiresharked Firefox and conan downloads (1MB v 4MB), and they both showed a similar metadata and transfer size. So it's more the interpretation of it on the client side.

I agree the overall picture is still fuzzy. It does seem like jpeg server must have been updated in the last few days as the recipe started failing suddenly. But I also still believe there is an issue in conan's use of `requests`, as with a patch, the download process becomes less sensitive to such environmental factors.

**Comment by mejdys** [comment]
hm, I started doubting myself. The headers of the server response are:

```
Hypertext Transfer Protocol
    HTTP/1.1 200 OK\r\n
    Content-Type: application/gzip\r\n
    Content-Length: 1030917\r\n
    Connection: keep-alive\r\n
    Keep-Alive: timeout=15\r\n
    Date: Fri, 30 Dec 2022 15:18:25 GMT\r\n
    Server: Apache\r\n
    Last-Modified: Tue, 04 Jan 2022 11:02:40 GMT\r\n
    ETag: "fbb05-5d4bf9360f400"\r\n
    Accept-Ranges: bytes\r\n
    Content-Encoding: x-gzip\r\n
```

[Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) is the encoding applied extra to the payload by the server. So `requests` and some browsers might be correct in decoding it before presenting to the user. And the server might be wrong in adding `Content-Encoding` here.

I will see if I can reach https://jpegclub.org/reference/contact/, which was mentioned on one of the issues as contact point for earlier "sha-changed" issues.

**Comment by memsharded** [comment]
> [Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) is the encoding applied extra to the payload by the server. So requests and some browsers might be correct in decoding it before presenting to the user. And the server might be wrong in adding Content-Encoding here.

I think I have seen this before: Some server doing weird things about the encoding, deciding differently for different user-agents (and probably a not updated list of them. I used Chrome to download it btw). I'd say it is a bug on their server.

**Comment by mejdys** [comment]
jpegclub now [confirmed](https://github.com/conan-io/conan-center-index/issues/13417#issuecomment-1368744694) there was a change on the server side and they look to fix it on their side.
There is still a slim change there is a bug somewhere, but given it's not only conan and `requests`, but also some browsers getting the same results, it feels very unlikely. So I will close this ticket.

Sorry for the confusion, but thank you very much for the support in investigation!

**Comment by memsharded** [comment]
Thanks to you for your report and following up!
