### ISSUE TITLE
[question] Should profile options apply to dependencies?

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12811]
### What is your question?

I am trying to build boost/1.79.0 as a shared library using Conan 2.0 and the recipe from CCI. I have my host and build profiles configured as follows:

> Profile host:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.libcxx=libstdc++11
> compiler.version=10.3
> os=Linux
> [options]
> shared=True
> [tool_requires]
> *: gcc/10.3.0, cmake/3.24.2, ninja/1.11.0
> [conf]
> tools.cmake.cmaketoolchain:generator=Ninja
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.libcxx=libstdc++11
> compiler.version=8
> os=Linux
> [options]
> cmake*:bootstrap=True
> [tool_requires]
> !openssl*: cmake/3.24.2

I have previously built the three required dependencies (bzip2, libbacktrace, and zlib) using the same profiles, which means they too were built as shared libraries. Now, when I try to build boost, I get the following error:

> -------- Installing (downloading, building) binaries... --------
> ERROR: Missing binary: bzip2/1.0.8:a03a232f92a8433653dbdfbb0739362e42ac3194
> ERROR: Missing binary: libbacktrace/cci.20210118:e71f87fe4e27609cfd4347add62b6d67b251f2e9
> ERROR: Missing binary: zlib/1.2.13:e71f87fe4e27609cfd4347add62b6d67b251f2e9
> 
> bzip2/1.0.8: WARN: Can't find a 'bzip2/1.0.8' package binary 'a03a232f92a8433653dbdfbb0739362e42ac3194' for the configuration:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.version=10.3
> os=Linux
> [options]
> build_executable=True
> fPIC=True
> shared=False
> 
> ERROR: Missing prebuilt package for 'bzip2/1.0.8', 'libbacktrace/cci.20210118', 'zlib/1.2.13'
> Use 'conan list packages bzip2/1.0.8 --format=html -r=remote > table.html' and open the table.html file to see available packages
> Or try to build locally from sources with '--build=bzip2/1.0.8 --build=libbacktrace/cci.20210118 --build=zlib/1.2.13'
> 
> More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

Notice that it appears to be looking for bzip2 with shared=False in spite of the host profile listing shared=True. If I edit the bzip2 recipe itself, and change the default value of the shared option from False to True, rebuild bzip2, and then try building boost again, the issue moves to the next required library:

> -------- Installing (downloading, building) binaries... --------
> ERROR: Missing binary: libbacktrace/cci.20210118:e71f87fe4e27609cfd4347add62b6d67b251f2e9
> ERROR: Missing binary: zlib/1.2.13:e71f87fe4e27609cfd4347add62b6d67b251f2e9
> 
> libbacktrace/cci.20210118: WARN: Can't find a 'libbacktrace/cci.20210118' package binary 'e71f87fe4e27609cfd4347add62b6d67b251f2e9' for the configuration:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.version=10.3
> os=Linux
> [options]
> fPIC=True
> shared=False
> 
> ERROR: Missing prebuilt package for 'libbacktrace/cci.20210118', 'zlib/1.2.13'
> Use 'conan list packages libbacktrace/cci.20210118 --format=html -r=remote > table.html' and open the table.html file to see available packages
> Or try to build locally from sources with '--build=libbacktrace/cci.20210118 --build=zlib/1.2.13'
> 
> More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

Thus I conclude that Conan 2.0 is looking for required dependencies using the default options as specified in their respective recipes rather than the options specified in the host profile used to build the current target. This seems wrong to me as it would indicate that the profile options are not influencing the configuration of the dependencies used when building a target, which I would expect they surely should. Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @System-Arch 

I am not sure if I get it. 
I think that you need to use ``*:shared=True`` (instead of ``shared=True``) in your profile, if you want to use all shared libraries. Otherwise it means the current one is shared library and the dependencies are static libraries, which is typically problematic if done to all dependencies in the graph.

**Comment by System-Arch** [comment]
Hi @memsharded,

Ah, thanks for the quick reply--that makes sense. Hadn't realized that wasn't the behavior without the "*". I just tried it, and indeed that gets me past this issue. Thanks again for the fast turnaround--much appreciated.

P.S. Not to be a bother, but any thoughts on #12785? Am I missing anything there too? Thanks

**Comment by memsharded** [comment]
> Ah, thanks for the quick reply--that makes sense. Hadn't realized that wasn't the behavior without the "*". I just tried it, and indeed that gets me past this issue. Thanks again for the fast turnaround--much appreciated.

Great, considering this issue solved, and closing.
