### ISSUE TITLE
[feature] Filter out `.DS_Store` on macOS in command `conan profile list`

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12816]
### What is your suggestion?

If there is a `.DS_Store` file in profiles folder, it's listed as a profile by `conan profile list` command. It should not be displayed.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Thanks for your suggestion, you're right that having clear outputs and not lying to the user is a good idea fi we know something is not a profile. 

For anyone interested in contributing this feature, I'll lay down the necessary steps to implement it, but please feel free to ask any questions if you find any problems during the process:


1. Setup the developing environment. When forking the project, make sure to uncheck "Clone only main branch", as we'll need to checkout the `develop2` branch, and this is by far the easiest way. Once you've done so, docs for setting up the env can be found in https://github.com/conan-io/conan#install-a-development-version. Open the project in your IDE of preference, everything _should_ be automatically picked up.
2. The command we want to modify is `profile`. You'll find its CLI in `conan/cli/commands/profile.py`. Its implementation is super simple, as it relies in the public conan API implementation for profiles found in `conan/api/subapi/profiles.py`
3. The interesting `list` function just walks the path of the profiles and is where we'll want to implement the changes. Feel free to do so as you see fit, but think about longterm maintenance and how we might want to in the future add some more folders/files (Such as `.git` to give you an example) The next step gives you info about creating the tests if you want to first do so before implementing the functionality
4. Tests in conan are currently found in `conans/test/`, and for this you'll want to create a new integration test in the corresponding `conans/test/integration/commands/test_profile.py` file, in which you:
 - Instantiate a TestClient()
 - Add a profile to be filtered out to its cache folder. Some useful attributes and methods for this will be `TestClient::cache.profile_path` for the folder of this TestClient profile folder path in which to add the empty profile, and the `TestClient::run` method to invoke the `conan profile` command. Note that this command stores its output in `TestClient::out`, so you can assert for any kind of output over that attribute
5. Send us a PR, we'll be happy to review it and help you where needed

**Comment by dead-tech** [comment]
I would like to give this a go 😄

**Comment by memsharded** [comment]
Fixed by @dead-tech in https://github.com/conan-io/conan/pull/12845, for beta.8
