### ISSUE TITLE
[bug] RC : fatal error RC1212: invalid option - /z argument missing substitute font name

### ISSUE THREAD

**Issue by sinall** [conan-io/conan#12819]
### Environment details

* Operating System+version: Windows11
* Compiler+version: VC++2022
* Conan version: 1.50.0 & 1.56.0
* Python version: 3.9.13

Conanfile:
```
from conans import ConanFile
import os

class MyConan(ConanFile):
	settings = "os", "compiler", "build_type", "arch"

	requires = (
		"openssl/1.1.1d",
		"boost/1.76.0",
		"di/1.2.0",
		"cpprestsdk/2.10.18",
		"soci/4.0.3",
		"sqlcipher/4.5.1",
		"libzip/1.7.3",
		"libzippp/4.0",
		"bzip2/1.0.8",
		"zlib/1.2.13",
		"zstd/1.5.2",
		"ms-gsl/3.0.1",
		"tesseract/4.1.1",
		"xz_utils/5.2.4",
		"cryptopp/8.5.0",
		"opencv/4.5.2",
		"libwebp/1.1.0",
		"qt/6.4.1",
		"libpng/1.6.39",
		"libiconv/1.17",
		"sqlite3/3.40.0",
		"libjpeg/9e",
		"libtiff/4.4.0",
	)

	generators = "visual_studio"

	default_options = (
		"boost:without_python=False",
		"boost:python_executable=" + os.path.join(os.path.dirname(__file__), "../../packages/Python/Python38/python.exe"),
		"boost:python_version=3.8",
		"soci:with_sqlite3=True",
		"libzip:shared=True",
		"libzippp:with_encryption=True",
	)

	def imports(self):
		dst = os.path.join("..", "..")
		if self.settings.arch == "x86_64":
			dst = os.path.join(dst, "x64")
		dst = os.path.join(dst, str(self.settings.build_type))
		self.copy("*.dll", dst, "bin", excludes=("libEGL*.dll", "libGLESv2*.dll"))

```

### Steps to reproduce

1. conan install . -if conaninfo/Debug --profile debug-x64 --build missing --no-imports

### Logs

> "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\rc.exe" /D FFI_BUILDING /D PCRE2_STATIC /D LIBJPEG_STATIC /D LZMA_API_STATIC /D OPJ_STATIC /D USE_GIF_LIB /D BOOST_STACKTRACE_USE_NOOP /D BOOST_STACKTRACE_USE_WINDBG /D BOOST_STACKTRACE_USE_WINDBG_CACHED /D BOOST_PYTHON_STATIC_LIB /D BOOST_ALL_NO_LIB /D LIBARCHIVE_STATIC /D QT_NETWORK_LIB /D QT_SQL_LIB /D QT_TEST_LIB /D QT_PRINTSUPPORT_LIB /D QT_OPENGLWIDGETS_LIB /D QT_WIDGETS_LIB /D QT_OPENGL_LIB /D QT_GUI_LIB /D QT_CONCURRENT_LIB /D QT_XML_LIB /D QT_CORE_LIB /D GSL_TERMINATE_ON_CONTRACT_VIOLATION /D LIBZIPPP_WITH_ENCRYPTION /D SQLITE_HAS_CODEC /D SQLITE_TEMP_STORE=2 /D SQLCIPHER_CRYPTO_OPENSSL /D _NO_ASYNCRTIMP /D BOOST_DI_CFG_DIAGNOSTICS_LEVEL=1 /l"0x0409" /ID:\.conan\data\di\1.2.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include /ID:\.conan\data\cpprestsdk\2.10.18\_\_\package\cb67ab36a4704bfc3a57260cb9ef073cff5dc59f\include /ID:\.conan\data\soci\4.0.3\_\_\package\4c9ef79a97b6e4ac4071faf7041da18e9faefce7\include /ID:\.conan\data\sqlcipher\4.5.1\_\_\package\9f5e6ba3b4b8a5b9bc4886dcfceee6372d60551c\include /ID:\.conan\data\sqlcipher\4.5.1\_\_\package\9f5e6ba3b4b8a5b9bc4886dcfceee6372d60551c\include\sqlcipher /ID:\.conan\data\libzippp\4.0\_\_\package\4bd4b4becfaff10724322705ab9dd891d1e497c1\include /I"D:\.conan\data\ms-gsl\3.0.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include" /ID:\.conan\data\tesseract\4.1.1\_\_\package\5dda08473b74b8d0ddea87df177d8c0e4ffb57e4\include /ID:\.conan\data\cryptopp\8.5.0\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\1ff5ad\1\include /I"D:\.conan\3d5de2\1\res\archdatadir\mkspecs\win32-msvc" /ID:\.conan\3d5de2\1\include /ID:\.conan\3d5de2\1\include\QtNetwork /ID:\.conan\3d5de2\1\include\QtSql /ID:\.conan\3d5de2\1\include\QtTest /ID:\.conan\3d5de2\1\include\QtPrintSupport /ID:\.conan\3d5de2\1\include\QtOpenGLWidgets /ID:\.conan\3d5de2\1\include\QtWidgets /ID:\.conan\3d5de2\1\include\QtOpenGL /ID:\.conan\3d5de2\1\include\QtGui /ID:\.conan\3d5de2\1\include\QtConcurrent /ID:\.conan\3d5de2\1\include\QtXml /ID:\.conan\3d5de2\1\include\QtCore /ID:\.conan\data\websocketpp\0.8.2\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include /ID:\.conan\data\sqlite3\3.40.0\_\_\package\6479851e80c7daa08c841403b40c4699e1a1c9d4\include /ID:\.conan\data\libzip\1.7.3\_\_\package\41d3884379620e9b2ee1575388cc9b423915795e\include /ID:\.conan\data\leptonica\1.80.0\_\_\package\ca20ad8d0afba8d02f1608ed8c51bcfd1054f5ea\include /ID:\.conan\data\leptonica\1.80.0\_\_\package\ca20ad8d0afba8d02f1608ed8c51bcfd1054f5ea\include\leptonica /ID:\.conan\data\libarchive\3.5.1\_\_\package\1bd1b1038a9e513777d8e4fa136fe0fb58351db6\include /ID:\.conan\data\jasper\2.0.32\_\_\package\2278242cc765d77e29f54e7b3e73f056c18d9a10\include /ID:\.conan\data\openexr\2.5.5\_\_\package\6acf24cd4adf2df742e006cc0e5f0329e3b6e60b\include\OpenEXR /ID:\.conan\data\openexr\2.5.5\_\_\package\6acf24cd4adf2df742e006cc0e5f0329e3b6e60b\include /ID:\.conan\data\eigen\3.3.9\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3 /ID:\.conan\data\quirc\1.1\_\_\package\11b7230897ba30e6da1af1c8b0726ed134f404ee\include /ID:\.conan\e57f02\1\include /I"D:\.conan\data\double-conversion\3.2.1\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include" /ID:\.conan\22dd21\1\include /ID:\.conan\22dd21\1\include\harfbuzz /ID:\.conan\data\libpq\14.5\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\md4c\0.4.8\_\_\package\1f5b0ce9970a3c13e031b0fc7851f447d0887ff3\include /ID:\.conan\data\openssl\1.1.1d\_\_\package\6acf24cd4adf2df742e006cc0e5f0329e3b6e60b\include /ID:\.conan\ed2479\1\include /ID:\.conan\data\giflib\5.2.1\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\libtiff\4.2.0\_\_\package\e2e95cb5797e0ea720de15db3e7a049a3772be97\include /ID:\.conan\data\openjpeg\2.4.0\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /I"D:\.conan\data\openjpeg\2.4.0\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include\openjpeg-2.4" /ID:\.conan\data\freetype\2.12.1\_\_\package\c69bad48274e7fc45c887cddc32aa0459f0a81e0\include /ID:\.conan\data\freetype\2.12.1\_\_\package\c69bad48274e7fc45c887cddc32aa0459f0a81e0\include\freetype2 /ID:\.conan\fe8f1b\1\include /I"D:\.conan\fe8f1b\1\include\gio-win32-2.0" /I"D:\.conan\fe8f1b\1\include\glib-2.0" /I"D:\.conan\fe8f1b\1\lib\glib-2.0\include" /ID:\.conan\data\xz_utils\5.2.4\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\zstd\1.5.2\_\_\package\1967f444568571a94da80e35a521699f1a90cb74\include /ID:\.conan\data\libjpeg\9d\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\libpng\1.6.39\_\_\package\8b1ef0ec9599374db4689199730c00a0d5f4de36\include /ID:\.conan\data\libdeflate\1.7\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\jbig\20160605\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\libwebp\1.1.0\_\_\package\092f77d3b4b4678d81fbffc1fccc9642b870175e\include /ID:\.conan\data\pcre2\10.40\_\_\package\2e8119dcddebbc9d5753b8e12f06b903b0f1ae93\include /ID:\.conan\data\brotli\1.0.9\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\brotli\1.0.9\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include\brotli /ID:\.conan\data\libffi\3.4.3\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\libgettext\0.21\_\_\paackage\e0c22822cdf05b624135e1696ae5cb784a23aeb3\include /ID:\.conan\data\zlib\1.2.12\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /ID:\.conan\data\bzip2\1.0.8\_\_\package\589a23dff5fdb23a7fb851223eb766480ead0a9a\include /ID:\.conan\data\libiconv\1.17\_\_\package\d057732059ea44a47760900cb5e4855d2bea8714\include /nologo /fo"x64\Debug\XXX_Gui_Qt.res" -permissive- -Zc:__cplusplus XXX_Gui_Qt.rc

10>RC : fatal error RC1212: invalid option - /z argument missing substitute font name

After I remove $(ConanCompilerFlags) from `<ResourceCompile/>`, the error disappears.

**Comment by memsharded** [comment]
Hi @sinall 

Thanks for your report.
It would be necessary to know more about your current ``conanfile`` you are using and the full output that you are seeing, if you can please share them.

**Comment by sinall** [comment]
> Hi @sinall
> 
> Thanks for your report. It would be necessary to know more about your current `conanfile` you are using and the full output that you are seeing, if you can please share them.

I added some verbose log into the thread.

**Comment by sinall** [comment]
After I switch to generators = "MSBuildDeps", the problem still exists:

![image](https://user-images.githubusercontent.com/1246382/210195527-43be23fe-ccc1-4278-b004-fdfc80897173.png)
![image](https://user-images.githubusercontent.com/1246382/210195542-898e83c0-99b7-4e7f-834a-9afaab222280.png)

I guess the new version of rc.exe doesn't like `-Zc:__cplusplus`, so we could use a different `Conanqt_qtCoreCompilerFlags` for ResourceCompile/AdditionalOptions.

**Comment by BobIsOnFire** [comment]
Hi @memsharded

I got similar error when trying to use MSBuildToolchain with ACE.

Here is my `generate()` method:

```py
    def generate(self):
        tc = MSBuildToolchain(self)
        tc.preprocessor_definitions["_HAS_AUTO_PTR_ETC"] = 1
        tc.generate()
```

And profile:

```
[settings]
os=Windows
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=17
compiler.version=193
compiler.update=6
compiler.runtime=dynamic
[conf]
tools.build:cxxflags=['/Od', '/RTC1', '/D_DEBUG', '/DWIN32', '/D_WINDOWS', '/EHsc']
tools.build:sharedlinkflags=['/DEBUG', '/INCREMENTAL', '/machine:x64']
tools.build:compiler_executables={'c': 'C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe', 'cpp': 'C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe'}
```

Results in following `conantoolchain_debug_x64.props`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>_HAS_AUTO_PTR_ETC=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalOptions>/Od /RTC1 /D_DEBUG /DWIN32 /D_WINDOWS /EHsc %(AdditionalOptions)</AdditionalOptions>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <LanguageStandard>stdcpp17</LanguageStandard>
      <MultiProcessorCompilation>True</MultiProcessorCompilation>
      <ProcessorNumber>12</ProcessorNumber>
    </ClCompile>
    <Link>
      <AdditionalOptions>/DEBUG /INCREMENTAL /machine:x64 %(AdditionalOptions)</AdditionalOptions>
    </Link>
    <ResourceCompile>
      <PreprocessorDefinitions>_HAS_AUTO_PTR_ETC=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <!-- next line is incorrectly filled with C++ compiler options -->
      <AdditionalOptions>/Od /RTC1 /D_DEBUG /DWIN32 /D_WINDOWS /EHsc %(AdditionalOptions)</AdditionalOptions>
    </ResourceCompile>
  </ItemDefinitionGroup>
  <PropertyGroup Label="Configuration">
    <PlatformToolset>v143</PlatformToolset>
  </PropertyGroup>
</Project>
```

And if I try to include it, I get `RC : fatal error RC1106: invalid option: /Od`.

Even though it makes sense to pass `tc.preprocessor_definitions` into the `ResourceCompile`, I think passing just usual C++ compiler flags is a very bad idea (since `rc.exe` is basically a different tool).

Could you please fix this? I would be happy if `AdditionalOptions` was just never filled up for `ResourceCompile`.

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/14378, for next 2.0.10
