### ISSUE TITLE
Configure(self) method do not have os.environ vars

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1282]
Same that happened with `test()` method. `self.env`is available.

**Comment by memsharded** [comment]
This has a limitation though.

``configure()`` is executed before pulling the requirements. So it is not possible to use environment variables defined by the dependencies. This will apply only to environment variables defined by the system, user input, or profiles. This will be slightly inconsistent, but I guess better provide that than nothing.

**Comment by memsharded** [comment]
Also apply it to ``config_options()`` and ``requirements()`` methods?
