### ISSUE TITLE
[bug] `conan inspect` does not return requirements set by `requirements()` method

### ISSUE THREAD

**Issue by andreas-km** [conan-io/conan#12838]
### Environment details

* Operating System+version: Ubuntu 22.04.1
* Compiler+version: N/A
* Conan version: 1.54
* Python version: 3.10.6

### Steps to reproduce

1. Create the following `conanfile.py`:
    ```python
    from conans import ConanFile
    class TestConan(ConanFile):
        def requirements(self):
            self.requires("openssl/1.1.1o")
    ```
2. Run `conan inspect -a requires .`

**Expected behaviour**: Conan returns the calculated `requires` list: `requires: ['openssl/1.1.1o']`
**Actual behaviour**: The returned `requires` has no value, not even an empty list: `requires: `

Note that if the requirements are set as follows it works as expected:
```python
from conans import ConanFile
class TestConan(ConanFile):
    requires = ["openssl/1.1.1o"]
```

### Logs

```
$ conan inspect -a requires .
requires: 
```

**Comment by memsharded** [comment]
Hi @andreas-km 

Thanks for your report.
This is by design. ``conan inspect`` do not perform a full evaluation of the recipe, and it does not evaluate ``requirements()``. In order to do so, it would need things like the full input profiles, and that is out of the scope of the ``conan inspect`` command.
If you want more detailed information about evaluated requirements, it is necessary to evaluate the full graph, this can be done with ``conan info`` command (``conan graph info`` in 2.0)

**Comment by andreas-km** [comment]
Hi  @memsharded , thanks for your response!

If this is as designed, could it be added to the documentation page for `conan inspect` that it does not evaluate the recipe?

The real life use case behind this bug is a bit more complicated and involves version ranges:
```python
from conans import ConanFile
class TestConan(ConanFile):
    def requirements(self):
        self.requires("zlib/[>=1.2.0 <1.2.12]")
```

I want to be able to programatically get the version or version range of the requirements. The issue as I see it is that `conan inspect` will not evaluate `requirements()`, and thus will not know about the requirement at all. But `conan info` will in addition to evaluating `requirements()` *also* evaluate the version range itself, thereby removing the the range info. It also doesn't have a nice way to output only the requirements without all the other information.

Is the only way to get the version range then to parse the full output of `conan info` and look for the "version range resolved" log messages?

**Comment by memsharded** [comment]
> I want to be able to programatically get the version or version range of the requirements. The issue as I see it is that conan inspect will not evaluate requirements(), and thus will not know about the requirement at all. But conan info will in addition to evaluating requirements() also evaluate the version range itself, thereby removing the the range info. It also doesn't have a nice way to output only the requirements without all the other information.

You can try different approaches:
- If your requirements are not conditional, you can declare them as ``requires = zlib/[>1...]``, and those will be listed in ``conan inspect``
- If you have some other custom logic, you might want to add them to structured ``conandata.yml`` fields, so you can parse that file more easily

The ``conan info`` command does return the evaluated graph, I think the original range is not displayed, but the final resulting version.

**Comment by andreas-km** [comment]
The requirements are conditional unfortunately, so setting `requires= [...]` as normal doesn't work.

The workaround I've found so far is to have an `__init__()` method for the conanfile, and set `self.requires` in that method:
```python
    def __init__(self, *args):
        super().__init__(*args)
        self.requires = self._get_requirements()
```
Here `self._get_requirements()` does the same stuff that would normally be done in `requirements()`. I haven't seen this in the documentation anywhere, so I don't know if it breaks some best practice somehow. It feels a bit hacky to me at least. But the requires does show up for `conan inspect` whend doing it like this.

I think the long term solution for me at least will be to try to refactor the tooling we use to not need the version range, but let conan resolve it and just use the result.

Since the original "bug" was intended behaviour, I am closing the issue. Thanks for your help @memsharded!

**Comment by memsharded** [comment]
> Here self._get_requirements() does the same stuff that would normally be done in requirements(). I haven't seen this in the documentation anywhere, so I don't know if it breaks some best practice somehow. It feels a bit hacky to me at least. But the requires does show up for conan inspect whend doing it like this.

Yes, the problem here is that this will not be correct. When ``__init__`` is called, the full information with settings, options, is not there yet, so whatever conditionals you have inside ``requirements()`` method will probably be incorrectly evaluated.
Also, yes, using ``__init__`` in conanfiles is not possible, that is an internal implementation thing and has some risk of breaking, but I think the above is even a bigger concern.

**Comment by andreas-km** [comment]
Sorry, I think I misunderstood what you meant by "conditional". The `requirements()` method will read a file and set version ranges based on that, but it is not dependent on anything in conan like settings or options. As I understood it, `requires = []` should be used for static requirements, whilst requirements that need to be calculated in some way should be set by using `requirements()`. So even though it is not conditional on any options or settings I places it there.

But it sounds like using `__init__()` should be avoided anyway, so not sure it matters.

**Comment by memsharded** [comment]
By conditional I mean something like:
```python
def requirements(self):
     if self.settings.os == "Windows":
           self.requires("winonlydep/1.0")
     else:
           self.requires("nixdep/2.0")
```

If that is not the case, then it seems that you could use attribute definition instead of the method because:
```python
def requirements(self):
        self.requires("zlib/[>=1.2.0 <1.2.12]")
```
is equivalent to:
```python
requires = "zlib/[>=1.2.0 <1.2.12]"
```
