### ISSUE TITLE
Linter warning: no info_build member

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1283]
Following the instructions in the documentation for `build_id()`, I set the `self.info_build.options.myoption` in my `build_id(self)` method.  It still appears to work correctly, preventing a rebuild, but the Linter is complaining.

Should I be doing it differently?

**Comment by memsharded** [comment]
No, you are right, this is an issue. The linter is not able to understand that such member is created at runtime, then complaining. It happens for a few members, this should be improved, filtering the messages, or maybe adding default=None members in the conanfile.

**Comment by memsharded** [comment]
ALSO: Make it configurable "warning as errors", and export aborted. Opt-in/user configurable. cc/ @tru

**Comment by memsharded** [comment]
Both things have been implemented in # 1365, avoiding the false positives and a new configuration ``pylint_werr`` and ``PYLINT_WERR`` env-var to error instead of warning while linting. Will be in 0.24

**Comment by memsharded** [comment]
Fix released in 0.24!

**Comment by jinq0123** [comment]
`    WARN: Linter. ... no 'info' member`
I made a header only package, and got the warn. https://github.com/jinq0123/conan-lua-intf
```python
    def package_id(self):
        self.info.header_only()
```
The full output:
```
E:\Git\conan-lua-intf (master)
λ conan create jinq0123/testing
lua-intf/0.1@jinq0123/testing: Exporting package recipe
Linter warnings
    WARN: Linter. Line 18: Instance of 'LuaintfConan' has no 'info' member
...
```
```
λ conan -v
Conan version 0.25.1
```

**Comment by memsharded** [comment]
@jinq0123 There is an open issue for this, scheduled to fix in next release: https://github.com/conan-io/conan/issues/1543, if you want to follow it. Thanks for telling!
