### ISSUE TITLE
[question] How to test a CMake Package with different options

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#12834]
### What is your question?

Hey guys,
I'm having a CMake Package with multiple options. I'd like to test the package with different options

I'm running this
`conan create . --build missing --profile:host crossbuild --profile:build default -o FreeRTOS:BUILD_TARGET=True`

So far my recipe looks like this
```

from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout
from conan.tools.scm import Git


class FreeRTOSConan(ConanFile):
    name = "FreeRTOS"
    version = "0.3"

    # Optional metadata
    license = "Apache 2.0"
    author = "Julian Heni"
    url = "https://gitlab.cds.testo/third_party/freertos"
    description = "FreeRTOS as a conan 3rd party"
    topics = ("FreeRTOS", "c", "c++")

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False],
               "fPIC": [True, False],
               "BUILD_TARGET": [True, False],
               "BUILD_SIMULATION": [True, False],
               }
    default_options = {"shared": True,
                       "fPIC": True,
                       "BUILD_TARGET": False,
                       "BUILD_SIMULATION": True}
    generators = "CMakeDeps"
    # build_policy = "always"  # for better debugging always build freertos

    def source(self):
        git = Git(self)
        # check out tagged version
        clone_args = ["-b add_port_arm_cm4f"]
        git.clone(url="git@gitlab.cds.testo:third_party/freertos.git", args=clone_args)

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
        if self.options.BUILD_TARGET:
            print("Building target")
            tc.cache_variables["BUILD_TARGET"] = "ON"
            tc.cache_variables["BUILD_SIMULATION"] = "OFF"
            del self.options.fPIC

        else:
            print("Building simulation")
            tc.cache_variables["BUILD_TARGET"] = "OFF"
            tc.cache_variables["BUILD_SIMULATION"] = "ON"
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure(build_script_folder="freertos")
        cmake.build()
        cmake.test(build_type=self.settings.build_type, target="FreeRTOS")

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["FreeRTOS"]
        self.cpp_info.includedirs = ["include"]
```

I would try to run
` cmake.test(build_type=self.settings.build_type, target="FreeRTOS") `
for BUILD_TARGET=ON and BUILD_SIMULATION=ON

I tried this
```
cmake.test(build_type=self.settings.build_type, target="FreeRTOS") # (use default option BUILD_SIMULATION)
cmake.test(build_type=self.settings.build_type, target="FreeRTOS", build_tool_args="-DBUILD_TARGET")
```

however this results in an error
```
bug --target FreeRTOS -- -j12 D B U I L D _ T A R G E T
ninja: error: unknown target 'D', did you mean 'all'?
```

=> so what is the best way to test different package options?

thx for your help :)

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ju1He1 

Quick question:
- The options seems mutually exclusive, based on the code you show in ``generate()``, TARGET and SIMULATION seems opposite. Then it sounds like only 1 options ``simulation: [True, False]``, by default ``False`` would be enough?


The ``cmake.test()`` is intended to run tests that were built before. It doesn't make much sense to pass different arguments that would cause an inconsistent build with the previous one? What I am missing here? Why it is not enough to run the tests that were built for that configuration?

**Comment by ghost** [comment]
Hey @memsharded  ja are right, BUILD_SIMULATION and BUILD_TARGET are mutaly exclusive, I have reduced that to BUILD_TARGET (thx for that note ;))

ah I think i misunderstood how conan works.
So just to clarify:
Whenever I call `conan install .... `
the test is executed either with BUILD_TARGET=ON or BUILD_TARGET=OFF depending on my used configuration?

**Comment by memsharded** [comment]
Note: Beware of an incorrect ``del self.options.fPIC`` that slipped into ``generate()``, probably copy& paste.

The ``conan install`` will not build or execute any test. But it will define a toolchain that defines what to do, what tests will be built or not, and what tests will be run. Subsequent calls to ``conan build`` or calling ``cmake`` with that toolchain will do what was defined at ``conan install`` time.

If you want to manage multiple configurations, simultaneously in different folders, it is possible:
- You can call ``conan install`` different times, with different options.
- By defining the ``tools.cmake.cmake_layout:build_folder_vars=["options.BUILD_TARGET"]`` you can make ``cmake_layout()`` to create different folders with different toolchains and different CMake presets to handle them. Then you can build and test both configurations easily.

**Comment by ghost** [comment]
ah thx for your explanation. Yes you're right del self.options.fPIC inside generate was a copy&paste error ⭕
