### ISSUE TITLE
[question] Export sources compiler depended

### ISSUE THREAD

**Issue by xakod** [conan-io/conan#12844]
### How to copy files in export_sources depends on compiler?

Hi! I tried:
```python
    def export_sources(self):
        if is_msvc(self):
            copy(self, "CMakeLists.txt", self.recipe_folder, os.path.join(self.export_sources_folder, "src"))
            copy(self, "config.h", self.recipe_folder, os.path.join(self.export_sources_folder, "src"))
        export_conandata_patches(self)
```
But conan threw error:
```
ERROR: ....: Error in export_sources() method, line ...
        if is_msvc(self):
        AttributeError: 'tuple' object has no attribute 'get_safe'
```
How can I do it correctly?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi,

Exported files or exported sources cannot be conditional to compiler, OS, or any other configuration. Whatever is exported with the recipe must be common to all configurations, in exactly the same way the ``source()`` method cannot be conditional to any configuration. If there is anything that is exclusively for a given configuration, like a patch, it should be applied in the ``build()`` method over the copied sources, not over the original sources.

If you need to export several different files for different configurations, export them under different folders, and then have them used in the ``build()`` method conditionally.
