### ISSUE TITLE
[bug] CMakeToolchain appends default arch flag although user_toolchain is set

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#12848]
### Environment details

* Operating System+version: Win 10
* Compiler+version: GCC arm none eabi
* Conan version: 1.55
* Python version: 3.10.1

### Steps to reproduce

1. clone this repo https://github.com/Ju1He1/FreeRTOSTest
2. add FreeRTOSTest\external\toolchain\Windows\gcc-10.2.1\bin to the path
3. use profiles from \FreeRTOSTest\external and adjust paths in crossbuild profile
4. run conan create . --build missing --profile:host crossbuild --profile:build default -o FreeRTOS:BUILD_TARGET=True

### Logs

[This](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html?highlight=cmaketoolchain#cross-building) says if user_toolchain is set no other CMake Variables and flags are appended.
(or am I mistaken here, if so this is not a bug ;))

However some flags (like -march=armv7e-m+fp and -imultilib thumb/v7e-m+fp/hard) are appended to my build.
I'm guessing those flags come from crossbuild to Arduino.

Actually I need a cross build to an embedded device (arm-none-eabi). I haven't found a generic Arch in the settings. To Arduino was the closest to arm-none-eabi i could find. Is there a more appropriate profile?

**Comment by memsharded** [comment]
I think there is a misunderstanding. The docs say:

> A custom user toolchain file can be added (included from) to the conan_toolchain.cmake one, by using the user_toolchain block described below, and defining the tools.cmake.cmaketoolchain:user_toolchain=["<filepath>"] configuration value.

That means that the ``user_toolchain`` is included (added), to the conan_toolchain, but it doesn't replace it. If you want to fully replace it (at your own risk you will be fully responsible of the toolchain matching the profile), you need to use the ``toolchain_file`` conf instead.

**Comment by ghost** [comment]
Hey @memsharded  thx for your feedback :)
It makes sense that the user_toolchain simply _adds_ flags (not replace them)

I did try out the following 2 steps
1) I did try to use toolchain_file instead of of user_toolchain  but the flag is still appended at some point.
2) Than I went back to use the user_toolchain. When checking the (generated) conan_toolchain.cmake
This (generated) file does **_not_** contain -march=armv7e-m+fp. It only contains my flags


```
string(APPEND CONAN_CXX_FLAGS " -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 --specs=nosys.specs -v -v")
string(APPEND CONAN_C_FLAGS " -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 --specs=nosys.specs -v -v")
```


=> so the question/bug is where is `march=armv7e-m+fp` coming from?



My guess is that conan somehow appends `march=armv7e-m+fp` because I'm using 
```
os=Arduino
os.board=ANY
arch=armv7
```
unfortunately `os=Generic `does not seam to work

This is my current full cross build profile

```
target_host=arm-none-eabi
standalone_toolchain=C:/git/toolbox/cmake/toolchain/arm-none-eabi/arm-gcc-toolchain.cmake

[settings]
os=Arduino
os.board=ANY
arch=armv7
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Debug

[conf]
tools.cmake.cmaketoolchain:user_toolchain=["C:/git/toolbox/cmake/toolchain/arm-none-eabi/arm-gcc-toolchain.cmake"]
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
tools.build:cxxflags=["-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 --specs=nosys.specs -v -v"]
tools.build:cflags=["-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 --specs=nosys.specs -v -v"]

```

**Comment by memsharded** [comment]
> => so the question/bug is where is march=armv7e-m+fp coming from?

Honestly I have no idea. I have searched in the Conan codebase, but I cannot see any place where this could be happening.
So I would say that this is coming from CMake maybe?

Is the project updated with all the necessary changes, so this can be reproduced from the project master branch? Do you see those flags as printed by the toolchain "print-variables" or directly applied in the compiler execution?

**Comment by jwillikers** [comment]
@Ju1He1 Can you share the contents of your CMake toolchain file? I don't believe Conan has any provisions to configure Arm architecture flags. Maybe try removing your CMake cache to be sure nothing is lingering in there.

**Comment by jwillikers** [comment]
@Ju1He1 FYI, Conan doesn't use `Generic` as CMake does, you'd need to use `os=baremetal`.

**Comment by ghost** [comment]
Hey thx both for your feedback. After some digging it turns out that this is not a Conan issue.
For some reason CMake ignores the *_INIT flags in some cases.
If I write my flags directly to CMAKE_CXX_FLAGS it works :)

so this is not a conan issue any more :)
