### ISSUE TITLE
[question] Doxygen dependency on zlib/xapian-core

### ISSUE THREAD

**Issue by rettenbs** [conan-io/conan#12843]
### What is your question?

We want to use Doxygen from Conan Center in our recipe. Since we use the GCC compiler on Windows, the prebuilt packages for `zlib` and `xapian-core` are missing. Doxygen itself removes compiler from the package id but `zlib` and `xapian-core` do not.

Here is our profile:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
```

Some solutions we are currently investigating:
* Fixing the compiler for `zlib` and `xapian-core` in the profile
* Providing `zlib` and `xapian-core` for gcc on our own JFrog server
* Improve the recipe for Doxygen (If `zlib` and `xapian-core` are static libraries, are they real requirements or just build requirements?)
* ?

Any other idea is appreciated.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rettenbs 

Quick question: do you plan/need to use gcc for your whole depenencies? or it is only for doxygen?. What are the reasons for this? MSVC seems by far the most used compiler in Windows in the industry, I am curious about your requirements and decisions to not use it, but use gcc (Mingw I guess?) instead.

If you are planning to build your own binaries with gcc, then certainly building things with your own profiles and storing the binaries in your own server is a recommended approach. I would even suggest to build things from a ``conan-center-index`` fork, not directly from the center, so you achieve full control of dependencies. And it is not very difficult to maintain, I can share some draft and ideas I have in my own branch.

**Comment by rettenbs** [comment]
We mainly develop for embedded devices. Hence, we prefer Mingw for Windows (e.g. for unit tests). We use the Mingw package from Conan Center to setup our toolchain. This works quite well for us and is even easier than installing MSVC.

**Comment by memsharded** [comment]
> We mainly develop for embedded devices. Hence, we prefer Mingw for Windows (e.g. for unit tests). We use the Mingw package from Conan Center to setup our toolchain. This works quite well for us and is even easier than installing MSVC.

Good to know, thanks for explaining!
The downside of it is that many third-party libraries and package recipes in ConanCenter might not build easily with Mingw. ConanCenter builds and test Windows with MSVC, but not with Mingw, so the support of recipes for this compiler might be varying, expect some recipes not work for it out of the box.

**Comment by memsharded** [comment]
Regarding your initial question:

> Providing zlib and xapian-core for gcc on our own JFrog server

This is a good practice for production, for any serious development. Not only for Conan, but other technologies too. Storing a copy of the packages your products need to build in your own server is more robust to network and infra issues, to package breaking changes, and also safer against malware and other malicious and supply chain attacks.
If you are using your own configuration with mingw, then it will also serve as binary storage, avoiding tons of re-builds from source, so very strongly recommended. 

> Fixing the compiler for zlib and xapian-core in the profile

If you are going with Mingw, then the idea would be that all the packages you need are built with mingw, not individual ones. Taking full control of all the binaries is basically the same effort as taking control of only some of them, and it is more robust and consistent. It is recommended to build from a conan-center-index github repo fork, in that way you fully control the recipes too, and you are robust against recipe changes.

> Improve the recipe for Doxygen (If zlib and xapian-core are static libraries, are they real requirements or just build requirements?)

You might need to eventually fix something in recipes so they build cleanly with Mingw. Contributing back these changes if they are reasonable and could be useful for the larger community, without compromising or risking the other configurations,  would be very appreciated.

Please let us know if these clarify a bit the question.

**Comment by rettenbs** [comment]
Thank you for the input. Unfortunately, we do not have the resources at the moment to maintain a complete conan-center-index fork. We created our own Doxygen recipe using the pre-built binaries which works for us.

One note: All other tools we use from conan center (e.g. CMake or Ninja) work out of the box with our setting. Only Doxygen has this issue.

I am closing the issue since we have solution that works for us.
