### ISSUE TITLE
[question] Extending MSBuildDeps?

### ISSUE THREAD

**Issue by illusionistpm** [conan-io/conan#12856]
### What is your question?

I'm trying to migrate from the `visual_studio_multi` generator to `MSBuildDeps` in order to take advantage of per-dependency `.props` files. We are currently running a modified version of `visual_studio_multi` that gets distributed as a Conan package. (There are several modifications, but the biggest is that we have a ton of different "Debug" and "Release" variants, so I need to do a `Contains` on the `Configuration` instead of a straight comparison.)

I've tried to follow a similar pattern to modify `MSBuildDeps`, but I get the below error during `conan install`, presumably because `MSBuildDeps` does not inherit from `Generator`. According to https://docs.conan.io/en/latest/howtos/custom_generators.html, custom generators are a deprecated feature but it's not clear to me what the alternative is. Is there another way I can register my class with Conan?

```
Traceback (most recent call last):
  File "C:\devel\checkout\core-conan\.venv\lib\site-packages\conans\client\generators\__init__.py", line 195, in write_generators
    generator_class = self._generators[generator_name]
KeyError: 'MSBuildDeps_Modified'
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @illusionistpm 

Thanks for your question.
You are right, ``Generator`` base class and global register is being removed in Conan 2.0, so new generators no longer follow that aproach, they do not extend ``Generator``.
User generators need to be implemented inside ``python_requires`` and instantiated explicitly:
```def generate(self):
      mygen = self.python_requires["mygenpkg"].module.MyGen(self)
      mygen.generate()
```
This has several advantages, like controlling the influence of the generator into the binaries with ``python_package_id_mode``.



Also, I guess you have read the ``MSBuildDeps``, that defines attribute ``.configuration``. Is it not enough to redefine it as desired?

**Comment by illusionistpm** [comment]
Thanks @memsharded for the quick response. I was able to get `python_requires` working. 

For whatever it's worth, the downside to this new approach for me is that I have to add more redundancy. Previously I could inject our custom generator via a profile, and then have 1 script that could pass in our typical generators and other settings to whatever conanfile we fed it, but now I need to upgrade any `conanfile.txt` to a `.py`, and add this `generate` block.

I can't find any reference to `python_package_id_mode` so maybe that hasn't made it to release yet.

It's actually the `_condition` method of `MSBuildDeps` that causes me problems.
```
    def _condition(self):
        props = [("Configuration", self.configuration),
                 ("Platform", self.platform)]
        condition = " And ".join("'$(%s)' == '%s'" % (k, v) for k, v in props)
        return condition
```
It always does a straight `==` comparison but for our (somewhat ridiculous) situation, I want to do e.g., `$(Configuration).Contains("Release")`.

I had a few other modifications to the VS generator, but I think if they are still problems, they might be worth contributing back. I'm still investigating.

**Comment by memsharded** [comment]
Closing this ticket as outdated.

Since then, global ``generators`` that can be installed globally in the Conan cache, with ``conan config install``, and used as other generators by name, has been restored in Conan 2.

Please create new tickets if you have any further question or feedback, thanks!
