### ISSUE TITLE
[bug] CMAKE_CXX_COMPILER not defined with tools.build.compiler_executables

### ISSUE THREAD

**Issue by fjp** [conan-io/conan#12853]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: clang++-13
* Conan version: 1.56
* Python version: 3.10.6

### Steps to reproduce

Hi, following up from #10877, I have some troubles to use the new `tools.build.compiler_executables` feature in conan version 1.56. My profile declares to use clang++-13 on Linux Ubuntu 22.04:

```
[settings]
 os=Linux
 arch=x86_64
 compiler=clang
 compiler.version=13
 compiler.libcxx=libstdc++11
 build_type=Release

 [conf]
 tools.build.compiler_executables={"c": "clang-13", "cpp": "clang++-13"}
 #tools.build.compiler_executables={"c": "/usr/bin/clang-13", "cpp": "/usr/bin/clang++-13"}
```

After `conan install` I cannot find where `CMAKE_CXX_COMPILER` was defined. I've expected it to be in either the CMake Presets or conan_toolchain.cmake.

When I execute `conan build .` CMake uses the default c++ compiler instead of clang:

```
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - broken
```

Using the following profile 

```
[settings]
 os=Linux
 arch=x86_64
 compiler=clang
 compiler.version=13
 compiler.libcxx=libstdc++11
 build_type=Release

 [buildenv]
 CC=clang-13
 CXX=clang++-13

 [conf]
 tools.env.virtualenv:auto_use=True
```

clang is detected by CMake correctly:

```
-- Using Conan toolchain: /home/fjp/dev/app/build/generators/conan_toolchain.cmake
-- The C compiler identification is Clang 13.0.1
-- The CXX compiler identification is Clang 13.0.1
```

**Comment by memsharded** [comment]
Hi @fjp 

Thanks for your report.
It seems you might have a typo in the conf. It is not ``tools.build.compiler_executables``, but ``tools.build:compiler_executables`` (note the ``:`` instead of ``.``). Please try that.

(We have introduced validation of confs in Conan 2.0 so this kind of thing doesn't happen)

**Comment by fjp** [comment]
@memsharded thank you for spotting the issue, now it works and I can see the `CMAKE_CXX_COMPILER` is present in the conan_toolchain.cmake.

In my opinion, https://github.com/conan-io/conan/issues/10877 can also be close by this new `tools.build:compiler_executables` feature.

**Comment by memsharded** [comment]
Great! 
Thanks for telling, lets close the other issue too.
