### ISSUE TITLE
[question] Are conf options available in the build method or only the generate method?

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#12861]
### What is your question?

Are `conf` options available in the `build()` method or only the `generate()` method?
This question arose from recent changes in the Boost recipe in CCI that have it use the `tools.build:compiler_executables`  configuration values: https://github.com/conan-io/conan-center-index/commit/7c70998c02260d4e46a3873736da1a941eb6526b#r95305077

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Yes, the ``conf`` is available at ``build()`` time.
I have extended the test in https://github.com/conan-io/conan/pull/12862 to make sure it works for this case.

**Comment by jwillikers** [comment]
@memsharded Thanks! That's really helpful to know.

**Comment by jwillikers** [comment]
@memsharded @SpaceIm I figured out why my profile values weren't taking effect as expected. I thought I could set individual values like so:

```
tools.build:compiler_executables.asm=aarch64-yocto-linux-as
tools.build:compiler_executables.c=aarch64-yocto-linux-gcc
tools.build:compiler_executables.cpp=aarch64-yocto-linux-g++
```

Configuring the values as done for the test code works:

```
tools.build:compiler_executables={"asm": "aarch64-yocto-linux-as", "cpp": "aarch64-yocto-linux-g++", "c": "aarch64-yocto-linux-gcc"}
```

**Comment by memsharded** [comment]
Yes, the correct syntax is a dictionary, not individual values.
