### ISSUE TITLE
How to move the location of the conan.lock file is generated in a multi project workspace

### ISSUE THREAD

**Issue by KingKiller100** [conan-io/conan#12888]
### What is your question?

Conan Version: 1.56.0

Hi,

I am working on a large framework library at my company. We want to break it into smaller modules but keep everything within the same repo/workspace. The directories are split so subdirectories each contain a module of the greater project with their own conanfile.py and the root directory is a facade to combine all the module packages altogether for a consumer.

In each script, I utilize the `layout()` method to keep all the generated files from the generators inside of their respective module by setting the `ConanFile.folders.generators`. 

My issue is that I noticed that generated files such as the conan.lock is created in the current working directory regardless of the module's `layout()` method. For example, if I open a terminal in the root directory and call `conan install fdrA/fdrB -pr ...`, the conan.lock file is located in the root directory whereas the generator's files are created in the directory I specified in *fdrA/fdrB/conanfile.py.*

 Is there a similar way to direct where these types of files should be generated?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @KingKiller100 

Thanks for your question

> In each script, I utilize the layout() method to keep all the generated files from the generators inside of their respective module by setting the ConanFile.folders.generators.

That shouldn't be necessary if using some of the built-in layous, like ``cmake_layout`` it will already define a folder inside that module. Are you using a custom layout? A different build system?

> My issue is that I noticed that generated files such as the conan.lock is created in the current working directory regardless of the module's layout() method. For example, if I open a terminal in the root directory and call conan install fdrA/fdrB -pr ..., the conan.lock file is located in the root directory whereas the generator's files are created in the directory I specified in

Yes, this is one of the annoying things that we couldn't change in 1.X without breaking, so you will need to ``cd module && conan lock ... && cd ..`` or ``conan lock create .. --lockfile-out=module/conan.lock``

We already fixed that in 2.0, and the lockfile will be generated inside the module folder, close to the module conanfile.py, and not in the ``cwd``.

**Comment by KingKiller100** [comment]
The build system we use is the ones supplied by visual studio. We build applications/libraries on an x86_64 windows environment that targets an x86 windows platform using MSBuild compilers toolsets. 

In the modules, I didn't know much about the predefined layouts for visual studio, especially because there are little to no conan docs on that layout. So I went about configuring the directories and settings manually. 

It is very unfortunate that we must wait til the next major conan version for this to be fixed, but I understand the risk and problems with performing breaking changes within minor versions. Definitely something to avoid at all cost for your constomers

**Comment by memsharded** [comment]
> In the modules, I didn't know much about the predefined layouts for visual studio, especially because there are little to no conan docs on that layout. So I went about configuring the directories and settings manually.

Yes, it is true that the ``vs_layout`` is not properly documented yet, sorry about that.
You have the ``conan new hello/0.1 -m=msbuild_lib`` (and ``msbuild_exe`` templates), that would be using it and should work out of the box, if you want to check it.
