### ISSUE TITLE
Incomplete documentation for Autotools support

### ISSUE THREAD

**Issue by absassi** [conan-io/conan#1288]
In [Mastering Conan > Build Helpers > Autotools: configure / make](http://conanio.readthedocs.io/en/latest/mastering/build.html#autotools-configure-make), it is not mentioned the existence of methods `configure` and `make` of `AutoToolsBuildEnvironment`, which are pretty helpful for package writers using Autotools. This gives the impression Autotools support is much simpler than it actually is. These methods appear in [Reference > Build helpers > AutoBoolsBuildEnvironment](http://conanio.readthedocs.io/en/latest/reference/build_helpers/autotools.html#).

In documentation of `configure` method, please mention the implications of omitting `host` (or setting to None), setting it to `False` or to any other value and its relationship with the package settings (especially `compiler` and `arch`). Currently, it only says that None triggers detection from settings. The same applies to `build` and `target`, but note that for these two parameters, it is important for package writers to know what Conan will do with them more precisely.

*Hint:* from [source code](https://github.com/conan-io/conan/blob/develop/conans/client/configure_build_environment.py#L96), if settings are for cross-compilation, it appears `build` comes from OS detection, `host` try to guess something from profile's `os` and `arch` settings to support some ARM cross-compilers and `target` is always omitted.

In documentation of `make` method, please mention parallel builds with automatic detection of processor cores.

**Comment by memsharded** [comment]
Hi @absassi 

I think this is a duplicate (though much better explained and more detailed) to: https://github.com/conan-io/docs/issues/197

We use the docs repo issues for it.

**Comment by absassi** [comment]
Hi @memsharded, I'm sorry, I've missed the existence of conan-io/docs at all. Thanks.

**Comment by memsharded** [comment]
No worries :)
