### ISSUE TITLE
[question] Transitive dependencies using CMakeDeps

### ISSUE THREAD

**Issue by Tobulus** [conan-io/conan#12898]
### What is your question?

Hi,

I have a project A which is build into a package and looks in essence like this:
```
generators = ("CMakeDeps")
requires = ("libbsd/0.10.0", "libsystemd/251.4")

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "both")
        self.cpp_info.set_property("cmake_file_name", "foo")

        # lib
        self.cpp_info.components["libfoo"].set_property("cmake_target_name", "foo::libfoo")
        self.cpp_info.components["libfoo"].set_property("pkg_config_name", "libfoo")
        self.cpp_info.components["libfoo"].libs = ["libfoo"]
        self.cpp_info.components["libfoo"].requires = ["libbsd::bsd", "libsystemd::libsystemd"]

        if self.settings.os == "Linux":
            self.cpp_info.components["libfoo"].system_libs.append("dl")
```
So this one depends on libbsd and libsystemd and the build is working fine.

Now I want to use the contained lib ('libfoo') in another project B and I thought that the 'CMakeDeps' generator is taking care to 'locate' the dependencies but I get this error:
```
cmake] CMake Error at /usr/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
[cmake]   Could not find a package configuration file provided by "libbsd" with any
[cmake]   of the following names:
[cmake]
[cmake]     libbsdConfig.cmake
[cmake]     libbsd-config.cmake
[cmake]
[cmake]   Add the installation prefix of "libbsd" to CMAKE_PREFIX_PATH or set
[cmake]   "libbsd_DIR" to a directory containing one of the above files.  If "libbsd"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
[cmake] Call Stack (most recent call first):
[cmake]   build/.../Debug/Findfoo.cmake:18 (find_dependency)
[cmake]   src/hello-world-lib/CMakeLists.txt:3 (find_package)
```
I think that I'm missing here something ... is there something obviously wrong?
I'm using `find_package('foo')` to use the lib.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tobulus 

I am trying to figure out, but nothing obvious there...

Are you using the ``CMakeToolchain`` in the consumer side? That file helps locating the right ``config.cmake`` files in the right location and with the right priority.

Can you please share the listing of files generated in your folder? (specially those for the bsd library)

**Comment by Tobulus** [comment]
Hi,

thanks for the fast answer!
I can't use the `CMakeToolchain` generator because we are using the cmake-wrapper ... 
```
libbsd-config-version.cmake
libbsd-config.cmake
libbsd-debug-armv8-data.cmake
libbsd-Target-debug.cmake
libbsdTargets.cmake
```
conan version is 1.56.0 by the way.

So the file requested in the error message is actually there ...
In my CMake project I'm adding `${CMAKE_BINARY_DIR}` to `CMAKE_MODULE_PATH` so the file should be discovered?

**Comment by Tobulus** [comment]
Ok, I found the root cause. It's a problem in my setup, but I'm still not 100% what is causing it ...

Before using conan we had a separate ARM rootfs located somewhere under `/opt` where we installed all our dependencies for building. I'm currently removing this to handle everything via conan. For the consumer I forgot to remove the related CMake code (defining SYSROOT etc.) ... could this cause the problem as this is also changing the search path for quite some files?

Thanks again for the fast help, I'm always amazed how fast I get help in the conan/conan-center-index repositories!

**Comment by memsharded** [comment]
> I can't use the CMakeToolchain generator because we are using the cmake-wrapper ...

Yep, that is one of the reasons we don't love the cmake-wrapper, and we will be investigating some other approaches to improve that after 2.0

> In my CMake project I'm adding ${CMAKE_BINARY_DIR} to CMAKE_MODULE_PATH so the file should be discovered?

You might need to add it to CMAKE_PREFIX_PATH too, did you try that too?

> efore using conan we had a separate ARM rootfs located somewhere under /opt where we installed all our dependencies for building. I'm currently removing this to handle everything via conan. For the consumer I forgot to remove the related CMake code (defining SYSROOT etc.) ... could this cause the problem as this is also changing the search path for quite some files?

Absolutely, yes, this could be the issue. The moment CMake paths to locate config/module files is changed or defined, it is very possible that CMake will no longer find the required files.

> Thanks again for the fast help, I'm always amazed how fast I get help in the conan/conan-center-index repositories!

You are welcome! :)
