### ISSUE TITLE
[bug] Can't execute conan search for any version under the null user/channel (_) or without user/channel

### ISSUE THREAD

**Issue by Tails86** [conan-io/conan#12894]
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
* Conan version: Conan version 1.57.0
* Python version: Python 3.8.10

### Steps to reproduce

1. Execute a conan search for a specific user/channel e.x. `conan search 'Package/*@dev/latest' -r remote --raw`
    - This should succeed (just done as a sanity check of provided string format)
2. Execute a conan search for the null user/channel e.x. `conan search 'Package/*@_' -r remote --raw` or `conan search 'Package/*@' -r remote --raw`

### Logs

```
$ conan search 'Package/*@dev/latest' -r remote --raw
Package/1.0.0@dev/latest
$ conan search 'Package/*@_' -r remote --raw
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/conans/client/command.py", line 2216, in run
    method(args[0][1:])
  File "/home/user/.local/lib/python3.8/site-packages/conans/client/command.py", line 1369, in search
    is_reference = check_valid_ref(args.pattern_or_reference)
  File "/home/user/.local/lib/python3.8/site-packages/conans/model/ref.py", line 82, in check_valid_ref
    if "*" in ref.name or "*" in ref.user or "*" in ref.channel:
TypeError: argument of type 'NoneType' is not iterable

ERROR: argument of type 'NoneType' is not iterable
```

**Comment by Tails86** [comment]
Workaround that I implemented:
```
conan search 'Package/*' -r remote --raw | grep -v @
```

**Comment by memsharded** [comment]
Hi @Tails86 

Thanks very much for your detailed report.
I have been able to reproduce, indeed a bug.

As you managed to find a workaround, it doesn't seem critical, and Conan 2.0 has already fixed this, I suggest closing this issue by https://github.com/conan-io/conan/pull/12895, which covers in tests that this works correctly, and assigning it for 2.0 milestone.

**Comment by Tails86** [comment]
That sounds good to me. Thank you for looking into it

**Comment by franramirez688** [comment]
It seems that we can close the issue. Please, don't hesitate to open it again if any other problem appears.
