### ISSUE TITLE
GCC 5 has two incompatible ABIs to the standard library.

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#129]
Raised by @TyRoXx 
"need a setting to choose which one I want. Or arbitrary compiler flags."

Thats true. Could be fixed with boolean setting (nested to gcc 5): _GLIBCXX_USE_CXX11_ABI. 

But probably it is time to consider allowing arbitrary compiler flags (though that would practically always lead to building from sources as typically no pre-built binary would match). Probably something to handle together with #124

**Comment by TyRoXx** [comment]
Arbitrary flags could be set like this:
``conan install -s cxx_flags=-D_GLIBCXX_USE_CXX11_ABI=0``

This feature would be useful for debugging and testing, too:
``conan install -s cxx_flags="-fsanitize=memory"``

**Comment by memsharded** [comment]
I have commented in related issue https://github.com/conan-io/conan/issues/138 about a possible solution, please check it and give feedback if possible.
