### ISSUE TITLE
How do I use build_requires in the build step

### ISSUE THREAD

**Issue by edahlseng** [conan-io/conan#12901]
### What is your question?

I must be dense, I'm having a tough time figuring out how to actually use `build_requires` to pin build-time dependencies. Here's what I'm trying:

```
class Test(ConanFile):
    name = "build-requires-test"
    version = "1.0.0"
    build_requires =  "make/4.3"

    def build(self):
        self.run("make -v") # This prints a version that is _not_ 4.3, but is my system's default make version
```

Am I neglecting a key step, or expecting this to work different from how it actually does? I oddly can't find any documentation or similar issues on this which makes me wonder if I'm misinterpreting what `build_requires` can be used for?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @edahlseng 

Thanks for your question.
It seems you are missing the ``generators = "VirtualBuildEnv"``. This will generate a script file that when activated will put the ``"bin"`` folder of the build dependencies in the path. You can see it by adding, run ``conan install .`` and reading the generated files. The ``self.run(..., env="conanbuild")`` default, will execute prepending the generated script.

To make sure you are using the 2.0 ready tools, you should be checking https://docs.conan.io/en/latest/reference/conanfile/tools.html (there is an ``environment`` section there too).

Please try that and let us know.

**Comment by edahlseng** [comment]
Hi @memsharded, aha! Thank you very much.

I had tried adding `generators = "virtualbuildenv"` (all lower case) earlier, based on some documentation I found somewhere, but I see that `generators = "VirtualBuildEnv"` (PascalCase) behaves differently and does exactly what I need.

Cheers!

**Comment by memsharded** [comment]
Yes, the docs right now are a bit confusing, while preparing the transition to 2.0. This is the section you want to keep an eye: https://docs.conan.io/en/latest/conan_v2.html for other things that might be legacy.
