### ISSUE TITLE
[feature] Authenticate against disabled remote

### ISSUE THREAD

**Issue by slietzau** [conan-io/conan#12909]
### What is your suggestion?

We have several remotes we use for different maturity levels. The most volatile one should be disabled by default.
We use `conan config install` to distribute the configuartion internally. Because we have a number of remotes we also automate the authentication to the remotes with a script so the user has to input his password only once.
Trying to authenticate with a disabled remote however fails with an error that the remote is disabled.

This combination makes it awkward to implement our workflow because we have to first authenticate against all remotes and then call `conan remote disable` for all that should be disabled. It would be better to define remotes as disabled in `remotes.json` but still allow `conan user` to authenticate against them.

I tried both `1.X` and `2.0.0-beta8`.
On a side note: is it expected, that `2.0` doesn't list disabled remotes with `conan remote list`? The only way I found was to open `remotes.json` in a text editor.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @slietzau 

Thanks very much for your suggestion.
I think it makes sense, both things:
- ``conan remote list`` should probably list all remotes, or at the very least have options to display disabled ones
- I don't see a strong reason to not allowing authentication against a disabled remote, as long as it is not for resolution, I am fine with it.

Lets discuss with the team, and we might be able to have it in next 2.0-beta.9

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12937 and #12913, for next beta.9
