### ISSUE TITLE
[feature] add XCode version to settings.yaml

### ISSUE THREAD

**Issue by andreya108** [conan-io/conan#12919]
### What is your suggestion?

Hi! 

I suggest adding xcode_version to settings.yml to be able fit concrete version of XCode required for the profile.

Currently only version of apple clang can be selected in conan settings, but there are situations when different XCode version have the same compiler:

Xcode 14.2
Apple clang version 14.0.0 (clang-1400.0.29.202)

Xcode 14.1
Apple clang version 14.0.0 (clang-1400.0.29.202)

Xcode 14.0.1
Apple clang version 14.0.0 (clang-1400.0.29.102)

Xcode 14.0
Apple clang version 14.0.0 (clang-1400.0.29.102)

The problem arises on CI build agent to select correct version of XCode before build.
There is no chance to deduce XCode version from clang version set in a profile.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @andreya108 

Thanks for your request.
We would need to understand why the XCode version is needed. If the compiler is the same, the binary will be the same. The ``settings.yml`` encode the "binary model", so encoding the compiler version should be enough to model the binaries, it doesn't matter what version of Xcode creates it, it will be the same binary.

Recall that it is possible to customize and extend the ``settings.yml`` if you need them for some specific use case, please check: https://docs.conan.io/en/latest/extending/custom_settings.html

**Comment by andreya108** [comment]
@memsharded 
My position is that XCode contains not only compiler but also headers, libraries and other build tools.

Suppose an extensive graph of dependent packages which has been built with the same version of compiler, but different versions of XCode.
I have no idea what is changing across different minor XCode version and how that changes may interfere.

But the thought that all my components are built with exact the same XCode version and it is stored in package info for future investigation (if some toolchain bug will be caught) makes sense and eliminates some mess in CI pipeline.

We for sure are going to extend our settings.yml with xcode_version, but I suppose it can be useful for other conan users too. This is the reason of creating this feature request.

**Comment by memsharded** [comment]
> We for sure are going to extend our settings.yml with xcode_version, but I suppose it can be useful for other conan users too. This is the reason of creating this feature request.

Yes, there is always a balance in the default settings.yml between an exact binary model and a pragmatic binary model that avoids the combinatoric explosions of different binaries. As long as the binaries are fully compatible, the default settings do not model minor versions of things like this. Sometimes they are made available for chosing, but not really used by default, unless users explicitly opt-in.

So far we have not been reported any incompatibility or even a relevant variation of the things included in Xcode. It is also possible that such things are not that included by default, and might only be active for some special type of applications? I am thinking things like GUIs, etc? So most of C/C++ general purpose libraries do not actually use Xcode specific headers or libraries, but just the compiler standard ones?

**Comment by memsharded** [comment]
Closing as not planned.

If users want to add specific Xcode versions to settings, it is very straightforward with custom settings, and now with the ``settings_user.yml``. 
Please create new tickets if you have any further feedback, thanks.
