### ISSUE TITLE
[question] Package-specifc configuration changes in Conan 2.0

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#12917]
Hi there,

As part of our ongoing evaluation of the upcoming Conan 2.0 release (looking great BTW), I've come across a scenario with a couple of our private packages that I would like a bit of clarification as to how we might best handle under Conan 2.0.

As some of our private packages produce very large outputs, including PDBs which we also package, we have found that adjusting the GZIP compression level via the `CONAN_COMPRESSION_LEVEL` environment variable allows for much improved performance during the upload phase of their (frequent) CI builds. For all our other packages we do not set the environment variable and hence they use the default value provided by Conan.

Under 2.0 I can see Conan configuration has moved entirely to the `global.conf` file and in this case we would presumably need to set the `core.gzip:compresslevel` property accordingly.

The question we have is what is now the correct way to do this on a per-package basis? `core` properties are global and cannot be overridden in profiles etc. Is the expectation that we adjust the property via a `conan config install` command using a local `global.conf` file in the repo? I could envisage a scenario where that may cause issues for some users as the altered config may then apply for subsequent builds which don't necessary want/expect it (though in our case it wouldn't be an issue given we use Docker containers for building i.e. the config is reset between builds).

Ultimately it appears that with Conan 2.0 and the removal of environment variable-driven configuration, there is no longer a simple way to make transient configuration changes, for `core` properties at least?

Look forward to your input.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @santhonisz 

Thanks for your question.
I have a quick question: how do you set ``CONAN_COMPRESSION_LEVEL`` env-var per package? It seems that such env-var is global, not per-package, because it is not applied in the "recipe" processing context, but internally in Conan. I guess that you set it in the process creating those packages, but it is not a profile one?

**Comment by santhonisz** [comment]
Hi @memsharded 

We set the env var as part of our CI build pipelines for the packages in question, hence it can be adjusted per-package.

Cheers.

**Comment by memsharded** [comment]
> We set the env var as part of our CI build pipelines for the packages in question, hence it can be adjusted per-package.

Ok, that makes sense, I though you meant some ``pkg_patttern*:env_var=value`` Conan per-package env-var (legacy) definition.

**Comment by memsharded** [comment]
As a first possible approach, the new ``global.conf`` file in 2.0 is also a jinja template. 
It should be doable do something like:
```
core.gzip:compresslevel = {{os.getenv("MYCOMPRESSLEVEL", 9)}}
```
And that way you already control again the value based on your own env-var

**Comment by santhonisz** [comment]
Perfect - that's absolutely what we were after!

Thanks again for the prompt response.

**Comment by memsharded** [comment]
Great then :)

I'll close this ticket as responded then.
I will be checking other alternatives to define ``core`` confs in command line too, but this is exploratory, not sure if it will be possible.
