### ISSUE TITLE
[bug] unzip gets stuck and never returns

### ISSUE THREAD

**Issue by lpapp** [conan-io/conan#12922]
### Environment details

* Operating System+version:
* Compiler+version:
* Conan version:
* Python version:

### Steps to reproduce

I have this in my recipe (source method):

```
from conan.tools.files import unzip

            cygwin_git = Git(self)
            cygwin_git.clone(url='git@gitlab.foo:cygwin.git')
            tarball_file = os.path.join(self.source_folder, 'Cygwin', 'cygwin64.tgz')
            unzip(self, tarball_file)
```

It seems that the extraction has actually happened, but the unzip process never returns.

This is happening on Windows 10 using the Visual Studio 2022 prompt. I am using conan 1.57.0.

**Comment by memsharded** [comment]
Hi @lpapp 

Does this happen with every tgz out there or only with that specific one?
I am trying to reproduce, but the ``git@gitlab.foo:cygwin.git`` url obviously doesn't work. If you have some URL with a tgz we could use to try to reproduce, that would help a lot, thanks.

**Comment by memsharded** [comment]
I am closing this ticket as staled, if you still need help, please re-open or create a new ticket. Thanks.
