### ISSUE TITLE
[feature] Add support for specifying the bash path on Windows

### ISSUE THREAD

**Issue by lpapp** [conan-io/conan#12924]
### What is your suggestion?

As a conan user,
I would like to be able to specify the bash path in my conan recipe for Windows,
so that I can build auto tools project in a specific recipe.

---

https://github.com/conan-io/conan/issues/12920 seems to claim that it is a conf. However, I do not want to touch a global conf. I want to make this change specifically for the recipe because this change only makes sense for that particular recipe, so it should be done where it belongs, not in an entirely different place.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi! Sorry that we didn't get back to you sooner - The mentioned conf seems to properly solve your use-case. `tool.` confs can be scoped per-reference using the `libname/*:tool.conf:name=value` syntax, which allows to specify them only to certain places.

under my point of view, defining in the recipe itself the path for the bash executable can be dangerous when sharing it to other developers who might have it in different places. 

An alternative is to depend on the tool as a tool_requires, which can modify the confs of their direct dependencies, such that for example the `msys2` recipe in Conan Center Index defines the following:
```
        self.conf_info.define("tools.microsoft.bash:path", os.path.join(msys_bin, "bash.exe"))
```

So its dependants have access to its bash executable without further changes.

Hope this helps, feel free to reopen/create a new issue should anyone have additional questions, thanks! :)
