### ISSUE TITLE
Scopes not being set

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1292]
Hi,

In 0.22.3, I am trying to use scopes for the first time.  But I cannot seem to set a scope at all.

My install line is: `conan install --build=Boost --scope foo=bar Boost/1.61.dv02@boost/external2`, but in the script (or in the debugger), `self.scope.foo` always is `None`.  I also tried putting a `[scopes]` section in a profile, with the same result.

What am I missing?

**Comment by memsharded** [comment]
I think you need to use the ``--scope Pkg:foo=bar`` syntax, or to apply to all packages ``--scope ALL:foo=bar``.

In any case, what are you trying to achieve with scopes? To me they are a bit "legacy", in the sense that they were introduced very early in conan when environment variables weren't a thing. Now, I'd say that the support for environment variables is much better, and better understood by many people, so it seems that most conan users tend to use them (and not scopes).

**Comment by tamboril** [comment]
Hi,

I have a package, `Boost`, which has _all_ the boost libraries in it.  When I consume it, it's really convenient to just use the `CONAN_PKG::Boost` target to set all the include and lib paths (and libs) for a target.

But this causes my target to link with every boost shared library, and I don't want that.

Because there's only one `cpp_info.libs`, I was thinking of controlling it with a scope in `package_info()` so that the resulting `CONAN_PKG::Boost` would have fewer libs in it.

I'll try the explicit scope setting you suggested, but in the meantime, I made a package `MiniBoost` with a `build_requires` of the main `Boost` package, and I copy a subset of files from `self.deps_cpp_info['Boost'].lib_paths[0]` (similar for includes).   This works, but it would be nice to have the Boost `conanfile.py` have a scope for `mini-mode`.

**Comment by memsharded** [comment]
Maybe I am missing something, but why not just filtering in the consumer side? You have a list of libraries, either in ``${CONAN_LIBS}`` or in the ``CONAN_PKG::Boost`` target. Why not just overriding/filtering with the libraries you know you are linking with? A couple of lines of CMake could do it.

If you want to add specific information of libraries, you might use the multi-config info, and do something like:

```python
def package_info(self):
     self.cpp_info.regex.libs = ["regex", "thread", "mpl"] #just an example, I don't know real deps
     self.cpp_info.filesystem.libs = ["thread", "log"]
     ...
```

Those will be later translated to CMake vars like ``CONAN_LIBS_REGEX``, that you might directly use to define your libs. However, if you are using more than one, you probably have to merge (in order) the respective lists, which is not something straightforward.

**Comment by tamboril** [comment]
I missed noticing the multi-config feature when it came out.  It looks like it will do what I want, with some cmake code to make a new interface library. I need to deconstruct the generated interface library and build up a new one with my desired subset of `INTERFACE_LINK_LIBRARIES`.

What would be really useful is if that were done for me in the cmake generator so that a new target would be defined in `CONAN_PKG::` for any multi-config I added.  In your example, there would be a `CONAN_PKG::Boost::regex`, or something similar.

**Comment by memsharded** [comment]
Could be an idea. What would be the relation, if any of the CONAN_PKG::Boost::regex, with the CONAN_PKG::Boost target? For the debug/release case, that was the main reason for multi-config, the info is already translated to the CMake targets with the cmake generators expressions. Are generator expressions flexible to do so, so we could parameterize the CONAN_PKG::Boost target with several configs like regex, thread, etc? Don't have the necessary cmake-fu, but may be possible.

**Comment by tamboril** [comment]
After some experimentation, I've come back to your original idea of filtering in the final consumer.  Even if we could do something with multi-config and generator enhancements, a library provider could not forsee all possible permutations of scopes of their library by its consumers.

The final consumer can simply do as you said with a couple llines of CMake:
```
# trim down the larger libraries which we directly or indirectly require
get_target_property(L CONAN_PKG::Boost INTERFACE_LINK_LIBRARIES)
list(FILTER L INCLUDE REGEX "program_options|locale|regex|context|system|iostreams|serialization")
set_property(TARGET CONAN_PKG::Boost PROPERTY INTERFACE_LINK_LIBRARIES ${L})
```

**Comment by memsharded** [comment]
Looks good, and agree. 

The root issue of this is the monolithic nature of boost (due to the historic lack of package manager, in turn). If Boost was properly split in conan packages, many things would be much smoother. I guess it might eventually happen.

In the meantime, as you said, it is not easy for a Boost package to foresee any consumer pattern, so probably the best is to let consumers filter the libraries they want to link with.

Could this issue be closed then, or something else we could help?
