### ISSUE TITLE
[feature] Allow custom naming of presets

### ISSUE THREAD

**Issue by WernerWessely** [conan-io/conan#12933]
### What is your suggestion?

First of all: Thanks for everything you guys do with Conan!

Here is my use case: I have profiles which are not used for packaging but only for unit testing and other testing.

Our workflow will be pretty standard:
1) Install one or multiple profiles
2) Use the CMake presets generated by Conan to configure/build/test the project.

The problem:
We have several different unit testing / testing profiles, all of which run on the same platform and use the same compiler etc.
The only way these builds differ is usually different CMake variables (which we will have to set using different user toolchain files with `tools.cmake.cmaketoolchain:user_toolchain` in the profiles).
So using `build_folder_vars` does not really make much sense since I can only use the package settings/options for naming which have nothing to do with testing.

Is there any other way to customize the generated preset name that I am not aware of? Maybe in Conan 2.0?

perhaps something like `tools.cmake.cmaketoolchain:preset_name` could be introduced? Maybe even with a format string?

PS: 
I know there is the option of using only one profile and doing something like:
- Write some presets manually which extend the ones generated by conan
- Or set the CMake variables manually when calling the preset
But both would be more complicated for everyone involved.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @WernerWessely 

I am working in https://github.com/conan-io/conan/pull/12932, to introduce a ``CMakeToolchain.presets_prefix`` to introduce a custom prefix to preset, for example, "conan", so presets are called "conan-debug", "conan-gcc-11-release", etc, so they don't conflict with user names and can be inherited. 

Check the unittest in https://github.com/conan-io/conan/pull/12932, I think this implements your flow?

**Comment by WernerWessely** [comment]
@memsharded Yes, that sounds like something I could use. Will it be available before Conan 2.0? I guess we can close this.

**Comment by memsharded** [comment]
Yes, it is for develop branch, will be in 1.58 if moves forward (still to discuss). We can close if the PR gets merged.

**Comment by elvisdukaj** [comment]
I had the same issue: I am trying to create a Conan package and build both for android and for native.

I used the following command:
`conan install . --profile android --settings=build_type=Release --output-folder=android_out`
`conan install . --profile native --settings=build_type=Release --output-folder=android_out`

Now I have two preset named "conan-release". Is there a way to avoid this?

**Comment by memsharded** [comment]
Hi @elvisdukaj 

Have you tried defined your ``build_folder_vars`` to contain the ``os``? That should create different presets for android and for native.

**Comment by elvisdukaj** [comment]
I didn’t try! So I’ve to pass these values in the command line or in the global.conf if I understood it correctly

**Comment by memsharded** [comment]
> I didn’t try! So I’ve to pass these values in the command line or in the global.conf if I understood it correctly

Yes, command line, profile, global.conf are possible.

Also, there is a ``build_folder_vars`` now in recipes too, in ``self.folders.build_folder_vars`` (https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html?highlight=build_folder_vars) if you want to hard-code it in the recipe.

**Comment by elvisdukaj** [comment]
Adding the following code in my recipe:

```Python
def layout(self):
    self.folders.build_folder_vars = ["settings.os", "settings.compiler", "settings.compiler.version", "settings.arch", "settings.build_type"] 
    cmake_layout(self)
```

Works just great... and it's also nice that now in the build directory every build has a different folder to don't mix with the others :)

**Comment by memsharded** [comment]
Fantastic! Thanks for the feedback.

Maybe we can close the ticket as resolved then?
