### ISSUE TITLE
[bug]  VirtualBuildEnv does not propagate transitive runenv_info

### ISSUE THREAD

**Issue by liarokapisv** [conan-io/conan#12939]
### Environment details

* Operating System+version: `Manjaro Sikaris 22.0`
* Compiler+version: `gcc-12.2.0`
* Conan version: `conan 2.0.0-beta8`
* Python version: `3.10.8`

### Steps to reproduce

I stumbled upon this while trying to port my `build_require` package to conan 2.0.

The basic gist of it is:
- package `A` defines runenv_info `TEST`
- package `B` requires `A`
- test_package of `B` build_requires `B`.
- we create package `A` normally
- we create the package `B` with `--build-require` for convenience.

We expect that the generated `conanbuildenv...` script in `B`'s test_package folder will have `TEST` defined.
This works properly on `Conan 1.57`,  but not on `2.0.0-beta8`

I have uploaded a small demonstration repository [HERE](https://gitlab.com/aliarokapis/conan_virtualbuildenv_possible_bug)

**Comment by memsharded** [comment]
Hi @liarokapisv 

I have been investigating this, thanks very much for putting together a repo, that really helps.

There is an issue with the definition of the problem. The ``pkgb`` ``test_package`` is not doing anything with the ``pkgb`` library. It contains an empty ``main(){}`` function. 
If it is defining the ``self.tool_requires(self.tested_reference_str)`` explicitly, it should also define ``test_type = "explicit"`` in Conan 1.X.
It is also not possible to use libraries as ``tool_requires`` and link with them. Tool requirements are for tools, executables, that need to run while building the consumer, but they belong to the "build" context, and not to the "host" context. To validate that a ``tool_requires`` is working, it would be better to use it in the ``test_package/conanfile.py`` ``build()`` method, in the same way that a ``tool_require`` would be expected to be used in reality.

Please let me know if this helps. Then, it would be great to have the project updated so it reflects a more realistic working example in Conan 1.X, and then we can check if it behaves correctly in 2.0 or something is missing (sometimes it is just a matter of defining some ``package_type = "application"`` for example, but better to have the full repro case, and work on it). Thanks!

**Comment by liarokapisv** [comment]
Hi James.

> The pkgb test_package is not doing anything with the pkgb library.

I know, I just care about it's virtualbuildenv environment. I could perform the env variable test in the root cmakelists if that's any better but I don't think that this is that important, we can simply inspect the virtualbuildenv file.

> It is also not possible to use libraries as tool_requires and link with them. Tool requirements are for tools, executables, that need to run while building the consumer, but they belong to the "build" context, and not to the "host" context.

I am aware, I don't think I am doing anything like this in the repo. I am simply using the packages to showcase the runenv_info propagation of transitive dependencies specifically with the VirtualBuildEnv generator. Both libraries are placeholders created with the cmake_lib template and they have the bare minimum needed to showcase just this behaviour.

The actual use-case deals with a protobuf generator requiring `protoc` in it's path through the protobuf package.

**Comment by memsharded** [comment]
Ok, good, let me try to setup a simple test in our test suite that covers this case and see what happens.

**Comment by memsharded** [comment]
Hi @liarokapisv 

I have done a test in https://github.com/conan-io/conan/pull/12948 that captures the behavior for Conan 1.X. 
It is true that this test fails if moved as-is to the 2.0 branch. When this is merged to develop2, we will do the necessary changes.

When you execute this test in 2.0 ``develop2`` branch you will see that in the second ``create``, the ``lib`` package is marked as "skip", that means the model in the dependency graph knows the binary is not needed and it is avoiding fetching/downloading/using the binary. That means that the ``runenv_info`` of that package is also not taken into account (a skipped package does not provide information for runtime, as it is simply not there.

In Conan 2.0, if we want to model this relation, there are different ways:
- Marking "lib" as ``package_type = "shared-library"`` (or if it defines a ``shared=True`` option)
- Defining the ``run=True`` trait in "tool", something like: ``self.requires("lib/0.1", run=True)``

When this test is merged in the "develop2" branch, I will add either of those things to make the test pass, and add a comment explaining it.

Please let me know if this clarifies the issue.

**Comment by liarokapisv** [comment]
Thanks James.

It seems the source of this issue was me not getting up to speed with the improved dependency graph model and the effect of the various traits (and therefore the package_type attribute). It didn't help that this is not really given much weight in the migration guide, I did not expect that the package_type could affect recipe behaviour that much. I watched the uploaded talk and now everything is much more clear. 

Regarding package types, it seems some packages like the aforementioned `protobuf` package are really a mix of both executable and library. Is there a recommended package type for such packages?

**Comment by memsharded** [comment]
> Regarding package types, it seems some packages like the aforementioned protobuf package are really a mix of both executable and library. Is there a recommended package type for such packages?

I would probably define it (or not necessary, if it already defines the ``shared`` option) as a ``package_type = "library"`` (that can be both a ``shared-library`` and a ``static-library`` depending on the option). I expect ``protobuf`` to be always used as a library, and sometimes as a ``tool_requires`` for the ``protoc`` application. It is likely that the implicit traits in ``tool_requires(build=True, headers=False, libs=False, run=True, visible=False)`` will be enough to do the right thing for it as an executable.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12948, I will merge it to ``develop2`` branch for 2.0 with the addition commented above.
