### ISSUE TITLE
[feature] Ability to show dependency graph with missing packages

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#12938]
### What is your suggestion?

Using conan 1.57.0, calling `conan info --json conan-info.json` on a conanfile, will fail and NOT produce any output when called on a consumer recipe.
It would be very helpful to be able to tell the information up collected up until the failure point at least, to aid in determining what the issue is.

Currently it will just abort, throw the hands in the air and be like "nah I cannot find x, I won't tell you anything".

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

This has already been implemented this way in Conan 2.0 with ``conan graph info`` command, so closing this ticket as solved in 2.0 milestone. Feedback about it welcome, thanks!
