### ISSUE TITLE
What is the correct way enable or disable unit test

### ISSUE THREAD

**Issue by ashley-b** [conan-io/conan#12947]
### What is your question?

What is the modern conan v2 way of enabling/disabling building and running  of unit test from with in a recipe.
I see mixed answer to this problem, using env CONAN_RUN_TESTS, self.should_test or config "tools.build:skip_test"

Or is it preferred that unit test's are not run from conan

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by ashley-b** [comment]
As a follow up I did find this HOWTO https://docs.conan.io/en/latest/howtos/header_only.html#with-unit-tests, but it seams out of date with best practices and this related issue #8102

**Comment by memsharded** [comment]
Hi @ashley-b 

Thanks for your question.
The new integrations like ``from conan.tools.cmake import CMake`` (as opposed to the legacy ``from conans import CMake``, do not listen anymore to env-vars for configuration, and only to the new ``conf``. Conan 2.0 has dropped most env-vars, and it will be mandatory to use ``conf``. So if you are using the new integrations (recommended, to be 2.0-ready), you should be using ``tools.build:skip_test``. Furthermore, this conf is also used to disable the build of tests in the ``cmake.build()`` step.

It is perfectly fine that recipes run ``cmake.build()`` and ``cmake.test()`` to build and run unittests, that allows comprehensive testing of the package being built, and the ``conf`` is there to disable it if not desired for some builds.

**Comment by ashley-b** [comment]
Thanks @memsharded for the quick and detailed response, that clears up the confusion.

**Comment by memsharded** [comment]
thanks for the feedback, then I think we can close this ticket, but don't hesitate to open new ones for any further question.
