### ISSUE TITLE
[develop2] [feature] Consider adding first X chars or package name into the cache folders hashed paths

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#12952]
### What is your suggestion?

This will really help when debugging and reading compiler output like:
```
gcc -I/home/hash1/include -I/home/hash2/include -L/home/hash3/lib ....
```
And have more something like:
```
gcc -I/home/zlib_hash1/include -I/home/bzip2_hash2/include -L/home/openssl_hash3/lib ....
``` 

To take into account:
- reduction in entropy? 
- We shouldn't make paths larger than the current ones, without risking long paths overflows in Windows

cc @thorsten-klein

**Comment by memsharded** [comment]
We have been checking with the team and there are some concerns about entropy reduction and possible collisions, or overflowing the path lengths. This situation is aggravated by the fact that there are many libraries starting with ``openxxx`` or ``libyyy``, so the overlap will be higher, the risk higher and also the paths seen will be useless, because ``path/openhash1`` ``path/libzhash2`` could be to ``openssl``, ``opencv``, ``openai``, ``libzstd``, ``libzcat``, and so on. So this seems a bit risky for the value, which is to improve the UX.

Instead, we can provide a reverse lookup, similar to ``conan cache path <ref>`` returning the path, a ``conan cache ipath <folder>`` that returns the reference of the stored object. This is doable and it might help to debug and support cases like the above when ``gcc -I/home/hash1/include -I/home/hash2/include -L/home/hash3/lib`` is not that explicit about the libraries being included and linked (and hopefully, it is that frequent of a use case). It will also be a "full" solution, in the sense that it will return the full reference, including the version, recipe revision, package-id, etc, instead than just the name.

Moving this to 2.X scope (not urgent issue), the recommendation is:
- To implement ``conan cache ipath <folder>`` command, where ``folder`` can be either the full path or just the hash,  to return the reference of the object contained inside (full name, version, recipe-revision, package-id, etc)

**Comment by thorsten-klein** [comment]
I am maybe not deep enough into the impact of this change. 
How does an additional folder affect entropy?
The windows path length is limited by maxchars, not by depth, isn't it? 

For us this cryptic include paths would be a real pain point when switching to conan 2.0.

The path with conan 2.0 is something like `/CONAN_HOME/p/ad14395562c66027/p`
Is it really not possible to add one folder anywhere in path, e.g. `/CONAN_HOME/p/opencv/ad14395562c66027/p`.
In contrast to this it was in conan 1.x `/CONAN_HOME/p/opencv/1.2.3/development/test/package/901aed1ab7179b92de7c6c800fed2d601267c795/`

If it really does not work: Can we have some setting `cache_path_contains_name` for this (which is by default `False`but can be set to `True` in `conan.conf`)?

**Comment by memsharded** [comment]
> How does an additional folder affect entropy?

The current hash length is calculated to support building of libraries that have long paths in Windows. If we make the hash larger (or the base path larger) it might hit the limit for some users

> The windows path length is limited by maxchars, not by depth, isn't it?

Yes, we did an estimation for the average user names, and the required length of libraries with long paths, and decided that we can use around 13 chars for the unique identifier, it doesn't matter if a single folder or multiple folders. 

The reason that we chose ``C:/.conan`` as a base folder in Conan 1.X to store the "short_paths" packages, necessary for more than 100 libraries in ConanCenter, and very often in private usage (in my experience, private packages tend to have longer names than open source), is because there is not much margin to hit the limit. Adding the full package name is not possible in practice (regarding the above, the typical package name in companies is CompanyTeamProjectComponentALibB), and taking the first few X characters would render useless in practice.

> If it really does not work: Can we have some setting cache_path_contains_name for this (which is by default Falsebut can be set to True in conan.conf)?

This feature might be possible, but it might also more challenging than it seems and have more rough edges than expected, because now in Conan 2.0 package references are stored in a DB too, so any change in the conf files would render the DB broken, or require a non trivial migration. Also, as commented above, just using the full package name will cause length path limit hits in Windows, and then users wanting a conditional conf that only works in linux systems, but not in windows... At the moment it seems too much for the value, so I still think we should provide the reverse mapping command utility, and lets see how it goes, and then revisiting this conf later after some more heavier real world usage of the 2.0 cache.

**Comment by thorsten-klein** [comment]
How can users currently work in Windows if the path issue is so critical? 
I mean, it seems to work anyhow for current paths like `C:/.conan/data/opencv/1.2.3/development/test/package/901aed1ab7179b92de7c6c800fed2d601267c795/` ?
So any shorter path will be an improvement at all (`C:/.conan/p/opencv/901aed1ab7179/`) ?

Nevertheless, even a short path is no guarantee, since inside the package folder files could be in nested folders and reach the limit by this. 
Do you have any overview how many packages would be affected in Windows if the path is ~15 chars longer (the estimated default length of names)?

Sorry to be so pushy. I am just afraid that this is really a breaking point when thinking about a way to 2.x - not only for us but also for many other Linux users

**Comment by memsharded** [comment]
> I mean, it seems to work anyhow for current paths like C:/.conan/data/opencv/1.2.3/development/test/package/901aed1ab7179b92de7c6c800fed2d601267c795/ ?

Because with the ``short_paths=True`` feature, that folder does not contain the package or any file. It contains a ``.conan_link`` file, containing the folder ``C:/.conan/<6charactershash>``. Yes, only 6 characters hash + the length of ``.conan``.

I don't know by heart how many packages will be affected if we increase 15chars the path, but I am sure some will be affected. And for those affected it will be a total blocker, as now there will be no ``short_paths`` feature to workaround it.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/13011 for beta.9.
We used an opportunity of shortening a path 2 chars down in another place, and decided to move forward with adding first 5 chars of the package name to the hash.

**Comment by thorsten-klein** [comment]
Sounds good to me for the beginning :-) 

Do you consider to make the `5 chars` adaptable via some config in future?

Many private repositories or companies have some prefix for their components to point out that it is some internal component, e.g. "<company>-myliba". In worst case, the company is `foobar` (6 chars long), so all packages will be `fooba<hash>`. In this case it would help the company to change it to `10 chars name + 8 chars hash` (on their own risk that a reduction of hash length will lead to conflicting names). 
Or even better: always keep the 13 chars hash --> `10 chars name + 13 chars hash = 23 chars in sum (instead of 18)`

**Comment by memsharded** [comment]
> Do you consider to make the 5 chars adaptable via some config in future?

This adaptability is not trivial. It requires a migration over the cache storage and cache DB, which will probably be difficult to achieve robustly, and would lead to painful support tickets and debug sessions. So maybe in the future, but at the moment would be too much.

The recommendation, and we will make it explicit in the docs is that the ``foobar`` company name should be the "user" part, and package names should be short, concise and meaningful (similar to Python package/namespaces conventions).
