### ISSUE TITLE
[bug] Visual Studio properties missing for statically linked libraries

### ISSUE THREAD

**Issue by illusionistpm** [conan-io/conan#12954]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: Visual Studio 2022 (17.4.0)
* Conan version: 1.57.0
* Python version: 3.10.2

### Steps to reproduce

The `MSBuildDeps` generator doesn't create the necessary properties for statically linked libraries. It creates a `Link` block which is suitable for dynamically linked projects, but is missing the `Lib` block needed for static libs. I've created a small project to demonstrate and opened PR #12956 with my proposed solution.

1. Extract [MissingLibDemo.zip](https://github.com/conan-io/conan/files/10481747/MissingLibDemo.zip)
2. In the `StaticLib` folder, create a `conan` directory
3. From `StaticLib/conan`, run `conan install .. -g=MSBuildDeps --build=missing`
4. Open `MissingLibDemo.sln` in Visual Studio and build `Release` / `x64`.
5. Note that `ConsoleApp` fails to link with `error LNK2001: unresolved external symbol deflateInit_`
6. Right click `StaticLib` / `Properties` / `General` / `Configuration Type` - change to `Dynamic Library`
7. Build again
8. Notice the successful build
9. Switch `StaticLib` back to `Static library`
10. Close the solution
11. Edit `StaticLib/conan/conan_zlib_release_x64.props`. Copy and paste the `Link` block and rename `Link` to `Lib`
12. Reopen the solution and build
13. Notice that the build is successful

**Comment by memsharded** [comment]
Hi @illusionistpm 

I think I have figured out what is happening:
- ConsoleApp project depends exclusively on the StaticLib project, but no other information about other dependencies, like zlib one
- StaticLib is using zlib, but it is not subsuming/embedding the zlib library into itself. This is the most common practice while managing static libraries.
- When ConsoleApp is linking against StaticLib, without further information, it doesn't know how to locate and link with the necessary zlib static library, so it fails.

The solution is to add the MSBuildDeps generated .props files to ConsoleApp as well, as it needs to link with the transitive dependencies as well.

The solution proposed in https://github.com/conan-io/conan/pull/12956 PR while it seems it fixes your issue, is not the best approach to manage dependencies. Changing the ``<link>`` section for ``<lib>`` what happens is that the Static.lib does a copy of libz.lib inside itself. But this is not the best approach, consider that:
- As the transitive dependencies increase, like liba->libb->libc->libd, each level in the dependency graph keeps growing in size, accumulating the above libraries. This is a problem of storage, speed.
- The approach might easily break when there are dependencies like liba->libb->libc and also liba->libq->libc. In that case, both libb and libq get a copy of the libc static library, and it might conflict while both converge on liba.

While it might be possible that in some situations it is desired to create a big static library that gathers and embed other static libraries, this would be a custom local solution to that specific wrapping library, but not something that ``MSBuildDeps`` can do by default. So I am closing https://github.com/conan-io/conan/pull/12956, as it is not a viable solution.

Please let me know if this makes sense and if you have any other further question. Thanks very much for your effort to contribute to Conan!

**Comment by illusionistpm** [comment]
That makes sense. Sorry for the false alarm and thank you for investigating!

**Comment by memsharded** [comment]
No prob, thanks to you for your report and your PR! Closing this ticket as solved.
