### ISSUE TITLE
[bug] Warning when using target aliases with CMakeDeps

### ISSUE THREAD

**Issue by phamelin** [conan-io/conan#12958]
### Environment details

* Conan version: 1.54

### Steps to reproduce

If a package has defined  `cmake_target_aliases` property, e.g.:

```
def package_info(self):
    # ...
    self.cpp_info.set_property("cmake_target_name", "mypackage::mypackage")
    self.cpp_info.set_property("cmake_target_aliases", ["mypackage"])
```
then, there's a warning when the find_package is called twice:
```
CMake Warning at build/Release/conan/mypackageTargets.cmake:25 (message):
   Target name 'mypackage' already exists.
 Call Stack (most recent call first):
   build/Release/conan/mypackageTargets-config.cmake:10 (include)
   CMakeLists.txt:54 (find_package)
```
This is explained by this part of the `mypackageTargets.cmake`:
```
if(NOT TARGET mypackage::mypackage)
    add_library(mypackage::mypackageINTERFACE IMPORTED)
    message(STATUS "Conan: Target declared 'mypackage::mypackage'")
endif()
if(NOT TARGET mypackage)
    add_library(mypackageINTERFACE IMPORTED)
    set_property(TARGET mypackagePROPERTY INTERFACE_LINK_LIBRARIES mypackage::mypackage)
else()
    message(WARNING "Target name 'mypackage' already exists.")
endif()
```
We see that the `else()` condition is present only for the target alias. We can avoid to call `find_package(mypackage)` twice in the consumer package. However, if another package also depends on `mypackage`, `find_dependency` macro will be called by the other package config file and the warning will still be present.

If there's no warning for the main target, I suggest that there should have no warning for the target alias as well.

**Comment by Hopobcn** [comment]
Any feedback on this? It's really a bit annoying to have these warnings TBH. They dirty the cmake configuration process which lowers the confidence on the conan generated code.

> New in version 3.15: Added the NOTICE, VERBOSE, DEBUG, and TRACE levels.
  
Perhaps now that cmake supports 3.15 these warnings could be moved to another level?

**Comment by memsharded** [comment]
Thanks for the feedback.
https://github.com/conan-io/conan/pull/14644 from @BobIsOnFire will remove this warning, it was more annoying that helpful. It will be in next 2.0.11
