### ISSUE TITLE
[question] use of tools.microsoft.msbuild:installation_path

### ISSUE THREAD

**Issue by FaerHack** [conan-io/conan#12955]
Specifying of tools.microsoft.msbuild:installation_path variable doesn't help to avoid auto-detect via vswhere at
https://github.com/conan-io/conan/blob/953f2adb78c190f82f45e758560a97bac6147ec0/conans/client/tools/win.py#L467
Is this intended behavior?

**Comment by memsharded** [comment]
Hi @FaerHack 

That call that you are linking should only happen in the legacy integrations. Also, those legacy integration do not listen to the new ``conf`` items like the one you mention.

The modern integrations (those in ``from conan.tools.xxx`` check https://docs.conan.io/en/latest/reference/conanfile/tools.html, and also the 2.0 migration guide: https://docs.conan.io/en/latest/conan_v2.html), no longer use that part of the code, and then they would not call vswhere. (Code to check is https://github.com/conan-io/conan/blob/develop/conan/tools/microsoft/visual.py)
