### ISSUE TITLE
[feature] Add `CMAKE_EXPORT_COMPILE_COMMANDS` environment variable to `CMakePresets` generation

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#12977]
### What is your suggestion?

Some tools such as clangd rely on generated `compile_commands.json` files for them to work. Currently to make CMake generate that file you need to add this to the generated `CMakePresets.json`:

```json
"environment": {
    "CMAKE_EXPORT_COMPILE_COMMANDS": "ON"
}
```

Conan should either add it by default (it shouldn't really break anything and is generally useful) or have an opt-in for users. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by Minimonium** [comment]
I didn't read the manual on CMakePresets properly, it's enough to have a separate Preset for the project unrelated to Conan to support it.

**Comment by memsharded** [comment]
Hi @Minimonium 

Sorry I couldn't respond on time. We are also working on a feature that would allow Conan generated presets to be included from user presets. It is still early, and will need some evolution and care, but this is the idea: https://github.com/conan-io/conan/pull/12932
