### ISSUE TITLE
[feature] tools.build:compiler_executables environment variables

### ISSUE THREAD

**Issue by fjp** [conan-io/conan#12982]
### What is your suggestion?

Hi, with the current implementation of `tools.build:compiler_executables` there seems to be no general way of using environment variables. For example the following won't work for CMake:

```
[conf]
tools.build:compiler_executables={"c": "$CLANGCC", "cpp": "$CLANGCXX"}
```

What seems to work for CMake is the following but I am not sure if this will be true for other build system generators.

```
[conf]
tools.build:compiler_executables={"c": "$ENV{CLANGCC}", "cpp": "$ENV{CLANGCXX}"}
```

Is there another recommended way to use environment variables with the `tools.build:compiler_executables`?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fjp 

If you want to define something as environment variable, then, it should be an environment variable in the ``[buildenv]`` section of the profile, in this case, I guess you would like to define the CC and CXX variables to point to the right locations defined by those vars.

Yes, the ``"$ENV{CLANGCXX}"`` will definitely break other build systems in the dependency graph, if you are sure you are using CMake everywhere, then it might be fine.

Probably the best approach is to leverage the fact that profiles can be jinja templates (if you call them with the .jinja file extension in 1.X, but always in 2.0), and then you can do an ``{{os.getenv("CLANGCC")}}`` to get the value of the env-var directly.

**Comment by AbrilRBS** [comment]
Closing as solved with the proposed Jinja solution (In lieu of the `buildenv` profile sections)
