### ISSUE TITLE
[bug] conan install fails to build package if username contains a whitespace

### ISSUE THREAD

**Issue by travnick** [conan-io/conan#12984]
### Environment details

* Operating System+version: Windows 10 21H2 (19044)
* Compiler+version: Visual Studio 2022 (17.2.7)
* Conan version: 1.56
* Python version: conan installed by Windows installer. I have standalone 3.7.5 but not sure if used by conan.

### Steps to reproduce

1. Have a username with a whitespace, like `My Username`
2. run `conan install "openssl/3.0.7@" -g visual_studio_multi -if openssl_if -of openssl_of --build=missing`
3. Successful builds are ```nasm/2.15.05: Already installed!
strawberryperl/5.30.0.1: Already installed!
zlib/1.2.13: Already installed!```
4. Fails to build `openssl`

### Logs

```
openssl/3.0.7: Copying sources to build folder
openssl/3.0.7: Building your package in C:\Users\My Username\.conan\data\openssl\3.0.7\_\_\build\c47212d5fc818fd54769ccb1344e758f51a9aacb
openssl/3.0.7: Generator txt created conanbuildinfo.txt
openssl/3.0.7: Aggregating env generators
openssl/3.0.7: Calling build()
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.2.7
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
openssl/3.0.7: using target: VC-conan-Release-Windows-x86_64-Visual Studio-17 -> VC-WIN64A
openssl/3.0.7: my %targets = (
    "VC-conan-Release-Windows-x86_64-Visual Studio-17" => {
        inherit_from => [ "VC-WIN64A" ],
        cflags => add("-O2 -Ob2 -MD"),
        cxxflags => add("-O2 -Ob2 -MD"),
        defines => add("NDEBUG"),
        includes => add("C:/Users/My Username/.conan/data/zlib/1.2.13/_/_/package/5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b/include"),
        lflags => add(""),








    },
);

WARN: replace_in_file didn't find pattern '/MTd ' in 'Configurations\10-main.conf' file.
WARN: replace_in_file didn't find pattern '/MTd"' in 'Configurations\10-main.conf' file.
'C:\Users\My' is not recognized as an internal or external command,
operable program or batch file.
openssl/3.0.7:
openssl/3.0.7: ERROR: Package 'c47212d5fc818fd54769ccb1344e758f51a9aacb' build failed
openssl/3.0.7: WARN: Build folder C:\Users\My Username\.conan\data\openssl\3.0.7\_\_\build\c47212d5fc818fd54769ccb1344e758f51a9aacb
ERROR: openssl/3.0.7: Error in build() method, line 612
        self._make()
while calling '_make', line 566
        self.run("{perl} ./Configure {args}".format(perl=self._perl, args=args), win_bash=self._win_bash)
        ConanException: Error 1 while executing C:\Users\My Username\.conan\data\strawberryperl\5.30.0.1\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\perl.exe ./Configure "VC-conan-Release-Windows-x86_64-Visual Studio-17" no-shared --prefix="C:\Users\My Username\.conan\data\openssl\3.0.7\_\_\package\c47212d5fc818fd54769ccb1344e758f51a9aacb" --libdir=lib --openssldir="C:\Users\My Username\.conan\data\openssl\3.0.7\_\_\package\c47212d5fc818fd54769ccb1344e758f51a9aacb\res" no-unit-test threads PERL=C:\Users\My Username\.conan\data\strawberryperl\5.30.0.1\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\perl.exe no-tests --release enable-fips no-md2 zlib --with-zlib-include="C:/Users/My Username/.conan/data/zlib/1.2.13/_/_/package/5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b/include" --with-zlib-lib="C:/Users/My Username/.conan/data/zlib/1.2.13/_/_/package/5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b/lib/zlib.lib"
```

**Comment by memsharded** [comment]
Hi @travnick 

Thanks for your report.
It seems you are using the legacy ``visual_studio_multi`` integration, which has already been removed from 2.0 (next month, now in beta.9), and has been superseded some time ago by the new MSBuildDeps+MSBuildToolchain integration. Please check: https://docs.conan.io/en/latest/reference/conanfile/tools.html

I think the new tools might have better handling of paths with spaces (though to be honest, they are always a big pain, both spaces and special chars, for different build systems, tools and APIs, so I try to avoid them as much as possible). Please try using the new tools and let us know if the problem persists with them. Thanks!

**Comment by travnick** [comment]
Does `-g` option really matter at the build step of a given library?
It does not matter which generator I use - even without any - the error is the same (as posted here before):
```
conan install "openssl/3.0.7@" -g visual_studio_multi -if openssl_if -of openssl_of --build=missing
conan install "openssl/3.0.7@" -g MSBuildDeps -if openssl_if -of openssl_of --build=missing
conan install "openssl/3.0.7@" -g MSBuildToolchain -if openssl_if -of openssl_of --build=missing
conan install "openssl/3.0.7@" -if openssl_if -of openssl_of --build=missing
```
```
'C:\Users\My' is not recognized as an internal or external command,
operable program or batch file.
openssl/3.0.7:
openssl/3.0.7: ERROR: Package 'c47212d5fc818fd54769ccb1344e758f51a9aacb' build failed
```

Unfortunately, I'm not able to easily change the username/home directory of my current user.

**Comment by memsharded** [comment]
Hi @travnick 

I was investigating this, and did https://github.com/conan-io/conan/pull/12986, that proves that MSBuild new integration works with spaces. But this is not the issue, you are right.

I was confused by the generator, while actually the error is in the openssl package.
The thing is that it doesn't seem a Conan issue at all, but something specific to the ``openssl`` build system specifically, that it is not prepared for handling builds with spaces in the path. We can transfer this issue to the ``conan-center-index`` repo, as a recipe issue, but it might be challenging to be solved, because patching openssl build system can be quite challenging.

So if you cannot change your user folder, I'd recommend using the Conan cache in a different location. You can define the CONAN_USER_HOME env-var to point to a different location (without spaces) and that will be used instead of your ``<userhome>/.conan``

**Comment by memsharded** [comment]
Was closed by https://github.com/conan-io/conan/pull/12986, but lets reopen until clarified if needs to be transferred to conan-center-index or the CONAN_USER_HOME is the right solution

**Comment by travnick** [comment]
I've changed the `storage.path` (in `conan.conf`) directory to something without whitespace, and it solved the issue. Since I'm very new to conan I was not able to determine where the bug really lives.

**Comment by memsharded** [comment]
> Since I'm very new to conan I was not able to determine where the bug really lives.

No prob, lets close this issue as solved (I don't think it is worth transferring this now to ConanCenter, as the migration there to 2.0 is taking lots of effort, and this seems a limitation of openssl build system, not a Conan issue and not a Conan openssl recipe issue). 

Thanks for the feedback, and don't hesitate to open new tickets for any further question.
