### ISSUE TITLE
[feature] Install with `Conan` conditionally due to OS

### ISSUE THREAD

**Issue by igormironchik** [conan-io/conan#12987]
### What is your suggestion?

Now we can write `conanfile.txt` and simply install all needed dependencies, like:

```txt
[requires]
freetype/2.12.1
fontconfig/2.13.93

[generators]
cmake_find_package

[options]
freetype:shared=True
fontconfig:shared=True
```

I'd suggest to implement a feature to say `Conan` in `conanfile.txt` to install, for example, `fontconfig` only on `Windows`. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @igormironchik 

Thanks very much for your request.
This has been discussed before, and the conclusion was that we are no further inventing a custom DSL over .txt files to represent conditionals. Instead, it would be necessary to use the ``conanfile.py`` syntax alternative, that can easily represents conditional with much more flexibility and power that would ever be possible in conanfile.txt. This is explained more explicitly in the new 2.0 docs: https://docs.conan.io/en/2.0/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html

**Comment by igormironchik** [comment]
Oh, I forgot about this possibility. Thanks.
