### ISSUE TITLE
[question] Explicitly using conan cache to store package sources

### ISSUE THREAD

**Issue by TheSalvator** [conan-io/conan#12998]
Hello everyone!

I have a question regarding managing sources in local cache. I wanted to create some kind of a filesystem snapshot containing only sources of packages, not the binaries and use this snapshot in variety of build agents to build packages from source without using artifactory. Of course the build profile and configuration is known beforehand. In my opinion this would provide a way to build bit to bit compatible packages in isolated environment without relying on web services, like artifactory for package recipes and github for source tarballs.

The first solution I came up with was the following:
* From the initial conanfile.txt and profile run `conan install . -b '*'`
* Then go to the `~/.conan/data` and remove all the `package` and `build` directories
* Make a snapshot

After you can take this snapshot and run `conan install . -b '*'` and it won't got to the outside since all the recipes and sources present in local cache

Another solution that came up to my mind was the following:
* Download all the sources needed for the packages
* Download repository with recipes
* Make a snapshot

After, you install this snapshot on build agent. Run `python -m http.server` on folder with all the sources. Run `conan_server`. Upload all the recipes from the recipe repository. (You'll need to modify all the source urls to localhost). And then build. 

Sounds like a lot to perform.

And then I came up with the dirtiest hack in my life :)
[0001-Hack-to-enable-only-download-of-sources.patch](https://github.com/conan-io/conan/files/10530000/0001-Hack-to-enable-only-download-of-sources.patch)

It allows just to download sources. This patch is not in any circumstances a proposal. It only shows one way to achieve a task i'm after.

Of course I'm not completely sure if this feature doesn't contradict conan philosophy.

I'm willing to cooperate on this question in terms of contributing code and providing any necessary additional info. But after a few days of thinking I couldn't come up with nice and elegant way to handle this. I'm not sure this even fits conan.

In any ways, thank you in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @TheSalvator 

Thanks for your question.

Let's start with your patch. It is not that far, actually I have been working on something for 2.0 that it will allow to do basically what you are doing, download the sources for the dependency graph: https://github.com/conan-io/conan/pull/12911, even if not installing the binaries. I'll try to finish this for 2.0

But there are other ideas and approaches that might be worth:
- The file download cache: https://docs.conan.io/en/latest/configuration/download_cache.html. It allows caching downloaded files. In Conan 2.0 there is already a separated ``conf``, like ``tools.files.download:download_cache`` that will store the tarballs there. It is not that the file download cache is intended to be backed-up and restored, and there might be unexpected problems, but definitely less than back-uping the whole Conan cache, that might be definitely problematic
- https://github.com/conan-io/conan/pull/8211 would be an step further, back-uping the download cache automatically, or semi-automatically in a server repo. Still the very recommended way is to store those things in a server, and using that server as the "ground-truth" for artifact storage, not only binaries like Conan packages, but also third parties sources tarballs.

**Comment by TheSalvator** [comment]
@memsharded Thanks for you reply!

And thanks a lot for your help!

If you need my help, I will be happy to contribute and/or test

**Comment by memsharded** [comment]
Thanks for the offer! If you want to test my branch in https://github.com/conan-io/conan/pull/13003, or it will be very soon on Conan 2.0beta.9, it would be great if you can test it.

I have marked https://github.com/conan-io/conan/pull/13003 to close this ticket, and in order for the other feature, which will be resumed after 2.0 (what we call 2.X scope), please track https://github.com/conan-io/conan/pull/8211. Thanks!

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/13003 closes this ticket, will be released in beta.9, please try when available.
