### ISSUE TITLE
[windows] Filename too long when building boost from source

### ISSUE THREAD

**Issue by mi-ael** [conan-io/conan#13]
Hi,

i tried to build boost from source on my windows 10 machine (AMD64), and it didn't work.

Log:

G:\Users\[name]\programming\projects\mytimer>conan install --build Boost
Requirements
    Boost/1.59.0@lasote/stable
WARN: Forced build from source: "Boost/1.59.0@lasote/stable"
Configuring sources in G:\Users\after\.conan\data\Boost\1.59.0\lasote\stable\source
Downloading http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.zip/download...
Percent: [########################################] 100.0% of 118.0Mb Done...
Unzipping 416 Mb, this can take a while
Error extract boost_1_59_0/doc/html/images/accumulators/structboost_1_1accumulators_1_1detail_1_1is__tail__variate__feat
ure_3_01tag_1_1tail__variate_3_05c8781b637de300b03d4be7e8c3a6d3b.png
Filename too long

[way more "Filename too long" errors]

Log end

Yay, windows's MAX_PATH!
To work around this everlasting windows problem, I'd like to specify a different source location for packages (or something similar).

Keep up the good work, the c++-community needs you!

**Comment by memsharded** [comment]
Thanks for your support @mi-ael !

Yes, it can be done, navigate to your user home ~/.conan folder.
There you will find a **conan.conf** file:

```
[storage]
# This is the default path, but you can write your own
path: ~/.conan/data
```

change the path to something like H:\ if you create a unit just for conan storage, or C:\conan or whatever fits you (short name).

Sorry, our fault, that the **conan.conf** file is still not properly documented in the docs, opening issue about it. Cheers!

**Comment by mi-ael** [comment]
Thanks for your help!

btw., is this the right place to submit bug reports for specific packages? The "conyfile.py" for boost 1.59.0 crashed in this line:
```
self.run("cd %s && type bootstrap.log" if self.settings.os == "Windows" else "cd %s && cat bootstrap.sh")
```

**Comment by memsharded** [comment]
No, better go to the package repository, in this case: https://github.com/lasote/conan-boost
It seems that the boost package, made by @lasote is still not completely mature, might have some issues yet, and is lacking an URL in the **conanfile.py**, so the repo is linked from the conan site.

Please specify which branch(es) is failing, the repo has three branches, for versions 1.57, 58, 59. Thanks!
