### ISSUE TITLE
conan 0.22.x not working with pkg_resources.DistributionNotFound: pylint==1.6.5

### ISSUE THREAD

**Issue by packadal** [conan-io/conan#1300]
Hi,

I'm having an issue on my CentOS machine where conan 0.22+ spits out the following error: `pkg_resources.DistributionNotFound: pylint==1.6.5`

If I downgrade to anything lower than 0.22 (e.g. 0.21.*, 0.20.*) the error becomes `pkg_resources.DistributionNotFound: distro>=1.0.2,<1.1.0`

I cannot seem to find any resource on this, and as far as I can see, pylint 1.6.5 is in fact installed. Am I missing something, like PYTHONPATH or something ?

The machine is a CentOS6 with a python 2.7.4.

Thanks in advance for the help.

**Comment by memsharded** [comment]
I am not sure. I guess that it is a clean ``pip install conan`` installation, is it?. Are you using virtualenvs? If not, I'd recommend trying that (actually, for absolutely everything python related, not only conan. And virtualenvwrapper is nice). Thanks!

**Comment by packadal** [comment]
I did not know about `virtualenv`, using it solved my issue, thanks a lot :)

**Comment by memsharded** [comment]
Great! :)
The issue could be that there were some package version interactions/incompatibilities with some other app in your machine. Python-pip doesn't easily allow to co-exist different versions in the same installation, and virtualenvs solve this issue.
