### ISSUE TITLE
[question] Static code analysis with Conan 

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#13005]
### What is your question?

Dear Conan Folks,

My goal is to run static code analysis over all our packages.
However, question is there a file(json , yaml) where all the source code used for compilation is written to ?
Also since we are having self building packages we have binaries of the packages instead of sources.
How do get the sources of the binaries in the consumer packages?
Any hints is greatly appreciated.
I am intending to use compiler_commands.json.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by maitrey** [comment]
I managed to run static code analysis using compile_commands.json. However , I need to suppress include headers of dependencies from reports. For this , I need to get the include paths which I am using with target_link_libraries. Is it ok to use: 
get_target_property(INCLUDE_DIRS TARGETA INCLUDE_DIRECTORIES) 
Or is there any other way to get the paths of include headers of dependencies?

**Comment by memsharded** [comment]
Not sure from CMake, but collecting header folders in Conan should be easy:
```python
def generate(self):
     for dep in self.dependencies.host.values():
           xxx = dep.cpp_info.includedir  # iterate ``includedirs`` if some has more than 1 include dir, unlikely
```

**Comment by maitrey** [comment]
Thanks @memsharded . Works for me.
