### ISSUE TITLE
[feature][CMakeDeps] Refactor

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#13018]
### What is your suggestion?

This issue aims to list all the things to be improved in a future version of CMakeDeps:

- [ ] Distinguish between STATIC/SHARED libraries (related to https://github.com/conan-io/conan/issues/3230#issuecomment-529229441 among others)
- [ ] Improve Apple Frameworks management (related to https://github.com/conan-io/conan/issues/10140)

Feel free to add more issues here...

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Maybe when this happens we want to consider https://github.com/conan-io/conan/issues/9000 possibility

**Comment by memsharded** [comment]
This has already started with the new CMakeDeps generator in Conan 2.9, closing as done
