### ISSUE TITLE
[bug] Bad error message about using `conan list packages`

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#13021]
### Environment details

* Operating System+version:
* Compiler+version:
* Conan version:
* Python version:

### Steps to reproduce

```
$ mkdir pkg && cd pkg
$ conan new cmake_lib -d name=pkg -d version=1.0
$ conan export .
$ mkdir pkg1 && cd pkg1
$ conan new cmake_lib -d name=pkg1 -d version=1.0
# Add -> requires = "pkg/1.0" to the conanfile.py
$ conan create .
``` 

### Logs

```
ERROR: Missing prebuilt package for 'pkg/1.0'
Use 'conan list packages pkg/1.0 --format=html -r=remote > table.html' and open the table.html file to see available packages
Or try to build locally from sources with '--build=pkg/1.0'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

**Comment by SSE4** [comment]
bad things about this error message:
1. it basically suggests a command that doesn't exist at all:
```
conan list packages yasm/1.3.0 --format=html -r=conancenter > table.html
usage: conan list [-h] [-f FORMAT] [-v [V]] [--logger] [-p PACKAGE_QUERY]
                  [-r REMOTE] [-c]
                  reference
conan list: error: unrecognized arguments: yasm/1.3.0
ERROR: Exiting with code: 2
```
apparently, there is no `conan list packages`, but only `conan list` (see [reference](https://docs.conan.io/en/2.0/reference/commands/list.html))

2. it's kinda inconvenient to suggest to export an .html to someone who is working from console and potentially doesn't have a web-browser to view it comfortably (e.g. over ssh session).

3. even if you manage to fix the command and run the right one (`conan list "yasm/1.3.0:*" --format=html -r=conancenter > table.html`), it will export an empty table:
```
        <table id="results" class="table table-striped table-bordered" style="width:100%">
            <thead>

            </thead>
            <tbody>

            </tbody>
            <tfoot>

            </tfoot>
        </table>
```
while JSON will export something more appropriate:
```
conan list "yasm/1.3.0:*" --format=json -r=conancenter         
{
    "conancenter": {
        "yasm/1.3.0": {
            "revisions": {
                "2a3d4e934b903c33d380b47bdf7f45be": {
                    "timestamp": 1668025199.03,
                    "packages": {}
                }
            }
        }
    }
}
```
this isn't currently reflected in [documentation](https://docs.conan.io/en/2.0/reference/commands/list.html) that JSON and HTML outputs are semantically different.

4. in general, I wonder why tell a user to run some command, if it could be done internally and showed immediately? it might only cause a headache in some situations. imagine a CI system, where builds could take some minutes or even hours, you will need to re-run CI to get a more useful error message. and by the time you manage to re-run it, a situation may change, as someone may upload or delete a package on remote.

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/docs/pull/2945

**Comment by SSE4** [comment]
@czoido but it's not actually fixed, bad error message is still there, there is just a warning in docs. am I missing something?

**Comment by czoido** [comment]
Sorry, my mistake, I meant to close https://github.com/conan-io/conan/issues/13022

**Comment by czoido** [comment]
closed by https://github.com/conan-io/conan/pull/13135
