### ISSUE TITLE
[bug] `conan list xxxx --format=html` is not working

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#13022]
### Environment details

* Operating System+version:
* Compiler+version:
* Conan version:
* Python version:

### Steps to reproduce

Any `conan list xxxxxx --format=html`

For instance: `conan list m4/1.4.19:\* --format html > table.html`

### Logs

![Screenshot 2023-02-01 at 13 15 02](https://user-images.githubusercontent.com/4571041/216040002-7795f4d2-8779-4efb-a439-6b891c14c013.png)

**Comment by SSE4** [comment]
the output is different from JSON, e.g.:
```
conan list "yasm/1.3.0:*" --format=html -r=conancenter > table.html
...
        <table id="results" class="table table-striped table-bordered" style="width:100%">
            <thead>

            </thead>
            <tbody>

            </tbody>
            <tfoot>

            </tfoot>
        </table>

...
```

```
conan list "yasm/1.3.0:*" --format=json -r=conancenter         
{
    "conancenter": {
        "yasm/1.3.0": {
            "revisions": {
                "2a3d4e934b903c33d380b47bdf7f45be": {
                    "timestamp": 1668025199.03,
                    "packages": {}
                }
            }
        }
    }
}

```

**Comment by czoido** [comment]
~~Closed by https://github.com/conan-io/docs/pull/2945~~

**Comment by memsharded** [comment]
The error message is still wrong:

> conan list packages zlib/1.2.13 --format=html -r=remote > table.html'

**Comment by czoido** [comment]
We also have to fix `conan graph info` that has html output as well

**Comment by czoido** [comment]
closed by https://github.com/conan-io/conan/pull/13135
