### ISSUE TITLE
CONAN_USER_HOME not obeyed for all uses of data dir

### ISSUE THREAD

**Issue by jondo2010** [conan-io/conan#1302]
In particular, `conans/client/rest/cacert.py` always writes `cacert.pem` to `$HOME/.conan/cacert.pem` even if I have `CONAN_USER_HOME` defined.

My use case: I'm running Conan from within a Docker container, mapping CONAN_USER_HOME to a persistent volume, and `$HOME/.conan` may be completely unwritable.

**Comment by memsharded** [comment]
Yes, that is true. Actually, the whole cacert.pem was a workaround to some limitations of ssl or the requests python lib conan is using for networking, but I think that could be removed now. Let's try to address this for 0.24, though can't be sure, as the 0.24 is already big, but lets try. If we can't get rid of cacert.pem, at least try to find a workaround. Thanks for reporting this!

**Comment by memsharded** [comment]
Update: The fix is simple: https://github.com/conan-io/conan/pull/1305
Lets submit it for 0.23, and we will consider getting rid of cacert.pem in a different issue.

**Comment by memsharded** [comment]
Hi @jondo2010, this has been released in 0.23, please upgrade and try it. Thanks!
