### ISSUE TITLE
[bug] Conan v1.57 breaks recipes which use CMakeDeps together with old CMake tool

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#13037]
### Environment details

* Operating System+version:
  * Windows
* Compiler+version:
  * VS2019
* Conan version:
  * 1.57
* Python version:
  * 3.10.5

### Steps to reproduce

1. Create recipe with CMakeDeps to generate CMake config files for the dependencies.
2. Use the old CMake helper tool to build the project.
3. You get a nice exception:

> Using the wrong 'CMake' helper. To use CMakeDeps, CMakeToolchain you should use 'from conan.tools.cmake import CMake'

Since cmake_find_package is deprecated, broken and won't be fixed, projects were forced to use the CMakeDeps generator.

But some projects kept using the old CMake tool, which worked OK. CMakeDeps just generates some CMake config files for the dependencies after all. But now this is broken.

Migration to CMake toolchains is not instantaneous, it takes time to get adjusted to, especially when managing many projects.

The statements in this "Stable" section sound like this change should be considered a bug:

https://docs.conan.io/en/latest/introduction.html#stable

> From Conan 1.0 and onwards, there is a commitment to stability, with the goal of not breaking user space while evolving the tool and the platform. This means:
> Moving forward to following minor versions 1.1, 1.2, …, 1.X should never break existing recipes, packages or command line flows
> If something is breaking, it will be considered a bug and reverted

On the other hand this statement sounds like this change should be considered acceptable (not a bug):

https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html

> Important
> Some of the features used in this section are still under development, while they are recommended and usable and we will try not to break them in future releases, some breaking changes might still happen if necessary to prepare for the Conan 2.0 release.

However, breaking old packages with client updates somehow is not very acceptable to me though.

### Logs

```

ERROR: my_pkg/1.5.0: Error in build() method, line 31
        cmake = CMake(self)
        ConanException: Using the wrong 'CMake' helper. To use CMakeDeps, CMakeToolchain you should use 'from conan.tools.cmake import CMake'

```

**Comment by stevn** [comment]
This remains broken in Conan client v1.58.

**Comment by memsharded** [comment]
Hi @stevn 

Thanks for your report.

The most important part in the stability commitment related to this is:

> Bug fixes will not be considered breaking, recipes and packages relying on the incorrect behavior of such bugs will be considered already broken.

Besides your linked page, also have a look to: https://docs.conan.io/en/latest/reference/conanfile/tools.html
There it says: 

> Only documented tools with explicitly documented imports can be used in recipes. Do not use any other import not found in this section of the documentation, even if they are in the from conan.tools namespace.

The thing is that using the legacy ``CMake`` with the new ``CMakeDeps`` was never intended, and it is broken in some subtle, but problematic ways. We have had so many issues and wasted tons of debugging hours because of this. The error message you are seeing was explicitly added to avoid this, because docs only was not working, and it was being too painful for everyone, users and maintainers. We saw mixing legacy and new integrations as a serious user-side recipe bug to be avoided.

Honestly I don't know what would be the best approach to handle this, because now we are so close to the 2.0 release, if we remove this hard error, users will still not realize about it, and bug reports will keep coming further slowing everyone down towards being 2.0 ready. It is very likely that the current 1.58 will be the last 1.X release before 2.0.

**Comment by stevn** [comment]
> It is very likely that the current 1.58 will be the last 1.X release before 2.0.

Wow, that's good news! Looking forward to some of the new concepts!

If there is a 1.59 release after all, could some kind of workaround be added to allow rebuilding old packages without running into this exception? Not sure how, maybe something like a CONAN_DISABLE_STRICT_MODE=1 environment variable.

Our package builds seemed to work fine, I'm not sure what was broken there. It would be good to know what exactly was/is broken, since we might have to act on that info. But touching old packages somehow seems wrong. We should be moving forwards towards 2.0 instead.

I guess we could also stay on v1.56 for our old Conan 1.x packages until 2.0 is released, at which point this becomes deprecated anyway.

**Comment by memsharded** [comment]
> Our package builds seemed to work fine, I'm not sure what was broken there. It would be good to know what exactly was/is broken, since we might have to act on that info. But touching old packages somehow seems wrong. We should be moving forwards towards 2.0 instead.

One of the most common mistakes is building packages with the wrong flags. As ``CMake`` legacy generator works by defining some command line definitions like CONAN_XXX that the ``conanbuildinfo.cmake`` of the legacy ``cmake`` generator is relying on, it is a very common mistake to drop that file (after all ``CMakeDeps`` and ``CMakeToolchain`` are replacing the legacy ``cmake`` generator), and removing the ``include(conanbuildinfo.cmake)``. That might result in package creation, but often with wrong ``cppstd``, ``libcxx``, ``GLIBCXX_11``, ``toolset`` and others, which will cause problems only later down the road (as it might also be undetected by consumers of this binary, if they do the same mistake).

Other problems that we saw is not finding the generated .cmake files generated by CMakeDeps, often was evident enough, but some painful case the system dependency via system or CMake find modules was being found.

**Comment by stevn** [comment]
Ok, so it seems to me that our old packages actually (probably) aren't broken.
1. We used include(conanbuildinfo.cmake) correctly.
2. The generated .cmake files were found correctly in our case.

>  system dependency via system or CMake find modules was being found

Yeah, I've run into that one in the past, but found a different solution.

So I understand the need to avoid this problem for new packages. But I basically don't see why the new client shouldn't be able to build these "somehow incorrect but actually working" old packages. I added a commit to my fork as a suggestion.

**Comment by stevn** [comment]
Maybe the CONAN_DISABLE_STRICT_MODE env var should be renamed to CONAN_DISABLE_SANITY_CHECKS.

**Comment by memsharded** [comment]
Oh, look what I found in code! 😮 

```python
        if getattr(conanfile, "must_use_new_helpers", None):
            raise ConanException("Using the wrong 'CMake' helper. To use CMakeDeps, CMakeToolchain "
                                 "you should use 'from conan.tools.cmake import CMake'")
```
I am sorry I didn't recall about this, but it seems there is already a built-in opt-out, which is to define the ``must_use_new_helpers = False`` in the recipe.

**Comment by stevn** [comment]
Hm, yeah I saw that. But then I'd have to patch all old recipes, which I can't.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13039
