### ISSUE TITLE
[question] Broken symlink issue

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#13045]
### What is your question?

Dear Conan Folks,

I donot use any symlinks. I see an error : ERROR: The file is a broken symlink, verify that you are packaging the needed destination files.  You can skip this check adjusting the 'general.skip_broken_symlinks_check' at the conan.conf file.
I use windows operating system. Only thing different is I have really long paths and had to fit to Windows path limitations. 
What is the effect of disabling this setting in conan.conf?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by maitrey** [comment]
DOnot see this issue anymore.

**Comment by hiiizxf** [comment]
I have the same problem. How did you solve it.
There are two servers, and running "conan create . xxx/xxx@" on one of them prompts a  "ERROR: The file is a broken symlink, verify that you are packaging the needed destination files:/${HOME}/.conan/data/xxx/{version}/{user}/{channel}/export/{mydir}/{some symblink file or dir}. You can skip this check adjusting the 'general.skip_broken_symlinks_check' at the conan.conf file." error.  The other server is OK.
{mydir} is a dir ,in my project, with symblink files .

**Comment by memsharded** [comment]
Hi @hiiizxf 

This is a closed issue, so might not get any responses.
The ``conan create`` is a local operation, it shouldn't depend on the servers.

Also, Conan 2.0 has dropped most of the built-in management of symlinks, and provided tools for users to explicitly manage symlinks at the time of packaging, they are also backported to Conan 1.X to allow easier migration to Conan 2.0, check: https://docs.conan.io/1/reference/conanfile/tools/files/symlinks.html
