### ISSUE TITLE
[bug] Extracting packages from Artifactory after download fails on Windows/SMB

### ISSUE THREAD

**Issue by aheck** [conan-io/conan#13046]
### Environment details

* Operating System+version: Windows Server 2016
* Compiler+version: Visual Studio 2019
* Conan version: 1.57
* Python version: 3.10

### Steps to reproduce

1. You need to have a package in Artifactory that is fetched during conan install as a dependency.
2. Do a conan install on a Windows SMB share and the extraction of the conan_package.tgz and conan_export.tgz fails.
3. With debug prints it could be determined that the following error codes are returned by Windows in Pythons ntpath.py:

ntpath.py:660: [WinError 3] The system cannot find the path specified

ntpath.py:679: [WinError 2] The system cannot find the file specified

When it works (e.g. because a time.sleep(5) is added in line 679) in both cases the error code 3 is returned.

Workaround:

Set the registry key HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\FileNotFoundCacheLifetime to 0 (no reboot needed) and it works. The default value is 5 seconds.

It looks like the FileNotFoundCache is either buggy or the caching breaks conan/Python path handling code.

**Comment by memsharded** [comment]
Hi @aheck 

Thanks for your report.
Indeed this seems a bad interaction with Python and SMB units.

In any case, I'd probably try to avoid it. The Conan cache cannot be shared, it is not designed for concurrency, much less for distributed concurrency (multiple machines), and even less for distributed multi-OS concurrency (a SMB drive might be accessed by different OSs?). So it sounds that putting the Conan cache in a SMB will probably cause many other issues down the road.

**Comment by memsharded** [comment]
Closing as responded back then. Please create new tickets for any further question.
