### ISSUE TITLE
[bug] imports() throws an exception for copying from a prebuilt package

### ISSUE THREAD

**Issue by JesusKrists** [conan-io/conan#13055]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: gcc-11
* Conan version: 1.58.0
* Python version: 3.8

### Steps to reproduce

Setting `self.requires("spdlog/1.11.0")` in a recipe and setting the options to `"spdlog:shared": True` and `"fmt:shared": True` seems to make self.copy fail under the imports() method.

This is the imports() method in question:
```
def imports(self):
        self.copy("*.dll", "build/dev/", "bin")
        self.copy("*.dll", "build/dev/test", "bin")
        self.copy("*.so", "build/dev/", "lib")
        self.copy("*.so", "build/dev/test", "lib")

        self.copy("*.dll", "build/", "bin")
        self.copy("*.dll", "build/test", "bin")
        self.copy("*.so", "build/", "lib")
        self.copy("*.so", "build/test", "lib")
```

And running this command in CI:
```
run: pip3 install "conan<2"
        && conan profile new default --detect
        && conan profile update settings.compiler.libcxx=libstdc++11 default
        && conan install . -b missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

### Logs

conanfile.py (JEngine-Reformed/latest) imports(): Copied 12 '.so' files
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/client/command.py", line 2216, in run
    method(args[0][1:])
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/client/command.py", line 523, in install
    info = self._conan.install(path=args.path_or_reference,
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/client/conan_api.py", line 609, in install
    deps_install(app=self.app,
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/client/manager.py", line 140, in deps_install
    run_imports(conanfile)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/client/importer.py", line 85, in run_imports
    _report_save_manifest(copied_files, import_output, conanfile.imports_folder, IMPORTS_MANIFESTS)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/client/importer.py", line 60, in _report_save_manifest
    file_dict[f] = md5sum(abs_path)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/util/files.py", line 145, in md5sum
    return _generic_algorithm_sum(file_path, "md5")
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/conans/util/files.py", line 158, in _generic_algorithm_sum
    with open(file_path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/JEngine-Reformed/JEngine-Reformed/build/dev/libspdlog.so'

**Comment by JesusKrists** [comment]
running with `conan install . --build` to force the packages to build seems to have the same problem.
```
spdlog/1.11.0 package(): Packaged 1 '.0' file: libspdlog.so.1.11.0
spdlog/1.11.0 package(): Packaged 1 '.11' file: libspdlog.so.1.11
spdlog/1.11.0 package(): Packaged 1 '.so' file: libspdlog.so
spdlog/1.11.0 package(): Packaged 1 file: LICENSE
spdlog/1.11.0 package(): Packaged 86 '.h' files
spdlog/1.11.0: Package '34bd83bf0526e11e1a85cf4c4eebab0f5eefc5fa' created
spdlog/1.11.0: Created package revision b0784a0dff82faa5ddf5563ff571a542
```

We can see that the file indeed gets packaged.

**Comment by memsharded** [comment]
Hi @JesusKrists 

Thanks for your report.
There is some complicated management of symlinks inside the ``self.copy()`` and ``import()`` logic, and I suspect that this error is caused by these symlinks.
As the ``imports()`` method and ``self.copy()`` are legacy, and have been removed in 2.0 (beta.9 is out, it will be GA very soon), I'd probably try to use the new 2.0-ready approach which would be:
- Implement the importing explicitly in the ``generate()`` method
- Use the ``from conan.tools.files import copy`` instead.

If that keeps failing, it would be probably easier to prioritize fixing it, as the 2.0 release is getting all the focus these days.

**Comment by JesusKrists** [comment]
Thank you for your quick response. I have been at this for the past days for a few hours at a time and I have a conclusion finally to this issue.

1. The original exception was being thrown because of my own mistake. the `"*.so"` pattern is actually sort of incorrect. I meant the `"*.so*"` pattern as there are `.so` files with more extensions after them for versioning purposes I believe, which all get symlinked together in some way. So your answer about the symlink mechanism making this exception show up is true. But also changing the pattern to match `"*.so*"` makes all of the `.so` files get copied and then the exception doesnt get thrown.

2. Initially I went down the conan 2.0-ready approach as you described above and while it actually worked, but I found it to be a lot less elegant for my liking. I ended up doing something like this

```
   def copy_binaries_to_build_folders(self, build_configuration: str = ""):
        EXTENSION_PATTERNS = ["*.dll", "*.so"]

        build_type = ""
        if is_msvc(self) and build_configuration == "build":
            build_type = str(self.settings.build_type)

        for dep in self.dependencies.values():
            if len(dep.cpp_info.bindirs) != 0:
                for extension in EXTENSION_PATTERNS:
                    copy(
                        self,
                        extension,
                        dep.cpp_info.bindirs[0],
                        os.path.join(
                            self.source_folder, build_configuration, build_type
                        ),
                    )
                    copy(
                        self,
                        extension,
                        dep.cpp_info.bindirs[0],
                        os.path.join(
                            self.source_folder,
                            build_configuration,
                            "test",
                            build_type,
                        ),
                    )

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()

        self.copy_binaries_to_build_folders("build")
        self.copy_binaries_to_build_folders("build/dev")
        self.copy_binaries_to_build_folders("build/coverage")
        self.copy_binaries_to_build_folders("build/sanitize")
```

And this feels like a lot more boilerplate code than using the current approach under the `imports()` method with the `copy` property. So I went with my original conan 1 approach with the `imports()` method as it currently feels a lot cleaner. Once conan 2 is actually ready, I will think about migrating everything of course.

I will leave closing this issue up to you as I don't know if you have anything to add on top of this. Thank you for your time and help and keep up the good work :)

**Comment by memsharded** [comment]
> The original exception was being thrown because of my own mistake. the "*.so" pattern is actually sort of incorrect. I meant the "*.so*" pattern as there are .so files with more extensions after them for versioning purposes I believe, which all get symlinked together in some way. So your answer about the symlink mechanism making this exception show up is true. But also changing the pattern to match "*.so*" makes all of the .so files get copied and then the exception doesnt get thrown.

Ok, excellent, yes, that all makes sense

```python
copy(
                        self,
                        extension,
                        dep.cpp_info.bindirs[0],
```
It seems that this pattern is the same in both cases, so you would be copying twice the same files from the cache to different folders in your folders. Is this the intended behavior? It seems a bit weird.

> I found it to be a lot less elegant for my liking.

Well, it might be a bit longer (I think it might be compacted a bit and some minor cleanings too), but the advantage of being explicit and being able to do basically everything that you want, greatly make it worth as a better general approach. Also taking into account that 2.0 also has ``deployers``, that doesn't need to be in a recipe, but they are separate.

> I will leave closing this issue up to you as I don't know if you have anything to add on top of this. Thank you for your time and help and keep up the good work :)

Thanks to you!

**Comment by JesusKrists** [comment]
Honestly I am no professional, I am not sure what is the best setup with conan in my case. In CI my cmake build directory is under `build/` for both windows and ubuntu. `build/sanitize` under ubuntu for my sanitizer pipeline. `build/coverage` for my ubuntu code coverage pipeline. And for windows specifically i am running the visual studio generator, which has this multi-configuration build as I understand, and those create an extra folder for both Debug and Release, which ends up looking like `build/Debug`. And on top of that I also have test binaries, which are created under `build/test`. So that turns out to be `build/test/Debug` for the visual studio generator. And locally when developing my build directory is set to `build/dev`. So in total that is a lot of possible paths for `.so` and `.dll` files to need to be placed in. Im guessing there is a way to set up to tell conan at `conan install .` step which build I am aiming for, but I haven't done the research yet so I have gone with this option of copying everything to everywhere haha

Before using conan I was setting up package dependencies using FetchContent in cmake + `add_subdirectory`, which worked quite well, but if I made any changes to CMake files, which required me to delete the build folder, fetching all dependencies took forever every time. And to add on top of that, I was also limited to building my dependencies with the same build configurations as my own project, which meant that if I was building in `Debug`, the dependencies would also be built in `Debug`, which was quite useless unless I had to debug a deep dependency issue. So even if I am not using conan to its full/correct potential, its still a much better experience than FetchContent has been

**Comment by memsharded** [comment]
> Honestly I am no professional, I am not sure what is the best setup with conan in my case. In CI my cmake build directory is under build/ for both windows and ubuntu. build/sanitize under ubuntu for my sanitizer pipeline. build/coverage for my ubuntu code coverage pipeline. And for windows specifically i am running the visual studio generator, which has this multi-configuration build as I understand, and those create an extra folder for both Debug and Release, which ends up looking like build/Debug. And on top of that I also have test binaries, which are created under build/test. So that turns out to be build/test/Debug for the visual studio generator. And locally when developing my build directory is set to build/dev. So in total that is a lot of possible paths for .so and .dll files to need to be placed in. Im guessing there is a way to set up to tell conan at conan install . step which build I am aiming for, but I haven't done the research yet so I have gone with this option of copying everything to everywhere haha

Good, thanks for explaining! 😄 

The overall idea with Conan is that the recipe can define options like ``options = {"sanitize": [True, False]}`` or have conf like the built-in ``tools.build:skip_test`` that control if tests are built or not. Passing these to the build system as arguments can control the build, so different binaries can be generated. That means that you could do something like ``conan install . - o pkg*:sanitize=True -s build_type=Debug``, and that will install the Debug dependencies, and configure the "sanitize" build. So basically every different binary configuration is a different "conan install" (and a different "conan create", creating its own different binary). 
Probably irrelevant for your use case and usage right now, but just to explain a bit the general Conan approach.

**Comment by JesusKrists** [comment]
Ah that makes sense. Thanks for the tip and explanation. I will implement this actually as I would love to not copy `.dll` and `.so` files all over the place. Conan is a great addition to my C++ toolbelt so to say. I see a lot of power in this solution. Thanks for creating a great product!

Best of luck to you! :)

**Comment by JesusKrists** [comment]
Sorry if I am keeping this issue alive. I just wanted to leave this here in case anyone ever gets any use out of this. I implemented what you suggested and it works flawlessly and is very clean.

```
options = {
    "dev_build": [True, False],
    "coverage_build": [True, False],
    "sanitize_build": [True, False],
}
```

```
def imports(self):
    build_folder = "build/"
    test_folder = "build/test"
    if self.options.dev_build:
        build_folder = "build/dev"
        test_folder = "build/dev/test"
    if self.options.coverage_build:
        build_folder = "build/coverage"
        test_folder = "build/coverage/test"
    if self.options.sanitize_build:
        build_folder = "build/sanitize"
        test_folder = "build/sanitize/test"
    if (
        is_msvc(self)
        and not self.options.dev_build
        and not self.options.coverage_build
        and not self.options.sanitize_build
    ):
        build_folder = f"build/{str(self.settings.build_type)}"
        test_folder = f"build/test/{str(self.settings.build_type)}"
    if self.settings.os == "Windows":
        self.copy("*.dll", build_folder, "bin")
        self.copy("*.dll", test_folder, "bin")
    if self.settings.os == "Linux":
        self.copy("*.so*", build_folder, "lib")
        self.copy("*.so*", test_folder, "lib")
```

And then on the command line I can do `conan install . -b missing -o JEngine-Reformed:sanitize_build=True` for example, and it works perfectly. And migrating to the 2.0 ready approach is elegant now as well I want to say :)

```
def import_shared_libraries(self):
    build_folder = "build/"
    test_folder = "build/test"
    if self.options.dev_build:
        build_folder = "build/dev"
        test_folder = "build/dev/test"
    if self.options.coverage_build:
        build_folder = "build/coverage"
        test_folder = "build/coverage/test"
    if self.options.sanitize_build:
        build_folder = "build/sanitize"
        test_folder = "build/sanitize/test"
    if (
        is_msvc(self)
        and not self.options.dev_build
        and not self.options.coverage_build
        and not self.options.sanitize_build
    ):
        build_folder = f"build/{str(self.settings.build_type)}"
        test_folder = f"build/test/{str(self.settings.build_type)}"

    for dep in self.dependencies.values():
        dirs = []
        extension_pattern = ""

        if self.settings.os == "Windows":
            dirs = dep.cpp_info.bindirs
            extension_pattern = "*.dll"
        if self.settings.os == "Linux":
            dirs = dep.cpp_info.libdirs
            extension_pattern = "*.so*"

        for dir in dirs:
            copy(
                self,
                extension_pattern,
                dir,
                os.path.join(self.source_path, build_folder),
            )
            copy(
                self,
                extension_pattern,
                dir,
                os.path.join(self.source_path, test_folder),
            )

def generate(self):
    tc = CMakeToolchain(self)
    tc.generate()

    self.import_shared_libraries()
```

Thank you very much for everything!

**Comment by memsharded** [comment]
Excellent, thanks for sharing!
