### ISSUE TITLE
[bug] Private dependencies broken when using CMakeDeps + CMakeToolchain with test_requires?

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#13052]
### Environment details

* Operating System+version:
  * Windows 10
* Compiler+version:
  * VS2019
* Conan version:
  * 1.56 + 1.58 (both have this problem)
* Python version:
  * 3.10.5

### Steps to reproduce

Create conanfiles for libs A, B, C

conanfile.py of lib A:

    def generate(self):
        tool_chain = CMakeToolchain(self)
        tool_chain.generate()
        cmake_deps = CMakeDeps(self)
        cmake_deps.generate()

    def build_requirements(self):
        self.test_requires("lib_b/[^4.2.9]@stevn/stable")

conanfile.py of lib B:

    def generate(self):
        tool_chain = CMakeToolchain(self)
        tool_chain.generate()
        cmake_deps = CMakeDeps(self)
        cmake_deps.generate()

    def requirements(self):
        self.requires("lib_c/[^4.0.3]@stevn/stable", private=True)

conanfile.py of lib C (has no dependencies):

    def generate(self):
        tool_chain = CMakeToolchain(self)
        tool_chain.generate()
        cmake_deps = CMakeDeps(self)
        cmake_deps.generate()

Call "conan create . -s:b build_type=Release -s:h build_type=Debug" for lib_c. Works.
Call "conan create . -s:b build_type=Release -s:h build_type=Debug" for lib_b. Works.
Call "conan install . -s:b build_type=Release -s:h build_type=Debug" for lib_a. It fails with the following error:

ERROR: conanfile.py (lib_a/4.3.4): Error in generate() method, line 90
        cmake_deps.generate()
        ConanException: error generating context for 'lib_b/4.2.9@stevn/stable': {'ref': lib_c/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}

When I change private=True to private=False in conanfile.py of lib_b, the install and later build succeed.

**Comment by stevn** [comment]
I think it has to with the component requires in package_info() method. Will check later.

**Comment by memsharded** [comment]
Hi @stevn 

Yes, please, let us know if the components have something to do, it sounds it is possible that it is related.

Quick tip about ``private``. In general they are discouraged in 1.X, as they tend to be problematic in different aspects. When you do ``self.requires("lib_c/[^4.0.3]@stevn/stable", private=True)``, why do you want to include ``lib_c`` privately? This should be used, as recommended, only in extreme cases, for example if requiring to use different versions in the same graph without conflict. Being ``lib_b`` a ``test_requires`` maybe it is not necessary? If you could put actual names and responsibilities to those packages, it would be possible to understand the use case a bit better.
