### ISSUE TITLE
[question] Conan is finding either Windows package or Linux and Mac, but not all three.

### ISSUE THREAD

**Issue by daniel-heater-imprivata** [conan-io/conan#13054]
### What is your question?

When I try to use a package I wrote, I can only `conan install` the Mac and Linux version OR the Windows version, but not all three.

`conan search` on my the Artifactory repo I uploaded to turns up the Mac version with `Package_ID: 68bbaeb530f162165b99736fbca83b8b45ba84c7` and Linux with `Package_ID: 966c472618462856d8b48a5c23c53b6b6a428f1c` OR Windows with `Package_ID: a6ee89a84c4b748dae0b78fa6bf92feb72062103`

When I look in Artifactory, all three appear to have deployed. The Windows package ends up in directory `671f10fa5adbfc41c555a46e580f3821` while Mac and Windows packages  end up in `68750c8933ab0ba0f1e17fcaeed9dd2f`.  I'm guessing that's why `conan search` only sees some of the packages. Is something wrong/ missing from my `conanfile.py`?

```
from conans import ConanFile, CMake, tools
from conan.tools.system.package_manager import Yum


class commonUtilsConan(ConanFile):
    name = "common-utils"
    version = "2.3.0"
    license = "Proprietary"
    url = "git.company.com:company/devops/rpms/common-utils.git"
    description = "Common utilities for company"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    generators = "cmake", "cmake_find_package"
    exports_sources = "CMakeLists.txt", "src/*", "include/*"

    def system_requirements(self):
        yum = Yum(self)
        yum.install(["company-java8", "company-openjdk-devel", "rpm-build"], update=True, check=True)

    def requirements(self):
        self.requires("catch2/3.2.1", "private")
        self.requires("fmt/9.1.0")
        self.requires("libcurl/7.87.0")
        self.requires("libzip/1.9.2")
        self.requires("mbedtls/3.2.1")
        self.requires("openssl/3.0.7")
        self.requires("spdlog/1.11.0")

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def build(self):
        cmake = CMake(self)
        cmake.definitions["ENABLE_TESTS"] = "OFF"
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()
        self.copy("*.h", dst="include", src="include")
        self.copy("*.hpp", dst="include", src="include")
        self.copy("*.h", dst="include/jni", src="include/jni")
        self.copy("*.a", dst="lib", src="lib")
        self.copy("*.lib", dst="lib", src="lib")
        self.copy("*.dll", dst="bin", src="bin")
        self.copy("*.dylib*", dst="lib", src="lib")
        self.copy("*.so", dst="lib", src="lib")
        self.copy("*.so.*", dst="lib", src="lib")
        self.copy("*.dylib", dst="lib", src="lib")

    def package_info(self):
        self.cpp_info.includedirs = ["include"]
        self.cpp_info.libs = ["common-utils"]
```

Conan version 1.57

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @daniel-heater-imprivata 

Thanks for your question.

I think that you might be experiencing some issue with your source code checkout line feeds. 
The recipe revision that identifies the recipe and sources is the computed from the hash of the contents. If the git checkout in Windows changes the line feeds, typically to force CRLF in Windows, that changes the hash of the contents, changes the recipe revision, and that produces the issue, because each revision has its own binaries.

Having different line feeds in different OSs is no longer a recommended practice. All text editors in Windows perfectly support LF, no need for CRLF, so using exactly the same ones (LF) in all OSs avoids many issues.

Please check if that is the thing causing the issue, and let us know. You can check that directly in the server side, or with Conan commands like ``conan search ... --revisions``

**Comment by daniel-heater-imprivata** [comment]
Yes. That appears to have been the problem! Thanks!

**Comment by daniel-heater-imprivata** [comment]
Leaving a note for reference.

Setting `* test=auto eol=lf` in `.gitattributes` should be sufficient.

But for some reason I don't understand, In my CI, using the Github `actions.checkout@v2 or v3` the EOL settings still end up:
```
i/lf    w/crlf  attr/text=auto eol=lf 	include/applicationinstaller.h
```
So still wrong in the working directory.  The workaround I found is to do a `git reset --hard` after the checkout.

**Comment by memsharded** [comment]
Seems related link: https://github.com/actions/checkout/issues/135
