### ISSUE TITLE
[question] How to create a package using API V2?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#13065]
### What is your question?

Since Conan Package Tools are not going to be supported for Conan 2.0, I'm trying to rewrite my CI scripts and use API V2 instead. During CI I need to create packages. CPT did that the following way:
```python
    self._results = self._conan_api.create(self._conanfile, name=name, version=version,
                            user=user, channel=channel,
                            build_modes=self._build_policy,
                            require_overrides=self._require_overrides,
                            profile_names=[self._profile_abs_path],
                            test_folder=self._test_folder,
                            not_export=self.skip_recipe_export,
                            update=self._update_dependencies,
                            lockfile=self._lockfile,
                            profile_build=profile_build)
```
I can't find a similar (convenient) way to do this using API V2.  I partially succeed with
```python
    conan_api = ConanAPI()
    remotes = conan_api.remotes.list()
    build = [conan_api.profiles.get_default_build()]
    host = [conan_api.profiles.get_default_host()]
    profile_build = conan_api.profiles.get_profile(profiles=build)
    profile_host = conan_api.profiles.get_profile(profiles=host)
    profile_host.settings.update(settings)
    profile_host.options.update(options_values=options)
    deps_graph = conan_api.graph.load_graph_requires([reference], None,
                                                     profile_host, profile_build, None,
                                                     remotes, None)
    build_modes = [reference]
    conan_api.graph.analyze_binaries(deps_graph, build_modes)
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
```
but it's too verbose and doesn't include testing. Is there an easier way to do this? I also need a graph in the end to check what actually has been built  and then upload it.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
The new 2.0 python API is much detailed and complete, with low level access than the previous one.

For high level, command-line equivalent, you might try to use:
```python
cli = Cli(conan_api)
    error = SUCCESS
    try:
        cli.run(args)
    except BaseException as e:
        error = cli.exception_exit_error(e)
```
(still not documented, not public API, might change and break)

Otherwise, if you want to add testing, your can have a look to the ``create`` command implementation, these would be the lines: https://github.com/conan-io/conan/blob/6071be9e4b82b2af592feecb35a5b45e0d8e9eb4/conan/cli/commands/create.py#L93

You can also simplify some of the above, like to obtain the profiles you can:
```python
profile_host, profile_build = conan_api.profiles.get_profiles_from_args(args)
```

**Comment by db4** [comment]
Hi @memsharded, 

> For high level, command-line equivalent, you might try to use: (...)
> (still not documented, not public API, might change and break)

Thanks, but it doesn't return a graph, and I have to deal with json output. So duplicating the commands logic via low-level 2.0 API still looks more convenient.

> Otherwise, if you want to add testing, your can have a look to the create command implementation,

Yes. done it. I just thought that some high-level API would be nice (for CI scripts, for instance) and was a bit surprised that it didn't not exist.

**Comment by memsharded** [comment]
> Thanks, but it doesn't return a graph, and I have to deal with json output. So duplicating the commands logic via low-level 2.0 API still looks more convenient.

But the 1.X doesn't return a graph object either? If you want the json format of the graph, you can still pass ``cli.run("... --format=json")`` to get it too in 2.0. It is also easy to capture stdout with something of the form:
```python
     original_stdout = sys.stdout
     sys.stdout = StringIO()
     try:
          Cli().run(mycmd)
    finally:
          result= str(sys.stdout.getvalue())
          sys.stdout = original_stdout
```
(If this is a common pattern, we might even consider adding something built-in for this purpose)

We found that the literal translation of the CLI to an API didn't make much sense, it takes some effort to maintain and document, and it is just more intuitive to users to use the same CLI syntax, so the provided value is relatively small. There are a bunch of Python based tools that follows a very similar approach.

**Comment by db4** [comment]
Ok, I get the point. Many thanks for your help!
