### ISSUE TITLE
[question] Improving build times for project with heavy dependencies

### ISSUE THREAD

**Issue by chulup** [conan-io/conan#13061]
### What is your question?

I am using Conan 1.56.0 and it's still a long time for me to move to Conan 2.0.
My project depends on several pretty big libraries like WebRTC, Qt and a few internal of similar size.

I am working on improving our builds (profiles, settings, cross-compiling...) and that takes a lot of tries. Dependencies like WebRTC download their source code every time and just that could take anywhere from 20 to 60 minutes, while being incompatible with download_cache (I just finished writing this question, WebRTC download only has already taken more than 30 minutes and it's not done yet).
Of course that just breaks my working process!

I found several takes other people did with improving builds: https://github.com/conan-io/conan/issues/9383 https://github.com/conan-io/conan/issues/6877 https://github.com/conan-io/conan/issues/8442

Now, my problems are like that:

1. I need to rebuild everything.
2. Most of dependencies could be rebuilt quickly, but few known take a long time to do it.
3. Doing at least parallel download for some (known beforehand) dependencies, preferably fully parallel buid.
4. Without using download_cache.
5. With every package being rebuilt at the end of the task.
6. It is possible to run multiple commands, sequentially or in parallel, with some of them finished with errors.

My idea for now, which I can't find a way to do:

1. Run `conan install <> --build='!qt*' --build='!WebRTC*' --build` to build all small deps. This should fail at the end as big deps won't be found.
2. Run `conan install` on my conanfile.py for exact package ID, like `WebRTC/5005_p9@my/testing ID: 7941fc92cc2b582c5f79ba8aaa2809dd3a054b0a`, or full command `conan install .. -pr:h <> -pr:b <>` but with command to build WebRTC only. Do this simultaneously for big packages as small ones were built on step 1.
3. Profit!

Step 2 breaks on the issue that build order is the same for every invocation and that means if Qt is being built in one command then WebRTC command will wait until Qt is done. 

I see a couple of ways to fix this: 
1. find a way to skip building the dependency entirely, knowing that `conan install` will fail at the end.
2. or, find a way to request building one exact package ID with settings and options taken from my root `conanfile.py`.

Can you help me with this or point me to some docs I missed?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @chulup 

Thanks for your question.
I have a quick question, what do you mean with "I need to rebuild everything."? You mean, every time? Aren't you using the precompiled Conan binaries? This is one of the main reasons to use Conan, because it is easy to store the binaries and save tons of time re-compiling very heavy to build libraries.

Regarding the binaries, it is not possible to command the build of an exact ``package_id``, the inputs are always the build and host profiles, and that will produce the resulting ``package_ids``, but as they are hashes (one way), it is not possible to obtain a configuration from a given ``package_id``.

**Comment by chulup** [comment]
I forgot to tell you thanks for creating such a wonderful tool and improving it further with Conan 2.0! Can't move to using it fast enough, but business have other priorities =)

> I have a quick question, what do you mean with "I need to rebuild everything."? You mean, every time? Aren't you using the precompiled Conan binaries? This is one of the main reasons to use Conan, because it is easy to store the binaries and save tons of time re-compiling very heavy to build libraries.

In order to do that you first must have binary packages to store. Our Conan builds worked up until now, but we have to update compilers and some of common libraries, change build settings to support some outdated system our managers would like to use. And that requires a lot of rebuilding and testing which is - surprise! - my job. When I am sure that everything works correctly I can push everything to CI so that it rebuilds it again and pushes to Conan repo, but that comes later.
Also, waiting all that time while CI recompiles everything every time I update some library takes toll on our team too. 

> Regarding the binaries, it is not possible to command the build of an exact `package_id`, the inputs are always the build and host profiles, and that will produce the resulting `package_ids`, but as they are hashes (one way), it is not possible to obtain a configuration from a given `package_id`.

What if I grab conaninfo.txt file generated in my build directory by doing `conan info --profile:host <> ...` with following lines:

```
[full_options]
...
WebRTC:enable_video=True
WebRTC:fPIC=True
WebRTC:shared=False
WebRTC:use_rtti=True
WebRTC:with_ffmpeg=False
...
```

and then use it to do WebRTC install like that:

```
conan install WebRTC/5005_p9@my/testing --profile:host <same> --profile:build <same2> -o WebRTC:enable_video=True -o WebRTC:fPIC=True -o WebRTC:shared=False -o WebRTC:use_rtti=True -o WebRTC:with_ffmpeg=False
```
Will that generate the same package ID as just doing `conan install my_root_conanfie.py -pr:b ... -pr:h ... --build=WebRTC`?

**Comment by memsharded** [comment]
> I forgot to tell you thanks for creating such a wonderful tool and improving it further with Conan 2.0! Can't move to using it fast enough, but business have other priorities =)

Thanks very much, happy to hear that!

> In order to do that you first must have binary packages to store. Our Conan builds worked up until now, but we have to update compilers and some of common libraries, change build settings to support some outdated system our managers would like to use. And that requires a lot of rebuilding and testing which is - surprise! - my job. When I am sure that everything works correctly I can push everything to CI so that it rebuilds it again and pushes to Conan repo, but that comes later.
Also, waiting all that time while CI recompiles everything every time I update some library takes toll on our team too.

Ok, now I understand things a bit better.

These might be some ideas to explore:
- The download of the sources from internet might be much slower than from our own servers. Putting source tarballs for third party in a server (like an Artifactory generic repo) that is close to the CI agents can speed up a lot the download and avoid more network issues. It is also a good practice, making it way more robust against possible changes, attacks, etc.
- Make sure the parallelism is being used. With the new integrations like ``CMakeToolchain``, the default would be build in parallel, but ``tools.build:jobs`` conf might help to setup the number of concurrent threads and optimize it.


> Will that generate the same package ID as just doing conan install my_root_conanfie.py -pr:b ... -pr:h ... --build=WebRTC?

yes, exactly, no need to capture conaninfo.txt first. Actually, with Conan 2.0, the ``conaninfo.txt`` will no longer be generated in user folders.

**Comment by chulup** [comment]
> yes, exactly, no need to capture conaninfo.txt first. Actually, with Conan 2.0, the conaninfo.txt will no longer be generated in user folders.

Actually, the conaninfo.txt for me is just for looking what are exact options we are using and use that information to run builds independently, and I would like to find another way to do it.

My original idea was like that:
My project depends on big libs A, B, C and a lot of smaller ones. A, B and C do not depend on each other and I would like to build them in parallel by doing `conan install my_conanfile.py --build A --build B --build C`. Is there a way to do it?

If not, then is there a way to run three instances of `conan install my_conanfile.py --build A` and `--build B` and `--build C`? 
Right now if I try it they are stuck on build order: for example, Conan decides that `--build` without parameters should happen in the order C A B. Therefore, when I run three separate builds for A B and C, installs for A and B wait until C completes even if they do not depend on each other!
I would like to know if I can explicitly skip building some library, or change the build order, so that my big libraries would be built simultaneously (note, "build" here includes downloading and everything).

**Comment by memsharded** [comment]
That is the thing: a package A that depends on another package B cannot be parallelized, it needs to wait for package B to finalize its build to start building itself.

The information of what can be built in parallel can be done with the "build-order" provided by Conan, that will return a list of lists, each inner list is a subgroup that can be built in parallel, but to proceed to the next subgroup, it needs to finish it first.
If your A, B, C packages are independent of each other, they should be able to be built in parallel without any issues, not sure what is not working there. You can launch 3 separate jobs in your CI, one job for each build without problems.

The idea is that you don't need to skip anything, but instead build the consumer package, with ``conan create .`` (in the ``mypkg`` folder containing the conanfile.py) or ``conan install mypkg/1.0@ --build=mypkg*``. Why is this not enough, am I missing something? Probably the issue is that you shouldn't be using a root ``my_conanfile.py`` all the time, but instead using the specific A, B, C conanfile or use the ``conan install <ref> --build=<ref>`` form instead?

**Comment by chulup** [comment]
> If your A, B, C packages are independent of each other, they should be able to be built in parallel without any issues, not sure what is not working there. You can launch 3 separate jobs in your CI, one job for each build without problems.

I'm trying to reduce build time locally first. CI build time is an issue too, but my development speed is a real problem when I need to try several builds on my machine. As such there is no CI jobs, just me running commands in terminal.

> The idea is that you don't need to skip anything, but instead build the consumer package, with conan create . (in the mypkg folder containing the conanfile.py) or conan install mypkg/1.0@ --build=mypkg*. Why is this not enough, am I missing something?

Three big packages I am talking about take a lot of time to download sources first, build time is secondary. I would be happy to run them concurrently. 
The exact command I run to build libraries is like that: `conan install .. --install-folder . --profile:build=default --profile:host=macos-10.13-clang13-debug --build=WebRTC --build=internal_lib`. The packages are being downloaded and built sequentially, taking a long time to do it.

One workaround I found is to use information from conaninfo.txt - grab options used to build WebRTC for example and run a command to build just it separately. It is doable but tedious (because of running `conan info` first, then reading conaninfo.txt). 

Another way to do it would be running `conan install` on MY project and request to build only one dependency of WebRTC, in another terminal run the same but build Qt, in another yet build internal_lib. I was unable to do it because Conan does not like skipping packages - and if it decided it needs Qt first then it won't event start working on WebRTC or my internal_lib.

**Comment by chulup** [comment]
Thank you for your patience!
At the end I decided to speed up the build times through `download_cache`, which requires me changing my recipes quite a bit.
