### ISSUE TITLE
[question] Cache conan results error

### ISSUE THREAD

**Issue by Kaaml** [conan-io/conan#13075]
### What is your question?

Hi, 

I have question according to conan caching in Github Workspaces. My project neeed to build few dependency which took about 45min, my idea is to cache ~/.conan directory to speed up build process. 
Everything would be fine if it were not this error:

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    bzip2/1.0.8 from 'conancenter' - Cache
    expat/2.5.0 from 'conancenter' - Cache
    gtest/1.8.1 from 'conancenter' - Cache
    libmysqlclient/8.0.30 from 'conancenter' - Cache
    libpq/14.5 from 'conancenter' - Cache
    lz4/1.9.4 from 'conancenter' - Cache
    openssl/1.1.1s from 'conancenter' - Cache
    pcre2/10.40 from 'conancenter' - Cache
    poco/1.12.4 from 'conancenter' - Cache
    sqlite3/3.39.4 from 'conancenter' - Cache
    tl-expected/1.0.0 from 'conancenter' - Cache
    zlib/1.2.13 from 'conancenter' - Cache
    zstd/1.5.2 from 'conancenter' - Cache
Packages
    bzip2/1.0.8:53b5fd22ba061620078deefdae9a437c5f693201 - Cache
    expat/2.5.0:8e589e066a19f700666be77ed94ff8e8bc88ee10 - Cache
    gtest/1.8.1:10f3c0a3a24a1055f3670e6694da4a93d078e663 - Cache
    libmysqlclient/8.0.30:c5ef57b516853ce6f3b2d8b82d356ce9e3c62201 - Build
    libpq/14.5:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Cache
    lz4/1.9.4:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Cache
    openssl/1.1.1s:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Cache
    pcre2/10.40:fd9a9b62bf1e3522e49e4c006b72bc34a2070df3 - Cache
    poco/1.12.4:b9fd8b5b0181d12f03a3a7138fe7518d734c5489 - Cache
    sqlite3/3.39.4:d4c90a44e87a0129d6c89e58d1337c25a5bec2b4 - Cache
    tl-expected/1.0.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    zlib/1.2.13:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Cache
    zstd/1.5.2:634eb14beaa4acb3dd5f1de8d7774c7748dabed3 - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
expat/2.5.0: Already installed!
gtest/1.8.1: Already installed!
libpq/14.5: Already installed!
lz4/1.9.4: Already installed!
openssl/1.1.1s: Already installed!
sqlite3/3.39.4: Already installed!
sqlite3/3.39.4: Appending PATH env var with : C:\Users\runneradmin\.conan\data\sqlite3\3.39.4\_\_\package\d4c90a44e87a0129d6c89e58d1337c25a5bec2b4\bin
tl-expected/1.0.0: Already installed!
zlib/1.2.13: Already installed!
zstd/1.5.2: Already installed!
ERROR: Error, the file to download already exists: 'C:\Users\runneradmin\.conan\data\libmysqlclient\8.0.30\_\_\dl\export\conan_sources.tgz'. [Remote: conancenter]
The 'libmysqlclient/8.0.30' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```

Where is conan cache saved? How to solve this problem?

Kaaml

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Kaaml 

Thanks for your question.

The Conan cache is the folder ``C:\Users\runneradmin\.conan``, where all the config and packages are stored.
The cache is not designed for concurrency, if it is being shared by more than 1 concurrent build job, then it might be an issue. It is also not designed to be portable, so the same cache cannot work for both Windows and Linux (specially in Conan 1.X, with the ``short_paths`` Windows issue).


Quick question: why is it building ``libmysqlclient`` while all other packages are not being built? What command are you using to obtain that log?

**Comment by Kaaml** [comment]
@memsharded 
_Quick question: why is it building libmysqlclient while all other packages are not being built?_
Because the cache is downloaded, and something is incorret in conan configuration, and this is how looks like. I don't know why. The earlier build, which is in cache sucessfully buidl all dependency and application.


 _What command are you using to obtain that log?_
 I'm using this [Action cache](https://github.com/actions/cache). My configuration looks following:
```
     - name: Cache conan modules
      id: cache-conan
      uses: actions/cache@v3
      env:
        cache-name: cache-conan-modules
      with:
        # conan cache files are stored in in C:/Users/runneradmin/.conan/
        path: |
          C:/Users/runneradmin/.conan
          C:/.conan
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
```

According to the paralel run of jobs - I don't think that there multiple instance which use the same files - so probably this is wrong path

**Comment by b1ackviking** [comment]
Hi @Kaaml

To cache Conan 1.x packages in GitHub Actions, you can save the `.conan/data` directory for every OS like this:

```
- name: Set environment variables
  run: echo CONAN_USER_HOME=${{ runner.temp }} >> ${{ github.env }}
- name: Cache Conan packages
  uses: actions/cache@v3
  with:
    path: ${{ env.CONAN_USER_HOME }}/.conan/data
    key: conandata-${{ runner.os }}-${{ hashFiles('conanfile.py') }}
    restore-keys: conandata-${{ runner.os }}-
```

For Conan 2.0 setting `conan_home=./.conan2` in the `.conanrc` file and saving `.conan2/p` directory seems to work as well.

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
