### ISSUE TITLE
Website: make package search more obvious

### ISSUE THREAD

**Issue by a-teammate** [conan-io/conan#1307]
This might seem like a very trivial change, but I heared some people figuring about where a list of provided packages can be found.
My first thought was that  maybe the searchbar could be placed more prominently but as I noticed the searchbar does not even contain anything suggesting it searches the package store.

Maybe change: `type keyword..` to `find package..`?

**Comment by Brunni** [comment]
I agree, that this can be improved as the same happend to me, when I visited the website.

"Try searching for your favourite package (e.g boost): [inputbox with boost prefilled]"

**Comment by lasote** [comment]
HI, @a-teammate @Brunni as you can see on the homepage we are moving to Bintray. Bintray offers many many improvements from the current conan.io site, and also there is a great team maintaining it, so we should close this issue and see if Bintray cover better your needs. Thanks for helping us!

**Comment by a-teammate** [comment]
yeah i saw that, awesome news!
PRs for packages hurray!
