### ISSUE TITLE
[bug] Issues with download_cache

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#13085]
### Environment details

* Operating System+version: Linux
* Compiler+version: n/a
* Conan version: 1.57.0
* Python version: 3.10.7

### Steps to reproduce

I have two potential problems with using the `download_cache`.

1. I tried to configure the `download_cache` according to the documentation: https://docs.conan.io/en/latest/configuration/download_cache.html. However, apparently this is not used everywhere? I used tools.files.get() to download a file and the setting was not applied. For this method, only settings in global.conf are used apparently. Not sure if this is a documentation issue or a bug in the implementation.

2. After setting a `download_cache` in my global.conf, it was used. But apparently ~ is not expanded in the setting. Not sure if that is intended either but it is unexpected:

        tools.files.download:download_cache=~/.conan/cache

    In this case, a subdirectory ~ was created in my package's source directory instead.

**Comment by memsharded** [comment]
Hi @fschoenm 

yes, the new conf decouples in 2 confs:
-  tools.files.download:download_cache
- core.download:download_cache

That allows caching only the parts that you want. In general ``core`` cache would not be necessary if having a fast server close enough, but ``tools.files`` cache might be more useful to cache heavy downloads from the internet

The ``~/`` is not expanded in profile files, but if you want to use jinja, you can put .jinja as the profile extension (not necessary in 2.0, all profiles will be jinja rendered), and you can use path methods there.

**Comment by fschoenm** [comment]
Isn't it good style to expand ~ (and maybe $HOME and other environment variables) everywhere? It would make for a better user experience. No specials like jinja2 and the files/config would be easier to share. 

I think I saw also ~ used by default (for the Conan cache in 1.0 I believe).

**Comment by memsharded** [comment]
> Isn't it good style to expand ~ (and maybe $HOME and other environment variables) everywhere? It would make for a better user experience. No specials like jinja2 and the files/config would be easier to share.

The problem is that Conan profiles can contain multitude of things, variables, values, etc. It is very easy that some users would have something like ``something=C:/Program~Files/...`` or the like in their profiles. So a replacement of the ``~`` by the user home is not possible in the profiles, and this is why explicit definition is the recommended approach

The ``~`` was allowed in some built-in 1.X ``conan.conf`` items, like the storage_path, but not replaced everywhere. Applying ``~`` expansion to every potential ``conf`` item that could be a path sounds a bit too much, but we could check

**Comment by fschoenm** [comment]
Hm, I see. Unfortunately it's just what I intuitively did when adding the `download_cache` setting (also because right next to it was the `storage_path` setting which used a ~). It's really confusing to figure out why the download cache doesn't work then and I just stumbled over it accidentally when checking the source directory of my package.

Maybe it would be ok to expand ~ in paths on Linux/Unix systems but not on Windows.
