### ISSUE TITLE
[question] one of my test package has an extra dependencies, which is missing on server but I cannot do conan test --build=missing

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#13088]
### What is your question?

I have a package A that has a test B, the test B has a dependency on C.

when I do

conan test B A

I get
ERROR: Missing prebuilt package for 'libev/4.33'

It appears that I cannot pass --build=missing to the conan test function.

And since C is not a dependency in anyway to A, I fail to see how to handle this.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
You mean the ``pkga`` has a ``test_package/conanfile.py`` for testing ``pkga``? is that ``test_package`` your B?

The ``conan test`` command is intended as an auxiliary way to call the ``test_package`` functionality, not for regular packages.
Also, the general recommendation for ``test_package`` is that they are as simple as possible, just a simple compile+link+run against the tested package, but is not intended for functional or unit testing the package.

If you have other separate project with a recipe ``pkgb``, then the recommended way is ``conan install`` + ``conan build`` (only ``conan build`` in 2.0), and there you will be able to pass any ``--build`` arguments you might need.

**Comment by hpe-ykoehler** [comment]
I think I misunderstood that part "they are as simple as possible".

I also somehow got confused since "conan test" first param is the name of a test, but it seems like test_package and test_v1_package are the only value for that argument.
