### ISSUE TITLE
ConanException Error 3221225477

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#13094]
### What is your question?

Hi

I am getting this error when running Conan Create and need help troubleshooting the error. How do I troubleshoot this error? This same code works on other recipe file but not the one I am currently running for some reason. I am using Conan 2b6.

bsw_project/1.0.4: WARN: Build folder C:\Users\bq824\.conan2\p\tmp\ac2fc515d6012cc8\b\BSW
ERROR: bsw_project/1.0.4: Error in build() method, line 193
        self.python_requires["csarbuildenvrequires"].module.build_target(self)
while calling 'build_target', line 243
        self.run(' make --version')
        ConanException: Error 3221225477 while executing

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

The error seems to be that the execution of ``make --version`` is failing. It would be good to know about that ``make`` executable, where is it, how was it compiled, does it have dependencies like shared libraries (one possible failure could be failing to load necessary shared libraries, in general it is very recommended to link tools like ``make`` statically). The error seems to be like ``make`` was found (otherwise some error like "make is not found installed" is expected), but it is crashing at runtime:

From https://stackoverflow.com/questions/10306272/apache-crashing-parent-child-process-exited-with-status-3221225477-restarti: 

> The error code 3221225477 is 0xC0000005 in hex, which on Windows is:

> #define STATUS_ACCESS_VIOLATION  ((NTSTATUS)0xC0000005L)
Access violation is Windows' version of "segmentation fault", which simply said means that the program tried to access a memory which is not allocated. This can happen for a lot of different reasons, but mostly (if not always) is a bug in the program.

But it seems a bug in ``make`` execution

**Comment by Ed-CMI** [comment]
Hi Deigo

The same make utility is used in two different recipe files but it works in the one recipe file but not the other one. The make utility is installed by a tool_requires files. When I compared the PATH variable defined for both recipe file they both reference the same recipe location for make. For ex, when running the cstart recipe file it pass with the following output
cstart/1.0.4: Run: make --version
GNU Make 4.1
Built for x86_64-pc-mingw32
Copyright (C) 1988-2014 Free Software Foundation, Inc
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/license/gpl.html>

When running the other recipe file on the same machine it gets this error. Both recipe file reference make location at C:\Users\bq824\.conan2\p\78d2afa819fbc7a4\p\bin. Attached are the two bat files created. The one labeled cstart.txt works and the one label bsw_project does not work.

There is no dependancy with any shared libaries
[cstart.txt](https://github.com/conan-io/conan/files/10708036/cstart.txt)
[bsw_project.txt](https://github.com/conan-io/conan/files/10708037/bsw_project.txt)

**Comment by memsharded** [comment]
Yes, indeed the paths look the same in both cases.

Just to make sure, you could try adding a ``self.run("which make")`` just before the invocation, and report the path, to rule out that in the second case another make would be found.
Then, I'd try to dump the environment and compare, to see if there could be something different there (``self.run("SET")``)

**Comment by Ed-CMI** [comment]
When trying to run self.run('which make') the Conan exception occurs. I then removed make and ran self.run('SET') and the same error occurs.

**Comment by memsharded** [comment]
Sorry, ``which`` is a cmder/posix specific command, not Windows. Try ``where make`` instead. So:

```python
self.run("where make")
self.run("SET")
self.run("make --version")
```

**Comment by Ed-CMI** [comment]
Any command I seem to put in the self.run command gives the same exception. If I remove the self.run and just print some line out to the console it works

**Comment by memsharded** [comment]
Which exception? all of them cause ``ConanException: Error 3221225477 while executing``?

**Comment by Ed-CMI** [comment]
Yes. Its the same exception (ConanException Error 3221225477)  everytime.

**Comment by memsharded** [comment]
Then I have absolutely no idea of what could be happening. We would need something to reproduce the behavior to investigate, like a couple of self contained ``conanfile.py`` that produces this error. The best is to produce a "minimal reproducible example", trimming down your code to something self-contained that produces the issue.

You can also try to send the 3 full recipes (working consumer, failing consumer and python_requires one), to info@conan.io, we could try to have a look, but without being able to reproduce, it might not be enough.

**Comment by Ed-CMI** [comment]
Hi Diego. I think we found out what is causing the error when executing self.run. The attached file shows BSW_PROJECT_SRCFILES. This environment variable is used in the makefile to compile all the source files. Looks there there is some limit that we are exceeding when execting self.run. If this environment variables reduce the number of files to less than 80 files the process works ok. Anything more than 80 and the ConanException occurs. Is there some type of limit on the number of characters we can set for the environment varaibles?
[bsw_project_srcenv.txt](https://github.com/conan-io/conan/files/10711020/bsw_project_srcenv.txt)

**Comment by memsharded** [comment]
Yes, totally. Windows env-vars have quite low limits in length. They are definitely not a good mechanism to pass such build information (like full list of source files), please don't use env-vars for that purpose.

In general, environment variables are *not* a mechanism to transfer information between Conan packages from recipe to recipe, and are more intended to transfer information from Conan to tools, like for example the CXX envvar, or the PATH env-var to put some executable in the path and make it available.

Conan is not a build system, so in general it shouldn't be managing information of list of source files to build. If for some reason you need to pass large amount of information, the possible approaches would be:
- The general approach of not passing source information but passing built artifacts. Is it not possible to compile the sources into a library in the package, then pass the library to the consumers?
- Use ``self.cpp_info.srcdirs`` to pass information about the directories containing the files (not every single file). 
- Write a file in the package that contain such list of sources. The consumer of the package would read the file to get the list of sources. This approach is also way more powerful, as you can write json files with the structure you want, adding folder information, or any other metadata or information is relevant.

**Comment by Ed-CMI** [comment]
[conanautotoolsdeps.txt](https://github.com/conan-io/conan/files/10714374/conanautotoolsdeps.txt)


Hi Diego

I have two questions regarding this attached bat file. In this file conan create LDFLAGS and added all the directories for our library files generated from the component recipe files. First, why is it putting the directories of our libraries in LDFLAGS? Shouldn't these library paths been defined in the LIBS variable instead of the LDFLAGS? Second question is that I'll assume we are going to have the same problem with LDFLAGS as we did with the environment variable that we created for all source files. There are going to be close to 100 or more library files that need to be linked.

**Comment by memsharded** [comment]
> I have two questions regarding this attached bat file. In this file conan create LDFLAGS and added all the directories for our library files generated from the component recipe files. First, why is it putting the directories of our libraries in LDFLAGS?

https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html says that folder to be defined with ``-L<folder>`` should be LDFLAGS. It is true that it also says that the LIBS should be named LDLIBS and ``AutotoolsDeps`` is not following the convention but using the ``LIBS`` variable, that seemed more used in open source libraries. We will check if it makes sense to add this LDLIBS too.

> Second question is that I'll assume we are going to have the same problem with LDFLAGS as we did with the environment variable that we created for all source files. There are going to be close to 100 or more library files that need to be linked.

The library folder would look something like: C:/Users/bq824/.conan2/p/t/bsw_pa20bad3822e77/p/lib, that is around 50 chars.

The theoretical limit is 32K chars, but in practice the limit comes by the SET, which is 8191 chars. 8191/50 = 160 paths it could store, so you might be ok.
If you hit the limit you will need some other generator, but that can be done with Conan:
- Create your own generator that iterates ``self.dependencies.host`` and put all the folders inside a mylibs.mak file that declares a MYLIBPATHS variable with all the values
- Put the generator in a python requires
- Add the python-requires to your recipes and call it in the ``generate()`` method
- Include the ``mylibs.mak`` file in your Makefiles, and use the MYLIBPATHS defined var at your will

The env-vars mechanisms are very intended for third party open source libraries and projects, that you don't have access to the build scripts, and you need to inject things without modifying their build scripts, so modifying the environment is the only way.
For your own projects, creating your own build files is not only more flexible and powerful, but also it is typically easier for developers to understand and debug, at the end of the day, they have files there they can easily open with their editors and see the paths easily, grep for occurences, etc.

**Comment by Ed-CMI** [comment]
Hi Deigo

I read the following from the attached link and just wanted to make sure I understood your response. Do you plan on splitting linker options into LDFLAGS and libraries into LBLIBS? 

LDFLAGS
Extra flags to give to compilers when they are supposed to invoke the linker, ‘ld’, such as -L. Libraries (-lfoo) should be added to the LDLIBS variable instead.

LDLIBS
Library flags or names given to compilers when they are supposed to invoke the linker, ‘ld’. LOADLIBES is a deprecated (but still supported) alternative to LDLIBS. Non-library linker flags, such as -L, should go in the LDFLAGS variable.

**Comment by memsharded** [comment]
> I read the following from the attached link and just wanted to make sure I understood your response. Do you plan on splitting linker options into LDFLAGS and libraries into LBLIBS?

This is already done. The integration is already sending ``-L<path>`` flags to LDFLAGS and ``-l<lib>`` flags to LIBS. The possible improvement that could be done is standardizing and sending the ``-l<lib>`` flags to LDLIBS (besides LIBS, or instead of, we need to check what could break).

**Comment by Ed-CMI** [comment]
Sorry I misread that statement. I think we are still going to have an issue with the LDFLAGS limit being exceeded. Is there a way to prevent the LDFLAGS from being updated? I'll assume that I cannot use AutoToolsDeps anymore since it will automatically update LDFLAGS

**Comment by memsharded** [comment]
You can always intercept it and remove it:
```python
def generate(self):
     deps = AutotoolsDeps(self)
     deps.environment.unset("LDFLAGS")
     deps.generate()
```
But at this point, you need that information anyway, it is not that it will work by removing the env-var. So going with your own generator would be the way to go.

**Comment by Ed-CMI** [comment]
Thxs. I will close this ticket.
