### ISSUE TITLE
[bug] DeprecationWarning for `imp`

### ISSUE THREAD

**Issue by progician** [conan-io/conan#13106]
### Environment details

* Operating System+version: macOS Ventura 13.2
* Compiler+version: Apple clang version 14.0.0 (clang-1400.0.29.202)
* Conan version: develop/1.58
* Python version: 3.11.1

### Steps to reproduce

1. Set up the "normal" developer environment with a recent Python, like 3.11.1
2. Run the model tests:  `python -m tox -- conans/test/unittests/model`

### Logs

The log of the tests will expose the following warning:

```
conans/client/loader.py:2
  /Users/gyula.gubacsi/Contrib/conan/conans/client/loader.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    import imp
```

**Comment by AbrilRBS** [comment]
Hi @progician, thanks a lot for the time you took to discuss this issue, we really appreciate it even if ultimately we won't address the specified issue. As a proper discussion already took place in the PR, I'll close this issue and people can look into the PR comments to see our rationale behind not fixing cases like this.

Again, thanks a lot :)
