### ISSUE TITLE
Trouble with compiler versions - cannot build a new test package

### ISSUE THREAD

**Issue by SuperV1234** [conan-io/conan#1310]
I work on Arch Linux x64 and I have three compilers installed:

* g++ 6.3.0 in `/usr/bin/`
* clang++ 4.0.0 in `/usr/bin/`
* g++ 8.0.0 (trunk) in `/usr/local/bin/`

I want to use both g++ 8 and clang++ 4 for my day-to-day development and my packages. I wanted to try out conan.io, and frustratingly couldn't get it to work with my setup. 

---

I ran the following commands:

```
mkdir example && cd example
conan new Hello/0.1@demo/testing -t
conan test_package
```

I got this error:

> ERROR: Invalid setting '7.0' is not a valid 'settings.compiler.version' value.
> Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5.1', '5.2', '5.3', '5.4', '6.1', '6.2', '6.3']
> Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

I read the FAQ, and changed my `~/.conan/settings.yml`'s `gcc` version array to:

```
version: ["4.1", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9", "5.1", "5.2", "5.      3", "5.4", "6.1", "6.2", "6.3", "7.0", "8.0"]
``` 

I retried running

```
conan test_package
```

and got this error output:

```
Exporting package recipe
Linter warnings
    WARN: Linter. Line 2: Unused import os
WARN: Conanfile doesn't have 'description'.
It is recommended to add it as attribute
Hello/0.1@demo/testing: The stored package has not changed
Requirements
    Hello/0.1@demo/testing from local
Packages
    Hello/0.1@demo/testing:0cfe908cf58c05e8436c7b33ddc7556fabfe39c5

Hello/0.1@demo/testing: WARN: Forced build from source
Hello/0.1@demo/testing: Building your package in /home/vittorioromeo/.conan/data/Hello/0.1/demo/testing/build/0cfe908cf58c05e8436c7b33ddc7556fabfe39c5
Hello/0.1@demo/testing: Copying sources to build folder
Hello/0.1@demo/testing: Generated cmake created conanbuildinfo.cmake
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
CMake Error at ../conanbuildinfo.cmake:201 (message):
  Incorrect 'gcc' version 'compiler.version=7.0' is not the one detected by
  CMake: 'GNU=6.3'
Call Stack (most recent call first):
  ../conanbuildinfo.cmake:244 (conan_error_compiler_version)
  ../conanbuildinfo.cmake:294 (check_compiler_version)
  ../conanbuildinfo.cmake:48 (conan_check_compiler)
  CMakeLists.txt:3 (conan_basic_setup)


-- Configuring incomplete, errors occurred!
See also "/home/vittorioromeo/.conan/data/Hello/0.1/demo/testing/build/0cfe908cf58c05e8436c7b33ddc7556fabfe39c5/CMakeFiles/CMakeOutput.log".

Hello/0.1@demo/testing: ERROR: Package '0cfe908cf58c05e8436c7b33ddc7556fabfe39c5' build failed
Hello/0.1@demo/testing: WARN: Build folder /home/vittorioromeo/.conan/data/Hello/0.1/demo/testing/build/0cfe908cf58c05e8436c7b33ddc7556fabfe39c5
Hello/0.1@demo/testing: WARN:   File "/home/vittorioromeo/.conan/data/Hello/0.1/demo/testing/export/conanfile.py", line 27, in build
Hello/0.1@demo/testing: WARN:     self.run('cmake hello %s %s' % (cmake.command_line, shared))
Hello/0.1@demo/testing: WARN:   File "/usr/lib/python3.6/site-packages/conans/model/conan_file.py", line 243, in run
Hello/0.1@demo/testing: WARN:     raise ConanException("Error %d while executing %s" % (retcode, command))
Hello/0.1@demo/testing: WARN: conans.errors.ConanException: Error 256 while executing cmake hello -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="7.0" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -Wno-dev 
ERROR: Hello: Error 256 while executing cmake hello -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="7.0" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -Wno-dev 
```

For some reason the CMake invocation detects my g++ 6.3.0 instead of my g++ 8.0 (as it would when manually invoking `cmake`). Additionally `CONAN_COMPILER_VERSION` is automatically set to `7.0` for some reason, which is neither 6.3 or 8.0!

I tried googling the error but didn't find any solution. Why is this happening? How can I control what compiler to use when calling `conan test_package`?

**Comment by memsharded** [comment]
``conan test_package`` and ``conan install`` takes as arguments, in order:
- The default settings defined in ``conan.conf`` file
- The settings specified in a profile specified in command line (``-profile``)
- The settings specified in command line ``-s compiler=gcc``

Even if you add that compiler to the default ``settings.yml`` that is just a definition of accepted setting, to make sure that everybody uses the same spelling, etc. You probably want to change your ``conan.conf`` defaults, create a profile, or pass compiler and compiler version in the command line. Please try and tell me if this helps.

**Comment by SuperV1234** [comment]
I managed to get it to work by changing `compiler.version` to `8.0` in `~/.conan/conan.conf` and by running `export CXX=/usr/local/bin/g++` before running `conan tests_package`. 

I couldn't find a way to specify the full compiler path to conan. This solution seems hackish - what's the idiomatic way of dealing with my situation (i.e. multiple versions of the same compiler installed in different paths)?

**Comment by memsharded** [comment]
Great that you made it work.

Yes, the most idiomatic way to express paths to compilers are environment variable. Conan is able to manage environment variables in different ways:
- In the command line: ``conan test_package -e CXX=...``. They can be also set per package, like ``-e MyPKg:CXX=...```
- The above is still a bit manual. Much better to handle them in profiles, defined as:
```
[settings]
compiler=gcc
compiler.version=8.0
compiler.libcxx=libstdc++
compiler.build_type=Release
[env]
CC=/usr/bin/gcc
CXX=/usr/bin/g++
```
Profiles are just text files that can be even stored in the repo, in a dedicated repo, to share with the team/company/community. They are named, you can have many of thems. They can be also modified in command line, for example for that profile if you want to change the build_type, you can do it in the command line with ``conan test_package -pr=mygcc8_profile -s build_type=Debug``.

Per package env variables can be also defined in profiles.

There could be another approach, that is to use ``build_requires`` feature. You can create packages for tools, that define environment variables, and depend on those requirements which will inject the environment variables in dependencies. I think you are good with the above, but ask if you want to know more about this one. Thanks!

**Comment by SuperV1234** [comment]
Thank you for the clarifications. Greatly appreciated :)

**Comment by memsharded** [comment]
Thanks! :) here to help, do not hesitate to submit any further question.

**Comment by AmirhosseinBayat** [comment]
Hi @memsharded 
I'm new to conan and cmake.
I have a problem to compile qt project on windows 7, I used this [guide](https://github.com/MaxRis/webkit/wiki/Building-QtWebKit-on-Windows-(Conan)) to compile source but I got bellow error:
```terminal
Cannot read C:/qt-build/qtwebkit/release/Source/WebKit/qt_lib_webkit.pri: No such file or directory
Cannot read C:/qt-build/qtwebkit/release/Source/WebKit/qt_lib_webkitwidgets.pri: No such file or directory
Reading C:/qt5/qtwebkit/Tools/qmake/projects/qtpng/qtpng.pro [C:/qt-build/qtwebkit/Tools/qmake/projects/qtpng]
Reading C:/qt5/qtwebkit/Tools/qmake/projects/qtjpeg/qtjpeg.pro [C:/qt-build/qtwebkit/Tools/qmake/projects/qtjpeg]
Reading C:/qt5/qtwebkit/Tools/qmake/projects/generate_cmake_toolchain_file.pro [C:/qt-build/qtwebkit/Tools/qmake/projects]

Generating CMake toolchain file C:/qt-build/qtwebkit/qmake_toolchain.cmake

set(CMAKE_C_COMPILER "gcc")
set(CMAKE_CXX_COMPILER "g++")

Reading C:/qt5/qtwebkit/Tools/qmake/projects/generate_forwarding_pris.pro [C:/qt-build/qtwebkit/Tools/qmake/projects]
Project MESSAGE: Writing C:/qt-build/qtwebkit/mkspecs/modules/qt_lib_webkit.pri
Project MESSAGE: Writing C:/qt-build/qtwebkit/mkspecs/modules/qt_lib_webkitwidgets.pri
Reading C:/qt5/qtwebkit/Tools/qmake/projects/run_cmake.pro [C:/qt-build/qtwebkit/Tools/qmake/projects]

Running  cmake C:/qt5/qtwebkit -G Ninja -DPORT=Qt -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\qt-build\qtwebkit\qmake_toolchain.cmake -DUSE_LIBHYPHEN=OFF -DQt5_DIR="C:/Qt/Qt5.12.0/5.12.0/mingw73_64/lib/cmake/Qt5" -DQT_BUNDLED_JPEG=1 -DJPEG_LIBRARIES=C:/qt-build/qtwebkit/lib/libqtjpeg.a -DJPEG_INCLUDE_DIR=C:/qt5/qtwebkit/../qtbase/src/3rdparty/libjpeg/src -DQT_BUNDLED_PNG=1 -DPNG_INCLUDE_DIRS=C:/qt5/qtwebkit/../qtbase/src/3rdparty/libpng -DPNG_LIBRARIES=C:/qt-build/qtwebkit/lib/libqtpng.a -DQT_CONAN_DIR=C:/qt-build/qtwebkit

-- Could NOT find Ruby (missing: RUBY_LIBRARY) (found suitable version "2.5.3", minimum required is "1.9")
-- Current conanbuildinfo.cmake directory: C:/qt-build/qtwebkit
CMake Error at C:/qt-build/qtwebkit/conanbuildinfo.cmake:485 (message):
  Incorrect 'gcc' version 'compiler.version=5.3' is not the one detected by
  CMake: 'GNU=7.3'
Call Stack (most recent call first):
  C:/qt-build/qtwebkit/conanbuildinfo.cmake:528 (conan_error_compiler_version)
  C:/qt-build/qtwebkit/conanbuildinfo.cmake:579 (check_compiler_version)
  C:/qt-build/qtwebkit/conanbuildinfo.cmake:293 (conan_check_compiler)
  Source/cmake/OptionsQt.cmake:17 (conan_basic_setup)
  Source/cmake/WebKitCommon.cmake:50 (include)
  CMakeLists.txt:137 (include)


-- Configuring incomplete, errors occurred!
See also "C:/qt-build/qtwebkit/release/CMakeFiles/CMakeOutput.log".
See also "C:/qt-build/qtwebkit/release/CMakeFiles/CMakeError.log".
Project ERROR: Running cmake failed
```
it took me two week and still I can't solve this issue! please tell me how I can solve this issue?
