### ISSUE TITLE
[question] test_package cannot find an include file

### ISSUE THREAD

**Issue by rturrado** [conan-io/conan#13119]
### What is your question?

Hi!

I have the following [GitHub project](https://github.com/rturrado/tree-gen.git), a fork of the `tree-gen` project.

That project defines two targets, a `tree-gen` executable, and a `tree-lib` library. I'm trying to create a conan package, which would include the `tree-lib` library. This is the latest commit with my changes in order to attempt that package creation (pacmans branch): 9dc2185f1b1e7c7bc5a581f977d1a53c47088715

I started with: `conan new tree-gen/0.1 --template=cmake_lib`.
- Since my project already had a `CMakeLists.txt` file, I removed the generated `CMakeLists.txt` file.
- I also changed `conanfile.py`:
  - I changed `self.cpp_info.libs = ["tree-gen"]` to `self.cpp_info.libs = ["tree-lib"]`, since that's the library name.
  - I set `export_sources = "CMakeLists.txt", "cmake/*", "generator/*", "include/*", "src/*"`, this to get the package compiling.
- I also replaced the contents of `test_package/src/example.cpp` with those of `tests/test-annotatable.cpp`.

When I run: `conan create . demo/testing`, the project compiles, but `test_package` fails, not being able to find the `test_annotatable.hpp` include file.

These are the complete logs for `(test package)` section:

```
tree-gen/0.1@demo/testing (test package): Generator txt created conanbuildinfo.txt
tree-gen/0.1@demo/testing (test package): Generator 'VirtualRunEnv' calling 'generate()'
tree-gen/0.1@demo/testing (test package): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
tree-gen/0.1@demo/testing (test package): Generator 'CMakeDeps' calling 'generate()'
tree-gen/0.1@demo/testing (test package): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
tree-gen/0.1@demo/testing (test package): Generator 'CMakeToolchain' calling 'generate()'
tree-gen/0.1@demo/testing (test package): Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
tree-gen/0.1@demo/testing (test package): If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/rturrado/projects/tree-gen/test_package/build/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
tree-gen/0.1@demo/testing (test package): Generator 'VirtualBuildEnv' calling 'generate()'
tree-gen/0.1@demo/testing (test package): Aggregating env generators
tree-gen/0.1@demo/testing (test package): Generated conaninfo.txt
tree-gen/0.1@demo/testing (test package): Generated graphinfo
Using lockfile: '/home/rturrado/projects/tree-gen/test_package/build/generators/conan.lock'
Using cached profile from lockfile
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
tree-gen/0.1@demo/testing (test package): Calling build()
tree-gen/0.1@demo/testing (test package): CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/rturrado/projects/tree-gen/test_package/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/rturrado/projects/tree-gen/test_package/."
-- Using Conan toolchain: /home/rturrado/projects/tree-gen/test_package/build/generators/conan_toolchain.cmake
-- Conan: Target declared 'tree-gen::tree-gen'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rturrado/projects/tree-gen/test_package/build/Release
tree-gen/0.1@demo/testing (test package): CMake command: cmake --build "/home/rturrado/projects/tree-gen/test_package/build/Release" '--' '-j16'
[ 50%] Building CXX object CMakeFiles/example.dir/src/example.cpp.o
/home/rturrado/projects/tree-gen/test_package/src/example.cpp:3:10: fatal error: tree-annotatable.hpp: No such file or directory
    3 | #include "tree-annotatable.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/example.dir/build.make:76: CMakeFiles/example.dir/src/example.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/example.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
ERROR: tree-gen/0.1@demo/testing (test package): Error in build() method, line 22
	cmake.build()
	ConanException: Error 2 while executing cmake --build "/home/rturrado/projects/tree-gen/test_package/build/Release" '--' '-j16'
```

I don't know if I am doing something wrong when creating the conan package. It may also be that the include files are not exported correctly with the `tree-lib` library. The test package is linking against `tree-lib` but, if the include files are not exported correctly, this error would make total sense.

Many thanks for your help.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rturrado 

Thanks for your question and your detailed report.
It seems you are missing to link with the right target in your ``test_package/CMakeLists.txt``:
```cmake
add_executable(example src/example.cpp)
target_link_libraries(example tree-gen::tree-gen)
```

After that, it is finding the header, but I get another error:
```
In file included from /home/conan/.conan/data/tree-gen/0.1/_/_/package/7fa3148f741307b51a958483d8a2d2dd66cf0ac7/include/tree-annotatable.hpp:14:0,
                 from /home/conan/conanws/support/tree-gen/test_package/src/example.cpp:3:
/home/conan/.conan/data/tree-gen/0.1/_/_/package/7fa3148f741307b51a958483d8a2d2dd66cf0ac7/include/tree-cbor.hpp:8:39: fatal error: tree-default-config.hpp.inc: No such file or directory
 #include "tree-default-config.hpp.inc"
```

But I think this is a package-related issue, like that .hpp.inc file has not been packaged. Maybe you know better what it coudl be?

**Comment by rturrado** [comment]
Hi @memsharded ,

Thanks to you for your help!

Yes, my `tree-gen` project has an `include` folder, and that include folder contains `*.hpp`, `*.hpp.inc`, and `*.cpp.inc` files. It seems only `*.hpp` files have been copied to the package. May it be because conan copies `*.hpp` by default and I have to copy files with other extensions by myself (this rings a bell)? What should be the proper way to do that copy, a copy command in `package_info()`?

By the way, it seems the package's `include` folder (in the conan cache) has an `include` subfolder. Is this something to do with declaring `include/*` in `export_sources`? I remember if I didn't do that, the project wouldn't even compile during `conan create`.

**Comment by memsharded** [comment]
> May it be because conan copies *.hpp by default and I have to copy files with other extensions by myself (this rings a bell)? What should be the proper way to do that copy, a copy command in package_info()?

If you are using ``cmake.install()`` functionality, then the ``CMake`` code should already complete to do that by itself. If it is not possible to modify that code, or simply the CMake doesn't contain packaging code, sure, using a ``copy()`` in the ``package()`` method (not in the ``package_info()``, note that this is the files were not packaged correctly) is the way to go.

> By the way, it seems the package's include folder (in the conan cache) has an include subfolder. Is this something to do with declaring include/* in export_sources? I remember if I didn't do that, the project wouldn't even compile during conan create.

This also depends on your local layout and your copy patterns. If you have the include folder you want to:
```python
copy(self, "*.h", src=os.path.join(self.source_folder, "include"), ....)
```
To copy starting from the ``include`` subfolder. Otherwise, if it is copying from the root folder and the ``dst`` is ``include``, it will create the nested ``include/include`` subfolder

**Comment by rturrado** [comment]
Many thanks @memsharded !

That was it. I basically had to fiddle with my `tree-gen` project's `CMakeLists.txt` in order to install not only `*.hpp` files but `*.hpp.inc` and `*.cpp.inc` too.

```
  install(
     DIRECTORY "$<TARGET_PROPERTY:tree-lib,INTERFACE_INCLUDE_DIRECTORIES>"
     DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
-    FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp"
+    FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp" PATTERN "*.hpp.inc" PATTERN "*.cpp.inc"
  )
```

**I think we can close this issue now**, as I've got an answer for my initial question. 👏

---

If possible though, I would like to ask you about some hook warnings I'm getting when running `conan create`. I don't know if/how I should address some/all of them.

1) Recipe folder size is too large (809 KB, bigger than 256 KB): can this be due to the fact that I'm including too many things in `exports_sources`? But I need them to create the package successfully (or that's what I think...).

```
[HOOK - conan-center.py] pre_export(): ERROR: [RECIPE FOLDER SIZE (KB-H009)] The size of your recipe folder (809.166015625 KB) is larger than the maximum allowed size (256KB). (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H009)
```

2) Attribute `url` not pointing to `conan-center-index`: I have it pointing to my self-hosted artifactory, e.g. `"http://localhost:8081/artifactory/api/conan/rturradocenter"`. Should I really make it point to `conan-center-index` even if I'm using a self-hosted artifactory?

```
[HOOK - conan-center.py] pre_export(): ERROR: [CONAN CENTER INDEX URL (KB-H027)] The attribute 'url' should point to: https://github.com/conan-io/conan-center-index (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H027)
```

3) Some files not ending in newline: but the point is, why is conan even looking at those files? They are ignored by git. Could I tell the `pre_export` hook to ignore them as well?

```
[HOOK - conan-center.py] pre_export(): ERROR: [NO FINAL ENDLINE (KB-H041)] File '/home/rturrado/projects/tree-gen/.idea/modules.xml' does not end with an endline (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H041)
```
4) Missing `test_v1_package`: I understand it's good to start being v2 compliant.

```
HOOK - conan-center.py] pre_export(): ERROR: [TEST V1 PACKAGE FOLDER (KB-H073)] The test_package seems be prepared for Conan v2, but test_v1_package is missing. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H073)
```

5) Missing `conandata.yml`: I understand this should be almost mandatory. A file including GitHub URLs and commit IDs for the different package releases, patches, and so on (I've tried with an empty file and that, at least, removed the warning).

```
[HOOK - conan-center.py] pre_source(): ERROR: [IMMUTABLE SOURCES (KB-H010)] Create a file 'conandata.yml' file with the sources to be downloaded. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H010) 
```

6) Missing `licenses` folder.

```
[HOOK - conan-center.py] post_package(): ERROR: [PACKAGE LICENSE (KB-H012)] No 'licenses' folder found in package: /home/rturrado/.conan/data/tree-gen/0.1/demo/testing/package/174df609440df17baf334e1f5953cca909f2ae18  (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H012)
```

I've tried adding this line to the `package` function, but without luck:

```
copy(self, "LICENSE.md", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))
```

**Comment by memsharded** [comment]
Quick question, do you intend to submit this to ConanCenter with a PR to ``conan-center-index``?  If not, just simply drop the ConanCenter hooks, they exist for helping in the contribution process to ConanCenter, but not necessary for your own recipes and packages.

If you intend to submit to ConanCenter, then the process is slightly different, because you dont ``export_sources`` the sources, but instead you implement a ``source()`` method that downloads the github tarball defined in the ``conandata.yml`` (this is why conandata.yml is mandatory for ConanCenter). You should start from a fork of ``conan-center-index`` and add there, a good idea is starting with some of the templates).

Closing this issue as solved. If the above about hooks helps, good, if not, maybe the best would be to open a new dedicated ticket for it, thanks!

**Comment by rturrado** [comment]
Thanks for the explanations @memsharded !

I may submit this as a ConanCenter package in a future. At the moment, I just wanted to test the package creation.

It makes sense that most of those hook errors should get fixed once I change the process to submit the package to ConanCenter.
