### ISSUE TITLE
[bug] conan.run(cmd, env="conanbuild") doesn't work on windows in test_package

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#13113]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: N/A
* Conan version: 1.58.0
* Python version: 3.11.1

### Steps to reproduce

It doesn't look like `conan.run(cmd, env="conanbuild")` updates the conanbuild environment correctly when run on windows. To replicate, you can follow these steps:

1. `conan remote add mtolympus-conan https://mtolympus.jfrog.io/artifactory/api/conan/mtolympus-conan`
2. `git clone https://github.com/samuel-emrys/python-virtualenv.git`
3. `cd python-virtualenv`
4. `git checkout feature/4-add-test-package`
5. `conan create .`

In this case, the `bindir` is not prepended to the `PATH`, and so `sphinx-build` is not discovered on the path. Am I doing something incorrect here? The code that replicates this is in [`test_package/conanfile.py`](https://github.com/samuel-emrys/python-virtualenv/blob/73cc829633de78437b42391039894daccf9a05f5/test_package/conanfile.py#L27-L31)

### Logs

To save you actually doing this, see the logs of a windows github actions run [here](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4163893956/jobs/7204834508#step:6:238). The equivalent statement on linux works, as per the github actions log [here](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4163893956/jobs/7204834696#step:5:225).

It doesn't look like  `conanbuildenv-release-x86_64.bat` is being populated correctly - it seems to be missing any mention of `PATH`:

```
@echo off
setlocal
echo @echo off > "C:\Users\user\projects\python-virtualenv\test_package\build\147a2f5e78ab557959d590969b349996393eef0d\deactivate_conanbuildenv-release-x86_64.bat"
echo echo Restoring environment >> "C:\Users\user\projects\python-virtualenv\test_package\build\147a2f5e78ab557959d590969b349996393eef0d\deactivate_conanbuildenv-release-x86_64.bat"
for %%v in () do (
    set foundenvvar=
    for /f "delims== tokens=1,2" %%a in ('set') do (
        if /I "%%a" == "%%v" (
            echo set "%%a=%%b">> "C:\Users\user\projects\python-virtualenv\test_package\build\147a2f5e78ab557959d590969b349996393eef0d\deactivate_conanbuildenv-release-x86_64.bat"
            set foundenvvar=1
        )
    )
    if not defined foundenvvar (
        echo set %%v=>> "C:\Users\user\projects\python-virtualenv\test_package\build\147a2f5e78ab557959d590969b349996393eef0d\deactivate_conanbuildenv-release-x86_64.bat"
    )
)
endlocal
```

Are there different assumptions between linux and windows about whether `bindir` is prepended to the `PATH`? This also happens when trying to us the run environment rather than the build. Any help is appreciated.

**Comment by memsharded** [comment]
Hi @samuel-emrys 

Thanks for your report and your reproducible case, that really helps.

It seems the issue is that you are not using the ``--profile:build``. The ``VirtualBuildEnv`` will collect information directly to the ``conanbuild`` env-var scripts from the "build" context.

The workaround that some users are doing, even if it sounds a bit too hacky for me, is something like injecting ``env="conanrun"`` instead, if the ``settings_build`` attribute is not defined (it is when using the 2 profiles), and leaving ``env="conanbuild"`` otherwise. I am not sure if this workaround covers all cases, just that I have seen it. Of course the recommended solution would be to pass ``-p:b=default`` and start running with the new 2 profiles approach as soon as possible, as Conan 2.0 due this month, will always use this approach by default.

**Comment by samuel-emrys** [comment]
Hi @memsharded thanks for the quick response. I've tried [adding dual profiles](https://github.com/samuel-emrys/python-virtualenv/blob/afd6f2eaf8e6b16fafe45a4de4b87df68652e2f1/.github/workflows/deploy.yml#L48) as you suggested, but unfortunately it had no effect. [logs](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4168369231/jobs/7215087489#step:6:260). I also would have expected this to influence linux and windows in the same way rather than only failing on windows. Can you think of anything else it might be?

**Comment by samuel-emrys** [comment]
I think I've somewhat resolved this issue with the help of @prince-chrismc on slack. The solution here was to realise that python virtual environments store binaries in the `bin` directory on linux, and the `Scripts` directory on windows, so the following fix resolved the issue:

```diff
    @property
    def _bindir(self):
        return "Scripts" if self.settings.os == "Windows" else "bin"

     def package_info(self):
+        self.cpp_info.bindirs = [self._bindir]
         self.conf_info.define("user.env.pythonenv:requirements", str(self.options.get_safe("requirements", "[]")))
         self.conf_info.define("user.env.pythonenv:dir", self.package_folder)
```
However, it looks like my debug statement is also inaccurate. Does the `conanbuild.bat` script not update the `PATH` variable on windows? My test package is obviously able to resolve `<package_dir>/Scripts` when searching for the `sphinx-build.exe` executable, but this doesn't seem to be managed via `%PATH%`? How is this managed on windows?

[Relevant log, indicating that `%PATH%` is not different between `conanbuild` and `conanrun` envs](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4201548100/jobs/7288657054#step:6:253). And the [related code](https://github.com/samuel-emrys/python-virtualenv/blob/0876dca0b2d93b6c9fc288fb977ca5c9e1230bee/test_package/conanfile.py#L25-L31):

```python
            path = "$PATH"
            if self.settings.os == "Windows":
                path = "%PATH%"
            self.output.info(f"Executing `echo {path}` with env=\"conanrun\"")
            self.run(f"echo {path}", env="conanrun")
            self.output.info(f"Executing `echo {path}` with env=\"conanbuild\"")
            self.run(f"echo {path}", env="conanbuild")
```

**Comment by memsharded** [comment]
Uhm, in Windows:

```
$  conanbuild.bat && echo %PATH%
```
Doesn't work as you would expect. %PATH% is replaced at command line parsing, then it executes, so initial %PATH% value is not affected by what is being defined in the ``conanbuild.bat`` script.
If you want to see the real effect put the ``echo %PATH%`` inside a ``myoutput.bat`` script and run instead:
```
$ conanbuild.bat && myoutput.bat
```
Or in conan
```
self.run("myoutput.bat")
```

**Comment by samuel-emrys** [comment]
Yep, that's it. Thanks for your help @memsharded - that's behaviour that I wasn't aware of - or more specifically, I wasn't aware that `self.run` was equivalent to `source .. && cmd`. Good to know.

**Comment by prince-chrismc** [comment]
Tip of the week idea here :) thank you!
