### ISSUE TITLE
[bug] using find_package to find conan libraries results in linking error

### ISSUE THREAD

**Issue by skrilax91** [conan-io/conan#13125]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: GCC 11.3
* Conan version: 1.58
* Python version: 3.10.6

#### Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

1. clone this project [here](https://github.com/skrilax91/Kappa-Engine/tree/4a4c4ed480b334308b7c24f2cfe5138a38fb74bd)
2. make `mkdir build && cd build && conan install ..`
3. make `cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug`
4. try to build the project using `make VERBOSE=1`
5. See the output that said "undefined reference to..."

### Logs

```
leo@leo-Prestige-15-A10SC:~/github/Kappa-Engine/build$ make VERBOSE=1 > ~/make_log.txt
```
[make_log.txt](https://github.com/conan-io/conan/files/10732370/make_log.txt)

**Comment by memsharded** [comment]
Hi @skrilax91 

Thanks for your question.

It would be good to see the ``conan install`` log, as well as the ``cmake`` configure step log.

In any case, I suspect it is a misalignment of the ``libcxx``. By default, and due to historic reasons and backwards compatibility, Conan is still using ``compiler.libcxx=libstdc++`` for the dependencies. There are a couple of warnings in the profile detect routine and in the docs that you should see (try to remove ``<home>/.conan/profiles/default`` and repeat). But your project would be using libstdc++11. 

The fix would be to define ``compiler.libcxx=libstdc++11`` in your default profile (this has already been done in 2.0) and do the ``install`` again

**Comment by skrilax91** [comment]
Hi, thanks for your answer, I've edited my issue and added my conan profile, as you can see I already have `compiler.libcxx=libstdc++11` in it.
You can see all inputs/outputs : 
```
leo@leo-Prestige-15-A10SC:~/github/Kappa-Engine$ mkdir build && cd build
leo@leo-Prestige-15-A10SC:~/github/Kappa-Engine/build$ conan install .. &> conan_install_logs.log
```
[conan_install_logs.log](https://github.com/conan-io/conan/files/10732897/conan_install_logs.log)
```
leo@leo-Prestige-15-A10SC:~/github/Kappa-Engine/build$ cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug &> cmake_log.log
```
[cmake_log.log](https://github.com/conan-io/conan/files/10732914/cmake_log.log)

**Comment by memsharded** [comment]
Uhm, that is interesting...
The ``conan_toolchain.cmake`` is a toolchain, not really intended for ``include()``, but it should be passed in the command line as ``-DCMAKE_TOOLCHAIN_FILE=.../conan_toolchain.cmake``. I think the toolchain files are applied slightly different than a pure ``include()``, it is worth trying.

**Comment by skrilax91** [comment]
I followed your suggestion and I removed the `include` statement from my CMakeLists.txt.
I tried to compile with `-DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake` but nothing changed
I make my changes on [this branch](https://github.com/skrilax91/Kappa-Engine/tree/feature/criterion)

**Comment by memsharded** [comment]
I have been testing this. 
Apparently there are some binary incompatibilities that make that the Release dependencies cannot be linked when building the consumer in Debug. It seems to work when installing the matching Debug dependencies with ``conan install .. -s build_type=Debug``

**Comment by skrilax91** [comment]
Yes! Thank you so much! It works if I require the debug build of dependencies
