### ISSUE TITLE
How to package/upload broken symlinks

### ISSUE THREAD

**Issue by gabeblack** [conan-io/conan#13129]
I am trying to create binary packages that are similar to how many linux distributions distribute their shared libraries (using a binary package and a "devel" package for the library (e.g., libpcap and  libpcap-devel)). Linux distributions will have the actual shared library binary in the library package and headers and a broken shared library symlink will be in the devel package (e.g., `libpcap.so.1.9.1` will be in the 'libpcap' rpm and the libpcap-devel rpm will contain the header files and a broken symlink of `libpcap.so` pointing to `libpcap.so.1.9.1`).

So the devel package on its own is "broken"; you need to install both the devel package and the library package for the broken symlink to be resolved (no longer broken).

Anyway, I'm trying to follow a similar construct with conan packages I'm creating . I found that if I set `skip_broken_symlinks_check=True` in my conan.conf I'm able to create these packages in my local cache and the broken symlink is "packaged up" correctly. I can then import the package in other projects where they are needed and if both the "library" and "devel" packages are imported, the symlink resolves.

However, if I UPLOAD the "devel" package to artifactory, the broken symlink is not included. Thus, these packages cannot be distributed; which kind of defeats the purpose of using conan as our package manager.

Is there any way to get the artifactory view to reflect what's in my local cache view in `~/.conan/data/<my_package>/.../package/*/*` ? In other words, is there any way to get the conan package in artifactory to have that broken symlink?

**Comment by memsharded** [comment]
Hi @gabeblack 

It seems that you might be using some of the legacy constructs, like ``self.copy()`` instead of ``copy()``. Even going further, it is not even necessary to use ``copy()`` you can also call explicitly whatever copy is necessary even with broken symlinks. There are also some utility methods that manipulate links to "prepare" for the package, check https://docs.conan.io/en/latest/reference/conanfile/tools/files/symlinks.html

The ``skip_broken_symlinks_check=True`` is legacy too, no need to use it.

Also, I am wondering about the reasons to do that. Conan main goal is to serve as a "development" C/C++ package manager, so all packages are "dev" packages containing headers, libs, etc. Then, for final deployment there are different mechanisms, like the new Conan 2.0 ``deployers``, that decouple the "runtime" extraction from the "development" packages.
It seems that the approach you are trying to do makes more sense for a "system" package manager, where it makes sense in most cases to install only "runtime" part. But it could add quite a complexity in the development flow, duplicating packages, complicating the builds, etc. For example, how will you manage the package creation? Because in practice it would easily mean building twice the same source code, and then packaging only some artifacts, dropping the others.

**Comment by gabeblack** [comment]
Thanks for the reply. Your intuition was spot on; I am using `self.copy()` (with `symlinks=True`) instead of `copy()`. My local conan cache in the package directory tree contains the broken symlinks. It is when the package is uploaded to artifactory (using the command `conan upload`, that the symlinks are no longer in the package (i.e. they are missing from the `conan_package.tgz` archive). Thus I get inconsistent behavior. If I use imports to retrieve the symlinks from my local cache, they are there. If I got/downloaded the same package from Artifactory and use imports, the symlinks are missing. I hope I'm communicating that and that's understood.

Anyway, are you saying that if I use `copy()` instead of `self.copy()` that conan upload will cause artifactory to reflect exactly what's in my local conan cache that results from the package step of `conan create`?

As far as the reasons to do what I'm doing.... uggh; I'm not happy about it. I work for a very large company that has ridiculous restrictions in place of where and how we retrieve our dependencies. We can't even bump to the next version of a dependency without having a legal review process that takes months. Our lab/dev environment can't access public repo's; no github, no conan.io, etc.. Long story short, I'm essentially mimicking/mirroring a linux distribution repo but providing the packages libraries and headers via conan (again the normal repo access being restricted). We will use it in addition for normal conan packages where the sources are included and you can cross-compile, etc., but some sort of solution is needed to make getting our distribution libraries/headers available in an efficient way. I was afraid in asking this question, I was going to get the "Why?!", but unfortunately due to factors way outside of my control, I can't change our dev environment or weird restrictions. 

Anyway, I hope you can help me with the symlink thing. If it isn't possible, no worries. I can "combine" the library and devel packages in to a single package so the symlinks aren't broken.

**Comment by SSE4** [comment]
I think it's related to #6252

**Comment by memsharded** [comment]
> Thus I get inconsistent behavior. If I use imports to retrieve the symlinks from my local cache, they are there. If I got/downloaded the same package from Artifactory and use imports, the symlinks are missing. I hope I'm communicating that and that's understood.

Understood, thanks for the clarification!

> Anyway, are you saying that if I use copy() instead of self.copy() that conan upload will cause artifactory to reflect exactly what's in my local conan cache that results from the package step of conan create?

Yes, definitely ``copy()`` does way less manipulations of symlinks than ``self.copy()`` does, so this could really help. There might still be some edge cases not covered, but this would be certainly the first thing that I would try. As you explained it is not even necessary to upload to Artifactory, it is good enough to check the ``conan_package.tgz`` that is generated at upload time. For being faster, you can do a ``--skip-upload`` to compress the tgz, but not upload it.

> As far as the reasons to do what I'm doing.... uggh; I'm not happy about it. 

Yeah, unfortunately these things are not that uncommon, thanks for explaining and good luck with it! Lets see if we can get at least the symlinks thing working.

**Comment by gabeblack** [comment]
I tried to use the new copy (assuming it is from `conan.tools.files`). I also tried 'prepping' the symlink with `absolute_to_relative_symlinks()` . The symlink exists in my local package cache (i.e. `~/.conan/data/<my-package>/.../package/<package-id>/lib/libpkg.so`) as it did before (using `self.copy()`). However, it still does not get put in to the generated `conan_package.tgz` file when running `conan upload`.

So no difference for me when I was using `self.copy()`. Unfortunately, in both cases I get the same behavior; the symlink exists in the local cache, but not in the upload artifact. Bummer.

**Comment by memsharded** [comment]
I am working in https://github.com/conan-io/conan/pull/13137 to validate that the full round trip is possible in 2.0, even with broken symlinks. I hit a couple of minor issues, but seems doable. Not sure what would be the effort for 1.X, probably the risk is much higher, but lets at least to make sure it works in 2.0

**Comment by memsharded** [comment]
This has been solved in Conan 2 for a while, (released 18 months ago), the risks of changing this kind of things in Conan 1 was too high, not possible.. Closing as solved, thanks for the feedback, please create new tickets against Conan 2 if necessary.
