### ISSUE TITLE
[feature] Update distro requirement to <=1.8.0

### ISSUE THREAD

**Issue by geochip** [conan-io/conan#13123]
### What is your suggestion?

Latest version of Distro is 1.8.0, it would be good to support this in requirements.txt as breaking changes seem to be few,
see https://github.com/python-distro/distro/blob/master/CHANGELOG.md

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @GeoCHiP 

Thanks for the suggestion. 
Sounds reasonable, do you want to do a PR yourself to test it and see if something breaks?

**Comment by geochip** [comment]
Hi @memsharded.

> Sounds reasonable, do you want to do a PR yourself to test it and see if something breaks?

I will try.
