### ISSUE TITLE
[question]  Packaging Existing FindPackage in Conan 2.0

### ISSUE THREAD

**Issue by someshSandbox** [conan-io/conan#13121]
Hi,
I am looking for an example of creating conan recipe for a package with pre-built binaries  (RTI DDS) which provides FindCMake scripts. Recreating all the variables and settings again in conan is error prone and tedious, so I want to reuse as much as I can .
https://github.com/rticommunity/rticonnextdds-cmake-utils/blob/main/cmake/Modules/FindRTIConnextDDS.cmake .

```

**Comment by memsharded** [comment]
Hi @someshSandbox 

We have some unittest in our code that tests this approach: https://github.com/conan-io/conan/blob/e0a8ee058bc8dc2d9811b8aeb6999f69aeb78d85/conans/test/functional/toolchains/cmake/test_cmaketoolchain_paths.py#L176.

It doesn't require anything special, CMakeToolchain is already prepared to inject the paths to the packages, so the xxx-config.cmake files insde them are found.

If you want to implement it yourself it would be something like this:

- Start from ``conan new cmake_lib -d name=pkg -d version=1.0``
- You can remove the ``package_info()`` method from ``conanfile.py``
- Complete the ``CMakeLists.txt`` so it creates the pkg-config.cmake and packages it
- You can drop the ``CMakeDeps`` from ``test_package/conanfile.py``
- ``conan create .`` should work

Please let us know if that works.

**Comment by memsharded** [comment]
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.
