### ISSUE TITLE
Disable x86 arch

### ISSUE THREAD

**Issue by fire** [conan-io/conan#1313]
In a conan file how do you disable the x86 arch? The project code only works with x86_64.

**Comment by memsharded** [comment]
There are a couple of ways:
- One is to create a ``configure()`` method in the recipe, and check there the settings. Then, raise an ``Exception`` if there is an unsupported setting, you can provide an error message
```python
def configure(self):
      if self.settings.arch != "x86_64":
            raise Exception("Only x86_64 architecture is supported")
```
- The other way is to constrain settings in the recipe declaration, something like: 
```python
class MyPkgConan(ConanFile):
    name = "MyPkg"
    version = "1.0"
    settings = {"os": None, "build_type": None, "compiler": None, "arch": ["x86_64"]}
```

**Comment by danimtb** [comment]
This worths an entry in the docs! I have opened an issue in the docs repo so I am closing this. Thanks!
