### ISSUE TITLE
[feature] Checker to warn/abort in case of 1.x features are used

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#13131]
### What is your suggestion?

We would like to go slowly towards Conan 2.x.
In the Conan 2 migration guide it is described how the recipes need to be changed to be 2.x compatible.
But following this consistently over all our Conan packages will be quite challenging and complicated.

It would be really nice if there would be a checker implemented that prints out warnings or even creates an error if 1.x recipe features are used when 2.x shall be the goal for the recipe.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

We had some CONAN_V2_MODE env-var exactly for this, but it was just too complicated to apply consistently, so it was not maintained anymore. We don't think it is possible to apply this now in the 1.X codebase.

Your best bet for a 1.X warning approach would be to use the linters that are being used in ConanCenter, check them in https://github.com/conan-io/conan-center-index/tree/master/.github/workflows. 

Some of these linters can be quite simple. 80% of the 2.0 readiness can be measured by checking just a few things: For example not using ``from conans`` but only ``from conan`` imports, would easily account for 60-70% of the migration effforts

In any case, our experience says that the best is just to setup a parallel CI job with 2.0 release that starts reporting on the PRs, not blocking it, but showing the results there, warning, etc. This can start with just a simple ``conan export`` job, not a full package creation, that already captures all the possible import errors, that as suggested above, will account for a vast majority of the necessary changes.

**Comment by MTomBosch** [comment]
Ok. Got it. Thanks for the quick reply.
