### ISSUE TITLE
Path reported by conan does not exist in the temp folder

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#13144]
### Environment details

* Operating System+version: Windows 10 Enterprise
* Compiler+version: Tasking 6.3r2p2
* Conan version: Conan version 2.0.0-beta9
* Python version: 3.11.1

### Steps to reproduce

The attached log show the results from running conan create on my cstart.py file. In the build method I executedd my makefile to dump the paths to files I am trying to compile. When the makefile executes I see the following paths reported in the temp folder for the files but when I look in the t folder cstar932ef4300baf0 does not exist. For ex, the makefile indicate the following file at this location

C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/metrics/objs/cstart/code/cstart_tc1.o C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/metrics/objs/cstart/code/cstart_tc2.o C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/metrics/objs/cstart/code/cstart_tc3.o C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/metrics/objs/cstart/code/cstart_tc4.o C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/metrics/objs/cstart/code/cstart_tc5.o

In cache C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0 does not exist.

The list of files above were generated in the build method and stored in the attached files. The makefile read these files to try and compile the file but couldn't because the path did not exist.
[cstart_inc.txt](https://github.com/conan-io/conan/files/10755938/cstart_inc.txt)
[cstart_src.txt](https://github.com/conan-io/conan/files/10755939/cstart_src.txt)
[console.log](https://github.com/conan-io/conan/files/10755944/console.log)

**Comment by memsharded** [comment]
Hi @Ed-CMI 

The build folder is moved when the package is finally created, and a package revision is computed, to the final package folder. The build folder is fully relocated to a different place.

Having absolute paths to folders inside the build folder shouldn't be done. Whatever happens at build time is ephemeral, and absolute paths are never valid information inside packages, because when you install those packages in another machine, those paths will be invalid (different ``C:/Users/xxxx`` folder, for a start). 

All the information defined by Conan to consumers, for example the ``cpp_info.includedirs``, ``cpp_info.libdirs`` is always relative to the package, because also it doesn't need to be absolute.

**Comment by Ed-CMI** [comment]
How is the recipe file going to be able to gather a list of file to compile? I setup the following code to gather the files

In generated method the following data was defined
           self._srcfiles = ["code/cstart.c", "code/cstart_tc1.c","code/cstart_tc2.c","code/cstart_tc3.c","code/cstart_tc4.c","code/cstart_tc5.c"]
            self._incdirs = ["code"]

Then in the build method the following code was used when creating the files that contained the list of files to be compiled. The code below basically takes the path listed above and uses os.path.join using the self.build_folder

SRCOPT = open(_opt + '/' + self.name + '_src.opt', "w")
		for _filename in self._srcfiles:
			_file = os.path.join(self.build_folder, str(self.name),str(_filename)) 
			_file = _file.replace('\\','/')
			_file = re.sub('.c$','.c   ', _file) # Make sure to leave a space at end of line
			SRCOPT.write(_file   )

**Comment by memsharded** [comment]
I am not sure what you mean. Write the file with the relative paths instead of the absolute ones? There is no need for paths to be absolute.

**Comment by Ed-CMI** [comment]
I dont understand your response. When a makefile is compiling files it can't use a relative path for the files. It needs the absolute path of the file in order to compile the file

**Comment by memsharded** [comment]
```
main:
	$(CXX) -o main src/main.cpp
```
No absolute paths there.

**Comment by Ed-CMI** [comment]
Not sure what happen but when I used the absolute paths in 2b6 my compiles were working. Here is a snapshot of the files being compiled. Did something change between 2b6 and 2b9

CC         C:/Users/uo855/.conan2/p/tmp/377eec794979256c/b/OctaneGold/physical_target/objs/cddudsprocessing/code/CDDUdsProcessing.o
ctc W504: ["C:\Users\uo855\.conan2\p\41877e81e83b4d9e\p\inc\Compiler_Cfg.h" 1446/9] macro "APP_SW" redefined
ctc W535: ["C:\Users\uo855\.conan2\p\400695ad5172e19f\p\Appl\GenData\Rte_Type.h" 8216/1] no type specifiers - assumed 'int'
ctc W500: ["C:/Users/uo855/.conan2/p/tmp/377eec794979256c/b/OctaneGold/cddudsprocessing/code/CDDUdsProcessing.c" 1904/76] expression without effect
ctc W500: ["C:/Users/uo855/.conan2/p/tmp/377eec794979256c/b/OctaneGold/cddudsprocessing/code/CDDUdsProcessing.c" 1905/78] expression without effect
ctc W500: ["C:/Users/uo855/.conan2/p/tmp/377eec794979256c/b/OctaneGold/cddudsprocessing/code/CDDUdsProcessing.c" 1915/77] expression without effect
ctc W500: ["C:/Users/uo855/.conan2/p/tmp/377eec794979256c/b/OctaneGold/cddudsprocessing/code/CDDUdsProcessing.c" 1916/79] expression without effect
ctc W500: ["C:/Users/uo855/.conan2/p/tmp/377eec794979256c/b/OctaneGold/cddudsprocessing/code/CDDUdsProcessing.c" 2010/76] expression without effect
ctc W500: ["C:/Users/uo855/.conan2/p/tmp/377eec794979256c/b/OctaneGold/cddudsprocessing/code/CDDUdsProcessing.c" 2011/58] expression without effect

**Comment by memsharded** [comment]
Some minor things changed in the cache in b9, but in theory it shouldn't affect (unless you are storing absolute paths somewhere, if you are that is fundamentally flawed, as it will break in other computers). 

Just in case, make sure to remove your Conan cache, a full removal of the ``.conan2`` folder would be the best to be sure.

**Comment by Ed-CMI** [comment]
Hi Diego

When setting up environment paths should they be pointing to the temp folder. For example, these paths were defined using absolute paths and they all will point to the temp folder. Do these need to change as well?

set "DIR_GENDIR=C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/generated"
set "DIR_OPTS=C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/generated/opt"
set "CONANBUUILDDIR=C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC"
set "DIR_COMPONENTLOGS=C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/generated/logs"
set "DIR_COMPONENTOBJS=C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/generated/objs"
set "DIR_LIBS=C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/generated/libs"
set "COMP_SOURCE_OPTS=C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/generated/opt/cstart_src.opt"
set "COMP_INCLUDE_OPTS=C:/Users/bq824/.conan2/p/t/cstar932ef4300baf0/b/SWC/generated/opt/cstart_inc.opt"

**Comment by memsharded** [comment]
Yes, those paths seem wrong, as they are pointing to the "build" ``/b/``  folder, not to the final package folder.

**Comment by Ed-CMI** [comment]
Closing the ticket and trying your approach
