### ISSUE TITLE
[question]Cross-build from 'Macos:armv8' to 'Android:armv8'

### ISSUE THREAD

**Issue by 97Simei** [conan-io/conan#13147]
### What is your question?

Hi! I have a question regarding Cross-build from 'Macos:armv8' to 'Android:armv8' on my M1 mac computer.

>Conan version 1.59.0

> profile_host
```
include(default)
target_host=aarch64-linux-android
android_ndk=/Users/lisimei/Library/Android/sdk/ndk/25.2.9519653/  # Adjust this path
api_level=33
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=11
os=Android
os.api_level=$api_level
[tool_requires]
[options]
[env]
PATH=[$android_ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host$api_level-clang
CXX=$target_host$api_level-clang++
LD=$target_host-ld
STRIP=$target_host-strip
CONAN_CMAKE_TOOLCHAIN_FILE=$android_ndk/build/cmake/android.toolchain.cmake
```

> profile_build
```
android_ndk=/Users/lisimei/Library/Android/sdk/ndk/25.2.9519653/
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=13
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
PATH=[$android_ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/]
[conf]
tools.android:ndk_path=[$android_ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/]
```

> Running Command
```
conan create . 0.6.1@ -pr:h ~/Documents/Thesis/helper/ccGP1/android_21_arm_clang -pr:b default
```

> Error
<img width="756" alt="Screenshot 2023-02-17 at 08 25 06" src="https://user-images.githubusercontent.com/86485345/219577671-7955b45d-8fe5-47d8-9fd6-a88a5a927114.png">

> Question:
1. I have tried several ways to set up the profile documents. but it seems like the "CMake" problems always exist. 
2. How to correctly set up a cross-compile profile for Cross-compile from 'Macos:armv8' to 'Android:armv8'?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @97Simei 

Thanks for your question.
It is very important to be able to help to have something that is reproducible. In this case, we are missing the whole input recipe conanfile.py and sources.
I'd strongly recommend starting with a modern template:
```
$ conan new pkg/0.1 -m=cmake_lib
```
This will create a simple CMake project using the modern tooling (CMakeToolchain, etc).
Then you should also be using a modern "host"profile, like:
```
 [settings]
  os=Android
  os.api_level=23
  arch=x86_64
  compiler=clang
  compiler.version=9
  compiler.libcxx=c++_shared
  build_type=Release
  [conf]
  tools.android:ndk_path={ndk_path}
```
The profile "build" does not need anything regarding the android_ndk, that goes only to the host one.

Then finally, apply both:
```bash
$ conan create . -pr:h=android -pr:b=default
```
Please try that and let us know

**Comment by 97Simei** [comment]
Hi @memsharded,

Thank you for your help, now I can cross-compile the package from my computer to the Android platform!

**Comment by memsharded** [comment]
> Thank you for your help, now I can cross-compile the package from my computer to the Android platform!

Excellent! Thanks for the feedback
