### ISSUE TITLE
[question] VCVars issue when using `tools.microsoft.msbuild:installation_path` in build context

### ISSUE THREAD

**Issue by Totollie** [conan-io/conan#13142]
### What is your question?

Hi, I am currently in the process of updating some local tooling to properly use build and host profiles in preparation for Conan 2.0. This is so far successfully using the new CMake generators.

In Conan 1.X, the profiles (used as both build and host context) try to use a VS Build Tools package as a `tool_requires` (alongside some other packages like cmake and ninja) meaning it appears in both contexts. The build tools recipe `package_info` sets `tools.microsoft.msbuild:installation_path` so that `VCVars` can work correctly. However it seems the correct way is that this should only be in the build context, and in Conan 2.0 there are graph loops when it is present in both which stops us testing further.

The problem arises as `tools.microsoft.msbuild:installation_path` does not seem to get set in the build context, and so the package is not found when configuring `VCVars`. What would be the best approach to handle this so that a build tools package can be successfully used in only one context?

Thank you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Totollie 

Thanks for your question.
It would be great to understand a bit better the dependency graph. You have a package, lets call it "msbuild/1.0" that contains the VS compiler and is intended to be used as a "tool_requires"? Does it contain a definition of ``conf_info`` for that conf in its ``package_info()`` method? Is this "tool-requires" also applied to other "tool_requires" in the build context? Maybe a graph in the form:
```
myapp -> mylib/1.0
myapp -(tool-require)-> msbuild/1.0
...
```
could clarify a bit. Thanks!

**Comment by Totollie** [comment]
Sure, so to clarify the graph a bit, we are coming from a one profile approach:

 - `msbuild/1.0` contains the VS Compiler and is intended as a `tool-requires` which we would set in the profile to apply it to every package using that profile.
     - `msbuild/1.0` does contain a definition of `conf_info` for `tools.microsoft.msbuild:installation_path` in its `package_info()`, which points to its own package folder.

- An example profile (lets call `windows_compiler`) would look like:
```
[settings]
....
[tool_requires]
msbuild/1.0
cmake/3.25
winsdk/1.0 # could be used as a requires as well as it contains some tools but also libs to link against.
```
  - None of the other tool-requires are expected to tool-require `msbuild/1.0`, so they are flat. But each one could tool-require a `p7zip` to extract their own binaries from a `.7z` into a conan package. Due to this, each tool-requires is exported and packaged using a `default` profile with no tool-requires specified and most other settings removed.
- The graph for us when using the same profile for build and host (shortened) would currently end up looking like:

```
myapp -> mylib1
myapp -(tool-require)-> cmake/3.25
myapp -(tool-require)-> msbuild/1.0
myapp -(tool-require)-> winsdk/1.0
msbuild/1.0 -(tool-require)-> p7zip/19.00
winsdk/1.0 -(tool-require)-> p7zip/19.00
```

- `mylib1` and `myapp` both have `CMakeToolchain` and subsequently `VCVars` generators to configure the build, where I expected `msbuild/1.0` `conf_info` to be used.

There might be two queries from this:

1) Just having one profile as above which lists settings and tool-requires, and using it for both build and host profiles, seems to work in Conan 1.X but not Conan 2.0 beta (where it generates a graph loop error).
2) Figuring out how `conf_info` can be used correctly with `VCVars`. Should the build profile be requiring `msbuild/1.0` instead of tool-requires? Or should the tool-requires be *only* in the host profile? I suspect the latter is the case but if I were cross-compiling linux to windows for example, shouldn't it look to the build profile for tool packages like compilers so that it retrieves binaries it can use?

Please let me know if I can provide more details to help with understanding the issue, or to clarify anything.

**Comment by Totollie** [comment]
Example of the output I'm currently seeing when I split the profiles and add tool-requires to the build profile only: https://gist.github.com/Totollie/7b36448d2693b46cebb11bcf8c645e18

**Comment by memsharded** [comment]
> Just having one profile as above which lists settings and tool-requires, and using it for both build and host profiles, seems to work in Conan 1.X but not Conan 2.0 beta (where it generates a graph loop error).

This could be relevant. Are you using the same profile both for "build" and "host" contexts? Only the "host" profile should contain the ``tool_requires`` to ``msbuild/1.0``, but that shouldn't happen in the "build" profile.

> Figuring out how conf_info can be used correctly with VCVars. Should the build profile be requiring msbuild/1.0 instead of tool-requires? Or should the tool-requires be only in the host profile? I suspect the latter is the case but if I were cross-compiling linux to windows for example, shouldn't it look to the build profile for tool packages like compilers so that it retrieves binaries it can use?

Yes, exactly, it should only be in the "host" profile. 
I don't think the second case holds, unless you have a compilation of msbuild that can run in Linux, I am not sure that exists (maybe via Wine?). But in any case, it is still a "tool_requires" for the host context, not for the "build" context, as it cannot build binaries for Linux.

**Comment by Totollie** [comment]
> This could be relevant. Are you using the same profile both for "build" and "host" contexts? Only the "host" profile should contain the `tool_requires` to `msbuild/1.0`, but that shouldn't happen in the "build" profile.

Originally this was the same profile for build and host, but I am now trying to split them. It seems like Conan 2.0 is a lot stricter on doing this (a good thing as it ensures proper usage!).

> Yes, exactly, it should only be in the "host" profile. I don't think the second case holds, unless you have a compilation of msbuild that can run in Linux, I am not sure that exists (maybe via Wine?). But in any case, it is still a "tool_requires" for the host context, not for the "build" context, as it cannot build binaries for Linux.

It was a poor example from me, but this clears things up. Can I then correctly say that the build profile is then used to apply settings which the tool-requires in the host profile would use. I.e. I want my msbuild/1.0 to use x64 tools to build x86 binaries, so my build profile would set `arch=x86_64`, my host profile would set `arch=x86` and `tool-requires`?

I will push ahead with using this tool requires in the host profile. Thank you for clearing up my confusion and clarifying the profile usage, it is much appreciated! I am happy for this issue to be resolved!

**Comment by memsharded** [comment]
> It was a poor example from me, but this clears things up. Can I then correctly say that the build profile is then used to apply settings which the tool-requires in the host profile would use. I.e. I want my msbuild/1.0 to use x64 tools to build x86 binaries, so my build profile would set arch=x86_64, my host profile would set arch=x86 and tool-requires?

Yes, that is the idea:
- A ``tool_requires`` in the "host" profiles is the tools that you want to use to build your normal "host" applications and libraries. For example, ``cmake`` can be a ``tool_requires`` in your "host" profile to build your "app/1.0" application
- A ``tool_requires`` in the "build" profile is the tools that you want to use to build your "build" applications. In this case, if you need to apply some other build tool to build ``cmake`` package from source itself, then you want to put it in the "build" profile.

**Comment by memsharded** [comment]
Closing this, but feel free to file new issues if you have any further question. Thanks!
