### ISSUE TITLE
what would be the best approach for `package_type`  when it changes depending on version

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#13145]
what would be the best approach for `package_type` in such recipe? Split it in 2 parts (old version with a lib, and new versions header-only)?

_Originally posted by @SpaceIm in https://github.com/conan-io/conan-center-index/issues/15963#issuecomment-1427823087_

**Comment by memsharded** [comment]
Split the recipe into 2 folders, depending on the version?
Sounds exactly the case of divergence that the conan-center-index folder structure was designed for.
It is likely that the package_type is  not the only thing that will need changes: conditional ``package_id()``, removed ``options``, etc.

It might be possible to do conditional package_types in ``configure()`` method, but it really doesn't sound like a solid approach

**Comment by AbrilRBS** [comment]
Closing as solved
