### ISSUE TITLE
[question] Using two conanbuildinfo.cmake in the same CMakeLists.txt file ?

### ISSUE THREAD

**Issue by nitrogene** [conan-io/conan#13152]
### What is your question?

Hello,

I am trying to add GTest to a project using Makefile/Cmake/Conan. I have two conanfiles, one for the main project, another for a google test project. The installation of the conan packages is done in the Makefile. In the main CMakeLists.txt file, I am trying to find all required conan packages with:

```cmake
include($(CONAN_DIR/conanbuildinfo.cmake)

if($ENV{GTEST})
     include($(GTEST_CONAN_DIR/conanbuildinfo.cmake)
endif()

conan_basic_setup(TARGETS)
```
The issue is that it does not find CONAN_PKG:: related to the main project (first include), but it finds those related to the GTest project. If I switch the include order, it will find those related to GTest and not to the main project.

Is there a way to handle two conanfile.txt files in the same CMakeLists.txt file ?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nitrogene 

I am afraid you are still using the legacy integrations, while the new ones are very recommended. 
Using ``CMakeToolchain`` and ``CMakeDeps`` and not ``cmake`` allows for a transparent integration in which you don't even need the ``include(conanbuildinfo.txt)``.

In any case, for one project you should have 1 conanfile for its dependencies. When you install it, it will be generating different CMake find ``xxx-config.cmake`` scripts, which you can use standard CMake to do ``find_package()`` and then use the created target natively with CMake, so you can link the gtest target to the tests, but not to the main application, without needing 2 conanfiles.

**Comment by nitrogene** [comment]
Hello @memsharded 

I am afraid that I have to stick with legacy integrations for now, i am not in position to change that sadly. Anyway I already found a solution, by  moving the include related to gtest to the CMakeLists.txt file related to gtests.

I'll take a look to CMakeToolchain for my personal culture.
