### ISSUE TITLE
[feature] allow user that `[tool_requires]` from conanfiles are preferred over `[tool_requires]` from profiles

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#13150]
### Environment details

* Operating System+version: Ubuntu 20
* Compiler+version: gcc 10.2
* Conan version: 1.60
* Python version: 3.8.10

### Steps to reproduce

`self.build_requires()` from a recipe should be preferred over `build_requires` coming from profiles (Conan 1.X)

Use case:

- we cross compile using a `sysroot` (which comes with some tools like cmake 3.15 or protobuf 3.15). 
- a user wants to override a tool using `self.build_requires("cmake/3.25")` or `self.build_requires("protobuf/3.19")`
- Expected: `PATH` should contain `cmake/3.25`'s and `protobuf/3.19`'s `PATH` before `sysroot`'s `PATH`
- Actual: cmake and protobuf are taken from `sysroot`

For `protobuf` the issue is even worse than for cmake:
When we specify `self.build_requires("protobuf/3.19")` and self.requires("protobuf-lib/3.19") the 3.19 library is found correctly since `CMakeToolchain` generator customizes `CMAKE_PREFIX_PATH` (as expected). But in PATH variable the sysroot path comes first so that `protobuf 3.15` compiler is taken --> MISMATCH

I will open some PR where I reproduce this.

**Comment by memsharded** [comment]
Hi @thorsten-klein 

Thanks for your contribution.
I am afraid this is not a bug, but expected behavior.
Conan design says that the most downstream consumer always has priority. In this case, the profile should always have priority over recipes. 
I can have a dependency graph, and if I write a profile saying I want some ``tool_requires``, and I pass that profile in the command line, that must be respected. The profile tool_requires should always have higher priority than the recipe definitions, in the same way the downstream consumers ``requires`` versions have higher priority over their dependencies versions.

As you can see, your change in your PR is breaking some tests in the test suite that capture this priority.

The use case of sysroots might need some especial consideration, but just swapping the order and  priority of normal ``tool_requires`` will be breaking behavior, this cannot be done.

**Comment by thorsten-klein** [comment]
For me the understanding with profiles is different. Profiles are the "base" where the actual user is based on top. A user can override this "base" analogue to the `self.requires()` behavior:
`libA -> libB -> libC`
`libB` has `self.requires(libC/1.0.0)`, but `libA` can override this requirement by `self.requires(libC/1.0.1)`. 
In this case also not the most downstream consumer wins (which would be libB), but the higher one (libA). Or am I wrong?

If this behavior was expected, I would suggest to introduce some attribute to change it on purpose.
I have two proposals which both do not break any existing behavior

Proposal 1:
`conanfile.py` has an attribute `self.override_profiles` which is set to `False` by default and can be set by the user to `True`.
This will be enough for simple use cases where a user wants to override profiles. But it may not be enough if a user wants to prefer one `build_requires` from a profile over a `build_requires` from another profile. This attribute is set in the user's `conanfile.py`.

Proposal 2:
An attribute `self.priority` which is `0` by default and can be set to any `int`
The `build_requires` will be sorted by this priority. The lower the integer, the higher the priority (the earlier in the list).
This attribute has to be set in the consumed `conanfile.py`, so the `libC` package would have to set `priority`. This is maybe not the best.

I prefer Proposal 1.

**Comment by memsharded** [comment]
I am afraid I don't understand, the most downstream consumer is libA, not libB, why do you say it is libB?

Let say this is the rationale:
- You are writing your own libA recipe, and you make it depend on libB/1.0
- That libB/1.0 depends in turn on libC/1.0.
- Both libB and libC are out of your control (other teams, ConanCenter, etc)
- Now you realize that there is a new ``libC/1.1`` that solves some important security vulnerability
- You cannot wait until libB developers release an update to use it
- Then, you, libA, which is the most downtream consumer of the graph, must be able to define: "I want libC/1.1" in my dependencies, and it can override it

Exactly the same story happens with profiles. The profile is the most downstream consumer. The profile is no other thing than a text representation of a command line argument. So if your command line says:
```
conan install .... -o *:shared=True
```
Then that is a user command, and that should always have higher priority. It doesn't matter that some recipes might be defining or defaulting to ``shared=False``, if I want all of them to be shared, I should be able to do so. Recipes are free to raise an ``ConanInvalidConfiguration()`` in their ``validate()`` if for some reason they cannot be built as shared library (why would they have the ``shared`` option if they can't but that is another issue).

So this is the rationale, the profile is what the user is commanding over the dependency graph. It should always have higher priority over the graph and recipes, in the same way ``libA`` has higher priority over ``libA``

**Comment by memsharded** [comment]
By the way, there is  a way, to specify in the profile that you don't want a certain override to apply to some dependencies:

```
[tool_requires]
!mypkg*:protobuf/3.15
```
That will override the protobuf version for all packages in the graph, except for ``mypkg``, isn't this what you are trying to achieve?

**Comment by thorsten-klein** [comment]
I think we just had a different naming but meant the same.
For me the profiles are the opposite of the most downstream consumer (most upstream consumer).

When I think at our project: 
`libC` can decide that they must always be build as static library for some setting combination (e.g. for a specific `arch` they set option `shared=False`). This information is maintained at `conanfile.py` of `libC` only. The consumers of `libC` should not have to concern about this. So even the profiles should be generic and not have some special pattern inside for `libC`. So `libC` as maintainer of their package defines when they need some specific option - no matter if some profile is trying to set `*:shared=True`. 
How would this be possible today that the `shared` option of `libC` cannot be overridden by a profile?





> By the way, there is a way, to specify in the profile that you don't want a certain override to apply to some dependencies:
> 
> ```
> [tool_requires]
> !mypkg*:protobuf/3.15
> ```
> 
> That will override the protobuf version for all packages in the graph, except for `mypkg`, isn't this what you are trying to achieve?

This is not possible for us since we need the other stuff from the sysroot. So sysroot really has to be resolved, but in different order (the other package should be preferred over sysroot).

**Comment by thorsten-klein** [comment]
This issue is obsolete.
