### ISSUE TITLE
[question] working of conan  info command with --package-filter and --json

### ISSUE THREAD

**Issue by UtkarshVerma37051** [conan-io/conan#13158]
### What is your question?

Hi,

I am trying to run conan info command to get some details about a package. (For demonstration let's consider libcurl/7.86.0 package)

when I am running conan info libcurl/7.86.0 -r conancenter I am getting the expected output:

![image](https://user-images.githubusercontent.com/74915320/219784008-b3aae8fc-e134-4916-88fc-47aeb77efbb5.png)

now when I tried to put the output in json format, I got this (which is also expected):

![image](https://user-images.githubusercontent.com/74915320/219785138-f0a1b196-0b69-49ab-b30e-85c10bd314f2.png)

but when I am trying to filter-out the packages with --package filter option and then try to put it into json, it is not filtering the data according to the package filter, rather the command is giving the whole data without the filter applied as shown below.
![image](https://user-images.githubusercontent.com/74915320/219786616-96507e3f-0b8f-4dc5-8b72-7e4794473d2a.png)

So I had a doubt that shouldn't the expected behavior be to filter out the packages info based on the packages-filter option and then dump into json? If yes, then is this a bug or am I missing something?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Yes, this was expected in 1.X, because why filtering a json file if it is not intended to be read by humans, but by machines, and having extra fields doesn't matter.

In any case, this has been changed in 2.0 already, and filters will apply to json output as well.

**Comment by UtkarshVerma37051** [comment]
Ah, I see.

I had one more doubt regarding the info command itself.

Running conan info command on a package that is not in the cache, downloads the conan recipes, manifests and the conan-export tar ball from the respective artifactory which can take time for larger packages , is there a way to avoid downloading but still get the information about the package?

**Comment by memsharded** [comment]
> Running conan info command on a package that is not in the cache, downloads the conan recipes, manifests and the conan-export tar ball from the respective artifactory which can take time for larger packages , is there a way to avoid downloading but still get the information about the package?

No, the ``conan info`` computes the dependency graph. This involves evaluation of the python scripts, no way that can be done server-side. 

But in any case, this shouldn't be an issue, because ``conan info`` only brings the ``conanfile.py`` recipes, which are very small and fast to download. The binary packages which are the heavy things are not downloaded with ``conan info``.

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
