### ISSUE TITLE
[bug] required_conan_version check doesn't work for 2.0.0 beta 10

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#13163]
### Environment details

* Operating System+version: Probably all of them, observed on macOS 12.6, Windows 10 22H2
* Compiler+version: apple-clang 13, msvc 193
* Conan version: 2.0.0-beta10
* Python version: 3.11.1

### Steps to reproduce

1. Upgrade to the latest conan beta: `pip install conan --pre --upgrade`
2. Set `required_conan_version` to a version 9 or lower: `required_conan_version = ">=2.0.0-beta7"` in conanfile.py
3. Run conan install

I get the error:
```
Current Conan version (2.0.0-beta10) does not satisfy the defined one (>=2.0.0-beta7).
```

I think it's just the classic 10 is less than 7 when evaluating the string rather than considering the numerical value. Workaround is just to set the minimum to `2.0.0-beta10`. I could see this not even being a problem in the final release, so I won't mind at all if you just close it, I just wanted to let you know if you weren't aware.

**Comment by AbrilRBS** [comment]
Hi @ssrobins, thanks for taking the time to submit the bug report!

You are totally right in that this does not work for the current versions of Conan released as `2.0.0-betaX`. Conan uses semver for version range comparisons everywhere, including the `required_conan_version`.

The issue arises from not following such schema ourselves for the beta releases. As seen [in semver#section-9](https://semver.org/#spec-item-9), PRE-RELEASE versions should be dot-separated between components, else it will fallback to lexicographical sorting (Section 10) as you correctly identified was happening. Conan should have released its alphas & betas as `2.0.0-beta.10` for this comparison to work.

We will make sure to address this for future releases, just not for the 2.0 betas, as Conan v2 is almost ready to be released :)

Again, thanks for the bugreport!
