### ISSUE TITLE
[question] deploy() method replacement in V2

### ISSUE THREAD

**Issue by upsilona** [conan-io/conan#13165]
### What is your question?

Hello everyone,

I'm in the process of migrating to V2,

In V1 I was using the deploy() method to produce several archive files (tar.gz) containing some binaries and their runtime dependencies, by copying files from the `package_folder`,

I've noticed there are two replacement in V2 : generate method and cutsom deployer, in my case a custom deployer sounds suitable, unfortunatly I've not been able to access the `package_folder` from the `graph` parameter of the deployer,

I was thinking in creating the archives in the `package` method, but this is definitely not as elegant as using the deploy() method,

My understanding of deployer is partial, is it possible to copy files from the `package_folder`, if not is there any replacement for this ?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @upsilona 

We are in the process now of finalizing docs for 2.0, please check https://docs.conan.io/en/2.0/reference/extensions/deployers.html if you haven't yet.

The deployer is getting a graph object, and for every node in the graph, you can access its ``package_folder`` via ``node.conanfile.package_folder``, or you can iterate the dependencies of the ``graph.root.conanfile``.

Maybe the code of the built-in ``full_deploy`` can give some hints:
```python
def full_deploy(graph, output_folder):
    """
    Deploys to output_folder + host/dep/0.1/Release/x86_64 subfolder
    """
    # TODO: This deployer needs to be put somewhere else
    # TODO: Document that this will NOT work with editables
    import os
    import shutil

    conanfile = graph.root.conanfile
    conanfile.output.info(f"Conan built-in full deployer to {output_folder}")
    for dep in conanfile.dependencies.values():
        if dep.package_folder is None:
            continue
        folder_name = os.path.join(dep.context, dep.ref.name, str(dep.ref.version))
        build_type = dep.info.settings.get_safe("build_type")
        arch = dep.info.settings.get_safe("arch")
        if build_type:
            folder_name = os.path.join(folder_name, build_type)
        if arch:
            folder_name = os.path.join(folder_name, arch)
        new_folder = os.path.join(output_folder, folder_name)
        rmdir(new_folder)
        shutil.copytree(dep.package_folder, new_folder, symlinks=True)
        dep.set_deploy_folder(new_folder)
```

**Comment by upsilona** [comment]
Hello @memsharded 

Using your answer I've been able to reproduce what I was doing in V1 with the deploy() method,

Thanks a lot for your kind answer !!

**Comment by memsharded** [comment]
Very happy that you managed to make it work, thanks very much to you for your feedback!
