### ISSUE TITLE
cmake_build_modules not being called

### ISSUE THREAD

**Issue by cocoza4** [conan-io/conan#13164]
### What is your question?

Hi there,

I'm trying to set property `cmake_build_modules`, with a module that define some custom targets.

Please find my setup below
`conanfile.py`
```
import os
import shutil
from pathlib import Path
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout
from conan.tools.files import patch, get
from conans import tools

class AbseilConan(ConanFile):
    name = "abseil"

    version = "20220623.1"

    settings = "os", "compiler", "build_type", "arch"

    generators = "CMakeDeps"

    exports_sources = "abseil-targets.cmake"

    def source(self):
        get(self, f"https://github.com/abseil/abseil-cpp/archive/{self.version}.tar.gz", strip_root=True)
    
    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        flags = []
        if self.is_msvc:
            flags.append('-DCMAKE_CXX_FLAGS="/std:c++14 /EHsc /MP"')
        cmake = CMake(self)
        cmake.configure(cli_args=flags)
        cmake.build()
        
    def package(self):
        cmake = CMake(self)
        cmake.install()

    @property
    def is_msvc(self):
      return self.settings.os == "Windows" and self.settings.compiler == "clang"
    
    def package_info(self):
        self.cpp_info.libs = ["absl"]
        self.cpp_info.set_property("cmake_file_name", "absl")
        self.cpp_info.names["cmake_find_package"] = "absl"
        self.cpp_info.filenames["cmake_find_package"] = "absl"
        self.cpp_info.filenames["cmake_find_package_multi"] = "absl"
        self.cpp_info.names["cmake_find_package"] = "absl"
        self.cpp_info.names["cmake_find_package_multi"] = "absl"

        targets_module = os.path.join(self.package_folder, "lib", "cmake", "abseil-targets.cmake")
        shutil.copyfile(os.path.join(self.package_folder, "../../export_source", "abseil-targets.cmake"), 
                        targets_module)
        
        tools.replace_in_file(targets_module, "${ABSEIL_INCLUDE_DIR}", os.path.join(self.package_folder, "include"))
        tools.replace_in_file(targets_module, "${ABSEIL_INSTALL_DIR}", self.package_folder)
        
        if self.is_msvc:
            tools.replace_in_file(targets_module, "${LIB_PREFIX}", "")
            tools.replace_in_file(targets_module, "${EXTENSION}", "lib")
        else:
            tools.replace_in_file(targets_module, "${LIB_PREFIX}", "lib")
            tools.replace_in_file(targets_module, "${EXTENSION}", "a")
        
        # Conan trick to set targets in CMake
        modules = [os.path.join("lib", "cmake", "abseil-targets.cmake")]
        print("target module", modules)
        self.cpp_info.set_property("cmake_build_modules", modules)     
```

`abseil-targets.cmake` (suffixed with `.txt` to upload)
[abseil-targets.cmake.txt](https://github.com/conan-io/conan/files/10776627/abseil-targets.cmake.txt)

`test_package`
[test_package.zip](https://github.com/conan-io/conan/files/10776633/test_package.zip)

The structure is as follows
```
abseil-cpp
    | -- /test_package
    | -- conanfile.py
    | -- abseil-targets.cmake    
```

I wonder why `abseil-targets.cmake` is not being called. It is set to be called in 
```
# Conan trick to set targets in CMake
        modules = [os.path.join("lib", "cmake", "abseil-targets.cmake")]
        print("target module", modules)
        self.cpp_info.set_property("cmake_build_modules", modules)     
```
Thanks

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cocoza4 

Some quick hint:
- ``flags.append('-DCMAKE_CXX_FLAGS="/std:c++14 /EHsc /MP"')`` is hardcoding the cppstd value. You might want to parameterize it based on ``self.settings.compiler.cppstd``.
- It seems you are changing the package contains in ``package_info()`` with:
```python
shutil.copyfile(os.path.join(self.package_folder, "../../export_source", "abseil-targets.cmake"), 
                        targets_module)
```
``package_info()`` should never modify contents of the package (package contains checksums, they might be considered corrupt if something changes inside the package). Maybe you want to do something different in the ``package()`` method.

Furthermore, it is undefined behavior to access the ``export_source`` folder from there, that folder might not exist at all when using the package. That location is an internal implementation detail, of the Conan cache internals, and subject to change at any time (in fact Conan 2.0 changes that a lot).
- Likewise, it is not possible to do ``tools.replace_in_file(targets_module`` in ``package_info()``, because that is changing the contents of the package, and packages must be immutable. That is also undefined behavior.

I think these things could be very related, I'd try to fix those as a first step.

**Comment by cocoza4** [comment]
@memsharded Thanks for your response. This is my new `package` and `package_info` methods.
```
def package(self):
        cmake = CMake(self)
        cmake.install()

        targets_module = os.path.join(self.package_folder, "lib", "cmake", "abseil-targets.cmake")
        shutil.copyfile(os.path.join(self.source_folder, "abseil-targets.cmake"), targets_module)
        
        tools.replace_in_file(targets_module, "${ABSEIL_INCLUDE_DIR}", os.path.join(self.package_folder, "include"))
        tools.replace_in_file(targets_module, "${ABSEIL_INSTALL_DIR}", self.package_folder)
        
        if self.is_msvc:
            tools.replace_in_file(targets_module, "${LIB_PREFIX}", "")
            tools.replace_in_file(targets_module, "${EXTENSION}", "lib")
        else:
            tools.replace_in_file(targets_module, "${LIB_PREFIX}", "lib")
            tools.replace_in_file(targets_module, "${EXTENSION}", "a")
    
    def package_info(self):
        self.cpp_info.names["cmake_find_package"] = "absl"
        self.cpp_info.set_property("cmake_file_name", "absl")
        self.cpp_info.filenames["cmake_find_package"] = "absl"
        self.cpp_info.filenames["cmake_find_package_multi"] = "absl"
        self.cpp_info.names["cmake_find_package"] = "absl"
        self.cpp_info.names["cmake_find_package_multi"] = "absl"
        
        # Conan trick to set targets in CMake
        modules = [os.path.join("lib", "cmake", "abseil-targets.cmake")]
        self.cpp_info.set_property("cmake_build_modules", modules)
```
Now it worked as expected. Thank you very much.

**Comment by cocoza4** [comment]
@memsharded one quick question, regarding the example posted above. For
```
flags.append('-DCMAKE_CXX_FLAGS="/std:c++14 /EHsc /MP"')
```
I have already moved `/std:c++14` to self.settings.compiler.cppstd=14 but for `/EHsc /MP` how can we set these flags globally in a profile. I tried
```
[conf]
tools.build:cxxflags=["/EHsc", "/MP"]
```
but it didn't work.

**Comment by memsharded** [comment]
Are you sure ```[conf]tools.build:cxxflags=["/EHsc", "/MP"]`` it didn't work?

Things to check:
- Go to the build folders in the cache, and inspect the ``conan_toolchain.cmake`` file there. It should contain those flags.
- The ``/MP`` might not be necessary. Conan has other mechanisms to define parallelism, check other confs, like ``tools.build:jobs``, and other msbuild/cmake configs in ``conan config list``.
- If they are in ``conan_toolchain.cmake``, can you check in the output messages if this file is being actually passed while building?
- Check that no other flags is interacting with it, so they could be overriden

**Comment by cocoza4** [comment]
@memsharded  yep, they were set in `conan_toolchain.cmake`
```
# Extra c, cxx, linkflags and defines
string(APPEND CONAN_CXX_FLAGS " /EHsc /MP")


if(DEFINED CONAN_CXX_FLAGS)
  string(APPEND CMAKE_CXX_FLAGS_INIT " ${CONAN_CXX_FLAGS}")
endif()
```
but i need to set it to `CMAKE_CXX_FLAGS` variable, essentially in 
```
cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan/data/abseil/20220623.1/_/_/build/1802d478666194d20415168b92739c8d4ad3d246/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/abseil/20220623.1/_/_/package/1802d478666194d20415168b92739c8d4ad3d246" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan/data/abseil/20220623.1/_/_/build/1802d478666194d20415168b92739c8d4ad3d246/." -DCMAKE_CXX_FLAGS="/EHsc /MP"
```

**Comment by memsharded** [comment]
That is weird, if they are in the toolchain file, and the toolchain file is being passed, they should definitely be applied! I cannot think of a reason why those variables are not being used in your build (without being passed in command line as ``-DCMAKE_CXX_FLAGS``), unless there are other conflicting instructions in your ``CMakeLists.txt``, I have no idea. Maybe it is worth trying to replace the ``CMakeLists.txt`` with a toy one, that just prints the flags, or try to build a simple hello world app with those flags, and be verbose, to see if they apply to the build or not.
