### ISSUE TITLE
[question] Private requirements with static libraries

### ISSUE THREAD

**Issue by Jamaslab** [conan-io/conan#13175]
### What is your question?

Hello,
I'm currently facing the following issue. I have the following configuration of packages:

```
big third party dependency          big third party dependency (with different options)
                |                                                           |
              lib a                                                         |           
                |                                                           |
              lib b                                                         |
                |________________________ final library ____________________|
```
What would be the correct way to configure the various conanfiles (of lib a, lib b and final library)? Currently I get the following error:
`Incompatible requirements obtained in different evaluations of 'requirements'`

I had a look to use the `private` flag in lib a, but unsuccessfully, as I get undefined reference of all methods from the third party dependency when compiling `lib b`. All the libraries are compiled as static, but I don't have them a strong requirement to have them as static, I could easily add them as dynamic

**Conan version:** 1.56.0

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Jamaslab 

The configuration you are presenting above, all as static libraries is impossible to do. Not with Conan, it is not a valid C/C++ libraries setup.

You would need the "big thirdparty"; let's call it ``btp`` package, to be a static library, then ``liba`` to be a shared library, and guarantee that ``liba`` is using ``btp`` as an internal implementation detail:
- Not header of ``liba`` includes any header of ``btp``
- No object or memory allocated by ``btp`` leaks the interface of ``liba`` to the downstream consumers.

This is irrespective of Conan, just at the source and build system level.

Now with Conan, it should be possible in Conan 1.X with the ``private`` flag, but of course only when all the above holds, if not you will get errors.
In any case, the ``private`` flag can be tricky in Conan 1.X, Conan 2.0 model will improve a lot over this. Conan 2.0 will be released very soon.

**Comment by Jamaslab** [comment]
Thank you very much for the support @memsharded.
I followed your suggestion by making `liba` shared, containing `btp` inside `liba` and putting the requires as `private`. I also configured the cmakelists to link `btp` as `private` when creating `liba` as shared.

All seems to be working now. Thanks!

**Comment by memsharded** [comment]
Great, thanks for the update!
