### ISSUE TITLE
Components break editable mode

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#13177]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: Visual Studio 2019
* Conan version: 1.59
* Python version: 3.10.5

### Steps to reproduce

1. Clone https://github.com/stevn/conan_editable_test
2. Follow steps in README.md

### Logs

```
-- Conan: Component target declared 'prj_a_comp::ProjectAComp'
-- Conan: Target declared 'prj_a_comp::prj_a_comp'
CMake Error at build/generators/cmakedeps_macros.cmake:39 (message):
  Library 'prj_a_comp' not found in package.  If 'prj_a_comp' is a system
  library, declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  build/generators/prj_a_comp-Target-debug.cmake:24 (conan_package_library_targets)
  build/generators/prj_a_compTargets.cmake:26 (include)
  build/generators/prj_a_comp-config.cmake:16 (include)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "conan_editable_test/project_b_comp/build/CMakeFiles/CMakeOutput.log".
ERROR: conanfile.py (prj_b_comp/1.0.0): Error in build() method, line 37
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="conan_editable_test/project_b_comp/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "conan_editable_test\project_b_comp\."
```

**Comment by memsharded** [comment]
Hi @stevn 

I think this is not a bug, but expected behavior.
If a package with components has to be put in ``editable`` mode, it has to define the components in ``layout()`` in the same way it is done for the ``folders`` and ``cpp_info``, for ``self.cpp.source``, ``self.cpp.build`` too. Please check https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-cpp

**Comment by stevn** [comment]
@memsharded Great, thanks for the tip! I think I've found a solution. Can you please check if this makes sense:

https://github.com/stevn/conan_editable_test/commit/98927f31342035103b71b073dffc1c96177fd3e8

If so, I think this ticket can be closed.

I was somehow assuming that components would get the base cpp info by default. But looks like this needs to be specified explicitly per component.

**Comment by stevn** [comment]
Somehow related:

https://github.com/conan-io/conan/issues/8564
https://github.com/conan-io/conan/issues/10444
https://github.com/conan-io/conan/issues/11490

**Comment by memsharded** [comment]
Yes, https://github.com/stevn/conan_editable_test/commit/98927f31342035103b71b073dffc1c96177fd3e8 is looking good
