### ISSUE TITLE
Review json logger in 2.0

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#13182]
### What is your suggestion?

There is a json logger in 2.0, which is not documented, and the interface not fully clear.
Let's review it for 2.0.1

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by gpxricky** [comment]
@memsharded 

Does this topic refer to the same problem that I can't notice the difference in the output result of the following commands:

```
conan remote list-users -f json
conan remote list-users -f json --logger
```

or 

```
conan remote list-users
conan remote list-users --logger
```

? The `--logger` options seems to be useless for me. CLI doc says that it should output `with log format, with time, type and message` but both outputs are equal for me.

**Comment by memsharded** [comment]
Yes, that ``--logger`` is unrelated to the output of list-users
