### ISSUE TITLE
Conan 2.0 layout method

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#13189]
### What is your question?

In the layout method I defined the following for the build folder
self.folders.build = str(self.options.CompClass)
Where self.options.CompClass = SWC

self.folders.source = self.name
where self.name = cstart

no_copy_source is set to False in my recipe file. When running the recipe file the build folders shows up as seen in the attached file inConan 2.0. In Conan 2b6 and 2b9 the cstart folder was copied inside the SWC folder but now it is outside the SWC folder. I have not changed the options listed above. Shouldn't the cstart folder be inside the SWC folder shown in the snapshot? The attached console log shows that the build folder is = to SWC

![Capture](https://user-images.githubusercontent.com/117375694/220753008-02e605aa-06fd-4cc2-9e9a-ee67fdecb1cd.PNG)
[consoleLog.txt](https://github.com/conan-io/conan/files/10808144/consoleLog.txt)

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

I am not sure that b9 behaved differently than the 2.0 in this regard.
The resulting layout that you are seeing is the expected one, the source_folder=cstart and the build_folder=SWC, both are siblings, everything looking correct.

**Comment by Ed-CMI** [comment]
I have many recipe files checkin where I defined the self.folders.build  and the source folder always was copied inside the self.folders.build folder. Why would the source code be outside of the build folder?  The manual indicates the self.folders.build specifies a subfolder where the files from the build are located.

**Comment by memsharded** [comment]
Yes, the ``self.folders.build`` indicates the subfolder where the build files are located, and the ``self.folders.source`` indicate the subfolder where the source files are located.

> I have many recipe files checkin where I defined the self.folders.build and the source folder always was copied inside the self.folders.build folder.

If you can share a reproducible case about this, we would gladly have a look. The ``source`` has always been copied by default to the cache "build" folder, which is not the same as ``self.build_folder``. So dependency on your layout definition, the ``source_folder`` and the ``build_folder`` could be the same or not.


> Why would the source code be outside of the build folder?

This is known as the out-of-source build, and nowadays it is kind of the most popular layout, as it is the one heavily recommended by CMake

**Comment by Ed-CMI** [comment]
I tried rolling my Conan back to 2b6 and now it shows the same thing. Attached is a snapshot from one of my team mates who right now is using 2.0 and is using the attached recipe file that setups the build folder. My teammate indicate he ran this using Conan 2.0

Line 68 shows         self.folders.build = str(self.options.Program). In this instance self.program.options is set to OctaneGold and the source folders is mcs_engpos. The attached snapshot shows the layout in cache as defined in the attached recipe file
![Capture](https://user-images.githubusercontent.com/117375694/220898942-2bde0286-6ea1-4055-b61f-
[conanfile.txt](https://github.com/conan-io/conan/files/10813199/conanfile.txt)
7fa6e05fe845.PNG)

**Comment by Ed-CMI** [comment]
Can we have a short meeting and I will try and get my teammate and me to demo

**Comment by memsharded** [comment]
Sorry, we are a bit swamped these days with the 2.0 launch, ConanCenter is still under maintenance for the migration, etc, that would need to wait. If you can try to upload the recipe (the above is broken, no recipe no output is shown) and the output (as text, not as images), we would try to have a look asynchronously when possible.

**Comment by Ed-CMI** [comment]
The attached conan.txt file is the python requires file that shows how the build folder is set in the csar_build_layout.  I reattached the snapshot as a word document that shows the build folder layout in cache.

[conanfile.txt](https://github.com/conan-io/conan/files/10813836/conanfile.txt)

[Layout_Snapshot.docx](https://github.com/conan-io/conan/files/10813837/Layout_Snapshot.docx)

**Comment by Ed-CMI** [comment]
Hi Diego

I found out what was wrong. I will close this issue. Thx for the support

**Comment by memsharded** [comment]
Ok, glad that you found the solution, thanks for following up!
