### ISSUE TITLE
[bug] conan.tools.files.get does not use proxy configuration

### ISSUE THREAD

**Issue by PengolodhGoedath** [conan-io/conan#13192]
### Environment details

* Operating System+version: Microsoft Windows Server 2019
* Compiler+version: Visual Studio Build Tools 2022
* Conan version: 1.53, 1.58
* Python version: 3.10.5 (not sure if conan brings its own version; it was installed via chocolatey)

### Steps to reproduce

1. Setup proxy:
```
conan config set proxies.http=http://user:password@proxy:port
conan config set proxies.https=http://user:password@proxy.port
conan config set "proxies.no_proxy_match=http://*.excluded.domain, https://*.excluded.domain"
```
2. Use `get` from `conan.tools.files` in a `ConanFile`:
```
from conan import ConanFile
from conan.tools.files import get

class McveConan(ConanFile):
    name = 'mcve'
    version = '0.0.1'
    def build(self):
        get(self, 'https://artifacts.excluded.domains/my/binary/artifact.zip')
```
3. run `conan create` on the MCVE conanfile

Expected behavior: Conan downloads the binary artifact without using a proxy
Observed behavior: Conan fails with error message 
```
mcve/0.0.1: ERROR: Error downloading file https://artifacts.excluded.domains/my/binary/artifact.zip: 'HTTPSConnectionPool(host='artifacts.excluded.domain', port=443): Max retries exceeded with url: /my/binary/artifact.zip (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable',)))'
mcve/0.0.1: ERROR: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' build failed
mcve/0.0.1: WARN: Build folder C:\w\p\bt\.conan\data\mcve\0.0.1\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
ERROR: mcve/0.0.1: Error in build() method, line 8
        get(self, 'https://artifacts.excluded.domains/my/binary/artifact.zip')
        ConanException: Error downloading file https://artifacts.excluded.domains/my/binary/artifact.zip: 'HTTPSConnectionPool(host='artifacts.excluded.domain', port=443): Max retries exceeded with url: /my/binary/artifact.zip (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable',)))'
```

---

Additional notes:
- Skipping step 1 above works around the issue. Not a general solution, as some recipes (especially some from conan-center) require proxy usage in order to be built.
- Same issue is present in old style `tools.get`.

**Comment by memsharded** [comment]
Hi @PengolodhGoedath 

Thanks for your report.

It seems your pattern is not actually matching. Internally, the comparison is doing a ``fnmatch``:
```
>>> fnmatch('https://artifacts.excluded.domains/my/binary/artifact.zip', "https://*.excluded.domains")
False
>>> fnmatch('https://artifacts.excluded.domains/my/binary/artifact.zip', "https://*.excluded.domains*")
True
```

You would need the ``*`` at the end.

**Comment by PengolodhGoedath** [comment]
Ah, that explains it. Seems I was too focused on matching the domain (as common in the `no_proxy` environment variable), and didn't think it would match the whole URL. Thanks for the quick response!

Something feels off about allowing matches in the complete URL (e.g. it seems `'https://other.domain/other.file?param=artifacts.excluded.domains'` would also be matched), but I guess that is not a problem for me (for now).
