### ISSUE TITLE
CMake generator creates a FOUND_LIBRARY cache entry

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#1319]
The FOUND_LIBRARY cache entry is used in internal function `conan_find_libraries_abs_path`. It should be unset before returning to not leak into CMakeCache.txt/cmake-gui etc.
Maybe also rename it to CONAN_FOUND_LIBRARY to avoid possible collisions?

**Comment by memsharded** [comment]
This has been solved by #1320
