### ISSUE TITLE
[question] How to conan install a single package with its reference in Conan 2.0?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#13194]
### What is your question?

How to conan install a single package with its reference in Conan 2.0?

In Conan 1.0, we can run `conan install` command with the package reference (`libevent/2.1.12@`) from the remote. For example:

```cmd
conan install libevent/2.1.12@ ^
-r conancenter ^
-pr:h win32-msvc16-x64-debug.ini ^
-pr:b win32.ini
```

However, it seems that Conan 2.0 cannot recognize the reference `libevent/2.1.12@`:

```cmd
C:\Users\hwhsu1231>conan --version
Conan version 2.0.0

C:\Users\hwhsu1231>conan search libevent/2.1.12
conancenter
  libevent
    libevent/2.1.12

C:\Users\hwhsu1231>conan install libevent/2.1.12@
ERROR: Conanfile not found at C:\Users\hwhsu1231\libevent\2.1.12@
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @hwhsu1231,
In Conan 2.0 you have to pass the `--requires` argument if you want to install the package with the reference name, like this:

```
conan install --requires=libevent/2.1.12
```

**Comment by hwhsu1231** [comment]
@czoido - I got it. Thanks!
