### ISSUE TITLE
[question] Possible Conan 2.0 issue w/ VCVars generator

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#13196]
Hi there,

Firstly, congratulations on the long-awaited Conan 2.0 release!

During some local experimenting, I have come across an intermittent issue where the `package` step seems to fail when running `conan create` for one of our recipes. It appears to not be able to copy the temporary build folder contents in the Conan cache to the final package folder e.g.

<details><summary><strong>Log Output</strong></summary>

```log
...
sdo-field-builder/0.1.0@shared: Exiting [SdoFieldBuilderConan].[build]
sdo-field-builder/0.1.0@shared: Package '723257509aee8a72faf021920c2874abc738e029' built
sdo-field-builder/0.1.0@shared: Build folder C:\Users\santhonisz\.conan2\p\t\sdo-f82806b5cba72d\b\.
sdo-field-builder/0.1.0@shared: Generating the package
sdo-field-builder/0.1.0@shared: Temporary package folder C:\Users\santhonisz\.conan2\p\t\sdo-f82806b5cba72d\p
sdo-field-builder/0.1.0@shared: Calling package()
sdo-field-builder/0.1.0@shared: package(): Packaged 1 '.exe' file: SdoFieldBuilder.exe
sdo-field-builder/0.1.0@shared: package(): Packaged 1 '.config' file: SdoFieldBuilder.exe.config
sdo-field-builder/0.1.0@shared: package(): Packaged 1 '.pdb' file: SdoFieldBuilder.pdb
sdo-field-builder/0.1.0@shared: Created package revision 7d7feccfc264dcd58e2f6cc82a123153
sdo-field-builder/0.1.0@shared: Package '723257509aee8a72faf021920c2874abc738e029' created
sdo-field-builder/0.1.0@shared: Full package reference: sdo-field-builder/0.1.0@shared#e8405177dfc3a5f5140beacf9169c826:723257509aee8a72faf021920c2874abc738e029#7d7feccfc264dcd58e2f6cc82a123153
ERROR: Couldn't move folder: C:\Users\santhonisz\.conan2\p\t\sdo-f82806b5cba72d->C:\Users\santhonisz\.conan2\p\sdo-f019a2dea9907b
Destination path 'C:\Users\santhonisz\.conan2\p\sdo-f019a2dea9907b\sdo-f82806b5cba72d' already exists
Folder might be busy or open. Close any app using it and retry.
```
</details>

<details><summary><strong>Host Profile</strong></summary>

```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
```
</details>

I wont bore you with the details of how I determined it (long and complex), but the root cause appears to be down to a race condition caused by the deault behaviour of the `vsdevcmd.bat` file in Visual Studio 2019+ to trigger the sending of telemetry data to Microsoft. That (PowerShell) process is locking the tempory build folder for a brief amount of time and leads to the intermittent failure in the `package` method execution.

As you would know the VCVars generator creates the call to `vcvarsall.bat` in the generated `conanvcvars.bat` file, which ultimately executes the `vsdevcmd.bat` file. 

Investigation revealed that it's possible to turn off the sending of telemetry data by setting the `VSCMD_SKIP_SENDTELEMETRY` environment variable. I tried it out and that seems to completely resolve the problem, and make the initial startup of `vcvarsall.bat` much quicker as well.

I did have the thought to set the environment variable in the `[buildenv]` section of the profile, however that unfortunatlely doesn't work as the `conanbuildenv` file generated to set the environment variable isn't called in the `conanbuild.bat` until after the call to `conanvcvars.bat` e.g.

```
@echo off
call "%~dp0/conanvcvars.bat"
call "%~dp0/conanbuildenv-release-x86_64.bat"
```

So I guess the question becomes is this something that Conan should set automatically e.g. in the `conanvcvars.bat` file, or rather is it something that end users should be made aware of and it is their responsibility to set in their development environments etc?  

It would appear the same issue came up for `vcpkg`, albeit for performance reasons, and they agreed to make it part of their CLI tools:

https://github.com/microsoft/vcpkg/issues/10468
https://github.com/microsoft/vcpkg/issues/8756

Finally I should also add that I've only experienced this issue when developing on my local PC and not in our CI environments, which leads me to beleive there may be a performance element associated with when the problem occurs.

I look forward to your feedback!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @santhonisz 

Thanks for your report and detailed investigation.

@jcar87 has been checking this too, and the key to define it in recipes is to do a ``.save_script(..., "xxxx.bat")``, forcing the .bat extension.

In any case, I agree it is better to make this built-in, so we will add it to Conan for the next patch 2.0.1. Thanks!

**Comment by memsharded** [comment]
Note for me:
```python
 env = Environment()
            env.define("__VSCMD_ARG_NO_LOGO", "1")
            env.define("VSCMD_SKIP_SENDTELEMETRY", "1")
            env.vars(self, 
```
