### ISSUE TITLE
[question] Is there a way to force update conan cache of a package

### ISSUE THREAD

**Issue by lijie-jiang** [conan-io/conan#13199]
Hello,

I'm unsure if there is a way to update the conan cache data for a package when the version number matches the one on the conan server. Currently, we're developing a package and don't plan to change its version number when updating the source code.

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by uilianries** [comment]
Hello @lijie-jiang !

I guess you are looking for the update parameter:

```
conan install foobar/0.1.0@company/stable -r company --update
```

It will fetch for package updates in your remote, and in case of finding it, it will update your local cache.

Documentation: https://docs.conan.io/2/reference/commands/install.html

OBS. It's the same command for Conan 1.x

**Comment by lijie-jiang** [comment]
Hello uilianries,

Great! It works. 

>
