### ISSUE TITLE
[bug] Conan remote add --force flag not working

### ISSUE THREAD

**Issue by mzukovec** [conan-io/conan#13208]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: Visual Studio 2022
* Conan version: 2.0.0
* Python version: 3.9.2

### Steps to reproduce

1. `conan remote add --force conancenter https://center.conan.io`
(In case it doesn't exist yet, first call will work)
2. `conan remote add --force conancenter https://center.conan.io`
`ERROR: Remote 'conancenter' already exists in remotes (use update to modify)`

### Logs

```
PS C:\Users\anon> conan remote add --force conancenter https://center.conan.io
PS C:\Users\anon> conan remote add --force conancenter https://center.conan.io
ERROR: Remote 'conancenter' already exists in remotes (use update to modify)
```

**Comment by AbrilRBS** [comment]
Hi! Thanks for your report
The `--force` flag works the other way around, it forces the creation of a _new_ remote which has a duplicated remote url already present, but does nothing for already defined remote names. For those you still need to use `update` as the error message suggests :)

**Comment by mzukovec** [comment]
In this case, the automated process of adding new remote becomes complex.

1. Execute `conan remote list` to get the list of all current remotes
2. Search through all available remotes to see if it already exists
3.a If it exists, execute `conan remote update`
3.b If it doesn't exist, execute `conan remote add`

Seems a bit too complex for such a trivial job?

Edit:
I'd expect if one supplies `--force` flag, remote gets overridden in any case?

**Comment by memsharded** [comment]
Hi,

I would like to suggest one thing: there shouldn't be an automated process of adding remotes.
Instead, defining remotes in a ``remotes.json`` file and managing it with ``conan config install``, together with some other configuration things, is the way to go. Remotes can be defined there as ``disabled`` too, so automated jobs main responsibility would be to enable certain ones.

**Comment by mzukovec** [comment]
Thanks for all the answers!

**Comment by memsharded** [comment]
Re-opening this, that will be closed by https://github.com/conan-io/conan/pull/13249, for next 2.0.1, allowing that behavior
