### ISSUE TITLE
[feature] Make a easy path for converting conanfile.txt to conanfile.py

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#13203]
### What is your suggestion?

When only consuming straightforward packages to build a simple project, [conanfile.txt](https://docs.conan.io/2/reference/conanfile_txt.html) is more than enough, but in case your project grows and need to add new logic, like using different package versions according to a specific OS, then [conanfile.py](https://docs.conan.io/2/reference/conanfile.html) is a better solution. However, converting `conanfile.txt` to a `conanfile.py` can be a monotonous task if you need to update many recipes in your enterprise code base.

It would be great if was possible to use a tool which read a `conanfile.txt` and generate an equivalent `conanfile.py`. With the new Conan 2.x feature [custom commands](https://docs.conan.io/2/reference/extensions/custom_commands.html), it would be possible to add such feature, but still it would be better if it could be centralized and maintained by Conan organization.

 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
This got a new repo contaning the command in https://github.com/conan-io/conan-extensions

And linked in https://github.com/conan-io/docs/pull/3040

So we can close this ticket as resolved, thanks @uilianries for proposing it
