### ISSUE TITLE
[bug] Can't provide custom logic for `build_requirements`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#13202]
### Environment details

* Conan version: 2.0

### Steps to reproduce

In Conan 1.0 it was possible to provide custom logic for `build_requriements`. In Conan 2.0, the below provides an error. I do not want the users to always install `catch` or `doxygen` and their dependencies if they explicitly state they do not want to build that part of the project.

```python
    @property
    def _build_all(self):
        return bool(self.conf["user.build:all"])

    @property
    def _skip_docs(self):
        return bool(self.conf["user.build:skip_docs"])

    def build_requirements(self):
        if self._build_all:
            self.test_requires("catch2/3.1.0")
            self.test_requires("wg21-linear_algebra/0.7.2")
        if not self._skip_docs:
            self.tool_requires("doxygen/1.9.4")
```

### Logs

```
ERROR: conanfile.py (mp-units/0.8.0): Error in build_requirements() method, line 126
        if self.conf["user.build:all"]:
        TypeError: 'Conf' object is not subscriptable
```

**Comment by mpusz** [comment]
BTW, it seems that the same issue applies to `generate()`:

```python
    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["UNITS_DOWNCAST_MODE"] = str(self.options.downcast_mode).upper()
        tc.variables["UNITS_BUILD_DOCS"] = self._build_all and not self._skip_docs
        tc.variables["UNITS_USE_LIBFMT"] = self._use_libfmt
        tc.generate()
        deps = CMakeDeps(self)
        deps.generate()
```

```
ERROR: conanfile.py (mp-units/0.8.0): Error in generate() method, line 156
        tc.variables["UNITS_BUILD_DOCS"] = self._build_all and not self._skip_docs
while calling '_build_all', line 92
        return bool(self.conf["user.build:all"])
        TypeError: 'Conf' object is not subscriptable
```

**Comment by jcar87** [comment]
Hi @mpusz  - 
It appears to be an issue with accessing `self.conf` - could you try `self.conf.get("user.build:all")` instead of `self.conf[]` - it should be possible to have conditional requirements.

for example:
https://github.com/conan-io/conan-center-index/blob/master/recipes/cairo/meson/conanfile.py#L143-L146

**Comment by mpusz** [comment]
Thanks! I just found it here as well: https://docs.conan.io/2/reference/conanfile/attributes.html?highlight=self%20conf#conf.
