### ISSUE TITLE
settings.yml does not seem to have an effect. 

### ISSUE THREAD

**Issue by schmidjo82** [conan-io/conan#13204]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: Visual Studio 16
* Conan version: 1.58
* Python version: 3.10.4
* 

### Steps to reproduce

1. change settings.yml. In my example i add compiler.cppstd 11 to Visual Studio compiler. (By the way: why is this missing?)
2. try 2 build a conan package with conan creater for recipe.
3. Result is: "ERROR: The specified 'compiler.cppstd=11' is not available for 'Visual Studio 17'. Possible values are ['14', '17', '20', '23']'"

Is it possible, that settings.yml is no longer used? Im pretty sure i have done something similar a while ago.  Can you help, to clarify that?

**Comment by memsharded** [comment]
Hi @schmidjo82 

Thanks for your quesiton

> change settings.yml. In my example i add compiler.cppstd 11 to Visual Studio compiler. (By the way: why is this missing?)

The VS compiler **never** defined a C++11 flag. The first flag it introduced was C++14. This is not a Conan issue, this is a VS limitation, it simply doesn't understand C++11 flags, they cannot be defined.

**Comment by memsharded** [comment]
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.
