### ISSUE TITLE
[question] How to modify the default directory of Binary Packages in Conan 2.0?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#13206]
### What is your question?

According to: https://github.com/conan-io/conan/issues/11690#issuecomment-1192415400, we can use the following two Conan-specific environment variables to change the default install directory of binary packages in Conan 1.0:

* [CONAN_USER_HOME](https://docs.conan.io/1/reference/env_vars.html#conan-user-home)
* [CONAN_USER_HOME_SHORT](https://docs.conan.io/1/reference/env_vars.html#conan-user-home-short)

However, it seems that the above settings is _not working_ with Conan 2.0.

I'm wondering how to modify the default directory of Binary Packages in Conan 2.0?

To be more specific, how to implement the following settings of Conan 1.0 in the Conan 2.0 way?

![image](https://user-images.githubusercontent.com/71438617/220911742-155c2331-d3e7-4bbd-9804-efb57e9b16f7.png)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hwhsu1231 

Please, use the ``CONAN_HOME`` env-var for 2.0

There is some docs like https://docs.conan.io/2/reference/config_files/global_conf.html?highlight=conan_home, but lets make it more explicit

**Comment by hwhsu1231** [comment]
@memsharded

Where can I see all the available env-vars in Conan 2.0? 

I cannot find "Environment Variables" option in "Reference".

![image](https://user-images.githubusercontent.com/71438617/220917287-8cab0599-24d3-4652-80b2-6cc09364933f.png)

**Comment by memsharded** [comment]
https://github.com/conan-io/docs/pull/3018 will add it

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3018

**Comment by hwhsu1231** [comment]
@memsharded  - Thanks for help. In my situation, I'll specify the `CONAN_HOME` as follows:

```
CONAN_HOME = D:\.conan2\home
```

![image](https://user-images.githubusercontent.com/71438617/222785128-72dd7ce1-d551-4b3f-9bee-8bf3ce50e01f.png)
