### ISSUE TITLE
[question] Is there a way to determine automatically if v2 or v1 is used in a project?

### ISSUE THREAD

**Issue by pgampe** [conan-io/conan#13216]
### What is your question?

Hi!

Is there a way to determine which major version of conan is used based of the files in the repository or with either the v1 or v2 command line tools?

So far I understand that the conanfile.py uses different imports (v1: conans, v2: conan). But is there any way to say this for a conanfile.txt? Or is the conanfile.txt the same for both?

Of course any repository revision older than the release date of v2 is very likely to be a v1 project.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @pgampe 

There are a few things related to the version:

- For sure you can always use ``conan --version`` to ask Conan which version it is running.
- Recipe files can declare a ``required_conan_version`` to define the minimum required Conan version to process that recipe
- ``global.conf`` can declare a ``core:required_conan_version``: Raise if current version does not match the defined range.

Also, there is some common subsyntax for conanfiles (both .py and .txt) that would be compatible simultaneously for latest 1.X and 2.0. We maintain compatibility of recipes in ConanCenter with this subsyntax. You can check: https://docs.conan.io/1/conan_v2.html

**Comment by memsharded** [comment]
Documenting ``required_conan_version`` in 2.0 docs, it was missing: https://github.com/conan-io/docs/pull/3020

**Comment by pgampe** [comment]
Thank you, that clarified things a bit. 

Given that v2 was only recently released, I think I can safely assume that v1 was used for all projects before 2023. I am doing repository data mining, therefore I am mostly interested in old records.
