### ISSUE TITLE
Add cmake generator support for RelWithDebInfo/MinRelSize configurations

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#1321]
This has been discussed in #917 already:

> target_link_libraries(library CONAN_PKG::MyLib), building will fail on empty build type and RelWithDebInfo

This quote still holds true. The RelWithDebInfo configuration may be useful in consumer projects e.g. for profiling.
A quick solution is to reuse `Release` packages and change the generated CMake files from

```
set_property(TARGET CONAN_PKG::zlib PROPERTY INTERFACE_INCLUDE_DIRECTORIES
    ${CONAN_INCLUDE_DIRS_ZLIB}
    $<$<CONFIG:Release>:${CONAN_INCLUDE_DIRS_ZLIB_RELEASE}>
    $<$<CONFIG:Debug>:${CONAN_INCLUDE_DIRS_ZLIB_DEBUG}>)
```
to
```
set_property(TARGET CONAN_PKG::zlib PROPERTY INTERFACE_INCLUDE_DIRECTORIES
    ${CONAN_INCLUDE_DIRS_ZLIB}
    $<$<CONFIG:Release>:${CONAN_INCLUDE_DIRS_ZLIB_RELEASE}>
    $<$<CONFIG:RelWithDebInfo>:${CONAN_INCLUDE_DIRS_ZLIB_RELEASE}>
    $<$<CONFIG:MinRelSize>:${CONAN_INCLUDE_DIRS_ZLIB_RELEASE}>
    $<$<CONFIG:Debug>:${CONAN_INCLUDE_DIRS_ZLIB_DEBUG}>)
```

**Comment by miqelm** [comment]
I found out that almost everything works well in version 0.24.
Shouldn't CONAN_DEFINES be set also for RelWithDebInfo and MinSizeRel build type?

In conanbuildinfo_multi.cmake there is only
`add_compile_options(${CONAN_DEFINES}
                        "$<$<CONFIG:Debug>:${CONAN_DEFINES_DEBUG}>"
                        "$<$<CONFIG:Release>:${CONAN_DEFINES_RELEASE}>")`

**Comment by memsharded** [comment]
Hi @miqelm 

I think you are right, these configurations are missing from the ``add_compile_options()``. Any reason @sixten-hilborn you didn't add them, or was it just accidentally skipped?

Would you like to make yourself a PR to fix it? I'd say it is just adding them, you can test locally, and if some test is broken, the CI will tell :)

Thank you!

**Comment by miqelm** [comment]
#1480

**Comment by sixten-hilborn** [comment]
Thanks for reporting and fixing this! I think I just overlooked `add_compile_options()` since I'm mostly using CMake TARGETS.
