### ISSUE TITLE
[bug] C++20 on MSVC 192.8

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#13213]
### Environment details

* Conan version: 2.0

### Steps to reproduce

With Conan 1.x I was able to test my C++20 project on Visual Studio 2019. The minimum requirement was 192.8, and it worked fine. However, Conan 2.0 do not allow setting the "Visual Studio" compiler anymore, and it claims that C++20 is supported only by Visual Studio 2022 (MSVC 193). Is it possible to test C++20 projects on Visual Studio 2019 with Conan 2.0?

### Logs

```
Found msvc 16
Detected profile:
Found gcc 8.1
[settings]
Found clang 15.0
arch=x86_64
WARN: This profile is a guess of your environment, please check it.
build_type=Release
WARN: The output of this command is not guaranteed to be stable and can change in future Conan versions.
compiler=msvc
WARN: Use your own profile files for stability.
compiler.cppstd=14
Saving detected profile to C:\Users\runneradmin\.conan2\profiles\default
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows

ERROR: The provided compiler.cppstd=[20](https://github.com/mpusz/units/actions/runs/4254422620/jobs/7400645358#step:12:21) requires at least msvc>=193 but version 192 provided
Error: Process completed with exit code 1.
```

See more: https://github.com/mpusz/units/actions/runs/4254422620/jobs/7400645358#step:12:38

**Comment by memsharded** [comment]
Thanks for reporting @mpusz, it should be fixed shortly.

If you want to give it a try, this is implemented in the profile plugin, so you can fix it yourself right now, without waiting for 2.0.1: https://docs.conan.io/2/reference/extensions/profile_plugin.html

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13278, for next 2.0.1
