### ISSUE TITLE
[question] CMakeToolchain CMakeUserPresets.json schema version

### ISSUE THREAD

**Issue by mzukovec** [conan-io/conan#13217]
### CMake presets schema version selection

Hi.

Is there a specific reason that the schema version is not the same in `CMakePresets.json` compared to `CMakeUserPresets.json`?
In case that user specifies `tools.cmake.cmaketoolchain.presets:max_schema_version=3`, the `CMakeUserPresets.json` uses the schema version 2, but `CMakePresets.json` uses version 3, which may cause errors if `CMakeUserPresets.json` is included first.

See the following:
[schema version detection](https://github.com/conan-io/conan/blob/843a4d86c8d05fa8c12e3937c292261d2e21ccdb/conan/tools/cmake/presets.py#L134)
[schema for CMakeUserPresets.json](https://github.com/conan-io/conan/blob/843a4d86c8d05fa8c12e3937c292261d2e21ccdb/conan/tools/cmake/presets.py#L240)
[schema for CMakePresets.json](https://github.com/conan-io/conan/blob/843a4d86c8d05fa8c12e3937c292261d2e21ccdb/conan/tools/cmake/presets.py#L165)

CMakeUserPresets therefore uses either schema version 2 or 4, but never 3, whereas CMakePresets can use 2 or 3.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

Edit:
Congrats for long awaited 2.0!

**Comment by memsharded** [comment]
Hi @mzukovec 

Thanks for your question.
I think this is a bit legacy, trying to accommodate some of the earlier CMake versions presets support.
I think that we could converge to use some more modern cmake so we can use the modern schema version always.

I'll discuss this with the team too, what do you think?

**Comment by mzukovec** [comment]
Hi. 

Thanks for your reply.
I think that at the two of them should match or at least the CMakeUserPreset.json version must be higher in order to support every field in CMakePresets.json file. 

I trust that you and your team will have a better insight into the following matter.

PS. Should I close the issue?

**Comment by memsharded** [comment]
No, please, leave it open until we discuss it and take a decision how to move forward.
Thanks for your insights!
