### ISSUE TITLE
[question] Unable to connect to conan.io / conan center from company network

### ISSUE THREAD

**Issue by MiSo1289** [conan-io/conan#13225]
### What is your question?

Hi, since yesterday we have been unable to connect to conan.io and conan center from our company network. I do not think it is an issue on our side (of course, it could be but I do not know how), I can ping the servers and the TCP connection can be established (and http -> https redirect works), but afterwards the requests hang:

```
$ wget conan.io
--2023-02-24 11:14:52--  http://conan.io/
Resolving conan.io (conan.io)... 35.244.198.18
Connecting to conan.io (conan.io)|35.244.198.18|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://conan.io:443/ [following]
--2023-02-24 11:14:56--  https://conan.io/
Connecting to conan.io (conan.io)|35.244.198.18|:443... connected.
```

Could it be due to us hitting some limits on the maximum number of requests by using conan center in our CI? Right now we are setting up a local cache for conan center, but the cache still needs to be able to connect to conan center to pull new packages.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MiSo1289 

Quick question: do you have access to the API of conancenter, like ``conan search "zlib*" -r=conancenter``? Is it only the web?

We changed some infrastructure in the last days for the launch of 2.0, but not sure how that could affect your side. Unless your company had some strict VPN/proxy rules that hardcoded some IPs or something.

**Comment by MiSo1289** [comment]
> Hi @MiSo1289
> 
> Quick question: do you have access to the API of conancenter, like `conan search "zlib*" -r=conancenter`? Is it only the web?
> 
> We changed some infrastructure in the last days for the launch of 2.0, but not sure how that could affect your side. Unless your company had some strict VPN/proxy rules that hardcoded some IPs or something.

Hi, thanks for a quick reply. To clarify, it is not just the web, we are also unable to access conan center from the conan CLI, eg running `conan install --update` (or normal install with clean cache) hangs when conan center is queried a package.

**Comment by MiSo1289** [comment]
```
$ cat ~/.conan/remotes.json 
{
 "remotes": [
  {
   "name": "conan-center",
   "url": "https://center.conan.io",
   "verify_ssl": true
  },
  // ... our remotes
```
```
$ conan --version
Conan version 1.59.0
```
```
$ conan search "zlib*" -r=conan-center
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ReadTimeoutError("HTTPSConnectionPool(host='center.conan.io', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conan-center=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

Running the command with the same setup on my home network succeeds.

**Comment by davidsanfal** [comment]
Hi @MiSo1289! 

I've been checking the external connection to our services and everything seems to be working properly. The infrastructure change we made last tuesday didn't affect to conancenter, it only affects the caching time of the conan.io page, so I don't think these changes are the reason of your connection problems.

Anyway, we will continue monitoring the connection to our services and if we discover something new I'll let you know.

**Comment by MiSo1289** [comment]
@davidsanfal It seems the connection problem has disappeared now. It is still unclear to me what was the cause, but thank you for your time investigating nonetheless. Closing the issue.
