### ISSUE TITLE
configure_dir parameter in AutoToolsBuildEnvironment requires a trailing slash

### ISSUE THREAD

**Issue by absassi** [conan-io/conan#1322]
In the method `AutoToolsBuildEnvironment.configure`, the parameter `configure_dir` can be used to specify the directory of the `configure` script, but it only works if the path ends with a slash. I think it should work without requiring that slash.

I can make a PR to fix this, if it is indeed a bug.

**Comment by memsharded** [comment]
You mean like ``self.configure(..., configure_dir="some/path/")``, right?
Yes, if not a bug, it seems a usability issue that can be improved, a PR would be great. Please @lasote confirm, just in case I am missing something.

**Comment by absassi** [comment]
Yes, I'd like the user to be able to type just `(..., configure_dir="some/path")`, since this is more compatible with things like:

```
env = AutoToolsBuildEnvironment(self)
rootdir = os.getcwd()
with tools.chdir(some_other_dir):
    env.configure(configure_dir=rootdir)
```

I'm sending the PR.
