### ISSUE TITLE
[bug] conan remote add --force does not work as expected (Conan 2.0)

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#13222]
### Environment details

Hi,

I'm running the following commands in Conan 2.0.0:

```
conan remote add test https://my-url/remote
conan remote add test https://my-url/remote --force
```

To my surprise I'm getting the following error message:

```
ERROR: Remote 'test' already exists in remotes (use update to modify)
```

So either the documentation of the `--force` flag is wrong or misleading ("Force the definition of the remote even if duplicated") or the functionality does not work yet.

Best regards,
gpxricky

**Comment by memsharded** [comment]
I think the docs for ``--force`` are not clear. The ``--force`` is to allow a duplicated URL, not to add the same remote ``name``.

I think it is the second issue related to this, lets reconsider if the same name should be allowed too.

**Comment by mzukovec** [comment]
> I think the docs for `--force` are not clear. The `--force` is to allow a duplicated URL, not to add the same remote `name`.
> 
> I think it is the second issue related to this, lets reconsider if the same name should be allowed too.

https://github.com/conan-io/conan/issues/13208

**Comment by memsharded** [comment]
Changing this to allow it in https://github.com/conan-io/conan/pull/13249, for next 2.0.1
