### ISSUE TITLE
[bug] sha256 signature failure for zlib

### ISSUE THREAD

**Issue by NAThompson** [conan-io/conan#13220]
### Environment details

* Operating System+version: Mac M1
* Compiler+version: AppleClang 14.0.0
* Conan version: 2.0.0
* Python version: 3.11.1

### Steps to reproduce

Given the following `conanfile.txt`:

```
[requires]
hdf5/1.14.0

[generators]
CMakeDeps
CMakeToolchain
```

Execute:

```
conan install . --build=missing
```

Error:

```
zlib/1.2.13: Calling source() in ~/.conan2/p/zlib9f370ca971ddf/s/src
ERROR: zlib/1.2.13: Error in source() method, line 51
	get(self, **self.conan_data["sources"][self.version],
	ConanException: sha256 signature failed for 'zlib-1.2.13.tar.gz' file.
 Provided signature: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
 Computed signature: a7c1b1322f90418410bf296ae95e028288d0a9c0a4231dcf65f8fce4e1187bde
```

**Comment by memsharded** [comment]
Hi @NAThompson 

Thanks for reporting.
This kind of error is not a Conan one, but typically something with ConanCenter recipe, and in this case, with the zlib tarball:
- something broke in the server providing the zlib tarball, and they changed that tarball
- someone hacked the zlib server
- there is some proxy or other man in the middle messing with files

I have just tried here:
```bash
conan install --requires=zlib/1.2.13 --build=zlib*

...
Decompressing conan_sources.tgz
zlib/1.2.13: Calling source() in C:\Users\memsharded\.conan2\p\zlib9f370ca971ddf\s\src
Downloading zlib-1.2.13.tar.gz


-------- Building package zlib/1.2.13 from source (1 of 1) --------
```
So it seems to be working fine

**Comment by jcar87** [comment]
We have seen this before - the server that hosts the zlib source package sometimes doesn't return the actual file, but a web page - it's unclear why, I believe it's some sort of traffic filtering, and some networks may be more affected than others.

**Comment by uilianries** [comment]
@NAThompson We didn't update the zlib checksum since we added that new version 2.1.13, which occurred in October 2022. I downloaded manually the source tar from zlib.net (https://zlib.net/fossils/zlib-1.2.13.tar.gz) and the sha256 is correct according to the conandata.yml

```
% wget https://zlib.net/fossils/zlib-1.2.13.tar.gz
--2023-02-24 10:44:50--  https://zlib.net/fossils/zlib-1.2.13.tar.gz
Resolving zlib.net (zlib.net)... 85.187.148.2
Connecting to zlib.net (zlib.net)|85.187.148.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1497445 (1,4M) [application/x-gzip]
Saving to: ‘zlib-1.2.13.tar.gz’

zlib-1.2.13.tar.gz                                                  100%[===================================================================================================================================================================>]   1,43M   796KB/s    in 1,8s    

2023-02-24 10:44:52 (796 KB/s) - ‘zlib-1.2.13.tar.gz’ saved [1497445/1497445]

% sha256sum zlib-1.2.13.tar.gz 
b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30  zlib-1.2.13.tar.gz
```

We had a past incident with other package, which the checksum computed was related to the package context, not to the tar file, but it was a server feature.

**Comment by memsharded** [comment]
Ok, so it seems a temporary glitch on the zlib server, not on Conan side.
Please re-check, and if it is gone, we can close the issue.

**Comment by NAThompson** [comment]
@memsharded : Thanks so much for your assistance-I have tried again this morning and the problem seems to have gone away.

Sorry for the noise.

**Comment by uilianries** [comment]
> Sorry for the noise.

@NAThompson By the contrary, thank you for reporting it. It was a false alarm, but could be something worst. Please, keep in mind to open issues directly to https://github.com/conan-io/conan-center-index when an error is related to a package and not Conan client itself. Have a great weekend.
