### ISSUE TITLE
Install from remote Conan 2

### ISSUE THREAD

**Issue by pipelinedestroyer** [conan-io/conan#13228]
### What is your question?

Hi,  I have a docker based on the following dockerfile:
```
FROM ubuntu

ENV TZ=Europe/Berlin
ENV LANG en_US.utf8
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y -f \
  locales git rsync vim bsdmainutils build-essential swig python3-full libboost-dev python3-dev python3-dbg python3-pip r-base cmake gdb time g++-12 gcc-12 \
  && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
  && rm -rf /var/lib/apt/lists/* \
  && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12 \
  && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12 \
  && update-alternatives --auto g++ \
  && update-alternatives --auto gcc
RUN pip install conan meson ninja mkdocs mkdocs-material

WORKDIR root

ENTRYPOINT ["tail", "-f", "/dev/null"]
```
now if I run `conan install boost/1.81.0@ --build=missing` within the container ( `conan remote list` gives `conancenter: https://center.conan.io [Verify SSL: True, Enabled: True]` as per default) I get the following error: `ERROR: Conanfile not found at /root/boost/1.81.0@` 

I'm new to the whole conan system so please excuse me if it's a simple fix.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @RerikOp 

Thanks for your question.
Conan 2.0 major version was released a couple of days ago, and that is the version that is being installed.
The syntax for 2.0 is ``conan install --requires=boost/1.81.0``, it has changed.

**Comment by pipelinedestroyer** [comment]
Great, thanks I'll edit the title so others can find it easily!
