### ISSUE TITLE
[question] conan v2: What is the rational for preventing access to `self.options` and `self.settings` in `package_id()`?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13227]
### What is your question?

This restriction can be very tedious to manage in complex recipes (see `arrow` recipe, good luck to make this recipe v2 compatible with such rule :s ).
So I'm wondering: what is the rational to forbid access to self.options & self.settings in package_id()? I have the feeling that it's the same one than old logic in `validate()` which has been reverted during beta (but meanwhile hundreds or CCI recipes have been corrupted with this logic).
I can't see any reason, and from my point of view this code makes little sense:

```python
def package_id(sef):
    if self.info.options.header_only:
        self.info.clear()
```

this one really express true logic of the recipe (when user set header_only option to True, it has a consequence on package id):

```python
def package_id(self):
    if self.options.header_only:
        self.info.clear()
```

Is it even possible to use helpers in package_id() since under the hood they have no concept of conditional access to info.options/info.settings depending on ConanFile method from which they are called? For example:

```python
def package_id(self):
    if is_msvc(self):
        # some logic
```

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @SpaceIm 

The ``compatibility.py`` and ``compatibility()`` work by creating different hypothesis that are assigned to ``self.info`` while each is is computed its ``package_id()``. If you use ``self.settings`` and ``self.options`` you would be computing based on wrong values, not the right ones, because that would be the ``package_id`` of the original input settings and options, not the "compatible" ones.

**Comment by SpaceIm** [comment]
Thanks, I think I understand. In a sense conan expects that all the logic in package_id() is based on compatible package options and settings and not original input options and settings.

I still don't understand how it can work when we want/have to use helpers like is_msvc() or is_apple_os() in package_id()?

**Comment by memsharded** [comment]
It cannot work, those helpers shouldn't be used there (and they will raise if tried to do so)

**Comment by SpaceIm** [comment]
Ouch, it will be a nightmare to fully migrate several complex conan-center recipes with tones of indirection in package_id() relying on common functions used in several methods.
Look at arrow recipe:
https://github.com/conan-io/conan-center-index/blob/945c14943832eb96cd59bdaf63cdabcebf29ad4c/recipes/arrow/all/conanfile.py#L213-L319
https://github.com/conan-io/conan-center-index/blob/945c14943832eb96cd59bdaf63cdabcebf29ad4c/recipes/arrow/all/conanfile.py#L544-L552

**Comment by SpaceIm** [comment]
It seems that arrow is the only CCI recipe with such convoluted logic, and I think actually that it comes from a bad recipe design anyway.
