### ISSUE TITLE
[question] conan v2: idiomatic way to set package_type depending on header_only option?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13231]
### What is your question?

Some recipes may have `shared`, `fPIC` and `header_only` options, and therefore be:
- shared if `shared` option is True and `header_only` option is False
- static if `shared` option is False and `header_only` option is False
- header-only if `header_only` option is True

The most famous recipe in conan-center with such options is `boost` of course.

What is the idiomatic way to set `package_type` in such recipe so that it can benefit from its side effects?

Is this recipe correct?

```python
class FooConan(ConanFile):
    name = "foo"
    package_type = "library"
    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "header_only": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
        "header_only": False,
    }

    def configure(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared or self.options.header_only:
            self.options.rm_safe("fPIC")
        if self.options.header_only:
            self.package_type = "header-only"
            del self.options.shared

    def layout(self):
        if self.options.header_only:
            basic_layout(self, src_folder="src")
        else:
            cmake_layout(self, src_folder="src")

    def package_id():
        if self.info.options.header_only:
            self.info.clear()
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @SpaceIm 

It is not necessary to do that, the ``package_type`` is already automatically deduced from the ``option`` value. Leave ``package_type="library"`` and it will automatically deduce "header-library" if ``header_only`` option.

**Comment by memsharded** [comment]
Closing this issue as solved, please re-open or create a new one if necessary
