### ISSUE TITLE
[question] How to detect local development flow in Conan v2?

### ISSUE THREAD

**Issue by bdegreve** [conan-io/conan#13245]
### What is your question?

In Conan v1, I add following property to my Conanfile to detect when I was using Conan in a local development flow:
```
    @property
    def _is_dev(self):
        return self.develop and not self.in_local_cache
```

I use this to enable testing when building the recipe for local development:
```
    tc.variables["BUILD_TESTING"] = self._is_dev
```

This will only turn on testing when building for local developement, and it will skip it when creating a new package in the cache.

However, Conan v2 no longer has the attributes `develop` and `in_local_cache`.  Is there an alternative method to know when I'm in local development flow?  Specifically during the generating phase.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @bdegreve 

Thanks for your question.
The development approach has changed a bit in Conan 2.0:
- the new CMake integrations are more transparent, allowing calling ``cmake`` to achieve the exact same build locally than with Conan calling ``conan build``. That means that in Conan 2.0 it is more expected that the local flow is often ``conan instal`` + calling the build tools.
- The ``layout()`` and ``generate()`` methods were designed for this purpose

But more importantly is that the "local development" means really nothing. So what has been introduced is a more powerful and customizable ``conf`` system
The example you cite is a very good example: now there is a new ``tools.build:skip_tests`` conf that will be used to automatically define ``BUILD_TESTING`` in the ``CMakeToolchain``, but also to inhibit running tests in the ``cmake.test()`` call. And can be used for other integrations as well. The improvement here is that now it is easier to do whatever is desired, sometimes it is more robust to run the unit-tests even if you are building in the cache, so you can define the value of the ``conf`` to do what you want, no matter if you are in the cache or you are local. Also the ``conf`` system has some advantages:
- It allows patterns to define ``conf`` per-package. Including the ``consumer`` package (the "development" one), with the ``&`` pattern
- It allows to define your own conf, like ``user.myteam:myconf=myvalue``, and you can use it to control whatever aspects of the build you want to control (metrics, logs, etc) that you might want to be able to turn on or off, irrespective if the package is being built locally or in the cache.

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
