### ISSUE TITLE
[bug] conan 2 does not support source and build directories on different drives under Windows

### ISSUE THREAD

**Issue by sakra** [conan-io/conan#13243]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: Visual Studio 2022 Community
* Conan version: 2.0.0
* Python version: 3.11.2

### Steps to reproduce

I am using out-of-source build with CMake. For organizatorial reasons, I need to have my source code repositories and my active build directories on different volumes on my Windows machine. The source code repo resides on volume drive S, the build directory are created on volume drive D.

The Conan 2 generator `CMakeToolchain` does not seem to work with that scenario, as it tries to compute a relative path from the source to the build directory, which results in a Python error (see log below).

### Logs

```
conanfile.txt: Writing generators to D:\Builds\helloworld_conan_vs2022
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: CMakeToolchain generated: conan_toolchain.cmake
conanfile.txt: Preset 'conan-windows-x86_64-msvc' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-windows-x86_64-msvc'
conanfile.txt: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=D:\Builds\helloworld_conan_vs2022\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
conanfile.txt: CMakeToolchain generated: CMakePresets.json
conanfile.txt: ERROR: Traceback (most recent call last):
  File "C:\Users\sakra\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\generators\__init__.py", line 70, in write_generators
    generator.generate()
  File "C:\Users\sakra\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\toolchain\toolchain.py", line 207, in generate
    write_cmake_presets(self._conanfile, toolchain, self.generator, cache_variables,
  File "C:\Users\sakra\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\presets.py", line 212, in write_cmake_presets
    _save_cmake_user_presets(conanfile, preset_path, user_presets_path, preset_prefix, data)
  File "C:\Users\sakra\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\presets.py", line 256, in _save_cmake_user_presets
    relpath = os.path.relpath(user_presets_path, conanfile.generators_folder)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 754, in relpath
ValueError: path is on mount 'S:', start on mount 'D:'

ERROR: Error in generator 'CMakeToolchain': path is on mount 'S:', start on mount 'D:'
```

**Comment by memsharded** [comment]
Hi @sakra 

Thanks for your report.
Quick question: is the ``--output-folder`` argument what you are using to point to another drive? Or is there something in your ``conanfile.py`` to try to specify that? If you could please provide a bit more of detail of how to trigger that exception, we would like to have a look and try to fix it.

**Comment by sakra** [comment]
I am using a plain `conanfile.txt`. Conan is invoked in the following way:

`conan.exe install --profile vs2022 --settings=build_type=Release --conf "tools.cmake.cmaketoolchain:generator=Ninja" -vverbose --update --build=missing "--output-folder=D:\Builds\helloworld_conan_vs2022_ninja_release" "S:\github\helloworld" `

global.conf contains the following setting:

`tools.cmake.cmake_layout:build_folder_vars=['settings.os','settings.arch','settings.compiler']`

**Comment by memsharded** [comment]
Thanks that really helped.
Fortunately it seems it was because some output messages, seems easy to fix, proposed a fix in https://github.com/conan-io/conan/pull/13248, for next 2.0.1.
