### ISSUE TITLE
[bug] Incorrect behavior when a common option is set twice for all dependencies & specific dependencies through configure()

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13240]
### Environment details

* Operating System+version: macOS Ventura
* Compiler+version: apple-clang 14
* Conan version: 2.0.0
* Python version: 3.11.2

### Steps to reproduce

Expected behavior: Force `shared=True` in all dependencies except few specific ones.

- The first approach through command line works fine:

  conanfile.py

  ```python
  from conan import ConanFile
  
  class FooConan(ConanFile):
      name = "foo"
      settings = "os", "arch", "compiler", "build_type"
  
      def requirements(self):
          self.requires("aaplus/2.41", force=True)
          self.requires("abseil/20230125.1", force=True)
          self.requires("bzip2/1.0.8", force=True)
          self.requires("zlib/1.2.13", force=True)
  ```
  
  ```
  conan install . -o "*:shared=True" -o "bzip/*:shared=False" -o "zlib/*:shared=False" -b missing
  ```

  `aaplus` & `abseil` are built as shared. `bzip2` & `zlib` as static. It's the expected behavior.

- The second approach where dependencies options are set in conanfile itself doesn't properly work:

  conanfile.py
  
  ```python
  from conan import ConanFile
  
  class FooConan(ConanFile):
      name = "foo"
      settings = "os", "arch", "compiler", "build_type"
  
      def configure(self):
          self.options["*"].shared = True
          self.options["bzip2"].shared = False
          self.options["zlib"].shared = False

      def requirements(self):
          self.requires("aaplus/2.41", force=True)
          self.requires("abseil/20230125.1", force=True)
          self.requires("bzip2/1.0.8", force=True)
          self.requires("zlib/1.2.13", force=True)
  ```
  
  ```
  conan install . -b missing
  ```

  `self.options["*"].shared = True` is ignored, `aaplus` & `abseil` are built with `shared=False` (default value of these 2 recipes). But If I remove `self.options["bzip2"].shared = False` & `self.options["zlib"].shared = False`, `shared=True` is honored in all dependencies...

**Comment by memsharded** [comment]
Hi @SpaceIm 

Thanks for reporting.
Indeed it seems that some legacy code from 1.X was moved into the assignment of dependencies options in ``configure()``, which was not behaving correctly. Proposing a fix in #13263, lets see how it goes.

**Comment by memsharded** [comment]
Fix in https://github.com/conan-io/conan/pull/13263 has been merged for 2.0.1

**Comment by SpaceIm** [comment]
@memsharded

After conan 2.0.1 release, I think there is still an issue.

Still the same example:

```python
    def configure(self):
        self.options["*"].shared = True
        self.options["bzip2"].shared = False
        self.options["zlib"].shared = False
```

`conan install` resolves bzip2 & zlib as shared=True instead of shared=False

I seems that https://github.com/conan-io/conan/pull/13263 fixed wildcard, but there is still no way in configure() to say: "I want all dependencies to be shared (potentially hundreds) expect few ones"

EDIT:

I see this test:

```python

    def test_multiple_options_patterns(self):
        c = TestClient()
        configure_consumer = textwrap.dedent("""
            from conan import ConanFile
            class Pkg(ConanFile):
                settings = "os", "arch", "compiler", "build_type"
                def requirements(self):
                    self.requires("dep1/1.0")
                    self.requires("dep2/1.0")
                    self.requires("dep3/1.0")
                    self.requires("dep4/1.0")
                def configure(self):
                    self.options["*"].shared = True
                    self.options["dep1*"].shared = False
                    self.options["dep2*"].shared = False
            """)
        c.save({"dep/conanfile.py": self.dep,
                "pkg/conanfile.py": configure_consumer})
        for d in (1, 2, 3, 4):
            c.run(f"export dep --name dep{d}")

        c.run("install pkg --build=missing")
        assert "dep1/1.0: SHARED: False!!" in c.out
        assert "dep2/1.0: SHARED: False!!" in c.out
        assert "dep3/1.0: SHARED: True!!" in c.out
        assert "dep4/1.0: SHARED: True!!" in c.out
```

I'm confused by:

```python
                    self.options["dep1*"].shared = False
                    self.options["dep2*"].shared = False
```

Is `*` wildcard needed also ? But how can I be sure than only `dep1` & `deps2` are static and not some `dep1foo` recipe? Moreover if it's really needed it may be problematic for cross v1/v2 compatibility of CCI recipes.

**Comment by memsharded** [comment]
> Is * wildcard needed also ? But how can I be sure tha

Yes, it is needed, if you want to make it more exact use ``self.options["dep1/*"]``

**Comment by SpaceIm** [comment]
> > Is * wildcard needed also ? But how can I be sure tha
> 
> Yes, it is needed, if you want to make it more exact use `self.options["dep1/*"]`

It doesn't work, I hit again original issue where the first `self.options["*"].shared = True` is not honored. Actually I see this issue in a far more complex dependency graph (hundreds of recipes), `self.options["*"].shared = True` is partially honored.

And as I said this syntax is problematic for v1/v2 compatibility of recipes, conan-center maintainers should be notified of this incompatibility. Why `self.options["dep1"]` doesn't mean `self.options["dep1/*"]` in conan v2? It's probably the only usage of 99% of users.

**Comment by memsharded** [comment]
> It doesn't work

Can you please clarify it? I just checked it, and this test also works fine:

```python
    def test_multiple_options_patterns2(self):
        c = TestClient()
        configure_consumer = textwrap.dedent("""
            from conan import ConanFile
            class Pkg(ConanFile):
                settings = "os", "arch", "compiler", "build_type"

                def requirements(self):
                    self.requires("dep1/1.0")
                    self.requires("dep2/1.0")
                    self.requires("dep3/1.0")
                    self.requires("dep4/1.0")

                def configure(self):
                    self.options["*"].shared = True
                    self.options["dep1/*"].shared = False
                    self.options["dep2/*"].shared = False
            """)
        c.save({"dep/conanfile.py": self.dep,
                "pkg/conanfile.py": configure_consumer})
        for d in (1, 2, 3, 4):
            c.run(f"export dep --name dep{d}")

        c.run("install pkg --build=missing")
        assert "dep1/1.0: SHARED: False!!" in c.out
        assert "dep2/1.0: SHARED: False!!" in c.out
        assert "dep3/1.0: SHARED: True!!" in c.out
        assert "dep4/1.0: SHARED: True!!" in c.out
```
