### ISSUE TITLE
[bug] Package ID for self.tested_reference_str not calculated correctly when options set on dependent package

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#13241]
### Environment details

* Operating System+version: Arch Linux
* Compiler+version: clang 15.0.7
* Conan version: 2.0.0
* Python version: 3.11.0

### Steps to reproduce

1. `git clone https://github.com/samuel-emrys/python-virtualenv.git`
2. `cd python-virtualenv`
3. `git checkout feature/6-conan2-fixes`
4. `conan remote add mtolympus-conan https://mtolympus.jfrog.io/artifactory/api/conan/mtolympus-conan`
5. `conan create . --user user --channel testing`

Observe the following error:

```
python-virtualenv/system@user/testing: Created package revision f8fc19eb58513b098893c4ad669185a3
python-virtualenv/system@user/testing: Package '572db8f1ba56708bcf5092af8ac484570c604ce2' created
python-virtualenv/system@user/testing: Full package reference: python-virtualenv/system@user/testing#034209adbd4c5f29ca8ce53415e77f2f:572db8f1ba56708bcf5092af8ac484570c604ce2#f8fc19eb58513b098893c4ad669185a3
python-virtualenv/system@user/testing: Package folder /home/user/.conan2/p/pytho0f713133974c1/p

======== Launching test_package ========

======== Computing dependency graph ========
Graph root
    python-virtualenv/system@user/testing (test package): /home/user/projects/python-virtualenv/test_package/conanfile.py
Build requirements
    python-virtualenv/system@user/testing#034209adbd4c5f29ca8ce53415e77f2f - Cache
Python requires
    pyvenv/0.1.1@mtolympus/stable#d8b9d47458878e9c8d15ed1f881f6c50 - Cache

======== Computing necessary packages ========
Build requirements
    python-virtualenv/system@user/testing#034209adbd4c5f29ca8ce53415e77f2f:ba73988a7e88beaae827c90205730611930dd354 - Missing

======== Installing packages ========
ERROR: Missing binary: python-virtualenv/system@user/testing:ba73988a7e88beaae827c90205730611930dd354

python-virtualenv/system@user/testing: WARN: Can't find a 'python-virtualenv/system@user/testing' package binary 'ba73988a7e88beaae827c90205730611930dd354' for the configuration:
[settings]
arch=x86_64
os=Linux
[options]
requirements=["sphinx", "sphinx-rtd-theme"]
[python_requires]
pyvenv/0.1.Z@mtolympus/stable

ERROR: Missing prebuilt package for 'python-virtualenv/system@user/testing'
Check the available packages using 'conan list python-virtualenv/system@user/testing:* -r=remote'
or try to build locally from sources using the '--build=python-virtualenv/system@user/testing' argument

More Info at 'https://docs.conan.io/en/2/knowledge/faq.html#error-missing-prebuilt-package'
```

This occurs because in [`test_package/conanfile.py`](https://github.com/samuel-emrys/python-virtualenv/blob/03fc74a6f8eed8e4b58f989167e4609ba4c7478e/test_package/conanfile.py#L14-L20), I have the following statement:

```python
    def build_requirements(self):
        self.tool_requires(self.tested_reference_str, options={
            "requirements": json.dumps([
                "sphinx",
                "sphinx-rtd-theme",
            ])
        })
```

If this is modified to

```python
    def build_requirements(self):
        self.tool_requires(self.tested_reference_str)
```
Then everything works as expected.

I think that package id evaluation in the test_package should consider the options placed on requirements under test. If it's not, this restricts testing to only the default configuration of a package. In this case, that wouldn't be a meaningful test because the default configuration is effectively no configuration.

### Logs

To save effort in reproduction, this can be observed in the github actions log:
* [Creates package id `572db8f1ba56708bcf5092af8ac484570c604ce2`](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4275122654/jobs/7442235627#step:5:85)
* [Tries to use package id `ba73988a7e88beaae827c90205730611930dd354` for `self.tested_reference_str`](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4275122654/jobs/7442235627#step:5:106) (which is the id for no options, as specified in `default_options`)

**Comment by memsharded** [comment]
Hi @samuel-emrys 

Thanks for your detailed report.
It seems this was a deliberated decision in the design of Conan 2.0:

We completely decoupled the generation of the package from the posterior ``test_package`` of it. The ``test_package`` step is not even loaded or evaluated when creating the binary package. This is because:
```bash
$ conan create .
$ conan create . -tf=None # or -tf=""
$ conan create . -tf=other
```
Was creating different packages. We thought that this was very inconsistent, the ``test_package`` should not be changing or defining which binary is being built. In other words, this:
```bash
$ conan create . -tf=None
$ conan test test_package pkg/1.0@
```
was also creating the "binary missing" error, which didn't make sense either (also because ``test`` couldn't build).
This was also very confusing for users that ``conan create .`` some package, but lately when they are consuming that package they found a "binary missing" error, just because the consumers are not passing the same options hidden in the ``test_package`` conanfile.
In Conan 2.0, now the ``conan create .`` is identical to the two above commands, which should work if provided with the same input profiles.

The approach in Conan 2.0 is that ``test_package`` shouldn't be used as a substitute or origin for configuration information. If there are several binaries with different ``package_ids``, they shouldn't be determined by different ``test_package`` folders, but by different profiles or command line arguments. We probably need to document this somewhere in the new docs a bit more explicitly.

Please let me know if this clarifies the behavior a bit.

**Comment by samuel-emrys** [comment]
Hmm, okay. I understand the rationale. It does make things a bit more verbose from the user perspective, but if the change I need to make is to provide configuration from the command line then I can live with that.

It is a bit of a shame though, because I was treating the `test_package`s as "working exemplars" of how a consumer can use the libraries. It was nice that it doubled up as developer documentation. There's still some value here, but it won't be appropriate for the "this is how you configure the options" type examples.

I've also noticed that it's not entirely consistent for `python-requires` packages with this workflow:

```python
$ conan create . -tf=None
$ conan test test_package pkg/1.0@
```
but I'll raise another issue to describe that in more detail.

**Comment by memsharded** [comment]
> It is a bit of a shame though, because I was treating the test_packages as "working exemplars" of how a consumer can use the libraries. It was nice that it doubled up as developer documentation. There's still some value here, but it won't be appropriate for the "this is how you configure the options" type examples.

Yes, seems a bit of a non expected usage of the feature. In theory it should be the other way, the ``test_package`` should be the minimal thing to check that the package has been correctly created. 
I think for the examples-docs that you mention, I would create a dedicated "examples" folder, and to make it work it is as simple as a single ``conan build .`` command. That includes the ``conan install`` in Conan 2.0, so you can pass all the same arguments as ``conan install``, it allows to define different options, it allows a clear ``--build=missing`` argument (so it is very efficient, as opposed to ``create`` that by default builds again the package from source, even if it is the same binary, just different example), etc. 

> I've also noticed that it's not entirely consistent for python-requires packages with this workflow:

yep, ``python_requires`` are a bit more tricky to inject into the test_package, so it is very likely that they can have issues with the separated flow.

**Comment by samuel-emrys** [comment]
> Yes, seems a bit of a non expected usage of the feature. In theory it should be the other way, the `test_package` should be the minimal thing to check that the package has been correctly created.

Yeah - in this situation those are essentially the same thing. I guess it stems from the philosophy of using unit tests to demonstrate usage of an API, which is a popular philosophy at the moment. I think the conan unit tests serve a similar purpose because you're testing "use cases" for the API. The tests are driven by behavioural examples, which makes them reasonably good exemplars that document intended usage. I'll consider an examples directory though.

To clarify your proposed solution here, are you suggesting the following?
```bash
conan create . --user user --channel testing -pr:h default -pr:b default -o 'python-virtualenv*:requirements=["sphinx","sphinx-rtd-theme"]' -tf test_package
```
This still appears to give me a similar error - the requirements are correctly propagated and installed with the package, but the test_package doesn't seem to pick up on the fact that the library has been built with options:
* [Command](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4291399659/jobs/7476533219#step:5:1)
* [Error](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4291399659/jobs/7476533219#step:5:239)

You can also see [here](https://github.com/samuel-emrys/python-virtualenv/actions/runs/4291399659/jobs/7476533219#step:5:244) that the test_package is using the default value for `requirements`, rather than what's been specified on the command line.

Thoughts/advice?

**Comment by samuel-emrys** [comment]
Update: seems to work fine when passing options to both profiles, i.e.
```
conan create . --user user --channel testing -pr:h default -pr:b default \
-o:b 'python-virtualenv*:requirements=["sphinx","sphinx-rtd-theme"]' \
-o:h 'python-virtualenv*:requirements=["sphinx","sphinx-rtd-theme"]' -tf test_package
```
I guess this makes sense - host profile is needed to create the main recipe with the right settings, build profile is needed for the `tool_requires` in the test_package.

Build is still failing due to #13237 , but that's unrelated to this so closing. Thanks for the help!

**Comment by memsharded** [comment]
Thanks for the feedback!

I think you might also be interested in the ``--build-require`` argument: when the package being created and tested is intended for ``tool_requires``, passing the ``conan create --build-require`` argument will directly create the package in the "build" context, receiving the build profile. With that, maybe passing the "host" option is not necessary anymore.

(also the ``--build-require`` works without ``test_package`` at all)
