### ISSUE TITLE
[question] conan2: package id default modes

### ISSUE THREAD

**Issue by dornbirndevelops** [conan-io/conan#13253]
### What is your question?

Hello!
In my currently used configuration file for 1.x the content looks like this:

`conan.conf`
```ini
[general]
required_conan_version = >=1.51.3
full_transitive_package_id = 1
default_package_id_mode = recipe_revision_mode  # environment CONAN_DEFAULT_PACKAGE_ID_MODE
revisions_enabled = True                        # environment CONAN_REVISIONS_ENABLED
user_home_short = None                          # environment CONAN_USER_HOME_SHORT
```

I had a look on the available options via `conan config list` and decided to give it a try.
Leaving `full_transitive_package_id`, `revisions_enabled`, and `user_home_short` aside, I set up my next gen configuration file like below to accomplish the same behavior as in 1.x. Unfortunately, each line yields a different error. See comment in line below each setting.

`global.conf`
```ini
core:required_conan_version: >=2.0.0
# --> Error in Conan initialization: Conf 'core:required_conan_version: >' cannot have a package pattern

core.package_id:default_build_mode: 'full_mode' # By default, 'None'
# --> Error in Conan initialization: Bad conf definition: core.package_id:default_build_mode: 'full_mode' # By default, 'None'

core.package_id:default_embed_mode: 'full_mode' # By default, 'full_mode'
# --> Error in Conan initialization: Bad conf definition: core.package_id:default_embed_mode: 'full_mode' # By default, 'full_mode'

core.package_id:default_non_embed_mode: 'full_mode' # By default, 'minor_mode'
# --> Error in Conan initialization: Bad conf definition: core.package_id:default_non_embed_mode: 'full_mode' # By default, 'minor_mode'

core.package_id:default_python_mode: 'full_mode' # By default, 'minor_mode'
# --> Error in Conan initialization: Bad conf definition: core.package_id:default_python_mode: 'full_mode' # By default, 'minor_mode'

core.package_id:default_unknown_mode: 'full_mode' # By default, 'semver_mode'
# --> Error in Conan initialization: Bad conf definition: core.package_id:default_unknown_mode: 'full_mode' # By default, 'semver_mode'
```

How would a correct equivalent look like?
What are all these modes? In which scenarios are they used?
What are the values possible in the respective setting?

I couldn't find this information in the documentation yet, which is why I'm asking.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @dornbirndevelops 

I think the key is that a ``=`` is necessary in the ``global.conf`` instead of another ``:``, based on https://docs.conan.io/2/reference/config_files/global_conf.html#configuration-file-template

Also, quotes would be unnecessary.
Please try that and let us know.

**Comment by dornbirndevelops** [comment]
Hi @memsharded, substituting the second `:` with `=` works, thank you for that hint.

I also figured out that the previously set `default_package_id_mode` setting seems to be only related to `core.package_id:default_non_embed_mode`, but not really to the others.

I ended up with a `global.conf` like this:
```ini
core:required_conan_version = >=2.0.0
# # By default, 'None'
# core.package_id:default_build_mode = full_mode
# # By default, 'full_mode'
# core.package_id:default_embed_mode = full_mode
# By default, 'minor_mode'
core.package_id:default_non_embed_mode = full_mode
# # By default, 'minor_mode'
# core.package_id:default_python_mode = full_mode
# # By default, 'semver_mode'
# core.package_id:default_unknown_mode = full_mode
```

I'm looking forward to the documentation update that explains these different modes and why I should care about them.

**Comment by memsharded** [comment]
Yes, those docs are pending.
In the meantime, this conference talk explain about it, it will probably help: https://youtu.be/kKGglzm5ous
