### ISSUE TITLE
C:\Users\username\conan2

### ISSUE THREAD

**Issue by leisun83** [conan-io/conan#13250]
### What is your question?

I'm new to conan and need some help with the settings. 

Whenever I run "conan config install" command, it will install at "C:\Users\username\conan2\" folder, is there any way to route it back to the default  "C:\Users\username\conan\" directory? I figure out it should be conan config home, how to change the path?

Thanks. 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @leisun83 thanks for your question! It seems you're using the newly released 2.0 version of Conan, in which `conan2/` _is_ the default home directory. The old `conan/` was used for versions 1.X, and its contents are not compatible with the new layout of the new major version, so I would suggest not using the same folder as the old versions.

In case you ever still need to change the path, https://docs.conan.io/2.0/reference/environment.html#conan-home specifies that the environment variable `CONAN_HOME` affects the location of Conan's home folder :)

**Comment by hwhsu1231** [comment]
It seems that this issue is related/duplicate to mine: https://github.com/conan-io/conan/issues/13206

**Comment by leisun83** [comment]
Thanks @hwhsu1231. It's very helpful.
