### ISSUE TITLE
[question] What's the diffrence between revision and package_id?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#13251]
### What is your question?

Does package_id calculate by settings, options and requirements, and revisions calculate by the content of package and conanfile?
Does this two have connection?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by samuel-emrys** [comment]
Yes, your understanding is pretty much correct. They are connected in the sense that they both provide you with a difference slice of parameters that make a recipe/package unique. Read the following pages for more info:
* [package_id()](https://docs.conan.io/2/reference/conanfile/methods/package_id.html#package-id)
* [Revisions](https://docs.conan.io/2/tutorial/versioning/revisions.html)
