### ISSUE TITLE
[question] Can I specifically install one package by using conan install like conan 1.5x?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#13252]
### What is your question?

For example, I can use "conan install zlib/1.2.13@ -r=conancenter", but in conan 2.0 I can't find similar command to get it.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by Tumb1eweed** [comment]
oh, I can use conan install --require

**Comment by memsharded** [comment]
And the good part is that there are some good improvements that come together with that syntax:
- You can do multiple ``--require=xxxx --require=yyy`` in the same command
- You can do multiple ``--tool_require=zzzz --tool_require=wwww`` in the same command
- You can mix both multiple ``--require`` and ``--tool_require`` in the same command.
