### ISSUE TITLE
[question] How to get recipe name and version

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan#13259]
### What is your question?

Hi conan community,

With conan 1.x releases, I used to call following shell commands:

- export PACKAGE_NAME=`conan inspect . --raw name`
- export PACKAGE_VERSION=`conan inspect . --raw version`

to get recipe name and version from golden source, typically when version is stored in the root CMakeLists.txt.
These environments variables were used after in `conan test` or `conan upload`, typically in my continuous integration pipeline.

But with conan 2.x releases, I don't see anymore `conan inspect` command and `conan graph` doesn't help better.
Do you have a replacement for `inspect` command?
Or a better mean to invoke conan commands with local conanfile.py in current directory without specifying recipe name and release since these infos are already known by local conanfile.py?

Regards.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @EstebanDugueperoux2, thanks for your question. You mention that you don't see `conan inspect` anymore in Conan 2, but it's there.

The feature that's missing from Conan 1 is the `--raw` argument to select the field you're interested in. You can simulate this output with things such as `jq` and the `--format json` formatter. `conan inspect . --format=json | jq -C '.name'` will output `"<name>"`, maybe that's something that can help you with your case. But let us know if this does not fit your usecase, and we can take a look into helping you

**Comment by EstebanDugueperoux2** [comment]
Hi @RubenRBS,

You are right, I can use jq in pipe, I'll do that.
And what do you think about the possibility to invoke 'conan test' and 'conan upload' commands using local conanfile.py as reference to retreive package name and version?

Regards.

**Comment by EstebanDugueperoux2** [comment]
One more remark, jq is not installed by default in official conan Docker images.
It would be nice to have common scenarii like invoking conan commands in conan Docker official images without installing another ubuntu package.
I tell that because in my case, I need to have cmake build done in the git clone in my continuous integration, to have gtest execution results and cppcheck quality analysis results in the git clone, to have these results fetched in another CI job by my sonar client.
Then I don't call directly "conan create" command but "conan install ...", "conan build .", ... .

What do you think about that?

**Comment by uilianries** [comment]
> But with conan 2.x releases, I don't see anymore conan inspect command and conan graph doesn't help better.

Have you tried `conan graph info --filter`?

> One more remark, jq is not installed by default in official conan Docker images.

It's no possible. Docker images are designed for building, not for development. Why? Image size, smaller is better. In the past we had vim and other cool tools, but in the end, 99% of time, docker images are consumed by the CI, not by us. Here is an old PR which we used to removed dev tools, we reduced around 25% of image size on that time: https://github.com/conan-io/conan-docker-tools/pull/92

But you still can create docker images which uses Conan docker images as their base, so you can customize as you want.

**Comment by EstebanDugueperoux2** [comment]
Hi @uilianries,

Thanks for your feedback.
I agree to keep Docker images small.
My purpose is to keep package name and version in a single place, in conanfile.py for package name and in my root CMakeList.txt for the version, for this last I use a custom python file to have conanfile.py retreive this version from CMakeLists.txt.

"conan graph info" seems powerfull but too much for my use case because it needs all options about profiles ...

I have tested "conan graph info . --profile:build .conan/profiles/gcc8 --profile:host .conan/profiles/gcc8 --filter name*" and get many output:

```
======== Computing dependency graph ========
Graph root
    conanfile.py (TslServer/11.0.3-build.3): /export/home/workingArea/dev/tablesetuplibrary/tslServer/conanfile.py
Requirements
    gflags/2.2.2#48d1262ffac8d30c3224befb8275a533 - Cache
    glog/0.6.0#cd13843f23fa8acb929e6eac693780ba - Cache
    libunwind/1.6.2#3fd3894a7a2dc2413b3284a7f53029b9 - Cache
    xz_utils/5.4.0#394283edeac4658356894312aa0fdcbb - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
Build requirements
    cmake/3.25.2#1e43a83edba41c63a6d14e02baf20134 - Cache
    ninja/1.11.1#a2f0b832705907016f336839f96963f8 - Cache
    openssl/1.1.1t#1e58dd56a2a930f23160558c572a62fd - Cache

======== Computing necessary packages ========
Requirements
    gflags/2.2.2#48d1262ffac8d30c3224befb8275a533:baeed852c575e87fdb16dccad08576ad5cf4e03b - Missing
    glog/0.6.0#cd13843f23fa8acb929e6eac693780ba:d9ca355d2eac0a0110358773ff8fe2d774ad165a - Missing
    libunwind/1.6.2#3fd3894a7a2dc2413b3284a7f53029b9:ebfade8eb321b5fa37a4bd0d348c970dbd32aab8 - Missing
    xz_utils/5.4.0#394283edeac4658356894312aa0fdcbb:897e6fde718e72637d92b0b8ed929893a1976238 - Missing
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f:897e6fde718e72637d92b0b8ed929893a1976238 - Missing
Build requirements
    cmake/3.25.2#1e43a83edba41c63a6d14e02baf20134:ff5e53e9b5c345ad76f596e0ec4681a7eadc5ee1 - Missing
    ninja/1.11.1#a2f0b832705907016f336839f96963f8:3593751651824fb813502c69c971267624ced41a#a53f170b60a46aef75ead8658bdeae05 - Download (conancenter)
    openssl/1.1.1t#1e58dd56a2a930f23160558c572a62fd:896855b1e3b5961bfcc08e699116d9ed588cac00 - Skip

======== Basic graph information ========
TslServer/11.0.3-build.3:
  ref: TslServer/11.0.3-build.3
glog/0.6.0#cd13843f23fa8acb929e6eac693780ba:
  ref: glog/0.6.0#cd13843f23fa8acb929e6eac693780ba
gflags/2.2.2#48d1262ffac8d30c3224befb8275a533:
  ref: gflags/2.2.2#48d1262ffac8d30c3224befb8275a533
libunwind/1.6.2#3fd3894a7a2dc2413b3284a7f53029b9:
  ref: libunwind/1.6.2#3fd3894a7a2dc2413b3284a7f53029b9
xz_utils/5.4.0#394283edeac4658356894312aa0fdcbb:
  ref: xz_utils/5.4.0#394283edeac4658356894312aa0fdcbb
zlib/1.2.13#13c96f538b52e1600c40b88994de240f:
  ref: zlib/1.2.13#13c96f538b52e1600c40b88994de240f
cmake/3.25.2#1e43a83edba41c63a6d14e02baf20134:
  ref: cmake/3.25.2#1e43a83edba41c63a6d14e02baf20134
openssl/1.1.1t#1e58dd56a2a930f23160558c572a62fd:
  ref: openssl/1.1.1t#1e58dd56a2a930f23160558c572a62fd
cmake/3.25.2#1e43a83edba41c63a6d14e02baf20134:
  ref: cmake/3.25.2#1e43a83edba41c63a6d14e02baf20134
openssl/1.1.1t#1e58dd56a2a930f23160558c572a62fd:
  ref: openssl/1.1.1t#1e58dd56a2a930f23160558c572a62fd
ninja/1.11.1#a2f0b832705907016f336839f96963f8:
  ref: ninja/1.11.1#a2f0b832705907016f336839f96963f8
```

and using '-v' to control the level of detail doesn't help.
I have seen --package-filter option but my purpose is to get the package name :)

In my use case a better change would be to have  'conan test' and 'conan upload' commands using local conanfile.py as reference to retreive package name and version.
What do you think about that?

Regards.

**Comment by uilianries** [comment]
In that case, the `conan inspect` command is the better way, just like Rubén commented before.

**Comment by EstebanDugueperoux2** [comment]
ok I'll remains on `conan inspect` with jq.
too bad for the possibility to use local conanfile.py for `conan test` and `conan upload` commands, I have tried :).
Thanks for your support.
