### ISSUE TITLE
[feature] Adding --build-folder flag to export-pkg command 

### ISSUE THREAD

**Issue by lo1ol** [conan-io/conan#13262]
### What is your suggestion?

Hi!

I use conan only to get and upload my dependencies,  and doesn't use it for building. So, I suppose to use this workflow at my projects:
1. Get path to dependency's package_foldres via `conan install --format json`. (this action is performed by qbs)
2. Qbs build my project
3. User or CI call `conan export-pkg` to add build package to cache

conan 1.0 has `--build-folder` flag to specify the directory with build artifacts, but conan 2.0 hasn't. I found only one way specify this path -- it's `layout` method. But I don't want to harcode build folder to conanfile, because this path may differ at CI and User.

Can you please add `--build-folder` flag to conan 2.0 version of export-pkg?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lo1ol 

I think you might be looking for the ``--output-folder`` in 2.0 (it is also there in 1.X). It is very similar to the ``--build-folder``, but it still plays well with the ``layout``, as it still makes sense to define a relative local layout, while the ``--output-folder`` allows to relocate the whole base folder where the build files (and Conan generated files, etc) are located.

**Comment by lo1ol** [comment]
Thanks! It works. But along side with it, conan also generates some unnecessary files at this folder. Such as conanrun.sh, conanbuild.sh and so on. How can I avoid this?

**Comment by memsharded** [comment]
> Thanks! It works. 

Great

> But along side with it, conan also generates some unnecessary files at this folder. Such as conanrun.sh, conanbuild.sh and so on. How can I avoid this?

Well they are not that unnecessary. The thing is that they contain information about env-vars that can be defined by profiles or by dependencies. Those files are created by an implicit call of ``VirtualBuildEnv().generate()`` and ``VirtualRunEnv().generate()``, to account for things that can be injected by a profile. For example if your profile defines a ``[tool_requires]`` to the ``cmake/3.25`` package, that basically adds its package_folder to the PATH environment variable, that will be automatically reflected in those generated files, that are also automatically called when the conanfile runs ``self.run(something)`` (translates to ``source virtualbuild.sh && something``).

If you want to avoid the creation, you could skip it instantiating them, but not calling generate:
```python
def generate(self):
     VirtualBuildEnv(self)  # without calling generate()
     VirtualRunEnv(self)  # without calling generate()
```

**Comment by lo1ol** [comment]
But I don't call this generators explicitly. `conan export-pkg` command does it :)

**Comment by memsharded** [comment]
> But I don't call this generators explicitly. conan export-pkg command does it :)

Yes, every command that computes the dependency graph for a "consumer" recipe that might use it, will do this implicitly. For example, if the ``package()`` method relies on some tool that is inside a ``tool_requires`` to execute, it needs to generate the ``conanbuild.sh`` script to put it in the path, so the ``self.run("mypackingtool")`` inside ``package()`` will activate it and work, to "package" the files from the current user folder to the cache. 

In general those files shouldn't be an issue. You can use a ``layout()`` method that just define ``self.folders.generators`` to not pollute the root folder with those files (and also easy gitignore/removal), or add the above ``generate()`` method to inhibit completely the creating of those files.

**Comment by lo1ol** [comment]
But my package method seems to doesn't touch generate method. Furthermore, I tried to  override `generate` method to make it empty, but generated files still appear

Example:
```python
from conan import ConanFile
from conan.tools.files import copy

class GeneralPackage(ConanFile):
    settings = "os", "arch"

    def layout(self):
        self.folders.generators = "conan_generators"

    def generate(self):
        pass

    def package(self):
        copy(self, "*", self.build_folder, self.package_folder)
```


```console
$ conan export-pkg --name pkg --version 0.0.1 .
======== Exporting recipe to the cache ========
pkg/0.0.1: Exporting package recipe: /home/lo1ol/Documents/work/conan-cprocsp/conanfile.py
pkg/0.0.1: Copied 1 '.py' file: conanfile.py
pkg/0.0.1: Exported to cache folder: /home/lo1ol/.conan2/p/pkgbc7eae41a48b6/e
pkg/0.0.1: Exported: pkg/0.0.1#06a7d9e9771514ae2700b017524d4a33 (2023-03-01 06:50:35 UTC)

======== Computing dependency graph ========
Graph root
    conanfile.py (pkg/0.0.1): /home/lo1ol/Documents/work/conan-cprocsp/conanfile.py

======== Computing necessary packages ========

======== Installing packages ========
conanfile.py (pkg/0.0.1): Calling generate()
conanfile.py (pkg/0.0.1): Generators folder: /home/lo1ol/Documents/work/conan-cprocsp/conan_generators
conanfile.py (pkg/0.0.1): Generating aggregated env files
conanfile.py (pkg/0.0.1): Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']

======== Exporting recipe and package to the cache ========
conanfile.py (pkg/0.0.1): Exporting binary from user folder to Conan cache
conanfile.py (pkg/0.0.1): Packaging to 63fead0844576fc02943e16909f08fcdddd6f44b
conanfile.py (pkg/0.0.1): Generating the package
conanfile.py (pkg/0.0.1): Temporary package folder /home/lo1ol/.conan2/p/t/pkg7896cd27315d6/p
conanfile.py (pkg/0.0.1): Calling package()
conanfile.py (pkg/0.0.1): package(): Packaged 43 '.sh' files
conanfile.py (pkg/0.0.1): package(): Packaged 1 '.py' file: conanfile.py
conanfile.py (pkg/0.0.1): package(): Packaged 7 files
conanfile.py (pkg/0.0.1): package(): Packaged 12 '.5' files
conanfile.py (pkg/0.0.1): package(): Packaged 12 '.so' files
conanfile.py (pkg/0.0.1): package(): Packaged 12 '.4' files
conanfile.py (pkg/0.0.1): package(): Packaged 272 '.h' files
conanfile.py (pkg/0.0.1): package(): Packaged 5 '.inl' files
conanfile.py (pkg/0.0.1): package(): Packaged 6 '.bat' files
conanfile.py (pkg/0.0.1): package(): Packaged 6 '.dylib' files
conanfile.py (pkg/0.0.1): Created package revision 123316288193f43f048995361b4bcb28
conanfile.py (pkg/0.0.1): Package '63fead0844576fc02943e16909f08fcdddd6f44b' created
conanfile.py (pkg/0.0.1): Full package reference: pkg/0.0.1#06a7d9e9771514ae2700b017524d4a33:63fead0844576fc02943e16909f08fcdddd6f44b#123316288193f43f048995361b4bcb28
conanfile.py (pkg/0.0.1): Package folder /home/lo1ol/.conan2/p/pkgeda3e97d03b03/p
conanfile.py (pkg/0.0.1): Exported package binary
$ ls conan_generators/
conanbuild.sh  conanbuildenv-x86_64.sh  conanrun.sh  conanrunenv-x86_64.sh  deactivate_conanbuild.sh  deactivate_conanrun.sh
```

**Comment by memsharded** [comment]
Yes, sorry I was not very clear about that:

- Defining the ``generators`` folder, will make the files be generated in that folder, not avoid them. It is easier to gitignore or remove the folder if they don't clutter your cwd
- If you want to completely avoid creating them, add the above ``generate()`` method to your ``conanfile.py``, instancing ``VirtualBuildEnv(self)`` and ``VirtualRunEnv(self)`` and the files will not be generated. But the instance is needed, it is what tells conan: "do not automatically instance that, I am doing it myself"

**Comment by lo1ol** [comment]
Thank you. It works!
