### ISSUE TITLE
[question] How to handle compiler variants with independent versions?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#13268]
### What is your question?

Hi,
we need to add a custom compiler to our settings file. For different target architectures there are dedicated compiler variants available from the vendorr. Normally we would just create an entry for the compiler and use the arch setting for choosing the right compiler variant.

But this compiler is special in a way that e.g. 1.2 and 2.1 are only available for arm architecture whereas the available compiler versions for the x86 architecture are only 1.0 , 2.2 and 3.1.

How should we deal with such a compiler?

We have identified at least two approaches:

1. Create for every compiler variant a dedicated settings entry where we list all the available versions
2. Create just one entry for the compiler and all its variants. 
    -  Add the superset of all compiler versions into the list.
    - Implement some mechanism that knows which version of the compiler can be used for which arch variant

Can you already recommend one of them or even have a different and better recommendation?

Thank you
  

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

Thanks for your question, it is an interesting one.
We already had to face this decision ourselves in different places in our default settings:
- There was a global ``cppstd``, but finally we decided that every compiler would have its own ``compiler.cppstd``, with potentially different values
- Not all compilers support all architectures, but it was too tedious to define the architecture for every compiler, so we have an aggregated single list with all configurations

I think in your case it probably sounds a bit simpler the second approach:

- Start with a common lists of versions for all variants, no matter if not supported
- The input profiles have the responsibility to not request an impossible configuration, but that should be easy.
- If later you want to go step beyond, in Conan 2.0 there is a "profile plugin" https://docs.conan.io/2/reference/extensions/profile_plugin.html that you can perfectly use to raise an error if someone request the wrong version for the wrong platform.

**Comment by memsharded** [comment]
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.
