### ISSUE TITLE
[question]No tpch folder contains after packaging duckDB

### ISSUE THREAD

**Issue by 97Simei** [conan-io/conan#13271]
### What is your question?

Hi

I am currently working on cross-compiling duckdb from mac to Android.

I managed to cross-compile using the [conanfile](https://github.com/conan-io/conan-center-index/blob/7075441a1fc168d14d15608da79119a797460353/recipes/duckdb/all/conanfile.py) in the conan-center-index repostery.

The build folder creates/compile the tpch extension correctly, which means  I can find the tpch folder inside the Build folder as below:
![Screenshot 2023-02-28 at 13 29 25](https://user-images.githubusercontent.com/86485345/221854500-a3995849-893a-4f89-ba1d-048878eddf3f.png)

However, when it comes to the package folder. Though I can find the file "libtpch_extension.a"
![Screenshot 2023-02-28 at 13 28 27](https://user-images.githubusercontent.com/86485345/221854315-7b0ab52d-6852-477d-944d-86a357bbab47.png)

There is no tpch header files. 

It should be flexible by modifying the following code, but I am not really clear how should I change it to also include the extension header into the "include/duckdb" or "include" directory
``` 
def package(self):
        copy(self, pattern="LICENSE", dst=os.path.join(self.package_folder, "licenses"), src=self.source_folder)
        cmake = CMake(self)
        cmake.install()
        if self.options.shared:
            rm(self, "*.a", os.path.join(self.package_folder, "lib"))
            rm(self, "duckdb_*.lib", os.path.join(self.package_folder, "lib"))

        rmdir(self, os.path.join(self.package_folder, "lib", "cmake"))
        rmdir(self, os.path.join(self.package_folder, "cmake"))```



### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @97Simei 

Thanks for your question.
It is not fully clear what is missing in the ``package_folder``. You said that the .a files are in the ``lib`` folder, but you are missing the headers. 
They should be in the ``include`` directory, can you please share what is inside that folder?

**Comment by 97Simei** [comment]
![Screenshot 2023-02-28 at 14 30 14](https://user-images.githubusercontent.com/86485345/221868418-ebde5ff8-f636-465e-88b9-0379ec18df89.png)
Yes, it should have the header in the `include` directory, but I don't think it has, and that's also what I want to find.

**Comment by 97Simei** [comment]
@memsharded 
![Screenshot 2023-02-28 at 14 32 43](https://user-images.githubusercontent.com/86485345/221869038-b4a71738-64ed-4c45-9dc3-ea506a0720be.png)
And if you look at the `src` directory in the source code, the `extension` directory is not under(not the subfolder) the `src`, could that be the reason why the extensions' header is not included in the `package`?

**Comment by memsharded** [comment]
I see.
This doesn't seem a Conan issue, but that the ``duckdb`` CMakeLists.txt script ``install()`` instructions are not installing the extensions headers. It seems that it doesn't want to make them explicitly transitively available, see: https://duckdb.org/docs/extensions/overview.html, so the Conan recipe might be aligned with that. If those headers are strictly necessary for consumers, then it should be fixed in ConanCenter, please let me know to transfer the ticket to that repo if that is the case.

**Comment by 97Simei** [comment]
Thank you for your explanation.

I am still at the basic level of using Conan and Duckdb, please correct me if I am wrong.

Yes, it seems like the duckDB allows users to download extensions by the [link](https://duckdb.org/docs/extensions/overview.html,) you just mentioned above. And the extension is also built-in after packaging(by setting the option in conanfile). 

As the result, I shouldn't use the `tpch header`  and try to use their built-in functions instead.

**Comment by memsharded** [comment]
> As the result, I shouldn't use the tpch header and try to use their built-in functions instead.

yes, exactly, it seems the functionality of those extensions is not intended to be accessed by header files, but instead at the binary level, kind of a plugin system or something. It would be good to ask them in their repo just in case.

I think we can close this issue, as it doesn't seem a Conan issue and it seems the ConanCenter recipe would be correct. If there is some different use case, I think the first thing would be to open a ticket in the ``conan-center-index`` repo to report about it. Thanks!

**Comment by 97Simei** [comment]
Sure, I will close the question!
