### ISSUE TITLE
[question] How to query/filter packages by timestamp

### ISSUE THREAD

**Issue by gabeblack** [conan-io/conan#13279]
### What is your question?

I have a project that pulls in many, many packages. Each package has it's own version and they aren't related to each other. However many packages get updated periodically and then up their versions. 

As a consumer of all these packages, I don't just want to get the latest all the time, or my builds won't be reproducible. I want to be deliberate about when I update the dependencies I pull in and pull in the updates on some regular cadence according to testing availability, etc.

We are trying to transition to using conan, but are struggling to figure out how to easily and deliberately update all our dependencies together. With our old mechanism, we would simply update a "timestamp", and we would pull in the latest version of packages that are before that timestamp.

Is there a similar way to accomplish this in conan? For example, if a new version of openssl is updated on Feb 25, 2023 and the version number is also updated, is there a way I can perform some sort of query and get the latest version of all packages in my conan repo that were updated on or before Feb 25, 2023 and thus not just pull in openssl, but also all other packages in the repo that are updated? Would that be an artifactory function maybe?

Thanks in advance for any ideas on how to perform such a query or accomplish what I'm trying to do.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gabeblack 

Thanks for your question.
Could you please clarify a bit about: 
> For example, if a new version of openssl is updated on Feb 25, 2023 and the version number is also updated,

If there is a new version of openssl, you can list versions and revisions with timestamp with (Conan 2.0 syntax):
```
$ conan list openssl/* -r=conancenter
conancenter
  openssl
    openssl/1.0.2s
    openssl/1.0.2t
    openssl/1.0.2u
    openssl/1.1.0k
...
$ conan list openssl/*#latest -r=conancenter
conancenter
  openssl
    openssl/1.0.2s
      revisions
        afe9b3878d1599a90b2e5e13aae6006f (2022-06-29 16:09:43 UTC)
    openssl/1.0.2t
      revisions
        df572b8bb51a79f91c5bfdfab444bbcc (2022-06-29 16:09:42 UTC)
    openssl/1.0.2u
      revisions
        585d7807fb6a08009323a474ab88d354 (2023-02-09 18:55:14 UTC)
...
$ conan list openssl/1.0.2s#* -r=conancenter
conancenter
  openssl
    openssl/1.0.2s
      revisions
        28d27c716262b96a6c6ce17536958428 (2019-10-14 13:24:41 UTC)
        1dfe459b3f7ec9c52d6daf84a5f6e017 (2019-10-22 10:46:28 UTC)
        e51b49809a9fca24fc521d5e91640dde (2019-10-24 10:51:54 UTC)
        365251d3426e4628c33a2afec755a2b3 (2019-10-25 08:57:06 UTC)
        a057e8a283cfa7d706402399a5aac6c8 (2019-10-29 16:44:08 UTC)
        c2e0ca9812aaab8a9e4581e5e48f4fb9 (2019-11-04 11:52:00 UTC)
...
```
All of those commands have a ``--format=json`` that will return an easy to parse json.

In Conan 2.0 you also have a new framework to create custom commands. If you have very specific requirements about timestamps of dependencies, you might be able to create a command that computes a dependency graph, then query each package for timestamps.

Then, there is also the ``conan install --update`` that basically fetches the latest revision or the latest version in the defined version range and update to it. This is typically the recommended way, if there is a new version, and that version is valid in the defined version ranges, a ``--update`` will automatically manage everything. You are able to get the information of revisions timestamps for every package in the graph, but the ``--update`` will not work on time constraints, but on version constraints.

Then, there is also the concept of lockfiles, that can guarantee an exact version and exact revision for dependencies, even if there are other more modern ones, to achieve full reproducibility of the dependency graph, check https://docs.conan.io/2/tutorial/versioning.html

Please let me know if this helps.

**Comment by gabeblack** [comment]
I'm not sure the query will work too well as I'd have to iterate through each package and make an individual query, which can be a bit slow. However, I think I can work with the lockfiles; it would definitely allow for reproducibility of our builds and their  dependencies.

Thank you for the prompt reply and information. That definitely helps!
