### ISSUE TITLE
[bug] Error in generator 'PremakeDeps': '_Component' object has no attribute 'aggregate_components'

### ISSUE THREAD

**Issue by Ohjurot** [conan-io/conan#13275]
### Environment details

* Operating System+version: Windows 11 (10.0.22621 Build 22621)
* Compiler+version: MSVC 193
* Conan version: 2.0.0
* Python version: 3.11.0

### Steps to reproduce

1. Create an empty/default conan file (Tried both .txt and .py --> same result).
2. Set / Add the generator `PremakeDeps`.
3. Add one (or multiple) "requires" (I used `nlohmann_json/3.11.2` for the example log).
4. Run conan install. I used `conan install . --build missing --output-folder=./Vendor --deploy=full_deploy --settings=build_type=Debug/Release`.
5. conan will fail.
6. No Lua file is generate!

### Logs

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.py: ...\conanfile.py
Requirements
    nlohmann_json/3.11.2#a35423bb6e1eb8f931423557e282c7ed - Cache

======== Computing necessary packages ========
Requirements
    nlohmann_json/3.11.2#a35423bb6e1eb8f931423557e282c7ed:da39a3ee5e6b4b0d3255bfef95601890afd80709#2d1a5b1f5d673e1dab536bed20ce000b - Cache

======== Installing packages ========
nlohmann_json/3.11.2: Already installed!

======== Finalizing install (deploy, generators) ========
conanfile.py: Conan built-in full deployer to ...\Vendor
conanfile.py: Writing generators to ...\Vendor
conanfile.py: Generator 'PremakeDeps' calling 'generate()'
conanfile.py: ERROR: Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\conans\client\generators\__init__.py", line 70, in write_generators
    generator.generate()
  File "C:\Program Files\Python311\Lib\site-packages\conan\tools\premake\premakedeps.py", line 47, in generate
    generator_files = self.content
                      ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\conan\tools\premake\premakedeps.py", line 82, in content
    deps = _PremakeTemplate(self._get_cpp_info())
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\conan\tools\premake\premakedeps.py", line 57, in _get_cpp_info
    dep_cppinfo.aggregate_components()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\conans\model\build_info.py", line 362, in __getattr__
    return getattr(self.components[None], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_Component' object has no attribute 'aggregate_components'

ERROR: Error in generator 'PremakeDeps': '_Component' object has no attribute 'aggregate_components'
```

**Comment by Ohjurot** [comment]
I think I see the issue in the source code. I'm also seeing that `PremakeDeps` still does not support multi build. If thats ok for you guys, I can try fixing both issues while still maintaining compatibility with existing premake implementations.

The changes would be realy simple. The problem ist that line:
https://github.com/conan-io/conan/blob/efff966a9dd35e2aca8411cddb6c316ad05a2690/conan/tools/premake/premakedeps.py#L57-L58
that should be:
```py
ret.merge(dep_cppinfo.aggregated_components())
```

The other changes are also quit simple and just involve adding something like
```py
build_type = str(self._conanfile.settings.build_type).lower()
```
to the `content()` function and reference the variable from the templates/format strings.

**Comment by memsharded** [comment]
Hi @Ohjurot 

Thanks for your report.
Definitely, failures are expected in ``Premake`` integration in 2.0. As you can see in the docs https://docs.conan.io/2/reference/tools.html, this integration is not even documented, even if something exists in code, is definitely not even "experimental" status.

We could definitely use some expertise to move this forward succesfully, so thanks very much for the offer. If you want to contribute, I'd suggest the following:
- Having a look to the other integrations the ``MSBuild`` might be a good one (not as complex as the ``CMake`` one, but quite complete)
- Try to do it in small steps. We are quite busy with the 2.0, so iterating in small steps will be easier. 
- It is not necessary to address the full feature parity with others, for example, it might not be necessary to implement "components" for it. Or it is possible to start only with ``PremakeDeps``, but not address ``PremakeToolchain`` or ``Premake`` till later
- Do not add too many functional tests, those are very slow. Try to do a reasonable coverage with integration tests, and just one or two functional ones. Ask for help or guidance if you need it.

It is completely fine to break if necessary, as it is not even documented, so feel free to fix things or improve it if it makes sense, even if it would be breaking.

**Comment by Ohjurot** [comment]
@memsharded Thank you for your information! I have created a PR (#13350). The code is already finished but might change again. I still need to fork "docs" and write the documentation (I hope I can do it tomorrow). Maybe you can already provide me some feedback on the code that I have written. This is my first PR to conan (and actually my first contribution to a python open-source project), so I would be happy to receive some feedback.
