### ISSUE TITLE
Syntax for conanfile.txt

### ISSUE THREAD

**Issue by tim-lebedkov** [conan-io/conan#1328]
What is the exact syntax for conanfile.txt? How can I write a comment?

**Comment by memsharded** [comment]
You can find its reference here: http://docs.conan.io/en/latest/reference/conanfile_txt.html
There are comments in the examples, with #
Anything you find missing or we can improve? Actually if there is something, please open issue better on https://github.com/conan-io/docs repo. Thank you!

**Comment by daravi** [comment]
Follow up question. What format is it based on?  
I want to know to be able to enable proper syntax highlighting for my editor (.vscode). I know it is not `.INI` since there are not always `key=value` pairs. Sometimes `key=value` and sometimes just `value`.

**Comment by memsharded** [comment]
Hi @daravi,

Yes, it is not INI, it is a custom configuration file, that evolved at the very beginning, adding functionality as needed with custom syntax. I'd use INI highlighter, might be the closer one.

In any case, conanfile.txt are really simple (besides the imports section), so if you feel you need syntax highlighting for your conanfile.txt files, you might better use a ``conanfile.py`` (it can be for consuming only, not necessary to implement the package creation methods), and that will use python style and highlighting.

**Comment by uilianries** [comment]
I know this place is not right one for a new discussion, but ...

Why not adopt some standard format? I think [TOML](https://github.com/toml-lang/toml) could be good candidate in this case. It looks like .INI but with steroids. For example, Gitlab uses TOML as official format for configuration files. 
Also there are good python parsers, so we won't need to think about how to parse or maintain our config files. 

Sorry for the noise.

**Comment by memsharded** [comment]
Yes, it seems it would make sense to use something standard like TOML, but:
- That would break massively to users, can't be done until 2.0
- In any case, the conanfile.txt is so simple and stable, it hasn't been a real issue since the beginning.

**Comment by uilianries** [comment]
Yes, I agree conanfile.txt format is really simple and good enough for our case. But I think we should consider it for Conan 2.0 anyway. Thanks for commenting.
