### ISSUE TITLE
Errors trying to execute Conan on Azure VM

### ISSUE THREAD

**Issue by escaperadius** [conan-io/conan#13291]
### What is your question?

Hello,
On a Windows 11 laptop (x64-based), I’ve successfully installed Conan version 1.58.0 and cmake version 3.26.0-rc1, allowing me to compile and verify the Conan example that computes MD5 checksum using the Poco library.

However, when I try to replicate this process on an Azure VM (Linux: ubuntu 20.04), the following error occurs:

ERROR: Invalid generator 'cmake'. Available types: CMakeToolchain, CMakeDeps, MesonToolchain, MSBuildDeps, MSBuildToolchain, NMakeToolchain, NMakeDeps, VCVars, QbsProfile, VirtualRunEnv, VirtualBuildEnv, AutotoolsDeps, AutotoolsToolchain, PkgConfigDeps, BazelDeps, BazelToolchain, IntelCC, XcodeDeps, XcodeToolchain, PremakeDeps

Installed on Azure VM (Linux: ubuntu 20.04):

1. Conan version 2.0.0
2. cmake version 3.16.3

Source:
https://github.com/escaperadius/md5-test.git

Please advise what should be done to rectify this error.
Regards,
Chris

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @escaperadius 

Thanks for your question.
It seems that you installed in your computer the 1.58 version before Conan 2.0 was released last Wednesday, and then you did the test in Azure, and major Conan 2.0 version was used.

If you are just starting with Conan, I'd recommend to go directly for Conan 2.0, the tutorial in https://docs.conan.io/2/tutorial.html should be quite complete.

**Comment by escaperadius** [comment]
Yes I had started with v1.58 but by the time I got to Azure, 2.0 had been released. It appears there were substantial differences in the commands issued and that was indeed confusing for a first time learner. Thankfully the examples provided in the 2.0 docs enabled me to compile and run the "compressor app".

That said, could you provide some additional information regarding these observations:

1. **generators** - in version 1.58  cmake was used as the build system reference. In 2.0 CMakeDeps & CMakeToolchain are the preferred references. Should I decide to use other generators, where would I find documentation regarding there usage within conanfile.txt?
2. **Poco Library** - In my initial attempts to learn Conan (using 1.58), I was using the sample code that computes the md5 checksum. CMakeLists.txt for Conan 2.0 seems to have noticeable differences as well. For example 
```
find_package(ZLIB REQUIRED)
&
target_link_libraries(${PROJECT_NAME} ZLIB::ZLIB)
```
Are used to identify the ZLIB library. If I wish to use the Poco library, how would I code this reference? Where would I find docs to find the syntax to use poco (i.e., find_package(POCO REQUIRED)).?

Thanks,
Chris

**Comment by memsharded** [comment]
> generators - in version 1.58 cmake was used as the build system reference. In 2.0 CMakeDeps & CMakeToolchain are the preferred references. Should I decide to use other generators, where would I find documentation regarding there usage within conanfile.txt?

the new generators are not exclusive of 2.0, they have also existed in 1.X for a long time, you can find the docs in: https://docs.conan.io/1/reference/conanfile/tools.html (though in any case if you are starting, it is recommended to go directly for 2.0)

It is recommend to use the new 2.0 tutorial to learn about those things, like in https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html you can see how the ``[generators]`` section declares ``CMakeDeps`` and ``CMakeToolchain`` and how they are used later. Also there are sections in those docs that explain how to use the new CMakePresets, that can be very convenient

> Poco Library - In my initial attempts to learn Conan (using 1.58), I was using the sample code that computes the md5 checksum. CMakeLists.txt for Conan 2.0 seems to have noticeable differences as well. For example

This is a good question. The target names of packages from ConanCenter have been defining the names that matches the "upstream", that is, the original library target names, or the target names that could be found in CMake built-in find modules, etc. (like the one that would be in the original Poco docs if any). By default it will be the same as the package name. The target names should be typically displayed in the CMake output when you are building and ``find_package()`` creates the target. The name to use in ``find_package()`` is a bit more difficult to know, but if you go to the "generators" folder, Conan had created there the ``xxxx-config.cmake`` files, so it is a matter of checking the ``xxxx`` part.

**Comment by escaperadius** [comment]
Hi @memsharded 
Following the success of building and running the simple "compressor app" and with your recommendations, I tried to refactor the MD5 checksum example to build under Conan 2.0 conditions. Using https://github.com/escaperadius/md5-test the build process threw the following errors:

> *********************************************************
> Recipe 'libmysqlclient/8.0.31' cannot build its binary
> It is possible that this recipe is not Conan 2.0 ready
> If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
> If it is your recipe, check it is updated to 2.0
> *********************************************************
> 
> ERROR: libmysqlclient/8.0.31: Error in build() method, line 229
>         cmake.build()
>         ConanException: Error 2 while executing

I checked the ConanCenter reference and found "compiler.cppstd setting on all platforms:" which might be related to this build output, but I'm unsure how to intrepret:

> error: ‘string_view’ in namespace ‘std’ does not name a type
>    57 | static inline std::string_view to_string_view(LEX_STRING str) {

Any recommendations?

**Comment by memsharded** [comment]
I think it would be worth it to report a detailed case for the failing recipe in the ``conan-center-index`` repo, but isolating the dependency. Something like ``conan install --requires=libmysqlclient/8.0.31 --build=missing`` should be enough to reproduce, and providing there the full output (as it contains important information about the profile, etc)

**Comment by escaperadius** [comment]
Being new to the Conan party, not sure if I've captured everything: 
https://github.com/conan-io/conan-center-index/issues/16366

**Comment by memsharded** [comment]
Reported there a couple of suggestions to improve the report.
As it is reported there as a recipe issue, I think we can closed this (as not a Conan client issue) and follow in ``conan-center-index`` repo. Thanks!
