### ISSUE TITLE
Why it report "The remote doesn't support revisions." when running conan install after I add a nexus conan proxy repository as a remote?

### ISSUE THREAD

**Issue by tedyage** [conan-io/conan#13294]
### What is your question?

  I can successfully consume the packages when I use the conan-center remote.
  I need to use nexus as an conan repository. So I tried to install nexus3 and add a conan proxy as a conan server. After I add a new conan remote and run command `conan install . --output-folder=build --build=missing`，it can't resolve the package in conanfile.txt and report the error `ERROR: Package 'zlib/1.2.11' not resolved: The remote doesn't support revisions. Conan 2.0 is no longer compatible with remotes that don't accept revisions.. [Remote: conan-proxy]`
  Could anybody explain why is that happened and tell me how to solve this problem?
  Here is the output when I run the conan install command.
![image](https://user-images.githubusercontent.com/32167109/222354921-fd2271b4-15d2-4bd5-a741-7d16825a8c18.png)

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tedyage 

Thanks for your question.

This is a problem of the nexus server that you are using, that it is not implementing revisions. Revisions have been out there for several years now in Conan 1.X, and Conan 2.0 is now always using revisions, so the server must support revisions. I suggest reporting it to the nexus server repositories. In the meantime, you might also use the open source conan_server or the free ArtifactoryCE in our https://conan.io/downloads page.

**Comment by tedyage** [comment]
Hi @memsharded 

Thanks for you answer.

Your explanation was quite clear. I have to report an issue to the nexus repository because my guest decided to use nexus to manage the whole of dependencies.

**Comment by memsharded** [comment]
Good, I am closing this ticket as resolved then, thanks!

**Comment by reussssya** [comment]
I have same error with
ERROR: The remote doesn't support revisions. Conan 2.0 is no longer compatible with remotes that don't accept revisions.. [Remote: qt]

using spdlog

**Comment by memsharded** [comment]
@reussssya yes, revisions date back from 2018, and they have been recommended for many years now, nobody should be using even Conan 1.X without revisions anymore.

**Comment by reussssya** [comment]
> @reussssya yes, revisions date back from 2018, and they have been recommended for many years now, nobody should be using even Conan 1.X without revisions anymore.

but Im using conan 2

**Comment by memsharded** [comment]
@reussssya then it is something in your server. Both ArtifactoryCE (completely free) and open-source conan_server support revisions since many years ago. If you use a different server and it doesn't support revision, you might want to file a ticket in their issue tracker. Otherwise, I'd recommend using ArtifactoryCE, it is free and well tested for Conan, including Conan 2.

**Comment by reussssya** [comment]
> @reussssya then it is something in your server. Both ArtifactoryCE (completely free) and open-source conan_server support revisions since many years ago. If you use a different server and it doesn't support revision, you might want to file a ticket in their issue tracker. Otherwise, I'd recommend using ArtifactoryCE, it is free and well tested for Conan, including Conan 2.

where i can find how to use ArtifactoryCE with conan? should I delete the old "pip conan"?

**Comment by memsharded** [comment]
``pip conan`` is the client, no need to remove it. It is the server: 
- https://docs.conan.io/2/tutorial/conan_repositories.html
- https://docs.conan.io/2/tutorial/conan_repositories/setting_up_conan_remotes.html
- https://conan.io/downloads

**Comment by reussssya** [comment]
> `pip conan` is the client, no need to remove it. It is the server:
> 
> * https://docs.conan.io/2/tutorial/conan_repositories.html
> * https://docs.conan.io/2/tutorial/conan_repositories/setting_up_conan_remotes.html
> * https://conan.io/downloads

thanks!
Im using CMake in my project so how i have to attach library that ive added by "conan upload lib -r=artifactory"?

still getting error when trying to "conan install . --output-folder=build --build=missing"

trying to install libmysqlclient/8.1.0 , on other project works ok. on this project (with qt installed locally without conan) im getting error:

ERROR: The remote doesn't support revisions. Conan 2.0 is no longer compatible with remotes that don't accept revisions.. [Remote: qt]

**Comment by memsharded** [comment]
The tutorial how to use packages is already using CMake as build system: https://docs.conan.io/2/tutorial/consuming_packages.html

> ERROR: The remote doesn't support revisions. Conan 2.0 is no longer compatible with remotes that don't accept revisions.. [Remote: qt]

this will keep happening if you keep using that remote that doesn't support revisions. You need to remove that remote with ``conan remote remove``. Or maybe just clean completely your Conan cache (remove the ``<userhome>/.conan2`` folder) and start over clean.

**Comment by reussssya** [comment]
removing .conan2 helped me, thanks a lot man!
