### ISSUE TITLE
migrated conan2 package doesn't appear conan 2 ready when used

### ISSUE THREAD

**Issue by igagis** [conan-io/conan#13300]
### What is your question?

I'm migrating my packages to conan 2 and now I have problem trying to use migrated conan2 package.

The package I have migrated is called `utki` and is published to my self-hosted conan repo. Here is the log from deploying the package:
https://github.com/cppfw/utki/actions/runs/4314409903/jobs/7527399805#step:12:34
```
Uploading package 'utki/1.1.192@cppfw/main#6e1206af8eff8bcd67ca7749758c8ce5:c02f97045ac96d3afb248507181d5e11c72951c9#b67845970c9de80e2f2239408aa9f6b1'
```

And now I'm trying to use it from another library package, called `opros`, which I'm also migrating to conan 2. And here is the build log with the error:
https://github.com/cppfw/opros/actions/runs/4314607221/jobs/7527862245#step:10:95

As one can see, it downloads the dependency `utki` package which is now supposed to be migrated to conan2, and says that it is not conan 2 ready:
```
Resolved version ranges
    utki/[>=1.1.192]@cppfw/main: utki/f39daeaf684dac882f90bb8bde0efcaa7452934f@cppfw/main
*********************************************************
Recipe 'utki/f39daeaf684dac882f90bb8bde0efcaa7452934f@cppfw/main' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check it is updated to 2.0
*********************************************************
```
Looking at these hashes it seems like it downloads some other version of the package?
What did I do wrong?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @igagis 

Thanks for your report.
There is something very weird there:

- The package you uploaded is ``utki/1.1.192@cppfw/main``
- The package that is being resolved is ``utki/f39daeaf684dac882f90bb8bde0efcaa7452934f@cppfw/main``

It seems that you have uploaded at some point it time a version called ``f39daeaf684dac882f90bb8bde0efcaa7452934f``. Did you do that? That would not be compatible with semver, and as you are not putting a ``[.... <2]`` upper limit, it is resolving to ``f39...`` because it is greater than 1.
If you didn't upload such a ``f39daeaf684dac882f90bb8bde0efcaa7452934f`` version in the past to the server, it could be a server corruption. Can you please do a ``conan list utki/* -r=myremote`` to list your versions?  Which server are you using?

**Comment by igagis** [comment]
yes, perhaps I did add this version long time ago. But I don't need these non-symver ones in the repo, how can I remove those from the repo?
```console
ivan@gagis:~$ conan list utki/* --remote cppfw
cppfw
  utki
    utki/1.1.151@cppfw/main
    utki/1.1.152@cppfw/main
    utki/1.1.153@cppfw/main
    utki/1.1.154@cppfw/main
    utki/1.1.155@cppfw/main
    utki/1.1.156@cppfw/main
    utki/1.1.157@cppfw/main
    utki/1.1.158@cppfw/main
    utki/1.1.159@cppfw/main
    utki/1.1.160@cppfw/main
    utki/1.1.161@cppfw/main
    utki/1.1.162@cppfw/main
    utki/1.1.163@cppfw/main
    utki/1.1.164@cppfw/main
    utki/1.1.165@cppfw/main
    utki/1.1.166@cppfw/main
    utki/1.1.167@cppfw/main
    utki/1.1.168@cppfw/main
    utki/1.1.169@cppfw/main
    utki/1.1.170@cppfw/main
    utki/1.1.171@cppfw/main
    utki/1.1.172@cppfw/main
    utki/1.1.173@cppfw/main
    utki/1.1.174@cppfw/main
    utki/1.1.175@cppfw/main
    utki/1.1.176@cppfw/main
    utki/1.1.177@cppfw/main
    utki/1.1.178@cppfw/main
    utki/1.1.179@cppfw/main
    utki/1.1.180@cppfw/main
    utki/1.1.181@cppfw/main
    utki/1.1.182@cppfw/main
    utki/1.1.183@cppfw/main
    utki/1.1.184@cppfw/main
    utki/1.1.185@cppfw/main
    utki/1.1.186@cppfw/main
    utki/1.1.187@cppfw/main
    utki/1.1.188@cppfw/main
    utki/1.1.189@cppfw/main
    utki/1.1.191@cppfw/main
    utki/1.1.192@cppfw/main
    utki/15d080fd784fc07839daff62804cbeb882521698@cppfw/main
    utki/ae571b16f06e31e0e8fbe5db022b153804eeae27@cppfw/main
    utki/f39daeaf684dac882f90bb8bde0efcaa7452934f@cppfw/main
```

**Comment by memsharded** [comment]
Use the ``conan remove <ref> -r=myrepo`` to remove

**Comment by igagis** [comment]
thanks a lot! I was able to remove those old packages and now it seems to work.
