### ISSUE TITLE
List dependent package options with conan list

### ISSUE THREAD

**Issue by lexknuther** [conan-io/conan#13304]
Currently, conan list only prints options for the target package.  It would be awesome if it also listed the options for its dependencies (even if they are defaults).  Without this information, it's difficult to resolve  missing binaries errors in conan create.

**Comment by memsharded** [comment]
Hi @lexknuther 

To be able to list options of dependencies, it is necessary to evaluate the graph.
For that purpose you have the ``conan graph info`` command, that will give you the dependencies (and their options too). Please have a look to it, thanks!

**Comment by AbrilRBS** [comment]
Closing as solved, feel free to open new issues should you have any other questions, thanks!

**Comment by memsharded** [comment]
Conan 2.0.15 even got the ``conan graph explain`` command to explain missing binaries
