### ISSUE TITLE
[question] How to determine the package folder for a downloaded reference

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#13306]
### What is your question?

Hi!
I welcomed the introduction of [conan cache path](https://github.com/conan-io/conan/pull/11017), but I think it may have a missing feature.
When I download a package via `conan download` it creates the following folders:
```
~.conan2/p/<reference_id_1>/d
~.conan2/p/<reference_id_1>/e
~.conan2/p/<reference_id_1>/es

~.conan2/p/<reference_id_2>/d
~.conan2/p/<reference_id_2>/p
```
If I try to run `conan cache path`, it only allows to query the following directories:
`[--folder {export_source,source,build}] reference`

Now, conan uploaded two archives in my workflow: `conan_sources.tgz` and `conan_package.tgz`. I would like to know the location of the downloaded **package** folder, in our case `~.conan2/p/<reference_id_2>/p`, where all the installed binaries are stored in my case in order to run them.

Is there an official solution for this?

### Have you read the CONTRIBUTING guide?

- [*] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @donlk 

yes, the ``reference`` must be a package reference, including the ``package_id``.
```
conan cache path pkg/version:package_id
```
will give you the package folder.

**Comment by donlk** [comment]
So I can specify a custom, humanly sensible package ID that is not a hash, then?
Maybe by:
```
def package_id(self):
    return "arbitrary_id"
```
Then `conan cache path pkg/version:arbitrary_id` should work, right? Are there any drawbacks to this?

**Comment by memsharded** [comment]
No, it is not possible to do that. The ``package_id`` is the hash of the ``conaninfo.txt`` file, that contains ``settings`` + ``options`` + ``requires`` information (and potentially ``conf``, ``settings_build``, ``settings_target``). While some simplifications and assumptions are possible over the binary compatibility model (like assuming different ``compiler.cppstd`` are binary compatible among them), manually defining a binary ``package_id`` is guaranteed to be very problematic in most cases. Also the influence of the dependencies versions via ``self.info.requires`` is critical for some core functionality of Conan, like the ``--build=missing`` functionality, or in general, knowing when a binary has to be built from sources. Returning an arbitrary package_id completely breaks this.

You can do a ``conan list pkg/version:*`` to list the different binaries with the different ``conaninfo.txt`` values.

**Comment by AbrilRBS** [comment]
Closing as answered, feel free to reopen/create a new issue should you have any other questions, thanks!

(`conan cache path` now also allows to return the paths for a reference if it only has 1 associated package id)
