### ISSUE TITLE
[question] conan2 transitive dependencies include path is not passed to compiler

### ISSUE THREAD

**Issue by igagis** [conan-io/conan#13308]
### What is your question?

Hi, I'm porting my packages to conan2 and have problem that include path for transitive dependencies is not passed to the compiler.

I have one package `utki` supposedly ported to conan2 and deployed to my self-hosted conan repo.
And the other package which I'm porting is `opros` and it depends on `utki`.

The build log can be found here:
https://github.com/cppfw/opros/actions/runs/4315947371/jobs/7531048956#step:10:228

When trying to build `test_package` of `opros` I get this error:
```console
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
/usr/bin/c++  -isystem /github/home/.conan2/p/opros2b86eb4ec3132/p/include -m64 -O3 -DNDEBUG -std=c++17 -o CMakeFiles/example.dir/example.cpp.o -c /__w/opros/opros/conan/test_package/example.cpp
In file included from /__w/opros/opros/conan/test_package/example.cpp:1:
/github/home/.conan2/p/opros2b86eb4ec3132/p/include/opros/wait_set.hpp:37:10: fatal error: utki/config.hpp: No such file or directory
   37 | #include <utki/config.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

as one can see, only `-isystem /github/home/.conan2/p/opros2b86eb4ec3132/p/include` is passed to the compiler, but no include path for `utki` is passed.

On my local system I have `utki` globally installed, so it finds the headers anyway when I'm building `opros` package locally, and then when it links I can see that it passes both `-L` paths to the linker:
```console
[100%] Linking CXX executable example
/usr/bin/cmake -E cmake_link_script CMakeFiles/example.dir/link.txt --verbose=1
/usr/bin/c++ -m64 -O3 -DNDEBUG -m64 CMakeFiles/example.dir/example.cpp.o -o example   -L/home/ivan/.conan2/p/oprosa414816a215ad/p/lib  -L/home/ivan/.conan2/p/utki4fc994b9fabf8/p/lib  -Wl,-rpath,/home/ivan/.conan2/p/oprosa414816a215ad/p/lib:/home/ivan/.conan2/p/utki4fc994b9fabf8/p/lib /home/ivan/.conan2/p/oprosa414816a215ad/p/lib/libopros.so /home/ivan/.conan2/p/utki4fc994b9fabf8/p/lib/libutki.so
``` 

So, it looks like the problem is only with include path. Library path seems to work OK.

What might I be doing wrong?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by igagis** [comment]
conan files of `opros` from this build can be found here:
https://github.com/cppfw/opros/tree/b047251ea98ce3844f73b47c56a1a11debd11d8c/conan

and `utki`'s conanfile is this one:
https://github.com/cppfw/utki/blob/master/conan/conanfile.py.in

**Comment by memsharded** [comment]
Hi @igagis 

In Conan 2.0 there is more control over what headers are propagated down to the consumers.

If app -> libb -> liba, by default, liba headers are not visible to app. If app uses directly liba headers, it should declare a ``requires`` to liba directly.

If it is a matter that libb public headers include the liba headers, then the include path must be propagated. To indicate this, the ``libb`` conanfile.py should do:
```python
def requirements(self):
     self.requires("liba/1.0", transitive_headers=True)
```

You can watch https://www.youtube.com/watch?v=kKGglzm5ous, and check https://docs.conan.io/2/reference/conanfile/methods/requirements.html for more information

**Comment by igagis** [comment]
thanks a lot! It worked. Though I think it would be good if that was mentioned in conan 2 migration guide https://docs.conan.io/1/conan_v2.html
