### ISSUE TITLE
[question] why cmake build does not work but conan build works

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#13303]
### What is your question?

So i have a project i would like to cross build for android using `clang`, as well as native build for linux using `gcc`. i have two profiles, `default` is for native linux builds, and `android` is for cross builds. 

everything works perfectly when i use `conan install`  and `conan build` as long i specify the right profile to use. but if i use `conan install .. -pr android`, and then use `cmake .. -GNinja && cmake --build .`, i always get error saying
```
CMake Error at build/conanbuildinfo.cmake:5024 (message):
  Incorrect 'clang', is not the one detected by CMake: 'GNU'
Call Stack (most recent call first):
  build/conanbuildinfo.cmake:4581 (conan_check_compiler)
  CMakeLists.txt:13 (conan_basic_setup)
```
This is OK, because i can always use `conan build` if i have a `conanfile.py`, but some projects only comes with `conanfile.txt`, how can i build it with cmake then?
it seems to me the only way is to specify all the stuff in profile `android` by cmake command, but why not conan pass everything to cmake when it runs install? as the profile android already been passed there?
I may asked a dumb question or miss something, maybe the question is how can i use conan + cmake to cross build project that only has `conanfile.txt` with a custom profile.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @shelper 

I suspect that it is missing the environment part.
Inside the ``build()`` method, the ``cmake.build()`` will run internally something like (with VirtualBuildEnv):
```
conanbuild.bat && cmake . -DCMAKE_TOOLCHAIN_FILE=.../conan_toolchain.cmake
```

This is with the new, recommended integrations (CMakeDeps, CMakeToolchain).
It seems (based on ``conanbuildinfo.cmake`` in the output) you are still using the legacy integrations.
It also seems you are still using the legacy 1 profile way of cross building, while the recommended approach is to use the ``--profile:build=default --profile:host=android`` 2 profiles approach.
I'd recommend to start getting familiarized with all those integrations, they are necessary to be 2.0 ready. You can start with the ``conan new pkg/0.1 -m=cmake_lib`` and try to cross-compile it with ``conan create .`` and the 2 profiles (the androidNDK location is defined via a ``[conf]`` called ``tools.android:ndk_path``). Once it work, try to cross compile locally with ``conan install .`` + ``cmake . -DCMAKE_TOOLCHAIN_FILE=.../conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release``

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
