### ISSUE TITLE
Conan incredibly slow on Windows

### ISSUE THREAD

**Issue by dibben-jsol** [conan-io/conan#1331]
Conan seems to be running  very slowly under Windows. 
For example, one application  has 29 library dependencies. We are using Artifactory as a Conan  server.

Running
   conan install -u
when there are no updates to install
 Linux: 13 seconds
 Windows: 55 minutes (!)

The Artifactory server is the  same in both cases and is on the local network. In the Conan config I have set it to not use a proxy server. 

On Linux most of the 13 seconds is spent copying library files in the "imports" section. The check to the server for new versions is virtually instantaneous. 

On Windows, there is a very significant delay between each resolved version message. As though for each call to the server it is waiting for something to time out. 

Running from the local cache only (eg "conan install" when all packages are available) is slower on windows than linux (1m 40s vs 9s) but acceptable. 

Any ideas on what could cause such a delay? 

Conan version 0.22.3
Artifactory 5.1.0
Python 2.7.10

**Comment by memsharded** [comment]
Yes, this is unnaceptable. Not sure what can be causing it. Could you please enable logging and send us the traces?

Check: http://conanio.readthedocs.io/en/latest/mastering/logging.html

Also, what are the times to run without updates? Is that the 1m40s? Still a long time. What are the sizes of the binaries? What happens if not using "imports"?

If they contain sensitive data, please send them privately, by email (info@conan.io), private gist...
Thanks very much for reporting!

**Comment by dibben-jsol** [comment]
Here is the trace with updates.

[trace.txt](https://github.com/conan-io/conan/files/1037265/trace.txt)
I obscured the server IP address but otherwise the log was not changed.

Without updates on Windows it was 1m40s with imports.

Without imports and without updates it too 50s. Here is the trace for that
[trace2.txt](https://github.com/conan-io/conan/files/1037276/trace2.txt)

I have some concern about the virus checker and firewall (we use Symantec) Unfortunately, disabling to test it is not easy due to corporate policies.

**Comment by memsharded** [comment]
Hi @dibben-jsol ,

Having a look at the traces, it seems that there is some weird network issue, might be related to Windows network config, proxies, firewall...

In the logs you can see:
```
{"_action": "REST_API_CALL", "duration": 5.051000118255615
```

To get an idea, similar REST API call to the same "search" endpoint, from my windows machine to conan.io (which search has to process a large index, and is located in AWS in a different country), takes about 1.5 seconds. Other API calls, such as those from installing:

```bash
conan install zmqcpp/4.1.1@memsharded/stable -r=conan.io
```
takes about 0.1 second each.

So I suggest taking the following steps to try to isolate the problem:
- Try the above conan install from conan.io, capture traces, see API calls times.
- Try to directly query your Artifactory instance, from your windows machine, with curl/ping/wget... anything that lets you check the network connection from your machine to Artifactory, without using conan.

**Comment by dibben-jsol** [comment]
Thanks for the suggestions.
Our firewall is making accessing conan.io difficult. I will try again later.

Using curl to access artifactory from the command line
(running from a bash shell on windows)
 
 time curl http://xx.xx.xx.xx/artifactory/libs-snapshot/filesep/1.0.0/builduser/snapshot/package/36efda426f2931c897d6aab086eb719ea3174f82/conan_package.tgz -o conan.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24619  100 24619    0     0   751k      0 --:--:-- --:--:-- --:--:--  751k

real    0m0.394s
user    0m0.000s
sys     0m0.124s

So direct access via curl is fast access and download a file. 

This is definitely a proxy problem. I just turned off our proxy in "internet explorer options" and the 
conan install -u
ran in 9 seconds!

So the problem seems to be that with windows proxy on (in IE settings) conan is still using the proxy even with no proxy section in the conf file. 
So how can we force conan to not use the system proxy? I have tried with no [proxies] section in the conf file and a proxies section with 
http= 
https=

**Comment by memsharded** [comment]
This are good advances!
Have you tried to directly define the proxy values in the conan.conf file?
Also, not defining "http=", "https=", but rather an empty [proxies] section? Might be slightly different.

However, I am a bit confused that IE settings are affected the system and other apps, I though it was strictly for IE navigation. Would it affect Chrome or other browsers? Doesn't make a lot of sense.

**Comment by dibben-jsol** [comment]
I have found a solution.

First about IE:
Windows IE internet options do provide system wide settings. Other browsers do use them. In windows Chrome if you click on the "Change proxy settings..." it opens the system (same as IE) Internet Properties dialog.

I had tried various options in the config file. However, this had no effect. I even added a "print" in command.py get_command to check that the proxies were indeed being set to None. So Conan was correctly not setting any proxy in the call to the requests library when the[proxies] setting was missing.

However, it seems that the requests library uses the system proxies. 
Have a look here, https://github.com/requests/requests/issues/879 for some info on how this library is handling proxies. It seems that if the proxies is empty then it uses the system proxies.

However, requests also respects the no_proxy variable. But, it does not seem to pick up the exceptions from the windows system settings.

So my solution is simply to define a "no_proxy" environment variable contain the IP address of the artifactory server. With this defined, "conan install -u" runs in 10 seconds. 

Thanks for the help

**Comment by memsharded** [comment]
Hi David,

Thanks very much for updating. Happy that you found a solution. 
I would like to add this piece of information to the conan docs, at least, or to implement the possibility to configure it in conan.conf.

From the current conan.conf, I'd say that it should be enough something like:
```text
[proxies]
no_proxy=your_server_ip
```
How did you set the env-var? Could you please try the above? Also, it seems to allow comma separated list of IPs: ``no_proxy=your_server_ip,other_ip``
Thanks very much again for your feedback and help

**Comment by dibben-jsol** [comment]
I just tried setting no_proxy in conan.conf but it did not work. With just this and no environment variable access was slow.

I set the environment variable globally
My Computer -> System Properties -> Advanced -> Environment Variables 

It also worked setting it from the cygwin bash shell that I use to run conan. ie
```
% export no_proxy=my_ip
% conan install -u
```

**Comment by memsharded** [comment]
Thanks for the feedback. Lets try to add something so it can be configured in conan.conf. Planned for next 0.24 release, shouldn't be difficult, but lets see.

**Comment by memsharded** [comment]
Hi @dibben-jsol 

I have a couple of alternative solutions, not sure which would be the most effective, even which one might work in your system. Are you able to run conan from sources? In that case, it would be very useful if you could try running a couple of different branches I have. If not possible, would you mind trying a couple of Win installers I can send you? Thanks!

**Comment by dibben-jsol** [comment]
I should be able to run from sources. I currently install via pip, but running from source should not be a problem. Please tell me what you would like me to try.

**Comment by memsharded** [comment]
OK, so here it is:

**Approach 1**: Running from https://github.com/memsharded/conan/tree/feature/no_proxy

Define in your ``conan.conf``

```
[proxies]
no_proxy=yourartifactory
```

**Approach 2**: Running from https://github.com/memsharded/conan/tree/feature/disable_proxies_none

Define in your ``conan.conf``

```
[proxies]
http=None
https=None
```

I believe the second one might be cleaner in the implementation and more idiomatic. Lets see what happens. Thanks very much for your help, dont hesitate to ask if you need help running from sources.

**Comment by memsharded** [comment]
Hi @dibben-jsol David,

Have you been able to try the above approaches? The release is moving forward and we would like to release a solution for this issue in it. 

Thanks!

**Comment by memsharded** [comment]
Hi again @dibben-jsol 

We are about to close the 0.25 release (this Tuesday 18), so if you would like to see this feature into it, we would like to know if they are working or not for your use case. Could you please have a look and try them? Thanks very much.

**Comment by memsharded** [comment]
Conan 0.25 is to be released, so moving forward this issue to 0.26. The solutions are implemented, looking forward to hearing your feedback to merge them.

**Comment by memsharded** [comment]
The solution of this will be then delayed to 0.27, looking forward the feedback of @dibben-jsol

**Comment by amues** [comment]
Hi @memsharded,

Regarding the two approaches mentioned above, I think the first (_no_proxy_ support) is a more general solution. We currently have a local Conan server running in an internal network, which needs to be accessed without a proxy; at the same time, we would like to have access to _conan-center_, and that needs to go though a proxy. So we need to be able to define _http_proxy_, _https_proxy_ and _no_proxy_ separately for this use case.

**Comment by memsharded** [comment]
Thanks @amues 
Yes, that makes sense: Lets try to merge both proposals!

**Comment by memsharded** [comment]
Now from conan 0.27, you have the ``no_proxy`` option as configuration in conan.conf: http://docs.conan.io/en/latest/reference/config_files/conan.conf.html#proxies
