### ISSUE TITLE
[question] how to isntall conan_server

### ISSUE THREAD

**Issue by igagis** [conan-io/conan#13311]
### What is your question?

After upgrading to conan 2 I found that conan_server is not anymore installed along with conan client. So, how can I install conan_server for conan 2?

Also, question: is conan_server from conan 1.X compatible with conan2 client?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
The ``conan_server`` is now a separate package in https://pypi.org/project/conan-server/

Check:
- https://docs.conan.io/2/tutorial/conan_repositories/setting_up_conan_remotes/conan_server.html#conan-server
- https://docs.conan.io/2/reference/conan_server.html

Note, however, that for production the recommended way would be behind some nginx, or running from sources with ``gunicorn`` or equivalent (we might need to document this)

Conan 1.X server might be usable with Conan2 client yes.

**Comment by igagis** [comment]
Ok, I'll check those links.

> Conan 1.X server might be usable with Conan2 client yes.

Right now, when using conan2 clinet with conan 1.X server I see strange behavior that deploying the same package built on different systems (e.g. linux arm32 and linux x86) will overwrite the previous one. So, only one binary configuration of the package is stored.

**Comment by memsharded** [comment]
> Right now, when using conan2 clinet with conan 1.X server I see strange behavior that deploying the same package built on different systems (e.g. linux arm32 and linux x86) will overwrite the previous one. So, only one binary configuration of the package is stored.

In theory it shouldn't, if the server is used only with the v2 api (all clients with revisions enabled), but it is true that the removal of the v1 api might have affected something. The general recommendation would be to upgrade to 2.0 server too.

**Comment by igagis** [comment]
Ok, I installed conan_server 2  and wiped out the old repo, stared from clean one. I deployed my package `utki` built in 2 different OSes (linux and macos). The linux one was deployed first and the macos one was deployed second.

Now, the server files layout for the package look like this:
```console
repo@gagis:~/conan-server-data$ ls -R data/utki/1.1.192/cppfw/main
data/utki/1.1.192/cppfw/main:
3532e928a7c99c758b2a4d0985f64ec2  958fb4dcd7ca35ee62851836ba435583  revisions.txt  revisions.txt.lock

data/utki/1.1.192/cppfw/main/3532e928a7c99c758b2a4d0985f64ec2:
export  package

data/utki/1.1.192/cppfw/main/3532e928a7c99c758b2a4d0985f64ec2/export:
conan_export.tgz  conan_sources.tgz  conanfile.py  conanmanifest.txt

data/utki/1.1.192/cppfw/main/3532e928a7c99c758b2a4d0985f64ec2/package:
3381de3bce3b26e2939b85d2b8118bf754612317

data/utki/1.1.192/cppfw/main/3532e928a7c99c758b2a4d0985f64ec2/package/3381de3bce3b26e2939b85d2b8118bf754612317:
30f11db468a0e858737418cb8f32877a  revisions.txt  revisions.txt.lock

data/utki/1.1.192/cppfw/main/3532e928a7c99c758b2a4d0985f64ec2/package/3381de3bce3b26e2939b85d2b8118bf754612317/30f11db468a0e858737418cb8f32877a:
conan_package.tgz  conaninfo.txt  conanmanifest.txt

data/utki/1.1.192/cppfw/main/958fb4dcd7ca35ee62851836ba435583:
export  package

data/utki/1.1.192/cppfw/main/958fb4dcd7ca35ee62851836ba435583/export:
conan_export.tgz  conan_sources.tgz  conanfile.py  conanmanifest.txt

data/utki/1.1.192/cppfw/main/958fb4dcd7ca35ee62851836ba435583/package:
c02f97045ac96d3afb248507181d5e11c72951c9

data/utki/1.1.192/cppfw/main/958fb4dcd7ca35ee62851836ba435583/package/c02f97045ac96d3afb248507181d5e11c72951c9:
ae5815ebfe9d6adac4521f0bd4dd793b  revisions.txt  revisions.txt.lock

data/utki/1.1.192/cppfw/main/958fb4dcd7ca35ee62851836ba435583/package/c02f97045ac96d3afb248507181d5e11c72951c9/ae5815ebfe9d6adac4521f0bd4dd793b:
conan_package.tgz  conaninfo.txt  conanmanifest.txt
```

But when I try to build other package `opros` which depends on `utki` it cannot find the package for linux build, but can find for macos build.
Here is the linux build log with error:
https://github.com/cppfw/opros/actions/runs/4322733945/jobs/7547342503#step:10:113
Here is the macos build log:
https://github.com/cppfw/opros/actions/runs/4322733945/jobs/7547342295

From the linux build log it complains that:
```
utki/1.1.192@cppfw/main: WARN: Can't find a 'utki/1.1.192@cppfw/main' package binary 'c02f97045ac96d3afb248507181d5e11c72951c9' for the configuration:
```
but from the file layout above I could find the `c02f97045ac96d3afb248507181d5e11c72951c9` hash used as name fo one of the directories, does that mean that the needed package IS in the repo, but why can't it find it then?

**Comment by memsharded** [comment]
From the contents of the server it seems that:

- There is only 1 package binary for ``data/utki/1.1.192/cppfw/main/3532e928a7c99c758b2a4d0985f64ec2`` recipe revision:
    - /package/3381de3bce3b26e2939b85d2b8118bf754612317 that matches the Macos binary
- The Linux binary is not there under that latest revision
- But what you have is another recipe revision ``data/utki/1.1.192/cppfw/main/958fb4dcd7ca35ee62851836ba435583``. This could be the Linux one, you might check it by inspecting the ``conaninfo.txt``

If that is the case, the most typical scenario is having git with different CRLF in different platforms, so the recipe revisions are not identical. I see that you have a recipe ``conanfile.py`` template that is a .in template, not a regular ``conanfile.py``. Whatever manipulation that you do on the ``conanfile.py`` that doesn't result in exactly the same one will produce a different recipe revision. You need to have the same contents, otherwise it needs new binaries for that new recipe revision, please read: https://docs.conan.io/2/tutorial/versioning/revisions.html

**Comment by igagis** [comment]
Hm... no idea how could this happen. I printed `md5sum` of the processed `conanfile.py` from different builds, and the hash is same `6326f837999fcab40fc833a516477c8e`, here are build logs:
https://github.com/cppfw/utki/actions/runs/4327850937/jobs/7556938891#step:10:21
https://github.com/cppfw/utki/actions/runs/4327850937/jobs/7556939245#step:10:22

So, I assume that line endings are same on both systems and files are actually identical. Any other ideas what could be wrong?

**Comment by memsharded** [comment]
You can see that you are exporting with the recipe many many files.
In one case you get:
```
utki/995c086d23418cf25ce088b771b9f705362ba469@cppfw/main#76fe75d737b60795a033de48ac7860b4 (2023-03-03 22:44:49 UTC)
```
and in the other
```
utki/995c086d23418cf25ce088b771b9f705362ba469@cppfw/main#0f41d3d30c88cb51ca1ed38e89b4dad9 (2023-03-03 22:46:56 UTC)
```
So the revisions are clearly different.
This is because not only the conanfile.py, but all the exported files, become part of the manifest and the recipe revision. No matter if the conanfile.py changes or if the input source changes, it will mean a different revision.

But the source code must be common to all different variants, it is not possible to export different things for different platforms:
- https://docs.conan.io/2/reference/conanfile/methods/source.html
- https://docs.conan.io/2/reference/conanfile/methods/export.html
- https://docs.conan.io/2/reference/conanfile/methods/export_sources.html

**Comment by igagis** [comment]
I see. Well, I export all files of my repository just to be able to build them during `build()` phase. In conan 1 I was using `scm` attribute with `auto` values for that but it was removed in conan 2. Is there another way to achieve this without exporting all the files?

I have no idea at the moment  which file of all those exported ones is causing the problem... perhaps repo files are contaminated with some other files on the CI...

But what I'd like to have at this point is to be able to build the package without cloning the repo second time, since sources are in the same repo where `conanfile.py` is. How can I do this without exporting all the files? I.e. copy all the files to build folder bypassing the export_sources folder?

**Comment by memsharded** [comment]
> I have no idea at the moment which file of all those exported ones is causing the problem... perhaps repo files are contaminated with some other files on the CI...

Yes, I see a lot of different files being exported, that are build-system specific, so it clearly seems that you are doing other things in CI that are polluting the repo with other temporary files, that are being exported. 

The ``scm`` got a new replacement already in 1.X, check: https://docs.conan.io/1/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature

So it is still possible to do it without exporting all the files. But if not exported they will be cloned, as the sources have to be obtained somehow. Please have a look to that new scm approach.

**Comment by igagis** [comment]
> But if not exported they will be cloned

This is exactly what I'm talking about. Previously, using `scm` attribute it was possible to do
```
scm = {"type": "git", "url": "auto", "revision": "auto"}
```

and this way the build was happening with local sources, I didn't have to export anything and clone anything.
But now it looks like the sources have to be cloned the second time.

In `def export_sources(self)` method the `recipe_folder` points to the repo folder, so it is possible to copy sources
```python
		source_folder = os.path.join(self.recipe_folder, "..")
		copy(self, "*", source_folder, self.export_sources_folder)
```
but this is not what I want, since I don't want to export the sources.

In `def source(self)` method the `recipe_folder` already points to some conan temporary folder like `/home/ivan/.conan2/p/utki10a7203018512/e`, so I cannot copy sources from cloned repo anymore. The only way is to clone the repo from git again.

Is there any other variable which holds path to the cloned repo with the conanfile.py accessable from `source()` method?

**Comment by memsharded** [comment]
> and this way the build was happening with local sources, I didn't have to export anything and clone anything.
But now it looks like the sources have to be cloned the second time.

Yes, the previous ``scm`` approach (with attribute) was a disaster in terms of reproducibility, and it had some other serious flaws. Doing a clone is the only way to guarantee reproducibility (besides doing the ``export`` of the files, which is something that is not desired in this case). It might be possible in some cases to optimize things fetching only one commit with the ``fetch_commit()`` function in https://docs.conan.io/2/reference/tools/scm/git.html#conan.tools.scm.git.Git.fetch_commit.

Note that the ``source()`` method also executes when the package is being built as a dependency (with ``--build=missing`` for example), so trying to reference some local user folder that no longer exist ends badly (and it was the origin of some of the above cited flaws). This is the reason the ``source()`` method needs to be abstracted from that concept that it can copy files from a local folder.

**Comment by igagis** [comment]
Ok, I have updated the `utki` conanfile to use git clone, but it still seems to be producing different revisions of the package.
Here is the log from deploying the built packages:
Linux:
https://github.com/cppfw/utki/actions/runs/4341549413/jobs/7581282188#step:11:31
Macos:
https://github.com/cppfw/utki/actions/runs/4341549413/jobs/7581282668#step:11:32

So, now, since we clone sources from repo, the only possible difference is that `conanfile.py` produced from `conanfile.py.in` is different on those two systems, right? This is strange because it was working with conan 1.X and I didn't change anything about `conanfile.py` generation. :(

I think that line endings when doing git clone should be the same LF on linux and macosx, this is not a windows anyway.

Any ideas?

**Comment by memsharded** [comment]
Yes, the best at this stage would be to get the ``conanmanifest.txt`` inside the export folder of each case, and compare (git diff is ok, they should be ordered), and that will give use more insights of what files could be the ones actually causing different revisions.

**Comment by igagis** [comment]
I found no way to list contents of `conanmanifest.txt` in export_folder, since in `export()` method the file is not yet existing and in all subsequent methods the `self.export_folder` is not available. So, how can I do it on CI?

**Comment by memsharded** [comment]
Yes, in the CI logs the folders where the packages are "exported" is in the logs. Or you can use the ``conan cache path`` command to get the path in the cache. But it has to happen after the package is exported, it cannot be done in the recipe, as you detected, while the recipe is being exported, there is still no ``conanmanifest.txt``, Conan computes it after the package has been exported.

You could also print it, after the export, like in the build method:
```
from conan.tools.files import load
def build(self):
       print(load(self, os.path.join(self.recipe_folder, "conanmanifest.txt")))
```

**Comment by igagis** [comment]
it looks like `conandata.yml` is different:
https://github.com/cppfw/utki/actions/runs/4342927289/jobs/7584339561#step:11:20
```
1678102373
conandata.yml: 17ada0512e7252e389d063e098297d6a
conanfile.py: 00db12ba8f0139260321a68a123b8592
```

https://github.com/cppfw/utki/actions/runs/4342927289/jobs/7584339089#step:11:19
```
1678102334
conandata.yml: ed365883a04320749cf73a69fe5bdc3d
conanfile.py: 00db12ba8f0139260321a68a123b8592
```

**Comment by memsharded** [comment]
Then you might be able to list it too:
```python
    def build(self):
        print(load(self, os.path.join(self.recipe_folder, "conanmanifest.txt")))
        print(load(self, os.path.join(self.recipe_folder, "conandata.yml")))
```
(it seems you have some processing that would make it different in different platforms)

**Comment by igagis** [comment]
`conandata.yml` looks identical, at first glance:
https://github.com/cppfw/utki/actions/runs/4343019051/jobs/7584544393#step:11:22
https://github.com/cppfw/utki/actions/runs/4343019051/jobs/7584544858#step:11:23

**Comment by memsharded** [comment]
If the ``conandata.yml`` seems identical, the possible explanation is that the line endings would be different, try:
```python
def build(self):
    print(load(self, os.path.join(self.recipe_folder, "conandata.yml")).splitlines(keepends=True))
```

**Comment by igagis** [comment]
I printed md5 sums also:
https://github.com/cppfw/utki/actions/runs/4343145639/jobs/7584827971#step:11:26
https://github.com/cppfw/utki/actions/runs/4343145639/jobs/7584828458#step:11:27
those are different.

Also, the git URL is as follows:
```
url: https://***@github.com/cppfw/utki
```
i.e. github actions have hidden the auth part of it behind `***` , but there actually is  `${{ github.token }}`, I suspect that the token is different for different jobs. I don't think it is line endings.

I need to investigate how to get remote URL without auth part, i.e. `git.get_remote_url()` but drop the auth part of the URL...

**Comment by memsharded** [comment]
Oh, yes, having different tokens for different jobs would make sense that is causing the issue.

> I need to investigate how to get remote URL without auth part, i.e. git.get_remote_url() but drop the auth part of the URL...

This seems like a reasonable use case, we might want to provide some utilities to help and make it easier. Looking forward your investigation, and I am tagging this as something to check ("look into")

This is useful information, thanks very much for all the feedback!

**Comment by memsharded** [comment]
Actually, lets spin a new ticket, as this has diverged too much from the original question (and we can close this question as solved)

**Comment by memsharded** [comment]
Ticket https://github.com/conan-io/conan/issues/13338 created to follow up, if the question about the server is solved, lets close here and follow the other one. Thanks!

**Comment by igagis** [comment]
Ok, I think we can close this one.

So far I'm looking into other GIT authentication options like `GIT_ASKPASS` etc. to avoid storing token embedded into the URL in the first place.

Thanks for your help!
