### ISSUE TITLE
[bug] Can't install remotes from remotes.txt on Conan 2.0.1

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#13318]
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version:
* Conan version: 2.0.1
* Python version: 3.8

### Steps to reproduce

```
$ export CONAN_HOME=~/brewst/.conan2
$ conan config install conan/config
Installing settings.yml
Copying file remotes.txt to /home/eriff/brewst/.conan2/.
[...]
```
But then
```
$ conan remote list                
conancenter: https://center.conan.io [Verify SSL: True, Enabled: True]
```
My `remotes.txt`:
```
$ cat conan/config/remotes.txt                      
conan-brewst https://artifactory.redacted.com/artifactory/api/conan/brewst-conan True
```

Looking around the docs, I found that
```
Overrides remotes. Will remove remotes that are not present in file.
Please, note that only one of remotes.json or remotes.txt should be
installed. If you have both .txt and .json in the folder, repo, etc.
that you are installing from, it can lead to undefined behaviour as the
order of the install is not deterministic
```
And I do have that remotes.json but I did not create it. Is json the default format for the remotes on 2.0?

**Comment by ericriff** [comment]
Even if I remove `remotes.json` from my cache, it gets recreated and my `remote.txt` gets installed next to it and ignored.

**Comment by memsharded** [comment]
``remotes.txt`` has been removed in 2.0, and ``remotes.json`` is the file that needs to be defined and shared: https://docs.conan.io/2/reference/config_files.html

**Comment by ericriff** [comment]
Maybe that should be listed on the migration guide. I looked for it but didn't see it. Or maybe flag remotes.txt as deprecated on the 1.x docs I referenced above.

**Comment by memsharded** [comment]
Yeah, lets add a note too, thanks!
