### ISSUE TITLE
[question] How to disable warnings about legacy v1 features?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13316]
### What is your question?

In conancenter, usage of `conan.conan_version` has been forbidden by conan team when it aims to conditionally use package_info features allowing support of legacy generators, like `self.env_info`, `self.cpp_info.filenames`, `self.cpp_info.names` & `self.user_info`.
However, conan v2 displays tones of warnings when it sees this legacy syntax in recipes. When you have many dependencies and many components, it makes conan output quite noisy and hard to read.
Is there some conf to disable these warnings?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13319 for 2.0.2
