### ISSUE TITLE
[question] How to use System requirements

### ISSUE THREAD

**Issue by xakod** [conan-io/conan#13335]
### What is your question?

Hello, I use System requirements like this in conanfile:
```
     def system_requirements(self):
         Apt(self).install(["python3-dev"])
         Brew(self).install(["python3-dev"])
```
But then I see error:

> ERROR: while executing system_requirements(): System requirements: 'python3-dev' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'

Look like it's ok but I have this package 

> apt list --installed | grep python3-dev
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> libpython3-dev/jammy,now 3.10.4-0ubuntu2 amd64 [installed]
> python3-dev/jammy,now 3.10.4-0ubuntu2 amd64 [installed]

Conan version 1.59.
How to use system requirements correctly? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
You can have a look to: https://docs.conan.io/1/reference/conanfile/tools/system/package_manager.html#configuration-properties-that-affect-how-system-package-managers-are-invoked, there it says about:

- tools.system.package_manager:mode: mode to use when invoking the package manager tool. There are two possible values:
  - "check": it will just check for missing packages at most and will not try to update the package manager database or install any packages in any case. This is the default value.
  - "install": it will allow Conan to perform update or install operations.
- tools.system.package_manager:sudo: Use sudo when invoking the package manager tools in Linux (False by default)
- tools.system.package_manager:sudo_askpass: Use the -A argument if using sudo in Linux to invoke the system package manager (False by default)
