### ISSUE TITLE
[question] API way for copying (transient) dependency libraries

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#13331]
### What is your question?

Hi!
Is there an official way for copying libraries from transient/direct dependencies to the project's package lib folder?
Let's say we have a dependency chain such as: `LibraryA` -> `LibraryB` -> `LibraryC`

Then we specify library component dependencies in `LibraryA`:
```
self.cpp_info.components[<component_name>].libs = [<libraryB_lib>]
```
We do the same in `LibraryC`:
```
self.cpp_info.components[<component_name>].libs = [<libraryC_lib>]
```

However, when invoking `conan create ...` or `conan install ...` the resulting pakage directory for `LibraryA` does not contain nor `libraryB_lib` nor `libraryC_lib`.
I've read about the [new deploy process](https://github.com/conan-io/conan/issues/7402), but it seems ti require a manual library copy to defined under `deploy()`.

Is there a better, automated way for doing this?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @donlk 

Thanks for your question.
It is not very clear why you are using components there, and if it is related or not to the issue.
If you have 3 packages called ``librarya``, ``libraryb`` and ``libraryc`` and these packages contain each one 1 library, it is not necessary to use components at all.

Also the final goal is not clear either. In most cases, the consumer package doesn't want to do a copy of the transitive dependencies, but it just needs the location of those libraries to link with them. It would be necessary to clarify a bit the goal.
You also need to specify the Conan version, Conan 2.0 contains new ``deployers`` to gather binaries from the dependency graph, to extract binaries outside of Conan if necessary (not necessary while working with Conan)

**Comment by donlk** [comment]
Thanks for the answer.
Let me clarify:
Each library contains potentially multiple library files. Now, when the linkage is static, I would agree with you, it is not necessarily required to include all the dependent libraries in the tree, as the subsequent libraries contain all the necessary symbols. However, when we are using shared linkage **and** we are building a release project, that project needs to be shipped with every necessary library it was built with, excluding the system libraries, obviously. Moreover, it is absolutely imperative when cross-compiling is involved. It is not just a mere conveninence, in a closed source environment the final package should be able to run with the least amount of system libraries possible. Even if we would encourage the consumer to install the necessary libraries for a distro, version incompatibility is bound to happen.

Yes, I am using Conan 2.0 and I've also looked at the `deployers` module with `full_deploy`, but I didn't copy any of the dependent libraries in place. Also - if I read correctly - it behaves as a simple package folder copy, it doesn't take into account the internal component dependency structure. Correct me if I'm wrong, naturally.

In my point of view the ideal solution would take into account the component dependency graph (or something similar) and do a full deploy that way, only copying the necessary library files into one lib folder, better yet, to predefined lib folders, if specified.

Don't get me wrong, conan is an absolute marvel in the C++ world, something that I've craved for years. Maybe my needs are not that common, but I do believe such a feature would benefit the system immensely.

**Comment by memsharded** [comment]
> Yes, I am using Conan 2.0 and I've also looked at the deployers module with full_deploy, but I didn't copy any of the dependent libraries in place. Also - if I read correctly - it behaves as a simple package folder copy, it doesn't take into account the internal component dependency structure. Correct me if I'm wrong, naturally.

Ok, thanks for the clarifications, I understand better now.
Yes, it is expected that the ``full_deploy`` is not the perfect solution for everyone, and this is the reason we made the ``deployers`` customizable on the user side. You can write your deployer to do the logic you want, in what files do you copy, and also where you want to copy them

> In my point of view the ideal solution would take into account the component dependency graph (or something similar) and do a full deploy that way, only copying the necessary library files into one lib folder, better yet, to predefined lib folders, if specified.

Yes, the ``deployers`` interface receives the whole dependency graph, and for every package in the graph, the internal ``cpp_info.components`` model is also available.

I'd suggest crafting some deployer that fits your needs, and let us know how it goes. At the moment it sounds a bit too specific of a use case, but if you think it could be of wider interest to other conan users, and you want to start contributing it and collaborating on https://github.com/conan-io/conan-extensions, we have setup this repo for this kind of things

**Comment by AbrilRBS** [comment]
Closing as solved, thanks for the question
