### ISSUE TITLE
[feature] Support loading multiple config files

### ISSUE THREAD

**Issue by rettenbs** [conan-io/conan#13334]
### What is your suggestion?

Hi,

Jinja, has a nice feature, we want to make use of for `global.conf`. You can include other files:
```jinja
{% include "user.conf" ignore missing %}
```

Idea: We use `conan config install` to download our default config. Users can overwrite some settings in `user.conf` if they have some custom preferences.

The error message we get, when adding the line to the template:
```
TypeError: no loader for this environment specified
```

To support `include` statement, Conan needs to load the template from the environment:
```python
Environment(loader=FileSystemLoader(base_path)).from_string(text).render({"platform": platform, "os": os, "distro": distro})
```
For profiles this is already working.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks @rettenbs for the suggestion.

I think this could make sense, lets have a look to see if possible.

**Comment by memsharded** [comment]
Seems quite straightforward, proposing https://github.com/conan-io/conan/pull/13336 for next 2.0.2
