### ISSUE TITLE
Git scm with Github tokens in URL produce different revisions

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#13338]
- scm captures in conandata.yml the url
- the url contains the token for the repo
- This happens in Github actions

I printed md5 sums also:
https://github.com/cppfw/utki/actions/runs/4343145639/jobs/7584827971#step:11:26
https://github.com/cppfw/utki/actions/runs/4343145639/jobs/7584828458#step:11:27
those are different.

Also, the git URL is as follows:
```
url: https://***@github.com/cppfw/utki
```
i.e. github actions have hidden the auth part of it behind `***` , but there actually is  `${{ github.token }}`, I suspect that the token is different for different jobs. I don't think it is line endings.

I need to investigate how to get remote URL without auth part, i.e. `git.get_remote_url()` but drop the auth part of the URL...

_Originally posted by @igagis in https://github.com/conan-io/conan/issues/13311#issuecomment-1456029255_

**Comment by igagis** [comment]
I think it would be handy if [`git_remote_url()`](https://docs.conan.io/1/reference/conanfile/tools/scm/git.html#get-remote-url) provided an option to strip out credentials out of the box. Right now the doc has a warning that stripping out the credentials is user's responsibility.

**Comment by igagis** [comment]
At the moment I started using `GIT_ASKPASS` for git authentication, this way it doesn't store the Token in the remote URL.

**Comment by memsharded** [comment]
Hi @igagis 

I am playing a bit with this with Github actions.
I have setup my own private repo, but by default it doesn't capture such token, but instead it is failing in the ``source()`` retrieval of the code.

How did you have configured the Github action to get the token in the URL?

**Comment by igagis** [comment]
Hi @memsharded ,

I use my own github action to clone the git repo:
https://github.com/myci-actions/checkout

and version `7` of the action was cloning the repo like this:
https://github.com/myci-actions/checkout/blob/6419226e4f32b9c0e8733db60e5c302277482d9f/action.yml#L29

but now in version `8` I changed it to use `GIT_ASKPASS`:
https://github.com/myci-actions/checkout/blob/master/action.yml#L28

so, I was able to workaround the problem.

**Comment by memsharded** [comment]
Ok, thanks for the feedback.
I have managed to build a pipeline with built-in Github actions that implement the basic Conan-Git-SCM capturing and using ssh keys, so no need to strip or inject anything into the URLs.

 I think I will send a PR to the docs to explain it, hopefully that helps other users too.

**Comment by memsharded** [comment]
I am submitting this PR to the docs: https://github.com/conan-io/docs/pull/3112, suggesting that it will close this issue.
We might add there other approaches like using GIT_ASKPASS as you did, but I still feel that this is more the way to go than messing with the URLs, please let me know what you think.

**Comment by igagis** [comment]
looks good to me

**Comment by memsharded** [comment]
Closing this issue as documented in https://github.com/conan-io/docs/pull/3112, the idea is that URLs managed by Conan shouldn't be authentication-dependant or contain any tokens, user or similar. Instead, other built-in mechanisms like ssh-keys should be used for orthogonal and more secure authentication.

If there is any further question, please re-open or file a new ticket. Many thanks for the feedback!

**Comment by rhuitl** [comment]
In case somebody else finds this thread: I ran into this issue where the auth credentials ended up in `conandata.yml` because I was setting up a Github Action Workflow this way, to allow Conan retrieve sources from Git (and not store them in the Conan package itself):

```yaml
    - name: Configure Git to use the GitHub token
      shell: bash
      run: git config --global url."https://oauth2:${{ github.token }}@github.com/".insteadOf "https://github.com/"
```

Now I changed it to a slightly different approach, which is also cleaner, and that works better:
```yaml
    - name: Configure Git to use the GitHub token
      shell: bash
      run: |
        git config --global credential.helper store
        echo "https://oauth2:${{ github.token }}@github.com/" >> ~/.git-credentials
```

While SSH keys would certainly also work, and have more advantages (e.g. allow access to other private repositories in case Conan needs to rebuild dependencies from source) they need extra work to set up. The `github.token` is built-in and works out of the box.

**Comment by memsharded** [comment]
Thanks for the feedback @rhuitl, it can really help other users.

The docs in https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html comment:

> The first important bit is that git.get_url_and_commit() will capture the url of the origin remote. This url must not encode tokens, users or passwords, for several reasons. First because that will make the process not repeatable, and different builds, different users would get different urls, and consequently different recipe revisions. The url should always be the same. The recommended approach is to manage the credentials in an orthogonal way, for example using ssh keys. The provided example contains a Github action that does this:

And that example there also contains code for GH actions to setup ssh-keys
