### ISSUE TITLE
[question] Integration tests

### ISSUE THREAD

**Issue by sandeshhardikar** [conan-io/conan#13333]
### What is your question?

Dear Team ,

I need suggestion for integration tests if you are already covering such a scenario. 

I will try to describe my use case below . 

- Lets say I have a generic tool called `my-tool/1.0.0` in the form of a conan package which is widely consumed by multiple recipes. 
- I would like to see that as soon as i have new release of `my-tool/1.1.0` the build pipelines for all its consumers are triggered and the breaking changes are detected even before they try to integrate them.
I tried to draw a small picture for it . 

For example : if a new version of [bison/3.7.2](https://github.com/conan-io/conan-center-index/blob/aca585b3617a00f86bef47eafb60ef19d5269f69/recipes/nas/all/conanfile.py#L50) is released , do you rebuild [nas](https://github.com/conan-io/conan-center-index/blob/aca585b3617a00f86bef47eafb60ef19d5269f69/recipes/nas/all/conanfile.py) recipe with it automatically before someone tries to upgrade it manually ?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandeshhardikar 

Thanks for your question.

The problem you are describing is a Continuous Integration problem for separate packages, and it is a complex problem that goes beyond package management.

Conan has several tools to help implementing such thing, but the overall solution is typically implemented in CI.

Please start reading this (even if it is from the 1.X version, not 2.0 latest): https://docs.conan.io/1/versioning/lockfiles/ci.html
The core ideas:
- To have more than one server repository, so packages created during CI do not break other developers and flows
- To define some "products" that are the ones to perform CI over (the products we need to maintain and keep delivering and not breaking during CI)

Then, lockfiles in 1.X were very challenging, so they have been massively simplified and improved in 2.0, please have a look: https://docs.conan.io/2/tutorial/versioning.html

And the CI docs and tutorial for 2.0 is still missing, we will be working on that soon, so please keep tuned. Thanks!

**Comment by memsharded** [comment]
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.

**Comment by oleksiigmg** [comment]
I am trying to implement multiple remotes approach in conan v1. I have the same build machine which builds ci and production pipelines. How to allow only certain remotes to be used depending on the stage in the pipeline? Shall I use different conan cache locations or can I run `conan remote enable/disable` command? I am afraid that conan v1 package association to remote can create issues.

**Comment by memsharded** [comment]
@oleksiigmg 

> I am trying to implement multiple remotes approach in conan v1. I have the same build machine which builds ci and production pipelines. How to allow only certain remotes to be used depending on the stage in the pipeline? Shall I use different conan cache locations or can I run conan remote enable/disable command? I am afraid that conan v1 package association to remote can create issues.

Certainly, in Conan1, if you disable one remote, but the package is associated to that remote it will be problematic. This is one of the reasons why this association was removed in Conan2. So yes, you might need different caches.

If you haven't had the chance to have a look at it, there is now a CI-tutorial in Conan 2 docs: https://docs.conan.io/2/ci_tutorial/tutorial.html. Even if you will not be able to implement it in Conan 1, at least it would be good to check it to learn about the principles, good practices and tools that have resulted from the experience doing CI of many users feedback, and have been implemented in Conan 2 tooling (I guess that you are also aware of Conan1 being deprecated, upgrading to Conan2 should be prioritized).

**Comment by oleksiigmg** [comment]
yep, I want to do v2 migration in two steps. First make recipes to use new features, generators etc which available in 1.66 and then switch to v2 completely and gradually introduce the rest of v2 features. But for that I need to refactor quite some recipes and I want to have separate artifactory repo for those refactored packages, with which I can build products and do qa before moving them to main repo

**Comment by memsharded** [comment]
>  But for that I need to refactor quite some recipes and I want to have separate artifactory repo for those refactored packages, with which I can build products and do qa before moving them to main repo

This might not be necessary. We migrated the whole ConanCenter (+1800 recipes) using the same Artifactory server repository.
If the package recipes aren't really different between Conan 1 and Conan 2 they will still generate the same exact ``recipe_revision``, which means that the recipe can be common to both conan 1 and conan 2. But the binaries will be disjoint sets, the binaries built with Conan 1 are visible only for Conan 1, and the binaries built with Conan 2 are visible only for Conan 2, so they don't interfere each other, and the CI can work without issues in the 2 pipelines.

**Comment by oleksiigmg** [comment]
> This might not be necessary...

Thanks for the hint! It is good to know that I can use same remote for conan v2. However, my question is about using two remotes for conan v1. When I need multiple CONAN_USER_HOME caches for working with conditionally different remotes, how could I avoid rebuilds? Basically I need download package from test remote and upload it to the build remote?

**Comment by memsharded** [comment]
> Thanks for the hint! It is good to know that I can use same remote for conan v2. However, my question is about using two remotes for conan v1. When I need multiple CONAN_USER_HOME caches for working with conditionally different remotes, how could I avoid rebuilds? Basically I need download package from test remote and upload it to the build remote?

It is not clear the issue. When packages are in the server, they are not rebuilt, so it is not important having different CONAN_USER_HOMEs, but just what packages are in the server, and that is done by doing "promotions" (yes, download from one remote and upload to other remote, is a copy promotion. It might be much faster and atomic to run those promotions with the Rest API, in Conan 2 this can be done with the ``conan art:promote`` command).

So I don't fully understand what is the connection between those. This is also a closed ticket, so it might be better to create a new ticket with the new question, to better track it (it is easier for closed tickets to fall through the cracks)
