### ISSUE TITLE
[bug] conanfile.py's configure is not respected in 2.0.1

### ISSUE THREAD

**Issue by ktamail666** [conan-io/conan#13339]
### Environment details

* Operating System+version: Win 10
* Compiler+version: msvc17
* Conan version: 2.0.1
* Python version: Python 3.10.7

### Steps to reproduce

This is from my script that works fine with conan 2.0.0:
```
conan install "${CONAN_FILE}" --output-folder="${INSTALL_FOLDER}" --profile:build=${CONAN_PROFILE} --profile:host=${CONAN_PROFILE} --build=missing
```
CONAN_PROFILE=conan_profiles/msvc17.txt
[msvc17.txt](https://github.com/conan-io/conan/files/10898431/msvc17.txt)
[conanfile.py.txt](https://github.com/conan-io/conan/files/10898465/conanfile.py.txt)
(I had to add .txt extension for conanfile)

but after update conan to 2.0.1, I got errors (attached logs below):
`pip install conan==2.0.1`

To workaround I downgraded to 2.0.0
`pip install conan==2.0.0`

I think stb dependency comes from tinygltf but I disabled it in configure:
```
    def configure(self):
        self.options["tinygltf"].draco = False
        self.options["tinygltf"].stb_image = False
        self.options["tinygltf"].stb_image_write = False
```
but it looks like from 2.0.1 is not working.

I would highlight this works fine with 2.0.0

### Logs

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
stb/cci.20210910: Not found in local cache, looking in remotes...
stb/cci.20210910: Checking remote: sim-conan
Graph root
    conanfile.py: C:/3rdparty\conanfile.py
Requirements
    nlohmann_json/3.9.1#0 - Cache
    sdl/2.0.18#16f6f021e7fd8754c07d3e4ed3a757e6 - Cache
    tinygltf/2.5.0#0 - Cache
    zlib/1.2.13#0 - Cache
ERROR: Package 'stb/cci.20210910' not resolved: Unable to find 'stb/cci.20210910' in remotes
```

**Comment by memsharded** [comment]
Hi @ktamail666 

In Conan 2.0, the syntax for matching dependencies has been normalized to be consistent accross many places. It also requires patterns to be explicit sometimes that resolve some ambiguities. In your case it is necessary to do:

```python
        self.options["tinygltf/*"].draco = False
        self.options["tinygltf/*"].stb_image = False
        self.options["tinygltf/*"].stb_image_write = False
```

You might want to read the comment in https://github.com/conan-io/conan/issues/13233#issuecomment-1446974793 for more insights on why this is necessary and it solves some issues in 1.X.

This syntax also has already been in 1.X for a long time, it is not necessary incompatible, as the above should work in 1.X too.

**Comment by ktamail666** [comment]
thank you very much for quick response. yes if I added "/*" to my options works again fine with 2.0.1.

**Comment by memsharded** [comment]
Great to know! Thanks for the feedback.
Then I guess we can close this issue as solved, but don't hesitate to re-open or create new tickets for further questions.
