### ISSUE TITLE
Smart symlinks handling

### ISSUE THREAD

**Issue by kdsx** [conan-io/conan#1333]
Actually there's no any problem to handle symlinks right now, however this handling can be simplified a bit.

I suggest adding "auto" mode for `symlinks` parameter. In this mode conan would preserve relative symlinks if their targets are in the package directory and follow any other links. I suppose this is what users usually want. The only questionable case is symlink which tries to get out of package bounds in the middle of its target path: `../../../../../../../a/b/c/d/e/package_root/lib/libsomething.so`. Such tricky links could be either simplified or followed.

**Comment by memsharded** [comment]
Yes, right now symlinks are assumed to be relative. What would be the use case for other non-relative symlinks? Indeed going out of the package bounds seems problematic.

**Comment by kdsx** [comment]
Actually this issue targets the default behavior which is currently "follow symlinks" (copy target file content instead of a symlink itself). As I understand this is done this way to guarantee that the resulting package does not contain broken symlinks. Non-relative symlinks could accidentally appear in the package directory, so this behavior is less error-prone. Now a user must ensure his package contain only "good" links and then set `symlinks=True`. However it is a bit annoying when one have to deal with Linux ".so" files every day. This is why I suggest this simplification. If conan could detect which symlinks are good and which are not automatically then users would remember about `symlinks` parameter only in very-very specific cases.

So what do we have now:
`symlinks=False` or `symlinks=None` (default): never copy symlinks, instead copy files content.
`symlinks=True`: always copy symlinks as symlinks.

What I suggest:
`symlinks=False`: never copy symlinks, instead copy files content.
`symlinks=True`: always copy symlinks as symlinks.
`symlinks=None` (default): copy "good" symlinks as symlinks and copy file content for "bad" symlinks.
Tricky symlinks like I mentioned before could be either simplified `../../../../../../../a/b/c/d/e/package_root/lib/libsomething.so -> libsomething.so` or treated as "bad".

**Comment by lasote** [comment]
I would prefer to just write some warning if a file is linked outside the package.
The default behavior should be to copy, I think.

**Comment by danimtb** [comment]
Currently only relative symlinks are copied and preserved and absolute ones pointing out of the package normally error with a "broken link" message. I think we haven't found strong evidence that this is a requested feature by the community and handling symlinks is always very tricky.

I am closing this but please feel free to open a new issue with an updated request if needed. Thanks!
