### ISSUE TITLE
[question] Conan v2: Is it possible to have a build requirement to another package of the same recipe?

### ISSUE THREAD

**Issue by Corristo** [conan-io/conan#13348]
Hi,

a bit of background: I'm trying to create a recipe(s) for Qt 6.4 for both x86_64 and aarch64 linux. However, in order to cross-compile Qt one already needs to have Qt binaries that can run on the build pc (x86_64 in my case). I could of course create two recipes,`qt-native` and `qt-cross`, where `qt-cross` has a build-requirement on `qt-native`, but that would duplicate a lot of code.

I was thus wondering if it is possible to declare a build requirement on a package of the same recipe but with different settings, e.g. something like
```
class QtRecipe(ConanFile):
    name = "qt"
 
    def requirements(self):
       if self.settings_target and self.settings_target.arch != self.settings.arch:
           self.tool_requires(f"qt/{self.version}")
```

to detect that we're cross-compiling and to request qt binaries for the build context. If this is possible, can I also set options for the qt package in the build context?

Thank you for your help

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Corristo 

Thanks for your question.

Yes, this should be possible in 2.0. We have a test that explicitly checks this behavior: https://github.com/conan-io/conan/blob/bc6a0eb13b2d0f82703464c77faf1df3640401aa/conans/test/integration/build_requires/test_install_test_build_require.py#L182, please, have a look, it could give some hints:

- The core recipe code is:
  ```python
  class Pkg(ConanFile):
            name = "tool"
            version = "1.0"
            settings = "os"
            def build_requirements(self):
                if cross_building(self):
                    self.tool_requires("tool/1.0")
   ```
- Then to avoid unnecessarily rebuilding the ``--build=missing:tool*`` would be the way to do it.

**Comment by memsharded** [comment]
I guess that the above response was working, so I am closing this question, please re-open or create new tickets if you have any further question.
