### ISSUE TITLE
Documentation lacks root_package parameter description for imports() 

### ISSUE THREAD

**Issue by kdsx** [conan-io/conan#1334]
I was looking for the way to import some directory for a specific package and didn't find it in the doc. Happily `copy` function already supports it :)

Also I wonder if it is possible to specify exclusions for importing files? E.g. I want to import contents of `bin` directory of all packages but Qt. So far I just iterate over `deps_cpp_info`, but maybe it could be done simpler?

**Comment by memsharded** [comment]
Certainly, this should be documented, sorry.

There is some ongoing work in https://github.com/conan-io/conan/pull/1327 to improve the imports, allowing organized imports, with a folder per package. There is already some support for exclusions in exports, so probably can be extrapolated to imports too. Lets try it for 0.24 release, thanks for your suggestion!

**Comment by memsharded** [comment]
It will also be properly documented. For documentation issues, you can submit issues and pull requests too to the docs repo, the docs are in github too: https://github.com/conan-io/docs

**Comment by kdsx** [comment]
Oh sorry, I didn't notice that repo. Thanks.

**Comment by memsharded** [comment]
I have added to https://github.com/conan-io/conan/pull/1327:

- Using imports parameters in conanfile.txt
- Defining "excludes" parameters
- Ignore_case argument
- Folder argument

**Comment by memsharded** [comment]
Merged! Will be released in 0.24.

**Comment by memsharded** [comment]
Functionality released in 0.24, docs pending: https://github.com/conan-io/docs/issues/230
