### ISSUE TITLE
[question] Conan does not detect Visual Studio Compiler

### ISSUE THREAD

**Issue by IceflowRE** [conan-io/conan#13345]
### What is your question?

I use `conan profile detect --force` and it shows me 
> No compiler was detected (one may not be needed)

what do i have to do that the Visual Studio Compiler is found?
The Build Tools and CMake support is installed.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @IceflowRE 

If you are using Conan 2.0, did you upgrade to 2.0.1? There was an issue fixed in https://github.com/conan-io/conan/pull/13284, that vswhere was failing to detect some msbuild-tools installation only.

**Comment by IceflowRE** [comment]
```
vswhere -all -prerelease 
```
```
Visual Studio Locator version 3.1.1+f4ef329670 [query version 3.6.30.6854]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 34d85d6b
installDate: 19.07.2021 00:28:18
installationName: VisualStudioPreview/17.6.0-pre.1.0+33417.168
installationPath: C:\Program Files\Microsoft Visual Studio\2022\Preview
installationVersion: 17.6.33417.168
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\devenv.exe
state: 4294967295
isComplete: 1
isLaunchable: 1
isPrerelease: 1
catalog_manifestName: VisualStudioPreview
catalog_manifestType: installer
catalog_productDisplayVersion: 17.6.0 Preview 1.0
catalog_productLine: Dev17
catalog_productLineVersion: 2022
catalog_productMilestone: Preview
catalog_productMilestoneIsPreRelease: True
catalog_productName: Visual Studio
catalog_productPatchVersion: 0
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productSemanticVersion: 17.6.0-pre.1.0+33417.168
catalog_requiredEngineVersion: 3.6.36.30156
properties_campaignId:
properties_channelManifestId: VisualStudio.17.Preview/17.6.0-pre.1.0+33417.168
properties_nickname:
properties_removeOos: 0
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe
```
```
conan --version 
```
```
Conan version 2.0.1
```

**Comment by memsharded** [comment]
Thanks for the feedback.
It seems that Conan it is not detecting pre-releases by default in the internal call to ``vswhere``.

I am submitting this https://github.com/conan-io/conan/pull/13355 as a starting point to discuss with the team what should be the Conan default (if you want to test with that branch if that would work in your case, that would be great too)

**Comment by memsharded** [comment]
#13355 moved forward, for next 2.0.2
