### ISSUE TITLE
[feature] `conan config get` for Conan 2.x

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#13340]
### What is your suggestion?

Hi,

as mentioned in #13254 it is quite impossible to set config values from an external source now.
However, the `conan config get` command might be very useful. Especially when Jinja2 expressions are used in the `global.conf` file or if it is allowed to split the configuration into multiple files (#13334). Usually our developers do not care about Python, Jinja2 or anything else, so a `conan config get` would tell them very easily (without knowing Jinja2 at all) the value of a configuration option.

Best regards,
gpxricky

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @gpxricky, thanks for taking the time to open the request. Your request seems more than reasonable, so we're implementing something in #13354 :)

**Comment by AbrilRBS** [comment]
Hi! This has now been implemented in the linked PR and will be available in 2.0.2!
