### ISSUE TITLE
[question] Proper way to set compiler path for tool_requires in 2.0

### ISSUE THREAD

**Issue by daltonv** [conan-io/conan#13341]
### What is your question?

I'm trying out packaging the gcc compiler in 2.0 and trying to figure out the "right" way of telling a consuming project to use this package.

My conanfile looks something like this for the compiler itself

```python
class ArmGcc(ConanFile):
    name = "gcc-arm-none-eabi"
    version = "9-2019-q4-major"
    package_type = "application"

    ...

    filename="gcc-arm-none-eabi.tar.bz2"
    foldername="gcc-arm-none-eabi"


    def build(self):
        conan.tools.files.download(self, url="https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2",
            filename=self.filename,
            verify=False,
            # Set this because the arm site hates the full Conan default user agent and
            # blocks access with 403 Forbidden with that agent.
            headers={
                'User-Agent':'Conan/2.0.0'
            })
        self.output.info("Downloaded gcc compiler")

        conan.tools.files.unzip(self, self.filename)

        os.unlink(self.filename)

    def package(self):
        package_folder = Path(self.build_folder) / f"{self.name}-{self.version}/"
        #package_bin = Path(self.package_folder) / "bin"
        conan.tools.files.copy(self, "*", src=package_folder, dst=self.package_folder, keep_path=True)

    def package_info(self):
        # TODO this is so the consumer can grab specific libs and such
        self.buildenv_info.define("GCC_ARMCOMPILER", self.package_folder)
```

Then in the consuming project should I just set
```python
tool_requires = "gcc-arm-none-eabi/9-2019-q4-major"
generators= "VirtualBuildEnv"
```

Should I be making a custom profile for the gcc toolchain/target and always adding a `-pr:h=../profiles/embedded_arm` arg to my conan commands on the consuming package end? Where my profile looks something like

```ini
[settings]
os=baremetal
arch=armv6
compiler=gcc
compiler.version=9.1
compiler.libcxx=libstdc++
build_type=Release
[buildenv]
CC=arm-none-eabi-gcc
LD=arm-none-eabi-ld
LDFLAGS=-Wl,--gc-sections --specs=nano.specs --specs=nosys.specs -mthumb -mabi=aapcs -Wl,-Map=${CMAKE_PROJECT_NAME}.map
```

Or is there some command I can add to the `package_info()` function of the compiler package that specifies the `CC` command to use when depending on this package? I'm guessing something like `self.cpp_info.cc = bin/arm-none-eabi-gcc`

Maybe it's because I hail from the land of custom makefiles but the profile file seems odd to me, especially when you specify a dependent package that contains the compiler.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by SpaceIm** [comment]
You can have a look at `package_info()` of `android-ndk` recipe in conancenter: https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/conanfile.py#L246-L321

It may be more complex than what you need, but basically you set `tools.build:compiler_executables` config, and `CC`/`CXX`/`LD`/`AR`/`STRIP`/`RANLIB` etc env vars through `self.buildenv_info` + eventually things like `tools.build:sysroot` config (and `SYSROOT` in buildenv_info just to be sure) and `tools.build:sharedlinkflags`/`tools.build:exelinkflags` (+ `LDFLAGS` in build_envinfo).

Once your `gcc-arm-none-eabi` recipe is properly written, your host profile should look like this:

```ini
[settings]
os=baremetal
arch=armv6
compiler=gcc
compiler.version=9.1
compiler.libcxx=libstdc++
build_type=Release
[tool_requires]
gcc-arm-none-eabi/9-2019-q4-major
```

**Comment by daltonv** [comment]
Hey @SpaceIm,

Thanks for the help. That example is very useful, and I definitely see the utility of putting the `[tool requires]` section in the profile instead of the conanfile itself.

I will try this method.

Regards,
Dalton
