### ISSUE TITLE
[question] conan search is not resultin in desired output

### ISSUE THREAD

**Issue by laxmij-cmd** [conan-io/conan#13352]
### What is your question?

When I run the command

conan search bzip2
There are no packages matching the 'bzip2' pattern

Why this is so? Is this issue related t permission? If yes, who will give me permission?

conan remote list shows remote repo

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @laxmij-cmd, thanks for your question. The default `conancenter` remote does not need any permission to use it, and locally, running `conan search bzip2/*` correctly shows me both currently available references, so there must be something else going on (Note the `*`, I get the same result without it, but Conan 2 tries to be more homogeneous in its interface so using patterns everywhere is a good practice)

What Conan version are you running? Are you using your own custom remote repository?

**Comment by laxmij-cmd** [comment]
My issue is resolved now. It was related to our own custom repository.
