### ISSUE TITLE
[question] Retargeting older .vcxproj files when using msbuild

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#13369]
### What is your question?

Older Visual Studio solutions will error when trying to build with a newer version and will require re-targeting of the .vcxproj. Normally you'd pass the parameter `/p:PlatformToolset=v<version>` to `msbuild` but it doesn't seem like conan does that by default. In a recipe using `MSBuild` and `MSBuildToolchain` how can I do this?

right now I have
```python
def layout(self):
    vs_layout(self)
    
def generate(self):
    env = VirtualBuildEnv(self)
    env.generate()
    tc = MSBuildToolchain(self)
    # This doesn't work
    # tc.properties["PlatformToolset"] = "v142"
    tc.generate()
        
def build(self):
    project = "cppunit_dll.vcxproj" if self.options.shared else "cppunit.vcxproj"
    msbuild = MSBuild(self)
    msbuild.build(os.path.join(self.source_folder, "src", "cppunit", project))
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

Conan defines the PlatformToolset in the generated toolchain ``conantoolchain.props`` file:

```
 <PropertyGroup Label="Configuration">
            <PlatformToolset>{{ toolset }}</PlatformToolset>
            {% for k, v in properties.items() %}
            <{{k}}>{{ v }}</{{k}}>
            {% endfor %}
          </PropertyGroup>
```
But this file is not automagically injected into the project or in command line. Actually, the idea is that developers can just open the solution/project, and it should work. To achieve that, it is necessary to add the ``conantoolchain.props`` into the project, did you do that?
