### ISSUE TITLE
[question] Overriding requirements in Conan 2.0

### ISSUE THREAD

**Issue by DProvinciani** [conan-io/conan#13368]
### What is your question?

I'm migrating my project from Conan 1.59 to 2.0, and I'm getting this error because `libcurl` didn't upgrade to `openssl/1.1.1t` (used by `poco`).

```
ERROR: Version conflict: libcurl/7.86.0->openssl/1.1.1s, None->openssl/1.1.1t.
```

Is it still possible in Conan 2.0 to override requirements in the `conanfile.txt` as described [here](https://docs.conan.io/en/1.59/using_packages/conanfile_txt.html#overriding-requirements) for Conan 1.59?

Reading the documentation of Conan 2.0, I only see the possibility of using the `override=True` in the `conanfile.py`. [[link](https://docs.conan.io/2.0/tutorial/versioning/conflicts.html#resolving-conflicts)]

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DProvinciani 

Thanks for your question.

Yes, those things are only possible in conanfile.py. We wrote a new dedicated section in the tutorial to explain this: https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html

If you are interested in trying, we also created a new extension command in https://github.com/conan-io/conan-extensions, for experimenting, that automatically converts conanfile.txt to conanfile.py.

**Comment by DProvinciani** [comment]
> If you are interested in trying, we also created a new extension command in https://github.com/conan-io/conan-extensions, for experimenting, that automatically converts conanfile.txt to conanfile.py.

Awesome! I'll give it a try.

So, considering the answer, I close the issue.
