### ISSUE TITLE
[bug] conan 2: Installation of zstd/1.5.4 fails under Windows

### ISSUE THREAD

**Issue by sakra** [conan-io/conan#13370]
### Environment details

* Operating System+version: Window 10 Professional
* Compiler+version: Visual Studio 2022 Community
* Conan version: 2.0.1
* Python version: 3.11.2

### Steps to reproduce

I have the following dependency in a `conanfile.txt`:

    zstd/[~1.5]

Upon installation of the dependency with 

    conan install --profile vs2022 --update --build=missing --output-folder=D:\Builds\build_helloworld_conan_vs2022_ninja_multi S:\github\helloworld

conan aborts the installatiom with the following error message:

    -------- Building package zstd/1.5.4 from source (25 of 28) --------
    zstd/1.5.4: Package zstd/1.5.4:47121e91833bc0c01414a4b0d4515c22a5cef7a2
    zstd/1.5.4: Copying sources to build folder
    ERROR: [('D:\\Cache\\conan\\packages\\zstd02e5ac4a878b3\\s\\src\\tests\\cli-tests\\bin\\unzstd', 'D:\\Cache\\conan\\packages\\t\\zstd4cb24a88a228a\\b\\src\\tests\\cli-tests\\bin\\unzstd', "[Errno 22] Invalid argument: 'D:\\\\Cache\\\\conan\\\\packages\\\\zstd02e5ac4a878b3\\\\s\\\\src\\\\tests\\\\cli-tests\\\\bin\\\\unzstd'")]
    Error copying sources to build folder

In `global.conf` I am using non-standard locations for the caches:

    # caches
    core.cache:storage_path=D:/Cache/conan/packages
    core.download:download_cache=D:/Cache/conan/downloads

Since I do not know if this is an issue with the zstd package or conan itsself, I am reporting this as a bug.

The other packages install fine under Windows. zstd also installs without problems under Linux.

**Comment by memsharded** [comment]
Hi @sakra 

Thanks for your report.
I am not sure what could be failing. I am trying on my Windows machine:
```
conan install --requires=zstd/[*] --build=z*
``` 
with the ``global.conf`` also pointing to another location in another unit, just in case that was causing the issue.
But this doesn't fail on my side.

Could you please try to run the above command, just to rule out if there could be other causes?

**Comment by sakra** [comment]
Here is the output of the command on my Windows machine:

	PS D:\Builds> conan install --requires=zstd/[*] --build=z* -vv

	======== Input profiles ========
	Profile host:
	[settings]
	arch=x86_64
	build_type=Release
	compiler=msvc
	compiler.cppstd=17
	compiler.runtime=dynamic
	compiler.runtime_type=Release
	compiler.version=193
	os=Windows
	[conf]
	tools.cmake.cmake_layout:build_folder_vars=['settings.os', 'settings.arch', 'settings.compiler']

	Profile build:
	[settings]
	arch=x86_64
	build_type=Release
	compiler=msvc
	compiler.cppstd=17
	compiler.runtime=dynamic
	compiler.runtime_type=Release
	compiler.version=193
	os=Windows
	[conf]
	tools.cmake.cmake_layout:build_folder_vars=['settings.os', 'settings.arch', 'settings.compiler']


	======== Computing dependency graph ========
	Graph root
		cli
	Requirements
		zstd/1.5.4#15ac0bc440f89247276d78ea4fdf8b14 - Cache
	Resolved version ranges
		zstd/[*]: zstd/1.5.4

	======== Computing necessary packages ========
	zstd/1.5.4: Forced build from source
	Requirements
		zstd/1.5.4#15ac0bc440f89247276d78ea4fdf8b14:47121e91833bc0c01414a4b0d4515c22a5cef7a2 - Build

	======== Installing packages ========

	-------- Building package zstd/1.5.4 from source (1 of 1) --------
	zstd/1.5.4: Package zstd/1.5.4:47121e91833bc0c01414a4b0d4515c22a5cef7a2
	zstd/1.5.4: Copying sources to build folder
	ERROR: [('D:\\Cache\\conan\\packages\\zstd02e5ac4a878b3\\s\\src\\tests\\cli-tests\\bin\\unzstd', 'D:\\Cache\\conan\\packages\\t\\zstd4cb24a88a228a\\b\\src\\tests\\cli-tests\\bin\\unzstd', "[Errno 22] Invalid argument: 'D:\\\\Cache\\\\conan\\\\packages\\\\zstd02e5ac4a878b3\\\\s\\\\src\\\\tests\\\\cli-tests\\\\bin\\\\unzstd'")]
	Error copying sources to build folder
	PS D:\Builds> conan --version
	Conan version 2.0.1
	PS D:\Builds> python.exe --version
	Python 3.11.2
	PS D:\Builds>

**Comment by memsharded** [comment]
This is really weird.
Maybe you have some antivirus SW or something like that, that could be somehow blocking access to some file (it is surprising that it always fail at the ``unzstd`` file)? Can you check adding an exclusion for it? Also, we have had glitches in the past in Windows, with the Windows indexer, and the solution was to also exclude the Conan cache folder from indexing.

**Comment by sakra** [comment]
The whole volume D: is already excluded. 

I was finally able to resolve the issue by deleting the conan package cache and reinstalling zstd.

Thanks for looking into it.

**Comment by memsharded** [comment]
Thanks for following up and reporting. Yes, I guess it was a Windows filesystem glitch, maybe something was broken the first time of zstd installation, and it was corrupted and that was causing the issue. 
If it happens again, please let us know.

**Comment by zhuoqiang** [comment]
@memsharded I have the same issue when installing `zstd/1.5.5`, it complains `no such file or directory` for `unzstd` as well.

the `unzstd` is actually there however it is a softlink. and the filesystem of CONAN_HOME is not a native filesystem (a Linux VM accessing the Mac OS host shared folder), after I moved the CONAN_HOME to native filesystem the error are gone.

I believe it is due to softlink handling on non-native filesystem path / directory.

**Comment by memsharded** [comment]
HI @zhuoqiang 

This ticket was closed, it also was reported against Windows, so this might be a slightly different thing.
It would be better if you create a new issue with details instructions on how to reproduce it, including the Conan version, the exact commands used, etc. Thanks!

**Comment by Nekto89** [comment]
> [@memsharded](https://github.com/memsharded) I have the same issue when installing `zstd/1.5.5`, it complains `no such file or directory` for `unzstd` as well.
> 
> the `unzstd` is actually there however it is a softlink. and the filesystem of CONAN_HOME is not a native filesystem (a Linux VM accessing the Mac OS host shared folder), after I moved the CONAN_HOME to native filesystem the error are gone.
> 
> I believe it is due to softlink handling on non-native filesystem path / directory.

Just in case if anyone would come here from google with the same issue. I've got this error while trying to use Colima + Docker on macOS. CONAN_HOME was in subfolder of mounted folder. It didn't work from the box but it started working after changing `mountType: sshfs` to `mountType: virtiofs` in `/Users/<username>/.colima/default/colima.yaml` + `colima restart`
