### ISSUE TITLE
"Path too long" while unpacking jfrog-artifactory-cpp-ce

### ISSUE THREAD

**Issue by travnick** [conan-io/conan#13371]
Not sure if it's the right place to file this issue, but I'm unable to unzip the Artifactory package for Windows because of "Path too long"

[jfrog-artifactory-cpp-ce-7.49.6-windows.zip](https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/cpp/ce/jfrog-artifactory-cpp-ce/[RELEASE]/jfrog-artifactory-cpp-ce-[RELEASE]-windows.zip)
![image](https://user-images.githubusercontent.com/619590/216411600-3a960bb3-3d2a-43f4-bd76-ec71e2f77384.png)

**Comment by memsharded** [comment]
Hi @travnick 

thanks for your question.
yes, this does not a Conan issue per se, neither an Artifactory issue.
If you want to run Artifactory in Windows, you might need to activate the system capability of handling long paths, which version of Windows are you running? Have you tried that?

**Comment by memsharded** [comment]
Just FYI, I have been able to download and unzip that version in a Windows10 (base folder something short like ``c:/ws/artifactory``). I am seeing some long paths like 
``C:\ws\artifactory\artifactory-cpp-ce-7.49.6\app\frontend\bin\server\dist\microfrontendStaticFallback\runtime\umd\js``, but not that large that they would hit the path limit of Windows.

**Comment by travnick** [comment]
That was my first try after an error, but unpacking at `d:\` also failed, so I filed the issue (Windows 10).
Didn't try to activate long paths yet.

--- edit
It is Windows Server 2016

--- edit 2
7-Zip managed to unpack the archive. System build in unzip is not able to do that since "path too long"

**Comment by memsharded** [comment]
any update here @travnick ? did you manage to unpack artifactory?
It seems the Windows server might have a limitation in the path length, I am not so sure that windows server 2016 allows long path, I am pretty sure that Windows 10 does it, but no idea about the other.

**Comment by travnick** [comment]
@memsharded As mentioned, I did it with 7-Zip, and it's running.

**Comment by memsharded** [comment]
Ok, perfect, thanks for the feedback, I missed that edit.

I think we can close this issue.
