### ISSUE TITLE
[question] Conan 2.0 how to lock options

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#13389]
### What is your question?

Hey, I have a question regarding locking options in Conan 2.0. 

In Conan 1.X, the options were part of the lockfiles. In Conan 2.0 they aren't. So how would I achieve to get the exact same package when reproducing a build using lockfiles and the profile, which is defining the options, might has changed in the meantime?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nicosmd 

Thanks for your question.

The lockfiles have been greatly simplified in 2.0, while getting more power. It is true that they are not storing the profiles inside the lockfile, but that solves a lot of problems and challenges there were in 1.X. Lockfiles in 2.0 have consolidated to something way closer to what other package managers to: a lockfile is locking versions (and revisions, in the conan case), but nothing more. The format is pretty simple, you can open the files and they will be very evident. The different options are part of the configuration, and as described in the docs, lockfiles in Conan 2.0 can be used 1 lockfile to lock multiple configurations, which was one of the major points in 1.X. Then the options definitions are still in the profiles. You use the different profiles and the 1 lockfile, and you will get the same exact dependency graphs you did in the past.

If you want to have stability and traceability over the profiles, that is the reason why the ``conan config install`` is there, to be able to manage them from a git repo or http versioned archive.

For some extreme cases, it might be possible to use the ``--lockfile-packages``, but that option is not even documented in the docs, we are not sure if we would even document it, it is super experimental. Most likely it shouldn't be necessary, I wouldn't recommend even considering it at this point.

**Comment by nicosmd** [comment]
Hey @memsharded, 
thanks for your answer. That makes absolutely sense and I really like the new lockfile concept. We haven't used them before, but now, since they become that simple, we want to use them in our CI/CD. 

I think stability and traceability of the profiles is exactly what we need. Is there maybe already some best practice how to manage profile properly? We are currently just always installing the latest master commit of our profile repository, but this does not feel very traceable or stable. So you're saying that we maybe need to specify the exact commit of the profiles repository in our Jenkinsfiles to achieve better stability? Or would it maybe make sense to store the profiles repo commit in the exported conan_data of a package via hooks or something?

**Comment by memsharded** [comment]
> I think stability and traceability of the profiles is exactly what we need. Is there maybe already some best practice how to manage profile properly? We are currently just always installing the latest master commit of our profile repository, but this does not feel very traceable or stable. So you're saying that we maybe need to specify the exact commit of the profiles repository in our Jenkinsfiles to achieve better stability? Or would it maybe make sense to store the profiles repo commit in the exported conan_data of a package via hooks or something?

Yes, totally, the profiles and the rest of the Conan configuration deserves to be properly versioned, especially now that there are also more extension points as ``compatibility.py``, profile-plugin, etc.
You can use tags in github too, and it might make sense to use some ``semver`` compatible approach, so you know that some new version of the configuration is incremental and not breaking, some might be adding new stuff but not breaking and some might be breaking.

There are some ideas to allow putting the config inside conan packages and leverage version ranges for installation, and other similar ideas, but very preliminary. But coupling in both directions, like putting the profiles repo commit in the recipes would not be great, it would probably introduce more issues than it solves. You might definitely store the reference to the config together with the lockfiles if they are not in repos that create packages (only in repos that consume packages)

**Comment by nicosmd** [comment]
Thank you very much! This gives me much more clarity, where it's the right place to version the options.

**Comment by memsharded** [comment]
Great. Keep tuned to our releases, the release mailing list or social, if new features in 2.X are released focused on versioning the configuration, it will be properly announced.
