### ISSUE TITLE
conan remove -r conan.io leads to error message on web site

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#134]
I removed an obsolete version of my library from the central package server:
```sh
 conan remove -r conan.io silicium/0.2
```
At the moment you can still find this version by searching for its name (https://www.conan.io/search?q=silicium), but when I open it I see this:
![error](https://cloud.githubusercontent.com/assets/941829/12764542/b7402c58-c9fa-11e5-8bc4-022f9ddb9adf.png)

EDIT: A few minutes later it is no longer among the search results. The error message is the same. There are actually two issues here:
* search takes a few minutes to update after an upload or remove
* The web site does not handle unknown package references gracefully (another example: https://www.conan.io/source/has/1.0/never/existed)

**Comment by lasote** [comment]
Fixed. Will be available soon.
