### ISSUE TITLE
[feature] CMAKE_VERBOSE_MAKEFILE injection via conf (or other way to increase CMake verbosity)

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#13406]
### What is your suggestion?

 ```
"tools.microsoft.msbuild:verbosity": "Verbosity level for MSBuild: 'Quiet', 'Minimal', 'Normal', 'Detailed', 'Diagnostic'",
"tools.apple.xcodebuild:verbosity": "Verbosity level for xcodebuild: 'verbose' or 'quiet",
```

Already exist, but none for CMake, but it can be very convenient to increase it for debugging.
I guess we might want to apply a verbosity level for all build systems if possible?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by SpaceIm** [comment]
I've also asked for this feature in https://github.com/conan-io/conan/issues/12239
