### ISSUE TITLE
[question] Migrating recipe to 2.0 : missing include directories for transitive dependencies

### ISSUE THREAD

**Issue by ATS-AValli** [conan-io/conan#13408]
### What is your question?

Hi.
I'm trying to migrate existing recipes to Conan 2.0.1 and I'm having problem with transitive dependencies, regarding header files.

First of all, the overall scheme for the involved recipes is:
using CMakeToolchain and CMakeDeps generators, in layout() method the cmake_layout helper; in build() the CMake helper object.

Let's say packages are A, B and C. Package B depend on A, package C depend on B (and implicitly, A).  When I try to compile package C, it finds the includes for package B  but not A.

In the corresponding CMakeLists.txt for package C, there's a direct target_link_libraries() for the package B, as "B::B" .

When CMake is configuring the build for package C , I get:

```
-- Conan: Target declared 'B::B'
-- Conan: Target declared 'A::A'

```
so it seems transitive dependencies are caught.
Moreover, in `CMAKE_INCLUDE_PATH` _all_ the required includes are available, so for now as a (ugly) workaround I've added 
`target_include_directories(<target_for_package_C> PUBLIC ${CMAKE_INCLUDE_PATH})` 

The same recipes were working (before porting them to 2.0) and all paths were configured correctly.

The `package_info()` method for package B has very little (maybe too little ?):
```
        self.cpp_info.libs = ["B"]
        self.cpp_info.set_property("cmake_build_modules", [<some modules>])
        self.cpp_info.system_libs.append("bfd")

```

and of course in the `requires:` of package B there's package A.

Any help is appreciated.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by ATS-AValli** [comment]
This in fact was answered by https://github.com/conan-io/conan/issues/13308
I wish there was a mention about that in the migration guide.

**Comment by memsharded** [comment]
Glad that you found a solution in https://github.com/conan-io/conan/issues/13308.

Indeed, there is still a lot of documentation to complete, we are trying to keep working on it, but there are many other priorities as well, so it takes time.
