### ISSUE TITLE
[question] Refer to CONAN_HOME from global.conf

### ISSUE THREAD

**Issue by tonichedgehog** [conan-io/conan#13419]
### What is your question?

Hi, I have a question on how to refer to CONAN_HOME from global.conf. 

I distribute a custom cacert file using `conan config install`, and would like to point the `core.net.http:cacert_path` setting to that file, preferably within the conan home directory.

Giving a relative path doesn't seem to work. I suppose I could use something like `{{os.getenv("CONAN_HOME")}}/my_ca_certs.pem`,  but I can't rely on that environment variable to be set explicitly.

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by gpxricky** [comment]
Hi @tonichedgehog

this will be solved in Conan 2.0.2. Refer to #13415 for details.

**Comment by memsharded** [comment]
Thanks for the hint @gpxricky!

yes, this would be closed by #13415, where ``conan_home_folder`` will be available as variable for jinja.
