### ISSUE TITLE
[bug] test_package of a conan 2.0 shared library package doesn't find shared library on Windows when using conan 1.58.0

### ISSUE THREAD

**Issue by joergbrech** [conan-io/conan#13416]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: MSVC 17 2022
* Conan version: 1.58.0 / 2.0.1
* Python version: 3.10.6

### Steps to reproduce

1. Create a new conan package using conan 2.0.1 with 
  
   ```
   conan new cmake_lib -d name=test -d version=0.1.0
   ```

2. Make sure you to build a shared library, e.g. by changing the corresponding default option in the `conanfile.py`
 
   ```
   default_options = {"shared": True, "fPIC": True}
   ```

3. Running `conan create .` with conan 2.0.1 will create and test the package successfully.
4. Running `conan create .` with conan 1.58.0 will create the package successfully, but will not find `test.dll` at the `test_package` stage.

I would have expected that I can create and test Conan 2.0 packages using Conan 1.x. Adding `test_type = "explicit"` to the test_package conanfile.py doesn't help either ([test_type = "explicit"](https://docs.conan.io/en/1.59/migrating_to_2.0/recipes.html#changes-in-the-test-package-recipe))

I have no issues on Ubuntu 20.04 by the way.

### Logs

```
ERROR: test/0.1.0 (test package): Error in test() method, line 27
        self.run(cmd, env="conanrun")
        ConanException: Error 3221225781 while executing Release\example
```

Also, a Windows error dialog pops up, stating `test.dll` cannot be found.

**Comment by memsharded** [comment]
Hi @joergbrech 

Thanks for your question.
I think this is expected.
The templates in ``conan new`` 2.0 have dropped the explicit instance of ``VirtualXXXEnv`` generators. So they won't work transparently backwards, it is not expected.

You have the ``[conf]`` ``tools.env.virtualenv:auto_use=True`` to get the same behavior in 1.X.

**Comment by joergbrech** [comment]
Ah ok, got it! Setting the configuration solved the issue for me. Thanks for the quick help!

So in essence, I should 

```
conan profile update conf.tools.env.virtualenv:auto_use=True default
```

if I want to use shared libraries in Conan 2 packages in 1.X?

**Comment by memsharded** [comment]
> if I want to use shared libraries in Conan 2 packages in 1.X?

Yes, that is correct, but not only for shared libraries, there could be other reasons, env-vars from tool-requires, etc, that might be necessary. Either setting the ``auto_use`` or explicitly defining the ``VirtualBuildEnv`` and ``VirtualRunEnv`` generators.

**Comment by joergbrech** [comment]
Ok, thanks for the info. I suppose this can be closed then.
