### ISSUE TITLE
[question] Shall package_folder be empty in conans.model.conanfile_interface.Conanfileinterface class?

### ISSUE THREAD

**Issue by dotChris90** [conan-io/conan#13426]
### What is your question?

Hello conan team!, 

i have a question related to the conanfileinterface model. 

I was following the instructions from https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html

and i debugged it and want to understand how to write my own deployer (e.g. collecting header files of all dependencies and spit out to destination to that vs code can use this headers for linting). 

But when debugging the example i was seeing that a dep data structure doesnt have any value in package_folder but i was expecting it has a value. ... 

see 
![2023-03-13_13h47_31](https://user-images.githubusercontent.com/33638852/224708468-95d9aff7-d25a-4d94-9f19-fef5db989776.png)

My question is now - is this desired behaviour and i did i miss sth or bug? 

My expectation was sth like "~/.conan2/boost3700b9e829477/p/" and this folder has sub folders "include", "lib" and "licenses" 

### Have you read the CONTRIBUTING guide?

- [] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @dotChris90 

Thanks for your question.

I am not sure, but is it possible that you are calling ``conan graph info`` instead of ``conan install``?
Because the first will not install binaries, only compute the dependency graph. But as the binaries are not there, then the ``package_folder`` will be undefined. If you run ``conan install``, then ``package_folder`` should be defined.

**Comment by dotChris90** [comment]
@memsharded thanks for this hint >.< that was my own mistake - yes if i use conan install - all works proper - i didnt see that deployer are also able for other commands.

thanks for pointing it out.

**Comment by memsharded** [comment]
Yes, the deployers were initially for ``conan install`` only, but then we saw that they can have some partial applicability to gather info from the graph quickly, even if the binaries are not installed, so we extended it to ``graph info`` too, but it is necessary to be aware of that.
