### ISSUE TITLE
[question][V2] Is build_policy ignored or am I using it wrong?

### ISSUE THREAD

**Issue by ASil-Scanway** [conan-io/conan#13422]
### What is your question?

Hello.

I'm rather new to Conan and starting with v2. I'm trying to migrate from using `conanfile.txt` to `conanfile.py`.
Previously I was using option `--build=missing` while installing configuration for my project. 

When setting `build_policy="missing"` in `.py` file it seems to be ignored - `conan install .` results in an error `ERROR: Missing prebuilt package for 'libmysqlclient/8.0.31', [...]`

Is it a bug or am I doing something wrong?

`conanfile.py`

```python
from conan import ConanFile
from conan.tools.cmake import cmake_layout


class AcquisitionRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"
    build_policy = "missing"  # seems to be ignored :(

    def requirements(self):
        self.requires("fmt/9.1.0")
        self.requires("cppzmq/4.9.0")
        self.requires("nlohmann_json/3.11.2")
        self.requires("poco/1.12.4")

    def layout(self):
        cmake_layout(self, generator="Ninja")
```
`profile`
```
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=14
compiler.version=15
os=Windows

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

`conan install . `
```bash
======== Installing packages ========
ERROR: Missing binary: libmysqlclient/8.0.31:3fca54a8709df23a457ac03778cc86be002fb61a
ERROR: Missing binary: libpq/14.5:8a73d28bb63b58e1c2af722f2fb1129cf2864fb1
ERROR: Missing binary: openssl/1.1.1t:0bc740541dbb1ac40d21346b486a1a4a78bed8a9
ERROR: Missing binary: pcre2/10.42:47e42ab8c860d9d35c3a9c89a59aca38374d0ba7
ERROR: Missing binary: poco/1.12.4:a6fc399dea03d3909f6d2cc062b88466ffc4b615

libpq/14.5: WARN: Can't find a 'libpq/14.5' package binary '8a73d28bb63b58e1c2af722f2fb1129cf2864fb1' for the configuration:
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.version=15
os=Windows
[options]
shared=False
with_openssl=False

ERROR: Missing prebuilt package for 'libmysqlclient/8.0.31', 'libpq/14.5', 'openssl/1.1.1t', 'pcre2/10.42', 'poco/1.12.4'
Check the available packages using 'conan list libpq/14.5:* -r=remote'
or try to build locally from sources using the '--build=missing' argument
```

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aleksander-sil 


Thanks for your question.

The ``build_policy = "missing"`` is a policy for the current package, not for the dependencies. It is used for a certain type of packages that will not work locally if it is not built from sources in the current machine (some drivers and low level things), and typically used with the ``upload_policy = "skip"`` to avoid uploading the locally compiled binaries.

But for the dependencies, it is necessary to pass the ``--build=missing`` command line argument.

**Comment by ASil-Scanway** [comment]
@memsharded Thank you for clarification. This answer resolves the issue.
