### ISSUE TITLE
[question] In requirements, what's the difference between using "override=True" and not using it ?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#13436]
### What is your question?

Suppose this circumstances:
ERROR: Conflict in boost/1.75.0:
    'boost/1.75.0' requires 'zlib/1.2.13' while 'ald/0.1.5' requires 'zlib/1.2.12'.

Should I use self.requires("zlib/1.2.13") or self.requires("zlib/1.2.13", override=True)? How would this parameter take effect?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

The ``override=True`` doesn't create a real dependency to the required package, it only changes the version of the transitive dependencies, if such transitive dependency exist, otherwise is a no-op, no dependency happens. While not using ``override`` introduces an actual direct dependency to that package.

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed
> 
> The `override=True` doesn't create a real dependency to the required package, it only changes the version of the transitive dependencies, if such transitive dependency exist, otherwise is a no-op, no dependency happens. While not using `override` introduces an actual direct dependency to that package.

But when such kind of conflict happen, for example A require C/0.1, B require C/0.2, the correct way is using `self.requires("C/0.X", override=True)` according to your answer. But when I not use override it can still resolve that conflict, is it the right way to solve conflict too?

**Comment by memsharded** [comment]
> But when such kind of conflict happen, for example A require C/0.1, B require C/0.2, the correct way is using self.requires("C/0.X", override=True) according to your answer. But when I not use override it can still resolve that conflict, is it the right way to solve conflict too?

No, because it introduces an artificial dependency to C/0.X, making the consumer to unnecessary link and depend directly on C/0.X

**Comment by Tumb1eweed** [comment]
> > But when such kind of conflict happen, for example A require C/0.1, B require C/0.2, the correct way is using self.requires("C/0.X", override=True) according to your answer. But when I not use override it can still resolve that conflict, is it the right way to solve conflict too?
> 
> No, because it introduces an artificial dependency to C/0.X, making the consumer to unnecessary link and depend directly on C/0.X

By adding this artificial dependency, does A and B would redirect to C/0.X?

**Comment by memsharded** [comment]
In Conan 1.X, yes, in Conan 2.0 it is necessary to define either the ``force=True`` trait for direct dependencies or the ``override=True`` for transitive dependencies.
