### ISSUE TITLE
[question] conan2: How to export custom FindXXX.cmake so that it can be found and used by other package?

### ISSUE THREAD

**Issue by mjb6** [conan-io/conan#13442]
### What is your question?

Hi,

my custom component "engine" has a custom `FindEngine.cmake` file. I want to create a conan package for this component.
Another component shall use "engine" as requries. How can I do this with conan2?

I tried this recipe and called `conan export-pkg` for the following folder structure:
- FindEngine.cmake
- some folders with prebuilt files and headers
- conanfile.py:
```
 from conan import ConanFile
 from conan.tools.files import copy

 class EngineConan(ConanFile):
     name = "engine"
     version = "6.3.17"
     build_policy = "never"

     def package(self):
         copy(self, "*", ".", self.package_folder)

     def package_info(self):
         self.conf_info.append("tools.cmake.cmaketoolchain:find_path", self.package_folder)
```

My consumer package has a requires to `engine/6.3.17`. The consumer CMakeLists.txt has a `find_package(Engine 3.6.17 REQUIRED)`.
My consumer conanfile uses the CMakeDeps and CMakeToolchain generator. When running `conan create`, it cannot find the FindEngine.cmake.

When running `conan install`, I see that the generated files do not contain anything that appends the package folder engine/3.6.17 to `CMAKE_MODULE_PATH`.

How can I tell conan that it shall append to CMAKE_MODULE_PATH the package folder of engine (where the FindEngine.cmake is located), when engine is used as requires?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mjb6 

Thanks for your question.
For the modern ``CMakeDeps`` generator on the consumer side you could try:

- Define in your recipe ``self.cpp_info.set_property("cmake_find_mode", "none")``. That means, no Conan config.cmake file will be generated in the consumer side, but only the path will be added to ``conan_toolchain.cmake`` by ``CMakeToolchain`` so your file can be located
- Need to define the ``self.cpp_info.builddirs = ["."]`` (or pointing to the directory you package your cmake file in.

You should be able to test this in your ``test_package`` folder of the ``engine`` package. In Conan 2.0 it will also run when executing the ``conan export-pkg`` command.

Also:
- ``cmaketoolchain:find_path`` does not exist you cannot do that

**Comment by mjb6** [comment]
Thanks a lot, this works fine!

For reference, here is my final recipe:
```python
from conan import ConanFile
from conan.tools.files import copy

class EngineConan(ConanFile):
    name = "engine"
    version = "6.3.17"
    build_policy = "never"

    def package(self):
        copy(self, "*", ".", self.package_folder)

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.builddirs = ["."]
```
