### ISSUE TITLE
[feature] AutotoolsToolchain: define environment when building for Android

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#13443]
### What is your suggestion?

When targetting Android and building something that requires Autotools, we need to define `CC`, `CXX`, etc, as described here: https://developer.android.com/ndk/guides/other_build_systems

if `os=Android`, if `os.api_level`  and `tools.android:ndk_path` are defined in the profile, we have enough information to derive the correct environment variables as per the Android NDK documentation. 

Currently `tools.android:ndk_path` is sufficient for `CMakeToolchain`, but not for Autotools, resulting in having to define additional variables in the profile. We could consider doing this implicitly.

See: https://github.com/conan-io/conan/issues/13373#issuecomment-1468193058

**Comment by SpaceIm** [comment]
> We could consider doing this implicitly.

Is it really the responsibility of conan build helpers to do babysitting of cross-compilers (I mean set CC, CXX, STRIP, AR, LD, RANLIB etc, I thought it was always the responsibility of user profiles)? I'm wondering if it will not lead to crazy expectations while using conancenter recipes based on custom build systems.
It may also break `android-ndk` recipe depending on how it's implemented.
