### ISSUE TITLE
[bug] lockfile options are overridden by config_options

### ISSUE THREAD

**Issue by AtnNn** [conan-io/conan#13451]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: N/A
* Conan version: 1.59.0
* Python version: 3.11

### Steps to reproduce

With `conanfile.py`

```
from conans import ConanFile
class MWE(ConanFile):
    requires = "libcurl/7.88.1#923efa6a87100fae3bdcff13b226b7ed"
    def configure(self):
        self.options["libcurl"].with_ssl = "schannel"
```

and `profile.txt`

```
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=16
compiler.toolset=v141
```

and a lock file:

```
$ conan lock create conanfile.py --profile profile.txt
```

As expected, the lock file contains `"options": "...\nwith_ssl=schannel\n...",` and does not contain `openssl`.

But `conan info` and `conan install` still expect to see `openssl`:

```
$ conan info libcurl/7.88.1@#923efa6a87100fae3bdcff13b226b7ed --lockfile conan.lock
ERROR: Require 'openssl' cannot be found in lockfile
$ conan install libcurl/7.88.1@#923efa6a87100fae3bdcff13b226b7ed --build libcurl --lockfile conan.lock
ERROR: Require 'openssl' cannot be found in lockfile
```

However the [`libcurl` recipe](https://conan.io/center/libcurl?version=7.88.1&tab=recipe) should not depend on `openssl` in this case:

```
    def requirements(self):
        if self.options.with_ssl == "openssl":
            self.requires("openssl/1.1.1t")
```

### Logs

```
{
 "graph_lock": {
  "nodes": {
   "0": {
    "options": "libcurl:shared=False\nlibcurl:with_brotli=False\nlibcurl:with_c_ares=False\nlibcurl:with_ca_bundle=auto\nlibcurl:with_ca_path=auto\nlibcurl:with_cookies=True\nlibcurl:with_crypto_auth=True\nlibcurl:with_dict=True\nlibcurl:with_docs=False\nlibcurl:with_file=True\nlibcurl:with_ftp=True\nlibcurl:with_gopher=True\nlibcurl:with_http=True\nlibcurl:with_imap=True\nlibcurl:with_ipv6=True\nlibcurl:with_largemaxwritesize=False\nlibcurl:with_ldap=False\nlibcurl:with_libidn=False\nlibcurl:with_libpsl=False\nlibcurl:with_librtmp=False\nlibcurl:with_libssh2=False\nlibcurl:with_mqtt=True\nlibcurl:with_nghttp2=False\nlibcurl:with_ntlm=True\nlibcurl:with_ntlm_wb=True\nlibcurl:with_pop3=True\nlibcurl:with_proxy=True\nlibcurl:with_rtsp=True\nlibcurl:with_smb=True\nlibcurl:with_smtp=True\nlibcurl:with_ssl=schannel\nlibcurl:with_symbol_hiding=False\nlibcurl:with_telnet=True\nlibcurl:with_tftp=True\nlibcurl:with_threaded_resolver=True\nlibcurl:with_unix_sockets=True\nlibcurl:with_verbose_debug=True\nlibcurl:with_verbose_strings=True\nlibcurl:with_zlib=True\nlibcurl:with_zstd=False\nzlib:shared=False",
    "requires": [
     "1"
    ],
    "path": "conanfile.py",
    "context": "host"
   },
   "1": {
    "ref": "libcurl/7.88.1#923efa6a87100fae3bdcff13b226b7ed",
    "options": "shared=False\nwith_brotli=False\nwith_c_ares=False\nwith_ca_bundle=auto\nwith_ca_path=auto\nwith_cookies=True\nwith_crypto_auth=True\nwith_dict=True\nwith_docs=False\nwith_file=True\nwith_ftp=True\nwith_gopher=True\nwith_http=True\nwith_imap=True\nwith_ipv6=True\nwith_largemaxwritesize=False\nwith_ldap=False\nwith_libidn=False\nwith_libpsl=False\nwith_librtmp=False\nwith_libssh2=False\nwith_mqtt=True\nwith_nghttp2=False\nwith_ntlm=True\nwith_ntlm_wb=True\nwith_pop3=True\nwith_proxy=True\nwith_rtsp=True\nwith_smb=True\nwith_smtp=True\nwith_ssl=schannel\nwith_symbol_hiding=False\nwith_telnet=True\nwith_tftp=True\nwith_threaded_resolver=True\nwith_unix_sockets=True\nwith_verbose_debug=True\nwith_verbose_strings=True\nwith_zlib=True\nwith_zstd=False\nzlib:shared=False",
    "package_id": "7e324a74ffbd012f06b1ae587f9ccb74de6c64db",
    "requires": [
     "2"
    ],
    "context": "host"
   },
   "2": {
    "ref": "zlib/1.2.13#13c96f538b52e1600c40b88994de240f",
    "options": "shared=False",
    "package_id": "6c6d4a9cf35f9c599858220dd6e2d3951493b05f",
    "context": "host"
   }
  },
  "revisions_enabled": true
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\ncompiler=Visual Studio\ncompiler.runtime=MD\ncompiler.toolset=v141\ncompiler.version=16\nos=Windows\n[options]\n[build_requires]\n[env]\n"
}
```

**Comment by memsharded** [comment]
Hi @AtnNn 

I think this is expected.
When you capture the lockfile for a given "root" of the graph, it cannot be arbitrarily applied to the dependencies in the middle of the graph.

The documentation in https://docs.conan.io/1/versioning/lockfiles/evolving.html explains that the application to the middle of the graph (``libcurl`` in this case), needs to be with:
```
$  conan lock create conanfile.py --lockfile=app_release.lock --lockfile-out=libb_deps_release.lock
```

But it cannot be done with 
```
$  conan info libcurl/7.88.1@#923efa6a87100fae3bdcff13b226b7ed --lockfile conan.lock
or 
$  conan install libcurl/7.88.1@#923efa6a87100fae3bdcff13b226b7ed --lockfile conan.lock
```

This has improved a lot in 2.0, it will be much easier to do these things.

**Comment by AtnNn** [comment]
Thanks @memsharded for your reply. Following the instructions in that article under "It is also possible to derive a partial lockfile for libb/1.0 without cloning the libb repository", I get the same issue (with a more useful error message):

```
$ conan lock create --reference=libcurl/7.88.1@#923efa6a87100fae3bdcff13b226b7ed --build=libcurl --lockfile conan.lock --lockfile-out libcurl.lock
libcurl/7.88.1: WARN: Require 'openssl' cannot be found in lockfile
ERROR: libcurl/7.88.1: Locked options do not match computed options
Locked options:
with_ssl=schannel
Computed options:
with_ssl=openssl
```

Migrating to Conan 2 is on my roadmap, but I'm not quite ready yet (lot's of old in-house recipes that need porting).

**Comment by memsharded** [comment]
I see. Apparently the lockfile usage without cloning cannot work with options different to the default ones. It seems that this would be one of the rough edges of lockfiles in 1.X that moved us to do a full re-write in 2.0 to simplify them. I am afraid that we might try to have a look, but it might be unlikely to get prioritized enough.

**Comment by AtnNn** [comment]
Tracing the code, I believe the issue is that `pre_lock_node` does `node.conanfile.options.values = locked_node.options` before the call to `conanfile.config_options()` in `run_configure_method`. This causes libcurl's `config_option` to override the options from the lock file, and contradicts the conanfile methods documentation which says "Values assigned in the `configure()` method cannot be overridden, while values assigned in `config_options()` can."

Would you be open to a PR to change that behaviour?

**Comment by memsharded** [comment]
Thanks for the offer to contribute, but please be aware that it is likely that this could be breaking behavior, we need to carefully consider it, and if there is risk of breaking existing users, it might not be possible to move it forward.

**Comment by AtnNn** [comment]
I've found a workaround that seems to work for my use case: instead of `self.options["libcurl"].with_ssl = "schannel"` in `configure`, I added the option to the profile:

```
[options]
libcurl:with_ssl=schannel
```

With that change, the option is added to the `host_profile` field in `conan.lock`.

**Comment by memsharded** [comment]
In fact, defining things in profiles is a good way to do this, not just a workaround. In our experience the less definition of options in recipes, the better, and having definition of options in profiles allows better control of this with less issues.

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
