### ISSUE TITLE
About packet id calculation rules

### ISSUE THREAD

**Issue by poapoauu** [conan-io/conan#13454]
What rules are used to calculate the package id of prefabricated packages in the program

**Comment by memsharded** [comment]
Hi @poapoauu 

Probably the video in https://docs.conan.io/2/knowledge/videos.html, is the best current resource explaining this. It will be added to the docs.

You might want to read these pages too:
- https://docs.conan.io/2/reference/conanfile/methods/package_id.html
- https://docs.conan.io/2/reference/extensions/binary_compatibility.html

**Comment by poapoauu** [comment]
Thank you

**Comment by memsharded** [comment]
If there are no further questions, I am closing this as responded, but please feel free to re-open or file new tickets if you have any further question. Thanks!
