### ISSUE TITLE
[feature] support require traits in `conanfile.txt`

### ISSUE THREAD

**Issue by CD3** [conan-io/conan#13452]
### What is your suggestion?

I think it would be great if the `conanfile.txt` file supported the new requires traits. I know that the documentation makes the case for using a `conanfile.py` instead: https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html, 
but the simplicity of putting a `conanfile.txt` at the root of a project _for development_ is _really_ convenient.

Specifically, I want to be able to specify the `override` trait for the requirements in a `conanfile.txt` to mimic the old behavior so that developers on the team that want to work on `libA` can just do a `conan install` to get started and not worry about the fact that some of `libA`'s dependencies updated to Boost 1.80, but some others did not.

I know that using a `conanfile.py` is more powerful, but if you don't need to do any conditional setup, using a `conanfile.txt` is very simple and easy to read.

From what I understand after looking at the source code, this would mean that:
1. The `ConanFile.requires(...)` method would need to support traits in the requires strings.
2. The `ConanfileTextLoader` would need to parse the requires strings before passing to `ConanFile.requires(...)`
3. `conanfile.txt` would need to add a section for specifying the requires traits.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @CD3 

Thanks for your suggestion.
But I am afraid this won't happen. The rationale is explained in https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html, and it clearly holds for this case. There is no point to invent a custom made DSL new txt-based language to do something that is documented, straightforward in Python, and will always cover all cases. This would be an endless rabbit hole, and we had the previous experience with the ``[imports]`` section in the 1.X that even the Conan team couldn't write properly without checking the docs.

We have even created a convenient custom command to translate conanfile.txt -> conanfile.py automatically in https://github.com/conan-io/conan-extensions. Closing this ticket as not planned, but thanks for the suggestion anyway!

**Comment by CD3** [comment]
Understood, thank you.
