### ISSUE TITLE
[bug] Conan1: tools.microsoft.is_msvc_static_runtime() always True

### ISSUE THREAD

**Issue by gouriano** [conan-io/conan#13464]
### Environment details

I create  package on Windows (Visual Studio 2019) using Conan 1.59.0 and I believe I see a bug in Conan.
The problem is that _is_msvc_static_runtime()_ always returns True.

I put the following code into _validate()_

    def validate(self):
        if tools.microsoft.is_msvc_static_runtime:
            print("static runtime")
        else:
            print("dynamic runtime")
        ...

and create package like this:

    conan create . -s compiler.runtime=MT

the recipe says "static runtime" and generated solution indeed uses Multi-threaded runtime libraries
I then use

    conan create . -s compiler.runtime=MD

the recipe again says "static runtime" and generated solution uses Multi-threaded DLL runtime libraries
That is, the solution is correct, but _is_msvc_static_runtime()_ is not. 
It seems I use it correctly, like described [here](https://docs.conan.io/1/reference/conanfile/tools/microsoft.html#conan-tools-microsoft-is-msvc-static-runtime)

**Comment by memsharded** [comment]
Hi @gouriano 

It seems you are missing the argument and the call
It is ``is_msvc_static_runtime(self), not ``is_msvc_static_runtime``. Please give that a try.

**Comment by gouriano** [comment]
OMG, You are right. Sorry for the noise

**Comment by gouriano** [comment]
not a bug

**Comment by memsharded** [comment]
NP! :)
