### ISSUE TITLE
[bug] using `include` in conan profiles dosen't get `[system_tools]`

### ISSUE THREAD

**Issue by FeignClaims** [conan-io/conan#13460]
### Environment details

* Operating System+version: MacOS Ventura 13.2.1
* Compiler+version: N/A
* Conan version: 2.0.2
* Python version: 3.11.2

### Steps to reproduce

1. Create a conan profile named `_common`:

  ```
  [conf]
  tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
  
  [system_tools]
  cmake/3.26.0
  ```

2. A profile named `default`:

  ```
  include(_common)
  
  [settings]
  arch=armv8
  build_type=Release
  compiler=clang
  compiler.cppstd=23
  compiler.libcxx=libc++
  compiler.version=15
  os=Macos
  ```

3. run `conan profile show -pr default`.

### Logs

Notice the `[system_tools]` part disappeared:
```
Host profile:
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.cppstd=23
compiler.libcxx=libc++
compiler.version=15
os=Macos
[conf]
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config

Build profile:
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.cppstd=23
compiler.libcxx=libc++
compiler.version=15
os=Macos
[conf]
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
```

**Comment by memsharded** [comment]
Hi @FeignClaims 

Thanks for your report.
I think you mean ``profiles`` not ``presets``? Because the ``presets`` is the CMake naming, it is a bit confusing.

If you mean ``profiles`` I think where the issue could be, indeed it could be a bug, please confirm and we will check.

**Comment by FeignClaims** [comment]
> I think you mean profiles not presets? Because the presets is the CMake naming, it is a bit confusing.

Yeah, it's `profiles`. Sorry for the confusion.

**Comment by FeignClaims** [comment]
> I think you mean profiles not presets? Because the presets is the CMake naming, it is a bit confusing.

Yeah, it's `profiles`. Sorry for the confusion.

**Comment by memsharded** [comment]
Found the issue, indeed a bug in the composition of profiles, was not doing the right thing for ``system_tools``. Proposed a fix for https://github.com/conan-io/conan/pull/13468 for the next patch release 2.0.3.

Thanks very much for reporting, the ``[system_tools]`` is experimental, so looking forward for feedback about it to stabilize it, please let us know how it goes.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/13468, will be in next 2.0.3
