### ISSUE TITLE
[question] target_include_directories with INTERFACE in conan

### ISSUE THREAD

**Issue by xuantambk** [conan-io/conan#13479]
### What is your question?

In normal CMake if i can just declare 1 lib have some INTERFACE dependencies then if any consumer link to `my_lib` it will automatically include the Interface include dir..

target_include_directories(my_lib
    INTERFACE
    ${CMAKE_CURRENT_SOURCE_DIR}/hearders_1
    ${CMAKE_CURRENT_SOURCE_DIR}/headers_2
)

How can i do that in conan when consumer now include only conanbuildinfo.cmake
So i can get rid of other dependencies header that my_lib required.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by tobiashienzsch** [comment]
You can set different include path in CMake depending on if your using an installed target or the source repo directly:

```cmake
target_include_directories(mylib
    INTERFACE
        $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/headers_1>
        $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/headers_2>

        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/headers_1>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/headers_2>
)
```

Here is the `CMakeLists.txt` and `conanfile.py` for one of our header-only libs:

- [CMakeLists.txt](https://github.com/ModernCircuits/mc-core/blob/main/src/CMakeLists.txt)
- [conanfile.py](https://github.com/ModernCircuits/mc-core/blob/main/conanfile.py)

It's not perfect yet for conan v2, but most things work.

**Comment by xuantambk** [comment]
I tried and it not working, I dont know if you understand my question but changing in CMakeList.txt of main package does not help because the consumer package will completely not known anything about it..  CMake setup of main package.
I also dont see you use conanbuildinfo.cmake so may be it not same use case here.

Anyway i fixed the issue by provide more header_path_1 and header_path_2 in cpp_info.includirs 
``` python 
self.cpp_info.includedirs = "include", \
    "include/header_path_1/includes", \
    "include/header_path_2/includes"
