### ISSUE TITLE
[question] How to remove all revisions except latest?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13475]
### What is your question?

conan documentation says that `latest` is a special keyword in several commands, but in `conan remove` there are only examples explaining how to remove latest and keep old revisions (unlikely the most common use case).
How to achieve the opposite: remove all revisions of a given reference except latest?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @SpaceIm,

Thanks for the question.  We have an example of a custom command in the documentation to do exactly that: https://docs.conan.io/2/examples/extensions/commands/clean/custom_command_clean_revisions.html#examples-extensions-commands-clean-revisions
You can check the implementation here: https://github.com/conan-io/examples2/tree/main/examples/extensions/commands/clean

Anyway, I'm marking this for the next release, and we will consider adding a built-in pattern in Conan to accept this in the `conan remove` command.

Hope this helps!

**Comment by SpaceIm** [comment]
Thanks @czoido, the custom command example helped a lot. And as you said I agree a native support of such command would be very useful

Supporting negation of latest may also help in some circumstances:
Remove all RREV except latest: `conan remove *#!latest`
Remove all PREV except latest: `conan remove *:*#!latest`

Or introduce `outdated` keyword?
Remove all RREV except latest: `conan remove *#outdated`
Remove all PREV except latest: `conan remove *:*#outdated`

**Comment by memsharded** [comment]
Added the ``!latest`` syntax to patterns, will be in 2.0.3

**Comment by SpaceIm** [comment]
Thanks !
