### ISSUE TITLE
[bug] Fail to link fmtlib in Debug mode while successful in Release mode

### ISSUE THREAD

**Issue by allencho1222** [conan-io/conan#13476]
### Environment details

* Operating System+version: Ubuntu 20.04 (5.4.0-144-generic)
* Compiler+version: GCC (12.2.0)
* Conan version: 2.0.2
* Python version: 3.9.13
* Cmake version: 3.26.0
* conan profile
```
Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
```
* conanfile.txt:
```
[requires]
fmt/9.1.0
spdlog/1.11.0
boost/1.81.0
yaml-cpp/0.7.0

[generators]
CMakeDeps
CMakeToolchain
```

* CMakeLists.txt in project root directory (/project)
```
cmake_minimum_required(VERSION 3.12)
project(XXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
# print SPDLOG_TRACE
add_definitions(-DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE)


find_package(Boost REQUIRED)
find_package(fmt REQUIRED)
find_package(spdlog REQUIRED)
find_package(yaml-cpp REQUIRED)

add_subdirectory(${CMAKE_SOURCE_DIR}/src)
```

* CMakeLists.txt in src directory (/project/src)
```
cmake_minimum_required(VERSION 3.12)

file(GLOB_RECURSE SIM_SRCS CONFIGURE_DEPENDS *.cpp)
add_executable(XXX ${SIM_SRCS})
target_include_directories(XXX
  PRIVATE XXX
  PRIVATE XXX
  PRIVATE XXX
  PRIVATE XXX
  PRIVATE XXX
  PRIVATE XXX)
target_link_libraries(XXX
  Boost::program_options
  fmt
  spdlog::spdlog
  yaml-cpp
)
target_compile_options(XXX PRIVATE -Wall -O3 -g)
```
(XXX is not important)

### Steps to reproduce

Executes (failed):

1.  `conan install ./ --output-folder=build --build=missing --settings=build_type=Debug`
2. `cd build`
3. `cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Debug`
4. `make -j`

Executes (success):

1.  `conan install ./ --output-folder=build --build=missing`
2. `cd build`
4. `cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release`
5. `make -j`

### Logs

[100%] Linking CXX executable XXX
/usr/bin/ld: cannot find -lfmt
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/XXX.dir/build.make:1061: src/XXX] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: src/CMakeFiles/XXX.dir/all] Error 2

`conan install` and `cmake` work perfectly, but `make` fails to link `fmtlib` in debug mode.

It seems that conan should link `libfmtd (-lfmtd)` instead of `libfmt (-lfmt)`:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/14326227/226111172-2cb7b426-bc0e-455b-9d9b-1ee4db4aa665.png">

**Comment by memsharded** [comment]
Hi @allencho1222 

Quick suggestion: have you tried to completely remove the ``build`` folder before the Debug build? Because the way you are using it, it might reuse the previous CMake temporary files and link incorrectly. I'd suggest:

- Removing the "build" folder completley
- Using a different ``--output-folder``
- Or better, define a:
```
[layout]
cmake_layout
```
in your ``conanfile.txt``, that will take care automatically to use different folder for the different configurations, without needing to pass the ``--output-folder`` in the command line.

**Comment by allencho1222** [comment]
Hi, @memsharded 

I tried your solutions (1. remove build directory and use different output directory, 2. use `cmake_layout`).
(I also removed package directory and re-built packages using `--build=missing`).

However, conan still fails to link fmtlib.

Here's my output from compilation process (I did not use `cmake_layout` here).

[compilation.txt](https://github.com/conan-io/conan/files/11010184/test.txt)

**Comment by memsharded** [comment]
Thanks for the feedback.
Having a look to the ``test_package`` of the ``fmt`` recipe, I see this:
```cmake
if(FMT_HEADER_ONLY)
    target_link_libraries(test_package PRIVATE fmt::fmt-header-only)
else()
    target_link_libraries(test_package PRIVATE fmt::fmt)
endif()
```
So it could be that you are using the wrong target? could you please try using the ``fmt::fmt`` target?

**Comment by allencho1222** [comment]
Hi, @memsharded 

`fmt::fmt` works correctly.

Thank you.

**Comment by memsharded** [comment]
Perfect, thanks for reporting!
