### ISSUE TITLE
[bug] Same package id computed for two variants although should be different

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#13471]
### Environment details

* OS: Ubuntu Linux
* Conan version: 1.47
* Python version: 3.8.2

### Steps to reproduce

We have a recipe for a package like this:

```
from conans import ConanFile
     	
class MyPackage(ConanFile):
    name = "mypkg"
    requires = (("other-pkg/2.2.4@ci/stable", "private"), )

    # ATTENTION: Below code seems not to work. If the below mentioned requirement is not available in local cache nothing
    #                     happens, no complaints but also no download is tried by Conan client. Alternative is the 
    #                     requires attribute  mentioned above.
    #def requirements(self):
    #    # Setting this as private dep so that the package is not downloaded when installing this package
    #   # But private dependencies still influence the package id according to some github conan posts
    #    self.requires("other-pkg/2.2.4@ci/stable", private=True)

    def package_id(self):
        self.info.requires["other-pkg"].full_package_mode()
```
Now we are running twice an export-pkg:
- Once with host profiles where variant 1 of "other-pkg" is used.
- Once with host profiles where variant 2 of "other-pkg" is used.

What I am trying to achieve is that dependending on the chosen variant (via os setting) of other-pkg mypkg gets a different packageid because I want to achieve that for every variant of other-pkg I also get a variant (=different packageid) of mypkg. According to the docs "full_package_mode()" should achieve this.

But my logs show me that I always get the same packageid for both export-pkg commands.

**Comment by memsharded** [comment]
Hi @MTomBosch 

Thanks for your report.
Your conanfile seems incorrect:
- Bad indentation
- You are defining  a ``requires`` in the ``config()`` method, not in the ``requirements()`` method. This is not allowed.

Not saying that this is causing the issue. If you could share the following, that could help:
- The 2 full logs of the 2 ``export-pkg`` commands
- The ``conaninfo.txt`` inside the Conan cache that is created for the ``mypkg`` after the ``export-pkg``

**Comment by MTomBosch** [comment]
Sorry for the bad indentation, this is due to copy pasting code. Will replace configure() by requirements() and then check it again.

**Comment by MTomBosch** [comment]
I did now some more testing. Besides the fact that the problem is still there specifiying the private requirement using the requirements() method did not have any effect. I commented above code, please check it. What is interesting though is that although I still get the same packageid, it is different when using the requires attribute and requirements() function.
But I guess this is because when using the requires attribute the recipe of other-pkg is downloaded whereas with the requirements method nothing is done by the Conan client.

Coming to you request about the logs and conaninfo, here we go:

export-pkg log variant 1

```
Exporting package recipe
mypkg/2.4.0@myuser/stable: A new conanfile.py version was exported
mypkg/2.4.0@myuser/stable: Folder: /home/myuser/.conan/data/mypkg/2.4.0/myuser/stable/export
mypkg/2.4.0@myuser/stable: Using the exported files summary hash as the recipe revision: 235832985378f5cff7a8fff3d1e5b97d
mypkg/2.4.0@myuser/stable: Exported revision: 235832985378f5cff7a8fff3d1e5b97d
other-pkg/2.2.4@ci/stable: Not found in local cache, looking in remotes...
other-pkg/2.2.4@ci/stable: Trying with '...-all-virtual'...
mypkg/2.4.0@myuser/stable: Forced build from source
Packaging to cb7f4b941c0e0b4d885c5a7f554197e2d84ddd43
mypkg/2.4.0@myuser/stable: Exporting to cache existing package from user folder
mypkg/2.4.0@myuser/stable: Package folder /home/myuser/.conan/data/mypkg/2.4.0/myuser/stable/package/cb7f4b941c0e0b4d885c5a7f554197e2d84ddd43
mypkg/2.4.0@myuser/stable: Packaged 5 '.txt' files
mypkg/2.4.0@myuser/stable: Packaged 11 '.cpp' files
mypkg/2.4.0@myuser/stable: Packaged 12 '.h' files
mypkg/2.4.0@myuser/stable: Packaged 2 '.rst' files: architecture.rst, detailed_design.rst
mypkg/2.4.0@myuser/stable: Packaged 1 '.puml' file: detailed_design.puml
mypkg/2.4.0@myuser/stable: Package 'cb7f4b941c0e0b4d885c5a7f554197e2d84ddd43' created
mypkg/2.4.0@myuser/stable: Created package revision 0983b9eb11b52df8506ce5deaf437f1f
```
conaninfo.txt variant 1:

```
[settings]

[requires]
    other-pkg/2.Y.Z

[options]

[full_settings]

[full_requires]
    other-pkg/2.2.4@vrte-ci/stable:7ca2bb01242d484a6a339bab012b8129ddaf8196

[full_options]
    other-pkg:ENABLE_LOGGER=ON

[recipe_hash]
    235832985378f5cff7a8fff3d1e5b97d

[env]
```

export-pkg log variant 2 (different os and different compiler than variant 1, but same options)

```
Exporting package recipe
mypkg/2.4.0@myuser/stable: A new conanfile.py version was exported
mypkg/2.4.0@myuser/stable: Folder: /home/myuser/.conan/data/mypkg/2.4.0/myuser/stable/export
mypkg/2.4.0@myuser/stable: Using the exported files summary hash as the recipe revision: 235832985378f5cff7a8fff3d1e5b97d
mypkg/2.4.0@myuser/stable: Exported revision: 235832985378f5cff7a8fff3d1e5b97d
mypkg/2.4.0@myuser/stable: Forced build from source
Packaging to cb7f4b941c0e0b4d885c5a7f554197e2d84ddd43
mypkg/2.4.0@myuser/stable: Exporting to cache existing package from user folder
mypkg/2.4.0@myuser/stable: Package folder /home/myuser/.conan/data/mypkg/2.4.0/myuser/stable/package/cb7f4b941c0e0b4d885c5a7f554197e2d84ddd43
mypkg/2.4.0@myuser/stable: Packaged 5 '.txt' files
other-pkg.ossscansrc/2.4.0@myuser/stable: Packaged 11 '.cpp' files
other-pkg.ossscansrc/2.4.0@myuser/stable: Packaged 12 '.h' files
other-pkg.ossscansrc/2.4.0@myuser/stable: Packaged 2 '.rst' files: architecture.rst, detailed_design.rst
other-pkg.ossscansrc/2.4.0@myuser/stable: Packaged 1 '.puml' file: detailed_design.puml
other-pkg.ossscansrc/2.4.0@myuser/stable: Package 'cb7f4b941c0e0b4d885c5a7f554197e2d84ddd43' created
other-pkg.ossscansrc/2.4.0@myuser/stable: Created package revision 1c89e98f09852e4030d17e856e5657d4 
```

conaninfo.txt variant 2

```
[settings]

[requires]
    other-pkg/2.Y.Z

[options]

[full_settings]

[full_requires]
    other-pkg/2.2.4@vrte-ci/stable:6e7c9fe13797b1bf1b7a4c0c3d997ed0b53f9f42

[full_options]
    other-pkg:ENABLE_LOGGER=ON

[recipe_hash]
    235832985378f5cff7a8fff3d1e5b97d

[env]
 
```

Shouldn't the used settings of other-pkg be mentioned in the file too to have an effect on the package id of mypkg?

**Comment by memsharded** [comment]
I have been trying to reproduce, but this seems to be working fine. 

I wrote the following unittest, passing in 1.47:
```python
def test_export_pkg():
    c = TestClient()
    mode = "self.info.requires['dep'].full_package_mode()"
    c.save({"dep/conanfile.py": GenConanfile("dep", "0.1").with_option("myoption", [True, False]),
            "app/conanfile.py": GenConanfile("app", "0.1").with_require("dep/0.1", private=True)
                                                          .with_package_id(mode)})
    c.run("create dep -o *:myoption=True")
    c.run("create dep -o *:myoption=False")
    c.run("export-pkg app -o dep*:myoption=True")
    assert "app/0.1: Package '256ceb5f901d821ecf532b0057844469bc3be566' created" in c.out
    c.run("export-pkg app -o dep*:myoption=False")
    assert "app/0.1: Package 'cd6ec36bf895d07d1b77c7b05c254a2df50136c4' created" in c.out
    ref = ConanFileReference.loads("app/0.1")
    pref1 = PackageReference(ref, "256ceb5f901d821ecf532b0057844469bc3be566")
    pkg1 = c.cache.package_layout(ref).package(pref1)
    info1 = load(os.path.join(pkg1, "conaninfo.txt"))
    assert "[requires]\n    dep/0.1:d2560ba1787c188a1d7fabeb5f8e012ac53301bb" in info1
    pref2 = PackageReference(ref, "cd6ec36bf895d07d1b77c7b05c254a2df50136c4")
    pkg2 = c.cache.package_layout(ref).package(pref2)
    info2 = load(os.path.join(pkg2, "conaninfo.txt"))
    assert "[requires]\n    dep/0.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" in info2

```

There is definitely something wrong with 
```
[requires]
    other-pkg/2.Y.Z
```
What should be there is something in the form:
```
[requires]
    other-pkg/2.1.3:package_id
```
No idea what could be, it seems there is something else in your configuration or setup that could be changing that. Maybe the ``package_id()`` method is still incorrectly indented?
If you could please have something that we can reproduce on our end, that would help a lot. Maybe setting up a git repo with some simple recipes and a script to run the necessary commands, or something like that.

**Comment by MTomBosch** [comment]
Thanks for further analyzing the issue.
I unfortunately cannot provide the exact repo that I am using since it is proprietary.
I will analyse it on my end for some more time to find the root cause, I will also try to setup an example myself. If not reproducible with a publicly shareable repo I will just leave it aside since I have already found another solution using a different approach that in the end suits my needs even better.

But I still want to understand why this is not working on my end ;)

One thing that comes to my mind that is different in your unit test compared to my setup:
- The dep package is not locally created and also not available in my local cache. It is/shall be fetched from a virtual Artifactory remote. Maybe setting up an example where app is like you did it but the dependency is a public package from conan center. This is more like my setup.

**Comment by memsharded** [comment]
I have tried to extend the test, so it uploads things to the server, and removes from the local cache, still seems to be working ok:
```python

def test_export_pkg():
    c = TestClient(default_server_user=True)
    mode = "self.info.requires['dep'].full_package_mode()"
    c.save({"dep/conanfile.py": GenConanfile("dep", "0.1").with_option("myoption", [True, False]),
            "app/conanfile.py": GenConanfile("app", "0.1").with_require("dep/0.1", private=True)
                                                          .with_package_id(mode)})
    c.run("create dep -o *:myoption=True")
    c.run("create dep -o *:myoption=False")
    c.run("upload * -r=default --all --confirm")
    c.run("remove * -f")
    c.run("export-pkg app -o dep*:myoption=True")
    assert "app/0.1: Package '256ceb5f901d821ecf532b0057844469bc3be566' created" in c.out
    ref = ConanFileReference.loads("app/0.1")
    pref1 = PackageReference(ref, "256ceb5f901d821ecf532b0057844469bc3be566")
    pkg1 = c.cache.package_layout(ref).package(pref1)
    print(pkg1)
    info1 = load(os.path.join(pkg1, "conaninfo.txt"))
    assert "[requires]\n    dep/0.1:d2560ba1787c188a1d7fabeb5f8e012ac53301bb" in info1

    c.run("remove * -f")
    c.run("export-pkg app -o dep*:myoption=False")
    assert "app/0.1: Package 'cd6ec36bf895d07d1b77c7b05c254a2df50136c4' created" in c.out
    pref2 = PackageReference(ref, "cd6ec36bf895d07d1b77c7b05c254a2df50136c4")
    pkg2 = c.cache.package_layout(ref).package(pref2)
    info2 = load(os.path.join(pkg2, "conaninfo.txt"))
    assert "[requires]\n    dep/0.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" in info2
```

**Comment by MTomBosch** [comment]
Found the root cause: Indentation of the package_id method was wrong so it was treated as global method and not as part of the class. And this means the package_id method was not overwritten by me.
After properly indenting it it works. *shame on me*

Thanks for your support.

**Comment by memsharded** [comment]
Ok, I assumed that had been fixed after the first comment, happy that it is finally working, glad to help!
