### ISSUE TITLE
[bug] Strange error when testing package with no requirements

### ISSUE THREAD

**Issue by tonichedgehog** [conan-io/conan#13483]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: N/A
* Conan version: 2.0.2
* Python version: 3.11.2

Hi, I'm trying to test a package that have no requirements, and the error message seems off, as it refers to the recipe for the package being tested, not the recipe for the test:

`ERROR: The conanfile at 'C:\Users\me\conanfile.py' doesn't declare any requirement, use 'self.tested_reference_str' to require the package being created.`

### Steps to reproduce

conanfile.py:
```
from conan import ConanFile
class DummyConan(ConanFile):
    name = "dummy"
    version = "0.1"
    package_type = "header-library"
    exports_sources = "dummy.h"
```
test_package/conanfile.py:
```
from conan import ConanFile
class TestDummyConan(ConanFile):
    def requirements(self):
        self.requires(self.tested_reference_str)
    def test(self):
        pass
```

`conan install .`
`conan test . dummy/0.1`

### Logs

`ERROR: The conanfile at 'C:\Users\me\conanfile.py' doesn't declare any requirement, use 'self.tested_reference_str' to require the package being created.`

**Comment by jcar87** [comment]
Hi @tonichedgehog, thanks for opening this issue.

`conan test . dummy/0.1` will use the `conanfile.py` present in the current working directory to perform the test operation, so in your case the error would be correct, as it is being done on the conanfile for the `dummy` library.

You would have to run, either:
```
conan test test_package dummy/0.1
```
or
```
cd test_package
conan test . dummy/0.1
```

in order for the test package to run. Please note that the package for `dummy/0.1` needs to previously be created.
The 
`conan create .` workflow (in the same directory as the `conanfile.py` for `dummy`) will automatically create the package _and_ run the test package.

Hope this helps clarify this, please let us know if this solves your issue.

**Comment by tonichedgehog** [comment]
That indeed clarifies my issue, seems I still have the v1 way of doing things etched into muscle memory.

Thanks for taking the time for helping me,
/J
