### ISSUE TITLE
[bug] conan editable does not work with `tools.cmake.cmake_layout:build_folder_vars`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#13485]
### Environment details

* Conan version: 2.0.2

### Steps to reproduce

Set `tools.cmake.cmake_layout:build_folder_vars=["settings.compiler", "settings.compiler.version"]` and try to link two packages with `conan editable add`. After `conan install` a `XXX__LIB_DIRS_RELEASE` will not contain the compiler in the path and the `find_package()` will fail in CMake.

**Comment by memsharded** [comment]
Hi @mpusz 

Sorry, there is not enough detail there to understand. Is this reproducible with ``conan new cmake_lib`` templates?
Thanks

**Comment by mpusz** [comment]
1. Set the below in `global.conf`

```
tools.cmake.cmake_layout:build_folder_vars=["settings.compiler", "settings.compiler.version"]
```

2. Do the following steps:

```
mkdir foo && cd foo
conan new cmake_lib -d name=foo -d version=1.0.0
conan build .
conan editable add .
cd ..
mkdir boo && cd boo
conan new cmake_lib -d name=boo -d version=1.0.0
```

3. Add `requires = "foo/1.0.0"` to _conanfile.py_ and `find_package(foo CONFIG REQUIRED)` to _CMakeLists.txt_ of boo.
4. Run `conan build .`

**Comment by memsharded** [comment]
Thanks! That helped :)

Managed to reproduce, there is a missing "is editable" check, indeed a bug. Fixing it in https://github.com/conan-io/conan/pull/13488 for next 2.0.3 patch release.

**Comment by memsharded** [comment]
Closed in https://github.com/conan-io/conan/pull/13488 for 2.0.3
