### ISSUE TITLE
[question] Best practice for multiple CMAKE_TOOLCHAIN_FILE in Conan (2.0)

### ISSUE THREAD

**Issue by chen-tianjian** [conan-io/conan#13482]
### What is your question?

May I ask what the best practice is if I have multiple `CMAKE_TOOLCHAIN_FILE`s? For example, Conan (2.0) needs the `conan_toolchain.cmake`, and I have another toolchain file for cross-compilation (e.g. [link](https://github.com/espressif/esp-idf/blob/master/examples/build_system/cmake/idf_as_lib/build.sh#LL12)). How can I have both at the same time?

Not sure if it is relevant, but vcpkg has a tool to combine their toolchain file with another toolchain file ([link](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#using-multiple-toolchain-files))

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @chen-tianjian  - thanks for asking this question.

If you already have a toolchain file for cross-compilation, you can use the `tools.cmake.cmaketoolchain:user_toolchain` configuration to cause Conan to `include()` it in the generated `conan_toolchain.cmake` file.

You would have to add it in the `[conf]` section of your _host_ profile, like this:
```
[conf]
tools.cmake.cmaketoolchain:user_toolchain=["/path/to/your/toolchain.cmake"]
```

**Comment by chen-tianjian** [comment]
Thanks @jcar87 , this is very helpful!
