### ISSUE TITLE
[bug] Output of `conan install` displays `Install finished succesfully` instead of `Install finished successfully`

### ISSUE THREAD

**Issue by benjaminchauvin** [conan-io/conan#13489]
### Environment details

* Operating System+version: MacOS Ventura 13.2.1
* Compiler+version: NA
* Conan version: 2.0.2
* Python version: 3.9.6

After a successful call of `conan install .`, the final message which is displayed is `Install finished succesfully`. I suggest to use `successfully` instead of `succesfully`.

I can create a PR if necessary.

**Comment by AbrilRBS** [comment]
Woops, nice catch!

In case you (or anyone else!) want to fix it,     https://github.com/conan-io/conan/blob/bc34240e028e9d7780b797a64a9e7a1bda37e9ec/conan/cli/commands/install.py#L81 is the culprit. A PR to the default release/2.0 branch would be great :)

If in the meanwhile you find any other typo in the code, feel free to also update that!

**Comment by benjaminchauvin** [comment]
@RubenRBS I created a pull request: https://github.com/conan-io/conan/pull/13522
But my change is in line 89, not 81. Is there another issue with line 81?

**Comment by AbrilRBS** [comment]
Closed by #13522
