### ISSUE TITLE
[question] Including PEP 440 post/dev Numbers and Local Version Identifiers in Conan Package Version

### ISSUE THREAD

**Issue by ntemplon** [conan-io/conan#13492]
### What is your question?

OS: MacOS Monterey (M1) and Ubuntu 20.04 (x86)
Conan Version: 1.53.0

Greetings all, and thank you in advance for any assistance you can provide!

My organization is currently in process of paying off tech debt associated with package deployment on all of our various packaging tools, and Conan's time has come. We have had good success with and a have strong preference for [PEP 440 version names](https://peps.python.org/pep-0440/) and would like to continue using that style with Conan packages. Unfortunately, we're experiencing issues with PEP 440 names that include post/dev numbers and/or local version identifiers being readable by Conan version ranges.

Our first attempt was to put a PEP 440 version number directly in the version field, like so:
`package_name/X.Y.Z.devN+git.1234ABCD@SourceRepository/SourceBranch`

We were hoping that `conan install package_name/[>=X.Y.Z]@SourceRepository/SourceBranch` would be able to locate and install the above version, just as it can if the `devN` and `+git` text is absent. Unfortunately Conan does not seem to be able to parse the version to compare to a range and complains that the version range '>=X.Y.Z' cannot be resolved.

Our next attempt was to "stuff" all the extra data after a dash as a prerelease, like so:
`package_name/X.Y.Z-devN-git.1234ABCD@SourceRepository/SourceBranch`

This let us match the package with the range `conan install package_name/[>=X.Y.Z, include_prerelease=True]@SourceRepository/SourceBranch`. On top of being no longer PEP 440 compliant, it feels overly hacky to treat every version as a prerelease in conan to fit the local version identifier (`git.1234ABCD`) into the version while still supporting ranges and we're not sure how version resolution will go (is `-post1` consider "newer" than `-dev5`?).

Is there a preferred means of or accepted convention for including this extra PEP 440 information in a Conan package version, while still supporting ranges?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ntemplon 

Thanks for your question.

I think what you are reporting above is a limitation of the library we were using in Conan 1.X to resolve version ranges. We couldn't remove it in 1.X, but we have removed that library in 2.0 and we have implemented our own version range resolution for Conan 2.0, and it should be able to deal with the version range that you suggest. The only limitation is that it doesn't handle hybrid number-strings as hybrid, but always as strings. But pre-releases, and +build identifier, with any level of nested items, should work. Could you please give it a try and let us know?

**Comment by ntemplon** [comment]
@memsharded .

Thank you for the rapid response!

Testing here was done on MacOS Monterey with Apple Silicon.

I tested the versioning scheme mentioned above with [the "hello" project from the conan 2 tutorial](https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html), and it appears to be working! Specifically, a package with the identifier `hello/1.10.3.post6+git.1234abcd@source_repo/source_branch` was found and installed by `conan install --requries='hello/[>=1]@source_repo/source_branch'`.

Based on your comment that hybrid number-strings are always handled as strings, we tested creating a version `1.0.1.post5+git.1234abcd`, `1.2.3.post6+git.1234abcd`, and the aforementioned `1.10.3.post6+git.1234abcd`. We expected string sorting to assume 1.2.3 was the newest version, but much to our (pleasant) surprise, conan correctly identified 1.10.3 as the latest version. Where can we expect the string comparison limitation to show up and "get us"?

**Comment by memsharded** [comment]
> I tested the versioning scheme mentioned above with [the "hello" project from the conan 2 tutorial](https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html), and it appears to be working!

Fantastic 😄 

> Based on your comment that hybrid number-strings are always handled as strings, we tested creating a version 1.0.1.post5+git.1234abcd, 1.2.3.post6+git.1234abcd, and the aforementioned 1.10.3.post6+git.1234abcd. We expected string sorting to assume 1.2.3 was the newest version, but much to our (pleasant) surprise, conan correctly identified 1.10.3 as the latest version. Where can we expect the string comparison limitation to show up and "get us"?

Yes, every dot, hyphen or plus sign separated element will be treated separately, and compared with the matching one in the range in the right order.
The only situation where it can show is in the ``1234abcd`` field. As it contains digits and letters, it will compare as a pure string, irrespective of the digits. So ``11abcd`` can be greater than ``1234abcd`` even if 11<12 (not validated, might be the opposite, I don't know by heart the ordering of letters vs numbers). The recommendation for this would be to split it into ``1234.abcd``, even in the ``+git.1234.abcd.234`` is possible to have an arbitrary number of dot separated fields, and they will be processed too.

I know that the upgrade to a major Conan version like 2.0 can take some effort, it is a big release, but we also put a ton of effort to improve things like this one, which was impossible to do in 1.X without breaking.

**Comment by ntemplon** [comment]
That all sounds pretty good; that field is a hash, so we aren't expecting any particular ordering there.

Will Conan parse the "postN" and "devN" sections as post/dev versions, or would "post.N" / "dev.N" be required for them to sort naturally?

**Comment by memsharded** [comment]
> Will Conan parse the "postN" and "devN" sections as post/dev versions, or would "post.N" / "dev.N" be required for them to sort naturally?

Exactly my point above. For a correct sorting it has to be ``post.N`` and ``dev.N``. Like of ``alpha.1.2.3``, ``beta.2.3.4``. Otherwise the N digit will be treated as string, not a number.

**Comment by ntemplon** [comment]
> Exactly my point above. For a correct sorting it has to be `post.N` and `dev.N`. Like of `alpha.1.2.3`, `beta.2.3.4`. Otherwise the N digit will be treated as string, not a number.

Thank you for your time and the very helpful explanation! This gives us good enough understanding (and enough features) to be able to work with Conan 2.

One potential issue (that could be an opportunity to improve Conan in the future?) is that `post.N` isn't PEP 440 compliant, while `postN` is. This means teams that produce both a Conan package and a pip sdist (via something like scikit build) for their software won't be able to use the same version number for both artifacts. While not a dealbreaker by any means, Conan is so close to full PEP 440 support that I'd love to see it get all the way there.

**Comment by memsharded** [comment]
Yes, it is because Conan implementation doesn't follow the PEP440, but it tries to follow (generalizing) the more general semver specification: https://semver.org/, and there it gives some examples for pre-releases with dots: ``1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92``

Thanks for the feedback!
