### ISSUE TITLE
[bug] delete option in conan recipe may cause unexpected error

### ISSUE THREAD

**Issue by bigcat26** [conan-io/conan#13498]
### Environment details

* Operating System+version: Linux Ubuntu 20.04
* Compiler+version: GCC 9
* Conan version: conan 1.59.0
* Python version: Python 3.9.13

### Steps to reproduce

The possible way to reproduce the issue:

1. Create a static library project A which depends on spdlog/1.11.0 with "option:header_only=True"
2. Build library A then export it.
3. Create an executable project B which depends on both library A and spdlog/1.11.0 with "option:header_only=True"
4. Run conan install in project B
5. Error occours

```
ERROR: spdlog/1.11.0: Error in configure() method, line 47
        if self.options.shared:
        ConanException: option 'shared' doesn't exist
Possible options are ['header_only', 'wchar_support', 'wchar_filenames', 'no_exceptions']
```

the origin issue please refer to https://github.com/conan-io/conan-center-index/issues/16652

### Logs

```
$ cat ../conanfile.txt 
[requires]
spdlog/1.11.0
ProjectA/v1.0.0
[generators]
cmake_find_package
[options]
spdlog:header_only=True

$ conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: spdlog/1.11.0: Error in configure() method, line 47
        if self.options.shared:
        ConanException: option 'shared' doesn't exist
Possible options are ['header_only', 'wchar_support', 'wchar_filenames', 'no_exceptions']
```

**Comment by AbrilRBS** [comment]
Hi @bigcat26 thanks for taking the time to open the report (And a companion PR to conan-center-index!), we really appreciate it.
Even though you have submitted reproduction steps and the contents of your conanfile.txt (Thanks again! Super useful), I've not been able to repro this locally, I get the expected behaviour of things not breaking, so I'm asking @memsharded to take a closer look, see if he can find anything :)

**Comment by bigcat26** [comment]
Hi @RubenRBS, I have dug a little deeper to find the root cause and finally I found that the issue is about the package order in the '[requires]' section. The error occurs when I put `spdlog` before `project-a`.

I have also created a repository to help reproduce the issue: https://github.com/bigcat26/repro-conan-package-depends-order-issue

**Comment by memsharded** [comment]
Hi @bigcat26 

I have also tried to reproduce from https://github.com/bigcat26/repro-conan-package-depends-order-issue, but it seems to be working fine here too! I have no idea what could be happening in your case.

I'd recommend the following:
- Adding in the repo a small script that runs all the steps (there were some minor detail missing like the version at ``conan create``)
- Make sure it works in a clean cache (either by running a ``conan remove * -f`` first, or by settings a temporary new CONAN_USER_HOME)

**Comment by AbrilRBS** [comment]
Hi! I'm closing this issue as I'm cleaning up old issues and this didn't get an answer. Please feel free to reopen should you find yourself with the same problem again :)
