### ISSUE TITLE
[question] How does buildenv_info work?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#13494]
### What is your question?

I create a cudatoolkit recipe, and add those code in package_info:
```
        self.runenv_info.define("CUDAToolkit_ROOT", self.package_folder)        
        self.buildenv_info.define("CUDAToolkit_ROOT", self.package_folder)
        self.runenv_info.define("CUDA_PATH", self.package_folder)
        self.buildenv_info.define("CUDA_PATH", self.package_folder)
```
and When I use it to compile:
```
find_package(CUDAToolkit REQUIRED)
```
In conan 1.59.0, it works; BUT, in conan 1.57.0, it fails.
So I want to know how buildenv_info works? Does it transfer some variables through conan_toolchain.cmake?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

Thanks for your question.

The information from ``buildenv_info`` and ``runenv_info`` is collected mostly by ``VirtualBuildEnv`` generator and ``VirtualRunEnv`` generators respectively in the consumer side, and creating several .sh/.bat files that will be executed when called ``self.run()``. These generators have to be declared explicitly on the consumer side or use the ``tools.env.virtualenv:auto_use`` conf.

But in theory they are not related to ``find_package()`` calls, unless such ``find_package()`` depends on having things in the PATH. If that is the case, the above definitions will define env-vars files, that will be loaded when ``cmake.configure()`` runs, which internally calls ``self.run("cmake.....", env="conanbuild")``, that could be putting the cuda binaries in the PATH and finding them.

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed
> 
> Thanks for your question.
> 
> The information from `buildenv_info` and `runenv_info` is collected mostly by `VirtualBuildEnv` generator and `VirtualRunEnv` generators respectively in the consumer side, and creating several .sh/.bat files that will be executed when called `self.run()`. These generators have to be declared explicitly on the consumer side or use the `tools.env.virtualenv:auto_use` conf.
> 
> But in theory they are not related to `find_package()` calls, unless such `find_package()` depends on having things in the PATH. If that is the case, the above definitions will define env-vars files, that will be loaded when `cmake.configure()` runs, which internally calls `self.run("cmake.....", env="conanbuild")`, that could be putting the cuda binaries in the PATH and finding them.

Thanks for replying! After I compare the conan_toolchain.cmake between 1.57 and 1.59, I find the difference is CMAKE_PROGRAM_PATH, conan 1.59 adds this variable to conan_toolchain.cmake.

**Comment by memsharded** [comment]
Ok, that makes sense, latest ``CMakeToolchain`` was adding some improvements to help supporting ``find_program()``, ``find_xxx()`` beyond ``find_package()``, so this is the reason it works for 1.59, thanks for reporting!

**Comment by petermbauer** [comment]
Please let me add my related question here:
I have this in the recipe of a dependency:
```
    def package_info(self):
        self.buildenv_info.define("UNITY_DIR", self.package_folder)
```
With `generators = "VirtualBuildEnv"` the scripts are generated as expected and when running the scripts before running `cmake` manually it works but without the scripts and with `conan build` it does not work (env var is not set).
I am using the new cmake tool and was expecting that `UNITY_DIR` would be set automatically for the build process:
```
    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()  // UNITY_DIR is not set
```
Do i have to explicitly use an `Environment` or `VirtualBuildEnv` and wrap the `cmake.build()` with it somehow? Or is there something to be done in the `generate()`?

thx

**Comment by memsharded** [comment]
No, that should work out of the box.
The following test passes (in Windows):
```python
def test_conan_build_cmd():
    unity = textwrap.dedent("""
        from conan import ConanFile

        class Pkg(ConanFile):
            name = "unity"
            version = "0.1"
            def package_info(self):
                self.buildenv_info.define("MYUNITYVAR", "MYUNITYEVALUE!!")
        """)

    app = textwrap.dedent("""
        from conan import ConanFile

        class Pkg(ConanFile):
            tool_requires = "unity/0.1"
            generators = "VirtualBuildEnv"
            def build(self):
                self.run("SET MYUNITYVAR")
        """)

    c = TestClient()
    c.save({"unity/conanfile.py": unity,
            "app/conanfile.py": app})

    c.run("create unity")
    c.run("install app")
    c.run("build app")
    assert "MYUNITYVAR=MYUNITYEVALUE!!" in c.out
```
I think that is your setup, so there should be something else in your recipes or config. If you can put together something that can be reproduced, that would help.

**Comment by petermbauer** [comment]
Thanks for the clarification, it works indeed as it should but my fault was to use a transitive `tool_requires` and then not specifying the `VirtualBuildEnv` generator.

Thanks a lot for your help!
