### ISSUE TITLE
[bug] option with "ANY" can't used in "conan create -o"  

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#13490]
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version: 9
* Conan version: conan 1.59.0
* Python version: Python 3.8.10

### Steps to reproduce

1. in conanfile
```
    options = {
        "cuda": ["ANY"],
    }
    default_options = {
        "cuda": "system",
    }
```

```
    def requirements(self):
        self.requires(f"cudatoolkit/{self.options.cuda}")
```

2. conan create . xxx/xxx -o cuda=11.1.1
3. in output log, it still shows using "cudatoolkit/system"
4. and add print
       ` print(f"cudatoolkit/{self.options.cuda}")`
it shows cudatoolkit/system, looks like there is some problem about option ANY.

**Comment by AbrilRBS** [comment]
Hi @Tumb1eweed thanks for your report. I've tried to reproduce your issue but I've not been able to. Could you share a minimal repro case? I've tried with Conan 1.59.0 (And 2.0 too just in case) with the following **conanfile.py** but I've had no luck:

```py
from conan import ConanFile

class Pkg(ConanFile):
	name = "pkg"
	version = "1.0"
	
	options = {
		"cuda": ["ANY"]
	}

	default_options = {
		"cuda": "system"
	}

	def configure(self):
		self.output.info(self.options.cuda)

	def requirements(self):
		self.output.info(self.options.cuda)

```

and when running `conan create . -o cuda=11.1.11` I get:
``` 
...

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=14
os=Macos
os_build=Macos
[options]
cuda=11.1.11
[build_requires]
[env]

pkg/1.0: 11.1.11
pkg/1.0: 11.1.11
pkg/1.0: Forced build from source
Installing package: pkg/1.0
Requirements
    pkg/1.0 from local cache - Cache
Packages
    pkg/1.0:cb6d487d87a856d3cc06bf3bf7a92f6e36004514 - Build

...
```

where I can properly see the `cuda=11.1.11` option and the expected 
```
pkg/1.0: 11.1.11
pkg/1.0: 11.1.11
```
output

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed thanks for your report. I've tried to reproduce your issue but I've not been able to. Could you share a minimal repro case? I've tried with Conan 1.59.0 (And 2.0 too just in case) with the following **conanfile.py** but I've had no luck:
> 
> ```python
> from conan import ConanFile
> 
> class Pkg(ConanFile):
> 	name = "pkg"
> 	version = "1.0"
> 	
> 	options = {
> 		"cuda": ["ANY"]
> 	}
> 
> 	default_options = {
> 		"cuda": "system"
> 	}
> 
> 	def configure(self):
> 		self.output.info(self.options.cuda)
> 
> 	def requirements(self):
> 		self.output.info(self.options.cuda)
> ```
> 
> and when running `conan create . -o cuda=11.1.11` I get:
> 
> ```
> ...
> 
> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> compiler=apple-clang
> compiler.libcxx=libc++
> compiler.version=14
> os=Macos
> os_build=Macos
> [options]
> cuda=11.1.11
> [build_requires]
> [env]
> 
> pkg/1.0: 11.1.11
> pkg/1.0: 11.1.11
> pkg/1.0: Forced build from source
> Installing package: pkg/1.0
> Requirements
>     pkg/1.0 from local cache - Cache
> Packages
>     pkg/1.0:cb6d487d87a856d3cc06bf3bf7a92f6e36004514 - Build
> 
> ...
> ```
> 
> where I can properly see the `cuda=11.1.11` option and the expected
> 
> ```
> pkg/1.0: 11.1.11
> pkg/1.0: 11.1.11
> ```
> 
> output

oh I find the problem, when there is a test_package with option ANY would cause this problem, like this:
```
class TestPackageConan(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    generators = "CMakeDeps", "CMakeToolchain", "VirtualRunEnv"
    test_type = "explicit"
    option = {"cuda": ["ANY"],}
```
if don't add this option, it would report:
![image](https://user-images.githubusercontent.com/27768261/226802588-742df036-af28-4282-9878-92fe633d2f5f.png)
![image](https://user-images.githubusercontent.com/27768261/226802601-17d6d781-c8b7-46a0-831b-2d70d08996aa.png)

**Comment by memsharded** [comment]
I think there is a typo in the ``test_package``, it is ``options = ...``, not ``option = ...``

**Comment by Tumb1eweed** [comment]
> I think there is a typo in the `test_package`, it is `options = ...`, not `option = ...`

my bad, type error, but even it's right this situation would happen.
In Configuration the option is right:
![image](https://user-images.githubusercontent.com/27768261/226838857-d22fa633-0d32-4cb1-9cc7-3271948d0a3e.png)

But in actual requirement:
![image](https://user-images.githubusercontent.com/27768261/226839007-1e60861e-0fe5-48c6-b0c9-5c7175afa661.png)

**Comment by AbrilRBS** [comment]
Hi @Tumb1eweed thanks for the extra info, still, can you please share a both your **conanfile.py** and **test_package/conanfile.py** files (A reduced version of it would be great but I can do that work for you, and feel free to privately send it over email if needed) as we're having problems trying to reproduce your exact issue and we want to rule out misscomunications please? Thanks! :)

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed thanks for the extra info, still, can you please share a both your **conanfile.py** and **test_package/conanfile.py** files (A reduced version of it would be great but I can do that work for you, and feel free to privately send it over email if needed) as we're having problems trying to reproduce your exact issue and we want to rule out misscomunications please? Thanks! :)

ok, my conanfile.py is:
```
import os, socket
from conan import ConanFile
from conan.tools.files import copy, unzip, ftp_download, collect_libs
from conan.tools.cmake import CMakeToolchain, CMakeDeps


class CudnnConan(ConanFile):
    name = "cudnn"
    license = "NVIDIA EULA"
    description = "The NVIDIA CUDA® Deep Neural Network library"
    url = "https://developer.nvidia.com/cudnn"
    settings = "os", "arch", "compiler", "build_type"  # even for pre-built executables
    options = {
        "cuda": ["ANY"],
    }
    default_options = {
        "cuda": "system",
    }
...
    def requirements(self):
        print(f"cudatoolkit/{self.options.cuda}")
        self.requires(f"cudatoolkit/{self.options.cuda}")
...
```

and test_package/conanfile.py is
```
from conan import ConanFile
from conan.tools.build import can_run
from conan.tools.cmake import cmake_layout, CMake, CMakeToolchain, CMakeDeps
import os


class TestPackageConan(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    generators = "CMakeDeps", "CMakeToolchain", "VirtualRunEnv"
    test_type = "explicit"
    options =  {"cuda": "ANY"}

    def requirements(self):
        self.requires(self.tested_reference_str)

    def layout(self):
        cmake_layout(self)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def test(self):
        if can_run(self):
            bin_path = os.path.join(self.cpp.build.bindirs[0], "test_package")
            self.run(bin_path, env="conanrun")
```

**Comment by memsharded** [comment]
Thanks for the files.

I built the following unittest based on your inputs:
```python
def test_options_test_package():
    c = TestClient()
    conanfile = textwrap.dedent("""
        import os, socket
        from conan import ConanFile

        class CudnnConan(ConanFile):
            name = "cudann"
            version = "0.1"

            options = {"cuda": ["ANY"]}
            default_options = {"cuda": "system"}

            def requirements(self):
                print(f"cudatoolkit/{self.options.cuda}")
                self.requires(f"cudatoolkit/{self.options.cuda}")
            """)
    test = textwrap.dedent("""
        from conan import ConanFile

        class TestPackageConan(ConanFile):
            test_type = "explicit"

            def requirements(self):
                self.requires(self.tested_reference_str)
            def test(self):
                pass
        """)

    c.save({"toolkit/conanfile.py": GenConanfile("cudatoolkit"),
            "cudann/conanfile.py": conanfile,
            "cudann/test_package/conanfile.py": test})
    c.run("create toolkit 1.1.1@")
    c.run("create cudann -o cudann*:cuda=1.1.1")
    print(c.out)
    assert "cudatoolkit/1.1.1" in c.out
    assert "cudatoolkit/system" not in c.out
```

As you can see, with:
- Defining the right option scope with ``-o cudann*:cuda=1.1.1``
- Not necessary to define ``options`` in the ``test_package`` if it is not used at all.
It works, and it resolves to ``cudatoolkiet/1.1.1`` correctly, and not ``system`` one.

Could you please check it and let us know?

**Comment by Tumb1eweed** [comment]
> Thanks for the files.
> 
> I built the following unittest based on your inputs:
> 
> ```python
> def test_options_test_package():
>     c = TestClient()
>     conanfile = textwrap.dedent("""
>         import os, socket
>         from conan import ConanFile
> 
>         class CudnnConan(ConanFile):
>             name = "cudann"
>             version = "0.1"
> 
>             options = {"cuda": ["ANY"]}
>             default_options = {"cuda": "system"}
> 
>             def requirements(self):
>                 print(f"cudatoolkit/{self.options.cuda}")
>                 self.requires(f"cudatoolkit/{self.options.cuda}")
>             """)
>     test = textwrap.dedent("""
>         from conan import ConanFile
> 
>         class TestPackageConan(ConanFile):
>             test_type = "explicit"
> 
>             def requirements(self):
>                 self.requires(self.tested_reference_str)
>             def test(self):
>                 pass
>         """)
> 
>     c.save({"toolkit/conanfile.py": GenConanfile("cudatoolkit"),
>             "cudann/conanfile.py": conanfile,
>             "cudann/test_package/conanfile.py": test})
>     c.run("create toolkit 1.1.1@")
>     c.run("create cudann -o cudann*:cuda=1.1.1")
>     print(c.out)
>     assert "cudatoolkit/1.1.1" in c.out
>     assert "cudatoolkit/system" not in c.out
> ```
> 
> As you can see, with:
> 
> * Defining the right option scope with `-o cudann*:cuda=1.1.1`
> * Not necessary to define `options` in the `test_package` if it is not used at all.
>   It works, and it resolves to `cudatoolkiet/1.1.1` correctly, and not `system` one.
> 
> Could you please check it and let us know?

OK, i reproduce the procedure:
1. I create a conanfile:
```
from conan import ConanFile

class CudnnConan(ConanFile):
    name = "cudnn"
    version = "0.1"
    options = {"cuda": ["ANY"]}
    default_options = {"cuda": "system"}

    def requirements(self):
        print(f"cudatoolkit/{self.options.cuda}")
        self.requires(f"cudatoolkit/{self.options.cuda}")
```
and `conan create . cudnn/0.1@`, it shows:
![image](https://user-images.githubusercontent.com/27768261/227474103-f5f622ce-6c8d-4b83-b917-b8d53c54de25.png)


use `conan create . cudnn/0.1@ -o cuda=11.1.1`
it shows:
![image](https://user-images.githubusercontent.com/27768261/227474048-e8d8826d-c749-41a1-8bf4-3acd16c4bb8c.png)

totally normal

2. After I create a conanfile in test_package:
```
from conan import ConanFile

class TestPackageConan(ConanFile):
    test_type = "explicit"

    def requirements(self):
        self.requires(self.tested_reference_str)

    def test(self):
        pass
```
If I use `conan create . cudnn/0.1@`, it acts normally.
But If I use `conan create . cudnn/0.1@ -o cuda=11.1.1`, it shows:
![image](https://user-images.githubusercontent.com/27768261/227475054-26722521-18c9-4b55-af55-45221b5f25a9.png)

so I add the options to test_package:
```
from conan import ConanFile

class TestPackageConan(ConanFile):
    test_type = "explicit"
    options = {"cuda":["ANY"]}

    def requirements(self):
        self.requires(self.tested_reference_str)

    def test(self):
        pass
```
and the problem occurs, when I use `conan create . cudnn/0.1@ -o cuda=11.1.1`, it shows:
![image](https://user-images.githubusercontent.com/27768261/227476056-9a543473-0319-432f-8104-6d07e1ca1a81.png)

the option is right, cuda/11.1.1, but the requirements are wrong, print "cudatoolkit/system"

I don't know if my grammar is right or a BUG, but you can reproduce this problem by my steps.

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

I am not sure if I follow. You are still using the wrong command line syntax ``create cudann -o cuda=1.1.1``. Instead of this, you should be using ``create cudann -o cudann*:cuda=1.1.1`` syntax (``create cudann -o *:cuda=1.1.1`` could be enough too), and that solves the issue without adding the option to the ``test_package``, as my test shows. Am I missing something?

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed
> 
> I am not sure if I follow. You are still using the wrong command line syntax `create cudann -o cuda=1.1.1`. Instead of this, you should be using `create cudann -o cudann*:cuda=1.1.1` syntax (`create cudann -o *:cuda=1.1.1` could be enough too), and that solves the issue without adding the option to the `test_package`, as my test shows. Am I missing something?
Oh, I ignore the syntax, my bad.
"*:cuda" this can solve my problem, thanks very much!

**Comment by memsharded** [comment]
You are welcome! 🙂
