### ISSUE TITLE
[bug] In the CMakeDeps Generator IMPORTED_LOCATION is overridden by IMPORTED_LOCATION${config_suffix}

### ISSUE THREAD

**Issue by DanielDewald** [conan-io/conan#13504]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: MSVC 19
* Conan version: 2.0.2
* Python version: 3.10

### Steps to reproduce

1. Download a dependency (e.g. thrift) with conan using the CMakeDeps generator
2. Have a look at the created cmakedeps_macros.cmake

In the function `conan_package_library_targets` line 48 and 49 for windows the correct target properties are set for IMPORTED_IMPLIB and IMPORTED_LOCATION. 

`set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_SHARED_FOUND_LIBRARY})
 set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_IMPLIB ${CONAN_FOUND_LIBRARY})`

Unfortunately those values are superseded by the line 61 where a per config value for IMPORTED_LOCATION_${config_suffix} is set, making the previous setting useless.

`set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION${config_suffix} ${CONAN_FOUND_LIBRARY})`

3. Create a cmake project using 

`  add_custom_command(TARGET mytarget POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_RUNTIME_DLLS:mytarget> $<TARGET_FILE_DIR:mytarget>)`

4. Instead of copying the dlls files to the binary folder upon building, the .lib files are copied.

**Comment by hgraeber** [comment]
The right thing is to not set IMPORTED_LOCATION at all.

Instead IMPORTED_LOCATION_DEBUG or IMPORTED_LOCATION_RELEASE shall be set to the Library for LIBRARY targets and to the dll (or so) for a shared library. For the latter IMPORTED_IMPLIB_DEBUG or IMPORTED_IMPLIB_RELEASE has to be set to the library. IMPORTED_LOCATION and IMPORTED_IMPLIB will then be automatically determined by cmake.

**Comment by Untzelmann** [comment]
Hey,

I have a fix for it here. 
[fix-cmakedeps-import-library-config-suffix.patch](https://github.com/conan-io/conan/files/11420056/fix-cmakedeps-import-library-config-suffix.patch)

I also tried to upload this into a branch, to start a pull request, but it seems like I have no permissions for that. Could somebody grant this permission to me, so that I can upload this change?

**Comment by memsharded** [comment]
> I also tried to upload this into a branch, to start a pull request, but it seems like I have no permissions for that. Could somebody grant this permission to me, so that I can upload this change?

Hi @Untzelmann 

you cannot upload branches to the main repo, you need to push your branches to your Github fork, and do a PRs from your fork. That is the contribution flow to Conan, we all, including the maintainers, do PRs from our forks, not from the central repo.

**Comment by Untzelmann** [comment]
Sorry, I actually never really worked on github, so this is all new to me.

I think this time I got it to work: https://github.com/conan-io/conan/pull/13841

**Comment by memsharded** [comment]
> Sorry, I actually never really worked on github, so this is all new to me.

No prob, thanks for wanting to contribute :) Feel free to ask any further question that you might have.

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/13841 by @Untzelmann , will be in next 2.0.5
