### ISSUE TITLE
[question] conan2 accessing self.settings vs self.info.settings

### ISSUE THREAD

**Issue by bbandix** [conan-io/conan#13506]
### What is your question?

Hi,

We started an experimental migration of our packages to conan 2.x.

In our conan_file_base package we have defined some common properties to assist variance handling in packages based on settings, we also use custom settings e.g. runtime, simplified along the lines of:

```
    @property
    def is_linux_simulation(self):
        return (
            self.settings.runtime == "simulation"
            and self.settings.os == "Linux"
        )

    @property
    def is_windows_simulation(self):
        return (
            self.settings.runtime == "simulation"
            and self.settings.os == "Windows"
        )
```
These properties are checked in different places (mainly package(), package_id(), and package_info()) in consumer conanfiles to decide on what to package and what settings to include in the id based on a centrally managed combination of settings.

With conan 2.x direct access to self.settings is restricted, so for example in package_id() one can only access self.info.settings, however in package() accessing self.info is forbidden, thus accessing self.info.settings is not possible, as the following exceptions demonstrate:
```
ConanException: 'self.settings' access in 'package_id()' method is forbidden
ConanException: 'self.info' access in 'package()' method is forbidden
```
**Question**
- Is there maybe a recommended/better way to read settings values, or defining such common properties derived from settings without having to check the caller to decide where to read the settings from or restrict the usability of such properties?

```
conan --version
Conan version 2.0.2
```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @bbandix 

Thanks for your question.
There is no general abstraction in Conan for that, while it is important that the correct ``self.settings`` and ``self.info.settings`` are used in the right methods for achieving the right behavior, specially in Conan 2.0 to enable the correct binary ``compatibility.py``.

Have you tried the quick workaround of doing a ``try-except`` around it? something like:
```python
@property
    def is_linux_simulation(self):
        try:
             return self.settings.runtime == "simulation" and self.settings.os == "Linux"
        except:
            return self.info.settings.runtime == "simulation" and self.info.settings.os == "Linux"
```
While not super clean, it might be pretty effective, and with a comment to explain the why, it would be reasonable.

For the long term, it would be interesting to learn about the binary compatibility use cases, if it really makes sense in the ``package_id()``, what kind of operation you are doing there, if there could be a better solution based on ``compatibility.py``, etc.

**Comment by bbandix** [comment]
Hi @memsharded,
Thank you for the answer, and the suggested workaround, this was also my initial idea, but it seemed too fragile.
I will try to look into compatibility.py, maybe a refactor could make it possible to use it.

**Comment by bbandix** [comment]
Hi @memsharded,
Looks like we can refactor the usage based on verify() and compatibility, so there is no need to do these checks in package_id() any more, therefore I will close this issue.
