### ISSUE TITLE
[feature] Improve `--update` logic regarding build requirements

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13508]
### What is your suggestion?

When I run `conan install . --update` against a conanfile.py where requirements have many common build requirements, I see in log that these common build requirements (and their requirements) are checked in remotes as many time as they appear for each dependency. Common recipes in requirements are checked only once.

For example I have a big conanfile.py with 767 conancenter recipes (just for testing purpose), and here is the number of checks of several build requirements when -u is passed to conan install:
m4/1.4.19: 237
autoconf/2.71: 109
automake/1.16.5: 54
libtool/2.4.7: 27
pkgconf/1.9.3: 32
meson/1.0.0: 51
ninja/1.11.1: 52
gnu-config/cci.20210814: 42
bison/3.8.2: 3

You can see that m4 is checked many times because it is a dependency of autoconf, which is a dependency of automake, which is a dependency of libtool. And libtool is a build requirement of many autotools based recipes.

Would it be possible to check these recipes only once?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @SpaceIm 

Could you please report the Conan version? Is this happening in Conan 2.0?

**Comment by SpaceIm** [comment]
2.0.2
