### ISSUE TITLE
[question] Conan 2.0 CMake without repeating all dependencies

### ISSUE THREAD

**Issue by jay-tux** [conan-io/conan#13513]
### What is your question?

Hi!

I'm currently using a CMakeLists.txt with the (1.X) usage of ``conan_basic_setup()`` (after including the cmake file generated by conan). However, it seems like 2.0 removes this. Can this be confirmed?

Additionally, while reading through the official docs, it seems like the new system with CMakeToolchain and CMakeDeps requires me to add every single dependency of my project using CMake's ``FIND_PACKAGE``. Is it possible to avoid this and just have CMake read the required packages from some Conan-generated file?

Thanks!

*Edit*: I'm using CLion, so I'd prefer if I could just have CMake do everything from inside my CMakeLists.txt

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jay-tux 

Thanks for your question.

Conan 1.X also superseded ``cmake`` generator time ago, providing ``CMakeDeps`` + ``CMakeToolchain`` in 1.X, not exclusively a 2.0 issue.

The answer is no, the new integration is a "transparent" integration, in the sense that it is pure CMake syntax, completely agnostic about Conan. So only ``find_package()`` calls are necessary. I also kind of liked the simplicity of the legacy one, but the community of users massively pushed towards this transparent integration, and maintaining more than one integrations is too complicated.

However, please note that you don't need to ``find_package()`` all dependencies and transitive dependencies. Just listing your direct dependencies in ``find_package(mypkg)`` and ``target_link_libraries(.... mypkg::mypkg)`` should be enough, they will internally manage to add the information from the transitive dependencies.

If you still want to automate that it should be doable with a bit of effort, but not very complex:
- Iterate in the ``generate()`` method over the ``self.dependencies.host.items()``
- For everyone, append to a ``myfinds.cmake`` file the ``find_package()`` call, and append to another variable (liek MYDEPSTARGETS) the target name
- ``include(myfinds.cmake)`` in your CMakeLists.txt
- add the ``target_link_libraries(your_target MYDEPSTARGETS)`` to your CMakeLists.txt

**Comment by jay-tux** [comment]
@memsharded Thank you for your swift reply. Do you have an example with the steps mentioned?

**Comment by jay-tux** [comment]
I tried with the Python-Conanfile below and the following CMake commands, but it seems like the `find_package` calls are not updating the required include directories (compilation gives that `glad/glad.h` is not found). What is the correct way to get the include directories working?

Conanfile:
```python
from conan import ConanFile
from conan.tools.cmake import cmake_layout


class ShardsRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"

    def requirements(self):
        self.requires("glad/0.1.36")
        self.requires("glfw/3.3.8")
        self.requires("opengl/system")
        self.requires("glm/cci.20220420")
        self.requires("stb/cci.20220909")
        self.requires("magic_enum/0.8.2")

    def generate(self):
        translation = {'glfw': 'glfw3', 'opengl': 'opengl_system'} # otherwise the generated files don't match, for some reason
        var_name = 'DEPENDENCY_TARGETS'
        link_target = []

        with open("dependencies.cmake", "w") as file:
            for req, dep in self.dependencies.host.items():
                pkg_name = translation[dep.ref.name] if dep.ref.name in translation else dep.ref.name

                file.writelines([
                    f"message(\"Calling find_package for {pkg_name}\")\n",
                    f"FIND_PACKAGE({pkg_name} REQUIRED)\n"
                ])
                link_target.append(f"{pkg_name}")
            file.writelines([f"set({var_name} {' '.join(link_target)})"])

    def layout(self):
        cmake_layout(self)
```

CMake:
```cmake
cmake_minimum_required(VERSION 3.19)
project(shards)

# ... flex & bison

EXECUTE_PROCESS(
        COMMAND "conan" "install" ".." "--build=missing" "-pr:b=default"
        WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
        RESULT_VARIABLE CONAN_EXIT_CODE
)

include("${CMAKE_BINARY_DIR}/generators/dependencies.cmake") # this is where the file is generated

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "-g -Wall -Wextra -pedantic -fconcepts-diagnostics-depth=5")
set(CMAKE_CXX_FLAGS_DEBUG "-DDEBUG")

add_executable(${PROJECT_NAME}
  # sources
)
# ... other in-project include directories

target_link_libraries(${PROJECT_NAME} ${DEPENDENCY_TARGETS}) # same var as in the python script
```

**Comment by memsharded** [comment]
Thanks for sharing the details.

This happens because the target names are different than the package names. By default they are ``<pkgname>::<pkgname>``, but there as exceptions like ``glfw`` package that it will be plain ``glfw``. This variability is not great, but it is what contributors in ConanCenter do to have the same target names as the "upstream", that means that the ``glfw`` library documents that it should be used with ``target_link_libraries(.... glfw)`` target instead of the ``glfw::glfw`` target.

So this should fix your code:
```pyhton
target = {"glfw": "glfw"}.get(dep.ref.name, f"{dep.ref.name}::{dep.ref.name}")
link_target.append(f"{target}")
```
I have tried here (Windows) and it seems to work, please give it a try.

**Comment by jay-tux** [comment]
That seems to work indeed. Thank you very very much for your help.

Still, I'd prefer if there would be an option to choose to use the more legacy implementation over the new Conan-agnostic system. Maybe a future feature?

**Comment by memsharded** [comment]
> Still, I'd prefer if there would be an option to choose to use the more legacy implementation over the new Conan-agnostic system. Maybe a future feature?

I am afraid this would be very unlikely. This legacy integration was removed because it is not possible to maintain multiple integrations for the same build-system, it takes too many resources, that we don't have. We cannot fight the ecosystem and provide a integration that goes against CMake best practices. It makes things more confusing and the ecosystem more fragmented.

**Comment by memsharded** [comment]
It seems this was responded and the response worked.
There are no plans to introduce back in 2.0 a legacy ``cmake`` integration that would implement something different than the standard ``CMake`` mechanism, which is via ``find_package()``, so closing this ticket. Thanks for the feedback!
