### ISSUE TITLE
[question] self.run() in Conan v2 no longer accepts a list argument

### ISSUE THREAD

**Issue by db4** [conan-io/conan#13510]
### What is your question?

`self.run(['command', 'opt'])` used to work in Conan 1.x, but it doesn't in Conan 2.x. (even with `shell=False`). Is it regression or it's excluded intentionally?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question.
It was excluded intentionally. In Conan 1.X there were some ugly hacks, as using the fact that the input was a list or not to change the ``shell`` value.
So Conan 2.0 simplified it:
- The command is always a string.
- There is a new ``self.run(...., shell=True)`` explicit argument to decide about ``shell`` behavior

**Comment by db4** [comment]
Hi @memsharded 

If command is always a string when how would one pass command line options unmodified? Proper escaping and quoting them on Windows is a nightmare...

**Comment by memsharded** [comment]
In practice, it has not been a big issue so far, do you have a very complicated command that you are calling and with arguments that need escaping? 

If not, it is not be documented, but maybe we want to document ``from tools.build import cmd_args_to_string`` utility for this purpose. I am not fully sure about this, as you said proper general escaping and quoting can be challenging, but in practice, escaping or quoting 1 particular conflictive argument is way easier, and can be done in the recipe without much effort.

**Comment by db4** [comment]
> In practice, it has not been a big issue so far, do you have a very complicated command that you are calling and with arguments that need escaping?

Generally speaking, file paths can potentially contain spaces, so if you pass them you should quote them. And quoting/escaping rules are very different for Windows and Unix shells (e.g. you just can't pass an option with LF character inside via cmd.exe, any escaping won't help) So in case of `subprocess.run` I always provide an arguments list and forget about shell specifics. I used to do the same for `self.run()` but if that's not possible anymore, `subprocess.run` is always an option for complex cases.

**Comment by memsharded** [comment]
``self.run()`` does a few things more than ``subprocess``, like adding all the environment files calls, and other stuff.

If you think it will help, we can consider the ``cmd_rags_to_string`` helper, please re-open so at least I can discuss it with the team
