### ISSUE TITLE
[bug] In the CMakeDeps Generator CONAN_FOUND_LIBRARY and CONAN_SHARED_FOUND_LIBRARY are not cleared

### ISSUE THREAD

**Issue by DanielDewald** [conan-io/conan#13512]
### Environment details

* Operating System+version: Windows 10 & Linux
* Compiler+version: MSVC 19 & gcc 11.3.0
* Conan version: 2.0.2
* Python version: 3.10.6

### Steps to reproduce

1. Create a conan project with a dependecy and CMakeDeps generator
2. execute conan install
3. Have a look at the created cmakedeps_macros.cmake

in the function `conan_package_library_targets` line 23 the variable `CONAN_FOUND_LIBRARY` is filled with the found library. This call will write the variable into the cache. The same goes for the variable `CONAN_SHARED_FOUND_LIBRARY` in line 35. While this works for the first library in this foreach loop, each following call will not search for the library and update the variable, but takes them from the cache. So this way all the libraries end up with the same .lib and .dll files. So either the variable needs to be cleared after each foreach loop, or the NO_CACHE option needs to be used in the find_library execution. Another possible solution would be to create a new variable for every library (e.g. CONAN_FOUND_LIBRARY_${LIB_NAME} and CONAN_SHARED_FOUND_LIBRARY_${LIB_NAME})

**Comment by memsharded** [comment]
Hi @DanielDewald 

Thanks for your report.
I think this shouldn't be an issue for ``CONAN_FOUND_LIBRARY``, as there is an ``unset()`` for it at the end of the loop.

> While this works for the first library in this foreach loop, each following call will not search for the library and update the variable, but takes them from the cache. So this way all the libraries end up with the same .lib and .dll files. 

If that was happening, the ``CMakeDeps`` generator would be quite broken, fortunately the ``unset()`` is preventing that.

It is true that that ``CONAN_SHARED_FOUND_LIBRARY`` is not being unset, so lets fix it.

(NO_CACHE can't be used, as the files should work in CMake 3.15, and that is like CMake >3.20)

**Comment by DanielDewald** [comment]
You're right of course. I did not see the unset for `CONAN_FOUND_LIBRARY` at the end of the loop. Just tested unsetting **both** variables in my CMake file, which solved the problem.

**Comment by memsharded** [comment]
Yes, thanks, proposing that fix in https://github.com/conan-io/conan/pull/13596 for next 2.0.3 release
