### ISSUE TITLE
[bug][conan2] conan create produces empty package for header-only package

### ISSUE THREAD

**Issue by bbandix** [conan-io/conan#13514]
### Environment details

With conan2 (version 2.0.2 on Linux) the command `conan create conanfile.py` produces a warning:
`header_only/0.0.1: package(): WARN: No files in this package!`
and produces an empty package, where as `conan export-pkg conanfile.py` correctly packages the header-only package contents.

**Expected behaviour**
`conan create` should also produce a package with the desired contents as specified in package() of the conanfile, as was the behaviour with conan 1.x.
 

### Steps to reproduce

Simplified example to demonstrate the problem:
preparation:
```
mkdir h
touch h/header.h
```

conanfile.py:
```
from conan import ConanFile
from conan.tools.files import copy
from os import path

class HeaderOnly(ConanFile):
    name = "header_only"
    version = "0.0.1"
    exports_sources = "include/*"
    no_copy_source = True

    def package(self):
        copy(
            self,
            "*.h",
            src=path.join(self.source_folder, "h"),
            dst=path.join(self.package_folder, "include"),
        )

    def package_id(self):
        self.info.clear()  # header-only
```

### Logs

$ `conan create conanfile.py`
```
...
header_only/0.0.1: Calling package()
header_only/0.0.1: package(): WARN: No files in this package!
...
```
$ `conan export-pkg conanfile.py`
```
...
conanfile.py (header_only/0.0.1): Calling package()                                                                                                                                                                                          
conanfile.py (header_only/0.0.1): package(): Packaged 1 '.h' file: header.h  
...
```

**Comment by memsharded** [comment]
Hi @bbandix 

I'd say the issue is in your ``exports_sources`` pattern. If you want to export the sources to be able to ``conan create``, the pattern shoudl include it, something like ``exports_sources = "h/*"``? Make sure that the export stage is listing the files that is exporting into the recipe

**Comment by bbandix** [comment]
Hi @memsharded,

Indeed, even without exports_sources conan create does not work, but if I change the entry to `h/*`, create also finds the contents.

I think this should be mentioned in the docs somehow.

**Comment by bbandix** [comment]
I think the behaviour changed there from conan 1.x, since if you left out the 
```
    exports_sources = "include/*"
    no_copy_source = True
```
attributes it still worked with conan create, now you **have to** use exports_sources.

Was this change intended?

**Comment by memsharded** [comment]
It seems that with conan 1.x the above still produces the same as in 2.0:

```
conan create .   # same result both in 1.X and 2.0
header_only/0.0.1: Calling package()
header_only/0.0.1 package(): WARN: No files in this package!
```

I have just tested it. The ``exports_sources = "include/*"`` seems incorrect in both cases.
Could you please double check, or clarify it? Thanks!

**Comment by bbandix** [comment]
Hi @memsharded,
Indeed even with 1.59 a correct exports_sources is necessary for `conan create` to work correctly, sorry for the noise.
I have no idea how our recipe worked previously, maybe as a side-effect of a bug on an older version, in any case I have corrected it now, thanks for the help.
