### ISSUE TITLE
[question] What is the purpose of changing the option `-f` to `-c` in `conan remove` in Conan v2?

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#13525]
### What is your question?

What is the purpose of changing the option `-f` to `-c` in `conan remove` in Conan v2?

`-f` is standard by default, i.e. `rm -f ...`

`--confirm` is confusing. E.g. in PowerShell `-Confirm` means "Prompts you for confirmation before running the cmdlet", `Remove-Item -Confirm ...`

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @DmitrySokolov thanks for your question!

The main reasoning behind it is homogeneization. Conan 2 tries to simplify the CLI and we wanted to separate the "override a Conan decision" from "skip confirmation", so --force was chosen for the first and --confirm for the second.

See https://github.com/conan-io/conan/issues/12523 for the initial PR that impemented it for initial reasoning :)

**Comment by DmitrySokolov** [comment]
OK, I see.

A lot of software uses `-quiet`, `-silent` for that purpose.

**Comment by DmitrySokolov** [comment]
Also, for this purpose

pacman uses `--noconfirm`

hg uses `--no-confirm`

**Comment by AbrilRBS** [comment]
As you can see, there's plenty of variability in the wild, and Conan just chose from one of the available ones :)

**Comment by DmitrySokolov** [comment]
Yes, but the meaning of `--confirm` option is the opposite in plenty of tools.

There is a common practice to provide `--option` and `--no-option` options, with some default value (it can be as positive, as negative).
