### ISSUE TITLE
[question] Iteratively resolve dependency graph through Python API

### ISSUE THREAD

**Issue by TimZoet** [conan-io/conan#13539]
### What is your question?

I have a perhaps somewhat peculiar question/feature request. I'm currently using the Python API to determine the dependencies of a package that is being built (i.e. the `conan.api.conan_api.ConanAPI` class, and subclasses). Obviously, if we are trying to build some package `A` that has a number of (transitive) dependencies these must be available in the local cache or some known remote. We cannot do that if  `B` or `C` are completely unknown:
```
A > B > C
```
However, I have a situation where that is not yet the case. What I want to do is request the **direct** dependencies of the root package `A` and using their names, channels, etc., determine some Git repository that needs to be retrieved. Each of these repositories contains its own Conan package. We therefore repeat this trick recursively, since they too might have unknown dependencies that need to be retrieved. A sample script that can be invoked with some root conanfile:

```py
import argparse
from conan.api.conan_api import ConanAPI
import os
import subprocess

def traverse(api, profile, conanfile, directory):
    # Tries to resolve complete graph, which obviously fails because packages are not known yet.
    # Let's pretend there is an option that can load direct dependencies only. Naturally, this is a bit
    # flawed since the packages higher up might be changing options of the current package and
    # we lack that context here.
    deps_graph = api.graph.load_graph_consumer(conanfile, None, None,
                                               None, None,
                                               profile, profile, None,
                                               [], [], False, False)

    for dep in deps_graph.direct_dependences:
        # If we have a dependency to some known package, e.g. Boost,
        # this will automatically be retrieved from ConanCenter.
        # It is only our own packages that we are interested in.
        if dep.conanfile.user != "timzoet":
            continue
        
        path = os.path.join(directory, dep.conanfile.name)
        
        # Do a checkout of our own package repository.
        subprocess.run([
            "git", "clone", "--depth", "1",
            "-b", dep.conanfile.channel,
            f"https://github.com/TimZoet/{dep.conanfile.name}.git",
            path
        ], check=True)

        # Recurse on any direct dependencies of this one before exporting.
        traverse(api, profile, dep.conanfile, directory)

        # All direct and transitive dependencies are now available in the local cache
        # because of above recursive call. We can safely export.
        subprocess.run([
            "conan", "export",
            "--user", dep.conanfile.user,
            "--channel", dep.conanfile.channel,
            path
        ], check=True)

if __name__ == "__main__":
    # This script can be invoked with parameters to the root package, a profile with which to build,
    # and a temporary directory in which to checkout dependencies.
    parser = argparse.ArgumentParser()
    parser.add_argument("--conanfile", required=True)
    parser.add_argument("--profile", required=True)
    parser.add_argument("--directory", required=True)
    args = parser.parse_args()

    api = ConanAPI()
    profile = api.profiles.get_profile([args.profile])
    traverse(api, profile, args.conanfile, args.directory)
```

I've browsed through the Conan code a bit, and I see that the `DepsGraphBuilder` is responsible for calculating the graph of a given package. Is it at all possible to adapt this class to not do this recursively, but iteratively, doing each step 'on demand'?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by TimZoet** [comment]
Did some tinkering myself. Added in a parameter to some of the graph construction functions that allows injecting a callback. This callback is called for each node, just before it is constructed. Changeset: TimZoet/conan@721e528

The sample code above can now be greatly simplified to the following:

```py
import argparse
from conan.api.conan_api import ConanAPI
from conans.model.requires import Requirement
import os
import subprocess

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--conanfile", required=True)
    parser.add_argument("--profile", required=True)
    parser.add_argument("--directory", required=True)
    args = parser.parse_args()

    visited = []

    def callback(require: Requirement):
        if require.ref.user != "timzoet":
            return
        if require.ref.name in visited:
            return
        visited.append(require.ref.name)
        
        path = os.path.join(args.directory, require.ref.name)
        subprocess.run([
            "git", "clone", "--depth", "1",
            "-b", require.ref.channel,
            "--recurse-submodules",
            f"https://github.com/TimZoet/{require.ref.name}.git",
            path
        ], check=True)
        subprocess.run([
            "conan", "export",
            "--user", require.ref.user,
            "--channel", require.ref.channel,
            path
        ], check=True)

    api = ConanAPI()
    profile = api.profiles.get_profile([args.profile])
    deps_graph = api.graph.load_graph_consumer(args.conanfile, None, None,
                                               None, None,
                                               profile, profile, None,
                                               [], [], False, False,
                                               callback)

```

**Comment by memsharded** [comment]
Hi @TimZoet 

Thanks for your question.
I am afraid that what you are trying to do is not possible. 
Please have a look to: https://docs.conan.io/2/knowledge/guidelines.html. 
As explained there, Conan is not re-entrant. You cannot call Conan from conan itself, calling ``conan export`` via a subprocess.call inside a Conan Python API call is undefined behavior and anything can happen.

If you have your own repo with recipes, something similar to conan-center-index, this would be the approach:
- at the moment, do an iterative ``export`` of all recipes that you need. We are adding custom commands that do this in https://github.com/conan-io/conan-extensions/pull/6
- We will be adding more functionality in the future, to manage a ``conan-center-index`` fork as a Conan remote, that will avoid having to export things before using them

Otherwise, it is not expected that we will be adding this kind of hooks into the graph expansion itself, the problem it is too complex, with too many implications and side effects (from conflicts, relation with lockfiles, updates, managing revisions...).

**Comment by TimZoet** [comment]
I don't think the export_all command is going to completely solve my problem. As far as I can tell, this still requires knowing all the required packages upfront, which is exactly what I'm trying to avoid. Or rather, I want to automate this.

If somewhere in the package's dependency graph something changes about one of my own packages, whether that is a version, channel, option, or a wholly new package... I want to automatically retrieve the sources from a matching Github repo, figuring out the appropriate branch from the channel. If I have to maintain a list of all my packages and their versions and channels, well.. so much for automation.

With a small adaptation, I can avoid the undefined behaviour and do without the callback. Just inspect the `error` reported by the graph construction. If it is a missing recipe error for one of my packages, it can be retrieved outside of the Conan context. Repeat until all packages have been found:

```py
# Iteratively discover missing pacakges by trying to construct the dependency graph.
while True:
    # Try to construct dependency graph.
    deps_graph = api.graph.load_graph_consumer(args.conanfile, None, None,
                                               None, None,
                                               profile, profile, None,
                                               remotes, [], False, False)
    
    # No error means all good, all packages found.
    if not deps_graph.error:
        break
    
    if deps_graph.error.kind != GraphError.MISSING_RECIPE:
        raise RuntimeError(f"Unexpected error while traversing graph: {deps_graph.error}")
    
    # Missing package from someone else.
    if deps_graph.error.require.ref.user != "timzoet":
        raise RuntimeError(f"Unexpected error while traversing graph: {deps_graph.error}")
    
    # Retrieve and export our own package.
    export(args.directory, deps_graph.error.require)
```

**Comment by memsharded** [comment]
Thanks for the explanation. I am afraid I still think this approach will be very problematic: What will you do when you get a ``requires`` that is ``somepkg/1.2.3#revision1``? How will you map that to the sources in the repo? it is basically not possible. This situation will happen in different scenarios, like when using lockfiles (note, lockfiles are used also when resolving the dependency graph ``test_package``, to guarantee that the ``test_package`` is testing what was just created. Resolving in repos using branches also breaks package immutability, which is another strong assumption in Conan 2.0, and internal Conan caching might resolve incorrectly too.

It is strongly recommended to do the ``export`` (or better, the ``create``) for the packages in advance, like when changes are pushed to the the git repo, the CI runs the ``export/create`` and uploads the package to make it available.

**Comment by TimZoet** [comment]
Yeah, although I stated at the beginning that this was all "somewhat peculiar", the "somewhat" is definitely a bit of an understatement. At least if you care about more modern standards, and things like reproducible builds<sup>TM</sup>.

My main motivation is that I want to be lazy. If I have some dev branch in `C` with new work, I want to build `A` without having to update the conanfiles in both downstream packages `A` and `B`. Instead, all packages should be built from source. Updating not one, but three repositories and their lockfiles slows me down when I'm experimenting.

Also, I'm playing around with GitHub Actions. I'm poor (read: cheap), so using the public runners. These don't have a persistent environment, so I'd still have to figure out a way to retrieve my own packages from somewhere, since there is no remote, official or otherwise, in which the packages were created. And that's the part I'd like to automate with the above script. See again motivation numero uno, laziness.

Anyway, I'll see how far I can get with my current solution. Thank you very much for your time and explanations.

**Comment by memsharded** [comment]
> My main motivation is that I want to be lazy. If I have some dev branch in C with new work, I want to build A without having to update the conanfiles in both downstream packages A and B. Instead, all packages should be built from source. Updating not one, but three repositories and their lockfiles slows me down when I'm experimenting.

For this use case I'd probably check the ``editables``, it allows to quickly iterate changes in several packages at the same time.
