### ISSUE TITLE
[question] Conan V2: how to access run environment variables in test() method

### ISSUE THREAD

**Issue by forthib** [conan-io/conan#13536]
### What is your question?

Hello,

I'm trying to modify the recipe of 'tcl' (in conan-center-index) to support conan v2.
In test_package, the `test()` method do the following:
```
self.run("{} {}".format(os.environ["TCLSH"], os.path.join(self.source_folder, "hello.tcl")), run_environment=True)
```
How to write it using conan v2 and VirtualRunEnv? How to access VirtualRunEnv variables in `test()` function? I tried:
```
with self.runenv.vars(self).apply():
    print(os.environ.get("TCLSH"))
```
but it does not work, as `self.runenv` (and `self.runenv_info`) is empty at this point.

Full modifications can be found here: https://github.com/forthib/conan-center-index/tree/tcl_conanv2

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @forthib 

Thanks for your question
There could be different approaches, but I think that the simplest would be: ``self.run(cmd, env="conanrun")`` will execute ``source conanrun.sh && cmd``, making the env-vars available for ``cmd`` execution, I think that should work for your use case.

**Comment by forthib** [comment]
Hello @memsharded 

Thank you! Indeed it works on Linux. On Windows `cmd` is not evaluated at runtime, so I wrote a small `hello.bat` and it works well.
Then the code looks like it:
```python
if self.settings.os == "Windows":
    self.run(os.path.join(self.source_folder, "hello.bat"), env="conanrun")
else:
    self.run(f"$TCLSH {os.path.join(self.source_folder, 'hello.tcl')}", env="conanrun")
```
with `hello.bat`:
```cmd
%TCLSH% %~dp0hello.tcl
```

**Comment by memsharded** [comment]
Yes, exactly, in Windows the command expansion evaluates first and does all replacements, then runs, so any potential environment variable definition that happens first is not used in the second part of the command if the %PLACEHOLDER% is directly in command line, but if it is executed inside a batch, it does work.
