### ISSUE TITLE
[feature] Provide a way to easily find if a recipe name is contained in self.dependencies

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13537]
### What is your suggestion?

A syntax like `deps in self.dependencies` would be useful for migration to conan v2 of libxslt: https://github.com/conan-io/conan-center-index/pull/16205

Currently when deps doesn't exist, it fails with an assertion error:

https://c3i.jfrog.io/c3i/misc/logs/pr/16205/5-configs/windows-visual_studio/libxslt/1.1.34//352acd5773c2def61f9be899612437fc6f06f167-build.txt

```
while calling '_build_msvc', line 148
	if "icu" in self.dependencies:
	AssertionError: 
```

I guess `UserRequirementsDict` class needs an implementation of `__contains__(self)`?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
This might be possible, but it is a bit trickier than it seems.

Wouldnt ``if self.dependencies["libxml2"].options.icu`` achieve the same?

**Comment by SpaceIm** [comment]
> Wouldnt if self.dependencies["libxml2"].options.icu achieve the same?

I guess. I don't like to rely too much on internal details of dependencies in downstream recipes (icu may come from another recipe, not super future proof).

**Comment by AbrilRBS** [comment]
2.0.15 has support for the `in` operator in `self.dependencies`. Please let us know if you have any feedback, closing this as solved :)
