### ISSUE TITLE
[question] cmake_layout in test_package

### ISSUE THREAD

**Issue by db4** [conan-io/conan#13534]
### What is your question?

The common pattern for test_package is nowadays

```python
    def layout(self):
        cmake_layout(self)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

it works well until you create/test several package options/settings configurations in sequence (for example, during CI). As they share the same `build` folder, `CMakeCache.txt` persists between test runs. This creates undesired side effects. To work around them I have to change `build` method in my recipes to:

```python
    def build(self):
        cache = os.path.join(self.build_folder, "CMakeCache.txt")
        if os.path.exists(cache):
            self.output.info(f"Removing {cache}")
            os.remove(cache)
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

but I'm afraid this issue could exist for many CCI recipes that one cannot easily modify (before  `cmake_layout` introduction each build resided in its own hash-named directory). Can it be solved on Conan level?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by samuel-emrys** [comment]
I would suggest setting `tools.cmake.cmake_layout:build_folder_vars` to avoid clobbering your build directory, i.e., in your profile:

```
[conf]
# whichever settings/options you care to vary
tools.cmake.cmake_layout:build_folder_vars=['settings.compiler', 'options.shared']
```

**Comment by db4** [comment]
@samuel-emrys
Thanks for your suggestion. Maybe `tools.cmake.cmake_layout:build_folder_vars` is supposed to help but it can't in the case of test_package.  First, `build_folder_vars` takes settings/options from test_package Conanfile which is pretty useless (one would need to examine Conanfile of the tested reference). Second, it's impossible to make **any** settings/options change affect the build folder name.

**Comment by memsharded** [comment]
Thanks for your report @db4 

This is one of the inconvenient side effects of the cmake_layout in test_package.
It should be solved in Conan 2.0, where the test build folder is removed if possible, so it doesn't reuse previous build.

> First, build_folder_vars takes settings/options from test_package Conanfile which is pretty useless (one would need to examine Conanfile of the tested reference). Second, it's impossible to make any settings/options change affect the build folder name.

this is not fully clear. The ``settings`` of the ``test_package`` are in practice always similar, or even more complete than the package itself (ex. a header-only ``conanfile.py`` without settings, will have a ``test_package`` with all the settings. While the opposite seems not a case. The "second" point, that it is impossible to make "any" settings/option affect the build folder name is not clear, if you could please clarify.

**Comment by db4** [comment]
Hi @memsharded 
> It should be solved in Conan 2.0, where the test build folder is removed if possible, so it doesn't reuse previous build.

Great, could you backport it to 1.60? It should be not very hard but would prevent quite unobvious errors.

> The "second" point, that it is impossible to make "any" settings/option affect the build folder name is not clear, if you could please clarify.

Sorry for that, I should be more specific. Yes, settings are almost always the same, but options are not. And I need to create packages with different sets of options.

**Comment by jeremy-coulon** [comment]
I was in the process of migrating my recipes to Conan v2 but I am impacted by this issue.
I cannot test the new CMake helpers while still running Conan 1.x.

For example, my CI (using CPT) fails with the following:
```
mypackage/v425@me/testing (test package): Calling build()
CMake Error: Error: generator : Visual Studio 17 2022
Does not match the generator used previously: Visual Studio 16 2019
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```

Removing the `test_package/build` folder before each `conan create` seems to be a good solution for Conan 1.x. 
I don't think anyone care about keeping this build folder between each run.

**Comment by memsharded** [comment]
We have considered this but the problem is this is the code for removing the test folder:

```python
  base_folder = os.path.dirname(conanfile_abs_path)
  conanfile = app.loader.load_basic(conanfile_abs_path)
  if hasattr(conanfile, "layout"):
      delete_after_build = False
      test_build_folder = base_folder
  else:
      test_build_folder, delete_after_build = _build_folder(test_build_folder,
                                                            graph_info.profile_host,
                                                            base_folder)
      rmdir(test_build_folder)
```
The ``test_build_folder`` in the case the layout is defined is the ``conanfile`` containing folder, that is ``test_package``. That folder obviously can't be removed, because it will destroy the contents of ``test_package``. We did an attempt to do it in another place, but it was a bit of a mess and fragile, so it didn't move forward.

**Comment by memsharded** [comment]
I think this might be outdated and solved by the addition of ``tools.cmake.cmake_layout:build_folder`` and ``tools.cmake.cmake_layout:test_folder`` some time ago in Conan 2

Please let me know if these confs solve your issues.
