### ISSUE TITLE
[feature] Add bindirs to pkgconfig generator

### ISSUE THREAD

**Issue by bruchar1** [conan-io/conan#13532]
### What is your suggestion?

pkg-config generator is useful to use conan dependencies in meson build system, especially on Windows. However, meson has no way of knowing where the DLL files are located, since the linkage is done on the import libraries.

Providing a `bindir` variable to the generated .pc file would allow meson (an possibly other systems) to query pkg-config for the location of the shared library binaries.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Maybe @RubenRBS can help a bit with this one. The important things to investigate are:

- Is there any possible side effect of adding the ``bindir``? 
- What if it adds executable paths to the host context that will affect the build context, like the typical ``protobuf`` example with protobuf both in host and build contexts?

**Comment by AbrilRBS** [comment]
Hi @bruchar1 I have tried to implement your request to the best of my understanding of what you were requesting. Could you please confirm that the linked PR would solve your issue? Thanks! :)

**Comment by bruchar1** [comment]
Yes, at first sight, it does what I need. However, I don't use cross compiling, so I cannot answer @memsharded question. Also, I'm not very familiar with Jinja2. Other variables use `%` notation, but I suppose `.format` works as well.

**Comment by AbrilRBS** [comment]
Yeah no worries about the implementation itself, just the pkg-conf feature :) Thanks for the confirmation, helps a lot!
