### ISSUE TITLE
[bug] Xcode 14.2 with macos sdk 13.1 not working

### ISSUE THREAD

**Issue by rockdreamer** [conan-io/conan#13530]
### Environment details

* Operating System+version: MacOS 13.2
* Compiler+version: Xcode 14.2
* Conan version: 1.59.0
* Python version: 3.8

### Steps to reproduce

Setting macos sdk to 13.0 and building cmake on a default install of xcode 14.2 fails

**Comment by memsharded** [comment]
This was fixed in https://github.com/conan-io/conan/pull/13531 for next 2.0.3 (PR targeted to ``release/2.0`` branch.
But this issue reports for 1.59, is it a mistake or intended?

**Comment by rockdreamer** [comment]
Hi @memsharded that was intended as we're still on 1.x at work. Will post a cherry pick
