### ISSUE TITLE
[feature] A None installer version for windows(zip)

### ISSUE THREAD

**Issue by Rikitik** [conan-io/conan#13541]
Is it possible to provide a none installer version for windows?

**Comment by memsharded** [comment]
Hi @Rikitik 

Thanks for your suggestion.
Quick question: why the provided installer is not enough for your use case? 

Even if we don't directly provide such zip, it is possible to use the ``pyinstaller.py`` in the root of the repo, it will create the Windows executable, you can put it in a zip, please check: https://docs.conan.io/2/installation.html#use-a-system-installer-or-create-a-self-contained-executable

**Comment by Rikitik** [comment]
I use a portable setup and move between enviroments a lot.
Thanks that may work just fine didnt find that in the docs yet

**Comment by memsharded** [comment]
Ok, let us know how it goes with ``pyinstaller.py``

**Comment by czoido** [comment]
Hi @Rikitik, we are working on this feature for the current sprint so it will probably be available starting in Conan 2.0.6 that will be released soon. I'll ping you back when it's ready.

**Comment by czoido** [comment]
Hi @Rikitik, 
We have been distributing zipped executables for Windows for some Conan versions now. Please check those in: https://conan.io/downloads
I'm closing this issue, but please feel free to reopen or open another issue if you have more questions. Thanks!
