### ISSUE TITLE
[question] How to specify multiple options at the same time?

### ISSUE THREAD

**Issue by michaelchao** [conan-io/conan#13549]
### What is your question?

Here is my part of conanfile.py:

```
class Myexpect(ConanFile):
    options = {"soc": ["A", "B", "C", "D"]}
```

then I want to specify two **soc** at the same time, just like:

```
conan install ..... -o soc=A,B
```

I got a error, How can I get my target?? Does conan support this kind of usage??

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by michaelchao** [comment]
It seems that it will not be implemented  if your option item type is none of python str.
I found a solution:

```python
class Myexpect(ConanFile):
    options = {"soc": "ANY"}
```

then 

```shell
conan install ..... -o soc=A,B // Ok, no error
# then call
conan build .... # In def build(...) in conanfile.py. we get soc by calling self.option.soc and handle it, for example, split it, check it and so on
```

By the more, conan is so interesting!

**Comment by memsharded** [comment]
Hi @michaelchao 

Thanks for your question and for your follow up with your solution.

Indeed, the ``options`` definition is a set of possible, exclusive values. This is intended to minimize error like typos and the like.
If you have a limited set of options you can also do:
```python
options = {"a": [True, False],
         "b": [True, False],
          ...}
```
Which might be more convenient for usage (no need to parse the string), and for other possible things like ``package_id`` (being more robust against errors, like ``a,b``, ``a, b``, ``b, a``, ``A, B`` resulting all in different binaries ``package_id``) definition, reporting by ``conan list``, etc.
