### ISSUE TITLE
How to find remotes server

### ISSUE THREAD

**Issue by definename** [conan-io/conan#1354]
Hi all,
Curently I am using only one remote server that is: conan.io
My question is how/where to find another remote servers?

**Comment by memsharded** [comment]
Hi!

Conan is decentralized, there is no way to "discover" or "search" for other remote servers. Typically you connect to the servers you want: your company/team server, the central conan.io server (very soon conan-center in bintray), or the servers of software providers you want to use.

**Comment by definename** [comment]
Thanks got it.
