### ISSUE TITLE
[question] Conan-hosted dependency breaks a build

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#13540]
### What is your question?

One of our recepies, has a dependency on 7-zip:

`self.build_requires("7zip/19.00")`

This used to work for a long time, however now it fails with:

```
ERROR: 7zip/19.00: Cannot load recipe.
Error loading conanfile at 'C:\Users\runner1\.conan\data\7zip\19.00\_\_\export\conanfile.py': Unable to load conanfile in C:\Users\runner1\.conan\data\7zip\19.00\_\_\export\conanfile.py
  File "c:\python38\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\runner1\.conan\data\7zip\19.00\_\_\export\conanfile.py", line 1, in <module>
    from conan import ConanFile
ImportError: cannot import name 'ConanFile' from 'conan' (c:\python38\lib\site-packages\conan\__init__.py)
```

I suspect something had changed, and the relevant package was rebuilt/updated for a more recent version of Conan (we use 1.41). But, perhaps, it's something else. How can it be fixed (short of eliminating this dependency, or replacing it with our own)?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by w3sip** [comment]
Update: the error persists even when using
```
self.build_requires("7zip/19.00@#7e1fae98e076cf075bea743444b918dd")
```
e.g. using revision that seems to have a compatible `required_conan_version = ">=1.33.0"`

Looks like no matter which revision is specified in the requirements, the file at `\Users\runner1\.conan\data\7zip\19.00\_\_\export\conanfile.py` is from the latest revision.

**Comment by memsharded** [comment]
Hi @w3sip 

Thanks for your question.
I guess that you are using dependencies directly from ConanCenter? We are recommending for production usage to have a copy of the dependencies in your own server repo, to avoid any kind of breakage and possible disruption.

Indeed the community has been modernizing the recipes in ``conan-center-index`` and as described in the the stability commitment, to be able to use ConanCenter, it is necessary to upgrade to the latest Conan version. Now that Conan 2.0 we will still maintain compatibility with latest 1.X for a while, to let time for users, to upgrade, but still latest 1.X might be necessary.

What is not clear to me is why an older revision won't work. I have checked that:
```
$ conan get 7zip/19.00@#7e1fae98e076cf075bea743444b918dd -r=conancenter
from conans import ConanFile, tools, AutoToolsBuildEnvironment
from conans.errors import ConanInvalidConfiguration
import os
```
So it seems that version will not use the modern ``from conan import ConanFile`` but the legacy ``from conans import ConanFile``

Have you tried to force remove the old ``7zip`` revision, and reinstall it with that revision? It would be worth trying and inspecting the recipe in the cache, to see if it is the new one or old one:

**Comment by w3sip** [comment]
Yea, I manually deleted the entire ./data/7-Zip folder every time. The recipe in `_/_/export/conanfile.py` after it always was the one from the latest revision.

On the road now, so can't test on the node with `1.41.0`, but my laptop with `1.53` doesn't seem to work:

```
alex@apple-macbook-air-alex src % conan --version
Conan version 1.53.0
alex@apple-macbook-air-alex src % conan get 7zip/19.00@#7e1fae98e076cf075bea743444b918dd -r=conancenter
from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.files import download, chdir, replace_in_file
from conans import tools, AutoToolsBuildEnvironment
import os

required_conan_version = ">=1.47.0"
```

**Comment by memsharded** [comment]
Something really weird happening there, that revision doesn't match the code you are seeing, no idea why.

I am not sure how you are installing that revision, there might be some side effect of multiple revisions competing against the others. If you could try to use a temporary clean cache just in case there would be something corrupted. Like:

- set CONAN_USER_HOME=some/temp/folder
```bash
$ conan get 7zip/19.00@#7e1fae98e076cf075bea743444b918dd -r=conancenter    
from conans import ConanFile, tools, AutoToolsBuildEnvironment                          
from conans.errors import ConanInvalidConfiguration                                     
import os                                                                               
                                                                                        
required_conan_version = ">=1.33.0"    
 ```

**Comment by w3sip** [comment]
```
alex@Alexanders-MacBook-Air ~ % export CONAN_USER_HOME=/tmp/.conan
alex@Alexanders-MacBook-Air ~ % mkdir /tmp/.conan
alex@Alexanders-MacBook-Air ~ % conan get 7zip/19.00@#7e1fae98e076cf075bea743444b918dd -r=conancenter
WARN: Remotes registry file missing, creating default one in /tmp/.conan/.conan/remotes.json
from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.files import download, chdir, replace_in_file
from conans import tools, AutoToolsBuildEnvironment
import os
```
The setting does have effect in a sense that `/tmp/.conan` is populated with some files, but as you can see that doesn't change the output.

**Comment by memsharded** [comment]
Oh I think that I know what happens, you might not have activated revisions. I could reproduced with revisions disabled.
Please try:
- set CONAN_USER_HOME
- ``conan config set general.revisions_enabled=True``
- ``conan get 7zip/19.00@#7e1fae98e076cf075bea743444b918dd -r=conancenter``

**Comment by w3sip** [comment]
Yup, that did it. Many thanks!
