### ISSUE TITLE
[question] More robust implicit building of dependencies

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#13553]
### What is your question?

Hi,

In the last weeks I painfully experienced that the process of building dependencies **implicitly** with a command like `conan create ... --build missing` is not the same in terms of robustness of the build as building it **explicitly** via `conan install ...`. I'm cross-building for armv8, so this might add some more problems as the recipes conan-center are not always tested as good as e.g. for x86, but this is just to give some more context. I'm also not sure whether this is more related to recipes itself or a problem in Conan in general.

See the analysis/comments [here ](https://github.com/conan-io/conan-center-index/issues/9222#issuecomment-1463745516) and following for some more context and examples. I found more cases where this is happening: too many, so we switched our approach to building 3rd party components in our environment.

From a simple `conan create . --build missing -pr:h armv8 -pr:b default` which kind of starts the build at the top of the dependency graph and pushes the required attributes to the dependencies (to my understanding), to a bottom-up approach where every build is started explicitly using lockfiles, somehow like this:
```
conan lock create --reference ${name}/${version} --build -pr:h ${profile} -pr:b default
conan lock build-order conan.lock --json build-order.json
ORDER=\$(cat build-order.json | jq -r '.[] | .[] | .[0]+" "+.[2]')

while read -r line; do
    NAME_CONTEXT=(\$line)
    NAME=\${NAME_CONTEXT[0]}
    CONTEXT=\${NAME_CONTEXT[1]}

    if [ "\$CONTEXT" = "host" ]; then
        conan install "\$NAME" --build missing -pr:h ${profile} -pr:b default
    fi

    if [ "\$CONTEXT" = "build" ]; then
        conan install "\$NAME" --build missing --build-require -pr:h ${profile} -pr:b default
    fi
done <<< "\$ORDER"
```

From my experience the transfer of build attributes is not always working as it should.
_Edit: after reading again, the following problem is maybe not the best one for this topic ..._
One of my most recent cases is that I tried to build `libsystemd` with Conan 2.0 with `conan install --requires=libsystemd/251.4@ --build missing -pr:h armv8 -pr:b default -s build_type=Release`

<details><summary>Profile</summary>

```
[buildenv]
CC=/usr/bin/aarch64-linux-gnu-gcc
CXX=/usr/bin/aarch64-linux-gnu-g++
STRIP=/usr/bin/aarch64-linux-gnu-strip
RANLIB=/usr/bin/aarch64-linux-gnu-ranlib
AR=/usr/bin/aarch64-linux-gnu-ar
AS=/usr/bin/aarch64-linux-gnu-as
OBJCOPY=/usr/bin/aarch64-linux-gnu-objcopy
LD=/usr/bin/aarch64-linux-gnu-ld
ARCH=arm64

[options]
*:shared=True
pcre2/*:shared=False

[settings]
os=Linux
arch=armv8
compiler=gcc

compiler.version=10.2
compiler.libcxx=libstdc++11
compiler.cppstd=gnu17
```

</details>

This was failing with
`../src/meson.build:3:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not /usr/bin/aarch64-linux-gnu-ld.`

So somehow the linker for host and build context are mixed up here, because once I remove the `LD` definition from [buildenv], this is working fine again.

```
Program tools/meson-build.sh found: YES (/home/user/.conan2/p/t/libsyf5c84a9ee80bf/b/src/tools/meson-build.sh)
C++ compiler for the build machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the build machine: c++ ld.bfd 2.35.2
C++ compiler for the host machine: /usr/bin/aarch64-linux-gnu-g++ (gcc 10.2.1 "aarch64-linux-gnu-g++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host machine: /usr/bin/aarch64-linux-gnu-g++ ld.bfd 2.35.2
```

I would really like to use commands like "conan create ... --build=missing" because it's just awesome to create a whole dependency graph with one command, especially when cross-compiling where the packages are not available on conan center.
But currently I experience that this is not working reliably in quite some cases.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tbsuht 

Thanks very much for  your feedback

>  I'm also not sure whether this is more related to recipes itself or a problem in Conan in general.

I'd say it is a mixture of 2 factors: recipes in ConanCenter are not that well prepared for some cross-building scenarios, but also that the upgrade to Conan 2.0, and thus the upgrade to the new cross-build paradigm (already available in Conan 1.X) of providing the 2 build and host profiles is happening at this moment.

Conan 1.X ConanCenter pipeline is NOT using the 2 profiles approaches, for backward compatibility, but that limits the amount of testing that is done for cross-build scenarios

Conan 2.0 ConanCenter pipeline already use the 2 profiles, but recipes are doing some tricks to keep backward 1.X compatibility with 1 profile, which is something that will be dropped. This is now the largest effort by the Conan team and the community by far.

> ../src/meson.build:3:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not /usr/bin/aarch64-linux-gnu-ld.

Yes, this seems more like a specific recipe issue, could be also related to the ``MesonToolchain`` integration, or to the specific ``meson-build.sh`` script (belongs to the library), that is doing something unexpected.

If that is the case, we could have a look to it, but would probably be better to spin a dedicated issue as "bug" for it, it will be more clear.


> I would really like to use commands like "conan create ... --build=missing" because it's just awesome to create a whole dependency graph with one command, especially when cross-compiling where the packages are not available on conan center.
But currently I experience that this is not working reliably in quite some cases.

Yeah, I can totally feel your pain. We are working very hard to make this possible again in 2.0, and we have some things planned in our roadmap to improve this, like adding some cross-compilations to ConanCenter CI. It will take a bit of time, but when we gradually move away from Conan 1.X and 2.0 becomes more mainstream, it will indeed be possible.

**Comment by tbsuht** [comment]
@memsharded just some feedback:

We just finished the migration to Conan 2.x and the pain points above improved a lot!

Thanks for the nice work, the migration worked quite smoothly.

**Comment by memsharded** [comment]
> We just finished the migration to Conan 2.x and the pain points above improved a lot!

Many thanks for your feedback @tbsuht 

I am very happy to hear that. We work super hard to try to deliver a better Conan 2.0, so even if the migration, specially in ConanCenter with the migration of all recipes to Conan 2.0 is hard, it is being worth it.

Maybe we can close this ticket now? Thanks!
