### ISSUE TITLE
[bug] Invalid work cppstd

### ISSUE THREAD

**Issue by AbakumovAG** [conan-io/conan#13559]
### Environment details

* Operating System+version: ubuntu 22.04
* Compiler+version: gcc-10.4.0
* Conan version: 2.0.2
* Python version: 3.10.6

### Steps to reproduce

I try to create conan package for our fork of TensorRTYollo and using conanfile.py:
`
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import copy
import os

class TensorRTYoloConan(ConanFile):
    name = "tensorrt_yolo"
    settings="arch", "os", "build_type", "compiler"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": True, "fPIC": True}

    def configure(self):
        self.settings.compiler.cppstd = 17

    def source(self):
        self.run("git clone --branch AbakumovBranch http://gl.vmx.org/vvs/TensorRTYolo.git")

    def layout(self):
        cmake_layout(self, src_folder="")

    def generate(self):
        generator_name = ""
        if self.settings.os == "Linux": generator_name = "Ninja"
        tc = CMakeToolchain(self, generator=generator_name)
        tc.variables["CMAKE_BUILD_TYPE"] = self.settings.build_type
        tc.variables["CMAKE_CXX_COMPILER"] = self.settings.compiler
        tc.generate()

        deps = CMakeDeps(self)
        deps.generate()

    def build(self):
        print("BUILD - self.source_folder="+self.source_folder)
        cmake = CMake(self)
        cmake.configure(build_script_folder=os.path.join(self.source_folder, "TensorRTYolo"))
        cmake.build()
`
But in compiling I get such Error:

> [10/18] Building CXX object CMakeFiles/TensorRTYolo.dir/modules/yolov3.cpp.o
FAILED: CMakeFiles/TensorRTYolo.dir/modules/yolov3.cpp.o 
/usr/bin/gcc -DTensorRTYolo_EXPORTS -I/home/anton/installed/TensorRT-8.4.1.5/include -I/home/anton/.conan2/p/t/tenso8b9f815ec35ff/b/TensorRTYolo/extra -I/home/anton/.conan2/p/t/tenso8b9f815ec35ff/b/TensorRTYolo/modules -I/usr/local/include/opencv4 -I/usr/local/cuda/include -m64 **_ -std=c++;17_**" -O3 -Wno-write-strings" -O3 -DNDEBUG **_-std=c++17_** -fPIC -MD -MT CMakeFiles/TensorRTYolo.dir/modules/yolov3.cpp.o -MF CMakeFiles/TensorRTYolo.dir/modules/yolov3.cpp.o.d -o CMakeFiles/TensorRTYolo.dir/modules/yolov3.cpp.o -c /home/anton/.conan2/p/t/tenso8b9f815ec35ff/b/TensorRTYolo/modules/yolov3.cpp
gcc: error: unrecognized command line option ‘-std=c++’; did you mean ‘-std=c++03’?

i.e. when I specify self.settings.compiler.cppstd in configure() method, conan create needed string in conan_toolchain.cmake, but in  compile time this working with error (bold italic font in log)

**Comment by memsharded** [comment]
Hi @AbakumovAG 

Thanks for your report.
It seems there is an error in ``configure()``, it is not possible to assign values to settings like ``self.settings.compiler.cppstd = 17`` in recipes. Please have a look to https://docs.conan.io/2/knowledge/guidelines.html#forbidden-practices

You need to define the ``compiler.cppstd`` value in the profile (or in command line). Alternatively, you can automate some values in the ``profile.py`` plugin.

Also ``tc.variables["CMAKE_BUILD_TYPE"] = self.settings.build_type`` shouldn't be necessary, Conan already can manage the build type in CMakeToolchain without this. Same for ``tc.variables["CMAKE_CXX_COMPILER"] = self.settings.compiler``, this seems unnecessary.

**Comment by AbakumovAG** [comment]
Hi @memsharded

I already defined compiler.cppstd in default profile, and even been removed it from recipe, but no effect
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
```

I removed CMAKE_BUILD_TYPE and CMAKE_CXX_COMPILER but error still exist

**Comment by memsharded** [comment]
Yes, it can be defined in the profile, but you also have it defined in the recipe ``configure()`` method. Do you mean that you removed it from the recipe?
Would you mind please posting a complete updated ``conanfile.py``?

Also it seems that it could be something related to the build itself, so having something that we could reproduce would be great (including the ``CMakeLists.txt`` and some source code. If not, you can start from a basic ``conan new cmake_lib -d name=pkg -d version=0.1`` and try to make it fail in the same way with your profile?

**Comment by AbrilRBS** [comment]
We didnt hear back from you in a while, so Im closing this one. Feel free to reopen should you still face these errors, we are always happy to help!
