### ISSUE TITLE
[question] Help migrating recipe to Conan 2.0

### ISSUE THREAD

**Issue by cprieto** [conan-io/conan#13554]
### What is your question?

I have some spare time this week so I decide to help migrating a few recipes to Conan 2.0, and one of those is `libssh2`. I am facing some issue with this line in the old recipe:

```py
cmake.definitions["OPENSSL_ROOT_DIR"] = self.deps_cpp_info["openssl"].rootpath
```

I moved all that variable definitions to the `configure` method in the recipe, but now I am trying to deal with `deps_cpp_info`, I had been looking in the documentation about migrating to Conan 2.0 but I cannot find a simple set of recipes like "if you used `deps_cpp_info` now you should do this... or similar stuff...

What is the new equivalent of `deps_cpp_info`?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cprieto 

Thanks for your question.

The equivalent in Conan 2.0 is ``self.dependencies``. It is already available in Conan 1.X, so you can modernize your recipe in 1.X to make it ready, without breaking, and then have the same recipe working in 1.X and 2.0. Please have a look to: https://docs.conan.io/2/reference/conanfile/attributes.html#dependencies


Also take into account that this kind of information is better managed in the ``generate()`` method, in your case, passed to the ``CMakeToolchain`` ``cache_variables`` (for cmake-presets if you are using it) or ``variables`` for ``conan_toolchain.cmake`` variables. In either case, the intention is that after ``conan install`` it is very easy to build with cmake, and just calling ``cmake`` as a developer, and still achieve the exact same build that Conan will do in the cache when ``conan create``. Please have a look to the new ``CMakeToolchain`` integration too.

So it could be something like (not tested):

```python
def generate(self):
     tc = CMakeToolchain(self)
     tc.cache_variables["YOUR_VARIABLE"] = self.dependencies["yourdep"].package_folder
```

Also note that this might not be completely necessary for the Openssl case, in theory ``CMakeDeps`` should generate a ``openssl-config.cmake`` file that could be located and used with ``find_package()`` without having to add that in the consumer recipe.

**Comment by cprieto** [comment]
Thanks @memsharded oh yeah, I already moved _all those variable sets_ to a `configure` method, they used to be set up in a helper method in the `build` method, no worries, I had been just looking at old recipes and see how they change, but a few things had been difficult to find, not much info regarding practical tips about moving old recipes to Conan 2.0...

This is for libssh2 and libgit2, I hope I will have a PR ready soon, thanks a lot!

**Comment by memsharded** [comment]
If you hadn't had the chance to read https://docs.conan.io/1/conan_v2.html, we have tried to summarize there some tips for the migration 1.X -> 2.0

Thanks to you for the feedback!
