### ISSUE TITLE
[question] Conan info requires .git

### ISSUE THREAD

**Issue by phinzin** [conan-io/conan#13566]
### What is your question?

Hi Team,
i am getting the following issue:
when i execute the command
```
conan info . -u -j conan_install_info.json
```
then getting this error message:

**ERROR: '...${CURRENT_DIRECTORY}' is not a valid 'git' repository or 'git' not found.**

Are there any depend on conan info and git, it's not mentioned in documentation?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @phinzin 

Thanks for your question.
We would need more information to try to help, like what is the ``conanfile`` you are using, the full output of the ``conan install`` command, and if there are other files necessary to reproduce, like ``profiles`` or ``CMakeLists.txt``.
Also, you need to specify the OS, Conan version that you are using.

**Comment by AbrilRBS** [comment]
Closing this one as stale, please feel free to re-open if this is still an issue and you can provide additional freedback, thanks!
