### ISSUE TITLE
[bug] `conan remote remove "*"` doesn't remove duplicate remotes

### ISSUE THREAD

**Issue by cqc-alec** [conan-io/conan#13569]
### Environment details

* Operating System+version: all
* Compiler+version: N/A
* Conan version: 2.0.2
* Python version: 3.10

### Steps to reproduce

1. `conan remote add` (some remote)
2. `conan remote add` (exactly the same remote -- a warning is printed but no error)
3. `conan remote remove "*"`
4. `conan remote list`

The remote remains (only one instance has been removed).

**Comment by memsharded** [comment]
Hi @cqc-alec 

Thanks for your report.

I can see that ``conan remote remove *`` is not removing repeated remotes names.
But I feel that it shouldn't be possible to add twice the same remote, that should be an error (if force, it should be overwritten), it doesn't make sense that there are 2 remotes with same name and same url. What do you think? Lets fix the original bug? I mean ``conan remote add .... --force`` will not add a new remote with same name and same url, but keep the existing one?

**Comment by cqc-alec** [comment]
Hi @memsharded , I agree, and this was my original expectation: that I could use `conan remote add ... --force` to add the remote if it didn't exist, and do nothing otherwise (this was the conan 1 behaviour). It was only later I realized that I had a huge list of duplicated remotes!

**Comment by memsharded** [comment]
Suggesting #13574 fix for next 2.0.3 release
