### ISSUE TITLE
[question] Conan 2.0 upgrade

### ISSUE THREAD

**Issue by alexfrasin** [conan-io/conan#13567]
### What is your question?

Hello,

We want to migrate our projects from conan 1.x to conan 2.0.
I tried to download a package made with conan 1.x but it failed at synx, because of `from conans import ConanFile`.
My question is the following:

At the moment we have a lot of packages made with conan 1.x, in order to still use those, is conan 2.0 providing a compatibility between them or we have to rebuild our packages with conan 2.0 ?

Thanks!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @alexfrasin 

Thanks for your question.

Conan 1.X provides a "modern" syntax that is compatible with 2.0. A recipe written in 1.X with the modern syntax should be able to be built in Conan 2.0.
You have a migration guide in the docs in https://docs.conan.io/1/conan_v2.html, to help you modernize the recipes. The compatible syntax has been around for a long time, but it is recommended to move to latest Conan 1.X, and also make sure that you are using the modern opt-ins, like always activating revisions, and always using the 2 profiles approach with "build" profile and "host" profile.

Once the recipes are compatible, the Conan 2.0 command line is different, it would be necessary to adapt it. The binaries you create with 2.0 can be put in the same server repo, together with the binaries for 1.X, for the same (compatible) recipe, and they will not be colliding. The binaries for 1.X will be listed by 1.X ``conan search`` and the binaries for 2.0 will be listed with 2.0 ``conan list``.

**Comment by alexfrasin** [comment]
Hello @memsharded ,

We have to modify all our recipes for using conan 2.0.
Thank you for the answer!

Have a great day!

**Comment by memsharded** [comment]
> We have to modify all our recipes for using conan 2.0.

Yes, I am afraid this is necessary to modernize the recipes. This is why we have been doing alphas (6) and beta (10) releases for the last year and a half, and have been pushing the "modern" syntax, because this upgrade to the modern syntax is fully possible in 1.X scope, and the effort could have been gradually distributed over time.

Closing the question as responded, please don't hesitate to ask new questions or create new tickets if you need them in the migration. Thanks!
