### ISSUE TITLE
[feature] Add an option in `conan cache clean` to remove files in `<conan_home>/p/t` folder

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13576]
### What is your suggestion?

When a build fails, temporary build directories are kept in p/t folder, and they are never removed. I don't see any command to remove these directories unless I've missed something in documentation. Of course a simple rm does the job, but since conan cache is now an internal detail, a dedicated command or option in existing command would make sense.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your suggestion @SpaceIm 

Proposing a PR for 2.0.3
