### ISSUE TITLE
Improvements for CI

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1357]
conan info:

- Way to dump the dependency graph (with package ids) to be able to import into a CI system
- From a consumer, conan info --build missing will tell us the nodes that will be built, but without levels (grouped) and without package_id.
- The general idea is to be able to merge different consumers/profiles graphs to make more efficient builds. 
- Think about the use case in CI before implement it. (Changes in dep package ID)

**Comment by memsharded** [comment]
Obsolete, with lockfiles, bundles, etc, there are new solutions to CI.
