### ISSUE TITLE
[feature] Conan 1.x & 2.x packages coexistence in the same remote

### ISSUE THREAD

**Issue by db4** [conan-io/conan#13588]
### What is your suggestion?

Uploading a Conan package without a channel (`package/1.0@user`) makes the whole repo completely unusable for Conan 1.x. E.g. `conan search -r all *` fails with
```
ERROR: Specify the 'user' and the 'channel' or neither of them. [Remote: conan-private]
```
It would be great if Conan 1.x just ignore packages that it cannot handle.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/13590 for next 1.60
