### ISSUE TITLE
[question] update profile

### ISSUE THREAD

**Issue by k-morozov** [conan-io/conan#13586]
### What is your question?

I read doc about profile https://docs.conan.io/2.0/reference/config_files/profiles.html
> Profiles can be created with the detect option in [conan profile](https://docs.conan.io/2.0/reference/commands/profile.html#reference-commands-profile) command, and edited later.

Where info about update profile? How I can update profile with terminal?

In previous version I used:
```
conan profile update settings.compiler.libcxx=libstdc++11 default
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @k-morozov thanks for your question. Conan v2 deliberately removes most CLI operations that were simple file modifications.
One of the main reasons is that profiles are now Jinja2 templates, and it would be extremely hard to keep those templates consistent with any kind of load-modify-save done by Conan itself, so in the end we decided not to go that route, and instead improve how profiles are composed to allow for nicer UX, even ifit means removing some convenience commands :)

**Comment by AbrilRBS** [comment]
Closing this as answered, feel free to open new issues should you have any other suggestion or question, thanks!
