### ISSUE TITLE
[question] cmake install for consumer packages with cmake_layout

### ISSUE THREAD

**Issue by db4** [conan-io/conan#13589]
### What is your question?

Having a usual recipe pattern
```python
    def layout(self):
        cmake_layout(self)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    dep package(self):
        cmake.install()
```
how would one do cmake install when building a recipe as a consumer one? Suppose I use Visual Studio generator and need to install build artifacts to the proper location for testing. Without cmake_layout it's possible do `conan package . -pf <destination>` but with cmake_layout it's not allowed.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question.

``cmake_layout()`` and the ``layout()`` in general do not support the local ``conan package`` command. The layout is a 2.0 feature, and in 2.0 there is no ``conan package`` command, it has been removed. The "local dev flow" is ``conan install`` + ``cmake ...``, that is calling cmake directly. ``cmake.install()`` is doing nothing but call ``cmake --install``, something that can be done directly by the developers. For testing the package() method and package creation ``conan export-pkg`` can be used.

**Comment by memsharded** [comment]
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.
