### ISSUE TITLE
How to build RelWithDebInfo for MSVC?

### ISSUE THREAD

**Issue by Wyverex42** [conan-io/conan#13598]
### What is your question?

I've been using Conan with CMake for a while now, so far only in Debug and Release configurations. Now I want to build a RelWithDebInfo configuration as well. 

Here's what I have:

I'm using Conan 1.59.0 (can't switch to Conan 2.0 yet) but I'm already using `CMakeDeps` and `CMakeToolchain`.

conanfile.py
```
from conan import ConanFile

class App(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires("boost/1.75.0")
        self.requires("cli11/1.9.1")
        self.requires("imgui/1.89.2")
        self.requires("openvr/1.16.8")
        self.requires("spdlog/1.8.2")

    def imports(self):
        self.copy("imgui_impl_win32.*", dst="../../src/imgui-bindings/imgui", src="./res/bindings")
        self.copy("imgui_impl_dx11.*", dst="../../src/imgui-bindings/imgui", src="./res/bindings")
```

For a Debug build I do this:
```
cd build/ivyvr-debug
conan install ../.. -s ivyvr:build_type=Debug -s build_type=Release
cmake ../.. -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
cmake --build . --config Debug
```

which works like a charm.

Now I want to do the same for RelWithDebInfo:

```
cd build/ivyvr-debug
conan install ../.. -s ivyvr:build_type=RelWithDebInfo -s build_type=Release
cmake ../.. -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
cmake --build . --config RelWithDebInfo
```

And I'm getting loads of include errors for the package dependencies. Looking into the generated `ivyvr.vcxproj` file, I can confirm that `<<ResourceCompile><AdditionalIncludeDirectories>` doesn't contain the include paths for the `RelWithDebInfo` confguration (but it does for `Debug` and `Release`)

I've found multiple other issues and questions here with similar findings. I think I've understood that Conan recipes are single configuration which is why we need the `-s ivyvr:build_type=<my-build-type> -s build_type=Release` trick to use `Release` 
packages, independent of my build config. 
I pretty much tried everything I found in those other posts but nothing worked so far. Some of them were also quite old and I'm not sure what the correct way to do this is with Conan 1.59.0 and CMakeToolchain.

Help would be greatly appreciated!

Edit: I get the same results when switching from MSBuild to Ninja. So the issue must be in how CMake is configured (likely through `conan_toolchain.cmake`)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Wyverex42 

Thanks for your question.
I think I might be missing some bit, or maybe the recipe above is oversimplified?
When you specify ``-s ivyvr:build_type=Debug``, I guess that the name of the provided ``conanfile.py`` is ``ivyvr``, but I am missing the declaration of the name like ``name = "ivyvr"``. If the name is not present, then the ``-s ivyvr:build_type=`` might be ignored. Could you please check this?

Also the syntax ``-s &:build_type=`` might help, it means "the consumer conanfile", and can be useful for case of consumers where the ``name`` is not defined.

**Comment by Wyverex42** [comment]
Hi @memsharded,

Thanks for your answer!

`ivyvr` is the name of my executable target. I thought I had seen something similar in another post but thinking about this further now, this would require conan to have knowledge of my CMake targets, which would invert the dependencies, so I think you're right that this isn't doing anything.

I tried running with `-s &:build_type=` before because I saw it in other posts but I get this error when I do so:
```
λ conan install ../.. -s &:build_type=RelWithDebInfo -s build_type=Release -pr:b=default
usage: conan install [-h] [-g GENERATOR] [-if INSTALL_FOLDER] [-of OUTPUT_FOLDER] [-m [MANIFESTS]] [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]] [--no-imports] [--build-require]
                     [-j JSON] [-b [BUILD]] [-r REMOTE] [-u] [-l LOCKFILE] [--lockfile-out LOCKFILE_OUT] [-e ENV_HOST] [-e:b ENV_BUILD] [-e:h ENV_HOST] [-o OPTIONS_HOST]
                     [-o:b OPTIONS_BUILD] [-o:h OPTIONS_HOST] [-pr PROFILE_HOST] [-pr:b PROFILE_BUILD] [-pr:h PROFILE_HOST] [-s SETTINGS_HOST] [-s:b SETTINGS_BUILD]
                     [-s:h SETTINGS_HOST] [-c CONF_HOST] [-c:b CONF_BUILD] [-c:h CONF_HOST] [--lockfile-node-id LOCKFILE_NODE_ID] [--require-override REQUIRE_OVERRIDE]
                     path_or_reference [reference]
conan install: error: argument -s/--settings: expected 1 argument
ERROR: Exiting with code: 2
```

**Comment by memsharded** [comment]
Uhm, I think that depends on the terminal escaping, please try quoting it like ``-s "&:build_type=RelWithDebInfo"``

**Comment by Wyverex42** [comment]
Oh gosh, that worked 🤦‍♂️ Thanks! Classical user error 😄

**Comment by memsharded** [comment]
No prob, happy that it is working with those hints! 😄
