### ISSUE TITLE
[question] "conan list" only shows the latest package info even though I "conan create" with multiple profiles 

### ISSUE THREAD

**Issue by chen-tianjian** [conan-io/conan#13593]
### What is your question?

(It might be because I am missing something, but I cannot figure it and struggled with it for several days)

With my package, when I do (1) `conan create . -pr=default` and then (2) `conan create . -pr=myprofile` (myprofile defines different build type, e.g. debug, etc.), both can build and create packages successfully. However, when I check with `conan list my_package:*`, it only shows the information of the latest build (which is (2)), and conan cannot find the previous build with the default profiles.

May I ask what can go wrong? Or am I misunderstanding something? Thanks in advance for your help!

For more info:
* I am using Conan 2.0.2
* I am with gcc 11, c++ 17 standard, linux
* My conanfile.py is similar to the [simple example](https://docs.conan.io/2/tutorial/creating_packages/create_your_first_package.html), only changed the names and versions, used `ninja` as the generator for `CMakeToolchain`, and some additional variables for `cmake.configure()`.
* My package is a mixed C and C++ package. Unfortunately this is proprietary software and cannot be shared.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by chen-tianjian** [comment]
I finally figured it out, it was because I was exporting some folder containing the auto-generated files  (second export includes the auto-generated files from the first export), so Conan sees different exports as different source packages. However, they have the same package name and version number, so instead of appending the new info, Conan ends up overwriting the existing info when using `conan list my_package:*`

Not sure if this is the intended behavior, but this is a mistake that people are likely to make.

**Comment by memsharded** [comment]
Hi @chen-tianjian 

Thanks for your question.
Could you please provide the 2 full outputs of the 2 ``conan create`` commands with the 2 different profiles? That could give some hints of what could be happening. Specifically we would be looking for:
- The ``recipe revision``, which should be the same in both cases. If it is not the same, you are doing a different ``exports``, ``exports_sources``. These need to be identical, to achieve the same recipe revision. It is not possible do do conditional exports or anything that results in a different set of exported files into the recipe.
- The effective profiles
- The ``package_ids``

Using ``conan list package*#*`` will list the different recipe revisions, and for each one you can list its binaries with ``conan list pkg/version#revision:*``

**Comment by memsharded** [comment]
Oh! It seems we were writing at exactly the same time 😅 

Yes, this is totally intended behavior, and actually it is not easy to avoid it. Users should be aware of which files they are exporting, and if things are being changed between different invocations of ``conan create``, it should be either cleaned, or the ``exports_sources`` limited somehow.

**Comment by chen-tianjian** [comment]
Thanks so much! Maybe it is good to put this warning somewhere in the doc.

**Comment by memsharded** [comment]
We added an item in the docs for this in: https://docs.conan.io/2/knowledge/guidelines.html

> All input sources must be common for all binary configurations: All the “source” inputs, including the conanfile.py, the conandata.yml, the exports and exports_source, the source() method, patches applied in the source() method, cannot be conditional to anything, platform, OS or compiler, as they are shared among all configurations. Furthermore, the line endings for all these things should be the same, it is recommended to use always just line-feeds in all platforms, and do not convert or checkout to crlf in Windows, as that will cause different recipe revisions.

But the truth is that it is difficult to connect the dots. Maybe if we create an entry in the FAQ, it could help, but it is something that won't be easy to find in any case.
