### ISSUE TITLE
[bug] MSBuildDeps props file not correct

### ISSUE THREAD

**Issue by gfidder** [conan-io/conan#13602]
### Environment details

* Operating System+version: Windows 10 1909
* Compiler+version: MSVC 193
* Conan version: 2.0.2
* Python version: 3.11.1

### Steps to reproduce

1. Create a package that is a single .lib and .h file
2. Create a second package that is dependent on the first package that is a single .lib and .h file. In this package, have the .h file include the .h file from the first project and use it.
3. Create a test project for the second package. Run `conan test` on the second package which will the fail build since it cannot find the header for the first package.

### Logs

```
conan test  -s compiler=msvc -s arch=x86 -s build_type=Debug -s compiler.version=193 test_package test_package_2/1.0.1@fsl/stable
.
.
.
======== Installing packages ========
test_package_1/1.0.0@fsl/stable: Already installed! (1 of 2)
test_package_2/1.0.1@fsl/stable: Already installed! (2 of 2)
.
.
.
C:\Users\***\.conan2\p\test_7bb6378fe5490\p\include\something.h(3,10): fatal  error C1083: Cannot open include file: 't
est.h': No such file or directory [C:\Users\***\TestPackage2\test_package\ConanTest.vcxproj]
```

**Comment by gfidder** [comment]
![package 2 screenshot](https://user-images.githubusercontent.com/50161749/229585857-cddd4935-df8c-4e91-81f0-389a96ae1e2e.png)
![package 1 screenshot](https://user-images.githubusercontent.com/50161749/229585867-35cf64e8-bc88-409a-bf46-9ff2aa3d38af.png)
The macro for the inherited package also does not work when looking at include directories

**Comment by gfidder** [comment]
Recipe for first package
```py
class Package(ConanFile):
    name = "test_package_1"
    version = "1.0.0"
    settings = "os", "arch", "compiler", "build_type"
    package_type = "static-library"
    requires = ()

    def configure(self):
        assert self.settings.os == "Windows"
        assert self.settings.arch in ["x86", "x86_64"]
        assert self.settings.compiler.version == "193"
        assert self.settings.build_type in ["Debug", "Release"]

    def package(self):
        copy(self, "*.h", self.source_folder, os.path.join(self.package_folder, "include"))
        copy(self, "*.lib", self.build_folder, os.path.join(self.package_folder, "lib"), keep_path=False)

    def build(self):
        cleanup = ["./Debug", "./Release", "x64"]
        for path in cleanup:
            if os.path.isdir(path):
                shutil.rmtree(path)

        ms = MSBuild(self)
        ms.build("./TestPackage1.sln")

    def package_info(self):
        self.cpp_info.includedirs = ["include"]
        self.cpp_info.libdirs = ["lib"]
        self.cpp_info.libs = ["TestPackage1.lib"]
```

Recipe for second package
```py
class Package(ConanFile):
    name = "test_package_2"
    version = "1.0.1"
    settings = "os", "arch", "compiler", "build_type"
    package_type = "static-library"
    generators = "MSBuildDeps"
    requires = "test_package_1/1.0.0@fsl/stable"

    def configure(self):
        assert self.settings.os == "Windows"
        assert self.settings.arch in ["x86", "x86_64"]
        assert self.settings.compiler.version == "193"
        assert self.settings.build_type in ["Debug", "Release"]

    def package(self):
        copy(self, "*.h", self.source_folder, os.path.join(self.package_folder, "include"))
        copy(self, "*.lib", self.build_folder, os.path.join(self.package_folder, "lib"), keep_path=False)

    def build(self):
        cleanup = ["./Debug", "./Release", "x64"]
        for path in cleanup:
            if os.path.isdir(path):
                shutil.rmtree(path)

        ms = MSBuild(self)
        ms.build("./TestPackage2.sln")

    def package_info(self):
        self.cpp_info.includedirs = ["include"]
        self.cpp_info.libdirs = ["lib"]
        self.cpp_info.libs = ["TestPackage2.lib"]
```

**Comment by gfidder** [comment]
Recipe for second package test
```py
class MyConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "MSBuildDeps"

    def requirements(self):
        self.requires(self.tested_reference_str)

    def generate(self):
        for dep in self.dependencies.values():
            print(dep.cpp_info)

    def build(self):
        cleanup = ["./bin", "./intermediate"]
        for path in cleanup:
            if os.path.isdir(path):
                shutil.rmtree(path)

        m = MSBuild(self)
        m.build(
            "./ConanTest.sln")

    def test(self):
        subprocess.check_call(
            "test.exe", cwd="./bin/", shell=True)
```

**Comment by memsharded** [comment]
Hi @gfidder 

Thanks for your detailed report.

Short answer: If the headers of the first dependency are publicly included via the public headers of the second recipe, it is necessary to declare them as transitive:

```python
def requirements(self):
     self.requires("test_package_1/1.0.0@fsl/stable", transitive_headers=True)
```

Long answer:

Headers of a dependency by default are considered private, as good practices recommend to give those headers the least possible scope. There are 2 situations where the final consumer should have visibility of those headers:

- If the code of the final consumer uses ``#include`` to those headers, then it is not a transitive dependency, but it should be declared as a direct ``requires`` in the final consumer
- If the intermediate package headers include the transitive dependency headers in its public headers, then the final consumer needs to have them in the include path. Conan allows to model this situation with the ``transitive_headers=True`` trait.

For more information there are detailed explanations in this video: https://youtu.be/kKGglzm5ous and you can also read: https://docs.conan.io/2/reference/conanfile/methods/requirements.html

**Comment by memsharded** [comment]
Some other recommendations:

- When using ``MSBuild`` and ``MSBuildDeps`` it is recommended to use and add the ``MSBuildToolchain`` ``conantoolchain.props`` file, that will inject some variability depending on the input Conan settings, like ``cppstdd`` or the ``toolset``
- ``self.cpp_info.libs = ["TestPackage2.lib"]`` is not recommended in general to add the ``.lib`` suffix, and specifying the plain library name is better.
- You probably don't want to hardcode the asserts like `` assert self.settings.compiler.version == "193"`` in the ``generate()`` method. If for some reason you don't really expect your code to compile in some configuration, better raise a ``ConanInvalidConfiguration`` in the ``validate()`` or ``validate_build()`` methods. But that might not be even necessary.
- ``self.cpp_info.includedirs = ["include"]`` and ``self.cpp_info.libdirs = ["lib"]`` are not necessary, those are already the default
