### ISSUE TITLE
RHEL 6.8: pkg_resources.DistributionNotFound: pylint==1.6.5

### ISSUE THREAD

**Issue by jgeorgeson** [conan-io/conan#1360]
Extremely new to Conan, looks really nice, found out about it after a recent upgrade of Artifactory servers. I tried installing via pip on RHEL 6.8 (using the python-pip package from EPEL) like this

```bash
$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseWorkstation
Description:	Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
Release:	6.8
Codename:	Santiago
$ rpm -q python
python-2.6.6-66.el6_8.x86_64
$ rpm -q python-pip
python-pip-7.1.0-1.el6.noarch
$ sudo -s
# https_proxy=http://myproxy.company.com:80 pip install conan
[ ... redacted for brevity ...]
# which conan
/usr/bin/conan
```

am receiving a stacktrace trying to run any Conan commands.

```bash
$ which conan
/usr/bin/conan
$ conan --version
Traceback (most recent call last):
  File "/usr/bin/conan", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pylint==1.6.5
```

Using the python2.7 SCL _appears_ to work

```bash
$ sudo -s
# scl enable python27 bash
# python --version
Python 2.7.8
# which pip
/opt/rh/python27/root/usr/bin/pip
# https_proxy=http://myproxy.company.com:80 pip install conan
[ ... redacted for brevity ...]
# exit
$ which conan
/opt/rh/python27/root/usr/bin/conan
$ conan --help
Conan commands. Type $conan "command" -h for help
  build          Utility command to run your current project 'conanfile.py' build() method.
  config         Manages conan.conf information
  copy           Copy conan recipes and packages to another user/channel.
  export         Copies the package recipe (conanfile.py and associated files) to your local cache.
  imports        Execute the 'imports' stage of a conanfile.txt or a conanfile.py.
  info           Prints information about a package recipe's dependency graph.
  install        Installs the requirements specified in a 'conanfile.py' or 'conanfile.txt'.
  new            Creates a new package recipe template with a 'conanfile.py'.
  package        Calls your conanfile.py 'package' method for a specific package recipe.
  package_files  Creates a package binary from given precompiled artifacts in user folder, skipping
  profile        List profiles in the '.conan/profiles' folder, or show profile details.
  remote         Handles the remote list and the package recipes associated to a remote.
  remove         Remove any package recipe or binary matching a pattern.
  search         Search package recipes and binaries in the local cache or in a remote server.
  source         Calls your conanfile.py 'source()' method to configure the source directory.
  test           (deprecated). Alias to test_package, use it instead
  test_package   Export, build package and test it with a consumer project.
  upload         Uploads a package recipe and the generated binary packages to a specified remote
  user           Update your cached user name (and auth token) to avoid it being requested later.
```
However there's an oddity in the default settings

```bash
$ conan config get settings_defaults
arch = x86_64
build_type = Release
compiler = gcc
compiler.libcxx = libstdc++
compiler.version = 4.8
os = Linux
$ which gcc
/usr/bin/gcc
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The `compiler.version` says 4.8, but the system's GCC install is 4.4.7.

Should I be able to install and run with the default Python 2.6? Should I be concerned with the compiler version discrepancy using the python2.7 version?

**Comment by memsharded** [comment]
Hi @jgeorgeson 

No, conan is developed and tested for Python 2.7 and Python 3.X. Though it might be possible to make it work in Python 2.6, there might be other quirks besides that failed import. So if it is not a hard constraint to run only 2.6, we would strongly encourage to use 2.7. Otherwise, please tell, so we could try to find workarounds.

Regarding the detected gcc version, conan has a relatively simple detection routine, that is run only the first time you run conan, which populates the default settings. You can see the result of that routine if you remove your ``<userhome>/.conan/conan.conf`` file, and run conan again. Please paste the output here. It is very possible that the detection routine is not prepared to detect older gcc compilers as 4.4.
Don't worry too much about that failure, it is just a helper, and not used at all in the rest of conan operation. Just edit your ``<userhome>/.conan/conan.conf`` file and write there 4.4 instead. 
In any case, you will probably find soon that the most convenient approach is to use ``profiles`` so you can put them in the project repo or in a common repo, and share all target configurations with the team easily. Using command line settings, options and profiles, overrides the default settings values.

**Comment by jgeorgeson** [comment]
Thanks for the quick reply! Using the _python27_ collection should be OK. I find SCLs have the drawback of having extra env setup in the CI environment (ie enabling the collection to get everything in your path) but the benefit of keeping the runtime requirements within official RHEL packages. 

I figured out the compiler version discrepancy too. We have NFS-mounted home directories and I first ran conan on an RHEL7 machine where the compiler is indeed 4.8.

**Comment by memsharded** [comment]
Yeah, good that you found the reason for the 4.8 version :) that makes sense.
I don't know your work setup, but just in case: if you want to redirect the conan user home to somewhere not in your user folder (so it is really local/temporary in each of your machines), you could use the env-var CONAN_USER_HOME.
Thanks for updating on this!
