### ISSUE TITLE
[question] How should component names be handled in a custom generator?

### ISSUE THREAD

**Issue by AlexRamallo** [conan-io/conan#13611]
### What is your question?

I'm working on a custom generator for waf, and am confused about resolving component dependencies.

For example, look at [spdlog](https://github.com/conan-io/conan-center-index/blob/master/recipes/spdlog/all/conanfile.py#LL135C60-L135C63) and [fmt](https://github.com/conan-io/conan-center-index/blob/master/recipes/fmt/all/conanfile.py#L108) on Conan Center.

* spdlog declares `self.cpp_info.components["libspdlog"].requires = ["fmt::fmt"]`
* fmt declares a component called `self.cpp_info.components["_fmt"]`, but sets cmake_target_name to "fmt::fmt"

This (apparently) means that the libspdlog component explicitly depends on the *cmake_target_name* of the fmt package, rather than the actual component name "_fmt". Is it supposed to work like this, or is it just that these packages are doing it wrong?

OR maybe the component requires has a reference format like "(package name)::(component name)", and it's just a coincidence that it looks like the cmake_target_name... but if that's true, then shouldn't it be "fmt::_fmt"?

The [docs](https://docs.conan.io/2/reference/conanfile/methods/package_info.html#components) say that Conan uses component names to resolve their dependencies. I assume that this works using just the component names (not properties), so either spdlog is wrong for depending on "fmt::fmt", or fmt is wrong for declaring "_fmt".

...yet, as far as I know, these packages still work. So is Conan and/or CMakeDeps doing some magic to deal with this situation? And if so, should my generator be doing it too?

For reference, I just need to generate a text file with variables like:

```py
CXXFLAGS_fmt = [...]
DEFINES_fmt = [...]
INCLUDES_fmt = [...]
REQUIRES_fmt = [...]
CXXFLAGS_spdlog = [...]
DEFINES_spdlog = [...]
INCLUDES_spdlog = [...]
REQUIRES_spdlog = ["fmt"] #same name used above
```

My immediate issue is just how to deal with the naming discrepancy to model component dependencies. I could do some hacks try to get it to work, but I'm not sure how well that would work for other packages. 

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @AlexRamallo 

Thanks for your question.
There is a bit of similarities in naming that could make it a bit confusing:

- Components are named ``components["comp_name"]``. This is the abstract name of the component.
- The ``pkg_name::pkg_name`` name always exists for a package, and it refers to the whole package. Kind of a base component that will automatically require all components if there are components, or just the package if there are no components in such package. 
- Components can require other components with ``components["comp_name"].requires = ["other_comp_name"]`` being the other component in the same package
- Components can require other components in other packages with the ``requires = ["pkg_name::comp_name"]``. This name might or might not be the same as the CMake target name. 
- This CMake target name is only retrieved by ``get_property("cmake_target_name")`` by CMake generators, but can be completely ignored for other build systems
- The CMake target name is not and shouldn't be used for ``components[].requires`` at all, it can raise if the component doesn't exist (even if there is a component that maps to that CMake target name)

I hope this clarifies a bit the issue.

**Comment by AlexRamallo** [comment]
Yes, that cleared things up a bunch, thanks!
