### ISSUE TITLE
Conan creating another profile when one already exists

### ISSUE THREAD

**Issue by leinadme** [conan-io/conan#13624]
### What is your question?

I'm using Conan 2.0.3 on Windows 10.  Prior to that I was using 2.0.2.  I'm having a strange issue which was working several weeks ago but now not working.  When I try to run a command such as 
conan install .. -s compiler.version=16 --build=missing -s build_type=Release
under "/Users/username/" a ".conan2" is created even though I already have a working ".conan".  
To try to get around the problem, I use the ".conan2" folder and modify the profiles/default from my existing profile in .conan to ".conan2".  Below are the settings.  I then get errors such as [options], [build_requires], and [env} are not valid.  It also doesn't like "compiler=Visual Studio" or "arch_build=x86_64". 
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[build_requires]
[env]

When I try to modify above setting just to get the conan install to work, I then get a message that python can't load conanFile.

Is there some way I can reset the environment to get things back to where they were?  I know I installed several Windows patches and not sure that has anything to do with my problems.  Once gain this was working flawlessly.  I did use the Conan Windows installer to install conan initially.

Any help would be appreciated!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by leinadme** [comment]
Also when I try running "conan profile list", it returns nothing as no profile exists but it does!

**Comment by leinadme** [comment]
Update:
I created two profiles, exactly the same .conan and .conan2.
When running "conan profile list" I get:
default

but when I run:
conan install .. -s compiler.version=16 --build=missing -s build_type=Release
I get "ERROR: Error reading 'C:\Users\userName\.conan2\profiles\default' profile: ConfigParser: Unrecognized field 'build_requires'

**Comment by freshduer** [comment]
this is my profile: conan2 is different between conan1.x,you need to change the format，
or u can delete the profile and run"conan profile detect" or something i dont quite remember,the code wil automatically detect you computer environment and write u a profile
```
[settings]
os=Windows
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=12.1
compiler.libcxx=libstdc++11
```

**Comment by leinadme** [comment]
Thanks, so I changed my profile as such:
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release

Now when I run conan install, this is what I'm getting:
ERROR: Error loading conanfile at 'C:\folder\project\conanfile.py': Unable to load conanfile in C:\folder\project\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\folder\project\conanfile.py", line 1, in <module>
    from conans import ConanFile, tools
ImportError: cannot import name 'ConanFile' from 'conans' (c:\python37\lib\site-packages\conans\__init__.py)

**Comment by memsharded** [comment]
Hi @leinadme 

Thanks for your question. Let me try to clarify a few things:

> under "/Users/username/" a ".conan2" is created even though I already have a working ".conan".

- Conan 1.X uses the ``.conan`` home/cache location by default and Conan 2.0 uses the ``.conan2`` home/cache location by default
- Both caches are incompatible, the format, layout, files, etc are different so the same cache cannot be used for both 1.X and 2.0


> compiler=Visual Studio

Conan 2.0 no longer support this ``setting``, and it only declares the ``msvc`` to model the VS. ``msvc`` was already introduced in 1.X some time ago.


> ImportError: cannot import name 'ConanFile' from 'conans' 

yes, the imports need to be modernized. This can be made in Conan 1.X, to be ready for Conan 2.0. The new imports and tools have been made available in Conan 1.X some time ago too.


I'd recommend having a look to: https://docs.conan.io/1/conan_v2.html

**Comment by leinadme** [comment]
May I ask why Visual Studio versions are still in the yml file?  I thought that file provide all the valid attributes and values.

**Comment by leinadme** [comment]
Thanks for all your help.  I managed to a conan install but still use Visual Studio as the compiler :)

**Comment by memsharded** [comment]
> May I ask why Visual Studio versions are still in the yml file? I thought that file provide all the valid attributes and values.

Not sure what is happening, it seems that manipulating your caches might have done something. I'd recommend to wipe completely the ``.conan`` and ``.conan2`` and start from scratch, it will generate the right ``settings.yml`` file.
Recall that if you are managing your own profiles, the recommended way is to put them in a git repo and install them with ``conan config install <git-repo-url>`` in the machines you want to use them. This way you can synchronize and update the profiles (and other files too). Just beware, as the cache is different, you cannot use the same origin for ``conan config install`` for 1.X and 2.0, each one would have its own configuration origin.

> Thanks for all your help. I managed to a conan install but still use Visual Studio as the compiler :)

Yes, ``msvc`` refers to exactly the same compiler as the 1.X ``Visual Studio``, it is not a different compiler, just different naming (and different versions, ``msvc`` uses the compiler version, not the IDE version, but there are equivalences between those).

**Comment by leinadme** [comment]
Thank you
