### ISSUE TITLE
[feature] dev dependency section for C/C++ CLI tools

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#13620]
### What is your suggestion?

# Summary

Could there be a dev dependency section for pinning assorted CLI tools used to develop a project, which are not needed by C/C++ libraries at runtime? That is, a dev dependency section similar to the dev dependency sections of NPM and RubyGems. Including the ability for conan to compile and install binaries from dev dependency projects.

# Context

For example, imagine a banking system C++ application that wishes to pin the version of cppcheck that the developers use to scan for common C++ coding quirks. I don't work for no bank, but I thought the example would add some helpful concreteness. By introducing a dev dependency section to the conan requirements schema, the banking developers benefit from tracking the exact cpplint version in version control. This reduces DevOps fires, to reproduce CI/CD builds locally, etc.

The developers also benefit from automation, so that they don't have to necessarily manually install cppcheck. While cppcheck itself actually enjoys entries in many popular package managers, like Homebrew, Debian packages and so on, there are in fact, many other dev tools which do not have Homebrew formulas, Debian packages or so on. And often the Debian package lags far behind the latest tool release: Developers who wish to install a newer version have to use a different installation method, such as manual compilation, in order to obtain the right version of cppcheck. And that bother takes valuable time away from direct coding work on the primary, banking application. Or graphics engine. Or widget. Or whatever.

Most maintainers of development tools unfortunately do not document installation steps in a highly portable way, that works for Command Prompt, PowerShell, WSL, native Linux, BSD, etc. etc. Portability is where conan shines. When dev tools are tracked as nearly equivalent to the runtime application dependencies that the banking app tracks with conan, then setting up the development environment to build, test, and lint the application becomes smoother. Onboarding is streamlined. Important steps demystified. But the current state of the art for setting up computers to build a C/C++ project, largely still uses very manual, fragile steps.

# Implementation notes

We would also want to ensure that conan packages have the ability advertise the names of the binaries that they build, so that conan is then able to copy them to a suitable location (e.g., `.conan/dev-tools/<package>/bin`) for ease of adding to the `PATH` environment variable.

# Prior art

* apk, apt, emerge, pkg, yum, etc. (UNIX distro specific; pinning and automation would involve UNIX shell scripts; OS package repositories tend to delete old package versions as new OS releases occur; inconvenient for getting ultra new and ultra old versions of components)
* Ansible (requires learning a separate DSL apart from to the conan configuration system)
* ASDF (designed for use with interactive localhost shells; trickier when used in CI/CD pipelines and remote deployments)
* Chef (adds Ruby to the technology stack)
* Circle CI, Jenkins, GitHub Actions, GitLab CI, etc. (precludes localhost/native development)
* Chocolatey (Windows specific; pinning and automation would involve bat / PowerShell scripts)
* Docker (would preclude localhost/native development)
* fpm (prepares installation media but does not provide a portable provisioning script)
* Homebrew (lack of Windows support; pinning and automation would involve UNIX shell scripts)
* make (tends to break things for non-WSL Windows users)
* Nix (Linux distro specific)
* NPM (intended for Node.js dependencies)
* pkgsrc, pkgin (lack of Windows support; pinning and automation would involve UNIX shell scripts)
* Puppet (adds Ruby to the technology stack)
* RubyGems (intended for Ruby dependencies)
* shell scripts (fragile)
* Vagrant (would preclude localhost/native development, adds Ruby to the technology stack, very slow)

Maybe conan already has a dev dependency tracking and installing ability, and I have missed something in the documentation for this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mcandre 

Thanks for your suggestion.
This seems to be a feature already existing in Conan, called ``tool_requires``.
Recipes can declare ``tool_requires`` to the dev tools they need: https://docs.conan.io/2/reference/conanfile/attributes.html#tool-requires. It also allows differntiating between tools (like cmake) and test frameworks, with ``test_requires``: https://docs.conan.io/2/reference/conanfile/attributes.html#test-requires

They can also add them conditionally, so different tools can be used in different platforms, using the ``build_requirements()`` method: https://docs.conan.io/2/reference/conanfile/methods/build_requirements.html

Tool requires can also be injected to the whole dependency graph via the profile ``[tool_requires]``: https://docs.conan.io/2/reference/config_files/profiles.html#introduction-to-profiles

**Comment by memsharded** [comment]
Any further question about this? Can we close the ticket as responded?

**Comment by memsharded** [comment]
Closing this ticket as responded, please re-open or create a new one if there are further questions
