### ISSUE TITLE
Copy command doesn't seem to work as expected

### ISSUE THREAD

**Issue by leinadme** [conan-io/conan#13629]
### What is your question?

Hi,

Since I'm migrating from conan1.x to 2.x, I'm running into issues trying to copy files in my recipe.  Here is an example:

from conan import ConanFile
from conan.tools.files import copy

class someClass(ConanFile):
    name = "someClassName"
    version = "1.0.1"
    # No settings/options are necessary, this is header only
    exports_sources = "folder/Utils/*.h"
    no_copy_source = True

    def package(self):
        copy(self, "*.h", src="folder/Utils", dst="include/folder/Utils")

When I try to run the recipe
conan create .

I expect the header file located in folder/Utils folder would be copied to include/folder/utils in the conan cache to be reference by other applications.
In 1.x I used the following which worked just fine:
self.copy("*.h", dst="include/folder/Utils", src="folder/Utils")

When I run the above command, I get the following message:
-------- Installing package someClassName/1.0.1 (1 of 1) --------
someClassName/1.0.1: Building from source
someClassName/1.0.1: PackagesomeClassName/1.0.1:da39a3ee5e6b4b0d3255bfef95601890afd80709
someClassName/1.0.1: Building your package in C:\Users\userName\.conan2\p\t\tdcs-65dbf418d3b46\b
someClassName/1.0.1: Generating aggregated env files
someClassName/1.0.1: Generated aggregated env files: ['conanbuild.bat', 'conanrun.sh']
someClassName/1.0.1: Package 'da39a3ee5e6b4b0d3255bfef95601890afd80709' built
someClassName/1.0.1: Build folder C:\Users\userName\.conan2\p\t\tdcs-65dbf418d3b46\b
someClassName/1.0.1: Generating the package
someClassName/1.0.1: Temporary package folder C:\Users\userName\.conan2\p\t\tdcs-65dbf418d3b46\p
someClassName/1.0.1: Calling package()
**someClassName/1.0.1: package(): WARN: No files in this package!**
someClassName/1.0.1: Created package revision 0ba8627bd47edc3a501e8f0eb9a79e5e
someClassName/1.0.1: Package 'da39a3ee5e6b4b0d3255bfef95601890afd80709' created
someClassName/1.0.1: Full package reference: someClassName/1.0.1#a7fa5100bf15a2d417f28458d917ac11:da39a3ee5e6b4b0d3255bfef95601890afd80709#0ba8627bd47edc3a501e8f0eb9a79e5e
someClassName/1.0.1: Package folder C:\Users\userName\.conan2\p\tdcs-d5e3126084ba7\p

In bold we can see no files in package, so I'm wondering what I am doing wrong?  I checked the cache and the include files are not there unless Conan is putting them in some other place.

Thanks!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @leinadme 

Thanks for your question.

The new ``copy()`` method uses absolute paths, not relative ones. It is necessary to specify something like:

```python
def package(self):
    copy(self, "*.h", src=os.path.join(self.source_folder, "folder/Utils"), 
            dst=os.path.join(self.package_folder, "include/folder/Utils"))
```

Please try that and let us know.

**Comment by leinadme** [comment]
Thank you!  That seem to do it.
