### ISSUE TITLE
[question] version overrides for dependencies that are both host and build (via tool_requires)

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#13638]
### What is your question?

Adding this ticket to look into this - could be a potential feature or document a proper way of dealing with this.

Some packages include _both_ libraries and executables - and the way Conan 2.0 handles propagation of usage requirements, we can handle cross-compilation very nicely. For this, we recommend expressing the dependency like this:

```
def requirements(self):
    self.requires("foobar/x.y.z")

def build_requirements(self):
    self.tool_requires("foobar/x.y.z")
```

When cross-building, two different packages will be pulled: one for an os/architecture that we can _run_ on the build machine (the `tool_requires`), and another one for the library to link against for the _host_ context.

However, the library requirement (host context), is liable to overrides from downstream consumers.  Some of these tools (that contain library+executables) are very sensitive to a mismatch in versions and have a stronger coupling.

Such a case is protobuf: the protobuf compiler (`tool_requires`) needs to generate `.pb.cc` and `.pb.h` files that are compatible with the version of protobuf resolved for the library requirement. If this is not the case, we will eventually get a compiler error.

I have uploaded a full reproducible example here (requires Docker): https://github.com/jcar87/conan-tool-require-override 

The example involves cross-building, but note that this situation can and will also happen when _not_ cross compiling, however a lot of recipes in conan center are including logic to work around this when not cross building, in a way that forces the executable from the _host_ package to be used. This is non-trivial logic that is hard to follow for a lot of contributors, and it only hides the problem: it really doesn't solve it when cross-building. 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Adding this ticket so that we can consider a feature to solve this - e.g. if there was a way of specifying in the recipe that has these requirements, that the version of the `tool_requires` needs to match the version of the `requires` - would be great - although there may be limitations preventing that from being the case. 

Some ideas (that may not work at all):
```
def requirements(self):
    self.requires("protobuf/3.22.0")
def build_requirements(self):
    self.tool_requires("protobuf", track_host_version=True)
```


```
def requirements(self):
   self.requires("protobuf/3.22.0")
 
def build_requirements(self):
  protobuf_version = self.dependencies.host["protobuf"].ref.version
  self.tool_requires(f"protobuf/{protobuf_version})
```

These may not be possible to implement, but just some ideas so that the recipe maintainer can express that the _versions_ need to match.

Note that it is not always the case that the versions need to match as closely as protobuf does, so this needs to be optional.

**Comment by memsharded** [comment]
I think this is relevant, and we should have a look to see if this is possible somehow, I am tagging it as "look into" for next iteration.
