### ISSUE TITLE
[question] how to eliminate vscode import error squiggles?

### ISSUE THREAD

**Issue by simsicon** [conan-io/conan#13632]
### What is your question?

Hi, I am starting to use conan2 in a new project, I think it has a lot of changes to conan1, I understand the changes must be made to solve some underlying problems.

It changes how I integrate conan with VSCode, I use cmake from terminal to build and use VSCode to code, so I appreciate how VSCode can locate the correct sources and jump to the definitions and no any import error squiggles, but after using conan2, my VSCode can not find the correct sources to import, while cmake works well, I hope someone using VSCode could shares the solution to this problem.

I am aware of this issue or question may lack of more details of my settings, I just followed [the simple cmake tutorial](https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html#), and not sure what settings could be relevant, please let me know if there's any. 

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by simsicon** [comment]
I don't know why, but it seems that there is no import error if executable reference the code, I can get it now, this issue is closed, but if anyone can explain more, please leave comments

**Comment by memsharded** [comment]
Hi @simsicon 

To be honest it is not fully clear to me what was happening, did you mean the Conan imports, like Python code? Or the C++ ``#include`` of the dependencies?

**Comment by simsicon** [comment]
@memsharded thank you for your honest mention, it's just the import errors like the screenshot, VSCode can not find the source, but I can use cmake to build from terminal. 

![image](https://user-images.githubusercontent.com/475199/230524127-3d9c02ae-73d0-4398-a15f-622951ea65cd.png)

**Comment by memsharded** [comment]
Thanks for the clarification @simsicon !

Ok, so it was the ``#includes``. I would expect that VSCode would not find them until the first ``cmake`` configure runs, and the ``CMakeLists.txt`` contains the ``find_package()`` that finds the respective dependency, otherwise the underline errors are expected, as VSCode will have no idea about include-dirs.
