### ISSUE TITLE
[bug] Error with conan cache clean ... while removing folders containing .git artifacts

### ISSUE THREAD

**Issue by todorico** [conan-io/conan#13636]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: msvc 192
* Conan version: 2.0.3
* Python version: 3.8.10

### Steps to reproduce

1. Build a recipe that create a .git folder in the build folder with conan.tools.scm.Git() for example.
2. Use "conan cache clean *" to remove the build cache
3. The command fail to remove every build directories that contain a .git file because of wrong access rights:

ERROR: [WinError 5] Accès refusé: 'C:\\Users\\t.odorico\\.conan2\\p\\t\\simancef2c7c7f30ad\\b\\build\\Release\\_deps\\catch2-src\\.git\\objects\\pack\\pack-dbb0dcd859bcb5edf7bd25e98eec19f48fbd948a.idx'

I can remove the files manually or with an rm command but not with conan cache clean *
Is there something I can do to prevent this from happening ? Even doing conan cache clean * in an admin prompt does not resolve the issue.

### Logs

Traceback (most recent call last):
  File "C:\Scoop\apps\python38\current\lib\site-packages\conan\cli\cli.py", line 272, in main
    cli.run(args)
  File "C:\Scoop\apps\python38\current\lib\site-packages\conan\cli\cli.py", line 171, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "C:\Scoop\apps\python38\current\lib\site-packages\conan\cli\command.py", line 164, in run
    self._subcommands[subcommand].run(conan_api, *args)
  File "C:\Scoop\apps\python38\current\lib\site-packages\conan\cli\command.py", line 181, in run
    info = self._method(conan_api, self._parent_parser, self._parser, *args)
  File "C:\Scoop\apps\python38\current\lib\site-packages\conan\cli\commands\cache.py", line 81, in cache_clean
    conan_api.cache.clean(package_list)
  File "C:\Scoop\apps\python38\current\lib\site-packages\conan\api\subapi\cache.py", line 66, in clean
    shutil.rmtree(app.cache.temp_folder)
  File "C:\Scoop\apps\python38\current\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Scoop\apps\python38\current\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Scoop\apps\python38\current\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Scoop\apps\python38\current\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 6 more times]
  File "C:\Scoop\apps\python38\current\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Scoop\apps\python38\current\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\t.odorico\\.conan2\\p\\t\\simancef2c7c7f30ad\\b\\build\\Release\\_deps\\catch2-src\\.git\\objects\\pack\\pack-dbb0dcd859bcb5edf7bd25e98eec19f48fbd948a.idx'

ERROR: [WinError 5] Accès refusé: 'C:\\Users\\t.odorico\\.conan2\\p\\t\\simancef2c7c7f30ad\\b\\build\\Release\\_deps\\catch2-src\\.git\\objects\\pack\\pack-dbb0dcd859bcb5edf7bd25e98eec19f48fbd948a.idx'

**Comment by memsharded** [comment]
Hi @todorico 

Thanks for your report.
A couple of quick questions:

If you remove it manually, and repeat, is it always stuck in the same exact file?
If you call it several times, it is always the same file too, or it can progress and get stuck in another file?
If you remove only that specific file and call it again, what happens?
Does it happen only for that specific package, or any other package with git clones also fail same way?

In any case, it seems weird that you have a full git clone inside the ``build/Release/_deps/catch2`` folder, of another package. Maybe it is exporting some unwanted files?

This seems a system permissions thing, complicated to debug, lets see...

**Comment by memsharded** [comment]
Hi @todorico 

Any feedback about the above questions?

**Comment by todorico** [comment]
Hi @memsharded 

Sorry for the late response. Recently I had no time to investigate more.

> If you remove it manually, and repeat, is it always stuck in the same exact file?

It was stuck on multiple files under .git\objects\pack\* until I removed all of them, 

> If you call it several times, it is always the same file too, or it can progress and get stuck in another file?

It was not always the same files that could not be removed 

> If you remove only that specific file and call it again, what happens?

Another file would prevent the removal of the cache directory

> Does it happen only for that specific package, or any other package with git clones also fail same way?

It was happening for multiple packages that using git to clone repos

However, I tried to reproduce the problem with Conan 2.0.4 and so far I did not encounter the problem again. If I do not encounter it again by the end of the week, I will close the issue.

**Comment by memsharded** [comment]
Thanks for the feedback.
I have been running a diff from current code to 2.0.3 (the one was failing for you), and I cannot find anything in the code related to that that could be fixing it, so willing to know if it is fixed now, and in case if it is fixed if you can think of anything else that could have been changed in your setup recently (git version, users in CI, etc)

**Comment by AbrilRBS** [comment]
We haven't seen this elsewhere since then, closing this as solved as we didnt hear from you either, please feel free to re-open/create a new isse should you face new problems, thanks!
