### ISSUE TITLE
Packaging binaries using Conan 2.0

### ISSUE THREAD

**Issue by leinadme** [conan-io/conan#13641]
### What is your question?

Hi when I was working with Conan 1.0 I was able to export the binary files to the local conan cache using the following command:
conan export-pkg -f ../conanfile.py myProject/1.1.0@ --build-folder=../build
The libraries and cmake-config files lived in the build directory also was the lib and bin folders with their corresponding contents. The build folder is one level up from the root folder where the conanfile.py lives.

Using conan 2.0 it seems that --build-folder argument is no longer used.
I was able to export the header files using the following command in the root directory one level below my build directory.
conan export-pkg . 

I looked at the documentation, https://docs.conan.io/2.0/reference/commands/export-pkg.html
but I can't seem to figure out how to copy the binary files (dll and lib).
This is on a Windows 10 machine.

Any help would be appreciated.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @leinadme 

Thanks for your question.

The important bits in Conan 2.0 are:
- The ``layout()`` method, defining where ``self.folders.source`` and ``self.folders.build`` (some helpers like ``cmake_layout()`` define them. For cases where the conanfile is in a subfolder of the project, there is the ``self.folders.root = ".."`` definition too.
- The ``--output-folder`` that can define the base folder used as root of the temporary generated files (build, generators, etc)

With these 2 things you should be able to do what you want. If you would like more detail, please provide a detailed layout of your files, and a minimal ``conanfile.py`` that you are trying to use, so we can check it and advice.

**Comment by leinadme** [comment]
My folder layout is as follows, I couldn't find a way to indent the folder structure, I used "indent" to show what folders are parents.
sqliteinterface_library
"indent"- canaFile.py
"indent"-build folder
"indent""indent" -bin folder
"indent""indent"-cmake folder
"indent""indent"-CMakeFiles folder
"indent""indent"-lib folder
"indent""indent"-ATENAfolder
"indent""indent"- x64 folder
"indent""indent" -all the cmake-config files for the project used to build the library           
"indent"-cmake folder (contains project-config.cmake.in)
"indent"-ATENA folder 
"indent""indent"CMakeLists.txt
"indent""indent"-SQLiteInterface Folder
"indent""indent""indent"-all the source files
               

       Here is my recipe:
from conan import ConanFile, tools
from conan.tools.files import copy
from conan.tools.cmake import CMakeDeps
import os

class SQLiteInterface(ConanFile):
    name = "ATENA-sqliteinterface"
    version = "1.1.0"
    description = "Description here"
    topics = ("ATENA", "SQLiteInterface")
    settings = "os", "compiler", "build_type", "arch"
    requires = "sqlite3/3.39.2"
    default_options = {"sqlite3/*:shared": True}
    generators = "CMakeDeps"

    # place the generator files under the build folder
    def layout(self):
       self.folders.generators = "build"


    #install dll's besides libs
    def generate(self):  # conan 2.0
        for dep in self.dependencies.values():
            copy(self, "*.dll", dep.cpp_info.libdirs[0], self.build_folder)
            copy(self, "*.lib", dep.cpp_info.libdirs[0], self.build_folder)
		
    def get_platform(self):
        return os.environ.get('ATENA_PLATFORM', None)

    def package(self):
        copy(self, "SQLiteInterfaceExport.h", src=os.path.join(self.source_folder, "./"), dst=os.path.join(self.package_folder, "include"))  # conan 2.x
        copy(self, "*.h", src=os.path.join(self.source_folder, "ATENA/SQLiteInterface"), dst=os.path.join(self.package_folder, "include/ATENA/SQLiteInterface"))  # conan 2.x
		
		
        if self.settings.compiler == "apple-clang":
            copy(self, "libATENA-SQLiteInterface.dylib", src=os.path.join(self.source_folder, "lib"), dst=os.path.join(self.package_folder, "lib"))  # conan 2.x
        elif self.settings.compiler == "gcc":
             copy(self, "libATENA-SQLiteInterface.so", src=os.path.join(self.source_folder, "lib"), dst=os.path.join(self.package_folder, "lib"))  # conan 2.x            
        elif self.settings.compiler == "msvc":
            copy(self, "*.dll", src=os.path.join(self.source_folder, "bin"), dst=os.path.join(self.package_folder, "bin"))  # conan 2.x
            copy(self, "*.lib", src=os.path.join(self.source_folder, "lib"), dst=os.path.join(self.package_folder, "lib"))  # conan 2.x 			

    # Information needed by consumers of this package
    def package_info(self):
        print("platform: {}".format(self.get_platform()))
        self.cpp_info.libs = tools.collect_libs(self)
        if not self.settings.compiler == "msvc":
            self.cpp_info.cxxflags = ["-pthread"]  # C++ compilation flags
        self.cpp_info.sharedlinkflags = []  # linker flags
        self.cpp_info.exelinkflags = []  # linker flags

**Comment by leinadme** [comment]
I think I figured it out, just use the following:
    def package(self):
        copy(self, "*.lib", src=os.path.join(self.source_folder,"build/lib"), dst=os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, "*.dll", src=os.path.join(self.source_folder,"build/bin"), dst=os.path.join(self.package_folder, "bin"), keep_path=False)

**Comment by leinadme** [comment]
Does that make sense?

**Comment by leinadme** [comment]
It seems to work okay, so I won't waste any more of your time.

**Comment by memsharded** [comment]
```python
copy(self, ".lib", src=os.path.join(self.source_folder,"build/lib"), dst=os.path.join(self.package_folder, "lib"), keep_path=False)
```

Yes, that makes a lot of sense, it is important with the new ``copy()`` to use the absolute paths (explicit is better than implicit, it allows much better control, awareness of what is happening and debugging, and some more advanced cases that were not possible before).

Thanks for following up and the feedback!
