### ISSUE TITLE
Unable to download wtl/9.1.0@lasote/vcpkg

### ISSUE THREAD

**Issue by definename** [conan-io/conan#1364]
Hi,
I am unable to download wtl/9.1.0@lasote/vcpkg package.
Have error: **Status: 7;"Couldn't connect to server"**

That is cmake output:
> -- Downloading http://downloads.sourceforge.net/project/wtl/WTL%209.1/WTL%209.1.5321%20Final/WTL91_5321_Final.zip?r=&ts=1477467616&use_mirror=netix...
> -- Downloading http://downloads.sourceforge.net/project/wtl/WTL%209.1/WTL%209.1.5321%20Final/WTL91_5321_Final.zip?r=&ts=1477467616&use_mirror=netix... Failed. **Status: 7;"Couldn't connect to server"**
> CMake Error at vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:43 (message):
> 
> 
>       Failed to download file.
>       Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues
> 
> Call Stack (most recent call first):
>   vcpkg/ports/wtl/portfile.cmake:3 (vcpkg_download_distfile)
>   vcpkg/scripts/ports.cmake:73 (include)
>   CMakeLists.txt:12 (include)
> 
> 
> -- Configuring incomplete, errors occurred!

**Comment by memsharded** [comment]
I think it was a temporary network error of sourceforge. I have just tried and it worked fine. 
It seems that you are building from source the package, not installing a pre-built binary package, and the package recipe is retrieving the original artifacts from source forge.

Could you please try again?

**Comment by definename** [comment]
The same:

> -- Downloading http://downloads.sourceforge.net/project/wtl/WTL%209.1/WTL%209.1.5321%20Final/WTL91_5321_Final.zip?r=&ts=1477467616&use_mirror=netix...
> -- Downloading http://downloads.sourceforge.net/project/wtl/WTL%209.1/WTL%209.1.5321%20Final/WTL91_5321_Final.zip?r=&ts=1477467616&use_mirror=netix... Failed. Status: 7;"Couldn't connect to server"
> CMake Error at vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:43 (message):
> 
> 
>       Failed to download file.
>       Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues
> 
> Call Stack (most recent call first):
>   vcpkg/ports/wtl/portfile.cmake:3 (vcpkg_download_distfile)
>   vcpkg/scripts/ports.cmake:73 (include)
>   CMakeLists.txt:12 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/.conan/_mvuwvgh/1/CMakeFiles/CMakeOutput.log".
> 
> wtl/9.1.0@lasote/vcpkg: ERROR: Package '79c71dbda360a634692376cd2ed5aafa18493952' build failed
> wtl/9.1.0@lasote/vcpkg: WARN: Build folder C:/.conan\_mvuwvgh\1
> ERROR: wtl/9.1.0@lasote/vcpkg: Error in build() method, line 52
>         self._get_triplet()))
>         ConanException: Error 1 while executing call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\../../VC/vcvarsall.bat" x86 && cmake -G "Visual Studio 14 2015" -DCONAN_LINK_RUNTIME="/MT" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="14" -DCONAN_CXX_FLAGS="/MP4" -DCONAN_C_FLAGS="/MP4" -Wno-dev -DPORT=wtl -DTARGET_TRIPLET=x86-windows -DCMD=BUILD

**Comment by memsharded** [comment]
Could you check if you have connectivity to the file?. Just clicking on the link, I am able to download the ZIP in my browser from sourceforge. Maybe sourceforge is blocked in your location?

**Comment by definename** [comment]
File is downloaded. I am confused... Still have this problem.

**Comment by memsharded** [comment]
That is really weird? It is possible that you are behind a proxy that might be filtering sourceforge? And your browser has it configured?

**Comment by definename** [comment]
There is no proxy. Mb my network provider do somthing... How to check it?

**Comment by memsharded** [comment]
I have no idea of what could be failing. Could you please tell me your OS version, your cmake version, conan version? 

BTW, I see that you are targeting VS2015 (VS14), and for that there should be already a package in conan, can't you just skip the ``--build`` for this package, and use the existing package binary in conan.io? That way, it won't require downloading from sourceforge.

**Comment by definename** [comment]
I am trying to skip the `--build` for this package and have this [error](http://i.imgur.com/G0RJpR2.png)
This is my environment [environment](http://i.imgur.com/ptOOfNz.png)

**Comment by memsharded** [comment]
It could be that there is no existing binary for your configuration, because you are using a non-common one. You are using ``MT`` for the runtime, but using ``debug`` build config. And also, there are no packages for MT, like the existing one is for MD. Are you using MT linkage for any specific reason? If you don't care about it, you might try:

```bash
$ conan install -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MDd -s build_type=Debug
```

Yes, the environment matches mine, I also tried in Win10, cmake 3.7.1 again, and it is working fin. This is very weird, honestly I don't know what could be failing. Actually, it is the cmake script of the vcpkg the one that is trying to do the download, it is not even conan, but a direct cmake command.

Do you have access to other machine, other OS, that you can try? The only explanation I can imagine is some network filter, I guess you are at home, connected via an ISP, right?

**Comment by definename** [comment]
> Do you have access to other machine, other OS, that you can try? The only explanation I can imagine is some network filter, I guess you are at home, connected via an ISP, right?

Yeap that is from home computer and I connects via an ISP. In my office all works fine... It had worked fine before. I didn't install firewall or filter... It just occurred few days ago.

**Comment by memsharded** [comment]
I have no idea of what could be happening. Maybe it is not worth the effort. As it is a header-only library, a real native conan package (as opposed to this one which is just a wrapper of a vcpkg cmake port), would just take a few minutes to create. Why don't you try yourself to create a package for it? I can help if necessary.

**Comment by definename** [comment]
> Why don't you try yourself to create a package for it?
I added headers into the project structure. Currently have no time to do it.
