### ISSUE TITLE
Recipe not generating config files

### ISSUE THREAD

**Issue by leinadme** [conan-io/conan#13640]
### What is your question?

Hi!,
I'm running a comand which implements a conan install
conan install .. -s compiler.version=193 --build=missing -s build_type=Release
In this recipe, it installs the sqlite3 binaries and libs.
After the install runs, I get the following warnings which comes from SQLite which I know is using an old recipe which I don't manage since I'm getting it built and installed by conan.
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

======== Computing dependency graph ========
Graph root
    conanfile.py (tena-sqliteinterface/1.1.0): C:\tena-source-git\sqliteinterface_library\conanfile.py
Requirements
    sqlite3/3.39.2#c611c7a15142464a30c89908b6fab527 - Cache

======== Computing necessary packages ========
Requirements
    sqlite3/3.39.2#c611c7a15142464a30c89908b6fab527:87804f6d4bc1492e896ee18927aee2681ce38ac6#ef5be5ac0f46d6dcc21b64c8f4d36e90 - Cache

======== Installing packages ========
**sqlite3/3.39.2: Already installed! (1 of 1)
WARN: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN:     'cpp_info.filenames' used in: sqlite3/3.39.2
WARN:     'cpp_info.names' used in: sqlite3/3.39.2
WARN:     'cpp_info.build_modules' used in: sqlite3/3.39.2
WARN:     'env_info' used in: sqlite3/3.39.2**

======== Finalizing install (deploy, generators) ========
conanfile.py (tena-sqliteinterface/1.1.0): Generating aggregated env files
conanfile.py (tena-sqliteinterface/1.1.0): Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
Install finished successfully

The problem is, in Conan 2.x, I had several config files which was generated by the install command.
  SQLite3Config.cmake
  sqlite3-config.cmake
but now they are not generated so when I do a build it fails.  Any idea how I can get conan to generate those files?  This is an example.  I have other libraries like Boost that has teh same issues.

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by leinadme** [comment]
Ok, so I figured out how to do it, simply add "generators = "CMakeDeps"
The issue now is it is placing the files in the root folder instead of my build folder which where 1.x placed them.  Would you know how to specify the folder to place the files?  Using Windows 10.

**Comment by leinadme** [comment]
Never mind, I figured it out using layouts().
    # place the generator files under the build folder
    def layout(self):
       self.folders.generators = "build"

**Comment by memsharded** [comment]
Yes, that is correct:

- The warnings are expected, they happen because recipes have some legacy things to support legacy 1.X generators that will be removed in a later 2.X version
- The layout() indeed is very recommended for 2.X recipes (it is available too in 1.X)
