### ISSUE TITLE
short_paths feature in Linux

### ISSUE THREAD

**Issue by cocoza4** [conan-io/conan#13659]
### What is your question?

Hi,
I'm cross-compiling for Windows on Linux. I'm facing 
```
\root\.conan\data\openvino\2022.3.0\_\_\source\src\common\transformations\src\transformations\common_optimizations\convert_compression_only_to_legacy.cpp : fatal error C1083: Cannot open compiler generated file: '': No such file or directory

make[2]: *** [src/common/transformations/CMakeFiles/inference_engine_transformations_obj.dir/build.make:342: src/common/transformations/CMakeFiles/inference_engine_transformations_obj.dir/src/transformations/common_optimizations/convert_compression_only_to_legacy.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
```
I think it's because long path exceeds MSVC character limit. I came across https://docs.conan.io/1/reference/conanfile/attributes.html#short-paths but when I enabled it, it didn't seem to affect anything at all. In Linux, does this feature work? if not, how can I shorten/modify hash?

I'm using Conan 1.58.0. Cross compiling on Linux: https://github.com/mstorsjo/msvc-wine
thanks
Peeranat F.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cocoza4 

Thanks for your report.

This is very unexpected, I really thought that Linux does not suffer from this problem, if you are running in Linux, no matter if you are cross-compiling, the OS is Linux, the tools run in Linux, and long paths shouldn't be a problem at all. At least this was my understanding, and this is the first time someone reports this. Maybe the ``msvc`` installation via ``wine`` suffers the same limitation that Windows native system? 

If this is the case, I am afraid that this won't be possible in Conan 1.X. The ``short_paths`` is very deep in the Conan code, and lots of assumptions it is for Windows OS only.

Fortunately this has been removed in Conan 2.0, and the cache in 2.0 doesn't suffer from the long paths issue with a new design.

**Comment by cocoza4** [comment]
As a workaround, is there a way for us to build from outside of conan path e.g. `/root/my_build` and not `\root\.conan\data\openvino\2022.3.0\_\_\build\1802d478666194d20415168b92739c8d4ad3d246` ?

**Comment by memsharded** [comment]
I guess that you could do a local build, with ``conan install .`` + ``conan build .`` + ``conan export-pkg .`` (with the right arguments) and that will build locally, not in the cache.

**Comment by cocoza4** [comment]
I will give it a try. Thanks

**Comment by cocoza4** [comment]
@memsharded I got it to work. Thanks
