### ISSUE TITLE
[bug] conan error“cannot import name 'ConanFile' from 'conans' (/root/anaconda3/envs/py37/lib/python3.7/site-packages/conans/__init__.py)”

### ISSUE THREAD

**Issue by fate1930** [conan-io/conan#13652]
### Environment details

Linux version 3.10.0-957.21.3.el7.x86_64
gcc version 4.8.5 20150623
Conan version 2.0.3
Python 3.7.13

### Steps to reproduce

When I try to use "conan download "poco/1.11.3#*" -r conancenter" to download all the revisions,it reported the error
However，the command "conan download "poco/1.11.3" -r conancenter" don't have the same question ,I can normally get the latest revisions.

### Logs#13651 
(py37) [root@iZuf65f1afl5bovf7ll7b1Z bin]# conan download "poco/1.11.3#*" -r conancenter

Downloading recipe 'poco/1.11.3#2f5e663a2d744e2d86962bfff2b2345e'

Decompressing conan_export.tgz

ERROR: Error loading conanfile at '/home/pocod67ce28c2d8ef/e/conanfile.py': Unable to load conanfile in /home/pocod67ce28c2d8ef/e/conanfile.py
  
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pocod67ce28c2d8ef/e/conanfile.py", line 2, in <module>
    from conans import ConanFile, CMake, tools

ImportError: cannot import name 'ConanFile' from 'conans' (/root/anaconda3/envs/py37/lib/python3.7/site-packages/conans/__init__.py)

**Comment by memsharded** [comment]
Hi @fate1930 

Thanks for your comments.
This wouldn't be a bug, but expected behavior.
Old poco versions from old revisions are not Conan 2.0 compatible, because they contain old imports that don't exist anymore.

If you try to install that revision of poco it will tell this error message:
```
$ conan install --requires=poco/1.11.3#2f5e663a2d744e2d86962bfff2b2345e                                                                           
                                                                                                                                                              
======== Input profiles ========                                                                                                                              
....                                                                                                                            
======== Computing dependency graph ========                                                                                                                  
Graph root                                                                                                                                                    
    cli                                                                                                                                                       
*********************************************************                                                                                                     
Recipe 'poco/1.11.3' seems broken.                                                                                                                            
It is possible that this recipe is not Conan 2.0 ready                                                                                                        
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html                                                                                      
If it is your recipe, check if it is updated to 2.0                                                                                                           
*********************************************************                                                                                                     
                                                                                                                                                              
ERROR: Package 'poco/1.11.3' not resolved: poco/1.11.3: Cannot load recipe.                                                                                   
Error loading conanfile at 'C:\Users\memsharded\.conan2\p\pocod67ce28c2d8ef\e\conanfile.py': Unable to load conanfile in C:\Users\memsharded\.conan2\p\pocod67ce28c2d8ef
\e\conanfile.py                                                                                                                                               
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module                                                                                     
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                
  File "C:\Users\memsharded\.conan2\p\pocod67ce28c2d8ef\e\conanfile.py", line 2, in <module>                                                                       
    from conans import ConanFile, CMake, tools                                                                                                                
ImportError: cannot import name 'ConanFile'                                                                                                                   
```                                    

This is something that cannot change, the old revisions need to be there for users still in 1.X and for historic reproducibility, and they cannot be changed because they would create new revisions, not those revisions.

**Comment by fate1930** [comment]
Hi @memsharded ,thank you very much for your interpretation. However, does that means I must download the revisions published before conan version 2.x with the previous conan veriosn 1.x.And I cannot use the "conan download " command to download all the revisions in the conancenter list.

**Comment by fate1930** [comment]
In addition,if there is a proper way to distinguish the ownership version of the revisions before I use the command to download.

**Comment by memsharded** [comment]
> Hi @memsharded ,thank you very much for your interpretation. However, does that means I must download the revisions published before conan version 2.x with the previous conan veriosn 1.x.And I cannot use the "conan download " command to download all the revisions in the conancenter list.

Yes, it will not be possible to download all the previous revisions with 2.0, but it will be necessary to use 1.X for this. 

> In addition,if there is a proper way to distinguish the ownership version of the revisions before I use the command to download.

There is no ownership, as current revisions are both simultaneously compatible for Conan 1.X and 2.0. It is not that some revisions belong to 1.X and some other revisions belong to 2.0 (the package binaries are indeed different, with different ``package_id``, and Conan 1.X only sees its binaries, and Conan 2.0 only sees its binaries)

The question would be what are you trying to achieve. Downloading all the previous revisions from ConanCenter is useless and a waste of space in the general case. It is more expected to download specific revisions (the ones that have been used in your production system). If you want the "history", everything that is in the ConanCenter repository comes from the ``conan-center-index`` Github repository, so every past state and past revision for packages in ConanCenter would be in some commit of that repo. What problem are you trying to solve?

**Comment by fate1930** [comment]
Hi, @memsharded ,the fact is that maybe it is necesssry for me to download all the revisions as the basic data stored in my repository(not only the poco mentioned),l need to execute the commands in batch to download different packages.I read the  document and found the command conan download "[pkgs]/[version]#*" -r conancenter",and it means that I can download all the available revisions when I use the wildcard.However,it didn't work indeed,which made me feel confused.

**Comment by fate1930** [comment]
conan download will download only the latest revision by default. If you want to download more revisions other than the latest one you can use wildcards in the revisions part of the reference pattern argument

You may also just download recipes (in this case selecting all the revisions in the pattern, not just the latest one):

# download all recipe revisions for zlib/1.2.13
$ conan download "zlib/1.2.13#*" -r foo --only-recipe

**Comment by memsharded** [comment]
> Hi, @memsharded ,the fact is that maybe it is necesssry for me to download all the revisions as the basic data stored in my repository(not only the poco mentioned),

Still not clear why you need this. ConanCenter has tons of old recipe revisions that are mostly useless as outdated. Unless you had used it in production is pretty pointless to have a copy of them, but there is no one that had used all recipe revisions from ConanCenter, that is basically impossible. Why not storing just the revisions that you use for your builds?


> l need to execute the commands in batch to download different packages.I read the document and found the command conan download "[pkgs]/[version]#*" -r conancenter",and it means that I can download all the available revisions when I use the wildcard.However,it didn't work indeed,which made me feel confused.

The docs are Conan 2.0 docs, they assume that the recipes would be at least 2.0-compatible, and old revisions in ConanCenter are not. Maybe the docs needs some clarification, but it is not expected that Conan 2.0 ``conan download`` will not be able to download legacy 2.0-incompatible revisions.

**Comment by memsharded** [comment]
Hi @fate1930 

Any further feedback or question here? Can we close this ticket? Thanks!
