### ISSUE TITLE
Visual Studio integration

### ISSUE THREAD

**Issue by deadlocklogic** [conan-io/conan#13651]
### What is your question?

Is there a way for a seamless integration with Visual Studio?
Right now the way I am following is to generate a Visual Studio solution and then build it.
Now whenever I need to add files to my project I need to modify the `CMakeFiles.txt` and regenerate the solution which becomes messy and redudant.
Is there a way to build the cmake project directly within Visual Studio by just providing the toolchain as vcpkg does?
I tried setting `cmakeToolchain` in `CMakeSettings.json` with no effect.
Thanks.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by deadlocklogic** [comment]
Somehow things worked using `CMakePresets.json`/`CMakeSettings.json` after a clean configure.

**Comment by memsharded** [comment]
Hi @deadlocklogic 

Thanks for your question.

For automatically calling ``conan install`` to get the dependencies when ``cmake`` executes we are not resuming work on the ``cmake-conan`` integration for Conan 2.0 in: https://github.com/conan-io/cmake-conan/tree/develop2 (note the ``develop2`` branch, and it is very early stage).

I haven't used ``CMakeSettings.json``, but if it works, great, thanks for sharing it.

**Comment by Simran-B** [comment]
I recently experimented with Conan 2 and VS 2019's "Open Folder experience" and found the following issues:
- Visual Studio ships with its own integrated CMake, but the version is dated.
- This CMake version doesn't support the schema versions of the CMake preset files that Conan generates
- Beware that you need to enable CMake presets support in VS to make it work at all - the default is to only look for the older `CMakeSettings.json`
- VS 2019, respectively its bundled CMake, doesn't support `CMakeUserPresets.json` with its `include` directive. As a workaround, you can copy the `CMakePresets.json` from `build\generators\` to your source root.
- VS 2019 doesn't support `configurePresets.toolchainFile` to locate the Conan-installed dependencies. even though this should be supported based on the claimed support for CMake preset schema versions in v16.10+, but it seems that VS isn't fully compatible in this regard. As a workaround, you can set `configurePresets.cacheVariables.CMAKE_TOOLCHAIN_FILE` to the value of the `toolchainFile` entry.
- In `CMakePresets.json`, you can set `configurePresets.cmakeExecutable` to use a different CMake binary but this doesn't seem to help - I believe it didn't use the specified binary, but even if it did, this would likely not change anything about the support for `toolchainFile` and `CMakeUserPresets.json`
- With the suggested workarounds, I am able to have VS automatically perform CMake configure runs as needed, as well as compile and link without problems. However, IntelliSense isn't working for some reason. It cannot find any of the include files of Conan-installed deps. If I do an external CMake configure and open the .sln in VS, IntelliSense does work.
