### ISSUE TITLE
Some libraries in the Conan Repo are not Conan 2.0 ready

### ISSUE THREAD

**Issue by leinadme** [conan-io/conan#13650]
### Environment details

* Operating System+version:  Windows 10
* Compiler+version:  msvc 193
* Conan version: 2.0.3
* Python version: 3.7

I'm trying to build my application which requires Qwt 6.1.6 as a dependency.  Qwt is indeed available in the Conan Repository.  It builds fine and I was able to use it with Conan 1.x but now that I migrated to 2.x, I get the following error.  Is there any way I can request or do myself to upgrade Qwt to Conan 2.0?  Right now, this is holding up my application development work.

*********************************************************
Recipe 'qwt/6.1.6' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'qwt/6.1.6' not resolved: qwt/6.1.6: Cannot load recipe.
Error loading conanfile at 'C:\Users\UserName\.conan2\p\qwt279075c3182a0\e\conanfile.py': Unable to load conanfile in C:\Users\UserName\.conan2\p\qwt279075c3182a0\e\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\UserName\.conan2\p\qwt279075c3182a0\e\conanfile.py", line 2, in <module>
    from conans import ConanFile, tools
ImportError: cannot import name 'ConanFile' from 'conans' (c:\python37\lib\site-packages\conans\__init__.py)

**Comment by memsharded** [comment]
Hi @leinadme 

Thanks for your comments.
This is expected and announced (see the release 2.0 blog post for example https://blog.conan.io/2023/02/22/Conan-2.0.html), it is impossible to have over 1500 recipe (multiple versions) updated to 2.0 overnight, it is a many months effort (the community has already been doing an amazing effort for many months)

If you want to track progress you can check (including a list of recipes that should be working) here: https://github.com/conan-io/conan-center-index/discussions/16196 (and in general, all the things related to ConanCenter should go to https://github.com/conan-io/conan-center-index, including specific issues about recipes).

I am closing this issue, as there is no further action necessary from the Conan tool itself, this belongs more to conan-center-index. Thanks!
