### ISSUE TITLE
[question] Impact of conf cxx flags on dependency cache

### ISSUE THREAD

**Issue by swhinton** [conan-io/conan#13653]
### What is your question?

I've just moved my project over to use conan and it's been great for the most part especially for cross-compiling. 

I need to generate different build profiles with different compile flags for testing where the compiled dependencies are not compatible between the different profiles. I saw some documentation that indicated one way to achieve this was using the `tools.build:cxxflags` in a profile. The problem I have is that conan doesn't know that it needs to build the dependencies for each profile independent of each other. E.g.

```
#profile 1:
include(default)

[conf]
tools.build:cxxflags=["--coverage"]
```

```
#profile 2:
include(default)

[conf]
tools.build:cxxflags=["-fsanitize=address"]
```

Is this the recommended approach, or have I misunderstood the use case for the `conf` flag?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @swhinton 

Thanks for your question
I think you are looking for a ``conf`` that allows to define which other confs should be part of the ``package_id`` of the packages, to define a new binary:
```
conan config list | grep package_id
...
tools.info.package_id:confs: List of existing configuration to be part of the package ID
```
The last one is the relevant one. It allows to define exactly that.
So if in your profile you add:
```
[conf]
tools.info.package_id:confs=["tools.build:cxxflags"]
```

Then, for different values of the flags, you will get different binaries. The only thing you should be careful is that it is a text inclusion, so for example changing the same flags in different order will produce different ``package_id``s and different binaries, even if in theory they should be the same.

**Comment by swhinton** [comment]
Thanks for the prompt response, @memsharded . That did the trick! I have much more learning to do!

**Comment by memsharded** [comment]
Excellent, happy to help! 
Don't hesitate to submit new issues if you have any further question.
