### ISSUE TITLE
[question] After upgrade conan to 2.0.3,  conan install can not work

### ISSUE THREAD

**Issue by fancygit** [conan-io/conan#13663]
### What is your question?

[conan_install.txt](https://github.com/conan-io/conan/files/11192164/conan_install.txt)

This is my conanfile.py

`from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps
from conan.tools.files import copy
import os

class IInspectPlugin(ConanFile):
    name = "i_inspect_plugin"
    version = "0.0.1"
    package_type = "shared-library"
    author = "<harry> <wangqijun@image-x.com.cn>"

    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of TestLua here>"

    topics = ("<Inspect>", "<Frame>", "<ImageX>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": True, "fPIC": True}
    exports_sources = "CMakeLists.txt", "src/*"

    def layout(self):
        cmake_layout(self)

    def requirements(self):
        self.requires("commonlibrary/0.0.2", transitive_headers=True, transitive_libs=True)

    def build_requirements(self):
        self.requires("protobuf/3.21.9")

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()
        for dep in self.dependencies.values():
            copy(self, "*.dll", dep.cpp_info.bindirs[0], os.path.join(self.build_folder, self.settings.get_safe("build_type")))

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

        # Explicit way:
        # self.run('cmake %s/hello %s'
        #          % (self.source_folder, cmake.command_line))
        # self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        build_type = self.settings.get_safe("build_type", default="Debug")

        copy(self, pattern="*.h", src=os.path.join(self.source_folder, "src"),
             dst=os.path.join(self.package_folder, "include"))
        copy(self, pattern="InspectLocationPlugin.lib", src=os.path.join(self.build_folder, build_type),
             dst=os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, pattern="InspectLocationPlugin.dll", src=os.path.join(self.build_folder, build_type),
             dst=os.path.join(self.package_folder, "bin"), keep_path=False)
        copy(self, pattern="InspectLocationPlugin.PDB", src=os.path.join(self.build_folder, build_type),
             dst=os.path.join(self.package_folder, "pdb"), keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["InspectLocationPlugin"]`

It works well until I upgrade conan to 2.0.3 from 2.0.2
Can you help me ?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
~Hi! Can you provide logs too please? And example invokation of how you're calling conan and what it is outputting would be really useful be able to help you more easily :)~

Don't listen to me, I didn't see the link. The issue has been fixed in 2.0.4, which will be released in the next few days!

**Comment by fancygit** [comment]
Thanks a lot , now I fallback to 2.0.2 it works.
