### ISSUE TITLE
[question] Setting CMAKE_TRY_COMPILE_TARGET_TYPE and other CMake variables from profile

### ISSUE THREAD

**Issue by realbogart** [conan-io/conan#13664]
### What is your question?

I'm trying to migrate my CMake toolchain to Conan profiles + CMakeToolchain. Here is my current profile:
```python
[settings]
os=Linux
arch=x86
compiler=clang
compiler.version=15
compiler.cppstd=20
compiler.libcxx=libstdc++11
build_type=Release
[conf]
tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"
tools.cmake.cmaketoolchain:system_name='Generic'
tools.build:sysroot='/home/workspace/sysroots/wasi-sysroot'
tools.build:cxxflags=['-O2', '-Wall', '-Wextra', '-Wpedantic', '-Wshadow', '-Wconversion', '-Werror', '-Wno-unused-command-line-argument', '--target=wasm32-wasi', '-nostartfiles', '-Wl,--import-memory','-Wl,--export-all', '-Wl,--no-entry', '-Wl,-allow-undefined-file=import.syms']
[options]
[tool_requires]
[buildenv]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
```

The only variables that I have to set manually in my CMakeLists.txt are these:
```CMake
set(CMAKE_C_COMPILE_OPTIONS_SYSROOT "--sysroot=")
set(CMAKE_CXX_COMPILE_OPTIONS_SYSROOT "--sysroot=")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
```

Can these be set from the profile somehow? And more generally, can I pass my own CMake variables from the profile using cmaketoolchain?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @realbogart 

Thanks for your question. 
I don't think there is a direct mapping of those CMake variables to Conan inputs. I think you might define ``--sysroot`` as ``cxxflag`` without making a difference, I recall users doing so.

Maybe an interesting approach is to leverage your own ``myown_toolchain.cmake``, defining what you want and passing it in your conf in the:
```
conan config list | grep cmake
...
tools.cmake.cmaketoolchain:user_toolchain: Inject existing user toolchains at the beginning of conan_toolchain.cmake
```
This ``tools.cmake.cmaketoolchain:user_toolchain`` would be a list of filenames that will be included in the toolchain automatically

**Comment by realbogart** [comment]
Wow, thank you for the fast reply! 

Moving `--sysroot` directly to `cxxflags` worked! I was also unaware of the very useful `conan config list` command. I'll try to pass the last one using `tools.cmake.cmaketoolchain:user_toolchain`. 

Would it make sense to add a feature that looks something like this?
`tools.cmake.cmaketoolchain:variables: ['CMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY']`

**Comment by realbogart** [comment]
Closing as resolved

**Comment by memsharded** [comment]
Excellent, thanks for the feedback!

Yeah, we thought about something like ``tools.cmake.cmaketoolchain:variables: ['CMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY']``, but at the end of the day, there could be too many corners, like users wanting to append to variables, to replace variables, to clear variables, to use placeholders, or to define them as CACHE variables or as normal variables, etc, etc. So the toolchain file seems a powerful and complete solution for all these cases.
