### ISSUE TITLE
conan test_package may force rebuild of dependee

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#1366]
For instance I've created two packages, `foo` and `foobar`, where foo depends on foobar.
Using `test_package` command will force a rebuild of foobar even if the binaries are there (I suspect it's because foobar starts with "foo"):

    ~/foo$ conan test_package .
    ...
    foobar/0.1@hilborn/stable: WARN: Forced build from source

**Comment by memsharded** [comment]
Yes, confirmed, this is because of ``foo`` is translated to a pattern, that finally matches foobar.
Trying to find a fix.

**Comment by memsharded** [comment]
Released in 0.24
