### ISSUE TITLE
[bug] I don't get the right expected recipe name with cmd 'conan inspect ..'

### ISSUE THREAD

**Issue by selim-pousse** [conan-io/conan#13673]
### Environment details

* Conan version: 2.0.3
* Python version: 3.9

### Steps to reproduce

class Ofris3(ConanFile):
  name            = 'Ofris3'
  version         = "3.0.0"  
  ....
  
def set_name(self):
    hw_role = os.getenv('hw_role', None)
    self.name = str(f"{self.name}-{hw_role}").lower()

### Logs

conan@c11813acc34c:~$ hw_role=ccu conan inspect project/ | grep name
name: Ofris3
    username: pis_cicd
    
=> I expected to get  'ofris3-ccu' as package name
=> the argument --raw  is not anymore available on conan 2.x

**Comment by selim-pousse** [comment]
I'm using this following command as workaround :
conan graph info project/ --format=json --filter version -vquiet | jq -C -r .nodes[0].ref

**Comment by AbrilRBS** [comment]
Hi, thanks for taking the time to report the issue. Allowing `conan inspect` to query by itself has now been requested a few times, and we'll track this in https://github.com/conan-io/conan/issues/13654

As for your "workaround", this is actually the expected flow for now! (You could remove `-vquiet`, Conan outputs its loging to stderr so only the json would make it to `jq`)
