### ISSUE TITLE
[question] How to make `Findxxx.cmake` module available in `CMAKE_MODULES_PATH`/How to copy a file to the package directory?

### ISSUE THREAD

**Issue by H-G-Hristov** [conan-io/conan#13679]
The following works for some recipes but it doesn't for others:
`self.copy("Findfmt.cmake", ".", ".")`

**Comment by memsharded** [comment]
The ``self.copy()`` should not be used anymore, it has been superseded by the ``copy()`` helper in ``from conan.tools.files import copy``: https://docs.conan.io/1/reference/conanfile/tools/files/basic.html#conan-tools-files-copy

The ``src`` and ``dst`` arguments for ``copy()`` are absolute paths, that should be good to resolve any possible ambiguities.

If you cannot make it work, please submit a full recipe and some commands that reproduce the issue. Thanks!

**Comment by H-G-Hristov** [comment]
Thank you. I am actually modifying this recipe for our needs:
https://github.com/conan-io/conan-center-index/blob/master/recipes/catch2/2.x.x/conanfile.py
I added
```python
exports=["FindXXX.cmake"]
```
and in the package method:
```python
def package(self):
    copy(self, pattern="FindXXX.cmaket", dst=self.package_folder, src=self......)
```
But I cannot figure out how to get the `export` directory's absolute path.

I also had to add to `package_info` to get the cmake module search path right:
```python
      self.cpp_info.builddirs = ["."]
```

**Comment by memsharded** [comment]
I think this could be because ``exports`` are for recipe files, not for package files.
If a file is source for the package it must be ``exports_sources`` instead. Then in the copy you would use ``src=self.source_folder``

**Comment by H-G-Hristov** [comment]
Thank you!

To summarise my changes to the above recipe:

```python
class Catch2Conan(ConanFile):
...
     exports_sources = "FindCatch2.cmake"
...

    def package(self):
...
        copy(self, pattern="FindCatch2.cmake", src=self.export_sources_folder, dst=self.package_folder)
...
    def package_info(self):
...
            # self.cpp_info.builddirs = ["."]
            self.cpp_info.builddirs.append(".")
```

**Comment by memsharded** [comment]
Nice! Thanks for following up and reporting the final changes!
