### ISSUE TITLE
[question] CMakeDeps not considering transitive build requirements?

### ISSUE THREAD

**Issue by s-mlr** [conan-io/conan#13683]
### What is your question?

Hi everybody,

I'm facing a setup where a conan ```package A``` contains a bunch of build scripts ```package_type = "build_scripts"``` and there is another conan ```package B``` with  ```package_type = "build_scripts"``` as well, which builds upon and wraps A, but still only contains build scripts . 

In my conan ```package C``` I require these build scripts. Instead of adding direct dependencies to both it does make sense in my mind to only depend on ```B```, which itself depends on ```A``` via ```tool_requires(A, visible=True)```, since ```B```  cannot stand alone anyway and ```A``` will only be utilized by calls to ```B```.

Using conan 2.0.3 the dependency graph reflects the setup as I would expect, but coming to CMakeDeps generator only the direct build dependencies are considered. This obviously breaks a ```find_package(A)``` call within ```B```.

Am I missing some configuration to make this use case possible? If it is not by design, I would be interested in why CMakeDeps restricts this, when the user takes care of downstream visibility for build requirements with the ```visible``` parameter already?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @s-mlr 

Thanks for your question.

I have reproduced your scenario in a test to make sure things work. Please have a look to https://github.com/conan-io/conan/pull/13689, to check if it is what you are trying to achieve.

In short, I think the key issue is that it is necessary to do:
```python
# in scriptsb
def requirements(self):
      self.requires("scriptsa/0.1", run=True, visible=True)
```
Because it is not a ``tool_requires``. That would mean that ``scriptsa`` is necessary to build ``scriptsb``, but this is not the case. The ``scriptsa`` is a regular "runtime" requirement of ``scriptsb``, whenever someone is depending on ``scriptsb``, they want also to run ``scriptsa``.

Please let me know if this helps.

**Comment by s-mlr** [comment]
Hi @memsharded

Thanks so much for already looking into it and providing the test! 

I took another look and was able to reproduce your results following the provided test setup. Unfortunately it still breaks moving to my actual setup, because your example is covering ```find_package()``` in ```module``` mode. If you were to try the same example in ```config``` mode you should find that ```CMakeDeps``` is only generating ```*-config.cmake``` for direct dependencies and the ```find_package(scriptsa)``` inside packageB won't work. 

https://github.com/conan-io/conan/blob/0a64c9f57098e7517b1c8e9659a31beabce9bae8/conan/tools/cmake/cmakedeps/cmakedeps.py#L53
https://github.com/conan-io/conan/blob/0a64c9f57098e7517b1c8e9659a31beabce9bae8/conan/tools/cmake/cmakedeps/cmakedeps.py#L68-L69

This is my test setup I derived from yours to reflect my situation more closely:

**packageA:**
```python
# conanfile.py 
from conan import ConanFile
from conan.tools.files import copy

class ScriptsA(ConanFile):
  name = "scriptsa"
  version = "0.1"
  package_type = "build-scripts"
  exports_sources = "*.cmake"

  def package(self):
    copy(self, "*.cmake", src=self.source_folder, dst=self.package_folder)

  def package_info(self):
    self.cpp_info.builddirs = ["."]
    self.cpp_info.set_property("cmake_build_modules", ["scriptsa.cmake"])
```
```cmake
# scriptsa.cmake 
function(myfunctionA)
  message(STATUS "MYFUNCTION CMAKE A: Hello world A!!!")
endfunction()
```

**packageB:**
```python
# conanfile.py 
from conan import ConanFile
from conan.tools.files import copy

class ScriptsB(ConanFile):
    name = "scriptsb"
    version = "0.1"
    package_type = "build-scripts"
    exports_sources = "*.cmake"

    def requirements(self):
        self.requires("scriptsa/0.1", run=True, visible=True)

    def package(self):
        copy(self, "*.cmake", src=self.source_folder, dst=self.package_folder)

    def package_info(self):
        self.cpp_info.builddirs = ["."]
```
```cmake
# findscriptsb.cmake 
find_package(scriptsa)

function(myfunctionB)
    message(STATUS "MYFUNCTION CMAKE B: Hello world B!!!")
    myfunctionA()
endfunction()
```

**packageApp:**
```python
# conanfile.py 
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps
from conan.tools.files import copy

class App(ConanFile):
  name = "app"
  version = "0.1"
  package_type = "application"
  settings = "os", "compiler", "arch", "build_type"

  def export_sources(self):
    copy(self, "CMakeLists.txt", self.recipe_folder, self.export_sources_folder)

  def generate(self):
    deps = CMakeDeps(self)
    deps.build_context_activated = ["scriptsa", "scriptsb"]
    deps.build_context_build_modules = ["scriptsa", "scriptsb"]
    deps.generate()
    tc = CMakeToolchain(self)
    tc.generate()

  def build_requirements(self):
    self.tool_requires("scriptsb/0.1")
    self.tool_requires("cmake/v3.21.0")

  def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
```
```cmake
# CMakeLists.txt 
cmake_minimum_required(VERSION 3.15)

project(App LANGUAGES NONE)

find_package(scriptsb)
myfunctionB()
```

**Comment by memsharded** [comment]
I am not using ``CMakeDeps`` at all! 😄 

If I change my test to:
```diff
--- a/conans/test/functional/graph/test_transitive_build_scripts.py
+++ b/conans/test/functional/graph/test_transitive_build_scripts.py
@@ -71,9 +71,9 @@ def test_transitive_build_scripts():
         myfunctionB()
     """)
     c.save({"scriptsa/conanfile.py": scriptsa,
-            "scriptsa/Findscriptsa.cmake": scriptsa_cmake,
+            "scriptsa/scriptsa-config.cmake": scriptsa_cmake,
             "scriptsb/conanfile.py": scriptsb,
-            "scriptsb/Findscriptsb.cmake": scriptsb_cmake,
+            "scriptsb/scriptsb-config.cmake": scriptsb_cmake,
             "app/conanfile.py": app,
             "app/CMakeLists.txt": app_cmake})
```
It still works.

This is because ``CMakeToolchain`` manages to inject the path to the package to locate the config.cmake scripts.
``CMakeDeps`` is only necessary when generating information for libraries and the like. To locate some cmake module/config scripts it is not necessary, they are already cmake scripts.

**Comment by s-mlr** [comment]
Ok, that is a good point. At least I think I understand how to create a work around.

So in my particular case I have to treat ```scriptsa``` as a third party repository with read-only access and it provides neither a ```Find*.cmake``` nor a ```*-config.cmake``` but just some arbitrary ```scriptname.cmake``` file. I'm working on creating a conan package out of it for us to use. That is why I tried to add this file to the auto include via  
```python
self.cpp_info.set_property("cmake_build_modules", ["scriptsa.cmake"])
``` 
and use ```CMakeDeps``` to get me there.

In this case I would try to manually add a respective ```Find*.cmake``` or ```*-config.cmake``` file during packaging, which just includes the ```scriptname.cmake```?

Or how would you approach this situation?

**Comment by memsharded** [comment]
> Or how would you approach this situation?

That is a good question. I think if there is no package to find, I would probably do:
- rely only on ``CMakeToolchain``, it will put the dependencies ``cpp_info.builddirs`` in the path
- Make sure the packages define ``cpp_info.builddirs``
- The consumer will do a direct ``include(scriptsa.cmake)`` or something like that. 

I think this should be doable too, and makes more sense that going through the hoops of ``find_package()``

**Comment by s-mlr** [comment]
I did go that route. Makes sense to me. 

Thank you so much for looking into this and having a conversation about it! Awesome support.

Cheers.
