### ISSUE TITLE
[question] Cmake generators: conan flag

### ISSUE THREAD

**Issue by xakod** [conan-io/conan#13684]
### What is your question?

Hi! Does Conan support smth like CONAN_EXPORTED but for generators? For example, my cmake helper scripts depends on package names. So if I use conan the target name can be a::a, but when I use my custom find scripts target name (I cannot change it) is just a.
```cmake
if (CONAN_GENERATOR_USED)
    target_link_libraries(${PROJECT_NAME} PUBLIC a::a)
else()
    target_link_libraries(${PROJECT_NAME} PUBLIC a)
endif()
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi,

There is nothing built-in, but adding new vars to the Conan invocations can be done with:

```python
def generate(self):
      tc = CMakeToolchain(self)
      tc.cache_variables["CONAN_EXPORTED"] = True
      tc.generate()
```

Other approach is to have the Conan recipes to generate a target name equal to the one that you are expecting, which can be done with (in the dependency recipe, not in the consumer):
```python
def package_info(self):
     self.cpp_info.set_property("cmake_target_name", "a") # instead of a::a
     # if also necessary to customize the filename, not only the target:
     self.cpp_info.set_property("cmake_file_name", "whatever_file_name")
```

**Comment by xakod** [comment]
> ```python
> def generate(self):
>       tc = CMakeToolchain(self)
>       tc.cache_variables["CONAN_EXPORTED"] = True
>       tc.generate()
> ```

I see you use CMakeToolchain. Will it work If I generate from conanfile.txt with CMakeDeps ?

**Comment by xakod** [comment]
> Other approach is to have the Conan recipes to generate a target name equal to the one that you are expecting, which can be done with (in the dependency recipe, not in the consumer):

I cannot do this because I use thirdparty from cci :)

**Comment by memsharded** [comment]
>  see you use CMakeToolchain. Will it work If I generate from conanfile.txt with CMakeDeps ?

Not possible, to customize the behavior you need to use ``conanfile.py``. You can read about the rationale in https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html
In any case, using ``CMakeToolchain`` generator is recommended, also if you use ``conanfile.txt``


> I cannot do this because I use thirdparty from cci :)

But ConanCenter already use those properties to define the target names equal to the upstream target names, there shouldn't be any divergence in names here.

**Comment by memsharded** [comment]
Closing this question as responded:
- Can be customized by using a ``conanfile.py`` instead of .txt and ``tc.cache_variables["CONAN_EXPORTED"] = True``
- ConanCenter recipes already provide the standard upstream CMake target names, there shouldn't be divergence in vast majority of cases.
