### ISSUE TITLE
[question] JSON generator is gone?

### ISSUE THREAD

**Issue by a1batross** [conan-io/conan#13687]
### What is your question?

Hello! 

In 1.5x I've been downloading packages like this:
```conan install $(pkg) -g json --build=missing -pr custom_profile```

... and then parsed `conanbuildinfo.json` file and added downloaded dependency to the project.

Now that I'm porting my code to 2.0, `-g json` doesn't work anymore. Seems it's completely gone from the repository, and I can't find an issue or a commit that removed it. 

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @a1batross 

Thanks for your question

The closest to the JSON generator has been moved the ``--format=json`` output formatter, that can be applied to ``conan install, conan create, conan graph info, conan export-pkg`` commands.

You can check: https://docs.conan.io/2/whatsnew.html#new-cli, and it should be also in the commands reference in: https://docs.conan.io/2/whatsnew.html#new-cli

**Comment by a1batross** [comment]
Thank you!

Yes, --format=json makes it easier for me :)
