### ISSUE TITLE
[question] options.shared value not defined even when specified in build and host profiles

### ISSUE THREAD

**Issue by r4stered** [conan-io/conan#13681]
### What is your question?

Hello. I am repackaging headers and binary libraries with conan and am trying to get the different configurations to work correctly. 

Im using conan version 2.0.2 on windows 11 x64

For package my first package (wpiutil), I am calling

```
conan create . --profile:build default --profile:build ..\.github\ci_conan_profiles\dbg_shared --profile:host default --profile:host ..\.github\ci_conan_profiles\dbg_shared
```

Here is my default profile:

```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

And here is ..\.github\ci_conan_profiles\dbg_shared

```
[settings]
build_type=Debug
compiler.cppstd=20

[options]
shared=True
```

This creates a package correctly, as seen by conan list
```
conan list wpiutil/2023.4.3:*
Local Cache
  wpiutil
    wpiutil/2023.4.3
      revisions
        bd1b46f840163614f2234addbe2d5ee6 (2023-04-12 23:47:12 UTC)
          packages
            23580f748869a078692c1ebc926fe58d9e19f009
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  os: Windows
                options
                  shared: True
                python_requires
                  wpicommon/0.1.Z
```

And when I try to package another library that depends on wpiutil (wpinet), I get an error saying options.shared wasn't defined for wpiutil

```
conan create . --profile:build default --profile:build ..\.github\ci_conan_profiles\dbg_shared --profile:host default --profile:host ..\.github\ci_conan_profiles\dbg_shared

======== Exporting recipe to the cache ========
wpinet/2023.4.3: Exporting package recipe: C:\Users\willi\dev\wpi-conan\wpinet\conanfile.py
wpinet/2023.4.3: Copied 1 '.py' file: conanfile.py
wpinet/2023.4.3: Exported to cache folder: C:\Users\willi\.conan2\p\wpineca12405bcc9c3\e
wpinet/2023.4.3: Exported: wpinet/2023.4.3#9b65c5c0f39aedb7d23d67ca54b11c2a (2023-04-12 23:48:13 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=193
os=Windows
[options]
shared=True
[conf]
tools.cmake.cmaketoolchain:generator=Visual Studio 17 2022

Profile build:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=193
os=Windows
[options]
shared=True
[conf]
tools.cmake.cmaketoolchain:generator=Visual Studio 17 2022


======== Computing dependency graph ========
Graph root
    cli
Requirements
    wpinet/2023.4.3#9b65c5c0f39aedb7d23d67ca54b11c2a - Cache
    wpiutil/2023.4.3#bd1b46f840163614f2234addbe2d5ee6 - Cache
Python requires
    wpicommon/0.1#f9908649863e9e1c8a1e9a7adf2750e1 - Cache

======== Computing necessary packages ========
wpinet/2023.4.3: Forced build from source
Requirements
    wpinet/2023.4.3#9b65c5c0f39aedb7d23d67ca54b11c2a:d468fc7c874729261a7c5aed6027e8b26019fd0c - Build
    wpiutil/2023.4.3#bd1b46f840163614f2234addbe2d5ee6:1ddf1259de389f0bdaaf6d3c26de1b25fa3b2a7e - Invalid

======== Installing packages ========
ERROR: There are invalid packages:
wpiutil/2023.4.3: Invalid: 'options.shared' value not defined
```

Im not sure why it would say that as options.shared is defined in the profile of the create command in both packages creation.

My code for creating the recipes is here: https://github.com/r4stered/wpiconan

Any help is appreciated,
Drew

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @r4stered 

Thanks for your question.

The ``options`` defined in profiles (and also when set in recipes for dependencies, possible, though defining them in profiles is recommended) follow a "pattern" approach. They are not automatically defined to all packages in the graph, if you want that, you need to specify:
```
[options]
*:shared=True
```

A couple of notes:
- Typically for the "build" context (build profile), static linkage could be preferred, it is simpler in some cases (but not always, just keep it in mind)
- There is other syntax when you want to apply some option only to the current consumer package, something like ``&:option=value`` can be specified
- Recipes can also default with ``default_options`` their value, is it possible that ``wpiutil/2023.4.3`` is not defining a default?

**Comment by r4stered** [comment]
Thank you for the clarification. Adding the *:shared=True seemed to fix my issue. 

The recipe does not have a default option, as I removed it when trying to figure out the issue above.
