### ISSUE TITLE
Undefined symbols for architecture x86_64 on macOS

### ISSUE THREAD

**Issue by yageek** [conan-io/conan#1369]
I am using version `0.23.1` on macOS Sierra `10.12.5 (16F73)`.

I have followed the [Tutorial to create the package](http://docs.conan.io/en/latest/packaging.html)
The result can be found here: https://github.com/yageek/lambert/tree/feature/conan

When I run `conan test_package`,  I get the following error while linking the example framework:
```[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable bin/example
Undefined symbols for architecture x86_64:
  "YGPointToDegree(YGPoint)", referenced from:
      _main in example.cpp.o
  "YGPointConvertWGS84(YGPoint, YGLambertZone)", referenced from:
      _main in example.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/example] Error 1
make[1]: *** [CMakeFiles/example.dir/all] Error 2
make: *** [all] Error 2```

**Comment by memsharded** [comment]
Hi @yageek 

I have started to have a look, first in windows. It seems the lib doesnt compile for the lack of definition of M_PI. Moving to Linux to check first the recipe.

**Comment by memsharded** [comment]
Seems fixed by https://github.com/yageek/lambert/pull/4, not a conan related issue but a C++ to C inclusion issue.
