### ISSUE TITLE
[feature] conan 2.0 verbose build option for meson

### ISSUE THREAD

**Issue by praetorian20** [conan-io/conan#13703]
### What is your suggestion?

Hi,
Conan 2.0 seems to be missing a verbose build option for meson.

I was doing the following with 1.x:
```python
meson = Meson(self)
meson.configure(<configure-opts>)
meson.build(args=['--verbose'])
```

I've updated my conanfile.py as follows for 2.0
```python
tc = MesonToolchain(self)
tc.project_options.update(<options>)
tc.properties.update(<props>)
tc.c_args = [<C defines>]
tc.generate()
meson = Meson(self)
meson.configure()
meson.build()
```
But now the `build` function doesn't take any arguments that it passes along to the backend.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @praetorian20 

I think for the ``verbosity`` issue, the correct approach is to extend https://github.com/conan-io/conan/pull/13428, and future https://github.com/conan-io/conan/issues/12239 for CMake, to Meson too. It shouldn't be necessary to hardcode the verbosity level in recipes.

**Comment by praetorian20** [comment]
Thanks for the quick response @memsharded. `tools.build:verbosity` extended to meson sounds perfect. I wasn't hardcoding it in the recipe, I added it as a package option, which is also not great. The generic verbosity level is much better.

Is anyone currently working on adding that capability to meson?

**Comment by memsharded** [comment]
It was planned that @RubenRBS could be doing something for CMake for 2.0.5 if possible, maybe that can be extended to Meson as well. Even if Meson is not done next, it would be better to wait for CMake to get it first, then follow with Meson.

**Comment by AbrilRBS** [comment]
Exactly as @memsharded said, I meant to tackle it these past few weeks, but some unexpected work in the infra of conan center index stole my time, so this is something I'll get this week, with hopefuly Meson verbosity too :)
