### ISSUE TITLE
[feature] don't warn on missing star removal

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#13701]
### What is your suggestion?

I frequently use the command `conan remove -f "*"` to cleanup my projects. However, this does not behave strictly idempotently.

When the command is run two or more times before reinstalling conanfile.txt packages, then conan emits a spurious warning:

```text
WARN: No package recipe matches '*'
```

This warning is not actionable.

When the conan removal command is automated as part of a larger cleanup script, then the user may become confused and think there is a problem.

One workaround involves piping the process' output to a null device. However, this risks eliding other, more relevant warnings. And it is more cumbersome to setup null device redirection in a portable way, considering the variety of shell interpreters including Command Prompt, PowerShell, POSIX sh family, csh family, fish, ion, rc, and so on.

Another workaround involves piping the output through grep to remove this specific warning. Though that is fragile, in case the conan message format changes over time. And it requires grep to be installed, which represents technology stack creep in the context of Docker containers and general dev environment setup.

I would like for this warning to be skipped, whenever the requested package query matches asterisk (`*`).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mcandre 

Thanks for your suggestion.

This has already been changed in Conan 2.0. The warning will not be emitted for this case.
For Conan 1.X only important bugs and necessary changes to allow recipe migration for 1.X->2.0 will be considered in general, so I suggest closing this issue as implemented in 2.0

**Comment by memsharded** [comment]
Closing this as fixed in 2.0, but please don't hesitate to create new tickets for any further questions.
