### ISSUE TITLE
[question] automatically update local config

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#13708]
### What is your question?

Hey!

The Situation:

In our company we have multiple repositories managed as conan packages. The conan configs are placed in a git repo too. Every repository stores the information, which config version is used to build it, in a json file located in that same repository. This json file is read by Jenkins and the right config repo version is installed before every build.

The Problem:

Our developers are usually working in multiple repositories. Every repository might has a different version of that config repository. So every time a developer wants to build a repository they need to install the right config repository. They might not need to install it when the repo is using an older version that the developer has installed and it is downwards compatible. But at least when the repo requires a newer version it might become a problem. 

The Question: 

So my question is, if there is a way to automatically update the developers installed config using that json file every time before a repository is build? Beside that it feels a bit clumsy that the local config is basically always overridden, when building an other repository. Could that become an issue?

I'm aware of the new extensions of conan2 but at least the hooks seems to be not suitable here, since the config update would need to be done before the hooks come into play, I guess. Are there other extension point, which could be used for what we want to achieve?

We are using conan2 already.

Thank you very much!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nicosmd 

Thanks for your question.
We had in Conan 1.X a scheduled cron-like that call ``conan config install`` over a memorized url. But it was super problematic, so we decided to drop it for 2.0

At the moment there is no other extension point that would be a good place to implement such functionality. 
Conan 2.0 introduced a yet undocumented (iirc) ``.conanrc`` that is able to define a different ``CONAN_HOME`` for every project.

Even if it would be possible to leverage such ``.conanrc`` it seems it would still be a bit arbitrary to define the behavior, for example:
- Lets say that we define in ``.conarc`` something like a ``config_install_url``
- Which commands will trigger the ``conan config install`` when this is found?
- If it is called all the time, for every command, for many commands (install, create, graph), it would be a destructive action for some user-defined local config, for example if a developer temporarily tries to add another remote, but then the next ``conan install`` would trigger the ``config_install_url``, and re-install the original remotes, removing the developer one.

**Comment by nicosmd** [comment]
Hey @memsharded thanks a lot for your answer, which was fast and precise as always. 

I see the problematic behind an implicit config update. I also would like to avoid having a different conan cache for every project, since that require much more space on the developers machine compared to one cache. 

I could imagine to create a hook, which at least informs the user that the current project is specifying a different config version than the one, which is installed. Would it work to update the config from a custom command extension? That command could provide at least some convenient way for the developers to explicitly update the config based on the json file in the project.

**Comment by memsharded** [comment]
> I see the problematic behind an implicit config update. I also would like to avoid having a different conan cache for every project, since that require much more space on the developers machine compared to one cache.

You could have different "homes" for different projects, each one will have different config, but they can point to the same storage of packages, via the ``core.cache:storage_path`` conf.

> I could imagine to create a hook, which at least informs the user that the current project is specifying a different config version than the one, which is installed. 

How would you implement this, checking some local file, lets say with a version, against a server side one (like calling curl, or ``requests.get()`` or something like that, to get the server file contents, compare the contents and report accordingly? (this part for me is the most difficult one)

> Would it work to update the config from a custom command extension?  That command could provide at least some convenient way for the developers to explicitly update the config based on the json file in the project.

Calling ``conan config install`` for a project when a json file with the url is found, should be quite straightforward and convenient, just a ``conan myconfig-install`` (or something like that, without arguments), and devs would get their config updated based on the json file

**Comment by nicosmd** [comment]
> You could have different "homes" for different projects, each one will have different config, but they can point to the same storage of packages, via the core.cache:storage_path conf.

Oh, I was not aware of that, but it is a neat feature. This might gives us some more opportunities to handle the local configs. 

> How would you implement this, checking some local file, lets say with a version, against a server side one (like calling curl, or requests.get() or something like that, to get the server file contents, compare the contents and report accordingly? (this part for me is the most difficult one)

Actually, this describes quite precise the idea I had in mind. I would put a version file in the config repo to read from in after the `conan config install` to know which version is installed locally. I also could imagine to not verify the version against a server one but against that config version stored in the json of the particular repository and trying to keep that json updated by an CI service. Than the hook would not require http requests but only checking some local files. 

> Calling conan config install for a project when a json file with the url is found, should be quite straightforward and convenient, just a conan myconfig-install (or something like that, without arguments), and devs would get their config updated based on the json file

That sounds pretty good :) I really like the new extension points conan2 provides.

**Comment by memsharded** [comment]
Good!

So, as I view it, I'd probably recommend something in this line:

- you can have a custom command that checks the json, install the config of the project.
- This is trivial for CI, and for developers it requires an extra step, calling it when they switch projects, but sounds a reasonable trade-off at the moment, compared with the complexity of the added automation to try to call it automatically, that always has some unexpected rough edges.
- I think that a bit down the road we might be able to consider to do something a bit more built-in in ``.conanrc``, but this is a bit speculative at the moment, and we need to further stabilize a bit Conan 2.0 and ConanCenter migration, so this would take some time to consider.

**Comment by nicosmd** [comment]
Thank you very much! That's for me a good way to go for the moment. I will looking forward to the built-in functionality and the new `.conanrc`. Is there maybe already some rough description to read more about the idea of `.conanrc`? That sounds pretty interesting.

**Comment by memsharded** [comment]
There is no docs for it yet, but there is already this ticket open, if you want to follow it: https://github.com/conan-io/docs/issues/3172

**Comment by nicosmd** [comment]
Thanks!
