### ISSUE TITLE
Clarify Gloabl conf is a user provided file and is expected to be generated 

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#13714]
When installing conan and running a command there are a set of files that are generated automatically however it's not always clear which files should or should not be present.

For example  https://docs.conan.io/2/reference/config_files/global_conf.html

> The global.conf file is located in the Conan user home directory, e.g., [CONAN_HOME]/global.conf.

However is only ever read from https://github.com/conan-io/conan/blob/5b242f73acc4e08ef9bffe514ed9778f26f071ce/conans/client/cache/cache.py#L154-L172

But it's not clear from the documentation that this files needs to be created explicitly by the user. Also it's unclear if this should be managed with `conan config install` which I'd assume yes but its not mentioned from my search.

Question on slack https://cpplang.slack.com/archives/C41CWV9HA/p1681744108614179 for reference.

**Comment by memsharded** [comment]
Hi @prince-chrismc 

Not very clear what is the issue, please try to not post links to threads that require registering, as they might not be visible to everyone (I don't have access to that slack at the moment).

To clarify one point: the ``global.conf`` file is not automatically created, the user that wants to customize it should create it. Maybe we want to create the file, even if it is an empty file?

**Comment by prince-chrismc** [comment]
I got distracted and never finished filling this out. I've updated the title and the description. I put the link so I could follow up :) but all the details are here on github

> To clarify one point: the `global.conf` file is not automatically created, the user that wants to customize it should create it.

This is exactly what was not clear about the current documentation.

**Comment by SSE4** [comment]
it's completely unclear if file is expected to be there after the installation, or if user has to create it themselves.

> The global.conf file is located in the Conan user home directory, e.g., [CONAN_HOME]/global.conf.

right now, this statement is wrong - file is not there (checked on multiple machines), and users think it's a broken installation, or some malfunction.

**Comment by memsharded** [comment]
Lets add this file automatically, empty (can have comments) by default

**Comment by memsharded** [comment]
Maybe consider the same for ``settings_user.yml``, to be discussed

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/13746.

``settings_user.yml`` is less problematic, as it is better documented in that regard, lets leave it as-is at the moment
