### ISSUE TITLE
[question] Test reports

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#13715]
### What is your question?

Dear Conan Folks,

I am a bit divided about the topic where shall test reports for a package belong to.
In this case for every package I have number of tests: Unit tests, static code analysis, functional tests, simulation tests, on device tests. Each of them will generate a report. I think that this shall be shipped along with the binaries or libraries of the package so that the binary and the reports are all in the same unit and can be referenced by the consumer of the package. But what I am concerened about is :
- The size of the package will increase.
Other alternatives that I thought about is:
- Having a generic repo for reports but then that will come with a disadvantage of linking the reports belonging to a package.
-  Having another conan package for storing reports again there also we need to link the reports  belonging to a package.
Could you please help me what is the suggestion from the experts?

Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

Thanks very much for your question.
I think it is very interesting, and I think we are already contemplating it, please check https://github.com/conan-io/conan/pull/13330

The idea is a metadata layer, that allows storing such reports, in the server, together with the package, but they will not be downloaded everytime the package is used. The storage in the server will still happen, that is inevitable, no matter the technology or the approach, it is necessary to store it, but the metadata layer will handle it automatically and make it very convenient.

We will continue finalizing this feature in the next releases and documenting it (you might experiment with it, but note it is not ready for production. Also, do not use if you are still using Conan 1.X; as until Conan 1.60, it might break the Conan 1.X client)

**Comment by maitrey** [comment]
Thanks @memsharded for the excellent news. I am so glad that this feature is already being considered. Should I leave the question open meanwhile?

**Comment by memsharded** [comment]
Yes, it can be open until we do the public release. Thanks!

**Comment by memsharded** [comment]
The metadata story is implemented in PR https://github.com/conan-io/conan/pull/13918 for next 2.0.7

**Comment by memsharded** [comment]
Merged, it will be in next 2.0.7

**Comment by hubertba** [comment]
HI ... nice to see it closed, but is somewhere a link to a documentation on how I can use that feature?

Pretty Please and Thank You.

**Comment by memsharded** [comment]
Hi @hubertba 

Thanks for pointing this out. Indeed the docs are still a WIP, but it will soon be released, you can see the current status and track its progress in https://github.com/conan-io/docs/pull/3283
