### ISSUE TITLE
[bug] When creating a package using MSVC, the build fails when source code path is too long

### ISSUE THREAD

**Issue by DominicPicard** [conan-io/conan#13726]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: MSVC 19.33
* Conan version: 1.59
* Python version: 3.9.13

### Steps to reproduce

When we run `conan create`, the source code gets copied to the `CONAN_USER_HOME` variable and the total path is a combination of the `CONAN_USER_HOME`+package name + version + id + ... + source code.

The problem is not with Conan itself, but with MSVC. MSVC fails when the source code path is too long.

Is there a way to fix that issue ? Is it possible to change the build directory to a shorter one so MSVC does not complain ? 

### Logs

fatal error C1083: Cannot open compiler generated file

**Comment by AbrilRBS** [comment]
Hi @DominicPicard thanks for your question.
Have you taken a look into https://docs.conan.io/1/reference/conanfile/attributes.html#short-paths? That and its associated env variable were implemented to solve issues such as this.

Let me know if that helps or if the problem persists :)

**Comment by DominicPicard** [comment]
Hi Ruben,

Yes, it is exactly what I needed ! 

Thanks for the quick reply 😄
