### ISSUE TITLE
[question] How to make package queries based on options or requires in conan list/remove?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#13724]
### What is your question?

In conan list & conan remove documentation, package query examples are all based on settings (`-p "compiler=gcc"` etc). But since settings is nevery explicitly written, it's not clear whether we can make queries based on options or requires, nor if it's doable.

Basically I would like to remove all packages which have a specific ref pattern in their requires (basically a major version of a recipe I don't want anymore in any package of my cache), and it's super tedious to manually remove (I could write a custom command, I should, but I would like to know whether it's doable with `conan remove`).

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
You can use options for package removal by adding `options.`, like so:
```
 ~/c/conan (rr/conan-inspect|✔) $ conan list "inih/*:*"
Local Cache
  inih
    inih/56
      revisions
        9f9c64ab3d9559865e604a4568674b60 (2023-04-18 15:54:42 UTC)
          packages
            76f7d863f21b130b4e6527af3b1d430f7f8edbea
              info
                settings
                  arch: armv8
                  build_type: Release
                  compiler: apple-clang
                  compiler.version: 14
                  os: Macos
                options
                  fPIC: True
                  shared: False
(venv) ~/c/conan (rr/conan-inspect|✔) $ conan remove "*:*" -p options.shared=False
Remove the package 'inih/56#9f9c64ab3d9559865e604a4568674b60:76f7d863f21b130b4e6527af3b1d430f7f8edbea#55fccbdf4e9d274779938a23d82f79ea'? (yes/no): 
```

As for requires, if you mean selecting packages based on their requirements, I don't think you can, nop.

**Comment by SpaceIm** [comment]
Thanks. Syntax is not obvious looking at https://docs.conan.io/2/reference/commands/remove.html (query syntax of options is not explained). For options you have to prepend with `options.`, but not for settings, while output of a `conan list` displays these info sub type at the same depth.

**Comment by AbrilRBS** [comment]
Good catch. I'll update the docs to better reflect the syntax
