### ISSUE TITLE
[bug] conan info --path destroys installed package

### ISSUE THREAD

**Issue by mahaase** [conan-io/conan#13725]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: -
* Conan version: 1.59.0
* Python version: 3.8.10

### Steps to reproduce

1. conan.conf with `use_always_short_paths = None` and `user_home_short = None`
2. there is a recipe with `short_path = True` 
3. `conan install <package>`: the package will be installed into long path
4. `conan info --paths <package>`: will destroy the content of package directory and create a `.conan_link` file with a broken/not existing link inside.
5. also the output of the paths are not like expected. this is maybe related somehow to https://github.com/conan-io/conan/issues/10294.

if the environment variable `CONAN_USER_HOME_SHORT=None` is set, than the `conan info --paths <package>` will work as expected.

**Comment by memsharded** [comment]
Thanks for reporting this @mahaase 

It seems there is indeed something missing there, and the conan.conf is not being propagated to the point when that is processed, and this is the reason that only the ``CONAN_USER_HOME_SHORT`` env-var works, but the conf doesn't. The ``short_paths`` in Conan 1.X is complicated, I am happy that we finally removed it in Conan 2.0.

We will try to fix it in a 1.61 release, but it might take some time, please use the env-var as workaround in the meantime.

**Comment by memsharded** [comment]
Conan 2.0 was now released 1 year ago, it seems this will no longer be prioritized, I am closing this as solved in Conan 2.0, please do not hesitate to create new tickets for any further question, thanks!
