### ISSUE TITLE
[question] CMakeToolchain generates CMAKE_SYSTEM_NAME baremetal instead of Generic?

### ISSUE THREAD

**Issue by s-mlr** [conan-io/conan#13735]
Hi everybody,

I'm running 2.0.2 and trying to cross compile for a bare metal target setting `os=baremetal`  in the respective profile. I was expecting `CMakeToolchain` to generate `CMAKE_SYSTEM_NAME` to `Generic` but it stuck with `baremetal`. Anything I'm missing or just something not considered yet?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for reporting this @s-mlr 

I have already submitted a fix for it in https://github.com/conan-io/conan/pull/13739, for next 2.0.5

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/13739, will be in 2.0.5
