### ISSUE TITLE
Rename "extension/deployers" folder

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#13734]
Hi @memsharded,
Thanks for the additional insights. Regarding "deploy" vs. "deployers", would it be possible to look in both "deployers" and "deploy" but issues a deprecation warning for any files found in the older one? Thanks

_Originally posted by @System-Arch in https://github.com/conan-io/conan/pull/13718#discussion_r1172421400_

**Comment by System-Arch** [comment]
Hi @memsharded,
Thanks for considering this suggestion. It will make all of the extension subdirectories (commands, plugins, hooks, generators, and deployers) consistent and easier to reference in documentation, etc.

**Comment by System-Arch** [comment]
Hi @memsharded,
One more suggestion in the interest of full grammatical consistency: It would be nice if the deployer argument to "conan install" was "--deployer" rather than "--deploy". This would then be parallel with the "--generator" argument. For true symmetry, it could also conceivably accept "-d" for short. Thus resulting in:

```
  -g GENERATOR, --generator GENERATOR
                            Generators to use
  -d DEPLOYER, --deployer DEPLOYER       
                            Deploy using the provided deployer to the output folder
```

compared to today's

```
  -g GENERATOR, --generator GENERATOR
                        Generators to use
  --deploy DEPLOY       Deploy using the provided deployer to the output
                        folder
```

**Comment by memsharded** [comment]
The ``--deployer`` is actually not breaking as ``argparse`` approximation allows the current ``--deploy`` as valid.

Submitted PR in https://github.com/conan-io/conan/pull/13740

**Comment by System-Arch** [comment]
Hi @memsharded ,
Thanks for the quick turnaround on this suggestion!
