### ISSUE TITLE
[question] conan 1 build_requirements not generated using CMakeDeps

### ISSUE THREAD

**Issue by forry** [conan-io/conan#13737]
### What is your question?

Hello again,
I have a recipe I'm using for `conan install` and `conan export-pkg` so no building this by conan. But when calling `conan install` with CMakeDeps there are no config files generated. Why is that? More on this below:
```python
import os
from conan import ConanFile
from conan.tools.files import copy
from conan.tools.cmake import CMakeDeps
from conans.model.version import Version

class Pdf2ImageConan(ConanFile):
    name = "pdf2image"
    license = ""
    author = ""
    url = ""
    description = "<Description of Testing here>"
    topics = ("PDF")
    settings = "os", "compiler", "build_type", "arch"
    build_policy = "never"
    
    def layout(self):
        self.folders.build = "build"

    def configure(self):
        self.options["boost"].header_only=True
    
    def build_requirements(self):
        print("~~~~build req")
        self.build_requires("pdfium/2020.9@pdf2image/prebuild")
        self.build_requires("boost/1.78.0@lexocad/prebuild")
        
    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
    
    def package_id(self):
        del self.info.settings.compiler
        del self.info.settings.build_type
    
    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        copy(self, "*.exe", os.path.join(self.build_folder,"Release"), os.path.join(self.package_folder, "bin"), keep_path=False)

```
When my cmake launches this, working dir is the -of itself:
```
conan install D:/lexocad/Pdf2Image/code -of=D:/lexocad/Pdf2Image/code/build/conan  -pr D:/lexocad/Pdf2Image/code/build/conan/conan_host_profile --build=missing --build=outdated --build=cascade --build -g CMakeDeps
```
Everything package is found in cache but no config.cmake files are generated. There is what I thing is just the relevant part of the output:
```
~~~~build req
boost/1.78.0@lexocad/prebuild: Package is up to date
pdfium/2020.9@pdf2image/prebuild: Main binary package '396fa883b47ece75049cdfa60ff83939c4390541' missing. Using compatible package 'a8b68c2e0c32f30c33866298cfc0d8263bf22fc5'
conanfile.py (pdf2image/None): Installing package
Requirements
Packages
Build requirements
    boost/1.78.0@lexocad/prebuild from 'lxdevelop' - Cache
    pdfium/2020.9@pdf2image/prebuild from local cache - Cache
Build requirements packages
    boost/1.78.0@lexocad/prebuild:524ea35a8120baabdde02483add58d81bf541327 - Cache
    pdfium/2020.9@pdf2image/prebuild:a8b68c2e0c32f30c33866298cfc0d8263bf22fc5 - Cache

Installing (downloading, building) binaries...
boost/1.78.0@lexocad/prebuild: Already installed!
pdfium/2020.9@pdf2image/prebuild: Already installed!
conanfile.py (pdf2image/None): Applying build-requirement: pdfium/2020.9@pdf2image/prebuild
conanfile.py (pdf2image/None): Applying build-requirement: boost/1.78.0@lexocad/prebuild
conanfile.py (pdf2image/None): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (pdf2image/None): Generator 'CMakeDeps' calling 'generate()'
conanfile.py (pdf2image/None): Generator txt created conanbuildinfo.txt
conanfile.py (pdf2image/None): Calling generate()
conanfile.py (pdf2image/None): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (pdf2image/None): Aggregating env generators
conanfile.py (pdf2image/None): Generated conaninfo.txt
conanfile.py (pdf2image/None): Generated graphinfo
```

It works when instead of `build_requires` I use `requires` but then they are propagated to the outside as dependencies of this standalone binary. So I thought that this is what the build_requires are for. I manage to pull this out from different random snippets in the documentation since the field `build_reqires` itself seems to be undocumented but it is in the migration guide. I'm trying to do this as an intermediate step before migrating to conan 2 in the far future.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @forry 

This is expected, because you are depending on those as ``build_requires()``.
Please check for example:
- https://docs.conan.io/1/devtools/build_requires.html
> The tool requirement was formerly named “build requirement” and has been renamed to highlight that the usage of this kind of requirement must be for “tools” exclusively, not being valid for libraries to express a “private” require or other meanings.

> tool_requires are designed for packaging tools, utilities that only run at build-time, but are not part of the final binary code. Anything that is linked into consumer packages like all type of libraries (header only, static, shared) most likely are not tool_requires but regular requires. The only exception would be testing libraries and frameworks, as long as the tests are not included in the final package.


In short, ``build_requires`` are executable, applications, not libraries.
If you are depending on libraries, and want ``CMakeDeps`` to create .cmake files so you can ``find_package()`` them and link with them, they should be regular ``requires``, not ``build_requires``.

Important: Please note that you are missing ``CMakeToolchain``, which is necessary in most cases for the correct functioning of the recipe.

**Comment by forry** [comment]
Thanks!
I have used the ("lib/1.0.0", "private") in the requires and I guess that this would need to wait until we switch to conan 2.

**Comment by memsharded** [comment]
If the issue was that the ``pdf2image`` was propagating linkage requirement down the dependency graph, to their consumers, that is true, Conan 2.0 does that better, and ``private`` workaround (beware that it also might have some rough edges) in 1.X might be good enough if it helps with your case.
