### ISSUE TITLE
[feature] Enhance the error message when settings.yml parsing fails

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#13738]
### What is your suggestion?

Hi, I would like for Conan 2.0.4 to emit a better error message when it finds an error inside the settings.yml during parsing.

At this time, I am getting the following:

```
ERROR: Invalid settings.yml format: 'list' object has no attribute 'items'
```

This is not helpful, ideally, I would like to know which line of the settings.yml caused the issue and the JSON id of the element in question.

I had 5 changes in that file and the way I had to find the culprit was to revert each diff one by one, which was unnecessarily painful (and as always, it was the last one).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your suggestion @hpe-ykoehler 

Quick question: are you aware of the ``settings_user.yml`` feature? It might be possible to not need to modify the ``settings.yml``, and just provide a new file with the modifications/additions, and it will by dynamically composed.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/13748 for next 2.0.5
