### ISSUE TITLE
[bug] self.cpp_info.builddirs has no effect when recipe uses components

### ISSUE THREAD

**Issue by ibrawada** [conan-io/conan#13733]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: msvc 2022 + v140
* Conan version: 1.59
* Python version: 3.10.10

### Steps to reproduce

1. The recipe has following package_info 
```
def package_info(self):
    self.cpp_info.set_property("cmake_file_name", "Sprout")
    self.cpp_info.builddirs.append(os.path.join("share", "sprout", "cmake", "cmake_modules"))
   # Alternatively
    self.cpp_info.builddirs = [(os.path.join("share", "sprout", "cmake", "cmake_modules"))]
  
    # Create components Sprout::<component>
    self.cpp_info.components["core"].set_property("cmake_target_name", "Sprout::core")
    self.cpp_info.components["utils"].set_property("cmake_target_name", "Sprout::utils")
 
    # Set library names in Debug and release mode
    prefix = "sprout_"
    version = self.version.replace(".", "_") if is_msvc(self) else ""
    postfix = "d" if self.settings.build_type == "Debug" else ""
    dash = "-" if self.settings.os == "Windows" else ""

    self.cpp_info.components["core"].libs = [f"{prefix}core{dash}{version}{postfix}"]
    self.cpp_info.components["utils"].libs = [f"{prefix}utils{dash}{version}{postfix}"]
```
2. The generated Sprout-<config>-x86_64-data.cmake contains the variables that should be filled with the folder path. But they are empty (Example): `set(sprout_BUILD_DIRS_DEBUG )`

3. The variable `<lib>_BUILD_DIRS_DEBUG`  is filled correctly if the recipe has no components

**Comment by memsharded** [comment]
Hi @ibrawada 

Thanks for your report.

Let me clarify a thing about the ``components``: Once ``components`` are defined, the global ``cpp_info.xxxx`` values are no longer used, they are not inherited by the components. It is possible that it might be necessary to further clarify it in the docs, but this is current expected behavior.

The approach would be to define ``builddirs`` (and other ``libdirs``, ``includedirs``, etc) in the components.

**Comment by ibrawada** [comment]
Hi @memsharded 
Thanks for the reply. 
adding:` self.cpp_info.components["cmake"].builddirs = [os.path.join("share", "sprout", "cmake", "cmake_modules")]` fixed the issue
Now its possible to use
```
find_package(Sprout)
include(sprout_some_module)
```

**Comment by memsharded** [comment]
Excellent!

Fyi, there are also some mechanisms like ``.set_property("cmake_build_modules")`` that could automatically do the ``include``. I am not a big fan of those, I prefer the explicit ``include()`` as you did, but it might be possible.

I think this ticket can be closed now? Thanks!

**Comment by ibrawada** [comment]
I have tried the `cmake_build_modules `but they were not what i needed. I will close the ticket. 
Thanks
