### ISSUE TITLE
[question] Is there a "naming convention" for conf_info?

### ISSUE THREAD

**Issue by krabbstek** [conan-io/conan#13747]
### Is there a "naming convention" for conf_info?

Hi!

I am currently looking at creating a generator (I guess consumed via python_requires) and will most likely use conf_info to configure parameters used by the generator. My question is: is there a naming convention for conf_info entries? All examples I have seen use tools.X or user.Y. Is tools.X reserved for tools distributed via conan? Am I free to use whatever name I want here, like "foo:bar"? Is there a naming convention when using conf_info? :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @krabbstek 

Thanks for your question.

The "enforced" rules are:
- ``core.xxx`` and ``tools.yyy`` are Conan built-ins, cannot be used by users.
- ``core.xxx`` can be defined in ``global.conf`` only, but not in profiles. 
- ``tools.yy`` can be defined in global.conf, profiles and cli
- ``user.zzz`` can be defined everywhere, and they are totally at the user discretion, no established naming convention yet. However this would be more or less expected:
   - For open source libraries, specially those in conancenter, ``user.libraryname:conf`` might be expected, like the ``boost`` recipe defining ``user.boost:xxxx`` conf
   - For private usage, the recommendation could be to use always ``user.teamname.library:conf``, where teamname could be company or org name, and ``library`` could be "pkg", "project" or some similar scope, or a general conf for company wide could happen with ``user.company:conf=value``

**Comment by krabbstek** [comment]
Very good explanation! One more question: is there a depth limit to the conf names? Can I use `user.aa.bb.cc.dd.ee.ff.gg:xxxx`?

**Comment by memsharded** [comment]
There is no depth, but as usual with everything we recommended in Conan: try to keep it simple. The shorter the better (without losing meaning). Same for package names, package versions, etc, etc.

**Comment by memsharded** [comment]
I am submitting the above to the docs in https://github.com/conan-io/docs/pull/3184 (it will tentatively close this question too)

**Comment by krabbstek** [comment]
Perfect, thank you very much! Have a great weekend! :)
