### ISSUE TITLE
[question] Package query on listing remotes

### ISSUE THREAD

**Issue by malonsorightware** [conan-io/conan#13744]
### What is your question?

Hi, I´ve been successfully listing all packages in Conan 2.0 for a certain query in local cache like this:
`conan list *:* -p os=Windows`

The output displays those packages that have been created for a Windows profile.

However the same command does not work if I specify a remote:
`conan list *:* -p os=Windows -r <remote_name>`

The output just displays package references, no entries for the Windows packages.

We recently upgraded our Artifactory to the latest version because we thought that the version we used did not have the backend that supported Conan 2.0 syntax. But there was no different output when we specified the remote on the list command.

Is this expected behavior or even supported?, if it is supported, what would be the right way to list the packages of a remote given a package query?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @malonsorightware 

Thanks for your question.
I think this command should be working, I have just tested ``conan list zlib/1.2.13:* -p os=Windows -r=conancenter`` and it works, returning only the Windows packages.

What output are you getting?
Are you completely sure you have those binaries in your server? You might double check by going to the Artifactory Web UI, checking the latest recipe revision folder, then packages and checking there the different ``package_id`` with their Conan properties.

**Comment by malonsorightware** [comment]
Yes, `conan list zlib/1.2.13:* -p os=Windows -r=conancenter` works successfully also on my end, returning windows packages indeed.

The output I get when I run `conan list foo/1.0.0@user/stable:* -p os=Windows  -r <remote>` is:

```
  foo
    foo/1.0.0@user/stable
      revisions
        6e1689a525e390abc56f0ba5f711f890 (2023-04-06 09:37:03 UTC)
          packages
```

I checked in the Artifactory Web UI that there is at least one package (ID: 7ce0083792ac7b45c456feaed60f5ef22829fdda) with Windows configuration:

```
OS: | Windows
Architecture: | x86_64
Build Type: | Debug
Compiler: | msvc
Compiler Version: | 192
Compiler Runtime: | dynamic
Compiler.runtime_type: | Debug
Compiler.cppstd: | 14
```

So I removed any foo package from local cache and I installed foo package again from the remote with one of our Windows profiles with the command `conan install --requires foo/1.0.0@user/stable -pr win64_vs2019_debug -r <remote>`

And then I ran `conan list foo/1.0.0@user/stable:* -p os=Windows`  and the output is:

```
Local Cache
  foo
    foo/1.0.0@user/stable
      revisions
        6e1689a525e390abc56f0ba5f711f890 (2023-04-06 09:37:03 UTC)
          packages
            7ce0083792ac7b45c456feaed60f5ef22829fdda
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: msvc
                  compiler.cppstd: 14
                  compiler.runtime: dynamic
                  compiler.runtime_type: Debug
                  compiler.version: 192
                  os: Windows
```
               
The previous version of Artifactory we used would not display anything in "Package Info" tab, but current version does, which is why I think it supports Conan 2.0 syntax. The repository and the packages were not modified in the migration to the new Artifactory version, so I can only think about cached data in some database that lives in the remote repo and it is already obsolete or has not been initialized, hence it does not contain any reliable data or no data at all.

**Comment by malonsorightware** [comment]
Ok, created a test package with a Windows profile and uploaded it to the same repo. It seems that there is, indeed, a database that was updated with this last addition and the query on the remote ran successfully this time.

**Comment by memsharded** [comment]
I see, it seems the migration to the newer Artifactory version might not have taken into account to re-index previously existing packages that had problems due to that bug. Maybe firing a re-index in the server will fix it. (But probably just re-uploading things is enough)

**Comment by malonsorightware** [comment]
Thanks for the answers by the way!, I thought I would need to re-upload stuff indeed. Would it make sense to mention this in Conan 2.0 migration?

**Comment by memsharded** [comment]
It is not specific to the Conan client migration, but to the server side, and specific for Artifactory.
We have pending some improvements to the Artifactory docs, that will summarize these things, hopefully that helps.

It seems that there is not much more to do on our side here in the Conan client then, might we close this issue? Thanks!
