### ISSUE TITLE
Consider USER_HOME or storage_path config in profiles

### ISSUE THREAD

**Issue by cleeland** [conan-io/conan#1374]
The documentation leads me to believe that a profile is just a specialized conan.conf file, but neither the code nor the behavior seems to be support that.  Are they the *supposed* to be the same?

**Comment by memsharded** [comment]
Hi!
No, they are not supposed to be the same. Profiles are more powerful, and have very distinct features to conan.conf:

- There can be multiple profiles, each one with different configuration of compiler, version, etc
- Profiles are intended to be shared. They are text files that can be put inside the repository
- Profiles have build_requires, which many times make sense only per-project, not per installation of conan.
- Profile also have ``options``, which only makes sense for specific projects.

On the other hand conan.conf has "global" configuration for the user/system:

- If using proxies
- The user preferred compiler and version, to avoid typing them even for simple examples. The ``settings_defaults``
- The storage of the local cache, where to put the packages.
- conan.conf is not intended to be shared. You can enable tracing, or the necessity of sudo, or the number of CPUs to be used, things that change from machine to machine.

**Comment by cleeland** [comment]
Thanks for the quick answer.  I'm curious as to the rationale for not having the cache location configurable in the profile.  In many cases, I want the project's dependencies to be resident under the project's workspace (or maybe under its "build" tree).

**Comment by memsharded** [comment]
There is no specific rationale, simply it has not been requested before. I don't know if it would be complex or not, should study it. 
In any case, why would you like to populate just the user directory, wasting extra space, and requiring re-building (waste of time too), when the same package (for the same configuration) is required from a different project? The good thing about having a common cache is saving lots of time and space.
What we had so far is the ``CONAN_USER_HOME`` variable that it is used to have fully independent environments, not only the package data storage, which is the best for CI. 
If you think this is a wanted feature, please submit a specific issue for it, and we will analyze it :)

**Comment by cleeland** [comment]
I am working to transition an existing monolithic repository to using conan; is part of the strategy to eventually break the monolithic repository into more manageable chunks.  Putting libraries into the workspace for the repository more closely models what currently exists, and so would provide a simpler evolutionary step.

Common caches are good and I plan to utilize them, but even in that case, the common cache would *not* reside in the user's home directory.  In that case it would make far more sense for the common cache to reside in a space that is common to all users rather than a single user.

As you pointed out, CI is another reason I want the storage to be in a location that is not a user's home directory.  I can utilize `CONAN_USER_HOME` as you suggest, but if I'm going to have a profile anyway I would prefer to minimize the "surface area" contact between CI and conan (or anything else, for that matter).

**Comment by memsharded** [comment]
>In that case it would make far more sense for the common cache to reside in a space that is common to all users rather than a single user.

When we decided about the default setup, we took some important security feedback under consideration: if you have cache per user, not per system, you can manage security more easily. If a certain user is not allowed to read/retrieve some package, that is fine. If a cache per system is used, there is no possible control of access to restricted code and binaries. 

So maybe we can consider the feature request of having the "storage" path configurable in profiles. I don't know if it will be possible, but lets have a look.

**Comment by cleeland** [comment]
> If a certain user is not allowed to read/retrieve some package, that is fine. If a cache per system is used, there is no possible control of access to restricted code and binaries.

Ah, good point.  I had not considered security at this level.  In my mind, for a shared cache I would punt the task of access control to whatever was being used to manage the cache (e.g., filesystem permissions/ACLs).  You could support this by offering configurability of a command to run on the downloaded/built items (e.g., `chmod` or `chattr`, etc.) after landing in the storage path. This would be more flexible than just using umask or similar.

**Comment by memsharded** [comment]
Yes, but the complexity of adding different permissions to the storage, for many different storage file systems, is definitely not worth it. Dealing with that kind of stuff for multiple OS takes much more time than expected, and having separate caches per user and the configurability of CONAN_USER_HOME is working fantastic-ly. 
I am still analyzing the use case for configuring a different path for the "data" storage in the profiles, and I see more problems than advantages. For example, for every package, conan tracks its remote origin in a file called ``registry.txt`` that lives in the local cache. The ``settings.yml`` might also be configured for different projects (that file also lives in the local cache). So you either point the full CONAN_USER_HOME to define the location of the complete cache per project, or you use the standard shared one, but just redirecting the package storage without redirecting the whole cache doesn't make sense, as the package data is meaningless without the other cache configuration files.

I think that you have a different underlying need, that is not related to the local conan cache. Please have a look to: https://github.com/conan-io/conan/issues/1377. We are considering adding functionality that would allow local edition of packages, without being linked from the local cache, but directly in user space. It is still early, but I'd say that could be what you are looking for. If so, maybe this issue could be closed and continue conversation there.

**Comment by cleeland** [comment]
It might be useful for me to discuss the workflow in which I'm trying to insert conan with you.  Is this the appropriate forum for that?

**Comment by memsharded** [comment]
I think it might be more productive to jump onto chat for discussing this. Please write an email to info@conan.io with details (such as your timezone). Thanks!

**Comment by memsharded** [comment]
Conan 2.0 has added a .conanrc file with a variable that can define CONAN_HOME, to configure the home per project, setting the home in profiles didn't look the right approach

Also, packages can be edited now directly in user space with ``editables`` no need to put them in the cache.

Closing as inactive.
