### ISSUE TITLE
vcvars_command incorrect if directory ~/Source exists.

### ISSUE THREAD

**Issue by barcharcraz** [conan-io/conan#1375]
vcvars_command returns a command with the incorrect effect for VS2017 if the user has a directory called "Source" in their home directory (their user profile dir). This is because of a hardcoded path in vsdevcmd_end. Perhaps conan should return a command that sets VSCMD_START_DIR to the build directory before invoking vsdevcmd_end.

Not sure if this is conan's responsibility unless this "feature" was present in the old command setup scripts as well. Perhaps there's still time for msft to get rid of this rather interesting choice of undocumented behavior.

**Comment by memsharded** [comment]
Yes, it looks like more like a msft responsibility. But in any case, could you please detail a bit more with examples, what are the outputs (the current one, the current with the Source dir, the expected one...). If there is something simple that can be added to ``vcvars_command`` that might ease some users life, we might consider adding it.

**Comment by barcharcraz** [comment]
Basically if ~/source exists then vcvarsall.bat will switch to it after adding all the msvc env vars. If it does not then it will return to the directory that was current when it was invoked. If you set the env var VSCMD_START_DIR then it will change to that directory no matter what.

**Comment by memsharded** [comment]
Ok, I think I more or less got it.
Maybe it shouldn't be implemented in ``vcvars_command`` the responsibility of that function is just to return a string (no side effects). The one actually calling things is 

```python
def msvc_build_command(settings, sln_path, targets=None, upgrade_project=True, build_type=None,
                       arch=None):
    vcvars = vcvars_command(settings)
    build = build_sln_command(settings, sln_path, targets, upgrade_project, build_type, arch)
    command = "%s && %s" % (vcvars, build)
    return command
```
Probably setting that environment variable VSCOMD_START_DIR, maybe pointing the the CWD, should be done in that method. What do you think?

In any case, very annoying behavior of that VS script.

**Comment by barcharcraz** [comment]
Well I use vcvars command for nmake based builds and it's a problem even
there

**Comment by memsharded** [comment]
That is very unlucky... The thing is that I think we cannot introduce side effects into the ``vcvars_command`` function, it is also used in ``conan-package-tools``, in a different context, so setting ``VSCOMD_START_DIR`` pointing to the CWD might have very unwanted results.

I think maybe the solution could be to make it explicit in the recipe, something like:

````python
def build(self):
    with self.environment_append({"VSCOMD_START_DIR": os.getcwd()}):
          vccmd = vcvars_command(self.settings)
          self.run("nmake ....")
```
Just an idea, I certainly don't know which could be the best workaround to this...

**Comment by memsharded** [comment]
obsoleted tools, new ones in https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html
