### ISSUE TITLE
[question] How to avoid having duplicate dev tool binaries in local cache?

### ISSUE THREAD

**Issue by jputcu** [conan-io/conan#13756]
### What is your question?

I have written a conan package, https://github.com/jputcu/avr_conan/blob/master/toolchain/conanfile.py, to package a cross compiler.
It works, but I notice the binaries are duplicated in my cache: A build folder and a full copy in the package folder. This is rather expensive because I now have 2x160Mb.
I've tested this with `conan-1` and `conan-2`, on both Linux and Windows.
Is it possible to avoid this, e.g. by unpacking directly in the package folder?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jputcu 

Thanks for your question.
If you are packaging some pre-built binaries, there are 2 alternatives:
- it is possible to use the ``conan export-pkg`` command, to package directly those binaries into the package, but if you pre-download yourself and put the binary besides the ``conanfile.py``. If you like automating the download in the recipe probably not a good approach.
- Disk space is cheap, you can let it use double the space, and then use from time to time the ``conan cache clean`` command to remove the build (and other) temporary folders.

**Comment by jputcu** [comment]
Hello, thank you for the fast response.
Is it perhaps possible to do the download and extract in the package method instead?

**Comment by memsharded** [comment]
> Is it perhaps possible to do the download and extract in the package method instead?

Yes, doesn't read very clean, but it might work. 
I think I'd still go for the ``build()`` + ``package()`` approach, because it is more standard and known pattern. Saving a few disk megabytes temporarily might not be worth it, many packages that are being built from sources takes huge disk space compared with the final package, and ``conan cache clean`` or similar are still necessary from time to time to free some space.

**Comment by jputcu** [comment]
Although I'm in favor of keeping things small to start with, I can relate to big source builds also taking up a lot of space.
Thanks for the response!
