### ISSUE TITLE
[question] How to correctly resolve version conflicts?

### ISSUE THREAD

**Issue by Jean1995** [conan-io/conan#13760]
### What is your question?

Hi! For an open source project I am using, I am currently working on a PR to allow them to move forward from conan1.x to conan2, which they use to consume dependencies.

In the process, a massive amount of version conflicts (including boost, openssl, and other packages) occured. I guess the default behavior of conan has changed?

I am (partly) able to resolve most of them using `force` or `overwrite`. However, looking into [the tutorial](https://docs.conan.io/2/tutorial/versioning/conflicts.html), it says:

> Resolving version conflicts by overrides/forces should in general be the exception and avoided when possible, applied as a temporary workaround. The real solution is to move forward the dependencies requires so they naturally converge to the same versions of upstream dependencies.

Unfortunately, I am unable to find any additional documentation/examples/references on how I should do that. What does "move forward the dependency requires" mean? Could you point me to documentation/references for best-practices on how to proceed? 🙂  

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @Jean1995 thanks for your question, I can give you a bit of context into your issue and how to maybe proceed, but I don't think there's much more written in the docs dealing with version conflict reasolution.

> "move forward the dependency requires"

By this the docs mean to try to bump the versions of your dependencies to the latest one the library supports. Once that is done, most version conflicts should _hopefully_ be resolved. If any remain, check if (I'm asssuming you're using conancenter) a PR is already open to address the issue, or open an issue with the conflict if not.

If all else fails, that's the moment you might think about using the overrides/force flags

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you, feel free to reopen/create new issues should you have additional questions, thanks! :)
