### ISSUE TITLE
[question]  how to share built packaged using gitlab package registry

### ISSUE THREAD

**Issue by kismetro** [conan-io/conan#13765]
### What is your question?

Hi,

I have changed conan verion from 1.X to 2.X to resolve version conflict.
CMake based build, compile and running of project has been done also.

To distribue conan packages for my co-workers, I had used "conan upload" to gitlab package registry using 1.x.

But after changing conan version 2,  I got error as below:
'''
ERROR: The remote doesn't support revisions. Conan 2.0 is no longer compatible with remotes that don't accept revisions..
'''

It seems that conan 2.x doesn`t support gitlab package registry, right?

Is there any solution - package sharing with gilab package registry ?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @kismetro thanks a lot for your question.
GitLab's integration with Conan is tracked in https://gitlab.com/groups/gitlab-org/-/epics/6816 and from there (Specifically https://gitlab.com/gitlab-org/gitlab/-/issues/348228) we can see that v2 support hasn't been finalized yet :)

**Comment by kismetro** [comment]
I checked that epic. Thanx!
