### ISSUE TITLE
CMake can not find POCO

### ISSUE THREAD

**Issue by Vildnex** [conan-io/conan#13773]
### What is your question?

I downloaded the last version of Conan from [here][1] and then I've done the following.

1. creating a new C++ project with the following

**main.cpp**

     #include "Poco/MD5Engine.h"
     #include "Poco/DigestStream.h"
    
     #include <iostream>
    
     int main(int argc, char** argv)
     {
         Poco::MD5Engine md5;
         Poco::DigestOutputStream ds(md5);
         ds << "abcdefghijklmnopqrstuvwxyz";
         ds.close();
         std::cout << Poco::DigestEngine::digestToHex(md5.digest()) << std::endl;
         return 0;
     }

**CMakeList.txt**

    cmake_minimum_required(VERSION 3.25)
    project(TestMailPrj)
    
    set(CMAKE_CXX_STANDARD 20)
    
    find_package(poco REQUIRED)
    
    add_executable(TestMailPrj main.cpp)
    target_link_libraries(${PROJECT_NAME} POCO)

**conanfile.txt**

    [requires]
    cmake/3.25.3
    poco/1.12.4
    
    [generators]
    CMakeDeps
    CMakeToolchain

2. run the following command: `conan install . --output-folder=build --build=missing`

Now, even if my all dependencies were installed properly, in CMakeFile it can not find my poco library.

    By not providing "Findpoco.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "poco", but CMake did not find one.
    Could not find a package configuration file provided by "poco" with any of the following names:
      pocoConfig.cmake
      poco-config.cmake
    Add the installation prefix of "poco" to CMAKE_PREFIX_PATH or set "poco_DIR" to a directory containing one of the above files. If "poco" provides a separate development package or SDK, be sure it has been installed.

Dose anyone knows what exactly I am doing wrong or this is a bug? 

  [1]: https://conan.io/downloads.html

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @Vildnex,

Thanks for the question. I think there could be a casing problem there in the _CMakeLists.txt_. It should be `Poco`, not `poco`:

```
find_package(Poco REQUIRED)
```

Could you check?

**Comment by Vildnex** [comment]
I've tried it with all the combination, Poco, poco and POCO and is always the same result.

**Comment by czoido** [comment]
> I've tried it with all the combination, Poco, poco and POCO and is always the same result.

I think the target name may also be not correct, please try:

```
target_link_libraries(${PROJECT_NAME} Poco::Poco)
```

**Comment by Vildnex** [comment]
This is the CMakeList with the changes:
```
cmake_minimum_required(VERSION 3.22)
project(TestMailPrj)

set(CMAKE_CXX_STANDARD 20)

#find_package(Poco REQUIRED Foundation Net Util)
find_package(Poco REQUIRED)

add_executable(TestMailPrj main.cpp)
#target_link_libraries(${PROJECT_NAME} Poco::Foundation Poco::Net Poco::Util)
target_link_libraries(${PROJECT_NAME} Poco::Poco)

```

And this is the output file:
```

CMake Error at CMakeLists.txt:7 (find_package):
  By not providing "FindPoco.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Poco", but
  CMake did not find one.

  Could not find a package configuration file provided by "Poco" with any of
  the following names:

    PocoConfig.cmake
    poco-config.cmake

  Add the installation prefix of "Poco" to CMAKE_PREFIX_PATH or set
  "Poco_DIR" to a directory containing one of the above files.  If "Poco"
  provides a separate development package or SDK, be sure it has been
  installed.

```

Is the same every time :(

**Comment by Vildnex** [comment]
Do I have to do something to tell the CMake where should it look for the conan packages?

**Comment by czoido** [comment]
Yes, after doing the `conan install . --output-folder=build --build=missing` you should do something like this:

```
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
cmake --build .
```

Does that work for you?

You can check the tutorial section in the docs for more information on how to start using Conan: https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html

**Comment by Vildnex** [comment]
I've tried this and interestingly enough... I don't have an error on the CMake now, and everything is running fine, but when I am running the main.cpp it still dose not find my package...
```
fatal error: Poco/Net/MailMessage.h: No such file or directory
    1 | #include <Poco/Net/MailMessage.h>
```

**Comment by Vildnex** [comment]
also, I've checked the tutorial page but is not helping me... because everything works fine if I am fallowing that example, but not when I am using poco.

**Comment by czoido** [comment]
Hi @Vildnex,
I made an example here: https://github.com/czoido/conan-issue-13773 
Could you try to follow those steps and provide the output in case something does not work?
Also, please check another change I made to the _conanfile.txt_, you were including `cmake/3.25.3` in the `requires` section but it should be under `tool_requires` (although this may not be the problem, but that's the correct syntax)

**Comment by Vildnex** [comment]
Thank you for your effort :). I did all the steps as you said in the repository and everything works properly now :D.
But I have 2 questions if you can explain to me...

1. why exactly do you need to do `source conanbuild.sh` I didn't see this part in the tutorial section, or I missed it.
2. even if it compiles, my CLion is not able to see any of the Poco libraries. Form it the whole library does not exist even if the project compiles. This has something to do with conanbuild.sh?

**Comment by czoido** [comment]
I'm glad to hear that! 
- The `conanbuild.sh` part is explained here: https://docs.conan.io/2/tutorial/consuming_packages/use_tools_as_conan_packages.html that is how you add the conan installed version of CMake to the path. All the packages added as tool_requires will have the information in the `conanbuild.sh`. 
- About the CLion problem, that's probably about the expected layout for the files, you could probably customize the layout to make it work, check the layout() section here (it will also mean the you have to use a conanfile.py instead a conanfile.txt): https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html
Anyway, I'll try to do some tests with CLion and ping you back.

**Comment by Vildnex** [comment]
I see, now I get it. Thanks you very much for your help :D
