### ISSUE TITLE
[bug] Server 500 error when conanfile has many authors

### ISSUE THREAD

**Issue by gabeblack** [conan-io/conan#13776]
### Environment details

Running `conan 2.0.3` and uploading to `artifactory`, if the `conanfile.py` has an `authors` attribute with many authors (e.g., the result from querying the authors of the `nginx` rpm package via the `rpmfile` package in python), and the authors have unicode characters in their names, then the initial attempt to upload the package to artifactory will fail with `Error uploading file: conanfile.py, '500 Server Error:  for url: ...`. The second attempt will succeed. I thought perhaps it might be unicode characters or the length of the attribute. 

To test if it was the length, I made "author" a long string of generic emails "name1@example.com, name2@example.com, ..." but the error did not reproduce. 

To test if it was something about the contents of the email list (e.g., unicode characters), I tried binary dissecting the list (cutting half of it out) but the error did not reproduce. 

So then I combined the two methods, replacing emails but trying to preserve the length of the authors string. Eventually I got to a list of generic emails with a single unicode email somewhere in the middle (well near the end). So kind of a weird bug and not sure what would be causing it. Below is an email list that will reproduce the error if you add it to your conanfile.py:

`   author = """name193@example.com, name194@example.com, name195@example.com,name116@example.com, name117@example.com, name118@example.com, name119@example.com, name120@example.com, name121@example.com, name122@example.com, name123@example.com, name124@example.com, name125@example.com, name126@example.com, name127@example.com, name128@example.com, name129@example.com, name130@example.com, name131@example.com, name132@example.com, name133@example.com, name134@example.com, name135@example.com, name136@example.com, name137@example.com, name138@example.com, name139@example.com, name140@example.com, name141@example.com, name142@example.com, name143@example.com, name144@example.com, name145@example.com, name146@example.com, name147@example.com, name148@example.com, name149@example.com, name150@example.com, name151@example.com, name152@example.com, name153@example.com, name154@example.com, name155@example.com, name156@example.com, name157@example.com, name158@example.com, name159@example.com, name160@example.com, name161@example.com, name162@example.com, name163@example.com, name164@example.com,name165@example.com, name166@example.com, name167@example.com, name168@example.com, name169@example.com, name170@example.com, name171@example.com, name172@example.com, name173@example.com, name174@example.com, name175@example.com, name176@example.com, name177@example.com, name178@example.com, name179@example.com, name180@example.com, name181@example.com, name182@example.com, name183@example.com, name184@example.com, name185@example.com, name186@example.com, name187@example.com, name188@example.com, name189@example.com, name190@example.com, name191@example.com, name192@example.com, name193@example.com, name194@example.com, name195@example.com, name196@example.com, name197@example.com, name198@example.com, name199@example.com, name0@example.com, name1@example.com, name2@example.com, name3@example.com, name4@example.com, name5@example.com, name6@example.com, name7@example.com, name8@example.com, name9@example.com, name10@example.com, name11@example.com, name12@example.com, name13@example.com, name14@example.com, name15@example.com, name16@example.com, name17@example.com, name18@example.com, name19@example.com, name20@example.com, name21@example.com, name22@example.com, name23@example.com, name24@example.com, name25@example.com,name98@example.com, name99@example.com, name100@example.com, name101@example.com, name102@example.com, name103@example.com, name104@example.com, name105@example.com, name106@example.com, name107@example.com, name108@example.com, name109@example.com, name110@example.com, name111@example.com, name112@example.com, name113@example.com, name114@example.com, name115@example.com, name116@example.com, name117@example.com, name118@example.com, name119@example.com, name120@example.com, name121@example.com, name122@example.com, name123@example.com, name124@example.com, name125@example.com, name126@example.com, name127@example.com,name177@example.com, name178@example.com, name179@example.com, name180@example.com, name181@example.com, name182@example.com, name183@example.com, name184@example.com, name185@example.com, name186@example.com, name187@example.com,name5@example.com, name6@example.com, name7@example.com, name8@example.com, name9@example.com, name10@example.com, name11@example.com, name12@example.com, name13@example.com, name14@example.com, name15@example.com, name16@example.com,name101@example.com, name102@example.com, name103@example.com, name104@example.com, name105@example.com, name106@example.com,Marcela Mašláňová <mmaslano@redhat.com> - 1.0.0-2,name138@example.com, name139@example.com, name140@example.com, name141@example.com, name142@example.com, name143@example.com, name144@example.com, name145@example.com, name146@example.com, name147@example.com, name148@example.com, name149@example.com, name150@example.com, name151@example.com, name152@example.com, name153@example.com, name154@example.com, name155@example.com, name156@example.com, name157@example.com, name158@example.com, name159@example.com, name160@example.com, name161@example.com, name162@example.com, name163@example.com"""`

### Steps to reproduce

add the "authors" attribute to your conanfile.py described in the description above.

Build the package: `conan create .`
Upload to artifactory: `conan upload <pkg> -r artifactory --confirm`

The first attempt should yield a server 500 error.

Second attempt will likely succeed.

### Logs

I don't have access to our company's server logs for artifactory but I have opened a ticket with them to see if they can see anything relevant.

**Comment by memsharded** [comment]
Thanks for your report @gabeblack 

Some quick feedback regarding this ticket: the ``authors`` attribute was never intended to store the authors information of the library itself. It was intended to store the author of the recipe, that is, the folk/folks that need to be reached out (if any) that maintains the recipe, if something needs to be fixed. Or the reviewer of the PR that you can submit to change something to that package recipe.

We will try to investigate this in the server side, but my strong recommendation would be to keep things as simple as possible, including this ``authors`` recipe field to contain only just a very few (1-3) recipe authors.

**Comment by gabeblack** [comment]
Ok, that's good to know. I can change our recipes to do just that then. This report then is very low priority. I'm going to close it as I think it isn't worth the effort investigating

**Comment by memsharded** [comment]
Yes, I think it makes sense, not enough priority atm. Thanks very much!
