### ISSUE TITLE
[bug] conan config: error: argument subcommand: invalid choice: 'init'

### ISSUE THREAD

**Issue by Havelet** [conan-io/conan#13784]
### Environment details

* Operating System+version: Linux version 5.4.0-117-generic (buildd@lcy02-amd64-006) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #132-Ubuntu SMP
* Compiler+version:  Gradle 7.5.1
Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Linux 5.4.0-117-generic amd64
* Conan version: Conan version 1.8.0
* Python version:  Python 3.8.10

### Steps to reproduce

git clone https://github.com/conan-io/conan.git -b relelase/1.8.0
python -m pip install -e .
export PATH=~/.local/bin:$PATH

### Logs

> Configure project :alexa-auto-apl-renderer:apl-render
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :aacs
Building AACS library
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :alexa-auto-app
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Task :aacs:buildDeps FAILED
WARN: Migration: This conan installation doesn't have settings yet
WARN: Nothing to migrate here, settings will be generated automatically
ERROR: Exiting with code: 2
usage: conan config [-h] {rm,set,get,install} ...
conan config: error: argument subcommand: invalid choice: 'init' (choose from 'rm', 'set', 'get', 'install')

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/hanbo.zhang/workspace/alexa-auto-sdk/aacs/android/service/core-service/build.gradle' line: 273

* What went wrong:
Execution failed for task ':aacs:buildDeps'.
> Process 'command 'conan'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
1 actionable task: 1 executed

**Comment by Havelet** [comment]
I checked version 1.44.1 which support 'conan config init" command

**Comment by czoido** [comment]
Hi @Havelet,

Thanks for the question. Yes, the problem looks like that you are using an outdated Conan version. Installing a newer version might help resolve your issue. Here are some guidelines on building the Alexa Auto SDK and they recommend to use at least 1.45: https://alexa.github.io/alexa-auto-sdk/docs/native/building/#general-build-requirements.

I'm closing this issue as it's not related to any problems with the Conan client itself, but to an incorrect version but please feel free to open new issues if you have any specific questions about Conan.

**Comment by Havelet** [comment]
Many thanks for your support!
