### ISSUE TITLE
Update single dependency in lockfile

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#13787]
Conan: 1.58
OS: Ubuntu 22.04 WSL

I have a conanfile.py.
This conanfile has a set of dependencies defined in `def requirements(self)`.
Among those are sqlite3/3.35.4.
I have generated a lockfile (current.lock) for the conanfile and its dependencies. 
Using this lockfile works perfect.

Now I would like to upgrade the sqlite3 dependency to a new version...so I update my conanfile.py

In order to create a new lockfile with the updated sqlite3 dependency based on the existing lockfile....then what command should I issue?

I tried:
`conan lock create conanfile.py --lockfile current.lock --lockfile-out new.lock --build sqlite3`
But this command uses the old sqlite3 version lock in current.lock. Which is as expected.

I can also create an entirely new lockfile not based on the current lockfile, but I am reluctant to do so as I would like to ensure that only that one sqlite3 package is updated.

What to do?

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by klausholstjacobsen** [comment]
Found this: https://github.com/conan-io/conan/issues/12582
I guess that is the answer?

**Comment by memsharded** [comment]
Yes, exactly. 

Evolving a Conan 1.X lockfile, to update to new versions is one of the really challenging problems that motivated us to go for a new design from scratch for 2.0 lockfiles. 
If I had to do this somehow for 1.X, I'd try something like:
- Start from a clean cache, defining a temp CONAN_USER_HOME
- Install the dependencies there with the old lockfile
- Install the new version package
- Now create a new lockfile, using that cache (not updating from server). This will resolve things from the cache, so it will stay as close as possible to the versions in the lockfile, as they are the only ones in the cache, but will resolve also to the updated one too.

**Comment by klausholstjacobsen** [comment]
That is exactly what I did!

Thanks for your ultra quick response.....as always!

**Comment by memsharded** [comment]
Happy to help! :)
