### ISSUE TITLE
[question] Define install_folder within conanfile.py

### ISSUE THREAD

**Issue by Liastre** [conan-io/conan#13790]
### What is your question?

Good day,

Currently I'm using `-if` flag within `install` command to set-up genarator output folder, like conanbuildinfo.props file. I was about to move this setting inside `conanfile.py`, I've found that we got new `self.folders` properties within `layout()` step. Unfortunately, I've tried everything to make it working, including changing `self.install_folder`. Nothing make any effect, conan keep generating those files in the same directory with `conanfile.py`.

I'm really struggling with it for week, I don't understand why it's not working, moreover, when I'm changing specific `self.cpp.source` and `self.cpp.build` it works pretty well. Maybe there some issues in my conan configurations, I don't know...

Current file I'm using:
```
from conans import ConanFile, CMake, MSBuild


class CurlConan(ConanFile):
    name = "curl"
    version = "7.81.0"
    description = "<Description of Curl here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}
    generators = "cmake", "visual_studio"
    exports_sources = "*", "!tmp*", "!*DerivedData*", "!tests/cache*", "!*/.vs/*", "!*/Binary/*", "!*/Generated Files/*", "!*/win/x64/*", "!*/win/win32/*", "!*/win/packages/*", "!tmp_cache/*", "!.conan/*"

    def requirements(self):
        self.requires("openssl/1.1.1t")

    def config_options(self):
        if self.settings.os == "Windows" or self.settings.os == "WindowsStore":
            del self.options.fPIC

    def layout(self):
        self.folders.build = ".\\ConanConfig"
        self.folders.install = ".\\ConanConfig"

        self.cpp.source.includedirs = ["include"]
        build_type = str(self.settings.build_type)
        build_platform = str(self.settings.arch)
        if self.settings.os == "Windows" or self.settings.os == "WindowsStore":
            build_platform = "Win32" if build_platform == "x86" else "x64"
            lib_dir = "Binary\{}\{}\{}".format(build_platform,build_type, self.name)
            self.cpp.build.libdirs = [lib_dir]

    def build(self):
        if self.settings.os == "Windows" or self.settings.os == "WindowsStore":
            msbuild = MSBuild(self)
            msbuild.build("build/VS2019_UWP/Curl/Curl.sln", upgrade_project=False)
        else:
            cmake = CMake(self)
            
            if self.settings.os == "Macos":
                cmake.definitions["CMAKE_OSX_ARCHITECTURES"] = "arm64;x86_64"
                cmake.definitions["OPENSSL_ROOT_DIR"] = "./ThirdParty/openssl/macos"

            cmake.definitions["CURL_DISABLE_LDAP"] = True
            cmake.definitions["CURL_USE_LIBSSH2"] = False
            cmake.definitions["CURL_STATICLIB"] = True

            if self.settings.os == "iOS":
                cmake.definitions["HAVE_LIBSOCKET"] = False

            if self.settings.os == "Android":
                cmake.configure(source_folder="Android")
            else:                 
                cmake.configure()
            cmake.build()

    def package(self):
        self.copy("*.h", dst="include/curl", src="include/curl")
        self.copy("*curl*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.dylib*", dst="lib", keep_path=False)
        self.copy("*curl*.so", dst="lib", keep_path=False)
        self.copy("*curl*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["Curl"]
```

## Environment
Conan version: 1.59.0
OS: Windows 10 Version	10.0.19044 Build 19044

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Liastre 

Thanks for your question.

First a clarification: ``from conans import CMake, MSBuild`` are the legacy helpers, not the new ones ``from conan.tools.cmake import CMake``, and ``from conan.tools.microsoft import MSBuild`` (see https://docs.conan.io/1/reference/conanfile/tools.html). The legacy generators and helpers, not from ``from conan.xxx`` will not fully follow the ``layout()`` definition. Same for ``generators = "cmake", "visual_studio"``, those are legacy. Only the new helpers and generators do follow ``layout()``. Furthermore those helpers and generators have already been removed in 2.0, it is necessary to use the new ones in order to be ready for 2.0.

Regarding your question, it is not very clear what you want to achieve. The CMake install operation in Conan is only used for packaging into a Conan package, and Conan defines what needs to be defined. The ``--install-folder`` has also been removed in 2.0 and ``self.folders.install`` doesn't exist. Could you please elaborate what problem are you trying to solve and what you want to achieve? Thanks.

**Comment by Liastre** [comment]
Hello @memsharded,

Thank a lot, that's very helpful. I was not aware that helpers imports and generators are changed. Will do some research on it.

As for my target, I want to achieve that `.props` files are generated during configuration was placed not in root folder, along with `conanfile.py`, but in a separate folder - unique for each configuration. Currently we achieve that through `--install-folder`.

**Comment by memsharded** [comment]
Thanks for the clarification.
For your goal you should be checking:
- Using a ``layout()`` method
- The ``vs_layout()`` could help, you can use a ``conan new msbuild_lib -d name=pkg -d version=0.1`` to get a new MSBuild working project

Quick question: as the existing .vcxproj should have the path to the generated files, how do you manage to provide those paths if you generated them in different folders, only defined at command line? The importance of ``layout()`` is that it can provide a consistent location of generated files, so everything works out of the box.

**Comment by Liastre** [comment]
I've managed to make it work, thank you @memsharded. Now I'm using proper imports:
```
from conan import ConanFile
from conan.tools.cmake import CMake
from conan.tools.microsoft import MSBuild, MSBuildDeps
```

And my layout and generation step looks like that:
```
    def layout(self):
        self.folders.generators = ".\\ConanConfig"

    def generate(self):
        if self.settings.os == "Windows" or self.settings.os == "WindowsStore":
            ms = MSBuildDeps(self)
            ms.generate()
```

As for your question, yes, you're correct there will be new path for each configuration, and .vcxproj must know where it's placed. Since we are building few configurations simultaneously, we need `.prop` files to be placed in different directories. For this purpose I'm using project defines, so our path within project file looks like `$(ProjectDir)$(Configuration)\$(Platform)\conan\` which translates to `MyProjectPath\Debug\x64\conan` for example. Our CI always know for which configuration and platform we are building.

**Comment by memsharded** [comment]
Great, thanks for the feedback!
