### ISSUE TITLE
[bug] default profile uses mismatching stdlibc++ version

### ISSUE THREAD

**Issue by Enhex** [conan-io/conan#13791]
### Environment details

* Operating System+version: Ubuntu 22.10
* Compiler+version: GCC 12.2
* Conan version: 1.59.0
* Python version: 3.10.7

currently Conan generates a broken default profile.
it can use the detected compiler version to set `compiler.libcxx` to the compiler's default,
so things work out of the box instead of sending new users down a debugging rabbit hole.

**Comment by memsharded** [comment]
Conan 2.0 will detect ``libcxx=libstdc++11`` already.

The default detection in Conan 1.X detects ``libcxx=libstdc++`` because that cannot be changed, it would be breaking behavior according to the 1.0 defined stability commitment.

New users will be warned with:
```
************************* WARNING: GCC OLD ABI COMPATIBILITY ***************************
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the {profile} profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 {profile}

Or edit '{profile_path}' and set compiler.libcxx=libstdc++11
********************************************************************************
```

The getting started docs https://docs.conan.io/1/getting_started.html for new users read, in a clearly highlighted green box:
```
**Important**

If you are using GCC compiler >= 5.1, Conan will set the compiler.libcxx to the old ABI for backwards compatibility.
 In the context of this getting started example, this is a bad choice though: Recent gcc versions will compile the
 example by default with the new ABI and linking will fail without further customization of your cmake configuration.
 You can avoid this with the following commands:

$ conan profile new default --detect  # Generates default profile detecting GCC and sets old ABI
$ conan profile update settings.compiler.libcxx=libstdc++11 default  # Sets libcxx to C++11 ABI

You will find more information in [How to manage the GCC >= 5 ABI](https://docs.conan.io/1/howtos/manage_gcc_abi.html#manage-gcc-abi).
```

Thanks for the feedback, closing this as solved in 2.0
