### ISSUE TITLE
[bug] Compile error when including nested dependencies

### ISSUE THREAD

**Issue by Mucha92** [conan-io/conan#13805]
### Environment details

* Operating System+version: Windows 10 Pro, 21H2
* Compiler+version: gcc (Rev10, Built by MSYS2 project) 12.2.0, cmake version 3.26.3
* Conan version: 2.0.4
* Python version: 3.8.3
```
Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Windows

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Windows
```

### Steps to reproduce

1. create execuable that depends on library B, which depends on library A
`exe` -> `lib_a` -> `lib_b`

```
mkdir lib_a
mkdir lib_b
mkdir exe

cd lib_a
conan new cmake_lib -d name=lib_a -d version=1.0
conan create .
cd ..

cd lib_b
conan new cmake_lib -d name=lib_b -d version=1.0 -d requires=lib_a/1.0
conan create .
cd ..

cd exe
conan new cmake_exe -d name=exe -d version=1.0 -d requires=lib_b/1.0
```
2. include `lib_a` in `exe/src/exe.cpp` (add `#include "lib_a.h"`)
3. build `exe`
```
cd exe
conan install .
conan build .
```
4. got error: `fatal error: lib_a.h: No such file or directory`

### Logs

This is how generated cmake file for `lib_a` looks like (`exe/build/Releases/generators/lib_a-release-x86_64-data.cmake`):

Note that `lib_a_INCLUDE_DIRS_RELEASE` variable is not set.

```
########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(lib_a_COMPONENT_NAMES "")
set(lib_a_FIND_DEPENDENCY_NAMES "")

########### VARIABLES #######################################################################
#############################################################################################
set(lib_a_PACKAGE_FOLDER_RELEASE "[hidden]/.conan2/p/lib_a9bcabdbb803b7/p")
set(lib_a_BUILD_MODULES_PATHS_RELEASE )


set(lib_a_INCLUDE_DIRS_RELEASE )
set(lib_a_RES_DIRS_RELEASE )
set(lib_a_DEFINITIONS_RELEASE )
set(lib_a_SHARED_LINK_FLAGS_RELEASE )
set(lib_a_EXE_LINK_FLAGS_RELEASE )
set(lib_a_OBJECTS_RELEASE )
set(lib_a_COMPILE_DEFINITIONS_RELEASE )
set(lib_a_COMPILE_OPTIONS_C_RELEASE )
set(lib_a_COMPILE_OPTIONS_CXX_RELEASE )
set(lib_a_LIB_DIRS_RELEASE "${lib_a_PACKAGE_FOLDER_RELEASE}/lib")
set(lib_a_BIN_DIRS_RELEASE )
set(lib_a_LIBRARY_TYPE_RELEASE STATIC)
set(lib_a_IS_HOST_WINDOWS_RELEASE 1)
set(lib_a_LIBS_RELEASE lib_a)
set(lib_a_SYSTEM_LIBS_RELEASE )
set(lib_a_FRAMEWORK_DIRS_RELEASE )
set(lib_a_FRAMEWORKS_RELEASE )
set(lib_a_BUILD_DIRS_RELEASE )
set(lib_a_NO_SONAME_MODE_RELEASE FALSE)


# COMPOUND VARIABLES
set(lib_a_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${lib_a_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${lib_a_COMPILE_OPTIONS_C_RELEASE}>")
set(lib_a_LINKER_FLAGS_RELEASE
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${lib_a_SHARED_LINK_FLAGS_RELEASE}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${lib_a_SHARED_LINK_FLAGS_RELEASE}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${lib_a_EXE_LINK_FLAGS_RELEASE}>")


set(lib_a_COMPONENTS_RELEASE )
```

**Comment by memsharded** [comment]
Hi @Mucha92 

Thanks for your report.

This is expected. ``lib_a`` is not a direct dependency of ``exe``, and as such, it cannot be directly included. The alternatives are:

- ``exe`` declares a explicit ``requires = "lib_a/...``, if it contains explicit ``#include "liba.h"`` in its source code. It means it is a direct dependency.
- ``lib_b`` declares a ``self.requires("lib_a/...", transitive_headers=True)`` if its headers publicly include the headers of ``lib_a``.

In your case, in ``2. include lib_a in exe/src/exe.cpp (add #include "lib_a.h")``, it seems you are in the first case, so you should be adding the explicit, direct requires to it. The video in https://youtu.be/kKGglzm5ous contains some explanations about it. Also https://docs.conan.io/2/reference/conanfile/methods/requirements.html#reference-conanfile-methods-requirements talks about traits (though we need to add more examples and details, this is future work)

**Comment by memsharded** [comment]
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.
