### ISSUE TITLE
[question] How to force specific compiler for CMake build

### ISSUE THREAD

**Issue by daltonv** [conan-io/conan#13814]
### What is your question?

I want to cross compile for windows and linux on a linux host machine. 

I thought I could just have my windows target profile list the mingw-64 package under `[tool_requires]`, but it appears that packages isn't Conan 2.0 ready yet.

In the mean time I just want to modify my conanfile.py to force the compiler to the mingw compiler when targeting windows. I have tried:
```python
def generate(self):
        if self.settings.os == "Windows":
            compiler_executables = {
                "c": "x86_64-w64-mingw32-gcc",
                "cpp": "",
            }
            self.conf_info.update("tools.build:compiler_executables", compiler_executables)
            self.buildenv_info.define_path("CC", compiler_executables["c"])

        cm = CMakeToolchain(self)
        cm.generate()
```

This doesn't seem to work though. Is there another way I can go about this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @daltonv 

Thanks for your question.
It seems there are a couple of confusions there:

- It is not possible to set values for configuration in recipes, to be consumed in the same recipe. Please read: https://docs.conan.io/2/knowledge/guidelines.html. Configuration values like the C compiler should be defined in general in profile files, not in recipes
- The ``generate()`` method is to process information from dependencies and generate the necessary files for the build, reading from dependencies and configuration, not for hardcoding values
- The ``conf_info`` and ``buildenv_info`` are to be used exclusively at the ``package_info()`` method, and that is information for the consumers of the recipe. It could make sense for a recipe like ``mygcc/1.0`` that contains the gcc compiler and that could be used as a ``tool_requires`` to inject it to other packages. In that case, the ``mygcc`` recipe could define ``conf_info`` and ``buildenv_info``.

Please let me know if this clarifies the issue. Thanks!

**Comment by daltonv** [comment]
Hi @memsharded,

Thanks that clears up quite a lot but I still have some questions. 

> * It is not possible to set values for configuration in recipes, to be consumed in the same recipe. Please read: https://docs.conan.io/2/knowledge/guidelines.html. Configuration values like the C compiler should be defined in general in profile files, not in recipes

That makes sense, but I need a bit more logic for this to work. I want to use the "x86_64-w64-mingw32-gcc" compiler only if my host profile os == Windows AND my build profile os == Linux. Is there a way to support that check, or do I just need two profile files for windows? 

> * The generate() method is to process information from dependencies and generate the necessary files for the build, reading from dependencies and configuration, not for hardcoding values
> * The conf_info and buildenv_info are to be used exclusively at the package_info() method, and that is information for the consumers of the recipe. It could make sense for a recipe like mygcc/1.0 that contains the gcc compiler and that could be used as a tool_requires to inject it to other packages. In that case, the mygcc recipe could define conf_info and buildenv_info.

That clears up a lot for me. Thanks. I do actually make a `mygcc/1.0` package for the arm compiler and blindly just copied `package_info()` code from there hoping it would would work. 

Regards,
Dalton

**Comment by memsharded** [comment]
> That makes sense, but I need a bit more logic for this to work. I want to use the "x86_64-w64-mingw32-gcc" compiler only if my host profile os == Windows AND my build profile os == Linux. Is there a way to support that check, or do I just need two profile files for windows?

Yes, I think so, the profile for cross compiling from Linux->Window might be different to the native Windows->Windows one, that would totally make sense, if that is the question. I guess you can use the ``jinja`` templates capabilities of profiles, you can write ``if`` conditions with jinja in your profile. You can also use ``include()`` of other profiles to do composition and avoid repetition if that is the concern.

**Comment by daltonv** [comment]
That seems to be what I am looking for. 

I see the documentation on the jinja templating in the profiles now. I've tested it out and its working for my needs.
