### ISSUE TITLE
[question] Package imports

### ISSUE THREAD

**Issue by Drllap** [conan-io/conan#13816]
### What is your question?

I'm developing a qt application and want to be able to distribute it via Qt. I want be able to run `conan install <myapp>` to fetch it from our conan package repository. I'm able to package my executable but I can't package the import qt .dlls. It's like they are deleted somewhere between after the call to `build` and before the call to `package`.

Here is my test `conanfile.py`:
```
from conans import ConanFile, CMake, tools

class ConanCmakeDefTestConan(ConanFile):
    name = "test"
    version = "1.0.0"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of ConanCmakeDefTest here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}
    requires = ["qt/6.4.2"]
    generators = "cmake"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def source(self):
        self.run("git clone https://github.com/conan-io/hello.git")
        # This small hack might be useful to guarantee proper /MT /MD linkage
        # in MSVC if the packaged project doesn't have variables to set it
        # properly
        tools.replace_in_file("hello/CMakeLists.txt", "PROJECT(HelloWorld)",
                              '''PROJECT(HelloWorld)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()''')

    def configure(self):
        self.options["qt"].shared = True

    def build(self):
        cmake = CMake(self)
        cmake.definitions["SOME_CMAKE_VARIABLE"] = "ON"
        cmake.configure(source_folder="hello")
        cmake.build()

    def package(self):
        self.copy("*.exe")
        self.copy("*.dll")

    def imports(self):
        if self.settings.os != "Windows":
            print("import for Linux not implemented yet") 
            return

        if self.settings.build_type == "Debug":
            self.copy("*/Qt6Cored.dll")
            self.copy("*/Qt6Widgetsd.dll")
            self.copy("*/Qt6Guid.dll")

            self.copy("res/archdatadir/plugins/platforms/qwindowsd.dll")
        else:
            self.copy("*/Qt6Core.dll")
            self.copy("*/Qt6Widgets.dll")
            self.copy("*/Qt6Gui.dll")

            self.copy("res/archdatadir/plugins/platforms/qwindows.dll")

```
When I run `conan create . u/t` I can see in the console that the import happens:
```
test/1.0.0@u/t imports(): Copied 4 '.dll' files: Qt6Core.dll, Qt6Widgets.dll, Qt6Gui.dll, qwindows.dll
```
so the import definitely happens and if I kill while it is building the files are there but when the packaging happens it only finds the .exe:
```
test/1.0.0@u/t package(): Packaged 3 '.exe' files: greet.exe, CompilerIdC.exe, CompilerIdCXX.exe
```

Is this intended behavior or a bug?
Any input on how I can package the dependent dlls?

I'm using:
conan version 1.59.0
Windows 10

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Drllap 

First, some quick hints:
- The ``cmake`` generator is legacy in 1.X and has been superseded in 1.X by ``CMakeDeps`` and ``CMakeToolchain``, and completely removed in 2.0. So better stop using it.
- Same for ``from conans import ConanFile, CMake``. The ``from conans`` import shouldn't be used any more, only ``from conan``, see https://docs.conan.io/1/reference/conanfile/tools.html
- The ``self.copy()`` has also been replaced by ``from conan.tools.files import copy`` free function in 1.X


Finally, the ``imports`` method is also removed in 2.0. You can replace it by the ``generate()`` method in Conan 1.59 and a explicit call to ``copy()``. Check: https://docs.conan.io/1/migrating_to_2.0/recipes.html#removed-imports-method (and the whole https://docs.conan.io/1/migrating_to_2.0/recipes.html in general)

The thing is that the ``imports()`` is a temporary copy while the build runs, but for package creation it will remove the files after being used, to avoid them being accidentally re-packaged. The ``generate()`` approach is completely explicit, it doesn't remove anything internally.

**Comment by Drllap** [comment]
@memsharded Thanks for this.

I'm trying to use the `CMake` from `conan.tools.cmake`. I am setting a custom cmake variable with:
```
cmake = CMake(self)
cmake.definitions["MY_VARIABLE"] = "MyValue"
```

but this doesn't work with the new module.

**Comment by memsharded** [comment]
Because the definition of variables belongs to the ``CMakeToolchain``, not to ``CMake``, in order to achieve reproducibility, also for the developer experience. So something like:
```python
def generate(self):
     tc = CMakeToolchain(self)
     tc.variables["MY_VARIABLE"] = "value"  # defined in conan_toochain.cmake
     # or
     tc.cache_variables["MY_OTHERVAR"] = "other value"  # defined in CMakePresets
     tc.generate()
```
