### ISSUE TITLE
[question] Conan-2.x and set_version

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#13827]
### What is your question?

Dear Conan Folks,

I see a change how packages look in conan cache with Conan-2.x. I use the method set_version in recipes , to differentiate between tag builds and branch builds:
```
def set_version(self):
        git = Git(self)
        try:
            git_tag = git.run("describe --exact-match --tags")
        except ConanException:
            git_tag = None
            pass
        if (git_tag == None):
            branch_name = git.run("symbolic-ref --short -q HEAD")
            commit_id = git.run("rev-parse --short HEAD")
            if (os.environ.get('JENKINS_HOME') is None):
                self.version = "0.0.0-dev.0"
            else:
                if (os.environ.get('BUILD_ID') is not None):
                    build_id = os.environ.get('BUILD_ID')
                    self.version = "%s.%s" %("0.0.0-dev", build_id)
        else:
            try:
                tag_version = semantic_version.Version(git_tag)
            except ValueError:
                print("Git tag is not named as per semantic versioning")
            else:
                self.version = "%s" %(git_tag)
```
In conan-1.x, when I compile locally, a package version used to be set as 0.0.0-dev.0 , however in conan-2.x I cannot find the versions attached to the packages. Could you please explain if I need to adapt the method above?
How is the naming in the cache with conan-2.x ? I appreciate that long path handling is automatically handled in Windows.

Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

Thanks for your question.

Do you mean how is the folder structure in the cache in 2.0?
It is using some hashing of the references, so it is not as straightforward to navigate as in 1.X, but it has other advantages:
- removed the ``short_paths`` Windows problem
- Can store multiple revisions (that was a big limitation in 1.X)
- Will be easier to provide concurrency in the future
- Contains infrastructure for operations as remove the unused things (not used in the last X time, to be develop in the future)

To navigate the cache, you can use the ``conan cache path <ref>`` command, it will tell you which folder contains your files. You can also check those folders, they are usually printed in the command output.

**Comment by maitrey** [comment]
Thanks james for replying.
 conan cache path qasw/0.0.0-dev.0@autosar/bringupconan2.x does 
provide  C:\Users\.conan2\p\qaswweb8ec1a432dd0\e and this is not the package folder. 
The features in conan-2.x definitely solve all the problems listed above however perhaps I was used to package names being inituitive in the cache.

**Comment by memsharded** [comment]
If you want the package folder, the ``ref`` should contain the package id like ``pkgv/version@user/channel:package_id``, otherwise you get the recipe folder.

**Comment by maitrey** [comment]
Yes that points to the correct location but its more easier to see the command output. The only drawback is when I build multiple variants then I must scroll through the command output.

**Comment by maitrey** [comment]
I have a supplementary question, I donot understand the lock files:
```
 {
    "version": "0.5",
    "requires": [ "qasw/0.0.0-dev.0@autosar/bringupconan2.x#b1d90f5b5e84b4f6f5bcf6cf0277f4af**%**1683278223**.**3261497" ]
}
```
What is the % and . in the above?

**Comment by memsharded** [comment]
The final part after the ``%`` is the timestamp of the revision. It is necessary to sort the revisions, to be able to correctly resolved them.

**Comment by maitrey** [comment]
Now I have all the informations that I want. I would request to close the question. Many thanks.
