### ISSUE TITLE
[bug] Bash doesn't like the use "!" when cleaning up old revisions

### ISSUE THREAD

**Issue by jputcu** [conan-io/conan#13834]
### Environment details

* Operating System+version: up-to-date Manjaro
* Conan version: 2.0.4
* Python version: 3.10.10

When trying to clean up old revisions using the advised command:
~~~~
> conan remove zlib/1.2.13#!latest
bash: !latest: event not found
> conan remove "zlib/1.2.13#!latest"
bash: !latest: event not found
> conan remove zlib/1.2.13\#\!latest
Remove the recipe and all the packages of 'zlib/1.2.13#13c96f538b52e1600c40b88994de240f'? (yes/no):
~~~~

So I think the choice of "#!" is unlucky on `bash`.

**Comment by jputcu** [comment]
Single quotes help:
~~~~
> conan remove 'zlib/1.2.13#!latest'
Remove the recipe and all the packages of 'zlib/1.2.13#13c96f538b52e1600c40b88994de240f'? (yes/no):
~~~~

**Comment by jputcu** [comment]
Apparently it is the '!': https://stackoverflow.com/questions/42798737/bash-usr-bin-env-event-not-found

**Comment by memsharded** [comment]
Thanks for the feedback @jputcu 

I think Conan is also using ``!`` in some other parts of the CLI, which I guess it might be a bit problematic to change.
There are also other characters like ``*`` that also require quoting, and those are also good for CLI, like ``conan remove "*" -c`` is quite intuitive. Maybe it is just a matter of adding quotes in the docs?

**Comment by jputcu** [comment]
Hello

Consistently adding the single quotes to the documentation would be a good idea if it is cross platform (Windows?).

**Comment by memsharded** [comment]
I have just checked, and it is a problem, the single quotes don't work on Windows :(

**Comment by jputcu** [comment]
Maybe add a variant, e.g. `not_latest` which allows the documentation to use double quotes consistently.

**Comment by mkmkme** [comment]
@memsharded I've just checked on my Windows 11, and it seems that in powershell, both single and double quotes work just fine. On `cmd.exe`, though, neither single nor double quotes seem to work. Both `echo 'zlib/1.2.13#!latest'` and `echo "zlib/1.2.13#!latest"` cause the string to be printed including the quotes.

**Comment by memsharded** [comment]
We will propose the ``~latest`` alternative syntax. Apparently it works:

- Propose the change for ``latest``, but also for ``--build=!zlib*`` negation patterns
- Test that it works without quotes or with double quotes in all platforms: Windows (cmd, powershell) Linux bash

**Comment by mkmkme** [comment]
Hi @memsharded, are you sure it's needed? As I pointed [here](https://github.com/conan-io/conan/issues/13834#issuecomment-1539404392), single quotes should work on Windows. So is it really worth changing?

**Comment by memsharded** [comment]
But single quotes don't work on Windows cmd, only in Powershell, do they?
I have just tested, and it fails to work (it takes the single quotes as literal, without removing them)
In Windows cmd both with and without quotes work, it is just the single quotes that fail, so it is not possible

**Comment by mkmkme** [comment]
PowerShell removes both single and double quotes. cmd.exe preserves both single and double quotes (i.e. keeps those as literals).

That's at least a result of my quick research.

Do preserved single quotes actually break something on Windows?

> In Windows cmd both with and without quotes work, it is just the single quotes that fail, so it is not possible

I see. In that case of course. Thanks for clarification :)

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/14000 implemented the ``~latest`` syntax, validated in all shells, will be in next 2.0.7
