### ISSUE TITLE
[bug] Conan doesn't find package binary when using virtual repositories

### ISSUE THREAD

**Issue by stefanpantic-pdftools** [conan-io/conan#13831]
### Environment details

* Operating System+version: macOS (M1 Pro), Linux (Ubuntu 22.04)
* Compiler+version: apple-clang 14, clang 14, gcc 9+
* Conan version: 2.0.4
* Python version: 3.9

### Steps to reproduce

I am experiencing the same issue reported in https://github.com/conan-io/conan/issues/5127.

I have a few private Conan repositories in my jFrog Cloud subscription where I post my prebuilt package binaries to. I aggregate my repositories + the Conan Center Index repository using a Virtual repository.

The problem which occurs is that for some packages (for example `zlib`) Conan reports the package binary is missing on all platforms even though the binary is present:
```
======== Installing packages ========
ERROR: Missing binary: zlib/1.2.13:8359538fee5b146800be789e3d3f504010b3bc01

zlib/1.2.13: WARN: Can't find a 'zlib/1.2.13' package binary '8359538fee5b146800be789e3d3f504010b3bc01' for the configuration:
[settings]
arch=armv8
build_type=Debug
compiler=apple-clang
compiler.version=14
os=Macos
[options]
fPIC=True
shared=False

ERROR: Missing prebuilt package for 'zlib/1.2.13'
Check the available packages using 'conan list zlib/1.2.13:* -r=remote'
or try to build locally from sources using the '--build=zlib/1.2.13' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```
<img width="941" alt="image" src="https://user-images.githubusercontent.com/112647847/236441234-650655b3-dc6e-456c-af37-05063615b731.png">

This only occurs when using the Virtual repository, when I removed the Virtual repository and used my remote directly the package was resolved and downloaded properly:
```
======== Computing necessary packages ========
pdf_demo_sdk/1.2.13: Forced build from source
Requirements
    pdf_demo_sdk/1.2.13#3b6cc92a6adab83a15e3558b8c3380fb:363f28e13fc5ac7a30cc25d890b19e4ff28fd774 - Build
    zlib/1.2.13#416618fa04d433c6bd94279ed2e93638:8359538fee5b146800be789e3d3f504010b3bc01#e2017b138e51656cc6fb902c4255780b - Download (components-conan-latest)

======== Installing packages ========

-------- Downloading 1 package --------
zlib/1.2.13: Retrieving package 8359538fee5b146800be789e3d3f504010b3bc01 from remote 'components-conan-latest'
Downloading conan_package.tgz
Decompressing conan_package.tgz
zlib/1.2.13: Package installed 8359538fee5b146800be789e3d3f504010b3bc01
zlib/1.2.13: Downloaded package revision e2017b138e51656cc6fb902c4255780b
```

**Comment by memsharded** [comment]
Hi @stefanpantic-pdftools 

Thanks for your report.
Unfortunately, this seems to be something exclusively of the server side, Artifactory in this case, so there is very little that we can do here from the client side. I will check internally with the right team, but this should probably be moved via customer support.

**Comment by stefanpantic-pdftools** [comment]
Thanks for the fast reply, I've created a support ticket for in my jFrog subscription.

**Comment by memsharded** [comment]
Seen the ticket in the tracker, lets follow there (closing it here, thanks for reporting!)
