### ISSUE TITLE
[question] Are values for 'cppstd' to be intended as numbers or strings?

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#13838]
### What is your question?

Hi!
We are trying to add a compiler definition in 'settings_user.yml', something like this:
```
cl2000:
    version: ["6.1.0", "18.1.8"]
    cppstd: [null, 98, 99, 03]
```
When trying to use it in a profile as follows:
```
compiler=cl2000
compiler.version=18.1.8
compiler.cppstd=03
```
what we get with a `conan build` command is the following error:
```
ERROR: Invalid setting '03' is not a valid 'settings.compiler.cppstd' value.
Possible values are ['98', '99', '3']
```
Seems that `03` is converted to a number and then back to the string `3`.

Are we using this setting the wrong way or is it possibly a bug?
We are currently trying version 2.0.4 of Conan on Windows 11.
TIA

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @marausch 

Thanks for your question.
All settings values are intended to be strings, including ``cppstd`` and versions like ``13``.
The reason is that there are other cppstd values like ``gnu17``, which are strings, having heterogeneous types for the same value would be more problematic and confusing. Same reason for version when ``13.1`` shouldn't be a float number, but a string.

**Comment by marausch** [comment]
Hi @memsharded,
Thank you for the quick answer.
You are confirming our assumption, but in this case, what is the explanation for the strange message we get:
`Possible values are ['98', '99', '3']`
despite having defined **`'03'`** (not **`'3'`**) in our _settings_user.yml_ file?

(Maybe a bug-issue should be opened instead...)

**Comment by memsharded** [comment]
Let me do a quick check for that.

**Comment by memsharded** [comment]
This test seems to work fine:
```python
def test_settings_user_extra_cppstd():
    c = TestClient()
    settings_user = textwrap.dedent("""\
        compiler:
            gcc:
                cppstd: ["03"]
        """)
    save(os.path.join(c.cache_folder, "settings_user.yml"), settings_user)
    c.save({"conanfile.py": GenConanfile().with_settings("os", "compiler")})
    # New settings are there
    c.run("install . -s os=Windows -s compiler=gcc -s compiler.version=11 "
          "-s compiler.libcxx=libstdc++11 -s compiler.cppstd=03")
    assert "compiler.cppstd=03" in c.out
```

**Comment by marausch** [comment]
In fact what we did (following the model given e.g. for `intel-cc` in the standard `settings.yml`) is:
`cppstd: [null, 98, 99, 03]`
instead of:
`cppstd: [null, "98", "99", "03"]`
as you did in your example above.
In other words, seems that we need to explicitly add quotation marks around the values for `cppstd` (in `settings_user.yml`).
And indeed, doing so it works.

**Comment by memsharded** [comment]
Oh, I see what is happen, it is just the "0".

This works too:
```python
def test_settings_user_extra_cppstd():
    c = TestClient()
    settings_user = textwrap.dedent("""\
        compiler:
            gcc:
                cppstd: [3]
        """)
    save(os.path.join(c.cache_folder, "settings_user.yml"), settings_user)
    c.save({"conanfile.py": GenConanfile().with_settings("os", "compiler")})
    # New settings are there
    c.run("install . -s os=Windows -s compiler=gcc -s compiler.version=11 "
          "-s compiler.libcxx=libstdc++11 -s compiler.cppstd=3")
    assert "compiler.cppstd=3" in c.out
```

It is that yaml will convert the "03" as integer literal to just "3". So it is necessary to quote it.
In general the yaml doesn't need to be quoted, as it adds a bit more of noisy, as Conan will internally convert to strings. But this "03" processing happens before Conan gets the data.

**Comment by marausch** [comment]
Thank you very much for your patience.
:)
So, i guess the same issue might happen with the similar case of `intel-cc` as defined in the standard `settings.yml`, where an unquoted `03` is listed as well:
```
cppstd: [null, 98, gnu98, 03, gnu03, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, 23, gnu23]
                          ^^
```

**Comment by memsharded** [comment]
Proposing a fix to quote it, but checked https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-9/std-qstd.html, it seems that it could be just dropped the ``03``?

**Comment by marausch** [comment]
I don't know, actually. I mentioned `intel-cc` just because we took it as an example for our case (we have a rather old version of a TI compiler). The solution of quoting the value is quick and we are happy to know it's an allowed one.
Again, thank you very much!

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13844, thanks for the feedback!
