### ISSUE TITLE
b2/4.9.6: Invalid: 'settings.os' value not defined

### ISSUE THREAD

**Issue by JohnVida** [conan-io/conan#13830]
### What is your question?

how can i  fix this issue？

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @JohnVida, thanks for your question. We need more info in order to help you out. In what situation are you finding this issue? What command are you running?

**Comment by JohnVida** [comment]
actually i am a fish man on conan.
The command and conanfile.txt is showed below:

**input**

[requires]
fmt/8.0.1
zlib/1.2.13
boost/1.71.0
gsl-lite/0.37.0
[generators]
cmake
cmake_find_package
[options]
fmt*:header_only=True
boost*:without_stacktrace=True
boost*:shared=False
boost*:header_only=False
boost*:fPIC=Tru
**cmd:** 
/usr/local/bin/conan install . --build missing --settings build_type=Debug --settings compiler=gcc --settings compiler.version=8 --settings compiler.libcxx=libstdc++11 --settings os=Linux --settings arch=x86 

**log：**
======== Input profiles ========
Profile host:
[settings]
arch=x86
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

Profile build:
[settings]


======== Computing dependency graph ========
Graph root
    conanfile.txt: /home/jiqiang/Documents/workspace/scc/SystemC-Components/build/conanfile.txt
Requirements
    boost/1.71.0#48916d15c23c5ab656001e59b3173e28 - Cache
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
    fmt/8.0.1#83a72a784eab50272df627a2f17a69be - Cache
    gsl-lite/0.37.0#ea78b98d288c2ed7561da22723e35117 - Cache
    zlib/1.2.13#e377bee636333ae348d51ca90874e353 - Cache
Build requirements
    b2/4.9.6#2e02945ad41739b8051247d14fe8297d - Cache

======== Computing necessary packages ========
Requirements
    boost/1.71.0#48916d15c23c5ab656001e59b3173e28:fbf39d5786e603f013aa4437f27a29522ee048c9 - Build
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d:949bb55be21deb7255e39507820996a3deb44bf0 - Build
    fmt/8.0.1#83a72a784eab50272df627a2f17a69be:da39a3ee5e6b4b0d3255bfef95601890afd80709#c0a08d798280d79d2d8fdb33adb58a84 - Download (conancenter)
    gsl-lite/0.37.0#ea78b98d288c2ed7561da22723e35117:da39a3ee5e6b4b0d3255bfef95601890afd80709#e37916602768911d456a4e7bc8eadc18 - Download (conancenter)
    zlib/1.2.13#e377bee636333ae348d51ca90874e353:a76da6dbc38e28d31047cba414b23ce60034452c - Build
Build requirements
    b2/4.9.6#2e02945ad41739b8051247d14fe8297d:da39a3ee5e6b4b0d3255bfef95601890afd80709 - Invalid

======== Installing packages ========
ERROR: There are invalid packages:
b2/4.9.6: Invalid: 'settings.os' value not defined

**Comment by AbrilRBS** [comment]
Thanks for the extra info. The problem here is that your build profile is empty. At the very least you need to define `os` and `arch` for the build context, the one where Conan actually runs, as Conan can not be run in a os-less system :)

Also, let me take the opportunity to recommend moving away from the legacy `cmake` & `cmake_find_package` integrations in favour of the modern ones, `CMake`, `CMakeDeps` and `CMakeToolchain` in which the consuming CMakeLists.txt doesn’t need to be aware at all about Conan, see https://docs.conan.io/2/reference/tools/cmake.html for mor info. (The legacy ones have been dropped from Conan 2, which we also recommend to update to if possible, one of the needed changes to port your usage of Conan to the new version is moving away from those generators)

**Comment by JohnVida** [comment]
Thank you very much.
I have used the cmd with os=Linux .But there is still the same issue. .
/usr/local/bin/conan install . --build missing --settings build_type=Debug --settings compiler=gcc --settings compiler.version=8 --settings compiler.libcxx=libstdc++11 --settings os=Linux --settings arch=x86

**Comment by JohnVida** [comment]
Thank you very much.
It worked when added the below settings in ~/.conan2/profiles/default file.
```
[settings]
os=Linux
arch=x86
```

**Comment by memsharded** [comment]
Yes, exactly, that is the correct solution @JohnVida 

The "build" profile is the profile of the machine Conan is running on. It must have at least the ``os`` and the ``arch`` (Conan needs to run a ``os`` with an ``arch``).

**Comment by AbrilRBS** [comment]
Closing as solved, feel free to open new issues should you have any other questions!
