### ISSUE TITLE
How to access self.cpp_info.objects

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#13843]
### What is your question?

Hi
I am trying to setup a recipe file to define an object file in self.cpp_info.objects and then try to access the object in my gnu makefile.  How can I access the path to this object file from my consumer package so I can setup my gnu makefile? I do not see variables defined like CPPFLAGS or LDFLAGS when setting up cpp_info.includedirs or cpp_info.libs in the bat files. Is there some documentation that show how a consuming recipe file should access  self.cpp_info.objects?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

Consumer recipes can always visit their dependencies, something like:

```python
def generate(self):
    for dep in self.dependencies.values():
        dep_objects = dep.cpp_info.objects
        # then, do what is desired with the dep_objects, typically write to a file that can be used
```

It seems that ``CMakeDeps`` implements some built-in management of ``.objects``, but other build system don't, most likely there is no standard convention to handle them.

**Comment by Ed-CMI** [comment]
HI Diego

When setting cpp_info.object is it suppose to be the full path to the object file  or just the name of the object file. When running you code all I get is octane_integration/1.1.1:  Object files['FblBmHdr_Lcfg.o']. I set cpp_inof.objects = ['FBLBmHdr_Lcfg.o'].  How do I get the full path to the object file

**Comment by memsharded** [comment]
The ``cpp_info.objects`` (in plural), gets converted to full absolute paths when managed by Conan, so consumers see the full path. I have checked in a couple of tests in Conan test suite and seems to be working fine.

**Comment by Ed-CMI** [comment]
Thx Diego. I'll check my code for a bug

**Comment by memsharded** [comment]
Sure, let us know how it goes, and please re-open if any further question or feedback.

**Comment by Ed-CMI** [comment]
Hi Diego

I was working on setting up the object files for some other file and I see a problem with the dep.cpp_info.object when using the code below. I set cpp_info.objects as follows
 self.cpp_info.objects = ['generated\obj\fbl_shared\src\FblBmHdr_Lcfg.o']

for dep in self.dependencies.values():
    self.output.info(f"csar-buildenv-requires.py: Object file {dep.cpp_info.objects}")

The path print out below is as follows
octane_integration/1.1.1: csar-buildenv-requires.py: Object file ['C:\\Users\\bq824\\.conan2\\p\\fbl_s1dfae53143030\\p\\generated\\obj\x0cbl_sLcfg.o'] 

For some reason the path is replacing the actual file name with x0cbl_sLcfg.o instead of FblBmHdr_Lcfg.o, When I uses this file in my makefile I get an error indicate no such file exist because of the name change. If this same code is done using  self.cpp_info.objects = ['FblBmHdr_Lcfg.o'] and place the file in the root directory of the package folder I see no issues

Is there some type of character limit being exceed in this instance?

**Comment by memsharded** [comment]
I would say it is could be not the character limit, but instead that the string is using backslash, which is considered a escape character in Python, without defining the ``r"generated\obj\"``. So I'd try:
- To define the path string as a raw literal with ``r"mystring"``
- To define it joining paths, like ``[os.path.join("generated", "obj", ...)]``

**Comment by Ed-CMI** [comment]
Hi Diego

That change worked. Thx
