### ISSUE TITLE
k[bug] Temp include subdirectories getting removed

### ISSUE THREAD

**Issue by cubisttriangle** [conan-io/conan#13859]
### Environment details

* Operating System+version: Win11 21H2
* Compiler+version: msvc v193
* Conan version: 2.0.4
* Python version: 3.11.0

### Steps to reproduce

1. use conan2
2. `mkdir subdir && cd subdir`
3. `conan new cmake_lib -d name=subdir -d version=0.1`
4. apply the following patch, which moves the header into a subdirectory (for clearer organization):
```
From 053e3f4fe5694bd96e2df542ffd14fb6c6e594a6 Mon Sep 17 00:00:00 2001
From: ...
Date: Tue, 9 May 2023 20:40:40 -0600
Subject: [PATCH] create include subdir

---
 CMakeLists.txt                     | 1 -
 include/{ => test_subdir}/subdir.h | 0
 src/subdir.cpp                     | 2 +-
 test_package/src/example.cpp       | 2 +-
 4 files changed, 2 insertions(+), 3 deletions(-)
 rename include/{ => test_subdir}/subdir.h (100%)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index ce3ed5b..0e06197 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,5 +9,4 @@ target_include_directories(subdir PUBLIC include)



-set_target_properties(subdir PROPERTIES PUBLIC_HEADER "include/subdir.h")
 install(TARGETS subdir)
diff --git a/include/subdir.h b/include/test_subdir/subdir.h
similarity index 100%
rename from include/subdir.h
rename to include/test_subdir/subdir.h
diff --git a/src/subdir.cpp b/src/subdir.cpp
index e78b206..e026893 100644
--- a/src/subdir.cpp
+++ b/src/subdir.cpp
@@ -1,5 +1,5 @@
 #include <iostream>
-#include "subdir.h"
+#include <test_subdir/subdir.h>



diff --git a/test_package/src/example.cpp b/test_package/src/example.cpp
index 659abe0..491ea1d 100644
--- a/test_package/src/example.cpp
+++ b/test_package/src/example.cpp
@@ -1,4 +1,4 @@
-#include "subdir.h"
+#include <test_subdir/subdir.h>

 int main() {
     subdir();
--
2.40.1.windows.1


```
5. `conan create .`

At this point, there should be a failure in building the `test_package` since `cmake_install.cmake` creates a reference to headers in a temporary build folder.

```
CMake Error in CMakeLists.txt:
  Imported target "subdir::subdir" includes non-existent path

    "~/.conan2/p/b/subdifdf3eb59af98d/p/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Indeed, the folder mentioned does not exist. Is there something I've missed in the `CMakeLists.txt` or `conanfile.py`?

**Comment by memsharded** [comment]
Hi @cubisttriangle 

It seems you are missing the correct installation of the headers, in your CMakeLists.txt:
```cmake
install(DIRECTORY include/
        DESTINATION include
        COMPONENT header_files
        FILES_MATCHING PATTERN "*.h")
```
The original ``set_target_properties(subdir PROPERTIES PUBLIC_HEADER "include/subdir.h")`` you removed was doing the ``cmake.install()`` in the ``package()`` method, but even if you leave this line, this "flattens" the hierarchy, so something like the above would be necessary.

Of course, alternatively you can do a ``copy(self, "*.h", ...`` in your ``package()`` method.

**Comment by cubisttriangle** [comment]
That works! You are a wizard - thanks!

**Comment by memsharded** [comment]
Happy to help!
