### ISSUE TITLE
[suggestion]   a better component support

### ISSUE THREAD

**Issue by zhangzikai** [conan-io/conan#13851]
### What is your suggestion?

I think  the way to use components is not elegant,i want some adjust,sorry for my poor english
## 1.for consuming  components: 
a convenient  way for requiring components
**in conanfile.txt**  
[requires]
mylib:cmp1/1.2.3
**in conanfile.py**
requires = "mylib:[cmp1,cmp2]/1.2.3"
## 2.for producing components: 
another way to define components's dependencies,i don't want to define dependencies twice
introduce a new concept requirements group ,there is a default requirements group which name is same as lib name(mylib)
### ①for 0 component  library , 
there is also a default component mylib,referenced by mylib/1.2.3,mylib:mylib/1.2.3. 
for example ,in mylib requirements()   method ,these method can push requirements into  the default group
```
self.requires("math/1.0", transitive=True, group="mylib") 
self.requires("math/1.0", transitive_libs=True)
self.requires("mylib",["otherib{cmp1,cmp2}/1.2.3",{"name":"otherlib{cmp1,cmp2}/1.2.3","transitive":True}])
self.requires({"groupName":"mylib","transitive":True},["otherib{cmp1,cmp2}/1.2.3",``{"name":"otherlib{cmp1,cmp2}/1.2.3","transitive":False}]) 
```
in package_info() method , the default component mylib will by default require the requiments group with same name
"self.cpp_info.~requires~bind('mylib')" #we can omit the line

(another question:i think there is no need of a  "transitive_headers" option, because only interface  headers are put in the requiment'package folder, we  just define wether the requiment is needed for mylib'consumer'build)
### ②for 1..n components library ,
 besides the default requirements group ,we can define one requirements group per component
in requirements() method
self.requires({"groupName":"cmp1","transitive":True},[":cmp2/1.3.3","mylib:cmp3/1.2.3","otherlib/4.5.6"])#push to the group cmp1
in package_info() method,
 "self.cpp_info.components["cmp1"].~requires~bind('cmp1','mylib')"#can be omited

we can give msbuild build system the components ability,in build() method
~~~
def getRequiementsGroupsByProjectName(prjName):
     return [prjName]
msbuild = msbuild()
msbuild.configure({"mapper":getRequiementsGroupsByProjectName})#find the vcproj file to inject or replace the conandeps.prop
msbuild.build()
~~~
in cmake build system ,we just collect all requirements to create the toolchain file,do just as usual in build method

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @zhangzikai 

Thanks for your feedback.

Please let me try to explain the rationale and design of the components:

- First, no added syntax will be added for ``conanfile.txt``. That format is only intended for the basic cases, any advance case needs a ``conanfile.py``. The rationale is explained in: https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html
- Components are not a package/redistribution thing, it is just a build system thing. The package is always complete and include all components binaries, they are all uploaded and downloaded. So ``require`` only some components is non actionable, Conan will still require the whole package. Then, the build system needs to define anyway what components to link. For example in CMake, ``target_link_libraries(myapp PRIVATE Boost::regex)``. For MSBuild it means adding the ``boost_regex.props`` to the subproject that depends on it. As this is the native way of doing it, and necessary in any case, it is not necessary to duplicate that information in the recipe.
- As components only have access at the build system level, it is not intended at the moment to add extra definitions in the ``conanfile.py`` recipe. We have already considered it a few times, but the necessary effort to implement those things would be too much for the value they would provide. 

Related to the ``transitive_headers``, it is a necessary trait, because knowing if the dependencies headers are visible through the current package headers, is necessary information for the consumers, it needs to be specified somewhere. I'd recommend watching https://youtu.be/kKGglzm5ous to learn more about these traits.

**Comment by zhangzikai** [comment]
hi, @mathieu 
I get your points,the support for component is enough.thanks for your explaintion

**Comment by zhangzikai** [comment]
hello, @mathieu
again,after some exploration,i want to talk about two thing
### the package type  .
i don't know why treat buildscript and python-require as separate type. is this messed  up the package-type config
i suggest to have these package type
```
|-------compiler related
|             └-------headeronly library
|             └-------static   library
|             └-------shared  library
|             └-------library
|-------compiler  not  related
|             └-------runable # exe,dll,so  which files should be put in conanrun.bat/conanbuild.bat depend on the 
|                             #  package in build/host context
|             └-------resource#build script ,python-requires something  be accessed from conanfile.py.python-
|                             # requires can be instead  by some util function 
```
### the dependecies management
The require funtion put  diffrent scope's option(build=True,headers=True) in one function call ,Its more like conan private api  to be used for deciding which files should be passed to downstream and creating the deps file(mathconfig.cmake,math.prop)
As a user ,i want the api to be clean.
1.  take the "build " option away  ,only  refer the runable by tool_require ,which will put the runable package and it's upstream in build context and add to the conanbuild.bat(i think  this package also can be defined to pass down to downstream)
2. hide the conan "private " traits(heads,libs,run,transitive_headers,transitive_libs,direct) from user , these traits should only be used in some  triky/hacky  situation.

when i define dependcies  , i only care about  two thing  
-   which api(dependency) do i want
-   which api(dependency)  will be part of my interface api to be passed down to downstream.

so . most of times ,i only use  few traits(visible,force,override,package_id_mode) .
As for conan private using traits ,these should be deduced from  the package type and  user using traits  in my require call.
for example,in the  dependency  tree     math(static)<-graphic<-engine(static)<-game(runable) https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html
when graphic is static library  , in graphic's conanfile.py
~~~
# the visible option default value is False ,which means math package'api(headers) is hidden from graphic's downstream
# inside conan ,also  pass math'libs to graphic's downstream for graphic's linking
# in case of  embed the math static lib in graphic static  lib ,it's time to use transitive_libs=False to 
# cut off  math's lib'stransmission
self.requires("math/1.0")
~~~
~~~
# inside conan ,also pass math'libs and headers to graphic's downstream for compiling and lingking with math
self.requires("math/1.0",visible=True)
~~~
when graphic is shared library 
~~~
# inside conan , pass nothing  to graphic's downstream
# but if there are some  shared library in upstream, these library'lib should always be passed down
self.requires("math/1.0")
~~~
~~~
# inside conan ,also pass math'libs and headers to downstream for compiling and lingking with math
self.requires("math/1.0",visible=True)
~~~
For now ,it's like conan doesn't work in this way , i think this way is more  intuitive. 
And  test trait  isn't  necessary, test = True can be instead of visible = False.

Also ,don't forget to provider package type support to component .

**Comment by memsharded** [comment]
> i don't know why treat buildscript and python-require as separate type. is this messed up the package-type config

``python-requires``: is some python code that you want to use directly in your ``conanfile.py``, even deriving from a base class. It is Conan related functionality extension, for all stages of the Conan recipe.
``build-scripts`` are build-only related information, necessary at build-time only, like some cmake scripts.

So they are super different in the way they are created, used and the way the propagate information.

> so . most of times ,i only use few traits(visible,force,override,package_id_mode) .

Most of the times, the ``headers, libs, transitive_headers, transitive_libs, run`` are indeed not necessary to define. They are automatically deduced from the ``package_type``. It is only necessary to define them when the defaults are not enough to represent some alternative cases.

**Comment by zhangzikai** [comment]
when graphic is shared library
```
 # inside conan ,also pass math'libs and headers to downstream for compiling and lingking with math
 self.requires("math/1.0",visible=True)
```
when i test conan in this situation .math's  headers and libs doesn't be passed down.
```
self.requires("math/1.0",transitive_headers=True)
```
when i changed the parameters to "transitive_headers=True",math's  headers and libs can be passed down together.
It's  wired, it's designed to behave in this way? or just a bug ? I don't know how to manage transitive dependecies in conan  nor that how  conan   deduce the  traits, I  also check conan site'document ,nothing more to find

**Comment by memsharded** [comment]
>  self.requires("math/1.0",visible=True)

``visible=True`` is already the default, you don't need to define it

> self.requires("math/1.0",transitive_headers=True)

This is only necessary when the ``math`` headers are included in the public headers of the current package. This is not the default, by default, libraries tend and try to encapsulate and have dependencies as an implementation detail, that is, only as part of their ``.cpp`` and private ``.h``, but not in their public headers, because that makes a more coupled API of the current package. SO this is very necessary to differentiate the case where the headers are included or not from the public API. It has nothing to do with the ``visible`` trait (it requires ``visible=True`` otherwise the require is not propagated at all), but it not the same as ``visible`` trait, it represents a very different thing.

**Comment by zhangzikai** [comment]
I think we give the dependencies tree diffrent abstraction. let's do a compartion.
could  you tell me what aguments should be put  in self.requires() to achieve the same functionality  in cmake?

math<-graphic<-engine<-game
| cmake | conan | meaning |
| - | - | - |
|target_link_library(graphic PUBLIC math)|self.requires("math/1.0",???)#self is graphic conanfile instance| regardless of  package 's type ,math  can be seen in graphic  and engine| 
|target_link_library(graphic PRIVATE math)|self.requires("math/1.0",???)#self is graphic conanfile instance| regardless of package 's type ,math can be seen in graphic   and can **not** be seen in engine|

**Comment by memsharded** [comment]
First case: ``self.requires("math/1.0", transitive_headers=True, transitive_libs=True)``
Second case: ``self.requires("math/1.0", transitive_headers=False, transitive_libs=False)``

In both cases, the usage of those without consideration to the actual package type can easily lead to compile errors or linking errors. When CMake is "seeing" or not "seeing" the dependency, it might be actually linking with it. But Conan is not a build system, and it needs to abstract any build system, so the abstraction is not 1:1 to the CMake one.

In practice the usage doesn't need to consider these things, and simply do:
- For most cases do ``self.requires("math/1.0")``
- If ``graphics`` leaks the ``math`` headers through its public headers, add ``self.requires("math/1.0", transitive_headers=True)``

**Comment by zhangzikai** [comment]
I know cmake will actually link with it ,even not having it's header ,but the  user don't need to take care of  it.It just happens and works.
conan2.0 have package type . It has the ability to provide a option like cmake to manage transitive dependencies  for example (self.requires("math/1.0",public=True). I really don't  want to focus on  things like package type ,libs ,headers.etc(the  low level,the detail thing can be manage by  conan). Conan have the ability  to detemine which headers should be passed down .and which lib should be linked with by  traversal the  tree and check node's package type.
Maybe i'm a little strict ,i just want conan  to be better
