### ISSUE TITLE
[question] Why isn't transitive dependency on Boost include directories propagated by CMakeDeps?

### ISSUE THREAD

**Issue by a-kryuk** [conan-io/conan#13856]
### What is your question?

I am trying to use Conan 2.0.4 to package a library depending on Boost (just the headers, really). The '`conan source .`' command succeeds, but '`conan export-pkg .`' fails when trying to test the package. Both the package and the test use **CMakeDeps**. I managed to trace the issue to the difference in the generated `Boost-release-x86_64-data.cmake` files. The one for the package has lines like
```CMake
set(boost_INCLUDE_DIRS_RELEASE "${boost_PACKAGE_FOLDER_RELEASE}/include")
```
and the one for the test has
``` CMake
set(boost_INCLUDE_DIRS_RELEASE )
```
So, my question is "what prevents Conan from propagating the include requirements to the package consumer?" Given that the link requirements do seem to be propagated, it looks like the cause lies in the Boost Conan recipe (I picked boost/1.81.0 and put it in a local Artifactory), but maybe I misunderstand the concepts and am doing something wrong. 

Attached is my minimal sample project with file `console.txt` capturing the commands and their output
[xxx.tar.gz](https://github.com/conan-io/conan/files/11433050/xxx.tar.gz)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @a-kryuk thanks for your question.
The issue you are seeing comes from Conan 2 being able to better predict what kind of information the user wants in their final package thanks to the usage of [requirement traits](https://docs.conan.io/2/reference/conanfile/methods/requirements.html#requirement-traits)

If your public headers use symbols from your dependencies/adds includes to those, such dependency would need to be declared with a `transitive_headers=True` trait.


In fact, if I apply this patch to your repro case (Thanks *a lot* for such a detailed repo, we appreciate those a lot):
```diff
diff --git a/conanfile.py b/conanfile.py
index 8376e64..16f5b76 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -20,7 +20,7 @@ class xxxRecipe(ConanFile):
 
   def requirements(self):
     if os.environ.get('XXX_CONAN_DEBUG'): print("debug:requirements()") 
-    self.requires("boost/[~1 >=1.57]")
+    self.requires("boost/[~1 >=1.57]", transitive_headers=True)
   #----------------------------------------------------------------------------
   def config_options(self):
     if os.environ.get('XXX_CONAN_DEBUG'): print("debug:config_options()") 
```


Then I get boost working as expected for the test package and the CMake files have all the relevant info added to them.

I hope this helps, happy to answer more regarding this if you have any other doubts :)

**Comment by a-kryuk** [comment]
Thanks for the answer. The `transitive_headers=True` argument indeed resolves the problem.
I guess, I still don't understand the auto-inference of requirements traits by Conan. I would expect the **headers** dependencies to be transitive by default unless turned off by something else, especially considering that the **libs** dependency does seem to be propagated. Is this controlled by the `package_type` (of boost in this case)?
Is it possible to specify only the `Boost::boost` (`Boost::headers`) part as a requirement, so that it can be treated as a header-only dependency?

**Comment by AbrilRBS** [comment]
Yes, some inferring of the traits is done by the specified `package_type` of the dependent/dependee. There's some section at the bottom of the link I sent that tries to document that behaviour, but let me know if it needs more clarification so that I can improve the wording there too :)

One other resource I'd like to bring your attention to is [this ACCU 2022 presentation](https://www.youtube.com/watch?v=kKGglzm5ous) by @memsharded where more details about the requirement traits is done

**Comment by a-kryuk** [comment]
Thaks, Rubén

After watching the talk, I think I understand the logic better.
It would be nice to put more of  those explanations in the written documentation, so that the information is searchable. For example, the default transitivity traits for different package types, not just for header-library.
I, personally, find having transitive_headers=False by default counterintuitive. It's not clear from the documentation what happens when the package_type is not explicitly set, or where one would want to set it.
In terms of wording, may I suggest rephrasing of the following in the "https://docs.conan.io/2/reference/conanfile/methods/requirements.html#libs" section

 This trait will typically be True for direct shared and static libraries, but could be false for indirect static libraries that are consumed via a shared library

Into

 This trait will typically be True for direct shared and static library dependencies, but could be false for indirect static library dependencies linked to a shared library dependency

Now that I think about it some more, I realize that I don't understand why in a "consumer->shared_lib->static_lib" dependency graph (no direct dependency "consumer->static_lib") the shared_lib package would set libs=False, rather than transitive_libs=False. Maybe I need to watch the video a couple more times 🙂


________________________________

**Comment by AbrilRBS** [comment]
Will give a proper answer in a few days, but for now:

> It would be nice to put more of  those explanations in the written documentation, so that the information is searchable. For example, the default transitivity traits for different package types, not just for header-library.


You're totally right! This is something I found that needed to be done a few weeks ago, and now it's available in https://docs.conan.io/2/reference/conanfile/methods/requirements.html#package-type-trait-inferring let me know if that works :)
