### ISSUE TITLE
[feature] Improve error message when not authenticated with remote

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#13858]
### What is your suggestion?

Currently when the user is not authenticated with a JFrog Conan repository, the Conan client won't say so. Neither during operations like conan create / install, nor while explicitly searching for a specific package.

Instead the Conan client reports something like this:

    $ conan search -r conanserver mypkg
    There are no packages matching the 'mypkg' pattern

This is technically correct in a way. But it also annoyingly insufficient, especially to new users. They expect to be notified when they need to log in, especially since the JFrog Artifactory Conan server seems to reset the authentication token quite often.

A simple warning would already be sufficient, something like:

    $ conan search -r conanserver mypkg
    Warning: skipping remote "conanserver" due to authentication failure
    There are no packages matching the 'mypkg' pattern

This would really improve usability and would prevent users from wondering what's going on. Especially since the output of commands like conan create can be very verbose and confusing, it is often not clear what's actually happening.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @stevn 

I think this issue has been reported before, and it seems something that cannot be solved, because it is a matter of server configuration. The server is not returning any authentication failure, it is returning a 404-NotFound. This is a typical server security strategy, not returning any information about things for non authenticated users. It is possible to configure the server so it actually throws an auth challenge and request the user to enter credentials, instead of returning 404:
```
conan search * -r=conan-local
Please log in to "conan-local" to perform this action. Execute "conan remote login" command.
Remote 'conan-local' username:
```

**Comment by stevn** [comment]
@memsharded 

I think the client should distinguish between an empty results list and a http 404 error? Seems weird to me to treat both as the same thing.

I must admit I haven't looked at the server communication code yet though.

**Comment by stevn** [comment]
This topic seems to be discussed here for example:

https://stackoverflow.com/questions/13366730/proper-rest-response-for-empty-table

**Comment by AbrilRBS** [comment]
As @memsharded said, this approach is quite normal, where an unauthenticated user can not know whether a resource is missing or if they don't have enough permissions to see it. https://jfrog.com/help/r/jfrog-platform-administration-documentation/hide-existence-of-unauthorized-resources explains how to toggle this feature in Artifactory

**Comment by nicosmd** [comment]
Hey @memsharded and @RubenRBS 

Would it be possible to at least print a hint that the user is not authenticated? It could be printed when artifactory is returning 404 and the user status for this remote is unauthenticated. In our company we can't easily toggle the hiding feature in Artifactory and it happens basically every week that a developer run in this issue. A hint would increase the self-solving rate dramatically, I guess.

**Comment by AbrilRBS** [comment]
Hi @nicosmd, maybe that can work, thanks for the suggestion! Let me take a look into it and see how it goes :)

**Comment by memsharded** [comment]
This was closed by https://github.com/conan-io/conan/pull/17127, which will be in next Conan 2.9
