### ISSUE TITLE
[bug] `conan graph build-order` generates lockfile in recipe directory

### ISSUE THREAD

**Issue by PengolodhGoedath** [conan-io/conan#13850]
### Environment details

* Operating System+version: Win10 x64 22H2
* Compiler+version: ---
* Conan version: 2.0.0, 2.0.4
* Python version: 3.11.2

### Steps to reproduce

1. Place `conanfile.py` in a directory, e.g. `mylib/conanfile.py`
2. Navigate into a different directory (e.g. parent of `mylib`)
3. Run these conan commands:
```
        conan lock create mylib --lockfile-out mylock.lock
        conan graph build-order mylib --lockfile mylock.lock --lockfile-out buildorder.lock
```
Expected outcome: `buildorder.lock` is in the current working directory
Observed outcome: `buildorder.lock` is in `mylib`, next to the `conanfile.py`

Most annoyingly, this prevents any further `conan create` calls, since `mylib` is now dirty.

**Comment by memsharded** [comment]
Hi @PengolodhGoedath 

Thanks for the feedback. It seems this would be indeed a bug, I will check it.
Just to double check, something is missing in your ``conan graph build-order`` command? Like it is missing a path or something?

**Comment by PengolodhGoedath** [comment]
Oops, I forgot to add `mylib/conanfile.py` as path. Will fix the initial post!

**Comment by franramirez688** [comment]
Closed by https://github.com/conan-io/conan/pull/13853
