### ISSUE TITLE
[question] Using Conan with Artifactory over ssh?

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#13863]
### What is your question?

It appears that the `jfrog-cli` is able to [support](https://jfrog.com/knowledge-base/cli-how-to-configure-jfrog-cli-to-work-with-ssh-authentication/) authentication in Artifactory using ssh keys rather then the traditional method of api tokens or passwords for authentication. I was wondering if conan supports a similar workflow using ssh keys when authenticating with the `conan remote auth` command? If so then is it documented somewhere  that I missed.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @wbehrens-on-gh 

Thanks for your question.

No, Conan does not support ssh keys, it needs a password or token, and at this moment it is not a planned feature.

**Comment by memsharded** [comment]
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.
