### ISSUE TITLE
[question] Conan2: Reading / dumping version ranges for dependencies ?

### ISSUE THREAD

**Issue by ATS-AValli** [conan-io/conan#13862]
### What is your question?

In order to integrate a Coan2 into our existing CI infrastructure, we would like to print (or dump to file) not only the RESOLVED dependencies  (such as those found in self.dependencies) but also the requirement as set in the requirements() method, that could be a version range, such as:
`self.test_requires("gtest/[>1]")`

It seems this information is available in the dependency graph (and is printed by Conan2 under "Resolved version ranges") but the CLI command "`conan graph info`" does not display it.

Is it mandatory to use the graph API ? I'd rather not use it as it's marked as unstable for now.

I've searched through the existing issues and I haven't found what I'm looking for.

Thanks for any help.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ATS-AValli 

Thanks for your question.

To see if I understood it correctly, you would like to have the same or equivalent of what is printed to screen in the json output of ``conan graph info .. --format=json``?

We plan to put some time this sprint to improve and stabilize that ``json`` output, so we could take this into consideration.

**Comment by ATS-AValli** [comment]
Hi!

> Thanks for your question.
> 
> To see if I understood it correctly, you would like to have the same or equivalent of what is printed to screen in the json output of `conan graph info .. --format=json`?

Not exactly, I've tried using "graph info" (with JSON format) and nowhere I could locate the requirement as it was specified in the requirements() method.

To be more clear, let's imagine we have the following method:

```
    def requirements(self):
        self.requires("mypackagef/[>0]", transitive_headers=True)
 [Imagine more self.requires() here]
```

What I would like to catch, other than the RESOLVED dependency (which could become "mypackage/1.1.1@user/channel"), is "mypackagef/[>0]".
Now, of course since it's specified in the code already I could copy and paste the same string in my desired output but I would like to read it from the code.

Or said in other words, I would like to have the same data that is being printed during "install" or "create" right below:

Resolved version ranges

I've been looking into the source of conan 2 and saw that this is the result of a call to graph.load_graph().

Thanks.

**Comment by memsharded** [comment]
> Not exactly, I've tried using "graph info" (with JSON format) and nowhere I could locate the requirement as it was specified in the requirements() method.

Yes, my suggestion/question, was if you would be happy if we added some new information to the json that contained the same information that is printed on screen.

> Or said in other words, I would like to have the same data that is being printed during "install" or "create" right below:

Yes, this is what I meant, adding this to the json

**Comment by ATS-AValli** [comment]
> Yes, my suggestion/question, was if you would be happy if we added some new information to the json that contained the same information that is printed on screen.

I would be very happy! :-)

> Yes, this is what I meant, adding this to the json

Now, I get it. Yes, that's what we would need.

Thanks a lot for the prompt response; I hope this improvement can make it through the pipeline in appropriate time.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/13934 added those to the graph json:

```json
 "resolved-ranges": {
        "pkgb/[~0]@common/unstable": "pkgb/0.1@common/unstable",
        "ros_perception/[~1.1]@3rdparty/unstable": "ros_perception/1.1.4@3rdparty/unstable"
    }
```

I am tentatively closing this as implemented in https://github.com/conan-io/conan/pull/13934, will be released in 2.0.6, but please don't hesitate to re-open or create a new ticket if there is some further issue or questions.

**Comment by ATS-AValli** [comment]
Thank you a lot.
We're looking forward to the 2.0.6 release.

Speaking of JSON, how stable is the format ?

Cheers.

**Comment by memsharded** [comment]
We will start documenting now, not sure if "experimental" or "preview", maybe the former for a couple of releases until users use it, just in case, then move to "preview", the idea is to stabilize it as quickly as possible.

**Comment by ATS-AValli** [comment]
> We will start documenting now, not sure if "experimental" or "preview", maybe the former for a couple of releases until users use it, just in case, then move to "preview", the idea is to stabilize it as quickly as possible.

Good to know, thanks!
