### ISSUE TITLE
[question] Generator in conan install command overwrite generators in recipe?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#13879]
### What is your question?

I have defined generators in my recipe resp. python_requires base class.
When I now run conan install with the -g parameter does it then overwrite the pre-defined generators or just add the specified one on-top of the pre-defined ones?

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

Thanks for your question.
The generators specified in command line add to the ones defined in the recipe, they don't overwrite the existing ones. Also when the generators are inherited from a python_requires.

Does this clarify your question?

**Comment by MTomBosch** [comment]
Yes. Thank you. Would be nice if this is mentioned in the official docs of the conan install command or the generators chapters in the docs .
I did remember what you said, then looked it up in the docs but could not find it. So I posted this question to be sure.

Will close this issue nevertheless.
