### ISSUE TITLE
conan create output_folder

### ISSUE THREAD

**Issue by baqeri** [conan-io/conan#13872]
### What is your question?

Hi everyone!
How can I change the default output_folder of `conan create .`? I changed `layout(self)` method in `conanfile.py` to this:
```
    def layout(self):
        self.folders.generators = os.path.join("target")
        self.folders.build = os.path.join("target")
#        cmake_layout(self)
```

it works when I call `conan build .` but on `conan create .` base_directory is changed to .conan2 cache directory.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @baqeri 

Yes, package creation, with ``conan create`` happens in the Conan cache. If you don't want to create a package, you can do ``conan build`` or ``conan install`` to install dependencies, but packages are created and installed in the Conan cache.

**Comment by baqeri** [comment]
thank you @memsharded

**Comment by AbrilRBS** [comment]
Closing as answered, feel free to open further issues if you have any other questions :)
