### ISSUE TITLE
How to tell if a conan center recipe is conan 2.0 compatible 

### ISSUE THREAD

**Issue by leinadme** [conan-io/conan#13876]
Hi,

I'm building an app that is required to use Qt 6.2.4.   Prior to that it was 5.15.7.  I was able to build and use 5.15.7 with conan 2.0 with no issues.  When I updated my recipe to install and build Qt 6.2.4 I got the following error (see below).  I checked the link 
( https://conan.io/cci-v2.html) but there was no pertinent information.  I looked at the Qt 6.2.4 recipe and it appears from the code that it is conan 2.0 ready.  

Is there a way I can tell if a recipe from the conan center is 2.0 ready by looking at the recipe or is there something else I am missing like the wrong compiler version?

Below is the command I used and the message I got in return.  Any help is appreciated.

conan install .. -s compiler.version=193 --build=missing -s build_type=Release

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

======== Computing dependency graph ========
Graph root
    conanfile.py (app/1.5.5): C:\folder\application\conanfile.py
Requirements
    boost/1.80.0#d9db5f9b32697fe04fa22390e9078427 - Cache
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
Build requirements
    b2/4.9.3#106e977c8c9892a5de9c438c465b3db6 - Cache
*********************************************************
Recipe 'qt/6.2.4' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'qt/6.2.4' not resolved: qt/6.2.4: Cannot load recipe.
Error loading conanfile at 'C:\Users\name\.conan2\p\qt47516955512f9\e\conanfile.py': Unable to load conanfile in C:\Users\name\.conan2\p\qt47516955512f9\e\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\name\.conan2\p\qt47516955512f9\e\conanfile.py", line 18, in <module>
    from conans import RunEnvironment, tools
ImportError: cannot import name 'RunEnvironment' from 'conans' (c:\python37\lib\site-packages\conans\__init__.py)

**Comment by memsharded** [comment]
Hi @leinadme 

There is a very clear indicator that a recipe is not 2.0 ready. If it contains any ``from conans``, then it is not 2.0 ready. Conan 2.0 completely removed that import for recipes, all recipes should import ``from conan``.

Otherwise it is difficult to know it. It would be very easy to implement in recipes if they added:
```
required_conan_version = ">=1.55 <2.0"
```
But the majority of ConanCenter recipes not compatible with 2.0 they don't contain that.

**Comment by leinadme** [comment]
Ok, it looks like I missed the last two  from statements which clearly show "conans".
Thanks.

from conan import ConanFile
from conan.tools.apple import is_apple_os
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.build import cross_building, check_min_cppstd, build_jobs, default_cppstd
from conan.tools.env import VirtualBuildEnv, Environment
from conan.tools.files import copy, get, replace_in_file, apply_conandata_patches, save, rm, rmdir, export_conandata_patches
from conan.tools.gnu import PkgConfigDeps
from conan.tools.microsoft import msvc_runtime_flag, is_msvc
from conan.tools.scm import Version
from conan.errors import ConanInvalidConfiguration
**from conans import RunEnvironment, tools
from conans.model import Generator**
required_conan_version = ">=1.55.0"
