### ISSUE TITLE
[bug] failed to download big file (1.91G)

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#13878]
### Environment details

* Operating System+version: Linux ubuntu 20.04
* Compiler+version: GCC 9.4.0
* Conan version: 1.59.0
* Python version: 3.8.10
* Docker image: nvcr.io/nvidia/l4t-ml:r35.2.1-py3

### Steps to reproduce

1. tools.get("https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/8.6.0/tars/TensorRT-8.6.0.12.Ubuntu-20.04.aarch64-gnu.cuda-12.0.tar.gz", strip_root=True)

### Logs
```
ERROR: tensorrt/8.6.0: Error in source() method, line 18
        tools.get("https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/8.6.0/tars/TensorRT-8.6.0.12.Ubuntu-20.04.aarch64-gnu.cuda-12.0.tar.gz", strip_root=True)
        ConanConnectionError: Download failed, check server, possibly try again
Transfer interrupted before complete: 1017118133 < 2054420674
```

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

Thanks for your report.

I have tried a few times in my computer, and I didn't manage to make it fail.
Maybe it is something related to the network, either a temporary glitch in their servers, of maybe some limits in your local network, like in the docker image?

Does it fail deterministically for you, that is, does it always fail?
Can you please try in other platforms, under the same network? Can you try in a different network?

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed
> 
> Thanks for your report.
> 
> I have tried a few times in my computer, and I didn't manage to make it fail. Maybe it is something related to the network, either a temporary glitch in their servers, of maybe some limits in your local network, like in the docker image?
> 
> Does it fail deterministically for you, that is, does it always fail? Can you please try in other platforms, under the same network? Can you try in a different network?

I think the problem is the network, thanks for replying.
