### ISSUE TITLE
[bug] Windows executable from website downloads the latest release only

### ISSUE THREAD

**Issue by taita2104** [conan-io/conan#13883]
### Environment details

When downloading a file from conan.io, the Windows executable obtained is the latest released.
This means that without notice, until 10/05/23, the downloaded version was 2.0.4 while from 11/05/23 the downloaded version is 1.60.0.

This causes issues because the two versions have different commands and behaviors.

**Comment by memsharded** [comment]
Hi @taita2104 

Thanks for reporting.

You are right, this is because Github makes it automatically the latest.
I have just fixed, please retry and let me know.

**Comment by taita2104** [comment]
Looks like it's fixed. 
Thank you.
