### ISSUE TITLE
[question] adding libraries to LDLIBS

### ISSUE THREAD

**Issue by igagis** [conan-io/conan#13889]
### What is your question?

Conan adds library path to all libraries from dependencies to `LDFLAGS` when using `AutotoolsDeps` generator.
But it does not add the actual libraries (from `cpp_info.libs`) to `LDLIBS`. Is it possible to make it do that?

Also, I have library C which depends on library B, which, in turn depends on library A, but B doesn't expose any API from A. I.e. B only needs A while building and uses it internally.

Now, if A, B and C are all packaged as static libraries. This means that when using library C in some program, one has to give `-lC` linker flag and also `-lB -lA`, otherwise linker will complain that there are undefined references to A in B and to B in C.

So, I want that when using C conan generator would add `-lA -lB -lC` to `LDLIBS`, is that possible to achieve?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by igagis** [comment]
Or maybe, when using C there is no need to add `-lC` automatically, but only `-lA -lB`, since those come transitively, and in case of dynamically linked `C` those don't have to be given to linker, but in case of static `C` we need those `-lA -lB`.

**Comment by igagis** [comment]
The explanation is a bit cumbersome, but I hope you get the idea :)

**Comment by igagis** [comment]
I've just found that in the docs https://docs.conan.io/2/reference/tools/gnu/autotoolsdeps.html
it says that `LIBS` variable will be set, and I checked that it is actually set to `-l<...>` values.
I'm wondering why is it `LIBS` and not `LDLIBS` which is the actual one used by `GNU make`, according to https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html#index-LDLIBS ?

**Comment by agagniere** [comment]
Yep, I always have to add `LDLIBS += $(LIBS)` in my Makefiles, which kind of defeats the point of AutotoolsDeps...
Maybe we can create a pull request to add `LDLIBS` in addition to `LIBS` : https://github.com/conan-io/conan/blob/release/2.0/conan/tools/gnu/autotoolsdeps.py#L72

**Comment by agagniere** [comment]
So, while GNU make uses `LDLIBS` by default, it seems the rest of the Autotools project does not follow that convention, and in `configure.ac` of big projects like ImageMagick, I see :
```bash
for var in CC CFLAGS CPPFLAGS CXX CXXCPP LDFLAGS AR_FLAGS LIBS ; do
```
([source](https://github.com/ImageMagick/ImageMagick/blob/main/configure.ac#L63))

**Comment by agagniere** [comment]
In fact the GNUCoding Guidelines only mention `LDFLAGS` : 
https://www.gnu.org/prep/standards/standards.html#Command-Variables

So it would seem that to conform to those guidelines one should be putting `-l name` flags  into `LDFLAGS`

**Comment by memsharded** [comment]
Thanks for your feedback  @igagis @agagniere 

The ``AutotoolsDeps`` tries to target the autotools tools (autoconf, automake, etc).

The ``autoconf`` documents (https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Preset-Output-Variables.html) the ``LIBS`` variable for this, so this seems aligned with the current behavior of the generator.

Efforts are being done to create a pure ``Make`` integration, starting with a ``MakeDeps`` generator, but that uses custom ``CONAN_`` variables that users should map to their own ``makefiles``

**Comment by igagis** [comment]
@memsharded at the moment in my makefiles I'm just adding `LIBS` to `LDLIBS` manually. This would be same as "mapping `CONAN_` variables to own makefiles" but just needs to map only one `LIBS` variable instead of several.

My suggestion is not to conform to `autoconf` or `GNU` coding guidelines or whatever, it is to make conan easier to use and more convenient. Since `GNU make` uses `LDLIBS` variable it would be very handy if `conan` also used it.

I could not find any docs or mentions about `MakeDeps` generator for conan 2, perhaps it is in early development stage yet. But, why using custom `CONAN_` variables as it was in conan 1? Why not go with same approach as in `AutotoolsDeps`? I.e. setting well known (by `GNU make`) variables like `CXXFLAGS`, `LDFLAGS`, `LDLIBS` in that `MakeDeps` generator?

**Comment by memsharded** [comment]
> My suggestion is not to conform to autoconf or GNU coding guidelines or whatever, it is to make conan easier to use and more convenient. Since GNU make uses LDLIBS variable it would be very handy if conan also used it.

Sure, of course, but the generator has ``AutotoolsXXX`` in the name. This one is expected to follow autotools conventions, and diverging from that, even if it could be more convenient for some users, can certainly annoy and even break other users that conform and expect strict conformance to the autotools standards. 
If we want to support and make it more convenient for other users not using autotools, the way to go is indeed other generators. This topic has been discussed in https://github.com/conan-io/conan/issues/13394

>  could not find any docs or mentions about MakeDeps generator for conan 2, perhaps it is in early development stage yet. 

This is wip in https://github.com/conan-io/conan/pull/14133, this feedback and discussion will be very welcome there. The work there builds on top of several users own implementations, and there was some consensus on this approach. But it would be great to discuss this topic there.

**Comment by igagis** [comment]
Ok, I think this question issue can be closed
