### ISSUE TITLE
[bug] conan create with error "ImportError: cannot import name 'conanFile' from 'conans'" 

### ISSUE THREAD

**Issue by onlyou2030** [conan-io/conan#13882]
### Environment details

* Operating System+version:macos 13.2.1
* Compiler+version:apple clang 14.0
* Conan version:2.0.0
* Python version:3.10.10

### Logs

janco@B-T2L0MD6M-1910 conan-opus % conan create .

======== Exporting recipe to the cache ========
ERROR: Error loading conanfile at '/Users/janco/ThirdParty/conan-opus/conanfile.py': Unable to load conanfile in /Users/janco/ThirdParty/conan-opus/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/janco/ThirdParty/conan-opus/conanfile.py", line 1, in <module>
    from conans import conanFile, tools, CMake
ImportError: cannot import name 'conanFile' from 'conans' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/__init__.py)

**Comment by memsharded** [comment]
Hi @onlyou2030 

Thanks for your report.

If you update to latest 2.0.4 (you should, only the latest patch of every major.minor is supported), the error message should be a bit more helpful. It should tell you that you are trying to use a recipe that is not 2.0-ready, with Conan 2.0.

So you would need:
- to make sure you keep using Conan 1.X (pip install conan==1.60, for example)
- to update the recipe to be 2.0 compatible (this can be done while in 1.X)

If the recipe is from ConanCenter, not all recipes have been updated yet there to be 2.0, the community is doing a great effort there, but it takes time.

**Comment by onlyou2030** [comment]
> .

Thanks for reply. It have been solved by using "from conan import ConanFile, tools".
But I have another question:  The get method in tools have removed, which one can I use instead?

ERROR: opus/1.3.1: Error in source() method, line 39
	tools.get(**self.conan_data["sources"][self.version])
	AttributeError: module 'conan.tools' has no attribute 'get'

**Comment by memsharded** [comment]
The tools have been catogorized in different namespaces, not removed. Please have a look to the docs in https://docs.conan.io/2/reference/tools.html

For this, it should be ``from conan.tools.files import get``

This was also done in Conan 1.X, it is compatible in 1.X and 2.0.
