### ISSUE TITLE
ERROR: Missing prebuilt package for electric-fence/2.2.0@lasote/stable

### ISSUE THREAD

**Issue by virtualint** [conan-io/conan#1388]
Hello,

I successfully compiled my package before 11 June, when conan.io moved to bintray completely. Now I cannot compile my project.

**1.** When I run the following command

`conan install ../ -s build_type=Debug `

conan gives following error

>Requirements
>    Boost/1.57.0@lasote/stable from local
>    OpenSSL/1.0.2h@lasote/stable from local
>    Poco/1.7.3@lasote/stable from local
>    electric-fence/2.2.0@lasote/stable from local
>    zlib/1.2.8@lasote/stable from local
>Packages
>    Boost/1.57.0@lasote/stable:0db5426d370c9c4957d5ea1d7af5744940cb3d1e
>    OpenSSL/1.0.2h@lasote/stable:8012780057107124c4d309744a0f51f7dce14c62
>    Poco/1.7.3@lasote/stable:982d1789cb30843171360bda274043b9dd92035c
>    electric-fence/2.2.0@lasote/stable:913b2bf51745909824871d361dfb55bc841f9d13
>    zlib/1.2.8@lasote/stable:913b2bf51745909824871d361dfb55bc841f9d13
>
>Boost/1.57.0@lasote/stable: Already installed!
>WARN: Can't find a 'electric-fence/2.2.0@lasote/stable' package for the specified options and settings:
>- Settings: arch=x86_64, build_type=Debug, compiler=gcc, compiler.version=5.4, os=Linux
>- Options: shared=False
>
>ERROR: Missing prebuilt package for 'electric-fence/2.2.0@lasote/stable'
>Try to build it from sources with "--build electric-fence"
>Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

**2.** I also checked if electric-fence package

`conan install electric-fence/2.2.0@lasote/stable  `

and the command gives the following output

>Requirements
>    electric-fence/2.2.0@lasote/stable from local
>Packages
>    electric-fence/2.2.0@lasote/stable:500a5737cfb7bee13d4a0039e72446892ca242ab
>
>electric-fence/2.2.0@lasote/stable: Already installed!

**3.** I tried conan command with --build missing and still no luck. I checked and read the http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package url which is given on the conan's error message.

Any help is appreciated, am i missing something?

I am using Ubuntu 16.04.2 LTS and Conan version 0.22.3

Regards

**Comment by jacmoe** [comment]
Did you update your remotes to point to `conan-transit` and `conan-center` ?

```bash
$ conan remote remove conan.io
$ conan remote add conan-center https://conan.bintray.com
$ conan remote add conan-transit https://conan-transit.bintray.com
```

http://conanio.readthedocs.io/en/latest/move_to_bintray.html

**Comment by virtualint** [comment]
Hello Jacmoe,

Sure I updated according to the document and when I run

`conan remote list`

conan-center: https://conan.bintray.com [Verify SSL: True]
conan-transit: https://conan-transit.bintray.com [Verify SSL: True]

Thanks
Regards

**Comment by jacmoe** [comment]
What error do you get when you add the option `build missing` (if you get any) ?

**Comment by memsharded** [comment]
Hi @virtualint 

I think I am missing some piece of information. There are no gcc 5.4 pre-built binaries for Boost/1.57.0@lasote/stable, so I guess you should have built that before, otherwise the error trace wouldn't say it is already installed.

But, if building from sources, it should have built first electric-fence, because it is a dependency.

The second time you are running ``conan install electric-fence/2.2.0@lasote/stable`` you are doing it without the ``Debug`` build type, which would be installing a different package.

Could you please try to help us creating a reproducible minimum case? Something like:

- Complete clean your local cache from installed packages (``conan remove "*" -f``)
- Create a minimum conanfile.txt. Most likely Poco is not required to reproduce this
- Call conan install over that conanfile.txt
- Paste the output, if not complete, at least the relevant parts.

Thanks very much for your help!

**Comment by virtualint** [comment]
Hello @memsharded,

Thanks for your help, after your suggestion I ran 

`conan remove "*" -f`

and then I tried 

`conan install ../ -s build_type=Release`

everything worked. Thanks again for a very useful and cool software for c++ programmers :)

Now I can use Poco, SDL2, Boost and gtest in my applications. 

As a note `conan install ../ -s build_type=Debug` still gives error as I mentioned in my first comment. Sorry if I gave any missing information in my previous comments.

Regards

**Comment by memsharded** [comment]
Thanks very much for your kind words :)

Good that it is working now. Could you please report which error are you getting for the ``build_type=Debug`` case? I think it should work too, though it might not be a conan issue, but a package recipe issue. Please tell me, and we'll try to figure out. Thanks!

**Comment by virtualint** [comment]
Hello @memsharded 

When I try to use `conan install ../ -s build_type=Debug `, gives error

> ERROR: Missing prebuilt package for 'gtest/1.8.0@lasote/stable'
> Try to build it from sources with "--build gtest"

`conan install ../ -s build_type=Debug  --build gtest --build Poco --build OpenSSL --build Boost` no errors and work like a charm :)

Thanks for your helps


Regards

**Comment by memsharded** [comment]
Ah, ok, that is perfectly fine, it is just that there is no precompiled package for that configuration. I thought it was failing when building from sources. Thanks very much for telling
