### ISSUE TITLE
[question] connection timeout / retry settings in remote_manager.py in Conan 1.xx?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#13887]
### What is your question?

Hi,
we have a heavily overfloaded Artifactory instance, so I regularly get into a situation when either
"conan export" or "conan install" or any other conan command times out like this:

ERROR: Error loading conanfile at '/home/user/trompeloeil/conanfile.py': HTTPSConnectionPool(host='xxxxx', port=8443): Max retries exceeded with url: /artifactory/api/conan/xxxxx/v2/conans/search?q=xxxxxxx%2F%2A%40xxxxxx%2Fmaster&ignorecase=False (Caused by ReadTimeoutError("HTTPSConnectionPool(host='xxxxxx', port=8443): Read timed out. (read timeout=60.0)",))
[08:12:26][Step 7/13] 
[08:12:26][Step 7/13] Unable to connect to xxxx=xxxxxxxx:8443/artifactory/api/conan/xxxxxx
[08:12:26][Step 7/13] 1. Make sure the remote is reachable or,
[08:12:26][Step 7/13] 2. Disable it by using conan remote disable,
[08:12:26][Step 7/13] Then try again.
[08:12:26][Step 7/13] Process exited with code 1

Can I set a.) bigger read timeout b.) increase the number of retries?
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by harsszegi** [comment]
Oh, is it CONAN_REQUEST_TIMEOUT?

**Comment by memsharded** [comment]
Hi @harsszegi 

CONAN_XXX env-vars was the 1.X legacy way of configuring things.
For the modern, Conan 2.0-compatible way, please check the ``conan config list``. I think there is a ``core.net:timeout`` or something similar, that implements this configuration.

**Comment by harsszegi** [comment]
Awesome, thanks @memsharded closing it!
