### ISSUE TITLE
[question] package sources are fetched only on recepie change

### ISSUE THREAD

**Issue by igagis** [conan-io/conan#13888]
### What is your question?

I'm working on migrating my libraries from conan 1 to conan 2 and I have to try different changes to my makefiles often.

I noticed strange thing, that changes to makefiles are not reflected in CI build unless I also do some changes to conan recipe.

For example, here are 3 consequent CI builds:
1) https://github.com/cppfw/urlmodel/actions/runs/4962443160/jobs/8880505749#step:9:142
There is a print of `LDLIBS` variable from within the `makefile`.

2) I added a print of `LDFLAGS` variable right next to print of `LDLIBS`:
here is the commit: https://github.com/cppfw/urlmodel/commit/b7960056cd8772a395fdd99ac1dce36b303611b0
and here is the CI build: https://github.com/cppfw/urlmodel/actions/runs/4962574790/jobs/8880801559#step:9:142
As one can see, there is still only `LDLIBS` printed, and no `LDFLAGS`.

3) I made a dummy change to the conan recipe, just added a newline:
https://github.com/cppfw/urlmodel/commit/3f92ca4e26336e326322e796f742d5178608ce49
and here is the CI build: https://github.com/cppfw/urlmodel/actions/runs/4962692010/jobs/8881059923#step:9:143
As one can see, no there is `LDFLAGS` print from previous commit.

These 3 commits demonstrate the behavior, but I observed the same earlier as well.

I don't get it because I do builds in docker containers, so every time it is clean environment, so there should be no any cache preserved between builds.
Any idea, why does this happen?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by igagis** [comment]
Ok, I figured out that this code in `export`:

```
                git = Git(self, self.recipe_folder)
		scm_url = git.get_remote_url()
		scm_commit = git.get_commit()
		update_conandata(self, {"sources": {"commit": scm_commit, "url": scm_url}})
```

causes ` git.get_commit()` to return latest commit in which `self.recipe_folder` was changed, not the latest commit of the whole repo.

**Comment by igagis** [comment]
I've changed the code to this:

```
                git = Git(self, Git(self).get_repo_root())
		scm_url = git.get_remote_url()
		scm_commit = git.get_commit()
		update_conandata(self, {"sources": {"commit": scm_commit, "url": scm_url}})
```

and now it seems to get the latest commit of the repo

**Comment by igagis** [comment]
I actually ended up with this code:
```
                git = Git(self)
		scm_url = git.get_remote_url()
		# NOTE: Git.get_commit() doesn't work properly,
		# it gets latest commit of the folder in which conanfile.py resides.
		# So, we use "git rev-parse HEAD" instead as it gets the actual HEAD
		# commit regardless of the current working directory within the repo.
		scm_commit = git.run("rev-parse HEAD") # get current commit
		update_conandata(self, {"sources": {"commit": scm_commit, "url": scm_url}})
```

I think it is not intuitive that `Git.get_commit()` returns not the actual commit of the `HEAD`.
According to the docs, the equivalent command is `git rev-list HEAD -n 1 -- <folder>`, so it takes current working directory into account, which is the dir of `conanfile.py`.

**Comment by memsharded** [comment]
It is getting the commit of the folder passed in the ``Git()`` construction if defined which defaults to the current folder ``.`` if not defined. 

Note that the current folder is not strictly necessary the one that contains the ``conanfile.py``, it depends on the ``layout()`` definition and the recipe method that is executing the code, if the ``self.folders.source`` is defined, that will be the current folder when ``source()`` method is running.

**Comment by igagis** [comment]
Well, yes, I figured out  that it matters which folder `Git` object uses. But that was not obvious at all and I expected another behavior at first. Closing this question as now it is more clear what is happening.
