### ISSUE TITLE
[question] Issue with transient symbols when linking component library

### ISSUE THREAD

**Issue by cubisttriangle** [conan-io/conan#13884]
### What is your question?

I'm trying to create my first [componetized](https://docs.conan.io/2/examples/conanfile/package_info/components.html) package, but am having some unexpected linking issues. I created a [repo ](https://github.com/cubisttriangle/conan_component_test )where this can be recreated.

Initially, I created a package which has a library that links another library. The `test_package` test works great. This can be seen in `HEAD~1` of the example repo.

```
$ conan create . --build=missing
...
======== Testing the package: Building ========
...
[ 50%] Building CXX object CMakeFiles/example.dir/src/example.cpp.o
[100%] Linking CXX executable example
[100%] Built target example

======== Testing the package: Executing test ========
my_unicode_lib/0.1 (test package): Running test()
my_unicode_lib/0.1 (test package): RUN: ./example
start
Successfully created collator
end
```

Next, I move the package's library to a component. Now when `test_package` gets run, it fails to find some symbols in the static lib. This can be seen at the `HEAD` of the example repo.

```
$ conan create . --build=missing
...
======== Testing the package ========
...
my_unicode_lib/0.1 (test package): Running CMake.build()
my_unicode_lib/0.1 (test package): RUN: cmake --build "~/code/cubist/conan/my_unicode_lib/test_package/build/gcc-9-x86_64-gnu14-release" -- -j48
[ 50%] Building CXX object CMakeFiles/example.dir/src/example.cpp.o
[100%] Linking CXX executable example
/usr/bin/ld: ~/.conan2/p/my_un12ff040403516/p/lib/libuni.a(my_unicode_lib.cpp.o): in function `my_unicode_lib()':
my_unicode_lib.cpp:(.text+0x83): undefined reference to `icu_73::Locale::getUS()'
/usr/bin/ld: my_unicode_lib.cpp:(.text+0x8e): undefined reference to `icu_73::Locale::Locale(icu_73::Locale const&)'
/usr/bin/ld: my_unicode_lib.cpp:(.text+0xa3): undefined reference to `icu_73::Collator::createInstance(icu_73::Locale const&, UErrorCode&)'
/usr/bin/ld: my_unicode_lib.cpp:(.text+0x17a): undefined reference to `icu_73::Locale::~Locale()'
/usr/bin/ld: ~/.conan2/p/my_un12ff040403516/p/lib/libuni.a(my_unicode_lib.cpp.o): in function `my_unicode_lib() [clone .cold]':
my_unicode_lib.cpp:(.text.unlikely+0x4): undefined reference to `icu_73::Locale::~Locale()'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/example.dir/build.make:98: example] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/example.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

ERROR: my_unicode_lib/0.1 (test package): Error in build() method, line 18
        cmake.build()
        ConanException: Error 2 while executing
```

I'm sure there's another small thing I'm missing, but I'm having trouble finding it. Thanks again.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by cubisttriangle** [comment]
I should also mention that I'm able to get around this by adding a `find_package` dependency on `icu` to the test_package `CMakeLists.txt`, but I wasn't expecting to need that.

**Comment by cubisttriangle** [comment]
Figured it out! Took me a while to get the naming right, but I needed to add the dependency to the component with:
```
self.cpp_info.components["uni"].requires = ["icu::icu-i18n"]
```

**Comment by memsharded** [comment]
Yes, that is correct. When you define components, it is needed to define the relations to those components and dependencies, so the downstream consumers can know what components need to be linked.

Is this questions solved then, could we close it? Thanks!

**Comment by cubisttriangle** [comment]
Thanks. Yep - good to close.
