### ISSUE TITLE
[question] Param reference was removed from conan create?

### ISSUE THREAD

**Issue by onlyou2030** [conan-io/conan#13893]
### What is your question?

With conan 2.0.2, how can I set the reference after name and version as followers:
helle/1.0@user/channel

It seems not work any more: conan create . user/channel -s build_type=Release

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @onlyou2030 thanks for your question.

I'm not quite sure if I understand your question, so feel free to correct me, but if what you want is to set the user and channel attributes when calling `conan create`, [it's as easy as using the `--user` and `--channel` arguments](https://docs.conan.io/2/reference/commands/create.html?highlight=[--name%20NAME]%20[--version%20VERSION]). 

So for your example, change it to look something like: 

`conan create . --user=user --channel=channel -s build_type=Release`

Note that you can set `name` and `version` this way too so there would be no need to specify those in the recipe itself too :)

Let me know if I can help you with anything else

**Comment by onlyou2030** [comment]
> Hi @onlyou2030 thanks for your question.
> 
> I'm not quite sure if I understand your question, so feel free to correct me, but if what you want is to set the user and channel attributes when calling `conan create`, [it's as easy as using the `--user` and `--channel` arguments](https://docs.conan.io/2/reference/commands/create.html?highlight=%5B--name%20NAME%5D%20%5B--version%20VERSION%5D).
> 
> So for your example, change it to look something like:
> 
> `conan create . --user=user --channel=channel -s build_type=Release`
> 
> Note that you can set `name` and `version` this way too so there would be no need to specify those in the recipe itself too :)
> 
> Let me know if I can help you with anything else

@RubenRBS You've really helped me a lot. Thanks~

**Comment by AbrilRBS** [comment]
Great to hear! Closing this as answered, feel free to open a new issue should you have any other questions :)
