### ISSUE TITLE
[bug] test_requires dependency that is also a transient dependency causes an error if it is not present in component requires 

### ISSUE THREAD

**Issue by bmwrightson** [conan-io/conan#13892]
### Environment details

* Operating System+version: Win 11
* Compiler+version: msvc 192
* Conan version: 2.0.4
* Python version: 3.10.10

There appears to be a bug that (may be an edge case of https://github.com/conan-io/conan/issues/13187) that results in conan wanting a test_requires to be specified as a component requirement in the case where that same dependency is a transient requirement of another required lib.

e.g.
    libc requires(libb) and test_requires(liba)
    AND libb requires(liba)

This then seems to lead to liba being promoted from test_requires() to requires() when creating the dependency graph for libc, which is then used as a reason for needing to explicitly state which component requires liba.

I believe this is a bug - none of libc's components explicitly require liba and so should not have to list it as a requirement for any component (libb is listed a requirement and it will bring in liba if it needs it). If I remove liba as a test_requires then I no longer need to specify it as a component requires, even though nothing about the requirements of the component have changed.

Note: in the logs that liba is listed in "Requirements" not "Test requirements" even though it is specified as test_requires in the conanfile.py

### Steps to reproduce

Create 3 new conan packages (liba libb and libc) using conan new and apply the attached patches to libb and libc:

mkdir liba
cd liba
conan new -d name=liba -d version=0.1.0 cmake_lib
conan create .
cd ..
mkdir libb
cd libb
conan new -d name=libb -d version=0.1.0 cmake_lib
git apply ../libb.patch
conan create .
cd ..
mkdir
 libc
cd libc
conan new -d name=libc -d version=0.1.0 cmake_lib
git apply ../libc.patch
conan create .

[libb.patch](https://github.com/conan-io/conan/files/11473116/libb.patch)
[libc.patch](https://github.com/conan-io/conan/files/11473117/libc.patch)

### Logs

======== Exporting recipe to the cache ========
libc/0.1.0: Exporting package recipe: C:\dev\libc\conanfile.py
libc/0.1.0: Copied 1 '.py' file: conanfile.py
libc/0.1.0: Copied 1 '.txt' file: CMakeLists.txt
libc/0.1.0: Copied 1 '.h' file: libc.h
libc/0.1.0: Copied 2 '.cpp' files: libc.cpp, libc_test.cpp
libc/0.1.0: Exported to cache folder: C:\dev\conan2_cache\libc2f6259e73bad7\e
libc/0.1.0: Exported: libc/0.1.0#75a84f32c4aa0d8ee56b8a9ede7c9eb6 (2023-05-14 22:51:54 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[conf]
tools.cmake.cmaketoolchain:generator=Ninja

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[conf]
tools.cmake.cmaketoolchain:generator=Ninja

======== Computing dependency graph ========
Graph root
    cli
Requirements
    liba/0.1.0#c0fc77e47d8c9e7a1e209fc5b7504a45 - Cache
    libb/0.1.0#fb1e217fe2509bc92df684d72968c334 - Cache
    libc/0.1.0#75a84f32c4aa0d8ee56b8a9ede7c9eb6 - Cache
Test requirements
    gtest/cci.20210126#dafbdf84b58cd687075ace7314651c1a - Cache

======== Computing necessary packages ========
gtest/cci.20210126: Checking 2 compatible configurations:
gtest/cci.20210126: 'c64a7bbade0edef3ad4ab3f016562e5d605e7838': compiler.cppstd=14
gtest/cci.20210126: Main binary package '9e3e3a321fe831e5423e0d46ff8f9759d6dff3f9' missing. Using compatible package 'c64a7bbade0edef3ad4ab3f016562e5d605e7838'
libc/0.1.0: Forced build from source
Requirements
    liba/0.1.0#c0fc77e47d8c9e7a1e209fc5b7504a45:dfa8c31b225ffb8dfcf6a48ffd071f448777ae71#124c8e90e081fa18623b29c9f9362587 - Cache
    libb/0.1.0#fb1e217fe2509bc92df684d72968c334:b327c487bb01bb60a2be490d15d2ecb2684ef363#69e3832a8f9765ed459bb43a73cfda12 - Cache
    libc/0.1.0#75a84f32c4aa0d8ee56b8a9ede7c9eb6:a867d24ce2a2363a39178a14bc38381861d3107a - Build
Test requirements
    gtest/cci.20210126#dafbdf84b58cd687075ace7314651c1a:c64a7bbade0edef3ad4ab3f016562e5d605e7838#e3c5ed9e8ce7711622d2ab62f805c01d - Cache

======== Installing packages ========
gtest/cci.20210126: Already installed! (1 of 4)
liba/0.1.0: Already installed! (2 of 4)
libb/0.1.0: Already installed! (3 of 4)

-------- Installing package libc/0.1.0 (4 of 4) --------
libc/0.1.0: Building from source
libc/0.1.0: Package libc/0.1.0:a867d24ce2a2363a39178a14bc38381861d3107a
libc/0.1.0: Copying sources to build folder
libc/0.1.0: Building your package in C:\dev\conan2_cache\t\libc8a265c0e349e3\b
libc/0.1.0: Calling generate()
libc/0.1.0: Generators folder: C:\dev\conan2_cache\t\libc8a265c0e349e3\b\build\Release\generators
libc/0.1.0: CMakeToolchain generated: conan_toolchain.cmake
libc/0.1.0: CMakeToolchain generated: CMakePresets.json
libc/0.1.0: CMakeToolchain generated: ..\..\..\CMakeUserPresets.json
libc/0.1.0: Generating aggregated env files
libc/0.1.0: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
libc/0.1.0: Calling build()
libc/0.1.0: Running CMake.configure()
libc/0.1.0: RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="C:/dev/conan2_cache/t/libc8a265c0e349e3/b/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/dev/con
an2_cache/t/libc8a265c0e349e3/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\dev\conan2_cache\t\libc8a265c0e349e3\b\."
conanvcvars.bat: Activating environment Visual Studio 16 - amd64 - vcvars_ver=14.2
[vcvarsall.bat] Environment initialized for: 'x64'
-- Using Conan toolchain: C:/dev/conan2_cache/t/libc8a265c0e349e3/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 17 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The CXX compiler identification is MSVC 19.29.30147.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'libb::libb'
-- Conan: Target declared 'liba::liba'
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091

-- Build files have been written to: C:/dev/conan2_cache/t/libc8a265c0e349e3/b/build/Release

libc/0.1.0: Running CMake.build()
libc/0.1.0: RUN: cmake --build "C:\dev\conan2_cache\t\libc8a265c0e349e3\b\build\Release" -- -j32
conanvcvars.bat: Activating environment Visual Studio 16 - amd64 - vcvars_ver=14.2
[vcvarsall.bat] Environment initialized for: 'x64'
[2/2] Linking CXX static library libc.lib

libc/0.1.0: Package 'a867d24ce2a2363a39178a14bc38381861d3107a' built
libc/0.1.0: Build folder C:\dev\conan2_cache\t\libc8a265c0e349e3\b\build\Release
libc/0.1.0: Generating the package
libc/0.1.0: Temporary package folder C:\dev\conan2_cache\t\libc8a265c0e349e3\p
libc/0.1.0: Calling package()
libc/0.1.0: Running CMake.install()
libc/0.1.0: RUN: cmake --install "C:\dev\conan2_cache\t\libc8a265c0e349e3\b\build\Release" --prefix "C:/dev/conan2_cache/t/libc8a265c0e349e3/p"
conanvcvars.bat: Activating environment Visual Studio 16 - amd64 - vcvars_ver=14.2
[vcvarsall.bat] Environment initialized for: 'x64'
-- Install configuration: "Release"
-- Installing: C:/dev/conan2_cache/t/libc8a265c0e349e3/p/lib/libc.lib
-- Installing: C:/dev/conan2_cache/t/libc8a265c0e349e3/p/include/libc.h

libc/0.1.0: package(): Packaged 1 '.h' file: libc.h
libc/0.1.0: package(): Packaged 1 '.lib' file: libc.lib
libc/0.1.0: Created package revision ec26e25aa953d4b9791d99a2c569ebab
libc/0.1.0: Package 'a867d24ce2a2363a39178a14bc38381861d3107a' created
libc/0.1.0: Full package reference: libc/0.1.0#75a84f32c4aa0d8ee56b8a9ede7c9eb6:a867d24ce2a2363a39178a14bc38381861d3107a#ec26e25aa953d4b9791d99a2c569ebab
libc/0.1.0: Package folder C:\dev\conan2_cache\libc0d017bc2a9bb5\p
ERROR: libc/0.1.0: Required package 'liba' not in component 'requires'

**Comment by memsharded** [comment]
Hi @bmwrightson 

Thanks for your report, I am checking it.

Some quick feedback, there is the ``conan new cmake_lib -d name=pkg -d version=0.1 -d requires=other/1.0``, and it will create the basic the dependency code in conanfile.py, CMakeLists.txt and source code.

**Comment by memsharded** [comment]
I have been checking the dependency graph that you reported, and it seems a bit challenging at the moment to fix it, because the information is being collapsed so it is not possible to differentiate between the direct test_requires and the indirect requires.

Also, it would be good to know the actual names of the libraries. How is a test_requires also a regular requires? In general test_requires as ``gtest`` or ``catch2`` will never be used as regular requires. The graph you are defining is not that common, that is likely the reason this has not been raised before.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/13898 has fixed this for next Conan 2.0.5

**Comment by bmwrightson** [comment]
FYI: The libraries are all internal ones. Basically liba is a low level utility library that is used in some other libraries but in libc's case it is only used to in some unit tests but not used otherwise in the production code of libc.
