### ISSUE TITLE
[feature] support customizing CMakeToolchain's blocks from toolchain packages

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#13896]
### What is your suggestion?

I'm trying to make my own `android-ndk` package, based on the [official one](https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/conanfile.py), but with a different build of libc++ with unstable ABI.

I'm using conan v2.0.4.

The idea is the following:

- I created a `settings_user.yml` to be distributed to my team that contains an additional `libc++` library for `clang`:

```yaml
    clang:
        version: ["14.0.7"]
        link_time_optimization: [null, "enabled"]
        libcxx: ["libc++v2", "ms_stl"]
```

I've created my own `conanfile.py` for `android-ndk`, which is mainly based on the [official one](https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/conanfile.py), but has additional part in `package_info` that defines correct compile and link flags when using custom libc++. It looks like this:

```python
def package_info(self):
    # mainly the same as in the official conanfile.py
    libcxx_str = str(self.settings_target.compiler.libcxx)
    if libcxx_str.startswith("c++_"):
        self.buildenv_info.define("ANDROID_STL", libcxx_str)
        self.conf_info.update(custom_cmake_options_key, {'MB_ANDROID_USE_CUSTOM_STL': 'OFF'})
    elif libcxx_str == "libc++v2":
        self.buildenv_info.define("ANDROID_STL", "c++_static")
        self.conf_info.update(custom_cmake_options_key, {'MB_ANDROID_USE_CUSTOM_STL': 'ON'})

        mb_stl_cxx_flags = [
            '-nostdinc++',
             f'-isystem {os.path.join(self._ndk_root, "sysroot", "usr", "include", "c++", "v1")}'
         ]
         self.conf_info.append('tools.build:cxxflags', mb_stl_cxx_flags)
         self.cpp_info.cxxflags.extend(mb_stl_cxx_flags)

         mb_stl_link_flags = [
             '-nostdlib++',
             f'{self.package_folder}/mb-stl/{self._android_abi}/libc++.a',
             f'{self.package_folder}/mb-stl/{self._android_abi}/libc++abi.a'
         ]
         self.conf_info.append('tools.build:sharedlinkflags', mb_stl_link_flags)
         self.conf_info.append('tools.build:exelinkflags', mb_stl_link_flags)
         self.cpp_info.exelinkflags.extend(mb_stl_link_flags)
         self.cpp_info.sharedlinkflags.extend(mb_stl_link_flags)

         mb_stl_defines = [
             '_LIBCPP_ABI_VERSION=2',
             '_LIBCPP_ABI_UNSTABLE=1'
         ]
         self.conf_info.append('tools.build:defines', mb_stl_defines)
         self.cpp_info.defines.extend(mb_stl_defines)
     else:
         self.buildenv_info.define("ANDROID_STL", "c++_shared")
         self.conf_info.update(custom_cmake_options_key, {'MB_ANDROID_USE_CUSTOM_STL': 'OFF'})
```

However, this doesn't work with `CMakeToolchain`, as it generates the following lines in `conan_toolchain.cmake`:

```cmake
# New toolchain things
set(ANDROID_PLATFORM android-21)
set(ANDROID_STL libc++v2)
set(ANDROID_ABI arm64-v8a)
set(ANDROID_USE_LEGACY_TOOLCHAIN_FILE OFF)
include(/Users/dodo/.conan2/p/androfd7e8e79ffe33/p/build/cmake/android.toolchain.cmake)
```

This then fails because `Android-Platform.cmake` from CMake validates `ANDROID_STL` for invalid inputs. The same happens if I try using the legacy toolchain (the validation then happens in the `android-legacy.toolchain.cmake`, but the problem is the same).

The solution is to modify the `android_system` block in the consumer's `generate` function, like this:

```python
    def generate(self):
        tc = CMakeToolchain(self)
        if self.settings.get_safe('compiler.libcxx') == 'libc++v2':
            tc.blocks['android_system'].values['android_stl'] = 'c++_static'

        tc.generate()
```

However, this requires changes to consumer packages, meaning that I can't simply use my toolchain package to cross-build packages from conan-center without forking them and changing their `generate` method.

It would be cool if I could affect the `CMakeToolchain's android_sytem` block directly from the `android-ndk's` `package_info` method.

Actually, it would be cool if I could affect any CMake variable in downstream's `CMakeToolchains` from `package_info` method of my toolchain package. As you can see above, I'm currently using a custom `conf` key for that, since currently I need it to only affect my own packages, which have a custom `generate` method that understands that specific `conf` key. However, one can argue that propagating CMake flags from toolchain packages should be left for teams to customize as they can't affect packages from the conan center. However, the case above affects even packages from the conan center.

Is it possible to add that feature?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DoDoENT 

Thanks for your suggestion.
What you are suggesting seems at this moment quite complicated. 

The main mechanism for customizating the behavior of consumers is by injection of complete cmake toolchain files, via the conf ``tools.cmake.cmaketoolchain:user_toolchain``, which it seems you are already using.

If the main issue that causes the consumers to need modifications is the change in libcxx, have you considered defining your variation with a libcxx subsetting, something like?
```yaml
libcxx:
     c++_static:
         variants: ["v2", "othervariant_v3",....]
```

**Comment by DoDoENT** [comment]
> If the main issue that causes the consumers to need modifications is the change in libcxx, have you considered defining your variation with a libcxx subsetting, something like?

This appears to work but with some caveats:

First, I added a `null` option to support regular `c++_static`, like this:

```yaml
        libcxx:
            ms_stl:
            c++_static:  
                version: [null, 2]
```

Then, when I add `compiler.libcxx.version=2` in my Android profile, everything works as expected. However, I also wanted to test whether I can still use the original `c++_static`, so I issued the following command:

```
(conan2-venv) [dodo@nm-nmiksa: android (conan-v2)]$ conan test ./test_package android-ndk/r25c@microblink/stable --profile android-ndk-r25c-arm64-v8a -s build_type=Release -s compiler.libcxx.version=None
ERROR: Invalid setting 'None' is not a valid 'settings.compiler.libcxx.version' value.
Possible values are ['2']
Read "http://docs.conan.io/2/knowledge/faq.html#error-invalid-setting"
```

It didn't work also with `-s compiler.libcxx.version=null`. Apparently, there is no way to "unset" the setting from the command line. I have to do it in a profile. I don't know if this is a feature or a bug.

The second caveat is the way I need to check in the recipe whether `c++_static.version` exists or not. At first, I wrote this:

```python
        libcxx_version = self.settings_target.compiler.libcxx.version
        self.output.info(f"libcxx version is {libcxx_version}")
        if libcxx_version is None:
            self.output.info("Using standard libc++")
        else:
            self.output.info("Using custom libc++")
```

The code above prints:

```
libcxx version is None
Using custom libc++
```

which is fully weird.

There are two "fixes" for this. The first one is to write like this:

```python
        libcxx_version = self.settings_target.compiler.libcxx.version
        self.output.info(f"libcxx version is {libcxx_version}")
        if libcxx_version == None:
            self.output.info("Using standard libc++")
        else:
            self.output.info("Using custom libc++")
```

However, if I write this, then Python linter complains about the violation of the E711 rule ("comparison to None should be 'if cond is None:').

An alternative, and probably most correct, fix is to write like this:

```python
        libcxx_version = self.settings_target.get_safe('compiler.libcxx.version')
        self.output.info(f"libcxx version is {libcxx_version}")
        if libcxx_version is None:
            self.output.info("Using standard libc++")
        else:
            self.output.info("Using custom libc++")
```

The `get_safe` function [has been documented](https://docs.conan.io/2/reference/conanfile/attributes.html#settings) as something to be used for accessing values that may not exists, which is the case here. However, the documentation states that directly accessing non-existing settings will make Conan fail, which didn't happen here.

Maybe documentation can be improved with an example similar to this one?

All in all, thank you for your help 😃
