### ISSUE TITLE
CONAN_COMPILER_VERSION is undefined with CMake 3.4 and VS 2015

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#139]
I upgraded to Conan 0.7 today on my Windows machine. I ran ``conan install`` again and then ``Generate`` in the CMake GUI. CMake fails in ``conanbuildinfo.cmake`` like this:
```
CMake Error at C:/dev/build/tyroxx-blog-generator-vs2015-conan/conanbuildinfo.cmake:152 (if):
  if given arguments:

    "(" "STREQUAL" "14" "AND" "NOT" "19" "STREQUAL" "19" ")" "OR" "(" "STREQUAL" "12" "AND" "NOT" "19" "STREQUAL" "18" ")" "OR" "(" "STREQUAL" "11" "AND" "NOT" "19" "STREQUAL" "17" ")" "OR" "(" "STREQUAL" "10" "AND" "NOT" "19" "STREQUAL" "16" ")" "OR" "(" "STREQUAL" "9" "AND" "NOT" "19" "STREQUAL" "15" ")" "OR" "(" "STREQUAL" "8" "AND" "NOT" "19" "STREQUAL" "14" ")" "OR" "(" "STREQUAL" "7" "AND" "NOT" "19" "STREQUAL" "13" ")" "OR" "(" "STREQUAL" "6" "AND" "NOT" "19" "STREQUAL" "12" ")"

  Unknown arguments specified
Call Stack (most recent call first):
  C:/dev/build/tyroxx-blog-generator-vs2015-conan/conanbuildinfo.cmake:178 (CHECK_COMPILER_VERSION)
  C:/dev/build/tyroxx-blog-generator-vs2015-conan/conanbuildinfo.cmake:81 (conan_check_compiler)
  CMakeLists.txt:40 (conan_basic_setup)
```

This is the relevant piece of CMake code:
```CMake
if( (${CONAN_COMPILER_VERSION} STREQUAL "14" AND NOT ${VERSION_MAJOR} STREQUAL "19") OR
            (${CONAN_COMPILER_VERSION} STREQUAL "12" AND NOT ${VERSION_MAJOR} STREQUAL "18") OR
            (${CONAN_COMPILER_VERSION} STREQUAL "11" AND NOT ${VERSION_MAJOR} STREQUAL "17") OR
            (${CONAN_COMPILER_VERSION} STREQUAL "10" AND NOT ${VERSION_MAJOR} STREQUAL "16") OR
            (${CONAN_COMPILER_VERSION} STREQUAL "9" AND NOT ${VERSION_MAJOR} STREQUAL "15") OR
            (${CONAN_COMPILER_VERSION} STREQUAL "8" AND NOT ${VERSION_MAJOR} STREQUAL "14") OR
            (${CONAN_COMPILER_VERSION} STREQUAL "7" AND NOT ${VERSION_MAJOR} STREQUAL "13") OR
            (${CONAN_COMPILER_VERSION} STREQUAL "6" AND NOT ${VERSION_MAJOR} STREQUAL "12") )
            ERROR_COMPILER_VERSION()
        endif()
```

You can conclude that ``CONAN_COMPILER_VERSION`` is empty or not defined. Everything works if I define ``CONAN_COMPILER_VERSION`` to ``14`` in the CMake GUI. This was not necessary in Conan 0.6. Am I doing something wrong here or is this a bug in Conan?

**Comment by memsharded** [comment]
Certainly a bug, sorry for it. While we release a patch for it, probably the easiest workaround would be to replace the call for

```cmake
conan_basic_setup()
```

by
```cmake
conan_output_dirs_setup()
conan_flags_setup()
set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_MODULE_PATH})
```
Which is basically the contents of the conan_basic_setup(), excluding the checks for compiler.

**Comment by memsharded** [comment]
Hi,
We have released 0.7.1 that should fix this problem. If you could check if your issue is resolved, please report back, thanks for pointing this issue!

**Comment by TyRoXx** [comment]
I installed Conan 0.7.2, ran ``conan install`` again and now CMake (3.4.1) says that:
```
C compiler:   C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
C++ compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
CMake Error at C:/dev/build/silicium-vs2015-conan/conanbuildinfo.cmake:122 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  C:/dev/build/silicium-vs2015-conan/conanbuildinfo.cmake:160 (conan_get_compiler)
  C:/dev/build/silicium-vs2015-conan/conanbuildinfo.cmake:53 (conan_check_compiler)
  CMakeLists.txt:92 (conan_basic_setup)


WARN: CONAN_COMPILER variable not set, please make sure yourself that your compiler and version matches your declared settings
Configuring incomplete, errors occurred!
```

**Comment by memsharded** [comment]
We have just released 0.7.2, it should fix these problems, could you try it please?

**Comment by memsharded** [comment]
I can't believe it is still failing :( Sorry for that, I go back to this issue again.

**Comment by memsharded** [comment]
I have investigated, and proposed a new PR: https://github.com/conan-io/conan/pull/151
The problem was that for header-only packages, as no settings are required, nothing was stored in conaninfo.txt, and the cmake code failed to load it. With this PR, I have been able to build your lib with:
```bash
$ git clone https://github.com/TyRoXx/silicium.git
$ cd silicium
$ conan install (my default is VS14, Release, 64 bits)
$ cmake -G "Visual Studio 14 Win64"
$ cmake --build . --config Release
```

Hopefully this is the good one, lets try to create a minor asap, If you have patience to keep reporting failures, we will not stop working until they are fixed. Thanks again for your patience and help.

**Comment by memsharded** [comment]
Released 0.7.3, including this fix. Hopefully this is the good one, but please tell us otherwise.

**Comment by TyRoXx** [comment]
I tried again with 0.7.4 and my problems are gone. Good job!

**Comment by memsharded** [comment]
Great! Thanks for telling and your patience, your feedback has been very useful to fix these problems. Cheers
