### ISSUE TITLE
[question] header_only child package has been skipped during the conan build of the grand-parent package ?

### ISSUE THREAD

**Issue by selim-pousse** [conan-io/conan#13900]
### What is your question?

Hi, I have question regarding the computing necessary packages done implicitly by conan 2 :

Assuming this following hierarchical dependencies :

```
LibGrandParent
 ├── LibParent1
 |    ├── LibChild1 (header_only)
 |    └── LibChild2 
 └── LibParent2
      └── LibChild1 (header_only)
```
      
Why the libChild1 has been skipped by conan during the computing necessary packages step of **LibGrandParent** when the `conan build` is executed as shown on the folowing logs ? 

```
+ conan build /home/conan/ws/CommonLibs/LibGrandParent/recipe --user pis --channel beta -o pack_variety=full -o hw_role=PSC -o 'libmqttobjectlayer/*:header_only=False' -s build_type=Release -pr:h aarch64-linux-gnu -pr:b x86_64-linux-musl

======== Computing dependency graph ========
Graph root
    conanfile.py (LibGrandParent/4.0.2@pis/beta): /home/conan/ws/CommonLibs/LibGrandParent/recipe/conanfile.py
Requirements
    LibChild1/0.0.1@pis/beta#0fa9a3d9dc604f3bb37ff9b67d4789f6 - Cache
    LibParent2/4.1.2@pis/beta#e02102515f949897bb3c380ecf92ed7d - Cache
    LibParent1/2.6.4@pis/beta#22191fb6a30f8b5649e04b7b54920775 - Cache
    LibChild2/1.3.10@pis/beta#36f72c74c84e66e8a0c995021de5667a - Cache
Python requires
    recipebase/0.0.1@pis#fa03aa2766f93a3ba65329395ac88f3e - Cache

======== Computing necessary packages ========
Requirements
    LibChild1/0.0.1@pis/beta#0fa9a3d9dc604f3bb37ff9b67d4789f6:d9d59402e493bac2e3512f785a64df95b691ad0a#2d3578bb9a5985d14254a9313d0f57cf - Skip
    LibParent2/4.1.2@pis/beta#e02102515f949897bb3c380ecf92ed7d:7a0fa2b0e31cd95a1c9d0fd4a301e89eb5660513#fd14eaaca149087de7e71d0765ae09cb - Cache
    LibParent1/2.6.4@pis/beta#22191fb6a30f8b5649e04b7b54920775:a73b2696971ecf2b560a49b02a41837440c15173#d15844818767d0171dd11d0d010742f3 - Cache
   LibChild2/1.3.10@pis/beta#36f72c74c84e66e8a0c995021de5667a:c88c19eea539206951cd9f7e2f025117833f5d94#2dee5e1dbfbf1ed1c4f600921f14e73c - Cache

======== Installing packages ========

======== Installing packages ========
LibChild2/1.3.10@pis/beta: Already installed! (1 of 3)
LibParent1/4.1.2@pis/beta: Already installed! (2 of 3)
LibParent2/2.6.4@pis/beta: Already installed! (3 of 3)
```

How can I avoid this skip of libChild1 which contains only headers and cmakefiles but necessary for me when I'm looking for them with CMAKE ?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @selim-pousse 

Thanks for your question.
I am afraid there is no enough information in your report to know what is happening.
It would be necessary to see the ``conanfile.py`` recipes of the packages involved

In general a ``header-only`` library when consumed by another library will be considered that it is used as implementation detail of the other libraries, and such will not be propagated downstream. That means that if LibParent1 and LibParent2 already have existing binaries, the LibChild1 is really not necessary, and it is fine to "Skip" it. If the headers of LibChild1 are included in the public headers of LibParentX, then it should be required as ``self.requires("lib_child1/1.0", transitive_headers=True)``

**Comment by selim-pousse** [comment]
Hi @memsharded,

thank a lot for your answer, you send me to the right track. I missed somehow to learn this concept of transitivity (https://www.youtube.com/watch?v=kKGglzm5ous&t=2439s&ab_channel=ACCUConference). 
It works now as expected.
