### ISSUE TITLE
folder path when copying file to package folder

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#13903]
### What is your question?

The following variable was defined in the generate method so I could create the directory and copy some build related files to the package folder when finished running he build method.

_genFolder = os.path.join(self.build_folder, "generated" ) 

When the package method ran the value of _genFolder indicated
C:/Users/bq824/.conan2/p/t/cstar705f25c0edba3/b/generated

This path points to the temp build directory. Is this ok or should this path actually point to the actual build folder and not the temp build folder  while running the package method?
_

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
When the ``package()`` method executes, it needs to go to the temporary build folder. This is the whole process to build and package from source:

- A temporary "t" folder is created in the cache.
- The build happens in a "t" subfolder
- When the build finishes the ``package()`` is called to extract the artifacts from that "t" folder
- When the final package is created, its revision is computed
- Then everything is moved to the final location, both build and package folders

In any case, this is going to change in Conan 2.0.5 with some improvement that will leave the build and package folder in their location, without any further movement. This helps to support better the debugging (step-into dependencies), as well as supporting some use cases for non-relocatable packages (``upload_policy = "skip"``)

**Comment by Ed-CMI** [comment]
Thx Diego.
