### ISSUE TITLE
[feature] `options` on `ConanFile` is "wierd"

### ISSUE THREAD

**Issue by nrbnlulu** [conan-io/conan#13910]
### What is your suggestion?

Options are handled in a **very** non-Pythonic way.
1. not only that it is untyped, it also changes its type to `Options` at runtime (like many other conan file hacks).
2. it is useless to define both options and then repeat yourself with default_options

much more simpler solution would be to use something like dataclass or pydantic model if you need serialization.
i.e
```python
from conan import BaseOption

@dataclasses.dataclass
class MyRecipeOptions(BaseOption):
    testing: bool = False
    shared: bool = False
    verbose: bool = False
    qt_version: str = "6.5.0"

class MyRecipe(ConanFile):
    options = MyRecipeOptions()

```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nrbnlulu 

We are aware of this. It is rooted on the fact that many Conan users know very little Python, so having the simplest structures when possible is desired. Requiring things like ``dataclass`` just adds more overhead.
There are also other considerations to take into account, like serialization is indeed needed, but we try not to add new Python dependencies, and at the moment things like ``pydantic`` are not planned to be added. Every added Python dependency is an extra liability and complexity for users, potentially causing more conflicts at ``pip install conan`` time (many users don't really use virtualenvs, even if we strongly suggest it).

Also, while not very Pythonic, it is so widespread and massively used that changing it would be such a huge effort, that it is not worth it. If it was very problematic in practice, we would consider other approaches, but in practice the feature is working well for users. Thanks for your feedback anyway!

**Comment by nrbnlulu** [comment]
@memsharded 
> Also, while not very Pythonic, it is so widespread and massively used that changing it would be such a huge effort

I would argue that it would be a huge effort, there is no need to deprecate the current approach, you can just 
map the dataclass fields to whatever you are doing rn...

 > but we try not to add new Python dependencies 

 As I said this can be optional... but even if not, it is not so hard to craft something from dataclasses which is a Python standard library.

**Comment by memsharded** [comment]
Having multiple ways to do the same thing has always been problematic, confusing for users, requiring duplicate documentation, duplicate testing, duplicate support, duplicate maintenance (there will always be new corner cases, bugs, new feature-requests, etc).

And yes, things are not necessary hard. It is the accumulated sum of thousands of small things that kills the project time and resources. So we really prefer not to introduce new stylistic things like this one unless they solve a very specific functional problem or pain (a C and C++ packaging problem). As I commented, there is no evidence this is a users actual pain, maybe it is not the most beautiful or pythonic, but definitely not a users pain.

**Comment by nrbnlulu** [comment]
:upside_down_face: Fair enough, If you will be willing to add support for this kind of things ping me here, I can try to contribute.

**Comment by nrbnlulu** [comment]
for starters you can provide something like 
```py
ConanBool = [True, False]

class MyRecipe(ConanFile):
    options = {"shared": ConnanBool }
```
Which is more understandable by users who don't know python
