### ISSUE TITLE
[bug] Android Studio tutorial example fails to compile, cannot find zlibVersion()

### ISSUE THREAD

**Issue by troeggla** [conan-io/conan#13912]
### Environment details

* Operating System+version: macOS Ventura 13.1 (M1)
* Compiler+version:
  - Android NDK 25.1.8937393 with clang 14.0.6
  - Android SDK 26
  - Android Studio 2022.2.1 Patch 1
  - Kotlin 1.8.0
* Conan version: 2.0.4
* Python version: 3.11.3

### Steps to reproduce

1. Follow tutorial at https://docs.conan.io/2/examples/cross_build/android/android_studio.html
2. I did have to change the paths in `conan_android_toolchain.cmake` to include the build type, otherwise cmake wouldn't find them, e.g. `include("${CMAKE_CURRENT_LIST_DIR}/build/armv7/generators/conan_toolchain.cmake")` becomes `include("${CMAKE_CURRENT_LIST_DIR}/build/armv7/Debug/generators/conan_toolchain.cmake")`
3. The install task completes successfully and `zlib` becomes available in `~/.conan2/p/`. The headers also become available in Android Studio, i.e. there are no syntax errors in `native-lib.cpp`
4. Run the application. Compilation fails with linker error `ld: error: undefined symbol: zlibVersion`

### Logs

```
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/Users/tom/Projects/AndroidStudioProjects/MyConanApplication/app/.cxx/Debug/3gt3r4a3/arm64-v8a'
  [1/1] Linking CXX shared library /Users/tom/Projects/AndroidStudioProjects/MyConanApplication/app/build/intermediates/cxx/Debug/3gt3r4a3/obj/arm64-v8a/libmyconanapplication.so
  FAILED: /Users/tom/Projects/AndroidStudioProjects/MyConanApplication/app/build/intermediates/cxx/Debug/3gt3r4a3/obj/arm64-v8a/libmyconanapplication.so 
  : && /Users/tom/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android26 --sysroot=/Users/tom/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++14 -fno-limit-debug-info  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--gc-sections -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libmyconanapplication.so -o /Users/tom/Projects/AndroidStudioProjects/MyConanApplication/app/build/intermediates/cxx/Debug/3gt3r4a3/obj/arm64-v8a/libmyconanapplication.so CMakeFiles/myconanapplication.dir/native-lib.cpp.o  /Users/tom/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/aarch64-linux-android/26/liblog.so  -latomic -lm && :
  ld: error: undefined symbol: zlibVersion
  >>> referenced by native-lib.cpp:10 (/Users/tom/Projects/AndroidStudioProjects/MyConanApplication/app/src/main/cpp/native-lib.cpp:10)
  >>>               CMakeFiles/myconanapplication.dir/native-lib.cpp.o:(Java_com_lichtfragmente_myconanapplication_MainActivity_stringFromJNI)
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
```

**Comment by troeggla** [comment]
Addendum: I tried the same setup on an Intel Mac and everything works as intended

**Comment by troeggla** [comment]
Another update: I've been able to narrow the issue down to the `externalNativeBuild` section under `defaultConfig` in `build.gradle`. Compilation fails only if I pass `cppFlags '-std=c++14'`. It works fine with `-std=c++11`,  `-std=c++17` or if I leave out the option altogether.

Not sure what to make of this. In theory I see the issue as resolved, but I still find it curious why it would fail with the c++14 option. Also, maybe the tutorial should be updated to reflect the inclusion of build_type in the paths in `conan_android_toolchain.cmake` (as mentioned under point 2 of 'Steps to reproduce')

**Comment by memsharded** [comment]
Hi @troeggla thanks for your report,

Yes, that is very curious, the ``c++14`` flag shouldn't affect at all to ``zlib``, as it is a C library, not a C++ one.
Also, no idea why the M1 architecture will produce a different behavior here, I fail to see how it could be affecting.

Agree it seems the docs might need an update. I am not sure if to transfer it to the ``docs`` repo, or wait until someone from the team can try to reproduce or investigate it a bit further (I don't have a Mac, so I can't do it).

**Comment by troeggla** [comment]
Thanks for looking into this! Out of curiosity, I tried the three flags on my Intel Mac and there it compiles just fine with either of them.

I will try to find another Silicon machine and see if I can reproduce the behaviour there or if it's just something weird with my setup.

**Comment by konradx64** [comment]
Hi, 
I also had problems as described above with the folder structure. However, another problem occurs with me. I get the message "Invalid character escape '\U'". In the file CMakeSystem.cmake the NDK path is about "C:\Users\[...]", but it should rather be "C:\Users\[...]" or "C:/Users/[...]". But I can't change this because it is generated anew each time. Even if I change the path in the profile file, nothing happens.

**Comment by DoDoENT** [comment]
Also, I'll add [this question here](https://stackoverflow.com/questions/76406426/how-to-modify-dependencies-of-appconfigurecmakedebugarm64-v8a-and-similar) so that the working answer to it can be used to improve the documentation.

But, as @troeggla said, the `conan_android_toolchain.cmake` needs to be modified to include the build type. Mine looks like this:

```cmake
# Implementation note:
# Toolchain file is processed multiple times during cmake configuration, and variables given from
# command line are not always available.
# If the required ones are unavailable, bail out and wait for the next processing.
#
if ( NOT ANDROID_ABI OR NOT CMAKE_BUILD_TYPE )
    return()
endif()
if( ${ANDROID_ABI} STREQUAL  "arm64-v8a" )
    include("${CMAKE_CURRENT_LIST_DIR}/build/armv8/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
elseif( ${ANDROID_ABI} STREQUAL "armeabi-v7a" )
    include("${CMAKE_CURRENT_LIST_DIR}/build/armv7/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
elseif( ${ANDROID_ABI} STREQUAL "x86_64" )
    include("${CMAKE_CURRENT_LIST_DIR}/build/x86_64/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
elseif( ${ANDROID_ABI} STREQUAL "x86" )
    include("${CMAKE_CURRENT_LIST_DIR}/build/x86/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
else()
    message(FATAL_ERROR "Not supported configuration")
endif()
```

**Comment by czoido** [comment]
> ```cmake
> # Implementation note:
> # Toolchain file is processed multiple times during cmake configuration, and variables given from
> # command line are not always available.
> # If the required ones are unavailable, bail out and wait for the next processing.
> #
> if ( NOT ANDROID_ABI OR NOT CMAKE_BUILD_TYPE )
>     return()
> endif()
> ```

Thanks @DoDoENT for reporting, I'll update the docs accordingly, it became obsolete after some changes in the `cmake_layout`.

@troeggla Could you reproduce the problems? I have been testing with C++14 and the fixes related to the layout in the toolchain and apparently everything works fine

**Comment by DoDoENT** [comment]
@czoido , feel free to use the stateful task from my [SO question](https://stackoverflow.com/questions/76406426/how-to-modify-dependencies-of-appconfigurecmakedebugarm64-v8a-and-similar). After the last change (see the EDIT part of the question) it works pretty good and avoids cmake reconfigurations every time a build/run is started from Android Studio.

The only problem I see with this solution is that it may be tied to the current version of the Android Gradle Plugin (v8 at the moment) - this is why I keep the question open. Hopefully, someone from [android](https://github.com/orgs/android/people) notices the question and provides a better solution that doesn't depend on reflection for task dependency injection.

**Comment by troeggla** [comment]
@czoido Thanks for checking this! I managed to test it on another M1 machine and there it seems fine as well. I'm pretty sure this was an issue with my setup.

I saw that the documentation is updated as well. I think this can be closed. Thanks for your help!
