### ISSUE TITLE
[question] how to create conan profile with specific compiler? 

### ISSUE THREAD

**Issue by captmors** [conan-io/conan#13916]
### What is your question?

I have msvc and gcc compiler. Conan detects first all the time and I want to use second. When I write:
conan profile detect --name []
it detects msvc all the time and show that it gcc 11.2 is found. How to detect gcc exactly? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @waitingsolong thanks for your question.
`conan profile detect` is meant as a convenience feature to be able to quickstart Conan usage. 

The recommended way is to manually create your `gcc` profile, maybe using the detected profile as a template and changing the necessary keys for your use-case.

**Comment by captmors** [comment]
> Hi @waitingsolong thanks for your question. `conan profile detect` is meant as a convenience feature to be able to quickstart Conan usage.
> 
> The recommended way is to manually create your `gcc` profile, maybe using the detected profile as a template and changing the necessary keys for your use-case.

but it literally writes Found gcc 11.2. It is no way to create profile for it and I need to find all settings by myself? That's sad

**Comment by AbrilRBS** [comment]
I misunderstood some of your question, though you wanted to edit most of the settings detected by the `detect` subcommand.

If you set `CC`/`CXX` env vars to the compiler you want to be detected, it will use those instead when detecting the compiler. Does that help?

**Comment by AbrilRBS** [comment]
Glad to see that it worked, feel free to open more issues should you have any other question :)
