### ISSUE TITLE
Avoid asking user and password

### ISSUE THREAD

**Issue by Pancir** [conan-io/conan#1392]
I have added more than one remote for my conan, and one of them needs user and password.
So when I try to install some dependencies  conan ask me the user and password for that repository, it is not always desired behavior for example for CI. It stops the task and waiting input but I actually don't need that repository for this task because I use only public repository for one. 
Can it be disabled with some additional argument? I would like only log information that the conan could not get access to some repositories because it unauthorized and I would like to avoid stopping the CI tasks.
Thank you.

**Comment by jacmoe** [comment]
See this:
[https://github.com/conan-io/conan-package-tools#working-with-bintray-configuring-repositories](https://github.com/conan-io/conan-package-tools#working-with-bintray-configuring-repositories)

**Comment by jacmoe** [comment]
Locally, you don't need to log in to anything other than your own Bintray remote.

Have you created a Bintray account and clicked the "set me up" button ?

**Comment by Pancir** [comment]
The problem is not with the bintray, Besides bintray repository we also have our own repository that is not public and that repository in conan's remote list too, so conan ask the user and password to our own repository every time, but actually for this certain project that repository is not needed. 
So for example if I have 10 private repository, I have to for each my project that uses conan, enter user name and password for those 10 repositories but what if this project actually does not need those 10 repositories?
The real situation is that my project uses only gtest from conan-center and nothing else and this project does not use anything from our own private repository, but I have to always enter user and password for our own private repository otherwise my CI task has stopped and waiting input.
BTW We have our own Jenkins server and use it, not travis or appveyor.

**Comment by memsharded** [comment]
I am not fully sure to understand the problem, but let me suggest different alternatives:
- If you are in CI, the correct approach is to remove (or not add) that remote. Remotes should be properly configured in CI as one of the initial steps of the job.
- Sometimes, it makes a lot of sense to upload dependencies to different repos, so you can get dependencies from one repo, upload them to another, so you might feel that using repos for projects can also help. For example, it is very typical (99% of companies do this), to get dependencies from the old conan.io (now conan-transit), and upload them to a company repo, so not depending on conan.io anymore.
- You could try to install packages from specific repositories first, using the ``-r myremote`` in an initial step, prior to launch the full job. Once the packages are in the local cache, the remotes won't be queried.

I'd certainly go for the first one, ensuring the correct remotes are in the correct order, is very good practice. Having other repos not needed for the job, is discouraged. Does this make sense? Please tell me, thanks!

**Comment by Pancir** [comment]
Thank you I think some kind of the first approach will help, I thought about it as workaround before. But I'm still going through different experiments.

**Comment by memsharded** [comment]
You are welcome. As it seems there is no action required on our side, I am closing the issue now, but if you have other question or need further details, please comment or re-open the issue. Thanks!
