### ISSUE TITLE
[Question] DuplicateOptionError Conan 1.60.0

### ISSUE THREAD

**Issue by ninamueller13** [conan-io/conan#13921]
### What is your question?

Dear Conan community,

I am working with Conan for the first time as part of a software development project. The software developer who provides the software I use recommends a Conan version released before v2.0.0. I installed v1.60.0 on Linux with the following command:

`sudo pip install -U "conan<2.0"`

After that I have made the configuration. 
In the next step I wanted to compile one of the samples which was also provided by the software developer. I received the following error message

`ERROR: while executing system_requirements(): System requirements: "libasound2, libasound2-dev" are missing but can´t install because tools.system.package_manager:mode is "check". Please update packages manually or set "tools.system.package_manager:mode" to "install" in the [conf] section of the profile, or in the command line using "-c tools.system.package_manager:mode=install"`

libasound2 and libasound2-dev are definitely installed and up to date.
The software manufacturer recommends adding the following lines to global.conf in case of this error

`tools.system.package_manager:mode=install`
`tools.system.package_manager:sudo=True`

Unfortunately, I cannot find a global.conf in version 1.60.0 and have not yet found any useful information on how to create one or in which path it should be stored. Therefore, I have tried to modify the global.conf accordingly

`[log]`
`run_to_output = True`
`run_to_file = False`
`level = critical`
`print_run_commands = False`

`[general]`
`default_profile = default`
`compression_level = 9`
`sysrequires_sudo = True`
`request_timeout = 60`
`default_package_id_mode = semver_direct_mode`
`revision_enabled = 1`

`[storage]`
`path = ./data`

`[proxies]`

`[hooks]`
`attribute_checker`

`[tools]`
`system.package_manager:mode = install`
`system.package_manager:sudo = True`

Unfortunately, when trying to compile the sample with this conan.conf, I get this error message

`raise DuplicateOptionError(sectname, optname, configparser.DuplicateOptionError: While reading from "/home/miti/.conan/conan.conf" [line 25]: option "system.package_manager" in section "tools" already exists`

I also tried to solve the problem with `unset`, but that didn't work either.
Unfortunately I don't know how to fix this problem, so I would be very grateful for tips on how to create the global.conf or how to adjust the conan.conf so that the compilation of the sample works. 

Thanks a lot!

n1n14

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @n1n14 

The ``global.conf`` file has to be created in the root of the cache. Then put the confs there, directly.

- Do not put ``conf`` like ``system.package_manager:mode = install`` in the ``conan.conf`` file, it doesn't work
- Put it in the ``global.conf`` file in the root of the cache
- Alternatively, you can put it in the ``[conf]`` section of your profile.
- Also, make sure to use the correct syntax, like ``tools.system.package_manager:mode=install``. All confs start with ``tools.``, ``core.`` or ``user.``

**Comment by czoido** [comment]
Sorry @n1n14 , I closed the issue by mistake, reopening it.

**Comment by ninamueller13** [comment]
Hi @memsharded 

creating a seperate `global.conf` totally solved this issue. Now I get a warning after building my sample which says

`WARN: Using the new toolchains and generators without specifying a build profile (e.g_ -pr:b=default) is discourage and might cause failures and unexpected behavior`

This confuses me because I configured the profile and registered it to a remote server. 
`conan profile new default --detect`

What is the difference between this and the build profile? Do I have to specify the build profile too?

Thank you!

n1n14

**Comment by memsharded** [comment]
Sure, read https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html for understanding the host/build profiles.

I know it is Conan 2.0 docs, but Conan 1.X also has both "build" and "host" profiles, and you should be using them, the warning is saying that, because in Conan 1.X it was not mandatory (Conan 2.0 always uses 2 profiles)

**Comment by memsharded** [comment]
Closing as responded, but please don't hesitate to re-open or create new tickets for any further question. Thanks for your feedback.
