### ISSUE TITLE
[bug] CMakeToolchain incorrectly sets the CMAKE_OSX_SYSROOT variable

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#13925]
### Environment details

* Operating System+version: MacOS Ventura 13.3.1
* Compiler+version: Xcode 14.3
* Conan version: 2.0.5
* Python version: 3.11.3

### Steps to reproduce

The generated `conan_toolchain.cmake` file contains following lines:

```cmake
# Setting CMAKE_OSX_SYSROOT SDK, when using Xcode generator the name is enough
# but full path is necessary for others
set(CMAKE_OSX_SYSROOT macosx CACHE STRING "" FORCE)
```

The line does not reflect the note from the comment, and this is problematic for non-Xcode generators, such as Ninja or "Ninja Multi-Config", as they then can't build code due to the error "no such sysroot directory: 'macosx' [-Wmissing-sysroot]".

**Comment by DoDoENT** [comment]
My local workaround for non-xcode generators is 

```cmake
if ( NOT XCODE )
    # workaround for https://github.com/conan-io/conan/issues/13925
    set( CMAKE_OSX_SYSROOT "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" CACHE STRING "" FORCE )
endif()
```

This location appears to be universal for all macs...

**Comment by memsharded** [comment]
I am having a look at this. 
The current implementation is:
```python
        host_sdk_name = self._conanfile.conf.get("tools.apple:sdk_path") or get_apple_sdk_fullname(self._conanfile)
       ...
        if host_sdk_name:
            ctxt_toolchain["cmake_osx_sysroot"] = host_sdk_name
```
So it will take the value from ``conf`` "tools.apple:sdk_path", and if not defined, will try to define as follow:
```python
def get_apple_sdk_fullname(conanfile):
    os_ = conanfile.settings.get_safe('os')
    os_sdk = conanfile.settings.get_safe('os.sdk')
    os_sdk_version = conanfile.settings.get_safe('os.sdk_version') or ""

    if os_sdk:
        return "{}{}".format(os_sdk, os_sdk_version)
    elif os_ == "Macos":  # it has only a single value for all the architectures
        return "{}{}".format("macosx", os_sdk_version)
    elif is_apple_os(conanfile):
        raise ConanException("Please, specify a suitable value for os.sdk.")
```

While the ``MesonToolchain`` and ``AutotoolsToolchain`` do automatically inject the full SDK path obtained with:
```python
def apple_sdk_path(conanfile):
    sdk_path = conanfile.conf.get("tools.apple:sdk_path")
    if not sdk_path:
        # XCRun already knows how to extract os.sdk from conanfile.settings
        sdk_path = XCRun(conanfile).sdk_path
    return sdk_path

sdk_path = apple_sdk_path(self._conanfile)
self.apple_isysroot_flag = "-isysroot {}".format(sdk_path) if sdk_path else None
```

Then, it seems that for other generators rather than ``Xcode``, the full path should be used too, instead of the short name?

The first step would be understanding why the ``test_locally_build_macos`` in ``test_ninja.py`` is working, what value of CMAKE_OSX_SYSROOT is using, etc. (by someone with a Mac)

**Comment by DoDoENT** [comment]
> Then, it seems that for other generators rather than Xcode, the full path should be used too, instead of the short name?

Most probably yes. I don't have any Meson or Autotools projects in my codebase to test it out.

> The first step would be understanding why the test_locally_build_macos in test_ninja.py is working, what value of CMAKE_OSX_SYSROOT is using, etc. (by someone with a Mac)

Are there any instructions on how to run this test locally?

**Comment by franramirez688** [comment]
I just checked it locally, and it's working correctly for Ninja too. Why? I think the `build.ninja` generated by CMake (CMake 3.26 in my case) is calling the `CMakeDetermineCompiler.cmake` file, which is running `xcrun --find macosx` internally, so that's the reason why it's working fine I guess. Looking at the `FLAGS` variable from this `build.ninja`, it's already resolved that path:
```
FLAGS = -m64 -stdlib=libc++ -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk
```
@DoDoENT I understand that it's not working fine in your local project, is it? Could it be due to your CMake version?

> Are there any instructions on how to run this test locally?

Have a look at this section: https://github.com/conan-io/conan#running-the-tests

UPDATED:

I've tested it with different versions (the latest CMake 3.26 and the minimum version required by CMakeToolchain CMake 3.15.5), even installed from Homebrew and the official CMake web page. The result is the same.

**Comment by DoDoENT** [comment]
> @DoDoENT I understand that it's not working fine in your local project, is it? Could it be due to your CMake version?

I'm using cmake 3.26.4, so it's not due to cmake version. I'm currently investigating what's different for my project. It happens with both `Ninja` and `Ninja Multi-Config`.

>  I think the build.ninja generated by CMake (CMake 3.26 in my case) is calling the CMakeDetermineCompiler.cmake file, which is running `xcrun --find macosx` internally

I've tried running `xcrun --find macosx` manually, and it resulted with:

```
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find macosx 2> /dev/null' failed with exit code 17664: (null) (errno=Invalid argument)
xcrun: error: unable to find utility "macosx", not a developer tool or in PATH
```

And if I try running the mentioned command directly:

```
$ /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find macosx
2023-06-20 13:11:51.655 xcodebuild[55363:6617038] Writing error result bundle to /var/folders/w1/67dfjvfs6sd66rd33brg4d5r0000gn/T/ResultBundle_2023-20-06_13-11-0051.xcresult
xcodebuild: error: 'macosx' not found.
```

The xcresult file, when opened with Xcode, also shows the same error.

It appears that `macosx` no longer exists. Are you using an Intel-based or M1-based Mac? What happens when you directly run these commands on your machine? Also, which version of Mac and Xcode are you using? I'm using Xcode 14.3 on MacOS Ventura 13.4.

**Comment by franramirez688** [comment]
Hi @DoDoENT 

My bad, sorry. I did not realize that that command is used to get the compiler, i.e., the correct one would be `xcrun --find clang`.
There is another `*.cmake` file named `Darwin-Initialize.cmake` which runs the good one. The command is `xcrun -sdk ${sdk} --show-sdk-path` -> `xcrun -sdk macosx --show-sdk-path`. This last one shows the correct SDK path `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk`.

> It appears that macosx no longer exists. Are you using an Intel-based or M1-based Mac? What happens when you directly run these commands on your machine? Also, which version of Mac and Xcode are you using? I'm using Xcode 14.3 on MacOS Ventura 13.4.

I'm using MacOS Ventura 13.4 Intel-based.

**Comment by DoDoENT** [comment]
`xcrun -sdk macosx --show-sdk-path` works and shows the correct path even on my system. Yet, `--sysroot macosx` is generated in `FLAGS` in my `build.ninja`.

> I'm using MacOS Ventura 13.4 Intel-based.

I tried also on one old Intel-based mac I have at hand, with cmake 3.24.2, and ninja didn't resolve the SDK path.

Now I know that it's something specific to my project. I just need to find what's different...

**Comment by DoDoENT** [comment]
OK, I found it.

Apparently, our code base had some workaround for CMake 3.5 + Ninja on Mac that caused problems with incorrectly detected sysroot, so the variable `CMAKE_OSX_SYSROOT` was unset. It's interesting why was then not empty, but set to `macosx`, as defined in the `conan_toolchain.cmake`. The workaround was dated to the year 2016.

All in all, thank you for your help. This is not a conan issue - I just need to clean up some workarounds for old cmake versions that are no longer needed in my codebase 😊 .

**Comment by memsharded** [comment]
Happy that you found the issue, thanks for the feedback!

**Comment by DerryMellon** [comment]
> 
I also encountered the same problem, can you tell me how you solved it?
I use cmake3.25.1, cmake could have correctly identified CMAKE_OSX_SYSROOT, but conan_toolchain.cmake forcibly changed this value to macosx, and then the compilation failed

**Comment by DoDoENT** [comment]
@DerryMellon , I had this lines in my cmake script, which now needed to be removed:

```cmake
# Implementation note:
# CMake (3.5.2) 'somehow' adds ${CMAKE_OSX_ARCHITECTURES} and
# ${CMAKE_OSX_SYSROOT} to the compiler options even if a generator other than
# Xcode (e.g. Ninja) is used (and this breaks the build of course).
if ( NOT ${CMAKE_GENERATOR} MATCHES "Xcode" )
  unset( CMAKE_OSX_ARCHITECTURES )
  unset( CMAKE_OSX_SYSROOT       )
endif ()
```

This workaround is no longer needed with recent versions of CMake, and conflicts with the generated `conan_toolchain.cmake`, as I described earlier.

**Comment by DerryMellon** [comment]
@DoDoENT, thanks.
But I don't find this lines in my script. So it seems this is not the solution for me.
I add this lines in my CmakeLists.txt to solve the problem now.
```
# export SDKROOT=`xcrun -sdk macosx --show-sdk-path`
if (CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND DEFINED ENV{SDKROOT})
    set(CMAKE_OSX_SYSROOT $ENV{SDKROOT})
endif ()
```

**Comment by JackMcTrimble** [comment]
After diving into the conan source code I was able to fix this inside my profile by adding the following to the [conf] section
```
[conf]
tools.apple:sdk_path=/somethin/something/target/SDK/MacOSX11.2.sdk
```

The comment from earlier in the thread gives a bit more context.
https://github.com/conan-io/conan/issues/13925#issuecomment-1596274888

**Comment by sohanmadhavb** [comment]
The above change worked for me.

If you're using conan say in VScode in MacOS.
1. Find the conan profile file by running this command.
    $ conan profile detect
    /Users/mylove/.conan2/profiles/default

2. Get the Path to the latest installed MacOS SDK:
     $ xcrun --show-sdk-path
     /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

3. Add this path in the conan profile file under conf section
    [conf]
    tools.apple:sdk_path=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

**Comment by sgandon** [comment]
Hello
I don't understand why this ticket is closed ?
I have found a working workaround using the comment above, but I believe that conan should be able to figure the path automatically leveraging the `xcrun` command and not require such manual workaround.

**Comment by lukas2** [comment]
I agree with @sgandon,  manual changes or workarounds should not be required?

P.S. my workaround:
```
if(APPLE)
    execute_process(
            COMMAND xcrun --sdk macosx --show-sdk-path
            OUTPUT_VARIABLE OSX_SDK_PATH
            OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    set(CMAKE_OSX_SYSROOT ${OSX_SDK_PATH})
endif()
```

**Comment by memsharded** [comment]
Hi all.

This is a closed ticket.
The CMAKE_OSX_SYSROOT is being defined in modern Conan by ``host_sdk_name = self._conanfile.conf.get("tools.apple:sdk_path") or get_apple_sdk_fullname(self._conanfile)`` in the ``CMakeToolchain``, which means that defining the ``tools.apple:sdk_path`` seems the way to define this.
If there are issues with this, it would be better to create new tickets, reporting the details. Thanks!
