### ISSUE TITLE
Question regarding self.dependencies

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#13931]
### What is your question?

Hi

I am having some trouble trying to read all the cpp_info.libdirs in my recipe files. In recipe file oct-integration.py it has a requires for recipe file bsw_subsystem.py. Recipe file bsw_subsystem.py contains the following requires.

   requires = ["conanconfig/1.1.2", "sip/1.1.2", "bsw_project/1.1.2", "mcal/1.1.2", "test_stub/1.1.2","project_templates/1.1.2", "import/1.1.2", "cddcj125/1.1.2", "cdddeltasigma/1.1.2"]

When executing the following code it does not pick up any of the cpp_info.libdirs in the bsw_subsystem.py recipe file. If I move the requires listed in bsw_subsystem.py and listed them as requires in oct-integration.py the code below works and I see all the libdirs listed in all the requires. 

for require, dependency in self.dependencies.host.items():
   self.output.info (f'LibDirs = {self.dependencies[str(dependency.ref)].cpp_info.libdirs}  ')

Why can I not see all the libdirs from bsw_susbystem.py when listed as a requires in oct-integration.py?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

Thanks for your question.

I'd need some clarifications.

You said ``oct-integration`` depends on ``bsw_subsystem``. But I don't see it in the declared ``requires``. Is it the ``bsw_project/1.1.2`` one? Can you please clarify the relation between these 2 package recipes?


Note, for better iteration do:
```python
for require, dependency in self.dependencies.host.items():
     # No need to dereference ``self.dependencies[]`` again
     self.output.info (f'LibDirs = {dependency.cpp_info.libdirs} ')
```

**Comment by Ed-CMI** [comment]
Hi Diego

Attached are the two recipe file. oct-integration has a requires of bsw_subsystem/1.1.2 and bsw_subsystem has the following requires
requires = ["conanconfig/1.1.2", "sip/1.1.2", "bsw_project/1.1.2", "mcal/1.1.2", "test_stub/1.1.2","project_templates/1.1.2", "import/1.1.2", "cddcj125/1.1.2", "cdddeltasigma/1.1.2"]
[oct-integration.txt](https://github.com/conan-io/conan/files/11533829/oct-integration.txt)
[bsw_subsystem.txt](https://github.com/conan-io/conan/files/11533830/bsw_subsystem.txt)

**Comment by memsharded** [comment]
Not sure what could be happening.

> Why can I not see all the libdirs from bsw_susbystem.py when listed as a requires in oct-integration.py?

What do you mean by this? What is the symptom, and empty list? It is crashing? What are the logs? Can't you see any of the transitive dependencies, or just some of them?

It would be interesting to see the implementation of the dependencies, specifically the definition of ``package_info()``.

**Comment by Ed-CMI** [comment]
HI

I can't see any of the transitive dependency when running the code below. All I see is the direct dependencies. If I move all the requires that were listed in bsw_subsystem into the octane-integration recipe file then I can see all the libdirs when running the code below.
for require, dependency in self.dependencies.host.items():
     # No need to dereference ``self.dependencies[]`` again
     self.output.info (f'LibDirs = {dependency.cpp_info.libdirs} ')

For ex, octane-integration.py would have the following requires and bsw_subsystem.py would be removed from the requires list in octane-integration.py.

requires = ["conanconfig/1.1.2", "sip/1.1.2", "bsw_project/1.1.2", "mcal/1.1.2", "test_stub/1.1.2","project_templates/1.1.2", "import/1.1.2", "cddcj125/1.1.2", "cdddeltasigma/1.1.2"]

package_info method is executing this code for every recipe file
self.cpp_info.libdirs = [str(self.options.CompClass)] 

Here is the output from the generate method  when I move all the requires listed in bsw_subsystem into  to octane-integration. I dont see any of these libDirs when all the requires above are listed in the bsw_subsystem.py

LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\sipb09327b25d733\\p\\VECTOR_SIP']
LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\bsw_p02fcc75148033\\p\\BSW_Project'] 
LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\test_a1348d6b13861\\p\\BSW_Project']
LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\mcaldfca949b9cdd6\\p\\INFINEON_MCAL']
LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\proje40effba414c67\\p\\BSW_Templates']
LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\cddknec1b45b411039\\p\\SWC']
LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\impor95d6d004b9722\\p\\Import']
LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\cddde1e48ded69527a\\p\\SWC']
LibDirs = ['C:\\Users\\bq824\\.conan2\\p\\cddcjca006ce519d63\\p\\SWC']

**Comment by memsharded** [comment]
I don't know what could be happening there, it is a bit challenging to know without being able to reproduce.
I have put a test that passes correctly, and that proves that the libdirs of the transitive dependencies is also available:

```python
def test_dependencies_transitive_shared():
    c = TestClient()
    app = textwrap.dedent("""
        from conan import ConanFile
        class App(ConanFile):
            package_type = "application"
            requires = "pkg/0.1"
            def generate(self):
                for require, dep in self.dependencies.host.items():
                    self.output.info (f'LibDirs {dep.ref} = {dep.cpp_info.libdirs} ')
        """)

    c.save({"dep/conanfile.py": GenConanfile("dep", "0.1").with_package_type("shared-library"),
            "pkg/conanfile.py": GenConanfile("pkg", "0.1").with_package_type("shared-library")
                                                          .with_requires("dep/0.1"),
            "app/conanfile.py": app
            })
    c.run("create dep")
    c.run("create pkg")
    c.run("install app")
    print(c.out)
    assert "conanfile.py: LibDirs pkg/0.1 = [" in c.out
    assert "conanfile.py: LibDirs dep/0.1 = [" in c.out
```
As you can see, both ``pkg/0.1`` and the transitive ``dep/0.1`` are being displayed.

**Comment by Ed-CMI** [comment]
What version of conan are you using. I am using conan 2.0.4

**Comment by memsharded** [comment]
Conan 2.0.5, but tested it on the 2.0.4 and it passes correctly too

**Comment by Ed-CMI** [comment]
All I see when setting requires = bsw_subystem.py in the octane-integration.py file 
is this list. This does not show any of the requires listed in bsw_subsysem
LibDirs = Recipe bsw_subsystem/1.1.2 is ['C:\\Users\\bq824\\.conan2\\p\\bsw_s455ff72ae4ec2\\p\\lib'] 
LibDirs = Recipe conanconfig/1.1.2 is ['C:\\Users\\bq824\\.conan2\\p\\conanea7952a5ad6ee\\p\\lib'] 
LibDirs = Recipe conan_tc39x_buildenv/1.1.2 is ['C:\\Users\\bq824\\.conan2\\p\\conan6402bc496e4b5\\p\\lib']

**Comment by Ed-CMI** [comment]
Would not setting the package_type to shared- library cause this issue by chance?

**Comment by memsharded** [comment]
Yes, if the transitive dependencies are static libraries, then the shared-library is linking and embedding those static libraries and the downstream consumer no longer has visibility over those libdirs, as they are already represented in the shared-library bindir

**Comment by Ed-CMI** [comment]
I think that is our problem. The recipe files are setting package_type to static-library. Does this also help explain why it worked when setting the requires directly in octane-integration.py?

**Comment by memsharded** [comment]
> I think that is our problem. The recipe files are setting package_type to static-library. Does this also help explain why it worked when setting the requires directly in octane-integration.py?

yes, exactly an ``application`` requiring ``static-libraries`` does need access to those static libraries in order to build itself. While that is not the case if there is a shared library in the middle.

If you haven't watched this presentation https://youtu.be/kKGglzm5ous, it might be worth having a look for clarification about these things.
