### ISSUE TITLE
[question] What is the relation between custom command and custom subcommand?

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#13935]
### What is your question?

I'm trying to figure out [this documentation](https://docs.conan.io/2/reference/extensions/custom_commands.html), notably how the main command is related to the subcommand with respect to argument parsing.

I'm trying to create a custom command to automatically detect my local environment and invoke the correct series of `conan install ...` commands to avoid doing that manually. The idea is to have main `project` command that has some arguments common to all subcommands, and additionally specific arguments for each specific subcommand.

My current approach is:

```python
# cmd_project.py

@conan_subcommand()
def project_ninja(conan_api: ConanAPI, parser: ArgumentParser, subparser: ArgumentParser, *args):
    """
    Create Ninja Multi-Config project for current environment
    """

    common_params = parser.parse_known_args(*args)

    ConanOutput().info(f'Parsed args (ninja): {common_params}')

@conan_command(group="Custom project")
def project(conan_api: ConanAPI, parser: ArgumentParser, *args):
    """
    Create build project using current environment.
    """

    parser.add_argument(
        "--build_types",
        action="append",
        choices=['Debug', 'DevRelease', 'Release'],
        required=False,
        help='''Build types that will be installed. By default, all build types are installed'''
    )

    common_params = parser.parse_known_args(*args)

    ConanOutput().info(f'Parsed args (main): {common_params}')
```

After running `conan --help`, `project` is listed under `custom project commands` section. Also, issuing `conan project --help`, nicely formats this help message:

```
(conan2-venv) [dodo@nm-nmiksa: conanfile-utils (conan-v2)]$ conan project --help
usage: conan project [-h] [-v [V]] [--build_types {Debug,DevRelease,Release}] {ninja} ...

Create build project using current environment.

positional arguments:
  {ninja}               sub-command help
    ninja               Create Ninja Multi-Config project for current environment

options:
  -h, --help            show this help message and exit
  -v [V]                Level of detail of the output. Valid options from less verbose to more verbose: -vquiet, -verror, -vwarning,
                        -vnotice, -vstatus, -v or -vverbose, -vv or -vdebug, -vvv or -vtrace
  --build_types {Debug,DevRelease,Release}
                        Build types that will be installed. By default, all build types are installed
```

However, if I run `conan project --build_types Debug --build_types Release ninja`, I get the following output:

```
Parsed args (main): (Namespace(v='status', subcommand='ninja', build_types=['Debug', 'Release']), [])
```

Meaning that `project` function was invoked, but `project_ninja` function wasn't. But at least `build_types` have been parsed and no parameter is left unparsed.

However, if I invoke without the `ninja` subcommand, I get this error:

```
usage: conan project [-h] [-v [V]] [--build_types {Debug,DevRelease,Release}] {ninja} ...
conan project: error: the following arguments are required: subcommand
ERROR: Exiting with code: 2
```

which is expected.

But, if I replace the order of `ninja` and `build_types`, like this: `conan project ninja --build_types Debug --build_types Release`, I get this weird behavior:

```
Parsed args (main): (Namespace(v='status', subcommand='ninja', build_types=None), ['--build_types', 'Debug', '--build_types', 'Release'])
Parsed args (ninja): (Namespace(v='status', subcommand='ninja', build_types=None), ['--build_types', 'Debug', '--build_types', 'Release'])
```

This means that both `project` and `project_ninja` functions were invoked, but neither managed to parse the arguments, although they clearly used the same instance of `parser`, otherwise `build_types` wouldn't be set to `None`.

The documentation states:
> Notice that to declare a sub-command is required an empty Python function acts as the main command.

But in this case, I don't understand why the subcommand needs to have distinct `parser` and `subparser` - what's their difference in that case? Namely, if my main function needs to be empty in this case, I can create my own function to parse common arguments to be shared between different subcommands, but in that case, it will be the same whether I use `parser` or `subparser`, so I don't understand why is there a need for those to be distinct.

All in all, my questions are:

- if the main function must be empty when subcommands are used, what is the purpose of having both `parser` and `subparser` as parameters of subcommand functions?
- if the main function can define common parameters for all subcommands, what is the correct way of parsing them so that they are available to all subcommands?
- also, in that case, what is the correct way of invoking the command from CLI - should arguments go before or after the subcommand?
- can you provide a working example with multiple subcommands that share some common arguments?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by DoDoENT** [comment]
Another observation:

If I change the code above to this:

```python
# cmd_project.py

def parse_common_arguments(parser: ArgumentParser, *args):
    parser.add_argument(
        "--build_types",
        action="append",
        choices=['Debug', 'DevRelease', 'Release'],
        required=False,
        help='''Build types that will be installed. By default, all build types are installed'''
    )

    return parser.parse_known_args(*args)


@conan_subcommand()
def project_ninja(conan_api: ConanAPI, parser: ArgumentParser, subparser: ArgumentParser, *args):
    """
    Create a Ninja Multi-Config project for the current environment
    """

    common_params = parse_common_arguments(parser, *args)

    ConanOutput().info(f'Parsed args (ninja): {common_params}')


@conan_command(group="Custom project")
def project(conan_api: ConanAPI, parser: ArgumentParser, *args):
    """
    Create a build project using the current environment.
    """
```

I get almost the same weird behavior as in the original question:

```
(conan2-venv) [dodo@nm-nmiksa: conanfile-utils (conan-v2)]$ conan project ninja --build_types Debug --build_types Release
Parsed args (ninja): (Namespace(v='status', subcommand='ninja', build_types=None), ['--build_types', 'Debug', '--build_types', 'Release'])
```

Only after changing the parameter to `parse_common_arguments` in `project_ninja` to use `subparser` instead of `parser`, did I get the correct behavior:

```
(conan2-venv) [dodo@nm-nmiksa: conanfile-utils (conan-v2)]$ conan project ninja --build_types Debug --build_types Release
Parsed args (ninja): (Namespace(v='status', build_types=['Debug', 'Release']), ['ninja'])
```

Although `ninja` is still passed to the subcommand's argument list, i.e. it's not consumed.

So, it appears that `parser` is pretty much unusable within subcommand functions... Is that intended?

**Comment by memsharded** [comment]
> This means that both project and project_ninja functions were invoked, but neither managed to parse the arguments, although they clearly used the same instance of parser, otherwise build_types wouldn't be set to None

The subcommands must use the subparser, this is the right approach:

```python
@conan_command(group="Consumer")
def graph(conan_api, parser, *args):
    """
    Compute a dependency graph, without installing or building the binaries.
    """

@conan_subcommand(formatters={"text": cli_build_order, "json": json_build_order})
def graph_build_order(conan_api, parser, subparser, *args):
    common_graph_args(subparser)
    args = parser.parse_args(*args)


@conan_subcommand(formatters={"text": cli_build_order, "json": json_build_order})
def graph_build_order_merge(conan_api, parser, subparser, *args):
    subparser.add_argument("--file", nargs="?", action="append", help="Files to be merged")
    args = parser.parse_args(*args)
```

It seems you keep using the ``parser`` inside the sub-commands, to add new sub-command arguments, which is incorrect. Make sure to use the ``subparser`` inside the sub-commands to add arguments to that specific sub-command, while using the ``parser`` to parse everything.

This is done because it is possible to have args that apply to all subcommands with ``argparse`` library. Having differentiated the parser and the subparser is the way to achieve this, even if in practice it will be very unusual that a subcommand wants to add an argument to the ``parser``, and they will always to go the ``subparser``

**Comment by DoDoENT** [comment]
> Make sure to use the subparser inside the sub-commands to add arguments to that specific sub-command, while using the parser to parse everything.

That is absolutely unintuitive, but apparently, it works. In that case, I get the behavior I expect, but it's completely unintuitive to me why I need to also add common parameters (i.e. those that are shared for all subcommand) in each and every subcommand and via `subparser`, and not in the main function via `parser`.

**Comment by memsharded** [comment]
Proposing a PR to the docs in https://github.com/conan-io/docs/pull/3226 to clarify these points.

**Comment by DoDoENT** [comment]
Thank you! The proposed documentation clarification makes it clearer now.
