### ISSUE TITLE
[question] conan recipe consisting of only requires

### ISSUE THREAD

**Issue by sid-gif** [conan-io/conan#13932]
### What is your question?

 I have 30 different recipes and one single integration recipe (let's call it A) which have these 30 recipes as requires. So instead of putting 30 requires in recipe A, I created new a recipe B. B isn't building anything, it just has these 30 recipes as requires and each method is passed. When using just B as requires for A, I am getting build failed error since it is not able to get the files packaged by the 30 recipes. When putting 30 recipes as requires it working okay. What am I doing wrong? Is there any smarter way to do this? 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sid-gif 

Thanks for your question.
I am afraid that there is not enough information there to know what is happening or what you mean. It is possible to have one recipe to have ``requires`` to many other packages, and use that single one for a consumer, and if things are defined correctly, the downstream consumer will get all the transitive dependencies.

Please try to provide:
- The Conan version, platform that you are running
- The necessary conanfiles to reproduce the use case. Recall that with ``conan new cmake_lib -d name=pkg -d version=0.1`` you can create fully functional Conan packages that can be created with ``conan create .``. With ``-d requires=other/version`` that template will also define dependencies to other packages.
- The specific commands you are using to reproduce the behavior
- The logs showing the errors.

**Comment by sid-gif** [comment]
![Capture](https://github.com/conan-io/conan/assets/117399302/0548e4e6-2957-4d6d-9a8e-a654d766a9d7)

So there are 5 recipe files which are packaging 20 .a2l files each, The integration recipes needs all those 100 .a2l files. Instead of putting those 5 recipes as requires in integration recipe, I have created a subsystem recipe which has these 5 recipes files as requires. Then the integration recipe is going to have this subsystem recipe as requires.
Is this the right way?

- When integration recipe has 5 recipes as requires (A,B,C,D,E) it works fine.
- When the integration recipe has subsystem recipe as requires, I get an error because the .a2l files are not found.

conan version: 2.0.4
Using, conan create conanfile.py -pr:b profile1 -pr:h profile2

**Comment by memsharded** [comment]
> When the integration recipe has subsystem recipe as requires, I get an error because the .a2l files are not found.

Are not found by who? What integrations are you using CMakeDeps?
Important points:
- Recipes ``package_type`` (or which ``options`` they define)
- ``requires`` traits if any
- Generators/build system integrations
- What it means they are not found? What is failing, what is the actual error message?
- The logs while creating ``conan create .``. Do you see the dependencies listed?

**Comment by AbrilRBS** [comment]
We didnt hear back from you in a while, so closing this one. Feel free to reopen should you still face similar issues, thanks!
