### ISSUE TITLE
Create new packages from existing - best practices ?

### ISSUE THREAD

**Issue by jacmoe** [conan-io/conan#1393]
I have read the docs a lot, and one thing is still not completely clear to me:

When I create a package using `package new nasl/0.4@jacmoe/testing` it generates a `conanfile.py` in my current directory.

That is fine. I understand that :)

Now, I want to change the version or the channel, so what I do is just edit the conanfile, run `conan test_package` and that's it, right?

Now, I only need to change the upload script:

```bash
#!/bin/bash
conan upload nasl/0.4@jacmoe/stable -r jacmoe-bintray --all
```

And I have a new package using the stable channel instead of the testing channel.

Just sanity checking :)

**Comment by jacmoe** [comment]
Yes, I could use the package tools, but my needs are simple, so I want to keep it simple.

For now :)

**Comment by jacmoe** [comment]
It seems to work fine :)

**Comment by memsharded** [comment]
Yes, the ``test_package`` has the following functionality:

- It reads the ``test_package/conanfile.py``, and gets its first requirement.
- Get the user/channel from that requirement, use it to ``conan export`` under that user/channel
- Do the ``conan install  --build=PkgTested`` over ``test_package/conanfile.py``
- Do a ```conan build`` over test_package/conanfile.py
- Execute test_package/conanfile->test() method

So in short, yes, changing the user or channel in the test_package/conanfile.py, already changes the package user/channel in the packaeg, that can be later uploaded. It is usually parameterized with env-vars, so you can even change it without modifying the source code:

```bash
$ export CHANNEL=stable
$ conan test_package
```

Besides that, you also have the ``conan copy`` command that allows to just copy already built packages, from one user/channel to a different one. That is a convenient way to promote packages without having to do a costly rebuild.

**Comment by jacmoe** [comment]
Thanks!
Conan is quite flexible. :)
