### ISSUE TITLE
[question] Is `conan-win-64.exe` in release telemetry free?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#13941]
### What is your question?

conan-win-64.exe at https://github.com/conan-io/conan/releases/

I've checked `.github/`, no github actions to create `conan-win-64.exe` there,
so want to know if the binary `conan-win-64.exe` is safe enough.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @playgithub 

> so want to know if the binary conan-win-64.exe is safe enough.

Being safe, and being telemetry free are completely different things. Many of the tools that we use like Visual Studio, Visual Code, and other IDEs have telemetry, and they are completely safe (as safe as they can be, that is, virus-free, malware-free, etc).

Said that, Conan doesn't have any type of telemetry. We create the .exe in our CI, so should be quite safe. But in case of doubt, you can easily create that exe running the ``pyinstaller.py`` file in the root of the repo: https://docs.conan.io/2/installation.html#use-a-system-installer-or-create-a-self-contained-executable
