### ISSUE TITLE
Removing packages outdated by recipe changes

### ISSUE THREAD

**Issue by et666** [conan-io/conan#1394]
When working with a package which e.g. is using a version HEAD and often the conan recipe is changed, it would be a good to have an option to remove all conan packages, which are outdated by recipe changes.

Maybe it is possible to use the --query option in the conan remove command for this.

**Comment by memsharded** [comment]
Implemented by @et666 in https://github.com/conan-io/conan/pull/1488

**Comment by memsharded** [comment]
Released in 0.25, please update and try.
