### ISSUE TITLE
[feature] Monitor changes for conanfile.py from CMakeToolchain

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#13954]
### What is your suggestion?

When developing a project that uses CMake, it's often needed to update the conan dependencies. The usual idiom for CMake projects is that whenever you make some change in any of the CMake files, the generated build system automatically detects that and re-runs the cmake configuration process. This is very useful.

In the [cmake wrapper for conan v1](https://github.com/conan-io/cmake-conan/blob/develop/conan.cmake#L797-L801), there was a trick to let CMake also monitor for changes in `conanfile.py`.

This feature is missing in conan v2, and I think it shouldn't be difficult to implement. Simply the `conan_toolchain.cmake` file that is generated by `CMakeToolchain` generator can have a variable that stores the full invocation string of `conan` (path to `conan` and all arguments given via CLI) and can use the same trick as the `conan.cmake` script linked above to ensure cmake configure is re-run whenever `conanfile.py` changes. The cmake configure would then simply need to invoke the same `conan install ...` (actually a list of all `conan installs` in case of a multi-config generator) and thus ensure the fresh set of dependencies are pulled.

The only issue with this idea I see is that CMake configure will invoke `conan install ...` additionally during the first-time configure, but I think this shouldn't be a problem, as the dependencies will already be installed at that time. Maybe it's possible to put this option behind a opt-in flag, so that it's used only for development, but not during package build?

What to you think about the idea?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DoDoENT 

Thanks for your suggestion.

For cmake-conan, I think this was recently implemented in https://github.com/conan-io/cmake-conan/blob/c69227de51f7edc04bb8fd9fd14bcdfec8aa4c2b/conan_support.cmake#L162, and the cmake-conan wrapper will actually re-install dependencies when the conanfile changes.

For regular ``conan install`` flows, that would certainly be too much. Having ``conan_toolchain.cmake`` to call ``conan install`` again is way beyond the scope and responsibility of the ``conan_toolchain.cmake``, and will introduce quite a bunch of complexity and fragility. If it is expected that cmake invocations will be calling conan again, that should be done via the ``cmake-conan`` integration, that is exactly its purpose.

**Comment by DoDoENT** [comment]
Thank you for your answer. I'll give the new cmake-conan wrapper a try and see if I can make it work together with `CMakeToolchain` generator in combination with `CMakeDeps`.
