### ISSUE TITLE
[question] CMake does not export include (or library) paths to Visual Studio project

### ISSUE THREAD

**Issue by TheFloatingBrain** [conan-io/conan#13958]
Hello, 

I have a Conan + CMake project and I am trying to the same CMake file on linux and windows. Everything works fine on linux, however, when I try to generate the VS Project (Visual Studio 2022) for Windows, its almost like conan does not exist.

I try to simply use glfw, but the headers are not in the include directories (under Project Properties -> C/C++ IIRC), and it does not look like the path for the libraries are entered into the linker settings.

Here is a link too my [CMake](https://github.com/TheFloatingBrain/invaders-from-space-3d/blob/main/CMakeLists.txt) and [Conan](https://github.com/TheFloatingBrain/invaders-from-space-3d/blob/main/conanfile.py) files.

I ran (from projectdir/build)
`conan install .. --build=missing --outputfolder=. -s build_type=Debug`
Then
`cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake` with or without specifying debug configuration
or 
` cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE={REMOVED FOR POST}/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW`
Am I missing something?

The only two things I can think of are: 

- I made a symbolic link too my conan root (leading to a separate drive) but everything installs fine, [I saw this recommended under a different issue](https://github.com/conan-io/conan/issues/2250) as `conan config set storage.path=<your new path here>` does not seem to be a valid option anymore (limited space on the C: drive) _UPDATE_ I did check this, I deleted the symbolic link, and generated a fresh .conan2 folder via `conan profile detect` and nothing seemed to change
- There are warnings on the GLFW conan package saying it uses deprecated features

I'm new to 2.0, so I am just not sure if I am doing things right.

Thank you, 
 - TFB

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @TheFloatingBrain 

Thanks for your report.

Could you please share the output/logs of both ``conan install`` and ``cmake ...`` commands?
Also, instead of opening the IDE, just build from the terminal with ``cmake --build . --config Debug``

Thanks!

**Comment by TheFloatingBrain** [comment]
[Result](https://gist.github.com/TheFloatingBrain/2340d824f76348f86ff8345f855125db) after deleting my conan folder and running: 
```
 conan profile detect
```
```
 conan install .. --build=missing --output-folder=. -s build_type=Debug
```
[Result](https://gist.github.com/TheFloatingBrain/e3d76b52eb9db2a4dcb1ff82162a312e) of 
```
 cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
```

[Result](https://gist.github.com/TheFloatingBrain/0702a938b84b3b879619a5a23bfa20a6) of: 
```
 cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
```
After deleting `build/CMakeFiles` and `build/CMakeCache.txt`

```
PS C:\Users\Chris\source\repos\ifs35\invaders-from-space-3d\build> cmake --build . --config Debug
MSBuild version 17.5.0+6f08c67f3 for .NET Framework

  Checking Build System
  Building Custom Rule C:/Users/Chris/source/repos/ifs35/invaders-from-space-3d/CMakeLists.txt
  main.cpp
C:\Users\Chris\source\repos\ifs35\invaders-from-space-3d\source\main.cpp(3,10): fatal  error C1083: Cannot open include
 file: 'GLFW/glfw3.h': No such file or directory [C:\Users\Chris\source\repos\ifs35\invaders-from-space-3d\build\link1.
vcxproj]
```

After copying clean template project, running the above steps but not deleting cmake files

```
 cmake --build . --config Debug
MSBuild version 17.5.0+6f08c67f3 for .NET Framework

  Checking Build System
  Building Custom Rule C:/Users/Chris/source/repos/ifs36/invaders-from-space-3d/CMakeLists.txt
  main.cpp
C:\Users\Chris\source\repos\ifs36\invaders-from-space-3d\source\main.cpp(3,10): fatal  error C1083: Cannot open include
 file: 'GLFW/glfw3.h': No such file or directory [C:\Users\Chris\source\repos\ifs36\invaders-from-space-3d\build\link1.
vcxproj]
```

^^ [Log before the above](https://gist.github.com/TheFloatingBrain/129c3cccdafb565f2ecdf396590c9fb3)

**Comment by TheFloatingBrain** [comment]
NOTE: Tried to build with VS because I anticipate a team member will want to use it

**Comment by TheFloatingBrain** [comment]
Also after repeating the procedure of deleting my conan folder and trying again 
```
 Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE
```
Disappears if I put `conan_toolchain.cmake` in quotes

**Comment by memsharded** [comment]
Oh, it seems I overlooked one missing thing:
You don't have a ``find_package(glfw3)`` in your https://github.com/TheFloatingBrain/invaders-from-space-3d/blob/main/CMakeLists.txt CMakeLists.txt

You need something like:
```cmake
find_package(glfw3 REQUIRED CONFIG)

add_executable(${PROJECT_NAME} test_package.c)
target_link_libraries(${PROJECT_NAME} PRIVATE glfw)
```

Dependencies are found via ``find_package()``, if you don't have it the dependencies cannot be found.
It is possible that in Linux it is just using some ``glfw`` library installed in the system or something like that.

**Comment by memsharded** [comment]
I'd recommend following the Conan tutorial in https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html#id2 to learn about these concepts

**Comment by memsharded** [comment]
> Disappears if I put conan_toolchain.cmake in quotes

Maybe you are in powershell shell? The command line expansions is a bit different in powershell, you might indeed need to quote some arguments, still not fully clear to me what are the reasons for this specific one

**Comment by TheFloatingBrain** [comment]
Thank you it works now
