### ISSUE TITLE
[question] conan upload and conan config

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#13955]
### What is your question?

Dear Conan Folks,

I use Jenkins as CI Tool. I used this to upload package to Artifactory repo with Conan1.x:
```
def uploadCall(def artifactoryname, def artifactoryrepo, String buildname, String pkg_refernce){
        println "Artifactory name is:" + artifactoryname + " Artifactory repo is: " + artifactoryrepo
        def buildInfo = Artifactory.newBuildInfo()
        buildInfo.name = buildname
        def server = Artifactory.server artifactoryname
        def client = Artifactory.newConanClient userHome: "${env.WORKSPACE}/conan".toString()
        def serverName = client.remote.add server: server, repo:artifactoryrepo , force: true
        String command_upload = "upload ${pkg_refernce} -r ${serverName} --confirm"
        client.run command: command_upload, buildInfo: buildInfo
        server.publishBuildInfo buildInfo
} 
```
But with conan-2.x it fails with:
cmd.exe /C "conan config set log.trace_file=E:\J\feature_bringupconan2/conan\conan_log.log && exit %%ERRORLEVEL%%"

conan config **set** doesnot exist according to conan-2.x
https://docs.conan.io/1/reference/commands/consumer/config.html?highlight=conan%20config
Could someone please help me?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

Thanks for your question.
That belongs to the Artifactory plugin, which has not been updated yet to support Conan 2.0. I would suggest to file a ticket in their Github repo.

For Conan 2.0 we are working in a custom command to generate the BuildInfo here: https://github.com/conan-io/conan-extensions (current commands in https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art)

The Artifactory plugin is a thin layer, you can perfectly code your jobs in Jenkins without using it, just calling ``conan ....`` commands yourself in the jenkins files

**Comment by maitrey** [comment]
Hi @memsharded  , 

Thanks for answering.
I hope this is the correct repo : https://github.com/jenkinsci/artifactory-plugin  
I think then I will have to raise a JIRA ticket for them if my information is correct.

**Comment by maitrey** [comment]
Perhaps I was mistaken . I created one here : https://github.com/jfrog/jenkins-artifactory-plugin/issues/820  .
Hopefully is the right place.

**Comment by memsharded** [comment]
https://github.com/jfrog/jenkins-artifactory-plugin seems good.

Closing this questions as solved, there is little we can do here, thanks!
