### ISSUE TITLE
[question] Is it possible to specify package id mode on a per-package basis in Conan 1.xx?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#13957]
### What is your question?

Hi,

we have quite a big dependency tree in our product. It uses both semver'd and non semver'd packages.
Is it possible to set the package_id mode on a per-package basis? E.g. I'd like to set the package id mode
in the non-semver packages to something other than semver_direct, for the complementer set I'd use the 
default being set (which we haven't changed and it's semver_direct).

I'm aware of the fact that from the topmost level, one could set self.requires['xxxx'].full_package_mode() or something
like that, but I'd like to keep this information baked into the given package and not to be controled by the
consumer.

And we are using still Conan 1.xx
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for your question.

It is not possible to define this in Conan 1.X. The only alternatives are:

- Define it per-consumer in ``package_id()`` as ``self.info.requires["dep"].xxx_mode()``
- Define it globally in the configuration, to change the default one.

Conan 2.0 introduced the possibility to define the default in the package itself, to change how it affects its consumers: https://docs.conan.io/2/reference/conanfile/attributes.html#package-id-embed-non-embed-unknown-mode

**Comment by harsszegi** [comment]
Aok, thanks a lot!
