### ISSUE TITLE
[question] How to have the header file of my dependency included in package?

### ISSUE THREAD

**Issue by baqeri** [conan-io/conan#13950]
### What is your question?

Hi everyone,

How to have the header file of my dependency included in package? I get compile error when adding my built library to another project as a dependency because that library is using nlohmann library in its header file.

```
.../.conan2/p/simuca512455cd01cd/p/include/mtp/ContractSettings.h:5:10: fatal error: nlohmann/json.hpp: No such file or directory
    5 | #include "nlohmann/json.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/example.dir/build.make:76: CMakeFiles/example.dir/src/example.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/example.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @baqeri thanks for your question!

Assuming your dependency graph looks something like:
```mermaid
graph LR;
    pkg-->simlib;
    simlib-->nlohmannjson;
```

There are two possible cases here:
 * If `pkg` directly uses functinality implemented in `nlohmannjson` headers, then it should properly declare that `nlohmannjson` is a direct dependency of itself, such that the graph looks like:
```mermaid
graph LR;
    pkg-->simlib;
    pkg-.->nlohmannjson;
    simlib-->nlohmannjson;
```
 * If `pkg` does not directly use `nlohmannjson` but its types are part of the API of `simlib`, then `simlib` should set the requirement trait `transitive_headers` to `True` (And `transitive_libs` for those libs that also need the libs).
```mermaid
graph LR;
    pkg-->simlib;
    simlib-. transitive_headers=True .->nlohmannjson;
```

For further info on requirements traits, see [this docs page](https://docs.conan.io/2/reference/conanfile/methods/requirements.html). To get a better understanding on how they work, I'd also recommend watching [this video](https://www.youtube.com/watch?v=kKGglzm5ous) by @memsharded which deals with how Conan models this.

Let me know if I this works for you, else I'm happy to answer any other questions you have :)

**Comment by baqeri** [comment]
Thank you, @RubenRBS! resolved.
