### ISSUE TITLE
[question] SHORT DESCRIPTION

### ISSUE THREAD

**Issue by ronnieott** [conan-io/conan#13960]
### What is your question?

When I compile and link my application with mbedtls using conan I get an error:

```error: ‘mbedtls_ssl_conf_tls13_key_exchange_modes’ was not declared in this scope```

my conan.py includes the latest version of mbedtls:

```    requires = [...,  "mbedtls/3.2.1", ...  ] ```

when I use mbedtls as a git submodule I can configure it:

```mbedtls/scripts/config.py set MBEDTLS_SSL_PROTO_TLS1_3```

and my code does compile smoothly. So my question is: how to configure it so that I can compile it using conan?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ronnieott 

Thanks for your question.

It would be necessary to have some more details and information and something we could reproduce. Like the ``conanfile.py`` of the consumer, the ``CMakeLists.txt``, the exact commands you are using to reproduce the behavior, the information about OS, compiler, Conan version, etc. Thanks!

**Comment by memsharded** [comment]
Hi @ronnieott 

Any follow up? Did you manage to solve the issue?  Please let me know.
