### ISSUE TITLE
[question] Optional build requires possible?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#13961]
### What is your question?

Context is Conan 1.x:

I would like to specify a build requires (for the host context) or use the new test_requires that should be optional.
Meaning if it is there download it and if not do not produce an error.

I could of course use an option for that to enable/disable these build requires but ideally I do not want to introduce an option for that.

In case it is possible in Conan 1.x is that also possible in 2.x?

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
For Conan 2, there's a new `system_tools` section in the profile ([See docs here](https://docs.conan.io/2/reference/config_files/profiles.html#system-tools)), which works mostly like you have already described.

It will try to match the version to the one you've defined in the profile. If there's no match, then Conan will look for it as normal

**Comment by AbrilRBS** [comment]
Ignore me, I missread your `tests_requires` with `tool_requires`. The explanation above does not apply for test_requires!

Your the best approach might be to conditionally add the test requirement on the value of `self.conf.get("tools.build:skip_test")`. That way if you're not running the tests, the requirements will not be there either

**Comment by MTomBosch** [comment]
Is there something similar for Conan 1.x available or was your example with self.conf.get("tools.build:skip_test") based/compatible with Conan 1.x?
Also is the tools.build:skip_test set by Conan or needs to be set externally.

**Comment by AbrilRBS** [comment]
The conf has been available since Conan 1.40.
As it's a conf, you need to add it to your `global.conf` file, or pass it in the CLI using `-c tools.build:skip_test=True`

See https://docs.conan.io/en/1.60/reference/config_files/global_conf.html#tools-configurations for more info on the confs
