### ISSUE TITLE
[question] Is there a way to register a user-defined method when issuing conan create?

### ISSUE THREAD

**Issue by lijie-jiang** [conan-io/conan#13974]
### What is your question?

Hello! I have a question on how to perform addtional operations when creating a package.
That is to say, I was using 'conan create ...' command to build and create a package from source codes. 
My requirement is to add some addtional files to the generated conan package.
Is there a way to 'insert' an used-defined method which will be invoked when the package() method being issued?
For now I modified my conanfile.py to add addtional statements to the package() method.
But I would prefer a better choice instead of modifying the conanfile.py.
Many thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lijie-jiang 

Thanks for your question.

Yes, in the general case, it is not possible to automagically inject behavior into recipes. The recommended approach is to modify the recipe to implement the behavior that you want.

Maybe you want to have a look to the hooks: https://docs.conan.io/2/reference/extensions/hooks.html

They allow to do ``pre_package`` and ``post_package`` operations. 
Note however, that this behavior shouldn't be critical for the package operation, if it is something considered core of the package creation, the recommended approach is to modify the recipe.

**Comment by lijie-jiang** [comment]
> Hi @lijie-jiang
> 
> Thanks for your question.
> 
> Yes, in the general case, it is not possible to automagically inject behavior into recipes. The recommended approach is to modify the recipe to implement the behavior that you want.
> 
> Maybe you want to have a look to the hooks: https://docs.conan.io/2/reference/extensions/hooks.html
> 
> They allow to do `pre_package` and `post_package` operations. Note however, that this behavior shouldn't be critical for the package operation, if it is something considered core of the package creation, the recommended approach is to modify the recipe.

Hi @memsharded,

I appreciate your information. 

Actually I was planning to add more manifest file to any third-party package when generating them, i.e. google test. It is not a good practice to modify a recipe from conan center, you know. But I would try the hook method post_generate() since it may be helpful. 

Thanks again for your reply.

**Comment by memsharded** [comment]
>  It is not a good practice to modify a recipe from conan center, you know.

Actually, it is.
There are many users doing this, creating their own packages from a fork of conan-center-index, with modified recipes to suit their needs. We are even preparing some features to simplify this fork model too. 
Building your own package binaries from your fork is a good practice, you have full control of your binaries, of your sources, absolute reproducibility and traceability of your binaries, etc.

**Comment by lijie-jiang** [comment]
It sounds great. Thanks again.
