### ISSUE TITLE
Error on Windows for project with libxml2 dependency

### ISSUE THREAD

**Issue by matteo-agnelli** [conan-io/conan#1397]
Hi guys,

I am having some issues lately building a project which depends on libxml2. I updated to 0.24 but still have the same problem. Somehow, something with libxml2 seems to go wrong during the install step.

I can see libxml2 is built from sources with its dependencies: libz and winiconv. Packages are built correctly and I can find them but when I build the project with CMake it tries to link against libiconv, which has not been installed (I can find the packaged with the hased id but it's empty). Here the issue:

> `Library libxml2 found:
C:/Users/agn/.conan/data/libxml2/2.9.3/lasote/stable/package/b21accc201486029c7467577aa1b851be67bb2e6/lib/libxml2.lib`
`Library zlibstaticd found 
C:/Users/agn/.conan/data/zlib/1.2.8/lasote/stable/package/f27dcd2d5e453cb01f9324a959461903ce8116a0/lib/zlibstaticd.lib`
`Library iconv found C:/Users/agn/.conan/data/winiconv/1.14.0/lasote/stable/package/c32596dcd26b8c708dc3d19cb73738d2b48f12a8/lib/iconv.lib`
`Configuring done`
`CMake Error in src/CMakeLists.txt:`
`Imported target "CONAN_PKG::libxml2" includes non-existent path
"C:/Users/agn/.conan/data/libiconv/1.14/lasote/stable/package/e381c005c524eb26ab473c85272cd86d1d35e60d/include"`
`in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:`
`* The path was deleted, renamed, or moved to another location.`
`* An install or uninstall procedure did not complete successfully.`
`* The installation package was faulty and references files it does not provide.`

Am I missing something in my configuration or is this an issue with the libxml2 package?

Thanks and cheers,
   Matteo

**Comment by memsharded** [comment]
Hi Matteo,

I have just tried in windows, and been able to make it work with:

```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
CONAN_BASIC_SETUP()

ADD_EXECUTABLE(example example.c)

find_package(ZLIB)
find_package(LibXml2)

if(LIBXML2_FOUND AND ZLIB_FOUND)
    include_directories(${LIBXML2_INCLUDE_DIRS})
    include_directories(${ZLIB_INCLUDE_DIRS})
    target_link_libraries(example ${LIBXML2_LIBRARIES} ${ZLIB_LIBRARIES})
    if(UNIX)
       target_link_libraries(example ${LIBXML2_LIBRARIES} ${ZLIB_LIBRARIES} m) 
    endif()
    if(APPLE)
       target_link_libraries(example iconv)
    endif()
else()
    message(FATAL_ERROR "Not found libxml2")
endif()
```

I have tried the TARGETS approach and is indeed failing. I am having a look.

**Comment by memsharded** [comment]
I have already reported the issue to the offending package, which results to be libiconv: https://github.com/lasote/conan-libiconv/issues/7

In the meantime, you can easily workaround this, either not using TARGETS, or creating the missing directory empty, something like:

```cmake
project(MyHello)
cmake_minimum_required(VERSION 2.8)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_executable(example example.c)
file(MAKE_DIRECTORY ${CONAN_INCLUDE_DIRS_LIBICONV})
conan_target_link_libraries(example)
```

**Comment by lasote** [comment]
Please, try now, I've fixed the recipe.

**Comment by matteo-agnelli** [comment]
Hi guys,

thanks for the quick answers! The issue I had during the build stage with CMake is now gone.

I have however another problem, which perhaps could be due to a wrong configuration on my side, not sure. My application is linking statically against all dependencies. However, I can see the application is only linking against the libxml2 and libiconv interface libraries (.lib) but it's reporting missing .dlls during runtime. Is there some configuration option I am missing in my conanfile to force linking against the static lib, or perhaps am I missing some command to install the .dlls?

What I tried in order to fix this:
- copy libxml2.dll (libxml2_a_dll.lib ?) and iconv.dll into the application folder: didn't work, still got errors with libxml2
- in Visual Studio, link my application against the static libxml2 (libxml2_a.lib). iconv doesn't provide a static version of the lib so I had to stay with the .dll in the application folder. When linking statically against libxml2 there is another Windows runtime lib missing (Ws2_32.lib) but after adding this one to the linker everything worked.

Is all of the above something I can fix configuring properly on my side the way I consume the conan-libxml2 package or are there some other issues with libxml2 dependencies?

Thanks again! Cheers,
Matteo

**Comment by memsharded** [comment]
I think the key is in the libxml2 recipe:

```python
def config_options(self):
        del self.settings.compiler.libcxx
        if self.settings.os == "Windows":
            self.options.shared = True # Static in win doesn't work, runtime errors
```
The recipe is forcing to use the dynamic library, because static one is not working on windows.
I will try to have a look to the library, but it seems there might be some limitation with the library build, not a conan issue.

**Comment by SSE4** [comment]
we're using static libxml2 on Windows for ages, it just has to have definitions LIBXML_STATIC/LIBXML_STATIC_FOR_DLL (second is for linking static libxml2 with shared libraries)

**Comment by danimtb** [comment]
Setting is as obsolete as there is now a Bincrafters recipe for libxml2 in conan center that seems to be working fine for both shared and static: 

https://github.com/bincrafters/conan-libxml2

Thanks!

**Comment by memsharded** [comment]
This can be closed, there is a new recipe for libxml2 in ConanCenter for a long time now, new issues with it should be submitted to ``conan-center-index`` repo.
