### ISSUE TITLE
Conan 2.x not working in WSL

### ISSUE THREAD

**Issue by schwaerz** [conan-io/conan#13973]
### Environment details

* Operating System+version: Win11 22H2 / WSL: Ubuntu 22.04
* Compiler+version: gcc11
* Conan version: 2.0.5
* Python version: 3.10.6

### Steps to reproduce

1. Create simple hello world library cmake project per template
2. Let conan create a deafult profile
3. Run `conan create` for the library template without specifying a profile

Result:
Conan will complain about missing settings. It does not seem to detect those in the `conan profile detect'. Instead it will complain about the following settings, if not set:
* `os.version`
* `os.bubsystem`
* `compiler.threada`
* `compiler.exception`
* 
Expected: The default profile should contain everything required to build something...

Furthermore - the tool requirement seems to be broken:
1. Create the prevously created project by specifying the missing settings on the command line, e.g.:

        conan create . -s os.version=ANY -s os.subsystem=wsl -s compiler.threads=posix -s compiler.exception=dwarf2

3. Create an executable cmake project. Use the same conan create command to create it:

        conan create . -s os.version=ANY -s os.subsystem=wsl -s compiler.threads=posix -s compiler.exception=dwarf2

5. Reconfigure the project to link against the library from the library project. Ensure that `conan create` will work
6. Create a third simple project which uses the exe project as tool requirement, just calling it using `self.run()`.
7. Try to build. Use the same conan create command to build it. It will not work but complain about missing settings:
```
Requirements
    foo/0.2#4ee72e4b887ab79440d81af6b7691551:c25fcd894d817fa0915195ef42037be7a1cf994e - Build
Build requirements
    hello/0.1#13792e36e0199a6f442b41b3bd471482:2f0f83d328ab76ec93d562405f16b7139787a4b2 - Invalid
Skipped binaries
    ['hello-lib/0.1']

======== Installing packages ========
ERROR: There are invalid packages:
hello/0.1: Invalid: 'settings.os.version' value not defined
```

As this setting is specified everywhere I am not sure why Conan thinks it is not set. I even tried adding it to the default profile - with no avail.

Furthermore I do not understand why all those additional settings will be required for WSL. We use WSL as a replacement to execute Linux builds from within Windows. Previously (Conan 1.x), we used 100% the same profile as for Linux. Which makes sense to me, as we also want to get the same result there.

**Comment by schwaerz** [comment]
Please note that the same thing works on native Linux 22.04. Conan should not behave differently in WSL - except if explicitly asked (though we would not need this anyways).

**Comment by schwaerz** [comment]
Please use the attached folder structure, running `./build-all.sh` to reproduce.
[conan2.0-wsl.zip](https://github.com/conan-io/conan/files/11573253/conan2.0-wsl.zip)

**Comment by memsharded** [comment]
Hi @schwaerz 

Yes, this doesn't look right.
I have been trying to reproduce with some simple steps:
- ``conan new cmake_lib -d name=pkg -d version=0.1``
- ``conan profile detect``
- ``conan create .``

And it worked without issues, not sure what could be happening.
Maybe it is something in the profile detection that is failing, my detected profile was:
```
Found gcc 11
gcc>=5, using the major as version
gcc C++ standard library: libstdc++11
Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
```
Can you please share your detected profile?

**Comment by schwaerz** [comment]
@memsharded You tried on WSL?

Then I wonder why it does not need those additional settings for you, as your profile does not contain them either?

The detected profile for me is:
```
conan profile detect --force
Found gcc 9
Found clang 14.0
gcc>=5, using the major as version
gcc C++ standard library: libstdc++11
Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
```

**Comment by memsharded** [comment]
> @memsharded You tried on WSL?

Yes, sure, my Ubuntu in WSL

Have you tried it without the ``hello`` dependency? Just the steps I copied above? Just to rule out something recipe-specific in "hello"

**Comment by schwaerz** [comment]
Does not work for me
```
~/repositories/test$
    conan new cmake_lib -d name=pkg -d version=0.1
    conan profile detect
    conan create .
File saved: CMakeLists.txt
File saved: conanfile.py
File saved: include/pkg.h
File saved: src/pkg.cpp
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/src/example.cpp
ERROR: Profile '/home/foo/.conan2/profiles/default' already exists

======== Exporting recipe to the cache ========
pkg/0.1: Exporting package recipe: /home/foo/repositories/test/conanfile.py
pkg/0.1: Copied 1 '.py' file: conanfile.py
pkg/0.1: Copied 1 '.txt' file: CMakeLists.txt
pkg/0.1: Copied 1 '.cpp' file: pkg.cpp
pkg/0.1: Copied 1 '.h' file: pkg.h
pkg/0.1: Exported to cache folder: /home/foo/.conan2/p/pkgd53c48554a642/e
pkg/0.1: Exported: pkg/0.1#af303d4e06b226cd095ae296f68bf6dc (2023-05-26 09:46:37 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    pkg/0.1#af303d4e06b226cd095ae296f68bf6dc - Cache

======== Computing necessary packages ========
Requirements
    pkg/0.1#af303d4e06b226cd095ae296f68bf6dc:308ccc1b7065dbcf54f86f902c83ab6fcd18d025 - Invalid

======== Installing packages ========
ERROR: There are invalid packages:
pkg/0.1: Invalid: 'settings.os.version' value not defined
```

**Comment by memsharded** [comment]
Can you please make sure to completely remove the ``.conan2`` cache folder, just in case there is some legacy there, something corrupted or the like? (Actually better, just rename it to ``.conan2_backup``, for further analysis). No idea what it would be failing in your case (I assume that ``/home/foo/.conan2`` is private to the Ubuntu, not shared with the Windows host or anything like that)

**Comment by schwaerz** [comment]
After deleting the `.conan2` folder, it is working :)

**Comment by memsharded** [comment]
> After deleting the .conan2 folder, it is working :)

Ok, great!

It could be some previous stuff there in the cache, maybe a legacy ``profile_plugin`` implementation that was not correctly migrated or something like that. If you want to share with us the .zip of the cache (I guess the packages in it can be removed, just the config files could be enough) for inspection, then that might help. Not strictly necessary, we can consider this ticket solved, as Conan 2 works with WSL as expected, so as you prefer. If there is some sensitive data and you want to share it to info@conan.io that might be possible too. 
Thanks!

**Comment by schwaerz** [comment]
Sorry however I would have to check each and every file for some sensitive data as I won't be allowed to share them outside of our company network.

If there are any file in particular (non-binary), I'd be happy to share.

Thanks for the quick support, btw. :)

**Comment by memsharded** [comment]
Probably the folder ``extensions`` there, if you didn't modify it, it should contain just ``profile.py``, and 2 .py files inside ``compatibility`` folder, and then the ``settings.yml`` file.

> Thanks for the quick support, btw. :)

Happy to help! :)

**Comment by memsharded** [comment]
Closing this ticket as solved.
If you want to share your files, they will be welcome, otherwise not an issue, thanks very much for your feedback!

**Comment by schwaerz** [comment]
> Probably the folder `extensions` there, if you didn't modify it, it should contain just `profile.py`, and 2 .py files inside `compatibility` folder, and then the `settings.yml` file.
> 
> > Thanks for the quick support, btw. :)
> 
> Happy to help! :)

Oh, this would have been in the `.conan2` folder? That one I unfortunately removed completetly :(
I only have the one where I can no longer reproduce the issue. Sorry for that, should have made a backup before.

In case I will face this issue again, I will happily share those files here.

**Comment by memsharded** [comment]
yes, the ``.conan2`` folder, but don't worry not an issue, thanks again!
