### ISSUE TITLE
[question] loongarch64 support

### ISSUE THREAD

**Issue by flying-sakura** [conan-io/conan#13996]
### What is your question?

Hi! I have a question regarding the plan if Conan will support loongarch64(a CPU architecture, differ from any other CPUs, e.g. x86, MIPS, etc.).
Currently, Conan doesn't support loongarch64 because it's a new architecture. 
There is an OS named KyLin that can run over this CPU. It's like Linux.
After run this command "conan profile detect --force" I will get the result:
gcc>=5, using the major as version
gcc C++ standard library: libstdc++11
Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

Now that the gcc on KyLin doesn't support "-m64" option, the compile progress will fail.
Temporary I change the arch to 'MIPS' so that gcc will not use “-m64" option and compile will pass.
But it's certainly not a real MIPS.

Could you please tell me if Conan would have a plan that support such arch, or if there is any ways for users to modify Conan so that it can apply their own CPU?

Kind Regards

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @flying-sakura 

Thanks for your question.
There are different things in this question:

- The detection of the profile doesn't aim to be accurate or complete. It is expected that it doesn't detect all settings and architectures. The recommended approach is to use and rely on you own profile files that you can share with ``conan config install``. Conan 2.0 does this way more explicit, adding warnings to the output, and better documenting that the detected profiles is not complete or stable.
- For adding new settings that do not exist in the default Conan ``settings.yml``, you can define your own settings too, and add there the architectures you want. Check https://docs.conan.io/2/reference/config_files/settings.html#customizing-settings. The custom settings are also managed by ``conan config install``
- Custom new architectures will not pass `` “-m64"`` to the build systems. You can inject your own compiler flags if necessary by different means, like providing CMake toolchain files via ``tools.cmake.cmaketoolchain:user_toolchain`` conf, or by ``tools.build:cxxflags`` conf.

I hope this helps.

**Comment by flying-sakura** [comment]
@memsharded Thanks for your help. It answers my question.

**Comment by memsharded** [comment]
Ok, thanks for the feedback, closing this issue as solved.

But if there are some more users questions and demand for this architecture, we can add it to the default ``settings.yml``, please any users, let us know.
