### ISSUE TITLE
[question] `conan-win-64.exe` needs priviledge for administrator on Windows

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#13998]
## Env
Windows 11
Window Terminal (powershell)

## Question
When running `conan-win-64.exe`, it needs priviledge for administrator, is it necessary?

**Comment by memsharded** [comment]
You mean the installer downloaded from our download page? Please try to be more clear and detailed in your reports.

Yes, it install the Conan application, and it needs permission to install it, as the vast majority of applications.

**Comment by playgithub** [comment]
https://github.com/conan-io/conan/releases/download/2.0.6/conan-win-64.exe

OK, it's an installer.

Thanks
