### ISSUE TITLE
[question] Is it somehow possible to build the same project with both Conan 1.x and 2.x ? 

### ISSUE THREAD

**Issue by ATS-AValli** [conan-io/conan#13992]
### What is your question?

Hi.

We have an extensive C++ codebase which currently builds with Conan 1.x .
Due to the new release of 2.x, but also other reasons, I've recently ported (most) our conanfiles to V2, with good results.

However, due to business concerns, the company wants to keep the old build system around, which uses conan 1.x .

Thus it's really a mess to have the two version live one next to the other.

So we have several repositories with a rather usual directory layout:

prjname/

- conanfile.py
- source_folder (with CMakeLists.txt, sources, includes, whatnot)

 
Right now the rather hackish way I've managed to implement something resembling a working solution is to add a "conan2" directory in the root of the project folder, with a V2 conanfile in it. However of course this V2 conanfile has to reference the source folder (for export_sources) with a leading "../" (like: "../source_folder"). I've achieved this by cooking into export_sources()  some code to prepend the directories with "../" but this is ugly as hell.

Does anyone have an idea on how to do this in a clean way ?
Playing around with soft links could be a solution but it's not clean either.
Maybe re-directing one conanfile to another, evaluating the conan version could be viable, but I have no idea if this is feasible in Python.
A third idea would be to have Conan V2 allow to specify a different filename for the conanfile, so an idea similar to n.1 but way cleaner.

I wonder if no-one else has stumbled on the same issue (there seems to be no other requests like this one, unless I'm mistaken), yet this is something that is likely to happen as more project try to adopt V2, especially in setups (like mine) where there's a strong requirement to keep old build systems working for a while more.

Ideas, suggestions ?

Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ATS-AValli 

I am not sure what is the issue. Could you please clarify about: 

> However, due to business concerns, the company wants to keep the old build system around, which uses conan 1.x .

We do this at scale with ConanCenter. The same recipes keep working both in Conan 1.X and 2.0, simultaneously. It is not necessary to drop 1.X to be able to upgrade and be ready for Conan 2.0. It shouldn't be necessary to create a new parallel layout or anything like that.

**Comment by ATS-AValli** [comment]
> We do this at scale with ConanCenter. The same recipes keep working both in Conan 1.X and 2.0, simultaneously. It is not necessary to drop 1.X to be able to upgrade and be ready for Conan 2.0. It shouldn't be necessary to create a new parallel layout or anything like that.

The old build system, which uses Conan 1, also starts the build process (in method build) in a completely different way, without invoking CMake directly but by using some scripts made in-house. So at least for that method (but possibly for others) we have to take two different code paths. So is there a way to check with version of Conan is currently running the conanfile ? I've looked into the reference at https://docs.conan.io/2/reference/conanfile/attributes.html but I didn't see it.

What you're stating above is very interesting however. Could you point me to a good conanfile example in ConanCenter that is compatible to both ?

And how do you import the various methods from either "conans" or "conan" ? The class hierarchy has changed between V1.x and V2.

Thanks!

**Comment by memsharded** [comment]
> The old build system, which uses Conan 1, also starts the build process (in method build) in a completely different way, without invoking CMake directly but by using some scripts made in-house. 

Thanks for clarifying. The fact that you are calling cmake directly doesn't imply that you cannot make this recipe work also simultaneously in Conan 1.X and Conan 2.0. In fact, if not relying on the legacy ``from conans import CMake`` or on the legacy ``cmake`` generator, the transition should be easier.

> So at least for that method (but possibly for others) we have to take two different code paths.

Well, in the worst case, it is very possible to do something like this:
```python
from conan import conan_version
def build(self):
     if conan_version >= "2":
            # new code
     else:
           # old code
```

> What you're stating above is very interesting however. Could you point me to a good conanfile example in ConanCenter that is compatible to both ?

There is a list in https://github.com/conan-io/conan-center-index/discussions/16196 of the packages that are already simultaneously compatible with Conan 1.X and Conan 2.0. As you can see there are already some hundreds, just pick some of the libraries you depend on. Also, the default templates, created with ``conan new pkg/0.1 -m=cmake_lib`` will be compatible in Conan 1.X and Conan 2.0, which is very easy to experiment and try things.

> And how do you import the various methods from either "conans" or "conan" ? The class hierarchy has changed between V1.x and V2.

To achieve simultaneous compatibility only ``from conan`` should be used, those exist both in 1.X and 2.0 (they have existed in 1.X for years now).

**Comment by ATS-AValli** [comment]
Thank you very much, a lot of food for thought. I'll try to merge out conanfiles then: if I have any issues I'll add another comment here, otherwise I'll close.

**Comment by ATS-AValli** [comment]
Hi.
I've got an update: I've got quite ahead in bringing up an "hybrid V1/V2" version of a rather complicated conanfile. However, I'm encountering this error while attempting to run it with a 1.x version:
```
cmake = CMake(self, set_cmake_flags=False)
	TypeError: __init__() got an unexpected keyword argument 'set_cmake_flags'
```

The code is the same as the old V1 version, however the import statement at the beginning of the file is now different, I've moved from:
`from conans import ConanFile, CMake, tools
`
to 

`from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps, cmake_layout
`

It seems I'm picking a different class named CMake that does not understand `set_cmake_flags` as keyword argument.

Any ideas ?

**Comment by memsharded** [comment]
Yes, it is not only the import. The ``CMake`` is a new class, with an updated interface, different arguments and behaviors. The basics ``cmake.build()``, ``cmake.configure()`` are there, but some of the legacy things from the previous one have been removed. You can have a look at the new interface in https://docs.conan.io/1/reference/conanfile/tools/cmake.html

**Comment by ATS-AValli** [comment]
Unfortunately I couldn't change (too much) the old statements due to (rather dumb) company policy. But I was able to workaround the issue by moving the import statements into conan 1.x specific code thusly:

```
    @property
    def useV2(self):
        return conan_version >= "2"

    def configure_cmake(self):
        if(self.useV2):
            from conans import CMake as old_cmake
        
            cmake = old_cmake(self, set_cmake_flags=False)
            ...


```

(I'm essentially learning Python by hacking conanfiles, sorry).

So, by taking different code paths using `conan_version` (as suggested), changing generators in `configure()` and some of that import trickery above, I was able to obtain what I needed.

Thank you very much for the prompt responses.

**Comment by memsharded** [comment]
Ok, yes, that should make it.
The recipes will be for a while a bit more cluttered, but I still think it is much better to have 1 recipe centralized for both 1.X and 2.0 than having 2 recipes in 2 different places. It will be way easier to maintain and evolve in the transition and after.

Thanks to you for all the feedback!

**Comment by ATS-AValli** [comment]
Indeed they're a bit cluttered and I'm so much looking forward to drop the V1 compatibility (for us, it's more than simply conan V1.x, as it's associated with an old, in-house archaic build system that is the stuff of horrors).
Having said, I agree that the "single recipe" approach fits best.
I hope my notes here will be useful for anyone else who might find himself/herself in the same situation.

**Update**: here's a little bit more knowledge for any poor soul who might find him/her self in the same situation.
Using the technique above, as suggested by @memsharded  , of checking conan_version of course only works if conan_version exists; that happens only from conan 1.52 onward. In older versions this workaround can be used:

```
    @property
    def useV2(self):
        try:
            from conan import conan_version
        except ImportError:
            return False
        else:
            return conan_version >= "2"

```
