### ISSUE TITLE
FindXXX.cmake better support, so can just link some libraries

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#14]
When using conan Boost package, ALL boost libraries are returned in CONAN_LIBS variable. FindXXX.cmake files usually allow to configure which components you want, and only link those components.

It is unlikely that the existing FindBoost will work with the conan packages, as they are "flattened" to include, lib, bin directories, and FindBoost expect some hierachies. Probably a regular Find can be developed that wraps it and filters the libraries to link only the required.

Other possibility is to filter the CONAN_LIBS variable, it has to be checked the UX of this approach, if it fits well to different libraries name patterns (libraries with different names depending on settings), or if it might need some additional helpers to ease the task.

Related to #6

**Comment by Manu343726** [comment]
You can actually change that directories with input variables of the FindBoost module. `BOOST_ROOT` variable sets the boost root directory for example. There are variables for stage, library, sources, etc. Then just call `find_package(Boost)` as usually.

Here's the cmake script I wrote to bootstrap Boost with biicode, the link points to the line were those variables are set just before calling `find_package()`: https://github.com/biicode/boost/blob/master/blocks/boost/install/install.cmake#L207

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/commit/5a8425f9f5727f41d0b18c0ef7d116ef35f91c3d (will be included in release 0.5, is an advance in this issue. It allows package creators to provide their own FindXXX.cmake modules which are extremely simple, as all the necessary variables are already provided by conanbuildinfo.cmake. The result is that consumers can transparently use the typical FindXXX.cmake sintax, providing compatibility for conan and non-conan builds with the same CMakeLists.txt by just doing the INCLUDE(conanbuildinfo.cmake), if missing, it will fallback to the standard non-conan approach. @lasote is testing this feature with some libraries

**Comment by jslee02** [comment]
:+1: I am looking forward this feature. This will allow existing projects to consume packages installed by conan without modifying their `CMakeLists.txt`s but just `FindXXX.cmake`s.
