### ISSUE TITLE
[bug] conan1 transitive override fails in diamond dependency variation

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#14001]
### Environment details

* Operating System+version: ubuntu 20.04
* Compiler+version: gcc7
* Conan version: 1.60
* Python version: 3.10.9

### Steps to reproduce

Everything needed to reproduce the issue are documented in this repository: https://github.com/nicosmd/conan1-transitive-override-bug .
The problem seems to be so basic that I can't believe that it hasn't been caught yet by someone else but I was not able to find an issue which is similar to this one. So I'm very sorry when this bug is duplicated or not a bug but intended behavior.

**Comment by memsharded** [comment]
Hi @nicosmd 

Thanks for the report and for the repro case.

I have done a quick test capturing your repo:
```python
def test_nested_overrides():
    """
    https://github.com/conan-io/conan/issues/14001
    """
    c = TestClient()
    c.save({"liba/conanfile.py": GenConanfile("liba"),
            "libb/conanfile.py": GenConanfile("libb", "0.1").with_requirement("liba/0.1"),
            "libc/conanfile.py": GenConanfile("libc", "0.1").with_requirement("liba/0.1")
                                                            .with_requirement("libb/0.1"),
            "libd/conanfile.py": GenConanfile("libd", "0.1").with_requirement("liba/1.0",
                                                                              override=True)
                                                            .with_requirement("libc/0.1")})
    c.run("create liba 0.1@")
    c.run("create liba 1.0@")
    c.run("create libb")
    c.run("create libc")
    c.run("create libd --build=missing")
    print(c.out)
    assert "liba/1.0: Already installed!" in c.out
    assert "liba/0.1: Already installed!" not in c.out
```

And it happens to be passing, not failing.
I have also tried with your repo, executing directly from it, just in case I didn't capture something, and it also works.
Not sure what could I be missing.

**Comment by nicosmd** [comment]
Hey @memsharded I'm very sorry, I guess I forgot one important detail. I have tried to reproduce the issue with a clean installation and it passed for me too. Then I have noticed that we have enabled `error_on_override` in the configuration. And after enabling this, the error occurs again. Could you try again with enabling this configuration? Thank you very much.

**Comment by memsharded** [comment]
Ok, that makes sense, that is a much different story.
Actually, only a few users activate ``error_on_override``, so it is possible that there are some cases that were not correctly covered.

Conan 2.0 made ``error_on_override`` behavior built-in and compulsory, and the test above is passing, so those are the good news.

The bad news is that I have been having a look at this in Conan 1.X for the last hour and it looks pretty challenging to fix, I have tried a couple of approaches, but it seems it would need a huge effort with some architectural changes to be able to workaround it.

**Comment by nicosmd** [comment]
Yes, now it makes much more sense that this hasn‘t been caught yet by others. 

I totaly unterstand when this issue won‘t be fixed, since it is so complicated and it will never become an issue for the most users.
Fortunately, we are currently in the migration process towards conan2 but we would still need a least a dirty hack in our conanfiles to solve this. I have had described two possible workarounds on conanfile-Level in my Repo. Do you have a recommendation, which one we should use or do you see some other dirty hack, which you would prefer?

thank you very much in advance.

**Comment by memsharded** [comment]
yeah, I have been trying for a while to find a workaround, trying things like changing the order of ``requires``, adding ``overrides``, etc. with little success.

**Comment by memsharded** [comment]
Sorry I cannot find the workarounds in https://github.com/nicosmd/conan1-transitive-override-bug, did you push them?

Depending on how you install Conan, maybe a patch to Conan hardcoding this exception might help, I couldn't think of other alternative so far.

**Comment by nicosmd** [comment]
Sorry I should have explained where to find them. I just have written them in text in the last section of the Readme.

The first workaround I see would be to remove the requirement of liba in the conanfile of libc so that it is retrieved implicit through libb only. I‘m not sure, if this is sophisticated enough in conan1 and will work in any case. I think it is at least less explicit but I could live with that. 

The second workaround, which seems to work is to add an override=True to the requires statement of liba in libc. I have the feeling that this might be the better solution, since it seems to be only a bit redundant. But maybe i‘m missing some Important side effects with this approach.

I can provide some code examples of both if this would be helpful.

**Comment by memsharded** [comment]
I think I understand the two approaches.

I'd like to suggest however a third one. 
In general, ``overrides`` should be minimized. They are intended as a temporary solution, when it is not possible to change the dependencies upstream, until such dependencies really converge to the expected transitive dependencies.

As you are suggesting that you can modify ``libc``, and other recipes, why not just trying to update things to everyone depends directly on ``liba/1.0`` instead of ``liba/0.1``? I think this should be easier and more consistent, also moving forward with better compatibility with Conan 2.0.

**Comment by nicosmd** [comment]
You are absolutely right. Of course we can update basically the versions more consistent through the graph. We are currently rolling out newer upstream packages starting from downstream using override, so we will run quite often into the problem again. That's why I've tried to find any hacky solution. But I think we should rethink this strategy in general and try to keep the complete graph up to date using better CI or version ranges.

**Comment by nicosmd** [comment]
@memsharded should I close the ticket as won't fix? I think I have the answers I needed so for me it is fine to close the bug even it will not be solved.

**Comment by memsharded** [comment]
Closing as solved in Conan 2 (won't fix in Conan 1)
