### ISSUE TITLE
requirements method and python requires question

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#14008]
### What is your question?

Hi

In a recipe files requirements method the following code was added to conditionally include a recipe file.

if self.settings.compiler == 'tasking' and self.settings.make == 'gnu':
		self.requires("conan_tc39x_buildenv/1.1.3")

I tried to do a similar code with a python requires recipe file.
	if self.settings.make == 'gnu':
		self.python_requires = ("gnumake_pyreq/1.1.3")

The following error is generated when this code executes.
while calling 'csar_requirements', line 66
        GenCompMk = self.python_requires["gnumake_pyreq"].module.GenGNUCompMk
        TypeError: string indices must be integers, not 'str'

Setting python_requires = "gnumake_pyreq/1.1.3" at the beginning of the recipe file resolve this error. 

Is adding self.python_requires in a conditional statement not allow in Conan?  I want to only use this python requires methods if gnu make is the make utility being used for this build. A different python requires file would be used for a different make utility.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

The ``python_requires`` can only be declared as class attributes. They cannot be conditional, as they need to be evaluated before any conditional can be executed (as they can inherit behavior from them). You might need to add all of the ones that you need in the recipe. Take them as simple Python ``imports``, you typically include all the ``imports`` in the upper part of the Python script, even if you don't use them in every flow.

More info in docs in https://docs.conan.io/2/reference/extensions/python_requires.html

**Comment by Ed-CMI** [comment]
Thx
