### ISSUE TITLE
[question] "Override" conan center recipe with a local version

### ISSUE THREAD

**Issue by mlutken** [conan-io/conan#14003]
### What is your question?

Hi
I am using a recipe from conan-center (ICU) that does not currently work with Emscripten.
(eventually I can try and do a pull request to contribute my changes)

Right now I would really like to for example put this recipe along with the sources for my actual C++ project that uses this library in a way so that conan would simply pick up my file if present instead of using the one from conan-center.
Is there a way to do this?

If not do I then really need to run my own conan_server or JFrog server? Seems a bit excessive for an open source project like mine in the current stage I am in.

P.S. Thanks for a really great project :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mlutken 

It is not possible for Conan to automatically use the local file you have in your repo, but if you put it in a folder, then it is simply a ``conan export folder`` command, and it will be exported to the local cache and from there it will be available for usage.

We are working on a concept when it is possible to depend on a fork of ``conan-center-index`` github repo in https://github.com/conan-io/conan/pull/13930 but it is a bit too early for this.

I think the ideal would be to upstream the changes in a PR to ``conan-center-index`` repo (as long as they are reasonable and not-breaking)

**Comment by mlutken** [comment]
That seemed to work. Thanks a lot.
I have some other packages also that I need to get to work with emscripten.
ffmpeg among others. 
When/if I get them working I will be happy to try and make some PRs for the changes.

Just for anyone finding this. The command I used to export  ICU:
$ ... conan-center-index/recipes/icu/all$ conan export --version=73.1 .
