### ISSUE TITLE
[question] How to handle *.cmake macros in my package

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14013]
### What is your question?

Hello,
My package besides libs and include files contains two cmake files. Let's say they are Macros1.cmake Macros2.cmake.
And ofc I would like to have access to them in my test_package. I can not find anything like this on the internet.
I beg for the help...

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @damian-tomczak 

It seems the docs could be improved with an explicit example about this.

There are 2 alternatives:


1. The ``cmake_build_modules``, check https://docs.conan.io/2/reference/tools/cmake/cmakedeps.html?highlight=cmake_build_modules:

```python
def package_info(self):
    self.cpp_info.set_property("cmake_build_modules", [os.path.join("lib", "mypkg.cmake")])
```
This one is automatic, and injects the module in the consumer


2. Add the modules folder to the builddirs (https://docs.conan.io/2/reference/conanfile/methods/package_info.html#conan-conanfile-model-cppinfo)
```python
def package_info(self):
    self.cpp_info.builddirs = ["myfolder"]
```
Then explicitly include ``include(mymodule.cmake)`` in the consumer side

In both cases the ``find_package()`` to load the file generated by ``CMakeDeps`` is necessary
I prefer the second one, with explicit ``include()``, but I think both are possible

**Comment by damian-tomczak** [comment]
Okey, I have tried for an example something like this:
```py
        copy(self, "Macros.cmake", src=os.path.join(self.source_folder, "cmake_tools"), dst=os.path.join(self.package_folder, "cmake_tools"))
        ...
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.components["cmake_tools"].builddirs = ["cmake_tools"]
        self.cpp_info.components["cmake_tools"].set_property("cmake_target_name", "cmake_tools")
        
        self.cpp_info.components["mylib"].libs = ["mylib"]
        ...
```
```cmake
project(test_package)

find_package(conan-package-name REQUIRED COMPONENTS cmake_tools)
include(Macros.cmake)

mymacro()
   ```
and it throws 
```
cmake] CMake Error at CMakeLists.txt:7 (include):
[cmake]   include could not find requested file:
[cmake] 
[cmake]     Macros.cmake
```
Can you help?
@memsharded

**Comment by memsharded** [comment]
Did a test for your reference:
```python

@pytest.mark.tool("cmake")
def test_reuse_macro_from_dep():
    c = TestClient()
    pkg = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.files import copy
        class Pkg(ConanFile):
            name = "pkg"
            version = "0.1"
            package_type = "static-library"
            exports_sources = "*.cmake"
            def package(self):
                copy(self, "*.cmake", src=self.source_folder, dst=self.package_folder)
            def package_info(self):
                self.cpp_info.builddirs = ["."]
            """)
    pkg_macros = textwrap.dedent("""
        function(pkg_macro)
            message(STATUS "PKG MACRO WORKING!!!")
        endfunction()
    """)
    app = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.cmake import CMake

        class App(ConanFile):
            package_type = "application"
            generators = "CMakeToolchain"
            settings = "os", "compiler", "arch", "build_type"

            def requirements(self):
                self.requires("pkg/0.1")

            def build(self):
                cmake = CMake(self)
                cmake.configure()
                cmake.build()
        """)
    app_cmake = textwrap.dedent("""
        cmake_minimum_required(VERSION 3.15)
        project(App LANGUAGES NONE)

        include(Macros)
        pkg_macro()
    """)
    c.save({"pkg/conanfile.py": pkg,
            "pkg/Macros.cmake": pkg_macros,
            "app/conanfile.py": app,
            "app/CMakeLists.txt": app_cmake})

    c.run("create pkg")
    c.run("build app")

    assert "PKG MACRO WORKING!!!" in c.out
```
One key point is:
```
include(Macros)
```
without the .cmake extension

**Comment by damian-tomczak** [comment]
W

> Did a test for your reference:
> 
> ```python
> @pytest.mark.tool("cmake")
> def test_reuse_macro_from_dep():
>     c = TestClient()
>     pkg = textwrap.dedent("""
>         from conan import ConanFile
>         from conan.tools.files import copy
>         class Pkg(ConanFile):
>             name = "pkg"
>             version = "0.1"
>             package_type = "static-library"
>             exports_sources = "*.cmake"
>             def package(self):
>                 copy(self, "*.cmake", src=self.source_folder, dst=self.package_folder)
>             def package_info(self):
>                 self.cpp_info.builddirs = ["."]
>             """)
>     pkg_macros = textwrap.dedent("""
>         function(pkg_macro)
>             message(STATUS "PKG MACRO WORKING!!!")
>         endfunction()
>     """)
>     app = textwrap.dedent("""
>         from conan import ConanFile
>         from conan.tools.cmake import CMake
> 
>         class App(ConanFile):
>             package_type = "application"
>             generators = "CMakeToolchain"
>             settings = "os", "compiler", "arch", "build_type"
> 
>             def requirements(self):
>                 self.requires("pkg/0.1")
> 
>             def build(self):
>                 cmake = CMake(self)
>                 cmake.configure()
>                 cmake.build()
>         """)
>     app_cmake = textwrap.dedent("""
>         cmake_minimum_required(VERSION 3.15)
>         project(App LANGUAGES NONE)
> 
>         include(Macros)
>         pkg_macro()
>     """)
>     c.save({"pkg/conanfile.py": pkg,
>             "pkg/Macros.cmake": pkg_macros,
>             "app/conanfile.py": app,
>             "app/CMakeLists.txt": app_cmake})
> 
>     c.run("create pkg")
>     c.run("build app")
> 
>     assert "PKG MACRO WORKING!!!" in c.out
> ```
> 
> One key point is:
> 
> ```
> include(Macros)
> ```
> 
> without the .cmake extension

Works Thank you very very much <3

**Comment by memsharded** [comment]
No prob, happy to help!

I will submit the test for inclusion in the test suite anyway.
