### ISSUE TITLE
[question] How to set PKG_CONFIG_PATH used by PkgConfig tool while cross-compiling?

### ISSUE THREAD

**Issue by trampen** [conan-io/conan#14019]
There are many conan recipes in CCI built based on the documentation found here https://docs.conan.io/1/reference/conanfile/tools/gnu/pkgconfig.html

My question is how/where to set the PKG_CONFIG_PATH for the conan recipe's PkgConfig tool for case when there is cross-compilation uses?

**Package and Environment Details**
Package Name/Version: **vaapi/system**
Operating System+version run as docker container: Linux **debian9**-x86-dev 5.4.0-149-generic #166~18.04.1-Ubuntu SMP Fri Apr 21 16:42:44 UTC 2023 **x86_64** GNU/Linux
Compiler+version: **gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516**
Conan version: **1.60.0**
Python version: **3.9.13**

Docker recipe:
FROM amd64/debian:stretch

WORKDIR /root/
COPY sources.list /etc/apt

RUN apt update && apt upgrade -y && apt install -y build-essential default-jre doxygen valgrind autoconf libtool vim mc ruby flex libbison-dev git iputils-ping ssh devscripts debhelper pgpgpg cppcheck net-tools && apt clean
RUN apt install -y locales checkinstall pkg-config gcc-multilib g++-multilib pandoc wget libffi-dev zlib1g-dev libncursesw5-dev libncurses5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libbz2-dev libapr1-dev liblzma-dev openjdk-11-jdk && apt clean
RUN cd /tmp && wget https://www.python.org/ftp/python/3.9.13/Python-3.9.13.tgz && tar xzf Python-3.9.13.tgz && cd Python-3.9.13 && ./configure --enable-optimizations && make altinstall -j8 && cd /tmp && rm -rf Python-3.9.13*  && wget https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2.tar.gz && tar xzf cmake-3.23.2.tar.gz && cd cmake-3.23.2 && ./configure && make install -j8 && cd /tmp && rm -rf cmake-3.23.2* && update-alternatives --install /usr/bin/python python /usr/local/bin/python3.9 1 && update-alternatives --install /usr/bin/pip pip /usr/local/bin/pip3.9 1
RUN pip install --upgrade pip && pip install --no-cache-dir "conan<2.0.0" 

COPY x86 /root/.conan/profiles

RUN dpkg --add-architecture i386 && apt update && apt install -y libxml++2.6-dev:i386 libreadline-dev:i386 libcrypto++-dev:i386 libomnithread3-dev:i386 libasound2-dev:i386 libncurses5-dev:i386 libgpgme-dev:i386

**To reproduce the issue**
$ conan install -r conancenter --profile:host=x86 --profile:build=default --build=missing --json out.json  vaapi/system@

```
Configuration (profile_host):
[settings]
arch=x86
arch_build=x86
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=6
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
AUTOMAKE_CONAN_INCLUDES=/usr/lib/i386-linux-gnu/pkgconfig
CFLAGS=-m32 -fPIE -fPIC
CHOST=i386-linux-gnu
CONAN_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=/usr/include/i386-linux-gnu
CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=/usr/lib/i386-linux-gnu
CXXFLAGS=-m32 -fPIE -fPIC
LDFLAGS=-pie -L/usr/lib/i386-linux-gnu
PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
[conf]
tools.system.package_manager:mode=install

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=6
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: vaapi/system
Requirements
    vaapi/system from 'conancenter' - Cache
Packages
    vaapi/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Cross-build from 'Linux:x86_64' to 'Linux:x86'
Installing (downloading, building) binaries...
vaapi/system: Already installed!

JSON file created at '/home/workspace/conan_recipes/out.json'
ERROR: vaapi/system: Error in package_info() method, line 55
        pkg_config.fill_cpp_info(self.cpp_info.components[name])
        ConanException: pkg-config command ['pkg-config', '--print-provides', 'libva', '--print-errors'] failed with error: Command 'pkg-config --print-provides libva --print-errors' returned non-zero exit status 1.
**Package libva was not found in the pkg-config search path.**
Perhaps you should add the directory containing `libva.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libva' found
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @trampen 

Thanks for your question. I think it is a duplicate of https://github.com/conan-io/conan/issues/13962, please check it and let me know, so we can close this issue and track the previous one.

Indeed there is some gap for cross-compiling recipes that use the ``PkgConfig`` tool for getting things from the system. I have opened a new line of work in https://github.com/conan-io/conan/pull/13985, but that means a relatively big change, so it might take some time.

In the meantime, it seems that setting the env-var at the system level (command line before conan invocation) might be necessary.

**Comment by trampen** [comment]
@memsharded thanks for fast response, according to your tip, invoking command as below can meanwhile solve the problem

`$ PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig conan install -r conancenter --profile:host=x86 --profile:build=default --build=missing --json out.json vaapi/system`@

**Comment by memsharded** [comment]
Perfect, happy that the workaround worked for you. Still, for being able to automate that better with Conan, please track the other ticket for future progress. Thanks!
