### ISSUE TITLE
[question] Incremental builds with tests

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14029]
### What is your question?

Hello,

I am not certain whether it is more of a CMake or a Conan question.
You can find my example repo [here](https://github.com/Todiq/test_conan/tree/tests).

I would like to be able to build my tests folders incrementally. In fact, I am currently facing the following behaviour:
- I build my project from scratch using ```conan build .```  &rarr; All sources except those for tests are built
- I build my project  from scratch using ```conan build . --conf tools.build:skip_test=False```  &rarr; All sources are built, including the tests ones
- I first build my project with ```conan build .``` then I build a second time using ```conan build . --conf tools.build:skip_test=False``` &rarr; All sources except those for tests are built ***but*** the second build does not do anything. (I get a ```ninja: no work to do``` message. A similar one is displayed using make)

Now my question is: Would it be possible to build a first time without including the tests, then compile them later on without having to delete my ```build``` folder and compile everything from scratch? Did I do anything wrong within my ```conanfile.py```and/or my ```CMakeLists.txt```? I can't be sure. Could I please get some help?

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your question.

The main issue here is the build system (CMake) cache.
The ``conan build`` command will call the ``build()`` method, but it is completely agnostic of the actual build system behavior. In the case of CMake, it is doing incremental builds, this is very desired beahavior, not doing a clean build every time.
But it also means that if the build system requires cleaning the cache for some updates, then it is something that only the developer knows and should be doing manually. In any case, even if the switch test/no-tests could be fine, CMake is not able to correctly regenerate the CMake cache, and it doesn't do the right thing. 

So for this use case, I think the only possibility is the developer cleaning the CMake cache manually before changing configuration. 

Does this make sense?

**Comment by Todiq** [comment]
Removing the ```CMakeCache.txt``` did the trick. Thank you very much
