### ISSUE TITLE
[question] Debugging conan using VS Code

### ISSUE THREAD

**Issue by Tobulus** [conan-io/conan#14025]
### What is your question?

Hi,

this is probably a dump question but I'm not working regularly with python.

I want to debug conan using VS Code and then step into multiple files. So I use [conan.py](https://github.com/conan-io/conan/blob/develop/conans/conan.py) as an entrypoint using a standard python debug launch.js.

Now the problem is I can't set any breakpoint outside this file as they will not get hit, which is probably due to the imports done in that file. The are taken from the local conan installation, not the git checkout. If I just move the `conan.py` into the root of the git repo everything works as expected.

So how should I handle this? I want to use the files of the local checkout. Maybe you are also using VS Code and can give a hint how to handle this.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by nrbnlulu** [comment]
duplicated https://github.com/conan-io/docs/issues/3195

**Comment by nrbnlulu** [comment]
For a reference you can just call the cli interface from Python.
```py
import os
import sys

from conans.conan import run
from pathlib import Path

if __name__ == '__main__':
    os.chdir(Path(__file__).parent.parent)  # change working dir to root
    sys.argv = "conan build .".split(" ")  # put your commands here
    sys.exit(run())
```
put this in a file and debug it.

**Comment by Tobulus** [comment]
Works, thanks!
