### ISSUE TITLE
[bug] MesonToolchain does not handle CXX, CC with arguments included, needs separate LD handling

### ISSUE THREAD

**Issue by Talkless** [conan-io/conan#14028]
### Environment details

* Operating System+version: Debian 11 bullseye
* Compiler+version: GCC 10
* Conan version: 1.60.0
* Python version: 3.9.2

### Steps to reproduce

I have toolchain called `fsl-imx-wayland-glibc-x86_64-core-image-base-cortexa53-crypto-imx8mmevk-toolchain-5.10-hardknott.sh` which has encironment setup script `environment-setup-cortexa53-crypto-poky-linux` defining CXX an C like this:
```bash
export CC="aarch64-poky-linux-gcc  -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=$SDKTARGETSYSROOT"
export CXX="aarch64-poky-linux-g++  -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=$SDKTARGETSYSROOT"
```

In other words, CC and CXX has arguments embedded together with executable name. And Meson does not like that:

```
../src/meson.build:1:0: ERROR: Unknown compiler(s): [['aarch64-poky-linux-gcc  -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/opt/fsl-imx-wayland/5.10-hardknott/sysroots/cortexa53-crypto-poky-linux']]
```

Because geenrated `conan_meson_cross.ini` has:

```ini
[binaries]
c = 'aarch64-poky-linux-gcc  -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/opt/fsl-imx-wayland/5.10-hardknott/sysroots/cortexa53-crypto-poky-linux'
cpp = 'aarch64-poky-linux-g++  -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/opt/fsl-imx-wayland/5.10-hardknott/sysroots/cortexa53-crypto-poky-linux'
```
It Works For Me™ after implementing workaround/hack/fix in `tools/meson/toolchain.py` by generating `c` and `cpp` as lists:
```diff
42,43c42,43
<     {% if c %}c = '{{c}}'{% endif %}
<     {% if cpp %}cpp = '{{cpp}}'{% endif %}
---
>     {% if c %}c = {{c}}{% endif %}
>     {% if cpp %}cpp = {{cpp}}{% endif %}
49a50
>     {% if ld %}ld = {{ld}}{% endif %}
173,174c174,175
<         self.c = compilers_by_conf.get("c") or build_env.get("CC") or default_comp
<         self.cpp = compilers_by_conf.get("cpp") or build_env.get("CXX") or default_comp_cpp
---
>         self.c = self._quote_or_none(compilers_by_conf.get("c") or self._get_env_list(build_env.get("CC")) or default_comp)
>         self.cpp = self._quote_or_none(compilers_by_conf.get("cpp") or self._get_env_list(build_env.get("CXX")) or default_comp_cpp)
176,177c177,179
<         self.c_ld = build_env.get("CC_LD") or build_env.get("LD")
<         self.cpp_ld = build_env.get("CXX_LD") or build_env.get("LD")
---
>         self.c_ld = build_env.get("CC_LD")
>         self.cpp_ld = build_env.get("CXX_LD")
>         self.ld = self._get_env_list(build_env.get("LD", []))
201a204,210
>     def _quote_or_none(self, value):
>         # do not quote lists, ignore None
>         if value is None or isinstance(value, list):
>             return value        
>         
>         return f"'{value}'"
> 
303a313,315
>         if v is None:
>             return v
>
```
Basically, I had to remove quotes around `cc` and `cxx` in the template, as lists should not have those, but quote later when needed.

Also, I had to separate `LD` env. value into `ld` for meson because of:
```
../src/meson.build:1:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not aarch64-poky-linux-ld  --sysroot=/opt/fsl-imx-wayland/5.10-hardknott/sysroots/cortexa53-crypto-poky-linux.
```
From IRC:

> [Friday, June 2, 2023] [2:23:00 PM EEST] <elibrokeit> Talkless: the cpp_ld value needs to be something that can be passed as -fuse-ld= 

> [Friday, June 2, 2023] [2:41:56 PM EEST] <elibrokeit> LD is not the same as CXX_LD so I guess conan should not do this
[Friday, June 2, 2023] [2:42:37 PM EEST] <elibrokeit> LD is the kind of thing I'd expect to see being used when manually linking objects with ld, not when using the compiler as the linker driver

**Comment by tbsuht** [comment]
The second problem regarding `LD` is the same problem as stated [here](https://github.com/conan-io/conan/issues/13824#issuecomment-1576243695).

**Comment by memsharded** [comment]
Hi @Talkless 

Sorry for late reply.

I think there might be 2 different issues here, as @tbsuht suggests. One would be the quoting, the other would be the LD thing. I suggest focusing first on LD, then treat the quoting in a separate issue.

Regarding LD, great that you got some internal messages, but the official docs in https://mesonbuild.com/Reference-tables.html#compiler-and-linker-selection-variables seems not clear. Do you have any other link or source that explains a bit better what is what in Meson definitions?

Maybe you want to try to submit a PR with the ``self.ld = self._get_env_list(build_env.get("LD", []))`` change?

**Comment by tbsuht** [comment]
> Regarding LD, great that you got some internal messages, but the official docs in https://mesonbuild.com/Reference-tables.html#compiler-and-linker-selection-variables seems not clear. Do you have any other link or source that explains a bit better what is what in Meson definitions?

Only found this: https://mesonbuild.com/howtox.html#set-linker
"With the former c_ld or CC_LD should be the value to pass to the compiler's special argument (such as -fuse-ld with clang and gcc)"

**Comment by franramirez688** [comment]
Hi @Talkless 

Thanks a lot for reporting the issue!
Have you tried to split those flags? Something like this:

```bash
export CC="aarch64-poky-linux-gcc "
export CXX="aarch64-poky-linux-g++"
export CFLAGS="-mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=$SDKTARGETSYSROOT"
export CXXFLAGS="-mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=$SDKTARGETSYSROOT"
```
Could this approach work fine?

**Comment by Talkless** [comment]
> Could this approach work fine?

Probably, I don't recall trying that, but these variable where generated by third party toolchain for some NXP ARM device, so idea is make it work without workarounds, especially if Meson supports passing defining arguments to compilers via list. This would require patching environment scripts on every toolchain reinstall/upgrade.

Strangely, even if `CC` is defined in environment setup script like this:
```
export CC="aarch64-poky-linux-gcc  -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=$SDKTARGETSYSROOT"
```
There's additional `CFLAGS` too:
```
export CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types "
```
So not sure what to make of it.
