### ISSUE TITLE
[question] Dependency with makefile

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14023]
### What is your question?

Hi,

I'm refactoring my project/lib to the conan package. And I have hit to the problem.
My project has external dependency that so far I was downloading it by fetchcontent via cmake and building it thanks to add_costum _command.

Building of this external dependency is quite simple because "make" is enough:
```py
from conan import ConanFile
from conan.tools.gnu import Autotools, AutotoolsDeps, AutotoolsToolchain


class XdpTools(ConanFile):
    name = "xdp-tools"
    version = "f1.0"
    settings = "os", "arch", "compiler", "build_type"
    exports_sources = "*"

    def generate(self):
        tc = AutotoolsToolchain(self)
        tc.generate()

    def build(self):
        autotools = Autotools(self)
        autotools.configure()
        autotools.make()

    def package(self):
        autotools = Autotools(self)
        autotools.install()

    def package_info(self):
        self.cpp_info.components["xdp"].libs = ["xdp"]
        self.cpp_info.components["xdp"].set_property("cmake_target_name", "xdp")

        self.cpp_info.components["bpf"].libs = ["bpf"]
        self.cpp_info.components["bpf"].set_property("cmake_target_name", "bpf")
```
then I'm building the package and sending it to my local artifactory.

My project/lib looks this way:
```py
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake
from conan.tools.files import copy

class MyLib(ConanFile):
    name = "MyLib"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    exports_sources = "*"
    generators = "CMakeDeps"
    requires = [
        ...
        "xdp-tools/f1.0"]

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure({})
        cmake.build()

    def package(self):
        ...
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        ...
        self.cpp_info.components["xdpwrapper"].libs = ["myxdp"]
        self.cpp_info.components["xdpwrapper"].requires = ["xdp-tools::xdp-tools"]
        self.cpp_info.components["xdpwrapper"].set_property("cmake_target_name", "xdpwrapper")

        self.cpp_info.components["logger"].libs = ["logger"]
        self.cpp_info.components["logger"].requires = [...]
        self.cpp_info.components["logger"].set_property("cmake_target_name", "analytics")
```

and while cmake configuration it throws an error:
```
[cmake] CMake Error at build/cmakedeps_macros.cmake:64 (message):
[cmake]   Library 'bpf' not found in package.  If 'bpf' is a system library, declare
[cmake]   it with 'cpp_info.system_libs' property
```
I'm not sure what is the problem here. I think that I did something wrong in xdp's conanfile.
In advance thank you very much <3

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by damian-tomczak** [comment]
I doubt it would be related but I'm adding xdp-tools at the level of cmake this way:
```cmake
find_package(xdp-tools REQUIRED COMPONENTS xdp bpf)

target_link_libraries(${PROJECT_NAME} PUBLIC
    ...
    xdp
    bpf
    ...
)
```

**Comment by czoido** [comment]
Hi @damian-tomczak,

Thanks for the question. I suspect that could be related to the `bpf` library not being packaged correctly in the `xdp-tools` package, maybe the `libbpf.a` file is not copied correctly during the `package()` method of the recipe. Could you check if the library is correctly packaged?

**Comment by damian-tomczak** [comment]
> Hi @damian-tomczak,
> 
> Thanks for the question. I suspect that could be related to the `bpf` library not being packaged correctly in the `xdp-tools` package, maybe the `libbpf.a` file is not copied correctly during the `package()` method of the recipe. Could you check if the library is correctly packaged?

You had right. Thank you very much

**Comment by czoido** [comment]
I'm glad to hear that! 😄 closing the issue then
