### ISSUE TITLE
[question] How can I get access to the Slack channel?

### ISSUE THREAD

**Issue by tarcisiofischer** [conan-io/conan#14035]
### What is your question?

Hi. I'm trying to get access into your Slack channel, hoping to get some help there.
In Conan's README.md there's two links:

(a) Slack: https://cpplang.slack.com/ (#conan channel)
This one requires me to have a `@aurescapital.com` email in order to sign up. I have no idea how to get one of those? - I also tried to login with my Google email, but it says `The email address must match one of the domains listed below. Please try another email.`

(b) Slack (https://cpplang-inviter.cppalliance.org/ #conan channel).
This one takes me to the Boost.org web page, I'm guessing it is an old link?

How can I get access to the Slack channel? Is it better to just ask questions here in the `Issues` page instead?

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tarcisiofischer 

Maybe try the first link in https://cppalliance.org/slack/? Please let me know if it works that way

**Comment by tarcisiofischer** [comment]
Thank you, seems to be working now! Had no idea that I needed to do that.

**Comment by Xevion** [comment]
Hi, I think this issue should be reopened or worked on, as the Slack links are still misleading and aren't helpful if you aren't already part of the Cpplang Slack.
