### ISSUE TITLE
Allow tag string when building a package

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#1403]
Say you're building a package, and the source (including the recipe) is in a git repository. I think it would be nice to be able to be able to trace a package back to a given head of the repository. You couldn't put it in the description itself because then you'd have to commit that and it would change the head. Therefore it would be nice if you could specify it on the command line when building the package. Then that would be queryable from the package later. Does that make sense?

**Comment by memsharded** [comment]
Yes, could make sense. Actually, this would be in parallel to a review of the ``conan export`` in which the version and name not necessarily encoded in the package recipe, as they could be specified in the ``conan export`` itself, and the conan model doesn't need it later on.

More people interested in this feature?

Could it be related to the current feature request of supporting arbitrary properties in conanfiles? https://github.com/conan-io/conan/issues/1100

**Comment by memsharded** [comment]
This flow has been implemented in the ``export`` method, storing things in the ``conandata.yml``, closing as solved.

See for example: https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html
