### ISSUE TITLE
[feature] A way to ignore (disable) system requirements when building for custom sysroots

### ISSUE THREAD

**Issue by Talkless** [conan-io/conan#14037]
### What is your suggestion?

Custom built sysroots for custom ARM hardware may not have any package manager.

Package like `gst-plugins-base` requires `xorg/system` (https://github.com/conan-io/conan-center-index/blob/0d701c828841e853487db48870b9c789ee77b2c9/recipes/gst-plugins-base/all/conanfile.py#L107) or `opengl/sytem` libraries, but checking for those fails as there's no `libx11-dev` per se, but there _are_ actual headers and libraries available in the toolchain's sysroot.

While packages might have some extra options to disable these requirements, maybe there would be better way to pass some sort of `[config]` for whole build inside profile to disable all `system_requirements()` or by some other means?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Talkless 

Thanks for your suggestion. 
Have you tried the ``tools.system.package_manager:mode=report`` mode? I think this should do what you are looking for.

**Comment by Talkless** [comment]
Thanks!
