### ISSUE TITLE
[question] how to configure conan_download_cache size?

### ISSUE THREAD

**Issue by GeFrIt42** [conan-io/conan#14034]
### What is your question?

The conan download cache seems to be limited to circa 5.5GB.
in my current project there are packages that are quite big 500MB+ compressed.

is there a way to configure conan_download_cache size to be bigger?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @GeFrIt42 

The conan cache is not restricted in any way, it can grow up to the disk size.
I hope it was a different thing and that is working as expected.

**Comment by GeFrIt42** [comment]
hi,

Thank you for the fast feedback,
I have realized after opening the ticket that i had a script that was cleaning the download cache,
The cache is working as you have described,
