### ISSUE TITLE
brew and pip install installing old version (1.52)

### ISSUE THREAD

**Issue by imf** [conan-io/conan#14036]
### Environment details

* Operating System+version: 
*Darwin cobalt 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:43 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8112 arm64
* Compiler+version:
* Conan version: 1.52
* Python version: Python 3.9.13

### Steps to reproduce

1. On a fresh install
2. Either pip install or brew install Conan
3. Expected: Current version installed.
4. Actual: 1.52 installed.

brew upgrade conan and pip install conan --upgrade both seem to think 1.52 is the latest, though a colleague has a later version he installed earlier.

**Comment by imf** [comment]
Sorry, it seems like pip was correctly installing 2.0.6 but that I had another version on my path (possibly from the brew install?)

**Comment by czoido** [comment]
Hi @imf,
Thanks for the question. Yes, probably it's a pip or brew install at system level. We normally recommend using virtual environments to install Conan ([docs](https://docs.conan.io/2/installation.html)) although the [latest release](https://github.com/conan-io/conan/releases/tag/2.0.6) also comes with an executable for Linux and Windows system you can put in your path and use directly (we will also have a macOS version soon).
I will close the issue as it seems solved but please feel free to reopen if you have more questions 🙂
