### ISSUE TITLE
[question] conan list using a profile

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#14045]
### What is your question?

Hi,

I was wondering whether it's possible to provide a profile to the `conan list` command in Conan 2.x or why it is not available?

Typical workflow in our CI is calling multiple `conan create` sequentially  with different profiles. After every call I want to query the revision of that package ... but can't really filter for it without listing everything manually via the package query parameter.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tbsuht 

There is the ``conan list -p "os=Windows"`` package query format that would be the closer.

In any case, for your flow, the recommendation wouldn't be doing ``conan list`` but capturing the output of the ``conan create ... --format=json > graph.json``, then getting the created revision from the ``graph.json``. You might be able to ``conan list --graph=graph.json`` from Conan 2.0.7, but you really want to make sure that you get the output from the actual ``conan create`` command, and not after, to avoid any possible race condition (imaging other ``conan create`` running in the middle)

**Comment by tbsuht** [comment]
Sounds good, I will try that, thanks!
