### ISSUE TITLE
[question] How to get the conandata.yml

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14043]
### What is your question?

Hi, I would like to create my own version of the package from conancenter, namely: https://conan.io/center/spdlog?tab=overview&os=Linux

I need for it conandata.yml but I don't know how to get it?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by damian-tomczak** [comment]
Okay I found it here: https://github.com/conan-io/conan-center-index/tree/master/recipes/spdlog

**Comment by memsharded** [comment]
Hi @damian-tomczak

Thanks for your question.
The packages from ConanCenter are created from the recipes in the Github repo: https://github.com/conan-io/conan-center-index. So if you fork and clone this repo, then you can go to the folder that you want and do there a ``conan create . --version=xxxx``. The ``conandata.yml`` is there, so you can modify the file if that is what you mean: https://github.com/conan-io/conan-center-index/tree/master/recipes/spdlog/all

Is this what you are asking for?

In case you are building your packages this way just take this into account: ConanCenter applies a hook (it is also available in the hooks repo), that trims the ``conandata.yml`` to the version that it is being currently packaged, to guarantee that revisions remain stable, that is, that adding a new version to the ``conandata.yml`` doesn't modify the previous recipe-revisions of previous versions.

Also, if the modification to the recipes conandata.yml that you are thinking of is mostly to do a backup of the sources from the internet to point to your copy, we are releasing a feature to do this automatically.
