### ISSUE TITLE
[question] conanfile.py virtualenvs

### ISSUE THREAD

**Issue by nrbnlulu** [conan-io/conan#14047]
### What is your question?

What if a `conanfile.py` on another package uses a python dependency that clashes with mine?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nrbnlulu 

Conan recipes ``conanfile.py`` shouldn't be installing Python dependencies at all. It is ok for some recipes to use the ``system_requirements()`` and ``SystemPackageTool`` to call the system package manager like ``apt`` and install some system package. It shouldn't be common but can be done, some packages in ConanCenter do it.

But Python packages are a different story, they should not be installed from Conan recipes, and then, it is impossible that they would be colliding or conflicting. There is some initiative in https://github.com/conan-io/conan/pull/11601, that we will continue working on after 2.0 stabilizes and Conan 2.X backlog starts to flow, that could help with this, but at the moment it is not recommended.

**Comment by nrbnlulu** [comment]
OK, Thanks!
