### ISSUE TITLE
[question] How to expose cmake files generated by package to consumer

### ISSUE THREAD

**Issue by Conzxy** [conan-io/conan#14048]
### What is your question?

I'm a new user for conan. In [reference of package_info](https://docs.conan.io/2/reference/conanfile/methods/package_info.html#reference-conanfile-methods-package-info)，has the following content:

> For example, if your package creates xxx-config.cmake files at build time, and they are put in the final package, it might not be necessary to define package_info() at all, and in the consumer side the CMakeDeps would not be necessary either, as CMakeToolchain is able to inject the paths to locate the xxx-config.cmake files inside the packages.

But this don't show the example code, I want to expose the xxxConfig.cmake generated by CMakeLists.txt of my packge to the consumer.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Conzxy 

Thanks for your question.

For achieving this 2 things must be done in the recipe:
- Make sure the generated xxx-config.cmake file from the builds get packaged in the ``package()`` method. If it is encoded in the ``CMakeLists.txt`` install, then calling ``cmake.install()`` should be enough.
- Declare this for the consumers in the ``package_info()`` method, like (depending on the folder containing the file):
```python
def package_info(self):
      self.cpp_info.builddirs.append("cmake")  # assumes xxx-config.cmake in the "cmake" folder
```

Then the consumers using ``CMakeToolchain`` will automatically use it via ``find_package()``.
Please try this and let us know. We will eventually add an example to the docs with this exact thing.

**Comment by Conzxy** [comment]
@memsharded 
Thany you for your reply, this is works.
It seems that add path to the `CMAKE_MODULE_PATH` variable.
But the xxx-config.cmake and other *.cmake generated by conan is also copyed to the build directory of consumer project directory, and it may cause the CMake search the xxx-config.cmake in the build directory rather than my specified config.
I want to disable the behavior, what I should do?
I try to remove the `tc.generate()` statement of `ConanFile::generate()` method:
```python
 def generate(self):
      [..]
      tc = CMakeToolchain(self)
      [..]
      tc.generate()       # <- remove
```
but this will trigger a error in `ConanFile::build()` method.

**Comment by Conzxy** [comment]
Oh, I read the code of conan and find the following code is helpful for me:
```python3
# /conan/tools/cmake/cmakedeps/cmakedeps.py
    @property
    def content(self):
            [..]
            cmake_find_mode = self.get_property("cmake_find_mode", dep)
            cmake_find_mode = cmake_find_mode or FIND_MODE_CONFIG
            cmake_find_mode = cmake_find_mode.lower()
            # Skip from the requirement
            if cmake_find_mode == FIND_MODE_NONE:
                # Skip the generation of config files for this node, it will be located externally
                continue

            if cmake_find_mode in (FIND_MODE_CONFIG, FIND_MODE_BOTH):  # <- Disable config file generation
                self._generate_files(require, dep, ret, find_module_mode=False)

            if cmake_find_mode in (FIND_MODE_MODULE, FIND_MODE_BOTH): # <- Allow the search of module path
                self._generate_files(require, dep, ret, find_module_mode=True)
            [..]
```
I try to set the `cmake_find_mode` to `none`, but it also remove the module path in `CMAKE_MODULE_PATH`.
Then, I try to set it to `module`, the `xxx-config.cmake` and other files are not generated by conan and `CMAKE_MODULE_PATH` contains expected paths. 

The problem has solved I think. The solution code as following:
```python
def package_info(self):
    self.cpp_info.builddirs.append('xxxxx') # <- the relative path of package folder
    self.cpp_info.set_property("cmake_find_mode", "module") # <- The xxx-config.cmake is not generated by conan
```

**Comment by jasonbeach** [comment]
I'm trying to understand this myself (see https://stackoverflow.com/q/76222222/2748602)

It seems weird that you set `cmake_find_mode` to `module` since we actually want `config` mode. 

How do you specify the path 'xxxxx' as that could be `build/Release`  `build/Debug` or somewhere in the conan cache when the package it built (e.g. `~/.conan2/p/b/say95ca0375f5dae/p/lib/cmake/say/say-config.cmake` (package install directory) or
`~/.conan2/p/b/say95ca0375f5dae/b/build/Release/say-config.cmake` (package build directory)

**Comment by Conzxy** [comment]
@jasonbeach 
The `xxxxx` is a relative path to the package folder.
Suppose the package folder in local cache as following:
```
~/.conan2/p/xxxxx2c1ad5c5b0e50/p
├── include
├── lib
└── xxxxx 
```
The `xxxxx` is the `~/.conan2/p/xxxxx2c1ad5c5b0e50/p/xxxxx` in fact.

**Comment by jasonbeach** [comment]
ah. so my standard practice is to install the cmake config files in <install_prefix>/lib/cmake/<library_name> e.g. `/usr/local/lib/cmake/foo/` so I would just have to add
 
    self.cpp_info.builddirs.append("lib/cmake/foo")

to my `package_info` method

**Comment by Conzxy** [comment]
@jasonbeach 
Yes. If you want install your custom cmake config files to system directory, e.g. `/usr/lib/cmake/xxxx`, the path is good.
But for conan, this is different.

I summarize some helpful usage as below.

## Add custom search path
* For package mode, you just add lib/cmake/xxxx to `cpp_info.builddirs` in `package_inf()`, in fact, it append it to the `CMAKE_MODULE_PATH` variable of `CMake`.
* For editable mode, you can achieve it by the following code:
```python
    def layout(self):
        [..]
        # The directory contains CMakeLists.txt, ie. project root directory
        self.folders.source = '.'

        # build/Debug
        # build/Release
        # Avoid clean build when switch between debug and release
        self.folders.build = os.path.join("build", str(self.settings.build_type))

        self.cpp.build.builddirs.append['.'] # Relative to the self.folders.build
        [..]
```

## Find mode influence
* For package mode, if you set the `cmake_find_mode` to `none`, the `CMAKE_MODULE_PATH` will be empty although I don't know the reason. So, I set the `cmake_find_mode` to `module` and it works.
* For editable mode, the `none` or `module` of `cmake_find_mode` does works.

**Comment by jasonbeach** [comment]
I've set `cmake_find_mode` to `none` and at least for now it seems to work. Good point on editable packages, although those files aren't really meant to be used in a build context, so I'll have to poke around and see how that works.

**Comment by memsharded** [comment]
There are different things in this thread:

- It is possible to use the in-package xxx-config.cmake, following the above guide, and using **only** the ``CMakeToolchain`` generator, but not ``CMakeDeps``. This assumes that all dependencies do package their xxxx-config.cmake (I assumed this was your case, I didn't think you were also using ``CMakeDeps`` too)
- If ``CMakeDeps`` is used, then it will generate files for dependencies. There are 2 ways to inhibit this default behavior:
   - In the dependency ``package_info()`` is possible to set ``cmake_find_more`` property
   - Defining the ``CMakeDeps.set_property()`` in the consumer, for the desired dependencies, to control that, so it is not needed to modify the dependency

I hope this clarifies a bit further.

**Comment by memsharded** [comment]
Is there any pending issue to clarify? Or can we close this ticket? Thanks!

**Comment by jasonbeach** [comment]
I'm good... No questions at the moment, but give me 5 minutes 🤣

**Comment by Conzxy** [comment]
I set the `cmake_find_mode` to `none`, it works also.
The generation of config files can be disabled by consumer side also using `CMakeDeps::set_property("xxxxx", "cmake_find_mode", "none")`.
The question can be closed.

**Comment by memsharded** [comment]
Great, thanks!
