### ISSUE TITLE
[question] how to fix conan recipe so transitive dependencies are handled

### ISSUE THREAD

**Issue by jasonbeach** [conan-io/conan#14050]
### What is your question?

Minimum example I've posted here https://github.com/jasonbeach/conan_example 

That repo has two packages (based on `conan` tutorials, but heavily modified as I experimented). Package `say` is a library that provides a function `say`. I've modified it so the function takes a type from a dependency, in this case `Eigen`. I also included `fmt` as the same behavior can be observed with it (if it's included in `say`'s header). 

I can build `say` fine (within the `say` directory) by
```
conan install .
cmake --preset conan-release
cmake --build --preset conan-release
```
or
```
conan create . 
```
If I install `Eigen` and `fmt` on my system I can also build and install `say` fine without `conan` by simply
```
mkdir build
cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
sudo ninja install
```
for `hello` which is just a simple app (that depends on `say` and so transitively depends on `Eigen` and `fmt`) I would've 
expected that 
```
conan install .
cmake --preset conan-release
cmake --build --preset conan-release
```
should work, but the build step fails:
```
$ cmake --build --preset conan-release 
[1/2] Building CXX object CMakeFiles/hello.dir/src/hello.cpp.o
FAILED: CMakeFiles/hello.dir/src/hello.cpp.o 
/usr/bin/c++  -isystem /home/react/.conan2/p/b/say648176e1eb3fa/p/include -m64 -O3 -DNDEBUG -std=gnu++14 -MD -MT CMakeFiles/hello.dir/src/hello.cpp.o -MF CMakeFiles/hello.dir/src/hello.cpp.o.d -o CMakeFiles/hello.dir/src/hello.cpp.o -c /workspaces/react/conan/hello/src/hello.cpp
In file included from /workspaces/react/conan/hello/src/hello.cpp:1:0:
/home/react/.conan2/p/b/say648176e1eb3fa/p/include/say/say.h:9:10: fatal error: Eigen/Dense: No such file or directory
 #include "Eigen/Dense"
          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
however it **does** work as expected if I don't use `conan` (i.e. system install `Eigen`,  `fmt`, and `say`.) The `cmake` config files I define properly includes the transitive dependencies so they can be included in the compiler invocation (I would've expected there being an accompanying `-isystem` entry for both `eigen` and `fmt`.) 

So it seems that somehow in the `cmake` config files that are generated by `conan`, those transitive dependencies aren't being handled quite right. `CMake` successfully runs which means it's finding the packages, but the `INTERFACE_INCLUDE_DIRECTORIES` are somehow not getting populated and so don't get sent through to the compiler.

I assume that I'm just not defining the `conanfile.py` in `say` correctly, but I'm not sure where. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @jasonbeach, thanks a lot for your question.

Have you taken a look into [requirement traits](https://docs.conan.io/2/reference/conanfile/methods/requirements.html#requirement-traits)? They define how different information about a requirement is treated an propagated by Conan, and looking into your issue, it looks like that's where you will need to look into

To give a bit more context, say your dependency graph looks something like:
```mermaid
graph LR;
    hello-->say;
    say-->eigen;
```

For the general case, there are two possible cases here:
 * If `hello` directly uses functionality implemented in `eigen` headers (which is not your case, but still), then it should properly declare that `eigen` is a direct dependency of itself, such that the graph looks like:
```mermaid
graph LR;
    hello-->say;
    hello-.->eigen;
    say-->eigen;
```
 * If `hello` does not directly use `eigen` but its types are part of the API of `say`, then `say` should set the requirement trait `transitive_headers` to `True` (And `transitive_libs` for those libs that also need the libs in the general case).
```mermaid
graph LR;
    hello-->say;
    say-. transitive_headers=True .->eigen;
```

To get a better understanding on how traits work, I'd also recommend watching [this video](https://www.youtube.com/watch?v=kKGglzm5ous) by @memsharded which deals with how Conan models this.


Let me know if this helps :)

**Comment by jasonbeach** [comment]
I had, but I guess I had thought those would be True by default (for a library).  I guess thinking about this now, it follows `CMake`'s method of annotating a dependency in something like a `target_link_libraries` call as either `PUBLIC`, `PRIVATE` or `INTERFACE`.  I hadn't grokked that that level of granularity had now been exposed for dependencies in the `conanfile.py` Thanks--I knew it had to be something simple I was missing.

**Comment by jasonbeach** [comment]
Maybe one follow on question, does `transitive_headers=True` imply `transitive_libs=True`  It seems like more often than not when you want one, you'd want the other so specifying them both seems overly verbose.

**Comment by memsharded** [comment]
> Maybe one follow on question, does transitive_headers=True imply transitive_libs=True

Libs transitivity works automatically in the majority of cases, it is more unusual having to modify it. 

Automatically defining it when ``transitive_headers=True`` is not a good idea, because that would break the correct transitivity of shared-static static-static. The fact that the headers are included in the public headers do not necessarily change the way the compiled library is propagated.

**Comment by jasonbeach** [comment]
I guess that makes sense. Even private dependencies still have to be linked in to produce a final binary.
