### ISSUE TITLE
[question] set build_type to individual package doesn't work

### ISSUE THREAD

**Issue by chimojs** [conan-io/conan#14057]
### What is your question?

Hi! I am testing conan and trying to mix build type of different packages. I have one executable named **consumer** which links two unrelated libraries **add** and **hello**. The **add** is compiled in Release mode and **hello** in Debug mode. Now I want compile my **consumer** in Debug mode using `conan install .  -s add:build_type=Release -s hello:build_type=Debug -s build_type=Debug`, but Conan complains that **add** can not be found. Here are the output of conan install:

> ======== Input profiles ========
> Profile host:
> [settings]
> arch=x86_64
> build_type=Debug
> compiler=apple-clang
> compiler.cppstd=gnu17
> compiler.libcxx=libc++
> compiler.version=14
> os=Macos
> add:build_type=Release
> hello:build_type=Debug
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=apple-clang
> compiler.cppstd=gnu17
> compiler.libcxx=libc++
> compiler.version=14
> os=Macos
> 
> ======== Installing packages ========
> ERROR: Missing binary: add/1.0:454923cd42d0da27b9b1294ebc3e4ecc84020747
> 
> add/1.0: WARN: Can't find a 'add/1.0' package binary '454923cd42d0da27b9b1294ebc3e4ecc84020747' for the configuration:
> [settings]
> arch=x86_64
> build_type=Debug
> compiler=apple-clang
> compiler.cppstd=gnu17
> compiler.libcxx=libc++
> compiler.version=14
> os=Macos
> [options]
> fPIC=True
> shared=False
> 
> ERROR: Missing prebuilt package for 'add/1.0'
> Check the available packages using 'conan list add/1.0:* -r=remote'
> or try to build locally from sources using the '--build=add/1.0' argument
> 
> More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @chimojs 

Thanks for your question.

It seems that it is not that ``add`` cannot be found, is that you don't have a binary for the matching configuration.
You can list your existing binaries with ``conan list add/*:*``, and that will display the binaries with their settings.

Note that the package names in 2.0 are better represented by patterns, like ``-s add/*:build_type=xxx``. Please try that and let us know.

**Comment by chimojs** [comment]
I tried `conan list add/*:*` and  the **Release** version of `add `  does exist.

> Local Cache
>   add
>     add/1.0
>       revisions
>         6a10b9fac515063f75680d6210091f8a (2023-06-09 09:29:48 UTC)
>           packages
>             3a30e794f52cc541a8eef1d48bd278ebdcc60c18
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: apple-clang
>                   compiler.cppstd: gnu17
>                   compiler.libcxx: libc++
>                   compiler.version: 14
>                   os: Macos
>                 options
>                   fPIC: True
>                   shared: False

So I think problem is that conan doesn't use this binary and want Debug version of it. As for `-s add/*:build_type=xxx`, it works perfectly and compiled `consumer` links correct versions of them. And another interesting I found today
+ if I only link `add` with `conan install .  -s "add:build_type=Release"  -s "&:build_type=Debug"`, it works.
+ if I use `conan install .  -s "add:build_type=Release" -s "hello:build_type=Debug" -s "&:build_type=Debug"`, it now complains about `hello`

But anyway, using `-s add/*:build_type=xxx` solves this problem. Thanks!

**Comment by memsharded** [comment]
Just in case, note that the binary compatibility between Debug and Release artifacts is not always strictly guaranteed. Visual Studio gives you link errors, so not really possible to mix Debug and Release. ``gcc`` is good with mixing binaries. But ``clang`` I don't know, I would think that it behaves  like ``gcc``, but it is also possible that it is not happy about it for some situations?

In any case, if the ``add/*:build_type`` works, closing the issue, thanks!
