### ISSUE TITLE
[question] How to package application binaries with the dependencies libraries, such as shared libraries

### ISSUE THREAD

**Issue by Conzxy** [conan-io/conan#14067]
### What is your question?

Hi! I'm a new user of the `conan 2`.
I want to package the binaries from application project to a release package, and this don't make the user to install `conan` and use it to install the application package. The expected thing is package binaries and its dependencies libraries, such as shared libraries(*.dll, *.so), to the specified directory, eg. `bin` directory.
But the `conan` manages the installed package in local cache and these paths are too obscure, it's hard to package them.
Does conan provides a method to get paths of dependencies from `packgename/[version]`?
Or is there another method to achieve my requirement?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by Conzxy** [comment]
@RubenRBS 
I find the the [self.dependencies](https://docs.conan.io/2/reference/conanfile/methods/generate.html) and [conan.tools.files.copy()](https://docs.conan.io/2/reference/tools/files/basic.html?highlight=copy#conan.tools.files.copy_pattern.copy) can solve the problem.
If this is the best method, can close this issue.

**Comment by AbrilRBS** [comment]
Hi @Conzxy thanks a lot for your question!

If I understand your need correctly, I'd suggest for you to take a look into [deployers](https://docs.conan.io/2/reference/extensions/deployers.html), which are a mechanism to facilitate copying files from one folder, usually the Conan cache, to user folders.

> I find the the [self.dependencies](https://docs.conan.io/2/reference/conanfile/methods/generate.html) and [conan.tools.files.copy()](https://docs.conan.io/2/reference/tools/files/basic.html?highlight=copy#conan.tools.files.copy_pattern.copy) can solve the problem.

Those are the methods that will be useful in the generators, yes! You might need to create a custom one for your specific task, but feel free to take a look into the built-in ones code, and more importantly for your need, into the "[Creating a Conan-agnostic deploy of dependencies for developer use](https://docs.conan.io/2/examples/extensions/deployers/dev/development_deploy.html)" example

Let me know if this helps, else feel free to let us know so we can help you further :)

**Comment by Conzxy** [comment]
Hi! @RubenRBS 
I have read the docs of deploy, ie. `full_deploy`, it will copy the all files of dependencies to the `full_deploy` folder and the relative paths are not changed, eg. `full_deploy/protobuf/include` and `full_deploy/protobuf/lib`, but I only need copy the libraries to a specified folder.
In fact, I think copying the `package_folder/lib/*.so`  from dependencies to the same folder is what I need.

**Comment by AbrilRBS** [comment]
Great to hear! 
Just as a further tip, I'd recommend using the `cpp_info.libdirs` information for each node of the graph, ([docs here](https://docs.conan.io/2/reference/conanfile/methods/package_info.html#cpp-info-library-and-build-information)) which will point to the proper library path(s) each dependency will have set as the path it places its libs (If any!)

So that your custom deployer might look something like this (Can't actually test it right now, but the syntax should be 99% of the way there):
```py
from conan.tools.file import copy

def deploy(graph, output_folder, **kwargs):
    for node in graph.nodes:
        libdirs = node.conanfile.cpp_info.libdirs
        if libdirs:
            for libdir in libdirs: 
                copy(node.conanfile, "*.so", src=libdir, dst="your/final/path")
```

**Comment by Conzxy** [comment]
oh, @RubenRBS , thanks for the further tip, it is helpful for me to implement custom deploy.
I have read the docs about the custom deploy, but there are some points I can't understand.
To your provided code, if the graph has a indirect dependency and it is specified as `-o shared=False`, the `libdirs` of it will be `['lib']` instead of some paths in local cache. In other cases, ie. direct dependency or indirect dependency with `shared=True`, the `libdirs` must points to the local cache.

For example, the `protobuf` has the `zlib` dependency.
If I specify the `zlib` to a direct dependency in `conanfile.txt` or `conanfile.py`, the `libdirs` is expected, regardless of the value of `shared` option.
But if the `zlib` becomes a indirect dependency from `protobuf`, the `libdirs` will be `['lib']` when `shared=False`.

Although I think this is right for c++, since the symbols have resolved in the dependency libraries. Does `conan` take this into account?

**Comment by memsharded** [comment]
> To your provided code, if the graph has a indirect dependency and it is specified as -o shared=False, the libdirs of it will be ['lib'] instead of some paths in local cache. In other cases, ie. direct dependency or indirect dependency with shared=True, the libdirs must points to the local cache.


There are some scenarios in which a dependency binary is "Skipped", for example if a shared library links with a static library, that transitive dependency is skipped, as the binary is not necessary as it has already been linked into the shared library. Depending on how you iterate:
```
for node in graph.nodes:
```
iterates all nodes in the graph, including transitive dependencies whose binaries might have been skipped
or 
```
for require, dep in graph.root.conanfile.dependencies.host:
```
Iterate only the "host" dependencies of the "root" of the graph dependencies and transitive dependencies (which might not include the "skipped" binaries)


You should see the "Skips" in the terminal output when you run conan.
