### ISSUE TITLE
[bug] Detected compiler missing in profile

### ISSUE THREAD

**Issue by jputcu** [conan-io/conan#14064]
### Environment details

Conan-2.0.6.

`conan detect profile` on FreeBSD when both `gcc` and `clang` are installed provides the default `gcc` profile. But when building cmake builds with `clang`.

Maybe we need to add the following the the profile?
~~~~
[conf]
tools.build:compiler_executables={'c': '<detected c compiler>', 'cpp': '<detected c++ compiler>'}
~~~~

~~~~~
$ conan new cmake_exe -d name=game -d version=1.
$ conan build .

Profile host:
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=FreeBSD

Profile build:
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=FreeBSD

....
======== Calling build() ========
conanfile.py (game/1.0): Calling build()
conanfile.py (game/1.0): Running CMake.configure()
conanfile.py (game/1.0): RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/jorisp/game/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/jorisp/game" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/jorisp/game/."
-- Using Conan toolchain: /home/jorisp/game/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 17 with extensions ON
-- The CXX compiler identification is Clang 14.0.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
....
~~~~~

Adding

~~~~~
$ cat ~/.conan2/profiles/default 
[conf]
tools.build:compiler_executables={'c': 'gcc', 'cpp': 'g++'}
....
$ conan build .
...
-- The CXX compiler identification is GNU 12.2.0
...
~~~~~

**Comment by memsharded** [comment]
Not sure how this connects to https://github.com/conan-io/conan/issues/14062. It seems the issue was the incorrect detection of gcc in the profile? Is this solved now with your PR?

**Comment by jputcu** [comment]
This issue was exposed due to #14062. Even though *gcc* was detected, it wasn't propagated to *cmake*, so I think it would be better to have the detected compiler added to the profile so everybody uses the correct one.

**Comment by memsharded** [comment]
Hi @jputcu 

Thanks for clarifying, now I understand.

Conan automatic detection of profile should already detect the "default" compiler, so no extra ``conf`` would be necessary. Now that for FreeBSD ``clang`` detection is fixed, it shouldn't be necessary to add anything extra to the detected profile, because everyone would be already aligned, and ``tools.build:compiler_executables`` would be redundant.

I think we could close this issue now?

**Comment by jputcu** [comment]
Strange that the autodetect for cmake gave a different compiler, it is a different implementation?
Adding the compiler to the profile seems redundant, but it is however nice for transparency, consistency with other profiles.
You can close the ticket if you want.

**Comment by memsharded** [comment]
> Strange that the autodetect for cmake gave a different compiler, it is a different implementation?

I guess yes, that CMake has hardcoded the preference for clang. We don't use any CMake at all to detect the default profile, as you saw in your own PR, so it is expected that it might deviate in some scenarios not taken into account (and not all build systems are CMake, there are plenty of Conan users doing autotools, meson, msbuild and others).

> Adding the compiler to the profile seems redundant, but it is however nice for transparency, consistency with other profiles.

Yes, in this case we prefer to have simpler default profiles, than adding a redundant thing that is not really necessary.

> You can close the ticket if you want.

Thanks for the feedback!
