### ISSUE TITLE
[bug] Profile detect selects wrong default compiler on FreeBSD

### ISSUE THREAD

**Issue by jputcu** [conan-io/conan#14062]
### Environment details

`conan profile detect` when both `gcc` and `clang` installed, `gcc` is selected, while `FreeBSD` actually uses `clang` as core/standard compiler.

**Comment by memsharded** [comment]
Hi @jputcu 

Yes, would make sense to change it. This one should be relatively easy, would you like to try to contribute a PR yourself?

**Comment by jputcu** [comment]
Sure, will need some time to get going with the code though.

**Comment by memsharded** [comment]
Sure, no problem, as a hint, this is probably where it should go: https://github.com/conan-io/conan/blob/81f7f2d8ef87d24eef5c0dab509ffa035f5be9e3/conans/client/conf/detect.py#L113

No need to add tests, as we don't have FreeBSD on CI, as long as you test it locally, it would be fine.
