### ISSUE TITLE
[question] how to write tests for a cmake_exe package using gtest?

### ISSUE THREAD

**Issue by baqeri** [conan-io/conan#14072]
### What is your question?

I can write tests for a cmake_lib package using Conan but how to write tests for a cmake_exe package using gtest?
Actually, how can I reference package header files in gtest TEST file? It gives fatal error on include.

**Comment by AbrilRBS** [comment]
Hi @baqeri thanks a lot for your question.

Could you share some extra info about your current conanfile/setup? This would make it so much easier for us to help you :)

**Comment by baqeri** [comment]
conanfile.py
```
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, CMakeDeps, cmake_layout


class Recipe(ConanFile):
    name = "app"
    version = "1.0"
    user = "me"
    channel = "testing"
    package_type = "application"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/*"

    def requirements(self):
        self.requires("cppkafka/0.4.0")
        self.requires("glog/0.6.0")
        self.requires("sole/1.0.4")
        self.requires("argparse/2.9")
        self.requires("fmt/10.0.0")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15)
project(app CXX)

set(CMAKE_VERBOSE_MAKEFILE ON)

find_package(CppKafka REQUIRED)
find_package(glog REQUIRED)
find_package(sole REQUIRED)
find_package(argparse REQUIRED)
find_package(fmt REQUIRED)

add_executable(${PROJECT_NAME} src/main.cpp
        src/MarketDataPayload.cpp
        src/MarketDataPayload.h
        src/MarketDataRoute.cpp
        src/MarketDataRoute.h
        src/MessageConsumer.cpp
        src/MessageConsumer.h
        src/MarketDataPublisher.cpp
        src/MarketDataPublisher.h
        src/EventSource.cpp
        src/EventSource.h
        )

target_link_libraries(${PROJECT_NAME}
        ${CppKafka_LIBRARIES}
        ${glog_LIBRARIES}
        ${sole_LIBRARIES}
        ${argparse_LIBRARIES}
        ${fmt_LIBRARIES}
        )

install(TARGETS ${PROJECT_NAME} DESTINATION "."
        RUNTIME DESTINATION bin
        ARCHIVE DESTINATION lib
        LIBRARY DESTINATION lib
        )
```

How can I get `gtest` to run my unit tests?

**Comment by memsharded** [comment]
Some side feedback:

- Do not link with the "LIBRARIES" only. It will be missing information. So instead of ``target_link_libraries(${PROJECT_NAME} ${CppKafka_LIBRARIES}``, better use something like ````target_link_libraries(${PROJECT_NAME} CppKafka::CppKafka)`` (I don't know the name of the target by heart, but it should be printed when ``find_package()`` finds it.

**Comment by baqeri** [comment]
Or is there any way to import `.a` file along with `.exe` in the package?

**Comment by memsharded** [comment]
> Or is there any way to import .a file along with .exe in the package?

Sorry, I don't know what you mean

**Comment by baqeri** [comment]
I have a project by `package_type = "application"` and want to write unit tests. The issue is that the examples currently found by googling, show how to write tests for library projects not applications. So I want to have the executable artifact of my project along with a library including object files of the project, in the package, for test usage (linking that library with unit tests). The question is "Is it possible"?

**Comment by memsharded** [comment]
Yes, it is totally possible. This is not necessarily something Conan specific, it is about how you write your CMakeLists.txt and your C++ code. It is not possible to test just a single ``main()`` function, but as your code will have other functions, classes, etc, you can perfectly test them with unit tests, as long as you write your tests c++ code and you add the tests to your ``CMakeLists.txt``.

If you add them to CMakeLists.txt, then Conan in the ``build()`` method if it does ``cmake.test()`` it will run the tests.

**Comment by baqeri** [comment]
How can I add them in `CMakeList.txt` for testing? is there any sample?

**Comment by memsharded** [comment]
There should be plenty of examples about this in the CMake docs and the internet (this is outside of Conan scope, and specific to CMake). See some quick links examples:
- https://cmake.org/cmake/help/book/mastering-cmake/chapter/Testing%20With%20CMake%20and%20CTest.html
- https://coderefinery.github.io/cmake-workshop/testing/

**Comment by baqeri** [comment]
Thanks @memsharded! Finally, my problem was solved by adding some lines in CMakeLists.txt.

**Comment by memsharded** [comment]
Excellent, thanks for telling!
