### ISSUE TITLE
[feature] AutotoolsToolchain support [conf] tools.android:ndk_path

### ISSUE THREAD

**Issue by zhizhi-dev** [conan-io/conan#14077]
### What is your suggestion?

AutotoolsToolchain support [conf] tools.android:ndk_path

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @zhizhi-dev 

Thanks for your suggestion.
In order for AutotoolsToolchain to be able to implement Android NDK support we would need help, to know what to do (sorry, I have no expertise in cross-build for Android with autotools):

- What flags need to be defined?
- How does the ``tools.android:ndk_path`` maps to the build?
- How are the Conan settings mapped to the autotools env-vars?

**Comment by zhizhi-dev** [comment]
> Hi @memsharded 
from now, i suggest:
* map cc, cxx toolchain to autotools, like gcc, clang , g++, clang++
* map sysroot 
* map some build flags , like  api level, cpu arch, etc,

**Comment by memsharded** [comment]
AutotoolsToolchain implemented some time ago definition of Android flags deduced from ``ndk_path``.
Closing as solved, but please don't hesitate to re-open or create new tickets if necessary for any further question. Thanks for the feedback.
