### ISSUE TITLE
[feature] Non-persistent editable API

### ISSUE THREAD

**Issue by fredizzimo** [conan-io/conan#14073]
### What is your suggestion?

I'm currently rewriting our "workspace" implementation in Conan 2. Previously for Conan 1.0 we used quite many hacks taking advantage of the internals of Conan to do it. But now with the new Conan 2 API, we can make the implementation much cleaner using only the public API.

But there is a problem, the `editable_add` is persistent, I would prefer it it operated completely in-memory, and that we re-build the list each time we call our script. I think I could do it as before by manipulating Conan's internal datastructures, but I'd rather not do it.

Furthermore it's not easy to clear the list of editables through the API. You need to call `editable_list` and then `editable_remove` for each element. But doing that at the startup is my current workaround. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fredizzimo 

Thanks for your suggestion

> Furthermore it's not easy to clear the list of editables through the API. You need to call editable_list and then editable_remove for each element. But doing that at the startup is my current workaround.

Probably not necessary. Now that the editable API can use paths, a workspace implementation can just iterate the paths of the workspace, which is the best and simplest interface in any case.
I guess something like:

```python
workspace folders = ["folder1", "folder2", ...]  # or read them from your own conf file
for folder in workspace_folders:
     ref = conan_api.local.editable_add(folder)

# Do your workspace here

for folder in workspace_folders:
     conan_api.local.editable_remove(folder)
```

The problem with non-persistent state is that the ConanAPI is basically stateless, it doesn't have any state in-memory, and the necessary things are obtained at every call of the api from the Conan cache. Doing this change would probably be a large change, and somewhat fragile, as it would be kind of an outlier in the design of the api, and the above solution seems enough at this moment.

**Comment by fredizzimo** [comment]
@memsharded.

Thank you for the answer. Clearing the editables is necessary for a couple of different reasons.

1. We support compiling both in "workspace mode" with all packages as editables. But also as a regular install with the packages exported to the cache, mostly for verifying that the actual packages work as well. So we need to ensure that there are no editable packages enabled when doing that.
2. We want to ensure that there's no left-overs, a package might have been deleted or renamed for example.

Also note that we want to share as much as possible of the cache between the two, so using two different caches is not an option.

That said, I think my workaround of deleting everything at the start is enough. It could be easier with an `editable_clear` command, but doable without so the issue can probably be closed.

**Comment by memsharded** [comment]
> Thank you for the answer. Clearing the editables is necessary for a couple of different reasons.

Thanks for explaining your use cases. When you have something working, it would be amazing if you could share with us it, or at least part of it, so we use it as input when re-introducing a built-in workspace concept. If not possible to share it in public, maybe in private, or maybe a summary of implementation ideas.

> That said, I think my workaround of deleting everything at the start is enough. It could be easier with an editable_clear command, but doable without so the issue can probably be closed.

Perfect, yes, lets close it, I think at this moment, the effort would be much higher than the benefit, so I'd prefer to wait a bit until we start reconsidering the introduction and we have some more feedback from other users as well.

Thanks for the feedback!
