### ISSUE TITLE
tools.environment_append looses LIB variable

### ISSUE THREAD

**Issue by osechet** [conan-io/conan#1408]
Using `VisualStudioBuildEnvironment`, after calling `tools.environment_append(env_build.vars)`, the `LIB` variable disappears from the environment. In my case, `LIB ` in `env_build.vars` is an empty string and since `environment_append()` only concatenate lists to existing environment, the final `os.environ.update()` removes the variable from the environment.
Either `VisualStudioBuildEnvironment` should return an empty array, either a `else` case should be added in `environment_append()` to deal with strings.

**Comment by memsharded** [comment]
This might be a similar problem to: https://github.com/conan-io/conan/pull/1371

**Comment by lasote** [comment]
We can check the current environment before generating the CL/LIB variable dict to automatically append previously set values in your environment.
We need to remember to check the virtualenv generator because probably we have the same problem that @memsharded reported: #1371

**Comment by lasote** [comment]
Actually, I reported here #1389 too about this.
