### ISSUE TITLE
[question] Is it possible to reference a specific packege id in conanfile?

### ISSUE THREAD

**Issue by chimojs** [conan-io/conan#14089]
### What is your question?

Hello! We have many shared libraries being compiled in `mingw` and using in a `msvc` project, what we currently do is tuning profile and set individual settings to specific packages like this:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.version=192
> os=Windows
> hello/*:compiler=gcc
> hello/*:compiler.version=13
> hello/*:compiler.libcxx=libstdc++11
> hello/*:compiler.threads=posix
> hello/*:compiler.cppstd=17
> hello/*:os.subsystem=msys2

But it seems messy and time consuming to set all these boilerplate settings. So I am thinking if there is anyway we can specify package id directly like this `hello/1.0#e69bb922fffcba1b661bd17459ef68db:f6e8a0cf5f557ee89967a3e45d85aea3e82fc25aa`? Or there are some better ways to deal with this situation? Any help would be appreciated!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @chimojs 

What you are doing is a good approach. From our understanding, it is not messy or boilerplate (unnecessary), but it is an explicit and exact definitions of what you want, that will allow full control, flexibility and be future proof.

Trying to require this thing directly in ``conanfile.py`` requires would be a bad idea, as it ties/hardcodes configuration into code. It is the equivalent of hardcoding configuration like URLs, port numbers, files, variables into the C++ code of an application.

If the thing is that there are many dependencies with that and the profiles get large, there are different alternatives:

- Use the ``&:setting=value`` syntax to affect only the consumer project, but not the rest
- Use jinja templating to define a ``for`` loop over the packages that requires a different compiler.

Alternatively, in Conan 2.0, you could define a custom ``compatibility.py`` that is able to fallback to use a different configuration than the provided one.

**Comment by chimojs** [comment]
I think `profile` is better than `compatibility.py` when running on different platforms.  Hardcodes is not always a bad idea if the user knows exactly what he is doing and is confident that everythings will go well.  I am willing to see that an option would be provided in future conan version,  and we user can have control of  package id setting.  I do believe that setting package id is a good way to go in our case. 

Anyway, I am much confident that tuning profile is the right approach. And thank you guys for this amzing project!!!

**Comment by memsharded** [comment]
> I think profile is better than compatibility.py when running on different platforms. 

Yes, I agree, I like profile being explicit. ``compatibility.py`` can be great for other cases when this is not possible (like quickly evolving compiler upgrades).

> Hardcodes is not always a bad idea if the user knows exactly what he is doing and is confident that everythings will go well.

In our experience, even with this confidence, things tend to change, evolved in unexpected ways, and this assumption goes bad quickly in a majority of cases. 

> I am willing to see that an option would be provided in future conan version, and we user can have control of package id setting. I do believe that setting package id is a good way to go in our case.

I think this is extremely unlikely to happen. We have supported many thousands of users along the years, helped them to debug issues and problems, and we know for sure that this feature will cause trouble to many users, and will also impact us (extra maintenance, support, etc). This is why we keep a strict separation of the configuration (profiles) and the functionality (recipes), and we plan to keep respecting this boundary.

> Anyway, I am much confident that tuning profile is the right approach. And thank you guys for this amzing project!!!

Fantastic, thanks very much for your kind words and your feedback! 🙂 
(Closing the issue as responded, but don't hesitate to create new tickets for any further question or issue)
