### ISSUE TITLE
[question] Why does this cycle happen when there is no real dependency cycle?

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#14085]
### What is your question?

I have a scenario with three packages: `foundation`, `llvm`, and `pkg`.

The `foundation` package is empty - it contains only the `conanfile.py` and serves only as a "profile helper", i.e. its purpose is to define compile and link flags based on the combination of architecture, build type, operating system, and compiler. For example, it will enable LTO or sanitizers based on compiler settings.

For purposes of demonstrating the issue in question, we can have an empty `foundation` recipe, like this one:

```python
from conan import ConanFile

class Foundation(ConanFile):
    name = 'foundation'
    version = '0.1.0'
    settings = 'os', 'arch', 'build_type', 'compiler'

    def package_id(self):
        self.info.clear()

    def package_info(self):
        # setup build and link flags depending on custom settings and os/arch/build_type/compiler combination
        pass
```

The recipe is accompanied by a profile that ensures the foundation package is always tool-required:

```
# foundation
[tool_requires]
foundation/0.1.0
```

The idea is that every profile in my system directly or transitively includes a `foundation` profile to ensure that correct build flags are always propagated to all packages, regardless of their build system.

Next, we have a concrete toolchain package that contains the real compilers. For this example, let's say it's an LLVM toolchain:

```python
from conan import ConanFile

class LLVMConan(ConanFile):
    name = "llvm"
    version = "16.0.5"
    settings = "os", "arch", "build_type", "compiler"

    def package_id(self):
        del self.info.settings.compiler
        del self.info.settings.build_type

    def package_info(self):
        pass
        # setup compilers and default flags
```

For using the LLVM toolchain, I defined a `llvm` profile that looks like this:

```
# llvm
include(foundation)

# setup arch, os, etc.

[tool_requires]
llvm/16.0.5
```

Finally, I want to use this `llvm` profile as both a build and host profile for my package `pkg`, however this results with an error:

```
$ conan install . -pr llvm -pr:b llvm

======== Input profiles ========
Profile host:
[settings]
[tool_requires]
*: foundation/0.1.0, llvm/16.0.5
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.cmake.cmake_layout:build_folder_vars=['settings.os', 'settings.os.sdk', 'settings.arch', 'settings.compiler', 'settings.compiler.version', 'settings.compiler.sanitizers', 'settings.compiler.link_time_optimization']
tools.files.download:retry=5
tools.files.download:retry_wait=2

Profile build:
[settings]
[tool_requires]
*: foundation/0.1.0, llvm/16.0.5
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.cmake.cmake_layout:build_folder_vars=['settings.os', 'settings.os.sdk', 'settings.arch', 'settings.compiler', 'settings.compiler.version', 'settings.compiler.sanitizers', 'settings.compiler.link_time_optimization']
tools.files.download:retry=5
tools.files.download:retry_wait=2


======== Computing dependency graph ========
Graph root
    conanfile.py (pkg/0.1.0): /Users/dodo/Desktop/test-conan-profiles/pkg/conanfile.py
Build requirements
    foundation/0.1.0#5300a7ac055d6857c6b29f29a9e6d2af - Cache
    llvm/16.0.5#0e31491b7747967c5546225ff878b2f1 - Cache
ERROR: There is a cycle/loop in the graph:
    Initial ancestor: foundation/0.1.0
    Require: foundation/0.1.0
    Dependency: foundation/0.1.0
```

Why does this cycle happen? Is this a feature or a bug?

I've tried to visualize the dependency graph with `conan graph info . -pr llvm -pr:b llvm --format=html > graph.html` and this resulted with this picture:

![image](https://github.com/conan-io/conan/assets/158844/2927b8c8-c648-433f-b913-dec822697137)

Apparently `foundation/0.1.0` has a dependency on `llvm/16.0.5` that again has a dependency on `foundation/0.1.0`.

But why does the `foundation/0.1.0` have a dependency on `llvm/16.0.5`? I never defined that dependency. I kinda understand the dependency of `llvm/16.0.5` on `foundation/0.1.0` due to the profile, although I'd expect that both `foundation/0.1.0` and `llvm/16.0.5` are added as dependencies of `pkg/0.1.0` without any inter-dependencies.

Is this a bug or a feature?

If it's a feature, can someone explain why this happens and how to avoid these dependency cycles?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Your effective profile contains:

```
[tool_requires]
*: foundation/0.1.0, llvm/16.0.5
```
Which means applies both tool requires to all packages.
This happens because you did ``llvm`` profile an ``include(foundation)``. The inclusion is a composition, so both ``[tool_requires]`` from both profiles are aggregated.

As you are applying this profile to both "build" and "host" context, it enters a cycle in the "build" context. With ``foundation`` and ``llvm`` package requiring each other.

You want to break this cycle, there could be different approaches, like making sure the "build" profile is different, not doing the ``tool_requires`` to ``llvm``. Please try that.

**Comment by DoDoENT** [comment]
>You want to break this cycle, there could be different approaches, like making sure the "build" profile is different, not doing the tool_requires to llvm. Please try that.

But that is the point - I _want_ `llvm` to be used as a build tool for both build and host context (I'm not cross-compiling). It's as if using system-wide LLVM, except that this one is packaged into a conan package.

> This happens because you did llvm profile an include(foundation). The inclusion is a composition, so both [tool_requires] from both profiles are aggregated.

But I want that composition. I want all packages built with this profile to both `tool-require` `llvm` and `foundation`. I just don't understand why `foundation` tool-requires `llvm` and vice-versa.

My current workaround is to basically copy the rules from `foundation` package into `llvm` (all the build flags, etc.), which means that I need to maintain an effective two copies of `foundation` package, which is not ideal.

**Comment by memsharded** [comment]
> But that is the point - I want llvm to be used as a build tool for both build and host context (I'm not cross-compiling). It's as if using system-wide LLVM, except that this one is packaged into a conan package.

yes, except ``llvm`` is a package itself, and it needs to be built, same with ``foundation``.
So it is necessary to define the logic that breaks the cycle. It is possible to define patterns and negate patterns in ``[tool_requires]``:
```ini
[tool_requires]
tool1/1.0
!tool1*:tool2/1.0
```

> But I want that composition. I want all packages built with this profile to both tool-require llvm and foundation. I just don't understand why foundation tool-requires llvm and vice-versa.

Because you are telling in your "build" profile:
```ini
[tool_requires]
*: foundation/0.1.0, llvm/16.0.5
```
That means for every package that is in the "build" context, automatically inject those 2 tool_requires. As requiring itself is not possible in this way, it results on ``llvm`` requiring ``foundation`` and ``foundation`` requiring ``llvm``. It is exactly what was defined in the profile.

**Comment by DoDoENT** [comment]
So, if I understood correctly, setting this in "build" profile:

```
[tool_requires]
llvm/16.0.5
```

will automatically add dependency `llvm/16.0.5 -> llvm/16.0.5`?

And in the case when I have multiple `tool_requires`, every package in `tool_require` will automatically `tool_require` every other?

Is this by design?

**Comment by memsharded** [comment]
> will automatically add dependency llvm/16.0.5 -> llvm/16.0.5?

No, the self-reference is discarded, it knows that it is itself, and doesn't apply it automatically.

> And in the case when I have multiple tool_requires, every package in tool_require will automatically tool_require every other?

If you have them in the "build" profile, yes, this is exactly the design.
The thing is that ``[tool_requires]`` is intended mostly for "host" context, like injecting a specific version of cmake or a gcc compiler to all your libraries and executables. 

For the "build" context the situation is much different and it is unlikely that such general ``[tool_requires]`` patterns apply. So tool-requires in the build context have to be way more specific, with specific patterns in the profile ``llvm/*: toolchain_to_build_llvm/1.0``, or even defining the ``self.tool_requires()`` directly in the ``conanfile.py`` recipe.

**Comment by DoDoENT** [comment]
OK, thank you for the explanation.

If that's by the design, I'll close the question now and find a different approach to my problem so that I have at most one `tool-requires` in my profiles in order to avoid surprises like this one.

**Comment by memsharded** [comment]
> If that's by the design, I'll close the question now and find a different approach to my problem so that I have at most one tool-requires in my profiles in order to avoid surprises like this one.

It is perfectly ok, and probably recommended to have multiple ``tool_requires`` for the "host" context. Trying to have only 1 ``tool_require`` for the host context will probably be an anti-pattern and result in other problems and issues.

It is just the "build" profile that needs to define the ``tool_requires`` a bit more carefully to avoid infinite recursion, but it doesn't mean that only 1 ``tool_require`` can be used.

The solution is not trying to use the exact same profile for "build" and "host". They are not the same, even if not cross-building. For example, when doing a "Debug" build of your product, you don't want ``cmake/3.25`` conan package and maybe ``gcc_toolchain/1.2.3`` conan package to be in ``build_type=Debug``, because they will be terribly slow. So the "build" context uses ``build_type=Release`` and the host context uses ``build_type=Debug``. The same reasoning applies for ``tool_requires``, it is expected that the ``tool_requires`` are not the same for the "host" context and the "build" context.

**Comment by DoDoENT** [comment]
I understand. I generally use `tool_requires` for host contexts, notably `emsdk` and `android-ndk`. However, on Windows, I package `llvm` also to the Conan package, and it should be used in the `build` context (I always define build types separately, never in the profile).

The thing is that I also want to have this `foundation` package for all platforms that will enforce some compile flags for all packages (LTO, sanitizers, etc.). I don't expect this `foundation` package to change frequently, if ever.

So, I basically merged the code of that `foundation` package (basically two functions that should be invoked from `package_info`) into the `llvm`, `emsdk`, and `android-ndk` packages, so that profiles for windows-llvm, android, and emscripten then don't include the `foundation` profile that adds `tools_requires` on foundation package. This foundation package is then only used for Linux, Mac, and iOS, where I rely on system-installed toolchains.

There are probably different solutions for the same problem, but this one appears to work for me for now (I'll see if it'll make problems in the future - I just started porting everything to conan2).

I was just curious and confused about the cycle I got in the original question and your answer explained it to me in a satisfying way. Thank you!

**Comment by memsharded** [comment]
Ok, that makes more sense, thanks very much for the clarifications. I was concerned of trying to collapse more than 2 big tool_requires into a single one. Adding the foundation lines to the other packages make sense. You might even refactor it into a ``python_requires`` that is used by the others, to avoid the repetition.

Understanding the pattern better with this feedback, maybe it would have been possible to with ``!foundation: llvm/xxx`` pattern in ``[tool_requires]`` section of "build" profile, as it becomes more clear that the ``foundation`` package containing only flags will not need llvm as a tool-requires.

Thanks very much to you for the feedback!

**Comment by DoDoENT** [comment]
> You might even refactor it into a python_requires that is used by the others, to avoid the repetition.

I might even do that in the future, in case `foundation` package becomes larger. Currently, with a couple of functions that need to be invoked from `package_info` (one that sets up LTO, and the other that sets up sanitizers) it's more visible when copied to all toolchain packages.

All in all, thank you for the idea.
