### ISSUE TITLE
[question] How to retrieve third parties components' names?

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14092]
### What is your question?

Hello,

I am currently following this [page](https://docs.conan.io/2/reference/conanfile/methods/package_info.html) and particularly the line ```self.cpp_info.components["ssl"].requires = ["crypto", "boost::headers"]``` to propagate my requirements downstream.
Looking into the generated ```.cmake``` files after running a ```conan install``` (boost is set a requirement) does not reveal any ```boost::headers``` but ```Boost::headers```. As a matter of fact, the only ones listed with a lowercase b are ```boost::numpy39``` and ```boost::python39```.
Adding any of the components with a capital B raises an error when my lib is installed to be used as dependency.
My question is: ***Where can I find a proper list of these components to be added into the requires field?***

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your question

> Looking into the generated .cmake files after running a conan install (boost is set a requirement) does not reveal any boost::headers but Boost::headers. As a matter of fact, the only ones listed with a lowercase b are boost::numpy39 and boost::python39.

The ``components`` names are not the same as the potential CMake components, they are an abstraction that can be leveraged by other build systems. 
So the important definition is whatever the used recipe defines as their components. If you want to quickly inspect the components definitions, you can add the ``--format=json`` argument to your command, like:
```
conan install --requires=boost/1.82.0 --format=json
```
And then inspect the output (you can ``> graph.json`` redirect the output to a file too), to see:
```json
"regex": {               
},                       
"serialization": {  
},
"stacktrace": {
}
```     
Which are the components names (the root name is the package name, which is always lowercase, same as you have it in your ``requires = "boost/1.82.0"``

**Comment by Todiq** [comment]
I see! It works now, using that info. Thank you very much :)
