### ISSUE TITLE
[question] Telling apart conan1.X and conan2.0 packages in Artifactory

### ISSUE THREAD

**Issue by eyal-ronel** [conan-io/conan#14094]
### What is your question?

Hi,
In my team we use a local Artifactory to store binary versions and data packages, and we've been using Conan 1.X for a while now.
I'm in the process of migrating to Conan 2.0 and have uploaded a few packages with 2.0 recipes.
Now I wonder how can I tell which packages are 2.0 and which are older?

I was advised to use conan search -r with an 1.x client and with a 2.0 client, 
and that each client will only list the packages that suit them. 
But when I run: 
`conan search -r my_repo` with conan 1.54 and
`conan search -r my_repo *` on conan 2.0.6,
unfortunately both clients display all packages in the repo (though 2.0.6 displays them nicer).
Am I missing a flag or attribute or something?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @eyal-ronel 

The ``conan search`` with a pattern, only displays "recipes" but not packages. To display the packages, you need to go on level down:

```
# Conan 1.X
$ conan search zlib/1.2.13@  # will give you the binaries for 1.X
# Conan 2.0
$ conan list zlib/1.2.13:* # will give you the binaries for 2.0
```

It is true that Conan 2.0 can go over all binaries for all recipes with ``conan list *:*``, but Conan 1.X need to go one recipe at a time, so iterating over all recipes is necessary in Conan 1.X.

Please let me know if this clarifies it.

**Comment by eyal-ronel** [comment]
Yes, thanks for clarifying the difference between a recipe and a package in that context.
