### ISSUE TITLE
[question] Make a requrement non-direct only (Conan 2)?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#14105]
### What is your question?

I'm trying to create (another language) compiler that needs cygwin to build and msys to use. So I wrote
```python
    def requirements(self):
        if self.settings.os == "Windows":
            self.requires("msys2/cci.latest", build=True, direct=False)

    def build_requirements(self):
        if self.settings.os == "Windows":
            self.tool_requires("cygwin_installer/2.9.0@internal")
```
That doesn't work: both cygwin and msys are added to PATH of the build context when creating the package (I'm creating it with `--build-require` flag). That's unfortunate because msys and cygwin conflicts. I tried to get gid of of `conanbuildenv-*.bat` and generate the necessary environment manually but surprisingly it doesn't work in Conan 2.0: it's still generated even when `generators` attribute doesn't contain `VirtualBuildEnv`. Any idea how to work around this?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question.
So what you want to achieve is basically deactivating the generation of environment scripts?

That can be done with:
```python
def generate(self):
     VirtualBuildEnv(self) 
     VirtualRunEnv(self) 
     # do not call generate() over it
```
I think setting the ``virtualbuildenv=False`` attribute should also work, but I think that is not documented at the moment.

Please let me know if this works for you.

**Comment by db4** [comment]
Hi @memsharded
Yes,  calling `VirtualBuildEnv(self)` without `generate()` is enough, thanks a lot for the hint.
