### ISSUE TITLE
"conan lock create" does not append to lock file

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#14117]
### Environment details

OS: WSL Ubuntu 20.04
Conan: 2.0.0

### Steps to reproduce

Running:
`conan lock create --profile:build: xxx --rpfile:host yyy conanfile.py --lockfile-out new.lock`

According to https://docs.conan.io/2/reference/commands/lock/create.html:

![image](https://github.com/conan-io/conan/assets/48069914/776af71d-f75f-4be8-b954-7b1c04d5062b)

I would expect my lock file to be extended every time I run lock create with different configs with that file as output.

What have I misunderstood?
How do I get it to extend the file?

Rgds
Klaus

**Comment by klausholstjacobsen** [comment]
I discovered that only when using `--lockfile my.lock` together with `--lockfile-out my.lock` it will append to the lockfile!
May I suggest to add this to the documentation!

**Comment by memsharded** [comment]
Yes, worth clarifying. The lockfile is only loaded automatically by default if it is called ``conan.lock``, but for custom names, it is necessary to feed it with ``--lockfile=my.lock``
