### ISSUE TITLE
[question] python_requires and methods: how to call methods from parent python_require package

### ISSUE THREAD

**Issue by ATS-AValli** [conan-io/conan#14118]
### What is your question?

Hi.

First of all, I should preface this by saying I'm not a python expert and probably the answer is known by someone who's a pro at python.

So, I'm following the documentation/tutorial for python requires found [here](https://docs.conan.io/2/reference/extensions/python_requires.html#reference-extensions-python-requires) .

Specifically, I'm interested in customizing the usual methods (such as `build`, `requirements`, `package`). Using the example that adds the several `self.output.info("My cool <method>!")` I see that only those methods NOT defined in the main conanfile (the one that inherits via python_requires) are called.

How can I call the methods from the python_requires package while at the same time have some code specific to each child conanfile ? Is it possible ?

Or should I rather change the name of methods in the child conanfile and call such renamed method from the base ?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ATS-AValli 

Thanks for your question, don't worry if not a python expert, we are here to try to help. In python calling the base class is done with ``super()`` like this:

```python
def source(self):
     super().source()
     self.output.info("MY OWN SOURCE")
```

I am adding a test in #14120 and adding a short example in the docs

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/14120 closed it automatically, but please let us know how it goes

**Comment by ATS-AValli** [comment]
> 

Works perfectly, thanks once again! :-)
