### ISSUE TITLE
[bug] Latest GitHub Actions windows-2022 image doesn't find compiler with compiler.update setting

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#14111]
### Environment details

I think this is an issue with the latest version of GitHub Actions `windows-2022` image and not Conan itself. I logged an issue in GitHub Actions:
https://github.com/actions/runner-images/issues/7741

Cross-posting here for general awareness, though there might be an opportunity for a Conan change to help make this more robust? The compiler is there and Conan uses it when `compiler.update` is not set.

**Comment by memsharded** [comment]
For reference, the code that defines the ``CMAKE_GENERATOR_TOOLSET`` is:

```python
        elif compiler == "msvc":
            toolset = settings.get_safe("compiler.toolset")
            if toolset is None:
                compiler_version = str(settings.compiler.version)
                compiler_update = str(settings.compiler.update)
                if compiler_update != "None":  # It is full one(19.28), not generic 19.2X
                    # The equivalent of compiler 19.26 is toolset 14.26
                    toolset = "version=14.{}{}".format(compiler_version[-1], compiler_update)
                else:
                    toolset = msvc_version_to_toolset_version(compiler_version)
```
with ``msvc_version_to_toolset_version`` just a dict resolution like ``{'170': 'v110',..}.get(str(version))``

Maybe it is not a runner, but CMake is simply not ready to recognize ``version=14.36``?

**Comment by ssrobins** [comment]
Thanks for the info on what Conan is doing under-the-hood. I don't think it's a CMake thing, The Conan/CMake workflow worked fine locally and a simple 'hello world' CMake project worked fine in GitHub Actions.

**Comment by ssrobins** [comment]
The issue was worked around in GitHub Actions by adding back an older versions of MSVC, which I assume they will leave in place until it's fixed in the MSVC scripts. Closing.
