### ISSUE TITLE
How to genrate an error in generate method

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#14128]
### What is your question?

Hi

I wanted to use the generate  method to check to see if a variables is empty and stop the execution of the recipe file. I tried using self.output.error but it still continues to run the recipe file.  How can I terminate the recipe file if the error exist in the generate method?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

Thanks for your question.

You can raise a ``Exception("My error message")`` in any ``conanfile.py`` recipe method, and that will produce an immediate stop of the processing of the recipe and raise that error (in a clean way, no stack trace, but method and line in conanfile.py).

The only exception that doesn't immediately terminate processing is ``ConanInvalidConfiguration`` in the ``validate()`` method.

**Comment by Ed-CMI** [comment]
When you say Exception are you meaning ConanException?

**Comment by memsharded** [comment]
You can also ``raise Exception``. When it happens in a recipe method, Conan will capture it and convert it to a ``ConanException``

**Comment by Ed-CMI** [comment]
Thx for the support
