### ISSUE TITLE
Add more integration tests about editables with a full flow

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#14127]
### What is your suggestion?

We need a few more tests that exercise some good full flows for editable packages, see https://github.com/conan-io/conan/pull/14109 where we had a few problems:
 * package folder being None got caught by a semi-unreleated test, let's ensure there're some
 * Package info not running in the expected folder when the call_package_info base_folder was set to another folder was not caught whatsoever

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
We don't have time for this, I guess it will be prioritized when there is some issue around this.
Closing as not planned.
