### ISSUE TITLE
Linter false positive: build_requires

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1413]
With:

```
    def build_requirements(self):
        # useful for example for conditional build_requires
        if self.settings.os == "Windows":
            self.build_requires("strawberryperl/5.26.0@conan/testing")
```

```
Linter warnings
   WARN: Linter. Line 44: Instance of 'OpenSSLConan' has no 'build_requires' member
   WARN: Linter. Line 51: No exception type(s) specified
```

About the broad exception one... I vote to deactivate it.

**Comment by ntff** [comment]
Also:
```
Linter warnings                                  
    WARN: Linter. Line 12: self.build_requires is not callable
```

for conanfile:
```python
from conans import ConanFile

class package(ConanFile):
    name            = "second"
    version         = "0.0.0"
    description     = "default"
    url             = "http://gitlab.com"
    license         = "default"
    build_requires  = ()

    def build_requirements(self):
        self.build_requires("first/0.0.0@user/stream")

    def build(self):
        pass
```

Accessing self.build_requires as callable is an example in official doc: http://conanio.readthedocs.io/en/latest/mastering/build_requires.html
Has something changed? Are there a better way to do the same? Should be the doc updated?

**Comment by drodri** [comment]
No, it is almost the same warning. As you tricked it declaring a local build_requires, it doesn't complain that it doesn't exist, but it complains that it is not callable (following your declaration).

The linter is "static", it doesn't know everything you change in runtime. You will be fine removing the ``build_requires`` declaration, and we will remove the linter warning for next 0.26. Thanks!
