### ISSUE TITLE
[question] How to hanlde Src code and CFG files properly?

### ISSUE THREAD

**Issue by Edgar8504** [conan-io/conan#14130]
### What is your question?

Hello,
I have a question regarding how is the best approach to handle a project in which we have "static " code (since this code does not change) and then we have Configuration files that the user can modify and select specific features, those Configuration files are needed as input for the "static" code in  order to generate an executable or library.
So far we are compiling each time all the code since the strong dependency between static code and configuration files.
I know, probably modifying the static code in order to avoid the strong CFG files dependencies could be the solution, but since this is a third party code is hard to do modifications.
I wonder if Conan has an approach for this kind of issues.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Edgar8504 

Thanks for your question.
I think the binary model in Conan is very powerful, so it might indeed help with your use case. But I'd need to understand it a bit better:

> I have a question regarding how is the best approach to handle a project in which we have "static " code (since this code does not change) and then we have Configuration files that the user can modify and select specific features, those Configuration files are needed as input for the "static" code in order to generate an executable or library.

Even if the users can modify the configurations, are those configurations infinite? It is more or less a reduced set? Are there some higher level abstractions, like I don't know, the combinations of 2 or 3 different selectors, with a few different values each? Is it expected that some configurations are "popular" or very typical and you want to be able to reuse those binaries without necessarily rebuilding from source again and again the same configuration?

> I know, probably modifying the static code in order to avoid the strong CFG files dependencies could be the solution, but since this is a third party code is hard to do modifications.

This shouldn't be an issue, Conan in fact acts like a wrapper around this kind of problem, providing some isolation and higher level abstraction over it.

As a first approach, I think it could be considering if adding a bunch of ``options`` to the recipe, that maps to different CFGs would be doable. ``options`` can be as many as you want, with as many values as you want (or no value), or even generic ANY value.

**Comment by Edgar8504** [comment]
> Even if the users can modify the configurations, are those configurations infinite? It is more or less a reduced set? Are there some higher level abstractions, like I don't know, the combinations of 2 or 3 different selectors, with a few different values each? Is it expected that some configurations are "popular" or very typical and you want to be able to reuse those binaries without necessarily rebuilding from source again and again the same configuration?

Yes you are right, those configurations are more a reduced set, many of them are higher level abstractions as you pointed out. 
Also could be some "popular" or common configuration that probably we can have ready (probably store as a specific version) and reuse those binaries.

> As a first approach, I think it could be considering if adding a bunch of `options` to the recipe, that maps to different CFGs would be doable. `options` can be as many as you want, with as many values as you want (or no value), or even generic ANY value.

Ok, this approach sounds reasonable, thanks for the suggestion.

**Comment by memsharded** [comment]
Ok, great, thanks for the feedback.
If the response is good so far, I am closing this ticket as solved, but don't hesitate to open new tickets for any further question or issue that you might have. Thanks!
