### ISSUE TITLE
[question] Select packages from conan index center (*@_/_) in profiles

### ISSUE THREAD

**Issue by c0rt** [conan-io/conan#14139]
### What is your question?

Hello!
I am using conan 1. I am migrating to conan 2.
I build own packages with user and channel. For example myuser/mychannel.

I want to set different parameters in the profile for my packages and from the conan index center. In the conan index center, recipes and packages have user and channel == _/_. Therefore, I select these packages separately in the profile.

```
[conf]
tools.build:cxxflags = ['-Werror']
*@:tools.build:cxxflags = []
```
Or like this:
```
[conf]
tools.build:cxxflags = ['-Werror']
*@_/_:tools.build:cxxflags = []
```

But when I build, all packages are built with the `-Werror` flag for some reason.

Can you please tell me how can I select packages that have user=_ and channel=_?

I also run the `conan search` command
`conan search '*@'`
And the packages I need are displayed. But the configuration in the profile doesn't apply the same pattern.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @c0rt 

Thanks for your question. I am submitting https://github.com/conan-io/conan/pull/14140 with a test that verifies this can be done with:
```
[conf]
user.myteam:myconf=myvalue1
*@user/channel:user.myteam:myconf=myvalue2
```
The latest match has priority, can overwrite previous value, so the ``user/channel`` pattern has priority over the more general pattern. The whole test you can see it in https://github.com/conan-io/conan/pull/14140/files


I hope this helps.

**Comment by c0rt** [comment]
Thanks a lot for the quick response!

Oh sorry, I have to add.
My company builds packages with different user and channel, the final list is not known, so I want to separately select packages from the conan index center.

And setting pattern like this: `*@_/_:user.myteam:myconf=myvalue1` doesn't work(

**Comment by memsharded** [comment]
You can do:
```
 [conf]
user.myteam:myconf=myvalue1
*@*/*:user.myteam:myconf=myvalue2
```
This seems to pass the test, because the matching for "all things with user channel" will not match packages without user and channel

**Comment by memsharded** [comment]
> My company builds packages with different user and channel, the final list is not known, so I want to separately select packages from the conan index center.

As a side note, please have in mind that using channels for denoting "maturity" of the package and use them for "promotions" or "stages" and modifying them (``conan copy`` in 1.X, has been removed in 2.0) is not recommended since some time ago. The recommendation is to treat user/channel as a constant for packages, and run promotions by having different server repositories and copying packages from the "develop" repository to the "production" repository, but without modifying or renaming the packages.

**Comment by c0rt** [comment]
> This seems to pass the test, because the matching for "all things with user channel" will not match packages without user and channel

Wow, it works!
It was not clear to me.
Thank you very much!

> As a side note, please have in mind that using channels for denoting "maturity" of the package and use them for "promotions" or "stages" and modifying them (conan copy in 1.X, has been removed in 2.0) is not recommended since some time ago. The recommendation is to treat user/channel as a constant for packages, and run promotions by having different server repositories and copying packages from the "develop" repository to the "production" repository, but without modifying or renaming the packages.

Yes thank you! We already know about it :)

Thanks for your hard work!
