### ISSUE TITLE
[bug] Conan mishandles cache path in symlinked homedir

### ISSUE THREAD

**Issue by iskunk** [conan-io/conan#14136]
### Environment details

* Operating System+version: Red Hat Enterprise Linux 7
* Conan version: 2.0.6
* Python version: 3.8.3

### Steps to reproduce

At my site, home directories are mounted on a typical Unix system using a combination of an automounter and symlinks. For example, given a user `robert`, the automounter will mount his homedir at a path like
```
/nfs/home14.internal.example.com/vol/vol374/r/ro/robert
```
but then for easier access, it will also create a symlink:
```
/user/robert -> /nfs/home14.internal.example.com/vol/vol374/r/ro/robert
```

At present, even though `HOME` is set to `/user/robert`, Conan will find the ugly long NFS path and use it for all cache operations. This is undesirable, especially when the long path gets baked into generated files and symlinks.

----

After some digging, I found that the culprit is an `os.path.realpath()` call at the top of `class DataCache`:

https://github.com/conan-io/conan/blob/81b195262350a13525a44a0b079c9a4eab9fb1cd/conan/internal/cache/cache.py#L20

Changing that to `os.path.abspath()` is enough to allow Conan to use the short path ubiquitously.

I believe `abspath` is in the spirit of what was originally intended with `realpath`, and if there is no objection, I'd like to submit a PR that makes this change.

**Comment by memsharded** [comment]
Hi @iskunk 

Thanks for your report.
I have been having a look to the relevant source code and comparing it with Conan 1.X implementation, and it seems that the proposed fix might be ok, so feel free to submit it (please also test it thoroughly in your setup if possible). Thanks for offering to contribute!

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/14164, will be in next 2.0.8
