### ISSUE TITLE
[question] How to configure XcodeDeps to silence warnings from dependencies?

### ISSUE THREAD

**Issue by wAuner** [conan-io/conan#14147]
### What is your question?

We're using Xcode and boost is among our dependencies. However, boost causes a lot of warnings (and with Werror fails to build) and thus we're only able to use boost by specifying the header search paths via `-isystem` which in an xcconfig file needs to be added to `OTHER_CPLUSPLUSFLAGS`.

So I'd like to use the `XcodeDeps` generator, but instead of putting the include paths to `HEADER_SEARCH_PATHS`, I need them to be added to `OTHER_CPLUSPLUSFLAGS` via `-isystem path/to/include`.

How can I achieve that? Is there maybe an option for that or do I need to write my own `XcodeDepsNoWarnings` that does that?
Any suggestion is appreciated.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @wAuner 
Thanks for your question.

Maybe it is not necessary to do it in OTHER_CPLUSPLUSFLAGS, ``SYSTEM_HEADER_SEARCH_PATHS`` seems to exist too.

In this sense, maybe we want to change the default to this one? I think it will be more aligned to what other generators are doing?

Maybe you want to do a quick check, if you know how to run Conan from source, just modify the code in XcodeDeps and try?

**Comment by wAuner** [comment]
Sounds like a good idea, will do. I've already changed the XcodeDeps generator to use `OTHER_CPLUSPLUSFLAGS` for testing. Tomorrow I'll test it with `SYSTEM_HEADER_SEARCH_PATHS` as suggested. 
Sounds like it would be more consistent as you say, according to #8543  the cmake gen also uses this approach (via `-isystem` directly in this case).

**Comment by wAuner** [comment]
ok using `SYSTEM_HEADER_SEARCH_PATHS` is probably much nicer than doing it via `OTHER_CPLUSPLUSFLAGS` and very easy to implement. I'll open a PR. Thanks for the quick response.

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/14157
