### ISSUE TITLE
Not able to use cmake different versions.

### ISSUE THREAD

**Issue by sangramjadhavbhtc** [conan-io/conan#14148]
### What is your question?

Hi!
Not able to use another version of cmake than **3.22.6**. Tried differnt vesions also but it still not working. Dont understand the reason. 
On my system **cmake version 3.26.4** was installed and I am using **Conan 2.0.7**

Conanfile.txt :
```
[tool_requires]
#[build_requires]
#cmake/3.23.0
#cmake/3.22.6
cmake/3.22.5

[generators]
CMakeDeps
CMakeToolchain
VirtualBuildEnv
```
 
C:\Users\sangram.jadhav\Desktop\CONAN\cmakeproject\xyz>conan install . -pr:h=myprofile --output-folder=build --build=missing

Output:
```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Windows
[conf]
tools.cmake.cmaketoolchain:generator=Unix Makefiles
[buildenv]
PATH+=(path)C:\mingw64\bin

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
cmake/3.22.5: Not found in local cache, looking in remotes...
cmake/3.22.5: Checking remote: conancenter
cmake/3.22.5: Downloaded recipe revision 62001c2c99e2501a5f92bc74864e588e
Graph root
    conanfile.txt: C:\Users\sangram.jadhav\Desktop\CONAN\cmakeproject\xyz\conanfile.txt
*********************************************************
Recipe 'cmake/3.22.5' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'cmake/3.22.5' not resolved: cmake/3.22.5: Cannot load recipe.
Error loading conanfile at 'C:\Users\sangram.jadhav\.conan2\p\cmake2d649888e7010\e\conanfile.py': Unable to load conanfile in C:\Users\sangram.jadhav\.conan2\p\cmake2d649888e7010\e\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sangram.jadhav\.conan2\p\cmake2d649888e7010\e\conanfile.py", line 5, in <module>
    from conans import tools, AutoToolsBuildEnvironment, CMake
ImportError: cannot import name 'tools' from 'conans' (C:\Users\sangram.jadhav\AppData\Roaming\Python\Python311\site-packages\conans\__init__.py)
```
Same happing when selecting other versions. For default, cmake version it will work but not working for desired version.

**Comment by czoido** [comment]
Hi @sangramjadhavbhtc,

Thanks for the question. What's happening there is that there are some versions in Conan Center Index that do not have Conan v2 compatible recipes, `cmake/3.22.5` is in fact one of them and will fail in Conan v2. Looks like for 3.22 the only compatible one is `3.22.6`. So you won't be able to use any other version lower than `3.22.6` from Conan Center Index (in general, I would recommend to go always for the latest patch version to ensure Conan 2.x compatibility). If that's a problem, you can always clone the Conan Center Index repository and modify the files in the cmake recipe folder to generate a version lower than 3.22.6 that's compatible with Conan 2.X.

**Comment by sangramjadhavbhtc** [comment]
Only cmake/3.22.6 is functional. I have tryied upper version like cmake/3.23.0, but result is same.

**Comment by czoido** [comment]
> Only cmake/3.22.6 is functional. I have tryied upper version like cmake/3.23.0, but result is same.

As I said previously, please try with the latest patch version (in general, for all recipes, I would recommend doing this because we sometimes drop old patch versions from Conan Center Index), if you do a `conan search cmake -r conancenter` pick the latest patches versions >= 3.19. These should be compatible: `3.19.8`, `3.20.6`, `3.21.7`, `3.22.6`, `3.23.5`, `3.24.4`, `3.25.3`, `3.26.4`

**Comment by czoido** [comment]
Hi @sangramjadhavbhtc, could you finally install cmake without problems? 
May I close the issue? Thanks!

**Comment by sangramjadhavbhtc** [comment]
Yes, I have tried version provided by you i.e. ```3.19.8, 3.20.6, 3.21.7, 3.22.6, 3.23.5, 3.24.4, 3.25.3, 3.26.4. ```  These are working for me. Thank you very much!
