### ISSUE TITLE
[feature] Add support for creating MultiPackagesList from graph

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#14144]
### What is your suggestion?

Currently, it's possible to create this object from [graph file](https://github.com/conan-io/conan/blob/release/2.0/conan/api/model.py#L75), however conan graph API returns the [graph object](https://github.com/conan-io/conan/blob/release/2.0/conan/api/subapi/graph.py#L141).

Now, in order to use `MultiPackagesList` to filter the graph and obtain the list of packages that have been built by dependency I need to serialize the graph object into the file and then load it. This is inefficient.

I'm currently working on a custom command that will:
- invoke `conan install --build missing` for each and every build type that we use in the company
- invoke `cmake --preset <generated-preset>` to automatically create the cmake project with installed dependencies

The idea is for this command to also return the list of packages that have been built by dependency, so I need to filter those packages from each and every dependency graph (for each build type), merge everything into a single PackageList, and serialize that into JSON using formatters so that the produced JSON is then compatible with `conan upload` command.

The custom command is intended to be used both by developers (in which case, the JSON pkglist of built dependencies is not important) and CI, where I would like to use the pkglist to upload the built binaries to the Artifactory server, similar to [this example in the Conan documentation](https://docs.conan.io/2/examples/commands/pkglists.html#building-and-uploading-packages).

Currently, I can copy the implementation of the linked code into my custom command, but it uses Conan's private API (in the `conans` package), which I'm not very comfortable using, as even a minor change in the conan version can break it.

Alternative workarounds are also welcome.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DoDoENT 

Thanks for your suggestion.

It would be good to better understand this request, to see it as a more detailed interface.

At the moment, if you want to create a ``MultiPackagesLists`` from graph, it would be done by:

```python
conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)

# This is the current interface
save("myfile.json",  json.dumps({"graph": deps_graph.serialize()})
multi_pkg_list = MultiPackagesList.load_graph("myfile.json", graph_binaries=["build"])
```

Yes, maybe it is not the most efficient thing, but even for huge graphs this should take less than one second, so I am not sure if I understand the pain. What would be your suggestion here, to have a ``MultiPackagesList.from_graph(deps_graph, ...)`` directly?

**Comment by DoDoENT** [comment]
It's not the pain - it's just the OCD 😃 . It annoys me to be inefficient when I don't need to be 😂 

I've seen in other parts of conan API that you sometimes use `load` to load something from a file, and `loads` to load the same thing from a string.

`from_graph` sounds like a good idea.

Btw, the support for custom commands and Conan Python API is really a game changer compared to v1. They are very flexible and provide the ability to create workflows that were really difficult with v1 and required a lot of custom scripts around conan. Great work! 👏
