### ISSUE TITLE
Make Graph display available for build_order

### ISSUE THREAD

**Issue by johnmj** [conan-io/conan#1414]
Could we have to ability to create graphs for build_order ? At the moment the -bo option displays the array of package(s) to be built if a downstream pkg changes - it would be great if we could convert this array into graph.

Example:

conan info Boost/1.60.0@lasote/stable -bo zlib/1.2.8@lasote/stable -g mygraph.dot

Currently displays;
[zlib/1.2.8@lasote/stable], [Boost/1.60.0@lasote/stable]

Would like to also create the mygraph.dot file with the above mapping.

**Comment by memsharded** [comment]
Conan 2.0 implement custom commands, it should be relative straightforward to implement this, and it doesn't seem that having this built-in in Conan was worth the effort, closing.
