### ISSUE TITLE
[question][bug] XcodeDeps with custom configuration does not behave as expected

### ISSUE THREAD

**Issue by wAuner** [conan-io/conan#14149]
### What is your question?

Hi,

I'm trying to understand the example from the [XcodeDeps tutorial with custom configurations](https://docs.conan.io/2/reference/tools/apple/xcodedeps.html#custom-configurations).

I've added the `conanfile.py` from the example and ran
```
> conan profile show
Host profile:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu20
compiler.libcxx=libc++
compiler.version=14
os=Macos

Build profile:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu20
compiler.libcxx=libc++
compiler.version=14
os=Macos

> conan install . --output-folder=build --build=missing -o 'shared=True'
```
 I was expecting that the config specifier in the resulting xcconfig files would now reflect the adapted configuration name, e.g. `ReleaseShared` - I thought that was the whole point.
But when I look inside the resulting `conan_zlib_zlib_release_arm64.xcconfig` then it's just `HEADER_SEARCH_PATHS_zlib_zlib[config=Release][arch=arm64][sdk=macosx*] ...`.

Is my understanding wrong?

We have several differently named Debug and Release configurations, e.g. "Release with asserts" and for that I need an xcconfig for all of them.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by wAuner** [comment]
If it was intended to work the way I would expect it to (and the docs suggest), then the problem might be this line:
https://github.com/conan-io/conan/blob/81b195262350a13525a44a0b079c9a4eab9fb1cd/conan/tools/apple/xcodedeps.py#L46

The first format argument should then be `self.configuration` instead of `(settings.get_safe("build_type")`. Otherwise the overwriting that's done in the docs has no effect:
```python
    def generate(self):
        xcode = XcodeDeps(self)
        # We assume that -o *:shared=True is used to install all shared deps too
        if self.options.shared:
            xcode.configuration = str(self.settings.build_type) + "Shared"
        xcode.generate()
```

**Comment by wAuner** [comment]
I've changed the XcodeDeps generator in a fork to experiment with and in this version it behaves as expected:
https://github.com/wAuner/conan/commit/1348435bde65c7c8371864ecba0ed0d4bf0437e7

**Comment by memsharded** [comment]
Hi @wAuner 

Thanks for your report.
I think that the above sounds right, if you want to submit a PR with it, that would be great.

**Comment by wAuner** [comment]
ok great. I'll submit the PR.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/14168, will be in 2.0.8
