### ISSUE TITLE
[feature] Add '--strip' option to cmake install

### ISSUE THREAD

**Issue by sagi-ottopia** [conan-io/conan#14166]
### What is your suggestion?

Can you add a parameter to `cmake.install` function in order to be able to strip binaries before install ?

install and strip were added to CMake about 4 years ago, and if I got it correctly in version 3.15
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/3069

Strip is very useful to remove debug symbols (actually all DWARF extension) from binaries and especially release binaries.

I tried many options to make it work with conan, but without success, so I think adding this option as a parameter to `install` function in `cmake` tool will be the best solution instead of some workarounds.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/14167
