### ISSUE TITLE
[question] The remote doesn't support revisions (https://conan.io/center)

### ISSUE THREAD

**Issue by geranim0** [conan-io/conan#14179]
### What is your question?

Hi, started having this issue today, wondering what might be causing it and how to fix?

`ERROR: Package 'boost/1.82.0' not resolved: The remote doesn't support revisions. Conan 2.0 is no longer compatible with remotes that don't accept revisions.. [Remote: conancenter].`

`conan remote list:
conancenter: https://conan.io/center [Verify SSL: True, Enabled: True]`

`conan -v:
Conan version 2.0.5`

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @geranim0 

For some reason you added the wrong remote URL
The http://conan.io/center is just the web url, not the conancenter API url that should be used.

You can see the default remote in: https://docs.conan.io/2/reference/config_files/remotes.html

which is https://center.conan.io, looks similar, but it is not. If you remove the ``remotes.json``, it will be re-generated with the default value.

**Comment by geranim0** [comment]
Ah! Thanks!
