### ISSUE TITLE
[bug] generated config files by CMakeDeps have different version logic than CMake-generated ones

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#14172]
### Environment details

* Operating System+version:
* Compiler+version:
* Conan version: 2.0.7
* Python version:

### Steps to reproduce

With a CMakeLists that has a call like the following:
```
find_package(fmt 6.2 CONFIG REQUIRED)
```

If we let the project consume the files generated by CMakeDeps:
```
conan install --require=fmt/10.0.0 -g CMakeDeps -g CMakeToolchain
cmake [....] -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
```

### Logs

```
CMake Error at CMakeLists.txt:6 (find_package):
  Could not find a configuration file for package "fmt" that is compatible
  with requested version "6.2".

  The following configuration files were considered but not accepted:

    /Users/luisc/dev/conan-io/conan-toy-projects/bug-reports/fmt-version/consumer/conan/fmt-config.cmake, version: 10.0.0
```

The expected result would be that version 10.0.0 satisfies 6.2 because it's greater and still considered compatible. This _may_ not be a general assumption to make for all libraries, but it is for fmt.

If we allow the same project to locate and consume the config files generated by `cmake install` on the fmt project, it generates a `fmt-config-version.cmake` file with the following contents:
```
# This is a basic version file for the Config-mode of find_package().
# It is used by write_basic_package_version_file() as input file for configure_file()
# to create a version-file which can be installed along a config.cmake file.
#
# The created file sets PACKAGE_VERSION_EXACT if the current version string and
# the requested version string are exactly the same and it sets
# PACKAGE_VERSION_COMPATIBLE if the current version is >= requested version.
# The variable CVF_VERSION must be set before calling configure_file().

set(PACKAGE_VERSION "10.0.1")

if (PACKAGE_FIND_VERSION_RANGE)
  # Package version must be in the requested version range
  if ((PACKAGE_FIND_VERSION_RANGE_MIN STREQUAL "INCLUDE" AND PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION_MIN)
      OR ((PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "INCLUDE" AND PACKAGE_VERSION VERSION_GREATER PACKAGE_FIND_VERSION_MAX)
        OR (PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "EXCLUDE" AND PACKAGE_VERSION VERSION_GREATER_EQUAL PACKAGE_FIND_VERSION_MAX)))
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  endif()
else()
  if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
      set(PACKAGE_VERSION_EXACT TRUE)
    endif()
  endif()
endif()
```

where the logic, in the absence of a version range, does ` set(PACKAGE_VERSION_COMPATIBLE TRUE)` when this conditional is false:   `if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)` - that is, it is considered compatible if the version is greater than the requested one, UNLESS `EXACT`.

CMakeDeps only marks it as CMake-compatible if the major version is match. While that is aligned with the Conan assumptions that changes in the major component of the version are breaking changes - it does impose only _one_ way of defining compatibility. The fmt CMakeLists has this:

```
  write_basic_package_version_file(
    ${version_config}
    VERSION ${FMT_VERSION}
    COMPATIBILITY AnyNewerVersion)
```
Where `COMPATIBILITY` can take the following values   `AnyNewerVersion|SameMajorVersion|SameMinorVersion|ExactVersion` according to the CMake [documentation](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html) - maybe there's some information that could live in the recipe to reflect this so that CMakeDeps can generate something equivalent? Otherwise `CMakeDeps` is doing a strict `SameMajorVersion` regardless of compatibility.

See https://github.com/conan-io/conan-center-index/pull/17545/files for a workaround to this.

**Comment by memsharded** [comment]
Duplicated to https://github.com/conan-io/conan/issues/13809
