### ISSUE TITLE
Detect VS2017 when the env-var VS150COMNTOOLS is set

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1417]

**Comment by SSE4** [comment]
@memsharded I think it already works as for 0.25

**Comment by memsharded** [comment]
Thanks for telling. I was talking about the initial detection routine to define default profile: 
https://github.com/conan-io/conan/blob/develop/conans/client/detect.py#L109

VS 15 2017 is not even being checked.

This is implemented in: https://github.com/conan-io/conan/pull/1661
