### ISSUE TITLE
[bug] Error in xmake generator

### ISSUE THREAD

**Issue by jputcu** [conan-io/conan#14170]
### Environment details

As an experiment I was trying out `xmake`, depending on a conan package:

~~~~
add_requires("conan::nanodbc/2.14.0", {alias = "nanodbc"})
add_requires("conan::termcolor/2.1.0", {alias = "termcolor"})

target("Logtailer")
    set_kind("binary")
    add_files("main.cpp")
    add_packages("termcolor", "nanodbc")
~~~~

* conan 2.0.7
* xmake v2.7.9+20230515 (Manjaro package)

~~~~~
======= Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to /home/jorisp/Workspace/GICC/logtailer/build/.conan/nanodbc/2.14.0
conanfile.txt: Generator 'XmakeGenerator' calling 'generate()'
conanfile.txt: ERROR: Traceback (most recent call last):
  File "/home/jorisp/.local/lib/python3.11/site-packages/conans/client/generators/__init__.py", line 92, in write_generators
    generator.generate()
  File "/home/jorisp/.conan2/extensions/generators/xmake_generator.py", line 34, in generate
    dep_cppinfo = dep.cpp_info.copy()
                  ^^^^^^^^^^^^^^^^^
  File "/home/jorisp/.local/lib/python3.11/site-packages/conans/model/build_info.py", line 440, in __getattr__
    return getattr(self._package, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_Component' object has no attribute 'copy'

ERROR: Error in generator 'XmakeGenerator': '_Component' object has no attribute 'copy'
~~~~~

**Comment by memsharded** [comment]
Hi @jputcu 

Thanks for reporting.
the ``XmakeGenerator`` does not belong to Conan, I think it is implemented in the Xmake side. You might need to report this issue in their repo.

**Comment by waruqi** [comment]
This is due to the fact that xmake 2.7.9 initially supported conan 2.0.5, but the new version of conan seems to have changed some module interfaces to break it.

You can try the xmake dev version, it should work


https://github.com/xmake-io/xmake/issues/3760

**Comment by jputcu** [comment]
Wow, thank @memsharded and @waruqi  for the quick feedback, now it works.

**Comment by memsharded** [comment]
For reference, in https://github.com/conan-io/conan/pull/14101/files we made the ``CppInfo`` a publicly documented interface (so far it was an internal non-documented class). At the moment the methods it documents are https://docs.conan.io/2/reference/tools/cpp_info.html (only ``aggregated_components`` and ``merge``

Thanks @waruqi for the quick help!
