### ISSUE TITLE
how to Include .h .hpp in v2

### ISSUE THREAD

**Issue by Crusoekid** [conan-io/conan#14181]
### What is your question?

In V1 i can use to load .h & .hpp in my build path
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```

how can i do this in v2?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Please check the Conan 2.0 tutorial: https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html

New integration is fully transparent, don't need to customize or modify the CMakeLists to included anything about Conan:
```cmake
cmake_minimum_required(VERSION 3.15)
project(compressor C)

find_package(ZLIB REQUIRED)

add_executable(${PROJECT_NAME} src/main.c)
target_link_libraries(${PROJECT_NAME} ZLIB::ZLIB)
```

(this integration is also included in Conan 1.X, you can use CMakeDeps and CMakeToolchain integration in 1.X too)

**Comment by Crusoekid** [comment]
I have read the tutorial
also i use include(${CMAKE_BINARY_DIR}/conan_toolchain.cmake) to link header
but if i did`t install lib in my PC env, so the conan 2.x can`t find lib.
when i use find_package(gflags REQUIRED) gflags::gflags 
it takes error
```
CMake Error at CMakeLists.txt:28 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake
```

**Comment by memsharded** [comment]
> also i use include(${CMAKE_BINARY_DIR}/conan_toolchain.cmake) to link header

toolchain files cannot be included, this is not how CMake works. They must be passed as ``-DCMAKE_TOOLCHAIN_FILE=...conan_toolchain.cmake`` as indicated in the documentation.

A shorter way if using CMake>=3.25 is to use the Conan generated CMakePresets

**Comment by Crusoekid** [comment]
how can i find `conanbuildinfo.cmake`this file in 2.x?
i just want to link libs and header in my project

**Comment by memsharded** [comment]
``conanbuildinfo.cmake`` no longer exist in Conan 2.0, it has been removed, it is not necessary.
You can link libs and headers in your project, with a fully transparent CMake integration, as explained above with this CMakeLists:
```cmake
cmake_minimum_required(VERSION 3.15)
project(compressor C)

find_package(ZLIB REQUIRED)

add_executable(${PROJECT_NAME} src/main.c)
target_link_libraries(${PROJECT_NAME} ZLIB::ZLIB)
```
That is the standard CMake syntax ``find_package + target_link_libraries``. No need for a custom ``conanbuildinfo.cmake``, standard CMake syntax can do it.

**Comment by Crusoekid** [comment]
But i must install lib in my /usr/lib?
Your way show to me make error above.
```
CMake Error at CMakeLists.txt:28 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake
```
i just make a gflags in my personal PC. So what`s wrong with me?

**Comment by memsharded** [comment]
> But i must install lib in my /usr/lib?

No, of course not. Packages are installed in the Conan cache

> Your way show to me make error above.

If you have an error, we need a way to reproduce. Please provide:
- Your conanfile
- Your CMakeLists.txt
- The exact commands you are using to get to that error
- The output of those commands

**Comment by Crusoekid** [comment]
confile is 
```
opencv/4.7.0@cabin/u18.04
gflags/2.2.2@cabin/u18.04

[generators]
CMakeDeps
CMakeToolchain


[options]
```
cmakelists is 
```
find_package(gflags REQUIRED)
find_package(opencv REQUIRED)

...
target_link_libraries(test gflags::gflags opencv::opencv)
```
bash is 
```
cmake   -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
        -DCMAKE_BUILD_TYPE=Debug \
        ../.. 
```
error is 
```
CMake Error at build/x86_64/cmakedeps_macros.cmake:64 (message):
  Library 'opencv' not found in package.  If 'opencv' is a system library,
  declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  build/x86_64/opencv-Target-release.cmake:24 (conan_package_library_targets)
  build/x86_64/opencvTargets.cmake:26 (include)
  build/x86_64/opencv-config.cmake:16 (include)
  CMakeLists.txt:29 (find_package)

```

**Comment by memsharded** [comment]
Can you please post the whole output of the ``conan install`` command?
For opencv the target names can be different than ``opencv::opencv``. They are typically printed to screen

**Comment by Crusoekid** [comment]
conan install ${prj_root}/conanfile/x86_64.txt \
        -s os=Linux \
        -s arch=x86_64 \
        --output-folder=./ \
        --deployer=direct_deploy

**Comment by Crusoekid** [comment]
is this?
```
-- Conan: Target declared 'gflags::gflags'
-- Conan: Target declared 'opencv::opencv'
```

**Comment by memsharded** [comment]
You are missing the details of ``conan install``

I think that you probably installed the ``build_type=Release`` (you can see it in the ``conan install`` logs), but you are trying to build the ``-DCMAKE_BUILD_TYPE=Debug``

**Comment by Crusoekid** [comment]
By the way, conan use `-DCMAKE_TOOLCHAIN_FILE` to set to chain.
When i cross-compile my code.how can i do this?

**Comment by memsharded** [comment]
You probably want to avoid the ``--deployer=direct_deploy``, for most use cases it is discouraged for normal development flows.

**Comment by memsharded** [comment]
For cross compile: https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html

**Comment by Crusoekid** [comment]
yes.my profile is 
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=11
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
```
but  when i change
```
cmake   -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
        -DCMAKE_BUILD_TYPE=Release \
``` 
it still error
```
CMake Error at build/x86_64/cmakedeps_macros.cmake:64 (message):
  Library 'opencv' not found in package.  If 'opencv' is a system library,
  declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  build/x86_64/opencv-Target-release.cmake:24 (conan_package_library_targets)
  build/x86_64/opencvTargets.cmake:26 (include)
  build/x86_64/opencv-config.cmake:16 (include)
  CMakeLists.txt:29 (find_package)
```

**Comment by Crusoekid** [comment]
i think 2.x is difficult for use include and lib.please get `conanbuildinfo.cmake` back. That`s make easy to load headers and libs in project

**Comment by memsharded** [comment]
> i think 2.x is difficult for use include and lib.please get conanbuildinfo.cmake back. That`s make easy to load headers and libs in project

It is not 2.0. The new CMakeDeps and CMakeToolchain integration has been in 1.X for years now. I am sorry, but this feature will not be back. The new integration is much better, more complete, and transparent, which is really very necessary to integrate with the rest of the C++ ecosystem nicely.


I don't know what it could be, it is difficult to guess, as you are not posting the complete files or the complete logs. You are also using custom ``opencv/4.7.0@cabin/u18.04`` packages, not packages from ConanCenter, so in that sense it is not possible to reproduce. If those packages are created in your company, did you create them? Do you have the full recipes and can you shared them?

**Comment by Crusoekid** [comment]
This opencv is build by my self. I can give you the `conan_source.tgz`? i just say use toolchain to load libs and headers is difficult for me to use. Also may build cross-compile also difficult for me. I will use 1.x also.

**Comment by Crusoekid** [comment]
Oh ,i see the conan_toolchain.cmake. it show me 
```
list(PREPEND CMAKE_LIBRARY_PATH "/home/xx/.conan2/p/opencfbd7269a24119/p/lib" "/home/xx/.conan2/p/b/gflagedcda145f92d2/p/lib")
```
opencv lack the v? what it happen? in my Artifactory have the v.But when i install it . it show me lach v

**Comment by memsharded** [comment]
> This opencv is build by my self. I can give you the conan_source.tgz

No, the ``conanfile.py`` is more relevant. The ``conan_source.tgz`` is an internal implementation thing. The sources for a package are the ``conanfile.py``

> opencv lack the v? 

The paths in the cache are not complete, just the very few letters, don't worry about that.

Cross compilation can also be done with Conan: https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html


> I will use 1.x also.

Yes, the CMakeToolchain and CMakeDeps works in 1.X and 2.0 too

**Comment by Crusoekid** [comment]
```
import os
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps
from conan.tools.files import copy

class CabinRecipe(ConanFile):
    name = "opencv"
    version = "4.7.0"

    # Optional metadata
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of opencv package here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "lib/*", "include/*"

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def package(self):
        copy(self, pattern="*", src=os.path.join(self.source_folder, "include"), dst=os.path.join(self.package_folder, "include"))
        copy(self, pattern="*", src=os.path.join(self.source_folder, "lib"), dst=os.path.join(self.package_folder, "lib"), keep_path=False)

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()


    def package_info(self):
        self.cpp_info.libs = ["opencv"]
        self.cpp_info.libdirs = ["lib"]
        self.cpp_info.includedirs = ["include"]
```
that is confile.py . i just push lib and include

**Comment by memsharded** [comment]
I am afraid that this still doesn't have enough information to reproduce, and it is impossible to know what is happening in your case.

I'd like to suggest a different angle. It is possible to create a fully reproducible project with very few commands:

```bash
# Create a ``dep/0.1`` package
$ mkdir dep && cd dep
$ conan new cmake_lib -d name=dep -d version=0.1
$ conan create .
# Now create a consumer. This will be equivalent to your project
$ cd .. & mkdir pkg && cd pkg
$ conan new cmake_lib -d name=pkg -d version=0.1 -d requires=dep/0.1
# You can inspect the generated code, the ``conanfile.py`` the ``CMakeLists.txt``, etc
# And this should work, you can create this package that depends on the ``dep/0.1`` one
$ conan create .
...
pkg/0.1 (test package): RUN: Release\example
dep/0.1: Hello World Release!
  dep/0.1: _M_X64 defined
pkg/0.1: Hello World Release!
  pkg/0.1: _M_X64 defined
```


This is a fully self-contained 2 packages project, in which the ``pkg`` consumer project is able to find the headers, link the libraries of the dependency ``dep/0.1``. Everything is there. You can see that the CMakeLists.txt of the consumer is just:

```cmake
find_package(dep CONFIG REQUIRED)

add_library(pkg src/pkg.cpp)
target_include_directories(pkg PUBLIC include)

target_link_libraries(pkg PRIVATE dep::dep)
```

So it doesn't require any explicit Conan calls, it is just standard CMake.

Please try the above steps, have a look to the code and how it works. Maybe that helps. 
If you still have issues, I'd recommend to put a full self-contained Github repo with the full code and detailed instructions how to reproduce the issue (hopefully a build script that runs it), and share the project repo link here. As you can see, it doesn't need to be the actual libraries, but "hello-world" like libraries generated with the ``conan new`` templates are good to reproduce issues.

**Comment by Crusoekid** [comment]
Thank you for your reply.
I'm using 1.x now and it's fine
When I have free time, I will try your method.
At the same time, I suggest to provide a template, just upload the compiled lib and headers

**Comment by memsharded** [comment]
> At the same time, I suggest to provide a template, just upload the compiled lib and headers

We have a full section in the docs dedicated to the topic of packaging compiled libraries, with working examples in code in the examples repo: https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html

As there is no further action from our side at the moment, I am closing the issue, don't hesitate to open a new one if you have any further question, thanks!
