### ISSUE TITLE
[bug] CMake toolchain logic doesn't handle Linux -> MacOS cross compilation

### ISSUE THREAD

**Issue by sfackler** [conan-io/conan#14186]
### Environment details

* Conan version: 2.0.7

### Steps to reproduce

1. Create a Conan recipe using a CMake toolchain.
2. Build with a Linux build profile and MacOS host profile, with the same architecture.
3. Note that `CMAKE_SYSTEM_NAME` is set to `Macos` rather than `Darwin`. You can see this either by looking at the generated CMake toolchain file, or by the warnings and build errors in CMake.

### Logs

```
System is unknown to cmake, create:
Platform/Macos to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
```

I think this logic needs to be updated to `os_host == "Macos" and (arch_host != arch_build or os_host != os_build)`: https://github.com/conan-io/conan/blob/b43eb83956f053a47cc3897cfdd57b9da13a16e6/conan/tools/cmake/toolchain/blocks.py#L732-L737

**Comment by memsharded** [comment]
Indeed! Thanks very much @sfackler for reporting and pointing to the solution.
I have submitted https://github.com/conan-io/conan/pull/14187 to fix it.
