### ISSUE TITLE
[question] Finding locally built packages

### ISSUE THREAD

**Issue by db4** [conan-io/conan#14196]
### What is your question?

I have a consumer project with some heavy Conan dependencies from conancenter (like Qt). Quite often these dependencies lack necessary binaries, that are built from sources during CI (due to `--build missing`). That takes ages so I would like to reuse those binaries in subsequent CI jobs. My idea is to search for packages with build folders at the end of CI and upload them to a cache Conan repo. But how to do that? `conan search` does not provide such info. I'm interested in 1.x and 2.x solutions if it's possible.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @db4, thank you for asking this question.
Quite timely as this is exactly what one of the latest features in Conan 2.0.7 aims to address, more details here: https://blog.conan.io/2023/06/28/Conan-bulk-package-operations.html

in a nutshell, if you have a workflow in CI where you pass `--build missing`, you can add the `--format json` flag to capture a json file, and then filter the binaries to obtain the list of the ones that were built from source, and then that filtered list can be used to upload only packages to a remote, e.g. ([docs here](https://docs.conan.io/2/examples/commands/pkglists.html)):

```
$ conan install --requires="spdlog/[*]" --build="*" --format=json > build.json
$ conan list --graph=build.json --graph-binaries=build --format=json > pkglist.json
$ conan upload --list=pkglist.json -r=myremote -c
```

Please let us know if this answers this question and satisfies the presented use case, thanks!

**Comment by memsharded** [comment]
Hi @db4 

Did the explanation above helped?

For 1.X, you also have the command json output https://docs.conan.io/1/reference/commands/output/install.html, that contains the information of what was built. The recommendation would be to parse the json and upload the "built" packages. It will be manual than in 2.0, but still preferred over trying ``conan search`` solutions for 1.X

**Comment by db4** [comment]
@memsharded,
Yes, the explanation was great but I was trying to implement automatic uploading for Conan 1.x first so did not reply immediately. Sorry for that.

BTW, I finally did it for 1.x with `conan lock create`, `conan lock build-order` and a simple python script:
```python
    import json
    import os
    import subprocess

    upload = os.environ.get('CONAN_UPLOAD')
    if upload:
        user = os.environ.get('CONAN_LOGIN_USERNAME')
        password = os.environ.get('CONAN_PASSWORD')
        if user and password:
            try:
                subprocess.run(f'conan user -p {password} -r {upload} {user}', shell=True, check=True)
            except CalledProcessError:
                # ignore authentification error
                exit(0)
        with open('bo.json', 'r') as content:
            bo = json.load(content)
            for group in bo:
                for (r, p, _, _) in group:
                    subprocess.run(f'conan upload {r}:{p} -r {upload}', shell=True)
```

**Comment by db4** [comment]
>```
>$ conan install --requires="spdlog/[*]" --build="*" --format=json > build.json
>$ conan list --graph=build.json --graph-binaries=build --format=json > pkglist.json
>$ conan upload --list=pkglist.json -r=myremote -c
>```
@jcar87 I've finally integrated this into my Conan 2.0 CI, and it works, thank you! But I had to work around the following problem. My CI uses Powershell, which creates `build.json` in UTF16LE with BOM encoding by default. So subsequent `conan list ...` unsurprisingly fails with:
```
ERROR: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
I solved it with `cmd /C "conan install --format=json > build.json"` which is not very convenient. Maybe Conan could check for BOM in its input files? Or someone knows how to force Powershell to use plain utf-8 without BOM?

**Comment by memsharded** [comment]
Conan already checks the BOM encoding in some text files. However, it is not very elegant, I'd prefer to avoid it if there is some other alternative, like making powershell to generate utf-8 files (quick check, it seems it is possible and Powershell has mechanisms: https://stackoverflow.com/questions/1707397/using-redirection-within-the-script-produces-a-unicode-output-how-to-emit-singl)

**Comment by db4** [comment]
@memsharded
Thanks for your suggestion. Closing the issue as solved.
