### ISSUE TITLE
conan install not working with 0.24.0

### ISSUE THREAD

**Issue by eugenwintersberger** [conan-io/conan#1419]
Somehow the installation seems to be broken for this version. I can search for packages but 

```
$conan install -r conan-transit -build missing . 
```
leads to
```
ERROR: Error while trying to get recipe sources for Boost/1.62.0@lasote/stable. No remote defined
```
checking my remotes with ``conan remote list`` I get
```
conan-center: https://conan.bintray.com [Verify SSL: True]
conan-transit: https://conan-transit.bintray.com [Verify SSL: True]
conan.io: https://legacy-server.conan.io [Verify SSL: True]
```
Is this a bug or is there something wrong with my setup?

**Comment by lasote** [comment]
I think something could be wrong in your local cache, try to remove your local Boost package and try again:

`conan remove Boost/1.62.0@lasote/stable`

**Comment by eugenwintersberger** [comment]
Thanks, that solved my problem.
