### ISSUE TITLE
[feature][2.x] conan cache path doesn't allow querying the package folder

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14198]
### What is your suggestion?

`conan cache path` only allows querying the _export_source_, _source_, _build_, and _metadata_ folders. It seems that the package folder, containing the final binaries, cannot be queried? Is that an oversight?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @fschoenm,

If you provide the reference with the `package_id` or the `package_id + package_revision` the package folder should be shown by default. Like this, for example:

```
# outputs the package folder for the latest package revision:
$ conan cache path zlib/1.2.13#e377bee636333ae348d51ca90874e353
/<path_to_local_cache>/.conan2/p/b/zlib27fc03271dsd3/p

# outputs the package folder for the specific package revision:
$ conan cache path zlib/1.2.13#e377bee636333ae348d51ca90874e353:6fe7fa69f760aee504e0be85c12b2327c716f9e7#90be0436f7d56b2561466a5914ecd2f1
/<path_to_local_cache>/.conan2/p/b/zlib27d3dds71f7ab/p

```

Hope this helps.

**Comment by fschoenm** [comment]
Thanks for the hint @czoido, I guess in that case the documentation is just wrong:

    --folder {export_source,source,build,metadata}
                          Path to show. The 'build' requires a package reference. If not specified it shows 'exports' path

**Comment by czoido** [comment]
We'll add some clarification there. Thanks for reporting @fschoenm

**Comment by fschoenm** [comment]
@czoido Maybe it would also be useful to allow `export` and `package` options in the `--folder` argument. IMO it's confusing (and very uncommon compared to other CLI tools) to have different behavior when not specifying such an argument instead of having defaults.
