### ISSUE TITLE
[question] Two questions about CMakePresets with conan

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14193]
### What is your question?

Hi

I have two questions about cmakepresets with conan:

1. How can I add CMake Variable to CMakePreset for an example -DENABLE_TESTS=ON
2. What could happen that vscode can not find conan cmake prests (it happens only in one project)?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @damian-tomczak, thank you for asking this question.

You can add variables in CMakeToolchain that are then expressed in the generated preset file as cache variables:

```
def generate(self):
    tc = CMakeToolchain(self)
    tc.cache_variables['ENABLE_TESTS'] = True
    tc.generate()
```

As for your second question, I would need more details - if you have some steps we can try to reproduce on our end to understand the issue, that would be really helpful, thanks!

**Comment by memsharded** [comment]
Just in case, regarding the specific use case of testing, Conan already implements built-in the enabling/disable of tests via the ``tools.build:skip_test`` conf, and the CMake ``BUILD_TESTING`` variable. So modifying recipes shouldn't be necessary in most cases, and just setting ``tools.build:skip_test`` in your profile or command line would be enough.

**Comment by damian-tomczak** [comment]
> Hi @damian-tomczak, thank you for asking this question.
> 
> You can add variables in CMakeToolchain that are then expressed in the generated preset file as cache variables:
> 
> ```
> def generate(self):
>     tc = CMakeToolchain(self)
>     tc.cache_variables['ENABLE_TESTS'] = True
>     tc.generate()
> ```
> 
> As for your second question, I would need more details - if you have some steps we can try to reproduce on our end to understand the issue, that would be really helpful, thanks!



> Just in case, regarding the specific use case of testing, Conan already implements built-in the enabling/disable of tests via the `tools.build:skip_test` conf, and the CMake `BUILD_TESTING` variable. So modifying recipes shouldn't be necessary in most cases, and just setting `tools.build:skip_test` in your profile or command line would be enough.

<3 Thank you <3
