### ISSUE TITLE
[question] The purpose of uploading the source code to private repo

### ISSUE THREAD

**Issue by penguin-madagascar** [conan-io/conan#14200]
### What is your question?

Hi! I am new to Conan and I am trying to build my own repository.

I notice in the document, you can use the _exports_sources_ attribute to define which files are source code, and upload them with the package. I am wondering what is the purpose of doing that. The first thing that came to my mind was that it can be downloaded and maintained by others, but are there more things that can be done with the source code?

For example, can Conan compile for me if I want Linux version of this package, when I didn't manually upload it.

Thanks for your patience

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @penguin-madagascar,

Thanks a lot for the question and welcome to the Conan community!

Yes, you're correct in your understanding of `exports_sources`. This attribute allows you to define which files are part of the source code of your library or application and they are uploaded along with the package. Then, you can install the package from any other platform different from the one you built the package for and build it for that platform. You can also build the same recipe for different configurations like `Release`, `Debug`, `shared`, `static` and using different `options`.

That's not the only way to handle sources in Conan packages, you can also get the sources from an external provider, like a git repo, a zip file hosted in a server... Please, check the docs about the `source()` method in the Conan docs: https://docs.conan.io/2/tutorial/creating_packages/handle_sources_in_packages.html

Also, I would recommend you to follow the Conan tutorial, it will give you an idea of the most importante Conan features and you can learn them with practical examples: https://docs.conan.io/2/tutorial.html

Hope this helps and don't hesitate to ask if you have more questions!
