### ISSUE TITLE
[question] Why is my simple example project not working

### ISSUE THREAD

**Issue by 0verEngineer** [conan-io/conan#14209]
### What is your question?

Why is my simple example project not working

Example Project: https://github.com/0verEngineer/Conan2SimpleTest

- For zlib i have undefined references on Linux and on Windows i can't even include the header.
- libssh2 header can not be included either because i don't know the naming / location or because some other problem (on windows and linux)

Linux:

`conan install . --output-folder=build-debug --build=missing`
<details>
  <summary>Expand for output</summary>
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

======== Computing dependency graph ========
Graph root
    conanfile.txt: /home/julian/Projects/test/Conan2SimpleTest/conanfile.txt
Requirements
    libssh2/1.10.0#7d19942c4516195553a998b4ad8b7030 - Cache
    openssl/1.1.1t#7d9fc949345908e1b8609d9d9f528a08 - Cache
    zlib/1.2.13#e377bee636333ae348d51ca90874e353 - Cache

======== Computing necessary packages ========
Requirements
    libssh2/1.10.0#7d19942c4516195553a998b4ad8b7030:06be257bc0f3f2de8ef8140c62a0c22aed88c00e#4e51820fb69902085da057caa370dbec - Cache
    openssl/1.1.1t#7d9fc949345908e1b8609d9d9f528a08:b469f21fcc058ee35f066fed6f93fcff17a9b73a#1bfe241f1d0218f1088722b975a0cf7b - Cache
    zlib/1.2.13#e377bee636333ae348d51ca90874e353:c81087b06d1a5beef0ad711fc32d45f7a425a8f3#0a69cd75c0f6d9f933d747fef0b5f1a7 - Cache

======== Installing packages ========
openssl/1.1.1t: Already installed! (1 of 3)
zlib/1.2.13: Already installed! (2 of 3)
libssh2/1.10.0: Already installed! (3 of 3)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: libssh2/1.10.0, zlib/1.2.13, openssl/1.1.1t
WARN: deprecated:     'cpp_info.build_modules' used in: openssl/1.1.1t

======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to /home/julian/Projects/test/Conan2SimpleTest/build-debug
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: CMakeToolchain generated: conan_toolchain.cmake
conanfile.txt: Preset 'conan-release' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-release' if using CMake>=3.23
conanfile.txt: If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/julian/Projects/test/Conan2SimpleTest/build-debug/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
conanfile.txt: CMakeToolchain generated: CMakePresets.json
conanfile.txt: CMakeToolchain generated: ../CMakeUserPresets.json
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: Generating aggregated env files
conanfile.txt: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
</details>

---

`cmake -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -S . -B build-debug`
<details>
  <summary>Expand for output</summary>
-- Using Conan toolchain: /home/julian/Projects/test/Conan2SimpleTest/build-debug/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 17 with extensions ON
-- The CXX compiler identification is GNU 13.1.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'Libssh2::libssh2'
-- Conan: Component target declared 'OpenSSL::Crypto'
-- Conan: Component target declared 'OpenSSL::SSL'
-- Conan: Target declared 'openssl::openssl'
-- Conan: Including build module from '/home/julian/.conan2/p/b/opens2b73ad451a70c/p/lib/cmake/conan-official-openssl-variables.cmake'
-- Conan: Target declared 'ZLIB::ZLIB'
-- Configuring done (0.1s)
-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091

-- Build files have been written to: /home/julian/Projects/test/Conan2SimpleTest/build-debug
</details>

---

`cmake --build ./build-debug`
<details>
  <summary>Expand for output</summary>
[ 50%] Building CXX object CMakeFiles/testConan.dir/src/main.cpp.o
[100%] Linking CXX executable testConan
/usr/bin/ld: CMakeFiles/testConan.dir/src/main.cpp.o: in function `main':
/home/julian/Projects/test/Conan2SimpleTest/src/main.cpp:7: undefined reference to `zlibVersion'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/testConan.dir/build.make:97: testConan] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/testConan.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
</details>

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @0verEngineer, thanks for your question.
In this case the issue seems to be caused by not specifying the proper `build_type` in the Conan invocation. If I add `-s build_type=Debug` to your Conan command example (or add `build_type=Debug` to my Conan profile), the compilation is carried out successfully.

Can you check if this fixes your issue? Else let me know and we can look into it further :)

**Comment by 0verEngineer** [comment]
Hey @RubenRBS thanks a lot for the fast answer.
You are right that fixes all the problems i listed above, thanks a lot :)

However i have another question: I get an error when i try to use the Ninja generator, if i pass no generator it works. Is there any way to use Ninja?

```

Generator

    Ninja

  does not support platform specification, but platform

    x64

  was specified.
```

**Comment by AbrilRBS** [comment]
How are you defining the generator? By setting the `tools.cmake.cmaketoolchain:generator` conf?

**Comment by 0verEngineer** [comment]
I (Clion) just pass `-G Ninja` to cmake.

How does this setting work?

**Comment by AbrilRBS** [comment]
Conan uses the concept of confs to set different aspects of how it works, [see the docs here](https://docs.conan.io/2/reference/config_files.html#)

Setting `tools.cmake.cmaketoolchain:generator=Ninja` either in your `global.conf`, your profile, or passed to Conan in the install command CLI as `-c tools.cmake.cmaketoolchain:generator=Ninja` might solve this issue too :)

Let me know if it doesn't!

**Comment by 0verEngineer** [comment]
Thanks a lot, it fixet my problem :) I think the documentation especially for profiles and the options and for switching from conan1 should be improved to avoid such questions. :)
