### ISSUE TITLE
[question] Auto compilation of an editable package

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14202]
### What is your question?

Hello,

I wonder whether is it a misconfiguration from my part or an intended behaviour. Are packages set as editable supposed to compile automatically if they are used by another package (that needs them) and have not been built beforehand? Or are we expected to do it manually? Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @Todiq thanks for your question.
It's not a misconfiguration on your part, editable packages are not "automatically" built, you need to do it manually for the changes to be picked up by others. ([See the editables docu page](https://docs.conan.io/2/tutorial/developing_packages/editable_packages.html) for an example of how the workflow looks like)

Note that editable packages can be specified to be built in `conan build` and `conan create` with the `--build` argument if you're using those, which might be of some help (Even if creating a package that uses an editable dependency is not really recommended!)

**Comment by memsharded** [comment]
The way to force the build from dependencies in editable the way to control it is with ``--build=editable``, but I think the ``--build=editable`` is under-documented. It is the value that should be passed to make sure the editable dependencies are also build from source (incremental builds, as they are local, so they can be no-op).

We might want to:
- Add some more test in our test suite to cover it a bit better
- Add some better docs

**Comment by memsharded** [comment]
This issue has been closed by https://github.com/conan-io/conan/pull/14358, that will also be used to force updating the docs including the ``--build=editable`` syntax
