### ISSUE TITLE
[question] How do I generate a usable XCode project when using Conan2 

### ISSUE THREAD

**Issue by SkyToGround** [conan-io/conan#14208]
### What is your question?

With Conan<2.0 I could do the following and get a usable Xcode project:

```
mkdir build_xcode & cd build_xcode
conan install .. --build=missing
cmake .. -G Xcode 
```

With Conan 2.0.6 I tried the following and although I get a Xcode project, Xcode is unable to find the dependencies:

```
mkdir build_xcode & cd build_xcode
conan install .. --output-folder=. --build=missing
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -G Xcode
```

When trying to build the targets in Xcode, it fails by not finding the header files of the dependencies.

I have tried to find documentation on what incantation will yield me a usable Xcode project but have so far failed, can anyone help or is the solution to go back to Conan < 2.0?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @SkyToGround thanks a lot for your question.

I can't test locally right now, but have you tried setting the `tools.cmake.cmaketoolchain:generator` conf to `Xcode`?
The issue might be fixed after adding it to the `global.conf` file, your profile, or passing it to conan install by using `- c tools.cmake.cmaketoolchain:generator=Xcode`

Let me know if that works, else we can look into it further :)

**Comment by SkyToGround** [comment]
@RubenRBS Thanks for the response. Your suggestion did not solve the issue. Because of that I went back to Conan 1.60.
When doing that I found some more aspects to this issue. It seems that Xcode project generation does not work properly when having Conan generate CMake "config" (_XXX-config.cmake_) scripts but it does work when using CMake "module" (_FindXXX.cmake_) scripts. Keep in mind that this only applies to generating Xcode projects, everything seems to work fine when using a _Makefile_.

**Comment by AbrilRBS** [comment]
@czoido suggested that this might be caused by mismatching configurations. Xcode seems to compile in Debug mode by default, and you are compiling for Release, did you make sure to change the build type to Relase in Xcode?

**Comment by SkyToGround** [comment]
Thanks, that was the last clue needed to solve this issue. Thus the incantation for using Conan, CMake and Xcode when writing software is as follows:

```
mkdir build_xcode & cd build_xcode
conan install .. --build=missing --output-folder=. --settings=build_type=Debug
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -G Xcode
```

Now that I understand the issue a bit better I was able to do a more precise Google search and it seems that #11607 is at the heart of this. Thus the incantation above makes it possible to compile using Xcode but does not do what I expected/want.

Regardless, hopefully the existence of this issue thread will help someone else and maybe push along the resolution of #11607.

@RubenRBS do you want me to close this issue?

**Comment by memsharded** [comment]
I am closing the https://github.com/conan-io/conan/issues/11607 issue, please check the comment https://github.com/conan-io/conan/issues/11607#issuecomment-1620636623 there explaining about the ``build_type``.

For ``Xcode`` generation, which is multi-config, if the intended flow is to be able to switch Debug and Release directly in the IDE without using Conan again, it should be more like (not tested, I don't have a Mac):

```
conan install .. -s build_type=Debug -c tools.cmake.cmaketoolchain:generator=Xcode
conan install .. -s build_type=Release -c tools.cmake.cmaketoolchain:generator=Xcode
cmake .. --preset conan-default
```
Specifying the ``Xcode`` generator is important so Conan is aware that it will use a multi-config generator and do the right thing creating files for dependencies.

If you want to force the use of Release dependencies also for the Debug build, then the first line as described in https://github.com/conan-io/conan/issues/11607#issuecomment-162063662:
```
conan install .. -s build_type=Release -s &build_type=Debug -c tools.cmake.cmaketoolchain:generator=Xcode
```

**Comment by SkyToGround** [comment]
Ok! Thanks!

**Comment by memsharded** [comment]
Happy to help! Don't hesitate to create new tickets if you have any further question, thanks!
