### ISSUE TITLE
[question] How to use the same version for "requires" in test_package

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#14218]
### What is your question?

I'm currently trying to fix itk recipe in CCI for conan v2. itk uses hdf5, but this dependency doesn't automatically add include directories because it's not needed for everyone. test_package wants to include hdf5 directly to check for some issues that have been present in the past. How to properly do this in conan v2?

self.requires(self.tested_reference_str) - this just adds static libraries for hdf5, but doesn't add anything else.
self.requires("hdf5/1.14.1") - this one works but it isn't automatically synchronized with main conanfile.py. I thought about using self.dependencies but it's still empty inside "def requirements(self):"?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Nekto89 

> I thought about using self.dependencies but it's still empty inside "def requirements(self):"?

Yes, the dependencies are not there yet! In ``requirements()`` method the requirements are being computed, the graph hasn't been expanded yet, so ``dependencies`` do not exist yet.

>  test_package wants to include hdf5 directly to check for some issues that have been present in the past. How to properly do this in conan v2?

What are exactly the issues? ``test_package`` purpose is to check the package has been created, not sure if these complex interactions between different parts of the dependency graph is a bit outside of the scope of ``test_package``, maybe these belong to the testing inside the ``build()`` of ``itk`` instead?

**Comment by Nekto89** [comment]
maybe the problem can be simplified. If package A depends on package B but doesn't add it to transitive dependencies, is it possible from package C to say "I want the same version of package B as in package A"? Some wildcard? Or change transitivity through CMakeDeps?

**Comment by memsharded** [comment]
I think a version range like ``self.requires("transitive/[*]")`` that accepts any version, if it is declared **after** the ones that define the version, should do the work, have you tried this approach?

**Comment by Nekto89** [comment]
> I think a version range like `self.requires("transitive/[*]")` that accepts any version, if it is declared **after** the ones that define the version, should do the work, have you tried this approach?

Thanks, this approach seems to be working.
