### ISSUE TITLE
[question] Using set_version to dynamically define version attribute

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#14211]
### What is your question?

Hi, I have learnt from the [documentation](https://docs.conan.io/2.0/reference/conanfile/methods/set_version.html) that I can use the `set_version() `method in a conan recipe, to dynamically define the version attribute.

I would like to do `self.version = load(self, "version.txt")`. However, `set_version() `will be invoked very early in the package creation process, when my version.txt does not exist yet. This file will be generated by CMake at project configuration time, using version information coded in the CMake `project()`. This approach is a common CMake way of doing, as described [here](https://cmake.org/cmake/help/v3.18/guide/tutorial/#adding-a-version-number-and-configured-header-file).

But `set_version() `expects version.txt to be there since the beginning of the process, hence it throws error.

Is there some way around this, or is this feature really only working if the recipe resides together with the code, and the version.txt is also there since the very beginning of the process? I am not storing the recipe together with the code, but rather I am cloning my conan agnostic Git repo with the `source()` method.

Thanks!
Luca

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @lucabarbiero,

Thanks for the question, as you say `set_version` will be invoked very early in the process of package creation, so if you don't have your sources already cloned next to the `conanfile.py` it will not be possible to get that information from local files or from the git repo information like the git tags versions. 

Can you give us more information on the workflow you want to follow? Are you using any branching model? Do you want to always clone a fixed branch?

Thanks a lot!

**Comment by freihamer** [comment]
Hi @czoido and thank you for getting to me quick!

My workflow to create a conan package looks like the following (but I am new to conan and I welcome suggestions):

1. There is a git repo with a CMake project in it. No conan recipe stored in that repo.
2. I write a conan recipe that will clone my git repo, checkout a fixed branch (develop) with the `source()` method. Then in the `build()` method I use the CMake wrapper to run `cmake.configure()`. Which will generate a Version.txt file. Finally use the `package()` to copy some binaries from the build folder to the package folder.

As understood, the problem with `set_version()` is that it gets called even before `source()` when not only my Version.txt is not there, but not even the CMake project that will generate it.

And if I get you right, I can't even retrieve version info from git tags, because again conan will search for those before cloning the git repo.

I can understand that package version information is needed first, because it's the fundamental piece of information conan needs to do anything in the cache. But then this dynamic `set_version()` feature is a bit limited..

Luca

**Comment by czoido** [comment]
Hi @lucabarbiero,
The thing that is setting the limitation here is using an external repository, if you had the conanfile along with the sources then it would be possible to read the latest tags information with conan with something like this:

```
    def set_version(self):
        git = Git(self, self.recipe_folder)
        self.version = git.run("describe --tags")
```

In this case, that you have an external repository, I would suggest to use some branching model or do releases in your repository and add the specific releases to the `conandata.yml` to manage versions. The tutorial section about handling sources may give you some ideas: https://docs.conan.io/2/tutorial/creating_packages/handle_sources_in_packages.html

**Comment by freihamer** [comment]
Thank you @czoido, I will investigate alternatives and maybe share my thoughts here.

What I don't like very much about storing the conan recipe along with the code in git, is that when I create the package, the source code also needs to be part of the package, in the local cache as well as in the remote. So I will end up having my code in both GitLab and JFrog. Which doesn't happen if the repo is external and cloned by the recipe. With this approach my code is only in GitLab and packages stored in JFrog only contain binaries, recipes and conan metadata.

This is what I have experienced so far. Is my understanding correct?

**Comment by czoido** [comment]
Hi @lucabarbiero,

Can you check this examples from the documentation? I think it could achieve what you want without the need of packaging the sources: https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html#examples-tools-scm-git-capture

Hope this helps

**Comment by freihamer** [comment]
Hi @czoido,

Great this solves my need to not package sources! At the same time, it solves a secondary issue that I had before: where to store the conan recipe if not in the git repo with the code? Now it all makes sense, and I can finally use set_version() to fetch version information from another file in the repo.

Thanks a lot for supporting.

Luca
