### ISSUE TITLE
[bug] Package for a build tool (used via tool_requires) with test_package cannot be created when lockfile is used

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#14214]
### Environment details

* Operating System+version: Linux and Windows
* Conan version: 2.0.7

### Steps to reproduce

1. Create a sample application package:
```
$ conan new cmake_exe -d name=my_tool -d version=1.0.0
```
2. Edit test_package/conanfile.py:
Change
```
    def requirements(self):
        self.requires(self.tested_reference_str)
```
to
```
    def build_requirements(self):
        self.tool_requires(self.tested_reference_str)
```
and
```
        self.run("my_tool", env="conanrun")
```
to
```
        self.run("my_tool", env="conanbuild")
```
3. Create the package:
```
$ conan create .
```
Works as expected!
4. Now create a lockfile:
```
$ conan lock create .
```
5. Try to create the same package again:
```
$ conan create .
```

### Logs

The second `conan create .` results in an error:
```
...
======== Launching test_package ========

======== Computing dependency graph ========
ERROR: Requirement 'my_tool/1.0.0#38b7b1a174eb2b9967f769eb9fb7e333%1688396412.639053' not in lockfile
```
In practice, it is thus impossible to build such a tool package with a test_package when using a lockfile.

By the way, when leaving the conanfile.py of the test_package in the original state (i. e. self.requires() instead of self.tool_requires() and env="conanrun" instead of env="conanbuild" etc.) then the package creation does work even when using a lockfile. Even though this can be used as a workaround for the time being, I think a build-tool package should actually be tested as a tool_requires in the test_package, shouldn't it?

**Comment by memsharded** [comment]
Hi @fourbft 

In Conan 2.0, the ``test_package`` is a completely separated thing, that happens only after the package build in the cache has happened. Also, the result of running ``conan create`` should be identical with our without the existence of ``test_package`` (or running with ``--test-folder=""`` to deactivate it). Put it explicitly:
```
conan create .
conan create . --test-folder=""
```
Should be identical and result always in the same outcomes.
That means that it is not possible to rely on the definition of ``tool_requires()`` that exists only in the ``test_package``, and it is necessary to indicate when something is a tool-require explicitly, with the ``--build-require`` argument.

The following test works for your use case:
```python
def test_lock_tool_requires_test_package():
    c = TestClient()
    test_package = textwrap.dedent("""
        from conan import ConanFile
        class Test(ConanFile):
            def build_requirements(self):
                self.tool_requires(self.tested_reference_str)
            def test(self):
                pass
            """)
    c.save({"conanfile.py": GenConanfile("tool", "0.1"),
            "test_package/conanfile.py": test_package})
    c.run("create .  --build-require")
    c.run("lock create .  --build-require")
    lock = c.load("conan.lock")
    assert "tool/0.1" not in lock  # Empty lockfile
    c.run("create .  --build-require")
    print(c.out)
```

Please let me know if this clarifies the issue.

**Comment by fourbft** [comment]
Hi @memsharded,
yes, I see the point. But I actually did not expect the test_package to influence the build of the "tested_reference_str" (i. e. the actual package). I was rather wondering, why it is, that when you require the "tested_reference_str" as a normal "requires" in the test_package, it does not need to be locked in the given lockfile and when you require it as a "tool_requires", Conan expects it to be in the lockfile? Does Conan internally add the "tested_reference_str" to the lockfile when creating the test_package? 

The fact, that it works with the "--build-require" parameter to "conan create", is that a side-effect of that parameter? I. e. does Conan then internally add the tested_reference_str to the build_requires section of the lockfile?

Ok, I just tested this with "--lockfile-out" to "conan create". Obviously this is exactly what happens. So I think I now understand, what is going on.

Actually, without that knowledge, it is a bit surprising, that it matters how you test your package in the test_package: as a requires or as a tool_requires. But on the other hand, it does not make much sense to have a test_package that requires the original package as tool_requires while not building it as a "build-require" in the first place. So Conan is consitent here.
(Maybe the error message could be improved: Instead of just complaining about "Requirement ... not in lockfile", Conan could say: "Hey, your test_package 'tool_requires' your package, while it was not built as a build-require!" - But the logic for that would probably be a bit challenging.)

The only little problem I still have is the "--build-require" parameter to "conan create". Our CI creates all packages via "conan create" and it currently does not know, if a package is intended to be a normal package or a build-require package. Would it make sense to add another package_type value to Conan, i. e. "build-require"? (There already is a "python-require", so this would seem to fit in).

On the other hand, most "build-require" packages can also be used as normal packages, so a valid solution - the one I implemented already - should be to build it as a normal "application" package and test it via "requires" in the test_package instead of "tool_requires".

So from my side, this issue would be solved.

**Comment by memsharded** [comment]
> yes, I see the point. But I actually did not expect the test_package to influence the build of the "tested_reference_str" (i. e. the actual package). I was rather wondering, why it is, that when you require the "tested_reference_str" as a normal "requires" in the test_package, it does not need to be locked in the given lockfile and when you require it as a "tool_requires", Conan expects it to be in the lockfile? Does Conan internally add the "tested_reference_str" to the lockfile when creating the test_package?

Yes, the first ``export`` operation that internally happen when calling ``conan create`` will update the lockfile, to guarantee that the ``test_package`` will be testing exactly that revision, and to avoid potential (future, still not supported concurrency) race conditions between parallel ``conan create`` in the same cache.


> The fact, that it works with the "--build-require" parameter to "conan create", is that a side-effect of that parameter? I. e. does Conan then internally add the tested_reference_str to the build_requires section of the lockfile?

Yes, the ``--build-require`` will make sure the first ``export`` updates the lockfile and puts the exported reference into the lockfile ``tool_requires``, not the regular ``requires``.


> The only little problem I still have is the "--build-require" parameter to "conan create". Our CI creates all packages via "conan create" and it currently does not know, if a package is intended to be a normal package or a build-require package. Would it make sense to add another package_type value to Conan, i. e. "build-require"? (There already is a "python-require", so this would seem to fit in).

It depends on how the automation is implemented. The thing is that ``--build-require`` does something even more important in some scenarios like cross-building, but also in regular builds. Lets say that you are building for Debug, but obviously you want your tool_requires to be Release for speed. With ``--build-require`` you don't need to figure out or change the profiles at all, you can use the same profiles all the time, and ``--build-require`` will manage to apply the right one, as if it was ``tool_required`` by other package.

The ``conan graph build-order`` tool will already provide the ``--build-require`` argument automatically, so no need to know.

For other cases, I think your comments are basically covered in this open ticket: https://github.com/conan-io/conan/issues/13440, that we will be considering. Please track that issue for future progress and feedback, I am closing this ticket as responded, thanks!
