### ISSUE TITLE
[question] Best way to use packaged (cross) compiler for building other packages

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14234]
### What is your question?

I'd like to use GCC (or other compilers) from a conan package. I actually created on and so far, I can use it like this:

```
$ conan install gcc/10.3.0 -g VirtualBuildEnv
$ source conanbuild.sh
$ which x86_64-linux-gnu-gcc
/home/fschoenm/.conan2/p/gcc87bb9f740b25f/p/bin/x86_64-linux-gnu-gcc
```

Now I experimented with using the _gcc_ package via `--tool-requires` and in that case, I can inject a CMake toolchain into my build process. But I don't really want all packages to depend on the package because it makes it difficult to switch compilers. So now I am looking for a different solution of how to use the packaged compiler into my build process:

* Do I just need to know how the compiler executables are called (_x86_64-linux-gnu-gcc_ in this case)?
* Do I have to set environment variables (CC, CXX, ...) in my virtual build environment to use the compiler?
* I there a way to generate/inject a CMake toolchain coming from the compiler package into my Conan runs?

So far I've tried the second approach but it's not really reliable. It also clashes if the profile is already setting environment variables.

Are there any best practices or a manual how to achieve that?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by samuel-emrys** [comment]
There's some discussion about compiler packages (particularly how to bootstrap them) available in https://github.com/conan-io/conan/issues/13533. Others have also found using a profile like the following helped:

```
[settings]
build_type=MinSizeRel
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++
compiler.version=12.2
os=baremetal

[tool_requires]
arm-gnu-toolchain/12.2.1

[conf]
{# conf stuff goes here #}
```

> But I don't really want all packages to depend on the package because it makes it difficult to switch compilers

Can you elaborate on this? It should be as simple as changing the compiler in your profile using the above example.

**Comment by fschoenm** [comment]
@samuel-emrys Thanks for the suggestion, I didn't know that would be possible. It's not possible to add a `--tool-requires` to the command line for example, which in my mind would be the same thing. I'm going to experiment with that.

**Comment by AndreyMlashkin** [comment]
Here I have a small experimental project to bootstrap gcc from conan compiler, using apt-installed gcc compiler.
https://github.com/AndreyMlashkin/minimalistic_conan_docker
