### ISSUE TITLE
[question] CMAKE_POLICY_DEFAULT_CMP0091

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14236]
### What is your question?

Hi,

When I'm using cmake preset generated by conan the cmake command `cmake --preset conan-debug ..` throws a warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091

```

What is the purpose of it and how can I avoid it?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @damian-tomczak 

As Conan is not parsing the CMakeLists.txt, it is always defining by default this policy, in case some projects define an old ``cmake_minimum_required()`` that doesn't have this policy defined.

The thing is that CMake is a bit annoying in this regard in my opinion (I don't fully agree with https://gitlab.kitware.com/cmake/cmake/-/issues/23602) I still don't get why it complains about a CMAKE_POLICY being defined, the fact that it has already that default value doesn't mean that it is not used (if the value was opposite it wouldn't warn IIUC).

So it cannot easily be avoided at this moment. It is true that it could be nice to have a way, but at the moment it seems too overkill for it.

**Comment by damian-tomczak** [comment]
Ohh, thank you

> Hi @damian-tomczak
> 
> As Conan is not parsing the CMakeLists.txt, it is always defining by default this policy, in case some projects define an old `cmake_minimum_required()` that doesn't have this policy defined.
> 
> The thing is that CMake is a bit annoying in this regard in my opinion (I don't fully agree with https://gitlab.kitware.com/cmake/cmake/-/issues/23602) I still don't get why it complains about a CMAKE_POLICY being defined, the fact that it has already that default value doesn't mean that it is not used (if the value was opposite it wouldn't warn IIUC).
> 
> So it cannot easily be avoided at this moment. It is true that it could be nice to have a way, but at the moment it seems too overkill for it.
