### ISSUE TITLE
[bug] CTEST_CONFIGURATION_TYPE expanded to empty string

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14239]
### Environment details

* Operating System+version: Windows 10 22H2
* Compiler+version: VS 2022
* Conan version: 2.0.7
* Python version: 3.9.13

### Steps to reproduce

Hello,

I am not entirely sure whether it concerns conan or most likely a cmake bug.

I have a conan package that builds a `libcore` but also a `core_tests` executable (latter not packaged), which tests libcore using GoogleTests.

I build both the lib and exe using:  `conan build -verror core/ --conf tools.build:skip_test=False`

To run the tests, I run `ctest --test-dir core\build`

The error I get is:
```powershell
Internal ctest changing into directory: D:/Documents/CAST/core/build
Test project D:/Documents/CAST/core/build
CMake Error at D:/Documents/CAST/core/build/CAST/Fundamental/coreTests/core_tests[1]_include.cmake:1 (include):
  include could not find requested file:

    D:/Documents/CAST/core/build/CAST/Fundamental/coreTests/core_tests[1]_include-.cmake
Call Stack (most recent call first):
  D:/Documents/CAST/core/build/CAST/Fundamental/coreTests/CTestTestfile.cmake:7 (include)
  CTestTestfile.cmake:8 (subdirs)


Errors while running CTest
Output from these tests are in: D:/Documents/CAST/core/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

Here is the content of `core_tests[1]_include.cmake`:
`include("D:/Documents/CAST/core/build/CAST/Fundamental/coreTests/core_tests[1]_include-${CTEST_CONFIGURATION_TYPE}.cmake")`

**We can see that the ${CTEST_CONFIGURATION_TYPE} is not properly expanded, thus leading to the error.**

On Linux, such a thing doesn't happen. I build with the same command: `conan build -verror core/ --conf tools.build:skip_test=False`, but run tests with `ctest --test-dir core\build\Release`. The tests run as expected.

Here is my `layout()`:
```python
def layout(self):
	cmake_layout(self)
	bt = "." if self.settings.os != "Windows" else str(self.settings.build_type)
	self.cpp.source.components["core"].includedirs = ["."]
	self.cpp.build.components["core"].libdirs = [os.path.join(bt, "CAST/Fundamental/core")]
	self.cpp.build.components["core"].bindirs = [os.path.join(bt, "CAST/Fundamental/core")]
```

Note that I use Ninja Multi-Config and Ninja as cmake generators for Windows and Linux, respectively.

**Comment by memsharded** [comment]
Hi @Todiq 

A couple of questions:

- Have you consider adding ``cmake.test()`` to your ``build()`` method, so tests are ran automatically when ``conan build`` or ``conan create``?
- Is it possible that you are missing ``--build-config`` for ``ctest`` invocation? For multi-config CMake generators, in the same way it is mandatory to do ``cmake --build . --config Release``, it might be necessary to specify the ``ctest --build-config``

**Comment by Todiq** [comment]
> * Have you consider adding `cmake.test()` to your `build()` method, so tests are ran automatically when `conan build` or `conan create`?

It is not possible for my use case. The developers do not necessarily want the tests to execute after the end of the build. Under Linux, we exclusively use `conan build` instead of decoupling it with `conan install` and `cmake` in order to keep things easy to remember.

> * Is it possible that you are missing `--build-config` for `ctest` invocation? For multi-config CMake generators, in the same way it is mandatory to do `cmake --build . --config Release`, it might be necessary to specify the `ctest --build-config`

That did the trick, thank you very much. So it was a cmake issue after all! Sorry for the inconvenience.
I still have trouble understanding the notion of single vs multi-config CMake generators.
Have a pleasant day!

**Comment by memsharded** [comment]
> It is not possible for my use case. The developers do not necessarily want the tests to execute after the end of the build. 

That is perfectly fine. You can have ``tools.build:skip_tests=True`` in your ``global.conf`` or on your profiles, that are automatically installed by ``conan config install``, and then the tests will not execute at the end of the build. Then devs can opt-in to run tests with ``-c tools.build:skip_tests=False`` in the command line
