### ISSUE TITLE
[question] Conan 2 equivalent of self.info.shared_library_package_id()

### ISSUE THREAD

**Issue by Marwan-imverse** [conan-io/conan#14248]
### What is your question?

The title says it all actually: what is the equivalent, in Conan 2.X of `self.info.shared_library_package_id()` ? 

Thank you!

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Marwan-imverse 

Thanks for your question.

This functionality is built-in (and improved) in Conan 2.0. The ``info.shared_library_package_id()`` was a workaround in 1.X to try to do what Conan 2.0 does.

I think there is no automatic migration, like an empty function in 2.0, but it would be enough to do:
```python
from conan import conan_version
def package_id(self):
      if conan_version < 2.0:
           self.info.shared_library_package_id()
```

**Comment by Marwan-imverse** [comment]
great, thank you!
