### ISSUE TITLE
[feature] make profile more dynamic

### ISSUE THREAD

**Issue by chimojs** [conan-io/conan#14244]
### What is your suggestion?

Hi!  Is it possible for conan to expand a profile like this
```
include(${dynamic_options})
include(${dynamic_settings})
```
and expand dynamically according to the `dynamic_options` and `dynamic_settings` values at runtime.

I can give a user case.  Suppose I have `n` projects, each have their own options `o1, o2, ..., on`, and `m` platforms `s1,s2,...,sm`. Every projects share their options across platforms, and use same settings on individually platforms. 

Now I have to write `n*m` profiles to build them, but in fact, there are only `n+m` variables. I could write `n+m` profiles
if these values could be composed dynamically.

There are two advantages of this feature:
+ less profiles need to be maintained.
+ if `o1` or `s1` changes, one only need to modify a single file.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @chimojs 

Thanks for your suggestion.

Conan profiles are actually jinja2 templates. That means that you can basically code there in jinja2 syntax whatever you like, define variables, loops, conditionals, string manipulation, importing from other files, etc.

Please have a look to https://docs.conan.io/2/reference/config_files/profiles.html#profile-rendering

**Comment by chimojs** [comment]
This is what i want. Thank you so much!!!

**Comment by memsharded** [comment]
Good, closing the ticket as resolved, then, thanks!
