### ISSUE TITLE
[question] dependency with option

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14240]
### What is your question?

Hi,

I can not set the option for dependency

I would like to have msgpack without boost so use_boost=False
```py
    def requirements(self):
        self.requires("msgpack-cxx/6.0.0")
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by damian-tomczak** [comment]
The answer is:
```py
    def configure(self):
        self.options["msgpack-cxx"].use_boost = False
```

**Comment by memsharded** [comment]
In Conan 2.0 also ``self.requires("msgpack-cxx/version", options={"use_boost": False})``
