### ISSUE TITLE
[question] bug while creating conaninfo?

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14243]
### What is your question?

Hi,

I have cloned conan center:
```
git clone https://github.com/conan-io/conan-center-index
```
I went to:
```
cd conan-center-index/recipes/msgpack-cxx/all
```
I called
```
conan create . --version=6.0.0 -- --build=missing
```
and the package created via it creates with empty conaninfo
![image](https://github.com/conan-io/conan/assets/43729842/2a68e258-669f-447a-b187-3985e96e4f63)

and I think that is the reason why when I'm finally using it it throws error about there is no such file or directory - msgpack.hpp
```
[build][confidential]:8:10: fatal error: msgpack.hpp: No such file or directory
[build]     8 | #include <msgpack.hpp>
[build]       |          ^~~~~~~~~~~~~
```
it is little related to the question I have already asked - I had Release package in the remotes but not Debug and it complained about the lack of includes: https://github.com/conan-io/conan/issues/14071 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @damian-tomczak 

Yes, that package is a ``package_type = "header-library"``. 
In Conan 2.0, header-only library ``conaninfo.txt`` will be empty (because its ``package_id`` is not affected by any settings or options). So this is totally expected.

I think the issue might be somewhere else on the consumer side, if you can share a bit about your CMakeLists.txt (like the ``find_package()`` and more output of the build output before the error happens, that would help.

**Comment by damian-tomczak** [comment]
Ohh, okay
Package:
```py
class MyPackage(ConanFile):
    name = "mypackage"
    version = "1.1.1"
    settings = "os", "compiler", "build_type", "arch"
    exports_sources = "*"
    generators = "CMakeDeps"

    def configure(self):
        self.options["msgpack-cxx"].use_boost = False

    def requirements(self):
        self.requires("msgpack-cxx/6.0.0")
        self.requires("fmt/8.0.1")
        self.requires("boost/1.75.0")
        ...

    def build_requirements(self):
        self.test_requires("gtest/cci.20210126")

    def package_info(self):
        self.cpp_info.components["utils"].libs = ["utils"]
        self.cpp_info.components["utils"].requires = ["msgpack-cxx::msgpack-cxx", "fmt::fmt"]
        self.cpp_info.components["utils"].set_property("cmake_target_name", "utils")

        self.cpp_info.components["base"].libs = ["base"]
        self.cpp_info.components["base"].requires = ["utils", "boost::program_options"]
        self.cpp_info.components["base"].set_property("cmake_target_name", "base")
       ...
```
```cmake
project(utils)

target_link_libraries(${PROJECT_NAME}
    PUBLIC
        msgpackc-cxx
)

```

```cmake
project(base)

target_link_libraries(${PROJECT_NAME} PUBLIC
    utils
)
```
Consumer:
```py
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake

class Consumer(ConanFile):
    name = "consumer"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"

    def requirements(self):
        self.requires("mypackage/1.1.1")

    def build_requirements(self):
        self.test_requires("gtest/cci.20210126")
```
```cmake
find_package(mypackage REQUIRED COMPONENTS
    base
)

project(consumer)

target_link_libraries(${PROJECT_NAME} PUBLIC
    base
)
```

**Comment by damian-tomczak** [comment]
@memsharded

**Comment by damian-tomczak** [comment]
While installing consumer:
```
Skipped binaries
    msgpack-cxx/6.0.0, b2/4.9.6
```
@memsharded

**Comment by damian-tomczak** [comment]
and I also can not find info about msgpack while doing cmake configuration

**Comment by memsharded** [comment]
Couple of quick hints:

- Try to avoid ``self.cpp_info.components["utils"].set_property("cmake_target_name", "utils")``. That creates a ``util`` target that has very high likelihood to conflict with other targes. Remove the line, and try to use the ``mypkg::util`` default target name.
- It seems you are missing ``CMakeToolchain`` in generators, everywhere. It is necessary in order to locate the generated files by ``CMakeDeps``.

**Comment by damian-tomczak** [comment]
@memsharded utils name is a simplification I made to explain you the snippet. The same is with the CMakeToolchain

**Comment by damian-tomczak** [comment]
@memsharded 
Skipped Binaries info is normal for header only packages?

And beside it I think a hint is the lack of msgpack info while cmake configuration

**Comment by memsharded** [comment]
> Skipped Binaries info is normal for header only packages?

Yes! If a header only library is used by a static library o a header only library, by default it is considered an implementation detail, and as such is not propagated to the consumers downstream. 

If the package consuming ``msgpack-cxx`` is including msgpack headers in its public headers, then it must declare it as:
``self.requires("msgpack-cxx", transitive_headers=True)``, as that is not the default (the default is information hiding when possible, a downstream consumer shouldn't be able to do ``#include transitive_dep/header.h"`` for transitive dependencies, but instead declare a explicit ``requires()`` to that dependency if it want to include its headers.

We are lacking some more complete docs for this, you might want to see this presentation. https://www.youtube.com/watch?v=kKGglzm5ous
