### ISSUE TITLE
[feature] add/ edit artifact quality status

### ISSUE THREAD

**Issue by chenx319** [conan-io/conan#14256]
is it possible to add/edit a attribute to show a quality status of a artifact?
Here is a my use case :
1 Today I develop and upload to conan, maker it's " quality status" as " release"  

2 then someone find a bug  and report to me 

3 i need change the " quality status" as " buggy"  or " locked"

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @chenx319 

Thanks for your question.

There are 2 mechanisms that you can use to represent the quality status of a package:

- Use metadata properties. Depending on the server, it is possible to use metadata properties to annotate artifacts. Artifactory has properties, and there is a new extension command in https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art that allows to set properties.
- Use different repositories to represent the status. This is good practice for all package types. You can have your main "release" repository. When there is something that you want to block, you can move that package to a "deprecated" or "locked" repository (so the package is still stored somewhere, but not resolved in dependencies)

**Comment by chenx319** [comment]
@memsharded 
thanks for your quick answer.
 the optioal 1 seems good for me , i will try it
