### ISSUE TITLE
[bug] `self.dependencies` in `validate()` does not show build dependencies

### ISSUE THREAD

**Issue by snakethatlovesstaticlibs** [conan-io/conan#14251]
### Environment details

* Operating System+version: Centos 7
* Compiler+version: gcc 10
* Conan version: 1.60.1
* Python version: 3.9.9

### Steps to reproduce

1. Use this conanfile:
```python3
from conans import ConanFile

class Repro(ConanFile):
    name = "repro"
    generators = ["cmake_find_package"]

    def validate(self):
        # deps = [dep.ref.name for _, dep in self.dependencies.items()]
        # print(deps)
        # assert "m4" in deps
        # assert "m4" in [dep.ref.name for _, dep in self.dependencies.build.items()]
        pass

    def generate(self):
        deps = [dep.ref.name for _, dep in self.dependencies.items()]
        print(deps)
        assert "m4" in deps
        assert "m4" in [dep.ref.name for _, dep in self.dependencies.build.items()]

    def requirements(self):
        self.requires("libcurl/7.86.0")

```

The `generate` step fails, even though `m4` is a build dependency. Same with the `validate` method if we uncomment that block of code

### Logs

```
conan install -r conancenter --build missing conanfile_2.py
Configuration:
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

libcurl/7.86.0: Retrieving from server 'conancenter'
libcurl/7.86.0: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.17k]
Downloading conanfile.py completed [33.00k]
Downloading conan_export.tgz completed [0.30k]
Decompressing conan_export.tgz completed [0.00k]
libcurl/7.86.0: Downloaded recipe revision 4abb30fa63a2e1866d414668954d370b
m4/1.4.19: Retrieving from server 'conancenter'
m4/1.4.19: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.47k]
Downloading conanfile.py completed [4.94k]
Downloading conan_export.tgz completed [0.41k]
Decompressing conan_export.tgz completed [0.00k]
m4/1.4.19: Downloaded recipe revision c1c4b1ee919e34630bb9b50046253d3c
Version ranges solved
    Version range '>=1.1 <4' required by 'libcurl/7.86.0' resolved to 'openssl/3.1.1' in local cache

conanfile_2.py (repro/None): Installing package
Requirements
    libcurl/7.86.0 from 'conancenter' - Downloaded
    openssl/3.1.1 from 'conancenter' - Cache
    zlib/1.2.13 from 'internalrepo' - Cache
Packages
    libcurl/7.86.0:9f21977c8b252beed648659fe77acbeea57b49d8 - Build
    openssl/3.1.1:194a5a97b7fec2da8c9fd30188184a4374243aa2 - Cache
    zlib/1.2.13:4abea69857a62f95f76f0917ecf45464337054db - Cache
Build requirements
    autoconf/2.71 from 'internalrepo' - Cache
    automake/1.16.5 from 'internalrepo' - Cache
    libtool/2.4.7 from 'internalrepo' - Cache
    m4/1.4.19 from 'conancenter' - Downloaded
    pkgconf/1.9.3 from 'internalrepo' - Cache
Build requirements packages
    autoconf/2.71:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    automake/1.16.5:258f6f05ca54813b3d7180161753df7f9ccf7e1d - Cache
    libtool/2.4.7:4266a06194937024d6a39fb0383d6d1796101e26 - Cache
    m4/1.4.19:1a032419479e0fe8660712050df2775c495d3123 - Build
    pkgconf/1.9.3:1a032419479e0fe8660712050df2775c495d3123 - Cache

Installing (downloading, building) binaries...
Downloading conan_sources.tgz completed [3.60k]
Decompressing conan_sources.tgz completed [0.00k]
m4/1.4.19: Configuring sources in /ccache/.conan/data/m4/1.4.19/_/_/source/src


... it builds m4 ...

libcurl/7.86.0 package(): Packaged 12 '.h' files
libcurl/7.86.0 package(): Packaged 1 '.pem' file: cacert.pem
libcurl/7.86.0 package(): Packaged 2 files: curl-config, COPYING
libcurl/7.86.0 package(): Packaged 1 '.a' file: libcurl.a
libcurl/7.86.0: Package '9f21977c8b252beed648659fe77acbeea57b49d8' created
libcurl/7.86.0: Created package revision 9cfc662e41b9c2f2fdfbea7fdf9a3fbb
conanfile_2.py (repro/None): Generator txt created conanbuildinfo.txt
conanfile_2.py (repro/None): Generator cmake_find_package created FindCURL.cmake
conanfile_2.py (repro/None): Generator cmake_find_package created FindOpenSSL.cmake
conanfile_2.py (repro/None): Generator cmake_find_package created FindZLIB.cmake
conanfile_2.py (repro/None): Calling generate()
['libcurl', 'openssl', 'zlib']
ERROR:
	AssertionError:
```

We can see that `m4` was not in the list we were expecting it to be in.

According to the documentation (https://docs.conan.io/1/reference/conanfile/dependencies.html):
> require.build: boolean, True if it is a build_require in the build context, as cmake.

In the libcurl recipe we see: `self.tool_requires("libtool/2.4.7")` which eventually includes `m4`, so I was expecting it to be included in `self.dependencies`. Is this a valid assumption, or is this working as intended?

**Comment by memsharded** [comment]
Hi @snakethatlovesstaticlibs 

Thanks for your question.

It seems this is not a bug, but expected behavior. ``m4`` is a ``tool_requires`` of the dependency, and ``tool_requires`` are private requires that are not propagated to the downstream consumer. Your current package doesn't have a dependency to ``m4`` just because some of your dependencies needs it for build, in the same way that your current package doesn't depend on Meson and CMake and other tools, just because your dependencies need them to build.

So it is totally expected that ``m4`` is not in ``self.dependencies`` of your package recipe, in any of the methods.

I hope this clarifies the issue, but please let us know. Thanks!

**Comment by snakethatlovesstaticlibs** [comment]
Thanks for the quick response @memsharded, I now understand why `m4` is not in `tool_requires`.

The issue I'm trying to solve is glibc incompatibility. The way we currently solve this is by forcing all packages into a channel that's locked to a certain version of glibc. For instance, we have a channel called `ubuntu-18` which contains binary packages which are incompatible with packages in `centos-7`.

As a result of not being able to override `m4` (https://github.com/conan-io/conan/issues/11010) it seems that we will have to build it from source on every platform we support.

Thank you for helping though. Hopefully we will be able to upgrade to conan 2 soon, which I heard might help fix issues like this

**Comment by memsharded** [comment]
> The issue I'm trying to solve is glibc incompatibility. The way we currently solve this is by forcing all packages into a channel that's locked to a certain version of glibc. For instance, we have a channel called ubuntu-18 which contains binary packages which are incompatible with packages in centos-7.

That is not the best way to achieve that, in fact it can be quite problematic and require more effort. I'd strongly suggest not using channels for that.
If you need to control glibc compatibility, please extend the settings: https://docs.conan.io/2/reference/config_files/settings.html#customizing-settings

Using a ``os`` ``Linux`` subsetting, that will give you fine control over that, without needing to modify a single line of any recipe. In Conan 1.X it will be more "demanding" of binaries re-build, but accurate. In Conan 2.0 you have the ``compatibility.py`` plugin in which you can define your custom binary compatibility rules for different glibcs or similar binary settings.

**Comment by snakethatlovesstaticlibs** [comment]
> That is not the best way to achieve that, in fact it can be quite problematic and require more effort.

I think I agree that this is the case, moving packages between channels is not ergonomic, which makes sense since this doesn't appear to be their primary purpose.

Can you please expand on how adding an `os` subsetting for `Linux` will solve this problem? I have tried that, but noticed that it doesn't change the package ID since the recipes I'm using don't use that subsetting. In Conan 1, it seemed like adding the subsetting had no effect on Conan packages.

I've read
* https://docs.conan.io/en/1.60/devtools/running_packages.html#deployment-challenges
* https://docs.conan.io/en/1.60/extending/custom_settings.html

but haven't been able to make the dependencies change their package ID. Maybe I'm doing something wrong?

**Comment by snakethatlovesstaticlibs** [comment]
I must have been somehow mistaken, but it seems to be working now. Thanks for guiding me to this new approach!

**Comment by memsharded** [comment]
Yes, both in Conan 1.X and 2.0, defining the os.glibc=xxx or os.distro=xxx or whatever other subsetting you define in your profiles, will automatically change the package_id, creating new ones specific for that value. I think that will definitely be much better than the channels. Thanks for the feedback!
