### ISSUE TITLE
[question] Conan 2.X options data type error with python_requires_extend

### ISSUE THREAD

**Issue by Marwan-imverse** [conan-io/conan#14259]
### What is your question?

I am currently migrating from conan 1.X to 2.X and am having problems inheriting options with `python_requires_extend`.

I have a base class used for all my recipes:
```python
class PyReq(ConanFile):
    name = "cmtkconan"
    version = "3.0.0"

class CmtkConanBase:
    options = \
        {
            "profiling": [True, False], 
            "generate_doc": [True, False],
            "run_tests": [True, False],
        } 

    default_options =\
        {
            "profiling": False,
            "generate_doc": True,
            "run_tests": True,
        }
```
Then in my packages I have this:
```python
class MyPackage(ConanFile):
    python_requires="cmtkconan/3.0.0"
    python_requires_extend="cmtkconan.CmtkConanBase"
    
    options = \
    {
        "memory_debugging": [True, False],
    }

    default_options = \
    {
        "memory_debugging": False,
    }
```

In conan 1.X options were simple dictionaries and, in the child class, to merge all options I used to do:
```python
def init(self):
        super().init()
        self.options |= super().options
        self.default_options |= super().default_options
```

However, in conan 2, options are now `conans.model.options.Options` with an `update()` method so, theoretically, I should be doing:
```python
def init(self):
        super().init()
        self.options.update(super().options)
```

But that is not working and I only have the child options in the result.

After some investigating, it seems that `super.options()` is treated as a standard dict and not as a `conans.model.options.Options`.

So I added this code in the base class:
```python
def init(self):
        print("In base classe, opptions type=" + str(type(self.options)))
```

And this in the child class:
```python
def init(self):
        print("super options before init " + str(type(super().options)))
        super().init()
        print("super options after init " + str(type(super().options)))
        print("self options " + str(type(self.options)))
```

And this is what I get in the output:
```
super options before init <class 'dict'>
In base class, options type=<class 'conans.model.options.Options'>
super options after init <class 'dict'>
self options <class 'conans.model.options.Options'>
```

Is this behavior expected? If so, what is the best way to add `super().options` to `self.options` in the child class (without having to iterate on all options, ideally)?

Thank you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Marwan-imverse 

Thanks for your question.
In Conan 2.0 there is a explicit ``update()`` methods that seems intended for this:
```python
from conan import ConanFile
class MyBase(object):
    settings = "os", "build_type", "arch"
    options = {"base_option": [True, False]}
    default_options = {"base_option": False}

class BaseConanFile(ConanFile):
    pass
```

And then this seems to work:

```python
from conan import ConanFile
class DerivedConan(ConanFile):
    settings = "os", "build_type", "arch"

    python_requires = "base/1.0"
    python_requires_extend = 'base.MyBase'

    options = {"derived_option": [True, False]}
    default_options = {"derived_option": False}

    def init(self):
        base = self.python_requires['base'].module.MyBase
        self.options.update(base.options, base.default_options)
```

Please see the ``init()`` documentation, I think this example is there: https://docs.conan.io/2/reference/conanfile/methods/init.html. Thanks!

**Comment by Marwan-imverse** [comment]
Works like a charm.
So I should be using `self.python_requires['base'].module.MyBase` instead of `super()`.

I scoured the documentation looking for the `options` keyword, guess I missed it in the `init()` documentation.

Thank you!

**Comment by memsharded** [comment]
> So I should be using self.python_requires['base'].module.MyBase instead of super().

Yeah, calling ``super().init()`` does nothing (base class init() doesn't exist), and using ``super()`` I think it is only valid for methods, not for variables: https://docs.python.org/3/library/functions.html#super

**Comment by Marwan-imverse** [comment]
It was working for conan 1.X so I never looked any further 😓

**Comment by Marwan-imverse** [comment]
Actually, in the documentation you linked to, it is explicitly stated that:
```In addition to method lookups, super() also works for attribute lookups. One possible use case for this is calling descriptors in a parent or sibling class.```

**Comment by memsharded** [comment]
The first definition ``Return a proxy object that delegates method calls to a parent or sibling class of type. This is useful for accessing inherited methods that have been overridden in a class.`` seem to say the opposite, but it is true what you are pointing is quite confusing. Not sure if it could be a defect in the docs, but this clearly don't work:

```python
class Base:
    def __init__(self):
        self.myobjvar = 4
    def mymethod(self):
        print("mymethod")


class Child(Base):
    def do_something(self):
        super().mymethod()
        print(super().myobjvar)

c = Child()
c.do_something()
```
The ``super().myobjvar`` will raise

**Comment by Marwan-imverse** [comment]
OK, thanks for taking the time to investigate this :)

My problem is solved anyway, so thanks a lot for your time and your quick response-time!

**Comment by memsharded** [comment]
Happy to help! 🙂
