### ISSUE TITLE
[question] Cannot find openssl include directories when NATS_BUILD_WITH_TLS is ON

### ISSUE THREAD

**Issue by davidhov** [conan-io/conan#14265]
### What is your question?

I have the following recipe file which you helped to define and it just works fine.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*
"""Module for nats package."""

import os
from conan import ConanFile
from conan.tools.scm import Git
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import collect_libs

required_conan_version = ">=1.59.0"

class NatsConan(ConanFile):
    name = "nats"
    description = "NATS is a simple, secure and high-performance messaging system."
    version = "3.6.1"
    license = "Apache-2.0"
    settings = "os", "compiler", "build_type", "arch"
    
    options = {
        "shared"                 : [True, False],
        "nats_build_streaming"   : [True, False],

        "windows_sdk"            : "ANY",
        "full_compiler_version"  : "ANY"
    }

    default_options = {
        "shared"                 : False,
        "nats_build_streaming"   : False,

        "windows_sdk"            : "10.0",
        "full_compiler_version"  : ""
    }

    short_paths = True

    def config_options(self):
        if self.settings.os != "Windows":
            del self.options.windows_sdk

    def layout(self):
        cmake_layout(self)

    def generate(self):
        cmake = CMakeDeps(self)
        cmake.generate()
        tc = CMakeToolchain(self)
        tc.variables["NATS_BUILD_STREAMING"] = self.options.nats_build_streaming
        tc.variables["NATS_BUILD_WITH_TLS"] = False
        tc.variables["NATS_BUILD_EXAMPLES"] = False
        tc.variables["BUILD_TESTING"] = False
        if self.options.shared:
            tc.variables["NATS_BUILD_LIB_STATIC"] = False
            tc.variables["NATS_BUILD_LIB_SHARED"] = True
        else:
            tc.variables["NATS_BUILD_LIB_STATIC"] = True
            tc.variables["NATS_BUILD_LIB_SHARED"] = False

        tc.generate()

    def source(self):
        git = Git(self)
        git.clone(url = "ssh://git@bitbucket/lib/nats.git", target = ".")
        git.checkout("v" + self.version)

    def requirements(self):
        self.requires("openssl/3.1.1_0@jenkins/stable")
        if self.options.nats_build_streaming:
            self.requires("protobuf/3.18.0_13@jenkins/stable")

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        if self.options.shared:
            self.cpp_info.libs = ["nats"]
            self.cpp_info.bindirs = ["lib"]
        else:
            self.cpp_info.libs = collect_libs(self)
```

The issue arises when I am changing `tc.variables["NATS_BUILD_WITH_TLS"] = False` to `tc.variables["NATS_BUILD_WITH_TLS"] = True`. I really need to set it to `True` for security reasons.
The error I am getting when using custom profile (by running `conan create . "davithov/test" -pr <some_profile> --build=missing`) is the following:

 ```
 parser.c
C:\.conan\b84332\1\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory (compiling source file C:\.conan\b84332\1\src\hash.c) [C:\.co
nan\b84332\1\build\src\nats_static.vcxproj]
C:\.conan\b84332\1\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory (compiling source file C:\.conan\b84332\1\src\msg.c) [C:\.con
an\b84332\1\build\src\nats_static.vcxproj]
  pub.c
C:\.conan\b84332\1\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory (compiling source file C:\.conan\b84332\1\src\asynccb.c) [C:\
.conan\b84332\1\build\src\nats_static.vcxproj]
C:\.conan\b84332\1\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory (compiling source file C:\.conan\b84332\1\src\kv.c) [C:\.cona
n\b84332\1\build\src\nats_static.vcxproj]
C:\.conan\b84332\1\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory (compiling source file C:\.conan\b84332\1\src\js.c) [C:\.cona
n\b84332\1\build\src\nats_static.vcxproj]
C:\.conan\b84332\1\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory (compiling source file C:\.conan\b84332\1\src\jsm.c) [C:\.con
an\b84332\1\build\src\nats_static.vcxproj]
//...
```
I tried to look into CMakeLists.txt files of NATS library (https://github.com/nats-io/nats.c/blob/main/CMakeLists.txt), but couldn't understand the reason of failure.
Also I looked into natsp.h file (https://github.com/nats-io/nats.c/blob/main/src/natsp.h#L24) from where the error comes and the line above it requires `NATS_HAS_TLS` flag to be defined and it is, indeed, defined here (https://github.com/nats-io/nats.c/blob/main/CMakeLists.txt#L225). So, I don't understand the issue.
Can you please help with this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @davidhov 

Could you please share the full output, everything that is printed before that error?

The problem seems to be that nats library is using legacy CMake, instead of using targets is using its own variables:
```cmake
if(NATS_BUILD_WITH_TLS)
  include_directories(${OPENSSL_INCLUDE_DIR})
  set(NATS_OPENSSL_LIBS "${OPENSSL_LIBRARIES}")
endif(NATS_BUILD_WITH_TLS)

# --------------------------------------
# Create the shared and static libraries
# --------------------------------------
if(NATS_BUILD_LIB_SHARED)
  add_library(nats SHARED ${SOURCES} ${PS_SOURCES} ${S_SOURCES})
  target_link_libraries(nats ${NATS_OPENSSL_LIBS} ${NATS_EXTRA_LIB} ${NATS_PROTOBUF_LIBRARIES} ${NATS_SODIUM_LIBRARIES})
endif(NATS_BUILD_LIB_SHARED)
```

So mostly the 
```
include_directories(${OPENSSL_INCLUDE_DIR})
set(NATS_OPENSSL_LIBS "${OPENSSL_LIBRARIES}")
```
which relies on global variables instead of targets.

Even if not recommended, for these cases, Conan defines some auxiliary variables:
```cmake
set(OpenSSL_INCLUDE_DIRS... )
set(OpenSSL_INCLUDE_DIR ... )
set(OpenSSL_LIBRARIES ... )
```
Maybe it is the casing and patching the nats CMakeLists.txt would be the recommended way (many recipes in ConanCenter do this)

**Comment by davidhov** [comment]
Thank you for the quick response!
Here is the output before the error:
```

[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
Exporting package recipe
nats/3.6.1@davithov/test: A new conanfile.py version was exported
nats/3.6.1@davithov/test: Folder: C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\export
nats/3.6.1@davithov/test: Exported revision: 56560530f33662eb755f9f0c0ed32dd0
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=20
compiler.runtime=MT
compiler.toolset=v143
compiler.version=17
os=Windows
os_build=Windows
[options]
*:full_compiler_version=17.11.21
*:win32_winnt=0x0603
*:windows_sdk=10.0.20348.0
*:windows_version=Windows8
[build_requires]
[env]

nats/3.6.1@davithov/test (test package): Installing package
Requirements
    nats/3.6.1@davithov/test from local cache - Cache
    openssl/3.1.1_0@jenkins/stable from 'artifactory' - Cache
Packages
    nats/3.6.1@davithov/test:c5771f073100aa8fe7f9f55943e10444dc85dae9 - Build
    openssl/3.1.1_0@jenkins/stable:c60cc351867edca95ed45465873196d33934d228 - Cache

Installing (downloading, building) binaries...
openssl/3.1.1_0@jenkins/stable: Already installed!
nats/3.6.1@davithov/test: Configuring sources in C:\.conan\a8c8bd\1\.
nats/3.6.1@davithov/test: Cloning git repo
nats/3.6.1@davithov/test: Checkout: v3.6.1
nats/3.6.1@davithov/test: Copying sources to build folder
nats/3.6.1@davithov/test: Building your package in C:\.conan\b84332\1
nats/3.6.1@davithov/test: Generator txt created conanbuildinfo.txt
nats/3.6.1@davithov/test: Calling generate()
nats/3.6.1@davithov/test: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
nats/3.6.1@davithov/test: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
nats/3.6.1@davithov/test: Preset 'default' added to CMakePresets.json. Invoke it manually using 'cmake --preset default'
nats/3.6.1@davithov/test: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:\.conan\b84332\1\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
nats/3.6.1@davithov/test: Aggregating env generators
nats/3.6.1@davithov/test: Calling build()
nats/3.6.1@davithov/test: CMake command: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/.conan/b84332/1/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/.conan/d6e9bb/1" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\.conan\b84332\1\."
-- Using Conan toolchain: C:/.conan/b84332/1/build/generators/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 20 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.35.32217.1
-- The CXX compiler identification is MSVC 19.35.32217.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'openssl::openssl'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/.conan/b84332/1/build
nats/3.6.1@davithov/test: CMake command: cmake --build "C:\.conan\b84332\1\build" --config Release
MSBuild version 17.5.1+f6fdcf537 for .NET Framework

  Checking Build System
  Building Custom Rule C:/.conan/b84332/1/src/CMakeLists.txt
  asynccb.c
  buf.c
  comsock.c
  conn.c
  crypto.c
  hash.c
  js.c
  jsm.c
  kv.c
  msg.c
  nats.c
  natstime.c
  nkeys.c
  nuid.c
  opts.c
  parser.c
  //... ERROR COMES HERE
```

**Comment by memsharded** [comment]
Ok, good, I was looking for things like ``Conan: Target declared 'openssl::openssl'``, which means that the generated file was found and the openssl target is there.

I think a patch to fix the nats ``src/CMakeLists.txt`` lines:
```cmake
include_directories(${OPENSSL_INCLUDE_DIR})
set(NATS_OPENSSL_LIBS "${OPENSSL_LIBRARIES}")
```
Is the way to go, I'd try with:
```cmake
include_directories(${OpenSSL_INCLUDE_DIR})
set(NATS_OPENSSL_LIBS "${OpenSSL_LIBRARIES}")
```

**Comment by davidhov** [comment]
I did the following steps:

1. created "patch" folder
2. created cmakelists.patch file inside it and added above 2 lines there
3. added `export_sources = "patches/*"` inside recipe file
4. added  `files.patch(self, patch_file = "patches/cmakelists.patch", base_path = self.src_base_path)` under `source()`, after `git.checkout(...)`. 

As I am getting an error, I guess I missed, something, correct?
Here is the link of my changes (https://github.com/davidhov/test_nats_patches)
I guess I did stupid things...

**Comment by memsharded** [comment]
It seems that the exported patches are in the folder, so you can't clone directly there. Can be fixed with:

```python
    def layout(self):
        cmake_layout(self, src_folder="src")  # <- Note the src_folder here

    def source(self):
        git = Git(self)
        # NOTE the ``target = "src"``
        git.clone(url = "ssh://git@bitbucket/lib/nats.git", target = "src")
```

But I cannot access that bitbucket server, so I can't pass that point.

**Comment by davidhov** [comment]
I have changed the sources to `GitHub` version ( https://github.com/davidhov/test_nats_patches/blob/main/conanfile.py#L66 ).
Also, I have provided proper .patch file (before it didn't contain patch diff)
Now, when running, I am getting strange error:

```
nats/3.6.1@davithov/test: Checkout: v3.6.1
ERROR: nats/3.6.1@davithov/test: Error in source() method, line 67
        git.checkout("v3.6.1")
        CalledProcessErrorWithStderr: Command 'git checkout v3.6.1' returned non-zero exit status 128.
fatal: not a git repository (or any of the parent directories): .git
```

I have an impression that I am missing something: maybe I should add `replace_in_file` ?

**Comment by memsharded** [comment]
Because the checkout needs to move to the cloned ``src`` folder, as you would do in command line, please check https://docs.conan.io/2/reference/tools/scm/git.html#git

**Comment by davidhov** [comment]
Sorry, for disturbing you time and time again. I changed according to the link above and pushed the changes (https://github.com/davidhov/test_nats_patches/blob/main/conanfile.py#L66)

Now, getting the error:

```
nats/3.6.1@davithov/test: WARN: patches/cmakelists.patch: error: no patch data found!
ERROR: nats/3.6.1@davithov/test: Error in source() method, line 70
        files.patch(self, patch_file = "patches/cmakelists.patch", base_path = "src")
        ConanException: Failed to parse patch: patches/cmakelists.patch
```

I thought probably it should have been `base_path = "."` instead of the `base_path = "src"`, but neither of these work for me.
Also, I used `WinMerge` tool to create a .patch file. And it looks like this:

```
8,9c8,9
<   include_directories(${OPENSSL_INCLUDE_DIR})
<   set(NATS_OPENSSL_LIBS "${OPENSSL_LIBRARIES}")
---
>   include_directories(${OpenSSL_INCLUDE_DIR})
>   set(NATS_OPENSSL_LIBS "${OpenSSL_LIBRARIES}")
```

I also don't understand why we specified "src" as a target directory. Is it because all sources are there? I thought that "target" means - "where we want to clone the repository, i.e., nats" and not where the sources are located.

**Comment by memsharded** [comment]
Yes, the WinMerge output is not standard patch format. If you use ``git diff ... > mypatch``, I think that has the correct format.

> I also don't understand why we specified "src" as a target directory. Is it because all sources are there? I thought that "target" means - "where we want to clone the repository, i.e., nats" and not where the sources are located.

The ``git.clone()`` target is nothing but ``git clone url target``. That is, the folder name that is used as target of the clone, that doesn't necessarily match the original repo name. You can perfectly use ``nats`` as the target folder, I was just using ``src`` because it is the common convention in ConanCenter recipes.

**Comment by davidhov** [comment]
Will you please help again? Sorry...
I know that I am asking too much questions.
I created a patch file as you suggested: via `git diff` and pushed (https://github.com/davidhov/test_nats_patches/blob/main/patches/nats-src-cmakelists-openssl.patch). 
Also I have changed recipe file there accordingly (hopefully everything is fine there).
But I am still getting an error (this time coming from the patch file)

`nats/3.6.1@davithov/test: Checkout: v3.6.1
nats/3.6.1@davithov/test: WARN: patches/nats-src-cmakelists-openssl.patch: file 1/1:     b'CMakeLists.txt'
nats/3.6.1@davithov/test: WARN: patches/nats-src-cmakelists-openssl.patch:  hunk no.1 doesn't match source file at line 5
nats/3.6.1@davithov/test: WARN: patches/nats-src-cmakelists-openssl.patch:   expected: b'include_directories(${NATS_PLATFORM_INCLUDE})'
nats/3.6.1@davithov/test: WARN: patches/nats-src-cmakelists-openssl.patch:   actual  : b'include(FindPackageHandleStandardArgs)'
nats/3.6.1@davithov/test: patches/nats-src-cmakelists-openssl.patch: source file is different - b'CMakeLists.txt'
ERROR: nats/3.6.1@davithov/test: Error in source() method, line 69
        files.patch(self, patch_file = "patches/nats-src-cmakelists-openssl.patch", base_path = self.source_dir)
        ConanException: Failed to apply patch: patches/nats-src-cmakelists-openssl.patch`
     
Something is wrong with the patching process I guess, but what exactly...

**Comment by davidhov** [comment]
> Will you please help again? Sorry... I know that I am asking too much questions. I created a patch file as you suggested: via `git diff` and pushed (https://github.com/davidhov/test_nats_patches/blob/main/patches/nats-src-cmakelists-openssl.patch). Also I have changed recipe file there accordingly (hopefully everything is fine there). But I am still getting an error (this time coming from the patch file)
> 
> `nats/3.6.1@davithov/test: Checkout: v3.6.1 nats/3.6.1@davithov/test: WARN: patches/nats-src-cmakelists-openssl.patch: file 1/1: b'CMakeLists.txt' nats/3.6.1@davithov/test: WARN: patches/nats-src-cmakelists-openssl.patch: hunk no.1 doesn't match source file at line 5 nats/3.6.1@davithov/test: WARN: patches/nats-src-cmakelists-openssl.patch: expected: b'include_directories(${NATS_PLATFORM_INCLUDE})' nats/3.6.1@davithov/test: WARN: patches/nats-src-cmakelists-openssl.patch: actual : b'include(FindPackageHandleStandardArgs)' nats/3.6.1@davithov/test: patches/nats-src-cmakelists-openssl.patch: source file is different - b'CMakeLists.txt' ERROR: nats/3.6.1@davithov/test: Error in source() method, line 69 files.patch(self, patch_file = "patches/nats-src-cmakelists-openssl.patch", base_path = self.source_dir) ConanException: Failed to apply patch: patches/nats-src-cmakelists-openssl.patch`
> 
> Something is wrong with the patching process I guess, but what exactly...

Figured out the issue - I used wrong path for `base_path` and it tried to patch with different CMakeLists.txt. 
Althought, I still have other errors...

**Comment by davidhov** [comment]
Thank you very much for the help!
Although I still have issues, but those are not connected to the current question, so closing the question.

**Comment by memsharded** [comment]
> Will you please help again? Sorry...
I know that I am asking too much questions.

No problem, we love to help 🙂 

Some quick questions: it seems that you are starting with Conan at this moment? Why aren't you using Conan 2.0?

This is what I did to make your repo working:
```diff
diff --git a/conanfile.py b/conanfile.py
index a9f2404..af09dce 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -35,15 +35,12 @@ class NatsConan(ConanFile):
         "full_compiler_version"  : ""
     }

-    source_dir = "src"
-    short_paths = True
-
     def config_options(self):
         if self.settings.os != "Windows":
             del self.options.windows_sdk

     def layout(self):
-        cmake_layout(self, src_folder = self.source_dir)
+        cmake_layout(self, src_folder="src")

     def generate(self):
         cmake = CMakeDeps(self)
@@ -63,13 +60,13 @@ class NatsConan(ConanFile):
         tc.generate()

     def source(self):
-        git = Git(self, self.source_dir)
+        git = Git(self)
         git.clone(url = "https://github.com/nats-io/nats.c.git", target = ".")
         git.checkout("v3.6.1")
-        files.patch(self, patch_file = "patches/nats-src-cmakelists-openssl.patch", base_path = self.source_dir)
+        files.patch(self, patch_file = "patches/nats-src-cmakelists-openssl.patch")

     def requirements(self):
-        self.requires("openssl/3.1.1_0@jenkins/stable")
+        self.requires("openssl/3.1.1")
         if self.options.nats_build_streaming:
             self.requires("protobuf/3.18.0_13@jenkins/stable")

diff --git a/patches/nats-src-cmakelists-openssl.patch b/patches/nats-src-cmakelists-openssl.patch
index 89dfc65..d6a8621 100644
--- a/patches/nats-src-cmakelists-openssl.patch
+++ b/patches/nats-src-cmakelists-openssl.patch
@@ -1,7 +1,7 @@
-diff --git a/CMakeLists.txt b/CMakeLists.txt
+diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
 index a1351d8..7ac1ec6 100644
---- a/CMakeLists.txt
-+++ b/CMakeLists.txt
+--- a/src/CMakeLists.txt
++++ b/src/CMakeLists.txt
```

In summary:
- simplify the layouts. You were applying ``src`` 2 times.
- Fix the patch, so it targets the right ``src/CMakeLists.txt``
- I also removed the ``short_paths``, it doesn't seem necessary so far
With this, the ``conan create`` worked.

**Comment by davidhov** [comment]
I have ready only Conan 2.0 documentation a bit and trying to apply Conan 2.0 functionality where I can. When facing issues I am trying also to view at other packages which currently exist in my company, so unconsciously copying < conan 2.0 things.
The latter version didn't work for me, because it, again, couldn't find `openssl/ssl.h` header, so I thought maybe patches were not applied and removed `openssl` from cache. Now regenerating...

**Comment by davidhov** [comment]
I can see that a patch file has been applied successfully here
```
C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src

//...
if(NATS_BUILD_WITH_TLS)
  include_directories(${OpenSSL_INCLUDE_DIR})
  set(NATS_OPENSSL_LIBS "${OpenSSL_LIBRARIES}")
endif(NATS_BUILD_WITH_TLS)
//...
```

but during building test project:

still the same issue:

```
nats/3.6.1@davithov/test: CMake command: cmake --build "C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build" --config Release
MSBuild version 17.5.1+f6fdcf537 for .NET Framework

  Checking Build System
  Building Custom Rule C:/Users/<workstation>/.conan/data/nats/3.6.1/davithov/test/build/c5771f073100aa8fe7f9f55943e10444dc85dae9/src/src/CMakeLists.txt
  asynccb.c
  buf.c
  comsock.c
  conn.c
  crypto.c
  hash.c
  js.c
  jsm.c
  kv.c
  msg.c
  nats.c
  natstime.c
  nkeys.c
  nuid.c
  opts.c
  parser.c
C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h':
 No such file or directory (compiling source file C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\asynccb.c) [C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build\src\nats_static.vcxproj]
  pub.c
C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h':
 No such file or directory (compiling source file C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\comsock.c) [C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build\src\nats_static.vcxproj]
C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\natsp.h(24,10): fatal  error C1083: Cannot open include file: 'openssl/ssl.h':
 No such file or directory (compiling source file C:\Users\<workstation>\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\conn.c) [C:\Users\<workstation>\
.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build\src\nats_static.vcxproj]
  srvpool.c
```
