### ISSUE TITLE
[bug] 1.60.1 conan install --output-folder does not place generated files in the selected folder

### ISSUE THREAD

**Issue by ridler77** [conan-io/conan#14269]
### Environment details

* Operating System+version:  Ubuntu 20 and Win 10
* Compiler+version: gcc 9 and VS2019
* Conan version: 1.60.1
* Python version: 3.8.10 and 3.10.5

### Steps to reproduce

conanfile.txt
[requires]
zlib/1.2.13
[generators]
CMakeDeps
CMakeToolchain

`conan install . --output-folder=build`

### Logs

The expected output is to have ZLIBConfig.cmake and conan_toolchain.cmake files created inside the build folder.
Instead, the build folder is empty and all the files are created in the current directory.

**Comment by memsharded** [comment]
Hi @ridler77 

Thanks for your question.

In Conan 1.X, the new generators like ``CMakeDeps`` will follow the ``--output-folder`` argument if the layout is defined. You need to add:
```
[layout]
cmake_layout
```
Please check https://docs.conan.io/1/reference/conanfile_txt.html#layout

**Comment by ridler77** [comment]
Thanks!  I got my build working using CMakeDeps CMakeToolchain and cmake_layout.

**Comment by memsharded** [comment]
Excellent, happy to hear that!
Thanks for the feedback and following up.
