### ISSUE TITLE
[bug] Conan 1.x: Using `conan install` with a lockfile does not detect changes in `conanfile.py`

### ISSUE THREAD

**Issue by snakethatlovesstaticlibs** [conan-io/conan#14268]
### Environment details

* Operating System+version: Ubuntu 18.04
* Compiler+version: gcc 10
* Conan version: Conan 1.60.1
* Python version: 3.9.9

### Steps to reproduce

1. Use this `conanfile.py`

```python3
from conans import ConanFile

class Repro(ConanFile):
    name = "repro"
    generators = ["cmake_find_package"]

    def requirements(self):
        self.requires("libcurl/7.86.0")
```
2. `conan lock create conanfile.py --lockfile-out conan.lock -r conancenter`
3. `conan install repro.py --build missing  -r conancenter` (installation succeeds as expected)
4. Change the lockfile to be
```
from conans import ConanFile

class Repro(ConanFile):
    name = "repro"
    generators = ["cmake_find_package"]

    def requirements(self):
        self.requires("libcurl/8.1.2")
```
5. `conan install conanfile.py --lockfile=conan.lock  -r conancenter`
6. The installation succeeds, even though we expect it to fail because [according to the docs](https://docs.conan.io/1/reference/commands/consumer/install.html):

> # lockfiles
> --lockfile=<path-to-lockfile>: The conan install ... --lockfile=path/to/file.lock command will provide an input lockfile to the command. Versions, revisions, and other data contained in that lockfile will be respected. If something has changed locally that diverges with respect the locked information in the lockfile, the command will fail.

This leads me to believe that updating the `conanfile.py` without updating the lockfile should result in an error at install time

### Logs

```
$ conan lock create repro.py --lockfile-out conan.lock -r conancenter
Version ranges solved
    Version range '>=1.1 <4' required by 'libcurl/7.86.0' resolved to 'openssl/3.1.1' in local cache

Requirements
    libcurl/7.86.0 from 'ourrepo' - Cache
    openssl/3.1.1 from 'conancenter' - Cache
    zlib/1.2.13 from 'ourrepo' - Cache
Packages
    libcurl/7.86.0:e582828ece0435ac35978baec377ce8361febdf2 - Cache
    openssl/3.1.1:bbce4e634086a7d39cc9c60315cf7527e02bdace - Cache
    zlib/1.2.13:9ee3f5c455630963c64b9eef7c7b37619fedbd75 - Cache

Generated lockfile: /home/xxx/repro/conan.lock
```

(after updating the lockfile)
```
$ conan install repro.py --lockfile=conan.lock
Using lockfile: '/home/xxx/repro/conan.lock'
Configuration:
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

repro.py (repro/None): Installing package
Requirements
    libcurl/7.86.0 from 'ourrepo' - Cache
    openssl/3.1.1 from 'conancenter' - Cache
    zlib/1.2.13 from 'ourrepo' - Cache
Packages
    libcurl/7.86.0:e582828ece0435ac35978baec377ce8361febdf2 - Cache
    openssl/3.1.1:bbce4e634086a7d39cc9c60315cf7527e02bdace - Cache
    zlib/1.2.13:9ee3f5c455630963c64b9eef7c7b37619fedbd75 - Cache

Installing (downloading, building) binaries...
zlib/1.2.13: Already installed!
openssl/3.1.1: Already installed!
libcurl/7.86.0: Already installed!
repro.py (repro/None): Generator cmake_find_package created FindCURL.cmake
repro.py (repro/None): Generator cmake_find_package created FindOpenSSL.cmake
repro.py (repro/None): Generator cmake_find_package created FindZLIB.cmake
repro.py (repro/None): Generator txt created conanbuildinfo.txt
repro.py (repro/None): Aggregating env generators
repro.py (repro/None): Generated conaninfo.txt
repro.py (repro/None): Generated graphinfo
```

**Comment by memsharded** [comment]
Hi @snakethatlovesstaticlibs 

Thanks for your report. It seems that changes in the current consumer conanfile are not raising errors. I can see the lockfile is still working and the previous version is the one that is resolved as dependency, but it is not raising an error.

This issue has been solved in 2.0. I can verify that the flow above results in:
```
======== Computing dependency graph ========
ERROR: Requirement 'libcurl/8.1.2' not in lockfile
```

Lockfiles in 1.X are complicated and fragile, and any changes in it are quite risky, so I am afraid this will not get fixed for 1.X, and the recommended solution is to update to Conan 2.0 (I see that you are still using legacy 1.X, I'd recommend to start using the new ``from conan`` (not from ``conans``) imports, and the new generators, like CMakeDeps instead of ``cmake_find_package`` as soon as possible. Please check https://docs.conan.io/1/conan_v2.html

**Comment by snakethatlovesstaticlibs** [comment]
Thank you for the reply, I've made the relevant changes and will hopefully be able to work around this issue until we migrate to conan 2!

**Comment by memsharded** [comment]
Thanks for the feedback!

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
