### ISSUE TITLE
[question] Downloading dependencies to specific folder

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#14262]
### What is your question?

Dear Conan Folks,

We have a use-case that we get a tool that needs dependencies to be copied to a specific folder before build . 
Is it possible to download dependncies to a specific folder?
Workflow is like this:
1. Component A, B build itself, generates obj files 
2. Tool X/1.0.0 is packaged , tool X is an exe.
3. Project consumes both component A, B and before build expects Tool X to generate code. Project expects Tool X to be downloaded to a specific folder. Project indicates Tool X as a dependency.  
Is it possible to achieve this?

Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

> Project consumes both component A, B and before build expects Tool X to generate code. Project expects Tool X to be downloaded to a specific folder.

What do you mean here? Like tool X need to be in a system folder, like /usr/bin or something like that? 
That sounds very bad, and in general I'd say that the project should be fixed to allow running tool X from the PATH or any arbitrary location with a full path to the exe. If you can elaborate a bit more about that requirement, that would be useful.

**Comment by maitrey** [comment]
Sorry James. I will try again. Tool X needs to be in a conf folder in the project context (meaning where it is consumed). And not in the cache because there are relative path references inside the project. Is it better to expose Tool X as:
```
self.build_env_info.TOOLX = os.path.join(self.package_folder)
```
Or is there a better way to do it?

**Comment by memsharded** [comment]
If ``toolx`` executable needs to be inside the consumer project, then the recommended approach is to copy it with ``generate()`` method and calling ``copy()``


Note: ``self.build_env_info.TOOLX = os.path.join(self.package_folder)`` is not correct syntax anyway. It should be more like ``self.buildenv_info.define_path("TOOLX", self.package_folder)``, but this won't add much, still the consumer needs to copy the .exe, and that is better done in the ``generate()`` method of the consumer.

**Comment by maitrey** [comment]
Do you mean to say I need to copy in the generate method and thats the only way?
I seem to use in some other utility tool like this:
```
def package_info(self):
        self.buildenv_info.define_path("STATICCODE_SERVICE", os.path.join(self.package_folder))
```
And this seems to work fine. Is this a wrong way of using it?

**Comment by memsharded** [comment]
But you told me that you have to have that executable in the project folder. If you need the executable in the consumer project folder, the only way is to copy it, defining environment-variables will not make it. This is not a Conan limitation, I understood this is a limitation of the project. If the executable doesn't need to be copied to the consumer project, and it needs an environment-variable to be defined pointing to its location, then sure, a ``buildenv_info.define_path()`` can do it.

**Comment by maitrey** [comment]
Yes I understood that the only way if tools are expected in a folder structure is to use the copy method. I misunderstood that it was forbidden to use: 
```
self.buildenv_info.define_path("STATICCODE_SERVICE", os.path.join(self.package_folder))
```
This I use for another tool that runs static code analysis and I understood that it is allowed.
Thanks James. I understand how to use in both the use-cases . Ticket can be closed, many thanks!

**Comment by memsharded** [comment]
Yes, ``self.buildenv_info.define_path("STATICCODE_SERVICE", os.path.join(self.package_folder))`` is not forbidden, it creates in the consumer a env-var poiting to a specific folder. But that doesn't seem enough for your other use case, in which really the executable needs to be copied. Thanks for the feedback!
