### ISSUE TITLE
[feature] CMakeToolChain should add environment section to CMakePresets.json

### ISSUE THREAD

**Issue by sharpepd** [conan-io/conan#14271]
### What is your suggestion?

Hi! I would like for Conan to be able to insert the environment variables defined in env_info and the env section of a profile into the CMakePresets.json so that CMake uses these environment variables when building.

According to https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html an environment section can be added to the config preset.

In my case, I need an environment variable setting to access the license for the compiler, which I am adding as a Conan package with a toolchain file. I am setting the required env var in the profile to include the required compiler, but the license is not found. When I added manually to the generated CMakePresets.json, then the license was found indicating that CMake had used it.

I would like this to happen automatically. I would rather not use the virtualenv generator, as it adds an extra step for my developers to remember - whereas this approach is working well with the modern approach you have defined for working with Conan and Cmake (and using VSCode's CMake plugin).

Note that I am currently using Conan 1.59.0 (and attempting to define recipes that are conan 2.x ready)

Attached:
[profile.txt](https://github.com/conan-io/conan/files/12012574/profile.txt) - The profile with a env_var defined
[CMakePresets.json.txt](https://github.com/conan-io/conan/files/12012582/CMakePresets.json.txt) - Modified CMakePresets.json file with the additional environment section I would like to see added.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sharpepd 


This is something that we have been wanting to explore for some time. I think there are other related tickets, but I couldn't find them at this moment, so I am leaving this one as the reference one for this idea.

Some ideas:
- A presets-only solution might not be enough, as we need something that works for users with older versions of CMake. 
- Is it possible to define it with toolchain only? To investigate and revisit.
- This should probably be opt-in, there is risk of breaking existing users

I am assigning this to the 2.X roadmap (this kind of new feature will no longer happen in Conan 1.X), this means it is important and it will be explored, but not immediately, as there are other higher priorities at this moment. Thanks for the feedback!

**Comment by memsharded** [comment]
Of course, if someone is willing to start this effort, first investigating the possible implementation options (toolchain-only if possible), that would be really appreciated, and help moving it forward earlier.

**Comment by sharpepd** [comment]
An idea for at least an initial low risk approach could be to provide an interface for the CmakeToolChain class to provide environment variables like it is currently done for Cache Variables. This way the user can set-up the environment variables they want and hopefully also use the dependencies interface to set-up environment variables defined in the env_info id the dependencies. A function then to automatically bind all of the env vars of dependencies can be added later?

My experiments so far in using the toolchain file to provide environment variables seem to indicate it is not possible, at least not with set (ENV{}) syntax, as the environment is not available to the runtime of cmake (only configuration).

**Comment by memsharded** [comment]
> An idea for at least an initial low risk approach could be to provide an interface for the CmakeToolChain class to provide environment variables like it is currently done for Cache Variables. This way the user can set-up the environment variables they want and hopefully also use the dependencies interface to set-up environment variables defined in the env_info id the dependencies. A function then to automatically bind all of the env vars of dependencies can be added later?

I think that part would be relatively easy, but still the default should be a conf opt-in that does it automatically without needing to modify the recipes.

> My experiments so far in using the toolchain file to provide environment variables seem to indicate it is not possible, at least not with set (ENV{}) syntax, as the environment is not available to the runtime of cmake (only configuration).

I see, yes, it seems impossible to do this via toolchain. I'll discuss with the team the presets-only approach

**Comment by thorntonryan** [comment]
Connecting more breadcrumbs, but a similar idea was expressed in:
https://github.com/conan-io/conan/issues/10515#issuecomment-1030063826

**Comment by memsharded** [comment]
This one is also related: https://github.com/conan-io/conan/issues/15012

Actually I think this would be the same. As https://github.com/conan-io/conan/issues/15012 is assigned to give it a try for next 2.0.15, I suggest to track it.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/15192 has added ``environment`` to CMakePresets, it will be released in 2.0.15, feedback welcome
