### ISSUE TITLE
[question] How to upload recipe & packages to another remote

### ISSUE THREAD

**Issue by sweinst** [conan-io/conan#14279]
### What is your question?

Hi,

I'm building a project using the "conancenter" remote for getting the sources and building the third-party libraries 
Once done, I want to upload the binaries to my own artifactory server. I want other users to avoid the building of these libraries (especially boost)
For example for ceres-solver, I run the command:
```bash
 conan upload ceres-solver/2.1.0@ -r my_remote -c --all
```
But when another user tries to use "my_remote", he can't find any packages

What is the correct way of doing that?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @sweinst thanks a lot for your question.

The process you describe seems to be the correct one, and for enterprise users of Conan that want to sue ConanCenter recipes is in fact the recommended approach. As to why other people can't find your binaries, my guess here is that it seems like you're the one building the binaries in your machine, so only those matching your current profile will be created, and thus anyone with a different configuration won't be able to use those.

It's usually the case that you need a CI system to build a for every configuration you care about. For example, in ConanCenter if you run (Conan v1 syntax as you showed, let me know if you need its v2 counterpart which ends up looking easier to read, specially its output) `conan search "ceres-solver/2.1.0@" -r=conancenter`, you'll be able to see all the binaries of different configurations that it has built.

So the way forward for this case would be to plan which configurations you'll need to generate for your users, and make those available :)

Let me know if this solves your question, but feel free to ask any other questions, happy to help :)

**Comment by memsharded** [comment]
I'd like to add a couple of recommendations:

> I'm building a project using the "conancenter" remote for getting the sources and building the third-party libraries
Once done, I want to upload the binaries to my own artifactory server.

When building packages from ConanCenter, it is recommended to build them from a fork of the ``conan-center-index`` github repo. The effort is practically the same, but the level of control, robustness and customization capabilities is much much higher. Please consider it, and let us know if you have any questions.

> conan upload ceres-solver/2.1.0@ -r my_remote -c --all

I am thinking that this might be about transitive packages of ``ceres-solver`` not being uploaded? What is the exact errors that you are getting. In case you want to upload all things that were part of a dependency graph, you might be interested in the latest "packages-lists" feature: https://blog.conan.io/2023/06/28/Conan-bulk-package-operations.html

**Comment by AbrilRBS** [comment]
Closing as solved. Please feel free to reopen/create a new issue should you have any other questions, thanks! :)
