### ISSUE TITLE
[question] Artifactory does not show artifacts in the same way as conancenter does

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#14273]
### What is your question?

Dear Conan Folks,

My use-case is that : 
- I would like to see what variants are build in artifactory similar to what conan center has. For example:
https://conan.io/center/cmake 
Here it shows the revision id and which configurations are available for this cmake version i.e. 3.26.0
The same i case of artifactory is not very intuitive. There is alwasys nested structure with sha-id. If you click on the top level0, and parse conan package info then probably you see what os , architecture, build type and compiler version. Is it possible to provide this information similar to what we see in the conan center?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

thanks for your question.

The development of Artifactory is outside of our scope, and you might need to direct the request to JFrog support channels.
At the moment, there is no plan to improve or change the Artifactory UI with regards to this.

The recommended way to explore the different binaries in servers is with the ``conan list`` command, that has many patterns and options to list revisions, configurations, etc.

**Comment by maitrey** [comment]
Thanks for your reply! What is the channel to contact directly with JFrog support? Could you please help me?

**Comment by memsharded** [comment]
I think support is only for customers, if you are you need to reach to the person in your team/company managing the support tickets. 
For community editions, I am afraid there is no support included.

In any case, I think it is unlikely that this will happen. I'd still recommend the ``conan list`` as the solution to navigate Conan packages in repositories.

**Comment by maitrey** [comment]
Alright Understood. That means we have to develop our own GUI if we would like to have such an overview.Ticket can be closed.

**Comment by memsharded** [comment]
If you want a GUI, I'd recommend checking @markfinal https://github.com/markfinal/cruiz cruiz GUI, it is super complete.

Thanks for the feedback!

**Comment by markfinal** [comment]
Thanks for the plug on cruiz! It has an Artifactory package browser feature, that shows details like this:
![Screenshot 2023-07-13 at 09 30 58](https://github.com/conan-io/conan/assets/984489/e3a9018e-82e6-4704-a1ca-f267f7febc1a)

(Conan 1.x working in the stable cruiz-1.3.x versions, and Conan 2.0 in a prerelease of cruiz)

**Comment by maitrey** [comment]
Thanks for the hint to you both. I will look into it and get back to you.

**Comment by maitrey** [comment]
Hi @markfinal , I tried the alpha version(that supports conan-2.x) but donot know what to do with : https://github.com/markfinal/cruiz/issues/122 
Could you please help?
