### ISSUE TITLE
[question] conan's steps short explanation

### ISSUE THREAD

**Issue by davidhov** [conan-io/conan#14278]
### What is your question?

Can you please explain how does generated files (in generators) folder make influence when building the library?

For example, there are a few files: cmakedeps_macros.cmake, conan_toolchain.cmake, openssl-config.cmake, openssl-config-version.cmake, ... ,opensslTargets.cmake.
Are these .cmake files set some variables and then when building the main library, it reads already set variables?
I don't understand steps of cmake variables set from many files.
Is it even possible to provide short answer to this question or maybe you can provide some documentation where the steps explained? I mean not what exactly some functions (e.g., package_id(), configure()) doing, but the structure of conan and its relationship with cmake.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @davidhov 

The general idea, as described in https://docs.conan.io/2/reference/tools/cmake.html and the tutorial is that those files are internal implementation detail. You don't really need to read or understand them.

They are saved in a location, and using ``find_package(mydep)`` and then ``target_link_libraries(mytarget ... mydep::mydep)`` should be good to consume it. Mostly as the config files provided by the libraries too, the ideas is that their contents are actually not intended to be read, but just to be used transparently with ``find_package()``.

There is not much magic or steps, but this is quite standard CMake behavior:

- Conan writes a few files, like the ``mydep-config.cmake`` (the entry point) and others, with CMakeDeps
- The ``conan_toolchain.cmake`` file written by ``CMakeToolchain`` contains CMAKE_PREXIX_PATH poiting to the ``generators_folder`` where ``CMakeDeps`` wrote its files.
- When ``cmake ... -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake`` (or using presets, it does the same), runs, and it finds a ``find_package(mydep)``, CMake will find the ``mydep-config.cmake`` file written by ``CMakeDeps``, load it, it will contain the ``mydep::mydep`` target with all the includedirs, libdirs, libs, etc
- Linking with ``target_link_libraries(... mydep::mydep)`` will pass all the information to find the headers and libs of the dependency and CMake will use it to link.

**Comment by davidhov** [comment]
Thank you for the answer!
