### ISSUE TITLE
[bug] cross_building fails to detect when building for same os but different arch

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#14276]
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version: gcc7
* Conan version: 2.0.7
* Python version: 3.8.10

### Steps to reproduce

I have the following in my recipe
```python
    def validate(self):
        if cross_building(self):
            raise ConanInvalidConfiguration('wxWidgets does not support cross compiling')
```

and the following profile

```ini
{% set toolchain = '/opt/arm-none/' %}
{% set target_host = 'arm-none-linux-gnueabi' %}
{% set sys_root = os.path.join(toolchain, 'sysroots', 'x86_64-nonesdk-linux') %}
{% set arm_root = os.path.join(toolchain, 'sysroots', 'armvhf-neon-none-linux-gnueabi') %}
{% set bin_path = os.path.join(sys_root, 'usr', 'bin', target_host) %}

[settings]
os=Linux
arch=armv7hf
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
build_type=Release

[options]
opencv/*:with_gtk=False
opencv/*:with_webp=False

[buildenv]
CONAN_CMAKE_SYSROOT={{arm_root}}
CONAN_CMAKE_FIND_ROOT_PATH={{arm_root}}
CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
CONAN_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
CONFIG_SITE={{toolchain}}/site-config-armhf-neon-none-linux-gnueabi
CCACHE_PATH+=(path){{sys_root}}/usr/bin
CCACHE_PATH+=(path){{sys_root}}/usr/bin/{{target_host}}
PATH+=(path){{sys_root}}/usr/bin/{{target_host}}

PKG_CONFIG={{sys_root}}/usr/bin/x86_64-nonesdk-linux-gnu-pkg-config
PKG_CONFIG_SYSROOT_DIR={{arm_root}}
PKG_CONFIG_PATH+=(path){{arm_root}}/usr/lib/pkgconfig 
PKG_CONFIG_PATH+=(path){{arm_root}}/usr/share/pkgconfig

# Set toolchain
CHOST={{target_host}}
AR={{target_host}}-ar
LD={{target_host}}-ld --sysroot={{arm_root}}
AS={{target_host}}-as 
NM={{target_host}}-nm
CC={{target_host}}-gcc
CXX={{target_host}}-g++ 
GDB={{target_host}}-gdb
STRIP={{target_host}}-strip
RANLIB={{target_host}}-ranlib
OBJCOPY={{target_host}}-objcopy
OBJDUMP={{target_host}}-objdump
LIBTOOL={{sys_root}}/usr/bin/x86_64-nonesdk-linux-gnu-libtool

# Set flags
LDFLAGS=-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed
```

I then run the following command
`conan create --build missing --version 3.1.5 -pr:b default -pr:h gcc7-linux-armhf wxwidgets/`

### Logs

```
======== Computing necessary packages ========
Requirements
    expat/2.5.0#91e43e4544923e4c934bfad1fa4306f9:237275f58cf2ea99f8a69878997fd852c75b4a47 - Build
    gtk/system#3671596ecc796ec65f881b2cad66ce26:b393f04ef5ca6a89590f29f8ca7eda026c148049#3d742b429533a316c8e6f3ea841ac0ae - Download (conancenter)
    jbig/20160605#2d29fa02aacd76902e0d2cbbc24631ef:dbd1cced0366cf20603572129fd38a905c409572 - Build
    libdeflate/1.18#3697b637656a9af04cabcbed50db9a7e:55f729a79cf5cdba1b2b8524545da58ed56429f4 - Build
    libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187:55f729a79cf5cdba1b2b8524545da58ed56429f4 - Build
    libpng/1.6.40#3b63a2aa000933a57a53322207790714:279cd42d603bf420e7df10857b093a01bc2316c1 - Build
    libtiff/4.4.0#162346e2d76e86279f3d3a44889a8cda:eaf0bfa29205e18331c96a26410ab594874677dc - Build
    libwebp/1.3.1#f86c9ecf081ebd5ac9def27e53de7bd3:30c5b46da47eba022ae14a4df3a9e56f0dc6e4c8 - Build
    wxwidgets/3.1.5#97b1e4225d404a3c766e61c8c1825c9a:9294b4e59e8f6fd70eff87ef98a1c2fa30e72fd5 - Invalid
    xz_utils/5.4.2#b6ee8320403def553418874435445982:55f729a79cf5cdba1b2b8524545da58ed56429f4 - Build
    zlib/1.2.13#e377bee636333ae348d51ca90874e353:55f729a79cf5cdba1b2b8524545da58ed56429f4 - Build
    zstd/1.5.5#93372fe14bb7883bd4de82914e0a1841:b8f9d225ea4beaf7a312e4d0a3e27167eb7db663 - Build
gtk/system: RUN: dpkg-query -W -f='${Status}' libgtk2.0-dev:armhf | grep -q "ok installed"
dpkg-query: no packages found matching libgtk2.0-dev:armhf

ERROR: gtk/system: Error in system_requirements() method, line 39
        apt.install(["libgtk2.0-dev"] if self.options.version == 2 else ["libgtk-3-dev"], update=True, check=True)
        ConanException: System requirements: 'libgtk2.0-dev' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'
```

**Comment by memsharded** [comment]
Hi @wbehrens-on-gh 

First some note, just in case. All the ``CONAN_XXX`` env-vars do not longer have any effect in the new generators in 1.X, and not at all in 2.0. I guess you keep them in the profile for some back compatibility with some legacy 1.X (not modern 1.X)


Then, this doesn't sound a Conan issue, but more like a recipe or problem definition issue.
The ``gtk`` recipe contains:
```python
 apt = package_manager.Apt(self)
apt.install(["libgtk2.0-dev"] if self.options.version == 2 else ["libgtk-3-dev"], update=True, check=True)
```
And Conan knows it is cross compiling, so it tries to install ``libgtk2.0-dev:armhf``, but that doesn't exist. But the approach is correct. These are the possibilities to handle this case:

- Inhibit the ``Apt`` execution with ``tools.system.package_manager:tool=""``, so it doesn't execute
- Add the knowledge of what package needs to be installed for what architecture in the ``gtk`` recipe.

**Comment by wbehrens-on-gh** [comment]
> First some note, just in case. All the CONAN_XXX env-vars do not longer have any effect in the new generators in 1.X, and not at all in 2.0. I guess you keep them in the profile for some back compatibility with some legacy 1.X (not modern 1.X)

Ah, I'm trying to convert a v1 profile to use the v2 stuff currently, but it was originally created from a yocto toolchain so most of the information is copied from the environment file.

> And Conan knows it is cross compiling, so it tries to install libgtk2.0-dev:armhf, but that doesn't exist. But the approach is correct. These are the possibilities to handle this case:

GTK is a dependency of the package I'm trying to compile, does conan attempt to resolve dependencies before checking the validate step? part of the reason why I'm wanting the build to raise an exception when cross compiling here is because the toolchain I'm using doesn't contain a GTK installation already (and the host is headless so it wouldn't need it). Is there a way I can raise the invalid configuration exception before conan tries to install gtk?

**Comment by wbehrens-on-gh** [comment]
My theory was right
```python
    def requirements(self):
        # This has to be placed here to keep conan from attempting to resolve the dependency graph when cross compiling
        if cross_building(self):
            raise ConanInvalidConfiguration('wxWidgets does not support cross compiling')
```
fixes the issue as it seems that conan reads the requirements first and attempts to resolve them before validating if the initial package can even be built. Shouldn't `validate()` always be called first? why would I care about the requirements if the package I'm trying to build isn't supported for the configuration?

**Comment by memsharded** [comment]
> fixes the issue as it seems that conan reads the requirements first and attempts to resolve them before validating if the initial package can even be built. Shouldn't validate() always be called first? 

It is the other way round, typically the ``validate()`` contains expressions like:
- If ``mydep`` is a shared library => it won't work, raise Invalid
- If ``otherdep`` is version>3.4 and I am a static library => no way, I need to be a shared library for this, raise Invalid

So many validation need to happen knowing about the dependencies, so it is necessary to resolve the dependencies first.

The graph resolution is always "imperative", based on the current definition (profile) the graph is expanded accordingly.

Please recall that raising ConanInvalidConfiguration in ``requirements()`` is not expected. You can launch a ``Exception`` if you want, but doesn't sound great either. The general recommended approach is add dependencies conditionally, or skip them conditionally, but not raise errors there.
