### ISSUE TITLE
[question] test_package: error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by davidhov** [conan-io/conan#14277]
### What is your question?

Hi!

I could overcome  "fatal  error C1083: Cannot open include file: 'openssl/ssl.h':" error mentioned here (https://github.com/conan-io/conan/issues/14265) by changing `OpenSSL_*` to `openssl*` in the patch file (please, see here https://github.com/davidhov/test_nats_patches/blob/main/patches/nats-src-cmakelists-openssl.patch#L11)

As I understood from what you have answered here (https://github.com/conan-io/conan/issues/14265#issuecomment-1629745603), it should have been `OpenSSL_*`, but it wasn't case for me because maybe I am not using standard recipe file for `openssl` library, but the custom one defined by my company. I looked into generated `openssl-config.cmake` file and the following was mentioned there:

```
set(openssl_VERSION_STRING "3.1.1_0")
set(openssl_INCLUDE_DIRS ${openssl_INCLUDE_DIRS_RELEASE} )
set(openssl_INCLUDE_DIR ${openssl_INCLUDE_DIRS_RELEASE} )
set(openssl_LIBRARIES ${openssl_LIBRARIES_RELEASE} )
set(openssl_DEFINITIONS ${openssl_DEFINITIONS_RELEASE} )
```

That's why I changed to `openssl*` in the patch file. Hence, my 1st question is:
1. I run `conan create ...` on another PC with standard `openssl` recipe file and it worked for me as well (both with `OpenSSL_*` patched version **and even without patch**). So, what might be the problem related to custom defined recipe file for `openssl`? How would you suggest to identify it?

2. when conan builds test_package, it throws the error:

```
  test.cpp
nats_static.lib(nats.obj) : error LNK2019: unresolved external symbol ERR_free_strings referenced in function _finalCleanup [D:\engage\test_nats_patches\test_package\build\test_application.
vcxproj]
nats_static.lib(nats.obj) : error LNK2019: unresolved external symbol EVP_cleanup referenced in function _finalCleanup [D:\engage\test_nats_patches\test_package\build\test_application.vcxpr
oj]
nats_static.lib(nats.obj) : error LNK2019: unresolved external symbol CRYPTO_cleanup_all_ex_data referenced in function _finalCleanup [D:\engage\test_nats_patches\test_package\build\test_ap
plication.vcxproj]
nats_static.lib(nats.obj) : error LNK2019: unresolved external symbol SSL_library_init referenced in function nats_sslInit [D:\engage\test_nats_patches\test_package\build\test_application.v
cxproj]
nats_static.lib(nats.obj) : error LNK2019: unresolved external symbol SSL_load_error_strings referenced in function nats_sslInit [D:\engage\test_nats_patches\test_package\build\test_applica
tion.vcxproj]
D:\engage\test_nats_patches\test_package\build\Release\test_application.exe : fatal error LNK1120: 5 unresolved externals [D:\engage\test_nats_patches\test_package\build\test_application.vc
xproj]
ERROR: nats/3.6.1@davithov/test (test package): Error in build() method, line 17
        cmake.build()
        ConanException: Error 1 while executing cmake --build "D:\engage\test_nats_patches\test_package\build" --config Release
```

Also, before this error there are some warnings related to it:

```
  srvpool.c
C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\nats.c(155,9): warning C4013: 'ERR_free_strings' undefined; assuming extern re
turning int [C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build\src\nats_static.vcxproj]
C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\nats.c(156,9): warning C4013: 'EVP_cleanup' undefined; assuming extern returni
ng int [C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build\src\nats_static.vcxproj]
C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\nats.c(157,9): warning C4013: 'CRYPTO_cleanup_all_ex_data' undefined; assuming
 extern returning int [C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build\src\nats_static.vcxproj]
C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\nats.c(1629,9): warning C4013: 'SSL_library_init' undefined; assuming extern r
eturning int [C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build\src\nats_static.vcxproj]
C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\src\src\nats.c(1630,9): warning C4013: 'SSL_load_error_strings' undefined; assuming ex
tern returning int [C:\Users\INT004201\.conan\data\nats\3.6.1\davithov\test\build\c5771f073100aa8fe7f9f55943e10444dc85dae9\build\src\nats_static.vcxproj]
```

As I can see those errors are linkage errors, i.e., compile phase passed for `test_package`, but when I am opening `test_application.sln ` file I can see that the solution could not find even included `nats/nats.h` header.

So, I don't understand how on earth Conan could pass compile stage and prompt me linkage errors.
Also, maybe should I change recipe file of the `test_package` accordingly? I mean that I have changed main recipe file (added there "src" in layout() function), so maybe that is the reason why `test_package` cannot find anything?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
> As I understood from what you have answered here (https://github.com/conan-io/conan/issues/14265#issuecomment-1629745603), it should have been OpenSSL_*, but it wasn't case for me because maybe I am not using standard recipe file for openssl library, but the custom one defined by my company.

Ok, that makes a lot of sense, of course, if you special recipe use a different casing, the consumer side should match it.

> I run conan create ... on another PC with standard openssl recipe file and it worked for me as well (both with OpenSSL_* patched version and even without patch). So, what might be the problem related to custom defined recipe file for openssl? How would you suggest to identify it?

Windows and OSX can be case-insensitive, and work, even if the casing doesn't match. Linux will typically be strict and fail if the casing doesn't match exactly. Is this the case?

Regarding the linking error, it might be a bit challenging to reproduce without access to your custom ``openssl`` package. I will try to reproduce (from next Monday, not possible for a few days) it, with the ConanCenter recipe, but it could be something like the previous case with the ``openssl`` casing.

**Comment by davidhov** [comment]
Thank you for the response!
No, actually I used windows on both my laptop and workstation. Furthermore, I have added standard remote, i.e., conancenter, (inside company we have our own internal remote), and with the standard `openssl` recipe file worked for me on the same machine. As soon as I am changing to custom recipe, it fails. 
What I can mention is that generated files by the custom recipe uses lowercase "openssl" everywhere (almost).
So, I tried to find `OPENSSL` or `OpenSSL` in the `CMakeLists.txt` files of NATS library and patch it to `openssl` counterparts.: 
1. In the main `CMakeLists.txt` file

**from**
```
if(NATS_BUILD_WITH_TLS)
  set(OPENSSL_USE_STATIC_LIBS ${NATS_BUILD_OPENSSL_STATIC_LIBS})
  find_package(OPENSSL REQUIRED)
endif(NATS_BUILD_WITH_TLS)
```
**to**

```
if(NATS_BUILD_WITH_TLS)
  set(OPENSSL_USE_STATIC_LIBS ${NATS_BUILD_OPENSSL_STATIC_LIBS})
  find_package(openssl REQUIRED)
endif(NATS_BUILD_WITH_TLS)
```

3. In the subdirectories' `CMakeLists.txt` file:

**from**
```
if(NATS_BUILD_WITH_TLS)
  include_directories(${OPENSSL_INCLUDE_DIR})
  set(NATS_OPENSSL_LIBS "${OPENSSL_LIBRARIES}")
endif(NATS_BUILD_WITH_TLS)
```

**to**
```
if(NATS_BUILD_WITH_TLS)
  include_directories(${openssl_INCLUDE_DIR})
  set(NATS_OPENSSL_LIBS "${openssl_LIBRARIES}")
endif(NATS_BUILD_WITH_TLS)
```
I tried to look into custom recipe file of `openssl`, but unfortunately didn't notice anything strange.
Just next to custom recipe file there is a `cmake` folder and `lib-openssl-config.cmake` file. It contains the following code:

```
set(openssl_FOUND 1)

if(NOT (TARGET openssl))
	add_library(openssl INTERFACE IMPORTED GLOBAL)
	set_target_properties(openssl PROPERTIES INTERFACE_LINK_LIBRARIES CONAN_PKG::openssl)
endif()

set(openssl_LIBRARIES openssl)
```

And based on the above code snippet I just assumed that maybe I should use lowercase `openssl` everywhere there it is possible inside NATS's `CMakeLists.txt` files.
BTW, if I don't user lowercase for `include_directories` cmake can't even find include directories. Once I applied patch, i.e., lowercase (  include_directories(${openssl_INCLUDE_DIR}) ), it started to recognize include directories.

**I can also modify our custom recipe file (e.g., by removing checks against other operation systems and other unrelated stuff) of `openssl` and send it to you if it will help**.
Another thing I tried is to run `cmake` with `--trace-expand` option for both custom and standard cases and compare printed info. There are quite some differences, but still couldn't find the problem. I have saved those files, so can share as well.

**Comment by davidhov** [comment]
Hello @memsharded,

Is it possible that you'll answer to the question today?
Thanks in advance!

**Comment by davidhov** [comment]
Sorry, for bothering you again, but I still have this issue and could not figure it out myself.
I would like to know whether you're going to help with this within **2.0.10** milestone or not. If yes, when may I expect the help?

**Comment by memsharded** [comment]
Hi @davidhov 

Sorry for the delay, we are a bit swamped, it is challenging to track all support tickets.
Yes, if you could share with us (or in private in info@conan.io if you prefer) your ``openssl`` recipe, that would help, indeed, as it works fine and can't reproduce with the ConanCenter recipe, it is difficult to know what could be happening, maybe having the recipe and reproducing with it helps.

**Comment by davidhov** [comment]
Hi @memsharded,

I have sent the custom recipe file to the above mentioned address.
To avoid sharing the exact file which my company uses I have also removed some code snippets from there which should not make any difference in this case.
Thank you for your help!

**Comment by memsharded** [comment]
Hi @davidhov 

Thanks got the file. I have been trying to build it, but unfortunately I haven't manage to build with that recipe.
I have overcome some things:
- Had to replace your private dependencies with ConanCenter public dependencies
- Had to replace your private source origin with the openssl public tgz
- Removed the injection of ``windows_sdk``, because I couldn't make it work, irrespective of what value I tried to use
- Fixed the layout of sources because of changing the source origin

And now I am getting compilation errors in the build itself of the kind:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winuser.h(4380): error C2146: syntax error: missing ')' before identifier 'lpwcx'
C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winuser.h(4380): error C2081: 'LPWNDCLASSEXA': name in formal parameter list illegal
C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winuser.h(4380): error C2061: syntax error: identifier 'lpwcx'
C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winuser.h(4380): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winuser.h(4380): error C2059: syntax error: ')'
```
Which honestly I don't know how to further progress :(

I am checking the ConanCenter recipe, and their definition is very different from yours. It is likely that the difference is there, but without being able to reproduce is almost impossible to know.

**Comment by davidhov** [comment]
Hi, I'll send you the original version of the file without making any
changes there. Hopefully it will compile. Sorry for inconvenience 🙏

**Comment by memsharded** [comment]
Tried it, still same compiler errors. I have tried different VS versions, still same. I guess it might be related to the Win SDK version, but no idea how to reproduce it or make it compile without removing the ``windows_sdk`` stuff.

**Comment by davidhov** [comment]
Hi James,

I am sending to you the whole package - without making any changes.
I am using Windows 10.

Best Regards,
David

**Comment by memsharded** [comment]
I am afraid the email never arrived, I have also checked the spam folder, but no success.

**Comment by davidhov** [comment]
Resending...

**Comment by memsharded** [comment]
It seems there might be something in the email path, could be some server size limit, or anti-virus/anti-spam check, but that email is not hitting our inbox, sorry :(

**Comment by memsharded** [comment]
Another alternative would be to put it in a Github repo and share access with us.
That would actually be useful, because it can include changes, adding some script that helps reproducing the issues would be great too.

**Comment by davidhov** [comment]
Hi @memsharded,

Sorry for the late response.
I have created a separate repository in github and shared it with you (https://github.com/davidhov/custom-openssl).
Frankly said, I didn't know what kind of script to add, because I have just run `create` command to create a package, i.e., didn't do nothing special.

**Comment by memsharded** [comment]
Hi @davidhov 

I am checking the repo, but I am finding only a zipped 7z archive in the repo. Why it doesn't contain source files? What am I supposed to do with the 7z file? It would be much better if it had the files there, because for example I can do inline comments, I can do a Pull Request with some proposed changes that could help, we could discuss in the review, etc. That is the main reason to put things in a Github repo. Do you think putting the files there would be possible? Thanks!

**Comment by davidhov** [comment]
Hi @memsharded,

Can you please recheck the repo? (https://github.com/davidhov/custom-openssl)
1. pushed there `nats` folder
2. pushed `openssl` folder which contains custom recipe file which we use. Please, note that in the recipe file of `nats` (line 64) it is mentioned remote which should be changed, but I didn't know how to do that.
3. pushed `openssl-3.2.0-alpha1` folder which is actual openssl library.
4. pushed `win-master-vs17u11-release-cpp20` profile file which I use when running `conan create`, i.e., I am running` conan create . nats/3.6.1@davithov/test --profile "..\tv-profiles\win\win-master-vs17u11-release-cpp20" --build=missing`

Please, let me know if I missed something again and sorry again for huge inconvenience. If you have to spend much time to figure out the problem, maybe I should close the ticket (let me know please if it is the case).
Thanks in advance!

Best Regards,
David

**Comment by davidhov** [comment]
Hi, I made further investigation on the issue I have and figured out that our custom openssl recipe file excludes functions which are deprecated (see `config_args = "no-srp no-engine no-deprecated --api=1.1.1 --prefix=%s" % self.build_folder` line in the recipe file). NATS library calls these deprecated function which basically don't exist, hence I am getting link errors.
As the issue is very project specific and isn't not connected to conan, I am closing this issue.

Thanks a lot for your help!

Best Regards,
Davit Hovsepyan

**Comment by davidhov** [comment]
see above comment

**Comment by memsharded** [comment]
Hi @davidhov 

Thanks very much for following up, your further investigation and feedback

> Please, let me know if I missed something again and sorry again for huge inconvenience. If you have to spend much time to figure out the problem, maybe I should close the ticket (let me know please if it is the case).

Not necessary. We might not be able to put enough time for some deep investigations, but not necessary to close the ticket if it has not been really solved. Even if it is unlikely, it might be useful to other users with the same issue, or someone is eventually put that time to investigate it. Sometimes as you see, it might be necessary to comment on it to "resurface" the ticket a bit, we try our best, even if sometimes we cannot help with everything

> Hi, I made further investigation on the issue I have and figured out that our custom openssl recipe file excludes functions which are deprecated (see config_args = "no-srp no-engine no-deprecated --api=1.1.1 --prefix=%s" % self.build_folder line in the recipe file). NATS library calls these deprecated function which basically don't exist, hence I am getting link errors.
As the issue is very project specific and isn't not connected to conan, I am closing this issue.

Ok, that totally makes sense, I suspected that it was something pretty specific to the way the openssl package was being built, very happy that you have found the cause! :)

Thanks very much again for your feedback!
