### ISSUE TITLE
[question] Need description of the new folder structure introduced in Conan-2.x

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#14274]
### What is your question?

Dear Conan Folks,

I am missing the documentation of the change in structure of folders inside conan cache. 
Right now, I see a b folder and a p folder sometimes a t folder in addition to es, s and e.
Could you please help me with the documentation link?
Another question that I have is:
- Is it possible to build in a output folder in the current working directory ?
- And then export and upload the package?
Normally , I use conan create with the user and channel but it automatically puts the build folder and package folder in the conan cache.
Some of our users do not wish to traverse to conan cache.
Is it possible to support this use-case with available functionality in 2.x?

Thanks a lot for your help !
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

The structure of the cache in 2.0 is an implementation detail, it will not be documented explicitly.
The way to access it is with the new ``conan cache path`` command: https://docs.conan.io/2/reference/commands/cache.html#conan-cache-path, you pass a reference, and it will tell you the folder. Commands like ``conan install .... --format=json`` will also contain folder information in the json output.


> Is it possible to build in a output folder in the current working directory ?

Yes, you can use the local flow: ``conan build`` + ``conan export-pkg``. Check: https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html


> Normally , I use conan create with the user and channel but it automatically puts the build folder and package folder in the conan cache.

Yes, this is still the recommended way to create packages. Even the local flow is possible, it shouldn't be necessary in CI, for exaample.

> Some of our users do not wish to traverse to conan cache.

They shouldn't. Normal developers should not need to do that. Their normal flow is ``conan install`` + ``cmake`` + ``git push changes``. They might want to do a local ``conan create`` to make sure things are working fine, but they shouldn't need to traverse the conan cache, open it or anything like that. The developers shouldn't be uploading the packages themselves, as a general rule, at lest to the development repositories. Check: https://docs.conan.io/2/knowledge/guidelines.html

**Comment by maitrey** [comment]
Hi James, Thanks for answering. We use mainly conan create as the main interface for our developers as well as in CI/CD. However when there is a build failure or a test failure it is needed to go to the folders in the cache and check for errors. This in conan-1.x was , clearly: export_sources, sources, build , package . This has changed to a one letter and the "t" is somewhat new. Could you please help me understand how this is in 2.x?  I could not find any information regarding it in the documentation.

**Comment by memsharded** [comment]
There is some internal implementation mapping, like ``e=export``, ``es=exports_sources``. 
But the idea is that now those are internal implementation details, and devs that want to get the folder will call ``conan cache path zlib/1.2.13 --folder=export_sources``, and get the folder directly.

It is also important the idea that Conan 2, with the layout() and improved build system integrations, the normal developers should do this much, much less, only occasionally. Digging in the cache should be less necessary, as the local build ``conan build`` for example would already cover the vast majority of developer issues and problems.

**Comment by maitrey** [comment]
I am interested to know the internal implementation mapping. Our implementation is same for local use-cases as well as CI/CD Use-Cases. So i need to understand the internal representation so that I can users what it stands for.

**Comment by memsharded** [comment]
If you are interested in the implementation, the best is the source code, you can find it here: https://github.com/conan-io/conan/blob/release/2.0/conan/internal/cache/conan_reference_layout.py

In any case, this is something that we will not document at this moment, it is an internal implementation detail, and relying on that mapping found in that file can break any time, we could change the cache layout, the folders, etc. It doesn't matter if it is CI or developers, if you are using that ``EXPORT_SRC_FOLDER = "es"`` and you hard coding the ``"es"`` string somewhere in your tooling, that can break in any future Conan release.

**Comment by maitrey** [comment]
Thanks james .. this is what i was looking for .. ticket can be closed.
