### ISSUE TITLE
[question] How to build large-scale binary files in bulk using Conan

### ISSUE THREAD

**Issue by BrainLyh** [conan-io/conan#14270]
### What is your question?

Hi！I want to build binary files using Conan. However, if the projects have different file structures, can I build them using a Python script？

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @BrainLyh 

Sorry, I don't know what you mean. With Conan you can use any build system, CMake, Visual, Autotools, Meson, etc, or you can use your own build system. If you have python scripts to build your project you can call them too.

**Comment by BrainLyh** [comment]
Hi @memsharded 

Thanks for your reply !

I want to compile different C projects into library files or executable files separately, for example: openssl, ffmpeg, etc. As far as I know, Conan provides information for some versions of these projects, but I cannot directly use the Conan recipe for certain versions because I will modify some of the code. My main question is, when dealing with projects like openssl and ffmpeg, should I put the entire project files in the /src directory? Then, when writing the CMakeLists.txt file, should I specify the source code as all the files in the /src directory (I'm not sure if this approach is correct)?

**Comment by memsharded** [comment]
>  but I cannot directly use the Conan recipe for certain versions because I will modify some of the code. 

The recommended approach is:
- Do a fork of ``conan-center-index`` repo containing the recipes
- Modify the recipes, apply your own patches, etc
- Do a ``conan create`` for the recipes and versions you want to use in your projects
- ``conan upload`` those packages to your own private server.

Then use those dependencies from your server as usual.

**Comment by BrainLyh** [comment]
Hi @memsharded 

Thanks for your suggestion! It helps a lot.

**Comment by memsharded** [comment]
Happy to help. Do not hesitate to open new issues for any further question you might have. Thanks for the feedback!
