### ISSUE TITLE
[question] How to reduce amount of the compilation after update one of conan packages

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14283]
### What is your question?

Hi,

I would like to ask if it is possible to avoid the recompilation the whole project after updating one of the conan packages?
Lets assume that I'm doing development of myproject-libs

- updating myproject-libs and creating new version of myproject-libs/2.3-rc4: `conan create . && conan upload -r artifactory myproject-libs/*`
- changing requirement of my myproject in conanfile.py to myproject-libs/2.3-rc4
- `conan install . --output-folder=build`

And the whole project is recompiling all over again...

Is it possible to avoid it?

Let me know if something is misunderstanding

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @damian-tomczak 

Thanks for your question

> And the whole project is recompiling all over again...
Is it possible to avoid it?

You need to provide way more information.
For a start, very important the Conan version.

Then, everything is managed by the ``package_id`` and the ``package_id_modes``. Conan will not rebuild when it is not necessary (specially Conan 2.0), so if it is building something from source, it is very likely that it needs to be rebuilt.
If you can provide a complete reproducible example (using ``conan new cmake_lib`` templates, for example, with some app->libc->libb->liba dependency graph), that would really help.

**Comment by damian-tomczak** [comment]
> Hi @damian-tomczak
> 
> Thanks for your question
> 
> > And the whole project is recompiling all over again...
> > Is it possible to avoid it?
> 
> You need to provide way more information. For a start, very important the Conan version.
> 
> Then, everything is managed by the `package_id` and the `package_id_modes`. Conan will not rebuild when it is not necessary (specially Conan 2.0), so if it is building something from source, it is very likely that it needs to be rebuilt. If you can provide a complete reproducible example (using `conan new cmake_lib` templates, for example, with some app->libc->libb->liba dependency graph), that would really help.

Turned out that the whole project isn't recompiled but only 62 of 63 translation units recompile. And they are using headers provided by the package, so nothing can be done here... Sorry for the question

**Comment by memsharded** [comment]
Good, thanks for the feedback!
