### ISSUE TITLE
[feature] See in logs when files were taken from the Download cache

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#14285]
### What is your suggestion?

Dear Conan dev team
As follow-up of https://github.com/conan-io/conan/issues/12129 I would like Conan (1.x and 2.x) to print to the debug log/Conan trace file when a file is not downloaded from the remote repository but instead taken from the download cache (and then unzipped into the package cache folder).

Our use case for this is:
We are heavily using the download cache (stored on a share network drive) and sometimes our Conan install duration is very long. We have the feeling that this is due to slow access to the download cache but to be sure we want to check if the long duration of Conan install happens when files are taken from the download cache.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

Thanks for the suggestion.
I think it makes sense to have some output with this information. Even something minimal with the default logging level if possible, but if too much, then yes, at least as verbose output.

**Comment by TheMarTom** [comment]
That would be great if you could add such a log output. At the moment we have to check for absence of certain entries in the logs and this is really cumbersome.

**Comment by MTomBosch** [comment]
Since we are still stuck with 1.x for some more time it would be great if this feature could be added to 2.x and 1.x as well.

**Comment by memsharded** [comment]
In 1.X it would be probably way more complicated, as it didn't implement logging levels correctly, and it can be very noisy.
This kind of UX improvement is likely that will be only targeted to 2.0, we will first target it and based on the final solution, consider backporting (but as said, this kind of improvement commonly doesn't get enough relevance to be backported)

**Comment by memsharded** [comment]
Implmented in https://github.com/conan-io/conan/pull/14716 for next 2.0.11
