### ISSUE TITLE
[feature] Support for Intel OneAPI as system requirement

### ISSUE THREAD

**Issue by forthib** [conan-io/conan#14288]
### What is your suggestion?

Hello, I would like to use Intel OneAPI components that are installed in the system: intel-tbb, intel-mkl, intel-ipp, intel-mpi, etc. I need to use them in a package recipe.

For each component, I need to specify a required version (e.g intel-tbb/2021.5.0).

I am aware of Conan packages onetbb, onedpl, but 1/ they do not exist for all oneAPI components (oneMKL, oneIPP, oneMPI) and 2/ I would like to use libraries of the oneAPI distributions.

I am also aware that I can package my own private version of intel-mkl, intel-mpi, etc. following https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#how-to-package-libraries-that-depend-on-proprietary-closed-source-libraries
but it is not that easy (there are a lot of libs to select, depending on options/configuration), and it can be a huge package (mkl_core.lib ~600MB).

It can be more convenient to define a conan package that acts like a proxy to versioned versions of  system libraries. Is it possible?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @forthib 

Thanks for your question.

> It can be more convenient to define a conan package that acts like a proxy to versioned versions of system libraries. Is it possible?

It is definitely possible to define such a package, but this is not something that the Conan client does. If anything this would be something to discuss in the ``conan-center-index`` repo.
But it is very likely that this will not fit ConanCenter either: Everything in ConanCenter must be open-source. Are all of those libraries open-source? As you suggest with the link, they are not.

So if it is not open-source, then there is little we can do from our side, and users wanting to do that will have to create the packages themselves.

**Comment by forthib** [comment]
Hi, thanks for your answer.

OK I understand. The best we can do seems to create our own private package, and maybe share the recipes, if there are no legal issues to do this.

**Comment by memsharded** [comment]
> OK I understand. The best we can do seems to create our own private package, and maybe share the recipes, if there are no legal issues to do this.

Yes, it would be great if you can share the recipes. The fact that it is not possible to add it to ConanCenter right away as binary packages, doesn't mean that the recipe won't be able to be added. We have new mechanisms like ``upload_policy = "skip"`` to avoid uploading binaries, that we could enable and allow in ConanCenter if it makes sense. Sharing the recipe itself is not a problem, the recipe can be ``MIT`` license, as long as you don't redistribute binaries or source, it is not a problem.

I am closing this ticket as responded, but I'd strongly recommend that if you have something you can share the recipe, please open a new ticket here in this repo, with that recipe, so we will analyze it and kick-off the discussion of adding this kind of thing to ConanCenter. 

Many thanks!
