### ISSUE TITLE
reported errors should contain line numbers

### ISSUE THREAD

**Issue by cleeland** [conan-io/conan#1428]
It would be really helpful if errors reported when running conan also reported guilty line numbers.

For example, I have the following `test_package/conanfile.py`:
```from conans import ConanFile, CMake
import os


channel = os.getenv("CONAN_CHANNEL", "testing")
username = os.getenv("CONAN_USERNAME", "ccleeland")


class CppdepTestConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires = "cppdep/latest@%s/%s" % (username, channel)
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "cmake"

    def build(self):
        pass

    def imports(self):
        pass

    def test(self):
        os.chdir("bin")
        self.run("pwd; ls; cpp-dependencies")
```

Running `test_package` I get an error in conanfile.py with no indication of where:
```$ conan test_package --profile ./devtoolset4.txt 
ERROR: /home/ccleeland/conanplay/cppdep/test_package/conanfile.py: Error while initializing options. 'options.shared' doesn't exist                                                                                 
Possible options are []
```

**Comment by memsharded** [comment]
Yes, I agree. In recent release we introduced wrappers to many conanfile calls, to be able to print the offending line. Sure it can be improved and extended to more cases.

But regarding your error, it seems that the conanfile is correct. I have run a quick test here, and it seems good. I think I might be missing something. Could you please provide more context? The whole package (with both the root conanfile.py and the test_package/conanfile.py) could help. I guess you are running ``conan test_package`` from the root folder, right?

**Comment by cleeland** [comment]
It's more perplexing.  I ran `conan test_package` with no arguments accidentally, hit ^C, then ran `conan test_package --profile ./devtoolset-4.txt` and it no longer gave me the error.

**Comment by memsharded** [comment]
In latest releases the output of errors has improved. Now an error in a conanfile.py method gives something like:

```bash
ERROR: Hello/0.1@user/failing: Error in package() method, line 23
        self.copy("*.lib", dst2="lib", keep_path=False)
        TypeError: __call__() got an unexpected keyword argument 'dst2'
```

In the case above, the thing is that the error is not in the conanfile itself, but from a combinations of factors and information from different origins, so it is not possible to assign the error to a conanfile line.

I think that this issue can be closed now, but please comment or re-open if necessary.
