### ISSUE TITLE
Conan workspaces on Conan version 1.59.0

### ISSUE THREAD

**Issue by igobrado** [conan-io/conan#14284]
### What is your question?

Hi!

I'm working on an enterprise project, so I can't post live examples of the conanfiles here, but I'm going to be as specific as I can.
The issue is the following,

My team is developing 6 closely connected components. and those components are depending on external components ( dependency hell .. ), and each of those components is exporting some lib that is doing something.

When I was searching for how this could be fixed, conan workspaces popped up in my browser and so I tried to implement it for us.
I added workspace.yml file and added the layout file, a top-level CMake file as described in https://docs.conan.io/1/developing_packages/workspaces.html.

**So far so good.**

Next steps:

1. Create a build directory
2. run `conan workspace install  .... -- pr:h ---
everything downloaded as expected, build layout looks similar to this
```
build
      - local_conan_cache
      - component1
      - component2
      - component3
      - component4
      - ....
```
**So far so good, output looks fine, every find* is generated and it's located in subcomponent repo in build folder**

### Problem starts
Usual build generation 
```
cd build
cmake ..

**everything exploded**
```
With the debugging process, I found out that every one of our components created the conan_toolchain.cmake which has to be included in CMake process, and when I hit CMake to generate the build files for the whole project, it's not included ( obviously .. ).
Including it manually should not be an option, but I'm really open to the discussion.
It's worth mentioning that we as well have def layout() and def generate() defined, and it's looking something like this:
```
    def layout(self):
        if not self.is_workspace_mode:
            self.folders.build = "build"
            self.folders.generators = join(self.folders.build, "conan")
            self.folders.source = "."
        else:
            self.folders.build = "../../build/component"
            self.folders.generators = self.folders.build
            self. folders.source = "./src"

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
```
I tried both CMakeDeps and cmake_find_package generators.
What could be our best possibility to create one common build for every component of ours using conan workspaces?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @igobrado 

I am afraid that the workspace feature was put on hold (on stand-by) several years ago. It is not prepared to handle the new ``editables`` or the new ``layout()``. The ``workspace`` command has been removed in Conan 2.0.

The recommendation at this moment is to use the ``editables`` and ``layout()`` and to set-up a project/workspace use a custom script (a custom command in 2.0 is possible too). From experience we know it is doable, very flexible and effective. Then, we will resume the work on workspace to reintroduce it in 2.X, the feedback from those scripts will be super valuable.

**Comment by igobrado** [comment]
Hi @memsharded,

OK.

Now I tried to use editables, I added an editable package `conan editable add ./ reference.
But now I'm getting following error:
`RROR: Error in generator 'CMakeDeps': error generating context for 'packageref': foobar/include is not absolute`.

package_info
```
    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "config")
        self.cpp_info.set_property("cmake_target_name", "myarget")
        self.cpp_info.components["mylib"].includedirs = ["foobar/include"]
        self.cpp_info.libs = ["mylib"]
```

Do you by any chance how I could rectify this issues?

**Comment by memsharded** [comment]
Note ``conan editable add .`` is enough now in 2.0 if the recipe declares ``name`` and ``version``

It seems the issue is that you are mixing components and not-components. Once you are defining components, everything should be a component. ``self.cpp_info.libs`` or any other "global" cpp_info is not allowed, it can be ignored or it might fail. Typically CMake target names will also be tied to components, not global.

If that is not fixing it, we would need something more complete we could reproduce. Thanks!

**Comment by igobrado** [comment]
Thanks, this helped a lot!

At the end with a bit of modification of `def layout` and CMakes, I managed to get the conan workspaces working for our components.

Thanks a lot for your help!

**Comment by memsharded** [comment]
Excellent, happy to hear that!

If you want to track progress of the future 2.0 workspaces, you can track and follow this ticket of the 2.x roadmap: https://github.com/conan-io/conan/issues/12466 (there are other tickets in 2.x regarding workspaces, easy to find navigating the 2.X Github milestone).

If you have some script, or the setup that you are doing for your project, it will be extremely interesting if you could share it, and possibly give feedback when https://github.com/conan-io/conan/issues/12466 work is resumed.


Thanks very much for your feedback!
