### ISSUE TITLE
[question] How to do custom generators and get all required dependency information

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#14287]
### What is your question?

How is one supposed to do custom generators now (with the generate function and all that being the new hot thing), without having to do everything manually every time in the generate function?

Also how does one get every dependency for each individual component of all the packages and get all the information regarding the components and associate them with the packages?

It seems there is very little information about that documentation wise (at least that I could find).

Looking at the (very complex) CMakeDeps generator, it looks like there are very many special cases and lots of different paths one has to check to get everything?

Would love to have some information about how to do these things nowadays, ideally being compatible with both 1.60+ and 2.0+

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

Thanks for your question.

> How is one supposed to do custom generators now (with the generate function and all that being the new hot thing), without having to do everything manually every time in the generate function?

The recommended way is using ``python_requires``: https://docs.conan.io/2/reference/extensions/python_requires.html

> Also how does one get every dependency for each individual component of all the packages and get all the information regarding the components and associate them with the packages?

Navigation of dependencies is done via ``self.dependencies``, and also the components information is there:
- https://docs.conan.io/2/reference/conanfile/methods/generate.html#conan-conanfile-model-dependencies
- https://docs.conan.io/2/reference/conanfile/methods/package_info.html#conan-conanfile-model-cppinfo
- https://docs.conan.io/2/reference/tools/cpp_info.html

This approach, of ``generate()`` that calls code from a ``python_requires`` and that code uses ``self.dependencies`` and the dependencies ``cpp_info`` will work both in 1.X and 2.0.

I hope this helps.

**Comment by AbrilRBS** [comment]
Closing as solved with the given explanation :)
