### ISSUE TITLE
[question] Why is the CMakeUserPresets.json file not generated when running "conan install" in the build folder?

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#14290]
### What is your question?

Hi, there seems to be a difference between running
```
conan install --install-folder build .
```
and
```
cd build
conan install ..
```
(Conan 1.60) regarding the `CMakeUserPresets.json` which is not generated with the second command. Why is that?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @petermbauer 

The ``CMakeUserPresets.json`` only works when it is located besides the ``CMakeLists.txt``. If the ``CMakeLists.txt`` is not there, it will not be generated, because it cannot be used, it would be useless to generate it.

**Comment by petermbauer** [comment]
thx @memsharded, that is clear, but the `CMakeLists.txt` is always there, next to the `conanfile.py`. Is it only searched in the current directory or what is the logic behind that?
From a user perspective the two commands are expected to give the same results i would say.

**Comment by memsharded** [comment]
No, it is not the same ``--install-folder`` is legacy, mostly used by legacy generators (not the new ones), and some of the legacy generated files. You should use ``--output-folder`` for the new ``layout()`` and modern ``generators``

**Comment by petermbauer** [comment]
I tried out a few variants with `--output-folder` but in the end all this leads to implementing the `layout()` method (`binaryDir` does not point to the `--output-folder` but to the source folder) which would be a quite deep rabbit hole to dive into atm.
Thanks again!
