### ISSUE TITLE
[feature] conan install --build should support building packages that are only compatible and not an exact match

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14291]
### What is your suggestion?

The new compatibility function allows `conan install` to use compatible packages instead of an exact match. However, I think it should work together with the `--build` parameter to force building packages that are only compatible (but use e.g. an older C++ standard or an older libc version). A more exact matching package might have performance or other advantages over using only a compatible package.

It could be called `--build compatible` or something similar.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by fschoenm** [comment]
Any comments on this one?

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/16871 implemented this for next Conan 2.8

**Comment by fschoenm** [comment]
This came out of nowhere. Thanks @memsharded for implementing this 😊

**Comment by memsharded** [comment]
No prob, sorry that we didn't respond or provide feedback back then, often it is challenging to keep track of all tickets, issues and PRs.
