### ISSUE TITLE
[question] how to configure a CMake project with custom variables?

### ISSUE THREAD

**Issue by famastefano** [conan-io/conan#14294]
### What is your question?

Hello,
I'm using Conan 2 with a CMake solution.

So far I've used Qt Creator and, don't laugh pls, I forgot how I configured it to use the conan generated config, I guess I just hardcoded the toolchain file path because it always ended up in the same spot.

I want to switch back to Visual Studio 2022, but I don't want to hack again this stuff...

The problem is that I have some variables in my CMakeLists.txt that change various stuff in my build, and some variables are required or CMake aborts the configuration.

How do I do that in conan?

I want to end up with 3 macro configurations:
1. Debug
2. Development
3. Shipping

All 3 set some variables to different values, think of it like `-DMY_PROJECT_OPT=ON` and so on, is it possible?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @famastefano 

yes, the ``CMakeToolchain`` allows this customization. Check: https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html

You can do:

```python
def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["MYVAR"] = "MYVAR_VALUE"
        tc.preprocessor_definitions["MYDEFINE"] = "MYDEF_VALUE"
        tc.generate()
```
and of course you can do ``if`` conditionals to activate vars or not, define values based on expressions, etc, you have full control over that.
You can take the values from settings, your own options, or your own ``conf`` items (in the form of ``user.myteam.mygroup:myconf``), options are typically better if they affect the final binary, ``conf`` if they don't affect the final binary.

**Comment by famastefano** [comment]
Hi @memsharded,
I've found my solution in a clean way, or better, the _conan-way!_

[Conan.io - CMakeToolchain: Extending your CMakePresets with Conan generated ones](https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets.html)

This addition, that I never seen before, grants me _"free will"_, as I can mess with CMake as much as I want as I can simply inherit from the conan config and everything will _just work&trade;_.

**Comment by memsharded** [comment]
Great, happy that you found what you needed, thanks for the feedback!
