### ISSUE TITLE
[bug] Visual Studio 2022; LNK4012; CMAKE_GENERATOR_PLATFORM is x64 instead of X64

### ISSUE THREAD

**Issue by skipfowler** [conan-io/conan#14293]
### Environment details

Windows 10 Enterprise 19044.3086
Visual Studio Professional 2022 17.5.4
Conan 1.60.1
Python 3.10.4

### Steps to reproduce

1. Run conan with a profile specifying `arch` and `arch_build` equal to `x86_64`
1. Check that `conan_toolchain.cmake` has `set(CMAKE_GENERATOR_PLATFORM "x64" CACHE STRING "" FORCE)`
1. Building any target should produce LNK4012 since VS 2022 is looking for X64 instead of x64

### Logs

```
LINK : warning LNK4012: invalid value 'x64;', must be 'ARM, ARM64, ARM64X, EBC, X64, or X86'; option ignored
```

**Comment by memsharded** [comment]
Hi @skipfowler 

Thanks for your report.
Is this a new thing of VS2022?. Maybe it depends on the CMake version too?

I am surprised about this, CMake docs https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_PLATFORM.html clearly put it in lowercase:

> The platform specifies the target platform (VS target architecture), such as x64, ARM64, or Win32. 

The same appears in command line in the ``-A`` argument in lowercase in https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html

> cmake -G "Visual Studio 17 2022" -A x64


Side note: ``arch_build`` is a legacy thing that shouldn't be used. Instead using the 2 profiles, including the "build" profile, is the recommended way to do cross-build.

**Comment by skipfowler** [comment]
Hi @memsharded,

The problem was my error. I set `/ignore:4099` on `CMAKE_EXE_LINKER_FLAGS` to suppress PDB related warnings for `protobuf` generated source. The moral is to use target based CMake like `target_link_options` whenever possible.

**Comment by memsharded** [comment]
Definitely, targets should be used as much as possible, as opposed to global definitions.

Thanks for following up!
