### ISSUE TITLE
[suggestion] Flush stderr after sending each log message

### ISSUE THREAD

**Issue by BobIsOnFire** [conan-io/conan#14298]
### What is your question?

Hi! As far as I can understand, Conan 2.0 doesn’t flush stderr regularly when writing log messages. 

When a relatively long operation without any output gets executed, you don’t see what is actually being executed, since the corresponding helpful log message is buffered and not printed yet. On multiple occasions I was trying to understand why some totally harmless operation is executing for so long, when in fact Conan was downloading & unpacking a large package in `source()` method at that time :) I did `self.output.flush()` just before calling `get()` in the method as a workaround, which immediately improved readability… in that specific place.

I believe it is also bad to have unflushed escape sequences. If the stream flushes the buffer only when it is full (read: whenever it wants to), it can flush the start of the colored message, but not the end of it, where the color resets back.

Do you think this can be fixed? I would love to at least have a conf for that.

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by BobIsOnFire** [comment]
I think I have also seen a problem with trace logs, when python tries to print a traceback from exception at the same time when Conan shows logs saying that something has broken, which completely messes up traceback. I am not sure this is related to flushing though..

**Comment by memsharded** [comment]
Hi @BobIsOnFire 

Thanks for reporting, I think it makes sense to flush automatically after every write, it seems it was done this way in 1.X. Submitting https://github.com/conan-io/conan/pull/14310 for next 2.0.9

**Comment by BobIsOnFire** [comment]
Thanks a lot!
