### ISSUE TITLE
Javascript disabled browsers

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#143]
Currently, nothing is shown if JS is disabled in browsers. Add at lest a check and a text notice stating that.

**Comment by lasote** [comment]
Done, will be available soon.

**Comment by annulen** [comment]
Now google search results display conan.io pages with title "So sorry, conan.io really needs javascript"

**Comment by memsharded** [comment]
Hi! Can you please post the details of the search you did? I cannot reproduce this, I get reasonable info for conan pages, including packages pages, like:

```
C/C++ Open Source Package Manager - Conan.io
https://conan.io/source/zlib/1.2.8/lasote/stable
conan install zlib/1.2.8@lasote/stable -s compiler=gcc -s compiler.version=4.9 -o option=true ... Complete the command using -s for your settings (or define your ...
```

Thanks!

**Comment by memsharded** [comment]
Yes, thanks, ok, now I see it. Reopening it, investigating.

**Comment by lasote** [comment]
Now we are sending a sitemap to google. Searches looks better now.

EX: [Search all my packages](https://www.google.es/search?biw=1366&bih=655&q=site%3Aconan.io+lasote&oq=site%3Aconan.io+lasote&gs_l=serp.3...0.0.0.61506.0.0.0.0.0.0.0.0..0.0....0...1c..64.serp..0.0.0.Hejz2MAgKZs)
EX: [Search cmake_intaller](https://www.google.es/search?biw=1366&bih=655&q=site:conan.io+cmake_installer&nfpr=1&sa=X&ved=0ahUKEwiYrqX13NPPAhUCtRoKHXZlDNoQvgUIHCgB)
