### ISSUE TITLE
[feature] Provide PACKAGE_FOLDER in CMake config files without config_suffix

### ISSUE THREAD

**Issue by dazze1812** [conan-io/conan#14303]
### What is your suggestion?

CMakeDeps generates a Find*.cmake file that sets some variables without the config_suffix:
```
set(xx_INCLUDE_DIRS ${xx_INCLUDE_DIRS_DEBUG} )
set(xx_INCLUDE_DIR ${xx_INCLUDE_DIRS_DEBUG} )
set(xx_LIBRARIES ${xx_LIBRARIES_DEBUG} )
set(xx_DEFINITIONS ${xx_DEFINITIONS_DEBUG} )
```

Since we have some "header-library" packages that also includes some source files it would be great if the PACKAGE_FOLDER was also provided without config_suffix.

In tools/cmake/cmakedeps/templates/config.py:

```
        set({{ file_name }}_VERSION_STRING "{{ version }}")
        set({{ file_name }}_INCLUDE_DIRS {{ '${' + pkg_name + '_INCLUDE_DIRS' + config_suffix + '}' }} )
        set({{ file_name }}_INCLUDE_DIR {{ '${' + pkg_name + '_INCLUDE_DIRS' + config_suffix + '}' }} )
        set({{ file_name }}_LIBRARIES {{ '${' + pkg_name + '_LIBRARIES' + config_suffix + '}' }} )
        set({{ file_name }}_DEFINITIONS {{ '${' + pkg_name + '_DEFINITIONS' + config_suffix + '}' }} )
```

add:

```
        set({{ file_name }}_VERSION_STRING "{{ version }}")
        set({{ file_name }}_INCLUDE_DIRS {{ '${' + pkg_name + '_INCLUDE_DIRS' + config_suffix + '}' }} )
        set({{ file_name }}_INCLUDE_DIR {{ '${' + pkg_name + '_INCLUDE_DIRS' + config_suffix + '}' }} )
        set({{ file_name }}_LIBRARIES {{ '${' + pkg_name + '_LIBRARIES' + config_suffix + '}' }} )
        set({{ file_name }}_DEFINITIONS {{ '${' + pkg_name + '_DEFINITIONS' + config_suffix + '}' }} )
        set({{ file_name }}_PACKAGE_FOLDER {{ '${' + pkg_name + '_PACKAGE_FOLDER' + config_suffix + '}' }} )
```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @dazze1812 

Thanks for your suggestion.

I'd like to clarify an important point: the "build_type" of the generated cmake file by ``CMakeDeps`` is not the "build_type" of the dependency, it is the "build_type" of the consumer. Let me put an example:

```python
def requirements(self):
     if self.settings.build_type == "Debug":
          self.requires("header_only/1.3")
    else:
          self.requires("header_only/2.0")
```
When installing in a multi-config environment like VS:
```bash
$ conan install . -s build_type=Release  # depends on 2.0
$ conan install . -s build_type=Debug # depends on 1.3
```
Then, there is no single ``PACKAGE_FOLDER``, there are 2 different package folders, one defined in ``xxx-release-data.cmake`` and the other in ``xxxx-debug-data.cmake``, one for release and one for debug, containing different files from different versions.

The existing ``xx_INCLUDE_DIRS`` variables are the very minimum necessary for legacy build system scripts from open-source packages in ConanCenter. They will not work in multi-config build systems, and in fact they have been sometimes problematic and confusing. But the tradeoff of the legacy build scripts balanced in that direction.

But that means that no more information will be added in the form of global, no-config variables will be added to the CMakeDeps generator.

There are some mechanisms that you can get access to the package folder of the dependencies in the recipes, like ``self.dependencies["mydep"].cpp_info`` (``.includedirs``, ``.srcdirs``), and from there you can pass it in the ``generate()`` method to the ``CMakeToolchain`` as the variables you want.

**Comment by dazze1812** [comment]
Hi @memsharded ,

we use this approach with the generate() method to provide the location of tool packages:

 ```
 def generate(self):
        tc = CMakeToolchain(self)
        # provide package root directories as CMake variables
        for require, dependency in self.dependencies.items():
            if require.build:
                tc.cache_variables["CONANPKG_" + dependency.ref.name.upper() + "_ROOT"] = PurePath(dependency.package_folder).as_posix().__str__()
```

My first thought was to do the same with our "source only" packages. Do I understand you correctly that this would be the right way?

**Comment by memsharded** [comment]
Yes, I think so.
It is a bit unexpected to need to folder location of ``tool_requires`` packages (as those are intended for executables, and the ``VirtualBuildEnv`` automatically manages to put them in the path, so just calling the executables work, typically not needed to add variables to CMake with their location), but otherwise, the process and overall approach is fine.

Just an important note: in Conan 2.0 ``dependency.package_folder`` can and will be ``None`` in those cases where the binary can be skipped. This happens often for ``tool_requires``, when such a ``tool_requires`` is actually not needed, because binaries for their consumers already exist, the tool will be marked as ``Skip``, the binary will not be downloaded, and then ``package_folder`` will be ``None`` (as there is no actual package installed)

**Comment by dazze1812** [comment]
We use VS Code with the CMake Tools Extension. I haven't found a way to use the VirtualBuildEnv in this setup. We have presets with different compiler versions and running VS Code in a VirtualBuildEnv is not an option.

**Comment by memsharded** [comment]
You might want to track https://github.com/conan-io/conan/issues/14271 for addition of environment information to CMake.

But in the general case, the management of environment is intended to work with all build systems, as it adds things to the environment before the actual build Not sure what is your flow, but if:
```
conan instal ...
conanbuild.bat # or . conanbuild.sh
code . # or calling ``cmake...``
```
It should work, it is the general flow that always work. Consider that ``tool_requires("cmake/[>3.25]")`` is a very common approach to depend on some cmake version managed by Conan. This can only work if the ``conanbuild`` activation of the environment happens before calling cmake (or running VS code, if that is the one calling cmake)

**Comment by dazze1812** [comment]
This flow does not work for us. We use several profiles (e.g. with different controllers or toolchains) for our packages. The use of the general flow would result in several instances of VS Code. 
Our flow is:
`code .`
in code: 
- run conan install for all profiles (via VS Code task)
- select preset/profile via CMake Tools extension
- build, test, ...

To enforce the correct CMake version we are patching the .vscode/settings.json with the CMake version from the tool_requires. I know, this only works if all profiles use the same version.

We are just starting to switch to Conan and are still trying and learning.
