### ISSUE TITLE
[feature] Support Alpine Linux system package manager

### ISSUE THREAD

**Issue by Sahnvour** [conan-io/conan#14307]
### What is your suggestion?

Hi,

The system manager support in conan is really handy and already covers a large list of distributions/tools.
It would be very nice though if it could also support [`apk`](https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper) for the Alpine Linux distribution.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Sahnvour 

Thanks for your suggestion.

Just to be sure, this is to add the ``Apk`` package manager to the Conan tool, but that doesn't mean that package recipes in ConanCenter will necessarily add its usage (Alpine not tested in ConanCenter CI). So it is for your own private recipes, isn't it?

We don't know much about ``apk``, would you like to contribute the feature yourself? It should be relatively straightforward, copying one of the existing ones.

**Comment by Sahnvour** [comment]
Hi @memsharded,

> So it is for your own private recipes, isn't it?

Yes, I am building my projects on Alpine in CI because it's a musl-based distribution that improves coverage, and I also think it is quite used in the docker space because of its small default size. As such, I'd be glad to let conan install system dependencies by itself instead of manually listing them myself.

I understand ConanCenter would probably not have prebuilt binaries but it's ok.
I don't know much about `apk` myself, however if you can give me some pointers on where to start in conan I will have a look at it (no promises).

**Comment by memsharded** [comment]
> I don't know much about apk myself, however if you can give me some pointers on where to start in conan I will have a look at it (no promises).

Sure, no commitment here at all, just if you like to do it. Some pointers:

- The entry point, and possibly the only file necessary to change is this one: https://github.com/conan-io/conan/blob/release/2.0/conan/tools/system/package_manager.py
- Copy and paste the ``Apt`` or the ``Yum`` class, and then start customizing for the ``apk`` case.
- If you clone and pip-install as editable the source project (https://github.com/conan-io/conan#setup), you can run ``conan`` commands using your clone changes
- Write a small recipe ``conanfile.py`` with a ``system_requirements()`` method that uses your new ``Apk`` class
- Try things.
- Finally, some integration tests would be enough, in this file: https://github.com/conan-io/conan/blob/release/2.0/conans/test/integration/tools/system/package_manager_test.py

**Comment by mkmkme** [comment]
Hey @memsharded ! Thanks for the pointers!
One issue I realized while poking into that is the fact that Alpine is a no-multilib distro. Hence, the concept of adding an arch separator and an explicit architecture to the package name is not applicable there.

So far I'm not sure how much of a problem this is. Let's see.

**Comment by memsharded** [comment]
I think that as long as ``self._arch_names = {}``, ``self._arch_separator = ""``, it shouldn't be a problem.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/14382 by @mkmkme, will be in next 2.0.10

**Comment by Sahnvour** [comment]
Thanks a lot @mkmkme !
