### ISSUE TITLE
How can I use conan to manage local installations of tools, including binaries?

### ISSUE THREAD

**Issue by cleeland** [conan-io/conan#1431]
The usage model for conan and libraries is pretty clear--one sets up a `conanfile.{txt,py}` to indicate required external packages.

In my case, I would like to use conan similar to `pip` or 'brew`--to set up an environment that includes binaries.

It seems that in order to do this with the way things are currently structured in conan, I would have to add the bin directory (or wherever executables are) for each individual required package into my path. That seems unwieldy at best, and non-scalable.

**Comment by lasote** [comment]
The package containing the tools can declare environment variables in the package_info method, using self.env_info.

For example, the path can be adjusted with self.env_info.path.append(os.path.join(self.package_folder, "bin").

The libraries that require the tool package will have automatically the declared environment vars available in the conanfile methods.

I recommend you to take a look to build requirements in the mastering Conan section in docs.conan.io. 

You can find an example of tools packaged there, also in the Android toolchain example here: http://docs.conan.io/en/latest/integrations/android_studio.html

**Comment by cleeland** [comment]
> The libraries that require the tool package will have automatically the declared environment vars available in the conanfile methods.

In my case, libraries aren't the users of the package.  I want the user to be able to use the content of the package interactively from the command line, for my CI job to be able to use the package inside CI (i.e., as a proxy for the user at the command line).

I'll take a look at the android examples to see if they do what I need.

**Comment by lasote** [comment]
Then take a look at the virtual environments: http://docs.conan.io/en/latest/mastering/virtualenv.html

**Comment by cleeland** [comment]
I independently found the `virtualenv` yesterday and it mostly does what I want.  I was hoping for something more akin to `brew` where all the installed stuff becomes available under one directory tree--either by virtue of being installed in that one tree or sym/hard-linked into that tree, but I think I can make virtualenv "close enough".

While looking into virtualenv I found documentation on two other virtual environments (runenv and buildenv), but it's not entirely clear from the description how those materially differ from virtualenv.  I will explore.
