### ISSUE TITLE
Fine-grained patching

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#14311]
Conan 2.0.6

As a qnx developer I frequently run into having patches specific to qnx.

Are there any plans to let `conan.tools.files.apply_conandata_patches()` support more fine-grained patching to for example allow  application of a specific patch only for a specific platform (settings.os and/or settings.os.version value).

Maybe do something like it was done with the sources section in conandata.yml for the prebuilt_tool template package: https://github.com/conan-io/conan-center-index/blob/master/docs/package_templates/prebuilt_tool_package/all/conandata.yml

If not, is there a recommended way of applying fine-grained patches other than implementing the above manually?

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Thanks for your suggestion.
The purpose of conan.tools.files.apply_conandata_patches() is precisely to implement the simple and most common use cases. It has some extra checks, managing some ConanCenter cases, etc, but in essence it is just:

```python
    patches = conanfile.conan_data.get('patches')
    for it in entries:
            patch_file = it.pop("patch_file")
            patch_file_path = os.path.join(conanfile.export_sources_folder, patch_file)
            patch(conanfile, patch_file=patch_file_path, **it)
```

Then, the recommended approach for other kind of patching is implementing a ``_apply_patches()`` method in the recipe that does basically the above, but if there are OS-specific patches, at some point it will do something in the line of ``self.conan_data["patches"][myos]...``

This is basically the same idea of the link you posted, check the https://github.com/conan-io/conan-center-index/blob/master/docs/package_templates/prebuilt_tool_package/all/conanfile.py conanfile implementation, that uses the ``os`` information to get the right ur.

- Change the ``conandata.yml`` to reflect the most convenient structure of patches
- Customize the recipe to use that ``conandata`` structure when necessary.

There could be different approaches, based on the needs, frequency of patches etc:
- Use always a classification of ``patches`` into OS, like the first nested dictionary key is the "OS"
- Apply some kind of attribute or tag to the patches that means "all" OSs, "linux-only", etc
- Keep the general patches that apply to all systems as-is now, and add an extra ``os-specific-patches`` section to the ``conandata.yml``


If we see growing need and demand for OS-specific packages, we will then try to encapsulate that behavior in some built-in helper, but at the moment we would like to see and learn a bit about the needs and usage of this.

**Comment by klausholstjacobsen** [comment]
This is what I have done so far....and will keep doing:
```
    def _patch_sources(self):

        # general patches
        for p in self.conan_data["patches"].get(self.version, []):
            print(f"patching general files: {p['patch_file']}")
            patch(self, **p, base_path=self.source_folder)
        
        # os specific patches
        for p in self.conan_data["patches"].get("{}-{}".format(self.version, str(self.settings.os).lower()), []):
            print(f"patching os specific files: {p['patch_file']}")
            patch(self, **p, base_path=self.source_folder)

        # os version specific patches
        for p in self.conan_data["patches"].get("{}-{}-{}".format(self.version, str(self.settings.os).lower(), self.settings.get_safe("os.version")), []):
            print(f"patching os version specific: {p['patch_file']}")
            patch(self, **p, base_path=self.source_folder)
```

conandata.yml:
```
sources:
  "1.0.0":
    url: "https://url"
    sha256: "aaa"
  "2.0.0":
    url: "https://url"
    sha256: "bbb"
patches:
  "1.0.0":
    - patch_file: "patches/0.patch"
  "1.0.0-some_os":
    - patch_file: "patches/1.patch"
  "2.0.0-some_os":
    - patch_file: "patches/2.patch"
  "2..0.0-some_os-v2":
    - patch_file: "patches/3.patch"
```

**Comment by memsharded** [comment]
That sounds very reasonable, thanks for sharing!
