### ISSUE TITLE
[question] run ./boostrap command

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14321]
### What is your question?

Hi,

At the beginning I would like to apologize for asking so many questions.

I want to create a package from the library that requires to call ./boostrap before configure and make.
What is the preferable way to do it?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @damian-tomczak 

> At the beginning I would like to apologize for asking so many questions.

No need to apologize! We love to help as much as possible, don't hesitate to ask the questions you have (sometimes we might be too busy, if you don't get a response, you can ping and revive the ticket too)

> I want to create a package from the library that requires to call ./boostrap before configure and make.
What is the preferable way to do it?

You can call whatever you want in your recipes, if you want to do:

```python
def build(self):
     self.run("./bootstrap")
     at = Autotools(self)
     at.configure()
     at.make()
```
is perfectly possible. Is this what you are looking for?

**Comment by memsharded** [comment]
Closing this ticket as staled, but please re-open or create a new one for any further question you might have. Thanks for the feedback!
