### ISSUE TITLE
[Question]Install Package failed: Invalid: 'options.cuda_version' value not defined

### ISSUE THREAD

**Issue by lxrui** [conan-io/conan#14339]
### What is your question?

I have packed a opencv prebuilt package with cuda, and upload it to my jfrog artifactory server named 'local'.
but conan install will failed with "Invalid: 'options.cuda_version' value not defined"

> PS C:\Users\hammer\develop\projects\cvva\src\bcv\build> conan.exe install . --remote local --build missing -o cuda_version=10.0 -o with_cuda=True
> 
> ======== Input profiles ========
> Profile host:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=192
> os=Windows
> [options]
> cuda_version=10.0
> with_cuda=True
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=192
> os=Windows
> [options]
> cuda_version=10.0
> with_cuda=True
> 
> 
> ======== Computing dependency graph ========
> Graph root
>     conanfile.txt: C:\Users\hammer\develop\projects\cvva\src\bcv\build\conanfile.txt
> Requirements
>     opencv/4.1.0@lxr/test#d7991cccb5bd892f64fee2cd176cb8ad - Cache
> 
> ======== Computing necessary packages ========
> Requirements
>     opencv/4.1.0@lxr/test#d7991cccb5bd892f64fee2cd176cb8ad:205bb53c45cba1c7e4b8ab243e4d46771e497b4e - Invalid
> 
> ======== Installing packages ========
> ERROR: There are invalid packages:
> opencv/4.1.0@lxr/test: Invalid: 'options.cuda_version' value not defined

And conan list can get options.cuda_version info on server

> PS E:\work\conan2> conan list "opencv/4.1.0@lxr/test:*" -r local
> local
>   opencv
>     opencv/4.1.0@lxr/test
>       revisions
>         d7991cccb5bd892f64fee2cd176cb8ad (2023-07-20 12:00:19 UTC)
>           packages
>             cb4785b2b8893eca6203d2c35a8d30a50cab2641
>               info
>                 settings
>                   arch: x86_64
>                   os: Windows
>                 options
>                   cuda_version: 10.0
>                   with_cuda: True

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lxrui 

Thanks for your question.

Options are defined per-package. Then, when specifying its value in the command line, it is also necessary to specify to which package that value is applying. You can define ``-o *:myoption=myvalue`` to apply to all packages (all packages that define the ``myoption`` option, if they don't it will be ignored).

In your case you are doing ``-o cuda_version=10.0`` that if not scoped, means that it will only apply to the "consumer" project, but not to the dependencies. You might want to be explicit as ``-o opencv/*:cuda_version=10.0``. Please try that and let us know.

**Comment by lxrui** [comment]
@memsharded Problem solved, thank you so much!

**Comment by memsharded** [comment]
Happy to hear that, you are welcome 🙂
