### ISSUE TITLE
Conan2 on windows does not recognize tls client certs

### ISSUE THREAD

**Issue by ccpsupport** [conan-io/conan#14332]
### What is your question?

Hi,
We are trying to use conan2 on win OS with below global.conf:

core.net.http:client_cert=('C:\Users\user\.conan2\client.cert', 'C:\Users\user\.conan2\client.key')

 and we get the following error:
Could not find the TLS certificate file, invalid path: ('C:\Users\user\.conan2\client.cert', 'C:\Users\user\.conan2\client.key'). [Remote: test_conan]

We have tested on Ubuntu and everything works fine, but we still have users which need to use conan2 on windows.

Do you have any suggestions?
Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ccpsupport 

Are you sure the path is correct? It is looking a bit weird, I would expect ``C:\Users\user\.conan2\client.cert`` and not the ``user.conan2`` part together.

**Comment by ccpsupport** [comment]
Hi, 
indeed, C:\Users\user\.conan2\client.cert is the correct path

**Comment by ccpsupport** [comment]
sorry C:\Users\user\.conan2\client.cert is correct

**Comment by ccpsupport** [comment]
copy paste is not working : C:\Users\user\.conan2\client.cert is correct

**Comment by ccpsupport** [comment]
`C:\Users\user\.conan2\client.cert`

**Comment by memsharded** [comment]
I think you need to put forward slashes and double quotes. Please try:
```
core.net.http:client_cert=("C:/Users/user/.conan2/client.cert", "C:/Users/user/.conan2/client.key")
```

**Comment by ccpsupport** [comment]
we did try with forward slash but because we were using gitbash the path was shown with small "c" instead of capital "C". With the later it works :) Thanks a lot!

**Comment by memsharded** [comment]
Happy to help! 🙂
