### ISSUE TITLE
Make conan compatible with 4-parts semver versioning

### ISSUE THREAD

**Issue by gsemet** [conan-io/conan#14333]
### What is your suggestion?

Hello. I really like semver, doing it for Conan from some times now, but in our sw production line we had issues with "hotfixes" that requires to perform urgent release in between 2 normal "normal semver life release".

Let's me give you a use case:
- I release version 1.0.0 of a given package that is used in the rest of the system.
- new dev occurs, for instance 1.0.1 is release (it is just a bugfix, for we update PATCH)
- new dev again, 1.0.2, and then 1.1.0 when a new feature has been integration
- so far so good, everybody is happy.
- now, we see during our validation campaign (that can takes weeks to be executed), that there is a blocking bug on 1.0.0. It may or may not be already fixed on 1.0.1 or 1.0.2. 
- "normal" way of doing it to "force" upgrade to a new version 1.0.3.
- but we need to have the option to say "no, I do not want to risk introducting regression by 1.0.1 or 1.0.2" (that may fix some bugs or just update the doc, or change something in the CI, or fix a bug that is not related to the validation)
- in this case we need to release 1.0.1.1 to say it is between 1.0.1 and 1.0.2, it is short lived, only to finish the validation, everything will of course be updated to 1.0.3 for the next "official" release

What I do today is increase my PATCH by 10 (1.0.0, 1.0.10, 1.0.20,...) but I only have 9 rooms for urgent releases. So far we only used it once, but I really would like to see with you if this would be something feasible with conan.

For me, these "4-parts" semver packages is not the normal way of doing semver, they should be most of the time ignored by conan, but do not fail if during a release we force to use a 1.0.0.1 instead of a semver version.

What do you think of my use case? Any other real life experience?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gsemet 

I am not sure if I understand your issue.

Conan 2.0 supports N-parts semver, with N as large as you want. It can perfectly implement your use case, and you can release ``1.0.1.1`` without problems, and your version ranges expressions will take that into account. Am I missing something?

**Comment by gsemet** [comment]
arg, damned, I am stuck with conan 1 for the moment (lot of package to rewrite)

**Comment by memsharded** [comment]
Yeah, prob with 1.X is that the semver implementation is external to Conan, a pip package, so there is little we can do there...

**Comment by memsharded** [comment]
Closing this as implemented in Conan 2.0, and cannot be fixed in 1.X because of the external implementation.
