### ISSUE TITLE
[question] visibility in graph

### ISSUE THREAD

**Issue by hubertba** [conan-io/conan#14348]
### What is your question?

Hi.

I have a question regarding the visibility in the graph.
I have created a small decency chain

component -> sub_component -> sub_sub_component

I require sub_sub_component from sub_component and I toggle visibility=True or visibility=False
If I require sub_component in component and generate the html graph with the command

conan graph info . -f html > info.html

I expect that if visibility=True I will be able to see the depenecy and if visibility=False I will not see the depency in the html file.
But this is not true. 

If I output the json the I see that the visibilty changes from true to false but the html always displays it.

Is this the intended behaviour? 
can I somehow output only visible depencies?
 

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hubertba 

This is intended behavior, yes.
The graph of dependencies is always complete for the recipes. The ``visible`` trait is a trait for the propagation of binary/package information down the graph, but it doesn't mean that the dependency graph can drop the non-visible dependency.

The ``--format=html`` current output does not contain at the moment any way to represent only the visible part of the graph. It is a doable feature, but it sounds quite large effort for a relatively minor UX improvement, so I think it is unlikely to be prioritized.

**Comment by hubertba** [comment]
Thank you very much for the clarification

**Comment by memsharded** [comment]
> Thank you very much for the clarification

You are welcome.

If that information becomes very necessary to you, please let us know, re-open the issue or create a new one, thanks!
