### ISSUE TITLE
[question] Difference between sources and download download_caches?

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14344]
### What is your question?

Could somebody please explain me the difference between the two `download_cache` settings? There's one for "sources" and one for "downloads" but it's not very well documented which cache is used for what. I have stuff in both caches but because the filename is obscured I don't really know what the files are.

```
core.download:download_cache: Define path to a file download cache
core.sources:download_cache: Folder to store the sources backup
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
- ``core.download:download_cache`` is for caching Conan internal artifacts download like ``conan_package.tgz`` coming from a Conan server
- ``core.sources:download_cache`` is for caching the sources downloaded in the recipes with the ``download(self, url..`` and ``get(self, url, ...`` when they provide the ``sha256`` checksum

**Comment by fschoenm** [comment]
@memsharded Thanks for the reply, I guess the source cache makes sense now.

I don't quite understand the artifact download cache. Aren't the `conan_package.tgz` extracted and stored locally? Why would those need to be cached?

**Comment by memsharded** [comment]
If you have multiple projects, each one using its own private cache via ``CONAN_HOME`` (for example in a CI server with parallel jobs), you can avoid the repeated download of the same ``conan_package.tgz`` everytime an independent cache/ci-job needs to download it to that machine.

**Comment by fschoenm** [comment]
@memsharded Oh, I see, thanks, that's very useful to know. I wish it were part of the documentation.
