### ISSUE TITLE
[question] conan install: '--build outdated' 1.x vs 2.x

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#14346]
### What is your question?

Hi,

is there somewhere an explanation in the docs why there is no 'outdated' option anymore for '--build'/'-b' for the conan install command in conan 2.x?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
The ``outdated`` option doesn't make sense anymore in Conan 1.X with ``revisions`` enabled. The moment revisions are enabled, it is impossible to have the binaries ``outdated`` with respect to the recipe. As ``revisions`` are mandatory in 2.0, the ``outdated`` option has been dropped in 2.0, as it no longer makes sense.
