### ISSUE TITLE
[question] How to use CONAN_LIB_DIRS_x in Conan 2.0

### ISSUE THREAD

**Issue by ThoSe1990** [conan-io/conan#14359]
Hi there, 

In Conan 1.x I used the conan created variable `CONAN_LIB_DIRS_x` to access the lib directory from my packages. I need this to install the libraries during a release process. 

In Conan 2.0 I noticed in `x-config.cmake`
```
set(x_VERSION_STRING "1.2.3.4")
set(x_INCLUDE_DIRS ${x_INCLUDE_DIRS_RELEASE} )
set(x_INCLUDE_DIR ${x_INCLUDE_DIRS_RELEASE} )
set(x_LIBRARIES ${x_LIBRARIES_RELEASE} )
set(x_DEFINITIONS ${x_DEFINITIONS_RELEASE} )
```

But I don't find a simple path to my lib directory anymore. Whats the easiest way here to access the lib directory, or do I need to add something in my recipe `conanfile.py`? 

Thanks in advance. 
Best Thomas

**Comment by memsharded** [comment]
Hi @ThoSe1990 

I guess this is  maybe not a 1.X - 2.0 question, but moving from the legacy ``cmake`` generator to the new ``CMakeDeps`` + ``CMakeToolchain`` one?

The core ideas of the new ``CMakeDeps`` generator is that it implements modern CMake practices, using targets, but not defining anything via variables anymore. Yes, there are some internal variables, but they are mostly implementation details, or the ones you posted above are necessary for some open source legacy libraries build scripts, but shouldn't be used for normal users consumption.

If the consumer side needs access to that information there could be 2 possible strategies:
- Extract in CMake with ``get_property()`` from the defined targets whatever can be extracted (not sure if the library directories is one thing in CMake, but it might not be possible...)
- In the consumer side ``generate()`` method, use ``self.dependencies["mydep"].cpp_info.libdirs`` and do what you want with it, like defining some variable in ``CMakeToolchain`` like ``toolchain.cache_variables["MYDEPLIBS"] = ...``


> In Conan 1.x I used the conan created variable CONAN_LIB_DIRS_x to access the lib directory from my packages. I need this to install the libraries during a release process.

The second approach is actually what ``deployers`` are doing, collecting and copying files from dependencies for a final release process, have you checked the new ``deployers``.

Please let us know if this helps.

**Comment by ThoSe1990** [comment]
Hi there, 

yes I'm trying to use the `CMakeDeps` + `CMakeToolchain`. 

I added the path to toolchain cache_variables, like you suggested. And I can see in the `CMakePresets.json` file this variable and it's value. Unfortunately I only can see this value in the `CMakePresets.json` in the package's build directory. 

When I run `conan install . -of ./build` in the consumers directory, the value isn't anymore in `./build/CMakePresets.json`. Or do I need to specify anything?

**Comment by memsharded** [comment]
> When I run conan install . -of ./build in the consumers directory, the value isn't anymore in ./build/CMakePresets.json. Or

yes, it should be there. If you have something we could reproduce, it would be worth re-opening and having a look.


Also, as a hint, using ``-of=build`` should generally not be necessary, but using the ``layout()`` like ``cmake_layout()`` makes this more automatic.

**Comment by ThoSe1990** [comment]
I'm sorry, I'm slightly confused now... 

Just for my understanding, if I use one of your examples `examples2\tutorial\creating_packages\handle_sources` and in `conanfile.py` I add a single line `tc.cache_variables["FOO"] = "some value/path here ..."` : 

```python
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout
from conan.tools.files import get


class helloRecipe(ConanFile):
    name = "hello"
    version = "1.0"

    # Optional metadata
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of hello package here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    def source(self):
        # Please, be aware that using the head of the branch instead of an immutable tag
        # or commit is not a good practice in general as the branch may change the contents
        get(self, "https://github.com/conan-io/libhello/archive/refs/heads/main.zip", 
                  strip_root=True)

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["FOO"] = "some value/path here ..."
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["hello"]

```


Then I create the package, like usual with: 
`conan create `

And later in the consumers project I have a `conanfile.txt`: 
```
[requires]
hello/1.0

[generators]
CMakeToolchain
CMakeDeps
```

Then where do I find/access my `tc.cache_variables["FOO"] = "some value/path here ..."`, because I can't find it at all. Or do I miss the entire use of `cache_variables`? 

Thanks.
Best Thomas

**Comment by memsharded** [comment]
Hi Thomas,

When you do ``tc.cache_variables["FOO"]`` in your hello ``conanfile.py``, that belongs to the ``hello`` build exclusively. The consumer ``conanfile.txt`` is completely unaware of it. Note in many cases, when you do ``conan install`` for your ``conanfile.txt``, it will be able to download and install a pre-compiled binary for it, and the ``build()`` method of ``hello`` recipe will not execute at all.

If you want to inject and define new behavior for your consumer project build, you need to:
- Convert your ``conanfile.txt`` to ``conanfile.py``: https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html
- Add in the ``generate()`` method the logic you want to inject, like adding information from dependencies in the form of CMake variables.
- ``conan install`` your ``conanfile.txt`` will create the ``conan_toolchain.cmake`` and ``CMakePresets.json`` files that contain that information.

Note that the build system of the dependency ``hello`` could be totally different to the consumer one, but it doesn't matter, the build of every package is fully encapsulated and isolated.

Please let me know if this clarifies a bit.

**Comment by ThoSe1990** [comment]
Ahh, perfect, yes this helps a lot. 
Thanks a lot for your reply. 

Best Thomas
