### ISSUE TITLE
Set authentication header in Conan

### ISSUE THREAD

**Issue by cocoza4** [conan-io/conan#14357]
### What is your question?

Hi,
I've installed Conan artifactory operated behind Cloudflare. When I do `conan install ..` I got a html response to a `Sign in ・ Cloudflare Access` page. From my understanding, I need to provide an auth header to bypass this. Ref: https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/

So, is there a way to pass auth header to the Conan artifactory?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cocoza4 

Thanks for your question.

At this moment it is not possible to inject any random headers in Conan http calls. 
But I am concerned about this, even if it would be possible, Conan might already be using auth headers to provide the auth and credentials for Artifactory itself. If you overwrite those headers, then it will be a problem. I don't know how Cloudfare works regarding this and other applications behind cloudfare, but I don't think that most client side applications will allow to inject auth headers in all http calls just to be able to connect to that server application. So maybe this is generally solved by using some client side proxies or something like that, no idea. 

Also, for advanced cases of setup of Artifactory you might want to reach out to JFrog Artifactory support, as that is a bit outside of our expertise.

**Comment by cocoza4** [comment]
Got it. Thanks
