### ISSUE TITLE
[feature]Add fuzz=True option to apply_conandata_patches()

### ISSUE THREAD

**Issue by Marwan-imverse** [conan-io/conan#14355]
### What is your suggestion?

It would be nice to have a `fuzz=True` option to the `apply_conandata_patches()` function, just like in tools.files.patch().

Currently, if I want to apply fuzzy patching to conandata patches, I have to write the following:
```python
for it in self.conan_data.get("patches", {}).get(self.version, []):
            patch(self, **it, fuzz=True)
```

It would be much simpler and easier to do so like this: ```apply_conandata_patches(self, fuzz=True)```.

Hope you think it's a good idea :) If not, I can keep using the workaround.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Marwan-imverse 

The ``patch()`` function being called by it already has the parameter, and ``apply_conandata_patches()`` passes whatever is defined in the ``conandata.yml`` as kwargs, so this should already be possible, did you try to add the ``fuzz`` argument to your ``conandata.yml``?

**Comment by Marwan-imverse** [comment]
No I didn't, how would you do that? Like this?
```
"1.0.0":
- base_path: "my_path"
  patch_file: "mypatch.diff"
  fuzz: "True"
```

**Comment by memsharded** [comment]
Yeah, something like that, but I think ``yaml`` allows to do ``fuzz: true`` without quoting for true boolean values.

**Comment by Marwan-imverse** [comment]
Didn't need to use this finally. Didn't have the chance to try it.

Don't know if I should keep this issue open...

**Comment by memsharded** [comment]
No problem, we can close it, it can be re-opened or create a new ticket if necessary. Thanks.
