### ISSUE TITLE
[question] How to remove "dirty" folders from cache?

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14360]
### What is your question?

From developing a package, I have all these folders in my Conan cache:

```
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:21:46 2023 cudnn057c1d57fac1a
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:51:44 2023 cudnn12a30acd76270
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:32:58 2023 cudnn19d0b61640574
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:26:00 2023 cudnn1a14e5853faf9
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:22:24 2023 cudnn28bf284881423
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:48:26 2023 cudnn308f63292f313
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:17:21 2023 cudnn43caf77c69514
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:08:07 2023 cudnn4d92ee0132d3f
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:20:06 2023 cudnn53240c5ed796e
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:21:28 2023 cudnn585d600af8f96
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:25:45 2023 cudnn5f8b5e3044f8b
drwxrwxr-x fschoenm fschoenm 4.0 KB Thu Jul 13 13:45:49 2023 cudnn5fcfc007e95ba
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:21:13 2023 cudnn6b3e6d3ad179a
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:57:10 2023 cudnn741f933530a32
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:20:51 2023 cudnn7d3ca56b33038
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:25:05 2023 cudnn837466905bfb2
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:43:21 2023 cudnn997430b0d40c5
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:12:39 2023 cudnn9fe0ca0da1368
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:50:59 2023 cudnnac3eac2228b0d
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:44:33 2023 cudnnadc02669bab89
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:27:54 2023 cudnnbac021edc8ee6
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:16:41 2023 cudnnbb3a7d4e8c20d
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:20:50 2023 cudnnd5fb639a54fff
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:24:32 2023 cudnndbe32fc2d5fe8
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:18:16 2023 cudnndfa8d8c1738e9
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 16:47:20 2023 cudnne280428d1e4cc
drwxrwxr-x fschoenm fschoenm 4.0 KB Tue Jun  6 14:19:16 2023 cudnnedd0427c28138
```

`conan list` only shows one revision and one package though:

```
$ conan list 'cudnn#*:*'
  cudnn
    cudnn/8.6.0@sdk/stable
      revisions
        3fc1c7b18d4440163f1ec2bf79e5bcae (2023-06-06 14:57:42 UTC)
          packages
            893dc7ded1d8de13b3857a60f3eb01fe24ee9422
              info
                settings
                  arch: x86_64
                  os: Linux
                  os.glibc: 2.31
                requires
                  cuda/11.Y.Z@sdk/stable
$ conan cache path cudnn/8.6.0@sdk/stable#3fc1c7b18d4440163f1ec2bf79e5bcae:893dc7ded1d8de13b3857a60f3eb01fe24ee9422
/home/fschoenm/.conan2/p/b/cudnn5fcfc007e95ba/p
```

What all but one folders have in common is that they contain `b.dirty` and/or `p.dirty` files. However, because they don't appear in `conan list`, I'm not sure how I can remove those dirty folders from my system? They take a lot of disk space (almost 50 GB in my case).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fschoenm 

Those seems to be orphan temporary "build" folders that never succeeded and were not converted to full "package revisions", so they are not indexed as such, and Conan is mostly unawere of them. They are not automatically removed because they would be quite important to be able to inspect and potentially debug build issues.

I think we need to add these orphan build folders to the ``conan cache clean`` command.

**Comment by memsharded** [comment]
Uhm, it seems ``conan cache clean`` might already be implementing this use case. Have you tried it?

**Comment by fschoenm** [comment]
@memsharded That'd be nice. I assumed so but I didn't want to manually work in the Conan cache. 

I even think those folders should be removed automatically after a while (similar to how the [git garbage collection](https://git-scm.com/docs/git-gc) works for example). While they may be interesting to debug build problems, I don't think they're very useful after a few days or weeks. And I'd prefer to not have to regularly remember calling a cleanup command.

**Comment by fschoenm** [comment]
> Uhm, it seems `conan cache clean` might already be implementing this use case. Have you tried it?

Which option is that? I tried `conan cache clean -b 'cudnn'` but it didn't do anything.

**Comment by memsharded** [comment]
Either ``conan cache clean`` will clean everything, or including the ``conan cache clean -b -t``

**Comment by fschoenm** [comment]
Hm, I guess those are "temporary" folders. I didn't even know what that is ... 🤷‍♂️

**Comment by memsharded** [comment]
Yes, yes, that ``-t`` means temporary: https://docs.conan.io/2/reference/commands/cache.html#conan-cache-clean or ``conan cache clean -h``

**Comment by fschoenm** [comment]
Thanks, this seemed to work.

Automatic cleanup would be nice but I can handle that for now.
