### ISSUE TITLE
[question] inspect in ConanAPI V2

### ISSUE THREAD

**Issue by Tricksam** [conan-io/conan#14369]
### What is your question?

Hi, I was using conan api to upload and install Conan packages with Artifactory. 
In the past I was using Conan 1.51.0 for that which has the inspect function to have an easy access on the version and other information from the conanfile.
Now that I want to upgrade on Conan v2, I struggle to find either the inspect or equivalent function in the ConanAPI from v2. Is their any?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tricksam 

You can find the ``inspect`` in this part of the new 2.0 API: https://github.com/conan-io/conan/blob/86bdc2143566a3028759040e2516d8f785af0367/conan/api/subapi/local.py#L107
