### ISSUE TITLE
[feature] Ability to hide host or build dependencies from conan graph info output

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#14365]
### What is your suggestion?

When executing:

```
conan graph info --requires mylib/x.y.z -f html > mylib.html
```

The resulting graph can be very difficult to view when there are a lot of upstream dependencies of `mylib`, and each has a lot of build requirements. These, understandably do not resolve to common versions (as they don't influence each other) in the same way that host requirements do, and so the tree can become very cluttered and difficult to navigate/reason about.

It would be useful to be able to hide the build dependencies from such a tree in order to be able to understand the host dependencies better. There may also be a use case here for being able to hide host dependencies to better understand the build dependencies of the tree, though one doesn't immediately jump out at me.

Something like:

```
conan graph info --requires mylib/x.y.z --exclude-build-deps -f html > mylib.html
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I think this kind of improvement makes sense, and I have been wanting to improve the html output of the graph. Only problem, it is not that critical, so we haven't had time yet to prioritize it.

**Comment by samuel-emrys** [comment]
Hi @memsharded just wondering how this is tracking in terms of priority. Our graph is quite large and this would be a big ux improvement.

**Comment by memsharded** [comment]
> Hi @memsharded just wondering how this is tracking in terms of priority. Our graph is quite large and this would be a big ux improvement.

Sorry, it didn't get enough priority yet. One of the reasons is that we want to do a full revamp of the html graph output, so we don't want to add new features that will need re-building soon. But also, not enough priority (resources) yet, compared with ConanCenter upgrade efforts and other critical features and bugfixes. I hope this can be prioritized in the following releases, but still a bit uncertain.

**Comment by samuel-emrys** [comment]
No problems - just wanted to make sure this hadn't dropped out of consideration given that it hasn't been assigned a milestone, which I've noticed you seem to use to evaluate implementation :)

**Comment by samuel-emrys** [comment]
Closed by https://github.com/conan-io/conan/pull/15846

**Comment by memsharded** [comment]
Thanks for tracking this @samuel-emrys !
