### ISSUE TITLE
[question] what is the equivalent in conan 2 for conan build -c

### ISSUE THREAD

**Issue by Marwan-imverse** [conan-io/conan#14375]
### What is your question?

The way we have our build system setup is to either use `conan build` to automatically install, configure, build and test, or only `conan build -c` to install and configure (setting up cmake variables to allow manual external build) and then do local dev and builds manually.

Is there a way to just run the configure step with conan 2.X?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Marwan-imverse 

The equivalent in Conan 2 would be not calling ``conan build``, but just ``cmake --presets conan-xxxx``. The idea is that the result should be identical to run ``conan build -c``, this is why the build configuration logic has been moved to the ``generate()`` method and the ``CMakeToolchain``

**Comment by Marwan-imverse** [comment]
shouldn't I at least call `conan install` first? How do I know what to use in `conan-xxx`? Is it `conan-debug` and `conan-release`? What folder should I run the `cmake` command in? 

So should I be setting all `CMakeToolchain` and `CMakeDeps` stuff in `generate()`?

**Comment by memsharded** [comment]
Yes, ``conan install`` goes first, sure, that doesn't happen automatically, and it is needed to generate the needed files.

The ``cmake`` command would be the standard one, in the folder that you have the ``CMakeLists.txt`` of your project, Conan would have generated there the CMakeUserPresets.json. It will be ``conan-default`` for multi-config systems like Visual Studio, and ``conan-debug``/``conan-release`` for single-config systems.

Doing ``generators = "CMakeToolchain", "CMakeDeps"`` can be enough for cases that don't need any customization. If you need customization, then yes, the ``generate()`` method is the right place for that.

**Comment by Marwan-imverse** [comment]
actually `conan install` was enough. I had a manually generated CMakePresets.json file I was using for conan 1. By removing it, Visual Studio automatically uses the toolchain files generated by conan 2.

I think with this, my port to conan 2 is finally finished :)

Thanks for all the support in the past couple weeks @memsharded

**Comment by memsharded** [comment]
> I think with this, my port to conan 2 is finally finished :)

Great to hear that! 🎉 

You are welcome, happy to help :)
