### ISSUE TITLE
[question] package internal dependencies

### ISSUE THREAD

**Issue by Tobulus** [conan-io/conan#14379]
### What is your question?

Hi,

Assume a packages A containing a lib, binary and test-binary. It requires a package B which is only used by the binary and test-binary, not the lib. So the dependency is not relevant for a consumer.

Now if I define in the `package_info()` only the lib of package A as a component Conan will complain, that there are dependencies not used by any component.

In Conan 1.x this could be circumvented with the "private" attribute. How should i treat this in 2.x? A workaround is of course to define the binary as a component but shouldn't be required?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tobulus 

> Assume a packages A containing a lib, binary and test-binary. It requires a package B which is only used by the binary and test-binary, not the lib. So the dependency is not relevant for a consumer.

That is not completely true. The consumer of the A package binary still needs the dependency of B. A clear example is if B is a shared library, you will need it to be able to run A binary, so very relevant for the consumer.

> Now if I define in the package_info() only the lib of package A as a component Conan will complain, that there are dependencies not used by any component.

Components are not really intended for binaries, but only for libraries. Because the definition of components and ``cpp_info`` is mostly ``includedirs``, ``libs``, ``libdirs``, etc, which is library inclusion and linking information. Binaries information goes via environment variables. So defining components in this package A probably won't help much.


> In Conan 1.x this could be circumvented with the "private" attribute. How should i treat this in 2.x? A workaround is of course to define the binary as a component but shouldn't be required?

You'd need to clarify further the issue, because as commented above, it is not possible to make this private, if consumers will want to use the package A binary, because it is really not a private dependency.

**Comment by Tobulus** [comment]
In our case we are mainly cross-compiling and such a package typically contains a binary, which will be a process running in the ARM target and a lib to communicate with the binary/process.

So the binary will only be deployed to a Linux image, not used by a consumer project.

```
class ModuleConan(ConanFile):

    def requirements(self):
        self.requires("A/[>=1.0.0 <2.0.0]")
        self.requires("B/[>=4.0.0 <5.0.0]")
        self.requires("C/[>=1.0.0 <2.0.0]")

    def package_info(self):
        self.cpp_info.components["lib"].libs = ["lib-foobar"]
        self.cpp_info.components["lib"].requires = ["A::A-lib", "B::whatever"]

 

        # TODO workaround
        self.cpp_info.components["proc"].libs = []
        self.cpp_info.components["proc"].requires = ["C::C-lib"]
```

Without the workaround this will fail with "ERROR: Required package 'C' not in component 'requires'".

So how should I correctly handle this?

**Comment by memsharded** [comment]
What you are suggesting does not seem a workaround, but it sounds like the correct solution. Your binary executable depends on ``C``, and that ``components["proc"].requires = ["C::C-lib"]`` is modeling exactly that. 

There is always a consumer project, when you are doing a ``conan install`` of your ``ModuleConan`` package, the consumer is the ``cli``, but there is a consumer. And still whoever wants to run your ``proc`` binary might need the ``C`` library to run, for example if C is a shared library. The line ``components["proc"].requires = ["C::C-lib"]`` express that your binary links with the library, which is exactly what is happening, so it looks good.

**Comment by Tobulus** [comment]
From the statement at the top ...
> Components are not really intended for binaries, but only for libraries. Because the definition of components and cpp_info is mostly includedirs, libs, libdirs, etc, which is library inclusion and linking information.

 ... I thought what I'm doing is a workaround?

> There is always a consumer project, when you are doing a conan install of your ModuleConan package, the consumer is the cli, but there is a consumer. And still whoever wants to run your proc binary might need the C library to run, for example if C is a shared library.

If I do a `conan install` in order to generate e.g. CMake integrations for another project to build, the "proc" component is not used by the consuming project, because only the lib is required for linking/headers.

If I do a `conan install -d my_deployer` I'm basically extracting my package so the component info for "proc" seems redundant.

Sorry, maybe my understanding of the internals is just to shallow. It's just that with Conan 1.x I could add the "private" attribute to the requires block and could stay away from defining the "proc" component.

**Comment by memsharded** [comment]
> Components are not really intended for binaries, but only for libraries. Because the definition of components and cpp_info is mostly includedirs, libs, libdirs, etc, which is library inclusion and linking information.

Well, the component ``proc`` you are defining is quite pointless, as it cannot be "linked" separately, as it is an executable. This is what I meant. In this case it is important to define the "consumption" of components from the requirements so Conan knows that LibC is being used by the package.

> If I do a conan install -d my_deployer I'm basically extracting my package so the component info for "proc" seems redundant.

It could be relevant for example to be able to retrieve the shared libraries that ``proc`` is using, to deploy them together with the ``proc`` binary if it was dynamically linked with ``libC``.

> It's just that with Conan 1.x I could add the "private" attribute to the requires block and could stay away from defining the "proc" component.

The ``private`` in Conan 1.X has been discouraged for years, it was a very early thing that should only be used in extreme cases, it has too many rough edges and problems. The right solution is to define that ``proc`` depends on that component of ``LibC``, that is the right modeling of the dependencies.

**Comment by Tobulus** [comment]
Thanks!
