### ISSUE TITLE
[question] Unclear package requirements influencing the package ID

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14388]
### What is your question?

What is the difference between those two packages? 

```
$ conan list -r bdc 'fast-dds:*'
bdc
  fast-dds
    fast-dds/2.10.1
      revisions
        41c9359faf3149a48652b3d049a2883a (2023-07-14 17:48:38 UTC)
          packages
            3dc3cc374e4fa36c914571c98c2553ef230cf68a
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: gcc
                  compiler.libcxx: libstdc++11
                  compiler.version: 10
                  os: Linux
                  os.glibc: 2.35
                options
                  fPIC: True
                  shared: False
                  with_ssl: False
                requires
                  asio/1.28.0#83b60467ba4e3487d61a29a722166a0b:da39a3ee5e6b4b0d3255bfef95601890afd80709
                  fast-cdr/1.0.Z
                  foonathan-memory/0.7.Z
                  tinyxml2/9.0.Z
            abfd7d24576466b15b86f172652fa5819c51e96d
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: gcc
                  compiler.libcxx: libstdc++11
                  compiler.version: 10
                  os: Linux
                  os.glibc: 2.35
                options
                  fPIC: True
                  shared: False
                  with_ssl: False
                requires
                  asio/1.28.Z
                  fast-cdr/1.0.Z
                  foonathan-memory/0.7.Z
                  tinyxml2/9.0.Z
```

Both have the same settings, only one seems to require `asio/1.28.Z` while the other requires `asio/1.28.0#83b60467ba4e3487d61a29a722166a0b:da39a3ee5e6b4b0d3255bfef95601890afd80709`.  `83b...` is the latest revision of asio (in conancenter and in our own remote).

How can that situation happen? And what does it mean if a requirement has revision and package hashes instead of omitting them?

Also: Why do some requirements have incomplete version information (with .Z at the end)? The conanfile specifies exact version numbers for those.

Query for asio revisions/packages:
```
$ conan list -r bdc 'asio#*:*'
bdc
  asio
    asio/1.28.0
      revisions
        83b60467ba4e3487d61a29a722166a0b (2023-07-28 12:57:42 UTC)
          packages
            da39a3ee5e6b4b0d3255bfef95601890afd80709
              info
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fschoenm 

Thanks very much for reporting this.
I think this is the result of the evolution of ConanCenter recipes, and binaries created in different times (and probably different days).

The ``asio`` got `` package_type = "header-library"`` defined the 10th of July. Defining a package type has implications on the binaries that consume them, as by default they have an effect on the consuming binary of ``full_mode``, that means they hash the full ``asio/1.28.0#83b60467ba4e3487d61a29a722166a0b:da39a3ee5e6b4b0d3255bfef95601890afd80709`` into the consuming binary. The ``asio/1.28.Z`` is the ``minor_mode`` that happens when a static library links another static library, as it is much safer to assume binary compatibility and not requiring a re-build.

I have been trying to reproduce, and building now ``fast-dds`` will always get the ``full_mode``, with the full asio reference, for all cases. I'd recommend doing a small edit in your conanfile.py that will create a new recipe revision and rebuild all binaries. I will try to do the same for ConanCenter.

**Comment by fschoenm** [comment]
Thanks @memsharded, I spent almost have a day trying to figure out why this wasn't working anymore in our CI system. 

Is there a way Conan could help in the future? This is almost impossible to understand without a very deep understanding and I couldn't figure it out.  

We're actually using the official asio and fast-dds packages. We just store our own prebuilt packages.

**Comment by memsharded** [comment]
> Is there a way Conan could help in the future? This is almost impossible to understand without a very deep understanding and I couldn't figure it out.

> We're actually using the official asio and fast-dds packages. We just store our own prebuilt packages.

We are actually recommending for production usage for this use case to work with a fork of ``conan-center-index`` and create your own pre-built binaries from there, not from the live recipes in ConanCenter. This has some important advantages:
- Full control and reproducibility, no matter what is changed upstream in ConanCenter, you are totally robust against any changes, and can perfectly re-create your packages
- You can apply your own patches, bump or downgrade versions, etc, anytime, and have instant binaries, no need to wait to ConanCenter reviewing and merging the changes
- You can still keep getting the changes/improvements from upstream periodically, but in a controlled way. You merge the upstream, then you can review the diff if you want, create your binaries, put them in a secondary server repo and test your products against the new binaries. If everything is good, you can copy the binaries to your main server repo, but if something breaks, you can investigate. 

There are already quite a few Conan users using this approach successfully, and we are indeed investigating ways and tools that could help further automating this flow (at the moment it is needed some user scripts that will iterate the references you want and create + upload them)

**Comment by fschoenm** [comment]
Thanks for the recommendation, maybe we should start doing that.
