### ISSUE TITLE
[question] how to create different package id in cross compilation

### ISSUE THREAD

**Issue by stefaneicher** [conan-io/conan#14384]
### What is your question?

HI we have some profiles files:

clang-linux-debug
clang-linux-release
gcc-cortex-m4-debug
gcc-cortex-m4-release
iar-cortex-m4-debug

that internally defines also compiler flags:
Example
""""
toolchain=/opt/arm-gcc
target_host=arm-none-eabi
cc_compiler=gcc
cxx_compiler=g++
base_c_flags = -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard --sysroot=$toolchain -mthumb -mabi=aapcs -Wall -ffunction-sections -fdata-sections -fno-strict-aliasing -fno-builtin -ffast-math -Werror
base_ld_flags = -mthumb -mabi=aapcs -Wl,--gc-sections -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard  -specs=nano.specs -specs=nosys.specs -specs=rdimon.specs -lc -lrdimon
base_asm_flags = -mcpu=cortex-m4

c_flags=$base_c_flags -Og
ld_flags=$base_ld_flags -Og

[settings]
build_type=Debug
compiler=gcc
compiler.version=10.3
compiler.libcxx=libstdc++11
os_build=Linux
arch_build=x86_64
os=baremetal
arch=armv7

[env]
PATH                    =[$toolchain/bin]
AR                      = $target_host-ar
CC                      = $target_host-$cc_compiler
CXX                     = $target_host-$cxx_compiler
OBJCOPY                 = $target_host-objcopy
OBJDUMP                 = $target_host-objdump
SIZE                    = $target_host-size   
DEBUGGER                = $target_host-gdb    
CPPFILT                 = $target_host-c++filt
LD                      = $target_host-ld
CONAN_CMAKE_SYSTEM_NAME = "Generic"
CONAN_C_COMPILER        = $cc_compiler
CONAN_CXX_COMPILER      = $cxx_compiler
MY_TOOL_FORMATTER  = clang-format
MY_TOOL_COVERAGE   = llvm-cov
MY_TOOL_PROFDATA   = llvm-profdata
MY_CMAKE_SYSTEM_PROCESSOR = arm
MY_CMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
CFLAGS            = $c_flags
CXXFLAGS          = $c_flags
ASMFLAGS          = $base_asm_flags
LDFLAGS           = $ld_flags
CONAN_C_FLAGS     = $c_flags
CONAN_CXX_FLAGS   = $c_flags

""""

I would like those flags and thus the [env] to be included in the package_id. Meaning a change in base_c_flags would create a different package id.

What is the idiomatic way to do this?
overwrite def pacakge_id order change the package info?

I use conan 1.60

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by stefaneicher** [comment]
What I found in the internet:
https://sourcegraph.com/search?q=context:global+self.env_info.CFLAGS&patternType=standard&sm=1&groupBy=repo
https://sourcegraph.com/github.com/freckled-dev/fubble/-/blob/scripts/conan_toolchains/linux_armv7/conanfile.py

**Comment by memsharded** [comment]
Hi @stefaneicher 

When you want something to affect the ``package_id``, there are different mechanisms:

- Define a new custom ``setting`` in your ``settings.yml`` and use it. This would be a project-wide abstraction over a set of flags/configurations
- Define a new package ``option`` in your recipes and use it. This would be a per-package abstraction
- Use the ``conf`` mechanism:
   - You have ``tools.build:cxxflags``, built-in, to define compiler flags, as well as others.
   - You can also define your own ``user.xxx:conf`` to customize things the way you want
   - You can use the ``tools.info.package_id:confs`` (Conan 2.0) to define what other ``confs`` make part of the ``package_id``

It seems in your case that you might want to create some high-level abstractions via custom ``settings``, like ``mycortex``, that encapsulate a full configuration. It can be a baremetal subsetting, or something like that.

Also, I suggest to drop ``[env]`` and start using ``[buildenv]`` as soon as possible, to be Conan 2.0-ready

**Comment by stefaneicher** [comment]
HI @memsharded ,
Thanks for your answer.
I will try to use options, which is the cleanest and most idiomatic conan way.
Regards Stefan

**Comment by memsharded** [comment]
Sounds good.

If at some point you find that the same option is being added to every package, then consider that it could be a setting instead.
Thanks for the feedback!

**Comment by stefaneicher** [comment]
@memsharded I use a "base package" that is used by all components. I think this is even better than changing the settings and getting the same benefit of changing in one place.
By changing the settings, I make the conan setting project dependent which, I conceptually think is worse. 

I hope I could make this base open-source once I have time.

Use of Base:

class XYZ(ConanFile):
    name = "xyz"
    python_requires = "platform_base/1.1.5@disroop/release"
    python_requires_extend = "platform_base.Base"
    
Base
