### ISSUE TITLE
[question] using Autotools for plain Makefiles

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#14385]
### What is your question?

Hi,

I think my previous question ticket fell through the notifications, so I gently open a new one here. :)
https://github.com/conan-io/conan/issues/14246

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tbsuht 

There is work happening to define a new pure Make based ``MakeDeps`` in: https://github.com/conan-io/conan/pull/14133

Please track that PR, feedback welcome for the ``MakeDeps``!

**Comment by tbsuht** [comment]
@memsharded Not really sure, but I don't have dependencies in my project. Is this related to my problem?

The Makefile which is reported missing, is part of the project itself.

**Comment by memsharded** [comment]
Yes, it is related. The ``MakeDeps`` is to generate information for dependencies. 
To generate the self (settings/options) configuration in the build, that needs to be done with the future, not yet implemented ``MakeToolchain``. In any case, if you don't have dependencies, then everything is way simpler, it is likely that you can map your settings to your own ``toolchain.mak`` file in your ``generate()`` method.
