### ISSUE TITLE
[bug] Deployers "full_deploy" and "direct_deploy" generates shell scripts conanbuild.sh, conanbuild.bat, conanbuild.ps1 with absolute paths

### ISSUE THREAD

**Issue by bladan** [conan-io/conan#14390]
### Environment details

* Operating System+version: Linux 72b1cf065f0e 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux
* Compiler+version: gcc version 8.3.0 (Debian 8.3.0-6)
* Conan version: Conan version 2.0.8
* Python version: Python 3.7.3

According to the documentation about the deployers (https://docs.conan.io/2.0/reference/extensions/deployers.html) the provided `full_deploy` should produce a self-contained as it states _"can achieve a fully self-contained project, including all the artifacts, binaries, and build files"_.

But it looks like the the generated shell scripts such as conanbuild.sh, conanbuild.bat, conanbuild.ps1, conanrun.sh, conanrun.bat, conanrun.ps1 and their child-scripts contain absolute paths. This makes it impossible to load environment variables on other machines using the deployed artifacts.

### Steps to reproduce

1. `git clone https://github.com/conan-io/examples2.git`
2. `cd examples2/tutorial/consuming_packages/conanfile_py`
3. `conan install . --output-folder build --build=missing  --deployer=full_deploy`
4. `more ./build/conanbuild.sh`
5. `more ./build/conanbuildenv-release-x86_64.sh`

### Logs

```
root@72b1cf065f0e:~/examples2/tutorial/consuming_packages/conanfile_py# conan install . --output-folder build --build=missing  --deployer=full_deploy

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.py: /root/examples2/tutorial/consuming_packages/conanfile_py/conanfile.py
Requirements
    zlib/1.2.11#ffa77daf83a57094149707928bdce823 - Cache
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb - Cache

======== Computing necessary packages ========
Requirements
    zlib/1.2.11#ffa77daf83a57094149707928bdce823:897e6fde718e72637d92b0b8ed929893a1976238#e907ac2d9dd18a29f4f4832f407577da - Cache
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb:63fead0844576fc02943e16909f08fcdddd6f44b#f4f5c7faaf81d64dc64f1b1f9c55518b - Cache

======== Installing packages ========
cmake/3.22.6: Already installed! (1 of 2)
cmake/3.22.6: Appending PATH environment variable: /root/.conan2/p/cmake5a09891eb5f57/p/bin
zlib/1.2.11: Already installed! (2 of 2)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'env_info' used in: cmake/3.22.6
WARN: deprecated:     'cpp_info.names' used in: zlib/1.2.11

======== Finalizing install (deploy, generators) ========
conanfile.py: Conan built-in full deployer to /root/examples2/tutorial/consuming_packages/conanfile_py/build
conanfile.py: Writing generators to /root/examples2/tutorial/consuming_packages/conanfile_py/build
conanfile.py: Generator 'CMakeDeps' calling 'generate()'
conanfile.py: Generator 'CMakeToolchain' calling 'generate()'
conanfile.py: CMakeToolchain generated: conan_toolchain.cmake
conanfile.py: Preset 'conan-release' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-release' if using CMake>=3.23
conanfile.py: If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/root/examples2/tutorial/consuming_packages/conanfile_py/build/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
conanfile.py: CMakeToolchain generated: CMakePresets.json
conanfile.py: CMakeToolchain generated: ../CMakeUserPresets.json
conanfile.py: Generating aggregated env files
conanfile.py: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
root@72b1cf065f0e:~/examples2/tutorial/consuming_packages/conanfile_py# more ./build/conanbuild.sh
. "/root/examples2/tutorial/consuming_packages/conanfile_py/build/conanbuildenv-release-x86_64.sh"
root@72b1cf065f0e:~/examples2/tutorial/consuming_packages/conanfile_py# more ./build/conanbuildenv-release-x86_64.sh
script_folder="/root/examples2/tutorial/consuming_packages/conanfile_py/build"
echo "echo Restoring environment" > "$script_folder/deactivate_conanbuildenv-release-x86_64.sh"
for v in PATH
do
    is_defined="true"
    value=$(printenv $v) || is_defined="" || true
    if [ -n "$value" ] || [ -n "$is_defined" ]
    then
        echo export "$v='$value'" >> "$script_folder/deactivate_conanbuildenv-release-x86_64.sh"
    else
        echo unset $v >> "$script_folder/deactivate_conanbuildenv-release-x86_64.sh"
    fi
done


export PATH="$script_folder/full_deploy/build/cmake/3.22.6/x86_64/bin:$PATH"
root@72b1cf065f0e:~/examples2/tutorial/consuming_packages/conanfile_py#
```

**Comment by memsharded** [comment]
Hi @bladan 

Thanks for your report.

Please check the note in the docs: https://docs.conan.io/2/examples/extensions/deployers/dev/development_deploy.html that says:

> The environment scripts in Linux and OSX are not relocatable, because they contain absolute paths and the sh shell [does not have any way to provide access to the current script directory for sourced files](https://stackoverflow.com/questions/29832037/how-to-get-script-directory-in-posix-sh/29835459#29835459).

**Comment by bladan** [comment]
Aha, thanks for pointing me to this additional documentation.

This brought me to reproduce the issue on Windows with Command Line Batch (.bat) and Powershell (.ps1):
`conan install . --output-folder build --build=missing   --conf tools.env.virtualenv:powershell=True --deployer=full_deploy`

Indeed, the *.bat seems to be relative.

But at least on *.ps1 i can still see an absolute path:

`gc .\build\conanbuildenv-release-x86_64.ps1`
```
....
$env:PATH="D:\GIT\examples2\tutorial\consuming_packages\conanfile_py\build\full_deploy\build\cmake\3.22.6\x86_64\bin;$env:PATH"
```
Any proposal to "patch" those absolute *.sh scripts on OX and UNIX in Python without using `sed` on the commandline on our CI?

**Comment by memsharded** [comment]
It seems you are right, the ``ps1`` call to ``relativize_generated_file()`` is missing. 
This is likely because we don't have that powershell knowledge, and just the ``.bat`` was implemented in the first iteration.

Do you know how would it look like? What is the placeholder for ps1 if any? In .bat it is ``content = relativize_generated_file(content, self._conanfile, "%~dp0")``, is there a simple equivalent in ps1?

> Any proposal to "patch" those absolute *.sh scripts on OX and UNIX in Python without using sed on the commandline on our CI?

I cannot imagine a simpler alternative than ``sed``, why are you looking for something else?

**Comment by bladan** [comment]
> What is the placeholder for ps1 if any?

How about using `$PSScriptRoot` in `conanbuildenv-release-x86_64.ps1` as it is already used in `conanbuild.ps1`?

> I cannot imagine a simpler alternative than sed, why are you looking for something else?
I thought about generation of an adapted conanbuild.sh (such as targeting bash without the limitations mentioned in the stackoverflow post) using a custom deployer as described in https://docs.conan.io/2.0/reference/extensions/deployers.html#custom-deployers

**Comment by memsharded** [comment]
That is true, I didn't recall we had that ``PSScriptRoot`` in Conan already, proposing #14391 to fix it.

**Comment by bladan** [comment]
> That is true, I didn't recall we had that PSScriptRoot in Conan already, proposing https://github.com/conan-io/conan/pull/14391 to fix it.

Thanks, I tested https://github.com/conan-io/conan/pull/14391 and it work for me. Please merge it in.

> I cannot imagine a simpler alternative than sed, why are you looking for something else?

> `sed -i 's,{old_folder},{new_folder},g' *`

Depending on the build job, our CI does either now the `old_older` or `new_folder`, but never both. We worked around the absolute paths in `.sh` script with the constraint, that the files shall always be sources in the current working directory, thus, we run following command to path the files after `conan install`:

`sed -i "s+$PWD+\$PWD+g" *.sh`

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/14391, for next 2.0.10 release

Not sure if I fully get the ``sed -i "s+$PWD+\$PWD+g" *.sh``, is it replacing the actual full path for the literal "$PWD"? The problem with PWD is that it only works when it is executed from that folder, and I think this is the reason we cannot use PWD directly in the generated files.
