### ISSUE TITLE
[feature] test_requires to be able to force/override

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan#14393]
### What is your suggestion?

ATM build_requirements like this have version conflicts
```
self.test_requires("gtest/1.13.0")
self.test_requires("rapidcheck/cci.20220514", options={"enable_gtest": True, "enable_gmock": True})
```
`ERROR: Version conflict: rapidcheck/cci.20220514->gtest/1.12.1, thing/0.0.0->gtest/1.13.0.`

I'd like to simply add `force=True`, but ATM the test_requires wrapper around requires doesn't allow that so instead I have to use `self.requires("gtest/1.13.0", force=True, test=True)`

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ignition 

There was a reason not to add ``force`` to ``test_requires``, and it is that it is dangerous as it can change the main "host" product ``requires`` requirements, and this would be certainly unwanted.

But the case for resolving conflicts among several ``test_requires`` makes sense, so lets add it, and try to warn in the documentation about the possible side effects.
