### ISSUE TITLE
How does one specify an explicit order of includedirs?

### ISSUE THREAD

**Issue by justinpa-asg** [conan-io/conan#1439]
I tried the following:
```
    def package_info(self):
        self.cpp_info.includedirs = self.deps_cpp_info['MyOtherProject'].includedirs + self.cpp_info.includedirs
```
And I do not see MyOtherProject directories prepended to the list. I have header files with same name and the wrong one is found first during compile.

**Comment by memsharded** [comment]
But you don't need to accumulate the ``includedirs`` of your dependencies into your own package ``includedirs``. This is automatically managed by conan.
Conan generates aggregated info, in the correct orders. For libraries to be linked it means libraries depended by other, at the end. For include directories, direct includes appears first in the include paths to be searched, and transitive includes appear later.

I think that trying to hack the include order, so downstream consumers find sooner the include from ``MyOtherProject``, might be problematic and error prone. Is there any reason you can't put headers in a subfolder with the package name? So all includes from MyOtherProject would be included as:

```
#include "MyOtherProject/some_include.h"
```
IMHO that is the only way to robustly deal with include collisions.

**Comment by memsharded** [comment]
Also beware that they are not the same. ``self.deps_cpp_info`` contains absolute paths, because they have been processed and converted by conan, while ``self.cpp_info`` are just the user interface for input definition, so easy, relative paths, like: ``self.cpp_info.includedirs = ["inc", "include"]``. So you cannot just concat both.

**Comment by memsharded** [comment]
This ticket is obsolete, ``deps_cpp_info`` has been removed by 2.0.

Access is now by ``self.dependencies`` that can be iterated in topological order and define the order the user (consumer recipe) wants.
