### ISSUE TITLE
[question] Out-of-source recipes

### ISSUE THREAD

**Issue by andrey-zherikov** [conan-io/conan#14409]
Hi!

The context: we have a lot of packages with metadata stored in some files (like `debian/control`) so everything that conan needs is there already.
What I'm trying to do is to create an out-of-source recipe that I can use "as is" to generate conan package. The problem is how to reuse that recipe.

One of the solutions described in documentation is to use [python_requires](https://docs.conan.io/2/reference/extensions/python_requires.html). This is useful but will force me to commit the same `conanfile.py` into all (actually, hundreds) repos which I'd like to avoid.

Another solution whould be to copy recipe into current directory in `layout()` method. This approach has disadvantage: it modifies source tree.

So I'd like to come up with third solution which doesn't have those disadvantages: separate recipe from the source tree. My general idea is:
- Recipe should be able to build a package locally from the sources (local development flow).
- Recipe should export itself and all metadata that is needed to build a package (like name, version, scm info etc.).
- Recipe should be able to download correct sources and build a package from conan cache.

It seems that conan already supports this workflow through `self.folders`/`self.layout()` because [`Folders` class](https://github.com/conan-io/conan/blob/95316bb0cf43ec1716ba85dbe714864e7f6274c4/conans/model/layout.py#L35C7-L35C14) has everything needed but there is no documentation unfortunately.

So how can I achieve/implement this workflow?
Does it make sense to extent "reuse the recipe" feature beyond `python_requires` and make conan support this worflow out of the box?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @andrey-zherikov 

You can certainly reuse the same recipe to package many different libraries with a bit of parametrization (name, version, for example).

Not sure what you are missing in the docs, there are some resources there that explain the ``layout()`` and other relevant stuff:
- https://docs.conan.io/2/reference/conanfile/attributes.html#layout
- https://docs.conan.io/2/reference/conanfile/methods/layout.html

There are also some examples of packages using different layouts:
- https://docs.conan.io/2/examples/conanfile/layout.html

The use case of having the recipe separate from the source is explained in the tutorial too: https://docs.conan.io/2/tutorial/creating_packages/create_your_first_package.html


Maybe it would be good to illustrate a bit more with a concrete real layout, explaining the folders, the structure of source/repos, etc.
Also, I'd probably wouldn't discard having a simple ``conanfile.py`` in every repo, that basically delegates most of the functionality in a common shared ``python_requires``. What is the problem with that? It is very convenient, you can customize that conanfile.py in case it is needed for a specific package, it is convenient for developers (just one single ``git clone`` + ``conan install``, etc), while not having any real downsides, yes, you have a file in the repos, but that is not a problem per-se.

**Comment by andrey-zherikov** [comment]
> Maybe it would be good to illustrate a bit more with a concrete real layout, explaining the folders, the structure of source/repos, etc.

I will try to come up with an example but let me explain my use case in few words (sorry if I was unclear in my previous post).
I have two repos:
- one with a recipe
- another with package sources (we actually have a lot of these repos)

Note that there is no relative path between recipe and package source.

The first issue I faced is that conan commands do not support two paths in general: "path to recipe" and "path to package source". They accept path to recipe only and the recipe says where package source is. So my idea here is to require that current working directory (where conan command is called from) is a directory with package source. The tricky part here is to catch `cwd` before conan jumps to recipe folder and restore all paths so conan thinks it's executed from package source, not a directory with recipe. I found that `cwd` in `layout()` function is what I need so the question I have is how I can adjust folders accordingly. Can you tell me how to do this?

From high-level point of with, my recipe will:
- take all metadata from package source during local development
- export all metadata together with recipe itself during `conan export` (e.g. as `conandata.yml`) - same way as SCM info is recorded
- take all metadata from exported data if built from conan cache

Does this all make sense?

> Not sure what you are missing in the docs, there are some resources there that explain the `layout()` and other relevant stuff:
> 
> * https://docs.conan.io/2/reference/conanfile/attributes.html#layout
> * https://docs.conan.io/2/reference/conanfile/methods/layout.html

As far as I got, everything here is described in terms of subdirectories. This is not really useful in my case because there is no relative path between recipe and source tree in general: for example, recipe might be on `C:\` and package source on `D:\`.

> There are also some examples of packages using different layouts:
> 
> * https://docs.conan.io/2/examples/conanfile/layout.html

These are good examples actually but they don't match my use case:
- "[Declaring the layout when the Conanfile is inside a subfolder](https://docs.conan.io/2/examples/conanfile/layout/conanfile_in_subfolder.html)" assumes that there is a "root" dir where recipe and sources are in (different) subdirectories.
- "[Declaring the layout when creating packages for third-party libraries](https://docs.conan.io/2/examples/conanfile/layout/third_party_libraries.html)" has hard-coded path to sources (basically SCM info). In my case, I need to know where source directory is to record SCM info.
- "[Declaring the layout when we have multiple subprojects](https://docs.conan.io/2/examples/conanfile/layout/multiple_subprojects.html)" is the same as the first one - it assumes that there is a relative path between recipe and sources.
- "[Using components and editable packages](https://docs.conan.io/2/examples/conanfile/layout/editable_components.html)" has all sources next to the recipe.

> Also, I'd probably wouldn't discard having a simple `conanfile.py` in every repo, that basically delegates most of the functionality in a common shared `python_requires`. What is the problem with that? It is very convenient, you can customize that conanfile.py in case it is needed for a specific package, it is convenient for developers (just one single `git clone` + `conan install`, etc), while not having any real downsides, yes, you have a file in the repos, but that is not a problem per-se.

I'm not saying that this is a no-no. As I said, this approach requires creating a `conanfile.py` file in many many repos. Although the file itself will be simple, there is no guarantee that it will never be changed in the future (for example, migrating to conan 3, or to support new feature) and this, unfortunately, adds maintaining headache. This is a main reason I'd like to avoid this approach if possible.

**Comment by andrey-zherikov** [comment]
@memsharded , I did a quick look at conan sources and the documentation. Here are my findings:
- `export_folder` attribute is not documented in [Reference](https://docs.conan.io/2/reference/conanfile/attributes.html) page at all.
- There are `recipe_metadata_folder` and `package_metadata_folder` undocumented attributes as well but it's probably fine since they are not actually used AFAICS.
- [Attribute reference page](https://docs.conan.io/2/reference/conanfile/attributes.html) has 18 `<MISSING PAGE>` things. This seems a bug in documentation.
- [Folders and layout](https://docs.conan.io/2/reference/conanfile/attributes.html#folders-and-layout) section mentions "base directory". How can I access it?
- Looking at the source code, there are multiple "base" directories. For example: `Folders._base_source`, `Folders._base_build`. But the documentation insists that they are the same: `(a cache directory when running in the cache or the output folder when running locally)`. Is this just a placeholder for future flexibility enhancement?
- Based on a way how `Folders.source_folder` is implemented (return `self._base_source` + `self.source`), it seems that if I set `_base_source` (through `Folders.set_base_source`) then I'll achieve what I need but I'm not sure because there is a bit more generic `Folders.set_base_folders` which might be better. Is this a correct way to achieve my goal or there is a better one?

**Comment by memsharded** [comment]
Quick clarification: the ``metadata`` is a merged, but not released and not announced yet feature, pending to be documented and launched publicly. ``recipe_metadata_folder`` is not documented yet on purpose.

**Comment by memsharded** [comment]
I think the response in https://github.com/conan-io/conan/issues/12993#issuecomment-1663060070 is also relevant here. Please have a look. I think in your case the problem is not the same, because you actually want to do a copy of the sources.

It is not very clear the real problem you are trying to solve. I still think that the easiest by far is to put a ``conanfile.py`` in the repos, trying to avoid that is causing you more problems than the supposed advantages and potential problems that you are trying to avoid in the future, but in our experience are not real problems.

If you still want to do something like that, just reuse the same recipe for all packages, most likely it can be solved by defining some convention of the folders structure:

```
- conanfile.py
- repo1
    |-src
- repo2
    |-src
- repoN
    |-src
```
Then you can parameterize your recipe, do not hardcode the ``name``, but allow defining it dynamically, and then parameterize the recipe on that name (not tested code, just the idea):
```python
class Pkg(ConanFile):
    def export_sources(self):
        copy(self, "*.h", src=os.path.join(os.path.dirname(self.recipe_folder), self.name)), dst=self.export_sources_folder)

    def layout(self):
         self.folders.source = f"{self.name}/src"
```
Have you tried something like this? is this something that makes sense?

**Comment by andrey-zherikov** [comment]
We had an internal discussion within our group and we decided to have small `conanfile.py` in each repo and use `python_requires`. Thanks @memsharded for your suggestions.

**Comment by memsharded** [comment]
Thanks for the feedback @andrey-zherikov !
