### ISSUE TITLE
[question] Accessing Package variables outside of CMake

### ISSUE THREAD

**Issue by KarstenErnert** [conan-io/conan#14403]
### What is your question?

Hello everyone,

I have a Conan project that I am building on windows in a batch script as follows:

1. Conan install ...
2. cmake --preset XY
3. cmake --build --preset XY

CMake is here one of the packages that I am fetching with the conan install. How can I now get a variable with the information, where the cmake is installed, so that I can use it in this batch script? The CMake package that I am fetching has already a variable in the buildenv_info available.
The only solution I found till now is the virtualenv. 
Is the virtualenv supposed to be deprecated at some point?

Thanks in advance for the support.

BR,
Karsten

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @KarstenErnert 

In Conan 2.0 with the ``conan install`` you should already get a ``conanbuild.bat|.sh`` file. Just activating or sourcing that file is enough to activate the cmake that was tool-required.

Please have a look to the info in https://docs.conan.io/2/tutorial/consuming_packages/use_tools_as_conan_packages.html

**Comment by KarstenErnert** [comment]
Hi @memsharded 

thanks for the reply. Currently I am using Conan 1.60.2 where I could see this scripts not beeing autogenerated yet. Anyhow its good to know that this functionality exists, so that I can reuse it later once I switched to Conan 2.

**Comment by memsharded** [comment]
But the ``conanbuild.bat|.sh`` already exist in Conan 1.X. It is recommended to switch to them in Conan 1.X, so the transition to 2.0 is easier. This can be done with:
- Explicit instantiation of ``VirtualBuildEnv`` and ``VirtualRunEnv`` generators in recipes
- Defining the ``tools.env.environment:auto_use=True`` conf
