### ISSUE TITLE
[question] How can I make conan use prebuilt binaries instead of rebuilding

### ISSUE THREAD

**Issue by emnkoksal** [conan-io/conan#14408]
### What is your question?

Whatever I do, conan is always trying to rebuild required package.
Here is my case:

I have a cmake - c++ project with conanfile.py. This has one dependency, which exists in remote repo without problem. Here are the attributes of conanfile.py of the project:

**conanfile.py** (Main project)

```
class MainProjectConan(ConanFile):
    name = "mainproject"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False], "use_some": [True, False], "some_on": [True, False]}
    default_options = {"shared": False, "fPIC": True, "use_some": True, "some_on": False}
    generators = "cmake"
    requires = "mylib/3.0.1@somepath/stable"
```

Here is the properties of uploaded mylib package:

```
[settings]
    arch=x86
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++11
    compiler.version=7
    os=Linux

[requires]


[options]
    fPIC=True
    shared=False
    use_some=True

[full_settings]
    arch=x86
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++11
    compiler.version=7
    os=Linux

[full_requires]


[full_options]
    fPIC=True
    shared=False
    use_some=True

[recipe_hash]
    2585afe96ca1df87cf66c97c81a88297

[env]
    CC=i686-linux-gcc -fPIC -m32
    CXX=i686-linux-g++ -fPIC -m32
```

The structure of directories of remote repo where mylib is:

```
- 3.0.1
-- stable
--- 0
---- export
---- package
---- export/conanfile.py
---- export/conanmanifest.txt
---- package/<some_hash>/0/conan_package.tgz
```

The **only conan profile** where I run conan install (or conan create):

```
[settings]
arch=x86
arch_build=x86
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

**conanfile.py** attributes of mylib:
```

class MyLibConan(ConanFile):
    name = "mylib"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False], "use_some":[True, False]}
    default_options = {"shared": False, "fPIC": True, "use_some": True}
    generators = "cmake"
```

- The remote repo is reachable and is the only remote that conan uses

- I am trying with clean conan cache

- My conan version is 1.56 and yes, I know there is newer but I have to use this one

I run `conan install . --build never`, but still conan is trying to rebuild mylib, instead of just using prebuilt binaries which is what I need.

What I saw is that conan downloads only conanfile.py and conanmanifest.txt from export directory and starts to build using conanfile.py of mylib that is downloaded. So, it does not bother download package.

Let say that for some thing conan does not match the requested package but then

why it **does not care** about "**--build never**"? **No**, there is no "build_policy" defined in conanfile.py of mylib.

Also, if it did not match, it also would not download export/conanfile.py, isn't it? Why does conan not bother download package and start to rebuild dependency lib?

Here is conan trace:

```
{"_action": "REST_API_CALL", "duration": 0.01719522476196289, "headers": {"User-Agent": "Conan/1.56.0 (Linux 5.15.90.1-microsoft-standard-WSL2; Python 3.6.9; x86_64)"}, "method": "GET", "time": 1690842692.490418, "url": "https://url/to/mylib/3.0.1/stable/0/export/conanmanifest.txt"}
{"_action": "DOWNLOAD", "duration": 0.01921844482421875, "time": 1690842692.492429, "url": "https://url/to/mylib/3.0.1/stable/0/export/conanmanifest.txt"}
{"_action": "REST_API_CALL", "duration": 0.017600059509277344, "headers": {"User-Agent": "Conan/1.56.0 (Linux 5.15.90.1-microsoft-standard-WSL2; Python 3.6.9; x86_64)"}, "method": "GET", "time": 1690842692.510231, "url": "https://url/to/mylib/3.0.1/stable/0/export/conanfile.py"}
{"_action": "DOWNLOAD", "duration": 0.01833343505859375, "time": 1690842692.5109558, "url": "https://url/to/mylib/3.0.1/stable/0/export/conanfile.py"}
{"_action": "DOWNLOADED_RECIPE", "_id": "mylib/3.0.1@somepath/stable", "duration": 0.0646970272064209, "files": [{"md5": "8ff61aa316a3010bc3414eda9f3bd8b1", "name": "conanmanifest.txt", "path": "/root/.conan/data/mylib/3.0.1/somepath/stable/dl/export/conanmanifest.txt", "sha1": "71a400a1c37be1664f4628f3e9b065091d8b8e55"}, {"md5": "59df740363db108e43abd3e217103518", "name": "conanfile.py", "path": "/root/.conan/data/mylib/3.0.1/somepath/stable/dl/export/conanfile.py", "sha1": "80efa537a399792ed25bcc0b5ce5da29100311a8"}], "remote": "conan-some", "time": 1690842692.511219}
```

And here is the **output** of **conan install** command:

```
mylib/3.0.1@somepath/stable: Not found in local cache, looking in remotes...
mylib/3.0.1@somepath/stable: Trying with 'conan-some'...
Downloading conanmanifest.txt completed [0.06k]
Downloading conanfile.py completed [5.85k]
mylib/3.0.1@somepath/stable: Downloaded recipe revision 0
<Then here prints of configure() method of mylib::conanfile.py, and it naturally fails>
```

How can I make conan to download and use the package instead of rebuilding it?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @emnkoksal 

There is definitely something weird going on. Without a explicit ``--build=something``, Conan should never rebuild from source.

I am missing some details there, so it would be great to know:
- Can you please post the whole output of the command causing the error? Without hiding the actual errors.
- If it fails at ``configure()`` then, it is not that it is trying to rebuild. ``configure()`` is not a build-stage command, it is executed always for all recipes, and contains basic *recipe* configuration, not necessarily configuration for building from source.
- If it is failing at ``configure()`` step, it would be necessary to share the ``mylib`` dependency recipe too.

Thanks

**Comment by emnkoksal** [comment]
Thank you @memsharded !
I appreciate your comments.

That was the "problem". When it was starting to call functions of its conanfile.py, I thought it was trying to build.
But then I did not understand a thing: 
Why does it call some functions of its conanfile.py? 
What would happen if I did not upload conanfile.py to repo?
Is it possible to avoid this?

In mylib's configure(), it was looking for the version of package from a source file which would not exist when using mylib.
So now, I am also not sure what happens if we do not set "version" in conanfile.py at all.

Thank you!

**Comment by memsharded** [comment]
> Why does it call some functions of its conanfile.py?

Conan will be calling different methods depending on the stage of dependency resolution, this is how conan works. If you want to understand more about the use case for ``configure()`` you can have a look to: https://docs.conan.io/2/reference/conanfile/methods/configure.html

> What would happen if I did not upload conanfile.py to repo?

If you don't  upload the ``conanfile.py`` to a Conan server, then it will only live in your local cache. You will not be able to share the package with other developers, it will not be used in CI build, you will not be able to use it from another machine, and if you remove the cache (it is a cache, it is fine to remove it and ``conan remove * -c`` will do that), then you will need to re-create your package. It is the same as if you dont ``git push`` your source code changes, they are local in your computer copy only.

> in mylib's configure(), it was looking for the version of package from a source file which would not exist when using mylib.
So now, I am also not sure what happens if we do not set "version" in conanfile.py at all.

For a "consumer" only ``conanfile.py``, it is not necessary to have ``name`` or ``version`` at all. If you try to create a package for it, it will require both name and version and fail if not provided.

It seems you are abusing the ``configure()`` method. Looking for other packages is not something that should be done in recipes, recipes should do ``requires("something/version")``, not checking if existing. Doing any re-entrant Conan calls is explicitly forbidden in https://docs.conan.io/2/knowledge/guidelines.html, as it can cause many problems and undefined behavior.

**Comment by emnkoksal** [comment]
Actually, I do not look for other package in configure(), only was trying to find out its own version from a file. Let me explain with reduced example:

mylib's conanfile.py:

```
def configure:
    self.set_my_version(/path/to/my/version/file)
```

When building mylib, this works.
Mylib is uploaded to repo, and done.

Now let look to mainproject's conanfile.py which uses mylib:

```
class MainProjectConan(ConanFile):
    requires = "mylib"
```

Then, when conan is building mainproject, first it downloads conanfile.py of mylib and runs its configure().
However, when building mainproject, `/path/to/my/version/file` does not exist! It was valid when building mylib, but not when using it.

**Comment by memsharded** [comment]
Oh! Now it is more clear what you want to do. I think you want to use the ``set_version()`` method.

Please have a look to:
- https://docs.conan.io/2/reference/conanfile/methods/set_version.html

That allows to dynamically define the version when you do ``conan create`` a package.

For the consumer side, it is not possible to do just ``requires = "pkg"``. The right approach typical in dependency management is to use version ranges:
```python
class MyConsumer(Conanfile):
      requires = "mylib/[>=1.0 <2.0]"
```

**Comment by emnkoksal** [comment]
Thank you much!
I was not aware of set_version! I had written my own and so put in configure() 😄 

(About requires: Sure, I had just too much minimized the example)

**Comment by memsharded** [comment]
Good! 😃
