### ISSUE TITLE
[question] Transitive includes not found by cmake when building

### ISSUE THREAD

**Issue by Marwan-imverse** [conan-io/conan#14402]
### What is your question?

I'm having a weird problem with porting my recipes from Conan 1.X to 2.X:

I have a library (let's call it `MyLibA`) that depends on `spdlog`. I build it fine and create the package with `conan export-pkg` (because I don't want to include the sources).
When I use it as a requires in `MyLibB` (`requires="MyLibA/1.0.0@user/channel"`) it cannot find the `spdlog `include files:
```
Cannot open include file: 'spdlog/spdlog.h'
```
What could cause this? Should the `MyLibA` recipe be declaring stuff explicitly?

`MyLibA `has a `requires="spdlog/1.11.0"`
`MyLibB `has a `requires="MyLibA/1.0.0"`
And they both have (from a common `python_requires_extend` class):

```python
def generate(self):
  [...]
  for require, dependency in self.dependencies.items():
    self._cmake_deps.set_property(dependency.ref.name, "cmake_find_mode", "both")
    if require.build:
      self._cmake_deps.build_context_activated.append(dependency.ref.name)
      self._cmake_deps.build_context_build_modules.append(dependency.ref.name)
```

Could this be affecting the configuration of `MyLibB` in some way?

`Findspdlog.cmake` is correctly generated when building `MyLibB`.
And  `module-spdlog-release-x86_64-data.cmake` correctly defines `spdlog_PACKAGE_FOLDER_RELEASE` but `spdlog_INCLUDE_DIRS_RELEASE` is empty.

In `MyLibA`, `spdlog `is linked to publicly in the cmake file:
`target_link_libraries([..] PUBLIC [..])`

And my `package_info()` is:
```
def package_info(self):
        self.cpp_info.libs = [self.name]
        self.cpp_info.set_property("cmake_find_mode", "both")
```
### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Marwan-imverse 

> conan export-pkg (because I don't want to include the sources).

This is not the main use case for ``export-pkg``. It is recommended for cases that you have the pre-compiled binaries, but not for not including the sources. If you want to not include the sources, you can still use the regular ``conan create`` (which has advantages over ``conan export-pkg``, using the https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html#examples-tools-scm-git-capture approach


> When I use it as a requires in MyLibB (requires="MyLibA/1.0.0@user/channel") it cannot find the spdlog include files:

Headers files are not automatically visible by downstream consumers, rather the opposite, by default they are hidden. There are two possibilities:
- If ``MyLibB`` includes explicitly headers from ``spdlog``, the ``MyLibB`` should have a explicit ``requires = "spdlog/...`` to express this, because it has a direct dependency to ``spdlog``
- If ``MyLib`` does not include headers from ``spdlog``, but they are transitively exposed by ``MyLibA``, then, the recipe of ``MyLibA`` should define it:
```python
def requirements(self):
     self.requires("sdplog/....", transitive_headers=True)
```
Recommended to watch the ACCU video in https://docs.conan.io/2/knowledge/videos.html for more explanations

> And module-spdlog-release-x86_64-data.cmake correctly defines spdlog_PACKAGE_FOLDER_RELEASE but spdlog_INCLUDE_DIRS_RELEASE is empty.

Yes, this is the default hiding of transitive headers

As some extra suggestions:
- I would try to avoid ``"cmake_find_mode", "both"``, and move to all ``config`` files. Find modules are legacy, better drop them.
- Recall that Conan 2.0 needs packages in lowercase, start renaming your packages to ``liba/...`` as soon as possible.

**Comment by Marwan-imverse** [comment]
> Hi @Marwan-imverse
> 
> > conan export-pkg (because I don't want to include the sources).
> 
> This is not the main use case for `export-pkg`. It is recommended for cases that you have the pre-compiled binaries, but not for not including the sources. If you want to not include the sources, you can still use the regular `conan create` (which has advantages over `conan export-pkg`, using the https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html#examples-tools-scm-git-capture approach

Thing is I don't wish to include sources, in any form (for IP and copyright reasons). Either directly or through git (or whatever scm). I only want to package the binaries. And I want to be able to build a package from a dirty repo for testing. None of my recipes have a `source()` method. This goes basck to [this issue](https://github.com/conan-io/conan/issues/14263#issuecomment-1631164020)

> > When I use it as a requires in MyLibB (requires="MyLibA/1.0.0@user/channel") it cannot find the spdlog include files:
> 
> Headers files are not automatically visible by downstream consumers, rather the opposite, by default they are hidden. There are two possibilities:
> 
>     * If `MyLibB` includes explicitly headers from `spdlog`, the `MyLibB` should have a explicit `requires = "spdlog/...` to express this, because it has a direct dependency to `spdlog`
> 
>     * If `MyLib` does not include headers from `spdlog`, but they are transitively exposed by `MyLibA`, then, the recipe of `MyLibA` should define it:
> 
> 
> ```python
> def requirements(self):
>      self.requires("sdplog/....", transitive_headers=True)
> ```

Isn't there a way to do this with the requires parameter? It was working automatically with 1.X? Why the change of philosophy for 2.X? Just curious.

I'll give it a try and see.

But this is only required for headers right? Transitive libraries will be linked normally?

> Recommended to watch the ACCU video in https://docs.conan.io/2/knowledge/videos.html for more explanations

Will do this right now :)

> As some extra suggestions:
> 
>     * I would try to avoid `"cmake_find_mode", "both"`, and move to all `config` files. Find modules are legacy, better drop them.
That would mean reworking our entire CMake infrastructure and CI, which is not planned for the moment, unfortunately.

>     * Recall that Conan 2.0 needs packages in lowercase, start renaming your packages to `liba/...` as soon as possible.
I did :) Conan2 does not even allow generating a package if the name is not all lower case. I was just illustrating and I used CamelCase by force of habit :)

**Comment by memsharded** [comment]
> Isn't there a way to do this with the requires parameter? It was working automatically with 1.X? Why the change of philosophy for 2.X? Just curious.

It is explained in the video. Leaking transitive headers allows bad practices.

> But this is only required for headers right? Transitive libraries will be linked normally?

There is also a ``transitive_libs`` trait. But it shouldnt be necessary for most cases, only exceptional ones. The automatic propagation of libs by Conan should be ok for most cases.

> I did :) Conan2 does not even allow generating a package if the name is not all lower case. I was just illustrating and I used CamelCase by force of habit :)

Great :)

**Comment by Marwan-imverse** [comment]
> > Isn't there a way to do this with the requires parameter? It was working automatically with 1.X? Why the change of philosophy for 2.X? Just curious.
> 
> It is explained in the video. Leaking transitive headers allows bad practices.

I our case we use a wrapper that needs to include the headers of the dependency (because of template issues).

I will avoid using this systematically. It's good to know that overriding this is an option.

Also this might be an issue with header only libs no? Or is transitivity forced in this case?
 
> > But this is only required for headers right? Transitive libraries will be linked normally?
> 
> There is also a `transitive_libs` trait. But it shouldnt be necessary for most cases, only exceptional ones. The automatic propagation of libs by Conan should be ok for most cases.

Noted, thanks.

**Comment by Marwan-imverse** [comment]
Well `transitive_headers=True` solved my issue anyway.

Thanks again @memsharded !

**Comment by memsharded** [comment]
> Also this might be an issue with header only libs no? Or is transitivity forced in this case?

header-only libraries requiring other libraries will automatically define ``transitive_xxx=True`` traits, yes.
