### ISSUE TITLE
CONAN_TRACE_FILE doesn't accept quotes on windows

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#1441]
If you do:

```
set CONAN_TRACE_FILE="C:\myPath\conan_trace.log"
conan install
```
you get:
`ERROR: Bad CONAN_TRACE_FILE value. The specified path has to be an absolute path to a file.`

Removing the quotes fixes the issue. It would be ok, except the example uses quotes.

**Comment by memsharded** [comment]
Thanks for noticing. I have removed the quotes in the env-var definition in the docs: https://github.com/conan-io/docs/commit/a553e70ef52258e0a4dc76c6761f17df490f3364

Tested in Win & Linux, should work in both without the quotes. Can this issue be closed with this?
Also, you can submit documentation issues and pull requests to: https://github.com/conan-io/docs

Thanks!
