### ISSUE TITLE
conandata.yml and exports_sources

### ISSUE THREAD

**Issue by laxmij-cmd** [conan-io/conan#14417]
### What is your question?

Hi,
I have to repackage tcl 8.6.11 using conana 2.0. While doing so I have to add dir "cmake" where conanfile.py is. I have tried doing by adding exports_sources in  conanfile.py of tcl

I added lines 30-31 :

![image](https://github.com/conan-io/conan/assets/111378770/98449827-277a-4fd1-a6d8-b9a1a02604c0)

but it is not working. It works only when I remove conandata.yml. 

How can I use both -- exports_sources and conandata.yml?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @laxmij-cmd 

Sorry, I am a bit confused. The ``conanfile.py`` is not inside the ``cmake`` dir.

It is also not clear what is failing. Could you please report:
- A full ``conanfile.py`` (it can be a simplified one, not the full tcl one) that we can use to reproduce
- The exact and complete description of the folders and file locations
- The command and the command output error, the full output, not just the error.

Thanks very much.

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you in a while - if anyone has any other question or request, please feel free to create a new issue, we're always happy to help! :)
