### ISSUE TITLE
[question] Breaking change in MultiPackagesList.refs() from 2.0.9 to latest release/2.0 branch?

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#14419]
### What is your question?

I've got a function that merges the built binaries list from all my invocations of `conan install` so that I can get a single list of built packages to give to `conan upload` command on CI.

Previously, this function looked like this:

```python
def merge_built_binaries(multi_pkg_list: MultiPackagesList, built_binaries: PackagesList):
    built_list = multi_pkg_list['Local Cache']

    # merge into built_binaries
    for ref, recipe_bundle in built_list.refs():
        built_binaries.add_refs([ref])
        for pref, _ in built_list.prefs(ref, recipe_bundle):
            built_binaries.add_prefs(ref, [pref])
```

This stopped working with latest state from `release/2.0` branch (actually branch by @memsharded where he fixed the `conan editable` issue with empty conan cache), and in order for the code to work, I had to write:

```python
def merge_built_binaries(multi_pkg_list: MultiPackagesList, built_binaries: PackagesList):
    built_list = multi_pkg_list['Local Cache']

    # merge into built_binaries
    for ref, recipe_bundle in built_list.refs().items():
        built_binaries.add_refs([ref])
        for pref, _ in built_list.prefs(ref, recipe_bundle).items():
            built_binaries.add_prefs(ref, [pref])
```

Since I'm locally experimenting with latest conan directly from mentioned branch, and my CI still got stable 2.0.9, my current workaround that should work with both cases looks like this:

```python
def merge_built_binaries(multi_pkg_list: MultiPackagesList, built_binaries: PackagesList):
    built_list = multi_pkg_list['Local Cache']

    # merge into built_binaries
    built_list_refs = built_list.refs()
    refs_is_dict = False
    # conan 2.0.10 and beyond
    if callable(getattr(built_list_refs, 'items', None)):
        built_list_refs = built_list_refs.items()
        refs_is_dict = True
    for ref, recipe_bundle in built_list_refs:
        built_binaries.add_refs([ref])
        built_list_prefs = built_list.prefs(ref, recipe_bundle)
        if refs_is_dict:
            built_list_prefs = built_list_prefs.items()
        for pref, _ in built_list_prefs:
            built_binaries.add_prefs(ref, [pref])
```

That's a bit ugly. So, I have several questions:

- is there a better way to make that detection?
- is this API break intended or accidental (I know that there is no commitment for Python API stability, but it's possible that the change was accidental)?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DoDoENT 

yes, this change was intentional. We need to do those changes for other features, and as this is at the moment completely private implementation detail, we went for it.

I think your detection is good enough for the case. I hope we don't need to change it again, but please be aware that this might happen (we thought converting ``refs`` and ``prefs`` to properties, and also renaming them, for example), as these components interfaces are still a bit early stage, need some iteration to improve the code.

**Comment by DoDoENT** [comment]
OK, thanks for the info. I use this API primarily to get the equivalent of `conan lock merge`, but for package lists. The idea is to install for both debug, dev-release, release, host, and build system and then upload all built packages "in one go".

I understand it's possible to write external scripts that handle multiple package list JSONs, but it was just easier for me to write that as a conan custom command that both does all the installation procedure mentioned above, and produces a single large JSON report of all built binaries that can be directly consumed by `conan upload` command.

**Comment by memsharded** [comment]
Yes, we are considering implementing this as built-in, kind of ``conan list merge`` command. Hopefully you will not need to do this in your custom command.

**Comment by DoDoENT** [comment]
If you expose it via Python API, just like all other CLI commands, I'll then be able to use that from my custom command that already wraps `conan install` by making sure that it always detects the correct profile, and installs all built types.
