### ISSUE TITLE
How to force values for options of required packages, from the recipe of the consumer package?

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#14415]
### What is your question?

Hi, from the documentation about  [default_options](https://docs.conan.io/2/reference/conanfile/attributes.html#settings) there is the following example

```
class MyPkg(ConanFile):
    ...
    requires = "zlib/1.2.8", "zwave/2.0"
    options = {"build_tests": [True, False],
                "option2": "ANY"}
    default_options = {"build_tests": True,
                        "option1": 42,
                        "z*:shared": True}
```

This is defining default values for option "shared" of packages zlib and zwave.

Can I force the value of required packages options from the consumer package recipe (not just define default value which could be overridden)?

Something like 
```
 def configure(self):
    self.options.z*:shared = True
```
But of course that is not valid syntax.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
You can do:

```python
def configure(self):
    # Update: this is wrong self.options["z*:shared"] = True
    self.options["z*"].shared = True
```
Which makes sense for example if you want to do conditionals, or use any expression or evaluation.
But it doesn't unconditionally force the value of the dependency, there are some situations that will change the value:
- If some downstream consumer defines the same option value, the downstream consumers always have precedence
- If some other sibling in the dependency graph in a diamond structure contains other value, the first one to be evaluated also has higher precedence.
- If the profile (or command line arguments, it is the same), define options values, those also have higher precedence.

This is necessary to respect the most-downstream consumer. That is, if the user types ``-o z*:shared=False`` in the command line and that is not respected, it is first super confusing, and users will wonder why this is happening and report it as a bug, and then it will also be blocking in many situations.

There are some exceptions in which the options of other downstream recipes are not propagated and those are special requirements with ``visible=False`` trait (the profile options will always be respected). But in the majority of cases this shouldn't be done, it should be for very exceptional cases.

**Comment by freihamer** [comment]
Thank you, I understand and share the philosophy.

However that syntax in your example doesn't seem to work for me. What works is something like:
```
def configure(self):
    self.options["z*"].shared = True
```

**Comment by memsharded** [comment]
oh, sorry, yes, you are right, that is the correct syntax, updating my comment above.
