### ISSUE TITLE
test_package skeleton writes BUILD_SHARED_LIBS twice to cmake invocation string

### ISSUE THREAD

**Issue by amues** [conan-io/conan#1442]
Running conan 0.24.0 installed with pip.

The _conanfile.py_ in the skeleton code generated by `conan new -t <pkg_name>` defines a `shared` variable in the `build` method, which is then added to the string passed to the `run` method:
```
def build(self):
        cmake = CMake(self)
        shared = "-DBUILD_SHARED_LIBS=ON" if self.options.shared else ""
        self.run('cmake hello %s %s' % (cmake.command_line, shared))
        ...
```
When `conan test_package` is called with `-o <pkg_name>:shared=True`, this results in the CMake command defining `BUILD_SHARED_LIBS` twice:
```
cmake hello ... -DBUILD_SHARED_LIBS="ON" -Wno-dev -DBUILD_SHARED_LIBS=ON
```

**Comment by memsharded** [comment]
Yes, that is correct.
Latest ``CMake``helper is able to automatically define ``BUILD_SHARED_LIBS`` based on the option. Submitted PR to fix it, that was easy, next time you might try to contribute it yourself :)

Thanks for telling!
