### ISSUE TITLE
[question] conan skipping package upload to artifactory

### ISSUE THREAD

**Issue by Prudvi-data** [conan-io/conan#14433]
### What is your question?

I have c++ project that produces staticlibrary and binary. While I am trying to export package it throws `No matching pattern found` as shown below.

![image](https://github.com/conan-io/conan/assets/95167320/4ca1d398-1e76-4f90-8e9e-c171c6cf319c)

Even it has error it successfully creates a package, but when I try to upload it to remote server( Artifactory) it just skips that package and only uploads conan sources.

![image](https://github.com/conan-io/conan/assets/95167320/0172290a-2355-4198-a40c-cf09caa29c37)

Conan is skipping package upload only when we get error while packaging as above, can someone take a look.

conan version -- 1.60.1

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Prudvi-data 

Please provide the upload command that you are using. Is it possible that you are missing the ``--all`` argument?

**Comment by Prudvi-data** [comment]
yeah I am not using `--all` argument because we set build_policy as always.

![image](https://github.com/conan-io/conan/assets/95167320/846cbe4a-1773-44ae-8f12-01e1f197837c)

**Comment by memsharded** [comment]
Then of course no binaries will be uploaded, this is what the policy means. If you force building with ``build_policy="always"`` no binaries are uploaded, because binaries are only built from source.

**Comment by Prudvi-data** [comment]
Thanks
