### ISSUE TITLE
Consumer package won't find public header of dependency

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#14434]
### What is your question?

Hi,

I am packaging a static library as follows (simplified view)
```
class HelloRecipe(ConanFile):
    name = "hello"
    package_type = "static-library"
    version = "1.0.0"

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["hello"]

```

Which ends up in a package folder structure like this one

```
p/include/hello.h
p/lib/libhello.a
```
But my consumer package does not find hello.h (compiler error with conan build)

In the Conan recipe I am doing:

```
class ConsumerRecipe(ConanFile):

    def requirements(self):
        self.requires("hello/1.0.0", headers=True, libs=True)
```

In the CMakeLists.txt of the consumer I have

`find_package(hello REQUIRED)`

Which can find hello package, otherwise CMake would complain. I can also see a generated hello-debug-armv7hf-data.cmake with correctly set CMake variable `hello_INCLUDE_DIRS_DEBUG`, but that information is not passed to CMake for the build.

What am I missing?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lucabarbiero 

Thanks for your question.

Quick note: ``self.requires("hello/1.0.0", headers=True, libs=True)`` those traits are not really necessary, those are already the defaults. Better drop them, only use them if the defaults are not working.

I would need more information about the consumer side. Typically the ``CMakeToolchain`` is necessary, and the ``conan_toolchain.cmake`` used. Please provide:
- the full commands ``conan install`` + ``cmake ...`` that you are using
- the full output of the commands

Also, I guess that you are using Conan 2.0, but better please make explicit always the Conan version.

**Comment by freihamer** [comment]
Hi @memsharded 

Thanks for the quick note and yes for sure I am using `CMakeToolchain` and I have a `conan_toolchain.cmake` (and yes I use Conan 2.0.7)

Following is what happens when I run `conan install` (looks normal to me)

```
conan install . --profile=win_to_armv7 -s build_type=Debug

======== Input profiles ========
Profile host:
[settings]
arch=armv7hf
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=6.3
os=baremetal
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
[buildenv]
CHOST=arm-none-eabi
AR=C:/ARM/arm-none-eabi/bin/arm-none-eabi-ar
AS=C:/ARM/arm-none-eabi/bin/arm-none-eabi-as
RANLIB=C:/ARM/arm-none-eabi/bin/arm-none-eabi-ranlib       
LD=C:/ARM/arm-none-eabi/bin/arm-none-eabi-ld
STRIP=C:/ARM/arm-none-eabi/bin/arm-none-eabi-strip
CC=C:/ARM/arm-none-eabi/bin/arm-none-eabi-gcc
CXX=C:/ARM/arm-none-eabi/bin/arm-none-eabi-g++
CXXFLAGS=-I"C:/ARM/arm-none-eabi/arm-none-eabi/lib/include"

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu98
compiler.libcxx=libstdc++
compiler.version=4.4
os=Windows
[conf]
tools.cmake.cmaketoolchain:generator=Ninja


======== Computing dependency graph ========
Graph root
    conanfile.py (consumer_pkg/1.1.0): C:\my_project\conanfile.py
Requirements
    hello/1.0.0#b33adfe8366de39daa1b25ae2534eb6f - Cache

======== Computing necessary packages ========
Requirements
    hello/1.0.0#b33adfe8366de39daa1b25ae2534eb6f:da3bd0ed4b5babb6d4b0a51f1fbbc55616765896#bf5683097102b4cce0f3f2afd7c7d75e - Cache

======== Installing packages ========
hello/1.0.0: Already installed! (1 of 2)

======== Finalizing install (deploy, generators) ========
conanfile.py (consumer_pkg/1.1.0): Calling generate()
conanfile.py (consumer_pkg/1.1.0): Generators folder: C:\Users\LBarbiero\Work\repos\software\CONDOR_Mk3\azimuth_motor_control_software\build\Debug\generators
conanfile.py (consumer_pkg/1.1.0): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (consumer_pkg/1.1.0): Preset 'conan-debug' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-debug' if using CMake>=3.23
conanfile.py (consumer_pkg/1.1.0): If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\my_project\build\Debug\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Debug'
conanfile.py (consumer_pkg/1.1.0): CMakeToolchain generated: CMakePresets.json
conanfile.py (consumer_pkg/1.1.0): CMakeToolchain generated: ..\..\..\CMakeUserPresets.json
conanfile.py (consumer_pkg/1.1.0): Generating aggregated env files
conanfile.py (consumer_pkg/1.1.0): Generated aggregated env files: ['conanbuild.bat', 'conanrun.sh']
Install finished successfully
```

After this I run `conan build`. The output is similar, but the compilation will fail for not finding hello.h.

I solve that problem if I manually provide the Conan generated CMake variable `hello_INCLUDE_DIR` to my CMake `target_include_directories()`, but I haven't read anywhere that I should be doing this. And anyway the problem then becomes that also the static library `libhello.a` won't be found at link time. 

I am sure that CMake `find_package()` works, thanks to information in `conan_toolchain.cmake`. The dependency package is found.

Could it be that I am overriding something in my CMakeLists.txt that jeopardizes some CMake variable that Conan took care of populating?

How exactly the dependency package include path should be provided to the compiler, eventually?

**Comment by freihamer** [comment]
All right sorry @memsharded, the mistake simply was that I used
`
target_link_libraries(myprj hello)`

instead of 


`target_link_libraries(myprj hello::hello)`

now it works

**Comment by memsharded** [comment]
Ok, that is great, thanks for the follow up.

You should be able to see the CMake target names in the CMake output. If the ``find_package()`` doesn't fail, it will list those correct target names for convenience.

I think we can close the ticket now, but don't hesitate to create new ones if necessary. Thanks!
