### ISSUE TITLE
[feature] Add `nox` for testing

### ISSUE THREAD

**Issue by chrysle** [conan-io/conan#14439]
### What is your suggestion?

[`nox`](https://nox.thea.codes/en/stable/index.html) is an easy-to-use, highly configurable testing framework for Python.

Are you interested in adding this to the project for testing purposes (and code quality checks)? Users could skip the set-up steps for the tests, if they were integrated in a `nox` session. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @chrysle 

Thanks for your suggestion.
we are not interested at this moment in adding more tooling to the test suite, we are happy about the current ``pytest`` usage, and many of the tools that are necessary for testing are not installable with tools anyway (like Visual Studio).

Closing this as not planned.

**Comment by chrysle** [comment]
Thank you for the quick response!

> and many of the tools that are necessary for testing are not installable with tools anyway (like Visual Studio).

Could you explain why Visual Studio is a testing dependency? I  did only find Python requirements in the corresponding README section.

**Comment by memsharded** [comment]
We have e2e (functional) tests that do use gcc, clang, Visual Studio, CMake, Ninja, Meson, pkgconf, msys2, cygwin, bazel, premake, android-ndk, autotools, etc, and we test in different OSs: Windows, Linux and OSX. Installing things like VS or msys2 dynamically is not an option, so we need to provision the machines with these tools. The ``conftest.py`` and ``conftest_user.py`` have the mappings.

**Comment by chrysle** [comment]
Thanks for the explanation!
