### ISSUE TITLE
[question] Profile with C++20

### ISSUE THREAD

**Issue by matheusdiogenesandrade** [conan-io/conan#14448]
### What is your question?

Hello.

I am trying to setup a conan profile with the C++20, but I am having some problems. When running the command:
```sh
conan install .. --profile ../conanprofile.txt
```
I obtain the following output:
```
ERROR: Invalid setting 'libstdc++20' is not a valid 'settings.compiler.libcxx' value.
Possible values are ['libstdc++', 'libstdc++11']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```
The structure of my profile script [`conanprofile.txt`](https://github.com/matheusdiogenesandrade/conan_example/blob/main/conanprofile.txt) is given below:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=20
compiler.libcxx=libstdc++20
build_type=Release

[options]

[conf]

[build_requires]

[env]
```

For the complete project structure, follows the [project](https://github.com/matheusdiogenesandrade/conan_example).

Thanks and regards.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @matheusdiogenesandrade - thank you for opening this issue.

The setting required for Conan to build packages with C++ 20 by default is `compiler.cppstd=20`. If you are using gcc on a modern distro, tcompiler.libcxx` should be `libstdc++11`. In your case you should also set `compiler.version` to the version of gcc you are using (there is no gcc 20 release yet, the most recent is gcc 13).

**Comment by matheusdiogenesandrade** [comment]
> Hi @matheusdiogenesandrade - thank you for opening this issue.
> 
> The setting required for Conan to build packages with C++ 20 by default is `compiler.cppstd=20`. If you are using gcc on a modern distro, tcompiler.libcxx`should be`libstdc++11`. In your case you should also set `compiler.version` to the version of gcc you are using (there is no gcc 20 release yet, the most recent is gcc 13).

Thank you very much. I implemented the suggested changes, ending up with the following profile script:
```conan
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12.2
compiler.cppstd=20
compiler.libcxx=libstdc++11
build_type=Release

[options]

[conf]

[build_requires]

[env]
```
But after running the `cmake ..` command, I obtained the following error:
```
CMake Error at build/conanbuildinfo.cmake:963 (message):
  Detected a mismatch for the compiler version between your conan profile
  settings and CMake:

  Compiler version specified in your conan profile: 12.2

  Compiler version detected in CMake: 11.4

  Please check your conan profile settings (conan profile show
  [default|your_profile_name])

  P.S.  You may set CONAN_DISABLE_CHECK_COMPILER CMake variable in order to
  disable this check.
Call Stack (most recent call first):
  build/conanbuildinfo.cmake:1047 (conan_error_compiler_version)
  build/conanbuildinfo.cmake:1154 (check_compiler_version)
  build/conanbuildinfo.cmake:702 (conan_check_compiler)
  CMakeLists.txt:17 (conan_basic_setup)
```
I think my CMake file is not structured correctly, follows it:
```cmake
cmake_minimum_required(VERSION 3.16)
project(Test)

##### SETs
set (Sample_VERSION_MAJOR 0)
set (Sample_VERSION_MINOR 0)
set (Sample_VERSION_PATCH 1)
set (Project_PATH "${PROJECT_SOURCE_DIR}")
set (CMAKE_BUILD_TYPE Release) 
set (CMAKE_CXX_STANDARD 20)

set (BUILD_SHARED_LIBS On)

##### Includes
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
conan_basic_setup()

##### Additional packages 

find_package (range-v3)

##### Config files 

configure_file(
    "${PROJECT_SOURCE_DIR}/SampleConfig.h.in"
    "${PROJECT_BINARY_DIR}/SampleConfig.h"
    )

##### Include Dirs 

include_directories(
    SYSTEM
    includes
    "${PROJECT_BINARY_DIR}"
    )

##### Compile options 


add_compile_options(-Wall
    -DIL_STD
    -Wfatal-errors
    -pedantic
    -fopenmp
    -DDEBUG
    -fdiagnostics-color=always
    -Wall
    -lz
    #
    #    -std=c++17
    -std=c++20
    #
    -lm 
    -lpthread 
    -ldl
    -Wno-sign-compare
    )

file(GLOB_RECURSE SOURCES "src/*.cpp")

add_executable(
    main 
    ${SOURCES} 
    )
    

target_link_libraries(
    main 
    ${CONAN_LIBS} 
    range-v3::range-v3
    pthread 
    m 
    dl
    )
```

The entire project is [here](https://github.com/matheusdiogenesandrade/conan_example).

Thanks for the attention.

**Comment by jcar87** [comment]
Hi @matheusdiogenesandrade - thank you for testing the proposed testings.

From what I can see, CMake finds gcc 11.4, while you have set `12.2` in your Conan profile. Is there any chance that you have multiple versions of gcc on your system? 

To be able to proceed, you need to **either**:
* set `compiler.version=11` in your Conan profile
* OR when first configuring the CMake build, tell CMake to use gcc 12, perhaps with `-DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++12` - provided gcc 12 is actually installed and can be accessed with the `gcc-12` and `g++-12` commands, which depends on which distro you are using.

I have also noticed that you are using the old integrations for Conan 1.x. The newer Conan 2.0 was released this past February, and the workflow for integrating with a CMake project has been improved and simplified. With Conan 2.0, you no longer need to do:
```
##### Includes
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
conan_basic_setup()
```

or reference `${CONAN_LIBS}` - 

This is covered in the Conan 2.0 documentation: https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html

Please let me know if this resolves your question.

**Comment by matheusdiogenesandrade** [comment]
Thank you very much. Just set to the version 11, and now everything is fine.
