### ISSUE TITLE
[bug] File not found exception during Conan upload

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#14449]
### Environment details

Ubuntu 20.04
Conan 1.60.1
Python 3.9

### Steps to reproduce

Don't know how to reproduce this problem as it is the first time we encountered this issue.

We got this error sometimes when using the download cache from multiple different machines but never during upload.
See: #14329 

### Logs

We are using the Download cache to reduce redundant downloads from our Artifactory remotes to our CI/CD machines.
During one run we got following error message:

```
+ conan upload ...-manager/8.6.0-develop.22@ci/develop -r ...-conan-snapshots-local --skip-upload
Uploading to remote '...-conan-snapshots-local':

Uploading ....-manager/8.6.0-develop.22@ci/develop to remote '...-conan-snapshots-local'
Compressing recipe...
ERROR: ....-manager/8.6.0-develop.22@ci/develop: Upload recipe to '...-conan-snapshots-local' failed: [Errno 2] No such file or directory: '/host/shared/conan/downloads/043b9336bfe4a849dea7588b7579943d3c55ff16e87aa80aa24d1120dbde9a82.dirty'. [Remote: ...-conan-snapshots-local]

ERROR: Errors uploading some packages
##[error]Bash exited with code '1'.
```

Why is the upload command doing anything with the download cache?

**Comment by memsharded** [comment]
Hi @MTomBosch 

I think this could be the problem:

> We got this error sometimes when using the download cache from multiple different machines but never during upload.

the download cache is not designed to be shared in a distributed, multi-machine way. It uses file-locking mechanism, which is a OS mechanism that works at the OS level. It is not guaranteed that it can work across a distributed shared drive, and most likely it will fail if different OSs are concurrently accessing it.

We know it would be great to have such a feature, but the technical challenges to build such a multi-platform distributed cache mechanism are just too much for Conan, it requires its own server application that controls access to disk.

**Comment by MTomBosch** [comment]
I understand your arguments related to the download cache architecture and I agree that we have to find potentially a different solution for caching due to our distributed setup. But regarding this ticket still the question remains: Why is an upload having any dependency or relation to the download cache? Not knowing the reasons this feels like a bug or dependency that shall not be there.

**Comment by memsharded** [comment]
> I understand your arguments related to the download cache architecture and I agree that we have to find potentially a different solution for caching due to our distributed setup. But regarding this ticket still the question remains: Why is an upload having any dependency or relation to the download cache? Not knowing the reasons this feels like a bug or dependency that shall not be there.

When the ``conan upload`` is executed, this command might download the ``conan_sources.tgz`` from the server, if for some reason it doesn't already have it in the cache. This happens for example when a package is not built from source in the cache, but uses a pre-compiled binary. As the package integrity needs the sources to be uploaded to the server, if they are missing, they will be downloaded, and if you have the download cache enabled, it will try to get it from there instead of an actual download from the server.
