### ISSUE TITLE
Unrecognized Argument Error: Issue when running the conan create command

### ISSUE THREAD

**Issue by alLiucb** [conan-io/conan#14469]
### What is your question?

I have recently encountered a problem while using Conan to build a project, and I'm seeking some assistance. Here are the details of the issue:

I'm trying to create a Conan package using the following command within the project's working directory:
conan create conan/openvolumemesh sxsong1207/stable

However, when I attempt to run the above command, I encounter an error message:
usage: conan create [-h] [-v [V]] [-f FORMAT] [--name NAME]
                    [--version VERSION] [--user USER] [--channel CHANNEL]
                    [-l LOCKFILE] [--lockfile-partial]
                    [--lockfile-out LOCKFILE_OUT] [--lockfile-packages]
                    [--lockfile-clean]
                    [--lockfile-overrides LOCKFILE_OVERRIDES] [-b BUILD]
                    [-r REMOTE | -nr] [-u] [-o OPTIONS_HOST]
                    [-o:b OPTIONS_BUILD] [-o:h OPTIONS_HOST]
                    [-pr PROFILE_HOST] [-pr:b PROFILE_BUILD]
                    [-pr:h PROFILE_HOST] [-s SETTINGS_HOST]
                    [-s:b SETTINGS_BUILD] [-s:h SETTINGS_HOST] [-c CONF_HOST]
                    [-c:b CONF_BUILD] [-c:h CONF_HOST] [--build-require]
                    [-tf TEST_FOLDER]
                    path
conan create: error: unrecognized arguments: sxsong1207/stable
ERROR: Exiting with code: 2

The crux of the issue lies in the sxsong1207/stable argument within the conan create command not being recognized, leading to the aforementioned error. While I have consulted official documentation and online resources, I have not been able to find a solution.

I'm looking for guidance on the proper usage of the conan create command and how to correctly pass the arguments in order to successfully create my Conan package. Any guidance or experiences from individuals who have faced a similar situation would be greatly appreciated.

Thank you very much for your assistance!

Ubuntu20.04
conan 2.0.9
cmake 3.19.6

I am attempting to build the project, and the project address is as follows:
https://github.com/GDAOSU/vis2mesh

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by fschoenm** [comment]
That's conan 1.x syntax. In conan 2.x you have to use the `--user` and `--channel` arguments to achieve the same thing

```
conan create conan/openvolumemesh --user sxsong1207 --channel stable
```

**Comment by alLiucb** [comment]
> That's conan 1.x syntax. In conan 2.x you have to use the `--user` and `--channel` arguments to achieve the same thing
> 
> ```
> conan create conan/openvolumemesh --user sxsong1207 --channel stable
> ```

ok，thanks @fschoenm
