### ISSUE TITLE
[question] Solve cmake version range

### ISSUE THREAD

**Issue by robert-shade** [conan-io/conan#14460]
### What is your question?

I'm trying to build `hdf5/1.14.0` locally, but it keeps failing with:

`ERROR: Version range '>=3.18 <4' from requirement 'cmake/[>=3.18 <4]' required by 'hdf5/1.14.0' could not be resolved in local cache`

I've tried adding `cmake/3.23.2` as an explicit tool_requires in my build profile, but that doesn't work either.

What is the proper way to handle this?

This is with conan 1.160.1

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @robert-shade thanks for your question. We need a bit more information to help you here:

What's the exact command you are using?

**Comment by robert-shade** [comment]
`conan install . --profile:build default_build --build hdf5`

conanfile.txt
```
[requires]
hdf5/1.14.0
```

Output:
```
$  conan install . --profile:build default_build --build hdf5
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/gcc
CXX=/usr/bin/g++
Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
*: cmake/3.23.2
[env]
CC=/usr/bin/gcc
CXX=/usr/bin/g++
hdf5/1.14.0: Forced build from source
ERROR: Version range '>=3.18 <4' from requirement 'cmake/[>=3.18 <4]' required by 'hdf5/1.14.0' could not be resolved in local cache
```

**Comment by AbrilRBS** [comment]
Thanks! Some more followup questions then:

 * What remotes do you have configured & active in your machine? You can get this information by running `conan remote list` (Feel free to censor URLs and such if needed)
 * Is cmake present in any of the active repositories? `conan search cmake -r=<remotename>`

**Comment by robert-shade** [comment]
```
$  conan remote list
ng-conan: https://artifactory.redacted.com/api/conan/ng-conan [Verify SSL: True]
```
(it's a virtual artifactory repo with conan-center remote included)

So just cmake itself doesn't work, but searching the full package name does
```
$  conan search "cmake" -r=ng-conan
There are no packages matching the 'cmake' pattern
```

```
$  conan search "cmake/3.23.2@" -r=ng-conan
Existing packages for recipe cmake/3.23.2:

Existing recipe in remote 'ng-conan':

    Package_ID: 01edd76db8e16db9b38c3cca44ec466a9444c388
        [options]
            with_openssl: False
        [settings]
            arch: x86_64
            build_type: Debug
            os: Windows
        Outdated from recipe: False
...
    Package_ID: d236921d4854b1409aaf5c280132cd46839056aa
        [options]
            with_openssl: True
        [settings]
            arch: x86_64
            build_type: Debug
            os: Linux
        [requires]
            openssl/1.1.1q:b1b85bfdc2206d81b3ed6a49e78498182bb98ef3
        Outdated from recipe: False
```

Hm, but it does work if I go directly to conancenter :/

```
$  conan search "cmake" -r=conancenter
Existing package recipes:

cmake/3.15.7
cmake/3.16.2
cmake/3.16.3
cmake/3.16.4
cmake/3.16.5
cmake/3.16.6
...
cmake/3.25.3
cmake/3.26.3
cmake/3.26.4
cmake/3.27.0
cmake/3.27.1
```

It also works if I go directly to our artifactory remote instead of the virtual repo.  Maybe this is an artifactory bug, then.
```
$  conan search "cmake" -r=conan-center-remote
Existing package recipes:

cmake/3.15.7
cmake/3.16.2
cmake/3.16.3
cmake/3.16.4
cmake/3.16.5
cmake/3.16.6
...
cmake/3.25.3
cmake/3.26.3
cmake/3.26.4
cmake/3.27.0
cmake/3.27.1
```

**Comment by robert-shade** [comment]
Update for anyone that finds this issue in the future:

This appears to be an Artifactory bug or misconfiguration.  If we turn off Priority Resolution for our local repositories in the virtual, search works as expected.  We have a bug report out to jfrog describing the situation.

**Comment by AbrilRBS** [comment]
Hi @robert-shade thanks for the detailed follow-up.
After checking from our side, you seem to be right, it looks to be mainly an artifactory issue.

Thanks a lot for escalating the issue to Jfrog and for providing a workaround for anyone that might be affected in the meanwhile!

**Comment by AbrilRBS** [comment]
Closing jere as there's nothing on our side we can do, but feel free to send an update once it gets fixed :)
