### ISSUE TITLE
Not able to download JFrog Artifactory Community Edition

### ISSUE THREAD

**Issue by sangramjadhavbhtc** [conan-io/conan#14463]
### Environment details

* Operating System+version: Win 10
* Compiler+version: GCC 13
* Conan version: 2.0.9
* Python version:3.11.2

### Steps to reproduce

I am trying to download JFrog Artifactory Community Edition for Windows from https://conan.io/downloads. But it is not downloading entire files; which means the downloadable size is showing 709MB but the actual downloaded folder size is only 3.14MB. Kindly check the issue. or tell the alternate way of download full version. 

![image](https://github.com/conan-io/conan/assets/129362731/4ea12951-e9f7-4138-9680-7098194583ed)

![image](https://github.com/conan-io/conan/assets/129362731/dada13bc-51c3-4cfe-bbe0-e3120a235a21)

**Comment by memsharded** [comment]
Hi @sangramjadhavbhtc 

It seems it is working fine here from my side. The links works and the download works too.

It could be some network, firewall or something like that from your side?

**Comment by sangramjadhavbhtc** [comment]
Yeah, I have tasted it with other PC and networks it is working fine. Thank you
