### ISSUE TITLE
Boost: Missing path to b2

### ISSUE THREAD

**Issue by AndersGnistrup** [conan-io/conan#14462]
### What is your question?

Hi, i have some problems getting b2 in the path when installing Boost in a cross build environment since b2 is required.

I am using conan 2.0.9. For host compilation works.
I am trying to install boost 1.82 in a arm cross build environment and to to this b2 is a tool requirement.
This seems to work just fine:
`Build requirements  b2/4.9.6#2e02945ad41739b8051247d14fe8297d:63fead0844576fc02943e16909f08fcdddd6f44b#07e7cfb1a52c516a8bc2ff6109366e4e - Cache`
This is triggered by Boost package, so no problems there.
But, during build b2 is not found.
```
boost/1.82.0: RUN: b2 -q target-os=linux architecture=arm address-model=32 binary-format=elf abi=aapcs --layout=system --user-config=/home/agn/work/EmbeddedProductDev/.conan2/p/boost0eafd9621eb61/s/src/tools/build/user-config.jam -sNO_ZLIB=1 -sNO_BZIP2=1 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=off --disable-iconv threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-date_time --with-exception --with-filesystem --with-log --with-program_options --with-random --with-regex --with-system --with-thread toolset=gcc cxxflags=-std=c++2a define=_GLIBCXX_USE_CXX11_ABI=1 define=BOOST_DLL_USE_STD_FS=1 pch=on linkflags="" cxxflags="-fPIC" install --prefix=/home/agn/work/EmbeddedProductDev/.conan2/p/b/boost934fe8e7fe9bd/p -j20 --abbreviate-paths -d0 --debug-configuration --build-dir="/home/agn/work/EmbeddedProductDev/.conan2/p/b/boost934fe8e7fe9bd/b/build-release"
/bin/sh: 1: b2: not found
```

But b2 is in .conan2
```
(.venv) agn@AndersGnistrup:~/work/EmbeddedProductDev$ [epd] .conan2/p/b21a8cf2a364eb1/p/bin/b2
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: https://www.bfgroup.xyz/b2/manual/release/index.html#bbv2.overview.configuration
error: no Jamfile in current directory found, and no target references specified.
```
If I add the .conan2/p/b21a8cf2a364eb1/p/bin to the $PATH Boost does compile but this is quite a hackish solutions.
```

I have then looked into the environment files for boost:
[epd] ls .conan2/p/b/boost934fe8e7fe9bd/b/build-release/conan/
conanbuildenv-release-armv7.sh  conanbuild.sh  conanrunenv-release-armv7.sh  conanrun.sh  deactivate_conanbuildenv-release-armv7.sh  deactivate_conanbuild.sh  deactivate_conanrun.sh
```

And conanbuildenv-release-armv7.sh does add b2 to the path!

Is this a recipi bug or am I doing something wrong?
This is my build profile:
```
[buildenv]
PATH=+[/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/bin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/sbin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/bin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/sbin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/../x86_64-pokysdk-linux/bin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-musl,/usr/local/sbin,/usr/local/bin,/usr/sbin,/usr/bin,/sbin,/bin]
CC=arm-poky-linux-gnueabi-gcc
CFLAGS= -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi
CXX=arm-poky-linux-gnueabi-g++
CXXFLAGS= -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi
CPPFLAGS= -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi
AR=arm-poky-linux-gnueabi-ar
RANLIB=arm-poky-linux-gnueabi-ranlib

[settings]
os=Linux
arch=armv7
compiler=gcc
compiler.version=11.2
compiler.libcxx=libstdc++11
compiler.cppstd=20
build_type=Release

[conf]
tools.gnu:host_triplet=armv7-poky-linux


```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AndersGnistrup** [comment]
I think I got the error.....
The format of the path variable is wrong. taken from conanbuildenv-release-armv7.sh in .conan
`export PATH="[/home/agn/work/EmbeddedProductDev/sdk,/home/agn/work/EmbeddedProductDev/sdk/sysroots/x86_64-linux/usr/bin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/bin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/sbin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/bin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/sbin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/../x86_64-pokysdk-linux/bin,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi,/home/agn/work/EmbeddedProductDev/build-target-tmb0201/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-musl,/usr/local/sbin,/usr/local/bin,/usr/sbin,/usr/bin,/sbin,/bin] /home/agn/work/EmbeddedProductDev/.conan2/p/b21a8cf2a364eb1/p/bin $PATH"`

**Comment by memsharded** [comment]
Hi @AndersGnistrup 

Thanks for your report.
Yes, it could be the ``PATH=+`` syntax.
The ``[buildenv]`` has explicit ``PATH=+(path)`` syntax to let it know something is a path, and allowing to concatenate and manage things correctly in different platforms: https://docs.conan.io/2/reference/config_files/profiles.html

Also, please note that adding a list is not possible here, need to add every path in a single ``PATH=+`` line (you can use jinja2 template syntax to for-iterate over your list of paths and do this, if you prefer)

**Comment by AndersGnistrup** [comment]
Thanks for the reply. I did found a the solution and ended up with this. It is generated from a python script
```
for elem in paths:
                profile.write(f"sdkPath+=(path){elem}\n")
profile.write(f"sdkPath=!\n") # Unset variable
```

**Comment by memsharded** [comment]
Thanks for sharing the solution. However, I do not understand how unsetting the ``sdkPath`` variable just after appending to it would work, it seems the ``for`` entries would be discarded?

In any case the idea that I was suggesting with the ``jinja`` template is that you don't need an extra python script for that. It is the same profile file that can iterate the paths and define the variables. I don't know if that helps, but if you are happy with your solution, then that is good 🙂, maybe we could close the issue now?
