### ISSUE TITLE
[feature] Request: Ability to specify a git repo containing recipes as a conan remote

### ISSUE THREAD

**Issue by patmantru** [conan-io/conan#14468]
### What is your suggestion?

If I'm pulling a package from conan-center, I make sure https://center.conan.io is in my remotes list, and reference the package.  That pulls the recipe (and potentially prebuilt binaries) by talking to the conan-center conan server, and does a build of that package if appropriate prebuilt binaries are not available.

Currently (correct me if I'm wrong) the only way for me to pull recipes from my local environment is for me to run a private conan server.  While that gives me the binaries support...what if I am OK with skipping that?  It would be great if I could specify a remote as a git repo such as (again, using CCI as an example) "https://github.com/conan-io/conan-center-index", and reference the recipes there...without expecting prebuilt binaries.

That sort of reference would require that the layout of the repo was the same as the CCI layout: a 'recipes' top level directory with individual package subdirectories underneath, each containing their own config.yml, an 'all' (or whatever) directory with the conanfile.py, conandata.yml, etc, etc.  Essentially the same layout that CCI has.

This would allow using any git repo as a pseudo-conan-server.  Recipes only...no binaries.  The benefit of this is that a git repo is much easier to spin up than a private conan server.  Speaking for my situation, it's a no-brainer for me to get a new repo approved and populated in my company's open-source account on GitHub and made public, but it's nearly impossible to convince my company's security/ops folks to run a (conan or anything) server that is public access.  (A policy I am fine with BTW)

I'd GLADLY give up the prebuilt binaries for the flexibility and ease of publishing recipes with this method.  (But: big bonus points for allowing me to publish binaries too...if I'm asking, I might as well ask big...)

It seems like a very do-able thing, and I think it would add a tremendous amount of flexibility to conan.

Thanks-
Pat

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @patmantru thanks a lot for your request.

As you mentioned, this is in fact implementable, so much so that there's already a PR for it! https://github.com/conan-io/conan/pull/13930

Thanks for your description, things like this help us a lot understanding the needs of users :)

**Comment by patmantru** [comment]
Great!  Thank you!!!  I've commented in that PR, and will close this one.
