### ISSUE TITLE
[question] How to use PkgConfig files from Sysroot Package

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#14476]
### What is your question?

Hey, I have a question regarding PkgConfig in combination with sysroot packages.

During my initial research I cam across question #13962 and the related PR #13985. I understand that with this feature it is now possible to create system packages, which are pointing to a sysroot location using the PkgConfig tool provided by conan within the package_info method. 

In our setup, we are providing the cross compiling sysroots as conan packages and I would like to ask how the PkgConfig approach would look like in this case? The PkgConfigs files are already available in the sysroot and they are using the actual location of the libraries on the target device (/usr/lib .. ) as prefix paths. I would like to reuse those files in order to set the cpp_info variables in the package_info stage of the corresponding system package (e.g. zlib/system).

So I think the question can be broken down to:
1. How can be ensured that a *.pc file is found in the sysroot package when using the PkgConfig tool provided by conan within a system package
2. How would the sysroot package location in the conan cache be added to the prefix of the existing *.pc files

Or is there maybe even a more obvious solution for my problem?

Thank you very much for your help!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nicosmd 

Thanks for your question.

I think for the above to work, it would be necessary that:

- ``xxx/system`` packages contain the idiom in the PR test:
```python
def package(self):
    pkg_config = PkgConfig(self, "libastral", pkg_config_path=".")
    cpp_info = CppInfo(self)
    pkg_config.fill_cpp_info(cpp_info, is_system=False, system_libs=["m"])
    cpp_info.save(os.path.join(self.package_folder, "cpp_info.json"))
def package_info(self):
    self.cpp_info = CppInfo(self).load("cpp_info.json")
```
- ``xxx/system`` uses a ``tool_requires`` to the package containing the ``sysroot``
- The ``sysroot`` package defines in its ``package_info()`` the ``self.conf_info`` for ``tools.gnu:pkg_config`` pointing to its own folder containing the ``.pc`` files (it might need to ``append/prepend`` to not completely ovewrite it)

IMPORTANT: Note the above serialization/deserialization of ``CppInfo`` is still not documented or public, but if you want to try it to give feedback, it will be more than welcome, and it will also help to stabilize, move forward and document it.

**Comment by nicosmd** [comment]
Hey @memsharded, thank you very much for your proposal!

I tested it and want to give some feedback. 

>     * The `sysroot` package defines in its `package_info()` the `self.conf_info` for `tools.gnu:pkg_config` pointing to its own folder containing the `.pc` files (it might need to `append/prepend` to not completely ovewrite it)

* I think you meant to export PKG_CONFIG_PATH environment variable or? As I understand `tools.gnu:pkg_config` will set the pkg-config executable or am I missing something?
* when my pc file looks like
  ```text
  prefix=/usr
  libdir=${prefix}/lib
  includedir=${prefix}/include
  bindir=${prefix}/bin
  
  Name: zlib
  Description: zlib library
  Version: 1.2.13
  Libs: -L"${libdir}" -lz
  Cflags: -I"${includedir}"
  ```
  the resulting cpp_info.json contains
  ```text
    {"root": {"includedirs": [], "srcdirs": null, "libdirs": [], "resdirs": null, "bindirs": null, "builddirs": null, "frameworkdirs": null,  "system_libs": [], "frameworks": null, "libs": ["z"], "defines": [], "cflags": [], "cxxflags": [], "sharedlinkflags": [], "exelinkflags": [], "objects": null, "sysroot": null, "requires": null, "properties": null}}
  ```
  but when I use `/usr/local` as prefix it's resulting in 
  ```text
  {"root": {"includedirs": ["/usr/local/include"], "srcdirs": null, "libdirs": ["/usr/local/lib"], "resdirs": null, "bindirs": null, "builddirs": null, "frameworkdirs": null, "system_libs": [], "frameworks": null, "libs": ["z"], "defines": [], "cflags": [], "cxxflags": [], "sharedlinkflags": [], "exelinkflags": [], "objects": null, "sysroot": null, "requires": null, "properties": null}}
  ```
  I would expect that for `/usr` it looks similar to `/usr/local`. Is this a bug or intended behavior?

* I noticed that the cpp_info.json contains a `sysroot` attribute. I'm wondering what is it used for? It seems not to be set when `tools.build:sysroot` is set. That means that in the package method I need to add something like 
  ```python
  ...
  pkg_config.fill_cpp_info(cpp_info, is_system=False)
  sysroot_path = self.conf.get("tools.build:sysroot")
  cpp_info.includedirs = sysroot_path + cpp_info.includedirs
  cpp_info.libdirs = sysroot_path + cpp_info.libdirs
  ```
  by my own in order to direct the consuming packages to the sysroot dir in my conan cache. Would it make sense to automatically add the sysroot dir to those pathes when it is available in the cpp_info.json within `CppInfo(self).load(..)`? 
* As already mentioned in the other issue I have linked, it would be necessary to set `build_policy="missing"` and `upload_policy="skip"` in order to make sure that the system package is always built on the developers machines to point to the actual directory in the cache. Is it guaranteed that if the sysroot package changes (either the version, package id, recipe revision or package revision) that the related system packages are always rebuilt? Otherwise it might point to an old sysroot in the conan cache,  I guess 
* When an other package using my system package is using `PkgConfigDeps` itself in combination with the `MesonToolchain` generator would that interfere with setting `PKG_CONFIG_PATH` pointing to my sysroot *.pc files? I would expect that the MesonToolchain will always use the *.pc files generated by `PkgConfigDeps` in this case. It this forced somehow?

Thanks a lot and looking forward to your answer!

**Comment by nicosmd** [comment]
Hey again @memsharded,

I think I wasn't aware enough about how to use a sysroot with PkgConfig properly. I tried out now the following approach, which I think is what you had in mind.

First I created a pkg-config wrapper in the sysroot package containing

```bash
#! /bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export PKG_CONFIG_PATH=
export PKG_CONFIG_LIBDIR=${SCRIPT_DIR}/sysroot/usr/lib/pkgconfig
export PKG_CONFIG_SYSROOT_DIR=${SCRIPT_DIR}/sysroot

exec pkg-config "$@"
```
in the sysroot package I have 

```python
def package_info(self):
        sysroot_path = join(self.package_folder, "sysroot")
        self.buildenv_info.define("SYSROOT", sysroot_path)
        self.conf_info.define("tools.build:sysroot", join(sysroot_path))
        self.conf_info.define("tools.gnu:pkg_config", join(self.package_folder, "bin", "arm-pkg-config"))

```
so that PkgConfig helper is using the previously created wrapper. 

Finally, in the `xxx/system` package I'm using it like

```
    def package(self):
        pkg_config = PkgConfig(self, "zlib")
        cpp_info = CppInfo(self)
        pkg_config.fill_cpp_info(cpp_info, is_system=False)
        cpp_info.save(os.path.join(self.package_folder, "cpp_info.json"))

    def package_info(self):
        self.cpp_info = CppInfo(self).load("cpp_info.json")


```
and conan seems to use the pkg-config wrapper from the sysroot package and successfully fill in the cpp_info variables during the build (except when I use `/usr` as a prefix as I mentioned above, maybe this is a bug?).

**But there is still one thing missing, I guess**.  Since tool_requires are not added to the package_id automatically, the created system package might point to the wrong sysroot package, when there are multiple in use for different targets or when I update a sysroot package and want to use the newer version. So I think the sysroot must be somehow added to the package_id. I checked the documentation to find information about it but had no luck. 

Is there any way I could add the sysroot package to the package_id in the sysroot package itself?

Thanks you very much for you help.

**Comment by nicosmd** [comment]
I found a solution for the package_id problem by setting

```python
class Sysroot(ConanFile):
   build_mode = "full_mode"
```

in the sysroot package. Now the sysroot package is part of the package_ids of the consumers. 

It seems that this feature is not documented yet? I just found it in https://github.com/conan-io/conan/pull/13100 where the usage is described in the test. Anyway, the question is answered for me.

Thanks for your help!

**Comment by jasal82** [comment]
Can't get this to work reliably with `is_system=False` in the `fill_cpp_info()` invocation because most third party recipes complain about `z` or other libs not being declared as system lib. However, it also doesn't work with `is_system=True` because other recipes (like `boost`) seem to look into `cpp_info.libs` only to find the dependencies they need. This is completely broken and extremely hard to fix in a generic way.

**Comment by nicosmd** [comment]
@jasal82 are you talking about this error: 

```bash
CMake Error at build/armv8/Release/generators/cmakedeps_macros.cmake:67 (message):
  Library 'z' not found in package.  If 'z' is a system library, declare it
  with 'cpp_info.system_libs' property
```  
?

If yes this is most likely caused by a wrong library path. So I got the error when I modify the library path to something not existing. You could try to check the library path by evaluating the created `cpp_info.json` in the package path in your cache and check if the path is really existing. Also make sure the PkgConfig file looks something like 

```text
prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include
bindir=${prefix}/bin

Name: zlib
Description: zlib library
Version: 1.2.13
Libs: -L"${libdir}" -lz
Cflags: -I"${includedir}"
```
