### ISSUE TITLE
Conan 2.0 cmake tutorial doesn't build

### ISSUE THREAD

**Issue by dvhwgumby** [conan-io/conan#14471]
### Environment details

* Operating System+version: Mac os 13.5
* Compiler+version: native mac clang 
* Conan version: 2.0.9 (but doc website is 2.0) installed from 'homebrew'
* Python version: unk

### Steps to reproduce

Run the CMake tutorial instructions from a machine that has not had conan 2 installed before.

The zlib library is built in Debug configuration but the test application is built in Release.  So the application builds but cannot link.

It's a single word fix so I think not worth making a fix + pull request (plus I don't know which you prefer to change).

**Comment by memsharded** [comment]
Hi @dvhwgumby 

Thanks for your feedback.

Not very clear what the exact point of this issue is. Is it in https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html? Could you please clarify the lines? It might be just a typo/error in the docs.

**Comment by memsharded** [comment]
Hi @dvhwgumby 

If you could please clarify the error, we would like to fix the docs if necessary

**Comment by memsharded** [comment]
Closing ticket as staled, please create new tickets if there are any further question.
