### ISSUE TITLE
CMAKE_CXX_COMPILER not found when using VS Code

### ISSUE THREAD

**Issue by DominicPicard** [conan-io/conan#14483]
### What is your question?

Hi, 

I am create a package using Conan. I have a recipe conanfile.py and I am using the CMakeDeps and CMakeToolchain generators.
When I run conan install for each of my profiles, it creates a CMakeUserPresets.json containing all my configurations....

If I open the folder in Visual Studio 2022, I can see all the configuration-presets and I can build with no problems.

If I open the folder in VS Code, I am able to see the configuration-presets but there is an error in the cmake configure step: 
``` No CMAKE_CXX_COMPILER could be found ```
I really don't know why 😟 

I can open a bland hello-world cmake project created with Visual Studio (using CMakePresets) with Vs Code

I searched on all the Internet and ChatGPT but I could not find the answer 😕 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DominicPicard 

Thanks for your question.

Quick question: what cmake generator are you using, is it possible that you are defining Ninja somewhere? I think it is possible that VS Code default to Ninja, and I think this might be the reason (https://github.com/microsoft/vscode-cmake-tools/issues/2598). If VS Code default to Ninja, even if VS compiler is targeted, it is necessary to define somehow the VS version in the environment. So not exactly a VS Code issue, but a ``vscode-cmake-tools`` issue. In this case, running ``conanbuild.bat`` that will activate the right VS prompt, then launching ``code .`` in it, should be enough for VS Code to locate and use the right compiler.

**Comment by DominicPicard** [comment]
Hi @memsharded 

Thank you for your quick reply 😄 

Yes, we use Ninja.

I tried what you suggested and it works !

Thanks a lot !

**Comment by memsharded** [comment]
Great, happy to help! 😄
