### ISSUE TITLE
[question] Use Git Branch as Channel

### ISSUE THREAD

**Issue by aed2fe** [conan-io/conan#14485]
### What is your question?

Hi folks,

with conan 1 I've had the following package naming convention:
PackageName/PackageVersion@GitHubOrganisation/GitHubBranch

now I'm trying to reproduce the same behavior with conan 2. For that I've a Class defined in a python requires which is handling that in the method **set_channel_and_user** which I call in the init() method of my recipe

The method looks the following:
`def set_channel_and_user(self):
        git = Git(self, self.recipe_folder)
        remote_url = git.get_remote_url()
        package_user = re.search(r"https://github\.enterpriceCloud\.com/(\w+)/", remote_url).group(1)
        package_branch = git.run("branch --show current")
        self.channel = pascal_to_snake(package_branch)
        self.user = pascal_to_snake(package_user)`

Unfortunately this fails during package creation cause the recipe will be copied into the conan cache first and than the command ´git branch --show current´ will be executed, based on that. And for sure in the conan cache I do not have a connection to the underlying git repository anymore (the .git folder will not be copied into the cache, as it would be senseless to copy it). So the ´git branch --show current´ will fail.

Do you have an idea how I can identify the branch and set it properly?

thx

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aed2fe 

Thanks for your question.

The short answer is that for Conan 2.0, that is no longer recommended. The channel should either be dropped or defined to something fixed and immutable, not something that changes so often and dynamic as a git branch. Also, please realize that the ``conan copy`` command has been dropped in 2.0, and any kind of copy-like promotion that changes user/channel in packages is explicitly documented as not possible in https://docs.conan.io/2/knowledge/guidelines.html

If you want to capture that information, a good place would be the ``export()`` method, and then storing the branch information in the ``conandata.yml``, for example, something similar to https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html

When there are CI flows that somehow need that information there are different possibilities:
- Make it part of the version. With ``-pre.xx.yy.zz`` prereleases and ``+build.xx.yy`` builds, it is possible to add extended information to versions too, and still resolve correctly with version ranges
- When it is something "structural" and there are many packages that depend on some convention like a branch name, one of the general devops good practices is to use different server repositories, and put the packages in that server. Then, the packages can be promoted (copied) from one server to other server, without changing its identity (immutable).

If you still want to set the channel dynamically with the branch name (even if not recommended and you might find other issues down the road) you can:
- Pass it on the command line with ``--channel``
- Define it in ``set_version()`` like:
  ```python
  class Lib(ConanFile):
            name = "pkg"
            version = "0.1"
            def set_version(self):
                self.user = "myuser"
                self.channel = "mychannel"
    ```
   Check https://docs.conan.io/2/reference/conanfile/methods/set_version.html and you'll see how you can call ``Git()`` in that method.

**Comment by aed2fe** [comment]
Hi @memsharded,

Thx for the fast and detailed answer. The scm information I've in fact already put into the conandata like explained. So to use the user and channel might no longer be required and I might still be too much stuck in the conan1 way of doing things 🙈 

For my actual use case the pre and postfix of the version is a quite good alternative. I'ok play around with that for now 👍 

Thx

**Comment by memsharded** [comment]
Thanks for the feedback!

I am still adding this test https://github.com/conan-io/conan/pull/14489, to guarantee that it is still possible to define dynamically the user/channel from recipes as you were doing in Conan 1.X. Maybe that helps with the migration to Conan 2.0, which is important, and you might postpone the change of flow/version definition after the upgrade.
