### ISSUE TITLE
[bug] pip deprecation warning

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#14495]
### Environment details

* Operating System+version: `Linux debian 6.1.8-x64v3-custom-xanmod1 #1 SMP PREEMPT_DYNAMIC Tue Jan 31 19:37:53 +07 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler+version: `gcc (GCC) 11.1.0`
* Conan version: `Conan version 1.60.1`
* Python version: `Python 3.7.13`

### Steps to reproduce

`pip install --upgrade conan==1.60.1`

### Logs

```
DEPRECATION: conan is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

**Comment by memsharded** [comment]
Hi @SSE4 

Thanks for the report.

This is not a bug (yet), but a deprecation warning.

- For Conan 1.X, this will not be changed, using the ``--use-pep`` should be enough workaround
- For Conan 2.0, we need to start checking the behavior in latest pip version. It is not that clear that the made it completely fail, but it can still fallback to the build: https://github.com/pypa/pip/issues/8559, but better check it.

**Comment by memsharded** [comment]
The warning has been removed from pip, and also https://github.com/conan-io/conan/pull/15186 has added a pyproject.toml
