### ISSUE TITLE
[question] Does the code version's format in conandata.yml have to be x.x.x?

### ISSUE THREAD

**Issue by BrainLyh** [conan-io/conan#14492]
### What is your question?

Hi! I encountered an error when I tried to use the recipe from the Conan-Center.

This is the conandata.yml
```
sources:
  1.2:
    url:
    - "https://xxxx"
```
And this is the error output:
```
...
qt/5.15.9: Already installed! (33 of 34)
quazip/1.2: Calling source() in /root/.conan2/p/quazi663c722d37d46/s/src
ERROR: quazip/1.2: Error in source() method, line 57
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        KeyError: '1.2'
```

When I compile the version 1.2.0, it works well. So, does the version format have to be "x.x.x"?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @BrainLyh 

Thanks for your question.

I think the error should be elsewhere, there are versions in ConanCenter recipes that have very different versions like ``"1.0-beta4"`` or ``cci.2120202002``. It could be some error in your yaml, if you want to put everything in a repo or in a zip, so something we can reproduce, that would help.

**Comment by BrainLyh** [comment]
@memsharded ,Thanks for your reply. I have put the .yml and conandata.py files in the [zip file](https://drive.google.com/file/d/1OcXMXkIDzLQjd7VGk1b62hfkZled2aF4/view?usp=sharing). To ensure once again, I changed the version from "1.4" to "1.4.0" and ran `conan create conanfile.py --version=1.4.0`. The output is:
```
...
quazip/1.4.0: package(): Packaged 17 '.h' files
quazip/1.4.0: package(): Packaged 1 file: COPYING
quazip/1.4.0: package(): Packaged 1 '.a' file: libquazip1-qt5.a
quazip/1.4.0: Created package revision b2fdba0bc5f7efbe4733c77c9d8da8e2
quazip/1.4.0: Package 'dbb15503844fa031842df2f77648ade5115df590' created
quazip/1.4.0: Full package reference: quazip/1.4.0#967280357677f54c84d2066399778ddf:dbb15503844fa031842df2f77648ade5115df590#b2fdba0bc5f7efbe4733c77c9d8da8e2
quazip/1.4.0: Package folder /root/.conan2/p/b/quazi643fedf049a56/p
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: bzip2/1.0.8, qt/5.15.9, brotli/1.0.9, zstd/1.5.5, xkbcommon/1.5.0, odbc/2.3.11, sqlite3/3.42.0, libpq/15.3, icu/73.2, freetype/2.13.0, zlib/1.2.13, fontconfig/2.14.2, pcre2/10.42, quazip/1.4.0, libxml2/2.11.4, expat/2.5.0, libiconv/1.17, libmysqlclient/8.0.31, libjpeg/9e, md4c/0.4.8, openssl/3.1.1, lz4/1.9.4, libpng/1.6.40
WARN: deprecated:     'cpp_info.build_modules' used in: libxml2/2.11.4, bzip2/1.0.8, openssl/3.1.1, qt/5.15.9, freetype/2.13.0, lz4/1.9.4, sqlite3/3.42.0
WARN: deprecated:     'env_info' used in: libxml2/2.11.4, xkbcommon/1.5.0, bzip2/1.0.8, md4c/0.4.8, libpq/15.3, odbc/2.3.11, automake/1.16.5, libiconv/1.17, icu/73.2, openssl/3.1.1, freetype/2.13.0, m4/1.4.19, fontconfig/2.14.2, pcre2/10.42, autoconf/2.71, wayland/1.21.0, libtool/2.4.7, sqlite3/3.42.0
WARN: deprecated:     'cpp_info.filenames' used in: libxml2/2.11.4, opengl/system, sqlite3/3.42.0, freetype/2.13.0, quazip/1.4.0
WARN: deprecated:     'user_info' used in: automake/1.16.5, freetype/2.13.0
```

**Comment by memsharded** [comment]
Thanks for the feedback.

You have the versions as ``1.4`` which are float numbers in the yaml specification. You need to quote them as ``"1.4"``. Having 3 digits like ``1.4.0`` yaml understand it is not a number and treat it as string automatically.

**Comment by BrainLyh** [comment]
The problem has been solved,thank you @memsharded !
