### ISSUE TITLE
[feature] Add visionOS support

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#14496]
### What is your suggestion?

Hi! I would like to use Xcode 15 beta 6 + CMake self-compiled from latest git source (2023-08-16) with Conan to target Apple visionOS.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by stevn** [comment]
Related:

#14494

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/14504 merged, I think we can close this one? Thanks!
