### ISSUE TITLE
[question] Usage of  self.deps_cpp_info in conan version 2

### ISSUE THREAD

**Issue by AroshikaFernando** [conan-io/conan#14506]
### What is your question?

I am new to conan  and  trying to migrate conan 1.0 recipe file to conan 2.0.

**Environment Details:** 

OS Version: Red Hat Enterprise Linux 8.5 (Ootpa)
Conan Version: 2.0.7
Python Version: 3.6.8

In my conan 1.0 recipe file `self.deps_cpp_info` is used in` imports () `.

As in the conan 2.0 documentation` imports () ` method and `self.deps_cpp_info` removed from the conan 2.0.

How can I migrate `self.deps_cpp_info` to conan 2.0?

As an example, 
My sample conan 1.0 recipe file:

Solution compressor/2.0 package that depends on product zlib/1.0. The zlib recipe defines as follows. And zlib/1.0 is uploaded to the artifactory.
```
import os, yaml, shutil, subprocess, re
from conans import ConanFile, tools
from distutils.dir_util import copy_tree

class Compressor(ConanFile):
    name = "compressor"

   product_component_directory = "zlib/src/"
   exclude_files = ['*.build_conf', 'build_config/CMakeLists.txt', 'build_config/conanfile.py', 'build_config/readme', 
                               'build_config/relman.h', 'build_config/version.cpp', 'build_config/version.h']
   sourcecode_directory = "product_sourcecode"
   copy_directory = "../admin_SysGuard_Auth/src/"

   def imports(self):
        if not os.path.exists(self.sourcecode_directory):
			os.makedirs(self.sourcecode_directory)

	target_folder = self.sourcecode_directory + "/" + self.product_component_directory
	self.output.info("Executing imports() method")
	self.output.info(self.deps_cpp_info["zlib"].rootpath)
	self.copy("*", excludes=self.exclude_files, dst=target_folder, 
                             src=self.deps_cpp_info["zlib"].rootpath+'/../../export_source/src', folder=False)
	copy_tree(target_folder, self.copy_directory)
```

How do I use  `self.deps_cpp_info["tech_Secure_MAuth"].rootpath` this in `generate ()` in conan 2.o 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by fschoenm** [comment]
I think it's not very well documented but according to the migration guide (see [here](https://docs.conan.io/1/migrating_to_2.0/recipes.html?highlight=deps_cpp_info#the-generate-method)) the replacement for `self.deps_cpp_info` in Conan 2 is `self.dependencies`.

**Comment by jcar87** [comment]
HI @AroshikaFernando  thanks for asking this question.

To access the root package folder of a dependency, the equivalent in Conan 2.0 syntax would be:
```
self.dependencies["zlib"].package_folder
```

Please note that in Conan 2.0 the `import()` method has been [removed](https://docs.conan.io/1/migrating_to_2.0/recipes.html?highlight=deps_cpp_info#removed-imports-method) - instead you can apply that logic in the `generate()` method.

**Comment by AroshikaFernando** [comment]
Thank you very much @jcar87  and @fschoenm. I'll try `self.dependencies`.

**Comment by AroshikaFernando** [comment]
Hi @jcar87,

Thank you for the solution.
But,
> self.dependencies["zlib"].package_folder

I want to copy the files from export_folder not from package folder. Because in my zlib recipe file, all the source files are copied to export source folder as follow,
**conanfile.py file of zlib**
```
def export_sources(self):
        copy(self, "src/*",  src = os.path.join(self.recipe_folder, "..", ".."),  dst = os.path.join(self.export_folder, "."))
```


I tried `self.dependencies["zlib"].export_folder` , `self.dependencies["zlib"].export_source_folder` 
both of these are not working.

How can I access export_source folder from here?

**Comment by fschoenm** [comment]
You can't. You have to copy them to the package_folder in your recipe's package() method.

**Comment by AroshikaFernando** [comment]
okay. Thank you very much @fschoenm

**Comment by memsharded** [comment]
Hi @AroshikaFernando 

Please let me comment a couple of other important things:

- The ``exports_source()`` method is intended for ``self.export_sources_folder``, which is the intended location for sources.
- The ``export()`` and ``self.export_folder`` is intended exclusively for files that belong to the recipe and must be interpreted together with the recipe, like ``conandata.yml`` or some extra ``.py`` file that you want to be used by ``conanfile.py``.
- Accessing the sources of a dependency is not expected in the general case, and if there are sources to be consumed by users of the dependency, they are in general expected to be packaged in the ``package()`` method, as @fschoenm pointed out. If there is some other use case that you are intending, please let us know.

**Comment by AroshikaFernando** [comment]
Thank you very much for the explanation @memsharded.

**Comment by memsharded** [comment]
Closing as responded back then, thanks for the feedback, please create new tickets if necessary.
