### ISSUE TITLE
[question] using 'conan graph build-order' to detect required rebuilds in a dependency graph

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#14505]
### What is your question?

Hi,

this is a follow-up of https://github.com/conan-io/conan/issues/14465

Let's take a look on the following example:
app -> libb -> liba
app2 -> libc -> liba
app3 -> libd

```
conan profile detect

mkdir libA && cd libA
conan new cmake_lib -d name=liba -d version=1.0.0
conan create . -pr:h default -pr:b default -s build_type=Release
cd ..

mkdir libB && cd libB
conan new cmake_lib -d name=libb -d version=1.0.0 -d "requires=liba/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release
cd ..

mkdir libC && cd libC
conan new cmake_lib -d name=libc -d version=1.0.0 -d "requires=liba/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release
cd ..

mkdir libD && cd libD
conan new cmake_lib -d name=libd -d version=1.0.0
conan create . -pr:h default -pr:b default -s build_type=Release
cd ..

mkdir app && cd app
conan new cmake_exe -d name=app -d version=1.0.0 -d "requires=libb/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release
cd ..

mkdir app2 && cd app2
conan new cmake_exe -d name=app2 -d version=1.0.0 -d "requires=libc/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release
cd ..

mkdir app3 && cd app3
conan new cmake_exe -d name=app3 -d version=1.0.0 -d "requires=libd/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release
cd ..
```

now we create lockfiles for the apps:
```
cd app && conan lock create . && cd ..
cd app2 && conan lock create . && cd ..
cd app3 && conan lock create . && cd ..
```

simulate a bugfix of libA:

```
cd libA
sed -i 's/1.0.0/1.0.1/g' conanfile.py
conan create . -pr:h default -pr:b default -s build_type=Release
cd ..
```

and update the lockfiles:
```
cd app
conan lock add --requires=liba/1.0.1 --lockfile conan.lock --lockfile-out updated-conan.lock
conan graph build-order . --lockfile updated-conan.lock --format=json > order.json
cd ..
cd app2
conan lock add --requires=liba/1.0.1 --lockfile conan.lock --lockfile-out updated-conan.lock
conan graph build-order . --lockfile updated-conan.lock --format=json > order.json
cd ..
cd app3
conan lock add --requires=liba/1.0.1 --lockfile conan.lock --lockfile-out updated-conan.lock
conan graph build-order . --lockfile updated-conan.lock --format=json > order.json
cd ..
```

after that we merge the generated build-orders:
```
conan graph build-order-merge --file app/order.json --file app2/order.json  > order.json
```

which outputs:
```
liba/1.0.1#2ffc261317d0cbdcc417854fcebc07a8:308ccc1b7065dbcf54f86f902c83ab6fcd18d025 - Cache
libb/1.0.0#ee48ab2412286fc1006e654d60639b6b:9a2d157c72e528e9af7d554c0bdf53f596db9b8d - Cache
libc/1.0.0#9d81df2874e73b749ee0ae8a86d05ac9:9a2d157c72e528e9af7d554c0bdf53f596db9b8d - Cache
```

So no rebuilds required? When exactly is a rebuild required? I think I also tried some changes in the dependency graph the other day, instead of the bugfix of liba above, and still there was no module mentioned which should be rebuild.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tbsuht 

Thanks for your question.

> So no rebuilds required? When exactly is a rebuild required? I think I also tried some changes in the dependency graph the other day, instead of the bugfix of liba above, and still there was no module mentioned which should be rebuild.

Indeed. No library has to be built under these assumptions because:
- The default are static libraries
- The version bump is a patch version. A patch version means a change in .cpp internal implementation, no change in the APIs
- Static libraries do not link against other static libraries.

If you added the ``app`` packages into the flow, create packages from it, and compute the build-order including them (you can do it with ``conan graph build-order --requires=app/1.0 ...``, then you will see that the ``app`` packages need to be rebuild from sources.

**Comment by tbsuht** [comment]
@memsharded Wow, that helps a lot! Can't wait to test this in our CI :)

> The default are static libraries

Already forgot about that, then the output makes sense.

> The version bump is a patch version

Great, I can see that when using minor bumps the output changes. So basically the semver definition is used to determine what needs to be rebuild? Or do you really compare e.g. whether something changed in the dependency graph?
E.g. if libA increases the minor version and what was added is a new cpp function which requires a new dependency to link against. Is the "rebuild" then propagated until the app?
[edit] just checked. Seems to work! You only need to add the new dependency also to the lockfiles.

For the sake of completeness, the following is a complete example for dynamic linking, for anyone who is struggling with these new features. The version bump of `libA` can be controlled by changing the variable "LIBA_FIX_VERSION"

```
conan profile detect

rm -rf ./app*
rm -rf ./lib*

conan remove "app*" -c
conan remove "liba" -c
conan remove "libb" -c
conan remove "libc" -c
conan remove "libd" -c

mkdir libA && cd libA
conan new cmake_lib -d name=liba -d version=1.0.0
conan create . -pr:h default -pr:b default -s build_type=Release -o shared=True -o *:shared=True
cd ..

mkdir libB && cd libB
conan new cmake_lib -d name=libb -d version=1.0.0 -d "requires=liba/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release -o shared=True -o *:shared=True
cd ..

mkdir libC && cd libC
conan new cmake_lib -d name=libc -d version=1.0.0 -d "requires=liba/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release -o shared=True -o *:shared=True
cd ..

mkdir libD && cd libD
conan new cmake_lib -d name=libd -d version=1.0.0
conan create . -pr:h default -pr:b default -s build_type=Release -o shared=True -o *:shared=True
cd ..

mkdir app && cd app
conan new cmake_exe -d name=app -d version=1.0.0 -d "requires=libb/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release -o *:shared=True
cd ..

mkdir app2 && cd app2
conan new cmake_exe -d name=app2 -d version=1.0.0 -d "requires=libc/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release -o *:shared=True
cd ..

mkdir app3 && cd app3
conan new cmake_exe -d name=app3 -d version=1.0.0 -d "requires=libd/[>=1.0.0 <2.0.0]"
conan create . -pr:h default -pr:b default -s build_type=Release -o *:shared=True
cd ..

# freeze current app graphs
cd app && conan lock create --requires app/1.0.0 -pr:h default -pr:b default -s build_type=Release -o *:shared=True && cd ..
cd app2 && conan lock create --requires app2/1.0.0 -pr:h default -pr:b default -s build_type=Release -o *:shared=True && cd ..
cd app3 && conan lock create --requires app3/1.0.0 -pr:h default -pr:b default -s build_type=Release -o *:shared=True && cd ..

# create a bugfix
cd libA
LIBA_FIX_VERSION="1.0.1"
sed -i "s/1.0.0/$LIBA_FIX_VERSION/g" conanfile.py
conan create . -pr:h default -pr:b default -s build_type=Release -o shared=True
cd ..

# create build-order
cd app
conan lock add --requires=liba/$LIBA_FIX_VERSION --lockfile conan.lock --lockfile-out updated-conan.lock
conan graph build-order --requires app/1.0.0 --lockfile updated-conan.lock -pr:h default -pr:b default -s build_type=Release -o *:shared=True --format=json > order.json
cd ..
cd app2
conan lock add --requires=liba/$LIBA_FIX_VERSION --lockfile conan.lock --lockfile-out updated-conan.lock
conan graph build-order --requires app2/1.0.0 --lockfile updated-conan.lock -pr:h default -pr:b default -s build_type=Release -o *:shared=True --format=json > order.json
cd ..
cd app3
conan lock add --requires=liba/$LIBA_FIX_VERSION --lockfile conan.lock --lockfile-out updated-conan.lock
conan graph build-order --requires app3/1.0.0 --lockfile updated-conan.lock -pr:h default -pr:b default -s build_type=Release -o *:shared=True --format=json > order.json
cd ..

# merge build-order
conan graph build-order-merge --file app/order.json --file app2/order.json --file app3/order.json > order.json
```

**Comment by memsharded** [comment]
> Great, I can see that when using minor bumps the output changes. So basically the semver definition is used to determine what needs to be rebuild? Or do you really compare e.g. whether something changed in the dependency graph?

Conan uses only the versions, it doesn't really analyze the source code for changes. The developers are responsible for versioning accordingly the changes they did in code.

> E.g. if libA increases the minor version and what was added is a new cpp function which requires a new dependency to link against. Is the "rebuild" then propagated until the app?

Yes, Conan propagates transitively what needs to be re-build when something changes, based on versions, package-types, require-traits, etc.

> For the sake of completeness, the following is a complete example for dynamic linking, for anyone who is struggling with these new features. The version bump of libA can be controlled by changing the variable "LIBA_FIX_VERSION"

Thanks very much for sharing this!
We still need to create a whole new section in the docs dedicated to these CI flows, this will be helpful.

Maybe the issue can be closed now as resolved? Thanks!
