### ISSUE TITLE
[question] How to specify cppstd using github actions

### ISSUE THREAD

**Issue by mcottontensor** [conan-io/conan#14502]
### What is your question?

I have a github action that pulls the latest conan and creates a default profile. The profile defaults to cppstd=14 but some of the deps I have require cppstd=17.
Previously I would do a `conan profile update settings.compiler.cppstd=17 default` but this has been removed in conan2.
How am I supposed to handle this now? Is there any way to override this on the CLI or in my projects config somewhere? In the conanfile.txt maybe?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @mcottontensor thanks a lot for your question.

There are a number of ways to handle values of settings coming from a profile for CI:
 * The recommended approach is to generate a profile that matches your needs and the environment Conan will run in, push it to a repository, and as part of the Conan setup, run `conan config install url-to-repo` ([Docs here](https://docs.conan.io/2/reference/commands/config.html#conan-config-install)). This will download said repo as part of Conan, and the profiles, deployers, custom commands etc present there will be available for use. This is really useful to achieve future reproducibility of builds, as the exact profiles used will be properly tracked by your SCM
 * Another way is to directly pass your desired value in the CLI. This would be done with the `-s compiler.cppstd=17` argument to your `conan install/create`

(Note that you can also use tools such as `sed` to replace lines in a file, but that's not recommended)

Let me know if this solves your issue, but feel free to ask further questions if you need to :)

**Comment by AbrilRBS** [comment]
Closing as solved, please feel free to reopen/create new issues should you have further questions, thanks!
