### ISSUE TITLE
[question] CMakeDeps and RelWithDebInfo

### ISSUE THREAD

**Issue by robert-shade** [conan-io/conan#14501]
### What is your question?

Hi, we're looking to convert our project to Conan 2 and have run into an issue.

We do our `conan install` with `--settings build_type=Release`, but we actually configure cmake in our project with `-DCMAKE_BUILD_TYPE=RelWithDebInfo`.

This was not a problem with the `cmake_find_package` generator (probably because it wasn't multi-configuration aware).  Is there some way we can make this work?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by robert-shade** [comment]
I came up with this, which creates a second CMakeDeps and changes the configuration.  Is it ok to do something like this?

```python
def generate(self):
        cmake = CMakeDeps(self)
        cmake.generate()

        if self.settings.build_type == "Release":
            cmake2 = CMakeDeps(self)
            cmake2.configuration = "RelWithDebInfo"
            cmake2.generate()
```

**Comment by memsharded** [comment]
Hi @robert-shade 

If I understood your issue, the right approach is to tell conan with:
```
conan install . -s build_type=Release -s &:build_type=RelWithDebInfo
```
You can use your explicit ``-s pkgname*:build_type=RelWithDebInfo`` if you prefer, ``&`` is a placeholder for the "consumer" conanfile

**Comment by robert-shade** [comment]
Thanks!
