### ISSUE TITLE
[question] skip_test Default Behavior

### ISSUE THREAD

**Issue by KevDi** [conan-io/conan#14513]
### What is your question?

Is there a reason why by default `skip_test` does not define the `BUILD_TESTING` Variable and set it to off? 
On the other hand if i set `skip_test = True` it sets the Variable to `OFF`.

I found it a bit strange to explicitly Test the String to be off in my CMakeLists.txt because first i added this 
```
if(BUILD_TESTING)
    enable_testing()
    add_subdirectory(tests)
```

But with the default behavior this will not build my tests.
Would it not be better to explicitly set the `BUILD_TESTING`?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @KevDi 

Thanks for your question.

What should be the default of this:
```python
def build(self):
    cmake = CMake()
    cmake.configure()
    cmake.build()
    cmake.test()
```
We think that the expected default is to actually build and run tests.
So the ``skip_test`` conf is an "opt-out". You need to explicitly set it to ``True``. When it is ``True``:
- The ``cmake.test()`` is a no-op
- Define ``cache_variables["BUILD_TESTING"] = "OFF"``

> On the other hand if i set skip_test = False it sets the Variable to OFF

I cannot reproduce this, I have tried with:
```python
def test_toolchain_conf_skip_test_true():
    client = TestClient()

    client.save({"conanfile.py": GenConanfile().with_generator("CMakeToolchain")})
    client.run("install . --name=mylib --version=1.0  -c tools.build:skip_test=False")

    presets = json.loads(client.load("CMakePresets.json"))
    cache_variables = presets["configurePresets"][0]["cacheVariables"]
    assert "BUILD_TESTING" not in cache_variables
```
And when skip_test=False, then "BUILD_TESTING" is not defined at all. Could you please double check it?

**Comment by KevDi** [comment]
Hello @memsharded 

i made a mistake in my question of course it should be ``skip_test=True`` i edit also the question 👍 
The problem i had was that i usually do this ``if(BUILD_TESTING)`` things in my ``CMakeLists.txt`` and with your mentioned default behavior of the ``conan build``  method my tests were not build because the Variable was not set. I have to explicitly check if it is not set to "OFF" like in the tutorial mentioned.

**Comment by memsharded** [comment]
Conan tries to be as aligned with the default CMake behavior as possible. It is not expected that Conan defines this variable by default (it is created when including ctest: https://cmake.org/cmake/help/latest/module/CTest.html), it only defines the value when it is necessary to change the default behavior. Maybe you just need to include ctest?

If not, yes, the check described in the Conan docs is:
```cmake
    if (NOT BUILD_TESTING STREQUAL OFF)
        add_subdirectory(tests)
    endif()
```

**Comment by KevDi** [comment]
Ok yes that makes sense. I include the CTest but i did it also inside the `if (BUILD_TESTING)` block. So maybe the solution would be to move it out of this block. And thanks for the explanation it helps me to better understand conan and it now makes sense to my why this variable is not set by default via Conan.

**Comment by memsharded** [comment]
Great, thanks for the feedback!
Maybe we can close now this issue as solved?

**Comment by KevDi** [comment]
yes would be ok for me
