### ISSUE TITLE
How can I modify the transitive options of a dependency

### ISSUE THREAD

**Issue by schmidjo82** [conan-io/conan#14516]
### What is your question?

I am using grpc and on Windows and need to specify protobuf as shared but the grcp package does not use protobuf as shared. 
How can I specify that in my requirements
    def requirements(self):
        self.requires.add("protobuf/3.21.9",override=True)
        self.options["protobuf"].shared=True
        self.requires.add("grpc/1.51.3")
        print(vars(self.options["grpc"])

        self.options.shared=True
        self.requires.add("boost/1.81.0")

The problem is if I set this here, the grpc package is still with protobuf static and therefore it contains symbols that should not be there. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @schmidjo82 thanks a lot for your question.
When asking these kinds of questions, it's usually better to specify the Conan version you are using. I'll be assuming Conan 2, but this should work in every modern Conan 1.x version too :)


You can suggest options values for your dependencies in a few ways:

 * In your recipe's `configure()` method, you can do something like this ([From the docs](https://docs.conan.io/2/reference/conanfile/methods/configure.html)):
 ```python
 def configure(self):
   self.options["grpc/*"].shared = True
 ```
 * You can also define it in your recipe's `default_options` attribute ([From the docs](https://docs.conan.io/2/reference/conanfile/methods/configure.html)):
 ```python
 default_options = {"grpc/*:shared": True}
 ```
 * If you're the one building the package and have control over the Conan invocation, you can add an extra argument `-o "grpc/*:shared=True"` (Explained a bit [here](https://docs.conan.io/2/reference/commands/install.html#profiles-settings-options-conf))
 * Similarly, if you use a specific profile, adding `grpc/*:shared=True` to the `[options]` section will achieve the same result (Explained a bit [here](https://docs.conan.io/2/reference/commands/install.html#profiles-settings-options-conf))

Hope this helps, let me know if you need further clarification on any of the points.

**Comment by AbrilRBS** [comment]
Closing as solved as I didn't hear back from you, but please feel free to re-open/create a new issue should you have additional questions, thanks! :)

**Comment by Innokentiy-Alaytsev** [comment]
For people from the future: currently the [behaviour has changed](https://github.com/conan-io/conan/issues/10283) and it is recommended to use profile for setting transitive dependencies options. It is possible to combine profiles, so the options can be stored in a separate profile file and passed alongside other profiles.
