### ISSUE TITLE
I can't get conan download to work

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#14515]
### What is your question?

Hi,

Working with Conan 2.0 and JFrog Artifactory, I have a problem with using conan download.

`conan download "mypkg/1.0.0" -r my_remote`

Results in

`ERROR: 500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. [Remote: my_remote]`

And the same with patterns like "mypkg/1.0.0#*" (Even though I did not understand well the use of # and wildcard * here)

`mypkg/1.0.0` is in the remote, I uploaded it myself, can list it, and it is also correctly downloaded automatically when it is a required dependency for some other package.

What am I doing wrong?

PS: I am also unclear about the use of quotes, because for example when I upload a package, they don't seem necessary. I also see differences in Linux vs Windows about this

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @lucabarbiero,

Thanks for the question. Could you please report which Artifactory version you are using? I think this could be related to a known compatibility issue of Conan 2.X and Artifactory fixed in Artifactory 7.52 (see https://github.com/conan-io/conan/issues/11370 and https://github.com/conan-io/conan/issues/12029)

Hope this helps!

**Comment by freihamer** [comment]
Hi @czoido,

All right I have 7.27.10. So I understand that I should ask JFrog an upgrade to 7.52 or newer to fix this issue?

**Comment by czoido** [comment]
> Hi @czoido,
> 
> All right I have 7.27.10. So I understand that I should ask JFrog an upgrade to 7.52 or newer to fix this issue?

Yes, please, it was fixed in Artifactory 7.52, with Conan 2.X you should use a version higher than that
