### ISSUE TITLE
[question] conan create `--keep-source` and `--keep-build` flags no longer available in conan 2

### ISSUE THREAD

**Issue by Poolmann** [conan-io/conan#14518]
### What is your question?

Hi, the title already describes it pretty well.
I couldn't find any information on why these flags are no longer available, so I decided to ask here.
Was this an active philosophical/technical decision, or is there any alternative that I am oblivious of?

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Poolmann 

Thanks for your question.
Those arguments are legacy optimizations from a time where the local development flow was not as mature as it is today. With the new ``layout()`` and ``generate()`` methods, the recommended way to develop and test most of the ``conanfile.py`` functionality is the local flow with ``conan install``, ``conan source``, ``conan build``.

So those arguments are no longer necessary for ``conan create``, which will always do the full flow including the fetching of the sources and building from sources. Recall that modern Conan also has some other caching mechanisms for downloads.

**Comment by Poolmann** [comment]
Thank you very much, that makes sense!
