### ISSUE TITLE
[bug] Possible Bazel toolchain deficiencies

### ISSUE THREAD

**Issue by valgur** [conan-io/conan#14519]
Copying over some observations regarding the Bazel generators / build system from one of the few CCI recipes targeting a Bazel-based project: https://github.com/conan-io/conan-center-index/pull/17575#discussion_r1205539939

* The `tools.build:compiler_executables` config values were not being applied.
* The `cppstd` value was not being translated into a `--std=c++14` build flag, as is done with `CMakeToolchain`. I might simply be using the `BazelToolchain` incorrectly, though.
* There's no obvious way (to me at least) how the build results should be installed for `package()` using Bazel. I added some explicit `copy()` commands in the conanfile for this. 

Conan version: 2.0.4

### Steps to reproduce

1. Clone https://github.com/embarktrucks/embag/compare/master...valgur:embag:conan
2. Run `conan create` on the recipe.

**Comment by memsharded** [comment]
Thanks @valgur for the report.
It is very likely that the Bazel integration is far less mature than other integrations. @franramirez688 has pending some work to revisit the integration and some of the open tickets around it.

**Comment by franramirez688** [comment]
Hi @valgur 

Thanks a lot for reporting this!

All your points should be solved by https://github.com/conan-io/conan/pull/14958, but the latest one:

> There's no obvious way (to me at least) how the build results should be installed for package() using Bazel. I added some explicit copy() commands in the conanfile for this.

Bazel has no explicit mechanism to do that, so it's not still obvious to make it automatically. I hope that future versions of Conan can automatize it in a better way.

**Comment by valgur** [comment]
> Hi @valgur 
> 
> Thanks a lot for reporting this!
> 
> All your points should be solved by https://github.com/conan-io/conan/pull/14958, but the latest one:
> 
> > There's no obvious way (to me at least) how the build results should be installed for package() using Bazel. I added some explicit copy() commands in the conanfile for this.
> 
> Bazel has no explicit mechanism to do that, so it's not still obvious to make it automatically. I hope that future versions of Conan can automatize it in a better way.

Thank you for the hard work on this, @franramirez688! Looks like everything I previously mentioned has been addressed and the issue can be closed.
