### ISSUE TITLE
inconsistency between exe behavior and python behavior in conan install

### ISSUE THREAD

**Issue by EthanHemo** [conan-io/conan#1452]
Hi,

I'm trying to build my code with the following command:
conan install <full_package_name> --build <full_package_name>

I'm using this command to be able to build from the cache the code (and package) without building the dependencies and to be able to package the whole thing at the end.

While on my machine where python is install the command succeed, in the server where conan exe installed is i get the following error:
ERROR: No package matching '<full_package_name>' pattern

Is there any workaround i can use?

Thanks,
Ethan.

**Comment by memsharded** [comment]
Could you please specify your full line? Something like:
```bash
$ conan install HelloPkg/0.1@user/channel --build HelloPkg
```

In any case, let me suggest that if you are creating packages, the recommended way is to use ``conan test_package`` command, that will run that ``install`` to build the package, but also test it, which is very convenient.

There are some minor quirks of the binary packages (created with pyinstaller), so that is why the python pip packages are much more recommended. Probably it could be related.

**Comment by EthanHemo** [comment]
Hi, 

So my command will be (from your example):
conan install HelloPkg/0.1@user/channel --build HelloPkg/0.1@user/channel

And the error i received was:
ERROR: No package matching 'HelloPkg/0.1@user/channel ' pattern.

I have yet to try to try the test_package, and for pip install, i would prefer not to install python on the CI servers at the moment, but i'm sure the different behavior was made from this (had something similar with my python program i made to exe).

Thanks,
Ethan.

**Comment by lasote** [comment]
Try to use quotes for the pattern, We experienced similar problems in other commands.

**Comment by EthanHemo** [comment]
I've tried the following: 
conan install HelloPkg/0.1@user/channel --build "HelloPkg/0.1@user/channel"

Same results.

**Comment by memsharded** [comment]
I think the issue is that the ``--build`` argument operates only on package names, or at least it checks for it. So the command should be with ``--build HelloPkg`` not with the full package reference

**Comment by EthanHemo** [comment]
It worked! 
Thanks :)

**Comment by memsharded** [comment]
Great, thanks for telling! Is there somewhere in the docs or help that made you understand to use ``--build`` with the full package reference? Maybe we should fix that if it is the case

**Comment by EthanHemo** [comment]
No it was my own try and error when i saw it could compile on my machine.
However i had hard time to find out a way to compile and package the code since i tried to compile it from my folder and not the local cache but it didn't do the whole flow of install, build and package. it just build and finished there.

I will check the test_package thought since it might do what i need.

Thanks.

**Comment by memsharded** [comment]
good, please check it also with the ``conan new`` command, it really helps getting started creating packages. So:

```bash
$ conan new Hello/0.1@user/channel -t
$ conan test_package
```
would create your first package from a github repo (see source code)
```bash
$ conan search 
$ conan search Hello/0.1@user/channel 
```
Use ``conan new -s`` to create an example with the source code inplace, not from external repo.
Cheers!

**Comment by EthanHemo** [comment]
I'm not sure that i understood the process. 
Should i checkout the code from my repository (svn in my case), use `conan build` and then use `conan test_package` ?
Because i saw that the command `conan build` didn't export my code or any package to my local cache, and im afraid that the command `conan test_package` will try to find the artifacts from the local cache and won't package the build i just had.

**Comment by memsharded** [comment]
No, ``conan build`` is just a local, helper command. You don't need it now.
``conan test_package`` will first run an export, then install, then build the project inside ``test_package`` folder to make sure the package was correctly created. If you need to jump to chat, please tell (send an email)

**Comment by EthanHemo** [comment]
I'm afraid it will have to wait to Monday.
Can you tell me an email to send to?
I could help me greatly to implement Conan in my organization :)

**Comment by memsharded** [comment]
Sure, just write us to info@conan.io :)
