### ISSUE TITLE
[feature][2.0.9] settings_target accessible in the compatibility method

### ISSUE THREAD

**Issue by adnan-ali1** [conan-io/conan#14527]
### settings_target in compatibility

Hello,

Currently compatibility method does not allow a tool to be made compatible across various target settings, I have tested a use case with the following patch and it seems to work. Please have a look, if this makes sense then I can also create a PR for it.

Changes at the following locations are made. Uploading a patch file isnt allowed here, so I am trying to explain here :) 

1. when a settings_target is added to the conan package it has to be done via package_id method. So when this is added then add this to both info and original_info objects
2. when cloning the info object, if settings_target are available then clone them as well
3. allow settings_target to be passed from compatibility method in conanfile.py 

```
diff --git a/conans/client/graph/compatibility.py b/conans/client/graph/compatibility.py
index 51de09ee9..fe7c4fa0a 100644
--- a/conans/client/graph/compatibility.py
+++ b/conans/client/graph/compatibility.py
@@ -99,6 +99,7 @@ class BinaryCompatibility:
             # use the compatible ones
             conanfile.info = c
             conanfile.settings = c.settings
+            conanfile.settings_target = c.settings_target
             conanfile.options = c.options
             run_validate_package_id(conanfile)
             pid = c.package_id()
@@ -123,4 +124,7 @@ class BinaryCompatibility:
                 if options:
                     compat_info.options.update(options_values=OrderedDict(options))
                 result.append(compat_info)
+                settings_target = elem.get("settings_target")
+                if settings_target:
+                    compat_info.settings_target.update_values(settings_target)
         return result
diff --git a/conans/client/graph/compute_pid.py b/conans/client/graph/compute_pid.py
index 8dc42beb6..0bad23c84 100644
--- a/conans/client/graph/compute_pid.py
+++ b/conans/client/graph/compute_pid.py
@@ -63,6 +63,10 @@ def compute_package_id(node, new_config):

     run_validate_package_id(conanfile)

+    if (conanfile.info.settings_target):
+        # settings_target has beed added to conan package via package_id api
+        conanfile.original_info.settings_target = conanfile.info.settings_target
+
     info = conanfile.info
     node.package_id = info.package_id()

diff --git a/conans/model/info.py b/conans/model/info.py
index 0c2de4634..a900d0e18 100644
--- a/conans/model/info.py
+++ b/conans/model/info.py
@@ -325,6 +325,7 @@ class ConanInfo:
         result.build_requires = self.build_requires.copy()
         result.python_requires = self.python_requires.copy()
         result.conf = self.conf.copy()
+        result.settings_target = self.settings_target.copy() if self.settings_target else None
         return result

     def dumps(self):
--
```

Thanks.
Adnan Ali

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @adnan-ali1 

Thanks for your request.

It is true that at the moment the ``compatibility()`` is only exposing and managing the minimum ``settings`` + ``options``, but not other elements. We typically wait for more real world use cases and requests for it, to make sure the right thing is being added.

I agree it makes sense to add ``settings_target`` to the equation for the cases you expose. Yes, it would be great, as you already did most of the work, if you could submit a PR to ``release/2.0`` branch to include it, thanks very much for the offer to contribute!

**Comment by adnan-ali1** [comment]
Sure, it would be my pleasure to contribute. I will create a PR for this.
