### ISSUE TITLE
[question]How to control the compilation optimization level in Conan v2?

### ISSUE THREAD

**Issue by BrainLyh** [conan-io/conan#14534]
### What is your question?

Hello, I'd like to ask if there is a way to control the compilation optimization level in Conan v2. For example, can we set the compilation optimization level to `-O3`? 

Through searching related issues https://github.com/conan-io/conan/issues/9366#issue-958478300 and corresponding answers, I found in the Conan v1 documentation that it seems possible to achieve this using `package_id()`. https://docs.conan.io/1/creating_packages/define_abi_compatibility.html
```
from conans import ConanFile
class Pkg(ConanFile):
    options = {"optimized": [1, 2, 3]}
    default_options = {"optimized": 1}
    def package_id(self):
        for optimized in range(int(self.options.optimized), 0, -1):
            compatible_pkg = self.info.clone()
            compatible_pkg.options.optimized = optimized
            self.compatible_packages.append(compatible_pkg)
```

Is it also achievable in Conan v2, or are there any relevant parameters that can be used when executing the `conan create` command?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @BrainLyh 

The above example using a ``optimized`` option is just a generic example how to use ``options``, but it shouldn't be necessary in most cases.

The general recommendation would be to rely on ``build_type`` defined optimizations, like ``Release, Debug, ...``, not on individual compiler flags. The ``build_type`` in many build systems like CMake or MSBuild already takes care of defining the optimization. What build system are you using? Isn't using the ``build_type`` a possibility for you?

**Comment by BrainLyh** [comment]
Hi @memsharded 

Thank you for your response. I am using CMake. When the `build_type` is set to Release or Debug, the corresponding default optimization level should be `-O3` or `-O0`. 

I changed the `build_type` to Debug for compilation testing, and the testing was successful. If I need the optimization level to be `-O2`, is it not possible to make that choice?

**Comment by memsharded** [comment]
> I changed the build_type to Debug for compilation testing, and the testing was successful. If I need the optimization level to be -O2, is it not possible to make that choice?

This is something that is typically managed at the build-system/toolchain level. In this case, to model the ``Debug`` build-type in CMake to use -O2.

But if you want to define and inject your own custom compilation flags from Conan it is possible with the ``tools.build:cxxflags``, ``tools.build:cflags``, ``tools.build:sharedlinkflags`` and ``tools.build:exelinkflags``. You define them in your profile ``[conf]`` section, and Conan will try its best to pass it to the different integrations, like ``CMakeToolchain`` in the CMake case.

**Comment by BrainLyh** [comment]
Hi @memsharded 

`tools.build:cflags` seemes could be used to set the optimization level.

**Comment by daltonv** [comment]
> Hi @memsharded
> 
> `tools.build:cflags` seemes could be used to set the optimization level.

Doesn't this actually not work for CMake? I see the optimization level I put here gets placed on the compile line, but CMake looks like it places the build type specific flags at the end of the compile line. This means the `CMAKE_C_FLAGS_DEBUG` value will override any `-O` options thrown by `CMAKE_C_FLAGS` option that gets filled by conan. 

It seems like the only way to resolve this is to manually set `CMAKE_C_FLAGS_DEBUG` (or release, minsizerel, etc) to an empty string. 

If I want all my conan packages to have the, for example, Debug profile have the same optimization level and that level is different than CMakes default maybe it would be better to have a `tools.cmake.cmaketoolchain.debugcflags` config option.

**Comment by memsharded** [comment]
Indeed there is a conflict here, with the optimization flags and the CMake build type, which has higher priority. It is true that the idea is that optimization flags shouldn't be changed via flags if the CMake build type abstraction is used, but using compile options instead (but that we don't have an abstraction over that)

Quick question, haven't you considered just using the ``RelWithDebInfo`` build type instead? It does what it seems you want, to have Debug information, but optimized.

**Comment by GrinlexGH** [comment]
Have the same issue. Im using `Ninja Multi-Config` generator, which by default uses `CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo"`, so I cant use MinSizeRel, but if im trying to change `CMAKE_CONFIGURATION_TYPES` with `extra_variables` it doesnt affect to compile options, because extra variables block located lower than `extra_flags_init` block

```cmake

########## 'extra_flags' block #############
# Include extra C++, C and linker flags from configuration tools.build:<type>flags
# and from CMakeToolchain.extra_<type>_flags

# Conan conf flags start: MinSizeRel
string(APPEND CONAN_CXX_FLAGS_MINSIZEREL " -march=native -mtune=native -s")
string(APPEND CONAN_C_FLAGS_MINSIZEREL " -march=native -mtune=native -s")
# Conan conf flags end


########## 'cmake_flags_init' block #############
# Define CMAKE_<XXX>_FLAGS from CONAN_<XXX>_FLAGS

foreach(config IN LISTS CMAKE_CONFIGURATION_TYPES)
    string(TOUPPER ${config} config)
    if(DEFINED CONAN_CXX_FLAGS_${config})
      string(APPEND CMAKE_CXX_FLAGS_${config}_INIT " ${CONAN_CXX_FLAGS_${config}}")
    endif()
    if(DEFINED CONAN_C_FLAGS_${config})
      string(APPEND CMAKE_C_FLAGS_${config}_INIT " ${CONAN_C_FLAGS_${config}}")
    endif()
    if(DEFINED CONAN_SHARED_LINKER_FLAGS_${config})
      string(APPEND CMAKE_SHARED_LINKER_FLAGS_${config}_INIT " ${CONAN_SHARED_LINKER_FLAGS_${config}}")
    endif()
    if(DEFINED CONAN_EXE_LINKER_FLAGS_${config})
      string(APPEND CMAKE_EXE_LINKER_FLAGS_${config}_INIT " ${CONAN_EXE_LINKER_FLAGS_${config}}")
    endif()
endforeach()

...

########## 'extra_variables' block #############
# Definition of extra CMake variables from tools.cmake.cmaketoolchain:extra_variables

set(CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo;MinSizeRel")
```

~~So I have to use user toolchain :(~~
And I cant use user toolchain for my dependencies

**Comment by memsharded** [comment]
Hi @GrinlexGH 

This is a closed ticket, it is not clear what is the action, if this is just a comment for others, or a question.

Quick question, why not adding:
```cmake
set(CMAKE_CONFIGURATION_TYPES "Debug;Release;MinSizeRel" 
    CACHE STRING "Supported configuration types" FORCE)

project(MyProject)
```
Directly in your ``CMakeLists.txt``?
(please open a ticket with further details if you would like this to be a discussion or new question)
