### ISSUE TITLE
[question] Resolve Version Conflicts Caused by Indirect Dependencies

### ISSUE THREAD

**Issue by PengZheng** [conan-io/conan#14535]
### What is your question?

The migration of [Celix](https://github.com/apache/celix/tree/feature/483-conan-2-support) to Conan 2 continues.
When I try to install all components' dependencies by the following commands, version conflict results:

```
 conan install .  -pr:b default -pr:h default -o celix/*:build_all=True  -of cmake-build2/
 
ERROR: Version conflict: civetweb/1.15->openssl/1.1.1t, celix/2.3.0->openssl/3.1.2.
```

Note that Celix itself does not depend on openssl directly. The other user of openssl might be libcurl, which Celix depends on.
And civetweb's usage of openssl is purely an implementation detail (it can use other TLS implementation instead) Celix does not care about.

The documentation suggests that we fix this problem in a consuming conanfile, which is Celix in this particular case.
However, a Celix user can opt out civetweb and libcurl by disabling certain options.
Directly adding `self.requires("openssl/1.1.1t")` will force our user to depend on openssl, which is not ideal (a user should only depend on what he/she needs).
As mentioned above, usage of openssl is purely implementation details of openssl and libcurl, which we should not care about.
I'd rather not mention openssl in our conanfile at all. 

Conan 1.0 provides `--require-override` command line option, while Conan 2.0 does not.
In enterprise environments, `--require-override` is valuable. 
Otherwise we must force many teams to update their conanfiles (many of which are published long ago) in case of emergency upgrade of openssl to fix some CVE.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PengZheng 

Thanks for your report.

Actually the approach might be different. We have started some time ago to allow version-ranges like ``openssl/[>=1.1 <4]`` in ConanCenter, to avoid discrepancies and conflicts in different packages requiring ``openssl`` and at the same time allow to move quickly the whole ConanCenter to the latest openssl when it is released.

In this case, it seems you are using dependencies from ConanCenter, and ``civetweb`` seems is not updated yet to require a version range. The best would be to fix ``civetweb`` in ConanCenter so you don't need anything as a consumer and all of your transitive dependencies naturally converge to latest openssl package. Are you a contributor of ConanCenter already, maybe you want to contribute it yourself?

**Comment by PengZheng** [comment]
> Are you a contributor of ConanCenter already, maybe you want to contribute it yourself?

Yes, I have contributed before. It turns out that civetweb does not support openssl 3 yet (https://github.com/conan-io/conan-center-index/pull/17077#discussion_r1176501352):

```python
            if Version(self.version) < "1.16":
                self.requires("openssl/1.1.1t")
            else:
                self.requires("openssl/[>=1 <4]")
```

Note that 1.16 is the latest civetweb. 

I'm OK to leave the ultimate downstream to resolve it. How could I make Celix's CI (both Conan1 and Conan2) happy without `--require-override`?
https://github.com/apache/celix/blob/feature/483-conan-2-support/.github/workflows/ubuntu.yml
Note also that Celix is not `game` in the documentation's example, it is just an `engine` used by other downstream games.
https://docs.conan.io/2/tutorial/versioning/conflicts.html

Now I use the following as a stop gap:
```python
    def requirements(self):
        # omit other requirements
        lst = [x.ref.name for x in self.requires.values()]
        if "libcurl" in lst or "civetweb" in lst:
            self.requires("openssl/1.1.1t")
```
But this is really less than ideal:

1. Dependency on openssl is implementation details Celix does not care about.
2. The downstream could opt out libcurl/civetweb's dependency on openssl, but now it is forced by us.

I'm expecting many cases like civetweb in my corporate deployment of Conan, which is currently still Conan 1.0.

**Comment by memsharded** [comment]
The recommended way is ``self.requires("openssl/1.1.1t", override=True)``, because that only changes the upstream dependency if it exists (no need to do any conditional), but it will not introduce a direct dependency from the current package at all, and it will not force its usage if the upstream doesn't depend on openssl. This should work in both Conan 1.X and 2.0, please try it and let us know.

**Comment by PengZheng** [comment]
Yes, it worked. 
And I check documentation of Conan 1 and Conan 2: both mentions this approach, and latter documentation make it even more explicit. Thank you very much for the very patient guidance  and nice explanation.

**Comment by memsharded** [comment]
Thanks for the feedback! 🙂
