### ISSUE TITLE
[question] How to get msvc update version?

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#14545]
### What is your question?

I want to check in my recipe which msvc update a current compiler has.

A concrete usecase: a recipe should have a different logic depending if msvc version is 16.11.27 or 16.11.29.

A related question: if there are two parallel msvc installations (let's take again 16.11.27 and 16.11.29), how do I specify in my conan profile to use a specific one?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @AndreyMlashkin 

I think there are different questions here.
The new ``msvc`` compiler setting contains an "update", you can access it with ``self.settings.compiler.update`` (which is between 0-9)
This update complements the main ``compiler.version``, which is 190-193. Together they will form the ``_MSC_VER`` that looks like 1934

According to https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B, there is no difference in _MSC_VER for those minor IDE versions:
<html>
<body>


Visual Studio 2019 version 16.11.24 | 16.11.24 | 2019 | 1929 | 192930148 | 14.29
-- | -- | -- | -- | -- | --
Visual Studio 2019 version 16.11.27 | 16.11.27 | 2019 | 1929 | 192930151 | 14.29


</body>
</html>

That means that in theory the toolset, compiler, etc is the same, and the difference is in the IDE application, but that shouldn't affect how the binaries are built, and consequently, doesn't need to be managed by Conan recipes. Do you have some further insights why it is that important to depend on the minor IDE version for the build?

**Comment by AndreyMlashkin** [comment]
> The new `msvc` compiler setting contains an "update", you can access it with `self.settings.compiler.update` (which is between 0-9)


That does not work with conan  1.60.2:
```
        print(self.settings.compiler.update)
        ConanException: 'settings.compiler.update' doesn't exist for 'Visual Studio'
'settings.compiler' possible configurations are ['runtime', 'toolset', 'version']
```

**Comment by AndreyMlashkin** [comment]
I have two build tools installed as follows:

![MicrosoftTeams-image](https://github.com/conan-io/conan/assets/3842441/7632b0e3-3296-4f5c-b073-9af7baaeea6f)

It seems, I can't differentiate them from conan profile now.

**Comment by AndreyMlashkin** [comment]
Maybe it would be better, I have created two tickets from the beginning..

**Comment by memsharded** [comment]
> That does not work with conan 1.60.2:

It works with the ``msvc`` compiler setting, not with the ``Visual Studio`` compiler setting.


The tools 14.36 is represented by ``msvc``, ``compiler.version=193``, ``compiler.update=6``. v14.36 <=> 19.36
The tools 14.37 is represented by ``msvc``, ``compiler.version=193``, ``compiler.update=7`` v14.37 <=> 19.37

**Comment by AndreyMlashkin** [comment]
> > That does not work with conan 1.60.2:
> 
> It works with the `msvc` compiler setting, not with the `Visual Studio` compiler setting.
> 
> The tools 14.36 is represented by `msvc`, `compiler.version=193`, `compiler.update=6`. v14.36 <=> 19.36 The tools 14.37 is represented by `msvc`, `compiler.version=193`, `compiler.update=7` v14.37 <=> 19.37

Thanks! That's what I just figured out by myself, but thank you anyway!

As I understand, there is no difference, right? It's just a different way of using it, it's the same CL executable in the end?

**Comment by memsharded** [comment]
> As I understand, there is no difference, right? It's just a different way of using it, it's the same CL executable in the end?

Not sure about that I think it can actually be a different CL executable, likely to contain only bugfixes or new standard impl, so probably completely binary compatibility in most cases

**Comment by AndreyMlashkin** [comment]
I mean, between 'Visual Studio' and 'msvc'

**Comment by memsharded** [comment]
> I mean, between 'Visual Studio' and 'msvc'. 

Yes, they are 2 ways to model the same compiler. Except ``Visual Studio`` don't have the ``update`` level.

**Comment by AndreyMlashkin** [comment]
Ok, thank you for your answers! That really helped!
