### ISSUE TITLE
[question] Can not cp the conan cache after an uncomplete conan upload

### ISSUE THREAD

**Issue by Adam-Maroni** [conan-io/conan#14546]
### What is your question?

Hello, 
I use **conan version 1.59** to fetch dependencies and build package throughout a **Jenkins CI pipeline**.
The package I build is a **C++ project.**
I rencently encounter a problem.

My CI pipeline is working on a **Docker Linux container agent, itself running on a  linux machine**. Once the container ready and running, I will use the following commands:
**conan create ...** -> Create the package
**conan upload ..**. -> To upload the package on our remote package repository
**cp -r <conan cache location of the created package> ./build** -> To copy the content of generated build files from the local conan cache to the build folder of my repository.

I noticed a strange behaviour. The copy of conan cache may or may not fails depending on the returns of conan upload command.
More precisely, if conan package successfully upload on the remote, for example: 

_conan upload <package_name>/<version>@<location_on_remote> --all -r=<remote>
Uploading to remote <remote> :
Uploading <package_name>/<version>@<location_on_remote> to remote <remote>
Recipe is up to date, upload skipped
Uploading package 1/1: <package_id> to '<remote>'
Compressing package...
Uploading ... ->  <package_name>/<version>@<location_on_remote>:<package_id>
Uploading ... ->  <package_name>/<version>@<location_on_remote>:<package_id>
Uploading ... ->  <package_name>/<version>@<location_on_remote>:<package_id>_

Then the copy will succeed, finding the conan cache location. 
But, if the conan upload skipped the upload of the package:

_conan upload <package_name>/<version>@<location_on_remote>--all -r=<remote>
Uploading to remote <remote> :
Uploading <package_name>/<version>@<location_on_remote> to remote <remote>
Recipe is up to date, upload skipped
Uploading package 1/1: <package_id> to '<remote>'
Package is up to date, upload skipped_

Then the copy will fails, saying "_cp: cannot stat '/root/.conan/data/<package_name>/<version>/<location>/build/*': No such file or directory._

Do you have any idea why this happens?
Thank you.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Adam-Maroni 

Quick question:

> cp -r ./build -> To copy the content of generated build files from the local conan cache to the build folder of my repository.

Why do you do that? In most cases it is not necessary, even discouraged to do that, it can be quite problematic. There are also other tools like ``generate()`` or ``deployers`` that can help and are designed to copy things from Conan packages into user space. If you could please elaborate what is the use case, that could help.

Also it is not very clear where, when and how you are executing that ``cp``, and what are the arguments, I don't fully understand how it is used.

**Comment by Adam-Maroni** [comment]
Hello @memsharded, thank you for your reply.

To elaborate, the reason why I try to copy the conan local cache is due to the architecture use. As I am working in a CI context which use a Docker container (mounted on the Jenkins workspace), once the Jenkins Job is over, the container will be closed, and the entire conan local cache will be lost. 
I wish to save that local cache so it could be accessible from the Jenkins workspace stored on the linux agent (this way I could have "archives" from what had been generated during the build).

Hope it clarifies the situation a little more.
Thanks again for your help.

**Comment by memsharded** [comment]
But the generated files by generators like CMakeDeps will be pointing to the cache, so copying them to another location makes them way more difficult to use. Have you read about https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html? Maybe you want to deploy the copy of your packages to your local folder?

**Comment by Adam-Maroni** [comment]
Yes, indeed.

After some research, it appears that it was just a misunderstanding of basic conan behavior. When I try to build a package that is already present in the remote, it fetches the generated files but does not store them in the exact same location it was during a completely new build. 

Now I know that, all that is left, is deciding what should be the CI behavior when package is fetch rather than build.

Once again, thank you for your help!

**Comment by memsharded** [comment]
No prob, happy to  help! 🙂
