### ISSUE TITLE
[question] how to consume prebuilt package in msvc debug config?

### ISSUE THREAD

**Issue by lxrui** [conan-io/conan#14540]
### What is your question?

I have create a prebuilt tbb package with conan:
```
class tbbConan(ConanFile):
    name = "tbb"
    version = "2020.1"
    settings = "os", "arch"

    def layout(self):
        _os = str(self.settings.os).lower()
        self.folders.source = "include"
        if (_os == "android"):
            self.folders.build = os.path.join("lib", _os, android_abi(self))
        else:
            self.folders.build = os.path.join("lib", _os)

    def configure(self):
        if self.settings.os == "iOS":
            self.settings.os.version = "10.0"
            self.settings.os.sdk = "iphoneos"
        elif self.settings.os == "Android":
            self.settings.os.api_level=21

    def package(self):
        copy(self, "*", self.source_folder, os.path.join(self.package_folder, "include"))
        copy(self, "*tbb.*", self.build_folder, os.path.join(self.package_folder, "lib"))

    def package_info(self):
        self.cpp_info.libs = ["tbb"]
        self.cpp_info.set_property("cmake_file_name", "tbb")
        self.cpp_info.set_property("cmake_target_name", "tbb")
        if self.settings.os == "Android" or self.settings.os == "iOS":
            self.cpp_info.set_property("cmake_find_mode", "both")

    def package_id(self):
        if self.info.settings.os == "Macos" or self.info.settings.os == "iOS":
            del self.info.settings.arch
```
When I try to consume this package in msvc with debug mode, msvc will report a link error while compile:
> LINK : fatal error LNK1104: cannot open file “tbb_debug.lib” 

There is no 'tbb_debug.lib' in the tbb package, and I'm not going to provide one.
I want to know **where is the "_debug" suffix from and how can I do to remove the "_debug" suffix in debug mode**.

ps: The Release/RelWithDebInfo mode is working fine in msvc and the macos do not have this problem. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lxrui 

Please let me comment a couple of things:

```python
       if self.settings.os == "iOS":
            self.settings.os.version = "10.0"
            self.settings.os.sdk = "iphoneos"
        elif self.settings.os == "Android":
            self.settings.os.api_level=21
```

Settings are read-only. Values for settings cannot be defined in recipes: https://docs.conan.io/2/knowledge/guidelines.html
You can use a ``profile.py`` plugin, or jinja profiles.

> LINK : fatal error LNK1104: cannot open file “tbb_debug.lib”

That seems hardcoded in the consumer of this package, not in this package. Could you please provide a full reproducible example, that includes the dowsntream consumer, so we can check it?

**Comment by lxrui** [comment]
@memsharded I have upload the demo to [ConanDemo](https://github.com/lxrui/ConanDemo), you can reproduce the problem follow `README.md`

**Comment by memsharded** [comment]
Thanks for the feedback and the project to reproduce.

The main issue is that you are using the legacy Conan 1.X ``cmake-conan`` integration with Conan 2.0. Please read the warning in the README of the project, and go to the https://github.com/conan-io/cmake-conan/tree/develop2 branch to find the new integration for Conan 2.0. It is still work-in-progress, but the way to go, the previous integration will not work.

I would also strongly recommend to not start with the ``cmake-conan`` integration. First make it work with the standard ``conan install`` + ``cmake ...`` (using Conan generated presets or Conan generated ``conan_toolchain.cmake`` as explained in the https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html. Once this is working smoothly, it might be possible to try to integrate the new ``cmake-conan`` develop2 integration (I still prefer the explicit ``conan install`` flow, but if desired the way to go is the new integration).

Please try that and let us know.

**Comment by lxrui** [comment]
@memsharded I have updated the consume demo to use `conan_provider.cmake` script on branch "conan_provider" of [ConanDemo](https://github.com/lxrui/ConanDemo), but it dose not make any difference.
And the standard `conan install` + `cmake ...` flow is also not working

**Comment by memsharded** [comment]
Sorry, I don't see the changes applied yet, are you sure you pushed them?
In https://github.com/lxrui/ConanDemo/blob/main/consume/consume_demo/conan_install.cmake, I can still see ``include(${CMAKE_CURRENT_LIST_DIR}/../cmake/conan.cmake)`` and calling ``conan_cmake_configure(`` which is not the new Conan 2.0 cmake-conan integration using providers.

**Comment by lxrui** [comment]
**Checkout to branch 'conan_provider'** plz.
The [consume/consume_demo/CMakeLists.txt](https://github.com/lxrui/ConanDemo/blob/conan_provider/consume/consume_demo/CMakeLists.txt) was no longer include the `conan_install.cmake`,
use `cmake -G "Visual Studio 15 2017 Win64" -B build -S . -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=..\cmake\conan_provider.cmake` instead

**Comment by memsharded** [comment]
I think I found the issue.
The tbb headers contain:
```c++
#if _MSC_VER
    #if ! __TBB_NO_IMPLICIT_LINKAGE
        #ifdef _DEBUG
            #pragma comment( linker, "/nodefaultlib:tbb_debug.lib" )
            #pragma comment( linker, "/defaultlib:tbbproxy_debug.lib" )
        #else
            #pragma comment( linker, "/nodefaultlib:tbb.lib" )
            #pragma comment( linker, "/defaultlib:tbbproxy.lib" )
        #endif
    #endif
#endif
```

Which is hardcoding the name of the library for debug. There are a couple of different possible approaches here:
- Use and define the ``__TBB_NO_IMPLICIT_LINKAGE``. You can do it in the tbb recipe in ``self.cpp_info.defines``
- Follow the convention and make sure that the library artifact is called like that.

I think it is more correct the first one, the pragma to the linker in the code has always felt bad imho.

**Comment by lxrui** [comment]
Thank you so much, problem solved.
