### ISSUE TITLE
[question] how to install from conan_package.tgz (not covered in docs)

### ISSUE THREAD

**Issue by yshurik** [conan-io/conan#14548]
### What is your question?

I have locally on my machine:

- conanmanifest.txt
- conaninfo.txt
- conan_package.tgz

(downloaded from package registry)

How I can install the package from these files locally into my conan environment?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @yshurik 

Thanks for your question.

Those files are an internal implementation detail. You cannot download them manually and install them in a local Conan environment. The way to install those files in your Conan environment is to ``conan remote add <registry>`` and then ``conan install`` them. There is metadata, folder structure and other stuff that needs to be managed in the install process, and that cannot happen from those files only.

**Comment by yshurik** [comment]
I can not add the registry because the package is not there now.
But files which I have locally are same that conan downloaded from the registry when it was there.
How to install them now? from local files? it is just same.

**Comment by memsharded** [comment]
No, I am afraid it is not the same.
To re-instantiate a package in a repo in theory it would be needed:

Files:
- The conanfile.py recipe that created it
- The ``conandata.yml`` if used in the conanfile
- The ``conanmanifest.txt`` of the recipe (not the package)

Metadata:
- Recipe name, version, user and channel
- Recipe revision
- Recipe revision timestamp
- Package-ID
- Package-revision
- Package-revision timestamp

Even if we had all this information, there is no automated or built-in way to recover it, it would need a lot of hacking to inject those things into an active cache.

**Comment by yshurik** [comment]
Okay, but then what would be correct way to save package from registry (or from local cache) to local files/archive and then install it into conan when it is needed?
(without rebuild of course)

**Comment by memsharded** [comment]
There is no way at the moment to save a package to files/archive, it is necessary to store them in registries. We might consider that in the Conan 2.X roadmap (you can track https://github.com/conan-io/conan/issues/4316 if you want).

**Comment by memsharded** [comment]
This has been implemented in https://github.com/conan-io/conan/pull/14923, for next 2.0.14 release.
