### ISSUE TITLE
[question] How can I use conan to download a build file (.hex) from a package stored in a server and deploy to a specific folder? Cannot find it in docs

### ISSUE THREAD

**Issue by marcobossi071189** [conan-io/conan#14552]
### What is your question?

Hi!
I have conan installed and I am trying to build up a process to download and flash a .hex file from the server (without re-building it).
I used conan download to download the package
conan list gives me the list of packages related to the package name I selected
How can I then obtain to copy the /bin folder inside the package to a local folder?
Did not find the answer in docs, conan install --name "<packagename>" --deployer full_deploy asks for a conanfile or a reference
I do not have the original conan.py recipe and don't want to get it locally, as it would require other files which are constructed specifically for building the source.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @marcobossi071189 

Thanks for your question

> I have conan installed and I am trying to build up a process to download and flash a .hex file from the server (without re-building it).

This is not very clear. You have a .hex file packaged inside a Conan package, in a Conan server?

> How can I then obtain to copy the /bin folder inside the package to a local folder?

Maybe the ``conan cache path <package-ref>`` that gives you the path to your package in the cache is enough?

> Did not find the answer in docs, conan install --name "" --deployer full_deploy asks for a conanfile or a reference

The syntax to install a package is ``conan install --requires=mypkg/myversion --deployer=full_deploy``, have you tried it?

**Comment by marcobossi071189** [comment]
Hi @memsharded
Thanks for answering and sorry for confusion or the maybe trivial question :)
Yes, I have a .hex file packaged inside a Conan package in a server
I tried to use conan cache path with the package ref, but I wondered if there is a better way, as using this I have to first download the package, then find the package id I need (which I would like it to just be the latest one instead of searching for it), and finally locate the cache and copy the folder.
Is there a direct way with conan install  ?  
I tried conan install --requires=mypkg/myversion --deployer=full_deploy but it starts looking for dependencies to build the package, and I do not want that - I'd like it to just retrieve the existing latest package folder and copy to the path specified through --deployer-folder

**Comment by memsharded** [comment]
> I tried to use conan cache path with the package ref, but I wondered if there is a better way, as using this I have to first download the package, then find the package id I need (which I would like it to just be the latest one instead of searching for it), and finally locate the cache and copy the folder.

Yes, the ``conan download`` doesn't evaluate profiles, so it needs the full ``pkg/version:package_id`` to download the binary tat you want, then do ``conan cache path pkg/version:package_id``, to get the path. The important point here is that yes, you need to know the ``package_id`` of the binary you want to use. Not necessarily the latest, the ``package_id`` represents a binary configuration for given settings and options.

> I tried conan install --requires=mypkg/myversion --deployer=full_deploy but it starts looking for dependencies to build the package, and I do not want that - I'd like it to just retrieve the existing latest package folder and copy to the path specified through --deployer-folder

But if the package binary is there, and the dependencies are modeled correctly, everything should be "skip" and only the recipes will be used to actually compute the package_id is the correct one for your settings and that it doesn't need to rebuild from source. Isn't this the case?

The thing is that ``conan install`` does the evaluation of the graph based on the input profiles with settings and options, then computes the ``package_id`` and decides what needs to be built or downloaded. It is not possible to ``conan download`` based on profiles without fully evaluating the graph to compute the ``package_ids`` as ``package_ids`` also depends on dependencies versions.

So it depends on what flow you prefer:
- If you know the ``package_id``, then you can use ``conan download`` + ``conan cache path`` (if you prefer you can easily create a custom command to wrap all the operations for you, this is super powerful and convenient: https://docs.conan.io/2/reference/extensions/custom_commands.html#reference-commands-custom-commands
- If you don't know the ``package_id`` and you have the input profiles with settings and options, then a ``conan install`` is necessary to compute the graph and compute the ``package_id``, so the ``full_deploy`` or ``direct_deploy`` can be used here. If the package models the right way the dependencies traits, Conan should be able to skip the retrieval of all the dependencies binaries, making it very fast.

**Comment by marcobossi071189** [comment]
thanks @memsharded, I understood what was wrong: basically the package I was trying to use was a wrong one. 
using conan install --requires=<package name and version> --deployer=direct_deploy --deployer-folder <target folder>  and by adding profile and info I can obtain exactly what I wanted.
Thanks again!

**Comment by memsharded** [comment]
Excellent, happy that it is working now, thanks for the feedback!
