### ISSUE TITLE
[question] Define CMake variables for a recipe in config / profile?

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#14558]
### What is your question?

Is it possible to define additional CMake variables for a recipe or globally in the conan configuration or profiles in conan 1.60.2 or does that require the recipe to do that?
Say I want to use a recipe from conan center which build using cmake, but does not expose a conan option for setting the cmake variable, can I still somehow set the cmake variable to the desired value?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

Thanks for your question.

yes, there is a way to inject arbitrary variables, via the ``CMakeToolchain`` configuration:

- Create a ``myvars.cmake`` file with the variables you want, put it together with your profile
- Define the conf ``tools.cmake.cmaketoolchain:user_toolchain+={{ os.path.join(profile_dir, "myvars.cmake") }}`` in your profile, needs .jinja extension in Conan 1.X

**Comment by memsharded** [comment]
Proving it works in a test in https://github.com/conan-io/conan/pull/14563

**Comment by memsharded** [comment]
Closed automatically by https://github.com/conan-io/conan/pull/14563, but please let us know, reopen or create a new issue if further questions.
