### ISSUE TITLE
Allow "anonymous" downloads from personal bintray repository

### ISSUE THREAD

**Issue by p-brz** [conan-io/conan#1455]
It is possible to configure my personal bintray repository to allows "anonymous" downloads?

To download recipes/binaries from "official" repositories, like conan-center and conan-transit,
i do not need to configure any user/authentication. 
But for my repository, looks like i need to use: `conan user -p <API_KEY> -r <REMOTE> <USER>` .

So, anyone that want to download recipes from my repo, needs to have a bintray account? :(

Or am i missing something?

**Comment by memsharded** [comment]
Hi!

All downloads from public bintray repositories can be anonymous. You only need credentials for uploading (or removing) to the repos. What error messages are you getting? Are you sure you added the correct remote URL for the repositories you want to access?

**Comment by p-brz** [comment]
Sorry, i probably did something wrong at the time. :flushed: 
When i tried, the client was asking to change the user from anonymous (or something like that). 

Now i tried again and have no problems (just added the repository: `conan remote add <REMOTE> <MY_REPO>`)

So, i am closing this. Thanks for the support. :+1:

**Comment by memsharded** [comment]
No worries :)
Just ask any doubt or further question you have, or if you need help. Cheers!
