### ISSUE TITLE
[question] Git.get_commit() result with subprojects

### ISSUE THREAD

**Issue by db4** [conan-io/conan#14559]
### What is your question?

If I use `Git.get_commit()` with `self.folders.subproject` set, it returns not the last commit of the whole git repo, but the last one in the subproject's subdirectory. It is because of
```python
            commit = self.run('rev-list HEAD -n 1 --full-history -- "."')
```
in `get_commit()` implementation. Is it intentional? I would prefer `rev-list HEAD -n 1 --full-history` which always returns the last commit of the whole repo.

Why do I need this? I export packages with
```python
    def export(self):
        path = os.path.join(self.export_folder, "conandata.yml")
        if not os.path.exists(path):
            git = Git(self, self.recipe_folder)
            scm_url, scm_commit = git.get_url_and_commit()
            update_conandata(self, {"sources": {str(self.version): {"commit": scm_commit, "url": scm_url}}})
```
which currently does not work correctly for subprojects.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question

This is intentional. When there is a repo with multiple subprojects sub1...subN, and a package is created from every subproject, then, a new recipe revision will create for each one, and the commit they use will be stored in the respective ``conandata.yml``, so it will affect the recipe revision of every package.

Now a change is done to the repo, just to one of the subprojects. If we recreate again all the packages, they should all get the same revision as before, except the one that has been changed. If the ``get_commit()`` gets the whole repo commit, it will then change the revision of every package for every subproject, when in reality it wouldn't be necessary, as they didn't change at all. Using the latest commit of the folder containing the subproject guarantees that only the subprojects with changes create new revisions.

**Comment by db4** [comment]
Hi @memsharded 

> This is intentional. When there is a repo with multiple subprojects sub1...subN, and a package is created from every subproject, then, a new recipe revision will create for each one, and the commit they use will be stored in the respective `conandata.yml`, so it will affect the recipe revision of every package.
> 
> Now a change is done to the repo, just to one of the subprojects. If we recreate again all the packages, they should all get the same revision as before, except the one that has been changed. If the `get_commit()` gets the whole repo commit, it will then change the revision of every package for every subproject, when in reality it wouldn't be necessary, as they didn't change at all. Using the latest commit of the folder containing the subproject guarantees that only the subprojects with changes create new revisions.

On the other hand, creating a new package is a manual operation that is usually done only when the subproject is modified. If repo changes affect the subproject's `conandata.yml`, what's wrong with it? Look, having a subproject doesn't guarantee that there is no dependency on the other part of the repo. For instance, I have a common git submodule that all subprojects use. If I modify its linked revision, `Git.get_commit()` currently doesn't see any changes. IMHO, that violates the principle of "least surprise".

**Comment by memsharded** [comment]
> On the other hand, creating a new package is a manual operation that is usually done only when the subproject is modified. If repo changes affect the subproject's conandata.yml, what's wrong with it?

There is nothing wrong with it, it is exactly what needs to happen. When the subproject is modified, it affects the conandata.yml, and it creates a new recipe revision for that subproject. That is perfect, is exactly what needs to happen.

>  Look, having a subproject doesn't guarantee that there is no dependency on the other part of the repo.

Of course, but it is necessary to define a default. The most expected scenario we have found is that when a subproject changes, users don't want to rebuild all packages in the repo, only the one that has been modified (and dependants if necessary). 
If you want a different behavior, it is easy, the ``Git`` helper is a very thin wrapper around ``git`` command line, you can just run ``commit = git.run("rev-list ...)`` with your own command and get the commit of the whole repo. Just please be aware that it will be very inefficient and requires a lot of unnecessary rebuilds of binaries, but if it is the behavior that you want, it is easy to do. But in my opinion it is better default to not have to rebuild all subprojects when 1 did change than the opposite.

As a guide, in case you would like to implement something that allows optimal re-building with that layout reusing code from a common folder in the project, it would be something like this:
- Capture in ``export()`` method, with 2 calls to git to get the commits of both the current subproject and the "common" folders
- Store the 2 commits in the ``conandata.yml``
- In the ``source()`` method, do 2 checkouts, one commit after the other, and do a clean copy of the contents of the respetive subproject and "common" folders.

**Comment by db4** [comment]
Ok, your point is clear. I will implement the necessary logic myself.
