### ISSUE TITLE
Unable to use conan command

### ISSUE THREAD

**Issue by InTheLittleWood** [conan-io/conan#1456]
So I was trying to install Plex Media Player on my Ubuntu 32-Bit machine and used pip to install conan, however after installation. When I use conan, it states

`No command 'conan' found, did you mean:
 Command 'conman' from package 'conman' (universe)
conan: command not found`

Solved by reinstalling pip and then reinstalling conan

**Comment by memsharded** [comment]
Hi!

I guess something went wrong with python/pip while installing, might depend on your Ubuntu distro, the python version, probably something failed at installation, did you use "sudo"...

As it seems it is solved now, there is no action required from us at the moment, so it can be closed. Thanks!
