### ISSUE TITLE
[question] package "xxx" created and package_id relation

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#14565]
### What is your question?

in my own jfrog I see:
![image](https://github.com/conan-io/conan/assets/27768261/2598eed7-e3a7-4bce-aa03-af780294b313)

![image](https://github.com/conan-io/conan/assets/27768261/832c3570-ec2b-4118-8fdf-dafe3e8a0560)
if "eea*" is the package revision, then "29ec*" represent what?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

That is the ``package_id``. You can read more about it in https://docs.conan.io/2/tutorial/creating_packages/configure_options_settings.html

Revisions are explained here: https://docs.conan.io/2/tutorial/versioning/revisions.html

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
