### ISSUE TITLE
can't find 'opencv/4.1.2@sim/stable' in remotes

### ISSUE THREAD

**Issue by SwordJoe** [conan-io/conan#14562]
### What is your question?

i am a new coder. my company use conan to manage packages，some errors occurred when i execute this command
`conan install ../conanfile-insource.py --build missing -if ./`

errors message is:
`opencv/4.1.2@sim/stable: Not found in local cache, looking in remotes...`
`opencv/4.1.2@sim/stable: Trying with 'conancenter'...`
`ERROR: Failed requirement 'opencv/4.1.2@sim/stable' from 'conanfile-insource.py'`
`ERROR: Unable to find 'opencv/4.1.2@sim/stable' in remotes`

part of conanfile-insource.py is:
`    def requirements(self):
        if self.options.using_its800_opencv == False:
            self.requires.add("opencv/4.1.2@sim/stable")`

 My conan's default profile is:
`[settings]`
`os=Linux`
`os_build=Linux`
`arch=x86_64`
`arch_build=x86_64`
`compiler=gcc`
`compiler.version=7`
`compiler.libcxx=libstdc++11`
`build_type=Release`
`[options]`
`[build_requires]`
`[env]`

so why does it happened? i am very confused.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @SwordJoe 

Thanks for your question
It seems what the error is saying. You are depending on the ``"opencv/4.1.2@sim/stable"`` package, but that package is not found anywhere. For sure it doesn't exist in ConanCenter, so it should be in one of your private remotes:
- List your remotes with ``conan remote list``, add the necessary remote (of your company or your team)
- Make sure the package you need is in that remote, check your remote ``conan list opencv* -r=myremote`` (Conan 2.0 syntax)

Also it seems that you are using old syntax and not recommended expressions. It should be more like:
```python
def requirements(self):
    if not self.myoption:  # NOT == False
          self.requires("opencv...")  # NOT requires.add
```

**Comment by SwordJoe** [comment]
yes, u are right. I make a test just now. I change all packages to Official repo, and execuate cmd:
`conan install ../conanfile-insource.py --build missing`

But another error occurs, here is the error description:
`ERROR: Error loading conanfile at '/home/qiaojian/simiris_cv/simcv/conanfile-insource.py': Unable to load conanfile in /home/qiaojian/simiris_cv/simcv/conanfile-insource.py`
`File "<frozen importlib._bootstrap_external>", line 678, in exec_module`
`File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed`
`File "/home/qiaojian/simiris_cv/simcv/conanfile-insource.py", line 3, in <module>`
    `from conans import ConanFile, CMake, tools`
`ImportError: cannot import name 'ConanFile'`

It says can't import 'ConanFile', my "conanfile-insource.py" is:
`from conans import ConanFile, CMake, tools`

my Python version is Python3.6, and my conan version is 2.0.9

so why? thank you

**Comment by memsharded** [comment]
> from conans import ConanFile, CMake, tools

As pointed out above, you are running quite old and legacy ``conanfile.py``. The ``from conans`` import has been completely removed in Conan 2.0, that belongs to some old Conan 1.X version (it shouldn't even be used in latest Conan 1.60). You can read about the migration to 2.0 in https://docs.conan.io/1/conan_v2.html
