### ISSUE TITLE
[bug] CMakeDeps: Target name '<name>' already exists

### ISSUE THREAD

**Issue by BobIsOnFire** [conan-io/conan#14560]
### Environment details

* Operating System+version: Oracle Linux 8
* Compiler+version: gcc 8
* Conan version: 2.0.9
* Python version: 3.6

#### Minimal project example

```
.
├── CMakeLists.txt
└── conanfile.txt
```

`conanfile.txt`:

```ini
[requires]
libarchive/3.6.2

[options]
libarchive/*:with_lz4 = True

[generators]
CMakeDeps
```

`CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.15)

project(test)

find_package(LibArchive REQUIRED)
find_package(lz4 REQUIRED)
```

#### Commands

* `conan install . --output-folder ./conan/ --build missing`
* `cmake -B ./build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=$(pwd)/conan -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON`

### Logs

Logs from `cmake` command:

```
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'LibArchive::LibArchive'
-- Conan: Target declared 'ZLIB::ZLIB'
-- Conan: Target declared 'Iconv::Iconv'
-- Conan: Target declared 'LZ4::lz4_static'
CMake Warning at conan/lz4Targets.cmake:25 (message):
  Target name 'lz4::lz4' already exists.
Call Stack (most recent call first):
  conan/lz4-config.cmake:16 (include)
  CMakeLists.txt:8 (find_package)


-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/user/repro/build
```

`lz4` targets have been already created as a dependency of `LibArchive` targets, hence a warning comes when I explicitly run `find_package(lz4 ...)` there. Note that I don't see a warning if I replace `lz4` with `ZLIB`, looks like this is because `lz4::lz4` name is defined in `cmake_target_aliases`. Also, `find_package(... QUIET)` doesn't suppress the warning.

Is the warning really needed here? Is there any misuse that it is trying to catch? Do you have any advice on how I could suppress it?

P.S. I guess I created a duplicate of #12958... Feel free to close my issue if you want.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/14644

**Comment by Nekto89** [comment]
will this fix be backported to conanv1?
