### ISSUE TITLE
[feature] bring back conan inspect --raw and/or --attribute

### ISSUE THREAD

**Issue by geir-t** [conan-io/conan#14573]
### What is your suggestion?

Hi!

In conan1 to get e.g. the version of a package we could do:
```
$ conan inspect . -a version
version: 0.0.2+dirty.1.sha.a6750c5
$ conan inspect . --raw version
0.0.2+dirty.1.sha.a6750c5
```
This was very useful since having an easy way of getting the version simplifies our CI code. Every time we do a conan create we need some way of knowing what version was created to do conan upload etc.

Best regards

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @geir-t 

Conan 2.0 is providing new means to achieve that, without relying on the inspect:

- ``conan create --format=json`` will give you a detailed json, you might want to get the info you want from that json
- Most times, it is not necessary to parse the json. The ``PackagesList`` feature will create a list of packages that need to be uploaded after the ``conan create`` and you can pass that list to ``conan upload`` directly
- This has the advantage that it also works for multiple packages, like if you do ``--build=missing``, it also knows how to upload all the packages that were built from source.

So the ``PackagesLists`` approach will give you an built-in solution for that use case.

If you still want to use the inspect for automated work, the recommendation is to use the ``--format=json`` and obtain the information from there. It is way more robust and unified across different Conan commands.

**Comment by geir-t** [comment]
Thank you for the answer. We will probably end up creating our own conan extension and in the mean time use `conan inspect . --format json | jq .version`

**Comment by memsharded** [comment]
I am curious, why not using the built-in ``PackagesLists`` approach? It implements exactly this use case of ``conan create`` + ``conan upload`` the created package.

**Comment by geir-t** [comment]
First of all because then we would have to change the current workflow everywhere. This was the easiest solution for now. 

The approach you outlined looks to do exactly what we need though, so I tested it out, but it seems to still have problems.

First issue is that because the recommended solution is to pipe to file we can no longer use standard print commands inside the conanfiles. Still, after removing these and verifying that the json was correct it still did not work.
```
conan create .  --format json > list-json
conan upload -l list-json -r guppy-conan-virtual --dry-run
ERROR: 'Local Cache' doesn't exist is package list

```
```

{

    "graph": {
        "nodes": {
            "0": {
                "ref": "conanfile",
                "id": "0",
                "recipe": "Cli",
                "package_id": null,
                "prev": null,
                "rrev": null,
                "rrev_timestamp": null,
                "prev_timestamp": null,
                "remote": null,
                "binary_remote": null,
                "build_id": null,
                "binary": null,
                "invalid_build": false,
                "info_invalid": null,
                "name": null,
                "user": null,
                "channel": null,
                "url": null,
                "license": null,
                "author": null,
                "description": null,
                "homepage": null,
                "build_policy": null,
                "upload_policy": null,
                "revision_mode": "hash",
                "provides": null,
                "deprecated": null,
                "win_bash": null,
                "win_bash_run": null,
                "default_options": null,
                "options_description": null,
                "version": null,
                "topics": null,
                "package_type": "unknown",
                "settings": {
                    "os": "Linux",
                    "arch": "x86_64",
                    "compiler": "gcc",
                    "compiler.libcxx": "libstdc++11",
                    "compiler.version": "10",
                    "build_type": "Release"
                },
                "options": {},
                "options_definitions": {},
                "generators": [],
                "python_requires": {
                    "package_name/0.1.0@company/latest#c525c55123b4d0912b0fbc5e2f1f9b10": {
                        "remote": null,
                        "recipe": "Cache"
                    }
                },
                "system_requires": {},
                "recipe_folder": null,
                "source_folder": null,
                "build_folder": null,
                "generators_folder": null,
                "package_folder": null,
                "cpp_info": {
                    "root": {
                        "includedirs": [
                            "include"
                        ],
                        "srcdirs": null,
                        "libdirs": [
                            "lib"
                        ],
                        "resdirs": null,
                        "bindirs": [
                            "bin"
                        ],
                        "builddirs": null,
                        "frameworkdirs": null,
                        "system_libs": null,
                        "frameworks": null,
                        "libs": null,
                        "defines": null,
                        "cflags": null,
                        "cxxflags": null,
                        "sharedlinkflags": null,
                        "exelinkflags": null,
                        "objects": null,
                        "sysroot": null,
                        "requires": null,
                        "properties": null
                    }
                },
                "conf_info": {},
                "label": "cli",
                "dependencies": {},
                "context": "host",
                "test": false
            }
        },
        "root": {
            "0": "None"
        },
        "overrides": {},
        "resolved_ranges": {}
    }
}

```

**Comment by memsharded** [comment]
> First issue is that because the recommended solution is to pipe to file we can no longer use standard print commands inside the conanfiles.

Conan provides and documents the ``self.output.info|success|warning()`` helpers for output, I think Conan didn't document using ``print()`` in recipes, but please let me know if you found it to fix it. If using ``print``, the recommendation would be to redirect to ``stderr`` like ``print(..., file=sys.stderr)``, to not pollute the ``stdout``

Regarding your flow, you are missing the intermediate step, please check the docs in https://docs.conan.io/2/tutorial/other_features.html#packages-lists and other pages. The result of ``conan create`` is not a package list, it is a ``graph``. You need to ``conan list --graph=xxxx`` to convert it to a package list that you can upload.

**Comment by geir-t** [comment]
Thank you, that was the missing step yes. Regarding the print, it is not a big issue, but yet another thing you need to be aware of. I think it would have simplified things to have an output file argument instead of having to rely on piping the output to a file.  
`--format json --output-file build.json`

**Comment by memsharded** [comment]
> I think it would have simplified things to have an output file argument instead of having to rely on piping the output to a file.
--format json --output-file build.json

I liked this idea, but the majority of users feedback made us use the standard piping approach, with stderr/stdout redirection.
