### ISSUE TITLE
[bug] conan create --format=json throws when creating a python_requires package

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#14577]
### Environment details

* Operating System+version: Ubuntu Linux 22.04
* Conan version: 2.0.9 / 2.0.10-dev
* Python version: 3.10.12

### Steps to reproduce

1. Create basic conanfile.py which shall be used as a python_requires. E. g. with the contents of the upper one from [this example page](https://docs.conan.io/2/reference/extensions/python_requires.html?highlight=python_requires):
```
from conan import ConanFile

myvar = 123

def myfunct():
    return 234

class Pkg(ConanFile):
    name = "pyreq"
    version = "0.1"
    package_type = "python-require"
```
2. Do a 
```
$ conan create . --format=json
```
This results in a:
```
ERROR: 'NoneType' object has no attribute 'serialize'
```
While a pure `conan create .` works as expected.

When searching the issue database, I stumbled across [this merge request](https://github.com/conan-io/conan/pull/14529) which looked like it would fix my exact problem. So I tried the source-version (commit 0e168973a58d284814c517d03baf841767c84d9f) but I still get the same error.

Background is: I want to use the generated json file with a `conan list --graph=conancreategraph.json --graph-binaries=build --format=json ...` and then a `conan upload --list=conanlist.json ...` command to upload the generated package to our conan remote. This should work with python_requires packages, as well, shoudn't it?

**Comment by AbrilRBS** [comment]
Thanks a lot for your report. We are currently not  initializing a dependency graph for python requires, I'll check how to best handle this! :)

**Comment by AbrilRBS** [comment]
Hi @fourbft thanks a lot for your report. I've sent https://github.com/conan-io/conan/pull/14594 for the next 2.0.10 release to fix your issue

Note that python requires are not expanded in the graph like other nodes, as they are a class attribute for recipes. Instead, in the resulting graph when creating a python-requires you'll find a virtual node whose `python_requires` attribute contains your python_requires (And every other if your new python-requires transitively requires other python-requires)

**Comment by fourbft** [comment]
Hi @RubenRBS,

thanks a lot for the quick fix! Just tried your PR version. Yes, the error is gone, but that still does not fix my use case completely.

What I am trying to do is the following: 
In our CI jobs, when building packages from source, we are doing these steps:

```
conan create . -pr:h $PROFILE -pr:b $PROFILE --format=json > conancreategraph.json
conan list --graph=conancreategraph.json --graph-binaries=build --format=json > conanlist.json
conan upload -c -r $REMOTE --list=conanlist.json
```

I took these steps from the conan docs somewhere. (Sorry, could not find it again in a quick search, but I guess you will recognize the pattern.)

With your changes, the first step works now, but the second step, the `conan list ...` results in an empty list in the conanlist.json file, when the package is a "python_requires". This is a problem, as our CI cannot know, what type of package the sources at hand represent. So we need a mechanism that works for all types of packages.

Do you think you can make that work? Or do you have another suggestion for what would be the best way to find out the reference of the package that was created in the `conan create` step, so it can be uploaded to the remote?

Actually I used to have a different aproach in the CI before I saw your recommendation with `conan list`. In the old procedure I used `conan inspect . -f json` and some python code to load the json and find out the package reference for the conan recipe in the local source tree. I could go back to that - it did work for python_requires packages, too. But I actually liked the `conan list` approach better, as it is "pure conan" (thus less brittle with conan changes) and shorter.

**Comment by fourbft** [comment]
Ah, just found it: [this](https://github.com/conan-io/conan/issues/14040#issuecomment-1579543693) was the place, I took the `conan upload` trick from. Not officially in the docs, yet. But an answer to a question by our conan-mastermind @memsharded. 😀

**Comment by memsharded** [comment]
Mastermind summoned 😂 

It is possible that the ``--graph-binaries`` argument is not enough for python-requires that do not contain binaries, adding:
```bash
conan list --graph=conancreategraph.json --graph-recipes=* --graph-binaries=build --format=json > conanlist.json
```
might make it work, please try and let us know.

**Comment by fourbft** [comment]
Hi @memsharded, glad I found the magic spell to conjure up the mastermind! 😂

But, unfortunately no luck. The list in conanlist.json is still empty even with `--graph-recipes=*`. When I remove the `package_type = "python-require"` from the conanfile.py it works, but not when the type is "python-require".

**Comment by memsharded** [comment]
You are right, there was a gap there. Trying to get a fix in https://github.com/conan-io/conan/pull/14602, lets see if it can go to 2.0.10 or need to wait until 2.0.11
