### ISSUE TITLE
[question] For a missing package what is the best way to find out what settings/options are different from prebuilt packages 

### ISSUE THREAD

**Issue by ibrawada** [conan-io/conan#14580]
### What is your question?

Hello,

for a library im building that depends on Qt i get an error message that pre-built package is not available. By looking at the huge list of options (see below) it is not possible to find out what is exactly is different for the required package from the ones that are already prebuilt (especially those with the same settings)

What is the best way to find out what is exactly different? 
Is there a way to do a diff between _qt/version:required_ and _qt/version:prebuilt_package_
Or maybe even have it displayed in the html file generate by **conan search --table**? by highlighting the differences in red?

Conan: 1.60.2
Docker: conanio/gcc9

- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++11, compiler.version=9, os=Linux
- Options: commercial=False, config=None, cross_compile=None, device=None, gui=True, multiconfiguration=False, opengl=desktop, openssl=True, qt3d=False, qtandroidextras=False, qtcharts=False, qtconnectivity=False, qtdatavis3d=False, qtdeclarative=False, qtdoc=False, qtgamepad=False, qtgraphicaleffects=False, qtimageformats=False, qtlocation=False, qtlottie=False, qtmultimedia=False, qtnetworkauth=False, qtpurchasing=False, qtquick3d=False, qtquickcontrols=False, qtquickcontrols2=False, qtquicktimeline=False, qtremoteobjects=False, qtscript=False, qtscxml=False, qtsensors=False, qtserialbus=False, qtserialport=False, qtspeech=False, qtsvg=False, qttools=False, qttranslations=False, qtvirtualkeyboard=False, qtwayland=False, qtwebchannel=False, qtwebengine=False, qtwebglplugin=False, qtwebsockets=False, qtwebview=False, qtx11extras=False, qtxmlpatterns=False, shared=False, sysroot=None, widgets=True, with_dbus=False, with_doubleconversion=True, with_fontconfig=True, with_freetype=True, with_glib=False, with_gssapi=False, with_harfbuzz=False, with_icu=True, with_libjpeg=libjpeg, with_libpng=True, with_md4c=True, with_mysql=True, with_odbc=True, with_pcre2=True, with_pq=True, with_sqlite3=True, with_vulkan=False, with_x11=True, with_zstd=True, brotli:enable_debug=False, brotli:enable_log=False, brotli:enable_portable=False, brotli:enable_rbit=True, brotli:endianness=None, brotli:fPIC=True, brotli:shared=False, brotli:target_bits=None, bzip2:build_executable=True, bzip2:fPIC=True, bzip2:shared=False, double-conversion:fPIC=True, double-conversion:shared=False, expat:char_type=char, expat:fPIC=True, expat:large_size=False, expat:shared=False, fontconfig:fPIC=True, fontconfig:shared=False, freetype:fPIC=True, freetype:shared=False, freetype:subpixel=False, freetype:with_brotli=True, freetype:with_bzip2=True, freetype:with_png=True, freetype:with_zlib=True, icu:dat_package_file=None, icu:data_packaging=archive, icu:fPIC=True, icu:shared=False, icu:with_dyload=True, icu:with_extras=False, icu:with_icuio=True, libffi:fPIC=True, libffi:shared=False, libiconv:fPIC=True, libiconv:shared=False, libjpeg:fPIC=True, libjpeg:shared=False, libmysqlclient:fPIC=True, libmysqlclient:shared=False, libpng:api_prefix=, libpng:fPIC=True, libpng:shared=False, libpng:sse=True, libpq:disable_rpath=False, libpq:fPIC=True, libpq:shared=False, libpq:with_openssl=False, libtool:fPIC=True, libtool:shared=False, libuuid:fPIC=True, libuuid:shared=False, libxml2:c14n=True, libxml2:catalog=True, libxml2:fPIC=True, libxml2:ftp=True, libxml2:html=True, libxml2:http=True, libxml2:iconv=True, libxml2:icu=False, libxml2:include_utils=True, libxml2:iso8859x=True, libxml2:legacy=True, libxml2:lzma=False, libxml2:mem-debug=False, libxml2:output=True, libxml2:pattern=True, libxml2:push=True, libxml2:python=False, libxml2:reader=True, libxml2:regexps=True, libxml2:run-debug=False, libxml2:sax1=True, libxml2:schemas=True, libxml2:schematron=True, libxml2:shared=False, libxml2:threads=True, libxml2:tree=True, libxml2:valid=True, libxml2:writer=True, libxml2:xinclude=True, libxml2:xpath=True, libxml2:xptr=True, libxml2:zlib=True, lz4:fPIC=True, lz4:shared=False, md4c:encoding=utf-8, md4c:fPIC=True, md4c:shared=False, odbc:fPIC=True, odbc:shared=False, odbc:with_libiconv=True, openssl:386=False, openssl:enable_weak_ssl_ciphers=False, openssl:fPIC=True, openssl:no_aria=False, openssl:no_asm=False, openssl:no_async=False, openssl:no_bf=False, openssl:no_blake2=False, openssl:no_camellia=False, openssl:no_cast=False, openssl:no_chacha=False, openssl:no_cms=False, openssl:no_comp=False, openssl:no_ct=False, openssl:no_deprecated=False, openssl:no_des=False, openssl:no_dgram=False, openssl:no_dh=False, openssl:no_dsa=False, openssl:no_dso=False, openssl:no_ec=False, openssl:no_ecdh=False, openssl:no_ecdsa=False, openssl:no_engine=False, openssl:no_filenames=False, openssl:no_fips=False, openssl:no_gost=False, openssl:no_idea=False, openssl:no_legacy=False, openssl:no_md2=True, openssl:no_md4=False, openssl:no_mdc2=False, openssl:no_module=False, openssl:no_ocsp=False, openssl:no_pinshared=False, openssl:no_rc2=False, openssl:no_rc4=False, openssl:no_rc5=False, openssl:no_rfc3779=False, openssl:no_rmd160=False, openssl:no_seed=False, openssl:no_sm2=False, openssl:no_sm3=False, openssl:no_sm4=False, openssl:no_sock=False, openssl:no_srp=False, openssl:no_srtp=False, openssl:no_sse2=False, openssl:no_ssl=False, openssl:no_ssl3=False, openssl:no_stdio=False, openssl:no_threads=False, openssl:no_tls1=False, openssl:no_ts=False, openssl:no_whirlpool=False, openssl:no_zlib=False, openssl:openssldir=None, openssl:shared=False, pcre2:build_pcre2_16=True, pcre2:build_pcre2_32=True, pcre2:build_pcre2_8=True, pcre2:build_pcre2grep=True, pcre2:fPIC=True, pcre2:grep_support_callout_fork=True, pcre2:shared=False, pcre2:support_jit=False, pcre2:with_bzip2=True, pcre2:with_zlib=True, sqlite3:build_executable=True, sqlite3:disable_gethostuuid=False, sqlite3:enable_column_metadata=True, sqlite3:enable_dbpage_vtab=False, sqlite3:enable_dbstat_vtab=False, sqlite3:enable_default_secure_delete=False, sqlite3:enable_default_vfs=True, sqlite3:enable_explain_comments=False, sqlite3:enable_fts3=False, sqlite3:enable_fts3_parenthesis=False, sqlite3:enable_fts4=False, sqlite3:enable_fts5=False, sqlite3:enable_json1=False, sqlite3:enable_math_functions=True, sqlite3:enable_preupdate_hook=False, sqlite3:enable_rtree=True, sqlite3:enable_soundex=False, sqlite3:enable_unlock_notify=True, sqlite3:fPIC=True, sqlite3:max_blob_size=None, sqlite3:max_column=None, sqlite3:max_variable_number=None, sqlite3:omit_deprecated=False, sqlite3:omit_load_extension=False, sqlite3:shared=False, sqlite3:threadsafe=1, sqlite3:use_alloca=False, wayland:enable_dtd_validation=True, wayland:enable_libraries=True, wayland:fPIC=True, wayland:shared=False, xkbcommon:fPIC=True, xkbcommon:shared=False, xkbcommon:with_wayland=True, xkbcommon:with_x11=True, xkbcommon:xkbregistry=True, zlib:fPIC=True, zlib:shared=False, zstd:fPIC=True, zstd:shared=False, zstd:threading=True
- Dependencies: zlib/1.2.13, openssl/3.1.1, pcre2/10.42, double-conversion/3.3.0, freetype/2.13.0, fontconfig/2.14.2, icu/73.2, libjpeg/9e, libpng/1.6.40, sqlite3/3.42.0, libmysqlclient/8.0.31, libpq/15.3, odbc/2.3.11, xkbcommon/1.5.0, xorg/system, opengl/system, zstd/1.5.5, md4c/0.4.8
- Requirements: double-conversion/3.Y.Z, fontconfig/2.Y.Z, freetype/2.Y.Z, icu/73.Y.Z, libjpeg/9e, libmysqlclient/8.Y.Z, libpng/1.Y.Z, libpq/15.Y.Z, md4c/0.4.8, odbc/2.Y.Z, opengl/system, openssl/3.Y.Z, pcre2/10.Y.Z, sqlite3/3.Y.Z, xkbcommon/1.Y.Z, xorg/system, zlib/1.Y.Z, zstd/1.Y.Z
- Package ID: ab96a265ac568c1a253f796f9f74e7b8d5fe7eed

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ibrawada 

Yes, there is no way to do a "diff", because the "distance" between 2 binaries is a difficult concept. So the best is indeed to use ``conan search --table`` and then use the filters that are provided in the html table, start selecting the different settings, etc. until the existing binaries exhaust.

In general, ConanCenter binaries only exist for the default configurations and options. If any option is changed, then it is almost certain that binaries will not exist. For using packages from ConanCenter in prod, we have written a new section in the docs: https://docs.conan.io/2/devops/using_conancenter.html

**Comment by ibrawada** [comment]
Hello @memsharded,

thanks for the feedback. I forgot to mention that we are using a self hosted instance of Artifactory and do not use conancenter at all. 
I figured out what was missing. It was a dependency of a dependency: Qt -> xkbcommon -> **wayland-protocols**. I did it by building and uploading the required package to our Artifactory and then doing conan search --table. 

This brings couple of observations and questions
* The missing dependency (wayland-protocols) didn't show up in the requirements list of the error message. Maybe because its a tool_requirement. But it is also a requirement (by looking at the recipe of xkbcommon) and it shows up in the list in the html file
* conan search --table cannot display packages from a remote and local cache together in one file, that's why i had to upload the package to Artifactory first.
* the generated html file only shows the options from Qt recipe but not the options of its dependencies. If there is a mismatch there then it would not be possible to locate the difference

I understand that having Qt as a dependency might not be a good idea, but is there a way to make the process of finding out the diff less tedious?

**Comment by memsharded** [comment]
> thanks for the feedback. I forgot to mention that we are using a self hosted instance of Artifactory and do not use conancenter at all.

Yes, the idea of using Conan commands is that they should work both with ConanCenter and your own private servers, in the same way, and do not rely on any website for ConanCenter

> I figured out what was missing. It was a dependency of a dependency: Qt -> xkbcommon -> wayland-protocols. I did it by building and uploading the required package to our Artifactory and then doing conan search --table.

Great, happy that you found the issue!

> The missing dependency (wayland-protocols) didn't show up in the requirements list of the error message. Maybe because its a tool_requirement. But it is also a requirement (by looking at the recipe of xkbcommon) and it shows up in the list in the html file

Conan 2.0 will correctly display the package in the requirements list, even if it is also a ``tool-requires``

> conan search --table cannot display packages from a remote and local cache together in one file, that's why i had to upload the package to Artifactory first.

Conan 2.0 ``conan list --format=html`` can do multiple cache + remotes in one single output and file

> I understand that having Qt as a dependency might not be a good idea, but is there a way to make the process of finding out the diff less tedious?

Analyzing when a binary is missing can be difficult, because there are so many factors involved. Dependencies effect in binaries is a complex thing by itself, Conan tries to model it the best it can, but when something is missing it might not be easy to understand why. Conan 2.0 introduced a few improvements trying to help with this, for example the ``package_id`` is computed as the hash of the ``conaninfo.txt`` file, without any extra internal logic. This makes a bit easier to understand the effects of dependencies in a given binary, just by reading the ``conaninfo.txt`` file.

**Comment by memsharded** [comment]
This would be much better solved in Conan 2 with the new ``conan graph explain`` that will return a detailed explanation of the closest binary with the "diff" of why it is not valid for the current settings.

Closing this question as solved, don't hesitate to create new tickets for any further question, thanks!
