### ISSUE TITLE
[Conan remote cleanup] Delete based on usage and/or upload time in artifactory

### ISSUE THREAD

**Issue by nagag08** [conan-io/conan#14586]
### What is your question?

Do we have a procedure for how to delete the files based on specific criteria, like not used in x days or uploaded x days before? This is for Conan remote as artifactory. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nagag08 

Conan does not have any server-specific metadata like the "not used in X days", so this is impossible from Conan side, and require something server-specific.

Conan has some tools for removing packages based on revisions:
- ``conan remove *#~latest`` might remove all recipe revision but the latest one. But not really filter by date.
- Conan is implementing for future release the ``conan remove --lru=Xd`` (or weeks, etc) to remove not used packages from the Conan cache. But it will only work in the local cache, not in remotes.

**Comment by memsharded** [comment]
Closing the question as responded. The client side is clear, and the server side should be server-specific. I think the feature you might be interested in Artifactory is "retention policies".
