### ISSUE TITLE
Add gcc 7.0 and 7.1 to default settings.yml

### ISSUE THREAD

**Issue by shearer12345** [conan-io/conan#1459]
Would be great to add support for gcc 7.0 and 7.1

Not a blocking issue, as can add it to settings.yml to keep working - as discussed in #1157 

I see the changes needed (for apple-clang) in #1178 - so happy to create a pull request for this.

Thanks for working on conan - loving it :-)

**Comment by memsharded** [comment]
Hi John!

Thanks very much, very glad that you are loving conan.

gcc 7.1 is already there in settings.yml, it should be there when installing from scratch. Maybe there is an issue with the automatic migration that updates settings.yml, I have to check it.

Are you sure you want 7.0 there? It is supposed to be beta, and these settings.yml are a default, intended to share packages with the world, not sure if there should be packages generated with 7.0, same reason there is no 5.0 or 6.0 in the default settings.yml. What do you think? Thanks for your feedback!

**Comment by shearer12345** [comment]
Thanks @memsharded - I just discovered it was already there. Sorry for the needless issue raise.

It's the 7.0 that's causing my issue - I've managed to install 7.0 instead of 7.1. I'll resolve that. I agree that 7.0 shouldn't be in the list.

Cheers

**Comment by memsharded** [comment]
No worries :) cheers!
