### ISSUE TITLE
Consider adding warning/error is `storage.path` is not an absolute path

### ISSUE THREAD

**Issue by shearer12345** [conan-io/conan#1460]
The documentation for [custom_cache](http://conanio.readthedocs.io/en/latest/howtos/custom_cache.html) says
> Note: Use an absolute path and without quotes in Windows.

I think it would be useful for conan to warn/error if a relatively path is used - perhaps by detecting that the path doesn't start with either `/` or `~` (I'm not aware of other bash-expansions like `~`, but there may be some?).

I think it would be valuable to modifying the comment in `conan.conf` from
> \# This is the default path, but you can write your own

to something like 
> \# This is the default path, but you can write your own - must be an absolute path, or a ~-expanded path

#### Example, for context.

If I run the following
```bash
export CONAN_USER_HOME=.conan
conan install Boost/1.62.0@lasote/stable --build missing
```
I get the following error:
```
ERROR: [Errno 2] No such file or directory: '.conan/.conan/data/bzip2/1.0.6/lasote/stable/export'
```
As the relative path isn't correct for conan at that point (I assume)

#### Ambiguous meaning in the docs

Also, I'm unclear, on the parsing of the meaning of that sentence in the docs - my belief is that "Use an absolute path" applies to both Windows and non-Windows, but that sentence could be interpreted either way - do you want a separate issue, or PR for that?

**Comment by memsharded** [comment]
Yes, that would be useful, indeed. Do you want to try then to provide a fix for it? Don't worry, there is already CI setup for Win, Linux and Mac, and the test suite is quite complete :) 
No worries if not, I have added to 0.26, so if you are not able, it will be fixed by then.

Then the docs can be fixed, yes, in a separate PR.

Thanks very much!

**Comment by shearer12345** [comment]
Very happy to. I'll jump on it next week
