### ISSUE TITLE
[feature] add possibility to check if MFC and ATL modules of MSVC are installed

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#14603]
### What is your suggestion?

relates to https://github.com/conan-io/conan-center-index/issues/19415

Some libs may require MFC or ATL support on MSVC. It would be good to have a possibility to check if these modules are installed in validate() method

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @AndreyMlashkin 

Thanks for your suggestion.

Note the ``validate()`` method is intended to validate a given configuration as defined in ``settings``, ``options``, etc. It is not auto-detecting things in the environment. This is important and necessary, for example to know what configurations need to be built in ConanCenter, we run ``conan graph info`` and the configurations that ``validate()`` raise, we don't try to build them. But the same (Linux) computer analyzes all the possible configurations, for Windows, OSX, etc. So it is not possible to rely on checking what is installed in the system at ``validate()`` time.

So this doesn't seem possible, and the only way would be something like:
- Use ``options`` to imperatively define when a package should be using MFC or ATL or not
- The build system raise an error if the option is not fulfilled

**Comment by memsharded** [comment]
Closing this as not planned at the moment. It seems this haven't had other users request, and it seems a bit of a corner case and not very clear how would it be used (as commented above, it cannot be checked in ``validate()`` time, this shouldn't be tied to the machine is executing, but only to the profile input data).

Thanks for the suggestion!
