### ISSUE TITLE
[bug] `PkgConfig.fill_cpp_info` is ignoring `/usr` prefix

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#14615]
### Environment details

OS: Ubuntu 20.04
Python: 3.10.9
Conan: 2.0.9

### Steps to reproduce

I found a bug when using the method `fill_cpp_info` of the `PkgConfig` helper. The CppInfo deduction fails when the used prefix set to simply `/usr`. 

Details in order to reproduce the issue can be found here: https://github.com/nicosmd/conan2_find_cpp_info_bug

**Comment by nicosmd** [comment]
This seems not to be a conan issue as stripping /usr/lib is a feature of pkg-config itself. For sysroots, the Environment Variable `PKG_CONFIG_ALLOW_SYSTEM_LIBS` needs to be set. Then everything is working as expected. The Env Variable can be set in the pkg-config wrapper I had to create anyway. I'm not sure if conan could provide some more logic in order to prevent this pitfall or maybe document this behavior but at least for me it is solved.

**Comment by franramirez688** [comment]
Hi @nicosmd 

So sorry about replying too late. Anyway, it's great that you've already solved that problem, so thanks a lot for the report.

**Comment by nicosmd** [comment]
@franramirez688 no worries! There are a lot issues reported in the recent past, I can imagine it is very hard to keep up with them. I'm glad to help with reporting solutions when I find one by my own. Thank you very much!
