### ISSUE TITLE
[feature] consider adding ability to specify override in conanfile.txt

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#14617]
### What is your suggestion?

Ability to specify `,override=True` in a dependency in `conanfile.txt`, to allow an override to resolve a conflict, without encoding a direct dependency

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Conan 2 added ``[replace_requires]`` to profiles, that allows to do dependency overriding, also to temporarily solve conflicts, see https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires. 

At the moment we are not considering to add this syntax to ``conanfile.txt``, but the recommendation is to use ``conanfile.py`` for advanced dependency definition.
