### ISSUE TITLE
Incorrect compiler version error when using CMake build helper (OSX)

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#1462]
On my machine (OSX 10.11), I have two versions of Clang installed:
- AppleClang 7.3 (the one provided by XCode) ( /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin)
- Clang 3.8.1 (built from source) (/usr/local/bin)

c and c++ commands are symlinked to the former, while clang and clang++ are symlinked to the latter. 

When running cmake, typically, it will always find the Apple one, unless I set the CMAKE_CXX_COMPILER and CMAKE_C_COMPILER when configuring cmake the first time.  Alternatively, if the CC and CXX environment variables are defined when invoking CMake, it will use those as default.

When installing conan, it automatically set the compiler version to 3.8, so I figured it found the right one. 
[settings_defaults]

```
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=3.8
os=Macos
```
But when using the CMake build helper in a build recipe (or, in this case, a test_package), I get an error:
```
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
CMake Error at build/da39a3ee5e6b4b0d3255bfef95601890afd80709/conanbuildinfo.cmake:332 (message):
  Incorrect 'clang' version 'compiler.version=3.8' is not the one detected by
  CMake: 'Clang=7.3'
Call Stack (most recent call first):
  build/da39a3ee5e6b4b0d3255bfef95601890afd80709/conanbuildinfo.cmake:375 (conan_error_compiler_version)
  build/da39a3ee5e6b4b0d3255bfef95601890afd80709/conanbuildinfo.cmake:426 (check_compiler_version)
  build/da39a3ee5e6b4b0d3255bfef95601890afd80709/conanbuildinfo.cmake:178 (conan_check_compiler)
  CMakeLists.txt:5 (conan_basic_setup)
```

I have added this to my conan.conf file, but still  get the same errors:
```
[env]
CC=/usr/local/bin/clang
CXX=/usr/local/bin/clang++
```

**Comment by memsharded** [comment]
Yes, that is very weird, it seems that CMake is not honoring the CC/CXX environment variables... 
Wait, did you add the env variables to the ``conan.conf`` or to a profile? I think those variables should be configured in profiles, not in conan.conf. Could you please check? Thanks!

**Comment by jcar87** [comment]
Perfect! that did the trick, copying that into a profile instead of conan.conf
But shouldn't it have worked regardless? My understanding of profiles was that they simply override the defaults in conan.conf? or are there some restrictions?

also, is there a way to make a profile the default then? (so that I dont forget the -p xxx flag)

but kudos on adding that compiler version check!! would've been difficult to trace if conan had silently ignored it. In most cases AppleClang will still build everything fine, but in those cases where I need OpenMP, not so much !

**Comment by lasote** [comment]
Hi, Just FYI in the next release 0.25 will be a default profile in `.conan/profiles/default` containing the default settings (removed from conan.conf). This profile will allow [env] variables and all the profiles possibilities. I hope it will be less confusing.

**Comment by memsharded** [comment]
Excellent, thanks :)

Yes, next release will provide the default profile, and using [env] there will be much clearer. I think this issue can be closed then, but please ask or open a new issue if necessary. Thanks!

**Comment by jcar87** [comment]
Great!! looking forward to 0.25 💃
