### ISSUE TITLE
[question] Minus sign is discouraged in package name

### ISSUE THREAD

**Issue by mikhailmaximov** [conan-io/conan#14626]
### What is your question?

I think that there is a discrepancy between actual code and documentation.

> conan --version
Conan version 2.0.10

At least two places in documentation tell that minus sign "-" is allowed to be a part of a package name. Yet Conan produces the following warning:
```
======== Exporting recipe to the cache ========
WARN: Name containing special chars is discouraged 'mylibrary-pkg1'
```

https://docs.conan.io/2.0/tutorial/creating_packages/create_your_first_package.html
```
name: a string, with a minimum of 2 and a maximum of 100 lowercase characters that defines the package name. It should start with alphanumeric or underscore and can contain alphanumeric, underscore, +, ., - characters.
```

https://docs.conan.io/2.0/reference/conanfile/attributes.html#name
```
The name of the package. A valid name is all lowercase and has:
A minimum of 2 and a maximum of 101 characters (though shorter names are recommended).
Matches the following regex ^[a-z0-9_][a-z0-9_+.-]{1,100}$: so starts with alphanumeric or _,
then from 1 to 100 characters between alphanumeric, _, +, . or -.
```

The behavior was introduced by the commit 8f8a53e1e62a972933cec2ccd9c947f4fb4ae7b9, file conans/model/recipe_ref.py

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @mikhailmaximov thanks a lot for your report.

As @memsharded mentioned in https://github.com/conan-io/docs/issues/3329#issuecomment-1682564305:

```
This is a valid warning, and also the docs are fine:

The name hello-world can be used.
It is not an error, and in general Conan will manage to create the packages.

The name hello-world is discouraged, and the warning will tell about it.
The reason is that so many integrations, build system, generators
can struggle with filenames, variables, etc
that contain these special characters that will appear.
We try to test and fix the most popular built-in ones,
but we have seen this failing too many times to actively discourage it.
```

What we can do is to better document this in the docs to make the behaviour a bit more clear, which is tracked in https://github.com/conan-io/docs/issues/3329 too

**Comment by mikhailmaximov** [comment]
Thank you.
