### ISSUE TITLE
[feature] allow regex pattern for `tools.info.package_id:confs`

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#14620]
### What is your suggestion?

It would be nice if users can specify patterns for conf `tools.info.package_id:confs` instead of listing each single conf name.

e.g.
```
[conf]
tools.info.package_id:confs = [ "tools.cmake.*" ]
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/14621 for 2.0.11
