### ISSUE TITLE
[bug] Options missed in build order graph

### ISSUE THREAD

**Issue by xandox** [conan-io/conan#14637]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: gcc 11
* Conan version: 2.0.10
* Python version: 3.9

### Steps to reproduce

1. do `conan graph build-order --requires opencv/4.5.5 -f json > build_order_opencv_def.json`
2. do `conan graph build-order --requires opencv/4.5.5 -o 'opencv/*:parallel=tbb' -f json > build_order_opencv_with_tbb.json`
3. `diff build_order_opencv_def.json build_order_opencv_with_tbb.json`

In diff you can see that onetbb was added to build order and set as dependency for opencv and opencv package_id changed but there was not any mention of option overriding

### Logs

[install-opencv-with-tbb.json.txt](https://github.com/conan-io/conan/files/12497082/install-opencv-with-tbb.json.txt)
[install-opencv-def.json.txt](https://github.com/conan-io/conan/files/12497084/install-opencv-def.json.txt)
[install-opencv-diff.txt](https://github.com/conan-io/conan/files/12497085/install-opencv-diff.txt)

**Comment by memsharded** [comment]
Hi @xandox 

Thanks for your feedback.
The ``conan graph build-order`` do not store in the result the information that comes from profiles (or command line arguments). The information computed there contains the options that are defined in downstream consumers of the recipe in the graph-build order, because that information would be lost otherwise when building that recipe in isolation. But the full inputs, the same profiles (the command line options belong to the "effective" profile) that are used in the ``conan graph build-order`` command must be the ones applied later in the build of every item in the result of the "build-order".

Please let me know if this clarifies the behavior of the ``conan graph build-order`` command.

**Comment by xandox** [comment]
Hi @memsharded 

Ok, may be for command line interface it has some mean.
But I do something like this with conan_api for generating then CI files.

```
full_install_graph = InstallGraph()
install_graph_def = generate_install_graph("opencv/4.5.5", options=None)
install_graph_with_options = generate_install_graph("opencv/4.5.5", options=['opencv/*:parallel=tbb'])
full_install_graph.merge(install_graph_def)
full_install_graph.merge(install_graph_with_options)
print(json.dumps(full_install_graph.install_build_order(), ident=4)
```
where `generate_install_graph` something like 
```
def generate_install_graph(ref, host_options):
    profile_host, profile_build = get_profiles_with_host_options(host_options)
    remotes = conan_api.remotes.list()
    build = ....
    deps_graph = conan_api.graph.load_graph_requires(
            [ref],
            [],
            profile_host,
            profile_build,
            None,
            remotes,
            build,
            True,
        )
        conan_api.graph.analyze_binaries(
            deps_graph,
            build,
            remotes=remotes,
            update=True,
            lockfile=None,
    )
    install_graph = InstallGraph(deps_graph)
    return install_graph
```
and final node for opencv looks like:
```
        {
            "ref": "opencv/4.5.5#1a0a9f5ddfd0ec0e9ec3a11ac7f57794",
            "depends": [
                "zlib/1.2.13#12b491771aa8105bca32bea4d34a392a",
                "eigen/3.4.0#3fdee248566f7185558e72b0131348f8",
                "protobuf/3.21.12#2e8ae9bc15d46aca1c0452dd4c63df29",
                "ade/0.1.2a#e5aee5f089255eb95d79c158911ba6fc",
                "gtk/system#3671596ecc796ec65f881b2cad66ce26",
                "libjpeg/9e#e1ac91099288eafc50d24b126f35e514",
                "jasper/4.0.0#b58b57b4d10ad6d08f5d6ca1f59ea428",
                "libpng/1.6.40#13ab4a7f7fdd2f5e5094c84553480d65",
                "openexr/3.1.9#433472fef732dd3c471123d1cd4971ae",
                "libtiff/4.5.1#a1ed552a343875a5c68fb02214685fdb",
                "libwebp/1.3.1#23056f4b4aeb3fe1717ad0113733d77a",
                "quirc/1.2#2906a4d4ceedc8f6188f71d003f8a840",
                "ffmpeg/4.4.3#b2ae4f95e7d0914a07d094af15565f26",
                "cmake/3.26.4#0b40747e190e755932767f2ec4768ff5",
                "ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21",
                "onetbb/2021.9.0#4bad741533c6cd1d0b149de766875a77"
            ],
            "packages": [
                [
                    {
                        "package_id": "3fcceaa9faa24f80407a4b61dd19214d149025da",
                        "prev": null,
                        "context": "host",
                        "binary": "Build",
                        "options": [],
                        "filenames": [],
                        "depends": [],
                        "overrides": {},
                        "build_args": "--require=opencv/4.5.5 --build=opencv/4.5.5"
                    },
                    {
                        "package_id": "57635c199d5bfa35bea387aeb3183ec68ac2bd76",
                        "prev": null,
                        "context": "host",
                        "binary": "Build",
                        "options": [],
                        "filenames": [],
                        "depends": [],
                        "overrides": {},
                        "build_args": "--require=opencv/4.5.5 --build=opencv/4.5.5"
                    }
                ]
            ]
        }
```
There is even `build_args` which the same for different package_id. For me it does not look like a good behaviour

**Comment by memsharded** [comment]
First, please let me recall that the python code that you are using has still not been publicly documented, and while it is planned to do, it cannot be considered as stable, and it can change and break your code in future Conan versions.

I think the gap that you are missing is the ``filenames`` field. When merging 2 or more different build-orders, they are assumed that have been stored in a file, with a given name. That filename is assigned in the ``filenames`` attribute, and will typically be a meaningful name like the profile one, like ``windows_vs22_shared``. This name is the thing that users can map to the specific configuration that will be used when building that specific package in the "build-order" json. The ``conan graph build-order`` is intended to be done in CI, and in CI, hardcoding options like ``-o 'opencv/*:parallel=tbb'`` in the command line (that means mostly hardcoded in the CI scripts) is not recommended. The ``opencv/*:parallel=tbb`` might be better in the profile file, and if the build-order information matches the profile name, then applying it in CI is straightforward.

**Comment by xandox** [comment]
Ok, I see your point. Can't say I am agree but...
