### ISSUE TITLE
[question] How to retrieve cpp_info outside of conan in 1.X

### ISSUE THREAD

**Issue by aander80** [conan-io/conan#14630]
### What is your question?

Hello!

I am developing a Python package that is to be used outside of conan 1.X (i.e. not called from within conan) where I want to consume conan packages using the information that is available in cpp_info (most likely properties). Is there a good way to do this?

I have two ideas so far:
* Add a conanfile.py to the Python package (this will be a consumer conanfile which is only intended to be called with conan install). We can take in the conan package to consume as a conan option, and then in generate() in this consuming conanfile use deps_cpp_info or self.dependencies (I don't quite recall which is correct in our use-case in conan 1) to consume the conan package. This solution would avoid us to put stuff in our conan cache (other than the package to consume).
* Add a generator conanfile.py in the Python package which will be copied into `CONAN_USER_HOME/.conan/generators`. We can then call `conan install <conan-package> -g <generator>` to generate a file from `<conan-package>` and use that file in our conan package. We can then remove the generator from the conan cache again, to keep it clean.

There are probably other approaches to solve this in conan 1, so feel free to come with alternative approaches.

Two aspects to take into account is that:
* If possible, we want to store everything in the Python package. We don't want to be dependent on syncing a conan package and a Python package, the Python package should be self-contained (hence why the conanfiles in the two approaches are to be stored in the conan package).
* If possible, we want to keep the conan cache clean. This is not the case in the second suggestion (even if we clean it afterwards, we still touch it).

What are your suggestions for my use-case?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aander80 

Thanks for your question.

> Add a conanfile.py to the Python package (this will be a consumer conanfile which is only intended to be called with conan install). We can take in the conan package to consume as a conan option, and then in generate() in this consuming conanfile use deps_cpp_info or self.dependencies (I don't quite recall which is correct in our use-case in conan 1) to consume the conan package. This solution would avoid us to put stuff in our conan cache (other than the package to consume).

Conan 1.X recommended approach s to use the ``generate()`` method, visiting the ``self.dependencies``, and you can read the ``cpp_info`` information there. 

I think this approach feels a bit simpler and self-contained than using the generator, and it will probably also move cleanly and work in Conan 2.0 with less issues.

> If possible, we want to store everything in the Python package. We don't want to be dependent on syncing a conan package and a Python package, the Python package should be self-contained (hence why the conanfiles in the two approaches are to be stored in the conan package).

In the ``generate()`` method you can do ``copy(...)`` and copy files from the dependencies to the current location (similar to the legacy ``imports``). Is this what you are trying to achieve?

**Comment by aander80** [comment]
Thanks for your quick reply!

> In the `generate()` method you can do `copy(...)` and copy files from the dependencies to the current location (similar to the legacy `imports`). Is this what you are trying to achieve?

Yes, this is similar to what we are trying to achieve (we probably only really care about where files are, not that they are located in a specific folder so as long as we have cpp_info I think we should be fine). I will try to use this method, then. Thanks, and have a great day and weekend! :)

**Comment by memsharded** [comment]
> Yes, this is similar to what we are trying to achieve (we probably only really care about where files are, not that they are located in a specific folder so as long as we have cpp_info I think we should be fine).

Sounds good, in the consumer side, the ``self.dependencies["mydep"].cpp_info.xxxdirs`` should already be an absolute paths, so it should be relatively easy to ``copy()`` from them to your current folders, no need to manually compose paths from ``self.dependencies["mydep"].package_folder + hardcoded paths``

> Thanks, and have a great day and weekend! :)

Thanks to you for your feedback, same!! 🙂
