### ISSUE TITLE
Customizing settings.yml from the clean state during CI

### ISSUE THREAD

**Issue by himikof** [conan-io/conan#1463]
I have a project that uses custom settings, so it requires customizing settings.yml to work with. In CI environment, conan is installed into fresh environment, no `$HOME/.conan` folder at all.

It is currently hard to ensure settings.yml is properly updated before running `conan install`.
- settings.yml is generated lazily, and it is very unclear when exactly is guaranteed to be written. For example, `conan remote add` seems to autodetect current settings, but does not write settings.yml.
- If anything is appended to settings.yml before defaults are written, the defaults are not written at all, and everything breaks due to invalid settings
- The only way I have found is to run some command like `conan info --build -- ./package`, have it fail due to missing custom settings definition (generating settings.yml in the process), append custom definitions to settings.yml and run desired commands. This is clearly suboptimal.
- There seems to be no analog to `conan config` for safely modifying setting definitions.

Am I missing something? Are profiles going to help this use case somehow, or some other behavior could be improved?

Example log:
```
$ conan remote add artifactory <snipped>

It seems to be the first time you've ran conan
Auto detecting your dev setup to initialize conan.conf
Found gcc 6.3
Default conan.conf settings
	os=Linux
	arch=x86_64
	compiler=gcc
	compiler.version=6.3
	compiler.libcxx=libstdc++
	build_type=Release
*** You can change them in ~/.conan/conan.conf ***
*** Or override with -s compiler='other' -s ...s***


WARN: Remotes registry file missing, creating default one in /root/.conan/registry.txt
$ conan user -p $ARTIFACTORY_API_KEY -r artifactory $ARTIFACTORY_USER
Change 'artifactory' user from None (anonymous) to <snipped>
$ echo 'python: {cpython: {version: ["2.7", "3.4", "3.5", "3.6"]}}' >> $HOME/.conan/settings.yml
$ conan install -u -r artifactory --build=outdated ./packaging -s python=cpython -s python.version=3.5
ERROR: 'settings.arch' doesn't exist
'settings' possible configurations are ['python']

```

**Comment by memsharded** [comment]
You are very right. The ``conan config`` command allows to edit the conan.conf, but not the settings.yml.
Actually a more general approach for defining settings should be consider, as "what would be the correct way to ensure all my team uses the same settings.yml", and how to "update that settings.yml" for the team

So tools to manage, share, define settings are needed. This release is packed, but lets do it in the next one. Thanks very much for your feedback.

**Comment by lasote** [comment]
In #1600 we implemented the edition of the default profile (and creation of a new one, optionally detecting) with the `conan profile` command. It will be released in 0.26.

**Comment by memsharded** [comment]
I am afraid that this feature still has not been addressed properly. The OP needs ``settings.yml`` to be generated to be able to modify it in CI before using it. I think these additions do not address this issue yet, so we need to review. Please @himikof confirm, but I am removing the fixed label and moving it to 0.27

**Comment by himikof** [comment]
Yes, profile editing solves a part of this issue, by allowing to robustly set some settings in CI (for example, setting `compiler.libcxx=libstdc++11`), and setting some options explicitly before running commands also helps. But the original problem that led to me reporting this issue ­(using **custom**, non-predefined settings or extending settings with new allowed values in a robust way for CI) still requires editing settings.yml, which is neither convenient nor robust. Maybe this could be solved by allowing profiles to explicitly declare new custom settings and/or their allowed values in addition to setting them.

**Comment by lasote** [comment]
Let's close this issue and continue on #1692
