### ISSUE TITLE
[feature] export-pkg should use set_name()

### ISSUE THREAD

**Issue by naggerx** [conan-io/conan#14638]
### What is your suggestion?

In the docs of 'set_name()' its stated:
>  This method is executed only when the recipe is exported to the cache `conan create` and `conan export`

Since `export-pkg` is also a command to "export to the cache" it would be desired that get_name() will be executed there too.

If  `conan export-pkg` is used today you get:
    ERROR: conanfile didn't specify name

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @naggerx 

Thanks for your question.
It already does, I have just checked with:
```python

class pkgRecipe(ConanFile):
    def set_name(self):
        self.name = "mypkg"
    
    version = "0.1"
```
and it works:
```
(conan2_36) λ conan export-pkg .

======== Exporting recipe to the cache ========
mypkg/0.1: Exporting package recipe: C:\Users\memsharded\conanws\kk\conanfile.py
mypkg/0.1: Copied 1 '.py' file: conanfile.py
mypkg/0.1: Copied 1 '.txt' file: CMakeLists.txt
mypkg/0.1: Copied 1 '.h' file: pkg.h
mypkg/0.1: Copied 1 '.cpp' file: pkg.cpp
```
Could you please double check it?

**Comment by naggerx** [comment]
Your are right it already works.  I had a bad copy'n'paste error.
Sorry for the noise.

**Comment by memsharded** [comment]
No prob, happy to help!
