### ISSUE TITLE
[feature] Add `--deployer` and `--generator` to `conan build` interface

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#14646]
### What is your suggestion?

Hi Team,

I'd like to propose adding the `--deployer` option to the `conan build` interface. The way I propose this should work is exactly the same as on the `conan install` interface - that is, does _not_ operate on the library being built, but rather only the dependencies specified in the conanfile.

This would add some convenience for local development workflows. To illustrate, I have a custom YouCompleteMe deployer that I invoke to enable YCM to find the conan libraries for symbol completion/code following etc (IDE integration). Currently, the workflow looks like:

```bash 
$ conan install . --deployer ycm
$ conan build .
```
If I then add a requirement to my conanfile, I have to repeat the same process somewhat redundantly since `conan build` also invokes `conan install`. It would be more convenient to issue only the single command:

```bash
$ conan build . --deployer ycm
```

This is not only inconvenient for the scenario in which I add a dependency, but any that impacts the `generators` folder, including:
* Changing build type
* Changing profile
* Modifying the dependency tree
* Changing a package option

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @samuel-emrys 

Thanks for your suggestion.
I think this could make sense, but I'd like to understand a bit better:

- Why ``ycm`` is not a generator instead of a deployer? Does it copy files from cache?
- Typically those generators and things like ``ycm`` are needed for your IDE before building. But calling ``conan build`` already automatically builds it, so no need for the IDE with that flow? The expectation is using ``conan install`` + ``your build system/IDE``, or ``conan build`` when not using and IDE

**Comment by samuel-emrys** [comment]
> * Why `ycm` is not a generator instead of a deployer? Does it copy files from cache?

That's a good question. I opted for a deployer based on advice you provided in https://github.com/conan-io/conan/issues/10751. It was a generator in conan 1.x, so if custom generators are a thing again, that might be a more natural workflow. For interest, the deployer is available [here](https://github.com/samuel-emrys/conan-ycm-deployer) if you have any specific suggestions.

> * Typically those generators and things like `ycm` are needed for your IDE before building. But calling `conan build` already automatically builds it, so no need for the IDE with that flow? The expectation is using `conan install` + `your build system/IDE`, or `conan build` when not using and IDE

Perhaps "IDE" is over-representing vim. I use vim as an enhanced text editor. I rely on the ycm deployer mostly for symbol resolution/code following/to enable static analysis. This really just involves the generation of a `conan_ycm_flags.json`, which contains the includes, defines and build flags. I build from the command line, so generally it's not hugely important to me that the build happens before I look at the code, or while I'm looking at the code.

**Comment by samuel-emrys** [comment]
I hadn't realised that the custom generator functionality had been re-added (documented [here](https://docs.conan.io/2/reference/extensions/custom_generators.html#using-global-custom-generators)). I think this is probably a more natural use case for a generator rather than a deployer, so I've re-implemented this functionality as a generator ([here](https://github.com/samuel-emrys/conan-ycm-generator)).

The same issue persists though; `--generator` is not on the `conan build` interface so this feature request stands. I think that there's probably still utility in `--deployer` being on the interface where copying from the cache is required and a generator may be insufficient/less semantically appropriate so perhaps this could stay?

**Comment by memsharded** [comment]
> I hadn't realised that the custom generator functionality had been re-added (documented [here](https://docs.conan.io/2/reference/extensions/custom_generators.html#using-global-custom-generators)). I think this is probably a more natural use case for a generator rather than a deployer, so I've re-implemented this functionality as a generator ([here](https://github.com/samuel-emrys/conan-ycm-generator)).

Yeah, when I was recommending deployers before, is because custom generators in the cache haven't been restored yet. We thought back then that deployers could cover all cases, but it was not true, so we finally brought back the generators (with different interface) in cache for Conan 2.0

Quick implementation question: The ``conan build`` command runs first ``conan install`` then the ``build()`` method. When calling ``conan install`` it does the deploy at the end of the install process. Should ``conan build ... --deployer=xxx`` also deploy after the install, but before the ``build()``?

**Comment by samuel-emrys** [comment]
> Quick implementation question: The conan build command runs first conan install then the build() method. When calling conan install it does the deploy at the end of the install process. Should conan build ... --deployer=xxx also deploy after the install, but before the build()?

Yes, I think so. Deployers typically operate on packages in the cache. Since `build()` doesn't place anything in the cache, I don't think it would make sense for it to do anything with the freshly built artifacts (unless you want to expand its scope). Running before `build()` is the behaviour I would expect.

**Comment by memsharded** [comment]
Merged https://github.com/conan-io/conan/pull/14737 for next 2.0.11
