### ISSUE TITLE
[feature] conan_toolchain.cmake: consider segregating blocks in separate files

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#14641]
### What is your suggestion?

The contents of `conan_toolchain.cmake` consist of several logic "blocks". For some users in tightly controlled environments, they may only be interested in some subsets of the file, wanting to avoid the rest.

If the logic blocks are in separate files, users could selectively `include()` them for CMakeLists.txt. This can be useful in situations where the users have pre-existing CMake toolchain files that must be used, or where the variables/behaviours set by `conan_toolchain.cmake` conflict with the project in ways where the user wants greater control.

Consider segregating the different logic blocks into separate files - `conan_toolchain.cmake` can still `include()` them all - and users can optionally include only what they need, where they have enough control to do the right thing ™️ . 

From team discussion:
- this behaviour could be enabled under an opt-in conf, retaining the current behaviour otherwise.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I have implemented this https://github.com/conan-io/conan/pull/14731 for the other PR with a very simple interface.

I am thinking that the level of control achieved with this current proposal:
- Splitting the ``conan_toolchain.cmake`` in multiple files, on per block
- Including in CMakeLists.txt ``include(particular_block)`` only desired blocks

Would be identical behavior to:
- Do a ``blocks.filter(desired_blocks)``, very simple interface
- Include in CMakeLists.txt ``include(conan_toolchain.cmake)`` than only contains code for desired blocks

So it seems to me that https://github.com/conan-io/conan/pull/14731 would be "two birds with a stone"?

**Comment by craigscott-crascit** [comment]
This issue arose out of a private conversation I had with @jcar87. Looking at the changes in #14731, I think that would work for the motivating use case. If I understand correctly, the behavior I'd be trying to achieve could be obtained like so:

```python
def generate(self):
    tc = CMakeToolchain(self)
    tc.blocks.filter("find_paths")
```

I could then put `include(path/to/conan_toolchain.cmake)` in my CMake file where I need to bring in just the changes to the CMake variables `CMAKE_PREFIX_PATH`, `CMAKE_MODULE_PATH`, `CMAKE_PROGRAM_PATH`, etc. The `filter()` would ensure the conan-generated toolchain file didn't have other things I wouldn't want to bring in other than just the path variables.

**Comment by memsharded** [comment]
Hi @craigscott-crascit 

Yes, this is exactly what I realized, that by easy filter (it seems that it will be called ``.select("find_paths")``) the blocks that you want, directly including the ``conan_toolchain.cmake`` directly provides the desired behavior, with the added advantage that it is easier for users, no need to find in the docs what is the specific name to ``include(conan_find_paths_toolchain.cmake)`` or whatever.

It seems that beyond the blocks the ``conan_toolchain.cmake`` also contains variables (only if defined in ``generate()``) and an include-guard, so it seems that it shouldn't be an issue, and implement the desired use case.

**Comment by memsharded** [comment]
I am tentatively marking this to be closed by https://github.com/conan-io/conan/pull/14731, if we realize it is not enough, or there are other not covered cases, we can reopen again. Thanks!
