### ISSUE TITLE
Windows bash using WSL2

### ISSUE THREAD

**Issue by vasama** [conan-io/conan#14647]
Conan has some support for using WSL as the subsystem for bash on Windows. The configuration value `tools.microsoft.bash:subsystem=wsl` is recognised and is at least partly implemented. I tested this using WSL2.

List of issues found while testing the `libiconv` package build:
* https://github.com/conan-io/conan/blob/develop2/conans/client/subsystems.py#L105
  Here the use of MSYS is assumed. While using WSL, the correct options would be something like `-e bash -- -c`.
* In the generated conanbuild environment scripts some absolute paths such as `script_folder` use Windows paths (`C:/...`) instead of the corresponding WSL paths (`/mnt/c/...`).
* In WSL Windows executables such as `cl.exe`, despite being in path, are not found using the name `cl` without the extension as they are on Windows. Perhaps generating forwarding scripts in a separate directory and appending that directory to path could solve this issue neatly.

There are still more issues that I was not yet able to work around. I will update this issue if I do.

**Comment by jcar87** [comment]
Hi @vasama  - thank you for opening this issue.

could you please add which commands you are running under which environments (version of Conan, etc), as well as which errors you are getting, so that we can reproduce this on our end? Thanks!

**Comment by vasama** [comment]
Conan 2.0.9

With conf:
```
tools.microsoft.bash:subsystem=wsl
tools.microsoft.bash:path=C:/Windows/System32/wsl.exe
```

`conan create conan-center-index/recipes/libiconv/all --version=1.17`

The errors were various of course. Some of them i worked through as i explained. I'm personally not too familiar with GNU Make, which is what libiconv uses, so debugging that wasn't as speedy as it might have been.

**Comment by memsharded** [comment]
Hi all,

Sorry this was not followed up.
It is true that ``wsl`` is there in the settings. But in practice this is a legacy from Conan 1.X, and is not really supported in practice in Conan 2:
- The docs only contain a mention in the ``settings.yml``: ``subsystem: [null, cygwin, msys, msys2, wsl]`` but absolutely nowhere else.
- There aren't any test in the test suite covering this, it is very likely that it will not work as expected
- We haven't seen any real demand or issues about it, so most likely this will keep being relatively unsupported. As we see it, users are using WSL mostly nowadays like any other Linux system, but not that much as a ``bash`` or substitute for ``msys2``.

To support this, it would require a relatively big effort, and I am afraid we don't have the necessary resources at the moment. What have you done? Have you settled for ``msys2`` usage?

**Comment by vasama** [comment]
This was a while ago. I think I ended up using msys.

**Comment by memsharded** [comment]
Ok, lets close the ticket then as not planned, we will probably leave ``wsl`` undocumented in the docs, and we might eventually mark it as deprecated.
