### ISSUE TITLE
Define standard env-var CONAN_RUN_TESTS or similar as convention for running unit-test

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1464]
From: https://github.com/conan-io/conan/issues/1170 cc/ @KalleDK 

I commented about a ``unittest()`` but that would involve repeating much of the code from ``build()``. As recipes have to manage/define it anyway, I think defining a variable would be simple and good.

**Comment by KalleDK** [comment]
Yes after some month developing, I tend to agree the unittesting should simply be a part of the builld step with a variable - as in not a part of conan itself.

**Comment by memsharded** [comment]
Ok, thanks very much for this feedback. Yes, it makes sense, so lets try to define at least such standard env-var and use case in the documentation.

**Comment by memsharded** [comment]
Closing this, and moving it to docs: https://github.com/conan-io/docs/issues/511
