### ISSUE TITLE
[bug] activate_build.sh is broken for conan v1

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#14657]
### Environment details

* Operating System+version: Linux 20.04
* Compiler+version: gcc9
* Conan version: 1.60.2

### Logs

I have created  conanfile.txt:

[build_requires]
cmake/3.22.6

Then call `conan install . -g virtualbuildenv`

then `chmod +x activate_build.sh`
and `./activate_build.sh`

after all cmake version is from the system:
 cmake --version
cmake version 3.27.1

**Comment by AndreyMlashkin** [comment]
[tool_requires] gives the same result

**Comment by memsharded** [comment]
Hi @AndreyMlashkin 

Thanks for your report.
Could you please try using the 2 profiles approach, passing some "build" setting or profile? 
Also the ``virtualbuildenv`` generator is the legacy one. The recommended one would be the ``VirtualBuildEnv`` with CamelCase, it is not the same generator. Could you please also give it a try and let us know?

**Comment by AndreyMlashkin** [comment]
It generates conanbuild.sh and conanbuildenv-release-x86_64.sh

after sourcing them, cmake is still pointing to the system one...

**Comment by memsharded** [comment]
This seems to be working fine, just tested it:
```bash
conan install . -g VirtualBuildEnv
source conanbuild.sh
conan@6e0d53d31473:~/conanws/kk$ cmake --version
cmake version 3.22.6
```

Note it is very important to ``source`` it, not execute it.

**Comment by AndreyMlashkin** [comment]
Yes, it seems source makes the trick, thank you!
