### ISSUE TITLE
Please provide a link to the repository of Conan 1.

### ISSUE THREAD

**Issue by gl-yziquel** [conan-io/conan#14658]
### What is your suggestion?

Hi.

I am trying to build a repository called hyperon-experimental.

https://github.com/trueagi-io/hyperon-experimental

It relies on Conan 1.60.2. And fails with Conan 2.

As I like to build things from source and have access to the source, I would like to kindly request that the README mentions where to find the code of Conan 1.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gl-yziquel 

Thanks for your question.

The ConanCenter repo works simultaneously with Conan 1 and Conan 2. All recipes there are built in CI against Conan 1.60.2. It is possible that some will not work in Conan 2.0 yet (the majority should), but they will definitely work with Conan 1.60. 
So no need for another repo, it is the same ``conancenter`` repo. Maybe you just need to ensure that Conan 1.60 is installed? (something like ``pip install conan==1.60.2``?)

**Comment by gl-yziquel** [comment]
Yes. I noted that 1.60.2 is tagged in the repo. (I like to get to the source...). So I checked it out.

Sorry for that not so useful issue I opened.

**Comment by memsharded** [comment]
No prob, do not hesitate to create new tickets for any other question that you might have.
