### ISSUE TITLE
[bug] CMAKE_OSX_DEPLOYMENT_TARGET for macOS does not support point releases

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#14656]
### Environment details

* Operating System+version: macOS
* Compiler+version: Xcode 15 (SDK 14.0) running on macOS 13.
* Conan version: 2.0.10
* Python version:

### Steps to reproduce

Discovered this using `cmake-conan`'s logic when passing `os.version`.

* `os.version` is only defined in `cmake-conan` if `CMAKE_OSX_DEPLOMENT_TARGET`
* `CMAKE_OSX_DEPLOYMENT_TARGET` is usually "empty" when targetting macOS, unless:
   - it is set manually
   - the SDK version detected is _newer_ than then OS we are currently running, in that case, it is set such that the binaries are compatibles with the OS we are usin

The SDKs (and thus. `os.version`) support point releases as valid targets, but for macOS, `settings.yml` only models the `.0` release for each major.  For the other Apple OSs (iOS, tvOS, watchOS), we do properly track the point releases.

Suggestion: accept point releases as valid `os.version` setting for macOS 11+ 

### Logs

```
ERROR: Invalid setting '13.5' is not a valid 'settings.os.version' value.
Possible values are ['10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15', '11.0', '12.0', '13.0', '14.0']
```

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/14740
