### ISSUE TITLE
Missing error message for non-existent options in package of lower version

### ISSUE THREAD

**Issue by ueberschall** [conan-io/conan#14652]
### Environment details

* Operating System+version: Linux Mint 21.1
* Compiler+version:
* Conan version: 1.55
* Python version: 3.10

### Steps to reproduce

I have a Conan package B that depends on another package A. A does have two versions 0.1.0 and 0.2.0. The version 0.2.0 of A does have an option "my_option" but 0.1.0 doesn't have it. Package B uses version 0.1.0 of A in its conanfile. If I execute the following command for B

conan install . -o A:my_option=anything

then the dependencies for B are installed, without any error message, despite the fact that A 0.1.0 does not have the option "my_option".

What I expect is that Conan interrupts the execution of the install command with an error message that A does not have the option "my_option".

**Comment by memsharded** [comment]
Hi @ueberschall 

Thanks for your question.
With Conan 1.60, the behavior is as follows:
```
conan install zlib/1.2.13@ -o zlib:potato=123
Configuration:
[settings]
...
ERROR: zlib/1.2.13: option 'potato' doesn't exist
Possible options are ['shared']
```
So it seems to be working fine.
Using a pattern like:
```
conan install zlib/1.2.13@ -o zlib*:potato=123
```
Will not fail

There are some possibilities here:
- The ``A`` package name is not valid one. Maybe you are missing some detail there. The pattern used must the be the full name
- Conan 1.55 had some issue, it would be worth upgrading to 1.60.2 and checking it

**Comment by steinerthomas** [comment]
> So it seems to be working fine. Using a pattern like:
> 
> ```
> conan install zlib/1.2.13@ -o zlib*:potato=123
> ```
> 
> Will not fail

Hi @memsharded!

Is there a documentation for this "non-existent" options feature?
I'm glad that this feature exists, but I can't find it in the docs.

**Comment by memsharded** [comment]
Maybe this section helps https://docs.conan.io/2/reference/config_files/profiles.html#reference-config-files-profile-patterns?

**Comment by steinerthomas** [comment]
Thanks, it's also mentioned here: https://docs.conan.io/2.0/reference/conanfile/attributes.html#default-options

Too bad, that it's not mentioned that it can be used for optional options to prevent errors on missing non-existent options. But it's logical, because it's a pattern...

**Comment by memsharded** [comment]
You are linking a slightly outdated version of the docs, better see https://docs.conan.io/2/reference/conanfile/attributes.html#default-options

I think in the updated docs it is a bit more clear about the pattern, but maybe you want to suggest a PR clarifying this point in the docs repo?
