### ISSUE TITLE
[question] Reverse dependencies/Dependents of a package

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#14661]
### What is your question?

Dear Conan Folks,

Is it possible to see which packages is dependent on my package?
Example: My package is lets say X, X is used by A, B, C.
I need a command that says who uses X meaning A, B and C.
I know the commands for checking the dependencies in my package using conan graph .

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

Thanks for your question.
No, Conan does not model the reverse dependency, as that can be an intractable problem in a decentralized setup with multiple repositories.

The recommended approach is a bottom-up approach, starting the CI processes from the consumers "products". Please have a look at the https://docs.conan.io/1/versioning/lockfiles/ci.html page, specially https://docs.conan.io/1/versioning/lockfiles/ci.html#products-pipeline (this is for 1.X, but the core concepts will be the same for 2.0)

**Comment by maitrey** [comment]
Understood, please close the ticket.
