### ISSUE TITLE
[feature] Add nobara distro -> dnf package manager mapping

### ISSUE THREAD

**Issue by lukester1975** [conan-io/conan#14665]
### What is your suggestion?

As per subject. It's a two liner, have a branch ready if this becomes "queue"d.

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lukester1975 

Sure, thanks for the report and the offer to contribute it! Feel free to open a PR for it (against ``release/2.0`` branch, please)

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/14668 for 2.0.11
