### ISSUE TITLE
conan config install of conan 2.0.10 not working on centos8

### ISSUE THREAD

**Issue by laxmij-cmd** [conan-io/conan#14671]
Hi,

I downloaded conan 2.0.10 from https://github.com/conan-io/conan/releases ([conan-linux-64.tar.gz](https://github.com/conan-io/conan/releases/download/2.0.10/conan-linux-64.tar.gz). When I run conan config install command on centos8 (8.5.2111), error is

./conan config install git@gitlab..../abc.git

![image](https://github.com/conan-io/conan-center-index/assets/111378770/2105b184-bb74-43b8-a125-3338afec825d)

In my knowledge, any executable/program built on centos7 must run on centos8. Please help.

Best Regards
Laxmi

**Comment by laxmij-cmd** [comment]
No such issue on centos7. It works as expected.

**Comment by AbrilRBS** [comment]
Hi @laxmij-cmd! Thanks for the report.

This is probably not the repo you want to open this PR, I'm moving it to the conan client one :)

But this looks like a compatibility issue with either Centos or python's from the looks of it

**Comment by memsharded** [comment]
This looks like a binary compatibility issue of the ``conan.exe`` binary created with ``pyinstaller``.
We create it in some "old" distro, so the glibc version is widely compatible, but this looks more like a forward compatibility thing, not a backwards one.

**Comment by czoido** [comment]
Hi @laxmij-cmd,

Thanks for reporting. This issue does not seem related with the Conan Client executable but an issue when executing `git` via SSH. Do other Conan commands besides `conan config install` also fail?
The error suggests there's a problem with the shared library `libk5crypto.so.3` (part of Kerberos) trying to use a specific function from OpenSSL (`EVP_KDF_ctrl`). This hints at a conflict or incompatibility between library versions on your system.

**Comment by memsharded** [comment]
Hi @laxmij-cmd 

Any update here? As @czoido was suggesting, this looks like that ``git`` is failing via ssh, but not a Conan issue. Are other Conan commands working fine and this the only one failing?

**Comment by laxmij-cmd** [comment]
This issue was resolved when re-installed. Sorry for not closing the issue.

**Comment by memsharded** [comment]
No prob, thanks for responding and closing!
