### ISSUE TITLE
[question] Why does conan rebuild my dependencies which are already built ?

### ISSUE THREAD

**Issue by barchstien** [conan-io/conan#14670]
### What is your question?

Hi Everyone

I use conan in docker to build my_bin and my_lib
my_bin depends on my_lib
my_lib is built and exported on my local (docker container) machine
my_build is built, and regardless on all my attempts, always end up rebuilding my_lib
I use : 
`
version: 2.0.10
python
  version: 3.10.12
  sys_version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
`

I am sure that I use the same version/user/channel
I have also tried with no user/channel (so that the pkg is named my_lib/M.m.p instead of my_lib/M.m.p@user/channel)
Note that M.m.p is just for that question, it is actually 5.3.2. Just like my_bin and my_lib are not the real names
Note also that when I say it rebuilds, that's because I use build=missing. If I were using build=never, the build would fails with "missing pre-built package"

I understand that the configuration/option also contributes to the hash, but I am using the very same machine with the same default profile. The `Input profiles` of both my_lib and my_bin do match
The consumer (my_bin) only refers to my_lib as :
`self.requires("my_lib/M.m.p")`

Also, I see that my_bin does use the same my_lib pkg that I just built because in
`Computing dependency graph` of my_bin I see the very same `my_lib/M.m.p#hash` as when my_lib is built with `conan create ...`

When reaching the `Computing necessary packages`, I see that my_lib is scheduled for being rebuilt :
`my_lib/M.m.p#hash:another_hash`
Note that that "hash" does match what I see when I conan create my_lib
But "another_hash" does not match
I do not know where that 2nd hash is from

So what am I missing ?
Can I list all elements which makes the hash ?
What did I miss ?

I have found https://docs.conan.io/2/tutorial/creating_packages/configure_options_settings.html
it would be nice to give some links when you state : "there is far more to package ID calculation than what we explain here"

Cheers
Bastien

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @barchstien 

Thanks for your question.

> my_build

Not sure what package is this one, you only introduced ``my_bin`` -> ``my_lib`` packages.

The ``another_hash`` is the ``package_id``. It is the hash of the configuration (``settings`` + ``options`` + ``dependencies`` versions). You can find some explanations about it in the tutorial like here: https://docs.conan.io/2/tutorial/creating_packages/create_your_first_package.html

The ``package_id`` is computed as the sha1 of the ``conaninfo.txt`` that is contained in each binary package, that contains the ``settings``, ``options``, etc. the information that is displayed with ``conan list mypkg*:*``, and you can see the file easily with ``conan cache path pkg/version:package_id`` will give you the cache path where the ``conaninfo.txt`` is located.

So for some reason, it seems there is some mismatch in the configuration in the ``conan create`` of the ``mylib`` and then when you try to build ``my_bin``. To understand what is happening, it would be good to know:

- The output of the ``conan create`` command (for ``mylib``)
- The output of the ``conan create`` or ``conan install`` command you are doing at the consumer ``my_bin`` package.

**Comment by barchstien** [comment]
Thanks for your quick answer

`conan create .` on mylib gives : 
```
etta/5.3.2: Exported: etta/5.3.2#a453ef9620366c12bb81967d90848e70 (2023-09-05 21:20:47 UTC)
[...]
etta/5.3.2: Package 'f956f104b5a9b0ee0e9b8ca578e164d0429ecbb1' built
[...]
etta/5.3.2: Created package revision 4bbaee95c8a5e8a749712b5b90267dc8
etta/5.3.2: Package 'f956f104b5a9b0ee0e9b8ca578e164d0429ecbb1' created
etta/5.3.2: Full package reference: etta/5.3.2#a453ef9620366c12bb81967d90848e70:f956f104b5a9b0ee0e9b8ca578e164d0429ecbb1#4bbaee95c8a5e8a749712b5b90267dc8
```

----

On `my_app`
```
======== Computing dependency graph ========
    etta/5.3.2#a453ef9620366c12bb81967d90848e70 - Cache
[...]    
======== Computing necessary packages ========
etta/5.3.2: Checking 11 compatible configurations:
etta/5.3.2: '90532b9ef93e8d1667f75c54d26a4786154985c4': compiler.cppstd=98
etta/5.3.2: '8a4200b700a8ecea214dc46b8d8530e45757338a': compiler.cppstd=gnu98
etta/5.3.2: '240d5927467c03fce7d35caf346deae745234c04': compiler.cppstd=11
etta/5.3.2: 'e847dc42c6161d4b55c0dc9689dec66fe12c3c82': compiler.cppstd=gnu11
etta/5.3.2: '7046d81b75bcf47a1483653587e631a04793bb35': compiler.cppstd=14
etta/5.3.2: '4baf5994677c2b02d914fbc62a4eba28c1508864': compiler.cppstd=gnu14
etta/5.3.2: 'd8c971b1d5abce5045ba9dd23519a2d8f5e2da49': compiler.cppstd=17
etta/5.3.2: '0052afb07ef3403fed884bf2842b5053bc47cc11': compiler.cppstd=20
etta/5.3.2: '211502207e37e292be9a05f7bf061ade9212fff0': compiler.cppstd=gnu20
etta/5.3.2: 'fa384fb63db53d1f69256944ad1e555684a0e94a': compiler.cppstd=23
etta/5.3.2: 'ca9a9769486936155997d0a851d40b1afc1ca4a6': compiler.cppstd=gnu23
[...]
Requirements
    etta/5.3.2#a453ef9620366c12bb81967d90848e70:5e4e14c3bc7b2f82390bd4b733eff55a866a8d8e - Missing
```

----

I see now there's actually 3 hashes
1. the one from the exported source `a453...`
2. the one from the bin/lib built, I guess it's the package_id
3. the revision (https://docs.conan.io/2.0/tutorial/versioning/revisions.html)

I hope I get it right so far ?

Then the consumer (myapp) does find the source or recipe, ie `a453...`

Then it lists the "compatible configurations", which I guess relates to the 2. hash
I do not see the expected hash, and I also see that only my `compiler.cppstd=gnu17` is not listed. Is that a hint about the source of my problem ?

Then the hash in the requirement  `5e4e...` is actually not in the list

Could I get more verbose on those several hashes calculations ?

**Comment by barchstien** [comment]
Here the profile
host and build are the same
```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
[buildenv]
CC=/usr/bin/gcc-12
CXX=/usr/bin/g++-12
```

**Comment by memsharded** [comment]
Just to double check, are you passing the profile to both commands?
If you paste the full output of both commands, the profile should be visible there in both.

In the second case, the profile ``gnu17`` is not checked, because that is the default one, not one of the potentially compatible ones.

**Comment by barchstien** [comment]
I get it now...
When I set `myapp` `default_options` to the very same value as `mylib` (etta in my post above), then the consumer project does get the built binary
```
Requirements
     etta/5.3.2#a453ef9620366c12bb81967d90848e70:f956f104b5a9b0ee0e9b8ca578e164d0429ecbb1#4bbaee95c8a5e8a749712b5b90267dc8 - Cache
```

Which sounds obvious now...
But then, there must be something I'm using wrong
I used `default_options` to setup deps of `mylib` like
```
default_options = {"shared": True, "boost/*:shared": True}
```
And then in `myapp` I was doing
```
default_options = {"shared": True}
```

how do I deal with options that I want to be kept at the level of `mylib` ?
I certainly do not want to have my top consuming bin (here `myapp`) having to specify things about the deps of its deps

**Comment by barchstien** [comment]
About profile, I do use the one and only `default` I have
Any advice on how I should deal with options of the deps of my deps ? @memsharded

**Comment by memsharded** [comment]
In general, it would be better to keep the definition of dependencies options in recipes as much as possible:
- Recipes define their own options and default options values
- Consumers of those recipes should in general build by default with the dependencies default
- Variability of dependencies options is better controlled by ``profiles``, not by consumer recipes

The reason is that defining options values in recipes can have some issues, for example, incompatible values for diamond structures (2 different consumers setting different values for a dependency option).

If you want to change the recipe defaults, it is better to do that, change the default in the recipe (this might be relevant: https://docs.conan.io/2/devops/using_conancenter.html). For settings things like having the whole dependency graph as shared libraries, using ``*:shared=True`` would be good.

Please let me know if this helps.

**Comment by barchstien** [comment]
Thanks for the clarification
Would you say the default conan strategy is to use static linking ?
Do you have docs/advices on how to deal with dependencies of dependencies ?

**Comment by memsharded** [comment]
> Would you say the default conan strategy is to use static linking ?

Not only Conan, but I'd say it is generally recommended in C and C++ because it is typically easier to build, test, deploy, etc, and only in some advance cases in which binary size or hot-updating shared library dependencies, go for shared libraries.

ConanCenter recipes default to static linking, and things like templates from ``conan new`` will also default to static libraries.

> Do you have docs/advices on how to deal with dependencies of dependencies ?

Nothing really special. The idea is that consumers should not care much about transitive dependencies, they are kind of implementation detail of the direct dependencies. So dealing with dependencies of dependencies in general shouldn't require any special effort. Do you have any specific detail or question about this?

**Comment by barchstien** [comment]
I actually turned all my deps to static about 6 months ago
I was mostly on x86
I was wondering if I was doing anything exotic, coz outside of conan I had the impression that most lib out there do dynamic linking by default

Recently I had to compile the code on yocto for ARM
BTW,  I appreciate the conan 2.0 approach, as it doesn't leak in my CMakeLists.txt file. Coz yocto (bitbake) and conan are kinda competing, so I ignore conan for yocto related build
Then I had all kind of weird issues, which I tracked back to using static link to protobuf and grpc

All that lead me to try falling back on dynamic link
I think that now, I will stick to static link, except for protobuf and grpc

**Comment by memsharded** [comment]
> I was wondering if I was doing anything exotic, coz outside of conan I had the impression that most lib out there do dynamic linking by default

Not really, from our experience, static linking is the default (but it is true that dynamic linkage is used in many scenarios too, it is not that it is uncommon)

> BTW, I appreciate the conan 2.0 approach, as it doesn't leak in my CMakeLists.txt file. Coz yocto (bitbake) and conan are kinda competing, so I ignore conan for yocto related build

Excellent. We know that upgrading to Conan 2.0 takes some effort, but it is very superior to Conan 1.X in so many aspects, that it is totally worth the effort, we hope that this feedback keeps spreading and motivate users to upgrade to Conan 2.0

> Then I had all kind of weird issues, which I tracked back to using static link to protobuf and grpc
All that lead me to try falling back on dynamic link
I think that now, I will stick to static link, except for protobuf and grpc

Sounds good!
Any other question? Maybe we can close the issue if the question was resolved, don't hesitate to open new tickets as necessary for any further question.

**Comment by barchstien** [comment]
Closing
Thanks for the help
