### ISSUE TITLE
[question] Appending PATH instead of replacing it in profile (migration from conan v1 to v2)

### ISSUE THREAD

**Issue by steinerthomas** [conan-io/conan#14686]
### What is your question?

Currently I'm trying to prepare the migration for conan v1 to conan v2, there I faced an interesting issue:
I had to append the PATH in conan v2 profiles instead of replacing it with the toolchain binary-path as we did in conan v1 profiles.

**conan v1 profile:**
https://github.com/steinerthomas/vs-cmake-conan-wsl-template/blob/migrate-conan2/.conan/profiles/gcc8x86

**conan v2 profile:**
https://github.com/steinerthomas/vs-cmake-conan-wsl-template/blob/migrate-conan2/.conan2/profiles/gcc8x86

Why was it ok to replace the PATH in conan v1?
Would be interesting if this profile looks good to you for cross-compiling scenarios?
Especially appending the PATH + setting the environment variables and appending the conan user_toolchain with our's.

PS: If you have time, you can take a look into my approach, migrating a Visual Studio 2022 conan-cmake project with debugging and cross-compiling on WSL1 from conan v1 to v2. Therefore I've created a dummy project https://github.com/steinerthomas/vs-cmake-conan-wsl-template/pull/1

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @steinerthomas 

Thanks for your question.

Just in case, and for other readers, the profiles you are defining with ``[buildenv]`` are also available in Conan 1.X, it is not strictly a migration issue from 1.X but from the legacy ``[env]`` to the new ``[buildenv]``, that can happen in 1.X only.

> Why was it ok to replace the PATH in conan v1?

The trick is that the legacy ``[env]`` is actually appending, not replace the PATH, when the parameter is a list. This is why the more explicit operators ``+=`` or ``=`` are used in the ``[buildenv]`` approach.

> Would be interesting if this profile looks good to you for cross-compiling scenarios?

Yeah, I think it looks good. Conan has a mechanism that is ``tools.build:compiler_executables`` that might have a bit wider reach than the ``CC`` and ``CXX`` env-vars, for build systems that don't listen to these variables. But if the env-vars are working fine for you, it is fine too.

**Comment by steinerthomas** [comment]
Hi @memsharded, 
thank you for your quick response - questions answered! :)
