### ISSUE TITLE
[question] Add own toolchain file into generator

### ISSUE THREAD

**Issue by KarstenErnert** [conan-io/conan#14680]
### What is your question?

Hi everyone,

this might be a stupid question, but I did not find the correct answer yet in the documentation.
I am using Conan 1.60.2 with tool packages that contain an own toolchain file. When I use now the toolchain file generator, it is also picking all of them up, adding them as an include to the `conan_toolchain.cmake`. 
Depending now on the compiler used (I have one for static testing and one for the native build) I want to add here 1 of 2 additional toolchain files to the `conan_toolchain.cmake`.
Is this an intended usecase?
How can I do that?

Thanks in advance

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @KarstenErnert 

Yeah, you have a configuration value to achieve that. Have a look at [this piece of documentation](https://docs.conan.io/en/1.60/reference/conanfile/tools/cmake/cmaketoolchain.html#using-a-custom-toolchain-file).

Basically, you can add this line to your Conan profile:
```
...
[conf]
tools.cmake.cmaketoolchain:user_toolchain=["toolchain1", "toolchain2"]
```
And it'll automatically add those toolchains to your Conan one as several include-lines.

**Comment by KarstenErnert** [comment]
Thanks for the quick answer, I will try it out today and have a look if it actually is what I am looking for.
Currently I am using the following to do some switches in the CMake:
`if(DEFINED X)
    include(TC_X)	
else()
    include(Y)
endif()`

**Comment by memsharded** [comment]
Quick hint, you might want to use the right "append/prepend" operators like ``+=`` in your profile to actually add your own toolchains, not overwrite the toolchains defined in ``tool_requires``. Please check the syntax in https://docs.conan.io/en/1.60/reference/config_files/global_conf.html#configuration-data-operators

**Comment by memsharded** [comment]
Hi @KarstenErnert 

I am closing this ticket as staled, I guess that it worked. If not, please feel free to re-open, or create a new ticket with further details, many thanks for your feedback.
