### ISSUE TITLE
[question] when using static library, there will be some linking order problem

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#14687]
### What is your question?

question like this: https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc

is there a way to solve this easily in conan? I always use tools.collect_libs, but it doesn't add order, so I have to write the order
personally.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

yes, ``collect_libs`` only read files, it is completely unaware of possible relations/dependnecies between libraries inside the same package.

The alternatives are:
- Define ``components`` and define the ``.requires`` to other components for each component. Conan will automatically order components in the right linking order
- Define the right order in the ``libs`` file, manually. Depending on the number of libs, this approach might be easier and more pragmatic.
