### ISSUE TITLE
AutoToolsBuildEnvironment do not define --host when cross-building x86_64 to x86

### ISSUE THREAD

**Issue by MarcoKoch** [conan-io/conan#1468]
From poking around in conan's source code, I know that it does not consider compiling from x86_64 to x86 as 'real' cross-building. Though I noticed that most `./configure` scripts I came across require the `--host` parameter to be specified in this case too to work correctly.
As a workaround I manually specified the `host` parameter to `AutoToolsBuildEnvironment.configure()`, which required to replicate some of the logic from `AutoToolsBuildEnvironment` that constructs those platform triplets.
I feel this not uncommon case should be handled automatically instead.

**Comment by memsharded** [comment]
Sounds legit, but I think @lasote should have a look first. Thanks!

**Comment by lasote** [comment]
@MarcoKoch thanks for reporting. I don't remember exactly which libraries I tried but if I excluded it probably is for some reason :S I'm afraid now to break something.

**Comment by lasote** [comment]
@MarcoKoch do you have any open source library example?

**Comment by MarcoKoch** [comment]
One example would be libunwind. I have a package recipe for that at https://github.com/MarcoKoch/conan-libunwind. I also had similar issues with ncurses.

**Comment by lasote** [comment]
Thanks! we will also review the FreeBSD integration currently not supported but managed by your recipe.

**Comment by MarcoKoch** [comment]
I have not tested that yet either. 😆
So I will be happy to hear about the results.

**Comment by memsharded** [comment]
Finally released in 0.28, feedback welcome!
