### ISSUE TITLE
[feature] conan command for listing the package revisions that went into building a package

### ISSUE THREAD

**Issue by geir-t** [conan-io/conan#14685]
### What is your suggestion?

Hi, when conan creating a package we can inspect the output of the command to know what package revisions went into the build.

```
conan create .
  creating foo/1.0.0@company#revision
  Requirements
  asio/1.28.0#83b60467ba4e3487d61a722166a0b - Downloaded (remote
  boost/1.81.0#9bd7ae86a881631b6c90621e470b - Downloaded (remote)
```

when we do 
`conan graph info --requires=foo/1.0.0@company#revision`
it recalculates the graph so the output from here does not necessarily match what foo/1.0.0@company#revision was built with. For testing and debugging it is important to know exactly what revisions went into a package. Basically I want to be able to fetch the lockfile that was used when building foo/1.0.0@company#revision.

Is this possible today?

Best regards

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @geir-t thanks for your question

Conan 2 now provides the ability to create package lists from some commands, [see the docs here](https://docs.conan.io/2/examples/commands/pkglists.html#building-and-uploading-packages)

The basic idea is that you can specify `--format=json` when creating your package (`conan create .... --format=json > pkgs.json`) to get the graph representation of what went into the creating of your package, and then you can pass that resulting file to `conan list` to get the info you're after, in your case `conan list -g pkg.json`

Let me know if that helps :)

**Comment by geir-t** [comment]
Thanks @RubenRBS, that is helpful. 

Do I understand correctly that there is no way of knowing what packages went into building a package if I did not store that information during creation? 

```
$ conan list zlib/1.2.13#*
Local Cache
  zlib
    zlib/1.2.13
      revisions
        e377bee636333ae348d51ca90874e353 (2023-07-11 09:24:06 UTC)
```
e.g. can I know what packages was used to build this zlib revision?

**Comment by AbrilRBS** [comment]
Hi @geir-t
> can I know what packages was used to build this zlib revision?

No. After the package has been built, not much information survives by default.

Another idea besides the pkglist (whose result can't be packaged with your resulting binary):

When building your recipe to modify its `generate()` method to write down a file containing all the data about the build that you might desire, and then to package it in the `package()` method for future consumers to be able to use it.

For something that stores the `pref` (So up to and including the package id and revisions) of each dependency, it could look something like this:

```py
from conan import ConanFile
from conan.tools.files import save, copy
import os

class Pkg(ConanFile):

    ... other stuff ...

    def generate(self):
        result = []
        for dep in self.dependencies.values():  # Will also contain transitive dependency data!
            result.append(dep.pref)
        save(self, os.path.join(self.build_folder, "dependencies.txt", str(result))

    ... more of your functions ...

    def package(self):
        # other packaging operations too here
        copy(self, src=os.path.join(self.build_folder, "dependencies.txt"), dst=os.path.join(self.package_folder, "dependencies.txt")

```
(See the `self.dependencies` [docs here](https://docs.conan.io/2/reference/conanfile/methods/generate.html#conan-conanfile-model-dependencies))

You could also create a global generator with the same idea to iterate the dependencies, [see its docs here](https://docs.conan.io/2/reference/extensions/custom_generators.html#using-global-custom-generators)

**Comment by geir-t** [comment]
This is great, thank you.
