### ISSUE TITLE
[question] conan config install tag

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#14681]
### What is your question?

Dear Conan Folks,

Is this the right way to install tag  using conan config install?
```
conan config install https://github.com/Radar/conan-config.git --args="-b 1.0.0"
```
I am using conan-2.0.6. and 1.0.0 is the tag on the repo where all the profiles are stored.
I donot see any errors but want to be sure.

Could you please confirm?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @maitrey thanks for your question.

I confirm that that's the expected way to do it.

Additionally, I'd also recommend adding `--depth 1`, as the command has no use for the rest of the git history and that might speed the clone up a bit :) In fact, let me check if we couldn't do this by default in the client!

**Comment by maitrey** [comment]
All clear , many thanks for confirming! ticket may be closed.
