### ISSUE TITLE
[bug] CMakeDeps ignores transitive dependencies in some cases

### ISSUE THREAD

**Issue by Ariox41** [conan-io/conan#14695]
### Environment details

* Operating System+version: ubuntu 22.04
* Compiler+version: gcc 11
* Conan version: 2.0.10
* Python version:  3.10.12

### Steps to reproduce

The problem appears in a large code base. So far we have not been able to reproduce the problem with artificial examples.

The problem appears when an indirect dependency enters the dependency graph as a transitive dependency of self.requires('...') and self.test_requires('...') at the same time.

Approximate dependency structure:

```python
class CMakeLibraryRecipe(ConanFile):
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": True, "fPIC": True} # all libraries are shared
    package_type = 'library'
    generators = "CMakeDeps"

class Lib1(CMakeLibraryRecipe):
    name = "lib_1"
    def requirements(self):
        #some requirements
        pass

class Lib2(CMakeLibraryRecipe):
    name = "lib_2"
    def requirements(self):
        self.requires('lib_1/[^0.1.0]', transitive_libs=True, transitive_headers=True) # ok

class Lib3(CMakeLibraryRecipe):
    name = "lib_3"
    def requirements(self):
        # ok, lib_1 is provided by сmake target lib_2::lib_2
        self.requires('lib_2/[^0.1.0]', transitive_libs=True, transitive_headers=True) 

class Lib4(CMakeLibraryRecipe):
    name = "lib_4"
    def requirements(self):
        self.requires('lib_1/[^0.1.0]', transitive_libs=True, transitive_headers=True)    
    def build_requirements(self):
        self.test_requires('lib_3/[^0.1.0]')

class Lib5(CMakeLibraryRecipe):
    name = "lib_5"
    def requirements(self):
         # error, cmake target lib_2::lib_2 does not provide lib_1 as a dependency
        self.requires('lib_2/[^0.1.0]', transitive_libs=True, transitive_headers=True)
    def build_requirements(self):
        self.test_requires('lib_4/[^0.1.0]')
```
After deleting `self.test_requires('lib_4/[^0.1.0]')` from the `Lib5.build_requirements`, the build completes successfully, which indicates an error in conan.

The problem can be solved by explicitly adding `find_package(lib_1)` and `target_link_libraries(${PROJECT_NAME} PUBLIC lib_1::lib_1)` to CMakeLists.txt . But for a large number of dependencies, this is inconvenient.

When debugging, the function `Conan File Dependencies.transitive_requires` looks suspicious:
```python
def transitive_requires(self, other):
        data = OrderedDict()
        for k, v in self._data.items():
            for otherk, otherv in other._data.items():
                if v == otherv:
                    data[k] = v
        return ConanFileDependencies(data)
```
For equivalent `k` and `otherk`, the values of  `v` and `otherv` are sometimes not equivalent. After deleting `self.test_requires`, the values become equivalent.

**Comment by memsharded** [comment]
Hi @Ariox41 

Thanks for your report, I am having a look.

Quick question: Why are you using ``transitive_libs=True`` in all cases? That is an unusual thing, that should probably be used only in some exceptional situations. ``transitive_headers=True`` is more common, it is good if it can be avoided, but if not, it is more expected. But ``transitive_libs=True`` should only happen when the public, transitive headers are not good enough as interface to the binary.

**Comment by memsharded** [comment]
I have replicated the above setup in a test, this is the dependency graph for reference: 
<img src="https://github.com/conan-io/conan/assets/15367152/b93134e1-f652-47c3-a9fb-fd754d559390" width=30% height=30%>

The "lib_3" and "lib_2" branch are "test_requires" of the "test_requires". As long as ``lib_4`` binary is there, these 2 dependencies are not needed.

I will share my test in a PR, to discuss over it

**Comment by memsharded** [comment]
This is the PR with the test mimicking your case above: https://github.com/conan-io/conan/pull/14697

I am checking the generated .cmake files:

- The ``lib_2`` files contain the correct definition of transitive dependency to ``lib_1``
- The ``lib_1`` files contain the correct definition of depending on the ``lib_1`` library, because ``transitive_libs=True``

Things are looking good so far, in theory it indicates that the ``find_package(lib_1)`` shouldn't be necessary, and that it is already bringing it automatically. If you could please try to have a look at the test (as you can see the testing framework we have is relatively easy), and see where the difference to your actual environment could be, that would help a lot.

**Comment by Ariox41** [comment]
We also failed to reproduce the problem on a small graph. On the weekend I will try to generate a test case with more complex dependencies. It is also possible that the result is affected by the dependency on Qt, which uses `self.cpp_info.components[componentname].requires`

As for `transitive_libs=True`, we encountered some `undefined reference`. We haven't figured this out enough yet, but we got the impression that using shared libraries is impossible without `transitive_libs=True`. Perhaps we should explicitly use `self.cpp_info.requires` instead of `transitive_libs`? But if I understand correctly, this is no better, unless the module contains several components, like Qt or boost. Similar problems do not occur when using static libraries, but this is not a solution.

We also noticed that most recipes in conancenter explicitly set `self.cpp_info.components[componentname].requires` instead of using `transitive_libs=True` or `transitive_libs=True`. Perhaps we should do the same?

**Comment by memsharded** [comment]
> As for transitive_libs=True, we encountered some undefined reference. We haven't figured this out enough yet, but we got the impression that using shared libraries is impossible without transitive_libs=True. 

It depends on the design of the libraries and their interfaces. We are building COnanCenter with ``*:shared=True``, and it is not necessary for all libraries, only some cases in which:
- The public headers are transitive ``transitive_headers=True``, and visible and used downstream
- Those headers are not pure interfaces, but they also need some implementation directly on the consumer (not via runtime shared libraries). This can happen, but not necessarily in all shared libraries.

> Perhaps we should explicitly use self.cpp_info.requires instead of transitive_libs?

That is only involved when there are componets, it is an orthogonal concept to the ``transitive_libs``, which is package-wise

> We also noticed that most recipes in conancenter explicitly set self.cpp_info.components[componentname].requires instead of using transitive_libs=True or transitive_libs=True. Perhaps we should do the same?

When your package recipe uses components, it is indeed necessary to express the dependencies of those components. It is possible that some linking errors come because not expressing these dependencies, and not necessarily because of ``transitive_libs``, yes.

**Comment by Ariox41** [comment]
I have not been able to reproduce the problem in a test environment.

After some changes, the problem also stopped appearing in the production environment, at least for the same problematic recipes. There have been two significant changes in the work environment:
- adding multiple self.cpp_info.requires for packages dependent on boost and qt components
- removing all packages from the package registry in Artifactory and then building from scratch

The only assumption I can make is that the problem did not occur in CMakeDeps, but when constructing the dependency graph. Perhaps two variants of the same dependency of the same version, but with a different package_id, got into the dependency graph?

In any case, I think the issue can be closed if you have no other ideas.

**Comment by memsharded** [comment]
> Perhaps two variants of the same dependency of the same version, but with a different package_id, got into the dependency graph?

This can happen, and it is not a problem per se, for example when requiring ``protobuf`` both as ``tool-requires`` (for protoc compiler) and as ``requires`` (for libprotobuf) in a cross-build scenario.

> In any case, I think the issue can be closed if you have no other ideas.

Yes, not sure what else could I try. Lets close it at the moment, please create a new ticket if you see it again, and we will investigate it again. Many thanks!
