### ISSUE TITLE
Use vswhere to locate VS

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1469]
From this comment https://github.com/conan-io/conan/issues/1402#issuecomment-312518695 we know that vswhere now comes bundled with VS, so maybe now it is easier to use it to locate VS 2017

**Comment by piponazo** [comment]
Hi. It's great that you are adapting to the new VS 2017 tools so quickly :)

I just wanted to ask if you tried to use the Visual Studio 2017 Build Tools (Without the IDE).

In conan 0.25.1, I can use a profile that makes use of Visual Studio 2017 but it only works if I have installed the full IDE (either the Community or Professional version). However, when I only have the Build Tools, conan does not find the compiler tools (Same error than #1503).

I guess that with the usage of **vswhere** the situation should be solved. Did you try that case ?

**Comment by memsharded** [comment]
Implemented, follow up in https://github.com/conan-io/conan/issues/1683
