### ISSUE TITLE
Add/remove remotes from command line

### ISSUE THREAD

**Issue by kreios4004** [conan-io/conan#147]
I would like the ability to add and remove remotes from the command line. This would allow for setting up new machines with scripts and not require modifying the config files directly. Below are some ideas on possible command line arguments.

`conan remote --add --name foo --url http://foo.com:1234`
`conan remote --remove --name foo`

**Comment by kreios4004** [comment]
An additional feature would be to list remotes. Basically, have similar features as git.

**Comment by memsharded** [comment]
Ok, this should be easy to implement. Why not go with the same syntax as git?

```
$ conan remote add myremote http://....
$ conan remote remove myremote
$ conan remote  // to list remotes
```

**Comment by kreios4004** [comment]
I don't have a problem with the git syntax.
