### ISSUE TITLE
How to generate Find<Package>.cmake in Conan 2.0?

### ISSUE THREAD

**Issue by bitwise-brew** [conan-io/conan#14701]
### What is your question?

I am trying to generate Find.cmake from Conan2.0 build for the set of c++ files. The cmake_find_package generator is depreciated in latest release and its been replaced by CMakeDeps generator. I am trying out with the sample C++ project.

All the sources are compiled as shared library.
```
base
├── CMakeLists.txt
├── conanfile.py
└── src
    ├── CMakeLists.txt
    ├── factorial
    │   ├── CMakeLists.txt
    │   └── factorial.cc
    ├── include
    │   ├── factorial.h
    │   ├── mul.h
    │   ├── sub.h
    │   └── sum.h
    ├── mul
    │   ├── CMakeLists.txt
    │   ├── mul.cc
    │   └── private
    │       ├── private_sum.cc
    │       └── private_sum.h
    ├── sub
    │   ├── CMakeLists.txt
    │   └── sub.cc
    └── sum
        ├── CMakeLists.txt
        └── sum.cc
```
I  use this conanfile.py
```
import os
from conan import ConanFile
from conan.tools.files import load, copy
from conan.tools.cmake import CMake, cmake_layout, CMakeDeps


class MyConanfile(ConanFile):
    name = "pkg"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain"
    options = {"shared": [True, False]}
    default_options = {"shared": True}
       
    def package_info(self):
       # I have a custom toolchain
       f=os.path.join(self.package_folder,"gcc7_linux_x86_64.cmake")
       self.conf_info.define("tools.cmake.cmaketoolchain:user_toolchain", [f])

       self.cpp_info.set_property("cmake_find_mode", "both")
       self.cpp_info.set_property("cmake_file_name", "PKG")
       self.cpp_info.set_property("cmake_target_name", "PKG::PKG")
       
    def generate(self):
        cmake = CMakeDeps(self)
        cmake.generate()       
       
    def export_sources(self):
        # The path of the CMakeLists.txt and sources we want to export are one level above
        folder = os.path.join(self.recipe_folder, ".")
        copy(self, "*.txt", folder, self.export_sources_folder)
        copy(self, "*.cc", folder, self.export_sources_folder)
        copy(self, "*.h", folder, self.export_sources_folder)
        copy(self, "*.cmake", folder, self.export_sources_folder)
    
    def source(self):
        # Check that we can see that the CMakeLists.txt is inside the source folder
        cmake_file = load(self, "CMakeLists.txt")

    def build(self):
        # Check that the build() method can also access the CMakeLists.txt in the source folder
        path = os.path.join(self.source_folder, "CMakeLists.txt")
        cmake_file = load(self, path)

        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        copy(self, "LICENSE", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))
        copy(self, pattern="*.h", src=os.path.join(self.source_folder, "include"), dst=os.path.join(self.package_folder, "include"))
        copy(self, pattern="*.so", src=self.build_folder, dst=os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, pattern="*.cmake", src=self.build_folder, dst=os.path.join(self.package_folder, "cmake"), keep_path=False)
```
Commands I run
```
conan create . -pr=<myprofile>
conan install . -pr=<myprofile>
```
This way I am able to generate the libraries. But the Find.cmake is not getting generated.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nanaveen 

Thanks for your question.

I guess that you mean how you can do that your package will be generating the ``find-mypkg.cmake`` module for consumers when consumers are using your package?

The idea would be:
- For your own packages, this is discouraged. CMake find modules are considered legacy, just for some existing open source third party libraries, but for everything else, the recommendation (CMake recommendation, not Conan one) is to use Config files instead
- If you still want your package to generate the file when downstream consumers are using ``CMakeDeps``, you can do it by:
  - Define your ``package_info()`` method. This method is necessary to define at the very least your ``self.cpp_info.libs = ["mylibname"]``, assuming that your directories are the standard ones
  - Define in your ``package_info()`` the ``self.cpp_info.set_property("cmake_find_mode", "module")``

Unless you are trying to reuse the .cmake file generated in your build, what are you trying to do with ``copy(self, pattern="*.cmake"``?

**Comment by bitwise-brew** [comment]
Yes I am trying to find/consume the libraries using the `find-mypkg.cmake` file. 

Say for example I am writing a addition application while compiling the same, I will be referring to the library via `find_package(add)` in my CMakeLists.txt. In that case even if I add `required=pkg\1.0` the precompiled libraries are not identified for application compilation. 

In this case how can I consume the precompiled libraries if there is no `find-<pkg>.cmake` ? In older versions it was automatically done by conan so it was effort less to consume the compiled libraries.

**Comment by memsharded** [comment]
> Say for example I am writing a addition application while compiling the same, I will be referring to the library via find_package(add) in my CMakeLists.txt. In that case even if I add required=pkg\1.0 the precompiled libraries are not identified for application compilation.

But you don't need a ``find-mypkg.cmake`` to do ``find_package(mypkg)``. The recommended way is to use a ``mypkg-config.cmake`` file instead. Why are you sticking to the legacy modules instead of using config files, if it is your own library?

> In this case how can I consume the precompiled libraries if there is no find-<pkg>.cmake ? In older versions it was automatically done by conan so it was effort less to consume the compiled libraries.

Not sure what is the issue. The ``CMakeDeps`` generator in the consumer side automatically generate pkg-config.cmake files for all dependencies, even if the dependencies do not use CMake at all, so dependencies don't need to worry about creating their own cmake files and packaging them, all is managed automatically by Conan ``CMakeDeps``. The concept is not new, it is the same as ``cmake_find_package_multi`` was doing, and it is not 2.0 only, as the ``CMakeDeps`` generator has been there for a long time already in Conan 1.X. You can migrate to it while being in Conan 1.X, then moving to Conan 2.0 will be easier, no need to change the recipe at all for Conan 2.0

I think there are some misconceptions in the recipe you share:
- You are using a toolchain and defining ``self.conf_info.define("tools.cmake.cmaketoolchain:user_toolchain", [f])``. This doesn't make sense for normal regular ``requires``, this only makes sense for ``tool_requires`` packages. But this package seems a regular library?
- It seems you have the .cmake file *before* even building the package: ``copy(self, "*.cmake", folder, self.export_sources_folder)``. This is unusual, I am not sure if I understand your flow. Typically these files are the result of building with cmake, and are produced in the ``build()`` step, not pre-existing.

I think I am missing the definition of the whole flow and desired behavior.

**Comment by bitwise-brew** [comment]
> You are using a toolchain and defining self.conf_info.define("tools.cmake.cmaketoolchain:user_toolchain", [f]). This doesn't make sense for normal regular requires, this only makes sense for tool_requires packages. But this package seems a regular library?

It was a requirement. This is trivial, please avoid

> It seems you have the .cmake file before even building the package: copy(self, "*.cmake", folder, self.export_sources_folder). This is unusual, I am not sure if I understand your flow. Typically these files are the result of building with cmake, and are produced in the build() step, not pre-existing

Yes its wrong. I will correct it.

> But you don't need a find-mypkg.cmake to do find_package(mypkg). The recommended way is to use a mypkg-config.cmake file instead. Why are you sticking to the legacy modules instead of using config files, if it is your own library?

Any examples are available in conan? If so kindly provide. Thank you!

**Comment by memsharded** [comment]
Sure, the whole tutorial and most of the examples are consuming generated config.cmake files by default: https://docs.conan.io/2/tutorial/consuming_packages.html, via the ``CMakeDeps`` generator.

For using some modules inside packages there are examples like this: https://docs.conan.io/2/examples/graph/requires/consume_cmake_macro.html, not exactly the same, but you can see the usage of ``self.cpp_info.builddirs`` there. It is still not fully clear if:
- You want to use your own config.cmake file generated by your build
- You want to leverage Conan to generate the config.cmake automatically for you (what most of the docs do)

**Comment by bitwise-brew** [comment]
> You want to use your own config.cmake file generated by your build

No, I don't want to use my own config.cmake

> You want to leverage Conan to generate the config.cmake automatically for you (what most of the docs do)

Yes I want conan to generate config.cmake

**Comment by memsharded** [comment]
Then, everything should be automatic by Conan:

- Drop the ``self.cpp_info.set_property("cmake_find_mode", "both")`` in the recipe. You can also drop the other properties, and use the standard file and target names, matching the package name
- Drop the ``copy(self, pattern="*.cmake"`` (both of them), they don't seem necessary
- Use ``CMakeDeps`` and ``CMakeToolchain`` in the consumers of your package
- Use ``find_package(mypkg)`` + ``target_link_libraries(myapp PUBLIC mypkg::mypkg)`` in the consumers side to link with the package library
