### ISSUE TITLE
Question: Facing linking issue with another imported library. Conan v1.60

### ISSUE THREAD

**Issue by jaswanthmv** [conan-io/conan#14702]
Hi, I am new to conan. I am using Ubuntu 20.04 and conan v1.60. 
I have a repo, inside which, there is an imported library. I am able to build and generate executable using normal CMakeLists but now wanted to generate a Conan package. So, I wrote a minimal conanfile.py which just builds the pacakge. I am able to generate package with Windows with the respective flavour of the imported package but facing issue with linux. 
collect2: error: ld returned 1 exit status
Is there any provision to link non-conan packages through conan.

Pkg

-Structure
     

     |_lib
            |_ Win

                     |_ <ImportedPkg>
                                                 |_ lib <.lib>
                                                 |_ bin <.dll>
                                                 |_ cmake <.cmake config files>
                                                 |_ include <.h files>
            |_ Linux
                     |_ <ImportedPkg>
                                                 |_ lib <.so>
                                                 |_ cmake <.cmake config files>
                                                 |_ include <.h files>
     |_ include
     |_ src
     |_ CMakeLists.txt
     |_ conanfile.py

Sample conanfile.py

exports_sources = "CMakeLists.txt", "src/*", "include/*", <imported_lib>

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def generate(self):
        tc = CMakeToolchain(self)
        tc.user_presets_path = False
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

**Comment by memsharded** [comment]
Hi @jaswanthmv 

Thanks for your question.
If you are packaging pre-compiled executables, you don't need the ``generate()`` and ``build()`` methods at all? Instead, the typical flow would be to use ``conan export-pkg`` to package the binaries you already have available in your folder: https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html#packaging-already-pre-built-binaries

Please have a look at that page, and let me know about your work flow with more details. If that is the case, this is not a ``cmake-conan`` question, it is a regular question about ``conan export-pkg`` and we can move it to the Conan repo.

**Comment by jaswanthmv** [comment]
Hi @memsharded 

Thanks for your quick response.
I had a look at the approach you suggested. It looks fine but, there is one issue. I have XXXXconfig.cmake files already provided with the imported package and would like to use these as they have some specific settings
`set_target_properties(XXXXX PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "XXXX_API=__declspec(dllimport);XX_VERSION_MAJOR=2;XX_VERSION_MINOR=1;XX_VERSION_PATCH=0"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)`
Is there any way I can add these target properties through conan or can I use the provided XXXXconfig.cmake files with conan?

**Comment by memsharded** [comment]
If you have config.cmake files, you need to:
- Make sure you are packaging it in the final ``package()``
- Define ``self.cpp_info.builddirs = ["."]`` (if it is in the root, otherwise the folder containing the config.cmake file), in your ``package_info()`` method, for consumers to be able to discover and use it.

Moving this to Conan repo, this has nothing to do with ``cmake-conan``, but about creating your own package with ``conan export-pkg``

**Comment by jaswanthmv** [comment]
Thanks for the help.
