### ISSUE TITLE
Should `conan cache clean <ref>` remove the local backup files for that reference?

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#14707]
Basically the title so we can discuss it at some point:

If a backup only contains that reference in its associated json file, should it be deleted if I run `conan cache clean`?

Edit: Just realized I just tested with the default flags. Maybe -s does that! Will check as soon as I can

**Comment by memsharded** [comment]
Probably not.

The download cache can be shared among multiple Conan caches, like in a CI agent, saving lots of external transfers to that machine, even if using blank new caches for every build in CI. So cleaning the cache ``conan cache clean`` probably shouldn't be tied to the download cache.

But we might want to consider adding something explicit to clean it, always more convenient than guessing the folder and ``rm`` it
