### ISSUE TITLE
Potential issues with private repositories and public backups

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#14703]
### What is your suggestion?

From Sam at CppLang's slack:

Lets say I have the following remotes:
```
$ conan remote list
conancenter: https://center.conan.io/
mypublicremote: https://myserver.com/mypublicremote
myprivateremote: https://myserver.com/myprivateremote
```
and in my global.conf, i set

```
core.sources:download_urls=["origin", "myserver.com/backup-sources"]
core.sources:upload_url=https://myserver.com/backup-sources
```

if I install a dependency, for example, with:
`conan install --requires openssl/1.1.1t -r conancenter --build openssl`
And then upload it with
`conan upload openssl/1.1.1t -r mypublicremote`
then everything works as I would expect - I'm able to build my own binaries using conan-center recipes, upload them to my own remote, and also have the sources mirrored in https://myserver.com/backup-sources (I assume, I haven't actually tested this).

But, if I want to follow this process for my private remote, I could contaminate the sources, i.e. if i:
`conan install --requires myprivatelib/x.y.z -r myprivateremote --build myprivatelib`

Then this might download sources from an access controlled repository. If i then run:
`conan upload myprivatelib/x.y.z -r myprivateremote`

Then at least as I currently understand it, the sources that have been downloaded from an access controlled repository would get backed up to https://myserver.com/backup-sources, which is now a mix of public and private source archives. Someone without access to myprivateremote or the access controlled source archives would now be able to access the source archives.

I'm wondering if this has garnered any thought so far (all good if not!) and if there's a process that could help address this, or maybe I should raise this as a feature request? The ability to associate an upload repository with a remote that a recipe has come from? something like:
```
{
 "remotes": [
  {
   "name": "myprivaterepo",
   "url": "https://myserver.com/myprivateremote",
   "source_upload_url": https://server.com/private-sources",
   "verify_ssl": true
  },
  {
   "name": "conancenter",
   "url": "https://center.conan.io/",
   "source_upload_url": "https://server.com/conan-center-sources",
   "verify_ssl": true
  }
 ]
}
```

**Comment by memsharded** [comment]
Lets discuss about this.

One possible idea would be, if we enable the possibility to pass the ``core`` configs in command line:
- To leave the upload_url conf not defined
- ``conan upload openssl/1.1.1t -r mypublicremote -c core.sources:upload_url=https://myserver.com/conan-center-sources``
- ``conan upload myprivatelib/x.y.z -r myprivateremote -c core.sources:upload_url=https://myserver.com/backup-sources``

Another idea is: if you are already retrieving things from your own private repos, use the ``exclude`` conf to exclude these repos to store an extra copy under your same org? The purpose of this ``exclude`` config is exactly to exclude your own origins of tarballs.

**Comment by samuel-emrys** [comment]
Yep thanks @memsharded using `core.sources:exclude_urls` is a good partial solution - it will get us up and running. It doesn't solve the case where we want to re-host sources from access-controlled servers in an access controlled repository though, so yeah in that case having the `core.sources:upload_url` conf able to pass from the CLI would satisfy my use case.

I don't think it's _quite_ as nice an interface as adding an optional `upload_url` field to each remote in `remotes.json`, but I can appreciate that implementation details mean it might be a quicker win given it's more consistent with the current design philosophy.

**Comment by memsharded** [comment]
Let's work on making it possible to pass ``core.xxx`` confs in command line

**Comment by AbrilRBS** [comment]
Closing this as solved with the proposed solution to use the `core.` conf (But we can think abotu other ways to solve it too)

Let's track the global CLI work in https://github.com/conan-io/conan/issues/13410 :)
