### ISSUE TITLE
[question] scons with conan 2.0

### ISSUE THREAD

**Issue by priyank31malhotra** [conan-io/conan#14717]
### What is your question?

Hi,
I have an issue regarding integrating scons with conan 2.0 and using it to integrate any open source package .
Can you guys help me out with this. A working demo project would be much appreciated.

Thanks, 
Priyank

**Comment by czoido** [comment]
Hi @priyank31malhotra,

I'm transferring this to the Conan repo, as it's not directly related with Conan Center Index and we have just started the work to bring basic SCons support for 2.X.
We have opened a [PR for 1.X](https://github.com/conan-io/conan/pull/14713) to add the SConsDeps generator, then we will bring that to 2.X.

**Comment by czoido** [comment]
Hi @priyank31malhotra,

We have ported the 1.x implementation to 2.0.11, that we will release very soon. We have a very basic functional test for scons in our test suite thay may help you: https://github.com/conan-io/conan/blob/release/2.0/conans/test/functional/toolchains/scons/test_sconsdeps.py
I consider this ticket closed as it will be merged in the next version, but please feel free to reopen o open other issues if you have any questions.
Thanks a lot!

**Comment by priyank31malhotra** [comment]
Hi Carlos,
Thanks for the help.
Just one more thing. How am I supposed to run this file with conan
2.0. Please mention the steps involved .

Thanks,
Priyank

**Comment by czoido** [comment]
Hi @priyank31malhotra,

I have created a basic example on how to use SCons in Conan to create and consume a package here: https://github.com/czoido/conan-scons-example
