### ISSUE TITLE
[bug] Failed to establish connection to conan center

### ISSUE THREAD

**Issue by dvhwgumby** [conan-io/conan#14714]
### Environment details

* Operating System+version: macos ventura 13.5.2
* Conan version: 2.0.10

### Steps to reproduce

All the sources have been downloaded to .conan2 already.  

I'm just doing `conan install -- build=missing` to set up a release build tree, after doing development with the Debug tree.

I get

    ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v2/conans/boost/1.83.0/_/_/revisions/8be129e9ab6e00b3d74810626cdbea9c/packages/a924576165115d00d209158cca5eb8ee2712a2f2/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10292ce50>: Failed to establish a new connection: [Errno 12] Cannot allocate memory'))

    Unable to connect to conancenter=https://center.conan.io
    1. Make sure the remote is reachable or,
    2. Disable it by using conan remote disable,
    Then try again.

This happens a lot.  I don't even know why conan need connect when the packages are already in the repository and the versions match what's in conanfile.txt

### Logs

````
======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=14
os=Macos
[options]
*/*:shared=True

Profile build:
[settings]
arch=armv8
compiler=apple-clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=14
os=Macos


======== Computing dependency graph ========
Graph root
    conanfile.txt: /Users/gumby/Dev/temp/examples2/tutorial/consuming_packages/simple_cmake_project/Externals/conanfile.txt
Requirements
    boost/1.83.0#8be129e9ab6e00b3d74810626cdbea9c - Cache
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
    cli11/2.3.2#1424b9b1d9e3682a7122f415b078b4d7 - Cache
    fmt/10.1.0#51d8d1db43672712db81b146a85ca73d - Cache
    jansson/2.14#42fc601d5b8e236e050e48f2321ef851 - Cache
    libbacktrace/cci.20210118#ec1aa63bbc10145c6a299e68e711670c - Cache
    libiconv/1.17#fa54397801cd96911a8294bc5fc76335 - Cache
    libuv/1.46.0#78565d142ac7102776256328a26cdf60 - Cache
    nlohmann_json/3.11.2#a35423bb6e1eb8f931423557e282c7ed - Cache
    openssl/3.1.2#ef79f25fe0968d69538feca6a6b3bc7f - Cache
    pcg-cpp/cci.20220409#b3c4e07c6ef6c2b5ddf2886f8a637bc7 - Cache
    spdlog/1.12.0#248c215bc5f0718402fbf1de126ef847 - Cache
    zlib/1.2.13#97d5730b529b4224045fe7090592d4c1 - Cache
Build requirements
    b2/4.9.6#53783bdbbdbb6c13732b25f1f6ea6c58 - Cache

======== Computing necessary packages ========
fmt/10.1.0: Checking 9 compatible configurations:
fmt/10.1.0: '100d4e9c0e2c29cdc23b123f7c4306837217bf92': compiler.cppstd=11
fmt/10.1.0: 'a66ef2900bed5b410a3f42fd0f8645e62dd9c70d': compiler.cppstd=gnu11
fmt/10.1.0: 'b9d3049f2fd934cb9748dffcfe90a014994b4af6': compiler.cppstd=14
fmt/10.1.0: '71c7be44000f1619ff2ecd50d3bbd509f005117b': compiler.cppstd=gnu14
fmt/10.1.0: 'bb687ef064cdd05120c2aee250b7e22ddbb1f6a4': compiler.cppstd=17
fmt/10.1.0: '4badcbd9a89ba34a8bdeef1579e4dcc0e921da13': compiler.cppstd=gnu17
fmt/10.1.0: 'd350b466e20804d3c38fafdaeda22289c31d0721': compiler.cppstd=gnu20
fmt/10.1.0: '13f9cc24b902c837127af7ad5e266ae9e6040530': compiler.cppstd=23
fmt/10.1.0: '3736fb12c406e8d5e9d658c738ee53c9f0af01e8': compiler.cppstd=gnu23
boost/1.83.0: Checking 9 compatible configurations:
boost/1.83.0: 'a924576165115d00d209158cca5eb8ee2712a2f2': compiler.cppstd=11
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v2/conans/boost/1.83.0/_/_/revisions/8be129e9ab6e00b3d74810626cdbea9c/packages/a924576165115d00d209158cca5eb8ee2712a2f2/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10292ce50>: Failed to establish a new connection: [Errno 12] Cannot allocate memory'))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
````

**Comment by dvhwgumby** [comment]
Is best practice to do `conan remote disable "*"` when all the packages I need are downloaded and just update it temporarily when I edit `conanfile.txt`?

**Comment by memsharded** [comment]
Hi @dvhwgumby 

Thanks for your report. We are checking things now, and everything seems to be working normally. We haven't had any recent incidents or outages in our logs that we can see. Maybe it could be some local network issue? corporate proxy/lan/vpn?

> This happens a lot. I don't even know why conan need connect when the packages are already in the repository and the versions match what's in conanfile.txt

When Conan finds a match in the local cache, it will use it, without connecting to the server at all.

What is happening here is the following:
```
fmt/10.1.0: Checking 9 compatible configurations:
fmt/10.1.0: '100d4e9c0e2c29cdc23b123f7c4306837217bf92': compiler.cppstd=11
...
```
That is, Conan is not finding a match for an fmt binary in ConanCenter, and then it is iterating looking for a compatible one (this take a while, this is a pending TODO, to optimize this a bit more). As it is not a perfect match, next ``conan install`` Conan will try to find a good match, and then it will look in the servers too.

There are different approaches for this depending on the needs:
- You can disable the ``compatibility.py`` plugin, that is iterating the different ``cppstd`` looking for a compatible one.
- You can define the exact match per-package in your profile, that is, something like ``fmt/*:compiler.cppstd=14``, even if your overall ``compiler.cppstd=17``, for example.

In any case, for production usage of packages from ConanCenter, please read the guide in: https://docs.conan.io/2/devops/using_conancenter.html. In short, to achieve more robust, faster and secure builds in production environments, using a copy of the packages might be the best choice. For example, Conan will not build all ``cppstd`` variants for all your dependencies. But you can perfectly build them with ``cppstd=20`` if that is what you are using, and store your own binaries in your own server, so no need to fallback to a compatible one built with ``cppstd=14`` (or other).

Please let me know if this helps.

**Comment by dvhwgumby** [comment]
Thank you for your informative and helpful message.  I'm still learning conan-fu.

With your response I can select what is best for us.
