### ISSUE TITLE
[question] Conan with Visual Studio

### ISSUE THREAD

**Issue by yekmen** [conan-io/conan#14725]
### What is your question?

I would like to make a Conan install of my Visual Studio solution. 
I tried to make the conan install from a powershell script which is launched when we start a build. The problem is, when I start Visual Studio with my solution, the script is automaticaly launched by Visual Studio and I don't know why ...

I create an project and add a custom build step which launch my powershell script before a CICompile.

I don't know if this is the good way or not.

Any help/suggest are welcome

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @yekmen 

This is interesting and something we would like to learn more, and even possibly add some documentation, guidelines or examples that could help other users.

What are you trying something like:
```xml
<Target Name="BeforeBuild">
  <TransformXml Source="Web.config" Transform="Web.$(Configuration).config" Destination="Web.config" /><!-- existing line, not part of answer -->
  <Exec Command="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -executionpolicy Unrestricted -command &quot;&amp; { .\MyScript.ps1 } &quot;" LogStandardErrorAsError="True" ContinueOnError="False" WorkingDirectory="$(MSBuildProjectDirectory)" />
</Target>
```
(from https://stackoverflow.com/questions/52433095/run-powershell-script-during-msbuild)
https://gist.github.com/fearthecowboy/9e06ad9d92c5d939582147a35c049693 also contains some interesting points

**Comment by memsharded** [comment]
Closing this ticket as staled, but please re-open or create new tickets for any further question you might have. Thanks for the feedback.
