### ISSUE TITLE
[question] Canonical way to define optional plugins for package info

### ISSUE THREAD

**Issue by MJacob-Lattice** [conan-io/conan#14730]
### What is your question?

Hi!

I am currently working on a conan (v2.0) recipe for OpenVino, and I am stuck with the following problem: OpenVino has a few plugins which can be optionally deployed (openvino_intel_cpu_plugin.dll, openvino_intel_gna_plugin.dll, etc.)

The issue I am hitting is: Since these aren't plugins and aren't linked anywhere, I am not finding a correct way to define the DLLs in a way where a consumer could choose which ones to copy over to his binary folder. 

Right now, my package info looks like this, but it has been unable to pickup the actual DLLs to copy over. Here are the relevant snippets I tried in my recipe file.

`
    components = {
        "gna": {
            "cmake_target_name": "gna",
        },
        "openvino_auto_batch_plugin": {
            "cmake_target_name": "openvino_auto_batch_plugin",
            "alias": "auto_batch_plugin"
        },
        "openvino_auto_plugin": {
            "cmake_target_name": "openvino_auto_plugin",
            "alias": "auto_plugin"
        },
        "openvino_gapi_preproc": {
            "cmake_target_name": "openvino_gapi_preproc",
            "alias": "gapi_preproc"
        },
        "openvino_hetero_plugin": {
            "cmake_target_name": "openvino_hetero_plugin",
            "alias": "hetero_plugin"
        },
        "openvino_intel_cpu_plugin": {
            "cmake_target_name": "openvino_intel_cpu_plugin",
            "alias": "intel_cpu_plugin"
        },
        "openvino_intel_gna_plugin": {
            "cmake_target_name": "openvino_intel_gna_plugin",
            "alias": "intel_gna_plugin"
        },
        "openvino_intel_gpu_plugin": {
            "cmake_target_name": "openvino_intel_gpu_plugin",
            "alias": "intel_gpu_plugin"
        },
        "openvino_ir_frontend": {
            "cmake_target_name": "openvino_ir_frontend",
            "alias": "ir_frontend"
        },
    }
...
    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "both")
        self.cpp_info.set_property("cmake_file_name", "openvino")
        self.cpp_info.set_property("cmake_target_name", "openvino::openvino")
        self.cpp_info.set_property("pkg_config_name", "openvino")
        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs.append("m")
        
        self.cpp_info.includedirs = ['runtime/include', 'runtime/3rdparty/tbb/include']  # Ordered list of include paths
        self.cpp_info.libdirs = ['runtime/lib/intel64/Release', 'runtime/3rdparty/tbb/lib', 'runtime/bin/intel64/Release']  # Directories where libraries can be found
        self.cpp_info.bindirs = ['runtime/bin/intel64/Release', 'runtime/3rdparty/tbb/bin']  # Directories where executables and shared libs can be found
        self.cpp_info.resdirs = ['runtime/bin/intel64/Release']  # Directories where executables and shared libs can be found
        self.cpp_info.libs = collect_libs(self)

        # We need to define some plugins components
        for pkgconfig_name, values in OpenVinoConan.components.items():
            cmake_target = f'{values["cmake_target_name"]}'
            self.cpp_info.components[pkgconfig_name].libdirs = ['runtime/bin/intel64/Release', 'runtime/3rdparty/tbb/bin']
            self.cpp_info.components[pkgconfig_name].bindirs = ['runtime/bin/intel64/Release', 'runtime/3rdparty/tbb/bin']
            self.cpp_info.components[pkgconfig_name].includedirs = ['runtime/include', 'runtime/3rdparty/tbb/include']  # Ordered list of include paths
            self.cpp_info.components[pkgconfig_name].set_property("cmake_target_name", cmake_target)
            self.cpp_info.components[cmake_target].libs = [cmake_target]
`

I am open to only supporting CMake as a build system generator if that helps anything.

Thank you in advance!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MJacob-Lattice 

Thanks for your question.

> Since these aren't plugins and aren't linked anywhere

Is this a typo? did you inted to say, "since these are plugins and aren't linked anywhere"?

> The issue I am hitting is: Since these aren't plugins and aren't linked anywhere, I am not finding a correct way to define the DLLs in a way where a consumer could choose which ones to copy over to his binary folder.

If I understood it correctly, then it seems that there is almost no need for modeling these as components or anything like that. That is only for libraries that really need to be propagated down for linkage. If these are exclusively for runtime, then the following could be a possible approach:

- Just define the plugins you have, in a property, like ``self.cpp_info.set_property("vino_plugins", ["path/plugin1.dll", ...])``
- The consumer side, in their ``generate()`` method can read this property, and copy the DLLs they want to the folders they want.

Is this the intended usage of those plugins?

**Comment by MJacob-Lattice** [comment]
Hi @memsharded , thank you for your quick response!

Your assumption about the type was right, I meant "since these are plugins and aren't linked anywhere"! 

I tried what you proposed and it really tackles 100% of the use case I was looking for! This is quick, convenient, and even allows the consumer of the package to specify which plugins they would like to use. I'll be closing this issue, thank you so much :)

**Comment by memsharded** [comment]
Happy to help! 🙂
