### ISSUE TITLE
[question] conan graph build-order gives unexpected output

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#14749]
### What is your question?

Hi,

I have a relationship between two projects `hello-world` and `hello-world-consumer`, where `hello-world-consumer` defines `"hello-world/[>=3.0.0 <4.0.0]"` as a dependency.

Now I have build `hello-world` against whatever version of `hello-world-consumer` which was satisfying the version range.
I will run `conan graph build-order --requires 'hello-world-consumer/[>=1.0.0 <2.0.0]' -pr:h armv8 -pr:b x86 -s build_type=Release`
which outputs 
```
hello-world/3.51.0#8826f9e3fb3700f9abaf71615d211c0e:98d7235ff4daff6152d9b9ede8ea7d525a2abc84 - Cache
hello-world-consumer/1.6.0#6b28d9df722e30ea054c48a5ecf33e64:13e62ddd9d496bbad22ac111fdcddefc86da3433 - Cache
```
, which is correct.

Afterwards I rebuild `hello-world` (not `hello-world-consumer`!) with a minor version change (3.52.0), then I rerun the `build-order` command shown above:
```
hello-world/3.52.0#8826f9e3fb3700f9abaf71615d211c0e:98d7235ff4daff6152d9b9ede8ea7d525a2abc84 - Cache
hello-world-consumer/1.6.0#6b28d9df722e30ea054c48a5ecf33e64:13e62ddd9d496bbad22ac111fdcddefc86da3433 - Cache
```
This looks wrong to me, I would expect to see "Build" or "Missing" instead of "Cache". Even if I introduce a change in the dependency graph e.g. by using an additional dependency in `hello-world`, this doesn't change.

I'm not setting `package_type` in my projects currently and `shared=True` is used in the profiles.

Which factors are driving the rebuild of consumers of a package?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by tbsuht** [comment]
I can notice a difference to my example I posted some time ago [here](https://github.com/conan-io/conan/issues/14505#issuecomment-1683488528).

There the depenceny is shown as:
```
$ conan list libc/1.0.0:*
Local Cache
  libc
    libc/1.0.0
      revisions
        9d81df2874e73b749ee0ae8a86d05ac9 (2023-09-15 12:04:19 UTC)
          packages
            4baba1ad2e6f595dbed8e1c75d75be8b0196724e
              info
                [...]
                requires
                  liba/1.0.Z
```

but in my current case it looks like

```
$ conan list hello-world-consumer/1.7.0:*
Local Cache
  hello-world-consumer
    hello-world-consumer/1.7.0
      revisions
        8965043c4dcc12ecd458639aea5f795d (2023-09-15 11:56:06 UTC)
          packages
            13e62ddd9d496bbad22ac111fdcddefc86da3433
              info
                [...]
                requires
                  hello-world/3.Y.Z
```

`3.Y.Z` vs `1.0.Z` although I'm using the same version range schema. Is that somehow related?

**Comment by memsharded** [comment]
Hi @tbsuht 

Thanks for your question.

> This looks wrong to me, I would expect to see "Build" or "Missing" instead of "Cache". Even if I introduce a change in the dependency graph e.g. by using an additional dependency in hello-world, this doesn't change.

> I'm not setting package_type in my projects currently and shared=True is used in the profiles.

This is probably the key. If you are seeing that your ``hello-world-consumer`` package has a relationship to ``hello-world`` in the form of ``hello-world/3.Y.Z``, it means exactly that, that new minor or patch versions of ``hello-world``, will not require re-building ``hello-world-consumer``.

The most common way to change this behavior is defining the package-types. If ``hello-world`` is a shared library and ``hello-world-consumer`` is another shared library or an application, seeing a minor version change should imply a re-building of the consumer. So the reasons is that the packages are not aware of their type. This can be solved by:
- Defining the ``option`` ``shared`` in both, and making sure it is equal to ``True``
- Adding explicitly the ``package_type`` definition

If none of those is specified, Conan 2.0 follows the legacy 1.X default behavior for unknown package type, that is "semver" mode, only requiring re-builds when the major version changes.

Alternatively you can configure the ``package_id`` modes, but I don't think that is the best approach in this case, and correctly modeling the package types would be better solution.

**Comment by tbsuht** [comment]
@memsharded I've now added the `shared` option, as this is a good idea anyway.

For the `package_type`: is there an additional benefit to add it? How to handle packages where an application and a library (providing the interface to the app) is contained?

**Comment by memsharded** [comment]
> For the package_type: is there an additional benefit to add it? How to handle packages where an application and a library (providing the interface to the app) is contained?

Yes, the ``package_type`` is very important on how the information is propagated in the graph. Either it being deduced from the ``shared`` option, or defined explicitly can affect from the generators to the ``package_id``.

The package type you want to give depends on the usage. If you want to use it as a ``tool_requires`` to use that application, then better the application type. If you pretend to use it as a library mostly, better the ``library`` type.

**Comment by tbsuht** [comment]
@memsharded Thanks!
