### ISSUE TITLE
[bug] Debug build tries to install as Release

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14757]
### Environment details

* Operating System+version: Windows 10 22H2
* Compiler+version: msvc193
* Conan version: 2.0.10
* Python version: 3.9.13

### Steps to reproduce

Hello,

I prepared this [example](https://github.com/Todiq/test_conan) to give a proper explanation. I am compiling using Visual Studio 2022.

I used this profile to install `zlib/1.2.13` in **shared** mode before trying to compile:
```txt
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

I then switched to this one, needing some more options:
```txt
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.version=193
os=Windows

[conf]
tools.build:skip_test=True
tools.env.virtualenv:powershell=True
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
```

I ran theses commands:
- `conan build -verror .\test_conan\Test\alpha\ --settings "&:build_type=Debug"`
- `cmake --install .\test_conan\Test\alpha\build --prefix Debug/`

How come it is looking for the **Release** version while I only compiled it in **Debug**? It works when I compile & install on Release on Windows and it works on both Release & Debug on Linux (with Ninja single config). Did I do something wrong? Please, find the log below.

Thanks in advance.

### Logs

```powershell
-- Install configuration: "Release"
-- Installing: D:/Documents/CAST/Debug/include/Alpha
-- Installing: D:/Documents/CAST/Debug/include/Alpha/alpha1_1
-- Installing: D:/Documents/CAST/Debug/include/Alpha/alpha1_1/alpha1_1.hpp
-- Up-to-date: D:/Documents/CAST/Debug/include/Alpha
-- Installing: D:/Documents/CAST/Debug/include/Alpha/alpha1_2
-- Installing: D:/Documents/CAST/Debug/include/Alpha/alpha1_2/alpha1_2.hpp
-- Up-to-date: D:/Documents/CAST/Debug/include/Alpha
-- Installing: D:/Documents/CAST/Debug/include/Alpha/alpha2
-- Installing: D:/Documents/CAST/Debug/include/Alpha/alpha2/alpha2.hpp
CMake Error at test_conan/Test/alpha/build/cmake_install.cmake:66 (file):
  file INSTALL cannot find
  "D:/Documents/CAST/test_conan/Test/alpha/build/alpha1/alpha1_1/Release/alpha1_1.dll":
  File exists.
```

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your question.
It seems you are missing the necessary ``--config Debug`` in multi-config setups.

```bash
$ cmake --install .\test_conan\Test\alpha\build --prefix Debug/ --config Debug
```

seems to work fine

**Comment by Todiq** [comment]
Hello @memsharded,

It indeed works fine this way. Thank you very much :)
