### ISSUE TITLE
[question] Problem with different revisions in Windows and Linux

### ISSUE THREAD

**Issue by jfang2807** [conan-io/conan#14761]
### What is your question?

In Conan 1.x, I could install Conan Linux packages on Windows simply by specifying the Linux profile. However, in Conan 2.0, I can't install Conan Linux packages on Windows machines anymore even though I specify the Linux profile. Is this cross-platform installation feature removed from Conan 2.0?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jfang2807 

Yes, this should be possible in Conan 2.0. Could you please detail what problems are you seeing, how this can be reproduced? Thanks.

**Comment by jfang2807** [comment]
First, I installed the Conan Windows package on a Windows machine

**PS> conan install  . -g MSBuildDeps -of .conan2 -pr Windows.Release -r cmru-conan-v2**

  ======== Input profiles ========
  Profile host:
  [settings]
  arch=x86_64
  build_type=Release
  compiler=msvc
  compiler.runtime=dynamic
  compiler.runtime_type=Release
  compiler.version=191
  os=Windows
  
  Profile build:
  [settings]
  arch=x86_64
  build_type=Release
  compiler=msvc
  compiler.runtime=dynamic
  compiler.runtime_type=Release
  compiler.version=191
  os=Windows
  
  
  ======== Computing dependency graph ========
  mypackage/1.10.0@3rd-party/release: Not found in local cache, looking in remotes...
  mypackage/1.10.0@3rd-party/release: Checking remote: cmru-conan-v2
  mypackage/1.10.0@3rd-party/release: Downloaded recipe revision abf482e1fb63c98c965a58573f0f606b
  Graph root
      conanfile.txt: C:\workspace\myproj\conanfile.txt
  Requirements
      mypackage/1.10.0@3rd-party/release#abf482e1fb63c98c965a58573f0f606b - Downloaded (cmru-conan-v2)
  
  ======== Computing necessary packages ========
  Requirements
      mypackage/1.10.0@3rd-party/release#abf482e1fb63c98c965a58573f0f606b:46779ffeb19cadd4fa5149c7aeafc3d6f6421280#005fcd953c2b511b6df7ccde8f818ae8 - Download (cmru-conan-v2)
  
  ======== Installing packages ========
  
  -------- Downloading 1 package --------
  mypackage/1.10.0@3rd-party/release: Retrieving package 46779ffeb19cadd4fa5149c7aeafc3d6f6421280 from remote 'cmru-conan-v2'
  mypackage/1.10.0@3rd-party/release: Package installed 46779ffeb19cadd4fa5149c7aeafc3d6f6421280
  mypackage/1.10.0@3rd-party/release: Downloaded package revision 005fcd953c2b511b6df7ccde8f818ae8
  
  ======== Finalizing install (deploy, generators) ========
  conanfile.txt: Writing generators to C:\workspace\myproj\.conan2
  conanfile.txt: Generator 'MSBuildDeps' calling 'generate()'
  conanfile.txt: Generating aggregated env files
  conanfile.txt: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
  Install finished successfully

*************************************************************************
Second, I tried to install a Conan Linux package on the Windows machine. I noticed that the Conan client used the **Windows build profile** from the command output below. In the end, the install failed to cite "Missing prebuilt package", 

**PS> conan install  . -g MSBuildDeps -of .conan2 -pr Linux.centos.Release -r cmru-conan-v2**

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=8
os=Linux
os.distribution=centos

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=191
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.txt: C:\workspace\myproj\conanfile.txt
Requirements
    mypackage/1.10.0@3rd-party/release#abf482e1fb63c98c965a58573f0f606b - Cache

======== Computing necessary packages ========
Requirements
    mypackage/1.10.0@3rd-party/release#abf482e1fb63c98c965a58573f0f606b:28e403f66bef174f529f1ca91c782acd664d072b - Missing

======== Installing packages ========
ERROR: Missing binary: mypackage/1.10.0@3rd-party/release:28e403f66bef174f529f1ca91c782acd664d072b

mypackage/1.10.0@3rd-party/release: WARN: Can't find a 'mypackage/1.10.0@3rd-party/release' package binary '28e403f66bef174f529f1ca91c782acd664d072b' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=8
os=Linux
os.distribution=centos

ERROR: Missing prebuilt package for 'mypackage/1.10.0@3rd-party/release'
Check the available packages using 'conan list mypackage/1.10.0@3rd-party/release:* -r=remote'
or try to build locally from sources using the '--build=mypackage/1.10.0@3rd-party/release' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'

*********************************************************************************************

**Comment by memsharded** [comment]
Thanks for the feedback.

This doesn't seem an issue that it cannot be installed, but that such specific binary is missing (non-existing) from your server.
If you type:
```
$ conan list mypackage/1.10.0@3rd-party/release:* -r=cmru-conan-v2
```
What do you get?


Side note, using ``-of .conan2`` is not great, because ``.conan2`` is the folder name of the Conan cache, and can be confusing. I'd suggest to use a different name for the output folder, like `.conan_deps` or something like that.

**Comment by jfang2807** [comment]
Thanks for the quick reply! I got more info on the issue

1. I have a Windows and a Linux package in the Conan registry on our Artifactory (see the attached screenshot). For some reason, they are placed in two different revisions.

![package-revisions](https://github.com/conan-io/conan/assets/52295278/58abdbd4-16c3-4556-bf3d-240b0953c384)

2. I cleaned the local cache on the Windows machine
PS> **remove-item .conan2/p/* -force -recurse**


3. This time, I installed the Linux package on a Windows machine first and it was installed successfully, which is nice to know it actually works.

PS> **conan install  . -g MSBuildDeps -of conan-deps -pr Linux.centos.Release -r cmru-conan-v2

======== Input profiles ========**
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=8
os=Linux
os.distribution=centos

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=191
os=Windows

======== Computing dependency graph ========
mypackage/1.10.0@3rd-party/release: Not found in local cache, looking in remotes...
mypackage/1.10.0@3rd-party/release: Checking remote: cmru-conan-v2
mypackage/1.10.0@3rd-party/release: Downloaded recipe revision 292744082e92b792ff74d941928f388f
Graph root
    conanfile.txt: C:\workspace\myproj\conanfile.txt
Requirements
    mypackage/1.10.0@3rd-party/release#292744082e92b792ff74d941928f388f - Downloaded (cmru-conan-v2)

======== Computing necessary packages ========
Requirements
    mypackage/1.10.0@3rd-party/release#292744082e92b792ff74d941928f388f:28e403f66bef174f529f1ca91c782acd664d072b#ce219a175548272266aa06d3b1731d7f - Download (cmru-conan-v2)

======== Installing packages ========

-------- Downloading 1 package --------
mypackage/1.10.0@3rd-party/release: Retrieving package 28e403f66bef174f529f1ca91c782acd664d072b from remote 'cmru-conan-v2'
mypackage/1.10.0@3rd-party/release: Package installed 28e403f66bef174f529f1ca91c782acd664d072b
mypackage/1.10.0@3rd-party/release: Downloaded package revision ce219a175548272266aa06d3b1731d7f

======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to C:\workspace\myproj\conan-deps
conanfile.txt: Generator 'MSBuildDeps' calling 'generate()'
conanfile.txt: Generating aggregated env files
conanfile.txt: Generated aggregated env files: ['conanbuild.bat', 'conanrun.sh']
Install finished successfully
********************************************************8


4. In the next step, I tried to install the Windows package on the same Windows machine but failed with the same "Missing binary" error. I noticed that the "conan install" command was trying to download the Windows package binary from the revision that the Linux package is in. Therefore failed.

**PS> conan install  . -g MSBuildDeps -of conan-deps -pr Windows.Release -r cmru-conan-v2**

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=191
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=191
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.txt: C:\workspace\myproj\conanfile.txt
Requirements
    mypackage/1.10.0@3rd-party/release#292744082e92b792ff74d941928f388f - Cache

======== Computing necessary packages ========
Requirements
    mypackage/1.10.0@3rd-party/release#292744082e92b792ff74d941928f388f:46779ffeb19cadd4fa5149c7aeafc3d6f6421280 - Missing

======== Installing packages ========
ERROR: Missing binary: mypackage/1.10.0@3rd-party/release:46779ffeb19cadd4fa5149c7aeafc3d6f6421280

mypackage/1.10.0@3rd-party/release: WARN: Can't find a 'mypackage/1.10.0@3rd-party/release' package binary '46779ffeb19cadd4fa5149c7aeafc3d6f6421280' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=191
os=Windows

ERROR: Missing prebuilt package for 'mypackage/1.10.0@3rd-party/release'
Check the available packages using 'conan list mypackage/1.10.0@3rd-party/release:* -r=remote'
or try to build locally from sources using the '--build=mypackage/1.10.0@3rd-party/release' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'

**Comment by memsharded** [comment]
Thanks for the feedback. That makes sense.
Having 2 different revisions for the same origin is to be avoided, is a logical error. 
The most typical cause is the CRLF differences in Windows, please check: https://docs.conan.io/2/knowledge/faq.html#error-obtaining-different-revisions-in-linux-and-windows

You can understand better what is the difference between the 2 revisions by downloading the ``export`` folder ``conanmanifest.txt`` files of both revisions, and comparing, it will tell you which files are different between the two.

**Comment by jfang2807** [comment]
@memsharded: Thank you so much for your help! What you described is exactly the root cause of my issue. Now I am able to fix it. Thanks again!

**Comment by memsharded** [comment]
That is great, happy that it is working now for you! 🙂 

Don't hesitate to open new tickets for any further question you might have. Cheers!
