### ISSUE TITLE
[question] Should defines follow the same rules as `transitive_headers` trait

### ISSUE THREAD

**Issue by lmglmg** [conan-io/conan#14763]
### What is your question?

I've encountered and issue where a define was transitivly propagated to the source file, but the header was not. I would just like to ask if this is an intended behavior or a bug.
The header was not not propagated to the source file bacause a dependency in between did not propagate the header of the package from which the define originated. The define was propagated because the dependency in between did propagate the define which caught me by surprise.

For example:

There is a package which defines a `PROTECT` define

```python
class ProtectionConan(ConanFile):
    def package_info(self):
        # ...
        self.cpp_info.components['protection'].defines = ['PROTECT']
```

There is a consumer of the package `protection` which does not tranistivly propagate headers of the package `protection`.

```python
class ConsumerConan(ConanFile):
    def requirements(self):
        self.requires('protection/[~2]@microblink/main')
```

The issue occurs in the test package of the `consumer` because of the following code:

```cpp
#ifdef PROTECT
#include <some-header-from-protection.hpp>
// Some protection specific code
#endif
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lmglmg 

Thanks for your question
I might be missing some info. If the headers are not transitive and thus not visible from the downstream consumer, why that consumer, in this case ``test_package`` contains an ``include`` to the headers, that will not be visible?

**Comment by lmglmg** [comment]
The final user might want to add different functionality to the program depending on the presence of  the `PROTECT` define. For example if the protection is not added, then there is no need for license checks. The protection could be omitted in tests and internal tools, but added in production code. In this example, the code depends on the `PROTECT` macro to switch between the functionalities, but the header path is not present.

**Comment by memsharded** [comment]
> The final user might want to add different functionality to the program depending on the presence of the PROTECT define. For example if the protection is not added, then there is no need for license checks. The protection could be omitted in tests and internal tools, but added in production code. In this example, the code depends on the PROTECT macro to switch between the functionalities, but the header path is not present.

Exactly, this is the point I am trying to clarify. There is functionality that could be enabled/disabled in the end consumer, just by linking with the ``protection`` library, even if the headers are not directly visible, they are still indirectly used and linked, and maybe as such, the PROTECT macro should be defined to enable these features on the consumer?

At the moment the logic is that as long the transitive dependency is either included or linked (or both), the ``defines`` are propagated.

**Comment by memsharded** [comment]
Closing as responded back then, but please re-open or create new tickets if necessary, thanks for the feedback.
