### ISSUE TITLE
Compare hash of recipe instead of timestamp

### ISSUE THREAD

**Issue by packadal** [conan-io/conan#1476]
When I build my packages with my CI server, some builds start at around the same time, but sometimes the one that started later finishes first (e.g. linux build is quicker than windows builds).

In this case, the conan package refuses to upload because ` Remote recipe is newer than local recipe`.

However this is not a useful error, if the recipes are the same (easy to check with a simple hash) I don't care which file was created first by the checkout.

**Comment by memsharded** [comment]
But that is definitely very weird. This is the code raising that error:
```python
if (remote_recipe_manifest != local_manifest and
                remote_recipe_manifest.time > local_manifest.time):
            raise ConanException("Remote recipe is newer than local recipe: "
```
As you can see, you should see that error only if the manifests changes (which is the hash of the recipe and the associated files). And if the manifest changes, it means that you are doing some local changes to the recipe, and then the system is protecting you to upload a modified recipe with a different date than the previous one.

You should check what your CI servers are doing differently. The most common issue would be cloning or checking out from git or other VCS with different CRLF in different OS. You can check your manifests, both  in the server and in the different CI machines, to check what is happening and why they are different. Please check them, or submit them so we can have a look. Thanks!

**Comment by packadal** [comment]
Oh thanks, that was probably the line ending messing with the hash.

Would it not be a good idea to trim the conanfile before hasing ?
Because the only other solution I see is to add a `.gitattributes` with a line like `conanfile.py -crlf`.

I feel conan could manage for me, don't you think ?

I'd be happy to write the patch if you think it can be integrated.

**Comment by memsharded** [comment]
It is not just the conanfile.py, but all the other files that are part of the recipe (exports, and exports_sources files) are also hashed. So it is a bit more complicated, because conan normalizing input could be error prone. What if some user wants some file with LF only? Or with CRLF? What if some file has no extension, but is a text file? A simple example, if you normalize all the text file to LF only, to be the same hash in all OS, then some editors might display included headers badly in Windows. Normalizing/trimming them on the fly might be also problematic, as you end with a manifest that doesn't match the real file.

I'd be happy if conan could help with this, but the truth is that we have considered this in the past, and thought it won't be safe for conan to do it.  I think you should be safe by just defining the same LF format for git, for all OS?

**Comment by packadal** [comment]
oh, I did not think that through.

Thanks for the answer, I'll try and add `gitattributes` then :)

**Comment by memsharded** [comment]
Ok, if you feel is not enough with gitattributes (or maybe gitconfig the ``autocrlf`` field?) please tell. Thanks!!

**Comment by packadal** [comment]
Hello again.

I have just finished testing intensively (deleting caches everywhere but on the server) anbd I have the issue, but the conanmanifest.txt has the same values as far as hashes are concerned.

here are the full conanfiles:

server-side file (from the server's `package/version/username/channel/export` folder)
```
1501163235
conanfile.py: 80d3083aaeca3f31e88a63387ecb6e88
test_package/CMakeLists.txt: 998de7c175ea2f7e1751a20a5e4bf458
test_package/conanfile.py: fd7572136afc6d5f45b7f55e1c8ad911
test_package/main.cpp: 59c21dbf969bef4d70333ab408343fd4

```

local file (from the build machine's conan `package/version/username/channel/export` folder)
```
1501165839
conanfile.py: 80d3083aaeca3f31e88a63387ecb6e88
test_package/CMakeLists.txt: 998de7c175ea2f7e1751a20a5e4bf458
test_package/conanfile.py: fd7572136afc6d5f45b7f55e1c8ad911
test_package/main.cpp: 59c21dbf969bef4d70333ab408343fd4
```

and the command `conan upload package/*user/%CONAN_CHANNEL% --all -c` fails with the message:
```
ERROR: Remote recipe is newer than local recipe: 
 Remote date: 1501060294
 Local date: 1499755975
```

**Comment by memsharded** [comment]
Honestly no idea :(

I have tried to replicate that, forcing that data in the server, and upload. Everything fine. The thing is that the code is doing first a comparison of checksums:

```python
  if (remote_recipe_manifest != local_manifest and
                remote_recipe_manifest.time > local_manifest.time):
            raise ConanException("Remote recipe is newer than local recipe: "
                                 "\n Remote date: %s\n Local date: %s" %
                                 (remote_recipe_manifest.time, local_manifest.time))
```

And the ``!=`` operator resolves to the comparison of checksums, but not the time.
You might provide relevant information by adding some "prints" to your conan source code. Either if you are running from source, or with an installed conan, you can locate the relevant sources:

- conans/client/uploader.py: Add a few prints that print the remote_recipe_manifest, the local_manifest, and the result of the comparison
- conans/model/manifest.py => method ``__eq__``. Print both arguments and the result too.

Then run your "upload" again and tell me the output. Thanks!

**Comment by packadal** [comment]
I finally had the time to work on this, and after upgrading to conan 0.25 I was still able to reproduce it.
However as soon as I added some `print` in the code, it got to working. No idea what happened there.

**Comment by memsharded** [comment]
You mean, a print in your package conanfile.py recipe? And if you add it back, the problem persists?
Still no idea, so if it happens again, please reopen. Thanks!

**Comment by packadal** [comment]
I mean I added a `print` in `conans/client/uploader.py`. Removed it, still works.

I'll re-open if it happens again, but I hope not.
