### ISSUE TITLE
Why does conan create tmp_config_install folder in cache?

### ISSUE THREAD

**Issue by Melkjot** [conan-io/conan#14778]
### What is your question?

Hi,

I would like to know, why conan creates `tmp_config_install` folder in cache?
The reason why I am asking this question is because of error that occurs in Jenkins pipeline when building projects.
`ERROR: Failed conan config install: Cannot change permissions for C:\***\.conan\tmp_config_install\test\ Exception info: (<class 'OSError'>, OSError(41, 'The directory is not empty'), <traceback object at 0x000001D1C788ED40>)`

My projects are so configured that `conan config install` is executed as a pre step and then the projects are built. When executing mentioned cmd, `tmp_config_install` is created in conan cache for a short time and then deleted. Conan settings are retrieved from `gerrit` repository. 
It seems that 'tmp_config_install' is locked/accessed by some other process and conan can not delete it. There are no concurrent jobs running.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Melkjot 

Thanks for your question.
The ``conan config install`` command is downloading or git-cloning some files, that have to be put somewhere. 
They were put in the cache for a few reasons:
- Sometimes they can contain some confidential information, so users were not happy it was put in some random ``tmp`` folders and for some reason not completely removed later. The ``.conan`` cache folder is more controlled by users.
- If something was failing, quick checking of what was downloaded could be useful.

I don't know why this would be failing, as you described, the folder exists while necessary, then if everything goes well, it is removed. If it is successfully removed, then it shouldn't be an issue later. Are you using some different user/permissions for ``conan config install``?

**Comment by Melkjot** [comment]
Hi @memsharded 

Thank you for your answer.
The `conan config install` command is executed always with same generic user. 
I will analyze it further and come back in case I have more questions.

**Comment by memsharded** [comment]
Seems this got staled back then.

Furthermore, Conan 2 has brought new features like the new ``conan config install-pkg`` that are quite convenient and has more features, that will not use this folder in the cache.

I am closing this ticket as staled, but please don't hesitate to re-open or create new tickets for any further question or issue you might have. Thanks for your feedback.

**Comment by MihaiPopescu1985** [comment]
There is a concurrency issue with this file.
If two commands are run on the same time, to install conan configuration by using the same location, one command will fail.
For example, if you set `CONAN_HOME` to be `C:\temp\.conan` in two terminals, and run the command `conan config install https://my.location/conan_configuration.zip` at the same time in both terminals, one terminal will throw the error: 
```
ERROR: Failed conan config install: Couldn't remove folder: C:\temp\.conan\tmp_config_install
[WinError 2] The system cannot find the file specified: 'C:\\temp\\.conan\\tmp_config_install'
Folder might be busy or open. Close any app using it and retry.
```

**Comment by memsharded** [comment]
Hi @MihaiPopescu1985 

Yes, this is known: https://docs.conan.io/2/knowledge/guidelines.html

> At the moment the Conan cache is not concurrent. Avoid any kind of concurrency or parallelism, for example different parallel CI jobs should use different caches (with CONAN_HOME env-var). This might change in the future and we will work on providing concurrency in the cache, but until then, use isolated caches for concurrent tasks.

We are starting some work to make the cache concurrent, but it will take time, it is a challenging thing.
