### ISSUE TITLE
[question]  declare layout when project is in sub directory

### ISSUE THREAD

**Issue by jasonbeach** [conan-io/conan#14783]
### What is your question?

I have a third party library I'm trying to make accessible via conan.  I have the sources in a zip file and I've been able to successfully download the file during the package creation process from the tutorial [here](https://docs.conan.io/2/examples/conanfile/layout/third_party_libraries.html) The rub and the problem is that the zip file contains multiple directories for different language bindings of which c++ is only one. So normally when I unzip the file, I would then move into the `cpp` folder which I can use as the toplevel project directory. 

If in the `layout()` method, I specify `self.folders.source="cpp"`, then the zip file gets unzipped into a `cpp` subfolder (and now the toplevel `CMakeLists.txt` is in `cpp/cpp`) so I still get an error. It almost seems like `self.folders.root` would be the answer, but the documentation says it's for specifying a parent directory (not a subdirectory) and when I set it to a sub-directory, it doesn't seem to have any affect that I can tell. 

So it seems I'm trying to do almost the opposite of the tutorial [here](https://docs.conan.io/2/examples/conanfile/layout/conanfile_in_subfolder.html#examples-conanfile-layout-conanfile-in-subfolder) (Declaring the layout when the conanfile is in a subfolder), I just can't quite figure out how to tell conan that. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jasonbeach 

Thanks for your question

I think for that case you want:
- The ``source`` folder is the root folder when your source is. If you are downloading like a zip with more files, it is that root folder with all files
- The build with the different helpers can locate the specific root for the C++ build. For example ``CMake`` helper can do:
```python
def build(self):
     cmake = CMake(self)
     cmake.configure(build_script_folder="cpp")
     ...
```

You are right, that the ``self.folders.root`` doesn't seem the solution for this, as it is for putting the ``conanfile.py`` in a subfolder, but not the same.

Please have a look to the above and let us know if it helps.

**Comment by jasonbeach** [comment]
that seems to have been the trick...thanks.
