### ISSUE TITLE
Test suite expects Visual Studio 12 2013 to be installed

### ISSUE THREAD

**Issue by torbjoernk** [conan-io/conan#1478]
Unless I'm mistaken, the unit test suite expects Visual Studio 12 to be installed on Windows.

Is there any way I can successfully run (at least) the CMake related tests on Windows with only Visual Studio 15 installed? Do I need to replace all occurrences of `settings.compiler.version = "12"` to be replaced by `settings.compiler.version = "15"` and `Visual Studio 12 2013` replaced by `Visual Studio 15 2017`?

**Comment by memsharded** [comment]
Do you mean, the conan codebase test suite? 
On Windows, I think you should be good with VS 14 and Mingw 4.9.
There might be some tests using version=12, but not actually building anything. But maybe I am wrong, could you please point out which tests are failing? If that is the case, maybe we should fix them, and require just 1 VS version to be installed (unless there is something that really deserves to be tested with older VS)

**Comment by torbjoernk** [comment]
Yes, I'm talking about the conan codebase test suite, i.e. the nosetests mentioned in the Readme of this repo here.

I have to admit, that I made a mistake by blindly running the tests within PyCharm without configuring the environment to something similar set by the VS 2017 command prompt. With that set, a couple additional tests pass.

Thank's for the hint with MinGW. I don't have that and will ignore tests related to that. Is there an attribute similar to `golang` or `slow` for those to exclude?

After replacing those occurrences of VS (12) 2013 or VS (14) 2015 with VS (15) 2017 a bunch more tests pass.

Should I provide a PR for that change?

**Comment by memsharded** [comment]
> Thank's for the hint with MinGW. I don't have that and will ignore tests related to that. Is there an attribute similar to golang or slow for those to exclude?

No, there is no such an attribute, but that is easy to add, and harmless for the test suite, so if you want to add it, go ahead.

Regarding the tests using VS12, if they are ``InstallSubfolderTest`` and ``InstallTest``, sure, those are no problem. If others are failing, please tell me first to check.

Regarding about the usage of VS 15 - 2017 as the default for testing, I am not sure. I think we should probably keep VS 14 - 2015 for a while, as it is still the more popular one.

**Comment by memsharded** [comment]
Lets try to fix this for next release, should be simple:
- Update only the failing test from VS 12 => VS 14, we will still assume that this is the default
- Label MinGW tests with the nosetests ``attr("mingw")`` for convenience

If you want to try yourself and need help, do not hesitate to ask. Otherwise, it is planned for next 0.27, we would do it. Many thanks!

**Comment by memsharded** [comment]
Hi @torbjoernk 

This has been fixed, now VS12 shouldn't be required, and you also have the "mingw" nosetests attribute (``nosetests . -A "not mingw"``). As this is a development feature, you can already try, running the tests from develop, please tell us if didn't work. Thanks!
