### ISSUE TITLE
[bug] tool_requires from profile does not apply for other tool requirements

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14791]
### Environment details

* Operating System+version: Ubuntu 23.04
* Compiler+version:
* Conan version: 2.0.11
* Python version: 3.11.4

### Steps to reproduce

I have a compiler packaged as a Conan package. It sets e.g. the compiler via its `conf_info` and the `tools.build:compiler_executables` setting. Usually, I "inject" the compiler package with a profile _toolchain-gcc10_ that just contains a `[tool_requires]` section. But now I ran into a problem when building e.g. ninja/1.11.1 from conancenter:

If I build it as `--tool-requires`, it fails because the conf variable is not used:
```
$ conan install -s build_type=Release --tool-requires ninja/1.11.1 -pr toolchain-gcc10 -pr default
...
ninja/1.11.1: Calling generate()
ninja/1.11.1: Generators folder: /home/fschoenm/.conan2/p/b/ninja275e5baa40ab3/b/build/Release/generators
ninja/1.11.1: tools.build:compiler_executables=None
...
```

If I build it as `--requires` (for testing), it seems to work:
```
$ conan install -s build_type=Release --requires ninja/1.11.1 -pr toolchain-gcc10 -pr default
...
ninja/1.11.1: Calling generate()
ninja/1.11.1: Generators folder: /home/fschoenm/.conan2/p/b/ninjaa797d00c3ab49/b/build/Release/generators
ninja/1.11.1: tools.build:compiler_executables={'asm': 'x86_64-linux-gnu-as', 'c': 'x86_64-linux-gnu-gcc', 'cpp': 'x86_64-linux-gnu-g++'}
...
```

If I change the conanfile.py of Ninja and manually add a `build_requirements()` method with a dependency to my package, it also works:
```
$ conan install -s build_type=Release --tool-requires ninja/1.11.1 -pr default
...
ninja/1.11.1: Calling generate()
ninja/1.11.1: Generators folder: /home/fschoenm/.conan2/p/b/ninja27401fb312558/b/build/Release/generators
ninja/1.11.1: tools.build:compiler_executables={'asm': 'x86_64-linux-gnu-as', 'c': 'x86_64-linux-gnu-gcc', 'cpp': 'x86_64-linux-gnu-g++'}
...
```

It seems to me that either I'm doing something wrong or adding tool requirements via profile to other build tools doesn't seem to work for some reason? Maybe you can help me out. Unfortunately, I wasn't able to create a small reproduction case because I don't really understand what goes wrong.

**Comment by memsharded** [comment]
Hi @fschoenm 

I think the issue is that:
```
$ conan install -s build_type=Release --tool-requires ninja/1.11.1 -pr toolchain-gcc10 -pr default
```
Is missing the information in the "build" context/profile. Only "host" profiles are being passed, that means that the "build" context will use just the "default" profile, that doesn't contain the information you want

It seems that you need to pass the ``-pr:b=profile`` information with the "build" profile. If you want to also use ``gcc10`` from your toolchain for the "build" profile you can define it there.
Note that it is not mandatory, and even not that typical to use the same toolchains in both contexts, you can be easily using the ``gcc10`` host profile cross compiling from Windows to some Linux or embedded system, but the "build" profile to build ninja in this case could be a ``msvc`` toolchain.

**Comment by fschoenm** [comment]
> It seems that you need to pass the -pr:b=profile information with the "build" profile. If you want to also use gcc10 from your toolchain for the "build" profile you can define it there.

@memsharded I'm not completely sure what you mean. This is how my profiles look, everything very straight forward because no crosscompilation is involved:
```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os.glibc=2.35
[tool_requires]
*: gcc/10.3.0@trs/stable
[conf]
tools.cmake.cmaketoolchain:generator=Ninja

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os.glibc=2.35
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

Does that look reasonable to you or what exactly is missing?

If I try to add the tool requirement to GCC in the build context, I the following error about a cycle in the graph:
```
ERROR: There is a cycle/loop in the graph:
    Initial ancestor: gcc/10.3.0@trs/stable
    Require: gcc/10.3.0@trs/stable
    Dependency: gcc/10.3.0@trs/stable
```

Maybe I'm still missing something about how profiles work but isn't the host context relevant for a package that needs to be build? I thought that the build context is only relevant for tool requirements, when they are executed.

**Comment by memsharded** [comment]
Injecting tool_requires in the "build" context can cause infinite recursion, if done with patterns like ``*``. Please try something like:

```
[tool_requires]
ninja*: gcc/10.3.0@trs/stable
```
Then I think that it is possible to have negations, like:
```
[tool_requires]
!mypkg/*:cmake/3.24
```
In case you want to try to apply the tool requires too all but itself.

**Comment by fschoenm** [comment]
@memsharded I think I understand now and I got it to work with your approach. Thanks :)

However, it has the disadvantage for me that now I need to specify `-pr:b toolchain-gcc10 -pr:b default` as build profiles. That's something I tried to prevent by always using a default build profile so that it looks nicer and easier for our developers. Maybe you have an idea but I'm not really sure how I could solve that so I will just assume that the build requirement are always prebuilt for our CI and our dev machines.

**Comment by memsharded** [comment]
> However, it has the disadvantage for me that now I need to specify -pr:b toolchain-gcc10 -pr:b default as build profiles. That's something I tried to prevent by always using a default build profile so that it looks nicer and easier for our developers.

For developer experience, you might try to define the default profiles you want to use with ``core:default_profile`` and ``core:default_build_profile`` in ``global.conf`` (which can also be a jinja template), and maybe using the ``include()`` profile directive instead of passing it to the command line removes the extra cli arg.

**Comment by fschoenm** [comment]
Good idea thanks. I'll think about doing it that way.
