### ISSUE TITLE
[feature] Explore ways to speedup compatibility checks

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#14799]
### What is your suggestion?

There's been internal discussion on how we could improve the time it takes to process the lookup of compatible packages. Opening this issue for treacability

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Lets start by fixing the order of resolution, looking first in the cache, to be able to work offline when compatibles are installed in the cache.

**Comment by memsharded** [comment]
Just realized we also have this ticket here https://github.com/conan-io/conan/issues/13820, which was older and submitted by a user, so closing this as duplicated and following up in the other one (also already assigned to 2.X milestone)
