### ISSUE TITLE
[question]How to config and link indirect dependence automatic in Conan2 with cmake

### ISSUE THREAD

**Issue by lxrui** [conan-io/conan#14790]
### What is your question?

I have a project `A` require a static lib `B`, and B require another static lib `C`, how can I link the indirect dependence  `C` automatic by `find_package(B)` or `target_link_libraries(A public B)`.
ps: use custom cmake script by cpp_info.set_property["cmake_build_modules"] seems possible, but I still want to know is there any other easier way

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lxrui 

This is all automatic, you don't need to do anything special:
- Make sure that your packages declare they are static either with the ``shared`` option or with ``package_type = "static-library"``
- In the consumer, use the ``CMakeDeps`` generator, do a normal ``find_package(B)`` and ``target_link_libraries(.... pkgb::pkgb)``, and that will bring linkage of C automatically

No need to use any custom ``cmake_build_modules`` for this

**Comment by memsharded** [comment]
Any further question here?
