### ISSUE TITLE
Case insensitive search seems broken

### ISSUE THREAD

**Issue by mikezackles** [conan-io/conan#1479]
(fresh install from AUR package)
```
$ conan --version
Conan version 0.24.0
$ conan search openssl -r=conan-center
There are no packages matching the openssl pattern
$ conan search OpenSSL -r=conan-center
Existing package recipes:

OpenSSL/1.0.2l@conan/stable
$ conan search openssl --case-sensitive -r=conan-center
There are no packages matching the openssl pattern
$ conan search OpenSSL --case-sensitive -r=conan-center
Existing package recipes:

OpenSSL/1.0.2l@conan/stable
```

**Comment by memsharded** [comment]
I am not sure... I think the ``case-sensitive`` option only applies to storage that is case-insensitive, like your local Windows conan cache. For other storages, that are case sensitive, as conan-center, this option is irrelevant.

**Comment by mikezackles** [comment]
Hmm, OK! FWIW it's a bit confusing as a new user.

**Comment by memsharded** [comment]
Yes, you are right, it should be more clearly stated in the docs, or at least in the command --help.

Maybe, we need to revisit this concept, not fully sure about its real utility. In either case, I am leaving this open to be improved, (either docs or some change in the UI) in next 0.26

**Comment by memsharded** [comment]
This is getting some command line help in #1874, but we will try to move to case-insensitive search by default in all remotes. This will take some time, so we cannot schedule this for a conan release.

**Comment by ArekPiekarz** [comment]
I would also be interested in this feature. Right now a user has to know beforehand how a given package is spelled case-sensitivity-wise in order to find it, try a bunch of combinations before giving up or use some website with index of packages.

**Comment by Talkless** [comment]
Any progress on this? It would really help usability, as this is currently confusing:
```
$ conan search openssl
Existing package recipes:

OpenSSL/1.0.2l@conan/stable
OpenSSL/1.0.2p@conan/stable
```
```
 conan search openssl -r=all
There are no packages matching the 'openssl' pattern
```

**Comment by antekone** [comment]
I have the same problem. Wanted to search for `openssl`, but only `OpenSSL` exists. At the same time, I also wanted to search for `HarfBuzz`, but only `harfbuzz` exists.

What is the point/rationale of using case sensitive search? What is the benefit over case insensitive search?

**Comment by kindlychung** [comment]
Case-sensitive search doesn't make sense at all. On the other hand, fuzzy search makes a lot of sense.

**Comment by kindlychung** [comment]
The command line search should give something similar to the results from the web ui (fuzzy search sorted on relevance):

![image](https://user-images.githubusercontent.com/995761/48198924-c23adf00-e35a-11e8-839c-eaa4a6554756.png)

**Comment by memsharded** [comment]
Conan 2.0 packages are all lowercase, so this won't be an issue anymore.
Also since the migration to the new ConanCenter (out of Bintray), packages are also lowercase in ConanCenter, so no longer an issue in ConanCenter too.
