### ISSUE TITLE
Packages should include licensing information

### ISSUE THREAD

**Issue by kreios4004** [conan-io/conan#148]
Some projects cannot operate with specific licenses and having that information would be significantly helpful. An added bonus would be to add restrictions on what licenses can be used/not used for a project. This feature would need to support libraries that have multiple licensing agreements (i.e. Qt with LGPL2 and LGPL3).

**Comment by memsharded** [comment]
As a initial step towards this functionality, current ``conan info`` command will show declared licenses (package authors should add the license attribute) for packages, so it can be easily checked. Probably the command can be shortened to --only-license or the like, to avoid the extra output. No active constraints are imposed when adding requirements to conanfiles, it can be complicated to deal with all kind of licenses and transitivity, but I think an useful information command could be enough at the moment. Have you tried it? What do you think?

**Comment by kreios4004** [comment]
I think that would be a great first step. I like that the package dependencies also get printed.

**Comment by memsharded** [comment]
Not sure if I understood, the command ``conan info`` is already available and working. You mean that "would be a great first step" the --only-license? Could you be a bit more precise? Have you tried to run the command? Thanks for your input!

**Comment by kreios4004** [comment]
Sorry, the --only-license would be great. It has already been a long day.
