### ISSUE TITLE
[feature] Apply profile to specific recipe

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14815]
### What is your suggestion?

Hello,

This feature would be more useful for Windows than for Unix-based systems. Let me give you an example.

`boost` with python (same for other packages) only compiles for me with the following profile:

```txt
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

I would like to compile my own packages using this one:
```txt
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.version=16
compiler.cppstd=23
compiler.runtime=dynamic
compiler.runtime_version=v143
os=Windows

[conf]
tools.build:skip_test=True
tools.cmake.cmaketoolchain:generator=Visual Studio 17
tools.env.virtualenv:powershell=True
```

However, whenever I try to run `conan build pkg/ --profile "clang"`, I get an error, telling me that the dependencies have not been compiled with this profile.

In fact, adding `--build=missing` results in some fails during the compilation. The only solution that remains is to manually pass all the settings and the conf to `pkg/` on the CLI, in order to only apply those to it and not to the dependencies, defeating the principle of having profiles in the first place.

Would it be possible to add the possibility to have `conan build pkg/ --profile "&:clang"`?

It makes sense to me, considering that both `settings` and `conf` have the same option. What do you reckon?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your suggestion.

You can already achieve this with a profile like:
```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows

&:compiler=clang
&:compiler.version=16
&:compiler.cppstd=23
&:compiler.runtime=dynamic
&:compiler.runtime_version=v143

[conf]
&:tools.build:skip_test=True
&:tools.cmake.cmaketoolchain:generator=Visual Studio 17
&:tools.env.virtualenv:powershell=True
```
If you want to put it in 2 profiles, you can define:
**deps_profile**:
```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows
```
**profile**:
```
[settings]
&:compiler=clang
&:compiler.version=16
&:compiler.cppstd=23
&:compiler.runtime=dynamic
&:compiler.runtime_version=v143

[conf]
&:tools.build:skip_test=True
&:tools.cmake.cmaketoolchain:generator=Visual Studio 17
&:tools.env.virtualenv:powershell=True
```
Then:
```
conan install ... -pr=deps_profile -pr=profile
```

the problem with the ``-pr=&:profile`` or similar syntax is that it is undefined, because the profile itself internally can contain other patterns, so this is not a possible approach. Please try the suggestions above.

**Comment by memsharded** [comment]
Alternatively, if you want to install just a subset with ``msvc`` and use ``clang`` for the rest, I'd recommend a ``jinja2`` template in the profile with a ``for`` loop that iterates over the dependencies you want, to define their ``pkg/*:setting=value`` pattern.

**Comment by Todiq** [comment]
Hello @memsharded,

Thank you for the proposed solution. My default profile remains:
```txt
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

My clang one is now the following (all my packages have the same pattern):
```txt
[settings]
cast*/*:compiler=clang
cast*/*:compiler.version=16
cast*/*:compiler.cppstd=23
cast*/*:compiler.runtime=dynamic
cast*/*:compiler.runtime_version=v143

[conf]
cast*/*:tools.build:skip_test=True
cast*/*:tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
```

However, it looks like my sources are built using cl instead of clang-cl:
```powershell
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
```

Any ideas about this? https://github.com/conan-io/conan/issues/14765

**Comment by memsharded** [comment]
Yes, I don't think this is a problem in the profile definition, but see https://github.com/conan-io/conan/issues/14765#issuecomment-1733381427, it could be some missing Clang configuration in the profile.
