### ISSUE TITLE
[question] How to determine package references created by conan create in conan2

### ISSUE THREAD

**Issue by dkumsh** [conan-io/conan#14817]
### What is your question?

Hi! 
With `conan [<2]` I use `conan create` command as described here:

https://github.com/conan-io/conan/issues/1985#issuecomment-426180214

.i.e. conan create command  generates  json file descrribing what has been done,
I parse that json file to extract package id and run package upload :
``` 
def do_upload(json,remote):
    for i in json['installed']:
        reference = i['recipe']['id']
        for package in i['packages']:
            if package['built']:
                package_id = package["id"]
                   command(f'conan upload {reference}:{package_id} -r {remote} --all -c ')
```
How can I do something similar with `conan2` ?

conan2  json file generated by `conan create` does not seem to be compatible and it does not seem to contain details on what has been built

 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @dkumsh 

Thanks for your question.
Conan 2.0 ``conan create --format=json`` contains all the necessary information to know what to upload.
Actually, Conan 2.0 has automated this task with the new "PackageLists" feature. No need of custom scripts from your side.

Please have a look to:
- https://blog.conan.io/2023/06/28/Conan-bulk-package-operations.html
- https://docs.conan.io/2/examples/commands/pkglists.html#building-and-uploading-packages

**Comment by dkumsh** [comment]
Thanks, that helps a lot!
