### ISSUE TITLE
[question] How should 'conan upload xyz' behave

### ISSUE THREAD

**Issue by NoWiseMan** [conan-io/conan#14821]
### What is your question?

We came across the following scenario.
(conan 2.0.11 / artifactory 7.68.11)

1. we upload a **correctly working** recipe to artifactory
2. we upload an incorrect recipe with _the identical version number_ to artifactory
3. after we found the issue, we revert the changes and try to upload the older recipe again with _the identical version number_
4. the upload was skipped by conan with `already in server, skipping upload`
5. but all consumer still get the defective recipe when we try to install the package with the option `--update`

We would expect that it is possible to overwrite the "last" recipe, or that the upload skip check only considers the last recipe version.
 

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @NoWiseMan thanks a lot, for your question:
While there's a discussion to be had about your comment/workflow, you can run `conan upload` with the `--force` flag to ensure the upload is always performed as a way to fix your current issue

Let me know if that helps :)

**Comment by NoWiseMan** [comment]
Sure this helps, I completely missed this flag
