### ISSUE TITLE
[question] About incremental builds & CMakeCache.txt

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14824]
### What is your question?

Hello,

Right now, if I build a project using cmake (Windows or Linux), a `CMakeCache.txt` is generated in `self.build_folder`.

If I try to rebuild by passing `--conf "&:tools.build:skip_test=False"` to force build the tests, nothing happens (it correctly builds incrementally the other changes not marked as tests, though).

However, if I delete the `CMakeCache.txt` before running that command, it succesfully builds the tests.

Is the expected behaviour from the creator to manually check the presence of the `CMakeCache.txt` in the `self.build_folder` and delete it if present? Or could a similar mechanism be applied on conan's side at build time to ensure that new cmake confs are properly taken into account? (BUILD_TESTING goes from FALSE to TRUE here). Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

This is the issue with build caching by CMake, and as you know, cache invalidation is one of the most challenging issues in SW engineer.

When doing local development, the main purpose is to have incremental (fast builds). Conan tries to have separate folders in the layout when it makes sense (different build-types), but it is impossible that Conan models every single change that could invalidate the CMake cache. There are many other parameters that alter Conan behavior but that might not require a removal of ``CMakeCache.txt`` and invalidating the CMake cache. So the only possibility is that this is the responsibility of the developer. If some Conan arguments are being changed, removal of the cache (typically removing the "build" folder is easier) is necessary. This can also happens for example when changing CMake generators, CMake will explicitly error and tell the user to clean the cache. But there are also other scenarios that require a CMake invalidation. The operation is so common that even IDEs like CLion contain Menu items to invalidate the CMake cache so it is convenient for developers.

**Comment by Todiq** [comment]
Seems clear to me. Thank you very much!
