### ISSUE TITLE
[feature] Conan cache could be more helpful about resolving packages from short references

### ISSUE THREAD

**Issue by antoinebardoz** [conan-io/conan#14828]
### What is your suggestion?

Very often, I'm interested in finding information about a package, to which I only have a "short" reference. I.e:
```
package_name/version@company
```

In these cases, Conan will either just give me information about the recipe, or say that it needs to know the package ID.

However, there is only one single package in existence which would match this particular reference, and Conan probably knows it. Why not have Conan then resolve this for me, instead of me having to jump through hoops to find the hash of the package_id?

I understand that if there is more than one package, Conan can't resolve it, but even in that case it would be _much more_ helpful if it listed which packages it found.

For example:
```
conan cache path package_name/version@company --folder=build
ERROR: '--folder build' requires a valid package reference
```

Could instead be:
```
conan cache path package_name/version@company --folder=build
/home/user/.conan2/p/packdf916cc80f201/b
```

Or, if more than one package_id matches this reference, in my cache:
```
conan cache path package_name/version@company --folder=build
ERROR: More than one package matches this reference. Need a package_id:
package_name/version@company#recipe_hash:package_id1
package_name/version@company#recipe_hash:package_id2
package_name/version@company#recipe_hash:package_id3
```

If this were implemented, I would also love to be able to specify ```--folder=package```. Then Conan would understand that I want the package path, and not the recipe path:
```
conan cache path package_name/version@company --folder=package
/home/user/.conan2/p/packdf916cc80f201/p
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Closing as commented in https://github.com/conan-io/conan/pull/14980, ``conan list *:* --format=compact`` gives a copyable reference to feed to ``conan cache path``, should be good enough for all use cases. Thanks very much for the feedback!

**Comment by RedX2501** [comment]
I'm commenting here as it is one of the first google results when searching for the error `ERROR: '--folder build' requires a valid package reference`.

With conan v2.8.1 there seems to be no usable output when using the provided command for a single package:

```
conan list "rb_bsw/*:*" --format=compact
Found 11 pkg/version recipes matching rb_bsw/* in local cache
Local Cache
  WARN: There are no matching recipe references
```

but I do know that it exists because I do use it in my `conanfile.py`.

Additionally:

```
$ conan cache path rb_bsw/testing-lso-0.1.100@ra7p/__
/home/buu2bue/.conan2/p/rb_bs1854dc5cf17a7/e
```
