### ISSUE TITLE
What is the working directory for imports section of conanfile.txt?

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#1483]
Under the `[imports]` section of my `conanfile.txt` I copy some dll's to the folder that I run my application from and some configurations to another folder.

    [imports]
    lib, *.dll -> ./bin
    config, *.cfg -> ./relative/path/to/my/configurations

My problem is that the paths specified in the `conanfile.txt` are relative to directory that I run the `conan install ...` command from and not relative to the `conanfile.txt`. Is there a way to change this behaviour? 

The build path and the path that conan is called from are not really important to me and they can change based on where the user is calling conan from. Having an environment variable like `CONAN_FILE_PATH` would be really nice.

**Comment by memsharded** [comment]
The reason why they are relative to the current directory, is the same why generated files (conanbuildinfo.cmake) and others are in the current directory: they are temporary files (you would typically not commit them to VCS) and they are specific for a configuration. So you will have just 1 conanfile.txt, but you can easily have two folders: debug and release and in each one you should have different imported files, retrieved from the debug and release dependencies respectively.

In http://conanio.readthedocs.io/en/latest/reference/conanfile/methods.html#imports you have an example of how to change its behavior with an env-var.

I will check anyway if something can be improved in the UI, we are right now improving it. Are you running it with the ``install`` command, or using the ``imports`` command? The ``conan install`` command is getting a ``--cwd`` argument to define its current directory, so all output files, generators and imported files will be relative to it.

**Comment by AliAskari** [comment]
I totally get the rationale behind your decision and I believe it is the right choice. The link you have provided is for `conanfile.py` and not for `.txt`. Is there a way to get/expand environment variables inside the `.txt` version? I prefer to stay with `conanfile.txt`. I am running it with `conan install`.

It would be nice to have the `--cwd` but I believe it would be much nicer if there was a way to expand environment variables within the `.txt` file. Adding a new flag requires the consumer to be aware of this flag, but if it is integrated within the recipe itself the consumer will always use the consistent `conan install .` command and it will be the responsibility of the package producer to take care of the internals. For `.py` recipes there is the `self.conanfile_directory` property, I am looking for the `.txt` version of this variable.

**Comment by memsharded** [comment]
Could you explain what are you thinking of? Something like:?

```
[imports]
lib, *.dll => %MYPATH%/mydlls
```
Which would be used as:
```
set MYPATH=C:/some/path
conan install .
```
rather than just?
```
conan install --cwd=C:/some/path
```
I think the first one is unnecesarily cluttering the environment, requires modification to the conanfile.txt...  not sure about this approach.

**Comment by AliAskari** [comment]
> I think the first one is unnecessarily cluttering the environment

I agree with you it is unnecessarily cluttering the environment and that's not what I want. I don't want the consumer of my packages to run any commands other than `conan install .`. 

This will be my preferred conanfile.txt: 

    [imports]
    lib, *.dll => %PATH_TO_CONANFILE%/mydlls

where `PATH_TO_CONANFILE` is a **private** and Conan only "environment variable". This variable is **only** known to the parser that parses conanfile.txt and it doesn't even have to be an environment variable. As I said it serves the exact purpose that `self.conanfile_directory` serves in conanfile.py. It is simply a private variable. 

> requires modification to the conanfile.txt... 

Of course, it requires modification to conafile.txt but I prefer to put the burden on the developer rather than the consumer.

**Comment by memsharded** [comment]
Conan 2.0 removes the ``imports`` approach in favor of new ``deployers``: https://docs.conan.io/en/2.0/index.html, this issue is no longer relevant
