### ISSUE TITLE
[bug] conan source failing with python_requires

### ISSUE THREAD

**Issue by docbrown1955** [conan-io/conan#14848]
### Environment details

* Operating System+version: Windows 11
* Conan version: 2.0.9 & 2.0.13
* Python version: 3.11.0

### Steps to reproduce

1. Use a "python_requires" in the recipe
2. Make sure the python requires recipe is **not** in the local cache, only on a remote
3. Call `conan source .`

By looking at the call stack, it seems no remote is ever defined from the `conan source` command, which explains why at the time the python requires is searching in remotes, it fails.

### Logs

```
 > conan source .
test_package/0.1.0: Not found in local cache, looking in remotes...
ERROR: Error loading conanfile at 'D:\workdir\test_package\conanfile.py': Cannot resolve python_requires 'recipe_utils/0.1.0': No remote defined
```

Call stack:
![image](https://github.com/conan-io/conan/assets/92524713/76394953-ab46-4f73-bbdb-02eed40ed6b9)
Looking at each steps from the very beginning (source method) the `remotes` variable is always empty.

**Comment by memsharded** [comment]
Hi @docbrown1955 

Thanks very much for reporting. Indeed there is a gap, and remotes were not passed. Adding them in https://github.com/conan-io/conan/pull/14852, proposed for next 2.0.14 release.

**Comment by docbrown1955** [comment]
Thanks a lot for the info, and the quick reaction!
