### ISSUE TITLE
[question] Why is special handling necessary for editable packages?

### ISSUE THREAD

**Issue by ohunter** [conan-io/conan#14842]
### What is your question?

First off I am using conan version 2.0.9

It is quite possible that I am doing this incorrectly but it seems to me that editable packages are treated differently to other packages. I have some packages with a source folder structure that is quite different from the one produced when the package is exported.
For instance, in one of them the headers are not kept in a folder called `include` but when packaged they are all copied the package's `include` folder. This is mainly because that package is a repackaging of someone else's sources. It means that I manually need to add the various include directories to `cpp_info` in the `package_info()` function where the best way I have found to detect whether this is an editable build is to do this `is_editable_build = self.package_path == self.export_sources_path` because both `self.source_path` and `self.build_path` are unavailable unless I go digging in the private variables of the `self.folders` member.
Another example is that I am creating a CMake object library which when packaged collects all the object files in the build tree and installs them to the `lib` folder in the package. To inform conan of all the objects I would normally just glob all the files in `self.package_path / 'lib'` but because `self.package_path` is the project path and there is no `lib` folder in the project (and even if it existed it wouldn't contain object files) it fails. Once again the solution is to detect whether it is an editable package and then alter the behavior based on that.

I had a suspicion that the package step isn't being called (which makes sense at first glance) which I checked by throwing a `breakpoint()` into the function. Based on my understanding of how conan works it seems like just calling `package()` and making sure that the `CMAKE_INSTALL_PREFIX` is set to something like `{project_root}/build/package`, `{project_root}/build/{build_type}/package` or maybe even `{project_root}/build/{build_type}` would solve it. That being said I am sure that there is a reason why such a simple solution hasn't been implemented, so why wouldn't it work?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ohunter 

Thanks for your question.
Indeed, implementing editable packages is a challenge. The more special the package is, the more challenging.

However, I am a bit confused, you don't even mention the ``layout()`` method, and focus on approaches trying to use only the ``package_info()`` method? The standard ``conan new cmake_lib -d name=mypkg -d version=0.1`` already implements a ``layout()`` method calling ``cmake_layout()`` that allows to simply call ``conan editable add .`` to put it in editable mode. You can create a chain of dependencies like ``conan new cmake_lib -d name=other -d version=0.1 -d requires=mypkg/0.1``, put it in editable mode and finally create a final consumer that requires ``other/0.1``, and play with it. The new ``--build=editable`` mode in Conan 2.0 should help with that.

This section of the docs contain some example: https://docs.conan.io/2/tutorial/developing_packages/editable_packages.html

Please let me know if this helps.

**Comment by ohunter** [comment]
It is quite possible that I've been doing this incorrectly. To answer your question, the `layout()` method for all the packages is implemented as `cmake_layout()`. Based on [this section](https://docs.conan.io/2/reference/conanfile/methods/layout.html#self-cpp) I could modify `self.cpp.build` as opposed to how I modify `self.cpp_info` now. It does seem like I stopped reading a bit too soon in my research into this as it is mentioned in the next section but I would also like to point out that this sentence is quite misleading:
> In this example, the `say` `conanfile.py` recipe is using the predefined `cmake_layout()` which defines the typical CMake project layout that can be different depending on the platform and generator used.

I will have to try it out tomorrow.

**Comment by memsharded** [comment]
Looking forward to hearing your feedback, many thanks!

**Comment by ohunter** [comment]
Ok, so `layout()` was definitely the right way to go about this but there are still some things that seem magical to me.
Given the object library example I mentioned at the start I essentially replaced the `cmake_layout(self)` with this:
```py
class Recipe(ConanFile):
    name="demo"
    version="0.1"
    ...
    def layout(self):
        object_extension = ".o" # TODO: Check that it is also .o for windows
        object_files = [file.with_suffix(f"{''.join(file.suffixes)}{object_extension}") for file in self._determine_compiled_sources()]

        self.folders.source = Path(__file__).parent # This is necessary because `Path()` will resolve to the path of the consuming package
        self.folders.build = Path(self.folders.source, "build", str(self.settings.build_type))
        self.folders.generators = Path(self.folders.build, "generators")

        self.cpp.package.includedirs = ["include"] # This is relative to `self.folders.package`
        self.cpp.package.libdirs = ["lib"] # This is relative to `self.folders.package`
        self.cpp.package.objects = [file.name for file in object_files] # All the files are moved to the same directory when packaged

        self.cpp.source.includedirs = ["include"]
        self.cpp.build.libdirs = ["."]
        self.cpp.build.objects = [Path("CMakeFiles", f"{self.name}.dir", "src", file) for file in object_files] # The files wont be moved to some other place like when packaged
```
and that worked as an editable package. However when I decided to try as a regular package I discovered that some step seems to be missing. Running `conan build .` works fine. If I try to run `conan export .` everything seems fine and the package exports as expected. If I then try to consume it in another package I get the error `CMake Error: The source directory "/home/olejeh/.conan2/p/demof7866e3c447b9/e" does not appear to contain CMakeLists.txt.`.

Another strange issue I ran into is if I run `conan export-pkg .` I get an error like this: `ninja: error: '/home/olejeh/.conan2/p/b/demo48f7edba8dc9/p/test.cpp.o', needed by 'main.elf', missing and no known rule to make it`. This does not happen when make is used as the cmake generator.

Neither of these problems occurred when the layout simply consisted of a `cmake_layout(self)` call and adding it to the start doesn't fix it either.

**Comment by ohunter** [comment]
Ok, so I figured out the second issue. I had assumed that `self.cpp.package.objects` was given the same treatment as `self.cpp_info.objects` in `package_info()` but that doesn't seem to be the case. When changed to `self.cpp.package.objects = [Path("lib", file.name) for file in object_files]` that seems to have resolved itself.

**Comment by memsharded** [comment]
Quick hints:

- ``self.folders.source = Path(__file__).parent`` doesn't seem correct because it will be an absolute path. Layout folders definition cannot be absolute paths, they must be relative, otherwise when in the cache, it will not work.
- Just in case: not all paths in Conan internals might be very happy receiving ``Path`` objects, because still the ``os.path`` is used in the codebase, not ``Path``. In case of issues, please try to us old-style paths.

For the first issue, if you have the ``conanfile`` in a subfolder of the repo, instead of having it in the root of the repo, then the approach is defining ``self.folders.root = ".."`` to define the starting point of the repo. But in any case, all paths in ``layout`` must be relative, starting from the root (either the conanfile folder, or the ``self.folders.root``)

Please let me know if that is your case, and the issue is that you have the ``conanfile`` in a subfolder instead of the root (it is recommended to have it in the root in the general case)

**Comment by ohunter** [comment]
Ok, so setting `self.folders.source = "."` seems to have resolved the issue. Everything else could stay the same.
