### ISSUE TITLE
Version wildcards not working

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#1485]
Searching for packages where part of the version is unknown works well:

    $ conan search 'zlib/1*@lasote/stable'
    Existing package recipes:

    zlib/1.2.8@lasote/stable
    zlib/1.2.11@lasote/stable

However using a wildcard for the whole version doesn't find any packages:

    $ conan search 'zlib/*@lasote/stable'
    There are no packages for pattern 'zlib/*@lasote/stable'

**Comment by memsharded** [comment]
The search ``conan search -r conan-transit zlib/*@lasote/stable`` seems to take a very long time

Workaround, add trailing *:
```bash
$ conan search -r conan-transit zlib/*@lasote/stable*
```
