### ISSUE TITLE
[package] pcre2/10.42: Recipe becomes corrupted on upload

### ISSUE THREAD

**Issue by bryce-cahill** [conan-io/conan#14856]
### Description

I've run into a very strange issue today that I can only seem to recreate with the pcre2 package. When building the package locally and uploading to artifactory everything appears to work as expected. However, when trying to download the package the conanfile.py is full of null characters which causes any projects that depend on this package to fail.

When looking at the local cache I can see the conanfile.py as expected and it is 9.8kb, the uploaded file on artifactory is shown as 9.71kb and when downloaded locally and opened with vscode it appears as 9947 null characters.

Tested at latest master: 1ede4d191660c9fcc0b7848744a8bcfb14cff626

### Package and Environment Details

* Package Name/Version: **pcre2/10.42**
* Operating System+version: **Linux Ubuntu 20**
* Compiler+version: **GCC 9.4.0**
* Conan version: **conan 2.0.9**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

### Steps to reproduce

(occurs without user tag as well)

conan create recipes/pcre2/all/ --version=10.42 --build=missing --user=mytag
conan upload pcre2/10.42@mytag -r=myrepo

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: Package 'pcre2/10.42@mytag' not resolved: pcre2/10.42@mytag: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/pcre27a0e904deed09/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/pcre27a0e904deed09/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
```

</details>

**Comment by bryce-cahill** [comment]
This appears to be caused by the version range added in: https://github.com/conan-io/conan-center-index/pull/19668

@SpaceIm @RubenRBS Any idea why adding the version range here causes the conanfile.py to become corrupted? This seems to be easily recreated by building with `--build='*'` and uploading to artifactory.

**Comment by AbrilRBS** [comment]
Hi @bryce-cahill, I'm moving this to the main Conan repository just in case it's a real issue with Conan instead of recipe-specific, will get back to you on Monday, thanks a lot for your patience :)

**Comment by AbrilRBS** [comment]
@bryce-cahill we haven't been able to reproduce this issue locally, so it's a bit confusing now. What Artifactory version are you using?

Can you try one thing for me?
- First update Conan, _just in case_
- Now export the env var `CONAN_HOME` to an empty directory and try again, does the error keep showing?

**Comment by bryce-cahill** [comment]
Morning @RubenRBS,

I've done a bit more testing and I'm still able to recreate this consistently:
- Tried with both Conan 2.0.9 and 2.0.13
- Built with a clean conan directory every time

We are currently running Artifactory 7.68.11, interestingly an issue has appeared in the last couple of days where a small number of non-conan uploads have also become corrupted although this currently appears to happen randomly. Strangely, if I revert the changes made in https://github.com/conan-io/conan-center-index/pull/19668 the recipe uploads fine and there is no corruption. Currently discussing with Devops and will update if there are any findings on the artifactory side.

**Comment by memsharded** [comment]
As this seems a bit difficult to reproduce on our side, I would recommend the following steps:

- Run a local ArtifactoryCE in the same failing machine, and upload the package to that Artifactory, instead to the other one, and check. That might rule out the client cause
- If you are using Artifactory in your own infrastructure, if you have any kind of middleware, proxy, vpn or something that could be causing some glitches, that could be something to consider.

**Comment by bryce-cahill** [comment]
Thanks for the feedback, closing this now as we appear to have been able to resolve this on our end.

Some extra context that hopefully helps in case someone else runs into this in the future. Our previous version of Artifactory had uploaded a corrupt version of the recipe to S3. However, this corrupt version remained in S3 after removing the recipe via Artifactory. This means that any subsequent uploads of the same recipe would point to this corrupt version.

Updating Artifactory, manually removing the corrupt version from S3 and then rerunning Conan upload has resolved the issue.

**Comment by memsharded** [comment]
Ok, thanks very much for following up and the feedback @bryce-cahill 

So it seemed like an unfortunate alignment of an older Artifactory version, using S3 as storage, some old corrupted package not being updated, likely a limitation or issue of the S3 backend. That would explain why we weren't able to reproduce.
