### ISSUE TITLE
[question] Creating an empty package on certain conditions

### ISSUE THREAD

**Issue by Naasha** [conan-io/conan#14866]
### What is your question?

Hello, i'm facing an issue where depending on the OS version my project needs to depend on different version of another package, and in some cases there is no required package. To handle this i'm trying to create "meta" package that will gather this logic.

So my dependencies looks like this:

```
Project
=> requires:  meta_vscode/1.0.0
   meta_vscode/1.0.0
       case "win 10" => requires vscode/[>=1.82]
       case "win 7" => requires vscode/1.81.1
       case "WS2008" => <no requirements>
```

When I perform the conan install for meta_vscode/1.0.0 on win 10 and 7 it works fine, but when i'm installing it on WS2008 I get the following error : ERROR: Missing prebuilt package for 'tool_meta_vscode/1.0.0'

So is there a better way to handle this problem ? (I'de like to avoid putting the "switch case" logic in my project dependencies directly)

Thanks for the help.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Naasha 

Thanks for your question.
If you have such a "meta" proxy recipe, it is likely that this will be empty, no actual binaries. It would be good to see a complete ``conanfile.py`` to understand the implementation, maybe you didn't remove the ``settings``?


> So is there a better way to handle this problem ? (I'de like to avoid putting the "switch case" logic in my project dependencies directly)

There are other ways to not repeat recipe logic, instead of creating "meta" packages that basically only contain python logic, like that switch. It is ``python_requires``, and it is a good way to reuse other functionality among multiple recipes.

**Comment by Naasha** [comment]
Hello, thx for the insight.
What do you mean by "removing" the settings ?
I'll also have a look to `python_requires` in the documentation because i've never used that indeed.

Here is the complete conanfile.py of my "meta" package:

```
import platform
from conans import ConanFile

class ToolMetaVsCode(ConanFile):
    name = "tool_meta_vscode"
    description = "Meta package for VSCode version dependency management according to system version"

    def requirements(self):
        system_name = platform.system()
        system_release = platform.release()
        
        if system_name.lower() == "windows":
            if system_release == "10":
                self.requires("tool_vscode/[>=1.82 <2]@fms200/release", override=True)
            elif system_release == "7":
                self.requires("tool_vscode/1.81.1@fms200/release")
            else:
                self.output.info(f"No VSCode version is applicable for {system_name} - {system_release}. Package is SKIPPED.")
        else:
            self.output.warn(f"No VSCode version is applicable for {system_name} OS yet. Package is SKIPPED.")
```

**Comment by memsharded** [comment]
> What do you mean by "removing" the settings ?

Recipes can declare ``settings = "os", "arch"....`` to use that information for building and taking decissions. If that is the case, but the final binary is intended to be empty, then ``self.info.clear()`` in the ``package_id()`` method will remove then and guarantee there will only be 1 package_id. 

But it happens that package_id also depends on the versions of the dependencies. So if your recipe doesn't have binaries adding:
```python
def package_id(self):
     self.info.clear()
```
Is recommended.


Some extra hints:
- In general, conditioning on system checks like ``system_name = platform.system()`` are not recommended. Instead using ``if self.settings.os == "Windows"`` is recommended. This approach allows to compute full dependency graphs even when you are not in that platform, for example from a Linux server running some CI tasks, it can still compute the necessary dependency graph from Linux.
- If something is a tool, like contains executables to be used at build-time, the recommended is ``self.tool_requires()``.

**Comment by Naasha** [comment]
Thank you for you help.
```
def package_id(self):
     self.info.clear()
```
worked fine, and i've learn something with the `python_requires` mechanism.
