### ISSUE TITLE
[question] Build info for rebuilt packages

### ISSUE THREAD

**Issue by hdnn** [conan-io/conan#14867]
### What is your question?

Hi!
Our company uses `Artifactory` with XRay.
I need to build multiple packages on our internal build server to have additional configurations(x86 for example). I do this with lock files. But before I upload the package `pkg/xxx@my_company/stable` I have to generate a `build_info` file for `Artifactory`. For this I use the `conan_build_info` tool.
After running  `conan_build_info --v2 start` and `conan_build_info --v2 stop` commands I see a `build_info.json` which contains only references to recipe files(`conanfile.py`, `conanmanifest.txt`, etc), but does not contain any information about the source files or binaries. 
XRay works with this information and shows License\Security problems if they exist. As I can imagine, XRay does it by simply extracting the name and version of the library and checking it against NVD.

The problem is that our "Application security" team have blocked such workflow, with the reason:

> You cannot add a variation of a public package, without a trace to the original package. The missing trace, expose your new variation to vulnerabilities we cannot detect.

But my understanding is that the rebuilt package is independent of the "origin" (which is stored in conancenter) and cannot have a reference to it in `build_info.json`, because it's just a copy of recipe files. But they both depend on a library source code and as I understand from this article [Conan and C/C++ Support in Xray](https://jfrog.com/help/r/jfrog-artifactory-documentation/conan-and-c/c-support-in-xray), **modules** section should enumerate every source file. Am I right? In that case security guys will see that we haven't injected vulnerabilities into original sources, I hope)

To summarize, pls help me with questions:
1) Am I right, that it's architecturally impossible to mention origin package in build_info of our variation?
2) Should build_info enumerate source files in `dependencies` section? 
2.1) If not, then how to be sure that our rebuild doesn't contain any extra changes?
2.2) If yes, then should I do it by `jq` tool via external script or `conan_build_info` is able to do and I just missed something?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hdnn 

Thanks for your question:

> Am I right, that it's architecturally impossible to mention origin package in build_info of our variation?

Yes, it is true, because it is not an origin package. You are building a replacement for it, and the common part is the name+version. You can most likely trace the origin to the ``conan-center-index`` original recipe, by capturing the git commit or something that is used to build your package in the package itself (can be done in the ``export()`` method for example, and stored in the ``conandata.yml`` file. But the ConanCenter package is not an origin at all about this, your package is not based on it, it doesn't use its artifacts binaries at all. The only common part is the recipe from conan-center-index repo.

> Should build_info enumerate source files in dependencies section?

The build-info creating has been fully re-vamped for Conan 2.0, trying also to overcome some of the limitations of the previous build-info. You can find it in https://github.com/conan-io/conan-extensions/blob/main/extensions/commands/art/readme_build_info.md. Maybe @czoido can help and clarify if the new build_info enumerate "source" files in dependencies? Could you please clarify what you mean with "source" files are those listing the package artifacts?

**Comment by czoido** [comment]
Hi @hdnn,
Thanks for the question. Currently the BuildInfo format would not accept some list of source files for the package. The files that are listed in the BuildInfo as artifacts are the files for the recipe and manifest and also the compressed files that have the sources that are exported within the recipe and the binaries. Something like this:

```
{
    "version": "1.0.1",
    "name": "build_release",
    "number": "1",
    "agent": {},
    "started": "2023-10-03T15:28:08.888+0200",
    "buildAgent": {
        "name": "conan",
        "version": "2.0.13"
    },
    "modules": [
        {
            "type": "conan",
            "id": "mypkg/1.0#4d50d4f4c4425c5f537f35083e830eeb",
            "artifacts": [
                {
                    "type": "py",
                    "sha256": "a93272f2f9c03cda49e69f3b7a74cc0d8dffd8e577d651a80c0dd0245dafbc89",
                    "sha1": "269291e73224efd0e9b8e236467c4ebdc550d7c3",
                    "md5": "9b9dfaaec46f6ed266c4c4e98ea1da96",
                    "name": "conanfile.py",
                    "path": "myrepo/_/mypkg/1.0/_/4d50d4f4c4425c5f537f35083e830eeb/export/conanfile.py"
                },
                {
                    "type": "tgz",
                    "sha256": "556e27d6404f629ba2556c3b8e9b14f6b60190db3644060768687ffc168260c1",
                    "sha1": "67a493dc10d3e7d317c71da8daac38390cc51f86",
                    "md5": "2eb7549205cef90d8ea147bc0bb4e42b",
                    "name": "conan_sources.tgz",
                    "path": "myrepo/_/mypkg/1.0/_/4d50d4f4c4425c5f537f35083e830eeb/export/conan_sources.tgz"
                },
                {
                    "type": "txt",
                    "sha256": "2e49b8e6640925009e4f889340f5ee10e54207b5ae56f37333f3119cecaec321",
                    "sha1": "a782a1e80362b5376258f82e6ab333d611321cbf",
                    "md5": "bd15b8808f7dae3f04bdfc99fbf5063d",
                    "name": "conanmanifest.txt",
                    "path": "myrepo/_/mypkg/1.0/_/4d50d4f4c4425c5f537f35083e830eeb/export/conanmanifest.txt"
                }
            ]
        },
        {
            "type": "conan",
            "id": "mypkg/1.0#4d50d4f4c4425c5f537f35083e830eeb:015c501fa3ba2da21e4c2e71becb7b76fa605a36#c10a24d864fce0fa74bafa72c59699f3",
            "artifacts": [
                {
                    "type": "tgz",
                    "sha256": "df498c988d8f24613e2a929f15b5b72a5bc9aa2ad92dcddbf0ae2b1a45eed344",
                    "sha1": "11de950dc912b7ecdc93fef86af7569cc73dba28",
                    "md5": "cff18b8c0ea529969951509203945feb",
                    "name": "conan_package.tgz",
                    "path": "myrepo/_/mypkg/1.0/_/4d50d4f4c4425c5f537f35083e830eeb/package/015c501fa3ba2da21e4c2e71becb7b76fa605a36/c10a24d864fce0fa74bafa72c59699f3/conan_package.tgz"
                },
                {
                    "type": "txt",
                    "sha256": "a25f7c7bd30da42683dec8da48757f5361d7a061ae8d637a9be0efd893698ac3",
                    "sha1": "a29e2a0363c91eac1faca09bedb71f5d6f8d54ad",
                    "md5": "aac93a9f5ea0f47a12886d2805ca787f",
                    "name": "conanmanifest.txt",
                    "path": "myrepo/_/mypkg/1.0/_/4d50d4f4c4425c5f537f35083e830eeb/package/015c501fa3ba2da21e4c2e71becb7b76fa605a36/c10a24d864fce0fa74bafa72c59699f3/conanmanifest.txt"
                },
                {
                    "type": "txt",
                    "sha256": "3f9dc6726eef2bc698c1a03218b5c41417523ea786ccccbc7c198bc1679cc649",
                    "sha1": "015c501fa3ba2da21e4c2e71becb7b76fa605a36",
                    "md5": "0cfd40b702c1c14cb4e11221e5d4fa4a",
                    "name": "conaninfo.txt",
                    "path": "myrepo/_/mypkg/1.0/_/4d50d4f4c4425c5f537f35083e830eeb/package/015c501fa3ba2da21e4c2e71becb7b76fa605a36/c10a24d864fce0fa74bafa72c59699f3/conaninfo.txt"
                }
            ]
        }
    ]
}

```

Those artifacts and dependencies are files that are stored in Artifactory as they appear in the BuildInfo, so adding more information than that in the BuildInfo, like a list of source files maybe could cause problems in Artifactory when interpreting the BuildInfo file.

**Comment by hdnn** [comment]
Thank you for answers!

@memsharded 

> something that is used to build your package in the package itself

Package name+version without user/channel, for example). But from by perspective it's just a hack, which doesn't make any profs that I haven't modified original package.

And I thought, that a library source files is the only one real dependency parent for origin and rebuilt package and referencing to it in `dependencies` section with hashes will give the Security team some profs. That's why I asked about enumeration. I don't really know how it should be, but in my head it sounds logically)

By "source" I mean `.cpp` files **or** an archive file with them, which recipe downloads.

@czoido,

> Those artifacts and dependencies are files that are stored in Artifactory as they appear in the BuildInfo

This is a good highlight for me, thank you! Honestly, all libraries sources I already download via artifactory(I have modified every link in conandata.yml), so it cached and presented in Artifactory. 
But in general, is it a viable idea to modify `build_info.json` with additional dependency information during the CI process?

**Comment by czoido** [comment]
> This is a good highlight for me, thank you! Honestly, all libraries sources I already download via artifactory(I have modified every link in conandata.yml), so it cached and presented in Artifactory. But in general, is it a viable idea to modify `build_info.json` with additional dependency information during the CI process?

Hi @hdnn,

Honestly, I don't think it's a good idea to modify the BuildInfo in the CI process, you could end up with a BuildInfo that's not interpreted correctly by Artifactory and cause another problem (maybe you can try to contact Artifactory support about this, they may give you some hints).
Maybe if you provide more detailed information about your workflow we could suggest some solution. Would that be possible?
Thanks a lot

P.S: As you mentioned that you have your sources in Artifactory, maybe the sources backup feature in Conan 2.0 could be of your interest. We have just published a blogpost about the feature: https://blog.conan.io/2023/10/03/backup-sources-feature.html

**Comment by hdnn** [comment]
Hi @czoido , sorry for delay. All this time a have been trying to solve the issue by my own. And finally, after long discussion our Security leader said "seems like I was mistaken" and unblocked our project and approved the workflow.
At that time I have realized that XRay is pretty stupid tool - it just take licence name from a recipe file, lib name and version from package name and use it make request to some DB with list of vulnerabilities. So, if I rename paridjson to glog in recipe, create and upload package -> Xray will show info like it's glog, while package binaries still rapidjson. I thought Xray scan artifacts like antivirus, but it isn't.
Thank you for your time!
