### ISSUE TITLE
[feature] add gcc 11.4 to settings

### ISSUE THREAD

**Issue by SimplyLiz** [conan-io/conan#14864]
### What is your suggestion?

On Ubuntu 22.04, the default version of gcc is 11.4. 
But this is missing in the latest conan 1.x (1.61.0) settings.yml 
Highest supported version is 11.3 

Please add it.

Also, what's the best way to add it manually? is there a conan command for it, or do i have to change the settings.yml and roll it out to all my build agents?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @SimplyLiz thanks a lot for your request - I've now submitted a new PR for Conan 1 to allow for the missing gcc versions to be released in 1.62

Note that as time goes on and Conan 1 gets progressively phased out in favour of Conan 2, there will be a longer and longer time in between such releases, answering your question of:

> Also, what's the best way to add it manually? is there a conan command for it, or do i have to change the settings.yml and roll it out to all my build agents?

The best recommended way is to maintain your copy of a modified settings.yml file yes, and maybe use something like [conan config install](https://docs.conan.io/en/1.61/reference/commands/consumer/config.html#conan-config-install) to deploy it to your agents

Once you're ready to move over to Conan v2, there's the [settings_user.yml ](https://docs.conan.io/2.0/examples/config_files/settings/settings_user.html?highlight=settings_user) feature to allow customization of the settings without risk of overwriting on an update :)

**Comment by AbrilRBS** [comment]
Closed in https://github.com/conan-io/conan/pull/14865 to be released in 1.62
