### ISSUE TITLE
[question] Upload the same package with different package id

### ISSUE THREAD

**Issue by igorquest** [conan-io/conan#14862]
### What is your question?

We have two development teams, one is using semver_direct_mode and the other full_package_mode. Rather than rebuilding the whole package, is it possible to download the package created by one team and re-upload the same binaries for the other team?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @igorquest 

Thanks for your question.
I am afraid I cannot think in a clean way to do it, anything that isn't too hacky. It is not just the binaries that needs to be copied, but the ``conaninfo.txt`` also would require modifications to be consistent, and then the ``conanmanifest.txt`` would also need to be updated to reflect those modifications. I am not sure if it is worth the effort, sounds it cannot be done easily and robustly, and building from source would be just easier.

As a recommendation moving forward in Conan 2.0:
- The default modes are way better, not as relaxed as ``semver_mode``, but smart enough to compete with the ``full_mode``, being more efficient in many cases. So using the defaults in Conan 2.0 could be good enough for majority of cases
- If you need to deviate, the recommendation would be to try to make sure that all teams uses the same modes. There are mechanisms that can be used to configure things in 2.0 for better modeling:
   - recipes can define their default mode for their consumers
   - recipes can define the default mode for dependencies

**Comment by igorquest** [comment]
Thank you for a quick response, @memsharded 
It's down to legacy at this point, both teams have a lot of packages in the artifactory. We'll build from source for now and hopefully converge on some common ground after conan 2.0 upgrade.

**Comment by memsharded** [comment]
Thanks for the feedback @igorquest 
I think we can close this issue, as at this moment it doesn't require any further action from us? Thanks!
