### ISSUE TITLE
[question] Why conan v2 raises ConanException when option is set downstream and configure() tries to programmatically change this value?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#14868]
### What is your question?

I thought from past discussions that in conan v2, values of dependencies options set downstream would always have precedence over values set upstream (even in "recipe owner" of this option). But I would have expected that in this situation, any attempt to programmatically change this value upstream would be silently ignored, not hard fail like this (https://github.com/conan-io/conan/blob/2.0.13/conans/model/options.py#L183-L188). What is the rational?

see https://cpplang.slack.com/archives/C41CWV9HA/p1696374024080289

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
The rational is that this raises when the recipe is trying to change too late the value of an option, because that value could have already been used in another conditional that could define some behavior, leading to an inconsistent state. Recipes can define their own ``default_options`` easily and also use ``config_options()`` for defining options values.

**Comment by SpaceIm** [comment]
Does it mean that deprecation logic of a recipe option like this one https://github.com/conan-io/conan-center-index/blob/ba7ca5d0ba56fe05a72499ee7e8631d9ef8ea373/recipes/boost/all/conanfile.py#L398-L408 can't work in conan v2?

If it can't work anymore, what could be the equivalent in conan v2?

**Comment by memsharded** [comment]
> If it can't work anymore, what could be the equivalent in conan v2?

Move it to the ``config_options()`` method?

**Comment by SpaceIm** [comment]
It's not possible since we can't read recipe option in config_options()

**Comment by memsharded** [comment]
You can only read the default, yes. 
What is not possible is to introduce conditional logic that alters what is defined from the profile. Inconsistent inputs can be validated, but not attempted to change them and expect Conan to not fail.

**Comment by SpaceIm** [comment]
So deprecation mechanism we have in conancenter can't easily work in conan v2, because we actually want to access the real option value, warn user that this option is deprecated and eventually alter other new options replacing deprecated ones to honor expected behavior.

**Comment by memsharded** [comment]
Yes, Conan 2.0 will always enforce using the option value defined in profiles or command line (consumer always has priority), so any attempt to change an option value in the ``configure()`` method (once that the profile values have been injected and defined) will result in an error. It won't silently fail either, that would be just hiding the problem and being confusing for users.

The strategy for incompatible or incorrect options values defined by consumers is to raise errors.

**Comment by SpaceIm** [comment]
Sorry I don't understand. A deprecation mechanism must not raise, so it's not the solution.

**Comment by memsharded** [comment]
Sorry, I don't know about the deprecation mechanism, that could be another discussion. I am just responding to the question why Conan 2.0 raises an error when someone tries to change the value of an ``option`` in the ``configure()`` method. 

If some other problem needs to be discussed, then please lets state the problem in a new ticket and lets have a look there.
