### ISSUE TITLE
[feature] Specify targets in CMake.build()

### ISSUE THREAD

**Issue by Ahajha** [conan-io/conan#14878]
### What is your suggestion?

My org has been moving away from using `EXCLUDE_FROM_ALL` for test targets, as it generally makes building + testing easier, but this means we need to specify which targets to build in the package.

Currently, we do the following:
```python
cmake.build(cli_args=["--target", "my_library"])
```

As a minor QOL, it would be nice if we could say something like
```python
cmake.build(targets=["my_library"])
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @Ahajha,

Thanks for the question. The CMake build helper does indeed add the [target argument](https://docs.conan.io/2/reference/tools/cmake/cmake.html#conan.tools.cmake.cmake.CMake.build), so you can use it like:

```python
cmake.build(target="my_library")
```

**Comment by Ahajha** [comment]
Excellent, that is quite useful, it must have been added since the last time I checked.

However, it only supports one argument, so if I have multiple things to build, I would either need two calls (which avoids potential parallelism) or resorting to the method described above. Could the `target` parameter be made to take either a string or list of strings?

**Comment by czoido** [comment]
Hi @Ahajha, 

Thanks for the suggestion, I'll add it to be discussed with the team and let you know soon.

**Comment by czoido** [comment]
Hi @Ahajha,
We will change this to also accept multiple targets. I have added this to the 2.0.14 milestone.
Thanks a lot for reporting.

**Update:** I have submitted https://github.com/conan-io/conan/pull/14883 this will be in 2.0.14 as:

```python
cmake.build(target=["target1", "target2"])
```
also valid:
```python
cmake.build(target=["target1"])
cmake.build(target="target1")
```
