### ISSUE TITLE
[bug] Version range doesn't support 4-digit versions in conan 1.X

### ISSUE THREAD

**Issue by kirmitrahovich** [conan-io/conan#14877]
### Environment details

* Operating System+version: Ubuntu 22.04
* Conan version: 1.61
* Python version: 3.10.12

### Steps to reproduce

Create 2 versions of the same package with 4-digits version
For example qt:
* 6.4.2.1
* 6.4.2.2

Consume this in another package and use version range: 
```python
    def requirements(self):
        self.requires("qt6/[>=6.4 <7.0]@user/channel")
```

### Logs

Version 6.4.2.1 found but 6.4.2.2 expected

```
Version ranges solved
    qt6/*@user/channel versions found in 'my-remote' remote
    Version range '>6.4 <7.0' required by 'qthrift/0.18@user/channel' resolved to 'qt6/6.4.2.1@user/channel' in remote 'my-remote'
```

**Comment by kirmitrahovich** [comment]
Looks like need to update **node-semver** to **0.8.0** or above
https://pypi.org/project/node-semver/0.8.0/

**Comment by AbrilRBS** [comment]
Hi @kirmitrahovich thanks a lot for your report. This is one of the reasons as to why Conan 2 had to happen: Conan 1 has reached its maximum maintenance ceiling - There's an explicit commitment not to break users, and so changes like this that at first might look reasonable are poisoned not to be doable, they became too risky, as Conan 1 relies on the specific behaviour of the pinned node-semver for things that if changed (bugfixes and all!) could break existing users in unexpected ways, so there's little to no chance of we bumping the dependency now.

Note that the behaviour you expect is the default in v2, and it supports an unlimited number of fields as an extension to semver

**Comment by kirmitrahovich** [comment]
Hi @RubenRBS

Yes, I found that **node-semver** is not listed in requirements.txt for Conan 2.x, that's good news that the issue is not present in the latest and greatest. 

From my side, I tried to fix it by upgrading node-semver in python-venv for conan on my machine. First I tried with latest version:
```bash
(conan-python-venv): $ pip3 install node-semver --upgrade
Collecting node-semver
  Downloading node_semver-0.9.0-py3-none-any.whl (12 kB)
ERROR: conan 1.60.1 has requirement node-semver==0.6.1, but you'll have node-semver 0.9.0 which is incompatible.
Installing collected packages: node-semver
  Attempting uninstall: node-semver
    Found existing installation: node-semver 0.6.1
    Uninstalling node-semver-0.6.1:
      Successfully uninstalled node-semver-0.6.1
Successfully installed node-semver-0.9.0

(conan-python-venv): $ conan --version
Traceback (most recent call last):
  File "/home/kmitrakhovich/conan-python-venv/bin/conan", line 5, in <module>
    from conans.conan import run
  File "/home/kmitrakhovich/conan-python-venv/lib/python3.8/site-packages/conans/__init__.py", line 4, in <module>
    from conans.client.build.msbuild import MSBuild
  File "/home/kmitrakhovich/conan-python-venv/lib/python3.8/site-packages/conans/client/build/msbuild.py", line 15, in <module>
    from conans.tools import vcvars_command as tools_vcvars_command
  File "/home/kmitrakhovich/conan-python-venv/lib/python3.8/site-packages/conans/tools.py", line 31, in <module>
    from conans.client.tools.version import Version
  File "/home/kmitrakhovich/conan-python-venv/lib/python3.8/site-packages/conans/client/tools/version.py", line 5, in <module>
    from semver import SemVer
ModuleNotFoundError: No module named 'semver'
```
It reasonably failed because **node-semver 0.9.0** version contains breaking changes.

Then I tried to install **node-semver 0.8.0** and seems it works well:
```bash
(conan-python-venv): $ pip3 install node-semver==0.8.0
Collecting node-semver==0.8.0
  Downloading node_semver-0.8.0-py3-none-any.whl (24 kB)
ERROR: conan 1.60.1 has requirement node-semver==0.6.1, but you'll have node-semver 0.8.0 which is incompatible.
Installing collected packages: node-semver
  Attempting uninstall: node-semver
    Found existing installation: node-semver 0.9.0
    Uninstalling node-semver-0.9.0:
      Successfully uninstalled node-semver-0.9.0
Successfully installed node-semver-0.8.0

(conan-python-venv) $ conan --version
Conan version 1.60.1
```

I found a workaround for me. If you want you can upgrade semver to 0.8.0 for conan 1.x, probably safe to do that

**Comment by AbrilRBS** [comment]
Hi @kirmitrahovich sorry that I did not replay to this sooner - Just wanted to thank you a lot for your time in checking the working condition of newer semver versions in Conan, we really appreciated it.

Unfortunately at this point we're not going to update anything related to Conan v1 dependencies, as it's just too risky of a factor. These kinds of issues is one of the reasons that motivated us to commit to the v2 version, as there it's much easier to take these things into consideration. We hope you understand :)

Closing this as solved, but please feel free to create new issues should you have any other question, thanks!
