### ISSUE TITLE
Should ConanFile.collect_libs() warn if both static and shared are found?

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#1487]
Here's a scenario we've just encountered. 

- build recipe for a library, `build()` uses CMake, and also builds the `install` target, so `package()` does nothing.
- the build scripts for the library build both static *and* shared versions.
- `package_info()` calls `collect_libs()` and all found libraries are added to cpp_info.libs

Now, we weren't aware of this initially, but it happens with some of the libraries we build. One of them, let's say, libraryA, generates two files: `libraryA.so` and `libraryA.a`. But another one, generates `libraryB.so` and `libraryBs.a`.

Forgot to mention, that neither the build scripts of these libraries have a cmake variable that will let us build either one or the other, otherwise we wouldn't be building both!

Now, the following things are happening:
For libraryA, I believe `collect_libraries()` will append "libraryA" twice to the list. When linking using conan generators (e.g. CMake), I guess this is harmless, but the linker usually favours the dynamic variant over the static when found in the same directory, so it's something we need to take into account.

For libraryB, collect_libraries() will pull in the two names, which will eventually cause our applications to link against both. In one of our test packages, this causes the executable to depend on a "dylib" we weren't expecting to be dependent on.

I'm wondering if one or two enhancements could come out of this situation.

1. Maybe collect_libs() can warn the user (or downright fail), if it finds the case libraryA.so and libraryA.a . Not sure much can be done about the ones that have different filenames for both variants, as there is no universal convention (some have "-s", "static", "s" suffixes) (Side note: something similar will happen on Windows if the recipe packs both release(/MD) and debug(/MDd) in the same package and both are added to cpp_info without specifying build_type.

2. Maybe collect_libs() can behave in a way that if 'shared' is defined as an option, it only pulls in the corresponding variants (on windows distinguishing a .lib between a static library and an import library for a DLL is tricky, but not impossible: https://stackoverflow.com/questions/6402586/know-if-lib-is-static-or-import) 

3. Maybe cpp_info can have a way of handling both shared and static in the same way that debug and release are? This way for these cases we can have a recipe that has the same SHA regardless of shared of static? e.g.

```
self.cpp_info.debug.static.libs.append('zlibstaticd.lib')
self.cpp_info.release.static.libs.append('zlibstaticd.lib')
self.cpp_info.debug.shared.libs.append('zlibd.lib')
self.cpp_info.release.shared.libs.append('zlib.lib')
```

**Comment by cleeland** [comment]
I disagree with failing in the case cited in (1).  A package may certainly choose to supply consumers with a choice of dynamic or archive libraries.  I'm also not in favor of making things too smart, because they typically become smart for one case and dumb for most others.

Described differently, your problem comes about because the behavior of `collect_libs()` surprised you in two different cases.  Making it smarter for your situation will very likely end up with a surprising behavior for many other situations, though.

Making `collect_libs()` dumber--or require the recipe writer to be more explicit in what they're wanting to be collected--may be the simplest way to end up with the least number of surprises.

What might be good is for `cpp_info` to learn a way to convey to its consumers which variants of libraries are available in the package, possibly along the lines of what's in (3).

**Comment by memsharded** [comment]
> the build scripts for the library build both static and shared versions.

and

> otherwise we wouldn't be building both!

It sounds that your real issue is not ``collect_libs()``, but the fact that the build system doesn't have an option to control that.

If you want to create different packages from the same build, without having to re-run the build, you might be interested in the ``build_id()`` method, that can do exactly that. There is no reason to define the resulting packages based on what the build is doing if you don't want to. http://docs.conan.io/en/latest/packaging/package_info.html#build-once-package-many

In that case, I would recommend to not use the cmake ``install`` feature, and write your own ``package()`` method. Typically this method is quite simple, it will take just a few minutes to write it, maybe a couple of attempts until you adequately package the 2 different static and shared packages.

Please tell me what you think.

**Comment by jcar87** [comment]
I don't think that there's anything wrong with `collect_libs()` at all, however, looking at the source code it does indeed seem to be looking for both `.so` and `.a`.

I have indeed considered different options, including `build_id()`, reworking the `package()` method, or even deleting the unwanted file from the package based on build options. I don't think any of this are a challenge per se.

It's more about the journey of how I discovered it was happening. I was using the install target (CMake) and doing nothing in the package() method, which is described as a valid alternative in Conan's documentation. Then a very simple test_package will also not fail in this circumstance: it lists "libz" twice (one for .so, one for .a), and because the linker is given the library path, the linker makes the decision (of using the .so). So everything can be fine and look fine and then using conan_target_link_libraries on CMake may result in linking against the wrong lib without knowing.

As for *not* using cmake install, sometimes I actually do need to use cmake install, for the following reasons:

1. Some libraries 'install' structure is completely unrelated to the structure they have in the source or the build directories. Some are super easy (all headers go into /include, all libraries go into /lib), but some are not (some headers from some directory go here, other headers from a different directory go there). The maintainers of the library have already gone through the effort of generating their "canonical" package, I'm a little wary of rewriting the logic in conan/python especially if these complexities are present. 

2. CMake build-tree generated binaries and install-tree generated binaries are linked differently on Linux and Mac. The build-tree ones include a absolute rpath or absolute install names, and the install-tree ones are clean. On Linux this isn't much of an issue given the way the dynamic loader works, but on OSX this is bad (and even they do work, if those libraries are included in a signed app bundle, they will fail gatekeeper validation for pointing to paths outside the app bundle). Bypassing the `install` method of CMake and copying the "build-tree" binaries into the package folder can have those unexpected side-effects. I would have to enable CMAKE_SKIP_RPATH or CMAKE_BUILD_WITH_INSTALL_RPATH for those builds, but would also have to be *very* careful that settings these options does not interfere with the cmake scripts for the libraries I'm building (for instance, CMAKE_BUILD_WITH_INSTALL_RPATH can result in some binaries not being generated at all). 

3. For some libraries I *do* rely on the cmake generated "LibNameConfig.cmake", again generated from the install tree. On my project, I cant rely on target_conan_link_libraries or link against ${CONAN_LIBS}, because not all of my executables are linked against *all* libraries. When linking against shared libraries, this will create a run-time dependency that may not be needed for a specific executable.
Take OpenCVConfig.cmake (generated with 'install'), the imported targets defined there contain the inter-library dependencies (e.g. opencv_imgproc depends on opencv_core). So being more "specific", I can link against the libraries I am aware that I'm explicitly using, and the imported targets have the implicit dependencies embedded in the target's link interface. I guess with conan_basic_setup(), given that it calls cmake `link_directories()`, this isn't an issue as the implicit dependencies will actually *be* found by the linker. But for my project, I can't rely on link_directories. I need the linker statements to look like `-l/absolute/path/to/libsomething.so`, rather than `-lsomething -L/absolute/path/to/`. Reason being is that if there happens to be a libsomething.so in the system, it may use that one, which can be link-time incompatible or run-time incompatible. With cmake targets, they always link to the absolute path.


Back on topic, given that it could all *work well* even with the test_package, I was thinking that a warning could at least point an unaware package maintainer in the right direction.
Oh, another thing! On Mac, the library version goes before the dylib extension, so the symlinked-versioned ones will *also* be found by collect_libs() and added twice, e.g. `libSomething.5.1.dylib` and `libSomething.dylib` (symlink to the former), will result in two 'Something' being added.

**Comment by memsharded** [comment]
Closing question as outdated, there is a new free ``from conan.tools.files import collect_libs``, and in any case, the preferred approach is to not recommend or use this helper except for trivial cases. Other cases, should be explicit in the ``package_info()`` and not rely on this tool.
