### ISSUE TITLE
[bug] apply_conandata_patches() does not work in build() method

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14876]
### Environment details

* Operating System+version: Ubuntu 23.04
* Compiler+version: n/a
* Conan version: 2.0.13
* Python version: 3.11.4

### Steps to reproduce

In https://docs.conan.io/2/examples/tools/files/patches/patch_sources.html, there's an example of how to patch source files. It says

> If you have a patch file (diff between two versions of a file), you can use the `conan.tools.files.patch` tool to apply it. The rules about where to apply the patch (`source()` or `build()` methods) are the same.

and 

> The example above works but it is a bit complex. If you follow the same yml structure (check the [apply_conandata_patches](https://docs.conan.io/2/reference/tools/files/patches.html#conan-tools-files-apply-conandata-patches) to see the full supported yml) you only need to call `apply_conandata_patches`:

That makes it sound like `apply_conandata_patches()` can also be used in the `build()` method but I tried and it fails, in my case with an error that it cannot find the file in the source folder:

```
ERROR: nvjpeg/11.1: Error in build() method, line 56
        apply_conandata_patches(self)
        FileNotFoundError: [Errno 2] No such file or directory: '/home/fschoenm/.conan2/p/nvjpea2c4c1ecfe18e/s/libnvjpeg-dev-11-1/usr/local/cuda-11.1/targets/x86_64-linux/include'
```

In the source code (https://github.com/conan-io/conan/blob/release/2.0/conan/tools/files/patches.py#L66-L67) it also seems like it can only work in the source folder (and the `source()` method).

Is that just an error in the documentation? However, I think the requirement to have configuration-dependent patches still applies to `apply_conandata_patches()` so it should be possible if it isn't right now.

**Comment by memsharded** [comment]
Hi @fschoenm 

Thanks for the feedback.
``apply_conandata_patches()`` is massively used in ``conan-center-index`` repo in the ``build()`` method: https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index%20apply_conandata_patches(self)&type=code

I guess that the problem could be elsewhere, in the folder/layout definition, the patch relative paths, etc. Maybe you have the ``no_copy_sources`` activated? You might need to remove it, you cannot apply patches in original source from the ``build()`` method.

**Comment by fschoenm** [comment]
@memsharded You're right, I had `no_copy_source = True` defined even though I don't have a `source()` method. Thanks for the hint!

By default, is `conanfile.source_folder` the same as `conanfile.build_folder` in the `build()` method? Because the [code](https://github.com/conan-io/conan/blob/release/2.0/conan/tools/files/patches.py#L66-L67) makes it look like `patchset.apply()` will always be executed in `conanfile.source_folder`.

And a follow-up question: Is there a chance to make `apply_conandata_patches()` work in the `package()` method so that it can be used with `export-pkg` instead of `create`?

**Comment by memsharded** [comment]
> By default, is conanfile.source_folder the same as conanfile.build_folder in the build() method? Because the [code](https://github.com/conan-io/conan/blob/release/2.0/conan/tools/files/patches.py#L66-L67) makes it look like patchset.apply() will always be executed in conanfile.source_folder.

The ``conanfile.source_folder`` will be inside the "build" folder in the cache, but not necessarily the same, as the ``layout()`` can define a ``src`` subfolder for it, different to the ``build`` subfolder. Both inside the cache "build" folder (the cache folder for the build step, not to be confused with the ``conanfile.build_folder``)

> And a follow-up question: Is there a chance to make apply_conandata_patches() work in the package() method so that it can be used with export-pkg instead of create?

It seems complicated. In theory the ``export-pkg`` exports already built binaries, while the patches are to be applied at source code. It seems the patching should happen earlier in the local process (executing ``conan source`` or ``conan build``)

**Comment by fschoenm** [comment]
> It seems complicated. In theory the `export-pkg` exports already built binaries, while the patches are to be applied at source code. It seems the patching should happen earlier in the local process (executing `conan source` or `conan build`)

Makes sense, most of the time. In this case we wanted to patch a header to a binary-only library from a third party. However, we can easily work-around that by using `conan create` and a `build()` method.
