### ISSUE TITLE
[question] Conan 1.55 + compatibility + --require-override + lockfiles + export-pkg issue

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#14872]
### What is your question?

Hi,

let's assume I have a conanfile.py that uses compatible_packages. Let's also assume I use --require-override with Conan 1.55 with "conan install".

Is it possible that even if I use export-pkg with --lockfile and give the lockfile "conan install" created, the lockfile will not contain the properly resolved compatible flags? E.g. we get "Locked options do not match computed options"

Is there a --require-override workflow in Conan 1.XX which works fully and it is not "conan create" based?
Thanks,

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for your question.
It is true that the ``--require-override`` is not existing in ``conan export-pkg`` command, only in ``conan create`` and ``conan install``. The truth is that the feature is complicated and fragile, and it has finally been removed in Conan 2.0 as problematic, and instead other practices are recommended. Specially, using some versioning approach, like when using version-ranges.

**Comment by harsszegi** [comment]
Hi @memsharded ,

actually I wanted to use the following approach:

* generate a lockfile with "conan install --require-override"
* use the generated lockfile by "conan install" in "conan export-pkg" with "--lockfile"

Am I getting it right, that not even that works?
Thanks,

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
