### ISSUE TITLE
Dynamic linking leads to LNK2019 with MSVC

### ISSUE THREAD

**Issue by timcoleman** [conan-io/conan#14889]
### What is your question?

Hi!

I've been struggling with this for a few days, and I can't seem to get anywhere with it. I have configured my build to be dependent on a dynamic build of OpenSSL (among other libraries).

In my conanfile.py, I configured 

`    self.options['openssl'].shared = True
`

In my CMakeLists.txt, I have

```
     find_package(OPENSSL REQUIRED)
 ...
     target_include_directories(libname PUBLIC 
 	...
 	${OpenSSL_INCLUDE_DIRS}
     )
 ...
     target_link_libraries(libname PUBLIC
 	${OpenSSL_LIBRARIES}
 	...
     )
 ```

I compile with

```
cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=generators\conan_toolchain.cmake
```

```
cmake --build . --config Release
```

But I get a bunch of unresolved symbols (such as EVP_sha512, PBKCS5_PBKDF5_HMAC_SHA1, etc) from OpenSSL. What am I missing?

Originally, I had a static build, and it did link successfully, but I do not want static linking.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @timcoleman 

Thanks for your question.
It is possible that the above ``self.options['openssl'].shared = True`` is not working? Where and how are you doing it? 

Also, the library should be linked with the target, not with the INCLUDE and LIBRARIES variables, but with the target name (something like ``OpenSSL::OpenSSL`` or the like, it will typically be printed when it is found in the CMake output).  It would be good to get the full output of your ``conan install`` and your ``cmake .. -G ...`` configure step, can you please share it?

**Comment by timcoleman** [comment]
Thanks for getting back to me!

I don't know how to tell that the shared build is working. But it is in my conanfile.py. The cache directory does contain a bin directory with DLLs and a lib directory with .lib files.

[conanfile.py.txt](https://github.com/conan-io/conan/files/12835865/conanfile.py.txt)

There are several library dependencies, including one package that I built on my machine. 

The ${OpenSSL_LIBRARIES} variable expands to openssl::openssl.

I am also attaching the cmake -G output from 

`cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=generators\conan_toolchain.cmake > cmake_output.txt`

[cmake_output.txt](https://github.com/conan-io/conan/files/12835889/cmake_output.txt)

**Comment by memsharded** [comment]
Some quick feedback:

- The recommended way to setup your dependencies options is:
   - In general, it is better to define options in the profile, not in recipes, as there can be conflicting recipes with different values of the same dependencies options
   - In case that some defaults are defined in recipes it is better to define them in ``default_options``. Trying to define them in ``configure()`` method is no longer allowed in Conan 2.0
   - You can define patterns to set the same option for your dependencies, like ``default_options = {"*:shared": True}``
- Typically it is better to unify requirements definitions, moving the attribute ``requires`` to the ``requirements()`` method.
- The filename and ``find_package()`` should be to ``find_package(OpenSSL CONFIG REQUIRED)``, not all uppercase. In windows it might be case-insensitive, but it could fail in other platforms

I am not sure what could be failing. I suspect that there is missing information about the ``libcrypto`` internal dependency, but not sure why, there are some important missing details there (as the openssl version, if the package is from ConanCenter or not, etc). I'd recommend to put together a small reproducible case, including a full conanfile + CMakeLists.txt + main.cpp that produces those errors. Do you think you could do that and share it? Many thanks!

**Comment by SpaceIm** [comment]
A portable CMakeLists should be:

```cmake
find_package(OpenSSL REQUIRED) # no CONFIG because it doesn't make sense outside of conan
target_link_libraries(foo PRIVATE OpenSSL::SSL OpenSSL::Crypto)
```

**Comment by timcoleman** [comment]
So you’re suggesting a different target_link_libraries() call. I believe I already tried that but I’m not at a computer right now to confirm.

**Comment by timcoleman** [comment]
It looks like the issue is with the override in my requirements() function. I downgraded to 3.1.0 and removed the override requirement and it built fine. Is there a different way to force a different version?

**Comment by timcoleman** [comment]
Yes, I needed to use force=True instead of override=True. I intend to build local versions of the libraries anyway, but I wanted to force it to use those versions until I could get it up and running. I hope I didn't waste too much of your time.
