### ISSUE TITLE
Creating a package from an existing binaries from conan-center

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#14881]
### How to create a boost header only package from conan center?

I know the conan center already contains boost. I want to create a header only boost package from the source in conan center.

I was able to install the boost with header only option, but not sure how to create a package out of it.

To install, I used the below conanfile.txt

```
[requires]
boost/1.70.0

[options]
boost/*:header_only=True
```

To create a package I have used the below conanfile.py but unfortunately it gives me an error.

```
from conan import ConanFile
from conan.tools.files import copy
import os


class BoostRecipe(ConanFile):
    name = "boost"
    version = "1.70.0"
    description = "C++ interface to the boost library."
.
    exports_sources = "*.h"    
      
    def requirements(self):
        self.requires("boost/1.70.0")

    def package(self): 
        print(os.listdir(self.source_folder))
        copy(self, "*.h", self.source_folder, self.package_folder) 
```

The logs:
C:\Repositories\Conan>conan create conanfile.py

======== Exporting recipe to the cache ========
boost/1.70.0: Exporting package recipe: C:\Repositories\Conan\conanfile.py
boost/1.70.0: Copied 1 '.py' file: conanfile.py
boost/1.70.0: Exported to cache folder: C:\Users\unnamed\.conan2\p\boost4f0118fa820a3\e
boost/1.70.0: Exported: boost/1.70.0#266a91852a3bc971211b81628ea2d94d (2023-10-06 08:58:12 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

======== Computing dependency graph ========
Graph root
    cli
Requirements
    boost/1.70.0#266a91852a3bc971211b81628ea2d94d - Cache
ERROR: There is a cycle/loop in the graph:
    Initial ancestor: boost/1.70.0
    Require: boost/1.70.0
    Dependency: boost/1.70.0

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

Thanks for your question.

You cannot have loops in the graph, in this case, you are trying to make a package called ``boost/1.70``, and it has a requirement on ``boost/1.70``, that is, itself. It is creating an infinite loop to itself, it is not possible to do that.

The concept you are trying to do is called re-packaging, and probably is not the right approach to your problem.
If you want to do customizations over ConanCenter packages, the recommended approach would be the one documented in: https://docs.conan.io/2/devops/using_conancenter.html. In short:

- You can fork conan-center-index repo. 
- Do the modifications you want to the recipes
- Do ``conan create . --version=xxxx`` to it, then ``conan upload`` to upload your package to your own server

(Once you fork conan-center-index, the recommendation would be to create your own binaries for all your dependencies, even if you don't modify the recipes)

Please let me know if this helps.

**Comment by sandybhat16** [comment]
@memsharded  Thank you for your response.

I was thinking we can directly create a package from existing recipe in conan center.

The option that you mentioned with forking will definitely work but then I need to have the whole repo cloned.

For now I am using a different approach where I download a specific version of boost from their website and have a recipe to package only the header files. Below is the recipe. If there is a better way to do this, please suggest. 

```
from conan import ConanFile
from conan.tools.files import copy
import os

class BoostRecipe(ConanFile):
	description = "C++ interface to the boost library."
					   
	exports_sources = "*.h", "*.hpp"
					   
	def package(self): 
		copy(self, "*.h, *.hpp", os.path.join(self.source_folder, "boost_1_70_0", "contents", "boost"), os.path.join(self.package_folder, "include", "boost"))
```

conan create conanfile.py --name=boost --version=1.70.0

**Comment by memsharded** [comment]
Hi @sandybhat16 

I still have some questions:

Why isn't the boost recipe and package from ``conancenter`` with the ``header_only=True`` option valid? It will be a header-only package, which is what you want, isn't it?

> The option that you mentioned with forking will definitely work but then I need to have the whole repo cloned.

Cloning the repo is a quite cheap operation, fast, it is just source. You can ignore the other packages if you don't need them, what is the issue with cloning the ``conan-center-index`` repo?

Also, why would you be downloading manually the boost sources, to put them together to the recipe and then ``create`` it? Conan is designed to fully automate those steps, you could use the ``source()`` method to download the sources, for example, so ``conan create`` will already take care of downloading the sources automatically.

**Comment by sandybhat16** [comment]
Hi @memsharded ,

Yes, I just want to create a header-only boost package. But can this be done without having to cloning the repo?

I mean, I can just download the boost recipe from [here](https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py) and just create a package with `header_only=True` ?

**Comment by memsharded** [comment]
> Yes, I just want to create a header-only boost package.

There is already a boost header-only package in ConanCenter, and you can install and use it with ``conan install --requires=boost/1.70.0 -o boost*:header_only=True``. Why do you want to create your own package from your own recipe for this boost specifically?

> I mean, I can just download the boost recipe from [here](https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py) and just create a package with header_only=True ?

Yes, sure, you could download ``conanfile.py`` + ``conandata.yml``, but why would you download a file from a repo instead of fork + clone it? Manually downloading loses track of the origin and makes it more difficult to do later updates from mainstream server, in case those are necessary.

Also, boost depends on other ConanCenter packages like zlib and bzip2. The recommendation is better not mix, if you create and store your own binaries, like this boost header-only, then the recommendation is to do the same for all your dependencies, and create them from your own recipes (or from your fork of ``conan-center-index``). There are some guidelines in https://docs.conan.io/2/devops/using_conancenter.html

**Comment by sandybhat16** [comment]
Hi @memsharded ,

Thank you for all the details. Very informative and helpful :)

Ok, so the reason I am creating a package is because I want to upload it to my artifact repository(JFrog). From here the consumers will download the artifacts and use them in their projects. We do not want consumers to have knowledge about conan, hence the artifact repository serves as a single source of truth for the consumers.

**Comment by memsharded** [comment]
> Ok, so the reason I am creating a package is because I want to upload it to my artifact repository(JFrog). From here the consumers will download the artifacts and use them in their projects

```
conan install --requires=boost/1.70.0 -o boost*:header_only=True -r=conancenter
conan upload boost* -r=myremote --confirm
```
And you have  the package now in your own ``myremote`` server, you could disconnect from conancenter if you want.

However it is true that this is a Conan server repo, and it should be used with the Conan client. If you don't want your consumers to use Conan, then I am not sure how creating a new Conan package with your own recipe helps with that. A Conan artifact repository serves for Conan clients, trying to use it without Conan will surely be complicated.

**Comment by sandybhat16** [comment]
Hi @memsharded ,

Just the two lines? I had already done the first part - conan install. But I was under an impression that you need to create a package of the installed boost and then upload. I wasn't aware you can directly upload the installed package :)

**Comment by memsharded** [comment]
> Just the two lines? I had already done the first part - conan install. But I was under an impression that you need to create a package of the installed boost and then upload. I wasn't aware you can directly upload the installed package :)

Sure, you can! You can even upload full dependency graphs, thanks to the ``package lists`` feature, check this blog post for example: https://blog.conan.io/2023/06/28/Conan-bulk-package-operations.html. Because it is not enough to have boost, in your own repo, as I pointed out, boost itself depends on zlib and bzip2, so those packages might be necessary as well.
