### ISSUE TITLE
Is there any way to "test" to see if the package in local cache is out of date?

### ISSUE THREAD

**Issue by cleeland** [conan-io/conan#1489]
I am currently using `package_files` to package up a staged "install" directory built by an external build system.  I'm modifying the legacy build system to generate the relevant `conanfile.py` and export it, and now I need to decide if I need to `package_files` and `upload`.

This is legacy, so it's driven from a Makefile, which works best when evaluating declared dependencies amongst files.  However, I'm not sure how to fit conan into a Makefile dependency flow.

Is there a way for me to detect that what's currently in the local cache is different from what `package_files` will package?  Is there a way for me to detect that what's currently in the local cache is newer (or older) than what's in The Repository?

**Comment by memsharded** [comment]
Every package and recipe in the local cache have a manifest with the md5 hashes of all the files, and the timestamp when it was created. They are used in integrity checks, and also for the manifest storage and validation. There are no automatic commands or tools to check that, but I think they might be useful. In the short term, you can read the ``conanmanifests.txt`` files, they are simple, so shouldn't be difficult to parse. If your local package before ``package_files`` is created with a local ``conan package`` command, it will also have its own manifest too. The ``FileTreeManifest`` class already has some code to compare them, so building the command interface to do it should be possible.

Suggestion welcome regarding the UI/UX and command.

**Comment by cleeland** [comment]
>Suggestion welcome regarding the UI/UX and command

Just to follow up, I'm working through this as I go.  At the moment the dependency situation is still a little murky.  I will definitely be back.

**Comment by memsharded** [comment]
This is very outdated, ``package_files`` haven't exist for years.

Now, with the ``revisions`` this shouldn't be an issue, closing, please create new tickets for further questions
