### ISSUE TITLE
[question] Using Conan Editable in 2.x with local repo without local recipe

### ISSUE THREAD

**Issue by JoshMusick** [conan-io/conan#14897]
### What is your question?

Hello, 

My question is how to use conan editable in 2.x when the conanfile.py is not version specific (the version information is stored in the conandata.yml)? 

(A little background) We are in the process of migrating our recipes from Conan 1.x to 2.x.  Our recipes are all contained in a single git repository, and each library/package recipe is contained within their own folder with a generic conanfile.py and an associated conandata.yml.  We define the different versions and the associated requirements  for each version in the conandata.yml, and run a python script to export the recipes into the local conan cache.  During the export, the version number maps to a SHA1 or git tag that is checked out during the source method.  (this was modeled after conan center I believe).

Previously (Conan 1.x), we would build a library/package and install it to specific install directory and then run the following Conan commands in the install directory:

$ conan get <package_name>/<version>@<user>/<channel>  > conanfile.py
... 
$ conan editable add . <package_name>/<version>@<user>/<channel>

In this way, if we need to change the package source, we would make edits, rebuild / re-install the modified package, and clients of the editable package would see / use the edited version.  

However, in Conan 2.x the `conan get` command is no longer available, and I'm unsure how make this work (get a conanfile.py that is version specific, based on what is in the cache).  The only way I can think of is to replicate the conanfile.py and conandata.yml files in the library git repository, and specify the version explicitly in the recipe.  This is doable, though not necessarily ideal (as this requires 2 sets of recipes to maintain).  I'm wondering if there is a better way of accomplishing this and I've just missed it.  All the documentation pages / tutorials I've read through include the recipe directly in the git repository / source bundles.

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @JoshMusick 

Thanks for your question.
Indeed the ``editable`` flow is intended when the source and recipe is located together in the same repo. But even if they don't it should be possible, as long as things like ``layout()`` are correct, even for recipes implementing multiple versions, as ``--version`` can be passed to ``conan editable add``. In any case, the flow is working from the repo directly, the ``conan get`` flow is very ill formed, and having things without tracing it to the source code in SCM repos is discouraged.

I have some quick questions:
- Are you using that approach for third-party dependencies or for your own libraries?
- What are the main challenges of doing ``conan editable add`` over the repo containing the recipes? Not fully clear why 2 sets of recipes are necessary for this, and why the existing recipe in the repo can't be used.

**Comment by JoshMusick** [comment]
- We are only using conan editable for our own libraries. 
- The main challenge is keeping the recipes synchronized and available to our team at large.  Until recently, we did not have access to an Artifactory instance to host our recipes, so our approach was a git repo with all the recipes which were exported using a custom python script.  If the recipe is in the source repo, it would be effectively tied to the "current" version of the library.  And anyone wanting the current set of recipes would need to clone and checkout all the relevant versions of the library and export each version.  As things in Conan have changed, our recipes have undergone a lot of change, and therefore having a repo of recipes has been nice.  

I think your suggestion regarding "conan editable add  ... " with the addition of the --version argument is a workable solution, we will just need to copy in the conanfile.py and conandata.yml into the local source repo (when we want to use it as editable), so the "official copy" of the recipe is in our recipe repository, rather than 2 "sources of truth".  

Thanks again!

**Comment by memsharded** [comment]
> I think your suggestion regarding "conan editable add ... " with the addition of the --version argument is a workable solution, we will just need to copy in the conanfile.py and conandata.yml into the local source repo (when we want to use it as editable), so the "official copy" of the recipe is in our recipe repository, rather than 2 "sources of truth".

Ok, sounds good, don't hesitate to open new tickets if you have any further question. Thanks for the feedback!
