### ISSUE TITLE
[question] Replacement for self.copy(root_package)

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#14895]
### What is your question?

I found `self.copy(root_package)` useful in v1 when doing imports. Is there a replacement in v2?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rconde01 

Yes, the equivalent of doing a ``self.copy()`` in imports would be a ``copy(self, ...)`` in the ``generate()`` method. Something like https://docs.conan.io/1/migrating_to_2.0/recipes.html#removed-imports-method:

```python
def generate(self):
    for dep in self.dependencies.values():
        copy(self, "*.dylib", dep.cpp_info.libdirs[0], self.build_folder)
        copy(self, "*.dll", dep.cpp_info.libdirs[0], self.build_folder)
```
However, in many cases, it is recommended to try to avoid the copy and use VirtualBuildEnv/VirtualRunEnv if possible instead.

**Comment by rconde01** [comment]
I'll look at VirtualBuildEnv/VirtualRunEnv, but the key thing missing here was the `root_package` so you can import different things based on the package

**Comment by memsharded** [comment]
You have full control over the package or packages you want to copy from with the new syntax (this is one of the reasons it is preferred, more control):
```python
def generate(self):
    dep = self.dependencies["mydep"]  # copy only from "mydep" package
    copy(self, "*.dylib", dep.cpp_info.libdir, self.build_folder)
    copy(self, "*.dll", dep.cpp_info.libdir, self.build_folder)
```

**Comment by rconde01** [comment]
ah great!
