### ISSUE TITLE
[feature] Add "warnings as errors" mode

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#14909]
### What is your suggestion?

For example, sometimes when i'm developing a package I get: "Warning: No files in package"...I would like that to show up as an error. Of course, I guess that also implies the need to suppress warnings - so perhaps it's not so simple.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for the suggestion @rconde01 

There is already some capability of suppressing warnings in Conan 2.0 with ``core:skip_warnings``
I think this is a valid feature request and something we would be interesting to provide. It is true that ``core:skip_warnings`` is not capable of suppressing all warnings, only those that are tagged now (only a few are, with "deprecation"), but that shouldn't be a stopper to provide this, lets discuss it with the team.

**Comment by rconde01** [comment]
For additional context, 2 other places i've seen warnings are patches and/or replace_in_file not applying correctly. I would say as a rule one should architect such that these apply, or are errors. Seems pretty risky otherwise and could be difficult to debug downstream.

**Comment by memsharded** [comment]
> For additional context, 2 other places i've seen warnings are patches and/or replace_in_file not applying correctly. I would say as a rule one should architect such that these apply, or are errors. Seems pretty risky otherwise and could be difficult to debug downstream.

I think these would deserve their own separate ticket, as it is a different one.
The ``replace_in_file`` by default will raise an error, not a warning, if not successful. It has an opt-out ``strict=False``, but otherwise it will raise an error. Same as ``patch()``. But if they dont, I agree it would be better if they raised an error (not that it could be changed now without breaking)

**Comment by rconde01** [comment]
hmm...but if the feature is "warnings as errors" then it's a bit weird if they don't cover these cases. But I see that indeed it's an edge case. You don't want to break any recipes, though you could make the policy to not allow `strict=False` in conan center for updated recipes. I guess the choice to show a warning is weird here. Either 

1. You didn't select `strict=False` and you want an error on failure.
2. You specified `strict=False` implying "hey - i know what i'm doing here and this behavior is expected"...warnings seem like noise then. 

Could change these cases to something like: `Info: replace_in_file didn't replace anything.` if it's really important to see it.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/15149 for next 2.0.15
