### ISSUE TITLE
Powershell virtualenv is missing for Linux on Conan V2

### ISSUE THREAD

**Issue by spakarl** [conan-io/conan#14903]
### Environment details

* Operating System+version: Linux
* Conan version: 2.0.13

In global.conf we can require powershell scripts for virtuel environment setup. Somebody decided that this is only needed for windows, which is wrong. I use powershell on linux for every build.

tools.env.virtualenv:powershell: If it is set to True it will generate powershell launchers if os=Windows

Currently no more powershell scripts for virtual environments are created anymore with conan v2. This breaks my build system.

### Steps to reproduce

Add the VirtualRunEnv and VirtualBuildEnv generators to your recipe.
Add tools.env.virtualenv:powershell=True to your host profile (not sure if this is required)
Try to build your small project: No powershell scripts are being generated on Linux.

**Comment by memsharded** [comment]
Hi @spakarl 

Thanks for your feedback.
I am not sure what you mean, I just tried in my linux:
```
$  conan --version
Conan version 2.0.13
$ conan install --requires="cmake/[>3]" -g VirtualRunEnv -c tools.env.virtualenv:powershell=True
...
cli: Generated aggregated env files: ['conanrun.ps1', 'conanbuild.ps1']
$ ls
conanbuild.ps1  conanbuildenv-release-x86_64.ps1  conanrun.ps1  conanrunenv-release-x86_64.ps1  deactivate_conanbuild.ps1  deactivate_conanrun.ps1
```

It seems to work fine

**Comment by spakarl** [comment]
You are right. It works after I added "tools.env.virtualenv:powershell=True" correctly to the profile.

But at least the documentation is misleading. It indicates that this only works if os = "windows".

https://docs.conan.io/2/reference/tools/env/envvars.html?highlight=powershell

You can close the issue. Thanks for helping.
