### ISSUE TITLE
[bug] Backport the fix for defining compiler_executables as a list for Meson to Conan V1

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#14910]
### Environment details

Please backport #14676 to Conan V1.
It's necessary to use the compiler executables with Meson in this way in order to cross-compile the `libsystemd` package due to bug  #10288.

**Comment by memsharded** [comment]
This backport is not planned, Conan 1 has even been phased out of ConanCenter.
Closing as unplanned.
