### ISSUE TITLE
[question] Error Finding Header-Only Package

### ISSUE THREAD

**Issue by csirianni** [conan-io/conan#14911]
### What is your question?

I'm looking for some help using [Crow](https://crowcpp.org/master/) in my C++ project. I am using Conan as a package manager. I have the following project structure:

```
/backend
└──/build
└──/src
|  └──main.cpp
└──conanfile.py
└──CMakeLists.txt
```

**CMake is unable to find Crow** using my `CMakeLists.txt`:

```
cmake_minimum_required(VERSION 3.27)
project(backend)

find_package(Crow REQUIRED)

add_executable(${PROJECT_NAME} src/main.cpp)
target_link_libraries(${PROJECT_NAME} Crow::Crow)
```

When I run `cmake ..` from `/build`, I get the following error:

```
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "FindCrow.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Crow", but
  CMake did not find one.
```

 My `conanfile.py` contains the following:

```
from conan import ConanFile


class BackendRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"

    def requirements(self):
        self.requires("crowcpp-crow/1.0+5")

    def build_requirements(self):
        self.tool_requires("cmake/3.22.6")
```

So, I'm stating that Crow is a required package, and I can see it installed when I run 

```
conan install . --output-folder=build --build=missing
```

from `/backend`.

I was able to import `zlib` by following the [docs](https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html), but when I replace zlib with Crow, the project breaks! You can see the working `zlib` configuration [here](https://github.com/csirianni/private-data-lookup). The only difference I know of is Crow is a **header-only library**. 

Could you please help me figure out this error?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @csirianni thanks a lot for your question. Unfortunately I'm not able to replicate this in my end.

As per the doc page you linked, I've run the following steps:
- `$ conan install . --build=missing --output-folder=build`
- `$ cd build`
- `$ cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release`
- `$ cmake --build .`

And I get a successful configuration and build in the last two steps - I wonder what's going on, because as far as I can see, you ran similar commands 🤔

**Comment by csirianni** [comment]
Wait, that worked! I was running `cmake ..`, not `cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release`. Could you help me understand the difference?

**Comment by memsharded** [comment]
These arguments achieve the following:
- ``-DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake`` pass the generated ``conan_toolchain.cmake`` file. You can inspect this file. It contains for example the definition of CMAKE_PREFIX_PATH so CMake can find the different xxxx-config.cmake files generated for dependencies, to locate the dependencies. It can also define some configuration to align the build with the defined Conan settings (you see the Conan settings in the output profiles of ``conan install``)
- The ``-DCMAKE_BUILD_TYPE=Release`` defines the CMake build type. This is important for non multi-config compilers (gcc, for example), as CMake builds with configurations, not providing one is a discouraged practice by CMake

Hope this helps.
