### ISSUE TITLE
Is there a multi config generator option for visual studio in Conan 2.0?

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#14917]
### Is there a multi config generator option for visual studio in Conan 2.0?

Hi,

I am trying to generate a multi config props file for visual studio, something that would mimic the legacy generator 'visual_studio_multi'. Is there a possibility?

Currently I am using 'MSBuildDeps' generator. But this generates for the build_type set in the current profile.

Do I need to individually generate and include them or there is someway that I am not able to find in the documentation of 2.0? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

Yes, the ``MSBuildDeps`` is multi-configuration, in the same way that ``visual_studio_multi`` worked. It allows to install both Debug and Release (and even more custom configs), do several ``conan install`` (one per configuration), and then add the .props file to the project (it will contain all the conditionals for switching configuration).
Yes, it generates the files for the current configuration/profile, you need to do:
```
conan install . -pr=myprofile
conan install . -pr=myprofile -s build_type=Debug
```
But I think this was already the case for ``visual_studio_multi``, this hasn't changed in this regard.

The ``MSBuildDeps`` is also superior, as it generates also a file per package, so it allows subprojects to depend on specific dependencies, and not to force all of them.

**Comment by sandybhat16** [comment]
Thank you @memsharded for the clarification. However I have one question. In the legacy `visual_studio` generator, it used to create only one file with name 'conanbuildinfoDebug.props' or 'conanbuildinfoRelease.props', depending on the configuration. But with the latest `MSBuildDeps `, it generates too many files. Is there a way to generate only 1 file, and also if possible to specify the filename? :)

**Comment by memsharded** [comment]
It also generates ``conandeps.props``, that serves the same purpose, aggregating all dependencies (and both Debug and Release configurations too)

**Comment by sandybhat16** [comment]
This is true, but I cannot directly include only this in my C++ project as it internally depends on many other props like `conan_boost.props` -> `conan_boost_headers`.props and so on.

**Comment by memsharded** [comment]
> This is true, but I cannot directly include only this in my C++ project as it internally depends on many other props like conan_boost.props -> conan_boost_headers.props and so on.

I am afraid I don't understand. The ``conanbuildinfoDebug.props`` also added all the dependencies, including boost, boost-headers, etc. The behavior has not changed, it is just the implementation uses more files.

**Comment by memsharded** [comment]
All good then with the new ``MSBuildDeps`` generator? Did you manage to migrate succesfully?

**Comment by sandybhat16** [comment]
Hi @memsharded , We wanted a package manager that supports both C++ & FORTRAN. Unfortunately I could not find a way to install the FORTRAN packages as there was no way to include a props file in a vfproj file. Hence we thought of moving to another  package manager, Conda.

**Comment by memsharded** [comment]
>  We wanted a package manager that supports both C++ & FORTRAN. Unfortunately I could not find a way to install the FORTRAN packages as there was no way to include a props file in a vfproj file. Hence we thought of moving to another package manager, Conda.

Ok, Conan can definitely be extended to create the files, that is kind of a 1 day effort, but I understand you want something that has that out-of-the-box, if Conda works for you, because you also manage packages with Python wrappers, etc, that is good. Thanks for the feedback.
