### ISSUE TITLE
Does conan also serve as a package manager for FORTRAN?

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#14916]
### Does conan also serve as a package manager for FORTRAN?

Hi,

I know conan is basically a package manager for C/C++ across different platforms. But now I have a requirement to include boost conan package in C++ project as well as FORTRAN. I was able to achieve this for C++ projects but was wondering if there are any generators or any specific way in which we can also use the conan package for FORTRAN projects?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

Conan does not have explicitly modeling or build helpers for Fortran.
But also, Conan is extremely flexible and customizable, we know that there are users using it to package Fortran built packages, but also even python, java, matlab, labview, full system images, etc.

You can also search ConanCenter for packages using or related to fortran:
- The ``gfortran`` package is there, it can be used as ``tool_requires``
- You can find recipes like armadillo, or openblas with some fortran options. It might be worth checking those and see how they use fortran

**Comment by sandybhat16** [comment]
Hi @memsharded ,

Thanks for the hint, will check those out. Meanwhile, another way I can think of is using a C wrapper around the FORTRAN and consume the Conan package. Much easier I guess 😄
