### ISSUE TITLE
Using conan-center by default?

### ISSUE THREAD

**Issue by Socapex** [conan-io/conan#1492]
Hello, quick question as I haven't found any documentation on simply using the new conan-center packages. All doc I've found was related to creating packages, not consuming them. The following
```
[requires]
OpenSSL/1.0.2l@conan/stable
```
doesn't find the package, but reverts to looking in remotes and using conan-center after all. Is that intentional behaviour? Can I provide parameters/options to specify conan-center only packages. I'm guessing this is a simple thing.

**Comment by memsharded** [comment]
Yes, you can. Most commands can use the ``-r=yourremote`` argument to restrict to that remote. 
You shouldn't need anything special to use conan-center, it is configured by default in latest conan clients, or you can add it with the ``conan remote`` command.

When you say that it can be found, is the package recipe that can't be found or maybe it is just that a pre-built binary for your configuration doesn't exist? Please copy the output showing the command and the error, and also specify your configuration. Thanks!

**Comment by Socapex** [comment]
Well this is embarrassing, I mis-understood the "Not found, looking in remotes..." message. I interpreted it as if conan didn't find the package remotely, looking in transit before conan-center somehow.

So from what I gather, by default in new versions, it will always prioritize conan-center. So as long as the user and version are found in center, that will be used by default. Seems good to me.

OpenSSL/1.0.2l@conan/stable: Not found, looking in remotes...
OpenSSL/1.0.2l@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]

**Comment by memsharded** [comment]
> "Not found, looking in remotes..."

Yeah, that means not found in the local cache, then looking for it in the remotes. 

Can this issue be closed then? :)

**Comment by Socapex** [comment]
Yes please! :)

**Comment by memsharded** [comment]
@Duduitto has improved the output message for this in #1511

**Comment by Socapex** [comment]
Awesome! Thanks
