### ISSUE TITLE
[question] test requirements propaged to graph as non test

### ISSUE THREAD

**Issue by xandox** [conan-io/conan#14927]
### What is your question?

Hello all.

I try to build my own deployer. And I faced the next problem

I have a library which requirements looks like:

```
    def requirements(self):
        self.requires("lib1")
        self.requires("lib2", transitive_headers=True)
        self.requires("lib3", transitive_headers=True)
        self.requires("lib4", test=True)
        self.requires("lib5")
```

And I want copy headers only from libraries which really needed (read as from transitive headers requirements only)
For this I do next:

```
def copy_pkgs_headers(conanfiles, output_folder):
    all_include_dirs = set()
    while conanfiles:
        conanfile = conanfiles.pop()
        all_include_dirs.update(collect_folders_to_copy(conanfile.cpp_info.includedirs))
        for req, dep in conanfile.dependencies.host.filter({"direct": True}).items():
            print(
                f"[{conanfile.ref}] {dep.ref} headers: {req.transitive_headers}, libs: {req.transitive_libs}, test: {req.test}, direct: {req.direct}, build: {req.build}, visible: {req.visible}"
            )
            if req.transitive_headers and not req.test:
                conanfiles.append(dep)

    folders_for_copy = collect_folders_to_copy(all_include_dirs)
    for folder in folders_for_copy:
        if folder.is_dir():
            print("Copying headers from", folder, "to", output_folder)
            shutil.copytree(folder, output_folder, dirs_exist_ok=True)


def deploy(graph, output_folder, **kwargs):
    output_folder = Path(output_folder)
    conan_file = graph.root.conanfile
    top_requires_ref = []
    top_requires = []
    for req_install in conan_file.requires.values():
        top_requires_ref.append(req_install.ref)

    for dep in conan_file.dependencies.host.values():
        if dep.ref in top_requires_ref:
            top_requires.append(dep)

    copy_pkgs_headers(top_requires, output_folder / "include")
```

In this scenario `lib1` and `lib5` are skipped as expected, `lib2` and `lib3` are selected to copy include directories (as expected too) but also `lib4` is selected to copy includes too!

`lib4` is not marked as for test (test attribute or is_test are None or False) and marked with `transitive_headers=True`.

I do not understand why it marked as transitive_headers, may be there is some reason behind this (but looks like a bug).
But about where have gone a `is_test` I have some theory. I investigated a bit and not sure I understand a bit much. But  
this line https://github.com/conan-io/conan/blob/release/2.0/conans/model/requires.py#L334 looks suspicious may be it should looks like 
```
        if require.test:
            downstream_require.test = True
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @xandox 

Thanks for your question.
I think the main reason is that for test requires the ``self.test_requires()`` is recommended.
This is because it does more than ``test=True``, but it does the very important ``visible=False``, to avoid propagating the test library to downstream consumers where it doesn't make sense.

Please try that and let me know.

**Comment by xandox** [comment]
Hello @memsharded 

Yes, `self.test_requires()` solve this problem. thank you
