### ISSUE TITLE
[question] importing existing packages into conan client

### ISSUE THREAD

**Issue by weatherhead99** [conan-io/conan#14921]
### What is your question?

Hello, 
I already know the *correct* answer to this question (host _two_ internal artifactory deployments), and am certain that I cannot fully do it at the moment, so please bear with me.
We have a fairly big stack of dependencies for several internal projects. After a few years of wrangling recipes etc, most of these can now be built by conan for all relevant platforms and configurations (yay!). We generally have different options from conan-center (all default shared libraries, depending on shared libraries all the way through the tree for a start,. and other different options etc), so we have our own set of build artifacts for these, even though many of the recipes come from conan center index. We have a conan_server running internally on our "outer" network, which helps with development, uploading etc on developer machines.

However, when we deploy to our "inner" network (which has no external internet access), we basically have to build our binaries and then copy them manually to the machines they will run on. This is generally fine, but it means re-building packages etc on those machines is pretty difficult. Every time I want to change a dependency I have to rebuild it on a development machine, and then scp the resulting binary to the inner machines (which has _only_ ssh access to the outer network, no other ports open, and no access to the wider internet - these are experimental hardware control machines).

What I would like is a way to "export" a bunch of conan package artifacts (e.g. as I would download from a conan_server as .tgz packages), and then "import" them into the cache of a local conan install. This was possible in conan1, but with conan 2, it seems of course I'd have to build the sqlite db etc etc.

We have considered running "conan_server" locally on _each_ inner machine, bringing in the data directory to that, and then "downloading" them locally into the conan cache. This is not ideal.

Alternatively, we can I suppose build a full deploy of all the dependencies for a project, zip it up, and then use that. THis is also not ideal because we lose a lot of the nice functionality of conan (e.g. "rebuild me this dependency with -obuild_type=Debug" or similar). 

Is this functionality  possible right now? Or could I get suggestions of how to implement it e.g. with a custom command or similar?

Thanks

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @weatherhead99 

This feature request already exist, it is planned for the 2.X roadmap, track these tickets:
- https://github.com/conan-io/conan/issues/4316
- https://github.com/conan-io/conan/issues/10740

The good news is that we have already started working on this and it is looking good, so hopefully it will be soon available.
I am closing this ticket as duplicate, please track the other tickets for progress about this feature, thanks!
