### ISSUE TITLE
[feature] allow ignoring untracked files in Git.is_dirty()

### ISSUE THREAD

**Issue by weatherhead99** [conan-io/conan#14925]
### What is your suggestion?

Hi,
In our internal projects we use the `tools.scm.Git` object with `set_version()` to determine package version from git tags.

With a bit of custom logic this works great, however: 
the value of `Git.is_dirty()` returns True, even if the repository is clean, if that repository also contains untracked files.

I would note this is different to the behaviour of setting e.g. "revision_mode=scm" or "revision_mode=scm_folder" which do not consider untracked files to make the repository dirty.

Thus, for example, I end up with a package (whose revision mode is "scm_folder") but which ends up getting a version attribute of project/0.3.3-dev.13+0c9b7c4-dirty.

I propose either:
   - changing behaviour of `tools.scm.Git.is_dirty()` to use `git status -s -u no` so that it ignores untracked files and returns True  when untracked files are present to align behaviour with revision mode (understand this probably isn't allowed due to compatibility
   - adding an optional parameter to `tools.scm.Git.is_dirty()` (e.g. `consider_untracked: bool`) so that users can choose this behaviour with default value of True which would retain the existing behaviour

Happy to open PR for that latter if it is the preferred option.

THanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Sorry for the delay in responding

Conan 2.1 (https://docs.conan.io/2/changelog.html#feb-2024) got:

- Feature: New Git(..., excluded=[]) feature to avoid “dirty” errors in Git helper. [#15457](https://github.com/conan-io/conan/pull/15457) . Docs [here](https://github.com/conan-io/docs/pull/3538)
- Feature: New core.scm:excluded feature to avoid “dirty” errors in Git helper and revision_mode = "scm". [#15457](https://github.com/conan-io/conan/pull/15457) . Docs [here](https://github.com/conan-io/docs/pull/3538)

I am closing this ticket as resolved, thanks very much for the feedback. If there is any further issue, please create new tickets for it. Thanks!
