### ISSUE TITLE
[bug] Find Commit in Remote on Shallow Clone

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#14928]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: gcc11
* Conan version: 2.0.13
* Python version: 3.10.6

### Steps to reproduce

The git helper is able to add the repo url and commit to our conandata.yml file.  It uses `git branch -r --contains {commit_hash}`.  My CI system does a shallow clone of the repo in certain cases and the `git branch` command can't find the commit.  It is easier to recreate outside of conan rather than inside a recipe.

1. git clone --depth=1 --branch=2.0.13 https://github.com/conan-io/conan.git
2. git log # Shows that the commit hash is 8cb007e15865d06d999658d72f396a69400aefcb
3. git branch -r --contains 8cb007e15865d06d999658d72f396a69400aefcb

Note that the `git branch` doesn't find the commit.  If you repeat the steps without the `depth=1` then git is able to find the commit.

### Logs

Inside of the `conan create` when I call `Git(self).get_url_and_commit()` I get the following warning.
WARN: Current commit f033eaf9380ec2177257d73ea9b4b8625f1b81d1 doesn't exist in remote origin
This revision will not be buildable in other computer

That commit does exist in the remote url.

### Solution
The current code in `conan/tools/git/` uses `git branch -r --contains {hash}`
I found that instead running: `git fetch origin --dry-run --depth=1 {hash}` works even if the commit is shallow.    https://stackoverflow.com/questions/65611995/how-to-check-whether-a-git-commit-exists-on-some-remote

I'm happy to submit a pull request for this.

**Comment by memsharded** [comment]
Hi @jsallay 

Thanks for your detailed report, your investigation and your proposal.

I agree that it might be worth fixing this, and making sure it works even if depth=1

Is there any possible risk that you envision with this change? Anything that could be broken by this fix? This works in reasonably old git versions, not only latest?

If looking good and no big risks, sure, a PR would be very welcomed!

**Comment by jsallay** [comment]
I can do some testing. What is the oldest version of git or operating
system that you support?

**Comment by memsharded** [comment]
Not an explicit Git version per se, but we typically use Ubuntu 16 LTS as a base line for system-versions (not CMake or compilers) that should work if possible.

**Comment by jsallay** [comment]
One important difference is that the `fetch` command contacts the git remote, while the `branch` command does not.  How do you feel about that?  The switch would mean that you couldn't build the repo without an internet connection.

We could do a two step approach and first try the `git branch` and then if that fails, do the `git fetch`.  I think the other option would be to see if I can detect if is this a shallow clone (i.e. there is no history in the .git folder) and assume that the commit is in the remote in this case.  Do you have thoughts?

**Comment by memsharded** [comment]
> One important difference is that the fetch command contacts the git remote, while the branch command does not. How do you feel about that? The switch would mean that you couldn't build the repo without an internet connection.

The goal of the check "in-remote" is to validate that the commit exist in the remote, so I think it is legit to ask for an internet connection to the remote. For a start, this internet connection is necessary, because the repo has had to be cloned from the internet in the first place in order for the commit to be there, isn't it?

Just make sure that it doesn't fail hard if the internet is not available and try to fallback to the previous behavior should be safe enough?

> We could do a two step approach and first try the git branch and then if that fails, do the git fetch. I think the other option would be to see if I can detect if is this a shallow clone (i.e. there is no history in the .git folder) and assume that the commit is in the remote in this case. Do you have thoughts?

Yes, exactly, I hadn't read the whole message, we are aligned! :)
