### ISSUE TITLE
[question] Best practices for libraries that are configured using targets with specific names and headers

### ISSUE THREAD

**Issue by ohunter** [conan-io/conan#14922]
### What is your question?

I know that Conan has limited support for microcontrollers and that the world of libraries for microcontrollers is lagging quite far behind in terms of tooling support so I'd like figure out how to best deal with the additional complexities a library such as [FreeRTOS-kernel](https://github.com/FreeRTOS/FreeRTOS-Kernel) introduces. If you look at the way that CMake is set up it requires a target `freertos_config` to be defined. This target generally just needs to be an interface target with some specific header files. Most of the time this is just a file called `FreeRTOSConfig.h` but depending on the architecture in use it might also need a file called `secure_context.h`. I am not sure whether other architectures require additional files. These files would normally be highly tied to the platform the application is running on so the need to configure it correctly per platform is critical. Thus I would like to know if there are any best practices for dealing with a situation like this.

My current solution is to download and unpack the specified release in `source()` into a subfolder. Then in the root I have a `CMakeLists.txt` in which I declare the `freertos_config` target. Crucially I also generate the headers in `build()` based on various settings and options. This is quite cumbersome as there are a fair number of [configuration options](https://www.freertos.org/a00110.html) that might need to be set. This approach works well until one of the configuration values need to depend on variable defined in the vendors SDK of the platform. Another downside to this is that the list of options becomes very long and most of the accepted values are set to `["ANY"]` or `["ANY", None]` (This is tangential to this, but based on my current understanding of conan I think replacing the current options model with a `TypedDict` implementation could fix this). 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ohunter 

Thanks for your question.

I think you commented a very important aspect: the variability of the microcontroller world is so vast and unstructured, that it can be very challenging to provide general common solutions to it.

So what we see in our users (there are many doing embedded, baremetal, micros, etc) is something like this:
- They define their own classification of the platforms they build for, in custom ``settings.yml`` (``settings_user.yml`` in Conan 2.0). This classification can be under ``baremetal`` OS, but we have also seen it as first level settings, under compiler, etc. This classification is a high level abstraction over the specific details, and avoids having too many knobs in the form of many options.
- When the platform abstraction is defined, then packages for it, like a package ``freertos_headers/version`` can be defined, and even if it header-only, it can create and store a different set of headers per platform (just do not do ``self.info.clear()`` in the ``package_id()`` method). This allows to simplify recipes that only need to depend on this as yet another package, as the ``settings`` will manage to get the right headers for the current platform.
- Common abstractions for the build systems that will use conditionals over the platform, can be encoded and reused in ``python_requires``.

While it is true that it is not a fully generic solution for the whole microcontroller ecosystem, approaches in this line seem to work quite well for organizations targeting embedded in their development.

**Comment by memsharded** [comment]
Closing this as responded back then, but please open new tickets for any further question or issue you might have, thanks for your feedback.
