### ISSUE TITLE
[bug] cache.sqlite3 is not compatible between Windows and Unix platforms

### ISSUE THREAD

**Issue by s-ker-s** [conan-io/conan#14926]
### Environment details

* Operating System+version: Windows
* Compiler+version: N/A
* Conan version: 2.0.13
* Python version: 3.10

### Steps to reproduce

1. Inspect $CONAN_HOME/p/cache.sqlite3
````
$ sqlite3 windows-conan2/p/cache.sqlite3   
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> select * from packages;
boost/1.83.0|e948ecbe69e6e240658ba2eda46ba8e8|da39a3ee5e6b4b0d3255bfef95601890afd80709|eb10a41c296a4acc9392570ae8d2cee6|boost63aa29112e350|1694688278.4|
gtest/1.10.0|986363bc16daca373e0bedc5b8456ab1|a47d85d4981b058fc786498a7982af6a9adfcd53|32b1b03dd535a084b1496f278976b12f|b\gtest5bb5ef36e2dcc|1697201372.42247|
````
3. Values in the `path` column contain a backslash on Windows, e.g. `b\gtest5bb5ef36e2dcc`
4. This leads to an error when trying to use that cache on another platform, e.g. macOS or Linux:
````
$ CONAN_HOME=$PWD/windows-conan2/ conan list "*:*"
Local Cache
  ERROR: Corrupted package 'gtest/1.10.0:a47d85d4981b058fc786498a7982af6a9adfcd53' without conaninfo.txt in: /Users/szkers/Downloads/conan-cache/windows-conan2/p/b\gtest5bb5ef36e2dcc/p/conaninfo.txt
````

Our use case is to first create and test Conan packages on various platforms in a single Gitlab pipeline, then pass the Conan cache directories to a single Linux job to upload the Conan packages to Artifactory "atomically".

This is possibly not supported on purpose, though IMHO it would be nice if it were. Possible workarounds:

- Convert the backslashes to slashes in `cache.sqlite3` before using it on Linux
- Rebuild `cache.sqlite3` from scratch (not sure if that's possible)

**Comment by memsharded** [comment]
Hi @s-ker-s 

Thanks for your report.
The Conan cache is not designed to be shared, more importantly not designed to be shared among different operating systems. 

> Our use case is to first create and test Conan packages on various platforms in a single Gitlab pipeline, then pass the Conan cache directories to a single Linux job to upload the Conan packages to Artifactory "atomically".

The way that this is recommended is:
- Upload the packages to a secondary Artifactory repo, directly from the builders
- When all builders finish, run a promotion, calling the api to copy packages from the secondary repo to the main repo. This operation is way more atomic than any other alternative, as Artifactory has de-duplication of files, so no actual copy happens, only creating of DB entries.

Said that, I think that we might still want to try to make all paths forward slashes, not backward, if possible, for all OSs. It might be challenging, as it would require a migration, but let's have a look.

**Comment by s-ker-s** [comment]
Hi @memsharded, thanks for the feedback! I'll think about the secondary Artifactory repo approach; I thought it would have been nice to keep all artifacts within the pipeline until all tests have passed. It may also be difficult to avoid interactions between jobs of interdependent libraries using a single repo. Using a separate secondary repo per project seems workable but includes a lot of infrastructure overhead.

> When all builders finish, run a promotion, calling the api to copy packages from the secondary repo to the main repo. This operation is way more atomic than any other alternative, as Artifactory has de-duplication of files, so no actual copy happens, only creating of DB entries.

Do you mean running a promotion using Artifactory's API? Do you have more information about that workflow? We've been promoting packages using the Conan CLI in the past.

**Comment by memsharded** [comment]
>  I'll think about the secondary Artifactory repo approach; I thought it would have been nice to keep all artifacts within the pipeline until all tests have passed. 

We are also investigating a possible CI flow doing local copy of packages in https://github.com/conan-io/conan/pull/14923, but this sounds a bit trickier than just uploading the packages to the server. In any case, probably interesting to keep an eye on that feature.

The server "build" repo has some other further advantages, for example when building a full product (that means, building also consumers of the current package, to check if something breaks) pipeline in a distributed server farm, it becomes necessary to cache the so-far built packages somewhere, and this "build" repo is the best approach to achieve that.

> Using a separate secondary repo per project seems workable but includes a lot of infrastructure overhead.

Not really a secondary repo per project, but just a secondary "build" repo for all projects.
With package-lists, for example, it is possible to track which packages have been uploaded to it, so the promotion can be done just for those packages, not everything in the repo.

> Do you mean running a promotion using Artifactory's API? Do you have more information about that workflow? We've been promoting packages using the Conan CLI in the past.

Yes, exactly. The problem with doing it via Conan CLI is that it can be much slower, less atomic, and also more resource intensive on bandwidth, etc, while the server side is cheaper.

We have been working in some of the native mechanisms for promotions like buildInfo and ReleaseBundle in the extensions repo: https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art.

We haven't started it yet, but it is possible that we will also do a custom extension command for doing a promotion based on native Conan package-lists. The API is basically a "copy" one, but it might need some deeper knowledge of the mapping between Conan references and server paths.

**Comment by s-ker-s** [comment]
> Not really a secondary repo per project, but just a secondary "build" repo for all projects.

Right, IIUC this "build" repo would only be written to by pipelines but not be read from as a Conan remote in concurrent builds, correct?

**Comment by memsharded** [comment]
> Right, IIUC this "build" repo would only be written to by pipelines but not be read from as a Conan remote in concurrent builds, correct?

It can be written by the package pipelines (the one building the packages), and it can be read by product pipelines (if you are building some downstream consumer to test in your pipeline if your new package will break some of your end products), but yes, it will not be read by developers (unless they want to explicitly activate it to debug something) nor by other package pipelines. 

Sorry, I am aware that the documentation for this is still pending, it is in our TODO-list, but we didn't manage yet to find some time to do it :(

**Comment by memsharded** [comment]
I am trying to make paths uniform in https://github.com/conan-io/conan/pull/14940

It seems it wouldn't be breaking, because paths are not compared in the DB, so caches can keep working with the legacy backwards slash, and new packages will use new forward slash.

I think running a migration over the DB to force update the slashes could be a bit riskier than not doing it at this moment. If users want to have the clean new behavior, it would be necessary to remove the full cache, wdyt?

**Comment by memsharded** [comment]
You might also be interested in this new PR: https://github.com/conan-io/conan/pull/14923, as this is related to CI flows like the one you describe.

**Comment by s-ker-s** [comment]
> I am trying to make paths uniform in #14940

Great, thanks!

> I think running a migration over the DB to force update the slashes could be a bit riskier than not doing it at this moment. If users want to have the clean new behavior, it would be necessary to remove the full cache, wdyt?

Yes, I think that's perfectly fine.

**Comment by s-ker-s** [comment]
> You might also be interested in this new PR: #14923, as this is related to CI flows like the one you describe.

Thanks, I'll monitor updates to that PR, this could be perfect for our workflow.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/14940 for next 2.0.14
