### ISSUE TITLE
`self.conf.append` changes global state

### ISSUE THREAD

**Issue by BobIsOnFire** [conan-io/conan#14931]
### Environment details

* Operating System+version: Oracle Linux 8
* Compiler+version: gcc 8.2
* Conan version: 2.0.13
* Python version: 3.6

### Steps to reproduce

1. Create `my_profile` profile, add a new conf in it:

```
[conf]
user.config:data = ["first", "second", "third"]
```

2. Create two packages `pkga` and `pkgb`, add following code to `generate()` methods:

`pkga/conanfile.py`:

```py
    def generate(self):
        self.conf.append("user.config:data", "forth")
        print(self.conf.get("user.config:data"))
```

`pkgb/conanfile.py`:

```py
    def generate(self):
        print(self.conf.get("user.config:data"))
```

3. Export and build packages together:

```bash
$ conan export pkga/ --version=0.1
$ conan export pkgb/ --version=0.1
$ conan install --requires=pkga/0.1 --requires=pkgb/0.1 --build=missing --profile=my_profile
```

Note that Conan should build `pkga` before `pkgb` for the bug to reproduce.

### Logs

**Expected**: `print()` from `pkga` shows `["first", "second", "third", "forth"]`; from `pkgb`: `["first", "second", "third"]`

**Actual**: both `print()`s show `["first", "second", "third", "forth"]`.

Doesn't reproduce if I build packages one-by-one, build order is changed, or if `pkga` is taken from binary cache.

My motivation — I want to be able to alter compile/link flags for selected packages without changing their build systems (e.g. suppressing annoying compiler warnings).

**Comment by memsharded** [comment]
Hi @BobIsOnFire 

Thanks for your report.
I think that this falls under the documented undefined behavior of https://docs.conan.io/2/knowledge/guidelines.html#forbidden-practices

> Settings and configuration (conf) are read-only in recipes

It might be worth having a look and trying to improve this and make it more robust, but in any case this shouldn't be done in the first place.

> My motivation — I want to be able to alter compile/link flags for selected packages without changing their build systems (e.g. suppressing annoying compiler warnings).

This shouldn't be done by locally modifying the ``conf``,  but probably via the build system.

**Comment by BobIsOnFire** [comment]
Hi @memsharded, thanks for such a quick reply!

I guess I got into forbidden territory… I kind of thought that this is possible. Even my IDE suggests to me that `self.conf.append` method exists :)

So, looks like I need to write some patches to apply to build systems during the build, for that matter. Thanks again!

**Comment by memsharded** [comment]
I am proposing https://github.com/conan-io/conan/pull/14932 that at least would avoid that such a change affect other recipes, as a minimal isolation.

Note that it is possible that we might restrict in the future this ``self.conf.append()`` by constraining ``self.conf`` interface, precisely to avoid that kind of IDE suggestions beyond the documented public API, as this is already documented as UB, so still seems that using another approach might be better. Maybe it doesn't need to be a full patch, but the build system integrations could help doing this without really needing patches, this could be a separate discussion.

**Comment by BobIsOnFire** [comment]
Sounds great, some read-only wrapper for `self.conf` would definitely help in enforcing immutability.

**Comment by BobIsOnFire** [comment]
I think it would also help to mention about `self.conf` immutability in the reference https://docs.conan.io/2/reference/conanfile/attributes.html#conf, what do you think?

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/14932, the PR docs will mention that in the docs, thanks!
