### ISSUE TITLE
[bug] conan 1.x breaks with python 3.12

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#14936]
### Environment details

* Operating System+version: Windows 11
* Conan version: 1.61
* Python version: 3.12

### Steps to reproduce

run `conan --version`

get:
```
ModuleNotFoundError: No module named 'imp'
```
`imp` was removed in Python 3.12. It is imported here: https://github.com/conan-io/conan/blob/a82ae09c622f0cfbf2e43b093e7409ae384edf54/conans/client/loader.py#L2C9-L2C9

**Comment by AbrilRBS** [comment]
Hi @rconde01 thanks a lot for your report.
This has already been fixed for 1.62, to be released some time soon

We're not 100% sure that it won't introduce some unexpected behavioural difference for Python 3.12 users, so feel free to report such cases should they happen! Thanks :)

**Comment by cajus** [comment]
@RubenRBS any idea when 1.62 will be there? Currently v1 is not usable in Fedora 39, and installing without pip is a bit unhandy. Thanks!

**Comment by franramirez688** [comment]
Hi @cajus, we're going to release it this coming week. Hopefully Monday or Tuesday 😀
