### ISSUE TITLE
[question] Error: It's not possible to compose str values and list ones.

### ISSUE THREAD

**Issue by AlexanderSerov** [conan-io/conan#14952]
### What is your question?

**Setup:**
conan version 2.0.13
platform: Mac OS X 10.15

**conan profile ios_13_4:**
```
[settings]
arch=armv8
os=iOS
os.version=13.4
os.sdk_version=13.4
os.sdk=iphoneos
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0

[conf]
tools.cmake.cmaketoolchain:user_toolchain=["/Users/visionlabs/polly-cmake-toolchains/ios-13-4-dep-11-0-arm64-bitcode-dev.cmake"]
tools.cmake.cmaketoolchain:generator="Xcode"
```

**Command:**
`conan install --requires=zlib/1.2.13 -pr ios_13_4 -c tools.cmake.cmaketoolchain:user_toolchain=/User/admin/SomePath`

**Error:**
`It's not possible to compose str values and list ones.`

**Goal:**
We build several conan packages locally and we share common profiles for all of them. This work good enough so far. But now for one of the package we need update `user_toolchain` config because we need to use custom toolchain for one of the packages. The intention we have is use old profile but update `user_toolchain `option via CLI. On the surface I was expected CLI have more priority over profile setting and profile have more priority over `global.conf`. This logic implemented for [example in pip](https://pip.pypa.io/en/stable/topics/configuration/#precedence-override-order). Although conan [documentation states](https://docs.conan.io/2.0/reference/config_files/global_conf.html#:~:text=Profiles%20values%20will%20have%20priority%20over%20globally%20defined%20ones%20in%20global.conf.) only about profile values precedence over global.conf values. Can we expect CLI options precedence over profile options too?
**Reasoning:**
Looks like error message said it can't assign user_toolchain to string from CLI because it already assigned to List type from profile first. [Associated code](https://github.com/conan-io/conan/blob/c271142d97da309ad9d6f512ca0a31d199fdb229/conans/model/conf.py#L239) 
**Workaround:**
For now we create a wrapper profile in which we modify desired setting:
ios_13_4_custom
```
include(ios_13_4)

[conf]
tools.cmake.cmaketoolchain:user_toolchain=["/User/admin/SomePath"]
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @AlexanderSerov 

If I understood your use case, I think the problem is that you need to enter that conf as a list too:

```bash
$ conan install --requires=zlib/1.2.13 -pr ios_13_4 -c "tools.cmake.cmaketoolchain:user_toolchain=['/User/admin/SomePath']"
```
This should work, and, yes, CLI options have precedence over profile options too.

**Comment by AlexanderSerov** [comment]
Hello @franramirez688 
Thank you for the help, it works
Previously I tried to use double quotes instead of single quotes in you command and I was hard to find example of how to pass list right. Hope this answer will help someone too
