### ISSUE TITLE
[bug] Unable to cross-build openssl/3.1.3

### ISSUE THREAD

**Issue by spakarl** [conan-io/conan#14963]
### Environment details

* Operating System+version: Ubuntu 20.04.6 LTS
* Compiler+version:gcc-arm-linux-gnueabihf version 9
* Conan version: 1.61.0
* Python version: 3.11.1

[installed-packages.txt](https://github.com/conan-io/conan/files/13025349/installed-packages.txt)

### Steps to reproduce

conan install openssl.txt --build=missing -pr:h=armv7hf-gcc9 -pr:b=gcc9

[openssl.txt](https://github.com/conan-io/conan/files/13025484/openssl.txt)
[gcc9.txt](https://github.com/conan-io/conan/files/13025492/gcc9.txt)
[armv7hf-gcc9.txt](https://github.com/conan-io/conan/files/13025493/armv7hf-gcc9.txt)

I guess the recipe is looking in the wrong folder for the file "Configure"

### Logs

ERROR: openssl/3.1.3: Error in build() method, line 520
	self._make()
while calling '_make', line 508
	self.run("{perl} ./Configure {args}".format(perl=self._perl, args=args), env="conanbuild")
	ConanException: Error 127 while executing perl ./Configure "conan-Release-Linux-armv7hf-gcc-9" no-shared --prefix=/ --libdir=lib --openssldir="/etc/ssl" no-unit-test threads PERL=perl no-tests --release -fPIC enable-fips no-md2 zlib --with-zlib-include="/home/buildagent/.conan/data/zlib/1.2.13/_/_/package/79a936a2eb2adfcb385f34406a4eb2396b702027/include" --with-zlib-lib="/home/buildagent/.conan/data/zlib/1.2.13/_/_/package/79a936a2eb2adfcb385f34406a4eb2396b702027/lib"

[build.log](https://github.com/conan-io/conan/files/13025504/build.log)

**Comment by memsharded** [comment]
I am trying to reproduce this:

- Using Conan gcc1 docker image
- Installed cross-compilers
- Used following profile:
 ```
[settings]
os=Linux
arch=armv7hf
compiler=gcc
compiler.version=9
compiler.cppstd=17
compiler.libcxx=libstdc++11
build_type=Release


[buildenv]
CC=arm-linux-gnueabihf-gcc
CXX=arm-linux-gnueabihf-g++
LD=arm-linux-gnueabihf-ld
CCLD=arm-linux-gnueabihf-ld
```
Going to ``conan-center-index/recipes/openssl/3.X.X``
And 
```bash
$ conan create . --version=3.1.3 -pr=armprofile.txt --build=missing
```
And it builds correctly. 
I still need to test this in latest Conan 1.X

**Comment by memsharded** [comment]
I have tested in in Conan 1.61.
Adding this in the profile:
```
[env]
CC=arm-linux-gnueabihf-gcc-9
CXX=arm-linux-gnueabihf-g++-9
LD=arm-linux-gnueabihf-ld
CCLD=arm-linux-gnueabihf-ld
```
it works fine, cross compiled correctly.

**Comment by memsharded** [comment]
Maybe your Ubuntu doesn't have ``perl``? The docker image I am using is also 20.04 LTS based.

**Comment by memsharded** [comment]
This seems duplicated to https://github.com/conan-io/conan-center-index/issues/20637?

Please, lets close one of the tickets, probably this one, and follow up just on one. The duplication made use duplicate our efforts.

**Comment by spakarl** [comment]
> This seems duplicated to [conan-io/conan-center-index#20637](https://github.com/conan-io/conan-center-index/issues/20637)?
> 
> Please, lets close one of the tickets, probably this one, and follow up just on one. The duplication made use duplicate our efforts.

Sorry, I didn't understand that there are two repos. I just missed the issue that I created before and thought I didn't save it correctly. But instead it was moved to the other repo.

**Comment by franramirez688** [comment]
Superseded by https://github.com/conan-io/conan-center-index/issues/20637

**Comment by memsharded** [comment]
Don't worry @spakarl 🙂 not a problem, I didn't realized that it was us that we moved the ticket to the other repo.

Lets follow up in the https://github.com/conan-io/conan-center-index/issues/20637
