### ISSUE TITLE
[question] Different build folders & cross compilation

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14965]
### What is your question?

Hello !

I am trying to cross compile from Linux to Windows using the tools provided here : https://github.com/mstorsjo/llvm-mingw/releases

I have a simple goal. I would like to have separate build folders, with each containing the desired architecture's results.

My `layout()` method looks like this:
```python
def layout(self):
	bf = f"build-{self.settings.os}-{self.settings.compiler}{self.settings.compiler.version}-{self.settings.arch}".lower()
	cmake_layout(self, build_folder=bf)
```

But whenever I try to compile from linux to windows using the command : `conan build . --build=missing -pr windows-clang16-x86_64 -pr:b linux-clang16-x86_64`, `a.exe` goes into the folder called `build-linux-clang16-x86_64`.

This causes an issue if I try to build its linux equivalent straight away with `conan build . --build=missing -pr linux-clang16-x86_64 -pr:b linux-clang16-x86_64`, because it still generates `a.exe` instead of `a.out`

My guess is that having a seperate `build-windows-clang16-x86_64` folder containing `a.exe` could fix the issue.

However, I don't know if there is a way to access the info of the host profile within recipes, as `self.settings.X` only returns info of the build profile.

Could you please guide me to a better solution? Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

I think that you are interested in the ``build_folder_vars``:
```python
def layout(self):
     self.folders.build_folder_vars = ["settings.os", "settings.arch", "options.shared"]
```
This will automatically manage to have different folders for different architectures

You can find hints for it in:
- https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html?highlight=build_folder_vars#generated-files
- https://docs.conan.io/2/reference/conanfile/methods/layout.html#self-folders

Please try that and let us know.

**Comment by Todiq** [comment]
Hello @memsharded,

There was a mistake in my Windows profile, which was the main issue. Fixing it then applying your fix to my conanfile gave me the expected result. Thanks a lot!
