### ISSUE TITLE
SystemPackageTool support for FreeBSD

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1496]
Hi!

`SystemPackageTool` is a great helper for build requirements, however, for now it supports only `apt-get`, `yum` and `brew`. Would be nice if it supports `pkg` also.

This feature request is simple, so I could help.

(Maybe in the future, `chocolatey` could be an option for Windows)

**Comment by lasote** [comment]
Sure, it can be improved and always well welcome ;)

**Comment by memsharded** [comment]
This was implemented in https://github.com/conan-io/conan/pull/1502.
