### ISSUE TITLE
Consider to remove the enforcement of having compiler.runtime on conan.conf

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#1497]
After spending some time modernising some conan recipes I felt in the same situation that is described in this issue:
https://github.com/conan-io/conan/issues/475

From my point of view, the fact of enforcing to have `compiler.runtime` in the `conan.conf` file is causing this situation.

There are some statements in that thread that are relevant for what I am going to propose:
- "Conan does not enforce any linkage with /MD or /MT and matching d debug options."
- "The setting can be also defaulted in the conan.conf file" <-- We do not have the option of doing it ... it **MUST** be defaulted, and I think this is the problem.
- "One general policy for conan is not to automatically decide or interfere with user configuration. So conan will never decide to use MDd because the build_type is debug, it has to be explicitly defined by the user."

I think it is good to have the change of passing the RUNTIME to different generators (CMake) through conan but many libraries already take care of this in their configuration. For example, I think that CMake will use /MD or /MDd by default depending on the CMAKE_BUILD_TYPE. 

My proposal is to remove the enforcement of having `compiler.runtime` in the `conan.conf` file.

Note that this other issue is also related with this topic:
https://github.com/conan-io/conan/issues/681

**Comment by memsharded** [comment]
I think this is reasonable, and we should consider it for 0.26.

**Comment by memsharded** [comment]
If https://github.com/conan-io/conan/pull/1565 moves forward, this settings pre-process should probably manage ``emcc`` too.
