### ISSUE TITLE
[question] Using Conan to create and share packages without generating binaries

### ISSUE THREAD

**Issue by Tricksam** [conan-io/conan#14976]
### What is your question?

Hi,
despite of the usual use of Conan we are using Conan to share files which were already compiled/build by our build automation or sometimes just a certain set of model files to be consumed as conan package. 
Previously this was possible with Conan V1.x as we copied the files when generating a package to the cache, uploaded them to artifactory and consumed them via [imports] in the conanfile.txt.
Now with Conan V2.x I managed to do the same for generating and uploading the packages. When trying to consume the package by using conan install, I found that [imports] seems to be obsolete. Beside of that it seems that the install API mandatory searches for some binaries or at least wants to build the binaries to run a successful installation of a package.

Is there a way to handle the described use case?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tricksam 

Thanks for your question.

> Previously this was possible with Conan V1.x as we copied the files when generating a package to the cache, uploaded them to artifactory and consumed them via [imports] in the conanfile.txt.

Yes, Conan 2.0 has some new ways to do the equivalent to ``imports``.
The more explicit, recipe approach, would be to call ``copy()`` in the ``generate()`` method of a ``conanfile.py`` that iterates all the dependencies via ``self.dependencies``.

But there are better ways. Conan 2.0 introduced the concept of "deployers", to do a copy of the files from Conan packages to the user folders. What is more interesting is that generated files, like those from ``CMakeDeps`` can point to the user folder, not to the cache. I'd suggest having a look at https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html and to the ``deployers`` documentation.


> Beside of that it seems that the install API mandatory searches for some binaries or at least wants to build the binaries to run a successful installation of a package.

This issue I don't understand, if you could please clarify.

**Comment by memsharded** [comment]
Hi @Tricksam 

Any follow up here or any further question? Maybe we can close this ticket as responded?
