### ISSUE TITLE
How to have the dependencies on an offline artifactory ?

### ISSUE THREAD

**Issue by juju773** [conan-io/conan#14975]
### What is your question?

Hello,
I'm starting on artifactory and conan. I would like to use some c++ library like asio, boost, mongo... on a network not connected to the internet (offline).
I instantiated an artifactory on this network. How can I get the sources, package them and send them to my offline artifactory?
I have access to a network with internet from where I can draw the sources of the library.

**Comment by AbrilRBS** [comment]
Hi @juju773 thanks a lot for your question, I'm moving it to the main Conan repo as it probably fits better there :)

**Comment by memsharded** [comment]
Hi @juju773 

Thanks for your question. 
There are a few approaches to populate your own private server:

- Download them from ConanCenter, like you do your ``conan install ... -r=conancenter`` to install your dependencies (repeating for your multiple configurations), and then upload them to your own server ``conan upload * -r=myremote -c``. This assumes that there are pre-compiled binaries that work fine for you in ConanCenter
- Download the recipes from ConanCenter, but force to build your own binaries, with ``conan install ... -r=conancenter --build="*"``, and then ``conan upload`` them too.
- Build your own binaries from the source recipes:
   - Fork ``conan-center-index`` repo
   - Create a list of the packages you use from ConanCenter
   - Do a script that iterates the packages and do a ``conan create`` them to build them from the source recipes
   - ``conan upload`` the packages to your own remote

You might want to have a look to https://docs.conan.io/2/devops/using_conancenter.html, depending on the business need (robustness, isolation, reproducibility, etc), you might want to go for one approach or the other. Typically the last one, building from the fork is a good approach, it requires a bit of extra effort, but the level of control is total.

Please let me know if this helps, or you have any further questions.

**Comment by memsharded** [comment]
As a note, it is possible to do "bulk" upload operations for a specific list of packages with the "packages list" feature, have a look in https://blog.conan.io/2023/06/28/Conan-bulk-package-operations.html if you want to know more about it.

**Comment by juju773** [comment]
Hello,
Thanks for your help, thanks to the information you gave me, I have actually managed to show the dependencies on my offline server.

**Comment by memsharded** [comment]
Good! Thanks for your feedback!
