### ISSUE TITLE
[bug] Potential bug in CMakeDeps

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#14978]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: Visual Studio 2022
* Conan version: 2.0.13
* Python version: 3.11.5

### Steps to reproduce

See https://github.com/conan-io/conan-center-index/issues/20553

I really don't know if this is a CMakeDeps bug, but I know conan bugs and recipe bugs are treated differently so I wanted to ensure it was examined with this lens. If it really is a recipe bug, then just close this.

**Comment by memsharded** [comment]
Hi @rconde01 

I have had a look.
It seems a recipe issue. The ``assimp`` build ``CMakeLists.txt`` is quite complicated, and it sets ``set(ZLIB_FOUND TRUE)`` in a couple of places. This avoids the transitive ``find_dependency()`` to execute (the minizip find_package() do not run the dependency to find ZLIB), and things fail.

I am further investigating why ``assimp`` has the ZLIB_FOUND to True in that point, still not clear...

**Comment by memsharded** [comment]
Changing one option to:
```
assimp/*:with_assbin_exporter=True
```
The related code seems to be (in project CMakeLists.txt):
```
  IF ( NOT ASSIMP_BUILD_ZLIB )
    if(ASSIMP_BUILD_ASSBIN_IMPORTER OR ASSIMP_BUILD_ASSBIN_EXPORTER OR ASSIMP_BUILD_ASSXML_EXPORTER OR
       ASSIMP_BUILD_BLEND_IMPORTER OR ASSIMP_BUILD_FBX_IMPORTER OR ASSIMP_BUILD_Q3BSP_IMPORTER OR
       ASSIMP_BUILD_X_IMPORTER OR ASSIMP_BUILD_XGL_IMPORTER)
        find_package(ZLIB REQUIRED)
    endif()
    set(ZLIB_FOUND TRUE)
  ENDIF()
```
This avoids the ``find_package()`` but still sets ``ZLIB_FOUND``. That sounds quite buggy in the build system CMakeLists.txtç, and should be fixed in the recipe. I am closing this in favor of https://github.com/conan-io/conan-center-index/issues/20553
