### ISSUE TITLE
How to provide refs for upload with Conan 2.0 python API

### ISSUE THREAD

**Issue by Tricksam** [conan-io/conan#14971]
### What is your question?

When trying to run the upload from UploadAPI it requests a package_list. A simple package string like known from the cli, e.g. conan upload test/1.3.5, is not sufficient.
However I struggle in finding the way to get a package_list in the form the upload from Upload API is requesting.
Can you tell me how to generate the requested package_list?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @Tricksam, thanks a lot for your question. When interacting with the api, it's usually useful to check how the built in commands handle their calls, as they are written with being able to serve as the base for custom commands/api usage in mind.

For this case, this is how the `conan upload` command does it in lines [93-94](https://github.com/conan-io/conan/blob/release/2.0/conan/cli/commands/upload.py#L93):
```py
ref_pattern = ListPattern(args.pattern, package_id="*", only_recipe=args.only_recipe)
package_list = conan_api.list.select(ref_pattern, package_query=args.package_query)
```

I hope this helps! Documentation for the API is something we are working towards, so please feel free to ask should you have any other questions regarding its usage :)

**Comment by Tricksam** [comment]
Thank you @RubenRBS this helped me to get one step closer to finalising the commands via API.
Looking forward to the Documentation of the API.
