### ISSUE TITLE
[question] Handling custom build types and build-type specific dependencies in conan v2.0

### ISSUE THREAD

**Issue by phil-chp** [conan-io/conan#14972]
### What is your question?

I have been working with Conan v2.0 and have encountered issues in managing custom build types, particularly when integrated with CMake. My project requires a custom build type named `Tests`, which essentially is a Debug build with additional coverage flags:
```cmake
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} -g3 -O0 -W -Wall -Wextra")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -g0 -O3")
set(CMAKE_CXX_FLAGS_TESTS "${CMAKE_CXX_FLAGS} -g3 -O0 -fprofile-arcs -ftest-coverage")
```

In Conan, dependencies are packaged for the defined `build_type` in the Conan profile. For CMake to find the dependencies it needs to have the matching `-DCMAKE_BUILD_TYPE=` (i.e. `build_type=Release` and ``-DCMAKE_BUILD_TYPE=Release`).

I have two ideas in mind that I've explored but haven't managed to get working:

1. Is there a way to extend create a custom build_type for conan, allowing "Tests" to be a valid term.
2. Alternatively, is there a way to avoid `build_type`-specific dependency paths in Conan, so that dependencies are accessible regardless of the build_type specified in CMake?
	- I have tried overriding the `build_type` in the profile config using an environment variable (i.e. `build_type={{ os.getenv("CONAN_BUILD_TYPE") }}`), but this feels like a workaround rather than a clean solution.

Any guidance on handling custom build types and ensuring correct dependency resolution in Conan v2.0 would be greatly appreciated.\
Thank you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @Philippe-cheype thanks a lot for your question. There's always a lot more to be said about this topic, but for starters:
> Is there a way to extend create a custom build_type for conan, allowing "Tests" to be a valid term.

Did you get a chance to read about [settings_user.yml in the docs](https://docs.conan.io/2/examples/config_files/settings/settings_user.html)? Seems to be the feature you might be asking for in here :)

**Comment by phil-chp** [comment]
Thank you for your quick reply! My bad I though settings.yml was v1.0 specific. I've looked into it, edited my settings like so:
`settings_user.yml`
```
build_type: [null, Debug, Release, Tests]
```

I ended up removing build_types that I don't use and added Tests instead. This worked, and conan started packaging all the dependencies for the `build_type=Tests`, and when it got to `libarchive/3.6.2` it broke. That library is configures in a way that doesn't understand what Tests is it seems.

For reference:
```py
from conan import ConanFile

class ImageProcessing(ConanFile):
    name = "ImageProcessing"
    version = "1.0"
    test_requires = [
        "catch2/3.4.0"
    ]
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def layout(self):
        self.folders.build = "build/conan/"

    def requirements(self):
        self.requires("leptonica/1.82.0")
        self.requires("tesseract/5.3.0")
        self.requires("opencv/4.5.5")
        self.requires("libtiff/4.6.0", override=True)
```

Is this a ConanCenter issue now?

<details>
<summary>libarchive/3.6.2 error logs</summary>

```
-------- Installing package libarchive/3.6.2 (31 of 50) --------
libarchive/3.6.2: Building from source
libarchive/3.6.2: Package libarchive/3.6.2:2090c4fd596ab0cdc0f6d71dc95dc16ce0a37fe8
libarchive/3.6.2: Copying sources to build folder
libarchive/3.6.2: Building your package in /Users/phil/.conan2/p/b/libarb7013a1817cba/b
libarchive/3.6.2: Calling generate()
libarchive/3.6.2: Generators folder: /Users/phil/.conan2/p/b/libarb7013a1817cba/b/build/Tests/generators
libarchive/3.6.2: CMakeToolchain generated: conan_toolchain.cmake
libarchive/3.6.2: CMakeToolchain generated: CMakePresets.json
libarchive/3.6.2: CMakeToolchain generated: ../../../src/CMakeUserPresets.json
libarchive/3.6.2: Generating aggregated env files
libarchive/3.6.2: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
libarchive/3.6.2: Calling build()
libarchive/3.6.2: Apply patch (portability): Remove broken ZLIB WINAPI check
libarchive/3.6.2: Apply patch (conan): Make CMake build-system compatible with Conan
libarchive/3.6.2: Apply patch (conan): Patch try_compile check to work with imported CMake targets from Conan packages
libarchive/3.6.2: Apply patch (conan): Fix MSVC build
libarchive/3.6.2: Running CMake.configure()
libarchive/3.6.2: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/Users/phil/.conan2/p/b/libarb7013a1817cba/b/build/Tests/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/phil/.conan2/p/b/libarb7013a1817cba/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Tests" "/Users/phil/.conan2/p/b/libarb7013a1817cba/b/src"
CMake Deprecation Warning at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Using Conan toolchain: /Users/phil/.conan2/p/b/libarb7013a1817cba/b/build/Tests/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:35 (MESSAGE):
  Unknown keyword for CMAKE_BUILD_TYPE: Tests

  Acceptable keywords: Debug,Release,RelWithDebInfo,MinSizeRel


-- Configuring incomplete, errors occurred!

libarchive/3.6.2: ERROR:
Package '2090c4fd596ab0cdc0f6d71dc95dc16ce0a37fe8' build failed
libarchive/3.6.2: WARN: Build folder /Users/phil/.conan2/p/b/libarb7013a1817cba/b/build/Tests
*********************************************************
Recipe 'libarchive/3.6.2' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: libarchive/3.6.2: Error in build() method, line 165
	cmake.configure()
	ConanException: Error 1 while executing
```

</details>

**Comment by phil-chp** [comment]
Okay I found a dumb work-around, my Tests are now called "RelWithDebugInfo"...

**Comment by memsharded** [comment]
Some other comments:

- Custom configs can be defined in settings, but yes, it is expected that dependencies will not understand these custom configurations, that might work only when you have full control. It might be possible to add information to dependencies, for example, via injection of toolchain files: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/inject_cmake_variables.html
- It is possible to mix dependencies settings, for example ``-s build_type=Debug -s mypkg/*:build_type=Tests`` (that can be done in profiles too.
- It might be possible to define ``compatibility.py`` fallbacks, like falling back to build_type=Debug when ``build_type=Tests`` but the binary for that build type is missing

I hope your workaround is good enough, but if not, please don't hesitate to create new ticket for any further question.
