### ISSUE TITLE
[bug] MesonToolchain does not handle tools.build:sysroot

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#14987]
### What is your suggestion?

The `tools.build:sysroot` conf variable is not used by the MesonToolchain. A `--sysroot` compiler flag should be added to the compiler and linker flags. Additionally, Meson has a `sys_root` cross file property that should be defined by the MesonToolchain for locating pkg-config files. This variable is documented [here](https://mesonbuild.com/Cross-compilation.html#properties).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @jwillikers 

Yes, you're completely right. We should be managing that variable. Thanks for reporting it!

**Comment by franramirez688** [comment]
For the record, this issue seems to be related: https://github.com/conan-io/conan/issues/15795
