### ISSUE TITLE
Retriving a specific package_folger

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#14983]
### What is your question?

Hi, when I create a package with Conan 2.0, the console shows the `package_folder` storing the final packaged artifacts.

But how can I retrieve the same path at a later point in time? I have tried `conan graph info` but that will only show `recipe_folder` while package folder is null.

I understand that in order to retrieve a `package_folder` path I would need to provide Conan not only with name, version but also settings and options that were used to create that package.

What is the command (if any) to get this information at any time?

Thanks in advance,
Luca

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lucabarbiero 

The ways to retrieve the package_folder in 2.0 are:

- ``conan install .... --format=json``. The ``conan graph info`` does not really install packages, so the package-folder can be None
- ``conan cache path pkg/version:package_id``. Check the ``conan cache path`` command

Please let me know if this helps.

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
