### ISSUE TITLE
[feature] Running test() method without build

### ISSUE THREAD

**Issue by xakod** [conan-io/conan#14989]
### What is your suggestion?

Hi, I think my issue relates #1629

> So it will just run the test(), without building the consumer project inside test_package folder?What would be the use case?

Yep, it's my case. Sometimes you need to run test executable with a lot of arguments. It's much be easier to debug such cases without rebuild _test_package_. It's very annoying for me because rebuilding _test_package_ takes ~5 minutes.
Maybe it would be great to something like old flag for ```create()``` method ```--keep-build```. I do not understand why this flag was removed in v2.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
> Yep, it's my case. Sometimes you need to run test executable with a lot of arguments. It's much be easier to debug such cases without rebuild test_package. It's very annoying for me because rebuilding test_package takes ~5 minutes.

I'd say that you are going beyond the intent and scope of test_package. If ``test_package`` takes 5 minutes to build, that is not expected. ``test_package`` is not intended to run a full test suite for the package, just to test that the package is correctly formed, it contains the necessary files, and as such it should be fast.

> Maybe it would be great to something like old flag for create() method --keep-build. I do not understand why this flag was removed in v2.

It was removed, because for these flows, using ``conan`` command is not recommended, but instead using native build commands, that is, calling ``cmake ...`` for example, instead of running ``conan``. All the changes with the new ``CMakeToolchain`` and ``generate()`` flows in general is intended to achieve transparency and being able to call the build system directly.

**Comment by xakod** [comment]
> I'd say that you are going beyond the intent and scope of test_package. If `test_package` takes 5 minutes to build, that is not expected. `test_package` is not intended to run a full test suite for the package, just to test that the package is correctly formed, it contains the necessary files, and as such it should be fast.

I mean my build takes 5 minutes only for test_package

> It was removed, because for these flows, using `conan` command is not recommended, but instead using native build commands, that is, calling `cmake ...` for example, instead of running `conan`. All the changes with the new `CMakeToolchain` and `generate()` flows in general is intended to achieve transparency and being able to call the build system directly.

Ok, I understand but for debugging `package() `method it was a nice helper

**Comment by memsharded** [comment]
> I mean my build takes 5 minutes only for test_package

Yes, this is too much. Building ``test_package`` should in general take less than a few seconds.

> Ok, I understand but for debugging package() method it was a nice helper

Debugging ``package()`` recommended way is running ``conan export-pkg`` (which also runs ``test_package`` automatically now, in the same way as ``conan create``)

**Comment by AbrilRBS** [comment]
Closing as solved with the proposed solution of running `conan export-pkg` as we didnt hear back from you in a while - feel free to reopen/create a new issue should you have any other quiestions, thanks!

**Comment by xakod** [comment]
@RubenRBS I'm not sure that it was solved. I need to test only package method without building and there is no solution

**Comment by memsharded** [comment]
If you are talking about the rebuilding of the package, a simple ``--build=missing`` will completely avoid building the package if it was already built, so ``conan create . --build=missing`` will only do the ``test_package`` part.

If the ``test_package`` part takes too long, that is not something expected. You can use ``user.myteam:avoid_test_build=False`` user confs to introduce them in the ``test_package`` recipe to control behavior if you want, like avoiding the ``build()`` inside ``test_package``, but this is not something that Conan will provide some built-in mechanism.
