### ISSUE TITLE
[feature] Custom installation path for conan install 

### ISSUE THREAD

**Issue by pgawro** [conan-io/conan#14996]
### What is your suggestion?

I think is good to have a **conan install --path <custom_path>** command to point elsewhere to install conan packages

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by pgawro** [comment]
Sorry I was not aware there is such command exist [-of OUTPUT_FOLDER] this is sufficient for me.

**Comment by memsharded** [comment]
Hi @pgawro 

Just in case, ``-of`` is the output folder of files generated by Conan, not for the packages themselves. The packages are installed in the Conan cache and used from there in the general case. For most cases, this is optimal, saves time, spaces, and guarantees there aren't collisions between versions or different binary configurations. If you still want to force to make an extra copy to the current project, you want to check https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html. But still, as I commented, not really recommended for normal usage.
