### ISSUE TITLE
[question] cannot remove just packages

### ISSUE THREAD

**Issue by thejohnfreeman** [conan-io/conan#14997]
### What is your question?

I want to remove packages but leave the recipe. I used to do this with Conan 1.x with this command:

```
conan remove --force ${reference} --packages
```

What is the translation to Conan 2?

I'm starting this off as a question and not a bug in case it's my misunderstanding. Here is the help string for the `--package-query` option of `conan remove` for Conan 2.0.13:

```
  -p PACKAGE_QUERY, --package-query PACKAGE_QUERY
                        Remove all packages (empty) or provide a
                        query: os=Windows AND (arch=x86 OR
                        compiler=gcc)
```

What does "Remove all packages (empty)" mean? I've interpreted "empty" to mean both "no argument" and "empty string argument", but both have led to errors:

```
# conan remove --confirm ${reference} --package-query
conan remove: error: argument -p/--package-query: expected one argument
ERROR: Exiting with code: 2
```

```
# conan remove --confirm ${reference} --package-query ''
ERROR: --package-query supplied but the pattern does not match packages
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @thejohnfreeman 

``conan remove pkg/version:*`` will remove the binaries of ``pkg/version`` (for all recipe revisions if not specified otherwise), but will leave the recipe there, not removing it.

It seems the docstring for ``Remove all packages (empty)`` should be clarified
