### ISSUE TITLE
[feature] set_ methods for metadata

### ISSUE THREAD

**Issue by thejohnfreeman** [conan-io/conan#14992]
### What is your suggestion?

Conan lets recipes compute [attributes](https://docs.conan.io/2.0/reference/conanfile/attributes.html) like the package name and version with `set_name()` and `set_version()`. The documentation even shows an [example](https://docs.conan.io/2.0/reference/conanfile/methods/set_version.html) of `set_version()` calling Git, which requires `self.recipe_folder` for an effective implementation, ruling out the possibility of defining the version as a property like this:

```python
@property
def version(self):
    # Cannot assume self.recipe_folder has a value here.
```

Are there any plans to add `set_` methods for the other metadata attributes like `license` or `url`, to let them leverage tools to reliably read the data from other source files in the package, relative to `self.recipe_folder`?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @thejohnfreeman 

Thanks for your suggestion.

Note that there is something very specific about the ``set_name()`` and ``set_version()`` methods.
They run exclusively at ``export`` time, when the recipe is being copied from user space to the cache. They will never run again, and the name and version from there will not be recovered, read again from files, but from the metadata (like the cache path or DB). The files containing the name and version does not even really need to be exported to the cache.

This is not the same for other fields like ``license`` that would still need to be loaded from the files when loaded from the cache. The ``init()`` method already documents this use case, please have a look to https://docs.conan.io/2/reference/conanfile/methods/init.html
