### ISSUE TITLE
[question] backup third-party source not done if the package already exists

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#15000]
### What is your question?

Hi,

I saw the docs for backing up third party sources: https://docs.conan.io/2/devops/backup_sources/sources_backup.html
Now the problem I have is that if the package already exists on artifactory but the sources are not backed up yet und you add the stuff mentioned in the docs, this is not detected and the backup is skipped.

Is this intended somehow? How can I backup the sources now for already created packages?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @tbsuht, thanks a lot for your question.
Indeed there currently is no built-in way to upload sources for already existing packages without recreating them.

You do raise a valid request in allowing for some kind of direct upload for existing packages, so Ill look into creating a custom command to do just that, will ping you once I have more info :)

**Comment by tbsuht** [comment]
@RubenRBS 

Is there no way to integrate this so that `conan upload` only skips the package but backups the sources?
As conan already creates checksums for the package it should be possible to detect that the package was indeed created from the sources which are now uploaded at a later point in time?

**Comment by AbrilRBS** [comment]
As with everything in programming, there's always a way, this is more about user expectations in the command rather than technical stoppers, so we are super grateful of you sharing yours!

**Comment by tbsuht** [comment]
One additional info which is related:

For the config `core.sources:upload_url` some sanity checks should be done. I tried the following two until I came to the working one.

`core.sources:upload_url=["https://myurl.com"]` fails with an exception because now list is allowed. I know this makes no sense but I copy&pasted the stuff from `core.sources:download_urls` which uses a list.

`core.sources:upload_url="https://myurl.com"` this fails with `ERROR: No connection adapters were found for...` because quotes are not allowed.

**Comment by memsharded** [comment]
Extra data point, from https://github.com/conan-io/conan-io.github.io/pull/258
```
# We added some metadata to the packages in the cache
# But those packages already exist in the server
$ conan upload "*" -c -r=myremote --metadata="*"
```
Can upload metadata even when the package is already in the server

**Comment by tbsuht** [comment]
@memsharded For clarification: is the source backup internally implemented as metadata of a package? So I can use this command to upload the sources retrospectively?

**Comment by samuel-emrys** [comment]
> You do raise a valid request in allowing for some kind of direct upload for existing packages, so Ill look into creating a custom command to do just that, will ping you once I have more info :)

For what it's worth, I would find the ability to manually backup using a source archive (without having to create a package) very useful - I'm not always going to be able to allow conan to download the sources from origin.

**Comment by memsharded** [comment]
> @memsharded For clarification: is the source backup internally implemented as metadata of a package? So I can use this command to upload the sources retrospectively?

No, the ``metadata`` is associated with every revision, and every package_id, stored in the Conan repo
The "backup-sources" is an orthogonal feature, it stores a common storage based on checksums. The same file can be used in multiple revisions for example.

**Comment by AbrilRBS** [comment]
Hi! From 2.0.14 onwards, you'll be able to use `conan cache backup-upload` to upload all the backups present in your local system, which will include those not associated with any package, or for packages that are already present in a remote server :)

**Comment by samuel-emrys** [comment]
I think I may have misunderstood what you were proposing @RubenRBS - would this allow me to `conan cache backup-upload boost-1.83.0.tar.gz boost/1.83.0` or similar? i.e., specify an archive and tag it with the appropriate reference manually?

**Comment by AbrilRBS** [comment]
No, this will allow you to upload all backups from your cache, regardless of whether they associated package is already present in your packages remotes or even if it exists (Picture doing a `conan source` for a package not yet uploaded to artifactory, this command would let you add the backups to the remote even in that case)
