### ISSUE TITLE
[bug] conan graph info with tools.build:download_source fails for editable packages

### ISSUE THREAD

**Issue by dezajno** [conan-io/conan#15003]
### Environment details

* Operating System+version: Ubuntu 20.04.6 LTS
* Compiler+version: not applicable
* Conan version: 2.0.13
* Python version: 3.8.10

### Steps to reproduce

1. Set up a conan project A
2. Set up a conan project B, with a dependency to A
3. Add A as an editable package using `conan editable add <path/to/A>`
4. Make sure `conan install ...` works as expected in project B, using A as an editable package
5. `conan graph info <path/to/B> --conf tools.build:download_source=True` --> Should succeed but fails

### Logs

`ERROR: Recipe '<recipe-of-A>' not found`

**Comment by memsharded** [comment]
Thanks very much @dezajno for your report.

Indeed there was a gap when both things happened. I am submitting https://github.com/conan-io/conan/pull/15004, so setting ``download_source=True`` conf will not make the command fail. Planned for next 2.0.14 release.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/15004 for next Conan 2.0.14
