### ISSUE TITLE
Conan + mod_wsgi = wrong password?

### ISSUE THREAD

**Issue by DarkMorford** [conan-io/conan#1500]
I'm trying to set up a Conan server running on Apache 2.4 with mod_wsgi for my team. I'm able to get the application to run (that is, if I `conan search` against it I get a valid "no packages" response), but I can't authenticate to upload anything.

I've created a `.conan_server` directory inside my www-data user's home (`/var/www`) and it contains a `server.conf` file and a `data` directory, both of which are owned and writable by www-data. The `server.conf` is a copy of the default one, with a demo:demo user account. Attempting to `conan upload` to this server just gets me an 'ERROR: Wrong password for user "demo"' message.

What's really confusing me is that if I stop Apache and run `sudo -u www-data conan_server`, I can upload using the demo account with no problem. If I then kill the conan_server process and restart Apache, `conan search` reveals the package I just uploaded. I can download and use it anonymously, but I'm once again unable to authenticate. This leads me to think that there's something wrong with my mod_wsgi configuration, but I'm not sure where to start; Apache's error log has been rather unhelpful in tracking this down. Any ideas?

**Comment by memsharded** [comment]
This is absolutely weird and puzzling. Honestly not idea of what could be happening, connection errors are more typical, but a wrong password, makes no sense. I guess a Linux server, right? Which distro and version? Also latest conan? Anyone else running Apache happened to deal with this issue?

**Comment by DarkMorford** [comment]
The server is 64-bit Xubuntu 16.04.2 running Apache 2.4.18 and Conan 0.24.0. Here's my Apache config file (with comments removed):

```
<VirtualHost *:9300>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	WSGIScriptAlias / /home/darkmorford/src/conan/conans/server/server_launcher.py
	WSGICallableObject app

	<Directory /home/darkmorford/src/conan/conans>
		Require all granted
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by memsharded** [comment]
My first trials configuring Apache for this failed. Maybe @lasote could have a look.
In the meantime, could you run the app with gunicorn to have it working while this issue can be investigated? Thanks!

**Comment by lasote** [comment]
I had a look but I was not able to even respond to a search... If you could provide us a docker image or server we can access with all configured we could debug it.

**Comment by DarkMorford** [comment]
This is my first time using Docker, so I'm not 100% sure I got everything right, but I think the `darkmorford/conan` image should illustrate the issue. Apache listens internally on port 80, so you'll need to run it with the `-p 9300:80` option for everything to match up correctly.

**Comment by lasote** [comment]
Hi, thanks so much, the image is ok and I'm able to reproduce the error. I'm investigating.

**Comment by lasote** [comment]
The problem is that Apache is intercepting the HTTP basic authentication requests, so you need to use the directive "WSGIPassAuthorization On" to pass it to conan:

```
<VirtualHost *:80>
	WSGIScriptAlias / /srv/conan/conans/server/server_launcher.py
	WSGICallableObject app
        WSGIPassAuthorization On

	<Directory /srv/conan/conans>
		Require all granted
	</Directory>
</VirtualHost>

```

Also, notice that the storage and the configuration are in the home of the Apache user, that's `/var/www/.conan_server`. If you want to change the user/pass edit the config in that directory.

We are going to document the Apache integration with mod_wsgi in the docs. Thanks!

**Comment by DarkMorford** [comment]
Interesting. Adding WSGIPassAuthorization seems to have done the trick, thanks!

Looking at the [mod_wsgi docs](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIPassAuthorization.html), it appears that it's also possible to let Apache handle the authentication (using one of its numerous mechanisms) and then pass the username to the script in an environment variable. Is this process supported by Conan? (This isn't necessary for my use case, just wondering if the option is there.)

**Comment by memsharded** [comment]
You might check: http://docs.conan.io/en/latest/server.html#authentication There is a plugin for using the htpasswd file, directly. Is that what you are looking for?

**Comment by DarkMorford** [comment]
Sort of. While the authenticator plugin system is nice, it still puts the burden of both authentication and authorization on the Conan script itself, and arguably would require reinventing the wheel if someone was using a different method supported by Apache. What I'm suggesting is allowing Apache to handle authentication and only performing authorization in the Conan script. (Again, I'm speaking in hypotheticals here; this is not specific to my needs.)

In particular, I'm referring to this section of the mod_wsgi documentation:
>If Apache is performing authorisation, a WSGI application can still find out what type of authorisation scheme was used by checking the variable AUTH_TYPE of the WSGI application environment. The login name of the authorised user can be determined by checking the variable REMOTE_USER.

For example, consider an organization that has a DBM file storing password information for a large number of users and uses Apache's mod_authn_dbm module to control access to all of their web-based tools. If this group wanted to set up a Conan server, they currently would need to either maintain a second password store (plaintext, htpasswd, etc.) or develop a custom authenticator plugin to access their existing DBM file. It would be more convenient if Conan had a mode in which it checked the environment's REMOTE_USER variable and used that (in combination with the access rules in `server.conf`) to determine whether to allow access. This would simplify integration by leveraging the authentication mechanism already in place and avoid needing to set the `WSGIPassAuthorization` option in the Apache configuration.

**Comment by memsharded** [comment]
I think I see what you mean, but not very clear how can the REMOTE_USER  environment variable be safely used in the typical concurrent scenario, with multiple users connecting simultaneously. Again, I am not sure how Apache works for this.

**Comment by lasote** [comment]
@memsharded is right, usually Apache authentication is linked to the resource, not to a user account in a service, I mean, you protect a folder with user/pass, but it's the same for all the users accessing the folder. With a service based on user authentication, you cannot do it safely.
