### ISSUE TITLE
[question] With MsBuild Conan is not able to find msbuild

### ISSUE THREAD

**Issue by DominicPicard** [conan-io/conan#15019]
### What is your question?

Hi,

I am using Conan version 2.0.13. 
I am trying to build a project using Visual Studio. The build in the recipe is simple : 
```
def build(self):
        msbuild = MSBuild(self)
        msbuild.build("my_solution.sln")
```

When I try to create the package, I get this error : 
```
legacy-core-hmi/0.0.0: Calling build()
legacy-core-hmi/0.0.0: RUN: msbuild "my_solution.sln" /p:Configuration="Release" /p:Platform=x86
'msbuild' is not recognized as an internal or external command,
operable program or batch file.
```

I am not sure that I understand why Conan does not find msbuild. I have other project that use CMake and Conan builds those projects correctly.

I am using Visual Studio 2022. (C:\Program Files\Microsoft Visual Studio\2022\Professional)

My profile is this : 
```
[settings]
arch=x86
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.version=193
compiler.cppstd=14
os=Windows
```

Note: If I manually run `vcvars` before the `conan create`, the build completes successfully

Thanks :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by DominicPicard** [comment]
I tried adding `compiler.toolset=v143` in the profile but still msbuild is not found

**Comment by memsharded** [comment]
Hi @DominicPicard 

Thanks for your question.
This is expected:
- CMake contains internal logic to find ``msbuild`` when ``-G Visual Studio xxxx`` is passed. Conan just call cmake and it happens
- If you type ``msbuild`` in the terminal, it fails, unless you activate the vcvars.
- Conan does not try to be smart and activate or setup the environment based on the settings. This has to be defined by the recipes.
- This would be the responsibility of the ``MSBuildToolchain``. If you use it, you'll see that it will create a ``conanvcvars.bat`` that contains the command to activate the VS. Furthermore, this ``conanvcvars`` will be automatically call from ``conanbuild.bat`` that is automatically called for every ``self.run()`` command, including commands like ``msbuild.build()`` that calls internally ``self.run()``
- The ``MSBuildToolchain`` also generates a ``conantoolchain.props`` file, with information about the toolset or cppstd that can be used to introduce variability, build different binary variant depending on the Conan input settings. This file must be included from your .vcxproj file

Please let me know if this helps.

**Comment by DominicPicard** [comment]
Hi @memsharded 

Thank you for your really quick reply 😄 

I added the `generators = "MSBuildToolchain"` line and it does fix the issue with Conan not setting up the Visual Studio environment during the build.
