### ISSUE TITLE
install shared and static libs

### ISSUE THREAD

**Issue by laxmij-cmd** [conan-io/conan#15014]
### What is your question?

Hi,

My understanding of installing shared and static libs from conan center: To install shared lib, profile should have following

[options]
shared=True

If this is not mentioned in profile, then static lib will be installed. 
Please correct me if my understanding is wrong.
Question : Is there a way to install both -- static and shared libs using same profile?

Best Regards
Laxmi

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by laxmij-cmd** [comment]
Forgot to add:
this question is regarding consumption of conan libraries using command "conan install". I have already created and uploaded static and shared libaries.

**Comment by memsharded** [comment]
Hi @laxmij-cmd 

Thanks for your question.
The profile is not fully correct. If you want all your dependencies as shared libraries:
```
[options]
*:shared=True
```
(Given that they implement the ``shared`` option, if some hardcode being a static library, there is not much to do)

Then, installing dependencies as static or shared libraries are indeed 2 consecutive installs:
```
conan install ... -o *:shared=False
conan install ... -o *:shared=True
```
You can manage with ``layout()`` and ``tools.cmake.cmake_layout:build_folder_vars`` for example to have different folders for generators of both configurations, and have different consumer builds that do not overwrite each other and can co-exist.

**Comment by laxmij-cmd** [comment]
Thank you very much for the explanation!
