### ISSUE TITLE
[bug] (Conan 1) Transitive python_requires is order dependent for consumers

### ISSUE THREAD

**Issue by aander80** [conan-io/conan#15016]
### Environment details

* Operating System+version: Tested both in Windows 10 and in Ubuntu 22.04 via WSL.
* Compiler+version: N/A
* Conan version: 1.61.0
* Python version: Python 3.9 in Windows, 3.10 in WSL

### Steps to reproduce

Hello!

We found an issue where transitive python_requires is order dependent in consumers.

This simple example reproduces it:

1. Create a `conanfile_aa.py` that contains
``` python
from conan import ConanFile

class ConanAA(ConanFile):
    name = "aa"
```

2. Create a `conanfile_bb.py` that contains
``` python
from conan import ConanFile

class ConanBB(ConanFile):
    name = "bb"
    version = "1.0"
    python_requires = "aa/[>=1, <3]"
```

3. Create a `conanfile_cc.py` that contains
``` python
from conan import ConanFile

class ConanCC(ConanFile):
    python_requires = (
        "aa/[~1]",
        "bb/[~1]",
    )
```

4. Export versions 1.0 and 2.0 of `aa`:
``` shell
❯ conan export conanfile_aa.py 1.0@
❯ conan export conanfile_aa.py 1.0@
```

5. Export `bb`:
``` shell
❯ conan export conanfile_bb.py
```

6. Install `conanfile_cc.py`:
``` shell
❯ conan install conanfile_cc.py
```

Step 6 will fail with error message `Conflict in py_requires aa/1.0 - aa/2.0`.

The error message will go away if we:

a. Update python_require to `aa/[~2]` (but we don't necessarily want this in practice)
b. Change the order of python_requires to list `bb/[~1]` **before** `aa/[~1]`, i.e.

``` python
from conan import ConanFile

class ConanCC(ConanFile):
    python_requires = (
        "bb/[~1]",
        "aa/[~1]",
    )
```

I would expect the order in which python_requires to not matter in the resolved dependencies, but perhaps I am missing something?

I have tried this example quickly in conan 2 and get the same error message in the initial `conanfile_cc.py`, but am getting other error messages when trying the fixes so I am keeping this to conan 1 for now.

### Logs

```
❯ conan export conanfile_aa.py 1.0@
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
aa/1.0: A new conanfile.py version was exported
aa/1.0: Folder: /home/aander80/.conan/data/aa/1.0/_/_/export
aa/1.0: Exported revision: 3d8341473b5047ef0cafc7402e3ec90a

❯ conan export conanfile_aa.py 2.0@
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
aa/2.0: A new conanfile.py version was exported
aa/2.0: Folder: /home/aander80/.conan/data/aa/2.0/_/_/export
aa/2.0: Exported revision: 3d8341473b5047ef0cafc7402e3ec90a

❯ conan export conanfile_bb.py
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
bb/1.0: A new conanfile.py version was exported
bb/1.0: Folder: /home/aander80/.conan/data/bb/1.0/_/_/export
bb/1.0: Exported revision: 99dca9044d94cc6f7c58066ed08012a5

❯ conan install conanfile_cc.py
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: Error loading conanfile at '/home/aander80/tmp/python_requires/conanfile_cc.py': Conflict in py_requires aa/1.0 - aa/2.0

# Update conanfile_cc.py to python_require aa/[~2]

❯ conan install conanfile_cc.py
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Version ranges solved
    Version range '~2' required by 'py_require' resolved to 'aa/2.0' in local cache
    Version range '~1' required by 'py_require' resolved to 'bb/1.0' in local cache
    WARN: Commas as separator in version '>=1, <3' range are deprecated and will be removed in Conan 2.0
    Version range '>=1, <3' required by 'py_require' resolved to 'aa/2.0' in local cache

conanfile_cc.py: Installing package
Requirements
Python requires
    bb/1.0
    aa/2.0
Packages

Installing (downloading, building) binaries...
conanfile_cc.py: Generator txt created conanbuildinfo.txt
conanfile_cc.py: Aggregating env generators
conanfile_cc.py: Generated conaninfo.txt
conanfile_cc.py: Generated graphinfo

# Revert conanfile_cc.py to python_require aa/[~1], but list bb/[~1] before aa/[~1]

❯ conan install conanfile_cc.py
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Version ranges solved
    Version range '~1' required by 'py_require' resolved to 'bb/1.0' in local cache
    WARN: Commas as separator in version '>=1, <3' range are deprecated and will be removed in Conan 2.0
    Version range '>=1, <3' required by 'py_require' resolved to 'aa/2.0' in local cache
    Version range '~1' required by 'py_require' resolved to 'aa/1.0' in local cache

conanfile_cc.py: Installing package
Requirements
Python requires
    bb/1.0
    aa/2.0
    aa/1.0
Packages

Installing (downloading, building) binaries...
conanfile_cc.py: Generator txt created conanbuildinfo.txt
conanfile_cc.py: Aggregating env generators
conanfile_cc.py: Generated conaninfo.txt
conanfile_cc.py: Generated graphinfo
```

**Comment by memsharded** [comment]
Hi @aander80 

Thanks for your detailed feedback and steps to reproduce.

I would like first to point to the docs (yes, they are new 2.0 docs, but they summarize the knowledge gathered in years of supporting 1.X): https://docs.conan.io/2/knowledge/guidelines.html

> Keep ``python_requires`` as simple as possible. Avoid transitive python_requires, keep them as reduced as possible, and at most, require them explicitly in a “flat” structure, without python_requires requiring other python_requires. Avoid inheritance (via python_requires_extend) if not strictly necessary, and avoid multiple inheritance at all costs, as it is extremely complicated, and it does not work the same as the built-in Python one.

Regarding your question:

> I would expect the order in which python_requires to not matter in the resolved dependencies, but perhaps I am missing something?

This is expected. Conan dependency resolver is not a full joint-compatibility SAT solver of ranges, but partially greedy (depth-first approach). That means that the first declared dependencies have higher priority, and diamond structures in the graph can generate conflicts if they don't completely align on the versions.

We are still doing improvements in Conan 2.0, for example https://github.com/conan-io/conan/pull/14912 will resolve more cases like yours (not for python-requires, but for regular requires), but still it is not expected to look for full joint compatibility (this is proven to be an NP-hard problem that in the case of Conan dependency resolution would mean being intractable in practice).

My recommendations to deal with this would be:
- Align the versions and version ranges so they lead to the same versions without conflict.
- Simplify the ``python_requires``, avoid transitivity and make them more flat as recommended in the https://docs.conan.io/2/knowledge/guidelines.html
- For Conan 2.0 we might eventually extend the work of https://github.com/conan-io/conan/pull/14912 to ``python-requires``, but it is not planned at the moment.

**Comment by memsharded** [comment]
I have been checking if implementing version-ranges joint compatibility made sense for Conan 2.0.
At the moment it seems excessive complexity for the value, so I am proposing https://github.com/conan-io/conan/pull/15033 that will close this ticket.

The recommendations are as above, short term, align the versions and version-ranges so they don't conflict, and mid-term, try to simplify the hierarchy and make it more flat. We are happy to re-evaluate this later, and re-consider adding better version-ranges intersection for python-requires in the future if this keeps being a big issue.

**Comment by aander80** [comment]
Thank you for the update!
