### ISSUE TITLE
conan 2.0 successor of the json generator

### ISSUE THREAD

**Issue by jegabe** [conan-io/conan#15010]
### What is your question?

Hello dear conanians,

the json generator seems to be deprecated (https://docs.conan.io/1/reference/generators/json.html). What is the correct conan 2.0 way of generating a json file containing conan info/dependencies? Or in other words: Why is the generator deprecated? Should it be replaced with "conan info -j" or another generator?
It would be nice to give a hint in the mentioned page

Regards, Jens

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jegabe 

The json generator has been superseded by the ``--format=json`` output of the ``conan graph info``, ``conan install`` and ``conan create`` commands. They will be creating a full graph description in json, containing even more detailed and complete information about dependencies that what the ``json`` generator used to do. Please have a look and let us know.

**Comment by jegabe** [comment]
Thanks very much @memsharded ! for the quick response I'll have a look. Maybe you could put that text into the https://docs.conan.io/1/reference/generators/json.html page?
Have a nice week!

**Comment by memsharded** [comment]
Thanks to you for the feedback!
