### ISSUE TITLE
[bug] Cannot build cppcheck/2.12.1 in debug on Windows with Visual Studio 2022 compiler

### ISSUE THREAD

**Issue by NightWulfe** [conan-io/conan#15039]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: Visual Studio 2022 17.7.4 (cl.exe 19.37.32824)
* Conan version: 2.0.13
* Python version:3.11.2

### Steps to reproduce

Sorry if I'm missing something. I'm also not sure if this is a me issue, a conan issue, or a cppcheck recipe issue.

Run the command specified in the Logs section. The build fails with the error
```
pcre dependency for RULES has not been found
```

I traced this to an cppcheck's `findDependencies.cmake` script is attempting to find `pcre` instead of `pcred`. The [conan recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/cppcheck/all/conanfile.py) attempts to work around this by applying a [patch ](https://github.com/conan-io/conan-center-index/blob/master/recipes/cppcheck/all/patches/0004-pcre-debuglib-name-2.12.patch) (if I understand how this works) to correct this limitation.

That patch does not appear to be working, and the build fails.

I could work around this if Conan would let me build cppcheck in release mode, regardless of my application build profile. IMO `tool_requires` dependencies should always build in Release by default.

### Logs

Command:
```
conan install --requires=cppcheck/2.12.1 --build=cppcheck* --settings build_type=Debug --settings compiler=msvc
```

Output:
```
CMake Error at cmake/findDependencies.cmake:36 (message):
  pcre dependency for RULES has not been found
Call Stack (most recent call first):
  CMakeLists.txt:15 (include)


-- Configuring incomplete, errors occurred!

cppcheck/2.12.1: ERROR:
Package 'd8a6306c2d70cd3e48ed9adc4a696e54bbf194ba' build failed
cppcheck/2.12.1: WARN: Build folder C:\Users\user\.conan2\p\b\cppcha3f024742435c\b\build\Debug
*********************************************************
Recipe 'cppcheck/2.12.1' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: cppcheck/2.12.1: Error in build() method, line 51
        cmake.configure()
        ConanException: Error 1 while executing
```

**Comment by memsharded** [comment]
Hi @NightWulfe 

thanks for your report, we need to have a look at it.

> I could work around this if Conan would let me build cppcheck in release mode, regardless of my application build profile. IMO tool_requires dependencies should always build in Release by default.

It is totally possible, and indeed recommended and typical. ``tool_requires`` use the "build" profile and the build profile is by default ``Release``, and if it isn't you should probably make it release. Can you please share the command output that shows your profiles?

Another different story is if you want to mix Debug and Release dependencies in the host context. This works in Linux for example, but in Windows it is typically not possible as the linker will refuse to do it. But from the Conan point of view is possible to define it with ``conan .... -s:h build_type=Debug -s:h cppcheck*:build_type=Release`` for example. This is called per-package settings and it is possible to define different settings for different packages using a pattern.

**Comment by NightWulfe** [comment]
Hello, @memsharded. Thank you for the quick reply!

I didn't realize `tool_requires` uses the build profile. That's great to know and lead me to check my `default` profile where `build_type` had somehow been set to `Debug`. Changing it to `Release` allowed me to install the dependencies and compile. All good, there!

Building manually in Debug still fails, which I assume is related to the patch issue. Should I leave this open for that?

**Comment by memsharded** [comment]
> I didn't realize tool_requires uses the build profile. That's great to know and lead me to check my default profile where build_type had somehow been set to Debug. Changing it to Release allowed me to install the dependencies and compile. All good, there!

Ok, that is great, happy that it is solved.

> Building manually in Debug still fails, which I assume is related to the patch issue. Should I leave this open for that?

Yes, let's leave it open, probably it needs to be transferred to the ``conan-center-index`` repo if it is a recipe issue, we'll check that when possible. Thanks for the feedback!

**Comment by NightWulfe** [comment]
Let me know if I can be of any further assistance!

Thanks again.

**Comment by AbrilRBS** [comment]
Closing in favour of the linked issue
