### ISSUE TITLE
[bug] test utils subpackage not usable because test.assets not exported with conan package

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#15031]
### Environment details

N/A

### Steps to reproduce

Hi Team,

It currently doesn't seem to be possible to import the conan test client for the purpose of unit testing our custom commands. When I attempt to do so through `from conans.test.utils.tools import TestClient`, I'm greeted with a "module not found" error associated with line 43: https://github.com/conan-io/conan/blob/84e5faef3c81aaa4a1582e090707fc3de3bb3a7f/conans/test/utils/tools.py#L43

This appears to be because `conans.test.assets` is not exported with the package because of this package logic: https://github.com/conan-io/conan/blob/84e5faef3c81aaa4a1582e090707fc3de3bb3a7f/setup.py#L15-L19

Is this intentional? The comment there is that the test utils are used by conan-package-tools, but I can't see how that could be possible with the current import issues one would face.

Even if it is intentional, it would be incredibly useful to us when writing our own custom extensions to be able to use the test utilities you've developed rather than copying/writing our own.

Otherwise, if I'm trying to use these incorrectly please advise of correct usage.

Cheers,

**Comment by memsharded** [comment]
Hi @samuel-emrys 

This seems intentional. We explicitly removed the tests from the packaged package in PyPI, because the Conan client is installed hundreds of thousands of times per month, and we thought that making it as small as possible was the best approach, saving a few bytes always help.

For development and testing, it is expected to clone the repo and put it in the testing path. 
``conan-package-tools`` is in the path of deprecation, it will no longer be used in 2.0. I think it is not tested anymore that way.

**Comment by samuel-emrys** [comment]
Thanks @memsharded, understood. Could you clarify what you mean by cloning and putting Conan on the path?

To clarify, I'm talking about an in-house equivalent to the conan-extensions repo where we want to make use of `TestClient`. Are you able to elaborate on how you would do this?

**Comment by memsharded** [comment]
I meant doing a git-clone of the repo and pre-pending the cloned folder to PYTHONPATH. Also possible to ``git clone`` and putting it in editable with ``pip install -e .`` works very well, and it is also something very useful, in case there is need to debug, modify the Conan code (this can be extremely convenient) while developing the extensions.

**Comment by AbrilRBS** [comment]
Closing as solved, assets have been packages for a while now :)

**Comment by samuel-emrys** [comment]
@RubenRBS does this mean using the TestClient helper to unit test our custom commands is a supported use case?

**Comment by AbrilRBS** [comment]
We plan on moving those files around for 2.4, so watch out for that, and we can't guarantee any kind of stability, but we will keep in mind outside usages (as we also use those utilities elsewhere just for the same case as yours) as to try to not break them, but will do if necessary - we'll still treat it mostly as an implementation detail that happens to work elsewhere :)

**Comment by samuel-emrys** [comment]
for awareness, our current approach has been to extract the `TestClient` from the conan code base and have it as a utility in our config repo so that we can execute unit tests without much overhead. There is a burden associated with keeping this up to date as the conan api changes, so we would love to be able to only rely on what's shipped with the conan client.

We're developing a reasonable library of custom commands to support our CI system, which seems to work well so far, but yes, it introduces similar requirements that you have around ensuring that behaviours are documented and we don't have regressions, so unit testing is very important.

I think that it sends a positive message for you to provide this kind of tooling to support the idea of and existing features for customising the behaviour of conan.
