### ISSUE TITLE
[question] How to exclude a faulty download URL?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15048]
### What is your question?

I'm trying to build a boost package (no matter what version) from sources. Its primary download URL is`https://boostorg.jfrog.io`. Right now it provides a download speed of about 40Kb/s, so the whole download time is more than an hour. Is there any way for Conan (1x and 2.x) to prevent the use of such a faulty URL and instead switch to a backup one? BTW `CONAN_TRACE_FILE` seems to be broken on Windows in the current Conan 1.x builds.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

The download URLs are defined in the recipes, so it is not possible to change them on the fly from the user without modifying the recipe. If you can modify the ``conandata.yml``, then it is obvious, just replacing the ``url`` there and ``conan create .``. This should be relatively easy.

What it would be possible (in Conan 2.0 only) is to use the new backup-sources features to prioritize downloading things from your own private repo: https://blog.conan.io/2023/10/03/backup-sources-feature.html, which would avoid the slow transfer from the external servers.

Regarding the CONAN_TRACE_FILE error, that would deserve a dedicated ticket, if you could please detail what failures are you seeing, that would help. Thanks!

**Comment by memsharded** [comment]
Just did a quick test with ``CONAN_TRACE_FILE`` and seems to be working fine here in Conan 1.X

**Comment by db4** [comment]
> The download URLs are defined in the recipes, so it is not possible to change them on the fly from the user without modifying the recipe. If you can modify the `conandata.yml`, then it is obvious, just replacing the `url` there and `conan create .`. This should be relatively easy.

I'm not going to change URLs in conandata.yml. There are two of them for boost/1.x, I would like Conan to ignore the first one (providing unacceptable download speed). If it did not respond at all Conan would choose the second URL automatically. 

> What it would be possible (in Conan 2.0 only) is to use the new backup-sources features to prioritize downloading things from your own private repo: https://blog.conan.io/2023/10/03/backup-sources-feature.html, which would avoid the slow transfer from the external servers.

Thanks, I will try that.

> Regarding the CONAN_TRACE_FILE error, that would deserve a dedicated ticket, if you could please detail what failures are you seeing, that would help. Thanks!

Done: https://github.com/conan-io/conan/issues/15049
