### ISSUE TITLE
[question] [conanv1] How to deal with "provides" conflict for requires/tool_requires

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#15065]
### What is your question?

Hi,

I have copies of recipes from CCI with some customizations.
https://github.com/Nekto89/conan-center-index/commit/f888ee02cf921765c282cba4732b91731e172151
https://github.com/Nekto89/conan-center-index/commit/79e3168c8898d1d51aae9cf33791754007b3f003

I'm trying to build onnx which uses protobuf in both requirements and build requirements.
I keep getting error about conflict and can't understand what I'm doing wrong.

build_profile
```
include(default)
[settings]
*:build_type=Release
[options]
protobuf:with_zlib=zlib-ng
zlib-ng:zlib_compat=True
[conf]
[build_requires]
[env]
```

host_profile
```
include(default)
[settings]
[options]
protobuf:with_zlib=zlib-ng
zlib-ng:zlib_compat=True
[conf]
[build_requires]
onnx*: protobuf/3.21.12@user/channel#99883cb5b41e69fac240e603a9401aee
[env]
```

conanfile.txt
```
[requires]
onnx/1.14.1@user/channel#715b413426c77e6de70a7cef0e01ad26
protobuf/3.21.12@user/channel#99883cb5b41e69fac240e603a9401aee
zlib-ng/2.1.3@user/channel#1aeb509a0960ec067fa90282fa6c2cf0
```

```
cd C:\dev\conan\conan-center-index\recipes\zlib-ng\all
conan export . zlib-ng/2.1.3@user/channel
cd ../../protobuf/all
conan export . protobuf/3.21.12@user/channel
cd ../../onnx/all
conan export . onnx/1.14.1@user/channel

cd C:\dev\conflict_reproduce
mkdir bld
cd bld
conan install -g cmake_find_package_multi -s build_type=Release --build=missing -pr:b "../build_profile" -pr:h "../host_profile" ../conanfile.txt
```

```
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
protobuf:with_zlib=zlib-ng
zlib-ng:zlib_compat=True
[build_requires]
onnx*: protobuf/3.21.12@user/channel
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
*:build_type=Release
[options]
protobuf:with_zlib=zlib-ng
zlib-ng:zlib_compat=True
[build_requires]
[env]

WARN: onnx/1.14.1@user/channel: requirement protobuf/3.21.12 overridden by your conanfile to protobuf/3.21.12@user/channel
ERROR: At least two recipes provides the same functionality:
 - 'zlib' provided by 'zlib-ng/2.1.3@user/channel', 'zlib-ng/2.1.3@user/channel'
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Nekto89 

Thanks for your report.
This seems it could be a bug in the ``provides`` computation in Conan 1.X.

Unfortunately, I don't have the bandwidth now to reduce it to a unit test that we could use to try to fix it, we are a bit overwhelmed at this moment

**Comment by memsharded** [comment]
I have tried a bit to reproduce this with a unit test, and not successful so far.

I have also tried to reproduce with the above instructions, but it seems that they are not fully complete, the revisions don't match, and it seems the commit above hasn't been merged, but they are also not in a branch, I guess the different commits need to be checked-out before every ``conan export``? Maybe the best would be to provide a branch in your repo with a "build.py" script in its root that can reproduce the issue, that would also help a lot.

**Comment by Nekto89** [comment]
> I have tried a bit to reproduce this with a unit test, and not successful so far.
> 
> I have also tried to reproduce with the above instructions, but it seems that they are not fully complete, the revisions don't match, and it seems the commit above hasn't been merged, but they are also not in a branch, I guess the different commits need to be checked-out before every `conan export`? Maybe the best would be to provide a branch in your repo with a "build.py" script in its root that can reproduce the issue, that would also help a lot.

Mentioned changes are part of branch "conflict_reproduce" in my fork of cci. There are no additional changes in that branch. So you can just take the latest (79e3168c8898d1d51aae9cf33791754007b3f003)
https://github.com/Nekto89/conan-center-index/commits/conflict_reproduce

I also forgot to mention that I'm using Conan version 1.61.0 and full package mode
```
default_package_id_mode = full_package_mode 
revisions_enabled = 1
```

I'll try to make "build.py" in several hours.

**Comment by Nekto89** [comment]
```
from pathlib import Path
from argparse import ArgumentParser
from subprocess import run
import tempfile

def reproduce_problem(cci_repo : Path):
    run("conan export . zlib-ng/2.1.3@user/channel", shell=True, cwd=cci_repo / "recipes" / "zlib-ng" / "all", check=True)
    run("conan export . protobuf/3.21.12@user/channel", shell=True, cwd=cci_repo / "recipes" / "protobuf" / "all", check=True)
    run("conan export . onnx/1.14.1@user/channel", shell=True, cwd=cci_repo / "recipes" / "onnx" / "all", check=True)
    with tempfile.TemporaryDirectory() as tmpdir:
        build_dir = Path(tmpdir)
        (build_dir / "build_profile").write_text('''include(default)
[settings]
*:build_type=Release
[options]
protobuf:with_zlib=zlib-ng
zlib-ng:zlib_compat=True
[conf]
[build_requires]
[env]
''')
        (build_dir / "host_profile").write_text('''include(default)
[settings]
[options]
protobuf:with_zlib=zlib-ng
zlib-ng:zlib_compat=True
[conf]
[build_requires]
onnx*: protobuf/3.21.12@user/channel#99883cb5b41e69fac240e603a9401aee
[env]
''')
        (build_dir / "conanfile.txt").write_text('''[requires]
onnx/1.14.1@user/channel#715b413426c77e6de70a7cef0e01ad26
protobuf/3.21.12@user/channel#99883cb5b41e69fac240e603a9401aee
zlib-ng/2.1.3@user/channel#1aeb509a0960ec067fa90282fa6c2cf0
''')
        run('conan install -s build_type=Release --build=missing -pr:b "./build_profile" -pr:h "./host_profile" "./conanfile.txt"', shell=True, cwd=build_dir, check=True)

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("--repo", type=Path, required=True, help="path to root of conan center index")
    args = parser.parse_args()
    reproduce_problem(args.repo)



```

**Comment by memsharded** [comment]
I am trying your script, but it is not working, it fails with:
```
WARN: onnx/1.14.1@user/channel: requirement protobuf/3.21.12 overridden by your conanfile to protobuf/3.21.12@user/channel
ERROR: Failed requirement 'protobuf/3.21.12@user/channel' from 'onnx/1.14.1@user/channel'
ERROR: The '2c7f97700da55a62d61fdabd8350ff79' revision recipe in the local cache doesn't match the requested 'protobuf/3.21.12@user/channel#99883cb5b41e69fac240e603a9401aee'. Use '--update' to check in the remote.
```
Can you please make sure to remove your local cache packages, to ensure a clean state? I suspect that you have some other local changes like in onnx that are not captured in the script.

**Comment by Nekto89** [comment]
> I am trying your script, but it is not working, it fails with:
> 
> ```
> WARN: onnx/1.14.1@user/channel: requirement protobuf/3.21.12 overridden by your conanfile to protobuf/3.21.12@user/channel
> ERROR: Failed requirement 'protobuf/3.21.12@user/channel' from 'onnx/1.14.1@user/channel'
> ERROR: The '2c7f97700da55a62d61fdabd8350ff79' revision recipe in the local cache doesn't match the requested 'protobuf/3.21.12@user/channel#99883cb5b41e69fac240e603a9401aee'. Use '--update' to check in the remote.
> ```
> 
> Can you please make sure to remove your local cache packages, to ensure a clean state? I suspect that you have some other local changes like in onnx that are not captured in the script.

Different hash is caused by hook from conan-center-index - #KB-H031: "CONANDATA.YML REDUCE"

**Comment by Nekto89** [comment]
I've removed recipe revisions to simplify test case.
https://github.com/Nekto89/conan-center-index/commit/0a57557e898a80832f9069e0bdd403040f0a39ae

```
from pathlib import Path
from argparse import ArgumentParser
from subprocess import run
import tempfile

def reproduce_problem(cci_repo : Path):
    run("conan export . zlib-ng/2.1.3@user/channel", shell=True, cwd=cci_repo / "recipes" / "zlib-ng" / "all", check=True)
    run("conan export . protobuf/3.21.12@user/channel", shell=True, cwd=cci_repo / "recipes" / "protobuf" / "all", check=True)
    run("conan export . onnx/1.14.1@user/channel", shell=True, cwd=cci_repo / "recipes" / "onnx" / "all", check=True)
    with tempfile.TemporaryDirectory() as tmpdir:
        build_dir = Path(tmpdir)
        (build_dir / "build_profile").write_text('''include(default)
[settings]
*:build_type=Release
[options]
protobuf:with_zlib=zlib-ng
zlib-ng:zlib_compat=True
[conf]
[build_requires]
[env]
''')
        (build_dir / "host_profile").write_text('''include(default)
[settings]
[options]
protobuf:with_zlib=zlib-ng
zlib-ng:zlib_compat=True
[conf]
[build_requires]
onnx*: protobuf/3.21.12@user/channel
[env]
''')
        (build_dir / "conanfile.txt").write_text('''[requires]
onnx/1.14.1@user/channel
protobuf/3.21.12@user/channel
zlib-ng/2.1.3@user/channel
''')
        run('conan install -s build_type=Release --build=missing -pr:b "./build_profile" -pr:h "./host_profile" "./conanfile.txt"', shell=True, cwd=build_dir, check=True)

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("--repo", type=Path, required=True, help="path to root of conan center index")
    args = parser.parse_args()
    reproduce_problem(args.repo)
```

**Comment by memsharded** [comment]
Excellent! I managed to reproduce, this is a good start, thanks very much.

**Comment by memsharded** [comment]
Got it. Try changing your ``zlib-ng`` recipe:
```diff
diff --git a/recipes/zlib-ng/all/conanfile.py b/recipes/zlib-ng/all/conanfile.py
index 8ac38d26f..b6a76d534 100644
--- a/recipes/zlib-ng/all/conanfile.py
+++ b/recipes/zlib-ng/all/conanfile.py
@@ -40,7 +40,7 @@ class ZlibNgConan(ConanFile):
         "with_reduced_mem": False,
     }

-    provides = []
+    provides = None

     def config_options(self):
         if self.settings.os == "Windows":
@@ -54,7 +54,7 @@ class ZlibNgConan(ConanFile):
         self.settings.rm_safe("compiler.cppstd")
         self.settings.rm_safe("compiler.libcxx")
         if self.options.zlib_compat:
-            self.provides.append("zlib")
+            self.provides = ["zlib"]

     def layout(self):
         cmake_layout(self, src_folder="src")
```

The ``configure`` might run more than once, and the recipe itself was appending 2 times the ``provides`` causing the conflict to itself.

**Comment by Nekto89** [comment]
> Got it. Try changing your `zlib-ng` recipe:
> 
> ```diff
> diff --git a/recipes/zlib-ng/all/conanfile.py b/recipes/zlib-ng/all/conanfile.py
> index 8ac38d26f..b6a76d534 100644
> --- a/recipes/zlib-ng/all/conanfile.py
> +++ b/recipes/zlib-ng/all/conanfile.py
> @@ -40,7 +40,7 @@ class ZlibNgConan(ConanFile):
>          "with_reduced_mem": False,
>      }
> 
> -    provides = []
> +    provides = None
> 
>      def config_options(self):
>          if self.settings.os == "Windows":
> @@ -54,7 +54,7 @@ class ZlibNgConan(ConanFile):
>          self.settings.rm_safe("compiler.cppstd")
>          self.settings.rm_safe("compiler.libcxx")
>          if self.options.zlib_compat:
> -            self.provides.append("zlib")
> +            self.provides = ["zlib"]
> 
>      def layout(self):
>          cmake_layout(self, src_folder="src")
> ```
> 
> The `configure` might run more than once, and the recipe itself was appending 2 times the `provides` causing the conflict to itself.

Thanks. So the issue was in recipe. There are currently 2 recipes with this approach in CCI:
conan-center-index\recipes\exiv2\all\conanfile.py(47):provides = []
conan-center-index\recipes\mpir\all\conanfile.py(22):provides = []
