### ISSUE TITLE
[question] Used defined parameters in profiles

### ISSUE THREAD

**Issue by mikirothman** [conan-io/conan#15067]
### What is your question?

Hi! 

I would like to add to my profiles some parameters (mainly strings).
Those parameters will be used on generate method, in order to perform some jinja configurations on several json and xml files, which are handled under the package sources.

is that a good practice or should I search for a different way ?
If it's makes sense, how should it be done ? using environment variables under buildenv tag ?
I guess it Would not be a part of the package id right ?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mikirothman 

Thanks for your question.
I think you are looking for ``user.myteam:myconf`` custom configuration.
In the same way that built-in configuration like ``tools.cmake.cmaketoolchain:generator`` can be used to configure how ``CMakeToolchain`` generates file in ``generate()``, you can use your own custom ``user.xxx`` (the ``user`` is literal) conf to configure the way you want your generators or recipe behavior.

Some ideas:
- Probably ``user.myteam.mypkg:conf`` is good naming if something is for a specific package
- In general the confs do not affect the ``package_id`` of the packages, but in some cases it is possible to make it affect if you want to
- Use ``self.conf.get("user.myteam...", check_type=list, default=...)`` to validate if your input is a list (this example), or a string, or an integer, etc

**Comment by mikirothman** [comment]
Great solution, fits exactly to my needs
