### ISSUE TITLE
[bug] Logging information missing from documentation

### ISSUE THREAD

**Issue by threeseed** [conan-io/conan#15069]
### Steps to reproduce

1. Visit Conan V2 [documentation](https://docs.conan.io/2/).
2. You will notice that there is no equivalent for the [V1 Logging Page](https://docs.conan.io/1/mastering/logging.html).

**Comment by memsharded** [comment]
Hi @nadenf 

Thanks for your feedback.
This is not a bug. That trace file was removed on purpose from Conan 2.0, not only from documentation.

The command outputs has been revamped in 2.0, and there are now logging levels in command line, like ``-vvv``. They are still not widely used, most of the current messages are just "info", but new "debug" and "verbose" messages will be added as necessary. Also, all output is to stderr, so it can be logged separately from stdout that contains the command result.
