### ISSUE TITLE
[question] How to avoid adding "compiler.cppstd=gnu14" to the default profile?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15074]
### What is your question?

I use gcc8 for CI (Conan 2). First I do `conan profile detect` that creates the following profile:
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
```
Question 1: why `gnu14`? gcc8 actually supports c++17. With the settings above some packages refuse to install:
```
$ conan install --requires stduuid/1.2.3
...
stduuid/1.2.3: Invalid: Current cppstd (gnu14) is lower than the required C++ standard (17).
```
Question 2: how to avoid adding `compiler.cppstd` to the profile? If I remove it manually, `conan install` succeeds. But how to do it in CI job? Conan 1 has `profile update` command, but Conan 2 doesn't.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question.

> Question 1: why gnu14? gcc8 actually supports c++17. 

``conan profile detect`` in 2.0 tries to be close to the compiler defaults while provide some minimum reasonable for the operations of ConanCenter. It doesn't provide the latest C++ supported by default.

> Question 2: how to avoid adding compiler.cppstd to the profile? If I remove it manually, conan install succeeds. But how to do it in CI job? Conan 1 has profile update command, but Conan 2 doesn't.

It is not recommended to drop ``compiler.cppstd`` in Conan 2.0. It will be mandated by many recipes, that can raise errors if a compiler.cppstd minimum is not satisfied. Maybe the ``compatibility.py`` defaults in Conan 2.0 is solving the issue, but it can be problematic. Please define your desired cppstd (the one you are going to build your applications/consumers with) in your profiles or command line.

The recommendation for production is not to rely on detected profiles, but use your own profiles and manage them with ``conan config install``.
From https://docs.conan.io/2/introduction.html#stable:

> Configuration and automatic tools detection, like the detection of the default profile (conan profile detect) can and will change at any time. Users are encouraged to define their configurations in their own profiles files for repeatability. New versions of Conan might detect different default profiles.

Also https://docs.conan.io/2/reference/commands/profile.html#conan-profile-detect

**Comment by db4** [comment]
@memsharded Thanks!
