### ISSUE TITLE
[bug] CMakeDeps traceback for transitive dependencies

### ISSUE THREAD

**Issue by fpoirotte** [conan-io/conan#15070]
### Environment details

* Red Hat UBI 9.1
* gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
* Conan version 1.61.0
* Python 3.9.16
* Build and target host are the same (no cross-compilation)

I have the following dependency chain:
`myapp --requires--> qt --requires--> libxcb`
The qt recipe is mostly the same as https://github.com/conan-io/conan-center-index/blob/26d5dbb1c09d207c5bbe55c88e8871f100e4f9bb/recipes/qt/5.x.x/conanfile.py, except I repackaged some of the Xorg-related libraries and require those instead of `xorg/system`. libxcb is one of those repackaged libraries.

The upstream libxcb project provides pkg-config (.pc) configuration files. Following Conan best practice, I have removed those files from the Conan package and defined `package_info()` as such:

```py
    def package_info(self):
        self.cpp_info.set_property("pkg_config_name", "xcb")
        self.cpp_info.libs.extend(["xcb"])
```
Notice that it does not define the `cmake_file_name` property (this is intended), because the library is not meant to be consumed as a CMake package through `find_package()` (instead, the cmake `FindPkgConfig` module must be used).

The `myapp` package depends both on packages that provide only pkg-config files and packages that provide CMake configuration files. Its recipe's `generate()` method uses both `PkgConfigDeps` and `CMakeDeps` (and, additionnally, `CMakeToolchain`).

An error is raised by the `CMakeDeps` generator in relation with the transitive dependency while building the `myapp` package.

It seems to me like `CMakeDeps` does not know how to deal with packages that lack a CMake configuration file (`cmake_file_name` property), hence the error. I managed to work around the error by capturing and ignoring this error and 2 similar ones:
* in `conan.tools.cmake.cmakedeps.templates.target_data.ConfigDataTemplate:_get_required_components_cpp` :
```py
            for require in comp.requires:
                if "::" in require:  # Points to a component of a different package
                    pkg, cmp_name = require.split("::")
                    try: # added this
                        req = direct_visible_host[pkg]
                    except KeyError: continue # and this
                    public_comp_deps.append(self.get_component_alias(req, cmp_name))
```
* in `conan.tools.cmake.cmakedeps.templates.target_data.ConfigDataTemplate:_get_dependency_filenames` :
```py
            for dep_name, _ in self.conanfile.cpp_info.required_components:
                if dep_name and dep_name not in ret:  # External dep
                    try: # added this
                        req = direct_host[dep_name]
                    except KeyError: continue # and this
                    ret.append(self.cmakedeps.get_cmake_package_name(req))
```
* in `conan.tools.cmake.cmakedeps.templates.target_data.TargetConfigurationTemplate:get_deps_targets_names` :
```py
            for dep_name, component_name in self.conanfile.cpp_info.required_components:
                if not dep_name:
                    # Internal dep (no another component)
                    req = self.conanfile
                else:
                    try: # added this
                        req = visible_host[dep_name]
                    except KeyError: continue # and this
```
I don't know if that is a safe patch or not though.

### Steps to reproduce

1. Execute :
```
conan install \
    --remote=local --build=missing \
    -pr:b ./code/dependencies/profiles/default.jinja2 \
    -pr:h ./code/dependencies/profiles/default.jinja2 \
    -s "*:build_type=RelWithDebInfo" \
    /tmp/cli/conanfile.py
```

### Logs

```
myapp/0.0.1: Configuring sources in /root/.conan/data/myapp/0.0.1/_/_/source/src
myapp/0.0.1: 
myapp/0.0.1: Copying sources to build folder
myapp/0.0.1: Building your package in /root/.conan/data/myapp/0.0.1/_/_/build/17d09ff2dbd82daa7fe604f31ded72c87ec4e76e
myapp/0.0.1: Generator txt created conanbuildinfo.txt
myapp/0.0.1: Calling generate()
myapp/0.0.1: Preset 'relwithdebinfo' added to CMakePresets.json. Invoke it manually using 'cmake --preset relwithdebinfo'
myapp/0.0.1: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/root/.conan/data/myapp/0.0.1/_/_/build/17d09ff2dbd82daa7fe604f31ded72c87ec4e76e/build/RelWithDebInfo/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=RelWithDebInfo'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/conan/tools/cmake/cmakedeps/templates/__init__.py", line 42, in render
    context = self.context
  File "/usr/local/lib/python3.9/site-packages/conan/tools/cmake/cmakedeps/templates/target_data.py", line 32, in context
    components = self._get_required_components_cpp()
  File "/usr/local/lib/python3.9/site-packages/conan/tools/cmake/cmakedeps/templates/target_data.py", line 172, in _get_required_components_cpp
    req = direct_visible_host[pkg]
  File "/usr/local/lib/python3.9/site-packages/conans/model/dependencies.py", line 76, in __getitem__
    return self._data[r]
KeyError: {'ref': libxcb/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}

ERROR: myapp/0.0.1: Error in generate() method, line 45
	deps.generate()
	ConanException: error generating context for 'libxcb/1.13.1': {'ref': libxcb/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}
```

Note: I patched `conan.tools.cmake.cmakedeps.templates.CMakeDepsFileTemplate:render` to display the full traceback for debugging purposes.

**Comment by memsharded** [comment]
Hi @fpoirotte 

Thanks for your report

> Notice that it does not define the cmake_file_name property (this is intended), because the library is not meant to be consumed as a CMake package through find_package() (instead, the cmake FindPkgConfig module must be used).

If you don't want ``CMakeDeps`` downstream to generate a .cmake file for the dependency, you need to set the ``self.cpp_info.set_property("cmake_find_mode", "none")`` to avoid it. Otherwise the file will be generated, just with the default package name as ``pkgname-config.cmake`` file, and it will be found and used.

> The myapp package depends both on packages that provide only pkg-config files and packages that provide CMake configuration files. Its recipe's generate() method uses both PkgConfigDeps and CMakeDeps (and, additionnally, CMakeToolchain).

I am afraid this might not always work. The generators are not designed to be mixed that way, but either relying on one or the other, specially for transitive dependencies. Once a dependency is found via ``find_package()`` it is expected that its transitive dependencies are also found via ``find_package()``. You can control via ``CMakeDeps.set_property()`` the ``cmake_find_mode`` of the dependencies and control which dependencies do generate or not a xxx-config.cmake file, but you need to guarantee that you are respecting the transitive dependencies.

The thing is that ``package_info()`` and generators are intended precisely to not to have to deal with these details. If your ``app`` depend on ``qt`` and it wants to do a ``find_package(qt)`` for it generated with ``CMakeDeps``, it should be irrelevant that the transitive dependencies use one or another generator, the consumer should always be able to consume all of its dependencies with the generator of its choice.


> The qt recipe is mostly the same as https://github.com/conan-io/conan-center-index/blob/26d5dbb1c09d207c5bbe55c88e8871f100e4f9bb/recipes/qt/5.x.x/conanfile.py, except I repackaged some of the Xorg-related libraries and require those instead of xorg/system. libxcb is one of those repackaged libraries.

This would be the key to be able to investigate this issue properly. Do you think you could strip down your qt recipe to the very minimum (I think it might be possible to remove most of the recipe, leaving just  some ``requires`` and ``package_info()`` but without really building anything.? Also like a very simple ``xcb`` recipe, most likely it can be almost empty to reproduce. If we could reproduce the issue on our end that would help a lot. Thanks!

**Comment by fpoirotte** [comment]
Thanks for your quick reply and the clarifications. It all makes sense.
I guess the remaining question is: why can't CMakeDeps find some of the transitive dependencies?

I'll try to create a minimal reproducing example for further debugging.

**Comment by fpoirotte** [comment]
Hi,

I finally managed to fix the problem.

`ConanException: error generating context for 'foo/1.13.1': {'ref': bar/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}`

actually means that package `foo` has a requirement on `bar` in its `package_info()` method (in the `requires` attribute), but lacks a corresponding dependency in `foo`'s `requirements()` method.

The traceback appears when package `qux` attempts to consume `foo` and uses `CMakeDeps`/`PkgConfigDeps` in its `generate()` method.

Maybe the error message could be improved a little (e.g. suggesting a missing dependency in that case).

Anyway, I'll close this issue as it's not a bug in Conan itself, but rather mistakes in the recipes.

**Comment by memsharded** [comment]
> Maybe the error message could be improved a little (e.g. suggesting a missing dependency in that case).

Thanks for the feedback. I have checked if this could be improved for Conan 2.0, but it seems that Conan 2.0 is already displaying a better message like:
```
ERROR: pkg/0.1: required component package 'nonexisting::' not in dependencies
```
