### ISSUE TITLE
[bug] conan configuration (download_cache) not used when downloading files

### ISSUE THREAD

**Issue by jsteinhofff** [conan-io/conan#15080]
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version: - not relevant -
* Conan version: 1.61.0
* Python version: 3.8.10 (conan installed in a virtualenv , in case this plays a role here)

### Steps to reproduce

Since we are downloading huge artifacts as part of some of our conan builds, i wanted to make use of the conan download cache.
I can confirm that the download cache seems to work sometimes, but for the downloads which i care about now which are made during the source() method of our packages, it does not get used and as far as i can tell from debugging it seems that conan somehow does not correctly forward conan configuration to the download method.
This is displayed in the following debugging situation:
![image](https://github.com/conan-io/conan/assets/70687692/1a7e6be9-a74f-49fb-b067-5b450ad95146)

When stumbeling around in the call-stack i get the impression that never does the conanfile.conf thing get filled with the global conan settings, but probably i am somehow missing something.

**Comment by memsharded** [comment]
Hi @jsteinhofff 

I don't think this is a bug. It seems you are setting the configuration in another file.
All modern configuration is defined in:
- ``global.conf`` file
- profiles ``[conf]`` section
- Command line ``-c`` arguments

But not in the legacy ``conan.conf`` file.
You can find more info in this https://docs.conan.io/1/reference/config_files/global_conf.html

Please let me know if this helps.

**Comment by jsteinhofff** [comment]
Hi @memsharded  thanks a lot for the quick answer, you are fully correct. In my defense .. i used conan config set to set the configuration and somehow this still seems to feed into `conan.conf` file so i never got the idea that i might be using the wrong file :-)

**Comment by memsharded** [comment]
> In my defense .. i used conan config set to set the configuration and somehow this still seems to feed into conan.conf file so i never got the idea that i might be using the wrong file :-)

No prob! 🙂 

yes, ``conan config set`` doesn't really validate, just append to the file. The ``conan config set`` is tied to ``conan.conf`` legacy configuration system, that command has also disappeared in Conan 2.0 together with the ``conan.conf``.
