### ISSUE TITLE
[bug] Does 'conan cache clean' really clean everything in cache?

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#15089]
### Environment details

* Operating System+version: **_Windows 11 Enterprise_** (Version: `23H2`, OS build `22631.2428`)
* Compiler+version: -
* Conan version: `2.0.13`
* Python version: `3.11.2`

### Description

Hi,
According to [Conan 2 documentation](https://docs.conan.io/2/reference/commands/cache.html#conan-cache-clean ) (and see also [#14360](https://github.com/conan-io/conan/issues/14360)), I expected to get the Conan cache cleared (everything removed, dirty packages included) after execution of the following commands:
```
conan remove '*'
conan cache clean
conan cache clean -s -b -d -t
```
In fact, this is **not** what happens in my case and quite some stuff related to dirty packages is still there.
This unexpected behavior seems to be related to the following setting in my _global.conf_ file:
`core.cache:storage_path=C:\c2`

By removing this setting (i.e. by having the Conan storage folder in _C:\Users\myhome\\.conan2\p_) the same command sequence correctly removes everything in folders _C:\Users\myhome\\.conan2\p\t_ and _C:\Users\myhome\\.conan2\p\b_, but there are still not empty folders like _C:\Users\myhome\\.conan2\p\motio3f68cc067fec1\b_ and _C:\Users\myhome\\.conan2\p\motio3f68cc067fec1\p_ remaining.

**Comment by memsharded** [comment]
Hi @marausch 

Thanks for reporting.
Quick question: When defining the ``core.cache:storage_path=C:\c2``, after the clean, what is left is empty folders only? Or are there some folders with files?

Can you reproduce with some specific flow? Like with a simple ``conan install --requires=zlib/1.2.13`` it will happen? Or maybe it happens when creating packages from source? Thanks for the feedback!

**Comment by marausch** [comment]
Hi @memsharded 

I cannot share the modules we are working on, but I think I managed to reproduce the issue with the following steps:

1. From an empty folder I started with:
```
conan new cmake_lib -d name=test_cache_clean -d version=0.1.0
```
2. Then I edited _conanfile.py_ adding the following line at the end of the _build()_ method:
`raise ConanException(f"Abort for debugging...")`
just to force an error on package building (no need to `import conan.errors`, BTW).
3. Finally, I tried to create the package with:
```
conan create -pr:b default -pr:h default --user demo --channel experimental .
```
At this point I tried to clear the conan cache with the three commands in question:
```
conan remove '*'
conan cache clean
conan cache clean -s -b -d -t
```
The following picture shows what I can see now in conan cache (I hope I've attached the picture correctly):
![image](https://github.com/conan-io/conan/assets/30287440/ad368b6a-9882-4bb3-a5bc-e38403f8e00d)

Note that I did this test after having deleted the conan cache folder (actually I just renamed the folder `c:\c2\` to `C:\c2sav`).
Originally the cache contained some additional folder such as `C:\c2\motio3f68cc067fec1\b\` containing subfolders and files that I wasn't able to clean away with the commands in question.
But I found out that this is old stuff I produced with previous versions of Conan and belonging to packages that weren't shown anymore by a `conan list '*'` command.

**Comment by jasal82** [comment]
Same problem here. The clean command seems to do nothing. I tried to clean up everything with `conan cache clean "*"` but I still have a lot of folders in `$CACHE/p` and even in `$CACHE/p/b`. Testing in WSL2 with Conan 2.0.17.

**Comment by memsharded** [comment]
But ``$CACHE/p`` is a perfectly valid folder that will contain downloaded packages, and also ``$CACHE/p/b`` is valid for packages that are built locally. This is expected, these are final packages that shouldn't be removed with ``conan cache clean``, these are not temporary folders.

**Comment by jasal82** [comment]
But I assume these packages are used by Conan for certain tasks? I had to remove these folders manually to get my local build working again, because a package with a broken conanfile (which was previously uploaded to the remote) was used instead of the fixed version from the remote.

**Comment by jasal82** [comment]
Maybe there is also a misunderstanding on my side about the term 'cache'. I assumed that `conan cache clean` would be equivalent to `rm -rf ~/.conan/data`.

**Comment by memsharded** [comment]
> Maybe there is also a misunderstanding on my side about the term 'cache'. I assumed that conan cache clean would be equivalent to rm -rf ~/.conan/data.

No, not really. The ``conan cache clean`` is to clean temporary files to save space. It doesn't remove packages, that is done with the ``conan remove`` command.

```
$ conan cache clean -h
usage: conan cache clean [-h] [-v [V]] [-s] [-b] [-d] [-t] [-p PACKAGE_QUERY] [pattern]

Remove non-critical folders from the cache, like source, build and/or download (.tgz store) ones.
```

**Comment by marausch** [comment]
Hi,
I've repeated the test I made on Nov 13, 2023 after having updated to Conan 2.0.16.
I also noticed that, according to the [current documentation](https://docs.conan.io/2/reference/commands/cache.html#conan-cache-clean), I might have used a wrong syntax:
```
conan cache clean
```
instead of:
```
conan cache clean '*'
```
So, this time I did:
```
conan remove '*'
conan cache clean '*'
conan cache clean -s -b -d -t '*'
```
but the result didn't change. There are still the same files and folder left in the cache (apart from some obvious differences).

**Comment by memsharded** [comment]
Thanks for the feedback @marausch 

I have been able to identify the issue, it was indeed specific of using ``core.cache:storage_path``
I am trying a fix in https://github.com/conan-io/conan/pull/15505, if you want to try it from source, feedback welcome.

**Comment by marausch** [comment]
Now it works!
Just doing:
```
conan cache clean
```
(no additional `'*'` seems to be required) there is only an empty folder _b_ and a file _cache.sqlite3_ remaining, which I think is ok.
![image](https://github.com/conan-io/conan/assets/30287440/cb0761a2-c33f-4d0a-84e8-07e9aaa34ed0)

**Comment by xorz57** [comment]
`conan remove "*"` and `rm -rf ~/.conan` seem to work for me.
