### ISSUE TITLE
[question] Problems with installing Poco through Conan

### ISSUE THREAD

**Issue by MadeleineKongshavn** [conan-io/conan#15087]
### What is your question?

Hi, The last couple of days i have been trying to install Poco with the help of Conan. have been following the official guide [Build a simple CMake project using Conan](https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html). Conan seems to be able to download Poco, but the setup of the libraries seems to be missing? The final steps gives me either the error that PocoFoundation.lib cannot be found/open, or the error that it cannot find or include 'Poco/..... I have tried searching for the library PocoFoundation.lib in my entire system, but it does not seem to exist. I am using Windows OS (windows 11) and Visual Studio 2022.

Conan version 2.0.13
cmake version 3.26.4-msvc4

Commands:

`conan install . --output-folder=build --build=missing
`
`cd .\build\
`
`cmake .. --preset conan-default -DCMAKE_BUILD_TYPE=Release
`
`cmake --build .
`

The final steps produces: 
```
PS C:\Users\ronnimad\source\repos\PWYPWebcrawler\build>  cmake --build .
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  Checking Build System
  Building Custom Rule C:/Users/ronnimad/source/repos/PWYPWebcrawler/CMakeLists.txt
  PWYPWebcrawler.cpp
C:\Users\ronnimad\source\repos\PWYPWebcrawler\PWYPWebcrawler\PWYPWebcrawler.cpp(6,10): fatal  error C1083: Cannot open include file: 'Poco/Net/HTTPClien
tSession.h': No such file or directory [C:\Users\ronnimad\source\repos\PWYPWebcrawler\build\PWYPWebcrawler.vcxproj]
```

I have also gotten a different error:
`LINK : fatal error LNK1104: cannot open file 'PocoFoundation.lib' [C:\Users\ronnimad\source\repos\PWYPWebcrawler\build\PWYPWebcrawler.vcxproj]`

Is there some extra steps that i am missing?

[CMakeLists.txt](https://github.com/conan-io/conan/files/13328445/CMakeLists.txt)
[conanfile.txt](https://github.com/conan-io/conan/files/13328446/conanfile.txt)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MadeleineKongshavn 

It seems you could be mixing commands from Linux/single-config systems with Windows/multi-config systems.

The right commands for Windows-Visual Studio would be:
```bash
# Not even need to change folder, if the recipe defined ``cmake_layout``
cmake --preset conan-default 
cmake --build --preset conan-release
```
In short:
- You shouldn't need to pass ``-DCMAKE_BUILD_TYPE=xxxx`` for multi-config systems like Visual Studio.
- You better use the ``presets`` also for building, instead of calling build without presets

Please let us know if that works. If it doesn't it would be helpful to see the full output of the ``conan install . --output-folder=build --build=missing`` command., if you could please share it.

**Comment by MadeleineKongshavn** [comment]
Hi, thanks for responding! I did the following steps:

`conan install . --output-folder=build --build=missing
`
`cmake --preset conan-default 
`
`cmake --build --preset conan-release
`

```
PS C:\Users\ronnimad\source\repos\PWYPWebcrawler> cmake --build --preset conan-release
>>
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  Checking Build System
  Building Custom Rule C:/Users/ronnimad/source/repos/PWYPWebcrawler/CMakeLists.txt
  PWYPWebcrawler.cpp
  PWYPWebcrawler.vcxproj -> C:\Users\ronnimad\source\repos\PWYPWebcrawler\build\Release\PWYPWebcrawler.exe
  Building Custom Rule C:/Users/ronnimad/source/repos/PWYPWebcrawler/CMakeLists.txt
PS C:\Users\ronnimad\source\repos\PWYPWebcrawler>
```

It does give me the .exe file, which is great! :). I was expecting the include statements in the .cpp file to find Poco and no longer give error. i.e "cannot open source file "Poco/Net/HTTPRequest.h" when holding over it etc.

```
#include "Poco/Net/HTTPRequest.h"
#include "Poco/Net/HTTPResponse.h"
#include "Poco/StreamCopier.h"
#include <iostream>
int main()
{
	std::cout << "nothing here :)";
}
```

 Do i need to do something else for that?

**Comment by memsharded** [comment]
> It does give me the .exe file, which is great! :). I was expecting the include statements in the .cpp file to find Poco and no longer give error. i.e "cannot open source file "Poco/Net/HTTPRequest.h" when holding over it etc.

You mean when opening the IDE (Visual Studio)? I think that depends on how it scans the project, the Intellisense, etc, but I'd definitely expect that if it is able to build the project it should be able to find the headers as well and not complaining in the editor. Maybe refreshing the IDE?

It is also important that you select the right configuration in the IDE, to ``Release`` in this case, because you installed the ``Release`` dependencies. If you also want to Debug you might need to do ``conan install .... <same args> -s build_type=Debug`` to also install the Debug dependencies (they might need to build from source, ConanCenter might not have all dependencies in Debug), and then call cmake again.

**Comment by MadeleineKongshavn** [comment]
Hi, thanks again for responding! 

It seems like when it built the project, it made another .sln inside the build folder. This .sln is able to find Poco (with release). 

...\repos\PWYPWebcrawler\build\PWYPWebcrawler.sln -> can find Poco lib
...\repos\PWYPWebcrawler\PWYPWebcrawler.sln -> cannot find Poco lib

Is it possible for me to specify that i want the sln to be outside the build folder?

**Comment by memsharded** [comment]
> It seems like when it built the project, it made another .sln inside the build folder. This .sln is able to find Poco (with release).

>...\repos\PWYPWebcrawler\build\PWYPWebcrawler.sln -> can find Poco lib
>...\repos\PWYPWebcrawler\PWYPWebcrawler.sln -> cannot find Poco lib

>Is it possible for me to specify that i want the sln to be outside the build folder?

Who created the project in the root of the repo? It is not clear.

When you are using CMake, cmake generates a VS solution .sln and VS projects files for you. Those files should be considered temporary and not committed to git. This is the reason they are created inside the ``build`` folder, they are expected to be ``.gitignore``d together with all the other temporary build objects inside the ``build`` folder. Your source repo will not contain a ``.sln`` file at all in the root, just the ``CMakeLists.txt`` file.


If you don't specify ``--output-folder=build``, the files will be generated in the root, but there will be many of them, polluting your project folder, it is really not recommended. This is not that specific to Conan, but how CMake works.

**Comment by memsharded** [comment]
I think we can close this ticket as resolved/outdated, but please create new tickets for any further question or issue that you might have. Thanks for the feedback.
