### ISSUE TITLE
CMake Generate Fails during Conan Build Yet Is Successful Without Conan

### ISSUE THREAD

**Issue by sjgiewont** [conan-io/conan#15081]
### What is your question?

Hello,

Currently running `Conan version 2.0.13` and running into some issues generating a Conan package for a CMake project. 

When building the project via just CMake (no Conan) there are no issue with the build:

```
mkdir -p build && cd build
cmake .. \
    -DMMDEPLOY_BUILD_SDK=ON \
    -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
    -DMMDEPLOY_BUILD_EXAMPLES=ON \
    -DMMDEPLOY_TARGET_DEVICES=cpu \
    -DMMDEPLOY_TARGET_BACKENDS=ort \
    -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR}

make -j$(nproc) && make install
```

I setup what I believe is a pretty straight forward Conanfile to handle this build:

```
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps
from conan.tools.files import collect_libs

class MMDeploy(ConanFile):
    name = "mmdeploy"
    version = "1.3.0"

    # Optional metadata
    license = "MIT License"
    author = "YadaYada"
    url = "https://github.com/open-mmlab/mmdeploy"
    description = "Conan Package for Open-mmlab mmdeploy SDK"

    settings = "build_type"
    default_options = {"onnxruntime/*:shared": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "*"

    generators = "CMakeDeps"

    requires = "onnxruntime/1.15.1", "opencv/4.5.5"

    def package_info(self):
        self.conf_info.update("tools.system.package_manager", {"mode": "install"})
        self.cpp_info.libs = collect_libs(self)

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["MMDEPLOY_BUILD_SDK_MONOLITHIC"] = "ON"
        tc.variables["MMDEPLOY_BUILD_SDK"] = "ON"
        tc.variables["MMDEPLOY_BUILD_SDK_PYTHON_API"] = "ON"
        tc.variables["MMDEPLOY_BUILD_EXAMPLES"] = "ON"
        tc.variables["MMDEPLOY_TARGET_DEVICES"] = "cpu"
        tc.variables["MMDEPLOY_TARGET_BACKENDS"] = "ort"
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure(variables={"ONNXRUNTIME_DIR": self.dependencies["onnxruntime"].package_folder}) 
        cmake.build()


    def package(self):
        cmake = CMake(self)
        cmake.install()
```

All dependencies install without an issue yet the cmake generate step seems to fail when I try to create the package:

`conan create . --build=missing -u -s build_type=Release -c tools.system.package_manager:mode=install` ==>

```
-- Conan: Including build module from '/root/.conan2/p/openc3a3cef6bde3ab/p/lib/cmake/conan-official-opencv-variables.cmake'
-- Configuring done
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_execution" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_cpu_device" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_graph" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_directory_model" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_operation" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_operation_cpu" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_operation_dummy" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_transform" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_transform_module" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_ort_net" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_net_module" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmcls" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmdet" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmseg" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmocr" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmedit" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmpose" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmrotate" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmaction" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_common_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_model_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_executor_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_pipeline_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_classifier_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_detector_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_segmentor_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_text_detector_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_text_recognizer_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_restorer_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_pose_detector_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_pose_tracker_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_rotated_detector_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_video_recognizer_obj" that is not in any export set.
CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_execution" that is not in any export set.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

mmdeploy/1.3.0: ERROR: 
Package 'b162f5a4ae71b2919c53a536481ffe85a57f6b4a' build failed
mmdeploy/1.3.0: WARN: Build folder /root/.conan2/p/b/mmdep4f69a587793cb/b/build/Release
*********************************************************
Recipe 'mmdeploy/1.3.0' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: mmdeploy/1.3.0: Error in build() method, line 46
        cmake.configure(variables={"ONNXRUNTIME_DIR": self.dependencies["onnxruntime"].package_folder})
        ConanException: Error 1 while executing
 ```

I have spent countless hours trying different settings and setups but I have still not been able to determine a solution or the root cause. Any tips or advice would be much appreciated. I'm not sure this is a bug in Conan 2 `CMakeToolchain` or just user error.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sjgiewont 

Thanks for your question.

I have some quick tips:

- It is not recommended to use only ``build_type`` for packages that compile, but use the full ``os``, ``compiler``, ``arch``, ``build_type``. The build system integrations like CMakeToolchain and CMakeDeps expect things like ``os`` to be defined for many conditionals.
- This ``self.conf_info.update("tools.system.package_manager", {"mode": "install"})`` is not recommended in recipes, but something to be defined in profiles. Installing packages at the system level shouldn't be something that happens because you "required" something. It is fine if you still want to do it, but you should be aware that this can be surprising.
- The step ``cmake.configure(variables={"ONNXRUNTIME_DIR": self.dependencies["onnxruntime"].package_folder})`` should be done in ``generate()`` somehow, so if you want to do ``conan install + cmake`` flow you should be able. But if you put things in the ``build()`` that will only work when you ``conan create`` the package, but recipes should also work for local development.


But in order to investigate and try to help, it would be good to know about the ``CMakeLists.txt``. It seems it has something ``install(EXPORT "MMDeployTargets" ...)`` that is causing issues, but it is difficult to know without being able to reproduce. Could you share it or is it private?

**Comment by sjgiewont** [comment]
Hello @memsharded thanks for getting back to me so quickly! 

1. I added the `os`, `compiler`, `arch` as well. I didn't think that it would be an issue since i'm locking down those dependencies with Docker to create my conan package. 
2. Totally agree with not including the `tools.system.package_manager:mode=install` in the Conanfile. After understanding the profiles more I realize that's the way to go.
3. So I think this line was the cuplrit! I moved this to the `generate()` stage and suddenly I was able to get the cmake generate step to succeed! I didn't have this in the generate stage to start because I was running into earlier issues.

Thanks for all the help! I was able to build this package and consume it in another project successfully during build and runtime!

**Comment by memsharded** [comment]
Fantastic! Happy to hear that you made it work.
Don't hesitate to open new tickets for any further question or issue that you might have. Thanks for the feedback!

**Comment by anhKhOa0902** [comment]
usr/bin/ld: libOpenSTA.a(Power.cc.o): in function `sta::Power::evalBddDuty(DdNode*, sta::Instance const*)':
Power.cc:(.text+0x282b): undefined reference to `Cudd_IsConstant'
/usr/bin/ld: Power.cc:(.text+0x283b): undefined reference to `Cudd_ReadOne'
/usr/bin/ld: Power.cc:(.text+0x2854): undefined reference to `Cudd_ReadLogicZero'
/usr/bin/ld: Power.cc:(.text+0x28b4): undefined reference to `Cudd_E'
/usr/bin/ld: Power.cc:(.text+0x28cf): undefined reference to `Cudd_T'
/usr/bin/ld: Power.cc:(.text+0x28eb): undefined reference to `Cudd_NodeReadIndex'
/usr/bin/ld: Power.cc:(.text+0x28f9): undefined reference to `Cudd_ReadPerm'
/usr/bin/ld: libOpenSTA.a(Power.cc.o): in function `sta::Power::evalDiffDuty(sta::FuncExpr*, sta::LibertyPort*, sta::Instance const*)':
Power.cc:(.text+0x2a7a): undefined reference to `Cudd_NodeReadIndex'
/usr/bin/ld: Power.cc:(.text+0x2a8b): undefined reference to `Cudd_bddBooleanDiff'
/usr/bin/ld: Power.cc:(.text+0x2a96): undefined reference to `Cudd_Ref'
/usr/bin/ld: Power.cc:(.text+0x2ab9): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: Power.cc:(.text+0x2ac8): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: libOpenSTA.a(Power.cc.o): in function `sta::Power::evalBddActivity(DdNode*, sta::Instance const*)':
Power.cc:(.text+0x2bb8): undefined reference to `Cudd_NodeReadIndex'
/usr/bin/ld: Power.cc:(.text+0x2bcb): undefined reference to `Cudd_bddBooleanDiff'
/usr/bin/ld: Power.cc:(.text+0x2bd6): undefined reference to `Cudd_Ref'
/usr/bin/ld: Power.cc:(.text+0x2bf9): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: libOpenSTA.a(Power.cc.o): in function `sta::Power::evalActivity(sta::FuncExpr*, sta::Instance const*)':
Power.cc:(.text+0x2d2c): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: libOpenSTA.a(Power.cc.o): in function `sta::Power::findInputInternalPower(sta::Pin const*, sta::LibertyPort*, sta::Instance const*, sta::LibertyCell*, sta::PwrActivity&, float, sta::Corner const*, sta::PowerResult&)':
Power.cc:(.text+0x33a8): undefined reference to `Cudd_NodeReadIndex'
/usr/bin/ld: Power.cc:(.text+0x33b9): undefined reference to `Cudd_bddBooleanDiff'
/usr/bin/ld: Power.cc:(.text+0x33c4): undefined reference to `Cudd_Ref'
/usr/bin/ld: Power.cc:(.text+0x33e9): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: Power.cc:(.text+0x33f8): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: libOpenSTA.a(Power.cc.o): in function `sta::Power::findInputDuty(sta::Instance const*, sta::FuncExpr*, sta::InternalPower*)':
Power.cc:(.text+0x35ec): undefined reference to `Cudd_NodeReadIndex'
/usr/bin/ld: Power.cc:(.text+0x35fd): undefined reference to `Cudd_bddBooleanDiff'
/usr/bin/ld: Power.cc:(.text+0x3608): undefined reference to `Cudd_Ref'
/usr/bin/ld: Power.cc:(.text+0x362b): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: Power.cc:(.text+0x363a): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: libOpenSTA.a(Sim.cc.o): in function `sta::Sim::funcBddSim(sta::FuncExpr const*, sta::Instance const*)':
Sim.cc:(.text+0x87b): undefined reference to `Cudd_NodeReadIndex'
/usr/bin/ld: Sim.cc:(.text+0x898): undefined reference to `Cudd_ReadOne'
/usr/bin/ld: Sim.cc:(.text+0x8a9): undefined reference to `Cudd_bddCompose'
/usr/bin/ld: Sim.cc:(.text+0x8b4): undefined reference to `Cudd_Ref'
/usr/bin/ld: Sim.cc:(.text+0x8c9): undefined reference to `Cudd_ReadLogicZero'
/usr/bin/ld: libOpenSTA.a(Sim.cc.o): in function `sta::Sim::evalExpr(sta::FuncExpr const*, sta::Instance const*)':
Sim.cc:(.text+0x924): undefined reference to `Cudd_ReadLogicZero'
/usr/bin/ld: Sim.cc:(.text+0x931): undefined reference to `Cudd_ReadOne'

You can help me to fix  errors below. Thanks!!

/usr/bin/ld: Sim.cc:(.text+0x953): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: libOpenSTA.a(Sim.cc.o): in function `sta::Sim::functionSense(sta::FuncExpr const*, sta::Pin const*, sta::Instance const*)':
Sim.cc:(.text+0xb7e): undefined reference to `Cudd_NodeReadIndex'
/usr/bin/ld: Sim.cc:(.text+0xb8e): undefined reference to `Cudd_Increasing'
/usr/bin/ld: Sim.cc:(.text+0xb9a): undefined reference to `Cudd_ReadOne'
/usr/bin/ld: Sim.cc:(.text+0xbb6): undefined reference to `Cudd_Decreasing'
/usr/bin/ld: Sim.cc:(.text+0xbc1): undefined reference to `Cudd_ReadOne'
/usr/bin/ld: Sim.cc:(.text+0xbd9): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: libOpenSTA.a(Bdd.cc.o): in function `sta::Bdd::Bdd(sta::StaState const*)':
Bdd.cc:(.text+0x29): undefined reference to `Cudd_Init'
/usr/bin/ld: libOpenSTA.a(Bdd.cc.o): in function `sta::Bdd::nodePort(DdNode*)':
Bdd.cc:(.text+0x13c): undefined reference to `Cudd_NodeReadIndex'
/usr/bin/ld: libOpenSTA.a(Bdd.cc.o): in function `sta::Bdd::~Bdd()':
Bdd.cc:(.text+0x20d): undefined reference to `Cudd_Quit'
/usr/bin/ld: libOpenSTA.a(Bdd.cc.o): in function `sta::Bdd::~Bdd()':
Bdd.cc:(.text+0x2ad): undefined reference to `Cudd_Quit'
/usr/bin/ld: libOpenSTA.a(Bdd.cc.o): in function `sta::Bdd::ensureNode(sta::LibertyPort const*)':
Bdd.cc:(.text+0x4a0): undefined reference to `Cudd_bddIthVar'
/usr/bin/ld: Bdd.cc:(.text+0x641): undefined reference to `Cudd_Ref'
/usr/bin/ld: libOpenSTA.a(Bdd.cc.o): in function `sta::Bdd::funcBdd(sta::FuncExpr const*)':
Bdd.cc:(.text+0x6c0): undefined reference to `Cudd_ReadOne'
/usr/bin/ld: Bdd.cc:(.text+0x6d0): undefined reference to `Cudd_Ref'
/usr/bin/ld: Bdd.cc:(.text+0x6f0): undefined reference to `Cudd_ReadLogicZero'
/usr/bin/ld: Bdd.cc:(.text+0x753): undefined reference to `Cudd_Ref'
/usr/bin/ld: Bdd.cc:(.text+0x763): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: Bdd.cc:(.text+0x77c): undefined reference to `Cudd_RecursiveDeref'
/usr/bin/ld: Bdd.cc:(.text+0x7d0): undefined reference to `Cudd_Ref'
/usr/bin/ld: Bdd.cc:(.text+0x814): undefined reference to `Cudd_bddAnd'
/usr/bin/ld: Bdd.cc:(.text+0x858): undefined reference to `Cudd_bddXor'
/usr/bin/ld: Bdd.cc:(.text+0x8a0): undefined reference to `Cudd_Ref'
/usr/bin/ld: Bdd.cc:(.text+0x8bf): undefined reference to `Cudd_bddOr'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sta.dir/build.make:89: sta] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/sta.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by memsharded** [comment]
@anhKhOa0902 sorry, your comment here doesn't make any sense.

Please create a new ticket for it if you need help, providing a complete description and reproduction steps. Thanks.
