### ISSUE TITLE
[bug] `<packageName>_INCLUDE_DIRS` variable created with `<packageName>` with lower case 

### ISSUE THREAD

**Issue by neucer** [conan-io/conan#15085]
### Environment details

* Operating System+version: Ubuntu 22.04.3
* Compiler+version: gcc-12 12.3.0
* Conan version: 2.0.13
* Python version: 3.10.12

### Steps to reproduce

conan file:
```
[requires]
protobuf/3.21.12

[generators]
CMakeDeps
CMakeToolchain
```

`find_package(Protobuf REQUIRED)` is expected to create a variable `Protobuf_INCLUDE_DIRS` but it creates a variable `protobuf_INCLUDE_DIRS`.

**Comment by memsharded** [comment]
Hi @neucer 

Thanks for your report.
The ``CMakeDeps`` generator is not expected to create all the variables with exactly the same variables casing as the upstream files, but the same targets. The properties defined in the dependency recipe are aimed to define the correct target name, which is the recommended way to use the package.

The official project config cmake files (https://github.com/protocolbuffers/protobuf/blob/main/cmake/protobuf-module.cmake.in), contains:

```
# Backwards compatibility
# Define upper case versions of output variables
```
It defines those variables just as a backwards compatible thing with the legacy module file. While ``CMakeDeps`` can still generate some legacy module files if desired, it doesn't aim for full upstream compatibility with the legacy modules if official config files with targets exists.

**Comment by neucer** [comment]
An external project that i can't edit needs protobuf. It searched the include directories in `Protobuf_INCLUDE_DIRS` but does not link to it. How can I achieve that? Do I need to use a different generator?

**Comment by memsharded** [comment]
I see. The common way to approach this is applying a patch on the downloaded source, have a look to https://docs.conan.io/2/examples/tools/files/patches/patch_sources.html.

This is done tons of times in recipes in ConanCenter, that there is no access to the source code, but there are things that need to be fixed to allow proper building and packaging.

**Comment by neucer** [comment]
Are you suggesting changing `include_directories(${Protobuf_INCLUDE_DIRS})` to `include_directories(${protobuf_INCLUDE_DIRS})` in the external project? I'm not sure I can do that, I'm not the one downloading it like in the example. It's a nested dependency, and possibly common and in use by others. But assuming I can edit it, is it safe to rely on the existence of `protobuf_INCLUDE_DIRS`?

**Comment by memsharded** [comment]
> Are you suggesting changing include_directories(${Protobuf_INCLUDE_DIRS}) to include_directories(${protobuf_INCLUDE_DIRS}) in the external project?

Yes, that patch.

> I'm not sure I can do that, I'm not the one downloading it like in the example. It's a nested dependency, and possibly common and in use by others.

There is someone or some job somewhere that is doing the download of the sources and calling ``conan install`` to bring the dependencies for it. The one with the ``conanfile.txt`` that you report above that is executing ``conan install``. That job executing ``conan install`` has full access to its ``CMakeLists.txt``, so it should be able to change it. 
This task can be easier and more automated moving that ``conanfile.txt`` to a ``conanfile.py`` and leveraging the different methods for ``source()`` and patching that ``conanfile.py`` provides.

> But assuming I can edit it, is it safe to rely on the existence of protobuf_INCLUDE_DIRS?

The ``protobuf_INCLUDE_DIRS`` variable is still an implementation detail. It would be much better to patch the CMakeLists.txt so it does something like ``target_link_libraries(..... protobuf::protobuf)`` which is the recommended way to consume dependencies in CMake. 
But if you can't do that, the implementation of ``CMakeDeps`` is relatively stable, it is unlikely that it will change those variables, so it is relatively safe to do that. No absolute guarantees, but it is quite unlikely to change.
