### ISSUE TITLE
How to create alias in Conan 2.0

### ISSUE THREAD

**Issue by rajesh-kare** [conan-io/conan#15096]
### What is your question?

'alias' is not a Conan command. See 'conan --help'.

How to create alias in Conan 2.0?
Problem:
I have a package that has an option of target. target(-o target=target1) value can be target1 , target2... 5 possible values for my package.
If my current package version is 2.4. I have 5 packages with version 2.4 each package corresponds to one target.
Now some change in code only needed for target 3 I increased version and 2.5 is available for target 3 and 2.4 for other 4 targets. Now if I want to download package for target 1 , version range is resolving to 2.5 but 2.5 target 1 package will now be there. I solved this using alias in Conan 1.0
pkg_name/target_1 -> latest available for that target.
With alias removed for 2.0.My code is broken. How to solve this?
conan -v    
Conan version 2.0.13

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @rajesh-kare,

Thanks for the question. The `conan alias` command has been replaced in 2.0 by using the `conan new` command like but the attribute is still there:

```
conan new alias -d name=pkg -d version=latest -d target=0.2 -f
```

Hope this helps.

**Comment by rajesh-kare** [comment]
No. It didn't help
Conan new alias  not adding user , channel
uploaded the alias package and Conan install on this alias package brings nothing

command 
Conan new alias -d name=pkg_name -d version=latest -d user=usr -d channel=chnl -d target=2.5@usr/chnl

All these things works beautifully with alias command in Conan 1.0.
how to create some package which always points to some version package(with settings)

**Comment by czoido** [comment]
Hi @rajesh-kare,

Maybe it's the syntax? Are you requiring the alias using the parenthesis syntax? That syntax is now compulsory for Conan 2.0. So you should have something like: `requires = "pkg_name/(latest)@usr/chnl"` or it will be resolved as a normal package.

Also, please note that in Conan 2.0, the use of aliases is no longer recommended. This change is due to significant improvements in Conan 2.0 regarding version handling and version ranges, which surpass the capabilities of Conan 1.X. Please read the comments in these issues: 
- https://github.com/conan-io/conan/issues/14956
- https://github.com/conan-io/conan/issues/13474

**Comment by rajesh-kareti-infovision** [comment]
Thanks for quick response.
conan install --requires="pkgname/2.5.0.0@master/test" -o target=target_1   -r test_repo --deployer=direct_deploy
Above command is passing and getting package successfully

conan install --requires="pkgname/[ >2.0.0.0]@master/test" -o target=target_1  -r test_repo --deployer=direct_deploy
This command failing saying
pkgname/2.5.0.0@master/test: Invalid: 'options.target' value not defined

version is resolved successfully but option value is not applied. Is there a different way to provide option when we use version ranges. This problem also i never encountered in conan 1.0

**Comment by memsharded** [comment]
Hi @rajesh-kareti-infovision 

That would be a different issue, it seems it is not related to the previous one. 
The general recommendation would be to close this one, then open a new one for the new issue.
In your case, I think you might be missing the ``-o pkgname*:target=value`` pattern. For most cases you want to specify the package to which the option applies. This is recommended also in Conan 1.

**Comment by rajesh-kare** [comment]
Thanks for the quick response @czoido  and @memsharded

I am able to use alias and options with the way you mentioned and it worked.
Please close this thread as the issue is solved with these suggestions
