### ISSUE TITLE
test_package runs package() twice if no_copy_source is True

### ISSUE THREAD

**Issue by MarcoKoch** [conan-io/conan#1509]
Here is a small recipe that demonstrates some strange behavior:
https://github.com/MarcoKoch/conan-test_package-bug-demo

Basically, if a `conanfile.py` defines `no_copy_source = True`, its `package()` method is run twice when built with the `conan test_package` command.
With `no_copy_source = False`, it is only run once (as expected). It is alo only run once if I build the package directly with `conan package`, regardless of the value of `no_copy_source`.

**Comment by memsharded** [comment]
This is expected behavior. ``package`` must also take files from the sources (like headers), that is the ``source`` folder when ``no_copy_source = True``. So the only way to achieve this is to call it twice, once over the ``source`` folder and other over the ``build`` folder.

**Comment by memsharded** [comment]
Maybe add it to the documentation of ``no_copy_source``?

**Comment by MarcoKoch** [comment]
Thanks for the fast answer again.
An addition to the documentation would be nice. With your explanation it makes sense, though it is not very intuitive if one does not know the internals of conan.

What brought me to the issue was that I had something like `os.mkdir("licenses")`in the `package` method, which then failed on the second run as the directory already existed.

Also, is it intentional then that `package` is only run once if I build the package directly with the `conan package` command? To my current understanding so far, the packaging should be the same then.

**Comment by memsharded** [comment]
Hi Marco,

Good point, if you run ``conan package`` and provide both ``--source_folder`` and ``--build_folder`` it should call ``package()`` twice, same reasoning as above :)

Regarding the ``os.makedirs()`` you probably want to use the ``mkdir()`` or ``save()`` helpers (``from conans.files import mkdir, save``), as they create intermediate directories and do not fail if the directory exists.

Just added https://github.com/conan-io/docs/commit/46f10a1e7ea050f661021a175835e303e329a0fe and https://github.com/conan-io/docs/commit/72b1fcbee094a33299567b11c0424874e5905aea to the docs. Don't be afraid to propose your own improvements to the docs when you feel something is not clear enough :)

Could this issue be closed now?

Thanks very much for your feedback!

**Comment by MarcoKoch** [comment]
Thanks, it's much clearer now. :)

Do you mean `conans.util.files`? There seems not to be a `conans.files`.
I completely missed about that module. Maybe those functions could be added to the 'Reference' section in the docs? I will see whether I can find some time to write something up in the next couple of days. ;)

Apart from that the issue can be closed :)

**Comment by memsharded** [comment]
Yes, you are right, it is: ``from conans.util.files import save``

https://github.com/conan-io/docs/issues/254

Thanks!

**Comment by lasote** [comment]
The "tools" module has currently available some of the file methods (imported from files), 
load, save, sha256sum, sha1sum, md5sum, md5
So you can do `tools.save()`.

Probably we should add the rest, like "mkdir", "rmdir" and others. WDYT @memsharded ?

**Comment by memsharded** [comment]
Yes, can be added. Key is docs, however.
