### ISSUE TITLE
What's the proper Conan 2.0 way of storing additional attributes in conan packages?

### ISSUE THREAD

**Issue by jegabe** [conan-io/conan#15094]
### What is your question?

Hi everybody!

In our company, we used to use the `self.user_info` field in the ``def package_info(self)` method to store additonal attributes of our packages (conan 1.x). They are file system paths into the package folder where we store meta-info such as path to a license info file (SPDX JSON); something like that:

```python
def package_info(self):
            self.user_info.license_spdx_file_path = <some path into the package>
```

We were then later able to collect all of these files in the dependency tree to, for example, build a list of open source licenses used in our software product by inspecting the `deps_user_info` array in the package consuming all of the other ones.

What would the proper conan 2.x way of doing something like this look like? We could of course use some conventions on those special files so we can scan the package folders without having an attribute in the conanfile.py, but maybe you have a much better solution in mind...

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @jegabe thanks a lot for your question!

With Conan 2 the recommended approach for this case is to use a deployer to fetch the licenses of the packages. We already have something that you can use as an inspiration in https://github.com/conan-io/conan-extensions/tree/main/extensions/deployers

The key here if you need control over which files would need to be copied over is the ability to use `self.conf_info.define("user.myorg.licenses:file", "<my path>")` (or whatever conf key works best for your use case, where the `user.` begining literal is needed) in your recipes' `package_info()` and then query it in the deployer by checking the `self.dependencies` attribute ([Docs here](https://docs.conan.io/2/reference/conanfile/methods/generate.html#self-dependencies)) of your graph's root conanfile.

An incomplete example of the deployer based on the first link would thus look something like this:

```py
def deploy(graph, output_folder, **kwargs):
    conanfile = graph.root.conanfile
    ... extra setup ...

    # For each dep
    for r, dep in conanfile.dependencies.items():
        if d.package_folder is None:
            continue
        
        # Get our license file which the conf points to
        path = dep.conf_info.get("user.myorg.licenses:file")
        if path is not None:
            copy(conanfile, path, dep.package_folder, <your_destination_folder_derived_from_output_folder>)

... rest of your deployer ...
```

And you would then fetch them with `conan install --requires=your/package --deployer=licenses` (Or `conan graph info`)

You might also want to make sure you disable skipping packages that Conan does by default in the graph by setting the `tools.graph:skip_binaries` conf to True.

Let me know if that helps, else feel free to ask more questions, we're happy to help where possible :)

**Comment by dazze1812** [comment]
Does this work?
`path = dep.conf_info.get("user.myorg.licenses:file")`

I thought conf_info was only available for first level tool requirements.

**Comment by memsharded** [comment]
``path = dep.conf_info.get("user.myorg.licenses:file")`` is possible to read directly from dependencies when explicitly iterating or visiting them. Note the object is ``dep``, not ``self``.

What is only automatically propagated from dependencies ``conf_info`` to the current recipe ``self.conf`` is that case of direct tool-requires.
