### ISSUE TITLE
[question] How to set cmake.cmake_layout:build_folder_vars in conan.conf? (Conan 1.x)

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15098]
### What is your question?

I cannot set `cmake.cmake_layout:build_folder_vars` in conan.conf (Conan 1.x):

```
D:\>conan config set tools.cmake.cmake_layout:build_folder_vars="['settings.compiler', 'options.shared']"

D:\>conan config get tools.cmake.cmake_layout:build_folder_vars
ERROR: 'cmake.cmake_layout:build_folder_vars' doesn't exist in [tools]
```
After `conan config set ...` conan.conf contains the following:
```
[tools]
cmake.cmake_layout:build_folder_vars = ['settings.compiler', 'options.shared']
```
I suspect the problem is in the comma character in the parameter name. Maybe some quoting is required?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @db4,

Thanks for your question. The problem here is that you are trying to put the configuration in the wrong file. should be defined in the [global.conf](https://docs.conan.io/1/reference/config_files/global_conf.html) (not in the [conan.conf](https://docs.conan.io/1/reference/config_files/conan.conf.html)) file with the new configuration mechanism compatible with 2.0 (it can also be passed in profiles via `[conf]` or by the command line with the `-c` argument)

Also, please, be aware that the `conan config set` command does not work with this configuration mechanism. We tried to avoid commands that just serve to modify files in 2.0.

Hope this helps!

**Comment by db4** [comment]
Hi @czoido 
 
> Thanks for your question. The problem here is that you are trying to put the configuration in the wrong file. should be defined in the [global.conf](https://docs.conan.io/1/reference/config_files/global_conf.html) (not in the [conan.conf]

Sorry, I didn't change `conan.conf` manually, I just called `conan config set ...`. If this command modifies the wrong file, isn't it a bug?

> Also, please, be aware that the `conan config set` command does not work with this configuration mechanism. We tried to avoid commands that just serve to modify files in 2.0.

Yes, I know that, but I need to make it work on Conan 1.x

**Comment by db4** [comment]
Some additional notes. I added `tools.cmake.cmake_layout:build_folder_vars` and it works, thank you. But I see some inconsistency here. `conan config list` shows this setting, but `conan config get` can't read it:
```
D:\>conan config get tools.cmake.cmake_layout:build_folder_vars
ERROR: 'tools' is not a section of conan.conf
```
If `conan config get/set` is not intended to work with `tools` settings, maybe more meaningful error message should be printed? Something like `Cannot get/set tools. ..., please edit it manually in global.conf`?

**Comment by czoido** [comment]
> Some additional notes. I added `tools.cmake.cmake_layout:build_folder_vars` and it works, thank you. But I see some inconsistency here. `conan config list` shows this setting, but `conan config get` can't read it:
> 
> ```
> D:\>conan config get tools.cmake.cmake_layout:build_folder_vars
> ERROR: 'tools' is not a section of conan.conf
> ```
> 
> If `conan config get/set` is not intended to work with `tools` settings, maybe more meaningful error message should be printed? Something like `Cannot get/set tools. ..., please edit it manually in global.conf`?

Hi @db4, I'm glad that it worked. Thanks for the suggestion, we'll take that into account.

**Comment by memsharded** [comment]
Conan 1.X is no longer getting this kind of changes, so closing this as solved. Thanks for the feedback.
