### ISSUE TITLE
[bug] PkgConfig not using buildenv?

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#15099]
### Environment details

* Conan version: 1.61.0

### Steps to reproduce

When I use `PkgConfig` in a recipe which has a Yocto toolchain package in its build requirements the environment variables set by this package via `buildenv_info` are not visible to `PkgConfig`. However, when I set the same variables with `env_info` it works fine. I think this is not the intended behavior. Yocto toolchains set `PKG_CONFIG_PATH` so that the `pkg-config` executable can find the correct `.pc` files. Without this variable it will query the host system instead.

**Comment by jasal82** [comment]
But it could also be that I am simply using it incorrectly. What is the intended pattern for passing environment variables like `CC`, `CXX`, `CFLAGS` and so on from a `build_requires` to other recipes in the dependency graph? Following the naming scheme I would have thought that `buildenv_info` is the correct one, but the current documentation is a bit thin.

**Comment by memsharded** [comment]
Sorry this was not responded back then.

There is a more thorough discussion about this in https://github.com/conan-io/conan/issues/14422, and the solution is being documented in https://github.com/conan-io/docs/pull/3811. I think this ticket can be closed, and we can follow up in those other ones, thanks!
