### ISSUE TITLE
[question] How to validate that a certain host context requirement is compatible with a certain build requirement?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#15106]
### What is your question?

Hi,

We want to validate that a certain build context requirement is "compatible" with a certain host context requirement when doing a conan install. If it is not compatible the conan install shall fail with an exception/error.

I have read in the documentation that for validating whether dependencies can be consumed or the current package can be built the validate() and validate_build() function can be used.

Is it possible to access the build-context and host-context-dependency graph within these functions?
If so do you have some example code for this?

PS. We are still using Conan 1.x so the code shall ideally be working with Conan 1.x.

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @MTomBosch thanks a lot for your question.

Beginning in Conan 1.38, `self.dependencies` is able to give you the necessary info you're looking for. [This section in the docs](https://docs.conan.io/1/reference/conanfile/dependencies.html#iterating-dependencies) goes over the usage of `self.dependencies.host` etc. Let us know if you need any further help on this after reading that section, happy to help!

**Comment by MTomBosch** [comment]
Yes. Thank you a lot. 

Next time I will search longer in the official docs ;)

**Comment by MTomBosch** [comment]
@RubenRBS Maybe one last question: Looking here (https://docs.conan.io/1/reference/conanfile/dependencies.html#dependencies-interface) it seems to me that a package can only exist as either build or host context dependency, correct?

**Comment by AbrilRBS** [comment]
I'm not quite sure I follow you. A recipe can exist in both contexts at once - glibc & protobuf are common examples in CCI.

As you're still on Conan 1.X there might be some extra insights I'm yet unaware of, but I don't think it works too different once you're using two profiles

**Comment by MTomBosch** [comment]
In this example taken from the official docs:

```
def generate(self):
        openssl = self.dependencies["openssl"]
        # access to members
        openssl.ref.version
        openssl.ref.revision # recipe revision
        openssl.options
        openssl.settings
```

I can see that the deps are a dict and I am asking for the dependency called openssl. If now openssl is used as requirement in build and host context what do I get in above example when looking into openssl.settings?
Which settings are this, the ones from build or host context?

PS. We are using build and host profiles.

**Comment by MTomBosch** [comment]
@RubenRBS Would be very nice if you could clear my doubt given in the previous comment. Thank you

**Comment by franramirez688** [comment]
Hi @MTomBosch 

I think that you could do something like this:

```python
# Build context
build_openssl = self.dependencies.build["openssl"]
# Host context
host_openssl = self.dependencies.host["openssl"]
# Each one will have its own refs, settings, options belonging to each own context
print(build_openssl.settings.compiler)  # will print build context compiler
print(host_openssl.settings.compiler)  # will print host context compiler
```
