### ISSUE TITLE
[question] Transitive handling of options defined in a requirement

### ISSUE THREAD

**Issue by PiJ82** [conan-io/conan#15100]
### What is your question?

Hi everyone,

I'm using conan 1.61, python 3.10.

I have some questions regarding the handling of options in requirements and downstream conan recipes using those requirements.
I'll try to explain with the option `shared`, because it is common to define it in conanfiles, but it might probably be any other option (see Footnote).

I have three conanfiles.

---
conanfile.py of `lib_a`:
```py
class LibAConanFile(ConanFile):
    name = "lib_a"
    options = { "shared": [True, False] }
    default_options = { "shared": False }
    package_type = "shared-library"
    # [...]
```
Let's say, `lib_a` was created with `shared=False` and `shared=True`, so both variants exist in the conan cache.

---
conanfile.py of `package_a` requiring `lib_a`:
```py
class PackageAConanFile(ConanFile):
    name = "package_a"
    package_type = "shared-library"
    # [...]
    
    def requirements(self):
        self.requires("lib_a/1.0.0")
```
Let's say, `package_a` was created with `lib_a:shared=True`.

---
conanfile.py of `package_b` requiring `package_a`:
```py
class PackageBConanFile(ConanFile):
    name = "package_b"
    package_type = "shared-library"
    # [...]
    
    def requirements(self):
        self.requires("package_a/1.0.0")
```
Let's say, I want to create `package_b` with `lib_a:shared=False`.

To my understanding, the options provided for `lib_a` to create `package_a` and `package_b` collide. So I expected `conan create` to fail for `package_b`. But to my surprise, `conan create` went through successfully.

Could someone clarify why this doesn't fail?
Is the described behavior correct or is this a bug/feature in conan?
Or is there something I'm missing here?

For the concrete example of option `shared`, my thoughts are:
* If `package_a` is built with `lib_a:shared:True` and `package_a` doesn't copy any shared libraries (*.dll, *so) files from the `lib_a` into its own package folder, `lib_a` must exist in the conan cache when linking the library from `package_a`.
* If `package_b` is built with `lib_a:shared=False`, the required symbols for `lib_a` are missing for library `package_a` , because required `lib_a` package only provides the static libraries not built into `package_a`. So, linking `package_b` against `package_a` should fail and thus the given options for `lib_a` collide.

It gets even more _interesting_ if `lib_a` would provide more options (like e.g.. `boost` does with options `without_xxx`).

## Footnote
I tried the scenario with `boost/1.79` and options `boost:zlib=True` and `boost:bzip2=True` for `package_a` and `boost:zlib=False` and `boost:zlib=False` for `package_b`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PiJ82 

Some quick preliminary feedback:
- the ``package_type`` is ignored in Conan 1.X
- The `` package_type = "shared-library"`` of the first package would be incorrect in Conan 2.0 if the package has an option. The correct one is either not defining it or `` package_type = "library"``

> To my understanding, the options provided for lib_a to create package_a and package_b collide. So I expected conan create to fail for package_b. But to my surprise, conan create went through successfully.

I think you are seeing the effect of the options priorities, and general Conan priorities. The rule is that the "downstream" consumer or user has always higher priority. If you specify in your command line an option like ``pkga:option=value`` then ``pkga`` will get that option, no matter what is defined by other packages in the middle. Your definition has higher priority and overrides the intermediate packages one.

In general:
- It is better if packages don't change the options themselves, just use the defaults by default
- Options are defined in profiles, which allows to apply them consistently accross full dependency graph.

The computation of the ``package_id`` and what needs to be build from source is much much better in Conan 2.0. Conan 1.X do not distinguish by default depending on one static or shared library, it might even think that it is the same binary, which it isn't, and it might be necessary to change the default package-id-mode in Conan 1.X to have something acceptable when doing shared libraries.

**Comment by PiJ82** [comment]
Hi @memsharded,

please excuse the delayed reply.

Thanks for the clarification. I also read some further information in the [documentation](https://docs.conan.io/1/devtools/build_requires.html#build-requires) about the `tool_requires` and it makes sense to me now.

**Comment by memsharded** [comment]
No prob @PiJ82 thanks for the feedback.
Then, could we consider this question solved and close the ticket? Thanks!
