### ISSUE TITLE
[question] How to cmake install a Debug version on Windows

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#15105]
### What is your question?

Hello,

I am uncertain about a workflow regarding Debug versions.

Here is my profile:
```txt
[settings]
arch={{detect_api.detect_arch()}}
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows

cast*/*:build_type=Debug
cast*/*:compiler.cppstd=17

[conf]
cast*/*:tools.build:skip_test=False
cast*/*:tools.env.virtualenv:powershell=True
cast*/*:tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
```

I build my project with `conan build -verror .\core --profile:host "windows-msvc-debug" --profile:build "windows-msvc-debug"` and everything goes fine.

However, running `cmake --install .\core\build\windows-msvc-193-x86_64 --prefix test"` tries to install the Release version of my project:
```powershell
-- Install configuration: "Release"
[...]
CMake Error at core/build/windows-msvc-193-x86_64/cmake_install.cmake:104 (file):
  file INSTALL cannot find
  "D:/Documents/CAST/core/build/windows-msvc-193-x86_64/Release/core.dll":
  File exists.
```

Which command am I supposed to run to allow a `cmake install` of the `Debug` version? Thanks in advance

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @Todiq thanks a lot for your question.

For multiconfiguration scenarios, you probably want to add [`--config Debug`](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-install-config) to your CMake invocation. Let me me know if that helps :)

**Comment by Todiq** [comment]
That worked, thank you :)
