### ISSUE TITLE
[question] buildenv_info confusion

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#15117]
### What is your question?

I'm a bit confused by the new environment handling and the multitude of new variables that have been introduced. I was under the impression that `buildenv_info` should be used to store environment variables required for building. So I changed all of our toolchain SDK recipes so that they do something like

```python
def package_info(self):
  self.buildenv_info.define("CC", "arm-oe-linux-gnueabi-gcc")
  self.buildenv_info.define("CXX", "arm-oe-linux-gnueabi-g++")
  for v in path:
    self.buildenv_info.append_path("PATH", v)
```

instead of the previous approach where we used `env_info`.

The compiler executable names are relative paths so they rely on `PATH` being set correctly. Now when I use this SDK recipe as a `tool_requires` in a consumer, the CMake build fails because `arm-oe-linux-gnueabi-gcc` is not found. I cannot find the `PATH` anywhere in the generated toolchain file, whereas `CC` and `CXX` are transferred correctly to the corresponding CMake settings. However, when I add all `PATH` entries to `cpp_info.bindirs` instead, the CMake build works.

Now the question is if this is intended? Do I have to add an additional `VirtualBuildEnv` generator to the consumer to make it work correctly? I find it a bit illogical that `PATH` is not applied to CMake builds whereas everything else is picked up from `buildenv_info`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @jasal82 

Thanks for the question, and sorry about the confusion.

Yes, it's intended. The consumer has to use VirtualBuildEnv to use those specific PATH variables defined for building context. Perhaps these pieces of documentation help to make it clear:

* [Propagating environment or configuration information to consumers](https://docs.conan.io/2/tutorial/creating_packages/define_package_information.html?highlight=buildenv_info#propagating-environment-or-configuration-information-to-consumers)
* [VirtualBuildEnv](https://docs.conan.io/2/reference/tools/env/virtualbuildenv.html#virtualbuildenv)

**Comment by jasal82** [comment]
@franramirez688 I see. The reason I asked was that there are multiple third party recipes in Conan Center which seem to not follow this pattern. For example the `mosquitto` recipe fails because it _doesn't_ use `VirtualBuildEnv` in addition to its CMake generator. So I'd like to know if you have any ideas how to enforce correct usage in the Conan Center recipes, because otherwise we'd have to apply this `cpp_info.bindirs` workaround to make it work reliably across all of the third party recipes.

**Comment by jasal82** [comment]
@franramirez688 What would be your recommendation on how to forward compiler configuration from a SDK recipe to consumers? Should we use `conf_info` and `tools.build` or `buildenv_info` together with `VirtualBuildEnv`? I feel that there are too many options now which makes it hard to establish best practices.

**Comment by franramirez688** [comment]
Hi @jasal82 

Sorry for the delay. Yes, I completely understand your doubts, and perhaps we should explain it better in our documentation.
I think that the best practice here is to define, as you said, both conf_info, e.g., `tools.build:compiler_executables`, and/or `self.buildenv_info.define_path("YOUR_VAR", "THE_PATH")`. Sometimes you can find recipes that define something like this:

```python

        compiler_executables = {
            "c": "arm-oe-linux-gnueabi-gcc",
            "cpp": "arm-oe-linux-gnueabi-g++",
        }
        self.conf_info.update("tools.build:compiler_executables", compiler_executables)
        self.buildenv_info.define_path("CC", "arm-oe-linux-gnueabi-gcc")
        self.buildenv_info.define_path("CXX", "arm-oe-linux-gnueabi-g++")
```
Why? It ensures the availability of those env variables if you're using your custom generators or want them injected via environment at build context.

`cpp_info.bindirs` [documentation](https://docs.conan.io/2/reference/conanfile/methods/package_info.html#cpp-info-library-and-build-information) reads like this:

```
bindirs: List of relative paths (starting from the package root) of directories in 
         which to find library runtime binaries (like executable Windows .dlls). By default, it is 
         initialized to ['bin'], and it is rarely changed.
```
So, it's not thought to put compiler paths but files needed at runtime.

A couple of examples:
* [nasm](https://github.com/conan-io/conan-center-index/blob/26d8785880f677ddc0c036698b3b58cc51f9312d/recipes/nasm/all/conanfile.py#L114C19-L114C19)
* [android-ndk](https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/conanfile.py#L255) (much more complex)

Another good point is the possibility of using the virtual environments automatically, so you would not need to add those generators in all the recipes thanks to the configuration `tools.env.virtualenv:auto_use=True`. Conan 2.x uses that one by default, but Conan 1.x needs to be defined in your profiles or global.conf. More information is in the [Migration guide](https://docs.conan.io/1/migrating_to_2.0/recipes.html#the-environment-management).

UPDATED: A clarification about the `compiler_executables` conf. This one will depend on the generator used by the consumer.
For instance, having a look at the [CMakeToolchain conf documentation](https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#conf):

```
tools.build:compiler_executables dict-like Python object which specifies the compiler as key and the compiler executable path as value. Those keys will be mapped as follows:
    * c: will set CMAKE_C_COMPILER in conan_toolchain.cmake.
    * cpp: will set CMAKE_CXX_COMPILER in conan_toolchain.cmake.
    * RC: will set CMAKE_RC_COMPILER in conan_toolchain.cmake.
    * objc: will set CMAKE_OBJC_COMPILER in conan_toolchain.cmake.
    * objcpp: will set CMAKE_OBJCXX_COMPILER in conan_toolchain.cmake.
    * cuda: will set CMAKE_CUDA_COMPILER in conan_toolchain.cmake.
    * fortran: will set CMAKE_Fortran_COMPILER in conan_toolchain.cmake.
    * asm: will set CMAKE_ASM_COMPILER in conan_toolchain.cmake.
    * hip: will set CMAKE_HIP_COMPILER in conan_toolchain.cmake.
    * ispc: will set CMAKE_ISPC_COMPILER in conan_toolchain.cmake.
```
Now, looking at the [AutotoolsToolchain one](https://docs.conan.io/2/reference/tools/gnu/autotoolstoolchain.html#conf):

```
tools.build:compiler_executables dict-like Python object which specifies the compiler as key and the compiler executable path as value. Those keys will be mapped as follows:
    * c: will set CC in conanautotoolstoolchain.sh|bat script.
    * cpp: will set CXX in conanautotoolstoolchain.sh|bat script.
    * cuda: will set NVCC in conanautotoolstoolchain.sh|bat script.
    * fortran: will set FC in conanautotoolstoolchain.sh|bat script.
 ```

**Comment by jasal82** [comment]
@franramirez688 That matches with what I figured out eventually. But in your example, if the `arm-oe-linux-gnueabi-gcc` is not available on the system's default `PATH`, what is the intended procedure to make CMake configure correctly? Do I have to specify full paths for `compiler_executables`? Because other than an additional VirtualBuildEnv generator in the consumer I see no way of forwarding a custom PATH to the CMake generators. And it is not guaranteed that every downstream consumer uses VirtualBuildEnv and the CMake generators together.

**Comment by franramirez688** [comment]
Hi @jasal82 

Sorry for the delay and for missing this one. Actually, when you define those `buildenv_info` variables in the recipe upstream is because of one of these cases:

* (unlikely scenario) Your recipe upstream is a library but it needs to define some paths because of some useful scripts. Normally, this is not the case because all those scripts would be within the `bin` folder (`bindirs` folder), but it could happen I guess.
* (the most frequent scenario) Your recipe upstream is a tool requirement, and you're installing all the needed stuff on the consumer side and setting the correct env paths, e.g., the android-ndk, make, etc. recipes.

As you said, in my example, what would I expect from the library upstream? (consuming that recipe as a tool requirement)

* That recipe would have to package those compilers, scripts, etc., and put them in my build environment.
* Using Conan 2.x is activating automatically the VirtualBuildEnvironment, so I can use those `compiler_executables` assuming that they're already in my path.

For instance, the same case as the [`test_package/conanfile.py` from the android-ndk recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/test_package/conanfile.py). It's running the ndk-build  script directly.

**Comment by franramirez688** [comment]
Hi @jasal82 

Is it clearer now? Do you have any other doubts? If not, I think that we could close this issue.

**Comment by jasal82** [comment]
@franramirez688 My question was mostly related to the new toolchain integrations in Conan 1.x, because that's what we're going to be stuck with for quite a while during the migration phase of our 600+ recipes. But I have a workaround for that now so this issue can be closed. Thanks.
