### ISSUE TITLE
[question] Provide valid PDBs for a custom recipe

### ISSUE THREAD

**Issue by davidhov** [conan-io/conan#15115]
### What is your question?

Hi!

I have my own recipe file defined for the [NATS ](https://github.com/nats-io/nats.c)library.
I have included `<nats/nats.h>` in my project and building it in **Debug** mode. 
I am getting many warnings like: 
```
 Build started: Project: Service, Configuration: Debug x64 ------
61>Main.cpp
61>nats_staticd.lib(nats.obj) : warning LNK4099: PDB '' was not found with 'nats_staticd.lib(nats.obj)' or at ''; linking object as if no debug info
```

So, I assume that PDB info should be added for the recipe file.
If my assumption is correct, how can I do that?

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @davidhov 

Thanks for your question.

The scenario is different for ConanCenter packages and for your own:
- ConanCenter packages will not package the PDBs. They are very large, costly to upload, storage and transfer in downloads, for very little benefit.
- Your own private recipes and your own private packages can perfectly ``copy()`` the pdbs in the ``package()`` method to have them available at build time, if that is what you want. It is mostly that, either your ``cmake.install()`` (code in your ``CMakeLists.txt``) copies the pdbs, or you should do a ``copy(self, "*.pdb", ...)`` in your ``package()`` method.

**Comment by davidhov** [comment]
Thank you for the answer!

Best Regards,
David
