### ISSUE TITLE
[bug] Can't build libcurl on alpine - can't run m4

### ISSUE THREAD

**Issue by neucer** [conan-io/conan#15111]
### Environment details

* Operating System+version: [alpine:latest](https://hub.docker.com/layers/library/alpine/latest/images/sha256-48d9183eb12a05c99bcc0bf44a003607b8e941e1d4f41f9ad12bdcc4b5672f86?context=explore)
* Compiler+version: gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924
* Conan version: 2.0.14
* Python version: 3.11.6

### Steps to reproduce

1. `docker run  -it   alpine:latest`
2. inside container
```
apk add make python3 py3-pip gcc g++ cmake perl linux-headers
pip install conan
conan profile detect
conan install --requires libcurl/8.2.1 --build=missing
```

### Logs

```
...
-------- Installing package libcurl/8.2.1 (9 of 9) --------
libcurl/8.2.1: Building from source
libcurl/8.2.1: Package libcurl/8.2.1:53e1cba16a20c8ea26639d4ae58c80d69af7af5a
libcurl/8.2.1: Copying sources to build folder
libcurl/8.2.1: Building your package in /root/.conan2/p/b/libcue407d5a23e876/b
libcurl/8.2.1: Calling generate()
libcurl/8.2.1: Generators folder: /root/.conan2/p/b/libcue407d5a23e876/b/build-release/conan
libcurl/8.2.1: Generating aggregated env files
libcurl/8.2.1: Generated aggregated env files: ['conanbuild.sh']
libcurl/8.2.1: Calling build()
libcurl/8.2.1: apply_conandata_patches(): No patches defined in conandata
libcurl/8.2.1: RUN: autoreconf --force --install
autom4te: error: need GNU m4 1.4 or later: /root/.conan2/p/m42bbd3e3ebdb44/p/bin/m4
aclocal: error: /root/.conan2/p/autocf3e6879dde7f6/p/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1

libcurl/8.2.1: ERROR: 
Package '53e1cba16a20c8ea26639d4ae58c80d69af7af5a' build failed
libcurl/8.2.1: WARN: Build folder /root/.conan2/p/b/libcue407d5a23e876/b/build-release
*********************************************************
Recipe 'libcurl/8.2.1' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: libcurl/8.2.1: Error in build() method, line 249
  autotools.autoreconf()
  ConanException: Error 1 while executing
```

ldd m4
```
/ # ldd /root/.conan2/p/m42bbd3e3ebdb44/p/bin/m4
  /lib64/ld-linux-x86-64.so.2 (0x7f1e3a80b000)
  libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f1e3a80b000)
Error relocating /root/.conan2/p/m42bbd3e3ebdb44/p/bin/m4: error_at_line: symbol not found
Error relocating /root/.conan2/p/m42bbd3e3ebdb44/p/bin/m4: __strdup: symbol not found
Error relocating /root/.conan2/p/m42bbd3e3ebdb44/p/bin/m4: rawmemchr: symbol not found
Error relocating /root/.conan2/p/m42bbd3e3ebdb44/p/bin/m4: error: symbol not found
```

**Comment by neucer** [comment]
I tried the newest version (`libcurl/8.4.0`) as well, same error

**Comment by memsharded** [comment]
Hi @neucer 

Thanks for your report.
I think this wouldnt be a Conan issue, but a package issue from the package in ConanCenter.
The issue you could be seeing is a binary incompatibility. ConanCenter creates packages with Ubuntu, in a relatively old glibc, to be as compatible as possible with most Linux distros, but this might not be always possible.

I'd suggest to try to force the build of m4 locally with ``--build=m4*``, and see how it goes.
Then, it is possible that for non "standard" binaries, for using ConanCenter packages in production to follow the guidelines in: https://docs.conan.io/2/devops/using_conancenter.html

**Comment by neucer** [comment]
`--build "m4*"` worked

**Comment by memsharded** [comment]
> --build "m4*" worked

Thanks for the feedback.
Please consider then the advice above ``Then, it is possible that for non "standard" binaries, for using ConanCenter packages in production to follow the guidelines in: https://docs.conan.io/2/devops/using_conancenter.html``, if you intend to use it in production.
