### ISSUE TITLE
[feature] support OpenHarmony System

### ISSUE THREAD

**Issue by fengozl** [conan-io/conan#15113]
### What is your suggestion?

Hello, 
    OpenHarmony is an open source project incubated and operated by the OpenAtom Foundation, with the goal of building an intelligent terminal device operating system framework and platform for the all-scene, all-connected and all-intelligent era, and promoting the prosperity and development of the Internet of everything industry.Open source repository address: https://openharmony.gitee.com/
    We used conan to compile the open source library, but found that conan does not support OpenHarmony .Hope to support this system.
Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @memsharded 

Nice to hear from your project. Thanks for your suggestion.
We would need more detail and guidance here:
> We used conan to compile the open source library, but found that conan does not support OpenHarmony .Hope to support this system.

What does it means? Does it means to have new ``settings`` in the default ``settings.yml``? Which ones? Does it mean to have some recipes in the ConanCenter repo?
It is possible that not everything could be built-in for OpenHarmony, but still some extensions in the ``conan-extensions`` could be possible.
Thanks for your feedback!

**Comment by memsharded** [comment]
Closing this ticket as staled, but please re-open or create a new one if still interested, thanks!
