### ISSUE TITLE
[question] Is it possible to map prebuilt binaries from conanv1 to conanv2?

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#15110]
### What is your question?

Hi,

In conanv1 I've been using these options to embed all the dependencies into hash
general.default_package_id_mode=full_package_mode
general.revisions_enabled=1

For conanv2 I've tried enabling
core.package_id:default_embed_mode=full_mode
core.package_id:default_non_embed_mode=full_mode
core.package_id:default_unknown_mode=full_mode

I suspect that it can't map existing binaries for recipes that are built from sources because of different set of settings for compiler even if they are basically the same toolset.

```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
*:build_type=Debug
```

```
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.update=9
compiler.version=192
os=Windows
```

What I don't understand - why can't it map binaries for prebuilt binaries that depend only on "os"? There are no requirements/build_requirements in recipe.

```
ERROR: Missing binary: package/1.0.0@user/channel:ebec3dc6d7f6b907b3ada0c3d3cdc83613a2b715


package/1.0.0@user/channel: WARN: Can't find a 'package/1.0.0@user/channel' package binary 'ebec3dc6d7f6b907b3ada0c3d3cdc83613a2b715' for the configuration:
[settings]
os=Windows


ERROR: Missing prebuilt package for 'package/1.0.0@user/channel'
```

In that recipe I have only "os" in settings.

```
settings = "os"
build_policy = "never"
```
![image](https://github.com/conan-io/conan/assets/4276548/eb5ada8f-e24c-45cf-90cb-5d260f62b4ab)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Nekto89 

The computation of ``package_id`` is different in 1.X and 2.0, even for exactly the same settings.
This is due on purpose, to guarantee strict separation of binaries, and also to be able to redesign how the ``package_id`` is computed in Conan 2.0. (in Conan 2.0 it is computed as the ``conaninfo.txt`` file checksum, directly, while in Conan 1.X it is a more elaborate internal checksum, cannot be validated against a file, and cannot be easily explained).

The idea is that binaries in 1.X and 2.0 can coexist in the same server repository, but with strict separation. Conan 1.X ``conan search ...`` will only list binaries created with Conan 1.X and Conan 2.0 ``conan list ...`` will only list binaries created with Conan 2.0.

Furthermore the only way that a recipe in Conan 2.0 is able to work fine and create a package is actually creating a package. So the recommended way to move forward in the Conan 2.0 migration is having the Conan 2.0 CI pipeline to build the package binaries with the Conan 2.0 client and upload them.

**Comment by Nekto89** [comment]
> Hi @Nekto89
> 
> The computation of `package_id` is different in 1.X and 2.0, even for exactly the same settings. This is due on purpose, to guarantee strict separation of binaries, and also to be able to redesign how the `package_id` is computed in Conan 2.0. (in Conan 2.0 it is computed as the `conaninfo.txt` file checksum, directly, while in Conan 1.X it is a more elaborate internal checksum, cannot be validated against a file, and cannot be easily explained).
> 
> The idea is that binaries in 1.X and 2.0 can coexist in the same server repository, but with strict separation. Conan 1.X `conan search ...` will only list binaries created with Conan 1.X and Conan 2.0 `conan list ...` will only list binaries created with Conan 2.0.
> 
> Furthermore the only way that a recipe in Conan 2.0 is able to work fine and create a package is actually creating a package. So the recommended way to move forward in the Conan 2.0 migration is having the Conan 2.0 CI pipeline to build the package binaries with the Conan 2.0 client and upload them.

Thank you @memsharded for your helpful response. I was hoping to skip at least preparation of repacked binaries but now it's clear that it's not possible.
