### ISSUE TITLE
[bug] DB migration failed on empty cache when upgrading 2.0.14

### ISSUE THREAD

**Issue by edwardvandevorst-philips** [conan-io/conan#15112]
### Environment details

* Operating System+version: [alpine 13](python:3-alpine docker container)
* Compiler+version: n.a.
* Conan version: 2.0.14
* Python version: 3.11

When upgrading with an empty cache to conan 2.0.14 (from 2.0.11), we get the following error:

```
WARN: Upgrade cache from Conan version '2.0.2'
WARN: Running 2.0.14 Cache DB migration to add LRU column
ERROR: Could not complete the 2.0.14 DB migration. Please manually remove your .conan2 cache and reinstall packages
ERROR: duplicate column name: lru
```
 when running the command `conan lock create -u  --version ....`

The cache is empty and the only thing that has run before is `conan config install -t dir <path>` which contains a version.txt with 2.0.2. 

This all worked fine with 2.0.11. 

### Steps to reproduce

1. Make sure you have an empty system
2. conan config install -t dir <path to config> (config contains version.txt with 2.0.2)
3. conan lock create -u --version ....etc

(I hope this is enough information)

### Logs

WARN: Upgrade cache from Conan version '2.0.2'
WARN: Running 2.0.14 Cache DB migration to add LRU column
ERROR: Could not complete the 2.0.14 DB migration. Please manually remove your .conan2 cache and reinstall packages
ERROR: duplicate column name: lru

**Comment by memsharded** [comment]
Hi @edwardvandevorst-philips 

I think that you could be observing the same as https://github.com/conan-io/conan/issues/15104

The cause is using ``the ``storage_path`` and not having the Conan home and the Conan package storage. Could you please check if this could be the issue?

**Comment by edwardvandevorst-philips** [comment]
@memsharded Thanks for your quick response. 

I still not fully understand what I should check and how to resolve. Our conan global config is:

```
core:required_conan_version=>=2.0
core.upload:retry=5
core.upload:retry_wait=5
core.download:parallel=5
core.download:retry=5
core.download:retry_wait=5
core.net.http:timeout=600
tools.files.download:retry=5
tools.files.download:retry_wait=5
```
so no storage_path which was recently introduced. 

Our `CONAN_HOME` on the build server is set  on `/tmp/.conan2`. 

We first install the conan configuration.

**Comment by memsharded** [comment]
Thanks for the feedback, then that is something different

I have now realized about this:

> conan config install -t dir (config contains version.txt with 2.0.2)

This is the issue. The ``version.txt`` is not a file that can be installed with ``conan config install``. It is an internal implementation file that Conan uses to track the current version and compare. If it is artificially changed by other file, then the migrations will be messed up. Could you please remove that file from your ``conan config install`` and try again?

(If you want the client to enforce a Conan version, that can be done with another ``conf``, but changing the ``version.txt`` not possible)

**Comment by edwardvandevorst-philips** [comment]
Ah, this seems to solve the issue. 
I assumed `version.txt` was needed for conan in other to automatically upgrade the other configuration settings like the extensions.

**Comment by memsharded** [comment]
> I assumed version.txt was needed for conan in other to automatically upgrade the other configuration settings like the extensions.

Not really. It is a "declaration" of the version last used to use that cache. This is why forcing its change from the outside produces confusion to the migrations.

I think the issue is solved now and this ticket could be closed? Thanks!

**Comment by edwardvandevorst-philips** [comment]
Yes, can be closed. Thanks.
