### ISSUE TITLE
[question][api] Access to `possible_values` settings after version 2.0.14

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#15125]
### What is your question?

We have a custom command for setting up profiles. Up to version 2.0.13 I had the following code to access to possible value for settings (settings.yml and settings_user.yml):
```python
conan_cache = ClientCache(conan_api.cache_folder)
... = conan_cache.settings.possible_values()
```

I think it broke with PR #14969.

Do you have any hint what's the new way to access this value? I had a look for the code that was in `cache.py` previously and it seems to have moved into `profiles.py` but the whole `_settings()` function there seems to be private.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fschoenm 

It is true that we moved and hided the ``settings`` access which was in a bad place (the ``ClientCache`` object probably won't be part of the public API at all).

At the moment it was hidden with the refactor, but I think it is legit that this would be a public API as well, let me discuss with the team what would be the right location for it.

**Comment by samuel-emrys** [comment]
Adding support for the idea that the cache has a helper on the public API (from which settings can be queried) - we use this a lot.

Also, doesn't removal of something from the public API constitute a breaking change? What's the Conan policy for managing/indicating these changes? I assume it won't be to bump the major version as semver suggests

**Comment by memsharded** [comment]
> Adding support for the idea that the cache has a helper on the public API (from which settings can be queried) - we use this a lot.

Sure, in that refactor we actually made the ``global.conf`` access public. The settings will also lie in the same category

> Also, doesn't removal of something from the public API constitute a breaking change? What's the Conan policy for managing/indicating these changes? I assume it won't be to bump the major version as semver suggests

The Python API is explicitly marked as experimental: https://docs.conan.io/2/reference/extensions/python_api.html, and even many of the subAPIs like https://docs.conan.io/2/reference/extensions/python_api/SearchAPI.html are not documented at all yet. We are waiting a bit to make it public, as Conan 2.0 matures and stabilizes a lot of changes have been necessary to APIs, making them stable and publicly documented too early will result in a legacy and outdated interface too early.

**Comment by AbrilRBS** [comment]
We're going to add a property to `conan_api.config` to allow acces to the contents f settings.yml, as well as adding a `conan config` subcommand to be able to also see its contents :)
