### ISSUE TITLE
[bug] follow tutorial “Consuming packages-Using build tools as Conan packages”

### ISSUE THREAD

**Issue by Mickeymua** [conan-io/conan#15123]
### Environment details

* Operating System+version:
NAME="openEuler"
VERSION="22.03 (LTS-SP2)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP2)"
ANSI_COLOR="0;31"
* Compiler+version:gcc version 10.3.1 (GCC)
* Conan version:2.0.14
* Python version:3.99

### Steps to reproduce

$ git clone https://github.com/conan-io/examples2.git
$ cd examples2/tutorial/consuming_packages/tool_requires
**[root@6c62377a3a12 with_center]# tree ./**
./
|-- CMakeLists.txt
|-- conanfile.txt
`-- src
    `-- main.cpp

1 directory, 3 files
**[root@6c62377a3a12 with_center]# cat conanfile.txt** 
[requires]
zlib/1.2.11

[tool_requires]
cmake/3.26.5

[generators]
CMakeDeps
CMakeToolchain
**[root@6c62377a3a12 with_center]# cat CMakeLists.txt** 
cmake_minimum_required(VERSION 3.10)
project(compressor C)

#set(CMAKE_CXX_STANDARD 20)
#set(CMAKE_CXX_STANDARD_REQUIRED True)

find_package(ZLIB REQUIRED)
message("Building with CMake version: ${CMAKE_VERSION}")
add_executable(${PROJECT_NAME} src/main.cpp)
target_link_libraries(${PROJECT_NAME} ZLIB::ZLIB)
**[root@6c62377a3a12 with_center]# conan install . --output-folder=build --build=missing**

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux

======== Computing dependency graph ========
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Checking remote: conancenter
zlib/1.2.11: Downloaded recipe revision dc0e384f0551386cd76dc29cc964c95e
cmake/3.26.5: Not found in local cache, looking in remotes...
cmake/3.26.5: Checking remote: conancenter
cmake/3.26.5: Downloaded recipe revision 45be851b07751d756215ef91456fcc09
Graph root
    conanfile.txt: /opt/with_center/conanfile.txt
Requirements
    zlib/1.2.11#dc0e384f0551386cd76dc29cc964c95e - Downloaded (conancenter)
Build requirements
    cmake/3.26.5#45be851b07751d756215ef91456fcc09 - Downloaded (conancenter)

======== Computing necessary packages ========
Requirements
    zlib/1.2.11#dc0e384f0551386cd76dc29cc964c95e:3f0cbc1394cb3fd9f3473d67001da1a496fb5b26 - Build
Build requirements
    cmake/3.26.5#45be851b07751d756215ef91456fcc09:63fead0844576fc02943e16909f08fcdddd6f44b#828536b3905230f8b7a9d20f9d7ee659 - Download (conancenter)

======== Installing packages ========

-------- Downloading 1 package --------
cmake/3.26.5: Retrieving package 63fead0844576fc02943e16909f08fcdddd6f44b from remote 'conancenter' 
cmake/3.26.5: Downloading 39.5MB conan_package.tgz
cmake/3.26.5: Downloaded 7.0MB 17% conan_package.tgz
cmake/3.26.5: Downloaded 14.0MB 35% conan_package.tgz
cmake/3.26.5: Downloaded 21.1MB 53% conan_package.tgz
cmake/3.26.5: Downloaded 28.2MB 71% conan_package.tgz
cmake/3.26.5: Downloaded 35.2MB 89% conan_package.tgz
cmake/3.26.5: Decompressing 39.5MB conan_package.tgz
cmake/3.26.5: Package installed 63fead0844576fc02943e16909f08fcdddd6f44b
cmake/3.26.5: Downloaded package revision 828536b3905230f8b7a9d20f9d7ee659
cmake/3.26.5: Appending PATH environment variable: /root/.conan2/p/cmake0733f7ea8fe05/p/bin
zlib/1.2.11: Sources downloaded from 'conancenter'
zlib/1.2.11: Calling source() in /root/.conan2/p/zlib2cad50ee1214e/s/src

-------- Installing package zlib/1.2.11 (2 of 2) --------
zlib/1.2.11: Building from source
zlib/1.2.11: Package zlib/1.2.11:3f0cbc1394cb3fd9f3473d67001da1a496fb5b26
zlib/1.2.11: Copying sources to build folder
zlib/1.2.11: Building your package in /root/.conan2/p/b/zlibfbd4aa6efb036/b
zlib/1.2.11: Calling generate()
zlib/1.2.11: Generators folder: /root/.conan2/p/b/zlibfbd4aa6efb036/b/build/Release/generators
zlib/1.2.11: CMakeToolchain generated: conan_toolchain.cmake
zlib/1.2.11: CMakeToolchain generated: CMakePresets.json
zlib/1.2.11: CMakeToolchain generated: ../../../src/CMakeUserPresets.json
zlib/1.2.11: Generating aggregated env files
zlib/1.2.11: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
zlib/1.2.11: Calling build()
zlib/1.2.11: Apply patch (conan): separate static/shared builds, disable debug suffix, disable building examples
zlib/1.2.11: Apply patch (portability): fix condition for WIDECHAR usage
zlib/1.2.11: Running CMake.configure()
zlib/1.2.11: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan2/p/b/zlibfbd4aa6efb036/b/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan2/p/b/zlibfbd4aa6efb036/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan2/p/b/zlibfbd4aa6efb036/b/src"
_**/bin/sh: line 1: cmake: command not found**_

zlib/1.2.11: ERROR: 
Package '3f0cbc1394cb3fd9f3473d67001da1a496fb5b26' build failed
zlib/1.2.11: WARN: Build folder /root/.conan2/p/b/zlibfbd4aa6efb036/b/build/Release
*********************************************************
Recipe 'zlib/1.2.11' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: zlib/1.2.11: Error in build() method, line 84
        cmake.configure()
        ConanException: Error 127 while executing

**Comment by memsharded** [comment]
Hi @Mickeymua 

Did you manage to solve the issue? 
I think the issue is that the ``tool_requires`` in the conanfile only applies to yourself. If you want cmake to be a tool_require for dependencies, you need to put it in the profile?
