### ISSUE TITLE
export pre-binary so file, can not skip so's rpath 

### ISSUE THREAD

**Issue by siweilvxing** [conan-io/conan#15124]
### What is your question?

I have a third party library build output so file, so I use conan export-pkg export this library.
but when my cmake projects link this so, my binary RPATH have /root/.conan2/p/b/xxx.
in cmakelists.txt I set(CMAKE_SKIP_RPATH TRUE), but it doesn't work. 
use readily -d xxx, so's file still has path.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
This might not be a Conan question, but a CMake question.

Conan ``CMakeToolchain`` already does
```cmake
set(CMAKE_SKIP_RPATH 1 CACHE BOOL "rpaths" FORCE)
```
You would need to detail:
- Your full ``conanfile.py``, ``CMakeLists.txt`` and source code to be able to reproduce
- The full commands that you are using
- Your Conan version, OS, compiler, etc.

**Comment by siweilvxing** [comment]
> This might not be a Conan question, but a CMake question.
> 
> Conan `CMakeToolchain` already does
> 
> ```cmake
> set(CMAKE_SKIP_RPATH 1 CACHE BOOL "rpaths" FORCE)
> ```
> 
> You would need to detail:
> 
> * Your full `conanfile.py`, `CMakeLists.txt` and source code to be able to reproduce
> * The full commands that you are using
> * Your Conan version, OS, compiler, etc.

conan version is : conan2, 2.0.14
os: linux
compiler: g++ 10
here is conanfile.py
```
import os
from conan import ConanFile
from conan.tools.files import copy


class frameworkRecipe(ConanFile):
    name = "framework"
    version = "3.6.2"
    settings = "os", "arch"
    options = { "shared": [True, False], "fPIC": [True, False]}
    default_options = { "shared": True, "fPIC": True }

    def layout(self):
        self.cpp.source.includedirs = ["include"]
        self.cpp.build.libdirs = ["lib"]

    def package(self):
        local_include_folder = os.path.join(self.source_folder, self.cpp.source.includedirs[0])
        local_lib_folder = os.path.join(self.build_folder, self.cpp.build.libdirs[0])
        copy(self, "*.h", local_include_folder, os.path.join(self.package_folder, "include"), keep_path=False)
        copy(self, "*", local_lib_folder, os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, "*", os.path.join("config-mail"), os.path.join(self.package_folder, "config-mail"), keep_path=False)
        copy(self, "*", os.path.join("config-net"), os.path.join(self.package_folder, "config-net"), keep_path=False)
        copy(self, "*", os.path.join("config-storage"), os.path.join(self.package_folder, "config-storage"), keep_path=False)
        copy(self, "*", os.path.join("config-tdlp"), os.path.join(self.package_folder, "config-tdlp"), keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["Framework"]
        self.cpp_info.libdirs=["lib"]
        self.cpp_info.includedirs=["include"]
        self.cpp_info.set_property("cmake_target_name", "framework::framework")
```
CMakeListst.txt just 
```
set(CMAKE_SKIP_RPATH TRUE)
```
use find_package etc

commands:
```
conan export-pkg . -s build_type=Release
conan install . --build=missing
cmake --preset conan-release
cmake --build build/Release -j8
```

after compile，
```
readelf -d xxxx
``` 

```
Dynamic section at offset 0x52d7a0 contains 33 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libboundscheck.so]
 0x0000000000000001 (NEEDED)             Shared library: [/root/.conan2/p/b/libbo618a34813d7aa/p/lib/libboundscheck.so]
 0x0000000000000001 (NEEDED)             Shared library: [libndpi.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [/root/.conan2/p/framed21bd5bddd3b9/p/lib/libFramework.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libNdlpClient.so]
 0x000000000000000c (INIT)               0xf5000
 0x000000000000000d (FINI)               0x42afbc
 0x0000000000000019 (INIT_ARRAY)         0x503c80
 0x000000000000001b (INIT_ARRAYSZ)       624 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x503ef0
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x338
 0x0000000000000005 (STRTAB)             0x3dac8
 0x0000000000000006 (SYMTAB)             0xdc78
 0x000000000000000a (STRSZ)              478479 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x530000
 0x0000000000000002 (PLTRELSZ)           85560 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xe0090
 0x0000000000000007 (RELA)               0xb6a68
 0x0000000000000008 (RELASZ)             169512 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0xb67b8
 0x000000006fffffff (VERNEEDNUM)         5
 0x000000006ffffff0 (VERSYM)             0xb27d8
 0x000000006ffffff9 (RELACOUNT)          2800
 0x0000000000000000 (NULL)               0x0
```
libboundscheck.so and libFramework.so still has path

I use include_directories add link_directories in CMake, no path

**Comment by memsharded** [comment]
If you are building something, a binary, it is impossible that your CMakeLists.txt is just ``set(CMAKE_SKIP_RPATH TRUE)``, there should be something else there in the CMakeLists.txt to be able to build something.

Then, there is something missing in the commands:
```
conan export-pkg . -s build_type=Release
conan install . --build=missing
```
I'd say that the package ``framework`` created with ``export-pkg`` is different from the consumer one that install the dependencies, the one that would have a ``requires="framework/3.6.2"``, so I am missing at least some ``cd`` to another folder?

Could you please clarify these points? Many thanks!

**Comment by siweilvxing** [comment]
> If you are building something, a binary, it is impossible that your CMakeLists.txt is just `set(CMAKE_SKIP_RPATH TRUE)`, there should be something else there in the CMakeLists.txt to be able to build something.
> 
> Then, there is something missing in the commands:
> 
> ```
> conan export-pkg . -s build_type=Release
> conan install . --build=missing
> ```
> 
> I'd say that the package `framework` created with `export-pkg` is different from the consumer one that install the dependencies, the one that would have a `requires="framework/3.6.2"`, so I am missing at least some `cd` to another folder?
> 
> Could you please clarify these points? Many thanks!

there are two projects. framework project and my project.
framework project is binary project build by other people， no source code. 
so I write conanfile.py above, call conan export-pkg command in framework folder
```
cd framework
conan export-pkg . -s build_type=Release
```
framework folder struct like this:
```
conanfile.py
config-mail/
config-net/
config-storage/
config-tdlp/
include/
lib/
```

 framework use in my project, conanfile.txt like this
```
[requires]
zookeeper-client-c/3.9.0
protobuf/3.21.12
lz4/1.9.4
cpptoml/0.1.1
libboundscheck/1.1.11
librdkafka/2.2.0
framework/3.6.2

[generators]
CMakeDeps
CMakeToolchain

[layout]
cmake_layout
```
in my project folder, execute command:
```
cd myproject
conan install . --build=missing
cmake --preset conan-release
cmake --build build/Release -j8
```
```
set(CMAKE_SKIP_RPATH TRUE)
```
in myproject CMakeLists.txt file

and link framework in CMakeLists.txt like this:
```
find_package(framework REQUIRED)

add_library(${PROJECT_NAME} SHARED ${SRC_FILES})
target_link_libraries(${PROJECT_NAME} 
  common rcu  policy_match serde boundscheck
  framework::framework
)

target_include_directories(${PROJECT_NAME} PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
```

**Comment by memsharded** [comment]
But quick question: Is the ``set(CMAKE_SKIP_RPATH TRUE)`` in your consumer ``CMakeLists.txt`` where you have the ``target_link_libraries(${PROJECT_NAME} .. framework::framework)``? This would be one of the bits that I am missing, having something that we can reproduce, because the full ``CMakeLists.txt`` of the consumer is what is necessary, including the CMake version used, etc.

As a side note, it is kind of easy to reproduce things with something like:
```bash
$ mkdir dep && cd dep
$ conan new cmake_lib -d name=dep -d version=0.1
$ conan create .
$ cd ..
$ mkdir app && cd app
$ conan new cmake_exe -d name=app -d version=0.1 -d requires=dep/0.1
$ conan build .
```
Then inspect the exe that was created inside ``app`` folder.

**Comment by siweilvxing** [comment]
> But quick question: Is the `set(CMAKE_SKIP_RPATH TRUE)` in your consumer `CMakeLists.txt` where you have the `target_link_libraries(${PROJECT_NAME} .. framework::framework)`? This would be one of the bits that I am missing, having something that we can reproduce, because the full `CMakeLists.txt` of the consumer is what is necessary, including the CMake version used, etc.
> 
> As a side note, it is kind of easy to reproduce things with something like:
> 
> ```shell
> $ mkdir dep && cd dep
> $ conan new cmake_lib -d name=dep -d version=0.1
> $ conan create .
> $ cd ..
> $ mkdir app && cd app
> $ conan new cmake_exe -d name=app -d version=0.1 -d requires=dep/0.1
> $ conan build .
> ```
> 
> Then inspect the exe that was created inside `app` folder.



cmake version is 3.26.5

myproject has a root CMakeLists.txt, it `set(CMAKE_SKIP_RPATH TRUE)`
target_link_libraries(${PROJECT_NAME} .. framework::framework) in subfolder like mylib
but in root CMakeLists.txt call
```
add_subdirectory(mylib)
```
 root CMakeLists.txt like this
```
cmake_minimum_required(VERSION 3.15)
project(stardew)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_SKIP_RPATH TRUE)

add_compile_options(
  -msse4.2
)

find_package(log4cplus REQUIRED)
find_package(Boost REQUIRED)

add_subdirectory(mylib)
```

so answer your question: cmake should `set(CMAKE_SIKP_RPATH TRUE)`  in mylib as I known

**Comment by memsharded** [comment]
Uhm, yeah this would be a bit unexpected. Unless there is something else in the ``mylib`` subdirectory ``CMakeLists.txt`` that would invalidate the ``set(CMAKE_SKIP_RPATH TRUE)``, but I guess that you have already checked that.

This is what Conan CMakeToolchain does: ``set(CMAKE_SKIP_RPATH 1 CACHE BOOL "rpaths" FORCE)``, and it seems to work.

Maybe at this point, the best would be to try to set up a complete minimal reproducible example that we can build and check. I'd try with the ``conan new`` hints I posted above, or if you could put a github repo or a zip with something that we could reproduce, that would be extremely helpful.

**Comment by siweilvxing** [comment]
> Uhm, yeah this would be a bit unexpected. Unless there is something else in the `mylib` subdirectory `CMakeLists.txt` that would invalidate the `set(CMAKE_SKIP_RPATH TRUE)`, but I guess that you have already checked that.
> 
> This is what Conan CMakeToolchain does: `set(CMAKE_SKIP_RPATH 1 CACHE BOOL "rpaths" FORCE)`, and it seems to work.
> 
> Maybe at this point, the best would be to try to set up a complete minimal reproducible example that we can build and check. I'd try with the `conan new` hints I posted above, or if you could put a github repo or a zip with something that we could reproduce, that would be extremely helpful.

ok。please see attach file.

I write a simple project.

myproject is main project, build execute binary, has a linkmylib so, link mylib project. it like this

myproject -> linkmylib.so -> mylib.so

mylib conan is conan project , export-pkg 
```
conan export . -s build_type=Release
```

after that:
```
conan install . --build=missing
cmake --preset conan-release
cmake --build build/Release -j8
```
readelf -d linkmylib.so, it all ok.

so I put into libboundscheck project, is a conan project
```
conan create .
```
and  then add
```
find_package(libboundscheck REQUIRED)
target_link_libraries(linkmylib mylib::mylib libboundscheck::libboundscheck)
```
after that ,rebuild

```
readelf -d build/Release/linkmylib/liblinkmylib.so 

Dynamic section at offset 0x2dc0 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libmylib.so]
 0x0000000000000001 (NEEDED)             Shared library: [/root/.conan2/p/libbo0c1afdd1626fa/p/lib/libboundscheck.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [liblinkmylib.so]
 0x000000000000000c (INIT)               0x1000
 0x000000000000000d (FINI)               0x1118
 0x0000000000000019 (INIT_ARRAY)         0x3db0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x3db8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x300
 0x0000000000000005 (STRTAB)             0x3d0
 0x0000000000000006 (SYMTAB)             0x328
 0x000000000000000a (STRSZ)              269 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x4000
 0x0000000000000002 (PLTRELSZ)           24 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x5b8
 0x0000000000000007 (RELA)               0x510
 0x0000000000000008 (RELASZ)             168 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x4f0
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x4de
 0x000000006ffffff9 (RELACOUNT)          3
 0x0000000000000000 (NULL)               0x0
```

libboundscheck.so has rpath , libmylib.so is ok. very strange
[myconan.tar.gz](https://github.com/conan-io/conan/files/13428444/myconan.tar.gz)

**Comment by memsharded** [comment]
I am trying to reproduce. 
This is what I got:
```
Dynamic section at offset 0x2e40 contains 22 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libmylib.so]
 0x000000000000000e (SONAME)             Library soname: [liblinkmylib.so]
 0x000000000000000c (INIT)               0x1000
 0x000000000000000d (FINI)               0x112c
 0x0000000000000019 (INIT_ARRAY)         0x3e30
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x3e38
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x2f0
 0x0000000000000005 (STRTAB)             0x3c0
 0x0000000000000006 (SYMTAB)             0x318
```

I am using the conan ``conanio/gcc11`` docker image, using CMake 3.27 from the Conan package.
Maybe I was missing something in between? The instructions were a bit unclear, like ``conan export . -s build_type=Release`` is incorrect, I guess it is a typo and ``export-pkg`` instead, and the order, to create ``conan create .`` the ``libboundscheck`` package later, I had to create it the first thing, otherwise the ``conan install`` fails for the consumer project because it declares a dependency to it.

Maybe you could add a small shell or python scripts that reproduces the problem from scratch (make sure to remove things from the cache)? Just in case I am missing something.

**Comment by siweilvxing** [comment]
> I am trying to reproduce. This is what I got:
> 
> ```
> Dynamic section at offset 0x2e40 contains 22 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libmylib.so]
>  0x000000000000000e (SONAME)             Library soname: [liblinkmylib.so]
>  0x000000000000000c (INIT)               0x1000
>  0x000000000000000d (FINI)               0x112c
>  0x0000000000000019 (INIT_ARRAY)         0x3e30
>  0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
>  0x000000000000001a (FINI_ARRAY)         0x3e38
>  0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
>  0x000000006ffffef5 (GNU_HASH)           0x2f0
>  0x0000000000000005 (STRTAB)             0x3c0
>  0x0000000000000006 (SYMTAB)             0x318
> ```
> 
> I am using the conan `conanio/gcc11` docker image, using CMake 3.27 from the Conan package. Maybe I was missing something in between? The instructions were a bit unclear, like `conan export . -s build_type=Release` is incorrect, I guess it is a typo and `export-pkg` instead, and the order, to create `conan create .` the `libboundscheck` package later, I had to create it the first thing, otherwise the `conan install` fails for the consumer project because it declares a dependency to it.
> 
> Maybe you could add a small shell or python scripts that reproduces the problem from scratch (make sure to remove things from the cache)? Just in case I am missing something.

it’s `conan export-pkg . -s build_type=Release`, my mistake.
attach file has `build.sh`, run it 
`clean.sh` clean temp build files

[myconan.tar.gz](https://github.com/conan-io/conan/files/13432879/myconan.tar.gz)

this version add call libboundscheck func `memset_s` in `linkmylib.cpp`.

in previous version , do not call `memset_s`， so some linux platform will link  libboundscheck , some not

**Comment by memsharded** [comment]
I am having a look, initial feedback:

- The libboundscheck lib seems pure C, not C++, so this would be missing:
```python
 def configure(self):
        del self.settings.compiler.cppstd
        del self.settings.compiler.libcxx
```

It seems there is something intrinsic in the ``libboundscheck`` library that makes RPATHs not being removed. Other libraries work fine, if I replace it with a fake shared library built with CMake the RPATHs are removed from the consumer myproject without issues.

Update: The link command is identical when using a fake replacement of libboundscheck than when using the real one.

**Comment by memsharded** [comment]
I have repeated the test with a new fake ``libboundscheck`` replacement, this time based on an autotools project created with ``conan new autotools_lib``, and it also works fine:

```
0x0000000000000001 (NEEDED)             Shared library: [liblibboundscheck.so.0]
```

There is something intrinsic to that Makefile that makes it not work, I am trying to strip it down but still no success

**Comment by memsharded** [comment]
I think I got it.

The shared library built with makefiles ``libboundscheck`` is missing ``soname``. Without it, the RPATHs seems that cannot be skipped, and they will be kept absolute.
Doing in the libbonudscheck Makefile something like:
```makefile
$(PROJECT): $(OBJECTS)
	mkdir -p lib
	$(CC)  -shared -o lib/$@ $(patsubst %.o,obj/%.o,$(notdir $(OBJECTS))) -Wl,-soname,$@ $(LD_FLAG)
	@echo "finish $(PROJECT)"
```
seems to fix it

**Comment by siweilvxing** [comment]
> I think I got it.
> 
> The shared library built with makefiles `libboundscheck` is missing `soname`. Without it, the RPATHs seems that cannot be skipped, and they will be kept absolute. Doing in the libbonudscheck Makefile something like:
> 
> ```makefile
> $(PROJECT): $(OBJECTS)
> 	mkdir -p lib
> 	$(CC)  -shared -o lib/$@ $(patsubst %.o,obj/%.o,$(notdir $(OBJECTS))) -Wl,-soname,$@ $(LD_FLAG)
> 	@echo "finish $(PROJECT)"
> ```
> 
> seems to fix it

many thanks! it works.

but I'm a little confused. I use include_directories, link_directories way to link libboundscheck, it has not this problem.

attach file use that way
attach file has `build.sh`, run it
`clean.sh` clean temp build files

[myconan2.tar.gz](https://github.com/conan-io/conan/files/13445499/myconan2.tar.gz)

**Comment by memsharded** [comment]
Yes, this is because it is doing a different linking: ``-L/home/conan/conanws/kk/test/myconan2/myproject/../libboundscheck/lib  -L/home/conan/.conan2/p/b/mylibfea480b74836c/p/lib  -lboundscheck``

The way CMake works with imported targets, external to your  project is different than with local targets in your project. For imported targets, it requires soname, or it will embed the full RPATH, while for local targets doesn't.
