### ISSUE TITLE
[question] CMakeDeps generate dep files in a subdirectory

### ISSUE THREAD

**Issue by sakra** [conan-io/conan#15133]
### What is your question?

Is it possible to make the `CMakeDeps` generator place all generated files (e.g. `XXX-config.cmake`) in a sub directory of the CMake root build directory (e.g., a `conan` directory)? Currently files generated by the project in the build directory are lost in a sea of conan dependency files.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sakra 

Thanks for your question.
Sure, this is what the ``layout`` is for: https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html#use-the-layout-method

You have it both in ``conanfile.txt`` and ``conanfile.py``. A built-in like ``cmake_layout`` is typically good enough, but you can customize it too.

**Comment by sakra** [comment]
Thanks. How can I set `self.folders.generators` attribute in my `conanfile.txt` file?
Is it possible to set this globally in the `~/.conan2/global.conf` file?

**Comment by memsharded** [comment]
The ``conanfile.txt`` can only use predefined layouts like ``cmake_layout``.
If you want to customize it, it should be done in a ``conanfile.py``. You can read about the rationale about it in https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html

> Is it possible to set this globally in the ~/.conan2/global.conf file?

It is not possible. The layout is a property of the project. Every project can have a different layout, and different build systems have necessarily a different layout, so it cannot be generalized. In most cases just ``cmake_layout(self)`` can be enough. If you want to reuse layouts (or any other recipe functionality) accross different recipes, the recommendation is to use a ``python_requires`` to put the common code in it. Check https://docs.conan.io/2/reference/extensions/python_requires.html

**Comment by sakra** [comment]
Thanks!
