### ISSUE TITLE
[question] Extra labels or variables for Conan packages

### ISSUE THREAD

**Issue by Wizradus** [conan-io/conan#15138]
### What is your question?

Hello, I have a question regarding Conan packages in Artifactory. 
Do we have any possibility to mark in any way some Conan packages in Artifactory? We would like put some information / label / extra variable directly from Conan to Artifactory package. For example we want to add to package label "release" or "NoDelete" and so.
I have observed that Artifactory supports something like properties, but I don't see possibility manage it thru Conan.

Can you clarify if there is any possibility for this?

BR Wiz 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by danimtb** [comment]
Hello @Wizradus,

Indeed, the artifactory propertiees is the feature you are looking for.
While there is a native API in artifactory to set properties https://jfrog.com/help/r/jfrog-rest-apis/set-item-properties?page=2
I recommend that you use the artifactory custom commands we have developed for Conan to do this. You can take a look here: https://github.com/conan-io/conan-extensions/blob/main/extensions/commands/art/readme_property.md

These commands are an extension to the Conan client and have to be installed previously. Check the install instructions in the repo: https://github.com/conan-io/conan-extensions/tree/main

With the Artifactory custom commands setting properties to a reference would be as easy as:

```
# This step has to be done only once to setup your artifactory instance and credentials
$ conan art:server add my_artifactory <artifactory_server_url> --user=<user> --password=<pass>

$ conan art:property add <artifactory_repo> mypkg/1.0.0@user/channel --server my_artifactory --property="my_label=release"
```

Please, give it a try and let me know if it works for you 😄

**Comment by Wizradus** [comment]
> Indeed, the artifactory propertiees is the feature you are looking for. While there is a native API in artifactory to set properties https://jfrog.com/help/r/jfrog-rest-apis/set-item-properties?page=2 I recommend that you use the artifactory custom commands we have developed for Conan to do this. You can take a look here: https://github.com/conan-io/conan-extensions/blob/main/extensions/commands/art/readme_property.md
> ...
> Please, give it a try and let me know if it works for you 😄

Thanks @danimtb for you quick response. I will check the links and of course going to do some testing.

**Comment by Wizradus** [comment]
I going to close this question, because I'm focussed on different task currently. I don't want blocking this. If something I'll create new one and link this issue.
