### ISSUE TITLE
[bug] CONAN/LINKER/MODULE_CPP20/

### ISSUE THREAD

**Issue by IGORSVOLOHOVS** [conan-io/conan#15139]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: MSBuild version 17.7.2+d6990bcfa for .NET Framework
* Conan version: Conan version 2.0.13
* Python version: conanfile.txt
* Photo
<img width="409" alt="image" src="https://github.com/conan-io/conan/assets/98398989/0f6ddd34-3b8b-4451-bddd-7968fd9ce2dd">

[TaskTools.zip](https://github.com/conan-io/conan/files/13411216/TaskTools.zip)

### Steps to reproduce

**conanfile.txt**
<img width="224" alt="image" src="https://github.com/conan-io/conan/assets/98398989/7ecfc277-7019-46b3-bd6e-39e78840a946">

**Cmakefile.txt**
<img width="686" alt="image" src="https://github.com/conan-io/conan/assets/98398989/28d5537b-a02a-4763-9e78-7a5aecf718e6">

**main.ixx**
<img width="352" alt="image" src="https://github.com/conan-io/conan/assets/98398989/b03f1c44-76b8-4f86-b7cf-5cf98aa5a76d">

**config.ixx**
<img width="395" alt="image" src="https://github.com/conan-io/conan/assets/98398989/08a8825c-16ef-4291-bc56-d37098e1a8c0">

**test.ixx**
<img width="429" alt="image" src="https://github.com/conan-io/conan/assets/98398989/33296052-93ca-4949-83c8-b7fc581e503f">

### Logs

**conan install .**
<img width="1535" alt="image" src="https://github.com/conan-io/conan/assets/98398989/4579e27d-bfa0-40fc-a6eb-c2f974e2c8e9">

**cd buid & cmake ..**
<img width="875" alt="image" src="https://github.com/conan-io/conan/assets/98398989/ae9b8423-088f-42c1-bb99-c021e2b15665">

**cmake --build .**
<img width="1488" alt="image" src="https://github.com/conan-io/conan/assets/98398989/b49c8525-7106-48fd-9e0a-be41dffcd8cb">

IMPORTANT TO USE: Cmake, Conan, c++ modules, benchmark + yaml-cpp, c++20 or c++23, compiler: any
PROBLEM: I dont understand why I have problem with linking...

**Comment by jcar87** [comment]
Hi @IGORSVOLOHOVS - thank you for raising this issue.

I suspect the problem has to do with the use of the legacy CMake variables, 
```target_link_libraries(... ${yaml-cpp_LIB_DIRS_RELEASE}```
combined with the fact that you are running `cmake --build . `, which I believe builds `Debug` by default if the generator is Visual Studio.


I suggest you do:
```target_link_libraries(modules_lib PUBLIC yaml-cpp::yaml-cpp benchmark::benchmark)```
(this will take care of both the linking libraries _and_ the include directories)

and when building, make sure you build the same configuration that you have called `conan install` for:
```
cmake --build . --config=Release
```

Using modern CMake targets for linking is hugely recommended - variable names are legacy and are only provided for compatibility purposes for projects that were already using them. New projects should use imported targets instead.

**Comment by IGORSVOLOHOVS** [comment]
Thank you!

**Comment by IGORSVOLOHOVS** [comment]
<img width="288" alt="image" src="https://github.com/conan-io/conan/assets/98398989/247995e3-7109-4eee-9775-88e87a126da0">

<img width="348" alt="image" src="https://github.com/conan-io/conan/assets/98398989/a8fc21f3-fde6-4f10-855e-be2684cd44ed">

<img width="610" alt="image" src="https://github.com/conan-io/conan/assets/98398989/d8d899a5-fad0-4744-b87c-eaf9fcff75d3">

PROBLEM: do not call function parser

**Comment by jcar87** [comment]
Hi @IGORSVOLOHOVS - is the problem that the executable now builds successfully but it doesn't run?

This is likely due to the fact that the dependencies are shared libraries (in your `conanfile.txt` the dependencies are `shared=True`), and the command line is not printing any errors about it.
After `main.exe`, I suspect if you run the following command:
```
echo $LastExitCode
```

you might see the code`-1073741515 (0xC0000135)` which is the error for not being able to locate DLLs.


In order to address this, assuming you are using powershell:
* pass `-c tools.env.virtualenv:powershell=True` when invoking `conan install`
* OR add `tools.env.virtualenv:powershell=True` to the `[conf]` section ~in `conanfile.txt`~ edit: in your conan profile

Conan will generate a file called `conanrun.ps1`, which will set up the environment such that executable can locate DLLs - this file is in the generators folder used by Conan.

Simply call
```
./conanrun.ps1
```
before calling
```
./Release/main.exe
```

that should take care of this issue

**Comment by IGORSVOLOHOVS** [comment]
Eh, I have the same problem...

conan install . -c tools.env.virtualenv:powershell=True
![image](https://github.com/conan-io/conan/assets/98398989/c980b29d-dc4c-41c9-853a-e882b887e2ad)

.\conanrun.ps1 do not work (((, I used  powershell -ExecutionPolicy Bypass -File .\conanrun.ps1 
![image](https://github.com/conan-io/conan/assets/98398989/d193a7d4-11e3-4e73-be55-990e72f3c57d)

build cmake
![image](https://github.com/conan-io/conan/assets/98398989/dd38412d-e1aa-4eda-9bf5-b199ce4a0c9c)

Nothing...
![image](https://github.com/conan-io/conan/assets/98398989/61cec84a-9616-4563-b0c2-178193ef2d63)

**Comment by jcar87** [comment]
After invkoing `conanrun.ps1`, if you print the PATH environment variable with `echo $Env:Path` - that should point to the `bin` binaries inside the Conan cache that contain the .DLLs, could you check if that is the case?

**Comment by IGORSVOLOHOVS** [comment]
The result is:
![image](https://github.com/conan-io/conan/assets/98398989/3ff31095-faeb-4c95-af4b-8515d659dedf)

**Comment by jcar87** [comment]
Indeed I cannot see the modified Path environment variable.

I would inspect the contents of both `conanrun.ps1` and the file it itself invokes (something along the lines of `conanrun-release-x86_64.ps1`). If the contents are correct and the Path environment variable is correctly modified, that is, at the end of the file you should see an assignment
```
$env:PATH=
```

where there are entries to the bin dirs for both of your dependencies.

if the contents of the files are correct, perhaps I'd be looking at the Powershell execution policies.

**Comment by IGORSVOLOHOVS** [comment]
Hi @jcar87!Yes, the problem was that bin folder could not be set in the PATH enviroment, because PowerShell... Thank you! Full solve:
1. run powershell with admin 
2. Set-ExecutionPolicy RemoteSigned 
3. conan install . -c tools.env.virtualenv:powershell=True 
4. .\conanbuild.ps1
5. .\conanrun.ps1
6. cd build 
7. cmake .. 
8. cmake --build . --config=Release 
9. .\Release\main.exe
