### ISSUE TITLE
[question] Does `--build="*"` always recompile?

### ISSUE THREAD

**Issue by skhaz** [conan-io/conan#15131]
### What is your question?

I'm not sure if it's the cache of my CI failing, but I have the impression that all dependencies are being recompiled every time. 

Is this an expected behavior of the asterisk (recompile **always**), or should I always use missing in case I don't want this behavior?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @skhaz 

Definitely, the ``--build="*"`` will recompile everything, always. 
This is really not recommended in most cases, and should probably be used only at development time to potentially debug something, but even in that case re-building everything might not be necesssary.

The recommended flow for many production scenarios would be to not use ``--build`` at all, and assume that the CI would have already built the binaries that the developer in the team/organization needs. This is the way saving lots of time unnecessarily rebuilding over and over from source is possible. Then, when a binary is "missing", it should be treated as a CI failure, something happened and the binary was not created, it should be created.

The ``--build=missing`` should be used mostly in CI scenarios, when something changes and we want to re-build downstream affected packages, or by developers while exploring, debugging or testing things, but not as a normal "installation" process.

**Comment by skhaz** [comment]
@memsharded, thank you very much for clarifying, it all makes sense.
