### ISSUE TITLE
[question] Using internal package requires generated files

### ISSUE THREAD

**Issue by mikirothman** [conan-io/conan#15147]
### What is your question?

Hi,

we have several packages that uses VS + MSBuild as the build system.
we use conan 2.x
let's say on package 'p' we declare 2 components: 'x' and 'y'.

when consumers of p will invoke their generate method they will get x and y data suitable for their build system (assuming we implemented package_info with the data).

but let's say y require x internally ? can we somehow create / consume conan generated files ?
I thought maybe if I declare the components relation in the layout method these data will be generated for me, but it wasn't.

of course for a more modern build system, it is straight forward to declare the relation between the components, but in MSBuild, we need to create props file by hand and maintain it, and when the data is already generated by conan it feels not correct to do so...

is there any existing solution for retrieving the components data within the build context ?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mikirothman 

Thanks for your question.

> but let's say y require x internally ? can we somehow create / consume conan generated files ?

Components can declare their relations like:
```python
def package_info(self):
  self.cpp_info.components["compx"].libs = ["libx"]
  self.cpp_info.components["compy"].libs = ["liby"]
  self.cpp_info.components["compy"].requires = ["compx"]
```
This way, Conan knows that liby->libx, and when it generates the information, they will be dependent.
Note for the most part, the definition is in ``package_info()``, not ``layout()``, unless we want to support the ``editable`` case.

> is there any existing solution for retrieving the components data within the build context ?

That of the "build" context I don't fully understand. Typically components are libraries in the host context, the build context just contains executables, tools to run, not different libraries.

**Comment by mikirothman** [comment]
I think I didn't explain the issue properly,
if I will declare the relations in the package_info method, the consumer of package 'p' will retrieve the information regards component 'x', that's great.
what I'm asking about is a way to use the information of component 'x' (AKA VS props file for example), inside package 'p'.
it will allow me to expose the x information (include path, libdir and etc), to other components in package 'p'.
since it is based on the layout, I thought it might be possible to generate this data not only for consumers of 'p', also for developing components inside 'p' (that consuming the build folders and not the package folders)

**Comment by memsharded** [comment]
> what I'm asking about is a way to use the information of component 'x' (AKA VS props file for example), inside package 'p'.
it will allow me to expose the x information (include path, libdir and etc), to other components in package 'p'.

I think I see what you mean now.

There is no "generation" concept for the package itself, the generators work exclusively for dependencies, not for the current package.

If you still want to leverage some common information for both your package and the consumers, you could do something like:
- Define your structure of information in a common place. It can be a private recipe method, or if you want to have it structured, maybe even in the ``conandata.yml`` file.
- Your ``generate()`` methods reads this information and generate the files that you want
- the ``package_info()`` or ``layout()`` methods can read it, and use it to define themselves

In any case, having this built-in into Conan is not considered. This would take Conan too deep into the build-systems realm, and this is something that is really too outside of Conan scope. So the package recipes should wrap build systems that are self-contained with regard to themselves, without needing extra files provided by Conan.
