### ISSUE TITLE
[question] cmake release type do not use default flags from cmake

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#15144]
### What is your question?

Dear Conan Folks,

I have a question. CMake adds the following flags by default :
CMAKE_CXX_FLAGS_DEBUG -g -O0
CMAKE_CXX_FLAGS_RELEASE -O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO -O2 -g -DNDEBUG
CMAKE_CXX_FLAGS_MINSIZEREL -Os -DNDEBUG

For the release build type we donot want any of these default flags to be added.
I found one or two ways to handle it but none of them is optimal.
I would like compiler flags to be handled in the profiles.
First way is to define it in the recipes:
```
def build(self):
    cmake = CMake(self)
    cmake.definitions["CMAKE_BUILD_TYPE"] = self.settings.build_type
    if self.settings.build_type == "Release":
        releaseflags = cmake.definitions.get("CMAKE_CXX_FLAGS_RELEASE", "")
        releaseflags = releaseflags.replace("-O3", "").replace("-DNDEBUG", "")
        cmake.definitions[CMAKE_CXX_FLAGS_RELEASE] = releaseflags.strip()
```
And another way is to define it in the CMakeLists.txt:
```
set(CMAKE_C_FLAGS_RELEASE          "${CMAKE_C_FLAGS}")
```
Both are not the best as we have to define them in every recipe or cmakelists.txt.
I see that buildenv does allow to append, prepend or unset but not to remove : https://docs.conan.io/2/reference/config_files/profiles.html?highlight=tools%20build%20cflags 

Could this be somehow extended? Or what is the best way to handle this use-case?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by maitrey** [comment]
Is it possible to somehow influence CMAKE_C_FLAGS_RELEASE in the profiles?

**Comment by memsharded** [comment]
Hi @maitrey 

You can totally control what CMake does, because you can inject toolchain files, with any variables definitions that you want.
Please have a look at: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/inject_cmake_variables.html

**Comment by maitrey** [comment]
Thanks a lot! works ticket can be closed :)

**Comment by memsharded** [comment]
Great, thank you!
