### ISSUE TITLE
[question] Scons Deps generator within build requirements

### ISSUE THREAD

**Issue by priyank31malhotra** [conan-io/conan#15146]
### What is your question?

Hi,
I was having some confusion regarding intergrating the sconsdeps or scons generator in the conanfile.py
`
class ZoneRecipe(ConanFile):
    # Package binary configuration
    settings = "os", "compiler", "build_type", "arch"
    package_type = "application"

    def requirements(self):
        self.requires("zlib/1.3")
        self.requires("robin-hood-hashing/3.11.5")
        
        # Add base64 dependency for Windows
        if self.settings.os == "Windows":
            self.requires("base64/0.4.0")

    def build_requirements(self):
        # Use the system's CMake for Windows
        if self.settings.os != "Windows":
            self.tool_requires("SConsDeps/4.3.0")`

This does not seem to work. Can you provide me a work around for this. Any version of scons will work. Basically I want to know how to use scons as a generator in this.

Thanks,
Priyank

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @priyank31malhotra 

Thanks for your question.
I think there is some confusion. ``SConsDeps`` is built-in. You don't need to ``tool_requires("SConsDeps")`` to use it or anything like, that, just import it.

You have docs for it in https://docs.conan.io/2/reference/tools/scons.html, please have a look, but something like:

```python
from conan import ConanFile
from conan.tools.scons import SConsDeps

class App(ConanFile):
    settings = "os", "arch", "compiler", "build_type"

    def generate(self):
        tc = SConsDeps(self)
        tc.generate()
```

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you for a while now, feel free to reopen/create a new issue should you have new questions about this :)
