### ISSUE TITLE
[feature] Predicate extraction filter for tools.get/untargz

### ISSUE THREAD

**Issue by nextsilicon-itay-bookstein** [conan-io/conan#15157]
### What is your suggestion?

I found myself needing a variant of `tools.get` which would:
1. Play well with the download cache
2. Let me filter extracted entries via code (regex was insufficient, I wanted to exclude examples and docs in various locations within the directory tree)

I've implemented this privately by copying and customizing upstream conan's code inside a locally-developed recipe, and it looks something like this (note the `predicate` argument):
```
def _customized_untargz(filename, destination=".", predicate=None, strip_root=False):
    """
    See conans.client.tools.files.untargz.
    """
    import tarfile
    with tarfile.TarFile.open(filename, 'r:*') as tarredgzippedFile:
        if not predicate and not strip_root:
            tarredgzippedFile.extractall(destination)
        else:
            members = tarredgzippedFile.getmembers()

            if strip_root:
                names = [n.replace("\\", "/") for n in tarredgzippedFile.getnames()]
                common_folder = os.path.commonprefix(names).split("/", 1)[0]
                if not common_folder and len(names) > 1:
                    raise ConanException("The tgz file contains more than 1 folder in the root")
                if len(names) == 1 and len(names[0].split("/", 1)) == 1:
                    raise ConanException("The tgz file contains a file in the root")
                # Remove the directory entry if present
                members = [m for m in members if m.name != common_folder]
                for member in members:
                    name = member.name.replace("\\", "/")
                    member.name = name.split("/", 1)[1]
                    member.path = member.name
                    if member.linkpath.startswith(common_folder):
                        # https://github.com/conan-io/conan/issues/11065
                        linkpath = member.linkpath.replace("\\", "/")
                        member.linkpath = linkpath.split("/", 1)[1]
                        member.linkname = member.linkpath
            if predicate:
                members = list(filter(lambda m: predicate(m.name),
                                      tarredgzippedFile.getmembers()))
            tarredgzippedFile.extractall(destination, members=members)


def _customized_tools_get(
    url, sha256="", destination=".", filename="", predicate=None, strip_root=False
):
    """
    Code copied from conans.tools.get, to customize extraction logic,
    because ortools has a large archive and we'd like to avoid extracting
    unneeded files.
    """
    url_base = url[0] if isinstance(url, (list, tuple)) else url
    if "?" in url_base or "=" in url_base:
        raise ConanException("Cannot deduce file name from the url: '{}'.")
    filename = os.path.basename(url_base)
    if not filename.endswith(".tar.gz"):
        raise ConanException("Unexpected ortools archive format.")

    # Forwarding kwargs in case they have a hash (for download cache).
    tools.download(url=url, sha256=sha256, filename=filename)
    try:
        _customized_untargz(
            filename=filename,
            destination=destination,
            predicate=predicate,
            strip_root=strip_root,
        )

    finally:
        os.unlink(filename)
```

I recall discussing this with conan devs back in June at C++Now, so here's the followup :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nextsilicon-itay-bookstein 

Thanks for your suggestion

> I recall discussing this with conan devs back in June at C++Now,

Maybe you mean CoreC++? In IL?


I am not sure about the added complexity for this use case. It would be interesting to know about the absolute times (without filtering) and the time savings. Even if this operation is relatively slow, it is usually much less than building from source.

The first step is solvable with the new publicly available ``from conan.tools.files import download`` in https://docs.conan.io/2/reference/tools/files/downloads.html#conan-tools-files-download. This will already manage and leverage the download cache in the same way ``get()`` does.

From there, it would be mostly just unzipping a file, wouldn't it? If we remove some of the aspects that you might not need, the implementation would be something like:
```python
with tarfile.TarFile.open(filename, 'r:*') as tarredgzippedFile:
     members = list(filter(lambda m: predicate(m.name), tarredgzippedFile.getmembers()))
     tarredgzippedFile.extractall(destination, members=members)
```
so maybe that can go directly in to the recipe?

We are trying to avoid the proliferation of knobs and parameters for niche use cases that 99% of users will not use and can be implemented in just a few lines directly in the recipe. Otherwise the bloat of parameters, tests, documentation, support, etc ends up accumulating and slowing down many other important things.

**Comment by memsharded** [comment]
Any further feedback here?

**Comment by nextsilicon-itay-bookstein** [comment]
Whoops, forgot about this, sorry.

> Maybe you mean CoreC++? In IL?
>
Yup, that's the one. 

> so maybe that can go directly in to the recipe?
>
That's essentially what we ended up doing. Offered this up because it seemed somewhat generically useful, since releases of more complex software packages can often include a lot of content that ends up not used in the particular recipe invocation one makes.

> We are trying to avoid the proliferation of knobs and parameters for niche use cases that 99% of users will not use and can be implemented in just a few lines directly in the recipe. Otherwise the bloat of parameters, tests, documentation, support, etc ends up accumulating and slowing down many other important things.
>
Fair enough :)

**Comment by memsharded** [comment]
> Whoops, forgot about this, sorry.

No prob :)

> That's essentially what we ended up doing. Offered this up because it seemed somewhat generically useful, since releases of more complex software packages can often include a lot of content that ends up not used in the particular recipe invocation one makes.

In many cases it is simply not worth the effort, it might be slower, but the overall time is little compared with build times, and added complexity also might have issues, require maintenance, etc.

I think I'll close this as unplanned at the moment, but don't hesitate to create new tickets for any further question, thanks very much for the feedback!
