### ISSUE TITLE
[question] Per dependency flags

### ISSUE THREAD

**Issue by skhaz** [conan-io/conan#15158]
### What is your question?

I have a dependency (Lua) that I need to compile with the flags listed below, but I would prefer not to compile the entire project with them. Is there any way to accomplish this?

```
[conf]
tools.build:cflags=["-fsanitize=address"]
tools.build:cxxflags=["-fsanitize=address"]
tools.build:exelinkflags=["-fsanitize=address"]
tools.build:sharedlinkflags=["-fsanitize=address"]
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @skhaz thanks a lot for your question. It's indeed possible to restrict which packages get what configuration by using configuration patterns ([Docs here](https://docs.conan.io/en/1.62/reference/config_files/global_conf.html#configuration-patterns))

In your case, it would look something like this:

```
[conf]
lua:tools.build:cflags=["-fsanitize=address"]
lua:tools.build:cxxflags=["-fsanitize=address"]
lua:tools.build:exelinkflags=["-fsanitize=address"]
lua:tools.build:sharedlinkflags=["-fsanitize=address"]
```

Let me know if that helps :)

**Comment by skhaz** [comment]
@RubenRBS, thank you so much!
