### ISSUE TITLE
[question] conan install + tools.file.save in generate method

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#15154]
### What is your question?

Dear Conan Folks,

I have in one of the tool_requires package the generate method as:
```
def generate(self):
    transformxml_runner_file = os.path.join(self.source_folder, "transformxml.bat")
    transformarxml_to = (f'@echo off \n'
                        f'pushd %~dp0 \n'
                        f'{sys.executable} -u {os.path.join(".", "FileCreation", "transformXml", "transformxml.py")} '
                        f'-p="{os.path.join(self.dependencies.build["pkg"].package_folder)}" '
                        f' \n'
                        f'popd')
    save(self, 
        path=transformxml_runner_file,
        content=transformarxml_to)
    self.output.info("INFO:::Generate was called")
````
When I indicate this package as a dependency, I thought that the transformxml.bat that is packaged will have the pkg folder as an absolute path. But it actually contains the correct path to the pkg folder both in CI as well as my local. Does this mean that when I run a conan install the generate method of the dependency is somehow executed or how does it get the correct path to the pkg folder in transformxml.bat? Could someone please help me understand. I seem to have a misunderstanding  :(

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

Not sure if I completely understand the intention, but I'll try to clarify

> When I indicate this package as a dependency,

When a package is used as dependency, its ``generate()`` method doesn't execute at all. The ``generate()`` method is only local-build, that means that it is only executed if the package is going to be built from source. If it is consumed as existing binary, the ``generate()``, ``source()`` and ``build()`` methods are not called at all.

> . Does this mean that when I run a conan install the generate method of the dependency is somehow executed or how does it get the correct path to the pkg

This might happen if you are doing a ``conan install --build=xxxx`` and that ``xxxx`` is triggering the build of the dependency. If not, whatever you get in the ``transformxml.bat`` (assuming there is some ``package()`` later that packages that file as final package) should have the folder that was used back them when that binary was built from source.

**Comment by maitrey** [comment]
Contents of my recipe are:
```
import os
from conan import ConanFile
from conan.errors import ConanException
from conan.tools.files import copy, save
import sys


class FileCreation(ConanFile):
    name = 'filecreation'
    exports_sources = "src/*.*"
	version=1.0

    def build_requirements(self):
        self.tool_requires("pkg/0.0.0-dev.0@autosar/featuretest")
    
    def generate(self):
		transformxml_runner_file = os.path.join(self.source_folder, "transformxml.bat")
		transformarxml_to = (f'@echo off \n'
                        f'pushd %~dp0 \n'
                        f'{sys.executable} -u {os.path.join(".", "FileCreation", "transformXml", "transformxml.py")} '
                        f'-p="{os.path.join(self.dependencies.build["pkg"].package_folder)}" '
                        f' \n'
                        f'popd')
		save(self, 
        path=transformxml_runner_file,
        content=transformarxml_to)
		self.output.info("INFO:::Generate was called")

    def package(self):
        copy(self, "transformxml.bat", self.source_folder, os.path.join(self.package_folder), keep_path=False)

    def package_info(self):
        self.cpp_info.set_property("transformxml_runner_file", os.path.join(self.package_folder, "transformxml.bat"))
        # clean cpp_info default values
        self.cpp_info.includedirs = []
        self.cpp_info.libdirs = []
        self.cpp_info.bindirs = []
# EOF
```
I donot use conan install with --build=xxxx . If I do a simple conan install it automatically picks the right location of the pkg which is defined as a dependency as in the recipe.

**Comment by maitrey** [comment]
Or is it the conan build --deployer=full_deploy that is able to somehow compute the full path to pkg where this FileCreation package is consumed?

**Comment by memsharded** [comment]
In any case, I'd like to clarify one thing: having one ``tool_requires`` containing a file that contains the ``package_folder`` of one of its transitive ``tool_requires`` is ill-formed. Packages should never require anything from their ``tool_requires`` for "runtime", they should be totally independent of them, because the idea is that ``tool_requires`` will not be there at all if there is already a binary for it. So having a path to a ``tool_require`` is not possible.

**Comment by memsharded** [comment]
Yes, if you are doing a deploy the moment you are building that package with ``conan build --deployer=...``, then just by luck/coincidence, it will work locally in that machine, because it contains a local copy in a user folder. But this is certainly not recommended, as this will certainly not work if you just ``conan install`` that package as a dependency in another different machine.

**Comment by maitrey** [comment]
Thanks for your reply! I expected it NOT to work but up until now could not figure out how does it edit and get the correct path of pkg wherever filecreation is consumed. I also had a look to the source code looking for hints in the copy method but could not find anything. Can you please help me figure out how does it works NOT only locally but also on our CI/CD environment ?

**Comment by maitrey** [comment]
I got the reason why it worked so far, sorry we were using another version of the package where the pkg was also packaged also not a good way. Thanks and ticket can be closed. Sorry for bothering you. Sometimes simple answers look complex.

**Comment by memsharded** [comment]
Don't worry, no bother at all, these things happen. Happy to help and that the issue is identified.
