### ISSUE TITLE
[question] How to use tools.scm.git with patches?

### ISSUE THREAD

**Issue by ottmar-zittlau** [conan-io/conan#15156]
### What is your question?

Hi,

I'm currently trying to modernize some local conan recipes - here for protobuf.
One aspect is to switch from `conans.tools.Git` to `conan.tools.scm.Git`.

My recipe has the following `export_sources` and `source`-methods:
```
def export_sources(self):
    export_conandata_patches(self)
    
def source(self):
    git = Git(self)
    clone_args = ['--depth', '1', '--branch', "v25.1"]
    git.clone(url=self.url, target=".", args=clone_args)

    # git = tools.Git()
    # git.clone(self.url, "v25.1", shallow=True)
    apply_conandata_patches(self)
```
With the old (commented) version everything worked fine.
With the new version I now get the error:
```
ERROR: protobuf/25.1@test/test: Error in source() method, line 36
	git.clone(url=self.url, target=".", args=clone_args)
	CalledProcessErrorWithStderr: Command 'git clone "https://github.com/protocolbuffers/protobuf.git" --depth 1 --branch v25.1 .' returned non-zero exit status 128.
fatal: destination path '.' already exists and is not an empty directory.
```
My current explanation is, that conan copies the patch and the `conandata.yml` to the source folder first and then tries to clone into this (now non-empty) folder.

I tried to run with it, by changing the path in my patch and use the default clone target:
```
git.clone(url=self.url, args=clone_args)
```
which will clone into a subfolder with the same name as the repo.
This works - however, then my build step fails:
```
def build(self):          
    cmake = CMake(self)
    cmake.configure()
    ....
```
More accurately the configure step already fails. I think that it is not aware of the subfolder added by git clone.
What is the recommended practice for this?
Is there a way to delay copying the patches to the source folder or do I need to tell conan that the sources are in a subfolder?

Thanks and best regards
oz

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ottmar-zittlau 

Thanks for your question.
The recommended practice for modern tools, even in Conan 1.X is to define the relative location of things in the recipe/project, with the ``layout()`` method. Please check: https://docs.conan.io/1/reference/conanfile/methods.html#layout and https://docs.conan.io/1/reference/conanfile/tools/layout.html

There is also this example in the Conan 2.0 docs: https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html#examples-tools-scm-git-capture, that uses the helper with the ``layout()`` using ``cmake_layout()``. I think this example might be even backwards compatible with 1.X

**Comment by ottmar-zittlau** [comment]
Hi @memsharded,

thanks again for the quick reply! 

I now added the `cmake_layout` command, like so:
```
from conan.tools.cmake import cmake_layout
....
def layout(self):
    cmake_layout(self)
```
This didn't work, so I tried different arguments:
```
cmake_layout(self, src_folder="protobuf")
cmake_layout(self, build_folder="protobuf")
cmake_layout(self, src_folder="protobuf", build_folder="protobuf")
```
If I specify `src_folder` - the data is cloned into `...sources/protobuf/protobuf` - which seems not the correct thing to do.
Specifying `build_folder` changed nothing.
Is there anything else I need to specify in the layout method. Maybe one of the layout folders (https://docs.conan.io/1/reference/conanfile/methods.html#self-folders) - but why would I use `cmake_layout` then?

Thanks and best regards
oz

**Comment by memsharded** [comment]
For packaging third-party code, using Git.clone is actually not a common practice, the recommended approach is to do a ``download()`` of the released source tarball, it is generally way simpler and more robust.

If you want to avoid the extra nested folder you can use the ``target="."`` argument to ``git.clone()`` I have just tested this and it works (I am using a ``src`` folder, but you can give it other name):

```python
    exports_sources = "potato.txt"

    def layout(self):
        cmake_layout(self, src_folder="src")

    def source(self):
        git = Git(self)
        # Bad practice, checking out a commit is the correct approach
        git.clone(url="https://github.com/conan-io/libhello.git", target=".")
```

**Comment by ottmar-zittlau** [comment]
Excellent, thank you - I was not aware that using the tarball is more common. I switched to using it instead of git and it works much smoother.

**Comment by memsharded** [comment]
Yeah, for third party it is better, for example every recipe in ConanCenter use ``download`` and not ``git.clone``.
