### ISSUE TITLE
[feature] `conan graph info` should print to stdout

### ISSUE THREAD

**Issue by kyllingstad** [conan-io/conan#15162]
### What is your suggestion?

`conan graph info` should print its primary output – the YAML code containing the dependency graph info – to the standard output stream.

Currently, it is printed to the standard error stream, which is problematic because:
* It is not immediately obvious why piping the output to a file or program doesn't work. (Experienced users will soon find that adding `2>&1` to the command line helps, but to many, this is rather arcane knowledge.)
* The YAML code gets mixed up with the status messages printed at the start, so even if you do pipe stderr to a file, the result is not a valid YAML file.

I am aware that using e.g. `--format=json` *does* result in clean output being printed to stdout as desired, but this is not obvious from the documentation, and YAML does not seem to be among the supported formats for that switch. Ideally, I'd like to see something like `--format=yaml` being an implicit default.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @kyllingstad thanks a lot for your report. You're right in that the `--format=text` formatter for graph info should be printing to stdout - I've proposed #15170 to fix the issue.

> the YAML code containing the dependency graph info – to the standard output stream.

Please note that the graph info output is _not_ YAML. The format just looks a bit like that, but it's not our intention to make it actually output YAML, and it's only meant as a visual representation. If you ever need structured output, please use the `--format=json` one, which we feel is enough to support any conceivable user-case :)

**Comment by kyllingstad** [comment]
I understand. Thanks for the fix!
