### ISSUE TITLE
[feature] Supress Conan 2 compatibility message

### ISSUE THREAD

**Issue by mariuszwicker-cnhind** [conan-io/conan#15161]
### What is your suggestion?

When a recipe fails to build Conan 2 will print a migration note regarding v2 compatibility:

```
*********************************************************
Recipe 'conanfile.py (...)' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************
```

This is confusing our developers though because they assume a Conan issue when in fact its a good old compiler failure right above that flashy message. Looking at the code I found now way to disable this - is there any plans to offer an option for that?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your feedback @mariuszwicker-cnhind 

That sounds right, lets remove that message, most of ConanCenter is now Conan 2.0 compatible, this message is probably more confusing at this stage than helpful.

**Comment by mariuszwicker-cnhind** [comment]
Awesome. Thanks for the quick turnaround.
