### ISSUE TITLE
[question] how to only depend on certain boost components

### ISSUE THREAD

**Issue by h-2** [conan-io/conan#15160]
### What is your question?

I am currently doing
```toml
[requires]
boost/1.83.0
```
And then doing
```cmake
find_package(Boost 1.57.0 COMPONENTS
    chrono
    date_time
    filesystem
    headers
    iostreams
    regex
    serialization
    system
    thread
    REQUIRED
    NO_MODULE)
```

This all works fine, but I would like to not build those parts of boost, that I won't use later on. I also expect the number of boost modules that we require going down.

I have read *somewhere* that it is possible to select only certain components from a package? With "options" maybe?

Unfortunately, most of the documentation floating around is still for conan1 and searching for "boost" or "components" or "options" in the conan2 documentation did not yield any obvious solutions.

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @h-2 

Thanks for your question.

> I have read somewhere that it is possible to select only certain components from a package? With "options" maybe?

Yes, the ``boost`` recipe has defined multiple ``without_xxx`` options that you can use to deactivate the building of certain libraries, among the defined:
```
CONFIGURE_OPTIONS = (
    "atomic",
    "chrono",
    "container",
    "context",
    "contract",
    "coroutine",
    "date_time",
    "exception",
    "fiber",
    "filesystem",
    "graph",
    "graph_parallel",
    "iostreams",
    "json",
    "locale",
    "log",
    "math",
    "mpi",
    "nowide",
    "program_options",
    "python",
    "random",
    "regex",
    "serialization",
    "stacktrace",
    "system",
    "test",
    "thread",
    "timer",
    "type_erasure",
    "url",
    "wave",
)
```

So basically the recommendation would be adding to your profiles:
```
[options]
boost/*:without_xxxx=True
....
```

**Comment by memsharded** [comment]
Note there is no documentation about this in the Conan docs, because this is specific to the boost recipe. Recipes might not provide this, and it means that all components will always be built. The components is a way to indicate usage, but they don't really define the build or binary of a package.

**Comment by h-2** [comment]
Thanks for the quick reply! Just for clarification, the syntax for deactivating multiple things would be
```
[options]
boost/*:without_atomic=True
boost/*:without_container=True
...
```
?
So, if I only want boost::filesystem, I need to explicitly exclude everything else? 😆 

> Note there is no documentation about this in the Conan docs, because this is specific to the boost recipe. Recipes might not provide this, and it means that all components will always be built. The components is a way to indicate usage, but they don't really define the build or binary of a package.

Hm, this is not really clear to me. There is a generic "component mechanism" that defines how packages can provide several "sub-packages", and it is also defined how other packages can depend on those "sub-packages", but the method of (not) building those sub-packages is independent?

**Comment by memsharded** [comment]
> So, if I only want boost::filesystem, I need to explicitly exclude everything else?

Yes. But you might enjoy the profiles ``jinja`` templating, you might be able to do a ``for`` loop that iterates a list and do it in just a couple of lines.

> Hm, this is not really clear to me. There is a generic "component mechanism" that defines how packages can provide several "sub-packages", and it is also defined how other packages can depend on those "sub-packages", but the method of (not) building those sub-packages is independent?

Yes, the components mechanism is a mechanism to define usage or linkage of libraries within a package, not for really defining sub-packages. The package is an entity that is built, released, uploaded, downloaded as a unit, with all its components inside. Then, users can select to link only one of its libraries. One example would be the ``openssl`` package, that actually contains 2 libraries ``libssl`` that depends on ``libcrypto``. You cannot really build or install them separately, you always install both libraries. But there are users that might want to link only ``libcrypto``. They can do it by specifying they require the ``crypto`` component only, but the full openssl dependency has been built and installed.

**Comment by h-2** [comment]
Thank you for your helpful replies! One last question:
can I make conan output what the conanfile.txt was rendered to after resolving the jinja templating? Right now it only tells me:
```
ERROR: Error while parsing [options] in conanfile.txt
Options should be specified as 'pkg/*:option=value'
```
which is not very useful for a Jinja noob like me. Something like `Expected 'pkg/*:option=value' but got 'XXXYYY'` would be great!

**Comment by h-2** [comment]
Background: I have tried using the following

```jinja
{% set disabled_boost_pkgs = ['atomic', 'container'] %}
{%- for subpkg in disabled_boost_pkgs -%}
boost/*:without_{{ subpkg }}=True
{% endfor %}
```

and according to http://jinja.quantprogramming.com/ this is translated to
```
boost/*:without_atomic=True
boost/*:without_container=True
```

But conan still gives me the aforementioned error.

**Comment by memsharded** [comment]
It is working perfectly fine here! 
Just tried it:
```
[options]
{% set disabled_boost_pkgs = ['atomic', 'container'] %}
{%- for subpkg in disabled_boost_pkgs -%}
boost/*:without_{{ subpkg }}=True
{% endfor %}
```
Then
```bash
conan profile show -pr=myprofile
```
and it works fine, it renders fine, I can use the profile for ``conan install`` too. Maybe it is something else? What Conan version are you using? (latest 2.0.14 is the recommended one)

**Comment by h-2** [comment]
Just to be clear, the options are added to the `conanfile.txt` and not to the profile, or are they?

This is my conanfile.txt right now:

```toml
[requires]
boost/1.83.0
libxml2/2.11.4
libiconv/1.17
libcurl/8.2.1
pcre/8.45
hunspell/1.7.2
openssl/3.1.2

[tool_requires]
cmake/3.26.4

[generators]
CMakeDeps
CMakeToolchain

[options]
{% set disabled_boost_pkgs = ['atomic', 'container'] %}
{%- for subpkg in disabled_boost_pkgs -%}
boost/*:without_{{ subpkg }}=True
{% endfor %}
```

This produces

```
% conan install SOURCEDIR --output-folder . --build=missing --profile:all=RelWithDebInfo

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=RelWithDebInfo
compiler=clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=17
os=Linux
[conf]
tools.build:compiler_executables={'c': 'clang-17', 'cpp': 'clang++-17'}
tools.cmake.cmaketoolchain:generator=Ninja

Profile build:
[settings]
arch=x86_64
build_type=RelWithDebInfo
compiler=clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=17
os=Linux
[conf]
tools.build:compiler_executables={'c': 'clang-17', 'cpp': 'clang++-17'}
tools.cmake.cmaketoolchain:generator=Ninja

ERROR: Error while parsing [options] in conanfile.txt
Options should be specified as 'pkg/*:option=value'
```

edit: I am on 2.0.14

**Comment by memsharded** [comment]
> Just to be clear, the options are added to the conanfile.txt and not to the profile, or are they?

Only the profile does ``jinja`` rendering, the conanfile.txt does not and will indeed fail.

In general it is more recommended to define options in the profile, because the profile you use it for different packages, and you don't want when building a different package recipe conanfile.py to suddenly require the whole boost again, you want it to be consistent with the other conanfiles.

**Comment by h-2** [comment]
> Only the profile does jinja rendering, the conanfile.txt does not and will indeed fail.

OK, thanks for clarifying!

> In general it is more recommended to define options in the profile, because the profile you use it for different packages, and you don't want when building a different package recipe conanfile.py to suddenly require the whole boost again, you want it to be consistent with the other conanfiles.

I am sorry, but this is very counter-intuitive. I have a repo-wide profile with my compiler settings etc, and then I have a bunch of smaller projects in the repo, some of which require many boost components, some require only few boost components and some require no boost componenets. They already define via their individual conanfile if they use boost or not. And via `find_package` they declare which components they use. 

*This is clearly a per-target property*, and it is not possible to define on a global scale. Indeed, a person modifying one of the projects (e.g. removing a boost dependency) should definitely not have to change the profile.

I guess I could use a `conanfile.py` (instead of `conanfile.txt`) to generate the list of options per-project?

**Comment by memsharded** [comment]
> I am sorry, but this is very counter-intuitive. I have a repo-wide profile with my compiler settings etc, and then I have a bunch of smaller projects in the repo, some of which require many boost components, some require only few boost components and some require no boost componenets. They already define via their individual conanfile if they use boost or not. And via find_package they declare which components they use.

> This is clearly a per-target property, and it is not possible to define on a global scale. Indeed, a person modifying one of the projects (e.g. removing a boost dependency) should definitely not have to change the profile.

This is the thing about components, that this is not the default recommended approach. If you have that setup, the recommendation is:
- Do not define any options, just bring and build the full boost
- Every project will define its own components usage to link only with the components they want

Otherwise you will end with every different consumer requiring a different boost binary, re-building from source for every consumer a slightly different package of boost, just because one consumer is requiring one component and other consumer is requiring other component. That ends with common components required by all projects to be re-built from source multiple times!

Defining your ``without_xxx`` options really only makes sense if different consumers have the same options, otherwise it is not worth it. Note that downloading an unzipping a  boost precompiled binary for a current configuration with all components built takes just a few seconds. It is not worth the complexity, and specially it will be bad performance wise, requiring more time building things from source and more storage too.

**Comment by h-2** [comment]
Thanks for the good explanation. I will go with the full package then. I had thought that project A uses component X and project B uses component X and Y, but no project uses component Z; then I could disable Y and Z for A and only disable Z for B and that they would share their build of X. But if X would have to be rebuilt, it's not worth it.

**Comment by memsharded** [comment]
Yeah, there is no "intersection" of options. Every different set of options compute a different ``package_id``, that needs to be built from source matching that sets of options. So unless the ``without_xxxx`` options really match, it can make the process more inefficient instead that more efficient.

Thanks for the feedback!
