### ISSUE TITLE
Install and deploy a package based on package_id

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#15164]
### What is your question?

Hi,
As I can list a package using the package_id (or just a truncation of it):

`conan list -r my_remote pkg/1.2.3*:9b939036b7c60e14*`

I would like to deploy that package to my user folder based on that same truncated package_id. But the following doesn't work:

`conan install --requires pkg/1.2.3*:9b939036b7c60e14* --deployer direct_deploy`

Despite the package_id contains the information related to settings and options, the install command still expect these to be provided.

Is there a way to deploy  `pkg/1.2.3` to user folder based solely on truncated package_id `9b939036b7c60e14*` ? Or do I need to parse the list command output and then figure out settings and options from that one?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lucabarbiero 

Thanks for your question.

The ``conan install`` command is intended to resolve dependencies, as such it cannot directly define dependencies, the ``package_id`` will be computed from the input profiles, versions, etc.

I think that you might be looking for the ``conan download`` command. That command can perfectly receive a reference based on ``package_id``, and download it. You can even use the output of ``conan list`` if you want to feed the ``conan download`` command.

From there, accessing its contents can be done with ``conan cache path pkg/version:package_id``, and then just copied. The ``deployers`` are also oriented to dependency resolution, and they operate over dependency graphs, not over individual packages, for individual packages, ``conan download`` would be better.

Please let us know if this helps.

**Comment by freihamer** [comment]
Hi @memsharded 

Yes that helps, thanks. So far I would always use the `conan install` command because it has the deployer feature, which `conan download` does not have (and not because I would necessarily care about installing package dependencies).

But indeed, using `conan dowload` and then `conan cache path` I can obtain the same, and using the package_id only. So this is a solution.

Minor points:
- Why not add a deployment feature to the `conan download` command?
- The `conan cache path` does not accept a truncated package_id, I need to get the full package_id from the output of` conan download`, and supply that in full for `conan cache path` to work

A bit of backgound:
My Conan packages contain embedded software images (motorola srecords) which I need to deploy to my system. When I create these packages with `conan create`, I would like to embed the Conan package_id in the software image itself. So that once the software is deployed to the system, by retrieving that information I will be able to know exactly what package was deployed there. But I only have 8 bytes to store this information (the payload size of a standard CAN message). That's why I can only store a truncated package_id in my software image (that's all I will be able to retrieve, one the system is in operation). Anyway all this can work with current Conan features, I just mentioned a couple points as possibile improvements

**Comment by memsharded** [comment]
> Why not add a deployment feature to the conan download command?

The deployers have more sense when they operate over a dependency graph and need to repeat the same operations over multiple packages. For 1 single package, if obtaining the path to the folder of the package is simple, then the ``deployer`` becomes  a bit overkill. I am not saying that this wouldn't be possible or that it won't be added, but that the utility is  way less than for dependency graphs

> The conan cache path does not accept a truncated package_id, I need to get the full package_id from the output of conan download, and supply that in full for conan cache path to work

Yes, that is correct. Conan only understand partial package-ids (more than partial, just patterns) in the ``list``-like commands, but most other commands require full references. The ``download`` command will print them while downloading, but if it makes sense that we extend the ``conan list --format=compact`` compact formatter to ``conan download``, let us know. For CI this wouldn't be an issue, because can use the ``--format=json`` easily, so you are talking mostly about dev ux?

**Comment by freihamer** [comment]
Indeed `--format=json` enables to easily extract a full package_id reference from list like commands. So I will just script these steps as part of an artifactory package download and "deployment". My devs will likely not run these commands directly anyway from command line. So it's ok the way it is. Thanks for explaining the rationales behind conan commands.

We can close this, thanks again!

**Comment by freihamer** [comment]
@memsharded sorry let me just ask one more thing at this point:

Is it possible to access the `package_id `from (some methods of) a Conan recipe? I though there would be a `self.package_id `attribute, but there is not?

**Comment by memsharded** [comment]
Yes, it is possible, the ``self.pref`` will contain the full package reference, ``self.pref.package_id`` will give it. It also contains the revisions, timestamp, you can ``self.pref.repr_humantime()``, etc (those might not be documented yet, please do not consider them stable, they are part of the Python API)
