### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'conan==0.24.0' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by philsuess** [conan-io/conan#1517]
Hi,
we are currently evaluating conan to use in our company. So far it's looking great and we have no trouble on self-administered Windows machines. I am now trying to install and run conan locally on a linux (Red Hat Enterprise Linux Workstation release 7.3 (Maipo)) system, as we don't have root rights there. So I tried `pip3 install conan`, which runs fine. Then executing `conan` results in the following:
```
Traceback (most recent call last):
  File "/u/s/suess/conan/bin/conan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/m/soft/python/3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/m/soft/python/3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/m/soft/python/3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/m/soft/python/3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/m/soft/python/3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/m/soft/python/3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'conan==0.24.0' distribution was not found and is required by the application
```

Here's the shebang from the conan file: `#!/m/soft/python/3.6.1/bin/python3`, and this is python3.6 in my installation. Any help would be greatly appreciated!

**Comment by memsharded** [comment]
This is weird, indeed. But it is not the first issue we see with RH, maybe these two other issues have some hints:

- https://github.com/conan-io/conan/issues/1360
- https://github.com/conan-io/conan/issues/1300

Seems that using SCL or virtualenv might help. Does this help?

**Comment by philsuess** [comment]
Thanks for the quick reply. I managed to get it running using virtualenv (using Python 2.7). However, it didn't work right away. I had to manually install two more package using pip in my virtual environment. The errors were: `pkg_resources.DistributionNotFound: backports.functools-lru-cache`, fixed by `pip install backports.functools-lru-cache` and `pkg_resources.DistributionNotFound: configparser`, fixed by `pip install configparser`.
After that, everything works!

**Comment by memsharded** [comment]
This is very weird. Both are transitive dependencies of ``pylint 1.6.5`` which is listed in the requirements.txt file, I have tried locally to install in a new virtualenv and it works, they are installed with ``pip install conan``

Can you check if there were some messages while you installed conan in the virtualenv regarding those python packages?

**Comment by philsuess** [comment]
None that I can see. I could send you the 350+ lines of bash output from my command if that helps. Should I post it here?

**Comment by memsharded** [comment]
Sure, please send them. Submit a file, or create a gist better, rather than put all of it inline. Thanks!

**Comment by philsuess** [comment]
https://gist.github.com/philsuess/4935d5b6562b547c7e6b405bd367c367

Hope this helps in figuring out what's going on.

**Comment by memsharded** [comment]
It seems from the output that it was installed correctly:

```
Installing collected packages: backports.functools-lru-cache
  Running setup.py install for backports.functools-lru-cache
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    
Successfully installed backports.functools-lru-cache
```
Something similar with configparser. However, it was complaining about ``setuptools``, like using an old version. Which python 2.7 version are you using? Overall it seems an issue with the python installation, maybe updating pip itself, or installing latest 2.7 might help.

**Comment by philsuess** [comment]
Python is 2.7.5 and pip is 1.4.1. So I guess I have some outdated versions floating around... I would be fine with closing this issue, as it seems to be a python installation issue.

**Comment by memsharded** [comment]
Yes, I agree, there is little we can do here, so closing it. Please tell any other issues you might find. Thanks!
