### ISSUE TITLE
[question] why does conan install write to the SRCDIR?

### ISSUE THREAD

**Issue by h-2** [conan-io/conan#15179]
### What is your question?

My setup is as follows:
* there is a SRCDIR that contains the source code and also `conanfile.txt`
* there is a BUILDDIR outside of the SRCDIR

I build like this:
```
cd $BUILDDIR
conan config install ${SRCDIR}/.conan # only necessary once
conan install ${SRCDIR} --output-folder . --build=missing --profile:all=RelWithDebInfo

cmake --preset conan-relwithdebinfo ${SRCDIR}

ninja -j 6
```

Now the problem is that this generates `${SRCDIR}/CMakeUserPresets.json` and if multiple different build-dirs run the above commands, I get
```
CMake Error: Could not read presets from SRCIDR: Duplicate presets
```
As a workaround, I always remove `${SRCDIR}/CMakeUserPresets.json` before calling `conan install`, but it seems strange to me, that I have to do this. However, the file seems to be required, because just deleting it, results in 

```
CMake Error: Could not read presets from SRCDIR
```

What am I doing wrong? I would prefer if the SRCDIR were not written to at all.

Thank you for your help!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @h-2 

> What am I doing wrong? I would prefer if the SRCDIR were not written to at all.

The problem is that CMake presets need to be together with the root ``CMakeLists.txt``. It cannot be put elsewhere, either the ``CMakeUserPresets.jon`` or the ``CMakePresets.json`` is written just besides the ``CMakeListst.txt`` in the source-dir, or it will not work for ``cmake --preset`` command.

Said that, if you want to disable the generation or create a different file, you can use the ``CMakeToolchain.user_presets_path`` attribute as defined in https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html. You can define your own presets and use the Conan information extending the Conan generated ones, there is a full example in https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets.html#examples-tools-cmake-toolchain-build-project-extend-presets

Alternatively, you can generate different presets for different installs without collisions, by defining ``build_folder_vars``, which can be defined in ``layout()`` as ``self.folders.build_folder_vars`` or in ``conf``.

**Comment by h-2** [comment]
> The problem is that CMake presets need to be together with the root CMakeLists.txt. It cannot be put elsewhere, either the CMakeUserPresets.jon or the CMakePresets.json is written just besides the CMakeListst.txt in the source-dir, or it will not work for cmake --preset command.

This is very strange, considering that out-of-source builds are the recommended way of building cmake projects. This is also often required by project policy. In my current project, this is acceptable, but it is definitely something that would prevent me from using Conan in other projects.

> Said that, if you want to disable the generation or create a different file, you can use the CMakeToolchain.user_presets_path attribute as defined in[...]

But then `cmake --preset ..` will stop working?

**Comment by memsharded** [comment]
> This is very strange, considering that out-of-source builds are the recommended way of building cmake projects. This is also often required by project policy. In my current project, this is acceptable, but it is definitely something that would prevent me from using Conan in other projects.

This is not something defined by Conan. It is a CMake thing. CMake forces the ``CMakeUserPresets.json`` to be located in the source dir besides the ``CMakeLists.txt``. If you don't want Conan to generate it, it is fine, you can tell Conan to not generate it, but then you will not have the presets file, and then you will not be able to use Conan auto-generated presets. You can still use Conan via CMAKE_TOOLCHAIN_FILE=.... but it will probably be a bit less convenient

> But then cmake --preset .. will stop working?

Yes, it will stop working. As said above, the preset file must be besides the ``CMakeLists.txt`` or it will be ignored by CMake. I think there is an open ticket in CMake issue tracker to request allowing arbitrary location, you might want to look for it and upvote it.

**Comment by h-2** [comment]
Thanks again for your patience with me!

I understand that this is not your responsibility, but it would have been really nice if the idiomatic way of using Modern Conan and Modern CMake would have just worked together nicely.

> I think there is an open ticket in CMake issue tracker to request allowing arbitrary location, you might want to look for it and upvote it.

I couldn't find it, and have opened a new issue:
https://gitlab.kitware.com/cmake/cmake/-/issues/25444

Feel free to add you your opinion or a thumbs-up if you feel like it.

**Comment by h-2** [comment]
> Said that, if you want to disable the generation or create a different file, you can use the CMakeToolchain.user_presets_path attribute as defined in https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html.

I am trying to deactivate the generation of the user presets file when invoking `conan install`, but I can't figure out how. I don't want to add this to the conanfile, because I don't want to forbid everyone from using it. I just need to prevent it from being created in certain environments.

Things I have tried passing to `conan install`:
* `--conf:all=tools.cmake.cmaketoolchain:user_presets_path=False`

**Comment by memsharded** [comment]
If you try to use a non existing config in Conan 2.0 it will error:
```
(conan2_36) λ conan install . -c tools.notexists=3
ERROR: [conf] 'tools.notexists' does not exist in configuration list.  Run 'conan config list' to see all the available confs.
```
You can list the available configurations with ``conan config list`` (Conan 1.X doesnt fail, but you can use it to list existing configurations)

At the moment there is no conf to disable the generation of ``CMakeUserPresets.json``, though it is considered as a possibility. At the moment it is not a big issue, if some of your users might want to use it, then leaving it and adding it to the ``.gitignore`` works quite well (as having a ``CMakeUserPresets.json`` besides to the ``CMakeLists.txt`` is the enforced CMake practice, and CMake themselves explicitly say that this file shouldn't be added to scm/git)

**Comment by h-2** [comment]
> If you try to use a non existing config in Conan 2.0 it will error:

Yes, that's true. However, part of the overall complexity of using conan is, that there are so many different places where things are "configured": the profile(s), the conan file (either python or ini), the command line, and potentially user-defined toolchain files or presets.
Some things can be set in multiple places, others cannot… it's all not exactly obvious 🤯

> At the moment there is no conf to disable the generation of CMakeUserPresets.json, though it is considered as a possibility.

Thanks for considering this! Wouldn't there maybe be a mechanism to expose all configuration options everywhere they make sense?
