### ISSUE TITLE
[bug] cannot find cmake when following tutorial

### ISSUE THREAD

**Issue by stheriault** [conan-io/conan#15178]
### Environment details

* Operating System+version:	Microsoft Windows 11 Pro
* Compiler+version: MSVC 17 2022
* Conan version: 2.0.14
* Python version: 3.10.5

### Steps to reproduce

Following these tutorial instructions:
https://docs.conan.io/2/tutorial/consuming_packages/use_tools_as_conan_packages.html

1 conan profile detect --force
2 git clone https://github.com/conan-io/examples2.git
3 cd examples2/tutorial/consuming_packages/tool_requires
4 conan install . --output-folder=build --build=missing
5 cd build
6  ./conanbuild.bat
7 cmake --version

### Logs

output of step 1:
detect_api: Found msvc 17

Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows

WARN: This profile is a guess of your environment, please check it.
WARN: The output of this command is not guaranteed to be stable and can change in future Conan versions.
WARN: Use your own profile files for stability.
Saving detected profile to C:\Users\sther\.conan2\profiles\default

---
note: step 6 produced no output

---
output of step 7:

cmake : The term 'cmake' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ cmake --version
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (cmake:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by juansblanco** [comment]
Hi @stheriault !
It looks like you are using a Powershell terminal which won't run the `conanbuild.bat` directly.
The tutorial is missing some information for using Powershell, I will fix it.

For now, you can use the conan configuration needed for using Powershell.
Try adding `--conf=tools.env.virtualenv:powershell=True` to the conan install command (step 4).
This will create the necessary files as `.ps1`.
Then you can run the `conanbuild.ps1` in step 6 so it correctly activates the environment and you will be able to find the specified CMake version.

Alternatively using another console that admits `.bat` files will work too.

Hope this helps you!

**Comment by stheriault** [comment]
Thank you so much!!! That worked

**Comment by franramirez688** [comment]
Thanks for reporting @stheriault 

Opened PR https://github.com/conan-io/docs/pull/3472 to improve the documentation.
