### ISSUE TITLE
[question] install dep to the working directory + cmake

### ISSUE THREAD

**Issue by IGORSVOLOHOVS** [conan-io/conan#15189]
### What is your question?

How to install dependencies(bin,lib,include) to the working directory on Windows? I try `conan install . --install-folder=. --build=missing --output-folder build -c tools.env.virtualenv:powershell=True ` but  --install-folder=. is not defined: `conan install: error: unrecognized arguments: --install-folder=.`

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @IGORSVOLOHOVS 

Thanks for your question.

In general, the recommendation is not to make a copy. It is not needed in most on the cases, and not only is not needed, but it can be problematic in many cases (conflicting, overwriting binaries for different configurations, losing track of dependencies versions, etc). So using packages from the Conan cache would be the recommended approach for most cases. Why do you want to make a copy?

If you still want to make a copy, the Conan 2.0 mechanism is called "deployers". You might want to have a look to this blog post: https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html

**Comment by IGORSVOLOHOVS** [comment]
@memsharded Thank you! Yes, it is what I wanted!!! In my case I use `conan install . --deployer=full_deploy --build=missing --output-folder build -c tools.env.virtualenv:powershell=True`. The [link](https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html) was realy helpful!
![image](https://github.com/conan-io/conan/assets/98398989/3dee9d58-2f26-4b32-b8c8-47bda2ee77a2)

**Comment by memsharded** [comment]
Don't forget to subscribe to the blog post, release announcements, our twitter... We typically share in those channels the new things like this, that can be interesting for users 🙂
