### ISSUE TITLE
How to use a dynamic library in dependencies when using CMakeDeps

### ISSUE THREAD

**Issue by dix75** [conan-io/conan#15193]
### What is your question?

I have created a dynamic library (vs) using conan.
Then I use this library in dependencies, in Linux everything works fine, but in Windows conan doesn't see this dependency.
If I create a static library in WIndows, everything works fine too.

Error
Library 'vs' not found in package.

I tried to add this package_info
```self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))```

I tried
```
self.cpp_info.libdirs = ["bin"] 
self.cpp_info.bindirs = ["bin"]
```
It's not helping.

First conanfile.py
```
    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["PACKAGE_BUILD"] = True
        tc.generate()
        CMakeDeps(self)
        tc.generate()

    def package_info(self):
        self.cpp_info.libs = ["vs"]
        self.cpp_info.set_property("cmake_find_mode", "both") 
        self.cpp_info.set_property("cmake_file_name", "vs") 
        self.cpp_info.set_property("cmake_target_name", "vs::vs")
        self.cpp_info.set_property("pkg_config_name", "vs") 
        self.cpp_info.names["cmake_find_package"] = "vs"
        self.cpp_info.names["cmake_find_package_multi"] = "vs"
```
Second conanfile.py
```
    def requirements(self):
        self.requires("vs/1.2.0@visys/stable")

    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["PACKAGE_BUILD"] = True
        tc.generate()
        CMakeDeps(self)
        tc.generate()

    def package_info(self):
        self.cpp_info.libs = ["vs"]
```
--- 
mingw 11.2
conan 1.62
Windows 11 (x64)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @dix75 

It seems you are using the legacy environment ``self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))``.
For new ``VirtualBuildEnv``, which is the modern and recommended one, this won't be necessary. As long as you put the binaries in the ``bin`` folder, it will work. You need to use the ``VirtualBuildEnv`` and ``VirtualRunEnv`` generators in the consumers or define the new ``[auto_use=True](tools.env.environment:auto_use=True)`` conf in the profile or global.conf


Some extra hints:

- ``self.cpp_info.names["cmake_find_package"] = "vs"`` is not recommended anymore, should be dropped, as ``cmake_find_package`` generator is legacy
- The ``set_property`` is only necessary when files and targets are different from the package name. If they are equal, you should drop them.
- The ``self.cpp_info.libs = ["vs"]`` in the second conanfile.py is incorrect, that only belongs to the first conanfile.

You can try with the ``conan new pkg/0.1 -m=cmake_lib`` template, that should work out of the box also for dynamic libraries.

**Comment by dix75** [comment]
Thanks, it works.

But if I use components, it doesn't help.
For example (Other.Package):
```    def package_info(self):
        self.cpp_info.components["flat"].libs = ["flatLib", "flatLibplugin"]
        self.cpp_info.components["flat"].includedirs = ["Flat"]
        self.cpp_info.components["flat"].resdirs = ["Flat"]
        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs.extend(["m", "pthread"])
```
What's best for me to use.

**Comment by memsharded** [comment]
That should be something else, the components are not really related to the ``VirtualXXXEnvs`` at all, so it should be something different, like missing the ``bindirs`` or something like that. We would need a fully reproducible example to be able to know what is happening.

**Comment by dix75** [comment]
[flat.zip](https://github.com/conan-io/conan/files/13527983/flat.zip)

I added the full package (archive)
- project (flat)
- data (.conan/data/flat)
- profiles (default)

I work like this
```
cd flat
make build-pkg
```

**Comment by memsharded** [comment]
Thanks for putting together the zip with the code.

Some quick feedback:

1. 
```
jsonInfo = json.loads(tools.load("package_info.json"))
    name = jsonInfo["project_name"]
    version = jsonInfo["version"]
    default_user = jsonInfo["default_user"]
    default_channel = jsonInfo["default_channel"]
```
This is not recommended. Use the ``set_name()``, ``set_version()`` methods instead


2. Instead of a custom package_info.json, better use the standard ``conandata.yml``

3. [env] is deprecated, please use ``[buildenv]`` instead
4. ``from conans`` is deprecated, please use only ``from conan``
5. Do not longer use ``os_build=Windows``, for any case when ``tool_requires`` are used, using the 2 profiles approach build/host is recommended
6. This ``/* CC=c:\\MinGW\\bin\\gcc.exe */`` is broken, it is an incorrect way to comment things in profiles, you need to comment with ``#``


With that, I am using this profile:
```
[settings]
os=Windows
arch=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
compiler.threads=posix
build_type=Release
[options]

[buildenv]
CC=C:\ws\msys64\mingw64\bin\gcc.exe
CXX=C:\ws\msys64\mingw64\bin\g++.exe
PATH=+(path)C:\ws\msys64\mingw64\bin
botan:CXXFLAGS=-Wa,-mbig-obj

[conf]
tools.env.virtualenv:auto_use=True
tools.env.environment:auto_use=True
tools.cmake.cmaketoolchain:generator=Ninja
```

Then it fails with
```
CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake
```
Because it cannot find Qt in my system, and it is not a requirement either.


In any case, using this code would probably be a bit too complicated, specially if it depends on heavy libraries like Qt. This is the reason it is much better to test things with a "minimal reproducible example" not a full fledge project. For that case, the ``conan new pkg/0.1 -m=cmake_lib`` can really make things way easier to reproduce, understand, support and fix. Like orders of magnitude faster, that is really recommended.

**Comment by dix75** [comment]
The example you suggest works fine, I wrote earlier.
Due to the fact that qt creates 2 library files, this situation happens, I will try to find another example.

**Comment by memsharded** [comment]
Hi @dix75 

Did you manage to solve the issue? Please do not hesitate to contact us if you still need help with this.
