### ISSUE TITLE
[question] How the Conan revision works

### ISSUE THREAD

**Issue by Wizradus** [conan-io/conan#15197]
### What is your question?

Hi, there.
I would like ask you for some details how works the revisions in Conan and what is real workflow.
If you have an article with more information than in [revision document](https://docs.conan.io/1/versioning/revisions.html), it might be fair enough.
Anyway I have a few questions related:
- I have some packages in local cache, which I have successfully built day before and now I got info that package [package_ID] is missing in the cache. What is verifying against Artifactory? That new recipe revision exist or new package revision exist? Both?
- When I'll be offline - Conan don't touch Artifactory, can I continue in work without any issue with my local cache? I expect that yes.
- How it works in situation, when I have installed specific revision from Artifactory to local cache and I want to build with this revision, does it won't failed after check that is new revision in Artifactory.

Thanks in advance for your time

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Wizradus 

You might take a look to https://docs.conan.io/2/tutorial/versioning/revisions.html for another docs page on revisions (they work mostly the same in 1.X and 2.0)

> I have some packages in local cache, which I have successfully built day before and now I got info that package [package_ID] is missing in the cache. What is verifying against Artifactory? That new recipe revision exist or new package revision exist? Both?

If a package binary is missing in the cache, it will look for it in the defined remotes, yes, this is the default behavior. If you don't want to check in the remotes, they can be disable with ``conan remote disable``. Conan will check for an existing ``package_id`` matching the recipe revision that you have in your cache. And for that ``package_id``, if found, it will retrieve the latest package revision.

> When I'll be offline - Conan don't touch Artifactory, can I continue in work without any issue with my local cache? I expect that yes.

yes, it is possible to work offline. As long as all the necessary packages are already installed in the cache, Conan will not try to download them from remotes

> How it works in situation, when I have installed specific revision from Artifactory to local cache and I want to build with this revision, does it won't failed after check that is new revision in Artifactory.

Sorry, I don't understand what you mean here.

**Comment by Wizradus** [comment]
Thanks for your quick response, James ( @memsharded ). Thanks also for the link, I'll look on it.
Regarding the last question...
I meant possibility to install specific revision with conan install from Artifactory, when I want to use it for build. Does it won't failed after Artifactory check, because of existing new revision?
`conan install mypackage/branch@test/dev#RREV`

**Comment by memsharded** [comment]
>  meant possibility to install specific revision with conan install from Artifactory, when I want to use it for build. Does it won't failed after Artifactory check, because of existing new revision?

Sure, you can explicitly use the recipe revision you want, using ``self.requires("pkg/version#reciperevision")``, that will force to use that revision, no matter if there are other revisions in the server.

**Comment by Wizradus** [comment]
> Sure, you can explicitly use the recipe revision you want, using self.requires("pkg/version#reciperevision"), that will force to use that revision, no matter if there are other revisions in the server.

So this mean, when I install specific revision, Conan will look for other packages in Artifactory related to this revision, right?

**Comment by memsharded** [comment]
> So this mean, when I install specific revision, Conan will look for other packages in Artifactory related to this revision, right?

It will look for binaries belonging to that specific revision, not from other revisions (unless configured in 1.X without revisions enabled). 

That is for ``self.requires("zlib/1.3#abcd")`` it will use binaries of ``zlib/1.3#abcd`` only ``zlib/1.3#abcd:package_id1`` etc. But for other dependency, not ``zlib``, of course not, that is only of the revision of zlib.

**Comment by Wizradus** [comment]
Aha. I'm probably getting the idea. I can install specific revision, but if there are any dependencies for this module, I need solve manually revisions for these dependencies.

**Comment by memsharded** [comment]
Yes, if you want to "freeze" to a specific set of dependencies revisions, the recommended approach is to use "lockfiles", see https://docs.conan.io/2/tutorial/versioning/lockfiles.html. You can also pin the revisions in every ``requires``, but that is more time consuming, because needs to be done for all dependencies.

**Comment by memsharded** [comment]
I am closing this ticket as responded, but please re-open or better, create new tickets for any further question you might have. Thanks for the feedback!
