### ISSUE TITLE
[feature] Extend .conanrc for profiles information

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#15209]
### What is your suggestion?

So we can change which default profiles, including the possibility of specifying multiple profiles, for different projects.

cc/ @maikelvdh 

Might be related to workspaces, we need to check how .conanrc and workspaces connect.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by antoinebardoz** [comment]
Any progress on this? We're still eagerly awaiting this feature.

**Comment by memsharded** [comment]
I am centralizing workspace related tickets in this one: https://github.com/conan-io/conan/issues/15992

Lets close this one and follow up there. We will start posting updates in that ticket when we are able to resume work on workspace feature.
