### ISSUE TITLE
[question] How to manage headers generated by cmake in editable mode?

### ISSUE THREAD

**Issue by tgurriet** [conan-io/conan#15201]
### What is your question?

Hello,

I'm currently working on a package where CMake generates a config header at configuration time with:
```
configure_file(
  ${CMAKE_CURRENT_SOURCE_DIR}/config/config.hpp.in
  ${CMAKE_CURRENT_BINARY_DIR}/include/config.hpp @ONLY
)
```

In order to use this package in editable mode, I need to have `self.cpp.source.includedirs` point to both the source and the build directories. Something like that:

```
self.cpp.source.includedirs = [
    "include",
    os.path.join(self.build_folder, "include"),
]
```

The `self.build_folder` is however empty when the `layout` function is called and I can't find a way to retrieve that information.

What's the recommended course of action?

Thanks in advance,
Tom

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tgurriet 

Thanks for your question.

I think this is the purpose of ``self.cpp.build.includedirs``. To represent includes that are generated at build time, not really sources, as you put above, they are generated in the CMAKE_CURRENT_BINARY_DIR (build folder)

Have you tried this approach?

**Comment by tgurriet** [comment]
That works!
The doc always uses `cpp.build` for libs and `cpp.source` for includes, but I should have expected that you guys had things covered :smile: 

Thanks

**Comment by memsharded** [comment]
> That works!
The doc always uses cpp.build for libs and cpp.source for includes, but I should have expected that you guys had things covered 😄

Thanks for the trust! 🙂 

Thats a good point, maybe adding a small example or note for generated headers would be useful, I'll do it.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3473

**Comment by tgurriet** [comment]
Doc looks much better now, thanks!
