### ISSUE TITLE
Error when creating a dependent library if the current library contains compiled libraries

### ISSUE THREAD

**Issue by dix75** [conan-io/conan#15203]
ау### Environment details

* Linux(Ubuntu 23.10 x64)
* gcc 13.2
* conan 1.62
* python 3.11.6

### Steps to reproduce

1.Create a simple library with dependencies (first)
```
For example:
    def requirements(self):
        self.requires("botan/2.19.3")
        
     def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()

        tc = CMakeDeps(self)
        tc.generate()
```
2. Create another library and use the first library in dependencies
For example:
```
    def requirements(self):
        self.requires("first/0.0.1")
```
        
3. Add to CMakeFile.txt (to create a second library) any reference to an existing compiled library
For example:
```
  set(ONVIF_CLIENT_LIB libonvifclient.a)

add_library(onvif_client STATIC IMPORTED)
set_target_properties(onvif_client PROPERTIES IMPORTED_LOCATION
  "${ONVIF_BIN_PATH}/onvif/${ONVIF_CLIENT_LIB}")

target_link_libraries(second PRIVATE
  first::first
  convif_client
)
```
 

### Logs

```
ninja: error: '/home/dix/.conan/data/second/0.0.1/visys/stable/build/6bf7e753d430bd79d80e508bd6409dc47b780f54/3dparts/bin/second/libonvifclient.a', needed by 'CMakeFiles/second_autogen_timestamp_deps', missing and no known rule to make it
second/0.0.1@visys/stable: 
second/0.0.1@visys/stable: ERROR: Package '6bf7e753d430bd79d80e508bd6409dc47b780f54' build failed

```

**Comment by memsharded** [comment]
Hi @dix75 

I am afraid that I don't have enough information to understand what is happening.
I have no idea where the ``libonvifclient.a`` comes from, and the error message is complaining exactly about that library, but this is not any of the libraries created in the ``first`` or ``second`` conan packages. Also it is not clear what you are trying to do with the ``PROPERTIES IMPORTED_LOCATION``

**Comment by dix75** [comment]
Hi [memsharded](https://github.com/memsharded)

I'm rewriting the conan recipe from CMake to CMakeTools generator
The previous recipe works fine for a long time.
Previous recipe. 
[conanfile.py.zip](https://github.com/conan-io/conan/files/13536287/conanfile.py.zip)

The problem with the current recipe, is that if I add any local library to the target_link_libraries section in CMakeLists.txt, this error occurs
Example:
```
target_link_libraries(Onvif PRIVATE
 anyonelib.so
)
```
p.s. CMakeLists.txt is the same for both recipes

**Comment by memsharded** [comment]
Some feedback about that conanfile:

- the ``conan_info`` method is useless, it is doing nothing at all. I think you have mistaken it for other method name.
- In most cases, adding ``cpp_info.libs`` with full extension like ``.dll`` is not correct, as adding them to the linker will produce linker errors
- The ``self.cpp_info.requires = ["vs::vs"]`` is not necessary if the current package doesn't define components


About what you say, ``CMakeTools`` does not exist. Maybe you meant ``CMakeDeps`` and ``CMakeToolchain`` generators?

Besides that, I am afraid that I still don't know what could be happening. It would be necessary to have a self-contained, complete reproducible case that we can build and check.

**Comment by dix75** [comment]
It's a pity

**Comment by dix75** [comment]
It's a pity

**Comment by memsharded** [comment]
Hi @dix75 

Did you find a solution? We are willing to help, but we would need more info to reproduce.
If sharing things here in public is not possible, maybe you want to send the reproducible case to info@conan.io in private?
