### ISSUE TITLE
Manually creating sha1 hash

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#1521]
Hi,

I know the `sha1` for build/shaxxx and package/shaxxxx in local cache (.conan) is created of settings + options + requires (configured by default to semver). But these can be tuple, list, set, dict... 

Are all these container values just concatenated as sting and then the sha1 over this concat string?

I see conan's python source has some functions to generate the sha1. How can I call this function from my `conanfile.py`?

**Comment by memsharded** [comment]
Hi! You can easily access it from:

```python
my_id = self.info.package_id()
```

It is not documented, because so far it hasn't been necessary, that info is usually abstracted away with the conan model. What would be your use case for explicitly managing the package ID?

**Comment by Twoflower2** [comment]
Just want to use it to get the location to copy the objects build outside Conan (In Eclipse CDT like you know) into the cache so that the `conan package` also includes these when using `conan upload` to Artifactory.

**Comment by memsharded** [comment]
But then the package manifest would be incorrect. I think it might eventually work, now we have removed the integrity check by default, but probably not a good idea. Are you aware of the ``conan package_files`` functionality, aren't you? Are you trying to have a final package that would be a merge of the ``build()`` + ``package()`` result, and some external files? Couldn't those files be generated/copied by the ``package()`` method?

**Comment by Twoflower2** [comment]
Yes using `self.info.package_id()` gives a different hash than in Conan cache package dir. How is the hash generated?

No I do not know the `conan package_files` because all dirs (bin, h, src, test_package) is included in the Conan cache using this cmd and the --path ie. `--path=bin\` gives error `conan package_files: error: unrecognized arguments: --path=bin\`

The the `conan package` does not include the `bin` dir where the builld object is created into the Conan cache although the line `self.copy(pattern="*.tlo", dst="lib", src="bin",keep_path=False)` is included in the package() method. (And using `conan package` only functions if you include the hash after this cmd.)

Thus we have to hack Conan by doing the following:
- conan export name/testing
- conan test_package    (this creates the 0ea6644d3c462f0d9fdffceca1d13609f3d075ea in the Conan cache)
- cp bin/* to 0ea6644d3c462f0d9fdffceca1d13609f3d075ea/build/bin/ of Conan cache
- conan package hello_statlib/1.0.0@name/testing 0ea6644d3c462f0d9fdffceca1d13609f3d075ea
- conan upload hello_statlib/1.0.0@name/testing -r conan-local --all

**Comment by memsharded** [comment]
``self.info.package_id()`` generates the hash from custom serialization of the settings, options and requirements (not the full requirements, but semver ones by default). The only way to reproduce it would be to copy the source code from conan codebase.

However, it shouldn't give a different hash. If you could provide a reproducible example, I'd like to have a look.

Maybe you could try a simple approach. What if your ``package()`` method just runs something like:

```python
def package(self):
    my_path = os.getenv("MY_BINARY_DIR")
    shutil.copytree(my_path, os.path.join(self.package_folder, "bin")
```
With those lines, you could be good with:
```bash
$ set MY_BINARY_DIR=/your/path/to/bin  # or export in linux
$ conan test_package
```

From today release 0.25, ``conan create`` would be the recommneded way instead of ``conan test_package``. Also, in either case, you do not need a separate export.

**Comment by Twoflower2** [comment]
I tried out your `package()` approach, but `self.package_folder` has a value of NONE.

Why does `self.copy(pattern="*.tlo", dst="bin", src="bin",keep_path=False)` which I later commented out, not copy into the `bin` into the Conan cache `package/shaxxxx`?  


```python
from conans import ConanFile
import os
from shutil import copytree

class HelloStatlibConan(ConanFile):
    name = "hello_statlib"
    version = "1.0.0"
    description = "Hello static library "
    url = "http://"
    license = "BSD"
    author = "name"
    settings = "os", "compiler", "build_type"
    exports_sources = "inc*"
    generators = "txt"
        
    def package_info(self):
        #self.cpp_info.includedirs= ["inc"]
        #self.cpp_info.libdirs = ["bin"]
        self.cpp_info.libs = ["hello_statlib"]

    def package(self):
#        self.copy(pattern="*.tlo", dst="bin", src="bin",keep_path=False)
#        self.copy(pattern="*.h", dst="inc", src="inc",keep_path=False)
        lib_path = "C:/git/conan_cdt_ns/hello_lib/bin"
        print(lib_path)
        print(self.package_folder)
        pack_path = os.path.join(self.package_folder, "bin")
        copytree(lib_path, pack_path)
```

**Comment by memsharded** [comment]
> I tried out your package() approach, but self.package_folder has a value of NONE.

Very weird, I have just checked, it works, it is even in the test suite. Could you please provide a minimum reproducible example? Which conan version are you using? If you are using some local command, you might need to specify ``--package_folder`` argument. 

> Why does self.copy(pattern="*.tlo", dst="bin", src="bin",keep_path=False) which I later commented out, not copy into the bin into the Conan cache package/shaxxxx?

I am not sure, you could have a look into the build/shaxxxx folder and check that the *.tlo files are there?

For these issues, it really helps to setup a github repo with a minimal example and exact steps to reproduce the issue. Many things can be faked, i.e. .tlo files doesn't need to be real, just some empty files.

**Comment by Twoflower2** [comment]
You already have my example repo [here](https://github.com/Twoflower2/conan_cdt), with now a slightly different conanfile.py like in the comment above. I'm still trying just get the lib to work using the "hack" in the comment above.

**Comment by Twoflower2** [comment]
Can you just give me a simple example I configure a conanfile.py and the conan cmds needed to:

put the contents of `inc` and `bin` dirs into Artifactory, if the objects are build outside Conan, thus already existing.

**Comment by memsharded** [comment]
Ok, I will create a example project and share with you.  Just a quick question, what is your initial layout? Is it good to assume that you have something like this in your local user folder:
```
myartifacts
    - inc
         - myheader.h
    - lib
         - mylibrary.lib
```

Please give me your initial layout, and I will make an example. Thanks!

**Comment by Twoflower2** [comment]
Like this https://github.com/Twoflower2/conan_cdt/blob/master/README.md

(So bin where you have lib for the hello_statlib.)

**Comment by memsharded** [comment]
Here it is: https://github.com/memsharded/simple_package_files_example

Please have a look, try to run "python run.py". I have to go now, will comment later.

**Comment by Twoflower2** [comment]
James why is there cmake in your example? That was not my request.

I just want Conan to:
Example 1: Put the contents of inc and bin local dirs into Artifactory.
Example 2: Get from Artifactory and put the contents into inc and bin local dir.

Not building, not testing, not trying to manipulate the Conancache...just a put and get. Will that be possible?

**Comment by memsharded** [comment]
I just need to build a real library, to test that everything is ok. I am using cmake to build that library. How that library is built is irrelevant for conan, you can use any build system you want for that. Please note: **conan is not building anything, the conan recipe doesnt build anything. I am building the library before using conan, to have a real library to test**. I am not manipulating the cache at all, just 2 conan commands.

The example above is just doing the basics of example 1, with the ``export`` and ``package_files``. It would be only necessary to run a ``upload`` to upload to Artifactory.

The extra step, with ``conan test_package --test-only`` is also using CMake. Again, this is mostly irrelevant, other build system could be used, and I add it only as a test and a demostration that the package I just built with ``export`` + ``package_files`` is correct. You can skip that part if you want, but it is a useful check before uploading and sharing the package in Artifactory.

Getting the artifacts will be just a ``conan install``, I would prefer to make sure we align over the first part before going to the second part.

I will update it removing the test part you don't like.

**Comment by memsharded** [comment]
Now you have it, without testing the package.

**Comment by Twoflower2** [comment]
Hi James,

I think we are almost there. I used your example and run the `run.py`

All runs fine, but my `bin` dir where the library object artefact (that was created externally using Eclipse), get deleted with `shutil.rmtree("hello_lib/bin")`. Not sure what your intention is with this. Also the `shutil.rmtree("hello_lib/build")` creates an empty `build` dir. Again not sure what is the need for this.

See image below as screenshot of Artifactory:
- The package in Artifactory also contains the `src` and `workspace` (used by Eclipse), which it should not or is not needed. How can we prevent this from being added?

![image](https://user-images.githubusercontent.com/3253973/28456008-71c1fe7a-6e01-11e7-84de-fb4fd01631ee.png)

**Comment by memsharded** [comment]
> All runs fine, but my bin dir where the library object artefact (that was created externally using Eclipse), get deleted with shutil.rmtree("hello_lib/bin"). Not sure what your intention is with this. Also the shutil.rmtree("hello_lib/build") creates an empty build dir. Again not sure what is the need for this.

Yes, I added those removals, to be able to repeat, and do a clean build of the test library. Of course they are not needed when you have the real artifacts, you don't want to remove them. But as I am generating it, I want the generation not to fail because there were previously existing folders.

I will add a ``conan package`` step to the example, to filter out the src and workspace folders.

**Comment by memsharded** [comment]
I have updated: https://github.com/memsharded/simple_package_files_example

- I have added to the conanfile.py:

```python
    def package(self):
        self.copy("*", dst="inc", src="inc",)
        self.copy("*", dst="bin", src="bin")
```

- Then, to the run.py script:
```python
os.system("cd hello_lib && conan install ..")
os.system("cd pkg && conan package .. --build_folder=../hello_lib") # This will improve with a CWD argument in future release
os.system("conan package_files Hello/0.1@user/testing --package_folder=pkg -f")
```

This is running a local "package" from the hello_lib to the local pkg folder, filtering the files you want.

Of course, this is a very simple task, so you are probably fine just doing a ``shutil.copytree`` in your script, to do a clean copy of ``inc`` and ``bin`` folders to a new folder different from the ``hello_lib`` source one. Would you prefer this approach?

**Comment by Twoflower2** [comment]
This now seems to work!

> This is running a local "package" from the hello_lib to the local pkg folder, filtering the files you want.

I do not fully understand what these lines
``` python
os.system("cd hello_lib && conan install ..")
os.system("cd pkg && conan package .. --build_folder=../hello_lib") 
````
do to produce what is does. Could you give me some insight? The key point is ` --build_folder=../hello_lib` here right?

> Of course, this is a very simple task, so you are probably fine just doing a shutil.copytree in your script, to do a clean copy of inc and bin folders to a new folder different from the hello_lib source one. Would you prefer this approach?

Could you add this as run2.py please?

**Comment by memsharded** [comment]
Great!!!

There are two things: 
- Creating packages, even local, requires some meta-information, to generate the "coaninfo.txt" with the configuration of the package, and the "conanmanifest.txt". So that is the first, line, running the ``conan install``, which will generate the "conaninfo.txt" with your configuration (compiler, OS, arch, etc).
- The second line, exactly, the key is that I am putting myself inside the ``pkg`` folder, then telling conan to create a package from the ``hello_lib`` folder which is the one containing the build (artifacts mixed with some other temporary files we dont want in the package)

I will add a run2.py example, sure :)

**Comment by memsharded** [comment]
Added run2.py

I think this is much easier to understand, a simple copy. The example in run.py is complete conan flow, which can be useful when continuously editing source code and doing incremental builds, but it is not the case, not that necessary here in our case.

**Comment by Twoflower2** [comment]
Perfect, many thanks for all your help!

I tried Example 2: `Get from Artifactory and put the contents into inc and bin local dir.` 

- To get lib to consumer I use: ` conan install .` 
- To get cunsumer artefact object to Artifactory I used your guidance again and that also works great.

I used 
``` python
from conans import ConanFile
import os

class HelloStatlibConan(ConanFile):
    name = "Hello_appl"
    version = "0.0.1"
    description = "Hello static library"
    url = "http:"
    license = "BSD"
    author = "twoflower2"
    settings = "os", "compiler", "build_type", "arch"
    requires = "Hello_lib/0.0.1@twoflower2/testing"

    def imports(self):
      self.copy("*.tlo", dst="lib", src="bin") # From bin to lib
      self.copy("*.h", dst="inc", src="inc") # From inc to inc
      
    def package_info(self):
        self.cpp_info.includedirs = ["inc"] # Ordered list of include paths
        self.cpp_info.libdirs = ["lib"] # Directories where libraries can be found
        #self.cpp_info.libs = ["hello_stalib"] # The libs to link against
        #self.cpp_info.bindirs = ["bin"]  # Directories where executables and shared libs can be found
```

Is my method for Example 2 ok or is there a more elegant method?

**Comment by memsharded** [comment]
You are welcome :)

Lets go for example 2. So you want to create another package "Hello_app", or you just want to create your final application, but that is not really a package? As in your recipe you dont have sources, build(), I think it is only a consuming application. 

In that case, you can much simplify your recipe:

```python
class HelloStatlibConan(ConanFile):
    requires = "Hello_lib/0.0.1@twoflower2/testing"

    def imports(self):
        self.copy("*.tlo", dst="lib", src="bin") # From bin to lib
        self.copy("*.h", dst="inc", src="inc") # From inc to inc
```
This should work the same, for a ``conan install``. It doesn't require name, version, or a ``package_info()`` method.
If you try that, you get a local copy in user folder, of what you want, right? 
If you are having more dependencies, you might want to use the ``folders`` argument in ``self.copy``, so files from different dependencies use their own folder. But that can wait I guess, until you have the basics working.

**Comment by Twoflower2** [comment]
> Lets go for example 2. So you want to create another package "Hello_app", or you just want to create your final application, but that is not really a package? As in your recipe you dont have sources, build(), I think it is only a consuming application.

Get from Artifactory and put the contents into inc and bin local dir. Do a build outside Conan (using Eclipse). Then Put the contents of bin local dir into Artifactory.

> If you try that, you get a local copy in user folder, of what you want, right?

Yes, correct.

**Comment by Twoflower2** [comment]
Let me add an example 3: A consumer appl. consumes two libs, appl. build outside Conan, then Conan upload to Artifactory.

**Location in the Conan cache:**

## Lib1 package dir:
```
├───shaxxxxx1
│   └───bin
│   └───inc
```

## Lib2 package dir:
```
├───shaxxxxx2
│   └───bin
│   └───inc
```

Extract of pythonfile.py for the consumer appl.:

``` python

    requires = "Lib1/1.2.4@twoflower2/testing" , "Lib2/1.5.1@twoflower2/testing"

    def imports(self):
      #Copy from Lib1
      self.copy("*", dst="impl/lib/Lib1/inc", src="inc") 
      self.copy("*", dst="impl/lib/Lib1/bin", src="bin") 
   
      #Copy from Lib2
      self.copy("*", dst="impl/lib/Lib2/inc", src="inc") 
      self.copy("*", dst="impl/lib/Lib2/bin", src="bin")
```

I then use `conan install .` to get these requirements into the project dir structure, but 
- it copies the Lib1 inc & bin from cache into project's dir Lib1 and Lib2
- and it copies the Lib2 inc & bin from cache into project's dir Lib1 and Lib2

How can I tell Conan that a `self.copy()` is only meant for just Lib1 or just Lib2?
