### ISSUE TITLE
[question] how to set CMAKE variable in profile

### ISSUE THREAD

**Issue by h-2** [conan-io/conan#15218]
### What is your question?

I want to define a CMakeVariable from within my `conanfile.txt`, but I seem to be too stupid to do this.

Things I have tried:

```
# has no effect:
[buildenv]
FOO=BAR

# These produce errors:
[conf]
tools.cmake.cmaketoolchain:variables += {"FOO":"BAR"}
tools.cmake.cmaketoolchain:variables["FOO"]="BAR"
```

What am I doing wrong?

Ps.: sorry for asking so many questions, but the documentation is currently not really helpful :|

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @h-2 

We have a explicit example in the docs for this use case: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/inject_cmake_variables.html

The injection is done via injection of user toolchains.

As a hint, you can use ``conan config list`` can give you all the defined configurations


> Ps.: sorry for asking so many questions, but the documentation is currently not really helpful :|

Don't worry, don't hesitate to ask about any questions or issues you might have. Documentation is always a work in progress and challenging to cover everything.

**Comment by h-2** [comment]
> The injection is done via injection of user toolchains.

I already read that page, but it seems like you need to include a file with the variables? This is very inconvenient, because I often only need to set one option depending on arch or OS or a combination thereof. I would need to ship a lot of files that just contain one line.

**Comment by memsharded** [comment]
> I already read that page, but it seems like you need to include a file with the variables? This is very inconvenient, because I often only need to set one option depending on arch or OS or a combination thereof. I would need to ship a lot of files that just contain one line.

You can perfectly ship just one user-toolchain file, and add CMake conditionals on the os and architecture on that file to behave it like you want.

We don't plan to add CMake variables to the profiles directly, because setting these variables can be tricky, setting different values, escaping values, different types, cache/noncache. Not to say the capability of doing checks, conditionals, etc. You get all that flexibility easily with CMake user-toolchain files, inventing a new syntax in profiles just to translate it to a CMake file just adds an inferior and more fragile level of indirection that has to be documented, learned by users, etc. We know it, we had this in Conan 1.

**Comment by h-2** [comment]
> You can perfectly ship just one user-toolchain file, and add CMake conditionals on the os and architecture on that file to behave it like you want.

> We don't plan to add CMake variables to the profiles directly, because setting these variables can be tricky.

I understand why you want to avoid this, but not having this feature really makes other workflows difficult.
If I create an extra UserToolchain.cmake, with lots of logic in it, I again have multiple places that I need to keep up to date when changing things. I had hoped to isolate all platform specific parameters into profiles, so that I don't have to duplicate logic 😢

**Comment by memsharded** [comment]
> I understand why you want to avoid this, but not having this feature really makes other workflows difficult.

But at the end of the day, it shouldn't really be an issue. Lets say that you manage 20 profiles. Then in the folder you use as ``conan config install`` origin you have:
```
windows64_abc.txt
windows64_abc.cmake
linuxarmv8_xyz.txt
linuxarmv6_xyz.cmake
...
```
And each profile .txt file will define the ``conf`` to include its respective .cmake user toolchain file.
This is clear, easy to maintain, with a clear separation of concerns and responsibilities, allowing full CMake syntax and power to define the variables with the level of detail you want (cache, variable types, appending, etc). It is just a matter of having 1 file or 2 files, and the rationale is that having definition of cmake variables in an ini-like file like the profile is a bad approach, it is better to have one file for each.

And for the users, both developers and CI, it is fully transparent, still only ``conan install ... -pr=profile_name.txt``. It would be nice to understand why this would make any workflow difficult.

**Comment by h-2** [comment]
>  It would be nice to understand why this would make any workflow difficult.

Well, typically, you would have some things that are set for all Linux and some things that are set for all arm. And some things that are set only for one combination. Either I duplicate the code in multiple toolchain files or I add a lot of logic to a single file.

In a profile, I can use `{% if detect_api.detect_os() == 'Linux' %}` or similar to assemble the options without exponential explosion.

But in the end, I understand that you need to consider the complexity of the conan implementation, as well! Thanks for taking the time to explain!

**Comment by memsharded** [comment]
> But in the end, I understand that you need to consider the complexity of the conan implementation, as well! Thanks for taking the time to explain!

Actually the implementation matters but not as much as other parts. It is typically the documentation, support and maintenance the things that really impact us. A feature like this will inevitably derive in a bunch of following feature requests to be able to define variables in different ways, cache/non-cache, etc, plus the inevitable bugs, then every evolution/change brings a new risk of breaking already existing users of that syntax... a rabbit hole we have gone too many times in the past and we try to avoid. Thanks very much for understanding! 🙂
