### ISSUE TITLE
[question] unable to connect to conancenter, EOF violation

### ISSUE THREAD

**Issue by WouterWolfslag** [conan-io/conan#15224]
### What is your question?

Since earlier today, I am unable to connect to conancenter, with the following error message:

> ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

This seems similar to #9695, but with a slightly different error and on **conan 2.0.4**

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by DDoSolitary** [comment]
I'm getting this as well since several minutes ago.
```
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ProtocolError('Connection aborted.', OSError(0, 'Error')))
```
It seems there's something wrong with the server. Even curl can't reach it.
```
$ curl -iv https://center.conan.io/
*   Trying 34.107.244.196...
* TCP_NODELAY set
* Connected to center.conan.io (34.107.244.196) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to center.conan.io:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to center.conan.io:443 
```

**Comment by jcar87** [comment]
Thanks for reporting - we are currently investigating

**Comment by Robort-wang** [comment]
same here

**Comment by jcar87** [comment]
The team has identified the issue and this should now be resolved.

We will continue monitoring the performance of the service.

Please let us know if anything isn't working as expected - apologies for the inconvenience.

**Comment by WouterWolfslag** [comment]
All fixed. Thank you

**Comment by jcar87** [comment]
closing this as resolved, but if there are any further issues please let us know! Thanks for using Conan! :)
