### ISSUE TITLE
[question] conan install with lockfile and -u installs newer revision?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#15227]
### What is your question?

Hi,
we are using Conan 1.61 and we are using lockfiles for installing frozen dependencies.
We are calling conan install -u -r <virtual Artifactory remote> -l <lockfile>.

We have to use -u since we faced errors when all or some of the dependencies that we want to install are available in a different revision (or was it version?) in the local Conan package cache.

But now I think that in case there are newer revisions available of the dependencies in the lockfile they are taken automatically.

If that is true then the usage of the lockfile is no more guaranteeing a completely frozen dependency graph, only frozen versions but not revisions.

Or is my understanding wrong here? If so please explain where my misunderstanding is.

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

Thanks for your question

> If that is true then the usage of the lockfile is no more guaranteeing a completely frozen dependency graph, only frozen versions but not revisions.

Yes, the lockfiles should lock down to the revisions too. 

> Or is my understanding wrong here? If so please explain where my misunderstanding is.

Basically, using lockfiles and ``--update`` together shouldn't have any effect for locked dependencies, because locked ones should resolve to whatever the lock says, not to the latest or newer as the update would want. The only scenarios that it could make sense would be for non-locked dependencies, things like partial resolution (in Conan 2.0 it is explicit with --lockfile-partial)

**Comment by MTomBosch** [comment]
@memsharded I believe I found the assumed bug. How to reproduce:
- Run a conan install with a lock file
- Now manually change in the lock file a revision (not the version, channel or user) of a previously installed Conan package
- Run conan install again with the changed lock file
- The file metadata.json in the package folder is unchanged and still points to the previously installed package revision. Also in the logs I cannot see any sign of package download.

**Comment by memsharded** [comment]
I have implemented those steps in the following test, it seems to be working fine:
```python
def test_version_ranges_revisions_update():
    # https://github.com/conan-io/conan/issues/7333
    client = TestClient(default_server_user=True)
    client.run("config set general.revisions_enabled=True")
    client.save({"conanfile.py": GenConanfile()})
    client.run("create . pkga/0.1@")
    assert "pkga/0.1: Exported revision: f3367e0e7d170aa12abccb175fee5f97" in client.out
    client.run("upload * --all --confirm")

    client2 = TestClient(servers=client.servers, users=client.users)
    client2.run("config set general.revisions_enabled=True")
    client2.run("lock create --reference=pkga/0.1@")
    lock = client2.load("conan.lock")
    assert "pkga/0.1#f3367e0e7d170aa12abccb175fee5f97" in lock

    client.save({"conanfile.py": GenConanfile("pkga", "0.1")})  # change revision
    client.run("create .")

    assert "pkga/0.1: Exported revision: bf46dbc8769aa3f6e3aab6fcc5d7c1df" in client.out
    client.run("upload * --all --confirm")

    lock2 = lock.replace("f3367e0e7d170aa12abccb175fee5f97", "bf46dbc8769aa3f6e3aab6fcc5d7c1df")
    lock2 = lock2.replace('"prev": "83c38d3b4e5f1b8450434436eec31b00",', "")
    save(os.path.join(client2.current_folder, "conan.lock"), lock2)
    client2.run("install pkga/0.1@ --update --lockfile=conan.lock")
    print(client2.out)
    assert "pkga/0.1: Downloaded recipe revision bf46dbc8769aa3f6e3aab6fcc5d7c1df" in client2.out
```
It downloads the new recipe revision

**Comment by MTomBosch** [comment]
Hi @memsharded
I have done also some testing on my side and I could reproduce a bug/problem. How to reproduce:
- (I don't know if that plays a role) Configure a Conan download cache.
- In Artifactory there are multiple revisions of the same (same version, user, channel and recipe revision) build requirements
- I now do a conan install with a custom lockfile that contains the newest revision of the build requirement
- I now change in this lock file the revision of that build requirement to an older revision and keep the local package cache as it is
- Now I run a conan install with that new lock file. Result is that the local package is not changed at all and there is also no warning or anything else mentioned on the console. It only says that the build requirement with that version is already in the cache.
      - Interestingly: If I use the -u option during the Conan install I get this warning:  `WARN: Current package is newer than remote upstream one` which is a little bit confusing since in the real upstream (=Artifactory repo) there is no newer revision but I guess here upstream means the lockfile.

The same buggy behaviour is not happening if first the lock file with the older revision is used and then afterwards the lockfile with the newer revision of the build requirement. Then I get this warning message: `WARN: Current package is older than remote upstream one`

**Comment by memsharded** [comment]
I am extending the tests to include:

- The download cache
- The "downgrade" to an older revision
- To test also ``tool-requires`` instead of regular requires

```python
class TestRevisionsUpdates:
    def test_revisions_update(self):
        client = TestClient(default_server_user=True)
        client.run("config set general.revisions_enabled=True")
        client.save({"conanfile.py": GenConanfile()})
        client.run("create . pkga/0.1@")
        assert "pkga/0.1: Exported revision: f3367e0e7d170aa12abccb175fee5f97" in client.out
        client.run("upload * --all --confirm")

        client2 = TestClient(servers=client.servers, users=client.users)
        client2.run("config set general.revisions_enabled=True")
        cache_folder = temp_folder()
        client2.run('config set storage.download_cache="%s"' % cache_folder)
        client2.run("lock create --reference=pkga/0.1@")
        lock = client2.load("conan.lock")
        assert "pkga/0.1#f3367e0e7d170aa12abccb175fee5f97" in lock

        client.save({"conanfile.py": GenConanfile("pkga", "0.1")})  # change revision
        client.run("create .")

        assert "pkga/0.1: Exported revision: bf46dbc8769aa3f6e3aab6fcc5d7c1df" in client.out
        client.run("upload * --all --confirm")

        lock2 = lock.replace("f3367e0e7d170aa12abccb175fee5f97", "bf46dbc8769aa3f6e3aab6fcc5d7c1df")
        lock2 = lock2.replace('"prev": "83c38d3b4e5f1b8450434436eec31b00",', "")
        save(os.path.join(client2.current_folder, "conan.lock"), lock2)
        client2.run("install pkga/0.1@ --update --lockfile=conan.lock")
        print(client2.out)
        assert "pkga/0.1: Downloaded recipe revision bf46dbc8769aa3f6e3aab6fcc5d7c1df" in client2.out

    def test_revisions_downgrade(self):
        client = TestClient(default_server_user=True)
        client.run("config set general.revisions_enabled=True")
        client.save({"conanfile.py": GenConanfile()})
        client.run("create . pkga/0.1@")
        assert "pkga/0.1: Exported revision: f3367e0e7d170aa12abccb175fee5f97" in client.out
        client.run("upload * --all --confirm")
        client.save({"conanfile.py": GenConanfile("pkga", "0.1")})  # change revision
        client.run("create .")
        assert "pkga/0.1: Exported revision: bf46dbc8769aa3f6e3aab6fcc5d7c1df" in client.out
        client.run("upload * --all --confirm")

        client2 = TestClient(servers=client.servers, users=client.users)
        client2.run("config set general.revisions_enabled=True")
        cache_folder = temp_folder()
        client2.run('config set storage.download_cache="%s"' % cache_folder)
        client2.run("lock create --reference=pkga/0.1@")
        lock = client2.load("conan.lock")
        assert "pkga/0.1#bf46dbc8769aa3f6e3aab6fcc5d7c1df" in lock

        lock2 = lock.replace("bf46dbc8769aa3f6e3aab6fcc5d7c1df", "f3367e0e7d170aa12abccb175fee5f97")
        lock2 = lock2.replace('"prev": "2dd219188a9fe683b58a936cd5bee67d",', "")
        save(os.path.join(client2.current_folder, "conan.lock"), lock2)
        client2.run("install pkga/0.1@ --update --lockfile=conan.lock")
        print(client2.out)
        assert "pkga/0.1: Downloaded recipe revision f3367e0e7d170aa12abccb175fee5f97" in client2.out

    def test_revisions_tool_require_downgrade(self):
        client = TestClient(default_server_user=True)
        client.run("config set general.revisions_enabled=True")
        client.save({"conanfile.py": GenConanfile()})
        client.run("create . pkga/0.1@")
        assert "pkga/0.1: Exported revision: f3367e0e7d170aa12abccb175fee5f97" in client.out
        client.run("upload * --all --confirm")
        client.save({"conanfile.py": GenConanfile("pkga", "0.1")})  # change revision
        client.run("create .")
        assert "pkga/0.1: Exported revision: bf46dbc8769aa3f6e3aab6fcc5d7c1df" in client.out
        client.run("upload * --all --confirm")

        client2 = TestClient(servers=client.servers, users=client.users)
        client2.run("config set general.revisions_enabled=True")
        cache_folder = temp_folder()
        client2.run('config set storage.download_cache="%s"' % cache_folder)
        client2.save({"conanfile.txt": "[tool_requires]\npkga/0.1"})
        client2.run("lock create conanfile.txt")
        lock = client2.load("conan.lock")
        assert "pkga/0.1#bf46dbc8769aa3f6e3aab6fcc5d7c1df" in lock

        lock2 = lock.replace("bf46dbc8769aa3f6e3aab6fcc5d7c1df", "f3367e0e7d170aa12abccb175fee5f97")
        lock2 = lock2.replace('"prev": "2dd219188a9fe683b58a936cd5bee67d",', "")
        save(os.path.join(client2.current_folder, "conan.lock"), lock2)
        client2.run("install pkga/0.1@ --update --lockfile=conan.lock")
        print(client2.out)
        assert "pkga/0.1: Downloaded recipe revision f3367e0e7d170aa12abccb175fee5f97" in client2.out
```

I am afraid that I can't still reproduce

**Comment by MTomBosch** [comment]
Hmm. I am using Conan 1.61.0. Which version did you run the test on?

**Comment by memsharded** [comment]
`develop` branch, would be 1.62, but I think nothing has changed related lockfiles or updates between 1.61 and 1.62

**Comment by MTomBosch** [comment]
I am not sure if this is the problem but the file conan.lock that I manually edited on my system was overwritten by the client so I called the custom lock file differently (dep_conan.lock) to not get this effect.

**Comment by MTomBosch** [comment]
I have to correct my above statement:

> The same buggy behaviour is not happening if first the lock file with the older revision is used and then afterwards the lockfile with the newer revision of the build requirement. Then I get this warning message: WARN: Current package is older than remote upstream one

The upgrade to the specified revision in the lockfile only works if I use the -u cli arg. Without it I get no warning and also no upgrade to the specified revision.

What is interesting is that the conan.lock that is created contains the updated revision but in the local package cache it is not updated.

How did I know the package was not downloaded/updated? By looking at the console output and also looking at the metadata.json file in the local package cache that was still pointing to the old revision.

**Comment by MTomBosch** [comment]
A identified a difference when comparing my local setup to your test: I am not installing a package by using a reference but I am installing the deps of a package using a recipe where one of the tool requirements is part of the lock file.

But even if I use just a package reference (like in your test above) and no recipe I can reproduce the behaviour on my machine :(

**Comment by MTomBosch** [comment]
I think I figured out sth.
I created a testlockfile package and testlockfileconsumer package. Then I created a lockfile based on the testlockfileconsumer. The lockfile then looks like this:

```
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "testlockfileconsumer/1.0.0",
    "options": "",
    "build_requires": [
     "1"
    ],
    "path": "conanfile_consumer.py",
    "context": "host"
   },
   "1": {
    "ref": "testlockfile/1.0.0#e48a43a1bf0b4c32b4970643c6260840",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "prev": "3d3fd2a48e1ac875628ad703bc24a227",
    "context": "host"
   }
  },
  "revisions_enabled": true
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++\ncompiler.version=9\nos=Linux\nos_build=Linux\n[options]\n[build_requires]\n[env]\n"
}
```
With this lockfile I did not get any warning and all was working like you explained in your above tests. Then I compared this lockfile with mine and I found one difference: the context is different. In above lockfile the context for the testlockfile is "host" whereas in my lockfile it is "build". 
And once I manually changed the context from "host" to "build" I got the warning message and the mentioned behaviour.

**Comment by memsharded** [comment]
That difference would be explaining by the usage of the 2 profiles (which is the recommended), or using only 1. The "build" context appears when the build profile (or any build settings like ``-s:b ...`` is used).

I have tried updating the last test, which I think is the closest so far to your use case to:
```python
    def test_revisions_tool_require_downgrade(self):
        client = TestClient(default_server_user=True)
        client.run("config set general.revisions_enabled=True")
        client.save({"conanfile.py": GenConanfile()})
        client.run("create . pkga/0.1@")
        assert "pkga/0.1: Exported revision: f3367e0e7d170aa12abccb175fee5f97" in client.out
        client.run("upload * --all --confirm")
        client.save({"conanfile.py": GenConanfile("pkga", "0.1")})  # change revision
        client.run("create .")
        assert "pkga/0.1: Exported revision: bf46dbc8769aa3f6e3aab6fcc5d7c1df" in client.out
        client.run("upload * --all --confirm")

        client2 = TestClient(servers=client.servers, users=client.users)
        client2.run("config set general.revisions_enabled=True")
        cache_folder = temp_folder()
        client2.run('config set storage.download_cache="%s"' % cache_folder)
        client2.save({"conanfile.txt": "[tool_requires]\npkga/0.1"})
        client2.run("lock create conanfile.txt -s:b os=Windows")
        lock = client2.load("conan.lock")
        assert "pkga/0.1#bf46dbc8769aa3f6e3aab6fcc5d7c1df" in lock

        lock2 = lock.replace("bf46dbc8769aa3f6e3aab6fcc5d7c1df", "f3367e0e7d170aa12abccb175fee5f97")
        lock2 = lock2.replace('"prev": "2dd219188a9fe683b58a936cd5bee67d",', "")
        save(os.path.join(client2.current_folder, "conan.lock"), lock2)
        client2.run("install pkga/0.1@ --update --lockfile=conan.lock")
        print(client2.out)
        assert "pkga/0.1: Downloaded recipe revision f3367e0e7d170aa12abccb175fee5f97" in client2.out
```
And now I can see that the context is "build", but test is still passing. I wouldn't recommend to change only the context on the lockfile, because the lockfile should capture the 2 profiles, you will see that you only have 1 profile "host" in the lockfile, and it would be undefined behavior to change only the context, but not providing the 2 profiles.

**Comment by MTomBosch** [comment]
I know this was a hack I just wanted to see if this makes a difference. In my real lockfile we have two profiles defined. 

I now created a complete testsetup in a scripted way. In the attached file please run the test_setup.sh to create and upload two package revisions.

Afterwards please run the test_install_older_revision.sh to try to overwrite an existing revision of a package with an older revision during a conan install.

The opposite (update the current revision with a newer one) is tested with the other sh script.

I hope this allows to reproduce the problem on your side.

[testlockfile.zip](https://github.com/conan-io/conan/files/13646040/testlockfile.zip)

**Comment by memsharded** [comment]
Thanks for putting the repro case together.
It explains some things.
You are not generating new **recipe revisions**, you are generating directly new **package revisions**, without changing the recipe revision at all, because this is done directly via ``conan export-pkg``.

Package revisions are challenging, and they have been mostly dropped in Conan 2.0, which consider the existence of multiple package revisions for the same recipe-revision+package-id a process error. Lockfiles in Conan 2.0 do not lock package revisions either by default, as lockfiles are intended to lock and track changes in source origins (recipes+source code), and package-revisions do not form part of the ``package_ids`` either. They are there to be able to detect and track process/model errors, but nothing more.

We could try to keep investigating why it is failing, but Conan 1.X is no longer fixing this kind of bugs for things that have been removed in 2.0, so I'd recommend instead to try to follow a process that is more aligned and ready with Conan 2.0. In this case it would be relatively simple, if we are packaging a different thing (different "content"), then it shouldn't be a new package revision, it should be a new version, or at the very least, have a reflect in the ``conanfile.py`` or ``conandata.yml`` so it gets a new recipe revision. That should solve the issue now and make things more ready for Conan 2.0

**Comment by MTomBosch** [comment]
At least you could reproduce it now I assume ;)

Thanks for explaining why you won't fix it for Conan 1.x. In case we would find someone that could contribute a fix would you then review/merge and release a new version or we should not waste this effort?

Regarding the term "content". In our case the content is different because different dependencies have been statically linked into the created binaries. But nothing in the source code. But the change of the dependencies has not lead to a change of the actual package id (likely due to our default package id mode being used) like you proposed to work around this problem.

So I see only the chance to use a different package id mode to resolve this problem or to keep using our current workaround (check for warning messages in a conan install command, then removing the packages where we got a warning and redoing the conan install).

**Comment by memsharded** [comment]
> Thanks for explaining why you won't fix it for Conan 1.x. In case we would find someone that could contribute a fix would you then review/merge and release a new version or we should not waste this effort?

Conan 1.X lockfiles are quite challenging, complicated and fragile. It is likely that potential fixes could have a relatively high risk of breaking things for other users, if there is some chance that this happens, it will not be considered, at this point existing bugs are more tolerable than breaking existing users in 1.X. This complexity of lockfiles was one of the important reasons that pushed towards a necessarily breaking 2.0.

> Regarding the term "content". In our case the content is different because different dependencies have been statically linked into the created binaries. But nothing in the source code. But the change of the dependencies has not lead to a change of the actual package id (likely due to our default package id mode being used) like you proposed to work around this problem.

yes, exactly, this is what I meant, this ``package_id`` not being modified is a model error. If there is an existing ``package_id`` for a given ``recipe-revision``, the binary should never be built again against new dependencies, and if it is built, it should result in the same binary, because the ``package_id`` information should guarantee that (so it shouldn't be built). If that is not the case, then the package-id-modes or something else should be changed, so a new ``package_id`` results when the dependencies change.

> So I see only the chance to use a different package id mode to resolve this problem or to keep using our current workaround (check for warning messages in a conan install command, then removing the packages where we got a warning and redoing the conan install).

Sounds it is probably reasonable at this point, and try to put those efforts towards the upgrade instead.

**Comment by MTomBosch** [comment]
At least you could reproduce it now I assume ;)

Thanks for explaining why you won't fix it for Conan 1.x. In case we would find someone that could contribute a fix would you then review/merge and release a new version or we should not waste this effort?

Regarding the term "content". In our case the content is different because different dependencies have been statically linked into the created binaries. But nothing in the source code. But the change of the dependencies has not lead to a change of the actual package id (likely due to our default package id mode being used) like you proposed to work around this problem.

So I see only the chance to use a different package id mode to resolve this problem or to keep using our current workaround (check for warning messages in a conan install command, then removing the packages where we got a warning and redoing the conan install).

**Comment by memsharded** [comment]
Hi @MTomBosch 

It seems Github did something weird, and your comment is posted twice. Did you see https://github.com/conan-io/conan/issues/15227#issuecomment-1854173471 my comment too? Because I think I have lost some Github notifications lately too

**Comment by MTomBosch** [comment]
I saw it, thank you.

I will close this issue now.
