### ISSUE TITLE
[question] export and upload Conan recipe

### ISSUE THREAD

**Issue by iaavo** [conan-io/conan#15228]
### What is your question?

So I would like to have a workflow like
```bash
conan export .
conan upload . -r my-remote
```
to make it work inside the CI without requiring knowledge about the name and version defined in the recipe. However, the conan upload command only accepts references and not a conanfile.py. My next attempt was to create a lockfile from the export command, but the upload command does not accept lockfiles either.

Then I found the documentation at https://docs.conan.io/2.0/examples/commands/pkglists.html#building-and-uploading-packages which states that you can use the following:
```bash
conan create . --format=json > create.json
conan list --graph=create.json --graph-binaries=build --format=json > pkglist.json
conan upload --list=pkglist.json -r=myremote -c
```
This is exactly what I want. However, if I use `conan export` instead of `conan create`, the workflow does not work.

Can this use case be achieved with basic Conan commands?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @iaavo - thanks for asking this question.

If you have the `jq` installed, you could try something like this:

```
conan export .  --format=json | jq '.reference' | xargs conan upload -r my-remote
```

This will use the `jq` tool to retrieve the exported reference, and `| xargs` will forward the argument to `conan upload`. 

Let me know if this works for you!

**Comment by jcar87** [comment]
Alternatively if you still need to keep separate commands:

```
conan export . --format=json > exported.json
conan upload $(jq -r '.reference' exported.json) -r my_remote
```

**Comment by iaavo** [comment]
Thanks for the reply! This does indeed help in my specific case and I can directly use your code snippet. Although I was hoping to make it work with basic Conan commands.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/15266, for next 2.0.15

``conan export ... --format=pkglist`` will create the necessary package list json file that can be fed to ``conan upload --list=...``
