### ISSUE TITLE
[question] [conan 2.0] How to get the path of the binary folder in local cache

### ISSUE THREAD

**Issue by afri-bit** [conan-io/conan#15238]
### What is your question?

I would like to know how to find a specific binary folder from a specific package using standard CLI, that conan2 already provides. I am aware that there is `cache.sqlite3` stored under the `p` folder inside the conan cache folder, but before accessing this local database, is there any simple method to get to the binary folder. Somehow every folder name is encoded using hash.

Is there any easy way to understand the folder pattern?

Thanks a lot in advance :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @afri-bit 

Thanks for your question.

I am not sure what do you mean. Are you looking for the ``conan cache path pkg/version:package_id`` command? That will give you the path in the cache for a given package binary. You can explore your packages in the cache with ``conan list pkg/version:*`` for example too.

Indeed the cache folders are hashes, that is the only way we can have short still unique paths. Exploring the cache manually is not recommended, this is the reason the ``conan cache path`` command is very convenient. Also most Conan commands like ``conan install`` or ``conan create`` will print relevant paths in the output.

**Comment by afri-bit** [comment]
Hi  @memsharded,

Thanks for the quick reply.

`conan cache path pkg/version:package_id` I guess this is the way to go. Somehow I missed it :)

Thanks again, it really helps a lot :)

FYI: I am working to extend my VS code extension (https://marketplace.visualstudio.com/items?itemName=afri-bit.vsconan) with conan2. I try to rely on the conan CLI first as single source of truth, even tho I know I could easily access the local database that is created during the initialization.

**Comment by afri-bit** [comment]
I think we can close this issue :)

**Comment by memsharded** [comment]
> Thanks again, it really helps a lot :)

Thanks, happy to help! Don't hesitate to open new tickets for further questions.

**Comment by hoyhoy** [comment]
Just ran into this as well.  `cache path` only gives you the recipe / export directory.  How do I display the binary directory?

```
$ conan cache path  openssl-fips/3.0.8
/Users/hoyhoy/.conan2/p/opens46a5251c3254d/e
```

But there's also:

```
/Users/hoyhoy/.conan2/p/b/openseabeb3041c5ab/b
```

Shouldn't `cache path` accept `--source`, `--build`, `--temp`, and `--download` like `cache remove`?

**Comment by afri-bit** [comment]
Hi @hoyhoy 

Maybe I can help here... 
@memsharded correct me if I am wrong :)

In order to get the binary folder you need to know the package id first. To get the package id use the command `conan list <package>/<version>:*`. There you can get list of the variants of binary including the hash id.
After you get the package id, you can use the package id to retrieve the binary path -> `conan path <package>/<version>:<package_id>` 

The `source`, `build`, `export_source` options are only available in the recipe level, not binary level.
`conan path --folder export_source <package>/<version>`

**Comment by memsharded** [comment]
Thanks for the response @afri-bit, you are correct, just minor nitpick, the command is ``conan cache path``, not ``conan path``. So something like ``conan cache path zlib/1.3:7bfde258ff4f62f75668d0896dbddedaa7480a0f`` will give the package folder of that specific binary for zlib/1.3.

@hoyhoy It is generally better to open new tickets for new questions, as closed tickets comments can pass unnoticed more easily

**Comment by afri-bit** [comment]
Thanks for the correction :) Indeed `conan cache path` it is :)
`conan path` doesn't exist

**Comment by daydream123** [comment]
I also need to get bin path of package, some package have one or more execuable files in bin folder, and I need to exuecte them during cmake configure or build.
In my preview cmake project, In FindXXX.cmake, I set IMPORTED_LOCATION properity with bin file, then I can read IMPORTED_LOCATION to get bin filepath.
How I can get the bin filepath in coann 2.0?

**Comment by memsharded** [comment]
@daydream123 this is a closed issue, and the response was that ``conan cache path`` can give the path in the cache to the packages.

It seems yours is a different question, so it is better to create a new ticket, but please make sure to provide more complete details. If you are asking about a ``conanfile.py`` recipe, you can get the path to the dependencies bindirs via ``self.dependencies``, but in general it won't be necessary, as Conan already manage to inject the dependencies ``bindirs`` into the PATH environment variable automatically, so consumers of it via ``tool_requires`` can already use it without having to do anything at all. But it would be necessary that you provide a more complete description, like your ``conanfile`` for the package containing the binary, the conanfile and the CMakeLists of the package using that binary (via ``tool_requires``).
