### ISSUE TITLE
[question] Create Package from Sources with multiple profiles

### ISSUE THREAD

**Issue by aed2fe** [conan-io/conan#15232]
### What is your question?

In our CI/CD pipeline I'm creating conan packages, using `conan create .`, for which external sources are required. These sources are fetched via the source() method. Furthermore does these packages contain up to 6 profiles for which they should be created. 

At the moment for every profile the sources are getting downloaded newly. But the sources are always the same and they are quite huge (> 1GB). So it take some time until they are available and unzipped. In conan1 I could use `--keep-sources` but this is quite dangerous. On the one side they are highlighted as "for testing purpose only" and on the other side the package creation will fail if the sources folder is dirty. And I also use the same pipelines for packages where the sources may be different among the profiles. 

I'm now thinking of copying the sources into the git repository folder from where I call `conan create .` and check inside the conan recipe if the sources are already copied. If so it skips downloading the sources once again. What do you think about it?

Do you maybe have a better idea?

How would this behave in conan2?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @aed2fe, thank you for your question.

Conan has a mode where it can cache file downloads if the `sha256` checksum is specified.
You can specify `core.sources:download_cache` in your global.conf, pointing to a folder where the downloaded files will be cached after the first time they are downloaded. Subsequent calls to download the same file (assuming the same sha256 checksum), will fetch it from here rather than download them remotely.

**Comment by aed2fe** [comment]
Cool :sunglasses:, so for conan2 there exists already a solution.

In conan1 there is no such configuration available. So here there is only the solution to copy it near by the cloned git repo?

**Comment by memsharded** [comment]
In Conan 1 there was the ``tools.files.download:download_cache`` that allowed caching downloaded source tarballs, similar behavior as the one in Conan 2.

I am closing this ticket as responded and solved, but please re-open if there are any further questions or issues, thanks!
