### ISSUE TITLE
[question] conan list <package_id>/<version> : why all requirement are listed with version [0-9].[0-9].Z ?

### ISSUE THREAD

**Issue by Potoman** [conan-io/conan#15239]
### What is your question?

Hi !

I learn about Conan and try to understand the behaviour of how my requirement are treated. And I have 2 questions for that.

First question :
----------------

When I do a "conan list <package_id>/<version>", I have this result :

```
Local Cache
  my_package
    my_package/8.3.7
      revisions
        123456(date 08:34:33 UTC)
          packages
            789789789987654351312
              info
                settings
                  arch: myarch
                  build_type: Debug
                  compiler: blibli
                  compiler.version: 3.12
                  os: blabla
                options
                  fPIC: True
                  shared: False
                requires
                  blabla_1/1.5.Z
                  blublu_2/2.2.Z
                  bloblo_3/2.0.Z
                python_requires
                  bleble/1.0.Z
```

He, I see that the requirement blabla, blublu and bloblo are always list with version that always finish by "Z" althoug I set it with fixed version. Like 1.5.2 for blabla package. Like that :

```
class MyPackageConan(ConanFile):
    name = "my_package"
    requires = [
            "blabla/1.5.2",

    # ...
```

Second question :
--------------------

Althoug, my second question are : If I list requirement in "def requirements(self):" method, requirement are not list in "conan info" command. Why ?

Thanks :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by Potoman** [comment]
Switch the Conan config from the default  value to core.package_id:default_non_embed_mode=full_mode and the behaviour was the one I expected.

Thanks :)

++

**Comment by memsharded** [comment]
Hi @Potoman 

There is an important thing to consider here: What is listed in the ``conaninfo.txt`` and ``conan list`` and the graph json output is not the ``requirements`` of a package. It is the "binary compatibility" of dependencies for a package.

Changing the ``default_xxx_mode`` changes the binary compatibility of packages regarding versions. It will store something different in ``conaninfo.txt`` and show that information in ``conan list`` but it also has some other more important effects. The most important one is that it can require way more and unnecessary package re-builds. The ``non_embed_mode`` controls for example when a static library that depends on another static library needs to be rebuild. If you change it to ``full_mode``, then changing a comma in the ``conanfile.py`` of the dependency, even if you don't bump the version, will force a rebuild of all static libraries that depend on that static library. But this is not desired in most of the cases, and the default ``minor_mode`` is better default. 
Please have a look to https://docs.conan.io/2/reference/binary_model.html to read more about this.

If you want to have some tracking of the exact dependencies that were used to build a certain binary, there are other approaches:
- You can generate and store lockfiles
- You can create a small "dependencies_manifest" helper that iterates the ``self.dependencies``, collecting the exact versions and storing them in a json file. Then you will call your ``dependencies_manifest()`` helper in your ``generate()`` method (you can put your helper in a ``python_requires`` to reuse it easily)
