### ISSUE TITLE
[feature] Intel oneAPI support

### ISSUE THREAD

**Issue by jakeheke75** [conan-io/conan#15236]
### What is your suggestion?

Hi, is there anything to be done in order to better support Intel oneAPI compiler in Conan?
Can maybe be updated some functions in [cppstd.py](https://github.com/conan-io/conan/blob/37573eeb176b9d382d999d5b3c45d220727f8702/conan/tools/build/cppstd.py#L111) and [detect_api.py](https://github.com/conan-io/conan/blob/37573eeb176b9d382d999d5b3c45d220727f8702/conan/internal/api/detect_api.py#L205)?
I can eventually contribute if needed.
Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jakeheke75 

Thanks for your comments.

We definitely want to support better intel oneAPI, as we don't have enough expertise nor time to improve its usage, and we have a few users using it, but they don't tend to contribute back and mostly keep their changes and tools proprietary.

It would be necessary to propose and discuss what needs to be changed, but definitely contributing Pull Requests to improve things are very welcomed!

Many thanks.

**Comment by memsharded** [comment]
I'd recommend:

- Closing this ticket as responded.
- Creating new tickets for every individual change that is proposed, like "Improving cppstd compiler flags for intel oneapi", or "adding new intel oneapi versions" or "improve CMakeToolchain management of intel oneapi compiler".
- From the feedback from those tickets, contribute individual PRs for them.

This really helps to move things forward, one at a time, with space to talk and discuss the improvements with the maintainers.

**Comment by jakeheke75** [comment]
Sounds good, I will proceed in this way, thanks.
