### ISSUE TITLE
How to consume a dependency package with multiple static libraries in it?

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#15230]
### What is your question?

Hi,
Until now I have created stati-library packages with one one static library, and I was able to consume them in user packages. For example I would create package `hello/1.2.3` containing `libhello.a` in `lib `folder. In the user package, I would be able to `find_package(hello REQUIRED) `with CMake and then `target_link_libraries(myexe.elf hello::hello)`.

But now I am trying to create `test/1.0.0` which packages `liba.a`,` libb.a` and `libc.a` in lib folder. Then in the user package CMake I use `find_package(test REQUIRED)`. But in the end `target_link_libraries(myexe.elf test::a test::b test::c)` doesn't work. CMake says that it doesn't know `test::a` `test::b` `test::c`.

I have also tried the following in the **provider** `test `package recipe
```
    package_type = "static-library"

    def package_info(self):
        self.cpp_info.libs = ["a", "b", "c"]   
```

To **help the consumer** package. But it doesn't work still. What am I missing?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by valgur** [comment]
This will generate exactly the CMake targets you are looking for:
```python
    def package_info(self):
        self.cpp_info.components["a"].libs = ["a"]
        self.cpp_info.components["b"].libs = ["b"]
        self.cpp_info.components["c"].libs = ["c"]
```
Note that `.includedirs`, etc. will also have to be applied for each component separately (although this might no longer be necessary in the latest 2.0 versions).

**Comment by freihamer** [comment]
Thank you, that worked! I am using Conan 2.0.7, indeed there is no need to specifiy .includedirs per component.
