### ISSUE TITLE
[bug] No template named 'function' in namespace 'std'

### ISSUE THREAD

**Issue by chang80** [conan-io/conan#15245]
### Environment details

* Operating System+version: MACOS sonoma
* Compiler+version:Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
* Conan version:1.62.0
* Python version: 3.11

### Logs

despite having #include<functional>  I run into this error No template named 'function' in namespace 'std'

**Comment by memsharded** [comment]
Hi @chang80 

This doesn't look a Conan error, but a regular C++ compile error. 

If it is a Conan error, you'd need to attach:
- A conanfile you are using
- the CMakeLists.txt or other build scripts that you are using
- The C++ code you are using
- The exact Conan commands to reproduce

The idea is to provide a minimal reproducible example, as simple as possible, so we can verify what is happening.

**Comment by memsharded** [comment]
Hi @chang80 

Any update? Thanks
