### ISSUE TITLE
Conan 0.25 could not export sources

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1525]
Hi!

After update to Conan 0.25, all builds on Travis are failing to export sources by `exports_sources`, there is an exception about "Operation not permitted" to write in export_source directory.

I don't know if this trouble comes from conan or conan-package-tools.

As example, I used @lasote's conan-zlib, I just forked and changed cmake to exports_sources

https://github.com/uilianries/conan-zlib/commit/09d2d0b736adbfa88b5fc959b17beb4b01d7835a
https://travis-ci.org/uilianries/conan-zlib/jobs/255654021

Regards.

**Comment by lasote** [comment]
Thanks, Uilian, we are probably releasing a minor today or tomorrow so I'm taking a look.

**Comment by lasote** [comment]
It's something related with docker and the permissions. The good news is that conan is ok, the bad news are that fix it requires a lot of time, but once I get it we can release conan_package_tools or docker images faster.

**Comment by uilianries** [comment]
Thanks @lasote!

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lasote** [comment]
We've been lucky this time. I've released a new **conan_package_tools** removing an unnecessary "conan export" at the beginning (outside the docker container) that was causing the problems.

I pushed my zlib using exports_sources (thanks for the tip) but now it's failing the upload to bintray with an already reported error `(b'<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body ) `. That problem will be solved in two weeks from now by Bintray people.
