### ISSUE TITLE
conan search --table=file.html does not generate output file

### ISSUE THREAD

**Issue by mschmid** [conan-io/conan#1526]
Hi, I tested the new feature "conan search --table" but it did not generate any output. I tested several variants regarding the output file, with extension, without, etc.
It just listed the normal output of "conan search" to the console.
Did I miss anything?
I installed the new version 0.25 via pip under Windows.

**Comment by memsharded** [comment]
can you please type the exact command you are running? remote or local? also compared with the standard output one. Maybe you are missing the filename?

**Comment by mschmid** [comment]
I tried locally:
conan search --table file.html
conan search --table file
conan search --table=file.html
conan search --table=file

**Comment by memsharded** [comment]
you have to provide the package reference:

conan search zlib/1.2.11@conan/stable --table=file.html -r=conan-center


Probably we have to improve the error message. Please try to update to 0.25.1, released today.

**Comment by mschmid** [comment]
I just updated and that gave me the correct error message.
From the description I understood, that it generates a table of all available binary packages, thus not needing a reference.
Providing a reference the command works. I assume it lists the available binary packages of just one reference.
Thanks for your help!

**Comment by memsharded** [comment]
Yes, exactly that. Getting all the binaries for all the packages (with all the versions, channels, etc), could be too much. Typically this is a tool you need to inspect some package, while debugging some issue, checking which supported platforms they have, etc. 

If you think the docs can be improved, please open an issue in the docs repo, or contribute a few lines to it. We just wrote something quick, to be able to release it asap.

Thanks for the feedback!
