### ISSUE TITLE
[bug] git.get_url_and_commit throws exception for different git configs

### ISSUE THREAD

**Issue by Solviana** [conan-io/conan#15261]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: n/a
* Conan version: Found on 1.59.0, all versions are affected
* Python version: 3.8.10

### Steps to reproduce

**1. Set git config "status.branch"** to true:

`git config --global status.branch true`

**2. Use Git.get_url_and_commit()** in your conanfile:
` 
from conan.tools.scm import Git

```
def export(self) -> None:
    git = Git(self, self.recipe_folder)
    scm_url, scm_commit = git.get_url_and_commit()   
   # Do something... 
```

**3. Execute conan create**. My example (copied from a python subprocess call):
```
'['conan', 'create', '-pr:b=ubuntu2004_x86_64_gcc8_debug', '-pr:h=ubuntu2004_x86_64_gcc8_debug', '-pr:h=cross_compiler_x86_64_linux_gcc8', '-pr:h=onep_bit', '/myrepo',
'0.20.2-alpha@user/dev'
```
**Observed result** (even though the repo is **not** dirty, I ran git clean -fd before):

```
Exporting package recipe
my_package/0.20.2-alpha@user/dev: Calling export()
ERROR: my_package/0.20.2-alpha@user/dev: Error in export() method, line 85
        scm_url, scm_commit = git.get_url_and_commit()
        ConanException: Repo is dirty, cannot capture url and commit: /myrepo
```

**Comment by Solviana** [comment]
The root cause is the `is_dirty` function inside `conan.tools.scm.Git`:
```
    def is_dirty(self):
        """
        Returns if the current folder is dirty, running ``git status -s``

        :return: True, if the current folder is dirty. Otherwise, False.
        """
        status = self.run("status -s").strip()
        return bool(status)
```

The problem is that the status.branch git config option will include the branch information in `git status -s` so the returned status will always contain at least one line. Because of this `return bool(status)` will always evalulate to True and this will raise an exception in `get_url_and_commit`

A solution would be to use `git status --short --no-branch`. The no-branch option takes precedence over git config status.branch so the function will perform as intended.

@conan-io/barbarians can you queue this? I'd like to raise a PR with the fix. Since I am already there I will consider all git status config entries to see if any problems like this can arise from other options.

**Comment by memsharded** [comment]
Hi @Solviana 

Thanks very much for your report and your investigation.

It makes sense that there can be some scenarios and configurations that could make the ``is_dirty`` fail. It also makes sense to improve it so it works better and covers those use cases if possible. If you are willing to submit a PR, that would be great of course.

It seems the ``--short --no-branch`` should be relatively low risk. The main risk is that if it would be a very modern git feature, is this the case?

**Comment by Solviana** [comment]
@memsharded 

Based on the Github Git mirror the status.branch was introduced in [ec85d07](https://github.com/git/git/commit/ec85d0700faac679ec27eeacad2bcaa6d9bc8322), so the feature is at least 10 years old (Git 1.8.4). If this is acceptable for you I'd go ahead with the PR.

Going over the [git-config documentation](https://git-scm.com/docs/git-config) I'd include --untracked-files flag as well.

**Comment by memsharded** [comment]
Sounds good, go for it, many thanks!
