### ISSUE TITLE
[feature] <host_version>: ability to reference a dependency of a different name

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#15265]
### What is your suggestion?

To cover cases where we have:
* self.requires()
* self.tool_requires()

Against a pair of references that could be separate components of the same tool - e.g. `libgettext` vs `gettext`, or an hypothetical `libprotobuf` vs `protobuf-compiler`, when we need a 1:1 version matching.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Some of the syntaxes I recall we originally discussed was
```
self.tool_requires("pkg/<host_version(foo)>")
self.tool_requires("pkg/<host_version:foo>")
```

I personally like the second one a bit better, but happy to hear other opnions

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/15274 for 2.0.15
