### ISSUE TITLE
[bug] conan info foo@ locks itself

### ISSUE THREAD

**Issue by marxin** [conan-io/conan#15276]
### Environment details

* Operating System+version: Linux
* Compiler+version: GCC 13.2
* Conan version: 1.62.0
* Python version: 3.11.6

### Steps to reproduce

```
marxin@marxinbox:~> find ~/.conan/data -name _.count.lock
marxin@marxinbox:~> conan info gdal/3.7.0@
WARN: libgeotiff/1.7.1: requirement libtiff/4.6.0 overridden by gdal/3.7.0 to libtiff/4.5.1 
WARN: libgeotiff/1.7.1: requirement proj/9.3.0 overridden by gdal/3.7.0 to proj/9.1.1 
libtiff/4.5.1 is locked by another concurrent conan process, wait...
If not the case, quit, and do 'conan remove --locks'
...
marxin@marxinbox:~> find ~/.conan/data -name _.count.lock
/home/marxin/.conan/data/gdal/3.7.0/_/_.count.lock
/home/marxin/.conan/data/libgeotiff/1.7.1/_/_.count.lock
/home/marxin/.conan/data/libtiff/4.5.1/_/_.count.lock
/home/marxin/.conan/data/json-c/0.16/_/_.count.lock
```

There's no other running conan process. What's also strange is that `conan remove --locks` does not release all locks:
```
marxin@marxinbox:~> find ~/.conan/data -name _.count.lock
/home/marxin/.conan/data/libtiff/4.5.1/_/_.count.lock
```

**Comment by memsharded** [comment]
Hi @marxin 

Thanks for your report.

I am trying to reproduce, but so far didn't succeed.
I have tried both on Windows and Linux (docker, the ``conanio/gcc11`` image), all good here.
I have no idea why this could be failing, is there something specific to your machine? Can you see this in different machines?

**Comment by marxin** [comment]
I wiped `~/.conan/data` and it's fine now.

**Comment by memsharded** [comment]
I guess that something went corrupted in the cache causing that, thanks for following up
