### ISSUE TITLE
[develop2] linking with opencv: at runtime does not find features2d and calib3d, others working

### ISSUE THREAD

**Issue by metalMajor** [conan-io/conan#15275]
Hello,

I use the conan_provider.cmake and that works all very well, so I have a library to which I link opencv this:
```
find_package(OpenCV REQUIRED COMPONENTS core imgproc features2d video calib3d)
target_link_libraries(myLib 
  PUBLIC
     opencv_core
    opencv_imgproc
    opencv_features2d
    opencv_video
    opencv_calib3d
)
```

And then I use that library in a (unittest) executable that I am creating:

```
target_link_libraries(myTest PUBLIC myLib)
```

Everything compiles and links, but when I start my tests using for example "ctest" in the build dir, then it only finds the "core", "imgproc" and "video" libraries, but not "features2d" and "calib3d". However, they exist in the same directory on my system under $HOME/.conan2/......lib. So they are there for sure. When not using the "features2d" and "calib3d" libraries, then it all works... so...

The only thing I see is that **the not-working libraries have a number in their names**, and the other ones not... or am I paranoia haha. It's suspicious!

Just adding: it works on macos, but not on a linux box.

**Comment by memsharded** [comment]
Hi @metalMajor 

I think this wouldn't be related to the cmake-conan integration at all, but to Conan and the recipes involved, I think this could be replicated with normal ``conan install`` + ``cmake ...`` commands. It would be great to do so to discard the effect of cmake-conan.

Then, this seems like an effect of RPATHs, and that is kind of expected, when using packages built in another machine, only the directly linked libraries will be in the executable RPATH, but the transitive ones might not be. This is typically addressed by activating the ``conanrun`` environment (``source conanrun.sh`` in Linux) before executing things that depend on shared libs of the host context (like tests in this case). Can you please try that?

**Comment by metalMajor** [comment]
Hi, thanks for the quick reply! It works when I indeed first source the "conan/conanrun.sh" in the build dir!

(sorry for posting here, it's sometimes difficult to know where it's most relevant 🙈 )

**Comment by memsharded** [comment]
No prob, we can transfer tickets as necessary, I will move this one to "conan" repo because it is then a question about Conan itself.

**Comment by memsharded** [comment]
> Hi, thanks for the quick reply! It works when I indeed first source the "conan/conanrun.sh" in the build dir!

That is great, so I think we can consider the issue resolved?
In any case, I think you might be interested in https://github.com/conan-io/conan/pull/15192, it generates the environment variables directly into a generated CMakePresets. It requires inversion of control, that means, not using ``cmake-conan``, but following the "standard" flow of ``conan install`` + ``cmake --preset ...``, but it might be worth the convenience
