### ISSUE TITLE
[bug] install not using latest recipe revision

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan#15283]
### Environment details

* Operating System+version: Ubuntu 22.04 (Docker)
* Compiler+version: gcc 11.4
* Conan version: 2.0.14
* Python version: 3.10.12

### Steps to reproduce

Difficult to give you a reproducible example, but I am experiencing the following issue:

Conan install does not use the latest recipe revision from the server.

```
conanfile.py
def requirements(self):
        self.requires("mypackage/1.0.0@me")
```

```
conan install . --build missing
```

```
======== Computing dependency graph ========
Graph root
    conanfile.py: /conanfile.py
Requirements
    mypackage/1.0.0@me#37ed57f56bf819f5e03a96adc221018d - Cache
```
```
conan list "mypackage/1.0.0#*" --remote myremote
myremote
  mypackage
    mypackage/1.0.0@me
      revisions
        37ed57f56bf819f5e03a96adc221018d (2023-11-24 12:50:15 UTC)
        1c895279d3c9d4f387953f2d8534ef79 (2023-11-28 09:13:58 UTC)
```

`1c895279d3c9d4f387953f2d8534ef79` is clearly the latest recipe revision but it is not being picked up by the conan install command. Is there any server side setting that could explain this? I will attempt to come up with a reproducible example in the meantime.

### Workaround

Specify the recipe revision explicitly in the `conanfile`

**Comment by memsharded** [comment]
Hi @planetmarshall 

Thanks for your question.

Conan resolves by default first in the cache, this is why the output:
```
mypackage/1.0.0@me#37ed57f56bf819f5e03a96adc221018d - Cache
```
is listing it in "Cache"

If you want to update the latest from the server, you need to provide the ``conan install --update`` argument.

**Comment by planetmarshall** [comment]
@memsharded thanks for the rapid response and clarification.
