### ISSUE TITLE
Package dependencies do not seem to be honored

### ISSUE THREAD

**Issue by nlbutts** [conan-io/conan#153]
I am trying to test package dependencies and pull the source code into the local project file. You responded a few days on how I could do this. What I've done is made a a convention that all toolchains get install to the toolchain directory, unittest frameworks live in the unittest directory and all libraries live in the libXXXX directory. 

Using this conanfile.py:
```
from conans import ConanFile, CMake, GCC

class AppConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires =  "gcc_arm_none_eabi/4.8.4@toolchain/stable", \
                "gmock/1.7.0@unittesting/stable",   \
                "stm32f4/1.0.0@processors/stable", \
                "utility/1.0.0@rtp/stable"
    generators = "cmake", "gcc", "txt"

    def imports(self):
        print("Import files")
        self.copy("*", "toolchain", "toolchain")
        self.copy("*", "unittest", "unittest")
        self.copy("lib*", "", "")

```
and running 
`conan install --build=missing`

I expect the following directory structure:

```
<project>/toolchain
<project>/unittest
<project>/libstm32f4
<project>/libutility

```
Now libutility's conan file looks like this:
```
from conans import ConanFile
import platform

class libUtility(ConanFile):
    name = "utility"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"
    exports = "*"
    license = "Appareo"
    author = "Appareo"
    requires = "HAL/1.0.0@processors/stable"

    def build(self):
        print("libUtility build")

    def package(self):
        print("libUtility package")
        self.copy("*", "libUtility", "libUtility")

    def package_info(self):
        self.cpp_info.includedirs = ['include']

```

It requires the HAL 1.0.0 package. So I expect, as part of the depenendecy check, that libutility would pull down libHAL and "build" it. In my case, the build step does nothing and the package step copies the entire directory from the export directory to the package directory. Then the applications conanfile.py tries to pull in all of the lib* directories. 

Why wouldn't libHAL get pulled down? What am I missing?

**Comment by nlbutts** [comment]
Doh, I had included an old package that didn't have the requirement in the conanfile.py. My bad.

**Comment by memsharded** [comment]
No problem. Better report and then realize that it is not an issue, than not reporting. Thanks!
