### ISSUE TITLE
[question] Conan 2 Package ID Mode

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#15305]
### What is your question?

Hello! I wanted to confirm that in Conan 2.x the Conan 1.x package ID mode called "package_revision_mode" is now the same as "full_mode". Is this a correct assumption? (It looks like the Conan 2.x documentation has a section to cover this but it is still empty/a work in progress.)

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @radonish 

Thanks for your question.

``full_mode`` in Conan 2.0 is:

```
    def full_mode(self):
        self.name = self._ref.name
        self.version = self._ref.version
        self.user = self._ref.user
        self.channel = self._ref.channel
        self.package_id = self._package_id
        self.recipe_revision = self._ref.revision
```
As you can see, the ``package_revision`` is no longer managed. It has been dropped in Conan 2.0 as a ``package_id`` factor, and having more than 1 ``package-revision`` for the same ``package_id`` is considered as a process or model error.

**Comment by radonish** [comment]
@memsharded, thank you for the clarification.

If I have a package for libA that uses exports_sources to include the source code in the package - am I safe to assume it will generate a different package ID if:

- version, user, and channel stay the same
- source code (as noted above it is in exports_sources) changes via developer code change

Is this still a safe assumption?

Thanks!

**Comment by memsharded** [comment]
No, if the source code changes, that code if it is in ``exports_sources``, it will be part of the **recipe revision**, which is the first part of the identifier: ``pkg/version#recipe_revision:package_id``:

- version + recipe-revision: uniqueness of the origin "sources" of the package, including conanfile, conandata, sources ...
- package_id: uniqueness of the configuration (settings, options, dependencies, etc)

So ``version + recipe-revision + package_id`` should always be unique, and wouldn't require to ever re-build the same package_id binary causing an extra package-revision.

**Comment by radonish** [comment]
Great, thanks again for the clarifications!
