### ISSUE TITLE
[question] How to build non-Conan third-party packages as part of another project

### ISSUE THREAD

**Issue by HerrNamenlos123** [conan-io/conan#15308]
### What is your question?

I have a project that needs a few third-party libraries that are not part of conan. I do not want to put effort into making a public conan recipe for the conan center, I tried once and I think it's way out of scope because everything needs to be perfect regarding settings, etc. I just need it for this project itself which is a lot easier to set up a single configuration.

Now, ideally I would like to provide a main conanfile.py to build the project, which requires the dependency, and then in another subfolder I have another conanfile.py, that provides a package by downloading the source and building it. The main conanfile would simply link to the sub conanfile so that it is found, and then the library would be built, and then the main project, but both just locally as part of one big project.

Can this be achieved in Conan 2? Or is there a better way? I am struggling with telling the main conanfile to look for the other one, how would I do that?

EDIT:
Oh and by the way, it should not involve using terminal commands. From the view of the user, it must be a single seamless build command, no calling different commands in different directories.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by HerrNamenlos123** [comment]
Well, I found the solution myself immedately after posting. classic.
For anyone: Here is the solution:
https://github.com/conan-io/conan/issues/1536

Sorry for any inconveniences

**Comment by HerrNamenlos123** [comment]
Only the command needs to be changed to `conan export --user=user --channel=stable conanfile.py`, to work with Conan 2

**Comment by memsharded** [comment]
Hi @HerrNamenlos123 

You might be interested in tracking https://github.com/conan-io/conan/pull/13930

It allows to use a git repo similar to ``conan-center-index`` (it can be typically a fork of it, so you can also use modifications of ConanCenter recipes if you need it), as a Conan remote (added by ``conan remote add ...``), and it avoids needing to ``conan export`` or ``conan create`` the recipes.

This is intended for one of the next releases, in about 1-2 months

**Comment by HerrNamenlos123** [comment]
Thanks for sharing!
