### ISSUE TITLE
[bug] "ERROR: win_bash=True but tools.microsoft.bash:subsystem configuration not defined" even though it's defined by a build requirement

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#15317]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: MinGW GCC 13.2.0
* Conan version: 2.0.15
* Python version: 3.11.1

### Steps to reproduce

```
conan install --requires libcurl/8.4.0 -b missing
```

### Logs

```
libcurl/8.4.0: Sources downloaded from 'conancenter'
ERROR: win_bash=True but tools.microsoft.bash:subsystem configuration not defined
```

**Comment by SpaceIm** [comment]
It's worth noting that `libcurl` recipe defines `self.win_bash=True` in build requirements if Windows and not msvc, and adds `msys2` to build requirements in this case if `tools.microsoft.bash:path` is not defined (and I don't define this conf in my profile, command line or global.conf). `msys2` defines `tools.microsoft.bash:subsystem` in its `package_info()`, so it shouldn't fail, and actually it didn't fail before conan 2.0.15 (just tested again with conan 2.0.14, and it builds fine).

https://github.com/conan-io/conan-center-index/blob/cc5692484d667b48e10aec754d498379f2e3ed71/recipes/libcurl/all/conanfile.py#L213-L216

All conancenter recipes which need a shell at build time on Windows rely on this pattern, so it could break many recipes.

**Comment by memsharded** [comment]
I have just tried with my profile:
```
[settings]
os=Windows
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
arch=x86_64
build_type=Release


[buildenv]
PATH=+(path)C:\ws\msys64\mingw64\bin
```
And it didn't fail. Update: it doesnt fail in libcurl, it fails in openssl build

**Comment by fdgStilla** [comment]
I get the same error from a fresh conan install in CI with another package: openh264

But after playing with a little with the conan version from/to 2.0.14 and 2.0.15, now I don't have the issue even with the last version of conan 2.0.15...

**Comment by memsharded** [comment]
We are considering a revert or a fix asap, keep tuned.
