### ISSUE TITLE
[bug] Options with allowed None value still need a default option value, otherwise error!

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#15315]
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version: NA
* Conan version: 1.61
* Python version: 3.9

### Steps to reproduce

On [this page](https://docs.conan.io/1/reference/conanfile/attributes.html#options)  it says:

> The consumer can define options using different methods: command line, profile or consumer recipes; an uninitialized option will get the value None and it will be a valid value if it is contained in the list of valid values. 

I have understood it like this that if I specify an option to have either None or "ANY" value then I do not need to define a default option value None since an "uninitialized option will get the value None". But during our testing it looks different. An error is thrown if I do not specify the default value to be None.

`ERROR: <pkg name>/None: '<option name>' value not defined`

Now I am asking if there is a misunderstanding on my side (then please enhance the docs a little bit to make it unambiguous) or this is supposed to work. And then this is a Conan problem/bug.

**Comment by MTomBosch** [comment]
Maybe to add some more context. The options are defined in a Conan recipe base class that the recipe is derived from. The base class package is declared within the python requires section.

**Comment by memsharded** [comment]
Hi @MTomBosch 

Thanks for your report.
Could you please clarify what definition are you using? I think ``options = {"myoption": [None, "ANY"]}`` is the correct one for enabling this.

**Comment by MTomBosch** [comment]
The definition is:

```
      options = {
        "variant": [None, "ANY"],
        "domain": [None, "ANY"],
      }

```

**Comment by memsharded** [comment]
I have been checking this, and this seems a failure in the documentation.
Indeed the desired behavior was being able to define ``myoption: [None, "ANY"]``, but apparently this wasn't possible to implement in Conan 1.X, and it was only implemented in Conan 2.0 fully, but the documentation captured the initial intention, not the final behavior.
In Conan 1.X:
- It is possible to have ``None`` as a possible value, allowing the non-definition of the option
- It is possible to have ``ANY`` as a possible value, allowing the definition with any VALUE, but really requiring a value
- But it is not possible to have both simultaneously

I have done a check, doing a new try to be able to provide this, but I am afraid this is not possible without quite some risk of breaking. So I think this needs fixing the docs (and it is already solved in Conan 2.0)

**Comment by MTomBosch** [comment]
Just to get it right:

In Conan 1.x I need to keep specifying default options like:

default_options = {
        "variant": None,
        "domain": None
}

If I want a conan install to not abort with an error if I do not specify any options for the package

In Conan 2.x I do not need to specify and default value because there None is then used implicitly.

Is my understanding correct?

**Comment by memsharded** [comment]
Yes, I think that is correct.
In both cases, the correct ``options`` definition would be ``options = {"config": [None, "ANY"]}``, and the ``default_options`` can be dropped in 2.0

**Comment by MTomBosch** [comment]
OK. Thank you for the confirmation. Closing this ticket.
