### ISSUE TITLE
Lib/bin not copied from build to package

### ISSUE THREAD

**Issue by Alxandr** [conan-io/conan#1532]
I'm not sure if this is a bug with conan or the package I'm using (I'm completely new to this and just set it up an hour or so ago), but I'm having problems getting the following package to work: https://conan.io/source/glew/2.0.0/coding3d/stable

It builds just fine, and I get my own code to compile, but it doesn't link. When I look in `~/.conan/data/glew/..../build` there are lib and bin files that should be used for linking, but they are not present in the `package` dir. And the cmake file produced only references the `package` dir. Is there something wrong with the package, or am I doing something wrong?

**Comment by Alxandr** [comment]
Figured it out. It turns out that copying is handled by the conan script in the package, and I've reported the problem with the package owner :)

**Comment by memsharded** [comment]
Ok, great. Would you mind copying here a link to the package owner github repo issue, if that is the case?
Thanks!

**Comment by Alxandr** [comment]
It was just discussed in a PR here: https://github.com/nigels-com/glew/pull/151.

**Comment by dimi309** [comment]
I've committed a fix for this issue. I am having [some trouble with the latest version of the package tools](https://github.com/conan-io/conan-package-tools/issues/89) in the CI environment, but if you clone my repository and build locally with conan there should be no problem.

**Comment by dimi309** [comment]
The issue I mentioned above has now been resolved and I have now published the corrected version of the glew package on bintray.
