### ISSUE TITLE
[question] access to the contents of a consumed packet

### ISSUE THREAD

**Issue by mangeMelon** [conan-io/conan#15332]
### What is your question?

access to the contents of a consumed packet

Hello
I'm trying to access a directory that I copied into Package A;
for used in package B (consume package A).

My package A is a communication library that uses protobuf
I am carrying out tests with Robot Framework, and I therefore created a python library to interact with protobuf
I integrated my emulator into package A.

in package B, I'm looking to access the emulator directory (in package A) and use it.

Can I access the emulator through the toolchain?

In the same principle, I have a C package which contains resources files (json...) which are used for configuration.
These files are common to several of my packages.

So I'm looking to access these files to read them.

Is this possible or am I trying to draw too much conan?

Merry Christmas and a wonderful New Year!
### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mangeMelon 

Thanks for your question.

A recipe can always get access to its dependencies, via the ``self.dependencies`` attribute, see: https://docs.conan.io/2/reference/conanfile/attributes.html#dependencies

The recommended way to do so is most of the times in the ``generate()`` method. Do there what you need, like copying files, and "prepare" the build. Then the ``build()`` method should find the things ready in place.

Though in general, I'd recommend trying to avoid this as much as possible. Packages are an abstraction over dependencies, accessing directly files via ``self.dependencies`` is breaking that abstraction.

> in package B, I'm looking to access the emulator directory (in package A) and use it.

This can be typically done:

- Package B puts its binaries inside the ``bin`` folder of the package
- The consumer of package B via the ``VirtualBuildEnv`` (implicit in 2.0, no need to call it explicitely) will create some ``conanbuild.bat|.sh`` file
- The consumer will automatically load the ``conanbuild`` environment script everytime is running something, automatically activating the environment and  putting B binaries in the path of the consumer, transparently. 

So please check the tools, and ask questions as necessary, it is very likely that you don't need to access the dependencies folders directly and Conan can provide mechanisms to use them more transparently

**Comment by memsharded** [comment]
Hi @mangeMelon 

Any further feedback or question here? Can we close the issue? Thanks!
