### ISSUE TITLE
[feature] Allow passing flags to CMake build tool

### ISSUE THREAD

**Issue by stevenwdv** [conan-io/conan#15333]
### What is your suggestion?

For example, one may specify `tools.cmake.cmaketoolchain:generator=Ninja`, which will cause Ninja to build with a lot of parallel processes, but some runners may not be able to handle this memory-wise, so it would be useful to be able to limit parallelism by passing flags to Ninja: `ninja -j1`, or alternatively `cmake --build . -- -j1`. This flag is just an example.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @stevenwdv 

There is the conf:
```
tools.build:jobs: Default compile jobs number -jX Ninja, Make, /MP VS (default: max CPUs)
```
(side note, you can see all confs with ``conan config list``)
That can be used to define the ``-j`` parallelism, and it works also for other build systems, is this what you are looking for?

**Comment by stevenwdv** [comment]
Oops, thanks! I searched for the wrong keywords.
