### ISSUE TITLE
virtualbuildenv's activate script does not append to PATH variable

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#1533]
This is probably by design, but it does pose a problem when you're trying to use Conan to get an executable needed for the build process (using the `build_requires` setting).

**Comment by MarcoKoch** [comment]
I have stumbled over this too recently.
The path is added if Conan is explicitly instructed to do so in the package recipe of the requirement:

    self.cpp_info.bindirs = ["bin"]
    self.env_info.path.append(os.path.join(self.package_folder, "bin"))

Though, I also had expecteded that defining `self.cpp_info.bindirs` would be sufficient. Is there a good reason to not add all paths in `bindirs` to `PATH`?

**Comment by JPGygax68** [comment]
@MarcoKoch I already had the second of your two lines, but adding the first one did not change anything for me.

**Comment by MarcoKoch** [comment]
@JPGygax68 Ah, sorry. I confused `virtualbuildenv` with `virtualenv`.
I agree that not adding it may be by design then. A solution or work-around would be nice though. I would probably have run into the same problem as you in a couple of days . 😆

**Comment by lasote** [comment]
**virtualbuildenv** only sets variables related to the build system, CXXFLAGS, CFLAGS, LDFLAGS, LIBS... etc. You should activate both **virtualenv** and **virtualbuildenv**, they are composable.

**Comment by JPGygax68** [comment]
Thank you Luiz,

but my point was that PATH *can* needed in the build environment if your
build dependency is a tool needed for building.

This however is a non-trivial subject, especially if cross-compilation
enters the picture.

**Comment by lasote** [comment]
Sorry but I still don't understand. If you have a dependency for building you have 2 options:

1. Use it as a **build_require** and declare the PATH variable in the `self.env_info` object. Then the packages depending on the build require will automatically inherit (no action required) the PATH or any other environment variable declared in the build_require.

2. If you want to do the same with virtual environments you can do it, specify both **virtualenv** and **virtualbuildenv** in the generators list and then activate both, first the `activate.sh` and then the `activate_build.sh`

**Comment by JPGygax68** [comment]
About (1): in this case, the final target is not a Conan package and therefore not being built by a Conan recipe, so that doesn't help in this case.

About (2): I understand I could do that, but I think it's incredibly counter-intuitive. A build dependency, by definition, is used for building. Why should the path be inherited when the building is done by Conan (1), but not when it is done by other means with the help of `activate_build` ?

**Comment by lasote** [comment]
About (1): Ok
About(2): It is... with the virtualenv environment. We think it's better to separate the environment produced by the user declared environment variables and the specific variables for a specific build system/environment.

**Comment by JPGygax68** [comment]
I don't think I'm understanding your comment about (2)... 

The way I see it, build dependencies and run-time dependencies are completely separate things, not least because of the possibility of cross-compilation (which, however, I've never done myself), so I wouldn't want to mix variables from one domain with variables from the other. In the absolute worst case, the build and run-time environments might both require the same component, but different versions - chaos ensues.

**Comment by lasote** [comment]
You are considering that virtualenv is for runtime dependencies and virtualebuildenv is for build dependencies, and that is not true. Virtualenv is applying the `self.env_info` objects from the dependencies, no matter if the dependencies are for run-time or building, and virtualbuildenv is "emulating" the build helpers available in the conanfile (AutoToolsBuildEnvironmend and/or VisualStudioBuildEnvironment), but using a virtualenv.

**Comment by JPGygax68** [comment]
Ahh - that does clear things up quite a bit! Sorry about that misunderstanding.

**Comment by memsharded** [comment]
@MarcoKoch 

> Though, I also had expecteded that defining self.cpp_info.bindirs would be sufficient. Is there a good reason to not add all paths in bindirs to PATH?

At some point we have considered automatically adding ``bindirs`` to path and even LD_LIBRARY_PATH, but finally preferred it to be something explicit and driven by the user. Automatically adding shouldn't be a problem until something happens, and there there is no possible way to avoid that failure. So whenever possible, conan tries to be explicit (opt-in behavior), so users keep in full control as much as possible.

**Comment by MarcoKoch** [comment]
This sounds reasonable. Maybe adding a short notice to the docs of `package_info()` could help save others some time to find out that they may have to add both lines?

I just noticed that using multiple virtual environments together is described in the docs as typical use case. Seems like I missed that back when studying those. Maybe some additional examples could help there too? I had to read through that page again multiple times until I now think I got a clear picture of when to use which virtual environment (or combination thereof).

**Comment by memsharded** [comment]
Sure, I have added some clarifications: https://github.com/conan-io/docs/commit/2de0c6cd12a51fb1498bb97cecbf7a0f65e1d8c6

For the other, what would you suggest, like a "composing environments" subsection in http://docs.conan.io/en/latest/mastering/virtualenv.html?
