### ISSUE TITLE
[question] What is the replacement of generators = "visual_studio" in conan 2.0

### ISSUE THREAD

**Issue by sinall** [conan-io/conan#15331]
### What is your question?

I tried `MSBuildDeps`, it generated lots of props files, is there a way to generate single one containing all those dependencies?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by sinall** [comment]
It seems that there is a `conandeps.props`.

**Comment by memsharded** [comment]
Hi @sinall 

Thanks for your question

This is not a Conan 2.0 question, but a ``MSBuildDeps`` one, this integration also exists in Conan 1.X for a long time, and it is recommended for 1.X too.

Regarding your question, ``MSBuildDeps`` generates a ``conandeps.props`` that aggregates all the dependencies, you can use that file if you don't want to use specific dependencies in specific subprojects (to avoid overlinking)
