### ISSUE TITLE
[question] upload_policy = "skip" breaks skipping binaries?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15330]
### What is your question?

Looks like `upload_policy = "skip"` attribute in a non-visible dependency doesn't work as one would expect: Conan builds a binary package that should be skipped. The test case is attached. When pkg3 is built pkg1 binary should be skipped, but it's built from sources due to `upload_policy = "skip"` in pkg1.
[test_case.zip](https://github.com/conan-io/conan/files/13752720/test_case.zip)

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your report.
It seems there could be a gap, or at least some undefinition in the behavior of this case. Your test case really helped to reproduce, thanks very much for putting it together.

I am checking it, seeing what possibilities of improvements are possible, I'll update here.

**Comment by memsharded** [comment]
I am exploring in this draft https://github.com/conan-io/conan/pull/15336 a possible solution

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/15336, it will be in next 2.1
