### ISSUE TITLE
[feature] Provide a strict compatibility checker for cppstd

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#15347]
### What is your suggestion?

Related to https://github.com/conan-io/conan-center-index/issues/19008

The Catch2 project supports both C++14 and C++20, and uses separated features in case building with C++20, making it incompatible to link to projects that were built with C++14.

So far, we don't have a helper to specify it directly. For now, we can use [compatibility.py](https://docs.conan.io/2/reference/extensions/binary_compatibility.html), or some workaround in `validate()`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/15348 for next Conan 2.1
