### ISSUE TITLE
[question] What is the replacement of `conan imports` in 2.0?

### ISSUE THREAD

**Issue by sinall** [conan-io/conan#15341]
### What is your question?

In my build process, I need to copy dll of dependencies to my `build` folder.
How can I do this? Is there a way to only copy dlls, or I have to run full `conan install`?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by db4** [comment]
@sinall You can do it in `generate()` method:
```python
    def generate(self):
        exts = ["dll", "so*"]
        for dep in itertools.chain(self.dependencies.host.values(), self.dependencies.test.values()):
            for ext in exts:
                copy(self, f"*.{ext}", src=dep.package_folder, dst=self.build_folder)
```

**Comment by memsharded** [comment]
Also, for most cases it is not necessary to copy the .dlls to the build folder. The built-in ``VirtualBuildEnv`` and ``VirtualRunEnv`` will manage to set the environment PATH (or other variables), so the dlls can be used without copying them.
