### ISSUE TITLE
[feature] Improve detect API to support Intel oneAPI compiler

### ISSUE THREAD

**Issue by jakeheke75** [conan-io/conan#15344]
### What is your suggestion?

Hi there,
Is there anything that we can do in order to better support the Intel oneAPI compiler in the [detect API](https://github.com/conan-io/conan/blob/37573eeb176b9d382d999d5b3c45d220727f8702/conan/internal/api/detect_api.py#L205)?
Any suggestion is welcome, I will be happy to contribute.
Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jakeheke75 

Thanks for your suggestion.

Yes, it would be possible to add detection for Intel OneAPI. The place to do it would be the ``def detect_compiler():`` method in ``detect.py`` file. Some points to take into account:

- The default precedence (msvc in Windows, gcc in Linux, etc) cannot be changed, it could be considered too breaking.
- If the CC/CXX env-vars are defined to point to it, then it would be the easier approach, and then the detection for it can be implemented there
- You can have a look how gcc and others detect the version
- After compiler + version are detected correctly (this can be tested with ``conan profile detect -f``), then it would be necessary to complete the other defaults: cppstd, libcxx (if it used, like Linux) or runtime (for Windows)

The way to do it would be a PR to improve that. As testing of this is quite challenging for this feature, no tests are initially added, and we should trust your manual testing mostly.

Please let me know if this is enough to start

**Comment by jakeheke75** [comment]
Hello @memsharded 

Thank you for all the information. It's enough to start, I will submit a draft PR as soon as I have something working. If I have any doubt during the development process I will write it here; in this way we can keep track of all the open points.

Thanks!

**Comment by jakeheke75** [comment]
Well, I haven't got so far without asking the first question :smile: 
Where can I update the strings of the Intel compiler versions in `settings.yml`? I mean, now for testing purposes I can update them manually, but in the future we probably want to have them stored and retrieved automatically right?
![image](https://github.com/conan-io/conan/assets/113254017/52efca58-156c-415d-b52e-54f08f032187)
Thank you in advance for your help.

**Comment by memsharded** [comment]
Hi @jakeheke75 

Don't worry, you can ask as many questions as you need 🙂 

You can add whatever is necessary/expected in https://github.com/conan-io/conan/blob/bde2eaa061e1d202dff06ece20427bd5f27cfaa4/conans/client/conf/__init__.py#L3

To test temporarily go to your cache (``conan config home``) and modify the ``settings.yml`` there.


Side hint: When posting things to Github, it is better to copy and paste as text rather than images, that allow us to copy and search, etc. Formatting can be done with triple backticks. Many thanks!

**Comment by jakeheke75** [comment]
Hello @memsharded

Just pushed a draft PR for this. Any advice is appreciated, thank you in advance for your time.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/15358 for 2.1
