### ISSUE TITLE
[question] Conan 2.0.15 issue with run environment and ctest

### ISSUE THREAD

**Issue by mikirothman** [conan-io/conan#15342]
### What is your question?

Hi,

I upgraded to Conan 2.0.15 from Conan 2.0.9, and was eager to test the new feature which introduced environment information to CMake test presets. [#15192](https://github.com/conan-io/conan/pull/15192).

The problem that it seems to break my integration with ctest.
until now, I used the ctest presets to invoke the application, and I was in charge to supply the application the environment in the following way:
```python
def generate(self):
        ms = VirtualRunEnv(self)
        envvars = ms.environment()
        envvars.define_path("CONFIG_PATH", os.path.join(self.recipe_folder, "config", ""))
        envvarsrun = envvars.vars(self, scope="run")
        envvarsrun.save_script("myproject-run-{}".format(str(self.settings.build_type).lower()))
```
then before running ctest I whould enable the run environment using myproject-run-${build_type} script.
The CONFIG_PATH environment variable is defined in my recipe generate method, but it's overriding CONFIG_PATH variable from on of my dependencies, now whenever I activate ctest with the presets, I'm getting CONFIG_PATH configured from the dependency package.
is there a WA ? am I doing something wrong ?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mikirothman 

Thanks for your question.

It is true that the new CMakePresets feature do not handle environment modifications from the current recipe, it only injects environment from dependencies. I'll have a look to investigate what could be done

**Comment by memsharded** [comment]
Some idea to discuss with @czoido:

We could leverage the internal buildenv+runenv of ``conanfile`` (not documented yet, do not use until it is public!). Doing that, every instance of ``VirtualBuildEnv`` and ``VirtualRunEnv`` would take that information into account, making it work in other places as well (for example ``MesonToolchain`` also instantiates internally ``VirtualBuildEnv``).

This would be a bit risky and new, so might need careful consideration and discussion

**Comment by czoido** [comment]
Hi @mikirothman,

I was checking the issue and thought that maybe if you change the way of adding the environment variable in your dependencies, you could override the value when you run the environment using the `myproject-run-${build_type}` script.
- Are you using `self.runenv_info.prepend_path("CONFIG_PATH",...)` in the dependencies? 
If that's the case, could you try changing that to `self.runenv_info.append_path("CONFIG_PATH",...)`? Doing so, the environment in the presets file will be generated like this:

```
    "testPresets": [
        {
            "name": "conan-release",
            "configurePreset": "conan-release",
            "environment": {
                ...
                "CONFIG_PATH": "$penv{CONFIG_PATH}:<the_value_set_by_dependency>"
                ...
            }
        }
    ]
```

So, when you manually activate the environment, the `CONFIG_PATH` should be the one from the script. 

Could you give it a try?

Thanks!

**Comment by mikirothman** [comment]
Hi, @czoido

I'm using ```self.runenv_info.define_path("CONFIG_PATH",...)``` in the dependencies, cause configuring a list of paths is not supported in our case...

**Comment by czoido** [comment]
> Hi, @czoido
> 
> I'm using `self.runenv_info.define_path("CONFIG_PATH",...)` in the dependencies, cause configuring a list of paths is not supported in our case...

Hi @mikirothman, 
Could you provide some details about your workflow?  How are you adding those paths, from which dependencies are added...? Understanding this will help us identify a potential workaround. Thank you!

**Comment by mikirothman** [comment]
Sure,

The ```CONFIG_PATH```, is a kind of a configuration entry point for the application (which we depend on as an SDK),
The SDK supplies a default value, that is usually (always in practice) overridden by the clients.

Until Conan v2.0.15, we use to set the environment with the client ```CONFIG_PATH``` and call ctest through the ctest presets.
Since Conan v2.0.15 it is not passible anymore, cause ctest preset is overriding the ```CONFIG_PATH```.

We thought on removing ```CONFIG_PATH``` from the dependency, and let the clients set it. but it's not feasible, cause the SDK can run on it's own, and also the common use-case is that there is at least depth of 3 nodes in the dependency three that sets the ```CONFIG_PATH```, and each can run independently,

The SDK is not supporting the ```CONFIG_PATH``` to be a list of paths, it reads only one path.

### dependency conanfile.py
```
def package_info(self):
        ...       
        self.runenv_info.define_path("CONFIG_PATH", ...)
        ...
```

The client will override the environment variable

### client conanfile.py
```
def build(self):
        ...       
        cmake.test(self) #here it fails, cause it will use the dependency CONFIG_PATH
        ...
```

```
def package_info(self):
        ...       
        self.runenv_info.define_path("CONFIG_PATH", ...) 
        ...
```

**Comment by czoido** [comment]
Hi @mikirothman thanks a lot for the feedback, we have just merged https://github.com/conan-io/conan/pull/15470 that should let you modify your environment in the `generate()` method and pass it to the presets via `CMakeToolchain.presets_build_environment` and `CMakeToolchain.presets_run_environment` . Something like this:

```python
def generate(self):
    runenv = VirtualRunEnv(self)
    runenv.environment().define("MY_RUN_VAR", "MY_RUNVAR_SET_IN_GENERATE")
    runenv.generate()
    env = Environment()
    env.define("MY_ENV_VAR", "MY_ENV_VAR_VALUE")
    env = env.vars(self)
    env.save_script("other_env")
    deps = CMakeDeps(self)
    deps.generate()
    tc = CMakeToolchain(self)
    tc.presets_run_environment = runenv.environment()
    tc.generate()
```

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/15470
