### ISSUE TITLE
Add "-FS" flag to ``AutotoolsToolchain``

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#15365]
Then, it would make sense to create an updated feature request for ``AutotoolsToolchain``. Having those cases in ConanCenter is also useful, I think it could be added to ``AutotoolsToolchain``

_Originally posted by @memsharded in https://github.com/conan-io/conan/issues/6514#issuecomment-1872636677_

**Comment by SpaceIm** [comment]
Pattern in conancenter:

```python
        tc = AutotoolsToolchain(self)
        if is_msvc(self) and check_min_vs(self, "180", raise_invalid=False):
            tc.extra_cflags.append("-FS")
            tc.extra_cxxflags.append("-FS")
```

Visual Studio version must be checked, otherwise it breaks for Visual Studio < 12 (several users have reported such issues in conancenter).
