### ISSUE TITLE
[question] Building debug config leads to missing headers in nlohmann_json package.

### ISSUE THREAD

**Issue by instinkt900** [conan-io/conan#15361]
### What is your question?

I'm not sure if this is something specific to nlohmann json, conan or perhaps my setup, but I have a minimal repro where I require a single package, nlohmann_json and a single cpp file that includes nlohmann/json.hpp and I'm using the cmake toolchain.
When I build using the release configuration it builds fine. When I build with debug I will get an error about not being able to find nlohmann/json.hpp. Is there something I'm misunderstanding about the configurations? I wouldn't have thought a large package like nlohman_json would have such an obvious config error so I'm a little confused.

Here is the setup.
conanfile.py
```
from conan import ConanFile
from conan.tools.cmake import cmake_layout

class Test(ConanFile):
	name = "test"
	version = "0.1"
	settings = "os", "compiler", "build_type", "arch"
	generators = "CMakeToolchain", "CMakeDeps"

	def requirements(self):
		self.requires("nlohmann_json/3.11.2")

	def layout(self):
		cmake_layout(self)
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.10)

project(ctest VERSION 0.1 DESCRIPTION "cmake test")

message("Building with CMake version: ${CMAKE_VERSION}")

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")

set(SOURCES ${SOURCES}
	main.cpp
)

find_package(nlohmann_json REQUIRED)

add_executable(${PROJECT_NAME} ${SOURCES})
set_target_properties(${PROJECT_NAME} PROPERTIES VERSION ${PROJECT_VERSION})
target_link_libraries(${PROJECT_NAME} nlohmann_json::nlohmann_json)
```
main.cpp
```
#include <nlohmann/json.hpp>

int main()
{
	return 1;
}
```
And I'm building using the following commands...
`conan install . --build=missing --profile=windows_profile`
`.\build\generators\conanbuild.bat`
`cmake --preset conan-default`
`cmake --build build --config Debug`

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @instinkt900 

Thanks very much for your report. And thanks for making it so good, self-contained and minimal, really appreciated, that really helps.

I have just tested it, and it works here. I suspect the problem could be that your profile is not defining ``build_type=Debug``, which it should. Please check it, try it if that is the case and let me know.

Side note: for this example, activating the ``conanbuild.bat`` is not really necessary, there are no tool-requires to activate.

**Comment by instinkt900** [comment]
Ah yes that was the problem. It feels odd to me to have to specify debug config in the profile as well as the cmake command. I'm not sure I understand what that allows you to do. I guess I'll keep two profiles around for debug and release.

**Comment by memsharded** [comment]
> It feels odd to me to have to specify debug config in the profile as well as the cmake command. I'm not sure I understand what that allows you to do. I guess I'll keep two profiles around for debug and release.

Because the ``cmake`` commands controls the build of the current projects. But ``conan install`` install the dependencies, and they can be installed as debug or release (or others) binaries. In systems like Windows this is necessary in the general case, or the linker will refuse to link, so dependencies binaries must be installed as debug, this is why ``conan install ... -s build_type=Debug`` is necessary, because this happens even before calling cmake.

I think the issue is solved and we can close the ticket? Thanks!

**Comment by instinkt900** [comment]
Yes this is solved now. Thanks.
