### ISSUE TITLE
[feature] Add some magic in AutotoolsToolchain when `tools.android:ndk_path` is set, to be consistent with CMakeToolchain & MesonToolchain

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#15376]
### What is your suggestion?

conan does some magic in `CMakeToolchain` & `MesonToolchain` when `tools.android:ndk_path` is set in profile, but not in `AutotoolsToolchain`.

Given that `AutotoolsToolchain` is by far the second most used toolchain in conancenter (used by popular libs like OpenSSL), it's confusing for users when it breaks if they use the (naive) profile recommended by conan cross-build tutorial: https://docs.conan.io/2/examples/cross_build/android/android_studio.html

See this issue for example: https://github.com/conan-io/conan-center-index/issues/22114

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Closing this as solved some time ago. The Android case is now automatically managed by AutotoolsToolchain (and GnuToolchain).
