### ISSUE TITLE
[feature] add a runtime deployer

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan#15381]
### What is your suggestion?

The purposes are:
- ease the conan 2 migration by giving an alternative to the conan import command that was removed
- be able to create an installer, by copying all the .dll into a single folder
- be able to launch the executable on windows, without using the conanrun.sh script (so that you can use the Visual Studio IDE with cmake support more easily) if you have a cmake version that do not allow you to use the cmake presets

The original request come from this PR: https://github.com/conan-io/conan-extensions/pull/94, from @memsharded

> I think, and I have been wanting to have a built-in deployer in conan for runtime (dll, exes). So I think it would be good to move this to the conan repo, and try to contribute this as a built-in:
>- Lets call it runtime_deployer
>- It should target all platform, collecting dlls, dylibs, so and executables (basically the bin folder plus some lib artifacts)
>- It should collect them "flat", all in the same folder
>- I think it should also collect licenses, in different folders so they don't overwrite

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/15382 merged, this will be in next Conan 2.5

**Comment by johan-boule** [comment]
I think it shouldn't collect everything "flat". There's a de-facto standard tree layout like bin, lib, libexec etc subdirs. Sometimes, the lib dir has a deeper hierarchy, for loadable modules, that's fine and should be preserved.
For what reason would someone want to get rid of this ? That doesn't sound to me like making it more simple to use, to the contrary, as it would deviates from standard practice and need special measures to make it usable.

**Comment by memsharded** [comment]
> I think it shouldn't collect everything "flat".

Why not? This is a multi platform deployer. In Windows, having all shared libraries DLLs in the same folder is the best approach. In fact having them in subfolders would require to add all of those subfolders to the PATH env-var, which if there are too many DLLs, it can overflow.

In any case, it is impossible that built-in deployers will suite all different and opposite needs of every user. This is the reason why deployers can be user defined easily, and that is the recommended way for most of the cases.

**Comment by johan-boule** [comment]
> > I think it shouldn't collect everything "flat".
> Why not? This is a multi platform deployer. In Windows, having all shared libraries DLLs in the same folder is the best approach.

Yes, I didn't mention that, but of course dll files are in bin dir in the package tree, so they end up in the bin dir too after deploy is called. By preserving the original layout of the package, this happens naturally without having to code any special case.

**Comment by johan-boule** [comment]
> In any case, it is impossible that built-in deployers will suite all different and opposite needs of every user. This is the reason why deployers can be user defined easily, and that is the recommended way for most of the cases.

I think a built-in deployer should be provided to support the most standard use-case, which is to preserve the original package layout, with all packages merged into the same tree. This is to support the equivalent of standard build-system install target (like make install to a system directory) or what system package managers do.
While I understand that Conan does already provide a customisation point where you can code your own deploy python function, I don't think most users find out how to do it. A ready-to-use command line is more discoverable and has less of a steep learning curve, for people who want to code C++, not python 😉

**Comment by memsharded** [comment]
Uhm, I think I partially see your point. 
An issue if that would be followed is that not all package necessarily use the ``bin``, ``lib`` conventions, this is why it is abstracted with the ``self.cpp_info.libdirs`` and ``self.cpp_info.bindirs``. It would be enough that some package puts their executable in the package root folder instead of ``bin``, and the runtime deployer will no longer work for it in Windows, because it expects to have the shared libs in the same folder as the executables.

**Comment by johan-boule** [comment]
I don't know whether Conan center has much more packages than what linux distributions have, but if an upstream package has already got some interest by a distro package maintainer, then it should have its build-system tidied up already to support proper standard packaging, otherwise there's no way it could have made it into a distro.
