### ISSUE TITLE
 [suggestion] "conan remove" command add support for removing empty recipe

### ISSUE THREAD

**Issue by didarpin** [conan-io/conan#15385]
### What is your suggestion?

I need to remove all empty recipe (has no package). I suggest adding this feature to "conan remove" command.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @didarpin 

Thanks for your suggestion.
The ``conan remove`` command already allows to remove recipes without packages:
```
$ conan remove zlib* -c
```
will remove the zlib recipes, even if they don't have binary packages

**Comment by didarpin** [comment]
@memsharded Thanks!
"conan remove zlib* -c" command remove all zlib recipes.
Maybe I didn't explain it clearly. What I mean is, only delete empty recipe, and not delete non empty recipe, This is very useful for automation.

**Comment by memsharded** [comment]
> Maybe I didn't explain it clearly. What I mean is, only delete empty recipe, and not delete non empty recipe, This is very useful for automation.

I see. There is no pattern at the moment that can be passed to ``conan remove`` that implements this logic.
What is the use case, could you please elaborate? What is the automation that you are implementing? In the any case it seems it could be easily implement in a custom command.

**Comment by memsharded** [comment]
Any further feedback here?

**Comment by memsharded** [comment]
Closing as staled. Please re-open or create new tickets for any further questions or comments.

There is no pattern that allows to remove only recipes that have no binaries. The use case for this is not very clear yet.
And if users want this logic, it should be relatively straightforward to implement it in a custom command. 

Thanks for the feedback!
