### ISSUE TITLE
[question] in a profile how to override *:shared=True only for some dependencies

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan#15387]
### What is your question?

Hi! I want to link with only shared libraries so I use `*:shared=True` in my profile. However I link to hundred of indirect dependencies and one of them depends on `abseil`, which fails with the following error: 
> Invalid: abseil/20230802.1 shared not availabe for Visual Studio (yet)

I get that some libraries may not be available as shared, so I just want to set abseil as static and keep the rest of the libraries as shared, so I tried:
```
*:shared=True
abseil/*:shared=False
```
But it does not set correctly the option for abseil. I can't list the hundred of packages one by one so how can I set the shared option for a single dependency?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fdgStilla 

I am a bit surprised about this, I think this should work correctly, and I have checked and there are tests in the test suite that covers this behavior. I have also done a quick check with openssl and zlib and seems to work fine too. Could you please provide more details to reproduce?

**Comment by fdgStilla** [comment]
I have done a test with zlib and I get the same behavior:

`conan install --requires=zlib/1.3 -of tmp -o "zlib/1.3:shared=False"`

> ======== Computing necessary packages ========
> Requirements
>     zlib/1.3#06023034579559bb64357db3a53f88a4:41ad450120fdab2266b1185a967d298f7ae52595#501d7aed51a2673c7e224633124b8398 - Cache

`conan list zlib/1.3#06023034579559bb64357db3a53f88a4:41ad450120fdab2266b1185a967d298f7ae52595` shows that the package is `shared: False`

`conan install --requires=zlib/1.3 -of tmp -o "zlib/1.3:shared=False" -o "*:shared=True"`

> ======== Computing necessary packages ========
> Requirements
>     zlib/1.3#06023034579559bb64357db3a53f88a4:ae9eaf478e918e6470fe64a4d8d4d9552b0b3606#7d5d4ec552588fb9a2a50f0672482629 - Cache

`conan list zlib/1.3#06023034579559bb64357db3a53f88a4:ae9eaf478e918e6470fe64a4d8d4d9552b0b3606` shows that the package is `shared: True`

I use Conan version 2.0.16

**Comment by memsharded** [comment]
Hi @fdgStilla 

The order is important. Patterns are evaluated in order, everything that matches is applied:

Instead of:
```bash
conan install --requires=zlib/1.3 -of tmp -o "zlib/1.3:shared=False" -o "*:shared=True"
```
you need to do:
```bash
conan install --requires=zlib/1.3 -of tmp -o "*:shared=True" -o "zlib/1.3:shared=False" 
```

Same in profiles

**Comment by fdgStilla** [comment]
Thanks for the explanation!

**Comment by fdgStilla** [comment]
And sorry I think my description was wrong, in my real scenario I use multiple "include" profile so the order was not trivial.

**Comment by memsharded** [comment]
>  And sorry I think my description was wrong, in my real scenario I use multiple "include" profile so the order was not trivial.



Not necessary to apologize! These things are often not evident, and we love to help, so don't hesitate to ask as many questions as you need!
