### ISSUE TITLE
[bug] profile detect does not try to use the compiler provided

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan#15399]
### Environment details

* Operating System+version: Ubuntu 22.04.3 LTS
* Compiler+version: Ubuntu clang version 17.0.6
* Conan version: Conan version 2.0.16
* Python version: Python 3.10.12

### Steps to reproduce

`CC=clang-17 CXX=clang++-17 conan profile detect`
I would expect it to use clang++-17 when detecting libcxx

### Logs

```
detect_api: CC and CXX: clang-17, clang++-17 
detect_api: Found clang 17.0
detect_api: clang>=8, using the major as version
detect_api: WARN: compiler.libcxx check error: /bin/sh: 1: clang++: not found
...
```

**Comment by memsharded** [comment]
Hi @Ignition 

Thanks for your report.
Yes, it seems that there could be a bug there, and the detection should be using CC/CXX defined compiler.

**Comment by memsharded** [comment]
@RubenRBS I am having a look how this could be improved:

- Breaking the ``detect_api`` interface, and make "detect_compiler" return: ``compiler, version, compiler_exe = detect_compiler()``, so we can pass the ``compiler_exe`` as optional argument to ``detect_libcxx`` and others
- Make it optional to not break with ``detect_compiler(return_compiler_exe=True)``
- Extract and re-use the logic that checks CC/CXX env-vars and call it again inside the ``detect_libcxx`` call. Not super robust, but doable

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/15418 that add new `detect_default_compiler` function.
Should be release very soon in 2.0.17
