### ISSUE TITLE
See info used to generate required package id of consumed package

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#15397]
Hello
Conan 2.0.16

I have a package A which I build and upload to my remote.
I also have package B which consumes package A (`self.requires("package_a/1.2.3")`).

When I do a "conan install..." for package B it calculates a different package id for package A than it was originally created and uploaded with thus concluding that it should actually build package A instead of downloading it.

To the best of my knowledge Packages A and B are created with matching profiles, options etc. So I'm genuinely baffled by this.

My question is thus. Is there a way where I, in the context of package B, can see the exact conaninfo that it uses to calculate the required package id for package A, so that I can match this with the actual conaninfo.txt file generated and uploaded with package A when it was created. I am not interested in the entire conaninfo.txt file for package B as such, but only the parts used to actually calculate the required package A package id.

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Yes, the commands that you are looking for are:
- ``conan list pkg/version:*`` will list the existing binaries, with a pretty printed version of ``conaninfo.txt``, which is the file that is used to compute the ``package_id`` (hashing the ``conaninfo.txt`` file, the whole of it with sha1 gives the package-id). You should be able to see the ``requires`` section in ``conaninfo.txt`` and what is hashing as dependencies. Note that package-types affect a lot to how this is computed, for example when a shared library uses a static library, it will need a new binary with a new package-id for every change in the recipe revision of the static library
- ``conan cache path pkg/version:package_id`` will give you the path to the folder containing the ``conaninfo.txt`` of the binary, if you want to fully inspect it. You can also see the file in servers like Artifactory
- ``conan graph explain`` can give you some hints about missing binaries, including dependencies mismatches.

Please let me know if this helps

**Comment by klausholstjacobsen** [comment]
Ahhh yes, `conan graph explain` was exactly what I needed. Had some discrepancies in `compiler.cppstd`!

Thanks!

**Comment by memsharded** [comment]
Happy that ``graph explain`` is proving useful! :)
