### ISSUE TITLE
conan list shows no packages

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#15398]
Hello
conan 2.0.16

I have my conan remote set-up on artifactory.
I have built many packages and uploaded thos.
When I do a `conan list xxx/0.0.0.3294@xxx/stable#*:*` is shows the recipe but no packages. 

Command:
![image](https://github.com/conan-io/conan/assets/48069914/a66d66d4-6253-4b1c-a866-15fe02d20b98)

Artifactory content:
![image](https://github.com/conan-io/conan/assets/48069914/186ebe18-0657-4955-b143-259f79318540)

Is something wrong or am I doing it wrong?

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Is it possible that those binary packages were created with Conan 1.X? Conan 1.X binaries are incompatible and "invisible" to Conan 2.0. This is a mechanism to ensure that packages from both Conan 1.X and 2.0 can coexist in the same server repository without conflict and without causing issues to the CI pipelines logic.

**Comment by klausholstjacobsen** [comment]
This particular version was created with conan 2.0.16, but there are older versions of the same package present, uploaded with conan 1.x. Could that play a role?

Regards
Klaus

**Comment by memsharded** [comment]
In principle other versions shouldn't matter, and binaries are listed not even by version, but by recipe revision inside that version. Can you please download and check the ``conaninfo.txt`` files that are inside the binary packages? If they contain ``recipe_hash``, the binaries were created with Conan 1.X, if not, with Conan 2.0, and they should be shown in ``conan list``.

Another quick check to do is use latest Conan 1.X and do a quick ``conan search pkg/version@user/channel`` in the remote, and see what happens.

**Comment by klausholstjacobsen** [comment]
conaninfo.txt:
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=9.4
os=Linux
[options]
fPIC=True
shared=False
[requires]
boost/1.72.Z
libcurl/8.4.Z
openssl/1.1.Z
pugixml/1.12.Z
zlib/1.2.Z
[python_requires]
component-dependency-info-generator/1.0.Z
dependency-info-generator/1.0.Z
```
Output from `conan search...` with conan 1.62:

![image](https://github.com/conan-io/conan/assets/48069914/cf15161d-54da-4e49-9375-3eda13d568a3)

**Comment by memsharded** [comment]
Yes, this is weird...

- Can you download with Conan 2.0 some of those binaries with ``conan download``?
- Can you install with Conan 2.0 those binaries too, with ``conan install``?

I am trying to understand if it is only the ``conan list`` or something else.
If you can clarify also about the server, just in case. Is it a "virtual" Artifactory repo? Can you try the same with a local one?

**Comment by klausholstjacobsen** [comment]
`conan download...` works fine:
![image](https://github.com/conan-io/conan/assets/48069914/23f665bd-fe3f-4369-bca8-83de4cf76b3b)

`conan install...`also work!

**Comment by memsharded** [comment]
Damn it! 😅 

So it seems:
- The packages are there
- The packages are Conan 2.0 packages
- Conan can install and download them
- But ``conan list`` is not showing them

> If you can clarify also about the server, just in case. Is it a "virtual" Artifactory repo? Can you try the same with a local one?

I cannot see anything on the client side causing this behavior at this moment, so we might need to check if it could be a server issue:
- Can you please confirm if this is an Artifactory virtual repo?
- Which Artifactory version? This can be important
- As the virtual will be aggregating a local that actually contain the packages, can you test against the local repo?

**Comment by klausholstjacobsen** [comment]
I can confirm that this is indeed an artifactory virtual remote.
Artifactory version 7.49.5
When browsing artifactory I can confirm that the package is present in the local repo as well as the virtual repo as expected.

When running `conan list...`directly on the local repo I do however get a different response saying `WARN: There are no matching recipe references`.

Regards
Klaus

**Comment by memsharded** [comment]
Ok, there are some issues with Artifactory older than 7.52, please check the release notes:

https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.52 

This means that certainly some operations can work (like ``install``), but others as listing might fail. In the traces of Artifactory there might be some internal errors. This also might affect how virtual repos interact with local ones. 

I'd strongly suggest to update Artifactory  to solve this issue.

**Comment by klausholstjacobsen** [comment]
Thank you for your advise.
I will close this for now as several weeks can pass before I get a chance to update our Artifactory server.
If the error persist then, I will re-open!

**Comment by memsharded** [comment]
Sure, looking forward your feedback when you update the server, thanks!
