### ISSUE TITLE
[feature] Automatically detect compiler toolchain during `conan install`

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#15405]
### What is your suggestion?

Hi! I would like `conan install` to automatically find the default C/C++ compiler toolchain provided by my environment. Instead of having to specify the toolchain when provisioning conan projects.

I have published portable C/C++ projects that use conan to acquire my library dependencies. However, conan's need to be explicitly told the compiler toolchain version, adds friction when supporting different environments. Whether my contributors arrive from Windows, macOS, or another UNIX environment, forces different `conan install` flags to be specified. It's harder to share provisioning steps when they're OS specific.

This also clutters CI/CD pipeline automation.

I think the existing flags would be fine for *overriding* the default toolchain. But ultimately I'd like for conan to take reasonable steps, like cmake, and autodetect at least one common C/C++ toolchain if the cc/c++ commands or an MSVC environment variable are found.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by valgur** [comment]
While I would not mind support for this feature as part of Conan itself, you can more or less already achieve this with [`cmake-conan`](https://github.com/conan-io/cmake-conan) if your project is using CMake.
For a more complete example I can recommend one of my existing public projects as a reference: https://github.com/valgur/novatel_edie/blob/main/cmake/third_party.cmake

**Comment by memsharded** [comment]
Hi @mcandre 

> Whether my contributors arrive from Windows, macOS, or another UNIX environment, forces different conan install flags to be specified. It's harder to share provisioning steps when they're OS specific.

What do you mean by ``flags``? Conan is able to auto-detect (without strong guarantees of stability) the default profile in most systems. In Conan 2.0 this is done with ``conan profile detect``, and then such profile is the one that is used by default by every ``conan install`` command without adding any extra flags, so this would be already an existing feature?

It is important to note that Conan will not couple in any case the auto-detection to the ``conan install`` command, these will be separate steps. It is very important to keep separation of concerns, given that auto-detection can't be always perfect and coupling would create unreasonable expectations. But the profile detection seems to be what you are asking for?

If you could please clarify a bit it, that would help.

**Comment by memsharded** [comment]
Any further feedback here @mcandre?
