### ISSUE TITLE
[question] MSBuildDeps generator for custom configurations

### ISSUE THREAD

**Issue by schoetbi** [conan-io/conan#15417]
Sorry for this rather lengthy issue but the context is probably needed to solve my problem.

## Context

I am currently using Visual Studio for my project that uses RTX. Previously I used Conan(1) and want to migrate to Conan2. Conan1 worked fine for me.

> RTX is a Real-Time Operating System (RTOS) extension for the Microsoft Windows operating system, developed by IntervalZero. It allows developers to run real-time tasks directly on the Windows platform, which is typically not a real-time operating system.

I have set up 6 different Solution Configurations:

1. Debug
2. Release
3. RtssDebug
4. RtssRelease
5. WinDebug
6. WinRelease

Each of these configurations serves a specific purpose, as outlined in the table below:

| Target Name | Purpose |
| --- |--- |
| Debug | Debug build for Windows. Executables can run under windows and are able to access the RTX objects like shared memory |
| Release | Release build for Windows. Executables can run under windows and are able to access the RTX objects like shared memory |
| RtssDebug | Debug build for RTX. Executables run under RTX and have to be started with `rtssrun <executable>.rtss` |
| RtssRelease | Release build for RTX. Executables run under RTX and have to be started with `rtssrun <executable>.rtss` |
| WinDebug | Debug build for Windows. Executables can run under windows but can not access RTX objects |
| WinRelease | Release build for Windows. Executables can run under windows but can not access RTX objects |

The projects within this solution have the same set of configurations. Therefore, the msbuild variable `$(Configuration)` is set to one of the above values.

The different configurations have the effect that the in the Rtss... configurations the symbols that are normally satisfied by the kernel32.lib are satisfied by RTX libraries that call into the real-time kernel.

## Usage of Conan1

Under Conan1, I created the prop files with the `visual_studio_multi` generator.

```powershell
conan install . --profile conanprofile.txt -s build_type=Debug   -s compiler.runtime=MTd -s ACE:build_type=RtssDebug    -r artifactory_local -if conan/RtssDebug
```

As you see I was able to switch the build type of ACE to `RtssDebug` which is a custom build type that I have defined in Visual Studio. It seems to me that this approach does not work with Conan2 anymore. Question: Is this correct?

## Usage of Conan2

To support these different build types, I now use an option to switch the runtime library of ACE. The option is called `runtime` and can be set to `win_only`, `rtx` or `win_rtss`.

To build prop files for the RtssDebug case, I start conan with a call like this:

```powershell
conan install . --profile conanprofile.txt -s compiler.runtime=static -s build_type=Debug -o ace/*:runtime=rtx -of conan/RtssDebug --build=missing
```

## Generation of prop files

The generator `MSBuildDeps` generates one main prop file called `conandeps.prop` where each of my dependencies are imported.

Here is an example with only one dependency to boost:

```xml
<?xml version="1.0" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
 <ImportGroup Label="PropertySheets"> 
  <Import Condition="'$(conan_boost_props_imported)' != 'True'" Project="conan_boost.props"/>  
 </ImportGroup>
</Project>
```

The file `conan_boost.props` looks like this:

```xml
<?xml version="1.0" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
 <ImportGroup Label="PropertySheets">
  <Import Condition="'$(conan_boost_headers_props_imported)' != 'True'" Project="conan_boost_headers.props"/>
        <!-- ... -->  
 </ImportGroup>
 <PropertyGroup>
  <conan_boost_props_imported>True</conan_boost_props_imported>
 </PropertyGroup>
</Project>
```

Then the file `conan_boost_headers.props` looks like this:

```xml
<?xml version="1.0" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
 <ImportGroup Label="PropertySheets">
  <Import Condition="'$(Configuration)' == 'Debug' And '$(Platform)' == 'x64'" Project="conan_boost_headers_debug_x64.props"/>
 </ImportGroup>
 <PropertyGroup>
  <conan_boost_headers_props_imported>True</conan_boost_headers_props_imported>
 </PropertyGroup>
</Project>
```

## Problem

When I build my project with the configuration `RtssDebug` the property sheet `conan_boost_headers_debug_x64.props` is not imported. This is because the condition `$(Configuration) == 'Debug'` is not met. The same is true for the other configurations `RtssRelease`, `WinDebug` and `WinRelease`.

## What I have considered

It would be possible to include the files like `conan_boost_headers_debug_x64.props` one by one into a props file and include this in my projects. But this would duplicate the information of what dependencies are used in my project.

Then I thought about using a custom generator that generates the property sheets that I need without the condition like `$(Configuration) == 'Debug'`.

## Question

My hope is that I am making a big mistake on how to use conan and that there is a better way to solve this problem. I am open to any suggestions.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @schoetbi 

Thanks for your question.

> I am currently using Visual Studio for my project that uses RTX. Previously I used Conan(1) and want to migrate to Conan2. Conan1 worked fine for me.

The first important point is that the ``MSBuildDeps`` generator is not exclusive of Conan2, but it has existed for years in Conan1. The recommendation and migration guidelines are to move to ``MSBuildDeps`` first in Conan1, and then upgrade to Conan2.

Let's see if we can figure out the issue anyway, let me try to understand the setup.

> To support these different build types, I now use an option to switch the runtime library of ACE. The option is called runtime and can be set to win_only, rtx or win_rtss.

Why did you change this? For ``settings`` the recommendation is to keep using the per-package settings, not options. Conan will use the ``build_type`` setting inside generators like ``MSBuildDeps`` to define logic.

I think this could be the root issue. There can be ways to customize the ``configuration`` in the recipe based on options, but I'd like to understand this first.

**Comment by schoetbi** [comment]
Hi @memsharded,

in my configuration only one package (ace) has all the build_types as the main application (RtssDebug, RtssRelease, WinDebug, WinRelease). All other packages have only the build_types `Debug` and `Release`.

I had created the props files previously with this conan call:

```ps
conan install . --profile conanprofile.txt -s build_type=Debug   -s compiler.runtime=static  -s ace/*:build_type=RtssDebug -of conan/RtssDebug
```

The prop files gets created, but still in the property file for e.g. boost (`conan_boost_headers.props`) there is still the condition `$(Configuration) == 'Debug'` which is not met in my case. All of my projects "inherit" the solution configuration (RtssDebug in this case), so the condition is not met (`'RtssDebug' == 'Debug'`)

I also have another question regarding this. In the command line I use the option `-s ace/*:build_type=RtssDebug`. Is it possible to set this also in the `conanfile.py`?

**Comment by memsharded** [comment]
> in my configuration only one package (ace) has all the build_types as the main application (RtssDebug, RtssRelease, WinDebug, WinRelease). All other packages have only the build_types Debug and Release.

If I understand correctly the issue, then the right syntax will be:
```
conan install . ... -s build_type=Debug  -s ace/*:build_type=RtssDebug -s &:build_type=RtssDebug
```
The ``&`` means "the consumer application", I understand this is what you mean with "main application", the one that is built with the ``conanfile`` that the ``conan install .`` is installing. Isn't it?

As a UX improvement you can make your main application ``conanfile`` a ``conanfile.py``, give it a ``name = "mainapp"`` and then define in your ``conanprofile.txt``:
```
[settings]
build_type=Debug
mainapp/*:build_type=RtssDebug
ace/*:build_type=Debug
```
Or you might as well define things in your ``profile.py`` plugin, making it automatic to deduce some settings dynamically based on other input settings.

Please let me know if this helps.

> I also have another question regarding this. In the command line I use the option -s ace/*:build_type=RtssDebug. Is it possible to set this also in the conanfile.py?

No, values for settings can only be defined in:
- command line
- profiles
- ``profile.py`` plugin

The reason they cannot be defined in recipes is because when those recipes participate in a graph, then all the problems of propagation of settings upstream, conflicts (when 2 branches of the graph try to define different settings), visibility of dependencies effect on propagation, etc, appear. We have this experience already with ``options``, and it is too problematic to generalize this to ``settings`` too.

**Comment by schoetbi** [comment]
Hi @memsharded,

thanks for pointing out to set the `build_type` of the consumer application. I have tried this and it works. I did not know that this is possible. Maybe you can point me to the documentation where this is explained? I was not able to find it.

The UX improvement is also a good solution, but I almost always need to build all the different configurations. So I would have to define a profile for each of the configurations. I think I will stick with the command line option for now.

Thanks,
Tobias

**Comment by memsharded** [comment]
> Maybe you can point me to the documentation where this is explained? I was not able to find it.

It is not explicit about build-type, but the ``&`` syntax is introduced here: https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns. Maybe we need to add more examples in other parts of the docs too


> The UX improvement is also a good solution, but I almost always need to build all the different configurations. So I would have to define a profile for each of the configurations. I think I will stick with the command line option for now.

Ok, but please keep in mind that profiles jinja template syntax, profile composition, profile plugin, etc are useful features that can automate that when you need, just open a new ticket when needed.

**Comment by schoetbi** [comment]
Thanks for pointing me to the docs. I definitely will look into the jinja template syntax it seems to be very powerful.
