### ISSUE TITLE
[feature] set jobs parameter in CMakePreset buildPresets to get parallel builds when invoking cmake after conan install

### ISSUE THREAD

**Issue by Hailios** [conan-io/conan#15419]
### What is your suggestion?

the generated CMakePresets.json does not contain the "jobs" parameter, making it default to 1 (at least sometimes).
when manually set to a higher number, the cmake build command builds in parallel as expected.
it would be good if Conan could set this parameter while generating the preset file(s).

example "buildPresets" section before this feature is implemented:
```
    "buildPresets": [
        {
            "name": "conan-relwithdebinfo",
            "configurePreset": "conan-relwithdebinfo"
        }
    ],
```

example "buildPresets" section with the proposed feature:
```
    "buildPresets": [
        {
            "name": "conan-relwithdebinfo",
            "configurePreset": "conan-relwithdebinfo",
            "jobs": 16
        }
    ],
 ```
 
 this allows cmake to be invoked as follows, `cmake --build --target all --preset conan-relwithdebinfo` and have it build in parallel (much faster).
 

 the issue was observed on Ubuntu 23.10
```
 $ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```

Conan version 2.0.14
cmake version 3.27.4

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Hailios 

Thanks for your suggestion.
I think this could make sense, might be doable, I'll check with the team.
