### ISSUE TITLE
[question] why is generate() executed during conan export-pkg?

### ISSUE THREAD

**Issue by iaavo** [conan-io/conan#15426]
### What is your question?

Is there a reason on why `generate()` is being executed during `conan export-pkg`?
My understanding is that the `conan export-pkg` command can be used in the context of:
```bash
conan install .
make
conan export-pkg .
```
since `conan install .` already runs the generators I don't see why they need to be run again during `conan export-pkg .`

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @iaavo 

Thanks for your question.

The ``conan export-pkg`` command is also used without a previous ``conan install``, specifically for those cases that do not require building from source, but they just do package some existing pre-compiled binaries, like for a closed-source vendor.

Then, for example, the recipe can still have some ``tool_requires`` and those can still be used in the ``package()`` method (imagine the closed source vendor distributes a .7z and we want to use the ``7zip`` Conan package tool-require to unzip it in the ``package()`` method). It is necessary that the tool-requires are used in the generators to create the environment scripts that will make those tool-requires available in the ``package()`` method. Thus, it cannot be assumed that the users will run a previous ``conan install`` before.

**Comment by memsharded** [comment]
Was this clarified @iaavo ? Maybe we can close this ticket? Thanks!

**Comment by iaavo** [comment]
Ah sorry, yes it is clarified. Thanks for the quick reply!
