### ISSUE TITLE
Recipe 'bzip2/1.0.8' cannot build its binary

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#15420]
### What is your question?

Since yester day I am trying to build boost and I keep getting errors for bzip2 and zlib. Has something changed? Below is the error:

> -------- Installing package bzip2/1.0.8 (2 of 4) --------
> bzip2/1.0.8: Building from source
> bzip2/1.0.8: Package bzip2/1.0.8:bf4baf0dcdc1c7941cf842f390e9b276b15ca608
> bzip2/1.0.8: Copying sources to build folder
> bzip2/1.0.8: Building your package in C:\Users\myuser\.conan2\p\b\bzip2164e34b3a1d23\b
> bzip2/1.0.8: Calling generate()
> bzip2/1.0.8: Generators folder: C:\Users\myuser\.conan2\p\b\bzip2164e34b3a1d23\b\build\generators
> bzip2/1.0.8: CMakeToolchain generated: conan_toolchain.cmake
> bzip2/1.0.8: CMakeToolchain generated: CMakePresets.json
> bzip2/1.0.8: Generating aggregated env files
> bzip2/1.0.8: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
> bzip2/1.0.8: Calling build()
> bzip2/1.0.8: apply_conandata_patches(): No patches defined in conandata
> bzip2/1.0.8: Running CMake.configure()
> bzip2/1.0.8: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/myuser/.conan2/p/b/bzip2164e34b3a1d23/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/myuser/.conan2/p/b/bzip2164e34b3a1d23/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\myuser\.conan2\p\b\bzip2164e34b3a1d23\b\src\.."
> 'cmake' is not recognized as an internal or external command,
> operable program or batch file.
> 
> bzip2/1.0.8: ERROR:
> Package 'bf4baf0dcdc1c7941cf842f390e9b276b15ca608' build failed
> bzip2/1.0.8: WARN: Build folder C:\Users\myuser\.conan2\p\b\bzip2164e34b3a1d23\b\build
> *********************************************************
> Recipe 'bzip2/1.0.8' cannot build its binary
> It is possible that this recipe is not Conan 2.0 ready
> If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
> If it is your recipe, check if it is updated to 2.0
> *********************************************************
> 
> ERROR: bzip2/1.0.8: Error in build() method, line 63
>         cmake.configure(build_script_folder=os.path.join(self.source_folder, os.pardir))
>         ConanException: Error 1 while executing

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

It seems the error message is:

> 'cmake' is not recognized as an internal or external command,

So not related to the recipe, maybe something changed in your computer?
- Do you have cmake installed and available in the sytem path? 
- can you run ``cmake --version`` in your terminal before running the Conan command?

Please also report:
- The Conan version
- The OS/platform

**Comment by sandybhat16** [comment]
@memsharded Thanks. That was so silly, Yesterday I had uninstalled and for to reinstall. Thanks again!

**Comment by memsharded** [comment]
Good, happy this one was easy to help 🙂
