### ISSUE TITLE
[question] does conan generate *.cmake files for the whole dependency tree? 

### ISSUE THREAD

**Issue by OlegWorld** [conan-io/conan#15421]
### What is your question?

I've got a problem:
I am building a conan package with my own library. Let us call it MyLib. MyLib depends on a header-only package. Let us call it MyHeader.
Ok, MyLib is built using Cmake, the unit-tests are Ok. But the test-package step of MyLib is failing because the compiler can't find includedir of MyHeader, although it is specified in MyHeader conanfile an is correctly used during MyLib build step. In the test-package generators folder I see only MyLib-config.cmake files and no files, corresponding to MyHeader. MyLib_FIND_DEPENDENCY_NAMES variable is empty and MyHeader is never mentioned in the MyLib-*.cmake files. 
On the other hand, the generate(self) method in the conanfile sees MyHeader dependency as indirect...
Is all that Ok? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @OlegWorld 

Thanks for your question.
I am assuming that you are using Conan 2.0

It is possible that the requirement from ``mylib``->``myheader`` is missing some specification.
If the public headers of ``mylib`` include headers from ``myheader`` and it is not an implementation detail (used only in .cpp files), the the requirement should be specified as:

```python
def requirements(self):
    self.requires("myheader/1.0", transitive_headers=True)
```
To make it available in the consumer (in this case, the consumer is the ``test_package``, but it could be just another regular package with a requires to ``mylib``

Please let me know if this helps

**Comment by OlegWorld** [comment]
Thanks a lot. It really helped!

**Comment by memsharded** [comment]
Great to know!
So it is working now? Maybe we can close the ticket? Thanks!

**Comment by memsharded** [comment]
Closing as responded, but please don't hesitate to re-open or create new tickets for any further questions. Thanks for your feedback.
