### ISSUE TITLE
It is not possible to return error codes from a recipe

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#1542]
I am trying to return a specific code from a recipe in the case a platform is not supported. Let's say that I know that one recipe is not supposed to be compatible with Mac. In that case I want to return an expected code `X`. If I do in the conan recipe:
```
sys.exit(X)
```
And then I check in a bash terminal the returned value:

```
conan test_package ...
echo $?
```
The value that I obtain is always `1` . It seems that `sys.exit()` raises the `SystemExit` exception and conan is caching all the exceptions.

Is there a way in conan to return a specific value ?
Would be this a interesting feature to have for you?

Cheers!

**Comment by memsharded** [comment]
I think this feature might be interesting, but in a controlled way:

- Not using ``sys.exit()``, it doesn't look very clean
- Maybe use some ``ConanExitException`` that can take an integer code and a message
- Capture this exception the first in command.py -> Command.run

What is your use case? I mean, you can already raise an Exception with your own message. 
Are you doing something different in your CI for such specific code X? I guess once the system has failed, it requires manual intervention. I am very curious :)

Please tell me, I think this feature is easy and could be added to 0.26.

**Comment by piponazo** [comment]
My use case is the following:

We have a Jenkins job dedicated to generate conan packages for a specific recipe. Any developer can provide : 

- Address to a git repository containing a conan recipe.
- Name of the branch to clone.
- Name of the channel to which the package will be uploaded in case of a successful build.

That jenkins job is a multi-configuration job with a matrix of `platforms` (linux, mac, win) , `compilers` (clang, gcc, msvc) and `modes` (release, debug). 

Some of the recipes that we are writing cannot be generated in some systems. For example, some libraries using CUDA will not be compiled on Mac (Mac computer do not have Nvidia cards currently). 
We would like to skip the generation of packages for these platforms in a controlled way (for example, checking a return code from the **conan** command). Then the jenkins job will check the following:

1. Return code from conan command = 0 --> upload recipe to conan server & show green status 
2. Return code from conan command = 1 --> error while generating the package & show red status
3 Return code from conan command = X --> skip package & show green or yellow status

**Comment by piponazo** [comment]
For the moment I added in the recipes a field `skip = 'X, Y'` where I list the platforms in which I want to skip the generating of the package. Then in the jenkins job I add some bash commands to do the magic.

However this was only a workaround. Since in the C/C++ world there are many libraries and tools that are not cross-platform, I think it would have sense to consider those cases in conan.

**Comment by memsharded** [comment]
Ok, got it, very interesting your setup!

> Since in the C/C++ world there are many libraries and tools that are not cross-platform, I think it would have sense to consider those cases in conan.

Yes, agree, the current approach right now is just to raise an Exception with the message, but didn't think about the returned error code being useful for that.

Lets make it for 0.26 then.
