### ISSUE TITLE
[question] How to access an executable target from CMake?

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#15423]
### What is your question?

Hello,

I am using conan 2.0.16

In my project's recipe (let's call it A), I have a `tool_requires` on another project of mine (let's call it B). B produces two executables:
- The first one takes a set of files in input. This set is combination of some from A & B. From them, it generates headers files
- The second only takes a set of files from B and generates a .bin file

These two executables must be called before A's building process.

So far, I've been doing the following in A's recipe. It works great:
```python
def generate(self):
	B = self.dependencies["B"]
	configuration = f"{self.build_folder}/configuration"
	copy(self, "*", src=B.cpp_info.components["FilesForHeaders"].resdirs[0], dst=f"{configuration}")
	copy(self, "*", src=os.path.join(self.recipe_folder, "FilesForHeaders"), dst=f"{configuration}")
	ct = CMakeToolchain(self)
	ct.generate()
	cd = CMakeDeps(self)
	cd.generate()

def build(self):
	bin_input = (self.dependencies["B"]).cpp_info.components["FilesForBin"].resdirs[0]
	configuration = f"{self.build_folder}/configuration"
	self.run(f"bin_generator -i {bin_input} -o {configuration}/my_file.bin")
	self.run(f"header_generator -i {configuration} -o {configuration}/include")
	cmake = CMake(self)
	cmake.configure()
	cmake.build()
```

Now:
- Is it possible to move these copies from the `generate()` method to a CMake equivalent?
For example by doing:
```cmake
file(COPY B::FilesForHeaders DESTINATION "${CMAKE_BINARY_DIR}/configuration")
file(COPY "${CMAKE_SOURCE_DIR}/FilesForHeaders" DESTINATION "${CMAKE_BINARY_DIR}/configuration")
```

- Similar questions regarding `build()`'s generations. Is it possible to access B's executables and files targets to do the following:
```cmake
add_custom_target(GENERATE_REQUIREMENTS ALL
	COMMAND B::bin_generator -i B::bin_input -o ${CMAKE_BINARY_DIR}/configuration/myfile.bin
	COMMAND B::header_generator -i "${CMAKE_BINARY_DIR}/configuration" -o "${CMAKE_BINARY_DIR}/configuration/include"
)
```

- If so, do I have to edit some others cpp_info (other than `resdir`), or do I need further editing through `set_property()` of cmake properties?

Thanks in advance

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your question.

I think that trying to move the logic from Python to CMake as you are suggesting would be a bit complicated and messy. The information is in the recipe, you would need to convert it to CMake variables or something that your ``CMakeLists.txt`` can later execute. This could be easy for folders.

But for executables there are no targets created. But they are not needed, they are directly in the PATH, so they can execute by name easily, without running them by target. You can do a ``find_program()`` if you want to, but as they are already in the path that is also unnecessary.

If for some reason it was completely necessary to do it from CMake, I'd try a different approach. I'd try to create some ``b_tools.cmake`` file with macros you can reuse, in the B package. These macros or functions take arguments. Putting this file in the ``self.cpp_info.builddirs = ["somefolder"]`` folder, will make it available to the consumer, that can include it. The idea is that the consumer would look like:

```cmake
include(b_tools.cmake)
generate_my_bin(some_local_folder_args)
generate_my_headers(some_other_local_folder_args)
```
this way you might completely avoid having to copy things, you can use files directly from B (as long as you don't modify them), and output generated files to the local A folders.

**Comment by Todiq** [comment]
Hello,

This explanation is cristal clear, hence closing the ticket. In the end, I've been doing everything from the recipe, but might give it another shot at some point.

Many thanks!

**Comment by memsharded** [comment]
Happy to help!
