### ISSUE TITLE
[question] Checking for requirements on a remote

### ISSUE THREAD

**Issue by h-2** [conan-io/conan#15424]
### What is your question?

Hi, I'd like to check if all of a package's requirements are available on a remote without downloading and unzipping them all.

Is something like this possible?

This could be implemented as dry-run option for `conan install`, e.g. `conan install --dry-run --remote artifactory` would check the conanfile for all dependencies and check whether corresponding recipes are available on the remote. If additionally `--build=never` is specified, it would check whether matching binary packages are also available to satisfy the requirements.

But it could also be implemented as e.g. `conan search --remote artifactory --from-file conanfile.txt` or something similar. 

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @h-2 

Thanks for your question.

Yes, the ``conan graph info`` command does exactly this, it constructs the dependency graph (downloading only the minimum necessary to construct the graph, just the recipes, but not the heavy binaries), and it allows to compute what packages are existing, what packages need to be built, etc.

Furthermore, the ``conan graph build-order`` behaves similarly, but already gives a list of lists of packages to build in the right order, so the packages build can be distributed and parallelized in build agents farm.

**Comment by h-2** [comment]
Nice, this is almost exactly what I was looking for!

It handles missing recipes correctly by saying
```
ERROR: Package 'foo/1.0' not resolved: Unable to find 'foo/1.0' in remotes.
```
And returning non-zero.

But it does not handle missing binary builds correctly when using `--build=never`. I have just removed `libcurl` from our artifactory and tested this.

With `--build=missing`, it correctly identifies the package as being "to-be-built":

```
...
libcurl/8.2.1#129c2b4eed0a8dfb132f315b9a89b6d6:c6375462bd0a10aa29f96db84768102912a1bac1 - Build
...
```

And with `--build=never`, it correctly identifies the package as being "missing":

```
libcurl/8.2.1#129c2b4eed0a8dfb132f315b9a89b6d6:c6375462bd0a10aa29f96db84768102912a1bac1 - Missing
```
However, it still returns 0, which makes the command not usable as a "dry-run" for install, because the respective install command would fail.

Is this a bug or is there some way I can make the command fail if a package is missing?

**Comment by memsharded** [comment]
> However, it still returns 0, which makes the command not usable as a "dry-run" for install, because the respective install command would fail.

No, the ``graph info`` returns successfully if it is able to compute the dependency graph, and missing binaries is not considered an error, because the graph is correct. The general rule we use in Conan to return non-0 is that if the command is not able to finish successfully, then it raise an exception and return not 0. If it is able to compute successfully the result, even if the result says that there are missing binaries or a conflict, then the command succeeded and the result is 0.
The idea is that you can very easily check the output in your CI, for example with ``jq`` you can check the json output for ``Missing`` binaries and act accordingly. 

Why do you want to use it as a dry-run, if it succeed you are doing a ``conan install``, why not doing the ``conan install`` directly in the first place?

**Comment by h-2** [comment]
> If it is able to compute successfully the result, even if the result says that there are missing binaries or a conflict, then the command succeeded and the result is 0.

I see.

> Why do you want to use it as a dry-run, if it succeed you are doing a conan install, why not doing the conan install directly in the first place?

That's not how it is supposed to work here. I have one CI action that is "make sure we have all dependencies" and one CI action that is "build app".
In the "make sure we have all dependencies", I currently do a `conan install --build=missing` followed by a `conan upload` to our artifactory. 
The "build app" action is not supposed to build any depdencies (`--build=never`).

Now obviously the "make sure we have all dependencies"-step is needlessly pulling and unpacking all those dependencies most of the time. That's why I would like to check if `conan install` and `upload` are necessary at that point at all.

Of course, I can parse the output, but I thought there might have been an easier way to "check if we have all deps on remote".

**Comment by memsharded** [comment]
> Now obviously the "make sure we have all dependencies"-step is needlessly pulling and unpacking all those dependencies most of the time. That's why I would like to check if conan install and upload are necessary at that point at all.

Ok, now I understand, it makes sense if you are using those 2 separate steps.

I think then I'd definitely recommend the ``jq`` command. It can most likely get you the result from the json in a oneliner without having to parse it at all.

I have also seen users caching the Conan cache between jobs, so a ``conan install --build=missing --update`` most likely can be quite efficient, even improving your previous flow performance.

As another potential idea, a bit of abuse but it can probably work conveniently is to define your own ``deployer`` and pass it to the ``conan graph info ... --deployer=check_missing``. Most likely that deployer is just 4-5 lines. Still the ``jq`` solution reads more well suited to the problem IMO.

**Comment by h-2** [comment]
> I think then I'd definitely recommend the jq command. It can most likely get you the result from the json in a oneliner without having to parse it at all.

Yeah, I managed to extract it with `jq '[.[]|.[]|.["packages"]|.[]|.[]|.["binary"] == "Missing"]|any'` although it's probably not the most elegant way.

If you ever think about creating a built-in flag for this, let me know :)

> I have also seen users caching the Conan cache between jobs,

We had that previously, but developers are supposed to use the artifactory, as well, so it's good to have CI test everything.

**Comment by memsharded** [comment]
> If you ever think about creating a built-in flag for this, let me know :)

I will, thanks for the feedback! 🙂
