### ISSUE TITLE
[question] [conan 1.59] :  Build errors in my application build from abseil conan package

### ISSUE THREAD

**Issue by honey-speaks-tech** [conan-io/conan#15428]
### What is your question?

Hello, 
I am getting the following build errors in my application build from abseil conan package. Our application is based on C++14.
![image](https://github.com/conan-io/conan/assets/2928745/2c81bf26-08fc-48b2-b56b-50ef211d9a5e)

From abseil source code, I understand this will happen only if `ABSL_USES_STD_VARIANT` is defined. See screenshot below.
![image](https://github.com/conan-io/conan/assets/2928745/2a22c67a-014d-4f50-a6d5-726e8a93ae75)

My conan file looks like something below. 

```
class AppConan(ConanFile):
    name = "app"
    description = "Application"
    settings = "os", "compiler", "build_type", "arch"
    requires = (
        "gtest/[1.8.x]",
        "fmt/[8.x]",
       ....
        "abseil/20230802.1"
```

Could some one guide me how can I resolve this issue? Do you think using bincrafters package would help?
Looking forward to hearing from you soon.

@memsharded @RubenRBS I would appreciate your valuable thoughts on my above issue.

Thanks,
Honey

Honey Sukesan

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by uilianries** [comment]
Hello @honey-speaks-tech! Could you please share more information, for what are you sharing, it's really hard to understand your scenario.

Plus, please, avoid screenshots and only share raw text, they are easier to read and parse in case need to search some keyword.

#### Package and Environment Details
* Operating System+version:
* Compiler+version:
* Python version:

#### Conan profile

example:
```
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

#### Steps to reproduce

> Did you run which conan commands?


I can confirm the Conan recipe for abseil does **not** set `ABSL_USES_STD_VARIANT`, the current recipe can be found here:

https://github.com/conan-io/conan-center-index/blob/master/recipes/abseil/all/conanfile.py

Plus, the upstream does not enforce it, you need to pass manually:

https://github.com/search?q=repo%3Aabseil%2Fabseil-cpp%20ABSL_USES_STD_VARIANT&type=code

Taking a look closer into your log, it shows `clang-diagnistic-error`. It seems be a clang-tidy error, nothing related to the package itself. If it's the case, please, take a look how to ignore that error from the linter: https://stackoverflow.com/questions/50355930/ignore-clang-diagnostic-error-clang-tidy-caused-by-3rd-party-headers

**Comment by honey-speaks-tech** [comment]
Hello @uilianries Thank you very much for the response. Here is more information.

_Package and Environment Details
Package Name/Version: abseil/20230802.1
Operating System+version: Linux Ubuntu 22.04
Conan version: conan 1.59.0_

Conan profile
```
[settings]
compiler.libcxx=libstdc++11
cppstd=gnu14
arch=x86_64
build_type=Release
compiler=gcc

[conf]
tools.cmake.cmaketoolchain:user_toolchain=['$PROFILE_DIR/../../toolchain/clang-tidy.cmake']
```

Steps to reproduce
Probably build an application using abseil package. I don't know for sure how to reproduce.

Logs
```
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:54:12: error: no member named 'bad_variant_access' in namespace 'std' [clang-diagnostic-error]
using std::bad_variant_access;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:56:12: error: no member named 'get_if' in namespace 'std' [clang-diagnostic-error]
using std::get_if;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:57:12: error: no member named 'holds_alternative' in namespace 'std' [clang-diagnostic-error]
using std::holds_alternative;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:58:12: error: no member named 'monostate' in namespace 'std' [clang-diagnostic-error]
using std::monostate;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:59:12: error: no member named 'variant' in namespace 'std' [clang-diagnostic-error]
using std::variant;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:60:12: error: no member named 'variant_alternative' in namespace 'std' [clang-diagnostic-error]
using std::variant_alternative;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:61:12: error: no member named 'variant_alternative_t' in namespace 'std' [clang-diagnostic-error]
using std::variant_alternative_t;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:62:12: error: no member named 'variant_npos' in namespace 'std' [clang-diagnostic-error]
using std::variant_npos;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:63:12: error: no member named 'variant_size' in namespace 'std' [clang-diagnostic-error]
using std::variant_size;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:64:12: error: no member named 'variant_size_v' in namespace 'std' [clang-diagnostic-error]
using std::variant_size_v;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:65:12: error: no member named 'visit' in namespace 'std' [clang-diagnostic-error]
using std::visit;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/types/variant.h:859:16: error: no member named 'visit' in namespace 'absl' [clang-diagnostic-error]
return absl::visit(variant_internal::ConversionVisitor{},
~~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/utility/utility.h:164:12: error: no member named 'in_place_t' in namespace 'std' [clang-diagnostic-error]
using std::in_place_t;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/utility/utility.h:165:12: error: no member named 'in_place' in namespace 'std' [clang-diagnostic-error]
using std::in_place;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/utility/utility.h:181:12: error: no member named 'in_place_type' in namespace 'std' [clang-diagnostic-error]
using std::in_place_type;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/utility/utility.h:182:12: error: no member named 'in_place_type_t' in namespace 'std' [clang-diagnostic-error]
using std::in_place_type_t;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/utility/utility.h:198:12: error: no member named 'in_place_index' in namespace 'std' [clang-diagnostic-error]
using std::in_place_index;
~~~~~^
/root/.conan/data/abseil/20230802.1///package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include/absl/utility/utility.h:199:12: error: no member named 'in_place_index_t' in namespace 'std' [clang-diagnostic-error]
using std::in_place_index_t;
```

**Comment by honey-speaks-tech** [comment]
Regarding:

> Taking a look closer into your log, it shows clang-diagnistic-error. It seems be a clang-tidy error, nothing related to the package itself. If it's the case, please, take a look how to ignore that error from the linter:

Please see the response I got from llvm github [here](https://github.com/llvm/llvm-project/issues/77109)
They said to fix the errors. :(

Please let me know if any more information is required.

Thanks,
Honey

**Comment by uilianries** [comment]
@honey-speaks-tech Are you really using GCC, and which version? Please, share your entire conan profile, some information is missing.

Plus, clang-tidy is a tool, so you should ignore it for external dependencies as you are not the maintainer. You should run it only over your project folders.

**Comment by honey-speaks-tech** [comment]
I have pasted the entire conan file above. But as you hinted, I have made a few more modifications just now. Here is it.
```
[settings]
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
cppstd=gnu14
arch=x86_64
build_type=Release
os_build=Linux
os=Linux

[conf]
tools.cmake.cmaketoolchain:user_toolchain+=['$PROFILE_DIR/../../toolchain/clang-tidy.cmake']
```

My latest `clang-tidy.cmake` look like this:
`set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_C_CLANG_TIDY clang-tidy --extra-arg=-Wno-error=unknown-warning-option)
set(CMAKE_CXX_CLANG_TIDY clang-tidy --header-filter='.*\/src\/app\/.*\.(cpp|h)' --extra-arg=-Wno-error=unknown-warning-option)`

**Comment by uilianries** [comment]
@honey-speaks-tech Your profile does not fit yet, the `cppstd` should be part of compiler. Please, read https://docs.conan.io/1/reference/profiles.html to get more information about profiles. Please, run `conan profile show default` and paste the exactly content. 

Plus, this error is not related to Conan, neither the package (it works fine), but LLVM Clang tidy. You should take a look how to disable clang tidy for external dependencies. As far as I read, you should use `--header-filter`, maybe you regex is not fitting/supported. Please, try to get informed by llvm dev team.

**Comment by honey-speaks-tech** [comment]
Hello @uilianries Thanks for the response. I could finally fix the issue. It is noticed the abseil conan package expects gnu17 and compiler version 11 for its Linux package.
See :
![image](https://github.com/conan-io/conan/assets/2928745/9edd5aa5-0a8c-484c-a6f7-b0cb90932744)

Finally I solved the issue by modifying my `cppstd` and `compiler.version` accordingly for the `clang-tidy` build.
Please confirm if this is a bug from abseil conan package perspective as original `abseil-cpp` is only expecting C++14 for its build.
See [Abseil docs](https://abseil.io/docs/cpp/quickstart).

Thanks,
Honey

Honey Sukesan

**Comment by uilianries** [comment]
@honey-speaks-tech Thank you for sharing your solution! 

The `settings.compiler.cppstd` is totally flexible and can be configured according to each package. Abseil can be built with C++14 (https://github.com/conan-io/conan-center-index/blob/master/recipes/abseil/all/conanfile.py#L38) or later, so it's up the user to build with a different configuration. In ConanCenterIndex we build with the default c++ standard supported by the compiler (GCC11 is C++17), or the lowest compiler.cppstd in case multiple packages are listed in the dependencies graph (Abseil has no dependencies). 

Said that, we can not provide abseil with gcc11 + compiler.cppstd=14 in Conan Center due the infrastructure, only compiler.cppstd=17 will be available for now. But Anyone can build locally with any supported cppstd version.

Thank you again for your feedback.

**Comment by memsharded** [comment]
Closing as solved back then, but please don't hesitate to create new tickets for any further question or issue. Thanks for the feedback.
