### ISSUE TITLE
Conan install with build_type=Release fails when invoke via CMake

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#15434]
### Conan install with build_type=Release fails when invoke via CMake

I am trying to install boost/gtest with build_type as Release. However it fails when I Call via CMake. It works fien when I call the same command via conan cmdline. Not sure why this happens. It works fine with build_type=Debug. I have tried using both via conan recipe and directly using the `--requirements flag`.

Below is my CMake file:
```
cmake_minimum_required (VERSION 3.5)

add_definitions(-D_SCL_SECURE_NO_WARNINGS)

SET(filter "*.h" "*.cpp")
AutoGenDirStruct(${CMAKE_CURRENT_SOURCE_DIR} filter TRUE SOURCES)

add_library(iTurbAdditionalClasses STATIC ${SOURCES})

SET(Boost_Package_name "boost")
SET(Boost_Version "1.71.0")

SET(Remote_Server "conancenter")
SET(Debug_Output_Folder "${CMAKE_CURRENT_SOURCE_DIR}\\..\\generated\\Debug\\")
SET(Release_Output_Folder "${CMAKE_CURRENT_SOURCE_DIR}\\..\\generated\\Release\\")

message(Generated=${Debug_Output_Folder})

execute_process(COMMAND conan install "${CMAKE_CURRENT_SOURCE_DIR}/../conan/ConanRecipe.py" -s arch=${ARCH} -s build_type=Debug -r ${Remote_Server} -g CMakeDeps -of ${Debug_Output_Folder} -b missing OUTPUT_QUIET)

execute_process(COMMAND conan install "${CMAKE_CURRENT_SOURCE_DIR}/../conan/ConanRecipe.py" -s arch=${ARCH} -s build_type=Release -r ${Remote_Server} -g CMakeDeps -of ${Release_Output_Folder} -b missing OUTPUT_QUIET)

find_package("ZLIB" REQUIRED PATHS ${Debug_Output_Folder} ${Release_Output_Folder})
find_package("BZip2" REQUIRED PATHS ${Debug_Output_Folder} ${Release_Output_Folder})
find_package(${Boost_Package_name} ${Boost_Version} REQUIRED PATHS ${Debug_Output_Folder} ${Release_Output_Folder})

include_directories("${Boost_INCLUDE_DIR}")

SET(GTest_Package_name "gtest")
SET(GTest_Version "1.8.1")

execute_process(COMMAND conan install --requires=${GTest_Package_name}/${GTest_Version} -s arch=${ARCH} -s build_type=Release -r ${Remote_Server} -g CMakeDeps -of ${Release_Output_Folder} -b missing OUTPUT_QUIET)

find_package(${GTest_Package_name} ${GTest_Version} REQUIRED PATHS ${Release_Output_Folder})

include_directories("${GTest_INCLUDE_DIR}")
```

Output from CMake:

> Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
> Platform target: x86
> Lib path base: C:/Repositories/myProject/src/lib
> ======== Input profiles ========
> Profile host:
> [settings]
> arch=x86
> build_type=Debug
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Debug
> compiler.version=193
> os=Windows
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=193
> os=Windows
> 
> 
> 
> ======== Computing dependency graph ========
> 
> Graph root
>     ConanRecipe.py: C:/Repositories/myProject/src/myModule/../conan/ConanRecipe.py
> Requirements
>     boost/1.71.0#ef4b08d5c6a68541f44d6bbb53d8823f - Cache
>     bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4 - Cache
>     zlib/1.3#06023034579559bb64357db3a53f88a4 - Cache
> Build requirements
>     b2/4.10.1#1b290403d8648c79f468f5a6496f829a - Cache
> Resolved version ranges
>     zlib/[>=1.2.11 <2]: zlib/1.3
> 
> 
> ======== Computing necessary packages ========
> 
> Requirements
>     boost/1.71.0#ef4b08d5c6a68541f44d6bbb53d8823f:0cdaa12812a0ac22ff84ef2bf2b2edfcee9b69b1#724c9b8bf75bfc9fc9c367c7ab747469 - Cache
>     bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4:bf4baf0dcdc1c7941cf842f390e9b276b15ca608#14a162153d8ce768f29597db71b59d76 - Cache
>     zlib/1.3#06023034579559bb64357db3a53f88a4:1c8fded4e0c33eda4eaf967c81b43fde5ab5fdd8#09190c4cf858bdda71f672621d65506e - Cache
> Build requirements
> Skipped binaries
>     b2/4.10.1
> 
> 
> ======== Installing packages ========
> 
> bzip2/1.0.8: Already installed! (1 of 3)
> 
> zlib/1.3: Already installed! (2 of 3)
> 
> boost/1.71.0: Already installed! (3 of 3)
> 
> boost/1.71.0: Disabled magic autolinking (smart and magic decisions)
> 
> WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
> WARN: deprecated:     'cpp_info.names' used in: boost/1.71.0, bzip2/1.0.8, zlib/1.3
> WARN: deprecated:     'cpp_info.build_modules' used in: bzip2/1.0.8
> WARN: deprecated:     'env_info' used in: boost/1.71.0, bzip2/1.0.8
> WARN: deprecated:     'cpp_info.filenames' used in: boost/1.71.0
> WARN: deprecated:     'user_info' used in: boost/1.71.0
> 
> ======== Finalizing install (deploy, generators) ========
> 
> ConanRecipe.py: Writing generators to C:/Repositories/myProject/src/myModule\..\generated\Debug\
> 
> ConanRecipe.py: Generator 'CMakeDeps' calling 'generate()'
> 
> ConanRecipe.py: Calling generate()
> ConanRecipe.py: Generators folder: C:/Repositories/myProject/src/myModule\..\generated\Debug\
> 
> ConanRecipe.py: Generating aggregated env files
> ConanRecipe.py: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
> 
> Install finished successfully
> 
> 
> ======== Input profiles ========
> Profile host:
> [settings]
> arch=x86
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=193
> os=Windows
> 
> Profile build:
> 
> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=193
> os=Windows
> 
> 
> 
> ======== Computing dependency graph ========
> 
> Graph root
>     ConanRecipe.py: C:/Repositories/myProject/src/myModule/../conan/ConanRecipe.py
> Requirements
> 
>     boost/1.71.0#ef4b08d5c6a68541f44d6bbb53d8823f - Cache
>     bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4 - Cache
>     zlib/1.3#06023034579559bb64357db3a53f88a4 - Cache
> Build requirements
>     b2/4.10.1#1b290403d8648c79f468f5a6496f829a - Cache
> Resolved version ranges
>     zlib/[>=1.2.11 <2]: zlib/1.3
> 
> ======== Computing necessary packages ========
> 
> boost/1.71.0: Checking 3 compatible configurations
> 
> boost/1.71.0: Compatible configurations not found in cache, checking servers
> 
> boost/1.71.0: 'a704987b7c2d968599af55ef54d585736260a0cf': compiler.cppstd=17
> 
> boost/1.71.0: '94a3c161d72f2a062214bf13bcc3720e4b97f90c': compiler.cppstd=20
> 
> boost/1.71.0: 'df04052829c2df1fce2e714d0ec6742b7ea346fc': compiler.cppstd=23
> 
> Requirements
> 
>     boost/1.71.0#ef4b08d5c6a68541f44d6bbb53d8823f:8d1d9bb88122a20cc9bd681af7c690b81c72ab73 - Build
>     bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4:6b8a1fe8cfc7e56f5e35dc6072cbcfba1dfdb27a - Build
>     zlib/1.3#06023034579559bb64357db3a53f88a4:8419bdd2579514d415d70db8caf4318ede661647 - Build
> Build requirements
>     b2/4.10.1#1b290403d8648c79f468f5a6496f829a:522dcea5982a3f8a5b624c16477e47195da2f84f#ac9afe8444d67960c7a12dc72320909b - Cache
> 
> 
> ======== Installing packages ========
> 
> b2/4.10.1: Already installed! (1 of 4)
> 
> 
> -------- Installing package bzip2/1.0.8 (2 of 4) --------
> bzip2/1.0.8: Building from source
> bzip2/1.0.8: Package bzip2/1.0.8:6b8a1fe8cfc7e56f5e35dc6072cbcfba1dfdb27a
> 
> bzip2/1.0.8: Copying sources to build folder
> 
> bzip2/1.0.8: Building your package in C:\Users\myuser\.conan2\p\b\bzip2f0f65c3180d2e\b
> 
> bzip2/1.0.8: Calling generate()
> bzip2/1.0.8: Generators folder: C:\Users\myuser\.conan2\p\b\bzip2f0f65c3180d2e\b\build\generators
> 
> bzip2/1.0.8: CMakeToolchain generated: conan_toolchain.cmake
> 
> bzip2/1.0.8: CMakeToolchain generated: CMakePresets.json
> 
> bzip2/1.0.8: Generating aggregated env files
> bzip2/1.0.8: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
> 
> bzip2/1.0.8: Calling build()
> bzip2/1.0.8: apply_conandata_patches(): No patches defined in conandata
> 

> 
> bzip2/1.0.8: Running CMake.configure()
> 
> bzip2/1.0.8: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/myuser/.conan2/p/b/bzip2f0f65c3180d2e/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/myuser/.conan2/p/b/bzip2f0f65c3180d2e/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\myuser\.conan2\p\b\bzip2f0f65c3180d2e\b\src\.."
> 
> bzip2/1.0.8: ERROR: 
> Package '6b8a1fe8cfc7e56f5e35dc6072cbcfba1dfdb27a' build failed
> 
> bzip2/1.0.8: WARN: Build folder C:\Users\myuser\.conan2\p\b\bzip2f0f65c3180d2e\b\build
> 
> *********************************************************
> Recipe 'bzip2/1.0.8' cannot build its binary
> It is possible that this recipe is not Conan 2.0 ready
> If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
> If it is your recipe, check if it is updated to 2.0
> *********************************************************
> 
> 
> ERROR: bzip2/1.0.8: Error in build() method, line 63
> 	cmake.configure(build_script_folder=os.path.join(self.source_folder, os.pardir))
> 	ConanException: Error while running cmd
> Error: [WinError 6] The handle is invalid
> 
> ======== Input profiles ========
> Profile host:
> [settings]
> arch=x86
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=193
> os=Windows
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=193
> os=Windows
> 
> 
> 
> ======== Computing dependency graph ========
> 
> Graph root
>     cli
> Requirements
>     gtest/1.8.1#c8a230fc18e7b5103adc986ccd1f6ba6 - Cache
> 
> 
> ======== Computing necessary packages ========
> 
> gtest/1.8.1: Checking 3 compatible configurations
> 
> gtest/1.8.1: Compatible configurations not found in cache, checking servers
> 
> gtest/1.8.1: '74ad6e579d88c522caeca4219ed2a0d244ce4015': compiler.cppstd=17
> 
> gtest/1.8.1: '564672ea94dbc96b1128735d0d4919695ef7533e': compiler.cppstd=20
> 
> gtest/1.8.1: 'c636eef0936a3fe1df7789ea9237d4ab6fd9645f': compiler.cppstd=23
> 
> Requirements
>     gtest/1.8.1#c8a230fc18e7b5103adc986ccd1f6ba6:9aaf3ed1a2b8f7dffcd3d83aa07de960f01c99e7 - Build
> 
> 
> ======== Installing packages ========
> 
> 
> -------- Installing package gtest/1.8.1 (1 of 1) --------
> gtest/1.8.1: Building from source
> gtest/1.8.1: Package gtest/1.8.1:9aaf3ed1a2b8f7dffcd3d83aa07de960f01c99e7
> 
> gtest/1.8.1: Copying sources to build folder
> 
> gtest/1.8.1: Building your package in C:\Users\myuser\.conan2\p\b\gtestde82d8c5eb1bf\b
> 
> gtest/1.8.1: Calling generate()
> gtest/1.8.1: Generators folder: C:\Users\myuser\.conan2\p\b\gtestde82d8c5eb1bf\b\build\generators
> 
> gtest/1.8.1: CMakeToolchain generated: conan_toolchain.cmake
> 
> gtest/1.8.1: CMakeToolchain generated: CMakePresets.json
> 
> gtest/1.8.1: CMakeToolchain generated: ..\..\src\CMakeUserPresets.json
> 
> gtest/1.8.1: Generating aggregated env files
> gtest/1.8.1: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
> 
> gtest/1.8.1: Calling build()
> 
> gtest/1.8.1: Apply patch (conan): add CUSTOM_DEBUG_POSTFIX option
> 
> gtest/1.8.1: Running CMake.configure()
> 
> gtest/1.8.1: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/myuser/.conan2/p/b/gtestde82d8c5eb1bf/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/myuser/.conan2/p/b/gtestde82d8c5eb1bf/p" -DCMAKE_POLICY_DEFAULT_CMP0042="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\myuser\.conan2\p\b\gtestde82d8c5eb1bf\b\src"
> 
> gtest/1.8.1: ERROR: 
> Package '9aaf3ed1a2b8f7dffcd3d83aa07de960f01c99e7' build failed
> gtest/1.8.1: WARN: Build folder C:\Users\myuser\.conan2\p\b\gtestde82d8c5eb1bf\b\build
> 
> *********************************************************
> Recipe 'gtest/1.8.1' cannot build its binary
> It is possible that this recipe is not Conan 2.0 ready
> If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
> If it is your recipe, check if it is updated to 2.0
> *********************************************************
> 
> ERROR: gtest/1.8.1: Error in build() method, line 135
> 	cmake.configure()
> 	ConanException: Error while running cmd
> Error: [WinError 6] The handle is invalid
> 
> CMake Error at myModule/CMakeLists.txt:35 (find_package):
>   Could not find a package configuration file provided by "gtest" (requested
>   version 1.8.1) with any of the following names:
> 
>     gtestConfig.cmake
>     gtest-config.cmake
> 
>   Add the installation prefix of "gtest" to CMAKE_PREFIX_PATH or set
>   "gtest_DIR" to a directory containing one of the above files.  If "gtest"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> Configuring incomplete, errors occurred!

Conan recipe file:
```
import os
from conan import ConanFile

class Recipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    
    def requirements(self):
        self.requires("boost/1.71.0")
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

It seems there are some not recommended (not only by Conan, but also CMake) practices in your code:

- You shouldn't be needing to define ``SET(Debug_Output_Folder "${CMAKE_CURRENT_SOURCE_DIR}\\..\\generated\\Debug\\")`` explicitly
- The ``find_package("ZLIB" REQUIRED PATHS ${Debug_Output_Folder} ${Release_Output_Folder})`` doesn't look right, it could find the wrong configuration, like always finding Debug. I think this is what is failing
- To use packages targets should be used. ``include_directories("${Boost_INCLUDE_DIR}")`` is considered nowadays legacy and discouraged CMake practice. Please use the ``Boost::Boost`` target (not sure about the spelling)
- Do not execute separate ``conan install`` for other requirements. All the requirements of a project must be consistent, and they should come from one ``conan install``. I am talking about ``execute_process(COMMAND conan install --requires=${GTest_Package_name}/${GTest_Version}`` to install ``gtest``. Add ``test_requires = "gtest/..."`` to your conanfile instead
- Same about targets for gtest, do not use ``include_directories("${GTest_INCLUDE_DIR}")`` but link with the gtest provided targets.
- ``find_package(${Boost_Package_name} ${Boost_Version} `` will not guarantee that you will have that boost version. The ``conanfile.py`` is the one saying which version is being installed.

I'd suggest using the standard and documented practices:
- If you want to call Conan from CMake, please use the provider integration in: https://github.com/conan-io/cmake-conan. It seems that you are trying to re-invent that, but it is not straightforward to do it, so better use the integration. I'd suggest using it with CMakePresets too
- Modifying CMakeLists.txt files to include Conan specific logic is an anti-pattern, and it should be avoided

**Comment by sandybhat16** [comment]
@memsharded Thanks for the improvement suggestions. I will try them out. But when I had a look at the packages available at conan center for gtest 1.8.1. It seems they do not have a package for x86 anymore. Hence the error.

> C:\Repositories\myProject\src\conan>conan list gtest/1.8.1:* -r=conancenter
> conancenter
>   gtest
>     gtest/1.8.1
>       revisions
>         c8a230fc18e7b5103adc986ccd1f6ba6 (2023-07-14 15:25:46 UTC)
>           packages
>             3e662a58974cc4404611dfa7ffbaf85bbb6f2393
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: apple-clang
>                   compiler.cppstd: 17
>                   compiler.libcxx: libc++
>                   compiler.version: 13
>                   os: Macos
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   hide_symbols: False
>                   shared: True
>             2ccd6652789906cdc03dfd327ec8c127706c87fa
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: gcc
>                   compiler.cppstd: 17
>                   compiler.libcxx: libstdc++11
>                   compiler.version: 11
>                   os: Linux
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   fPIC: True
>                   hide_symbols: False
>                   shared: False
>             37380549bf10b61117fd85c49fe6504e0210d9dc
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: msvc
>                   compiler.cppstd: 14
>                   compiler.runtime: dynamic
>                   compiler.runtime_type: Release
>                   compiler.version: 192
>                   os: Windows
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   hide_symbols: False
>                   shared: False
>             a738bb3b89df5bec31c12750fb201a1a1a46f81b
>               info
>                 settings
>                   arch: armv8
>                   build_type: Release
>                   compiler: apple-clang
>                   compiler.cppstd: 17
>                   compiler.libcxx: libc++
>                   compiler.version: 13
>                   os: Macos
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   hide_symbols: False
>                   shared: True
>             e8881c31d7715e9ffccf19b87014654db155beed
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: msvc
>                   compiler.cppstd: 14
>                   compiler.runtime: dynamic
>                   compiler.runtime_type: Release
>                   compiler.version: 193
>                   os: Windows
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   hide_symbols: False
>                   shared: False
>             7454cdbd06c42a89d31949895397be16760c36a2
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: apple-clang
>                   compiler.cppstd: 17
>                   compiler.libcxx: libc++
>                   compiler.version: 13
>                   os: Macos
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   fPIC: True
>                   hide_symbols: False
>                   shared: False
>             9940e217936a0f218f90473d62bf1d4db55efaa7
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: msvc
>                   compiler.cppstd: 14
>                   compiler.runtime: dynamic
>                   compiler.runtime_type: Release
>                   compiler.version: 193
>                   os: Windows
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   hide_symbols: False
>                   shared: True
>             1f1820e0c72740a14c15b5803b640843027458a6
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: gcc
>                   compiler.cppstd: 17
>                   compiler.libcxx: libstdc++11
>                   compiler.version: 11
>                   os: Linux
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   hide_symbols: False
>                   shared: True
>             5de47a8c9b001228bc52de437bb373bb631f5311
>               info
>                 settings
>                   arch: x86_64
>                   build_type: Release
>                   compiler: msvc
>                   compiler.cppstd: 14
>                   compiler.runtime: dynamic
>                   compiler.runtime_type: Release
>                   compiler.version: 192
>                   os: Windows
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   hide_symbols: False
>                   shared: True
>             03ca8b40958eec491545af6f98d6fad96aa7eb4b
>               info
>                 settings
>                   arch: armv8
>                   build_type: Release
>                   compiler: apple-clang
>                   compiler.cppstd: 17
>                   compiler.libcxx: libc++
>                   compiler.version: 13
>                   os: Macos
>                 options
>                   build_gmock: True
>                   disable_pthreads: False
>                   fPIC: True
>                   hide_symbols: False
>                   shared: False

**Comment by memsharded** [comment]
Yes, ConanCenter dropped the creation of most x86 binaries some time ago, that architecture is barely used nowadays, and ConanCenter requires too many resources.

For users wanting to use other architectures, specially in production the recommendations are not to rely directly on ConanCenter binaries, but rather https://docs.conan.io/2/devops/using_conancenter.html. Please have a look, and if you are using x86 32 binaries, I'd recommend following the guidelines there.

**Comment by memsharded** [comment]
Any further feedback or question here @sandybhat16 ?

**Comment by sandybhat16** [comment]
Nothing for now.
