### ISSUE TITLE
[question] How to Download tgz package in conan2

### ISSUE THREAD

**Issue by msk-iit** [conan-io/conan#15431]
### What is your question?

Hi,

I want to download conan_package.tgz using conan2.

Previously in conan 1.x, `conan download <package>`  downloads .tgz file in cache
Now in conan2, it just downloads manifest file. Is there a way in conan2 to download .tgz file.

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @msk-iit 

Thanks for your question.

The ``conan_package.tgz`` is an implementation detail, and it shouldn't be handle directly. Conan commands compress and decompress, and if you want the artifacts within a package, the ``deployers`` can help you.

Said that, the ``conan download`` works the same in 1.X and 2.0. In both cases it will download the conan_package.tgz, probably it is just in another location. check the ``conan cache path`` command to get information about paths in the cache.

**Comment by memsharded** [comment]
Closing this ticket as responded, don't hesitate to create new tickets for any further question, thanks!
