### ISSUE TITLE
[question] build_id() and packaging prebuilt libraries

### ISSUE THREAD

**Issue by daltonv** [conan-io/conan#15437]
My team packages an SDK for a mcu vendor for conan distribution. The SDK comes as a zip file with the sdk sources and prebuilt libraries for 3 different compilers. 

I setup my conan recipe so that my `build()` method really just downloads the SDK of the right version from a publicly accessible link on the vendor's site. The `package()` method just copies the right libs based on the settings from the profile being used.

This is all working for me, but I would like to avoid pointlessly redownloading the sdk for each package binary I produce as all variants depend on the same sdk.

I found the `build_id()` method can do this, but it seems to only work for multiple build types. If I try to set `self.info_build.settings.compiler = "Any"` in the method I get and error about Any not being a valid selection. `ConanException: Invalid setting 'Any' is not a valid 'settings.compiler' value.`.

Is there some way to set that every compiler uses the same "build"? 

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @daltonv 

Thanks for your report. I assume this is 2.0
I have been able to reproduce in 2.0, it seems there is a gap for settings that are not final (that have nested sub-settings), I am checking it.

**Comment by daltonv** [comment]
Yep this 2.0. 2.0.16 to be exact.

**Comment by memsharded** [comment]
While I am investigating it in #15439, a quick question: is it possible that you don't want to define the ``compiler`` setting in the first place? It seems that this package will have a low variability, and it is likely that it is enough to not define the ``compiler`` setting directly? What is the binary variability?

**Comment by daltonv** [comment]
The SDK provides 3 static libs that are really all just variants of the same built source code for 3 different compilers. I really do need each lib to be its own package binary, so the consumer of the package just needs to setup their profile right and they get the right library for the compiler their project is using.

**Comment by memsharded** [comment]
Oh, I see. So the variability is indeed over the compiler, got it.
Ok, please track progress of #15439, I hope we can unblock this soon. Thanks for the feedback!

**Comment by daltonv** [comment]
Sounds good. Thanks for looking into it!

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/15439 has been merged, so this will be available next Conan 2.1 release

**Comment by daltonv** [comment]
Awesome thanks for the quick fix!
