### ISSUE TITLE
[question] Possible to upload a conan package from artifacts ?

### ISSUE THREAD

**Issue by docbrown1955** [conan-io/conan#15449]
### What is your question?

Hi,

My question is about CI/CD good practices when developping and deploying conan packages. I would very much like to have the possibility to separate build and upload stages for a conan package. 

This separation makes the pipeline cleaner but most importantly makes CI/CD much more flexible and robust as one can for example have multiple jobs using the same package (deploy on Artifactory & other for example), or for example build several configurations at once before uploading any of them (hard to do if the upload follows the build in a unique job).

My current understanding of the way conan works tells me that it is not possible a priori, but possible if either:

1. the entire conan cache is sent as an artifact between jobs to keep it sane, or
2. we hack the conan cache to put a single package in it which we want to upload, or
3. we upload directly using some jf CLI command.

Solution 1. is not a viable option for packages that have a lot of dependencies (waste of resources) and solutions 2. and 3. do not seem quite robust.

Could it be one day possible with standard conan ? I imagine the possibility to generate a folder containing the recipe, the package and posssible additional info for the upload so that conan can later upload it safely without the need for any package in the cache (the said folder could therefore be just archived and passed around as an artifact).

It is perfectly possible I am missing a simpler solution, if so please ignore my proposal above ;)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @docbrown1955 

I don't know if you saw the ``conan cache save/restore`` feature in Conan 2.0. If not please have a look to https://docs.conan.io/2/devops/save_restore.html

This is specifically intended for CI flows and systems, when you want to delay uploading the packages, accumulate them or something like that. It also works with "package-lists" feature, so it should be well integrated with other commands flow.

**Comment by docbrown1955** [comment]
Hi @memsharded,

That's perfect, I was not aware at all of these conan commands! Thanks

**Comment by memsharded** [comment]
> That's perfect, I was not aware at all of these conan commands! Thanks

I'd recommend to subscribe to the mailing list, it is used just for announcing these new features and releases and not spam.
Also we share these news in the Conan blog like in https://blog.conan.io/2023/11/28/Conan-new-features-2-0-14.html

Can we close this ticket as responded? You can open new ones if there is any further question.

**Comment by docbrown1955** [comment]
I will, thanks. You can close the ticket indeed :)
