### ISSUE TITLE
[question] How to handle package dendencies in conan v1

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#15442]
### How can I handle dependencies in conan v1

Hey guys,
I'm using lvgl (an embedded GUI framework) which relys on sdl (I want to use the latest from conan center).
Basically we are running 3 configurations

1. windows (requires sdl)
2. linux (requires sdl)
3. embedded target (must not use sdl, uses generic driver)

lvgl and sdl are build using cmake.

My conan file looks like this
```

from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps
from conan.tools.files import copy, rename
from conan.tools.scm import Git
from hashlib import sha256
import os
from os import path


class LvglConan(ConanFile):
    name = "lvgl"
    version = "9.0_dev"
    # Optional metadata
    license = "MIT"
    author = "xxx"
    description = "LVGL as a conan 3rd party, including drivers and simulator"
    generators = "CMakeDeps"
    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "lv_conf_path": [None, "ANY"],
        "disable_examples": [True, False],
        "disable_demos": [True, False],
        "driver": [None, "sdl"],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
        "lv_conf_path": None,
        "disable_examples": True,
        "disable_demos": True,
        "driver": None,
    }

    def ensure_directory_exists(self, dir_path):
        """Ensure that the directory exists; if it doesn't, create it."""
        if not path.exists(dir_path):
            os.makedirs(dir_path)

    def __copy_as(self, src, dst):
        import shutil
        self.ensure_directory_exists(path.dirname(dst))
        shutil.copy(src, dst)

    def __copy_as_test(self, src, dst):
        self.ensure_directory_exists(path.dirname(dst))
        copy(self, path.basename(src), path.dirname(src), path.dirname(dst))
        if path.basename(src) != path.basename(dst):
            rename(self, path.join(path.dirname(dst), path.basename(src)), dst)

    def __copy_config_files(self):
        if self.options.lv_conf_path:
            lv_conf_path = self.lv_conf_path
            self.__copy_as(lv_conf_path, path.join(self.source_folder, "lvgl/lv_conf.h"))
        else:
            original_conf_file = "lv_conf_default.h"
            self.__copy_as(
                path.join(self.source_folder, f"lvgl/config/{original_conf_file}"),
                path.join(self.source_folder, "lvgl/lv_conf.h"),
            )

    def requirements(self):
        if self.options.driver == "sdl":
            self.requires("sdl/2.28.5", transitive_headers=True, transitive_libs=True)

    def source(self):
        git = Git(self)
        clone_args = [f"-b heju/lvgl_master"]
        git.clone(url="xxx/lvgl.git", args=clone_args)

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
        elif self.settings.os == "Linux":
            del self.options.driver  # building sdl on linux fails pipeline

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)

        tc.cache_variables["LV_CONF_PATH"] = self.source_folder.replace("\\", "/") + "/lvgl/lv_conf.h"
        if self.options.driver == "sdl":
            tc.cache_variables["BUILD_DRIVERS"] = "ON"

        if self.options.shared:
            tc.cache_variables["BUILD_SHARED_LIBS"] = "ON"
        if self.options.disable_examples:
            tc.cache_variables["LV_CONF_BUILD_DISABLE_EXAMPLES"] = "ON"
        if self.options.disable_demos:
            tc.cache_variables["LV_CONF_BUILD_DISABLE_DEMOS"] = "ON"
        tc.generate()

        # generate dependency find info for CMake find_package to locate sdl (and other deps)
        cmake_deps = CMakeDeps(self)
        cmake_deps.generate()

    def build(self):
        self.__copy_config_files()
        cmake = CMake(self)
        cmake.configure(build_script_folder="lvgl")
        cmake.build()

        cmake.test(build_type=self.settings.build_type, target="lvgl")

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def __getFilehash(self, filename):
        try:
            with open(filename, "r", encoding="utf8") as f:
                text = f.read()
        except FileNotFoundError:
            print(f"File not Found: {filename}")
            raise

        h = sha256()
        bts = bytes(text, "utf8")
        h.update(bts)
        return h.hexdigest()

    def package_id(self):
        if self.options.lv_conf_path:
            self.lv_conf_path = self.info.options.get_safe("lv_conf_path")
            self.info.options.lv_conf_path = self.__getFilehash(self.lv_conf_path)


    def package_info(self):
        self.cpp_info.libs = ["lvgl"]
        self.cpp_info.includedirs = ["include", "include/lvgl"]
        self.cpp_info.defines = [
            "LV_CONF_PATH=lvgl/lv_conf.h",
        ]
        if self.settings.os == "Windows" and self.settings.compiler == "Visual Studio":
            self.cpp_info.defines.append("LV_ATTRIBUTE_EXTERN_DATA=__declspec(dllimport)")

        if self.options.driver == "sdl":
            self.cpp_info.components[f"lib{self.name}"].requires = ["sdl::sdl"]

```

I have setup a little test package which simply does

```
#include <lvgl/lvgl.h>
int main() {
  lv_init();
  return 0;
}
```

However, setting driver to "sdl" instead of None, i'm getting a linker error that lv_init() canot be found. Strangely, with drivers set to None the test package builds properly.
In every case I'm running
`conan create . --build=missing`

Can you tell me what I'm missing?
thx guys

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ju1He1 

First, let me suggest some hints:

- ``ensure_directory_exists`` probably is not needed, the built-in ``conan.tools.files import mkdir`` does exactly that
- You have ``CMakeDeps`` twice, as attribute and in the ``generate()`` method
- ``cmake.test(build_type=self.settings.build_type`` sounds wrong or at least unnecessary, Conan should automatically do that
- ``self.settings.compiler == "Visual Studio"`` will break in Conan 2.0, you should use ``is_msvc()``
- Unless  you are packaging the examples and demos in the final package, the options ``"disable_examples", "disable_demos"`` should be removed in the ``package_id``, or maybe converted to something like ``user.myorg:disable_examples`` conf.
- ``with open(filename, "r", encoding="utf8") as f:`` can be done with ``conan.tools.files import load`` helper too
- ``tc.cache_variables["BUILD_SHARED_LIBS"] = bool(self.options.shared)`` oneliner will work (even without the ``bool()`` cast)

This one is very important:
- ``clone_args = [f"-b heju/lvgl_master"]`` is broken design to create packages. Package sources must be uniquely 1:1 match with an immutable source. Using a branch as origin, which is a moving target breaks package reproducibility and immutability. A fixed commit or a tag should be used to retrieve sources from git repos

I think the main error is:
```
self.cpp_info.components[f"lib{self.name}"].requires = ["sdl::sdl"]
```
When components are defined, the global ``self.cpp_info.includedirs`` and other ``self.cpp_info`` global information like defines, libs, etc, is not used. Everything should be defined in component information.

**Comment by ghost** [comment]
Hey @memsharded thx for your fast feedback :)

1) ensure_directory_exists probably is not needed, the built-in conan.tools.files import mkdir does exactly that
=> thx removed that function and used mkdir from conan

2)
You have CMakeDeps twice, as attribute and in the generate() method
=> do you mean setting `generators = "CMakeDeps"` is sufficient? No need for 
```
cmake_deps = CMakeDeps(self)
cmake_deps.generate()
```

3) cmake.test(build_type=self.settings.build_type sounds wrong or at least unnecessary, Conan should automatically do that
=> thx I removed that

4) self.settings.compiler == "Visual Studio" will break in Conan 2.0, you should use is_msvc()
=> ah I did not know that, I'll have a look at my other recipes as well :)


5)
Unless you are packaging the examples and demos in the final package, the options "disable_examples", "disable_demos" should be removed in the package_id, or maybe converted to something like user.myorg:disable_examples conf.
=> thx not sure on that one, I need to have a look. Having these options in the package id should not break the build right?


6)with open(filename, "r", encoding="utf8") as f: can be done with conan.tools.files import load helper too
=> thx I used that helper as well :)


7)
=> tc.cache_variables["BUILD_SHARED_LIBS"] = bool(self.options.shared) oneliner will work (even without the bool() cast)
=> thx I replaced that (and the other options, this defintately makes the script cleaner


8)
clone_args = [f"-b heju/lvgl_master"] is broken design to create packages. Package sources must be uniquely 1:1 match with an immutable source. Using a branch as origin, which is a moving target breaks package reproducibility and immutability. A fixed commit or a tag should be used to retrieve sources from git repos
=> ah sorry this is just for testing. At the moment I'm doing a conan remove "*" -f before recreating. Once done it will becode a specific tag

9)
When components are defined, the global self.cpp_info.includedirs and other self.cpp_info global information like defines, libs, etc, is not used. Everything should be defined in component information.

sorry I don't uderstand, could give me a little example?


thx once again :)

**Comment by memsharded** [comment]
> do you mean setting generators = "CMakeDeps" is sufficient? No need for

yes, exactly that, can be removed from ``generate()`` if it is declared as attribute

> thx not sure on that one, I need to have a look. Having these options in the package id should not break the build right?

No, it will not break the build. But it will create different ``package_id``, so if you do a build with one of those options =True, then a ``package_id`` will be computed. If you later try to use that package but do not define that option to True, it will compute a different ``package_id`` and tell you that a binary for that configuration is not existing and has to be built from source. So unless you do actually want to have different binary packages, some with the demos and examples packaged inside the package and others without those, then you want to get the same ``package_id`` for all values of those options.

> ah sorry this is just for testing. At the moment I'm doing a conan remove "*" -f before recreating. Once done it will becode a specific tag

Sounds good

> sorry I don't uderstand, could give me a little example?

```python
# SEEMS INCORRECT
def package_info(self):
        self.cpp_info.libs = ["lvgl"]  # Ignored if ``self.options.driver == "sdl"
        self.cpp_info.includedirs = ["include", "include/lvgl"]  # Ignored if ``self.options.driver == "sdl"
        self.cpp_info.defines = [  # Ignored if ``self.options.driver == "sdl"
            "LV_CONF_PATH=lvgl/lv_conf.h",
        ]
        if self.settings.os == "Windows" and self.settings.compiler == "Visual Studio":
             # Ignored if ``self.options.driver == "sdl"
            self.cpp_info.defines.append("LV_ATTRIBUTE_EXTERN_DATA=__declspec(dllimport)")

        if self.options.driver == "sdl":
            self.cpp_info.components[f"lib{self.name}"].requires = ["sdl::sdl"]
```
```python
# CORRECT ONE
def package_info(self):
        if self.options.driver == "sdl":  # Using components
            self.cpp_info.components[f"lib{self.name}"].requires = ["sdl::sdl"]
            self.cpp_info.components[f"lib{self.name}"].libs = ["lvgl"] 
            self.cpp_info.components[f"lib{self.name}"].includedirs = ["include", "include/lvgl"]
            self.cpp_info.components[f"lib{self.name}"].defines = [
                "LV_CONF_PATH=lvgl/lv_conf.h",
            ]
            if self.settings.os == "Windows" and self.settings.compiler == "Visual Studio":
                self.cpp_info.components[f"lib{self.name}"].defines.append("LV_ATTRIBUTE_EXTERN_DATA=__declspec(dllimport)")
        else:  # Not using components
             self.cpp_info.libs = ["lvgl"]  # Ignored if ``self.options.driver == "sdl"
             self.cpp_info.includedirs = ["include", "include/lvgl"]  # Ignored if ``self.options.driver == "sdl"
             self.cpp_info.defines = [  # Ignored if ``self.options.driver == "sdl"
                "LV_CONF_PATH=lvgl/lv_conf.h",
             ]
             if self.settings.os == "Windows" and self.settings.compiler == "Visual Studio":
                 # Ignored if ``self.options.driver == "sdl"
                self.cpp_info.defines.append("LV_ATTRIBUTE_EXTERN_DATA=__declspec(dllimport)")
```

This is bad code, in reality this can be shorter, but just the idea.
In reality, it seems that usage of components is not good. Maybe you want something different, it is not clear what problem you are trying to solve by that dynamic definition of components. Mostly you either have components in your package, if you have multiple libraries that can be optionally linked or not, or you don't have components in your package. But such component just to define a ``requires=["sdl::sdl"]`` reads unexpected.

**Comment by ghost** [comment]
Hey @memsharded  thx for your answer. This seams to work well.
I added an option "STANDALONE_BUILD" to make it more clear

There are basically 2 use cases.
1) Building lvgl as stand-alone (via a CMake preset)
2) Building lvgl as a 3rd party for some actual project via conan.

The first usecase (standalone build) does not use conan. We are making some company specific adoptions to lvgl. Therefore we need to ensure that our adoptions do not break any build (windows, linux, embedded target). In this usecase SDL is added as a git submodule to the project.

The second usecase is the more important one. Since we are already using conan here I decided to add the dependency (sdl) to the conan recipe instead of using git submodules

So to sum up:

1. Any dependency needs to be added self.cpp_info.components.
2. Each component map can have the same members as the self.cpp_info map (https://docs.conan.io/1/reference/conanfile/attributes.html#cpp-info) (names, libs, defines, requires)


One last question:
sdl seams to be build as a static lib (this seams to be the default value in the sdl recipe). I'd prefer a shared lib.
Is something like this possible to pass settings to the dependency
`self.dependencies["sdl"].options.shared = self.options.shared`




If anyone is interested, this is how the new recipe looks like

```
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout
from conan.tools.files import copy, rename, mkdir, load
from conan.tools.microsoft import is_msvc
from conan.tools.scm import Git
from hashlib import sha256
from os import path


class LvglConan(ConanFile):
    name = "lvgl"
    version = "9.0_dev"
    # Optional metadata
    license = "MIT"
    author = "XXX"
    description = "LVGL as a conan 3rd party, including drivers and simulator"
    generators = "CMakeDeps"
    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "lv_conf_path": [None, "ANY"],
        "disable_examples": [True, False],
        "disable_demos": [True, False],
        "disable_thorvg": [True, False],
        "driver": [None, "sdl"],
        # set to true if you would like to use sdl from lvgl git repo, set to false if you would
        # like to use sdl from conan center
        "use_packaged_sdl": [True, False],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
        "lv_conf_path": None,
        "disable_examples": True,
        "disable_demos": True,
        "disable_thorvg": True,
        "driver": None,
        "use_packaged_sdl": False,
    }

    def __copy_as(self, src, dst):
        mkdir(self, path.dirname(dst))
        import shutil

        shutil.copy(src, dst)

    def __copy_as_test(self, src, dst):
        mkdir(self, path.dirname(dst))
        copy(self, path.basename(src), path.dirname(src), path.dirname(dst))
        if path.basename(src) != path.basename(dst):
            rename(self, path.join(path.dirname(dst), path.basename(src)), dst)

    def __copy_config_files(self):
        if self.options.lv_conf_path:
            lv_conf_path = self.lv_conf_path
            self.__copy_as(lv_conf_path, path.join(self.source_folder, "lvgl/lv_conf.h"))
        else:
            original_conf_file = "lv_conf_default.h"
            self.__copy_as(
                path.join(self.source_folder, f"lvgl/config/{original_conf_file}"),
                path.join(self.source_folder, "lvgl/lv_conf.h"),
            )

    def requirements(self):
        if self.options.driver == "sdl" and not self.options.use_packaged_sdl:
            self.requires("sdl/2.28.5", transitive_headers=True, transitive_libs=True)

    def source(self):
        git = Git(self)
        clone_args = [f"-b v{self.version}"]
        if self.options.use_packaged_sdl:
            clone_args.append("--recurse-submodules")
        git.clone(url="git@xxx/lvgl.git", args=clone_args)

    def config_options(self):
        if self.settings.os == "Windows":
            self.options.rm_safe("fPIC")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)

        tc.cache_variables["LV_CONF_PATH"] = self.source_folder.replace("\\", "/") + "/lvgl/lv_conf.h"
        tc.cache_variables["LV_CONF_BUILD_DISABLE_THORVG_INTERNAL"] = bool(self.options.disable_thorvg)
        if self.options.driver == "sdl":
            tc.cache_variables["BUILD_DRIVERS"] = "ON"
            if self.options.use_packaged_sdl:
                tc.cache_variables["USE_STANDALONE_BUILD"] = "ON"

        tc.cache_variables["BUILD_SHARED_LIBS"] = bool(self.options.shared)
        tc.cache_variables["LV_CONF_BUILD_DISABLE_EXAMPLES"] = bool(self.options.disable_examples)
        tc.cache_variables["LV_CONF_BUILD_DISABLE_DEMOS"] = bool(self.options.disable_demos)
        tc.generate()

    def build(self):
        self.__copy_config_files()
        cmake = CMake(self)
        cmake.configure(build_script_folder="lvgl")
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def __getFilehash(self, filename):
        try:
            text = load(self, filename)
        except FileNotFoundError:
            print(f"File not Found: {filename}")
            raise

        h = sha256()
        bts = bytes(text, "utf8")
        h.update(bts)
        return h.hexdigest()

    def package_id(self):
        if self.options.lv_conf_path:
            self.lv_conf_path = self.info.options.get_safe("lv_conf_path")
            self.info.options.lv_conf_path = self.__getFilehash(self.lv_conf_path)

    # CORRECT ONE
    def package_info(self):
        if self.options.driver == "sdl" and self.options.use_packaged_sdl:  # Using components
            self.cpp_info.components[f"lib{self.name}"].requires = ["sdl::sdl"]
            self.cpp_info.components[f"lib{self.name}"].libs = ["lvgl"]
            self.cpp_info.components[f"lib{self.name}"].includedirs = ["include", "include/lvgl"]
            self.cpp_info.components[f"lib{self.name}"].defines = [
                "LV_CONF_PATH=lvgl/lv_conf.h",
            ]
            if self.settings.os == "Windows" and is_msvc(self):
                self.cpp_info.components[f"lib{self.name}"].defines.append(
                    "LV_ATTRIBUTE_EXTERN_DATA=__declspec(dllimport)"
                )
        else:  # Not using components
            self.cpp_info.libs = ["lvgl"]  # Ignored if ``self.options.driver == "sdl"
            self.cpp_info.includedirs = ["include", "include/lvgl"]  # Ignored if ``self.options.driver == "sdl"
            self.cpp_info.defines = [  # Ignored if ``self.options.driver == "sdl"
                "LV_CONF_PATH=lvgl/lv_conf.h",
            ]
            if self.settings.os == "Windows" and is_msvc(self):
                # Ignored if ``self.options.driver == "sdl"
                self.cpp_info.defines.append("LV_ATTRIBUTE_EXTERN_DATA=__declspec(dllimport)")
```

**Comment by memsharded** [comment]
> sdl seams to be build as a static lib (this seams to be the default value in the sdl recipe). I'd prefer a shared lib.
Is something like this possible to pass settings to the dependency
self.dependencies["sdl"].options.shared = self.options.shared

You can use something like:
```
def configure(self):
     self.options["sdl"].shared = self.options.shared
```
You can of course configure it in the command line, or the recommended one is in the profiles like:
```
[options]
sdl/*:shared=True
```

**Comment by ghost** [comment]
thx @memsharded  you have been a great help once again. This works fine :)
