### ISSUE TITLE
self.cpp.package.set_relative_base_folder should escape "\" on Windows

### ISSUE THREAD

**Issue by ShuangLiu1992** [conan-io/conan#15446]
### Environment details

* Operating System+version: Windows
* Compiler+version: MSVC
* Conan version: 2.0.16
* Python version: 3

### Steps to reproduce

call set_relative_base_folder of an editable package on Windows, these variables will contain \ that trigger cmake error
CMAKE_INSTALL_BINDIR
CMAKE_INSTALL_SBINDIR
CMAKE_INSTALL_LIBEXECDIR
CMAKE_INSTALL_LIBDIR
CMAKE_INSTALL_INCLUDEDIR
CMAKE_INSTALL_OLDINCLUDEDIR

**Comment by memsharded** [comment]
Hi @ShuangLiu1992 

Thanks for your report.

``set_relative_base_folder`` is a private implementation detail, not documented, so it shouldn't be called by recipes.

Could you please elaborate how to trigger this error:
- Specify a minimal conanfile.py, CMakeLists.txt to reproduce
- Specify the command line to reproduce

Many thanks!

**Comment by ShuangLiu1992** [comment]
Thanks for your reply. If `set_relative_base_folder` is a private method I will avoid using it

**Comment by memsharded** [comment]
Everything that is not in the Conan docs shouldn't be used, please check https://docs.conan.io/2/introduction.html#stable

Thanks!
