### ISSUE TITLE
'cryptography<2.0.0,>=1.3.4' distribution was not found and is required by conan

### ISSUE THREAD

**Issue by nunojpg** [conan-io/conan#1544]
This started about 1 week ago.

Eg. https://travis-ci.org/nunojpg/conan-botan/jobs/255008729

**Comment by memsharded** [comment]
Have you tried to install conan first, then conan-package-tools?
Like:

```bash
pip install conan
pip install conan_package_tools
```
In your ``install.sh`` script.

**Comment by nunojpg** [comment]
Thanks, that order trick solves it.

**Comment by memsharded** [comment]
Good! Yes, it is more an issue of pip, than a conan issue.
