### ISSUE TITLE
Option to split cmake steps

### ISSUE THREAD

**Issue by xoppa** [conan-io/conan#1545]
Currently our build() method looks basically like this:

```
    def build(self):
        cmake = CMake(self)
        self.run('cmake name %s' % cmake.command_line)
        self.run("cmake --build . %s" % cmake.build_config)
```

The first cmake command generates the visual studio project, while second cmake command builds the project. However, for developing we often only want to generate the visual studio project, without actually having to wait for it to build. It would be nice if we could somehow split these steps or make the build command optional.

One option we've thought of was using an environment variable to make the second step optional. But because we need to switch this quite often, this isn't very practical. Perhaps a better options would be if we could somehow add an additional command line option, so we could do something like this:
```
conan build --generate-only
```

So we could use this in the `build()` method like this:

```
    def build(self):
        cmake = CMake(self)
        self.run('cmake name %s' % cmake.command_line)
        if not self.generate_only:
            self.run("cmake --build . %s" % cmake.build_config)
```

Would it be possible for such option to include or is there perhaps something we could already use to achieve this?

**Comment by memsharded** [comment]
Right now there is one approach, that is using scopes. But not recommended, we might try to deprecate them. 

This totally makes sense, to automatically have one variable that sets to true when the recipe is in user space (for edition with the IDE), and false when in the local cache. Is that the feature you need right? Lets try to make it for next release.

**Comment by xoppa** [comment]
Great, thanks! We often also need to fully build in user space without IDE though, e.g. when cross compiling in docker. So basing it solely on whether it's running in use space probably won't suffice. Although having such variable still makes sense and would be a great addition.

**Comment by memsharded** [comment]
It made sense if you wanted it to be automatic, but if you need full control, I think it might be too specific. What would be the problem of using and environment variable, which you can also set in the command line? The syntax will be:

```bash
$ conan install -e GEN_ONLY=True
```
Then something like: 
```python
def build(self):
        cmake = CMake(self)
        self.run('cmake name %s' % cmake.command_line)
        if not os.getenv("GEN_ONLY"):
            self.run("cmake --build . %s" % cmake.build_config)
```

I think it is already there, quite clean and idiomatic. The thing with a custom command line argument for this, is that it doesn't stop there: Why not another --only-test, so the cmake ctests are not run? Some people will use cmake install feature, to package directly form the ``build()`` method and skip the ``package()`` method definition. Should we add another ``--no-package`` command line argument.

With env-vars, you can perfectly configure any behavior you want.

What do you think?
PD: you might be interested too in the ``cmake.configure()``, ``cmake.build()``, ``cmake.test()`` methods

**Comment by xoppa** [comment]
That looks like it should work. Especially if we could combine it with the variable you mentioned to determine whether it is running in user space. That way we could use the variable to define the default behavior and use the environment variable to override it. Thanks!

**Comment by memsharded** [comment]
You might not need the user space var at all. ``os.getenv("GEN_ONLY")`` already returns ``None`` even if the variable is not defined, so that is a good default (note that the condition is not negated). 

So the non-existence of env-vars is typically equal to them having a ``False`` value, which can be safely taken as the default. Works great even if not in user space! So for example if you want to enable/disable running unitary tests while building the package, you could do:
```bash
$ conan install -e RUN_MY_TESTS=1
```
And if you have:
```python
def build(self):
        cmake = CMake(self)
        self.run('cmake name %s' % cmake.command_line)
        self.run("cmake --build . %s" % cmake.build_config)
        if os.getenv("RUN_MY_TESTS"):
             cmake.test()
```

Then it can run the unit tests even for the full dependency graph in local cache, while the default for most users would be not necessary to run the unit-tests (most likely they are already run in CI or something).

**Comment by xoppa** [comment]
Thanks, sounds great! We're going to use this approach.

**Comment by memsharded** [comment]
Good to know. Please keep us updated, and if everything works fine with that approach, this issue might be closed.

**Comment by memsharded** [comment]
I think this can be closed, no further action needed, seems the suggested approach is valid. Please reopen or comment if necessary, thanks!
