### ISSUE TITLE
Conan requires work wrongly with multiple libs with same layout.

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#1546]
@memsharded Let me add an example 3: A consumer appl. consumes two libs, appl. build outside Conan, then Conan upload to Artifactory.

### Lib1 package dir:
```
├───shaxxxxx1
│   └───bin
│   └───inc
```

### Lib2 package dir:
```
├───shaxxxxx2
│   └───bin
│   └───inc
```

Extract of conanfile.py for the consumer appl.:

``` python

    requires = "Lib1/1.2.4@twoflower2/testing" , "Lib2/1.5.1@twoflower2/testing"

    def imports(self):
      #Copy from Lib1
      self.copy("*", dst="impl/lib/Lib1/inc", src="inc") 
      self.copy("*", dst="impl/lib/Lib1/bin", src="bin") 
   
      #Copy from Lib2
      self.copy("*", dst="impl/lib/Lib2/inc", src="inc") 
      self.copy("*", dst="impl/lib/Lib2/bin", src="bin")
```

I then use `conan install .` to get these requirements into the project dir structure, but 
- it copies the Lib1 inc & bin from cache into project's dir Lib1 and Lib2
- and it copies the Lib2 inc & bin from cache into project's dir Lib1 and Lib2

-- I think I would need a `Lib1` dir after the sha1 like `.conan\data\Lib1\1.2.4\twoflower2\testing\package\shaxxxx1\Lib1` but how do I tell Conan this when doing a `package_files` for Lib1 like so: 

`conan package_files Lib1/1.2.4@twoflower2/testing --package_folder=dist -f` where the `dist` is where the inc & bin dirs are located.

-- How can I tell Conan that a `self.copy()` is only meant for just Lib1 or just Lib2?
-- Can I do a `self.copy()` on the Conan options that the libraries hold (not the consumer)?

**Comment by memsharded** [comment]
``imports`` doesnt work that way by default. The default behavior is that the scan ALL dependencies and put all the matching files inside the ``dst`` folder.

You have two approaches for this:

- Use the ``root_package`` argument, like:

```python
self.copy("*", dst="Lib1/inc", src="inc", root_package="Lib1")
self.copy("*", dst="Lib2/inc", src="inc", root_package="Lib2")
```
Or if you are fine, you could use the ``folder`` argument, like:
```python
self.copy("*", dst="inc", src="inc", folder=True)
```
It will generate a subfolder, with the name of the package, for each package you depend on.

**Comment by Twoflower2** [comment]
`root_package=` works perfectly, thanks. 

Please close.
