### ISSUE TITLE
[question] inter partition package (embedded, multiple architectures)

### ISSUE THREAD

**Issue by mjb6** [conan-io/conan#15460]
### What is your question?

Hello,
I have an embedded device with multiple cpu cores, that have different architectures (armv7 and aarch64). I would like create a package that references the flashable images for the individual cores.

In my example, lets consider the following package graph: armv7 with a rtos and an embedded component, and aarch64 with a POSIX OS and a component.

```
          pkg:sys
           ^   ^
           |   |
    pkg:rtos   pkg:posix
        ^            ^
        |            |
pkg:rtos-comp    pkg:posix-comp
```

I have a profile for the posix part and a profile for the rtos part. I can create individual packages for all posix parts or for all rtos parts.
But I cannot create the system pkg, cause of the conflict that conan sees between the different settings for posix/rtos.

I guess I would need a feature to ignore on top level certain settings (e.g. on system level, set the architecture settings to ANY but on pkg:posix level set the architecture setting to `aarch64` (and then downstream pkg:posx-component should inherit this)

Is there a solution for this in conan?

Thanks, best regards

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mjb6 

Thanks for your question.

Conan is a C/C++ "development" package manager, intended for building C/C++ libraries and applications. As such, it is not specially designed to mix in the same package binary libraries or packages from different incompatible architectures.

Said that, Conan aims to be as flexible as possible, and we have seen users pushing it and doing things like that.

A possibility would be to include the platform in the package name, as the name can be parameterized too in the command line with ``conan create . --name=pkg_rtos --version=1.0 -pr=profilertos``, and internally it could depend on ``self.requires(f"dep_{self.settings.arch}/2.0")``. (It is not completely clear in your description if you are already using different names or the package name is the same and the architecture is just a qualifier to describe the binary). Then the aggregator profile could be written as:
```
[settings]
*_rtos/*:arch=rtos
*_posix/*:arch=aarch64
....
```

Another possibility to consider would be to drop the ``arch`` as setting, and include it as ``option`` in every package. Then, the consumer package could do something like ``self.requires("pkg/0.1", visible=False, options={"*:arch": "rtos"})`` and another require to the same package but with ``self.requires("pkg/0.1", visible=False, options={"*:arch": "aarch64"})``. This might require some internal in-recipe mapping of the architecture flags to the build systems as the default ``self.settings.arch`` will not be defined and at least some of the Conan built-in system integrations might fail.

Please let me know if this helps.

**Comment by mjb6** [comment]
Hello
thanks! Appending the partition name to the package name and matching the correct settings value based on the partition name works for me!

Thank you very much!

**Comment by memsharded** [comment]
Happy to help!

Don't hesitate to open new tickets for any further question or issue that you might have. Thanks!
