### ISSUE TITLE
`self.settings.rm_safe(...)` in `def configure(self)` leads to errors when using compatibility plugins

### ISSUE THREAD

**Issue by Ariox41** [conan-io/conan#15466]
### Environment details

* Operating System+version: ubuntu 22.04
* Compiler+version: gcc 11
* Conan version: 2.0.17
* Python version: 3.10.12

### Steps to reproduce

After updating qtcreator, a binary incompatibility occurred due to the absence of 'compiler.cppstd' in the host profile. When added to compatibility.py lines `result.append({"settings": [("compiler.cppstd", "gnu17")]})`an error occurred: `ERROR: 'settings.compiler.cppstd' doesn't exist for 'gcc'.

The problem was manifested due to the zlib dependency, which has a fragment
```python3
def configure(self):
    self.settings.rm_safe("compiler.cppstd")
```

Most likely, the problem may occur in more common cases.

### Reproducible example (Linux, gcc):

```python3
#!/bin/python3

import os
import subprocess
import shutil
from typing import List
import textwrap


def main():
    build_folder = os.path.abspath("build")
    conan_home = os.path.join(build_folder, "conan2")
    conan_compability_plugin_folder = os.path.join(conan_home, 'extensions', 'plugins', 'compatibility')

    os.environ["CONAN_HOME"] = conan_home
    shutil.rmtree(build_folder, ignore_errors=True)
    os.mkdir(build_folder)
    os.makedirs(conan_compability_plugin_folder)
    
    with open(os.path.join(conan_compability_plugin_folder, "compatibility.py"), 'w') as f:
        f.write("""    
from conan import ConanFile

def compatibility(conanfile: ConanFile):
    result = []
    
    build_type_comp = []
    if conanfile.settings.get_safe('build_type') in ['Debug', 'RelWithDebInfo', 'MinSizeRel']:
        build_type_comp = [("build_type", "Release")]
        result.append({"settings": build_type_comp})


    if conanfile.settings.get_safe("compiler.cppstd") is None:
        result += [{"settings": config["settings"] + [("compiler.cppstd", "gnu17")]} for config in result]
        result.append({"settings": [("compiler.cppstd", "gnu17")]})
    return result
""")
        
    subprocess.run(["conan", "profile", "detect"]).check_returncode()
  
    lib1_folder = os.path.join(build_folder, "lib1")
    os.mkdir(lib1_folder)
    lib2_folder = os.path.join(build_folder, "lib2")
    os.mkdir(lib2_folder)
    
    subprocess.run(["conan", "new", "cmake_lib", "-d", "name=lib1", "-d", "version=0.1.0"],
                   cwd=lib1_folder).check_returncode()
    conanfile1 = open(os.path.join(lib1_folder, 'conanfile.py')).read()
    
    # The original problem manifested itself when using zlib
    conanfile1 = conanfile1.replace('def configure(self):', 'def configure(self):\n        self.settings.rm_safe("compiler.cppstd")')
    open(os.path.join(lib1_folder, 'conanfile.py'), 'w').write(conanfile1)
    
    
    subprocess.run(["conan", "build", lib1_folder, "-s", "build_type=Release"],
                   cwd=build_folder).check_returncode()
    subprocess.run(["conan", "export-pkg", lib1_folder,  "-s", "build_type=Release"],
                   cwd=build_folder).check_returncode()
    
    
    
    subprocess.run(["conan", "new", "cmake_lib", "-d", "name=lib3", "-d", "version=0.1.0", "-d", "requires=lib1/0.1.0"],
                   cwd=lib2_folder).check_returncode()
    # ERROR: 'settings.compiler.cppstd' doesn't exist for 'gcc'
    # 'settings.compiler' possible configurations are ['exception', 'libcxx', 'threads', 'version']
    subprocess.run(["conan", "build", lib2_folder, "-s", "build_type=Debug"],
                   cwd=build_folder).check_returncode()
    
if __name__ == '__main__':
    main()
```
### Temporary solution:
in  compatibility.py
```python3
if conanfile.settings.get_safe("compiler.cppstd") is None:
        allowed = True
        try:
            getattr(conanfile.settings, "compiler.cppstd")
        except ConanException:
            allowed = False
        if allowed:      
            result += [{"settings": config["settings"] + [("compiler.cppstd", "gnu17")]} for config in result]
            result.append({"settings": [("compiler.cppstd", "gnu17")]})
```

### Logs

ERROR: 'settings.compiler.cppstd' doesn't exist for 'gcc'
'settings.compiler' possible configurations are ['exception', 'libcxx', 'threads', 'version']

**Comment by memsharded** [comment]
Hi @Ariox41 

Thanks for your report, specially thanks for your detailed reproducible case, that really helps.

I have been reproducing this, and it seems the problem is indeed:
```python
if conanfile.settings.get_safe("compiler.cppstd") is None:
     result.append({"settings": [("compiler.cppstd", "gnu17")]})
```
Note the default ``compatibility.py`` implementation uses:
```
cppstd = conanfile.settings.get_safe("compiler.cppstd")
    if not compiler or not compiler_version or not cppstd:
        return []
```
If the recipe doesn't have a ``cppstd``, then it shouldn't try to fallback to another ``cppstd`` value.

If you want to check if ``cppstd`` is defined for that recipe, maybe this would be cleaner:
```python
if "cppstd" in conanfile.settings.compiler.possible_values():
        if conanfile.settings.get_safe("compiler.cppstd") is None:
            result += [{"settings": config["settings"] + [("compiler.cppstd", "gnu17")]} for config in result]
            result.append({"settings": [("compiler.cppstd", "gnu17")]})
```

Note in any case, the root cause is:

>  due to the absence of 'compiler.cppstd' in the host profile.

It is very strongly recommended to define ``compiler.cppstd`` in the profiles. Please try to do it, or if it something in QtCreator, try to report to them. 

Side note: Note that for Windows/msvc, the compatibility fallback to ``Release`` doesn't work, so maybe you want to take it into account in case you target Windows sometime. And the ``compiler.runtime_type=Debug`` should be taken into account for build-types that might be compatible.

**Comment by Ariox41** [comment]
The original problem is indeed on the QtCreator side,  and actually this approach does not work, I will have to add a local patch of the QtCreator installation.

If you think that such an error cannot occur if conan is used correctly, you can close the request. But maybe the documentation can be improved.

P.S. The solution to the problem with Qt Creator turned out to be explicitly specifying cmake variables in the configuration:
```shell
-DCMAKE_CXX_STANDARD:UNINITIALIZED=17
-DCMAKE_CXX_EXTENSIONS:UNINITIALIZED=ON
```

**Comment by memsharded** [comment]
> The original problem is indeed on the QtCreator side, and actually this approach does not work, I will have to add a local patch of the QtCreator installation.

But this ``compatibility.py`` is on your side, you shared the code, and it is in your Conan home folder, so you can customize it? I am not sure I understood.

Regarding the QtCreator side and profile, maybe @cristianadam can give some feedback here?

**Comment by Ariox41** [comment]
Although the error is caused by the code in compatibility.py, this behavior looks unexpected, and the error message does not indicate the problem, which is why this issue was created.

However, a properly written compatibility.py apparently should not contain checks for `if conan.file.settings.get_safe("...") is None`, so I close the issue.
