### ISSUE TITLE
[question] how conan determine to copy cppstd_compat.py to home or not

### ISSUE THREAD

**Issue by X1aomu** [conan-io/conan#15478]
### What is your question?

I'm writting my own compatibility extension like this

```python
from msvc_compat import msvc_compat
from gcc_compat import gcc_compat
from cppstd_compat import cppstd_compat


def compatibility(conanfile):
    compiler = conanfile.settings.get_safe("compiler")
    if not compiler:
        return []

    if compiler == "msvc":
        return msvc_compat(conanfile)

    if compiler == "gcc":
        return gcc_compat(conanfile)

    return cppstd_compat(conanfile)
```

I would like to use the default cppstd_compat implemention, thus i don't pack `cppstd_compat.py` with my whole conan config.

`conan config install <url-to-my-config>` is used in CI to import my config. Howerver `conan install`, shows an error that the `cppstd_compat.py` was not there.

```
======== Computing necessary packages ========
ERROR: Unable to load conanfile in D:\gitlab-runner\builds/0/.conan\extensions\plugins\compatibility\compatibility.py
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\gitlab-runner\builds/0/.conan\extensions\plugins\compatibility\compatibility.py", line 3, in <module>
    from cppstd_compat import cppstd_compat
ModuleNotFoundError: No module named 'cppstd_compat'
```

The question is, when will conan copy the default cppstd_compat.py to the conan home? And in my use case, how can i get to cppstd_compat.py correctly?

Additional info:

1. the conan config in CI build directory is cleared regularly, to ensure something that has been deleted in my current config can also be removed in CI build environment.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @X1aomu 

Thanks for your question.

The ``cppstd_compat.py`` file is generated together with the ``compatibility.py``, when this needs to be generated and only when it needs to be generated. They are a single plugin unit, so the plugin files are generated or not. If you want to have ``cppstd_compat.py`` in your own custom ``compatibility.py`` plugin implementation, you need to copy it to your ``conan config install`` origin folder.

**Comment by X1aomu** [comment]
Thanks for your response.

I just wanted to implement my own `compatibility()` for some known situations, then leave others fallback to the default implementation. And I would like to take no care of the default implementation, such as update `cppstd_compat.py` in case of the default implementation has changed.

Though, that's almost a pseudo requirements. The situation that needs a fallback implementation has never arrived.

Raising an exception instead of calling `cppstd_compat` is currently not bad to me.

**Comment by memsharded** [comment]
> I just wanted to implement my own compatibility() for some known situations, then leave others fallback to the default implementation. And I would like to take no care of the default implementation, such as update cppstd_compat.py in case of the default implementation has changed.

Yes, the issue is that user custom ``compatibility()`` can interact with the ``cppstd_compat.py`` one. In other words, Conan should be able to change the implementation, name, interface of ``cppstd_compat.py``, and it won't be breaking because it goes together with its own ``compatibility.py``, so it is basically an internal implementation detail. Otherwise we should document the interface and behavior of ``cppstd_compat.py`` to allow this kind of usage, and that is too much. Thanks for the feedback!
