### ISSUE TITLE
[question] Why does "Computing necessary packages" step cost too much time?

### ISSUE THREAD

**Issue by carlgump** [conan-io/conan#15474]
### What is your question?

My package depends on 6 thirdparth libraries(only one is dynamic lib). When building the package, Computing necessary packages costs a lot of time, like (8mins/10mins[total]). How to opt the process.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @carlgump 

This doesn't look right. This step takes little time even with many dozens of dependencies, there might be something weird in the network

We would need more data:
- Conan version
- OS, python version, Conan installation
- Which server are you using, is it ConanCenter? If not, please specify the server and version
- Are you running in a VPN, proxy, zscaler or similar?

**Comment by carlgump** [comment]
Conan version 2.0.11
Python 3.10.12
OS Linux 648a15cb1200 5.19.17-moon01 #1 SMP PREEMPT_DYNAMIC Wed Aug 9 07:57:52 CST 2023 x86_64 x86_64 x86_64 GNU/Linux                             # moon01 is based on ubuntu22.04
No, I don't use ConanCenter but my own ConanCenter based on local JFrog Artifactory.
No, the developing PC cannot connect to Internet but local network.

**Comment by memsharded** [comment]
Thanks for the feedback

> No, I don't use ConanCenter but my own ConanCenter based on local JFrog Artifactory.
No, the developing PC cannot connect to Internet but local network.

I suspect this is a local network or server configuration. An Artifactory connected in the local network should be quite fast, unless there is some problem with it. What is the Artifactory server version?

If you want to check how fast the client and resolution should be, removing the possible network issues, you can download the ArtifactoryCE from https://conan.io/downloadsto your machine, and test against it.

**Comment by carlgump** [comment]
======== Computing necessary packages ========
ceres/2.1.0@A/stable: Checking 11 compatible configurations:
ceres/2.1.0@A/stable: 'ff2d924d1dbb9c509580c93447de00fa9b65c729': compiler.cppstd=98
ceres/2.1.0@A/stable: '57ab7d55ced75387a77412a0d0e54530855b50ac': compiler.cppstd=gnu98
[Processing: ModuleTest]
ceres/2.1.0@A/stable: '7f358dd9f2e5aa89df414bf86b1d2448f795d51a': compiler.cppstd=11
ceres/2.1.0@A/stable: '63817c5d035a1531cd7238de461b5319e95941db': compiler.cppstd=gnu11
ceres/2.1.0@A/stable: 'b333c3a41142a35cf8c0c15c619c27bae0a1b138': compiler.cppstd=14
ceres/2.1.0@A/stable: '231beb6ce401e5e783ab87604a3593f6be4e67d5': compiler.cppstd=17
[Processing: ModuleTest]
ceres/2.1.0@A/stable: '1485d1a205c68265060cfe743e65670d9d7739c4': compiler.cppstd=gnu17
ceres/2.1.0@A/stable: Main binary package 'bdad290611981cbe8b2576ef556ddc2dd50a7fc0' missing. Using compatible package '1485d1a205c68265060cfe743e65670d9d7739c4'
eigen/3.3.4@A/stable: Checking 11 compatible configurations:
eigen/3.3.4@A/stable: 'ff2d924d1dbb9c509580c93447de00fa9b65c729': compiler.cppstd=98
eigen/3.3.4@A/stable: '57ab7d55ced75387a77412a0d0e54530855b50ac': compiler.cppstd=gnu98
[Processing: ModuleTest]
eigen/3.3.4@A/stable: '7f358dd9f2e5aa89df414bf86b1d2448f795d51a': compiler.cppstd=11
eigen/3.3.4@A/stable: '63817c5d035a1531cd7238de461b5319e95941db': compiler.cppstd=gnu11
eigen/3.3.4@A/stable: 'b333c3a41142a35cf8c0c15c619c27bae0a1b138': compiler.cppstd=14
eigen/3.3.4@A/stable: '231beb6ce401e5e783ab87604a3593f6be4e67d5': compiler.cppstd=17

Every above dep rprocessing will cost 10+ seconds.
Can skip the step after I have built the package once?

**Comment by memsharded** [comment]
> Every above dep rprocessing will cost 10+ seconds.

This is wrong, there is something broken in your network. Every of those steps should be just some milliseconds.

Yes, there are ways to disable the default cppstd compatibility, for example you can customize the ``compatibility.py`` plugin (manage it with ``conan config install``). You can also explicitly require the ``cppstd`` you want to do, in fact in Conan 2.0 it is very strongly recommended to always use ``compiler.cppstd`` defined in your profiles, and can use per-package settings to define different ``cppstd`` for different packages too

But I am not sure you want to change the ``compatibility.py``, but the network issue should be found and fixed, as it will be affecting you in other ways too.

**Comment by carlgump** [comment]
Thanks. 
I checked the network that had wrong DNS setting, which lead to long time domain name lookup.
Configuring right DNS server to /etc/resolv.conf would compute necessary packages quickly.

**Comment by AbrilRBS** [comment]
This is great to hear, thanks a lot for taking the time to report the issue, we're happy we were able to find the culprit. Feel free to open new issues should you have any additional questions, thanks! :)
