### ISSUE TITLE
[question] How to manually tell conan create about a package folder?

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#15475]
### What is your question?

Hi there!
I have a quite peculiar scenario at hand. I'm transforming existing conan 1.x packages in an artifact repo to conan 2.x, without having access to the source, so I'm only operating on export packages (containing the conanfile and manifest among other things) and the binary packages.
I have done the necessary transformations to the conanfiles and I'm packaging them using conan 2.x. All is well.
The problem is that I have to tell `conan create` somehow to include my package folder in the package creation process. I managed quite an ugly workaround by exporting the conanfile and the package folder like this:

`exports_sources = "conanfile.py", "package/*"`

and then I modififed the package function to copy the contents of my package folder to the appropriate folder and remove the unnecessary copies that conan did:

```
copy(self, "*", src=os.path.join(self.export_sources_path, "package"), dst=self.package_folder)
rmdir(self, os.path.join(self.source_folder, "package"))
rmdir(self, os.path.join(self.export_sources_path, "package"))
esFolder = os.path.join(os.path.dirname(self.export_sources_path), "es")
rmdir(self, os.path.join(esFolder, "package"))
```
I know, it's ugly, but couldn't find any other way. Since `conan create` does everything, I couldn't find a way to actually query the package folder in the conan cache to copy these files manually, also the `package_folder` attribute changes values between stages too.
However, by doing it this way, every time `conan create` is invoked, it creates a new recipe hash as well, resulting in the upload of multiple export packages, even if the actual conanfile did not change. I'd need to come up with a solution where I have a single export package uploaded with several different package versions.

Any ideas are welcome, thank you!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @donlk 

Thanks for your question.

>  Since conan create does everything, I couldn't find a way to actually query the package folder in the conan cache to copy these files manually, also the package_folder attribute changes values between stages too.

Yes, unfortunately this is not possible, modifying folders after a package is created might not work correctly, as it invalidate revisions, and revisions are used to identify artifacts to upload and download.

Could  you please clarify how are you getting the previous binaries? You download the binaries first, and then you mean you are executing the ``conan export-pkg`` command? That should not require to ``export`` the "package/*" folder at all, you should be able to encode it directly in the ``package()`` method, using the current ``self.build_folder`` that will be pointing to your local user folder containing the binaries.

**Comment by donlk** [comment]
I am using `conan download` to get the conan 1.x export and binary packages. I am not using `conan export-pkg` as it would seem redundant compared to `conan create`. Should I use it though? `conan create` is such a good way to validate the correctness of the transformed conanfiles though, I would be hesitant to abandon it.

Can I use `conan create` and `conan export-pkg` in tandem?

**Comment by memsharded** [comment]
The thing is that if you cannot build from source, how will the ``conan create`` provide any value? It is still not reproducible build, you still depend on binaries that have to be manually downloaded and put close to that recipe that is creating the package. When you do ``exports_sources`` the ``package/*`` pre-compiled binaries, you also end with packages that will at least double the size, but if you have to do many configurations, then the export should contain all of them at the same time, and only package one of them in each configuration, so it will be a very inefficient package. 

If you are ok with this, then yes, you might use the ``conan create``.

But what you are seeing with the revisions is that, the exported things cannot change for different configurations, it has to be the same for all binary configurations. Something like this:
- Download all the possible different configurations you need to repackage
- Put the binaries to export in such ``package/*`` folder, with some subfolders like ``package/debug/x64/shared/...`` as your variability needs
- Your ``package()`` method uses this to package the right binaries using ``self.settings.arch``, ``self.options.shared``, etc, to address the particular folder you need to package for the configuration

**Comment by donlk** [comment]
The merit of `conan create` stems from the fact that it invokes all appropriate ConanFile functions from beginning to end. Of course, we have to remove the generational/build related functions, but - for example - `package_info()` gets called as well, essentially validating that function, so as others.
In my experience `conan export-pkg` does no such thing. It certainly invokes the `package()` method, but not much else.
This kind of validation is essential when you want to automate this whole process.

But you're right, I can call `conan create` just for validation and then `conan export-pkg` for compression. Thanks for the tip!

**Comment by memsharded** [comment]
> In my experience conan export-pkg does no such thing. It certainly invokes the package() method, but not much else.
This kind of validation is essential when you want to automate this whole process.

Oh, ``conan export-pkg`` also runs in Conan 2.0 any ``test_package`` you have there, then forcing the execution of the ``package_info()`` method and the validation if the package is correct. So it invokes: ``export()``, ``export_sources()``, ``generate()``, ``package()``, ``package_info()``, it should be quite complete. The only ones that do not run are ``source()`` and ``build()``, they can be typically executed locally, like ``conan source`` + ``conan build`` + ``conan export-pkg`` for local validation.

**Comment by donlk** [comment]
I tested it, export-pkg does not call package_info.
Let me quote your comment on a previous issue, where you stated [just this](https://github.com/conan-io/conan/issues/9403#issuecomment-895446249).

**Comment by memsharded** [comment]
> I tested it, export-pkg does not call package_info.

Yes, it will do it if there is a ``test_package`` folder to test it, in Conan 2.0.

https://github.com/conan-io/conan/issues/9403#issuecomment-895446249 was a Conan 1.X report, when this was not a feature, it was that way by design in Conan 1.X. Now in Conan 2.0, the ``test_package`` will work for ``conan export-pkg`` in the same way it works for ``conan create``, calling ``package_info()``

**Comment by donlk** [comment]
I've read about this [test_package](https://docs.conan.io/2/tutorial/creating_packages/test_conan_packages.html) concept you're referring to, but I'm struggling to grasp the meaning of it in my scenario. I already have my packages, why would I create an additional test_package? Or am I missing something? Could you point me in the right direction?

**Comment by memsharded** [comment]
The ``test_package`` is a very convenient mechanism to guarantee that the package creation (either via ``create`` or ``export-pkg`` command) is creating working packages. You don't have your packages yet, you are just creating them. After a package is created 
 and even when the package is there, there are a ton of things that can go wrong:
- the package didn't package the headers
- the package didn't package the libraries
- the package put the artifacts in different, unexpected folders
- the package artifacts are not the one expected for the current configuration
- there are bugs in ``package_info()`` method
- etc

The only way to make sure the package is ok, is to actually use it from another project. This is what the ``test_package`` automates.

Having an integrated ``test_package`` together with your package ``conanfile.py`` is extremely useful to guarantee some minimum correctness of the package, and it is launched automatically for every ``conan create`` and ``conan export-pkg`` command.

**Comment by memsharded** [comment]
Hi @donlk 

Following up on this ticket. Did the last comment clarified the ``test_package``? Please let me know if there are any further questions.

**Comment by donlk** [comment]
Yes, the following test conanfile works to make export-pkg invoke package_info:
```
from conan import ConanFile

class MyTestPkg(ConanFile):
    
    def requirements(self):
        self.requires(self.tested_reference_str)

    def test(self):
        pass
```

Since we cannot generate test conanfiles for all packages in an automatic fashion, this will have to do for now.
Thanks for the help!
