### ISSUE TITLE
Support AutoTools CC_FOR_BUILD variable

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#15486]
### What is your suggestion?

Hello
Conan 2.0.16

I am cross building various packages.
I have both a build profile and host profile which both has tool_requires to their respective toolchain packages.
These toolchain packages define (among other things) `tools.build:compiler_executables`.
This works well in many cases.
But sometimes I come across packages that build with autotools and uses the `CC_FOR_BUILD` variable to find the compiler for the build host. These packages always find my system installed `gcc`. I do not want that.

I suggest that if I have a build profile that define `tools.build:compiler_executables` in the build context then AutoToolsToolchain should define the `CC_FOR_BUILD` variable to point to the compiler here.

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Sorry this was not responded back then. 
There is this other thread that is touching the same aspect: https://github.com/conan-io/conan/issues/15878

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/16391 merged, this will be released in next Conan 2.4 soon
