### ISSUE TITLE
[question] Setting build tools options dynamically (Conan 2)

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15488]
### What is your question?

For some reason I need to configure build tool options dynamically. The following worked in Conan 1.x:
```python
    def build_requirements(self):
        self.tool_requires("tool/1.0")

    def configure(self):
        self.options["tool"].an_option = "value"
```
but it doesn't work anymore in Conan 2.x, I have to do something like this:

```python
from conan import conan_version
CONAN_V2 = conan_version >= '2'

...
    def build_requirements(self):
        if CONAN_V2:
            self.tool_requires("tool/1.0", options={"an_option": "value"})
        else:
            self.tool_requires("tool/1.0")

    def configure(self):
        if not CONAN_V2:
            self.options["tool"].an_option = "value"
```
Why `self.settings` assignments are ignored in Conan 2.x for build tools? Is it possible to restore 1.x behavior in 2.x?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question.
In theory you should be able to do something simpler like:

```python
default_options = {"tool/*:an_option": "value"}  # works in 1.X, doesn't interfere with 2.0
default_build_options = {"tool/*:an_option": "value"}  # works in 2.0, doesn't interfere with 1.X

def build_requirements(self):
    self.tool_requires("tool/1.0")
```

Can you please try this approach?

**Comment by db4** [comment]
Hi @memsharded

Thanks for the reply, but your proposal won't work for me, as I wrote, I calculate the option value **dynamically** in the recipe, it's not a constant. But why `self.options["pkg"]` assignment is OK for host requirements but ignored for build ones? Conan 1.x behavior seems to be more logical (I use 2 profiles for Conan 1.x as well)

**Comment by memsharded** [comment]
Do you mean, you want to be able to define different values in ``configure()`` method? This also works:

```python
default_build_options = {}

def configure(self):
    if something:
             self.default_build_options["mydef/*:shared"] = "somevalue"
```
So values can also be defined dynamically

> But why self.options["pkg"] assignment is OK for host requirements but ignored for build ones?

Conan 1.X had a couple of gaps/issues:
- Unable to override options from the downstream consumer, like in the profiles, for build-requires
- Impossible to define different options for requires and tool-requires for the same dependency (like ``protobuf`` both in the host and build context)

So Conan 2 defined ``default_build_options`` and ``self.requires(..., options=)`` mechanisms to be able to solve this issue (and the profiles precedence was fixed too)

**Comment by db4** [comment]
Yes, that works. Thanks a lot!
