### ISSUE TITLE
[question] Please, help to update from conan 2.0.13 without rebuilding packages

### ISSUE THREAD

**Issue by apyvovar** [conan-io/conan#15487]
### What is your question?

Hi. In our organisation we have conan 2.0.13 (installed as `python3 -m pip install conan -v conan==2.0.13`). In our private repository we store conan packages without sources (binaries only). Those packages, obviously, built with conan 2.0.13.

The problem: if we update conan to latest version, we're having `Missing binaries` problem for all required packages. 

As far, as I understand, in one of conan versions, introduced after 2.0.13, something changed in conan's internal databases, that invalidates package ID's of requested packages. So packages, created with 2.0.13 or previous versions, so they are no longer accepted and conan requests to rebuild them. The most obvious fix is, of course, to rebuild the package, but unfortunately, in my case that's impossible, because, as previously noted, we don't distribute sources with packages.

The best option for me, would be if conan introduce some fix, so that newer versions of conan somehow could accept packages with ID's, created with 2.0.13 or earlier. Is this possible?

Otherwise, I'd need to gradually rebuilt all packages in whole organization with latest conan. The only way to handle it, which I can see now, is something like that on CI:
- create and upload package with conan 2.0.13 (so that projects and other packages can use it with current conan 2.0.13)
- remove `~/.conan2`, install latest conan
- create and upload the same package with latest conan
- remove `~/.conan2`, install conan 2.0.13, (so that everything with old packages remain buildable).
And this should be done for all packages.

Later, when all packages are updated in all branches of all projects, the whole organisation (devs and CI) can update to latest conan.

It's so inconvenient, I'd really like to avoid all of this. Maybe you could think of other way? (my hopes still that it can be fixed by conan).
Thank you.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @apyvovar 

Thanks for your report.
It would be necessary to understand what was the cause of changing package-ids. Conan latest 2.0.X didn't change all the package_ids. It is true that there was a bug fix that affected some special cases of ``confs`` in package-ids, but that should be something quite exceptional, maybe this is the case?

If you could report what are the ``conaninfo.txt`` of some packages that have the "missing binaries" in 2.0.13 and if you rebuild it in 2.017, and share both ``conaninfo.txt`` that would help a lot, and based on that we can try to think of possible approaches.

**Comment by apyvovar** [comment]
Hello, @memsharded .

I've managed to create minimal reproducable example of the problem. In short - looks like the issue can be reproduced by calling `self.info.clear()` from `python-require` package - binaries, created with 2.0.13, become `Missing` with 2.0.17.
Please, take a look.

[archive.zip](https://github.com/conan-io/conan/files/14073434/archive.zip)


Steps to reproduce:
1. Remove `~/conan2` dir. Set up and configure conan of version `2.0.13`
2. Unpack, execute `run_test.sh`. Be aware, that at some point, script will try to update conan using `pip3 intall --upgrade conan` command. Change it to appropriate one, if that's not desirable.

**Comment by memsharded** [comment]
Thanks for the reproducible case @apyvovar 
I have a quick question, why would you do a ``self.info.clear()`` for all packages containing ``settings`` and compiled binaries? That is basically destroying all the binary and ``package_id`` information? 

I guess it is only part of the minimal reproduction, but not something that you are doing in practice for all your binaries, is it?

I know understand this is coming from https://github.com/conan-io/conan/pull/15285, where an important bug in the ``self.info.clear()`` was fixed. Packages before 2.0.15 were being affected by ``python_requires`` even if they declared their independence via ``self.info.clear()``

**Comment by memsharded** [comment]
In your case, if you'd like to maintain the influence of ``python-requires`` in the ``package_ids`` the best would be to change the ``package_id()`` method in your ``python-require`` to:

```python
          def package_id(self):
                self.info.settings.clear()
                self.info.options.clear()
                self.info.requires.clear()
                self.info.conf.clear()
                self.info.build_requires.clear()
```
this would keep the package_id invariant from 2.0.13 to 2.0.17. Though it will still maintain the erroneous influence of the ``python-require`` in consumers that shouldn't have it, you should remove that and go back to the ``self.info.clear()`` when you can re-build your binaries.

**Comment by apyvovar** [comment]
> why would you do a self.info.clear() for all packages containing settings and compiled binaries?

In practice, the issue is actually regarding header-only libraries with tests. Real conanfile is basically almost the same as in [documentation](https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/header_only_packages.html).

> this is coming from https://github.com/conan-io/conan/pull/15285

Does it mean, the issue should affect only `self.info.clear()`? If so, then it's, basically, only about header-only libraries and that's a lot easier to handle. I thought, that all packages are affected. Sorry for misinformation in original post.

**Comment by memsharded** [comment]
> In practice, the issue is actually regarding header-only libraries with tests. Real conanfile is basically almost the same as in [documentation](https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/header_only_packages.html).

Good

> Does it mean, the issue should affect only self.info.clear()? If so, then it's, basically, only about header-only libraries and that's a lot easier to handle. I thought, that all packages are affected. Sorry for misinformation in original post.

Yes, this one is only about header-only with ``self.info.clear()``.
Not a problem at all, thanks very much for the reproducible case and all the feedback.

**Comment by apyvovar** [comment]
Thank you for help.
