### ISSUE TITLE
[bug] Building x86 version of icu library using MSYS2 subsystem results in an error: The system cannot find the path specified.

### ISSUE THREAD

**Issue by tmiseikis** [conan-io/conan#15482]
### Environment details

* Operating System+version: **Windows 10**
* Compiler+version: **msvc 192**
* Conan version: **conan 2.0.17**
* Python version: **Python 3.12.0**

### Description

Hi, I originally created this bug on conan-center-index repo (conan-io/conan-center-index#22446), but was asked to do it here instead as it might be conan client related.

I'm trying to install 32-bit version of icu 74/2 library. Since it doesn't exist in the conan repository, conan tries to build it. I am using MSYS2 subsystem and building it with msvc 192 compiler.

If you check the logs below, the error happens when it is trying to execute: 

`"/c/users/XXX/.conan2/p/b/icu28a954e529410/b/src/source/configure" ...`

which ends up in an error: "**The system cannot find the path specified.**", which is a classic Windows error that is shown when the given path does not exist. I can get the same error if I simply paste the command in Windows command line. However, if I first enter bash shell and run the command manually - it works fine. So it looks like conan (or icu recipe?) is trying to execute this command without entering the bash shell first? Or perhaps something is missing in my MSYS2 subsystem setup?

What I have tried:
1) Enter bash shell then run conan install -> same error
2) Switch compiler to gcc -> same error
3) Set "**tools.microsoft.bash:active=true**", enter bash shell and run conan install -> Results in a new error: 
```
icu/74.2: ERROR:
Package '6ed54ede16828530e6423ff755551de025f84337' build failed
icu/74.2: WARN: Build folder C:\Users\XXX\.conan2\p\b\icu27f1bfd7bc668\b\build-release
ERROR: icu/74.2: Error in build() method, line 204
        autotools.configure(build_script_folder=os.path.join(self.source_folder, "source"))
        ConanException: Cannot wrap command with different envs,['C:\\Users\\XXX\\.conan2\\p\\b\\icu27f1bfd7bc668\\b\\build-release\\conan\\conanbuild.bat'] - ['C:\\Users\\XXX\\.conan2\\p\\b\\icu27f1bfd7bc668\\b\\build-release\\conan\\conanbuild.sh']
```

### Conan profile

```
[settings]
os=Windows
arch=x86
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=192

[conf]
tools.microsoft.bash:path=C:/msys2/usr/bin/bash.exe
tools.microsoft.bash:subsystem=msys2
```

### Steps to reproduce

1) Create win32 file with profile settings above.
2) Run: conan install --requires=icu/74.2 --build=missing --profile:build=win32 --profile:host=win32

### Logs

<details><summary>Click to expand log</summary>

```
C:\project\a>conan install --requires=icu/74.2 --build=missing --profile:build=win32 --profile:host=win32

======== Input profiles ========
Profile host:
[settings]
arch=x86
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[conf]
tools.microsoft.bash:path=C:/msys2/usr/bin/bash.exe
tools.microsoft.bash:subsystem=msys2

Profile build:
[settings]
arch=x86
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[conf]
tools.microsoft.bash:path=C:/msys2/usr/bin/bash.exe
tools.microsoft.bash:subsystem=msys2


======== Computing dependency graph ========
Graph root
    cli
Requirements
    icu/74.2#2c5797e68b97c6d12883397c753880cc - Cache

======== Computing necessary packages ========
icu/74.2: Checking 2 compatible configurations
icu/74.2: Compatible configurations not found in cache, checking servers
icu/74.2: '102fb057e12423c5ab43a232ed4295ca00786c97': compiler.cppstd=17
icu/74.2: 'ea1f37a2c1cfdf858965820fd3119f9284e66621': compiler.cppstd=20
Requirements
    icu/74.2#2c5797e68b97c6d12883397c753880cc:6ed54ede16828530e6423ff755551de025f84337 - Build

======== Installing packages ========

-------- Installing package icu/74.2 (1 of 1) --------
icu/74.2: Building from source
icu/74.2: Package icu/74.2:6ed54ede16828530e6423ff755551de025f84337
icu/74.2: Copying sources to build folder
icu/74.2: Building your package in C:\Users\XXX\.conan2\p\b\icu28a954e529410\b
icu/74.2: Calling generate()
icu/74.2: Generators folder: C:\Users\XXX\.conan2\p\b\icu28a954e529410\b\build-release\conan
icu/74.2: Generating aggregated env files
icu/74.2: Generated aggregated env files: ['conanbuild.sh', 'conanbuild.bat', 'conanrun.bat']
icu/74.2: Calling build()
icu/74.2: Apply patch (file): patches/0001-69.1-fix-mingw.patch
icu/74.2: Calling:
 > "/c/users/XXX/.conan2/p/b/icu28a954e529410/b/src/source/configure" --disable-shared --enable-static --prefix=/ --bindir=${prefix}/bin --sbindir=${prefix}/bin --libdir=${prefix}/lib --includedir=${prefix}/include --oldincludedir=${prefix}/include --datarootdir=${prefix}/lib --enable-release=yes --enable-debug=no --enable-dyload=yes --enable-extras=no --enable-icuio=yes --disable-layoutex --disable-layout --enable-tools=yes --enable-tests=no --disable-samples --with-library-bits=32
icu/74.2: RUN: "/c/users/XXX/.conan2/p/b/icu28a954e529410/b/src/source/configure" --disable-shared --enable-static --prefix=/ --bindir=${prefix}/bin --sbindir=${prefix}/bin --libdir=${prefix}/lib --includedir=${prefix}/include --oldincludedir=${prefix}/include --datarootdir=${prefix}/lib --enable-release=yes --enable-debug=no --enable-dyload=yes --enable-extras=no --enable-icuio=yes --disable-layoutex --disable-layout --enable-tools=yes --enable-tests=no --disable-samples --with-library-bits=32
conanvcvars.bat: Activating environment Visual Studio 16 - x86 - winsdk_version=None - vcvars_ver=14.2
[vcvarsall.bat] Environment initialized for: 'x86'
The system cannot find the path specified.

icu/74.2: ERROR:
Package '6ed54ede16828530e6423ff755551de025f84337' build failed
icu/74.2: WARN: Build folder C:\Users\XXX\.conan2\p\b\icu28a954e529410\b\build-release
ERROR: icu/74.2: Error in build() method, line 204
        autotools.configure(build_script_folder=os.path.join(self.source_folder, "source"))
        ConanException: Error 1 while executing
```

</details>

**Comment by memsharded** [comment]
Hi @tmiseikis 

Thanks for your report. 
It is not completely clear what is your issue. Specifying
```
tools.microsoft.bash:path=C:/msys2/usr/bin/bash.exe
tools.microsoft.bash:subsystem=msys2
```
is unnecessary, because the ``icu`` recipe will have ``msys2/cci.latest`` as "tool-require", so using your profile without those lines works fine.

Running directly from an msys2 terminal for MSVC compiler can be a bit challenging. For example the necessary execution of ``vcvars.bat`` to activate the configuration of msvc doesn't work right (at least in my experience, I have just re-tried, and a bare attempt to activate the enviroment via ``conanbuild.bat`` fails in ``msys2`` terminal, and it works fine in other terminals.

**Comment by tmiseikis** [comment]
Hi @memsharded,

Unfortunately, my application is 32-bit, so I am building 32-bit version of `icu` and it looks like `msys2/cci.latest` only supports x64:

```
======== Installing packages ========
ERROR: There are invalid packages:
msys2/cci.latest: Invalid: Only Windows x64 supported
```

So I am specifying `msys2` subsystem where I have installed 32-bit toolchain: `mingw-w64-i686-toolchain`.

**Comment by memsharded** [comment]
Thanks for the feedback.

If it is possible to have a msys2 that supports 32-bit, maybe the easiest would be to tune the ``msys2`` recipe locally, do a ``conan create`` (and upload to your server to avoid building it from source again and again), and try to see if it works? Having ``msys2`` as a Conan package is very convenient both for developers and CI, and as shown, it can provide the functionality to do builds inside ``msys2`` for packages like ``icu`` and using the ``msvc`` compiler that would be challenging otherwise.

I'd suggest to try that, please let me know.

**Comment by SpaceIm** [comment]
Just to check whether your profiles are correct: irrespective of arch you are targeting, is your build machine 64 bits or 32 bits?

Is there any strong reason for you to run conan from msys2 terminal? You can absolutely run conan from powershell or Cmd terminal, even if icu requires a shell at build time under the hood (as soon as you specifiy `tools.microsoft.bash:path` and `tools.microsoft.bash:subsystem` in your profiles, or eventually let recipe uses msys2 from conancenter (but indeed it requires a 64 bits build machine)).

> So I am specifying `msys2` subsystem where I have installed 32-bit toolchain: `mingw-w64-i686-toolchain`.

This `mingw-w64-i686-toolchain` is not used at all in your context, because you are telling conan to use msvc.

**Comment by tmiseikis** [comment]
Hi @memsharded @SpaceIm . Thanks a lot for your comments. I've been definitely doing things incorrectly. My build machine is 64-bit, but I'm trying to build 32-bit libraries. However, I have specified 32-bit architecture for both build and host profiles. After I changed the arch for the build profile to 64-bit everything seems to work now! Thank you a lot!

**Comment by memsharded** [comment]
Great, happy that you found the issue and it is working now, thanks for letting us know!
