### ISSUE TITLE
Force a recipe file to always run no matter if there is a current version in cache

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#15480]
### What is your question?

When running conan create on a recipe file is there a way to make it always rerun even though it may exist in conan cache. The build_policy does not seem to have an option of "always"

We have a recipe file that autogenerates a source file with a build id that consist of a timestamp and other data and need it to recompile the source file everytime conan create is used on the recipe file.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

Thanks for your question.

Please read from the docs:

https://docs.conan.io/2/tutorial/creating_packages/handle_sources_in_packages.html

> It is expected that retrieving the sources in the future produces the same results. Using mutable source origins, like a moving reference in git (e.g HEAD branch), or the URL to a file where the contents may change over time, is strongly discouraged and not supported. Not following this practice will result in undefined behavior likely to cause breakages

https://docs.conan.io/2/knowledge/guidelines.html

> Sources used in recipes must be immutable. Once a recipe is exported to the Conan cache, it is expected that the sources are immutable, that is, that retrieving the sources in the future will always retrieve the exact same sources. It is not allowed to use moving targets like a git branch or a download of a file that is continuously rewritten in the server. git checkouts must be of an immutable tag or a commit, and download()/get() must use checksums to verify the server files doesn’t change. Not using immutable sources will be undefined behavior.

As such, auto-generating source that changes overtime cannot happen in the ``source()`` method. There must be something that uniquely correlates the package sources origins (exports, exports-sources, sources data in ``conandata.yml``, etc) and the recipe revision. If you want to do such, you can try:

- Generating the code first, then making sure it is part of the ``exports_sources =`` and it is exported with the recipe. It will create a new ``recipe-revision`` every time, and it will require to re-build
- Generate the code in the ``export_sources()`` method, this will also make the ``recipe-revision`` to change, requiring a new build everytime
- Generate the source code in the ``build()`` method, and force the build on the command line when you want with ``--build=mypkg/*`` (this is the default of ``conan create``, so then putting the code generation in ``build()`` method should work)

**Comment by Ed-CMI** [comment]
Hi Diego

For this option here

> Generate the code in the export_sources() method, this will also make the recipe-revision to change, requiring a new build everytime

Can the export_source be used to pull some templates from gitlab first and then generate the source file?

**Comment by memsharded** [comment]
> Can the export_source be used to pull some templates from gitlab first and then generate the source file?

Yes, I think so, it would be a bit slow, but nothing dramatic if you do a download of some text file and not a full ``git clone`` of a repo. The method executes at every ``export`` execution (``conan export`` and ``conan create``), which seems what you want, and the ``recipe-revision`` is computed after the methods run, so whatever replacements happen there will be processed correctly towards the recipe-revision later.

**Comment by memsharded** [comment]
I am closing this ticket as staled, but please re-open if there is any further question or issue, or create new tickets. Thanks!
