### ISSUE TITLE
[question] Migration of `cpp_info` statements

### ISSUE THREAD

**Issue by bomut** [conan-io/conan#15481]
### What is your question?

I'm working on a Conan recipe file migration tool (to migrate Conan recipes from version 1.x to 2.x).

I have trouble understanding how to syntactically transform certain `build_modules` statements. The [migration guide](https://docs.conan.io/1/migrating_to_2.0/properties.html#migrating-components-information) states the following:

The statement:
```python
def package_info(self):
    ...
    self.cpp_info.components["mycomponent"].build_modules.append(os.path.join("lib", "mypkg_bm.cmake"))
    ...
```
becomes:
```python
def package_info(self):
    ...
    self.cpp_info.set_property("cmake_build_modules", [os.path.join("lib", "mypkg_bm.cmake")])
    ...
```
The guide also explicitly states "*The property "cmake_build_modules" can't be declared in a component, do it in self.cpp_info*".

So if I have the following statement, how would the migration to the Conan 2.x syntax look like?
```python
def package_info(self):
    ...
    self.cpp_info.components[component_name].build_modules["cmake_find_package"] = [<first_path>, <second_path>]
    ...
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @bomut 

Thanks for your question.

Your method should be:
```python
def package_info(self):
    ...
    self.cpp_info.set_property("cmake_build_modules", [<first_path>, <second_path>])
```

The documentation means that ``cmake_build_modules`` cannot be defined per-component, as they are a cmake-thing, so they are always global to the package, and can only be defined in the global ``self.cpp_info``, not in components.

**Comment by bomut** [comment]
Alright, understood. Thank you for the fast reply!
