### ISSUE TITLE
[question] Access host & target OSs in generate method

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#15490]
### What is your question?

Hello,

I am building a project which contains both .NET & C++ code. For the .NET parts, I am using commands in cmake, such as `dotnet build` and `dotnet publish`.

However, some of the .NET executables need to be built for a target OS, while some others should be built for the "building" OS. Fortunately, conan holds the `host` and `build` OSs info in the matching profiles.

For now, I do something like this:

```python
def generate(self):
	tc = CMakeToolchain(self)
	if self.settings.os == "Windows":
		tc.cache_variables["DOTNET_TARGET_OS"] = "win"
	elif self.settings.os == "Linux":
		tc.cache_variables["DOTNET_TARGET_OS"] = "linux"
	elif self.settings.os == "Macos":
		tc.cache_variables["DOTNET_TARGET_OS"] = "osx"
	tc.generate()
	d = CMakeDeps(self)
	d.generate()
```

But it looks like `self.settings.os`'s content depends on the order of the profiles passed through the CLI. Would it be possible to access the host & build profiles info in order to fill in other variables that would depend specifically on one of these? Something like:

```python
def generate(self):
	tc = CMakeToolchain(self)
	if self.host.settings.os == "Windows":
		tc.cache_variables["DOTNET_TARGET_OS"] = "win"
	elif self.host.settings.os == "Linux":
		tc.cache_variables["DOTNET_TARGET_OS"] = "linux"
	elif self.host.settings.os == "Macos":
		tc.cache_variables["DOTNET_TARGET_OS"] = "osx"
	tc.generate()
	if self.build.settings.os == "Windows":
		tc.cache_variables["DOTNET_BUILD_OS"] = "win"
	elif self.build.settings.os == "Linux":
		tc.cache_variables["DOTNET_BUILD_OS"] = "linux"
	elif self.build.settings.os == "Macos":
		tc.cache_variables["DOTNET_BUILD_OS"] = "osx"
	tc.generate()
	d = CMakeDeps(self)
	d.generate()
```

Thanks in advance

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your question.
I am not fully sure about the issue is the "order" of profiles, as long as they are ``-pr:h/--profile:host`` and ``-pr:b/--profile:build``, there shouldnt be an issue.

I think that you might be looking for the ``self.settings_build`` attribute, that you can already use for your purpose, can you please try it? just ``self.settings_buid.os``, etc, should work.

For cases of compiling cross-compiling tools, there is even the ``self.settings_target``, attribute that can be used for the same, and it can also be made part of the ``package_id`` (to have different binaries for executables that depend on the target platform)

**Comment by Todiq** [comment]
Hello @memsharded,

`self.settings_build` does the job, thank you. Something else happened: I am apparently not able to run `if arch in ["x86_64", "x64"]` if arch is set to `self.settings_build.arch`. It leads to:

```powershell
ERROR: conanfile.py (castdotnet/1.0): Error in generate() method, line 98
        dotnet_target_arch = self._get_dotnet_arch(self.settings_build.arch)
while calling '_get_dotnet_arch', line 69
        if arch in ["x86_64", "x64"]:
        ConanException: Invalid setting 'x64' is not a valid 'settings.arch' value.
Possible values are ['x86', 'x86_64', 'ppc32be', 'ppc32', 'ppc64le', 'ppc64', 'armv4', 'armv4i', 'armv5el', 'armv5hf', 'armv6', 'armv7', 'armv7hf', 'armv7s', 'armv7k', 'armv8', 'armv8_32', 'armv8.3', 'arm64ec', 'sparc', 'sparcv9', 'mips', 'mips64', 'avr', 's390', 's390x', 'asm.js', 'wasm', 'sh4le', 'e2k-v2', 'e2k-v3', 'e2k-v4', 'e2k-v5', 'e2k-v6', 'e2k-v7', 'riscv64', 'riscv32', 'xtensalx6', 'xtensalx106', 'xtensalx7']
Read "http://docs.conan.io/2/knowledge/faq.html#error-invalid-setting"
```

However, this works fine if `arch` is set to `self.settings.arch` or if I replace it with `if str(arch) in ["x86_64", "x64"]` (cast to string). Is it something expected?

**Comment by memsharded** [comment]
``x64`` is not a recognized ``settings.yml`` architecture, the right value should always be ``x86_64``.

Casting settings to ``str()`` eliminates the checks for correctness of settings, but it will also allow bugs like typos to pass, so they should be used with caution. I'd recommend using ``x86_64`` as value, and if some tool requires a different value, then map that value directly to it in the recipe, but not changing the input settings, like:
```python
# dirty, just the idea
some_tool_input = {"x86_64": "x64"}.get(str(self.settings.arch), str(self.settings.arch))
```

**Comment by Todiq** [comment]
Hello,

Thanks for the proposition. In the end, I simply did something as simple as:

```python
def _get_dotnet_arch(self, arch):
	if arch == "x86_64":
		return "x64"
	elif arch == "armv8":
		return "arm64"
	return None
```

I am stuck with python 3.9, thus not able to use `switch ... case`

I then assign the return value to a variable to be able to pass it to the different `dotnet` commands
