### ISSUE TITLE
[question] Exported sources are packaged into subfolders

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#15493]
### What is your question?

Hello!
Scenario:
I have a library where the conanfile.py imports a module from another python file. In order for correct conanfile evaluation I export these files the following way:
```
def export(self):
    copy(self, 'example.py', dst=self.export_folder, src='.')
    copy(self, '.coveragerc', dst=self.export_folder, src='.')
```
All is well, the files will be in the same folder in the cache as the conanfile.

However, when conan 2.0 creates the export package, it puts these files into subfolders:
```
conan_export.tgz
    lib_b7533b345g3
        e
            example.py
            .coveragerc
```
This is a problem, as when the library is downloaded by another one, the conanfile cannot import the module from example.py, as it resides under two subfolders.
I assume I'm doing the export correctly, as the [doc says](https://docs.conan.io/2.0/reference/conanfile/methods/export.html):
`Only files that are necessary for the evaluation of the conanfile.py recipe must be exported with this method. `

Where am I going wrong?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @donlk 

I am not sure what is the issue, I can't reproduce. 
The following test works fine:
```python
    def test_python_export(self):
        helpers = textwrap.dedent("""\
            def build_helper(output):
                output.info("Building!!!!")
            """)

        file_content = textwrap.dedent("""\
            from conan import ConanFile
            from myhelper import build_helper

            class ConanFileToolsTest(ConanFile):
                exports = "*"

                def build(self):
                    build_helper(self.output)
            """)

        client = TestClient()
        client.save({"myhelper.py": helpers,
                     "conanfile.py": file_content})
        client.run("create . --name=pkg --version=0.1")
        print(client.out)
        assert "pkg/0.1: Building!!!!" in client.out
```
Conan puts the files, including the ``conanfile.py`` under such ``e`` folder, so the ``conanfile.py can import without issues the exported "helpers" python file.

**Comment by donlk** [comment]
Interesting, I've found the following code in `conans/client/cmd/uploader.py`:
```
files, symlinked_folders = gather_files(export_folder)
...
# Files NOT included in the tgz
files.pop(CONANFILE)
files.pop(CONAN_MANIFEST)
```
This means that the conanfile and manifest are deliberately excluded from the export package.

**Comment by memsharded** [comment]
They are not in the ``tgz``, because they are managed independently. 
Still the ``tgz`` is an internal implementation detail, it is not recommended to use it directly, in the Conan cache the files will be together and work correctly.

**Comment by donlk** [comment]
Thanks for the response.
It turned out the issue was caused by my incorrect implementation of patching uploader.py to compress artifacts in parallel using pigz. Fixed it and the issue was solved too. Sorry for wasting your time :/
Closing the issue.
