### ISSUE TITLE
Web site could display header-only libraries better

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#155]
This is one of the header-only libraries I have packaged so far:
https://www.conan.io/source/catch/1.3.0/TyRoXx/stable

A "binary" package without any options looks strange on the web site:
![unbenannt](https://cloud.githubusercontent.com/assets/941829/12988228/ff94f342-d0ff-11e5-9ec6-391ed529d35e.png)

Maybe it would be more helpful if the web site could optionally say that the package is header-only and requires no platform-specific binaries.

**Comment by lasote** [comment]
We cannot presume that a conanfile without options or uploaded packages should be a header only library.
In this case, Why don't you upload the package with the headers?

**Comment by TyRoXx** [comment]
Thank you. You didn't even see that I had in fact uploaded the built package. That's exactly what I mean.

Why can't we define an optionless package description as headers-only?

**Comment by lasote** [comment]
Oh! I understand now what's the problem. :+1:

**Comment by lasote** [comment]
Fixed and deployed!
