### ISSUE TITLE
[feature] upload the binary package just created with `create`/`export-pkg`

### ISSUE THREAD

**Issue by X1aomu** [conan-io/conan#15502]
### What is your suggestion?

In CI, it's very common to build (create) a binary package, and then upload it to the remote.

Recently, i've tried to get the exact pattern to match the binary package that just created by `conan create` or `conan export-pkg`, but failed to find an easy way.

Let me show some example.

Example 1, `conan create` a binary package, upload the package and all its dependencies just built.

```
conan create . -b=missing -f=json > graph.json
conan list -g graph.json -gb build -f json > pkglist.json
conan upload --list=pkglist.json -r=remote -c
```

Example 2, `conan create` a binary package, upload **only** the package created, not any of its dependencies. This is not that intuitive as Example 1, and wasteing time and space (caculate the graph twice, and generates things twice). We need `install` first to build all dependencies, then `create` to build the package we want. 

```
conan install . -b=missing
conan create . -f=json > graph.json
conan list -g graph.json -gb build -f json > pkglist.json
conan upload --list=pkglist.json -r=remote -c
```

Example 3, `conan export-pkg` a package and upload it. `conan list  -gb build` can't help anymore, it seems to ignore the root node, which is the package we want, and even it has `"binary": "Build"`. I need to specify both the name and the version. 

The hardest part is acquiring the version. The files they live are varies (conanfile.py, or any other). The way to acquire its value to the CI shell are also varies (powershell in Windows and bash in Linux) ....

```
# firstly, we need to get the version
version=`head -n 1 version.txt | tr -d '\n'`
# conan install 
conan install conanfile.py -pr:a $profile --build=missing -f=json > graph.$profile.json
conan list --graph=graph.$profile.json --graph-binaries=build -f=json > deps_to_upload.$profile.json
# upload the dependencies just build
conan upload -r remote -l deps_to_upload.$profile.json -c
# build the library
conan build conanfile.py -pr:a $profile
# create conan package
conan export-pkg conanfile_package.py -pr:a $profile
# upload the package
conan upload -r remote "name/$version@user#latest:*#latest" -c
```

Things could be easier if

+ `conan create` / `conan export-pkg` can optionally output the accurate pattern (`name/version@user/channel:rrev#package_id:prev`) of package just created, which can be used by `conan upload` later.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @X1aomu 

Thanks for your suggestions.

I'd like to clarify some issues first:

> Example 2, conan create a binary package, upload only the package created, not any of its dependencies. 

This is a broken approach. You shouldn't do ``conan install --build=missing`` + ``conan create`` + ``conan upload only the created one``. This means that you are uploading a binary that was built against non-existing binaries in the dependencies. This binary will not be reproducible, and it can fail in different scenarios. It is only recommended to upload packages that already have their dependencies binaries in the server or uploading the dependencies too. This is why ``Example1`` is the recommended approach, everything that was built locally should be uploaded, or it shouldn't have been built locally in the first place.


> Example 3, conan export-pkg

This might be a different issue, I'll have a look at this

**Comment by memsharded** [comment]
I see that the "exported" binary package has ``"recipe": "Consumer"`` which seems the main issue. I am contributing a fix in https://github.com/conan-io/conan/pull/15504

**Comment by X1aomu** [comment]
Oh, I didn't realized there is a bug related to `export-pkg`. Thanks for continuing following on it.

As for
> Example 2, conan create a binary package, upload only the package created, not any of its dependencies.

There is a story about how I *struggle* with Conan's binary model. It's too heavy to explain here. I plan to do it later, when we have the initial setup setttle down, which is to changing our build system from VS+Nuget to CMake+Conan. 

Briefly, we've choose to call `self.info.requires.clear()` in `package_id()` in every recipes we made. Currently, we are at an early stage, to compile thing, and let them run. We want some **reproducible** things that may different from others‘ understanding. The reproducibility to quick reuse the built library, the building time, and the storage space to hosting those built library (plus their symbols, as huge as you know) are also matter.

Imaging we are creating a binary package of a shared library, and it have many dependencies. Some static library (Conan models this as `embeded`), and some shared library. Most of time, the static parts are private, no any ABI leakage. thus the consumer don't care any of the private dependencies if they have already got a built shared library. Those private dependencies are useless when the shared library was built. Thus uploading them may waste the storage space. That's why there is Example 2.

**Comment by X1aomu** [comment]
Hi @memsharded 

While this issue is close by the merged PR, shall we reopen this to talk more about the Example 2?

**Comment by memsharded** [comment]
> Briefly, we've choose to call self.info.requires.clear() in package_id() in every recipes we made. Currently, we are at an early stage, to compile thing, and let them run. 

This is an anti pattern, yes. It mostly drops the reproducibility, tracking, multi-platform, multi-binary capabilities of Conan.

> Most of time, the static parts are private, no any ABI leakage. thus the consumer don't care any of the private dependencies if they have already got a built shared library. Those private dependencies are useless when the shared library was built. Thus uploading them may waste the storage space. That's why there is Example 2.

It sounds that you don't want a package then, just do the build of those static libraries in the same package recipe, and fully isolate them. Creating a package with a package manager to say and then saying, "I am not uploading the package, so basically the package doesn't exist" sounds also contrary to the principles of package management and devops

It seems that it would be better to create a new ticket to talk about this things, yes, please do open. Thanks!

**Comment by X1aomu** [comment]
Agree that `self.info.requires.clear()` is some kind of anti-pattern, I would like to reconsider that in the future.

Things to talk in a new ticket at this time is still not clear to me. Let me play more with conan. I need some time to experience, i think.
