### ISSUE TITLE
tools.env.virtualenv:auto_use missing from conan config list

### ISSUE THREAD

**Issue by seriousfreedom** [conan-io/conan#15500]
unable to build package due to tools.env.virtualenv:auto_use missing from conan config list
[conan issue.txt](https://github.com/conan-io/conan/files/14016513/conan.issue.tx

is there somekind of solution to this

**Comment by memsharded** [comment]
What Conan version?

If Conan 2, this conf has been removed, the behavior is the default in 2.0 without any conf, actually the ``conf`` is an opt-in in 1.X to enable this behavior in preparation for 2.0

**Comment by seriousfreedom** [comment]
It's conan 2, is there a way to build a package that calls for that virtualenv without it?

**Comment by memsharded** [comment]
> It's conan 2, is there a way to build a package that calls for that virtualenv without it?

Sorry, I don't know what you mean. ``VirtualBuildEnv`` and ``VirtualRunEnv`` will be used by default. You can also instantiate them directly in your ``generate()`` method to customize their behavior.

**Comment by seriousfreedom** [comment]
build fails because .tools.env.virtualenv:auto_use isnt in the config list   and the package im trying to build requires that to be present
unless im just missing soemthing altogether

![Screenshot from 2024-01-25 21-39-07](https://github.com/conan-io/conan/assets/80973316/fe7b350d-a4be-4ffb-9373-e64768949aeb)

**Comment by memsharded** [comment]
``tools.env.virtualenv:auto_use`` doesn't exist in Conan 2.0, it is only a Conan 1.X, you need to remove it from your ``global.conf``. Are you sure that ``Cura`` already upgraded and supports Conan 2.0?

**Comment by seriousfreedom** [comment]
> `tools.env.virtualenv:auto_use` doesn't exist in Conan 2.0, it is only a Conan 1.X, you need to remove it from your `global.conf`. Are you sure that `Cura` already upgraded and supports Conan 2.0?

well it aparently has not as i am unable to build it

**Comment by memsharded** [comment]
> well it aparently has not as i am unable to build it

then maybe you need to install ``conan==1.62.0``? Have you tried that?

**Comment by memsharded** [comment]
Closing this ticket as staled/responded, don't hesitate to create new tickets for any further question, thanks!
