### ISSUE TITLE
[question] Setting path to dlls in runtime for multi config projects

### ISSUE THREAD

**Issue by ViktarHasiul231862** [conan-io/conan#15509]
### What is your question?

Hi, I am using Visual Studio and install some libs via conan and planning to use both release and debug configurations. In order to run my app I need to set paths to my dlls by running conanrunenv-<build_type>-x86_64.bat for either debug or release.

Is there any conan feature which allows to automatically set paths to corresponding dlls when I switch between debug and release in Visual Studio so I dont need to run those .bats manually everytime? Can MSBuild help with that?

Edit: I can not run both scripts because some dll names are the same so it conflicts.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ViktarHasiul231862 

Thanks for your question.

If you are using Visual Studio projects, then the ``MSBuildDeps`` will already take this into account and add the ``bindirs`` of the dependencies to the ``<LocalDebuggerEnvironment>`` so it is possible to execute from the IDE executables that depend on DLLs of dependencies. The ``MSBuildDeps`` is also a multi-config generator, so it allows to switch from Debug to Release and it will find the correct DLLs, just need to make sure to install both flavors:
```
conan install .
conan install . -s build_type=Debug
```
before opening the project.

**Comment by ViktarHasiul231862** [comment]
Ok, thank you. Seems to be working. Using MSBuildDeps to install libs and later adding conandeps.props to Visual Studio project using Property Manager allows to build and run both debug and release apps without running any conanrun.bat files.
