### ISSUE TITLE
[question] conan 1.x info query does not return conditional dependencies

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#15511]
### What is your question?

Scenario:
I'm working conan 1.x packages, essentially transforming them to conan 2.x. For this to work, I need to query a dependency graph listing the build order for a specific package. The issue is, if a `requires` statement is conditional, `conan info` does not return it. Is this intentional? Is it due to the requirement to provide a profile directly to `conan info` so the conditions can actually be resolved by the command?
Example:
```
if self.settings.os == "Linux":
    self.requires("example_lib/1.0.0.0@user/channel")
```

So the solution would be to download the actual package first with all the binary packages, get the conaninfo form all of them, and passing them as profiles for the next graph query?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @donlk 

> The issue is, if a requires statement is conditional, conan info does not return it. Is this intentional?

``conan info`` should use that requirement if the conditional is set, and ``conan info`` evaluates the dependency graph based on input profiles and settings in the same way as ``conan install`` and ``conan create``, computing different dependency graphs based on the profiles. So if you do ``conan info ... -s os=Linux`` the dependency should be there in the response, isn't it the case?

>  Is it due to the requirement to provide a profile directly to conan info so the conditions can actually be resolved by the command?

Yes, exactly, the profile is necessary.

> So the solution would be to download the actual package first with all the binary packages, get the conaninfo form all of them, and passing them as profiles for the next graph query?

Not sure what is exactly the issue, or the problem to solve. In theory, you could keep using your CI pipeline for 1.X untouched, and then implement a 2.0 CI pipeline, isn`t it?

**Comment by donlk** [comment]
Transformation of existing ones is a requirement in my scenario, but the profile solution works, thank you.
