### ISSUE TITLE
[question] TypeError: sequence item 0: expected str instance, SettingsItem found

### ISSUE THREAD

**Issue by Vasile-Creuco** [conan-io/conan#15527]
### What is your question?

Hi!

When I try to run conan build command, I get this error and I don't know where it comes from exactly.

This is the error:
======== Finalizing install (deploy, generators) ========
ERROR: Traceback (most recent call last):
  File "conan\cli\cli.py", line 280, in main
  File "conan\cli\cli.py", line 190, in run
  File "conan\cli\command.py", line 126, in run
  File "conan\cli\commands\build.py", line 65, in build
  File "conan\api\subapi\install.py", line 70, in install_consumer
  File "conans\client\generators\__init__.py", line 117, in write_generators
  File "conan\tools\env\virtualbuildenv.py", line 88, in generate
  File "conan\tools\env\environment.py", line 536, in save_script
  File "conan\tools\env\environment.py", line 422, in save_bat
  File "conan\tools\env\environment.py", line 158, in get_str
TypeError: sequence item 0: expected str instance, SettingsItem found

ERROR: sequence item 0: expected str instance, SettingsItem found

Thank you!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Vasile-Creuco 

Thanks for your question.

It is very challenging to know this without further information.
But I suspect this comes from an environment assignment like:
```python
env = Environment()
env.define("some_var", self.settings.somesetting)
```
This is incorrect, the ``env.define()`` and other methods should receive strings, try ``env.define("some_var", str(xxxx)`` instead

**Comment by Vasile-Creuco** [comment]
Thank you for answer @memsharded

I don't understand exactly what you mean. Where I should define the env variable?

So, I have a conanfile.py and conandata.yml.
conandata.yml contains some requirements which I need when I want to create some packages with my conanfile.py.
conanfile.py is a simple recipe with some methods like requirements(), build(), package(), buildinfo().
In the build() method I want to run matlab compiler and get some result which I want to add in my packages before to deploy it in artifactory.

This is my profile:
[settings]
build_type=Release
compiler=matlab
compiler.version=R2023b
os=Windows
arch=x86_64

Also in settings.yml in the compiler section I added matlab with some versions.

This is the conan command:
conan build . --name=namepkg --version=1.0.0 --user=myuser --channel=channel -pr:h myProfile -pr:b myProfile

-pr:h is profile host
-pr:b is profile build

After running the conan command, I get this the error mentioned up and I don't know where it comes from.

**Comment by memsharded** [comment]
The line that seems to fail is inside ``VirtualBuildEnv``. This is a generator that is collecting environment information from dependencies. If some dependency is doing something like ``self.buildenv_info.define("myvar", self.settings.xxxx)`` this will cause your client side to crash, but the problem could be in your dependencies recipes, not your conanfile


I am not 100% sure this would be the root cause, but sound likely, I'd start investigating with this idea. It would be good to try to isolate the problem more, start dropping dependencies until you find the offending one, then check its conanfile recipe

**Comment by memsharded** [comment]
Hi @Vasile-Creuco 

Did you manage to find the root issue? Don't hesitate to re-open or create new tickets if you have any further questions. Thanks!

**Comment by Vasile-Creuco** [comment]
Hi @memsharded 

Yes. I found the root issue. Some dependencies is doing self.buildenv_info.define("myvar", self.settings.xxxx) in package_info method.
I had to modify to get a str(self.settings.xxxx) instead of self.settings.xxxx and it worked fine.

Many thanks for your support!

**Comment by memsharded** [comment]
Great, thanks for the feedback!
