### ISSUE TITLE
[question] Automatically Authenticating with multiple remotes

### ISSUE THREAD

**Issue by FannoFlow1** [conan-io/conan#15520]
### What is your question?

I'm setting up a Conan toolchain, for assisting projects with their CI/CD pipelines. Part of that is dealing with any number of remotes and authentications within the build process.

For example, project A might depend on remote X,Y,Z
and project B depends on just remote Z

Currently my plan to deal with this was to direct users to add a `remotes.json` coupled with a `credentials.json`, which looked like a perfect way of letting individual projects to deal with their own authentication.

However, it seems like the `conan build` and `conan search` does not force an authentication before searching for required dependencies. 
For example, the code below is after adding the remotes.json and credentials.json to the conan home directory

`conan build . --profile=...`
```
======== Computing dependency graph ========
Graph root
    conanfile.py (YYY/1.5.0): /workspaces/.../conanfile.py
ERROR: Package 'XXXX' not resolved: Version range '>=2.0.0' from requirement 'XXXX' required by 'YYY/1.5.0' could not be resolved.
```

Searching for the package before authenticating shows the expected package not found
```
conan search XXX
conancenter
  ERROR: Recipe 'XXX' not found
remote-1
  ERROR: Recipe 'XXX' not found
remote-2
  ERROR: Recipe 'XXX' not found
```

after Explicitly logging in to the individual remote, the build procedes as expected
```
conan remote login remote-1
conan remote login remote-2
```

My question is, how can this process be automated?
Is there a way to force an authentication with all remote `conan remote login *` ?
Can the conan build / search / etc. be configured to login when searching for requirements? 

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @FannoFlow1 

Thanks for your question.

This is mostly a security configuration from the server sides, that can decide to silently return a 404 or similar when users are not preemtively logged-in. This can be solved by configuring the remotes to require authentication instead, and then whenever a remote without credentials is touched, it will launch an authentication challenge and the Conan client will stop for user input or use its auth mechanisms to auth.

The explicit client approach would be indeed to call ``conan remote login *``. But it is not possible from the client to just enforce a new auth on every Conan command, that would make the tool much slower unnecessarily.

**Comment by FannoFlow1** [comment]
Thanks for the quick response!

These are all local Artifactory conan remotes, configured with group scoped tokens. 
Is there a way to check for this security configuration?
`curl https://.../artifactory/api/conan/<remote>` returns an 200 status code

**Comment by memsharded** [comment]
> curl https://.../artifactory/api/conan/<remote>

I guess the repo itself might be visible, but the internal packages are not, same as ``curl www.google.com`` would return something, but ``curl www.google.com/some/private/address`` will return a 404 even if the resource exist if we are not authenticated

> Is there a way to check for this security configuration?

You mean checking how it is configured in the server? Like this? https://jfrog.com/help/r/jfrog-platform-administration-documentation/hide-existence-of-unauthorized-resources

**Comment by FannoFlow1** [comment]
I see!
We had Anonymous access enabled, and hide existence disabled.
I disabled anonymous access and wouldn't you know it worked like a charm.

Unfortunately we do have some public mirrors that we keep on Artifactory and allow anonymous access to, so I'm not sure how viable that solution is.
It is curious that with anonymous access enabled, seeing that the conan repository exists through the conan API returns a 200, when it should likely return a 401/403 if anonymous doesn't have access to that repository. 

Is that something you guys can look into? Should I file my own support ticket with JFrog? 

Also, is `conan remote login *` actually a viable command? I've tried various forms of this with various errors (conan 2.0.13)
`conan remote login *` pulling in all files in the current dir as arguments
`conan remote login "*"` using literal `*` as the remote name
`conan remote login "*-conan-release"` giving a login attempt with *, ignoring the credentials.json:

Am I just not supplying these login patterns correctly?

**Comment by memsharded** [comment]
> Is that something you guys can look into? Should I file my own support ticket with JFrog?

Yeah, it would be better if you can directly file the ticket to JFrog

> conan remote login * pulling in all files in the current dir as arguments

Sorry that was my fault. ``conan remote login`` works for a single remote. I meant the ``conan remote auth`` that can iterate all remotes.

**Comment by FannoFlow1** [comment]
All good!

Thanks for being so responsive! This has been a great help. 
I'll go ahead and file a ticket with JFrog and see what they come up with. I'll close this issue in the meantime.
