### ISSUE TITLE
[question] Can options can be used to store strings without predefined value in recipe.

### ISSUE THREAD

**Issue by Toug19** [conan-io/conan#15526]
### What is your question?

Hi,

We would like to use an option in one of our recipe. This option would store a string. But we would like be able to pass any string value when using the recipe (with conan create <path> -o my_option="<any_string").

From documentation and errors we are having, it seems that we must pass all the possible value in the recipe with:

`options = {"ghs_lmhost": [license_server_list1, license_server_list2]}`

otherwise if we don't set all possible values using this code
`options = {"ghs_lmhost"}`
 we are having the following error when exporting: 
ERROR: Error loading conanfile at '/workspace/tools/compilers/ghs2020.1.4-arm/conanfile.py': Error while initializing options. 'set' object has no attribute 'items'

and if we set the possible value in the recipe (like 1st code) and we try to force an other value with:
`conan create tools/compilers/ghs2020.1.4-arm/ -o ghs_lmhost="toto"`

we have the following error:
ERROR: 'toto' is not a valid 'options.ghs_lmhost' value.
Possible values are ....

Seems that option feature is not the good choice for us. Am I wrong?
What feature should we use?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Toug19 

Thanks for your question.
Conan accepts the placeholder ``options = {"myoption": ["ANY"]}`` to indicate any value.

However, please note that such value will become part of the ``package_id``, every different value of that string will imply a different binary. If this is your intent, because your final packages have different licenses, then please try that and let us know.

**Comment by Toug19** [comment]
Yes this is perfect. 
Maybe this could be great to add it to the documentation: like here https://docs.conan.io/2/tutorial/creating_packages/configure_options_settings.html

Thanks.

**Comment by memsharded** [comment]
Please check the reference: https://docs.conan.io/2/reference/conanfile/attributes.html#options

We try not to add too much info to the tutorial part, to not overwhelm the beginners, just the basic concepts. 

I think this question is responded, can we close the ticket now? Thanks!
