### ISSUE TITLE
[cmd refactor]  deploy() feature. Issue: imports does not work as expected when installing packages

### ISSUE THREAD

**Issue by mschmid** [conan-io/conan#1552]
I have a package 'applicationA' with an imports method:
`    def imports(self):
        self.copy("*", src="res", dst="res", root_package="libA")`

When running `conan install` directly in the folder with the conanfile.py, everything works as expected, the ressources are copied.
When running `conan install application/0.1@user/testing` in a blank folder instead, the imports method does not get called and all my ressources are missing. Unfortunately, I need a copy in the user space.

**Comment by memsharded** [comment]
The rationale for this behavior is that ``imports`` are defined by the consumer, not by the installed package.

When you are running it locally, you are acting as the consumer, but when you are using ``conan install <pkg-reference>``, you are installing it, but the ``pkg-reference`` is the installed resource, not the consumer.  So the ``imports`` declared in "application" package, are the needed files by "application". But if you install application, and for example want to imports "application.exe" executable, that is not possible withing the "application" package. 


So the approach would be to define a consumer conanfile, maybe a simple conanfile.txt:

```
[requires]
application/0.1@user/testing

[imports]
....
```
And ``conan install`` it.

**Comment by mschmid** [comment]
Thank you for the fast answer. For my consumers it would be easiest to just launch one command (`conan install pkg-reference`) and be ready with the configuration (and all imports). The separate necessary conanfile.txt seems somewhat redundant for the end-user when installing a package. Maybe I need to add another package that packages the imports again by copying them to accomplish this issue.

**Comment by memsharded** [comment]
That is a very good point. If you are releasing like an end product for your consumers, maybe you want to create a "runtime" package with the very minimum they need. That depends on what is your final product and how your consumers use it.

I am going to have a look, there is a ``conan imports`` command, but it is not working as it should be, maybe adapting it could achieve this.

**Comment by lasote** [comment]
@memsharded could you explain a little what are you thinking about it for 0.26?

**Comment by memsharded** [comment]
Moving it to 0.27, we need more time to carefully analyze options for this. I think it is related to the management of shared libraries, and "runtime" packages, so maybe it should be addressed as a whole.

**Comment by memsharded** [comment]
Hi @mschmid,

I am working on this issue, already tried some re-packaging approach that works well. However, I would like to know more about your use case:

- You want to install just 1 dependency (and its transitive dependencies), for users, with a single ``conan install Pkg/0.1@user/channel`` command. Is it your only dependency? Please note that if you have more than one, they should better be installed all at the time with a conanfile, to avoid conflicts in upstream transitive versions

- Are you installing a library for development? Static, shared? Do you want to hide your implementation details to your package consumers? E.g. if you depend on some library A, but that is just hidden in the usage by library B, you want your users to only have B retrieved (and A shared library if that is the case)

Please let me know. You can also contact us by direct email to info@conan.io, and we also use slack and twitter, if you want to discuss privately about your requirements. That would be very good feedback for us. Thanks!

**Comment by mschmid** [comment]
Hi @memsharded,
yes, my use case is to provide a single dependency for users that they can install with just one command on the command line and get everything prepared for running some executable.
The dependencies and transitive dependencies therefore include an executable and some dynamic linked libraries that are necessary.
It would be good to optionally hide the details for the end users, but it is not required in the first place.

The use case targets on end-users, I think libraries for development could also be installed using the traditional approach with a conanfile.py or conanfile.txt.

**Comment by memsharded** [comment]
Good, that makes sense. I guess that you really need the local copy of the artifacts. Because if not really necessary, then ``virtualenvs`` are a good and clean solution. With them you can do something like:

```bash
$ conan install <your_package> -g virtualrunenv  # This generates activate_run.bat file
$ activate_run.bat  # running this script puts the package "bin" folder in the path
$ your_exe.exe # works without local copies
```

I am working in documenting the re-packaging approach, which would be necessary anyway. If you really need copying the files to user folder with a single ``conan install <pkg>``, then we would need to add something, I am also having a look

**Comment by mschmid** [comment]
Hi @memsharded,
I need the local artifacts for one use case especially:
Some ddl (unfortunately we have to use this one and do not own the source code) resides in its own package and tries to load a configuration file from a fixed relative path. The configuration file itself resides in another package by design.
The only way I found to solve this issue is to retrieve both packages to the userspace with imports.

**Comment by memsharded** [comment]
Ok,  many thanks for the feedback. We will try to think something for this use case!

**Comment by memsharded** [comment]
A proposal has been done #1884 it would be great if you @mschmid could have a look at the user interface and usage of the feature. Maybe even running conan from source in the develop branch to test. Thanks!

**Comment by memsharded** [comment]
The deploy() functionality has been released, would be great if you could try it and give feedback:

Please check: http://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy
And: http://docs.conan.io/en/latest/packaging/running_packages.html
