### ISSUE TITLE
How to easily download the lastest package version from a remote

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#15523]
### What is your question?

Hi, is there an easy way to tell conan 2.0 to download the latest version of a certain package in a remote? Latest means higher version number. So for example if I have
- hello/1.0.0
- hello/1.2.1
- hello/2.2.0

My users would like to be able to download hello/2.2.0 without first listing all "hello" versions and figuring out by themselves which one is the latest. Is there a smart way to do this with one or two conan commands, or do I need to script this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lucabarbiero 

Thanks for your question.

You mean ``conan install --requires="hello/[*]"``? If you want to make sure it updates an existing version in the cache, also add the ``--update`` argument.

**Comment by freihamer** [comment]
Hi @memsharded

Thanks this seems what I am after. It works (meaning the highest version number is installed), but it seems to ignore the package options I specify.

Assume in the `hello ` recipe I have:
```
options = {"some_option": ["value1", "value2"]}
default_options = {"some_option" : "value1"}
```
Then 
`conan install --requires="hello/[*]" --profile my_profile -o some_option=value2 --deployer direct_deploy`

Will not install and deploy the build with `some_option `set to `value2`. It seems that options are ignored (also no error if an invalid option value is provided, like `value3 `in my example). I just get the build for `some_option` set to `value1`, which is the default in my `hello` recipe. Can you  check on this? I am using Conan v2.0.7.

Thanks
Luca

**Comment by memsharded** [comment]
It seems the ``options`` syntax is not correct, you need to do: ``-o hello/*:some_option=value2``, because options are per-package. Note you could do ``conan install --requires="pkg1/[*]" --requires="pkg2/[*]"`` and then there would be no way to know to which package you want to apply the option. If you want to apply it to all packages, you can of course do ``-o *:some_option=value2`` too.

**Comment by memsharded** [comment]
> I am using Conan v2.0.7.

Only the latest patch of each minor is supported (https://docs.conan.io/2/introduction.html#stable), please try to update and use 2.0.17

**Comment by freihamer** [comment]
Thank you this solves the problem!

**Comment by memsharded** [comment]
Excellent, happy to hear that!
