### ISSUE TITLE
[question] cannot find -lGSL::gsl: No such file or directory

### ISSUE THREAD

**Issue by effepivi** [conan-io/conan#15529]
### What is your question?

Hi,
I am using CMake.

I got a main project where GSL is used.
In a subproject (with its own subdirectory and own `CMakeLists.txt`, which is included from the main project), I want to inherit from the main project. In other word, I don't want to call `FIND_PACKAGE` in all subprojects.
Before using Conan, I used the system library provided by my Linux distro without any problem.

I am migrating to Conan and the linkage of the subproject fails with errors as follows:
`cannot find -lGSL::gsl: No such file or directory`.

Any idea what is wrong? I am hitting a wall.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @effepivi 

Thanks for your question.
We would need a bit more of information to reproduce the issue. Could you please provide:

- The ``conanfile`` that you are using
- The exact ``conan install`` command and the produced output.
- The platform: os, compiler, Conan version
- Your ``CMakeLists.txt``, or a minimal version to reproduce
- The ``cmake ...`` command line that you are using and the produced output.

Thanks very much

**Comment by effepivi** [comment]
thanks for the prompt reply @memsharded . It's a big and complex project. I'll make a mock example but it'll take me a bit of time...

**Comment by memsharded** [comment]
> thanks for the prompt reply @memsharded . It's a big and complex project. I'll make a mock example but it'll take me a bit of time...

This issue not finding GSL sounds like a relatively doable to reproduce by a very aggressive stripping of the project, like a very reduced ``conanfile.txt`` with the requirement and a minimal CMakeLists.txt could probably work. Just let us know if you need help :)

**Comment by effepivi** [comment]
thanks again. I haven't been able to replicate the problem with a simplified example I made from scratch. I guess it's a good news. I am trying to move away from a Superbuild with CMake and to use Conan as an alternative. My CMake code is old and has not been updated in a long time. I may have to start again from scratch but I cannot make it a priority. I'll get back to you when I make some progress on this issue.

**Comment by memsharded** [comment]
> I am trying to move away from a Superbuild with CMake and to use Conan as an alternative. My CMake code is old and has not been updated in a long time. 

That is a good hint. It is possible that usage of old-style ``include_directory()``, ``link_directories()`` etc, instead of modern targets could be related, is one of the typical issues for old CMake.

> I'll get back to you when I make some progress on this issue.

Good, looking forward. If you don't mind, I am closing this ticket as it doesn't need our attention at this moment (we are trying to improve our Github issues management), you can re-open or create a new one when you have the information. Many thanks!
