### ISSUE TITLE
[question] Conan 1.x specify only version, user and channel but use package name from conanfile.py on export-pkg?

### ISSUE THREAD

**Issue by Danielku15** [conan-io/conan#15533]
### What is your question?

Hi.

Is there a built-in way in 1.x to specify only `version@user/channel` and keep the package name from the conanfile.py? Is overriding the name in the `configure` method the correct way to achieve this or are there alternatives? 

I've seen that in conan 2.x on the `export-pkg` it is possible to pass in the package name, version, user and channel individually while in Conan 1.x there are 2 proposed syntaxes as `reference`:

> `user/channel or pkg/version@user/channel`
> (https://docs.conan.io/en/1.9/reference/commands/creator/export-pkg.html)

I like the 2.x approach but we are not yet ready to move from 1.x to 2.x due to some in-house dependencies so I'm looking for a workaround. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Danielku15 

THanks for your question

> Is there a built-in way in 1.x to specify only version@user/channel and keep the package name from the conanfile.py? Is overriding the name in the configure method the correct way to achieve this or are there alternatives?

yes, the ``version@user/channel`` syntax should work, have you tried? I am using:
```
conan export-pkg . 0.1@user/channel
```
and seems to work correctly. Please give it a try and let us know

**Comment by Danielku15** [comment]
@memsharded Finally got it running. 🥳  The `version@user/channel` syntax works fine. Seems I had some other remaining problems which caused the confusion.

**Comment by memsharded** [comment]
Happy to hear that! 😄
