### ISSUE TITLE
[question] How to run conan server with pipx

### ISSUE THREAD

**Issue by ErikTempelaarVO** [conan-io/conan#15537]
### What is your question?

Hi! I have a question regarding running conan_server with pipx.

New distros point to either pipx or venv when dealing with python packages.

```
error: externally-managed-environment

× This environment is externally managed
╰─>
    The system-wide python installation should be maintained using the system
    package manager (apk) only.

    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:

    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage

    To exit the virtual environment, run:

    deactivate

    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.

    To automatically manage virtual environments, consider using pipx (from the
    pipx package).
    ```
``` 
I consulted the conan docs and for conan I found the instructions here:
https://docs.conan.io/2/installation.html#install-with-pipx

However these settings don't apply to conan_server and the docs for conan_server don't mention pipx.
https://docs.conan.io/1/uploading_packages/running_your_server.html
https://docs.conan.io/2/tutorial/conan_repositories/setting_up_conan_remotes/conan_server.html

I tried using pipx for conan_server as well but ran into two issues:
- I needed to install bash, seems this is a requirement for pipx.
- I was unable to install the requirements.txt, seems that pipx doesn't support that?

I solved my issue with virtualenv, but maybe there's another solution with pipx?
Ideally that would be covered in the docs too. Thanks in advance!


### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ErikTempelaarVO 

Thanks for your question.
It is true that ``conan_server`` does not support ``pipx`` at this moment, and it is not planned to add support in the short-term.

We have planned though a refactor of the repository layout, moving the server to its own folder. Most likely at that time we will have a look to the setup scripts, we might try then (not guaranteed that it will be possible to provide it, and maybe it will still be unsupported)

**Comment by ErikTempelaarVO** [comment]
@memsharded 

Thanks for the quick reply.

**Comment by memsharded** [comment]
I am closing this as non planned.
Even if it was possible, in practice running such a server in prod would require some frontend, like nginx or apache, and probably some other service like gunicorn for performance, so the ``pipx`` installation wouldn't be well suited for this. In practically all scenarios this is not worth the effort in prod, and using ArtifactoryCE which is free will be much better.
