### ISSUE TITLE
How remove an option from default_options

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1553]
Hi, this is a question.

After new versions of Conan, the components in Conanfile were transformed to classes, e.g. Options, Requirements.

In some cases I need to set some default option by OS:

```python
class BazConan(ConanFile):
    ...
    options = {"fPIC": [True,False], "shared": [True, False]}
    default_options = "fPIC=False", "shared=False"
    ...
```

```python
class FoobarConan(ConanFile):
    ...
    requires = "Baz/0.1.0@qux/testing"
    default_options = "Baz:fPIC=True", "Baz:shared=True", "shared=True"

    def config_options(self):
        if self.settings.compiler == "Visual Studio":
            # Invalid statement, but could be the easiest
            self.options.values.remove("Baz:fPIC")
            # OR, It works, but is not elegant 
            self.options.values = OptionValues( "Baz:shared=True", "shared=True")
```

I'm looking for the better approach to exclude an external option, because forcing `fPIC` to some value, on Visual Studio, will result as error, so I need to exclude it.

The real case is Boost, I want to force fPIC true, but I need to exclude when I'm using VS. But the rule could be applied in any case. Anyway, transform all component was great, is a proud to read such code.

Regards.

**Comment by memsharded** [comment]
Maybe don't add ``"Baz:fPIC=True"`` in the defaults, and set it dynamically in ``configure()`` or ``config_options`` only if not Visual Studio.

**Comment by uilianries** [comment]
Good, but how to add in options.values, if OptionValues is not dict?

```python
# invalid statement
self.options.values.add("Baz:fPIC=True")

```

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by memsharded** [comment]
```python
self.options["Baz"].fPIC=True
```

**Comment by uilianries** [comment]
Of course! :tada: 

Thanks @memsharded
