### ISSUE TITLE
[feature] tools.cmake.cmaketoolchain.compile_warning_as_error

### ISSUE THREAD

**Issue by hoyhoy** [conan-io/conan#15543]
### What is your suggestion?

We have a large list of requirements that must compile on PowerPC-based hosts and we need to disable `-Werror` on some of them.  For example, I attempted fix `google_cloud_cpp` recipe in conan-center by just disabling the warnings [here](https://github.com/conan-io/conan-center-index/pull/21808/files), but @uilianries won't merge the patch because his CI doesn't have PowerPC hosts.  Why not just expose the setting in the conan CMakeToolChain instead?  Every useful setting like this should be exposed through the conan config interface.  We've been blocked by conan-center taking months to review and merge patches sent over and were forced to fork nearly every recipe into a user and channel.  If we had these options in the toolchain, it would solve a number of issues for us.

This setting wouldn't fix the `google-cloud-cpp` because they actually rolled their own `CMAKE_COMPILE_WARNING_AS_ERROR`, but it would have prevented me from writing my own implementation.

```
    @property
    def _werror(self):
        return self._get_safe_options_boolean("warnings_as_error")

    def generate(self):
        toolchain = CMakeToolchain(self)
        toolchain.cache_variables["CMAKE_COMPILE_WARNING_AS_ERROR"] = self._werror
```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hoyhoy 

Thanks for your suggestion.
There is already a recommended way to inject any desired variables and behavior into CMake toolchain files, it is documented here, please have a look: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/inject_cmake_variables.html

There is no need to create a custom Conan conf for every potential CMake variable that we want to customize, that doesn't scale. The above documents how you can write a CMake file with the variables values you want, and then pass it in a single conf, that will inject it.

**Comment by memsharded** [comment]
Hi @hoyhoy 

Did the above help?

> We've been blocked by conan-center taking months to review and merge patches sent over and were forced to fork nearly every recipe into a user and channel. If we had these options in the toolchain, it would solve a number of issues for us.

Regarding this, please take a look at https://docs.conan.io/2/devops/using_conancenter.html. For use cases like this it is recommended to work with your own fork, and build binaries from it. Please check the https://docs.conan.io/2/devops/conancenter/hosting_binaries.html#devops-conancenter-hosting-your-own-conancenter-fork too, it recommends that packages should be created without user/channel, same as ``ConanCenter``, that makes way easier to maintain the fork, with less divergence.

**Comment by memsharded** [comment]
Closing this ticket as staled/responded, don't hesitate to create new tickets for any further question, thanks!

**Comment by hoyhoy** [comment]
It'd still we be good to have some kind of global disable `Werror` feature that works across all generators and toolchains.  

For example google-cloud-cpp is still busted on PowerPC at the moment, four months after I submitted a patch to fix it.

We had to work around it by forking the conan-center recipe and setting each dependency's `CFLAGS` to `-w` as needed.  In addition to that, we have a customized cmake function to compile our own outdated code.

```
function (enable_permissive_compile_options)
    if (CMAKE_C_COMPILER_ID STREQUAL GNU AND CMAKE_C_COMPILER_VERSION VERSION_GREATER_EQUAL 11.0)
        if (ASPERA_CORE_ENABLE_STATIC_ANALYSIS)
            add_compile_options("$<$<COMPILE_LANGUAGE:C>:-fno-analyzer>")
        endif ()
        add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-fpermissive>")
        add_compile_options("-w")
        add_compile_options("-Wno-error")
    elseif(CMAKE_C_COMPILER_ID MATCHES Clang)
        add_compile_options("-Wno-error")
        add_compile_options("-Wno-everything")
    elseif(CMAKE_C_COMPILER_ID MATCHES MSVC)
        add_compile_options("/w")
    endif()
endfunction()
```

**Comment by memsharded** [comment]
I will try to push https://github.com/conan-io/conan-center-index/pull/21808, so it is merged.

Regarding the compile options, can't they just be defined in profiles ``[conf]`` like ``tools.build:cxxflags=["-Wno-error"]``? That should take care of injecting it into dependencies too? If the build scripts of the dependencies decide to ignore or hardcode other values, then there is nothing that Conan can do from the outside, so it still depends on each recipe patching the specific build script.

**Comment by hoyhoy** [comment]
I'm already setting.  

```
# llvm
tools.build:cxxflags=["-Wno-everything", "-Wno-error" ]
tools.build:cflags=["-Wno-everything", "-Wno-error" ]
# gcc
tools.build:cxxflags=["-w", "-fpermissive" ]
tools.build:cflags=["-w", "-fpermissive" ]
```

If you don't set `GOOGLE_CLOUD_CPP_ENABLE_WERROR=OFF`, `google-cloud-cpp`'s cmake overrides the cxxflags. 

We're slowly getting rid of our forked recipes here.  We _almost_ have everything working.  Thanks for all of your help.
