### ISSUE TITLE
[bug] conan create ... , got `ERROR: Specify the 'user' and the 'channel' or neither of them` 

### ISSUE THREAD

**Issue by h20282** [conan-io/conan#15546]
### Environment details

* Operating System+version: Windows 22621.2134
* Compiler+version:
* Conan version: 1.61.0
* Python version: 3.10.10

### Steps to reproduce

execute command 
```bash
conan create . system_api/0.0@gzh/testing
````
I specified user=gzh and channel=testing, but still get 
```bash
ERROR: Specify the 'user' and the 'channel' or neither of them
```

### Logs

```log
DEBUG :conan_api.py   [176]: INIT: Using config 'C:\Users\20536\.conan\conan.conf' [2024-01-29 11:27:13,444]
DEBUG :tracer.py      [156]: CONAN_API: create(name=system_api,version=0.0,user=gzh,channel=testing,profile_names=None,settings=None,conf=None,options=None,env=None,test_folder=None,not_export=False,build_modes=None,keep_source=False,keep_build=False,verify=None,manifests=None,manifests_interactive=None,remote_name=None,update=False,test_build_folder=None,lockfile=None,lockfile_out=None,ignore_dirty=False,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None, conf=None),is_build_require=False,require_overrides=None) [2024-01-29 11:27:13,446]
DEBUG :profile_loader.py[121]: PROFILE LOAD: C:\Users\20536\.conan\profiles\default [2024-01-29 11:27:13,447]
INFO  :settings_preprocessor.py[56]: Setting 'compiler.runtime' not declared, automatically adjusted to 'MDd' [2024-01-29 11:27:13,479]
DEBUG :profile_loader.py[121]: PROFILE LOAD: C:\Users\20536\.conan\profiles\default [2024-01-29 11:27:13,479]
ERROR: Specify the 'user' and the 'channel' or neither of them
```

**Comment by memsharded** [comment]
Hi @h20282 

Thanks for your report.

It seems the problem could be in your profile. Can you please share your ``default`` profile?

**Comment by h20282** [comment]
> Hi @h20282
> 
> Thanks for your report.
> 
> It seems the problem could be in your profile. Can you please share your `default` profile?


Configuration for profile default:

```profile
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Debug
[options]
[conf]
[build_requires]
[env]
```

but There is no difference before and after getting this bug

**Comment by memsharded** [comment]
Thanks for sharing. 
I am afraid that I don't know what could be happening. If you could share your ``conanfile.py``, that could also help to give some hints

**Comment by memsharded** [comment]
Hi @h20282 

Any further feedback here? Your ``conanfile.py``?

**Comment by h20282** [comment]
I removed origin .conan folder (in C:/), and changed it to D:/, now it works fine

> Hi @h20282
> 
> Any further feedback here? Your `conanfile.py`?

**Comment by memsharded** [comment]
> I removed origin .conan folder (in C:/), and changed it to D:/, now it works fine

Not sure why, I cannot see any relation between that error and changing the unit, unless there was some corruption in the local cache, that was fixed by starting with a new one in another location.  But happy to hear that it is working now.

As this most likely won't be an issue in Conan 2, as it uses other mechanisms to define user/channel, I am closing this ticket as solved. Please don't hesitate to create new tickets for any further question you might have, thanks!
