### ISSUE TITLE
Howto `conan install` with fine grained --options for the libs it requires?

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#1554]
Hi,

I'm looping over 
`conan package_files Lib1/1.2.4@twoflower2/testing --package_folder=dist -o vproc=mproc -f`

where `dist` and `mproc` changes on the iterations the for loop. Therefore quite a few hashes are created in package dir in the local cache.

Now the consumer will issue a `conan install .` to pull Lib1 as per consumer conanfile.py  `requires = "Lib1/1.2.4@twoflower2/testing"`.

My problems are:
1. How do I choose which Lib1 options to pull in doing an `install` cmd?
2. Does the `install` cmd's `--options` apply to just the consumer or also to Lib1 it `requires`
2. How to pull in all Lib1 options in doing an `install` cmd?

**Comment by memsharded** [comment]
1. You use the same options, or configuration in general, that you used to create the package:

```bash
$ conan install -o Lib1:vproc=<value>
```
You can also specify the default option in the conanfile.py:

```python
class MyPkg(ConanFile):
     ...
     default_options = "Lib1:vproc=value"
```
But the former is recommended.

2. The options apply per-package. The recommended approach is to use ``Lib1:option=value``

3. To read the options for Lib1, you need to check the recipe. A helper command to inspect recipes and other files, from the local or remotes is ``conan get``:

```bash
$ conan get Lib1/1.2.4@user/channel
```

**Comment by Twoflower2** [comment]
@memsharded Thanks explains it nicely, but I have to try it. Now just to understand `options` hence this in DOCs - https://github.com/conan-io/docs/issues/266
