### ISSUE TITLE
[question] How to do a `conan install` && `cmake` with multi-config generators?

### ISSUE THREAD

**Issue by garyo** [conan-io/conan#15558]
### What is your question?

I'm working on a template for building C++ plugins (shared-lib/DLL/CFBundle) using conan2 and cmake. My repo is at https://github.com/garyo/cmake-conan-plugin-template. 
I've set it up to be able to build using the conan-cmake integration (the dependency provider is copied into that repo) or use a normal `conan install . && cmake ...` workflow; see the [README](https://github.com/garyo/cmake-conan-plugin-template/blob/main/README.md).

My question is how to support a `conan install . && cmake...` style workflow when specifying a multi-config generator like "Ninja Multi-Config"? When I try, I get duplicate presets:
```
conan install . --build=missing
conan install . --build=missing -s build_type=Debug
# at this point conan has created `build/Release` and `build/Debug` and is including both of them in `CMakeUserPresets.json` 
cmake --preset default -G "Ninja Multi-Config"
# at this point I get errors: "CMake Error: Could not read presets from /Users/garyo/src/cmake-conan-template: Duplicate presets"

Not sure where to go from there. You can clone the above repo and try it yourself.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @garyo 

Thanks for your question.

I think the issue is that if you are using a CMake generator different than the default one, it is necessary to inform Conan, so it uses the right layout, etc. So something like:

```
conan install . --build=missing -c tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"
conan install . --build=missing -s build_type=Debug -c tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"
```
should work, I have just tried and worked fine
As a note, the
```
cmake --preset default -G "Ninja Multi-Config"
```
wouldn't be necessary, just:
```
cmake --preset default
```
Because the generator is already defined in the preset.

**Comment by garyo** [comment]
Thanks! It's `cmake --preset conan-default` but you got me on the right track.

Complete working instructions now added to my [README](https://github.com/garyo/cmake-conan-plugin-template/blob/main/README.md):
```
  conan install . --build=missing -c tools.cmake.cmaketoolchain:generator="Ninja Multi-Config" -s build_type=Debug
  conan install . --build=missing -c tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"
  cmake --preset conan-default
  cmake --build --preset conan-debug
  cmake --build --preset conan-release
```
