### ISSUE TITLE
[feature] conan list: info in packages when passing in a graph file

### ISSUE THREAD

**Issue by aander80** [conan-io/conan#15551]
### What is your suggestion?

Hello!

When passing in a graph file into `conan list -g graph.json --format json`, there is no `info` field (containing e.g. settings) in the output list JSON, which you would otherwise get if you ran `conan list "*:*" --format json`.

As an example, assume the following `conanfile.py`:

``` python
from conan import ConanFile

class ConanRecipe(ConanFile):
    name = "pkg"
    version = "0.0"
    settings = "os", "compiler", "build_type", "arch"
```

Now run the following commands:

``` shell
conan create . --format json > graph.json
conan list -g graph.json --format json
conan list "pkg:*" --format json
```

The first `conan list` command does not contain package info, whereas the second one does. Could the `conan list` command be extended to include the info from the graph file, if provided? The info seems to be present in `graph.json`, so conan should be able to copy it over?

If this feature is added, could it also be included when generating a list file from `conan upload`? I.e.

``` shell
conan upload --list build-list.json -r my-remote --format json > upload-list.json
```

would also contain info in the packages in `upload-list.json`? I realize this second one could potentially require more to implement since there is no guarantee that `build-list.json` but it would be a nice addition nonetheless.

Also, the CLI of conan 2 is very good in my opinion, with the JSON formats that can be passed from command to command, well done! :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aander80 

Thanks for your suggestion. I am having a look at it, and I think it makes sense to expand the serialization to include the ``self.info`` information in serialized form too. I will send a exploratory PR shortly

> If this feature is added, could it also be included when generating a list file from conan upload? I.e.

I think this is already happening, could you please double check? The ``conan upload`` is already serializing the ``info``, and it is there in the output

**Comment by aander80** [comment]
You are correct that `conan upload` is serializing the `info`, I just assumed that it wasn't since I was not getting it in the output, but that was because my input list to `conan upload` did not have the `info`, thanks for pointing that out! :)

**Comment by memsharded** [comment]
Sending a exploratory PR in #15553 

> Also, the CLI of conan 2 is very good in my opinion, with the JSON formats that can be passed from command to command, well done! :)

Thanks very much! We did a huge effort in Conan 2.0, and even if the migration effort is necessary, we strongly believe it is a much better version in many different aspects and it is worth it, thanks very much for appreciating it! 🙂

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/15553 merged, for next release
