### ISSUE TITLE
[bug] The CMake policy CMP0091 must be NEW, but is ''

### ISSUE THREAD

**Issue by LarsLeferenz** [conan-io/conan#15556]
### Environment details

* Operating System+version: Win11
* Compiler+version: msvc - v193
* Conan version: 2.0.17
* Python version: 3.10.11

### Steps to reproduce

I'm currently trying to update this recipe https://github.com/sintef-ocean/conan-mavsdk to feature a newer version of the MAVSDK library. This is my current conanfile.py :
```python
from os.path import join
from conan import ConanFile
from conan.tools.files import copy, rmdir
from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps, cmake_layout
from conan.tools.scm import Git


class MAVSDKConan(ConanFile):
    name = "mavsdk"
    license = "BSD-3-Clause"
    version = "2.1.0"
    author = "SINTEF Ocean"
    homepage = "https://mavsdk.mavlink.io/main/en/"
    url = "https://github.com/mavlink/MAVSDK.git"
    description = "MAVSDK is a set of libraries providing a high-level API to MAVLink."
    settings = "os", "compiler", "build_type", "arch"
    package_type = "library"
    options = {
        "fPIC": [True, False],
        "shared": [True, False]
        }
    default_options = {
        "fPIC": True,
        "shared": False
        }

    def export_sources(self):
        pass

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        pass
    
    def configure(self):
        pass

    def source(self):
        git = Git(self, folder=self.source_folder)
        git.clone(self.url, args=[f"-b v{self.version}", "--recursive"])
        copy(self, "*", join(self.source_folder, "MAVSDK"), self.source_folder)
        rmdir(self, join(self.source_folder, "MAVSDK"))

    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["SUPERBUILD"] = True
        tc.variables["BUILD_MAVSDK_SERVER"] = False
        tc.variables["CMAKE_POLICY_DEFAULT_CMP0091"] = "NEW"
        tc.generate()

        deps = CMakeDeps(self)
        deps.generate()


    def build(self):
        cmake = CMake(self)
        cmake.configure(cli_args=["-DCMAKE_POLICY_DEFAULT_CMP0091=NEW", "-DCMAKE_BUILD_TYPE=Release"])
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

        copy(self, "LICENSE", self.source_folder,
             join(self.package_folder, "licenses"))
        rmdir(self, join(self.package_folder, "lib", "cmake"))

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "both")
        self.cpp_info.set_property("cmake_file_name", "MAVSDK")
        self.cpp_info.set_property("cmake_target_name", "MAVSDK::mavsdk")
```

When running `conan create .` I'm getting the following error:
```
-------- Installing package mavsdk/2.1.0 (1 of 1) --------

...

mavsdk/2.1.0: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/Lars/.conan2/p/b/mavsd201be907eaaba/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/Lars/.conan2/p/b/mavsd201be907eaaba/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\Lars\.conan2\p\b\mavsd201be907eaaba\b\src" -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release

...

-- Conan toolchain: CMAKE_GENERATOR_TOOLSET=v143
CMake Error at C:/Users/Lars/.conan2/p/b/mavsd201be907eaaba/b/build/generators/conan_toolchain.cmake:37 (message):
  The CMake policy CMP0091 must be NEW, but is ''
Call Stack (most recent call first):
  C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
CMake Error at third_party/cmake/build_target.cmake:32 (message):
  C:/Users/Lars/.conan2/p/b/mavsd201be907eaaba/b/src/third_party/mavlink
  failed to configure!
Call Stack (most recent call first):
  third_party/CMakeLists.txt:11 (build_target)


-- Configuring incomplete, errors occurred!

mavsdk/2.1.0: ERROR:
Package '9bdee485ef71c14ac5f8a657202632bdb8b4482b' build failed
mavsdk/2.1.0: WARN: Build folder C:\Users\Lars\.conan2\p\b\mavsd201be907eaaba\b\build
ERROR: mavsdk/2.1.0: Error in build() method, line 63
        cmake.configure(cli_args=["-DCMAKE_POLICY_DEFAULT_CMP0091=NEW", "-DCMAKE_BUILD_TYPE=Release"])
        ConanException: Error 1 while executing

```

Other issues (#12458) mention that this might be due to a malformed CMakeLists file, but I've looked through all the CMakeLists files of the library and all appear to call `cmake_minimum_required()` before `project()`. 

I've tried to patch `cmake_policy(SET CMP0091 NEW)` into the files, with the same error occurring. 

Does anyone have an idea how to actually set this policy correctly?

### Logs

Full output:
[output.log](https://github.com/conan-io/conan/files/14086349/output.log)

**Comment by memsharded** [comment]
Hi @LarsLeferenz 

Some preliminary quick feedback:
- Passing ``-DCMAKE_BUILD_TYPE`` specially hardcoding it in the recipe is problematic, specially for Visual Studio generator. Please avoid that, Conan will already pass it automatically when needed, no needed to pass it as extra argument.
- ``git = Git(self, folder=self.source_folder)`` passing the ``source_folder`` is probably unnecessary, as ``source()`` method already executes in the source folder


Can you please remove the args, do ``cmake.configure()``, try again and share the results?

**Comment by LarsLeferenz** [comment]
Hi,

Thanks for the quick reply. Specifying the git folder was unnecessary, you're right^^

```
PS C:\Users\Lars\Documents\mavsdk-conan> conan create .

======== Exporting recipe to the cache ========
mavsdk/2.1.0: Exporting package recipe: C:\Users\Lars\Documents\mavsdk-conan\conanfile.py
mavsdk/2.1.0: Calling export_sources()
mavsdk/2.1.0: Copied 1 '.py' file: conanfile.py
mavsdk/2.1.0: Exported to cache folder: C:\Users\Lars\.conan2\p\mavsd69f5b2c9dc8b2\e
mavsdk/2.1.0: Exported: mavsdk/2.1.0#3fd0633e838701221b34657c76b90737 (2024-01-29 16:23:54 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    cli
Requirements
    mavsdk/2.1.0#3fd0633e838701221b34657c76b90737 - Cache

======== Computing necessary packages ========
mavsdk/2.1.0: Forced build from source
Requirements
    mavsdk/2.1.0#3fd0633e838701221b34657c76b90737:9bdee485ef71c14ac5f8a657202632bdb8b4482b - Build

======== Installing packages ========
mavsdk/2.1.0: Calling source() in C:\Users\Lars\.conan2\p\mavsd69f5b2c9dc8b2\s\src
mavsdk/2.1.0: Cloning git repo

-------- Installing package mavsdk/2.1.0 (1 of 1) --------
mavsdk/2.1.0: Building from source
mavsdk/2.1.0: Package mavsdk/2.1.0:9bdee485ef71c14ac5f8a657202632bdb8b4482b
mavsdk/2.1.0: Copying sources to build folder
mavsdk/2.1.0: Building your package in C:\Users\Lars\.conan2\p\b\mavsdf2265d2c46458\b
mavsdk/2.1.0: Calling generate()
mavsdk/2.1.0: Generators folder: C:\Users\Lars\.conan2\p\b\mavsdf2265d2c46458\b\build\generators
mavsdk/2.1.0: CMakeToolchain generated: conan_toolchain.cmake
mavsdk/2.1.0: CMakeToolchain generated: CMakePresets.json
mavsdk/2.1.0: CMakeToolchain generated: ..\..\src\CMakeUserPresets.json
mavsdk/2.1.0: Generating aggregated env files
mavsdk/2.1.0: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
mavsdk/2.1.0: Calling build()
mavsdk/2.1.0: Running CMake.configure()
mavsdk/2.1.0: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/Lars/.conan2/p/b/mavsdf2265d2c46458/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/Lars/.conan2/p/b/mavsdf2265d2c46458/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\Lars\.conan2\p\b\mavsdf2265d2c46458\b\src" -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
-- Version: v2.1.0
-- Version major: 2
-- Version minor: 1
-- Version patch: 0
-- Using Conan toolchain: C:/Users/Lars/.conan2/p/b/mavsdf2265d2c46458/b/build/generators/conan_toolchain.cmake
-- Conan toolchain: CMAKE_GENERATOR_TOOLSET=v143
-- Conan toolchain: C++ Standard 14 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.36.32543.0
-- The CXX compiler identification is MSVC 19.36.32543.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Conan toolchain: C:/Users/Lars/.conan2/p/b/mavsdf2265d2c46458/b/build/generators/conan_toolchain.cmake
-- Conan toolchain: CMAKE_GENERATOR_TOOLSET=v143
CMake Error at C:/Users/Lars/.conan2/p/b/mavsdf2265d2c46458/b/build/generators/conan_toolchain.cmake:37 (message):
  The CMake policy CMP0091 must be NEW, but is ''
Call Stack (most recent call first):
  C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
CMake Error at third_party/cmake/build_target.cmake:32 (message):
  C:/Users/Lars/.conan2/p/b/mavsdf2265d2c46458/b/src/third_party/mavlink
  failed to configure!
Call Stack (most recent call first):
  third_party/CMakeLists.txt:11 (build_target)


-- Configuring incomplete, errors occurred!

mavsdk/2.1.0: ERROR:
Package '9bdee485ef71c14ac5f8a657202632bdb8b4482b' build failed
mavsdk/2.1.0: WARN: Build folder C:\Users\Lars\.conan2\p\b\mavsdf2265d2c46458\b\build
ERROR: mavsdk/2.1.0: Error in build() method, line 62
        cmake.configure(cli_args=["-DCMAKE_POLICY_DEFAULT_CMP0091=NEW"])
        ConanException: Error 1 while executing
```

Removing the build type sadly didn't fix the issue. According to the mavsdk build guide (https://mavsdk.mavlink.io/main/en/cpp/guide/build.html#release), you need to set it even on Windows because they use this step to build dependencies. They also note that this is unusual. 

I should also note that straight-up following their build instructions does work on my system, conan's involvement seems to cause the error somehow.

**Comment by memsharded** [comment]
Ok, I think I know what is happening.

CMake doesn't allow to define policies like that with variables. There are 2 possibilities:
- To add a explicit ``cmake_policy(SET CMP<NNNN> NEW|OLD)``
- To change the ``cmake_minimum_required(VERSION 3.13)`` to something newer

Conan supports from CMake 3.15. Both ways would require doing a patch, which in general is relatively simple. I tried adding a patch to the main ``CMakeLists.txt`` to update the ``cmake_minimum_required(VERSION 3.15)``, but then a cascade of errors happened:

- This project has tons of other ``CMakeLists.txt`` nested, and everyone is adding its own ``cmake_minimum_required(VERSION xxxx)``, generally with older than 3.15 versions and their own ``project()`` calls. Every one will inject again the toolchain
- Then I tried to generalize the patch and then simply comment out the ``cmake_minimum_required(VERSION 3.13)`` in every subdirectory, but then the ``mavlink`` CMakeLists.txt contains an ``ExternalProject_add(`` which cannot easily be patched, but that will also produce the same error

I am afraid that this project might not be straightforward to build with the built-in ``CMakeToolchain`` and ``CMakeDeps``, because those are intended for modularized projects, not for projects with everything vendored, specially via intrusive approaches like hunter and ExternalProject_Add, which are challenging to patch. Conan integrations put a lot of effort to guarantee that it is possible to create fully Conan-agnostic ``CMakeLists.txt``, so Conan doesn't interfere with other tools.

There are 2 strategies here:

- Drop the ``CMakeToolchain`` and ``CMakeDeps`` generators, and try to inject yourself the right configuration into the project. Build it as a big project together with all dependencies, and package the minimum necessary. The potential issue with this approach is if you need to package third parties, lets say zlib or other dependencies, that might conflict with other packages dependencies if you plan to use them, besides this ``mavsdk`` one, because there could be multiple and incompatible copies of such zlib (or others) in the dependency graph.

- Unvendor the dependencies, make them Conan packages (this is the strategy we use in ConanCenter for all open source public dependencies). It seems this is equivalent to disable the ``SUPERBUILD``. This can be a large effort, given that the project is not simple. Fortunately it seems that most of the dependencies are already in ConanCenter, so that will make things way easier, but still requires some effort and CMake and Conan expertise.

I think I'd try to do the second approach if I had to do this myself, it might be more effort, but probably better in the long term. Following that way the recipe might be even added to ConanCenter too.

I have started trying this:
```python
def source(self):
        git = Git(self, folder=self.source_folder)
        git.clone(self.url, args=[f"-b v{self.version}", "--recursive"])
        copy(self, "*", join(self.source_folder, "MAVSDK"), self.source_folder)
        rmdir(self, join(self.source_folder, "MAVSDK"))
        replace_in_file(self, "CMakeLists.txt", "3.13", "3.15")

    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["SUPERBUILD"] = False
        tc.cache_variables["BUILD_MAVSDK_SERVER"] = False
        #tc.cache_variables["CMAKE_POLICY_DEFAULT_CMP0091"] = "NEW"
        tc.generate()
```
And then the build can progress beyond that point, and then start failing because ``curl`` is not there. It should be added to the ``conanfile.py`` and start from there the unvendoring process.

**Comment by memsharded** [comment]
To clarify, this is not a bug in Conan, but several issues in the project:
- Using unsupported CMake versions, minimum 3.15 necessary
- Even if applying patches, the project has vendored dependencies in multiple mechanisms, hunter, ExternalProject_Add. They should be unvendored to work correctly.

**Comment by LarsLeferenz** [comment]
Thank you very much for the detailed explanation.

In that case I'll probably try the second approach with `SUPERBUILD` set to false. I am planning on integrating mavsdk into a larger software project, where some dependencies might overlap, so splitting the recipe up seems like a good idea. Also, I think if I omit some of the features of mavsdk (server & tests), the amount of dependencies gets smaller. 

I'll experiment around a bit and see if I get a version running.  If its suitable for conan-center I'll create a request there.

Thanks again, I'll close this issue for now.

**Comment by memsharded** [comment]
Thanks for the feedback. Do not hesitate to open new tickets as necessary for any further question you may have.
