### ISSUE TITLE
package_files -o with different values create same hash in package dir  in Conan cache

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#1556]
Why would no different shaxxx created under package dir in the Conan cache for these cmds and just the last is in the cache? Isn't a shaxxxx calculated using the options too? It seems for `package_files` cmd uses the option values in configure() and not the values set from the cmd line, which I think is a bug.

### cmds where option `cversions` changes:
`conan package_files Lib1/1.2.4@user/testing --package_folder=dist -f -o variations="d1" -o crvus="H01" -o cversions="v1"`

`conan package_files Lib1/1.2.4@user/testing --package_folder=dist -f -o variations="d1" -o crvus="H01" -o cversions="v2"`

`conan package_files Lib1/1.2.4@user/testing --package_folder=dist -f -o variations="d1" -o crvus="H01" -o cversions="v3"`

### option values set in conanfile.py configure():
```
self.options.variations = ['d1', 'd2', 'd3']
self.options.crvus = ['H01', 'H02', 'H03']
self.options.cversions = ['v2', 'v3', 'v4']
```

- How can I force different 3x shaxxx created under package in Conan cache for the 3x different options of the `package_files` cmd in this example?

**Comment by Twoflower2** [comment]
Any ideas?

**Comment by memsharded** [comment]
Have you tried creating them as class attributes?:
```python
class MyPkg(ConanFile):
     options = {"variations": ['d1', 'd2', 'd3'], ...}
```

Also, you have to specify the package to which those options apply:

```bash
$ conan package_files Lib1/1.2.4@user/testing --package_folder=dist -f -o Lib1:variations="d1"
```
Note the ``-o Lib1:variations="d1"``

**Comment by Twoflower2** [comment]
- Now I have. With using the `configure()` like I had it with `-o Lib1:variations="d1"` it still did not work.
My `options` looked like this below and the `configure()` is above:
```
options = {"vproc" : "ANY", "internalVersion" : "ANY", "variations" :"ANY", "crvus" : "ANY", "cversions" : "ANY"}
```


- Then I removed `configure()` and moved option values like you did above and with `-o Lib1:variations="d1"` and **Now it works!**. I'm forsure using it like this now.

Sorry for my dumb `conanfile.py`, but why would the `configure()` way not work and your way does?

**Comment by memsharded** [comment]
It is not dumb, it is in fact a subtle difference:

- When ``options`` are declared at the class level, they are used to define option and **possible set of values** for those options, like constraints.
- Later, when ``self.options`` is used, a different object is used, which manages the "set" and "get" operations for existing options. It might be also possible to create options, but when you assign values, you might not be creating constraints, but creating an option with a list as a value.

**Comment by Twoflower2** [comment]
One thing:

Doing a `conan package_files` work perfect doing it your way, but `conan info` errors:

```
> conan info
ERROR: Conanfile: 'cversion' value not defined
```

How can I get rid of that error but for `conan package_files` still to work?

**Comment by lasote** [comment]
Have you specified default_options as well? http://conanio.readthedocs.io/en/latest/reference/conanfile/attributes.html?highlight=default_options#options-default-options
