### ISSUE TITLE
Calling python_requires function to determine version of package

### ISSUE THREAD

**Issue by lstoffer** [conan-io/conan#15560]
### What is your question?

Hi! I have a question regarding the python_requires functionality.
So far I was using this functionality to determine the version for my conan packages:

```python
build_tools = "buildTools/[~3.0]@tools/release"
bt = python_requires(build_tools)`

class LibErrorConan(ConanFile):
    name = "libError"
    version = bt.get_version()
```
Where I have a function `get_version()` in the `buildTools` project.

However, with conan 2 this no longer seems to be possible since the version for the package has to be set before the functions from python_requires are available.

My question is, if there is a possibility to achieve the same behaviour as with `python_requires` from conan1 in conan2.
The reason I want do do it this way is because there are many libraries that are going to use this `get_version()` function and I don't want do duplicate the code.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi! Thanks a lot for your question.

This is totally possible using the `set_version` method of recipes.

If you have a `base` `python_requires`:
```py
from conan import ConanFile
from conan.tools.files import load
import os

class Source(object):
    def set_name(self):
        self.name = load(self, "name.txt")

    def set_version(self):
        self.version = load(self, "version.txt")

class MyConanfileBase(ConanFile):
    pass
```
Export the `python_requires` with `conan export . --name=base --version=0.1`
You can then use such methods in your recipes as such:

```py
from conan import ConanFile
class MyConanfileBase(ConanFile):
    python_requires = "base/0.1"
    python_requires_extend = "base.Source"
    def source(self):
        self.output.info("Pkg1 source: %s:%s" % (self.name, self.version))
```

That would output whatever is in the `name.txt` and `version.txt` files as the name and version of your recipe. This can be extended to any functionality you desire :)

Hope this helps, let me know if you have any further questions!

**Comment by AbrilRBS** [comment]
Also note that your Python requires usage was superseded in Conan 1.21 with the class attribute approach I showed you, and updating to that approach has been recommended ever since 2019 when they were released :)

**Comment by lstoffer** [comment]
Thanks a lot for your explanations, this worked for me!
