### ISSUE TITLE
[bug] provide conflict when package depends on itself in build context

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#15570]
### Environment details

* Operating System+version: macos 14.2
* Compiler+version: apple-clang 15.0.0
* Conan version: 2.0.17
* Python version: 3.11

### Steps to reproduce

- Create a package that depends on itself in `build` context (e.g. grpc-style).
- add `provides = 'feature'` attribute to the package's conanfile
- make package editable or export it to the local cache
- install package in cross-compilation mode (i.e. targeting android/iOS/browser)

Expected: this case should work and `provides` attribute should only affect downstream packages

Actual: Package conflicts on itself with error like this:
```
|| ERROR: Provide Conflict: Both 'my_package/2.0.0' and my_package/2.0.0' provide '('pkg1', 'pkg2', 'pkg3')'.
```

The current workaround is to not use the `provides` attribute and rely on c++ compiler/linker errors to detect duplicate symbols.

**Comment by memsharded** [comment]
Thanks very much for your detailed report @DoDoENT, it helped to identify the issue.

I am submitting a fix in https://github.com/conan-io/conan/pull/15575 for next release.
