### ISSUE TITLE
[question] CONAN_CMAKE_MODULE_PATH does not pick up generated Arrow package

### ISSUE THREAD

**Issue by bytesapart** [conan-io/conan#15574]
### What is your question?

I'm using conan 1.62. I have a repository of conan recipes, where I've recently added a new Arrow recipe following https://github.com/conan-io/conan-center-index/blob/master/recipes/arrow/all/conanfile.py, with a slight modification where rmdir is not executed and therefore, I still have `package/<hash>/lib/cmake/Arrow/*.cmake` files present.

When I run a `conan install .` on a repository which contains arrow as a dependency in it's `conanfile.py`, I can see that it picks up arrow, and populates `CONAN_ARROW_ROOT`, `CONAN_INCLUDE_DIRS` (with several paths, but arrow is included), `CONAN_LIB_DIRS.`, but `CONAN_CMAKE_MODULE_PATH` does not contain the new apache arrow package.

I tried searching the documentation, but it seems to be lacking on what or how `CONAN_CMAKE_MODULE_PATH` is populated, and no matter how many older versions of `arrow/all/conanfile.py` I use, I simply cannot get `CONAN_CMAKE_MODULE_PATH` populated. I expect `CONAN_CMAKE_MODULE_PATH` to have the path to arrow root directory in it.

I've even tried adding `self.cpp_info.builddirs = ["lib/cmake/Arrow"]` to `package_info()`, but it just doesn't seem to work. I have no clue on where to proceed, since I'm very new to the conan ecosystem. Any help on this will be really appreciated! 

Edit 1:

The conanfile.txt generated after doing a `conan install .` does not contain `[builddirs]` section populated.

```
[includedirs_arrow]
/Users/bytesapart/.conan/data/arrow/15.0.0/ba/e-t/package/bf0e0b8e38827dc0d2369900cf99c610c92b2c35/include

[libdirs_arrow]
/Users/bytesapart/.conan/data/arrow/15.0.0/ba/e-t/package/bf0e0b8e38827dc0d2369900cf99c610c92b2c35/lib

[bindirs_arrow]


[resdirs_arrow]


[builddirs_arrow]


[libs_arrow]
arrow

[system_libs_arrow]


[defines_arrow]
ARROW_STATIC
```
However, when I look at a dependency to arrow which I added, called, `jemalloc` from https://github.com/conan-io/conan-center-index/blob/441d9161edf93d241ee49ec0317ed9ebd6c634c4/recipes/jemalloc/all/conanfile.py (had to use a previous version not migrated to v2), it has it's respective `[builddirs]` populated. This conanfile does not even contain an explicit `self.cpp_info.builddirs` setup.

```
[includedirs_jemalloc]
/Users/bytesapart/.conan/data/jemalloc/5.3.0/ba/e-t/package/879abb2efec177cfcbdd546bd20dce512229c4dc/include
/Users/bytesapart/.conan/data/jemalloc/5.3.0/ba/e-t/package/879abb2efec177cfcbdd546bd20dce512229c4dc/include/jemalloc

[libdirs_jemalloc]
/Users/bytesapart/.conan/data/jemalloc/5.3.0/ba/e-t/package/879abb2efec177cfcbdd546bd20dce512229c4dc/lib

[bindirs_jemalloc]


[resdirs_jemalloc]


[builddirs_jemalloc]
/Users/bytesapart/.conan/data/jemalloc/5.3.0/ba/e-t/package/879abb2efec177cfcbdd546bd20dce512229c4dc/

[libs_jemalloc]
jemalloc_pic

[system_libs_jemalloc]


[defines_jemalloc]
JEMALLOC_EXPORT=

[cppflags_jemalloc]


[cxxflags_jemalloc]


[cflags_jemalloc]


```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @bytesapart 

Thanks for your question.

For the CONAN_CMAKE_MODULE_PATH, this variable is filled with the explicit ``self.cpp_info.set_property("cmake_build_modules", ....`` in the arrow recipe.

This is intended for automatically loading of those modules when the ``CMakeDeps`` generated ``arrow-config.cmake`` file is found via ``find_package()``. It is not fully clear if you want to use the ``CMakeDeps`` file or you want to use the config.cmake file generated and packaged inside the arrow package. If that is what you want, typically you want to modify the recipe to define ``self.cpp_info.set_property("cmake_find_mode", "none")``


It would be good to describe a bit more explicitly the consumer side, like the generators you are using (the ``txt`` generator that you are displaying is not very useful, it might not contain all the information contained in the modern generators, Conan 2.0 has fully dropped the ``txt`` generator creating that file you are posting). If you are new to Conan, maybe you want to start directly with Conan 2.0? It was released almost 1 year ago, and it is very recommended to use it instead of 1.X

**Comment by bytesapart** [comment]
Hi @memsharded, thank you so much for the quick response!

> For the CONAN_CMAKE_MODULE_PATH, this variable is filled with the explicit self.cpp_info.set_property("cmake_build_modules", .... in the arrow recipe.

I could not find that particular property in the existing arrow's `conanfile.py`

> It would be good to describe a bit more explicitly the consumer side, like the generators you are using
A little background on how the existing project is setup.

We have a `main-repo` and a `recipes-repo`. The `recipes-repo` contains all 3rd-party dependencies, that are built by a CI-job. In the `main-repo`, we create a `build` folder, and do a `conan install ../src`. The `main-repo` src folder contains a conanfile.py that has `def requirements` which contains a list of dependencies, for example:

```
def requirements(self):
        dependencies = [
            "arrow/15.0.0",
            "boost/1.84.0",
            "catch2/3.5.2",
            .....
```

In the CMakeLists.txt within 'src' folder, we do the following:
```
...
# Not exact code in CMake file, but something similar
include("conanbuildinfo.cmake")
list(PREPEND CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH})
...
```

When I did a `conan install ../src`, I get a `conanbuildinfo.cmake`, which contains a variable CONAN_CMAKE_MODULE_PATH, but for some odd reason, it does not contain paths to `arrow` (while containing other paths such as boost and catch2). None of the other recipes in `recipe-repo` have an explicit `cpp_info.set_property`, so a little baffled on why it does not pick up `arrow`. The `conanbuildinfo.cmake` file does contain paths to `arrow` in `CONAN_INCLUDE_DIRS` and `CONAN_LIB_DIRS` variable.

>  If you are new to Conan, maybe you want to start directly with Conan 2.0? It was released almost 1 year ago, and it is very recommended to use it instead of 1.X

Unfortunately, due to historical reasons, I'm constrained by 1.X at the moment.

**Comment by memsharded** [comment]
Ok, you are still using the very legacy ``cmake`` generator, the one creating the ``conanbuildinfo.cmake``. This generator is deprecated, and ``CMakeDeps`` + ``CMakeToolchain`` should be used instead (even in Conan 1.X, I am not even talking about Conan 2.0).

The thing is that the ``cmake`` generator do not listen or implement management of ``self.cpp_info.set_property()``  properties.

**Comment by bytesapart** [comment]
Ah, I see! Thank you so much @memsharded , I'll probably have to write some wrapper in order to support the very legacy 1.x build with `CMakeDeps` and `CMakeToolchain`. Apologies for the question, will hopefully migrate to 2.x to make it easier in the future! :)

**Comment by memsharded** [comment]
No prob, happy to help! 

Do not hesitate to open new tickets for any further question or help you might need :)
