### ISSUE TITLE
[question] how to create a self-contained build system that works well with IDEs

### ISSUE THREAD

**Issue by elvisdukaj** [conan-io/conan#15576]
### What is your question?

Hi! I am trying to replace our custom build system in something more standard based on Conan and CMake. I have two important goals:

- the build system should be self-contained: ideally all the required tools should come from Conan. (In my dreams also the host toolchain but this seems very hard to achieve)
- It should work smoothly with other IDEs like vscode, CLion, Android Studio, etc....

I am experimenting different scenarios. I created the following recipes:

```
# myorgprofile
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.version=193
os=Windows

[tool_requires]
ninja/1.11.1
cmake/3.28.1

[conf]
tools.env.virtualenv:powershell=True
tools.cmake.cmaketoolchain:generator=Ninja



# myorg_androidr21e
include(myorgprofile)

[settings]
os=Android
os.api_level=29
arch=armv8
compiler=clang
compiler.version=9
compiler.libcxx=c++_static
compiler.cppstd=17

[tool_requires]
android-ndk/r21e
zulu-openjdk/21.0.1



# myorg_androidr26
include(myorgprofile)

[settings]
os=Android
os.api_level=29
arch=armv8
compiler=clang
compiler.version=9
compiler.libcxx=c++_static
compiler.cppstd=17

[tool_requires]
android-ndk/r21e
zulu-openjdk/21.0.1
```

Now suppose I would like to cross compile using these 3 recipes. The workflow should be:

1. activate the virtual environment for conan
2. for Android
  1. call `conan install . --profile  myorg_androidr26 
  2. activate the build environment
  3. start the IDE from the same shell

The workflow above is needed as CMake and Ninja tools are not in the PATH, and if they are in the PATH, I don't want that the system version is used instead of what I've specified in my recipe. Moreover, this workflow is not ideal and error prone. For instance, when I want to switch to another profile I should:

1. close the IDE
2. deactivate the current environment on the shell or create a new shell
3. activate the new build environment for the new build configuration
4. start the IDE again from the shell

I am not sure how to improve the situation... a possible workaround could be to have some custom command to start the IDE given a recipe:

```
conan start_vscode --profile myorg_androidr26 
```

The above command should call `conan install`, activate the build environment and then start the IDE. That is still not ideal but is better than nothing, I think.

What is the recommended way you suggest for this scenario. I was thinking this should be a basic workflow but it seems hard to achieve.

Thank you for the support and for this amazing project!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @elvisdukaj 

Thanks for your question.

Some quick feedback:

> recipes

Minor nitpick :) Those are called ``profiles`` files. Recipes are ``conanfile.py`` files (or even ``conanfile.txt``)

> the build system should be self-contained: ideally all the required tools should come from Conan. (In my dreams also the host toolchain but this seems very hard to achieve)

There are organizations out there putting everything in tool-requires, including the toolchains. The ``android_ndk`` and ``mingw`` or ``cmake`` are some public examples this is possible, but it is true that putting full compilers like gcc and clang is not that evident, and might require some effort. But we know from users packaging and using gcc, clang and msvc build tools in Conan packages. If you are starting now, sure better wait until later to try this.

>  myorg_androidr21e
include(myorgprofile)

Try to not include a mostly unrelated profile. The base profile is a msvc, while the android one is basically overriding completely all the settings. My recommendation would be to not do an ``include``, just copy the parts like ``tool_requires`` that you might need. Or refactor the common parts to a ``basic`` profile that is included both by ``msvc`` profile and ``android`` profile.


> 4. activate the build environment

We are working to add environment to the CMake presets. Even the ``cmakeExecutable``. So in some cases, it will be possible to drop this step, just ``conan install`` + ``cmake --preset``



Regarding your question.

I think this flow can be implemented with Conan generated presets for IDEs that support them, like this works nice with VSCode. The ``build_folder_vars``, which can be both a ``conf`` in your profiles, or hardcoded in the recipe as ``layout()`` can be used to generate as many different presets as you want, including the ``os``, the ``arch`` and other things. Then the IDE should be able to switch from one to other preset without re-initializing (that is assuming the environment from the presets is enough)

Regarding the ``build_folder_vars`` have a look to https://docs.conan.io/2/reference/tools/cmake/cmake_layout.html and https://docs.conan.io/2/reference/conanfile/methods/layout.html?highlight=build_folder_vars

For the ``cmakeExecutable`` it might be necessary to wait until the next release I think, but it would be good to try this flow, skipping at the moment the requirement for the ``cmake`` path (and in any case, if the cmake package version doesn't change from one profile to the other, then it will be ok, not needing a restart)

**Comment by elvisdukaj** [comment]
> Minor nitpick :) Those are called profiles files. Recipes are conanfile.py files (or even conanfile.txt) 

Yes true my bad! I was thinking to profiles but typing recipe!


> Try to not include a mostly unrelated profile. The base profile is a msvc, while the android one is basically overriding completely all the settings. My recommendation would be to not do an include, just copy the parts like tool_requires that you might need. Or refactor the common parts to a basic profile that is included both by msvc profile and android profile.

Very good point, I splitted the common part in `org_base` 

> We are working to add environment to the CMake presets. Even the cmakeExecutable. So in some cases, it will be possible to drop this step, just conan install + cmake --preset

This would definitely solve all my problems... It's also fine to have a local CMake installed but during the build process that one specified in the profile/recipe should be used! I love it and I am looking forward to see this! Do you have any ETA for this?

> I think this flow can be implemented with Conan generated presets for IDEs that support them, like this works nice with VSCode. The build_folder_vars, which can be both a conf in your profiles, or hardcoded in the recipe as layout() can be used to generate as many different presets as you want, including the os, the arch and other things. Then the IDE should be able to switch from one to other preset without re-initializing (that is assuming the environment from the presets is enough)

I created a template to create a new project `conan new org_cmake_lib ...` and the layout function looks like:

```Python
    def layout(self):
        if self.settings.os == 'Android':
            self.folders.build_folder_vars = [
                "settings.os", "settings.os.api_level",
                "settings.arch", "settings.compiler",
                "settings.compiler.version"
                ]        
        else:
            self.folders.build_folder_vars = [
                "settings.os",
                "settings.arch", "settings.compiler",
                "settings.compiler.version"
                ] 
```

So the preset for now are well organised and from the IDE it's working fine. The issue is that the environment is not changing, so for instance switch from `androidr21e` to `androidr26` is not working as the environment variables are not changing at the moment.

**Comment by memsharded** [comment]
> This would definitely solve all my problems... It's also fine to have a local CMake installed but during the build process that one specified in the profile/recipe should be used! I love it and I am looking forward to see this! Do you have any ETA for this?

We are aiming for next week, lets see if possible.

For the presets consider:

```python
 def layout(self):
        self.folders.build_folder_vars = [ "settings.os", "settings.arch", "settings.compiler",
                                           "settings.compiler.version"] 
       if self.settings.os == 'Android':
            self.folders.build_folder_vars.insert(1, "settings.os.api_level") 
```
As a shorter form if necessary, BUT... it might not be necessary, try doing just:
```python
 def layout(self):
      self.folders.build_folder_vars = ["settings.os", "settings.os.api_level",
                                        "settings.arch", "settings.compiler", "settings.compiler.version"]
```
Because Conan will automatically filter out ``None`` values, so if ``os.api_level`` is not defined, it will be just dropped      


> So the preset for now are well organised and from the IDE it's working fine. The issue is that the environment is not changing, so for instance switch from androidr21e to androidr26 is not working as the environment variables are not changing at the moment.

Can you check and share your ``CMakePresets.json`` generated by Conan? It should have different ``env`` defined for the different versions

**Comment by elvisdukaj** [comment]
> Because Conan will automatically filter out None values, so if os.api_level is not defined, it will be just dropped

Nice! Indeed works as expected!

You are absolutely right, the `CMakePresets.json` has all the environment! That's amazing! 

I was confused because I was trying to create a Conan plugin for `gradle`, but gradle is not using the `--preset` for building and that confused me! But this a bit more complex topic!

So that means that calling `cmake --preset xxx` will just work and there is not much more need to call source the build environment! That's amazing I am happy that I can just call `cmake` from the IDEs! I tested it with CLion and works really great!

I am looking forward to have also the `cmakeExecutable` to close the circle!

Thank you for your hard work! I hope I can push Conan for replacing our home-made tools.

**Comment by memsharded** [comment]
Excellent, thanks for the feedback!

Then, keep tuned for the next release, and give it a try when it is out. We can leave this ticket open until then :)

**Comment by elvisdukaj** [comment]
@memsharded  I see that that `conan 2.1.0` populates correctly the `cmakeExecutable` field! I think that this thread could be marked as solved :)

**Comment by memsharded** [comment]
Great, thanks for following up!
