### ISSUE TITLE
Package IDs generated for the identical sources are different on Windows.

### ISSUE THREAD

**Issue by bemehiser** [conan-io/conan#15586]
### Environment details

* Operating System+version: Windows 11 (vs macOS, Linux, iOS, Android)
* Compiler+version: msvc 193
* Conan version: 2.0.17
* Python version: 3.12.1

### Steps to reproduce

We are building multiple packages in parallel on Jenkins from identical sources/conanfile. The build runs with specific profiles for each os/arch, and uploads the resulting packages to our Artifactory server. The package id for every package is the same, except for on Windows. Because Windows has a different package ID, and builds slower than all the other platforms, it is uploaded last. Since the package is "newer", even though it was built from the same sources as all the other packages, it "replaces" the other packages in artifactory. When our subsequent build job runs, it can only find pre-built binaries for the "newer" windows package, and all the other platforms must rebuild.

Why would a package be built with a different package id on Windows? What influences the package id calculation? Is this expected, and is there a way we can make all packages have the same package id, regardless of platform?

### Logs

```
linux-ppc64le	transfer-sdk/1.0.0#36a679b7f7247bd15345f478cc933c0a:68fd133fb1784e5c993d134b92b180477e8108e5
linus-s390x	transfer-sdk/1.0.0#36a679b7f7247bd15345f478cc933c0a:f505c010f46f467adfef5be5f616c0eba179b03a
linux-x86_64	transfer-sdk/1.0.0#36a679b7f7247bd15345f478cc933c0a:706ce9c18ce0d6272184eaed43c59d538bda4088
macos-armv8	transfer-sdk/1.0.0#36a679b7f7247bd15345f478cc933c0a:eaa5855aa71fffcd8c837d7d19875ea36ba88cc3
macos-x86_64	transfer-sdk/1.0.0#36a679b7f7247bd15345f478cc933c0a:9aaa30ea5cb5280742bcf9f068267c417e3bd7ef
windows-x86_64	transfer-sdk/1.0.0#61412df02533871ab878e67b04bc5c69:90d0a3cbf3b19612b07183f343be458f3c0c3e47
                                   ^^^ package_id is different on Windows
```

**Comment by bemehiser** [comment]
The conanfiles and other sources _looked_ identical, but they had different line endings, so therefore different checksums. The solution was to set `eol=lf` for the `git clone` so they files would actually be the same on all platforms.
https://github.com/conan-io/conan/issues/13054

**Comment by memsharded** [comment]
Hi @bemehiser 

glad that you found the issue so quickly!
