### ISSUE TITLE
[bug] Impossible to add a CMake definition

### ISSUE THREAD

**Issue by JD31** [conan-io/conan#15581]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: msvc 2022
* Conan version: 1.62
* Python version: 3.11.3

### Steps to reproduce

I took the example from here as start point : https://docs.conan.io/1/creating_packages/getting_started.html
I need to add a cmake definition, which is linked to a conan option:

```
    options = {"shared": [True, False], "withDebugUI": [True, False]}
    default_options = {"shared": False, "withDebugUI": True}
    
    def build(self):
        cmake = CMake(self)
        cmake.definitions['SMARTMAP_DEBUG_UI'] = self.options.withDebugUI
        cmake.configure()
        cmake.build()
```

When doing `conan create . author/testing -pr:b=default`, the line `cmake.definitions` fails with
>         cmake.definitions['SMARTMAP_DEBUG_UI'] = self.options.withDebugUI
>         AttributeError: 'CMake' object has no attribute 'definitions'

Note that without this cmake.definition line I am able to build the project thus the conan/cmake installation is good I guess.

**Comment by memsharded** [comment]
Hi @JD31 

Thanks for your question.
The getting started is using the new ``CMake``, note ``from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout``

The new ``CMake`` doesn't have definitions anymore, you have to define them in ``CMakeToolchain``, please check: https://docs.conan.io/1/reference/conanfile/tools/cmake/cmaketoolchain.html (using ``cache_variables`` or ``variables``)


In any case, if you are starting to learn Conan, please note that Conan 1.X is no longer recommended, please use Conan 2.0.

**Comment by JD31** [comment]
Thank you so much !
I used to use conan 1.X but older version without the CMakeToolChain tool.

Unfortunatly I now have another error:

> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> compiler=Visual Studio
> compiler.runtime=MD
> compiler.version=17
> os=Windows
> os_build=Windows
> [options]
> withDebugUI=True
> [build_requires]
> [env]
> 
> ERROR: C:\workspace\smart-map-clion\test_package\conanfile.py: option 'withDebugUI' doesn't exist
> Possible options are []

It is like the options which are in the profile are not well taken into account.

**Comment by memsharded** [comment]
Options are defined per-package, so you typically need a pattern, like 
```
[options]
mypkg/*:withDebugUI=True
```
You can do ``*:withDebugUI=True`` if it will apply to many packages

**Comment by JD31** [comment]
I see. The option was then passed to the test_package where it is not define.
Thank you so much for your help.
It is working as expected.
