### ISSUE TITLE
[question]  Recipe not found when dowload of an package from Artifactory

### ISSUE THREAD

**Issue by ZenwalkerD** [conan-io/conan#15589]
### What is your question?

Hi,

I have installed conan via PIP and below is the details:
```
> conan -v
Conan version 1.62.0
```
I am trying to download Conan packages from Jfrog artifactory (private hosted in my comapany). So in order to get this done; i executed below commands:

Powershell:
```
> conan remote add energy-release-conan-egll https://xyz.jfrog.io/artifactory/api/conan/energy-release-conan-egll
> conan user -p <Key> -r energy-release-conan-egll <user>
> $env:CONAN_REVISIONS_ENABLED=1 
```

Then now when i execute below command i get the error as shown:
```
> conan download somepackage/9.70.0@repo/stable
ERROR: Recipe not found: 'sip5-cfgtools/9.70.0@repo/stable'
```

In JFrog Artifactory web portal; i can see the package and all its contents as shown:
![image](https://github.com/conan-io/conan/assets/869964/ff0f1c58-3c50-430a-a11d-0119b604b9e7)

Kindly please help as what i need to do in order to download the package? I dont want to install it. Just download!

Thanks 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ZenwalkerD 

I guess you found the issue yourself? Please let us know if you need any further clarification
