### ISSUE TITLE
[feature] Support new ``msvc`` versioning for VS2022 latest toolsets

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#15583]
### What is your suggestion?

vs2017 -> platform toolset v141 -> msvc 19.1x
vs2019 -> platform toolset v142 -> msvc 19.2x
vs2022 -> platform toolset v143 -> msvc 19.3x
vs2022 , version 17.10 and higher -> platform toolset  v143 ->  msvc toolset 14.40 -> msvc 19.4x

From: https://devblogs.microsoft.com/cppblog/msvc-toolset-minor-version-number-14-40-in-vs-2022-v17-10/

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by Nekto89** [comment]
Do I understand correctly that currently conan doesn't support stabilization at vs2022 update 10 which is currently in Preview?

**Comment by memsharded** [comment]
Not yet,  #15588 intends to improve this, but honestly the versioning approach of Microsoft is a bit messed up with this change, so this is complicated to map it.

**Comment by Nekto89** [comment]
I've just installed VS2022 Update 10 Preview 6 and tried to check how it works.
It requires at least CMake 3.29 https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9271
`cmake -G"Visual Studio 17 2022" "-Tv143,version=14.40.17.10"`

Will conan support this version of VS2022 in 2.3.0? If yes, when it will be released?

**Comment by memsharded** [comment]
Yes, it is intended in https://github.com/conan-io/conan/pull/15588 for 2.3, next week.

**Comment by memsharded** [comment]
Closed in https://github.com/conan-io/conan/pull/15588 for 2.3.1
