### ISSUE TITLE
[bug] EnvVars.save_script() generates incorrect paths when placing a recipe in `/build/` folder

### ISSUE THREAD

**Issue by Ariox41** [conan-io/conan#15585]
### Environment details

* Operating System+version: debian 10
* Compiler+version: gcc 8
* Conan version: 2.0.17
* Python version: 3.7

### Steps to reproduce

When building recipes in docker images, I usually use the `docker run --rm -it -w /build -v $PWD:/build my_image bash`  command. I recently discovered a strange behavior caused by the generation of incorrect paths in environment variables in the form of `$script_folder/../../..$script_folder/../../..`.

Due to the use of the rarely used working directory `/build/`, when using `cmake_layout` in recipes, the `self.generators_folder` becomes `/build/build/generators`, and conan replaces the `build` fragment with `$script_folder/../../..` twice in the `EnvVars.save_script()` implementation.

**Comment by memsharded** [comment]
Hi @Ariox41 

Thanks for your report.

I think there could be something else beyond the generation, like those substitutions happen typically in deployers.
It would be necessary to have something we can reproduce. Ideally without the docker image, to rule out possible issues related to docker. Could you please put together some (as minimal as possible) files and instructions to reproduce the issue? Thanks!

**Comment by Ariox41** [comment]
Is there an official conan2 docker image ? I was able to reproduce the problem as follows:

```shell
docker run --rm -it -w /build python bash
python3 -m pip install conan
conan profile detect
apt-get update
apt-get install cmake
conan new cmake_exe -d name=game -d version=1.0 -d requires=zlib/1.3.1 
conan install . -b missing
cat ./build/Release/generators/conanbuild
```
Output:

```shell
script_folder="/build/build/Release/generators"
echo "echo Restoring environment" > "$script_folder/../../..$script_folder/../../../Release/generators/deactivate_conanbuildenv-release-x86_64.sh"
for v in 
do
    is_defined="true"
    value=$(printenv $v) || is_defined="" || true
    if [ -n "$value" ] || [ -n "$is_defined" ]
    then
        echo export "$v='$value'" >> "$script_folder/../../..$script_folder/../../../Release/generators/deactivate_conanbuildenv-release-x86_64.sh"
    else
        echo unset $v >> "$script_folder/../../..$script_folder/../../../Release/generators/deactivate_conanbuildenv-release-x86_64.sh"
    fi
done
```
In this case, the problem manifests itself a little differently, but the reason is the same

**Comment by memsharded** [comment]
> Is there an official conan2 docker image ? 

We have some images in ``conanio``, like ``conanio/gcc11`` you might use

I have tried with that image and I get:

```
conan@1807b7f92fc9:~$ cat ./build/Release/generators/conanbuild.sh                                                                                            
. "/home/conan/build/Release/generators/conanbuildenv-release-x86_64.sh"conan@1807b7f92fc9:~$ cat ./build/Release/generators/conanbuildenv-release-x86_64.sh  
script_folder="/home/conan/build/Release/generators"                                                                                                          
echo "echo Restoring environment" > "$script_folder/../../../build/Release/generators/deactivate_conanbuildenv-release-x86_64.sh"                             
for v in                                                                                                                                                      
do                                                                                                                                                            
    is_defined="true"                                                                                                                                         
    value=$(printenv $v) || is_defined="" || true                                                                                                             
    if [ -n "$value" ] || [ -n "$is_defined" ]                                                                                                                
    then                                                                                                                                                      
        echo export "$v='$value'" >> "$script_folder/../../../build/Release/generators/deactivate_conanbuildenv-release-x86_64.sh"                            
    else                                                                                                                                                      
        echo unset $v >> "$script_folder/../../../build/Release/generators/deactivate_conanbuildenv-release-x86_64.sh"                                        
    fi                                                                                                                                                        
done                                                                                                                                                          
```

Note the file I am listing is ``./build/Release/generators/conanbuildenv-release-x86_64.sh``, not the one you suggested, I guess that is a typo?

Then, I tried your example, and it reproduced (with the above correction of the file). The difference is the usage of the ``/build`` folder, I don't know yet exactly why it matters, but seems related

**Comment by memsharded** [comment]
I got what is happening.

It is the name of the matching ``/build`` root folder that matches the intermediate ``/build`` path, where the full path is ``/build/build/generators...``.
It never happens in Windows where ``C:/`` unit will break the pattern
It never happens in Linux or OSX in any folder like ``/home/user`` or similar that won't be found in paths

While I can easily fix the ``deactivate`` code, changing this for the general case of your own env-vars would be way more challenging, and require parsing the whole shell script for paths. I'd recommend to use any other name rather than just ``/build``  at the root of the file system, something like ``/mybuild`` or ``home/user/build`` should work.

**Comment by Ariox41** [comment]
Changing the build directory solves my problem. Changing the directory itself is not a problem. However, the problem with paths in variables is hardly noticeable, and in many cases it does not manifest itself. When using `VirtualBuildEnv`, the values of the environment variables are not damaged, only the paths to the recovery scripts are damaged. I was lucky enough to notice this problem in a limited environment when building Qt manually. But in a complex system, it can take a long time to find the cause of the problem. Therefore, I believe that in such cases, conan should at least output a warning or throw an exception.

I just reported the bug I found, I cannot say that the potential cost of the bug will be higher than the cost of fixing it.

**Comment by memsharded** [comment]
> Changing the build directory solves my problem. 

Happy to know it :)

> Changing the directory itself is not a problem. However, the problem with paths in variables is hardly noticeable, and in many cases it does not manifest itself. When using VirtualBuildEnv, the values of the environment variables are not damaged, only the paths to the recovery scripts are damaged. I was lucky enough to notice this problem in a limited environment when building Qt manually. But in a complex system, it can take a long time to find the cause of the problem. Therefore, I believe that in such cases, conan should at least output a warning or throw an exception.

> I just reported the bug I found, I cannot say that the potential cost of the bug will be higher than the cost of fixing it.

Thanks for the feedback @Ariox41 

Yes, I agree, this is why I kept trying yesterday after my last report to improve this, even if challenging, didn't give up, and came up with https://github.com/conan-io/conan/pull/15592. Still early stage, but might be able to cover the issue correctly, at least for ``VirtualBuildEnv``. I still need to check for other generators, so still some work to do, and there are other risks that should be taken into account, but at least we are trying.

**Comment by memsharded** [comment]
Hi @Ariox41 

PR https://github.com/conan-io/conan/pull/15592 should fix completely the issue for ``VirtualXXXEnv`` generators, as full correct processing of paths is done now. The issue will persist at the moment for ``CMakeToolchain`` and ``CMakeDeps``, we will keep working on it for future releases. 

Still, having a root name that is more unique will completely avoid the issue.
Thanks for the feedback!
