### ISSUE TITLE
[question] How to set given CMake flag for library if it's not supported by package description?

### ISSUE THREAD

**Issue by Kaaml** [conan-io/conan#15594]
### What is your question?

Hi, 
I'm using conan 1.x and I wonder how should I set CMake flag for dependency of my project. 
I'm using Date library installed by conan, In package [conanfile.py Date](https://github.com/conan-io/conan-center-index/blob/master/recipes/date/all/conanfile.py) file I don't see possibility to set CMake flag `MANUAL_TZ_DB` from [Date](https://github.com/HowardHinnant/date/blob/master/CMakeLists.txt). 

I cannot find in documentation any option to directly set this flag for building this library, could you explain me how should I do this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Kaaml 

thanks for your question.

The high level customizable interface of packages is exposed by the  ``options``. In this case I see:
```python
 options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "header_only": [True, False],
        "use_system_tz_db": [True, False],
        "use_tz_db_in_dot": [True, False],
    }
```
Indeed, I don't see any option that allows to set this build configuration.
If you want to customize it, there could be a few different approaches:

- Work from a fork of ``conan-center-index`` repo, so you can use your own customizations. This is the approach recommended in https://docs.conan.io/2/devops/using_conancenter.html for those organizations that need to customize recipes and build their own binaries
- If this would be a popular use case, it could make sense to contribute a new ``option`` to the recipe to enable controlling it
- There are ways to inject things into the build systems of the dependencies. In this case, as it is using ``CMake``, you might be able to inject via toolchain any arbitrary CMake variables, so maybe it is possible to "hack" the package build. See how to inject an arbitrary cmake toolchain in https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/inject_cmake_variables.html. This doesn't sound like the cleanest approach, but might be doable

**Comment by Kaaml** [comment]
@memshard
Thanks for you answeer. Probably I'll contribute new option and temporarly until it woulnd't be merged I use the cmake variable injection.
