### ISSUE TITLE
How to create packages with Premake?

### ISSUE THREAD

**Issue by jinq0123** [conan-io/conan#1559]
[Docs » Creating packages » Getting started](http://docs.conan.io/en/latest/packaging/getting_started.html#creating-the-package-recipe)
uses CMake to create packages. I tried to use Premake to create packages and found it is too hard.

See my codes:
```
git@github.com:jinq0123/csv_parser_RFC4180.git

Revision: 77f305835cf2efbc1a1235444c2592dd6a35a563
Author: Jin Qing <jinq0123@163.com>
Date: 17.8.1 16:36:51
Message:
Fix python format warning.
```

The problem is conan has no build helper for Premake.

CMake is simple:
```python
    def build(self):
        cmake = CMake(self)
        self.run('cmake hello %s' % cmake.command_line)
        self.run("cmake --build . %s" % cmake.build_config)
```

My `build()` using Premake only for vs2015:
```python
    def build(self):
        if self.settings.compiler == "Visual Studio":
            self.run("premake5.exe --os=windows vs2015")
            env_build = VisualStudioBuildEnvironment(self)
            with tools.environment_append(env_build.vars):
                cmd = tools.msvc_build_command(self.settings,
                    "csv_parser_RFC4180.sln",
                    targets=["csv_parser_RFC4180"],
                    upgrade_project = False)
                self.run(cmd)

        # There must be other codes for other settings like:
        # if self.settings.compiler == "gcc":
        #     ...
        # if self.settings.compiler == "clang":
        #     ...
```

x86_64 build is OK, but `conan create jinq0123/testing -s arch=x86` results error:
```
ERROR: csv_parser_RFC4180/0.1@jinq0123/testing: Error in build() method, line 25
        self.run(cmd)
        ConanException: Error 1 while executing call 
 "D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\../../VC/vcvarsall.bat"
 x86 && msbuild csv_parser_RFC4180.sln
 /p:Configuration=Release /p:Platform="x86"
 /target:csv_parser_RFC4180
```
because "Release|x86" is invalid. I don't know how to change it to "Release|Win32".

Solution may be one of these:
* Use cmake to create packages
* Write build helper for premake
* Patch Premake to provide function as `cmake --build`

**Comment by memsharded** [comment]
Hi @jinq0123 

- About using cmake to create packages, that might not be an option, for people willing (or having to) use premake
- Premake providing a ``--build`` option sure be helpful for premake users, not only for conan. I would suggest that not only as a patch, but as a contribution to premake for future release
- A build helper for premake, totally makes sense. I am not an expert, but if we can get to a working package, contributing a ``Premake`` helper as built-in for conan wouldn't be difficult.

I am trying to check your repo, but I only see the ``cmake`` version. If you are able to put your proposal for ``build()`` in a branch, I could try it. Thanks!

**Comment by jinq0123** [comment]
I have changed it to using cmake. Please checkout rev 77f305 for premake version.

**Comment by memsharded** [comment]
I think this issue can be closed. The OP, @jinq0123 has switched to CMake. If someone is interested in having a Premake build helper, please re-open the issue, but I am closing it until there is someone who is going to really use it and help to build and test it. Thanks!
