### ISSUE TITLE
[feature] add `--format=json` to conan cache path

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#15599]
### What is your suggestion?

I would like for conan to be able to give me a machine readable file, rather than having to pipe the output of the `conan cache path` command.

There's nothing wrong with piping, but this makes life slightly easier on a CI system that needs to support both bash syntax and bat/cmd syntax on Windows. 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
We probably want this extended to `conan config home` if we end up likeing this idea

**Comment by memsharded** [comment]
These 2 commands were intended to get the "text" output also valid for automation. So when a command returns a single string (path) as a result, the text in ``stdout`` will be equivalent to a potential ``json`` output with 
```
{"path": "/result/path"}
```
Though maybe the line ending in the terminal is disturbing the "text" flow? In that case, sure, I don't oppose to have a json formatter for these commands, good to me
