### ISSUE TITLE
[question] Tracking Downloads

### ISSUE THREAD

**Issue by mals512** [conan-io/conan#15604]
### What is your question?

Hi, how can I track how many people are using/downloading my package on Conan?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
You mean a package in ConanCenter?

This is challenging to know, due to the different moving pieces it was difficult to collect stats in a robust way.  We tried to add some metrics some time ago, but it was costly and not very accurate, so it was dropped.

**Comment by mals512** [comment]
> You mean a package in ConanCenter?
> 
> This is challenging to know, due to the different moving pieces it was difficult to collect stats in a robust way. We tried to add some metrics some time ago, but it was costly and not very accurate, so it was dropped.

Yes, a package in ConanCenter. I am curious how many people are using it.

**Comment by memsharded** [comment]
this would be this discussion here: https://github.com/conan-io/web/issues/144, closing this ticket as duplicated, please follow up there.
