### ISSUE TITLE
[bug] messed console message color in pwsh with redirected stdout

### ISSUE THREAD

**Issue by X1aomu** [conan-io/conan#15615]
### Environment details

* Operating System+version: Windows 11 + pwsh 7.4.1
* Compiler+version: not related
* Conan version: 2.0.17
* Python version: 3.11.7

### Steps to reproduce

1. find any recipe to run `conan export` against
2. in pwsh, run `conan export <recipe> -f json > abc.txt`
3. console color is messed up
4. run `conan export <recipe>` to see the correct color
5. `-f.json` can be omited

### Logs

![image](https://github.com/conan-io/conan/assets/18374537/abeeadc7-a7d2-449c-bced-74d99b99cb0b)

**Comment by memsharded** [comment]
Hi @X1aomu 

Thanks for your report.

Unfortunately this seems out of our control, but it seems a ``colorama`` issue, check: https://github.com/tartley/colorama/issues/218 or https://github.com/tartley/colorama/issues/335

We have seen this issue in other terminals like ``cmd`` and ``cmder`` with previous Python versions, but it seems with latest Python like 3.10 it is no longer a problem for us. But it seems the issue remains similar for powershell terminals.

To disable colors, there is the ``$Env:NO_COLOR=1`` you can use to disable colors if necessary.

I suggest closing this ticket, as there is little we can do it from here, and track the ``colorama`` issues.

**Comment by X1aomu** [comment]
Thanks for pointing out the cause. Can close now. Let's reopen this when it is fixed on upstream, to make sure conan get updated.
