### ISSUE TITLE
CMake: dependency of dependency not added correctly to linker input files (Visual Studio)

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#1561]
I just created a new library and a test program to go with it.
The library requires boost, which in turn requires zlib.

The library is generated ok, but not the test program, which fails because the linker cannot find `zlibstatic.lib`.

When I looked at the project configuration for the test program, I noticed that the linker input file `zlibstatic.lib` was pathless (whereas all boost libraries were correctly listed with their full conan paths).

The problem can be worked around by explicitly adding a package providing zlib to the conan dependencies of the library (EDIT: I previously stated, wrongly, that zlib must be defined as a dependency of the test program - that is not the case, the test program does not use conan at all).

**Comment by memsharded** [comment]
Hi!

I am missing some important information. If you could share with me some reproducible recipe, and steps, that would help. Also which Boost packages are using, some public or are you creating your own boost packages, the same for the zlib package. If you can't share it in public, you can also send private email.

Thanks!

**Comment by JPGygax68** [comment]
Here is the current state of the project. It works as it is; to reproduce the problem, just remove zlib from the conanfile in the lib subdirectory before doing `conan install` in the build directory.

I'm also attaching the script I use to do `conan install` on all directories of a project tree.

[libGPCInterproc.zip](https://github.com/conan-io/conan/files/1191333/libGPCInterproc.zip)
[conan-install.zip](https://github.com/conan-io/conan/files/1191336/conan-install.zip)

**Comment by memsharded** [comment]
I have tried to build it from your project, but not successful so far. I will try again tomorrow, thanks for sharing your project!

**Comment by JPGygax68** [comment]
Uh, I wouldn't call it a project just yet. Anyway, thanks to you for looking into this!

**Comment by lasote** [comment]
I'm taking a quick look to the project files. So, the "tests" folder program is the one failing, right? The CMakeLists.txt is not specifying nor including any conanbuildinfo.cmake or similar, at least you are building your library as a shared one (embedding zlib and boost) it will fail. Am I missing something?

**Comment by JPGygax68** [comment]
`test_server` is the project that is failing; it is not using conan by itself, but it should inherit, via CMake, all the dependencies of `libGPCInterproc`. 
`libGPCInterproc` in fact only depends on Boost, but Boost in turn depends on zlib. That latter dependency is not being passed correctly. In the `test_server` linker settings, it was listed as simply `zlibstatic`, without any path.
(I'm not at home right now so I cannot verify if this is still reproduceable.)

**Comment by ruipires** [comment]
Hi,

Have you tried the "targets" approach ?
That should give you all the dependencies (and sub-dependencies) of a
particular library, as long as conan is aware of them.

http://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html#targets-approach

Cheers,
Rui

**Comment by JPGygax68** [comment]
The library I'm trying to link *is* being built with TARGETS:

```language=cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)
conan_basic_setup(TARGETS)


add_library(${PROJECT_NAME}
  
  include/gpc/interproc/Lock_free_ringbuffer.hpp src/Lock_free_ringbuffer.cpp
  
  conanfile.txt
)

target_include_directories(${PROJECT_NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)

target_link_libraries(${PROJECT_NAME} PUBLIC CONAN_PKG::boost)
```

**Comment by JPGygax68** [comment]
Here's the list of dependencies in in the linker configuration of `test_server`:
```
..\..\lib\Debug\libGPCInterproc.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_wave.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_unit_test_framework.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_prg_exec_monitor.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_test_exec_monitor.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_container.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_exception.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_graph.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_iostreams.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_locale.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_log.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_log_setup.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_math_c99.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_math_c99f.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_math_c99l.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_math_tr1.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_math_tr1f.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_math_tr1l.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_program_options.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_random.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_regex.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_wserialization.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_serialization.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_signals.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_coroutine.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_context.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_timer.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_thread.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_chrono.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_date_time.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_atomic.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_filesystem.lib
C:\Users\gygax\.conan\data\boost\1.64.0\hoxnox\testing\package\6d9c1f1b056007ba9bb908f9da63e34d88dc031e\lib\libboost_system.lib
zlibstatic.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
```

As you can see, the boost libraries have their full paths, while `zlibstatic.lib` gets inserted "naked", which of course doesn't work.

**Comment by JPGygax68** [comment]
I just experienced the same problem on a different project, but this time I couldn't work around it by adding the dependency at the top level.

I think it has to do with my using `cmake_multi`. This problem only seems to happen in Debug builds (whereas Release builds have a different set of problems I need to investigate tomorrow).

**Comment by memsharded** [comment]
These generators are deprecated now, new generators in https://docs.conan.io/en/latest/reference/conanfile/tools.html should be used instead, please report against them if necessary.
