### ISSUE TITLE
Check handling around `.dirty` usage in file download handlings

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#15612]
We found some issues in https://github.com/conan-io/conan/pull/15601

Specifically, `.dirty` files in the local backup cache can be left without their corresponding failed file and never be removed, nor a warning that there was ever a dirty file be printed.

We should look into reviewing this pattern and coming up with a cleaner solution the works for all the current use-cases

**Comment by AbrilRBS** [comment]
Closing in favour of https://github.com/conan-io/conan/issues/15840

**Comment by memsharded** [comment]
In principle the scope of https://github.com/conan-io/conan/issues/15840 was not covering the file-download cache, but I agree that the .dirty mechanism revamp should also apply to file-download cache.
