### ISSUE TITLE
can a conan recipe be added as dependency to another conan recipe?

### ISSUE THREAD

**Issue by rajesh-kareti-infovision** [conan-io/conan#15621]
### What is your question?

I have 2 module A,B . Both have recipe(conanfile.py) and i call conan build for A and conan build for B.
I want to add A as dependency to B and conan build of A should invoke conan build of B?
requirements section is to get the binaries i assume? So is there a way to add conan recipe as requirement for another recipe?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rajesh-kareti-infovision 

Thanks for your question.

I am afraid this is not how a package manager works. Packages are managed independently, and each package can in fact have a different build system. It is not the responsibility of one package to fire the build of its dependencies, but the package manager will manage to build such dependencies when necessary. If there are pre-compiled binaries it will use the binaries, and if not, it will fail unless the ``--build=missing`` is provided, but in any case, all of that is abstracted away from the consumers of the packages. Every package will use its dependencies assuming they are already built binaries.

You define requirements among packages with either ``requires = "myotherpkg/1.0"`` or with the equivalent 
```python
def requirements(self):
    self.requires("myotherpkg/1.0")
```
In either case will be the package firing the build of the dependency.

I hope this clarifies the topic.
