### ISSUE TITLE
[question] How to provide package folder to conan export-pkg in conan2?

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#15636]
### What is your question?

Hi,

I'm trying to repack packages that contain prebuilt binaries. In conan1 I was running `conan export-pkg` and giving package folder as input with all the necessary files so conan recipe was just taking everything from there. In conan2 I don't see options that will allow me to do the same. I don't want to put binaries near the recipe. Do I need to add some custom processing in recipe with environment variables to achieve this? Is there some other way?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Nekto89 

The ``package()`` method  operates from ``source_folder`` and ``build_folder`` to the ``package_folder``. 
The ``package_folder`` is defined, but it is the folder in the Conan cache where the package is being exported. The local folders are source and build folders. 

Mostly something like:

```python
def package(self):
        copy(self, "*.h", os.path.join(self.source_folder, "include"),
             os.path.join(self.package_folder, "inc"))
        copy(self, "*.lib", os.path.join(self.build_folder, "lib"),
             os.path.join(self.package_folder, "lib"))
```

should work both in Conan 1.X and Conan 2.0 (if necessary, define a ``layout()``), have you tried this?

**Comment by Nekto89** [comment]
> Hi @Nekto89
> 
> The `package()` method operates from `source_folder` and `build_folder` to the `package_folder`. The `package_folder` is defined, but it is the folder in the Conan cache where the package is being exported. The local folders are source and build folders.
> 
> Mostly something like:
> 
> ```python
> def package(self):
>         copy(self, "*.h", os.path.join(self.source_folder, "include"),
>              os.path.join(self.package_folder, "inc"))
>         copy(self, "*.lib", os.path.join(self.build_folder, "lib"),
>              os.path.join(self.package_folder, "lib"))
> ```
> 
> should work both in Conan 1.X and Conan 2.0 (if necessary, define a `layout()`), have you tried this?

How do I inject my external folder? In Conan 1.x there were parameters "[-pf PACKAGE_FOLDER] [-sf SOURCE_FOLDER]". I don't see any similar parameters in Conan 2.0. My files aren't located anywhere near the recipe. I can probably copy the recipe to the binaries before export, but it will be very strange thing to do in my opinion.

**Comment by Nekto89** [comment]
that's what I was doing with Conan 1.X. Recipe didn't have any logic except for package_info and self.copy("*"). https://docs.conan.io/1/creating_packages/existing_binaries.html#packaging-pre-built-binaries

```
cd /d %CD%\input
conan export-pkg -pf . -f -s os=Windows C:/conan/test_conan/recipes/my_library/all/conanfile.py my_library/1.0@user/channel
cd /d %CD%\..
conan test -s os=Windows -s build_type=Release C:/conan/test_conan/recipes/my_library/all/test_package/conanfile.py my_library/1.0@user/channel
```

**Comment by Nekto89** [comment]
it seems that
 ```
-of OUTPUT_FOLDER, --output-folder OUTPUT_FOLDER
The root output folder for generated and build files
```
can be used in recipe as self.build_folder. But conan also puts temporary files there.

**Comment by Nekto89** [comment]
This seems to be working, at least on Windows there are no files that are created in input folder.

`conan export-pkg -nr -tf C:/conan/test_conan/recipes/package/all/test_package -of "%CD%" --name package --version 1.0 --user user --channel channel -s os=Windows C:/conan/test_conan/recipes/package/all/conanfile.py`

```
from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.env import VirtualBuildEnv, VirtualRunEnv
from conan.tools.files import copy

required_conan_version = ">=1.47.0"


class PackageConan(ConanFile):
    name = "package"
    description = "Some package"
    license = "Custom"
    url = ""
    topics = ("topic")
    package_type = "shared-library"
    settings = "os", "arch", "compiler", "build_type"
    build_policy = "never"
    
    def layout(self):
        pass

    def package_id(self):
        del self.info.settings.compiler
        del self.info.settings.build_type

    def validate(self):
        if self.settings.os != "Windows":
            raise ConanInvalidConfiguration(f"{self.ref} supports only Windows")
        if self.settings.arch != "x86_64":
            raise ConanInvalidConfiguration(f"{self.ref} supports only x86_64")

    def source(self):
        pass

    def generate(self):
        #suppress generation of env files
        VirtualBuildEnv(self)
        VirtualRunEnv(self)

    def build(self):
        pass

    def package(self):
        copy(self, "*", self.build_folder, self.package_folder)

    def package_info(self):
        self.cpp_info.frameworkdirs = []
        self.cpp_info.resdirs = []
        self.cpp_info.libs = ["package"]
```

**Comment by memsharded** [comment]
> In Conan 1.x there were parameters "[-pf PACKAGE_FOLDER] [-sf SOURCE_FOLDER]".

In Conan 2.0, something like the ``source_folder`` is defined by the ``layout()`` (also the relative ``build_folder``)

> can be used in recipe as self.build_folder. But conan also puts temporary files there.

yes, this would be the output folder for absolutely all files, the build files, the files generated by Conan, etc. In most cases it might not be necessary, and for example ``layout()`` defaults to a local "build" folder that can be easily git-ignored or removed when desired.

The ``self.source_folder`` is not affected by ``outtput-folder``, as it points to the original folder containing the source, typically to ``copy()`` the headers, which is part of the source files, not the built files.


Does it work now then with the information above? It is not fully clear if you made it work or not.

**Comment by Nekto89** [comment]
> > In Conan 1.x there were parameters "[-pf PACKAGE_FOLDER] [-sf SOURCE_FOLDER]".
> 
> In Conan 2.0, something like the `source_folder` is defined by the `layout()` (also the relative `build_folder`)
> 
> > can be used in recipe as self.build_folder. But conan also puts temporary files there.
> 
> yes, this would be the output folder for absolutely all files, the build files, the files generated by Conan, etc. In most cases it might not be necessary, and for example `layout()` defaults to a local "build" folder that can be easily git-ignored or removed when desired.
> 
> The `self.source_folder` is not affected by `outtput-folder`, as it points to the original folder containing the source, typically to `copy()` the headers, which is part of the source files, not the built files.
> 
> Does it work now then with the information above? It is not fully clear if you made it work or not.

Yes, I've used this approach to repack several packages from conan 1.X to conan 2.X.

**Comment by memsharded** [comment]
Sounds good, can we close the ticket as solved then?
