### ISSUE TITLE
[feature] Output dependency graph with conan build

### ISSUE THREAD

**Issue by antoinebardoz** [conan-io/conan#15634]
### What is your suggestion?

With ```conan create``` and ```conan install```, we can add ```-f json > somename.json``` to get a dependency graph out. However, we can't do the same for ```conan build```.

This seems like an oversight, because now it's possible to call ```conan build``` without calling ```conan install``` first, which I thought was nice. But it's not quite as nice if I'm now forced to call ```conan install``` just because I want the dependency graph.

Could you please add this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for the suggestion @antoinebardoz 

Yes, this makes sense, lets add it.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/15651, it will be in next 2.1 release
