### ISSUE TITLE
[question] conan2: upload multiple recipes

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#15649]
### What is your question?

Hi! I have a question about behavior of conan upload.

1) I'm exporting recipe from local folder through conan export which leads to package/1.0@user/channel#revA in my local cache.
2) I'm installing same package but different recipe revision through conan install --build=missing package/1.0@user/channel#revB. Recipe is downloaded from conan remote. Binaries are built during this install.
3) I want to upload everything that is currently in local cache and related to package/1.0@user/channel (without specifying recipe revision). conan upload -r remote --check --confirm package/1.0@user/channel. My expectations after looking at documentation: conan should upload recipe for package/1.0@user/channel#revA and binaries for package/1.0@user/channel#revB + tell that recipe for revB already exists on server. Actual result: conan uploads only recipe package/1.0@user/channel#revA without uploading binaries for package/1.0@user/channel#revB .

from documentation: "by default, all the matching references are uploaded (all revisions)."

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Nekto89 

Thanks for your question

> conan install --build=missing package/1.0@user/channel#revB

This is not Conan 2.0 syntax. Are you sure this is using Conan 2.0?

>  want to upload everything that is currently in local cache and related to package/1.0@user/channel (without specifying recipe revision). conan upload -r remote --check --confirm package/1.0@user/channel

By default ``conan upload`` uploads only latest revision in the cache If you want to upload all revisions, the syntax is:

```bash
conan upload pkg/1.0@user/channel#* -r=myremote -c
```

**Comment by Nekto89** [comment]
> Hi @Nekto89
> 
> Thanks for your question
> 
> > conan install --build=missing package/1.0@user/channel#revB
> 
> This is not Conan 2.0 syntax. Are you sure this is using Conan 2.0?
> 
> > want to upload everything that is currently in local cache and related to package/1.0@user/channel (without specifying recipe revision). conan upload -r remote --check --confirm package/1.0@user/channel
> 
> By default `conan upload` uploads only latest revision in the cache If you want to upload all revisions, the syntax is:
> 
> ```shell
> conan upload pkg/1.0@user/channel#* -r=myremote -c
> ```

You are right, I was writing from memory. Real command is like this:
`conan install  --profile:host=...host_windows --profile:host=.../build/packages/host_profile --profile:host=.../build/packages/additional_profile_options.txt --profile:host=.../Release --profile:build=.../build -of=.../build/packages --build=missing --generator=CMakeDeps .../build/packages/conanfile.py`

Thanks, I'll try with `#*`
