### ISSUE TITLE
[question] Issues building with SDL2_ttf and freetype. Unresolvable conflicts?

### ISSUE THREAD

**Issue by instinkt900** [conan-io/conan#15641]
I have an application that uses both SDL_ttf, freetype and harfbuzz directly and so I have the following conanfile.py
```
from conan import ConanFile
from conan.tools.cmake import cmake_layout

class FTTest(ConanFile):
    name = "fttest"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"

    def requirements(self):
        self.requires("sdl_ttf/2.20.2")
        self.requires("freetype/2.12.1")
        self.requires("harfbuzz/8.3.0")

    def build_requirements(self):
        self.tool_requires("cmake/3.27.9")

    def layout(self):
        cmake_layout(self)
```
When I run `conan install .` I get the following...
`ERROR: Version conflict: harfbuzz/8.3.0->freetype/2.13.2, fttest/0.1->freetype/2.12.1..`
Trying to resolve the conflict by working backwards through harfbuzz versions appears to not work since all available versions seem to use 2.13.2 of freetype. This is where I try an override...
`self.requires("freetype/2.12.1", override=True)`
This allows conan to complete it's configuration fine and so I run cmake with the following CMakeLists.txt
```
cmake_minimum_required(VERSION 3.10)

project(fttest VERSION 1.0 DESCRIPTION "Freetype testing")

find_package(Freetype REQUIRED)
find_package(SDL2_ttf REQUIRED)

add_library(${PROJECT_NAME} STATIC fttest.cpp)
target_link_libraries(${PROJECT_NAME} SDL2_ttf::SDL2_ttf-static)
target_link_libraries(${PROJECT_NAME} Freetype::Freetype)
```
and run `cmake --preset conan-default` which completes okay but I do notice a small warning,
```
CMake Warning at build/generators/freetypeTargets.cmake:25 (message):
  Target name 'freetype' already exists.
```
I ignore it and try to run `cmake --build --preset conan-release` (also tried this with debug config and same results) and I get the following error from MSVC,
`<snip>\fttest.cpp(1,10): fatal  error C1083: Cannot open include file: 'ft2build.h': No such file or directory [<snip>\fttest.vcxproj]`
After some messing about I tried to change the override and my freetype version so the requirements now look like,
```
        self.requires("sdl_ttf/2.20.2", override=True)
        self.requires("freetype/2.13.2")
        self.requires("harfbuzz/8.3.0")
```
Again, conan completes but this time cmake fails with,
```
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindSDL2_ttf.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2_ttf",
  but CMake did not find one.

  Could not find a package configuration file provided by "SDL2_ttf" with any
  of the following names:

    SDL2_ttfConfig.cmake
    sdl2_ttf-config.cmake

  Add the installation prefix of "SDL2_ttf" to CMAKE_PREFIX_PATH or set
  "SDL2_ttf_DIR" to a directory containing one of the above files.  If
  "SDL2_ttf" provides a separate development package or SDK, be sure it has
  been installed.
```
It seems that when adding override to the requirement, it does not end up in the cmake configuration? I think freetype behaves slightly differently because it's included as part of SDL_ttf so find package seems to complete but it would appear the headers still cannot be found when building?
I'm unsure about how to resolve this problem. Perhaps it's a bug, perhaps I'm not handling conflicts correctly, I just ran out of ideas and don't know where else to look. Thanks for any help or advice.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by instinkt900** [comment]
After browsing around conan center I noticed that SDL_ttf listed a different version of freetype than what it was reporting on my machine. So I tried to clean the cache with various `conan cache clean` commands. I noticed using `conan install` still said packages were cahced and my .conan2/p/ folder still had hundreds of packages so I went nuclear and deleted the folder.
Upon retrying now everything works when using the following requirements,
```
        self.requires("sdl_ttf/2.20.2")
        self.requires("freetype/2.13.2")
        self.requires("harfbuzz/8.3.0")
```
I don't know why my cache was broken or why cache clean wasn't actually cleaning the cache didn't clear the cache but now it configures and builds as expected.
Perhaps the issue can be closed, but I'm still confused about why using an override prevents cmake from being able to find it using find_package.

**Comment by memsharded** [comment]
Hi @instinkt900 

Thanks for your question.

It seems there could be some different issues here. I assume you are using Conan 2, is this correct?

The ``conan cache clean`` does not really remove packages. It only purges temporary build and download files while leaving the packages in place, so it is not good enough to remove old versions in the cache that could be creating conflicts. The correct command would be ``conan remove "*" -c`` (will clean both the packages and the temporary files associated with those packages).

Then, the conflicts can happen sometimes in ConanCenter, after new versions of packages are added or requirements are bumped. We are working to try to improve this and reduce these conflicts as much as possible. 
One possible strategy would be to use version ranges. For example if you can do ``self.requires("freetype/[>=2.12 <3]")``, then it will automatically adapt to the upstream dependency that ``harfbuzz`` is depending one, without conflict. Of course, if you really want version ``2.12.1`` there are 2 possibilities:
- Use ``override=True`` if you don't depend directly on the package. You don't have direct ``#include`` to freetype in your project. But if that is the case, you probably don't want to have a ``requires`` at all, and then just let your transitive dependency be naturally resolved
- Use ``force=True`` if you have a direct dependency on the package, with your project having ``#include`` to freetype.

> Perhaps the issue can be closed, but I'm still confused about why using an override prevents cmake from being able to find it using find_package.

``override=True`` means that, it is not a direct dependency. It shouldn't have a ``find_package()`` in your ``CMakeLists.txt`` at all.

Please let me know if this clarifies it. Thanks!

**Comment by instinkt900** [comment]
Yes I'm using Conan 2.

I might have missed that specific option to remove the packages. I'll keep that in mind. Thanks.

The option of adding the requirement with a range is something I did try but it wasn't working for me. Granted I probably messed up how I specified it or something. Since removing the packages resolved the version conflict I can't repro it again but I'll keep it in mind for the next time.

It's good to have it confirmed that override will prevent cmake from finding the package, I wasn't sure if that was expected behaviour or not, and I did try force too, but it was another thing that didn't seem to do anything. I can't remember if I still got the conflicts or if cmake was complaining about it missing. Another thing I'll keep in mind.

My issue has now slowly evolved into another loosly related issue. On linux, it seems that maybe harfbuzz introduced the glib dependency and it all configures and builds fine right up to linking and then I get an error about `g_module_open_full` being a missing symbol. I've tried a bunch of things but nothing seems to help. Though I'm not sure if this is something to do with how conan is building it, or the way the dependency is setup, or maybe the machine configuration. It might not be an issue for here.

**Comment by memsharded** [comment]
> It's good to have it confirmed that override will prevent cmake from finding the package, I wasn't sure if that was expected behaviour or not, and I did try force too, but it was another thing that didn't seem to do anything. I can't remember if I still got the conflicts or if cmake was complaining about it missing. Another thing I'll keep in mind.

Sounds good, I think in this regard we can close the issue, you can always create a new ticket with updated details when you can reproduce and we will have a look.

> My issue has now slowly evolved into another loosly related issue. On linux, it seems that maybe harfbuzz introduced the glib dependency and it all configures and builds fine right up to linking and then I get an error about g_module_open_full being a missing symbol. I've tried a bunch of things but nothing seems to help. Though I'm not sure if this is something to do with how conan is building it, or the way the dependency is setup, or maybe the machine configuration. It might not be an issue for here.

No prob, you can submit a new ticket with the details you have so far, if it is reproducible on our end, we can try to help and have a look too.
