### ISSUE TITLE
[question] Why does the order matter

### ISSUE THREAD

**Issue by fliiiix** [conan-io/conan#15644]
### What is your question?

Why does `find_package` only work after declaring a project?

```
...
find_package(Crow REQUIRED)
project(radiopi)
...
```

This fails ->

```
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
-- Found LibVLC include-dir path: /usr/include
-- Found LibVLC library path:/usr/lib64/libvlc.so
-- Found LibVLCcore library path:/usr/lib64/libvlccore.so
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "FindCrow.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Crow", but
  CMake did not find one.

  Could not find a package configuration file provided by "Crow" with any of
  the following names:

    CrowConfig.cmake
    crow-config.cmake

  Add the installation prefix of "Crow" to CMAKE_PREFIX_PATH or set
  "Crow_DIR" to a directory containing one of the above files.  If "Crow"
  provides a separate development package or SDK, be sure it has been
  installed.
```

While this one works fine

```
...
project(radiopi)
find_package(Crow REQUIRED)
...
```

Maybe thats just a stupid question and i don't understand how cmake works?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fliiiix 

Thanks for your question.

This question doesn't seem really related to Conan, but this is pure CMake question.

Basically just a very few things can be done before ``project()`` call, like ``cmake_minimum_required`` and some toolchain-related things. But otherwise, most of the ``CMakeLists.txt`` content should be after the ``project()`` definition.

**Comment by fliiiix** [comment]
The reason i guess why im having this question in the first place is that i don't see that restriction in the https://cmake.org/cmake/help/latest/command/find_package.html docs of cmake and my FindPKG for the systems libraries works fine before and after the project. Something like this:

```
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")
find_package(LIBVLC REQUIRED)
```

which leaves me to believe that this requirement has something to do with how conan handles cmake

**Comment by memsharded** [comment]
The official CMake docs: https://cmake.org/cmake/help/v3.20/command/project.html#usage says that ``project()`` must be first thing, just after ``cmake_minimum_required()``

> It is important to establish version and policy settings before invoking other commands whose behavior they may affect. See also policy [CMP0000](https://cmake.org/cmake/help/v3.20/policy/CMP0000.html#policy:CMP0000).

It can also be seen more explicitly said by maintainers in support forum, see https://gitlab.kitware.com/cmake/cmake/-/issues/22027

> Re-order your `CMakeLists.txt` file to call `project()` just after `cmake_minimum_required` and before everything else

**Comment by fliiiix** [comment]
Fair enough, so it is a stupid questions thanks :+1:  

> Either way, CMake's error message here could use some improvement.

I think that is still true :D I might open an other cmake bug after testing that with the newest cmake version

**Comment by memsharded** [comment]
> Fair enough, so it is a stupid questions thanks 👍

No, no questions are ever stupid! Do not hesitate to open new tickets to ask any further question that you might have 🙂
