### ISSUE TITLE
[question] Accessing package options in test_package

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15643]
### What is your question?

For Conan v1 the following worked in test_package:
```python
    def test(self):
        if self.options["pkg"].an_option:
            ...
```
This no longer works for Conan v2:
```
ERROR: pkg/1.0 (test package): Error in test() method, line 32
        if self.options["pkg"].an_option:
        ConanException: option 'an_option' doesn't exist
Possible options are []
```
Why?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi! Thanks for your question. The syntax you are looking for is `self.dependencies["mydep"].options.my_option` :)

**Comment by db4** [comment]
Got it, thanks!
