### ISSUE TITLE
Add RelWithDebInfo as a supported build_type

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1564]
`RelWithDebInfo` is a standard build type when using CMake, and I always have to add it to `conan.conf`.

It would be nice for it to be a recognized `build_type` by default.

**Comment by memsharded** [comment]
You mean, you have to add it to ``settings.yml``? Not ``conan.conf``?

The thing is that those settings defaults are the one that make sense for most conan public repository usage. Each company and teams are expected to use their own. For most people, it doesn't make a lot of sense to generate packages for ``RelWithDebInfo``, because actually they don't debug their dependencies from downstream. And linking ``RelWithDebInfo`` from consumer packages/projects, with ``Release`` packages seems to work well.

Probably what you might be interested in is in some easy way to synchronize and share ``settings.yml`` between machines and teams. This is something that we are considering how to add as a conan feature, so teams can easily share settings, remotes, and configuration in general.

**Comment by tamboril** [comment]
Yes.  I meant `settings.yml`.  Not a big deal.  I hadn't considered public repositories.

Thanks

**Comment by tamboril** [comment]
But yes, it's a minor annoyance that things that work for me don't work for my colleagues because I had set some default in a hidden file a long time ago, or they updated versions past mine.  Its' fine if you know what you're doing, but it would be good if I could make it easier for everyone to consistently succeed at installing a package.

**Comment by memsharded** [comment]
Ok, we will keep conversation about this sharing and configuration of settings in: https://github.com/conan-io/conan/issues/1463. It is not exactly that, but it is the closest issue to it, and with some overlap, so lets follow from there. Thanks!

**Comment by tamboril** [comment]
I noticed the main issue I was having with this is that the latest update _removed_ `RelWithDebInfo` from my `settings.yml`, which was unexpected.

**Comment by lasote** [comment]
That's strange. In the latest version, we are not migrating the settings.yml file.

**Comment by tamboril** [comment]
It would seem that you are.  I did a test:
```
[jharris@jharris2 ~]$ (cat ~/.conan/version.txt ; echo)
0.21.1
[jharris@jharris2 ~]$ tail ~/.conan/settings.yml
        runtime: [MD, MT, MTd, MDd]
        version: ["8", "9", "10", "11", "12", "14", "15"]
    clang:
        version: ["3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9"]
        libcxx: [libstdc++, libstdc++11, libc++]
    apple-clang:
        version: ["5.0", "5.1", "6.0", "6.1", "7.0", "7.3", "8.0"]
        libcxx: [libstdc++, libc++]

build_type: [None, Debug, Release, RelWithDebInfo]
[jharris@jharris2 ~]$ conan search
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: A new settings.yml has been defined
WARN: Your old settings.yml has been backup'd to: /home/jharris/.conan/settings.yml.backup
WARN: ****************************************
WARN: Migration: Moving default settings from conan.conf file to default
WARN: Migration: export_source cache new layout
WARN: Migration: Removing package with old export_sources layout: MoneyCore/9999.00.000/devsvc/release
Existing package recipes:

Boost/1.61@boost/external
Catch/1.8.2@philsquared/external
Cmake/3.7.1@kitware/external
LocalGcc/6.1@gnu/external
cpp-hocon/0.1.5@puppetlabs/external
json/2.0.6@nlohmann/external
leatherman/0.11.1@puppetlabs/external
onload/201606-u1.2@solarflare/external
spdlog/0.13.0@gabime/external
[jharris@jharris2 ~]$ (cat ~/.conan/version.txt ; echo)
0.25.1
[jharris@jharris2 ~]$ tail ~/.conan/settings.yml
        runtime: [MD, MT, MTd, MDd]
        version: ["8", "9", "10", "11", "12", "14", "15"]
    clang:
        version: ["3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "4.0"]
        libcxx: [libstdc++, libstdc++11, libc++]
    apple-clang:
        version: ["5.0", "5.1", "6.0", "6.1", "7.0", "7.3", "8.0", "8.1"]
        libcxx: [libstdc++, libc++]

build_type: [None, Debug, Release]
```
