### ISSUE TITLE
[question] How to activate the build environment from `self.run()`

### ISSUE THREAD

**Issue by elvisdukaj** [conan-io/conan#15656]
### What is your question?

I am experimenting with Conan and Android Studio and how make them work together.

I've created a Conan gradle pluging getting inspiration from [conan doc](https://docs.conan.io/2/examples/cross_build/android/android_studio.html#examples-cross-build-android-studio), [ppetraki](https://gist.github.com/ppetraki)/[!conan-gradle-multiarch-build](https://gist.github.com/ppetraki/ca8630cc272edcd6a881ed82aa30b559). Now I am finally able to build C++ packages from Android Studio, with the nice bonus that I adapted my recipe to use the NDK specified during the build.

In the effort to keep the build system as much self-contained as possible, I hit the issue that running gradle from the command line gives you an error the environment `JAVA_HOME` is not defined.

Now I wanted the build environment doesn't depend from the version of Java. One solution that came to my mind was just to create a conan recipe that requires openjdk as tool (or any company distribution) and then just calls gradle from the build function.

```Python
from conan import ConanFile

class buildGradleRecipe(ConanFile):
    settings = "build_type",

    def tool_requirements(self):
        self.tool_requires("zulu-openjdk/21.0.1")

    def build(self):
        if self.settings.build_type == "Debug":
            self.run("gradlew assembleDebug", scope="build", shell="True")
        if self.settings.build_type == "Release":
            self.run("gradlew installRelease", scope="build", shell="True")
```

The solution here is not really great because `gradle` have many different tasks and I am not sure how I can pass an arbitrary task to gradle yet. Maybe I could use a generic option `variant` where I can set any arbitrary value and change the build function to: `self.run(f"gradlew {self.options.variant}", scope="build", shell="True")`, but I don't know if it's possible to pass an arbitrary value to an options. As alternative I can provide the most common tasks.

But if I call `conan build . -of=build_env -s build_type=Debug`, I get the same error of the missing `JAVA_HOME` environment that should be there from `zulu-openjdk`.

I am even not sure this is the smartest path for achieving this problem and I am in the beginning of exploring `conan`.

TLTR: How can I use with conan some tools that are affecting the environment variable (i.e. JAVA, Android NDK, ...) and use the `self.run()` command inside the `build()` with the active environment?

The documentation of `self.run` is almost non-existing.

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @elvisdukaj 

Thanks for your question.

The injection of ``conanbuild`` environment scripts is automatic, so that should mostly work if you are in Conan 2.0. Is this the case?

Then ``tool_requirements()`` is not a Conan method, it is called ``build_requirements()`` (because it would typically be used both for tool-requires and test-requires). It is likely that the tool-require dependency is not being pulled at all, so this is why it is failing. 
Maybe you can provide a full output? that would help to understand the issue.

**Comment by elvisdukaj** [comment]
HI @memsharded ,

Yes I confused the methods name! Using `build_requirements` does the job! Thank you for the help! I can mark this as solved!

**Comment by elvisdukaj** [comment]
I will close this as I was confusing the name of the function in the `conanfile.py`. Using the right method it works!

**Comment by memsharded** [comment]
Thanks for following up!
