### ISSUE TITLE
[bug] Can't set GLOBAL visibility for imported targets 

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#15662]
### Environment details

* Operating System+version:
* Compiler+version:
* Conan version: 2.0.17
* Python version:

### Steps to reproduce

1. Make a simple CMake project with one subdirectory (two CMakeLists.txt files).
2. The outer one should do `add_subdirectory()` on the lower one.
3. Do `find_package(<package_name> GLOBAL)` in the inner CMake file
4. Try to use the imported target in the outer CMake file

_At least CMake 3.24 is needed. More details in https://cmake.org/cmake/help/latest/command/find_package.html#basic-signature._

**Comment by jcar87** [comment]
Hi @mpusz - thank you for reporting this.

Will investigate, as my understanding from reading the CMake documentation is that this should work transparently and that it doesn't need anything specific in the generated files by the `CMakeDeps` generator.

**Comment by mpusz** [comment]
Right! It should be the case. But Conan generates different target types and more of them than the regular CMake installation process. It might be an issue.

BTW, recently I generated the graph with `cmake --graphviz` and was quite surprised to see so many Conan-generated targets there for each dependency.

**Comment by memsharded** [comment]
The generation of targets has completely changed with the new "incubating feature" CMakeDeps: https://docs.conan.io/2/incubating.html

As the previous CMakeDeps will likely not be getting changes anymore as they are a bit risky, it would be great to target this to the new incubating CMakeDeps.
I am closing this ticket as resolved by the incubating CMakeDeps, as it creates targets exactly as CMake ``xxx-config.cmake`` does, so this would no longer be a Conan issue. 

Please create new tickets for any further question or issue regarding the new generator, thanks for the feedback.
