### ISSUE TITLE
Is there a way to fetch package info for the whole conan repository in a single request?

### ISSUE THREAD

**Issue by malonsorightware** [conan-io/conan#15668]
### What is your question?

Hi, we are developing a GUI client to list and install Conan packages. The user should be able to identify each package's type quickly. The package type is determined by the set of "topics" declared in the conan file (conanfile.py). The only way we can fetch the package's topics in Conan2 is by running `conan graph info` on each one of the packages.  This operation may drag the performance of the entire UI down, depending on each package's dependency tree depth. 

We´ve considered a separate working thread that pulls the graph info of each one of the packages of the repository in order to cache them in memory, but I am afraid that the whole idea can take a severe bite on the memory usage and it may be quite slow. 

My question is: is there any way to fetch the information we need for all packages in a repository in a single request?, if there is not such a feature, does it sounds reasonable to implement it?

Thank you very much.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @malonsorightware 

Do you know that https://github.com/markfinal/cruiz by @markfinal exists and is open source? Maybe it would be better to join forces and collaborate.

> My question is: is there any way to fetch the information we need for all packages in a repository in a single request?, if there is not such a feature, does it sounds reasonable to implement it?

I am afraid not such a feature exist.
If you mean all packages are all binaries for all revisions for all versions for all recipes, we are talking about hundreds of thousands of packages in ConanCenter for example? Retrieving the information for each one will take hours, even if there was a single endpoint to request it. 

Also, talking specifically about the package-type, this is an "evaluated" property of the recipes to build them. Binary packages can have an ``options.shared=True``, but they no longer store the package-type. So the only way to obtain package types is to deduce them from a dependency graph. The exact same recipe will be ``shared-library`` or ``static-library`` depending on its consumers and which options do they use.

**Comment by malonsorightware** [comment]
Thanks for the answer. I have not had the chance to check cruiz, but I am working on an embedded solution, not a standalone one, FYI. Regarding the original question, since the topics are attributes for the conanfile, would be reasonable to retrieve the info that "conan inspect" offers  from all packages in a repository?. Conan 1.x `conan inspect `worked pretty well, but then again you would have to run the command per recipe.

**Comment by memsharded** [comment]
> Thanks for the answer. I do not know what cruiz is, but I am working on an embedded solution, not a standalone one. Regarding the original question, since the topics are attributes for the conanfile, would be reasonable to retrieve the info that "conan inspect" offers from all packages in a repository?. Conan 1.x conan inspect worked pretty well, but then again you would have to run the command per recipe.

``conan inspect`` is loading Python files. This cannot be evaluated server side for security reasons.
So it would be necessary to download all recipes for all versions, then ``conan inspect`` them locally. That can take hours too for a large repo, not planned.
If you are working from ConanCenter packages, then the best is to use the ``conan-center-index`` repo and parse the files there, that would be doable.

**Comment by memsharded** [comment]
Closing this question as responded, to summarize:
- There is no way to fetch a whole repository in a single request, this can be huge and take very long time (hours), but would most likely timeout.
- Getting the information one by one would also be a very slow task, this is not recommended and would be strongly discouraged. The recommendation is to use ``conan-center-index`` repo, and if desired, to use the new ``local-recipes-index`` feature, to process it: https://docs.conan.io/2/devops/devops_local_recipes_index.html
