### ISSUE TITLE
[bug] self.info.settings not available in source()

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#15666]
### Environment details

* Operating System+version: Linux Ubuntu
* Compiler+version: gcc11
* Conan version: 2.0.17
* Python version: 3.8.10

### Steps to reproduce

I'm working on a recipe that has a large source download.
The source retrieved depends on the OS.  I know it isn't recommended to switch at source(), but at least during the development phase, I want to switch.

in source() I write `if self.info.settings.os == "MacOS"`,
this works when using `conan create`,
but if I do `conan install .` and `conan source .` it will fail (self.info is set to None)

There are docs that mention `platform.system()`, and that would probably work as long as there is no cross-compiling (that isn't desired for me), so is that the correct approach?

Note that I also need self.info.settings.arch

And, self.info.settings.compiler as it changes some parts of the environment during the source-fetch.
I saw it is instead recommended to fetch the source during build(), which makes sense as the compiler may change.

However, this is for the v8 (javascript engine) recipe, which has a complex way of retrieving the sources.  It takes quite some time to retrieve the source, so it is desirable to do it this other way (for now).

So the chief question is, why I can build with conan-create but I can't use the conan-install + conan-source workflow. Which seems wrong/inconsistent.

**Comment by memsharded** [comment]
Hi @paulharris 

Thanks for your report.

This is known and documented behavior, by design, please have a look to: https://docs.conan.io/2/reference/conanfile/methods/source.html#source-caching

The fact that it might be made available in ``conan create`` looks like a "leak", but not really intended.
I am trying to reproduce, but it still raises:
```python
def source(self):
        self.settings.os
```
Then
```bash
$ conan create .
...
pkg/0.1: Calling source() in...
ERROR: pkg/0.1: Error in source() method, line 26
        self.settings.os
        ConanException: 'self.settings' access in 'source()' method is forbidden
```

Can you please double check? I am not sure why your ``conan create`` is not raising such exception.

**Comment by memsharded** [comment]
> However, this is for the v8 (javascript engine) recipe, which has a complex way of retrieving the sources. It takes quite some time to retrieve the source, so it is desirable to do it this other way (for now).

For the heavy case that downloading from ``build()`` is to be avoided, then the check ``if platform.system() == "Windows":`` might be doable, as long as you know that you will not be doing things like cross-building with that recipe.

**Comment by paulharris** [comment]
Your test missed the "info" bit
```
def source(self):
        self.settings.os   ---> self.info.settings.os
```

The `platform.system()` approach also doesn't work, as there is also a switch related to which compiler is being used.  It relates to the build environment it sets up for itself (involves msys and other things).
For now I'll use conan-create only, and rely on the leakage.

In future either there'll need to be a fair amount of magic to get it to work in the pure conan build env, 
or perhaps more sensibly, put these platform/compiler questions as options to the recipe.  So if cross compiling, the appropriate options can be set by the user, and multiple builds will work.   Just a bit more manual for the consumer.

I'll leave this open until you confirm the leakage.
Would be nice if conan were changed so there was an 'escape hatch' to get this info (unlikely),
or at least a better error message to briefly explain, something like,

settings.info isn't available in source(), because the same source() will be used for multiple platforms and compilers.
Thus, whatever source() does should be identical across any compiler/platform configuration, and should not depend on settings.info.
If you need to know during source deployment, either download the source in the build() step (when the exact platform/compiler is known), or, require the consumer to specify the desired information via recipe options.

**Comment by memsharded** [comment]
> I'll leave this open until you confirm the leakage.

Yes, I confirm the leakage, ``source()`` method is not expected to receive or allow the ``self.info`` at any time, and it can and it will most likely will remove it in the future, producing a clear error message that the ``info`` is not allowed in this method.

What you might want to "abuse" for your use case is the ``generate()`` method that runs before ``source()``, has access to settings and to the source folder. It is a bit of abuse and not intended, but I think at least it allows you to do that with less risk of future breaking.

I'd say that the most idiomatic solution would be something in the line:
- Download the platform-specific code in the ``build()`` method
- Use a ``user.myteam:skip_download`` or similar ``conf`` in the recipe to be able to opt-out the repeated download of the source in the ``build()`` method.

Also, in many cases, this shouldn't be an issue, as in local development running ``conan build`` repeatedly should be less frequent that running it one time, then just running the generate project or running ``cmake ...`` to build, without needing to call ``conan build`` all the time.

I am labeling this as a question, not a bug, as the ``source()`` documents the correct behavior, and it is mostly a leakage, so it could be considered a UX improvement (when an error message is clearly raised if ``info`` is used), not a bug.

**Comment by paulharris** [comment]
Ok thanks, I'll aim for the build() approach.

**Comment by sykhro** [comment]
I had the recipe set up like this:
```python

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

        if self.options.get_safe("with_embedded_rpmalloc"):
            git = Git(self)
            git.clone(
                "https://github.com/mjansson/rpmalloc",
                target=Path(self.source_path).joinpath("rpmalloc").resolve().as_posix(),
                args=["--depth", "1", "--branch", "1.4.5"],
            )

```
just wondering, is there anything I can do to avoid paying the cloning tax when that option is disabled? do I have to make a package for rpmalloc?

**Comment by memsharded** [comment]
Hi @sykhro 

If you move the ``self.options...`` part to the ``build()`` method, you will still have the common part of the ``get()`` common to all builds, only pay once, and then you will need to pay for each build for the clone of that repo for the option, yes. There is no "caching of sources for every different possible combinations of options/settings".

Making a common package for ``rpmalloc`` might indeed avoid the issue (but it is always a balance, depending on your usage and needs, might be overkill, if only that package uses the code of ``rpmalloc``.
