### ISSUE TITLE
[feature] Have `trim_conandata` not throw when there's no `conandata.yml`

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#15672]
### What is your suggestion?

`trim_conandata` can be used inside a `post_export` hook instead of the `export()` method in recipes, but then we have no control over wether a recipe has an associated `conandata.yml`.

The fix is easy, just `try: ... catch:` it, but feels a bit dirty.
Ideally that could be skipped, but it's true that when used in the `export` method, it might be desirable to have it raise, so we need to give it a thought

Reproducing this is easy: Have a simple recipe without a `conandata.yml` and a `post_export` hook that simply calls `trim_conandata`. That is, this test should pass, which currently does not:

```py
def test_trim_conandata_as_hook_without_conandata():
    c = TestClient()
    c.save_home({"extensions/hooks/hook_trim.py": textwrap.dedent("""
    from conan.tools.files import trim_conandata

    def post_export(conanfile):
        trim_conandata(conanfile)
    """)})

    c.save({"conanfile.py": GenConanfile("pkg")})
    c.run("export . --version=1.0")
    assert c.exported_recipe_revision() == "a9ec2e5fbb166568d4670a9cd1ef4b26"
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Ideally, I'd like the `trim_conandata` function to raise when it's not executing on a hook context, but keep raising if it was call elsewhere, as that is something the user will have control over on a recipe basis

/cc @memsharded wdyt?

**Comment by jcar87** [comment]
My suggestion is `def trim_conandata(conanfile, raise_if_missing=True)` (a `True` default value to behave exactly as it does now)

* And implement the hook as:
```
    def post_export(conanfile, raise_if_missing=False):
        trim_conandata(conanfile)
```

If called from a recipe, these have control over: the argument passed, and whether conandata.yml exists.

**Comment by memsharded** [comment]
> Ideally, I'd like the trim_conandata function to raise when it's not executing on a hook context,

Not sure what you mean. I think recipes should call this explicitly, to be self-contained and not depend on a hook to do the right thing. Being a multi-version recipe is something that is specific to the recipe, so I'd like it to be part of the recipe by default. The hook approach is necessary because it will take a lot of time to get there.
