### ISSUE TITLE
[question] How to list outdated dependencies?

### ISSUE THREAD

**Issue by stevenwdv** [conan-io/conan#15688]
### What is your question?

How do I list outdated dependencies required by my recipe? Similar to `npm outdated` for npm.js.
It seems like this is a feature that should exist but search engines and documentation leave me empty-handed.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
There is no direct command to list outdated dependencies. The ``--update`` can update the dependencies that can be updated (within the defined ranges), but there is nothing built-in to list new versions of current dependencies. 
It should be pretty easy to do with a custom command though, mostly a graph-info, then a ``list`` for each one. This might also be considered as a built-in subcommand too, it would make sense to have it too.

**Comment by memsharded** [comment]
Conan 2.2 has merged https://github.com/conan-io/conan/pull/15838 that implements the ``conan graph outdated`` command for this purpose.
