### ISSUE TITLE
[question] Why do conan create options propagate to test_package?

### ISSUE THREAD

**Issue by KingKiller100** [conan-io/conan#15687]
OS: Windows 11 Pro 22H2
Conan version: 1.55.0 - 1.63.0

Hi, I noticed some weird behaviour when running conan create on a newly generated conan project. If there is a recipe that supports options and I call `conan create` and define a value for the option, the build fails. If I remove the definition for the option on the `conan create` command, the build works. The error reported is saying that the test_package does not have the option stated inside of its recipe. 

This seems odd since conan create is designed to build the package using the values stated for the options and then the test_package should run using the package generated from those options implicitly. I shouldn't need to duplicate the options within the test_package's recipe, right? I have other projects that use test_package and do not have this issue. 

Any ideas as to what I was doing wrong?

To reproduce this issue, I performed the following steps.

1. Created a new project space from the msbuild exe template using `conan new -m msbuild_exe hl/1.0`. 
2. Edited the newly generated recipe to support a new option. The recipe is as follows:

  ```python
import os

from conan import ConanFile
from conan.tools.microsoft import MSBuildToolchain, MSBuild, vs_layout
from conan.tools.files import copy


class Conan(ConanFile):
    name = "hl"
    version = "1.0"
    options = {"cheats":["on", "off"]}
    default_options = {"cheats":"off"}
    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "hl.sln", "hl.vcxproj", "src/*"

    def layout(self):
        vs_layout(self)

    def generate(self):
        tc = MSBuildToolchain(self)
        tc.generate()

    def build(self):
        msbuild = MSBuild(self)
        msbuild.build("hl.sln")

    def package(self):
        copy(self, "*hl.exe", src=self.build_folder,
             dst=os.path.join(self.package_folder, "bin"), keep_path=False)
  ```

3. `conan create -pr msvc.profile -o cheats=on .` using the following profile:
  ```txt
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=static
compiler.runtime_type=Release
compiler.toolset=v141_xp
compiler.version=191
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_DISABLE_STRICT_MODE=1
[conf]
tools.microsoft.msbuild:verbosity=Normal
   ```
4. The following error msg should appear:
```bash
ERROR: D:\scm\git\Fw\Conan\conan-generators\tmp\test_package\conanfile.py: option 'cheats' doesn't exist
Possible options are []
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @KingKiller100 

Thanks for your question.
This is a known issue in Conan 1.X. It can be solved by explicitly dissambiguating the scope of the option:

```
conan create . -pr msvc.profile -o hl:cheats=on
```

It works fine with ``-o cheats=on`` in Conan 2 already

**Comment by KingKiller100** [comment]
Thanks for the swift reply, @memsharded,

Oh interesting, would it be possible to add the fix to the conan 1.x series too? My company want to move to 2.x in future but we need to make some changes to our build servers and workflow to be able to support it so we can't upgrade at this time.

If not, are there other ways to have `conan create -pr msvc.profile -o cheats=on .` work for 1.x series? For example, adding something within the main project or test_package's recipe's?

**Comment by memsharded** [comment]
> Thanks for the swift reply, @memsharded,

No prob, glad to help

> Oh interesting, would it be possible to add the fix to the conan 1.x series too? My company want to move to 2.x in future but we need to make some changes to our build servers and workflow to be able to support it so we can't upgrade at this time.

I am afraid not, Conan 2 was launched already 1 year ago (it was in beta 2.5 years), so we are not backporting this kind of thing anymore, we don't have enough resources. But also, in this case, this wasn't fixed in 1.X back then because it was quite challenging to do it without breaking (yet another thing that had to wait to Conan 2 to be fixed, because of high breaking risk in 1.X)

> If not, are there other ways to have conan create -pr msvc.profile -o cheats=on . work for 1.x series? For example, adding something within the main project or test_package's recipe's?

You can skip the test first, then execute the test_package separately:
```
conan create . -o cheat=True -tf=None
conan test test_package pkg/0.1@
```
But I think the ``-o pkg:cheat=True`` will be easier than that.

**Comment by KingKiller100** [comment]
> I am afraid not, Conan 2 was launched already 1 year ago (it was in beta 2.5 years), so we are not backporting this kind of thing anymore, we don't have enough resources. But also, in this case, this wasn't fixed in 1.X back then because it was quite challenging to do it without breaking (yet another thing that had to wait to Conan 2 to be fixed, because of high breaking risk in 1.X)

Oh dear, that's sad to hear but understandable. We'll do what we can with 1.x series until we can move. 

This is a little off topic but when does your team plan to end all support for the 1.x series?

> You can skip the test first, then execute the test_package separately:

Funnily enough, this was my original solution to this problem but I wanted to track down the reason for why this wasn't working all of a sudden. Plus I prefer having the one cmd perform all the steps I need to build and test my package before releasing to consumers

**Comment by memsharded** [comment]
> This is a little off topic but when does your team plan to end all support for the 1.x series?

Depending what you mean by support :) We plan to keep responding questions, trying to help, and doing some releases like the recent 1.63 with bugfixes and some small features, specially if necessary to help in the migration to Conan 2.0. But development of new features in 1.X has already been very slowed down in the last 6 months at least, just check https://docs.conan.io/1/changelog.html.

We also plan to freeze support in ConanCenter in the following months, meaning that nothing will break, but Conan 1.X will no longer process updates or fixes to recipes in ConanCenter, with the recipes and binaries being frozen to not breaking, but not evolving anymore. 


> Funnily enough, this was my original solution to this problem but I wanted to track down the reason for why this wasn't working all of a sudden. Plus I prefer having the one cmd perform all the steps I need to build and test my package before releasing to consumers

But I don't think this is a new thing in recent 1.X releases, this should have been this way for a long time already in 1.X

**Comment by KingKiller100** [comment]
> Depending what you mean by support :) We plan to keep responding questions, trying to help, and doing some releases like the recent 1.63 with bugfixes and some small features, specially if necessary to help in the migration to Conan 2.0. But development of new features in 1.X has already been very slowed down in the last 6 months at least, just check https://docs.conan.io/1/changelog.html.

Great! I've been trying to make our recipes more conan 2.0 compatible nowadays so this will be very helpful for those stuck on the 1.x series for now.

> We also plan to freeze support in ConanCenter in the following months, meaning that nothing will break, but Conan 1.X will no longer process updates or fixes to recipes in ConanCenter, with the recipes and binaries being frozen to not breaking, but not evolving anymore.

After that cut-off, Conan 1.x's ConanCenter won't have any new packages added anymore, but Conan 2.x ConanCenter will?

>  But I don't think this is a new thing in recent 1.X releases, this should have been this way for a long time already in 1.X

Ah, you are correct. I tested another package that had options and test_package and tried to perform a create with & without defining an option. The same error occurs. I must have performed creates without stating an option before

**Comment by memsharded** [comment]
> After that cut-off, Conan 1.x's ConanCenter won't have any new packages added anymore, but Conan 2.x ConanCenter will?

Yes, that is the idea, but not only new packages, but also new versions and new revisions (changes or fixes to existing versions).

**Comment by KingKiller100** [comment]
Cheers for the information! Thank you
