### ISSUE TITLE
[question] Use CMake PUBLIC linked library with editable mode

### ISSUE THREAD

**Issue by johannes-wolf** [conan-io/conan#15691]
### What is your question?

I want to use my package in editable mode.
The package has one (header only) dependency that it also uses in it's public headers. Everything works when using `conan create .`, but if I try using `conan editable add .` and then
consuming the package, the consumer does not know about the sub-package it also has to include.

Is there an option to inject dependencies to consumers (from the `package_info()` function maybe)?

Thank you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @johannes-wolf 

Thanks for your question.

I am not sure it is an issue of the editable, but the definition of the requirement. If the included headers are included in public headers of your package, the correct definition is ``self.requires("mydep/1.0", transitive_headers=True)``. Maybe you are missing it?

If not, if you could please provide something we can reproduce, like a couple of minimal recipes and the exact commands you are using, that would help a lot. Thanks!

**Comment by johannes-wolf** [comment]
> transitive_headers

Exactly what I was looking for, thank you! I was missing the `transitive_headers=True`.

**Comment by memsharded** [comment]
Good! Then it is working now, maybe we can close the issue? Thanks!
