### ISSUE TITLE
[question] How to work with additional recipe data files? eg for requirements()

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#15698]
### What is your question?

I'm sure I asked this or saw an answer in the past, but I cannot find it.

I want to load and process a JSON file during the config_options() and requirements() method, as well as many other methods like generate() and build().

I'm not sure how...

take `requirements()` for example.
It has self.recipe_folder but it refers to the folder /e/ in the cache.
It has NO other folders available that I could see.  EG self.source_folder is None (understandable - a package deploy wouldn't have source).
`export_sources()` copies it to the /es/ folder, but requirements() doesn't have a way to find that path.

So, how do I get my file out of the real recipe folder and into a place in the cache that requirements() can load?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @paulharris 

Thanks for your question:

- Extra files that are parsed and used by the recipe are ``exports``. They need to be exported with ``exports = `` or ``export()`` method.
- They will be located together with the recipe. So current dir or ``self.recipe_folder`` should work. That folder should contain the exported files too.

Follow the ``conandata.yml`` location, it is the same use case (in fact, you can also use that ``conandata.yml``, add your info there, and benefit this file is both automatically exported and automatically loaded into ``self.conan_data``

**Comment by paulharris** [comment]
Ok great, thanks!  Would be great if this were added to the cmake package template.  Not sure if you think that template is already too busy?

I had thought `export()` was related to some packaging thing, so I didn't dive deeper into that part of the docs.

As for conandata.yml, it won't be the right place for this data.  Its an 8K json file, and this recipe may need a different one for each version.
