### ISSUE TITLE
download caching and avoiding a single point of failure

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#157]
The current APIs work, but they do things backwards. A strong hash code is the best identifier for a file, not an HTTP URI.

``` Python
download("http://www.sfml-dev.org/files/%s" % zip_name, zip_name)
check_sha256(zip_name, "03fe79943c48222037f1126a581b12c95a4dd53168881907964695c5ec3dc395")
```

An API like the following could cache the file somewhere in `.conan` or use a distributed file transfer protocol like IPFS and ignore the HTTP server entirely.

``` Python
retrieve(
  sha256: "03fe79943c48222037f1126a581b12c95a4dd53168881907964695c5ec3dc395",
  locations: ["http://www.sfml-dev.org/files/%s" % zip_name],
  save_as: zip_name
)
```

Benefits:
- `build.py` downloads the source code at most one time instead of N times where N is the number of tested configurations
- alternative download protocols are possible instead of an HTTP single point of failure
  - for example, the Conan server could cache source code in case the original server is unavailable (GitHub is known to be very unreliable)
- encourages hash checks by making `retrieve` the default recommended API, which is beneficial to security and safety

Does this make sense to you?

**Comment by lasote** [comment]
Hi @TyRoXx 

The sources should be downloaded once even for multiple build configurations. If don't, please report it.
My opinion is that a cache introduce ** a lot ** of complexity to any system (we had it in biicode), is it really a problem to wait for a zip download nowadays? I think its a overkill feature.

So, for me it has not sense. @memsharded what do you think?
Anyway, always a pleasure to hear your ideas @TyRoXx

**Comment by TyRoXx** [comment]
You are right. The source is not downloaded again if the conanfile stays the same. That means there is in fact already a source caching mechanism in Conan. It just happens to be on the wrong layer.

Yes, it is a problem. The download does not only waste time which is very expensive, but is also likely to break at some point because the server disappears or is temporarily unavailable. The latter is even more expensive if it happens.
My personal blockers regarding source retrieval at the moment are:
- Unnecessary download after every little change of the conanfile. My workaround is to modify the conanfile.py to replace the download with a ``cp`` from a local copy. This is error-prone and a waste of time and I will forget to remove the workaround half of the time before ``conan upload``.
- Unnecessary download from the WAN even if the source has been downloaded already to the LAN of my organization. This is especially unacceptable in CI scenarios. Example: Third party Conan library A depends on my library B. For every commit in B I want to check that A will still work with the latest B. Why do I have to download the same source code for A again and again?
- Builds are not reproducible because servers go away all the time. Absolute dealbreaker for (competent) professional use of Conan.

I agree that cache invalidation is hard in general, but Conan should have the necessary information to decide what to keep around. Example for a solution: Package binaries that were built locally keep their source archives alive by incrementing a reference counter per hash code and copying the archive to a package-independent location. ``conan remove`` would decrement the counters for the affected source archives. For consistency, there would have to be a simple garbage collector, too. This would solve the first of my blockers mentioned.

**Comment by lasote** [comment]
I think with the local development flow introduced and improved in Conan 1.X and as this issue has not been gained support for the community I'm closing it. Anyone, feel free to comment and I will open it again if needed.
