### ISSUE TITLE
Conan search syntax not quite working as docs show

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1570]
This page indicates you should be able to use conan search with with an unquoted string of the exact package name, but in my test below it fails.  If i surround the package name with asterisks, it works.  Either it's a recent bug, or perhaps a windows-specific issue, or the doc was wrong and it always needed asterisks.  

http://conanio.readthedocs.io/en/latest/reference/commands/search.html

```
C:\Users\jerry>conan search *Boost/1.64.0*
Existing package recipes:

Boost/1.64.0@lasote/stable
conan_boost/1.64.0@dario-ramos/stable

C:\Users\jerry>conan search *Boost/1.64.0@lasote/stable*
Existing package recipes:

Boost/1.64.0@lasote/stable

C:\Users\jerry>conan search Boost/1.64.0@lasote/stable
There are no packages for pattern 'Boost/1.64.0@lasote/stable'

C:\Users\jerry>conan search conan_boost/1.64.0@dario-ramos/stable
There are no packages for pattern 'conan_boost/1.64.0@dario-ramos/stable'
```

**Comment by lasote** [comment]
When you search by reference you are searching the binary packages associated with the recipe, in your case it seems that there are no binaries for 'Boost/1.64.0@lasote/stable' nor 'conan_boost/1.64.0@dario-ramos/stable', right? Maybe the message is not clear enough.

**Comment by solvingj** [comment]
In all 4 the commands above, i'm in the root of my profile (no recipe exists there), so it's confusing that I would receive any results at all (even when I use the asterisks).   The commands show that if I search the exact same package name surrounded asterisks, it returns the packages as expected.  If I remove the asterisks (and mimic the example on the docs), it can't find them.  

I would actually expect that the `conan search` command is a global search of my cache and all remotes for packages (not the current recipe).

**Comment by lasote** [comment]
`conan search` is a global search in the local cache or in a remote if specified.
The command can search:

a) Recipes: If a pattern is specified (non valid reference a/b@c/d)
b) binary packages of a recipe: If a reference is specified (a/b@c/d)

If you are using asterisks it is not a reference, so it will look in the local cache for the pattern.
Otherwise will search the binary packages for the specified reference.
