### ISSUE TITLE
[question] How to specify options for tools

### ISSUE THREAD

**Issue by CJCombrink** [conan-io/conan#15709]
### What is your question?

Hi! I created this issue for a problem that I have: https://github.com/conan-io/conan-center-index/issues/22818

Now the question is, how do I get past that issue while the _bug_ exists in a dependency of the tool that I want.

I did try the following:
```
 self.tool_requires("thrift/0.17.0", options={"boost/*:without_cobalt": False})
 ```
Conan does except it, it does not choke, but it also does not seem to work.
PS: I moved to conanfile.py since from my findings the conanfile.txt does not support his

Any help will be appreciated

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @CJCombrink 

Thanks for your question.

I think ``self.tool_requires("thrift/0.17.0", options={"boost/*:without_cobalt": False})`` should work for Conan 2.0, isn't this the case?

It would be great to have something smaller that we can reproduce. Maybe you can try using the ``conan new cmake_lib -d name=mytool -d version=0.1 -d requires=mydep/0.1`` templates, to produce something small that we could check?

Also, as an alternative, you should be able to use ``-o:b boost/*:option=False`` in the command line or the equivalent in the **build** profile ``[options]`` section.

**Comment by paulharris** [comment]
This question was also posted on slack, he tried the tool_requires...options suggestion, it didn't work.

Based on the error message from #22818, I would imagine that gcc10 requires `-fcoroutines` for the gcc compiler.  Maybe he can add the flag to the profile?
And, the boost recipe perhaps needs to add that flag automatically?

One other option is to try gcc13, which perhaps doesn't need that flag.

On this topic, I find it tricky if the user types the wrong option, and conan doesn't complain that the option doesn't exist.
eg perhaps CJ has typed `boost/*:withalt_carbolt` which is wrong... but conan won't tell you it doesn't match anything!

**Comment by CJCombrink** [comment]
@memsharded 

Edit: Sorry I see I inverted the setting, it seems to work as intended

Here are the steps to reproduce
```
~/> conan --version                                                                                                                                                                                     
Conan version 2.1.0
~/my_tool/> mkdir my_tool && cd my_tool
~/my_tool/> conan new cmake_lib -d name=mytool -d version=0.1 -d requires=boost/1.80.0
~/my_tool/> echo '    def build_requirements(self):
        self.tool_requires("thrift/0.17.0", options={"boost/*:without_cobalt": True})' | tee -a conanfile.py
~/my_tool/> conan install conanfile.py --build=missing -of build
```

I used `"boost/*:without_cobalt": False` instead of `"boost/*:without_cobalt": True`

**Comment by CJCombrink** [comment]
@memsharded @paulharris Thank you for the help, even if it was noise

**Comment by memsharded** [comment]
> On this topic, I find it tricky if the user types the wrong option, and conan doesn't complain that the option doesn't exist.
eg perhaps CJ has typed boost/*:withalt_carbolt which is wrong... but conan won't tell you it doesn't match anything!

Yes, but this is necessary. Not even warnings are possible, otherwise using ``-o *:shared=True`` will print multitude of warnings for every header-only package, every application package, etc. If it is pattern-based, it cannot fail or warn if the option doesn't exist. Even options change with different versions of the same library.

**Comment by paulharris** [comment]
> Yes, but this is necessary. Not even warnings are possible, otherwise using `-o *:shared=True` will print multitude of warnings for every header-only package, every application package, etc. If it is pattern-based, it cannot fail or warn if the option doesn't exist. Even options change with different versions of the same library.

I can understand that.
But what if there is no wildcard?  Does `-o package/1.2.3:shared=True` fail if that version has no 'shared' option?

It would be good to tell conan that I really want to be sure this option exists...

If a new version of a package drops an option that I expect, I would prefer the build stops and alerts me.
eg `-o something/*:parallel_with_tbb=True`
if that stops working (and they revert to OpenMP or threads), then I would want to know.
