### ISSUE TITLE
[question] Add an option in config_options()

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#15701]
### What is your question?

In def config_options() there are examples of how to remove an option, eg del self.options.fPIC.   How do I ADD an option?
The logical thing  `self.options["something"] = something` does not work, `object does not support item assignment`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
> In def config_options() there are examples of how to remove an option, eg del self.options.fPIC. How do I ADD an option?
The logical thing self.options["something"] = something does not work, object does not support item assignment.

Options cannot be added dynamically, they can only be removed. It is important to declare them in ``options`` first, to make them easier to discover/inspect them.

**Comment by paulharris** [comment]
That is awkward.  There are lots of options with this recipe, and the options can change each version.
I have an external file that I can parse and load the options.
I could do it in the class setup, ie in the constructor, but I was going to use `self.recipe_folder` (I could assume it is in the current directory?),
and I also wanted to check the target OS, rather than always adding and then removing.

**Comment by memsharded** [comment]
> That is awkward. There are lots of options with this recipe, and the options can change each version.

Are we talking about a ``conan-center-index`` like recipe for third-party? Or for your own recipe for your own internal package?
For the first case, if the recipes diverge too much, the recommendation is to separate them in folders as defined in the ``config.yml`` file.

> I have an external file that I can parse and load the options.

I see. You might use the ``init()`` method, it can be used for dynamic initialization of recipe fields.
Check the docs in https://docs.conan.io/2/reference/conanfile/methods/init.html, which uses the ``options.update()`` method

**Comment by paulharris** [comment]
This is for the giant VTK recipe.
It has been working for me for a year now on Conan 1.  Now it is time to go to Conan 2.
It is building and working with Conan 2, except now it has to become more clever to only require the dependencies that the enabled modules require.

I have almost all the logic done, it should work with a bit more fiddling.
The info of what modules depend on what, and what each needs, is encoded in the VTK source.
It gets dumped to JSON after the build, but I've generated it from source for every possible module.

So I have requires() based on that json file.
Next is to generate the options from that file.  Which is done (untested), if I can populate the options from code.

So I lose the access to self at the point of construction, so I can't use `load(self, filename)`, nor can I check the target OS, but I think those can be dealt with.

I am wondering if I will need self.recipe_folder though.  I won't have that.

Maybe this init() method will work... I'll give it a try.

**Comment by paulharris** [comment]
Hmm I'm not sure init() works.
I did something like
```
options = { "option": True }
def init(self):
   print(self.options)
   extra_options = {"another": True}
   self.options.update(extra_options)
   print(self.options)
```

And the second print didn't show the "another" in the set.

**Comment by paulharris** [comment]
I think I've got it... `self.options.update(extra_options, extra_defaults)`

**Comment by paulharris** [comment]
This is working now, thanks!  Pretty niche...
