### ISSUE TITLE
[feature] CMakeDeps: Support arbitratry component strings

### ISSUE THREAD

**Issue by reddwarf69** [conan-io/conan#15715]
### What is your suggestion?

The experimental check_components_exist property (https://docs.conan.io/2/reference/tools/cmake/cmakedeps.html#check-components-exist) expects the components to be independent libraries.

But there is at least one well known pre-existing example in which the components are just custom strings: https://cmake.org/cmake/help/latest/module/FindCURL.html. curl itself has this information in the pkg-config file (https://github.com/curl/curl/blob/master/libcurl.pc.in#L32) (`pkg-config --variable supported_features libcurl`), and it actually pre-dates even pkg-config by being in curl-config (https://github.com/curl/curl/blob/master/curl-config.in#L44).

Ideally CMakeDeps would allow also such custom strings as components.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @reddwarf69 

Thanks for your suggestion.

I think the ``Find`` modules are no longer recommended by CMake and have been superseded by ``xxx-config.cmake`` Config files. Is there any official ``curl-config.cmake`` files that also defines these features as components?

The https://docs.conan.io/2/reference/tools/cmake/cmakedeps.html#check-components-exist, is optional, not really used, and opt-in. So it shouldn't be an issue for most cases, what is the error that you see with the ``CMakeDeps`` if you define ``COMPONENTS`` to those features in your ``CMakeLists.txt``?

**Comment by reddwarf69** [comment]
> I think the Find modules are no longer recommended by CMake and have been superseded by xxx-config.cmake Config files.

xxx-config.cmake is what upstream itself would generate. Sure, CMake would like every single library to provide a xxx-config.cmake, but when they don't you create a find module.

https://cmake.org/cmake/help/latest/command/find_package.html
"The Find<PackageName>.cmake file is not typically provided by the package itself. Rather, it is normally provided by something external to the package, such as the operating system, CMake itself, or even the project from which the find_package() command was called. Being externally provided, [Find Modules](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules) tend to be heuristic in nature and are susceptible to becoming out-of-date. They typically search for certain libraries, files and other package artifacts."

"The config and version files are typically installed as part of the package, so they tend to be more reliable than Find modules. They usually contain direct knowledge of the package contents, so no searching or heuristics are needed within the config or version files themselves."

The recommendation is to keep trying to use Find modules: "Where possible, user code should generally look for packages using the basic signature, since that allows the package to be found with any mode."

I don't know of any recommendation to use https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html, which is still not the default, and the documentation describes it as something for a corner case scenario.

The support for checking for features and protocols as components in FindCURL.cmake is also relatively modern; it came in CMake 3.14.0, from 14 March 2019. So it's very much actively supported, with a fix as recent as from two months ago: https://gitlab.kitware.com/cmake/cmake/-/commit/ab6b44b1bb88273a7944acf822560386f9a0a082. 


> Is there any official curl-config.cmake files that also defines these features as components?

curl supports a CMake build system that generates a CURLConfig.cmake. But it's newer and, even if started in 2009 (https://github.com/curl/curl/commit/4c5307b45655ba75ab066564afdc0c111a8b9291), it's still incomplete (https://github.com/curl/curl/blob/master/docs/INSTALL-CMAKE.md#current-flaws-in-the-curl-cmake-build).

No, it doesn't support checking for features as components. In fact, if you try to check for any component it will fail since it incorrectly uses CMakePackageConfigHelpers... just another thing broken with it. Being broken, it's unclear what the actual intention is.

Most people use autotools to build curl if they can (Windows users are likely to use CMake since autotools is not that easy to use in Windows), and when using it no CURLConfig.cmake is generated at all and people rely on FindCURL.cmake from CMake.
I include Conan Centre in the group using autotools: https://github.com/conan-io/conan-center-index/blob/master/recipes/libcurl/all/conanfile.py#L135... not that it matters since Conan Centre has the policy of deleting all the xxx-config.cmake files (https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/build_and_package.md#package-method), arguing CMakeDeps can generate them.

Even if you use a curl built with CMake, and CURLConfig.cmake is available, the default when doing `find_package(CURL COMPONENTS XXXX)` is that:
- It will start using FindCURL.cmake from CMake
- Which will redirect itself to CURLConfig.cmake (https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindCURL.cmake?ref_type=heads#L80)
- CURLConfig.cmake will fail, but FindCURL will continue (https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindCURL.cmake?ref_type=heads#L85) and actually check if the components are supported.


> So it shouldn't be an issue for most cases, what is the error that you see with the CMakeDeps if you define COMPONENTS to those features in your CMakeLists.txt?

The CMakeDeps generated files, when using the Conan Centre curl package, will just accept any COMPONENT in find_package() (the opposite of what the broken, official, CURLConfig.cmake file does). It will accept it no matter if the feature is supported or unsupported by the build... or even if it's not the real name of a feature potentially supported by curl, it will just accept any random string as component.

The only error you can get is that you are going to be asking find_package() if the feature is supported, it's going to tell you "yes" even if it isn't... and you are going to be surprised that your program fails to work properly.

**Comment by memsharded** [comment]
The new ``CMakeDeps`` generator has implemented support for components definition and checking in https://github.com/conan-io/conan/pull/17302 for next Conan 2.10 release.

Note this generator is at the moment under a dev-testing feature flag, which is the config ``-c tools.cmake.cmakedeps:new=will_break_next`` that will change at each release to discourage production usage.
Please give it a try when 2.10, looking forward to hearing your feedback. We will use feedback from users to get this feature out of dev-testing stage, as it is a very big one (the new ``CMakeDeps`` generator is completely new, from scratch, fixing many pending issues), it requires some pre-release testing and feedback.

Thanks very much!
