### ISSUE TITLE
[question] settings/profile recomendation for msys2 environments

### ISSUE THREAD

**Issue by jcaselman** [conan-io/conan#15711]
### What is your question?

We're preparing to build out a matrix of conan packages for the msys2 MINGW64, UCRT64, and CLANG64 environments.

Based on https://www.msys2.org/docs/environments/, we can distinguish between these environments using the "C Library" and "C++ Library" based on the table in the link:
`msvcrt` + `libstdc++` = `MINGW64`
`ucrt` + `libstdc++` = `UCRT64`
`ucrt` + `libc++` = `CLANG64`

In our conan profiles we can start to distinguish these by comparing the `compiler.libcxx` setting, but I don't see a default setting where we would distinguish between the C libraries (`ucrt` vs `msvcrt`).

Before we just go ahead and add something, I wanted to check to see if there is an existing pattern for profiles supporting these different environments, and in the case that there are not, what would be recommended?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jcaselman 

Thanks for your question.

Have you had a chance to check this blog post? https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html  (it was written for 1.X, but relatively modern, so most of it should be valid for 2.0)

It is not explicitly covering Mingw, but I think it might help.

There is also the under-used ``os.subsystem: [null, cygwin, msys, msys2, wsl]`` for Windows. It could be extended to add ``ucrt`` if necessary maybe? I think that clang and mingw should be enough modeled by ``libcxx`` and ``runtime``, but ``ucrt`` might not be handled yet.

**Comment by jcaselman** [comment]
Hi @memsharded, I did come across that post but I didn't feel that it covered my case quite well enough based on my understanding.  I'm happy to use `os.subsystem`, that's the direction I was headed before posting.

I do want to understand your suggestion otherwise first though, are you saying that it's appropriate to infer the clang64 or mingw64 environments based on the `clang.compiler.runtime` from the settings:
```runtime: [None, MD, MT, MTd, MDd, static, dynamic]``` ?

**Comment by memsharded** [comment]
> I do want to understand your suggestion otherwise first though, are you saying that it's appropriate to infer the clang64 or mingw64 environments based on the clang.compiler.runtime from the settings:

Yes, if ``runtime`` is not defined, then it is basically a subsystem, not ``msvc`` nor ``clang-cl`` with VS backend. Complementary to ``libcxx`` which would only be defined for ``msys/clang`` and ``msys/mingw``, but not for ``msvc`` based compilers.


Just something to be aware: some of the ``confs`` in Conan, like ``tools.microsoft.bash:path`` are not intended for mingw or clang, but for running some package creating in the msys2 bash, but actually using ``msys2`` subsystem to run autotools builds, using ``msvc`` as the compiler. This is what most of autotools recipes in ConanCenter does.


Another thing to be aware is that recipes in ConanCenter are not tested against mingw/clang in Windows, so while many contributors submit patches for these, quality might vary across different recipes. Support for ``msvc`` compiler should be more robust.

**Comment by jcaselman** [comment]
Thanks for the clarification/tips @memsharded!
