### ISSUE TITLE
[question] Questions for the `conan remote login` command

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#15723]
### What is your question?

We are looking at combining `conan` with JFrog's `artifatory`. The only documented ways I've seen to authenticate `conan` with `artifatory` is the command sequence

```bash
conan remote add <remote-registry-name> <remote-registry-url>
conan remote login <remote-registry-name> <userid> -p <password>
```

Are there any other ways to authenticate? Such as SSH, or Active Directory or any other single sign no technology?

How long is the authentication good for? When does it time out? As I play with and investigate the tools it appears that it never times out? Or perhaps the admin that set up our artifactory server set a long timeout?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @RochaStratovan 

The current mechanisms for Conan auth are only using a user/password or user/token.

These can be defined in different places, all of them can use a token in the password field:
- Interactively, Conan will request them when necessary, password hidden
- Explicitly with ``conan remote login`` command, password visible
- Using ``CONAN_XXX`` environment variables
- Using the ``credentials.json`` file in the cache. This file can be a jinja template, so it can read from other places


It is unlikely that Conan can add any other auth  mechanism, they require also changes in the protocol (that is months-long effort, needing to change server side). Other package managers existing since way longer don't have this kind of feature either (https://github.com/pypa/pip/issues/4475), this is quite challenging thing.

What we might add is a ``credentials.py`` plugin that users can put any arbitrary Python code to obtain their tokens. Would this be something that you are interested in?

**Comment by RochaStratovan** [comment]
Hi @memsharded,

Thank you. I now seet _Artifactory_'s ability to share encrypted passwords and generate/share tokens that can then be used as the `-p <password>` parameter to `conan remote login`.

Thanks for pointing me towards the `CONAN_XXX` environment variables. I found the [documentation reference](https://docs.conan.io/2/reference/environment.html#remote-login-variables) and  this is a good option.

Using your tip [I also found the reference for `credentials.json`](https://docs.conan.io/2/reference/config_files/credentials.html#credentials-json). Previously I skipped that because it says it's experimental and I'm cautious about using functionality that can be removed or changed.

Why is the environment variable method not recommend for developers, while the same concern doesn't exist for the `credentials.json` file?

The `credentials.py` plugin sounds interesting. However, I don't understand enough about the proposed abilities or functionality to really comment as to if it would be better or the same as the environment variables or the `credentials.json` file.

**Comment by memsharded** [comment]
> Why is the environment variable method not recommend for developers, while the same concern doesn't exist for the credentials.json file?

Env-vars are generally more easily visible, listing their values is relatively simple, while access to the ``credentials.json`` is a bit more local, can use other variables not the standard CONAN_PASSWORD ones that would be easier to identify. But both methods are kind of similar security-wise, and it is important to control access to the machines, and monitoring logs to make sure that credentials are not being leaked.


> The credentials.py plugin sounds interesting. However, I don't understand enough about the proposed abilities or functionality to really comment as to if it would be better or the same as the environment variables or the credentials.json file.

I am not an expert in this area, but it might be possible to code something in the plugin that access the credentials in a more secure way, including using some cyphers or encryption, and would be less explicit than having a CONAN_PASSWORD env-var defined in the system.

**Comment by RochaStratovan** [comment]
> I am not an expert in this area, but it might be possible to code something in the plugin that access the credentials in a more secure way, including using some cyphers or encryption, and would be less explicit than having a CONAN_PASSWORD env-var defined in the system.

Oh! This sounds nice. My manager and I where day dreaming about how something like this might work. We use password-less SSH so much we were thinking of something where the authentication was done with SSH, even though it's not using SSH to upload/download data. Just using the SSH key for the authentication.

We are in no way knowledgeable in this area, we were just brainstorming and thought of something like. When authentication is needed, it does an SSH connection for authentication verification, after which it works.

In my investigation I saw that the `.conan.db` file is updated after `conan remote login`. I'm guessing some token or key or something is stored locally for the connection. Maybe grabbing that token would be done via an SSH interaction.

However, that would require a client and server side modification.

Having the ability to store credentials locally in an encrypted manner seems good too. Although I would put all kinds of disclaimers that it should only be used for tokens, not passwords.  (This is based on my non-security trained paranoia about security).
