### ISSUE TITLE
[bug] Incorrect directory or incomplete CMake config files in `cmake.configure` for `build()`

### ISSUE THREAD

**Issue by jimmysoda** [conan-io/conan#15725]
### Environment details

* Operating System+version: Ubuntu 20.04 (WSL)
* Compiler+version: gcc 9.4.0
* Conan version: 2.1.0
* Python version: 3.10.5

### Steps to reproduce

1. Download and/or replicate the following two recipes for libraries in [Azure/azure-sdk-for-cpp](https://github.com/Azure/azure-sdk-for-cpp).

    - [azure-core-cpp](https://github.com/conan-io/conan/files/14365001/azure-core-cpp-conan.zip) (only version 1.10.2 is supported)
    - [azure-storage-common-cpp](https://github.com/conan-io/conan/files/14365024/azure-storage-common-cpp-conan.zip) (only version 12.5.0 is supported).

     Both recipes download a full [Azure/azure-sdk-for-cpp](https://github.com/Azure/azure-sdk-for-cpp) source archive, yet each attempts to build only the corresponding library. The supported versions are compatible with each other.

     Both recipes follow this directory structure:

   ```txt
      ├── all
      │   ├── conandata.yml
      │   ├── conanfile.py
      │   └── test_package
      │       ├── CMakeLists.txt
      │       ├── conanfile.py
      │       └── test_package.cpp
      └── config.yml
   ```

   `azure-core-cpp/1.10.2` requires `libcurl/8.6.0` and `openssl/3.2.1` by default.

   `azure-storage-common/12.5.0` requires `azure-core-cpp/1.10.2`, `libxml2/2.12.4`, and `openssl/3.2.1`.
 
1. Build `azure-core-cpp/1.10.2`. The test_package will run at the end and print out an `Azure::DateTime` for the current time.

   ```
   cd azure-core-cpp-conan
   conan create all --version 1.10.2
   ```

1. Locate the local build cache directory for `azure-core-cpp` in `~/.conan2/p/b`.

   Note that the `~/.conan2/p/b/azure<hash>/b/build/Release` directory is missing `azure-core-cppTargets.cmake`, even though it is referenced in `azure-core-cppConfig.cmake`. On the other hand, all necessary files are available in `~/.conan2/p/b/azure<hash>/p`.

1. Attempt to build `azure-storage-common-cpp/12.5.0`. The process will fail at the `build()` step, specifically when calling `cmake.configure`. The `azure-core-cppTargets.cmake` file cannot be found because the the config files used are from the build cache for `azure-core-cpp/1.10.2` (`~/.conan2/p/b/azure<hash>/b/build/Release`), which is missing the file.

   ```
   cd azure-storage-common-cpp-conan
   conan create all --version 12.5.0
   ```

### Logs

These are the build logs:

[azure-core-cpp-1-10-2_conan-create.log](https://github.com/conan-io/conan/files/14365432/azure-core-cpp-1-10-2_conan-create.log)

[azure-storage-common-cpp-12-5-0_conan-create.log](https://github.com/conan-io/conan/files/14365433/azure-storage-common-cpp-12-5-0_conan-create.log)

I also collected the conan cache directories created by each of these builds:

[azure-core-cpp-1-10-2_conan-cache.zip](https://github.com/conan-io/conan/files/14365443/azure-core-cpp-1-10-2_conan-cache.zip)

[azure-storage-common-cpp-12-5-0_conan-cache.zip](https://github.com/conan-io/conan/files/14365444/azure-storage-common-cpp-12-5-0_conan-cache.zip)

**Comment by memsharded** [comment]
Hi @jimmysoda 

Thanks for your detailed report.

Some quick preliminary questions/feedback:

- Why are you removing the C++ settings in the ``configure()`` method:
  ```python
    def configure(self):
      self.settings.rm_safe("compiler.cppstd")
      self.settings.rm_safe("compiler.libcxx")
  ````
  This is only to be done when the code is pure C, not C++, but this is not the case of the library.


I have been having a look at this for more than one hour now.
It doesn't seem an issue in Conan, but some specific internal thing of the azure libraries that is full of juggling/magic things doing way more than what they should be doing. It seems like the actual build of the "core" library is registering itself at build time, so the later "storage" library does an internal ``find_package(core)`` to locate it, and it magically finds the build version of core, not the final package, even if Conan is not passing that information at all! (because the build folder might not be there always, for example if you are installing the precompiled library). 

I am investigating if this behavior can be deactivated somehow.

**Comment by jimmysoda** [comment]
Thanks @memsharded. I'll remove the lines you mentioned from `configure()`. They are cruft from me trying to replicate the functionality of the aws-c-common from conan-center-index. I'll  also check the Azure SDK for any variables I may have overlooked or any need for a patch.

**Comment by memsharded** [comment]
I have made it work simplifying the ``generate()`` in the consumer ``storage`` to:

```python
 def generate(self):
    deps = CMakeDeps(self)
    deps.generate()

    tc = CMakeToolchain(self)
    tc.variables["DISABLE_AZURE_CORE_OPENTELEMETRY"] = False
    tc.variables["BUILD_PERFORMANCE_TESTS"] = False
    tc.variables["BUILD_TESTING"] = False
    tc.variables["AZURE_SDK_DISABLE_AUTO_VCPKG"] = True
    tc.variables["AZ_ALL_LIBRARIES"] = False
    tc.variables["FETCH_SOURCE_DEPS"] = False
    tc.generate()
```
without the change in folders.
With that ``chdir`` the generated cmake files were located in an inner folder that the toolchain was not pointing at, and then they were not find, and the black magic in the CMake scripts of the azure library managed to find their way to locate the build tree of the previous ``core`` package. So once the generated .cmake scripts are found, then it seems to work.

Can you please give it a try and let me know?

As a side note, I want to check inside Conan why a ``chdir`` is affecting only ``CMakeDeps`` but not ``CMakeToolchain``, I'll run some test.

**Comment by memsharded** [comment]
It seems adding the lines
```python
tc.variables["AZ_ALL_LIBRARIES"] = False
tc.variables["FETCH_SOURCE_DEPS"] = False
```
to the ``core`` recipe might be good (I still don't understand well enough the build system of these azure libraries)

**Comment by jimmysoda** [comment]
Thanks @memsharded. I recall setting those variables to `False` for `azure-storage-common-cpp`, but had omitted to do so for `azure-core-cpp`. However, I'm still getting the same error after disabling `AZ_ALL_LIBRARIES` and `FETCH_SOURCE_DEPS` for `azure-core-cpp`, removing all `azure*` packages, and rebuilding both `azure-core-cpp` and `azure-storage-common-cpp`.

```
No transport adapter was selected, using libcurl as the default option for POSIX.
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
CMake Error at /home/climavision/.conan2/p/b/azure59b40f65744ec/b/build/Release/azure-core-cppConfig.cmake:45 (include):
  include could not find requested file:

    /home/climavision/.conan2/p/b/azure59b40f65744ec/b/build/Release/azure-core-cppTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)


-- Found LibXml2: /home/climavision/.conan2/p/b/libxm034c8adbaf170/p/lib/libxml2.a (found version "2.12.4") 
-- Found OpenSSL: /home/climavision/.conan2/p/b/opensede4114446c79/p/lib/libcrypto.a (found version "3.2.1")  
-- Retrieving version from /home/climavision/.conan2/p/b/azured1d0c98173a1a/b/build/sdk/storage/azure-storage-common/src/private/package_version.hpp
-- VERSION_MAJOR 12
-- VERSION_MINOR 5
-- VERSION_PATCH 0
-- VERSION_PRERELEASE 
-- AZ_LIBRARY_VERSION 
-- Configuring incomplete, errors occurred!

azure-storage-common-cpp/12.5.0: ERROR: 
Package 'cbc58677cd0345a4509113561c094ba683f7d20f' build failed
azure-storage-common-cpp/12.5.0: WARN: Build folder /home/climavision/.conan2/p/b/azured1d0c98173a1a/b/build/Release
ERROR: azure-storage-common-cpp/12.5.0: Error in build() method, line 69
        cmake.configure(build_script_folder=self._source_subfolder)
        ConanException: Error 1 while executing
```

**Comment by memsharded** [comment]
Just in case you missed it, did you also fixed the above?
```python
def generate(self):
    deps = CMakeDeps(self)
    deps.generate()
    ....
```
removing the ``chdir`` context?

**Comment by jimmysoda** [comment]
Thanks @memsharded, moving those two lines outside of the `chdir` context fixed the build!

```txt
...
azure-storage-common-cpp/12.5.0: package(): Packaged 4 '.cmake' files: azure-storage-common-cppConfig.cmake, azure-storage-common-cppConfigVersion.cmake, azure-storage-common-cppTargets-release.cmake, azure-storage-common-cppTargets.cmake
azure-storage-common-cpp/12.5.0: package(): Packaged 1 file: copyright
azure-storage-common-cpp/12.5.0: package(): Packaged 1 '.a' file: libazure-storage-common.a
azure-storage-common-cpp/12.5.0: package(): Packaged 19 '.hpp' files
azure-storage-common-cpp/12.5.0: package(): Packaged 1 '.txt' file: LICENSE.txt
azure-storage-common-cpp/12.5.0: Created package revision d10afb87c70bfb9b54502f8e2f7dac80
azure-storage-common-cpp/12.5.0: Package 'cbc58677cd0345a4509113561c094ba683f7d20f' created
azure-storage-common-cpp/12.5.0: Full package reference: azure-storage-common-cpp/12.5.0#f0fe171e7e7dbe2e65ac71b33eaa67d0:cbc58677cd0345a4509113561c094ba683f7d20f#d10afb87c70bfb9b54502f8e2f7dac80
azure-storage-common-cpp/12.5.0: Package folder /home/climavision/.conan2/p/b/azure9580aa41bf382/p
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: zlib/1.3.1, libcurl/8.6.0, openssl/3.2.1, libiconv/1.17, libxml2/2.12.4
WARN: deprecated:     'env_info' used in: openssl/3.2.1, libiconv/1.17, libxml2/2.12.4
WARN: deprecated:     'cpp_info.build_modules' used in: openssl/3.2.1, libxml2/2.12.4
WARN: deprecated:     'cpp_info.filenames' used in: libxml2/2.12.4
```

This is the `generate` function for `azure-core-cpp`:

```
  def generate(self):
    deps = CMakeDeps(self)
    deps.generate()

    with chdir(self, os.path.join(self.source_folder, "sdk", "core", "azure-core")):
      tc = CMakeToolchain(self)
      tc.variables["BUILD_TRANSPORT_CURL"] = self.options.with_curl_transport
      tc.variables["BUILD_TRANSPORT_WINHTTP"] = self.options.with_winhttp_transport
      tc.variables["DISABLE_AZURE_CORE_OPENTELEMETRY"] = False
      tc.variables["BUILD_PERFORMANCE_TESTS"] = False
      tc.variables["BUILD_TESTING"] = False
      tc.variables["AZURE_SDK_DISABLE_AUTO_VCPKG"] = True
      tc.variables["AZ_ALL_LIBRARIES"] = False
      tc.variables["FETCH_SOURCE_DEPS"] = False
      tc.generate()
```

and this is the one for `azure-storage-common-cpp`:

```
  def generate(self):
    deps = CMakeDeps(self)
    deps.generate()

    with chdir(self, self._source_subfolder):
      tc = CMakeToolchain(self)
      tc.variables["DISABLE_AZURE_CORE_OPENTELEMETRY"] = False
      tc.variables["BUILD_PERFORMANCE_TESTS"] = False
      tc.variables["BUILD_TESTING"] = False
      tc.variables["AZURE_SDK_DISABLE_AUTO_VCPKG"] = True
      tc.variables["AZ_ALL_LIBRARIES"] = False
      tc.variables["FETCH_SOURCE_DEPS"] = False
      tc.generate()
```

The changes you suggested resolved this issue. I will separately look into setting `DISABLE_AZURE_CORE_OPENTELEMETRY`, the inverse logic of the variable threw me off and I ended up enabling telemetry.

**Comment by memsharded** [comment]
```
with chdir(self, self._source_subfolder):
```
I need to test some things regarding the folders for generators, but it might be that removing completely this for the ``CMakeToolchain`` also works

In any case, I'd like to point out that those libraries build scripts are extremely complicated, and specially very coupled to their very own technologies and ways of doing things, not specially friendly to being packaged with external tools. So I have to say that you did an initial great job and manage to package those things with relatively simple Conan recipes, without even needing to apply crazy patches, so not bad 🙂 

Sometimes, creating a Conan package around something can be challenging, but that challenge comes 95% from build that thing as desired, and just 5% is the actual Conan recipe packaging.

Don't hesitate to open new tickets if you have any further question!

**Comment by trns1997** [comment]
Hey guys, 
i just stumbled upon this issue regarding the `azure-sdk-for-cpp`, i would appreciate your inputs on the following PR: https://github.com/conan-io/conan-center-index/pull/23663, i am adding a new recipe for the azure sdk.

**Comment by memsharded** [comment]
Thanks for the ping @trns1997 

Have you checked the new "local-recipes-index"? If not please check: https://blog.conan.io/2024/04/23/Introducing-local-recipes-index-remote.html

This will probably help a lot in reducing the urgency for PRs in ConanCenter, as you can use the recipes from there until the PR is merged.

**Comment by trns1997** [comment]
> Thanks for the ping @trns1997
> 
> Have you checked the new "local-recipes-index"? If not please check: https://blog.conan.io/2024/04/23/Introducing-local-recipes-index-remote.html
> 
> This will probably help a lot in reducing the urgency for PRs in ConanCenter, as you can use the recipes from there until the PR is merged.

Oh thank you @memsharded , I did not know this existed, I'll check it out
