### ISSUE TITLE
tools.unzip prints errors "Filename too long"

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#1572]
When I try to unzip [this](https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-win32.zip) file with tools.unzip i get plenty of errors "Filename too long".

**Comment by memsharded** [comment]
I guess that your OS is Windows, that is the one having a path length limit of 260 chars. 
You might want to use the ``short_paths`` feature, to store the package in a shorter path location, so it doesn't have this issue.
