### ISSUE TITLE
[bug] {{profile_dir}} is expanded incorrectly when used in subdir

### ISSUE THREAD

**Issue by andrey-zherikov** [conan-io/conan#15726]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: N/A
* Conan version: 2.1.0
* Python version: 3.10.2

### Steps to reproduce

Small `setup.bat` file to create profiles:
```cmd
set CONAN_HOME=%cd%\.conan2
mkdir %CONAN_HOME%\profiles\fragment\os
(echo [conf] & echo tools.cmake.cmaketoolchain:user_toolchain = [ "{{profile_dir}}/toolchain.cmake" ]) > %CONAN_HOME%\profiles\fragment\os\windows
echo include(fragment/os/windows) > %CONAN_HOME%\profiles\myprofile
```

Once executed, it creates the following structure in `.conan2` dir:
```
├── profiles
│   ├── fragment
│   │   └── os
│   │       └── windows
│   └── myprofile
```

File content for reference:
- `profiles/myprofile`
  ```
  include(fragment/os/windows)
  ```
- `profiles/fragment/os/windows`
  ```
  [conf]
  tools.cmake.cmaketoolchain:user_toolchain = [ "{{profile_dir}}/toolchain.cmake" ]
  ```

### Logs

Execute `conan profile show -pr:a myprofile` and see invalid toolchain path:

```
Host profile:
[settings]
[conf]
tools.cmake.cmaketoolchain:user_toolchain=['C:\\conan-test\\.conan2\\profiles\x0cragment/os/toolchain.cmake']

Build profile:
[settings]
[conf]
tools.cmake.cmaketoolchain:user_toolchain=['C:\\conan-test\\.conan2\\profiles\x0cragment/os/toolchain.cmake']
```

**Comment by memsharded** [comment]
Thanks for your report @andrey-zherikov 

This was an unfortunate issue with the loading of ``confs`` and Windows backslash.
I am submitting a fix in https://github.com/conan-io/conan/pull/15727 for next release.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/15727 merged, this will be in the next release

**Comment by andrey-zherikov** [comment]
@memsharded Is it possible to port this fix into 2.1.* patch release?
I think I'm facing this issue in our prod:
I have `tools.cmake.cmaketoolchain:user_toolchain = [ "{{conan_home_folder}}/profiles/toolchain/{{platform.system().lower()}}.cmake" ]` in `global.conf`
This is expanded to the following piece of profile:
```
[conf]
tools.cmake.cmaketoolchain:user_toolchain=['D:\\Jenkins\\workspaces\\conan\\workspace\ty_cmake-install-bb-library_main@2/.conan2/profiles/toolchain/windows.cmake']
```
And `\t` in the path above is converted to `<tab>`:
```
-- Using Conan toolchain: D:/Jenkins/workspaces/conan/workspace/ty_cmake-install-bb-library_main@2/.conan2/p/b/cmakef116027922a0c/b/conan_toolchain.cmake
CMake Error at D:/Jenkins/workspaces/conan/workspace/ty_cmake-install-bb-library_main@2/.conan2/p/b/cmakef116027922a0c/b/conan_toolchain.cmake:17 (include):
  include could not find requested file:

    D:/Jenkins/workspaces/conan/workspace	y_cmake-install-bb-library_main@2/.conan2/profiles/toolchain/windows.cmake
Call Stack (most recent call first):
C:/basbuild/build-tools/cmake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:148 (include)
CMakeLists.txt:3 (project)
```

**Comment by memsharded** [comment]
At the moment a patch release is not planned, those are reserved mostly for regressions or large impact bugs.
I'll sync with the team, the Conan 2.2 release shouldn't be far away.

**Comment by andrey-zherikov** [comment]
@memsharded Is there any 2.2 pre-release I can test with?

**Comment by memsharded** [comment]
Running from ``develop2`` branch (clone and ``pip install -e .`` in the repo)

**Comment by andrey-zherikov** [comment]
Tested with `Conan version 2.2.0-dev` - seems it's a different bug and it's still there:
```
-- Using Conan toolchain: C:/1/ty_cmake-install-bb-library_main@2/.conan2/p/b/cmake151f9b67b11af/b/conan_toolchain.cmake
CMake Error at C:/1/ty_cmake-install-bb-library_main@2/.conan2/p/b/cmake151f9b67b11af/b/conan_toolchain.cmake:17 (include):
  include could not find requested file:

    C: y_cmake-install-bb-library_main@2/.conan2/profiles/toolchain/windows.cmake
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:3 (project)
```

@memsharded Do you want me to create another issue?

**Comment by memsharded** [comment]
Yes, please, open another ticket with details to reproduce that new error.
It might be a difficult one to reproduce, looks like path encodings issues.

**Comment by andrey-zherikov** [comment]
Created https://github.com/conan-io/conan/issues/15868
