### ISSUE TITLE
[question] Migrating recipes from conan 1 to conan 2 - Question about the new coordinates_to_conandata()

### ISSUE THREAD

**Issue by CJCombrink** [conan-io/conan#15734]
### What is your question?

Hi! 
I am busy migrating recipes from the old generators to the new generators (still conan 1)

I see with the recent release of conan 2.1 two new utility members were added, `coordinates_to_conandata()` and `checkout_from_conandata_coordinates()` and I have two questions on those:

1. They [use](https://github.com/conan-io/conan/pull/15377/files#diff-9af4758943b5275fbbff9c15f170e7ee81d3ac7f258652be9b4ac222e57158aeR243) `"scm"` as the key in the conan_data. If we compare that to the migration guide, section [The scm attribute](https://docs.conan.io/en/1.63/migrating_to_2.0/recipes.html#the-scm-attribute) it instead uses `"sources"` as the key. Is there a more correct or better one or does it not matter as long as they match? (I am willing to PR a change in the migration guide if `scm` is the better option)
2. Can we expect those functions to be available in conan 1? It would surely make migration easier.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @CJCombrink 

Thanks for your question


These helpers ``coordinates_to_conandata`` aim to be a 2.X-only feature, not backward compatible.
But it is true that if a recipe manages explicitly export()/source() methods to store to conandata, they can use whatever convention and key there, including the ``scm``.

> (I am willing to PR a change in the migration guide if scm is the better option)

That sounds good, thanks for the offer.

> Can we expect those functions to be available in conan 1? It would surely make migration easier.

Not anymore, as long as it is possible with ``export()/source()``, we are no longer backporting these kind of new additions (we would need to backport it to 2.0, create a new 2.0.18 release... the amount of release work grows, we cannot afford it)

**Comment by CJCombrink** [comment]
Thanks for the (quick) response, I can understand the reasoning.
