### ISSUE TITLE
virtualenv and activate/deactivate with nested directories

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#1575]
I've asked about nested projects before, but now I have a specific question about whether/how this can work with the `virtualenv` generator.

The situation is roughly this: I have one CMake out-of-source build directory as per usual. In that build directory, I call `conan install ...` multiple times to get the dependencies not just of the main project, but also of its subprojects. One of those subprojects happens to be an executable needed as a tool at build time, which is made available thanks to the `virtualenv` generator giving me an `activate.bat` script to set the paths.

So far, so good. My question now is this: what happens if more than one of the conanfiles uses `virtualenv` ? Will the `activate.bat` file generated by the last invocation of `conan install` overwrite the script generated by previous invocations?

I'm guessing the answer to that is "yes, it will". If so, do you see an alternative, perhaps for a future release of Conan? (I seem to recall that you mentioned a future feature allowing the sharing of packages that are still in development.)

**Comment by lasote** [comment]
Yes, it will 😉 . The activate.bat, as any other generator file, like conanbuildinfo.cmake, will be overridden. What is the behavior you would like in a future version of Conan? 
You could change again the current directory or use the **--cwd** parameter in conan install to keep different **activate.bat** scripts.

**Comment by JPGygax68** [comment]
That is a really good question.

I think you as the authors will have to make one or more strategic decisions as to what usage patterns you want to actively support. In this case, the usage pattern is "nested project directories" (the subject has come up before in earlier questions).

Since Conan does not *explicitly* support that pattern, I've created my own little script to crawl through my projects' directory structures. Unfortunately, that script clashes with the limitation I've described above, which is that there can be only one pair of activate/deactivate scripts.

You could solve this particular problem by providing an option that appends to the activate/deactivate scripts instead of overwriting them. But I'm pretty sure that other problems related to that pattern would appear soon after.

There is one thing that could be considered a "fallback" and that would, IMO, help programmers help themselves. The actual problem, in my case, is making specific tools (mostly executables, but sometimes libraries too) available for the *build* phase of a given project.

So, how about supporting the use of Conan as "traditional", user-controlled package manager, instead of an automated dependency resolver?

I see the situation this way: programmers often need libraries, but sometimes tools also, and in many cases the libraries we need come with companion tools (FFmpeg would be a good example, ditto OpenCV). Installing those libraries and tools can be hell.  Conan is well on the way of solving the problem of packaging those libraries and tool via recipes,, so why not make the most of those efforts and let the users decide where exactly to install the libraries and tools ?

The net effect would be that Conan could then act as the "bailout guy" for people working on Windows. Chances are that Linux users can install pretty much anything they want, anywhere they want - to system-wide, user-specific or even project-specific locations - with a single invocation of their package manager. The one thing that would help me out most would be to be able to do the same thing in Windows.

**Comment by JPGygax68** [comment]
The `build_requires` approach is powerful - I was already working with it (see below) but read the doc more seriously only now. (I'm a bit confused as to why the patterns were introduced - why should it be up to the consumer package to specify (or override?) the build tools that dependencies are going to need? Shouldn't that be up to each dependency package?)

But `build_requires` cannot help much with nested project directories. To explain: nested project directories are what I get when I jointly develop a project and one or more of its dependencies at the same time. As an example, I have an application that needs to use my GUI library, which is still in early development. So, I use the git submodule functionality to nest the GUI project tree below the root of my application directory.

To combine both projects, I use the CMake `add_subdirectory()` feature, so that in the end I have a Visual Studio solution that is capable of building everything on demand.

However, the (nested) GUI project requires a couple of custom command-line tools to build. So, I created a Conan profile for the GUI project to fulfill one of those dependencies via, yes, `build_requires`.  The problem is that the application (the "parent" project) also has dependencies I would like to satisfy using Conan, which led to the clash I described earlier.

(I'm not saying, btw, that this could not be resolved with `--cwd`, but it would make my own supporting script a lot more complex.)

**Comment by lasote** [comment]
>  (I'm a bit confused as to why the patterns were introduced - why should it be up to the consumer package to specify (or override?) the build tools that dependencies are going to need? Shouldn't that be up to each dependency package?)

It depends, for example, a cross building toolchain can be specified by the consumer. The libraries to be cross built probably don't need to know about that toolchain, but the consumer could need to change the **build_require** with different toolchains. The same for CMake or MinGW, the consumer will choose which packages want to build with which tools. For another kind of **build_requires** like [7zip](https://bintray.com/conan-community/conan/7z_installer%3Aconan), probably it will be specified in the **build_require** field of a recipe that needs to uncompress some compressed file.

The most important feature is our roadmap is to improve the development flows, so thanks for explaining your use case. In this case, have you though about creating a conan package for the GUI project? If the parent project depends on the GUI Project it will work with a simple `conan install` with the same generated `virtualenv`.

**Comment by JPGygax68** [comment]
Thank you for your explanations!
Yes, I've thought about making the GUI library into a package, but I find it much more convenient to have the application and the library in the same build tree while both are still under development.

**Comment by lasote** [comment]
I understand. That's why asked. Your "pain" is developing both packages at the same time when A depends on B. We are working on it, but still, on a very early stage, it is becoming a need for many many users, so your feedback will be welcome when we start to have something!

**Comment by JPGygax68** [comment]
Thank you! I'll let you decide whether to keep this issue open as a reminder, or to close it for now. On my side, I have no further comment for now.

**Comment by memsharded** [comment]
The management of environment now is done with new tools (https://docs.conan.io/en/latest/reference/conanfile/tools/env.html), closing this as legacy
