### ISSUE TITLE
update xkbcommon: FIX: WARN: deprecated

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan#15758]
### What is your suggestion?

xkbcommon/1.5.0: Generators folder: /mnt/d/mc/1/3/.conan2/p/b/xkbco2d696edab57f8/b/build-release/conan
WARN: deprecated: **Please, do not use a Conan option value directly. Convert 'options.with_wayland' into a valid Pythondata type, e.g, bool(self.options.shared)**
WARN: deprecated: Please, do not use a Conan option value directly. Convert 'options.with_x11' into a valid Pythondata type, e.g, bool(self.options.shared)
WARN: deprecated: Please, do not use a Conan option value directly. Convert 'options.xkbregistry' into a valid Pythondata type, e.g, bool(self.options.shared)

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @blockspacer 

Thanks for your report.
It is not very clear what is the issue, those warnings seems correct.
