### ISSUE TITLE
[bug] `cli_args` does not work for `cmake.ctest()`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#15755]
### Environment details

* Operating System+version:
* Compiler+version:
* Conan version: 2.1.0
* Python version:

### Steps to reproduce

1. Call `cmake.ctest(cli_args="--output-on-failure")` in `build()`

### Logs

```
conanfile.py (mp-units/2.2.0): RUN: ctest --build-config Release --parallel 12 - - o u t p u t - o n - f a i l u r e
```

Conan adds spaces in between every letter, causing the `ctest` command to not work properly.

**Comment by AbrilRBS** [comment]
Hi! Thanks for the report.
As for every method in the `CMake` object, the `cli_args` argument is meant to be a list of strings, not a string itself. Can you try `cli_args=["--output-on-failure"]` and let me know if that fixes it? Thanks!

**Comment by mpusz** [comment]
I confirm that it helps. Thanks!

**Comment by AbrilRBS** [comment]
Great to hear, closing as solved :)
