### ISSUE TITLE
Build botan 3.3  on Windows with gcc

### ISSUE THREAD

**Issue by dix75** [conan-io/conan#15759]
Hi all!

It is impossible to build a library under vindows!
`
C:\Users\admin\AppData\Local\Temp\ccFTYqoZ.s: Fatal error: can't write 150 bytes to section .text of build/obj/lib/botan_all.o: 'file too big'

The Window profile contains `CXXFLAGS=-Wa,-mbig-obj`

> [settings]
> os=Windows
> arch=x86_64
> arch_build=x86_64
> compiler=gcc
> compiler.version=11.2
> compiler.libcxx=libstdc++11
> compiler.cppstd=20
> build_type=Release
> [options]
> [build_requires]
> [env]
> botan:CXXFLAGS=-Wa,-mbig-obj
> openssl:CC=c:/MinGW/bin/gcc.exe
> openssl:CXX=c:/MinGW/bin/g++.exe
> [conf]
> tools.env.virtualenv:auto_use=True
> tools.env.environment:auto_use=True
> tools.cmake.cmaketoolchain:generator=Ninja

The Version 2.19.3 was built without problems!

How can I fix this!

**Comment by memsharded** [comment]
Hi @dix75 

Thanks for your question.

Can you please provide reproducible steps for this? Basically:

- The exact Conan version you are using. Recommended to use Conan 2
- The exact command line invocation that you are using
- If you are using a ``conanfile``, that conanfile
- The full output of the command.

As a hint, the ``[env]`` definition is legacy, the ``[buildenv]`` should be used instead
Furthermore, recipes in ConanCenter are not tested with MinGW, but with VS. If you can also try and report if it works in VS, it is also useful information.

It is likely that this is not a Conan issue, but something specific to the botan recipe in ``conan-center-index`` repo

**Comment by dix75** [comment]
The problem is that the '`-Wa,-mbig-obj`' parameters are not passed to the compiler.
How to correctly add additional parameters to the compiler `CXXFLAGS` ?

`botan:CXXFLAGS=-Wa,-mbig-obj`
in `buildenv `section doesn't work!

I tested version 2.1 and 1.63.

**Comment by memsharded** [comment]
Build system integrations listen to the ``tools.build:cxxflags`` conf, see for example ``CMakeToolchain``: https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#conf

So you need to define it in your profile, like
```
[conf]
tools.build:cxxflags=["-Wa", "-mbig-obj"]
```

**Comment by dix75** [comment]
Thank you. 
It's working.
Is there any possibility to add these flags only for building one library?

**Comment by memsharded** [comment]
Yes, same per-package prefix can be applied:
```
[conf]
mypkg/*:tools.build:cxxflags=["-Wa", "-mbig-obj"]
```

If it is working, I am closing the ticket as solved, thanks!
