### ISSUE TITLE
Multiple Consume Packages Lead to 403 Forbidden on bzip2 dependency

### ISSUE THREAD

**Issue by richjohnson-wwt** [conan-io/conan#15765]
### Environment details

arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

* Conan version 2.1.0
* Python version: 3.9.6

### Steps to reproduce

This same scenario plays out with poco and sfml for me.

conanfile.txt:

[requires]
poco/1.13.2
cmake/3.28.1

[generators]
CMakeDeps
CMakeToolchain

[layout]
cmake_layout

Then run: conan install . --build=missing

bzip2/1.0.8: Sources downloaded from 'conancenter'
bzip2/1.0.8: Calling source() in /Users/johnsonr/.conan2/p/bzip232e122e5f0e0b/s/src
ERROR: bzip2/1.0.8: Error in source() method, line 50
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        AuthenticationException: 403: Forbidden

### Logs

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

Profile build:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

======== Computing dependency graph ========
poco/1.13.2: Not found in local cache, looking in remotes...
poco/1.13.2: Checking remote: conancenter
poco/1.13.2: Downloaded recipe revision 8f1ef7528ac796a75e72b83afd809719
pcre2/10.42: Not found in local cache, looking in remotes...
pcre2/10.42: Checking remote: conancenter
pcre2/10.42: Downloaded recipe revision a7a2c122056510509a7525c83d6a6695
zlib/1.3.1: Not found in local cache, looking in remotes...
zlib/1.3.1: Checking remote: conancenter
zlib/1.3.1: Downloaded recipe revision f52e03ae3d251dec704634230cd806a2
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Checking remote: conancenter
bzip2/1.0.8: Downloaded recipe revision 457c272f7da34cb9c67456dd217d36c4
expat/2.5.0: Not found in local cache, looking in remotes...
expat/2.5.0: Checking remote: conancenter
expat/2.5.0: Downloaded recipe revision 91e43e4544923e4c934bfad1fa4306f9
sqlite3/3.45.0: Not found in local cache, looking in remotes...
sqlite3/3.45.0: Checking remote: conancenter
sqlite3/3.45.0: Downloaded recipe revision 3a7911478ffd14e7acc694ac113449b6
openssl/3.2.1: Not found in local cache, looking in remotes...
openssl/3.2.1: Checking remote: conancenter
openssl/3.2.1: Downloaded recipe revision 39bd48ed31f1f3fbdcd75a0648aaedcf
libpq/15.4: Not found in local cache, looking in remotes...
libpq/15.4: Checking remote: conancenter
libpq/15.4: Downloaded recipe revision cbae5e1ee85bd5e959e039e00307e8b1
libmysqlclient/8.1.0: Not found in local cache, looking in remotes...
libmysqlclient/8.1.0: Checking remote: conancenter
libmysqlclient/8.1.0: Downloaded recipe revision ecca1993f7ce32371ef5436f3639074a
zstd/1.5.5: Not found in local cache, looking in remotes...
zstd/1.5.5: Checking remote: conancenter
zstd/1.5.5: Downloaded recipe revision b87dc3b185caa4b122979ac4ae8ef7e8
lz4/1.9.4: Not found in local cache, looking in remotes...
lz4/1.9.4: Checking remote: conancenter
lz4/1.9.4: Downloaded recipe revision 1217a03c990b79aa34ed0faede18f534
cmake/3.28.1: Not found in local cache, looking in remotes...
cmake/3.28.1: Checking remote: conancenter
cmake/3.28.1: Downloaded recipe revision 92f79424d7b65b12a84a2180866c3a78
Graph root
    conanfile.txt: /Users/johnsori/myspace/code/cpp/poco-hello/conanfile.txt
Requirements
    bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4 - Downloaded (conancenter)
    cmake/3.28.1#92f79424d7b65b12a84a2180866c3a78 - Downloaded (conancenter)
    expat/2.5.0#91e43e4544923e4c934bfad1fa4306f9 - Downloaded (conancenter)
    libmysqlclient/8.1.0#ecca1993f7ce32371ef5436f3639074a - Downloaded (conancenter)
    libpq/15.4#cbae5e1ee85bd5e959e039e00307e8b1 - Downloaded (conancenter)
    lz4/1.9.4#1217a03c990b79aa34ed0faede18f534 - Downloaded (conancenter)
    openssl/3.2.1#39bd48ed31f1f3fbdcd75a0648aaedcf - Downloaded (conancenter)
    pcre2/10.42#a7a2c122056510509a7525c83d6a6695 - Downloaded (conancenter)
    poco/1.13.2#8f1ef7528ac796a75e72b83afd809719 - Downloaded (conancenter)
    sqlite3/3.45.0#3a7911478ffd14e7acc694ac113449b6 - Downloaded (conancenter)
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Downloaded (conancenter)
    zstd/1.5.5#b87dc3b185caa4b122979ac4ae8ef7e8 - Downloaded (conancenter)
Build requirements
    cmake/3.28.1#92f79424d7b65b12a84a2180866c3a78 - Downloaded (conancenter)
Resolved version ranges
    cmake/[>=3.18 <4]: cmake/3.28.1
    openssl/[>=1.1 <4]: openssl/3.2.1
    zlib/[>=1.2.11 <2]: zlib/1.3.1

======== Computing necessary packages ========
libmysqlclient/8.1.0: Checking 11 compatible configurations
libmysqlclient/8.1.0: Compatible configurations not found in cache, checking servers
libmysqlclient/8.1.0: 'cfea978178b7196891b05818e0c8525aa5031e73': compiler.cppstd=98
libmysqlclient/8.1.0: '968802de46348f2be0386d5c5200f836a020e710': compiler.cppstd=gnu98
libmysqlclient/8.1.0: '8dfd206d2f17563c60c2069f89227b4741c4f26f': compiler.cppstd=11
libmysqlclient/8.1.0: '5222e6d26f40cfbe198bfdaafd28d052b2a028ae': compiler.cppstd=gnu11
libmysqlclient/8.1.0: '5817083689f19133df5fa1dec8f2598ebdeec3b5': compiler.cppstd=14
libmysqlclient/8.1.0: '2d82cd5c6002b2ed2354ff9b99c9a1db9b8d5de2': compiler.cppstd=gnu14
libmysqlclient/8.1.0: '7c074531806a60f4895840a3215e39d8ec823989': compiler.cppstd=17
libmysqlclient/8.1.0: '1cd53fa32f058df1a820404cef67d43e58ee2862': compiler.cppstd=20
libmysqlclient/8.1.0: '1d4d6199005d30399c1e392d636de61635e167d9': compiler.cppstd=gnu20
libmysqlclient/8.1.0: '1673a3cb79f51ad1a364881e28fed51ca097a168': compiler.cppstd=23
libmysqlclient/8.1.0: 'd9c25261dcf51d5d7f57f2b8cd8e6e88bb08fe8f': compiler.cppstd=gnu23
poco/1.13.2: Checking 5 compatible configurations
poco/1.13.2: Compatible configurations not found in cache, checking servers
poco/1.13.2: 'ca4782b91025cdf3ced5a51a2b53c38c6bf33ebe': compiler.cppstd=17
poco/1.13.2: '32164e63315afced7d855e85a51a1b62724682f1': compiler.cppstd=20
poco/1.13.2: '7f3a6b74fe3cfdb556b79ad99736f16cb4750f89': compiler.cppstd=gnu20
poco/1.13.2: '08690a44797cf069616731747c8d5ab3b7b18f39': compiler.cppstd=23
poco/1.13.2: '44e6d5bceecb84dd4d93b35e58b7b39aa1d9ad9c': compiler.cppstd=gnu23
Requirements
    bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4:bd47875fc25b97398a4030f4060ef8ef3539584a - Build
    cmake/3.28.1#92f79424d7b65b12a84a2180866c3a78:9e5323c65b94ae38c3c733fe12637776db0119a5#2ace414902354371affae8b3b49fd2d0 - Download (conancenter)
    expat/2.5.0#91e43e4544923e4c934bfad1fa4306f9:10fd60dbb19c1c7b079fb35f1ca651920973f9ca - Build
    libmysqlclient/8.1.0#ecca1993f7ce32371ef5436f3639074a:ba7095561a14b7ff2949805be9ef59edefd108eb - Build
    libpq/15.4#cbae5e1ee85bd5e959e039e00307e8b1:f0b000c509a4fac0d67f486d07efc67f25653547 - Build
    lz4/1.9.4#1217a03c990b79aa34ed0faede18f534:2ee39e692ca4177b4b689b15bc1f2cfdf8f83706 - Build
    openssl/3.2.1#39bd48ed31f1f3fbdcd75a0648aaedcf:6c5be3e8c24780ce8840a294f99c0b01b1fd0686 - Build
    pcre2/10.42#a7a2c122056510509a7525c83d6a6695:17867723f5118ac06c0e40c6780f191fc7f9489d - Build
    poco/1.13.2#8f1ef7528ac796a75e72b83afd809719:923003cabe568928dd9f4a609e5ee0d87be8d546 - Build
    sqlite3/3.45.0#3a7911478ffd14e7acc694ac113449b6:dc4b586c4203330fce9008cb16c26d25219e4944 - Build
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:2ee39e692ca4177b4b689b15bc1f2cfdf8f83706 - Build
    zstd/1.5.5#b87dc3b185caa4b122979ac4ae8ef7e8:76dad4e6c83dde347fd81bafee7e53584d62846e - Build
Build requirements
    cmake/3.28.1#92f79424d7b65b12a84a2180866c3a78:9e5323c65b94ae38c3c733fe12637776db0119a5#2ace414902354371affae8b3b49fd2d0 - Download (conancenter)

======== Installing packages ========

-------- Downloading 1 package --------
cmake/3.28.1: Retrieving package 9e5323c65b94ae38c3c733fe12637776db0119a5 from remote 'conancenter' 
cmake/3.28.1: Downloading 79.0MB conan_package.tgz
cmake/3.28.1: Decompressing 79.0MB conan_package.tgz
cmake/3.28.1: Package installed 9e5323c65b94ae38c3c733fe12637776db0119a5
cmake/3.28.1: Downloaded package revision 2ace414902354371affae8b3b49fd2d0
bzip2/1.0.8: Sources downloaded from 'conancenter'
bzip2/1.0.8: Calling source() in /Users/johnsori/.conan2/p/bzip232e122e5f0e0b/s/src
ERROR: bzip2/1.0.8: Error in source() method, line 50
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        AuthenticationException: 403: Forbidden

**Comment by memsharded** [comment]
Hi @richjohnson-wwt 

Thanks for your report. If this is failing on your side, it should be possible to reproduce with a much smaller case:
```
$ conan remove bzip2* -c  # Just to make sure
$ conan install --requires=bzip2/1.0.8 --build="bzip2*"
```
Does that fail in your case?

This doesn't fail here, so one possible cause is that you have some VPN, firewall, proxy, or the like, that is blocking you from downloading those sources from the internet. Is this the case?

**Comment by richjohnson-wwt** [comment]
Wow, thanks for quick response. You're right. I dropped the VPN connection and it worked. On the VPN, It downloaded every other dependency except bzip2 for SFML and poco so I didn't consider that was the issue.  Thank you!

**Comment by richjohnson-wwt** [comment]
Resolved!

**Comment by memsharded** [comment]
> wow, thanks for quick response. You're right. I dropped the VPN connection and it worked. On the VPN, It downloaded every other dependency except bzip2 for SFML and poco so I didn't consider that was the issue. Thank you!

happy to help! 🙂
