### ISSUE TITLE
[question] CMake generators don't check compiler version mismatch

### ISSUE THREAD

**Issue by PeteAudinate** [conan-io/conan#15766]
### What is your question?

I've just noticed that the Conan v2 Cmake generators don't check that the actual gcc/clang compiler version matches the version specified in the settings.

We use packaged toolchains everywhere, so never have a situation where the wrong compiler version might accidentally be used.

But how do people manage this when using the system compiler? For example, if a machine happens to have gcc 10 installed and I try to compile using a gcc 9 profile, I'd like it to fail rather than silently use the wrong compiler version.

Does everyone just set `tools.build:compiler_executables={ "c": "gcc-9", "cpp": "g++-9" }` in their profiles to ensure this? Or am I missing something obvious?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by PeteAudinate** [comment]
I thought I remembered this producing an error in the past, and @ericLemanissier helpfully pointed out the following code that appears to check for a compiler version mismatch. I guess this isn't being used anymore, perhaps?

https://github.com/conan-io/conan/blob/develop/conans/client/generators/cmake_common.py#L426

**Comment by PeteAudinate** [comment]
For example, here's me trying to use clang v10 with a profile that specifies clang v9 (though without `tools.build:compiler_executables` set).

I'd have hoped for an error, but it happily compiles using v10.

```
$ export CXX=/usr/bin/clang-10
$ conan install --requires=catch2/2.13.10 --profile clang9 --build="*"

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    catch2/2.13.10#d8541ec3a7e1236ecc46a5952896969e - Cache

======== Computing necessary packages ========
catch2/2.13.10: Forced build from source
Requirements
    catch2/2.13.10#d8541ec3a7e1236ecc46a5952896969e:da39a3ee5e6b4b0d3255bfef95601890afd80709 - Build

======== Installing packages ========

-------- Installing package catch2/2.13.10 (1 of 1) --------
catch2/2.13.10: Building from source
catch2/2.13.10: Package catch2/2.13.10:da39a3ee5e6b4b0d3255bfef95601890afd80709
catch2/2.13.10: Copying sources to build folder
catch2/2.13.10: Building your package in /home/pete/.conan2/p/b/catch87269dc57eee0/b
catch2/2.13.10: Calling generate()
catch2/2.13.10: Generators folder: /home/pete/.conan2/p/b/catch87269dc57eee0/b/build/Release/generators
catch2/2.13.10: CMakeToolchain generated: conan_toolchain.cmake
catch2/2.13.10: CMakeToolchain generated: CMakePresets.json
catch2/2.13.10: CMakeToolchain generated: ../../../src/CMakeUserPresets.json
catch2/2.13.10: Generating aggregated env files
catch2/2.13.10: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
catch2/2.13.10: Calling build()
catch2/2.13.10: Running CMake.configure()
catch2/2.13.10: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/pete/.conan2/p/b/catch87269dc57eee0/b/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/pete/.conan2/p/b/catch87269dc57eee0/p" -DCATCH_INSTALL_DOCS="OFF" -DCATCH_INSTALL_HELPERS="ON" -DCATCH_BUILD_STATIC_LIBRARY="False" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/pete/.conan2/p/b/catch87269dc57eee0/b/src"
-- Using Conan toolchain: /home/pete/.conan2/p/b/catch87269dc57eee0/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 14 with extensions ON
-- The CXX compiler identification is Clang 10.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang-10 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (1.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/pete/.conan2/p/b/catch87269dc57eee0/b/build/Release
...

catch2/2.13.10: Package 'da39a3ee5e6b4b0d3255bfef95601890afd80709' built
catch2/2.13.10: Build folder /home/pete/.conan2/p/b/catch87269dc57eee0/b/build/Release
catch2/2.13.10: Generating the package
catch2/2.13.10: Packaging in folder /home/pete/.conan2/p/b/catch87269dc57eee0/p
catch2/2.13.10: Calling package()
catch2/2.13.10: Running CMake.install()
catch2/2.13.10: RUN: cmake --install "/home/pete/.conan2/p/b/catch87269dc57eee0/b/build/Release" --prefix "/home/pete/.conan2/p/b/catch87269dc57eee0/p"
-- Install configuration: "Release"
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/lib/cmake/Catch2/Catch2Targets.cmake
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/include
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/include/catch2
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/include/catch2/catch.hpp
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/include/catch2/catch_reporter_sonarqube.hpp
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/include/catch2/catch_reporter_teamcity.hpp
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/include/catch2/catch_reporter_automake.hpp
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/include/catch2/catch_reporter_tap.hpp
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/lib/cmake/Catch2/Catch2Config.cmake
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/lib/cmake/Catch2/Catch2ConfigVersion.cmake
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/lib/cmake/Catch2/ParseAndAddCatchTests.cmake
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/lib/cmake/Catch2/Catch.cmake
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/lib/cmake/Catch2/CatchAddTests.cmake
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/share/Catch2/gdbinit
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/share/Catch2/lldbinit
-- Installing: /home/pete/.conan2/p/b/catch87269dc57eee0/p/share/pkgconfig/catch2.pc

catch2/2.13.10: package(): Packaged 5 '.hpp' files
catch2/2.13.10: package(): Packaged 3 '.cmake' files: ParseAndAddCatchTests.cmake, CatchAddTests.cmake, Catch.cmake
catch2/2.13.10: package(): Packaged 1 '.txt' file: LICENSE.txt
catch2/2.13.10: Created package revision d747b95b8e7ed466e354429ffd7f048f
catch2/2.13.10: Package 'da39a3ee5e6b4b0d3255bfef95601890afd80709' created
catch2/2.13.10: Full package reference: catch2/2.13.10#d8541ec3a7e1236ecc46a5952896969e:da39a3ee5e6b4b0d3255bfef95601890afd80709#d747b95b8e7ed466e354429ffd7f048f
catch2/2.13.10: Package folder /home/pete/.conan2/p/catch95371a689a8ee/p
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: catch2/2.13.10

======== Finalizing install (deploy, generators) ========
cli: Generating aggregated env files
cli: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
```

**Comment by memsharded** [comment]
Hi @PeteAudinate 

Thanks for your question

> I've just noticed that the Conan v2 Cmake generators don't check that the actual gcc/clang compiler version matches the version specified in the settings.

This is not specific of Conan2, but already happens in Conan 1 with the modern ``CMakeToolchain`` generator.
The moment a non-intrusive, transparent integration via CMake toolchain files is used, it is not possible anymore to do these compiler checks, because the toolchain code executes to define the compiler and before the compiler is defined. So it is impossible for the ``conan_toolchain.cmake`` to do any actual compiler version checks.

We were evaluating this, and as always it is a trade-off. We considered that the benefits of the transparent ``CMakeToolchain`` integration, together with the much higher configurability and flexibility and also the capabilities of having user builds via ``cmake`` (with toolchain or presets) that match exactly the builds of ``conan build`` and ``conan create``, were much higher than the inconvenience of not having the compiler version check.


> But how do people manage this when using the system compiler? For example, if a machine happens to have gcc 10 installed and I try to compile using a gcc 9 profile, I'd like it to fail rather than silently use the wrong compiler version.

The ``profile.py`` plugin could be used to do some extra checks like the compiler version check, if this is problematic.
In practice, it is not that common that users do mistakes in the compiler version they are using, specially in CI that are more controlled.

> Does everyone just set tools.build:compiler_executables={ "c": "gcc-9", "cpp": "g++-9" } in their profiles to ensure this? Or am I missing something obvious?

No, not really. This might help to avoid some of those errors, yes, but also not necessary for all those cases that are aligned.
I think if this would become an issue in my case, I'd try to introduce a check in the ``profile.py`` plugin.

**Comment by PeteAudinate** [comment]
Thanks for your quick reply, much appreciated as always! That makes sense. 

> The profile.py plugin could be used to do some extra checks like the compiler version check, if this is problematic.

I hadn't considered checking this in a `profile.py` plugin.

Do you mean look at the combination of CC, CXX and PATH, run the appropriate `compiler --version`, then ensure the result matches settings.compiler.version?

Would this still work if compiler_executables is overridden somwhere? To handle the cross-compilation case, for example. 

Also, the docs say that `profile.py` receives a single profile. What happens when multiple profiles are composed on the commandline? Does it check each one separately, or just the final combined profile?

> In practice, it is not that common that users do mistakes in the compiler version they are using, specially in CI that are more controlled.

Sure, our CI environments are well controlled, but this is really just to avoid silly mistakes on devs' machines. I don't think we'd want to try to account for all things that might go wrong. TBH, adding a specific version to `tools.build:compiler_executables` to each profile is so simple that we'll probably just leave it at that. Trying to parse the output of `compiler --version` is probably overkill for us.

**Comment by memsharded** [comment]
> Do you mean look at the combination of CC, CXX and PATH, run the appropriate compiler --version, then ensure the result matches settings.compiler.version?

Yes, something in that line.

> Would this still work if compiler_executables is overridden somwhere? To handle the cross-compilation case, for example.

No, it wouldn't. In practice  it would be challenging to auto-detect all cases from Conan side. 
It is likely that the only robust-enough (and even in that case not perfect, the Conan 1.X automatic checks also had false positives) would be to introduce explicit CMake code in the users ``CMakeLists.txt``, but that would be ugly and intrusive, it is not planned anything like that at the moment, not worth the value/effort.

> Also, the docs say that profile.py receives a single profile. What happens when multiple profiles are composed on the commandline? Does it check each one separately, or just the final combined profile?

It receives the "final" composed profile of all the command line profiles plus settings plus options plus conf.

> Sure, our CI environments are well controlled, but this is really just to avoid silly mistakes on devs' machines. I don't think we'd want to try to account for all things that might go wrong. 

That typically would be a very minor issue, as long as the developers don't have permissions to upload packages directly (https://docs.conan.io/2/knowledge/guidelines.html)

> TBH, adding a specific version to tools.build:compiler_executables to each profile is so simple that we'll probably just leave it at that. Trying to parse the output of compiler --version is probably overkill for us.

Sounds reasonable.

**Comment by PeteAudinate** [comment]
Understood, thanks for clarifying. And I agree that it's reasonable for Conan not to do any checking, it just took me a bit by surprise.

**Comment by eric-riff-simplisafe** [comment]
I have to say, this took me by surprise.
I have an ubuntu build environment where both gcc 11 and 12 are installed.
I had my profile set like this
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.cstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
```

Yet CMake is using gcc-11, the system default:
```
- The CXX compiler identification is GNU 11.4.0
```
And `conan list` also says this is a package built with gcc 12. 

Is using `tools.build:compiler_executables` the recommended workflow for these scenarios?

**Comment by memsharded** [comment]
Hi @eric-riff-simplisafe 

Yes, if you have gcc 12 in a non standard location, and the system one is gcc 11 (i guess that a ``conan profile detect`` would detect gcc 11), then it is needed to specify it somehow. That somehow depends on you, your need, your flows, etc.

For example it is perfectly valid if you are in a Linux system to do some ``update-alternatives`` to change the default gcc to your gcc 12. Or you can define the environment via ``CC/CXX`` environment variables on your side.

If you want to make it with Conan profiles, yes, ``compiler_executables`` in ``[conf]`` section is a common way to do it. The idea is that it is similar to the ``CC/CXX`` environment variables, but it can also work for some compilers or platforms that don't really listen to those env-vars. But many users define ``CC/CXX`` in their ``[buildenv]`` section in the profile, and it can work for them.

**Comment by eric-riff-simplisafe** [comment]
I do use linux and I install `gcc` using `apt` so it is not on a custom path. It never crossed my mind that conan wouldn't honor what you set on `compiler.version`.
And I don't want to use update-alternatives, I want to use different profiles to build with different gcc versions so I don't mess with my system.
If `compiler_executables` is the way to go for this, I'm ok with it. It is just a bit unintuitive / unexpected.

**Comment by memsharded** [comment]
It is almost impossible to correctly setup a toolchain/compiler in a multiplatform way with something like ``compiler=gcc`` and ``compiler.version=12``. That responsibility is well beyond a package manager, and Conan never intended to act as a smart auto-detector/locator of the toolchain and automatic set it up. The ``settings`` mostly behave as a declaration of the current environment, not as setup instructions about the environment.

We have tried to make this documented, and there are several parts of the docs that explain about setting the compiler, for example:

- In the very first page of the Conan getting started tutorial: https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html
 
 > Using a compiler other than the auto-detected one

 > If you want to change a Conan profile to use a compiler different from the default one, you need to change the compiler setting and also tell Conan explicitly where to find it using the [tools.build:compiler_executables configuration](https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#conan-cmake-toolchain-conf).

- with ``[buildenv]`` https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html
- with a special ``conf`` such as ``ndk_path``: https://docs.conan.io/2/examples/cross_build/android/ndk.html#examples-cross-build-android-ndk
- An example using the ``compiler_executables`` conf for Tricore compiler: https://docs.conan.io/2/examples/cross_build/tricore.html
