### ISSUE TITLE
[feature] Expand ```.conanrc``` to allow difinition of local default profiles

### ISSUE THREAD

**Issue by antoinebardoz** [conan-io/conan#15769]
### What is your suggestion?

Hi,

We work on multiple target architectures, and so we do a lot of cross compiling, using various profiles. Since we have multiple targets, we cannot use a default profile.

This means that we _always_ have to set ```-pr:b some_x86_profile -pr:h some_target_profile``` in our commands. This is tedious to say the least. I am incredibly jealous of people who can simply write ```conan build .``` or similar. It would be fantastic if we could have a default profile set in ```.conanrc``` so we could then have a sensible default per repo or per subfolder, and have the CLI arguments override this default if necessary. For example:
```.conanrc``` contains:
```
profile_build = x86_64_profile
profile_host = arm64_profile
```

Then, at the very least if I want to compile for MIPS instead, I wouldn't have to set ```-pr:b```, just ```-pr:h```:
```
conan build -pr:h mips_profile
```

and if I were compiling for arm64, I wouldn't need any profiles at all in the command.

This would be a game changer for us.

EDIT: It could also simply contain a field like ```local_conf_path``` so we could use the same fields we would've used in global.conf if we only needed a single profile, and have them be appended to the stuff we have in our global.conf.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I think this  might be a duplicate of https://github.com/conan-io/conan/issues/15209?

**Comment by antoinebardoz** [comment]
Great, I agree it's a duplicate. I will close this issue :+1:
