### ISSUE TITLE
[question] Using profile host and profile build in conan create

### ISSUE THREAD

**Issue by Vasile-Creuco** [conan-io/conan#15778]
### What is your question?

Hi!

I have a question regarding how to use profiles in conan create.

So, I want to create a package with a specific profile, but the dependencies which I get for create the package, have another profile with different details.

For example the package which I want to create have the profile like this:

`buildProfile`

```
[settings]
build_type=Release
compiler=Visual Studio
os=Windows
arch=x86_64
```

The profile for dependencies is:

`defaultProfile`

```
[settings]
build_type=Debug
compiler=Visual Studio
os=Windows
arch=x86_64
```
I tried to use the conan command with profile host and profile build arguments:

`conan create . --name=namePackage --version=1.1.1 --user=username --channel=channel_Name -pr:h defaultProfile -pr:b buidProfile
`

And it also created a package which have the `defaultProfile`. It can be visible the result in `conaninfo.txt` from package created:
```
[settings]
arch=x86_64
build_type=Debug
compiler=Visual Studio
os=Windows
[requires]
name_dependencies/1.Y.Z@username/channel_Name
```

So, How can I proceed? Is it possible to create package with specific profile if dependencies have different profile?

Many thanks!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Vasile-Creuco 

Thanks for your question.

The host and build profiles are not related to what you are trying to achieve, but to the usage of ``tool_requires`` and the build and host contexts. Please have a look to https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html to understand better about it. Note that this also applies even if not cross-building, for example when you are building in ``Debug`` (host), you typically want your build tools, in ``tool_requires`` like ``cmake/3.25`` or ``ninja/1.11`` to be executing in ``Release`` (in the build context).

I think what you are looking for is per-package settings in the "host" context: check the "profile patterns" docs in https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns

There is a placeholder for the "current consumer" which is ``&``. So a profile like:
```
[settings]
build_type=Release
&:build_type=Debug
```
Will have the dependencies in Release and the current package under development in Debug (in the user folder space)
Same works with ``conan install ... -pr=profile_release -s &:build_type=Debug`` in command line.

**Comment by Vasile-Creuco** [comment]
Many thanks for your support!
