### ISSUE TITLE
[feature] python_requires; change package_id through attributes

### ISSUE THREAD

**Issue by antoinebardoz** [conan-io/conan#15774]
### What is your suggestion?

Hi,

For regular Conan packages, we can change the package_id mode with attributes, such as:
```
package_id_embed_mode = "unrelated_mode"
package_id_non_embed_mode = "unrelated_mode"
package_id_unknown_mode = "unrelated_mode"
```

Unfortunately, this doesn't work for a python-require package.  I have tried with the following:
```
def some_function():
    pass

class MyPythonReq(ConanFile):
    name = "python_tool"
    package_type = "python-require"

    package_id_embed_mode = "unrelated_mode"
    package_id_non_embed_mode = "unrelated_mode"
    package_id_unknown_mode = "unrelated_mode"
```

If one of my packages consumes this python-requirement, the package ID of the consumer changes if the version of ```python_tool``` changes. We would like to be able to set it in unrelated_mode using attributes.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @antoinebardoz 

I think what you request was added in Conan 2.1: https://docs.conan.io/2/changelog.html

Please check:

- https://github.com/conan-io/conan/pull/15453
- https://github.com/conan-io/docs/pull/3542/files

And let me know

**Comment by antoinebardoz** [comment]
Fantastic, I'm very happy to hear this. This fixes our issue.
