### ISSUE TITLE
Conan version 2.1.0 - pkgconf/2.1.0: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan#15776]
### What is your suggestion?

Conan version 2.1.0 

WARNING:

pkgconf/2.1.0: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @blockspacer 

Why would be this an issue? That call in ``pkgconf`` recipe is deprecated and will be removed. The recipe must be fixed, totally intended and expected.
