### ISSUE TITLE
[question] conan2: reexport recipe with sources

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#15773]
### What is your question?

Hi, I would like to take already existing recipe without binary packages and reexport it under different version/user/channel. How can I achieve this with conan2 without cutting corners? Currently I'm doing it like this:
1) download recipe through conan download
2) get folder with recipe and folder with sources through conan cache path and --folder export_source
3) copy recipe and source folder to some temporary folder
4) use conan export with desired version/user/channel
5) upload recipe through conan upload

Is there some better way to achieve the same result? Ideally I would like to skip step 3.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Nekto89 

Thanks for your question.

I am not sure why this flow. The recommended approach would be to go to the git source repository and ``conan export`` from there. Could you please elaborate a bit more the problem you are trying to solve?

Regarding the ``user/channel``, the recommendation would be mostly to forget about those, use them as constant and immutable, not something that changes over time. For open-source, ConanCenter like, using them as ``zlib/1.3`` without user/channel is the recommended approach.

**Comment by Nekto89** [comment]
> Hi @Nekto89
> 
> Thanks for your question.
> 
> I am not sure why this flow. The recommended approach would be to go to the git source repository and `conan export` from there. Could you please elaborate a bit more the problem you are trying to solve?

It is used as promotion. some packages "name@version-devXXXXX@user/nightly" are promoted to "name@version@user/stable". "Sources" contain .so/.dll/.dylib so it would be nice if there would be some way to copy whole conan_sources.tgz without unpacking step.

**Comment by memsharded** [comment]
> It is used as promotion. some packages "name@version-devXXXXX@user/nightly" are promoted to "name@version@user/stable". "Sources" contain .so/.dll/.dylib so it would be nice if there would be some way to copy whole conan_sources.tgz without unpacking step.

The promotion flow via ``user/channel`` is no longer recommended. This is also a reason why the ``conan copy`` command was dropped. It has several flows problems and issues.

The recommended approach is to do promotions (copies) of immutable artifacts (with exactly same references with same user/channel) accross different server repos. So there is a server repo called ``xxx-nightly`` and another repo called ``xxx-stable``. When some packages are validated they are copied from one repo to the other, but not changing user/channel anymore (also not the version).

**Comment by memsharded** [comment]
Closing this question as responded, please don't hesitate to re-open or create new tickets if necessary, thanks.
