### ISSUE TITLE
[question] Can I create dynamic package option name?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#15783]
Hi,
I need to create Conan packages that “requires” certain dependencies from a prebuilt Yocto SDK. It means that these packages would not have a regular “.requires” counterparts in conanfile.py
However I need to have these SDK requirements exposed in the package_id - for obvious reasons.
This would require dynamic package option names. E.g I need something like “zlib_version”= 1.2.13-r0
I can’t have a “sdk_version=zlib/1.2.13-r0” as that can’t work when this given package  is consumed by someone else - as that entity can’t recreate this same “sdk_version” value
Any idea whether this can be done if it can be at all?
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for your question.

I am not sure I understood it completely.
Maybe this is one case for the ``replace_requires`` feature described in https://blog.conan.io/2024/02/20/Conan-2-graph-features.html? You can create recipe wrappers for system dependencies, and used them to model them, including things like ``package_id``.

Maybe another approach is to add a custom setting? https://docs.conan.io/2/reference/config_files/settings.html#customizing-settings

If the SDK in the system is something that affects packages linking it, then it would be similar to a ``compiler.version`` setting, isn't it? Then it would deserve to be modeled correctly, maybe as a subsetting to the ``compiler`` or to the ``os``?


>  E.g I need something like “zlib_version”= 1.2.13-r0
I can’t have a “sdk_version=zlib/1.2.13-r0” as that can’t work when this given package is consumed by someone else - as that entity can’t recreate this same “sdk_version” value

This part I don't understand it, sorry.

**Comment by harsszegi** [comment]
Hi @memsharded,

afaik I have overcomplicated the things a bit :)
I needed something like this (this is a python_requires base recipe, so yocto_deps is set by the children):

  ```
options = {
    "shared": [True, False], 
    "fPIC": [True, False], 
  }
  default_options = {
    "shared": False, 
    "fPIC": False, 
  }

  yocto_deps = None

  def init(self):
    if self.yocto_deps is not None:
      for dep in self.yocto_deps:
        option_value = f'{dep}_version'
        self.options.update({option_value : "ANY"});
        self.default_options.update({option_value : None});

```
Then later I could fill this like:

`self.options.__setattr__(f'{dep}_version', "Yocto version for 'dep'")`

Re the last part.
Assume I have openssl, libssh2 (depends on openssl) and curl (depends on libssh2 and zlib)

if I was to have a "sdk_requires" it would be filled like "sdk_requres=openssl/3.0.12-r0" for libssh2 and "sdk_requires=zlib/1.2.13-r0" for curl (obviously curl would have a regular self.requires for libssh2 as well).

My fear was that during package_id calculation the "sdk_requires" clause could have been calculated badly for transitive dependencies (e.g. when checking for appropriate libssh2, curl's own sdk_requires value could have confused the libssh2 package_id calculation), but I might be wrong on that :)

Afaik we can close this

**Comment by memsharded** [comment]
Thanks for the feedback.

I'd say this looks like a potential good use case for ``[platform_requires]`` or ``[replace_requires]`` explained in the blog above, and manage that with actual ``requires`` dependencies instead of custom options, which helps to track the same across the dependency graph.
