### ISSUE TITLE
[question] Force looking for the most compatible package

### ISSUE THREAD

**Issue by lo1ol** [conan-io/conan#15792]
### What is your question?

Hi,

We faced with the problem that conan doesn't look for the most compatible package and uses already downloaded compatible package, which could be not most compatible.

It may lead to some problems.

For example:

We have compatible settings for compiler versions (packages built with gcc11 are compatible for gcc13 builds).

We have packages A and B. B depends on A

We build to packages of A with profiles linux-x86_64-gcc11 and  linux-x86_64-gcc13. Then we clear cache.

if we try to build package B with profile linux-x86_64-gcc13 and then for linux-x86_64-gcc11 -- everything is ok. But if we try to build package for gcc11 firstly and after that for gcc13 profile, conan doesn't look for most compatible gcc13 package of A and uses gcc11 package.

Do you know how to force conan to look for the most compatible package version? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lo1ol 

I think this is aligned with the overall Conan behavior, prioritizing the contents of the cache and using what is there before having to check in the server. 
To check the most updated, latest, or compatible binaries in the server, the ``--update`` argument should be used. If it is used, it should resolve to that most compatible binary in the server. Can you please try it and report?

**Comment by lo1ol** [comment]
yeah, thank you!

**Comment by lo1ol** [comment]
Hi!

Default behaviour is changed? I discovered that new conan (2.0.17) tries to get updates by default

**Comment by memsharded** [comment]
> Default behaviour is changed? I discovered that new conan (2.0.17) tries to get updates by default

No, this shouldn't be the case. Cache will always be prioritized, unless ``--update`` is passed explicitly to the command line. If that is not the case, you might want to file a specific issue for it.
