### ISSUE TITLE
[question] meson cross-build 

### ISSUE THREAD

**Issue by crstzh** [conan-io/conan#15809]
### What is your question?

I am building lcms/2.16 and I use below command:
conan create all --version=2.16  -pr:b windows-build-x86_64 -pr **windows-msvc17.6.0-arm64ec**  -s build_type=Debug --build=missing
I always get below error: 
fatal error LNK1392: Incompatible object type found. Did you mean /machine:arm64x or /machine:arm64ec?

But for armv8, it works well.
conan create all --version=2.16  -pr:b windows-build-x86_64 -pr **windows-msvc17.6.0-armv8**  -s build_type=Debug --build=missing

I noticed that conan_meson_cross.ini:
for arm64ec, it is:
```
[build_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[host_machine]
system = 'windows'
cpu_family = 'arm64ec'
cpu = 'arm64ec'
endian = 'little'
```

for armv8, it is:
```
[build_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[host_machine]
system = 'windows'
cpu_family = 'aarch64'
cpu = 'armv8'
endian = 'little'
```

Then I found the below code in meson_helper, why can I not see **arm64ec** here?

_meson_cpu_family_map = {
    'armv4': ('arm', 'armv4', 'little'),
    'armv4i': ('arm', 'armv4i', 'little'),
    'armv5el': ('arm', 'armv5el', 'little'),
    'armv5hf': ('arm', 'armv5hf', 'little'),
    'armv6': ('arm', 'armv6', 'little'),
    'armv7': ('arm', 'armv7', 'little'),
    'armv7hf': ('arm', 'armv7hf', 'little'),
    'armv7s': ('arm', 'armv7s', 'little'),
    'armv7k': ('arm', 'armv7k', 'little'),
    'armv8': ('aarch64', 'armv8', 'little'),
    'armv8_32': ('aarch64', 'armv8_32', 'little'),
    'armv8.3': ('aarch64', 'armv8.3', 'little'),
    'avr': ('avr', 'avr', 'little'),
    'mips': ('mips', 'mips', 'big'),
    'mips64': ('mips64', 'mips64', 'big'),
    'ppc32be': ('ppc', 'ppc', 'big'),
    'ppc32': ('ppc', 'ppc', 'little'),
    'ppc64le': ('ppc64', 'ppc64', 'little'),
    'ppc64': ('ppc64', 'ppc64', 'big'),
    's390': ('s390', 's390', 'big'),
    's390x': ('s390x', 's390x', 'big'),
    'sh4le': ('sh4', 'sh4', 'little'),
    'sparc': ('sparc', 'sparc', 'big'),
    'sparcv9': ('sparc64', 'sparc64', 'big'),
    'wasm': ('wasm32', 'wasm32', 'little'),
    'x86': ('x86', 'x86', 'little'),
    'x86_64': ('x86_64', 'x86_64', 'little'),
    'riscv32': ('riscv32', 'riscv32', 'little'),
    'riscv64': ('riscv64', 'riscv32', 'little')
}

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @crstzh 

Thanks for reporting.

It seems that you are right, and the Meson integration is missing that architecture. Would you like to add it yourself via a PR?

**Comment by crstzh** [comment]
Sure. But yesterday I got approved to access the conan-center-index repo, but I still have a permission error to push.

**Comment by memsharded** [comment]
> Sure. But yesterday I got approved to access the conan-center-index repo, but I still have a permission error to push.


That permission is only for ``conan-center-index`` (the volume of PRs and security implications there is too high), you can already open PRs to this repo.

**Comment by crstzh** [comment]
Thank you and let me take a try,
 Is this correct?
 'arm64ec': ('aarch64', 'arm64ec', 'little'),

**Comment by memsharded** [comment]
Yes, it looks correct, but depends on Meson, I don't know enough about Meson management of this architecture.

If you are trying it locally, and you can verify manually that it works and produce the right results (checking somehow the resulting binary), please let us know in the PR, you can comment you did try locally.

**Comment by crstzh** [comment]
> Yes, it looks correct, but depends on Meson, I don't know enough about Meson management of this architecture.
> 
> If you are trying it locally, and you can verify manually that it works and produce the right results (checking somehow the resulting binary), please let us know in the PR, you can comment you did try locally.

Ok, I will follow this locally.

**Comment by crstzh** [comment]
> [msharded](/memsharded)
Hello, I want to test this locally before it's checkin , how can I change my conanfile to make meson can genarate as below:

```
[host_machine]
system = 'windows'
cpu_family = 'aarch64'
cpu = 'arm64ec'
endian = 'little'
```
Here is my conanfile generate()

```
    def generate(self):
        env = VirtualBuildEnv(self)
        env.generate()
        tc = MesonToolchain(self)
        tc.cross_build["build"]
        if self.settings.arch == "arm64ec":
             pass
        tc.generate()
```

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/15812
