### ISSUE TITLE
[question] copy gives plain AssertionError in generate()

### ISSUE THREAD

**Issue by PengZheng** [conan-io/conan#15818]
### What is your question?

I tried to work around the private linking issue (https://github.com/conan-io/conan/issues/13302) following the suggestion given (https://github.com/conan-io/conan/issues/13302#issuecomment-1584162534).

https://github.com/apache/celix/blob/1db9b858fe924e87e0290d812062636a14cd5c17/conanfile.py#L347-L351

```Python
    def generate(self):
        tc = CMakeToolchain(self)
        // omit other settings
        for dep in self.dependencies.host.values():
            if self.settings.os == "Linux":
                copy(self, "*.so*", dep.cpp_info.libdir, os.path.join(self.build_folder, "lib"))
            elif self.settings.os == "Macos":
                copy(self, "*.dylib", dep.cpp_info.libdir, os.path.join(self.build_folder, "lib"))
        tc.cache_variables["CMAKE_BUILD_RPATH"] = os.path.join(self.build_folder, "lib")
        tc.generate()
```

It runs successfully on my local machine (Ubuntu 22.04, same as the GitHub Action Image) with 
```
conan create . -c tools.cmake.cmaketoolchain:generator=Ninja -b missing -o celix/*:build_all=True  -o celix/*:enable_ccache=True -pr:b default -pr:h default -s:h build_type=Release -tf examples/conan_test_package_v2 -o celix/*:celix_cxx17=True -o celix/*:celix_install_deprecated_api=True
```

However, when runing the same command with GitHub Actions, the following error occured:

```
celix/3.0.0: Generators folder: /home/runner/work/celix/celix/release/p/b/celixad36e9f31654f/b
ERROR: celix/3.0.0: Error in generate() method, line 349
	copy(self, "*.so*", dep.cpp_info.libdir, os.path.join(self.build_folder, "lib"))
	AssertionError: 
Error: Process completed with exit code 1.
``` 

https://github.com/apache/celix/actions/runs/8171188939/job/22338881270

The whole project is available here: https://github.com/apache/celix/tree/hotfix/conan-private-dep

I have no idea of what happened. Any help will be appreciated.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PengZheng 

Thanks for your question.

You might use ``... -vvv`` to get more information about the error, it should display a full stacktrace

Also, we have already changed that assertion for a full Exception with a clearer error message, it will be in next Conan 2.2


Then I suspect that ``dep.cpp_info.libdir`` might be ``None``. If you could add a ``self.output.info()`` message before using it in ``copy()``, and then share the 2 different outputs (in CI and locally), that might have some hints. Just in case, add a ``self.output.info()`` for ``os.path.join(self.build_folder, "lib")`` value too. Thanks!

**Comment by PengZheng** [comment]
> Then I suspect that dep.cpp_info.libdir might be None. 

This is indeed the case. With an extra None test for `dep.cpp_info.libdirs`, the workaround worked as expected.

```python
        for dep in self.dependencies.host.values():
            if dep.cpp_info.libdirs:
                copy(self, "*", dep.cpp_info.libdir, os.path.join(self.build_folder, "lib"))
```

The interesting thing is that I didn't encounter the same issue on my local machine. I guess it is due to my stale conan cache.
Thank you for the prompt very helpful reply.
