### ISSUE TITLE
Change settings.yml in Conan Artifactory Jenkins Plugin

### ISSUE THREAD

**Issue by mschmid** [conan-io/conan#1581]
Hi,
I am using the Artifactory Jenkins Plugin to create Conan packages nightly.
For a cross-compiling project, I added a new OS to the settings.yml locally (called VxWorks).
How can I add a setting in the Artifactory plugin on Jenkins? As far as I see the environment is generated newly every time the plugin runs.
I also miss a command line argument to change settings by script.
Thanks in advance!

**Comment by lasote** [comment]
Conan nor the Artifactory plugin supports "live" configuring the settings.yml file. 
I think you could write the settings.yml file using groovy, probably there is a jenkins plugin that could help.

I'm not sure about the command line command, the yml file is nested and can be complex. If you can provide the syntax of how you think the command can work would be useful.

**Comment by mschmid** [comment]
This would be a suitable solution to me - I just need the path of the temporary Conan instance then. This is also a thing I could not find out yet.

**Comment by lasote** [comment]
I didn't try it but `getUserPath()` in the client instance should work. Let me know.

**Comment by memsharded** [comment]
Hi @mschmid 

You might want to check ongoing work of ``conan config install`` which might be interesting for your use case: https://github.com/conan-io/conan/pull/1705

**Comment by memsharded** [comment]
I think #1705 might be the best solution to this, so proposing it as fixed, please follow up if it is not the case. Thanks!

**Comment by memsharded** [comment]
``conan config install`` has been released in 0.27: http://docs.conan.io/en/latest/reference/commands/config.html#conan-config-install

Please try it, and give feedback, re-open or comment if necessary.
