### ISSUE TITLE
[question] Get all licenses for dependencies

### ISSUE THREAD

**Issue by h-2** [conan-io/conan#15822]
### What is your question?

I would like to track the licenses of all my dependencies. I had hoped that I would be able to achieve something like that with `conan graph build-order`, but the nice json that it prints does not contain the license information unfortunately.

What would be the recommend way to achieve this?

On a related note: when a conan package specifies multiple licenses, does that mean "logical AND" or "logical OR" or is this not specified? Some open source projects allow you to choose the license ("OR") while others contain components under different licenses ("AND").

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi! Thanks for your question.

If you only want to get the info in the `licenses` attribute, you might get this info using the `conan graph info` command, which contains the information about the current graph dependencies

As for actually extracting the licenses, the recommended way to get the dependencies' licenses would be using a deployer ([Docs here](https://docs.conan.io/2/reference/extensions/deployers.html)), they allow to extract files from the conan cache to a user specified location using custom logic

In fact, we have published a deployer as an example to be used for mostly the reason you're requesting, check https://github.com/conan-io/conan-extensions/blob/main/extensions/deployers/licenses.py for the code example.

You can check https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html for an example of a similar deployer that goes into a bit of detail what a deployer looks like.

As for the license syntax question: This is something we want to have a better model in the future, but for now the license field is not constrained by Conan itself.
Conan Center Index recipes are expected to use SPDX identifiers, and lately we've gone the route of various licenses items (`licenses = "foo", "bar"`) meaning `OR`, and for libraries with `AND` licenses, using the SPDX syntax of `licenses = "foo AND bar"`), but the change has not yet spread to every recipe there

Hope that helps :)

**Comment by h-2** [comment]
Thank you for the quick reply! This looks like a powerful mechanism, but it's a lot more than I need. I don't need the actual files, and it also seems unsafe to assume that a "licenses" folder actually exists...

I just the need the license-strings that are stored in the conanfile and a warning for every conan file that doesn't provide one. It seems that graph would be the perfect tool to output this, since it parsed the conanfile of all dependencies anyway?

**Comment by AbrilRBS** [comment]
Yes!
As I said (Sorry if you didn't see the edit, realized too late that you might have been referring to the license attribute!), you can use `conan graph info ... -f=json` to get a machine readeable representation of your graph, and for every node on the dependency graph, the `license` attribute will be populated to whatever the recipe has set :)

**Comment by h-2** [comment]
Awesome, I don't know why I was too stupid to figure that out myself!

Thanks!
