### ISSUE TITLE
[question] Failed to test a prebuilt binaries package

### ISSUE THREAD

**Issue by 5yh** [conan-io/conan#15828]
### What is your question?

**### I packaged a prebuilt binaries package "vtk/9.2" and I want to test it, but it errored.**
First I Packaged the "vtk/9.2" by following the tutorial.This is the vtk conanfile.py:

```
import os
from conan import ConanFile
from conan.tools.files import copy

class vtkRecipe(ConanFile):
    name = "vtk"
    version = "9.2"
    settings = "os", "arch"

    def layout(self):
        _os = str(self.settings.os).lower()
        _arch = str(self.settings.arch).lower()
        self.folders.build = os.path.join("vtk9.2", _os, _arch)
        self.folders.source = self.folders.build
        self.cpp.source.includedirs = ["include"]
        self.cpp.build.libdirs = ["lib"]
        self.cpp.build.bindirs = ["bin"]

    def package(self):
        local_include_folder = os.path.join(self.source_folder, self.cpp.source.includedirs[0])
        local_lib_folder = os.path.join(self.build_folder, self.cpp.build.libdirs[0])
        copy(self, "*", local_include_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*", local_lib_folder, os.path.join(self.package_folder, "lib"), keep_path=True)
        copy(self, "*", os.path.join(self.source_folder, "bin"), os.path.join(self.package_folder, "bin"), keep_path=True)
    def package_info(self):
        self.cpp_info.libs = ["vtk"]
```

VTK's bin, include, and lib are in the subfolder "./windows/x86_64".
Here is the file structure of VTK.
createVtk
-conanfile.py
-vtk9.2
--windows
---x86_64
----bin
----include
----lib

**### I used conan export-pkg command to create the package, it success:**

```
PS D:\myCode\createVtk> conan export-pkg . -s os="Windows" -s arch="x86_64"

======== Exporting recipe to the cache ========
vtk/9.2: Exporting package recipe: D:\myCode\createVtk\conanfile.py
vtk/9.2: Copied 1 '.py' file: conanfile.py
vtk/9.2: Exported to cache folder: C:\Users\赵\.conan2\p\vtk550f921268e4f\e
vtk/9.2: Exported: vtk/9.2#c159d09a8926039aabb4aa78d1971a46 (2024-03-07 02:50:42 UTC)

======== Computing dependency graph ========
Graph root
    conanfile.py (vtk/9.2): D:\myCode\createVtk\conanfile.py

======== Computing necessary packages ========

======== Installing packages ========
conanfile.py (vtk/9.2): Generating aggregated env files
conanfile.py (vtk/9.2): Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']

======== Exporting recipe and package to the cache ========
conanfile.py (vtk/9.2): Exporting binary from user folder to Conan cache
conanfile.py (vtk/9.2): Packaging to 522dcea5982a3f8a5b624c16477e47195da2f84f
conanfile.py (vtk/9.2): Generating the package
conanfile.py (vtk/9.2): Packaging in folder C:\Users\赵\.conan2\p\b\vtk37b95ddd9ebca\p
conanfile.py (vtk/9.2): Calling package()
conanfile.py (vtk/9.2): package(): Packaged 121 '.dll' files
conanfile.py (vtk/9.2): package(): Packaged 2750 '.h' files
conanfile.py (vtk/9.2): package(): Packaged 37 '.txx' files
conanfile.py (vtk/9.2): package(): Packaged 13 '.hxx' files
conanfile.py (vtk/9.2): package(): Packaged 1 file: octree
conanfile.py (vtk/9.2): package(): Packaged 65 '.hpp' files
conanfile.py (vtk/9.2): package(): Packaged 2 '.cc' files: format.cc, posix.cc
conanfile.py (vtk/9.2): package(): Packaged 116 '.lib' files
conanfile.py (vtk/9.2): Created package revision c12f5025dcb24eeac702b1201ff9f506
conanfile.py (vtk/9.2): Package '522dcea5982a3f8a5b624c16477e47195da2f84f' created
conanfile.py (vtk/9.2): Full package reference: vtk/9.2#c159d09a8926039aabb4aa78d1971a46:522dcea5982a3f8a5b624c16477e47195da2f84f#c12f5025dcb24eeac702b1201ff9f506
conanfile.py (vtk/9.2): Package folder C:\Users\赵\.conan2\p\b\vtk37b95ddd9ebca\p
conanfile.py (vtk/9.2): Exported package binary

PS D:\myCode\createVtk> conan list vtk
Local Cache
  vtk
    vtk/9.2
```

### **Then I want to test the package with a simple example:**

file structure:
useVtkDemo
-src
--example.cpp
-CMakeLists.txt
-conanfile.py

**conanfile.py:**
```
import os

from conan import ConanFile
from conan.tools.cmake import CMake, cmake_layout
from conan.tools.build import can_run


class helloTestConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires(self.tested_reference_str)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def layout(self):
        cmake_layout(self)

    def test(self):
        if can_run(self):
            cmd = os.path.join(self.cpp.build.bindir, "example")
            self.run(cmd, env="conanrun")
```

**CMakeLists.txt:**
```
cmake_minimum_required(VERSION 3.15)
project(PackageTest CXX)

find_package(vtk CONFIG REQUIRED)



add_executable(example src/example.cpp)
target_link_libraries(example vtk::vtk)
```

**example.cpp:**
```
#include"vtkUnstructuredGridWriter.h"
#include <vector>
#include <string>

int main() {
    std::vector<std::string> vec;
    vec.push_back("test_package");

}
```

**### I used conan test I the folder, it errored:**
```
PS D:\myCode\useVtkDemo> conan test . vtk/9.2

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Launching test_package ========

======== Computing dependency graph ========
Graph root
    vtk/9.2 (test package): D:\myCode\useVtkDemo\conanfile.py
Requirements
    vtk/9.2#c159d09a8926039aabb4aa78d1971a46 - Cache

======== Computing necessary packages ========
Requirements
    vtk/9.2#c159d09a8926039aabb4aa78d1971a46:522dcea5982a3f8a5b624c16477e47195da2f84f#c12f5025dcb24eeac702b1201ff9f506 - Cache

======== Installing packages ========
vtk/9.2: Already installed! (1 of 1)

======== Testing the package ========
Removing previously existing 'test_package' build folder: D:\myCode\useVtkDemo\build\msvc-193-x86_64-14-release
vtk/9.2 (test package): Test package build: build\msvc-193-x86_64-14-release
vtk/9.2 (test package): Test package build folder: D:\myCode\useVtkDemo\build\msvc-193-x86_64-14-release
vtk/9.2 (test package): Writing generators to D:\myCode\useVtkDemo\build\msvc-193-x86_64-14-release\generators
vtk/9.2 (test package): Generator 'CMakeToolchain' calling 'generate()'
vtk/9.2 (test package): CMakeToolchain generated: conan_toolchain.cmake
vtk/9.2 (test package): CMakeToolchain generated: CMakePresets.json
vtk/9.2 (test package): CMakeToolchain generated: ..\..\..\CMakeUserPresets.json
vtk/9.2 (test package): Generator 'CMakeDeps' calling 'generate()'
vtk/9.2 (test package): Generating aggregated env files
vtk/9.2 (test package): Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']

======== Testing the package: Building ========
vtk/9.2 (test package): Calling build()
vtk/9.2 (test package): Running CMake.configure()
vtk/9.2 (test package): RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="D:/myCode/useVtkDemo/build/msvc-193-x86_64-14-release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="D:/myCode/useVtkDemo" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "D:\myCode\useVtkDemo"
-- Using Conan toolchain: D:/myCode/useVtkDemo/build/msvc-193-x86_64-14-release/generators/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 14 with extensions OFF
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22631.
-- The CXX compiler identification is MSVC 19.39.33519.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'vtk::vtk'
CMake Error at build/msvc-193-x86_64-14-release/generators/cmakedeps_macros.cmake:67 (message):
  Library 'vtk' not found in package.  If 'vtk' is a system library, declare
  it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  build/msvc-193-x86_64-14-release/generators/vtk-Target-release.cmake:24 (conan_package_library_targets)
  build/msvc-193-x86_64-14-release/generators/vtkTargets.cmake:26 (include)
  build/msvc-193-x86_64-14-release/generators/vtk-config.cmake:16 (include)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!

*********************************************************
Recipe 'vtk/9.2 (test package)' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: vtk/9.2 (test package): Error in build() method, line 17
        cmake.configure()
        ConanException: Error 1 while executing
```
### 
**Is there anything wrong during my packaging steps or using steps?**

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @5yh 

Thanks for your question.

I think the issue seems very related to:

```
def package_info(self):
        self.cpp_info.libs = ["vtk"]
```
It could be that there is not enough information there to represent the package. So when ``CMakeDeps`` in the consumer side generates the information for the ``vtk::vtk`` target, it will not have enough information to know what to do.

There are some things that can be done to debug this:
- In your ``test_package/D:/myCode/useVtkDemo/build/msvc-193-x86_64-14-release/generators`` check for your ``vtk-....-data.cmake`` file and check its contents. It should contain definitions of _INCLUDEDIRS, _LIBDIRS, etc, that should be pointing to the folders containing the right files, you can open the folders and verify it
- It is important that the library itself is called ``vtk.lib`` or something like this, if not the ``package_info()`` should be changed. 
- Can the files from ``./windows/x86_64`` actually be downloaded from a place that we could get them and reproduce?



Some other notes:

- The `` def test(self):`` method is only for the Conan ``test_package`` functionality.
- Specifically, the ``self.requires(self.tested_reference_str)`` only works when it is a ``test_package`` or used with the ``conan test`` command.
- It looks like you can take the ``useVtkDemo`` and put it as a ``test_package`` folder inside ``createVtk``. That will run the test automatically for you when you run the ``conan export-pkg`` 
- If there are many other static and dynamic libs inside the package, it might be necessary to also list them in ``cpp_info.libs``
- It might be very recommended to define a ``package_type = `` in your recipe, to define if it is a shared library, a static library, etc.
- You might want to add a ``build_policy = "never"`` to explicitly say that this package cannot be ``--build`` or ``conan create`` it

**Comment by memsharded** [comment]
Also, if what you would like is to use some ``xxx-config.cmake`` packaged inside the package instead of defining ``package_info()``, please have a look to https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html

**Comment by 5yh** [comment]
Thank you for your response. I checked the file: vtk-release-x86_64-data.cmake. It does contain the variables vtk_INCLUDE_DIRS_RELEASE, LIBDIRS, etc., and they all point to the correct Conan package cache.

However, the library itself isn’t called vtk.lib. In the include directory, there are thousands of xxx.h files and subdirectories containing other xxx.h files. In the bin directory, there are hundreds of xxx.dll files. In the lib directory, libraries are named as ‘vtkxxx.lib’.

Should I list all of them in conanfile.py?

Here is the vtk9.2 zip file.
[vtk9.2.zip](https://github.com/conan-io/conan/files/14552914/vtk9.2.zip)

There is a program that uses vtk before, its CMakeLists.txt uses vtk like(vtk codes are in the ** lines):

```
cmake_minimum_required(VERSION 3.13)

# options
option(BUILD_SHARED_LIBS "Build the shared library" OFF)
option(BUILD_ZFMESH_EXECUTABLE "Build test executable" ON)

# cxx standard
set(CMAKE_CXX_STANDARD 11)

# project zgrid_meshdata
project(zfMesh)

file(GLOB_RECURSE HEADER_FILES include/*.h) 
file(GLOB_RECURSE SOURCE_FILES src/*.cpp)
set(ZFMESH_SOURCES
    ${HEADER_FILES}
    ${SOURCE_FILES}
)

find_package(Eigen3 REQUIRED)
message("Eigen3_INCLUDE_DIRS = ${Eigen3_INCLUDE_DIRS}")
include_directories(${Eigen3_INCLUDE_DIRS})
#message(STATUS "HEADER_FILES:${HEADER_FILES}")
#message(STATUS "SOURCE_FILES:${SOURCE_FILES}")

**set(VTKLibDir ${CMAKE_CURRENT_SOURCE_DIR}/extern/vtk9.2/lib/)
set(VTKSharedLibDir ${CMAKE_CURRENT_SOURCE_DIR}/extern/vtk9.2/bin/)
set(VTKIncludeDir ${CMAKE_CURRENT_SOURCE_DIR}/extern/vtk9.2/include/)
file(GLOB VTKlibs ${VTKLibDir}/*.lib)
file(GLOB VTKSharedlibs ${VTKSharedLibDir}/*.dll)**

add_library(zfMeshLib STATIC ${ZFMESH_SOURCES})
#add_subdirectory(DataManager)

**target_link_libraries(zfMeshLib PUBLIC ${VTKlibs})**
target_link_libraries(zfMeshLib PUBLIC ZFG_DataManager)
target_link_libraries(zfMeshLib PUBLIC  ${CMAKE_CURRENT_SOURCE_DIR}/extern/tigerlib/smesh/lib/SmeshGen_lib_d.lib)
#target_link_libraries(zfMeshLib PUBLIC  ${CMAKE_CURRENT_SOURCE_DIR}/extern/tigerlib/smesh/lib/SmeshGen_lib_r.lib)
target_link_libraries(zfMeshLib PUBLIC  ${CMAKE_CURRENT_SOURCE_DIR}/extern/tigerlib/dt3d/dt.lib)
target_link_libraries(zfMeshLib PUBLIC  ${CMAKE_CURRENT_SOURCE_DIR}/extern/tigerlib/sizefunction/adaSurfSizing_new.lib)
**target_include_directories(zfMeshLib PUBLIC include 
${CMAKE_CURRENT_SOURCE_DIR}/../
${VTKIncludeDir} 
${CMAKE_CURRENT_SOURCE_DIR}/extern/tigerlib/smesh/inc/
${CMAKE_CURRENT_SOURCE_DIR}/extern/tigerlib/
${CMAKE_CURRENT_SOURCE_DIR}/../zfgrid_geometry/)**

# set group for vs .sln
if(MSVC)
    source_group(include FILES ${HEADER_FILES})
    source_group(src FILES ${SOURCE_FILES})
    set_target_properties(zfMeshLib PROPERTIES FOLDER ZFMesh)
endif()

# zfMesh Exe
add_subdirectory(test)
```

Maybe I should change the CMakeLists.txt structure to contain vtk9.2's bin, include , lib?
I will try it.

**Comment by memsharded** [comment]
Thanks, that clarifies a bit.

If you had only a few libraries, you could do something like:

```python
def package_info(self):
    self.cpp_info.libs = [f"vtksys-{self.version}",  ...]
```

Given that you have a lot of them, you could list them explicitly, or maybe you want to try the automatic ``collect_libs()``: https://docs.conan.io/2/reference/tools/files/basic.html#conan.tools.files.collect_libs (note that ``collect_libs`` do not order the libraries, so if a specific linkage order is needed, then it will not work.

If linkage order is necessary, I'd go for something like:
```python
def package_info(self):
    vtk_libs = ["vtksys", "vtkChartsCore", ....]  # My list in order
    self.cpp_info.libs = [f"{lib}-{self.version}" for lib in vtk_libs]
```

In general, I'd try to avoid patching the library code or build scripts if not strictly necessary, if the conanfile.py can model the package contents, no need to patch or change the CMakeLists

**Comment by 5yh** [comment]
:) Thanks a lot, I used self.cpp_info.libs to add libs and it succeed in collecting libs.
Here is my new export package's conanfile:
```
import os
from conan import ConanFile
from conan.tools.files import copy
from conan.tools.files import collect_libs

class vtkRecipe(ConanFile):
    name = "vtk"
    version = "9.2"
    settings = "os", "arch"
    build_policy = "never"
    # exports = "bin*", "include*", "lib*"

    def layout(self):
        _os = str(self.settings.os).lower()
        _arch = str(self.settings.arch).lower()
        self.folders.build = os.path.join("vtk9.2", _os, _arch)
        print("--------------------------------------------------")
        print(self.folders.build)
        self.folders.source = self.folders.build
        self.cpp.source.includedirs = ["include"]
        self.cpp.build.libdirs = ["lib"]
        self.cpp.build.bindirs = ["bin"]
        
        

    def package(self):
        local_include_folder = os.path.join(self.source_folder, self.cpp.source.includedirs[0])
        local_lib_folder = os.path.join(self.build_folder, self.cpp.build.libdirs[0])
        print("*************************")
        copy(self, "*", local_include_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*", local_lib_folder, os.path.join(self.package_folder, "lib"), keep_path=True)
        copy(self, "*", os.path.join(self.source_folder, "bin"), os.path.join(self.package_folder, "bin"), keep_path=True)
    def package_info(self):
        self.cpp_info.libdirs = ["lib"]  # Default value is 'lib'
        self.cpp_info.libs = collect_libs(self)
        self.cpp_info.bindirs=["bin"]
```
      
After I exported the vtk/9.2, I tried to use it in useVtkDemo.

This is the `CMakeLists.txt` of useVtkDemo:
```
cmake_minimum_required(VERSION 3.15)
project(PackageTest CXX)

find_package(vtk CONFIG REQUIRED)



message("VTK Include Directories: ${vtk_INCLUDE_DIRS_RELEASE}")
message("${vtk_LIB_DIRS_RELEASE}")
message("${vtk_BIN_DIRS_RELEASE}")




add_executable(example src/example.cpp)

target_link_libraries(example vtk::vtk)

```

`conanfile.py` of useVtkDemo, I use `conan test . vtk/9.2` command to test it ,so `def test` can be used:

```
import os

from conan import ConanFile
from conan.tools.cmake import CMake, cmake_layout
from conan.tools.build import can_run


class helloTestConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires("vtk/9.2")

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def layout(self):
        cmake_layout(self)

    def test(self):
        if can_run(self):
            cmd = os.path.join(self.cpp.build.bindir, "example")
            self.run(cmd, env="conanrun")

```
When compiling, it successfully detected the **libs** and finished compilation.
However, I can't use **bins, or dlls** with conan, despite I packaged bins before. I also define `self.cpp_info.bindirs=["bin"] ` in package_info. 
I check `vtk-release-x86_64-data.cmake` file and I find that `set(vtk_BIN_DIRS_RELEASE )` is empty.
I am wondering how do conan manage bins in packages?Are there any mistakes in my config files?

**Comment by memsharded** [comment]
Conan uses 2 concepts to model dependencies:
- ``package_type``: https://docs.conan.io/2/reference/conanfile/attributes.html#package-type
- ``requirement traits``: https://docs.conan.io/2/reference/conanfile/methods/requirements.html#requirement-traits

In this case you are not specifying with any what is your dependency, and then Conan is not adding the dependency ``bindirs`` to the generated ``VirtualBuildEnv`` and ``VirtualRunEnv`` (files ``conanbuild.bat`` and ``conanrun.bat``)

If for example you specify ``package_type = "shared-library"`` in your vtk recipe, it should start adding its path to the ``conanrun.bat``, and then execution via ``self.run(..., env="conanrun")`` will activate it. Note this is not a CMake thing, because CMake is only at build time, but this is a runtime thing outside of CMake.

**Comment by 5yh** [comment]
I added `package_type = "shared-library"` to my recipe, and Conan successfully set the environment variables for the binaries. Now it works!
Thank you for your patient and thorough responses. Your help has been invaluable!
I believe the issue can be closed now.

**Comment by memsharded** [comment]
Excellent! Happy to help 🙂 

Do not hesitate to create new tickets for any further question or issue that you might have. Thanks for the feedback!

**Comment by aiyolo** [comment]
How can I create package with debug and release dll?

**Comment by memsharded** [comment]
@aiyolo You can put inside a Conan package whatever you like. But it is very discouraged to add different configuration binaries in the same package binary, Conan implements one different binary for each configuration, including Debug/Release, but also any other variant, and all the tooling and processes are designed around that.

For example you would need to have a build that build both variants. That means that all dependencies of that package should also contain both Release/Debug variants, which is not true for ConanCenter packages. So it would be needed to modify all the dependencies recipes to be multi-config too. Then, the default ``cmake.configure()``, ``cmake.build()`` methods are intended to build 1 config, so this might need some tweaking too. Then, the ``package_info()`` is also not designed to model multiple variants inside the same package, so a lot of the generators code will not be useful for this purpose, and it would be needed to use other strategy.

**Comment by aiyolo** [comment]
To make my question more clear, I have a local prebuilt opencv library. The folder structure is:

![Image](https://github.com/user-attachments/assets/2261a660-f7a5-41d0-8bfe-c6b4abc4c54a)

this library has a debug dll and a release dll.

I create a conanfile.py beside the folder in order to package it in conan cache
```
import os
from conan import ConanFile
from conan.tools.files import copy


class helloRecipe(ConanFile):
    name = "opencv_enhanced"
    version = "0.1"
    settings = "build_type"

    def layout(self):
        self.folders.build = "opencv_enhanced" 
        self.folders.source = self.folders.build
        self.cpp.source.includedirs = ["include"]
        self.cpp.build.libdirs = ["x64/vc16/lib"]
        self.cpp.build.bindirs = ["x64/vc16/bin"]

    def package(self):
        local_include_folder = os.path.join(self.source_folder, self.cpp.source.includedirs[0])
        local_lib_folder = os.path.join(self.build_folder, self.cpp.build.libdirs[0])
        local_bin_folder = os.path.join(self.build_folder, self.cpp.build.bindirs[0])
        copy(self, "*.h", local_include_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.hpp", local_include_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.lib", local_lib_folder, os.path.join(self.package_folder, "lib"), keep_path=True)
        copy(self, "*.dll", local_bin_folder, os.path.join(self.package_folder, "bin"), keep_path=True)

    def package_info(self):
        if self.settings.build_type == "Debug":
            self.cpp_info.libs = ["opencv_world3414d"]
        else:
            self.cpp_info.libs = ["opencv_world3414"]
```
Then I run the following commands to create two different configuration for this libary.
```
conan export-pkg .
conan export-pkg . -s build_type=Debug
```
I have two Conan cache folders, each containing both debug and release DLLs, which is redundant.
In the package() method, should I only copy the binaries relevant to the current build_type?
Additionally, due to unfamiliarity with this process, I ran the conan export-pkg command multiple times before successfully packaging the library. This caused my Conan cache to accumulate many OpenCV-prefixed failure folders. How can I clean up and remove these previous failed packages?

**Comment by memsharded** [comment]
> In the package() method, should I only copy the binaries relevant to the current build_type?

yes, exactly, you need to condition your ``package()`` method on the ``self.settings.build_type``, to copy exclusively the libraries for the specific ``build_type`` and not all.


> Additionally, due to unfamiliarity with this process, I ran the conan export-pkg command multiple times before successfully packaging the library. This caused my Conan cache to accumulate many OpenCV-prefixed failure folders. How can I clean up and remove these previous failed packages?

the ``conan cache clean`` is what you are looking for to remove temporary folders that didn't succeed.

**Comment by aiyolo** [comment]
Thanks for your reply. But after I run `conan cache clean`, there is nothing changed.
![Image](https://github.com/user-attachments/assets/2e6a357c-352b-47be-b889-5d7a9aacf9e2)

**Comment by memsharded** [comment]
But you can have different revisions too
What is the output of ``conan list "opencv*#*:*"``?

**Comment by aiyolo** [comment]
This is the output, I want to keep the last two, and remove other package. 
```
PS C:\Users\zhu\project\qiaoyi\use_pkg> conan list "opencv*#*:*"
Found 1 pkg/version recipes matching opencv* in local cache
Local Cache
  opencv_enhanced
    opencv_enhanced/0.1
      revisions
        3119de5c93d09d78c349489ff70b57a4 (2025-01-25 04:15:13 UTC)
          packages
            522dcea5982a3f8a5b624c16477e47195da2f84f
              info
                settings
                  arch: x86_64
                  os: Windows
        185bc0c5168732543e89a984f5251a8b (2025-01-25 04:18:06 UTC)
          packages
            522dcea5982a3f8a5b624c16477e47195da2f84f
              info
                settings
                  arch: x86_64
                  os: Windows
        0c4b1169350d23302ab42567879f9720 (2025-01-25 04:19:05 UTC)
          packages
            522dcea5982a3f8a5b624c16477e47195da2f84f
              info
                settings
                  arch: x86_64
                  os: Windows
        f0dd5ee3d74e9902f269bedcb12f51e9 (2025-01-25 04:26:24 UTC)
          packages
            522dcea5982a3f8a5b624c16477e47195da2f84f
              info
                settings
                  arch: x86_64
                  os: Windows
        4e2018a4b55f9d33cb615b99e31ce9a9 (2025-01-25 15:06:36 UTC)
          packages
            522dcea5982a3f8a5b624c16477e47195da2f84f
              info
                settings
                  arch: x86_64
                  os: Windows
        8261a16428c91084a2199dfc43e39023 (2025-01-25 15:10:18 UTC)
          packages
            9e186f6d94c008b544af1569d1a6368d8339efc5
              info
                settings
                  build_type: Debug
            efa83b160a55b033c4ea706ddb980cd708e3ba1b
              info
                settings
                  build_type: Release
```

**Comment by memsharded** [comment]
You can remove the revisions you want with ``conan remove pkg/version#revision``

It is also possible to remove all previous revisions except the latest with ``conan remove "pkg/version#~latest"``

If you want to keep the last 2 revisions, you need to iterate the first way for every revision you want to remove.
