### ISSUE TITLE
[question] About 'package_folder' of editable packages.

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#15820]
### What is your question?
What is the value of `package_folder` supposed to be for a module when it is built locally?

### Environment details

* Conan version: **2.1.0**
* Python version: **3.11.2**

### Description

Hi,
What is the value of `package_folder` supposed to be for a module when it is built locally?

The answer is not so obvious to me as it should be.
We would say that [package_folder](https://docs.conan.io/2/reference/conanfile/attributes.html#package-folder) is not needed because there is no execution of the [package](https://docs.conan.io/2/reference/conanfile/methods/package.html#package) method.

But if the module is put in _editable mode_ it may also get built locally when doing a:
```
conan install -b editable .
```
for another module that depends on it.
I'm just experimenting with a dependency whose _conanfile_ defines a build method like this:
```
def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        cmake.install()
```
and looking at the implementation of [cmake.install](https://github.com/conan-io/conan/blob/4dd2891d7672046815bd3b6181699f7111ec2dea/conan/tools/cmake/cmake.py#L206) it seems that in this case `package_folder` is needed at build stage too.

Thank you in advance for any clarification.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @marausch 

Thanks for your question

> What is the value of package_folder supposed to be for a module when it is built locally?

It is ``None``. When built locally there is no package at all, just a build tree.

> and looking at the implementation of [cmake.install](https://github.com/conan-io/conan/blob/4dd2891d7672046815bd3b6181699f7111ec2dea/conan/tools/cmake/cmake.py#L206) it seems that in this case package_folder is needed at build stage too.

This is the reason the ``cmake.install()`` does not belong to the ``build()`` method, but to the ``package()`` method.

If you move it to the ``package()`` method and there is a correct ``layout()`` defined (the example from ``conan new cmake_lib`` should work out of the box), then the ``editable`` should work with ``--build=editable``

**Comment by marausch** [comment]
> cmake.install() does not belong to the build() method, but to the package() method.

This is the point!
I wasn't considering that it is not allowed anymore to call `cmake.install` from `build()` (it's a remnant of my previous _Conan **1.x**_ implementation).

Thank you.

**Comment by memsharded** [comment]
> I wasn't considering that it is not allowed anymore to call cmake.install from build() (it's a remnant of my previous Conan 1.x implementation).

It might be used if not using ``editables`` or local flow at all, so it is not that it is always completely forbidden. This is why Conan 2 it is not raising a hard exception for doing it, we thought it was better to keep kind of allowing it, and only if users want to use the local flow, they must move it to the ``package()`` method.
