### ISSUE TITLE
[question] how to make Conan use the correct recipe revision for a dependency, based on that dependency's options?

### ISSUE THREAD

**Issue by wuziq** [conan-io/conan#15827]
### What is your question?

When I am building a package, is there a way to make Conan use the correct recipe revisions for my package's dependencies based on the options I provide for those dependencies?

Scenario:

* Using Conan 1.62.  Open to using Conan 2, if it matters.
* Revisions are enabled.
* Package ID mode is `package_revision_mode`.
* libA takes a long time to build.
* libA has an option, `useLibB`.  In its conanfile.py, I set `useLibB` to false, then I create and upload to the remote.  Then I modify conanfile.py, setting `useLibB` to true, then I create and upload to the remote.
* On the remote, I can see there are two recipe revisions for libA, each containing one package.  So far so good.
* I want to create libC, which depends on libA.  Specifically, I want to use the libA whose option `useLibB` is false:  `conan install . -o libA:useLibB=False`.  Conan gives me "ERROR:  Missing binary".  If I specify `--build=missing`, then libA is rebuilt, and its resulting package ID is the same as the one that already exists in the remote for the recipe whose `useLibB` is false.

So, when I am building libC, is there a way to make Conan use the recipe revision for libA based on the `libA:useLibB=False` option I provided?

More generally, what are the best practices for this scenario, with regards to:
* creating libA and its different flavors?
* consuming one flavor or another of libA?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @wuziq 

Thanks for your question

I think what you are looking for is lockfiles. Please have a look to https://docs.conan.io/2/tutorial/versioning/lockfiles.html

Lockfiles have improved a lot and are way easier to manage in Conan 2, so if you plan to use them, I'd encourage to try to update to Conan 2.

>  Then I modify conanfile.py, setting useLibB to true, then I create and upload to the remote.

This is not recommended. Do not modify recipes to change options values, the way to change options values is to change the command line ``-o mypkg/*:myoption=value`` (or better, in the profiles), but not editing the ``conanfile``

> package_revision_mode

In Conan 2 this mode has dropped, it is not intended to have more than 1 package revision, because it shouldn't be necessary.

**Comment by wuziq** [comment]
Got it, makes sense.  Thank you!

> > package_revision_mode
> 
> In Conan 2 this mode has dropped, it is not intended to have more than 1 package revision, because it shouldn't be necessary.

I'm not quite sure I understand why it's not necessary.  We want to be sure we handle ABI compatibility issues correctly. 
 Admittedly I haven't researched Conan 2 - is there some documentation that can help me to understand this?  Is there a different mode we should be using instead?

**Comment by memsharded** [comment]
> I'm not quite sure I understand why it's not necessary. We want to be sure we handle ABI compatibility issues correctly.
Admittedly I haven't researched Conan 2 - is there some documentation that can help me to understand this? Is there a different mode we should be using instead?

Yes, binaries are fully defined by:
- Recipe revision: captures all the sources variations
- Package_id: captures all the configuration (settings, options, deps) variations

For every recipe-revision + package_id it is necessary to build that binary only once. Re-building again for the same recipe-revision+package-id if a previous binary exist is a model error, if nothing changes in the inputs, re-building the binary is a waste of resources and discouraged.

The binary model is explained in https://docs.conan.io/2/reference/binary_model.html

**Comment by wuziq** [comment]
Thank you!
