### ISSUE TITLE
Packager should not warn if no files are copied in expected scenarios

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#1582]
conans/client/packager.py:46 currently fires a warning if no files are copied. Usually this makes sense, because if no files are copied then your package is empty, which is probably not what had been intended.

However, when ```no_copy_source``` is set and there is no ```build()``` method defined, it makes sense that there would be nothing to copy from the second call to package for the items from the build folder. (A case where this might happen, for example, is a template library in which only header files exist.) In this scenario, the output is several lines saying package() copied a bunch of files, followed immediately by a line saying ```package(): WARN: No files copied!```. This is (1) confusing, and (2) potentially alarming. Especially for developers who prefer to treat warnings as errors, this warning will desensitize users to real problems.

I think the package() step should suppress that warning in the case where ```no_copy_source``` is set and there is no build step, though maybe there are other cases where it needs to be suppressed as well. Preferably, the warning _would_ still occur if neither call to package() resulted in any copied files.

**Comment by memsharded** [comment]
Agree, this should be improved. Not assigning it to next 0.26 release, because it is already quite full, but labeling as easy, maybe some contributor can help with this.

**Comment by memsharded** [comment]
Released in http://docs.conan.io/en/latest/conan1.0.html 
Thanks for the feedback!
