### ISSUE TITLE
[question] Regarding user defined cmake toolchain files in addition to profiles

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#15821]
### What is your question?

Hi I have a question regarding cmake toolchain files. I had raised this earlier :https://github.com/conan-io/conan/issues/15144 .
But today I ran into issues where some variables like 
CMAKE_SYSTEM_NAME and CMAKE_SYSTEM_PROCESSOR were not set correctly. It was set to my Windows machine which is my build machine. It seems to me that somehow setting it like : https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/inject_cmake_variables.html leads to an issue where cross compilation use-case does not work.
Could it be related to this : https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#cross-building ?
I have the profile with contents as:
```
[conf]
tools.cmake.cmaketoolchain:user_toolchain+={{profile_dir}}/common.cmake
```
and common.cmake contents as:
```
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
set(CMAKE_C_FLAGS_RELEASE          "${CMAKE_C_FLAGS}")
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

Thanks for your question.

It is not very clear what could be happening. It would be necessary to have something that we can reproduce, maybe starting from a ``conan new cmake_lib -d name=hello -d version=0.1`` and doing some minimal modifications and adding those profiles is it possible to have something reproducible?

**Comment by maitrey** [comment]
It looks like cmake has not set something with respect to cross building. When I inspect the conan_toolchain.cmake, 
```
# Cross building
set(CMAKE_SYSTEM_NAME RTOS)
set(CMAKE_SYSTEM_PROCESSOR KDP)
```
is missing after adding the conf to profiles.
```
{% set target_host = "C:/tools/bin/ppc" %}
{% set standalone_toolchain = "C:/tools/ppc/bin" %}

[settings]
os=RTOS
arch=KDP
compiler=ppc-gcc
compiler.version=1.4
build_type=Release

[buildenv]
PATH+=(path){{standalone_toolchain}}
PATH+=(path)C:/tools/MinGW/4.8.1/bin
PATH+=(path)C:/tools/CMake/bin
CC={{target_host}}-gcc.exe
LD={{target_host}}-gcc.exe
AR={{target_host}}-ar.exe
AS={{target_host}}-as
CFLAGS=-O2 -W -Wall -Weabi-alignment-violation=2 -Wcast-align -Wcast-qual -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wfloat-equal -Wredundant-decls -Wstrict-prototypes -Wundef -Wunsuffixed-float-constants -mversion-info  
CFLAGS_RELEASE=-O2 -W -Wall -Weabi-alignment-violation=2 -Wcast-align -Wcast-qual -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wfloat-equal -Wredundant-decls -Wstrict-prototypes -Wundef -Wunsuffixed-float-constants -mversion-info
LDFLAGS=-lgcc -mcpu=KDP -mfixed-sda

[conf]
tools.cmake.cmaketoolchain:user_toolchain+={{profile_dir}}/common.cmake
```
The common.cmake contains:
```
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
set(CMAKE_C_FLAGS_RELEASE          "${CMAKE_C_FLAGS}")
```
If I remove the conf part it recognizes the cross building scenario and sets the variables correctly i.e.
set(CMAKE_SYSTEM_NAME RTOS)
set(CMAKE_SYSTEM_PROCESSOR KDP)

**Comment by memsharded** [comment]
Oh, I see.

I'd say this is expected.

If the ``user_toolchain`` is defined, then it allows the user to define whatever important toolchain variables like ``CMAKE_SYSTEM_NAME`` and ``CMAKE_SYSTEM_PROCESSOR``. This is done this way because otherwise, the users that wanted to define their own configuration in their user toolchain.cmake files, they couldn't, because the Conan generated toolchain coming later was overwriting it.

So if ``user_toolchain`` is defined, there are 2 options:
- Add those variables in your own ``common.cmake``
- Define ``tools.cmake.cmaketoolchain:system_name, tools.cmake.cmaketoolchain:system_version, tools.cmake.cmaketoolchain:system_processor`` in your ``conf`` to set the values.

Please try that and let us know.

**Comment by maitrey** [comment]
Hi @memsharded ,
Thank you for your reply.
Both approaches work but are there any side effects to either of them that must also be considered while choosing any one approach ?
Is there anything else that needs to be taken care of?

**Comment by memsharded** [comment]
I don't see in code any other special side effect, the only place where the ``user_toolchain`` is checked is exactly that one to deactivate the code that defines ``system_name, system_version, system_processor``, so the Conan definitions don't overwrite the ``user_toolchain`` ones. 
Likewise, ``tools.cmake.cmaketoolchain:system_name`` and the others are only used also in that context.

So I'd say there is nothing else to take care of.

**Comment by maitrey** [comment]
Thanks for fast reply! Ticket can be closed.
