### ISSUE TITLE
[bug] Conan Assert after canceled conan Install

### ISSUE THREAD

**Issue by MichalCermakx** [conan-io/conan#15839]
### Environment details

* Operating System+version:
Windows 11
* Compiler+version:
NA
* Conan version:
2.1.0
* Python version:
3.12.2

### Steps to reproduce

Hi Conan team,
I hard-closed the cmd window with the execution of conan install when it was downloading packages from Artifactory.
Subsequent Conan install ended with Assert (See attached picture), and the only way to fix it is to call conan remove this package.
![image](https://github.com/conan-io/conan/assets/67799654/bb798421-a6b4-40f0-b190-6e4af8ebf983)

It would be ideal if conan install could recover from previously failed/interrupted installs.

Thank you.

**Comment by memsharded** [comment]
Hi @MichalCermakx 

Thanks for your report.

Conan already has a lot of ".dirty" state management to recover gently from this kind of errors, but it seems you could have hit a case that is not protected.

If you could please share the stack as text, not as image, that help us to check it better, copy fragments and search them in codebase, etc., that would be nice.

**Comment by MichalCermakx** [comment]
Here it is. It is another package, but it has the same error:

```
  File "D:\.conan2\p\titan227a0c3e69778\p\Lib\site-packages\conan\cli\cli.py", line 281, in main
    cli.run(args)
  File "D:\.conan2\p\titan227a0c3e69778\p\Lib\site-packages\conan\cli\cli.py", line 191, in run
    command.run(self._conan_api, args[0][1:])
  File "D:\.conan2\p\titan227a0c3e69778\p\Lib\site-packages\conan\cli\command.py", line 142, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\.conan2\p\titan227a0c3e69778\p\Lib\site-packages\conan\cli\commands\install.py", line 72, in install
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "D:\.conan2\p\titan227a0c3e69778\p\Lib\site-packages\conan\api\subapi\install.py", line 26, in install_binaries
    installer.install(deps_graph, remotes, install_order=install_order)
  File "D:\.conan2\p\titan227a0c3e69778\p\Lib\site-packages\conans\client\installer.py", line 259, in install
    self._handle_package(package, install_reference, handled_count, package_count)
  File "D:\.conan2\p\titan227a0c3e69778\p\Lib\site-packages\conans\client\installer.py", line 335, in _handle_package
    assert os.path.isdir(pkg_folder), "Pkg '%s' folder must exist: %s" % (str(pref), pkg_folder)
AssertionError: Pkg 'ngaims-tests/feature_ngaims_7006__2023_11_09_14.37.55_93f7d921:f96e8d271f3ac77ff706bc011c839f457c3b4ce9' folder must exist: D:\.conan2\p\ngaime0327f1a1948a\p
```

**Comment by memsharded** [comment]
What are the previous messages before the stacktrace?
Is it possible that it prints ``Already installed! (# of total)'``?

**Comment by MichalCermakx** [comment]
Here is a full log. There are 2 conan install . runs. First was killed in the middle via Windows Task manager. Second ends with the assert.
[ConanInstallAssert.log](https://github.com/conan-io/conan/files/14539848/ConanInstallAssert.log)

**Comment by memsharded** [comment]
Excellent, that helps, thanks.

I have been having a look to the code and improvement possibilities.
It seems that this would need a large refactor of the Conan internal "dirty" mechanism control, possible to move it to a DB table.
This would be too much at the moment for this issue, it is kind of expected that interruptions/kills of the process might leave at some point the cache corrupted, and the only way to recover would be the ``conan remove`` or cleaning the cache, as it is virtually impossible to cover all potential points of failure.

We have planned for future roadmap to improve the concurrency of the cache, this is the ticket for tracking progress there: https://github.com/conan-io/conan/issues/15840. The concurrency will need to re-consider and refactor the "dirty" mechanism, so this will probably improve when the concurrency is addressed.

I am closing this ticket, to follow https://github.com/conan-io/conan/issues/15840 instead.

In the meantime, please use the ``conan remove`` to remove corrupted packages after crashes and interruptions that Conan didn't manage to recover by itself. Many thanks for the feedback!

**Comment by thorsten-klein** [comment]
+1. We run into this issue as well.
PS: The issue might be related to #19178.
