### ISSUE TITLE
Support "WindowStore" as an os setting value

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#1584]
"Universal Windows" is a platform offered by Microsoft featuring apps built on top of WinRT with the ability for users to run the same apps on both tablet and PC (these are the so-called Windows Store apps). UW acts as a separate platform because it has strict requirements over the packaging, signing etc and applications may only use the WinRT API, not the traditional Win32 (at least I'm not aware of easy ways to break out of that sandbox). Also, you can't run UWP apps on anything older than Windows 10. CMake added support for this platform as `CMAKE_SYSTEM_NAME=WindowsStore`. I suggest using the same identifier to avoid confusion. By "support" I only mean for the platform to be added by default to the settings.yml.

More information:

  * https://docs.microsoft.com/en-us/windows/uwp/layout/design-and-ui-intro
  * http://floooh.github.io/2016/08/20/uwp.html

**Comment by SSE4** [comment]
I can take a look and investigate, probably there are multiple platforms to add/handle:

- Windows CE
- Windows Embedded
- Windows Phone
- Windows Mobile
- Windows RT
- Windows Store

some of them may be actually same platforms with different names, need to research

**Comment by sztomi** [comment]
I don't think there is a difference between Windows Phone and Mobile. 

Windows RT was discontinued and superseded by Windows Store. 

Windows CE is now known as Windows Embedded Compact.

**Comment by memsharded** [comment]
I think this can be considered as implemented by @SSE4 PR https://github.com/conan-io/conan/pull/1987, will be in 0.29, but @sztomi feedback also welcome before the release if possible. Thanks!
