### ISSUE TITLE
[question] Possible to "inject" dependency into consumer when using `tool_requires`?

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#15858]
### What is your question?

We have a code generator that is distributed as a Conan package. The consumer can use it with `tool_requires`. However, the generated code has a new dependency that needs to be added as a normal `requires` to the consumer.

Is it possible to model and automate this behavior with Conan, i.e. using `tool_requires("codegen/1.0")` automatically adds a dependency `requires("lib/1.0")` to the consumer?

(Right now, our solution is that the required packages need to be manually added to the consumer, which makes it difficult to use as you have to somehow "know" which dependencies are missing or maybe even have changed.)

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fschoenm 

> Is it possible to model and automate this behavior with Conan, i.e. using tool_requires("codegen/1.0") automatically adds a dependency requires("lib/1.0") to the consumer?

I am afraid not. Any ``tool_require`` package defining or propagating something to its consumers will propagate it in the "build" context, and that makes it not usable. 

The possible strategy is to have the double dependency in the consumers:

```python
class Pkg(ConanFile):
    def requirements(self):
            self.requires("codegen/1.0")
   def build_requirements(self):
           self.tool_requires("codegen/<host_version>")
```
And have the ``codegen`` recipe to have a transitive ``requires`` to that dependency to inject, possibly conditional to the context.

But overall seems more artificial and complex than directly adding a ``requires("lib/10")`` to the consumer. It would be the same case as ``protobuf``, requiring it in the "build" context for generating code do not automatically inject the regular library requirement in the host context, that must be explicit.

**Comment by fschoenm** [comment]
Hello @memsharded,

Thanks for the answer.

> But overall seems more artificial and complex than directly adding a requires("lib/10") to the consumer. 

Well, it would remove the need for additional documentation on how to use the code generator. It may not only be one lib but multiple dependencies and those might even change over time.

Seems to me, the best way forward is the double dependency, as you mentioned.

**Comment by memsharded** [comment]
Closing as responded back then
