### ISSUE TITLE
Behavior and documentation for "conan new" inconsistent

### ISSUE THREAD

**Issue by marco-m** [conan-io/conan#1585]
Hello,

the documentation for `conan new` (http://docs.conan.io/en/latest/reference/commands/new.html) gives examples using a package name containing also user and channel, but these two informations are not used in the generated files:

```
Examples:

Create a new conanfile.py for a new package mypackage/1.0@myuser/stable
$ conan new mypackage/1.0@myuser/stable
```

On the other hand, invoking

    conan new mypackage/1.0@myuser/stable

or

    conan new mypackage/1.0

has the same effect on the generated `conanfile.py`: the only information that is taken into consideration is the package version (which I understand makes sense! but see below):

Since informations like user and channel should not go into the top-level conanfile, it looks like that the following changes are needed:

- examples should use `mypackage/1.0` and not `mypackage/1.0@myuser/stable`
- `conan new` should fail with a meaningful error if invoked with a name like `mypackage/1.0@myuser/stable`

There is also the additional question of what should happen when using the `--test` option. In this case, the `conanfile.py` inside the `test_package` directory could make usage of the user and channel information, and actually that was the case for the previous versions I tested:

conan 0.23 and conan 0.24, when invoked as

    conan new --test mypackage/1.0@myuser/fofo

generate a test_package/conanfile.py that contains:

    channel = os.getenv("CONAN_CHANNEL", "fofo")
    username = os.getenv("CONAN_USERNAME", "myuser")
    ...
    requires = "mypackage/1.0@%s/%s" % (username, channel)

while conan 0.25.1 doesnt contain these 3 lines.

Could you please explain or point me to some discussion of why conan doesn't use anymore the user and channel information in test_package/conanfile.py ?

Maybe this is related to the introduction of the new "conan create" command ?

There is also a related problem: it looks like that a test_package/conanfile.py created with "conan new" from conan 0.25 will not work with "conan test_package" (I read that it is deprecated). From the "conan test_package" documentation:

```
This command will run the equivalent to conan export <user>/<channel> where
user and channel will be deduced from the values of the requirement in the
conanfile.py inside the test subfolder. 
```

but these two arguments are not present any more... I am not asking to add additional conditional logic or to resurrect test_package, I am happy with conan create :-) I am just pointing out what I discovered. Maybe at this point is better to always fail the invocation of test_package, instead of simply deprecating it... To me, the simpler a tool is, the better :-) Less ifs, less bugs.

thanks!
marco

**Comment by lasote** [comment]
Hi! Probably the `conan new` command has to be changed, you are right, the user/channel should not be longer required.

The test_package project doesn't require anymore the requires to the recipe being tested, it's automatically injected. 

All this is related with the new `conan create` command, we have done a refactor, and yes, now the test_package command is deprecated. You can use the conan create command instead, even without the test_package folder, and only if the test_package folder is present it will run the package test.

I'm adding this to the 0.26 to review the new command. 

Thanks!!!

**Comment by lasote** [comment]
Hi again, I've been checking it, the user and channel are required to generate the CI scripts, so we have 2 choices: 

1. Only require the user and channel if you specify some CI option.
2. Keep it as is. 

As `conan new` is just a helper to create a base layout I would prefer to keep it always receiving the complete reference.

About the new `test_package` command, it works with the generated files, but now it requires that you pass the `user/channel` in the command.

Do you have any other concern with it? 

Thanks

**Comment by marco-m** [comment]
Hello,
to me is a question of not misleading the user. For example the documentation mentions:

```
Examples:

Create a new conanfile.py for a new package mypackage/1.0@myuser/stable
$ conan new mypackage/1.0@myuser/stable
```

If as a user I read this, I expect that `myuser` and `stable` will be actually used to perform the command (either as a validation, so ephemeral, or embedded in the generated files).

So if you want to keep the `conan new` code as-is, at least the documentation should be updated with correct examples in my opinion.

**Comment by lasote** [comment]
I will. Thanks

**Comment by lasote** [comment]
https://github.com/conan-io/conan/pull/1598
https://github.com/conan-io/docs/pull/274

**Comment by marco-m** [comment]
Merci!
