### ISSUE TITLE
export_sources cannot cope with "../"

### ISSUE THREAD

**Issue by SirLemyDanger** [conan-io/conan#1586]
The following project structure:

-- cpp/
-- cpp/file.cpp
-- include/
-- include/file.h
-- projects/
-- projects/conanfile.py

In conanfile.py:
Example 1:
`exports_sources = "../cpp/*", "../include/*"`

Example 2:
`exports_sources = "../*.foo", "cpp/*", "include/*"`
 
After calling `conan export user`
Result of example 1:
nothing but the conanfile was exported

Result of example 2:
cpp/file.cpp & include/file.h + conanfile were exported

It seems that conan interpret `../` ,temporary changes to that folder and reads the rest of the relative paths from there.

**Comment by lasote** [comment]
Thanks for the explanation, I'll try to perform a test to reproduce it.

**Comment by lasote** [comment]
I tried the Example 1 and `file.cpp` and `file.h` is being copied. 
Are you using the latest conan version?
Could you paste here the export command (or install or whatever) you are executing?

Thanks

**Comment by lasote** [comment]
By the way, we introduced the `exports_sources` folder in the latest version, in the `export` folder will be only the conanfile.py and the conanmanifest.txt

**Comment by SirLemyDanger** [comment]
I missed that version. I have updated conan and the behavior is indeed different - different but not as expected. Can you please check the following test cases:

project structure:

-- cpp/
-- cpp/file.cpp
-- include/
-- include/file.h
-- projects/
-- projects/conanfile.py
-- test/
-- test/src/
-- test/src/test.cpp

In conanfile.py:
Example 3:
`exports_sources = "../cpp/*", "../include/*", "../test/src/*"`

Example 4:
`exports_sources = "../test/src/*", "../cpp/*", "../include/*"`

After calling `conan export user`
Result of example 3:
all files were exported

Result of example 2:
only test/src/test.cpp was exported

It seems that now the order of the exports_sources matters, as if the relative path is relative to the previous element in the list. I was expecting that the path is relative to the conanfile.py.

Cheers

**Comment by memsharded** [comment]
Having a look.

> Result of example 2:
only test/src/test.cpp was exported

You mean now example 4?

**Comment by memsharded** [comment]
Confirmed, it is a bug. Will submit a fix asap. Thanks very much for your detailed reports.

**Comment by SirLemyDanger** [comment]
Yes :)
I just tested a bit more and in both example 3 & 4 all files in the export_sources dir in the conan cache were copied there without any directory structure, just flat which leads to errors in the build process.

I found a workaround defining export_sources like this:
`exports_sources = "../*.foo", "test/src/*", "cpp/*", "include/*"`

This tricks conan to treat all pathes after ´../*.foo´ (which not exists) relative to `../`

**Comment by memsharded** [comment]
Just submitted the fix, with a new test: https://github.com/conan-io/conan/pull/1590

Exactly, good workaround! You nailed it: the bug is that the first pattern processed is overwriting the ``FileCopier`` base path with the relative path. 

Please note, however, with the fix, the relative folders will not be added to the final path. If you want to have for example "cpp" and "include" folders in the package layout, you have to:

```python
exports_sources = "../cpp*", "../include*"
```

The fix will be in 0.26, or sooner if we can release a minor. Thanks again for your detailed reports, they really helped

**Comment by SirLemyDanger** [comment]
Thanks for you super quick response. Looking forward to the next release.

**Comment by lasote** [comment]
We prefer to keep it opened until we release, we will mark it as "fixed" when merged. Thanks!

**Comment by lasote** [comment]
Will be released in 0.26. Thanks!

**Comment by memsharded** [comment]
Now released in 0.26, you can now use normal exports_sources :) Thanks again!

**Comment by johnlaird-caff** [comment]
Are upward relative paths deliberately removed in conan 2? I see an assert here:
https://github.com/conan-io/conan/blob/release/2.0/conan/tools/files/copy_pattern.py#L30

and when I try thus in export_sources:
exports_sources = "CMakeLists.txt", "Project/*", "Project_Tests/*", "../../../../Shared/*"

conan create .
======== Exporting recipe to the cache ========
myproject/19.0@company/stable: Exporting package recipe: /home/me/code/mycode/Server/Libraries/myproject.root/myproject/conanfile.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/conan/cli/cli.py", line 264, in main
    cli.run(args)
  File "/usr/local/lib/python3.9/dist-packages/conan/cli/cli.py", line 167, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/usr/local/lib/python3.9/dist-packages/conan/cli/command.py", line 130, in run
    info = self._method(conan_api, parser, *args)
  File "/usr/local/lib/python3.9/dist-packages/conan/cli/commands/create.py", line 49, in create
    ref, conanfile = conan_api.export.export(path=path,
  File "/usr/local/lib/python3.9/dist-packages/conan/api/subapi/export.py", line 16, in export
    return cmd_export(app, path, name, version, user, channel, graph_lock=lockfile,
  File "/usr/local/lib/python3.9/dist-packages/conans/client/cmd/export.py", line 43, in cmd_export
    export_source(conanfile, export_src_folder)
  File "/usr/local/lib/python3.9/dist-packages/conans/client/cmd/export.py", line 136, in export_source
    _tmp = copy(conanfile, pattern, src=conanfile.recipe_folder,
  File "/usr/local/lib/python3.9/dist-packages/conan/tools/files/copy_pattern.py", line 30, in copy
    assert not pattern.startswith("..")
AssertionError

**Comment by memsharded** [comment]
Hi @coffeeaddict19 

Referencing parent directories with ``exports_sources`` attribute isn't recommended in 1.X either, and the ``export_source()`` method was introduced to be able to better handle these cases. That will work in 2.0 too.
