### ISSUE TITLE
[bug] SHORT DESCRIPTION. Get error when building llvm with conan. `undefined reference to `std::__throw_bad_array_new_length()'`

### ISSUE THREAD

**Issue by SteveLee123** [conan-io/conan#15861]
### Environment details

* Operating System+version:  SUSE Linux Enterprise Server 12 SP5
* Compiler+version: gcc 11.4.0
* Conan version: conan2
* Python version: python3.10

### Steps to reproduce

I use conan for build a project . but before that , I need to build llvm , and I get this errorl.

### Logs

[  8%] Built target LLVMDebugInfoMSF
[  8%] Linking CXX static library ../libLLVMOption.a
[  8%] Built target LLVMOption
[  8%] Linking CXX executable ../../bin/UnicodeNameMappingGenerator
/usr/bin/ld: CMakeFiles/UnicodeNameMappingGenerator.dir/UnicodeNameMappingGenerator.cpp.o: in function `loadDataFiles(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)#1}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const':
UnicodeNameMappingGenerator.cpp:(.text._ZZL13loadDataFilesRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_ENKUlS6_bE_clES6_b+0x827): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: CMakeFiles/UnicodeNameMappingGenerator.dir/UnicodeNameMappingGenerator.cpp.o: in function `std::_Hashtable<Trie::Node*, std::pair<Trie::Node* const, bool>, std::allocator<std::pair<Trie::Node* const, bool> >, std::__detail::_Select1st, std::equal_to<Trie::Node*>, std::hash<Trie::Node*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_rehash(unsigned long, unsigned long const&)':
UnicodeNameMappingGenerator.cpp:(.text._ZNSt10_HashtableIPN4Trie4NodeESt4pairIKS2_bESaIS5_ENSt8__detail10_Select1stESt8equal_toIS2_ESt4hashIS2_ENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb0ELb0ELb1EEEE9_M_rehashEmRKm[_ZNSt10_HashtableIPN4Trie4NodeESt4pairIKS2_bESaIS5_ENSt8__detail10_Select1stESt8equal_toIS2_ESt4hashIS2_ENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb0ELb0ELb1EEEE9_M_rehashEmRKm]+0x10f): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: CMakeFiles/UnicodeNameMappingGenerator.dir/UnicodeNameMappingGenerator.cpp.o: in function `auto Trie::dumpIndex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(auto:1 const&)#1}::operator()<std::vector<std::unique_ptr<Trie::Node, std::default_delete<std::unique_ptr> >, std::allocator<std::default_delete<std::unique_ptr> > > >(std::vector<std::unique_ptr<Trie::Node, std::default_delete<std::unique_ptr> >, std::allocator<std::default_delete<std::unique_ptr> > > const&) const':
UnicodeNameMappingGenerator.cpp:(.text._ZZN4Trie9dumpIndexERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEENKUlRKT_E_clISt6vectorISt10unique_ptrINS_4NodeESt14default_deleteISF_EESaISI_EEEEDaSA_[_ZZN4Trie9dumpIndexERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEENKUlRKT_E_clISt6vectorISt10unique_ptrINS_4NodeESt14default_deleteISF_EESaISI_EEEEDaSA_]+0x470): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: CMakeFiles/UnicodeNameMappingGenerator.dir/UnicodeNameMappingGenerator.cpp.o: in function `std::_Hashtable<Trie::Node*, std::pair<Trie::Node* const, int>, std::allocator<std::pair<Trie::Node* const, int> >, std::__detail::_Select1st, std::equal_to<Trie::Node*>, std::hash<Trie::Node*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_rehash(unsigned long, unsigned long const&)':
UnicodeNameMappingGenerator.cpp:(.text._ZNSt10_HashtableIPN4Trie4NodeESt4pairIKS2_iESaIS5_ENSt8__detail10_Select1stESt8equal_toIS2_ESt4hashIS2_ENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb0ELb0ELb1EEEE9_M_rehashEmRKm[_ZNSt10_HashtableIPN4Trie4NodeESt4pairIKS2_iESaIS5_ENSt8__detail10_Select1stESt8equal_toIS2_ESt4hashIS2_ENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb0ELb0ELb1EEEE9_M_rehashEmRKm]+0x10f): undefined reference to `std::__throw_bad_array_new_length()'
collect2: error: ld returned 1 exit status
utils/UnicodeData/CMakeFiles/UnicodeNameMappingGenerator.dir/build.make:99: recipe for target 'bin/UnicodeNameMappingGenerator' failed
gmake[2]: *** [bin/UnicodeNameMappingGenerator] Error 1
CMakeFiles/Makefile2:27774: recipe for target 'utils/UnicodeData/CMakeFiles/UnicodeNameMappingGenerator.dir/all' failed
gmake[1]: *** [utils/UnicodeData/CMakeFiles/UnicodeNameMappingGenerator.dir/all] Error 2
[  8%] Linking CXX static library ../libLLVMTableGen.a
[  8%] Built target LLVMTableGen
[  8%] Linking CXX static library ../libLLVMFileCheck.a
[  8%] Built target LLVMFileCheck
[  8%] Linking CXX static library ../../libLLVMDebugInfoCodeView.a
[  8%] Built target LLVMDebugInfoCodeView
Makefile:155: recipe for target 'all' failed
gmake: *** [all] Error 2

llvm/17.0.2: ERROR: 
Package 'fb2363e94ffbd68589b1a6c24429e02fddae31e8' build failed
llvm/17.0.2: WARN: Build folder /home/builduser/.conan2/p/b/llvm675bc31515041/b/build/Release
ERROR: llvm/17.0.2: Error in build() method, line 331
        cmake.build()
        ConanException: Error 2 while executing
CMake Error at cmake/conan.cmake:174 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:212 (conan_install)
  cmake/conan.cmake:230 (conan_setup)
  CMakeLists.txt:57 (include)

**Comment by memsharded** [comment]
Hi @SteveLee123 

Can you please share with us the recipe you are using for building that ``llvm`` package?
Without it it would be impossible to know what is happening.

Please also report the exact Conan version you are using. Thanks!

**Comment by SteveLee123** [comment]
Never mind it . I fix it. It 's not related to conan .

thanks.
