### ISSUE TITLE
Enable self.deps_env_info in local build() method

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#1587]
I am trying to consume [cmake_installer](https://github.com/lasote/conan-cmake-installer) package that have following ```package_info``` method:

```
def package_info(self):
        if not self.package_folder is None:
            self.env_info.path.append(os.path.join(self.package_folder, "bin"))
```

This information gets propagated well into PATH environment variable during ```build``` call, into virtualenv generator script, also it is visible via ```self.env```, but I can not access it via ```self.deps_env_info``` within consumers conanfile. I am getting ```KeyError``` when trying to reference required package using ```self.deps_cpp_info["cmake_installer"]```.

This is my consumers conanfile:

```
import os
import conans


class ConanFileInst(conans.ConanFile):
    name = "dev-tools"
    version = "0.1.0"

    requires = (
        "cmake_installer/0.2@demo/demo"
    )

    def build(self):
        print(self.env)                                 # ok
        print(os.environ["PATH"])                       # ok
        print(self.deps_cpp_info["cmake_installer"])    # ok
        print(self.deps_env_info["cmake_installer"])    # fails

```

**Comment by memsharded** [comment]
I confirm this, I also hit this a couple of days ago. I found that "env_info" is propagated through env-vars, not via ``deps_env_info``, so you have to read the ``os.getenv("YOUR_VAR")``. Although this works, maybe filling ``deps_env_info`` should be done.

**Comment by lasote** [comment]
I cannot reproduce it. I have a test accessing **deps_env_info** and your same example working.

**Comment by lasote** [comment]
Are you using conan 0.25.1?

**Comment by omicronns** [comment]
Yes ```Conan version 0.25.1```

**Comment by lasote** [comment]
How are you "running" the consumer conanfile? With `conan build` or exporting + installing?

**Comment by lasote** [comment]
I'm able to reproduce it with `install + build`. Currently, the environment variables information is stored in the `conaninfo.txt` file but only the applied values, not scoped by a package, so it is not possible to recover the `deps_env_info` object.

**Comment by lasote** [comment]
I'm renaming the issue and labeling it now that we know the real issue.

**Comment by lasote** [comment]
By the way, I'm currently adding CI and fixing some things in the cmake-installer package. Tomorrow I will add it to conan-center.

**Comment by sztomi** [comment]
Experiencing the same issue. I have a temporary test package to test a dev tool package. 

```python
class Btest(ConanFile):
  name = "btest"
  version = "1.0"
  requires = "mytool/2.8.2@user/channel"

  def build(self):
    print self.deps_env_info._dependencies_.items # empty
    print self.deps_env_info["mytool"] # fails
```

Calling this temporary test package via `conan build`

**Comment by sztomi** [comment]
Additional info: I'm experiencing the same behavior in `test_package` as well.

**Comment by lasote** [comment]
@sztomi Thanks for the info, will be useful.
