### ISSUE TITLE
How to specify msbuild properties with the new MSBuild build helper

### ISSUE THREAD

**Issue by PaulvdLinden** [conan-io/conan#15872]
### What is your question?

I'm upgrading my deprecated imports `from conans import ConanFile, MSBuild, tools` to the recommended imports. I'm having difficulties with the new MSBuild helper to specify custom properties for msbuild.

In my old recipe I have this:

```python
from conans import ConanFile, MSBuild, tools

class FooConan(ConanFile)
    def configure(self):
        self.generators = ["visual_studio_multi"]
            
    def build(self):
        build_properties = {
            "ProductVersion": self.version,
            "PreBuildEventUseInBuild": False,
            "PostBuildEventUseInBuild": False
        }

        msbuild = MSBuild(self)
        msbuild.build("foo.sln", upgrade_project=False, properties=build_properties)
```

the updated recipe now looks like this:

```python
from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.microsoft import MSBuild, MSBuildDeps, VCVars, msvs_toolset
from conan.tools.scm import Version, Git

class FooConan(ConanFile)
    def configure(self):
        self.generators = ["VCVars", "MSBuildDeps"]
            
    def build(self):
        msbuild = MSBuild(self)
        cmd = msbuild.command("foo.sln")
        self.run(cmd + ' /p:ProductVersion="' + self.version + '" /p:PreBuildEventUseInBuild="False" /p:PostBuildEventUseInBuild="False"')
```

To specify custom properties, I just append these to the msbuild command. I was wondering if there isn't a better method for this. I was hoping there was something like `msbuild.build("foo.sln", '/p:PreBuildEventUseInBuild="False"')

Currently I'm using conan 1.63

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PaulvdLinden 

Thanks for your question.

The recommended way to define properties is via the ``MSBuildToolchain``, please check https://docs.conan.io/2/reference/tools/microsoft/msbuildtoolchain.html#attributes

The idea is that with this way of adding properties you can get exactly the same build with ``conan install`` + opening the IDE and building there that with the ``conan build`` or ``conan create`` commands, because the ``MSBuildToolchain`` generate the file at ``conan install`` time.

**Comment by PaulvdLinden** [comment]
Thanks for the quick response. That seems exactly what I'm looking for.

**Comment by memsharded** [comment]
Happy to help! :)
