### ISSUE TITLE
[bug] Errors with Conan v1 and CONAN_V2_CLI=1

### ISSUE THREAD

**Issue by fpoirotte** [conan-io/conan#15873]
### Environment details

* Operating System+version: Fedora Linux 38
* Compiler+version: GCC 13.2
* Conan version: 1.63.0
* Python version: 3.11.8

### Steps to reproduce

Run `CONAN_V2_CLI=1 conan --help`

### Logs

```
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.11/site-packages/conans/cli/cli.py", line 114, in run
    command = self.commands[command_argument]
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: '--help'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.11/site-packages/conans/cli/cli.py", line 182, in main
    exit_error = cli.run(args)
                 ^^^^^^^^^^^^^
  File "/home/me/.local/lib/python3.11/site-packages/conans/cli/cli.py", line 121, in run
    self.help_message()
  File "/home/me/.local/lib/python3.11/site-packages/conans/cli/cli.py", line 96, in help_message
    self.commands["help"].method(self.conan_api, self.commands["help"].parser,
    ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'help'

ERROR: 'help'
```

**Comment by fpoirotte** [comment]
For context:

* We are aware that Conan v1 is on a deprecation path
* We have several recipes which are not yet v2-compatible
* Our tooling (CI scripts and so on) currently uses Conan v1's commands to create packages
* We are preparing our platform for a future migration to Conan v2 as a 3-steps program:
  * Upgrade our tooling to be v2-friendly (start building packages using Conan v1 running in v2 compatibility mode)
  * Update the recipes to be v2-compatible
  * Move on to use solely Conan v2

The error above prevents us from listing available commands.

My understanding is that Conan v1 with CONAN_V2_CLI set and Conan v2 share the exact same commands, so in the meantime, we will be using Conan v2's help to update our scripts.
Nonetheless, fixing the error above would provide a smoother upgrade path for folks going down the same road we did.

**Comment by memsharded** [comment]
Hi @fpoirotte 

Thanks for your report.

I am afraid the ``CONAN_V2_CLI`` approach was dropped long time ago, even long time before the release of Conan 2.0. It never achieved parity with Conan 2 command line.

Your approach to the migration is almost perfect, just you should start testing your pipeline with an actual Conan 2 version, in parallel to your Conan 1 pipeline. This is what we have been doing at scale in ConanCenter, and the vast majority of users have been doing: adding a parallel Conan 2 pipeline, that doesn't make the builds fail, but it warns about incompatibility, so teams can gradually make recipes compatible.

**Comment by fpoirotte** [comment]
Hi, thank you for this information.
I'll give your suggestion a try.
