### ISSUE TITLE
How do I pass down compiler options?

### ISSUE THREAD

**Issue by freihamer** [conan-io/conan#15879]
### What is your question?

Hi,
So far I always worked with hard coded target_compile_options in my CMakeLists.txt. However now I need to build a package for Linux as well as for ARM baremetal, and the target_compile_options I need are different.

What is the right way to handle this with Conan?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by freihamer** [comment]
After reading [this](**url**) I am looking into [CMakeToolchain](https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#cmaketoolchain), which until now I always and only used as
```
tc = CMakeToolchain(self)
tc.generate()
```
And now I would like to pass the following flags when os is "baremetal" and "arch" is "armv7hf"

-mcpu=cortex-m7 -x c -c mthumb -ffunction-sections -mlong-calls -Wall -MP -MMD -MF -std=c99 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -g3 -O2

Or maybe I should rather set the CFLAGS in the conan profile I am using?

[buildenv]
CFLAGS=-mcpu=cortex-m7 -x c -c mthumb -ffunction-sections -mlong-calls -Wall -MP -MMD -MF -std=c99 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -g3 -O2

I am trying both approaches but I don't think the flags are actually passed down to the build system (I tried to inject wrong flags and the compiler did not complain, which is a sign that my flags did not make it through)

Working with Conan 2.0.17

**Comment by freihamer** [comment]
Ok I think my solution is to add the following in my cross build profile linux_to_armv7:

[conf]
tools.build:cflags=["-mcpu=cortex-m7", "-x c", "-c", "-D__SAMV71Q21B__", "-mthumb", "-ffunction-sections", "-mlong-calls", "-Wall", "-MP", "-MMD", "-MF", "-std=c99", "-mfloat-abi=hard", "-mfpu=fpv5-sp-d16"]

@memsharded could you just confirm this is the right way to go?

**Comment by memsharded** [comment]
Hi @lucabarbiero 

yes, using the ``conf`` items ``tools.build:cflags`` ``tools.build:cxxflags``, etc is a recommend way to "inject" compiler flags into the different build systems. A couple of quick notes:

- This is done by the built-in build system integrations like ``CMakeToolchain`` and others
- This depends on the recipes using them, or manually reading the ``conf`` values and applying them.
- If there is some recipe that uses a custom build system integration and is not applying the ``conf`` manually in the recipe, obviously, they will not be honored.

**Comment by freihamer** [comment]
Thanks for the confirmation and additional info!
