### ISSUE TITLE
[feature] Bring back imports (take 2)!

### ISSUE THREAD

**Issue by p-groarke** [conan-io/conan#15884]
### What is your suggestion?

What is your suggestion?

OK my last attempt at explaining this was misguided, sorry about that. Let's try this again! :)

In our products that use conan, we cannot use virtualenv. We will never be able to use virtualenv. IMO virtualenv is a bad road anyways (see `pip` and its failures).

This means, we cannot use `conanfile.txt` anymore, which we are sad about. We <3 `conanfile.txt` for quick prototypes. We also use them for things like translations and tests data, pure data download packages. It makes conan very flexible and enticing.

Why can't we use `conanfile.txt`? It has no way to copy dlls anymore. I think we can all agree copying dlls is a no-brainer and something that should work out-of-the-box in conan. All our devs were quite surprised that conan 2 is incapable of copying dlls, so, dylibs.

I don't think the removal of `imports` was thought through. I understand there were problems with it. I'm not asking for a 1:1 reintroduction, but we need a non-python, simple, builtin mechanism to copy files to our local build folders. That mechanism should be flexible enough to copy files without the draconian requirement of running conan *before* our build systems.

If you explain the rational behind `imports` removal, I'm happy to brainstorm some alternative. But I don't believe you need me to do that, I am confident you can find something better that fulfills everyone's workflow. Whomever has the luxury of using virtualenv can keep using that, but we can't.

Take care!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @p-groarke 

Thanks for your suggestion.

We understand that using and activating the virtualenvs is not always convenient. This is the reason why we have been working in recent improvements like:
- ``env`` sections have been added to the generated CMakePresets.json generated by ``CMakeToolchain``. That means that it is no longer necessary to activate the virtualenv, and using CMake presets will already automatically activate the environment, both for build and test targets
- The ``cmakeExecutable`` was also added to CMakePresets to even take into account tool_requires to cmake that could be used by IDEs and other applications
- Next Conan 2.2 adds and uses ``CMAKE_VS_DEBUGGER_ENVIRONMENT`` CMake variable for VS IDE, adding automatically all the dependencies bindirs to automatically locate .dlls, no need of virtualenvs either.

With these improvements, activating the virtualenvs won't be necessary in the majority of cases.

Regarding the ``imports`` functionality, the most important part is that ``imports`` functionality **has not been removed at all**. It is still possible to copy files from dependencies, just with a different syntax. So we are talking here mostly about  the removal of ``[imports]`` section in the ``conanfile.txt``:

This was a deliberate design decision, let me explain the rationale:
- For "users" of conanfiles, it really doesn't matter, all it matters is ``conan install . `` and the like, which is totally irrelevant if it is a conanfile.txt or a conanfile.py.
- For "writers" of conanfiles, we carefully analyzed the possibilities. It happened that absolutely no one, not a single maintainer of the Conan project, including the founders were capable of correctly writing an ``[imports]`` section in a ``conanfile.txt`` without having to go to the docs to check. While the whole team is able to write the equivalent syntax in a ``conanfile.py`` by heart, no need to check docs, and even in more advanced cases. We checked this fact with quite a few users and the findings were completely aligned, the ``[imports]`` syntax is bad, difficult to read, write and maintain. Limited in functionality and more challenging to debug.

We wrote the rationale in https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html. In essence it boils down to:
```
[requires]
zlib/1.2.11

[tool_requires]
cmake/3.22.6

[generators]
CMakeDeps
CMakeToolchain
```
vs
```python
from conan import ConanFile

class CompressorRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"
    requires = "zlib/1.2.11"
    tool_requires = "cmake/3.22.6"
```

While it has slightly more characters to write, this is also very straightforward, and this has many advantages for the writer, including full debuggability with a debugger, or easy ``print()`` statements. 

Not to say, that ISO C++ survey reports a 70% of users responding Python to the question ``Q15 Besides C++, what programming languages/environments do you use in your current and recent projects?``, so it is not that the Python syntax is alien to the C++ ecosystem anymore.

I have been discussing it with the team. and there is quite consensus that this is still the recommendation, we are not introducing back into ``conanfile.txt`` an invented, complicated, and quite limited syntax in an ``[imports]`` section, for something that can be done cleanly and way more flexible in the ``conanfile.py`` variant.

For comparison this is the .txt syntax vs the .py syntax for copying the .dlls for a dependency (zlib for example):

```
[imports]
bin, *.dll -> . @ root_package=zlib, folder=True
```

```python
def generate(self):
     copy(self, "*.dll", src=self.dependencies["zlib"].cpp_info.bindir, dst="zlib")
```
As a side note, I had to fix the .txt version 3 times until I got it working, even while reading the docs.
Note that the conanfile.py version is also superior as it doesn’t need to know that the binary folder is called “bin”. If “zlib” recipe had decided to name the folder differently, the txt version would fail, while the python version would work without modification.

Summary:
- There are 2 different and independent issues in this thread, one is the usage of virtualenvs, and the other is the definition of “imports” in ``conanfile.txt`` versus ``conanfile.py``
- Regarding virtualenvs, we are aware they are not always the best option, and this is why the latest Conan releases have included tons of improvements in the CMake integration that allows to use environment variables defined in dependencies transparently without requiring virtualenvs at all.
- The ``imports`` functionality has not been removed at all. It is still very possible to copy files from dependencies, just with a different syntax. The only thing that has been removed is the ``[imports]`` syntax in ``conanfile.txt``.
- Regarding the definition of ``[imports]`` in ``conanfile.txt``, the definition is not only way more complicated, to the point that it is almost impossible to get it right by heart without reading the docs, even for the project maintainers, but also it is way more limited in a multitude of cases that requires more flexibility. Consequently, we have decided to not introduce back the complex custom DSL ``[imports]`` in ``conanfile.txt``, and we recommend using the ``conanfile.py`` alternative to implement that functionality.

Thanks very much for your feedback!

**Comment by p-groarke** [comment]
@memsharded Hi again James :) 

I didn't really think I'd convince you, but it's important that you understand *why* this request more than the request itself. I want to make sure you are aware of our workflow. You seem to misunderstand our situation, multiple products' situations, which worries me.

> We understand that using and activating the virtualenvs is not always convenient.

This is wrong and incorrect, a misunderstanding of my premise. I will dive into just that sentence, since I know I won't ever convince you of the value of `[imports]`.

It is not that it isn't convenient, it is that we **cannot** use `virtualenv` for technical reasons. Furthermore, as we speak we **cannot** use `cmaketoolchain` generator nor anything of that ilk, which requires calling `conan install` **before** our builds. Let alone we don't use cmake in many products.

Why is that? We are dealing with insanely massive, old, horrible legacy build-systems that are Frankenstein's of technologies evolved over time. Our build-system situation is hodge-podge of processes, various technologies built over multiple decades. Many areas of lost knowledge.

In our situation, **the dlls must exist at precise locations at precise moments** throughout our build. Furthermore, we must call conan from sub-processes, eliminating any and all generators the requires being called before our build systems. As you know, environment variables cannot be "inherited" from sub-processes either.

We adopted conan 1 because it was flexible enough to integrate in these horror-shows of real world build-systems nicely. Conan 1 gave us an adoption path and a way forward to slowly improve our situation over time. I don't see the same capabilities in Conan 2, which seems to expect "ideal build-systems and simple projects only". Until VS2022, we couldn't even open our visual studio solution without crashing VS itself due to the sheer amount of projects in it 🤣 

Furthermore, we have plugin architectures where our dll search paths are completely custom and have nothing to do with our build path. AFAIK virtualenv / cmaketoolchain-env generators **cannot** work in this world.

We have publishing steps which expect dlls to be copied to certain locations and to network locations at various moments. Again, virtualenv / cmaketoolchain-env generators **cannot** fulfill this scenario.

My point is, really, that the number 1 conan workflow is copying dlls. It is weird that users asking conan 2 be able to do that receive any sort of push back. It points to a misunderstanding of conan usage in the wild. Your `env` work is amazing and we will likely use it on smaller or newer projects. But who cares about those, they are easy and have never been a problem.

I get your point and you are most likely right, but if `conanfile.txt` cannot copy files anymore, maybe it should be removed entirely?

I hope you better understand the situation now. I'd be happy to organize a call about this, I discuss with Diego once in a while and maybe this is worth going over. I just want to make sure our workflow isn't removed from conan and we still have an adoption path. Our builds are improving thanks to conan, we estimate roughly 20 years to get rid of pain-point technologies in our build-systems. But we will always need to copy dlls, forever.

As always, take care, no hard feelings :)

**Comment by memsharded** [comment]
Thanks for the feedback.

Sure, lets forget about virtualenvs, or about using environment in CMakePresets.

Lets focus only on the imports.

Imports haven't been removed. Users wanting to use imports in Conan 2 are not pushed back, they can perfectly keep copying the DLLs, not problem at all with that. Just a new syntax, that is proven to be not only way easier to remember, to write and to maintain, but also more flexible and powerful to support more advanced cases, is the way to do it.


> but if conanfile.txt cannot copy files anymore, maybe it should be removed entirely?

Why? It still very useful for a lot of people. The fact that you cannot use it because you cannot use virtualenvs, but you cannot use either CMakeToolchain, doesn't mean that the ``conanfile.txt`` is not useful. 


> I just want to make sure our workflow isn't removed from conan and we still have an adoption path. 

You can be sure your workflow has not been removed and there are not any plans to remove it. Just the legacy ``conanfile.txt`` "imports" syntax has been removed because of being problematic and not enough flexible. But the workflow is still fully supported with the new "copy" syntax in ``conanfile.py``. (furthermore, there are some pending improvements that will be able to accelerate repeated copies, which can be very useful for your case).


Thanks very much for your feedback again.

**Comment by p-groarke** [comment]
Alright well, this one has been covered hehe.
