### ISSUE TITLE
Conan create and conan test_package errors on Windows

### ISSUE THREAD

**Issue by cpace6** [conan-io/conan#1588]
Hi,

Ever since upgrading to version 0.25.1, many of my Windows builds that use conan test_package are failing. Additionally, I have been unable to successfully use "conan create" on Windows (specifically, Windows 10, 64-bit). 

Here is the basic error I am seeing- From the top level of project, I run 'conan create name/stable -tf ./test/package -pr ./tools/profiles/vs-14-release'. Then, project/0.0.1@name/stable gets exported successfully and finds its dependencies, which are already cached. Then, I consistently run into this error "ERROR: Error while trying to get recipe sources for project/0.0.1@name/stable. No remote defined"

I have tried clearing the local cache, but that does not have an effect. I have also tried manually defining the remote by running 'conan add_ref project/0.0.1@name/stable remote_name', but after re-running 'conan create', I see a different error: "ERROR: Request for path: project/0.0.1/name/stable/export Not Found. [Remote: remote_name]"

Please let me know if you need any more details.

Best Regards,
cpace6

**Comment by lasote** [comment]
Hi,

First of all, do you have any example of failure with the test_package? Only fails in windows? Is it the same error that you described with `conan create`?

Could we access to the recipe that is failing with `conan create`?

**Comment by cpace6** [comment]
Yes, it only fails on Windows. I am able to run the same commands on the same repo in Mac/Linux with no problems.

Here is the error after running 'conan test_package -tf ./test/package -pr ./tools/profiles/vs-14-release': "ERROR: Error while trying to get recipe sources for project/0.0.1@name/stable. No remote defined.". I tried clearing my local cache and updating the remote to remote_name manually using 'conan add_ref', but still saw the error. 

Do you have any suggestion for which part of the recipe could be failing? I don't think I'll be able to send the full file. 

Thank you for the quick response.

**Comment by memsharded** [comment]
I am confused, in theory we have not changed test_package, only added the create command. I have no idea of what could it be. Could you please send us the file, or just a snippet (covering the declarations, the exports, exports_sources, source() method), together with the full output, privately to our email? (info@conan.io)

**Comment by cpace6** [comment]
Sent. We think it might have to do with "self.short_paths = True" but we are still looking at it.

**Comment by memsharded** [comment]
I just sent you some feedback.
Good guess! As I suggested, ``short_paths`` should be a class attribute, there is no need to set it in any method. Actually, it has to be a class attribute, because the way it is read and processed at ``conan export``. It is possible that recent changes in the ``exports_sources`` layout have revealed the underlying issue. Please try using ``short_paths`` at the class level, dont worry, it will not affect other systems than Windows, for other OSs, it is just ignored.

**Comment by cpace6** [comment]
Setting short_paths at the class level seems to have fixed the problem!!
Thank you for the exceptional support and excellent feedback, I will respond via email if I have any follow-up questions about your suggestions. 
Thank you!!

**Comment by memsharded** [comment]
Excellent! Thanks to you for trusting conan
