### ISSUE TITLE
exports_sources cannot handle read only files

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#1589]
(Running on Windows; I have not verified on any other system)

If exports_sources specifies a file that is read-only, the file that ends up in the "export_source" folder in the .conan folder is also made read-only. This is fine for the first execution of `conan create`, but upon the second invocation, an error "Permission denied" occurs. Clearing the read only bit on these files resolves the error (the files are overwritten as expected).

This is a common configuration in my case because the version control system I'm using (p4) marks files as read only until they are checked out, so most of that folder will be read only at any given time.

Probably the correct solution here is for the copy operation to _not_ copy the read only bit. One could also just ignore the read-only attribute and forcibly overwrite the files in the export_source folder, but that makes less sense on non-Windows systems. For now, my workaround has been to create a source() method that removes the read only bit, but this is not portable.

**Comment by lasote** [comment]
@memsharded take a look, maybe you can add it to the #1571

**Comment by memsharded** [comment]
I think we can force the Write bit while exporting. Though maybe we can also make it at the time of removal, not at export (lazy approach). Could you please share the detailed trace of the failure? Trying to see the place where the "permission denied" occurs.

**Comment by mpdelbuono** [comment]
The lazy approach makes sense to me, too. It would also have the beneficial side effect of preventing developers from modifying the copied sources accidentally (without realizing what folder they're in). The traceback at the time of error is here:

```
TestLib/0.1.0@matthewdb/demo: Exporting package recipe
Traceback (most recent call last):
  File "conan\conans\client\command.py", line 856, in run
  File "conan\conans\client\command.py", line 198, in create
  File "conan\conans\client\conan_api.py", line 56, in wrapper
  File "conan\conans\client\conan_api.py", line 283, in create
  File "conan\conans\client\manager.py", line 90, in export
  File "conan\conans\client\export.py", line 61, in export_conanfile
  File "conan\conans\client\export.py", line 140, in _execute_export
  File "conan\conans\client\file_copier.py", line 75, in __call__
  File "conan\conans\client\file_copier.py", line 169, in _copy_files
  File "shutil.py", line 130, in copy2
  File "shutil.py", line 83, in copyfile
IOError: [Errno 13] Permission denied: 'C:\\Users\\matthewdb\\.conan\\data\\TestLib\\0.1.0\\matthewdb\\demo\\export_source\\path\\to\\file\\...'
```

The command executed was `conan create matthewdb/demo`. This is Conan v0.25.1.

**Comment by memsharded** [comment]
Thanks for the feedback. I will explore the lazy approach first then.

**Comment by memsharded** [comment]
Proposed the lazy approach, removing the offending folder before exporting a new one: https://github.com/conan-io/conan/pull/1596

**Comment by lasote** [comment]
It was merged and will be available in the next release. Thanks!
