### ISSUE TITLE
[question] Upgrade existing binaries to conan2

### ISSUE THREAD

**Issue by huysentr** [conan-io/conan#15894]
### What is your question?

Hello

I am in the situation that I have to make a private remote compatible with conan2. This remote has a ton of conan1 binary uploads (no build scripts, nothing, just package-export code) I was wondering if there was a quick way to do this. I'm considering writing a script to automate the process. But maybe there is another way?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @huysentr 

thanks for your question.

Moving to Conan 2 largest effort is making sure that recipes are jointly compatible with Conan 1 and Conan 2 syntaxes. Once this is achieved, having the "binaries" is relatively straightforward, a ``conan export-pkg`` (or ``conan create``) should make it.

Unfortunately it is challenging to have an automated script that upgrades recipes to make them compatible with Conan 2, so this would require some manual work. In ConanCenter the migration of more than 1500 recipes has been done, we would have enjoyed such automation, but the variability in recipes makes this impossible.

I would suggest to add a parallel Conan 2 pipeline in CI that works in parallel with the Conan 1 one, and then have it working in parallel without hard failing until things are also green for Conan 2, then do the switch.

**Comment by memsharded** [comment]
I am closing this ticket as responded, don't hesitate to re open or create new tickets for any further question, thanks!
