### ISSUE TITLE
[feature] Ability to run `conan profile detect` w/o error and w/o overwriting when the profile already exists

### ISSUE THREAD

**Issue by mmomtchev** [conan-io/conan#15902]
### What is your suggestion?

I am using `conan` as a part of a source-level distribution system on `npm` for JavaScript packages that contain C++ code (compiled to native binary for Node.js and to WASM for the browser). `conan` enables me to produce self-contained builds without having to maintain all the included libraries.

Currently, all my build scripts start with:

```
{{platform.python}} -m pip install --user git+https://github.com/conan-io/conan # because of #15867
{{platform.python}} -m conans.conan profile detect || echo ok
{{platform.python}} -m conans.conan install ..... <very long line>
```

The second line works with both `bash` and `cmd.exe` but it would be even better if there was a `--if-not-exists` option - so that all my builds do not start with an error. I could of course create a special profile and overwrite it at each invocation - or even create my own `conan` home directory, but I think that I should support the case where the user has an already existing `conan` profile that contains custom options.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mmomtchev 

Some quick feedback first: the usage of ``conans.conan`` is not documented, not part of the public interface. This is guaranteed to change in some future Conan release, when we will refactor the code internals.

For not raising an error for ``conan profile detect``, there is already the ``--force`` flag. But that would indeed overwrite the existing ``default`` profile.

I think what is incompatible is both having a modified ``default`` profile and also calling ``conan profile detect`` to detect the ``default`` profile. The not overwrite error is there for this reason, to protect against this.

The strategy should probably be different:
- Manage your own profiles explicitly, name them and use them explicitly. Manage them with ``conan config install``
- Detect and use a different name than the profile, like ``conan profile detect --name=myprofile``. The default profile name can also be changed in ``global.conf`` if you want to avoid passing ``-pr=myprofile`` in every invocation.
- You can check yourself in your pipeline with ``conan profile list`` if the ``default`` profile already exist

**Comment by mmomtchev** [comment]
If I decide to always overwrite, I won't be compatible with an existing `conan` installation - which is could be a good decision. On other hand, parsing the `conan profile list` output in a platform-independent way would require a Node.js or Python script. And alas, a `pip` bin directory - especially the user one - that is not in the `PATH` is a very common occurrence - maybe not on Linux - but quite probable on macOS and Windows. I am afraid that there are no simple alternatives.

**Comment by memsharded** [comment]
Proposing ``--exist-ok`` in https://github.com/conan-io/conan/pull/15933
