### ISSUE TITLE
CMake generator: detect if conan install needs to be run again?

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#1591]
Here's a scenario:
- repository for project that lists dependencies in conanfile.py (or conanfile.txt)
- project uses cmake, and find_package to locate dependencies
- developers need to run `conan install` prior to invoking `cmake` for the first time 

The scenario is the following. Developers are likely constantly switching branches or frequently syncing the main branch with remote, _while working on the same cmake build directory_.  CMake-wise, this is mostly safe: all targets depend on 'zero-check' which forces cmake to rerun if the scripts have been altered. If sources have changed instead, next time a target is built, the files will be recompiled. In a nutshell, developers can safely switch branches or `git pull` and cmake sorts itself out in most cases.

Enter conan, `conan install` needs to be called before the first time cmake is configured, in order to generate `conanbuildinfo.cmake`.  But now, if `conanfile.py` is modified (different branch, or `git pull`, etc), the users will need to call conan install again for `conanbuildinfo.cmake` to be updated properly (and as a side note, they will probably have to clear the cmake cache for the dependencies to be picked up correctly by find_package/find_library/find_path).

I am trying to come up with a way of verifying, through cmake, whether `conanbuildinfo.cmake` is up-to-date with the "file" it originates from (`conanfile.py`), to detect this situation and simply warn the user and point them to call "conan install". Here's the options I'm considering:

- Have a custom conan generator (a variant of the cmake one) that prints out the MD5 hash of the conanfile.py that was used to express the requirements. However, Im not even sure this is at all possible, as I think there's multiple ways of invoking the conan cmake generator through conan install (conanfile.py, conanfile.txt, or passing the dependencies and their options as arguments to conan install).
On top of that I'm making the assumption that when people call "conan install", they call with with the correct compiler settings (compiler, version, os, runtime, etc), or at least that their defaults are correct. 
I just noticed that conan's cmake generator does include functionality to perform these checks, but unless I'm missing something, `CONAN_COMPILER`, `CONAN_COMPILER_VERSION`, etc, are only defined when invoking cmake using conan cmake from inside conanfile.py? Wouldn't it make more sense for those things to be defined in `conanbuildinfo.cmake` when that file is generated? That information is already known at that stage.

- Make the cmake configuration depend on `conanfile.py` (https://cmake.org/cmake/help/v3.8/prop_dir/CMAKE_CONFIGURE_DEPENDS.html) . That should force cmake to rerun if conanfile.py changes. I could cache the MD5 of that file when cmake is first configured, and then alert the user when conanfile.by has changed.  But still doesnt really tell me if `conanbuildinfo.cmake` is "up-to-date". 

- Call `conan install` from cmake a-la https://github.com/conan-io/cmake-conan. In that case I can cmake cache the arguments passed to conan install (or the MD5 of conanfile.py), and if these change then call conan install again or alert the user to clear the cache.

As for the "why" of all this:  large dev team where most are wary of dealing with cmake any more necessary.
Because we rely on CMake's find_package (which relies on find_library and find_path), if any of the dependencies changes (lets say I update OpenCV from 2.4 to 3.2 through conan). It is likely that that commit that brings in the change in the conanfile.py that switches to OpenCV 3.2, will also bring in code changes that make use of 3.2-only functionality. Because CMake caches the find_package results, even if I point to to a different directory (3.2 instead of 2.4), it will still use the older version. So users do have to clear the cache and start over. If they dont, chances are cmake will configure okay, but developers will get compiler errors

**Comment by memsharded** [comment]
Interesting problem. We can assume here that that developers are using the same configuration (compiler, version, runtime), otherwise, they would probably need to clean the build folder anyway (clearing conanbuildinfo.cmake), and regenerate a clean project with cmake.

I find interesting the second idea, I would probably to to create a custom target that cleaned the cmake stuff (including conanbuildinfo.cmake) when conanfile.py is changed, and also show a message telling to conan-install. I am not a cmake expert, but with some cmake-fu should be possible, what do you think?

**Comment by piponazo** [comment]
We are exactly in the same situation and some developers want to do something about that. I actually also like the second idea. I will let you know if we take some decision ;)

**Comment by marco-m** [comment]
Hello, we took the idea from @jcar87 and implemented it (at least partially). Works very well, thanks! Here is a gist ready to go https://gist.github.com/marco-m/d00531c4a6eca30a53305b1767872937

**Comment by jens-totemic** [comment]
Here's another take of a cmake script that checks for the need to re-run conan: https://gist.github.com/jens-totemic/f580342769f401434b86f63d97a0393d
This cmake module can be included in the project instead of `conanbuildinfo.cmake`. It detects if conan was run at all or needs to be run again. It also prints the appropriate conan install command with all needed parameters as convenience for the user.

**Comment by memsharded** [comment]
Closing this issue as outdated, the new ``cmake-conan`` for COnan 2.0 is now fully transparent, don't need modifications to CMakeLists.txt and will re-run ``conan install`` if ``conanfile`` changes: https://github.com/conan-io/cmake-conan/tree/develop2
