### ISSUE TITLE
Downloading libs from dependent packages

### ISSUE THREAD

**Issue by vithalsm** [conan-io/conan#15923]
### What is your question?

Hi,

We have internal conan server, where certain packages (of type libs) and trying to download, but unable to achieve in some case, as descried below:
Packages (libs) in conan server 
   - Individual packages - L1, L2, L3
   - Another L4 - requires L1, L2 and L3.  (transitive = true for all).

Now, when I download individual package:
'conan download L1 -r <server>' I could get recipe alone with prebuild lib of L1.

For L4, used 'conan install --requires L4 -r <server>' command, recipes for L1/L2/L3 are pulled.  But fails further during 'Installing packages' stage with error as:
ERROR: Missing binary: <L1>

Adding '--build=missing' with above install command works.  But, want to download prebuilt libraries than building from the source.

Appreciate any help/info how to achieve this.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @vithalsm 

Thanks for your question

> For L4, used 'conan install --requires L4 -r ' command, recipes for L1/L2/L3 are pulled. But fails further during 'Installing packages' stage with error as:
ERROR: Missing binary:

> Adding '--build=missing' with above install command works. But, want to download prebuilt libraries than building from the source.

If you are getting a "missing binary" error that is basically what it means. The binary packages you have for L1/L2/L3 are not valid for L4. There are many reasons for this to happen:
- They were compiled with different settings, like different compiler or compiler.version
- They were compiled with different options, like shared/static
- They were compiled with different dependencies, and now there are new dependencies versions that require to rebuild them.

Now there is the ``conan graph explain`` command, that will tell you the reason why the existing binaries you have in the server are not valid for your current install. Can you please try it and copy here the output?

**Comment by vithalsm** [comment]
@memsharded thank you so much.  It's due to mismatched settings 'build-type' causing the issue.  Will address it.  Thanks again.

**Comment by memsharded** [comment]
Thanks for the feedback. I think we can close this ticket then as solved, don't hesitate to create new tickets for any further question.

**Comment by vithalsm** [comment]
@memsharded  As its related or in continuation, thought to put the comment here, please let me know if I need to do so in new ticket.
In out conan build profile, using 'build-type' with 'RelWithDebInfo' settings and uploading the internal libraries.  
However, the publicly dependent libs like protobuf are built with 'Release' attributes.
So, even though I am able to fix 'build-type' for L1/L2/L3/L4 libs, it becomes challenging when it comes to downloading prebuilt libs from conan.io repository.
Is there anyway to get around this problem please?
