### ISSUE TITLE
[feature] want conan get to one shot config packge

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [conan-io/conan#15938]
### What is your suggestion?

I want conan to be like golang, where you can download and configure a package and its dependencies directly with a single line of command.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Mr-Ao-Dragon 

This is what Conan already does. When you do ``conan install --requires=somepackage/version ..`` it will install that package and its dependencies too.

**Comment by Mr-Ao-Dragon** [comment]
> Hi @Mr-Ao-Dragon
> 
> This is what Conan already does. When you do `conan install --requires=somepackage/version ..` it will install that package and its dependencies too.

ok
