### ISSUE TITLE
[feature] Add support for Pop!_OS to package_manager

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#15930]
### What is your suggestion?

[Pop!_OS](https://pop.system76.com/) is an Ubuntu-based Linux distribution. It would be great if it could be added to the list of distributions that support `apt-get`. Its `distro.id()` is `pop`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Sure, thanks for the suggestion @jwillikers 

That should be an easy one, do you want to submit the contribution yourself?

**Comment by jwillikers** [comment]
I can do that.
