### ISSUE TITLE
referencing settings or options in source method

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#1594]
After few days using conan, I am realizing that accessing options or settings in the source method of a recipe is an error : The settings/options at source time influence the source cache, and later build will reuse these cached sources, regardless of the build time settings and options.
The [documentation](http://docs.conan.io/en/latest/howtos/cross_building.html#creating-toolchain-packages) itself gives an example of source method influenced by settings . In this example, the usage of tools.OSInfo() seems wrong too, because the source packaged on a remote can be used from several OSes.
I think the example for the toolchain example linked above shows a proper build method, not source. A correct source method would have to download all the possible combination of os and compiler version.
As proper example, [mingw-installer](https://github.com/lasote/conan-mingw-installer/blob/master/conanfile.py) and [cmake-installer](https://github.com/lasote/conan-cmake-installer/blob/master/conanfile.py) have no source method.
The [the source method documentation](http://docs.conan.io/en/latest/reference/conanfile/methods.html#source) should advise against using settings, options, and tools.OSInfo in source, and advise to gather the full sources covering all combinations supported by the package. Is it also possible that the linter warns on usage of settings, options, and tools.OSInfo ?

**Comment by memsharded** [comment]
I agree, that documentation has to be fixed. You are right, the ``source()`` method has to be valid for all packages, irrespective of configuration.

Lets keep this here, but you can also submit issues (and also PR) to the https://github.com/conan-io/docs repo. 

Thanks for noticing.

**Comment by memsharded** [comment]
The source() method documentation has been improved with a very clear notice about this. Also the toolchain docs.

I have checked if a linter, warning or whatever made sense, but the use case for different OS will fire false positives, and just filtering for that would be too specific, so I think clear docs would be enough.
