### ISSUE TITLE
[question]  The 'CMakeUserPresets.json' generated by 'conan install' seems that it can not be used in 'Visual Studio 2019'.

### ISSUE THREAD

**Issue by fancygit** [conan-io/conan#15940]
### What is your question?

Here is my conanfile.py:
[conanfile.txt](https://github.com/conan-io/conan/files/14739832/conanfile.txt)

Here is the presets file:

[CMakePresets.json](https://github.com/conan-io/conan/files/14739877/CMakePresets.json)

And when I open the CMakeLists.txt in visual studio 2019,  it can not find the correct presets file.
![image](https://github.com/conan-io/conan/assets/2269316/a97f49d0-b10c-4f12-ab1e-26041dfac8a7)

Can you help me find how to use conan 2.0  in Visual Studio 2019.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by fancygit** [comment]
I have changed the IDE from vs2019 to vs2022, and it works.

**Comment by db4** [comment]
> I have changed the IDE from vs2019 to vs2022, and it works.

Are you sure that you run `conan install` with the correct compiler settings? What `compiler.version` does it report in host profile settings?

**Comment by fancygit** [comment]
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.version=192
os=Windows

it's setted as above.

**Comment by fancygit** [comment]
So I just use vs2022 as an IDE, but the compiler is still vs2019, but it works.

**Comment by db4** [comment]
What CMake are you using? If it's the one that is bundled with Visual Studio 2019, it's probably too old for Conan (3.14, right)? Install recent CMake separately and I expect your presets to work.

**Comment by memsharded** [comment]
It is possible to tell Conan to target the ``192`` compiler version both from VS2019 and VS2022:

- For VS2019 it is the default, no need to specify anything else
- For VS2022, configuring ``tools.microsoft.msbuild:vs_version=17`` to force the VS2022, and the ``compiler.version=192`` will force the v142 toolset (needs to be installed in VS2022, besides the default, which is v143)


Thanks very much @db4 for the support, I agree the CMake version could be problematic, 3.14 is too old for Conan, but for presets the minimum necessary is 3.23

**Comment by fancygit** [comment]
> What CMake are you using? If it's the one that is bundled with Visual Studio 2019, it's probably too old for Conan (3.14, right)? Install recent CMake separately and I expect your presets to work.

Thx @db4 , I've already install the new Version of CMake that support presets fully, but Can you tell how to set in vs2019  so that I can use  the new Version of CMake instead of the old one.

**Comment by db4** [comment]
[This](https://stackoverflow.com/questions/58773901/configure-cmake-version-in-visual-studio-2019) answer suggests editing your `CMakeSettings.json`

**Comment by memsharded** [comment]
@fancygit any further feedback here? Did you manage to get this working for your use case?

I don't know if the comment above https://github.com/conan-io/conan/issues/15940#issuecomment-2020044116 made some sense to you?
