### ISSUE TITLE
[question] Can Conan be used for source only packages

### ISSUE THREAD

**Issue by LouChiSoft** [conan-io/conan#15954]
### What is your question?

We're evaluating if Conan can be used internally for a project. The project is made from a framework, a collection of modules that use said framework and an executable that uses both the framework and any number of the modules. Because of the nature of our project, it has a lot of templates and Cuda code, the easiest (and currently only) way to build the project is to have a single CMake target that has all the modules and framework included as source and build it that way.

But we still want to use Conan as a tool for versioning the framework and modules as well as managing which modules we need to include at any given time. Is there a way to setup Conan package so that when it's included all it does is pull the source code and add it to a given target in CMake?

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @LouChiSoft 

Thanks for your question.

Conan is not explicitly designed for that use case, but as it is quite flexible it allows to implement many different use cases and flows. As some examples, we have learned that there are users using it for Matlab, Labview, Python, Java, binary images, etc.

You can see that we even implemented a "source-only" approach for dependency management for golang even before go had go modules in https://docs.conan.io/1/howtos/other_languages_package_manager.html. This source flow is relatively simple to implement:

- You can ``package()`` almost anything you want in Conan packages, including sources. The recommendation for your case would be to put the sources in the final package, as the "artifacts" provided by that package. 
- You can safely drop the ``settings``, ``options``, etc from your packages, and a ``self.info.clear()`` in your ``package_id()`` method will ensure you only have 1 artefact for all binary configurations (the source code).
- Recovering artifacts from a dependency graph from a consumer is relatively easy, Using ``self.dependencies`` you can easily gather in the ``generate()`` method of a recipe the dependencies, and copy the files you want to your current one to build (or build directly from the sources in the packages, by location)


Of course I'd recommend moving forward to try to start building the project modularly, every package should be able to build its own binary, but I think it should be relatively easy to use Conan for managing just source packages.

**Comment by LouChiSoft** [comment]
Thanks for the assistance, I will look into that. I would love it if each component of the project could be built standalone, but right now it's a Cuda issue that no one in our team has been able to solve yet. But deadlines are deadlines, and since we can compile right now if we use source code packages, that's what we'll have to do until someone can figure out the issue

**Comment by memsharded** [comment]
@jcar87 has been doing some CUDA builds with Conan, so if you have any specific CUDA questions, do not hesitate to create new tickets for them.

**Comment by LouChiSoft** [comment]
Oh really, I might just do that. If this Cuda issue can be solved that would be huge for our team

**Comment by LouChiSoft** [comment]
Update: I managed to get the static binaries to build and link (turns out it was a cmake cache error) so we can move forward with standard static binary builds. But thanks for providing the tips for source code packages only anyway.

**Comment by memsharded** [comment]
> Update: I managed to get the static binaries to build and link (turns out it was a cmake cache error) so we can move forward with standard static binary builds. But thanks for providing the tips for source code packages only anyway.

Excellent, happy to hear that, thanks for the follow up
