### ISSUE TITLE
[build_requires] dependencies not added to activate_build.bat

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#1595]
```
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows

[build_requires]
gpcbin2c/0.1.1@jpgygax68/testing
```
I'm defining a build dependency in my profile, but `conan install` does not add the corresponding path to `activate_build.bat`:
```
@echo off
SET PROMPT=(motionflow) %PROMPT%
SET LIB=C:\Users\gygax\.conan\data\glbinding\2.1.2\highstreeto\testing\package\c85f9b402dd4d46acdf074e1c63b768a41181d7a\lib;C:/.conan\0t5n3khl\1\lib;C:\Users\gygax\.conan\data\glbinding\2.1.2\highstreeto\testing\package\c83d8b197f1a331ca3b55943846d427ad4f7f8e1\lib;C:/.conan\idp7idgd\1\lib;D:\libraries\lib;C:\mingw\mingw32\lib;D:\libraries\lib;C:\mingw\mingw32\lib;%LIB%
SET CL=/IC:\Users\gygax\.conan\data\glbinding\2.1.2\highstreeto\testing\package\c85f9b402dd4d46acdf074e1c63b768a41181d7a\include;/IC:/.conan\0t5n3khl\1\include;/IC:\Users\gygax\.conan\data\glbinding\2.1.2\highstreeto\testing\package\c83d8b197f1a331ca3b55943846d427ad4f7f8e1\include;/IC:/.conan\idp7idgd\1\include;;%CL%
```

Strangely, as you can see, one of the normal (not build-time) dependencies defined in the project's conanfile is being added - here's the project's conanfile:
```
[requires]
glew/2.0.0-1@lasote/vcpkg
glbinding/2.1.2@highstreeto/testing

[generators]
virtualenv
virtualbuildenv
virtualrunenv
```
I have to assume that this is owed to the `glbinding` recipe, since GLEW is not being added in the same way.

**Comment by lasote** [comment]
The `build_requires` packages are only downloaded/installed/executed when the package that includes it has to be built. Furthermore, the variables won't be included in any virtual environment script, the environment variables will be only available at build time.

The `virtualbuildenvironment` is not related with build_requires, is only setting common variables like CXX_FLAGS, LIBS, etc

**Comment by JPGygax68** [comment]
Thanks you! However it seems to me that `virtualbuildenv` should do this. Isn't it intended to allow developers to access the same tools that a recipe would have access to ?

**Comment by lasote** [comment]
No, it just offer the variables from AutoToolsBuildEnvironment and VisualStudioBuildEnvironment, any other env variable is available in the `virtualenv` generator, except the build_requires variables, that are only available at build time.
