### ISSUE TITLE
[question][conan2] clang-cl configuration for either (re)building everything, or linking with MSVC compatible binaries

### ISSUE THREAD

**Issue by LarrxX** [conan-io/conan#15953]
### What is your question?

I have a project using `clang-cl` for C++23 compatibility reasons (clang-cl has more compatibilities than the MSVC compiler), but I am exclusively developing for a Windows environment (using the Visual Studio 2022 compiler and tools).

I would like to use conan2 to streamline the dev process.

I tried setting up a profile to use clang-cl by following [this page](https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html) which seems a bit outdated since some of the options in there do not exist anymore. Here is the profile I ended up using:
```
[settings]
os=Windows
arch=x86_64
compiler=clang
compiler.version=17
compiler.runtime=static
compiler.cppstd=23
compiler.runtime_version=v143
build_type=Release

[buildenv]
PATH=+(path)C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/Llvm/x64/bin

[conf]
tools.cmake.cmaketoolchain:generator=Visual Studio 17
tools.build:compiler_executables={'c': 'clang-cl', 'cpp': 'clang-cl'}
```

But with this profile I have to rebuild all the binaries from conancenter, and a lot of them just fail to build (I tried both `conan install --build=missing` and straight out building the recipes from the conan index github).

However, clang-cl only differs in the compiler frontend from MSVC's cl, and generates ABI compatible binaries. We've actually been using MSVC compiled conan binaries with our clang-cl project successfully.

So I have 3 solutions in mind, but I'm afraid I don't know how to proceed with either of them:

1. Is there a way to configure conan (or a recipe) to build my project's source using clang-cl but to use msvc built dependencies?
2. How can I fix my clang-cl profile above to be able to build the binaries I want? (but I think this is more of a dependency's cmake configuration than a conan problem).
3. Maybe "cross-compile" using an msvc profile as the build profile and a clang-cl profile as a host profile to rebuild my dependencies? Would that work?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @LarrxX 

Thanks for your question.

I am afraid this might not be something regarding the Conan client but the recipes in ConanCenter, which might vary in the support for other compilers rather than the mainstream ones.

So in general for any configuration it would be good to:

- First validate that it works with the templates ``conan new cmake_lib`` and others, to see if the Conan integrations with minimal projects work
- Then, if some recipe in ConanCenter fails, it would be necessary to report against that specific recipe and version, with the details about the failure. It might be something to try to update in the recipe to support more compilers.

**Comment by LarrxX** [comment]
That's what I was afraid of.

Unfortunately there are too many recipes that fall and I can't afford to fix them all (or wait to get them fixed). 

So what about the other solutions I was thinking about? Is there a way to tell conan to build my sources with clang-cl but link with packages built with msvc?

I guess, the worst case scenario would be for me to create binary packages of all the dependencies I need. Would that work? How would I manage the dependencies between them in that case?

**Comment by memsharded** [comment]
> Unfortunately there are too many recipes that fall and I can't afford to fix them all (or wait to get them fixed).

Not necessarily that you fix them. Just reporting failures is useful, even if it might take some time for others from the community to fix, it will eventually help.

> So what about the other solutions I was thinking about? Is there a way to tell conan to build my sources with clang-cl but link with packages built with msvc?

Yes, this would be a case of per-package settings: https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns

You can do ``conan install . -s &:compiler=clang -s compiler=msvc ...`` to use clang for your current project, yet force the dependencies to use ``msvc``.

There are other approaches, like defining a custom binary "fallback" configuration in the ``compatibility.py`` plugin: https://docs.conan.io/2/reference/extensions/binary_compatibility.html#reference-extensions-binary-compatibility. You can define that when a binary is missing for your clang compiler, to fall back to a msvc one. That way, if you happen to enable builds for certain dependencies with clang, those will be used, and other dependencies will still fallback to msvc.


> I guess, the worst case scenario would be for me to create binary packages of all the dependencies I need. Would that work? How would I manage the dependencies between them in that case?

Building your own binary configuration is a very usual practice among Conan users: https://docs.conan.io/2/devops/using_conancenter.html. There is nothing really special to do, Conan will manage, mostly doing a ``conan create`` of the recipes you want from ``conan-center-index`` repo with the profiles you want and upload them to your server.

**Comment by LarrxX** [comment]
Thank you for your enlightening answers @memsharded !

> Not necessarily that you fix them. Just reporting failures is useful, even if it might take some time for others from the community to fix, it will eventually help.

OK, will do for the ones I encountered.

> Yes, this would be a case of per-package settings: https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns
> 
> You can do `conan install . -s &:compiler=clang -s compiler=msvc ...` to use clang for your current project, yet force the dependencies to use `msvc`.

Interesting. Would it be possible to put this in a profile? I could eventually upload the msvc dependencies in their own user/channel to filter them out.

> There are other approaches, like defining a custom binary "fallback" configuration in the `compatibility.py` plugin: https://docs.conan.io/2/reference/extensions/binary_compatibility.html#reference-extensions-binary-compatibility. You can define that when a binary is missing for your clang compiler, to fall back to a msvc one. That way, if you happen to enable builds for certain dependencies with clang, those will be used, and other dependencies will still fallback to msvc.

Also interesting, hadn't seen that yet.

> > I guess, the worst case scenario would be for me to create binary packages of all the dependencies I need. Would that work? How would I manage the dependencies between them in that case?
> 
> Building your own binary configuration is a very usual practice among Conan users: https://docs.conan.io/2/devops/using_conancenter.html. There is nothing really special to do, Conan will manage, mostly doing a `conan create` of the recipes you want from `conan-center-index` repo with the profiles you want and upload them to your server.

That's what I am trying to do :)
Guess my comment was misleading: I was saying I could create prepackaged binary only packages: https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html

But in that case, I would lose the dependency graph, and that's a shame (or could I copy it somehow?)

**Comment by memsharded** [comment]
> Interesting. Would it be possible to put this in a profile?

Definitely, you can put those in a profile ``[settings]`` section, one per line.

>  I could eventually upload the msvc dependencies in their own user/channel to filter them out.

About the user/channel, not really recommended anymore. Please do not use user/channel anymore to differentiate packages or binaries. Conan binary model should take charge of it, explicitly naming packages (with name, user, channel or version) after binary configuration isn't necessary and will bring more problems than solutions. You can mostly drop user/channel or if using them, just use always the same, like ``yourteam/stable`` and forget about it.

> But in that case, I would lose the dependency graph, and that's a shame (or could I copy it somehow?)

The ``conan export-pkg`` to package pre-compiled binaries will definitely preserve the dependency information and the dependency graph. Still, ``conan create`` is the preferred way to create packages when building them from source, as it has much better reproducibility guarantees and less potential build issues.

**Comment by LarrxX** [comment]
OK thanks for all your suggestions, this will give me plenty to work with. ❤️

**Comment by memsharded** [comment]
Excellent, happy to help 🙂 

I am closing this question as solved at the moment, then, but don't hesitate to create a new ticket for any further question you might have (as well as open tickets for ConanCenter packages that might be improved).

Thanks for the feedback!
