### ISSUE TITLE
[question] Different package revision (PREV) in header-only library

### ISSUE THREAD

**Issue by IgorIvanov-Kudan** [conan-io/conan#15960]
### What is your question?

Forwarding my question from Slack to here as suggested by @RubenRBS .

Looking at [`catch2` package](https://github.com/conan-io/conan-center-index/tree/master/recipes/catch2/2.x.x) for example:
```
$ conan create . catch2/2.13.7@ -s build_type=Release
...
catch2/2.13.7 package(): Packaged 1 '.txt' file: LICENSE.txt
catch2/2.13.7 package(): Packaged 3 '.cmake' files: ParseAndAddCatchTests.cmake, Catch.cmake, CatchAddTests.cmake
catch2/2.13.7 package(): Packaged 5 '.hpp' files
catch2/2.13.7: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
catch2/2.13.7: Created package revision 40bd8970ec93fb5a33e823c8edb1461b

$ conan create . catch2/2.13.7@ -s build_type=Debug
...
catch2/2.13.7 package(): Packaged 1 '.txt' file: LICENSE.txt
catch2/2.13.7 package(): Packaged 3 '.cmake' files: ParseAndAddCatchTests.cmake, Catch.cmake, CatchAddTests.cmake
catch2/2.13.7 package(): Packaged 5 '.hpp' files
catch2/2.13.7: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
catch2/2.13.7: Created package revision ce0071a603eeb7bbd5ead3aaa7dd0b1b
```
You can see that `build_type` does not affect package ID generation, as `catch2` is header-only by default. Yet despite Conan packaging the same files, the PREV is different.
If I `conan create && conan upload` the package on my CI, in Artifactory even the `conan_package.tgz` will have identical sha256 sums.
I also noticed that `conaninfo.txt` will still contain the settings used (compiler, os, etc.) in `[full_settings]` section.

This is not `catch2` specific, I can see this in our custom recipes using `def package_id(self): self.info.clear()` as well.

I _assume_ this is intended, but why? Shouldn't PREV depend only on actual contents of the package?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @IgorIvanov-Kudan 

Thanks for your question.

This is an effect of some legacy Conan 1 design of ``conaninfo.txt``, including extra information not related to the binary compatibility of the artifacts.

This doesn't happen in Conan 2, and it should get there the same ``package_revision``.

**Comment by IgorIvanov-Kudan** [comment]
> This doesn't happen in Conan 2, and it should get there the same package_revision.

Was hoping to hear exactly that! :grin: Ticket can be safely closed.

And this is not something that is going to be fixed for Conan 1, right?

**Comment by memsharded** [comment]
> And this is not something that is going to be fixed for Conan 1, right?

yes, this would be massively breaking in Conan 1, quite challenging.

If you want to avoid that, maybe doing a ``conan create --build=missing`` can save you that, because it can go to the server, see that the package is already there and skip the creation of a new package-revision.

Closing as solved in Conan 2, thanks!
