### ISSUE TITLE
[question] Tips for setting up Cuda packages

### ISSUE THREAD

**Issue by LouChiSoft** [conan-io/conan#15961]
### What is your question?

Hi @jcar87, hopefully you don't mind the ping too much, @memsharded mentioned that you have been doing some Cuda build with Conan and I was hoping to get your input on setting up Cuda packages. The main one is around things like setting architecture flags. With our project being a single pipeline built up from multiple composable libraries things like architecture needs to be consistent across all the packages. Is there a method to propagate architecture flags down from the top so that everything is always aligned?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Duplicated to https://github.com/conan-io/conan/issues/15962?

**Comment by memsharded** [comment]
Duplicated, follow discussion in https://github.com/conan-io/conan/issues/15962, closing this one, thanks.
