### ISSUE TITLE
[question] download generic zip (non-conan package) from artifactory

### ISSUE THREAD

**Issue by veljkosbbb** [conan-io/conan#15966]
### What is your question?

Hi,

with conan install I am installing some local generated packages (mostly source code) to be used for C++ projects, but now I need to download and install (copy) source code from some zip packages (non-conan packages) to be installed (copied) into the C++ project before the build starts.

I have a test repository of Generic type in Artifactory which holds some zip files. I would like to download those packages using the conan.

I have added that remote succesully.

`(conan remote add conan-af https://artifactory.domain.dev/artifactory/api/conan/test)`

With conan remote set-auth I have done the login as well.

Now I have folder and file in that repo: components/FA/fa.zip

As I saw with conan install --requires I will not be able to download non-conan package? Am I wrong???

So I tried option conan download

`conan download -r conan-af https://artifactory.domain.dev/artifactory/api/conan/test/components/FA/fa.zip`

Error: ERROR: 404: Repo 'test' was not found. [Remote: conan-af]

While if I paste the same URL in browser, or use curl, my file is being downloaded automatically

How I can download it or install it using conan?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @veljkosbbb 

Thanks for your question.

Conan repos are for Conan packages, but not for generic artifacts like a ``fa.zip``. Those should live in generic repos.

Package ``conanfile.py`` recipes can download sources from any http server, you can find more information about it in https://docs.conan.io/2/tutorial/creating_packages/handle_sources_in_packages.html

> So I tried option conan download

``conan download`` is exclusively to download Conan packages, not for arbitrary zip folders.

**Comment by veljkosbbb** [comment]
Hi @memsharded 

Thanks a lot for your kind assistance to answer.
Yes, we understand that Conan repos are for Conan packages.

But my question is quite opposite - is it possible with Conan to download packages from Artifactory repositories with Generic or Maven types?
If this is not possible, can you please be direct with the answer.

In your example: main.zip does it contain conan package with conanfile or some generic source code files without any conan files?

Also by using the **source/get**  how we can propagate credentials to connect to the JFrog artifactory?
Thanks a lot once again!

**Comment by memsharded** [comment]
> But my question is quite opposite - is it possible with Conan to download packages from Artifactory repositories with Generic or Maven types?
If this is not possible, can you please be direct with the answer.

yes, absolutely, the ``source()`` method in conan recipes can do downloads from wherever you want: github, sourceforge, your own artifactory generic repo, or any http server. The examples in https://docs.conan.io/2/tutorial/creating_packages/handle_sources_in_packages.html is explaining it:

```python
    def source(self):
        # Please, be aware that using the head of the branch instead of an immutable tag
        # or commit is a bad practice and not allowed by Conan
        get(self, "https://github.com/conan-io/libhello/archive/refs/heads/main.zip",
                  strip_root=True)
```
The ``get()`` function gets a url to any http server. The ``get()`` does both a download+unzip, if you want only the download you can call ``download(self, <url>, ...)`` instead.

This example in the ``main.zip`` it contains source code, whatever is in the github ``libhello`` repo, without any conanfile or anything like that, this is a pure http download of an archive/zip, not related to Conan packages (not the download of a conan package)

Authentication to the servers can be done with the ``source_credentials.json`` file: https://docs.conan.io/2/reference/config_files/source_credentials.html

**Comment by veljkosbbb** [comment]
Thank you @memsharded
for this detailed explanation and example.

We are using version 2.1.0
I've set up source_credentials.json file within the folder: **C:\Users\myUser\.conan2**
I also added source method in my conanfile.

```
from conan import ConanFile

from conan.tools.files import copy

from conan.tools.files import download

from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout 

class XHUB(ConanFile):
```

    requires = "fixcommon/1.1"  

    def source(self):
        download(self,"https://artifactory.domain.dev/artifactory/generic-snapshot-local/components/ADM/ADM_2020_1_0_Windows.zip",  "myfilename.zip", verify=False)        

    def generate(self):

        print(self.dependencies.values())

        for dep in self.dependencies.values():

            print(dep.package_folder)

            print(self.generators_folder)

            copy(self,"*", dep.package_folder+"/base", self.generators_folder+"/base")`

But when I run it,it seems that the source method is not being invoked at all.
Not getting any related message or error for it.
Does it have to be called explicitly in some way?

Extraction from the log.

````
======== Computing dependency graph ========
Graph root
    conanfile.py: C:\Projects\xhub1\conanfile.py
Requirements
    fixcommon/1.1#0d2c98d500facde4e5a95428fa0ea047 - Cache

======== Computing necessary packages ========
Requirements
    fixcommon/1.1#0d2c98d500facde4e5a95428fa0ea047:da39a3ee5e6b4b0d3255bfef95601890afd80709#356c940f0cc6a5b725631061ba1b9da8 - Cache

======== Installing packages ========
fixcommon/1.1: Already installed! (1 of 1)

======== Finalizing install (deploy, generators) ========
conanfile.py: Calling generate()
conanfile.py: Generators folder: C:\Projects\xhub1
odict_values([<conans.model.conanfile_interface.ConanFileInterface object at 0x00000129BA2DA510>])
C:\Users\e5614274\.conan2\p\b\fixco3f95863da2997\p
C:\Projects\xhub1
conanfile.py: Generating aggregated env files
conanfile.py: Generated aggregated env files: ['conanbuild.bat', 'conanrun.sh']
Install finished successfully`

```

**Comment by memsharded** [comment]
If you are doing ``conan install`` it only install the dependencies. If you want the source() method to be called you need to call ``conan source``. Please check https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html for more information.

**Comment by veljkosbbb** [comment]
Thank you, its clear now!
