### ISSUE TITLE
[feature] Remove duplicated display of cmd when configure() is called by Autotools

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#15970]
### What is your suggestion?

In configure() method of Autotools, there are these 2 lines:

```python
        self._conanfile.output.info("Calling:\n > %s" % cmd)
        self._conanfile.run(cmd)
```

The first line is useless and leads to duplicated display of cmd (which can be very long) in the terminal, since a `conanfile.run` also displays cmd in the terminal in conan v2.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for reporting @SpaceIm, sending PR to remove it.
