### ISSUE TITLE
Question: Is there better way to work with ccache?

### ISSUE THREAD

**Issue by hrkn** [conan-io/conan#1597]
Hi.

I'm trying to use conan with ccache.
But by reason of conan installs each package in separated directory, ccache tells "cache miss" and compiles *whole* sources in work tree after any package was updated (This is caused by -I compiler option change).

It seems the ccache might expects implicitly the each header files of modules would be stored in single directory.

Does conan have any good facilities to solve the problem?
(ex. Create & update some identical symbolic link which points to versioned packages)

Best Regards,

**Comment by lasote** [comment]
I know that some users are using ccache but I don't have any previous experience with it (with or without conan).
AFAIK ccache uses a global cache, it not attached to the project directory structure, am I right?
So, theoretically, it should work.

**Comment by memsharded** [comment]
I can confirm that there are conan users using ccache in production. Don't know the details of it, but up to my knowledge it is working fine. Sorry I cannot help further, I haven't used ccache myself either, but at least I wanted to tell that it is possible to use it with conan.

**Comment by hrkn** [comment]
@lasote  @memsharded 
You're right. Conan works good with ccache basically.
But point is more complicated.
Please let me figure out detail of the problem.

First of all ccache use "compiler options" as one of input for hash generation which use to determine the output object file is identical with generated on past.

As you know, conan generated header search paths are provided per package per version/user/channel/and other settings.
So, some package update triggers cache miss caused by the header search path on compiler option (passed as -I xxx) change.
Ccache treats this as "source file was updated" and invokes compiler, it won't pick up a cache.
I would like to reduce such cache miss case.

I think it is good to fix an header search path through package update.
(Ccache also watches each hash sums of the include files, so even though header search path are fixed ccache can detect each header file update and handle appropriately.)
I wonder if there is some good functionality to solve this with conan.

Any advice or comment?

**Comment by memsharded** [comment]
I am not sure about what could be optimized. Packages indeed have different paths for different settings, and ccache should fire a miss. Even if for more cases the headers will be the same irrespective of the settings, for different configurations, that is not true in the general case (as for generated headers, like config.h, which for example might be different for debug and release configurations).

Could you please elaborate a bit more on your idea? Thanks!

**Comment by hrkn** [comment]
"Cache miss" described above will happen to all of the related sources, not only the dependent of updates.
Please think about project with hundreds of sources.
Once any of package was changed, whole source will be re-compiled and it would take a long time.
That may suffer developers.

My wish is to prevent these build time increase.
As my opinion previously explained, some symbolic links may be helpful to make compile option fixed throughout the package update.
So if there is any kind of user definable hooks on package update, I thought I can take link update operation.

**Comment by hrkn** [comment]
Finally, I found `conan imports` may help this.

This is how I resolved.
I treat local conan repository as only the storage for dependencies and it never be referred on build directly. (It is similar to a git local repository.)
Write appropriate [[imports] section](http://docs.conan.io/en/latest/reference/conanfile_txt.html#imports) to project's `conanfile.txt` to "checkout" header/lib file into workspace directory.
If `conanfile.txt` has [import] section, after dependencies are "fetched", `conan imports` run subsequently and dependencies are "checked-out" from repository to project workspace.
Also the build system must configured as to refer right place for **files in workspace**.

After all, compiler command line arguments are not change toward package update, and ccache works fine!!

**Comment by lasote** [comment]
Hi @hrkn. I think I didn't understand the issue and why the imports solved it. 
The issue is, if any file in the package (in the local cache) changes, it won't use the cache, right? 
Questions:

- Why does the package in the local cache changes?  Are you installing different versions of your dependency and switching between them?
- Why importing them into the user workspace solves the issue?

**Comment by hrkn** [comment]
@lasote 
Hi. sorry for late reply.

> Why does the package in the local cache changes? Are you installing different versions of your dependency and switching between them?

Yes.
I installed the another version of packages.

> Why importing them into the user workspace solves the issue?

Ccache determines "need to recompile" if any part of compile command string changed.
`-I` option is no exception of the rule.
Here is some example of include/library directories part of compile options.
```
gcc -c src/bar.cc -o build/debug/src/bar.o -m64 -s -DNDEBUG \
-I"/home/hrkn/.conan/data/foo/1.0.0/hrkn/stable/package/de9...cb6/include" \
-Wl,-rpath="/home/hrkn/.conan/data/foo/1.0.0/hrkn/stable/package/de9...cb6/lib" \
-L"/home/hrkn/.conan/data/foo/1.0.0/hrkn/stable/package/de9...cb6/lib" \
-D_GLIBCXX_USE_CXX11_ABI=0
```
When I update `foo/1.0.0@hrkn/stable` to `foo/1.1.0@hrkn/stable`, all compile command will updated, and ccache determines _**whole sources**_ need to be recompiled.
Even whether each `.cc` file depends to `foo` package or not.

Then here is another one which used headers imported to `external/`
```
gcc -c src/bar.cc -o build/debug/src/bar.o -m64 -s -DNDEBUG \
-I"externals/include" \
-Wl,-rpath="externals/lib" \
-L"externals/lib" \
-D_GLIBCXX_USE_CXX11_ABI=0
```
As you see, there is no version numbers appear on compile command.
Then ccache handle recompile only necessary files which dependent header had been updated.

**Comment by lasote** [comment]
Thanks for the explanation @hrkn. Now I understand. 
Yes, the imports could be an option as you realized, I don't see a better workaround.

**Comment by daravi** [comment]
@hrkn I know this is an old issue. But for anyone finding this via search, you might also be able to set `hash_dir` to `false` in your `ccache` configuration.

**Comment by AndreyMlashkin** [comment]
Could please someone share ccache conan build profile? What exactly you override?

**Comment by jwillikers** [comment]
> Could please someone share ccache conan build profile? What exactly you override?

You can create symlinks from your compiler executables to point to the `ccache` executables and make sure they are first in `PATH`. This will use `ccache` for everything. Alternatively, you can prefix the compiler with the `ccache` command. See the documentation on [Run modes](https://ccache.dev/manual/4.9.html#_run_modes).
