### ISSUE TITLE
[feature] conan command to report current python and system for troubleshooting

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#15974]
### What is your suggestion?

Some runtime issues can be caused by the Python interpreter that is invoking Conan, or the environment it is on  (see https://github.com/conan-io/conan/issues/15892)

Oftentimes in issues I find myself asking users to report the shebang of the Conan command script - for further troubleshooting.

I could be useful if conan had a command, e.g `conan system report` that could give us some basics that help us troubleshooting, for example:
* The version of Conan
* The location of the Conan script that is currently running
* The python interpreter that is running command, if one is being used
* Alternatively, whether the executable is self-contained ("frozen")
* The CPU architecture that python is reporting (useful on systems that can run multiple architectures like arm64 macOS and Windows)
* The OS and version
* The actual/physical CPU type - to highlight cases where the process is running emulating the CPU architecture (Rosetta on macOS Apple Silicon, emulation on Windows ARM64, etc).

Over time we may consider expanding and perhaps reporting the default compiler or build environment, etc (e.g. is the SDKROOT variable defined on macOS, etc)

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
``conan version`` already displays the Python interpreter:
```
version: 2.3.0-dev
python
  version: 3.10.2
  sys_version: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
```

We can add there more information if needed, as it also has ``json`` output for machine parsing.
