### ISSUE TITLE
Meaning of error message: Locked options do not match computed options for google-benchmark package/recipe

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#15976]
### What is your question?

We are using Conan 1.62.

We are using the conan info command in conjuntion with a lockfile like this: 

`conan info conanfile.py --lockfile=conan.lock --graph=conan_dep_graph.html`

When running it we get the above mentioned error message:

`
##[error]failed with error: b'ERROR: google-benchmark/latest: Locked options do not match computed options\nLocked options:\nenable_exceptions=False\nenable_lto=False\nshared=True\nComputed options:\nenable_exceptions=False\nenable_libpfm=False\nenable_lto=False\nshared=True\n'.
`

I think the reason is that in the configure()/config_options() function dynamically options are removed. But why is that a problem?

The recipe looks like this (same like in OSS google-benchmark repo)

```
import os

from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.build import cross_building
from conan.tools.cmake import CMake, cmake_layout
from conan.tools.files import copy, get
from conan.tools.microsoft import check_min_vs, is_msvc
from conan.tools.scm import Version

required_conan_version = ">=1.53.0"

class BenchmarkConan(ConanFile):
    name = "google-benchmark"
    description = "A microbenchmark support library."
    license = "Apache-2.0"
    url = "https://github.com/conan-io/conan-center-index/"
    homepage = "https://github.com/google/benchmark"
    topics = ("google", "microbenchmark")

    package_type = "library"
    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "enable_lto": [True, False],
        "enable_exceptions": [True, False],
        "enable_libpfm": [True, False],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
        "enable_lto": False,
        "enable_exceptions": False,
        "enable_libpfm": False,
    }

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
        if self.settings.os != "Linux":
            del self.options.enable_libpfm

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")


# ... more recipe code omitted since not relevant likely
```

Thank you for your support.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @MTomBosch  - I believe this is a known issue in Conan 1.x that is resolved in Conan 2 with the `conan graph info` command  (the lockfiles in Conan 2 no longer list the options).

Pinging @memsharded in case there are known solutions for Conan 1.x that I'm not aware of!

**Comment by memsharded** [comment]
We would need a full reproducible case to really know what is happening, it is not possible to know without knowing exactly the profiles, the captured lockfiles, etc. 

In any case, I am afraid that I recall this is one of the lockfile issues in Conan 1.X that we never managed to address, there were some issues with the options being locked in the profiles that were too challenging to fix without breaking other things. Let's try to have a look to a repro case if possible, but it might not be solvable within 1.X scope.

**Comment by MTomBosch** [comment]
Actually we are using the google benchmark repo/package in conjunction with lockfiles so it should be quite easily reproducible on your side.
But the comment from jcar87 already helped in case you cannot reproduce it using above hint.

Thank you

**Comment by memsharded** [comment]
> But the comment from jcar87 already helped in case you cannot reproduce it using above hint.

Yes, I was trying to reproduce with ``conan info conanfile.py --lockfile=conan.lock --graph=conan_dep_graph.html`` (latest 1.X), but it was working fine from my side (I captured a lockfile for it first with ``conan lock create conanfile.py``), so I guess that I am missing some setup or configuration.


In any case, yes, this will be a Conan 1.X issue, already solved in Conan 2, the reason is that Conan 1.X lockfiles stored the profiles in it, and any difference in inputs made it error. Can we then close this question as solved in Conan 2? Thanks!

**Comment by MTomBosch** [comment]
Yes. We can close it then. Thank you.
