### ISSUE TITLE
[question] Can conan cache be cleared selectively?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#15971]
### What is your question?

e.g. there are several versions for one lib, only some versions needs to be cleared, any way?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @playgithub 

The `conan remove` command accepts a pattern, so if you know which versions you want to clear,  you can issue commands that way, e.g.

```
conan remove "zlib/1.2*"
```
this would remove all zlib 1.2 versions that match this pattern, but preserve more recent 1.3 ones for instance.

Recently `conan remove` also gained the ability to remove "least recently used" references - you can pass `--lru=5d` to remove recipes and binaries that have not been used in the past 5 days for instance
