### ISSUE TITLE
[bug] conan config install silently fails, fresh install

### ISSUE THREAD

**Issue by dindon-sournois** [conan-io/conan#15989]
### Describe the bug

Installing a custom conan profile silently fails from a fresh installation (2.2).

```bash
$ ls conan/profiles/
custom_profile.linux
$ export CONAN_HOME=$PWD/custom
$ conan config install conan/
Copying file remotes.txt to $PWD/custom/.
Installing settings.yml
Copying file custom_profile.linux to $PWD/custom/profiles
```

But $PWD/custom/profiles folder isn't created and the custom profile isn't copied. From what I've tested it works for 1.63.0

**Comment by memsharded** [comment]
Hi @dindon-sournois 

Thanks for your report.

I am not sure what is happening, I cannot reproduce it here.
In my case, the last line shows:
```
Copying file custom_profile.linux to /home/myuser/custom/profiles
# NOT
Copying file custom_profile.linux to $PWD/custom/profiles
```

It would seem that your ``$PWD`` hasn't been processed in your ``export`` command. Can you please type ``conan config home`` after the ``export``?

**Comment by memsharded** [comment]
Hi @dindon-sournois 

Any update here? Did you manage to solve the issue?

**Comment by dindon-sournois** [comment]
> Hi @dindon-sournois
> 
> Thanks for your report.
> 
> I am not sure what is happening, I cannot reproduce it here. In my case, the last line shows:
> 
> ```
> Copying file custom_profile.linux to /home/myuser/custom/profiles
> # NOT
> Copying file custom_profile.linux to $PWD/custom/profiles
> ```
> 
> It would seem that your `$PWD` hasn't been processed in your `export` command. Can you please type `conan config home` after the `export`?

Actually the "$PWD" was just my poor attempt at obfuscating my full path. I tried reproducing the issue but can't anymore. Sorry!

**Comment by memsharded** [comment]
No prob, happy that it is solved now. Don't hesitate to create new tickets for any further question you might have!
