### ISSUE TITLE
[question] Why does AutotoolsToolchain not respect tools.apple:enable_bitcode?

### ISSUE THREAD

**Issue by lagner** [conan-io/conan#15988]
### What is your question?

Hi everyone. 

I am building my project on iOS with bitcode setting enabled. Conan profile looks like this
```ini
[settings]
os=iOS
os.version=13.0
arch=armv8
compiler=apple-clang
compiler.libcxx=libc++
os.sdk=iphoneos
compiler.version=15
compiler.cppstd=20
build_type=Release

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.cmake.cmaketoolchain:user_toolchain=["build/ios-arm64/mobile-sdk/multi/cmake-toolchain-build-release"].
tools.apple:enable_bitcode=True
tools.apple:enable_arc=True

[buildenv]
```

The cmake dependencies work fine. However, the autotools projects do not respect the bitcode and arc settings.

Right now I can work around this with the following code in a conanfile
```python
def generate(self):
    tc = AutotoolsToolchain(self)
    if is_apple_os(self):
        if self.conf.get('tools.apple:enable_bitcode', check_type=bool)
            tc.extra_cflags.append('-fembed-bitcode')
            tc.extra_cxxflags.append('-fembed-bitcode')
```

But I'm confused, I have to do this in every recipe. 

How is it supposed to work in general? Is there any reason not to respect the settings in the common AutotoolsToolchain?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by SpaceIm** [comment]
There is already an issue: https://github.com/conan-io/conan/issues/12197

I've proposed https://github.com/conan-io/conan/pull/15027

**Comment by paulocoutinhox** [comment]
Im waiting two years and it still not merged :(
