### ISSUE TITLE
[question] Specifying specific setting for current package when using conan install --requires=...

### ISSUE THREAD

**Issue by tgurriet** [conan-io/conan#15984]
### What is your question?

Hello,

I'm currently using the latest version of conan: 2.2.2.

I'm using the `conan install --requires="my_lib/0.0.1" --generator=CMakeDeps --generator=CMakeToolchain -s:a build_type=Release` to generate a cmake toolchain and cmake config files to be used by a non-conan build system.

I would like the `build_type` of the generated cmake config files to be `RelWithDebInfo`, which I could generate with `-s:a <PACKAGE_NAME>:build_type=Release`, but I cannot specify a name for that anonymous package, it's saying:

`ERROR: Can't use --name, --version, --user or --channel arguments with --requires`.

Any idea on how to achieve that?

Thanks in advance,
Tom

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @tgurriet thanks a lot for your question.

You can specify the current package by using the `&:` syntax in place of the name of the current package. See https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns for further explanation, but maybe we should make it a bit more clear in the docs :)

Let me know if that helps

**Comment by tgurriet** [comment]
Sweet, thanks!
