### ISSUE TITLE
[bug] Requiring libunwind needs a dependency that doesn't exist

### ISSUE THREAD

**Issue by vmishelcs** [conan-io/conan#15996]
### Describe the bug

I am using the conanfile.txt below.
```
[requires]
libunwind/1.3.1
gtest/1.14.0
glog/0.7.0

[generators]
CMakeDeps
CMakeToolchain
```

I get the error
```
ERROR: Package 'xz_utils/5.6.1' not resolved: Unable to find 'xz_utils/5.6.1' in remotes.
```

Checking on ConanCenter, one of the dependencies of libunwind is `xz_utils/5.6.1`, but this package is not on ConanCenter.
https://conan.io/center/recipes/libunwind?version=1.3.1

### How to reproduce it

Use conanfile.txt

```
[requires]
libunwind/1.3.1

[generators]
CMakeDeps
CMakeToolchain
```

and run

```
conan install . --output-folder=build --build=missing
```

in console.

**Comment by vmishelcs** [comment]
I now see that this has been mentioned in another issue: https://github.com/conan-io/conan-center-index/issues/23381

**Comment by franramirez688** [comment]
Hi @vmishelcs, thanks for reporting this 😁 

It should not be a problem anymore (see https://github.com/conan-io/conan-center-index/pull/23322).

I just checked it and it ran OK:

```bash
$ conan install . --output-folder=build --build=missing

....

Graph root
    conanfile.txt: /home/develop/conan/mmmmm/conanfile.txt
Requirements
    libunwind/1.3.1#7bb7f19fff6dfa448bb5f1faee8ff850 - Downloaded (conancenter)
    xz_utils/5.4.5#a26a2d42ab9c3dabc151bbe1bf898e53 - Downloaded (conancenter)
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Downloaded (conancenter)
Resolved version ranges
    zlib/[>=1.2.11 <2]: zlib/1.3.1

....

conanfile.txt: Generating aggregated env files
conanfile.txt: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
```

Could you try it again to verify it's working on your side?

UPDATED:
@vmishelcs Add `--update` to tell Conan that you'd like to use the latest revision: `conan install . --output-folder=build --build=missing --update`

**Comment by vmishelcs** [comment]
@franramirez688 Adding the `--update` option solved the issue. Thanks! 😁
