### ISSUE TITLE
[question] How do I set/change the location of the test_package information

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#16008]
### What is your question?

# How do I set/change the location of the test_package information?

The standard conan location for it's `test_package` folder breaks my company's standards. All tests must reside under an appropriately named folder rooted under `tests`

For example:

```
tests/unit
tests/integration
tests/network
```

I want to use conan's test_package ability, but I'll need to move it to something like `tests/package` or `tests/conan_packaging`, etc.

How can I achieve this?

I was thinking it might be in the [`self.cpp_info`][1] section but I don't see a way to change that mapping.

I did find the [`cmake_layout:test_folder`][2], however, that appears to change where the test code is built, not change the location of the `test_package`

[1]: https://docs.conan.io/2/reference/conanfile/methods/package_info.html#cpp-info-library-and-build-information
[2]: https://docs.conan.io/2/reference/tools/cmake/cmake_layout.html#cmake-layout:~:text=tools.cmake.cmake_layout%3Atest_folder

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @RochaStratovan 

the ``test_package`` folder can be defined in command line: ``conan create . --test-folder=path/to/my/test_package``

The conf ``tools.cmake.cmake_layout:test_folder`` is only about the "build" of the ``test_package``, not about the location of the ``test_package`` itself.

**Comment by RochaStratovan** [comment]
Oh. Nuts. So this is something that my devs would have to remember to add manually to the `conan create` or `conan export-pkg` CLI entries? That's unfortunate.

Can a feature be added to allow the `test_package` location to be identified in the `conanfile.py` file?

**Comment by memsharded** [comment]
> Can a feature be added to allow the test_package location to be identified in the conanfile.py file?

yes, this makes sense, lets add it.

**Comment by memsharded** [comment]
Added in https://github.com/conan-io/conan/pull/16013 for next Conan 2.3 release
