### ISSUE TITLE
[question] How do I get CMake transitive links to work with conan?

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#16007]
### What is your question?

# How do I get CMake transitive links to work with conan?

<details><summary>Environment</summary>

| What          | Version |
|---------------|---------|
| conan         | 2.2.2   |
| python        | 3.12.1  |
| cmake         | 3.23.1  |
| visual studio | VS2022  |

</details>

Problem Summary

I have a CMake project with a dependency tree that is similar to the following

```bash
app-A
└───lib-B (static)
    ├───sublib-C (static)
    ├───sublib-D (static)
    └───sublib-E (static)
```

Where lib-B includes the sub libraries as public linkage since users of lib-B
will need to link with the sub libraries too.

<details><summary>Example of lib-B's CMake usage of sublib-D</summary>

```cmake
...
find_package(sublib-C REQUIRED)
target_link_libraries(${TARGET} PUBLIC sublib-C)
find_package(sublib-D REQUIRED)
target_link_libraries(${TARGET} PUBLIC sublib-D)
find_package(sublib-E REQUIRED)
target_link_libraries(${TARGET} PUBLIC sublib-E)
...
```

</details>

When this is done with pure CMake it works fine. The `INTERFACE_LINK_LIBRARIES`
for `lib-B` correctly references/identifies `sublib-C`, `sublibD` and
`sublib-E`.

I changed `lib-B` to a conan package. I am using the same CMake I'm just using
conan to create a package from it. I have not converted the sub libraries to
conan, only `lib-B`.

If I now use `lib-B+conan` for `app-A` it won't compile because the conan
generated CMake files aren't listing any of the sub libraries for `lib-B`s
`INTERFACE_LINK_LIBRARIES` interface.

I know conan is widely used, so I cannot imagine this doesn't work. So, how can
I get this to work correct?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @RochaStratovan 

Just to understand, you want to create a package for ``libB`` that packages all the for libraries B, C, D and E, is this correct?

There are 2 approaches:

- List the 4 libraries in ``self.cpp_info.libs = ["libb", "libc", "libd", ...]`` in the right link order
- Define components. This allow more control and selective linkage from consumers

If you are always linking libB, then the first approach will be much simpler

**Comment by RochaStratovan** [comment]
Hello @memsharded 

That is not what I was asking bout. The sub libraries are not packaged in conan, nor do I want them packaged, in some cases they cannot be packaged because they are system libraries.

I want to know how to configure conan so that the CMake files it generates for usage with `conan install .` work for transitive upstream dependencies.

Forgive me if this is already common knowledge for you..... In the CMake world, when you define library dependencies it looks like the following:

```
find_package(sublib-C REQUIRED)
target_link_libraries(lib-B PUBLIC sublib-C)

find_package(sublib-D REQUIRED)
target_link_libraries(lib-B PUBLIC sublib-D)

find_package(sublib-E REQUIRED)
target_link_libraries(lib-B PUBLIC sublib-E)
```

This sets the `INTERFACE_LINK_LIBRARIES` property for `lib-B` to identify that you also need to link with `sublib-C`, `sublib-D` and `sublib-E` (_actually, the PUBLIC keyword also adds the include pats for the sublib's too_). Think of it as transitive linking. 

In `app-A` it will have logic like the following:

```
find_package(lib-B REQUIRED)
target_link_libraries(app-a PRIVATE lib-B)
```

This will cause `app-a` to link with `lib-B` as well as with all the transitive upstream sublib entries identified in `lib-B`s `INTERFACE_LINK_LIBRARIES` property.

This works correctly for "autogenerated" modern CMake relocatable packages. It does not work when I use conan's "autogenerated" CMake files from `conan install .`.

For a real world example, consider the 3rd Party `Chilkat` library. It's distributed as a binary.

* Chilkat[Linux] requires usage of the `pthread` and `dl` system libraries.
* Chilkat[Windows] requires usage of the `crypt32.lib`, `ws2_32.lib`, `dnsapi.lib` system libraries.

The `CMake` way is that you only need to add `Chilkat` using something like:

```
find_package(Chilkat REQUIRED)
target_link_libraries(${TARGET} <SCOPE> Chilkat)
```

Where \<SCOPE\> is PUBLIC, PRIVATE or INTERFACE, as appropriate.

The above causes `${TARGET}` to link with Chilkat as well as the libraries that Chilkat requires.

How do I get this to work correctly in conan? How do I configure conan so that it correctly propagates transitive library dependencies like this. Especially since downstream libraries cannot always be "_conan-ized_".

Aside from that, there are additional link and build properties that might be transitively acquired from a downstream library too these would be values set with CMake commands such as

```
# can add compile time flags to be used by anyone that uses lib-B
target_compile_options(lib-B <SCOPE> <option>)

# can add link time flags to be used by anyone that uses lib-B
target_link_options(lib-B <SCOPE> <option>)
```

**Comment by memsharded** [comment]
> That is not what I was asking bout. The sub libraries are not packaged in conan, nor do I want them packaged, in some cases they cannot be packaged because they are system libraries.

If you want to link ``libb`` which is a static library, and ``libc``, ``libd`` are also static libraries, the ``libb`` doesn't contain the code or symbols of the other transitive dependencies. So there are 3 possibilities:
- The ``libc``, ``libd`` libraries are also packaged inside the package and made them available to the consumers to link
- The ``libc``, ``libd`` libraries are assumed to be in the system, and they will be in the consumer system when they are necessary. For this case, they can be added to ``self.cpp_info.system_libs = ["libc", "libd", ...]``
- The ``libb`` is an special archive which is actually re-archiving the transitive dependencies ``libc``, ``libd`` into it. This is pretty unusual, but it can be done. If that is the case, nothing needs to be done, just declaring ``self.cpp_info.libs = ["libb"]`` will work, because it contains a copy of the code, symbols, etc inside it.


I think you are looking for the ``self.cpp_info.system_libs`` specifier then?

**Comment by RochaStratovan** [comment]
Based on your response, it sounds like conan doesn't honor the CMake transitive properties of the library it packages. Which is a limitation I can kind of understand since conan is being made to work for all compile infra, but it is alarming that basic CMake functionality like this won't work with conan.

What you explain sound like workarounds for getting the library dependencies to work, but how would this share the transitive link or compile options?

For us I guess we'll have to continue to generate the CMake relocatable packages, and use the logic to skip conan generated cmake logic and instead include the CMake relocatable package files in the package and use that.

This is loosely related to another issue you helped me understand at one time. We were hoping to go with a "pure" conan solution, but loosing basic CMake functionality like this is huge. Although, I suppose this could be the exact reason conan allows one to use the CMake logic provided in the package rather than the conan logic.

Thank you for your help.

**Comment by memsharded** [comment]
> Based on your response, it sounds like conan doesn't honor the CMake transitive properties of the library it packages. Which is a limitation I can kind of understand since conan is being made to work for all compile infra, but it is alarming that basic CMake functionality like this won't work with conan.

I am not sure I am fully understanding your issue.

This isn't even related to CMake build system or Conan. If you are building with any build system a static library, that depends on other static libraries, those other transitive static libraries need to be packaged or copied together with the static library or they should be in the system. It seems that you don't want to package those static libraries, but this is not possible, irrespective if the build system of that package is CMake, Meson, Autotools or any other. And if they are system libraries, then they don't need to be packaged, but they need to be in the system when linked. There is nothing in any build system that can avoid packaging the transitive static libraries (except the re-archiving and bundling them).

For both cases there is Conan functionality to manage it, like ``system_libs`` or defining ``components`` if desired. I don't understand what is the use case that is not covered.

What am I missing?

**Comment by RochaStratovan** [comment]
Hmmm... this is hard.... I get your points and I can see them from a purely
"packaging" lens, and I'm looking at this from a CMake build lens. You seem to
be worried about things that are true, but beyond or after the problem I'm
describing. Those would be second tier problems after this layer I'm referring
too.

I'm hoping the following will make it more clear.

Consider the simplified dependency graph

```
app-A ---> lib-B ----> lib-C
```

* `app-A` uses `lib-B`
* `lib-B` uses `lib-C`

To create `app-A` it will need to link with `lib-B` and `lib-C`.

`lib-B` sets up it's dependency on `lib-C`.

```
add_library(lib-B STATIC ${LIB-B-SOURCES})
target_link_libraries(lib-B PRIVATE lib-C)

# suppose lib-B requires the definition of the macro LIB_B_MEMGUARD for
interacting with it's header files.
target_compile_definitions(lib-B INTERFACE -DLIB_B_MEMGUARD=1)
```

This causes the `lib-B` target in cmake to have various CMake properties, one
of which is `INTERFACE_LINK_LIBRARIES` which will have `lib-C` in it's
list. And an `INTERFACE_COMPILE_DEFINITIONS` with the value `LIB_B_MEMGUARD=1` in
it's list.

<br>

**CMake Relocatable Package**<br>
If this is a standard modern relocatable package that is generated by the CMake
functionality it creates a CMake file set which is usable with the
`find_package()` logic.

When the `lib-B` package is found its CMake logic is included some of which is

```
add_library(lib-B STATIC IMPORTED)

set_target_properties(lib-B PROPERTIES
   INTERFACE_INCLUDE_DIRECTORIES "${IMPORT_PREFIX}/include"
   INTERFACE_LINK_LIBRARIES "lib-C"
   INTERFACE_COMPILE_DEFINITIONS "LIB_B_MEMGUARD=1
)
```

<br>

**Hand crafted/Legacy Packages**<br>
Many projects custom create their own cmake logic to be utilized with the
`find_package()` command. Even the custom created cmake logic would add logic
like the above to pass along the transitive CMake dependencies.

<br>

**Usage:**

The application `app-A` needs to use `lib-B` so it has logic such as

```
add_executable(app-A ${SOURCES})

find_package(lib-B REQUIRED)
target_link_libraries(app-A PRIVATE lib-B)
```

This searches for the CMake package `lib-B` and includes/incorporates `lib-B`'s
CMake files, part of which is the definition of the imported static library.

This causes lib-B to be added to lib-A's link list.

Moreover, as part of that interaction the CMake logic see the transitive need
for lib-C and adds lib-C to lib-A's link list.

Finally, it sees that we have the transitive compile definition of
LIB_B_MEMGUARD=1, and that define is provided to the compile of each of
`lib-A`'s source files.

This is how basic modern CMake behaves.

<br>

**Conan Interaction**<br>
When conan is used in this equation, conan is generating the cmake files that
`find_package(lib-B...)` will interact with.

However, the CMake logic that is generated by `conan install` and incorporated
via by passing `-DCMAKE_TOOLCHAIN_FILE="<path-to-toolchain-file"` is missing
the `INTERFACE_LINK_LIBRARIES` and `INTERFACE_COMPILE_DEFINITIONS` values as
defined above.

<br>

The long and short of it is that conan generated CMake files
isn't creating an appropriate import library for lib-B.

I'm working on abstracting this to a "simple" example to illustrate this further and will upload to github tomorrow.

**Comment by memsharded** [comment]
The ``CMAKE_TOOLCHAIN_FILE`` will only point to the folders containing the cmake files, so ``find_package()`` finds and use them.

If we are talking about the cmake files generated by ``CMakeDeps`` they define the ``INTERFACE_COMPILE_DEFINITIONS``, see https://github.com/conan-io/conan/blob/767012b66a61ff350f8bd021e338bd504c3e222b/conan/tools/cmake/cmakedeps/templates/target_configuration.py#L114  (also ``INTERFACE_COMPILE_OPTIONS``, ``INTERFACE_LINK_LIBRARIES``, and others).

Maybe the issue that you are seeing is that this is not automatic, and it needs to be defined in ``cpp_info`` in the ``package_info()`` method. This is true, it is necessary to specify things in ``cpp_info``. Consider a few points:

- The consumer package might not use CMake at all, but other build system, so the CMake information is useless.
- It is impossible to automatically parse CMake code and automagically deduce the ``cpp_info`` abstraction from CMake files, it requires user definition in the recipe ``package_info()`` method.
- When the package is consumed, the CMake of the dependency is not even executed at all, it doesn't exist at all, it is not possible to rely on any behavior that the execution of CMake in the dependency provides. The building of the package is completely decoupled from the consumption of the package, they are not connected at all. You can even provide pre-compiled binaries without a build script, and things will keep working exactly the same.

Is this what you mean? If this is the issue, then as it seems you comment, you can package and use your ``xxx-config.cmake`` files inside the packages and not rely at all on the ``package_info()`` and ``cpp_info`` abstraction and not use ``CMakeDeps`` generated files, but your own in-package ones. But to use the ``CMakeDeps``, things need to be specified in the ``package_info()``, it is almost physically impossible to obtain it from the build ``CMakeLists.txt`` (or from other build systems like autotools or msbuild)

This situation might improve in the future with the CPS initiative we are working on, but as every standardization effort it might take some time.

**Comment by RochaStratovan** [comment]
Sorry for the delayed response. I was out of action yesterday due to food poisoning. Well enough now.

I had my demo logic 90% done when I left Wednesday evening, and I found your response today.

Thank you. This makes it clear again, and even though I don't like it, it makes sense. You're world is something that works for all build systems whereas my world is CMake only. I don't care about other build systems nor do I need that sort of flexibility, so I'm having to learn how to map from my specific world of CMake into your generalized world of conan. (growing pains).

While I feel like I know a simple enough way to have this work automatically for CMake projects, I can also see that this would make CMake on CMake easier, but might lead to challenges when folks are trying to use a different build system. The current method levels the playing field requiring all to map from their native build system to conan.

You are correct, I am not setting anything in the `cpp_info`.

Can you outline what fields I would set for INTERFACE_COMPILE_OPTIONS and
INTERFACE_LINK_OPTIONS to be set appropriately?

I found documentation for [cpp_info: Library and build information][1]. I see the references for `cpp_info.libs` and `cpp_info.system_libs` (you mentioned these before).

I see `cp_info.defines`, `cpp_info.cflags`, `cpp_info.cxxflags` etc. but due to their names I would imaging that they map to the legacy "project-wide" settings that are no longer recommended in modern CMake, where target specific settings are the new norm.

Thanks again for you patience and help.





[1]: https://docs.conan.io/2/reference/conanfile/methods/package_info.html#cpp-info-library-and-build-information

**Comment by memsharded** [comment]
> Sorry for the delayed response. I was out of action yesterday due to food poisoning. Well enough now.

No prob, happy to hear that you are better now!

> Thank you. This makes it clear again, and even though I don't like it, it makes sense. You're world is something that works for all build systems whereas my world is CMake only. I don't care about other build systems nor do I need that sort of flexibility, so I'm having to learn how to map from my specific world of CMake into your generalized world of conan. (growing pains).

> While I feel like I know a simple enough way to have this work automatically for CMake projects, I can also see that this would make CMake on CMake easier, but might lead to challenges when folks are trying to use a different build system. The current method levels the playing field requiring all to map from their native build system to conan.

Yeah, we keep working hard on improving the CMake integration, and also specifically on the CPS initiative to try to make this fully transparent for everyone. But at the moment, it is basically impossible to do it without a bit of repetition in the user Cmake files and in the Conan recipe ``cpp_info``. While this can be a bit annoying, in practice it is not that terrible, it is a one-time effort mostly, many packages can be done in just a few minutes, as the mapping is relatively straightforward.


> Can you outline what fields I would set for INTERFACE_COMPILE_OPTIONS and
INTERFACE_LINK_OPTIONS to be set appropriately?

Yes, they will be mapping to the ``cflags`` and ``cxxflags`` for the C and CXX ``COMPILE_OPTIONS`` and to the ``sharedlinkflags`` and ``exelinkflags`` (different for shared libs and exes) for the ``INTERFACE_LINK_OPTIONS``

> I see cp_info.defines, cpp_info.cflags, cpp_info.cxxflags etc. but due to their names I would imaging that they map to the legacy "project-wide" settings that are no longer recommended in modern CMake, where target specific settings are the new norm.

No, they can be defined per ``component`` too. They are applied to the ``targets``, something like:
```
 set_property(TARGET {{ comp_target_name }} APPEND PROPERTY INTERFACE_LINK_OPTIONS
                             $<$<CONFIG:{{ configuration }}>:{{tvalue(pkg_name, comp_variable_name, 'LINKER_FLAGS', config_suffix)}}>)
                set_property(TARGET {{ comp_target_name }} APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
                             $<$<CONFIG:{{ configuration }}>:{{tvalue(pkg_name, comp_variable_name, 'INCLUDE_DIRS', config_suffix)}}>)
                set_property(TARGET {{comp_target_name }} APPEND PROPERTY INTERFACE_LINK_DIRECTORIES
                             $<$<CONFIG:{{ configuration }}>:{{tvalue(pkg_name, comp_variable_name, 'LIB_DIRS', config_suffix)}}>)
                set_property(TARGET {{ comp_target_name }} APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS
                             $<$<CONFIG:{{ configuration }}>:{{tvalue(pkg_name, comp_variable_name, 'COMPILE_DEFINITIONS', config_suffix)}}>)
                set_property(TARGET {{ comp_target_name }} APPEND PROPERTY INTERFACE_COMPILE_OPTIONS
                             $<$<CONFIG:{{ configuration }}>:{{tvalue(pkg_name, comp_variable_name, 'COMPILE_OPTIONS', config_suffix)}}>)
```
So they are "modern", they will only apply to your executables and shared libraries if you really ``target_link_libraries()`` those packages or components.

**Comment by memsharded** [comment]
> Thanks again for you patience and help.

Thanks to you for your continuous feedback! Happy to be able to support you 🙂
