### ISSUE TITLE
[question] How do I mix Debug and Release libraries using conan?

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#16002]
### What is your question?

# How do I mix Debug and Release libraries using conan?

There are plenty of times when we use a 3rd party binary distribution library
that is only available in the Release build configuration.

How can we use conan to create a debug image of our product that will correctly
work with the release version of the 3rd party library.

We are using Visual Studio 2022 on Windows, so it's multi configuration, as
well as Ubuntu 20 Linux (gcc).

We have the 3rd Party binary in a conan package and the steps I use in my
product are

I use `conan install .` to pull the 3rd party library into my local cache and
provide me with the toolchain logic that I pass into my `cmake` command to
generate the visual studio files.

Then use the VS IDE with the generated `.sln` file.

However, this only sets up the _Release_ build to use the 3rdParty package. How
do I use conan to use the _Release_ version of the 3rd Party Binary with any
configuration I use? Would this be a matter of changing the 3rd Party package
to not include a `build_type` setting? Or is there some other way?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your question @RochaStratovan 

> How can we use conan to create a debug image of our product that will correctly
work with the release version of the 3rd party library.

Well, this might not be possible for all cases. For example, it is very common that Debug builds in Visual Studio need to build with Debug artifacts (specifically with Debug artifacts linked with the debug runtime), and linking with Release artifacts (linked with the release runtime) will simply refuse to link. For other platforms such as Linux this is less of an issue and typically possible.

> There are plenty of times when we use a 3rd party binary distribution library
that is only available in the Release build configuration.

If you manage to have a binary that is really build-type agnostic then the best way is to just drop it from the ``settings = "os", "compiler", "arch"``.  I guess that also in many cases they are created with ``conan export-pkg``, not built from source.

> However, this only sets up the Release build to use the 3rdParty package. How
do I use conan to use the Release version of the 3rd Party Binary with any
configuration I use? Would this be a matter of changing the 3rd Party package
to not include a build_type setting? Or is there some other way?

If the ``build_type`` is removed from the dependencies, then the consumers should work as usual doing ``conan install . -s build_type=Release`` + ``conan isntall . -s build_type=Debug`` will create the multi-config project, and both the Debug and Release configurations will be pointing to the same dependency binary, as it doesn't depend on the build-type.

**Comment by RochaStratovan** [comment]
Thanks you @memsharded,

I believe you are saying I need to remove `build_type` from the conan package I generate for the 3rd Party library so it becomes valid for any `build_type`?

Then if creating a debug image I could do

```
conan install . build_type=Debug
```

which would pull in the 3rd Party package because it doesn't have a `build_type` limitation?

**Comment by memsharded** [comment]
Yes, exactly ``conan install . build_type=xxxx`` will always pull the same dependency for the 3rd party package, no matter the value of ``xxxx``, because that third party package doesn't depend on the ``build_type`` at all (that is the effect of removing it from the settings, making the package binary independent of the build-type)

**Comment by RochaStratovan** [comment]
Awesome! Thanks!
