### ISSUE TITLE
[feature] Command for running tests (or other executables) in local workflows

### ISSUE THREAD

**Issue by Ahajha** [conan-io/conan#16014]
### What is your suggestion?

See https://github.com/conan-io/conan/issues/1629 for initial motivation, it has been closed for some time so I thought I'd open a new one.

Essentially, I would like a `cargo`-esque workflow where I can ideally just run something like `conan test` and that will build and run the tests of my project.

On top of having that workflow, my ulterior motive here is to simplify build instructions in projects that use Conan to build, mainly with CMake. Currently, there's some logic to be processed depending on the build type and  whether the generator being used is multi-config (which people new to CMake would not know). This logic also has to be written in CI scripts, which tends to be ugly. I would like to be able to just write in a README (after the usual spiel of installing the necessary tools) to be "run `conan test` to build and run the tests".

Some details:
- I am primarily concerned with local workflows where a `conanfile.py` is defined for dependencies and as a build wrapper
- Whether or not the `conanfile.py` defines a package or is just used for consumption of other packages is not important
- I know `conan test` is currently reserved to only working with test packages. I think there is use in allowing normal conanfiles to define a `test()` method and then running them somehow

I propose the following to be added as a second function to `conan test`: If given just a path, performs the equivalent of `conan build` (with path and all positional arguments forwarded), then runs the `test()` method.

(I don't _think_ this can be emulated with a custom Conan command, but correct me if I'm wrong. That would be a wonderful first step)

Some stretch goals:
- If there are multiple things to run, perhaps it could be given more arguments to switch between them. For example, maybe `conan test main` would run an application and `conan test` would default to the unit tests (and `conan test unit_test` would explicitly run the unit tests). (Perhaps have `test()` take an argument and the routing can be done internally)
- Extremely minor QOL improvement, and would potentially be a separate proposal, but perhaps have `.` be the default path for a lot of conan commands.

Open to feedback on details of course.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ahajha 

Thanks for your suggestion.

I think this should be achievable already with the current tools. The normal flow is to add the testing in the ``build()`` method like:

```python
def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
    cmake.test()
```
This will already build and run tests when using ``conan build .``. 
Then the recommended way to disable testing if you don't want them is to use ``conan build . -c tools.build:skip_test``. The ``cmake.test()`` will not run in this case.

Is this what you are looking for?

**Comment by Ahajha** [comment]
Sorry for taking so long to respond - I was aware of this solution but for whatever reason I didn't think it would be as useful as having native commands. I guess I just felt it was odd that we could `test()` with test packages but not with normal ones. The solution you mentioned should work for me, thanks!
