### ISSUE TITLE
[question] Dependency of package not used, as minor version changed

### ISSUE THREAD

**Issue by florian-hubertSE** [conan-io/conan#16029]
### What is your question?

Hi,

I was not able to find something in the documentation about it.

We use conan as follows. A package specifies its requirements and only fixes the major version like

```python
class A(ConanFile):
    name = "A"
```
        
Now we build that package and deployed it to artifactory as version 0.0.0.1.

```python
class B(ConanFile):
    name = "B"
     def requirements(self):
          self.requires("A/[~0]")
```

Another Package C is using B.

```python
class C(ConanFile):
    name = "C"
     def requirements(self):
          self.requires("A/[~0]")
          self.requires("B/[~0]")
```

If we now create package A as v0.1.0.0, C is not building anymore, as its expects

> [settings]
> arch=x86_64
> build_type=Debug
> compiler=clang
> compiler.version=16
> os=Windows
> [options]
> shared=False
> [requires]
> A/0.0.Z

but uploaded is

>               info
>                 settings
>                   arch: x86_64
>                   build_type: Debug
>                   compiler: clang
>                   compiler.version: 16
>                   os: Windows
>                 options
>                   shared: False
>                 requires
>                   A/0.1.Z

So the package has a change in the minor version, but we would still like to use it, as we only look at the major version.
How can we force conan to use this package, as we would like to accept all packages, with the same major version?

In addition: Do we need to specify dependency A in C, if C is depending on B? I would assume no. But how is it with transitive dependencies?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @florian-hubertSE 

Thanks for your question.

I guess that from 

> If we now create package A as v0.1.0.0, C is not building anymore, as its expects

You mean that you are getting a ``Missing binary`` error? please try to be more specific in what is happening, that helps us to understand the issues.

I think what you are observing there is the binary model default behavior. Please have a detailed view to: https://docs.conan.io/2/reference/binary_model.html, see specially https://docs.conan.io/2/reference/binary_model/dependencies.html

There you will see it is possible to define and "relax" the assumptions of binary compatibility, changing the default modes for example, as explained in https://docs.conan.io/2/reference/binary_model/custom_compatibility.html#global-default-package-id-modes. 

However I'd strongly suggest to re-consider this approach. The conan defaults (minor-mode) is good, and together with the package-types it allows to have a "safe" policy of when it is necessary to build things. Having a too relaxed policy, like ``major_mode`` only it means that things will not get re-built, and this can be a big error, for example if you have an application that is linking static libraries, and you don't rebuild that application when the static libraries change, then the changes, bugfixes, etc will not be made part of the application, until the static libraries bump the major version. But this can be very bad for the product application.

**Comment by GRyzer** [comment]
Hi @memsharded 

I was able to reproduce the error, and have created the following Github repository: https://github.com/GRyzer/conan-dependency-error

Maybe you can use it to better understand our problem.

**Comment by memsharded** [comment]
Thanks for your repro case, it helps.

The behavior is totally expected.

If you type ``conan list bb:**``, you will see:

```
$ conan list bb:*
Found 1 pkg/version recipes matching bb in local cache
Local Cache
  bb
    bb/0.0.0.1
      revisions
        554f227c8f1d1674e37c9126afd8fe1a (2024-04-07 20:56:49 UTC)
          packages
            b8e83d72f6ff59aed56f53d6e91c430e68c2431f
              info
                settings
                  ...
                options
                  shared: False
                requires
                  aa/0.0.Z
```
It means the binary of ``bb/0.0.0.1`` is binary compatible with all the patch versions of ``aa``, that is ``aa/0.0.Z`` for any ``Z``.

When a new ``aa/0.1.0.0`` is available, it is a ``minor`` bump and it means it requires a new binary of ``bb`` to be built from source, this is the expected behavior, as explained in https://docs.conan.io/2/reference/binary_model/dependencies.html

Note that the default "minor_mode" is good because it allows full control:
- If the ``patch`` is bumped then it means that it is not necessary to rebuild the consumer
- If the ``minor`` is bumped it means that the headers are compatible, but they have changed, so it is necessary to rebuild the consumers from source
- If the ``major`` is bumped it means the headers have got a breaking change that requires code changes in the consumers.

**Comment by florian-hubertSE** [comment]
Thank you James, that helped us a lot!

We will look into and try to find the best suitable solution for us.

**Comment by memsharded** [comment]
Great, happy to help 🙂 

Don't hesitate to open new tickets for any further question you might have, thanks for the feedback!
