### ISSUE TITLE
[feature] CMake: support `CHECK_INCLUDE_FILE` and `CMAKE_REQUIRED_INCLUDES`

### ISSUE THREAD

**Issue by mmomtchev** [conan-io/conan#16039]
### What is your suggestion?

Currently, if I want to use `CHECK_INCLUDE_FILE` I must add the include directory manually to `CMAKE_REQUIRED_INCLUDES`.

This is something that is very often impossible, as `conan` uses generator expressions and `CMAKE_REQUIRED_INCLUDES` does not seem to support them.

Would it possible to simply add both the `Release` and `Debug` directories to `CMAKE_REQUIRED_INCLUDES`?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I think this might be related to https://github.com/conan-io/conan/issues/12012, could you please have a look?

The CMake checkers like ``check_c_source_compiles`` and others have always been a bit problematic, in the way they are affected by dependencies (when they shouldn't in many cases in my opinion). In general it would be recommended to use a more "imperative" approach: as it is known which dependencies are there, it is easy to generate variables like "THIS_DEP_EXIST", so it is not necessary to do things like ``check_include_file`` in the ``CMakeLists.txt`` files.

**Comment by valgur** [comment]
Setting `CMAKE_TRY_COMPILE_CONFIGURATION` to the current build type will probably resolve the issues you are having with the generator expressions in the include dir pahts. See the discussion in #12180.

It might not be an acceptable workaround, though, if you want to support multi-config CMake generators, like Visual Studio projects.

**Comment by mmomtchev** [comment]
Yes, indeed, `try_compile` with `CMAKE_TRY_COMPILE_CONFIGURATION` is a solution
