### ISSUE TITLE
[question] How to use "conan config install -cc" to set global.conf settings?

### ISSUE THREAD

**Issue by philipbe-intel** [conan-io/conan#16033]
### What is your question?

Hi folks,

I think I might be missing something really obvious here. The [documentation](https://docs.conan.io/2/reference/config_files/global_conf.html#user-tools-configurations) mentions that the `core.xxx` settings can be set with the CLI argument `-cc`, but when I use that, I don't seem to see that the settings are reflected in the `global.conf` file afterward.

I'm trying to issue the following command to set a different `storage_path` than the default location:
```
conan config install -cc=core.cache:storage_path=<path to my desired folder> -t=dir <path to my profile dir>
```

The command seems to execute successfully, but if I look at the `global.conf` file afterward it's still blank and `conan config show "*"` confirms that as well.

Does anyone know what I'm missing?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @philipbe-intel 

Thanks for your question.
Maybe this is a misunderstanding, it could be that our description of the behavior in the docs is not fully clear.

> I think I might be missing something really obvious here. The [documentation](https://docs.conan.io/2/reference/config_files/global_conf.html#user-tools-configurations) mentions that the core.xxx settings can be set with the CLI argument -cc, but when I use that, I don't seem to see that the settings are reflected in the global.conf file afterward.

This mean that the ``core.xxxx`` values are defined in memory when Conan executes, but it doesn't update the contents of the ``global.conf`` file. It is intended as a mean to override/complete/change the values of ``global.conf`` dynamically from the CLI, but not to permanently define values in ``global.conf``.

The recommended way to permanently modify ``global.conf`` is to modify the file (``conan config home`` gives easily the location), and if those configurations are meant to be more long lived, maybe shared with other devs and CI, then put that ``global.conf`` file inside a repo, or a Conan package and use ``conan config install`` or ``conan config install-pkg`` to update the configuration, including the ``global.conf`` file.

Please let me know if this clarifies the behavior.

**Comment by philipbe-intel** [comment]
Ah, thanks for clarifying! That makes more sense. I'll go with the recommended method and create my own `global.conf` that can be installed across systems.

Appreciate the quick feedback! Thanks again!

**Comment by memsharded** [comment]
> Appreciate the quick feedback! Thanks again!

Happy to help! 🙂 Don't hesitate to create new tickets for any further question you might have.
