### ISSUE TITLE
[question] Prevent default "buildPresets" and "testPresets" being generated in CMakePresets.json

### ISSUE THREAD

**Issue by tmiseikis** [conan-io/conan#16036]
### What is your question?

Hi, if you use `CMakeToolchain` generator in `conanfile.py` then default build presets and test presets called "conan-release" and/or "conan-debug" are included in the generated `CMakePresets.json` file. Is it possible to still generate the `CMakePresets.json`, but without the default "buildPresets" and "testPresets"? 

The reason I am asking is because I am providing my own build presets and I want to avoid people accidentally choosing the conan presets. I could obviously instruct conan not to generate the `CMakePresets.json`, however, I still need the configure preset called "conan-default" that is included in `CMakePresets.json` as it sets many useful options. I inherit this preset in my own configure preset.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tmiseikis 

Thanks for your question.

Maybe you are interested in this page: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets.html

Basically, if you are providing your own profiles, what you want to do is provide your profiles that extend the Conan ones. With this approach, all that would be necessary is to ignore the build and test presets and just provide your own without extending the Conan ones.

**Comment by tmiseikis** [comment]
Hi @memsharded 

Thank you for the link. I tried to follow the description, but it doesn't seem to achieve what I would like.

I've added the following to my **conanfile.py**:

```
def generate(self):
    tc = CMakeToolchain(self)
    tc.user_presets_path = "ConanPresets.json"
    tc.generate()
```

This generated "ConanPresets.json" file in my root directory:

```
{
    "version": 4,
    "vendor": {
        "conan": {}
    },
    "include": [
        ".../build/CMakePresets.json"
    ]
}
```

As you can see, this file includes the "build/CMakePresets.json" file that was auto-generated by Conan:

Now, in my own **CMakePresets.json** file I have the following:

```
{
    "version": 4,
    "include": ["./ConanPresets.json"],
    "configurePresets": [
        {
            "name": "default",
            "displayName": "Default Config Preset",
            "inherits": "conan-default"
        }
    ],
    "buildPresets": [
        {
            "name": "test",
            "displayName": "Test Preset",
            "configurePreset": "default",
            "configuration": "Release",
            "jobs": 4
        }
    ]
}
```

So my **CMakePresets.json** includes **ConanPresets.json** which includes **build/CMakePresets.json**. **build/CMakePresets.json** contains:

configurePresets: conan-default
buildPresets: conan-release and conan-debug
testPresets: conan-release and conan-debug

The only thing I really need from **build/CMakePresets.json** is "conan-default" **configurePresets**, because it sets e.g. "toolset", "architecture", "environment", "cacheVariables", etc... But in the current configuration it will also inherit all the **buildPresets** and **testPresets**, and they will show up in e.g. Visual Studio IDE. I would like to avoid that.

**Comment by memsharded** [comment]
> The only thing I really need from build/CMakePresets.json is "conan-default" configurePresets, because it sets e.g. "toolset", "architecture", "environment", "cacheVariables", etc... But in the current configuration it will also inherit all the buildPresets and testPresets, and they will show up in e.g. Visual Studio IDE. I would like to avoid that.

I see. 

I think you can very easily customize that with something like (not tested):
```python
def generate(self):
    tc = CMakeToolchain(self)
    tc.user_presets_path = "ConanPresets.json"
    tc.generate()
    presets = json.loads(load(self, "ConanPresets.json"))
    # remove what you don't want like ``del presets["buildPresets"]`` or the like
    save(self, "ConanPresets.json", json.dumps(presets, indent=2))
```

**Comment by tmiseikis** [comment]
@memsharded  - I see. So the idea is to simply delete the unneeded keys from the Conan generated presets file. That should work. Thanks!

**Comment by memsharded** [comment]
> I see. So the idea is to simply delete the unneeded keys from the Conan generated presets file. That should work. Thanks!

Yes, generators are not that magic, they are designed to be quite transparent and customizable by the user, this is the reason they are created in ``generate()``, but actually used later in the ``build()``
