### ISSUE TITLE
[bug] tools.build:verbosity=verbose is not setting CMAKE_VERBOSE_MAKEFILE=ON

### ISSUE THREAD

**Issue by Tails86** [conan-io/conan#16030]
### Describe the bug

OS: Ubuntu 22.04 (in WSL)
Compiler: gcc
Conan Version: 2.2.2
cmake version 3.28.3

Setting tools.build:verbosity=verbose does not seem to be setting CMAKE_VERBOSE_MAKEFILE=ON. I see [this issue](https://github.com/conan-io/conan/pull/13428) which seems to hint that it was added. The only way I can seem to get the output I want is to edit my `generate()` step, adding `toolchain.variables['CMAKE_VERBOSE_MAKEFILE'] = true`.

This feature would be useful when I'm trying to debug linker issues.

### How to reproduce it

Execute: `conan create conanfile.py -c tools.build:verbosity=verbose`
Expected outcome: I expect to see all compile/link commands in the output
Actual outcome: I see `--loglevel=VERBOSE` being added to the cmake command, but this doesn't seem to affect the value of CMAKE_VERBOSE_MAKEFILE at all

**Comment by memsharded** [comment]
Hi @Tails86 

Thanks for your report.

I don't think this is a bug. The ``tools.build:verbosity`` configuration is intended to set the ``--quiet/--verbose`` that is intended for the CMake tool itself.

What you might be looking for is the ``tools.compilation:verbosity`` configuration, which is the one setting the verbosity on the compilation itself. 

``conan config list`` will show a short summary of the available configurations, and you can see them in https://docs.conan.io/2/reference/tools/cmake/cmake.html#conf

**Comment by Tails86** [comment]
Yep, I was confused. Thanks for the clarification!
