### ISSUE TITLE
Command is missing

### ISSUE THREAD

**Issue by JoseNavio** [conan-io/conan#16048]
### What is your question?

Hi, I updated from 1.6 to 2.2 and the following command is missing.

```
conan frogarian
```
I used it a lot, is still supported?

Thanks.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @JoseNavio 

Thanks for your question.

Yes, the ``conan frogarian`` was not a real command, it was an "easter-egg" (at some point it was not even listed in ``conan -h``). It didn't have any real functionality and it was using extra space and it also required some maintenance. So Conan 2 decided to remove it, and at the moment there is no plan to add it again. Any special reason you were using this command for?

**Comment by JoseNavio** [comment]
I used it to get my partner's attention so he could help me with something, because I'm really a newbie using Conan.

Then I guess I'll have to learn myself.

Anyway, thanks and great work.

**Comment by memsharded** [comment]
Conan 2 added custom commands: https://docs.conan.io/2/reference/extensions/custom_commands.html

You can easily create your own commands, and install them easily into your Conan installation with ``conan config install``. Adding your own ``conan frogarian`` command is possible now, so you can still use it if you want.

I think we can close this question as resolved/not planned? Thanks!

**Comment by JoseNavio** [comment]
I'll check it, thanks so much.
