### ISSUE TITLE
[question] Migration from `self.options` to `self.dependencies.options` in Conan v1 and v2

### ISSUE THREAD

**Issue by Linux13524** [conan-io/conan#16057]
### What is your question?

Hi! We are currently migrating from Conan v1 to v2 and stumbled upon a problem that seems to be related to https://github.com/conan-io/conan/issues/15206.

In the `test_package` we are currently accessing some option from the main package, but also from some main packages we are are accessing options from dependencies. This works just fine with `self.options["dependency"].option`  in Conan v1 and with `self.dependencies["dependency"].options.option` in Conan v1 and v2 **in the `generate()` method**. 

However this does not work for Conan v1 in the `test()` method where we also need to access dependency options, but it does in Conan v2.. Before it was working fine with `self.options` in Conan v1.

[The documentation](https://docs.conan.io/en/1.59/reference/conanfile/dependencies.html#dependencies-interface) is very specific about this:
* "This information only exists in those methods that evaluate after the full dependency graph has been computed": Should be the case for `test()`, right?
* "It will not exist in configure(), config_options, export(), export_source(), set_name(), set_version(), requirements(), build_requirements(), system_requirements(), source(), init(), layout().": No `test()` listed here.
* "At the moment, this information should only be used in generate() and validate() methods. Any other use, please submit a Github issue": I just opened the issue :)

So the question is: What can and should be used to access options from dependencies in the `test()` method?

---

Maybe some more words about the use-cases for accessing options from dependencies in the `test()` methods:

* We need some files to be in place for the tests but we cannot load them in `generate()` because we need some system package installed in `system_requirements()` which runs after `generate()`. The files depend on some dependencies option.
* For some packages the information if the test can run also depends on some dependency option. If the option is set the test should only run if a specific hardware was detected.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Linux13524 

Thanks for your question.

> However this does not work for Conan v1 in the test() method where we also need to access dependency options, but it does in Conan v2.. Before it was working fine with self.options in Conan v1.

> "It will not exist in configure(), config_options, export(), export_source(), set_name(), set_version(), requirements(), build_requirements(), system_requirements(), source(), init(), layout().": No test() listed here.

It seems this would be a gap in the docs. Many times the methods enumeration covers the main package conanfile, but not the ``test_package/conanfile.py``. The limitation is that in Conan 1.X, the ``build()`` and ``test()`` steps are decoupled from the graph computation, and they basically recover state from text files, but this is a very limited and fragile approach, this is why it has been changed in Conan 2, and Conan 2 already allows accessing options.

> So the question is: What can and should be used to access options from dependencies in the test() method?

The recommendation for making it working in Conan 1.X is still valid for moving forward to Conan 2 and is aligned with the general design of the ``generate()`` step. The idea is:
- The ``generate()`` method process everything related dependencies and "prepares" the build by creating the necessary build files like ``conan_toolchain.cmake``
- The ``build()`` (and ``test()``) steps are pretty dummy regarding dependencies, they just execute what has been prepared before.
- The general idea is that developers can easily replicate exactly the same build than the ``build()`` and ``test()`` steps, but manually, by invoking ``cmake`` (like with ``cmake --preset conan-default``)

So if you need this working in Conan 1.X, I'd probably generate a file from ``self.dependencies[...].options`` values you want, and this file will be read by the ``test()`` method. If it makes sense to be a build file, like a ``myoptions.cmake``, it is possible, if not, you can always save a ``.json`` file and read it in the ``test()`` method.

Please let me know if this helps.

**Comment by Linux13524** [comment]
Hi @memsharded!

Thanks a lot for your quick answer!

This information already helps us moving forward in the right direction. However I still have some more questions:

* Is it maybe possible to read the information about the dependency options from some already generated file (like `conanbuildinfo.txt` or `conaninfo.txt`) or is it really necessary to write a file by ourselves in the `generate()` method, just to read that again in `test`?
* I saw some approach in Conan Center Index where the Conan version was checked to adapt the logic and came up with something similar for this problem and wanted to know if it is rather good or bad to do it like this:

  ```python
  if Version(conan_version) < "2.0.0":
      return self.options["dependency"].option
  else:
      return self.dependencies["dependency"].options.option
  ```

* Maybe a bit unrelated question: We are currently doing extensive testing in the `test_package` including unit test (where we need to load those files for) even though we know it is advised to do this in the main package. The reason for that was mainly that it is easier to skip the tests when they are in the `test_package` with `-tf None`. So actually there are two questions:
  * With Conan v2 is it easily possible to skip tests when they are executed in `build()` with `cmake.test()`?
  * Would it help in our case to move the tests into the main packages `build()` method to solve this problem here? So you say the behavior is a bit different in the main package than the `test_package`, can I run the `self.dependencies["dependency"].options.option` in the `build()` method with Conan v1 in the main package?

**Comment by memsharded** [comment]
> Is it maybe possible to read the information about the dependency options from some already generated file (like conanbuildinfo.txt or conaninfo.txt) or is it really necessary to write a file by ourselves in the generate() method, just to read that again in test?

If you want it to be Conan 2-ready and future proof, yes, you need your own file (generated typically inside build_folder, not in the root as those files), because Conan 2 completely drops those ``conanbuildinfo.txt`` and ``conaninfo.txt`` and other files.

If you want, you might also introduce something like ``if conan_version < 2`` in the recipe, and do different things depending on the Conan version if you prefer, try to read those files in Conan 1, and use the ``self.dependencies`` for Conan 2.

> I saw some approach in Conan Center Index where the Conan version was checked to adapt the logic and came up with something similar for this problem and wanted to know if it is rather good or bad to do it like this:

Ok, I was responding line by line 😅 
yes, this is perfectly valid, if it is good for you, go for  it.


> Maybe a bit unrelated question: We are currently doing extensive testing in the test_package including unit test (where we need to load those files for) even though we know it is advised to do this in the main package. The reason for that was mainly that it is easier to skip the tests when they are in the test_package with -tf None. So actually there are two questions:

Yes, the ``tools.build:skip_test`` is the recommended way to disable tests in Conan 2.
The main reason is that many unittest need internal headers that are not in the public package, so it is impossible to test them from the ``test_package`` without violating encapsulation. The Conan built-in integrations will already listen to ``tools.build:skip_test``.


> say the behavior is a bit different in the main package than the test_package, can I run the self.dependencies["dependency"].options.option in the build() method with Conan v1 in the main package?

Yes, I think this should work.

**Comment by Linux13524** [comment]
Many thanks! We will consider all options and see what fits best in our case and if we maybe finally move the tests into the main package. :wink:

**Comment by memsharded** [comment]
Sounds good, don't hesitate to open new tickets for any further question you might have, thanks for the feedback!
