### ISSUE TITLE
[question] Cannot specify link libraries for target

### ISSUE THREAD

**Issue by manuelpagliuca** [conan-io/conan#16051]
### What is your question?

Hello I'm finding the following error when I try to build the plugin using the command
`conan build ./code --profile macos --settings build_type=${{ env.BUILD_TYPE }} --options archicad=${{ matrix.adk }} -of "./build"`

- The first placeholder values is always `MinSizeRel`, while the second changes between `25`, `26` and `27`.

In short I get this error
```
CMake Error at cmake/Archicad.cmake:40 (target_link_libraries):
  Cannot specify link libraries for target "CONAN_PKG::archicad_adk" which is
  not built by this project.
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)
-- Configuring incomplete, errors occurred!
ERROR: conanfile.py: Error in build() method, line 111
	cmake.configure()
	ConanException: Error 1 while executing
```
Here is the full is [log.txt](https://github.com/conan-io/conan/files/14920789/log.txt)

I'm not really a CMake expert, but I think this error can be avoided using in the correct way Conan 2.2.2 (I'm moving from Conan 1.62.0). For what I understand right now, this error is given because I'm attempting to linking a library before I've built an executable, but the same CMakeLists.txt file were working with the previous version of Conan.

* [CMakeLists.txt](https://github.com/conan-io/conan/files/14920835/CMakeLists.txt)
* [Archicad.cmake](https://github.com/conan-io/conan/files/14920847/Archicad.txt) (saved as .txt)

I was thinking that maybe the problem could be in the [conanfile.py](https://github.com/conan-io/conan/files/14920864/conanfile.txt) (saved as .txt), so I've also attached this for being sure. Maybe there is something extra that I should know about the CMakeDeps class for avoiding this conflict.

Could you please help me understand why is this happening?

Thanks in advance for you availability, I don't know where I would be without your help :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
```cmake
if(EXISTS ${CMAKE_BINARY_DIR}/conan_toolchain.cmake)
  include(${CMAKE_BINARY_DIR}/conan_toolchain.cmake)
endif()
```
Toolchains cannot be included. Toolchains need to be passed in command line or in CMakePresets.


```cmake

target_link_libraries(Common PUBLIC
    CONAN_PKG::archicad_adk
```
You shouldn't be linking with the internal CONAN_PKG:: targets. Those are internal implementation details, and they are incomplete. Use the ``pkg::pkg`` like public targets.

Those are some hints. Still, impossible to know what it is if we cannot reproduce it.

**Comment by manuelpagliuca** [comment]
Hello @memsharded, I'm already passing the toolchain from the command line, so I've to remove the include. I'll try with this first, thanks. I didn't really well understood the second step, how I should use the `pkg::pkg`?

If this won't solve the problem I'll create a repository so that it is possible to reproduce some of the steps (but it will take time).

**Comment by manuelpagliuca** [comment]
I tried to change to `archicad_adk::archicad_adk`, but this doesn't work, maybe since I'm exporting pre-built package with `conan export-pkg` I need to specify it with `package_info()`?

```
CMake Error at cmake/Archicad.cmake:40 (target_link_libraries):
  Cannot specify link libraries for target "archicad_adk::archicad_adk" which
  is not built by this project.
Call Stack (most recent call first):
  CMakeLists.txt:18 (include)
```

**Comment by manuelpagliuca** [comment]
This time I passed the Conan toolchain directly to the cmake command and I got the following:
```
CMake Error in CMakeLists.txt:
  Imported target "archicad_adk::archicad_adk" includes non-existent path
    "/Users/runner/.conan2/p/archif3b6c5b228d4e/p/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
CMake Error in CMakeLists.txt:
  Imported target "archicad_adk::archicad_adk" includes non-existent path
    "/Users/runner/.conan2/p/archif3b6c5b228d4e/p/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
CMake Error at CMakeLists.txt:78 (target_link_libraries):
  Target "Common" links to:
-- Generating done (0.1s)
    gsl-lite::gsl-lite
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
CMake Error at CMakeLists.txt:125 (target_link_libraries):
  Target "UnitTests" links to:
    catch2::catch2
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
CMake Error at CMakeLists.txt:[175](https://github.com/JFrog-Group/BIM-ArchiCAD-Plugin/actions/runs/8629855788/job/23654888153#step:10:176) (target_link_libraries):
  Target "JfrogTestRunner" links to:
    catch2::catch2
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
CMake Warning:
  Manually-specified variables were not used by the project:
    PROJECT_ARCH
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by memsharded** [comment]
>  I didn't really well understood the second step, how I should use the pkg::pkg?

If you do a ``conan new hello/0.1 -m=cmake_lib`` it will show you in the ``test_package/CMakeLists.txt`` how to do it.

It is extremely recommended to do the Getting Started tutorial of Conan 2, even if you are in Conan 1. Check: https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html

It will put use things like ``target_link_libraries(${PROJECT_NAME} ZLIB::ZLIB)``. 
Also the output of Conan2 already prints in screen what ``find_package()`` and what ``target_link_libraries()`` you need to use for your dependencies.


For more details of what could be happening, yes, we would need something that we can reproduce, thanks.

**Comment by memsharded** [comment]
I am closing this ticket as inactive, but please re-open or create new tickets for any further question or issue. Thanks for the feedback!
