### ISSUE TITLE
[question] How to modify `conan install .` outputs.

### ISSUE THREAD

**Issue by LouChiSoft** [conan-io/conan#16050]
### What is your question?

Hi, I am fiddling around with the arguments for `conan install` trying to some desired behaviour and I am a but puzzled as to some of the behaviour of how conan creates output files.

If I run `conan install . --build=missing` for example, the path to the toolchain file ends up being `build/generators/conan_toolchain.cmake` since build is the default output when you don't specify.

If I then run `conan install . --build=missing -of build` I would expect to get the same result because we have replaced the default output folder with a value of the exact same. But instead the path to the toolchain file becomes `builld/build/generators/conan_toolchain.cmake`. 

What I want to do is be able to pass any value to the output folder like `build` or `build-release`, etc. and be able to have the `conan_toolchain.cmake` file be places directly in the root of the folder. I'd like it to be this way, so that we can reliably have CMake call conan and cache the location of the toolchain file before we call `project()`. Is fixing the output location to the root of the output folder possible?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @LouChiSoft 

Thanks for your question.

There are many factors that affect the location of the output folder:

- The ``cmake_layout()`` already defines a base "build" folder for the build, to avoid cluttering the user root directory with build temporaries, even if the user don't add ``--output-folder``
- The ``--output-folder`` will define a base output folder, but that is independent of the ``cmake_layout()`` one. If both are defined, then 2 folders will be used ``build/build`` if both are "build"

In Conan 2.2, the new conf https://docs.conan.io/2/reference/tools/cmake/cmake_layout.html#conf defines:

- ``tools.cmake.cmake_layout:build_folder`` (experimental) uses its value as the base folder of the conanfile.folders.build for local builds. 

This allows to define the ``cmake_layout`` default "build" folder. You might use this conf to relocate the folder wherever you want, without an extra nested "build" folder. 


Please, note however, that the recommended approach is to have at least a valid ``conan install .`` configuration that is completely valid and doesn't require any extra ``--output-folder`` or ``conf`` to work. Also Conan implements extra logic to take care of multi-config vs single-config build systems, as in multi-config the same ``conan_toolchain.cmake`` must be shared for all Debug/Release configs, same location, while in single-config, there will be 2 or more different ``conan_toolchain.cmake`` files in different locations. Having things fully defined in the recipe ``layout()`` is self-contained, so in general simpler and more robust.

**Comment by LouChiSoft** [comment]
Hi @memsharded,

Thanks for the reply. 

> The --output-folder will define a base output folder, but that is independent of the cmake_layout() one. If both are defined, then 2 folders will be used build/build if both are "build"

Ah, that'll be what's causing the double build folder on our end.

For some additional context this is an internal only package, and the intention is that CMake will be the default method for calling Conan to simplify our build process. In a perfect world the user would only have to call:
```
cmake -B <build_directory> -DCMAKE_BUILD_TYPE=<build_type>
cmake --build <build_directory>
```
and that would be the project 100% of the time. As for multi-config cmake builds, I can't say I even know CMake supported that. I have personally always done a separate build directory for each configuration, `build-release`, `build-debug`, etc.

Based on the `conf` information. it looks like that means that if I did `conan install . -c tools.cmake.cmake_layout:build_folder="${CMAKE_CURRENT_BINARY_DIR}"` inside our CMake file then it would place the toolchain file there every time. Albeit losing multi-config support, but IIRC no one in my team uses CMake that way, so not really a loss for us

**Comment by memsharded** [comment]
> and that would be the project 100% of the time. As for multi-config cmake builds, I can't say I even know CMake supported that. I

Visual Studio by default is multi-config. Also ``Ninja Multi-Config`` is becoming more popular too. If you are fine with forcing the single-config approach always, that sounds good enough, but still the: 

> cmake -B <build_directory> -DCMAKE_BUILD_TYPE=<build_type>

the definition of ``CMAKE_BUILD_TYPE`` for multi-config build systems, even if forcing them to be single-config is discouraged by CMake. CMakeLists.txt and others shouldn't rely on ``CMAKE_BUILD_TYPE`` value at CMake configure time.

Likewise it would be mandatory for Visual Studio multi-config generator to use: 

```
cmake --build <build_directory> --config <config>
```
for build-time. It doesn't matter if you are forcing the creation of 2 projects, one per configuration, they are still 2 multi-config projects, that you just defined one configuration in each only. But it can be problematic both depending on CMAKE_BUILD_TYPE and ommitting ``--config <config>``.

Unless you are not using at all any CMake "Visual Studio XX" generator, and always using Ninja or the like.


> conan install . -c tools.cmake.cmake_layout:build_folder="${CMAKE_CURRENT_BINARY_DIR}"

Using ``CMAKE_XXX`` variables doesn't have meaning in this context. This executes and evaluates much earlier than CMake starts running, so this has to be a value.

This is the reason why the default ``cmake_layout()`` or variations of it can work well, because it knows what will be the CMake binary dir.

Please let me know if this helps.

**Comment by LouChiSoft** [comment]
I see, this is more complex that I was hoping (although maybe enough to convince my boss that we shouldn't try embed conan in cmake)

> Using CMAKE_XXX variables doesn't have meaning in this context. This executes and evaluates much earlier than CMake starts running, so this has to be a value.

Surely that's only the case if you are calling conan from the command line before cmake. We currently have a semi-functional CMake function that calls conan before configuring the cmake project. So the cmake variables would be present, at least in my testing they are

**Comment by memsharded** [comment]
> I see, this is more complex that I was hoping (although maybe enough to convince my boss that we shouldn't try embed conan in cmake)

Embedding Conan in cmake, we have the cmake-conan provider https://github.com/conan-io/cmake-conan, which does this quite transparently via  a CMake dependency provider. However it is true that this is good mostly for simple developer flows. It will probably not be recommended to wrap all possible Conan functionality from CMake, as CMake is not that great as scripting or automation language. 

> Surely that's only the case if you are calling conan from the command line before cmake. We currently have a semi-functional CMake function that calls conan before configuring the cmake project. So the cmake variables would be present, at least in my testing they are

If that means you evaluate yourself the ``${CMAKE_CURRENT_BINARY_DIR}`` and pass to Conan the evaluated value which would be a folder, then good. But passing the literal ``"${CMAKE_CURRENT_BINARY_DIR}"`` to the conf, will be that literal, and won't be evaluated inside Conan.

**Comment by LouChiSoft** [comment]
> Embedding Conan in cmake, we have the cmake-conan provider https://github.com/conan-io/cmake-conan, which does this quite transparently via a CMake dependency provider.

I will look into this, this might be what we need.

> If that means you evaluate yourself the ${CMAKE_CURRENT_BINARY_DIR} and pass to Conan the evaluated value which would be a folder, then good.

Correct, we evaluate what the variable is and would pass the evaluated version in

**Comment by memsharded** [comment]
Any further question here? 

If not, maybe we can close this ticket as responded? Thanks!
