### ISSUE TITLE
[question] cross compile from macos armv8 to ubuntu x86_64

### ISSUE THREAD

**Issue by Jie-Cheng** [conan-io/conan#16055]
### What is your question?

Hi, 

So far conan has been working great for my project. I am able to build it from both x86_64 Ubuntu and armv8 MacOS. I am interested in cross compiling from MacOS to Ubuntu. What additional tools do I need to install (like gcc)? Is there a tutorial for this? I have read the cross compile tutorial in the documentation but still don't know where to start. 

Thank you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Jie-Cheng 

Thanks for your question.

Have you also checked the examples in https://docs.conan.io/2/examples/cross_build.html? they might be useful too.

It is true that Conan docs doesn't cover how to install the cross build tools, because this would be widely varying. 
Quick questions: have you considered using docker instead? We are preparing a great feature to automatically use docker containers for building for Linux in other OSs.

I don't know any specific resources for installing a Linuxx64 toolchain in OSX-arm, I'll ping the team in case someone has a good learning resource from this. In any case, if you manage to install it and you can cross compile something by hand, then let us know if you have any question how you can configure it with Conan profiles.

**Comment by Jie-Cheng** [comment]
Hello @memsharded 

Yes I have read the examples in the documentation. And I'd love to use docker if it makes cross compiling easier. Do you know when the new feature would be available? I can't wait to try it!

It'd be nice if someone could point me to some resources regarding cross compiling by hand too.

Thank you!

**Comment by memsharded** [comment]
I have been getting feedback from the team, and apparently it is more challenging than one would expect to install a LinuxX64 cross-compiler in OSX, it might require quite some juggling.

Using docker for building for Linux is relatively straightforward nowadays, mostly prepare one image (we have some ones in the conan-docker-tools repo) with the tools inside, launch it, and work inside as if you were in a Linux box. I suggest you give it a try already.

The feature that we are planning will improve over this flow, launching Conan inside a docker container more automatically. It is not guaranteed, but it might be in next 2.3 or 2.4 depending on how it goes, 1-2 months.

**Comment by Jie-Cheng** [comment]
Thanks for the advice! I will give docker a try. The images in [conan-docker-tools](https://github.com/conan-io/conan-docker-tools/tree/master/modern) are built for older Ubuntu versions, is there any trouble if I build in Ubuntu 18 and deploy on Ubuntu 20 and above?

**Comment by memsharded** [comment]
>  is there any trouble if I build in Ubuntu 18 and deploy on Ubuntu 20 and above?

Typically yes, forward compatibility works better, specially regarding glibc versions, while the opposite doesn't, like building in modern distros and trying to run on older ones might fail because of not enough glibc version.

**Comment by Jie-Cheng** [comment]
@memsharded , docker approach looks promising!
I was able to build my project using the `conanio/gcc13-ubuntu16.04` image with `--platform linux/x86_64` on my m3 macbook.
but when I ran it on a Ubuntu 20.04 PC with x86_64 chip I got
```
my_app: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./my_app)
my_app: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./my_app)
my_app: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./my_app)
```
my PC has gcc 9, not gcc 13. But it shouldn't matter what compiler I have, right? Do you know how to fix this?

**Comment by memsharded** [comment]
> But it shouldn't matter what compiler I have, right?

Yes, using a more modern compiler, specifically for C++ will also link the C++ standard libraries, which might not be enough in other systems if they don't have a compatible or modern enough one, depending on what is installed in that system.

Depending on the runtime and deployment strategies and requirements, there could be different approaches. Some try to statically link the C++ runtime, so the deployment of the app is independent on it. It will still depend on the C runtime / libc version, but that is less dependent on the compiler version and more on the distro and system libc. 

Of course, if the deployment PC has gcc9, then using a docker image with gcc9 most likely solve the issues easily.

**Comment by Jie-Cheng** [comment]
@memsharded thanks for the help! I built my project and deployed with `conanio/gcc9` image.

**Comment by memsharded** [comment]
Sounds good, thanks for the feedback! The images will eventually install only Conan 2 or get deprecated.

Stay tuned to our blog in https://blog.conan.io/ and our release notes for new versions, we will be announcing there when the new integration with docker is available.
