### ISSUE TITLE
[question] How do i transfer a variable in conan to cmake

### ISSUE THREAD

**Issue by GRyzer** [conan-io/conan#16059]
### What is your question?

# Description
Hi
My goal is to have a c++ function that returns the current git commit hash:

```cpp
const std::string getGitRevision()
{
    return std::string( "70dac1d815706b531c2f8965bf616cd1b21fcb7c-dirty" );
}
```

Since this changes continuously, I need a template file, which generates a cpp with this function. For this I use CMake which takes over this task.

```cpp
const std::string getGitRevision()
{
    return std::string( "@scm_revision@" );
}
```

I would like to use Conan to pass the git commit hash to CMake. This is what my two methods look like in conanfile.py:

```python
def find_git_commit(self):
    git = Git(self, self.recipe_folder)
    try:
        scm_revision = git.get_commit()
        if git.is_dirty():
            scm_revision += "-dirty"
    except ConanException:
        scm_revision = os.getenv("GIT_COMMIT")
        if scm_revision is None:
            scm_revision = "unknown"
    return scm_revision

def build(self):
    scm_revision = self.find_git_commit()
    cmake = CMake(self)
    cmake_variables = { "scm_revision": scm_revision }
    cmake.configure(variables=cmake_variables)
    cmake.build()
```

[Here](https://github.com/GRyzer/conan-scm-revision) is an associated repository with a conan package that reflects the complete source code.

## Questions

I have three questions:

1. Is this a valid approach and can be considered `Best Practice`?
2. During a `conan create`, my source code is copied and is no longer a git repo. Is it still possible to access the git commit hash via the conan infrastructure?
3. How can i share the method `self.find_git_commit()` across conan packages? (I have a lot of repositories/packages which need this functionality) I don't like to duplicate code :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @GRyzer 

Thanks for your question and your repo with code, that helps!

I am afraid this is not a valid method in the general case. When the ``build()`` method executes in the cache, it is not a git repo anymore, as you pointed out.

I think you want to check https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html
The idea is:
- When the recipe is exported it captures in ``conandata.yml`` the url and commit of the repo
- This url and commit of the repo will be available in ``self.conan_data`` accross the recipe methods later, even if no longer in a git repo, so something in the line of ``cmake_variables = { "scm_revision": self.conan_data["scm"]["commit"]}``
- You might not need the ``source()`` part of that doc page, as you are already doing the ``exports_source``.

Please let me know if this helps.

**Comment by GRyzer** [comment]
Thanks a lot @memsharded !

In fact, this simplifies our workflow if we use the `conan create` command. Unfortunately, we have another scenario where we need to have our build output in a specific place. Accordingly, we have to rely on `conan install` and `conan build`. The consequence of this approach is that my `conandata.yml` file does not exist and consequently `self.conan_data is None`.

Is there a solution for this as well?

**Comment by memsharded** [comment]
I guess that you can do something like this:
```python
def find_git_commit(self):
    if self.conan_data is not None:
         return self.conan_data["scm"]["commit"]
    git = Git(self, self.recipe_folder)  # it will be local
    scm_revision = git.get_commit()
    if git.is_dirty():
       scm_revision += "-dirty"
    return scm_revision

def build(self):
    scm_revision = self.find_git_commit()
    cmake = CMake(self)
```

Does this help?

**Comment by GRyzer** [comment]
I tried to avoid it. The reason is that i introduce code duplication.
If every single repository needs to implement this logic, then it is a code smell. 
Does conan provide anything in this direction to avoid this?
If not, then i have to live with it. I mean you helped us out a lot and improved our approach. So we are already thankful.
It is just that we try to implement the optimal way and go away from "it works, therefore it is good enough"

**Comment by memsharded** [comment]
> If every single repository needs to implement this logic, then it is a code smell.
Does conan provide anything in this direction to avoid this?

yes, you have ``python_requires``: https://docs.conan.io/2/reference/extensions/python_requires.html#reference-extensions-python-requires

Is this what you are looking for?

**Comment by GRyzer** [comment]
I guess so. I will have a look. We appreciate your help.
I will mark this question as closed :)

**Comment by memsharded** [comment]
Great, don't hesitate to open new tickets for any further question you have, thanks for your feedback!
