### ISSUE TITLE
[question] own package not finding headers

### ISSUE THREAD

**Issue by ebassi00** [conan-io/conan#16060]
### What is your question?

I have my own Conan package which consists of N static libraries and N components (one for each library). My problem regards the headers included in some of those libraries: when they are compiled, everything is fine but, when I try to use my package in some other projects, it gives me include errors (it doesn't find headers). I found a "solution" which looks very ugly to me and I'm sure there's a better one: let's suppose one of my libraries is organized as follows:

```
root/
    CMakeLists.txt
    lib1/
        CMakeLists.txt
        file1.hpp
        file1.cpp
        file2.hpp
        file2.cpp
        folder1/
            file3.hpp
            file4-hpp
            file4-cpp
```

the lib1's CMakeLists just adds every .hpp/.cpp file to the add_library method, creates a STATIC library and then uses the `target_include_directories(lib1 PUBLIC ${CMAKE_SOURCE_DIR})` to link all the directories to the target.

The problem comes after creating the package: the package is correctly created (conan create .), I include it in my project but, when I try to use `file4.hpp` it says:

fatal error: file1.hpp: No such file or directory
The first (and only) solution I found is to manually include all the directories in the package's conanfile.py, in the package_info() method as follows:

`self.cpp_info.components["lib1"].includedirs = ["include", "include/lib1", "include/lib1/folder1"]
`
This may look as a fine solution, but imagine you have more and more libraries in your package and you have to include all the folders manually: it is chaotic and very bad looking. I think the "problem" is in the CMakeLists of lib1 but I'm not 100% sure, could you help me? Thank you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ebassi00 

Thanks for your question.

> The problem comes after creating the package: the package is correctly created (conan create .), I include it in my project but, when I try to use file4.hpp it says:

> fatal error: file1.hpp: No such file or directory

> The first (and only) solution I found is to manually include all the directories in the package's conanfile.py, in the package_info() method as follows:

The important bit is not how the files look like in the "source" tree, but how they look like after the "install" step in the final package folder. What would be the layout of headers in that folder? You can ``tree`` the package-folder, you can see the package folder in the output while ``conan create`` or do a ``conan cache path mypkg/myversion:mypackageid`` to get the path. Please check it and let us know.

Then, it is important to define what would be the "include" schema you want the users of your package to use.
In most cases ``#include "file4.h"`` will be discouraged, as it can have name collisions with other packages.

The recommended approach would be to require at least ``#include "pkgname/file4.h"`` by the consumers. Depending on your design and components, you might also want to be explicit  and require ``#include "pkgname/component/file4.h"``. 

Once a ``#include`` schema is defined, it is very likely that ``self.cpp_info.components["mycomp"].includedirs = ["include"]`` is all you want. Libraries and packages should not be prepared to allow users to ``#include`` with whatever path they like, but very the opposite, to require a very specific and unique way of including your headers.

Please let me know if this helps.

**Comment by ebassi00** [comment]
Hi @memsharded 
and thanks for the answer.
It was my mistake not to specify, but when the user includes the component of the package (previously installed via conanfile and then included in the project in CMakeLists --> `target_link_libraries(project PUBLIC pkg::lib1)`), the path will be `#include <lib1/folder1/file4.h>` and then gives the error.
For what concerns the conan package folder after it is created, it is organized as follows:

```
include/
    lib1/
        *.h
    lib2/
        *.h
    lib*/
        *.h
lib/
    *.a
```

I tried working only with `self.cpp_info.components["mycomp"].includedirs = ["include"]` but it looks like it only searches in the "root" folder of include and does not go deeply inside

**Comment by memsharded** [comment]
If the layout of the package folder is ``include -> libX -> *.h`` then the expected and recommended would be:
- ``self.cpp_info.components["mycomp"].includedirs = ["include"]`` (assuming ``mycomp`` = lib1 for example)
- ``#include "lib1/myheader.h"``
This should work.

But the path that you are posting with ``<lib1/folder1/file4.h>`` shouldn't, as the ``folder1`` is not there.

Please note that you might have different include paths at development time for your internal ``.cpp`` files than the include paths that you might want for the consumers of the package, something in the line of:
```cmake
target_sources(
  mylib
  PUBLIC
    $<INSTALL_INTERFACE:myfirstpublicheader.h>
    $<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/myfirstpublicheader.h>
    $<INSTALL_INTERFACE:mysecondpublicheader.h>
    $<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/mysecondpublicheader.h>
)```

If on the other hand, you want your final consumers to really ``#include <lib1/folder1/file4.h>``, then you need to guarantee that in the final package folder the layout of folders is exactly that, and you want to either fix your ``CMakeLists.txt`` so it installs with that layout, or maybe use the ``package()`` method with your own custom ``copy()``?

**Comment by ebassi00** [comment]
my bad again...actually I want to use the header in folder1 inside lib1:
```
include/
    lib1/
        *.h
        folder1/
            file4.h
    lib2/
        *.h
    lib*/
        *.h
lib/
    *.a
```
and it correctly finds the file4.h header but somehow it doesn't find headers (included by file4.h) contained in the previous folder

**Comment by memsharded** [comment]
> and it correctly finds the file4.h header but somehow it doesn't find headers (included by file4.h) contained in the previous folder

What is the ``#include`` that ``file4.h`` has? It is relative? it is absolute? It should be ``#include "lib1/otherheader.h"``

**Comment by ebassi00** [comment]
it just includes file1.hpp contained in the lib1 folder `"#include file1.hpp"`. I thought about adding the folder name to the path as you suggested (`"#include "lib1/file1.hpp""`) but shouldn't that be handled by CMake?

**Comment by memsharded** [comment]
> it just includes file1.hpp contained in the lib1 folder "#include file1.hpp". I thought about adding the folder name to the path as you suggested ("#include "lib1/file1.hpp"") but shouldn't that be handled by CMake?

No, not really. That is part of the design of the source structure, and in general having "absolute" includes like ``#include "file1.hpp"`` is not recommended, as it requires juggling with the build system unnecessarily. It is typically more recommended to have a clear structure of includes. They might be relative too, but I don't think that is also generally recommended.

The reason would be the same as other languages like java or python, which most use the concept of namespaces or scopes for "imports" of other files. In general, the recommendation is either making them relative (depending on the language) or making them absolute (from the start of the project/package, not from the system root folder of course), but not relying on the definition of multiple origins for the imports (like multiple PYTHONPATHs within the same project)

All of this is of course topic of possible discussion, and there might be people with different preferences. But I think that in general having path conventions relative to a single 1 root "include" directory is common and generally preferred.

**Comment by ebassi00** [comment]
This solution works absolutely fine, but what about possible future changes to source code? It will most likely change in time and folders / files could be in other locations leading me to change the absolute path everywhere. That could take long time in very large libraries

**Comment by memsharded** [comment]
> This solution works absolutely fine, but what about possible future changes to source code? It will most likely change in time and folders / files could be in other locations leading me to change the absolute path everywhere. That could take long time in very large libraries

Not really. ``#includes`` are part of code, and the expectation when code changes is that this should change too. 
Most modern refactoring tools and IDEs might be able to automatically refactor too the includes when files are changed location, and if not, it is normally not a big deal, some regex search & replace can easily do it in a couple of minutes, even for very large codebases.

**Comment by ebassi00** [comment]
Ok, you convinced me! Thank you for your time and your valuable advices.

**Comment by memsharded** [comment]
Good, happy to help :) 

Closing the ticket as resolved, don't hesitate to create new ones for any further question.
