### ISSUE TITLE
CMake Generator : Check that directories exist when populating .cmake file

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1607]
This was discussed in slack, and the error is shown below. 

Summary:
The conan recipe for `Boost.Program_Options` shown in the error does not have an include directory, and did not specify any in a `package_info` step.  As a result, when this package is listed as a requirement in a package which uses the `cmake` generator, and the `conan install` command is run, the generated `conanbuildinfo.cmake` file has a problem.  The problem appears when CMake runs and tries to use the generated file, at which time CMake it throws the error shown below.  

At the root of the problem is that the CMake generator assumes that every package has an include directory, and adds lines in the generated `.cmake` file that points to them.  If that directory doesn't exist, CMake gives an error. 

Suggested Fix:
@lasote suggested adding a step to check that each directory exists before adding it to the generated `.cmake` file.  This makes sense to me. 

Notes:
- The error appears to be nonfatal. 
- The same logic probably applies to other package directories like `lib` and `res` (untested)

```
1> CMake Error in C:\Users\jerry\git-c\hello-world\CMakeLists.txt:
1>   Imported target "CONAN_PKG::Boost.Program_Options" includes non-existent
1>   path
1> 
1>     "C:/Users/jerry/.conan/data/Boost.Mpl/1.64.0/bincrafters/testing/package/eb9c161ab70566ac811cce24cb59fbb8226e821c/include"
1> 
1>   in its INTERFACE_INCLUDE_DIRECTORIES.  
```

**Comment by memsharded** [comment]
I would consider another approach, that might be valid for other build systems too: clear non-existing directories in the bare ``deps_cpp_info`` data structure, so all generators will have the same behavior.

**Comment by solvingj** [comment]
Also as a note regarding libraries with self.info.header_only(), the need to check for existence of the `include` directory still applies in these cases. I don't want them to get missed in case they're handled specially.

**Comment by memsharded** [comment]
Sure, such functionality is not related to the ``info`` object, which is used exclusively for the ``package_id``. Thanks for the note!

**Comment by solvingj** [comment]
I took a look to try and find the root cause, the point at which an `include` directory is added to a cpp_info object to add a check there.  As a complete novice with python, could not find it.

**Comment by solvingj** [comment]
Thank you @SSE4 for the PR on the issue, can't wait to test it!
