### ISSUE TITLE
[feature] CMakeToolchain cacheVariables should have a type

### ISSUE THREAD

**Issue by jmarrec** [conan-io/conan#16078]
### What is your suggestion?

Type mismatch in CMake configure arguments is a common issue that is really hard to track down, and as such I'm really pedantic about specifying the type of the variables when configuring CMake, especially for path/filepath ones.

```diff
--DMY_FLAG=ON
+-DMY_FLAG:BOOL=ON

-DMY_PATH=/path/to/file
+DMY_PATH:FILEPATH=/path/to/file

-DMY_DIR_PATH=/path/to/dir
+DMY_DIR_PATH:PATH=/path/to/dir
```

I noticed that the CMake presets do not hold a type for `cacheVariables`, while the CMake documentation explicitly says it can be a value, or a an object with both `type` and `value`, cf https://cmake.org/cmake/help/v3.29/manual/cmake-presets.7.html#configure-preset

Perhaps should consider explictly setting it, around https://github.com/conan-io/conan/blob/f1ef6e461accc293b14a7bf883865858ac29c7ad/conan/tools/cmake/toolchain/toolchain.py#L240-L271

Related:

* #14590
* #14568

---- 

Quoting Professional CMake - Practical Guide, 15th edition by Craig Scott (I hope that's ok, since I can already find the same online at https://discourse.cmake.org/t/cmake-d-var-type-value/1135)

> There is a special case for handling values initially declared without a type on the cmake command
line. If the project’s CMakeLists.txt file then tries to set the same cache variable and specifies a type
of FILEPATH or PATH , then if the value of that cache variable is a relative path, CMake will treat it as
being relative to the directory from which cmake was invoked and automatically convert it to an
absolute path. This is not particularly robust, since cmake could be invoked from any directory, not
just the build directory. Therefore, developers are advised to always include a type if specifying a
variable on the cmake command line for a variable that represents some kind of path. 

> It is a good habit to always specify the type of the variable on the command line in general anyway so that it is
likely to be shown in GUI applications in the most appropriate form. It will also prevent one of the
surprising behavior scenarios mentioned in the previous section

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Closing after https://github.com/conan-io/conan/pull/16079 is closed
