### ISSUE TITLE
[feature] Use `pluggy` to take plugin-managemant to the next level

### ISSUE THREAD

**Issue by hackenbergstefan** [conan-io/conan#16106]
### What is your suggestion?

Hi!

[pluggy](https://github.com/pytest-dev/pluggy) is used in several (big) projects (e.g. pytest) to provide an easy and powerful way to enhance a python package by plugins. Currently Conan implements plugins/extensions looking at appropriate locations in `CONAN_HOME`. This has some drawbacks:
* It is not possible to "install" a plugin/extension as pure python package (e.g. via pip)
* There is no mechanism tracking the origin and version of the plugin/extensions (in contrast to a proper python package)

Thus, I would propose to enhance the plugin/extension system of Conan with pluggy. 💪
My suggestion is:
1. Keep the existing way of implementing plugins/extensions
2. Let's leverage pluggy in addition and define meaningful hooks.
3. Implement and test.

If this feature request is liked - for sure - I would take care of the implementation and testing!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hackenbergstefan 

Thanks for your suggestion.

At the moment we are not interested in adding a new way for managing the plugins. Things in that regard are working quite well, and we don't want to add more complexity

> It is not possible to "install" a plugin/extension as pure python package (e.g. via pip)

Conan needs to work as a standalone executable too (python interpreter bundled), so pip packages don't work in those cases, and we prefer to not add things that wouldn't work for the standalone executable.

> There is no mechanism tracking the origin and version of the plugin/extensions (in contrast to a proper python package)

This is not accurate, the ``conan config install-pkg`` uses Conan packages with versions, revisions, lockfiles, updates, version-ranges, etc... in a package that is integrated in the Conan ecosystem, which is much preferred by our users.

Thanks very much for your suggestion anyway! closing it as not planned.

**Comment by hackenbergstefan** [comment]
Thanks for the quick reply! 🙂
I definitely understand that not increasing complexity is a value!
