### ISSUE TITLE
[question] does conan command line tool automatically discover conanfile(s) in subfolders ?

### ISSUE THREAD

**Issue by eyyubvolkan** [conan-io/conan#16107]
### What is your question?

Hi there,

imagine I have such a folder structure;
```
/
└── solution
    ├── project1
    │   ├── <project files>
    │   └── conanfile.py
    ├── project2
    │   ├── <project files>
    │   └── conanfile.py
    ├── <etc...>
    └── <solution files>
```

each conanfile listed here is supposed to introduce some requirements/dependencies. Is there a way to install all dependencies from root folder (solution folder) in one go ? Does conan discovers recipe files in subfolders ? thx in advance

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @eyyubvolkan 

Thanks for your question.

No, there is not such a functionality.
But one of the great things of Conan 2 is the custom command frameworks. You can very easily write your own custom Conan command, and implementing the logic of ``os.walk`` a folder, looking for ``conanfile`` there and calling ``conan install`` for each one of them would be relatively straightforward. 

Please check https://docs.conan.io/2/reference/extensions/custom_commands.html

(also note that custom commands can be shared and installed easily with ``conan config install / install-pkg``)

**Comment by eyyubvolkan** [comment]
nice, thank you
