### ISSUE TITLE
[question] How to dynamically set channel attribute ?

### ISSUE THREAD

**Issue by eyyubvolkan** [conan-io/conan#16101]
### What is your question?

Hi,

I'm looking for an option to set **channel** attribute value **dynamically** instead of defining it in the class header (so to say). As far as I know, there are options for name and version (**set_name** / **set_version**) but I couldn't find a similar functionality for the channel attribute. Is there an alternative way or a workaround to do that ? thx in advance

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @eyyubvolkan 

Thanks for your question.

It is is possible to define the channel on the command line with ``--channel``.

However, the recommendation would be not doing it:
- The channel is mostly a legacy thing from ancient Conan 1 versions
- It is not recommended to use the channel for variability, or for information
- Conan 2 has dropped the necessity to use the channel, it is possible to do ``pkg/version@user``
- Any variability is recommended to be encoded in:
  - version information
  - pre-releases
  - Using different server repos with names like "testing", "develop", "production", and promote (copy) packages from one repo to the other, keeping the packages names immutable.
 
So the general recommendation would be to drop it, or set it to something static and immutable that will stay there for long time, and if it needs to be changed it will be changed in recipe code.

Please let me know if this clarifies the intention of channel. Thanks!
