### ISSUE TITLE
[question] Strange handling of options in Conan 1.x create lock

### ISSUE THREAD

**Issue by db4** [conan-io/conan#16128]
### What is your question?

I had the impression that profile/command line option values always have precedence over ones set in `config_options()` method. For 1.x `create lock` this seems not to be the case. Consider the following test recipe:
```python
from conan import ConanFile


class PkgConan(ConanFile):
    options = {
        "with_something": [True, False]
    }
    default_options = {
        "with_something": False
    }

    def config_options(self):
        self.options.with_something = True

    def requirements(self):
        if self.options.with_something:
            self.requires("non_existing/1.0")
```
`create` works:
```
conan create . pkg/1.0@ -o pkg/*:with_something=False
...
pkg/1.0: Forced build from source
Installing package: pkg/1.0
Requirements
    pkg/1.0 from local cache - Cache
Packages
    pkg/1.0:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Build
...
pkg/1.0: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' created
pkg/1.0: Created package revision 9f4c99de8dd69f423db54ea1bece5e6f
```
but `create lock` doesn't
```
conan lock create conanfile.py --name=pkg --version=1.0 -o pkg/*:with_something=False
non_existing/1.0: Not found in local cache, looking in remotes...
ERROR: Failed requirement 'non_existing/1.0' from 'conanfile.py (pkg/1.0)'
ERROR: No remote defined
```
Why? Is it expected? In Conan 2.x `create lock` works for that recipe.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Yes, this is expected, there were some some situations in Conan 1 that Conan didn't follow its own design principles, more because of legacy and not being able to break than other reasons. So ``configure()`` defined options via ``self.options["dep"]`` or similar could have even higher priority than profile defined ones.

This was finally fixed in Conan 2, one of the multitude of reasons a major breaking release like Conan 2 was needed.

**Comment by db4** [comment]
@memsharded Thanks for your clarification. Despite all the known limitations, I thought that different graphs that Conan 1.x create/lock create generated with the same input were just a bug. But as this is unlikely to be fixed, I'm closing the issue.
