### ISSUE TITLE
How to reference packages such as iostream , limits etc

### ISSUE THREAD

**Issue by sgavathe** [conan-io/conan#16129]
### What is your question?

Hello I am not a C++ programmer but I am establishing a packeto buildpack for c++ and using the conan package manager.  Here is a simple dockerfile , I have

```
FROM ubuntu:22.04 as base

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  cmake \
  make \  
  libsqlite3-dev \
  gdal-bin \
  libgdal-dev \
  gdb \
  ca-certificates \
  wget \
  curl \
  git \
  jq \
  libc6-dev \
  libssl-dev \
  libffi-dev \
  libncurses5-dev \
  zlib1g \
  zlib1g-dev \
  libreadline-dev \
  libbz2-dev \
  libsqlite3-dev \
  openssl \
  xz-utils \
  gcc \  
  && rm -rf /var/lib/apt/lists/*
```

And then I have a simple src/main.cpp file that has 
```
#include <iostream>

using namespace std;

int main() {
  cout << "Hello, world!" << endl;
  return 0;
}
```

**conanfile.txt**
```
[generators]
CMakeDeps
CMakeToolchain
```
**CMakeLists.txt**

```
cmake_minimum_required(VERSION 3.15)
project(model C)

find_package(ZLIB REQUIRED)

add_executable(${PROJECT_NAME} src/main.c)
```

when I go to run the cmake build, i get the iostream not found error
```
[builder] [ 50%] Building C object CMakeFiles/model.dir/src/main.c.o
[builder] /workspace/src/main.c:4:10: fatal error: iostream: No such file or directory
[builder]     4 | #include <iostream>
[builder]       |          ^~~~~~~~~~
[builder] compilation terminated.
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sgavathe 

Thanks for your question.

This wouldn't be related to Conan, this is C++. ``<iostream>`` is part of the C++ standard library that would be most times just installed with your C++ compiler. Your source file is a ``.c`` file which means C language, not C++, this is most likely the reason why the C++ std library is not being used, most build systems by default will use the ``.cpp`` extension.

**Comment by sgavathe** [comment]
Oh got you @memsharded . Thank you for the clarification. Yeah this makes sense. 

So the procedure for  referencing/compiling cpp files is similar to how c files under conan?

**Comment by memsharded** [comment]
> So the procedure for referencing/compiling cpp files is similar to how c files under conan?

No, compiling/building C++ is a complex matter. Conan is not a build system, you should probably be learning about build systems such as CMake and the process of building C++ first (static libs, shared libs, symbols, build-types as Debug/Release).

Conan is the package manager, but it is not a build system, it will be calling/wrapper any underlying build system, so it is necessary to understand it to use Conan.

**Comment by sgavathe** [comment]
yep you are right @memsharded ,  I am checking the CMake for it, which is documented under conan reference guide. Thanks.

**Comment by memsharded** [comment]
Good. I am closing this questions as responded, don't hesitate to open a new one if you have any further question about Conan, thanks!
