### ISSUE TITLE
[bug] dependency collision text report does not match graph

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#16130]
Windows, conan 2.2.3

My project has a lot of dependencies, but no direct dependency on libjpeg-turbo.

conan-install reports a version collision, in this way:
`ERROR: Version conflict: libtiff/4.6.0->libjpeg-turbo/3.0.2, my_project/None->libjpeg-turbo/3.0.1.`

It should complain about libtiff vs qt ...

This is the graph:
![image](https://github.com/conan-io/conan/assets/1646667/eb5d9821-5e3a-4558-ae31-a96b3b1f3491)

Note, no direct line between my_project and libjpeg-turbo.

**Comment by memsharded** [comment]
Fixed in #16137 for next Conan 2.3
