### ISSUE TITLE
[question] Best approach to "automate" conan commands

### ISSUE THREAD

**Issue by diogomatos3** [conan-io/conan#16138]
### What is your question?

Hello community,

I am trying to automate conan command execution. Mainly conan install, build and package.
For that, I am doing in python with click and subprocess library.

While doing conan install, I am observing that the download progress of the packages is not visible. Not confident, but it seems that subprocess is not able to catch this output. 
Is there a way to do, so that user can get feedback of the ongoing download, during the install?

Related to conan build through subprocess, there is a source file (from my project) where the build get stuck. But the same conan build command triggered in the terminal directly works fine. Could it be that there subprocess is "restricting the resources", causing a stuck during the build?

At then end... I would like to learn... what would you recommend to use or what is the best approach to automate or run conan commands through a python cli?

I am using conan 1.56.0 and Ubuntu 20.04.6 LTS.

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @diogomatos3 

Thanks for your question.

Indeed running things with ``subprocess`` can be a bit more tricky that it seems, specially if the output is very large, as it can happen with C++ builds. We experienced these issues in the past in Conan itself.

I think what you are looking for is the ``custom comands`` in 2.0. Please have a look to: https://docs.conan.io/2/reference/extensions/custom_commands.html. It is a full framework to create your automation around Conan, with access to a proper documented and public (ongoing work) Python API, and that it allows to be easily shared and installed by your users and CI with a simple ``conan config install``.

**Comment by diogomatos3** [comment]
Hi @memsharded 

Thanks a lot for the reply!
That would mean, that I shall upgrade the conan version from 1.56.0 to 2.x.x?

Is there a unit-test, for example that you can refer, showing how for example a conan build command could be automated?

**Comment by memsharded** [comment]
> That would mean, that I shall upgrade the conan version from 1.56.0 to 2.x.x?

Conan 2 is now more than one year old, and it is nowadays the maintained and recommended version for production.
Packages in ConanCenter will stop getting updates for Conan 1 (they will not be removed or broken, but they will not process any further fixes or new versions, they will be frozen). So upgrading to Conan 2 is recommended in any case, and then, the new features will probably help in your use case.

> Is there a unit-test, for example that you can refer, showing how for example a conan build command could be automated?

Not a unit test, but the current implementation of the build command will be the reference for it.

You can just start from https://github.com/conan-io/conan/blob/develop2/conan/cli/commands/build.py, make a copy of it, rename it to ``mybuild`` and put it in your cache in the relevant position, and start testing it.

**Comment by diogomatos3** [comment]
Wonderful!
My doubts are clarified. @memsharded  thanks a lot for the help :)

**Comment by memsharded** [comment]
Great, happy to help, thanks for the feedback @diogomatos3 

Closing the ticket, don't hesitate to open new ones for any question.
