### ISSUE TITLE
[bug] Requiers field does not allow revisions

### ISSUE THREAD

**Issue by RobinMaub** [conan-io/conan#16141]
### Describe the bug

OS: Linux (Ubuntu 22.04)
Conan: 1.63.0
Package registry: Gitea 1.21.11
Compilers: Gcc
Conan package tools: 0.39.1

### How to reproduce it

Hello everyone,

I am working with conan with revisions enabled, I am creating packages and pushing them on my package registry.
I was used to use rolling versions as dependencies such as the conan files specifies the dependencies with the following: self.requires("myLib/[~0]@conan/stable") in order to use the latest "myLib" package on which the revision range is working. 
But this strategy does not work anymore, when searching for a package, it now has a [requires] field fixed to: "myLib/0.0.X" and it does not want to use it if the package myLib/0.0.(X+1) exists.

Is there any way to get back the rollong revisions working ?

**Comment by memsharded** [comment]
Hi @RobinMaub 

>  in order to use the latest "myLib" package on which the revision range is working.
But this strategy does not work anymore, when searching for a package, it now has a [requires] field fixed to: "myLib/0.0.X" and it does not want to use it if the package myLib/0.0.(X+1) exists.

I am sorry, I am not sure what you mean. Conan 1.X (which is the version it seems you are reporting about) hasn't changed anything regarding the revisions behavior in the last years.
It would be necessary to provide a bit more details:
- A minimal reproducible case, with source code (can be an almost empty ``conanfile.py``), the exact commands to reproduce the issue.
- The output logs of running those commands.
- If it is a behavior change in newer Conan versions, it would be necessary to know which Conan version was working (with the output logs) and the Conan version that is failing (with the output logs).

In any case, please be aware that Conan 1.X is now legacy and mostly in "maintenance" mode, and Conan 2 is the mainstream and recommended version for production.

**Comment by memsharded** [comment]
> Package registry: Gitea 1.21.11

Also, please consider that this might be a change in Gitea server, that we don't own or Control.
You can download from our download page the Free ArtifactoryCE and run it locally to run tests and reproduce the issue. If it is a server issue, you will need to report it to Gitea, not to this Conan repo.

**Comment by RobinMaub** [comment]
Manz thanks for your answer. I have contacted also the Gitea support, it is most likely in their side. Do you have any tip for where to look on the server side ? It is self hosted so I can check it,

**Comment by memsharded** [comment]
> Do you have any tip for where to look on the server side ? It is self hosted so I can check it,

I am afraid I don't, no idea about the Gitea implementation. I'd recommend the approach above: downloading ArtifactoryCE and running it locally it is very easy, so it will allow you to check the behavior, compare it, and report to Gitea about that.

If there is no immediate action required from us, I think we can close this ticket as it seems on Gitea side, and you can always re-open or create a new one if there are any further question or issue. Thanks!

**Comment by RobinMaub** [comment]
I agreee ! Thanks
