### ISSUE TITLE
Prune deps graph expansion for repeated nodes

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1614]
Very dense and big graphs might be very slow, because the same node is checked again and again.

Check if the recursion can be avoided.

**Comment by solvingj** [comment]
An example of a graph which reaches into thousands of duplicate checks can be experienced with this package on this repo: 

`conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"`
`Boost.Fiber/1.64.0@bincrafters/testing`
`https://github.com/bincrafters/conan-boost-fiber`

**Comment by memsharded** [comment]
@claasd This feature greatly improves the re-loading of big graphs with an improved algorithm. Available now as RC: ``pip install conan==0.26.0rc1`` It would be great if you could test it before the release, I think you have large graphs and could have substantial improvements.

**Comment by claasd** [comment]
Hi,
i made a test with component that has the largest graph. The graph contains ~30 dependencies up to a depth of 6. All requirements are defined using the `MyPkg/[~1.7]@user/channel` version range syntax.
First test: clean conan, no package on the local system at all. Call `conan info` on the conanfile
Second test: all package receipts are on the local system
Third test: all package son local system, running info -u
It seems that the -u flag has no effect on the info command. Therefore, i additionally called install and install -u. I made sure all packages and recipes were installed on the system.


Test | 0.25.1 | 0.26.0rc1 | Improvement
-----|--------|---------- | -------
info, nothing installed | 3:54 | 3:43 | ~5%
info, all recipes on local system | 0:02,16 | 0:03,57 | ~40%
info -u, all recipes on local system | 0:02,23 | 0:03:61 | ~40%
install, all recipes/packages on local system | 00:14,57 | 00:13,74 | ~5%
install -u, all recipes/packages on local system, | 6:46 | 5:30 |~ 20 %

Hope this helps.

**Comment by lasote** [comment]
So, the info command is running slower in the new 0.26.0rc1?

**Comment by claasd** [comment]
No, copy paste error. I will change my comment.

**Comment by memsharded** [comment]
Thanks @claasd for your report, very happy that there are improvements. 
Have you checked the consistency of the results? So the graph resulting is the same in 0.25 and 0.26? If you haven't maybe you can just  capture and compare the output of the ``info`` command. We have added a few tests more, but that would help to make sure the algorithm changes didn't affect something unexpectedly. Thanks very much again.

**Comment by claasd** [comment]
Hi,

attached are the info outputs.
From a first glace it looks good. 
Hundrets of lines like 
```Version range '~0.3' required by 'A/1.7.0-beta-build.153@user/testing' valid for downstream requirement 'CMakeMacros/0.3.0-build.147@user/testing'```
are missing when using 0.26 (wich is good).
Also, the order of the infos has changed, making it kind of hard to check if everything is consistent. 
[info-result-0.25.1.txt](https://github.com/conan-io/conan/files/1260156/info-result-0.25.1.txt)
[info-result-0.26.0rc1.txt](https://github.com/conan-io/conan/files/1260157/info-result-0.26.0rc1.txt)

**Comment by memsharded** [comment]
Hi @claasd 

I am inspecting the logs, I am a bit surprised about this:

``` Requires:
        CMakeMacros/0.3.0-build.147@user/testing
        CMakeMacros/0.3.0-build.147@user/testing
        CMakeMacros/0.3.0-build.147@user/testing
        CMakeMacros/0.3.0-build.147@user/testing
        ...
```

What am I missing? Conan has some check to avoid duplicated requirements form the same package, so no idea what could be happening to have this output. Please consider opening a new issue to manage this, or ask if you need access to our slack to discuss or any other channel

**Comment by memsharded** [comment]
Also, I have processed the graphs, and I am detecting some differences. For example:

```
Node  myOrg.ServiceComm.SQ/0.10.0-beta-build.153@user/testing
Different requires
['Boost/1.63.0@user/extern', 'CMakeMacros/0.3.0-build.147@user/testing', 'cppzmq/4.2.2-pre@user/extern', 'libzmq/4.2.2@user/extern', 'myOrg.Commons/1.8.3-unreleased-build.189@user/testing', 'myOrg.IoC/1.7.0-beta-build.142@user/testing', 'myOrg.Logging/1.7.0-beta-build.153@user/testing']
['Boost/1.63.0@user/extern', 'CMakeMacros/0.3.0-build.147@user/testing', 'cppzmq/4.2.2-pre@user/extern', 'libzmq/4.2.2@user/extern', 'myOrg.Commons/1.8.3-unreleased-build.189@user/testing', 'myOrg.IoC/1.7.0-beta-build.142@user/testing', 'myOrg.ServiceComm/0.10.0-beta-build.162@user/testing']
```

I assume that you are running exactly on the same data, so there might be a bug in the new graph algorithm in the RC :( :( :( I have to investigate. Could you please have a look to the above difference, in case it makes some sense to you that help debugging this? Many thanks

**Comment by memsharded** [comment]
I would like to ask, about 2 requirements: Boost/1.63.0@user/extern, and CMakeMacros/0.3.0-build.147@user/testing, I guess they could be "private", is it possible?

**Comment by claasd** [comment]
Yes, CMakeMacros are private requirements. Most developers did not yet switch to build_requires.
At least on package uses Boost as private requirement, other use it as public requirement.

**Comment by claasd** [comment]
Do you still need feedback for the differences in requirements? The comments is not here anymore ...

**Comment by memsharded** [comment]
Ok, thanks very much for the feedback. That makes sense. I am right now investigating about the possible impact on this. Fortunately the packages ID are not affected, so that is good. Enough for now, I will keep updated if need more info.

**Comment by memsharded** [comment]
@claasd I think you will be mostly fine, the graph seems consistent. It just have less duplicated nodes for ``CMakeMacros/0.3.0-build.147@user/testing``, that is why now in 0.26 they do not appear as duplicated ``Requires``, which I think is an improvement. It hasn't affected the package binary IDs, so all good. The duplicated nodes for Boost are consistent too.

I have also checked with other users projects, and the new algorithm seems totally consistent when not using private requirements, and returning a different graph, but a better, simplified one, in case of having private requirements.

Thanks very much for your help!!
