### ISSUE TITLE
[question] Conan tries to download the latest revision from conan remote repository when using local repository

### ISSUE THREAD

**Issue by tmiseikis** [conan-io/conan#16146]
### What is your question?

Hi,

I have set up conan repositories in JFrog Artifactory using https://jfrog.com/help/r/jfrog-artifactory-documentation/set-up-a-conan-repository guide. So essentially I now have a local repository called `conan-local`, a remote repository called `conan-remote`, and a virtual repository called `conan` in my Artifactory. 

My understanding is that Conan will always try to download the latest revision of a recipe unless a revision is explicitly specified in the conanfile.py or when using lockfiles. Is this correct?

My other understanding is that if a local repository is explicitly specified when running `conan install -r conan-local` then Conan will use the latest revision of a recipe in _that_ local repository and not in the remote repository. Is that correct?

If that is correct, then I don't understand why I am getting an error when doing this:

1. Build 32-bit version of `boost/1.83.0` and upload it to my `conan-local` repository. The revision of this library is `boost/1.83.0#20336b52d154a33834c8087c4dffed8f`
2. Delete this boost recipe from my local cache.
3. Run `conan install --output-folder=build --remote=conan-local .`
4. Error:

```
Requirements
    boost/1.83.0#163e26b9dc12e73728e4d3c489bec1bd:36ff1e91df00be599aedba6dfb8f3d47241ced61 - Missing
ERROR: Missing binary: boost/1.83.0:36ff1e91df00be599aedba6dfb8f3d47241ced61
```

Why is Conan trying to download revision `boost/1.83.0#163e26b9dc12e73728e4d3c489bec1bd`, which is of the moment of writing (2024.04.25) the latest recipe revision for 1.83.0 version of boost on https://conan.io/center/recipes/boost?version=1.84.0, instead of downloading the latest revision that is in my local repository?

I can fix this by explicitly specifying the revision number in my conanfile.py, but I don't understand why I need to do that when I already instruct conan to use my local repository.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tmiseikis 

Thanks for your question.

> My understanding is that Conan will always try to download the latest revision of a recipe unless a revision is explicitly specified in the conanfile.py or when using lockfiles. Is this correct?

Yes, this is correct.

> My other understanding is that if a local repository is explicitly specified when running conan install -r conan-local then Conan will use the latest revision of a recipe in that local repository and not in the remote repository. Is that correct?

Not exactly. Conan will always prioritize whatever is already in the cache by default. This will only use a more modern revision from the server if you request ``conan install ... --update -r=conan-local``. It will also only update that revision if it is more modern than the one that you have in the cache.

Does this explain what you are experiencing?

If that is the case, it is true that going back in time to that revision when you already have that in cache would need either to remove the local cache revision first, or to use a lockfile (you can also pin the ``requires`` revision, but generally lockfiles are used for this purpose).

**Comment by tmiseikis** [comment]
> Not exactly. Conan will always prioritize whatever is already in the cache by default.

Yes, I understand this, but in my scenario I did remove boost/1.83.0 from my cache:

```
conan list boost*
Found 0 pkg/version recipes matching boost* in local cache
Local Cache
  WARN: There are no matching recipe references
```

> This will only use a more modern revision from the server if you request ...

When you say "from the server" what does that mean? 

E.g. if I have `lib/1.0#rev1` in my `conan-local` and there exists `lib/1.0#rev2` in `conan-remote`, and I run `conan install ... --update -r=conan-local`, is it expected that I get `lib/1.0#rev2` and not `lib/1.0#rev1`? Because that's the behavior I am seeing, yet I would expect to get `lib/1.0#rev1`, because that's what exists in my `conan-local` repository.

**Comment by tmiseikis** [comment]
Perhaps I am confusing things here and the reality is: Conan always knows about that latest revision of the recipe and Artifactory is just a way to tell Conan where to get those revisions from? So running `conan install ... --update -r=conan-local` simply means: download latest recipe revision from the remote called `conan-local`.

So if the Conan server knows that there exists `lib/1.0#rev2` it will try to find it in `conan-local` instead of using `lib/1.0#rev1` that already exists in `conan-local`. And will fail if this revision does not exist in `conan-local`.

Is this an accurate summary?

**Comment by memsharded** [comment]
> E.g. if I have lib/1.0#rev1 in my conan-local and there exists lib/1.0#rev2 in conan-remote, and I run conan install ... --update -r=conan-local, is it expected that I get lib/1.0#rev2 and not lib/1.0#rev1? Because that's the behavior I am seeing, yet I would expect to get lib/1.0#rev1, because that's what exists in my conan-local repository.

Let me double check this just in case, I'll write a test with this case.

**Comment by memsharded** [comment]
```python
def test_update_revisions_multiple_servers():
    """ https://github.com/conan-io/conan/issues/16146
    """
    c = TestClient(servers=OrderedDict({"server1": TestServer(), "server2": TestServer()}),
                   inputs=2 * ["admin", "password"])
    c.save({"conanfile.py": GenConanfile("pkg", "0.1")})
    c.run("create .")
    rrev1 = c.exported_recipe_revision()
    c.run("upload * -r=server1 -c")
    
    # Do a modification to force a new revision, rrev2 will be newer than rrev1
    time.sleep(1)
    c.save({"conanfile.py": GenConanfile("pkg", "0.1").with_class_attribute("potato = 42")})
    c.run("create .")
    rrev2 = c.exported_recipe_revision()
    c.run("upload * -r=server2 -c")
    
    # Clear the cache, and install from server 1
    c.run("remove * -c")
    c.run("install --requires=pkg/0.1 -r=server1 --update")
    print(c.out)
    assert rrev1 in c.out
    assert rrev2 not in c.out
```
This test passes green. You can check there are two servers, no matter if the ``rrev1`` is older than ``rrev2``, if I install only from the server1, I only get that revision not the other one.

> ERROR: Missing binary: boost/1.83.0:36ff1e91df00be599aedba6dfb8f3d47241ced61

The fact that the binary is missing seems unrelated to this recipe-revisions issue, that might be a different issue.

> So if the Conan server knows that there exists lib/1.0#rev2 it will try to find it in conan-local instead of using lib/1.0#rev1 that already exists in conan-local. And will fail if this revision does not exist in conan-local.

Servers do not connect repositories information. If you are using ``-r=server1``, whatever is stored in other repositories is unknown at this point.

I think it would be good to complete your repro above with some extra steps and data:
1. Build 32-bit version of boost/1.83.0 and upload it to my conan-local repository. The revision of this library is boost/1.83.0#20336b52d154a33834c8087c4dffed8f => Lets do it with a ``conan new cmake_lib -d name=mypkg -d version=0.1`` + ``conan create .`` + report the full output.
2. Upload it to the server. Report the upload logs
3. Do a ``conan list mypkg/0.1#* -r=myserver`` to make sure the revision is there and it is the latest.
4. Delete this boost recipe from my local cache.
5. Run conan install --output-folder=build --remote=conan-local . Share the full logs

**Comment by tmiseikis** [comment]
Could you please clarify the steps: 

On Step 1, should I add boost dependency to the generated "mypkg" conanfile, or should I keep it as is?
On Step 4, did you mean to write "remove mypkg from the local cache" and not Boost?
On Step 5, won't this just run the "generate" method in the conanfile.py of "mypkg", without really doing anything with the remote?

**Comment by memsharded** [comment]
> On Step 1, should I add boost dependency to the generated "mypkg" conanfile, or should I keep it as is?

Not necessary. If this is an issue of revisions management, updates, etc, we should be able to reproduce nicely with a simple self-contained recipe too, that will build much faster than boost if necessary, and can easily help in reproduction, as we will also get the same recipe revisions. It is just a way to do a more isolated and reproducible case. Something closer to the unit test that I shared above, that doesn't use boost at all, and still validates the revisions behavior with 2 remotes and ``--update``.

**Comment by tmiseikis** [comment]
@memsharded - sorry for the delay. I did some more testing and concluded that I was wrong. It looks like it works correctly as you described. I am not sure why I was seeing the strange behavior, perhaps my cache was not completely clean and Conan was pulling the newer revisions from there.

Anyways, sorry for the confusion and thank you for your time.

**Comment by memsharded** [comment]
> Anyways, sorry for the confusion and thank you for your time.

No problem, always happy to help. Don't hesitate to open new tickets of any other question or issue that you might have. Thanks!
