### ISSUE TITLE
[question] how to solve "'tools.env.virtualenv:auto_use' does not exist in configuration list or the conf format introduced is not valid."

### ISSUE THREAD

**Issue by petaflot** [conan-io/conan#16143]
### What is your question?

it's all in the title.

```
(py311) meta@gentx ~/_git/CuraEngine $ conan install . --build=missing --update
ERROR: [conf] Either 'tools.env.virtualenv:auto_use' does not exist in configuration list or the conf format introduced is not valid. Run 'conan config list' to see all the available confs.
(py311) meta@gentx ~/_git/CuraEngine $  conan config list | grep auto_use
(py311) meta@gentx ~/_git/CuraEngine $  
```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @petaflot 

``auto_use`` is a Conan 1.X configuration, that doesn't exist anymore in Conan 2.
But it seems you are using Conan 2, so it is complaining that such an unknown configuration is provided. Please make sure to either remove that configuration (if you intend to use Conan 2), or to make sure that Conan 1 is installed.
