### ISSUE TITLE
[question] Library header files can't be found 

### ISSUE THREAD

**Issue by Sickeroni** [conan-io/conan#16159]
### What is your question?

# disclaimer
In the First place a question, but maybe already a feature request. I'm not even sure if conan itself is the right place for this.  

# System details
* WSL with ubuntu.22.04  under Windows 11 
* g++-12 (through apt)
* cmake 3.29.2 (through snap) 
* Conan  2.0.16
* VS Code with cmake plugin 1.88.1
* Project uses the conan provider file 

# The Problem 
It's so far mostly annoying and it slow downs developing. 

For every library provided by conan, the header files can't be found in vscode so far. 
But they can be found by the build process itself. 
For external libraries like `fmt` it can be okayish, but we develop custom libraries and for debug purposes this is a big deal. Also even header of external libraries can provide helpful details about some functions, when used. 

![image](https://github.com/conan-io/conan/assets/4477853/be02f939-bb7e-4858-8b0b-bedcf625dd12)

Also since i can't remember to ever had that problem, i think it worked prior than using conan.

#  Expected behaviour:
Click on a header in vscode and just press F12 to open the corresponding, conan provided file.  

# other sources 
The only search result I could find was this similar one
https://github.com/microsoft/vscode-cmake-tools/issues/1735
But based on the result it's already fixed in vscode 1.7.0 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Sickeroni 

Thanks for your question.

I am not sure what Conan can do in this regard either.
Conan just generates ``xxx-config.cmake`` files and ``conan-toolchain.cmake`` that CMake correctly understands, so up to our knowledge they are correct in that regard.

I don't know how VSCode or the VSCode plugins (cmake-tools) are working to provide navigability to headers, but I would assume they would be taking the information from the build system, but apparently it doesn't if it is not working? 

We would need better understanding on how VSCode works in this regard, and what could be missing.

**Comment by SpaceIm** [comment]
I use VSCode for C++, and it depends on the plugin used for C++ completion/intellisense etc. Most populars are "C/C++" and "clangd" I would say (and looking at your error, I guess it's "C/C++").

When you use CMake, these plugins expect to see `compile_commands.json` generated by CMake configuration in some predefined or customizable location.

So for me it's an issue related to your VSCode settings, not to conan.

**Comment by Sickeroni** [comment]
This makes completly sense.
therefore close and big thanks for the fast answers!
