### ISSUE TITLE
Conan to generate conanbuild.csh/tcsh files if using csh or tcsh as default shell.

### ISSUE THREAD

**Issue by sharadupadhyaya** [conan-io/conan#16154]
### What is your suggestion?

Currently, there's no option to generate a .tcsh/.csh script with Conan.
Conan commands are generating conanbuild.sh files for bash only.
This impacts the workflow for developers who use tcsh/csh as default shell.
Will be great to add support in Conan to generate conanbuild scripts for tcsh/csh.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sharadupadhyaya 

Thanks for your suggestion.

At the moment adding other shell dialects is not planned. Supporting new shell formats is fragile and quite a large effort for the value, as switching to bash is relatively easy. Furthermore Conan keeps doing more efforts to not require using env-vars files, for example, now the build environment is also added to the CMakePresets.json.

Closing as unplanned, thanks again for your feedback.
