### ISSUE TITLE
How to instruct Conan to generate conanbuild.csh files if using csh or tcsh as default shell.

### ISSUE THREAD

**Issue by sharadupadhyaya** [conan-io/conan#16150]
### What is your question?

Hi, by default I use csh/tcsh.
Conan commands are generating conanbuild.sh files. Is there an option to generate a tcsh script by Conan?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @sharadupadhyaya,
Thanks for the question.
There's no option to generate a `.tcsh` script with Conan. We are not planning currently to add it but we are always open to accepting PR's to improve functionalities. We have another one that's under review right now for `fish` if you want to check an example for that: https://github.com/conan-io/conan/pull/15503

**Comment by sharadupadhyaya** [comment]
Thanks @czoido , I will raise a PR for it.

**Comment by sharadupadhyaya** [comment]
Created requirement #16154

**Comment by czoido** [comment]
> Created requirement #16154

Thanks @sharadupadhyaya, let me close this issue then and we can leave the other one open.
