### ISSUE TITLE
[bug] Chevron versions with prereleases include breaking changes

### ISSUE THREAD

**Issue by AshleighAdams** [conan-io/conan#16156]
### Describe the bug

Using a package with a version range of `[^1.0.0, include_prereleases=True]` incorrectly includes prereleases for version 2.0.0 packages

It looks like it's effectively being expanded to `[>=1.0.0 <2.0.0, include_prerelease=True]` instead of the expected `[>=1.0.0 <2.0.0-0, include_prerelease=True]` as the documentation indicates

Conan version: 1.64.0
Environment: Windows 11 x64

### How to reproduce it

Create a recipe/package with versions v1.0.0 and v2.0.0-alpha.1, then attempt to resolve a dependency on `[^1.0.0, include_prerelease=True]` of the package, Conan will incorrectly grab v2's prerelease

**Comment by memsharded** [comment]
Hi @AshleighAdams 

Thanks for your report.

I have just tried it, adding an extra test, and it seems it has been solved in Conan 2.
The issue in Conan 1 is that Conan 1 uses an external library ``python-node-semver`` to resolve versions, so it is outside of scope, this is not expected to get any new fixes (also Conan 2 is the mainstream and recommended version nowadays, it was released now more than 1 year ago, most of dev efforts go to it, Conan 1 is in maintenance mode, critical regressions, backports necessary to smooth the migration to 2.0)

Maybe you can try converting the expression to a explicit one with ``>=xxx <yyyy`` one.

**Comment by AshleighAdams** [comment]
Yeah, that's what we are doing for now, our of curiosity, was this version ever pulled in? https://github.com/podhmo/python-node-semver/pull/40

Not sure if that PR would have fixed the issue or not

**Comment by memsharded** [comment]
That PR seems to belong to 0.9.0, but Conan 1 is pinning ``node-semver==0.6.1``, because newer versions of that dependency also introduced some potentially breaking changes (and it was also a reason why this responsibility was embedded and developed in Conan 2 as built-in and not externally, to be able to have full control, do bug fixes and protect stability and evolve while not breaking users code)

**Comment by AshleighAdams** [comment]
I understand, feel free to close as wontfix
