### ISSUE TITLE
[bug] conan new --help formatting issue

### ISSUE THREAD

**Issue by ashley-b** [conan-io/conan#16151]
### Describe the bug

OS: Fedora release 39
Conan version: 2.2.3

When showing the help for `conan new`
there is no space between **local_recipes_index** and **E.g**

```
positional arguments:
  template              Template name, either a predefined built-in or a user-provided one. Available built-in templates: basic, cmake_lib, cmake_exe, meson_lib, meson_exe, msbuild_lib, msbuild_exe, bazel_lib, bazel_exe, autotools_lib,
                        autotools_exe, local_recipes_indexE.g. 'conan new cmake_lib -d name=hello -d version=0.1'. You can define your own templates too by inputting an absolute path as your template, or a path relative to your conan
                        home folder.
```
This is the change that introduced the typo
https://github.com/conan-io/conan/pull/13930/files#diff-005f70f8e75660148b1739ca76dab6623fcfa70a993b66bc16c8534ef31350aa

May the E.g should be on a new line, for readability ?

Also great work on this feature local_recipes_index !
I only discovered this feature via the blog, as issue #13930 does not seam to be part of the release notes for 2.2.0

### How to reproduce it

Command line
```sh
conan new --help
```

**Comment by czoido** [comment]
Hi @ashley-b,
Thanks for reporting, we will fix the _--help_ message for the next release. 
As you pointed out, the feature is not already documented, we wanted to do some extra tests before documenting but we are ready now to do that so it will be documented in following days.
Thanks a lot for testing the feature and the kind words! 🙂
