### ISSUE TITLE
Validate conanfile class after instantiating

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#1616]
Currently, `load_conanfile_class` will check two attributes of the loaded class: `name` and `version`. While these are valid checks, I'd argue that they should be checked on the instance and not on the class itself. Our usecase: we want to override `version` if `my_version` and `my_revision` are set. `version` would return `"<version>-<revision>"` as a property. We can do this in the constructor of `MyConanFile`, but conan won't load the class unless it has the version attribute set.

**Comment by memsharded** [comment]
Have you checked the new behavior from 0.25? Name and version are no longer necessary attributes. They will be assigned dynamically, and you can do:

```bash
$ conan create Pkg/0.1@user/channel
$ conan export Pkg/0.1@user/channel
```

So you don't need to code them anymore, they can be directly part of the CI if you want

**Comment by lasote** [comment]
I don't know what means the "export" in red color but to clarify, the export is not working specifying the library name and version, maybe it should but it doesn't. Currently is only taking `user/channel`.

**Comment by lasote** [comment]
I'm taking a look to the export.

**Comment by sztomi** [comment]
Thanks! I assumed that this wouldn't change with the update and haven't updated yet. I think this will solve my issue, so I'm closing it. Will reopen if it still doesn't work.

**Comment by memsharded** [comment]
@lasote Yes, sorry, I think it is the ``test_package`` that got the same functionality, but not the export. Maybe it makes sense to update the export to implement it.

**Comment by lasote** [comment]
I almost have it, will open a PR asap. I've found some "issues" with the create too so I'm adding some tests

**Comment by memsharded** [comment]
This was solved long time ago.
