### ISSUE TITLE
How exactly do I import my C and C++ modules that I have installed via Conan?

### ISSUE THREAD

**Issue by novaTopFlex** [conan-io/conan#16167]
### What is your question?

Hello! I have some questions about how exactly I import modules that I have installed via Conan to my C and C++ projects. I have attempted to utilize the `#include <[project_installed_with_conan][.h]>` format but have failed when performing such format in my C and C++ test files. How exactly can I successfully import these modules into my C code? Is the process significantly different for C++?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @novaTopFlex 

There is nothing special in the ``#include`` per se, but it is important that the packages create and declare the information correctly.

You have hands-on tutorial with working code examples in https://docs.conan.io/2/tutorial/consuming_packages.html, that you can use to check how the ``#include`` to the dependencies work.

**Comment by memsharded** [comment]
Any further feedback or question here @novaTopFlex ?

**Comment by memsharded** [comment]
Closing as staled, but please re-open or create new tickets if you any further question, thanks.
