### ISSUE TITLE
What is the correct setting for a package built with the Intel classic compilers part of the Intel oneAPI 2023.1 package?

### ISSUE THREAD

**Issue by ansutremel** [conan-io/conan#16160]
### What is your question?

Hi! I have a question regarding the correct profile settings for a package built with the Intel classic compilers being part of the Intel oneAPI 2023.1 package, which value for `compiler.version` and `compiler.mode` should be used for Conan 2?

- The Intel compiler package installed is 2023.1.0
- The integration into VisualStudio is using the toolset name `Intel C++ Compiler 19.2`
  ![image](https://github.com/conan-io/conan/assets/1674717/d33ffd4f-b00a-4800-bbba-d1a58998f708)
- The compiler version returned by running `icl.exe --version` is 2021.9.0
  ```
  C:\Program Files (x86)\Intel\oneAPI\\compiler\2023.1.0\windows\bin\intel64\icl.exe" --version
  Intel(R) C++ Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.9.0 Build 20230302_000000
  Copyright (C) 1985-2023 Intel Corporation.  All rights reserved.
  ```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @ansutremel 

Thanks for opening the issue. I think that it would be enough to use this one for instance:

```ini
[settings]
os=Windows
arch=x86_64
compiler=intel-cc
compiler.mode=classic
compiler.version=2023.1
compiler.libcxx=libstdc++
build_type=Release
```
Let me know if this is working or if you have any other doubts about using the generators there.

**Comment by franramirez688** [comment]
Any news on this, @ansutremel? If not, we could close this issue 😁

**Comment by ansutremel** [comment]
@franramirez688, @memsharded, so for Intel compilers the convention would be to follow the package version and not the result of running `icl.exe --version`?

**Comment by franramirez688** [comment]
@ansutremel I recall that it followed this versioning: https://www.intel.com/content/www/us/en/developer/articles/technical/oneapi-toolkit-version-to-compiler-version-mapping.html
So, yes, it's meant to simplify the way to put the compiler version I think.

**Comment by franramirez688** [comment]
@ansutremel Does it solve your doubt? Could we close the issue if there are no more doubts?

**Comment by ansutremel** [comment]
@franramirez688 thanks, this solves the doubts.
