### ISSUE TITLE
[question] Is there a place where the information about all include paths is available?

### ISSUE THREAD

**Issue by GRyzer** [conan-io/conan#16168]
### What is your question?

Hi,

I need the include paths that are relevant for my package. We are using an IDE in which the include paths have to be listed explicitly and which has no conan or cmake support. Accordingly, I am currently looking for a solution in which I can access all include paths in the e.g. `generate()` method, like:

```python
for element in self.dependencies.values():
    print(element.cpp_info.includedirs)
```

This results in:

```txt
conan-home/p/a123456789/p/include
conan-home/p/b123456789/p/include
conan-home/p/c123456789/p/include
conan-home/p/d123456789/p/include
conan-home/p/e123456789/p/include
conan-home/p/f123456789/p/include
conan-home/p/g123456789/p/include
```

I know that I can get to my include paths of the dependencies this way. However, I am missing the include paths which I have set in my `CMakeLists.txt`.
In CMake I can access my include paths as follows.

```cmake
get_target_property(MY_INCLUDE_DIRS ${MyTarget} INCLUDE_DIRECTORIES)
foreach(DIR ${MY_INCLUDE_DIRS})
  message("Include directory: ${DIR}")
endforeach()
```

This results in:

```txt
Include directory: package-path/./include
Include directory: package-path/./src
Include directory: $<BUILD_INTERFACE:package-path/include>
```

Currently I do not have a list of all include paths in any place.
Is there a possibility that I can access all include paths in Conan?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @GRyzer 

Thanks for your question.

> I know that I can get to my include paths of the dependencies this way. However, I am missing the include paths which I have set in my CMakeLists.txt.

Yes, the ``dependencies`` interface only contains the information of the dependencies, but the current project is not included in that list, as it is not a dependency.

If you have modeled correctly your ``layout()``, then the information for the local development layout will be in the ``self.cpp.build``  (this would be for automatically generated code, build-temporary, but code) and the ``self.cpp.source`` (for regular sources) interfaces.

Please have a look to https://docs.conan.io/2/tutorial/developing_packages/package_layout.html for further details.

**Comment by GRyzer** [comment]
Thank you for the answer. My layout method looks like:

```python
def layout(self):
    cmake_layout(self)
```

I have used the CMake command `target_include_directories()`:

```cmake
target_include_directories(${MyTarget} 
    PUBLIC ./include
    PRIVATE ./src
)
```

I assume that you want me to do something like this:

```python
def layout(self):
    cmake_layout(self)
    self.cpp.package.includedirs = ["include", "src"] 
```

So i conclude that i cannot use only CMake commands to specify the include paths but also need to specify them in the `layout()` method. Is my assumption correct? 

If I look at [cpp.package](https://docs.conan.io/2/tutorial/developing_packages/package_layout.html#cpp-package), then the effect is the same as using `self.cpp_info.includedirs = ['include', 'src']`. But i dont want to provide `src` as an include path for consumers. It should be a private path, for internal use only.

**Comment by memsharded** [comment]
Yep, the default ``cmake_layout()`` has this:
```python
conanfile.cpp.source.includedirs = ["include"]
```

Please note that this only covers the "public" interfaces, it is not intended to expose the internal headers to consumers. 
If you are looking to also add the internal header paths, then why not just generating what you want in the ``generate()`` method? You have there the folders defined, like ``self.source_folder``, so if you already know the layout of your current project, you might be able to just append those folders to the folders that you accumulated from ``self.dependencies``?

**Comment by GRyzer** [comment]
I think the main issue here is the lack of knowledge on my side.
I was hoping to be able to set my private include paths in one place. If I do this in CMake, then I would have these private paths available in my `generate()` method. If I specify my private include paths in the `generate()`method, I would like to be able to use them easily in CMakeLists.txt.
So unfortunately i dont really understand your hint :D 
Because my private include paths will differ from package to package, so i cannot make the assumption that my include path is always `self.source_folder.joinpath('src')`.

**Comment by memsharded** [comment]
> I think the main issue here is the lack of knowledge on my side.
I was hoping to be able to set my private include paths in one place. If I do this in CMake, then I would have these private paths available in my generate() method. If I specify my private include paths in the generate()method, I would like to be able to use them easily in CMakeLists.txt.
So unfortunately i dont really understand your hint :D

No prob :) 

The thing is that Conan is a package and dependency manager, not really a build system or a project manager. As such, it doesn't model the current build system or the current project layout, or it is prepared to model it only for the external interface, that is for other packages that would be using this package.

The internal headers of the project are for Conan an internal implementation detail. Conan never needs it for anything, not even for the package in ``editable`` mode, so it doesn't model internal project headers, which seems what you would like to do in the ``generate()`` method.

> Because my private include paths will differ from package to package, so i cannot make the assumption that my include path is always self.source_folder.joinpath('src').

The ``generate()`` method would then probably change from package to package, to adapt to the current project layout. Maybe it is not a big issue if many of your projects have more or less the same layout, or if your IDE won't complain about unexisting paths, you might just add all the typical paths where your headers could be. 

Another idea could be just to ``os.walk(self.source_folder)`` in the ``generate()`` method, looking for files with your header extensions and add them to the lists of paths from ``self.dependencies``. It might be a bit slower, but unless your project is really huge, you wouldn't notice.

Please let me know if this helps.

**Comment by GRyzer** [comment]
Thanks a lot, I appreciate your effort. 
I know that I use Conan also a bit for things which are not intended. But Conan holds a lot of information about a package :)
Actually, I would have to write a special generator that acts like CMakeDeps. However, this is too complex for my level of knowledge. Maybe in the future :D

**Comment by memsharded** [comment]
Thanks for your feedback!

Don't hesitate to open new tickets for any further question or issue you might have.

> Actually, I would have to write a special generator that acts like CMakeDeps.

This is not that scary, specially if you know well your build system, taking inspiration of some of the simpler generators like ``AutotoolsDeps`` (instead of ``CMakeDeps`` which would be the most complex), wouldn't be a huge task, we will try to help.
