### ISSUE TITLE
[question] Editable libs not removable if deleted

### ISSUE THREAD

**Issue by Sickeroni** [conan-io/conan#16164]
### Describe the bug

# Error:
If you remove folders that are in editable mode, there is no easy way to remove them from the editable list anymore.

# workaround: (not tested)
create new conanfile.py in the specific location. 
then it should work again. 

# Expected  behaviour:
using `conan editable remove [folder]` should remove ALL packages in the editable list from that location. 
using `conan editable remove [folder]\conanfilefilename.py` should remove that specific packages in the editable list.
The second suggestion is only for simplification, even through the location could have more files than the default `conanfile.py`. 
The big difference is to the current behaviour, that the folder can be already deleted. 

### How to reproduce it

```shell
conan new something # creating a new lib, replace with proper command 
conan editable add [folder]
rm -r [folder]
conan editable list
conan editable remove [folder] 
# getting Error
conan editable list
# still see the same list
```

**Comment by memsharded** [comment]
Hi @Sickeroni 

Thanks for your question.

> If you remove folders that are in editable mode, there is no easy way to remove them from the editable list anymore.

If you remove the folder containing the editable, you can still remove that editable by reference:
```bash
$ conan editable remove -r=mypkg/0.1
```
Have you tried that?

**Comment by Sickeroni** [comment]
Hey
Yeah i just tried it and it works!
therefore already thanks! (also because you were fast with helping) 

But now i have a new question.
I would suggest a feature request to have the specific fallback above.  (if directory is removed, still interpret it as it would be) 
It would much more intuitive and userfriendly. 

But I don't think it was never discussed. Can i get some infos about that situation?
(also i qill change the topic to be officially a question)

**Comment by memsharded** [comment]
> But now i have a new question.
I would suggest a feature request to have the specific fallback above. (if directory is removed, still interpret it as it would be)
It would much more intuitive and userfriendly.

Sounds reasonable, not sure how difficult it is (I think the way it works now is loading the recipe inside the folder, to obtain the reference), lets have a look.

**Comment by memsharded** [comment]
Happens to be trivial, https://github.com/conan-io/conan/pull/16170 planned for next 2.3

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/16170, will be in 2.3
