### ISSUE TITLE
[question] How to properly build and install self-made headers and libraries with CMake and Conan for the consumer?

### ISSUE THREAD

**Issue by Isaacwhyuenac** [conan-io/conan#16183]
### What is your question?

# Describe the bug

```conf
❯ conan profile show  
Host profile:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

Build profile:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

```

## Description

I am building a [sample library](https://github.com/Isaacwhyuenac/cpp-namespace-example) with a folder structure like this

```tree
├── CMakeLists.txt
├── conanfile.py
├── include
│   └── my_foundation
│       └── my_algorithm.h
├── src
│   └── my_algorithm.cpp
└── test_package
    ├── CMakeLists.txt
    ├── conanfile.py
    └── src
        └── example.cpp
```

I hope my internal library in `src` would consume the `include/my_foundation/my_algorithm.h` file without the `my_foundation` namespace like this

```cpp
// src/my_algorithm.cpp

#include "my_algorithm.h" // not "my_foundation/my_algorithm.h"
```

While all the consumers like `test_package/src/example.cpp` would consume the library with the namespace

```cpp
// test_package/src/example.cpp
#include "my_foundation/my_algorithm.h"
```

Currently in [my sample repo]((https://github.com/Isaacwhyuenac/cpp-namespace-example)), I managed to build the library in a lib file BUT all my headers are not included in the final package.

![20240430-183736](https://github.com/conan-io/conan/assets/13378284/6ce1be3b-4f33-40e3-8783-29aac66e691a)

I tried the following directives in my main `CMakeLists.txt` file but the `include` directory is still not included

```cmake
add_library(my_foundation STATIC src/my_algorithm.cpp)
target_include_directories(my_foundation INTERFACE include)
target_include_directories(my_foundation PRIVATE include/my_foundation)

install(TARGETS my_foundation
        PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/include/my_foundation # NOT WORKING
)
```

May I know what I have to modify in order to make my library consumable to the "external" applications??
 

# How to reproduce it
## Commands

```shell
conan new cmake_lib -d name=my_algorithm -d version=0.0.1

conan install .
cmake --preset conan-release
cmake --build --preset conan-release
```

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Isaacwhyuenac 

Thanks for your question.

> I hope my internal library in src would consume the include/my_foundation/my_algorithm.h file without the my_foundation namespace like this

I'd like to challenge this. In my experience (not talking about Conan specifically, but as a C++ developer for decades), it is almost always better to use the same ``#include`` paths both in development and for final consumption. The build systems and compilers "include paths" definition allows to have this easily.

Otherwise, this is mostly a CMake question, not a Conan one. You had:

> install(TARGETS my_foundation
        PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/include/my_foundation # NOT WORKING
)

Use this ``CMakeLists.txt``:
```cmake
cmake_minimum_required(VERSION 3.15)
project(mypkg CXX)

add_library(mypkg src/mypkg.cpp)
target_include_directories(mypkg PUBLIC include)

set_target_properties(mypkg PROPERTIES PUBLIC_HEADER "include/mypkg.h")
install(TARGETS mypkg PUBLIC_HEADER DESTINATION include/myfolder)
```
And change the ``test_package`` include to ``#include "myfolder/mypkg.h"`` and it will work.

Please try that and let me know.

**Comment by Isaacwhyuenac** [comment]
Hi @memsharded.

Thank you for your quick response.

I updated my code based on your recommendation and still have some issues. 

```console
cpp-namespacing/test_package/src/example.cpp:1:10: fatal error: 'my_foundation/my_algorithm.h' file not found
#include "my_foundation/my_algorithm.h"
```

Seems the `test_package` cannot find my header files and the `install(TARGETS my_foundation PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/include/my_foundation)` is not copying the `include` directory to the `build/Release` folder.....

I have updated my code to [Here](https://github.com/Isaacwhyuenac/cpp-namespace-example/blob/memsharded/CMakeLists.txt#L4-L10)

**Comment by memsharded** [comment]
> install(TARGETS my_foundation PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/include/my_foundation)

You are copying it wrong. Please copy my ``CMakeLists.txt`` on top of yours. Or omit the ``${CMAKE_INSTALL_INCLUDEDIR}``, which is creating a double ``include`` folder

**Comment by Isaacwhyuenac** [comment]
Thank you for your advice. It is working.

**Comment by memsharded** [comment]
> Or omit the ${CMAKE_INSTALL_INCLUDEDIR}, which is creating a double include folder

I understand that with this change it worked? 🙂 

Happy if that is the case, thanks for the feedback!
