### ISSUE TITLE
[bug] Cannot install packages on Ubuntu 24.04 

### ISSUE THREAD

**Issue by f-scholer** [conan-io/conan#16181]
### Describe the bug

I am not able to install any packages such as cppcheck, fmt or zlib with Conan 2.2.3 on Ubuntu 24.04

**conan profile detect && conan install --tool-requires cppcheck/2.14**
detect_api: Found gcc 13
detect_api: gcc>=5, using the major as version
detect_api: gcc C++ standard library: libstdc++11

Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

WARN: This profile is a guess of your environment, please check it.
WARN: The output of this command is not guaranteed to be stable and can change in future Conan versions.
WARN: Use your own profile files for stability.
Saving detected profile to /root/.conan2/profiles/default

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

======== Computing dependency graph ========
cppcheck/2.14: Not found in local cache, looking in remotes...
cppcheck/2.14: Checking remote: conancenter
cppcheck/2.14: Downloaded recipe revision 79f1ba3ee1e49ae1c1767857ac29a708
pcre/8.45: Not found in local cache, looking in remotes...
pcre/8.45: Checking remote: conancenter
pcre/8.45: Downloaded recipe revision 64cdfd792761c32817cd31d7967c3709
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Checking remote: conancenter
bzip2/1.0.8: Downloaded recipe revision 457c272f7da34cb9c67456dd217d36c4
zlib/1.3.1: Not found in local cache, looking in remotes...
zlib/1.3.1: Checking remote: conancenter
zlib/1.3.1: Downloaded recipe revision f52e03ae3d251dec704634230cd806a2
Graph root
    cli
Build requirements
    bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4 - Downloaded (conancenter)
    cppcheck/2.14#79f1ba3ee1e49ae1c1767857ac29a708 - Downloaded (conancenter)
    pcre/8.45#64cdfd792761c32817cd31d7967c3709 - Downloaded (conancenter)
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Downloaded (conancenter)
Resolved version ranges
    zlib/[>=1.2.11 <2]: zlib/1.3.1

======== Computing necessary packages ========
cppcheck/2.14: Compatible package ID 359e36e09bd9d25ba8981402975b05eeca04c5e2 equal to the default package ID: Skipping it.
Build requirements
    cppcheck/2.14#79f1ba3ee1e49ae1c1767857ac29a708:359e36e09bd9d25ba8981402975b05eeca04c5e2 - Missing
Skipped binaries
    bzip2/1.0.8, pcre/8.45, zlib/1.3.1
ERROR: Missing binary: cppcheck/2.14:359e36e09bd9d25ba8981402975b05eeca04c5e2

cppcheck/2.14: WARN: Can't find a 'cppcheck/2.14' package binary '359e36e09bd9d25ba8981402975b05eeca04c5e2' for the configuration:
[settings]
arch=x86_64
os=Linux
[options]
have_rules=True
[requires]
bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4:432d7695adc526147073285e155d2ca0340bc76d
pcre/8.45#64cdfd792761c32817cd31d7967c3709:ff07c65def72743f7d4456ad10cd9433535cd8ed
zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:c81087b06d1a5beef0ad711fc32d45f7a425a8f3

ERROR: Missing prebuilt package for 'cppcheck/2.14'. You can try:
    - List all available packages using 'conan list cppcheck/2.14:* -r=remote'
    - Explain missing binaries: replace 'conan install ...' with 'conan graph explain ...'
    - Try to build locally from sources using the '--build=cppcheck/2.14' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'

### How to reproduce it

conan profile detect && conan install --tool-requires cppcheck/2.14

**Comment by f-scholer** [comment]
works with "--build missing".

**Comment by AbrilRBS** [comment]
Hi! Thanks a lot for your question.

As the error message points out, this means that no binary is available for your current configuration. Conan Center Index builds a restricted set of binaries, and as described in the error message and the linked URL docs, for those cases you need to explicitly tell conan that it needs to build those missing binaries.

In this case I was nontheless able to regenerate those binaries on our side, so trying the same command might now as expected, let me know if that's the case! :)

**Comment by f-scholer** [comment]
Thanks for your detailed explanation. I had clearly not understood the error message initially.
I still cannot build cppcheck/2.14 without "--build missing", but this is not really an issue for me though.
