### ISSUE TITLE
[bug] Wrong version number in generated pkg-config files.

### ISSUE THREAD

**Issue by rbehrends** [conan-io/conan#16197]
### Describe the bug

I am not sure whether to best report this bug in this repo or in the conan center repo. While it appears to be a problem with the `fontconfig` recipe, the underlying problem may be more general.

The problem is basically that `fontconfig` has a dependency on `freetype`, but that the version number of `freetype` in the generated `pkg-config` is wrong, using the recipe's version number instead of that of the library proper. However, that only happens in the presence of a `conan.lock` file, not without. This problem seems to occur regardless of operating system and has been tested with Conan 2.2.3.

### How to reproduce it

The following files contain a minimal reproducible example.

- `conanfile.txt`

```
[requires]
fontconfig/2.15.0

[tool_requires]
cmake/3.26.4

[generators]
CMakeDeps
CMakeToolchain
```

- `conan.lock`

```
{
    "version": "0.5",
    "requires": [
        "freetype/2.13.2#dfa3d504cae4a08d5c72113bd6f28498%1709741165.8"
    ],
    "build_requires": [
    ],
    "python_requires": [],
    "config_requires": []
}
```

- `build.sh`

```
set -e
export CONAN_HOME=$PWD/.conan-cache
conan profile detect
conan install . --build=missing --lockfile-partial --output-folder=output
```
If you run `build.sh`, and then do:

```
cat .conan-cache/p/b/fontc*/b/build-release/conan/freetype2.pc
```

you should get something along the following lines (note the version number, which is the version of the freetype recipe, not that of the freetype library)):

```
prefix=/opt/testdir/.conan-cache/p/b/freetd8f1acf36f49f/p
libdir=${prefix}/lib
includedir=${prefix}/include
includedir1=${prefix}/include/freetype2
bindir=${prefix}/bin

Name: freetype2
Description: Conan package: freetype2
Version: 2.13.2
Libs: -L"${libdir}" -lfreetype
Cflags: -I"${includedir}" -I"${includedir1}"
Requires: libpng zlib bzip2 brotli
```

If you omit the `conan.lock` file, the error does not occur.

Somewhat curiously, this does not necessarily lead to a broken build. Under some circumstances that I haven't been able to determine, `pkg-config` still manages to retrieve a version number that allows the build to finish. The following docker file, however, seems to reproducibly result in a build error due to the wrong version number.

```
FROM ubuntu:24.04

RUN mkdir -p /opt/testdir
COPY build.sh conanfile.txt conan.lock /opt/testdir/
RUN apt-get update && \
    apt-get install -y python3 python3-venv python3-pip build-essential cmake
RUN python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    python3 -m pip install conan && \
    cd /opt/testdir && \
    bash build.sh
```

The relevant part of the build output is as follows:

```
Project name: fontconfig
Project version: 2.15.0
C compiler for the host machine: gcc (gcc 13.2.0 "gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0")
C linker for the host machine: gcc ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/opt/testdir/.conan-cache/p/pkgco03f8fb03aa80a/p/bin/pkgconf) 2.1.0
Dependency freetype2 found: NO found 2.13.2 but need: '>= 21.0.15'
Run-time dependency freetype2 found: NO (tried pkgconfig)
Found CMake: /usr/bin/cmake (3.28.3)
Run-time dependency freetype found: NO (tried cmake)
Not looking for a fallback subproject for the dependency freetype because:
Use of fallback dependencies is disabled.

../src/meson.build:32:17: ERROR: Dependency 'freetype' is required but not found.
```

I have also attached the files as [a tar.gz file](https://github.com/conan-io/conan/files/15197523/pkg-config-bug.tar.gz).

**Comment by memsharded** [comment]
Hi @rbehrends 

Thanks for your report.

This wouldn't be a bug, but expected.

You are locking old revision ``freetype/2.13.2#dfa3d504cae4a08d5c72113bd6f28498``.
This revision do not contain the line:
```python
 self.cpp_info.set_property("system_package_version", libtool_version)
```

That defines this version. So when you are not passing the lockfile it resolves to a newer revision that works.
If you rely on that behavior, you need to update your lockfile to point to a newer revision. Revision ``7934d59c447d72edcd56025dc60e1aeb`` contains this line and works as expected.

**Comment by memsharded** [comment]
I am also submitting PR with new test that more explicitly cover this scenario: https://github.com/conan-io/conan/pull/16198, it will close this ticket when merged. Thanks for the feedback!

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/16198, don't hesitate to open new tickets for any further question you might have!
