### ISSUE TITLE
[bug] Restoring the conan cache more than once corrupts artifacts

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#16199]
### Describe the bug

conan: 2.2.2
python: 3.9.18
os: rockylinux 8.8

profile:
```txt
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

### How to reproduce it

Run the following commands:

- `conan install --requires "boost/1.84.0" --build=missing --remote conancenter`
- `conan cache save *:*/*`
- `rm -rf ${CONAN_HOME}`

- Add a remote which you can upload to. e.g: `conan remote add hello https://myartifactory.mycompany.com/artifactory/api/conan/conan --force --insecure`

- Try restoring and uploading
- `conan cache restore conan_cache_save.tgz`
- Dry run an upload to confirm it would work: `conan upload "*" --remote hello --check --confirm --dry-run`
- Restore and upload a second time:
- `conan cache restore conan_cache_save.tgz`
- `conan upload "*" --remote hello --check --confirm --dry-run`

Notice that the artifacts are corrupted. The log is too long to be pasted here.

This only happens when `conan upload` is run with the `--check` option. With artifact checking skipped, it would upload just fine.

**Comment by memsharded** [comment]
Thanks for your report @Todiq 

I am trying to reproduce, but so far I haven't been able. I have done this test that works fine:

```python
def test_double_restore_integrity():
    c = TestClient()
    c.save({"conanfile.py": GenConanfile("pkg", "0.1").with_package_file("file.txt", "HELLO")})
    c.run("create .")
    c.run("cache save *:*")
    cache_path = os.path.join(c.current_folder, "conan_cache_save.tgz")
    c2 = TestClient(default_server_user=True)
    c2.run(f'cache restore "{cache_path}"')
    c2.run("upload * -r=default --check -c --dry-run")
    c2.run(f'cache restore "{cache_path}"')
    c2.run("upload * -r=default --check -c --dry-run")
```
Is this happening with every package, or only with boost?

**Comment by Todiq** [comment]
Hello @memsharded,

Indeed, I have only been able to reproduce when the initial `conan install` targets boost. However, artifacts other than boost also happen to be corrupted in the final `conan upload`.

I just tried with zlib and libbacktrace instead, but that worked fine.

**Comment by memsharded** [comment]
I have tried the exact above steps, with boost, in my Windows machine, and I could not make it fail, it works fine.

I have also tried with 2 different patterns the `` conan cache save *:*/*`` only captures recipes, not binaries, so I have also tried with `` conan cache save *:*``, which captures binaries too. It works fine in both cases.

The ``onan cache check-integrity "boost*"`` command can be a way to reproduce it easier than with the ``upload`` and I think it might probably do some better reporting of the differences, can you please try it?

**Comment by Todiq** [comment]
Looks like even I cannot reproduce it anymore. I might have encountered small unnoticed disconnections that caused a corruption? I will open back the ticket and tag you if the case ever happens again. Thanks!

**Comment by memsharded** [comment]
> Looks like even I cannot reproduce it anymore. I might have encountered small unnoticed disconnections that caused a corruption? I will open back the ticket and tag you if the case ever happens again. Thanks!

Maybe there were some operations in between that could be modifying the contents of the package folder? Like opening with an IDE that creates some ``.folder`` inside it or something like that?

Sounds good, if it happens again please re-open or create a new ticket, and maybe the ``conan cache check-integrity`` can help giving more details.
