### ISSUE TITLE
How can I read CPPFLAGS

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#16208]
### What is your question?

Hi

I am running into an issue with CPPFLAGS exceeding a length when this environment variable is set during an Integration recipe file. I wanted to try and read CPPFLAGS to capture the information and then run unset on this environment variable. How can I read this CPPFLAGS or is there a better option to use instead of reading CPPFLAGS and then unset this variable?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

Thanks for your question.

It is not very clear where and when you want to read this. If this is an environment variable set in the system, it would be a ``os.environ.get()`` or ``os.getenv()`` or similar.

But Conan does not set the env-vars in memory, but in script files like ``conanbuildenv.sh`` and the like.
Also env-vars can be defined, appended, prepended from different places, like in a profile file ``[buildenv]`` section, or in a recipe ``generate()`` method, depending what generator is collecting the CPPFLAGS from where (like defined from dependencies with the ``PkgConfigDeps`` generator? It is also possible to run commands without activating environment-variables by disabling the ``env`` files in ``self.run()``.

**Comment by Ed-CMI** [comment]
CPPFLAGS is created when running AutoToolsDeps. I wanted to read the CPPFLAGS in the generate method to gather the list of include directories that were collected based off requires used in recipe files so I can create an option file to be used during compilation. During our integration recipe file the CPPFLAGS is getting to large and when trying to invoking the makefile the following error is generated.

        ConanException: Error 3221225477 while executing

**Comment by memsharded** [comment]
I see.

The ``AutotoolsDeps`` can customize its environment as defined in the docs in https://docs.conan.io/2/reference/tools/gnu/autotoolsdeps.html#customization. 

Basically the ``environment`` attribute gives access to the environment definition, and allow manipulating it if desired.

**Comment by Ed-CMI** [comment]
I have read thru this and will unset the variable but I need to read it first. How can I read CPPFLAG before I unset the variable? The Envvars class has a way to get environment variables but I did not see this in AutoToolsDeps.

**Comment by memsharded** [comment]
It is an ``Environment`` object, first step is obtain the ``vars`` as documented in https://docs.conan.io/2/reference/tools/env/environment.html#obtaining-environment-variables, something like ``envvars = env.vars(self, scope="build")``, then you can do a ``get()`` over it (see https://docs.conan.io/2/reference/tools/env/envvars.html)

**Comment by Ed-CMI** [comment]
I tried this logic before but the _include_paths kept indicating None. Am I doing something wrong?
env = Environment()
envvars = env.vars(self, scope="build")
_include_paths = envvars.get("CPPFLAGS", default=None, variable_reference=None)
print(f"Include Paths = {_include_paths}\n")

**Comment by memsharded** [comment]
You are instantiating a new ``Environnment`` instead of using the one from ``AutotoolsDeps.environment``. Please check the above docs link: https://docs.conan.io/2/reference/tools/gnu/autotoolsdeps.html#customization

```python
def generate(self):
        tc = AutotoolsDeps(self)
        tc.environment.remove("CPPFLAGS", "undesired_value")
```
it is the ``tc.environment`` not a new (empty) ``Environment`` object one, which is expected to return ``None``.

**Comment by Ed-CMI** [comment]
Sorry Diego but I dont understand this response. My last comment ask why this code return None instead of the data currently stored in CPPFLAGS.
env = Environment()
envvars = env.vars(self, scope="build")
_include_paths = envvars.get("CPPFLAGS", default=None, variable_reference=None)
print(f"Include Paths = {_include_paths}\n")

**Comment by memsharded** [comment]
You are instantiating an empty ``env = Environment()`` object. That object is empty, it doesn't contain any env-vars defined untill someone adds information to it, like ``env.define()`` or one of the other methods. Having an empty ``Environment`` object and calling ``env.get()`` over it will always return ``None``, because that object is empty.

There is no "data currently in CPPFLAGS", the information is not stored in the global system environment variable. That information, if using ``AutotoolsDeps`` comes from the ``AutotoolsDeps.environment`` not over an empty ``Environment()`` object not connected to the ``AutotoolsDeps``.

**Comment by Ed-CMI** [comment]
Ok, Then we are back to my orginal question. How can I get the information stored in CPPFLAGS from AutoToolsDeps or is there another way to get all the includes from all the required recipe files included in the my integration recipe file?

**Comment by memsharded** [comment]
> Ok, Then we are back to my orginal question. How can I get the information stored in CPPFLAGS from AutoToolsDeps or is there another way to get all the includes from all the required recipe files included in the my integration recipe file?

```python
def generate(self):
        tc = AutotoolsDeps(self)
        env = tc.environment
        myenvvar = env.get("MYENVVAR")
        ...  # whatever you do with the env-var contents
        # you can also call other ``env`` methods
        
        tc.generate()
```

**Comment by Ed-CMI** [comment]
I tried your suggestion and got the following error when using this code
	tc = AutotoolsDeps(self)
	env = tc.environment
	_include_paths = env.get("CPPFLAGS")

ERROR: accellimrqstcoord/1.0.0.0: Error in generate() method, line 84
        self.python_requires["csarbuildenvrequires"].module.csar_generate(self)
while calling 'csar_generate', line 108
        _include_paths = env.get("CPPFLAGS")
        AttributeError: 'Environment' object has no attribute 'get'

**Comment by memsharded** [comment]
Sorry, my bad, I forgot to use the ``EnvVars`` described above:
```python
def generate(self):
        tc = AutotoolsDeps(self)
        env = tc.environment
        myenvvar = env.vars.get("MYENVVAR")
        ...  # whatever you do with the env-var contents
        # you can also call other ``env`` methods
        
        tc.generate()
```
Please try that and let me know.

**Comment by Ed-CMI** [comment]
Same issue when using  myenvvar = env.vars.get("MYENVVAR")

accellimrqstcoord/1.0.0.0:  Number of Processors = 24
ERROR: accellimrqstcoord/1.0.0.0: Error in generate() method, line 84
        self.python_requires["csarbuildenvrequires"].module.csar_generate(self)
while calling 'csar_generate', line 108
        _include_paths = env.vars.get("CPPFLAGS")
        AttributeError: 'function' object has no attribute 'get'

**Comment by memsharded** [comment]
I am writing the code by heart, I am not checking it, the docs contain the exact interfaces to use.

This is more tested, it shouldn't fail:
```python
    def generate(self):
        deps = AutotoolsDeps(self)
        env = deps.environment
        vars = env.vars(self)
        cppflags = vars.get("CPPFLAGS")
        ...
        deps.generate()
```

**Comment by Ed-CMI** [comment]
This worked. Thanks. Can you provide a link to where this is documented. I tried to check version 2.2 documentation of Conan and can't find this reference.

**Comment by memsharded** [comment]
- https://docs.conan.io/2/reference/tools/gnu/autotoolsdeps.html#customization defines the usage of ``deps.environment`` and returns an ``Environment`` object
- The ``Environment`` has a link, follow it for https://docs.conan.io/2/reference/tools/env/environment.html#obtaining-environment-variables, for the ``envvars = env.vars(self, scope="build")`` environment variables object 
- Then you have the reference for ``EnvVars`` in https://docs.conan.io/2/reference/tools/env/envvars.html, including the ``.get()`` method

Closing the ticket as solved, thanks for the feedback!
