### ISSUE TITLE
[question] Problem on package creation and build=missing

### ISSUE THREAD

**Issue by alararai** [conan-io/conan#16204]
### What is your question?

Hi, sorry to bother you, but I have a question regarding the different instances of a package.
I want to create a package with a set of options and store on a repo.
When the user gets this package and the options are similar, get the instance from the repo, and if not create the package locally.
Currently having problem with one of the options.

This is the package information on the .conan cache:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=193
os=Windows
[options]
RECIPE=nda
SIGNING=OFF

This is the command I use to install the "new instance":
conan install ..\  --build=missing -o:a RECIPE=nda -o:a SIGNING=ON -pr:a ..\tools\conan\profiles\Windows\Debug_MSVC.profile
and the result:
![image](https://github.com/conan-io/conan-center-index/assets/91744230/978f9cb9-6c3a-4357-a436-4eae9367efce)

It says that it has been found, I only create the "SIGNING=OFF" one

Thanks for your help

**Comment by AbrilRBS** [comment]
Hi! Thanks for your question - as this is a general Conan question, I'm transferring the question to the main Conan repository, where I think it fits better :)

**Comment by alararai** [comment]
> Hi! Thanks for your question - as this is a general Conan question, I'm transferring the question to the main Conan repository, where I think it fits better :)

Thanks and sorry :)

**Comment by memsharded** [comment]
Hi @alararai 
Thanks for your question

Some other quick feedback:

- ``-pr:a ..\tools\conan\profiles\Windows\Debug_MSVC.profile`` it sounds you can benefit the ``conan config install`` to share your profiles, so you can use just ``-pr=Debug_MSVC.profile``
- Note that with ``-pr:a ..\tools\conan\profiles\Windows\Debug_MSVC.profile`` you are applying a "Debug" profile also for your ``tool_requires``. That means that for example if you have a ``tool_requires`` to ``cmake/xxx``, that CMake executable might be running from a Debug executable, being slower. In general, the "build" profile would be a Release one, not a Debug one.
- Regarding the CMAKE_UTILS_DIR, it seems you might want to put those CMake utils into a Conan package, and you can use it better from there. That will achieve more reproducibility, easier and more traceable update of those utils, control over the binaries and ``package_id`` of the packages using the utils, etc.
- Do not use versions as ``1.00``, but ``1.0`` instead, it will work better from semver and version ranges perspective
- In general lowercase is preferred for options, not uppercase
- Please don't paste images, those are difficult to read, and we cannot copy extracts from it. Better copy and paste the output from the terminal.


Regarding your issue, it depends on the ``movidasm`` recipe, it might have some binary compatibility provision or some ``package_id`` logic. It would be necessary to see your ``movidasm`` recipe to understand what could be happening.

**Comment by alararai** [comment]
Hi @memsharded, 
Thanks for the feedback I will try to use those points now on.

Regarding movidasm recipe:
class movidasmRecipe(ConanFile):
    name = "movidasm"
    version = "1.00"
    package_type = "shared-library"

    # Optional metadata
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of movisdasm package here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "*",
    no_copy_source = True

    options = {"RECIPE": ["nda", "public"],
               "SIGNING": ["ON", "OFF"]}

    default_options = {"RECIPE": "nda",
                       "SIGNING": "OFF"}

    def source(self):
        self.run("git clone something
        self.run("git clone something else
    def layout(self):
        cmake_layout(self)

    def generate(self):
        env = Environment()
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.variables["ANALYZER"] = "ON" if self.settings.compiler == "clang" else "OFF"
        if self.options.SIGNING == "ON":
            tc.variables["SIGNING"] = "ON" if self.settings.os == "Windows" else "OFF"
        tc.variables["RECIPE"] = self.options.RECIPE
        tc.variables["STRIP_BINARIES"] = "ON" if self.settings.os == "Linux" else "OFF"

        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()
        header_folder = os.path.join(self.source_folder, "moviDasm", "moviDasmDll", "Includes")
        copy(self, "moviDasmDll.h", src=header_folder, dst=os.path.join(self.package_folder, "include"))

    def package_info(self):
        self.cpp_info.libs = ["moviDasm"]

**Comment by memsharded** [comment]
Thanks, I don't see anything there that could be causing that.
Can you please do:
```
$ conan list movidasm/1.00:*
```
And share the results?

**Comment by alararai** [comment]
C:\code\conan list movidasm/1.00:*

Remainder of file ignored
Local Cache
  movidasm
    movidasm/1.00
      revisions
        f80c1191e77e36ebb941f88cc625a5b2 (2024-05-06 09:15:40 UTC)
          packages
            0565893f7e7f2e371cdd9fb19bff036bb65b9d0e
              info
                settings
                  arch: x86_64
                  build_type: RelWithDebInfo
                  compiler: msvc
                  compiler.cppstd: 20
                  compiler.runtime: dynamic
                  compiler.runtime_type: Release
                  compiler.version: 193
                  os: Windows
                options
                  RECIPE: public
                  SIGNING: OFF
            2b67735bc1db996ce41c8b7ec8eaa416859db0df
              info
                settings
                  arch: x86_64
                  build_type: RelWithDebInfo
                  compiler: msvc
                  compiler.cppstd: 20
                  compiler.runtime: dynamic
                  compiler.runtime_type: Release
                  compiler.version: 193
                  os: Windows
                options
                  RECIPE: nda
                  SIGNING: OFF
            5fec2d70cda8a14bb38520b498f872e689f706c2
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: msvc
                  compiler.cppstd: 20
                  compiler.runtime: dynamic
                  compiler.runtime_type: Debug
                  compiler.version: 193
                  os: Windows
                options
                  RECIPE: nda
                  SIGNING: OFF
            69961cf76335d30fce9b92295d08bd7f622492fa
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: msvc
                  compiler.cppstd: 20
                  compiler.runtime: dynamic
                  compiler.runtime_type: Debug
                  compiler.version: 193
                  os: Windows
                options
                  RECIPE: public
                  SIGNING: OFF
            99baaa526202e4ae5653b1fb96a2696de9271fdc
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: clang
                  compiler.cppstd: gnu20
                  compiler.runtime: dynamic
                  compiler.runtime_type: Debug
                  compiler.runtime_version: v143
                  compiler.version: 18
                  os: Windows
                options
                  RECIPE: nda
                  SIGNING: OFF
            d392f004b4fabdf8f1a0f05e084823cad5a6b489
              info
                settings
                  arch: x86_64
                  build_type: RelWithDebInfo
                  compiler: clang
                  compiler.cppstd: gnu20
                  compiler.runtime: dynamic
                  compiler.runtime_type: Release
                  compiler.runtime_version: v143
                  compiler.version: 18
                  os: Windows
                options
                  RECIPE: nda
                  SIGNING: OFF
            e218c27e42d3f858e889af72582970ce7fb22349
              info
                settings
                  arch: x86_64
                  build_type: RelWithDebInfo
                  compiler: clang
                  compiler.cppstd: gnu20
                  compiler.runtime: dynamic
                  compiler.runtime_type: Release
                  compiler.runtime_version: v143
                  compiler.version: 18
                  os: Windows
                options
                  RECIPE: public
                  SIGNING: OFF
            ef4db9f19a19a7030020d080fa32b94d07af51a7
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: clang
                  compiler.cppstd: gnu20
                  compiler.runtime: dynamic
                  compiler.runtime_type: Debug
                  compiler.runtime_version: v143
                  compiler.version: 18
                  os: Windows
                options
                  RECIPE: public
                  SIGNING: OFF

**Comment by memsharded** [comment]
> Remainder of file ignored

What do you mean with this? Is there more output that you are trimming?

You can also print the output from the terminal formatted, use triple backticks, and you can do something like:
```
Local Cache
  zlib
    zlib/1.3.1
      revisions
        f52e03ae3d251dec704634230cd806a2 (2024-02-22 09:20:06 UTC)
          packages
            7bfde258ff4f62f75668d0896dbddedaa7480a0f
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: msvc
                  compiler.runtime: dynamic
                  compiler.runtime_type: Release
                  compiler.version: 193
                  os: Windows
                options
                  shared: False
```

Please try to paste then the full output.

In any case, I have realized what is happening.
Options are per-package. You need to specify it when doing conan install:
```
$ conan install -o *:SIGNING=ON  # not -o SIGNING=ON
```
Because ``-o SIGNING=ON`` only affects the most downstream consumer recipe, not dependencies.

It is also not recommended to always use the same options for build and host context, you might want to do ``-o`` instead of ``-o:a``.

**Comment by alararai** [comment]
ok, Thanks for the explanation. I will try and come back to you.

**Comment by alararai** [comment]
Hi again,
Yeah, that worked like a charm. Thanks!

**Comment by memsharded** [comment]
Thanks for following up, happy that it solved the question!
