### ISSUE TITLE
[question] How to Conan download binaries and find binaries

### ISSUE THREAD

**Issue by zsmj-xu** [conan-io/conan#16203]
### What is your question?

My needs are:
Download the binary file through Conan, analyze the binary, and store the analysis results in my database

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by zsmj-xu** [comment]
How can I get all binaries in the conancenter repository

**Comment by memsharded** [comment]
Hi @zsmj-xu 

> How can I get all binaries in the conancenter repository

Please don't try to do that. ConanCenter contains a huge amount of binaries, a ton of Tbs. 
That could be considered abuse of the service and result in blocking.

The recommendation for many users in production is building their own binaries in-house, see https://docs.conan.io/2/devops/using_conancenter.html and https://docs.conan.io/2/devops/devops_local_recipes_index.html.

**Comment by zsmj-xu** [comment]
I am using the download command to download the package. Can I only download the binary file? I need these binaries for training of my SCA model.

**Comment by zsmj-xu** [comment]
I am using the download command to download the package. Can I only download the binary file? I need these binaries for training of my SCA model. @memsharded

**Comment by zsmj-xu** [comment]
I will only download partial binary data

**Comment by memsharded** [comment]
I am afraid you can't, this would be against the terms of service, ConanCenter is not intended to be scanned or used for training, the service is for downloading just your dependencies for your C++ projects.

**Comment by memsharded** [comment]
Closing this ticket as resolved.
