### ISSUE TITLE
[question] "control" cmake include dir variable

### ISSUE THREAD

**Issue by diogomatos3** [conan-io/conan#16230]
### What is your question?

Hello community,

In a certain conan package, I wanted to set the include dir path only on a specific component (conan-package_component_INCLUDE_DIR) and keep the generic one (conan-package_INCLUDE_DIR) set to default "include".

To do that, I tried:
`self.cpp_info.components["component"].includedirs = [ "include", os.path.join("include", "path/to/folder/1"), os.path.join("include", "path/to/folder/2")]
`
But, I observed the these paths are then also set to the generic variable (conan-package_INCLUDE_DIR).

Is this an expected behaviour? Is there way to achieve that?

I am using conan 1.56.0 and Ubuntu 20.04.6 LTS.

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @diogomatos3 

Thanks for your question.

The way components works is that when ``components`` are defined, they fully invalidate/drop the global ``cpp_info.xxxdirs`` information. All information comes from components definition now, it is not possible to have components and at the same time have a global configuration, because having a global configuration means exactly that there are no components.

The ``the generic variable (conan-package_INCLUDE_DIR).`` becomes just the aggregation of the components. This variable represents the whole package information, not just a subset excluding the components.

**Comment by diogomatos3** [comment]
Hi @memsharded,

Thanks a lot for the quick reply and explanation. It fits completely what I have observed.
If you don't mind, one more question... how would be the proper/efficient way to have direct access to "include" folder of the package, in the consumers' cmakelists? Considering that components have different sets of includedirs.

**Comment by memsharded** [comment]
> If you don't mind, one more question... how would be the proper/efficient way to have direct access to "include" folder of the package, in the consumers' cmakelists? Considering that components have different sets of includedirs.

That is the thing, there is no ``include`` folder of the package, if you define 2 components in one package and one has ``includedirs =["myinc1"]`` and the other has ``includedirs=["myinc2"]``, the consumer cannot obtain the "include" folder of the package, it doesn't exist. Maybe I am not fully understanding the issue.

Probably there is something else there. From the consumers it shouldn't be needed to get the ``includedirs`` and used them explicitly. The ``includedirs`` are already included in the generated targets, so just ``target_link_libraries(mytarget  ... mydep::mydep)`` should be enough to automatically bring the ``includedirs`` of the dependencies and successfully find and use them.

**Comment by diogomatos3** [comment]
Ok, understood. My doubts are clarified.

You got the issue. I was just wondering if there was some way to "reach" include directly. But, like you said if there is components makes no sense to have interest on "include".

On my use case, the conan package has a folder inside "include" with some headers files which do not belong specifically to a component. Then, I guess, I shall refer it on components that depend on.

Thanks!

**Comment by memsharded** [comment]
> On my use case, the conan package has a folder inside "include" with some headers files which do not belong specifically to a component. Then, I guess, I shall refer it on components that depend on.

But you can create a component to refer to those headers, why not creating a ``"headers"`` component that define that ``includedirs``? Then you have a way to refer to it. If you want to avoid having duplicated includedirs, then you can define a component ``.requires`` to this component with headers from other components using those common headers.

**Comment by diogomatos3** [comment]
I like this suggestion: "why not creating a "headers" component that define that includedirs"
It will be my approach. Thanks a lot for the guidance!

**Comment by memsharded** [comment]
Good, thanks for the feedback!

I am closing this question as responded then, don't hesitate to re-open or create new tickets for any further question.
