### ISSUE TITLE
What's the best way to support Meson?

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#1624]
Hi there, awesome project! Really glad to finally have a working package manager for C++!

I was wondering about what would be the best way to support the [Meson build system](http://mesonbuild.com), and the maintainer mentioned in [this issue](https://github.com/mesonbuild/meson/issues/2208#issuecomment-323057822) that generating a `pkg-config` file would the best way to go (and would also support other build systems).

Since Meson doesn't let you include files like CMake with the `conanbuildinfo.cmake`, I think this is the only way to make it work.

What do you think about it?

**Comment by memsharded** [comment]
Thanks very much!

I think in Meson you can import files, like:

```
tmod = import('testmod')
tmod.do_something()
```

So it seems a conan generator for Meson could generate a file like "conanbuildinfo.meson" with ``include_directories`` and other commands, that is callable from the main script.

Conan doesn't use pkg-config for dependencies, as there are some build systems, like Msft VS (MSbuild) that won't manage them. But I think a Meson generator in conan shouldn't be difficult and work great.

**Comment by theodelrieu** [comment]
Meson is supported since 0.28

**Comment by memsharded** [comment]
For reference: http://docs.conan.io/en/latest/integrations/meson.html
