### ISSUE TITLE
[question] Why is DLL path not set in conanrunenv when creating a prebuilt binaries package?

### ISSUE THREAD

**Issue by LarrxX** [conan-io/conan#16248]
### What is your question?

Hello,
I am creating a very simple package from precompiled closed source binaries, and test_package but the test is failing because it is not finding the DLL paths.
I compared to other projects I created and it seems there is one line missing from the conanrunenv generated file: the path to the dlls is not set.

Is there anything specific to do to get that line to generate?
Here is the project I'm trying to run (I removed the binaries and the `main.cpp` file of the test for confidentiality reasons)

[my_project.zip](https://github.com/conan-io/conan/files/15307373/my_project.zip)

And here is the conanrunenv generated for this project: 
```
@echo off
chcp 65001 > nul
setlocal
echo @echo off > "%~dp0/deactivate_conanrunenv-release-x86_64.bat"
echo echo Restoring environment >> "%~dp0/deactivate_conanrunenv-release-x86_64.bat"
for %%v in () do (
    set foundenvvar=
    for /f "delims== tokens=1,2" %%a in ('set') do (
        if /I "%%a" == "%%v" (
            echo set "%%a=%%b">> "%~dp0/deactivate_conanrunenv-release-x86_64.bat"
            set foundenvvar=1
        )
    )
    if not defined foundenvvar (
        echo set %%v=>> "%~dp0/deactivate_conanrunenv-release-x86_64.bat"
    )
)
endlocal
```

As opposed to the one generated by another much more complicated but somewhat similar project:
```
@echo off
chcp 65001 > nul
setlocal
echo @echo off > "%~dp0/deactivate_conanrunenv-release-x86_64.bat"
echo echo Restoring environment >> "%~dp0/deactivate_conanrunenv-release-x86_64.bat"
for %%v in (PATH) do (
    set foundenvvar=
    for /f "delims== tokens=1,2" %%a in ('set') do (
        if /I "%%a" == "%%v" (
            echo set "%%a=%%b">> "%~dp0/deactivate_conanrunenv-release-x86_64.bat"
            set foundenvvar=1
        )
    )
    if not defined foundenvvar (
        echo set %%v=>> "%~dp0/deactivate_conanrunenv-release-x86_64.bat"
    )
)
endlocal


set "PATH=C:\conan2\p\b\mkl5c54d20a82898\p\bin;%PATH%"
```

Why doesn't my project generate the PATH variable correctly?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by LarrxX** [comment]
If I manually add this line in `package_info()`, it works as expected:
`self.runenv_info.append_path("PATH", os.path.join(self.package_folder, "bin"))`

But shouldn't that be done automatically?

**Comment by memsharded** [comment]
Hi @LarrxX 

Thanks for your question.

> self.runenv_info.append_path("PATH", os.path.join(self.package_folder, "bin"))

> But shouldn't that be done automatically?

Yes, it should be done automatically, but this might depend on the ``package_type``.
If the package hasn't defined ``option`` ``shared``, then you might want to explicitly define ``package_type = "shared-library"``, so Conan knows it is a shared library and it will append the "bin" folder to the PATH.

Please let me know if this helps.

**Comment by LarrxX** [comment]
Remember the problem I had with oneMKL? I am having it again here now ':-)

If I set `package_type = "shared-library"` and remove my  `path_append line`, I get this error:
```
CMake Error in CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target
  "CONAN_LIB::my_project_RELEASE" configuration "Release".
```

**Comment by LarrxX** [comment]
FYI I am using conan 2.2.3 if it's relevant.

**Comment by memsharded** [comment]
In the oneMKL case it was caused by a mismatch in the lib/dll names, maybe it is the same case here too?
If you can post the full ``tree`` of the package folder in the cache, it might have some hints.

**Comment by LarrxX** [comment]
it's one lib -> one dll :)

and by manually setting the runenv path, everything works as expected

**Comment by memsharded** [comment]
Maybe you can post an updated ``myproject.zip``, that bundles the .h/.lib/.dll of the precompiled binary (it can be an empty or "hello world" compiled lib for testing), that would be fantastic if I can reproduce it here.

**Comment by LarrxX** [comment]
that's going to be a bit complicated as I don't have the bandwidth for that right now, sorry

Since my patchy solution is working, it's ok for me for now

**Comment by memsharded** [comment]
I have been trying to reproduce, did a simple library, built it locally to have the .h/.lib/.dll, then tried the ``conan export-pkg`` + ``test_package`` and checked the ``conanrun`` environment, it contains the path to the ``bin`` folder containing the ``.dll`` and everything works fine.

So I guess it should be something else. 
If we can't reproduce at the moment, the best would be to close the question as solved: "the path should be there and it shouldn't be necessary to add manually to ``self.runenv_info``", and it can't be reproduced locally, things seems to be working fine.

If you manage to reproduce it please re-open and we will have a look. Many thanks!
