### ISSUE TITLE
[bug] Inconsistent output of `conan create lock`

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#16255]
### Describe the bug

[conan_override_null.zip](https://github.com/conan-io/conan/files/15312383/conan_override_null.zip)
In creating a lockfile with from a recipe with an override, I'm seeing sometimes the output is:
```
    "overrides": {
        "sqlite3/3.44.2": [
            "sqlite3/3.45.0#3a7911478ffd14e7acc694ac113449b6"
        ],
        "sqlite3/3.45.0": [
            "sqlite3/3.45.0#3a7911478ffd14e7acc694ac113449b6",
            null
        ]
    },
```
and sometimes the output is:
```
    "overrides": {
        "sqlite3/3.44.2": [
            "sqlite3/3.45.0#3a7911478ffd14e7acc694ac113449b6"
        ],
        "sqlite3/3.45.0": [
            null,
            "sqlite3/3.45.0#3a7911478ffd14e7acc694ac113449b6"
        ]
    },
```
I've also seen where it gets to:
```
        "sqlite3/3.45.0#3a7911478ffd14e7acc694ac113449b6": [
            null,
            "sqlite3/3.45.0#3a7911478ffd14e7acc694ac113449b6"
        ]
```
but i didn't see that in this reproduction.

### How to reproduce it

1. Extra the zip
2. Run test.py (it will automatically create a virtual environment and install conan)
3. Look at the output test_deps.lock
4. It will randomly switch between the 2 configurations

**Comment by rconde01** [comment]
BTW I'm considering post processing the file for consistency - but i'm not sure if these configurations have a certain semantic difference - I didn't find any documentation on the lock file itself.

**Comment by memsharded** [comment]
Hi @rconde01 !

I have been having a look at this, running the code that you provided, but I couldn't reproduce it.
I suspect that the Python version and the OS might be related. The sorting of Python ``dicts`` might differ in different platforms.

It is also possible that something has changed since then, I am trying with latest 2.7

Can you please re-check and report your platform and Python details? Many thanks!

**Comment by rconde01** [comment]
I can still reproduce:

- Windows 11
- Python 3.11.6
- Conan 2.7.1

https://github.com/user-attachments/assets/2a0c3c27-dcaf-4e49-b600-99f4a23222df

**Comment by memsharded** [comment]
Interesting, I have mostly the same setup, except exact Python version, I was using 3.10, not happening in my case...
Can you please share the full output of ``conan version`` just in case?

I'll try to replicate with exactly same Python version.

**Comment by rconde01** [comment]
I actually added to the script to call conan --version at the end of the run - it's in that video showing `2.7.1` - was there something else you needed?

**Comment by memsharded** [comment]
I meant ``conan version``, without the ``--``, for the full output, not only the version number

**Comment by rconde01** [comment]
ahh:
```
version: 2.7.1
conan_path: C:\Users\RobConde\Downloads\test\venv\Scripts\conan
python
  version: 3.11.6
  sys_version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
  sys_executable: C:\Users\RobConde\Downloads\test\venv\Scripts\python.exe
  is_frozen: False
  architecture: AMD64
system
  version: 10.0.22631
  platform: Windows-10-10.0.22631-SP0
  system: Windows
  release: 10
  cpu: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
```

**Comment by memsharded** [comment]
My setup:
```
$ conan version
version: 2.7.1
conan_path: C:\Users\memsharded\Envs\conanpip2_311\Scripts\conan
python
  version: 3.11.6
  sys_version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
  sys_executable: C:\Users\memsharded\Envs\conanpip2_311\Scripts\python.exe
  is_frozen: False
  architecture: AMD64
system
  version: 10.0.22631
  platform: Windows-10-10.0.22631-SP0
  system: Windows
  release: 10
  cpu: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
```

Good news, I have managed to reproduce, thanks for the feedback!

This sounds it could be a glitch on CPython implementation on Windows, updating to Python 3.11.9, the issue no longer reproduces.

**Comment by rconde01** [comment]
I see the same - closing the issue. Thanks!

**Comment by memsharded** [comment]
SW updates FTW!! 😄

Great that this one is solved now, happy to help!

**Comment by rconde01** [comment]
Note that for whatever reason this popped up again for me. Maybe you can just add manual sorting on the conan side?
