### ISSUE TITLE
[feature] Allow customizing CMAKE_GENERATOR_PLATFORM,  CMAKE_GENERATOR_TOOLSET and other VS options

### ISSUE THREAD

**Issue by sykhro** [conan-io/conan#16260]
### What is your suggestion?

I'm attempting to use Conan to manage packages built GDK.
GDK is the Microsoft framework for develping games for the Store and Xbox. It defines WINAPI_PARTITION_GAMES (like UWP) and a build target, Gaming.Desktop.x64. It's essentially like compiling for Windows but without a chunk of Win32.

If you are a licensed developer, you also get the build targets for Xbox. Most of this knowledge is public and vcpkg implements it: [info](https://walbourn.github.io/vcpkg-now-supports-targeting-xbox/).

To get this platform working, you can have a look at the [GDK CMake examples](https://github.com/microsoft/Xbox-GDK-Samples/blob/main/Samples/Tools/CMakeGDKExample/grdk_toolchain.cmake).

The core of the issue, that `conan_toolchain.cmake` ends up overwriting `CMAKE_GENERATOR_PLATFORM` and `CMAKE_VS_PLATFORM_NAME`, leading to building for the wrong platform.

_Note: it's also possible to bypass the VS props and write a toolchain file that's compatible with Ninja, but I would like to avoid it if possible. Due to the nature of the platform there are certain libraries that don't use CMake, so it would be good to have a VS profile working. I realize however that there also other options missing for MSBuild_

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by sykhro** [comment]
I was able to achieve it with:
```
os=Windows
arch=Gaming.Xbox.Scarlett.x64
build_type=Debug

compiler=clang
compiler.version=17
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.runtime_version=v143
```
sorry!

**Comment by memsharded** [comment]
Hi @sykhro 

Thanks for your feedback and thanks for following up.

Even if you found a way with custom ``arch`` I think there are still cases when it might be useful to further override some of the Conan toolchain behavior, check https://github.com/conan-io/conan/issues/16240 for example.

We might be exploring different ways to allow further configuration of ``CMakeToolchain``, follow that ticket if you are interested. Thanks!

**Comment by sykhro** [comment]
wow, the simulation is low on entropy - someone running into the same things just 2 days prior with another game console..
either way, I'll watch that ticket. however, for this particular usecase, I'm also interested in `MSBuild` working correctly - it's not just about `CMakeToolchain`, in the end

**Comment by memsharded** [comment]
If we are talking about ``MSBuildToolchain``, yes, that might be a separate issue, maybe you want to open a dedicated ticket for it? It is most likely that the other ticket will focus on CMake only.
