### ISSUE TITLE
[question] conan search SYCA_Casting/0.4.7@master/dev -r=artifactory  gets timeout

### ISSUE THREAD

**Issue by brosmar** [conan-io/conan#16277]
### What is your question?

I have problems when getting prebuild packages.

```
ERROR: Missing binary: SYCA_Casting/0.4.7@master/dev:8383b2cf8a42fd057a769110b72a2cfd89157958
SYCA_Casting/0.4.7@master/dev: WARN: Can't find a 'SYCA_Casting/0.4.7@master/dev' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, arch_build=x86_64, build_type=Release, compiler=gcc, compiler.cppstd=gnu11, compiler.version=11, os=Linux
- Options: fPIC=True, shared=False, SYVE_Version:fPIC=True, SYVE_Version:shared=False
- Dependencies: SYVE_Version/0.4.7@master/dev
- Requirements: SYVE_Version/0.4.7
- Package ID: 8383b2cf8a42fd057a769110b72a2cfd89157958

ERROR: Missing prebuilt package for 'SYCA_Casting/0.4.7@master/dev'
Use 'conan search SYCA_Casting/0.4.7@master/dev --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=SYCA_Casting'
```
But the  SYCA_Casting/0.4.7@master/dev:8383b2cf8a42fd057a769110b72a2cfd89157958 package is definitive there:

`https://artifactory.atus.io/artifactory/xentric-conan-dev-local/master/SYCA_Casting/0.4.7/dev/d0829f088f7ecbd2c160a0d7d4e4ce04/package/8383b2cf8a42fd057a769110b72a2cfd89157958/4f81e94ea63a436427f1a345ff12e25c/conan_package.tgz
`

When i try the hint 'Use conan search' the conan did not return.

Did not return:
```
conan search SYCA_Casting/0.4.7@master/dev -r=artifactory
{"_action": "COMMAND", "name": "search_packages", "parameters": {"outdated": false, "query": null, "remote_name": "artifactory"}, "time": 1715852324.9989898}
{"_action": "REST_API_CALL", "duration": 0.03435468673706055, "headers": {"User-Agent": "Conan/1.61.0 (Linux 4.18.0-513.24.1.el8_9.x86_64; Python 3.9.2; x86_64)", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1715852325.035617, "url": "https://artifactory.atus.io/artifactory/api/conan/xentric-conan-dev/v1/ping"}
{"_action": "EXCEPTION", "class": "ConanConnectionError", "message": "HTTPSConnectionPool(host='artifactory.atus.io', port=443): Max retries exceeded with url: /artifactory/api/conan/xentric-conan-dev/v2/conans/SYCA_Casting/0.4.7/master/dev/search (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='artifactory.atus.io', port=443): Read timed out. (read timeout=60.0)\"))\n\nUnable to connect to artifactory=https://artifactory.atus.io/artifactory/api/conan/xentric-conan-dev\n1. Make sure the remote is reachable or,\n2. Disable it by using conan remote disable,\nThen try again.", "time": 1715852505.3564236}

```

When adding --revisions I get the revisions 
 ```
conan search SYCA_Casting/0.4.7@master/dev --revisions -r=artifactory
{"_action": "COMMAND", "name": "get_recipe_revisions", "parameters": {"remote_name": "artifactory"}, "time": 1715852744.3684034}
{"_action": "COMMAND", "name": "get_remote_by_name", "parameters": {}, "time": 1715852744.371006}
{"_action": "REST_API_CALL", "duration": 0.037033796310424805, "headers": {"User-Agent": "Conan/1.61.0 (Linux 4.18.0-513.24.1.el8_9.x86_64; Python 3.9.2; x86_64)", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1715852744.4098692, "url": "https://artifactory.atus.io/artifactory/api/conan/xentric-conan-dev/v1/ping"}
{"_action": "REST_API_CALL", "duration": 0.032691001892089844, "headers": {"User-Agent": "Conan/1.61.0 (Linux 4.18.0-513.24.1.el8_9.x86_64; Python 3.9.2; x86_64)", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1715852744.443055, "url": "https://artifactory.atus.io/artifactory/api/conan/xentric-conan-dev/v2/conans/SYCA_Casting/0.4.7/master/dev/revisions"}
~
```

The real question is:
Why is the module ERROR: Missing binary: SYCA_Casting/0.4.7@master/dev:8383b2cf8a42fd057a769110b72a2cfd89157958 not found.

`https://artifactory.atus.io/artifactory/xentric-conan-dev-local/master/SYCA_Casting/0.4.7/dev/d0829f088f7ecbd2c160a0d7d4e4ce04/package/8383b2cf8a42fd057a769110b72a2cfd89157958/4f81e94ea63a436427f1a345ff12e25c/conaninfo.txt

[settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.cppstd=gnu11
    compiler.version=11
    os=Linux

[requires]
    SYVE_Version/0.4.7

[options]
    fPIC=True
    shared=False

[full_settings]
    arch=x86_64
    arch_build=x86_64
    build_type=Release
    compiler=gcc
    compiler.cppstd=gnu11
    compiler.version=11
    os=Linux

[full_requires]
    SYVE_Version/0.4.7@master/dev:800f8f565640878f5c8781b91ff373cc180819df

[full_options]
    fPIC=True
    shared=False
    SYVE_Version:fPIC=True
    SYVE_Version:shared=False

[recipe_hash]
    d0829f088f7ecbd2c160a0d7d4e4ce04

[env]

`

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @brosmar 

Thanks for your report.

> conan search SYCA_Casting/0.4.7@master/dev -r=artifactory

yes, certainly this shouldn't time out. A couple of quick questions:

- Does it happen the same for other packages different to that one? 
- Does it happen for other versions of that same package?
- Can you please report on your Artifactory version? (I understand that Conan is 1.61 from the logs)

**Comment by memsharded** [comment]
Any feedback here @brosmar?
Marking the question as staled (will be closed soon)
