### ISSUE TITLE
[question] Why does an identical revision appear as "newer than the remote one"

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#16273]
### What is your question?

When running `conan install --update`, I get messages such as:
```
b2/4.10.1: Current package revision is newer than the remote one
```

When the recipe revision is actually the same:
```
$ conan list 'b2/4.10.1#*'
Local Cache
  b2
    b2/4.10.1
      revisions
        a41eecb267963ddf518e3c177eae60e1 (2024-02-09 17:48:16 UTC)

$ conan list -r conancenter 'b2/4.10.1#*'
conancenter
  b2
    b2/4.10.1
      revisions
        12ca818ee46ada48431d97d78e0633db (2023-07-11 06:00:20 UTC)
        8dc3df1cc73ad65d86cbdfd31fdb011f (2023-07-22 06:10:05 UTC)
        1b290403d8648c79f468f5a6496f829a (2023-11-13 10:27:42 UTC)
        a41eecb267963ddf518e3c177eae60e1 (2024-02-09 17:48:16 UTC)
```

Why the confusing message?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @paulharris thanks for the report

This comes from an oversight in the output info when the timestamps match, thanks for the heads-up. I'm proposing https://github.com/conan-io/conan/pull/16275 for the next Conan release to only output this when the cache'd revision is actually newer :)

**Comment by paulharris** [comment]
Great thanks, I'll close this issue and assume it'll be fixed in the future!
