### ISSUE TITLE
[question] Visual Studio solution missing headers, but `conan build` works just fine

### ISSUE THREAD

**Issue by LouChiSoft** [conan-io/conan#16280]
### What is your question?

I have a project that depends on a conan package. My build process is as follows:
- `conan install . --build=missing`
- `cmake --preset conan-default`
then either of
- `cmake --build ./build`
- `cd build; MSBuild.exe gamma.sln`

In both cases the build system is unable to determine the location of the headers provided by the conan package. But if I run `conan build .` immediately after `conan install . --build=missing` it builds no problem. Not sure what is causing it, since IIRC the conan build command is simply a wrapper around CMake when using the CMake toolchain in conanfile.py. I've double checked the package in the conan repository and confirmed that the missing files are on disk as well, although if they weren't I would have expected `conan build .` to fail as well

```Python
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps

class gammaRecipe(ConanFile):
    name = "gamma"
    version = "0.1"
    package_type = "library"

    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/*", "include/*"

    def config_options(self):
        if self.settings.os == "Windows":
            self.options.rm_safe("fPIC")

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def layout(self):
        cmake_layout(self)

    def requirements(self):
        self.requires("amf/0.1")

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["gamma"]
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @LouChiSoft 

Thanks for your question.

I think you are missing some information:

```
cmake --build ./build
```

This is not complete for Visual Studio (multi-config generator, that doesn't necessarily default to ``Release``), you need either:
```
cmake --build ./build --config Release
# or
cmake --build --preset conan-release
```
The later is preferred if you were using presets for the configure step.


For the msbuild command line version ``cd build; MSBuild.exe gamma.sln`` you might need to add ``/p:Configuration=Release`` too there. But I also think that if you configured the project with ``cmake``, then using ``cmake --build`` is also preferred.

**Comment by LouChiSoft** [comment]
Thanks for the fast response @memsharded. This was the answer, I guess the missing files in Visual Studio is a CMake specific issue then, not a conan one.
Thanks

**Comment by memsharded** [comment]
> Thanks for the fast response @memsharded. This was the answer, I guess the missing files in Visual Studio is a CMake specific issue then, not a conan one.

It is kind of alignment in all the tools, ``conan install`` install by default ``Release`` dependencies for the ``Release`` configuration. But even CMake strongly encourage to use a ``build_type`` or configuration, it is not really mandatory, so it still kind of works even if it is not specified, but then it fails to find the dependencies because they were installed for ``Release``
