### ISSUE TITLE
[feature] Improve version-range-parsing error message

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#16288]
### What is your suggestion?

If you specify a requirement such as `expat/[>=2.6.2 < 3]`
Note the space between < and 3

The error message reads simply as:
```
ERROR: Error parsing version range "<"
```

With no hint as to which recipe it was processing, nor which requirement.

Would be nice if hints were given :)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your suggestion @paulharris 

This totally makes sense, lets add them.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/16289 merged for next Conan 2.4
