### ISSUE TITLE
[bug] Inconsistency in `conan install` `require` or `requires`

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#16286]
### Describe the bug

The documentation for `conan install` documents a `--requires` option. https://docs.conan.io/2/reference/commands/install.html

 However, `conan graph build-order` output "build_args", which is documented to be intended to be used with `conan install`, will have `--require=xyz`. They both seem to be accepted by `conan install`, but i'm not sure why they shouldn't be consistent.

**Comment by memsharded** [comment]
Thanks for reporting this @rconde01 

It is true that ``argparse`` extrapolates, and understand ``--require`` as ``--requires``, but it would be better if they match, lets fix it.
