### ISSUE TITLE
Running the 'test' method like 'conan build'

### ISSUE THREAD

**Issue by yosizelensky** [conan-io/conan#1629]
Is there a way for running the `test` method directly from the command line, like it is done for the `build` method with `conan build`?

I am asking this because i would like to use conan as my only tool for creating, building, and testing my packages instead of using it along with `cmake` (for `cmake test`) or just manually running my tests executable.

I know that `test_package` calls the `test` method of the test_package, but i don't want to have all my tests in the `test_package` like here: https://github.com/lasote/conan-gtest-example

So my wishful workflow when cloning a clean version of my library\repository is:

```cmd
> conan install
> conan build
> conan test
```

This could also be very helpful in CI scripts.

**Comment by lasote** [comment]
No, currently the test method is used only within `conan create` command (that replaces the deprecated `test_package`). And it's used to test the package, if there is no package (local build command) there is no package to test.

**Comment by yosizelensky** [comment]
Okay, but do you think it is a good idea to add this? how hard would you estimate to implement this?

If you are deprecating the `test_package` command, which replaced the `test` command, maybe we can bring back the `test` command to run the `test` method of the package?

Thanks for the quick answer!

**Comment by mschmid** [comment]
I would like to ask in a more general way: Is it possible to have conan called custom methods that are implemented in a recipe? A test()-method could be one example which just runs ctest. Another example would be to prepare the build-step by creating CMake-Files, which in some use-cases shall also be called separately by CI.

**Comment by memsharded** [comment]
``test_package`` is not being deprecated, it is not being recommended as the main way to create packages. Its main function will be to just build and run the test() method (but not build the package under test) with the command:

```bash
$ conan test_package --test-only
```

Do you mean a ``conan test`` command, different to ``conan test_package``?  So it will just run the ``test()``, without building the consumer project inside ``test_package`` folder?What would be the use case?

**Comment by memsharded** [comment]
Hi,

This has been quiet for some time, and many changes have been done since them. Summary:

- ``conan test_package`` was deprecated and removed
- ``conan create`` can run with or without test_package folder
- ``conan test`` command exists which only runs the test
- The local workflow has been largely improved.

So I think this issue can be closed, but please comment or open a new issue otherwise. Thanks!
