### ISSUE TITLE
Remote priority

### ISSUE THREAD

**Issue by ebclark2** [conan-io/conan#1630]
Remote priority does not appear to be followed.  After adding a new remote via `conan remote add NEW_REMOTE url --insert` and seeing it at the top of `conan remote list`, conan still searches conan-transit first.  A workaround appears to be to remove the conan-transit remote and re-add it.

**Comment by memsharded** [comment]
What do you mean by "conan still searches"? I guess it is not a ``conan search`` but the remote that is used to retrieve packages.

Conan stores the package remote origin once it is installed. So if you install a package from conan-transit, even if you add/insert another remote, it will keep using the conan-transit remote for that package. You can see, change and remove that information with the ``conan remote`` command and ``xxx_ref`` subcommands, check the docs: http://docs.conan.io/en/latest/reference/commands/remote.html.

The effect of removing conan-transit, is that all packages referencing that remote, lose the reference, then use the new remote reference to be installed.

**Comment by ebclark2** [comment]
Thanks for the explanation, this makes sense.
