### ISSUE TITLE
[question] Can I pass --vs-args or --ninja-args arguments to the meson tool when executing build command

### ISSUE THREAD

**Issue by NiceBlueChai** [conan-io/conan#16301]
### What is your question?

I want to execute meson compile -C. -j[N_JOBS] [TARGET] --vs-args=xx,xx when I run meson.build()

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @NiceBlueChai 

Thanks for your question.

What specific arguments you want to pass? The recommendation would be trying to not have to pass anything in the command line of ``meson``, but define them in the Meson toolchain files (via ``MesonToolchain``)

**Comment by memsharded** [comment]
Any feedback here @NiceBlueChai?

Things like ``-n[JOBS]`` are already automatically added by Conan, and it is possible that the other are better managed by toolchains.
