### ISSUE TITLE
[bug] Github actions fail when set `tools.system.package_manager:mode`

### ISSUE THREAD

**Issue by nagayev** [conan-io/conan#16306]
### Describe the bug

When I run conan on Ubuntu 22.04/24.04 `conan install . -c tools.system.package_manager:mode=install --build=missing -of build` i'm getting the error message:
```
dpkg-query: no packages found matching libva-dev
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
ERROR: vaapi/system: Error in system_requirements() method, line 38
	apt.install(["libva-dev"], update=True, check=True)
	ConanException: Command 'apt-get update' failed
```

### How to reproduce it

Create conanfile which depends on opencv and run it from github actions

**Comment by memsharded** [comment]
Hi @nagayev 

Thanks for your question.

This doesn't seem a bug, but the error message seems to indicate that you don't have enough permissions, and ``sudo`` might be required:

> E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)


So try adding ``-c tools.system.package_manager:sudo=True`` to activate the ``sudo apt-get install``

**Comment by nagayev** [comment]
@memsharded Thank you, the problem is gone!
