### ISSUE TITLE
copy resources from same directory as conanfile.txt

### ISSUE THREAD

**Issue by vadixidav** [conan-io/conan#1631]
Do I need to create a package with a `conanfile.py` to package additional resources required when calling `conan install` on a `conanfile.txt` or is there a way to copy things from the same directory as the `conanfile.txt`?

**Comment by memsharded** [comment]
Hi @vadixidav 

I would need more information, it is not clear to me what is your question. To create packages it is always required a ``conanfile.py``, ``conanfile.txt``, is exclusively for consuming existing packages. Though you can use a ``conanfile.py`` to consume existing packages, and also add some logic, as the ``build()`` method not supported by the text version.

If you are asking about the ``imports`` functionality, it is supported both in conanfile.txt and conanfile.py (as the ``imports()`` method)

Please clarify your question. Thanks!

**Comment by vadixidav** [comment]
@memsharded You answered my question by stating that "`conanfile.txt` is exclusively for consuming existing packages". Thanks.
