### ISSUE TITLE
Split tools.py to improve the development

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1632]
Hi!

I ran pylint over tools.py, here are the results:

```
+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |1      |NC         |NC         |100.00      |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |9      |NC         |NC         |22.22       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|method   |32     |NC         |NC         |31.25       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|function |28     |NC         |NC         |39.29       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
```

There are many classes and functions in this file, I see almost a monolithic file. I'm afraid that this number can increase after new contributions.  
My intention is move some classes and functions to others files (as done for modules), and use only reference in tools, to avoid breaking things.

Regards.

**Comment by memsharded** [comment]
Agree. I would suggest to start moving all the SystemPackageTools specific instances (choco, pkgutil, etc) to their own module or modules.
