### ISSUE TITLE
[feature] Add a --skip-generator option

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#16325]
### What is your suggestion?

Might not be the right solution but currently for `conan install` when i really just want to build, i need to create a temporary directory and set the `--output-folder` to that directory. This would address that.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I am not sure what you mean @rconde01 

I don't need ``--output-folder``, I practically never use it, just ``conan install`` + building with ``cmake`` or other build system. If the build needs the dependencies, then the generators cannot be skipped anyway. What am I missing?

**Comment by rconde01** [comment]
If you are just building, this will dump a bunch of files in your current directory which you don’t need. There’s an easy workaround with output folder…just wanted to share the idea.

**Comment by memsharded** [comment]
> If you are just building, this will dump a bunch of files in your current directory which you don’t need. There’s an easy workaround with output folder…just wanted to share the idea.

You probably mean the environment files, isn't it? In that case this could be a duplicate of https://github.com/conan-io/conan/issues/13751

**Comment by rconde01** [comment]
So, in the past i would build using my deps file so all those files would be generated as well. But with `--requires` indeed it's just the environment files. So now it's a dupe.
