### ISSUE TITLE
[question] How to modify global.conf

### ISSUE THREAD

**Issue by andrey-zherikov** [conan-io/conan#16336]
### What is your question?

I'm trying to setup some workflow where I need to modify existing `global.conf`. What is a recommended way to do that?
conan 1 had `conan config set` but there is no such option in conan 2

A bit of context: my workflow does `conan config install --type git ...` as a first step so I already have `global.conf` which I need to modify - actually I'm need to set/change `core.net.http:*` properties there.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @andrey-zherikov 

The idea is that it shouldn't be necessary to hot-modify the ``global.conf``, but the recommendation would be to identify the logic that need those changes and represent them explicitly in the ``global.conf`` using the jinja2 templates. You can use there any input condition, like environment variables, or ``os`` or ``platform`` checks. You can do things like ``core.net.http:proxies = {{os.getenv("myproxies")}}`` or something like that.

**Comment by andrey-zherikov** [comment]
What I'm doing is I'm trying to automate (to the certain degree) bringing new versions of third-party packages (like `cmake`) to our artifactory. The idea is to take the recipe from conan-center (which re-package pre-built binaries) and run it on our side. This recipe creates a package in local cache, then this package is gonna be uploaded to our artifactory.

The main issue with this workflow is that connection to internet requires proxy with our own CA cert but connection to artifactory requires no proxy. I can specify proxy through `https_proxy` environment variable to specific conan command which requires it but I'm not able to provide CA cert (or I didn't find the way) - conans' `-c` option doesn't allow changing `core.*` settings (I tried `-c core.net.http:cacert_path=...`).

So I see the only way is to modify `global.conf` locally (our shared `global.conf` has no proxies on purpose to avoid any random recipe to go to internet and I prefer not to change it globally).

**Comment by memsharded** [comment]
I see, probably what you are looking for is:
```
 -cc CORE_CONF, --core-conf CORE_CONF
                        Global configuration for Conan
```
This is different from the ``-c`` which is the ``profile`` configuration. The ``-cc`` allows changing the ``global.conf`` from the command line.

**Comment by andrey-zherikov** [comment]
What is CORE_CONF? How to use it? I did a quick search on conan docs and didn't find any explanation

**Comment by memsharded** [comment]
From https://docs.conan.io/2/reference/config_files/global_conf.html


- ``core.*``: aimed to configure values of Conan core behavior (download retries, package ID modes, etc.). Only definable in ``global.conf`` file.

- ``tools.*``: aimed to configure values of Conan tools (toolchains, build helpers, etc.) used in your recipes. Definable in both ``global.conf`` and [profiles](https://docs.conan.io/2/reference/config_files/profiles.html#reference-config-files-profiles).

**Comment by andrey-zherikov** [comment]
That is clear. My question was about `-cc CORE_CONF` - how to use it? Does it accept the same strings  as `-c`? Does it accept path to custom `global.conf`? How does it work with original `global.conf` from CONAN_HOME?

Compare, for example, these help screens - the second one is very clear:

```
-cc CORE_CONF, --core-conf CORE_CONF
                        Global configuration for Conan
```

```
-c CONF, --conf CONF  Apply the specified conf. By default, or if specifying
                        -c:h (--conf:host), it applies to the host context.
                        Use -c:b (--conf:build) to specify the build context,
                        or -c:a (--conf:all) to specify both contexts at once.
                        Example: -c tools.cmake.cmaketoolchain:generator=Xcode
```

**Comment by memsharded** [comment]
It would be used the same way as "profile" ``tools.*`` conf, so something like the 
``Example: -c tools.cmake.cmaketoolchain:generator=Xcode``, but for ``core.*`` configuration:

```
conan ... -cc core.download:parallel=8
```

I understand now better your question, probably we want to extend the cli help to include an example.

**Comment by andrey-zherikov** [comment]
@memsharded thank you for clarifications
Just confirmed that using `-cc` twice (once for proxy and once for CA cert) works perfectly.

**Comment by memsharded** [comment]
> Just confirmed that using -cc twice (once for proxy and once for CA cert) works perfectly.

Nice, thanks for the feedback!

I'll add some docstrings to improve this and close this ticket.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/16347 for next 2.4
