### ISSUE TITLE
Pass compilation flags for all requirements through conan install 

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#1633]
One of the problems that I always have with C++ libraries is that if I want to test a new flag I have to modify the CMake and recompile all libraries which is really time consuming. With Conan the recompilation part is super easy because we have the `--build` flag that we can use to always rebuild libraries. But I still have to modify all my CMake files and add the new compiler flag. If you just have a few libraries this won't be a big deal but I am using 30+ Conan libraries in my projects and modifying every single one of them takes a lot of time and it doesn't let me test different combination of flags easily. It would be really nice if there was a new Conan flag that would rebuild all requirements with the new compilation flag.

Let's say I am testing a performance issue and want to test the `-ffast-math` flag. In my main project I am installing my dependencies with `conan install --build=with-compile-flags --compile-flags=-ffast-math`, where `compile-flags` is the new Conan flag that will automatically pass the specified compilation flags, the flags could be comma separated, to the compiler and Conan would re-build all libraries using this new flag. This would make testing new flags really easy.

**Comment by memsharded** [comment]
The problem with such an approach is that cannot be used to know whether you want to create different binaries for different compile flags or not.

Using the conan "model", that is using settings or options, you can model a certain build, which can use a certain set of flags, and that will generate, store and retrieve the correct binary for those flags. If there is not model for the flags.

One very powerful feature of conan is that it very agnostic about the build. It doesn't know how to process compiler flags, just manage settings, env-vars, propagate generic info about packages (as include paths). Some helpers, like the ``CMake`` one, might provide some local automation for some build systems, but that is not in the conan core. With your proposed approach, conan would need to hardcode how to pass those compile flags to specific build-systems, and won't be extensible for not-conan-managed build systems.

If you want an easy way to inject arbitrary flags to your build, it might be very easy. If you are using Makefiles, you can directly define the flags in your profile as environment variables or in the command line. If you are using CMake, you can just inject some ``cmake.definitions["SOME_VAR"] = os.getenv("SOME_ENV_VAR", "")`` to your cmake build, then make your CMakeLists.txt to use them as you want, and then define the values of SOME_ENV_VAR in the profile or command line.

**Comment by lasote** [comment]
Maybe you could use the environment variable `CONAN_CMAKE_TOOLCHAIN_FILE to point to a custom *.cmake file introducing the new flags. It will set in CMake the variable `CMAKE_TOOLCHAIN_FILE`:
 
> Absolute or relative path to a cmake script which sets up all the toolchain related variables mentioned above

**Comment by AliAskari** [comment]
@memsharded Your reply makes a lot of sense and the solution to my problem is really simple. Thanks!

**Comment by memsharded** [comment]
Good! Then I think this issue can be closed, please reopen or comment if necessary any further help

**Comment by liarokapisv** [comment]
Hello, has there been any progress towards addressing this issue? It would be very useful to be able to somehow pass compilation flags not accounted by the recipe and also having them affect the resulting package hash.

Of course this leads to a discussion of whether the library author should be the sole person responsible for defining ABI compatibility or if consumers may also have a word in it in the case of not accounted for flags.

I think that the biggest issue here is that this basically requires a mechanism for a user to extend the settings of a given recipe. Such a solution should probably also require the full scripting capabilities of a conanfile.py and may be recipe-speficic or user-specific perhaps being treated as the settings.yml file. 

In any case I think this is something worth researching further. Perhaps what's needed is a convenient way to patch recipes instead.
