### ISSUE TITLE
[feature] Adding support to exclude pattern when removing files with Conan tools

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#16343]
### What is your suggestion?

Greetings!

Following the logic behind of [conan.tools.files.copy](https://docs.conan.io/2/reference/tools/files/basic.html#conan-tools-files-copy), users can exclude an specific pattern of file, avoid extra logic in the recipe to copy or not files.

The same could be added to [conan.tools.files.rm](https://docs.conan.io/2/reference/tools/files/basic.html#conan-tools-files-rm) too.

The scenario is when you have mixed files in the same folder, but only want to remove part of them. Real example, exclude Tools installed in bindir, but keep .dll installed at same place.

Currently we have the Geographiclib in ConanCenterIndex under to this specific case, we need to exclude tools after installing (there is an option for tools, and upstream recommends customizing the install, not the building step), but preserving .dll files when having it.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Sure, if this helps recipes, I think this can be added.
