### ISSUE TITLE
[question] Inject toolchain.cmake from RTOS library package via user_toolchain

### ISSUE THREAD

**Issue by sastel** [conan-io/conan#16340]
# Background
Using Conan 2.0.14.

I'm working on packaging a set of libs, headers, and scripts, from the NuttX RTOS. The way NuttX is designed, if you `make export` it as a library for use in another build system, you get cmake toolchain files, archives, and headers for the RTOS, drivers, libcxx, and built-in applications. The export is configured for a particular board. I have simply used `conan source .` to get the `nuttx-export-x.y.z.tar.gz` in my consuming packages, but I'd like to take it a step further and also have a conan recipe for NuttX (aka `nuttxpkg`). This will allow me to control all of the dependencies (including the compiler package which everything is built with) from one profile.

# Problem
The part I'm stuck on is how to correctly inject the `nuttx-export-x.y.z/scripts/toolchain.cmake` file into `conan_toolchain.cmake`. 

I saw in the [documentation](https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#using-a-custom-toolchain-file) that if I use `nuttxpkg` as a `[tool_requires]` in the consuming packages, and set the following snippet in my `nuttxpkg` recipe, then consuming packages will automatically inject the `toolchain.cmake` file. Since the NuttX export `toolchain.cmake` file sets all of the right cmake variables, this also causes my libs and apps to include the NuttX headers and link against the NuttX libs. It worked! At this point I thought I had solved the problem and was busy congratulating myself.
``` python
    def package_info(self):
        # Later packages get access to the NuttX export not by find_package() in CMake,
        # but through the conan_toolchain.cmake file which includes the toolchain.cmake
        # from NuttX. This means that all builds which mark this package as a
        # tool_requires will include the NuttX headers and link against the NuttX libs.
        toolchain = os.path.join(self.package_folder, "nuttx-export-12.5.0/scripts/toolchain.cmake")
        self.conf_info.append("tools.cmake.cmaketoolchain:user_toolchain", toolchain)
        # TODO can I do this ^ for regular libraries?
```
But wait! There's a problem with this. I was hoping to set options in the profile to select which board and kconfig I was building NuttX for as per the following snippet.  
```
[options]
nuttxpkg/*:HOST_CONFIG=myboard-myconfig
```
This worked fine when building `nuttxpkg` with the profile, but when building the packages which consumed `nuttxpkg` via `tool_requires`, I noticed that Conan was ignoring the `HOST_CONFIG` option when computing the `package_id`. This and this comment from @memsharded ["We are aware that this won't work this way, and it is by design, for tool_requires."](https://github.com/conan-io/conan/issues/14280#issuecomment-1633236498) implies that I shouldn't be using `tool_requires`. But if I use `requires`, then the `toolchain.cmake` file isn't automatically injected.

This seems to be a weird case because of how NuttX is an RTOS and provides both build time and run time dependencies.

# Question
How do I correctly add a dependency on `nuttxpkg` such that the `toolchain.cmake` is injected in consuming packages, and so that Conan also respects the options set in the profile for `nuttxpkg`?

Thanks for reading through this, and thanks also for making such a fantastic package manager!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sastel 

Thanks for your question.

> Using Conan 2.0.14.

Please note that only the latest patch of each minor is supported as per https://docs.conan.io/2/introduction.html#stable, so please update at least to 2.0.17 (latest 2.3.1 would be recommended)


A quick question, in which profile are you adding ``nuttxpkg/*:HOST_CONFIG=myboard-myconfig``? Maybe the issue is that you are defining it in the "host" profile? If ``nuttxpkg`` is a ``tool_requires``, the options to configure it should be in the "build" profile, or in command line with ``-o:b/--options:build ...``.

**Comment by sastel** [comment]
Hi @memsharded. I upgraded to the latest version of Conan - thanks for the reminder and for your prompt response.

Adding `-o:b nuttxpkg/*:HOST_CONFIG=myboard-myconfig` worked. So much more simple than I expected!

Do you anticipate any problems with this approach since NuttX is providing both cmake files and static libraries? The cmake files, static libraries and headers provided may change based on the `myboard-myconfig` setting in nuttxpkg.

**Comment by memsharded** [comment]
> Adding -o:b nuttxpkg/*:HOST_CONFIG=myboard-myconfig worked. So much more simple than I expected!

Excellent! Happy to hear that this is what you needed 🙂 

> Do you anticipate any problems with this approach since NuttX is providing both cmake files and static libraries? The cmake files, static libraries and headers provided may change based on the myboard-myconfig setting in nuttxpkg.

It depends. The issue with ``tool_requires`` and the build context is that it is intended mostly for tools executables, like ``cmake`` that run in the "build" machine. But when we are talking about libraries to link, they must match the "host" context and the "host" profile, so they must use regular ``requires``. The exception to this case is some toolchain-like packages that contain libraries for the "host" context for "tool-require" packages. This might need the ``settings_target`` definition to correctly match the "host" environment, so you need to make sure that the libraries in the "build" context package match the "host" context. Is this what you are using to align which libraries are provided to consumers?

**Comment by sastel** [comment]
No I haven't been using `settings_target`, instead I've been using my custom option `HOST_CONFIG` to differentiate the `package_id` for `nuttxpkg`:

```sh
$ conan list nuttxpkg/0.0:*
Local Cache
  nuttxpkg
    nuttxpkg/0.0
      revisions
        bc9910abe47ac2c85cce697ba12c0327 (2024-05-27 14:16:19 UTC)
          packages
            308d1cdf4fcfcd8c2093f7465e91493dc4c7ad61
              info
                settings
                  build_type: Release
                options
                  HOST_CONFIG: myboard-configA
            60f3fd47b8e8973fb438d114f67ad1a973ff039a
              info
                settings
                  build_type: Release
                options
                  HOST_CONFIG: myboard-configB
```

And this is my simple `nuttxpkg` recipe:
```python
import os
from conan import ConanFile
from conan.tools.scm import Git
from conan.tools.cmake import cmake_layout
from conan.tools.files import (unzip, chdir)

class NuttxPkgRecipe(ConanFile):
    name = "nuttxpkg"
    package_type = "static-library"
    description = "NuttX Package"
    settings = "build_type"
    version = "0.0"

    options = {"HOST_CONFIG":[None, "myboard-configA", "myboard-configB"]}
    default_options = {"HOST_CONFIG":None}

    def layout(self):
        # Not using cmake, but this keeps the conan generated files tidy
        cmake_layout(self, src_folder="nuttxspace", build_folder="build")

    def source(self):
        appsgit = Git(self)
        appsgit.clone(url="https://github.com/apache/nuttx-apps.git", target="./apps")
        appsgit.folder = "apps" # cd apps
        appsgit.checkout(commit="nuttx-12.5.0")

        nuttxgit = Git(self)
        nuttxgit.clone(url="https://github.com/apache/nuttx.git", target="./nuttx")
        nuttxgit.folder = "nuttx" # cd nuttx
        nuttxgit.checkout(commit="nuttx-12.5.0")

    def build(self):
        with chdir(self, self.source_folder + "/nuttx"):
            self.run('make distclean')
            match (self.options.HOST_CONFIG):
                case "myboard-configA":
                    self.run('./tools/configure.sh ../../boards/myboard/configs/A')
                case "myboard-configB":
                    self.run('./tools/configure.sh ../../boards/myboard/configs/B')
                case _:
                    raise Exception(f"HOST_CONFIG '{self.options.HOST_CONFIG}' not supported!")
            self.run('make export')

    def package(self):
        unzip(self, self.source_folder+"/nuttx/nuttx-export-12.5.0.tar.gz", self.package_folder)

    def package_info(self):
        # Later packages get access to the NuttX export not by find_package() in CMake,
        # but through the conan_toolchain.cmake file which includes the toolchain.cmake
        # from NuttX. This means that all builds which mark this package as a
        # tool_requires will include the NuttX headers and link against the NuttX libs.
        toolchain = os.path.join(self.package_folder, "nuttx-export-12.5.0/scripts/toolchain.cmake")
        self.conf_info.append("tools.cmake.cmaketoolchain:user_toolchain", toolchain)
```
My libraries and applications are being built with the same build profile as I use to build `nuttxpkg`.
```sh
conan build . -pr:h=../profiles/myboard-configA -o:b nuttxpkg/*:HOST_CONFIG=myboard-configA
```

The profile specifies a compiler package for my GCC compiler/linker.

Is this incorrect, and should I be using `settings_target` instead?

**Comment by memsharded** [comment]
I see.

I'd say that yes, you might benefit of managing your board configuration as settings. Is it correct to assume that such settings are also relevant for the final "host" package binaries that are built, because if they are built with a different toolchain settings, they will get different binaries?

In that case the approach could be:
- Add ``board`` custom settings to your ``settings_user.yml``
  - Depending on the needs, you might want to use it as a first-level setting or as a subsetting or other, like the "baremetal" ``os`` setting.
- In the recipes: You can add to regular packages ``settings = "os", .... , "board" if it is first level. If it is nested level setting to ``os`` it will be automatic, you might need to remove it with ``self.settings.rm_safe("os.board")`` or something like that in the recipes.
- Define it in ``[settings]`` in this case of the "host" profile (a bit more intuitive than adding the options in the build profile)
- The ``nuttxpkg`` special toolchain package can use the ``self.settings_target`` to access the right value to do what it needs.

This example might help to illustrate about it: https://docs.conan.io/2/examples/cross_build/toolchain_packages.html

**Comment by sastel** [comment]
Yes the `HOST_CONFIG` currently drives the config file that NuttX uses to build. So that dictates the C++ library used, which drivers are present, whether or not networking utilities are present, etc. In other words, the final host package binary changes significantly based on the config that NuttX is built with.

Thank you, I will give this a try!

**Comment by sastel** [comment]
This works well. Now I have settings_user.yml which has this settings snippet:
```yml
os:
    NuttX:
        version: ["12.5"]
        board_config: [myboard-myconfig]
```
This is a section of my host profile:
```yml
[settings]
...
os=NuttX
os.board_config=myboard-myconfig
```
The recipe for `nuttxpkg` shared above has been modified in the `build` method and had `package_id` added following the cross-build toolchain packages example.
```diff
     def build(self):
         with chdir(self, self.source_folder + "/nuttx"):
             self.run('make distclean')
-            match (self.options.HOST_CONFIG):
+            match (self.settings_target.os.board_config):
...
+    def package_id(self):
+        # Assign settings_target to the package ID to differentiate binaries by target platform.
+        self.info.settings_target = self.settings_target
```
I built `nuttxpkg` with this command:
```sh
conan build . -pr:h=../profiles/myboard-myconfig --build-require
```
And the other packages which depend on `nuttxpkg` with this:
```sh
conan build . -pr:h=../profiles/myboard-myconfig
```
Now Conan is tracking settings_target:
```sh
$ conan list nuttxpkg/0.0:*
Local Cache
  nuttxpkg
    nuttxpkg/0.0
      revisions
        16a6c8ade7451432dda267d8a251de89 (2024-05-27 20:42:42 UTC)
          packages
            5b25a1d6b40587c2bd14118b191db5bde75e52a6
              info
                settings
                  build_type: Release
                settings_target
                  ...
                  os: NuttX
                  os.board_config: myboard-myconfig
```
I have some more improvements to make as I learn more about Conan, but this is exactly what I was hoping was possible with the tool!

**Comment by memsharded** [comment]
This looks good, great job! 🙂 

Thanks for the detailed feedback about the solution.

If things are working good, and you don't have any immediate further question, you can close the ticket as responded. You can always later re-open or create a new ticket for any further question, issue or discussion.

**Comment by sastel** [comment]
@memsharded thanks for your clear answers and timely support. I will close this for now and reopen if need be.
