### ISSUE TITLE
[bug] SSL error when trying to create package with docker remote runner

### ISSUE THREAD

**Issue by bkarasm** [conan-io/conan#16348]
### Describe the bug

Host OS: Macos
Target OS (docker): ubuntu 20.04
Conan: 2.3.2 on both

I'm on a corporate network behind Zscaler and I'm experimenting with remote runners feature. My host machine is Macos with Conan 2.3.2 and I'm trying to create libzen/0.4.41 (recipe is copied without modification from conan center) package for ubuntu 20.04. I have my Zscaler certificates copied to docker image and when I manually build and run docker container I'm able to create libzen package inside it. However, if I'm trying to do that with remote runners feature with exactly the same docker image I get an error when Conan tries to download libzen sources:

`libzen/0.4.41: WARN: network: Error downloading file https://mediaarea.net/download/source/libzen/0.4.41/libzen_0.4.41.tar.bz2: 'HTTPSConnectionPool(host='mediaarea.net', port=443): Max retries exceeded with url: /download/source/libzen/0.4.41/libzen_0.4.41.tar.bz2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'`

Command:
`conan create . --version 0.4.41 --profile:build gcc-9_4 --profile:host gcc-9_4`

Profile (gcc-9_4):
```
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++
compiler.version=9.4
os=Linux

[runner]
type=docker
configfile=<path>/<to>/configfile-gcc-9_4
```

Configfile:
```
image: gcc-9_4
build:
    dockerfile: <path>/<to>/dockerfile-gcc-9_4
run:
    name: gcc-9_4
```

Dockerfile:
```
FROM ubuntu:20.04

# Copy and apply Zscaler certificates
COPY <certificate>.crt /usr/local/share/ca-certificates/

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        python3 \
        python3-pip \
        python3-venv \
    && rm -rf /var/lib/apt/lists/*
RUN pip install conan

ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

RUN conan profile detect --force
```

**Comment by AbrilRBS** [comment]
> I have my Zscaler certificates copied to docker image 

Hi @bkarasm thanks a lot for taking the time to report this issue.

While we look into seeing if the docker feature itself can be helpful (Pinging @davidsanfal), you can try to run with 
`-c="libzen/*:tools.files.download:verify=False"` to solve the issue for the moment.

Note that it's a security risk as-is, and the proper solution would come from fixing the cert issues, either from your IT team allowing it, or the root CA from docker being aware of this

**Comment by bkarasm** [comment]
After cleaning up the local cache of Docker images and containers and running conan create again, the issue did not reoccur. It seems that I need to learn a thing or two about how Docker works. Anyways, I appreciate your help, @RubenRBS. The workaround also works.
