### ISSUE TITLE
How to use shared libraries that are not linked?

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#1635]
I am trying to use a shared library package without linking it but I am having a hard time. Creating the shared library package itself is very straightforward.

In my main project I am not using the headers of this shared library, I just use `dlopen/LoadLibrary ` to load the symbols at runtime. This means this package is not really a [build requirement](http://conanio.readthedocs.io/en/latest/mastering/build_requires.html#build-requires) or a build dependency; it's rather a runtime dependency because my main application will be useless at runtime without these shared libraries. It might be similar to [system_requirements](http://conanio.readthedocs.io/en/latest/reference/conanfile/methods.html?highlight=shared%20library#system-requirements), but it is not a system package really. 

I have searched the documentation but I cannot find this use case. How do you suggest I should go about using this package?

**Comment by memsharded** [comment]
I think the most common approach for this use case, if you really care about not using the headers (in most cases, they will be retrieved, but the impact on download/install performance is low), would be to re-package. So you can create a "runtime" package, that will "imports" the shared library, and copy it. I think you can use "build_requires", so that runtime package doesn't retrieve the dependents packages if existing. Writing an example for the docs was in my to-do list, but very low priority compared with other issues.

**Comment by AliAskari** [comment]
Just to clear things up a bit. The shared library that I am interested in is already packaged as a Conan package. The main difference between this dependency and other dependencies is that I don't want the compiler to know anything about the path to this library and its header files. 

If I add the this library in the `requires` section of my conanfile.py, the compiler is actually trying to link with it. Also, if I try to use it as "build_requires", the same thing happens, the compiler tries to link with it but that's exactly what I don't want. I don't want the compiler know anything about this library. I just want to declare it as a "runtime_requirement" and then ask Conan to somehow copy the library to a specific path using the `imports` method.

Your answer makes me really confused, you are suggesting me to add this package under the "build_requires" section but as I have mentioned, if I add it there the compiler actually tries to find it and link with it; and that's not what I want. The compiler doesn't have to know anything about it.

Yes, this method might work because the linker doesn't even try to search for symbols in this library because I am not using any of the symbols from the library at compile time, so nothing weird happens and everything goes smoothly. However, the compiler should not have to know about this library at all.

**Comment by lasote** [comment]
> I don't want the compiler to know anything about the path to this library and its header files.

In your library package clear the `self.cpp_info.libs` and `libdirs`. 

```
def package_info(self):
      self.cpp_info.libs = []
      self.cpp_info.libdirs = []
      self.cpp_info.includedirs = []
```

**Comment by AliAskari** [comment]
@lasote That's exactly what I wanted. Thank you!

**Comment by memsharded** [comment]
Great, then this issue can be closed. Thanks!
