### ISSUE TITLE
[question] Pulling Conan 2x binaries with Conan 1x 

### ISSUE THREAD

**Issue by faizalatcirclecvi** [conan-io/conan#16369]
### What is your question?

Looks like the package_id calculation is different from Conan 1x and Conan 2x or perhaps the default mode is different.

I see that with conan-center, I am able to pull Conan 2x binaries with Conan 1x. However, when I try this with our own local repo (using Artifactory instance), I can only retrieve Conan binaries with Conan 2x tools. Conan 1x tools cannot see the binaries due to package_id calculation. Is there a trick conan-center is using?

Background: We are migrating to Conan 2x and wanted to stay with Conan 1x tools until all our recipe have been migrated. So it would be nice if Conan 1x tools could pull the Conan 2x binaries.

**Comment by AbrilRBS** [comment]
Hi! Thanks a lot for your question.

> I see that with conan-center, I am able to pull Conan 2x binaries with Conan 1x [...] . Is there a trick conan-center is using?

What you're seeing here is the result of Conan Center building for both Conan 1 and Conan 2 for the time being, which results in binaries for recipes being available in both versions. Note that Conan 2 is not able to pull Conan 1 binaries in any way

**Comment by faizalatcirclecvi** [comment]
Thanks, that's what I suspected. However, when I try to do the same with our local repo, once I publish Conan 2x binaries for the same version, the Conan 1x is not able to see the binaries from 1x. We are using Artifactory CE 7.55.13 as our Conan repo.

I will repeat the steps to confirm that I cannot see the 1x binaries (using Conan 1) once I publish the 2x binaries (same version)

**Comment by AbrilRBS** [comment]
(Moving this to the main Conan repository where it fits better as a question)

**Comment by memsharded** [comment]
Hi @faizalatcirclecvi 

Most likely you might be having issues with the recipe revision. The recipe revision for both Conan 1 and 2 must be the same, then there will be different binaries with different ``package_id`` for Conan 1 and for Conan 2 hanging below the same recipe revision (you cannot see them both with the Conan client, as Conan 1 only see binaries from Conan 1 and Conan 2 only sees binaries from Conan2, but you might see both in the server UI).

If the recipe revision is not the same, then creating packages with Conan 1 and 2 alternatively will overwrite each other and only the latest revision binaries will be there for either 1 or 2, but not both versions. 

Can you please make sure and report about the recipe revisions? It is perfectly possible to use the same recipe and generate the same recipe revision, we are doing that in ConanCenter.

**Comment by faizalatcirclecvi** [comment]
Okay,  makes sense. That is what is probably happening with recipe revision mismatch. Thanks for all the help.

**Comment by memsharded** [comment]
> Okay, makes sense. That is what is probably happening with recipe revision mismatch. Thanks for all the help.


No prob, happy to help.
I am keeping the ticket open, until you have the chance to verify it and let us know. Thanks!

**Comment by faizalatcirclecvi** [comment]
Yes, confirmed it works as long as recipe revision has not changed. I able to pull the same version reference using both Conan 1 and Conan 2 with the respective tools.

**Comment by memsharded** [comment]
Nice, thanks very much for the feedback.

I think we can close the ticket then, please don't hesitate to open new tickets for any further question.
