### ISSUE TITLE
[bug] conan install fails to grab artifactory config.zip

### ISSUE THREAD

**Issue by michxymi** [conan-io/conan#16371]
### Describe the bug

Using conan client version 2.3.1, I'm unable to grab a config.zip file from our internal artifactory instance. The command I use is `conan config install https://our.artifactory.instance/artifactory/Conan-V2/configs/config-test.zip --verify-ssl=False --type url`

The error I'm getting is:
`ERROR: Failed conan config install: Error while installing config from https://our.artifactory.instance/artifactory/Conan-V2/configs/config-test.zip
Not found: https://our.artifactory.instance/artifactory/Conan-V2/configs/config-test.zip`

Which is wrong because the file exists and if I actually click the link I can download it. I have also used `curl https://our.artifactory.instance/artifactory/Conan-V2/configs/config-test.zip -o config.zip` which is able to grab the file.

### How to reproduce it

We use the following in CI to bundle a folder containing the conan config and upload it to artifactory.

```
python -c "import shutil; shutil.make_archive('config', format='zip', root_dir='./config/')"
```
```

 "ZIPSHA1=$(shasum -a 1 config.zip | cut -d' ' -f1)"
  echo $ZIPSHA
  if [[ -z "${UPLOAD_USER}" ]]; then echo "UPLOAD_USER not set"; exit 1; fi
  'curl -LfsS -u "${UPLOAD_USER}" -T config.zip -H "X-Checksum-Sha1: $ZIPSHA1" "${CONAN_V2_ARTIFACTORY}/config-test.zip"'

```

**Comment by memsharded** [comment]
Hi @michxymi 

Some quick questions:

- Does the file has any access or permissions? Or is it available for anonymous access? 
- The ``curl`` command that you are using is exactly like that or it has more arguments? If there are more arguments, can you please share the full ``curl`` command?
- As you are packaging it with ``python`` can you also download it with Python ``requests``? It should be straightforward, something like:
```python
import requests

url = 'your-url'
r = requests.get(url)
open('config-test.zip', 'wb').write(r.content)
```

**Comment by michxymi** [comment]
Hey @memsharded , thanks for your prompt reply. I'll give this a go. I've also updated the full curl command we use to upload the zipped archive.

**Comment by memsharded** [comment]
> Hey @memsharded , thanks for your prompt reply. I'll give this a go. I've also updated the full curl command we use to upload the zipped archive.

Does the UPLOAD_USER includes a token/password? Or is it possible to upload without auth? I suspect it will be mostly a credentials issue.

Also, just in case, this process might be highly simplified and improved with https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg, that allows to use Conan packages in the Conan repo for configuration, and benefits from version ranges, lockfiles, and even ``package_id`` effect if desired.

**Comment by michxymi** [comment]
Trying with the `requests` python package, I originally got ssl errors but after passing the certificate file I got a json file back which is basically a Not Found response:

`
{
  "errors" : [ {
    "status" : 404,
    "message" : "Resource not found"
  } ]
}
`

UPLOAD_USER is a password auth we use in CI. I can try without but it seems that I should better look at the conan config install pkg.

**Comment by memsharded** [comment]
So it seems basically an auth error, the URL for that download require credentials that are not being provided?
Probably creds should be embedded in the URL, or the URL made available via anonymous access?

**Comment by michxymi** [comment]
Yes, we got it actually. It proved that the problem was not at all with the conan client but rather with our new conan artifactory repo, not having set the anonymous access as with the v1 one. Once that was set, the command worked seamlessly. I'll definitely give a look to config as a package! Thanks for all your help!

**Comment by memsharded** [comment]
Thanks for the feedback!
