### ISSUE TITLE
[bug] vcvars not called when using Visual Studio 17.10 + clang

### ISSUE THREAD

**Issue by sykhro** [conan-io/conan#16373]
### Describe the bug

Windows 11
Visual Studio 17.10.1
Conan version 2.3.2

`vcvars` is not sourced correctly resulting in some libraries failing to build

### How to reproduce it

I have a profile as follows:
```ini
[settings]
os=Windows
arch=x86_64
build_type=Debug

compiler=clang
compiler.version=17
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.runtime_version=v143
 
[conf]
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
```
all recipes show the following:
```bash
conanvcvars.bat: Activating environment Visual Studio 17 - amd64 - winsdk_version=None - vcvars_ver=14.3
[ERROR:vcvars.bat] Toolset directory for version '14.3' was not found.
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.   
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
```
and *some* decide to die right after (e.g. `libjpeg-turbo`)
I can see in the code that v143 is mapped to `vcvars_ver=14.3`:
https://github.com/conan-io/conan/blob/5abec94cfc014c94c02e8ed51f21b7d779245072/conan/tools/microsoft/visual.py#L133-L136

However, when using 17.10, the `14.3` tools are wiped by the VS installer. In light of this bug and work I've been doing lately around VS, I express desire for:
- a way to specify the vcvars_version
- a way to pass a different setup script entirely (ties back into #16276)

**Comment by sykhro** [comment]
> (ties back into https://github.com/conan-io/conan/issues/16276)

_Note: at the moment I'm not using MSBuildToolchain. I'm actually trying to build a CMake toolchain for these platforms with Ninja; the CMake experience with the VS generator is close to awful at least for this usecase_

**Comment by memsharded** [comment]
Thanks for the report @sykhro 

At the moment, at least with my LLVM/Clang 16, it seems it is not compatible with the new ``v14.4`` toolset version, I am getting compile errors like:

> #define _EMIT_STL_ERROR(NUMBER, MESSAGE)   static_assert(false, "error " #NUMBER ": " MESSAGE)

(after fixing the Conan internals to compute the ``v14.4`` for ``vcvars`` for clang.

I'll try using latest clang.

Update: It works fine with latest llvm/clang 18.1.6

**Comment by sykhro** [comment]
> Thanks for the report @sykhro
> 
> At the moment, at least with my LLVM/Clang 16, it seems it is not compatible with the new `v14.4` toolset version, I am getting compile errors like:
> 
> > #define _EMIT_STL_ERROR(NUMBER, MESSAGE)   static_assert(false, "error " #NUMBER ": " MESSAGE)
> 
> (after fixing the Conan internals to compute the `v14.4` for `vcvars` for clang.
> 
> I'll try using latest clang.
> 
> Update: It works fine with latest llvm/clang 18.1.6

That's expected, the MS STL has been requiring clang >= 17 since at least VS 17.7
https://github.com/microsoft/STL/blob/872f4768724bf77d95d6eb2f4c637dd66e2099a1/stl/inc/yvals_core.h#L894

**Comment by memsharded** [comment]
I am proposing https://github.com/conan-io/conan/pull/16374 to fix this (irrespective of the other ticket, trying to make more flexible the customization is a good idea, but this needs to work without customization). 

In short:
- Augment the ``clang`` settings to include ``compiler.runtime_version=v144``. The ``v144`` is actually the toolset **version** ``v14.4``, not the toolset **platform** ``v144``, that doesn0t exist, but unfortunately, the ``runtime_version`` subsetting in settings.yml, didn't explicitly define the dot that corresponds to the toolset version and does the conversion internally.
- Use that in the ``VCVars`` class
- Make sure that the new ``tools.microsoft:msvc_update`` is also taken into account in this place of ``VCVars`` usage.

I have been testing it locally and seems to work, feedback very welcome.

**Comment by sykhro** [comment]
> I am proposing #16374 to fix this (irrespective of the other ticket, trying to make more flexible the customization is a good idea, but this needs to work without customization).
> 
> In short:
> 
> * Augment the `clang` settings to include `compiler.runtime_version=v144`. The `v144` is actually the toolset **version** `v14.4`, not the toolset **platform** `v144`, that doesn0t exist, but unfortunately, the `runtime_version` subsetting in settings.yml, didn't explicitly define the dot that corresponds to the toolset version and does the conversion internally.
> * Use that in the `VCVars` class
> * Make sure that the new `tools.microsoft:msvc_update` is also taken into account in this place of `VCVars` usage.
> 
> I have been testing it locally and seems to work, feedback very welcome.

It seems fine to me. I wonder how this could be handled when platform v144 is released, considering the toolset version is probably going to be 14.5 or something like that ([blog post](https://devblogs.microsoft.com/cppblog/msvc-toolset-minor-version-number-14-40-in-vs-2022-v17-10/))

**Comment by sykhro** [comment]
it shouldn't be a problem until 2026 is their release cycle/timeline is to be trusted...

**Comment by sykhro** [comment]
regardless of this, I think that more customisation points would be good - I find it strange that I can edit `settings.yml` however I please but have little control over how vcvars are sourced

**Comment by memsharded** [comment]
> regardless of this, I think that more customisation points would be good - I find it strange that I can edit settings.yml however I please but have little control over how vcvars are sourced

Yes, I am not opposed to customization points, it is just we haven't been able to prioritize it yet, while this kind of bug is a much higher priority.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/16374 for next Conan 2.4

**Comment by sykhro** [comment]
Thanks!

**Comment by exoosh** [comment]
> I am proposing #16374 to fix this (irrespective of the other ticket, trying to make more flexible the customization is a good idea, but this needs to work without customization).
> 
> In short:
> 
>     * Augment the `clang` settings to include `compiler.runtime_version=v144`. The `v144` is actually the toolset **version** `v14.4`, not the toolset **platform** `v144`, that doesn0t exist, but unfortunately, the `runtime_version` subsetting in settings.yml, didn't explicitly define the dot that corresponds to the toolset version and does the conversion internally.
> 
>     * Use that in the `VCVars` class
> 
>     * Make sure that the new `tools.microsoft:msvc_update` is also taken into account in this place of `VCVars` usage.
> 
> 
> I have been testing it locally and seems to work, feedback very welcome.

While it's correct that you are looking for the directory named `14.40.*` it's wrong to make the assumption that this is derived from or maps 1:1 to a _platform toolset_ `v144`!

Besides, if you think it further ... if 14.40 maps to `v144` and Microsoft happens to decide in a future version that their platform toolset is based on major number 15 and we get 15.4 eventually, how are you going to distinguish that from 15.40?

See [my comment](https://github.com/conan-io/conan/pull/16374#issuecomment-2209258376).

**Comment by UndefBehavior** [comment]
+1 to @exoosh 

@memsharded can this decision be reviewed? Conan forces me to set nonexistent runtime_version after minor MSVS update. This decision will be obviously broken after real v144 toolset announcement so it will be needed to create new compiler property.

Maybe this property must be refactored and used also for msvc compiler since it has similar problems (there is no way to show that 193 and 194 versions of msvc compiler belongs to the same toolset).

**Comment by sykhro** [comment]
> +1 to @exoosh
> 
> @memsharded can this decision be reviewed? Conan forces me to set nonexistent runtime_version after minor MSVS update. This decision will be obviously broken after real v144 toolset announcement so it will be needed to create new compiler property.
> 
> Maybe this property must be refactored and used also for msvc compiler since it has similar problems (there is no way to show that 193 and 194 versions of msvc compiler belongs to the same toolset).

this is a clang-specific setting that was misnamed and used in a way that looks like the platform toolset, but it isn't:
https://github.com/conan-io/conan/blob/3c72e2a83b468bb0d18e958c7e160fbb324b146e/conan/tools/microsoft/visual.py#L135

**Comment by UndefBehavior** [comment]
oookay, isn't this a problem? Conan has misnamed internal toolset version property and hasn't real toolset version property.

I don't use conan as a packages' builder, I use it as a packages' dependency manager (conan export for exporting, conan install from the build system for importing).

Is it impossible to set windows profiles with correct compatibility rules? I wanted to set that v143 toolset could use v142 dependencies (i.e. static libraries) but today I find out that conan don't have toolset version for clang-cl at all. Is it right to use `msvc_version_to_toolset_version(version)` for creating compatibility rules for cl (pure msvc)?

Can this property be more documented? Is there an ability to get runtime_version for clang-cl based conan profile?
