### ISSUE TITLE
[question] Publish Package.

### ISSUE THREAD

**Issue by karimzahrouni** [conan-io/conan#16379]
### What is your question?

Hi,

Is it  possible to publish my package to the Conan Center as an open source package?

Best Regards

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @karimzahrouni 

Yes, there is a process using Pull Requests to https://github.com/conan-io/conan-center-index. 
It requires initial request for contribution in a repo issue to request access, but that is resolved quickly within a few days.

At the moment we are transitioning the ConanCenter CI to a Conan 2 pipeline and that is a huge effort, plus there are many open Pull Requests (last year ConanCenter got like 6000 PRs in 2023 alone), the activity there is very high, so things might be slow, please be patient.

I am closing this ticket as responded, feel free to open new tickets for any open questions. Thanks.
