### ISSUE TITLE
Server write persmissions order matter

### ISSUE THREAD

**Issue by ovidiub13** [conan-io/conan#1637]
If I set the permissions in this order:

```
[write_permissions]
*/*@*/*: obogdan
*/*@myteam/*: jenkins
```

I get a `permission denied` error for the `jenkins` user.

However, if I set the permissions in this order:

```
[write_permissions]
*/*/myteam/*: jenkins
*/*@*/*: obogdan
```

the `jenkins` user can upload normally.

**Comment by ovidiub13** [comment]
Also, I've just noticed, with the second order, I get a `permission denied` for the user `obogdan`.

**Comment by lasote** [comment]
Conan search for a matching package name expression in order, so as `*/*@*/*` match any reference, it will use that rule. So yes, the order matters. Specify first the more specific references, then the more general.

**Comment by ovidiub13** [comment]
This should be clarified in the `server.conf` comments. I'll make a PR.

**Comment by ovidiub13** [comment]
Done: #1638
