### ISSUE TITLE
conan test always chooses the default option although I pass another one

### ISSUE THREAD

**Issue by malakdaka** [conan-io/conan#16384]
### What is your question?

Hey,

We recently started working with conan, I added some option to test_package conan file
and I pass the option I need via the conan test command line but it always choses the default option although it is different. 

class QuantizerTest(ConanFile):
    settings = "os", "build_type", "sp"
    options = {"test":["sanity", "checkin","all"]}
    default_options = {"test":"sanity"}

this is my conan file 

conan test . quantizer/* -pr linux_sp100_release_profile -o:a test=checkin

this is the commandline I do run.

but I always get 
**The value of the test option is: sanity**

what could be the problem?
thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @malakdaka 

Thanks for your question.

The problem would be:

> conan test . quantizer/* -pr linux_sp100_release_profile -o:a test=checkin

The options must be defined with the specification of the package they apply to, something like ``-o mypkg/*:test=checkin``, or if you want to apply it for all packages, using a pattern like ``-o *:shared=True``

We have already introduced a warning in the next Conan 2.4 version to be released to give hints to user in this very specific case.

**Comment by memsharded** [comment]
Did this clarify the issue @malakdaka? Maybe we can close it as solved? Thanks

**Comment by memsharded** [comment]
Closing as responded, please create new tickets for any further question.
