### ISSUE TITLE
Premake Lua Dependencies

### ISSUE THREAD

**Issue by Codinablack** [conan-io/conan#16380]
### Describe the bug

I'm using windows 10. My profile for conan looks like this

```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

I am using conan version 2.2.1

I am using premake as my build system.

Here is my conanfile.py

```
from conan import ConanFile

class BlackTekServerSDK(ConanFile):
    settings = ("os", "compiler", "build_type", "arch")
    generators = ("PremakeDeps")

    def requirements(self):
        self.requires("cryptopp/8.9.0")
        self.requires("fmt/10.2.1")
        self.requires("mariadb-connector-c/3.3.3")
        self.requires("pugixml/1.14")
        self.requires("boost/1.84.0")
        self.requires("lua/5.4.6")
        self.tool_requires("cmake/3.27.5")

    def layout(self):
        self.folders.generators = "./packages"
```

Here is my premake file: (it includes my manual override to make it work)

```
include "packages/conandeps.premake5.lua"

workspace "Black-Tek-Server"
   configurations { "Debug", "Release"}
   platforms { "64"}
   location "./projectfiles"
   editorintegration "On"

   project        "Black-Tek-Server"
      kind        "ConsoleApp"
      language    "C++"
      cppdialect  "C++20"
      targetdir   "%{wks.location}"
      objdir      "build/%{cfg.buildcfg}/obj"
      location    "./projectfiles"
      files { "src/**.cpp", "src/**.h" }
      flags {"LinkTimeOptimization", "MultiProcessorCompile"}
      vectorextensions "AVX"
      enableunitybuild "On"

      includedirs { "C:/Users/codin/.conan2/p/luaf3d88df2ec370/p/include" }
      libdirs { "C:/Users/codin/.conan2/p/luaf3d88df2ec370/p/lib" }
      links { "lua" }

      filter "configurations:Debug"
         defines { "DEBUG" }
         symbols "On"
         optimize "Debug"
      filter {}

      filter "configurations:Release"
         defines { "NDEBUG" }
         symbols "On"
         optimize "Speed"
      filter {}
      
      filter "platforms:64"
         architecture "amd64"
      filter {}

      filter "system:not windows"
         buildoptions { "-Wall", "-Wextra", "-pedantic", "-pipe", "-fvisibility=hidden", "-Wno-unused-local-typedefs" }
      filter {}

      filter "system:windows"
         openmp "On"
         characterset "MBCS"
         debugformat "c7"
         flags {"NoIncrementalLink"}
         linkoptions {"/IGNORE:4099"}
      filter {}

      filter "toolset:gcc"
         buildoptions { "-fno-strict-aliasing" }
         buildoptions {"-std=c++20"}
      filter {}

      filter "toolset:clang"
         buildoptions { "-Wimplicit-fallthrough", "-Wmove" }
      filter {}

      filter { "system:macosx", "action:gmake" }
         buildoptions { "-fvisibility=hidden" }   
      filter {}

      conan_setup()
      intrinsics   "On"

```

### How to reproduce it

When using lua as a dependency (and generating the solution with premake), my project cannot find the location of lua.hpp or the rest of its include/bin/lib. I tried to narrow down the problem with help from people on a programming discord and with the help of chat gpt. Following the generated files leads me to a folder inside of .conan2/p that does indeed contain the correct include/bin/ and lib folders, however visual studio is not finding it.

When bypassing the generated files by conan, and directly adding in the links to premake manually like so

```
      includedirs { "C:/Users/codin/.conan2/p/luaf3d88df2ec370/p/include" }
      libdirs { "C:/Users/codin/.conan2/p/luaf3d88df2ec370/p/lib" }
      links { "lua" }
```

the produced solution file now can find lua.hpp and the rest of it just fine. This leads me to believe that conan itself is not merging filepaths or something correctly. 

Although I was able to work around this problem, my solution is just a band-aid for myself. My end users should not be expected to have to find the location of the conan installed packages themselves to add in the manual override for the linking.

Please help me figure out how to resolve this so that my users can benefit from the flexibility and power of conan.

**Comment by AbrilRBS** [comment]
Hi!
Thanks a lot for your report. I've tried to reproduce this locally but was unable to. 

(Notice the lack of Premake documentation in Conan 2 for the time being, as we're not 100% confident with its stability to properly release it without guaranteeing its robustness like the more commonplace generators, so thanks a lot for taking the time to report this issue, as it helps us have more insight into its usages etc :) )

Some general questions to understand where things might be going wrong:

- Are the rest of the dependencies correctly being found by your IDE?

- In your local `./packages` folder, you should have something a file named something like `conan_lua_vars_release_x86_64.premake5.lua`, which should contain the same paths you're looking for. This file is automatically included by the `packages/conandeps.premake5.lua` file you import so no extra work should be necessary on your side. Does said file exist? Does it contain the proper paths?


(Wild guess, but does changing your lines:

```
filter "platforms:64"
   architecture "amd64"
filter {}
```

to specify direclty the `x86_64` value that `amd64` stands for change anything?)

---

One minor extra thing: 
It won't be breaking anything, but remember that tool_requires should go into their own `def build_requirements(self):` function ([Docs here](https://docs.conan.io/2/reference/conanfile/methods/build_requirements.html)) :)

**Comment by Codinablack** [comment]
> Hi! Thanks a lot for your report. I've tried to reproduce this locally but was unable to.
> 
> (Notice the lack of Premake documentation in Conan 2 for the time being, as we're not 100% confident with its stability to properly release it without guaranteeing its robustness like the more commonplace generators, so thanks a lot for taking the time to report this issue, as it helps us have more insight into its usages etc :) )
> 
> Some general questions to understand where things might be going wrong:
> 
>     * Are the rest of the dependencies correctly being found by your IDE?
> 
>     * In your local `./packages` folder, you should have something a file named something like `conan_lua_vars_release_x86_64.premake5.lua`, which should contain the same paths you're looking for. This file is automatically included by the `packages/conandeps.premake5.lua` file you import so no extra work should be necessary on your side. Does said file exist? Does it contain the proper paths?
> 
> 
> (Wild guess, but does changing your lines:
> 
> ```
> filter "platforms:64"
>    architecture "amd64"
> filter {}
> ```
> 
> to specify direclty the `x86_64` value that `amd64` stands for change anything?)
> 
> One minor extra thing: It won't be breaking anything, but remember that tool_requires should go into their own `def build_requirements(self):` function ([Docs here](https://docs.conan.io/2/reference/conanfile/methods/build_requirements.html)) :)

Thanks for the apt response!

Yes the rest of the dependencies are correctly found by my IDE.

As for the file existing, yes and yes to the correct path. I did mention this in my first post, although I guess I wasn't so clear, but that is where I found and compared the paths myself before making the manual addition to the premake file. Both files for lua exist actually. I have one that references the `conan_lua_vars_release_x86_64.premake5.lua` and I have that file too. 

![image](https://github.com/conan-io/conan/assets/8696596/aa215bc2-becb-41e4-9826-4317cba19b2a)

The file you specifically asked about, the conan_lua_vars_release_86_64.premake.lua looks like this

```
#!lua

include "conanutils.premake5.lua"

t_conandeps = {}
t_conandeps["release_x86_64"] = {}
t_conandeps["release_x86_64"]["lua"] = {}
t_conandeps["release_x86_64"]["lua"]["includedirs"] = {"C:/Users/codin/.conan2/p/luaf3d88df2ec370/p/include"}
t_conandeps["release_x86_64"]["lua"]["libdirs"] = {"C:/Users/codin/.conan2/p/luaf3d88df2ec370/p/lib"}
t_conandeps["release_x86_64"]["lua"]["bindirs"] = {"C:/Users/codin/.conan2/p/luaf3d88df2ec370/p/bin"}
t_conandeps["release_x86_64"]["lua"]["libs"] = {"lua"}
t_conandeps["release_x86_64"]["lua"]["system_libs"] = {}
t_conandeps["release_x86_64"]["lua"]["defines"] = {}
t_conandeps["release_x86_64"]["lua"]["cxxflags"] = {}
t_conandeps["release_x86_64"]["lua"]["cflags"] = {}
t_conandeps["release_x86_64"]["lua"]["sharedlinkflags"] = {}
t_conandeps["release_x86_64"]["lua"]["exelinkflags"] = {}
t_conandeps["release_x86_64"]["lua"]["frameworks"] = {}

if conandeps == nil then conandeps = {} end
conan_premake_tmerge(conandeps, t_conandeps)

```

and the other like so
```

#!lua
include "conan_lua_vars_release_x86_64.premake5.lua"
```

as for that specific bit about x64. I don't think that actually makes any difference at all on windows, I can't say for sure for linux. I really only used that as it was used in another example I was drawing from, better safe than sorry kind of thing.

and about the tool_requires, thanks for the tip! I thought I had read somewhere that build_requirements() was being deprecated soon, but I guess I was mixing that up with something else, I will correct that issue for sure. 

I did notice the lack of documentation for premake. It did sadden me to see that premake support was kind of placed on a back-burner. It has worked well with conan from my experience, so far. I love premake and the development has recently picked back up on it. To be honest with you, if I ever get the free time, I would most likely contribute to it as well, I just have other projects that demand my attention first.

**Comment by Codinablack** [comment]
Just noticed some errors I didn't see before

```
fmt/10.2.1: Checking 3 compatible configurations
fmt/10.2.1: Main binary package '81000d7a34fb02600d7a1deb46c478bd09216966' missing. Using compatible package 'bed280a9c51d41820ca64294cf373083ad852aa8': compiler.cppstd=14
lua/5.4.6: Checking 3 compatible configurations
lua/5.4.6: Main binary package '839ffb0a3b4bcd4242d3733d5f81f38ccda78b1c' missing. Using compatible package 'e0f3a9b9f144c65d081eb9982bcae09be7427cd4': compiler.cppstd=14
pugixml/1.14: Checking 3 compatible configurations
pugixml/1.14: Main binary package '430aae9c26e6a6528b1a42fc20aee57cef92ce94' missing. Using compatible package '30ef123599bdbe8832d0547653bcc4946252c2f9': compiler.cppstd=14
cryptopp/8.9.0: Checking 3 compatible configurations
cryptopp/8.9.0: Main binary package '1ea364231c650f022d5beba1cd465683c4edcc75' missing. Using compatible package '9bdee485ef71c14ac5f8a657202632bdb8b4482b': compiler.cppstd=14
```

**Comment by Codinablack** [comment]
This is getting crazy. I discovered that the luajit my compiler was linking against previously was actually one installed by vcpkg (this brings doubt about my compiler linking against anything from conan tbh). 

I removed that installation of luajit, and decided to switch back to using it with conan to see if it would find it , and low and behold, it did not. What is crazy, is it finds it for release, but not for debug. Which is absolutely mind boggling for me. I am also noticing what appears to be hundreds of errors for mariadb now. 

![image](https://github.com/conan-io/conan/assets/8696596/e082fa6d-279e-406b-8f7a-f21afcca4247)
![image](https://github.com/conan-io/conan/assets/8696596/de94f87c-cacf-4804-b917-f8f061b76bf3)

I know that is a topic for another issue, and probably should be made an issue on the conan center, I just thought I would mention all these troubles I am having.

**Comment by Codinablack** [comment]
For the record, I do install both debug and release versions of everything. Both my premake and conan are called from this setup_build.py file, it looks like this:

```
import subprocess
from platform import system

def ConfigureConan():
	subprocess.run(["conan", "profile", "detect"])

def RunConan(buildType):
	subprocess.run(["conan",  "install", ".", "--build=missing", f"--settings=build_type={buildType}"])

def RunPremake():
	match system():
		case "Linux":
			subprocess.run(["./premake5", "gmake2"])
		case "Windows":
			subprocess.run(["premake5", "vs2022"])
		case "Darwin":
			subprocess.run(["premake5", "xcode4"]) # Maybe?


if __name__ == "__main__" :
	#ConfigureConan()
	RunConan("Debug")
	RunConan("Release")
	RunPremake()
```

**Comment by AbrilRBS** [comment]
Hi @Codinablack thanks for the extra information on your process. This is what I'm doing currently to try to reproduce this:
1. Run `conan install --requires=lua/5.4.6 -b=missing -g PremakeDeps`
2. For this premake5.lua file (Reduced from yours)

3. Activate the `.\conanbuild.ps1` env
4. Run `premake5.exe vs2022`

In the resulting VS solution I can properly include `lua.h` and this compiles ok
```
#include "lua.h"

int main() {
	return LUA_OK;
}
```

Could you try running by hand, see if that changes things? Thanks!

**Comment by AbrilRBS** [comment]
Note that this https://github.com/conan-io/conan/issues/16380#issuecomment-2143277110 comment from Conan is not an error, but Conan trying to fetch compatible binaries before resorting to building them :) (Thanks for reporting the maria-db compilation errors, we appreciate it!)

**Comment by Codinablack** [comment]
I gave up and moved back to vcpkg.

**Comment by AbrilRBS** [comment]
I'm sorry to hear that, if you ever feel like running the steps I mentioned above to help diagnose the issue, feel free to reopen the issue :)
