### ISSUE TITLE
How to add compiler flag to a package before it's built?

### ISSUE THREAD

**Issue by Codinablack** [conan-io/conan#16381]
### What is your question?

Hello all! I have a project that utilizes luajit. Luajit itself will throw exceptions for the size of the lua environment when reaching a 2 gig limit. This can be fixed by passing the -X flag to luajit during its build. 

My question is how can I do that with conan? I am using the packages from the conan center. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @Codinablack thanks a lot for the question.

While it remains to be seen if adding this flag directly to the CCI recipe would make sense (If this is something endemic to all luajit builds, it might be better to fix it at the recipe level!), locally you can add extra compilation flags to your recipes using the `tools.build:cflags` and/or `tools.build:cxxflags` confs when building the recipe locally ([Docs here](https://docs.conan.io/2/reference/config_files/global_conf.html)).

This means adding something like this line to either your profile in a `[conf]` section (recommended for reproducibility's shake), or your CLI (by using the `-c` argument):

`luajit/*:tools.build:cflags=["-X"]`

(The first section ensures that only the `luajit` package gets the extra cflags, [docs here](https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns))

This should add the desired flag to the luajit build and let it properly work in your environment. 

~Note that afaik luajit is C code so you should use the `:cflags` conf, but I might be missremebering and if it were C++, you should use the `cxxflags` conf instead~ Edit: Just checked, it in fact is C code!

Let me know if this helps :)

**Comment by Codinablack** [comment]
I added that line to my profile, as far as I can tell it might have worked, I just can't tell for sure right now as I am running into an issue getting it to link against luajit in debug now (debug was how I saw the exceptions that were being caused as a lack of using this compiler flag)
