### ISSUE TITLE
[bug] custom deploy script using conan.tools.file.copy throws AttributeError object has no attribute output.

### ISSUE THREAD

**Issue by drmacdon** [conan-io/conan#16395]
### Describe the bug

Conan Version 2.3.2 running a custom deploy script with 'conan deploy sources_deploy.py' which depends on conan.tools.file.copy to help with copying throws AttributeError. It did work at one point but now fails. 

```
  File "/opt/homebrew/Cellar/conan/2.3.2/libexec/lib/python3.12/site-packages/conan/tools/files/copy_pattern.py", line 51, in copy
    conanfile.output.debug(f"copy(pattern={pattern}) copied {len(copied_files)} files\n"
    ^^^^^^^^^^^^^^^^
AttributeError: 'ConanFileInterface' object has no attribute 'output'
```

### How to reproduce it

Running a custom deploy script called 'sources_deploy.py' with 'conan deploy sources_deploy.py' which makes use of the conan.tools.file.copy helper generates an exception on execution.

```
# cat sources_deploy.py
from conan.tools.files import copy
from conans.errors import ConanException
import os

def deploy(graph, output_folder, **kwargs):
    out = os.path.join(output_folder, "project")
    for name, dep in graph.root.conanfile.dependencies.items():
        source_folder = str(dep.folders.package_folder)
        if dep.ref.name == 'project':
            copy(dep, "*", source_folder, out)
```
which encounters the following exception
```
ERROR: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/conan/2.3.2/libexec/lib/python3.12/site-packages/conan/cli/cli.py", line 291, in main
    cli.run(args)
  File "/opt/homebrew/Cellar/conan/2.3.2/libexec/lib/python3.12/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/opt/homebrew/Cellar/conan/2.3.2/libexec/lib/python3.12/site-packages/conan/cli/command.py", line 164, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/conan/2.3.2/libexec/lib/python3.12/site-packages/conan/cli/commands/install.py", line 74, in install
    conan_api.install.install_consumer(deps_graph, args.generator, source_folder, output_folder,
  File "/opt/homebrew/Cellar/conan/2.3.2/libexec/lib/python3.12/site-packages/conan/api/subapi/install.py", line 73, in install_consumer
    do_deploys(self.conan_api, deps_graph, deploy, deploy_package, base_folder)
  File "/opt/homebrew/Cellar/conan/2.3.2/libexec/lib/python3.12/site-packages/conan/internal/deploy.py", line 66, in do_deploys
    deployer(graph=graph, output_folder=deploy_folder)
  File "/Users/me/dev/project/sources_deploy.py", line 10, in deploy
    copy(dep, "*", source_folder, out)
  File "/opt/homebrew/Cellar/conan/2.3.2/libexec/lib/python3.12/site-packages/conan/tools/files/copy_pattern.py", line 51, in copy
    conanfile.output.debug(f"copy(pattern={pattern}) copied {len(copied_files)} files\n"
    ^^^^^^^^^^^^^^^^
AttributeError: 'ConanFileInterface' object has no attribute 'output'

ERROR: 'ConanFileInterface' object has no attribute 'output'
```

**Comment by memsharded** [comment]
Quick hint ``from conans.errors import ConanException`` shouldn't be used anymore, only ``from conan.xxx``, no ``from conans.`` the later will be removed in future versions.

**Comment by memsharded** [comment]
Thanks for your report @drmacdon 

I am not sure this is a bug. The ``copy()`` method is not intended to be passed the dependency, but the actual caller of the copy.  In this case it would be ``graph.root.conanfile`` instead.  This is what the example in https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html#code-tour is doing.

**Comment by drmacdon** [comment]
Thanks for the fast response @memsharded.

Confirmed, I switched to using graph.root.conanfile and it works as expected.

Closing as non-issue.

Thanks!

**Comment by memsharded** [comment]
Thanks for following up.

I have re-checked this, just in case, and it seems correct to keep the ``.output`` private to the recipe and not available to the consumers. The reason is that that ``.output`` is the one that prints all the ``pkg/version: messsage`` so in the output logs it is easy to identify operations and output that happens while processing that specific ``pkg/version`` recipe. But if a deployer or other consumer of the package can use that same object with the same output, it can be confusing, so the idea is that the output really belongs to the caller for UX.

Thanks for the feedback!
