### ISSUE TITLE
[question] How to package application  with conan installed dependencies together?

### ISSUE THREAD

**Issue by aiyolo** [conan-io/conan#16408]
### What is your question?

I want to make a installer for my application that will need some dll files installed by conan.

I known that conan will install dependencies to `.conan` folder, but how I can I copy the  all the dependent *dll file to a customed folder when I run `cmake --build  --preset release --target install `?

 Is there a recommended practice?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aiyolo 

Yes, there are some recommended practices:

- ``deployers`` can be used as a generic mechanism to extract files from the conan cache and copy them to your local folder so you can create installers from them: https://docs.conan.io/2/reference/extensions/deployers.html#deployers
- You can also create your custom commands that do your own logic, you might even automate the creation of your installer in a Conan custom command: https://docs.conan.io/2/reference/extensions/custom_commands.html
- These are conan commands, no ``cmake`` commands. If you want to automate something from the CMake side, you might use https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#conan-runtime-lib-dirs

**Comment by memsharded** [comment]
Any further question here @aiyolo ? Maybe the ticket can be closed?

**Comment by aiyolo** [comment]
> Any further question here @aiyolo ? Maybe the ticket can be closed?

Thanks for your  reply！I had tried the  deployer option. I hope more example around this option can be added into official site.
