### ISSUE TITLE
[question] source_credentials.json jinja example

### ISSUE THREAD

**Issue by kip3f** [conan-io/conan#16407]
### What is your question?

Hi!  I'm experimenting with injecting credentials using source_credentials.json, and I'm interested in setting up a jinja template to do  this as per the web page.  Is there an example showing how I could configure this?  (I've never used Jinja before)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @kip3f 

You have some examples in:
- https://docs.conan.io/2/reference/config_files/source_credentials.html
- https://docs.conan.io/2/reference/config_files/credentials.html
- global.conf: https://docs.conan.io/2/reference/config_files/global_conf.html#configuration-file-template
- https://docs.conan.io/2/reference/config_files/profiles.html#profile-rendering

This is the basic jinja usage, for a full reference of jinja you can read: https://jinja.palletsprojects.com/en/3.1.x/templates/

**Comment by memsharded** [comment]
Did this help?
Maybe we can close the ticket? Thanks!

**Comment by kip3f** [comment]
Hi memsharded,
this was very helpful, please close the ticket, thanks.  May I recommend that [the source_credentials.json website](https://docs.conan.io/2/reference/config_files/source_credentials.html) be updated to only include jinja templates?  I think that would have helped clarify things.
