### ISSUE TITLE
[question] What is the order of conan methods call?

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#16410]
### What is your question?

What is the call order of https://docs.conan.io/2/reference/conanfile/methods.html ?

In particular, the call order of:
* set_name()
* set_version()
* configure()
* layout()
* requirements()
* package()

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DmitrySokolov 

Thanks for your question.

You have the order of the ``conan create`` in https://docs.conan.io/2/reference/commands/create.html#methods-execution-order

**Comment by DmitrySokolov** [comment]
Hi @memsharded 

Thanks!

But why there are 2 `init()` calls?

**Comment by memsharded** [comment]
> But why there are 2 init() calls?

The ``export`` and the ``install`` are separate steps, one loads the recipe in the user space, and then ``install`` loads the recipe in the cache, to guarantee reproducibility. The ``create`` command is equivalent to ``conan export`` + ``conan install --requires=<thepkg> --build=<thepkg>`` + ``conan test ...``

**Comment by DmitrySokolov** [comment]
So, the `self.version` field acquired in `set_version()` will be available in `layout()`, right?

**Comment by memsharded** [comment]
> So, the self.version field acquired in set_version() will be available in layout(), right?

Yes, but ``set_version()`` only works at ``export`` time, the ``self.version`` might come from the cache metadata once the package is in the cache, without executing the ``set_version()`` method.

**Comment by DmitrySokolov** [comment]
Thanks!
