### ISSUE TITLE
[bug] XcodeToolchain's  conan_global_flags.xcconfig not flagged to save if _global_defines is populated

### ISSUE THREAD

**Issue by jacobfriedman** [conan-io/conan#16422]
### Describe the bug

Changelog: (Bugfix):

Docs state that the global xcode config will be generated with modification of the _global_defines, but the _check_if_extra_flags(self) only checks for cflags/cxxflags/ldflags/exelinkflags.

Docs: https://docs.conan.io/2/reference/tools/apple/xcodetoolchain.html#xcodetoolchain-conf

### How to reproduce it

Attempt to modify _global_defines and conan_global_flags.xcconfig will not be created.

Fix:
https://github.com/jacobfriedman/conan/pull/1

**Comment by czoido** [comment]
Hi @jacobfriedman,
Thanks a lot for reporting. Indeed it seems a bug.
Adding this to be fixed in the 2.5.0 release.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/16429 for 2.5
