### ISSUE TITLE
[bug] fails to download from conancenter

### ISSUE THREAD

**Issue by ocpalo** [conan-io/conan#16437]
### Describe the bug

Rocky linux 9.4
conan version 2.4.0

conan profile:
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux
```

Error is:
```
libsodium/1.0.19: WARN: network: Error downloading file https://github.com/jedisct1/libsodium/releases/download/1.0.19-RELEASE/libsodium-1.0.19.tar.gz: 'HTTPSConnectionPool(host='[github.com](http://github.com/)', port=443): Max retries exceeded with url: /jedisct1/libsodium/releases/download/1.0.19-RELEASE/libsodium-1.0.19.tar.gz (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))'
libsodium/1.0.19: Waiting 5 seconds to retry...
libsodium/1.0.19: WARN: network: Error downloading file https://github.com/jedisct1/libsodium/releases/download/1.0.19-RELEASE/libsodium-1.0.19.tar.gz: 'HTTPSConnectionPool(host='[github.com](http://github.com/)', port=443): Max retries exceeded with url: /jedisct1/libsodium/releases/download/1.0.19-RELEASE/libsodium-1.0.19.tar.gz (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))'
libsodium/1.0.19: Waiting 5 seconds to retry...
ERROR: libsodium/1.0.19: Error in source() method, line 74
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        ConanException: Error downloading file https://github.com/jedisct1/libsodium/releases/download/1.0.19-RELEASE/libsodium-1.0.19.tar.gz: 'HTTPSConnectionPool(host='[github.com](http://github.com/)', port=443): Max retries exceeded with url: /jedisct1/libsodium/releases/download/1.0.19-RELEASE/libsodium-1.0.19.tar.gz (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))'
```

**Comment by ocpalo** [comment]
![image (6)](https://github.com/conan-io/conan/assets/44481097/b4832d73-f733-4c6b-a1d3-57df19b68515)

It fails to download protobuff to. However I think zlib successfully downloaded and installed. What can be wrong?

**Comment by memsharded** [comment]
Hi @ocpalo 

This kind of error, downloading things from the internet can be caused by several reasons, outside Conan scope, like VPN, enterprise proxies configurations, ZScaler, custom user certificates, etc.

Something you can try is to add the ``-c tools.files.download:verify=False`` to disable the https verification (this is kind of a workaround/test, if this works, then you might need to work with your IT to find the blocker and allow-list those URLs or add certificates)

**Comment by ocpalo** [comment]
`conan install -c tools.files.download:verify=False . --output=build --build=missing`

I tried like that and it did not work out. Is the placement of the `-c tools...` flag correct?

**Comment by memsharded** [comment]
In general it is preferred positional arguments first (argparse can have ambiguities otherwise), so 
```
conan install  . -c tools.files.download:verify=False --output-folder=build --build=missing
```
Also the ``--output-folder`` full format is preferred, or the short ``-of=build``

Still it doesn't seem that it would be the issue, and there are other limitations elsewhere.
Can you please confirm your system ``conan version`` and also if you are running it in some corporate computer and/or network that could be limiting some resources?

**Comment by ocpalo** [comment]
I tried to git clone and it also failed. Error is :

```
fatal: unable to access 'https://github.com/zeux/pugixml/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443)fatal: unable to access 'https://github.com/zeux/pugixml/': OpenSSL SSL_connect: Connection reset by peer in connection to [github.com:443](http://github.com:443/)
```

Do you have any idea about that error?

There is something wrong with the netwok configuraitons. It seems that it has nothing to do with conan. Thanks for quick response!

**Comment by memsharded** [comment]
> Do you have any idea about that error?

Yes, I know the main reasons:
- Corporate proxies
- Corporate VPNs
- Corporate ZScaler
- Corporate network limitations/firewalls
- Corporate certificates or the like
- Country bans/restrictions

But besides that it is quite challenging to know what exactly it could be. If you can easily reproduce with a ``git clone url`` or a ``wget`` or ``curl`` normal download, I suggest you reach out to your IT with that and ask them for help. This process might need to be iterated a few times to allow-list several sites like github, sourceforge and others

**Comment by ocpalo** [comment]
ah ok. Thank you. I am closing this.

**Comment by ocpalo** [comment]
Hi again @memsharded 

It is odd that without making any changes on network, i managed to sucessfully run conan install with the following command

`conan install . -pr:h=release -pr:b=release --output-folder=build --build=missing`

Previously I was used

`conan install  . --output-folder=build --build=missing`

Do you think that makes a difference?

**Comment by memsharded** [comment]
> -pr:h=release -pr:b=release 

No, the ``profiles`` shouldn't affect this behavior, unless you had some specific ``[conf]`` in your profiles, the ``source()`` download will do exactly the same. Maybe it is that using those profiles, Conan is finding a pre-compiled binary and not needing to build from source, and as it is not building from source, the ``source()`` method will not be executed and it will not fail to download anything. You should be able to see that in the output of the command.
