### ISSUE TITLE
Overwriting build_id to set options.shared = "Any" breaks test_package source build

### ISSUE THREAD

**Issue by tru** [conan-io/conan#1643]
I noticed this when I started to make our packages build shared / static at the same time, after adding: `def build_id(self): self.info_build.options.shared = "Any"` running `test_package` seems to change the defaults from `--build=<package>` to `--build=missing`. Meaning that I don't see a forced rebuild everytime I run test_package.

I was able to reproduce it easily with the attached sample.

[conan-test-package.zip](https://github.com/conan-io/conan/files/1241250/conan-test-package.zip)

**Comment by lasote** [comment]
Confirmed. I think I fixed it. I'll write a test and submit it to 0.26

**Comment by lasote** [comment]
Sorry, as @memsharded pointed in the PR this is the intended behavior. If we force the rebuilding of the library the `build_id` is useless, it's intended to avoid building again generating packages. So if you want to rebuild it you will need at least to remove the build folder.

**Comment by tru** [comment]
Oh I see. I guess I was expecting it to work similar to how the current test_package thing works. Maybe this should be a documented effect of the change?

**Comment by memsharded** [comment]
But I don't think it is a change, I think it was already that way. Packages with ``build_id()`` won't rebuild if the build folder already exists.
