### ISSUE TITLE
[question] Building libX11 with conan

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#16483]
### What is your question?

Hi!
I've noticed that Qt has xorg as a system dependency. Is there a conanfile in development for building the entirety of libX11? Are there any caveats?

thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @donlk 

From our experience, those low-level libraries work typically better, less issues, etc when coming from the system. Even if in theory there could be recipes for X11/xorg that build from source, the binary compatibility for those packages with respect to the system is not that clear, so it could have difficult to understand and debug issues. Also, it doesn't seem to have a large and clear demand, also from the experience, the vast majority of users expect this library to be part of the system, not managed by Conan.

We think that there should be a limit for the scope of ConanCenter. Users can do what they want with their private packages and repos, but for ConanCenter, it is a delicate balance between value provided for the majority of ConanCenter users, and the complexity and maintenance costs. X11 is one of the "system" ones, that would add quite some complexity for the value, and this complexity can easily lead to more fragility, more problems on recipes using it, and more maintenance cost. X11 working as a "system" dependency has been working pretty well so far.

**Comment by donlk** [comment]
I see, thank you!
