### ISSUE TITLE
Build profiling using Conan?

### ISSUE THREAD

**Issue by devlpr** [conan-io/conan#16516]
### What is your question?

Would Conan be a good fit for adding build profiling since it executes all of the build commands? Having a graph of all the execution times would go a long way toward efficient builds.

Thanks in advance!

-Darin

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @devlpr 

yes, Conan has some mechanisms intended to be able to deal with some of these "meta-build" things:

- The hooks. You can use a ``post-build`` hook for example to submit the build time to your own metrics backend. There is a ``pre-build`` hook, maybe to start the timer. You could be collecting data as the binaries size or other stuff
- The ``metadata`` files. This is a way of storing files, together with packages, but that are not necessarily downloaded everytime with every package install.

Maybe for this specific use case, the hooks looks better.

**Comment by devlpr** [comment]
Thanks very much. We will look into this. We do have metrics collection already so this may not be too bad.

I really appreciate your response!

-Darin
