### ISSUE TITLE
[question] Is there any way to get conan_run.log in Conan v2?

### ISSUE THREAD

**Issue by CommanderCRM** [conan-io/conan#16524]
### What is your question?

Hi,
 [previously ](https://docs.conan.io/en/1.60/mastering/logging.html) there was an environment variable called CONAN_LOG_RUN_TO_FILE earlier which parsed the Conan output to .log file. 

I've visited new env [reference ](https://docs.conan.io/2.4/reference/environment.html) and global.conf [reference](https://docs.conan.io/2.4/reference/config_files/global_conf.html#reference-config-files-global-conf), there doesn't seem to be anything alike. Is there any way to log the build process to a file now?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @CommanderCRM ,

Yes, we got rid of that variable in Conan 2.x. We would recommend that you redirect the output directly to a file via CLI. Something like:

```
conan create . > my_log.txt
```
```
conan install --requires=zlib/1.3.1 --format=json > my_log.json
```
If you also want to redirect the stdout to a file and the stderr to the stdout:

```
conan create . >file.log 2>&1
```

**Comment by CommanderCRM** [comment]
All right, noted, thanks
