### ISSUE TITLE
test_package/conanfile.py not importing shared libraries on linux

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#1652]
When I use `conan new --test`  the resulting `test_package/conanfile.py` only imports .dll (windows) and .dylib (Macos) files, but it forgets about importing the .so ones (Linux).

```
    def imports(self):
        self.copy("*.dll", dst="bin", src="bin")
        self.copy("*.dylib*", dst="bin", src="lib")
```
It would be nice to add the following line to that method:

```
        self.copy('*.so*', dst='bin', src='lib')
```
When I use the **test_package** I want my application to load the libraries directly from the deployment folders, and not from the **package** folders of the recipes.

**Comment by memsharded** [comment]
But to load the *.so files form the local bin folder, you still need to define LD_LIBRARY_PATH or something. So you need to modify the recipe anyway, right?

**Comment by memsharded** [comment]
Added PR, that was simple. But I don't know if that will be a bit confusing, inexperienced linux users might think that it should work for shared libraries as-is.

**Comment by piponazo** [comment]
Right, I did not consider that. In the `test_package/CMakeLists.txt` file we always do this trick to be more restrictive with the RPATHs:

```
conan_basic_setup()
if (UNIX)
    set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
    if (APPLE)
        set(CMAKE_SKIP_RPATH 0) # Solve known issue on Mac
        set(CMAKE_INSTALL_RPATH "@executable_path/../lib")
    else()
        set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")
    endif()
else()
``` 

If you think it could generate confusion, I will understand it.

**Comment by memsharded** [comment]
The PR https://github.com/conan-io/conan/pull/1655 added different executions of apps with shared libs dependencies
