### ISSUE TITLE
Getting started tutorial doesn't work

### ISSUE THREAD

**Issue by nowox** [conan-io/conan#1654]
I am very new to Conan, and I am trying to follow the [getting started](http://conanio.readthedocs.io/en/latest/packaging/getting_started.html) page. 

So I did: 

    mkdir mypkg && cd mypkg
    conan new Hello/0.1 -t
    conan create demo/testing

On Cygwin I get this error: 

```
$ conan create demo/testing
Hello/0.1@demo/testing: Exporting package recipe
WARN: Conanfile doesn't have 'description'.
It is recommended to add it as attribute
Hello/0.1@demo/testing: The stored package has not changed
Hello/0.1@demo/testing: Installing package
Hello/0.1@demo/testing: WARN: Forced build from source
Hello/0.1@demo/testing: Building your package in /cygdrive/c/Users/Ycr/Home/.conan/data/Hello/0.1/demo/testing/build/85f22dc2060808f4a253f35b57e3ebb52aac80b9
Hello/0.1@demo/testing: Copying sources to build folder
Hello/0.1@demo/testing: Generator cmake created conanbuildinfo.cmake
Hello/0.1@demo/testing: Calling build()
CMake Error: Could not create named generator MinGW Makefiles
Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  KDevelop3                    = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.

Hello/0.1@demo/testing:
Hello/0.1@demo/testing: ERROR: Package '85f22dc2060808f4a253f35b57e3ebb52aac80b9' build failed
Hello/0.1@demo/testing: WARN: Build folder /cygdrive/c/Users/Ycr/Home/.conan/data/Hello/0.1/demo/testing/build/85f22dc2060808f4a253f35b57e3ebb52aac80b9
ERROR: Hello/0.1@demo/testing: Error in build() method, line 25
        self.run('cmake hello %s' % cmake.command_line)
        ConanException: Error 256 while executing cmake hello -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_SYSTEM_NAME="Windows" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="5.4" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/cygdrive/c/Users/Ycr/Home/.conan/data/Hello/0.1/demo/testing/package/85f22dc2060808f4a253f35b57e3ebb52aac80b9" -Wno-dev
```

And on CentOS I get this one: 

```
$ conan create demo/testing
Hello/0.1@demo/testing: Exporting package recipe
WARN: Conanfile doesn't have 'description'.
It is recommended to add it as attribute
Hello/0.1@demo/testing: The stored package has not changed
ERROR: Hello/0.1@demo/testing: 'settings.compiler' value not defined
```

Could someone explain what I did wrong? Using `conan` doesn't seems to be very straightforward.

**Comment by memsharded** [comment]
Conan will not install compilers for you, it will use the compilers and tools you have in the system.
It seems in both cases conan didn't properly detected the environment, or something is not properly configured.

Could you please remove the ``<userhome>/.conan`` folder and run ``conan`` again? The paste the output for each system. Look for your default profile, that will store your default automatically detected configuration. You can read it with ``conan profile show default``, or just open the ``<userhome>/.conan/profiles/default`` file.

**Comment by nowox** [comment]
On both systems I have the compilers installed. I have `gcc` and `glibc`. 

After removing `~/.conan` on both system I have the same issue on both systems. 

For CentOS I have: 

```
$ conan profile show default
Configuration for profile default:

[settings]
    os: Linux
    arch: x86_64
    compiler: gcc
    compiler.version: 4.8
    compiler.libcxx: libstdc++
    build_type: Release
[env]
[scopes]
    dev=True
```

and on Cygwin 

```
$ conan profile show default
Configuration for profile default:

[settings]
    os: Windows
    arch: x86_64
    compiler: gcc
    compiler.version: 5.4
    compiler.libcxx: libstdc++
    build_type: Release
[env]
[scopes]
    dev=True
```

For the latter config I think it is wrong to say I am on Windows. I run on Cygwin which is different.

**Comment by skizzay** [comment]
Is gcc found in your `PATH` variable?  On CentOS, what's the output of `which gcc`?

**Comment by nowox** [comment]
In both distributions:

    $ which gcc
    /usr/bin/gcc

**Comment by memsharded** [comment]
The case about CYGWIN, I know very little, if someone else know better, please help (I am aware of some users using it, because the CYGWIN references in the conan code were added by them)

The case for CentOS is much weirder. Just to make sure, you are runing conan 0.25.1, right?
``conan --version``

Could you please copy the full output when running this?

```bash
rm -rf /home/user/.conan
mkdir mypkg && cd mypkg
conan new Hello/0.1 -t -s
conan create demo/testing
```

Thanks!

**Comment by nowox** [comment]
A funny thing is  the tutorial now shows:

```
$ conan create . demo/testing
...
Hello world!
```

Notice the dot (`.`). Of course I get this error: 

```
$ conan create . demo/testing
usage: conan create [-h] [--cwd CWD] [--file FILE] [-ne] [-tf TEST_FOLDER]
                    [--keep-source] [--werror] [--manifests [MANIFESTS]]
                    [--manifests-interactive [MANIFESTS_INTERACTIVE]]
                    [--verify [VERIFY]] [--update] [--scope SCOPE]
                    [--profile PROFILE] [-r REMOTE] [--options OPTIONS]
                    [--settings SETTINGS] [--env ENV]
                    [--build [BUILD [BUILD ...]]]
                    reference
conan create: error: unrecognized arguments: demo/testing
ERROR: Exiting with code: 2
```

Is that normal?

**Comment by nowox** [comment]
In the mean time, I switched to WSL (Windows Subsystem for Linux) which looks much better than Cygwin and there, the Conan example works.

**Comment by memsharded** [comment]
Hi @nowox 

Could you please check the version you are running in each system?

```
$ conan --version
```
I would say you might have an old version in Windows, but a new one in WSL. Please tell. Thanks!

**Comment by nowox** [comment]
```
$ conan -v
Conan version 0.29.1
```

**Comment by memsharded** [comment]
> Conan version 0.29.1

That is the issue. The docs you are seeing, with ``conan create . user/testing`` (with dot) are for conan 1.0, not for conan 0.29. Please make sure your conan installation really upgrades to 1.0

**Comment by danimtb** [comment]
Getting started change a lot since then so this issue is obsolete right now. Closing this but feel free to open a new one with the info updated. Thanks!
