### ISSUE TITLE
Easiest way to get the URL from a ref in Conan 2

### ISSUE THREAD

**Issue by devlpr** [conan-io/conan#16589]
### What is your question?

Hi there. I'm used to using `conan inspect` in Conan 1, to get the URL from a package. This is useful for our internal packages mainly so I can go clone them down to work on them. What is the best way to do the same thing in Conan 2? It seems that most commands now want a path.

Something like this works, but it seems fragile.

`conan graph info . | grep package-name -A 10 | grep url`

Thanks for any advice.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @devlpr 

Thanks for your question.

The recommended way for this would be the ``conan graph info ... --format=json > graph.json``, then getting ``graph->nodes->0->url``. This second part can be done relatively easily with ``jq``.

Also, we are consider a new command that will clone any dependency that has the right information stored in the ``conandata`` with the ``scm`` approach (as the commit is also necessary to work exactly on the right commit for any previous version). This will be part of the ``workspace`` feature.

**Comment by devlpr** [comment]
That gets it from a path, right? I'm looking to get the URL from a reference instead. I'm not looking for the URL of the current package. I'm looking for the URL from a package that is on the remote. On of the dependencies. Even a transitive one. In Conan 1 I could us `conan inspect REF` to get this easily. Usually I pull the ref from a package failure message. Then I can go clone it easily so I can work on it.

**Comment by memsharded** [comment]
> That gets it from a path, right? I'm looking to get the URL from a reference instead. I'm not looking for the URL of the current package. I'm looking for the URL from a package that is on the remote

yes, ``conan graph info --requires=mypkg/version --format=json > graph.json`` will get you this information, just need to access to node ``1`` instead of the ``0`` one.

**Comment by devlpr** [comment]
Ok, so it's similar to what I was doing. A convenience function for this would be really nice. `conan url REF` or `conan url path` for instance. But I can get by with graph info.

**Comment by devlpr** [comment]
Thanks for the responses. I really appreciate it.

**Comment by memsharded** [comment]
>  A convenience function for this would be really nice. conan url REF or conan url path for instance. But I can get by with graph info.

We will explore this as part of the ``workspace`` feature. The main focus would be to use the ``conandata`` ``scm`` information stored accordingly to https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html, and then a single Conan command can do both clone the code and checkout the necessary commit to work on any specific version.

**Comment by devlpr** [comment]
Nice! Thanks for this!

**Comment by devlpr** [comment]
Can you make sure it will also just give the URL without clone or checkout?
