### ISSUE TITLE
Redesign SystemPackageTool interface

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1659]
From the addition of Chocolatey to SystemPackageTool (https://github.com/conan-io/conan/pull/1657), which could break existing recipes, I think there is something a bit weird in SystemPackageTool

The thing is that it can be used as:

```python
pack_name = "some_pkg"
installer = SystemPackageTool()
installer.install(pack_name)
```
That will try to use a different system package manager in every platform, like apt in debian, yum, pkgutil.... And will fall back to the ``NullTool`` if not existing. For example in Windows, and the above code will be a no-op in Windows.

So adding Chocolatey as another tool for Windows had potential to break things.

Typically the complexity of the decission to install a package is given on the previous package name selection:

```python
pack_name = None
    if os_info.linux_distro == "ubuntu":
        if os_info.os_version > "12":
            pack_name = "package_name_in_ubuntu_10"
        else:
            pack_name = "package_name_in_ubuntu_12"
    elif 
```

Maybe it makes more sense something like:

```python
def system_requirements(self):
      apt.install(<some pkgs>)
      yum.install(<some pkgs>)
      choco.install(<some pkgs>)
```
So extensibility is under user control. The above will be no-ops if the system it is running doesn't support that package managers.

Wdyt? @uilianries @sixten-hilborn @lasote

**Comment by uilianries** [comment]
@memsharded Thanks for think about redesign `SystemPackageTool`. I agree, we have a big number of variations by platform, package manager, os version ... The explicit name by helper should solve a future case involving an new optional package manager. Also, only some them are native (e.g. apt), but we don't have complete sure about if is installed, is a out of edge case, but is possible to use a tidy distro, without the package manager installed.

What will happen with the current interface? I mean, if you chance `SystemPackageTool` to don't solve the package manager, you could break many recipes. My question is, how to preserve the current behavior and extend to use a explicit mechanism?

For now we have:
```python
choco = SystemPackageTool(runner=self.runner, os_info=OSInfo(). tool=ChocolateyTool())
choco.install(<package>)
```
`OSInfo` and `runner` are not really required, but is just for the example. Do you think about to create a new simple interface? Maybe like this:

```python
choco = ChocoPackageTool(runner=self.runner)
choco.install(<package>)
```
Again, `runner` could be optional, if it is null, then a new `ConanRunner` is created.

Regards.

**Comment by lasote** [comment]
I agree with the @memsharded and about keeping the old interface compatibility @uilianries . And of course, changing the docs to only show the new way

**Comment by sixten-hilborn** [comment]
I think the problem is that `SystemPackageTool` doesn't fail if no package manager is found (e.g. it falls back to the `NullTool`). Removing `NullTool` and simply fail if no package manager is found would allow extending `SystemPackageTool` for new package managers/distros etc. in the future, without requiring Conan package developers to know about every possible future/current package manager for every system.

As a transition a new flag can be added and deprecate setting it to `True`:

    installer = SystemPackageTool(allowMissingTool=True/False)

**Comment by memsharded** [comment]
No, I am not saying about removing ``NullTool``, nor failing. Also, maybe it is very optimistic that the code will be so general that new system package managers can be plugged and existing recipes would work. In fact, from what I see, the ``SystemPackageTool`` calling is preceded by something like:

```python
 if os_info.linux_distro == "ubuntu":
        if os_info.os_version > "12":
            pack_name = "package_name_in_ubuntu_10"
        else:
            pack_name = "package_name_in_ubuntu_12"
    elif 
```
So maybe there is no way this would work when new system package managers are added in the conan internal code. I feel that the abstraction would be good only if it also abstracted the mappings from packages to the specific names in concrete package managers, but for that a very complete database would be necessary, and it is out of scope.

**Comment by sixten-hilborn** [comment]
Yes it's hard/not feasible to map a dependency to all possible names in all package managers, so it's better to implement the dependency as a Conan package (if possible). :)
Using `installer.install(["package_name_in_ubuntu_12",  "package_name_in_ubuntu_10"])` may increase the chances that it will work with a new manager in the future though.

I don't like that `.install` can fail without an error when the recipe obviously requires that dependency. Failing during build because of the missing dependency can take longer to troubleshoot or (worst case) the package is silently built without it.

**Comment by SSE4** [comment]
that's reasonable addition, because anyway packages have different naming across distribution, and you already shall have code like that:
```
if os_info.linux_distro == "debian":
    installer.install("libfreetype-dev")
elif os_info.linux_distro == "centos":
    installer.install("freetype-devel")
```
and it will be much more explicit to use then:
```
if os_info.linux_distro == "debian":
    apt.install("libfreetype-dev")
elif os_info.linux_distro == "centos":
    yum.install("freetype-devel")
```

**Comment by weatherhead99** [comment]
I've been using the SystemPackageManager tool in anger recently, and I think that at least in the specific case of debian based vs redhat based package naming (or e.g. fedora or suse which have specific shared library package naming conventions) it would be possible and useful to automate some of this, e.g. have a "devel_package_suffix" field in OSInfo or similar as a start. 

My feeling is that I would rather see more generic rather than specific solutions. Cross platform packages are already high friction, and this is the kind of thing where a sensible default can cover a very large portion of cases I think.

**Comment by yangcha** [comment]
> From the addition of Chocolatey to SystemPackageTool (#1657), which could break existing recipes, I think there is something a bit weird in SystemPackageTool
> 
> The thing is that it can be used as:
> 
> ```python
> pack_name = "some_pkg"
> installer = SystemPackageTool()
> installer.install(pack_name)
> ```
> 
> That will try to use a different system package manager in every platform, like apt in debian, yum, pkgutil.... And will fall back to the `NullTool` if not existing. For example in Windows, and the above code will be a no-op in Windows.
> 
> So adding Chocolatey as another tool for Windows had potential to break things.
> 
> Typically the complexity of the decission to install a package is given on the previous package name selection:
> 
> ```python
> pack_name = None
>     if os_info.linux_distro == "ubuntu":
>         if os_info.os_version > "12":
>             pack_name = "package_name_in_ubuntu_10"
>         else:
>             pack_name = "package_name_in_ubuntu_12"
>     elif 
> ```
> 
> Maybe it makes more sense something like:
> 
> ```python
> def system_requirements(self):
>       apt.install(<some pkgs>)
>       yum.install(<some pkgs>)
>       choco.install(<some pkgs>)
> ```
> 
> So extensibility is under user control. The above will be no-ops if the system it is running doesn't support that package managers.
> 
> Wdyt? @uilianries @sixten-hilborn @lasote

@memsharded, I think we could use a dict to map the OS(with version) to the packages to install, such as:
```
install({'ubuntu_x64:12', [<some pkgs>], 'centos_x64:6', [<some pkgs>]})
```
One thing I am not comfortable about conan is that there is no unified or it is hard to get the information of OS.  If there is a conan command "conan system inspect", which show the system information, and first item shows the system OS and version in a string such as 'ubuntu_x64:12'. This string will be used as the key of the dict.

**Comment by brianthelion** [comment]
You have not asked for my advice, but as a conan user and outside observer to the design process, I can't help but feel that the very idea of the `SystemPackageTool` is wrongheaded. The spectre of a giant, hand-coded `if ... else` tree involving distros, package names, versions, and other terrible things is the sign of a broken model. Plus, it opens the door to the user wanting -- and then *"needing"* -- to marshal general system configuration from within the conanfile. This is bad for conan.

The alternative is to offload this burden to an existing tool that's designed to handle precisely this kind of terribleness. I, personally, would love to see conan just call out to `salt` or `ansible` and be done with it. The artifacts necessary to make that happen (which also happen to be called "recipes" in the case of `salt`) can be easily stored and versioned alongside their conan counterparts. For simple system requirements, though, a multi-line yaml string in the conanfile will probably get the job done.

Will the naive conan user be annoyed that they have to learn some opaque DSL to add simple system requirements? Sure, but they'll thank you later.

**Comment by lasote** [comment]
**Approved a behavior change for 2.0:**

It should by default, if it needs to install a system requirement: fail with a message "missing package XXX, run 'apt install....'". 
Only optin by the conan.conf, enable the automatic installation

**Comment by tvogel** [comment]
> > ```
> > def system_requirements(self):
> >       apt.install(<some pkgs>)
> >       yum.install(<some pkgs>)
> >       choco.install(<some pkgs>)
> > ```
> > 
> > 
> > So extensibility is under user control. The above will be no-ops if the system it is running doesn't support that package managers.

Be aware that there is the possibility that multiple package managers are available on a given system. Yes, there might be a primary one but there could be both `zypper` and `apt` on an openSUSE system (https://software.opensuse.org/package/apt).
So, to me, explicit dependency on the distribution makes sense.

**Comment by memsharded** [comment]
Starting to think about this seriously for 2.0. 

I'd like feedback (@lasote @czoido @franramirez688 ) about possible UIs:

Using magic member objects that will automatically enable/disable based on current active manager:
```python
def package_info(self)
     mgr = SystemPackageManager(self)
     mgr.yum.add_repository(...)
     mgr.yum.install("pkg1", "pkg2", ...)
     mgr.apt.install("pkg1-dev", ....)
```
Pros:
- Simple interface, only 1 import
Cons:
- Implementation seems a bit dirtier

Using the package manager name as first attribute
```python
def package_info(self)
     mgr = SystemPackageManager(self)
     mgr.add_repository("yum", "repo...", ...)
     mgr.install("yum", "pkg1", "pkg2", ...)
     mgr.install("apt", "pkg1-dev", ....)
```
Pros:
- Simple interface, only 1 import
- Allows "magic" (like loading the "yum", "apt" tools dynamically from a user plugin or whatever)
Cons:
- Implementation a bit less straightforward

Direct invocation of the tool (that would enable/disable itself based on the current active manager):
```python
def package_info(self)
      Apt(self).add_repository("repo...")
      Yum(self).install("pkg1", "pkg2", ....)
```
Pros:
- Very explicit and pythonic
- Scales easily, users can just use any python_require code to extend
Cons:
- Require a specific class, making it public, doing the ``import``

For all the above the UI for defining the system is:
- Have a default table mapping from the current distro to the default system package manager in that distro ("debian" => "apt")
- Allow the user to specify a ``tools:system_package_manager=apt`` configuration that forces the enabling of that package manager, overriding the default mapping.
- We might want to future-proof this, and allow multiple managers enabled ``tools:system_pakage_manager=apt, yum``.
