### ISSUE TITLE
[question] What is the recommended way to read environment variables

### ISSUE THREAD

**Issue by KingKiller100** [conan-io/conan#16599]
### What is your question?

Conan version: 1.64.1
OS: Windows 11

Hi, I'm confused on how we're meant to read environment variables from the machine we're running on and/or profiles used to install the package. I know the `conans.tools` module has an `get_env()` function designed to do so but I've noticed that the `conan.tools.env` module exists too. Since its in the `conan` module space, I assume that is the library we're meant to use. But upon testing inside of a terminal, I couldn't get the `Environment().vars(self).get()` to work like I needed.

What is the recommended way to read environment variables?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @KingKiller100, thanks a lot for your question. The general recommendation would be to just follow normal Python rules, and read env variables from `os.environ`

A few more extra things:

- The `get_env()` function, while a nice utility, has been made private in Conan 2, so using it will most likely lead to more issues in the future once you port to Conan 2
- The recommended way to set and read variables would be thru the profiles, with the  [buildenv](https://docs.conan.io/2/reference/config_files/profiles.html#buildenv) and [runenv](https://docs.conan.io/2/reference/config_files/profiles.html#runenv) sections (Conan 2 docs, but the idea still aplies in Conan 1), which you can then [use the apply method as documented here of EnvVars](https://docs.conan.io/2/reference/tools/env/envvars.html#applying-the-environment-variables) to get that information. (You would need to instantiate the `VirtualRunEnv`/`VirtualBuildEnv` generators)

Let me know if this helps :)

**Comment by KingKiller100** [comment]
Thank you for responding @AbrilRBS. This information has been very helpful. I thought the `conan.tools.env.Environment` type was a direct replacement for the `conans.tools.get_env()` method. I will use `os.environ` from now on.

It is good to know that the profile can support the addition of a build/run environment section now. Is it possible to add this via cli as well? like a `conan install -pr [profile] -s runenv.[envvar]=[value] .`?

**Comment by AbrilRBS** [comment]
Sorry for the delay!

> Is it possible to add this via cli as well? like a conan install -pr [profile] -s runenv.[envvar]=[value] .?

This would not be directly possible as part of the Conan cli. But profiles in Conan 2 (And Conan 1 if you use the `.jinja` extension) are Jinja templates that get rendered when Conan loads your profiles, which allow you to programatically set environment variables as needed, check https://docs.conan.io/2/reference/config_files/profiles.html#profile-rendering

Happy to solve any further questions if needed

**Comment by memsharded** [comment]
Closing this as responded, but please don't hesitate to re-open or create new tickets for any further question. Thanks for your feedback.
