### ISSUE TITLE
[question] Why is self.settings_target None ?

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [conan-io/conan#16592]
### What is your question?

Hi, im trying to cross compile to aarch64 from an x86_64 machine.

https://docs.conan.io/2/examples/cross_build/toolchain_packages.html

according to the documentation, my self.run should show the same value as self.settings.arch
but instead it shows 
```
demo/1.1.1: RUN: uname -m
x86_64

# print(self.settings.arch)
armv8
```

and self.settings_target is none 

So my question is as follows: is the documentation outdated or am I doing something wrong ?

This is not a blocking problem for me as I found out I can just use conan.tools.build.cross_building.

Here is the command I used

```conan create . -v -pr:h ../profiles/docker-aarch64```

here are my profiles
```
>conan profile show -pr:h ../profiles/docker-aarch64 
Host profile:
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
[buildenv]
CC=aarch64-linux-gnu-gcc
CXX=aarch64-linux-gnu-g++
LD=aarch64-linux-gnu-ld
AR=aarch64-linux-gnu-ar
RANLIB=aarch64-linux-gnu-ranlib

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
```

here is my conanfile.py
```
from conan import ConanFile
from conan.errors import ConanInvalidConfiguration

class DemoRecipe(ConanFile):
	name = "demo"
	version = "1.1.1"

	package_type = "library"
	settings = "os", "compiler", "arch", "build_type"
	options = {"shared": [True, False]}
	default_options = {"shared": False}

	def validate(self):
		self.run("uname -m")
		print(self.settings.arch)

		if self.settings_target is None:
			raise ConanInvalidConfiguration("Target doesn't exist")

	def build(self):
		pass
```

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Marc-Pierre-Barbier 

Thanks for your question.

The ``settings_target`` is only defined for ``tool_requires`` in the "build" context. 
When you are building a package with ``conan create`` that means that you need to pass the ``conan create . --build-require`` to specify that. If you are building it as a dependency it wouldn't be an issue, because it would be already in the "build" the context.

Can  you please try that and let me know?

**Comment by Marc-Pierre-Barbier** [comment]
It works perfectly now. Thank you very much.
