### ISSUE TITLE
[question] Using deployers to get Conan package binaries without invoking Conan generators

### ISSUE THREAD

**Issue by akielbas** [conan-io/conan#16604]
### What is your question?

Is it possible to run a deployer (one of the built in ones or a custom one) without invoking the Conan generators which leave behind batch/shell scripts?
I was hoping to perhaps do it with `conan graph info`, should that be possible?

When I tried it I got this error:
```
conan graph info --requires pkgname/1.0.0@user -pr some_profile_name --deployer direct_deploy --deployer-folder ouput

======== Computing dependency graph ========
Graph root
    cli
Requirements
    pkgname/1.0.0@user#895e04e18fb5e3aa1b6286c29aa3fa80 - Cache

======== Computing necessary packages ========
Requirements
    pkgname/1.0.0@user#895e04e18fb5e3aa1b6286c29aa3fa80:371a22c2b9e66d5b4accfc1db2771e91a2455b72#20e0ca5d38f2598f7c3157c3c6dc0333 - Cache
cli: Conan built-in pkg deployer to ouput\direct_deploy
ERROR: full_deploy: The copy of 'pkgname/1.0.0@user' files failed: expected str, bytes or os.PathLike object, not NoneType.
You can use 'tools.deployer:symlinks' conf to disable symlinks
```

I am running Conan 2.4.1 on Windows

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @akielbas 

Thanks for your question.

``conan graph info`` only constructs the graph, but doesn't fetch, install, download or build binaries. The package binaries will not be there. Then, it cannot be used with deployers that expect to be able to deploy binaries, and I think this is the case of ``full_deploy`` and ``direct_deploy`` built-in deployers.

It is the built-in VirtualXXXEnv generators that generate some shell/bat scripts, and these generators are called implicitly. If you want to deactivate them, at this moment it is possible to do it in the consumer ``conanfile.py`` ``generate()`` method, just by instantiating them with ``VirtualBuildEnv(self)`` without calling their ``.generate()`` method. There is pending a feature request to have a conf to disable the generation of these scripts, but it didn't get prioritized enough yet.

**Comment by akielbas** [comment]
Makes sense, thanks.

Just making sure, if I download the package into the local cache with `conan download` ahead of time, the package folder still won't be available to `conan graph info` right?

**Comment by memsharded** [comment]
> Just making sure, if I download the package into the local cache with conan download ahead of time, the package folder still won't be available to conan graph info right?

Correct, even if the package is already in the cache, the ``conan graph info`` does not even compute the ``package_folder`` of the binary, as if it wouldn't exist in the cache, as it would be inconsistent and problematic to have a package folder defined for some packages and not other, just because of the state. If access to packages is desired, it should be ``conan install`` instead (as packages must be installed).

**Comment by memsharded** [comment]
Closing this question as resolved, but please don't hesitate to re-open or create new tickets if you have any further question or issue. Thanks.
