### ISSUE TITLE
[question] Help correctly translating Conan 1 code.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16626]
Hello,

How do I translate this Conan 1 code:
```python
        if self.settings.compiler == "msvc":  #--> in Conan 1 it was "Visual Studio"
            if self.settings.build_type == "Debug":
                self.settings.compiler.runtime = "MDd" if self.options.shared == True else "MTd"
            else:
                self.settings.compiler.runtime = "MD" if self.options.shared == True else "MT"
```
to Conan 2 so it achieves the same effect?  Running this in Conan 2 results in this error:
```bash
        self.settings.compiler.runtime = "MD" if self.options.shared == True else "MT"
        ConanException: Invalid setting 'MD' is not a valid 'settings.compiler.runtime' value.
Possible values are ['static', 'dynamic']
```
The problem is that in Conan 1 there are four possible values (dynamic/release; dynamic/debug; static/release; static/debug) and now only two are allowed.  So, how do I achive the same effect of the Conan 1 code in Conan 2 terms?  I believe I'll need to use a combinantion of two attributes but I don't know which to use for the debug/release option in this case.

thank you,

PC

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @PauloCarvalhoRJ thanks a lot for your question.

I don't belive this is necessary in Conan 2, as the [default profile loader plugin](https://github.com/conan-io/conan/blob/b0d916f1324325c2c27c39f1580953c4d5337c06/conans/client/profile_loader.py#L35) will automatically handle the debug/release variants based off of your `build_type`. Either way, the subsetting you would be looking for is `compiler.runtime_type`, which allows `Release/Debug` values (As seen [in the `settings.yml` documentation](https://docs.conan.io/2/reference/config_files/settings.html)) 

Hope this helps :)

**Comment by PauloCarvalhoRJ** [comment]
Hello, @AbrilRBS ,

Nice catch.  The `settings.yml` has every option there, I believe.  It's a Qt recipe which is complex.  There are lots of conditionals like that.

Thank you,

PC
