### ISSUE TITLE
[question] How to set version ranges in Conan 2?

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16627]
Hello,

So, I have this in a recipe that used to work in Conan 1:
```python
    requires = [ "python3/[3.10.*]" ]
```
Which gives this error in Conan 2:
```bash
Package 'python3/[3.10.*]' not resolved: Version range '3.10.*' from requirement 'python3/[3.10.*]' required by 'qt5/5.15.9' could not be resolved.
```
Given I already have a working `python3/3.10.11` package, if I set `requires = [ "python3/3.10.11" ]` the recipe works.

How do I achieve the same functionality in Conan 2?

thanks,

PC

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
HI @PauloCarvalhoRJ 

As shown in [this sectrion of the tutorial](https://docs.conan.io/2/tutorial/versioning/version_ranges.html#range-expressions) and [the requires reference docs](https://docs.conan.io/2/reference/conanfile/attributes.html#requires), the syntax for version ranges is based on comparison operators, a standard way to describe version ranges.

Our recommendation would in fact be to use the `python3/[>=3.10 <3.11]` syntax, as that's what's more evidently obvious for developers across the board, even if there exist shorthand versions to express the same version range (`python3/[~3.10]` in this case)

Let me know if this helps :)

**Comment by PauloCarvalhoRJ** [comment]
Ok!  Thank you.  What if the version has letters in it?  For example, I have a package named `openssl/1.1.1c`.

**Comment by PauloCarvalhoRJ** [comment]
> Ok! Thank you. What if the version has letters in it? For example, I have a package named `openssl/1.1.1c`.

Never mind.  It's covered in the tutorial.

**Comment by PauloCarvalhoRJ** [comment]
> HI @PauloCarvalhoRJ
> 
> As shown in [this sectrion of the tutorial](https://docs.conan.io/2/tutorial/versioning/version_ranges.html#range-expressions) and [the requires reference docs](https://docs.conan.io/2/reference/conanfile/attributes.html#requires), the syntax for version ranges is based on comparison operators, a standard way to describe version ranges.
> 
> Our recommendation would in fact be to use the `python3/[>=3.10 <3.11]` syntax, as that's what's more evidently obvious for developers across the board, even if there exist shorthand versions to express the same version range (`python3/[~3.10]` in this case)
> 
> Let me know if this helps :)

Thank you, it works.  I believe that new version range syntax can result in more accurate version conditionals.

best,

PC
