### ISSUE TITLE
self.cpp_info.bindirs is not working [bug]

### ISSUE THREAD

**Issue by wizard-123** [conan-io/conan#16632]
### Describe the bug

I want to create a conan version of saribbon. In conanfile.py's package_info function, I use self.cpp_info.bindirs=["bin"]. But when I used it, I found that in the saribbonbar-release-x86_64-data.cmake file, saribbonbar_BIN_DIRS_RELEASE is set to empty (set(saribbonbar_BIN_DIRS_RELEASE)). windows system and conan version 2.5.0

**Comment by memsharded** [comment]
Hi @wizard-123 

We would need more details about this, and a way to reproduce it (full conanfile, exact commands that you are using and the output of the commands). 
It is very likely that it is related to package types, requirement traits and propagation of dependencies information (e.g. ``requires`` a static library does not provide ``bindirs`` information to the consumers).

**Comment by wizard-123** [comment]
Sorry，is my fault, I missed a parameter and setting shared to True just worked
