### ISSUE TITLE
[question] What is the replacement for `AutoToolsBuildEnvironment` in Conan 2?

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16630]
Hello,

I have a Conan 1 recipe with the following code:
```python
    def _get_env_build(self):
        if not self._env_build:
            self._env_build = AutoToolsBuildEnvironment(self)
            if self.settings.compiler == "apple-clang":
                self._env_build.flags.append("-arch %s" % tools.to_apple_arch(self.settings.arch))
                self._env_build.flags.append("-isysroot %s" % tools.XCRun(self.settings).sdk_path)
                if self.settings.get_safe("os.version"):
                    self._env_build.flags.append(tools.apple_deployment_target_flag(self.settings.os,
                                                                              self.settings.os.version))
        return self._env_build
```
So, what are the guidelines to port that to Conan 2?

thank you,

PC

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PauloCarvalhoRJ 

Mostly the GNU tools in https://docs.conan.io/2/reference/tools/gnu.html
All build system integrations in Conan 2 follow the same approach ``XXXToolchain`` + ``XXXDeps``. In this case ``AutotoolsDeps`` doesn't work well in Windows, and ``PkgConfigDeps`` can be a better recommended alternative for Windows, or custom integrations, depending on the package.

You have other resources:
- https://docs.conan.io/2/examples/tools/autotools/create_your_first_package.html#examples-tools-autotools-create-first-package
- https://docs.conan.io/2/examples/tools/autotools/create_your_first_package_windows.html

**Comment by PauloCarvalhoRJ** [comment]
Hello,

Thanks for the reply.  That code is part of the `openssl/1.1.1c` recipe I have, which is configured and built with Autotools.  So, even in Windows I'll need Autotools.  Hence, I guess I'll have to stick to `AutotoolsDeps`.

best,

PC

**Comment by memsharded** [comment]
But ``AutotoolsDeps`` doesn't work in Windows, you cannot use it for that, it is documented.

Note the recipe in ConanCenter: https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/3.x.x/conanfile.py does not use ``AutotoolsDeps``, but directly get the ``zlib`` from ``self.dependencies`` and inject it in the recipe.

**Comment by PauloCarvalhoRJ** [comment]
Hmmm... why does it instantiate an `AutotoolsToolchain` in its `generate()` callback?

**Comment by PauloCarvalhoRJ** [comment]
Thank you, I don't know for sure whether this was solved, but now I'm getting an error elsewhere in the `openssl/1.1.1c` recipe.  So I'm closing this for now.
