### ISSUE TITLE
Skip uploads when there are no changes

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1663]
Right now, when generating new recipes or packages, the timestamp of the conanmanifest causes an upload of just that file, which is not necessary. cc/ @tru

**Comment by lasote** [comment]
Maybe makes sense to not write again the `conanmanifest.txt` if it's the same. `export.py`:64

**Comment by memsharded** [comment]
It can happen in a clean machine. Just git clone + export, and the files will be the same.

**Comment by lasote** [comment]
So, what?
