### ISSUE TITLE
version 2.4.0 conan install with --deployer=full_deploy [bug]

### ISSUE THREAD

**Issue by wizard-123** [conan-io/conan#16631]
### Describe the bug

use conan install . --deployer=full_deploy , there will create a conan_toolchain.cmake file, in conan_toolchain.cmake file
`list(PREPEND CMAKE_MODULE_PATH "\${CMAKE_CURRENT_LIST_DIR}/full_deploy/...`
but not
`list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/full_deploy`

**Comment by czoido** [comment]
Hi @wizard-123,
Thanks a lot for reporting, this was indeed a bug in 2.4.0 but was fixed in 2.4.1 after merging this: https://github.com/conan-io/conan/pull/16434
Please, update to 2.4.1 or 2.5.0 to solve it.

**Comment by wizard-123** [comment]
thanks，update to 2.5.0 solve it
