### ISSUE TITLE
[question] What is the replacement for Conan 1's `tools.which()`?

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16640]
Hello,

I have a Conan 1 recipe with a call to `tools.which(...)`, which runs the `which` command in POSIX OSes.  Searching "which", "which function", "which command", etc. in Conan 2's docs returns a lot of unwanted stuff, evidently since "which" is a rather common word.  The search also ignores the usage of double quotes which is supposed to force two or more terms to be close together.  So, does anyone know from the top of one's head how I port that call to Conan 2?

thank you,

PC

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PauloCarvalhoRJ 

``which`` became a Python utility: https://docs.python.org/3/library/shutil.html

Also, it should be less and less necessary in Conan 2 to do an explicit ``which`` in recipes, and it is recommended to have more explicit and imperative definitions of what to do. What are the binaries you are locating via ``which`` and why?

**Comment by PauloCarvalhoRJ** [comment]
Hello,

Here:
```python
            if not self.options.no_asm and not tools.which("nasm"):
                self.build_requires("nasm/2.13.01")
```
This code tests whether the user **wants `nasm`** and whether `nasm` is **not already available** in the system. If so, the recipe adds `nasm` as a requirement.   Minimizing explicit calls like that and maximizing usage of Conan automation is ideal, but we must keep an open mind to some oddities out there.  Legacy software being the most common sources.  Assuming `shutil.which()` has the same behavior as that of the old `tools.which()`, I don't expect any problems.

Thank you,

PC

**Comment by memsharded** [comment]
>   if not self.options.no_asm and not tools.which("nasm"):
                self.build_requires("nasm/2.13.01")

Exactly this is not expected anymore in Conan 2. A better approach would be:
- Define ``self.tool_requires("nasm/version")`` irrespective of the ``which()``.
- Let users that want to use a system installed nasm to define ``[platform_tool_requires]`` to use their system ``nasm``.

I understand that while upgrading to Conan 2 using a ``shutil.which`` will help, I am just pointing the long term Conan-2-only possible approach.

**Comment by PauloCarvalhoRJ** [comment]
Thank you.  I added a FIXME comment in the recipe with the URL of your post.
