### ISSUE TITLE
[question] How to disable generating of the excess files from export-pkg

### ISSUE THREAD

**Issue by forry** [conan-io/conan#16650]
### What is your question?

Hi,
how does one tell the `conan export-pkg` not to generate any of those .bat files? 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Note that in general the generated files are needed, if any ``[tool_requires]`` is injected in the profile that define any tool that the ``package()`` method will run, either these files are generated or it won't work. 

If you know for sure that this will never happen and want to deactivate it, you can add to the recipe a instantiation of ``VirtualBuildEnv(self)`` and ``VirtualRunEnv(self)`` calls in the ``generate()`` method, without calling their ``.generate()`` methods.

**Comment by forry** [comment]
Maybe a dumb question but why isn't that rather an opt-in?

**Comment by memsharded** [comment]
Because it is necessary, recipes cannot anticipate if users of the recipe will want to inject ``tool_requires`` from their profile, so they should work by default, so the generation of those env scripts by default is necessary for things to work in the general case.
