### ISSUE TITLE
[question] How to improve conan performance?

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#16652]
### What is your question?

When running `conan install` of an app with a large number of dependencies, it takes a *very long time* to calculate the dependencies and generate the output. Furthermore, since we need to do this three times (Release, RelWithDebInfo, and Debug), it takes even longer.

Here is the timing output of one such installation, while having everything already in cache (i.e. no downloads were needed from the Artifactory server):

```
$ time conan install . -pr emscripten-3.1.57-advanced -pr:b macos-ninja-arm64-clang-15.0.0 -s build_type=Release

real    0m38.607s
user    0m37.488s
sys     0m0.542s
```

Now, do this three times (Release, RelWIthDebInfo, Debug), and it takes 

```
$ time conan project ninja -pr emscripten-3.1.57-advanced --install-only

real    2m11.346s
user    2m7.001s
sys     0m2.133s
```

(side note: `conan project` is our custom command that installs all three build types and automatically detects the correct build profile from the active environment - but it basically invokes `conan install` three times, using the Conan Python API)

This is a very long wait, especially on a CI system that needs to do this on every build... The project in the example has 73 dependencies and 61 build dependencies listed in its lockfile.

Most of the time is spent after the message "Computing dependency graph" is printed, and I see a single CPU core hogged at 100%.

My questions are:

- would it be possible to compute the dependency graph by using some parallel algorithms that would better use the available multiple-core CPU?
- is there a way to install both Release, RelWithDebInfo, and Debug versions of packages "in a single run", thus saving the time required to compute the graph?
- is there any way I could profile conan to see which parts are the "hottest" and should be prioritized for optimizations?

I'm currently using conan v2.5.0.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DoDoENT 

Quick question, if all the dependencies are local, can you please try adding ``--no-remotes`` to the commands above and report the results?

I guess we are talking about latest Conan 2.5, is this correct?

**Comment by DoDoENT** [comment]
Yes, conan v2.5.0:

Here is the release-only timed installed with added `--no-remote`:

```
$ time conan install . -pr emscripten-3.1.57-advanced -pr:b macos-ninja-arm64-clang-15.0.0 -s build_type=Release --no-remote


real    0m39.635s
user    0m38.148s
sys     0m0.659s
```

**Comment by DoDoENT** [comment]
I made sure that I had all dependencies downloaded and built before making this question/perf-bug report. Of course, when conan needs to download and/or build dependencies, it takes even longer, but that is expected...

**Comment by memsharded** [comment]
Can  you please report with ``--format=json > graph.json`` what is the size of the dependency graph being resolved?

**Comment by DoDoENT** [comment]
[graph.json.zip](https://github.com/user-attachments/files/16174625/graph.json.zip)
 I've zipped the JSON because the raw JSON is 71 MB large.

**Comment by memsharded** [comment]
The dependency graph you are resolving contains around 13450 nodes. 
At 40 seconds of resolution it brings an average of 3ms to evaluate each node on the graph.
Given that there are quite costly operations to do, including loading and parsing python files, loading conandata yml files, propagation of dependencies in the dependency graph, etc, this is not bad.

It is important to note that parallelization of the graph resolution is quite challenging and introduce fragility and issues. We are continuously trying to improve the performance of Conan, but this goes slowly, step by step. Last attempt to paralelize some things had to be reverted because of being problematic.

I'd say that it might be possibilities to optimize the size of the graph, for example, it seems that the explosion of the graph size is due to recursive tool/test requires. Maybe doing something like https://blog.conan.io/2024/07/09/Introducing-vendoring-packages.html can highly reduce the size of the graph.

**Comment by DoDoENT** [comment]
OK, I thought so...

I'll see if there is a way to help myself with vendoring...

And, what about this question?:

> is there a way to install both Release, RelWithDebInfo, and Debug versions of packages "in a single run", thus saving the time required to compute the graph?

**Comment by DoDoENT** [comment]
Since graph computation is expensive, maybe if done "single time" instead of being repeated for each build type, the total project initialization could be much faster?

**Comment by memsharded** [comment]
There are conditional requirements to the ``build_type`` (and other settings), this is not possible because the dependency graph is often different for different settings, so caching and reusing graphs is unfeasible.

**Comment by DoDoENT** [comment]
I know it's possible to have different dependencies based on the `build_type`, but assuming this rarely happens, only a small amount of nodes would have extra expansions due to different build_types, so overall most of the nodes would be the same for all build types, which can then be reused when doing the graph computation and thus save time?

Or is this difficult to achieve with the current conan architecture?

**Comment by memsharded** [comment]
There has been a few related changes in the last Conan versions:

- New confs like ``tools.graph:skip_test`` and ``tools.graph:skip_build`` to fully skip test or build dependencies respectively
- The new ``vendor=True`` feature.
- Several optimizations in the graph resolution


We will keep focusing on performance as a continuous effort, we already have some further possible optimizations. I am closing this question as responded, thanks for the feedback!
