### ISSUE TITLE
[question] What is a launcher in Conan 2 context?

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16655]
Hello,

Reading here: https://docs.conan.io/2/reference/tools/microsoft/vcvars.html#conan.tools.microsoft.VCVars.generate one finds the following text:

> Parameters:
> scope – str Launcher to be used to run all the variables. For instance, if build, then it’ll be used the conanbuild launcher.
> 

What is a "conanbuild launcher"?  I couldn't find it by searching the Conan 2 docs.  Anyway, what is a launcher?

thanks,

PC

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
The launcher is another name for the env-vars scripts, the ``conanbuild`` launcher is nothing but the ``conanbuild.bat`` script, that is automatically used by ``self.run()``

**Comment by PauloCarvalhoRJ** [comment]
Ok.  Perhaps the docs are due some clarity improvement, then.

**Comment by PauloCarvalhoRJ** [comment]
I would close this, but I guess this will be closed automatically when Conan 2.6.0 hits the road.

**Comment by memsharded** [comment]
It is open so we update the docstrings that generate these docs, it is pending a PR to fix it. Thanks for following up.
