### ISSUE TITLE
[question] Overriding build requirements

### ISSUE THREAD

**Issue by Drllap** [conan-io/conan#16654]
Hi
Is it possible to override build requirements?
I'm trying to use `proj/9.4.1`. I'm trying to build it for x86 Windows.
When I run `conan install . --build missing` I get the following error:
```
Build requirements packages
    cmake/3.30.0:INVALID - Invalid
    jom/1.1.3:11e6a84a7894f41df553e7c92534c3bf26896802 - Cache
 
Cross-build from 'Windows:x86_64' to 'Windows:x86'
Installing (downloading, building) binaries...
ERROR: There are invalid packages (packages that cannot exist for this configuration):
cmake/3.30.0: Invalid ID: CMake binaries are only provided for x86_64 and armv8 architectures
cmake/3.30.0: Invalid ID: CMake binaries are only provided for x86_64 and armv8 architectures
```
If I understand the error correctly it is trying to pull x86 version of cmake to build `proj`. But since I'm building on a machine with x86_64 architecture I should be able to use x86_64 bit version of cmake just fine.

I'm using conan 1.64.1 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Drllap 

Thanks for your question.

The recommended approach when using tool-requires is using the 2 profiles approach. Even if it is Conan 1, this page of the docs in Conan 2 explains better the usage and concepts: https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html

In your case, your "build" profile will have ``arch=x86_64`` while the "host" profile can use another architecture like ``x86`` if you want to build your products for 32 bits arch.

This is passed in command line with something as ``conan install .. -pr:h=profile_x86 -pr:b=profile_x86_64``

Please try that and let us know.

**Comment by Drllap** [comment]
@memsharded Awesome, thanks
