### ISSUE TITLE
[question] How to replace `tools.vcvars()` context manager in Conan 2?

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16653]
Greetings,

So, I have a Conan 1 recipe with the following `build()` callback:

```python
    def build(self):
        unzip(self, filename=os.path.join(self.source_folder, "openssl-{}.tar.xz".format(self.version)))
        rename(self, src="openssl-{}".format(self.version), dst=self._source_subfolder)
        with tools.vcvars(self.settings) if self._use_nmake else tools.no_op():
            env_vars = {"PERL": self._perl}
            if self._full_version < "1.1.0":
                cflags = " ".join(self._get_env_build().flags)
                env_vars["CC"] = "%s %s" % (self._cc, cflags)
            if self.settings.compiler == "apple-clang":
                xcrun = tools.XCRun(self.settings)
                env_vars["CROSS_SDK"] = os.path.basename(xcrun.sdk_path)
                env_vars["CROSS_TOP"] = os.path.dirname(os.path.dirname(xcrun.sdk_path))
            with tools.environment_append(env_vars):
                if self._full_version >= "1.1.0":
                    self._create_targets()
                else:
                    self._patch_makefile_org()
                self._make()
```
According to Conan 1 docs, the `tools.vcvars(self.settings)` call brings to the current environment the environment variables necessary to compile stuff correctly in Visual Studio.  That is equivalent to opening a terminal and issuing `vcvarsall ...` before building.  I've read in Conan 2 docs about the `VCVars` class, but from what I learnt, it only generates a batch file, which is not the same as I need.

The question is, how do I port that call to Conan 2 API?  If a direct port is not possible, how do I achieve the same effect (the usage of VS env vars limited to a Python context) in Conan 2 terms?

Thank you,

PC

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
For Windows you can use the ``VCVars`` new generator, either explicitly in the ``generate()`` method.

Also, some other generators like Autotools, Meson, MSBuild, even CMake for Ninja, will automatically call ``VCVars`` generator to create the ``conanvcvars.bat`` script to do this automatically.

**Comment by PauloCarvalhoRJ** [comment]
Yes, I read about the `VCVars` generator.  But the question was: how do I use it so I achieve the same effect as in the `build()` callback posted in the OP?

**Comment by PauloCarvalhoRJ** [comment]
I mean: in addition to run `vcvarsall.bat`, it also needs to be scoped (the `with` keyword) and conditional (`... if self._use_nmake else tools.no_op()`).

**Comment by memsharded** [comment]
It is automatic. It is just another env-var scripts ``conanvcvars.bat`` that is automatically included in the ``conanbuild.bat`` and the ``conanbuild.bat`` is automatically called by any ``self.run()`` command, including the internal execution of commands of build helper such as ``cmake.configure()`` or ``cmake.build()``.

In the above the ``self._make()`` call will have some ``self.run()`` calls inside and they will inject the vcvars automatically.

**Comment by PauloCarvalhoRJ** [comment]
Ok.  But how do I make it: a) scoped and, b) conditional?

**Comment by memsharded** [comment]
The creation of the ``conanvcvars.bat`` is already conditional to ``msvc`` compiler usage and the necessary other generators. It is mostly automatic in the majority of cases. Then, as other environment based generators, no need to scope anything, no need to do something like ``with tools.environment_append(env_vars):``, the addition of the ``conanvcvars.bat`` is automatic in every ``self.run()``. I am not sure if I understand your questions.

**Comment by PauloCarvalhoRJ** [comment]
Thanks for the feedback.   On a second thought, I gave up porting all the old Conan 1 recipes and decided to adapt the Conan 2 recipes from Conan Center, which seems to be a better approach when it comes to complex, highly customizable recipes such as Qt's and VTK's.

**Comment by memsharded** [comment]
> Thanks for the feedback. On a second thought, I gave up porting all the old Conan 1 recipes and decided to adapt the Conan 2 recipes from Conan Center, which seems to be a better approach when it comes to complex, highly customizable recipes such as Qt's and VTK's.

Sounds good. The recommended approach to maintain custom recipes for third parties is actually by forking ``conan-center-index``, we documented it: 
- https://docs.conan.io/2/devops/using_conancenter.html
- https://docs.conan.io/2/devops/conancenter/hosting_binaries.html
