### ISSUE TITLE
Getting started with conan

### ISSUE THREAD

**Issue by BlueSolei** [conan-io/conan#1666]
I followed the steps [here](http://conanio.readthedocs.io/en/latest/getting_started.html).
The step of running conan (`conan install ..`) failed with an error:

> ERROR: Unable to find 'Poco/1.7.8p3@pocoproject/stable' in remotes

I figured it out to be that the url of conan.io was deprecated (I used conan remote list).
The bad value was: : https://server.conan.io 
I fixed it with:
`conan remote update conan.io https://conan.bintray.com`

I don't really know at which part of the conan installation process this url is set, but if you can fix it for other first time users, it will be great :-)

**Comment by memsharded** [comment]
That is really weird, conan new installations should have bintray already as their default.

Which version of conan were you running? Did you use conan in the past, or is it a fresh, clean installation? How did you installed conan, with pip? Which OS?

Thanks for your feedback!

**Comment by BlueSolei** [comment]
Conan version: Conan version 0.24.0
It was the first time I use it. 
installed with pip.
OS: Win7
Could be it that I installed it some time ago, and only use it now, so maybe that is the issue?

**Comment by memsharded** [comment]
Yes, could be, if you had any previous versions of conan, it already had configured remotes, and conan upgrades do not change those remotes, se there were docs for existing users to migrate: http://docs.conan.io/en/latest/packaging/bintray/move.html

You could re-check by totally uninstalling your conan client, and also completely removing your ``<username>/.conan`` folder. BTW, there is already a 0.25 release, and 0.26 is coming probably tomorrow, please try to update if possible :)

**Comment by Croydon** [comment]
I guess this can be closed. This is a pre-1.0 error which can't happen anymore as conan-center is now via default configured.
