### ISSUE TITLE
[question] ERROR: 'settings.os_build' doesn't exist for 'settings'

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [conan-io/conan#16662]
### Describe the bug

OS: Windows 11
Compiler: MSVC
arch:x85_64
Conan version: 2.5.0

the error goes like this
```
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22631.
-- CONAN_PROFILE_ARCH: x86_64
-- Conan executing: conan install C:/Users/jou/code/cadeau/conanfile.py -pr windows-x86_64 -s os_build=Windows -s arch_build=x86_64 -s build_type=Release -g cmake --build=missing --update
ERROR: 'settings.os_build' doesn't exist for 'settings'
'settings' possible configurations are ['arch', 'build_type', 'compiler', 'os']
CMake Error at cmake/conan.cmake:340 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/ConanHelper.cmake:62 (conan_cmake_install)
  CMakeLists.txt:22 (include)
```

Any hints are apperciated

**Comment by memsharded** [comment]
Hi @irvingoujAtDevolution 

This seems expected. It seems  you are using a legacy ``cmake-conan`` integration for Conan 1.X, for the newest Conan 2.

You might need to check the details of the new integration with CMake dependencies provider (fully transparent, no need to modify CMakeLists.txt at all!) in https://github.com/conan-io/cmake-conan

In this case I see ``settings.os_build`` which was very legacy also within Conan 1.X, that replaced it some time ago for the 2 profiles (build/host) approach, so it looks the ``ConanHelper.cmake`` is something specific and custom on your side.

**Comment by irvingoujAtDevolution** [comment]
I see, thank you, it seems like the project I'm working on expect a different version.
