### ISSUE TITLE
[question] Perform 2-step build and upload to same remote package 

### ISSUE THREAD

**Issue by chulme** [conan-io/conan#16665]
### What is your question?

I am trying to package Doxygen tagfiles (allows different Doxygen builds to link to each other) along with my package binaries, so that I can trivially fetch the tagfiles of a package's dependencies when building documentation. 

My problem is that I must perform parallel C++ builds and documentation builds in different Docker environments ie. Using a C++ build image and a documentation build image. As these must be performed in parallel and in different images, the conan cache shall not be shared.

I'm wondering if this workflow is supported with Conan 2.5:

1. Build C++ package, package the C++ sources, binaries, etc and upload. 
2. Build the documentation, package the documentation sources, documentation output ie. Doxygen tagfile (and potentially the actual built documentation as Conan metadata), upload to same package as step one.

My initial theory is that I will need to use Conan options so that when installing the dependencies, either the dependencies C++ binaries, or the documentation, are built. But I'm not sure how to then perform 2 uploads to the same package. If not supported I suspect I may just need to have 2 different packages living in the remote, depending on the options.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @chulme 

Thanks for your question.

Both recipes and package binaries are immutable, once they are created they cannot be modified. Using different options will result in different ``package_ids`` (different binaries), not the same one. And then depending on the same package, different options simultaneously is not simple.

The only possibility to add some files after a package has been created is using the metadata files, but it doesn't seem your use case at all.

Maybe what you can do is something like:

- Create different packages for the different parts, like ``mypkg_docs``, ``mypkg_tags``
- Have one "aggregator" package that depends on all of them
- This new aggregator package can be built with the "vendor" feature (https://blog.conan.io/2024/07/09/Introducing-vendoring-packages.html) or not, depending on the needs

**Comment by memsharded** [comment]
Hi @chulme 

Any further question or clarification needed here? Thanks for your feedback.

**Comment by chulme** [comment]
Hi @memsharded ,

Thanks for your reply. No further questions from me I'll close this issue 😃
