### ISSUE TITLE
[question] Add new config

### ISSUE THREAD

**Issue by Anchorli** [conan-io/conan#16668]
### What is your question?

Hello

  I am conducting embedded development. How can I add new configs for different cross-build toolchains so that persons in my team can use these configs

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Anchorli 

I think you are looking for the ``conan config install`` and ``conan config install-pkg`` commands:

- https://docs.conan.io/2/reference/commands/config.html#conan-config-install
- https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg
