### ISSUE TITLE
[question] What corresponds to `tools.replace_prefix_in_pc_file()` in Conan 2?

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16667]
Hello,

That's a straight question.  I have a Conan 1 recipe with said call that no longer works in Conan 2.  So, how do I port that call to Conan 2?

thanks,

PC

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PauloCarvalhoRJ 

This function has been removed in Conan 2.

Its usage was not very clear, and the implementation is very straightforward, just a replace of ``prefix=xxxx``, so it can be done in a recipe in a couple of lines with a regex.

If you want to give feedback about the usage of that function, that would be useful (but still unlikely to be restored in Conan 2, but feedback useful anyway).

**Comment by PauloCarvalhoRJ** [comment]
Hello,

I was just looking for a 1-to-1 replacement in Conan 2.  It is part of a Qt 5.15.9 recipe I have.  Given the number of API changes, I'm considering using the one in Conan Center, which seems to be Conan 2.

thanks,

Paulo

**Comment by memsharded** [comment]
> I was just looking for a 1-to-1 replacement in Conan 2. It is part of a Qt 5.15.9 recipe I have. Given the number of API changes, I'm considering using the one in Conan Center, which seems to be Conan 2.

Sure, sounds good, all ConanCenter could be ported to Conan 2 without this function, and the recipe code is minimal in case of needing something like it, this is why it was deprecated and removed.

**Comment by PauloCarvalhoRJ** [comment]
So far, the Conan 2 recipes from Conan Center are working with minimal adaptations taken from my current Conan 1 recipes with custom procedures.
