### ISSUE TITLE
[question] Is Python inheritance allowed or not?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16679]
Hi,

I have seen colleagues doing regular Python inheritance in recipes instead of doing python_requires.
I vaguely recalled that Python inheritance was discouraged back then, but I can't seem to find anything related to this in the documentation. The only thing I've found to state that one should not mix python_requires with Python inheritance.

So. What is the official approach for Conan currently? Can or can't Python inheritance be used?
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for your question

> I have seen colleagues doing regular Python inheritance in recipes instead of doing python_requires.
I vaguely recalled that Python inheritance was discouraged back then, but I can't seem to find anything related to this in the documentation. The only thing I've found to state that one should not mix python_requires with Python inheritance.

Python inheritance is not really forbidden, but it might be discouraged, depending on how it is implemented:

- If the base class is imported together with the ``conanfile.py`` into the recipe, then this is not bad per se. It doesn't provide any type of automatic updates, to do so it would be necessary to do a new ``conan create/export`` with the new base class changes.  But the recipe is self-contained, reproducible, etc, so all good, this is valid.
- If the base class is imported from outside of the recipe, let's say, from a pip-like package, then this is much worse. This breaks the recipes encapsulation and traceability. Changing the base class is completely transparent to the recipes, which can fully change behavior without any kind of trace. In practice, it seems you have a package like ``mypkg/1.0#revision1``, but in reality the behavior of that version and revision can change any time, so the version and revision is worth nothing. Reproducibility is completely broken, you could have a lockfile locking ``mypkg/1.0#revision1``, but as the final behavior of the recipe and pacakage depends on something external, this is not locked or reproducible at all. This would be very discouraged.

This is why the solution with ``python_requires`` is more recommended:
- It is stored in Conan packages, it allows full traceability
- The ``python_requires`` affect the ``package_id`` of the consumers using it, so it is possible to achieve full reproducibility
- It is integrated in Conan, no need to use other mechanism like ``pip``, which has its own problems.

**Comment by harsszegi** [comment]
Awesome, thanks a lot for the clarification @memsharded, closing it!
