### ISSUE TITLE
[question] Is it possible to check if local cache is corrupted? 

### ISSUE THREAD

**Issue by lagner** [conan-io/conan#16670]
### What is your question?

Hi, all!

I'm using conan for building our application on CI, and it's truly great. However, occasionally, I encounter errors such as:
```
ERROR: Corrupted package 'boost/1.84.0+build.247:8c27f9643e3b829f0a867c1ae86ddfefb5f27297' missing conaninfo.txt at: /mnt/Jenkins/workspace/conan-ci/cache/0/.conan2/p/boost975cab8258a69/p/conaninfo.txt
```
or
```
ERROR: Package 'zlib/1.2.13+build.247' unresolved: Error, the file for download is already present: '/workspace/build/.conan2/p/zlib9ca3ef3ffd69b/d/conan_export.tgz'.
```
The cause of these errors is unclear to me. It might be related to some tasks being interrupted, but I'm not sure.

Anyway, I would be happy if I could check that the cache is completely fine before building. My question is, is this possible?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @lagner thanks a lot for your kind words :)

You might want to look into the `conan cache check-integrity` command ([Docs here](https://docs.conan.io/2/reference/commands/cache.html#conan-cache-check-integrity)), which is meant to help in situations like this!

Let me know if this helps. Happy to also help diagnose the corruption if you end up suspecting it's on Conan's side

**Comment by lagner** [comment]
This seems to be what I'm looking for.

Thank you!
