### ISSUE TITLE
[question] How to pass resource file path to consumer?

### ISSUE THREAD

**Issue by s-mlr** [conan-io/conan#16676]
### What is your question?

Hi everybody, 
I face a situation where I build multiple static libraries and ship them as package A. These static libraries will be consumed by package B to create an executable. 
In addition to the static libraries there is additional files required in the artifacts of package A (*.a2l), which support accessing memory locations at runtime (but these specifics don't matter here, just for a better understanding). 
I am utilizing CMakeToolchain and CMakeDeps generator and am looking for a neat way to supply the path to these files to the consuming package B. I am thinking of providing the consumer with a CMake variable ```packageA_a2l_files``` or something similar. I don't want the consumer to have to have specific knowledge about the layout of packageA artifacts.

I played around with following ideas but none of them feels like a really clean design.

1. Create a custom *.cmake file during package() of packageA, which sets the mentioned CMake variable and load the cmake file via declaring in package_info(): ```self.cpp_info.set_property("cmake_build_modules", [f"build_scripts/{self.name}.cmake"])``` 
This approach faces the drawback of having to use knowledge about the package_info in creating the script at an earlier stage already, as well as having to deal with all kinds of path resolutions, which are outsourced to the generators CMakeDeps / CMakeToolchain for a reason.

2. Using ```tools.cmake.cmaketoolchain:extra_variables``` to define the variable via conf_info, which also feels a bit dirty, since this information really is very specific about the layout / description of shipped artifacts of packageA and therefore feels more in the domain of CMakeDeps?

Am I missing the intended way of doing this? Any feedback is highly appreciated.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @s-mlr 

Thanks for your question.

Have you considered using the ``cppinfo.resdirs`` definition? (https://docs.conan.io/2/reference/conanfile/methods/package_info.html). This would be intended for directories containing resource files for consumers.

Then, the only issue is that there is no standard way to use these files in the consumers. ``CMakeToolchain`` will have the ``<pkgname>_RES_DIRS_<config>`` variables defines, you might want to directly use these variables in your consumer ``CMakeLists.txt`` after the ``find_package``?

If not, it is possible to directly access from the consumers:
```python
# in the consumer conanfile.py
def generate(self):
     res_folder = self.dependencies["mydep"].cpp_info.resdirs
     # do whatever operation you need to do with the ``res_folder`` or the files inside it
```
Note this doesn't really hardcode the path to the files in the dependency, the ``resdirs`` is an abstraction/parameterization, and can be used to change it in the dependency without altering the consumer.

Please let me know if this helps.

**Comment by s-mlr** [comment]
Thanks @memsharded for your immediate reply. Your response times are second to none!

That approach certainly works and I'm completely fine with. I mainly wanted to make sure there is no other design available to completely take care of this from the consumer side. As long as I'm following best practices it's all good.

It does feel like it would be aligned with the general idea / behavior of current generators (as I read them) to fully define it from consumer side and the tc basically already added that option, so I'm keen to see if something along those lines might be coming in the future?

Please consider the question answered. Thanks a bunch!

**Comment by memsharded** [comment]
> It does feel like it would be aligned with the general idea / behavior of current generators (as I read them) to fully define it from consumer side and the tc basically already added that option, so I'm keen to see if something along those lines might be coming in the future?

The challenge here is that we haven't seen any common pattern or usage of resource files, that are wildly varying in nature and usage. For a built-in generator it would be necessary to have some well known and popular usage patterns to implement anything  in Conan. As always, we are open to feedback to learn about the use cases, but so far seems a bit unlikely.

Thanks to you for the feedback!
