### ISSUE TITLE
[question] test_package does not respect dependency includes/libs

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#16675]
### What is your question?

Hi!
I'm building `nss`. It's not officially available as a conan package, so I sat down fixing it.
My issue is, the test_package inside gave me an include error:
```
<root>/p/b/<nss_dir>/p/include/seccomon.h:17:10: fatal error: prtypes.h: No such file or directory
   17 | #include "prtypes.h"
```
`prtypes.h` comes from `nspr`, which clearly defines it's own include dirs and libs:
```
@property
def _library_names(self):
    return ["plds4", "plc4", "nspr4"]

def package_info(self):
    self.cpp_info.libs = libs
    ...
    self.cpp_info.includedirs.append(os.path.join("include", "nspr"))
```

Problem is, these don't get propagated to `nss`' test_package cmake project. CMakeDeps disregards these value automatically. It only works if I explicitly append nspr and sqlite and requirements in the test's conanfile:
```
def requirements(self):
    self.requires(self.tested_reference_str)
    self.requires("nspr/4.35")
    self.requires("sqlite3/3.41.2")
```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @donlk thanks a lot for your question.

If `nss` exposes includes and symbols of one of its dependencies as part of its API, then its recipe has to tell Conan to explicitly propagate the headers (and libs if necessary) thru the use of the `transitive_headers` trait ([Docs here](https://docs.conan.io/2/reference/conanfile/methods/requirements.html#requirement-traits))

This is acomplished by modifying the `self.requires` for `nspr` in `nss` conanfile (and any other necessary requirement) to:
`self.requires("nspr/4.35", transitive_headers=True)`

Let me know if that helps :)

**Comment by donlk** [comment]
Using this and `transitive_libs` solved the issue.
Thank you very much!
