### ISSUE TITLE
[question] conan info --graph replacement?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16671]
Hi,

how can I generate a HTML/DOT similar to Conan 1 with regular Conan CLI commands?
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi,

Yes, ``conan graph info ... --format=html > graph.html``

It is not only similar, but the html format in Conan 2 has been greatly improved: https://docs.conan.io/2/reference/commands/graph/info.html#html-formatter

**Comment by harsszegi** [comment]
Awesome, thanks a lotfor the quick response @memsharded , closing it!
