### ISSUE TITLE
[question] How to implement a validation in the best way?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#16682]
### What is your question?

Hi.
We are using Conan in the lastest 1.x version.

We have two components X and Y  which have a predefined/same option declared with different default values that should never be available in the same dependency tree. If so Conan shall raise an error.
That means if we would have a dep tree like this it shall raise an error:

A -> B - > C -> X
         |  -> D -> Y
         
or

A -> X
| ->  Y

or (you get it I believe)

And no matter whether A or B is created it shall abort with an error.

Also I want to achieve that in case B -> X that one specifc option defined in X is also available in B with the same value.

I have implemented this now in a Conan base class via the validate() function. This base class will be used by all potential consumers of X and Y. 

But I am wondering if there is any chance to implement such validations only in the recipe of X and Y so that I do not need to "pollute" all the other components with that special validation rules. Is it and if so can you give me a hint on how/where to implement it?

Thanks a lot in advance.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

Quick question: are X and Y always mutually exclusive?

If that is the case, then maybe the ``provides`` is a built-in mechanism that will do this automatically for you.

**Comment by MTomBosch** [comment]
Yes. They are mutually exclusive. I was not aware of that attribute (feature). Nice.

What about the 2nd question wrt to checking option values?

> Also I want to achieve that in case B -> X that one specifc option defined in X is also available in B with the same value.

Any idea for that too?

**Comment by memsharded** [comment]
> Also I want to achieve that in case B -> X that one specifc option defined in X is also available in B with the same value.

I think this can be only done with a check in ``B`` ``validate()``, something like:

```python
def validate(self):
     if self.dependencies["depx"].options.myoption != self.options.myoption:
         raise ConanInvalidConfiguration(....)
```

**Comment by MTomBosch** [comment]
OK. This is what I have implemented in a Conan base class that we wanted to rollout to all potential consumers of x/y. Thanks a lot for the quick response.
