### ISSUE TITLE
[question] core.cache:storage_path + Docker

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16681]
Hi,

according to the https://docs.conan.io/2/reference/config_files/global_conf.html#core-cache-storage-path the storage path location in global.conf should be an absolute path. However I don't fully understand where it is being enforced in Conan, e.g. I could write anything like "./foo" or "~/foo".

My issue is that I need to set it to a "easily deductible" value, so that if I run Conan within a Docker container and I mount the configuration folder (and the storage path) into the container the value set in the host's global.con for storage_path would still be valid within the container.

Are there any suggestion how to use this in a "Docker-compatible way" (I suppose the best is not to have it set to anything, then the complete config folder (together with "p") would be mounted)?

[Sidenote: I have checked Conan1, where we have "\~/.conandata" being set, and when I do "conan config get storage.path", the returned value is properly being resolved to an absolute path, e.g. "\~" is resolved, however I don't get the same with Conan2, e.g. I get the actual value stored in global.conf, "\~" is not resolved]

Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

I am not very sure what is the issue or problem to solve.

Maybe this helps:

- The ``global.conf`` is in Conan 2 also a ``jinja2`` template, it can resolve jinja syntax
- The ``global.conf`` gets injected the ``conan_home_folder`` variable that points to the current ``global.conf`` location.
- Then it is easy to form absolute paths from relative paths, starting from the ``conan_home_folder`` variable

You can check it in https://docs.conan.io/2/reference/config_files/global_conf.html#configuration-file-template

Is this what you are looking for?

**Comment by harsszegi** [comment]
Awesome, that is perfect information! Thanks a lot @memsharded , closing it!
