### ISSUE TITLE
[suggestion] Access properties of profile's tool requirements in [conf] section

### ISSUE THREAD

**Issue by Corristo** [conan-io/conan#16687]
### What is your suggestion?

Hi,

The project I work on is built with multiple different versions of GCC (e.g. one for GCC 9 and one for GCC 14, but also multiple variants of the same GCC version for different architectures), and also with Clang. Because Clang is a cross-compiler by default, we have a single Clang build that can be used with the different GCCs by using Clang's `--gcc-toolchain` compiler flag to tell Clang which GCC's libstdc++, crt files and binutils to use. 

I have now started to create toolchain packages for our compilers following the [example for packaging a cross-compiler](https://docs.conan.io/2/examples/cross_build/toolchain_packages.html), and created profiles that list the respective GCC package in their [tool_requires] section, just like in the example. For the GCC packages this works fine. But when creating a profile for the Clang compiler I ran into the following issue: How to specify the `--gcc-toolchain` flag? 

Ideally, it'd be possible to write a profile 

```
[tool_requires]
clang/18.1.7
gcc/14.1.0

[conf]
tools.build:cflags="--gcc-toolchain={{ self.dependencies.build['gcc'].package_folder }}"
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Corristo 

Thanks for your feedback.

I think you might be missing some relevant feature from tool-requires packages.

In these packages you can directly do something like:

```python
# UPDATE: This is package_info, not generate, my mistake
def package_info(self):
     self.conf_info.append("tools.build:cflags", f"-gcc-toolchain={self.package_folder}")
```
And when the toolchain is injected as ``tool_require``, it will automatically communicate that ``tools.build:cflags`` to its consumers, without needing to specify that in the profiles.

Please let me know if this helps.

**Comment by Corristo** [comment]
It might help, but only if there is a way to conditionally append the flag based on some condition that is evaluated when the package is used, not when it is built. The issue is that I can't add this unconditionally to the GCC recipe, as `--gcc-toolchain` is a Clang flag, not a GCC flag. But I also can't add it to the Clang recipe, because there I don't know which GCC it will be used with (if at all), unless I build one Clang package per GCC package, which will be quite wasteful.

**Comment by Corristo** [comment]
By the way, what difference does it make to add this to the `generate` method instead of the `package_info` method? My Clang recipe currently uses 
```
self.conf_info.define(
    'tools.build:compiler_executables.c',
     os.path.join(self.package_folder, 'bin', 'clang'))
```
in the `package_info` method. Should I move that to the `generate` method?

**Comment by memsharded** [comment]
> By the way, what difference does it make to add this to the generate method instead of the package_info method? My Clang recipe currently uses


When you define something in ``package_info()`` of a recipe it is information for the consumers of this package, not for the package itself. The ``package_info()`` method is always called, irrespective whether the package has been built from source or it  has downloaded a pre-compiled binary, it is information of the current binaries to be applied to other packages that ``requires`` or ``tool_requires`` this one.

When you define things in ``generate()`` those are for the build of the current package, not for consumers of the package. This is used to gather information from dependencies to use them properly in the build of the package. The ``generate()`` method is only called when the package is being built from source (or when ``conan install`` locally)

UPDATE: I have realized there was a mistake above, it was intended to be a ``package_info()`` method, not a ``generate()`` one, I have fixed it, maybe now it is clearer.

**Comment by memsharded** [comment]
> It might help, but only if there is a way to conditionally append the flag based on some condition that is evaluated when the package is used, not when it is built.

yes, you can use conditionals in the ``package_info()`` method, it is just important to know what is the condition to apply based on the build/host context. It could be something like:

```python
def package_info(self):
      if self.settings_target.compiler == "clang":
         self.conf_info.append("tools.build:cflags", f"-gcc-toolchain={self.package_folder}")
```

I think in this case, the setting to use is the ``settings_target``, as you might have seen in https://docs.conan.io/2/examples/cross_build/toolchain_packages.html

**Comment by Corristo** [comment]
Thank you very much! That should work for me. With the downside that I have to rebuild all my GCC packages :D

**Comment by memsharded** [comment]
> Thank you very much! That should work for me. With the downside that I have to rebuild all my GCC packages :D

Happy to help. I hope the rebuild is worth it :)
