### ISSUE TITLE
[question] Propagating bin dirs for hybrid package

### ISSUE THREAD

**Issue by forry** [conan-io/conan#16697]
### What is your question?

Hi,
I have come across this package I need to port to conan 2:
```python
import os
from conan import ConanFile
from conan.tools.files import copy

class VulkanConan(ConanFile):
    name = "vulkan"
    version = "1.2.141"
    description = "<Description of Vulkan here>"
    url = "None"
    license = "None"
    author = "None"
    topics = None
    settings = "os", "arch"
    build_policy = "never"

    def package(self):
        copy(self, "*", "./include/", os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.exe", "./bin/", os.path.join(self.package_folder, "bin"), keep_path=False)

#I've later added this to see if it helps
    def package_info(self):
        self.cpp_info.bindirs = ['bin']
```
It is partially a build tool that is called as a custom pre-build target from cmake and it also is a header library. Using conan-cmake (cmakeDeps), I would like to know why the vulkan_BIN_DIRS_RELEASE is empty in the generated cmake config files. I tried to require it in the attribute requires and also like this `self.requires("vulkan/1.2.141@lexocad/prebuild",headers=True, libs=True, build=True)` with libs also set to False. Nothing changed. I know a way around this by using `${vulkan_PACKAGE_FOLDER_RELEASE}/bin`, but I would like to know if there is a better more standard (not specifically tailored to CmakeDeps) solution even though there is nothing standard about this package. Also, I have found a similar package - just headers and DLLs - no libs and it works the difference being `package_type = "shared-library"`, but in the vulkan package case it seems wrong.

Thanks!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by forry** [comment]
I've probably found out the magical combination in the consumer conanfile
```python
def requirements(self):
        self.requires("vulkan/1.2.141@lexocad/prebuild", headers=True, libs=False, build=True, run=True)

    def generate(self):
        cmake = CMakeDeps(self)
        # generate the config files for the tool require
        cmake.build_context_activated = ["vulkan"]
        cmake.generate()
```
But now it seems very wrong. I would like to be able to express what needs to be exposed in the vulkan package since I know that headers and bin dir will be needed during the build of a consumer and not only if cmake is used. And I really don't want to and can't use the provided shell scripts for virtual env. First, they are bad because in multi config the last one (debug) is in the conanbuild.bat (but I think I've heard in some talk that there might be some black magic that puts the release versions of the build tools in the other configs). Second, it is so much easier to use something like `set(glslangValidator "${CONAN_BIN_DIRS_VULKAN}/glslangValidator.exe")` in conan 1 or `set(glslangValidator "${vulkan_BIN_DIRS_RELEASE}/glslangValidator.exe")` and then put it to the `custom_command()` and not care about anything else.

**Comment by memsharded** [comment]
Hi @forry 

I think what is missing is the ``package_type = "header-library"`` in the recipe. This will make them available when used from ``requires``.

Then, the right approach to model this is with 2 requires:
- Use ``requires()`` to depend on the "library" headers
- Use another ``tool_requires()`` to the same reference to depend on the "binary" executable.

Please check: https://docs.conan.io/2/examples/graph/tool_requires/using_protobuf.html

**Comment by forry** [comment]
I might have finally found a solution. First of all, using a tool and a normal requirement is not good for me since it wants some build suffix, and in the two separate functions is something that can be done in one line. `package_type = header-library` really does nothing for me. But thanks to you I have found another example that shows a cmake build modules. It's between the things I would like (this will only work for cmake as a deps generator) but it hides the conan from the consumer's cmake quite nicely by having a custom build module provide an imported executable target instead of some variable.

So my vulkan package now looks like:
```python
import os
from conan import ConanFile
from conan.tools.files import copy

class VulkanConan(ConanFile):
    name = "vulkan"
    version = "1.2.141"
    description = "<Description of Vulkan here>"
    url = "None"
    license = "None"
    author = "None"
    topics = None
    settings = "os", "arch"
    build_policy = "never"

    def package(self):
        copy(self, "*", "./include/", os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.exe", "./bin/", os.path.join(self.package_folder, "bin"), keep_path=False)
        copy(self, "*.cmake", "./cmake/", os.path.join(self.package_folder, "cmake"), keep_path=False)

    def package_info(self):
        self.cpp_info.set_property("cmake_build_modules", ["cmake/buildModule.cmake"])
```

The cmake/buildModule.cmake:
```cmake
add_executable(vulkan::glslangValidator IMPORTED)
set_property(TARGET vulkan::glslangValidator PROPERTY IMPORTED_LOCATION "${vulkan_PACKAGE_FOLDER_RELEASE}/bin/glslangValidator.exe")
```
consumer conanfile:
```python
...

    def requirements(self):
        self.requires("vulkan/1.2.141@lexocad/prebuild", headers=True, libs=False, build=True, run=True)

    def generate(self):
        cmake = CMakeDeps(self)
        # generate the config files for the tool require
        cmake.build_context_activated = ["vulkan"]
        cmake.build_context_build_modules = ["vulkan"]
        cmake.generate()
```
And then in the consumer CMakeLists.txt after find_package(vulkan) one can use:
```cmake
add_custom_command(COMMAND vulkan::glslangValidator --some-arg ...)
```
What is not ideal in this solution is the `_RELEASE` in the variable name. But that can be improved.
I also tried to somehow add the conanbuild.bat into the command directive like `${CMAKE_BINARY_DIR}/generators/conanbuild.bat && glslangValidator.exe` and I couldn't get it working. Also, it exposes the conan into cmake.

When I look back on this afternoon, it seems I have done overcomplicated stuff for something so simple. I don't understand how to make it more general outside of cmake other than to write lots of cpp_info properties. Is this meant to be that way?

**Comment by memsharded** [comment]
Ok, but please note the solution you are proposing isn't valid in the general case, when there could be compiled libraries and in cross-build scenarios, in that case it would be broken and won't work. So the recommendation would still be to follow the 2 requirements using ``requires()`` and ``tool_requires()`` as described in https://docs.conan.io/2/examples/graph/tool_requires/using_protobuf.html.

> I might have finally found a solution. First of all, using a tool and a normal requirement is not good for me since it wants some build suffix, and in the two separate functions is something that can be done in one line.

In general the source issue is that using CMake modules and targets for executables tend to overcomplicate things. Conan puts the executables directly in the PATH of the consumer, so just executing it works, no need to locate or find it at all within CMake code, no ``find_package(vulkan)``, no ``add_custom_command(COMMAND vulkan::glslangValidator --some-arg ...)``, just ``add_custom_command(COMMAND glslangValidator --some-arg ...)`` will work out of the box.

**Comment by forry** [comment]
>  Conan puts the executables directly in the PATH of the consumer...

Is it really? I might be missing something here, but the only way of getting anything into path is to manually run conanbuild*.bat. To clarify, this is the consumer conanfile for developers to set up their build environment of an application, and the custom command is a pre-build command for one of the targets inside the app. I don't know how conan can put something into the path here. I think the user would be required to run cmake which runs conan-cmake to generate those bat/sh files, then start commandline, run the correct conanbuild.bat and then from there start Visual Studio to work? But the conanbuild.bat only gives you a debug into path so what good is it really? I think I don't understand the idea of that workflow here.

**Comment by memsharded** [comment]
> Is it really? I might be missing something here, but the only way of getting anything into path is to manually run conanbuild*.bat. To clarify, this is the consumer conanfile for developers to set up their build environment of an application, and the custom command is a pre-build command for one of the targets inside the app. I don't know how conan can put something into the path here

The environment variables are added both to the ``conanbuild.bat``, but they are also added as ``env`` sections in the generated CMakePresets. So it is not really necessary to activate the ``conanbuild.bat``, using regular ``cmake --preset`` can also work. It is true that the ``cmake-conan`` cannot do this automatically, but this is one of the limitations of driving the process from CMake, with ``cmake-conan``, and this is why in general we recommend the more standard flow of ``conan install + cmake ...``.

See for example, with this ``CMakeLists.txt``:
```cmake
cmake_minimum_required(VERSION 3.15)

project(MYPROJECT LANGUAGES NONE)

execute_process(COMMAND ninja --version)
```
Assuming ``ninja`` is not in the system, then:
```bash
$ conan install --tool-requires="ninja/[*]" -g CMakeToolchain
$ cmake --preset conan-default
```
Will correctly inject the ninja PATH in the ``env`` presets and the correct ninja version from the Conan package will be displayed.

**Comment by forry** [comment]
The problem is that **execute_process** runs directly when the cmake is running. I was talking about **add_custom_command** which schedules/runs during the build, like Qt's moc. So in our case when the dev starts working he git pull and then assuming this is not the first time, he will directly open Visual Studio and start working. When he builds the solution then the vulkan::glslangValidator is run, so there is no conan involved now, and cmake might have run before as a result of the ZERO_CHECK target detecting that the lists were changed but the environment is already set.

I might be wrong here, but it seems that the conan defaults are focused mostly on the developers making the conan packages/libraries driven by conan. I think most people are on the other end developing the applications using conan as a part of already existing workflow. I have no problem with that, I just wanted to know if there is a smoother way possible with our workflow where now after the dev environment setup you don't need a shell at all, and everything is done in some GUI tool (GUI for git, cmake-gui, VS).

**Comment by memsharded** [comment]
> I might be wrong here, but it seems that the conan defaults are focused mostly on the developers making the conan packages/libraries driven by conan. I think most people are on the other end developing the applications using conan as a part of already existing workflow. I have no problem with that, I just wanted to know if there is a smoother way possible with our workflow where now after the dev environment setup you don't need a shell at all, and everything is done in some GUI tool (GUI for git, cmake-gui, VS).

Sure, we try that as much as possible, but at some point there are external, physical limits, that Conan cannot solve. This is the case of trying to inject tool-requires installed by Conan into a build that is not driven by Conan, but by CMake, because that creates a chicken-and-egg problem. For example, it is possible to have a ``tool-requires`` to ``cmake/version`` to bring and inject any specific CMake version into your build. This is completely impossible if we want to drive the process from ``CMake``, because you need to run cmake in the first place...
