### ISSUE TITLE
[question] tool_requires ignores option settings?

### ISSUE THREAD

**Issue by drmacdon** [conan-io/conan#16696]
### What is your question?

I can not seem to get my default_options to override the option for my tool_requires recipe. 

If I switch from tool_requires() to requires(), the option is disabled as expected. Do tool_requires recipes allow for option changing or am I doing something wrong? The simplest test I have is using cmake and disabling the with_openssl (although you'll have to use the cmake source recipe and not the binary recipe).

On Conan v2.5.0, this still leaves openssl as a build requirement,

```
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps, cmake_layout
from conan.tools.files import copy

class Test(ConanFile):
    name = "test"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    exports_sources = "CMakeLists.txt", "conanfile.py", "main.cpp"
    generators = "CMakeToolchain", "CMakeDeps"
    default_options = {
      "cmake/*:with_openssl": False,
    }

    def build_requirements(self):
        self.tool_requires("cmake/3.30.0")
        #self.requires("cmake/3.30.0")

    def layout(self):
        cmake_layout(self)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

```main.cpp```
```
#include <iostream>

int main() {
        std::cout << "Hello World" << std::endl;
}
```

```CMakeLists.txt```
```
cmake_minimum_required(VERSION 3.22 FATAL_ERROR)

project(test VERSION 1.0 LANGUAGES CXX)

set(CMAKE_EXPORT_COMPILE_COMMANDS on)
set(CMAKE_VERBOSE_MAKEFILE on)

add_executable(main main.cpp)
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @drmacdon 

Thanks for your question.

To define options in the build context (tool-requires), it is necessary to use the ``default_build_options`` instead (I think they can also be defined in ``self.tool_requires(..., options={})`` directly). 

Please try that and let us know.

**Comment by drmacdon** [comment]
Thanks @memsharded. 

*Confirmed* either of these, both work 
```
    def build_requirements(self):
        self.tool_requires("cmake/3.30.0", options = { "with_openssl": False })
```
or 
```
    default_build_options = {
      "cmake/*:with_openssl": False,
    }

    def build_requirements(self):
        self.tool_requires("cmake/3.30.0")
```

Is there a syntax I can use from a ```host profile``` when using
```
[tool_requires]
cmake/3.30.0
```

My problem originally stemmed from trying to customize a cross-compiler option.

**Comment by memsharded** [comment]
> Is there a syntax I can use from a host profile when using

The way to achieve this is to define the options in the ``build profile`` instead of the ``host profile``.

**Comment by drmacdon** [comment]
```build profile```
```
[options]
cmake/*:with_openssl=False
```
```host profile```
```
[tool_requires]
cmake/3.30.0
```

Works - thanks for the clarifications!

**Comment by memsharded** [comment]
Great, happy to help!

**Comment by ericriff** [comment]
Neither `default_build_options` nor `options = {}` seem to work on a tool_requirements when it is also listed as a requirement and you're crosscompiling. Using the `important` syntax also doesn't work. 

I know that "setting options on recipes has no strong guarantees", but I wanted to mention it anyways.

E.g.
```python
    default_options = {"grpc/*:with_libsystemd!": False}
    default_build_options = {"grpc/*:with_libsystemd!": False}

    def requirements(self):
        self.requires('grpc/[>=1 <2]')

    def build_requirements(self):
        self.tool_requires("grpc/<host_version>")
```
Produces
```
Build requirements
    abseil/20240116.2#996c9b7c09f1f561bdf2e2f3c889a8cb - Cache
    autoconf/2.71#f9307992909d7fb3df459340f1932809 - Cache
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50 - Cache
    bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4 - Cache
    c-ares/1.33.0#ea6e87dbcb4c5a4d2a782e88c7d4b93a - Cache
    flex/2.6.4#e35bc44b3fcbcd661e0af0dc5b5b1ad4 - Cache
    gnu-config/cci.20210814#dc430d754f465e8c74463019672fb97b - Cache
    gperf/3.1#1d622ad9717e9348ed3685c9994ad0b9 - Cache
    grpc/1.65.0#d17bcdb3f35110f8e3e1e7dc6f071c37 - Cache
    libcap/2.69#7ef2d60864c2e58e89db957be936dc49 - Cache
    libmount/2.39.2#64850679fa9d5ead878e5076b0cab2a8 - Cache
    libselinux/3.6#5a78ff6ae5034eeaac8da723361a8ce4 - Cache
    libsystemd/255#8e49d0c6b1d63861e3e10665cc1b7b4d - Cache
    libtool/2.4.7#08316dad5c72c541ed21e039e4cf217b - Cache
    libxcrypt/4.4.36#4b4e8f20794f1997dd59eeed0b7cdcfb - Cache
    lz4/1.9.4#652b313a0444c8b1d60d1bf9e95fb0a1 - Cache
    m4/1.4.19#b38ced39a01e31fef5435bc634461fd2 - Cache
    meson/1.2.2#29cf77c283f6af08818f6fd8068c37e8 - Cache
    meson/1.4.0#d04d88a761cf81e05206dbbe0f1bfea2 - Cache
    ninja/1.12.1#fd583651bf0c6a901943495d49878803 - Cache
    openssl/3.3.1#279e86dc2a7dded8c1fe8512e775bdb1 - Cache
    pcre2/10.42#576680686b88a4dadf6d382d6d6351d9 - Cache
    pkgconf/2.1.0#27f44583701117b571307cf5b5fe5605 - Cache
    pkgconf/2.2.0#6462942a22803086372db44689ba825f - Cache
    protobuf/5.27.0#ccce9aa25886556c6d66c77b2be4d806 - Cache
    re2/20230301#e8d673155a0494f27c7589b611e8350d - Cache
    xz_utils/5.4.5#b885d1d79c9d30cff3803f7f551dbe66 - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache
    zstd/1.5.5#1f239731dc45147c7fc2f54bfbde73df - Cache
```

Replacing default_build_options with `self.tool_requires('grpc/<host_version>', options = { "with_libsystemd": False })` has no effect.
But if I don't list grpc as a requirement, then it works.

BTW I'm getting the graph using:
```
 conan graph info conanfile.py -pr:b x86_64 -pr:h arm --format=html
```
Setting the options on the build profile does work.
```
[options]
grpc/*:with_libsystemd=False
```

**Comment by memsharded** [comment]
This is unexpected @ericriff, I have just double checked, and there is a test in the test suite that seems to be testing specifically this behavior, please check https://github.com/conan-io/conan/blob/51731ef38732b07a0b17f1523790b71d4d24839e/test/integration/options/test_options_build_requires.py#L119

It might be something else, if you have a full reproducible case, please create a new ticket with it, that would help to investigate.

**Comment by ericriff** [comment]
https://github.com/conan-io/conan-center-index/issues/25115
