### ISSUE TITLE
[bug] `conan.tools.files.copy()` fails silently.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16695]
### Describe the bug

Hello,

 `conan.tools.files.copy()` always fails silently (e.g. passing bogus paths).  It should throw an exception or at least interrupt execution.  The silent failure makes it difficult to solve issues in the recipes.

- O.S.: Windows 11
- Toolset: Visual Studio 2022
- Conan: 2.3.2
- Python: 3.12.3

thanks,

PC

### How to reproduce it

Just place a `copy(self, pattern="*", src="blah-blah-blah", dst="blah-blah")` in any recipe callback (e.g. `source()`).

**Comment by memsharded** [comment]
Thanks for your feedback @PauloCarvalhoRJ 

This is not necessarily a bug, but expected behavior.

There are often cases when a certain folder might exist in one platform but not in others. So ``copy()`` doesn't check existence of paths, it just copy from it if it exists, and ignore it if not. It helps simplifying the ``package()``, ``export()`` and ``export_sources()`` methods avoiding having to introduce many conditionals. 

This was already the behavior in Conan 1, and it has been maintained. It is not possible to change it now, it will be easily breaking existing user recipes relying on this behavior.

**Comment by PauloCarvalhoRJ** [comment]
Sorry, but this time I have to disagree.  It is against good practice in software development.  If a code fails, it must give feedback to the user or abend the program.

Well, you could add a flag, say `silentfail=True` by default to keep the current behavior.  Those wanting more robust scripts could explicitly set it to `False`.

**Comment by memsharded** [comment]
The code doesn't necessarily fails, take into account this example:
```python
def package(self):
      copy(self, "*.h", ....)
      copy(self, "*.so", ....)
      copy(self, "*.a", ....)
      copy(self, "*.lib"; ....)
```

This code works fine and is common in many Conan recipes out there. It is not necessary to check the existence of those files, or error if files with that pattern are not found there. This usage is so spread, that it is even part of the tutorial in https://docs.conan.io/2/tutorial/creating_packages/package_method.html#use-conan-tools-files-copy-in-the-package-method-and-packaging-licenses.

If existence was necessary, it would made the recipes way more complex, something like:

```python
def package(self):
      copy(self, "*.h", ....)
      if self.settings.os == "Linux" or self.settings.os == "FreeBSD" or ...:
          copy(self, "*.so", ....)
      if self.settings.os == "Linux" or "is Windows msys2":
          copy(self, "*.a", ....)
      if self.settings.os == "Windows":
          copy(self, "*.lib"; ....)
```
And this will be more fragile too, when not covering all platforms directly.

Now, in the same way that ``*.so`` are not existing while packaging in some scenarios, it is possible that some folders containing binaries do not exist in some scenarios, something like:

```python
def package(self):
      ...
      copy(self, "*.so", src=os.path.join(self.build_folder, "armv8_libs"), ....)
      copy(self, "*.so", src=os.path.join(self.build_folder, "x86_64_libs"), ....)
```
If the build system creates different folders for different configuration, something not that unusual.

So while I understand your point of view, and I think that I mostly agree with you, I can also understand why some users have been relying on this as a feature, so declaring it a bug is too much, and this is why I said that this cannot be changed, as it cannot be really declared a bug, it is mostly about UX and user expectations.

Your suggestion sounds good but might not be very practical, we have seen similar things in the past. As it would be an opt-in, most users will not be easily aware of this, so they might be affected by the default behavior. And when they realize about it, in most cases they will still fix the issue by fixing the typo, won't necessarily check the docs and add the argument. Adding an argument is only slightly better than having to add one line to the recipe with ``assert os.path.exists(...)`` previous to the ``copy()`` method calls, which is probably how users will realize that they did a typo in the folder.

So while it makes sense, it is an attempt to marginally improve the UX to protect users against relatively unlikely errors, which doesn't typically warrant the effort to add it. Not everything that could be improved in UX can be really prioritized.
