### ISSUE TITLE
[question] How to support conanfile.py in a subdirectory, using Bazel

### ISSUE THREAD

**Issue by peakschris** [conan-io/conan#16690]
### What is your question?

We have a small monorepo built with Bazel that contains 3 libraries that are separately packaged by conan. So we will need 3 conanfile.py files, each in subdirectories. If I put the conanfiles in subdirectories, they do not correctly export the bazel build files (workspace etc) from root of repo and the build fails.

This is what i have tried, this conanfile.py is in src/library1:
```
    # Sources
    exports_sources = "WORKSPACE.bazel", "WORKSPACE.bzlmod", "MODULE.bazel", "src/library1/*"

    def layout(self):
        self.folders.root = "../.."
        bazel_layout(self, src_folder="../..")

    def generate(self):
        bz = BazelDeps(self)
        bz.generate()
        bz = BazelToolchain(self)
        bz.generate()

    def build(self):
        bazel = Bazel(self)
        bazel.build(target="//src/library1", clean=False)
```

Thanks!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @peakschris 

I was trying this approach for the next folder structure:

```
.
├── MODULE.bazel
└── lib1
    ├── BUILD
    ├── conanfile.py
    └── src
        ├── BUILD
        ├── hello.cpp
        └── hello.h
```

Then, I had to export the sources manually:

```python
    # exports_sources = "xxxxxxx" => No need to use this

    def export_sources(self):
        source_folder = os.path.join(self.recipe_folder, "..")
        copy(self, "*", source_folder, self.export_sources_folder)

    def layout(self):
        self.folders.root = ".."
        bazel_layout(self)

    def build(self):
        bazel = Bazel(self)
        bazel.build(target="//lib1/src:hello")
```

A related problem that I encountered was the target relative folder. Even using the `layout(self)` with a subproject does not work because the `target=` param is not evaluated. I'll open another issue with this.

Let me know if it worked on your side.

**Comment by franramirez688** [comment]
> A related problem that I encountered was the target relative folder. Even using the layout(self) with a subproject does not work because the target= param is not evaluated. I'll open another issue with this.

Reviewing the code, I recalled the limitations of the Bazel layout so I guess that I can not change or improve it for now 😅

**Comment by franramirez688** [comment]
Hi @peakschris 

I'm closing this issue as the Bazel layout presents some limitations that Conan can not solve for now.

Do not hesitate to reopen it if you have any other doubts or even if Bazel 8.x or 9.x brings some improvements regarding this topic 😁
