### ISSUE TITLE
[question] Access Resource file in cmake module

### ISSUE THREAD

**Issue by GRyzer** [conan-io/conan#16692]
### What is your question?

Hello together,

I would like to publish a Macros.cmake file. I have done it exactly like described [here](https://docs.conan.io/2/examples/graph/requires/consume_cmake_macro.html#use-a-cmake-macro-packaged-in-a-dependency)
Furthermore i would like to publish two certificate files. My package folder structure looks like this:

```ìni
- cmake
  - Macros.cmake
- certs
  - privatekey.pem
  - publiccert.pem 
```

In my Macros.cmake i have following function:

```cmake
function( doSomething MyTarget MyCommand)
    add_custom_command( TARGET ${MyTarget} POST_BUILD
        COMMAND ${MyCommand} -p=<package_path>/certs/privatekey.pem  -c=<package_path>/certs/publiccert.pem
)
```

I would like to provide other packages the function `doSomething()`. Other packages should not have to know where the certificate files are located. I would like that my function knows the location of the certs, since it is shipped together with them. 
Is there a possibility to do something inside the conanfile.py, like setting a variable which i can access in my Macros.cmake file?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @GRyzer 

Thanks for your question.

I might be missing something, but why aren't you using CMake variables? Something like:

```cmake
function( doSomething MyTarget MyCommand)
    add_custom_command( TARGET ${MyTarget} POST_BUILD
        COMMAND ${MyCommand} -p=${CMAKE_CURRENT_LIST_DIR}/../certs/privatekey.pem  -c=${CMAKE_CURRENT_LIST_DIR}/../certs/publiccert.pem
)
```

**Comment by GRyzer** [comment]
I had that in my mind, but i was unsure if that is the best solution. But since this was also your first proposal i would say that i take it :D. Thanks a lot!
