### ISSUE TITLE
Profile management question

### ISSUE THREAD

**Issue by bschindler** [conan-io/conan#1669]
Hi 
Before the switch to use profiles all the time, simply executing conan created the default configuration by autodetection. Now, I cannot figure out how the default profile can be created without issuing conan install. 
We need to have a guide for setting up our machines and this is much easier if I can tell people to just issue command x + y to have a working conan setup. 
Downloading the source and issuing conan install is an odd way of setting a configuration. 

So, is there a way to create and manage the profiles apart from the read access you have in conan profile?

**Comment by lasote** [comment]
Related to #1463. 
We have added the `conan profile new` and `conan profile update` command and will be released in 0.26.
