### ISSUE TITLE
[feature] Manifold workspace

### ISSUE THREAD

**Issue by aviv000** [conan-io/conan#16708]
### What is your suggestion?

I have been working on a custom command that creates an offline manifold workspace, meaning the command gathers not only the exact dependencies that corresponds to profile+options, but also potential dependencies as well, ones that can be used once the correct option or profile setting is set.
The command currently successfully pulls the dependencies in the order needed recursively, meaning that the package with no dependencies will be pulled first, and be used as dependency for whatever package can consume it.
The collection of the dependencies and their corresponding paths is saved as a json file, which conan editable uses to activate or deactivate those paths as editables.
Given the description I have given, is the idea good enough to be on mainline conan? Did other implementations have already started to support workspace in general?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aviv000 

Thanks for your suggestion.

Could you please elaborate a bit more on this idea?

- What is a `` an offline manifold workspace,``
- What is the problem/pain you are trying to solve with this
- Clarify the behavior, it is downloading all packages for all options and settings values? What is the cost of it in terms of time? 
- How is it connected to editables and workspaces the downloading of all dependencies? It doesn't seem related

With the new custom commands framework, this doesn't seem core enough to be built-in, but in any case we would need to work first in the workspace feature (to be resumed soon), to set the foundations, then we could discuss on other workspace features. But lets try to understand first the proposal.

**Comment by aviv000** [comment]
1. Assume a python conan recipe A that can be built optionally with a subset of dependencies {A_1,...,A_n}.
Given a profile and options, when running `conan install` or `conan build`, not every optional dependency(sources) will be pulled and built due to the nature of giving providing build and install options, also via the profile.
The main problem is a package developer that has a constraint to deploy the package in an offline environment, may not have given the correct options when building on his environment and when the developer tries to deploy to the offline environment when it only has binaries, can be problematic, when the developer may want to change build options or even build with different dependencies because of the change. manifold workspace means that in every case, a subset of the potential dependencies sources will be used to build package A, knowing that probably some of {A_1,...,A_n} will be used as dependencies when building and some are not.

2. The aim is that the deploying developer will have all potential dependencies packages sources with the recipe at hand (the recipe needs to support building as editable), so that the developer will not have to return to its home environment, build with the fixed options, and return to deploy on the offline environment.

3. It is downloading all conanfile.py (also conanfile.txt can be supported easily) packages and pulls their sources that are specified in requirements,build_requirements,tool_requirements,python_requirements, recursively with memoization(caching), meaning that in order to resolve A, we have to resolve {A1,...,An} that may lead to their dependencies, but no duplicate dependencies will be pulled due to runtime caching of the package by its identifiers (like name, version ,reference).

4. How I've developed it initially (can be improved) is by creating a separate and new CONAN_HOME, where the packages are being downloaded there, then calling `source` if needed, then copying the exported recipe from the package and sources to an output path. for every package that has already resolved, I temporarily in the runtime set it as editable so that the package that declared it as dependency will not raise an error. after all dependencies and sub-dependencies are pulled and saved locally in the format I have specified, a json file containing the paths of the dependencies and sub-dependencies is created in the order of pulling them, so that you could the command to set all those paths as editables, and work offline afterwards, knowing you have all optional dependencies, and you can build from sources with `-nr` with no worries when you change an option and you'll need to interact with the remote again.

**Comment by memsharded** [comment]
> The main problem is a package developer that has a constraint to deploy the package in an offline environment, may not have given the correct options when building on his environment and when the developer tries to deploy to the offline environment when it only has binaries

The details of the "offline environment" would be interesting too.
There are quite a few Conan users working in air-gapped environments, I guess that is mostly the "offline environment" you refer to, where there is at least some LAN. 
The recommendation for this use case is having a server in the offline LAN, and put the binaries there for usage within the offline LAN.


> The aim is that the deploying developer will have all potential dependencies packages sources with the recipe at hand (the recipe needs to support building as editable), so that the developer will not have to return to its home environment, build with the fixed options, and return to deploy on the offline environment.

But that is a completely different use case. Having the recipe as editable requires having the sources ``git cloned`` first, this is not something that can be done if there is no network to the original recipe sources, and that doesn't depend on Conan having the binary packages cached in the Conan cache, so this seems different to having the multiple versions and binaries for the different dependencies combinations cached.

> It is downloading all conanfile.py (also conanfile.txt can be supported easily) packages and pulls their sources that are specified in requirements,build_requirements,tool_requirements,python_requirements, recursively with memoization(caching), meaning that in order to resolve A, we have to resolve {A1,...,An} that may lead to their dependencies, but no duplicate dependencies will be pulled due to runtime caching of the package by its identifiers (like name, version ,reference).

I am not sure what you are doing, but this is not necessary, there is already a conan configuration that automatically forces the download of sources to the cache, even if the pre-compiled binary is being used: ``tools.build:download_source``.


There is also a mechanism for isolating the source tarball downloading: the "backup sources", see: https://blog.conan.io/2023/10/03/backup-sources-feature.html


It seems to me that there are different problems here. The problem of pre-caching some different combinations of dependencies in a Conan cache, I can more or less understand it, I don't see it as built-in, but I think a custom command can do the job.

For the editables/workspaces, I am not sure it is the correct approach. In general, when working from source, the approach is that the sources live in ``scm`` repos, like ``git``, and that is the starting point for any source work. Conan is a package manager and contains packages, but it is not intended to manage sources at all. Recovering some sources from Conan packages to **modify** them is actually a discouraged practice. All source code changes must be tracked in a proper ``scm`` like ``git``.

There are mechanisms in Conan like ``scm`` capturing (https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html) that can help tracking this, and in fact it is what our Conan 2 ``workspace`` feature will do. Still, it is a ``git clone`` operation, and will require access to the ``git`` source repo.

**Comment by aviv000** [comment]
> The details of the "offline environment" would be interesting too.
There are quite a few Conan users working in air-gapped environments, I guess that is mostly the "offline environment" you refer to, where there is at least some LAN.
The recommendation for this use case is having a server in the offline LAN, and put the binaries there for usage within the offline LAN.

The air-gap offline environment I meant is also to support when there's no LAN or without the ability to spin up a server and take it with you to deploy.

> I am not sure what you are doing, but this is not necessary, there is already a conan configuration that automatically forces the download of sources to the cache, even if the pre-compiled binary is being used: tools.build:download_source.

I am familiar with that feature, although I mean to fetch optional dependencies as well, meaning those that are not necessarily corresponds to the profile and options you have given, but has no regard to options or profile and takes all potential dependencies sources.

> For the editables/workspaces, I am not sure it is the correct approach. In general, when working from source, the approach is that the sources live in scm repos, like git, and that is the starting point for any source work. Conan is a package manager and contains packages, but it is not intended to manage sources at all. Recovering some sources from Conan packages to modify them is actually a discouraged practice. All source code changes must be tracked in a proper scm like git.

The goal is to have the potential dependencies sources and not to change them when you build, using them as editable is more of a side effect, having the dependencies  sources cached somewhere. The small changes in options or profile happen in the deployed package, the consumer of all dependencies. If there was a way that all **potential** sources to be in the conan cache, it would be also applicable, the purpose is that if you change an option while deploying offline, there would not be a possibility that conan would need to fetch something from the remote.

To clarify what I mean by potential dependency, is that `conanfile.py` allows to conditionally use `self.requires` when an option of some kind is set, if you do not give the correct option, that dependency might not be fetched, but in some cases it might, this is what makes the dependency a potential/optional dependency in my perspective.

**Comment by memsharded** [comment]
> The air-gap offline environment I meant is also to support when there's no LAN or without the ability to spin up a server and take it with you to deploy.

What kind of setup is that? If there is not even a LAN, it is just a computer developing things that cannot get out of the development machine? How are the final products, packages, etc, made available to others? Is the isolated machine used for development the same that is used for production? Isn't there any CI at all then that will be the one building the final production packages?
I am not saying that this is not possible, but we have users in some of the most restrictive environments, like defense R&D of some different countries, and I have never heard of such setup, when there is not even some kind of local, air-gapped connectivity, so I am interested in learning more.

> I am familiar with that feature, although I mean to fetch optional dependencies as well, meaning those that are not necessarily corresponds to the profile and options you have given, but has no regard to options or profile and takes all potential dependencies sources.

The ``source()`` must be fully invariant of the profile, settings and options, and in fact, it forbids its access, if you try to use ``settings`` or ``options`` from the ``source()`` method, you will get an exception.
One thing is to have different dependencies, like depending on ``zlib/1.2.11`` or ``zlib/1.3`` depending on the configuration, and a different one is the access to the sources of those packages, which is the thing that can be forced via the ``tools.build:download_source``, but it seems that I understood it differently.

Because there are 2 different sources:

- The ``recipe`` sources, with the ``conanfile.py`` and other files
- For third-parties the sources downloaded from the ``source()`` method, which URLs are stored in the ``conandata.yml``. 

And both need to be downloaded if you want to be disconnected from the internet. The second one is the one that can be forced with the ``tools.build:download_source`` configuration. The first one needs a ``conan install`` or ``conan download`` to get them from the server in the local cache.


Another important note is that the space for ConanCenter third parties can be huge. There are packages with dozens of options, that have mutual interactions, exclusions and incompatibilities. For a relatively large dependency graph, exploring all the possible options combinations might simply be too much and take for ever.

In practice what I would have:
- Have well defined ``profile`` files for the configurations that my organization supports. That should perfectly cover the space of needed packages. You can manage the profiles with ``conan config install`` or ``conan config install-pkg``
- Have somewhere a script that contains a list of package references to be cached.
- That same script will iterate the different profiles, calling ``conan install --requires=mypkg/version -c tools.build:download_source=True``. 

You can make the last 2 a custom command, for convenience, that developers can run before going offline.

This would be for the "caching" problem for going offline with respect to the Conan package server. For the source issues, please recall my above comments, that it is not recommended to make packages editable from the Conan package itself, it must be made editable from the ``git clone`` of the source recipe.

Thanks very much for the feedback, so far I don't see this as a built-in feature, and I think the right approach is to have a custom command on the user side that does the specific logic.

**Comment by aviv000** [comment]
> What kind of setup is that? If there is not even a LAN, it is just a computer developing things that cannot get out of the development machine? How are the final products, packages, etc, made available to others? Is the isolated machine used for development the same that is used for production? Isn't there any CI at all then that will be the one building the final production packages?
I am not saying that this is not possible, but we have users in some of the most restrictive environments, like defense R&D of some different countries, and I have never heard of such setup, when there is not even some kind of local, air-gapped connectivity, so I am interested in learning more.

What's happening is that there is a package whose binaries were built to certain platforms on the local environment, and those binaries also needs to be integrated on a foreign environment which the deployer has little to no impact on, and not necessarily on the exact target platform as well, those are the main painful constraints, I can further explain via mail or chat if you'd like. 

> One thing is to have different dependencies, like depending on zlib/1.2.11 or zlib/1.3 depending on the configuration, and a different one is the access to the sources of those packages, which is the thing that can be forced via the tools.build:download_source, but it seems that I understood it differently.

would `tools.build:download_source` pull both zlib/1.2.11 and zlib/1.3 regardless of the profile?

> For a relatively large dependency graph, exploring all the possible options combinations might simply be too much and take for ever.

Probably true, but not in my use case. The runtime of my custom command that takes advantage of `ConanAPI` for a relatively large project, which has in-house made packages and packages originally from ConanCenter takes about half a minute with memoization.

> This would be for the "caching" problem for going offline with respect to the Conan package server. For the source issues, please recall my above comments, that it is not recommended to make packages editable from the Conan package itself, it must be made editable from the git clone of the source recipe.

I get why you would say that, but also if you implemented `source` or provided `export_sources` then it should be fine no?

**Comment by memsharded** [comment]
Workspaces have been released in latest Conan as "incubating feature": https://docs.conan.io/2/incubating.html

Please give it a try, and report new tickets for any further question or issue related to the new workspaces. Thanks for the feedback.
