### ISSUE TITLE
[question] Artifactory compatibility between Conan 1 and Conan 2?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16701]
Hello,

I have revisions_enabled=True and default_package_id_mode=semver_direct_mode for Conan 1 in conan.conf, for Conan 2 I set nothing.

I have a header-only package (self.info.clear() in package_id()).

I get the following error when trying to look the package up in Artifactory:

(conan2) D:\workspace\virtualenv\conan2\Scripts>conan search foo/3.0.5+feature_conan2+558-d0d0582@user/dev -r=default
Found 1 pkg/version recipes matching foo/3.0.5+feature_conan2+558-d0d0582@user/dev in default
default
  foo
    foo/3.0.5+feature_conan2+558-d0d0582@user/dev

(conan1) D:\workspace\virtualenv\conan1\Scripts>conan search foo/3.0.5+feature_conan2+558-d0d0582@user/dev -r=default
ERROR: HTTPSConnectionPool(host='artifactory.hostname.com', port=8443): Max retries exceeded with url: /artifactory/api/conan/default/v2/conans/foo/3.0.5+feature_conan2+558-d0d0582/user/dev/search (Caused by ResponseError('too many 500 error responses')). [Remote: vp95]

Any idea what might be goind wrong here?

Is self.info.clear() not enough for Conan 1? Do I have to set something for Conan 2 in relation with "revisions_enabled" as well?
Please advise,
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for  your question.

This doesn't seem an issue related with the specific "header-only" library, I'd say this is an issue with the specific package reference `` foo/3.0.5+feature_conan2+558-d0d0582@user/dev``. It is possible that the double ``+`` is making Conan 1 Artifactory API implementations to choke.

As this isn't a standard or close to standard ``semver`` reference, I'd recommend in any case to use some more standard version, something like ``foo/3.0.5-d0d0582+feature_conan2.558@user/dev``, that is:
- ``prerelease`` with ``-d0d...`` before the ``+`` metadata
- Avoid double ``+``, using a ``.`` dot instead to add different digits to either build metadata or prereleases

**Comment by harsszegi** [comment]
Hi @memsharded , sadly this is not the case :(

This version format we use works / worked perfectly fine until now. Even further I have tested the following:
* erased the problematic version from Artifactory
* uploaded only the one produced by Conan 1

and everything works perfectly fine:

(conan1) D:\workspace\virtualenv\conan1\Scripts>conan search foo/3.0.5+feature_conan2+558-d0d0582@user/dev -r=default
Existing packages for recipe foo/3.0.5+feature_conan2+558-d0d0582@user/dev:

Existing recipe in remote 'vp95':

    Package_ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
        Outdated from recipe: False

The package breaks as soon as I publish with Conan 2 "on top of" the Conan 1 package.

**Comment by memsharded** [comment]
Which version of Artifactory are you using?

**Comment by harsszegi** [comment]
7.33.12 rev 73312900

**Comment by memsharded** [comment]
Artifactory version 7.33 is one year older than Conan 2, it is expected that there will be issues if uploading Conan 2 packages to this version of Artifactory. Please update to more modern version, I think at least 7.63 is recommended, but better if using something as close to the latest as possible.

**Comment by harsszegi** [comment]
Understood, thanks a lot @memsharded , closing it!
