### ISSUE TITLE
[bug] VirtualBuildEnv causes compiler to load shared libraries from conan cache?

### ISSUE THREAD

**Issue by nextsilicon-itay-bookstein** [conan-io/conan#16711]
### Describe the bug

I attempted creating a profile with sanitizers (ASan, UBSan) enabled, and building dependencies with it.
Two of these dependencies are gmp and mpfr (which depends on gmp).
The compiler is clang, and it depends on libgmp indirectly through libz3.
When building mpfr, the `conanbuild.sh` file (created by the VirtualBuildEnv, I think?) modifies `LD_LIBRARY_PATH` in such a way that it causes clang to load libgmp.so.10 **from the Conan cache** rather than from the location it usually gets loaded from. I only noticed it because it causes failures, because the libgmp.so.10 it loads is sanitized (with -shared-libasan) so it's missing libasan.so symbols.
It seems very weird to have the compiler inadvertently load libraries from the Conan cache like this 😕 
Thanks for the help!

### How to reproduce it

The profile looks basically like this, and it needs `ENABLE_SANITIZERS=1` and `LIBASAN_PATH=<path/to/libclang_rt.asan.so>`.
I tried this using clang-16 and by installing mpfr + gmp.

```
{% set cc, cc_ver, cc_exe = detect_api.detect_default_compiler() %}
{% set cxx_exe = os.getenv("CXX", "c++") %}
{% set truthy = ("true", "yes", "1", ) %}
{% set enable_sanitizers = os.getenv("ENABLE_SANITIZERS", "false").lower() in truthy %}
{% set libasan_path = os.getenv("LIBASAN_PATH", "/") %}
{% set libasan_dir = os.path.dirname(libasan_path) %}

[settings]
os={{detect_api.detect_os()}}
arch={{detect_api.detect_arch()}}
compiler=clang
compiler.version=16
compiler.libcxx=libstdc++11
compiler.cppstd=gnu20
build_type=Release

[buildenv]
CC={{cc_exe}}
CXX={{cxx_exe}}

[conf]
tools.build:compiler_executables={"c": "{{cc_exe}}", "cpp": "{{cxx_exe}}"}
tools.cmake.cmaketoolchain:generator=Ninja

{% if enable_sanitizers %}
tools.build:cflags+=["-fsanitize=undefined", "-fsanitize=address", "-fsanitize-address-use-after-scope", "-fno-omit-frame-pointer"]
tools.build:cxxflags+=["-fsanitize=undefined", "-fsanitize=address", "-fsanitize-address-use-after-scope", "-fno-omit-frame-pointer"]
tools.build:exelinkflags+=["-fsanitize=undefined", "-fsanitize=address"]
tools.build:sharedlinkflags+=["-fsanitize=undefined", "-fsanitize=address"]

{% if cc == "clang" %}
# We use shared-libasan because we sometimes host sanitized libraries in
# processes whose executable is not sanitized (e.g. loading DSOs into a 
# Python interpreter). We pass these link flags to cflags and cxxflags as well
# because some configure scripts (e.g. gmp) don't pass LDFLAGS to test
# executables that they create and then run them, leading to a static-vs-dynamic
# ASan mismatch.
tools.build:cflags+=["-shared-libasan", "-Wl,-rpath={{libasan_dir}}", "-Wno-unused-command-line-argument"]
tools.build:cxxflags+=["-shared-libasan", "-Wl,-rpath={{libasan_dir}}", "-Wno-unused-command-line-argument"]
tools.build:exelinkflags+=["-shared-libasan", "-Wl,-rpath={{libasan_dir}}"]
tools.build:sharedlinkflags+=["-shared-libasan", "-Wl,-rpath={{libasan_dir}}"]
{% endif %}

# Make the package_id depend on these flags so that sanitized and unsanitized
# builds are keyed separately.
tools.info.package_id:confs+=["tools.build:cflags", "tools.build:cxxflags", "tools.build:exelinkflags", "tools.build:sharedlinkflags"]

# Propagate this to the generated CMake toolchain file.
tools.cmake.cmaketoolchain:extra_variables={"LIBASAN_SO_PATH": "{{libasan_path}}"}
{% endif %}
```

**Comment by memsharded** [comment]
Hi @nextsilicon-itay-bookstein 

Thanks for your report.
I am also a bit surprised that regular dependencies add their path to the ``conanbuild`` scripts.

Can you reproduce with something simple such as:
```
conan install --requires=gmp/version
```
And then sharing both the output and the contents of the ``conanbuild.sh`` and the contents of the included files from there, such as ``conanbuild-release-x86.sh`` or similar?

**Comment by nextsilicon-itay-bookstein** [comment]
During the more complex build I see the culprit modification in `conanrunenv-release-x86_64.sh`:
```
script_folder="/local/users/itay/.conan2/p/b/mpfr1a803f48e8949/b/build-release/conan"
echo "echo Restoring environment" > "$script_folder/deactivate_conanrunenv-release-x86_64.sh"
for v in LD_LIBRARY_PATH DYLD_LIBRARY_PATH
do
    is_defined="true"
    value=$(printenv $v) || is_defined="" || true
    if [ -n "$value" ] || [ -n "$is_defined" ]
    then
        echo export "$v='$value'" >> "$script_folder/deactivate_conanrunenv-release-x86_64.sh"
    else
        echo unset $v >> "$script_folder/deactivate_conanrunenv-release-x86_64.sh"
    fi
done


export LD_LIBRARY_PATH="/local/users/itay/.conan2/p/b/gmpde43b98884dcf/p/lib:$LD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="/local/users/itay/.conan2/p/b/gmpde43b98884dcf/p/lib:$DYLD_LIBRARY_PATH"
```

I'll try to create a smaller repro.

**Comment by memsharded** [comment]
Thanks for the feedback.

> conanrunenv-release-x86_64.sh

This is totally expected, this is the ``conanrunenv``, not the ``conanbuildenv``. It is expected to be used when the application is running (and then it will need those env-vars to locate the shared libs), not when it is building, this file shouldn't be used at build time.

**Comment by nextsilicon-itay-bookstein** [comment]
I have managed to repro the problem with this command line (note I have slightly updated the above profile):
```
env ENABLE_SANITIZERS=1 LIBASAN_PATH=<path/to/compilers/libclang_rt.asan.so> conan install -pr:a <path/to/above/profile> --requires=mpfr/4.2.0#b26709ecb020361b850a35b89785b37e --build=missing --options mpfr/\*:shared=True --options gmp/\*:shared=True
```
What I observe happening is that the above LD_LIBRARY_PATH modification is active during the execution of mpfr's `configure` script, which makes the sanitized libgmp.so.10 load into the compiler when invoked from the configure script.

Indeed, grepping reveals this:
```
~> rg conanrunenv /local/users/itay/.conan2/p/b/mpfr1a803f48e8949/b/build-release/
/local/users/itay/.conan2/p/b/mpfr1a803f48e8949/b/build-release/conan/conanbuild.sh
1:. "/local/users/itay/.conan2/p/b/mpfr1a803f48e8949/b/build-release/conan/conanbuildenv-release-x86_64.sh" && . "/local/users/itay/.conan2/p/b/mpfr1a803f48e8949/b/build-release/conan/conanrunenv-release-x86_64.sh" && . "/local/users/itay/.conan2/p/b/mpfr1a803f48e8949/b/build-release/conan/conanautotoolsdeps.sh" && . "/local/users/itay/.conan2/p/b/mpfr1a803f48e8949/b/build-release/conan/conanautotoolstoolchain.sh"
...
```

So the conanrunenv is sourced during build. Maybe that's a problem with the specific recipe?

**Comment by nextsilicon-itay-bookstein** [comment]
Aha! https://github.com/conan-io/conan-center-index/pull/19150#pullrequestreview-1573618285

**Comment by memsharded** [comment]
Ok, that explains it!

It is mostly a recipe issue, not a Conan client bug per se.

There are some recipes that added the idiom:
```python
if not cross_building(self):
            env = VirtualRunEnv(self)
            env.generate(scope="build")
```
I think this is mostly a Conan 1 legacy compatibility thing, when not using the 2 profiles (build/host), and I'd say it will be removed. In the meantime, maybe the best would be to work from a ``conan-center-index`` fork as recommended in https://docs.conan.io/2/devops.html, to quickly fix things for your use case without having to wait for ConanCenter reviews, that can take some time as the queue is large.

cc @jcar87 to discuss if this idiom can be removed already,  or has to wait until Conan 2-only pipeline

**Comment by nextsilicon-itay-bookstein** [comment]
I might eventually do that, but I'd rather not have this as a forced dependency during this Conan 1 -> Conan 2 upgrade. I already have a hacky way of privatizing recipes from the Conan 1 days (committing them into the repo and exporting them into the cache before building them). So I'd rather select a workaround first, preferably without privatizing the recipe. Maybe I can simply not sanitize these particular libraries for now (by overriding their cflags/linkflags?).

Should I close this and reopen an issue on conan-center-index for discussing this problematic idiom?

**Comment by memsharded** [comment]
> Maybe I can simply not sanitize these particular libraries for now (by overriding their cflags/linkflags?).

Yes, in case you don't know it, the ``conf`` also has patterns that allow to define them per-package:
```
pattern*:tools.build:cflags=...
```
And these patterns also have negations. Having the jinja template you can also do a ``for`` loop over a list of packages.


I have been getting feedback from the team, and it seems there are some recipes that have this problem:

- Recipes with ``autotools`` toolchain that will execute compiled programs during the build
- If the compiled programs use shared libraries, the path to these shared libraries need to be defined correctly too
- So it is expected these builds will inject the shared libs into the LD_LIBRARY_PATH, also at build time

It seems this is a limitation of the build systems of those particular libraries, which doesn't have a good solution, besides a very heavy update to the build system scripts, something that it is out of the scope of Conan or ConanCenter recipes to do.

**Comment by nextsilicon-itay-bookstein** [comment]
Cool, that makes sense, thank you for all the help.
So I'm closing this without opening an issue for discussion on `conan-center-index`, then.

**Comment by memsharded** [comment]
Thanks for the feedback!

We will keep an eye when possible on recipes in ConanCenter, trying to simplify it if the idiom was not strictly necessary (sometimes some copy & paste or other legacy issue might happen).

**Comment by jcar87** [comment]
@nextsilicon-itay-bookstein , you may try your luck with the very experimental https://github.com/conan-io/conan-center-index/pull/24702/files  (for mpfr)

This issue is caused in some scenarios:
* a recipe is built using autotools
* there are dependencies and they are shared
* autotools is *not* crossbuilding (or nor aware of it)

In this scenarios, the `./configure` script _may_ try to link a test executable that it immediately tries to execute. The executable will compile and link (because we pass the relevant flags to do so), but it may not run if it has shared library dependencies - because the runtime loader needs to find those dependencies too. That's why the virtual "run" env (for the host context) is being exposed to the build, but it is excessive, since it causes `LD_LIBRARY_PATH` to be exposed to all processes launched, including the compiler.

The workaround im proposing in https://github.com/conan-io/conan-center-index/pull/24702 involves exposing `LD_RUN_PATH` such that those ephemeral test executables have the rpath embedded and can run without `LD_LIBRARY_PATH` - but it also means we need to ensure this variable is _not_ active when building the actual library, otherwise we end up with absolute paths in the resulting libraries.
Feel free to give it a go, it may help this particular case.
