### ISSUE TITLE
[question] runtime_deploy copying deps with run=False trait

### ISSUE THREAD

**Issue by forry** [conan-io/conan#16712]
Hi,
I need to copy stuff from bin/ dir of the dependencies to create a standalone win application. I tried to use the runtime_deploy but I have noticed that it copied some stuff (namely executables from draco/1.5.6. library) that I don't need and the draco dependency has its run trait set to false.

Does the run=False trait mean that it should have no run-time dependencies?
If yes is that a bug or a feature for some other reasons?

conan 2.5.0

**Comment by memsharded** [comment]
Hi @forry 

Thanks for your question.

At the moment the ``runtime_deployer`` is not using the traits to filter dependencies. I think it might make sense to have it, if some dependencies explicitly have ``run=False``, then it can be skipped.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/16724 changed this, it will be in next Conan 2.6

**Comment by forry** [comment]
Thanks. Also, it would be good if the doc explicitly states exactly what it does/copies. At least in the reference>extension>deployers. Even though it doesn't feel like an extension when it's built in.
