### ISSUE TITLE
[question] Best practices to use Conan in large projects

### ISSUE THREAD

**Issue by FWiesner** [conan-io/conan#16710]
### What is your question?

Hi,

we would like to use Conan with our very large closed-source product and have created a Conan repository on our Enterprise Artifactory for it. We are cutting over from an older custom build system and an old SCM to CMake and Git. Our idea is to build all ported shared libraries using CMake and then upload them to Artifactory, together with their headers. This includes third party software as well, so conancentral will be disabled and we generally won't have non-binary recipes.

The old build system will then pull the prebuilt libraries from Artifactory and use the artifacts in non-ported builds. Because of the legacy nature of our code base, libraries today are small, but huge in number, so we talk about hundreds of CMake targets.
In CMake we use source and header file sets to drive the IDE and have a ton of macros for module homogeneity. So, we obviously aim for reusing as much of the CMake project setup to steer Conan publishing.

I wonder what the best way would be for us to use Conan.

Thank you in advance,
Florian

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @FWiesner 

Thanks for  your question.

>  This includes third party software as well, so conancentral will be disabled and we generally won't have non-binary recipes.

This is a good practice, note how our docs document how to build packages from ``conan-center-index`` github repo sources, to not depend on ConanCenter binaries: 
- https://docs.conan.io/2/devops/using_conancenter.html
- https://docs.conan.io/2/devops/conancenter/hosting_binaries.html


> The old build system will then pull the prebuilt libraries from Artifactory and use the artifacts in non-ported builds. Because of the legacy nature of our code base, libraries today are small, but huge in number, so we talk about hundreds of CMake targets.
In CMake we use source and header file sets to drive the IDE and have a ton of macros for module homogeneity. So, we obviously aim for reusing as much of the CMake project setup to steer Conan publishing.

For this, it would be better to understand a bit more your setup, if this is a huge single-repo with all the libraries, or what is the approach.

**Comment by memsharded** [comment]
I think this question can be closed, feel free to create new tickets for any specific new question, or reach out for discussion and advice. Thanks!
