### ISSUE TITLE
[question] How to erase values from one profile to the other

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#16718]
### What is your question?

Hello,

I created a reproducible case for the example : https://github.com/Todiq/test_conan

On windows, you just have to run `python build.py` with msvc & clang installed (VS or LLVM, does not matter).

Notice that during the first build (msvc), `Conan toolchain: C++ Standard 17 with extensions OFF` is displayed.

However, during the second one, the C++ standard is not set at all.

My guess is that I made a mistake when using `include(msvc)` in my `clang-windows` profile and that it breaks the set up of variables.

Could you please explain to me how to do it properly using the `include()` functionailty?

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your report.

This seems is not intended, a subtle bug in the profile inclusion resolution.
I am submitting a fix in https://github.com/conan-io/conan/pull/16720, hopefully for next 2.6 release.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/16720 was merged, it will be in next 2.6

**Comment by Todiq** [comment]
Thanks for your quick reaction, as always!
