### ISSUE TITLE
[question] How to build locally with msys2

### ISSUE THREAD

**Issue by Drllap** [conan-io/conan#16713]
### What is your question?

 Hi
I'm trying to build ffmpeg locally. This is what I execute:
```
conan1 install . ffmpeg/6.1.1@ -pr d64  `
    -o ffmpeg/*:with_ssl=False
conan1 source .
conan1 build .
```
I get this error: 
```
ERROR: conanfile.py (ffmpeg/6.1.1): Error in build() method, line 707
        autotools.configure()
        ConanException: Cannot wrap command with different envs, ['C:\\Development\\conan-center-index\\recipes\\ffmpeg\\all\\build
-debug\\conan\\conanbuild.bat'] - ['C:\\Development\\conan-center-index\\recipes\\ffmpeg\\all\\build-debug\\conan\\conanbuild.sh'] 
- []
```
I suspect this has something to do with the fact that the ffmpeg uses msys to build. What am I don't wrong?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by Drllap** [comment]
This is my d64 profile: 
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=16
# compiler.version=17
# compiler.cppstd=14
# compiler.cppstd=17
build_type=Debug
[options]
[build_requires]
[env]
```

**Comment by memsharded** [comment]
Hi @Drllap 

Thanks for your question.

First, please note that many recipes in ``conan-center-index`` might not be prepared at all for the local flow. That is, they will only build correctly with ``conan create``, but fail in the local flow with ``conan source`` and ``conan build``.

It is also very possible that the local flow is less supported in Conan 1. I have just tried this in Conan2:

```
conan source . --version=6.1.1
conan build . --version=6.1.1 -o ffmpeg*:with_ssl=False
```
And this seems to be able to build locally correctly.

**Comment by Drllap** [comment]
@memsharded Ok, thanks for the clarification. I just thought I was doing something wrong
