### ISSUE TITLE
[bug] required tool paths gets overridden when using host profiles

### ISSUE THREAD

**Issue by rollebolle** [conan-io/conan#16719]
### Describe the bug

I have a cross-compilation case where a package need `scons`, defined like so in the `conanfile.py`:

`tool_requires = "scons/[>=4.0.1]"`

I also use a host profile for the build, and this host profile contains a custom path in the `[buildenv]` section:

`PATH=[xx/xxx,yyy/yyy,$PATH]`

The build now fails with:

`/bin/sh: 1: scons: not found`

I *think* the reason is that the host profile paths is resolved early, and then later the path to the required tools are added. But as the profile path has already been "resolved", when it comes to actually building with the host profile, the appended scons path is lost. I am not sure about this, but this message comes after the profile has already been printed:

```
scons/4.6.0: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter' 
scons/4.6.0: Package installed da39a3ee5e6b4b0d3255bfef95601890afd80709
scons/4.6.0: Downloaded package revision fe92b9aea83de27b2fdff7edea27626b
scons/4.6.0: Appending PATH environment var: /xxx/build/p/scons3d609e566e37a/p/bin

```

### How to reproduce it

Run conan create using a host profile containing a path env var and have a required tool

**Comment by AbrilRBS** [comment]
Hi @rollebolle thanks for your question - As per the [`[buildenv]` docs](https://docs.conan.io/2/reference/config_files/profiles.html#buildenv), the recommended way to set PATH values is to use the append/prepend operators alongside the `(path)` specifier, like the example shown there

```
# Prepend another PATH to "MyPath1"
MyPath1=+(path)/other path/path12
```

here `MyPath1` can be `PATH` to set your PATH variable as needed :)

Let me know if this helps!

**Comment by rollebolle** [comment]
Thanks for the quick feedback, this helped!

**Comment by AbrilRBS** [comment]
Great to hear! I'm closing this issue as solved then, but don't hesitate to reopen/create a new issue should you find any other problem :)
