### ISSUE TITLE
[question] CMake no depencency include directories in VS solution

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#16721]
### What is your question?

Not sure what I am doing wrong, or even if I am doing anything wrong.
Using conan 2.5.0 and cmake 3.27.4 on Windows, I created a conanfile.py to bring in some dependencies, which then I ran cmake and it creates me a VS project and solution. However none of the conan dependencies have their include directories in the VS project. As such Visual Studio cannot find the headers and building the project fails.
Curiously enough cmake itself is somehow capable of building it when not going through VS.

conanfile.py
```py
from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.cmake import cmake_layout, CMakeToolchain, CMakeDeps, CMake

class DemoConan(ConanFile):
    name = "demo"
    version = "0.1"
    settings = "os", "arch", "build_type", "compiler"
    default_options = {
        "spdlog/*:header_only": True,
        "fmt/*:header_only": True,
    }
    generators = "CMakeToolchain", "CMakeDeps"

    def requirements(self):
        self.requires("asio/1.30.2", force=True) # WebsocketPP wants older version
        self.requires("websocketpp/0.8.2")
        self.requires("ms-gsl/4.0.0")
        self.requires("spdlog/1.14.1")

    def layout(self):
        cmake_layout(self)
```

CMakeLists.txt
```cmake
project(Demo VERSION 1.0.0 LANGUAGES CXX)
set(CXX_STANDARD_REQUIRED ON)
if(NOT "${CMAKE_CXX_STANDARD}" OR CMAKE_CXX_STANDARD LESS 20)
    set(CMAKE_CXX_STANDARD 20)
endif()

add_library(${PROJECT_NAME})

find_package(asio REQUIRED)
find_package(websocketpp REQUIRED)
find_package(spdlog REQUIRED)
find_package(Microsoft.GSL REQUIRED)

target_link_libraries(${PROJECT_NAME} PRIVATE asio::asio)
target_link_libraries(${PROJECT_NAME} PRIVATE websocketpp::websocketpp)
target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog_header_only)
target_link_libraries(${PROJECT_NAME} PRIVATE Microsoft.GSL::GSL)

target_include_directories(${PROJECT_NAME} PUBLIC include)
```

Then running `conan install -pr:a default .` will install / build all the dependencies and create the build directory with all the CMake stuff. Running `cmake --preset conan-default` will create the solution and project files.
Opening the solution in Visual Studio reveals that all the include files pertaining to conan dependencies are being underlined and are not found. Checking the project properties shows that only the include directory listed in the cmake file is present.
It wil fail to compile when building the solution, complaining about missing include files.
However when running `cmake --build --preset conan-release` it will build successfully.

Not sure if this is a cmake error for some reason, or an error on conans part.
Any insight is appreciated.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

Thanks for your question.

I think the main issue is that:
```
conan install -pr:a default .
```
Will install the ``default`` configuration, which by default is ``Release``
But when opening Visual Studio, the default configuration the IDE picks is ``Debug``. If you select ``Release`` in the IDE configuration box and build it should work.

You can also install the dependencies in Debug mode with:
```
conan install . -pr:a default -s build_type=Debug
```
Though ConanCenter is not building Debug binaries for many configurations, so those binaries might be ``Error: Missing binary``, and you would need to build them from source with ``--build=missing``.

Please let me know if this helps.

**Comment by Sil3ntStorm** [comment]
That does appear to be the case yes. Should've looked at release mode too.

Unfortunately they are not listed properly in the UI but are instead setup as command line arguments. But I reckon that is cmake doing the /external:I thing for each of them instead of them being regular include directories.

**Comment by memsharded** [comment]
> Unfortunately they are not listed properly in the UI but are instead setup as command line arguments. But I reckon that is cmake doing the /external:I thing for each of them instead of them being regular include directories.

Not sure what you mean, that the ``Debug/Release`` configurations are not listed in the UI? Up to my knowledge cmake generates VS projects with this. The ``external:I`` thing might be a different thing, related to include directories and maybe intellisense highlighting (or incorrectly tagging as non-existing, even if the project compiles correctly)? This would be more related to ``cmake``, not conan, yes.

**Comment by Sil3ntStorm** [comment]
Not about the Debug / Release configurations, those are there. It was more about the include directories, they are not in the place where you'd expect them in the VS UI. For some reason they get generated as `/external:I` command line parameters instead.

In any case it works.

**Comment by memsharded** [comment]
> Not about the Debug / Release configurations, those are there. It was more about the include directories, they are not in the place where you'd expect them in the VS UI. For some reason they get generated as /external:I command line parameters instead.

yes, this is expected in CMake, because the packages used via ``find_package()`` (external dependencies) will be labeled as ``/external`` in VS, it is standard CMake behavior.

**Comment by memsharded** [comment]
As it works, I think we can close the ticket now, feel free to create new tickets if there is any further question, thanks for the feedback!
