### ISSUE TITLE
[bug] Conflict when running install(RUNTIME_DEPENDENCY_SET my_app_deps ...)

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#16726]
### Describe the bug

```bash
version: 2.5.0
conan_path: /opt/venv/bin/conan
python
  version: 3.9.18
  sys_version: 3.9.18 (main, May 16 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
  sys_executable: /opt/venv/bin/python3
  is_frozen: False
  architecture: x86_64
system
  version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
  system: Linux
  release: 5.15.153.1-microsoft-standard-WSL2
  cpu: x86_64
```

### How to reproduce it

Hello,

Please clone the following repo https://github.com/Todiq/test_conan

On linux, run `python3 build.py`

I am getting the following error:
```bash
CMake Error at beta/build/linux-clang/Release/cmake_install.cmake:66 (file):
  file Multiple conflicting paths found for libz.so.1:

    /opt/conan/p/b/test_054688ffad74d/p/lib/libz.so.1
    /opt/conan/p/zlib8d8d9c4bb2ec5/p/lib/libz.so.1
```

Now, I get a similar error on CI, when it clashes with the system version of the same lib. But I guess the origin of the issue is the same. Would you mind having a look?

Thanks in advance!

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your report.

Would you please mind printing the ``CONAN_RUNTIME_LIB_DIRS`` variable in your CMakeLists.txt and sharing its value?

I am cc`ing @jcar87, maybe he can also help with this.

**Comment by jcar87** [comment]
The alpha build scripts are bundling zlib here: https://github.com/Todiq/test_conan/blob/main/alpha/CMakeLists.txt#L54-L69
and beta is doing the same https://github.com/Todiq/test_conan/blob/main/beta/CMakeLists.txt#L46-L56

the the build scripts for beta, which _also_ depends on zlib, try to resolve libz.so, it will find it in both the zlib package _and_ the alpha package - 

this is something to avoid - as zlib is visible multiple times. 

I suppose it depends on what the final goal is here - but some options:
* amend the requirements such that if you intend for one recipe to bundle zlib and then _provide_ zlib to its consumers, zlib is no longer referenced by the consumer (the new vendor feature may be useful)
* if packages are to be consumed independently and conan is to satisfy zlib, don't bundle it in any other package

the logic here: https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#conan-runtime-lib-dirs is intended for final applications to bundle everything - typically useful for devs who create standalone bundles with all dependencies, to be distributed outside of Conan

**Comment by Todiq** [comment]
@memsharded @jcar87 

Thanks for your answers. Indeed, removing the whole block from `alpha` fixed the issue. I also managed to understand the origin of the error in my company's project.

I would like to package a final application and deliver it in the form of a Docker image which takes `FROM scratch` as a source.

To do so, I need to embed system libraries as well. Thus, I edited the `install()` to do so:

```cmake
install(RUNTIME_DEPENDENCY_SET my_app_deps
	PRE_EXCLUDE_REGEXES
		[=[api-ms-]=] # VC Redistibutable DLLs
		[=[ext-ms-]=] # Windows extension DLLs
		[[kernel32\.dll]] # Default in conan doc
		# [[libc\.so\..*]] [[libgcc_s\.so\..*]] [[libm\.so\..*]] [[libstdc\+\+\.so\..*]] # Default in conan doc
	POST_EXCLUDE_REGEXES
		[=[.*system32\/.*\.dll]=] # Windows system DLLs
		# [=[^\/(lib|usr\/lib|usr\/local\/lib)]=] # Unix system libraries
	DIRECTORIES ${CONAN_RUNTIME_LIB_DIRS}
)
```

But that leads to the following error:

```bash
CMake Error at build/linux-clang-17-x86_64/Release/cmake_install.cmake:81 (file):
  file Multiple conflicting paths found for libxml2.so.2:
    /builds/technology_extensions/cpp/build/linux-clang-17-x86_64/Release/generators/../../../../.conan/p/libxmb3e2d3365a661/p/lib/libxml2.so.2
    /lib64/libxml2.so.2
```

How could I both include system libraries and conan dependencies without it clashing?

Adding `[[libxml2\.so\..*]]` to `PRE_EXCLUDE_REGEXES` skips the lib entirely (from conan as well).

I understand it is more of a cmake issue than a conan one, but I think this could be added to the docs. What do you think?

**Comment by Todiq** [comment]
Also, I am getting a ton of warnings:

```bash
...
CMake Warning at build/linux-clang-17-x86_64/Release/cmake_install.cmake:81 (file):
  Dependency libicui18n.so.72 found in search directory:
    /builds/technology_extensions/cpp/.conan/p/icu0b46e1efb06e0/p/lib
  See file(GET_RUNTIME_DEPENDENCIES) documentation for more information.
CMake Warning at build/linux-clang-17-x86_64/Release/cmake_install.cmake:81 (file):
  Dependency libicuuc.so.72 found in search directory:
    /builds/technology_extensions/cpp/.conan/p/icu0b46e1efb06e0/p/lib
  See file(GET_RUNTIME_DEPENDENCIES) documentation for more information.
CMake Warning at build/linux-clang-17-x86_64/Release/cmake_install.cmake:81 (file):
  Dependency libicudata.so.72 found in search directory:
    /builds/technology_extensions/cpp/.conan/p/icu0b46e1efb06e0/p/lib
  See file(GET_RUNTIME_DEPENDENCIES) documentation for more information.
CMake Warning at build/linux-clang-17-x86_64/Release/cmake_install.cmake:81 (file):
  Dependency libxerces-c-3.2.so found in search directory:
    /builds/technology_extensions/cpp/.conan/p/xercec2a38c9dad6ac/p/lib
  See file(GET_RUNTIME_DEPENDENCIES) documentation for more information.
...
```

**Comment by jcar87** [comment]
> @memsharded @jcar87
> 
> Thanks for your answers. Indeed, removing the whole block from `alpha` fixed the issue. I also managed to understand the origin of the error in my company's project.
> 
> I would like to package a final application and deliver it in the form of a Docker image which takes `FROM scratch` as a source.
> 
> To do so, I need to embed system libraries as well. Thus, I edited the `install()` to do so:
> 
> ```cmake
> install(RUNTIME_DEPENDENCY_SET my_app_deps
> 	PRE_EXCLUDE_REGEXES
> 		[=[api-ms-]=] # VC Redistibutable DLLs
> 		[=[ext-ms-]=] # Windows extension DLLs
> 		[[kernel32\.dll]] # Default in conan doc
> 		# [[libc\.so\..*]] [[libgcc_s\.so\..*]] [[libm\.so\..*]] [[libstdc\+\+\.so\..*]] # Default in conan doc
> 	POST_EXCLUDE_REGEXES
> 		[=[.*system32\/.*\.dll]=] # Windows system DLLs
> 		# [=[^\/(lib|usr\/lib|usr\/local\/lib)]=] # Unix system libraries
> 	DIRECTORIES ${CONAN_RUNTIME_LIB_DIRS}
> )
> ```
> 
> But that leads to the following error:
> 
> ```shell
> CMake Error at build/linux-clang-17-x86_64/Release/cmake_install.cmake:81 (file):
>   file Multiple conflicting paths found for libxml2.so.2:
>     /builds/technology_extensions/cpp/build/linux-clang-17-x86_64/Release/generators/../../../../.conan/p/libxmb3e2d3365a661/p/lib/libxml2.so.2
>     /lib64/libxml2.so.2
> ```
> 
> How could I both include system libraries and conan dependencies without it clashing?
> 
> Adding `[[libxml2\.so\..*]]` to `PRE_EXCLUDE_REGEXES` skips the lib entirely (from conan as well).
> 
> I understand it is more of a cmake issue than a conan one, but I think this could be added to the docs. What do you think?

Conan serves as a way to isolate your build system and your project from different versions of the same dependencies that may exist on the system. This is a key feature of Conan.
By commenting out the regex rule that would otherwise tell CMake to exclude the system libraries - you are exposing the cmake runtime library searcher to dependencies from both places, and it is failing - one may argue it should not fail but rather pick up the first one (as the runtime linker should) -  you may wish to raise an issue in the CMake project for this. 

On the other hand, in your case I can see that libxml2.so is provided from conan, but also found in `/lib64` - I would simply _uncomment_ the following but also add `lib64`:

```
		# [=[^\/(lib|usr\/lib|usr\/local\/lib|\/lib64)]=] # Unix system libraries
``` 

I would not try to package the system dependencies at all on Linux - a Linux docker image is already likely to have the minimum runtime it needs from the system, assuming you're using conan for everything else.

**Comment by Todiq** [comment]
Ok, that seems clear enough. Thank you very much!
