### ISSUE TITLE
Show full traceback when an exception is uncaught

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#1672]
Consider this example:

```py
class TracbackFail(ConanFile):
  name = "tbfail"
  version = "1.0"

  def foo(self):
    raise RuntimeError("foo threw this exception")

  def bar(self):
    self.foo()

  def quaz(self):
    self.bar()

  def build(self):
    self.quaz()
```

Upon building this package, the following error message is produced:

```
ERROR: tbfail/1.0@me/stable: Error in build() method, while calling 'foo', line 9
        raise RuntimeError("foo threw this exception")
        RuntimeError: foo threw this exception
```

Unfortunately, this often lacks vital information because the full traceback is hidden. What I would like to see is something like this:

```
tbfail/1.0@me/stable: Calling build()
Traceback (most recent call last):
  File "C:\Users\sztomi\.conan\data\tbfail\1.0\me\stable\export\conanfile.py", line 20, in build
    self.quaz()
  File "C:\Users\sztomi\.conan\data\tbfail\1.0\me\stable\export\conanfile.py", line 16, in quaz
    self.bar()
  File "C:\Users\sztomi\.conan\data\tbfail\1.0\me\stable\export\conanfile.py", line 13, in bar
    self.foo()
  File "C:\Users\sztomi\.conan\data\tbfail\1.0\me\stable\export\conanfile.py", line 10, in foo
    raise RuntimeError("foo threw this exception")
RuntimeError: foo threw this exception
```

Note, this is exactly what would be printed if conan itself didn't catch the exception to print a formatted/colored message. That is fine, but more information is needed. To produce the above output, I did this change:

```py
  def build(self):
    try:
      self.quaz()
    except:
      traceback.print_exc()
``` 

The `traceback` module has everything needed for this. Particularly, `traceback.format_exc` does exactly what `print_exc` does, but returns a string instead of printing to stdout. That could be used to stylize the output to match the conan colors.

**Comment by lasote** [comment]
```
ERROR: tbfail/1.0@ll/jj: Error in build() method
In 'build' (line 19): self.quaz()
 In 'quaz' (line 16): self.bar()
  In 'bar' (line 13): self.foo()
   In 'foo' (line 10): raise RuntimeError("foo threw this exception")

RuntimeError: foo threw this exception
```

Looks good?

**Comment by sztomi** [comment]
As per our discussion via slack, I'd opt for a more traditional format (as in my first post). Two reasons:

  * Using a different traceback format requires cognitive overhead to mentally parse
  * We want to be able to see the callstack outside the conanfile as well (we have an inhouse utility module that we import. Sometimes the failure happens deep inside that module)

**Comment by lasote** [comment]
Note for myself and @memsharded, now we were trying to avoid long and confusing tracebacks with internal conan/python code, so we will need to detect that the code is in a user module to show the traces as well.

**Comment by sztomi** [comment]
Actually, as a user I'd rather see the tracebacks for internal *uncaught* exceptions. If they reach the "surface" they are relevant for me anyway.

**Comment by tru** [comment]
I am happy for this to be configurable with a environment variable as well. I understand your idea - but for advanced users it’s frustrating when you don’t know the “real” error.

**Comment by memsharded** [comment]
Yes the story was:

- Traces were added for not controlled exceptions.
- Errors inside conan methods are wrapped, because many users would be just overwhelmed with a full trace, and only the line that caused the error is output

Also, when outputting even internal (from the conan method) traces, that would be very scary for many users, because you actually see traces from the python lib, conan python dependencies, etc, not only your code.

Not sure best approach, maybe opt-in behavior with env-var for advanced users.

**Comment by sztomi** [comment]
If it's opt-in in any shape or form, I think it would make sense to make it explicit that the traceback is truncated and what the user needs to do in order to see the full trace. BTW I support the environment variable as a way to opt-in.
