### ISSUE TITLE
[question] How can I distinguish release and debug versions when I upload pacakges to jfrog artifactory automatically

### ISSUE THREAD

**Issue by Anchorli** [conan-io/conan#16725]
### What is your question?

As the title suggests，I have two repositories named separately as conan-stable and conan-debug. How can I configure to upload the packages to conan-stable when version is lick 1.1.1 and upload the packages to conan-debug when version is 1.1.1-alpha 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by Anchorli** [comment]
Also, How can the aritfactory refuse the 1.1.1-alpha version upload to conan-stable

**Comment by memsharded** [comment]
Hi @Anchorli 

Thanks for your question.

There is no configuration to upload certain packages names to certain repositories, the upload of packages is always "explicit", if you are building a pre-release like ``-alpha``, then the pipeline should be uploading to the ``-r=conan-debug`` repo (by the way, the ``debug`` name doesn't sound great, as it sounds related to packages debug configuration, while this seems more like a ``prerelease`` repo).

So this is something that is explicitly implemented by the pipeline.

> Also, How can the aritfactory refuse the 1.1.1-alpha version upload to conan-stable

I don't know if Artifactory has any built-in feature to reject package uploads based on package name. I have checked a bit, but I haven't found anything. If you are using some pro version, I'd recommend to reach out to support and ask about it.

In any case, from the client side, it should be relatively easy to implement checks, like periodic checks on CI or whatever, just with a ``conan list "*/*-*" -r=conan-stable --format=json > myfile.json`` and erroring if the ``myfile.json`` contain any result.

**Comment by Anchorli** [comment]
Hi @memsharded 

Thanks for your answer.

I can configure the artifactory to avoid uploading -alpha to conan-stable. But I can not avoid uploading versions such as 1.1.1 to conan-prerelease. In this way，there will be two same version in conan-stable and conan-prerelease. Is there a priority so that I can use conan-stable rather than conan-prerelease in my local development environment

**Comment by memsharded** [comment]
> I can configure the artifactory to avoid uploading -alpha to conan-stable. But I can not avoid uploading versions such as 1.1.1 to conan-prerelease. In this way，there will be two same version in conan-stable and conan-prerelease. Is there a priority so that I can use conan-stable rather than conan-prerelease in my local development environment

Sure, in fact it is not a problem to have the same package stored and duplicated in two different repos, and this is part of recommended CI pipeline flows using promotions (package copies between server repos).

Conan has some mechanisms to prioritize different packages:
- Using ``remote`` repository order and enable/disable. By controlling the remotes on the client side, it is possible to enable/disable remotes. Also package resolution is resolved by default in the "first matching dependency returns", so if you put the repo that you want as the first remote, and a valid version is found there, it will stop searching in other remotes.
- Pre-releases have explicit control with the ``core.version_ranges:resolve_prereleases`` ``conf`` in the client side, so this can garantee that prereleases are not used during depenency resolution.

**Comment by Anchorli** [comment]
Thanks @memsharded

**Comment by memsharded** [comment]
As a side note, please check the "custom commands" in Conan 2: https://docs.conan.io/2/reference/extensions/custom_commands.html

With this, you can create your own ``upload`` command with the logic that you want, that automatically define the remotes that you want and that it can also do extra checks after upload. The command can be easily shared with ``conan config install`` or ``conan config install-pkg``.
