### ISSUE TITLE
[question] header-only lib component

### ISSUE THREAD

**Issue by Dimitrius-dev** [conan-io/conan#16736]
### What is your question?

I have read docs part about library components declared in `package_info` method. Is there a way to set library components as a `header-only` type according to cmake `add_library(target INTERFACE...)`?

Example:
Some library contains components part1, part2, part3... . Some of this components are templates. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Dimitrius-dev 

Thanks for your question.

The components specification allows to not define the ``.libs`` field, so something like:

```python
def package_info(self):
    self.components["myregularlib"].includedirs = ["include"]
    self.components["myregularlib"].libs= ["myreglib"]
    self.components["myregularlib"].libdirs= ["lib"]
    # This myheaderlib is a header-only library
    self.components["myheaderlib"].includedirs = ["include"]
    self.components["otherlib"].includedirs = ["include"]
    self.components["otherlib"].libs= ["otherlib"] 
    ...
```

Is this what you are looking for?

**Comment by Dimitrius-dev** [comment]
Yes, that's it, thank you so much!
