### ISSUE TITLE
Uploading only new packages created with "conan install"

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#16746]
### What is your question?

Hello Conaneers (Yes, I just made that up :-) )!

conan  version: 2.4.0

If I do a `conan install...--build missing`, is there a single command that I can execute to only upload the new packages that were built during conan install?

I know I can do something like `CONAN_HOME=/my/temporary/home conan install... ; CONAN_HOME=/my/temporary/home conan upload -r my-remote "*" -c`, but I'm looking for a method using the default CONAN_HOME?

Regards
Klaus

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

> Hello Conaneers (Yes, I just made that up :-) )!

I approve 😄 , thanks for your question.

> If I do a conan install...--build missing, is there a single command that I can execute to only upload the new packages that were built during conan install?

It is not a single command, but 2:

```bash
$ conan install ... --build=missing --format=json > graph.json
$ conan list --graph=graph.json --graph-binaries=build --format=json > mypkglist.json
$ conan upload --list=mypkglist.json ...
```

Please check https://docs.conan.io/2/examples/commands/pkglists.html#building-and-uploading-packages and let me know if it helps.

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Did the above help? Any further question? Thanks!

**Comment by klausholstjacobsen** [comment]
All good, thanks!
