### ISSUE TITLE
Trying to adapt our C++/CMake components to conan2...

### ISSUE THREAD

**Issue by gto406** [conan-io/conan#16748]
Hello Conan experts, thank you for allowing the community to file issues.

I have run into a problem, and seek clarification on how best to adapt conan 2 to this structure.

BR/Brian.

**Context**: C++ (gnu g++), CMake (3.25+), Ninja generator (albeit Unix Makefile are fine too).
**Goal**: Adapt a series of components (packages) to support Conan 2
**Problem**: having issues understanding directory layout for Conan2, simple case works fine, components that depend on local + 3rd party lib/packages cause issues.

**Directory construct**: have adopted [BorisK's canonical structure](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1204r0.html).

An example (names altered) are as follows:
```
├── CMakeLists.txt
├── CMakeUserPresets.json
├── LICENSE
├── README.md
├── baz
│   └── foo
│       ├── File1.hpp
│       ├── File2.hpp
│       ├── File2.cpp
│       └── bazfoo-units.test.cpp
├── build
├── cmake
│   └── bazfooConfig.cmake.in
├── conanfile.py
```
The conanfile.py identifies two (2) requirements: pkg/library fuBu/0.4.0* and 3rd-party nlohmann_json/3.11.3.  
   - pkg fuBu/0.4.0 is found when doing a 'conan list fuBu' <- in my local cache

```
class BazfooConan(ConanFile):
    name = "bazfoo"
    version = "0.6.0"
    settings = "os", "compiler", "build_type", "arch"

    # Direct dependency requirements listed here...
    def requirements(self):
        self.requires("nlohmann_json/3.11.3")
        self.requires("fuBu/0.4.0")

    # Build tool requirements listed here...
    def build_requirements(self):
        self.tool_requires("cmake/3.25.3")

    # Layout...
    def layout(self):
        cmake_layout()

    # Build - primitive, runs unit-test(s) 
    def build(self):
        # Location of unit test(s)
        utpath = os.path.join(self.source_folder, self.folders.build)
        message4 = f'build() - Unit-test: {utpath}'
        self.output.info(message4)

        # CMake configure, then build...
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

        # Unconditionally run unit-test(s)
        self.run(os.path.join(utpath, "bazfoo-units"))

    # Package - invokes install target from CMakeLists.txt
    def package(self):
        cmake = CMake(self)
        cmake.install()

    # Export - copy files from user folder to Conan cache folders
    #            - export_source is omitted as it is the same, except it copies files to tgt='self.export_sources_folder'
    def export(self):
        # For now, we copy everything - at some point, this may change
        copy(self, "CMakeLists.txt", self.recipe_folder, self.export_folder)
        copy(self, "CMakeUserPresets.json", self.recipe_folder, self.export_folder)
        copy(self, "LICENSE", self.recipe_folder, self.export_folder)
        copy(self, "README.md", self.recipe_folder, self.export_folder)
        copy(self, "baz/foo/*.cpp", self.recipe_folder, self.export_folder, True)
        copy(self, "baz/foo/*.hpp", self.recipe_folder, self.export_folder, True)
        copy(self, "cmake/*", self.recipe_folder, self.export_folder, True)
```
If I invoke 'conan build . -s build_type=Release' - CMakeLists.txt file is found, however the source (i.e. baz/foo) is missing.  Specifically:

CMake Error at CMakeLists.txt:21 (add_library):
  Cannot find source file:
       baz/foo/File1.hpp 

I am not 'welded' to the canonical structure outlined above, but I did like the way it forces includes to utilize '#include < path/to/hpp-file>' - narrows the eligible paths searched for include directories - my understanding.

If someone can point out what I am doing wrong, would greatly appreciate it.  

Thank-you!

**Comment by memsharded** [comment]
Hi @gto406 

Thanks for your question.
This question doesn't seem very specific to one of the repo examples so I am moving it to the main Conan client repo, as this seems a generic Conan client question.

**Comment by memsharded** [comment]
Regarding your usage of ``def export(self):``, I'd say it wouldn't be correct. It should be done exclusively in the ``export_source()`` method, not in ``export()``. The ``export()`` is limited to files that the ``conanfile.py`` script will load, such as ``conandata.yml`` (this ``conandata.yml`` is not necessary, as it is exported automatically). In any case, the ``export()`` is not related to this ticket, as the ``conan build`` local command is not doing the ``export()`` or the ``export_source()`` at all.

Regarding ``self.requires("fuBu/0.4.0")``, I guess that is just a placeholder, Conan 2 doesn't allow uppercase in package names. In any case, I think the requirements are not related to this case at all, they could be removed to reduce the example and have a more minimal repro.

Quick question. Does it work with a ``conan create`` and only fails with the local ``conan build``?

I think this could greatly benefit from a minimal repro case, I'll try to quickly set one up.

**Comment by memsharded** [comment]
Please check this code: [foo.zip](https://github.com/user-attachments/files/16419753/foo.zip)

Both ``conan create .`` and ``conan build .`` works well. Please let me know if this helps.

**Comment by gto406** [comment]
Hello James,

Your correct (fuBu) a placeholder - likely doesn’t impact the issue.

I have not tried a local build.  I assume you mean a separate configure/build in the source directory of bazfoo?  I will check that this evening - and reply back tonight.

BR/Brian.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by memsharded** [comment]
> I have not tried a local build.  I assume you mean a separate configure/build in the source directory of bazfoo?  I will check that this evening - and reply back tonight.

I meant, ``conan build`` does a local build, building the project in user space, but not creating a package. On the other hand ``conan create`` does a build in the local cache, then call ``package()`` to create a package. The layout in both places might not be identical, so it is possible that one works but not the other.

**Comment by gto406** [comment]
I tried the local build - by that I mean invoking…

```
> conan install . --build=missing
   Result: successfully see the build sub-folder in my local bazfoo 
> cd build/Release
> source ./generators/conanbuild.sh
   Result: no errors, just comes back silently
> cmake ../.. -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release 
   Result: ( see clip of output below):
 
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'fubu::fubu'
-- Conan: Target declared 'nlohmann_json::nlohmann_json'
-- Configuring done
CMake Error at CMakeLists.txt:80 (add_executable):
  Cannot find source file:

    baz/foo/bazfoo-units.test.cpp

```

I shall try the foo.zip you very kindly provided.  FYI, I tried `conan build` and same result as the manual build, above. 

Note: I had one error in my def layout() method.  I should have called cmake_layout(self), I fixed that in the run above.

Further updates tomorrow!  Thank you! 😊

**Comment by gto406** [comment]
Hello James!

Hope you are having a great day.  I tried the foo dot zip you created for me and my results are as follows:

Had some minor issues getting the structure to ‘mimic’ what I had, however I utilized the basis of the top-level `conanfile.py` and the test_package to create my own lib/pkg known as  `bazfoo` which consists of:
    - the test code from test_package - i.e. `example.cpp`
    - modified version of `CMakeLists.txt` which combines mine/your versions
    - I modified the system, to create a stand-alone exec (not really a unit-test) to verify the main - known as `bazfoo-test`
    - The stand-alone exec has a dependency on `nlohmann_json’

After re-creating the dir-structure, I tried a local/manual build in-place (apologies if my terms are inaccurate/incorrect).  This consisted of:

  ```
> conan install . --build=missing
  > cd build/Release
  > source generators/conanbuild.sh
  > cmake ../.. -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
  > cmake —build .

  # All went well producing an executable bazfoo-test which when run produces:
  > {"foo":["test_package","nlohmann_json"]}
```


I then re-ran the above, using:
```
  > conan create . --settings build_type=Release
  
  # the package seemed to get built, and exported as I was able to perform a:

  > conan list bazfoo
  
  # conan 2.x returned:
Found 1 pkg/version recipes matching bazfoo in local cache
Local Cache
  bazfoo
    bazfoo/0.3.0
```

I think (I am hopeful) I can adapt this to my current structure, and add the unit-testing and other components in.  I would like to contribute this example - if it helps - to Conan, so that this may help others.  You can clone the public GitHub repository [here](https://github.com/gto406/conanTst.git).

I will try and get a little further (today/Wednesday) to see if I can get back to where I was.  I was in the process of converting some package libraries (C++/CMake) to conan.

BR/Brian.

**Comment by gto406** [comment]
I validated the issue with my own libraries - that originally were giving me issues, including a bazfoo pkg/lib that had a cached (local-dev) dependency + a third-party (nlohmann_json).  I have overcome the issue based on James very helpful inputs - and I am moving forward!  Thanks to the quick-response of the conan dev-team.

BR/Brian.

**Comment by memsharded** [comment]
> I validated the issue with my own libraries - that originally were giving me issues, including a bazfoo pkg/lib that had a cached (local-dev) dependency + a third-party (nlohmann_json). I have overcome the issue based on James very helpful inputs - and I am moving forward! Thanks to the quick-response of the conan dev-team.

Great to know, thanks very much for the feedback and the detailed follow up! 🙂 

We are happy to help, don't hesitate to create new tickets for any further question or issue you might have.
