### ISSUE TITLE
Multi-config props files

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [conan-io/conan#1674]
Hello.

I have test case: on my work we use Visual Studio. Now i am trying to switch to Conan from SVN Externals.

Usually Visual Studio developers have at least 4 configurations (x32/x64 * Release/Debug). Someone have more.

For comfortable managing dependency will be great if all dependecies will be in one conanfile.props file, because now we should manage at least four files and it's annoying.

**Comment by lasote** [comment]
Hi, @ZaMaZaN4iK thanks for the feedback. As you know currently is not possible to do it, but please, could you provide an example of how the property files could look like for that four configurations? It would help to understand and see if we can develop a fix.

**Comment by ZaMaZaN4iK** [comment]
@lasote I am not so familiar with Visual Studio's property sheet format. But i would like to see inside conan's property sheet one XML part for every configuration. I am not sure, is this possible or not.

**Comment by SSE4** [comment]
@memsharded  I think it could be done by adding new generator similar to cmake_multi, e.g. props_multi. Visual Studio props support imports and conditional statements, so master props file can include children for each configuration. what do you think?

**Comment by memsharded** [comment]
Yes, I think this is the way to go, but I still have to learn about the syntax. I am afraid that props files do not allow to include other file like CMake, so the ``multi`` generator should load&modify an already generated file to append the new configuration, which might be tricky to implement. Then compare to the multiple generation of files, and including different .props files in Visual Studio under the different configurations, which is also possible.

**Comment by memsharded** [comment]
I have added docs for generating the different files as it has to be done now: https://github.com/conan-io/docs/pull/321/files

Just to be sure:
- the process of installing the different configurations is still necessary, that cannot be avoided
- The goal would be to just have to include 1 file in the VS IDE, instead of 4 (if 32&64) or 2 files (if only Debug/Release)

I am having a look, if vs.props files allow to include other files while defining the configuration, it might be doable, otherwise, it would be too much to avoid 1 or 3 extra clicks in the IDE.

**Comment by SSE4** [comment]
@memsharded I was able to solve the problem with the following master props file:
```
<?xml version="1.0" encoding="utf-8"?> 
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" >
    <Import Condition=" '$(Configuration)' == 'Debug'   And '$(Platform)' == 'Win32' " Project="debug32\conanbuildinfo.props"/>
    <Import Condition=" '$(Configuration)' == 'Debug'   And '$(Platform)' == 'x64' " Project="debug64\conanbuildinfo.props"/>
    <Import Condition=" '$(Configuration)' == 'Release' And '$(Platform)' == 'Win32' " Project="release32\conanbuildinfo.props"/>
    <Import Condition=" '$(Configuration)' == 'Release' And '$(Platform)' == 'x64' " Project="release64\conanbuildinfo.props"/>
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup />
</Project>
```
I will try to implement visualstudio_multi generator same way as cmake_multi works and submit PR

**Comment by memsharded** [comment]
Ok, thanks for the info, that really helps!

Good, if you are able to submit a PR, great, otherwise, no problem, with that info it won't take me too much. Thanks!

**Comment by memsharded** [comment]
@ZaMaZaN4iK This has been released as the ``visual_studio_multi`` generator:
http://docs.conan.io/en/latest/reference/generators/visualstudiomulti.html
