### ISSUE TITLE
[question] how to get the source_folder of a dependency inside a generator ?

### ISSUE THREAD

**Issue by M0rtalPhe0nix** [conan-io/conan#16740]
### What is your question?

how to get the source_folder of a dependency inside a generator ? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I guess you found the answer yourself @M0rtalPhe0nix? Don't hesitate to re-open or create new tickets for any further question.
