### ISSUE TITLE
[question] Is it possible to add additional information to exceptions and display them in the console?

### ISSUE THREAD

**Issue by elvisdukaj** [conan-io/conan#16747]
### What is your question?

I would like to catch an exception and add some additional information to it. The following snippet tries to download a file during the `build`

```python
    def build(self):
        try:
            get(self, **self.conan_data["sources"][self.version][str(self._settings_build.os)])

        except Exception as e:
            error_message = f"""
This is a custom message that explains what happened: for instance, instruction on how to mount the network device on different operating systems.

  - On Windows do this
  - On Linux do that
  - On macOS to this
"""
            e.add_note(error_message)
            raise
```

The problem of the above code is that the additional notes are not printed in the console. As workaround I can call `self.output.error(error_message)`.

I am fine with the workaroundm but I am wondering if there is a better way for this.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Try raising a new exception with a new message:
```python
try:
    ...
except Exception as e:
    raise Exception(f"New error message. Original: {e}")
```

**Comment by elvisdukaj** [comment]
Raising a new exception will work, maybe it's not necessary keep the original exception. I think I will go this way for now.

**Comment by memsharded** [comment]
Ok, closing this ticket as resolved then, thanks for the feedback!
