### ISSUE TITLE
[question] What could be the reason for "network: Error downloading file https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.xz"

### ISSUE THREAD

**Issue by ThomasDBecker** [conan-io/conan#16755]
### What is your question?

Hi,

short question, would could be the reason for:

network: Error downloading file https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.xz

![grafik](https://github.com/user-attachments/assets/b53d4366-6b01-48b5-80bf-6450541d7367)

I see this error for 

```
self.requires("grpc/1.54.3")
```

Interesting, if I download the file in the recipe like this (just for testing)...

```
import conan.tools.files as CONAN2_TOOLS_FILES
.
def layout(self):
  CONAN2_TOOLS_FILES.download(self, "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.xz", "nasm-2.16.01.tar.xz", verify=True)
.
```

...it works:
![grafik](https://github.com/user-attachments/assets/904a47a4-11d8-438a-9bcf-3032fbb00fd9)

But of course that doesn't help.

I also tried out **tools.files.download:verify=False** in a way like this:

```
conan install . -c tools.files.download:verify=False --output-folder=out --build=missing --profile:all=./profiles/windows
```
But unfortunately that doesn’t help either.

I can also download this file in the browser without any problems.
![grafik](https://github.com/user-attachments/assets/0c056112-2fb8-4768-be1b-b2f0cea06fd0)
![grafik](https://github.com/user-attachments/assets/12fec703-c055-49cc-bb53-5d90cc1b02a2)

I would be very grateful for any ideas.

**Supplement 01**
In _.venv\Lib\site-packages\conan\tools\files\files:get_ I made the following change
![grafik](https://github.com/user-attachments/assets/39fed5c7-10af-4907-925d-8c7d0cccd4fd)
Then the `conan install...` with `-c tools.files.download:verify=False` command runs through

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @ThomasDBecker,

Thanks a lot for reporting. I think that the config is not working because `-c` will be applied by default to the `host` context but _nasm_ is in the build context. Can you try to do `-c:a tools.files.download:verify=False` instead of just `-c` ? Then the config will be passed to both the `host` and `build` context (`a` stands for _all_) and it should work.

Hope this helps.

**Comment by ThomasDBecker** [comment]
Hi @czoido ,

Thank you for your quick and helpful answer.

Yes, it helps.

Next time I also know where I can search ... ;)

```
-c:b CONF_BUILD, --conf:build CONF_BUILD
-c:h CONF_HOST, --conf:host CONF_HOST
-c:a CONF_ALL, --conf:all CONF_ALL
```

**Comment by czoido** [comment]
> Hi @czoido ,
> 
> Thank you for your quick and helpful answer.
> 
> Yes, it helps.
> 
> Next time I also know where I can search ... ;)
> 
> ```
> -c:b CONF_BUILD, --conf:build CONF_BUILD
> -c:h CONF_HOST, --conf:host CONF_HOST
> -c:a CONF_ALL, --conf:all CONF_ALL
> ```

Great! I'll close the issue then, please feel free to reopen if you have any more questions.
