### ISSUE TITLE
[question] How to avoid Redundancy between Conan and the Package Config File

### ISSUE THREAD

**Issue by pasbi** [conan-io/conan#16756]
My library creates a `MyLibConfig.cmake` file using [`configure_package_config_file`](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html) and installs it using `install(FILES ...)`.

This file looks like
```
set(MYLIB_VERSION @PROJECT_VERSION@)
set(MYLIB_MAJOR_VERSION @PROJECT_VERSION_MAJOR@)
set(MYLIB_MINOR_VERSION @PROJECT_VERSION_MINOR@)
set(MYLIB_PATCH_VERSION @PROJECT_VERSION_PATCH@)
set(MYLIB_COMPILED_WITH_CUDA @HAVE_CUDA@)

@PACKAGE_INIT@

set_and_check(MYLIB_INCLUDE_DIR "@PACKAGE_CMAKE_INSTALL_INCLUDEDIR@")
set_and_check(MYLIB_LIBRARY_DIR "@PACKAGE_CMAKE_INSTALL_LIBDIR@")

include(CMakeFindDependencyMacro)

find_dependency(OpenCV)

if(MYLIB_COMPILED_WITH_CUDA)
  # find CUDA dependencies ...
endif()

include("${CMAKE_CURRENT_LIST_DIR}/MyLibTargets.cmake")

set_target_properties(MyLib::mylib PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${MYLIB_INCLUDE_DIR};${MYLIB_INCLUDE_DIR}/mylib")
```

I recently introduced conan and successfully build a conan package for that library.
However, this `MyLibConfig.cmake` was not used for building that package.

To make a consuming `Application` work, I had to define the extra include path in `package_info` in the `conanfile.py`.
```
    def package_info(self):
        [...]
        self.cpp_info.libs = ["mylib"]
        self.cpp_info.includedirs = ['include', 'include/mylib']
```

This makes me wonder how to make the information of the `MyLibConfig.cmake` available for conan without manually adding it to `cpp_info`?
Apparently, conan is able to do a lot automatically, without the `MyLibConfig.cmake` file:
E.g., it manages to make CMake call `find_dependency(OpenCV)` when configuring `Application`.

But it fails to add the `include/mylib` include path automatically, I had to specify that manually in `package_info`.
It also fails to define the variables in the beginning of `MyLibConfig.cmake`, they're not available in `Application`.

**My Question**:
How and where can I define these things (definitions, targets, include paths, etc.) such that both conan packages and traditional CMake installations include them, without specifying all of that twice?
I guess including that `MyLibConfig.cmake` into the toolchains generated by conan would be a bad idea because it would conflict?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @pasbi 

Thanks for your question.

There are different approaches to this.

First, you can use the ``MyLibConfig.cmake`` file if you package it into your package. See a full working example here: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html

In that case, you don't need to fill the ``package_info()`` method ``cpp_info`` information, but the approach has some known limitations, the most obvious is that it only works for CMake, but not for other build systems, and a less obvious is that the ``multi-config`` setup of some IDEs like Visual Studio will not work as CMake ``find_package()`` doesn't allow to locate different binaries in different directories.

Another approach would be to drop the creation of the ``MyLibConfig.cmake`` from your CMakeLists.txt and then specify only in ``conanfile.py`` recipe ``package_info()`` method the contents of the package. At the moment, and even if some attempts were done to use the CMake FileAPI, it is not possible to "deduce" the information from CMake, definitely not by trying to parse or analyze the contents of CMakeLists.txt files.

Being pragmatic, and with the exception of some very complicated large packages such as Boost or Qt, writing a ``package_info()`` is just a few lines, and if you are the creator of the library and writer of the build scripts, it is a relatively small effort, that is done once, as it is something typically quite stable.


Finally, this duplication, that derives from the lack of standard communication between build systems, will hopefully be superseded some day by the CPS standardization initiative, that we are actively involved in. But this will still take long time, if you are curious you can check our CppCon23 talk, and ongoing work in https://github.com/conan-io/conan/pull/16054

**Comment by pasbi** [comment]
Thanks for the quick reply.
Thanks for the link to the tutorial, I haven't seen it yet and it looks very promising.
Also thank you for the other (pragmatic) proposal, also very promising.
