### ISSUE TITLE
Populate all Bintray Package and Version Fields from Conanfile

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1675]
I'm not sure if this is possible or just not well documented, but there are a number of Bintray fields which don't exactly match up directly with Conanfile fields.  I think the Bintray fields are good and it seems like there should be a mapping.  If re-working the Conan API's to enable this is a huge project, perhaps adding a Bintray API call to set the metadata properly upon deployment when applicable could be a reasonable workaround.

**Comment by sourcedelica** [comment]
Another thing, with the old repo you could easily tell if a package had versions for particular operating systems, compilers, settings, options, etc.  That was very helpful.
