### ISSUE TITLE
[question] Package not found although in cache

### ISSUE THREAD

**Issue by Neumann-A** [conan-io/conan#16750]
### What is your question?

Following situation:
(ignore that the recipe is called protobuf; it is not the conancenter recipe)

The recipe contains the following important parts (the rest can basically be assumed to be some sane default) :
```
    def build_requirements(self):
        if cross_building(self):
            self.tool_requires(f"{self.name}/{self.version}", visible=True)

    def package_id(self):
        if self.context == "build":
            self.info.settings.rm_safe("compiler")
```

The recipe is build with and without `--build-require` into the local cache resulting into:
```
neumann-A@pc:~/src/dev8$ conan list -v -c protobuf/3.0.1-dev.3+v3.21.12.g83db08abc:*
Local Cache
  protobuf
    protobuf/3.0.1-dev.3+v3.21.12.g83db08abc
      revisions
        38c7c967ad11c14747318c1a2c699bde (2024-07-30 08:54:57 UTC)
          packages
            153d90bae8fd802f8b14109f4bd6336f5330c093
              info
                settings
                  arch: x86_64
                  build_type: RelWithDebInfo
                  compiler: gcc
                  compiler.libcxx: libstdc++11
                  compiler.version: 10
                  os: Linux
            5a83d488fab0b9df90332696aa0643a422bfb69e
              info
                settings
                  arch: x86_64
                  os: Linux
```

So now I am trying to compile for a different arch with the build profile:
```
Profile build:
[settings]
arch=x86_64
os=Linux
```

```
======== Computing dependency graph ========
protobuf/3.0.1-dev.3+v3.21.12.g83db08abc: Checking remote: artifactory
cmake/2.1.0+v3.29.3.g2f48341: Checking remote: artifactory
Graph root
    cli
Requirements
    protobuf/3.0.1-dev.3+v3.21.12.g83db08abc#38c7c967ad11c14747318c1a2c699bde - Not in remote
Build requirements
    cmake/2.1.0+v3.29.3.g2f48341#8a9e5ecaca21e00540ebde360b814dc7 - Cache (artifactory)
    protobuf/3.0.1-dev.3+v3.21.12.g83db08abc#38c7c967ad11c14747318c1a2c699bde - Not in remote
Resolved version ranges
    cmake/[^2.0]: cmake/2.1.0+v3.29.3.g2f48341
```
ok it does not find it in the remote but it should have a locally cached version, however

```
======== Computing necessary packages ========
....
protobuf/3.0.1-dev.3+v3.21.12.g83db08abc: Forced build from source
....
protobuf/3.0.1-dev.3+v3.21.12.g83db08abc: Forced build from source
Requirements
    protobuf/3.0.1-dev.3+v3.21.12.g83db08abc#38c7c967ad11c14747318c1a2c699bde:22976c0bcfaa859ff842ab52f878a74c7f4e8590 - Build
Build requirements
    cmake/2.1.0+v3.29.3.g2f48341#8a9e5ecaca21e00540ebde360b814dc7:6b1ce4229bef37a01679c82e63e8e76eb389f79b#6852a9b3551370d58de1d9d47cec69f7 - Cache
    protobuf/3.0.1-dev.3+v3.21.12.g83db08abc#38c7c967ad11c14747318c1a2c699bde:5a83d488fab0b9df90332696aa0643a422bfb69e - Build
```
Shows that `protobuf/3.0.1-dev.3+v3.21.12.g83db08abc#38c7c967ad11c14747318c1a2c699bde:5a83d488fab0b9df90332696aa0643a422bfb69e` is marked for `Build` instead of `Cached`

From my investigations I concluded that https://github.com/conan-io/conan/blob/f494458dd7b2826be30c977970a274cb048f392d/conans/client/graph/graph_binaries.py#L44
is not good enough to correctly identify and deal with with this case. 
Any suggestions on how to solve it?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Neumann-A 

Thanks for your question.

I think this case is intended to be covered by the explicit ``--build=missing:[pattern]``, that is:

```bash
$ create ... --build=missing:protobuf
```

The placeholder ``&`` to indicate the current package also should work:
```
$ create ...  --build=missing:&
```

This is because by default the ``conan create`` command defaults to ``--build=<current-pkg-name>``. I think that the ``--build=missing:<current-pkg-name>`` would be a better default, but I tried to change it some time ago, and I couldn't do it, because it would have been breaking behavior. But it would be better to avoid re-building the same binary that already exists in the server, avoiding wasting time and resources. I'd suggest to use this approach in CI with ``--build=missing:<pkg-name>``.

In the case above the ``conan create`` default is forcing to build also the "build context" ``tool_require``, even if it exists already. 
Please try the above and let me know.

**Comment by Neumann-A** [comment]
works
