### ISSUE TITLE
cmake_build_modules failing when dependent on each other

### ISSUE THREAD

**Issue by LucidDistress** [conan-io/conan#16768]
### What is your question?

I have a question regarding cmake_build_modules. I have multiple .cmake files I would like to include as part of a product, but several of them depend on each other and that is causing the include step to fail. I even tried ordering them so the files that need to be included come first in the list. As an example, generated_dependencies.cmake is included in generated_interface.cmake. generated_dependencies.cmake gets included correctly, but when I conan includes generated_interface.cmake, I get a "include could not find requested file" error. I tried doing something similar using builddirs at some point, but I could not get that to work either. Suggestions?

```
def package_info(self):
        cmake_modules = list()
        cmake_modules.append(path.join("cmake/modules", "ada_rules.cmake"))
        cmake_modules.append(path.join("cmake/modules", "CoreDX_config.cmake"))
        cmake_modules.append(path.join("cmake/modules", "FindCoreDX.cmake"))
        cmake_modules.append(path.join("cmake/modules", "generated_dependencies.cmake"))
        cmake_modules.append(path.join("cmake/modules", "generated_interface.cmake"))
        cmake_modules.append(path.join("cmake/modules", "idl_rules.cmake"))
        self.cpp_info.set_property("cmake_build_modules", cmake_modules)

        self.cpp_info.components["InterfaceBuilder"].includedirs= ["scripts/interface_builder"]
        self.cpp_info.components["InterfaceFactory"].includedirs= ["include/interface_factory"]
        self.cpp_info.components["DdsCommon"].includedirs= ["include/dds"]

        if self.settings.build_type == "Debug":
            self.cpp_info.components["SharedMemoryUtils"].libs = ["shared_memory_utilsd"]
        else:
            self.cpp_info.components["SharedMemoryUtils"].libs = ["shared_memory_utils"]

        self.cpp_info.components["SharedMemoryUtils"].includedirs = ["include/shared_memory_utils"]
        self.cpp_info.components["SharedMemoryUtils"].system_libs = ["rt", "pthread"]
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @LucidDistress,

Thank you for reporting this issue. I have been trying to reproduce it without success. I created a[ repository with a simple example](https://github.com/czoido/test-build-modules-includes) that includes three build modules: `mod1.cmake` includes `mod2.cmake`, and `mod2.cmake` includes `mod3.cmake`. Everything appears to work fine when running `conan create`.

Is this similar to your case? Could I be missing something? Please take a look at the example and let me know.

**Comment by LucidDistress** [comment]
> Hi @LucidDistress,
> 
> Thank you for reporting this issue. I have been trying to reproduce it without success. I created a[ repository with a simple example](https://github.com/czoido/test-build-modules-includes) that includes three build modules: `mod1.cmake` includes `mod2.cmake`, and `mod2.cmake` includes `mod3.cmake`. Everything appears to work fine when running `conan create`.
> 
> Is this similar to your case? Could I be missing something? Please take a look at the example and let me know.

One difference I see is that in your package section, you use a manual copy command for your modules vs I used the built in cmake install for that. Would that make a difference? I will go ahead and test that regardless.

**Comment by LucidDistress** [comment]
I found the reason yours worked. I am used to just being able to do include(file) because of everything being in my CMAKE_MODULE_PATH. I saw that your includes looked more like this:

`include(${CMAKE_CURRENT_LIST_DIR}/generated_dependencies.cmake)`

Adding that seemed to fix it. Thank you!

**Comment by czoido** [comment]
> 
> Adding that seemed to fix it. Thank you!

I'm glad that it worked! Thanks a lot!
