### ISSUE TITLE
[question] How to propagate a path to a consumer?

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16769]
Hello,

So, I'm building IKT 5.3 and I'm experiencing a difficulty to propagate an information to its test package (this will likely be an issue to other ITK consumers too).  

The test package tries to use the following CMake script : `C:/conan_packages/b/itk665eb0bcff404/p/lib/cmake/ITK-5.3/UseITK.cmake`.  This script belongs to the dependency and expects a variable called `ITK_CMAKE_DIR`:
```cmake
include(${ITK_CMAKE_DIR}/ITKInitializeCXXStandard.cmake)
```
In ITK's recipe's `package_info()` callback I define it:
```python
        itk_cmake_dir = os.path.join(self.package_folder, "lib", "cmake", self._itk_subdir )
        self.buildenv_info.define_path("ITK_CMAKE_DIR", itk_cmake_dir)
```
The path is correct, but it doesn't make through when I build ITK's test package:
```bash
CMake Error at C:/conan_packages/b/itk665eb0bcff404/p/lib/cmake/ITK-5.3/UseITK.cmake:25 (include):
  include could not find requested file:

    /ITKInitializeCXXStandard.cmake
```
Notice that `ITK_CMAKE_DIR` is blank, when it shouldn't as I set it in the recipe of the package under test.  How do I make that information be available to consumers?

thank you,

PC

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by PauloCarvalhoRJ** [comment]
Solved by doing in parent package's `package_info()`:
```python
        itk_cmake_dir = os.path.join(self.package_folder, "lib", "cmake", self._itk_subdir )
        self.cpp_info.set_property("itk_cmake_dir", itk_cmake_dir)
```
Then, by doing in test package's (consumer package) `generate()`:
```python
        tc = CMakeToolchain(self)

        # This info is needed by ITK's UseITK.cmake when dependant packages like this use ITK package during configuration with CMake.
        itk_cmake_dir = self.dependencies[self.tested_reference_str].cpp_info.get_property("itk_cmake_dir")
        tc.cache_variables["ITK_CMAKE_DIR"] = itk_cmake_dir.replace("\\", "/") # backslashes in Windows paths result in syntax errors in CMake

        tc.generate()
        tc = CMakeDeps(self)
        tc.generate()
```
On a side comment, ITK 5.3 is a kind of odd to configure and build.  I had to do some unorthodox procedures in addition to this one in the recipe in order to configure and build.

best,
PC

**Comment by memsharded** [comment]
Good that you found a solution @PauloCarvalhoRJ

In general, the ``self.cpp_info.builddirs`` attribute is designed for this purpose: to define the location of build scripts that can be used by consumers. In some cases these directories can be automatically injected in the consumers ``CMake`` paths, so it might be possible to ``include()`` them directly without having to add anything specially in the consumer. You can try that and create new tickets if you have any question about it.

**Comment by PauloCarvalhoRJ** [comment]
Hello, @memsharded ,

Thank you for that feedback. but in order to use that more elegant solution, I have to change the consumer's `CMakeLists.txt` to not use that variable (`ITK_CMAKE_DIR`), which it would be no big problem.  I'm working on another package right now, but I can return to ITK later and check this out.

best,

PC

**Comment by memsharded** [comment]
Yes, I was commenting on general recommendation, there might be specifics of ITK that doesn't fit it, and require some extra work. Some users add extra build modules to the packages, in this case it would be possible to create an extra cmake module for itk that is loaded when ``find_package(ITK)`` and that defines the ``ITK_CMAKE_DIR`` if this helps (but I have no idea).
