### ISSUE TITLE
[question] Conan 2: How to generate conaninfo.txt?

### ISSUE THREAD

**Issue by chrisc66** [conan-io/conan#16763]
### What is your question?

I am upgrading my project from Conan v1.64 to v2.6.0. The `conan install` command in v1 used to generate `conaninfo.txt`, which I use in later scripts to identify and track dependencies. After migrating to Conan 2, `conan install` doesn't generate this file anymore. Can someone please help with how to generate `conaninfo.txt` in the previous format?

This is the last few lines of the conan install command, I am only installing one tiny library in this run.
```
$ conan install /opt/conanrepo/dev -pr:a=/opt/conanrepo/dev/conan_profile --build=missing
...
======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to /opt/conanrepo/resources
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(zstd)
    target_link_libraries(... zstd::libzstd_shared)
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: CMakeToolchain generated: conan_toolchain.cmake
conanfile.txt: CMakeToolchain: Preset 'conan-release' added to CMakePresets.json.
    (cmake>=3.23) cmake --preset conan-release
    (cmake<3.23) cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
conanfile.txt: CMakeToolchain generated: /opt/conanrepo/resources/CMakePresets.json
conanfile.txt: Generating aggregated env files
conanfile.txt: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @chrisc66,

Thanks a lot for your question. The `conaninfo.txt` file is only generated in Conan 1.X to be used for the local development flow and is not needed for Conan 2 any more. If you need the information that used to be there, you can find that by doing a `conan install ... --format=json > info.json` and then you can parse that json.
If you tell us more details about your workflow and why you need to get information from `conaninfo.txt` we may give you some hints in case you can skip that step in Conan 2 using some new feature.

Hope this helps

**Comment by chrisc66** [comment]
Hi @czoido , thanks for your reply! I have been using Conan v1 for a few years, and realized many commands and APIs are changed after spending a good amount of time on v2 migration . Your suggestion `conan install ... --format=json > info.json` provides much more information.

I would like to keep track of all packages, versions and upgradable packages in my project. There are a few scripts that parse `conaninfo.txt` and `conanfile.txt`:
1. list currently installed packages and versions
2. list deprecated packages and upgradable packages
3. list transitive dependency packages (not included in my `conanfile.txt`)
4. find out executables installed as part of the package (e.g. `xxx/.conan/data/xxx/package/bin/curl` in v1 format)

Could you please point it out if Conan v2 already generates above info from CLI? Thanks a lot!

**Comment by memsharded** [comment]
> list currently installed packages and versions

The ``conan list`` command lists all installed packages, versions, revisions and package-id binaries


> list deprecated packages and upgradable packages

The ``json`` format of the different commands (install, create, graph info) will already contain the ``deprecated`` field of all direct and transitive dependencies

The ``conan graph outdated`` command will report packages that have newer versions in servers

> list transitive dependency packages (not included in my conanfile.txt)

The ``json`` format output contains this information

> find out executables installed as part of the package (e.g. xxx/.conan/data/xxx/package/bin/curl in v1 format)

The ``json`` format output contains ``bindirs`` folders for every dependency, you can find executables directly inside those ``bindirs``


You shouldn't need to parse ``conaninfo.txt`` at all in Conan2, the output is much richer and more complete than in Conan 1.

**Comment by chrisc66** [comment]
@memsharded Thanks for your info. I am now able to migrate all packages to Conan 2 and get enough information from CLI commands.

**Comment by memsharded** [comment]
Great, thanks for the feedback!
