### ISSUE TITLE
Create an un-moderated and Browsable Central Repository

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1676]
Before Bintray acquired Conan.io, it had a browsable and searchable central repository that included all community contributions.  While the old repository is still available, no new contributions can be made to this, and it's a significant loss to the momentum of collaborative community packages.   

It's not a new idea, nor my own.  The Redhat/Fedora communities have several community repos listed here :  https://wiki.centos.org/AdditionalResources/Repositories

While a good reference for the usefulness of such repositories, there are problems with the current state of affairs above.  I think Conan has the unique opportunity to provide a much more practical and centralized middle-ground repository which integrates with the "Linked Repository" feature in Bintray .

Conan-Center is obviously still an invaluable and critical development for Conan packages.  However, as the Conan team has taken a step back from supporting packages directly, there is an extremely awkward situation surrounding the low number of trusted packages currently available, and lack of a centralized community repository where people can get new packages.  

Among the specific challenges currently experienced by the community: 
- Using a community package from a new author effectively involves adding 1-remote-per-package
-- The proliferation of "community remotes" and the management thereof is a problem
- There will now be far more redundant package efforts because of blindness
-- People cannot easily see what other packages are in progress in the community

Another reason I suggest this feature is that it's "easy."  Bintray is setup to "link" packages to other central repositories, and has central repositories like conan-center for other package types.  Conan-center is the only "special" one for conan packages at the moment, but adding another is relatively simple for them. 

In truth, it's not "easy", as a proper implementation would require thought about letting users intelligently set controls on "signed vs unsigned", and deciding what is a reasonable way to notify users if they're pulling a package from the community repository. It would certainly require adding features like priority and such.  Again however, we can look to mature communities like the RHEL/Fedora system to see what protections they implemented as a reference.

**Comment by sourcedelica** [comment]
I'm in the process of getting an open source project ready to go into Conan Center and it's a lot more work than the old repo, mostly because of the requirement to support multiple platforms and architectures.  The Conan Package Tools are a godsend, but debugging problems via the CI logs is time consuming.

I like the idea of having a way of getting packages into a central repo that doesn't have strict requirements, but still has "official" owners of packages so users can distinguish them when searching.

**Comment by solvingj** [comment]
I forgot I opened this ticket, and I now feel such a repository would conflict and detract from the long-term growth of Conan-Center, and significantly increase the risk of malicious packages being downloaded.  If people can just add one repository and get back to the old behavior of conan.io, they will, and there's too much risk involved with that (IMO). 

On the other hand, I would still support this ticket with the major change, that users cannot actually download from the repo (strange i know).  Users would still have to manually add the remote for the package they want, but it's a much more conscious acceptance of risk by the user to do so.  The benefits being the ease of "publishing"/"Announcing" your packages to the community, and the visibility into the activity surrounding community packages from the general public.  Currently that activity is not visible anywhere, and still won't be even once conan-center is going strong.

**Comment by solvingj** [comment]
Searching from Bintray's main search box allows users to search ALL public repositories on bintray.  This includes conan repositories, and every other kind of repository.  This satisfies my request.
