### ISSUE TITLE
[bug] cpp_info.objects are not linked to consumers if package was cross-built

### ISSUE THREAD

**Issue by AmateurECE** [conan-io/conan#16771]
### Describe the bug

Environment details:
Conan 2.6.0 and also 2.4.1
Gentoo Linux

Description:
I have a library built as a Conan package that's targeting a baremetal ARM environment. It exports a few object files that provide required symbols for consumers to link against. My package is `stm32mp1/1.6.0`, and my profile is called `armv7e-m-gnu`.

The package builds fine, but I get link errors building the test package because the object files are not linked to my consuming target. If I built the package using `conan create -pr:a armv7e-m-gnu -tf "" .`, that is, I'm using my bare-metal profile for both build and host profiles, the test succeeds whether the test itself is cross-built or not. Obviously, this is a workaround, because my build and host profiles are not the same in reality.

It looks like the CMakeDeps generator is just not populating them in the target information, because if I compare `stm32mp1-release-armv7e-m-gnu-data.cmake` between the working and not working test packages, I see this:
```diff
--- failing.cmake	2024-08-02 11:30:13.026550207 -0500
+++ passing.cmake	2024-08-02 11:31:48.553056904 -0500
@@ -12,7 +12,7 @@
 
 ########### VARIABLES #######################################################################
 #############################################################################################
-set(stm32mp1_PACKAGE_FOLDER_RELEASE "/home/edtwardy/Git/metalwork/.conan/p/b/stm324c204eaa825cb/p")
+set(stm32mp1_PACKAGE_FOLDER_RELEASE "/home/edtwardy/Git/metalwork/.conan/p/b/stm32ffc18eb3f06dd/p")
 set(stm32mp1_BUILD_MODULES_PATHS_RELEASE )
 
 
@@ -23,7 +23,10 @@
 set(stm32mp1_DEFINITIONS_RELEASE )
 set(stm32mp1_SHARED_LINK_FLAGS_RELEASE )
 set(stm32mp1_EXE_LINK_FLAGS_RELEASE "-T;STM32MP157CAAX_RAM.ld")
-set(stm32mp1_OBJECTS_RELEASE )
+set(stm32mp1_OBJECTS_RELEASE "${stm32mp1_PACKAGE_FOLDER_RELEASE}/lib/startup_stm32mp157cxx_cm4.s.o"
+			"${stm32mp1_PACKAGE_FOLDER_RELEASE}/lib/system_stm32mp1xx.c.o"
+			"${stm32mp1_PACKAGE_FOLDER_RELEASE}/lib/sysmem.c.o"
+			"${stm32mp1_PACKAGE_FOLDER_RELEASE}/lib/syscalls.c.o")
 set(stm32mp1_COMPILE_DEFINITIONS_RELEASE )
 set(stm32mp1_COMPILE_OPTIONS_C_RELEASE -include;stdint.h;-DUSE_HAL_DRIVER;-DSTM32MP157Dxx;-DCORE_CM4)
 set(stm32mp1_COMPILE_OPTIONS_CXX_RELEASE -include;cstdint;-DUSE_HAL_DRIVER;-DSTM32MP157Dxx;-DCORE_CM4)
@@ -59,7 +62,10 @@
 set(stm32mp1_stm32mp1_c_polyfill_IS_HOST_WINDOWS_RELEASE 0)
 set(stm32mp1_stm32mp1_c_polyfill_RES_DIRS_RELEASE )
 set(stm32mp1_stm32mp1_c_polyfill_DEFINITIONS_RELEASE )
-set(stm32mp1_stm32mp1_c_polyfill_OBJECTS_RELEASE )
+set(stm32mp1_stm32mp1_c_polyfill_OBJECTS_RELEASE "${stm32mp1_PACKAGE_FOLDER_RELEASE}/lib/startup_stm32mp157cxx_cm4.s.o"
+			"${stm32mp1_PACKAGE_FOLDER_RELEASE}/lib/system_stm32mp1xx.c.o"
+			"${stm32mp1_PACKAGE_FOLDER_RELEASE}/lib/sysmem.c.o"
+			"${stm32mp1_PACKAGE_FOLDER_RELEASE}/lib/syscalls.c.o")
 set(stm32mp1_stm32mp1_c_polyfill_COMPILE_DEFINITIONS_RELEASE )
 set(stm32mp1_stm32mp1_c_polyfill_COMPILE_OPTIONS_C_RELEASE "")
 set(stm32mp1_stm32mp1_c_polyfill_COMPILE_OPTIONS_CXX_RELEASE "")
```

I poked around in the cmakedeps generator code for a little while, but nothing stuck out to me as causing this kind of thing. I also tried other workarounds, like populating the object files in the `exelinkflags` and `libs` properties of the packages `cpp_info`, but that didn't get me anywhere.

### How to reproduce it

Cross-build a package that exports object files in its `cpp_info`, and then attempt to consume the package in a test package. Observe that the object files are not linked. Create the package using the same profile for host and build, and observe that the object files are linked correctly.

**Comment by czoido** [comment]
Hi @AmateurECE,

Thanks a lot for reporting. I have been trying to reproduce the issue with no luck. I made [this simple reproducible example](https://github.com/czoido/conan-cppinfo-objects) that creates some object files and adds them to the `cpp_info` but apparently the test_package is linking correctly. Could you please check to see if that more or less mimics your current situation? 
I can build the package and test_package for both cases with no problems:

```
conan create . -pr:a=default
conan create . -pr:h=./raspberry -pr:b=default
```

**Comment by AmateurECE** [comment]
At first glance, that example appears to more or less mimic my current state, yes! I'll play with it more tonight and get back to you with anything I observe. Thanks for putting this example together!

**Comment by AmateurECE** [comment]
By incrementally applying changes to make it more like my package, I was able to determine that this is an issue with my CMake configuration and conanfile.py, not a bug in Conan.

When the same profile is used for host and build, Conan does *not* explicitly set `CMAKE_SYSTEM_NAME` in the generated toolchain file. In this case, CMake refers to the host system (in my case, Linux) to determine to determine the extension for object files ([see CMakeCInformation.cmake](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.28.5/Modules/CMakeCInformation.cmake#L13)). My conanfile.py contains this:

```python
def package_info(self):
    # ...
        self.cpp_info.components['c_polyfill'].objects = glob.glob(self.package_folder + '/lib/*.o')
```

So, when using a separate profile for cross-compilation, the generated toolchain file contains `set(CMAKE_SYSTEM_NAME "Generic")`, and perhaps surprisingly, the generated object files are created with the extension .obj, instead of .o. Changing the extension in the package_info method allowed the test package to compile correctly.

Thanks very much for your help in debugging this issue!

**Comment by czoido** [comment]
> 
> Thanks very much for your help in debugging this issue!

I'm really happy that it worked! Thank you!
