### ISSUE TITLE
[bug] Infinite loop when trying to upload package to remote with CONAN_LOGIN_USERNAME and CONAN_PASSWORD

### ISSUE THREAD

**Issue by uvollhardt** [conan-io/conan#16770]
### Describe the bug

When trying to upload a package to a remote with the following command : 

`CONAN_LOGIN_USERNAME="<user>" CONAN_PASSWORD="<token>" conan upload "<pkg>" -r <remote>`

I got an infinite loop of conan asking to excute "conan remote login" and telling my it found the username and password from environment : 

```
Found 1 pkg/version recipes matching <pkg> in local cache

======== Uploading to remote <remote> ========

-------- Checking server existing packages --------
<pkg>/v1.0.0: Checking which revisions exist in the remote server
Please log in to "<remote>" to perform this action. Execute "conan remote login" command.
Got username '<user>' from environment
Got password '******' from environment

-------- Preparing artifacts for upload --------

-------- Uploading artifacts --------
<pkg>/v1.0.0: Uploading recipe '<pkg>/v1.0.0#63fefc2d65e3a5864fef6dba05a4c24a' (14.8KB)
Please log in to "<remote>" to perform this action. Execute "conan remote login" command.
Got username '<user>' from environment
Got password '******' from environment
Please log in to "<remote>" to perform this action. Execute "conan remote login" command.
Got username '<user>' from environment
Got password '******' from environment
Please log in to "<remote>" to perform this action. Execute "conan remote login" command.
Got username '<user>' from environment
Got password '******' from environment
Please log in to "<remote>" to perform this action. Execute "conan remote login" command.
Got username '<user>' from environment
Got password '******' from environment
Please log in to "<remote>" to perform this action. Execute "conan remote login" command.
Got username '<user>' from environment
Got password '******' from environment
.....
```

If a input the credential myself without the environment variable it works perfectly. However, I want to automate the deployment of a package in a CI/CD pipeline, so I can't obviously input the credentials by hand each time it's asked.

### How to reproduce it

- Create any package localy
- Log to the remote with the command `conan remote login -p <password> <remote> <user>` 
- Try to upload it using CONAN_LOGIN_USERNAME and CONAN_PASSWORD environment variables.

=> Infinite loop of conan asking to use "Please log in to "\<remote\>" to perform this action"

**Comment by czoido** [comment]
Hi @uvollhardt,

Thanks a lot for reporting. I have been trying to reproduce this with no luck, I can set the credentials with those variables and not enter the infinite loop as you can see in the log:

```
$ CONAN_LOGIN_USERNAME="admin" CONAN_PASSWORD="password" conan upload "mypkg" -r myrepo
Found 1 pkg/version recipes matching mypkg in local cache

======== Uploading to remote myrepo ========

-------- Checking server existing packages --------
mypkg/1.0: Checking which revisions exist in the remote server
Please log in to "myrepo" to perform this action. Execute "conan remote login" command.
Got username 'admin' from environment
Got password '******' from environment

-------- Preparing artifacts for upload --------
mypkg/1.0: Compressing conan_sources.tgz
mypkg/1.0:015c501fa3ba2da21e4c2e71becb7b76fa605a36: Compressing conan_package.tgz

-------- Uploading artifacts --------
mypkg/1.0: Uploading recipe 'mypkg/1.0#3884c19173cedc31447ff5ca2fc7edc6' (3.1KB)
mypkg/1.0: Uploading package 'mypkg/1.0#3884c19173cedc31447ff5ca2fc7edc6:015c501fa3ba2da21e4c2e71becb7b76fa605a36#59131e5fa50779c5335dd8958a60bf6f' (3.0KB)
Upload completed in 0s
```

Could you please provide more details about the environment? Which Conan version are you using? In which platform?
Is it possible for you to try in another environment and check if that still happens? Maybe from a clean docker container?

Thanks a lot.

**Comment by YassineLambarki** [comment]
I think there is two questions right there.
1- Why doesn't the upload work ?
2- Why doesn't the command fail immediately and why does it go into an infinite loop ?

1- Are your credentials are right ? Did the login succeed ?
2- Normally, if the login fails, this error shows up : 
```
Got username '<user>' from environment
Got password '******' from environment
ERROR: b'{\n  "errors" : [ {\n    "status" : 403,\n    "message" : "This request is blocked due to recurrent login failures, please try again in 5 seconds"\n  } ]\n}'
```

**Comment by yasslbk** [comment]
It seems like there are two main questions here:

Why isn’t the upload working?
Why doesn’t the command fail immediately and instead goes into an infinite loop?
To address these:

Are your credentials correct? Did the login succeed?
Typically, if the login fails, you would see this error:
```
Got username '<user>' from environment
Got password '******' from environment
ERROR: b'{\n  "errors" : [ {\n    "status" : 403,\n    "message" : "This request is blocked due to recurrent login failures, please try again in 5 seconds"\n  } ]\n}'
```

**Comment by uvollhardt** [comment]
Hi @czoido 

I'm using conan version 2.6.0 on a ubuntu 22.04 and trying to upload to a `gitea Conan Package Registry`.

I tried it with a docker container as you suggested and the results are the same with the same remote. In addition i tried with a wrong password to check the behavior and here is the result: 

```
CONAN_LOGIN_USERNAME="user" CONAN_PASSWORD="password" conan upload
 "mypkg" -r remote
Found 1 pkg/version recipes matching mypkg in local cache

======== Uploading to remote remote ========

-------- Checking server existing packages --------
mypkg/v1.0.0: Checking which revisions exist in the remote server
Please log in to "remote" to perform this action. Execute "conan remote login" command.
Got username 'user' from environment
Got password '******' from environment
ERROR: Wrong password for user "user"
Got username 'user' from environment
Got password '******' from environment
ERROR: Wrong password for user "user"
Got username 'user' from environment
Got password '******' from environment
ERROR: Wrong password for user "user"
ERROR: Too many failed login attempts, bye!. [Remote: remote]
```
It seems to be the correct behavior, although it tried 3 times before exiting (I don't know if it's the expected behavior or not).

Finally I also tried to change the remote by using the `Artifactory Community Edition` instead of the `gitea Conan Package Registry` and it seems to by working as expected (both with a right password and a wrong one). 

Wrong password : 
```
CONAN_LOGIN_USERNAME="test" CONAN_PASSWORD="Test000" conan upload "mypkg" -r artifactory
Found 1 pkg/version recipes matching mypkg in local cache

======== Uploading to remote artifactory ========

-------- Checking server existing packages --------
mypkg/v1.0.0: Checking which revisions exist in the remote server
Please log in to "artifactory" to perform this action. Execute "conan remote login" command.
Got username 'test' from environment
Got password '******' from environment
ERROR: Wrong user or password
Got username 'test' from environment
Got password '******' from environment
ERROR: {
  "errors" : [ {
    "status" : 403,
    "message" : "This request is blocked due to recurrent login failures, please try again in 1 seconds"
  } ]
}. [Remote: artifactory]
```

Right password:
```
 CONAN_LOGIN_USERNAME="test" CONAN_PASSWORD="Test0000" conan upload "mypkg" -r artifactory
Found 1 pkg/version recipes matching mypkg in local cache

======== Uploading to remote artifactory ========

-------- Checking server existing packages --------
mypkg/v1.0.0: Checking which revisions exist in the remote server
Please log in to "artifactory" to perform this action. Execute "conan remote login" command.
Got username 'test' from environment
Got password '******' from environment

-------- Preparing artifacts for upload --------
[...]
```

So it seems that the `gitea Conan Package Registry` is the issue here, but I don't understand why the behavior is different between giving the credentials using CONAN_LOGIN_USERNAME and CONAN_PASSWORD and giving the credentials when asked in the terminal. Both should behave in the same way with the remote, should'nt they ?

**Comment by memsharded** [comment]
Thanks for the feedback.

I have checked the code, and this is something that might happen if the server side rejects the JWT it just created in the previous ``authenticate`` call, that "succeeds" but then rejects its own token with a new ``AuthenticationException``.

I'd suggest reporting this to the gitea project, seems and issue there, not in the Conan client (thought we could try to improve it to avoid the infinite loop, throwing a hard error, but avoiding it will still be an issue in your case because you will still not be able to communicate with the server propertly.

**Comment by sparrowyang** [comment]
I have the same problems, Conan version 2.5.0 + nexus 3.71.0-06
```
PS D:\wp\conan_create_package>  conan upload hello/1.0 -r=lucas

======== Uploading to remote lucas ========

-------- Checking server existing packages --------
hello/1.0: Checking which revisions exist in the remote server

-------- Preparing artifacts for upload --------

-------- Uploading artifacts --------
Please log in to "lucas" to perform this action. Execute "conan remote login" command.
Remote 'lucas' username: admin
Please enter a password for "admin" account: 
Please log in to "lucas" to perform this action. Execute "conan remote login" command.
Remote 'lucas' username: admin
Please enter a password for "admin" account: 
Please log in to "lucas" to perform this action. Execute "conan remote login" command.
Remote 'lucas' username:
```

**Comment by memsharded** [comment]
Hi @sparrowyang 

It seems it would be the same reason, I suggest reporting it to nexus project.

Any further question here? It seems there is little more we can do from our side, so I'd suggest closing this as not a bug in Conan.

**Comment by aviv000** [comment]
I have encountered something similar to this. The Conan client has a local SQLite DB with your credentials at $CONAN_HOME.
I would check if the encoded password in there is correct, for some reason it was empty for me after the conan upload credentials prompt.
Worst case scenario you could insert your credentials to that DB using SQL, use this as last resort.

**Comment by hahaSK** [comment]
> I have the same problems, Conan version 2.5.0 + nexus 3.71.0-06
> 
> ```
> PS D:\wp\conan_create_package>  conan upload hello/1.0 -r=lucas
> 
> ======== Uploading to remote lucas ========
> 
> -------- Checking server existing packages --------
> hello/1.0: Checking which revisions exist in the remote server
> 
> -------- Preparing artifacts for upload --------
> 
> -------- Uploading artifacts --------
> Please log in to "lucas" to perform this action. Execute "conan remote login" command.
> Remote 'lucas' username: admin
> Please enter a password for "admin" account: 
> Please log in to "lucas" to perform this action. Execute "conan remote login" command.
> Remote 'lucas' username: admin
> Please enter a password for "admin" account: 
> Please log in to "lucas" to perform this action. Execute "conan remote login" command.
> Remote 'lucas' username:
> ```

Encountering the same problem.

**Comment by hahaSK** [comment]
Found solution for Nexus. In Nexus the Conan bearer token must be enabled. See section [Requirements and Limitations](https://help.sonatype.com/en/conan-repositories.html) -> [https://help.sonatype.com/en/realms.html](https://help.sonatype.com/en/realms.html)

**Comment by memsharded** [comment]
Thanks for the feedback.
I am closing this ticket as this is not related to Conan but to the respective servers nexus/gitea, tickets should be reported to those projects if the issue persist.
