### ISSUE TITLE
[question] How to get the version of a package in the test package?

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16773]
### What is your question?

Hi,

I have the following code in the test package's recipe:
```python
    v = Version(self.dependencies[self.tested_reference_str].version)
```
But it gives this error:
```bash
AttributeError: 'ConanFileInterface' object has no attribute 'version'
```
The question is: how do I get the version of the package under test in the test package recipe?

thank you,

PC

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @PauloCarvalhoRJ,

Thanks for the question. The syntax there is not correct, please try with:

```python
v = Version(self.dependencies[self.tested_reference_str].ref.version)
```

Hope this helps.

**Comment by PauloCarvalhoRJ** [comment]
Hello,

Thank you.  There is that little `ref` in the middle that I would never have figured out.

best,

PC
