### ISSUE TITLE
[question] Issue with 'automatic' compatible packages and custom package ids

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16785]
Hi,

could anyone please review this? https://github.com/conan-io/conan/pull/16772

"
In case the recipe uses its own package_id() and compatible packages are generated automatically (e.g. Visual Studio vs msvc), then the compatible packages will use wrong 'base' info set for the compatible package id generation.

In case the recipe's own package_id() erases a few options / settings, the compatible packages will not know about it, as those are generated prior the recipe's package_id() is being called.

The change makes sure that first the recipe's package_id() is called, then the compatible packages are generated, so that they pick up the updated info set.
"

If possible this would also have to be added to the 1.65 release, as it affects the msvc compatibility, e.g. it relates to: https://github.com/conan-io/conan/pull/16732
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @harsszegi thanks for your PR, we appreciate it

> could anyone please review this? https://github.com/conan-io/conan/pull/16772

Please understand that in this time of the year PR review times might (will) increase as the team gets its deserved summer vacations going, so having more patience than usual in that regard will be necessary, thanks! :)

**Comment by harsszegi** [comment]
Understood, thanks a lot!
