### ISSUE TITLE
[question] Is it possible to use the Sources Backup feature in Conan 1.64?

### ISSUE THREAD

**Issue by markspacehub** [conan-io/conan#16788]
### What is your question?

Hello,
My company are using Nexus as our repository manager for various things, including Conan. Unfortunately, Nexus does not support Conan 2 (yet).
Our Nexus server contains a mirror of conan-center for getting public packages, however our CI environment does not allow access to any non-whitelisted URLs which includes Github. As such, despite mirroring conan-center, any package without binaries built in the matching configuration cannot build in the CI environment, because --build=missing tries to get the package sources for Github (the few we are testing with are all on Github: gtest glog etc).

In Conan 2, there is a [sources backup](https://docs.conan.io/2/devops/backup_sources/sources_backup.html) feature, that while not specifically designed for this use case, may allow us to backup the sources on our git server and then use for our conan-center mirror. Is this available for for Conan 1.64? If not, is there anything else we are able to do? 

I guess I am not expecting this feature to be available, but I am wondering if there is a different solution that solves my problem

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @markspacehub, thanks a lot for your question.

Unfortunately the source backups are only available in Conan 2, it's one of the features that the new improved codebase made possible with respect to Conan 1. When adding the feature in Conan 2 we thought about backporting it to Conan 1, but the added complexity made it almost unfeasible, efforts that we decided would be better spent elsewhere.

As for possible workarounds, other than waiting/asking Nexus, there's sadly not a transparent way to implement this in Conan 1. Is your only hold-up to migrate to Conan 2 the fact that Nexus does not support it?

**Comment by markspacehub** [comment]
Yes, our only hold-up is Nexus' support (or lack of). It looked like my team would be setting our own dev-ops up and I implemented our test set of projects with Conan 2, only to be brought into the existing setup and required to revert!

Oh well, I guess we'll have to poke Nexus and wait

Thanks @AbrilRBS
