### ISSUE TITLE
Copy conan package which gets created by conan create to any local folder of my choice

### ISSUE THREAD

**Issue by nefree18ster** [conan-io/conan#16790]
### What is your question?

Hi Team 
I have a scenario where I create conan package by conan create command on docker image. I want to copy this created conan package to a local folder of my choice.
How can I achieve this?

I am aware of conan upload but this will upload the conan package created to remote location and not local folder. also is there a way to upload conan package to local location? is there a way?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @nefree18ster thanks for your question. In Conan 2, you have some choices here:

The main one would be to use the `conan cache save`/`conan cache restore` commands, check [this guide](https://docs.conan.io/2/devops/save_restore.html) for more information regarding said workflow, which shows how to save your created packages and restore them elsewhere. You can additionally use this with https://docs.conan.io/2/examples/commands/pkglists.html and pass the generated pkglist with only the built binaries to the `conan cache save` command

Moreover, we now have an experimental feature that allows to directly run Conan from within a docker container, check the [`runner` docs here](https://docs.conan.io/2/examples/runners/docker/basic.html) for more information - additionally a blogpost is also coming soon-ish which will go into a bit of detail into the usecase, so stay tuned for that! :)

**Comment by nefree18ster** [comment]
Hi Team, by any way can I achieve copy of conan package to local directory of my choice in conan 1 ?

**Comment by AbrilRBS** [comment]
There's not a built-in way to do the same in Conan 1, it's one of the things the new architecture in Conan 2 allowed us to add without all the complexity that it would neeed in Conan 1, but in Conan 1 you might be able to get away by copying the package folder directly by yourself, but your millage may vary

**Comment by nefree18ster** [comment]
Okay I tried copy required created package from one image to another but the package from new image remains unidentified. Can you please guide on steps to do this successfully? 
My scenario is I want to upload this package to jfrog from new image (new release job in git)

**Comment by memsharded** [comment]
Hi @nefree18ster 

Sorry, it is not fully clear what is your issue. How did you copy the package in Conan 1? Or did you move to Conan 2?
Also it is not clear if you want to move the package from a Conan cache to another Conan cache (this can be done with ``conan cache save/restore``) or if you want to copy the artifacts/files from a Conan package to your final user folder, to use them outside of Conan (this can be done with Conan 2 ``deployers`` too)

> My scenario is I want to upload this package to jfrog from new image (new release job in git)

This scenario, typically involving different jobs in CI is solved with ``conan cache save/restore`` followed by ``conan upload``, nothing more is needed.

**Comment by nefree18ster** [comment]
Sorry for the confusion. I did not move to conan 2. 
**I want solution in conan 1** . Currently I did normal copy-Item command in powershell to copy the required folder from conan folder of one image to another image. 
I want to run conan upload from 2nd image so that I can upload the package to artifactory.

I need steps for conan1 to :
1) manually copy conan cache with selective package only from one image to another (I need to know what all I can copy; given that the cache has lot many package and I want to upload only one package of my choice)
2) I need to upload via conan upload command from 2nd image to artifactory. 

Regards

**Comment by memsharded** [comment]
I am afraid there is not supported, built-in solution for this flow in Conan 1.

You might try to copy the ``<path/to/cache>/.conan/data/pkgname/pkgversion/pkguser/pkgchannel`` from one cache to the other (note the user and channel might be ``_`` for packages without user and channel), but not sure if this will work at all, and it is not a supported approach, you might try it at your own risk.

**Comment by AbrilRBS** [comment]
Closing for now, feel free to reopen should you have any other questions/approach, thanks!
