### ISSUE TITLE
[bug] self.conf.get cannot see some variables

### ISSUE THREAD

**Issue by mtribiere** [conan-io/conan#16797]
### Describe the bug

OS: Windows
Conan: 2.5.0

I have an ``application`` package that contains a binary and a Python launcher. So to provide the launcher path to the consuming package I use:

```python
class MyToolRecipe(ConanFile):
[...]
  def package_info(self):
          self.conf_info.define("tools.my_tool:launcher_path", os.path.join(self.package_folder,"tool_launcher/launcher.py"))

```

And strangely, in my consuming package, ``conf.get`` cannot see the variable ``tools.my_tool:launcher_path``, but ``conf._values["tools.my_tool:launcher_path"]`` does see it.

```python
class MyConsumer(ConanFile):
[...]
  def build(self):
      print(self.conf._values["tools.my_tool:launcher_path"])    # <- Works 
      print(self.conf.get("tools.my_tool:launcher_pat"))         # <- Crash

```

Is this a bug or am I not using this correctly? Is there a better way to provide the launcher path to the consuming package?

**Comment by franramirez688** [comment]
Hi @mtribiere 

A couple of suggestions:

* You should use the namespace `user` instead of `tools` because `tools` is kind of protected. I mean:

```python
  def package_info(self):
          self.conf_info.define("user.my_tool:launcher_path", os.path.join(self.package_folder,"tool_launcher/launcher.py"))
```

* Are you requiring that application as a `build_require`? 

```python
class MyConsumer(ConanFile):

  def build_requirements(self):
      self.tool_requires("my_app/1.0")
```
Both changes should fix the problem.

**Comment by mtribiere** [comment]
Hi @franramirez688 

Thanks for the speedy response, your suggestion to change the namespace to ``user`` did solved the issue!

Just two question for my understanding:

- If I understand, no tool should write in the ``tool.*`` config is that correct? And if so, should all packages that need to provide informations to a consumer need to use the ``user.*`` config exclusively?

- I'm using this path to run a Python launcher with ```self.run(f"python {self.conf.get("user.my_tool:launcher_path")}")```. 
 Is that the proper way to do it, or is there a more "conan way" to do so?

**Comment by franramirez688** [comment]
Hi @mtribiere 

> * If I understand, no tool should write in the `tool.*` config is that correct? And if so, should all packages that need to provide informations to a consumer need to use the `user.*` config exclusively?

To understand better all these namespaces, I recommend reading the [global.conf section](https://docs.conan.io/2/reference/config_files/global_conf.html). There, you'll find all the answers to your questions.

> * I'm using this path to run a Python launcher with `self.run(f"python {self.conf.get("user.my_tool:launcher_path")}")`.
>   Is that the proper way to do it, or is there a more "conan way" to do so?

I think it's fine to use a user configuration, also you could add the PATH or even the PYTHONPATH directly. Something like:

```python
        self.buildenv_info.prepend_path("PATH", launcher_path)
```
Then, you could use it directly in your recipe like:

```python
self.run("python launcher_binary")
```
You have a better example in the [`android-ndk` recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/conanfile.py#L255) to check how it's done there.

**Comment by mtribiere** [comment]
Hi @franramirez688 

Thank you for pointing out those resources, it does answers my questions.

I will close the issue now.
