### ISSUE TITLE
[Conan cache save dependencies] Does saving package from cache also save its dependencies

### ISSUE THREAD

**Issue by MouhK** [conan-io/conan#16792]
### What is your question?

Hi I have a question regarding conan cache save.
Let's say I have on my cache a package A which requires package B.
If I do `conan cache save "A/"*:*"` will it also put "B/"*.*"` inside ?

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @MouhK thanks a lot for your question.

> If I do conan cache save "A/"*:*" will it also put "B/"."` inside ?

No, the `conan cache save` command won't save dependencies, it will only save those packages that match the given pattern.

What you can do is to use [the pkglist feature](https://docs.conan.io/2/examples/commands/pkglists.html):
- Run `conan graph info --requires=a/... --format=json > graph.json` for the versions you're interested in.
- The generated json can then be passed to `conan list` as shown in the link above, `conan list --graph=graph.json --format=json > pkglist.json` (Check [the `conan list` docs](https://docs.conan.io/2/reference/commands/list.html#listing-graph-artifacts) for more information on using pkglists in the command)
- Repeat the steps above for each of your needed references, saving to different pkglists files
- Then run [`conan pkglist merge`](https://docs.conan.io/2/reference/commands/pkglist.html#conan-pkglist-merge) to merge all those pkglists
- Finally, run `conan cache save --list=finalpkglist.json` ([Docs here](https://docs.conan.io/2/reference/commands/cache.html#conan-cache-save)) to get all your packages in the zipped file

Hope this helps, feel free to ask any follow-up questions, happy to help where possible :)

**Comment by MouhK** [comment]
Hello @AbrilRBS. Amazing that's exactly what I need.

Thank you for your responsiveness and detailed explanations.
