### ISSUE TITLE
Where/how to declare custom variables? (not change the hash & displayed in Artifactory)

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#1679]
- If a custom variable is needed (not an environmental variable for PATH), is `user_info` the only place to do it that does not change the hash like settings/options do?

- `cpp_info` does not allow custom variables, right?

- Why is a declared custom `user_info` variable and value not displayed in Artifactory Properties like `conan.package`, `conan.options` and ``recipe_hash`?

#### The problem I need to solve is to declare a custom variable that does not change the hash and that are displayed in Artifactory Properties.

**Comment by memsharded** [comment]
-  Yes, custom variables have to be defined in ``user_info``
- ``cpp_info`` doesn't allow custom variables
- ``user_info`` so far is only to declare information for consumer packages, something like ``cpp_info`` but for general purpose. ``cpp_info`` is not displayed in Artifactory either. May I ask about the specific use case? What does this variable represent? Why do you need to display it in Artifactory web UI?

I think the only workaround to achieve what you want is to add some ``option`` to the package, then remove it in the ``package_id()`` method:

```python
class MyPkg(ConanFile):
      options = {"my_option": [True, False]}  # Or ANY
      default_options = "my_option=True"

      def package_id(self):
            self.info.options.my_option= "ANY" # discard specific value
```

**Comment by Twoflower2** [comment]
> May I ask about the specific use case? 

Our packages have a OS specific version number embedded/linked into the binaries itself. It quite common to reference this version number on this system. It will be good if this OS specific version number is stored as a property of a binary.

> What does this variable represent? 

OS specific version number.

> Why do you need to display it in Artifactory web UI?

Library consumer might want to search using the AF UI to first see if a binary of this OS specific version number exists + nice to have ;-)

**Comment by mpdelbuono** [comment]
I do like this idea, but I think it would be nice if I could declare which ones show up in Artifactory and which ones do not. I have a few user_info variables that are probably useless for searching/display, but are important for the dependent builds to understand. I guess there's nothing really wrong with them showing up in Artifactory, but it could clutter it up a bit.

**Comment by Twoflower2** [comment]
Also, a simple field, but self explaining field for any artefacts not in Artifactory and that is `description` 😉

**Comment by Twoflower2** [comment]
@memsharded would this enhancement be considered?

**Comment by memsharded** [comment]
Closing this as outdated and not planned.

The recommendation will be to use a Conan extension command for Artifactory (https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art) to set and get properties associated to packages
