### ISSUE TITLE
Access conan profile variable from 'buildenv' section in custom deployer

### ISSUE THREAD

**Issue by vithalsm** [conan-io/conan#16793]
### What is your question?

Hello,

I am implementing a custom deployer - abc_deployer.py.   
Conan profile has certain buildenv vars like STRIP.  
Need to access this variable i.e. STRIP from within abc_deployer.py.  Please let me know how to achieve same.

I tried following:
for dep in graph.root.conanfile.dependencies.values():
     print(dep.info.buildenv)    >>> NOT AVAILABLE,  only dep.info.settings is available here.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by vithalsm** [comment]
This helped
graph.root.conanfile.buildenv.vars(conanfile).get("STRIP")

Unless there is any other preferred way.

**Comment by memsharded** [comment]
Hi @vithalsm 

You can directly access for dependencies the ``dep.buildenv_info`` object directly, it is listed in https://docs.conan.io/2/reference/conanfile/methods/generate.html#dependencies-interface

But it might depend what you want to do with that env-var, what is the final usage in the deployed folder? Deployments are typically done for copying files, env-vars are not related or managed with generators instead, so it would be useful to know about the final usage.

**Comment by vithalsm** [comment]
Thanks @memsharded for the pointers.
Yes, custom deployer is to copy certain files like .so.  
In addition, as original .so are built with 'debug info', need to strip off the debug info.
Hence need to access STRIP buildenv variable from the profile which is set with respective path for 'strip' binary (diff for diff profiles).
If you can elaborate and help me to how to use dep.buildenv_info to get value of 'STRIP' variable, would be handy n quick.

**Comment by memsharded** [comment]
The ``buildenv_info`` is an ``Environment`` object, see https://docs.conan.io/2/reference/tools/env/environment.html#conan-tools-env-environment-model, so you can call the ``.vars()`` (https://docs.conan.io/2/reference/tools/env/environment.html#obtaining-environment-variables) to obtain an ``EnvVars`` object (https://docs.conan.io/2/reference/tools/env/envvars.html) which has several methods as ``.get()``.

Please try that and let us know.

**Comment by vithalsm** [comment]
Hi @memsharded as I had mentioned in my previous post itself, this is what exactly I had done and it had helped.

graph.root.conanfile.buildenv.vars(conanfile).get("STRIP")

So, if this is the preferred way, then we can close this issue.
Thanks for the help.

**Comment by memsharded** [comment]
Great, happy to help, thanks for the feedback!
