### ISSUE TITLE
self.conf.get used in set_version method

### ISSUE THREAD

**Issue by Ed-CMI** [conan-io/conan#16805]
### What is your question?

Hi

The following code was implemented  in the set_version method using conan version 2.2.2. When running conan export or conan create on the conan recipe file the error listed in the attachment is generated. Are self.conf variables, setting and options not available when the set_version method runs?

def set_version(self):
        self.version = self.conf.get("user.mcal:recipe_version",default=["NOTDEFINED"])

[set_version_error.docx](https://github.com/user-attachments/files/16550587/set_version_error.docx)

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Ed-CMI 

``conf`` is profile defined information, while ``set_version()`` is a mechanism to extract the version information from outside of Conan, not from Conan itself, like reading a user file containing the version information.

The way to define an initial version to the ``set_version()`` method is through the ``--version=xxx`` argument.

**Comment by Ed-CMI** [comment]
Thanks. Will close the ticket
