### ISSUE TITLE
[question] I am experminting with the patch feature and I want ask what is the standard way to do an extention that analyze the dependencies graph for the sake of validations on the binaries outside the standard analyze binaries method 

### ISSUE THREAD

**Issue by M0rtalPhe0nix** [conan-io/conan#16806]
### What is your question?

what is the standard way to analyze the dependencies graph for the sake of validations on the binaries outside the standard analyze binaries method

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @M0rtalPhe0nix 


Not really sure what you mean.

The ``conan install`` command (and other commands) have the ``conan install ... --format=json > graph.json`` that will create a serialized json representation of the dependency graph, is this what you are looking for?

**Comment by memsharded** [comment]
Any further question here? This would need some clarifications.

**Comment by memsharded** [comment]
I am closing this ticket as staled, but please don't hesitate to re-open or create new tickets for any further question. Thanks for your feedback.
