### ISSUE TITLE
[question] How to validate Options of a Dependency Package in conan v1

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#16814]
Hi,

In conan v1.52, how can a consumer package validate/check the options of a dependency package?

Below are my conan recipies:

Dependency Package:  
conan get DepPkg/v1@demo/test
```
from conans import ConanFile

class DepConanFile(ConanFile):
    name = "DepPkg"
    version = "v1"
    options = {
            "DEP_SECURE": [True, False],
            "DEP_MODE": ["A","B"]
            }
    default_options = "DEP_SECURE=True", "DEP_MODE=A"
```

Consumer Package:  
conan get ConsumerPkg/v1@demo/test
```
from conans import ConanFile
from conans.errors import ConanException


class ConsumerConanFile(ConanFile):
    name = "ConsumerPkg"
    version = "v1"
    options = {
            "SECURE": [True, False],
            "MODE": ["A","B"]
            }
    default_options = "SECURE=True", "MODE=A"


    def requirements(self):
        self.requires('DepPkg/v1@demo/test')

    def configure(self):
        if self.options.MODE != self.options['DepPkg'].DEP_MODE:
            raise ConanException("Values for MODE are different in Consumer(%s) and Dependency(%s)" % (self.options.MODE, self.options['DepPkg'].DEP_MODE))
```

When I am trying to build the consumer package, it doesn't seem to find all the available options in the dependency package:

```
ERROR: ConsumerPkg/v1@demo/test: Error in configure() method, line 19
	if self.options.MODE != self.options['DepPkg'].DEP_MODE:
	ConanException: option 'DEP_MODE' doesn't exist
Possible options are []
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sunj1 

Thanks for your question.

Conan 1 also supports the ``validate()`` method for these cases:
```python
def validate(self):
       if self.dependencies["mydep"].options.someoption != 2:
            raise ConanInvalidConfiguration("Option 2 of 'dep' not supported")
```

Please note that Conan 1 is deprecated, and Conan 1.52 is already 2 years old. I'd strongly recommend prioritizing the upgrade to Conan 2. Staying in Conan 1 is a risk that even ourselves cannot fully control because of dependencies becoming deprecated or vulnerable, etc.

**Comment by sunj1** [comment]
Thanks for the super quick response.  
This method seems to have been introduced in v1.32 (from the docs).  

Could you please suggest me a better way of finding such newly introduced changes which are kind of breaking/backward-incompatible  (moving from version 1.7 to version 1.52) ?

**Comment by sunj1** [comment]
> Hi @sunj1
> 
> Thanks for your question.
> 
> Conan 1 also supports the `validate()` method for these cases:
> 
> ```python
> def validate(self):
>        if self.dependencies["mydep"].options.someoption != 2:
>             raise ConanInvalidConfiguration("Option 2 of 'dep' not supported")
> ```
> 
> Please note that Conan 1 is deprecated, and Conan 1.52 is already 2 years old. I'd strongly recommend prioritizing the upgrade to Conan 2. Staying in Conan 1 is a risk that even ourselves cannot fully control because of dependencies becoming deprecated or vulnerable, etc.

This works for the minimal reproducible example.  
But throws below error in some other conan recipie:

```
	if self.options.MODE.value in ["A","B"] and self.dependencies["DepPkg"].options.SECURE == "False":
	KeyError: {'ref': DepPkg/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}
```

**Comment by memsharded** [comment]
> Could you please suggest me a better way of finding such newly introduced changes which are kind of breaking/backward

In theory there are no breaking changes moving forward, updating to latest Conan 1.X versions should not be breaking.  For learning new released features, using the changelog in https://docs.conan.io/1/changelog.html and the blog in https://blog.conan.io/ where we post new feature updates is recommended.

**Comment by memsharded** [comment]
> self.dependencies["DepPkg"]

Note, one important thing to migrate is to make all packages lowercase, as Conan 2 supports lowercase only.


> KeyError: {'ref': DepPkg/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}

Yes, this is possible if the dependency ``DepPkg`` is not really a dependency or is another kind of dependency. It would be needed a fully reproducible example to be able to understand why. If it only exists in some scenarios, you might want to wrap it in a ``try-except``

**Comment by sunj1** [comment]
> > KeyError: {'ref': DepPkg/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}
> 
> Yes, this is possible if the dependency `DepPkg` is not really a dependency or is another kind of dependency. It would be needed a fully reproducible example to be able to understand why. If it only exists in some scenarios, you might want to wrap it in a `try-except`

I checked few environment variables to print verbose information, and found that using ` CONAN_VERBOSE_TRACEBACK=1` prints below traceback:

```
ERROR: Traceback (most recent call last):
  File "/opt/conan_1_52/lib64/python3.9/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/opt/conan_1_52/lib64/python3.9/site-packages/conans/client/graph/graph_binaries.py", line 411, in _compute_package_id
    conanfile.validate()
  File "/home/sun/repro_conan/consumerPkg/conanfile.py", line 19, in validate
    if self.options.MODE.value in ["A","B"] and self.dependencies["DepPkg"].options.SECURE == "False":
  File "/opt/conan_1_52/lib64/python3.9/site-packages/conans/model/dependencies.py", line 76, in __getitem__
    return self._data[r]
KeyError: {'ref': DepPkg/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}
```

Also, by using debug logging, I can see that conan was next trying to execute `rest_client_common.py[188]: REST: get: http:/...` call for the DepPkg on the conan server.

**Comment by memsharded** [comment]
Yes, it is expected, it is failing in ``self.dependencies["DepPkg"]`` because it seems ``DepPkg`` was not a dependency for that package in that specific point of execution. This is why I was suggesting to wrap it in a ``try-except`` to let it continue for that case.

**Comment by sunj1** [comment]
How to zero in to that specific case?  
The `try-except` will be applicable to all cases which will essentially make validate method of no use.  

Am I missing something?


I printed few elements at that point in the validate method, and it seems like no dependencies have been populated as of yet for that package.
```
print (self.dependencies.__dict__)
{'_data': OrderedDict(), '_require_filter': None}

print (self.dependencies.values())
odict_values([])

print (self.dependencies.items())
odict_items([])


```

**Comment by sunj1** [comment]
Minimal reproducible example:

ConsumerPkg:
```
from conans import ConanFile
from conans.errors import ConanException


class ConsumerConanFile(ConanFile):
    name = "ConsumerPkg"
    version = "v1"
    options = {
            "SECURE": [True, False],
            "MODE": ["A","B"]
            }
    default_options = "SECURE=True", "MODE=A"


    def requirements(self):
        self.requires('DepPkg/v1@demo/test')
        self.requires('SubDepPkg/v1@demo/test')

    def validate(self):
        print (self.dependencies.__dict__)
        print (self.dependencies.values())
        print (self.dependencies.items())

        if self.options.MODE != self.options['DepPkg'].DEP_MODE:
            raise ConanException("Values for MODE are different in Consumer(%s) and Dependency(%s)" % (self.options.MODE, self.options['DepPkg'].DEP_MODE))
```

DepPkg:
```
from conans import ConanFile

class DepConanFile(ConanFile):
    name = "DepPkg"
    version = "v1"
    options = {
            "DEP_SECURE": [True, False],
            "DEP_MODE": ["A","B"]
            }
    default_options = "DEP_SECURE=True", "DEP_MODE=A"

    def requirements(self):
        self.requires("SubDepPkg/v1@demo/test")
        
    def validate(self):
        print (self.dependencies.__dict__)
        print (self.dependencies.values())
        print (self.dependencies.items())

        if self.options.DEP_MODE != self.dependencies['DepPkg'].options.SUB_DEP_MODE:
            raise ConanException("Values for MODE are different in Dep(%s) and SubDependency(%s)" % (self.options.DEP_MODE, self.dependencies['SubDepPkg'].options.DEP_MODE))
```

SubDepPkg:
```
from conans import ConanFile

class DepConanFile(ConanFile):
    name = "SubDepPkg"
    version = "v1"
    options = {
            "SUB_DEP_SECURE": [True, False],
            "SUB_DEP_MODE": ["A","B"]
            }
    default_options = "SUB_DEP_SECURE=True", "SUB_DEP_MODE=A"
```

Run Command:
```
conan info .
{'_data': OrderedDict([({'ref': SubDepPkg/v1@demo/test#41c075206c4bfb748cb8a126eb627f7c, 'build': False, 'direct': True, 'test': False, 'visible': True}, <conans.model.conanfile_interface.ConanFileInterface object at 0x7f3c219b2340>)]), '_require_filter': None}
odict_values([<conans.model.conanfile_interface.ConanFileInterface object at 0x7f3c219b2340>])
odict_items([({'ref': SubDepPkg/v1@demo/test#41c075206c4bfb748cb8a126eb627f7c, 'build': False, 'direct': True, 'test': False, 'visible': True}, <conans.model.conanfile_interface.ConanFileInterface object at 0x7f3c219b2340>)])
ERROR: DepPkg/v1@demo/test: Error in validate() method, line 20
	if self.options.DEP_MODE != self.dependencies['DepPkg'].options.SUB_DEP_MODE:
	KeyError: {'ref': DepPkg/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}
```

**Comment by sunj1** [comment]
While I was trying to inspect the structure of objects in a loop,  
looks like some property/attribute caused the values to be cleared.  

The solution seems to work fine.
Thank you.
Closing the issue.

**Comment by memsharded** [comment]
Happy that it worked, thanks for the feedback.
