### ISSUE TITLE
[question] Conan SSL Errors With Artifactory

### ISSUE THREAD

**Issue by astough** [conan-io/conan#16817]
### What is your question?

Hi. My team is using Conan version 1.43.4 with Artifactory on an isolated network. Artifactory was recently updated by our IT department to version 7.84.16. Since this upgrade, any attempts to use Conan to communicate with Artifactory returns the following error...

`SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:852)'),))`

After some discussions with the IT team, we discovered that the version of Artifactory that we're now using requires all communications to use TLS version 1.3. We believe that the version of Conan we're using uses an older version of TLS which is why we're seeing these errors.

Since we're working on an isolated network, we install Conan from the self-contained executable. Is there a version of Conan that we could upgrade to with support for TLS version 1.3? Any other suggestions of things that we could do to fix this problem would be appreciated.

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @astough 

Thanks for your question.

The TLS version is more a function of the Python interpreter and its core libraries (the ssl one) and maybe the Python-requests http library, Conan itself doesn't define or use any specific TLS version. You might be able to print the python version by printing ``sys.version`` inside a recipe.

The Conan 1.43 version is quite deprecated nowadays, more than 2.5 years old, and we are already 1.5 years into the Conan 2.X release train, the recommended version for production. Please also note that ConanCenter will soon stop updating packages for Conan 1.X, only updates for Conan 2 will be done to packages there. I'd strongly recommend prioritizing the upgrade to Conan 2.

We changes in the Conan 1.X releases of the self-contained executable that could affect this, but it is true that the base Python installation for the self-contained executable have been gradually updated along the years.

So I'd suggest doing first a quick check with the latest Conan 1.65 version in your environment and see if it works.
- If it works, then I think it would be worth trying to update to it. If not possible for some reason, the feedback would be useful, and maybe doing a "bisect" to previous 1.X version to find a working one.
- If it doesn't work, I'd try with a ``pip install`` Conan, using a modern Python base environment. If the self-contained executable is very necessary for your case, it can be generated with the ``pyinstaller.py`` script at the root of the project.


Please let us know how it goes.

**Comment by astough** [comment]
I've completed some tests with the latest 1.X and 2.X versions of Conan and have provided the results of the tests in the table below.

| Conan Version | Python Version (via sys.version) | SSL Errors w/ Artifactory |
| - | - | - |
| 1.43.4 | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] | Yes |
| 1.64.1 | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] | Yes |
| 2.6.0 | 3.9.18 (main, Oct  3 2023, 00:20:18) [MSC v.1929 64 bit (AMD64)] | No |

It looks like the version of Python within the self-contained executable is the same between versions 1.43.4 and 1.64.1 which explains why updating to that version did not fix the SSL errors with Artifactory. Version 2.6.0 contains a newer version of Python which appears to be using TLS v1.3 because this version was able to communicate with Artifactory without any issues.

Our plan now is to update our codebase to use Conan v2.6.0, something we probably should have done a while ago.

Thanks for the help!

**Comment by memsharded** [comment]
Thanks for the feedback!

This looks correct, the base Python 3.6.8 looks insufficient.
If it helps in the migration, please recall that you can generate self-contained executables for Conan 1.64 with the Python version you want, it is relatively easy, running ``python pyinstaller.py`` in the root.

I think it is possible to close this issue as solved, and if you need you can open new tickets for any question about the pyinstaller. Thanks

**Comment by astough** [comment]
Sounds good.

Thanks!
