### ISSUE TITLE
[question] Conan 'home' with CI/CD Runners

### ISSUE THREAD

**Issue by cjserio** [conan-io/conan#16825]
### What is your question?

Our company uses GitLab for CI/CD. We have various machines for 'runners' but my question pertains to one platform in particular which is a linux machine running a linux docker container. When the pipeline goes to build our product, the build happens inside of this docker container. The most simple and naive thing to do would be to install conan inside the docker container and be done with it, but we care about pipeline efficiency so we installed an Artifactory server and uploaded all of our package dependencies there so that they don't need to be compiled, merely downloaded.

My question is this...If I simply install Conan inside the docker container, each run of the pipeline starts with a fresh docker contain so the conan home would be wiped out each time requiring all of the dependencies to be reinstalled each time.

I was wondering what the recommended practice would be to allow the conan cache to persist. Would it be to mount a directory from the host machine into the docker container and use that as the conan home directory so that it persists (if so, how do I tell conan where to put the home location?) or is there another way that's recommended?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cjserio 

Thanks for your question.

> I was wondering what the recommended practice would be to allow the conan cache to persist. Would it be to mount a directory from the host machine into the docker container and use that as the conan home directory so that it persists (if so, how do I tell conan where to put the home location?) or is there another way that's recommended?

The most important thing to know about cache is that it is not concurrent at this moment. CI are typically concurrent in nature, so mounting the same folder for the same image for every job could produce race conditions. 

Mounting a folder from the host to host the cache is not problematic per-se, and can be done, but it has to be done for mutually exclusive or sequential jobs. For example, we do it in ConanCenter for the builds of the same PR. Every commit triggers a new build, but the builds for a new PR are never concurrent, if a new commit comes, the previous build is stopped and a new build is launched, so they are guaranteed to be sequential.

There are another couple of mechanisms that might help:

- If you are using the same host machine for different guest docker runners, you might try to use the "download cache" feature, which is concurrent safe (in the same machine, but I think a Linux docker in a Linux host works too) to avoid the download transfer. The "download cache" can cache both external downloads from internet, but also downloads of Conan packages (``core.download:download_cache: Define path to a file download cache``)
- The ``conan cache save/restore`` might be a useful way to transfer some packages within a CI pipeline to make it faster, in some scenarios. Probably it is not recommended to do a full population of the cache, but more to transfer partial results of the pipeline and aggregate them https://docs.conan.io/2/devops/save_restore.html

Please let me know if this clarifies a bit. Thanks!

**Comment by cjserio** [comment]
Hi! Yes that's very helpful. Our pipelines are CPU and memory intensive and because of that we never run them concurrently however the download cache still seems like a more appropriate solution.

So if i understand correctly, we'd mount a directory from the host machine to the docker container and set that location as the download cache location and then we'd get concurrent caching of downloads across multiple processes and docker container instances? Seems simple enough!

**Comment by memsharded** [comment]
> So if i understand correctly, we'd mount a directory from the host machine to the docker container and set that location as the download cache location and then we'd get concurrent caching of downloads across multiple processes and docker container instances? Seems simple enough!

Yes, exactly. It is true that there is still a cost to pay, the cost of unzipping the ``tgz`` files, because the download cache saves the files compressed not after unzipping them, but at least the download time will be saved. The note about concurrent support is because concurrency is implemented with file locks, which in theory they only work for the same machine, but it seems they still work well when used in Linux docker containers.

If you are completely sure your CI will never do concurrency, then you can simply try to mount persistent storage for the Conan cache (then you might need to implement some cleaning policies to avoid unlimited growth over time of that cache, there are some Conan features like ``lru`` that can help):

**Comment by memsharded** [comment]
I am closing this ticket as responded, but please don't hesitate to re-open or create new tickets for any further question or issue you might have, thanks for your feedback!
