### ISSUE TITLE
[question] Migrating custom generator + user_info to Conan 2.0

### ISSUE THREAD

**Issue by nubenar** [conan-io/conan#16820]
### What is your question?

Hello, in Conan 1.x we've built several custom generators that rely on data from user_info. I am looking for a way to migrate this to Conan 2.0.

Example usecase: many of our components have a description file for measurement and calibration data. When the complete software is integrated, these description files are processed and merged into one large file.

### Conan 1.x Implementation (abbreviated)

In the component recipe:
```
def package_info(self):
    ...
    self.user_info.macfile = "mac_" + self.name + "_" + str(self.options.get_safe("variant"))
```

The custom generator would then loop over the dependencies, collect all the "macfile"s from the user_info along with their location in the conan cache and write the full paths of all "macfile"s to a cmake variable in a cmake file (or rather I should say, provide a filename() and content() method/@property that results in the generation of said cmake file with said content).

The integration recipe "requires" a number of components and "python_requires" the custom generator. In its CMakeLists.txt file it would include the cmake file generated by the custom generator and pass the list of "macfile"s to some external tool for processing.

### How to Migrate to Conan 2.0?

I understand that user_info has been removed in Conan 2.0, but custom generators still exist. I saw that there is a new attribute called conf_info, but that seems to be intended for a different purpose (see: https://docs.conan.io/2/reference/conanfile/methods/package_info.html#conan-conanfile-model-conf-info). Could this still be used as a replacement? The migration guide seems to suggest so: https://docs.conan.io/1/migrating_to_2.0/recipes.html#removed-self-user-info

I also thought about defining some directory convention, so that the custom generator would still loop over the dependencies and simply check the contents of a specific (sub)folder. I guess having such a convention is no better or worse than defining an arbitrary user_info attribute and would probably work. However, I must say, in Conan 1.x it just felt natural, deliberate and explicit to declare such artifacts, that are intended to be used by a consumer, in the package_info method, similar to how you declare your library in self.cpp_info.libs.

Note that we have a few similar usecases that we all solved in the same way, since they are fundamentally the same: some meta data fragment is stored in a file alongside individual components and needs to be processed into a single file on integration.

I'm looking for a solution that respects Conan 2.0's conventions (which is why I didn't jump on conf_info, since it might be considered misuse). Please let me know if more details are needed.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nubenar 

Thanks for your question.

> een removed in Conan 2.0, but custom generators still exist. I saw that there is a new attribute called conf_info, but that seems to be intended for a different purpose (see: https://docs.conan.io/2/reference/conanfile/methods/package_info.html#conan-conanfile-model-conf-info). Could this still be used as a replacement? The migration guide seems to suggest so: https://docs.conan.io/1/migrating_to_2.0/recipes.html#removed-self-user-info

Yes, the ``user_info`` has been replaced by ``conf_info``. I think you can safely use that to migrate. Just some clarification:

- The ``conf_info`` is propagated automatically to the ``self.conf`` of consumers exclusively for direct ``tool_requires``. 
- Regular requires do not propagate the ``conf_info``, but it is always possible to access its information from the consumer via ``self.dependencies["mydep"].conf_info``

This was done for some reasons:
- Too many mechanisms to propagate information
- ``conf`` mechanism allows more powerful features and control, like appending, prepending, updating, and also overriding values from user side. It also provides validation in ``get()`` both of type and choices.

please let me know if this helps.

**Comment by nubenar** [comment]
Thanks for the clarification, @memsharded! I guess the special handling in case of tool_requires and the naming ("conf") led me to believe that this was not suitable for general usage. I will proceed with conf_info.

**Comment by memsharded** [comment]
Yes, the ``conf`` is divided in built-in ``core.xxx`` and ``tools.yyy``, and users can use the ``user.zzz`` scope (you might use ``user.orgname.zzz`` if sharing packages with more organizations), to make the ``conf`` mechanism usable and extensible by users too.

Feel free to close the ticket, you can always re-open or create new tickets for any further question. Thanks for the feedback!
