### ISSUE TITLE
conan not working properly when using GNUInstallDirs

### ISSUE THREAD

**Issue by LucidDistress** [conan-io/conan#16829]
### Describe the bug

RHEL 8.3
Tried this on two different servers. One with Conan 2.5.0 and another with 2.2.3.

Our team is fairly new to conan so thank you for the support.

We have a product that choose to use GNUInstallDirs within their cmake structure. We started using that product in what I will call our primary product and started seeing issues with locations of libraries bouncing between lib and lib64. When I examined his conan.py I noticed at some point he added a second libdir to all of his components. Hoping to fix the inconsistencies, I tried removing the extra "lib" dir since everything should be in lib64, but that caused conan create to stop working so I assume he added lib to fix that.

`def package_info(self):
        # The libs to link against
        self.cpp_info.components["core"].libs = ["SymRLCore"]
        # Directories where libraries can be found
        self.cpp_info.components["core"].libdirs = ["lib", "lib64"]`

The reason all of this even became apparent is he added hardcoded installs for his shared libraries in the main repo and the installs would fail on occasion depending on where the library ended up being. As a test, and in an attempt to remove this hardcoded cmake installs, I was going to attempt to use the generate section of conan..py in order to copy our runtime dependencies to the right location. As a test I tried printing the libdirs for this library and even though a lot of the generated files as part of conan install showed two different paths (lib, lib64) the print showed only:

/home/users/td26750/.conan2/p/symrl0f6ecf44fd379/p/lib

Problem is, when I try to look at the directory, it does not exist. lib64 does. This is my last shot before I just gut all of his GNUInstallDirs code so hopefully you guys have some answers.

An example of one of his cmake install commands:

`install(TARGETS ${component}
           COMPONENT ${component}
           LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
           NAMELINK_ONLY
           RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
           ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)`

Admittedly it could be something in his install command because that is way more complicated than I would normally make an install command.

**Comment by jcar87** [comment]
Hi @LucidDistress - thanks for reaching out.

```
install(TARGETS ${component} COMPONENT ${component} LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} NAMELINK_ONLY RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} )
```

I would say this is perfectly valid, but at the same time I think this explains the inconsistencies you are seeing.
The  problem is that the `GNUInstallDirs` module is has different behaviour depending on the machine doing the build - so there is some "system instrospection". On non-Debian systems it will generally be `lib64`, in other systems it will be `lib`. 

https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake#L296-L305

This can cause some inconsistencies if the same recipe is built on different flavours of Linux (you mention RHEL, are you using any other, perhaps inside Docker?)

oh the other hand, Conan does define these variables in `conan_toolchain.cmake`


```
set(CMAKE_INSTALL_BINDIR "bin")
set(CMAKE_INSTALL_SBINDIR "bin")
set(CMAKE_INSTALL_LIBEXECDIR "bin")
set(CMAKE_INSTALL_LIBDIR "lib")
set(CMAKE_INSTALL_INCLUDEDIR "include")
set(CMAKE_INSTALL_OLDINCLUDEDIR "include")
```

but they will be shadowed by the values given by `GNUInstallDirs` I suspect.


As a workaround, may I suggest you try the following using Conan 2.6.0 (I think this feature may have landed in 2.5.0 too). Add the following to your Conan profile

```
[conf]
tools.cmake.cmaketoolchain:extra_variables={'CMAKE_INSTALL_LIBDIR': {'value': 'lib', 'cache': True, 'type': 'STRING', 'docstring': 'install libdir'}}
```

Or, alternatively, pass `-c "tools.cmake.cmaketoolchain:extra_variables={'CMAKE_INSTALL_LIBDIR': {'value': 'lib', 'cache': True, 'type': 'STRING', 'docstring': 'install libdir'}}"` via the command line.

This will cause the variable to be defined as a cache variable and prevent `GNUInstallDirs` from overriding it (as I can see it uses cache variables too).

**Comment by LucidDistress** [comment]
Thank you so much for your answer. I was going to try out your specific workaround, but you mentioning this reminded me that for release build purposes, there is a different runner for this product then the server I was testing on. It has a newer version of RHEL and ironcially enough, an older version of conan. After beating my head against the wall trying to make it use lib64, I discovered that lib64 only shows up when doing conan export-pkg and NOT when using conan create. That was very frustrating to prove. For now I am going to change the runner, but I will keep your answer in my back pocket in case I need it. Thank you for the help.

**Comment by LucidDistress** [comment]
Left this open just so I could confirm. Updating the conan version did in fact make the lib64 issue go away. Thank you so much for the help.

**Comment by glennaycock** [comment]
We are having a similar issue while migrating to Conan 2.x. Our existing CMake project works perfectly using 1.x recipes and dependencies. The introduction of CMakeDeps and CMakeToolchain in 2.x results in the GNUInstallDirs variables being overridden with incorrect values corresponding to the defaults posted above. CMAKE_INSTALL_LIBDIR gets set to 'lib' instead of 'lib64' and CMAKE_INSTALL_SBINDIR gets set to 'bin' instead of 'sbin'. We will try the workaround, but I would rather not arbitrarily replace the values generated by GNUInstallDirs because then we also have to incorporate that into the developer environment.
