### ISSUE TITLE
[question] cpp_info in editable mode

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#16822]
### What is your question?

Hello,

I created an example here: https://github.com/Todiq/test_conan

In the `package_info()` method of `test_alpha` I set the following line: `self.runenv_info.define("TEST", os.path.join(self.package_folder, self.cpp_info.resdirs[0]))`

The resdirs were set in the `layout()` method of `test_alpha`, as the location differs depending if the package is in editable mode or not:

```python
self.cpp.source.resdirs = ["source"]
self.cpp.package.resdirs = ["package"]
```

\
\
When setting `test_alpha` as an editable, then running `conan install` on `test_alpha` and `test_beta`, we can observe that the variable `TEST` in beta's `conanrunenv-release-x86_64.sh` is set to the following: `export TEST="/workspace/test_conan/alpha/package"`

However, I expected it to be set to: `export TEST="/workspace/test_conan/alpha/source"`
\
\
I understand that it might be expected. When executing `test_alpha()`'s `package_info()` it is expected for it to be in the cache (in opposition to being editable). Hence, `self.cpp_info.resdirs[0]` would naturally point to `self.cpp.package.resdirs`, previously set in `layout()`
\
\
\
However, while there is a dynamic way to access the current location of the package through `self.package_folder`, how could one do the same with any of the values stored in `cpp_info`?

In fact, I would like to dynamically store the path to my resdirs into an environment variable for my consumers to easily access it. Could you please enlighten me?

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your question.

I think you are looking for ``self.cpp.source.buildenv_info``, ``self.cpp.build.runenv_info``, etc. 

Please check last part of https://docs.conan.io/2/reference/conanfile/methods/layout.html#environment-variables-and-configuration, and let us know.

**Comment by Todiq** [comment]
That did the trick, thank you
