### ISSUE TITLE
[bug] building QT 6.5.3 under WSL2, conan builds/installs a "cmake" that fails to run. 

### ISSUE THREAD

**Issue by loopless** [conan-io/conan#16831]
### Describe the bug

I am trying to use qt/6.5.3 under WSL2, Windows 11
The build process fails as the "cmake" that gets installed by conan (3.30.1) and used by the build process fails to run.

$ which cmake
/home/acu/dev/conan/cmake/3.30.1/_/_/package/a4c020c25ae9692dd8c8e9f1e67b3983185d7d65/bin/cmake
$ cmake
Inconsistency detected by ld.so: dl-version.c: 204: _dl_check_map_versions: Assertion `needed != NULL' failed!

attached 

### How to reproduce it

[cmake_build.txt](https://github.com/user-attachments/files/16627421/cmake_build.txt)

conanfile.txt as follows
[requires]
qt/6.5.3

[generators]
cmake_find_package
cmake_paths

Then  in a build directory 
conan install ../  -u --build=missing -c tools.cmake.cmaketoolchain:generator="Ninja"

**Comment by loopless** [comment]
The attachment shows the build/install on my machine of cmake version 3.30.1 by conan

**Comment by loopless** [comment]
OK, I found the issue. We have a conan hook "strip.py". For some reason, this is making the cmake binary not run.
Our bad :)

**Comment by memsharded** [comment]
Hi @loopless 

Thanks for the feedback.

I am seeing that you are still using Conan 1.X and legacy ``cmake_find_package`` generators, replaced by ``CMakeToolchain`` + ``CMakeDeps`` in Conan 1. Please note that Conan 2 is already 18 months now, and all dev effort have been shifted to Conan 2 already. If you are using packages from ConanCenter, they will soon stop receiving updates (fixes, new versions, etc) for Conan 1, they will be "frozen". I'd strongly recommend prioritizing moving to Conan 2, let us know if you have any questions regarding that.
