### ISSUE TITLE
[question] Adding test_package which automatically sets up environment for run-time linkage to tested reference

### ISSUE THREAD

**Issue by Tails86** [conan-io/conan#16836]
### What is your question?

Conan version: 2.6.0
OS: Linux (Ubuntu) and Windows
Compilers: GCC and MSVC, C++17

It looks like the run environment for a test package doesn't automatically add the tested reference library directory to the run environment. Is there anything I can do to have this automatically added through some Conan hook?

I am following the [test_package](https://docs.conan.io/2/tutorial/creating_packages/test_conan_packages.html) tutorial with the following differences:
- I define my own `generate()` method which uses `CMakeToolchain` and `CMakeDeps` 
- I execute `cmake.test(cli_args=["--verbose"], env="conanrun")` to run the tests

I do have the following, and the tested reference is getting properly linked in the build. The test generates an executable which links against shared libraries of the tested reference.
```py
    def requirements(self):
        self.requires(self.tested_reference_str)
```

This is my current workaround: at the end of my `generate()` method, I have the following in order to explicitly inject the tested reference library path into the environment.
```py
        tested_name = str(self.tested_reference_str).split('/', maxsplit=1)[0]
        virt_env = VirtualRunEnv(self)
        env = virt_env.environment()
        if sys.platform.lower().startswith("win"):
            # Windows - add bindirs to PATH
            for d in self.dependencies[tested_name].cpp_info.bindirs:
                env.prepend_path("PATH", d)
        else:
            # Linux - add libdirs to LD_LIBRARY_PATH
            for d in self.dependencies[tested_name].cpp_info.libdirs:
                env.prepend_path("LD_LIBRARY_PATH", d)

        virt_env.generate()
```

My main concern is that my current solution is not completely portable.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tails86 

Thanks for your question.

In theory it shouldn't be necessary to do anything extra, it should work pretty much out of the box. 
For example the:
```bash
$ conan new cmake_lib -d name=hello -d version=0.1
$ conan create . -o *:shared=True
```
works using the shared library from the dependency with a ``self.run(cmd, env="conanrun")`` in the ``test_package/conanfile.py``, so I am not sure what could be the cause in your use case. Even ``cmake.test(cli_args=["--verbose"], env="conanrun")`` might be unnecessary, the default already uses ``conanrun``, so using ``cmake.test(cli_args=["--verbose"])`` should work too.

Do you have something minimal that I could reproduce on my side to check it? Thanks!

**Comment by Tails86** [comment]
Thanks for your response. 

I did look back into my Linux build and determined that I do not need to set `LD_LIBRARY_PATH` as you stated. I may have needed to in the past for one reason or another which I can't determine at the moment. However, my workaround seems to still be needed for Windows to find the dependent library properly.

Here is my sample code which runs unit test properly in Linux but not in Windows (at least on my system).
[conan_example_jms.zip](https://github.com/user-attachments/files/16664306/conan_example_jms.zip)

I'm simply running the following in a powershell.
```
cd conan_example_jms
conan create .
```

If you uncomment lines 47 through 54 in `test_package\conanfile.py`, then the test runs fine in Windows too.

**Comment by Tails86** [comment]
It seems that everything works on windows if I change the requirements definition to the following. Is this the correct way to go about this?
```py
    def requirements(self):
        self.requires(self.tested_reference_str, run=True)
```

I'm a little confused because I'm not deviating too far from the example created from `conan new cmake_lib` command, and that didn't require `run=True`.

**Comment by memsharded** [comment]
Thanks for the feedback.

The issue is that you are missing the ``package_type = "shared-library"``, to indicate that this is a shared library and then consumers will automatically deduce the ``run=True`` trait. The package type can also be automatically deduced if you define an ``option`` ``shared``. See https://docs.conan.io/2/reference/conanfile/attributes.html#package-type

**Comment by Tails86** [comment]
Ah, yes. That's what I was missing! Thanks for helping me with this

**Comment by memsharded** [comment]
Happy to help! Don't hesitate to create new tickets for any further question.
