### ISSUE TITLE
[bug] Remote login variables not working in docker runner

### ISSUE THREAD

**Issue by solosuper** [conan-io/conan#16834]
### Environment details

* OS: Ubuntu 22.04
* Compiler: not relevant(?)
* Conan runner config:

    ```yaml
    image: myimage
    run:
      name: container_name
      containerEnv:
        CONAN_LOGIN_USERNAME_ARTIFACTORY: username
        CONAN_PASSWORD_ARTIFACTORY: password
      containerUser: developer  
   ```
* `docker_host` profile:

    ```
    # ... snip
    [runner]
    type=docker
    cache=clean
    remove=true
    configfile=/home/solosuper/myrunnerfolder/runnerconfig
    ```
### Description

I am following the [Creating a Conan package using a Docker runner](https://docs.conan.io/2/examples/runners/docker/basic.html) tutorial, using my own recipe.

At first, I am facing #16812,
<details>
<summary><b>Expand to see details, which should however be unrelated to this current issue</b></summary>

<pre>
conan create ./recipes/my_recipe -pr:h /home/solosuper/myrunnerfolder/docker_host -pr:b /home/solosuper/myrunnerfolder/docker_build
</pre>

<pre>
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Running in container: "conan create /developer/conanrunner/my_recipe -pr:h /home/solosuper/myrunnerfolder/docker_host -pr:b /home/solosuper/myrunnerfolder/docker_build -f json > create.json"  |
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ERROR: Profile not found: /home/solosuper/myrunnerfolder/docker_build
</pre>
But the profile certainly exist, else the `conan create` errs at a much earlier stage. Relative paths yield the same.

The problem seems to be that the runner  interprets the path literally at this stage.
</details>

By copying the profiles into the docker image, I am able to proceed. However, now I cannot login to my private remote.

```
======== Computing dependency graph ========
superflow/5.0.0: Not found in local cache, looking in remotes...
superflow/5.0.0: Checking remote: conancenter
superflow/5.0.0: Checking remote: artifactory
Please log in to "artifactory" to perform this action. Execute "conan remote login" command.
Remote 'artifactory' username:
```
I have tried the [CONAN_LOGIN_USERNAME_{REMOTE_NAME}](https://docs.conan.io/2/reference/environment.html#remote-login-variables) both in the runner config and as `ENV` in the dockerfile, but the seem not to come through to the `======== Computing dependency graph ========` in the docker runner.

Expected behavior:
```
Got username '<user>' from environment
Got password '******' from environment
```

### How to reproduce it

I am trying as closely as possible to follow the tutorial, but with my own recipe and remote.

**Comment by czoido** [comment]
Hi @solosuper,

Thanks a lot for your question and sorry for the late response.

For the first part regarding the profiles, we have added a [note in the docs](https://docs.conan.io/2/reference/runners/docker.html#how-to-use-a-docker-runner) explaining that the profiles you use for the runners must be in the conan home in the profiles folder to be recognized, profiles outside that folder will not work correctly.

For the part of the remote, I have been trying to reproduce the issue but apparently everything works fine for me. Is this issue still happening for you? Which Conan version are you using?
To try to debug the issue what you could do is using `remove=false` in the profile and then connecting to `container_name`:

```
docker exec -it container_name /bin/bash 
```

Then, print the environment variables to check that they are correctly set. 
You can also try to check the defined remotes with `conan remote list` there to try to debug the issue or trying to connect with `conan search "*" -r remote`

Please check and report us back if you find anything.

**Comment by czoido** [comment]
Hi @solosuper,
Could you check again? Is this still an issue for you?
Thanks a lot!

**Comment by solosuper** [comment]
Hi @czoido ,
Thank you for response, and I sorry for responding late as well.

I have tried again with conan 2.8.1 and profiles in ~/.conan2/profiles as you suggested, and I am no longer able to reproduce the issue :shrug: 

Thank's anyway, feel free to close the issue :slightly_smiling_face:

**Comment by czoido** [comment]
> Hi @czoido , Thank you for response, and I sorry for responding late as well.
> 
> I have tried again with conan 2.8.1 and profiles in ~/.conan2/profiles as you suggested, and I am no longer able to reproduce the issue 🤷
> 
> Thank's anyway, feel free to close the issue 🙂

Great to hear it’s resolved—I’ll close the issue. Thanks a lot! 😊
