### ISSUE TITLE
[bug] inconsistent `-f` options

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#16835]
### Describe the bug

E.g.

`conan remote -f` means `--force`
`conan remote auth -f` means `--format`

**Comment by memsharded** [comment]
Hi @DmitrySokolov 

Thanks for your feedback.

I guess the first line you mean ``conan remote add -f``, as ``conan remote -f`` is not really a command.

It is true that there is a small overlap, only in the short forms of the cli arg, the arguments are really ``--format`` and ``--force`` which are well defined and used thoroughly in other commands, even co-existing (in those cases the short form is not defined) Besides the overlap, there is no much larger impact, things are not really malfunctioning or causing errors. And changing this would be breaking behavior, so not worth doing any change in these arguments. Thanks very much for pointing it anyway!
