### ISSUE TITLE
How can I have libstdc++ version and glibc version in profile

### ISSUE THREAD

**Issue by oblique** [conan-io/conan#1684]
Consider this code:

```
#include <stdio.h>

int main() {
    char buf[100];
    FILE *f = fmemopen(buf, sizeof(buf), "r");
    fclose(f);
}
```

If you compile this on ArchLinux and then try to run it on Centos 7 you will get

```
a.out: /lib64/libc.so.6: version `GLIBC_2.22' not found (required by a.out)
```

ArchLinux now has GCC version 7.1. This version can be installed in Centos 7 manually.
Also most of the time distributions have different glibc versions and you can have this kind of error.

In my development environment I have this issue. I can workaround it if I manually clone all my dependencies and add to them `package_id`.

I don't like the above workaround, so I'm trying to do it by editing only my consumers' `conanfile.py`. I couldn't find any way to inform my dependencies about the new `self.info.settings.compiler.version`. Also I couldn't find a way to add this in profile instead.

The same goes with libstdc++. You can get their versions with:

```
strings /usr/lib/libc.so.6 | grep '^GLIBC_\([0-9.]\)' | sort -u -V | tail -n1
strings /usr/lib/libstdc++.so | grep '^GLIBCXX_\([0-9.]\)' | sort -u -V | tail -n1
```

Any suggestions?

**Comment by lasote** [comment]
This is the same problem we had with **travis.ci** when we upgraded the compiler in an old Ubuntu distribution, then the packages failed to be reused in a modern Linux with the same compiler version, because of the ``libc`` or ``stdlib`` version.

If you are going to mix the standard libraries you have to model them as settings. Some users introduced the distribution and version in the settings.yml, some others modeled directly the version of the standard library.

We do not model it by default because usually the libraries are consumed in a system with a similar compatible standard library, but if it is your use case, the only way to guarantee the compatibility is to introduce new settings.

You could try also to generate the packages with the older glibc and see if it's compatible with the new one (sometimes backward compatible).

**Comment by oblique** [comment]
> some others modeled directly the version of the standard library.

I don't understand what do you mean by this.

> the only way to guarantee the compatibility is to introduce new settings.

I need to also modify the `settings` variable in the `conanfile.py`, correct?

**Comment by lasote** [comment]
> I don't understand what do you mean by this.

I meant some users have introduced a new setting to model the glibc version. Maybe it has the sense to add it as a subsetting of Linux operating system?

```
os:
    Windows:
    Linux:
       glibc: [None, "2.15", "2.16", "2.17", "2.18", "2.19", "2.20", "2.21", "2.22", "2.23", "2.24", ...........]
    Macos:
```
> I need to also modify the settings variable in the conanfile.py, correct?

If it is a subsetting you don't need to modify the conanfile, because you already have the "os"

**Comment by oblique** [comment]
Cool! Thanks a lot.

**Comment by kheaactua** [comment]
> > I don't understand what do you mean by this.
> 
> I meant some users have introduced a new setting to model the glibc version. Maybe it has the sense to add it as a subsetting of Linux operating system?
> 
> ```
> os:
>     Windows:
>     Linux:
>        glibc: [None, "2.15", "2.16", "2.17", "2.18", "2.19", "2.20", "2.21", "2.22", "2.23", "2.24", ...........]
>     Macos:
> ```
> 
> > I need to also modify the settings variable in the conanfile.py, correct?
> 
> If it is a subsetting you don't need to modify the conanfile, because you already have the "os"

Is there any way to detect the version of glibc?  I don't see anything in the `detect_api` functions that would do this.

I think I'm running into a glibc version compatibility issue in my binaries when I build stuff on 22.04 with clang 18 and try to link with stuff I built on a 24.04 system with the same version of clang. (I could be wrong, but that's what I suspect)

It would be great if I could do:
```
[settings]
os.glib2={{detect_api.detect_libcxx_version()}}
```

**Comment by memsharded** [comment]
There is the ``detect_api.detect_libc()``, check in https://docs.conan.io/2/reference/config_files/profiles.html:

> detect_libc(ldd="/usr/bin/ldd"): experimental returns a tuple with the name (e.g., “gnu”, “musl”) and version (e.g., “2.39”, “1.2.4”) of the C library.


> I think I'm running into a glibc version compatibility issue in my binaries when I build stuff on 22.04 with clang 18 and try to link with stuff I built on a 24.04 system with the same version of clang. (I could be wrong, but that's what I suspect)

Please recall that in some situations it might be more convenient to model this binary compatibility in terms of "distro", defining the "families" or "groups" of jointly compatible distros/versions. as a higher level abstraction over the glibc version.

**Comment by kheaactua** [comment]
> There is the `detect_api.detect_libc()`, check in [docs.conan.io/2/reference/config_files/profiles.html](https://docs.conan.io/2/reference/config_files/profiles.html):
> 
> > detect_libc(ldd="/usr/bin/ldd"): experimental returns a tuple with the name (e.g., “gnu”, “musl”) and version (e.g., “2.39”, “1.2.4”) of the C library.
> 
> > I think I'm running into a glibc version compatibility issue in my binaries when I build stuff on 22.04 with clang 18 and try to link with stuff I built on a 24.04 system with the same version of clang. (I could be wrong, but that's what I suspect)
> 
> Please recall that in some situations it might be more convenient to model this binary compatibility in terms of "distro", defining the "families" or "groups" of jointly compatible distros/versions. as a higher level abstraction over the glibc version.

Oh awesome!  I'll give it a try.  Thanks!

I was thinking of somehow using the release (_e.g._ 22.04, 24.04) - though I don't think this would have been a great solution - is there any way to detect that in a profile?

**Comment by memsharded** [comment]
The profiles do inject the ``distro`` helper into the jinja render context, that allows to do checks on linux distros, you can call ``distro.xxx`` in your jinja code, maybe that helps.

**Comment by kheaactua** [comment]
> The profiles do inject the `distro` helper into the jinja render context, that allows to do checks on linux distros, you can call `distro.xxx` in your jinja code, maybe that helps.

That sounds great, but I don't see it in the docs.  Is this in https://docs.conan.io/2/reference/config_files/profiles.html ?  I don't see anything in the [search results](https://docs.conan.io/2/search.html?q=distro&check_keywords=yes&area=default) either.

What properties does `distro` have?

**Comment by memsharded** [comment]
Oh, I see, you are right, it is only defined in the ``global.conf`` jinja2 template, not in the profiles template, my mistake.
That ``distro`` is this package: https://pypi.org/project/distro/

Sorry for the confusion.

The ``platform`` module is injected too, you might try with ``platform.release()`` in your template.

**Comment by kheaactua** [comment]
> Oh, I see, you are right, it is only defined in the `global.conf` jinja2 template, not in the profiles template, my mistake. That `distro` is this package: [pypi.org/project/distro](https://pypi.org/project/distro/)
> 
> Sorry for the confusion.
> 
> The `platform` module is injected too, you might try with `platform.release()` in your template.

Amazing, thanks!

I think the libc version will resolve my issues in a better way, but it's great to find out about this package too.

**Comment by memsharded** [comment]
Sure, it was only a suggestion, it might be better in some situations, but if finer control is desired ``libc`` version might be better.

Thanks for the feedback!
