### ISSUE TITLE
[feature] Add support for sane defaults in `package_info` based on `package_type` using the new `implements`

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#16843]
### What is your suggestion?

I've been discussing with @danimtb the possibility to add a new entry to the valid `implements` attribute, so that the recipe automatically sets some default values in the `package_info` for the user, based on the `package_type` for example.

This one would be different to the other current valid values, in that having it enabled and defining a custom `package_info` method would not invalidate the default implementation.

The idea with an example would be to have something like `implements = ["package_info_defaults"]` that would maybe have code like

```py
if conanfile.package_type is PackageType.HEADER:
    conanfile.cpp_info.bindirs = []
    conanfile.cpp_info.libdirs = []
elif ...
```

so that recipes can save those boilerplate lines (Along with possibly others?) and can write the important stuff in their `package_info`s

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for the suggestion @AbrilRBS !

I'd like to first understand the possible optimizations. Is it only the ``package_type = "header-library"``, or are there others that can be deduced and automated?

**Comment by memsharded** [comment]
We have discussed this:

- The abstraction ``implements = ["package_info_defaults"]`` could be a bit too high-level or not clear for users, while the explicit ``conanfile.cpp_info.bindirs = []`` is easy to understand by users
- In the best case, it saves 2 lines of code in the recipes (1 if counting that a new line ``implements`` is needed).
- This would be a good default for potentially breaking Conan 3.0 behavior

I am labeling this as Conan3, but closing it as this is something not planned at the moment.
