### ISSUE TITLE
[question] Get the exact version of a just installed package

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#16845]
### What is your question?

The command
```
conan install --require 'pkg/[~1.2]' --profile 'name.conf'
```
will install 'pkg' package version 1.2.x

How can I get the reference of a just installed package: 'pkg/ver#rev:id' ?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DmitrySokolov 

Thanks for your question.

The information will be in the output. If you add ``--format=json > graph.json``, you will find that information (and more) in the resulting ``graph.json``

**Comment by DmitrySokolov** [comment]
Hi, 

Thanks!
