### ISSUE TITLE
[bug] SyntaxWarning in visual studio tests

### ISSUE THREAD

**Issue by Sahnvour** [conan-io/conan#16851]
### Describe the bug

Warning when installing conan from AUR on archlinux:

```
[...]
/usr/lib/python3.12/site-packages/conan/test/assets/visual_project_files.py:3: SyntaxWarning: invalid escape sequence '\M'
  sln_file = '''
/usr/lib/python3.12/site-packages/conan/test/assets/visual_project_files.py:41: SyntaxWarning: invalid escape sequence '\M'
  vcxproj_file = '''<?xml version="1.0" encoding="utf-8"?>
/usr/lib/python3.12/site-packages/conan/test/assets/visual_project_files.py:3: SyntaxWarning: invalid escape sequence '\M'
  sln_file = '''
/usr/lib/python3.12/site-packages/conan/test/assets/visual_project_files.py:41: SyntaxWarning: invalid escape sequence '\M'
  vcxproj_file = '''<?xml version="1.0" encoding="utf-8"?>
[...]
```

### How to reproduce it

I was using `pikaur` to update my packages, `conan` from `2.5.0-1` to `2.6.0-1`.
I guess just a barebones AUR install of the package will produce the same warning.

**Comment by memsharded** [comment]
Hi @Sahnvour 

Thanks for the feedback.
I am doing a PR to remove those warnings in the ``visual_project_files.py``, but if there are more warnings in other files, please provide the full log. Thanks!

**Comment by Sahnvour** [comment]
Thanks, I did not have any other.
