### ISSUE TITLE
[question] How To Use The  Release Conan Package With RelWithDebInfo Build Type?

### ISSUE THREAD

**Issue by crystalsky** [conan-io/conan#16852]
### What is your question?

1. The version of Conan is 1.55.
2. conan install used the generators: cmake, CMakeDeps, VirtualRunEnv, and CMakeToolChain.
3. In the CMake project, CMAKE_BUILD_TYPE=RelWithDebInfo.
4. The Conan packages are all in Release.
5. After conan install, the corresponding package's CMake dependency files are correctly generated.
6. In the project, Conan packages like curl::curl are referenced, but the project cannot find the package's header file directory and library paths, causing the linking to fail.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @crystalsky 

Thanks for your question.

You can use the "profile patterns" to define specific settings for any package, including the current "consumer" one using the ``&`` placeholder.

In this case something like:
```
conan install . -s build_type=Release -s &:build_type=RelWithDebInfo
```
(you can put those in a profile file as well)
That means that all the dependencies are ``build_type=Release``, except the current project you are building for (``&``) that will be ``build_type=RelWithDebInfo``.

Please try that and let us know.

**Comment by crystalsky** [comment]
@memsharded 
**the command not working.  :build_type=RelWithDebInfo is not a command**
```sh
conan install . -s build_type=Release -s &:build_type=RelWithDebInfo
```

**Comment by memsharded** [comment]
That depends on the specific terminal, and how the terminal is escaping characters. If it doesn't, try quoting the arguments, something like this (depending on the terminal):

```
conan install . -s build_type=Release -s "&:build_type=RelWithDebInfo"
```

**Comment by memsharded** [comment]
Any further comment here @crystalsky? Can we close this ticket? Thanks

**Comment by crystalsky** [comment]
I leave the question to do other project.....I forgot this. 
I will try this in two days. and to close this question as fast as i do.

**Comment by crystalsky** [comment]
It works for me . Thanks!!!!! God Job!!!!

**Comment by memsharded** [comment]
Great, happy to help 😄 thanks for the feedback!

**Comment by unidevop** [comment]
Great solution, it works for conan 2.x.
