### ISSUE TITLE
[bug] `conan install --requires` not working

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#16850]
### Describe the bug

```
conan install --remote 'itc_server' --requires 'qt6/6.7.2+build.1#4afac3afcf02fe76118f8dff49ce1834:2068baaab67a8d1ae925bbe12c37df5b885a6d56' -pr:a .\windows-x86_64-vc143-release.conf

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
qt6/6.7.2+build.1: Not found in local cache, looking in remotes...
qt6/6.7.2+build.1: Checking remote: itc_server
Graph root
    cli
ERROR: Package 'qt6/6.7.2+build.1' not resolved: Unable to find 'qt6/6.7.2+build.1#4afac3afcf02fe76118f8dff49ce1834:2068baaab67a8d1ae925bbe12c37df5b885a6d56' in remotes.
```

``` 
conan list -r 'itc_server' --format json 'qt6/6.7.2+build.1#4afac3afcf02fe76118f8dff49ce1834:2068baaab67a8d1ae925bbe12c37df5b885a6d56'
{
    "itc_server": {
        "qt6/6.7.2+build.1": {
            "revisions": {
                "4afac3afcf02fe76118f8dff49ce1834": {
                    "timestamp": 1724087314.466,
                    "packages": {
                        "2068baaab67a8d1ae925bbe12c37df5b885a6d56": {
                            "info": {
                                "settings": {
                                    "arch": "x86_64",
                                    "build_type": "Release",
                                    "compiler": "msvc",
                                    "compiler.cppstd": "17",
                                    "compiler.runtime": "dynamic",
                                    "compiler.runtime_type": "Release",
                                    "compiler.version": "193",
                                    "os": "Windows"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by DmitrySokolov** [comment]
```
conan install --remote 'itc_server' --requires 'qt6/6.7.2+build.1' -pr:a .\windows-x86_64-vc143-release.conf

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
qt6/6.7.2+build.1: Not found in local cache, looking in remotes...
qt6/6.7.2+build.1: Checking remote: itc_server
qt6/6.7.2+build.1: Downloaded recipe revision 4afac3afcf02fe76118f8dff49ce1834
...
```

**Comment by AbrilRBS** [comment]
Hi @DmitrySokolov thanks a lot for your question.

This is not a bug, but expected behaviour. Your issue here is that you can't not require a library by its _package id_ (That's the hash after `:` in your reference), as that's actually computed from the profiles you supply Conan with, and Conan manages to find the correct one for each configuration. You should only provide a `name/version` (And optionally a recipe revision `name/version#reciperevision`), but nothing more

Check https://docs.conan.io/2/reference/commands/install.html#conanfile-path-or-requires for some exmaples on `conan install`, and [this section of the tutorial](https://docs.conan.io/2/tutorial/consuming_packages/different_configurations.html#introducing-the-concept-of-package-id) for information about the package id

I hope this helps, let me know if you have any follow-up questions, happy to help where possible!

**Comment by DmitrySokolov** [comment]
Hi,

I can't see anything regarding `package_id` on the page `install.html#conanfile-path-or-requires`.

Why 
```
conan list "qt6/6.7.2" -fp .\windows-x86_64-vc143-release.conf -f compact -r itc_server
ERROR: --package-query and --filter-xxx can only be done for binaries, a 'pkgname/version:*' pattern is necessary
```
forces me to use `pakage_id` if it calculates from a profile?

**Comment by memsharded** [comment]
``conan list`` is a different command than the above ``conan install``.

For the ``conan list``, if we wish to filter the binaries based on a given profile, we need to provide a pattern that includes binaries. In this case it will be something like:

```
$ conan list "qt6/6.7.2:*" -fp=myprofile ...
```
Note the ``:*`` that means: list all binaries for qt6/6.7.2.

**Comment by DmitrySokolov** [comment]
As for me, it's a bit unclear.

`conan list pkg/ver` - list packages, ok

`conan list pkg/ver:*` - list packages with binaries, ok, but the separate option `--binaries` is more clear

then, `conan install pkg/ver#rev:id` - should be ok for installing the exact package binaries.


Thanks!

**Comment by memsharded** [comment]
> conan list pkg/ver - list packages, ok

We call them "recipes", they list only the existing recipes, which might or might not have binaries.

```
$ conan list zlib/* -r=conancenter
Found 6 pkg/version recipes matching zlib/* in conancenter
conancenter
  zlib
    zlib/1.2.8
    zlib/1.2.11
    zlib/1.2.12
    zlib/1.2.13
    zlib/1.3
    zlib/1.3.1
```

> conan list pkg/ver:* - list packages with binaries, ok, but the separate option --binaries is more clear

I have to disagree. We actually implemented, tried and experimented with it as users when we were designing the UX for Conan 2, and it was way more confusing and problematic. We believe the current approach is more clear and we are happy about this design.

> conan install pkg/ver#rev:id - should be ok for installing the exact package binaries.

As you know, hashes are not reversible. To install a package it needs to install its dependencies, it needs to resolve the dependency graph, so it needs the profiles (settings, options) as inputs. It is not enough to have a ``package_id`` as input to resolve a dependency graph, it is physically impossible, and this is why it is impossible to ``conan install`` a package based on its ``package_id``. What you can do is download it ``conan download pkg/version#revision:package_id``.
