### ISSUE TITLE
[question] Conan 2 Migration - Default User/Channel

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#16860]
### What is your question?

Hello, I am working on migrating my company's Conan 1.x infrastructure to Conan 2.x. Here's a simplified summary of our Conan approach:

- A repo has many packages within it
- Each package is using the company name as the user by way of the Conan 1.x `default_user`
- Each package is using the current Git branch as the channel by way of the Conan 1.x `default_channel` property
- Git Flow methodologies are being used; develop is our trunk
- Developers make updates to the packages and the versions they create would always have their branch name as the channel in the package reference

For example, a developer modifying package A would generate a package with reference A/1.0.0@company/feature_12345 by simply going into package A's subdirectory and doing a `conan create . <additional params>`. The user and channel did not have to be specified on the command line.

If package B depended on package A, our Git branch-based channel scheme would mean the `default_channel` property for package B would set the dependency of package A to be for that Git branch-based channel automatically. This scheme allowed us to develop on this monolithic repo as if it were a silo with no impact from other developers.

After porting a couple initial recipes (roots of the dependency tree) I see that `default_user` and `default_channel` are now being ignored. An attempt to build package A is now generating a package with reference A/1.0.0 instead of A/1.0.0@company/feature_12345.

Question: Is there still a way to automatically set the user and channel within the recipe and have it be used like in Conan 1.x?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @radonish 

Yes, the fields have been called now ``user`` and ``channel`` and they are dynamically defined if desired. Something like:

```python
class mypkgRecipe(ConanFile):
    name = "mypkg"
    version = "0.1"
    package_type = "library"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/*", "include/*"

    def set_name(self):
        self.user = "myorg"
        self.channel = "mychannel"
```
Will automatically do it (you can read the branch in ``set_name()`` to get it from git)

**Comment by AbrilRBS** [comment]
Some extra info, if this is needed in multiple recipes and the logic to select the user/channel can be shared among those, you might want to use `python_requires` ([docs here](https://docs.conan.io/2/reference/extensions/python_requires.html#reference-extensions-python-requires)) to abstract this logic away :)

**Comment by radonish** [comment]
@memsharded, using `set_name()` worked nicely to replicate what I had with my 1.x recipes - thank you!

@AbrilRBS, thank you for the tip - I will look at `python_requires`.
