### ISSUE TITLE
I have a conan package , i want in editable mode , but my repo root having .git , editable package will also .git , how to handle or overcome this issue

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#16862]
### What is your question?

I have a conan package , i want in editable mode , but my repo root having .git , editable package will also .git , how to handle or overcome this issue

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @subbaraokadali 

I am sorry, I didn't understand your issue. Having a ``.git`` in the repo is not an issue, that is the standard thing, ``editable`` mode can be perfectly used for git repos. Please try to provide more complete details and instructions about how to replicate your issue.

**Comment by ghost** [comment]
@memsharded : in my repo root i have .git , i have a conan package   "test_package" , i want to do changes using conan editable and commit the changes

**Comment by memsharded** [comment]
Still no idea what is the issue or what is failing. Please provide detailed steps, something like:

- ``conan new cmake_lib -d name=mypkg -d version=0.1``
- ``git init .`` & ``git add .`` && ``git commit ....``
- ``conan editable add .``
- ``conan create .``

Then provide the full output logs, and explain what would be the expectation, what happened, etc.

**Comment by memsharded** [comment]
I am closing this ticket as responded.
Please don't hesitate to re-open or create a new ticket with the details above to help reproduce the issue and be able to help.
Thanks very much for your feedback.
