### ISSUE TITLE
[question] arm-toolchain/13.2 not available in conan center?

### ISSUE THREAD

**Issue by Longosz** [conan-io/conan#16866]
### What is your question?

Hi, I am following the tutorial. Currently I am at https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html step where it's advised to see this example:
https://docs.conan.io/2/examples/cross_build/toolchain_packages.html#example-cross-build-toolchain-package-use
in case i don't have a proper toolchain. I tried it with:
[tool_requires]
arm-toolchain/13.2
in the profile but then error pops out:
ERROR: Package 'arm-toolchain/13.2' not resolved: Unable to find 'arm-toolchain/13.2' in remotes.

I check on conan center and it's true, i cannot find arm-toolchain. Does it mean tutorial is not aligned with conan center content and we cannot really execute this example successfully?

Thank you for your help!

Regards,
Piotr

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Longosz 

Thanks for your question.

No, the ``arm-toolchain/13.2`` package is not available in ConanCenter. 
This toolchain is available and created in the https://docs.conan.io/2/examples/cross_build/toolchain_packages.html example. If you read that from the beginning, it will explain the recipe and how the package is created from source, look for this line in that page:
```
$ conan create . -pr:b=default -pr:h=../profiles/raspberry-64 --build-require
```

The full recipe is available in the examples2 repo, as described in the first section of the page:
```
$ git clone https://github.com/conan-io/examples2.git
$ cd examples2/examples/cross_build/toolchain_packages/toolchain
```

**Comment by Longosz** [comment]
Hi @memsharded ,

Awesome, thank your help and for the clarification:)

Regards,
Piotr

**Comment by memsharded** [comment]
Happy to help! :) 

I am closing the ticket as resolved, but don't hesitate to re-open or create any new ticket for any further question. Thanks for the feedback!
