### ISSUE TITLE
[bug] Git.get_commit(..., repository=True) fails to detect when the repo is dirty **above** the conanfile

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#16873]
### Describe the bug

It seems there is a bug with how `repository=True` is handled. Testing with conan 2.5.0, we can observe that the "dirty repo" exception:

> ConanException: Repo is dirty, cannot capture url and commit: C:\Users\adn\projects\Clients\AstuteGraphics\AstuteManager\astutemanager\conan

is still not thrown when a file in the repository **above** the recipe is touched. Which is contrary to the intent of capturing the commit for the repo as a whole (and thus, being informed when such repository as a whole is not clean).

### How to reproduce it

Write a recipe in a subfolder of the repository root (e.g. `conan/conanfile.py`), making a call to the above function, or to `get_url_and_commit` e.g.:

    def export(self):
        Git(self, self.recipe_folder).get_url_and_commit(repository=True)

Then, call `conan create` for both scenarios:
* Touch `conan/conanfile.py`, or any file in the `conan`  subfolder -> the `ConanException` is thrown.
* Touch any file at the root of the repo -> the `ConanException` is not thrown.

**Comment by memsharded** [comment]
Thanks for reporting this @Adnn 

This seems a bug indeed, proposing a fix in https://github.com/conan-io/conan/pull/16892

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/16892 merged, this will be in next 2.7, thanks again for reporting
