### ISSUE TITLE
[bug] Typo in conan create call (build_packages tutorial)

### ISSUE THREAD

**Issue by Longosz** [conan-io/conan#16888]
### How to reproduce it

https://docs.conan.io/2/tutorial/creating_packages/build_packages.html
in the conan create comand, 1 extra quote character. See screenshot below:
![image](https://github.com/user-attachments/assets/1e29b374-a0c3-42f0-9078-4ad40b19dcd3)

**Comment by ErniGH** [comment]
Thanks for report this! 👍
