### ISSUE TITLE
[bug] Specifying `tools.build.linker_scripts` in my profile results in an invalid command line when linking.

### ISSUE THREAD

**Issue by photex** [conan-io/conan#16882]
### Describe the bug

I'm using Fedora 40, with conan from the develop2 branch.

While attempting to move my linker_script setup out of cmake and into my conan profile I encountered the error that the way in which the linker command was appended doesn't put a space between the previous linker arguments (if any).

### How to reproduce it

If you create a new cmake_lib and use a profile such as:

```ini
[settings]
os=baremetal
arch=tc162
compiler=gcc
compiler.version=11
compiler.cppstd=20
compiler.libcxx=libstdc++11

[conf]
tools.build:compiler_executables={"c":"tricore-elf-gcc","cpp":"tricore-elf-g++"}
tools.build:linker_scripts=[ "${PROJECT_SOURCE_DIR}/Lcf_Gnuc_Tricore_Tc.ld" ]
tools.cmake.cmake_layout:build_folder=build/tc162
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config

# I have to do this, otherwise zlib tries to use fPIC which isn't supported by tricore.
[options]
*:shared=False
*:fPIC=False
```

Then you'll get an error during the build similar to this:

```
tricore-elf-g++: error: unrecognized argument in option ‘-mtc162-T/home/chipc/.conan2/p/b/mypkg6fa17d873b59e/b/Lcf_Gnuc_Tricore_Tc.ld’
    tricore-elf-g++: note: valid arguments to ‘-mtc’ are: 13 131 16 161 162 18
```

**Comment by photex** [comment]
It's possible to work around this by using `tools.build:exelinkflags`

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/16883 for next Conan 2.7
