### ISSUE TITLE
[question] How to override an option with value `None` via cmdline

### ISSUE THREAD

**Issue by DenizThatMenace** [conan-io/conan#16896]
### What is your question?

The documentation of Conan explains that recipe options can take different pre-defined values, one of them being `None`. Consider for example:
```
options = {
    "shared": [True, False],
    "threading": [None, "OMP", "TBB"],
 }
default_options = {
    "shared": True,
    "threading": "OMP",
 }
```

The documentation further explains how to override a recipe's option default-value with another value from the command-line.
```
conan create . -o:a "*:shared=False" -o:a "*:threading=TBB"
```

However, I am now struggling.  
**I see no way, how I could set an option to its allowed value of `None`.**

----

1st attempt:
```
conan create . -o:a "*:threading=None"
```
yields the following error:
```
ERROR: 'None' is not a valid 'options.threading' value.
Possible values are [None, 'OMP', 'TBB']
```

----

2nd attempt:
```
conan create . -o:a "*:threading="
```
yields this error:
```
ERROR: '' is not a valid 'options.threading' value.
Possible values are [None, 'OMP', 'TBB']
```

----

3rd attempt:
```
conan create . -o:a "*:threading=\"\""
```
yields this error:
```
ERROR: '""' is not a valid 'options.threading' value.
Possible values are [None, 'OMP', 'TBB']
```

----

Is this at all possible?

Is that maybe a bug and the parsed string should be compared against the string `"None"` and if equal be replaced by `None` instead?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DenizThatMenace 

Thanks for your question.

The ``None`` value is a special one, you can read in https://docs.conan.io/2/reference/conanfile/attributes.html#options:

- ``None``: Allow the option to have a ``None`` value (not specified) without erroring.

So it represents the absence of value, not being assigned at all. Consequently it is not possible to assign it a value from the command line.

That looks like a model error in the recipe, it doesn't make much sense to have ``"threading": [None, "OMP", "TBB"],`` and then have a default ``threading!=None``.

**Comment by DenizThatMenace** [comment]
OK, thanks for clearing that up.

However, would a situation be possible, where package `A` has this option and it defaults to `threading==None`, but that option gets overridden by another package `B` (which has package `A` as a dependency) with `threading==OMP`, but I again want to override that again (via cmdline) with `threading==None`!?

If such a situation is possible, then the only solution would be to use another string (e.g. `"Sequential"`) instead of `None` as indicator for package `A` to not use "threading" support. Is that correct?

**Comment by memsharded** [comment]
> If such a situation is possible, then the only solution would be to use another string (e.g. "Sequential") instead of None as indicator for package A to not use "threading" support. Is that correct?

Yes, exactly, ``None`` is special case, if you want a regular value that can always be overriden, it should be a regular string.
A different story is that in general, specifying different options for dependencies from recipes should be minimized as much as possible, using always the default, and leave customization of options to ``profiles``.

**Comment by DenizThatMenace** [comment]
Thank you. This helps.

So, I will remove the `None` and replace it with a `"Sequential"`.
