### ISSUE TITLE
[question] How to set [conf] items from a conanfile.py?

### ISSUE THREAD

**Issue by DevAGCO** [conan-io/conan#16908]
### What is your question?

Our goal is to set the tools.system.package_manager:mode config from docker.
One idea would be to manually create a global.conf file, but that feels hacky.

Doing this from the conanfile.txt works as expected :
```
[conf]
tools.system.package_manager:mode=install
```
But to do that from a conanfile.py, using the following syntax doesn't work:
```
def configure(self):
    self.conf.define("tools.system.package_manager:mode", "install")
```

What's the proper way to achieve this?
It has to be noted that we are using cmake-conan to invoke conan:
`cmake ... -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake`

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DevAGCO 

Thanks for your question.

> Doing this from the conanfile.txt works as expected :

I am afraid this is not correct. That works only from a profile file, not from a ``conanfile.txt``.

In both scenarios the approach is the same, define it in the profile and pass the profile, it doesn't matter if it is a ``conanfile.txt`` or ``conanfile.py``.
Alternatively you can also call it directly in the command line, like ``-c tools.system.package_manager:mode=install``, but it is usually more convenient to put it in the profile.

**Comment by DevAGCO** [comment]
Hi @memsharded 

Thanks for the lightning-fast reply! 
Apologies for the confusion. Yes that's right. I made it work with having it in the profile not in the conanfile.txt.

So this syntax is not valid at all?
```
def configure(self):
    self.conf.define("tools.system.package_manager:mode", "install")
```

**Comment by memsharded** [comment]
Yes, it is not possible to define ``conf`` items from conanfiles to their dependencies.
There are many reasons, but a important one is that they easily generate conflicts, with different conanfiles in the graph requesting different values. Another reason is that it is not nice to have that behavior without explicitly defining from users, this ``mode=install`` is a very good example: recipes cannot decide by themselves to install system packages without user approval. This is a design principle in Conan, it will not modify your system without user being explicitly aware (profiles/command line are defined by user, while recipes can be defined by others).

The ``conf`` is a configuration item, only from profiles and command line, not recipes. Similar to ``settings``, they cannot be defined /written in conanfiles, only read.

**Comment by DevAGCO** [comment]
Makes perfect sense!
Thank you so much for your time.

**Comment by memsharded** [comment]
Happy to help, thanks for the feedback!
