### ISSUE TITLE
[question] Windows gitlab-runner [WinError 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by cancech** [conan-io/conan#16928]
### Windows gitlab-runner [WinError 183] Cannot create a file when that file already exists

I'm trying to setup a gitlab-runner pipeline, such that when it automatically creates and uploads the conan package as part of the deploy stage of the pipeline. I have it working with the following job:

```yaml
create_and_upload:
  stage: deploy
  script:
    - conan create . -j build.json -s build_type=Release
    - conan upload -r my_repo $(type build.json | jq.exe -r .installed.[0].recipe.id)
```

And this works great provided that I don't re-run the pipeline such that I don't try to "reuse" an existing build directory (i.e.: re-run a the pipeline without performing any changes). If I do that, then it fails with the following:

```
myproject/0.0.1@user/channel: Copying sources to build folder
JSON file created at 'C:\Program Files\GitLab-Runner\builds\2GoytBDF\0\myproject\build.json'
WARN: **************************************************
WARN: *** Conan 1 is legacy and on a deprecation path **
WARN: *********** Please upgrade to Conan 2 ************
WARN: **************************************************
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
ERROR: [WinError 183] Cannot create a file when that file already exists: 'C:\\Windows\\system32\\config\\systemprofile\\.conan\\data\\myproject\\0.0.1\\user\\channel\\build\\11f1c10467e5a14f82dc936b3f721f04940b2ccd'
Error copying sources to build folder
```

If I observe the build directory, then I can see that a `11f1c10467e5a14f82dc936b3f721f04940b2ccd.dirty` file is added, but nothing more happens. If I manually delete the `11f1c10467e5a14f82dc936b3f721f04940b2ccd`, then the pipeline/job successfully complete when I restart it.

In my digging I came across #4516, which looks like the same kind of issue (albeit in a docker environment, which I'm not using), however from what I can tell the gitlab-runner already adds the appropriate parameters. Per the gitlab documentation  it should be running powershell with:

```
powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command generated-windows-powershell.ps1
```

where the `generated-windows-powershell.ps1` is derived from the job `yaml`.

I'm not sure what to do/try from here. The only thing that I can think of would be to force a cleanup of the build directory at the conclusion of the job, however I don't see the build directory listed anywhere in the generated `build.json` and my attempt to use `conan remove` doesn't do anything...

```yaml
create_and_upload:
  stage: deploy
  script:
    - conan create . -j build.json -s build_type=Release
    - conan upload -r my_repo $(type build.json | jq.exe -r .installed.[0].recipe.id)
    - conan remove $(type build.json | jq.exe -r .installed.[0].recipe.id) --builds --force
```

Any thoughts on this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cancech 

Thanks for your question.

I am not sure what is happening, it seems something very specific to the Gitlab runner users and permissions, like if the second run used some other user that doesn't have overwrite permissions for those folders. Does this happen for every package, or just for just one specific one?

> 'm not sure what to do/try from here. The only thing that I can think of would be to force a cleanup of the build directory at the conclusion of the job, however I don't see the build directory listed anywhere in the generated build.json and my attempt to use conan remove doesn't do anything...

Not sure either why the ``conan remove`` is not removing the package, but personally, it seems quite a workaround, I think I'd still try to investigate first why it is not possible to overwrite that folder in the cache. Unfortunately, I don't have expertise in Gitlab runners, but knowing if this is specific to one package or happens always to all packages might give some hints.

**Comment by cancech** [comment]
Thanks for the quick response!

Unfortunately this is the only package that I currently have that needs compilation. The other two packages are "just" collections of scripts, and those work fine (however they bypass this part by not needing to be compiled).

Doing some more digging I figured out how to change the account under which the `gitlab-runner` executes, and by switching it to a "real" account from the `Local System` it was configured for fixed everything. Now it can properly overwrite the build directory without complaints and even the `conan remove` is working now. I still need to play around with it some more (i.e.: the account that's currently working is a administrator account, which is less than ideal), but at least I have a way forward. Unclear as to why `Local System` doesn't work (it can create the files, but not overwrite?), but c'est la vie.

Some question about `conan remove`: 

* If I were to run this after the package is created and uploaded, would it be the equivalent of performing a `clean`?
* I've noticed that it's been deleting not only the nested directory in which the build is performed (i.e.: `build/abc123`), but also the root `build` directory. Is the root `build` directory removed when the last nested directory is removed, or is this command deleting everything?
 
I'm tempted to leave that step in to ensure as much of a clean slate between jobs/pipelines as possible, but don't want to "overstep". As-in, I would want it to only delete the one specific nest build directory for whichever exact revision (down to the Release/Debug) I specify and not all. As is I would be running it as:

`conan remove myproject/0.0.1@user/channel#609804e4d64f246a991a6a3a3acb3a9e --builds --force`

so would this delete only `builds\5e71a64a5cfa3635256ea63c1944b753e8d3d886` (assuming that that's the build directory of 609804e4d64f246a991a6a3a3acb3a9e)?

**Comment by cancech** [comment]
Through some experimentation I was able to answer at least one of my questions. Running 

`conan remove myproject/0.0.1@user/channel#609804e4d64f246a991a6a3a3acb3a9e --builds --force`

does in fact delete the entire `build` directory and not just the nested `builds\5e71a64a5cfa3635256ea63c1944b753e8d3d886`. Given that the argument is `--builds` I expect that this is by design. Would there be a way to tell it to only delete the specific build of the exact revision I reference, or a means of determining which build directory the revision employs? I know that it prints it into the command line output, but the generated `build.json` doesn't include it and I can't think of where else to look for it.

**Comment by memsharded** [comment]
> Unfortunately this is the only package that I currently have that needs compilation. The other two packages are "just" collections of scripts, and those work fine (however they bypass this part by not needing to be compiled).

A possibility would be that the contents of the folder, being application, executables, etc, get some different user permissions as regular scripts or text files, and those make the folder to raise such an error.

> Doing some more digging I figured out how to change the account under which the gitlab-runner executes, and by switching it to a "real" account from the Local System it was configured for fixed everything. Now it can properly overwrite the build directory without complaints and even the conan remove is working now. I still need to play around with it some more (i.e.: the account that's currently working is a administrator account, which is less than ideal)

This aligns with our experience. Running as admin/root can be typically problematic, and things work way more smoothly with regular non-privileged users.  For some reason, the permissions of files and folders on disk when created by admin/roots do not overwrite nicely when running in different "sessions" of the CI runner. We generally recommend to run as a non-privileged user, not only for this reason, but also and more importantly because of security. Running as admin is "overkill", Conan doesn't need admin permissions to run, and it is always a big liability to run and build under admin users.

> If I were to run this after the package is created and uploaded, would it be the equivalent of performing a clean?

Not really, the ``conan remove`` removes the recipe and package binary, and as a side effect, it will also remove temporary files like build folders. On the other hand ``clean`` is designed to remove only temporary files and folders, but not the recipe or package artifacts.

> I've noticed that it's been deleting not only the nested directory in which the build is performed (i.e.: build/abc123), but also the root build directory. Is the root build directory removed when the last nested directory is removed, or is this command deleting everything?

yes, the ``remove`` includes the "clean" of the build folder

> conan remove myproject/0.0.1@user/channel#609804e4d64f246a991a6a3a3acb3a9e --builds --force

The thing is that in Conan 1.X, the cache is able to host only 1 revision at a time. So it really doesn't matter what revision you use there, maybe except to do some extra checking. But revisions in the Conan 1.X cache evict to each other when they are installed.

> does in fact delete the entire build directory and not just the nested builds\5e71a64a5cfa3635256ea63c1944b753e8d3d886. Given that the argument is --builds I expect that this is by design. Would there be a way to tell it to only delete the specific build of the exact revision I reference, or a means of determining which build directory the revision employs? I know that it prints it into the command line output, but the generated build.json doesn't include it and I can't think of where else to look for it.

The ``--builds`` can receive the "package-id"/"build-id" argument of the build to remove, so something like:
```
conan remove myproject/0.0.1@user/channel --builds=<package_id> --force
```
should remove only that build (sorry if not, I am rusty with Conan 1 commands, Conan 2 is already 19 months old, and the recommended version for production, Conan 1.X is legacy as you can see in the output logs and warnings.

**Comment by cancech** [comment]
Thanks for the information!

**Comment by memsharded** [comment]
Thanks to you for the feedback!

**Comment by cancech** [comment]
So, switching to a different user was not the ultimate solution. It worked briefly, but then I started seeing the exact same behavior. Or more specifically `Release` builds would fail in the same way while `Debug` builds would success. So I started digging and went down the rabbit hole, and what I've figured out is:

* `PowerShell` is the only shell that `GitLab` support for runners on Windows
* `PowerShell` has a 256 character limit on paths (Note: I've seen 248 - 260 quoted as the limit, but 256 feels like the right number)
* Hence if any file within the relative path exceeds 256 characters (with the file name/extension included) it fails to delete
* Originally the `Conan` home directory (`C:\\Windows\\system32\\config\\systemprofile`) was appearing in a location such that this limit was always reached (hence why it never worked)
* When running as the user the two extra characters (Release vs Debug) is enough to push one file over the 256 character limit (which is why Debug works but Release fails)

I'm not sure if I would call this a `Conan` issue per say, as this is 100% a `PowerShell` limitation that `Conan` has forced upon it. That been said, I've managed to put together a work around that seems to work for my needs by forcefully cleaning up the build directory after the completion of the job. Namely:

```yaml
create_and_upload:
  stage: deploy
  script:
    - conan create . -j build.json -s build_type=Release
    - conan upload -r my_repo $(type build.json | jq.exe -r .installed.[0].recipe.id)
  after_script:
    - rm -r -force -path "\\?\$HOME\.conan\data\$(type build.json | jq -r .installed.[0].recipe.name)\$(type build.json | jq -r .installed.[0].recipe.version)\$(type build.json | jq -r .installed.[0].recipe.user)\$(type build.json | jq -r .installed.[0].recipe.channel)\build\*"
```

This will delete everything in the `build` directory, as I see no way to distinguish which exact subdirectory has finished. The `build.json` only references the `Package ID` and I see no way to derive the `Build ID` from it. The `\\?\` at the start of the path is ***MANDATORY***. I've no clue what it does or why, but that somehow allows the deletion of files past the 256 character limit.

**Comment by memsharded** [comment]
Thanks for the information.

> C:\\Windows\\system32\\config\\systemprofile

In my opinion it is less than great that Conan builds are happening inside ``C:/Windows/system32``, not to say sound a bad idea.
Conan doesn't need admin/root permissions for anything, and it should be using the least possible privileges, including which folders it is using. I think a possible trivial approach which also looks better than that is doing the builds (defining the Conan cache with CONAN_USER_HOME env-var) in somewhere like ``C:/.conan2``. And then the path limits will be fine.

Also, this most likely will not be an issue with Conan2, as the Conan cache in Conan 2 uses way shorter paths in all cases.

**Comment by cancech** [comment]
Ok, thanks for the information! I'll look into moving the CONAN_USER_HOME to the root of the drive for the time being, until I'm able to upgrade to Conan 2 in the future.

**Comment by memsharded** [comment]
Great, thanks for the feedback.

Please try to make moving to Conan 2 a priority, it is not that we will remove it from PyPI, but for example packages in ConanCenter will soon stop to receive updates from new pull requests. It will not break, but it will no longer be updated.

Don't hesitate to open new tickets for any further question you might have. Thanks!
