### ISSUE TITLE
[question] Collecting licenses

### ISSUE THREAD

**Issue by Einsied** [conan-io/conan#16923]
### What is your question?

Hello people,
I am currently integrating conan-packages into a larger industrial project.
As usual the customer is not supposed to get access to the source-code.
So I have to manually satisfy the license requirements.

What I am currently attempt to do is to iterate over the different dependencies and to extract the licenses.
Like demonstrated in the following function:
```python
def recursive_license_search(package) -> tuple:
    '''
    @brief Recursively searches for license files in the dependencies of a package.
    @param package The package to search for licenses.
    @return A tuple containing the name of the dependency, its SPDX-identifier and either a tuple like this.
    '''
    # Some dependencies do have multiple licenses.
    # In this case we will use the most permissive one, we find, so here is an ordered list with the preferred licenses.
    preferred_licenses = [
        "MIT", "BSD-3-Clause", 
        "Apache-2.0", 
        "LGPL-3.0", "LGPL-3.0-or-later",
        "LGPL-2.1", "LGPL-2.1-or-later"
    ]
    sub_dependencies = list()
    for dependency in package.dependencies.items():
        _, dependency_package = dependency
        sub_dependencies.append(recursive_license_search(dependency_package))
    sub_dependencies = tuple(sub_dependencies)
    license_identifier = package.license
    if isinstance(license_identifier, tuple):
        for license_candidate in license_identifier:
            if license_candidate in preferred_licenses:
                license_identifier = license_candidate
                break
    return (str(package.ref).split("/")[0], license_identifier, sub_dependencies)
```

I now struggle with deciding if a license needs to be included, because I am not aware if a package will link against it or not.
So let us take `Qt6.7.1` as a (not so minimal) example.

```python
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps
from conan.tools.files import copy
import pathlib

class ExampleProject(ConanFile):
    name = "Example"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    package_type = "application"

    def requirements(self):
        self.requires("qt/6.7.1", options={"shared":True})
        self.test_requires("gtest/1.15.0")

    def generate(self):
        tool_chain = CMakeToolchain(self)
        tool_chain.generate()
        dependencies = CMakeDeps(self)
        dependencies.generate()
        qt6 = self.dependencies["qt"]
        copy(self, "*.dll", qt6.cpp_info.bindir, self.build_folder + "/bin")
        spdx_licenses = dict()
        for license_file in (pathlib.Path(self.source_folder) / "spdx_licenses").iterdir():
            license_name = license_file.stem
            spdx_licenses[license_name] = potential_license_file
        qt6_tree = recursive_license_search(qt6)
        gtest = self.dependencies["gtest"]
        gtest_tree = recursive_license_search(gtest)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

This file will include packages like "strawberryperl", "automake" and "m4".
From my understanding these are build_tools, that the packages use during the build,
but their code is not included into the produced binaries.
Therefore I do not add the license-files to my list.

So what I am searching is a `is_not_included()` property,
that tells me the package is not relevant for licensing issues.
I assume such a feature exists but I could not find it in the documentation,
could you please link or provide sample code?

If the feature does not exist, we should keep in mind that some licenses are intended to be infectious.
So if one package statically links against a non-permissive copy-left-license like the GPL-3,
it can itself not be used like a MIT-License package.
This is obscured in the current license look-up process I believe,
increasing the risk of copyright violations.

Cheers and good display
Einsied

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Einsied 

Thanks for your question.

> This file will include packages like "strawberryperl", "automake" and "m4".

I was surprised by this too, there are sometimes that packages like ``automake`` or ``m4`` are not in the "build" context as tools, but in the "host" context as potential libraries, because they are requirements of ``libtool``, which happens to be used as a library sometimes too, and it has regular ``requires`` to these other packages. A bit confusing, we will probably try to iterate this and improve if possible in ConanCenter recipes, but just for your awareness.

I think there could be 2 different approaches:

- Let each package gather its own dependencies license and re-package them, according to its own logic. This way, each package would only have to gather licenses from its immediate dependencies, and things will work recursively.
- Let each package gather is own subgraph of dependencies, including transitive ones.

In both cases, the key would be to use the dependencies traits to decide what is having linkage and what not, see https://docs.conan.io/2/reference/conanfile/methods/generate.html#iterating-dependencies

In the same way that ``require.direct`` or ``require.build`` are used in those docs, you can use the other traits, like ``require.headers`` and ``require.libs`` to see if the requirement is bringing code and libraries or not.

Also consider that some cases are a mixture of the 2 above approaches, like if using a shared library that embeds a bunch of static libraries, this shared library will not propagate to its consumers the ``require.headers`` and ``require.libs``, because consumers will not have linkage requirements. So the ``shared`` library should re-package the license (depending on the license "linkage" conditions) of its dependencies, so the final application using the ``shared`` library will use the static libraries licenses indirectly.


Please let me know if this helps.

Side hint: for "orthogonal" or "reusing" code functionality, recall that there are some Conan mechanisms that might help:
- ``python_requires`` to re-use common Python code in different recipes
- Conan "hooks" to automatically execute extra code while building or packaging packages.

**Comment by Einsied** [comment]
Hello @memsharded ,
yes your information helped a lot.
I will later send an updated version of my recursive function here,
so other people can use it.

> I think there could be 2 different approaches:
>
> - Let each package gather its own dependencies license and re-package them according to its own logic. This way, each package would only have to gather licenses from its immediate dependencies, and things will work recursively.
>
> - Let each package gather is own subgraph of dependencies, including transitive ones.

I think the recursive approach is better, because licensing may depend on package configuration (e.g. options, target-operating system).
So a license might only be transitive if the package is built with option A.
This can also done in the subgraph but then the requires have to be changed to.

We could also argue that the package as a whole is one entity and it can only be used as whole. So it needs to be licensed as a whole. This is appealing if the package contains one compiled artifact (".so", ".dll", ".lib").
On the other hand "qt" has a lot of different artifacts, which could be licensed independently, but the subgraph will not solve this problem either.

> In both cases, the key would be to use the dependencies traits to decide what is having linkage and what not, see https://docs.conan.io/2/reference/conanfile/methods/generate.html#iterating-dependencies
>
> In the same way that require.direct or require.build are used in those docs, you can use the other traits, like require.headers and require.libs to see if the requirement is bringing code and libraries or not.

Yes that was the missing piece of information I think I can build the function now. Essentially the `inherit_license` trait will be:
```python
inherit_license = require.headers or require.libs or require.run
```

Greetings
Einsied

**Comment by memsharded** [comment]
> I think the recursive approach is better, because licensing may depend on package configuration (e.g. options, target-operating system).
So a license might only be transitive if the package is built with option A.

Sounds good

> We could also argue that the package as a whole is one entity and it can only be used as whole. So it needs to be licensed as a whole. This is appealing if the package contains one compiled artifact (".so", ".dll", ".lib").
On the other hand "qt" has a lot of different artifacts, which could be licensed independently, but the subgraph will not solve this problem either.

Just in case you didn't see it, I think the "vendoring packages" feature could be related to some of your use cases: https://blog.conan.io/2024/07/09/Introducing-vendoring-packages.html

Thanks for your feedback!

**Comment by Einsied** [comment]
Here is the final version of the recursive function:
```python
def recursive_license_search(package) -> tuple:
    '''
    @brief Recursively searches for license files in the dependencies of a package.
    @param package The package to search for licenses.
    @return A tuple containing the name of the dependency, its SPDX-identifier and either a tuple like this.
    '''
    # Some dependencies do have multiple licenses.
    # In this case we will use the most permissive one, we find, so here is an ordered list with the preferred licenses.
    # This list is not complete and should be adjusted depending on the project.
    preferred_licenses = [
        "MIT", "BSD-3-Clause",
        "Apache-2.0", 
        "LGPL-3.0", "LGPL-3.0-or-later",
        "LGPL-2.1", "LGPL-2.1-or-later"
    ]
    sub_dependencies = list()
    for require, dependency in package.dependencies.items():
        # It does not matter if we include a static or dynamic library, both will be included via a header, if we use C++.
        # So if we now walk along the direct dependencies an collect everything requiring headers,
        # we should get all code that is included in the final project and usually packaged.
        # It is of course possible that someone decided to ship host their code as a zip that unpacks into headers files
        # and therefore does not require headers. In this case we would miss the license.
        # So a look into the dependency-graph is still necessary.
        if require.direct and require.headers:
            sub_dependencies.append(recursive_license_search(dependency))
    sub_dependencies = tuple(sub_dependencies)
    license_identifier = package.license
    if isinstance(license_identifier, tuple):
        for license_candidate in license_identifier:
            if license_candidate in preferred_licenses:
                license_identifier = license_candidate
                break
    return (str(package.ref).split("/")[0], license_identifier, sub_dependencies)
```

`inherit_license = require.headers or require.libs or require.run` was condensed down to `require.headers`, because the build-tools are required to run.
A case in which only the libs are required is possible, but did not appear in my project.
In this case the headers would be supplied from something else. Something that has an identical API. This something will be a different version of the included package and share its license in most cases. So it seems good enough.

My problem is solved now and I hope this snippet is useful for someone else.

@memsharded thanks for the tip about vendoring. I did not see it, but now I see the potential for distributing applications that should work in concert.

**Comment by memsharded** [comment]
Thanks very much for the feedback and sharing your solution @Einsied 

I think the ticket can be closed now as solved.

Don't hesitate to create new tickets for any further question, about vendoring, or any other issue you might have. Thanks!

**Comment by macdew** [comment]
I appreciate that this issue is closed, but I would be cautious about the recursive approach.  OpenSSL, for instance, uses GPL licensed perl modules as part of its build process.  And thus it includes (recursively), a GPL license.

But you do not want, under any circumstances, to associate this build tool license with the actual distribution of OpenSSL.  I would therefore be very careful about "inherited" licenses that are not in any way differentiated from the actual run-time licenses!  (tool_license vs license?)

**Comment by memsharded** [comment]
> I appreciate that this issue is closed, but I would be cautious about the recursive approach. OpenSSL, for instance, uses GPL licensed perl modules as part of its build process. And thus it includes (recursively), a GPL license.

Yes, this is why in general you want to iterate only the ``self.dependencies.host`` or filter by ``not require.build`` to only bring "linked" dependencies and not tools. There are still users that might want to collect all licenses, even the ones of the tools involved, not for distribution, but for compliance or other internal reasons. This is why a built-in license collector is difficult, and the recommendation is go via ``deployers`` or other similar user-defined implementations.
