### ISSUE TITLE
[bug] CMakeDeps generator links visible=False dependencies publicly

### ISSUE THREAD

**Issue by hugo-luccarini-tfs** [conan-io/conan#16939]
### Describe the bug

From my understanding, the `visible` trait affects the visibility of C++ artifacts / executables.

In a project `HelloWorld`, I specify a requirement like follows:
```
    def requirements(self):
        self.requires("zlib/1.3.1", visible=False),
```

On the consuming package, after conan install, inside `HelloWorld-Target-debug.cmake` I found the following generated code:
```
set_property(TARGET HelloWorld_DEPS_TARGET
             PROPERTY INTERFACE_LINK_LIBRARIES
             $<$<CONFIG:Debug>:${HelloWorld_FRAMEWORKS_FOUND_DEBUG}>
             $<$<CONFIG:Debug>:${HelloWorld_SYSTEM_LIBS_DEBUG}>
             $<$<CONFIG:Debug>:ZLIB::ZLIB>
             APPEND)
```

If I understood correctly, zlib is not linked privately, therefore, `visible=False` in this case is not doing anything.

Conan version: 1.65.0

**Comment by memsharded** [comment]
Thanks for your feedback @hugo-luccarini 

> From my understanding, the visible trait affects the visibility of C++ artifacts / executables.

Not really, the ``visible`` trait is about the propagation of the package, even if it doesn't contain any artifacts, so two packages in the same subgraph with ``visible=True`` will conflict if they have different versions, for the same package name.


> Conan version: 1.65.0

I think that is the issue, traits is a Conan 2 feature, the ``visible`` trait only does something in Conan 2. In Conan 1.X traits are ignored, they are allowed to have a common recipe syntax that doesn't fail in Conan 1.X.

**Comment by memsharded** [comment]
> self.requires("zlib/1.3.1", visible=False),

To clarify, this is something that it should typically be unnecessary in Conan 2, as Conan 2 already manages good propagation of artifacts and avoid overlinking by default, so it only should be done in very exceptional cases when desiring to have 2 different versions of the same package in the same dependency graph and hidden behind executable artifacts like shared libraries (fully embedded and private implementation detail of the shared library)

**Comment by hugo-luccarini-tfs** [comment]
@memsharded Ok understood, thanks for the quick response.
