### ISSUE TITLE
[bug] conan_api.cache_folder contains path not to cache folder

### ISSUE THREAD

**Issue by lo1ol** [conan-io/conan#16940]
### Describe the bug

Hi!

I noticed, that in my custom command `conan_api.cache_folder` returns `'/home/user/.conan2'`. But In `global.conf` it set to another folder: "core.cache:storage_path=/conan/some_folder". 

Is it Ok?

### How to reproduce it

Add custom command:

```python
from conan.cli.command import conan_command

try:
    from conan.cli.formatters.graph import format_graph_json as formater
except ImportError:
    # Old versions of conan uses this formatter,
    # but in new ones it's replaced by format_graph_json
    from conan.cli.commands.export_pkg import json_install as formater

@conan_command(group="Custom commands", formatters={"json": formater})
def print_cache(conan_api, parser, *args):
    print(conan_api.cache_folder)
```

```bash
CONAN_HOME=$(conan config home)
echo "core.cache:storage_path=/conan/some_dir" >> "$CONAN_HOME/global.conf";
conan print_cache
```

**Comment by memsharded** [comment]
Hi @lo1ol 

There are 2 different concepts here:

- The Conan home or cache folder, which is the one configured in CONAN_HOME, reported in `conan config home`
- The Conan package storage. By default it is in ``<conan_home>/p`` (note the ``p``) folder, which is the one containing the actual package recipes and binaries.

The ``core.cache:storage_path`` conf changes the second one, the package storage, but not the Conan home/cache folder.

**Comment by lo1ol** [comment]
ok. So what is the proper way for getting package storage path? Something like this?

```python
        config = ConfigAPI.load_config(conan_api.home_folder)
        cache_folder = config.get("core.cache:storage_path")

        if cache_folder is None:
            cache_folder = os.path.join(conan_api.home_folder,"p")

```

**Comment by memsharded** [comment]
The subapis shouldn't be instantiated, you should always use the object from the ``conan_api``:
```python
conan_api.sub_api.method()
conan_api.config.get(...)
```

Still your code above is not correct, the ``cache_folder`` will point in the second case (if storage_path is not defined) to the Conan home, while if ``storage_path`` is defined, it will return the "package storage", which is a different folder. 

Also, some guidelines about the cache and package storage:
- the Conan cache folders are read-only for users. They should only be managed through the Conan API, recipes, hooks, etc, but not modified directly
- The recommended way to access (read-only) packages location is through the ``conan cache path``

Not sure what you are aiming to do with the "storage_path" folder, but please note that everything there is an internal implementation detail (can change at any time in any future Conan version), and shouldn't be modified externally, that could be undefined behavior and fail in unexpected ways.

**Comment by lo1ol** [comment]
> Not sure what you are aiming to do with the "storage_path" folder

We have several docker containers that could build project in parallel. All of them started on the same machine. Containers has the cache drive, that mounted to `/conan_cache` folder. We want to sync access to it via flock. 

So, this flock has to be located in common space too.

I got your idea that this folder is read-only. I think,  we will start to keep cache in  `/conan/cache` folder and will create lock file in `/conan` folder
