### ISSUE TITLE
[feature] make full use of cmake install information with cmake-file-api

### ISSUE THREAD

**Issue by TsXor** [conan-io/conan#16944]
### What is your suggestion?

# Background
## CMake can generate package files on its own
- `install(TARGETS)` and `install(EXPORT)`
  Command [`install(TARGETS)`](https://cmake.org/cmake/help/latest/command/install.html#targets) have an `EXPORT` option that can associate installed targets to an "export group", which can be installed with command [`install(EXPORT)`](https://cmake.org/cmake/help/latest/command/install.html#export). This process generates and installs a CMake file containing code to import targets from the installation tree into another project.
- `CMakePackageConfigHelpers`
  [`CMakePackageConfigHelpers`](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html) provides helpers for generating config files. `configure_package_config_file` can fill in a template to make `<name>-config.cmake` and `write_basic_package_version_file` can make `<name>-version.cmake` from project version.

With these said, CMake projects can and should customize their package config file to apply custom logics. Therefore, users consuming these projects should also use these config files directly so that these custom logics can work.
However, current recommended way of conan is to populate `self.cpp_info` in conanfiles so that `CMakeDeps` can generate package config files again and left stock package config file unused.

## Some relevant `CppInfo` property affecting `CMakeDeps`
- `cmake_find_mode`
  When this is set to `'none'`, `CMakeDeps` will not generate package config files. This is documented to be used to create a system wrapper.
- `builddirs`
  This property will populate `CMAKE_MODULE_PATH` in generated toolchain file.

According to [Disable CMakeDeps For Installed CMake configuration files](https://docs.conan.io/2/reference/tools/cmake/cmakedeps.html#disable-cmakedeps-for-installed-cmake-configuration-files), we can simply use stock package config file with following code in our conanfile:
```python
def package_info(self):
    self.cpp_info.set_property("cmake_find_mode", "none") # Do NOT generate any files
    self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "foo"))
```
Yet this is not the recommended way. I didn't find exact reason but I guess this is because conan is a generic solution and forwarding config job to stock package config file makes solution tied to CMake. That is not good, so not recommended.
However, using the recommended way causes us to repeat ourselves just for conan. Also, config files generated with `CMakeDeps` is not as exact as stock ones, for example #12654 .
Is it possible to use stock package config files while letting conan conveniently get generic `CppInfo`?

## Target information can be retrieved via `cmake-file-api`
[cmake-file-api](https://cmake.org/cmake/help/v3.30/manual/cmake-file-api.7.html) is available since 3.14 and can provide information of current CMake build. Some information are relevant to `install` commands mentioned above.
- `codemodel->configurations->directories->installers`
  Under this path of keys are install rules of a directory.

We can retrieve information of installed and exported targets via `cmake-file-api`. Detailed information like filenames are also available. With that, we can write exporting logic in CMake way and let conan automatically read exported targets and populate `CppInfo` of conanfiles so that we get convenience while not tied to CMake.

# Proposal
Note: property names mentioned here are exposition-only. You can choose more proper names from them. Also, this is just a hint of how this can be implemented.
- Add more parameters to `CMakeToolchain::generate` to control content of query files for `cmake-file-api`.
- Add a utility function to `conan.tools.cmake` for populating `cppinfo` with information provided from `cmake-file-api`. This should be used in `package_info` phase.
- Document how to use these features.

I'm willing to implement these if they don't conflict with current conan design and are proper.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your suggestion @TsXor 

Using the CMake File API is something that we already tried, see the code in Conan 1: https://github.com/conan-io/conan/blob/8a0bca67155f551cea47c688ed40fb741186f338/conan/tools/cmake/file_api.py#L9

There were several problems that made this effort not successful, for example, the extracted information was not always complete, so it was still necessary to complete the information in the ``package_info()`` method, making it very confusing, as it is not very evident what information is missing and how to add it. 

Furthermore, it seems that File API didn't get enough attention from users, so it is not improving substantially over time.

So we decided to remove it in Conan 2, and we are not considering to add it back.

Instead, what we are doing is working in the C++ Ecosystem Evolution group (together with people from other orgs, including CMake, Msft, Bloomberg, etc), in the Common Package Specification CPS standardization effort. We started with a talk in CppCon 2023, and we are following up with the efforts this year too: https://cppcon2024.sched.com/event/1gZew/common-package-specification-cps-in-practice-a-full-round-trip-implementation-in-conan-c-package-manager. This talk will use recently merged feature in CMake master branch (not released yet) that allows to generate CPS files from a CMake build.

This has been our efforts in this line, and it will continue to be for the future. But we will not consider to bring back the CMake File API again in Conan 2. Thanks very much for the suggestion anyway!

**Comment by TsXor** [comment]
> Using the CMake File API is something that we already tried, see the code in Conan 1:
 
Thanks for that information! I didn't find that as it is not in document ;)

> This talk will use recently merged feature in CMake master branch (not released yet) that allows to generate CPS files from a CMake build.

Glad this is happening. I'll sit back and wait delightfully 😋

**Comment by jdoubleu** [comment]
> Instead, what we are doing is working in the C++ Ecosystem Evolution group [..]

Any updates on this approach? What's the current status? Are there more information regarding the implementation in Conan? Are contributions welcomed?

> This talk will use recently merged feature in CMake master branch (not released yet) that allows to generate CPS files from a CMake build.

By now, this should be broadly available in CMake, right?

**Comment by memsharded** [comment]
Yes, Conan support CPS now.

I recommend watching CppCon and using std::cpp conference talks, for example https://docs.conan.io/2/knowledge/videos.html#an-introduction-to-the-common-package-specification-cps-for-c-and-c-diego-rodriguez-losada

Of course, testing, feedback and contributions very welcome.
Note that the main generator for CPS is ``CMakeConfigDeps``, not ``CMakeDeps``. Thanks!
