### ISSUE TITLE
replace_in_file warning

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1694]
Sometimes, because a bad find pattern or because the origin file has changed in a new version, the replace in file is not replacing anything, and maybe could be an option to raise if it happens. My use case is: I'm trying to update to libpng 1.6.32, and patching the CMakeLists.txt file:

```
 tools.replace_in_file("CMakeLists.txt", "cmake_minimum_required(VERSION 2.8)", conan_magic_lines)
```

But this searched version is not there anymore, because now libpng requires 3.0.2. The symptom is that zlib (dependency) is not found, and it's very hard to debug. 

So, replace in file, maybe even opt-out, could raise if nothing has been replaced? or at least to print a big WARN

**Comment by memsharded** [comment]
Yes, I would vote opt-out, as most people would like a replacement to occur
