### ISSUE TITLE
[question] Confusing behaviour of virtualenv generation in Windows

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#16945]
### What is your question?

In my local Windows image with a default profile

```
Host profile:
[settings]
arch=armv8
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=194
os=Windows
[conf]


Build profile:
[settings]
arch=armv8
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=194
os=Windows
[conf]
```

I get an unexpected `.sh` generated for a simple test case using a dummy dependency `dep`

1) If I run `conan install --requires=dep/1.0`, I get a `conanbuild.bat` and a `conanrun.bat` file
2) If I run `conan install .` for a `conanfile.txt` that only has the requirement to dep, I also get the expected `conanbuid.bat` and `conanrun.bat` launchers
3) BUT, running that same `conan install .` for a `conanfile.py`, gets me a `conanbuild.bat` **but** a `conanrun.sh` file, which I don't know where it comes from!

See the following test for a repro

```py
@pytest.mark.skipif(platform.system() != "Windows", reason="Requires Windows")
def test_virtualenv_sh_windows_generation():
    tc = TestClient()
    tc.save({"dep/conanfile.py": GenConanfile("dep", "0.1"),
             "py/conanfile.py": GenConanfile().with_requires("dep/0.1"),
             "txt/conanfile.txt": "[requires]\ndep/0.1"})
    tc.run("create dep")
    # Running conan install . over the text file generates a conanrun.bat
    tc.run("install txt -of=txt")
    assert os.path.exists(os.path.join(tc.current_folder, "txt", "conanrun.bat")), f"Expected conanrun.bat not found in {os.listdir(os.path.join(tc.current_folder, 'txt'))}"
    # Running conan install --requires dep/0.1 also generates a conanrun.bat
    tc.run("install --requires=dep/0.1 -of=requires")
    assert os.path.exists(os.path.join(tc.current_folder, "requires", "conanrun.bat")), f"Expected conanrun.bat not found in {os.listdir(os.path.join(tc.current_folder, 'requires'))}"
    # Running conan install . over the python file generates a conanrun.sh, even if the same bat is expected
    tc.run("install py -of=py")
    # This fails
    assert os.path.exists(os.path.join(tc.current_folder, "py", "conanrun.bat")), f"Expected conanrun.bat not found in {os.listdir(os.path.join(tc.current_folder, 'py'))}"
```

Which locally fails with 
```
FAILED test/integration/environment/test_env.py::test_virtualenv_sh_windows_generation - AssertionError: Expected conanrun.bat not found in ['conanbuild.bat', 'conanbuildenv.bat', 'conanfile.py', 'conanrun.sh', 'conanrunenv.sh', '...
```

So my question is why this sh is being generated as a sh just for the `conanfile.py` case

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
The test can be fixed with:
```python
"py/conanfile.py": GenConanfile().with_requires("dep/0.1").with_settings("os"),
```

The generation of environment files is using ``settings.os`` to determine the platform and generate the scripts, if ``os`` is not defined, it will fall back to "Linux-like" system (kind of assuming no-OS is "baremetal", and most likely cross-compilers with be Linux-like environment).

The reason is doesn't happen in ``conanfile.txt``  or ``--requires`` consumer, is because these assume a default ``settings = "os", "arch", "compiler", "build_type"``.

**Comment by AbrilRBS** [comment]
That makes lots of sense, even if it was a bit suprising to get that, thanks for clarifying!
