### ISSUE TITLE
[bug] Override/force requirements not working with dependencies that are required and test_required somewhere in the graph

### ISSUE THREAD

**Issue by lordjaxom** [conan-io/conan#16959]
### Describe the bug

Conan 2.7.0

The problem only affects dependency resolution, so no compiler is involved in the example.

Profile (host and build)
```
[settings]
os=Windows
arch=x86_64
compiler=msvc
compiler.cppstd=20
compiler.version=193
compiler.runtime=dynamic
```

tl;dr:
The whole dependency complex that produces the error is available in code in the attached archive (see below)

We have a fairly complex dependency graph, where some core dependencies are required almost everywhere, even for testing other dependencies. This leads to our main application requiring one core dependency, while also requiring a dependency that test_requires something that requires the core dependency.

We use version ranges to always include the newest artifacts that don't break the API, while updating the range when an artifact breaks the API. Due to the fairly complex graph, updating a breaking change in a core component involves lots of repositories. Before doing that, we would like to enable developers to build the main application, which requires all other dependencies, with the breaking dependency using force=True and --build=missing, so people can check for which components source changes will be necessary.

To demonstrate I have stripped down our dependency graph to the minimum that shows the error and have adapted that graph to the versioning example (see attached file). The graph looks like this:

```
game/1.0 (main application)
	requires("matrix/[>=1.0 <2.0]")
	requires("engine/[>=1.0 <2.0]")
		requires("matrix/[>=1.0 <2.0]")
		requires("tools/[>=1.0 <2.0]")
			requires("matrix/[>=1.0 <2.0]")
		test_requires("intro/[>=1.0 <2.0]")
			requires("matrix/[>=1.0 <2.0]")
```

Now I would like to compile the main application with matrix/2.0. For that purpose I have replaced the requirement in game with the following to "see what happens" (i.e. which projects in the tree that depend on matrix need changes to compile again).

`requires("matrix/[>=2.0 <3.0]", force=True)`

This leads to the following error raised in conans/client/graph/graph.py (the error mentions matrix/1.0 instead of matrix/2.0):

`ERROR: Runtime Error: Could not process 'intro/1.0' with 'matrix/1.0'`

In the graph, intro/1.0 is a test requirement of engine/1.0 and matrix/1.0 is a requirement of intro/1.0. My assumption was that matrix/2.0 gets replaced also in the test requirement

I have tried to fix this by ignoring the runtime error in case the processed node is a test requirement. That makes the runtime error disappear, but in the end matrix/1.0 is installed instead of matrix/2.0 (so the forced requirement is ignored in the end).

You can see the line in graph.py that I changed in the ci_test_example.py script. 

### How to reproduce it

Unpack the attached archive and run ci_test_example.py from the root folder. The archive contains recipes that model the minimum of our dependencies that produces the error.

ATTENTION: The script patches conans/client/graph/graph.py in your Conan installation. The patch is immediately reverted, but I thought I should point this out.

[conan_bugreport.tar.gz](https://github.com/user-attachments/files/16931802/conan_bugreport.tar.gz)

**Comment by memsharded** [comment]
Hi @lordjaxom 

Thanks for your report.

> In the graph, intro/1.0 is a test requirement of engine/1.0 and matrix/1.0 is a requirement of intro/1.0. My assumption was that matrix/2.0 gets replaced also in the test requirement

``test_requires`` are private requirements, and as such they are not overriden/forced by downstream in the same way as regular ``requires``. The ``override/force`` is intended for regular ``requires``

I cannot run your code right now, but thanks for providing it, I'll try to reproduce when possible (it might take a couple of weeks).

Just a quick question, have you considered the ``[replace_requires]`` new feature instead? It seems that it can work better for your use case, and it would also be cleaner, as it doesn't require editing ``conanfiles``, and it can also be applied from the same profile to any package in the dependency graph, which can be way more convenient.

**Comment by lordjaxom** [comment]
> test_requires are private requirements, and as such they are not overriden/forced by downstream in the same way as regular requires. The override/force is intended for regular requires

That's what I figured. The problem is that the private requirement of a package down the tree prevents the regular requires from being overridden, apparently.

Since we "conan create" without tests (from our point of view the code is tested in CI/CD pipelines, and before recipe and exported sources are uploaded, the code has already been tested, so we don't export the test code) for us it wouldn't even matter that test_requires never get overridden.

> Just a quick question, have you considered the [replace_requires] new feature instead? It seems that it can work better for your use case, and it would also be cleaner, as it doesn't require editing conanfiles, and it can also be applied from the same profile to any package in the dependency graph, which can be way more convenient.

I know about replace_requires and we considered using it to force a certain set of third party libraries, but then abandoned it (for now). For this scenario however I guess replace_requires is the way to go, I was just hoping to spare our developers the editing of profiles. We are just introducing Conan in ~15 projects (of about 150) and the profiles are transparent to most devs. The conanfile is the first thing our devs learn, because they have to add and update dependencies there anyway.

**Comment by AbrilRBS** [comment]
Hi! Just dropping by to note that

>  I was just hoping to spare our developers the editing of profiles

Is not our recommended approach either. We recommend using the `conan config install` approach ([docs here](https://docs.conan.io/2/reference/commands/config.html#conan-config-install)), or even `conan config install-pkg` for even better reproducibility ([docs here](https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg)), so that ideally your developers would see little profile editing themselves

**Comment by lordjaxom** [comment]
>Is not our recommended approach either. We recommend using the conan config install approach ([docs here](https://docs.conan.io/2/reference/commands/config.html#conan-config-install)), or even conan config install-pkg for even better reproducibility ([docs here](https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg)), so that ideally your developers would see little profile editing themselves

That is what we do. Therefore the suggestion to use replace_requires instead of force=True forces our developers to edit profiles, which they wouldn't need to do otherwise.

As a workaround we are including an additional file from the repository in our corporate profile if it exists (like follows), that way developers can add their overrides next to conanfile.py (which is worse than inside conanfile.py, but better than editing profiles).

```
{% set conanfile_override = os.path.join(os.environ["WORKSPACE_DIR"], "conanfile.override") %}
{% if os.path.exists(conanfile_override) %}
include({{ conanfile_override }})
{% endif %}
```

**Comment by memsharded** [comment]
> I know about replace_requires and we considered using it to force a certain set of third party libraries, but then abandoned it (for now). For this scenario however I guess replace_requires is the way to go, I was just hoping to spare our developers the editing of profiles. We are just introducing Conan in ~15 projects (of about 150) and the profiles are transparent to most devs. The conanfile is the first thing our devs learn, because they have to add and update dependencies there anyway.

To clarify about the dev UX: devs do not need to modify existing profiles. As profiles compose it would be basically:
- Write a local file like "myreplaces" in the user folder or project folder with just the ``[replace_requires]`` section
- Pass that file together with the other profiles like ``-pr=default_profile -pr=myreplaces``

So it would still be a local edition, no modification of existing profiles in the cache, just editing another file rather than the current conanfile.py. The good thing is that if they are working with several conanfiles belonging to different packages of the graph, they can put the ``myreplaces`` in a common folder, and just use the same command for all of them, avoiding to have to repeat the addition of the ``override`` to every ``conanfile.py``.

**Comment by memsharded** [comment]
Also, there is something I'd like to understand better around the usage of those ``test_requires``

The ``test_requires`` were always intended to be for test libraries such as ``gtest`` or ``catch2``. What would be the purpose of your ``intro`` package and why it depends on the ``matrix`` library? The problem that it arises with this kind of dependencies is that the "tested subject" becomes also part of the "testing tool", and as such it is kind of unexpected/undesired, isn't it?

**Comment by lordjaxom** [comment]
I believe the situation is not necessarily unexpected. Test libraries might be extensive and offer lots of features, which may be built on other features.

Let's say for example GTest decides to use features from Boost. Then Boost would be a transitive dependency of a test_requires. But I also want to use Boost. Now Boost is also a direct requirement. In this case Boost would have to be the same for me and GTest.

Let's say I use a library that test_requires a GTest that uses Boost and I myself use Boost. Then I would not care what Boost version that library has used when it was built and tested, I can just use Boost in a totally different version myself. Only if that library needs to be built from source that Boost version is of interest. This is roughly the case that the example describes.

But we might not even have to construct an example. Boost also has a library Boost.Test. Suppose someone wants to test_require Boost (for Boost.Test only) and someone else would like to use and propagate Boost within the same dependency tree.

**Comment by memsharded** [comment]
> But we might not even have to construct an example. Boost also has a library Boost.Test. Suppose someone wants to test_require Boost (for Boost.Test only) and someone else would like to use and propagate Boost within the same dependency tree.

Sure, the problem comes when these dependencies are transitive dependencies.

Let me reverse the problem:

Lets say that you are creating a package ``mypkg`` that has a dependency to ``boost.test`` and is using a given version of boost, like 1.73, your project has C++ code using that specific version API, but not even depending on Boost directly or indirectly for anything else.

Now your ``mypkg`` is used by someone else ``app``, that has other dependencies like boost, direct or transitive.
Now if the ``app`` needs to solve a conflict, or just want to force another version of ``boost`` in its dependencies, then  doing a ``requires("boost/newversion", force=True)``, if that actually propagates to your ``mypkg`` and overrides it, breaking your ``mypkg`` build, the complain would be the opposite one: 

"why conan is overriding my ``test_requires``, these are my private tests, with my private code, Conan should not override my ``test_requires``"

This was actual feedback in the past, and this is why this is not a bug but ``test_requires`` are private (not affected by downstream recipes, and not affecting downstream recipes) by design, more often the ``test_requires`` are quite isolated/independent than the opposite.

In any case, I'd also like to recall what is said in the docs: see https://docs.conan.io/2/reference/conanfile/methods/requirements.html

> The force and override traits to solve conflicts are not recommended as a general versioning solution, just as a temporary workaround to solve a version conflict. Its usage should be avoided whenever possible, and updating versions or version ranges in the graph to avoid the conflicts without overrides and forces is the recommended approach.

the ``override`` and ``force`` should be just very occasional and temporary solutions.
Same for ``[replace_requires]``, but the advantage of them over recipe ``requires(override/force)``, is that they don't require changes to recipes, that change recipe-revisions and create other issues (like locality in distributed CI builds, a major challenge for CI at scale).

**Comment by lordjaxom** [comment]
I understand that this is a problem very hard to solve, when the dependency graph has to be fully resolved before deciding if anything has to be built from source. Otherwise one could just "not care" about the test dependencies as long as they don't need to be built.

Anyway, I understand the issue and also that it's not feasible to put effort into this when overriding/forcing dependencies is discouraged anyway.

Disclaimer: Unfortunately I have left the project where we established Conan over the last six months, so I'll not be able to follow up on this. Which makes me a bit sad because I love what I have learned in this time and I'd love to continue using and maybe even contributing to Conan, but I don't think I'll have the time since my new project is a completely different genre :-(

**Comment by memsharded** [comment]
Thanks very much for your feedback @lordjaxom 

>  understand that this is a problem very hard to solve, when the dependency graph has to be fully resolved before deciding if anything has to be built from source. Otherwise one could just "not care" about the test dependencies as long as they don't need to be built.

There is one idea that I have been trying to investigate, is kind of making the ``test`` dependencies more optional with some configuration, something that can be done nowadays explicitly with:
```python
def build_requirements(self):
    if not self.conf.get("tools.build:skip_tests"):
        self.test_requires("mytestreq/version")
```
Which can help in some scenarios. Still, if trying to override the upstream dependencies that might conflict and also needing to build from source, the conflict will arise again, but for running some experiments forcing new versions, it might be useful.

> Disclaimer: Unfortunately I have left the project where we established Conan over the last six months, so I'll not be able to follow up on this. Which makes me a bit sad because I love what I have learned in this time and I'd love to continue using and maybe even contributing to Conan, but I don't think I'll have the time since my new project is a completely different genre :-(

No prob, best luck in your new project, and if you ever need our help we will be here :)
