### ISSUE TITLE
[question] Ampersand in profiles supported for env?

### ISSUE THREAD

**Issue by tb-hh-si** [conan-io/conan#16955]
### What is your question?

Hi! I'm using conan 1.65.0 and want to use the ampersand syntax in a profile to refer to the package itself like this:
```
[settings]
&:compiler=cafeCC

[options]
&:strip_test_binaries=False

[env]
&:CC=cafeCC -lang-c
```
This works for the settings and options block. But in the env block the line is not applied. I have to state the name of my package instead. This works:
```
[settings]
&:compiler=cafeCC

[options]
&:strip_test_binaries=False

[env]
my_package:CC=cafeCC -lang-c
```

 Is the ampersand syntax not supported for the env block or is it a bug?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tb-hh-si 

Thanks for your report.
This is a known issue of the legacy ``[env]`` section, that is deprecated now (and fully removed in 2.X)

The new and recommended ``[buildenv]`` section does support ``&:`` syntax, I have just verified it in Conan 2 (and this should be the same in Conan 1.X with ``[buildenv]``

**Comment by tb-hh-si** [comment]
Hi!

I switched to `[buildenv]` and it generates a `conanbuildenv-release-x86_64.sh` with my environment variables set. But only when I use my package name like this:
```
[buildenv]
my_package/*:CC=cafeCC -lang-c
```

Using `&:CC=cafeCC -lang-c` with conan 1.65.0 does not work. This variable is not added to the environent-script then...

**Comment by memsharded** [comment]
> Using &:CC=cafeCC -lang-c with conan 1.65.0 does not work. This variable is not added to the environent-script then...

Thanks for the feedback.
You are right, it is true that Conan 1.X didn't fully implement the ``&`` syntax for the new ``VirtualXXXEnvs``, this seems only fully supported in Conan 2.X. Sorry for the confusion, I thought that Conan 1.X had it, but it is true that Conan 2 is already +18 months old, so I don't know all the details by heart anymore.
