### ISSUE TITLE
[bug] MakeDeps generator does not provide any info about tool_requires

### ISSUE THREAD

**Issue by cubanpit** [conan-io/conan#16950]
### Describe the bug

In [conan_bug.zip](https://github.com/user-attachments/files/16908999/conan_bug.zip) there is a simple tool_requires on cmake, then the MakeDeps generator is used but it does not produce any information about the given tool_requires.

Command:
`conan install conanfile.txt --remote conancenter -pr:a Linux_test_profile -of conanfiles`

In `conanfiles/conandeps.mk` there is no variable from the `cmake` package, which could be used for the build.

Conan version 2.6.0

**Comment by memsharded** [comment]
Hi @cubanpit 

Thanks for your report.
At the moment this is intended, ``MakeDeps`` is generating variables for include-dirs, lib-dirs, etc, that is, things in the "host" context that can be used in the build. Likewise, other generators like ``CMakeDeps`` do not generate files by default for ``tool_requires``

It is not clear what variables would be added for ``tool_requires``, and how those variables could be leveraged in the build of consumers. I guess just ``CONAN_BIN_DIRS``? How would you use that information later in the Makefile for your build?
Note that the standard built-in generators like ``VirtualBuildEnv`` are already generating scripts that put the ``tool_requires`` in the ``PATH``, ``LD_LIBRARY_PATH``, etc, so not sure what else could be done that can be used in a Makefile.

**Comment by cubanpit** [comment]
Thank you for the explanation, I think I assumed the `BIN_DIRS` variable would be there because it was there in Conan 1, and we used it in our workflow. 
We use Conan to manage the dependencies, we then use the CMake/Make generators to pass down the information to the build system, two of our dependencies are `tool_requires` that only provide a binary needed at build time.
Using the `*Env` generators would be (maybe) a cleaner solution, but I found the Make generator solution quite convenient for our use case. We currently generate the `.mk` file ourselves, which is also a good solution for such a simple use case.
If this is on purpose, I would not consider it a bug, considering how easy it is to work around it with few lines in Python.

**Comment by memsharded** [comment]
At the moment, it is on purpose, but it doesn't mean that there is no space for improvement :)

If there is any common pattern that could make sense for MakeDeps to generate files for ``tool_requires``, so they can be used by consumers more easily, then it could be added. Our question here is that this usage pattern is not very clear, so we are not even sure what files should be generated with what content. In the case of ``CMakeDeps`` this evolved to an opt-in using ``CMakeDeps.build_context_activated = []`` that allows to also generate find_packages for the build context (``tool_requires``)

If it is easy from your side to make it work, then great, if you think there is something that could be built-in and be general enough for other users (important, it shouldn't break existing usage), then please re-open and let us know. Thanks for the feedback!
