### ISSUE TITLE
Conan error 'Could not connect to local cache' in fresh install version 0.25.1 in Windows

### ISSUE THREAD

**Issue by jngd** [conan-io/conan#1695]
After fresh install when I type conan in my Window machine I get the following trace:

`C:\Users\jngd>conan                                                                                               Traceback (most recent call last):                                                                                        File "conan\conans\conan.py", line 10, in <module>                                                                      File "conan\conans\conan.py", line 6, in run                                                                            File "conan\conans\client\command.py", line 922, in main                                                                File "conan\conans\client\conan_api.py", line 124, in factory                                                           File "conan\conans\client\conan_api.py", line 94, in instance_remote_manager                                            File "conan\conans\client\store\localdb.py", line 12, in __init__                                                       File "conan\conans\client\store\sqlite.py", line 30, in connect                                                       conans.errors.ConanException: ('Could not connect to local cache', OperationalError('unable to open database file',))   Failed to execute script conan  `

I'm using conan v0.25.1

I have not any data (I have others like artifacts, .conan, ... but not any file called data). Any idea about it?

**Comment by lasote** [comment]
The file is trying (and failing to open) is `~/.conan/.conan.db`. Sometimes there are issues with the Windows indexer, please verify that you exclude the ~/.conan/ folder from the indexer and try again. If the problem persist, try to remove the .conan.db file (maybe it's locked?)

**Comment by jngd** [comment]
Thanks @lasote. I have disabled indexer for this folder and remove also conan.db file with the same result. When I do conan in my command line, this file is regenerated.

**Comment by memsharded** [comment]
Have you used the python pip install, or the Windows installer? Which Windows version are you using? Is your current user an Administrator?
 
Also, conan 0.26 is already available, I don't think the error will be different, but just in case. Also, if you used the Win Installer, maybe you could try to use the pip install (it is the recommended one)

**Comment by jngd** [comment]
@memsharded Before install v0.25.1 I have installed via pip and windows installer v0.26.0 with the same result: when I do anything with conan via cmd, conan doesn't returns any output of command executed. After uninstall all, I have installed via windows installer, v0.25.1, getting the error that I have reported. Is this version available via pip?

**Comment by lasote** [comment]
Yes. It's available in pypi too.

**Comment by memsharded** [comment]
Could you please try to remove everything, all the apps, then completely remove the ``<userhome>/.conan`` folder, and start from scratch installing the python pip version 0.26?
Which version of python are you using? I am not sure if stated in the docs, but I always run with python 32 bits, so typing python I get:
```
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
```

**Comment by jngd** [comment]
@memsharded All programs uninstalled. Fresh installation of Python 2.7.12 and conan v0.26 via pip:

Same result than when I have installed v0.26 via windows installer. No response when conan commands executed.

Python env:
`Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32                        Type "help", "copyright", "credits" or "license" for more information. `

Pip conan installation
`C:\Users\jngd>pip install conan                                                                                   Collecting conan                                                                                                          Using cached conan-0.26.0.tar.gz                                                                                      Requirement already satisfied (use --upgrade to upgrade): PyJWT<2.0.0,>=1.4.0 in c:\python27\lib\site-packages (from conan)                                                                                                                     Requirement already satisfied (use --upgrade to upgrade): requests<3.0.0,>=2.7.0 in c:\python27\lib\site-packages (from conan)                                                                                                                  Requirement already satisfied (use --upgrade to upgrade): colorama<0.4.0,>=0.3.3 in c:\python27\lib\site-packages (from conan)                                                                                                                  Requirement already satisfied (use --upgrade to upgrade): PyYAML<3.13.0,>=3.11 in c:\python27\lib\site-packages (from conan)                                                                                                                    Requirement already satisfied (use --upgrade to upgrade): patch==1.16 in c:\python27\lib\site-packages (from conan)     Requirement already satisfied (use --upgrade to upgrade): fasteners>=0.14.1 in c:\python27\lib\site-packages (from conan)                                                                                                                       Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in c:\python27\lib\site-packages (from conan)     Requirement already satisfied (use --upgrade to upgrade): node-semver==0.1.1 in c:\python27\lib\site-packages (from conan)                                                                                                                      Requirement already satisfied (use --upgrade to upgrade): distro<1.1.0,>=1.0.2 in c:\python27\lib\site-packages (from conan)                                                                                                                    Requirement already satisfied (use --upgrade to upgrade): pylint==1.6.5 in c:\python27\lib\site-packages (from conan)   Requirement already satisfied (use --upgrade to upgrade): future==0.16.0 in c:\python27\lib\site-packages (from conan)  Requirement already satisfied (use --upgrade to upgrade): pygments<3.0,>=2.0 in c:\python27\lib\site-packages (from conan)                                                                                                                      Requirement already satisfied (use --upgrade to upgrade): bottle<0.13,>=0.12.8 in c:\python27\lib\site-packages (from conan)                                                                                                                    Requirement already satisfied (use --upgrade to upgrade): pluginbase<1.0,>=0.5 in c:\python27\lib\site-packages (from conan)                                                                                                                    Requirement already satisfied (use --upgrade to upgrade): urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests<3.0.0,>=2.7.0->conan)                                                                                           Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests<3.0.0,>=2.7.0->conan)                                                                                              Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests<3.0.0,>=2.7.0->conan)                                                                                           Requirement already satisfied (use --upgrade to upgrade): idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests<3.0.0,>=2.7.0->conan)                                                                                                  Requirement already satisfied (use --upgrade to upgrade): monotonic>=0.1 in c:\python27\lib\site-packages (from fasteners>=0.14.1->conan)                                                                                                       Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from node-semver==0.1.1->conan)                                                                                                          Requirement already satisfied (use --upgrade to upgrade): backports.functools-lru-cache in c:\python27\lib\site-packages (from pylint==1.6.5->conan)                                                                                            Requirement already satisfied (use --upgrade to upgrade): configparser in c:\python27\lib\site-packages (from pylint==1.6.5->conan)                                                                                                             Requirement already satisfied (use --upgrade to upgrade): isort>=4.2.5 in c:\python27\lib\site-packages (from pylint==1.6.5->conan)                                                                                                             Requirement already satisfied (use --upgrade to upgrade): mccabe in c:\python27\lib\site-packages (from pylint==1.6.5->conan)                                                                                                                   Requirement already satisfied (use --upgrade to upgrade): astroid<1.5.0,>=1.4.5 in c:\python27\lib\site-packages (from pylint==1.6.5->conan)                                                                                                    Requirement already satisfied (use --upgrade to upgrade): lazy-object-proxy in c:\python27\lib\site-packages (from astroid<1.5.0,>=1.4.5->pylint==1.6.5->conan)                                                                                 Requirement already satisfied (use --upgrade to upgrade): wrapt in c:\python27\lib\site-packages (from astroid<1.5.0,>=1.4.5->pylint==1.6.5->conan)                                                                                             Installing collected packages: conan                                                                                      Running setup.py install for conan ... done                                                                           Successfully installed conan-0.26.0                                                                                     You are using pip version 8.1.1, however version 9.0.1 is available.                                                    You should consider upgrading via the 'python -m pip install --upgrade pip' command.     `

Conan command result:

`C:\Users\jngd>conan remote list                                                                                                                                                                                                           C:\Users\jngd>conan                                                                                                                                                                                                                       C:\Users\jngd>conan something                                                                                                                                                                                                             C:\Users\jngd>conan --help                                                                                                                                                                                                                 `

**Comment by lasote** [comment]
Is Conan running or just quiting the execution? Could you try to redirect the output to a file?

**Comment by memsharded** [comment]
Also, please try to print the returned error, something like:

```bash
$ conan remote list
$ echo %errorlevel%
```

The other option to start debugging what could be happening in your machine is to start adding ``prints`` to the source code. I would locate your ``def main(args):`` function in ``conans/client/command.py`` file, and start adding ``prints`` line by line to check what could be happening. If you need help with that, please tell me, maybe we could arrange some pair-debugging. Thanks!

**Comment by onfiro** [comment]
I have the same problem on conan 0.16.1 on Windows 10 installed from binaty package. Replace conan home directory to C:\conan fix it( detail in https://community.activestate.com/node/6709 )

**Comment by memsharded** [comment]
Hi @onfiro 

Have you tried the following?

- Use an updated version, we are already in 0.27. Old 0.16 can be considered totally deprecated.
- Use the pip installed version of conan, not the binary
- Use the standard CPython distribution of python, no the ActivePython? Which python were you using @jngd ?


If you could please try the above, that could help. Thanks for your feedback!

**Comment by onfiro** [comment]
Sorry, but I can`t update conan to newest version now. 
Already use standart CPython distribution.
If 0.16.0 avaliable in pip, what information could help you?

**Comment by memsharded** [comment]
> Sorry, but I can`t update conan to newest version now.

NP, but please just be aware that this is a deprecated version from more than 10 months ago, which is a lot given conan release speed, and its beta status. Even if we do a big effort not to break, this is a highly deprecated version. We try to provide automatic migrations from version to version, but jumps so big won't work. The more you wait to upgrade, the more potential issues.

Maybe something related to permissions? Is it possible that your user is a non-admin user? Something specific in your user home folder? Some encryption software? Encrypted home folder? Other software that could be interfering with your user home?

**Comment by memsharded** [comment]
Hi!

Those conan versions were deprecated time ago and are no longer supported. It seems they were some corner cases regarding very specific python installations, and without further feedback, any similar issues from any other users, and not being able to reproduce, I think this issue can be closed. But please comment, re-open or open a new issue if the problem persists for latest conan versions. Thanks!
