### ISSUE TITLE
Conan fails to determine that required library is used with different option to produce new build.

### ISSUE THREAD

**Issue by bobeff** [conan-io/conan#1696]
I created recipes for **OpenSSL** and **rabbitmq-c** libraries which by default produce static libraries. **rabbitmq-c** uses **OpenSSL**. I created (static, static) and (shared, shared) packages. But when I tried static **OpenSSL** used by shared **rabbitmq-c** **Conan** reports:

> conan install rabbitmq-c/0.8.0@igsoft/stable -pr x86_debug -o shared=True -o OpenSSL:shared=False
> rabbitmq-c/0.8.0@igsoft/stable: Installing package
> OpenSSL/1.0.2l@igsoft/stable: Already installed!
> rabbitmq-c/0.8.0@igsoft/stable: Already installed!

But the real installed package is (shared, shared). I have to write:

> conan install rabbitmq-c/0.8.0@igsoft/stable -pr x86_debug -o shared=True -o OpenSSL:shared=False --build=rabbitmq-c

for forcing **Conan** really to create new package but it replaces the old (shared, shared) package.

I described the dependencies the following way:

```python
def requirements(self):
    if self.options.ssl_support:
        self.requires("OpenSSL/1.0.2l@igsoft/stable")
```

I tried this with latest **Conan** version **0.26.0**.

**Comment by lasote** [comment]
I'm not sure I understand the issue, but the options have to be scoped for all the packages. Specify:

`conan install rabbitmq-c/0.8.0@igsoft/stable -pr x86_debug -o rabbitmq-c:shared=True -o OpenSSL:shared=False --build=rabbitmq-c`

**Comment by memsharded** [comment]
In order to keep it short, remember that you can add the options to the profile too:
```
[options]
rabbitmq-c:shared=True
OpenSSL:shared=True
```

**Comment by bobeff** [comment]
The issue is that:
```
conan install rabbitmq-c/0.8.0@igsoft/stable -pr x86_debug -o rabbitmq-c:shared=True -o OpenSSL:shared=True --build=rabbitmq-c
```
is not recognized as different from:
```
conan install rabbitmq-c/0.8.0@igsoft/stable -pr x86_debug -o rabbitmq-c:shared=True -o OpenSSL:shared=False --build=rabbitmq-c
```

**Comment by lasote** [comment]
Has the openssl recipe the shared option? Are you adjusting some options at runtime in a configure method? Could I take a look to the recipes?

**Comment by bobeff** [comment]
[Here ](https://pastebin.com/SZ1FLD3B )is **OpenSSL** recipe and [here ](https://pastebin.com/FrGBGMzJ) **rabbitmq-c** one.

**Comment by lasote** [comment]
It is requiring a different binary when you change the shared option. Can't reproduce the issue.

Both shared:
```
rabbitmq-c/0.8.0@igsoft/stable: Installing package
Requirements
    OpenSSL/1.0.2l@igsoft/stable from local
    rabbitmq-c/0.8.0@igsoft/stable from local
Packages
    OpenSSL/1.0.2l@igsoft/stable:c83d8b197f1a331ca3b55943846d427ad4f7f8e1
    rabbitmq-c/0.8.0@igsoft/stable:f8125598e3718406d3b6d211f2717a8160b7ab58
```

 rabbitmq-c:shared=True -o OpenSSL:shared=False:
```
rabbitmq-c/0.8.0@igsoft/stable: Installing package
Requirements
    OpenSSL/1.0.2l@igsoft/stable from local
    rabbitmq-c/0.8.0@igsoft/stable from local
Packages
    OpenSSL/1.0.2l@igsoft/stable:c32596dcd26b8c708dc3d19cb73738d2b48f12a8
    rabbitmq-c/0.8.0@igsoft/stable:f8125598e3718406d3b6d211f2717a8160b7ab58
```

-o rabbitmq-c:shared=False -o OpenSSL:shared=False
```
rabbitmq-c/0.8.0@igsoft/stable: Installing package
Requirements
    OpenSSL/1.0.2l@igsoft/stable from local
    rabbitmq-c/0.8.0@igsoft/stable from local
Packages
    OpenSSL/1.0.2l@igsoft/stable:c32596dcd26b8c708dc3d19cb73738d2b48f12a8
    rabbitmq-c/0.8.0@igsoft/stable:b81c3dfc752847050c78913d2b15ca0a0b854689
```

**Comment by bobeff** [comment]
The issue is not in the packages required but in the final package created. In both cases with static and shared **OpenSSL** the final **rabbitmq-c** package is the same. But this is not correct because this are different builds. In one the **rabbitmq-c** library uses shared **OpenSSL** from `dll`, but in the other it uses static **OpenSSL** linked statically into **rabbitmq-c**'s `dll`. But the package with the same hash is created for **rabbitmq-c** in both cases and the second build overrides the first.

**Comment by lasote** [comment]
Thanks, now I understand the issue. 
You can control when the rabbitmq-c package changes its SHA when its requirements changes. In this case, if you want to generate a different package for rabbitmq when openssl changes an option:

```
def package_id(self):
    # Any change in the MyOtherLib version, user or
    # channel or Package ID will affect our package ID
    self.info.requires["OpenSSL"].full_package_mode()
```

You can read more here: http://conanio.readthedocs.io/en/latest/howtos/define_abi_compatibility.html

**Comment by bobeff** [comment]
Thanks for the explanation how to overcome the issue. But isn't it logical almost always when some of the required packages change its **SHA** to change the **SHA** of produced package, because this way the build is different? The decision by default the package **SHA** to depend only on package settings and options. but not on the settings and options of its requirements is strange. For example there is huge different whether **OpenSSL** is linked statically to some other library `dll`, or it itself is used as `dll` and this way its `dll` have to be added to the application distribution.

**Comment by lasote** [comment]
It's not always true. Only affects if the consumer library, in this case, rabbitmq is embedding the consumed library, OpenSSL. Make it sense to default to `full_package_mode()`? Could be, In this case, the more frequent use case for OpenSSL is to distribute it as a DLL not embedded in any other library, so any option affecting OpenSSL should not change the SHA of the libraries consuming it.

The key here is that you cannot know it automatically, only the user creating the packages can understand (as you did) if the sha needs to change or not, so we providede the `package_id` method.

**Comment by bobeff** [comment]
Thanks for the explanation once again and I think that you can close the issue.
