### ISSUE TITLE
[feature] Provide means to drop a tool_requires when the system provides a good enough alternative

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#16961]
### What is your suggestion?

I'd like to use something like `replace_tool_requires` to drop some tools when I know the system provides a good enough version of said tool.

A good example is CMake, many recipes ask for a given version, so I end up with multiple versions of CMake on the cache (not a big deal). But we we maintain our own conan remote, so I either have to patch the recipes to unify the version of CMake they use and deviate from conan-center (which makes sync-ing our conan-center mirror tedious) or maintain multiple versions of CMake, which could also be tedious.

I've seen modern recipes use version ranges for tools like CMake, which helps but I still think it would be a neat feature to be able to just do
```
[replace_tool_requires]
cmake/*:
```
And just drop CMake. 

Alternatively, which might be harder to implement, a conf could be added to automatically use the system-provided tool, if available and the version is ok.
```
[tool_requires_use_system_if_possible]
cmake/*
```
Then if a recipe requires CMake, conan could query the system to see if it is available and if it is, skip it.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @ericriff thanks for your question

You might be looking for the `platform_tool_requires` feature, which  is documented here https://docs.conan.io/2/reference/config_files/profiles.html#platform-tool-requires, and achieves mostly what you ask for, please take a look and let us know if it works for you.

Happy to answer further questions if not! :)

**Comment by ericriff** [comment]
I completely missed this. 
Sorry about the noise!
