### ISSUE TITLE
[question] Validating package version values in conan recipe 

### ISSUE THREAD

**Issue by mys2kor** [conan-io/conan#16985]
### What is your question?

Hi,

In our conan recipe file, we want the user to put only fixed (ex. 1.2.3 or 1.2) or semantic (ex ^1.2.3 or ^1.2). We do not want to allow ranges (ex. [>= 1.2] or [>=1.2 <=1.12] ).
Is there a way to accomplish this with conan? We tried to use `conan info` command with the output parsed to a json file and use that file to do some validation. However, that json only had fixed version and even the range values are accepted as input.

Any suggestions as how to go about this?

**Note: We are using conan version 1**

**Comment by memsharded** [comment]
Hi @mys2kor 

Thanks for your question.

> In our conan recipe file, we want the user to put only fixed (ex. 1.2.3 or 1.2) or semantic (ex ^1.2.3 or ^1.2). We do not want to allow ranges (ex. [>= 1.2] or [>=1.2 <=1.12] ).

Could you please clarify why? A ``^version`` is totally equivalent to a version range, and in fact it is internally mapped and represented as one. Furthermore, we know from experience that a large majority of developers cannot distinguish or know clearly about the resolution of ``^version``, while they perfectly understand the explicit comparison operators. This is why we generally recommend the explicit comparison operators over the caret or tilde shortcuts.


Conan doesn't have something like that at this moment. But Conan recipes ``conanfile.py`` are code, they should be in git repos as any other code, and CI will be used to create packages from them when they change. Maybe the way to go is to do it as a source code check? It would be relatively easy to parse/regex the recipes and check for patterns? 

If you wanted to integrate this in your workflow, it could be made a Conan custom command. You might even overwrite the built-in ``conan create`` or ``conan export`` and inject there the extra checks over the ``conanfile.py`` code, but it seems a bit too much to me. I'd probably do a custom ``conan myorg:recipe-check`` command that both CI and devs can run to check the recipes follow some of your org conventions.

**Comment by mys2kor** [comment]
Hi @memsharded 

Thanks for the quick response.
I am sorry for not being very clear in my question. What I meant with version range is some thing like [>= 2 <=5.5] and not just a range within the same Major version (which, as you mentioned can be accomplished by using the caret symbol).
We want to avoid the range syntax altogether.

Thanks for the suggestion. We will look into parsing the `conanfile.py` and do a custom check on that.

**Comment by memsharded** [comment]
> What I meant with version range is some thing like [>= 2 <=5.5]

Thanks for clarifying, I understand now, I see how it can make sense to try to avoid it (in some cases, like for example ``openssl``, it might be desired, we have the range ``[>=1.1 <4]`` for ConanCenter ``openssl``, because they did the jump from 1 to 3, being API compatible.

> Thanks for the suggestion. We will look into parsing the conanfile.py and do a custom check on that.

Sounds good, let us know how it goes.
If there is no further question, maybe we can close the ticket? You can always re-open it, or create new tickets for any other question or issue. Thanks for the feedback!

**Comment by mys2kor** [comment]
@memsharded  Thanks. Closed the issue.
