### ISSUE TITLE
[question] Conan 2 Migration: CMAKE_CXX_FLAGS_RELEASE Behavior

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#16993]
### What is your question?

I'm in the process of migrating my company from Conan 1.x (1.65.0) to Conan 2.x (2.7.0). When working on migrating our customized (minor changes like using a local source zip vs. download) POCO recipe (https://github.com/conan-io/conan-center-index/tree/master/recipes/poco/all) I noticed a behavior delta when using the same profile (with the 2.x profile having necessary syntax updates), same POCO source version (1.9.0), and same CMake version (3.15.4):

Conan 1.x CMAKE_CXX_FLAGS_RELEASE are "-O3 -DNDEBUG -s"
Conan 2.x CMAKE_CXX_FLAGS_RELEASE are "-O3 -DNDEBUG"

I've been trying to figure out where the "-s" flag is coming from as I want it to be present for the Conan 2.x POCO build (and release builds in general, really). 

Could anyone provide some guidance as to what might be causing the "-s" flag to be excluded in the Conan 2.x build?

Profile Summary:
[settings]
os=Linux
arch=armv5te
compiler=gcc
compiler.version=8.4
compiler.libcxx=libstdc++11
compiler.cppstd=gnu11
build_type=Release

[buildenv]
CONAN_CMAKE_SYSTEM_NAME=Linux
CONAN_CMAKE_SYSTEM_PROCESSOR=armv5te
PATH=...
CC=...
CXX=...
LD=...
CFLAGS=--sysroot=...
CXXFLAGS=--sysroot=...
LDFLAGS=--sysroot=... -L.../usr/lib

Thank you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @radonish 

Thanks for your question.

This is the relevant code in Conan 1:
```python
        if str(compiler) in ["clang", "gcc", "apple-clang", "qcc", "mcst-lcc"]:
            # FIXME: It is not clear that the "-s" is something related with the build type
            # cmake is not adjusting it
            # -s: Remove all symbol table and relocation information from the executable.
            flags = {"Debug": ["-g"],
                     "Release": ["-O3", "-s"] if str(compiler) == "gcc" else ["-O3"],
```
As you can see, it contains a ``FIXME`` about this. 
The ``-s`` which strips symbols is not really a Debug/Release flag, and it was incorrectly being added by Conan 1.
It has been fixed in Conan 2, and whether the symbols are stripped or not, that is a build decision that user build scripts will do.

**Comment by radonish** [comment]
@memsharded, thank you for the quick response and background as to why the delta was occurring. Much appreciated.

**Comment by memsharded** [comment]
Happy to help!
