### ISSUE TITLE
[question] Different versioning schemes based on build_type

### ISSUE THREAD

**Issue by mtribiere** [conan-io/conan#16991]
### What is your question?

Hi! I'm trying to implement a use case where our product version is different based on build_type.
The basic rule for package versions is:
- `Release`: Load the version.txt
- `Debug`: name of the current branch

My naïve implementation in the `conanfile.py` was the following:
```python
def set_version(self):

    # If the current version is tagged, use the current branch
    if self.settings.build_type == "Release":  
        self.version = load(self, "version.txt")

    else: # Else use the branch name as the version
        self.version = git.run("branch --show-current")
```

However this doesn't work, seems like when the `set_version` is evaluated none of the settings are populated yet.
How could I achieve my use case? And is my approve the correct one?

Thanks you for your help!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mtribiere 

Thanks for your question.

I am afraid this is not possible. As you can check the binary model in https://docs.conan.io/2/reference/binary_model/package_id.html, means that there is 1 recipe (with its name, version, etc), and for that version it can have any number of different binaries, for the different configurations Release/Debug, shared/static, architectures, OSs, etc.

But it is not possible to make the version of the package different for different build_type (or any other setting or option).

Could you please elaborate a bit more what problem are you trying to solve with this versioning approach? It is possible that there could be other solutions. In fact one of the advantages of using Conan is that this is not necessary, you can have the same version for both Release/Debug, and still have different behavior of the package, cause when consumers use them, they will get in practice different binaries, even different headers if they want to.

**Comment by mtribiere** [comment]
Hi @memsharded 

Thanks for the answer. I will try to be little more general, there might be a better solution.
The workflow we use right now is the following: 

Per library, we have a git repo, let's say `lib_a`. Each repo contains X amount of branches (main, feature/CAN_FD, hotfix/lang,... ).
Those branches each produce a library via jenkins that we consider as "Debug" builds. (Each push triggers a new build and a new delivery). 
The consumer of those libraries simply calls (in our own dependency manager) for `lib_a;feature/CAN_FD` for example. This would result in the consumer getting the latest build of the `lib_a` that as been produced by the `feature/CAN_FD` branch.

For Release, much simpler, a commit is tagged (say `v1.0.1`), build by jenkins. Then the consumer reference `lib_a;v1.0.1`.

Apologies if it's not the clearest, let me know if I can clarify any part of this.
If we want to migrate our current workflow to Conan, how should we go about building something like this?

Thanks for your help

**Comment by memsharded** [comment]
Thanks for the clarifications.

If I understood correctly, I'd say that the build_type is not a condition but a result/consequence.

Basically the logic seems to be:
- There is some external logic to Conan that defines both the version and the build_type.
- If the external logic is based on git information, for example if the current commit is a tag or not, then it is possible to deduce the version in ``set_version()`` from the branch logic. If it is a tag version, pick the ``1.0.1``, if it is a feature branch, pick the version with the name of the branch.
- The version can be relatively easily reported with ``conan export`` or ``conan inspect``
- Same applies to the profile or command line definition of ``build_type=Debug``, it is a result of being in that branch, not a condition. So the version obtained in the previous step can be used to define the ``build_type``

Please let me know if this makes sense.

**Comment by mtribiere** [comment]
Thank you for the clarification, I think I had it backwards. 
As you said, the build_type is a result of being on a branch, not the condition. It's the other way around.

That logic will probably be handled by Jenkins then.
I will close the question, thank you for your helpful answers :)

**Comment by memsharded** [comment]
Happy to help! :)

Don't hesitate to create new tickets for any further question that you might have, thanks for your feedback.
