### ISSUE TITLE
[question] Can we use conan packages with C# project?

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#17007]
### Can we use conan package in a C# project?

I have a requirement to use a conan package containing some dlls in a C# project. I tried the usual approach of generating the props file and including them in the C# project, but unfortunately the values do not seem to appear under the macros or anywhere. Is there some other approach to achieve this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

Thanks for your question.

> Can we use conan package in a C# project?

Yes, we are aware of users that are using Conan to manage C# projects

> I have a requirement to use a conan package containing some dlls in a C# project. I tried the usual approach of generating the props file and including them in the C# project, but unfortunately the values do not seem to appear under the macros or anywhere. Is there some other approach to achieve this?

You would need to be more specific. If a package contain only DLLs, but not import libs (the small static .lib that load the dll), then, they can certainly not be "linked" by a regular C++ project, so it is normal they will not appear in the generated ``.props`` files, if you are talking about ``MSBuildDeps``, which is not clear either). But they can still be used as runtime, and they will be added to the PATH environment variable.

**Comment by sandybhat16** [comment]
Sorry for missing details. Here is the scenario. I have a C# project in my visual studio solution which wants to consume a particular dll. There is a conan package which contains precompiled dlls(Don't ask why, this is how it is :D). The idea is to install this conan package and utilize it in the C# project.

I can do this easily for C++ projects using the `MSBuildDeps `generator that generates the props file which I include it in the project and can access all the props variables.

However, this approach does not work for C# project as you cannot include a props file in a C# project. 
So my question is how does one deal with in such a scenario? How can I consume the installed conan package(this custom package containing only dlls) in the C# project?

**Comment by memsharded** [comment]
The way to approach this would be to make a custom generator, preferably as ``python_requires``, but it can also be a global generator: https://docs.conan.io/2/reference/extensions/custom_generators.html#custom-generators-as-python-requires

There you write the logic you want to generate the files you want for your C# projects, with the information provided by the ``dependencies`` field, as the example shows.

**Comment by sandybhat16** [comment]
Thanks for your response. Will try this out.
