### ISSUE TITLE
[bug] Typo in error message when name is not in package list

### ISSUE THREAD

**Issue by simmplecoder** [conan-io/conan#17003]
### Describe the bug

The following error message will appear
```
ERROR: 'Local Cache' doesn't exist is package list
```

if for example list did not go through `conan list` after `conan create`.
Is it supposed to be `in package list` instead of `is package list`?

### How to reproduce it

For drogon recipe:
```
conan create all/conanfile.py -pr:a=default-debug --version=1.9.5 --format=json > $HOME/create.json
conan upload --list=$HOME/create.json -r=<any remote> -c
```

**Comment by memsharded** [comment]
Thanks for your report

> Is it supposed to be in package list instead of is package list?

Yes, that seems to be the case, you are right
