### ISSUE TITLE
conan install is Fail!

### ISSUE THREAD

**Issue by Caesar454905970** [conan-io/conan#17011]
### Describe the bug

![image](https://github.com/user-attachments/assets/5f68880b-052d-4fd5-ac31-2bb708af223a)
![image](https://github.com/user-attachments/assets/c5f051b3-1760-4e3d-b476-777121ed8e3e)
[requires]
pdfium/95.0.4629
[generators]
CMakeDeps
CMakeToolchain

[options]
pdfium*:shared=True

**Comment by AbrilRBS** [comment]
Hi @Caesar454905970, thanks for your issue. This seems to be an issue with your proxy connection, as I'm able to download the file just fine, and the error seems to point that way.

Could you please check if it's properly setup? Thanks!

**Comment by Caesar454905970** [comment]
i am from China，I can't access Google without using VPN；however,conan does not allow VPN downloads！

**Comment by Caesar454905970** [comment]
> 你好@Caesar454905970，谢谢您的问题。这似乎是您的代理连接的问题，因为我可以正常下载文件，错误似乎指向了这一点。
> 
> 您能否检查一下是否设置正确？谢谢！
i use VPN to chat  with you now.

**Comment by danimtb** [comment]
@Caesar454905970 thank you for your comment.

Unfortunately, we can't help you further on your issue. To try to debug what's happening, I'd suggest trying with the following curl command to test your connection issue:

```
curl https://pdfium.googlesource.com/pdfium/+archive/refs/heads/chromium/4629.tar.gz -o file.tar.gz
```

When the curl command successes, then try again with Conan and report if there is any other issue with the download.
Thanks again for reporting your issue and I hope this helps 🙂
