### ISSUE TITLE
[feature] Redirect stderr from pkg-config in PkgConfig

### ISSUE THREAD

**Issue by cubanpit** [conan-io/conan#17013]
### What is your suggestion?

In [PkgConfig](https://github.com/conan-io/conan/blob/develop2/conan/tools/gnu/pkgconfig.py) tool there is the `_parse_output` method which executes pkg-config, it redirects the stdout but leaves the stderr stream to the terminal.
When using PkgConfig and catching the ConanException we end up having stderr in the terminal, which is not desirable.
I would propose to redirect stderr as well in `run()`, save it and print it as part of the exception message in `fill_cpp_info()`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your suggestion @cubanpit 

I think it makes sense, I am proposing PR https://github.com/conan-io/conan/pull/17020 to implement this (together with some extended cmd, stdout and stderr reporting if the exception is raised)

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/17020 was merged, so this will be in next Conan 2.8, thanks again for the feedback.
