### ISSUE TITLE
[feature] Implement verbosity levels for 'remote' command

### ISSUE THREAD

**Issue by cubanpit** [conan-io/conan#17014]
### What is your suggestion?

As far as I can tell, when running `conan remote` commands the output does not depend on the verbosity level.
I tried setting it from command line and `conan remote -vquiet disable '*'` is not considered a valid command, other variations just ignore the setting and print the same output.
I tried setting it from environment variable `CONAN_LOG_LEVEL`, but it is again ignored.
From a quick look at the code I would guess it is not implemented at the moment, I think it would be nice to have.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cubanpit 

Thanks for your suggestion.

> I tried setting it from command line and conan remote -vquiet disable '*' is not considered a valid command, other variations just ignore the setting and print the same output.

I'd like to understand what would be the problem we would be trying to address here. Yes, it is true that at the moment the ``remote`` commands doesn't implement different levels of verbosity, but this is because their output is always very reduced, so what would be the benefit of ``conan remote disable`` not reporting what remotes were actually disabled?

**Comment by cubanpit** [comment]
I would expect consistency with what the verbose options are saying, for example `-werror` would only print errors, the listing of the disabled remotes is not an error.
Of course this is only a minor detail, but it is nice to be able to set a policy and know that all Conan commands are respecting it.

**Comment by memsharded** [comment]
Sure, sure, I agree that things should be consistent, I was trying to understand the "magnitude" of the issue and trying to learn if there was there some other use case, flow, or anything that we could be missing, that would be affected by this, also to be able to prioritize the work.

**Comment by memsharded** [comment]
I have double checked this, and the thing is that ``conan remote disable`` is actually returning the list of disabled remotes as "result", and that result is being processed by the default text formatter:
```
@conan_subcommand(formatters={"text": print_remote_list, "json": formatter_remote_list_json})
def remote_disable(conan_api, parser, subparser, *args):
```
So the ``conan remote disable`` can also return a json formatted file with the disabled remotes.
In that regard, the ``-v`` verbosity levels do not apply, because they only apply to ``stderr`` informational messages of Conan, not to commands results, that goes to ``stdout`` (or redirected to a file).

**Comment by cubanpit** [comment]
Yes, I would expect a behavior similar to what `conan export` does (Conan 2.6):
```
$ conan export cci/recipes/zlib/all --version 1.2.13
[verbose output]
$ conan export cci/recipes/zlib/all --version 1.2.13 -v quiet
[no output]
$ conan export cci/recipes/zlib/all --version 1.2.13 --format json
[verbose output]
[json output]
$ conan export cci/recipes/zlib/all --version 1.2.13 --format json -v quiet
[json output]
```
But I have not checked the difference in the implementation between the two commands.

**Comment by memsharded** [comment]
The behavior is already the same.
The only difference is that ``conan remote disable`` does not have any informational messages directed to ``stderr``, all is output that goes to ``stdout``, so in this regard, it is already behaving as ``conan export`` does. You can verify with:
```
conan remote disable "*" --format=json > disabled.json
```
No output in terminal there at all.

**Comment by cubanpit** [comment]
From your previous message I understand that the difference is that the plain text output is considered an alternative to the JSON output in the `remote` command, contrary to the `export` command which has the plain text output for "logging" purpose only.
This means it cannot be silenced because the `-v` flag only affects the "logging" output and not the "result" output.
All this explains the difference, then it becomes a question of opinion which behavior is better, I find the behavior of the `export` command quite clear and more consistent with the provided flags.

**Comment by memsharded** [comment]
> From your previous message I understand that the difference is that the plain text output is considered an alternative to the JSON output in the remote command, contrary to the export command which has the plain text output for "logging" purpose only.

Exactly, the printed lines in ``conan remote disable`` is "result", while the printed lines in ``conan export`` are "information"
You can see the difference with:

```
λ conan export . --format=json > exported.json
```
The information messages will be printed, but an ``exported.json`` file will be generated with the "result" of the command. The difference is that ``conan export`` doesn't have a default ``text`` formatter, so it is not printing to stdout that information, but the behavior is fully consistent across different commands.

**Comment by cubanpit** [comment]
Thank you for the detailed explanation with examples, it was not obvious to understand (at least for me). I guess the issue can be closed and people who might want to filter the output can use shell output redirection on stdout, as is the case for JSON output, eventual warnings/errors will be on stderr and will still be visible. Verbosity levels will only work on the `remote` command if "information" output is added to it in the future, "result" output will never be affected by those.
