### ISSUE TITLE
[bug] SSL certification of conancenter fails

### ISSUE THREAD

**Issue by thomaskeller79** [conan-io/conan#17019]
### Describe the bug

I am trying to follow the first step of the Conan 2 tutorial as described [here](https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html) and the execution of the conan install command (conan install . --output-folder=build --build=missing) fails with the following error:

ERROR: Package 'zlib/1.2.11' not resolved: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))

I am running Conan version 2.7..1 on Ubuntu 22.04 that is running inside WSL.

### How to reproduce it

Can be reproduced by following the steps in the tutorial (this is the first one, so it's basically just the installation - in my case within a python3 virtual environment - and the checkout if the tutorial repo).

**Comment by czoido** [comment]
Hi @thomaskeller79,

Thanks a lot for your question. We have seen these issues happening under some VPNs, ZScaler and similar, that might need to add some exceptions to their filters. Is it happening under some corporate network? Can you try on a different machine on same network or same machine, other network?

You can also try to use the `tools.files.download:verify` conf adding something like: `-c="zlib/*:tools.files.download:verify=False"` to the Conan command.

```
conan install . --output-folder=build --build=missing -c="zlib/*:tools.files.download:verify=False"
```

Hope this helps.

**Comment by thomaskeller79** [comment]
Thanks @czoido for the quick response! The tool.files.download:verify option does not help, but I am indeed in a corporate network with ZScaler restrictions. I'm going to request an exception in the ZScaler config and let you know if this is indeed the problem.

**Comment by thomaskeller79** [comment]
ZScaler has indeed been the issue. After adding an exception I was able to download zlib from conancenter.

Thanks for the help!
