### ISSUE TITLE
[bug] `<host_version>` does not work if the features are not the default ones

### ISSUE THREAD

**Issue by mmomtchev** [conan-io/conan#17021]
### Describe the bug

`<host_version>` does not honor the options of the host version package

### How to reproduce it

Consider the following `conanfile` which is what `harfbuzz` does:

```python
from conan import ConanFile

class MyConanFile(ConanFile):
	settings = 'os', 'compiler', 'build_type', 'arch'

	def requirements(self):
		self.requires('glib/2.81.0')
		self.tool_requires('glib/<host_version>')

	def configure(self):
		self.options['glib'].with_selinux = False
```

It will produce two distinct glib installations - one with SELinux enabled and one with SELinux disabled.

In fact, currently, I do not see any way to modify the options of `tool_requires` of my dependencies.

**Comment by AbrilRBS** [comment]
Hi @mmomtchev thanks for your question.

The `<host_version>` mechanism is intended only for version matching, it's not its responsability to modify the options of the build dependency.

As for the options for `tool_requires`, they can be set either in the `tool_requires()` call, or as part of the `default_build_options`, see https://docs.conan.io/2/reference/conanfile/attributes.html#default-build-options

Let me know if this helps

**Comment by mmomtchev** [comment]
Yes, this does it.

**Comment by mmomtchev** [comment]
Actually the only reliable way to do this is with a profile with `[options]` section.
