### ISSUE TITLE
[question] -j8 and MinGW Generator 

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#17038]
### What is your question?

Dear Conan Folks,

I enabled in my profile:
tools.build:jobs=8
with the help of documentation:
https://docs.conan.io/2/reference/tools/cmake/cmake.html#conf
So, I expect that make is called with -j8. However, I donot see that cmake build is getting called with -j8 option.
Also, Do I set it correctly?
I also checked the CMakeConfigureLog.yaml which also doesnot show the -j8 option being called with make.
If it is not set in profiles, what is the default behaviour? 
Could you please help me?

Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

When I am running 
```
conan build . -c tools.build:jobs=7 -c tools.cmake.cmaketoolchain:generator="MinGW Makefiles" -c tools.compilation:verbosity=verbose
```
I can see in the output:
```
conanfile.py (mylib/0.1): RUN: cmake --build "C:\Users\Diego\conanws\kk\build\Release" --verbose -- -j7
```
So it seems Conan is instructing CMake to forward the ``-j7`` to the underlying build (in this case mingw32-make``, seems to be working fine.

**Comment by maitrey** [comment]
Ah I was looking at the configure instead of build.  Yes it absolutely works!!!!
Thank you for replying.

**Comment by memsharded** [comment]
Happy to help!
Closing this ticket as resolved then, thanks for the feedback!
