### ISSUE TITLE
[question] How to Install Conan Packages Without Downloading Source Files?

### ISSUE THREAD

**Issue by leviskim17** [conan-io/conan#17034]
### What is your question?

Hi Conan!

May I know whether it is possible to install packages without downdload source()?

[conanfile.py.txt](https://github.com/user-attachments/files/17093428/conanfile.py.txt)
Currently, I am installing with the attached conanfile.py through the command, `conan install . -s compiler=msvc -s compiler.version=193 -s compiler.cppstd=20 -s os=Windows -s build_type=Release -s arch=x86_64 -of=%CONAN_PATH%\props --deployer=recap_deploy --deployer-folder=%INSTALL_FOLDER%  -c tools.build:download_source=True`

It downloads packages well. but there are complaints from the team it occupy much disk spaces. So I'd like to search there is a way not to download source().
![1](https://github.com/user-attachments/assets/a1f5ed04-115f-4c9b-9b0e-acda2ea494f0)

When I tried build=never, it seems to try source() as well. 

While using conan install, is there a way to download only the package without downloading the source from the source() method?

Conan version: conan==2.2.3
OS: Windows 10

Thanks you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @leviskim17 

Thanks for your question.

You are forcing the download of sources with the `` -c tools.build:download_source=True`` argument.
If you don't pass that argument, the sources will not be downloaded, unless the package needs to build from sources.

**Comment by memsharded** [comment]
Hi @leviskim17 

Any further feedback or question here? Thanks!

**Comment by leviskim17** [comment]
Hi @memsharded,
No more question. Thanks!
