### ISSUE TITLE
[question] Applying patches to conan-center package

### ISSUE THREAD

**Issue by HazyMrf** [conan-io/conan#17037]
### What is your question?

Hello, I want to apply my custom patch to onnxruntime. I see that there is an official package here https://conan.io/center/recipes/onnxruntime and it contains a lot of stuff -- many versions, many different patches, even some .cmake file patch in a special directory. How can I proceed to apply my patch to onnxruntime in conanfile.py? Should I just copy all these patches and .cmake and just add my .patch file to them or there is a more elegant way?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @HazyMrf 

thanks for your question.

Yes, if you have a patch for a library in ConanCenter, the recommended approach is described in https://docs.conan.io/2/devops/using_conancenter.html, basically:

- Fork ``conan-center-index`` github repo
- Modify the recipe at your will, add patches or change the recipe itself
- Create the packages from your fork
- Upload the packages to your own server

In general, doing this is still recommended for many production cases, even if the recipes are not modified, for all your production dependencies, as explained in that docs page.

**Comment by HazyMrf** [comment]
Thank you @memsharded for such a quick response❤️
