### ISSUE TITLE
[question] Building package with multiple workstation 

### ISSUE THREAD

**Issue by mtribiere** [conan-io/conan#17032]
### What is your question?

Hi I'm trying to migrate a rather complex job to conan. 

Here the current process: The job is running on Jenkins and build the binaries ( `.elf`) on a Linux node. Those binaries are then sent by Jenkins to a Windows node for generating more binaries (`.bin`) based on those `.elf`. They are then all delivered to a storage server.
This multi OS setup is sadly necessary as the build process only works on Linux, and the software that generates the `.bin` for the `.elf` is only compatible with Windows.

How should I go about having something like this, i.e a single package with both `.elf` and `.bin` files with Conan/Jenkins?

My first intuition would be to have a `conan create .` build the `.elf` files, then somehow pause the process as it's about to package it. Then send the files over to the Windows node with Jenkins, and get the `.bin` copied in the build folder. And finally package and upload.

I'm not sure this is the right approach, would you have any advice on this?
Thank you for your help

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mtribiere 

Thanks for your question. This is an interesting use case.

> How should I go about having something like this, i.e a single package with both .elf and .bin files with Conan/Jenkins?

> My first intuition would be to have a conan create . build the .elf files, then somehow pause the process as it's about to package it. Then send the files over to the Windows node with Jenkins, and get the .bin copied in the build folder. And finally package and upload.

Interrupting the ``conan create`` could be complicated, I don't think this is possible.


I would probably try to consider these different approaches:

- If you can have a build agent that you can connect via ``ssh``, then you might try to call it from the ``build()`` method from your Windows machine. This would make transparent (or hidden in the recipe) the details that this is being built in a Linux machine remotely. In Windows machines with WSL it is also possible to forward tasks to the WSL and then recover the generated binaries. This is simple from the Conan-recipes point of view, but requires some extra infra in place (WSL or a ssh connection to a build agent)
- To model it a bit more explicitly with Conan you might try something like:
  - Create a ``pkg_elf/version`` package for the ``elf`` binary that only builds in Linux (you can control that with ``validate_build()``) but can be consumed from other OSs (removing settings in ``package_id()``)
  - Make a requirement to ``pkg_elf/version`` from the ``pkg_bin/version`` package.
  - A ``conan graph build-order --order=by-recipe`` will return the right order with the right configurations to run in a CI distributed way.

Please let me know if this helps.

**Comment by mtribiere** [comment]
Hello @memsharded 

Thank you for your response. The  first approach you suggest might cause some tractability issues, as those ssh connections will happen "outside" of Jenkins and therefore we cannot trace them.
The second might be a winner for me, two separate packages would work in our context. Plus I feel it describes the overall process more explicitly. 

I will go with that, closing the issue, thank you again for the help.

**Comment by memsharded** [comment]
Great, thanks for the feedback.

Don't hesitate to create new tickets for any further question, I know this is a bit exceptional case, so there will most likely be questions along the path.
