### ISSUE TITLE
[question] EDITABLE MODE BUILD

### ISSUE THREAD

**Issue by dragananinkovic** [conan-io/conan#17042]
### What is your question?

Hello all, 
I have two Conan repos where the first one (let's say A) is dependency for the other (let's say B) and I can do Conan build and Conan create properly (everything is tested in detail) but when I try to build dependency in editable mode as
`conan build . -pr:h=profile-1 -pr:b=profile-2 --build=editable` 
I get many errors in the code (It says that some macros are not defined). I modified layout method in repo A conan recepie by looking at https://docs.conan.io/2/tutorial/developing_packages/editable_packages.html#editable-packages and  https://docs.conan.io/2/tutorial/developing_packages/package_layout.html :
```
def layout(self):
        #set current folder as source folder
        self.folders.source = "."
        # set build folder as build/Release or build/Debug depending on profile
        self.folders.build = os.path.join("build", str(self.settings.build_type))
        # set path to generators
        self.folders.generators = os.path.join(self.folders.build, "generators")
 
        # set path to the all folders which contain header files
        self.cpp.source.includedirs = ["include","examples","src"]
        # set path to the bin folder
        self.cpp.source.bindirs.append("buildDst/bin")
 
        # set path to library folder
        self.cpp.package.libdirs.append("buildDst/lib")
        # list all libraries which package should contain
        self.cpp.package.libs = ['lib1', 'lib2', lib3']
        # set path to the all folders which contain header files
        self.cpp.package.includedirs = ["include","examples","src"] 
```
'lib1', 'lib2' and 'lib3' are libraries inside package A (this list is the same as in in package_info). 
And I modified package_info to this:
```
 def package_info(self):
        if not os.path.exists(os.path.join(self.package_folder, "lib")):
            self.cpp_info.bindirs = ["buildDst/bin"]
            self.cpp_info.libdirs = ["buildDst/lib"]
 
        self.cpp_info.libs = ['lib1', 'lib2', lib3']
        self.cpp_info.includedirs = ["include", "examples", "src"] 
```
Only difference between Conan cache and my repo is that in my repo all build folders are not in build/Release but also in buildDst, and in Conan cache all these folders are directly in Conan cache, but as you can see I modified all paths accordingly. Could you help me with this please.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @dragananinkovic 

Thanks for your question.

I think I am missing in your ``layout()`` above some important definitions like the ``libdirs`` at build time:

So something like:
```python
def layout(self):
        ...
        # set path to the all folders which contain header files
        self.cpp.source.includedirs = ["include","examples","src"]
        # set path to the bin folder
        # FIXME: This bindirs is probably better as self.cpp.build.bindirs
        self.cpp.source.bindirs.append("buildDst/bin")
        # THIS WAS MISSING
        self.cpp.build.libdirs= ["path/to/libs/in/local/build"]
```

Note that you can easily setup a working example with:
```
$ mkdir liba && cd liba && conan new cmake_lib -d name=liba -d version=0.1
$ conan editable add .
$ cd ..
$ mkdir libb && cd libb && conan new cmake_lib -d name=libb -d version=0.1 -d requires=liba/0.1
```

This will use the ``cmake_layout()`` which is already ready to work as editable. Internally it defines something like:
```python
conanfile.cpp.source.includedirs = ["include"]

    if multi:
        conanfile.cpp.build.libdirs = ["{}".format(build_type)]
        conanfile.cpp.build.bindirs = ["{}".format(build_type)]
    else:
        conanfile.cpp.build.libdirs = ["."]
        conanfile.cpp.build.bindirs = ["."]
```
To take into account that libdirs and bindirs will be in different locations depending on the CMake generator used.


Please check that and let us know if that helps.

**Comment by dragananinkovic** [comment]
Thank you for your answer, I fixed the issue!

**Comment by memsharded** [comment]
Great, happy that it works now.

I am closing the ticket as resolved then, don't hesitate to create new tickets for any further question or issue. Thanks for your feedback!
