### ISSUE TITLE
[feature] PkgConfigDeps `pkg_config_name` property as empty

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#17049]
### What is your suggestion?

It'd be useful to have the mechanism to avoid the creation of any PC file. For instance:

```python
    def package_info(self):
        self.cpp_info.set_property("pkg_config_name", "")
```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Suggestion: Is there prior art to have something be disabled by passing an empty string? (Outside the CLI options like `-tf`) I ask to know if we have thought about instead of `""`, if passing `None` would be better/feasible

**Comment by franramirez688** [comment]
The problem that I see with the None value is when you read that property from the Conan side it'll be difficult (but not impossible for sure) to distinguish between the property was set to None or was not declared.

**Comment by memsharded** [comment]
We have the ``set_property("cmake_find_mode", "none")`` to disable the generation of CMakeDeps xxx-config.cmake files.

**Comment by ErniGH** [comment]
The test here #17159  verifies that if the component and package names match, the component is deterministically prioritised. In this case, we can assume that removing the line `self.cpp_info.set_property("pkg_config_name", "")` would maintain the expected behaviour.
