### ISSUE TITLE
[question] Editable mode without CMakeDeps

### ISSUE THREAD

**Issue by BjarneLorenzen** [conan-io/conan#17047]
Hi all, 
im integrating Conan into an existing project and am therefore not using CMakeDeps to generate the xxxx-config.cmake files for the modules, but already existing ones.
In the conanfiles for each package, the `package_info` is therefore defined as:

``` python
def package_info(self):
    #path to the .cmake files in the package
    self.cpp_info.builddirs = [f"lib/cmake/{self.name}-{self.version}"] 
    self.cpp_info.set_property("cmake_find_mode", "none")
```
this works fine, but fails in editable mode, since the location of the .cmake files, headers and libs is different in a local build than in an installed package.

The current idea is to check wether the package is in editable mode during the build, pass a flag/option to CMake and then set the paths in the .cmake files accoringly.
Checking wether the package is in editable mode while building it would require calling conan inside the conanfile, which accoriding to the docs is _forbidden practice_. 
(`if os.path.abspath(__file__) in str(subprocess.check_output(['conan'], ['editable'], ['list'], ['-f'], ['json'])):` works fine though)

Is there any straight forward way to make it work?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @BjarneLorenzen 

Thanks for your question.

> The current idea is to check wether the package is in editable mode during the build, pass a flag/option to CMake and then set the paths in the .cmake files accoringly.

The idea is that ``editable`` packages should be transparent for the consumers of these packages.

This can be achieved with the correct definition of the ``layout()``  method, specifically the ``self.cpp.build`` like in https://docs.conan.io/2/tutorial/developing_packages/package_layout.html#cpp-source-and-cpp-build

So the same ``self.cpp_info.builddirs = [f"lib/cmake/{self.name}-{self.version}"] `` that you do in ``package_info()``, something similar should be done in ``layout()``:

```python
def layout(self):
    self.cpp.build.builddirs = ["path/to/my/xxxx-config.cmake"] 
```

Please try that and let us know.

**Comment by BjarneLorenzen** [comment]
> Please try that and let us know.

Thanks @memsharded!  I'll have a look at it

**Comment by memsharded** [comment]
Hi @BjarneLorenzen 

Did you manage to have a look? Any further question? Thanks for your feedback.

**Comment by BjarneLorenzen** [comment]
Hi @memsharded 
I didn't get to try it, but in the meantime we moved everything to `CMakeDeps`, so it's not a problem anymore from my side. Thanks!

**Comment by memsharded** [comment]
Sounds good, then I will close this ticket at the moment, please don't hesitate to re-open or create new tickets if necessary for this or any other further question. Thanks for the feedback!
