### ISSUE TITLE
conan 2.0 replacement for conan 1.0 get command

### ISSUE THREAD

**Issue by rajesh-kareti-infovision** [conan-io/conan#17058]
### What is your question?

how to get the recipe file for a packgae in conan 2.0 
like
conan 2.0 replacement for conan 1.0 get command

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rajesh-kareti-infovision 

Thanks for your question.

There is no direct replacement for the ``conan get`` command in Conan 2.

To know which folder has some recipe (including the conanfile in case you want to check it); the recommendation would be:
```
conan cache path mypkg/myversion
```
And it will return the folder containing the conanfile.py.

**Comment by rajesh-kareti-infovision** [comment]
Thanks. This has solved my issue

**Comment by memsharded** [comment]
Thanks for the feedback!

Just in case. Conan 2 defines new tools and ways of doing this. If you were using ``conan get`` to do some operation in CI, this is probably discouraged in Conan 2. If it was only to list and see the code of some dependency, then it might be ok, but recall that the cache is read-only, it is forbidden to modify files inside the cache. Feel free to open new tickets for any further question you might have.
