### ISSUE TITLE
CMakeDeps - Enumerating dependencies

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#17059]
Hello 

conan 2.4.0

I use the CMakeDeps generator to be able to use find_package(...) in my consumer project.
This works very nicely.

I would like to be able to enumerate all dependencies of targets produced by find_package(...).

For example `find_package(CURL CONFIG REQUIRED)` produces the target `CURL::libcurl`.

Doing `get_target_property(TARGET_DEPENDENCIES "CURL::libcurl" LINK_LIBRARIES)` produces nothing.
Is there a way to enumerate the dependencies for CURL::libcurl?

I realize that this is a borderline generic cmake question. But maybe the answer lies in the way CMakeDeps generate the required cmake files for find_package(...)

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Thanks for your question.

The thing is that ``CURL::libcurl`` might be an ``INTERFACE`` target that depends on other internal targets like ``CONAN_LIB::Curl_libcurl``, which is the actual compiled library.

If you do instead:
```
get_target_property(TARGET_DEPENDENCIES "CURL::libcurl" INTERFACE_LINK_LIBRARIES)
message(STATUS "TARGET_DEPENDENCIES ${TARGET_DEPENDENCIES}")
``` 
then it will list something like:
```
$<$<CONFIG:Release>:>;$<$<CONFIG:Release>:CONAN_LIB::libcurl_CURL_libcurl_libcurl_RELEASE>;CURL::libcurl
```

**Comment by memsharded** [comment]
In any case, why would you want to enumerate the target dependencies for? What would be the use case or issue you are trying to solve?

**Comment by klausholstjacobsen** [comment]
My end goal is to create a launch.json file for adding various gdb launch configurations (launch, attach and core dump analysis) for vscode. 
In order to that I need to set-up solib search paths for gdb and add this path to launch.json. 

My intend is to do this by generating a json file during cmake configure that contains info about all directories for shared library targets as well as shared library conan packages. Then this json file can be referenced directly from launch.json.

I realize that I can also create a generic conan generator to generate a separate json file for conan info during conan install.

Yes, I can also activate the conan run environment. That will set-up LD_LIBRARY_PATH for all conan shared library packages.
But that requires our developers to do this before starting vscode, and I do not want to add that requirement to their development start-up procedure, because they would have to first run conan install, and then source conanrunenv.sh.

Any other methods?

Regards
Klaus

**Comment by memsharded** [comment]
> My intend is to do this by generating a json file during cmake configure that contains info about all directories for shared library targets as well as shared library conan packages. Then this json file can be referenced directly from launch.json.

Wouldnt this be easy to generate within Conan? Just a few lines in ``generate()`` method that iterates the ``self.dependencies`` and add the ``bindirs``

> I realize that I can also create a generic conan generator to generate a separate json file for conan info during conan install.

Actually, the ``CMakeToolchain`` generated ``conan_toolchain.cmake`` creates a ``CMAKE_MSVC_RUNTIME_LIBRARY`` variable that list all the directories containing shared libraries, maybe this can help?

For VSCode, if using the CMake presets, Conan is generating presets that contain the ``buildenv`` environment variables for the ``configure`` and ``build`` presets and the ``runenv`` environment (this will contain the LD_LIBRARY_PATH of the host dependencies) in the ``test`` presets.

Please let me know if this helps.

**Comment by klausholstjacobsen** [comment]
Ohhhhh yes now I see the `CONAN_RUNTIME_LIB_DIRS` in the conan_toolchain.cmake.

I have already traveled down the generate/generator path. All required info is readily available there. The drawback for me is that then my consumer project target info and the conan target info is separated. In an ideal world I would have liked to be able to generate one json file containing all direct and transitive dependencies (and their runtime dirs) for each of my consumer project executable targets. 
But the options you presented are not bad.

Thanks a lot for your help....again!

//Klaus

**Comment by memsharded** [comment]
>  The drawback for me is that then my consumer project target info and the conan target info is separated. In an ideal world I would have liked to be able to generate one json file containing all direct and transitive dependencies (and their runtime dirs) for each of my consumer project executable targets.

I didn't fully understand this path, but don't worry, if you are good with the current solution, I am happy too! :)
