### ISSUE TITLE
[question] build-scripts with options

### ISSUE THREAD

**Issue by cwsamuelson** [conan-io/conan#17066]
### What is your question?

I'm still learning Conan2; as far as I can tell it's much better, but also somewhat more complex, so please help fill in any gaps I'm missing here.

I'm creating a small package with some cmake build scripts, and trying to leverage options for slightly different tools available.  These options are not strictly necessary, but they imply additional requires that will need to be managed, so I'm using it to silo those additional dependencies when they're not needed.

I'm attempting to add a `test_package` that accounts for these options; checking that the expected scripts are available, but only when the option is set.

What I found is when I run `conan create . -o A=True`, the profile will list the option as expected, but anytime I try to inspect the option in my `conanfile.py`, it will list as the default value(False); if I change the default, everything functions as I expect.

This is very strange behavior!  If the conanfile cannot determine what options were requested/set, then what's the point of options altogether?

After some experimentation, I determined this is only true when `package_type = 'build-scripts'`.  This is definitely a feature of conan2 I'm still learning, so likely the gap exists here.
I found this documentation: [Package Type Trait Inferring](https://docs.conan.io/2.5/reference/conanfile/methods/requirements.html#package-type-trait-inferring).  But I fail to see what part gives this behavior.  It specifically says: `build-scripts: headers=False, libs=False, run=True, visible=False`, but headers, libs, run, and visible would not affect something like this, as far as I know.

Is this a bug in conan? or a bug in my mental model?

I do have a minimal example I used to determine the source of the problem,  if there's interest in seeing that, I can double-check and provide it.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @cwsamuelson thanks a lot for your question.

The main confussion here seems to be in what context your package is. `build-scripts` are usually required as `self.tool_requires("mybuildscript/1.0")`, which means that they'll be placed in the `build` context of the Conan graph (Ie, what machine you'll be compiling in, See https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html and maybe https://docs.conan.io/2/tutorial/consuming_packages/use_tools_as_conan_packages.html for some context on.. contexts)

This is to show that the reason you're not seeing the options effect is that by default, CLI arguments apply only to the host context (What machine you're compiling for. When not corsscompiling, these 2 are identical, but Conan still makes the distinction internally)

Running `conan create -h` we can in fact see that
```
  -o OPTIONS, --options OPTIONS
                        Apply the specified options. By default, or if specifying -o:h (--options:host), it applies to the host context. Use -o:b
                        (--options:build) to specify the build context, or -o:a (--options:all) to specify both contexts at once. Example: -o
                        pkg:with_qt=true
  -o:b OPTIONS_BUILD, --options:build OPTIONS_BUILD
  -o:h OPTIONS_HOST, --options:host OPTIONS_HOST
  -o:a OPTIONS_ALL, --options:all OPTIONS_ALL
```

This means that if you want to apply options for your build-scripts, you'll need to either pass it as `-o:b A=True` in your CLI, or have the option set in your build profile


I hope this helps, let me know if you have any further questions, thanks! :)

**Comment by cwsamuelson** [comment]
Hi @AbrilRBS, thanks so much for explaining this to me.  I haven't done any cross-building, and therefore forgot about distinguishing between host and build profiles!  This makes a lot of sense.  I haven't yet tested it (busy with other work), but with your explanation, I have no doubt that will correct it.  I'll likely be putting it into a profile or something to help me not forget for that package.

Thanks for your help!
