### ISSUE TITLE
[bug] Xcode16 not recodnized

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#17064]
### Describe the bug

[INFO] Creating default profile...
Found apple-clang 16.0
apple-clang>=13, using the major as version
Profile created with detected settings: /Users/paulo/.conan/profiles/default
[INFO] Installing darwin toolchain...

WARN: **************************************************
WARN: *** Conan 1 is legacy and on a deprecation path **
WARN: *********** Please upgrade to Conan 2 ************
WARN: **************************************************
ERROR: Invalid setting '16' is not a valid 'settings.compiler.version' value.
Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1', '10.0', '11.0', '12.0', '13', '13.0', '13.1', '14', '14.0', '15', '15.0']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

**Comment by memsharded** [comment]
Thanks for the feedback @paulocoutinhox 

This has already been added in https://github.com/conan-io/conan/pull/16980, and it is scheduled for next Conan 1.X release which will be 1.66.

In the meantime, recall that you can add it to your own ``settings.yml`` to unblock that.

**Comment by paulocoutinhox** [comment]
Thanks @memsharded
