### ISSUE TITLE
[question] Conan 2 Migration - Conan Home/Other Settings

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#17071]
Hello, working on migrating my company to Conan 2.x.

In our Jenkins setup multiple jobs building new Conan packages could end up being tasked to the same agent. In order to encapsulate each build in its own little world, we have historically done the following with Conan 1 within the pipeline:

1. Update CONAN_USER_HOME environment variable to a subdirectory of the Jenkin's build workspace
2. Do a `conan config install` from a Git repo into that new home directory
3. Update the storage path (now core.cache:storage_path) to be a subdirectory within the new CONAN_USER_HOME (again, within a subdirectory of the Jenkin's build workspace)

I'm seeing 2 initial issues:
1. Even though I update CONAN_USER_HOME, when I run `conan config home` it shows me the default home directory, not what I just changed via environment variable
2. Now that `conan config set` no longer exists, I'm not sure how to override the default storage path getting pulled in via the global.conf in the Git repo when doing the `conan config install`

Looking at the documentation I thought I could use the `--core-conf` parameter somehow to set the storage path override but had no luck.

Thank you in advance for any help!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @radonish 

Thanks for your questions.

> CONAN_USER_HOME

In Conan 2, the env-var has been renamed to ``CONAN_HOME`` only. This was simpler, but also nice to be able to have both Conan 1 and Conan 2 co-existing in the same machine. Please try that.


> Now that conan config set no longer exists, I'm not sure how to override the default storage path getting pulled in via the global.conf in the Git repo when doing the conan config install

The idea is that the conf can be defined in the ``global.conf``, which can be installed with the ``conan config install``.
Recall that ``global.conf`` is also a Jinja2 template, and it has defined the ``conan_home_folder`` variable, so you can refer to it inside the ``global.conf`` as ``{{os.path.join(conan_home_folder, "myfolder")}}``


In any case, why would you like to change the storage path? by default it will be already a subdirectory inside the CONAN_HOME, so it is not clear what would be the advantage to set it to a different subdirectory.

**Comment by radonish** [comment]
Hello @memsharded, thanks for your response.

Oops, I will update from CONAN_USER_HOME to CONAN_HOME - that was the problem.

In regards to the storage path the issue is we have both developers and our Jenkins pipelines using the `conan config install` command to install our Conan settings from a Git repo. Desire varies a little for developer vs. Jenkins pipeline. Developers use the default Conan home directory but specify a separate path for Conan storage due to space limitations in user home directories. We want Jenkins to encapsulate everything within the running job's workspace.

Developer:
Conan home directory: ~/.conan2
Conan storage directory: /different/share/with/more/storage/allocation/conan_data2

Jenkins:
Conan home directory: /path/to/jenkins/workspace/.conan2
Conan storage directory: /path/to/jenkins/workspace/.conan2/data

In light of losing the `config set storage.path=...` capability I may just default our storage directory to what works for Jenkins and have developers manually update their global.conf since the `conan config install` is something that is just done by new developers during setup or in the rare case we update the Conan settings repo.

**Comment by memsharded** [comment]
Ok, thanks very much for the explanation.

So it means that jenkins could run with the default (the ``data`` is just call ``p``, but that is good to keep paths short, specially for Windows), so no real difference here.

If there is a single thing that you could query in your developer machines, you can always query for it in the ``global.conf`` file:
```
{% if !os.getenv("CI") %}
core.cache:storage_path=/path/to/developer/cache
{% else %}
core.cache:storage_path={{conan_user_home}}/data  # but this won't change much from the default
{% endif %}

There are typically a bunch of things that can be checked that are specific for CI machines, different to developers, so I think it should be possible to automate this, so no need for developers to do an extra step.

In the worst case, I'd probably have them to ``conan config install`` a different thing, and I'd guarantee that this keeps in sync with my CI config install.

**Comment by radonish** [comment]
Exactly, @memsharded - I agree that it can probably be scripted, based on something in the environment.

Your earlier reference to having Jinja2 as an option made me realize it would also be an opportunity to add the developer's username to the storage path, helping us with an unrelated use case that has required manual configuration update: on rare occasion 2 developers are sharing a machine and thus, the /different/share/with/more/storage/allocation/conan_data2 storage path can conflict between those 2 developers. Now, with Jinja2, we could include the username and avoid the need for manual developer configuration update.

Thanks for all of your help!

**Comment by memsharded** [comment]
Exactly, using something like ``os.getenv("USERNAME")`` might allow you to have parameterized paths.
