### ISSUE TITLE
[question] `conan install ... --build=missing` not building unbuilt dependencies.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#17079]
Hello,

So, I'm trying to run this command:
![image](https://github.com/user-attachments/assets/5d212e27-b61e-4e6f-886a-3c09f949cc74)
`libpng` depends on `zlib` which is in the cache:
![image](https://github.com/user-attachments/assets/be5ab911-7d14-4412-bce2-7690bb017c3b)

From my understanding, the `--build=missing` is supposed to build dependencies whose binaries are missing.  However, I get the following error instead:
![image](https://github.com/user-attachments/assets/79af262d-d6d1-4b36-a0d5-2b58cbf698ec)

The missing `p` folder in the cache means that the dependency is not being built on demand as expected.

Sorry for posting text as screen caps, but Microsoft's p.o.s. Remote Desktop for some reason decides to not copy whatever I copy in the remote system.

The question is: how do I make Conan build missing dependencies on demand?

thanks in advance,

PC

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PauloCarvalhoRJ 

Thanks for your question.

I think there might be something not behaving quite well, like some cache corruption or something like that. Indeed this shouldn't happen, Conan things that the package exists and it is there, but it seems that something has removed it from the cache, but not from the DB that stores the packages in the cache.
Can you please try wiping the cache (or just testing with a new temporary cache with ``CONAN_HOME=....`` env-var)?

**Comment by PauloCarvalhoRJ** [comment]
Hi, @memsharded ,

> some cache corruption

Spot on!  I deleted everything inside the cache directory, re-`conan install`-ed and re-`conan export`-ed the dependencies and voilà: it worked like charm.  I've never paid much attention to the `cache.sqlite3` file until now.  It would be good to have some way to fix it instead of deleting the entire cache.  Qt, VTK and ITK for example take quite a while to build.

thank you again,

PC
