### ISSUE TITLE
[question] How do i mark subsettings as compatible after adding user settings?

### ISSUE THREAD

**Issue by sveinuah** [conan-io/conan#17075]
### What is your question?

In order to support multiple, incompatible, Linux armv8 platforms, I added another sub-setting to `settings_user.yml`:
```yml
# Example settings_user.yml
arch:
    armv8:
        platform: [null, myplatform1, myplatform2]
```

To build for these platforms, I also added profiles that define `arch.platform=myplatform1` and `myplatform2` respectively.
`myplatform1` is the old platform, where all previous dependencies were built with `arch=armv8` only. While `myplatform2` is the new platform, with a new toolchain and sysroot.

In an attempt to re-use the old dependencies, I did try to set `<dep>/<version>:arch.platform=None`, as seen below. But I could  not get this to work with either `None`, `{{ None }}`, `null` or `"" `
```
# Attempt at overriding arch.platform for dependency
[settings]
os=Linux
arch=armv8
arch.platform=myplatform1

dep1/x.y:arch.platform=None
```
Is there a way to mark dependencies built before this sub-setting was introduced compatible with `arch.platform=myplatform1`, while keeping them incompatible with `arch.platform=myplatform2`?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sveinuah 

Thanks for your question.

I think you might want to check the ``compatibility.py`` plugin: https://docs.conan.io/2/reference/binary_model/custom_compatibility.html#the-compatibility-py-plugin

This allows for you to do the fallback logic you want, while prioritizing packages that have already been built for the new platform settings, quite transparently

Something in the line of adding to the default current compatibility.py:

```python
if arch == "armv8":
        if arch.platform is not None:
            factors.append([{"arch.platform": None}])
```

Please let me know if this helps.

**Comment by sveinuah** [comment]
Hi @memsharded, and thanks for the quick reply!

The code snippet you refer to seems to be placed in `extensions/plugins/compatibility/cppstd_compat.py` in my local version(2.7.1). I did, however, manage to add it to `compatibility.py` with some small modifications. It worked perfectly!

Thanks :)

For those who are interested:

```python
def linux_armv8_platform_compat(conanfile):
    os = conanfile.settings.os
    arch = conanfile.settings.arch
    if os != "Linux" or arch != "armv8":
        return []

    arch_platform = arch.get_safe("platform")
    if arch_platform == "myplatform1":
        return [{
            "settings" : [("arch", arch), ("arch.platform", None)]
        }]
    else:
        return []

```

Then I appended the return value to the default compabilities.

**Comment by memsharded** [comment]
> The code snippet you refer to seems to be placed in extensions/plugins/compatibility/cppstd_compat.py in my local version(2.7.1).

Yes, exactly that is the location. The plugin can be managed, distributed and shared to all the Conan clients with the ``conan config install`` or ``conan config install-pkg`` command, together with all the other Conan configuration.

Note that if you modify the plugin, it will no longer automatically migrate (note the comments in the first line you have to remove), so for future Conan versions that might bring new defaults to compatibility, you might need to check from time to time if you want to incorporate those.

> Then I appended the return value to the default compabilities.

The problem with that approach is that it doesn't compose with the other compatibility ``factors``. So you will lose the default ``compiler.cppstd`` compatibility with your approach (You cannot use a different ``compiler.cppstd`` together with a different ``arch.platform``). To make it jointly compatible, it is better to add the "variation" to the ``factors`` and let the factors be managed below.

**Comment by sveinuah** [comment]
> The problem with that approach is that it doesn't compose with the other compatibility factors. So you will lose the default compiler.cppstd compatibility with your approach (You cannot use a different compiler.cppstd together with a different arch.platform). To make it jointly compatible, it is better to add the "variation" to the factors and let the factors be managed below.

Ah. I see. I'll integrate it with the rest then.

> Note that if you modify the plugin, it will no longer automatically migrate (note the comments in the first line you have to remove), so for future Conan versions that might bring new defaults to compatibility, you might need to check from time to time if you want to incorporate those.

Thanks for the heads up! I'll keep that in mind.
