### ISSUE TITLE
[question] Debugging/Develope custom commands with VSCode

### ISSUE THREAD

**Issue by punicawaikiki** [conan-io/conan#17070]
### What is your question?

Hi All,
I am currently playing around with the conan custom commands.
When I create a conanfile.py I use often the possibility to develope with the help of VSCode python debugger as already mentioned in #10055.
Unfortunately this is not working for conan custom commands, the code will be executed with this line:
https://github.com/conan-io/conan/blob/develop2/conan/cli/command.py#L171
but is ingoring my breakpoints within my custom command.

So does anyone have a good idea?
How do you develope custom commands?

Versions I've tested:
os: Ubuntu 20.04
conan: 2.7.1
Python: 3.10.14 and 3.12.6

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @punicawaikiki 

Thanks for your question.

What happens if you add a ``breakpoint()`` in your custom command? is it also ignored?

Custom commands are no much different than conanfiles, they are dynamically loaded, but that is all. If you can step-into conanfiles, in theory you should be able to step and debug custom commands.

**Comment by punicawaikiki** [comment]
Sorry forgot to mention that...

I've also tried with adding a breakpoint() to the code and it doesn't work either.

**Comment by memsharded** [comment]
I am afraid I don't know enough about VSCode configuration for debugging, sorry.

In my case, when running ``conan ...`` (Conan installed with ``pip install -e .`` as editable) with a ``breakpoint()`` in a custom command in my cache, it stops at that breakpoint and shows the (Pdb) prompt.

**Comment by punicawaikiki** [comment]
After trying some time with pdb, I am not be able to get the breakpoint hit with pdb. I am not familiar with pdb, can you explain your workflow with pdb please?

What I've done:
- clones conan repository
- installed it like in the contribution guide with pip install -e
- checked conan version with "conan --version"

**Comment by memsharded** [comment]
Exactly like that, I put the breakpoint() in the custom command, launch it with ``conan custom:command args`` and it stops and open (Pdb) in the terminal

**Comment by punicawaikiki** [comment]
So I got it finally working (vscode and pdb), thanks for your help!

It was my mistake (as expected) I didn't download the conan repo itself, stepped into the repo and installed it with pip install -e ., instead I've installed it with pip install -e git+<conan-repo-url> and this was not working ....

thanks a lot!

**Comment by memsharded** [comment]
Great, happy that it works now, thanks for the feedback!
