### ISSUE TITLE
[question] Can I install packages to project director by setting a variable?

### ISSUE THREAD

**Issue by aiyolo** [conan-io/conan#17077]
### What is your question?

I need to deploy my software to a machine that can't connect to  the internet, so I wish that I can I can dowload package to project subdirector such as thrid-party directory, once the software can built on my machine, I can copy the whole project directory including the package directory to the deployed machine? 
My question is how can I download these packages to a specified directory?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aiyolo 

Please have a look to https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html

Note in the post there explain there can be some limitations, as paths cannot be relocated in some scenarios (shell scripts)

Another possibility is to use the ``conan cache save/restore`` to move packages from one machine with internet to another one without internet.

**Comment by aiyolo** [comment]
thank you
