### ISSUE TITLE
[feature] C++26 support

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#17073]
### What is your suggestion?

gcc-14+ and clang-17+ support C++26 already with `-std=c++26`. It would be great to be able to use it with Conan and test new language features that are being shipped already.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
In fact, clang has this to say
```
...
note: use 'c++23' for 'ISO C++ 2023 DIS' standard
note: use 'gnu++23' for 'ISO C++ 2023 DIS with GNU extensions' standard
note: use 'c++2c' or 'c++26' for 'Working draft for C++2c' standard
note: use 'gnu++2c' or 'gnu++26' for 'Working draft for C++2c with GNU extensions' standard
```

See https://godbolt.org/z/nfY6q96Gq, TIL. It's interesting to see that this did not happen for C++ 23, which was marked as `c++2b` from clang 12 to clang 16, and in clang 17 it was marked as `c++17`

But, this looks to be an internal name only as per https://discourse.llvm.org/t/rfc-lets-just-call-it-c-26-and-forget-about-the-c-2c-business-at-least-internally/70383, we'll need to take a closer look, as they make a point to explicitly not document it (Even if it shows up in the help message?)

(Gcc has supported both syntaxes at the same time from the begining in the last few std versions)

**Comment by AbrilRBS** [comment]
@mpusz thanks for taking the time to request C++26 support. After considering my previous message with the team, we've decided to go ahead and add support for C++26  for clang, gcc and apple-clang for now. If there are any other compilers that currently have C++26 support under a flag, thanks!
