### ISSUE TITLE
[bug] Conan 2.8.0 change in dependencies package_id - bootstrap?

### ISSUE THREAD

**Issue by jwatson0** [conan-io/conan#17086]
### Describe the bug

Today, with the release of conan 2.8.0 I noticed a change in the way dependencies are calculated by conan for an internal build tool that we build with conan.  It may be related to the new bootstrapping feature, as this build tool depends on a version of itself to build.

The source is available here, but you may not be able to build it without access to our internal artifactory server.  This tool and some of its dependancies are not on Conan Center.
https://github.com/StanzaOrg/slm

The problem appeared this morning on our CI server with this message:
```
slm/0.6.13: WARN: Can't find a 'slm/0.6.13' package binary 'a4b54cca2e36f0953babee402f42eb85e7a65aa7' for the configuration:
[settings]
arch=x86_64
os=Linux
[python_requires]
lbstanzagenerator_pyreq/0.6.Z

ERROR: Missing prebuilt package for 'slm/0.6.13'. You can try:
    - List all available packages using 'conan list "slm/0.6.13:*" -r=remote'
    - Explain missing binaries: replace 'conan install ...' with 'conan graph explain ...'
    - Try to build locally from sources using the '--build=slm/0.6.13' argument
```

`conan graph explain` shows:
```
======== Retrieving and computing closest binaries ========
Missing binary: slm/0.6.13
With conaninfo.txt (package_id):
[settings]
arch=x86_64
os=Linux
[python_requires]
lbstanzagenerator_pyreq/0.6.Z

Finding binaries in the cache
Finding binaries in remote artifactory

======== Closest binaries ========
slm/0.6.13
  slm/0.6.13#2080e677a82bd722df848c90c1251eb7%1724976507.666 (2024-08-30 00:08:27 UTC)
    slm/0.6.13#2080e677a82bd722df848c90c1251eb7:0d1c040c4da7ee20a770f14b6c9dddbd8cebeee5
      remote: artifactory
      settings: Linux, x86_64
      requires: http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235:b647c43bfefae3f830561ca202b6cfd935b56205
      python_requires: lbstanzagenerator_pyreq/0.6.Z
      diff
        dependencies
          expected: None
          existing: http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235:b647c43bfefae3f830561ca202b6cfd935b56205
        explanation: This binary has same settings and options, but different dependencies
```

Downgrading to conan 2.7.1 works as it did previously.

This reference to an `http_parser/2.9.4` did not appear in the past.

The `slm` conanfile requires a previous version of itself to build:
```
    self.tool_requires("slm/0.6.13")
```
(Requiring on a version range with >= creates a dependency loop, so we made a specific version dependency.  I'm interested in the new bootstrap feature to improve this)
(I also notice that this tool depends on several previous versions of itself through inheritance, and I'm working to remove those)

The other regular dependencies are required using `unrelated_mode` so that they aren't required to use the final package:
```
    self.requires(f"{pkgname}/{pkgver}", package_id_mode="unrelated_mode")
```
This may not be the ideal way to handle these dependencies, but it was working before conan 2.8.0.

I'm not sure if this is affecting any recipies on Conan Center.

For now, I'm using conan 2.7.1 successfully for our builds.

### How to reproduce it

```
> git clone git@github.com:StanzaOrg/slm.git
> cd slm
> make
# ERROR: Missing binary: slm/0.6.13:a4b54cca2e36f0953babee402f42eb85e7a65aa7

# debugging
> cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu

> python --version
Python 3.12.1

> source venv/bin/activate
> export CONAN_HOME=$PWD/.conan2
> pip list
 pip list
Package            Version
------------------ -----------
certifi            2024.8.30
charset-normalizer 3.3.2
colorama           0.4.6
conan              2.8.0
distro             1.8.0
fasteners          0.19
idna               3.10
Jinja2             3.1.4
jsons              1.6.3
MarkupSafe         2.1.5
patch-ng           1.18.0
pip                23.2.1
python-dateutil    2.9.0.post0
PyYAML             6.0.2
requests           2.32.3
six                1.16.0
typish             1.9.3
urllib3            1.26.20

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: pip install --upgrade pip

> $ conan --version
Conan version 2.8.0

> conan graph explain -pr:b linux-x86_64-default -pr:h linux-x86_64-gcc-11 -vtrace .
# ...
======== Closest binaries ========
slm/0.6.13
  slm/0.6.13#2080e677a82bd722df848c90c1251eb7%1724976507.666 (2024-08-30 00:08:27 UTC)
    slm/0.6.13#2080e677a82bd722df848c90c1251eb7:0d1c040c4da7ee20a770f14b6c9dddbd8cebeee5
      remote: artifactory
      settings: Linux, x86_64
      requires: http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235:b647c43bfefae3f830561ca202b6cfd935b56205
      python_requires: lbstanzagenerator_pyreq/0.6.Z
      diff
        dependencies
          expected: None
          existing: http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235:b647c43bfefae3f830561ca202b6cfd935b56205
        explanation: This binary has same settings and options, but different dependencies

# downgrade conan and retry
> pip install conan==2.7.1
> make
# success
```

**Comment by memsharded** [comment]
Hi @jwatson0 

Thanks for your report.

Indeed something was changed regarding the bootstrapping capabilities in Conan 2.8, in this PR: https://github.com/conan-io/conan/pull/16870

The intention was to allow some bootstrapping, basically depending on yourself in some situations that were not allowed in the past, and they raised exceptions reporting an infinite dependency loop.
But I still don't understand how this could be creating different ``package_id``, let's see if we can understand why.

A few questions:

- Is the ``requires`` from ``slm`` to ``http_parser/2.9.4`` also with the ``unrelated`` mode?
- This doesn't seem to match from the ``existing: http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235:b647c43bfefae3f830561ca202b6cfd935b56205``, it means that the previous binary for ``slm`` was actually depending on the very specific ``http_parser`` down to the revision and package_id, so like ``full_mode``, not unrelated.
- Does ``http_parser`` has other dependencies or transitive dependencies? 
- It would be very useful to have a full graph dump of the command that creates the first ``slm/0.6.13: WARN: Can't find a 'slm/0.6.13' package binary 'a4b54cca2e36f0953babee402f42eb85e7a65aa7'``. Using a ``conan graph info --format=json`` for the exact same inputs would be very useful, specially if we can have the results both for Conan 2.7.1 and Conan 2.8.0 and compare the dependency graph.

Do you think it would be possible to have the dependency graphs? Many thanks for your feedback.

**Comment by memsharded** [comment]
I have done a full diff for the release, and realized about this other change: https://github.com/conan-io/conan/pull/16987

This was declared a fix, it was solving some misbehaviors of ``requires(..., package_id_mode="xxxx")`` when there are diamonds structures in the dependency graph, that priority was not being given to the most downstream consumer. 

This could explain the difference in the ``package_id``, and it probably meant that your previous binary was buggy, affected by that bug that PR was fixing:

- Your previous binary for ``slm`` actually depended on ``http_parser``
- But it seems your intention was indeed that it should be independent ``unrelated_mode``
- Now, with the Conan 2.8 fix, the binary that is being requested is actually independent of ``http_parser`` but it hasn't been built yet, but it is the correct binary with the correct ``package_id`` that should have been computed before.

Please let me know if this makes sense.

**Comment by jwatson0** [comment]
> Is the requires from slm to http_parser/2.9.4 also with the unrelated mode?

That was the intent.  We are dynamically adding these dependencies in `requirements()` from reading another file, we attempt to set unrelated_mode on all of them, but it's possible that http_parser got skipped somehow.  Looking at the older packages with conan 2.7.1, I see the http_parser requirement, but it didn't fail to resolve before.

```
> conan --version
> conan list slm/0.6.17:*
Local Cache
  slm
    slm/0.6.17
      revisions
        d88b5f990a56b0ef5017f0e554146357 (2024-09-30 18:03:11 UTC)
          packages
            0d1c040c4da7ee20a770f14b6c9dddbd8cebeee5
              info
                settings
                  arch: x86_64
                  os: Linux
                requires
                  http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235:b647c43bfefae3f830561ca202b6cfd935b56205
                python_requires
                  lbstanzagenerator_pyreq/0.6.Z
```

> Does http_parser has other dependencies or transitive dependencies?

Not that I see:
```
> conan list http_parser/2.9.4:*
Local Cache
  http_parser
    http_parser/2.9.4
      revisions
        38bd28da476afbba5e4adcdd726ea235 (2024-05-09 21:11:18 UTC)
          packages
            b647c43bfefae3f830561ca202b6cfd935b56205
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: gcc
                  compiler.version: 11
                  os: Linux
                options
                  fPIC: True
                  shared: False
```

> full graph dump

Here are the graph outputs.  I see in the 2.8.0 output, http_parser is listed as unrelated_mode, but it the 2.7.1 output, it's listed as full_mode.  Maybe that's due to the bug you fixed that now shows different behavior.  It seems that perhaps my conanfile code assigned unrelated_mode in the past, but that assignment for http_parser wasn't correctly applied until now?
[conangraphinfo_2_7_1.txt](https://github.com/user-attachments/files/17195777/conangraphinfo_2_7_1.txt)
[conangraphinfo_2_8_0.txt](https://github.com/user-attachments/files/17195778/conangraphinfo_2_8_0.txt)

> Now, with the Conan 2.8 fix, the binary that is being requested is actually independent of http_parser but it hasn't been built yet, but it is the correct binary with the correct package_id that should have been computed before.

I think that's right.  The previous bug was probably masking the http_parser requirement and I didn't notice that it was there.  I will address that and rebuild the slm package, making sure that it doesn't have the http_parser requirement.

Is there a way that I can require the older slm package even though it has an http_parser requirement?
I had been using
```
self.tool_requires("slm/0.6.13")
```
Can I somehow add an override to tell conan that the slm version with the http_parser requirement is ok to match with?  Can I just add http_parser as a tool_requires also?

Thanks.

**Comment by memsharded** [comment]
> requires
                  http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235:b647c43bfefae3f830561ca202b6cfd935b56205

Yes, this was it, this shows the previous package had the bug, as it was explicitly depending on the full ``http_parser`` reference, even if it had the ``package_id_mode="unrelated_mode"``.

It didn't fail to resolve before because the ``package_id`` resolves in the same way both when you are creating the package and when you are consuming it, so the bug manifests in exactly the same way in both cases.

You would have realized about the bug if you had released a new ``http_parser/2.9.5`` version and it would have raised a "Missing binary" for ``slm`` package even if you defined the "unrelated" mode and that would have been unexpected.

> Maybe that's due to the bug you fixed that now shows different behavior. It seems that perhaps my conanfile code assigned unrelated_mode in the past, but that assignment for http_parser wasn't correctly applied until now?

Yes, that is exactly the previous bug. It was not completely evident, it really only happens if there are diamonds in the dependency graph and there is some other package depending on the ``http_parser``, which in turn is also required by ``slm``. Is this the bug that has been fixed, so now the ``unrelated`` that you defined is really honored, while previously it was being discarded.


>  I will address that and rebuild the slm package, making sure that it doesn't have the http_parser requirement.

I think that is the best way to move forward, rebuild ``slm`` with 2.8 with the correct ``package_id``.


> Is there a way that I can require the older slm package even though it has an http_parser requirement?
I had been using

You would need to explicitly opt-in again into the full mode:
```python
self.requires("http_parser/version", package_id_mode="full_mode")
```

But this is not the behavior you really want, so the best would be to create the new binary for ``slm`` and upload it to the server, then both Conan 2.7 and Conan 2.8 will be able to resolve to the different binaries.

> Can I just add http_parser as a tool_requires also?

Yes, it is possible, see for example https://docs.conan.io/2/examples/graph/tool_requires/different_options.html 
By default the ``tool_requires`` do not affect the ``package_id`` of the consumers.

**Comment by memsharded** [comment]
As a side note, in most cases the ``requires("dep/version", package_id_mode=xxx)`` approach is not the recommended approach in most cases, instead:

- the default behavior of Conan 2 is pretty balanced, being correct for the vast majority of cases if the versioning is followed correctly, and also being efficient and avoiding too many unnecessary builds from sources.
- If necessary to change something because a different overall versioning scheme is used, then the global configuration might be the way to go.
- If necessary to define how some specific packages affect their consumers, different to the general defaults, use the class attributes: https://docs.conan.io/2/reference/conanfile/attributes.html#package-id-embed-non-embed-python-unknown-mode
- If necessary how a package is affected by its dependencies prefer the ``package_id()`` approach.
- The ``requires(..., pacakge_id_mode=xxxx)`` might be possibly the last approach.

**Comment by jwatson0** [comment]
Thanks for your suggestions.

**Comment by memsharded** [comment]
Thanks to you for your feedback!

Sorry for the inconvenience that this change has caused, but I hope that getting the originally intended behavior would be worth it.

**Comment by jwatson0** [comment]
Update: removing all `unrelated_mode` settings and using `vendor=True` seems to have addressed the issue and simplified the dependency graph.

**Comment by memsharded** [comment]
> Update: removing all unrelated_mode settings and using vendor=True seems to have addressed the issue and simplified the dependency graph.

So that is what you were trying to achieve with the ``unrelated`` mode? Interesting, yes, in that case, the ``vendor=True`` feature might help with this case.

**Comment by jwatson0** [comment]
Yes, the build of the slm tool uses static libraries, so no dependencies should be needed to use the slm tool as a tool_requires in other packages.  The vendor feature seems to do just what I need for that.
