### ISSUE TITLE
Case insensitivity when exporting package

### ISSUE THREAD

**Issue by tobyas** [conan-io/conan#171]
Hi,
When I export a package which alredy exists with different large or lower case, my package will assume the other package's name. Due to case-sensitivity issues my package won't be exported with the name I gave it. This is problematic when trying to access it with the name I intended for it.
E.g.:
**conan serach** gives us a
Hello/0.1@demo/testing

Trying to **conan export  demo2/testing** a package named hello will result in Hello/0.1@demo2/testing
being created. The way I understand it this is a windows filesystem problem(case-sensitivity). It would be nice if a warning would be generated, informing the user about case problems when creating packages.

**Comment by memsharded** [comment]
So this has been merged to develop, should be released in next 0.8. Finally I implemented an Exception, as Win actually overwrites the full contents of the folder, with possible information loss if different case actually meant different packages. 
Thanks for your feedback!
