### ISSUE TITLE
[question] how can I use attribute exports to pick up the correct file?

### ISSUE THREAD

**Issue by kip3f** [conan-io/conan#17106]
### What is your question?

Each of my packages stores requirements versions in an external file with the same name, e.g.:

PACKAGE A:
exports = config/versions.txt
...
def requirements(self):
    open('config/versions.txt') ...

PACKAGE B:
exports = config/versions.txt
...
def requirements(self):
    open('config/versions.txt') ...
    ...
    self.requires('PACKAGE A')

The problem that I have is that when I try to run conan install command for the conanfile for package B, it's behaving as if the the conanfile for package A is loading up the wrong versions.txt file.  How can I ensure that the conanfile for package A always uses the versions.txt that belongs to package A?  Is there a special prefix that I can prepend to the open() command?  Or is this a defect in the conan install command?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @kip3f 

Thanks for your question.

This should be possible in theory, and each package could have its own and independent ``versions.txt`` and use it without problem.
I think it is a path problem: ``open('config/versions.txt')`` is a relative path, but ``requirements()`` is not guaranteed to execute in a given path, you might need to do something like:
```python
def requirements(self):
    versions = load(self, os.path.join(self.recipe_folder, "config", "versions.txt"))
```

Please try that and let me know.

**Comment by kip3f** [comment]
Thank you, that resolved the issue.

**Comment by memsharded** [comment]
Great, thanks for your feedback!
