### ISSUE TITLE
pylint version bump

### ISSUE THREAD

**Issue by tivek** [conan-io/conan#1710]
requirements.txt should be updated to allow the latest release of pylint.

Conan depends on an older version of pylint 1.6.5, but the tests also pass with the latest pylint 1.7.2 - see [Travis CI](https://travis-ci.org/tivek/conan/builds/272065425) and [AppVeyor](https://ci.appveyor.com/project/tivek/conan/build/1.0.34).

I am already packaging Conan 0.26.0 for Arch Linux in such a way to allow pylint >= 1.6.5. This is maybe too unconstrained. Should we require pylint >= 1.6.5 and < 1.8.0? I don't know if pylint follows semantic versioning.

**Comment by lasote** [comment]
According to the https://github.com/PyCQA/pylint/issues/1650 we can upgrade "safetely" to <= 1.8.0
Would you mind to open a PR? Thanks for you constant effort with this!

**Comment by tivek** [comment]
Pull request open. Thanks for finding out about pylint's versioning scheme!
