### ISSUE TITLE
[feature] Support inverse match with .conanignore

### ISSUE THREAD

**Issue by skycaptain** [conan-io/conan#17120]
### What is your suggestion?

As recommended, we store our Conan config in a distinct Git repository. Since we use many automation tools, we end up with numerous config files and other dotfiles in the repository unrelated to Conan. This repo also serves as a template for other project maintainers, who might add more non-Conan related files. `.conanignore` files are helpful for filtering files to be installed. However, they would be more useful if they supported inverse matching, just like `.gitignore` or `.dockerignore` do. This is especially true for the latter, where it's common practice to ignore all files and only explicitly add those required, e.g.:

```ignore
*
!profiles/
!global.conf
!remotes.json
```

I believe this would make maintaining such a config repository much easier. If third-party libraries are an option, there are [gitignore-compatible parsers](https://pypi.org/project/gitignore-parser/) already available for Python.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @skycaptain thanks a lot for your request. I think this feature makes sense (having conan config remotes alongside other configs is not something we considered when implementing this feature, but I'll let @memsharded chime in about the approach itself!), so I've proposed https://github.com/conan-io/conan/pull/17123

It still needs team review and the approach could be changed in the meanwhile, but this should be released with Conan 2.9 at some point early next month :)

**Comment by memsharded** [comment]
Yeah, makes sense, this can be added, thanks for the feedback!

**Comment by memsharded** [comment]
#17123 was merged, so this will be in next 2.9, thanks for the feedback.
