### ISSUE TITLE
[question] How to flatten profiles with Conan itself?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#17128]
Hi, 
our profiles use a lot of include()s in them. Is there a way to produce the "flattened" version from the profiles, e.g. every include resolved and merged together into a single profile file?
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @harsszegi thanks for the question.

You'd might be looking for the `conan profile show` command ([Docs here](https://docs.conan.io/2/reference/commands/profile.html#conan-profile-show)), which will show the processed profile, and can be supplied as many as necessary.

Let me know if this helps :)

**Comment by harsszegi** [comment]
Awesome, thanks
