### ISSUE TITLE
[question] Handling RPATH in package function

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#17136]
### What is your question?

I'm using a very old library that uses RPATHs all over the place.  I want to build this as a conan package  Because of how it uses the RPATHs it is not relocatable.  However, I discovered the `patchelf` tool (the library only works on linux) that allows for me to update the RPATHs after building.

I added code in the package function that rebases the RPATHs from the `build_folder` to the `package_folder`.  This works great on my local machine.  However, I discovered issues when I upload it and download it on a separate machine.  On the building machine, the package folder is something like `$HOME/.conan2/p/b/packa<hash1>`.  When I download it, it goes to `$HOME/.conan2/p/packa<hash2>`.  The RPATHs in the package are set to the folder that it was built in, not the folder that it is downloaded to.

Obviously there is a problem with how I am approaching this.  Is there a better way to deal with this situation?  From looking at the code and past issues, I can see that the final package folder isn't known until the package is fully built, so I see that I have a chicken and egg problem.  

If I use a different package_id mode, does that only effect the package_id or does it also impact the path in the conan cache?  (Would it be possible to know the final package_folder in the package method if we use a different package_id mode?)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jsallay 

Thanks for your question.

If I understood it correctly, I think this could be a good candidate for the ``finalize()`` feature. Have you checked it? https://blog.conan.io/2024/09/03/New-finalize-method.html

The idea would be that the ``finalize()`` method of your recipe does the ``patchelf`` over a copy of the binaries to be able to force them whatever machine-local absolute paths that old library needs to run locally, but still can use the Conan package to avoid a full rebuild from source for every installation.

Please check it and let me know.

**Comment by jsallay** [comment]
That looks like it will work for me.  Looks like you guys added at just the right time.  I just have one minor issue left.  Let's define a few paths to explain the issue.  For a package called `mypkg` lets have a
`cache_package_folder=$HOME1/.conan2/p/b/mypkg0123456789bc/p`
`installed_package_folder=$HOME2/.conan2/p/mypkgabcdef0123456/p`
`installed_finalize_folder=$HOME2/.conan2/p/mypkgabcdef0123456/p`

Note that `$HOME1` does not have to be the same as `$HOME2` because the package could be built by a different user than it is consumed by.

When I download `mypkg` onto my system it is copied into `installed_package_folder` but the RPATHs point to `cache_package_folder`.  I need to replace all instances of `cache_package_folder` with `installed_finalize_folder`.  To my knowledge, I don't have any way of knowing what the `cache_package_folder` is.

I have a hacky solution of looking for any path that has `.conan2` in it and replacing up to the second `p`.  This feels like a hack.  Is there a more correct way to tell if a package points to a conan cache path?  Is it safe to check for a `.conan2` in the path?  Is there a way that I could somehow include the `cache_package_folder` in the package so that I know what to replace?

**Comment by memsharded** [comment]
> When I download mypkg onto my system it is copied into installed_package_folder but the RPATHs point to cache_package_folder. I need to replace all instances of cache_package_folder with installed_finalize_folder. To my knowledge, I don't have any way of knowing what the cache_package_folder is.

I think this rings a bell. I recall somewhere that an approach to this was adding a fixed and known path, even if it didn't exist in the first initial build ``cache_package_folder``. Then, all subsequents patchelfs do the replacement using the same placeholder.

This shouldn't be an issue even for HOME1, because the package creation process for the package in HOME1 will also do the ``finalize()``, so there will be also another ``installed_cache_folder=$HOME1/....`` with the RPATH that has already been patched.

Maybe @jcar87 recalls this practice?

**Comment by jsallay** [comment]
What I ended up doing was writing a file in the package folder with the path that needs to be replaced.  I don't copy this to the finalize folder so it is transparent to anyone using the package that it is there.  It would be nice if it weren't there, but it's not a big deal.  I'll go ahead and close the issue.

**Comment by memsharded** [comment]
Sounds good, happy to know that the  ``finalize()`` feature helped to implement it.
Thanks for the feedback!
