### ISSUE TITLE
[question] display custom conf_info attribute?

### ISSUE THREAD

**Issue by gabeblack** [conan-io/conan#17135]
### What is your question?
conan version: 2.8.0
python3 version: 3.9.18
OS: Oracle Linux 9.0

My conanfile.py has a `package_info(self):` with the following:

```
    def package_info(self):
        self.conf_info.define('user.mystring', 'hello world!')

```
However, when I run `conan graph info conanfile.py` , it shows: 
```
...
conf_info:
...
```
That is, `conf_info` is empty. How do a set a custom property/attribute where I can inspect the value on the CLI?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gabeblack 

Thanks for your question.

When you are executing ``conan graph info <path/to/conanfile>`` or ``conan install <path/to/conanfile>`` the graph that is computed is the graph of the dependencies of that conanfile. But the local conanfile is not a Conan package, and it doesn't have any consumers, so its ``package_info()`` method is never executed.

You would see that information if you do something like:
```bash
$ conan export .
$ conan graph info --requires=mypkg/version
```
Please let me know if this helps.

**Comment by gabeblack** [comment]
@memsharded Thank you for the prompt reply.

I tried those commands, `conan export .` (ran from where the conanfile.py recipe exists for my package), followed by `conan graph info --requires=grub-fips-mod/2.06` (grub-fips-mod is the name of the package and it's version is 2.06) and it still didn't have anything in conf_info.

**Comment by memsharded** [comment]
Oh, yes, you are right, this is true.

The ``conan graph info`` doesn't install packages at all. Some might be in the cache but not really necessary. So it is impossible to call the ``package_info()``, because there might not be package in the first place. One common case is the ``package_info()`` containing something like a ``collect_libs()`` call, that scan the files in disk to deduce the ``cpp_info.libs`` information.

It is possible to see the info with a ``conan install --requires=pkg/version --format=json``
I have just tried it, and was able to see the value:
```
 "conf_info": {
         "user.myorg:myvalue": "123"
 },
```

**Comment by gabeblack** [comment]
ok -- so there isn't really a way to just query a conan package for userdata/custom attributes without running install?

**Comment by memsharded** [comment]
The full ``package_info()`` contents, no, that is the information of the binary package, and it is necessary to have the package installed in order to get that information. Other details might be available, like settings, options, package_id, dependencies, requires, that is the "graph information", but the "package information" needs the ``conan install`` yes.


In any case, what would be the use case to get that ``conf_info`` that way? The ``conf`` mechanism is designed as a conan-to-conan mechanism, not as a conan-to-user mechanism. If you want to elaborate more on the problem you are trying to solve, there could be other approaches.

**Comment by gabeblack** [comment]
Basically, we have packages that are built from source archives that have varying signatures/methods that identify their version (not as simple as "version 1.0"). These source archives get updated periodically along with their signatures being updated. 

Basically, would like a way to query our conanfile to see if its packages are up-to-date by checking if the packages "source signatures" match the latest source archive signatures. If they don't, then we know it time to point our conan recipes to build new versions and upload them, etc.

 I was thinking to store these "source signatures" in some user-defined attribute that I would be able to query.

**Comment by memsharded** [comment]
> Basically, we have packages that are built from source archives that have varying signatures/methods that identify their version (not as simple as "version 1.0"). These source archives get updated periodically along with their signatures being updated.

Interesting. Is this some information that is common to the different binaries that could be built from the same recipe/sources for different configurations, or it is something that is mostly attached to the source code?

> Basically, would like a way to query our conanfile to see if its packages are up-to-date by checking if the packages "source signatures" match the latest source archive signatures. If they don't, then we know it time to point our conan recipes to build new versions and upload them, etc.

How would you compare this? From the graph info, collecting the data, then checking against your own (non-conan) sources?

I think there might be other mechanisms to gather this data and automate this process efficiently (without having to install the packages):

- Capture the information that you want form those sources in the ``export()`` method, and store it in the ``conandata.yml``, something similar to what is done for ``scm`` data in https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html
- Collect the information you want iterating the dependencies, and getting the ``conan_data`` attribute from each dependency. Using for example a custom ``deployer``, you can ``conan graph info ... --deployer=collect_my_info`` create a custom file in your desired format ready to be used
- If you would like to further automate the checks against the origins, I'd strongly recommend a Conan custom command that encapsulates the building of the graph, the recollection of ``conan_data`` and the checks against the origins, see https://docs.conan.io/2/reference/extensions/custom_commands.html

**Comment by gabeblack** [comment]
> > Basically, we have packages that are built from source archives that have varying signatures/methods that identify their version (not as simple as "version 1.0"). These source archives get updated periodically along with their signatures being updated.
> 
> Interesting. Is this some information that is common to the different binaries that could be built from the same recipe/sources for different configurations, or it is something that is mostly attached to the source code?

The sources can vary -- some are tarballs, some are source rpms provided by vendors. Some sources have a version indicated by the name of the tarball/rpm, others don't have a version or file, but rather we download the archive from the commercial vendor we "select" the version to download, but are simply given a `download.zip` archive without anything indicating a version.

> > Basically, would like a way to query our conanfile to see if its packages are up-to-date by checking if the packages "source signatures" match the latest source archive signatures. If they don't, then we know it time to point our conan recipes to build new versions and upload them, etc.
> 
> How would you compare this? From the graph info, collecting the data, then checking against your own (non-conan) sources?

Yes -- or any other way custom meta-data can be queried.

> I think there might be other mechanisms to gather this data and automate this process efficiently (without having to install the packages):
> 
> * Capture the information that you want form those sources in the `export()` method, and store it in the `conandata.yml`, something similar to what is done for `scm` data in https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html
> * Collect the information you want iterating the dependencies, and getting the `conan_data` attribute from each dependency. Using for example a custom `deployer`, you can `conan graph info ... --deployer=collect_my_info` create a custom file in your desired format ready to be used
> * If you would like to further automate the checks against the origins, I'd strongly recommend a Conan custom command that encapsulates the building of the graph, the recollection of `conan_data` and the checks against the origins, see https://docs.conan.io/2/reference/extensions/custom_commands.html

I'll take a look at those references. Thank you. I'll go ahead and close this as at least there is a way to query by using the `conan install` command. That is definitely not a deal breaker to have to do that.

**Comment by memsharded** [comment]
Good, thanks for the feedback!
