### ISSUE TITLE
CMake preset environment variables aren't set when calling conan build command

### ISSUE THREAD

**Issue by NormanT7** [conan-io/conan#17146]
### Describe the bug

Environment Details: Windows, MSVC compiler, cmake, Conan 2.8.0

I'm using a basic CMake recipe and following [this example](https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#presets-build-environment-presets-run-environment) in the conan docs to set project-specific environment variables in the preset build environment. The relevant portions of the recipe are as follows.

```Python
    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()

        buildenv = VirtualBuildEnv(self)
        buildenv.environment().define("myvariable", "value")
        buildenv.generate()

        tc = CMakeToolchain(self)
        tc.presets_build_environment = buildenv.environment()
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

The CMakePresets.json file generated by Conan includes the preset variable as expected, and I can build using the preset by calling cmake directly. However, if I instead use the "conan build ." command as described [here](https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html#conan-build), then the preset variable is not set. 

I understand that there are reasons that Conan doesn't call the preset directly, but I would expect it to be consistent with the preset regardless. Indeed, when I run conan create, the environment variable is set at the point when the build method runs and everything works as expected. It's only when running the build command that the preset build environment is not respected. 

We can resort to calling cmake directly with the preset but this would preclude us from using some of the functionality associated with [building editable dependencies](https://docs.conan.io/2/tutorial/developing_packages/editable_packages.html#building-editable-dependencies). I can also think of circumstances in automation where it would be nice to be able just use the build command instead of having to figure out what build system a particular project uses so that it can be called directly.

**Comment by memsharded** [comment]
Hi @NormanT7 

Thanks for your question.

I am not sure what could be happening, but what should happen with that is that when you call ``conan build .`` this happens:

- Conan will call internally a ``conan install`` to install the dependencies
- Then it will call the ``generate()`` method to create the necessary files.
- This ``generate()`` will create the CMakePresets.json with the variables and more importantly a ``conanbuild.bat|.sh`` depending on the system that calls other files like ``conanbuildenv.bat|.sh`` that contains the defined variable. Please check if this file is in your disk after ``conan build .`` and if it contains your variable
- Then it will call ``build()`` method, which in turn will call ``cmake.configure()`` and ``cmake.build()``
- Those cmake methods, internally call ``self.run("cmake", env="conanbuild")``, which means they will call and activate the environment script, defining your variable. You might use the ``-vvv`` argument in latest Conan to see the full wrapped commands
- You might verify if it works with a simple ``self.run("echo $MYVAR")`` or equivalent command in the ``build()`` method


Please check that and let us know if it helps.

**Comment by NormanT7** [comment]
Thank you for your helpful response! 

With that understanding, I figured it out. The preset environment variables I was setting made use of the [CMake presets macro expansions](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#macro-expansion) (e.g., ${sourceDir}). This worked when I ran the Conan-generated preset directly with cmake. However, it appears that these expansions aren't handled by Conan in the environment scripts that it creates, resulting in the inconsistency when running "conan build ."

**Comment by memsharded** [comment]
Indeed, the regular Conan usage, that is, when ``cmake.configure()`` runs inside recipes, it doesn't use CMake presets with ``cmake --preset``. Instead (it is necessary to support CMake 3.15, and also because it was a recommended CMake practice), the CMakePresets.json arguments are read and passed in command line arguments like ``cmake ... -DCMAKE_TOOLCHAIN_FILE=...``

The environment variables must be "regular" environment variables, it is not possible to rely on the CMake presets evaluation on those. 

I hope this clarifies the issue.

**Comment by NormanT7** [comment]
I understand now. The issue was the use of the cmake macro expansions. Thanks!

**Comment by memsharded** [comment]
Thanks for your feedback!
