### ISSUE TITLE
[question] Question about test_requires when tools.build:skip_test=True

### ISSUE THREAD

**Issue by andersonjd** [conan-io/conan#17147]
### What is your question?

If I run the following command:

```
conan install . --build=missing -c tools.build:skip_test=True
```
Conan will resolve and build all `test_requires` for the package dependencies that are missing, even though testing will not be built or performed according to the `skip_test=True` configuration. 

According to the docs here: [test-requires](https://docs.conan.io/2/reference/conanfile/attributes.html#test-requires), it seems like this is the intended behavior.  Can this be changed?

If I have set the `skip_test=True` configuration I would like to avoid an fetching / building of test_requires all together.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @andersonjd thanks for your request

We're in the progress of implementing a similar feature, where a Conf can control the expansion of test_requires, see https://github.com/conan-io/conan/pull/17117 for the discussion. We might change how we approach it, but the idea is to release it for the next Conan 2.9 release :)

**Comment by andersonjd** [comment]
That's perfect, thanks!
