### ISSUE TITLE
[feature] Conan install should have a "fallback to previous recipes" option if latest recipe does not contain the required package

### ISSUE THREAD

**Issue by syed-jamal** [conan-io/conan#17144]
### What is your suggestion?

We have a separate conan remote for our CI/CD. We only occasionally update the packages to the latest recipe revision from conancenter. Our issue is that if we update a package to the latest recipe revision only for one build_type for example "Release", in future CI/CD runs, `conan install` is not able to locate a package for other build types say "Debug" even though the package ID does exist in the previous recipe revision. We would like an option for conan to resolve to older recipe revision in this case. Thanks.
 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @syed-jamal 

Thanks for your suggestion.

This has been discussed previously, under different conditions, see for example:
- https://github.com/conan-io/conan/issues/12043
- https://github.com/conan-io/conan/issues/9547
- https://github.com/conan-io/conan/issues/11700

You can see some detailed explanation about it in the FAQ, regarding version conflicts:
https://docs.conan.io/2/knowledge/faq.html#getting-version-conflicts-even-when-using-version-ranges

So this request is basically the same, requiring to backtrack to older revisions when a selected revision doesn't contain a given binary is a NP-hard problem, intractable in practice.

For this reason, the recommended approach is to build the necessary binaries when a new recipe revision is done.
For production systems using packages from ConanCenter, either using at least lockfiles is recommended, but in most cases hosting the necessary binary packages built in your own CI hosting them in a private server is the recommended way to go. See the recommendations in https://docs.conan.io/2/devops/using_conancenter.html

In your case, it means when updating recipes, it is necessary to make sure that the binaries for both Release and Debug configurations are built and uploaded to the server, falling back to the previous one is generally not correct (erroneously getting a binary that does not match the given recipe and build instructions), and in any case it is not a tractable problem in practice.


Thanks very much for your feedback.

**Comment by syed-jamal** [comment]
@memsharded I see. Thank you for the elaborate explanation. Yes I think going forward, we will enforce upload for all build types.

**Comment by syed-jamal** [comment]
@memsharded Sorry wasn't sure but I'm closing this issue as resolved. Thanks.

**Comment by memsharded** [comment]
Great, thanks for the feedback!
