### ISSUE TITLE
Support Glob Expressions in Options 

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1715]
Currently, the examples here show how users set options per-package: 
http://conanio.readthedocs.io/en/latest/reference/conanfile_txt.html?highlight=shared#options

Currently, the options appear to use exact-matching on package name to option association.  There is at least one case where we would like to set an option across many packages by matching or glob expression of some kind. There are many places where Conan matches packages based on expression, the hope is that this might be trivial to implement and completely non-disruptive, even if it's not extremely common. 

Alternatively, if someone can point out a way to achieve our goal without making any changes to Conan, that would be preferable.  For example, if there's already a native way to set a "global" option which is visible to all transitive dependencies (and their generators).  Or, perhaps we can set an option on a fictional package name such as `AllABCPackages:shared = True` which might have a similar effect of being visible transitively.  

Conan has so much power already, I'm guessing there's a way to do this. 

It's worth noting that we thought we might be able to achieve the goal if the consuming package uses a conanfile.py , where we can write logic in the `requirements()` method body.  However, this wouldn't help for consumers using conanfile.txt, AND we don't even know if it's possible really.

**Comment by memsharded** [comment]
I have no idea about the complexity of implementation yet, I have to check. But I think that this make sense, so there is a way for example to switch the whole graph from shared to static options and viceversa. Indeed the current workaround is to set options from downstream to upstream to match, but it feels a bit weird sometimes.

**Comment by ringgelerch** [comment]
Looking forward to see this feature in 0.28
