### ISSUE TITLE
conan package info not visible inside artifactory

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#17151]
### What is your question?

Hello. I am doing some packages/recipes migration from conan 1.24.0 -> 2.8.0

I managed to adapt the commands to create packages from existing pre-built binaries, succeded to upload the packages inside Artifactory but I get an error when I try to visualize the Conan package info tab

I am running Artifactory Conan edition license 7.35.2

The Conan Info tab is visible
![image](https://github.com/user-attachments/assets/4d4263b6-1365-4b2b-8eca-5612813869ca)

But Conan package info is not:
![image](https://github.com/user-attachments/assets/a3e5418f-fd43-4aa7-ac3d-be27940a56b1)

This is my conanfile.py
```
from conan import ConanFile
from conan.tools.files import copy

class Package(ConanFile):
    name = 'zlib'
    version = '1.2.11'
    license = '''ZLIB '''
    url = 'https://github.com/madler/zlib/tree/v1.2.11'
    description = 'NA'
    settings = 'os', 'compiler', 'build_type', 'arch'
    options = {"shared": [True, False]}
    default_options = {"shared": False}

    def package(self):
        copy(self, "*", '/home/user/conan-packages-uploader/_Sandbox_BUILD_Linux_Ubuntu_x86_64/zlib_1_2_11/stage', self.package_folder)
```

The only noticeable difference I can see between conan 1.x and 2.x packages is conaninfo.txt which in conan2.x has less information

conan 1.x
```
[settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=16
    os=Windows

[requires]


[options]
    shared=True

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=16
    os=Windows

[full_requires]


[full_options]
    shared=True

[recipe_hash]
    25af86eb33e236e1c45254294a5f8bc5

[env]

```

conan 2.x
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=12.3
os=Linux
[options]
shared=True
```

And this is the command I am using to create the conan package. The command is executed inside this directory: /home/user/conan-packages-uploader/_Sandbox_BUILD_Linux_Ubuntu_x86_64/zlib_1_2_11/stage
```
conan export-pkg --name zlib --version 1.2.11 --user user--channel stable -s os=Linux -s arch=x86_64 -s build_type=Release -o:a shared=True -pr:a /home/user/newtoolchain/scripts/data/../../conan/profiles/x86_64-Linux-gcc12 -of /home/user/conan-packages-uploader/_Sandbox_BUILD_Linux_Ubuntu_x86_64/zlib_1_2_11/build /home/user/conan-packages-uploader/_Sandbox_BUILD_Linux_Ubuntu_x86_64/zlib_1_2_11/build
```

**Comment by memsharded** [comment]
Hi @danielhalati 

Thanks for your question.

I think you need to update to some newest version of Artifactory, I am running on 7.55 and that tab looks fine.
I am not sure if in the upgrade it will re-index and get the information, you might need to re-upload.

Please try that and let us know.

**Comment by danielhalati** [comment]
Ok thanks
