### ISSUE TITLE
[bug] Meson on Conan 1.65.0

### ISSUE THREAD

**Issue by VA-GS** [conan-io/conan#17161]
### Describe the bug

Hello, I think https://github.com/conan-io/conan/blob/develop/conan/tools/meson/toolchain.py#L299 has the same issue that was mentioned in https://github.com/conan-io/conan/issues/6779: basically merging sharedlinkflags and exelinkflags into ldflags prevents having linker flags passed on exe and not shared.

**Comment by memsharded** [comment]
Hi @VA-GS 

Thanks for your report. 
What would be the right approach for this? What flags should be defined to Meson for this to work correctly?

**Comment by VA-GS** [comment]
I had a quick look but I never used Meson before finding this issue today. I pass some flags from my project to Conan (for Memory Sanitizer) and those caused issues in libglvnd on a `.so` while the flag I was setting was in my exelinkflags only, not sharedlinkflags.

**Comment by memsharded** [comment]
Up to my knowledge, Meson doesn't have this distinction, it only define ``c_link_args`` and ``cpp_link_args`` for the linker, irrespective of linking executables or shared libraries. So this doesn't seem a bug in Conan, but a limitation in Meson build system.

**Comment by memsharded** [comment]
Thanks for linking the issue.
As there is nothing we can do at the moment for Meson, I am closing the issue.
Please re-open it or create a new one when this is available in Meson and can be implemented in Conan. Many thanks for your feedback.
