### ISSUE TITLE
Can't clone to "." in source

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1717]
- fatal: destination path '.' already exists and is not an empty directory.
Because of the `.conan_dirty` created. 

Maybe extract the .conan_dirty to parent, and call it `.conan_source_dirty`

**Comment by lasote** [comment]
Anyway, the conanfile.py and conanmanifest is already copied, so it's not possible to clone in "."

**Comment by danimtb** [comment]
Is this fixed now @lasote?

**Comment by lasote** [comment]
No, because the `exports_sources` or any other file will be there.
In the past, I've been against creating a git wrap tool because of the boilerplate, but maybe we could consider it again to provide the trick to "clone" a repository with an non-empty directory:

https://stackoverflow.com/questions/2411031/how-do-i-clone-into-a-non-empty-directory

(see the most voted answer, not the accepted one)

**Comment by lasote** [comment]
With the scm feature it is fixed. First the scm is run, then the exports, exports_sources and finally the source method is called.
