### ISSUE TITLE
[question] Why is boost 1.86.0 suddenly invalid?

### ISSUE THREAD

**Issue by av4625** [conan-io/conan#17176]
### What is your question?

Conan version 1.65.0

I have a project that has been using boost 1.86.0 header only for a while now with no issues.

I tried to run a github action (linux) for it recently and it failed with:

```
...
boost/1.86.0: Retrieving from server 'conancenter' 
boost/1.86.0: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
boost/1.86.0: Downloaded recipe revision 0
...
Requirements
    boost/1.86.0 from 'conancenter' - Downloaded
...
Packages
    boost/1.86.0:INVALID - Invalid
...
ERROR: There are invalid packages (packages that cannot exist for this configuration):
boost/1.86.0: Invalid ID: process requires ['filesystem', 'system']: filesystem is disabled
CMake Error at build/third_party/conan.cmake:651 (message):
  Conan install failed='6'
Call Stack (most recent call first):
  third_party/CMakeLists.txt:150 (conan_cmake_install)
```

I thought this was strange as I had a github action run ~2 weeks ago and it was fine.

I then removed the previous downloaded boost from `~/.conan` on my local machine (Mac) and tried again and I get exactly the same problem now.

I use the following boost options:
```
    boost:header_only=True
    boost:error_code_header_only=True
    boost:without_atomic=True
    boost:without_charconv=True
    boost:without_chrono=True
    boost:without_cobalt=True
    boost:without_container=True
    boost:without_context=True
    boost:without_contract=True
    boost:without_coroutine=True
    boost:without_date_time=True
    boost:without_exception=True
    boost:without_fiber=True
    boost:without_filesystem=True
    boost:without_graph=True
    boost:without_graph_parallel=True
    boost:without_iostreams=True
    boost:without_json=True
    boost:without_locale=True
    boost:without_log=True
    boost:without_math=True
    boost:without_mpi=True
    boost:without_nowide=True
    boost:without_program_options=True
    boost:without_python=True
    boost:without_random=True
    boost:without_regex=True
    boost:without_serialization=True
    boost:without_stacktrace=True
    boost:without_system=True
    boost:without_test=True
    boost:without_thread=True
    boost:without_timer=True
    boost:without_type_erasure=True
    boost:without_url=True
    boost:without_wave=True
```

I also provide the build missing option but because I'm using it header only that shouldn't matter. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by av4625** [comment]
As you can probably tell from my output that I am using cmake_conan. To take that out of the equation here is an example using conan on the command line.

[conanfile.txt](https://github.com/user-attachments/files/17401121/conanfile.txt)

`conan install . --build=missing`

**Comment by av4625** [comment]
I just seen that there was a commit to boost about 2 weeks ago adding process.
Adding this new option fixed it: `boost:without_process`

**Comment by memsharded** [comment]
Hi @av4625 

Happy to see that you found the solution, updating the potions to align with the last recipe changes (the recipe had a bug, because 1.86 added a new compiler library, but it was not properly modeled in the recipe).

Please recall that to use packages from ConanCenter in production, it is recommended to use at least ``lockfiles`` to lock to the desired revisions and not be affected by changes in ConanCenter, or even better, to use your own server. If you haven't checked it yet, it is recommended to have a look to https://docs.conan.io/2/devops/using_conancenter.html
