### ISSUE TITLE
[question] extends feature in conandata.yml

### ISSUE THREAD

**Issue by Vasile-Creuco** [conan-io/conan#17188]
### What is your question?

The extends feature is supported in Conan 2.x versions?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Vasile-Creuco 

I am not sure what feature are you taking about, could you please clarify?
I don't know of any extends feature in Conan1 for conandata.yml, if you have any links or code that could help.

**Comment by memsharded** [comment]
Any further question or issue here? If not maybe we can close the ticket? Thanks for your feedback.
