### ISSUE TITLE
[feature] allow self.version in combination with set_version(self)

### ISSUE THREAD

**Issue by iaavo** [conan-io/conan#17185]
### What is your suggestion?

Hi, I have checked the documentation of [set_version](https://docs.conan.io/2/reference/conanfile/methods/set_version.html) and there is a warning regarding using the version as property and method at the same time.

I would like to use that as I have the following use case:

- We are in a monorepo setup, so there are many different conan recipes, each having their own version defined. As such we cannot use tags for defining the version. The version is defined in the conan recipe itself.
- We would like to setup a central python_require file which defines the set_version() method
- The set_version() method should use the self.version attribute of the conan recipe and bump its patch version and also append the current git branch to it as a prerelease.
- That way devs can create versions locally and consume them by using the use_prereleases=true conf

I know that we can use a simple text file along with the conan recipe and define the version there. But it would be more convenient to have the version directly in the conan recipe.

Im just wondering why this limitation exists in the first place.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @iaavo 

Thanks for your feedback.

I think this is already possible, please check the following unit test, that works:
```python
def test_python_requires():
    c = TestClient()
    pyrequires = textwrap.dedent("""
        from conan import ConanFile

        class MyBase:
            def set_version(self):
                self.version = (self.version or self._version) + ".custom"

        class PyReq(ConanFile):
            name = "pyreq"
            version = "1.0"
            package_type = "python-require"
        """)

    conanfile = textwrap.dedent("""
        from conan import ConanFile

        class Pkg(ConanFile):
            name = "mypkg"
            _version = "2.1"
            python_requires = "pyreq/1.0"
            python_requires_extend = "pyreq.MyBase"
        """)

    c.save({"pyreq/conanfile.py": pyrequires,
            "pkg/conanfile.py": conanfile})
    c.run("create pyreq")
    c.run("export pkg ")
    assert "mypkg/2.1.custom" in c.out
    c.run("export pkg --version=3.4")
    assert "mypkg/3.4.custom" in c.out
```

This can be done by using your own user attribute ``_version`` instead of the Conan one.

The reason that warning is there in the docs, is to avoid having a ``version = "value"`` declared in the recipe that don't align with the actual value, specially when the ``set_version()`` might be hidden in a ``python_requires``, and also allowing at the same time to have implementations that respect the ``--version=xxx`` argument from command line, as you can see in the test.

**Comment by iaavo** [comment]
Thanks for the code example. I see, then I can just define `_version` in the conan recipe file. That would work. Thanks!

**Comment by memsharded** [comment]
Yes, I really think that ``_version`` captures the intent much better, for someone who reads a recipe, seeing a ``_version`` attribute will realize: "this is not the real ``version``, but a user defined thing, there might be something else somewhere that is defining the real ``self.version``"

Many thanks for the feedback!
