### ISSUE TITLE
[question] SHORT DESCRIPTION Why can't I find the lib in the conan library when I use bazel ?

### ISSUE THREAD

**Issue by wangyaxin1998** [conan-io/conan#17181]
### What is your question?

    def requirements(self):
        self.requires("nlohmann_json/3.7.3@3rd-party/stable")
        self.requires("opencv/3.4.5@3rd-party/stable#334db9b74ea14617b1f59c64dd5313a5")
        self.requires("ucp/3.1.3@saturnv/stable")

    def generate(self):
        bz = BazelDeps(self)
        bz.generate()

        bt = BazelToolchain(self)
        bt.generate()        

    def layout(self):
        bazel_layout(self)
`
![image](https://github.com/user-attachments/assets/4da37e0f-a3f3-4074-a7d6-59b1757a6499)

![image](https://github.com/user-attachments/assets/9264d4fe-b8fd-412e-a72c-13940f51ef00)

Why is the lib library in conan not exported in the conan/ucp/BUILD.bazel directory?

I found that if I have a static library in lib, I can find it, but the dynamic library cannot be found in lib.

I hope to ask the developers how to solve this problem

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by wangyaxin1998** [comment]
I tried to create a static library of libucp.a in the lib directory of the download directory of the conan library I depend on, and found that BUILD.bazel would add this static library
![image](https://github.com/user-attachments/assets/56590d07-e874-494d-858f-d71b63720863)
So how should I import my dynamic library into BUILD.bazel？

**Comment by franramirez688** [comment]
Hi @wangyaxin1998 

I'm sorry for not getting back to you sooner.
Did you get to solve the issue?

If I understood your issue, the problem that I see is that the name of the shared library to find could not be listed correctly in your `ucp`'s `cpp_info.libs`. For instance:

**ucp conanfile.py**
```python

# ....

def package_info(self):
    self.cpp_info.libs = ["hlog"]  # and the rest of them if there are several ones belonging to the same component
```
