### ISSUE TITLE
[question] Is there a flag to silence `cmake` messages related to `conan`?

### ISSUE THREAD

**Issue by i-ilak** [conan-io/conan#17191]
### What is your question?

When running something like 
```
conan install /path/to/conanfile
cmake --preset conan-release
```
As user you will be confronted with some messages that were generate from creating the `cmake` targets that are Conan related. They come from lines like [this one here](https://github.com/conan-io/conan/blob/d1f6e8a9bd85b238b99936c3da0f488d10183b40/conan/tools/cmake/cmakedeps/templates/targets.py#L68) and similar places. 

Depending on what packages (e.g. something like Qt) or how many packages one uses in a project, this can generate hundreds/thousands of lines of output. As far as I can tell from the code, it is currently not possible to silence this...

Are there any plans on changing this? E.g. something like a `CONAN_SILENCE_CMAKE_OUTPUT` flag that would let the user turn this of if he choses to do so?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @i-ilak 

Thanks for your question.

If you check the line that you are sharing, you can see a ``{{ file_name }}_MESSAGE_MODE `` that determines the verbosity.

This variable is define from

```
if({{ file_name }}_FIND_QUIETLY)
     set({{ file_name }}_MESSAGE_MODE VERBOSE)
else()
     set({{ file_name }}_MESSAGE_MODE STATUS)
endif()
```

Which in turns is defined by the ``find_package(  QUIET)``

**Comment by i-ilak** [comment]
Thanks a lot for the answer, was not familiar with this `cmake` functionality... Sorry for the disturbance!

**Comment by memsharded** [comment]
Happy to help, thanks for the feedback!
