### ISSUE TITLE
[question] C++26 and CMAKE_CXX_STANDARD_LATEST

### ISSUE THREAD

**Issue by rdong8** [conan-io/conan#17192]
### What is your question?

In CMake 3.30 there's a new variable called `CMAKE_CXX_STANDARD_LATEST` that sets the C++ standard to the latest available from the compiler, what is the Conan equivalent of this in the Conan profile? For instance, on the Clang 18 shipped by Fedora 40, this uses C++26, which Conan does not seem to support yet.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rdong8 

Thanks for your question.

C++26 was added to the default settings.yml in https://github.com/conan-io/conan/pull/17092, that means that it will be in next Conan 2.9 release, typically before the end of the month.

Recall that very often, it is possible to edit and add values to the default ``settings.yml`` file, or even better, to add them in the ``settings_user.yml`` file, not having to wait until the next Conan release.

**Comment by rdong8** [comment]
Thanks!
