### ISSUE TITLE
[feature] New version 1.x

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#17196]
### What is your suggestion?

Hi,

Can you release a new 1.x version with Apple Clang 16 support.

Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @paulocoutinhox thanks for your request. The 1.66 release is scheduled to be released at the end of this month, which will include support for the latest compilers at that time.

Note that Conan 1 releases will drastically reduce in frequency as it gets progresively more deprecated, and support for future configurations is not something we expect to do outside special circumstances/security releases, so we encourage you to prepare for that too 

Note that meanwhile you can try adding support locally by modifying the `settings.yml` file on your Conan cache

**Comment by memsharded** [comment]
Closing this one to prepare the release of 1.66, thanks
