### ISSUE TITLE
[question] vs code includePath ~/.conan/data/** not resolving third party libraries

### ISSUE THREAD

**Issue by ftbmynameis** [conan-io/conan#17213]
### What is your question?

I am trying to use VS code in an existing project where I have no control over the conan and cmake setup. I have added the mentioned path to my includePath settings on VS code. Note that I am on windows tho, so my added path is "C:/<myuser>/.conan/data/**". However third party library includes are not resolved. 
Ive got the idea for this "solution" from this SO post: https://stackoverflow.com/a/60460921

I am no conan or cmake expert. I use the standard cmake-tools extensions in vs code. The project itself is still on conan 1. The referenced SO post made my think that this should work like that pretty much out of the box, but its not. Now I struggle to see where exactly I am doing something wrong. It feels like I am missing a vital piece somewhere.

I did notice that going down the data folder there are eventually some .conan_link files that point towards where I want to go, but I do not see how VS code should resolve this just like that on its own (which again the SO post kind of is suggesting to me that it can). Also these are available for multiple library versions which makes this more complex as well. Is there a conan extensions required for resolving? Should conan be able to gather all of this from the cmake files? Is my approach in general wrong?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ftbmynameis 

Thanks for your question.

First, to make sure I fully understand the issue: the main problem is that the VS Code editor will not recognize the ``#include`` and mark them with underlined red? But the project can still build and run successfully, you can also build and run from the command line without issues, etc?

**Comment by ftbmynameis** [comment]
Hi @memsharded 

exactly the includes are not recognized for third party libraries (underlined red), i.e. libraries included as <....>, except STL header. The project cannot be build or run within VSC, but within regular Visual Studio it can. 
VSC is not a supported IDE but I am currently trying to make it possible to develop within VSC. I haven't minded about the build/run so far, because a) that would have been the step next to sorting out the issue with resolving the includes and b) Id even be happy if I only develop within VSC, but build/run/debug with regular visual studio.
If possible Id like to fully move to VSC of course, but right now its not the main priority, except if there is an easy way. I am however not experienced enough in all of this to simply make it happen.

**Comment by memsharded** [comment]
I am afraid that this is not clear, because the editor is mostly irrelevant. The important bit is the build system.

Nowadays, the most popular one is CMake. Is your project using CMake? 

If the answer is yes, then the first step is to make sure that everything works, even without VSCode or any editor, just with command line commands such as: ``conan install ... `` + ``cmake ... `` + ``cmake --build ...``. All the Conan documentation uses this approach and explains these steps. Using modern presets with cmake like ``cmake --preset`` is recommended.

Then, after making sure things work, then it is time to check the editor/IDE. Because for example, when using VSCode with cmake-tools, the cmake-tools extension can sometime manage to find the includes and manage it automatically, without any further action. Plus, it is important to highlight that the important thing is to be able to correctly build things, not that the editor underlines something correctly or not, that is secondary.

**Comment by ftbmynameis** [comment]
Sorry for that unclear information.

cmake and conan are used, yes. Everything does work with plain cmake including the build itself. I can generate visual studio solution/project files with cmake and work + build from there, like youd expect.

Im now trying to make it work on VS code because I prefer that IDE.

**Comment by memsharded** [comment]
It should work out of the box with cmake-tools.
See:
- ``conan new cmake_lib -d name=pkg -d version=0.1 -d requires=zlib/1.3.1``
- change the ``CMakeLists.txt`` to use the correct ``find_package(ZLIB `` (uppercase) and ``target_link_libraries(... ZLIB::ZLIB)``
- ``conan install .``
- open VSCode: ``code .`` (it should have cmake-tools extension installed)
- Select build, select the ``conan-default`` preset (in Windows, in Linux it would be ``conan-release``). 

When done this, the ``#includes`` will be correctly detected and highlighted, note how the ``zlib.h`` is correct, but the ``unknown.h`` is underlined.

<img width="172" alt="image" src="https://github.com/user-attachments/assets/16b78e1b-46ad-47b9-b39a-72d83438f603">


If it doesn't work in your case, it is important to report the exact steps, as I did here, to explain what is being done, and let us try to understand what could be happening and try to help.

**Comment by ftbmynameis** [comment]
Thanks for that detailed answer and sorry for my late reply. I got held up by other things since this is really only something I do on the side.
The project I am working in has its own team who work on cmake+conan.. so I am afraid this might be a bit too much of a special case and I probably need their support to get this running. But its good to know that technically all of this is supposed to work fine just out of the box.
I will try to learn more about conan so hopefully eventually Ill get this running, but I think for now itll be difficult so Ill be closing this issue, but thanks for the in-depth support!

**Comment by memsharded** [comment]
Happy to help!
