### ISSUE TITLE
[question] Package Development Flow with build dirs named after conan profiles

### ISSUE THREAD

**Issue by guban** [conan-io/conan#17218]
### What is your question?

Hi,

I want to do the package development flow
with several build directories named after their corresponding Conan profiles.

I created a minimal example that models my real-life situation.
In my working directory, I have files

```
my_source_code.cpp
CMakeLists.txt
conanfile.py
profile_A
profile_B
```

I want Conan to use sub-directories `build-profile_A` and
`build-profile_B` when building profile A and B, respectively.
I need to run "conan install" and "conan build" for each of these build directories.

It is important that the build directories are named after their profiles:
my profile file names are concise, distinct, meaningful descriptions of their options and settings.
I cannot (and don't want to) use a generic name like "Debug_x64_opt1=value1_opt2=value2"
obtained by concatenating settings and options.

I guess the solution involves defining `self.folders.build` in the `layout()` method.
When I run `conan install . --profile=profile_A`, I need `self.folders.build = "build-profile_A"`.
But when I run `conan install . --profile=profile_B`, I need `self.folders.build = "build-profile_B"`.
But I don't want to manually change the `layout()` method in the recipe recipe
every time I switch between the profiles. How do I achieve this?

After hours of reading and searching, I found only a rather ugly workaround:
In `layout()`, I set `self.folders.build = f"build-{self.conf.get('user:build_dir')}"`.
This expects that the `user:build_dir` configuration is provided somewhere.
Then, I provide the expected configuration by running
`conan install . --profile=profile_A -c "&:user:build_dir=profile_A"` for profile A
and `conan install . --profile=profile_B -c "&:user:build_dir=profile_B"` for profile B.

Is there a better way of achieving the above-stated needs?

Thank you.

File conanfile.py:

```
import os
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake

class Recipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"

    def requirements(self):
        self.requires("zlib/1.2.11")

    def layout(self):
        self.folders.build = f"build-{self.conf.get('user:build_dir')}"
        self.folders.generators = os.path.join(self.folders.build, "gen")

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
 ```

File CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.15)
project(my_app CXX)
find_package(ZLIB REQUIRED)
add_executable(my_app my_source_code.cpp)
target_link_libraries(my_app ZLIB::ZLIB)
```

File my_source_code.cpp:

```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include <zlib.h>

int main(void) {
    char buffer_in [256] = {"Conan is a MIT-licensed, Open Source package manager for C and C++ development, "
                            "allowing development teams to easily and efficiently manage their packages and "
                            "dependencies across platforms and build systems."};
    char buffer_out [256] = {0};

    z_stream defstream;
    defstream.zalloc = Z_NULL;
    defstream.zfree = Z_NULL;
    defstream.opaque = Z_NULL;
    defstream.avail_in = (uInt) strlen(buffer_in);
    defstream.next_in = (Bytef *) buffer_in;
    defstream.avail_out = (uInt) sizeof(buffer_out);
    defstream.next_out = (Bytef *) buffer_out;

    deflateInit(&defstream, Z_BEST_COMPRESSION);
    deflate(&defstream, Z_FINISH);
    deflateEnd(&defstream);

    printf("Uncompressed size is: %lu\n", strlen(buffer_in));
    printf("Compressed size is: %lu\n", defstream.total_out);

    printf("ZLIB VERSION: %s\n", zlibVersion());

    return EXIT_SUCCESS;
}
```

File profile_A:

```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

File profile_B:

```
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

The commands I run:

```
conan install . --profile=profile_A -c "&:user:build_dir=profile_A" --build=missing
conan install . --profile=profile_B -c "&:user:build_dir=profile_B" --build=missing
conan build . --profile=profile_A -c "&:user:build_dir=profile_A"
conan build . --profile=profile_B -c "&:user:build_dir=profile_B"
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @guban 

Thanks for your question.

I think it might be doable with the built-in ``build_folder_vars``. Please check https://docs.conan.io/2/reference/tools/cmake/cmake_layout.html#conf

If you do something like:
```
conan install ... -c tools.cmake.cmake_layout:build_folder_vars="['const.profile_A']"
```
Your folders will automatically get the profile name in the path.
Note that if you put that conf in your profile files, there is jinja2 templating, so you can use the ``{{profile_name}}`` var to automatically access the profile name.

Note also in many cases this might not be necessary, and using the ``build_folder_vars`` with settings and options can be enough to create the different folders for the different configurations.

Please let me know if this helps

**Comment by guban** [comment]
Hi @memsharded,

Thank you for fast feedback.

My understanding is that `build_folder_vars` works only for cmake.
Alas, some of my packages need `msbuild` because they still define the build in terms of `.vcxproj`.
I wish I had time, resource and team support for converting all those projects to cmake, but I don't.
Is there an `msbuild` equivalent for `build_folder_vars`?

In fact, if `build_folder_vars` and `const.profile_A` worked for all build systems,
that would be a good solution to my problem.

> you can use the `{{profile_name}}` var

Yes, `{{profile_name}}` might help a bit. At the same time,
I'm considering to have a `create_build_dir.py` script
that will create a build directory and generate inside it scripts `1-conan_install.py` and `2-conan_build.py`
that run "conan install" and "conan build" commands, respectively.
Since these scripts will be generated automatically anyway,
passing `user:build_dir` via `-c` command-line option will be a better solution
because it will isolate the workaround inside the generated scripts,
so that Conan profiles will remain clean and simple.

> using the build_folder_vars with settings and options

One of my packages is a library that is used in several apps.
For each app, this library must be built with a specific combination of settings and options.
The library has about 20 Conan options, and each app needs a specific combination of them.
Over time, new applications and new options are added,
and existing apps update their combinations of options and settings
(e.g., some app upgrades their compiler version).
Remembering which combination of settings and options corresponds to which app is impractical.
Instead of long, ever-changing, low-level names like "Debug_x64_vs2017_opt1=value1_opt2=value2",
I need to use short, meaningful, stable, high-level names like "appA_debug".
The name of a Conan profile is a valuable piece of information
that tells much more than a name like "Debug_x64_vs2017_opt1=value1_opt2=value2".
I don't want to lose this valuable piece of information.

**Comment by memsharded** [comment]
> My understanding is that build_folder_vars works only for cmake.
Alas, some of my packages need msbuild because they still define the build in terms of .vcxproj.
I wish I had time, resource and team support for converting all those projects to cmake, but I don't.
Is there an msbuild equivalent for build_folder_vars?

I am afraid it doesn't exist. The problem is that VS projects (MSBuild) basically hardcode their layout. There is nothing that can be done from the outside (Conan) to change the location of the output and build files, in needs changes in the project itself.

> Since these scripts will be generated automatically anyway,
passing user:build_dir via -c command-line option will be a better solution
because it will isolate the workaround inside the generated scripts,
so that Conan profiles will remain clean and simple.

Our experience is that in general it is better to rely on built-in features than using custom solutions, which needs more awareness and learnings from devs

Something that you might consider is using Conan custom commands instead of your own scripts for extended functionality. They can be shared and distributed automatically via ``conan config install``, so it is a great way to manage those scripts and make sure all devs and CI use the right versions. They also offer discoverability, standard command-line help, etc. You can further inject ``conf`` values automatically from your custom commands implementation (but I still think it will be better to use the builtin ``build_folder_vars`` than a custom user conf.

**Comment by guban** [comment]
Yes, I agree that it is better to rely on built-in features and avoid custom scripts.
I know how painful their maintenance can be :)

Thank you for pointing me to custom commands. I have created one: `conan mkbd` (make build directory).
Running `conan mkbd profile_A` creates build directory `build-profile_A` with scripts
that run conan install/build/export-pkg with `user:build_dir` configuration set to `build-profile_A`.
Then, in the `layout()` method I have `self.folders.build = self.conf.get("user:build_dir") or "build"`.
This forces Conan to use my custom build directories named after my Conan profiles.

Then, I realized what equivalent built-in Conan behavior I actually need.
For "conan install", "conan build" and "conan export-pkg" commands,
I need a way to **override `self.folders.build` in `layout()` method**.
This is essentially what I was trying to achieve with the `conan mkbd` command.

The overriding of the build directory could be implemented in Conan
as a command-line option, e.g. `--build-dir=<my_build_dir>`.
When I run `conan install . --build-dir=build-profile_A`,
Conan shall behave *as if* in `layout()` method I had `self.folders.build="build-profile_A"`.
This is exactly what I need.

I think this desired built-in behavior is generic and potentially useful to many Conan users.
It gives an option to use custom build directory names
in the package development flow with multiple build directories.
The custom build directory names in general have nothing to do with profile names,
but one (e.g., me) could choose to name build folders after profiles.

Interestingly, `build_folder_vars` with `const.XXX` is also a way
of overriding the build directory, only rather indirect and limited to cmake only.
The `--build-dir=<my_build_dir>` way is better because it is simple and direct, and it works for any build system.

What do you think about adding to Conan this new method of overriding the build directory?

**Comment by memsharded** [comment]
Hi @guban 

I think what you are looking for is ``tools.cmake.cmake_layout:build_folder`` conf. This conf allows exactly to redefine the build directory.

Tip: You can use the ``conan config list <pattern>`` to list existing confs that contain that pattern, for example:

```
$ conan config list folder
core.scm:local_url: By default allows to store local folders as remote url, but not upload them. Use 'allow' for allowing upload and 'block' to completely forbid it
core.sources:download_cache: Folder to store the sources backup
tools.cmake.cmake_layout:build_folder: (Experimental) Allow configuring the base folder of the build for local builds
tools.cmake.cmake_layout:build_folder_vars: Settings and Options that will produce a different build folder and different CMake presets names
tools.cmake.cmake_layout:test_folder: (Experimental) Allow configuring the base folder of the build for test_package
```

**Comment by guban** [comment]
Hi @memsharded,

Yes, `tools.cmake.cmake_layout:build_folder` is better because it is more direct than `build_folder_vars`+`const.XXX`.
At the same time, I have a few concerns about it:

1. It is coupled to `cmake` only. What do I do when I don't use `cmake`?
2. It is coupled to `conan.tools.cmake.cmake_layout`. What do I do when I don't use `cmake_layout`?
3. It is experimental. Will it stay? Will it receive breaking changes in the future?

After some contemplation, I've settled on the following way of customizing the build folder:
in `layout()`, I do `self.folders.build = self.conf.get("user:build_dir") or "build"`.
Then, in my "conan install", "conan build" and "conan export-pkg" commands,
I add the `-c "&:user:build_dir=<my_custom_build_dir>"` command-line option.
This works for any build system, and this is simple and straightforward.

It seems to me that Conan could benefit from having one single, universal way
of specifying a custom build folder for the local package development flow,
regardless of the build system and regardless of how `layout()` method
is implemented (with or without `cmake_layout`).
Of course, my understanding is limited, and you are
in a much better position to judge whether Conan really needs that or not.

Thank you for your feedback!
Much appreciated.

**Comment by guban** [comment]
Hi @memsharded,

And after all the above, I've discovered the `-of OUTPUT_FOLDER` option.

I did not consider this option before because I was not sure what it's intended for,
and I mistakenly thought that to have a build folder for local package development flow,
I absolutely need to set `self.folders.build` in `layout()` method.

It looks like the `-of OUTPUT_FOLDER` option is what I need.
To do the local package development flow with Conan profile `profile_A`,
from my working directory (where the source code, `profile_A` and `conanfile.py` are)
I simply run

```
conan install . -of build-profile_A --profile=profile_A --build=missing
conan build . -of build-profile_A --profile=profile_A
```

This creates my custom build directory `build-profile_A` and generates all build files therein.
In this manner, I can create as many side-by-side build directories as I need.
This works even when I don't define the `layout()` method at all.

So, the answer to my question is: use the `-of OUTPUT_FOLDER` option.

Sorry about confusion.

**Comment by memsharded** [comment]
>So, the answer to my question is: use the -of OUTPUT_FOLDER option.

Ok, that is great. Sorry I didn't suggest that, I thought that you were already aware of the ``-of`` argument, it is introduced in the Conan tutorial since the very beginning, while the other ``confs`` are more advanced and serve to address more specific needs.

Don't hesitate to submit new tickets for any further question, thanks for your feedback!
