### ISSUE TITLE
[bug] [Windows] Cannot create a working default profile for VS 2022

### ISSUE THREAD

**Issue by pierricgimmig** [conan-io/conan#17228]
### Describe the bug

- Windows 11
- Python 3.11.8
- Conan 2.8.1

![image](https://github.com/user-attachments/assets/716c1dac-fbac-4ab0-8ffb-a13dcfb3a3c2)

![image](https://github.com/user-attachments/assets/eec84801-49a4-4ebc-bbd7-4eaf42072c1b)

I have a simple setup, Windows 11, VS 2022 installed, yet the default profile generated by `conan profile detect` doesn't work.

```
Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows

WARN: This profile is a guess of your environment, please check it.
WARN: The output of this command is not guaranteed to be stable and can change in future Conan versions.
WARN: Use your own profile files for stability.
Saving detected profile to C:\Users\pierr\.conan2\profiles\default
```

When trying to run `conan install .`, I get different errors:
- `'settings.os.subsystem' value not defined`, which I fixed by adding `os.subsystem=msys2`
- `'settings.compiler.update' value not defined`, which I fixed by adding `compiler.update=None`  (at random since I can't find docs on this) 
- I then get `Invalid: 'settings.compiler.toolset' value not defined`, so I add the toolset of my VS 2022 install as shown in the image above, v143, but v143 is not in the list of valid toolsets. Why is that?

```
ERROR: Invalid setting 'v143' is not a valid 'settings.compiler.toolset' value.
Possible values are ['None', 'v110_xp', 'v120_xp', 'v140_xp', 'v141_xp']
```

I'm running a very common setup here, Windows 11, VS 2022. How is it that `conan profile detect` is not able to figure out some valid settings? Perhaps this command should simply not be there as to not confuse users? Is there some docs on how to setup VS 2022 on Windows?

Thanks for your help!

**Comment by memsharded** [comment]
Hi @pierricgimmig 

Thanks for your feedback.

It is not very clear how to reproduce this. That detected profile is used widely and it works in most cases.

For example can you do:
- ``conan profile detect``
- ``conan new cmake_lib -d name=mypkg -d version=0.1``
- ``conan create .``

Does it work? If it doesn't work, how does it fail?

The settings you are trying to change aren't necessary in most of the cases, for example ``os.subsystem=msys2`` should only be done when targeting the ``mingw`` gcc or clang compilers within a ``msys2`` for example. But not when using the ``msvc`` compiler. Likewise the ``settings.compiler.update`` is only necessary for users that want a very fine tuning of the msvc compiler update, but given that the binary compatibility of msvc is very good among updates, this is not necessary in most of the cases. Also the toolset shouldn't be necessary, unless you want to build for XP or something like that.

It might happen that you are using some recipes/packages that hardcode some assumptions. This is why it is better to report using known recipes like the ``conan new`` produced ones.

**Comment by pierricgimmig** [comment]
Hi @memsharded , thanks for your prompt response!

I tried your suggestion, and I get the same issue:

```
PS C:\Users\pierr\git\conar> cd .\blah\

PS C:\Users\pierr\git\conar\blah> conan new cmake_lib -d name=mypkg -d version=0.1
File saved: CMakeLists.txt
File saved: conanfile.py
File saved: include/mypkg.h
File saved: src/mypkg.cpp
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/src/example.cpp

PS C:\Users\pierr\git\conar\blah> conan create .

======== Exporting recipe to the cache ========
mypkg/0.1: Exporting package recipe: C:\Users\pierr\git\conar\blah\conanfile.py
mypkg/0.1: Copied 1 '.py' file: conanfile.py
mypkg/0.1: Copied 1 '.txt' file: CMakeLists.txt
mypkg/0.1: Copied 1 '.h' file: mypkg.h
mypkg/0.1: Copied 1 '.cpp' file: mypkg.cpp
mypkg/0.1: Exported to cache folder: C:\Users\pierr\.conan2\p\mypkga237a5f70f50d\e
mypkg/0.1: Exported: mypkg/0.1#69dcbff05d037a4e961ce5a029a6ed92 (2024-10-27 23:28:12 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    cli
Requirements
    mypkg/0.1#69dcbff05d037a4e961ce5a029a6ed92 - Cache

======== Computing necessary packages ========
Requirements
    mypkg/0.1#69dcbff05d037a4e961ce5a029a6ed92:9bdee485ef71c14ac5f8a657202632bdb8b4482b - Invalid
ERROR: There are invalid packages:
mypkg/0.1: Invalid: 'settings.os.subsystem' value not defined
```

**Comment by memsharded** [comment]
That is quite unexpected, unless the ``settings.yml`` has been modified or something like that.

Can you please retry completely wiping your ``.conan2`` home folder (or defining another temporary one with ``CONAN_HOME`` env-var)?

**Comment by memsharded** [comment]
I also see that it seems you are in a powershell terminal. This might require different setup, for example the environment files that are generated can be generated for .ps1 instead of .bat with ``-c tools.env.virtualenv:powershell=True``. 

I am not sure if this could be related to your issue, but we'd recommend using a regular ``cmd`` or ``cmder`` terminal first, at least for learning Conan.

**Comment by pierricgimmig** [comment]
Hi @memsharded, again thank you for the responsiveness.

Wiping my conan2 directory and trying your suggestion again did the trick. I think I might have messed with the `settings.yml` a while back to make a package compile. I didn't have to do anything special to make it work in powershell by the way.

I'm unblocked now, thank you!

**Comment by memsharded** [comment]
Happy that we found the cause :)
Thanks for your feedback!
