### ISSUE TITLE
Can't query individual profile key

### ISSUE THREAD

**Issue by VestniK** [conan-io/conan#1723]
Before settings_default migration to profile/default there was way to get and set individual compiler settings

    conan config set settings_defaults.compiler.libcxx=libstdc++11
    conan config get settings_defaults.compiler.libcxx

It's possible to set individual key with the latest conan version

    conan profile update settings.compiler.libcxx=libstdc++11

however there is no way to query individual key. `conan profile show` dumps whole profile content. Can you provide `conan profile get <key_name> <profile_name>` command or similar to port existing scripts to new conan version?

Use case which is now broken for me: My CI setup has two parts:
 * bunch of docker images with preconfigured default compiler settings for conan
 * script in the project repository which is executed by containers entripoint

Script uses default conan settings (default profile with the latest version) provided by the container but needs to access some individual values. With the new conan version I have to write some grep/sed voodo in order get them.

**Comment by lasote** [comment]
Yes. You are right and we can do it easily. I'm adding it at 0.27.

**Comment by lasote** [comment]
This will be released in 0.27, planned for Wednesday.

**Comment by VestniK** [comment]
I've upgraded conan and tested the fix. Thank you for your work on a great tool.
