### ISSUE TITLE
[question] Using python_requires_extend: Change base option default in derived object

### ISSUE THREAD

**Issue by CJCombrink** [conan-io/conan#17231]
### What is your question?

Hi! Looking at the docs on `python_requires_extend`, is it possible to change the default of a base option in the derived class?

For example the unit test here: [test_options_errors](https://github.com/conan-io/conan/blob/develop2/test/integration/py_requires/python_requires_test.py#L797C9-L797C28)

Is it possible to change the default of `base` to `False` in the `init()` function of the `DerivedConan` class?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @CJCombrink thanks for your question:

> Is it possible to change the default of base to False in the init() function of the DerivedConan class?

Edit: 

Yes! This is possible by directly assigning the default option value to the option itself in the init method, see https://github.com/conan-io/conan/pull/17234/files#diff-f878d79d77d1e88028cb3a732739e04ca753176513c5d0f44fc9d55f128be247R861

So simply doing `self.options.base = new_value`/`setattr(self.options, "base", new_value)` should be enough to change the default value after the fact



(Note that another option would be to:
1. Have base definition be `"base": [None, True, False]`, with a `default_options` of `None`
2. In the `configure()` method, check if it's None, which means the user will not have specified it, and set it as desired (Via `self.options.base = new_value`/`setattr(self.options, "base", new_value)`) 

Hope this helps! :)

**Comment by CJCombrink** [comment]
@AbrilRBS Thank you very much for confirming and the example, this is exactly what I needed
