### ISSUE TITLE
[question] Conan 2 Migration - CI Multiple Product/Profile Combinations

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#17253]
Hello, in migrating to Conan 2 (currently using 2.9.0) I am working on updating Jenkins pipelines to use the new lock file and build order features. I've been reading over the work-in-progress [CI tutorial documents](https://github.com/memsharded/docs/tree/feature/devops_ci/ci_tutorial).

We have multiple top-level products/applications that get built for multiple profiles (assuming "configurations" in the document is synonymous with "profiles").

Using the example product names of "game" and "mapviewer" I assumed this to be correct:
```
# Create a single master lock file covering each product/profile combination
conan lock create --requires=game/1.0 -pr=profile-linux-x86 --lockfile-out=conan.lock
conan lock create --requires=game/1.0 -pr=profile-linux-arm --lockfile=conan.lock --lockfile-out=conan.lock
conan lock create --requires=mapviewer/1.0 -pr=profile-linux-x86 --lockfile=conan.lock --lockfile-out=conan.lock
conan lock create --requires=mapviewer/1.0 -pr=profile-linux-arm --lockfile=conan.lock --lockfile-out=conan.lock

# Create an individual build order file for each product/profile combination
conan graph build-order --requires=game/1.0 -pr=profile-linux-x86 --lockfile=conan.lock --build=missing --order-by=recipe --format=json > game_linux_x86.json
conan graph build-order --requires=game/1.0 -pr=profile-linux-arm --lockfile=conan.lock --build=missing --order-by=recipe --format=json > game_linux_arm.json
conan graph build-order --requires=mapviewer/1.0 -pr=profile-linux-x86 --lockfile=conan.lock --build=missing --order-by=recipe --format=json > mapviewer_linux_x86.json
conan graph build-order --requires=mapviewer/1.0 -pr=profile-linux-arm --lockfile=conan.lock --build=missing --order-by=recipe --format=json > mapviewer_linux_arm.json

# Merge and reduce build order files into a single build order file
conan graph build-order-merge --file=game_linux_x86.json --file=game_linux_arm.json --file=mapviewer_linux_x86.json --file=mapviewer_linux_arm.json --reduce --format=json > build_order.json

# Parse final build order JSON and spawn parallel jobs
```

global.conf
```
core.package_id:default_build_mode = full_mode
core.package_id:default_embed_mode = full_mode
core.package_id:default_non_embed_mode = full_mode
core.package_id:default_python_mode = full_mode
core.package_id:default_unknown_mode = full_mode
```

Are my assumptions above about using the profile correct? I ask because after my first attempt the build order operation failed with an "Invalid configuration" for the product (all of its dependencies were correctly calculated as "Build", however).

Edit: To clarify, some product build orders succeeded but others failed with "Invalid configuration" - so, looking for an initial sanity check/confirmation that the algorithm is correct.

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @radonish 

Thanks for your question.

> global.conf

Your global.conf might be extremely pessimistic (and inefficient), building from sources way more than should be built.

> Are my assumptions above about using the profile correct? I ask because after my first attempt the build order operation failed with an "Invalid configuration" for the product (all of its dependencies were correctly calculated as "Build", however).

The "Invalid configuration" is unrelated to the ``conan graph build-order``. It is a state that will also happen with a ``conan graph info`` or a ``conan install`` using the same inputs. It is just being exposed here, but not due to the ``build-order``.

It would be necessary to have more data, it seems that there are dependencies with a ``validate()`` method that ``raise ConanInvalidConfiguration`` under some conditions.

Can  you please check your recipes? Also providing a full output of the command might help.

**Comment by radonish** [comment]
Hello @memsharded,

Your background on what could cause the "Invalid configuration" was very helpful, thank you! I immediately found that it was due to a conanfile.py Conan 2.x change that snuck in via a reused/reengineered open source conanfile.py we use. It was now checking for a minimum CPP standard and that was failing for 1 specific profile we use (older ARM processor/older compiler).

That fix got me through the complete algorithm: master lock file generation, build orders generated for each product/profile combination, and then a final merge of all of those individual build orders via the `conan graph build-order-merge` command.

After visual inspection of the final merged build order JSON I'm happy to report that it looks perfect. Your changes in the area of both the lock file and build order merging will actually allow us to cut some build time off as we can now parallelize both at the configuration/profile level as well as independent product/application level. Thank you for these improvements!

(Regarding the global.conf package build modes - necessary for now based on how we version based on Git branch. I'll save that topic for another day!)

**Comment by radonish** [comment]
Related, follow up question for now parsing the JSON to then spawn off parallel Jenkins jobs.

The distributed Jenkins jobs the pipeline spawns off need the package reference (name/version/user/channel) and profile as parameters. In the [CI tutorial](https://github.com/memsharded/docs/blob/feature/devops_ci/ci_tutorial/products_pipeline/full_pipeline.rst) the configuration (debug vs. release) is parsed out of the `filenames` field. Is that the recommendation for extracting the profile? A user would need to make sure the intermediate build order filenames had the profile name within their name?

1. I assume there were/are complications with just including the profile name within the JSON output for that given package so it can be easily parsed out from a specific field?
2. The combined/master lock file needs to get transferred to the child Jenkins builder job, correct?

Thanks

**Comment by memsharded** [comment]
> After visual inspection of the final merged build order JSON I'm happy to report that it looks perfect. Your changes in the area of both the lock file and build order merging will actually allow us to cut some build time off as we can now parallelize both at the configuration/profile level as well as independent product/application level. Thank you for these improvements!

Happy that you did progress, and find the improvements useful! Indeed we worked hard and incorporated a lot of learnings in it.

> (Regarding the global.conf package build modes - necessary for now based on how we version based on Git branch. I'll save that topic for another day!)

As long as you are aware that it is possible in many cases to save a lot of CI time and cost with some different "package_id_modes", that is fine.

> The distributed Jenkins jobs the pipeline spawns off need the package reference (name/version/user/channel) and profile as parameters. In the [CI tutorial](https://github.com/memsharded/docs/blob/feature/devops_ci/ci_tutorial/products_pipeline/full_pipeline.rst) the configuration (debug vs. release) is parsed out of the filenames field. Is that the recommendation for extracting the profile? A user would need to make sure the intermediate build order filenames had the profile name within their name?

We just added in latest Conan 2.9 the ``profiles``->``args`` argument in the "build-order", specially useful for merged build-orders, to help mapping from filenames of build-order merged to the original profile arguments.

> The combined/master lock file needs to get transferred to the child Jenkins builder job, correct?

yes, the child jobs will need the lockfile, and of course the profiles and other configuration files. Most of the config can be managed with ``conan config install``, but the lockfile probably needs to be transferred via CI mechanisms.

**Comment by radonish** [comment]
> We just added in latest Conan 2.9 the `profiles`->`args` argument in the "build-order", specially useful for merged build-orders, to help mapping from filenames of build-order merged to the original profile arguments.

Ok, I will ensure the profile name is in the filename for the build order JSON file and then parse it out from the `filenames` field in the JSON from the merged build order file. I assume there are issues with having a distinct `profiles` field in the JSON due to it being an optional argument?

> > The combined/master lock file needs to get transferred to the child Jenkins builder job, correct?
> 
> yes, the child jobs will need the lockfile, and of course the profiles and other configuration files. Most of the config can be managed with `conan config install`, but the lockfile probably needs to be transferred via CI mechanisms.

Yes, with Conan 1.x we were already doing this and will continue to do so (transferring lock file via Artifactory, and doing `conan config install`/other setup within the pipeline).

Thanks for the feedback!

**Comment by memsharded** [comment]
> Ok, I will ensure the profile name is in the filename for the build order JSON file and then parse it out from the filenames field in the JSON from the merged build order file. I assume there are issues with having a distinct profiles field in the JSON due to it being an optional argument?

Not sure if I understand. With the new feature, this is not as necessary, as the profile-args field will contain exactly the ``-pr=xxx ..`` that are necessary. It is enough to enter in the ``profiles`` field with the ``filenames`` argument, but the name of the filename itself is no longer that critical.

**Comment by radonish** [comment]
Apologies, @memsharded - I had updated to 2.9.x on my test system but had not pushed it to the build farm so I was not seeing the new profile-args JSON field on the Jenkins node being tasked. I see it now - thank you!

**Comment by memsharded** [comment]
No prob, let me now how it goes with that new information.
If there is no further question, maybe this ticket can be closed?

**Comment by radonish** [comment]
I've updated the 1.x algorithm to work with the 2.9.x capabilities and it's working great. Excited to see what kind of time savings we get now that the product-level build orders can be merged. Thanks again for all your help!

**Comment by memsharded** [comment]
Happy to help, and happy to hear that, thanks for the feedback!
