### ISSUE TITLE
[bug]Deploy installed conanfile

### ISSUE THREAD

**Issue by jsallay** [conan-io/conan#17278]
### Describe the bug

I am running conan 2.8.0 on Ubuntu 22 with python 3.10.12

I believe that I have run into some unexpected behavior with the `deploy` function.  Let's say that I have a conanfile that defines a simple `deploy` method:
```
from conan import ConanFile
from conan.tools.files import copy

class Pkg(ConanFile):

    def deploy(self):
        copy(self, "*", src=self.package_folder, dst=self.deploy_folder)
```

If I run `conan install conanfile.py --deployer-package=*`, this fails with the following error:
```
======== Finalizing install (deploy, generators) ========
conanfile.py: Executing deploy()
ERROR: conanfile.py: Error in deploy() method, line 7
        copy(self, "*", src=self.package_folder, dst=self.deploy_folder)
        ConanException: copy() received 'src=None' argument
```

The error occurs because I haven't built the package yet, so the package folder doesn't exist.  (And I don't believe it would be populated on a conan install anyway).

In my case, my recipe depends on several packages that define a deploy method, so I use `--deployer-package=*` to make it easy.  It would be annoying to go into the conan file and specifically add each dependency (and check to see if it defines a deploy method).

I think that the expected behavior would be to not ever call the deploy package on the top level conanfile in an install command.  I think an acceptable alternative would be to have a syntax for `deployer-package` that means everything but the current package.  Maybe that is already possible, but I couldn't find anything in the docs.

My present work around is to add the following to the top of each deploy method:
```
def deploy(self):
    if self.package_folder is None:
       return
    ...
```

**Comment by memsharded** [comment]
Hi @jsallay 

Thanks for your report.

It seems that we have a test in our test suite that covers this scenario: https://github.com/conan-io/conan/blob/aa061ffd093eb07c34c3bea69ff2ae06294212c6/test/integration/conanfile/test_deploy_method.py#L49

Basically it seems:
- Conan ``--deployer-package`` seems to aim to support being called on the "consumer" conanfile, with ``conan install <path-to-consumer>``, so it calls its ``deploy()`` method, even in local
- The check for ``src=None`` was added explicitly in https://github.com/conan-io/conan/commit/17610ce2391172c5848dc1f9db377a0f9aa5c4ed

So it seems if we want to give flexibility and power to the users, it makes sense that the ``deploy()`` method of the current consumer is also called. As it is true that ``self.package_folder`` doesn't exist for a consumer recipe, as there is no package, then recipes that implement a ``deploy()`` method that are expected to be used as local consumers (as opposed as being deployed from the cache with ``--requires=pkg/version``), then they need to provision for ``self.package_folder`` being ``None``, and introduce a conditional or something. So this wouldn't be a workaround, but a correct approach if we want to be able to call with ``--deployer-package="*"``.


>  I think an acceptable alternative would be to have a syntax for deployer-package that means everything but the current package. Maybe that is already possible, but I couldn't find anything in the docs.

Yes, there is a syntax for deploying all dependencies except the current consumer, with
```
conan install . --deployer-package=!& --deployer-package=*
```

I don't think it is possible to just skip the ``deploy()`` for local consumer ``conanfile.py``, that would be breaking behavior, it is very likely that there will be already a few users depending on this behavior. So the above alternatives (cli syntax or in-recipe checks) would be the solutions.

**Comment by jsallay** [comment]
Thanks for the explanation.  I'll close the issue and add the note that in bash I need to have single quotes around !& for it work.  So `conan install . --deployer-package='!&' --deployer-package=*`
