### ISSUE TITLE
[question] test_package error LNK2019

### ISSUE THREAD

**Issue by pherzl** [conan-io/conan#17273]
### What is your question?

Hi!

I'm doing some research on how we can use Conan with our CMake projects.
I followed the [components tutorial](https://docs.conan.io/2/examples/conanfile/package_info/components.html) and then adjusted it to better match the existing structure of our projects. 
Essentially, a parent project (like the game engine in the tutorial), but with a subdirectory with its own CMakeLists for each library and namespaces  (like game-engine::algorithms, ...) 

When running  then `conan create .`  command, the test package works until I add an external dependency to the algorithms lib (I've tried it with fmt and zlib). Then I get linker errors:

```
1>Checking Build System
  Building Custom Rule C:/Users/phili/CLionProjects/conan/test_package/CMakeLists.txt
  example.cpp
algorithms.lib(algorithms.obj) : error LNK2019: unresolved external symbol zlibVersion referenced in function "void __cdecl algorithms(void)" (?algorithms@@YAXXZ) [C:\Users\phili\CLionProjects\conan\test_package\build\msvc-192-x86_64-14-relea
se\example.vcxproj]
```

In my understanding, it shouldn't be necessary to export/install the external libraries via CMake, or should it?
I'm using Clion and the Conan plugin (in case this is relevant)

My demo project can be found [here](https://github.com/pherzl/game-engine)

 Any help would be greatly appreciated.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @pherzl 

Thanks for your question.

You were very close, just a small detail :)

```diff
diff --git a/conanfile.py b/conanfile.py
index b1a9fbb..f0283f7 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -45,6 +45,7 @@ class game_engineRecipe(ConanFile):
     def package_info(self):
         self.cpp_info.components["algorithms"].libs = ["algorithms"]
         self.cpp_info.components["algorithms"].set_property("cmake_target_name", "game-engine::algorithms")
+        self.cpp_info.components["algorithms"].requires = ["fmt::fmt", "zlib::zlib"]

         self.cpp_info.components["network"].libs = ["network"]
         self.cpp_info.components["network"].set_property("cmake_target_name", "game-engine::network")
```

When declaring components it is necessary to define which components depend on which external dependencies, to avoid unnecessary overlinkage when using components that do not depend on those transitive dependencies.

**Comment by pherzl** [comment]
Great, now it works. 
Thank you very much for the help and the explanation!

**Comment by memsharded** [comment]
Great!
Closing the ticket as solved then, don't hesitate to create new tickets for any further question. Thanks for your feedback!
