### ISSUE TITLE
[question] Failed to find public header of editeable packages transitive dependency

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [conan-io/conan#17275]
### What is your question?

Ok so this is maybe a bit harder to explain so I recreated the setup in a toy project:

[test.tar.gz](https://github.com/user-attachments/files/17623499/test.tar.gz)

This is the structure. Notice that root is the project "test", while sublib is a sub-package within this repo:

```
.
├── include
│   └── main_include.h
├── src
│   └── main.cpp
├── sublib
│   ├── include
│   │   └── sublib.h
│   ├── src
│   │   └── sublib.cpp
│   ├── third_party
│   │   └── otherlib
│   │       ├── CMakeLists.txt
│   │       └── headeronly.h
│   ├── CMakeLists.txt
│   └── conanfile.py
├── .gitignore
├── CMakeLists.txt
└── conanfile.py
```

Now I have a project "test" that requires "sublib" as a dependency package. "sublib" in turn links to another library called "otherlib" which resides in a folder "third_party". "main_include.h" includes headerfiles from sublib, which in turn require headerfiles from otherlib. This is where it fails. While I can build sublib by itself (so it appears sublib.h can find `otherlib/headeronly`) the same is not true when I include sublib.h from "main_include.h".  This is the error I get:

```
conanfile.py (testpackage/0.1): CMake command: cmake --build "/home/sbeer/dev2/test/build/Release" '--' '-j20'
[ 50%] Building CXX object CMakeFiles/test.dir/src/main.cpp.o
In file included from /home/sbeer/dev2/test/src/main.cpp:1:
In file included from /home/sbeer/dev2/test/include/main_include.h:1:
/home/sbeer/dev2/test/sublib/./include/sublib.h:1:10: fatal error: 'otherlib/headeronly.h' file not found
#include "otherlib/headeronly.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake[2]: *** [CMakeFiles/test.dir/build.make:76: CMakeFiles/test.dir/src/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
ERROR: conanfile.py (testpackage/0.1): Error in build() method, line 30
        cmake.build()
        ConanException: Error 2 while executing cmake --build "/home/sbeer/dev2/test/build/Release" '--' '-j20'
```

To reproduce:

1. unzip project somewhere and cd into it.
2. Add sublib as an editeable pacakge:
```
conan editable add sublib sublib/0.1@user/testing
```
3. Build the subpackage
```
cd sublib
conan install .
conan build .
```
4. Try building the testpackage
```
cd ..
conan install .
conan build .
```

Now you should see the error.

It seems some of my header specifications are wrong. But for the live of me I can't figure out which ones. What am I not getting?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MartyMcFlyInTheSky 

Checking this. Some quick feedback:

- Make sure to not use any import ``from conans``. They are not necessary in your shared recipes and it can create issues. At the moment, just by luck, the necessary imports are the latest ones, so it works
- Try to drop the ``@user/channel`` part, or if using it make sure that those things are constants and not used for any kind of stage or quality dynamic information


It seems that you are missing in the ``sublib`` conanfile:
```python
def layout(self):
        cmake_layout(self)
        self.cpp.source.includedirs.append("third_party")
```
The ``third_party`` includes are not inside the ``include`` subfolder, so they are not added by the default ``cmake_layout()`` implementation, and the ``layout()`` needs to tell the consumers: When this package is in "editable" mode, there will be headers in this directory.

Please try that and let us know.

**Comment by MartyMcFlyInTheSky** [comment]
Thanks a lot @memsharded, that got me further at least! Now I'm encountering a linking error though. I again recreated it in the toy package. Here's the updated version:

[test.tar.gz](https://github.com/user-attachments/files/17630253/test.tar.gz)

The linker error is:

```
[100%] Linking CXX executable test
/usr/bin/ld: /home/sbeer/dev2/test/sublib/build/Release/libsublib.a(sublib.cpp.o): in function `myfunc()':
sublib.cpp:(.text+0x2): undefined reference to `ocv::do_something()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/test.dir/build.make:98: test] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
ERROR: conanfile.py (testpackage/0.1): Error in build() method, line 30
        cmake.build()
        ConanException: Error 2 while executing cmake --build "/home/sbeer/dev2/test/build/Release" '--' '-j20'
```

I can't understand how the symbol is not defined, since I link everything publicly in the whole chain. It appears I haven't understood some of the basics :/

And thanks a lot for your feedback! I removed the @user/channel for now. For the conans - part: I found it a bit hard to figure out what to replace it with. I need the conans tools to do some validations in the `validate(self)` method:

```
    def validate(self):
        if self.settings.compiler.get_safe("cppstd"):
            tools.check_min_cppstd(self, self._minimum_cpp_standard)
        min_version = self._minimum_compilers_version.get(str(self.settings.compiler))
        if not min_version:
            self.output.warn("{} recipe lacks information about the {} compiler support.".format(
                self.name, self.settings.compiler))
        else:
            if tools.Version(self.settings.compiler.version) < min_version:
                raise ConanInvalidConfiguration("{} requires C++{} support. The current compiler {} {} does not support it.".format(
                    self.name, self._minimum_cpp_standard, self.settings.compiler, self.settings.compiler.version))

```

Maybe this can already be done more elegantly today, but it's an example I also found in the issues tracker :)

**Comment by memsharded** [comment]
> And thanks a lot for your feedback! I removed the @user/channel for now. For the conans - part: I found it a bit hard to figure out what to replace it with. I need the conans tools to do some validations in the validate(self) method:

You have modern replacements compatible with Conan 2 in https://docs.conan.io/1/reference/conanfile/tools/build.html


Regarding your issue, the ``sublib`` recipe was still missing the information about the ``otherlib`` location and library name. You need to do:

```python
    def layout(self):
        cmake_layout(self)
        self.cpp.source.includedirs.append("third_party")
        # Note this path might change for different compilers and build systems
        # This works for VS-msvc which is multi-config
        self.cpp.build.libdirs.append(f"third_party/otherlib/{self.settings.build_type}")

    def package_info(self):
        self.cpp_info.libs = ["sublib", "otherlib"]
```

Note the comment in the layout() method. 
As a reference, internally the ``cmake_layout()`` does something like:
```python
    gen = conanfile.conf.get("tools.cmake.cmaketoolchain:generator", default=generator)
    if gen:
        multi = "Visual" in gen or "Xcode" in gen or "Multi-Config" in gen
    else:
        compiler = conanfile.settings.get_safe("compiler")
        multi = (compiler == "msvc")
```
To know if it is a multi-config generator or not, which changes the CMake layout

**Comment by MartyMcFlyInTheSky** [comment]
Ugh seems like I'm missing a lot of context about this `cmake_layout()` functionality. I adapted it and it works, thank you very much! Do I basically have to mimick what goes to the install location in the layout then?

**Comment by memsharded** [comment]
> Ugh seems like I'm missing a lot of context about this cmake_layout() functionality. I adapted it and it works, thank you very much! Do I basically have to mimick what goes to the install location in the layout then?

Yes, the core idea of the ``layout()`` is that it represents the location of artifacts in the "build" tree, as opposed to the "install" tree (the one in the final package after ``package()`` method put things in its place). As such, it needs to define:
- the location of headers in the source tree ``self.cpp.source.includedirs``
- the location of automatically generated headers in the build tree ``self.cpp.build.includedirs``, if existing
- the location of compiled libraries in the build tree ``self.cpp.build.libdirs``, ``self.cpp.build.bindirs``, depending on the platform
- Other fields like ``self.cpp_info.libs`` might be used from the ``package_info()`` as those do not really depend on the location, and the final used ``cpp_info`` is the result of merging the ``self.cpp.source``, ``self.cpp.build`` and ``self.cpp_info``

**Comment by MartyMcFlyInTheSky** [comment]
That's actually very helpful to know! Using this I could solve all problems except I still have one linking error. If I compile the sublib, it works fine. But when I compile the test executable it will fail with this:
 
```
/usr/bin/ld: /home/user/dev/test/sublib/build/Release/libsublib.a(LogFile.cpp.o): in function `spdlog::sinks::daily_filename_calculator::calc_filename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tm const&)':
LogFile.cpp:(.text._ZN6spdlog5sinks25daily_filename_calculator13calc_filenameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK2tm[_ZN6spdlog5sinks25daily_filename_calculator13calc_filenameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK2tm]+0xec): undefined reference to `fmt::v10::vformat[abi:cxx11](fmt::v10::basic_string_view<char>, fmt::v10::basic_format_args<fmt::v10::basic_format_context<fmt::v10::appender, char> >)'
/usr/bin/ld: /home/user/dev/test/sublib/build/Release/libsublib.a(LogFile.cpp.o): in function `spdlog::sinks::daily_file_sink<std::mutex, spdlog::sinks::daily_filename_calculator>::sink_it_(spdlog::details::log_msg const&)':
LogFile.cpp:(.text._ZN6spdlog5sinks15daily_file_sinkISt5mutexNS0_25daily_filename_calculatorEE8sink_it_ERKNS_7details7log_msgE[_ZN6spdlog5sinks15daily_file_sinkISt5mutexNS0_25daily_filename_calculatorEE8sink_it_ERKNS_7details7log_msgE]+0x15a): undefined reference to `spdlog::details::file_helper::write(fmt::v10::basic_memory_buffer<char, 250ul, std::allocator<char> > const&)'
/usr/bin/ld: /home/user/dev/test/sublib/build/Release/libsublib.a(LogEntrySender.cpp.o): in function `LogEntrySender::send()':
LogEntrySender.cpp:(.text+0x197): undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v10::basic_string_view<char>, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)'
/usr/bin/ld: /home/user/dev/test/sublib/build/Release/libsublib.a(LogEntrySender.cpp.o): in function `LogEntrySender::flush()':
LogEntrySender.cpp:(.text+0x2d9): undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v10::basic_string_view<char>, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/test.exe.dir/build.make:258: test.exe] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/test.exe.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

Sublib in this case is a consumer of the spdlog package. I have adapted the paths and names to match the toy repo but I didn't manage to come up with a toy project that produces these kind of errors yet. Maybe you have seen these kinds of errors though. So since sublib depends in this case on spdlog could it be that the compiler optimized out some stuff in libsublib.a that's necessary when trying to call associated functions from test application? If so how do I prevent it?

**Comment by memsharded** [comment]
It might be missing something like the ``package_type`` or  something like that, so it is not propagating ``fmt`` linkage down to the consumers, but yeah, it might be a bit challenging to know without being able to reproduce.

You might try to add ``self.requires("spdlog/...", transitive_headers=True, transitive_libs=True)`` in your recipe, this could be necessary in some (exceptional) cases, and see what it happens, but it would be better if this weren't necessary, but it really depends on how the libraries interact with each other.

**Comment by MartyMcFlyInTheSky** [comment]
Thanks for the hint, didn't know about these options! Unfortunately the error is still there... I'll try to extend the toy example, but it will take me a while since the company decided on some more urgent task in the meantime. I'll close this until further notice, thanks again!
