### ISSUE TITLE
[question] Github Packages

### ISSUE THREAD

**Issue by andromeda306** [conan-io/conan#17271]
### What is your question?

Could anyone please explain how to authenticate to github packages when using conan? (is it even possible?) I'm currently using the following commands but cannot get past authenticating and uploading the package itself. For additional context I am performing the action as myuser who belongs to the myorg org.
```
conan profile detect
conan install demo --profile default --build=missing
conan create demo --name=hellolibrary --version=1.0 --user=myorg --channel=stable

conan remote add github https://myorg.pkg.github.com/conan-demo
conan remote list
    conancenter: https://center.conan.io [Verify SSL: True, Enabled: True]
    github: https://myorg.pkg.github.com/conan-demo [Verify SSL: True, Enabled: True]
conan remote login github myuser -p "$PAT_SECRET"
   ERROR: b'<!DOCTYPE html><title>Not Found</title>\n<body>The requested URL is was not found.</body>\n</html>\
   ...
conan upload hellolibrary/1.0@myorg/stable --remote github --confirm
    ERROR: 404: Not Found. [Remote: github]
````

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @andromeda306 

Up to our knowledge, Github packages do not support Conan packages. Unless they have released it recently, this is not expected to work. You need to use a package server that supports Conan, we have ArtifatoryCE that is free for Conan package, you can download it from our page: https://conan.io/downloads

**Comment by andromeda306** [comment]
Thanks for confirming. Following some additional research I was afraid this was the case.
