### ISSUE TITLE
[feature] Better handling of invalid CONAN_LOG_LEVEL values

### ISSUE THREAD

**Issue by SoShiny** [conan-io/conan#17279]
### What is your suggestion?

Used version 2.9.1.

Observation
===

```bash
CONAN_LOG_LEVEL=verbose conan config home
````

Works for `CONAN_LOG_LEVEL` values of `quiet`, `error`, `warning`, `notice`, `status`, `verbose`, `v`, `debug`, `vv`, and `trace`.
This is in line with the `-v` options of `conan config`.

_However_, "unsetting" the `CONAN_LOG_LEVEL` variable by `export CONAN_LOG_LEVEL=` or running

```bash
CONAN_LOG_LEVEL= conan config home
```

result in the error message

```bash
ERROR: Invalid argument '-v'
```

Similarly, specifying some random value for `CONAN_LOG_LEVEL` will still refer to the invalid argument `-v<randomvalue>`.

This is confusing behavior, since we don't explicitly specify `-v` on the command line. It is even more confusing for the case of setting `CONAN_LOG_LEVEL=` to an empty value (using `unset CONAN_LOG_LEVEL` works). 

Change in behavior
===

a) Check the value for `CONAN_LOG_LEVEL` before passing its value as an argument further, and print a more informative error message.
b) Allow unsetting with `export CONAN_LOG_LEVEL=`

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @SoShiny 

Thanks for your feedback

Doing https://github.com/conan-io/conan/pull/17280 to improve a bit the UX for those wrong values for CONAN_LOG_LEVEL. Planned for next 2.10 release
