### ISSUE TITLE
Possible to override configuration when using conan build tools

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1728]
I am trying to build a library from a pre-existing visual studio solution.  It has the following configurations listed in the .sln file: 
```
                Debug No NetMon|Win32 = Debug No NetMon|Win32
		Debug No NetMon|x64 = Debug No NetMon|x64
		Debug|Win32 = Debug|Win32
		Debug|x64 = Debug|x64
```
Conan passes x86 by default.  Is there any way to override this and tell it to pass in Win32, or simply provide the whole string?

**Comment by lasote** [comment]
No, currently it will use "x86" if the architecture is "x86".
We need to check the possible values of the Platform and understand why Win32 is there. Probably we could introduce an "else" to pass the "arch" specified parameter if it doesn't match with the common ones.

In the meantime, you could use two approaches:

1. use the tools.replace_in_file("myfile.sln", "|Win32", "|x86") 
2. Create the msbuid command yourself.

**Comment by solvingj** [comment]
Thanks, ended up doing strongreplace on the command aftrer tools creates it. I found two unrelated projects using Win32 now, must have been old convention.
