### ISSUE TITLE
[question] Maintained status on Conan center

### ISSUE THREAD

**Issue by Jorissss** [conan-io/conan#17287]
### What is your question?

Hi! 

On conancenter, when viewing the tab with versions of packages, there is a checkmark under the leftmost column that states 'maintained version' vs 'unmaintained version' when hovered over:

![image](https://github.com/user-attachments/assets/ad1ed3c1-191d-4777-a49a-fab65d39e740)

What does this mean exactly? E.g. for ffmpeg it states that version 5.0 is maintained but according to https://endoflife.date/ffmpeg it is no longer supported.

Is it possible to retrieve this information through the command line interface? I need an inventory of the level of support of our software bill of materials and was hoping to use this to automate part of that.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @Jorissss  - 

Those check marks correlate to whether or not the "recipe" itself is still actively maintained / checked on CI for _that version_ - and it bears no correlation as to whether or not the version of the library is maintained by the upstream maintainers.

For any given recipe, the recipe is up-to-date for versions listed in our Github repository for `conan-center-index`, e.g. for zlib
https://github.com/conan-io/conan-center-index/blob/master/recipes/zlib/config.yml

and for ffmpeg
https://github.com/conan-io/conan-center-index/blob/master/recipes/ffmpeg/config.yml

This only refers to the recipe itself - this means, for example, that if a user reports that a recipe has an issue for a specific version, we will not be fixing or addressing issues for the recipe itself for versions of the recipe that are no longer maintained by us.

There are no ways to retrieve this via the command line interface. Perhaps we need to clarify in our website that the warning is only for _recipes_ and not the actual software.

**Comment by memsharded** [comment]
Also, @Jorissss if you have those requirements like providing sboms then it is likely you want more control over the dependencies,  please have a look to https://docs.conan.io/2/devops/using_conancenter.html.

You might also be interested in our related extensions commands in https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/sbom

**Comment by Jorissss** [comment]
@jcar87 I see, thanks a lot for the detailed clarification.

@memsharded Thanks, will definitely explore these tools.
