### ISSUE TITLE
[question] How to retrieve package info from conan remote via "conan list" command?

### ISSUE THREAD

**Issue by sbrett9** [conan-io/conan#17282]
### What is your question?

Hi,

I seem to be having trouble retrieving package info information from both my Artifactory servers at my workplace.
I one server is internally referred to as being a  "legacy" one, running 7.18.5 and another, newer, one is running 7.41.7, which I have labeled "notsolocal".
Using conan client 2.9.0 in WSL2 ubuntu 22.04  on Windows 10, I am unable to  see the package info cmake_lib starter packages built  and uploaded to either of the servers.

Running the command :conan list "mypackage/*:*" -r legacy

results in a full on HTTPConnectionPool max retries exceeded with url: blah blah

However, running: conan list "mypackage/1.0" -r  legacy shows me at least the recipe, if none of the packages.

Running the command: conan list "mypackage/*:*" -r notsolocal 

results in  output like 

Found 1 pkg/version recipes matching mypackage/* in notsolocal
```
notsolocal
  mypackage
    mypackage/1.0
      revisions
        64f053e99e7de1c3741f80ac0d5911cf (2024-11-06 01:40:14 UTC)
          packages
```
Looking on the artifactory UI for both it's clear to see that the packages are present. Each package for a revision has conaninfo.txt files alongside them. Navigating on the "legacy" server's webui to one of the packages and trying to select the "conan package info" tab for it results in a nice error popup in the GUI about being unable to extract conan package information.
Same goes for notsolocal.

Client doesn't seem to be the cause either, as using conan 2.3.0 in a ubuntu 22.04 docker container results in the same behavior.

At first I thought that the packages were not getting uploaded, which was why I could not see the package info when using a wildcard pattern with conan list, but I'm starting to think now that this is more server related, as, when running conan list against the local cache for the same packages, I'm shown everything I want.

The big problem here is that without this, the package query patterns for conan list do not work for finding arm or x64 packages and I can't do some things I need to with our build automation tools that need updates to pull certain things out of artifact based on these patterns.

If it's a server side thing, which version of Artifactory do we need to update at least our notsolocal server to? Clearly  7.41.7 isn't good enough? 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sbrett9 

Thanks for your question.

Yes, I think that is the main reason, you need to update to a more modern Artifactory.
For example there is a bug fix related to listing packages https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.52 

> Fixed an issue whereby, when running the Conan 2.0 
Conan List
 REST API, Artifactory returned a 500 error.

That was in Artifactory 7.52, but we'd recommend to use at least 7.63.
Please update and let us know.

**Comment by memsharded** [comment]
Hi @sbrett9 

Did you manage to upgrade your Artifactory version?
Any further question or issue? Thanks for your feedback.

**Comment by sbrett9** [comment]
Not  yet. Its a shared resource unfortunately and I am not the
administrator. It may be yet some time before I can verify.

**Comment by memsharded** [comment]
Ok, let's close this ticket by now, as it wouldn't require any action or response from us at the moment.

Please comment on it or re-open it if necessary when you have more info. Thanks for the feedback!
