### ISSUE TITLE
[bug] git.fetch_commit() throws an error when downloading sources to subfolder

### ISSUE THREAD

**Issue by bkarasm** [conan-io/conan#17295]
### Describe the bug

`conan.tools.scm.Git.fetch_commit()` method throws an error when `folder` argument is passed to Git class constructor:

```python
def source(self):
    git = Git(self, folder="myFolder")
    git.fetch_commit(url, commit=self.conan_data["sources"]["commit"])
``` 

Error message:
```bash
ERROR: mypackage/1.2.3: Error in source() method, line 65
        git.fetch_commit(url, commit=self.conan_data["sources"]["commit"])
        FileNotFoundError: [Errno 2] No such file or directory: 'myFolder'
```

It seems that `mkdir(self.folder)` is missing in the body of `fetch_commit()` method - similarly as it is done in `clone()` method.

**Comment by memsharded** [comment]
Hi @bkarasm 

Thanks for your report.
It seems it could be a small UX improvement (what we call a ``fix``, not a ``bugfix``), and I think it should be very straightforward, would you like to do it yourself and contribute a PR?

**Comment by bkarasm** [comment]
Sure, I can give it a try.
