### ISSUE TITLE
Elicpse CDT and Code Completion

### ISSUE THREAD

**Issue by joesulewski** [conan-io/conan#17309]
### What is your question?

Hello,

I have a project I'm working on, and I was able to get Conan to work with Linux Make files and Visual Studio projects. I want to be able to use Eclipse for a Linux IDE.  I can create a new CMake project and point it to my projects home directory.  From here I can compile the output and run the debugger to do step debugging. 

The last issue for me is that the IDE doesn't understand any of the external library includes.   For example, I'm using Log4CXX and it can't find the includes, in fact, it can't even find anything from the standard library.  

Has anyone been able to use Eclipse and get code completion working with Conan generated CMakefiles?  Any help on getting the indexer working would be very helpful.

Thanks,
Joe

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @joesulewski 

Thanks for your question.

It is the CMake Eclipse generator, isn't it? 
Is it that the IDE fails to locate the headers for the highlighting and it will underline them as errors, but still builds correctly (as it is CMake building), or is it failing to build too?

**Comment by joesulewski** [comment]
Hello,

Thanks for the quick reply.  

I'm using the CMake for Unix Files generator, I read the Eclipse CDT is deprecated and it didn't seem to work. 

Regarding your question you have it correct, the IDE underlines uses of external libraries or standard libraries as errors, however, make clean and make work perfect.  

Joe

**Comment by memsharded** [comment]
Great, thanks for the feedback.

Then I am afraid that there is little that can be done from the Conan side, and this is lying between CMake and Eclipse. 
We can leave the ticket opened for a bit to see if there is some other Eclipse user out there that could give some hint.

**Comment by joesulewski** [comment]
I was afraid that was true, but thanks for keeping it open a bit.   I thought maybe it wasn't able to parse something from the generated CMake data. 

Any plans to make a Conan integrated plugin for eclipse like CLion or Visual Studio?

**Comment by memsharded** [comment]
> Any plans to make a Conan integrated plugin for eclipse like CLion or Visual Studio?

I am afraid not, there isn't enough interest, and if any it is disappearing, we have seen a decline of people using Eclipse in the last years, specially with VSCode gaining popularity.

**Comment by memsharded** [comment]
I am closing this ticket as responded (or not planned regarding the Eclipse plugin).
Thanks very much for your feedback!
