### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'conans.conan' 

### ISSUE THREAD

**Issue by arpan-kusari** [conan-io/conan#17317]
### Describe the bug

Environment details: Ubuntu 22.04, python3 version 3.10.12, conan 2.9.2

After installing conan using `pip3 install conan`, I run `conan remote list` and get the following output:

```
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 5, in <module>
    from conans.conan import run
ModuleNotFoundError: No module named 'conans.conan'

```

### How to reproduce it

```
pip3 install conan
conan remote list
```

**Comment by memsharded** [comment]
Hi @arpan-kusari 

Thanks for your feedback.

This doesn't look like a bug in Conan, but some issue in the installation (or more exactly in the update).
Can you please try to make sure to completely uninstall conan, and then installing again?

**Comment by memsharded** [comment]
Hi @arpan-kusari 

Did you try that? 
Any other question or feedback?

**Comment by arpan-kusari** [comment]
Hi,
I have reinstalled everything but getting the same bug. Not sure what else
I can try.

**Comment by memsharded** [comment]
What do you have exactly in ``/usr/local/bin/conan``?  Is that a symlink? 
Please share the contents of that file if not, or follow the symlink to report where it is pointing, and what is in that location.

This still seems like a legacy Conan 1.X installation that is not completely cleaned. Did you remove the ``/usr/local/bin/conan`` file while re-installing it (by the way, it is not just re-installing, it is making sure that the previous installation is completely removed, eliminating all possible conan related files).

**Comment by arpan-kusari** [comment]
I have no idea why but installing with the github develop2 branch removed the error. Thanks for your help.

**Comment by memsharded** [comment]
Thanks for the feedback!
