### ISSUE TITLE
CMakeDeps missing include path from transitive dependency

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#17318]
Conan 2.9.2
CMake 3.28.1

I have the following chain of dependencies:

test package A -> component A -> component B

Component B exposes the following package info:
```
  def package_info(self):
    self.cpp_info.resdirs = ["res"]
    self.cpp_info.includedirs = ["include"]
    self.cpp_info.libs = ["B"]

    self.cpp_info.set_property("cmake_target_name", "componentB::B")
```
Component A depends on B:
```
  def requirements(self):
    self.requires("B/0.0.1")
```
The test package for component A is a very generic test package.
When building component A with `conan create...` the component builds just fine, but when it comes to build the test package it cannot find include paths for B. Looking in the generated B-release-x86_64-data.cmake file I can see:
```
set(B_INCLUDE_DIRS_RELEASE )
...
set(B_LIB_DIRS_RELEASE "${B_PACKAGE_FOLDER_RELEASE}/lib")
...
set(B_LIBS_RELEASE B)
```
As we can see above the include paths are not set in the file generated by CMakeDeps.
If I look in the corresponding generated file from build the component A package itself (burried in the conan cache folder) I see that here the include dirs is actually set properly:
```
set(B_INCLUDE_DIRS_RELEASE "${B_PACKAGE_FOLDER_RELEASE}/include")
...
set(B_LIB_DIRS_RELEASE "${B_PACKAGE_FOLDER_RELEASE}/lib")
...
set(B_LIBS_RELEASE B)
```

What am I doing wrong here?
I have actually recently seen similar issues with a consumer recipe depending on libcurl which transitively depends on libssh2.
Here the issue was that the generated cmake deps file for libssh2 was actually missing the value for XXX_LIBS_RELEASE and not the include dirs.
I do not know if that is related or not.

Regards
Klaus

**Comment by klausholstjacobsen** [comment]
Update:
If I add an explicit dependency to B from the test package...
```
    def requirements(self):
        self.requires(self.tested_reference_str)
        self.requires("B/0.0.1")
```
....then it works and the proper CMakeDeps files are generated. This is the exact same way I solved the libcurl/libssh2 problem... by adding an explicit dependency on libssh2 to my consumer recipe.

I would expect to not have to do this as the test package should have no explicit knowledge about a transitive dependency on component B.

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

This happens when ``A`` public headers include ``B`` public headers.
The default by Conan is assuming encapsulation of dependencies (which would be the a good default for most cases if possible to achieve). So it is expected that the B headers are not visible downstream.

To make them visible, the requirement has to declare it "I will include publicly the headers, so they need to be transitive" (Conan is not analyzing source code). It can be done with:

```python
 self.requires("B/0.0.1", transitive_headers=True)
```
Please try that and let us know.

**Comment by klausholstjacobsen** [comment]
You are the man!

It works!

**Comment by Enhex** [comment]
@memsharded today i fell into this pitfall myself and wasted hours debugging it.
"transitive_headers" isn't mentioned in the tutorials (only in the reference) and `conan new`'s generated conanfile doesn't include it.
users won't know it exists and could assume Conan is broken.

I think it should be mentioned in:
https://docs.conan.io/2/tutorial/creating_packages.html
ideally in a way that's hard to miss in case users skim it.

or better yet default to something that just works™, seems like a premature optimization.
though i understand this decision was already made.
