### ISSUE TITLE
[question] Deploying files from skipped dependencies

### ISSUE THREAD

**Issue by schaber-hxg** [conan-io/conan#17313]
### What is your question?

Hi!
I have a question regarding deploying files from the conan cache to another directory. We do that by parsing the json output of a _conan install_ command. We know of the (custom) deployers feature, more on that later.
As i understand, the _package_folder_ is set to None on purpose for skipped dependencies in the graph. You explained that in this issue: https://github.com/conan-io/conan/issues/14299#issuecomment-1637231388. 
I guess one reason to skip is when linking a static library A into another shared library B that is then used by an application. In this case no library files of A (e.g. .dll or .so) are required by the application. In our case this assumption (that no files of A need to be made available to the application) does not hold: the static library A provides resource files that may be used by the application (via lib A).
The libraries in question are Qt with webengine and libdrm. libdrm provides files via _cpp_info.resdirs_ that we want to deploy to our application. We read the json output of a conan install command to get the paths to the library files and deploy them. For libdrm the package_folder is None and we cannot get the resource files. We are aware of the deployers feature of conan install and evaluate using it. However, even when using deployers the package_folder is still None I think.

We are still investigating if the resources files of libdrm are really required in our application. Regardless of the outcome it would be interesting what your thoughts are on this.
Are you aware of that use case? Is the qt package supposed to include the resource files of libdrm (and it's a bug in the qt recipe)? Is there another way to access the resource files if the package_folder is None?

Conan version 2.7.1, OS: Linux, compiler gcc

Thanks for your work on conan

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi! More can be said about the QT aspects of your question, but regarding your skip issue, if your use-case requires all binaries to be present, you might want to try using the `tools.graph:skip_binaries=False` conf (either your profile or CLI invokation), which will force Conan not to skip anything you might need for the deployers/your custom setup.

Let me know if this helps, and I'll let others chime in for the other questions :)

**Comment by schaber-hxg** [comment]
Thanks for the quick answer! I gave the conf option a try and it does work for us, the packages are no longer skipped and their paths appear in the json output. An important detail is to set the conf only for the host profile. If it also applies to the build profile the conan install command includes the the build requirements, which is not desired for the package consumer.

**Comment by memsharded** [comment]
> An important detail is to set the conf only for the host profile. If it also applies to the build profile the conan install command includes the the build requirements, which is not desired for the package consumer.

yes, that is correct, very often only the ``host`` context is desired, this is one of the advantages of the dual profile, it gives finer control over this kind of thing.

Then maybe we can close this question as solved? Thanks for the feedback!

**Comment by schaber-hxg** [comment]
Thanks for your replies, our issue is resolved and this question could be closed. However, I'd be interested if you consider the behavior of conan 2 described above as intended. If a library is statically linked and at the same time provides resource files, then, if this library gets skipped, the intended way to get the files is disabling the skipping conf? I'm asking because that feels a bit unexpected to me. For dynamic libs deploying works as usual (use a deployer), if static libs are involved you first have to switch a conf to get all packages processed. Maybe the package folder and res dirs could be set also for skipped libraries? Or static libs with res dirs should not be skipped?

**Comment by memsharded** [comment]
>  If a library is statically linked and at the same time provides resource files, then, if this library gets skipped, the intended way to get the files is disabling the skipping conf?

Depending on how those resources are used. If the resources are used at build/compile time, then the behavior is the same. But if the resources are used at run time, then the dependency indeed shouldn't be skipped. This could be specified with the:
```
self.requires("dep/version", run=True)
```
to indicate that such dependency is needed at runtime and as such cannot be skipped, and the binary is still necessary.

**Comment by schaber-hxg** [comment]
The run trait is also a good hint. As a quick experiment, I tried setting it in our applications conanfile.py so that modifying the qt recipe is not necessary: self.requires("library/version", override=True, run=True). I used override because it's not a direct dependency of our application. This did not seem to work, does it work with override in theory? Will look further into that, might very well be there is still a mistake on my side :). Thank you for the help so far.

**Comment by schaber-hxg** [comment]
Found an answer to my question: `self.requires("library/version", override=True, run=True)` does not work, the run trait is not respected in this case. I guess the require without run=True further down in the graph takes precedence.
Adding the run trait to the direct dependency works. Now we have even two options to fix our deployment :)
Again, thank you for your help and quick answers. Will close the question as completed.

**Comment by memsharded** [comment]
>  self.requires("library/version", override=True, run=True). I used override because it's not a direct dependency of our application. This did not seem to work, does it work with override in theory?

Indeed ,the ``override`` can only override the version, not traits (if the dependency is not even found in transitive dependencies, it is fully discarded).

Thanks very much for your feedback! Do not hesitate to open new tickets for any further question.

**Comment by Cyriuz** [comment]
I got a bit confused by this too when working on migrating to conan 2, but for my case I was trying to migrate this: https://docs.conan.io/1/howtos/collect_licenses.html

Maybe there is some official way to do it but I've been trying to make a deployer basically just iterating the dependencies and copying from the licenses folder. Wouldn't it make sense to populate the graph if the package exists in the cache? I understand that you want to avoid downloading it if it doesn't exist for a normal use case, and if you want it then you'll need to run without skip once.

**Comment by AbrilRBS** [comment]
Note that https://github.com/conan-io/conan-extensions/tree/main/extensions/deployers contains a license deployer that achieves your goals, from which you will still want to run with the skip disabled

**Comment by Cyriuz** [comment]
@AbrilRBS Thank you for the link! I assumed as much but didn't find it for some reason... Petition to link it in the migration guide or conan 1 docs :)
