### ISSUE TITLE
New CMakeDeps issues

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#17321]
Hi @memsharded, I've tried the new CMakeDeps generator, and ran into some problems: 

- Packages that use `cmake_find_mode=none` with a `fooConfig.cmake` file in the `cpp_info.builddirs` path (https://docs.conan.io/2/reference/tools/cmake/cmakedeps.html#disable-cmakedeps-for-installed-cmake-configuration-files) are no longer discovered. This path will need to be added to `CMAKE_FIND_ROOT_PATH` by `conan_cmakedeps_paths.cmake`. Adding them to `CMAKE_PREFIX_PATH` alone would not be sufficient in the case of cross-compilation, unless the `~/.conan2/p/b/fooabc/p` is already in the `CMAKE_FIND_ROOT_PATH`.
- There appears to be something wrong with the capitalization of the generated CMake targets. For example, when building a package `foo` that depends on OpenBLAS, the generated target `foo::foo` by Conan depends on `openblas::openblas`, whereas the actual generated OpenBLAS target is `OpenBLAS::OpenBLAS`.

If useful, I could open new issues with more information.

_Originally posted by @tttapa in https://github.com/conan-io/conan/issues/16324#issuecomment-2479341117_

**Comment by memsharded** [comment]
Thanks for your feedback @tttapa.

I have opened a new ticket for you. Lets have a look at those, (I thought that the first one should work, but lets check), and if necessary to split in separate tickets I'll let you know.

**Comment by tttapa** [comment]
Thanks!

Here's an example of the second issue: https://github.com/tttapa/conan-recipes/blob/11765d09410927dc001bb08de3f1a850e4b3e756/recipes/coinmumps/all/conanfile.py

```sh
git clone https://github.com/tttapa/conan-recipes
conan remote add tttapa-conan-recipes "$PWD/conan-recipes" --force
cd conan-recipes/recipes/ipopt/all
conan create . --version=3.14.16 --build=missing    # works
conan create . --version=3.14.16 --build=missing -c tools.cmake.cmakedeps:new=will_break_next    # does not work
```

<details><summary>Full output</summary>

```
======== Exporting recipe to the cache ========
ipopt/3.14.16: Exporting package recipe: /tmp/conan-recipes/recipes/ipopt/all/conanfile.py
ipopt/3.14.16: exports: File 'conandata.yml' found. Exporting it...
ipopt/3.14.16: Copied 1 '.yml' file: conandata.yml
ipopt/3.14.16: Copied 1 '.py' file: conanfile.py
ipopt/3.14.16: Exported to cache folder: /home/pieter/.conan2/p/ipopt9a746552a1ee1/e
ipopt/3.14.16: Exported: ipopt/3.14.16#01c815c005a134ac871a5d8b8bd8191c (2024-11-15 18:14:35 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[conf]
tools.cmake.cmakedeps:new=will_break_next

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    coinmumps/3.0.7#53df8e3d1b90efec14bba86a1bf391c2 - Cache
    ipopt/3.14.16#01c815c005a134ac871a5d8b8bd8191c - Cache
    openblas/0.3.27#c16c3dbdf45e4a4ff56f8ada8631a2f3 - Cache

======== Computing necessary packages ========
openblas/0.3.27: Main binary package 'bc6c7a69ae72a75e92e2dcbdc9e3560daef36419' missing
openblas/0.3.27: Checking 11 compatible configurations
openblas/0.3.27: Found compatible package 'eb6292a0e957646b54c2bfd72a2a6c8d0b7a1aac': compiler.cppstd=17
ipopt/3.14.16: Forced build from source
Requirements
    coinmumps/3.0.7#53df8e3d1b90efec14bba86a1bf391c2:da8cda98ce5c347f86e367506d27090df7150d5e#17436017e49b2b4c6eb2d8c6b264cc14 - Cache
    ipopt/3.14.16#01c815c005a134ac871a5d8b8bd8191c:aee99e0e9ca0db3bc3f87a71d61629d23c32e9b4 - Build
    openblas/0.3.27#c16c3dbdf45e4a4ff56f8ada8631a2f3:eb6292a0e957646b54c2bfd72a2a6c8d0b7a1aac#6231bd84d94ddb4211bfaa4d6287e04c - Cache

======== Installing packages ========
openblas/0.3.27: Already installed! (1 of 3)
coinmumps/3.0.7: Already installed! (2 of 3)
ipopt/3.14.16: Calling source() in /home/pieter/.conan2/p/ipopt9a746552a1ee1/s
ipopt/3.14.16: Unzipping 3.14.16.tar.gz to /home/pieter/.conan2/p/ipopt9a746552a1ee1/s

-------- Installing package ipopt/3.14.16 (3 of 3) --------
ipopt/3.14.16: Building from source
ipopt/3.14.16: Package ipopt/3.14.16:aee99e0e9ca0db3bc3f87a71d61629d23c32e9b4
ipopt/3.14.16: Copying sources to build folder
ipopt/3.14.16: Building your package in /home/pieter/.conan2/p/b/ipopte17a619841258/b
ipopt/3.14.16: Calling generate()
ipopt/3.14.16: Generators folder: /home/pieter/.conan2/p/b/ipopte17a619841258/b
ipopt/3.14.16: Generating aggregated env files
ipopt/3.14.16: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
ipopt/3.14.16: Calling build()
ipopt/3.14.16: RUN: "/home/pieter/.conan2/p/b/ipopte17a619841258/b/configure" --disable-shared --enable-static --prefix=/ '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--with-lapack= ' --with-mumps=yes
[...]
configure: Configuration of Ipopt successful

ipopt/3.14.16: RUN: make -j8
Making all in src
make[1]: Entering directory '/home/pieter/.conan2/p/b/ipopte17a619841258/b/src'
[...]
make[1]: Leaving directory '/home/pieter/.conan2/p/b/ipopte17a619841258/b'

ipopt/3.14.16: package(): Packaged 6 '.h' files
ipopt/3.14.16: package(): Packaged 79 '.hpp' files
ipopt/3.14.16: package(): Packaged 1 '.inc' file: IpReturnCodes.inc
ipopt/3.14.16: package(): Packaged 2 '.la' files: libipopt.la, libsipopt.la
ipopt/3.14.16: package(): Packaged 2 '.a' files: libipopt.a, libsipopt.a
ipopt/3.14.16: package(): Packaged 1 '.pc' file: ipopt.pc
ipopt/3.14.16: package(): Packaged 2 '.md' files: README.md, ChangeLog.md
ipopt/3.14.16: package(): Packaged 2 files: AUTHORS, LICENSE
ipopt/3.14.16: Created package revision 8d9eadcf5fd1383a17bc78f0650320c3
ipopt/3.14.16: Package 'aee99e0e9ca0db3bc3f87a71d61629d23c32e9b4' created
ipopt/3.14.16: Full package reference: ipopt/3.14.16#01c815c005a134ac871a5d8b8bd8191c:aee99e0e9ca0db3bc3f87a71d61629d23c32e9b4#8d9eadcf5fd1383a17bc78f0650320c3
ipopt/3.14.16: Package folder /home/pieter/.conan2/p/b/ipopte17a619841258/p
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: openblas/0.3.27
WARN: deprecated:     'env_info' used in: openblas/0.3.27

======== Launching test_package ========

======== Computing dependency graph ========
Graph root
    ipopt/3.14.16 (test package): /tmp/conan-recipes/recipes/ipopt/all/test_package/conanfile.py
Requirements
    coinmumps/3.0.7#53df8e3d1b90efec14bba86a1bf391c2 - Cache
    ipopt/3.14.16#01c815c005a134ac871a5d8b8bd8191c - Cache
    openblas/0.3.27#c16c3dbdf45e4a4ff56f8ada8631a2f3 - Cache

======== Computing necessary packages ========
openblas/0.3.27: Main binary package 'bc6c7a69ae72a75e92e2dcbdc9e3560daef36419' missing
openblas/0.3.27: Checking 11 compatible configurations
openblas/0.3.27: Found compatible package 'eb6292a0e957646b54c2bfd72a2a6c8d0b7a1aac': compiler.cppstd=17
Requirements
    coinmumps/3.0.7#53df8e3d1b90efec14bba86a1bf391c2:da8cda98ce5c347f86e367506d27090df7150d5e#17436017e49b2b4c6eb2d8c6b264cc14 - Cache
    ipopt/3.14.16#01c815c005a134ac871a5d8b8bd8191c:aee99e0e9ca0db3bc3f87a71d61629d23c32e9b4#8d9eadcf5fd1383a17bc78f0650320c3 - Cache
    openblas/0.3.27#c16c3dbdf45e4a4ff56f8ada8631a2f3:eb6292a0e957646b54c2bfd72a2a6c8d0b7a1aac#6231bd84d94ddb4211bfaa4d6287e04c - Cache

======== Installing packages ========
openblas/0.3.27: Already installed! (1 of 3)
coinmumps/3.0.7: Already installed! (2 of 3)
ipopt/3.14.16: Already installed! (3 of 3)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: openblas/0.3.27
WARN: deprecated:     'env_info' used in: openblas/0.3.27

======== Testing the package ========
Removing previously existing 'test_package' build folder: /tmp/conan-recipes/recipes/ipopt/all/test_package/build/gcc-11-x86_64-gnu17-release
ipopt/3.14.16 (test package): Test package build: build/gcc-11-x86_64-gnu17-release
ipopt/3.14.16 (test package): Test package build folder: /tmp/conan-recipes/recipes/ipopt/all/test_package/build/gcc-11-x86_64-gnu17-release
ipopt/3.14.16 (test package): Writing generators to /tmp/conan-recipes/recipes/ipopt/all/test_package/build/gcc-11-x86_64-gnu17-release/generators
ipopt/3.14.16 (test package): WARN: Using the new CMakeDeps generator, behind the 'tools.cmake.cmakedeps:new' gate conf. This conf will changenext release, breaking, so use it only for testing and dev
ipopt/3.14.16 (test package): Generator 'CMakeDeps' calling 'generate()'
ipopt/3.14.16 (test package): Generator 'CMakeToolchain' calling 'generate()'
ipopt/3.14.16 (test package): CMakeToolchain generated: conan_toolchain.cmake
ipopt/3.14.16 (test package): CMakeToolchain generated: /tmp/conan-recipes/recipes/ipopt/all/test_package/build/gcc-11-x86_64-gnu17-release/generators/CMakePresets.json
ipopt/3.14.16 (test package): CMakeToolchain generated: /tmp/conan-recipes/recipes/ipopt/all/test_package/CMakeUserPresets.json
ipopt/3.14.16 (test package): Generating aggregated env files
ipopt/3.14.16 (test package): Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']

======== Testing the package: Building ========
ipopt/3.14.16 (test package): Calling build()
ipopt/3.14.16 (test package): Running CMake.configure()
ipopt/3.14.16 (test package): RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/tmp/conan-recipes/recipes/ipopt/all/test_package" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/tmp/conan-recipes/recipes/ipopt/all/test_package"
-- Using Conan toolchain: /tmp/conan-recipes/recipes/ipopt/all/test_package/build/gcc-11-x86_64-gnu17-release/generators/conan_toolchain.cmake
-- Conan toolchain: Defining architecture flag: -m64
-- Conan toolchain: C++ Standard 17 with extensions ON
-- Conan toolchain: Including CMakeDeps generated conan_find_paths.cmake
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring Targets for ipopt/3.14.16
-- Configuring Targets for coinmumps/3.0.7
-- Configuring Targets for openblas/0.3.27
-- Conan: Target declared imported STATIC library 'OpenBLAS::pthread'
-- Conan: Target declared imported INTERFACE library 'OpenBLAS::OpenBLAS'
-- Conan: Target declared imported STATIC library 'coinmumps::coinmumps'
-- Conan: Target declared imported STATIC library 'Ipopt::Ipopt'
-- Configuring done (0.2s)
CMake Error at build/gcc-11-x86_64-gnu17-release/generators/coinmumps-Targets-release.cmake:20 (target_link_libraries):
  The link interface of target "coinmumps::coinmumps" contains:

    openblas::openblas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  build/gcc-11-x86_64-gnu17-release/generators/coinmumpsTargets.cmake:6 (include)
  build/gcc-11-x86_64-gnu17-release/generators/coinmumps-config.cmake:6 (include)
  /home/pieter/.local/lib/python3.13/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  build/gcc-11-x86_64-gnu17-release/generators/Ipopt-Targets-release.cmake:7 (find_dependency)
  build/gcc-11-x86_64-gnu17-release/generators/IpoptTargets.cmake:6 (include)
  build/gcc-11-x86_64-gnu17-release/generators/IpoptConfig.cmake:6 (include)
  CMakeLists.txt:4 (find_package)


CMake Error at build/gcc-11-x86_64-gnu17-release/generators/Ipopt-Targets-release.cmake:25 (target_link_libraries):
  The link interface of target "Ipopt::Ipopt" contains:

    openblas::openblas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  build/gcc-11-x86_64-gnu17-release/generators/IpoptTargets.cmake:6 (include)
  build/gcc-11-x86_64-gnu17-release/generators/IpoptConfig.cmake:6 (include)
  CMakeLists.txt:4 (find_package)


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

ERROR: ipopt/3.14.16 (test package): Error in build() method, line 20
	cmake.configure()
	ConanException: Error 1 while executing
```

</details>

I'm using Conan 2.9.2 on Ubuntu 22.04 (x86_64), Python 3.10.14, CMake 3.28.4.

**Comment by memsharded** [comment]
Regarding the first issue, I have just checked, and there is already a test in https://github.com/conan-io/conan/blob/fabc81498dd673a03fd86326e6c3e858f1f7c3cc/test/functional/toolchains/cmake/cmakedeps/test_cmakedeps_new_paths.py#L50 that seems to be testing exactly this scenario.

Maybe the problem is that the file is named ``fooConfig.cmake``, but it should be named ``foo-config.cmake`` instead?

**Comment by memsharded** [comment]
Regarding the second issue, I have just tried in my ubuntu, and besides the fact that I had to install ``gfortran``, using the ``develop2`` branch, it worked :)

Sorry for not remember it, but there was a PR https://github.com/conan-io/conan/pull/17257 a couple of weeks ago, that has been merged, and it is ready for release in next Conan 2.10. This PR fixed this issue too. 

You can give it a try now running from the ``develop2`` source branch from the repo, or wait until the end of the month for the 2.10.0 release. Thanks for your feedback!

**Comment by tttapa** [comment]
Thanks, switching from 2.9.2 to develop2 indeed solves problem 2. Problem 1 is not yet fixed when cross-compiling, though. I'll try to isolate the problem and post a minimal example.

**Comment by tttapa** [comment]
Here's an example of problem 1, I'm having the same issue even when not cross-compiling.

https://github.com/tttapa/conan-recipes/blob/11765d09410927dc001bb08de3f1a850e4b3e756/recipes/guanaqo/all/conanfile.py#L81-L83

In a `python:3.13-bookworm` container:

```sh
docker run -it --rm python:3.13-bookworm bash
apt update && apt install -y cmake
python3 -m pip install -U 'conan@git+https://github.com/conan-io/conan#develop2'
conan profile detect
git clone https://github.com/tttapa/conan-recipes
conan remote add tttapa-conan-recipes "$PWD/conan-recipes" --force
cd conan-recipes/recipes/guanaqo/all
conan create . --version=1.0.0-alpha.1 --build=missing  # works
conan create . --version=1.0.0-alpha.1 --build=missing -c tools.cmake.cmakedeps:new=will_break_next  # does not work
```

**Comment by memsharded** [comment]
Thanks very much for the reproducible case. This kind of reporting with reproducible steps really helps!

I think the problem is the one commented above:

> guanaqoConfig.cmake

Conan is following the convention of using ``LibraryConfig.cmake`` if package name is not lowercase or ``library-config.cmake`` otherwise. In this case ``guanaqo-config.cmake`` should work.

This might be changed in the new CMakeDeps generator, but there might be other issues related to this naming, so maybe the recommendation would still be to try to change the filenames.

**Comment by memsharded** [comment]
I am doing https://github.com/conan-io/conan/pull/17330 to add support for ``fooConfig.cmake`` in-package files, even if it is not the general recommendation.

**Comment by tttapa** [comment]
Thanks, I appreciate the help! I wasn't aware of the distinction, is there a reason why `fooConfig.cmake` is not recommended? If I understand correctly, there's no difference as far as CMake's `find_package` is concerned, and the [CMakeToolchain: Using xxx-config.cmake files inside packages example](https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html) also seems to use the `mypkgConfig.cmake` convention.

Follow-up question: does this approach support multiple `xxx-config.cmake` or `xxxConfig.cmake` files? In some of my larger projects, I'm using one `fooConfig.cmake` and multiple `fooCompXXXConfig.cmake` files for optional components (which are used internally in the main `fooConfig.cmake`).  
On the other hand, maybe I should just bite the bullet and mirror the entire package and component structure in `cpp_info`, but I haven't found the courage yet :)

**Comment by memsharded** [comment]
> Thanks, I appreciate the help! I wasn't aware of the distinction, is there a reason why fooConfig.cmake is not recommended? If I understand correctly, there's no difference as far as CMake's find_package is concerned, and the [CMakeToolchain: Using xxx-config.cmake files inside packages example](https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html) also seems to use the mypkgConfig.cmake convention.

Yes, that is correct, and seems our own example is not following the convention, we might want to change it too. But it is true that it is mostly a widespread convention and that CMake allows both, this is why I am adding the PR support for it.

> Follow-up question: does this approach support multiple xxx-config.cmake or xxxConfig.cmake files? In some of my larger projects, I'm using one fooConfig.cmake and multiple fooCompXXXConfig.cmake files for optional components (which are used internally in the main fooConfig.cmake).

Yes, the new ``CMakeDeps`` will work as long as there is one existing file that matches the pattern, so you can structure and have as many other .cmake files as desired. If the package name doesn't match, the ``self.cpp_info.set_property("cmake_file_name", ...)`` can define the name that will be used.

> On the other hand, maybe I should just bite the bullet and mirror the entire package and component structure in cpp_info, but I haven't found the courage yet :)

If you are using only CMake and you are happy with creating and maintaining your own in-package ``.cmake`` files, then defining components, etc, would be duplicated effort for little value.

**Comment by memsharded** [comment]
Hi @tttapa 

With this PR https://github.com/conan-io/conan/pull/17330 merged, and the previous one merged to ``develop2``, I think this ticket can be closed. Both will be in next Conan 2.10 soon. Please re-open or create new tickets for any further question or issue you might have. Thanks very much for your feedback!

**Comment by tttapa** [comment]
Thanks a lot! The latest `develop2` version indeed solves the previous two issues.

While trying it out, I did run into another related issue, though: 
```py
    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.set_property("cmake_file_name", "QPALM")  # There can only be one, AFAICT
        self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "QPALM"))
        if self.options.with_cxx:
            self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "QPALM_cxx"))
        if self.options.with_fortran:
            self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "QPALM_fortran"))
```
In this package, the C++ and Fortran interfaces are their own CMake packages, and `find_package(QPALM_cxx)` fails when using the New CMakeDeps. What I will probably do instead is creating `CXX` and `Fortran` components in the main `QPALMConfig.cmake` rather than creating separate top-level CMake packages, but it may be good to know that this is a limitation of new CMakeDeps.

**Comment by memsharded** [comment]
Yes, exactly, this is expected.
Every package is expected to have 1 ``pkgConfig.cmake`` as entry point, not several of them. We are using now the ``pkg_DIR`` in the new ``CMakeDeps`` to identify the right location for packages for CMake. This sounds better and more robust than relying on search paths with CMAKE_PREFIX_PATH and other similar variables. But Conan needs to know the ``<pkgname>_DIR`` of the things that could be found inside packages, and at the moment this is not possible because only 1 ``cmake_file_name`` can be defined.

Maybe it makes sense to consider this feature, if we make ``cmake_file_name`` a list for ``cmake_find_mode=none``, then this might be doable.

It would be better to file this as a separate ticket as a new Feature Request, to discuss with the team, as this one is closed now as the initially reported issues have been solved.

**Comment by tttapa** [comment]
> Every package is expected to have 1 `pkgConfig.cmake` as entry point, not several of them.

Thanks, I think this is a reasonable requirement.  
I ended up just creating a main `pkgConfig.cmake` file that adds the other `pkgComponentConfig.cmake` files to the search path (`pkgComponentConfig_DIR=${CMAKE_CURRENT_LIST_DIR}`). Then it just loops over `pkg_FIND_COMPONENTS` and does a `find_package(pkg${COMP} ...)` for each requested component.

Unless a large number of existing projects have the same issue of multiple `pkgConfig.cmake` files per package, it may not be worth complicating the Conan `cmake_file_name` feature.

**Comment by memsharded** [comment]
Sounds good, lets keep it as an idea, I think it wouldn't be hard to implement, if we get the request again or you happen to need it again too in other case, please let us know, create a new ticket and we will try to implement it. Thanks again for your feedback!
