### ISSUE TITLE
[bug] HTML graph is broken in Safari browser

### ISSUE THREAD

**Issue by kambala-decapitator** [conan-io/conan#17323]
### Describe the bug

Dependency graph generated with `conan graph info . -f html > 1.html` is unusable in Safari: sidebar controls don't work, legend appears in the middle of the screen (see SS). In Chromium-based browsers looks fine (tested in Vivaldi).

macOS 14.7, Conan 2.9.2, Safari 18.0.1

### How to reproduce it

Sample HTML: [1.html.zip](https://github.com/user-attachments/files/17786622/1.html.zip)

Safari SS:
![Screenshot 2024-11-16 at 16 56 02](https://github.com/user-attachments/assets/40a50111-3999-4b74-a44d-8850dc68d437)

Vivaldi SS:
![Screenshot 2024-11-16 at 16 56 06](https://github.com/user-attachments/assets/8fea143f-3785-4be0-b991-0382df6f7ff6)

**Comment by AbrilRBS** [comment]
Hi! Thanks a lot for your report

I've submitted #17335 to fix this for the next 2.10 release.

If this is a blocker for you, you can add a file to `CONAN_HOME/templates/graph.html` with the contents of the html template at https://github.com/AbrilRBS/conan/blob/ar/fix-graph-info-safari/conan/cli/formatters/graph/info_graph_html.py which will force Conan to use the updated template, which can then be removed once 2.10 is released :)

**Comment by kambala-decapitator** [comment]
Thanks a lot! Not a blocker at all :)
