### ISSUE TITLE
[question] Can a package change behavior depending on downstream dependency?

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#17332]
### What is your question?

Hello, I have a dependency graph that looks somewhat like this: My app uses an interface/serialization lib, which is automatically generated from an IDL file by the codegen (tool requirement). Both, the app and the interface lib use a communication lib.

```mermaid
graph BT;
  app --> interface;
  app --> lib;
  interface --> lib;
  interface --> codegen;
```

There's a new major version of the communication lib and codegen though, and I want my interface package to support both versions, i.e. if my app depends on version 3 of the lib, the interface should also depend on version 3 of the lib and use version 3 of the codegen. If an app is still using version 2 of the lib, the interface should use/depend on the previous versions too.

What's the best way to model this in Conan? I could use an option _codegen_version_ in the interface package that changes the behavior. But I wonder if the interface package could also determine the correct version automatically depending on the downstream dependencies?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fschoenm 

Thanks for your question.

If the ``lib`` and ``codegen`` follow the same versioning, then the ``host_version`` has syntax to support it:
```python
class Pkg(ConanFile):
    def requires(self):
        self.requires("lib/version")
   def build_requirements(self):
        self.tool_requires("codegen/<host_version:lib>")
```

If they don't follow the same versioning, I am trying to think about something, but besides adding a explicit ``option`` to model this, I don't think there is other way.

**Comment by fschoenm** [comment]
@memsharded Thanks for the quick reply.

> If the lib and codegen follow the same versioning, then the host_version has syntax to support it:

Unfortunately, they don't. They are versioned independently (not even sharing the same major version).

I think I'll resort to the explicit option for now.

**Comment by memsharded** [comment]
Ok, thanks for the feedback. Closing the question as responded, don't hesitate to re-open or create new tickets for any further question.
