### ISSUE TITLE
[question] self.variable in conanfile different behavior in conan build and conan create

### ISSUE THREAD

**Issue by DanielKopp94** [conan-io/conan#17341]
### What is your question?

For the following source code

```python
from conan import ConanFile


class Tester(ConanFile):

    name = "tester"
    package_type = "application"

    variable_value = -1

    def set_version(self):
        """
        Calculate and assign module's version.
        """
        self.version = "1.0.0"
        self.variable_value = 100
        print("Setting version, variable_value: ", self.variable_value)

    def layout(self):

        print("Setting layout, variable_value: ", self.variable_value)

    def generate(self):

        print("Generating, variable_value: ", self.variable_value)

    def build(self):

        print("Building, variable_value: ", self.variable_value)

    def package(self):

        print("Packaging, variable_value: ", self.variable_value)
```

By running a `conan build .` the value of `self.variable_value` remains 100 in all functions. By running a `conan create .` it will be 100 until the dependency graph is calculated. So in layout it is already again `-1`. As far as I understood there the class will be created again. I do not know if this is intended and I did not find any documentation for this behavior.

My question now is if there is a solution or if this is a wanted behavior.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DanielKopp94 

Thanks for your question.

Yes, this is expected. Using object/class variables to pass information across methods of a recipe is not a valid mechanism (in any case, if at some point you use your own attributes or methods, make sure to name them starting with ``_``, as the public namespace is owned by Conan, see: https://docs.conan.io/2/reference/conanfile.html

Conan methods are called in different stages and in different moments. The ``set_version()`` will only be called at "export" stage, when a recipe is being exported from user folder to Conan cache (``conan export``, ``conan create``, ``conan export-pkg``), but it will not be called in other usages, like ``conan install``. The methods ``source()``, ``build()`` and ``package()`` are exclusively called when the package is being built from source, but not in other cases.

Some compound operations like ``conan create`` are equivalent to ``conan export`` + ``conan install``, and those happen as separate api calls, so they might result in independent loading of ``conanfile.py`` with independent evaluation of different methods. 

There are some defined mechanisms to connect information across methods. For example ``generate()`` method should generate all information as files, so the posterior ``build()`` (or using calling their build systems) will find all the necessary information in files.

**Comment by DanielKopp94** [comment]
Hi @memsharded ,

thanks for the clarification
