### ISSUE TITLE
[question] How to limit conan search to local cache only

### ISSUE THREAD

**Issue by rajesh-kareti-infovision** [conan-io/conan#17347]
### What is your question?

If remote is not provided conan will search in all remotes . How to limit conan search to search only in local cache 
conan 1.0 this was straight forward.if remote not provided it will search only local cache

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rajesh-kareti-infovision 

Thanks for your question.
The ``conan list`` command uses the cache only by default, unless using ``-r`` argument.
In fact the ``conan search`` is now only a simplified alias of the more powerful and complete ``conan list`` command.

**Comment by rajesh-kareti-infovision** [comment]
Thanks for the quick response
