### ISSUE TITLE
[question] Shared and static libraries in the same package

### ISSUE THREAD

**Issue by Linux13524** [conan-io/conan#17364]
### What is your question?

Hi! I currently have a situation where I'm creating a recipe for a 3rd-party library that can be built shared or static, so I added the option `shared`. When building the library shared I get a  `.so` file on Linux and when I build the library static I get a `.a` file. So far everything as expected. 

However, there is also an option that enables a kind of addon to the library (let's call it `enable_addon`), and this one is always shared (seems it is somehow loaded dynamically and just when needed), even when building the library itself static. I'll get a `.so` and a `.a` file in that case. So far that wasn't a problem with Conan v1, but now with Conan v2 it seems the `package_type` is still detected as `static-library` and my `test_package` cannot find the `.so` file on execution (I suppose due to the `run` trait).

I don't feel like setting the `package_type` to `shared-library` as the "original" library is still a static lib.
Also, the shared lib is only included in the case of `enable_addon`.
And setting the `run` trait also seems odd as I would need to set it in the `test_package` or wherever my package is a `requires`, right?

So the question is: How to best handle this situation with Conan v2? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Linux13524 

Thanks for your question

> However, there is also an option that enables a kind of addon to the library (let's call it enable_addon), and this one is always shared (seems it is somehow loaded dynamically and just when needed), even when building the library itself static. I'll get a .so and a .a file in that case. So far that wasn't a problem with Conan v1, but now with Conan v2 it seems the package_type is still detected as static-library and my test_package cannot find the .so file on execution (I suppose due to the run trait).

> And setting the run trait also seems odd as I would need to set it in the test_package or wherever my package is a requires, right?

This isn't necessarily odd, this is exactly one of the cases of the ``run=True``:
- You have a package binary that is a static library, behaves mostly as a static library for building, etc. Definitely not a shared library. The package type seems correct.
- But that library contains something that is necessary at runtime too. This is a special situation, static libraries are not needed at runtime. There are other cases which this happens, if the package contain some other resources, like data files, that are needed at runtime.
- If the consumers want to use those add-ons at runtime, they should tell it, this is a explicit behavior for the consumer. In other words, you don't want to link with a static library, thinking your executable is fully statically linked, but it happens to be some shared library out there needed at runtime. The ``run=True`` makes explicit this extra requirement.

On the other hand if:

> (seems it is somehow loaded dynamically and just when needed

Then, I mostly don't see a reason to not consider the package a ``package_type = "shared-library"``. If the addon is not optional and it is always loaded at runtime from the static library, then the package behaves mostly as a "shared-library", isn't it? That is what the import-libs do with DLLs in windows mostly, and they are considered ``shared-library`` even if the loading happens via the static import-lib.

Please let me know what you think.

**Comment by Linux13524** [comment]
Thanks a lot for your answer!

>  If the addon is not optional and it is always loaded at runtime from the static library, then the package behaves mostly as a "shared-library", isn't it?

The addon is not optional in case a specific option is set. Is it possible to set the `package_type` conditional based on options and where would be the right place to do this?

**Comment by memsharded** [comment]
> The addon is not optional in case a specific option is set. Is it possible to set the package_type conditional based on options and where would be the right place to do this?

You can do this in the ``configure()`` method, I think something like this should work:

```python
def configure(self):
     if self.options.addon:
           self.package_type = "shared-library"
    # if not, it will deduce the type based on ``shared`` option automatically
```

The only thing is to make sure that the rest of the recipe like CMake build/CMakeToolchain definition is consistent, for example if options.shared=False for static lib, then BUILD_SHARED_LIBS will be off by default for CMake, that the recipe should take that into account.

Please try that and let us know.

**Comment by Linux13524** [comment]
I set it up like this now and it worked perfectly. Thanks again!

**Comment by memsharded** [comment]
Happy to help!
Don't hesitate to create new tickets if you have any further question or issue. Thanks for the feedback!
