### ISSUE TITLE
[question] python_requires + alias is no longer supported in Conan 2?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#17373]
### What is your question?

Hi,

I'm doing Conan 2 migration and bumped into the following error:

ERROR: Error loading conanfile at 'xxxx\base64\conanfile.py': python-requires 'alias' are not supported in Conan 2.0. Please use version ranges instead

Does it mean that alias support will be removed actually from Conan 2? If not where can it be used without fearing that it might be deprecated?

Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for your question.

Actually, the whole ``alias`` feature hasn't been documented in Conan 2.

We have maintained it for regular requires, to allow easier migration from Conan 1 to Conan 2, but the idea is to deprecate it. It was a very legacy Conan 1.X from a time where proper versioning, pre-releases, version ranges, lockfiles and multi-repositories pipelines didn't exist.

So, while you can use the ``alias`` for regular requires in Conan 2.X, it should be a high priority after the upgrade to get rid of them and move to proper versioning. At the moment there is no deadline for removing them, but Conan 2 is approach 2 years old, and it might eventually happen.

**Comment by harsszegi** [comment]
Understood, thanks a lot @memsharded, closing it
