### ISSUE TITLE
[question] Confused on interaction between layout() and source() with Git

### ISSUE THREAD

**Issue by JackOfAllBugs** [conan-io/conan#17370]
### What is your question?

I am running into an interesting problem with the interaction between layout() and source() with Git. When using the cmake_layout + root/subproject syntax outlined [here](https://docs.conan.io/2.4/examples/conanfile/layout/multiple_subprojects.html), I am seeing different behavior when using local install/build commands vs create. The key issue I believe is that layout() is setting the self.source_folder to be the subproject folder, which locally works, but occurs BEFORE source() is run during create, which changes the relative paths (the repo is cloned into a fake/empty subproject folder in the cache, and ends up telling CMake to use the wrong CMakeLists.txt during build(). (NOTE: these CMakeLists.txt are disconnected and not within the same tree)

What I am looking for (I think) is a way to tell conan that the source dir is the project root, but CMake that its source is "unique-subproject". After a few hours of hunting through the documentation and trying various iterations of custom layouts/cmake flags, I am hoping that someone else has had this problem before. If so, any guidance would be much appreciated!

My functions are as follows:

```
generators = "CMakeToolchain", "CMakeDeps"

def export(self):
  git = Git(self, self.recipe_folder)
  scm_url = git.get_remote_url()
  scm_commit = git.get_commit()
  update_conandata(self, {"sources": {"commit": scm_commit, "url": scm_url}})

def source(self):
  git = Git(self)
  sources = self.conan_data["sources]
  git.clone(url=sources["url"], target=".", args=["-c", "http.sslVerify=false"]
  git.checkout(commit=sources["commit"])

def layout(self):
  self.folders.root = ".."
  self.folders.subproject = "unique-subproject"
  cmake_layout(self)
```

The repo is structured like this (simplified):

repository/
├── conanfile.py
├── CMakeLists.txt
├── src/
├── unique-subproject/
│   ├── CMakeLists.txt
│   ├── conanfile.py
│   ├── src/

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @JackRenner 

Thanks for your question.

Quick question: I understand that the ``conanfile.py`` you provide is the one inside ``unique-subproject`` isn't it?

I think this is the same use case that we have in this test: https://github.com/conan-io/conan/blob/d144ef2e27dcd65917898ad034c4b416c5713eab/test/functional/tools/scm/test_git.py#L844

What you might be missing is an extra move of the source after the checkout:
```python
    from conan.tools.files import load, copy, save, update_conandata, move_folder_contents


                def source(self):
                    git = Git(self)
                    sources = self.conan_data["sources"]
                    git.clone(url=sources["url"], target=".")
                    git.checkout(commit=sources["commit"])
                    # Layout is pkg/pkg/<files> and pkg/common/<files>
                    # Final we want is pkg/<files> and common/<files>
                    # NOTE: This abs_path is IMPORTANT to avoid the trailing "."
                    src_folder = os.path.abspath(self.source_folder)
                    move_folder_contents(self, src_folder, os.path.dirname(src_folder))
```

Please try that and let us know.

**Comment by JackOfAllBugs** [comment]
Yes, the `conanfile.py` is from `unique-subproject`

It looks like `move_folder_contents` cannot account for the fact that the `self.source_folder` already exists since it is created before `source()` ever runs. 

I did figure out another way that seems consistent. I am curious what your thoughts are if this should be the advertised way of handling git clones in `source()` when using a nested `conanfile.py` ?

```
def source(self):
  src_folder = os.path.abspath(self.source_folder)
  os.chdir(os.path.join(src_folder, "..") ## adjust the path for cloning without modifying self.source_folder
  shutil.rmtree("unique-subproject") ## remove the conan-generated self.source_folder to allow git clone to work
  git = Git(self)
  sources = self.conan_data["sources]
  git.clone(url=sources["url"], target=".", args=["-c", "http.sslVerify=false"]
  git.checkout(commit=sources["commit"])
```

**Comment by memsharded** [comment]
I might be missing something. The test that I provided works, it clones inside the ``unique-subproject``. It cannot clone outside of it, as this might be in a different place in the Conan cache when this is being built as a dependency, and break things. It might not break by luck when using the ``cmake_layout``, but if that is changed, things might break.

The thing is that when something is a Conan package, it has to be understood as an independent entity, so:
```
src/
│ ├── CMakeLists.txt
│ ├── conanfile.py
│ ├── src/
```
Is what the source tree should look-like in the Conan cache. The name of the containing folder does not need to be ``unique-subproject``, that name should be irrelevant. But that folder is the root folder where we can clone, download, etc, we cannot go one level up and clone there, so the subproject automatically matches. This is why the ``move_folder_contents`` was necessary.

If the approach with the ``move_folder_contents()`` was not working, it would be good to have a full reproducible case, like the test (or even a modified version of the test, that would be even better). Please let us know, thanks for the feedback!

**Comment by memsharded** [comment]
Hi @JackRenner 

Any feedback or further question here? Thanks!

**Comment by memsharded** [comment]
I am closing this ticket as responded, but please don't hesitate to re-open if you have any further questions or feedback, or create new tickets as necessary. Thanks for your feedback!
