### ISSUE TITLE
[bug] Powershell scripts generated on MacOS

### ISSUE THREAD

**Issue by wawanbreton** [conan-io/conan#17386]
### Describe the bug

Hi, I'm building my project using conan 2.7.1 on both Linux, Windows and MacOS. Our Windows developers mainly use Powershell, so I have activated the config in our global profile to have it by default:
```
tools.env.virtualenv:powershell=True
```
However, on the Mac runner, is see Powershell scripts being generated, and obviously this fails because they can't be processed:
```
-------- Installing package abseil/20230802.1 (1 of 61) --------
abseil/20230802.1: Building from source
abseil/20230802.1: Package abseil/20230802.1:3381de3bce3b26e2939b85d2b8118bf754612317
abseil/20230802.1: Copying sources to build folder
abseil/20230802.1: Building your package in /Users/runner/.conan2/p/b/abseie56d7a3c01c4b/b
abseil/20230802.1: Calling generate()
abseil/20230802.1: Generators folder: /Users/runner/.conan2/p/b/abseie56d7a3c01c4b/b/build/Release/generators
abseil/20230802.1: CMakeToolchain generated: conan_toolchain.cmake
abseil/20230802.1: CMakeToolchain generated: /Users/runner/.conan2/p/b/abseie56d7a3c01c4b/b/build/Release/generators/CMakePresets.json
abseil/20230802.1: CMakeToolchain generated: /Users/runner/.conan2/p/b/abseie56d7a3c01c4b/b/src/CMakeUserPresets.json
abseil/20230802.1: Generating aggregated env files
abseil/20230802.1: Generated aggregated env files: ['conanbuild.ps1', 'conanrun.ps1']
abseil/20230802.1: Calling build()
abseil/20230802.1: Apply patch (portability): link libm to absl string
abseil/20230802.1: Apply patch (portability): Fix build with MinGW
abseil/20230802.1: Running CMake.configure()
abseil/20230802.1: RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/runner/.conan2/p/b/abseie56d7a3c01c4b/p" -DCMAKE_POLICY_DEFAULT_CMP0067="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DBUILD_TESTING="OFF" -DCMAKE_BUILD_TYPE="Release" "/Users/runner/.conan2/p/b/abseie56d7a3c01c4b/b/src"
/bin/sh: powershell.exe: command not found
/bin/sh: cmd: command not found

abseil/20230802.1: ERROR: 
Package '3381de3bce3b26e2939b85d2b8118bf754612317' build failed
abseil/20230802.1: WARN: Build folder /Users/runner/.conan2/p/b/abseie56d7a3c01c4b/b/build/Release
ERROR: abseil/20230802.1: Error in build() method, line 124
	cmake.configure()
	ConanException: Error 127 while executing
```

Here is the relevant extract of the config:
```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=14
os=Macos
[conf]
tools.build:skip_test=True
tools.cmake.cmaketoolchain:generator=Ninja
tools.env.virtualenv:powershell=True
tools.gnu:define_libcxx11_abi=True

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=14
os=Macos
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.env.virtualenv:powershell=True
tools.gnu:define_libcxx11_abi=True
```

The documentation clearly mentions that this setting should have an effect only on Windows.  For now I have workarounded this by using the setting only on Windows, but the initial setup should work, right ? 

### How to reproduce it

* Set config `tools.env.virtualenv:powershell=True`
* install dependency abseil/20230802.1 on Macos (no idea if this issue is specific to this package)

**Comment by czoido** [comment]
Hi @wawanbreton,

Thanks a lot for your question.

Yes, I think this is a bug, I could reproduce it on Linux and I don't think that this should affect when building in other os than Windows.

Besides not adding that in other profiles others than windows, for other cases or other confs, be aware that you can also use [Jinja syntax in your profiles](https://docs.conan.io/2/reference/config_files/profiles.html#profile-rendering), so that you avoid to set that configuration when not in Windows. For example:

```
include(default)
[conf]
{% if platform.system() == "Windows" %}
tools.env.virtualenv:powershell=True
{% endif %}
``` 

I'll mark this issue to be solved for the next release.

**Comment by wawanbreton** [comment]
Thanks for confirming, I hope it is an easy fix.

> Besides not adding that in other profiles others than windows, for other cases or other confs, be aware that you can also use [Jinja syntax in your profiles](https://docs.conan.io/2/reference/config_files/profiles.html#profile-rendering), so that you avoid to set that configuration when not in Windows. For example:

This is exactly what I am doing, and it is very convenient :slightly_smiling_face: however the config was initally in my `global.conf`, so I had to move it to a profile. This is really no problem though. I'll wait for the fix and then I can put it back into the main file.

**Comment by czoido** [comment]
Hi @wawanbreton,

I'm sorry, but it looks like, in the end, we can't modify this. @memsharded told me that there are users using PowerShell on platforms other than Windows, so we have to keep the current behavior. I was not aware that could be possible, but it is: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos

What we will do is fix the documentation and the help message for conan config list so we don't say that this only has effect on Windows.

Thanks a lot for reporting.

**Comment by wawanbreton** [comment]
Ok, that makes sense then. As long as the documentation mentions it, I'm fine with it.

**Comment by czoido** [comment]
@wawanbreton thanks a lot for reporting, we have fixed the issue in the help message that will be release in 2.10.0 and also in the docs for that version.

**Comment by wawanbreton** [comment]
I'm glad to help :slightly_smiling_face: and thank you for being always extremely reactive !
