### ISSUE TITLE
[question] requirements built_type / CLion integration

### ISSUE THREAD

**Issue by pherzl** [conan-io/conan#17388]
### What is your question?

Hi,

I am encountering a problem that seems similar to this [Conan Issue](https://github.com/conan-io/conan/issues/14520) regarding setting a custom package build type via the conanfile.py. 
Is the answer provided there is still valid?

I am using CLion with the Conan plugin. In the IDE's CMake settings, the build type is set to RelWithDebInfo. However, when I add a dependency like opencv/4.5.5 and load the project, the Conan plugin automatically calls the conan install command using the RelWithDebInfo build type.

This is problematic because the project dependencies, including OpenCV, must be pulled in using the Release build type, not RelWithDebInfo. 

I have tried using the command line solution suggested in [this comment](https://github.com/conan-io/conan/issues/14501#issuecomment-1681767612), which works, but I'm uncertain how to apply the same configuration in CLion using the Conan plugin.

I also attempted to modify the default profile by adding the build_type, but this did not resolve the issue, as dependencies are still being built in RelWithDebInfo.
`[settings]
arch=x86_64
build_type=Release
&:build_type=RelWithDebInfo
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.version=192
os=Windows
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
`

Ideally, I'd like to configure the project / recipe so that a user can simply pull the project from Git, set the build type to RelWithDebInfo in CLion, and have the dependencies automatically pulled in with the Release configuration.

Additionally, this applies to Debug builds as well—if the build type is set to Debug in CLion, the dependencies should still be pulled in with Release settings.

Any help would be greatly appreciated.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @pherzl,

Thanks a lot for your question.

If you want to use the dependencies in a different build_type than the one that is set in the CLion plugin you can use the syntax `!&:build_type=Release` which means that **everything but the consumer** should be built in Release, the consumer will be built in the build_type dictated by CLion.

To apply that setting you can modify the arguments that are passed to CMake in CLion:

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/dc0dca0f-8e30-4ecd-a365-3df74c58fc49">


In that case, we are adding the argument to the Debug configuration, so our project is built in Debug but all the dependencies, like OpenCV will be built in Release.

As you can see, we add: `-DCONAN_INSTALL_ARGS="--build=missing;-s=!&:build_type=Release"` This could also be done via profiles by passing -`DCONAN_HOST_PROFILE=` (check the [cmake-conan docs](https://github.com/conan-io/cmake-conan) that the CLion plugin uses internally for more info)

Hope this helps!

**Comment by pherzl** [comment]
Yes, that was very helpful, thank you very much!
