### ISSUE TITLE
[question] Package ID modes

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#17401]
### What is your question?

It seems that package ID calculation in Conan 2 now takes into account the so-called embed-mode or non-embed-mode, which is a good thing. However, the documentation is unclear about how this mode is detected. Is it decided purely based on the value of the `package_type` attribute or is there some more heuristics going on? What happens when a recipe does not specify a `package_type` attribute? My expectation would be that it falls back to `full_mode` in the package ID calculation. Is there a way to define the default package ID mode for cases where Conan fails to determine the embed mode?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jasal82 

Thanks for your question.

> However, the documentation is unclear about how this mode is detected. Is it decided purely based on the value of the package_type attribute or is there some more heuristics going on? What happens when a recipe does not specify a package_type attribute?

The ``package_type`` will be automatically deduced, even if not defined for all packages that define a ``shared`` option or a ``header_only`` option. In practice this means the majority of recipes, at least the vast majority of ConanCenter recipes.

If no ``package_type`` is defined and it cannot be automatically deduced either, it becomes ``package_type = unknown``.

The unknown package type defaults to a mode very similar to legacy Conan 1.X mode of "semver_mode". But it can also be customized via:
- ``core.package_id:default_unknown_mode`` conf
- The ``package_id_unknown_mode`` attribute

**Comment by memsharded** [comment]
Hi @jasal82 

Any further question or feedback here? Thanks!

**Comment by jasal82** [comment]
Everything clear now, thanks!
