### ISSUE TITLE
[question] get package install dir from within package_info()

### ISSUE THREAD

**Issue by igagis** [conan-io/conan#17400]
### What is your question?

Hi,

I'm trying to package a set of `*.mk` files which are to be included from a `makefile` of another library.
The `*.mk` files are installed to `include` directory.

In linux, the `/usr/include` and `/usr/local/include` are default search paths where `GNU make` will search for includes.
It is also possible to add inlcude search path as command line argument: `make --include-dir=...`.

So, I want to provide a `MAKE_INCLUDE_DIRS` env variable to my package users, so that they could do `make $MAKE_INCLUDE_DIRS` and use the inlcuded `*.mk` from their `makefile`s.

Inside of the package the `*.mk` files are in `include` directory.

So, I need  this:
```
def package_info(self):
		self.buildenv_info.append("MAKE_INCLUDE_DIR_ARGS", "--include-dir=TODO:")
```
And the question is what directory to place instead of TODO?

The source code can be browsed here: https://github.com/cppfw/prorab-extra/blob/main/conan/conanfile.py#L48

And, currently ci build fails with error:
```
makefile:2: prorab-license.mk: No such file or directory
```
https://github.com/cppfw/prorab-extra/actions/runs/12120922564/job/33790715885#step:10:145

Because the include directory is not provided.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @igagis 

Thanks for your question.

The issue is that you are using the package as a regular ``requires``. It is not a library, so it should be better used as a ``tool_requires``.
So in your ``test_package`` try:
```
self.tool_requires(self.tested_reference_str)
```
Instead of the ``self.requires(self.tested_reference_str)``. For ``conan create`` step, in some cases you might need to do:
```
conan create . --build-require
```
To indicate you are building for the "build" context the package. If the package has no ``settings`` and it only contains ``.mk`` build scripts, this might be unnecessary.

**Comment by igagis** [comment]
Hi @memsharded ,

unfortunately this did not help. I tried both, `tool_requires` and `--build-requires`, but still same problem:
https://github.com/cppfw/prorab-extra/actions/runs/12121533308/job/33792669553#step:10:129

and I'd say it is expected, because `make` does not search for `.mk` files in package install directory.

**Comment by memsharded** [comment]
I didn't see it, but ``self.run("make $MAKE_INCLUDE_DIRS_ARG", env="conanrun")`` also seems incorrect, it should be ``env="conanbuild"`` (this is the default, you can omit it), as the recipe is defining ``self.buildenv_info``.

**Comment by igagis** [comment]
ok, I'll try it, but I still don't understand how `make` is supposed to find the `.mk` files.

**Comment by igagis** [comment]
yes, same problem:
https://github.com/cppfw/prorab-extra/actions/runs/12121794555/job/33793508814#step:10:129

**Comment by igagis** [comment]
Just to make sure you grasped my question. The main question is:

> And the question is what directory to place instead of TODO?

**Comment by memsharded** [comment]
Yes, probably I didn't understand it.

You should put there the directory where you put your ``.mk`` files. Something like ``os.path.join(self.package_folder, "mymkdir")``. 

Is that the question? Even if you put that, it wouldn't have worked without the fixes described above.

**Comment by igagis** [comment]
yes, this worked, thanks a lot!

I was unsure about `self.package_folder` as I though of it as package build folder, not as package install folder.

But it works. Thanks again!

**Comment by memsharded** [comment]
Yes, the ``self.package_folder`` exists in ``package_info()`` and can be used, as ``package_info()`` always execute after the binary has been installed, it represents the final installed package.
