### ISSUE TITLE
[question] [2.0] cacert.pem file in conan2

### ISSUE THREAD

**Issue by Aki1608** [conan-io/conan#17404]
### What is your question?

Hi all, I am working on migrating a conan1 recipe to conan2 and saw that when I install config with `conan config install`, it doesn't generate cacert.pem file. Is there any way I can generate this file while installing config? Is this file not necessary in 2.0? I am using version 2.9.3. Thank you.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Aki1608 

Thanks for your question.

Yes, Conan 2 no longer uses a custom cacert.pem. This was not the best practice while in Conan 1, so now Conan 2 removed it and it is using the system cacerts, in this case whatever the Python ``requests`` library uses. Conan 2 exposes some of the ``requests`` configuration:

```
$ conan config list net
core.net.http:cacert_path: Path containing a custom Cacert file
core.net.http:clean_system_proxy: If defined, the proxies system env-vars will be discarded
core.net.http:client_cert: Path or tuple of files containing a client cert (and key)
```

**Comment by Aki1608** [comment]
Thank you so much for the fast reply, @memsharded. 

I also wanted to know about `artifacts.properties`.  It seems like that has also been removed from conan2. Is there any alternative for that too?

**Comment by memsharded** [comment]
> I also wanted to know about artifacts.properties. It seems like that has also been removed from conan2. Is there any alternative for that too?

Sure. Now there are explicit Artifactory custom commands in the conan-extensions repo, installed in the same way than the build-info commands: https://docs.conan.io/2/integrations/jfrog.html#how-to-install-the-build-info-extension-commands

This is the repo containing the commands: https://github.com/conan-io/conan-extensions.git

So now the command in https://github.com/conan-io/conan-extensions/blob/main/extensions/commands/art/cmd_property.py allows to do ``property add/set`` to define artifactory properties.

For the build-info related functionality it is not necessary to do it manually, the ``build-info`` commands will already manage to define the properties for the build-info.

**Comment by Akash-Parikh-einfochips** [comment]
Okay, if I understand correctly, we must run this command separately to get the necessary information and it will generate a json file and not an _"artifacts.property"_ file. 

Is there any way that this file will get generated at `conan config install .`  stage with conan2?

And one last question. _"config_install.json"_ file is also not being generated in conan2 while installing configs. How can it be generated?

**Comment by Aki1608** [comment]
Okay, if I understand correctly, we must run this command separately to get the necessary information and it will generate a json file and not an "artifacts.property" file.

Is there any way that this file will get generated at conan config install . stage with conan2?

And one last question. "config_install.json" file is also not being generated in conan2 while installing configs. How can it be generated?

**Comment by memsharded** [comment]
> Okay, if I understand correctly, we must run this command separately to get the necessary information and it will generate a json file and not an "artifacts.property" file.

No, the artifactory property command just set properties in artifactory, it does not create any json file.

The ``artifacts.property`` in Conan 1 was tied to the generation and upload of the Artifactory BuildInfo. Now this happens automatically with the new Conan 2 build-info commands in the extensions repository. So this file is unnecessary (it was actually quite a hack and ugly workaround).

> Is there any way that this file will get generated at conan config install . stage with conan2?

the file is completely unrelated to ``conan config install``, I don't understand the question. The file doesn't exist at all in Conan, it is not needed for anything, I am not sure what I am missing.

> And one last question. "config_install.json" file is also not being generated in conan2 while installing configs. How can it be generated?

It is not generated, this file has been removed. Conan configuration in Conan 2 recommendations are:
- Centralize all configuration in one single place, avoid having multiple configurations sources
- If you have complex configuration logic, for better management, creation, versioning, etc of configuration use the new ``conan config install-pkg``, putting configuration inside a Conan package

**Comment by Aki1608** [comment]
>  The file doesn't exist at all in Conan, it is not needed for anything, I am not sure what I am missing.

I saw that file when I installed config using `conan config install .`, so I thought maybe that command generated that file. But now I understand it. 

Thank you so much for the answers. :)

**Comment by memsharded** [comment]
The ``conan config install`` doesn't really generate new files. It downloads and installs files from the URL or Git repo that you provide, but the contents of that zip file or git repo are completely defined by users.

Thanks to you for your feedback!
