### ISSUE TITLE
[question] How to get the package folder of a binary package with Conan 2?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#17419]
Hi,

I can use "conan info --profile xxx -build_type .. --paths rev" to get the locations for Conan 1 binary packages.
I need to do the same for Conan 2.

I know there is "conan cache path", however I have zero idea how to calculate / figure out the actual package id hash corresponding with a given profile + settings.

I need the exact location of the binary package so that I can check whether certain files has been generated by the package or not.
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for your question.

You can use the ``conan install ... --format=json > graph.json``

That json will contain all the information you need, including the package folder, you can check about it in https://docs.conan.io/2/reference/commands/formatters/graph_info_json_formatter.html

**Comment by harsszegi** [comment]
Awesome, tested, works fine, thanks a lot @memsharded , closing it!
