### ISSUE TITLE
[question] stdout/stderr confusion

### ISSUE THREAD

**Issue by walterschneider** [conan-io/conan#17412]
### What is your question?

Hi!
I am confused regarding the stdout and stderr streams:

[conan_run](https://github.com/conan-io/conan/blob/develop2/conans/util/runners.py#L43)
All processes started with conan_run redirect stdout to stderr,
the docu says "Instead of print to sys.stdout print to that stream" but it is initialized with sys.stderr.
A typo?
However, i can control the streams with the stderr option.

[ConanOutput](https://github.com/conan-io/conan/blob/develop2/conan/api/output.py#L95)
All messages (info, warning, error) are written to stderr.
In my opinion, this should be stdout for info and stderr for error and popably warning.

Can you explain the background?
Thank you.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @walterschneider,

Thanks a lot for the question. 

For the first part, yes, that seems a typo in the `conan_run` docstring but please, be aware that `conan_run` is not meant to be public and be used outside the internal code for Conan. To run external commands in recipes please use Conanfile's `run` method, like explained in the docs: https://docs.conan.io/2/reference/conanfile/running_and_output.html

Regarding `ConanOutput`, the the decision to send all messages, but the final output of the command, including info, warnings, and errors, to `stderr` follows a deliberate design choice that aligns with common practices in many CLI tools and the [POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/stderr.html) (you'll see that it defines _standard output (for writing conventional output) and standard error (for writing diagnostic output)_ so stderr is not only used for errors but all kinds of informative messages).

For Conan, the separation allows the main data output of commands to be cleanly directed to `stdout`, while diagnostic and auxiliary information (like logs, progress bars, and status messages) is sent to `stderr`.

For example, if you're running a command like `conan install` and want to capture its main output in a file (e.g., in JSON format), you can redirect `stdout` to a file without mixing it with diagnostic messages. This approach is used by many well-known tools like `git`, `curl`, `wget`, `rsync`, and others.

Hope this helps, please don't hesitate to reach out if you have any further questions or need additional clarification!

**Comment by walterschneider** [comment]
Thank you very much for your fast end detailed explanation!
I am using use ConanFile.run which forwards to conan_run.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/17507 adds a new ``--output-file`` to enforce writing the result in that file irrespective of the ``stdout`` redirections or other possible issues. It will be in next Conan 2.12. Thanks for the feedback!
