### ISSUE TITLE
[question] How to access options of tool_requires?

### ISSUE THREAD

**Issue by tttapa** [conan-io/conan#17415]
### What is your question?

When writing a test package for a build tool or application, how can one access the values of the options of the package under test?

For example:
```py
# conanfile.py for my-tool

import os
from conan import ConanFile


class MyToolConan(ConanFile):
    name = "my-tool"
    package_type = "application"
    settings = "os", "arch"

    options = {"variant": ["foo", "bar"]}
    default_options = {"variant": "foo"}

    def build(self):
        pass

    def package(self):
        pass

    def package_info(self):
        bindir = os.path.join(self.package_folder, "bin")
        self.buildenv_info.prepend_path("PATH", bindir)
```

```py
# test_package conanfile.py for my-tool

import re
from conan import ConanFile
from io import StringIO


class TestPackageConan(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    generators = "VirtualBuildEnv"
    test_type = "explicit"

    def build_requirements(self):
        self.tool_requires(self.tested_reference_str)

    def test(self):
        tokens = re.split("[@#]", self.tested_reference_str)
        my_tool, required_version = tokens[0].split("/", 1)
        variant = self.tool_dependencies[my_tool].options.variant            ???
        self.run(f"my-tool-{variant} --version", output := StringIO())
        assert required_version in output.getvalue()
```
Here, `self.tool_dependencies` is of course fictitious syntax, but I couldn't find a build context member parallel to `self.dependencies`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by tttapa** [comment]
Aha, I was looking for direct members of `ConanFile`, but `print(dir(self.dependencies))` revealed `self.dependencies.build`, which contains the needed information. Marking as solved for now.

**Comment by AbrilRBS** [comment]
Yes! You are right in your finding, the `self.dependencies.build` accessor is meant to give you your tool_requires, which plain `self.dependencies` won't do, happy to hear that you found the solution :)

**Comment by tttapa** [comment]
@AbrilRBS Thanks for the confirmation!

In the [`ConanFile.generate` documentation](https://docs.conan.io/2/reference/conanfile/methods/generate.html#self-dependencies), there's the following comment about `self.dependencies`:

> At the moment, this information should only be used in generate() and validate() methods. For any other use, please submit a Github issue.

Is it valid to use `self.dependencies` in `ConanFile.test`?
