### ISSUE TITLE
[question] how to use gcc built dependencies when trying to build with clang?

### ISSUE THREAD

**Issue by rickrick318** [conan-io/conan#17410]
### What is your question?

hi team:
          my current conan version is 1.59.0,  I used to use gcc to build my projects, here is my profile:
          `[settings]
                arch=armv8
                arch_build=x86_64
                os=Linux
                os_build=Linux
                compiler=gcc
                compiler.version=9.3
                compiler.libcxx=libstdc++11
                build_type=Release
                region=CN
                platform=orin
                target_platform=orin
                target_platform_type=soc
                soc=1
                project=helloconan
                [options]
                *:shared=True
                [build_requires]
    `
    now I want to switch to use clang to build my projects, this is my new profile:
    `
    [settings]
arch=armv8
arch_build=x86_64
os=Linux
os_build=Linux
compiler=clang
compiler.version=13
compiler.libcxx=libc++
build_type=Release
region=CN
platform=orin
target_platform=orin
target_platform_type=soc
soc=1
generation=NT2
project=helloconan

[options]
*:shared=True
[build_requires]
[env]
CC=clang-13
CXX=clang++-13
    `
    but I got error "ERROR: Missing prebuilt package for 'gflags/2.2.2@3rdparty/stable', 'glog/0.4.0_231109@3rdparty/stable'", the reason is conan can't find gflags and glog which built by gcc because the package_id of gflags and glog changed, so my question is is there any way to use gcc built conan packages when building with clang?  thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rickrick318 

Thanks for your question.

No, there is no way to use a package compiled with ``compiler=gcc`` if your profile says ``compiler=clang`` implicitly in Conan 1. This is only available with the new compatibility.py plugin in Conan 2.

What can be possible in Conan 1 is explicitly define per-package settings for the packages you want:
```
[settings]
...
compiler=clang
compiler.version=13
....
gflags/*:compiler=gcc
gflags/*:compiler.version=9.3
gflags/*:compiler.libcxx=...
...
```

**Comment by rickrick318** [comment]
thanks very much for your answer. @memsharded 

for our projects, our dependencies were written to a yml file, and being imported by requirements in conanfile. we don't know what dependencies we need before we download this yml file, it's impossible to put all the dependencies under profile [settings] for us~

for x86_64 build, I can trick by export compiler env like: export CC="/usr/bin/clang-13"
export CXX="/usr/bin/clang++-13" , but I can't do this for cross build armv8, do you know is there any way to change the armv8 compiler to clang by export env or other ways?

**Comment by memsharded** [comment]
> for our projects, our dependencies were written to a yml file, and being imported by requirements in conanfile. we don't know what dependencies we need before we download this yml file, it's impossible to put all the dependencies under profile [settings] for us~

If all dependencies use ``gcc``, just use ``compiler=gcc`` in the profile you use for ``conan install``

The ``CC`` environment variable is irrelevant. The "identity" of the binary is the ``package_id``, which is computed from settings. If you want to install a binary that was built with ``compiler=gcc``, then you  need to install it with ``compiler=gcc`` setting.


> but I can't do this for cross build armv8, do you know is there any way to change the armv8 compiler to clang by export env or other ways?

If you are building the packages from source, that is a different story. One thing is installing packages that were built with one compiler, and another is building some package with some compiler. If you are creating a package, use the ``settings`` you want that package to be created, with the compiler, architecture, etc you want to use to build that package.

**Comment by rickrick318** [comment]
@memsharded , yes, all my dependencies is built with gcc and now I want to build my project with clang. the result is when I change my profile to [settings] compiler=clang compiler.version=13, the dependencies' can't be found because the package_id changed.

in my case, can I use a profile with gcc settings for conan install and another profile for conan build? currently I use the same profile for install and build.

**Comment by rickrick318** [comment]
when I say I export export CXX="/usr/bin/clang++-13 to change the compiler that means I can bypass the package_id calculate of all my dependencies, but it only works for x86_64, I don't know what the armv8 cross build compiler env is~

**Comment by memsharded** [comment]
> @memsharded , yes, all my dependencies is built with gcc and now I want to build my project with clang. the result is when I change my profile to [settings] compiler=clang compiler.version=13, the dependencies' can't be found because the package_id changed.

Don't do that, use:
```
[settings]
compiler=gcc
compiler.version=9.3
...
&:compiler=clang
&:compiler.version=13
...
```
That will use your dependencies built with gcc, but your current consumer project will use clang.

**Comment by rickrick318** [comment]
@memsharded  when i change my profile to 
[settings]
arch=armv8
arch_build=x86_64
os=Linux
os_build=Linux
compiler=gcc
compiler.version=9.3
compiler.libcxx=libstdc++11
build_type=Release
region=CN
platform=orin
target_platform=orin
target_platform_type=soc
&:compiler=clang
&:compiler.version=13
&:compiler.libcxx=libc++
[options]
*:shared=True

it looks conan still use gcc to build my project。

when I add [env] CC=clang-13 CXX=clang++-13 to my profile, the compiler loos right now, 
-- The C compiler identification is Clang 13.0.1
-- The CXX compiler identification is Clang 13.0.1

but I got error:
c/lib/libglog.so: error adding symbols: file in wrong format
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm blocked again, 😭

**Comment by memsharded** [comment]
> it looks conan still use gcc to build my project。

What Conan uses to build a project and the ``settings`` are not the same. The ``settings`` is the "declaration" of configuration, but it does not automatically or magically set the environment for you.

Indeed, you need to configure the environment, like setting env-vars or whatever mechanism that you would use to use that specific compiler.

> c/lib/libglog.so: error adding symbols: file in wrong format

Are you completely 100% sure that there is perfect binary compatibility across your gcc compiled dependencies and clang. There are multitude of factors that affect, the ``libcxx`` and other stuff that can be different and will generate binary incompatibilities. In your case, it is very likely that the difference in ``compiler.libcxx`` would be causing this. To clarify, the ``compiler.libcxx`` is not configuring your environment to use one or the other, but it declares that the binaries built with gcc where built against ``libstdc++11`` and now you are trying to link with clang and ``libc++`` standard C++ library. This is not possible, this is not related to Conan, you cannot mix different standard libraries.

This is why Conan in general and by default uses the binary compatibility per compiler. Binaries built with gcc are intended to be used by gcc, and if you want to use dependencies building with clang, the safest by far is compile your dependencies with clang. So I'd strongly recommend to build the dependencies with clang, that is one of the advantages of using Conan you can build them and store them in the server without any issues or conflict with the existing gcc binaries.

**Comment by rickrick318** [comment]
I totally understand, but our project is too big and it have lots of 3rd-party dependencies which only have libs, no source code at all~, it's really impossible to build all our dependencies with clang for us.

anyway, thanks very much for your help, i will try to look other solutions~, good night.

**Comment by memsharded** [comment]
> I totally understand, but our project is too big and it have lots of 3rd-party dependencies which only have libs, no source code at all~, it's really impossible to build all our dependencies with clang for us.

So it depends on how those pre-compiled libs were built. But it is indeed most likely that if they were built with gcc, they were using ``libstdc++11``, that means that you cannot easily link them using ``clang`` linking with ``libc++``. You would need to request the vendor providing those pre-compiled binaries to generate clang-libc++ compatible binaries for you.

If there are no further questions, I am closing the ticket as resolved, but please don't hesitate to re-open or to create a new ticket if you have any further question or issue. Thanks for the feedback!
