### ISSUE TITLE
[question] CMakeDeps trying to find dependencies with cmake_find_mode none.

### ISSUE THREAD

**Issue by huysentr** [conan-io/conan#17435]
### What is your question?

Hi,

So I made a conafile.py 
`class ConanCudss(ConanFile):`
which requires
` self.requires("cuda/[>=11.0.0 <13.0.0]@devops/stable")`
My ConanCuda contains:
```
def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
```

cudss has a file `self.cpp_info.set_property("cmake_build_modules", ["append_cuda.cmake"])`

```
if(NOT APPEND_CUDA_CMAKE_INCLUDED)
    set(APPEND_CUDA_CMAKE_INCLUDED TRUE)

    # Find the CUDA Toolkit package
    find_package(CUDAToolkit REQUIRED)

    # Function to append CUDA::cudart to an existing target
    function(append_cuda_dependency target_name)
        if(TARGET ${target_name})
            target_link_libraries(${target_name} INTERFACE CUDA::cudart)
            message(STATUS "Appended CUDA::cudart to target ${target_name}")
        else()
            message(FATAL_ERROR "Target ${target_name} does not exist.")
        endif()
    endfunction()
    append_cuda_dependency(cudss::cudss)
endif()
```

This calls the native cmake shipped find package for cuda and finds the first cuda in the path which will be the conan one, because of the requirement of cudss. 
Can I prevent that the config of cudss calls `list(APPEND cudss_FIND_DEPENDENCY_NAMES cuda)` to not try and the find cuda through conan? 
I have two fixes for this, enable the CMakeDeps find mode for cuda so it creates a target that is never used. Or add custom cmake config for cuda that does find_package(CudaToolkit) 

Or can I prevent `cudss_FIND_DEPENDENCY_NAMES cuda` ?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @huysentr 

Thanks for your question.

> Can I prevent that the config of cudss calls list(APPEND cudss_FIND_DEPENDENCY_NAMES cuda) to not try and the find cuda through conan?

But this doesn't mean that cuda would be find via Conan, this would be adding a ``find_dependency()``, and that the transitive dependency must exist, but not necessarily that the ``cuda-config.cmake`` file would be provided by Conan.

If it is the CMake config filename, maybe you are looking for the ``cmake_file_name`` cpp_info property, that can be defined to configure that name?

**Comment by huysentr** [comment]
Yes, if will just try to find it, can I prevent it from trying? to find it at that level?

**Comment by memsharded** [comment]
I am afraid it is not possible, or nothing that I can think of so far. If it is a dependency defined in ``requires()`` it is a dependency, and it has to be found with ``find_dependency()``.  Could you please elaborate a bit more what is the issue you are trying to avoid? If it is not a real dependency, maybe it is only a tool-requires and you want to define it as ``self.tool_requires("cuda/...")``?
Isn't the CMake ``FindCuda.cmake`` good? How do you stablish the relationship between your ``cudass`` and ``cuda`` if the CMake scripts are completely unaware of it?

**Comment by jcar87** [comment]
If I'm understanding this correctly, you have a recipe called `cuda` with does not generate CMake files (`cmake_find_mode=none`), and you have a downstream consumer `cudss` -

And then consumers of `cudss` don't work properly because Conan is trying to do `find_package(cuda)` when resolving `find_package(cudss)`? and fails because there's nothing to resolve a package with this name? 


In your recipe for CUDA, where you have the following

```
def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
```

it may be possible to do the following:

```
def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.set_property("cmake_file_name", "CUDAToolkit")
```

this will cause conan to encode  `cudss_FIND_DEPENDENCY_NAMES CUDAToolkit ?` instead - which would actually be correct and would not conflict with the logic inside `append_cuda.cmake`

**Comment by huysentr** [comment]
That's a nice solution indeed!
