### ISSUE TITLE
Version selection logic for required items

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#1743]
I'm trying to run `conan create` in a CI environment. I would like it to always use the latest published version that is declared to be compatible. So I have a dependency set for, for example, version 0.1.x of a package, rather than a specific version.

However, it appears that when presented with this, Conan isn't always taking the latest version. Am I doing something wrong here, or is the logic just "all of these _should_ work so I'm just going to pick one"? If the latter is true, then I'd propose changing it to "take the latest compatible version" instead, as we can assume that patch number bumps would be a result of backwards-compatible bug fixes, etc., that anyone would like to incorporate.

This is the kind of behavior I'm experiencing:
```
>conan search -r artifactory BuildTools/*@autobuilder/main
Existing package recipes:

BuildTools/0.1.0.186749@autobuilder/main
BuildTools/0.1.0.186758@autobuilder/main

>conan create --manifests --update -r artifactory autobuilder/main
...
CommonLib/0.1.0.0@autobuilder/main: Building package from source as defined by build_policy='missing'
CommonLib/0.1.0.0@autobuilder/main: Installing build requirements of: CommonLib/0.1.0.0@autobuilder/main
CommonLib/0.1.0.0@autobuilder/main: Build requires: [BuildTools/[0.1.x]@autobuilder/main]
Version range '0.1.x' required by 'None' resolved to 'BuildTools/0.1.0.186749@autobuilder/main'
BuildTools/0.1.0.186749@autobuilder/main: Not found in local cache, looking in remotes...
BuildTools/0.1.0.186749@autobuilder/main: Trying with 'artifactory'...
```

I would prefer that 0.1.0.186758 be selected, which it appears to see (per the `conan search`). It appears to be non-deterministic (I've seen it work on occasion). Am I doing something wrong here?

**Comment by memsharded** [comment]
Yes, it might be a bug, I think conan "semver" just uses the first three MAJOR.MINOR.PATCH, not sure what is the behavior of the forth. Will check it.

In the meantime, are you aware of the ``conan alias`` functionality? It might have several advantages, just in case:
- It might resolve faster than version ranges, as they are actually exact versions, no need to search in remotes for matches, which is costly
- It can be managed by the package creator, upstream. Consumer just use exact versions, and package creators can evolve, revert, the aliased reference at will
- They are transparent to the dependency graph: they do not appear in the graph.

**Comment by mpdelbuono** [comment]
So I'm familiar with `conan alias` and I actually want to use it for other reasons, too, but I've been struggling to figure out the right way to bring it into the CI environment. 

I would prefer that my build server not know what version of a package it's creating, and that works great with conan because I just say `conan create` and the conanfile describes the version information that then gets put in. But in order to use the `conan alias` command I need to know the target package reference, which requires that I know the target version number. I haven't yet been able to find a good way to write the command line for the CI server. If you have any suggestions on that front I'd be very open to hearing them.

**Comment by memsharded** [comment]
Yes, that is true, for the ``conan alias`` you need to know the target reference. We have thought of several ways of automating this, so you actually don't need to do the alias command, something like ``alias_reference = "MyPkg/0.X@....`` inside the package recipe, so when you ``conan create`` it, it will also generate the alias for you. The issue with this approach is that it is error prone, because re-building old package references will set the alias to the old one, and that is not desired. 

I have to think about it, if it is not convenient (I get it why) to make the reference explicit in CI, then, something else might be needed.

**Comment by memsharded** [comment]
Hi @mpdelbuono 

I have tracked down this issue, to the library we are using. We haven't implemented the ``semver`` satisfying logic, but instead using ``node-semver==0.1.1`` package from PyPI. It seems that it is following the ``semver`` specification (http://semver.org/), and a four digit is not used at all for the matching/satisfying.

It seems that adding the fourth digit as pre-release information (with ``-``) works, though not exactly as in the specification:

```python
# prereleases are ordered
        result = satisfying(["1.1.1-1", "1.1.1-11", "1.1.1-111", "1.1.1-21"], "", output)
        self.assertEqual(result, "1.1.1-111")
        # a glitch in the semver library, in theory the result might be 1.1.1
        result = satisfying(["1.1.1", "1.1.1-11", "1.1.1-111", "1.1.1-21"], "", output)
        self.assertEqual(result, "1.1.1-111")
```

I would prefer not to deviate too much from the standard, what do you think? Is it an option?

**Comment by mpdelbuono** [comment]
Hmm... that last case is weird to me. I would have expected `1.1.1` to be chosen over `1.1.1-111` as a stable version should be accepted over a pre-release one. I do 100% agree with you that deviating from the standard is bad.

The relevant part of the spec (which I think you already identified):
```
When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version.
```

However, since this is coming from the CI system, I think it's reasonable to use this approach. All of the automated builds would be pre-release versions anyway, until someone comes along and selects it for promotion as a stable release, so that gives the developers the flexibility they need.

OK thanks. I'll try out using the pre-release identifier as the fourth digit instead. But I think the selection of the pre-release version over the normal version should be fixed (though it seems like that may be a 3rd party library problem and not in your control).

**Comment by memsharded** [comment]
>  I would have expected 1.1.1 to be chosen over 1.1.1-111 as a stable version should be accepted over a pre-release one

Yes, I agree, and it is true that it is the specification. But the current behavior of the ``semver`` library we are using seems to be wrong/buggy. I have had a look to the source code, and looked like a big effort, I will try to submit an issue to the library, lets see how it works.

**Comment by memsharded** [comment]
I think with the update to node-semver to 0.2.0, this issue was fixed.
