### ISSUE TITLE
[question] Using tools scm capture with excluded 

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#17456]
### What is your question?

Dear Conan Folks,

I have a question to: 
https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html#examples-tools-scm-git-capture.
I am trying to upgrade from conan-2.0.11 to conan2.10.2.
Earlier I have been using export_sources but this also uploads the exported sources into artifactory  which for us is not needed.
Build from sources can be fulfilled by the above feature.
We are generating code and uploading the generated code to artifactory.
Generated code is not inside the git repository.
 I need to exclude these two files which are also generated documentation otherwise the export method reports that it is dirty.
However, it looks like I donot use the fnmatch correctly or I donot instantiate the class correctly.
I use conan build + conan export-pkg to keep my use-cases locally and in CI/CD same.
The reason being our users are not necessarily software developers and need to see the folders in the same structure.
Could someone please help?

```
 def export(self):
        git = Git(self, self.recipe_folder, excluded="doc/GeneratedDev_doc.html, doc/GeneratedUser_Doc.html")
        git.coordinates_to_conandata()

    def source(self):
        git = Git(self)
        git.checkout_from_conandata_coordinates()
```
Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by maitrey** [comment]
One more point to add:
I also tried using : core.scm:local_url=allow in global.conf because of:
```
class Git:
    """
    Git is a wrapper for several common patterns used with *git* tool.
    """
    def __init__(self, conanfile, folder=".", excluded=None):
        """
        :param conanfile: Conanfile instance.
        :param folder: Current directory, by default ``.``, the current working directory.
        :param excluded: Files to be excluded from the "dirty" checks. It will compose with the
          configuration ``core.scm:excluded`` (the configuration has higher priority).
          It is a list of patterns to ``fnmatch``.
        """
        self._conanfile = conanfile
        self.folder = folder
        self._excluded = excluded
        global_conf = conanfile._conan_helpers.global_conf
        conf_excluded = global_conf.get("core.scm:excluded", check_type=list)
        if conf_excluded:
            if excluded:
                c = ConfDefinition()
                c.loads(f"core.scm:excluded={excluded}")
                c.update_conf_definition(global_conf)
                self._excluded = c.get("core.scm:excluded", check_type=list)
            else:
                self._excluded = conf_excluded
        self._local_url = global_conf.get("core.scm:local_url", choices=["allow", "block"])
```
And also tried using excluded as List of files in export method but still did not work.
Not sure what am I missing

**Comment by memsharded** [comment]
Hi @maitrey 

THanks for your question.

The exclude logic is implemented in:
```python
 lines = [line for line in lines if not any(fnmatch.fnmatch(line, p) for p in self._excluded)]
```
It is a fnmatch over the lines reported in the ``git status`` command. I'd say it is likely that the ``doc/filename`` might not be a match for the lines reported by git. Maybe you can introduce a couple of ``print()`` in the ``Git`` source code around that line that prints both the ``lines`` and the ``self._excluded``, just in case?

**Comment by maitrey** [comment]
I actually used git status -s and it shows the two files that I excluded above. When I print the lines, self._excluded and lines I got to know more of the files and my bad there was a typo in the file name.
Issue can be closed, many thanks for your support.

**Comment by memsharded** [comment]
Happy to know that it was a typo and now it works. Thanks for the feedback!

**Comment by maitrey** [comment]
One more question: 
-  core.scm:local_url=allow in global.conf Can this configuration be enabled locally if I use export method for getting the scm url and sha id?
- It seems not to respect it as if I have some local changes and want to build the package using conan build. It complains that the repo is dirty.
- What is the purpose of export_sources , for my use-case as along as I can build from sources with export/source method would work for me.

**Comment by memsharded** [comment]
> It seems not to respect it as if I have some local changes and want to build the package using conan build. It complains that the repo is dirty.

This config is only used in the ``Git`` helper, which is typically used in the ``exports()`` and ``source()`` methods. None of these methods are called in ``conan build`` command, so it is expected that the config does nothing, but it is not expected that anyone is complaining about the dirty repo in a ``conan build``. Would need details to reproduce if this is happening.

> What is the purpose of export_sources , for my use-case as along as I can build from sources with export/source method would work for me.

The ``exports`` are always downloaded with the recipe. If you have 100Mbs of sources, they will be downloaded everytime the recipe is downloaded, even if you don't need them and don't need to build from source.
The ``exports_sources`` are only downloaded when necessary to build from source.

**Comment by maitrey** [comment]
I think its the conan export-pkg that I execute after conan build that is reporting as dirty:
 git.coordinates_to_conandata()
        ConanException: Repo is dirty, cannot capture url and commit:
But then it shuld respect the global conf, right?

**Comment by memsharded** [comment]
> I think its the conan export-pkg that I execute after conan build that is reporting as dirty:
git.coordinates_to_conandata()

This is probably very expected, if you don't add the full "build" folder to the ``excluded`` field, isn't it?

> core.scm:local_url

This configuration only protects against having a commit locally in your computer that is not in the server git remote. But it won't affect the "dirty" status. For that purpose the ``core.scm:excluded`` can be used to inject exclusions.

Please, feel free to re-open the ticket if necessary, it seems there are still some open issues.

**Comment by maitrey** [comment]
Although I donot use core.scm:excluded in the global.conf, I am already using in the recipe when making an object of Git class.
It was a wrong assumption on my side. I went through the implementation(coordinates_to_conandata) and now its clear. Thanks!

**Comment by memsharded** [comment]
Ok, happy that it is clear now, thanks for the feedback!
