### ISSUE TITLE
[bug] Test Package with Tool-Requirement breaks Cross Compilation in Conan 1

### ISSUE THREAD

**Issue by Leanny** [conan-io/conan#17458]
### Describe the bug

Having a `tool_requires` in conan 1.66.0 breaks cross compilation. For whatever reason the existence of a `self.tool_requires(self.tested_reference_str)` overwrites the settings of the conanfile  with the build settings. This is not the case for conan 2, as it seems to be handled correctly there. It is also not the case with regular requires.  I added steps to reproduce this reliably in the "how to reproduce it" section. 

This issue also has implications on the generated package, as all the settings ins the finished package are also wrong.

### How to reproduce it

The exact profiles do not really matter and it can be reproduced with the following files:
conanfil.py
```python
from conan import ConanFile
from conan.tools.build import cross_building

class Broken(ConanFile):
    name = "test_package"
    settings = "os", "arch", "compiler", "build_type"
    version = "0.1"

    def build(self):
        print(self.settings.os, self.settings_build.os)
        assert cross_building(self) # this is where it breaks on conan 1
        assert not cross_building(self) # this is where it breaks on conan 2 and is what I expect for conan 1 as well
```
tesst_package/conanfile.py
```python
from conan import ConanFile

class TestConan(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    test_type = "explicit"
    
    def build_requirements(self):
        self.tool_requires(self.tested_reference_str)
        
    def test(self): pass
```

Now execute the following commands (ideally in a fresh environment) (remove comments):
```
# set up default profile
# conan 1
conan profile new --detect default
# conan 2
conan profile detect

# execute build command
conan create . -s:h os=Windows -s:b os=Linux
```

On conan 1 the output is:
```
test_package/0.1: Calling build()
Linux Linux
test_package/0.1:
test_package/0.1: ERROR: Package 'd151ebb79a8a0182dc10efb038798f07490d8d34' build failed
test_package/0.1: WARN: Build folder F:\conan_testing\.conan1\.conan\data\test_package\0.1\_\_\build\d151ebb79a8a0182dc10efb038798f07490d8d34
ERROR: test_package/0.1: Error in build() method, line 11
        assert cross_building(self)
        AssertionError:
```

On conan 2 the output is:
```
test_package/0.1: Calling build()
Windows Linux
test_package/0.1: ERROR:
Package 'c13a22a41ecd72caf9e556f68b406569547e0861' build failed
test_package/0.1: WARN: Build folder F:\conan_testing\.conan2\p\b\test_46aaca3f57031\b
ERROR: test_package/0.1: Error in build() method, line 12
        assert not cross_building(self)
        AssertionError:
```

**Comment by memsharded** [comment]
Hi @Leanny 

Thanks for your report.

I think this is working correctly.

The ``test_package`` is in the "build" context. Packages in the "build" context are never cross-built, because they need to run in the "build" context, if you cross-build it to the other platform, it will not run, and you will not be able to use it as tool-requires for your current "build" machine.

So Conan 1 is doing what is expected.

The main difference that you are seeing wrt to Conan 2 is that Conan 2 don't use the ``test_package/conanfile.py`` ``tool_requires()`` to put the requirement in the "build" context, but by default it will do the creating of the package completely independently of the ``test_package``, without even reading it, so that means by the above command line, it will be in the "host" context and it will be a cross-compilation. 
If in Conan 2 you want to force it to be built as a tool-require, then the command line is:
```
conan create . -s:h os=Windows -s:b os=Linux --build-require
```

This command line works and do the right thing, computing the package with the right context and settings, even if a ``test_package`` doesn't exist at all, and this is why this is now the recommended explicit approach in Conan 2.

**Comment by Leanny** [comment]
I see, so to summarize (and to see if I understand it correctly):
* conan 1 checks what it needs from the test package (in this case just a `tools_require`) and sets the profiles accordingly (i.e. overwriting host with build profile)

Now I wonder how I am supposed to cross-compile certain tools. For example, I want to build [Ninja](https://github.com/conan-io/conan-center-index/tree/master/recipes/ninja) with my cross-compile toolchain and provide a package for linux and windows. Since its just an executable that is produced, the only relevant parameter for the final package should be `settings.os`.
Now both, my native compiled and my cross-compiled package both have `settings.os=Linux` and I cannot find the windows package on my windows machine.
I kind of assumed that is what `can_run` is for, to ensure that `test` is only executed in the correct context and not that is enforced by overwriting the host settings.

**Comment by memsharded** [comment]
> conan 1 checks what it needs from the test package (in this case just a tools_require) and sets the profiles accordingly (i.e. overwriting host with build profile)

Yes, Conan 1 took the "root" of the dependency graph the ``test_package`` when the package was being created. That means that possible options or anything in the test_package that afected the package itself was changing how the package was created.
Which resulted in ``conan create .`` having different behavior if there exist a ``test_package`` or not. 
This was quite problematic and confusing in many cases, so Conan 2 decoupled it completely. All you need to understand how a package is created is in the package ``conanfile.py`` and the command line, nothing in the ``test_package`` conditions how the package is created, and it became a pure post-creation check.

> Now I wonder how I am supposed to cross-compile certain tools. For example, I want to build [Ninja](https://github.com/conan-io/conan-center-index/tree/master/recipes/ninja) with my cross-compile toolchain and provide a package for linux and windows. Since its just an executable that is produced, the only relevant parameter for the final package should be settings.os.

``settings.os`` and ``settings.arch`` typically.

Lets forget about ``tool-require`` usage of Ninja. I think you can do:
- Define it as a regular ``requires()`` in the ``test_package``
- Do ``conan create . -s:b os=Linux -s:h os=Linux`` # native Linux build
- Do ``conan create . -s:b os=Linux -s:h os=Windows``  # cross-build from Linux to Windows

The ``test_package/conanfile.py`` will use it with ``env="conanrun"`` and it can use the ``can_run()`` check.

That's it, basically cross-build as any other regular application (not a tool-require).

Then, if you want to have an extra ``test_package`` you can do:
- Put it in another folder like ``test_package_tool``
- Define there the ``tool_requires``
- In the case that you want to test it that way pass the ``--test-folder=test_package_tool`` (might require the ``--build-require`` too)

**Comment by Leanny** [comment]
Thanks, that should do the trick. Thank you
