### ISSUE TITLE
Tools, option to override vcvarsall.bat detection and run again

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1745]
This comes out of #1733. 

There's an apparent safeguard in `tools.vcvars_command()` which tries to prevent redundant execution of `vcvarsall.bat` if it's already been run by a previous recipe in an execution.  

This safeguard blocks the following workflow: 

Visual Studio 2017 provides numerous mechanisms for launching conan in a child process, such as `conan install <packagename> -s compiler.version=14`.  The safeguard effectively blocks the compilation using any version other than 15 if `tools.vcvars_command()` was used because it detects that the version 15 environment variables are already loaded.

There are currently a few workarounds to bypass this safeguard.  One is to nullify the "VisualStudioVersion" environment variable in all recipes that use `tools.vcvars_command()`.  Another is to simply not use `tools.vcvars_command()` and manually provide an alternative mechanism for creating the command string. 

The feature request here is to add an option such as "override=true" to tools.vcvars_command().  However, it also suggests that the desire to override is so common, that it begs the question as to why the safeguard exists in the first place.  It's possible that perhaps the safeguard can be removed, or the override=true should become the default.  This would be a significant change however, so probably requires significant discussion. It depends on what the potential dangers of running the `vcvars_command()` a second time were.

**Comment by memsharded** [comment]
Yes, this makes sense.

This guard was introduced to guarantee that clean configurations are obtained when chaining calls to different ``vcvars.bat`` from different VS versions. If some Microsoft Visual Studio expert could confirm this point, yes, I think it could be made ``override=True`` the default. Otherwise, we might keep on the safe side and make it ``override=False`` by default.

Thanks for the feedback!

**Comment by solvingj** [comment]
Note that this check is dubious to begin with, since there's actually no way to tell if the command had been run previously or not.  It simply looks for a matching value in the "VisualStudioVersion" environment variables; a somewhat loose strategy for detecting a previous vcvarsall execution.  If someone had set this globally on their machine, then tools.vcvars_command() would actually never work properly.  I suspect that there's actually no reasonable way to ensure or even define a "clean configuration" when it comes to the environment variables of vcvarsall.bat.  It might also be premature optimization if nobody can recall a single specific negative side effect that avoiding a "dirty configuration" is protecting us from. The more I think about it, the more I think this check should probably just be removed outright (pending other opinions and discussion of course). At this time, I question if it's ever protected anyone from any problem.

**Comment by memsharded** [comment]
From the microsoft documents:

https://msdn.microsoft.com/en-us/library/f2ccy3wt(v=vs.110).aspx

> If the current version of Visual C++ is installed on a computer that also has a previous version of Visual C++, you should not run vcvars32.bat from different versions in the same command window.

Similar info in: https://msdn.microsoft.com/en-us/library/f2ccy3wt(v=vs.140).aspx

So I think this feature is not possible, due to this vcvars limitation.

**Comment by memsharded** [comment]
> The more I think about it, the more I think this check should probably just be removed outright (pending other opinions and discussion of course). At this time, I question if it's ever protected anyone from any problem.

Yes, I personally have attended a few questions regarding this error where raising this error was actually detecting some misconfiguration in the environment or error in the package recipe. Given the potential problems that such overriding can have, I think we should keep all the checks, even improve them when possible.

**Comment by solvingj** [comment]
Can we still consider adding a feature to override?

**Comment by memsharded** [comment]
> Can we still consider adding a feature to override?

It might be possible to do it in the conan code, but are you sure you want to do that? Have you read the warnings from the docs? So basically the .bat scripts might be appending info, so overriding it you will end with an environment mixing paths, flags, tools from different VS versions, and the output of that would be totally undefined. The bad thing is that it might eventually seem to work for some cases, but then you will end later with the worst debugging nightmare you can imagine. 

I don't think it is a good idea to make this possible with just a flag, I prefer to be really sure that no one is doing that, otherwise we will later end with support requests that will take us forever to address. If someone wants to do that, it is easy to build a vcvars command, but I don't think conan should make this an option in its helpers.

**Comment by lasote** [comment]
Agree. If it's warned by Microsoft: "Don't do that with my tool" we are not going to allow that, it will come with more issues for us ;)

**Comment by solvingj** [comment]
It turns out I was misinformed.  Visual studio 2017 doesn't launch with the variables that `vcvarsall.bat` runs.  It only creates creates three:  
```
VisualStudioDir                C:\Users\jerry\Documents\Visual Studio 2017                                                                     
VisualStudioEdition            Microsoft Visual Studio Community 2017                                                                          
VisualStudioVersion            15.0 
```
It doesn't create the ones that are actually important, like `INCLUDE` and `LIB` are not created, and `PATH` is unaltered.  So, I would like to look into improving detection to check for these instead.

**Comment by memsharded** [comment]
I still dont get very well the point. Is it Visual Studio 2017 as launched by the IDE or from the VS prompt? Or activating the vcvars.bat?

- If it is in the VS 2017 IDE, then everything is set in the IDE, no need to activate anything, you will not be using or calling conan from it, will you?
- If it is in the prompt or activating the vcvars, you will already have all the variables including the INCLUDE, LIB, etc.

I think I might be missing something from the first use case.

**Comment by solvingj** [comment]
I will try to explain more since I was incorrect about the "root cause". 

## User Story
As a developers working in Visual Studio 2017, I should be able to be able to trigger Conan from the IDE process, and pass the variable "compiler.version=14".  

## Problem
When launching Conan from a Visual Studio 2017 process, recipe's which use `tools.vcvars_command()` will fail because they erroneously detect that `vcvarsall.bat` has been run.  It's a reasonable mistake, as Conan simply looks at the environment variable `VisualStudioVersion` to detect if `vcvarsall.bat` has been run.  Historically and for most cases where Conan is launched directly from a CLI, this was/is a decent indicator of a prior execution.  However, this variable is set by Visual Studio 2017 without running `vcvarsall.bat`, so for this case, it is not a reliable indicator. 

## Use Case Validation
It's reasonable to question whether users really try to compile with MSVC14 from an MSVC15 window.  Visual Studio has made it clear that this is supported, and the official CMake integration for Visual Studio does exactly this.  Visual Studio 2017 will effectively compile C++ with the MSVC14 compile, by passing the relevant compiler options to CMake.   See the generators section: 
https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/#configure-cmake

Of note, there were several MS tickets during the preview period for the CMake integration to solve some of the "hard-set" environment variable problems in Visual Studio to allow cross-version compiling.  So, the restriction that Visual Studio Version X should only launch compilation with compiler version X no longer exists.  

Finally, it's worth pointing out that developers who may be working on Visual Studio extensions for direct Conan integration into Visual Studio will hit this problem.

**Comment by memsharded** [comment]
Hi @solvingj 

I am not sure that launching the IDE is only creating the env-vars you said above. I am running VS 2015, and it clearly defines also LIB and INCLUDE env variables

```
-- VisualStudioVersion 14.0
1>  -- LIB C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\amd64C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib\amd64C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64lib\um\x64C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Lib\um\x64
1>  -- INCLUDE C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\includeC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\includeC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrtC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\umC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\sharedC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\winrtInclude\um
1>  
```

Same for VS 2017

```
1>-- VisualStudioVersion 15.0
1>-- LIB C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\lib\x64C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc\lib\x64C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x64C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\libC:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64lib\um\x64C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Lib\um\x64
1>-- INCLUDE C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\includeC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc\includeC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\includeC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrtC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\includeC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\umC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\sharedC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\winrtInclude\um
```

So even if we use a different detection, it doesn't seem right to activate VS2015 environment inside VS2017 IDE, because the LIB and INCLUDE variables would be already pointing to VS2017, and who knows the behavior of appending the VS2015 ones.

**Comment by memsharded** [comment]
Furthermore, if you have a .sln generated for VS 2015, and open it with VS 2017, it will keep the LIB and INCLUDE variables from VS2015, but feature a different ``VisualStudioVersion``:

```
1>-- VisualStudioVersion 15.0
1>-- LIB C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\amd64C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib\amd64C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64lib\um\x64C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Lib\um\x64
1>-- INCLUDE C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\includeC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\includeC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrtC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\umC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\sharedC:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\winrtInclude\um
```

So I would say that the only possible approach is to keep respecting the ``VisualStudioVersion``, as long as it is defined, it is not possible to activate another environment via ``vcvars``.

**Comment by lasote** [comment]
Could it make sense to use the visual studio `toolsets` in this case? https://github.com/conan-io/conan/issues/966
Could be reasonable if the CMake helper, reading the current `VisualStudioVersion` tries to apply a `--toolset` for the `compiler.version` when visual studio? I didn't try it, but maybe it's the correct way to go.

**Comment by sigmoidal** [comment]
Hi,

I just want to add another use case

On Appveyor I had a situation where I would require to use MSYS2. Unfortunately, there is a Git installation that overrides the tools of MSYS2, so MSYS2 could not be appended to PATH. I decided to prepend the PATH with the MSYS2 binary path. However, this caused another issue: because Appveyor has the VS environment pre-configured now link.exe of MSYS2 would override VS's.

I thought calling tools.vcvars_command() could solve this, as I can use the result in every self.run() prior to configure and compilation of the app. This however is not possible, because vcvars_command returns `"echo Conan:vcvars already set"`.

If vcvars_command had a simple override for detecting and setting the VS env at the user's discretion (not "on" by default would be fine), it would be very simple to tackle this. I resorted to solving it with:

```
   del os.environ["VisualStudioVersion"]
   vscmd = tools.vcvars_command(self.settings)
```

Having it built into conan tools themselves, or somehow else may help others too.

thank you.

**Comment by SSE4** [comment]
adding additional use-case to the above said - cross compiling for Windows ARM, Windows Store or WindowsPhone requires vcvars to be set with additional arguments (architecture, SDK version and platform). this for sure require to override vcvars on appveyor.

**Comment by lasote** [comment]
We have reconsidered it. If MS allows to execute it several times, we can add a parameter to allow it, even if they don't guarantee that it works, we will do the same, we will warn a message.

**Comment by solvingj** [comment]
I see the new param added here: 
https://github.com/lasote/conan/blob/d79d809e19dac16bf9ca6d8d5ee98ded01d2d7a3/conans/client/tools/win.py#L18

Is it premature to use it?  It's not in the docs yet.

**Comment by memsharded** [comment]
No, it is not premature, if it is labeled as "fixed", and then closed, it means that it has been released. So the only thing is that it is not documented. Opened a docs issue: https://github.com/conan-io/docs/issues/397
