### ISSUE TITLE
[bug] Circular import -> ImportError: cannot import name 'ref_matches' from partially initialized module 'conans.model.recipe_ref' 

### ISSUE THREAD

**Issue by nimpsch** [conan-io/conan#17452]
### Describe the bug

Hey,
it is not possible anymore to import `from conans.model.recipe_ref import RecipeReference` without getting a circular import error.

Error:
```
Traceback (most recent call last):
  File "PATH\test.py", line 1, in <module>
    from conans.model.recipe_ref import RecipeReference
  File "PATH\venv2\lib\site-packages\conans\model\recipe_ref.py", line 6, in <module>
    from conan.errors import ConanException
  File "PATH\venv2\lib\site-packages\conan\__init__.py", line 1, in <module>
    from conans.model.conan_file import ConanFile
  File "PATH\venv2\lib\site-packages\conans\model\conan_file.py", line 8, in <module>
    from conans.model.conf import Conf
  File "PATH\venv2\lib\site-packages\conans\model\conf.py", line 10, in <module>
    from conans.model.recipe_ref import ref_matches
ImportError: cannot import name 'ref_matches' from partially initialized module 'conans.model.recipe_ref' (most likely due to a circular import) (PATH\venv2\lib\site-packages\conans\model\recipe_ref.py)

```

Might be the caused by this PR -> https://github.com/conan-io/conan/commit/dcea8d9cd4533d565023e74f9909dad1652f38b2#diff-304eadc68e55b38cf6a13f7bf66e5b4675384b66920a4bd4357049a4890a1a8cR22

Conan Version: 2.10.2
OS: Windows
Python-Version: Python 3.10.5

### How to reproduce it

```
from conans.model.recipe_ref import RecipeReference
```

**Comment by memsharded** [comment]
Hi @nimpsch 

Thanks for your report.

I am afraid that the ``from conans`` space is a private implementation detail. It is not allowed to import from it, only ``from conan``.

The ``from conans`` was a legacy Conan 1.X thing that doesn't exist anymore in Conan 2, check https://docs.conan.io/1/migrating_to_2.0/recipes.html#python-import-statements. Even if there is still some legacy code, it is a private implementation details that is being gradually moved to the ``from conan`` space. Most of it is being moved to the ``from conan.internal`` space, which indicates that it shouldn't be used either, it is exclusively internal and cannot be used by recipe code.

Please let us know about your use case to import this object, as it is not part of the public API, recall only things explicitly documented in https://docs.conan.io/2/index.html can be used. Depending on the case, we might consider adding it to the public documented API. Thanks for the feedback.

**Comment by nimpsch** [comment]
@memsharded  
Thanks for the quick reply. Is there an alternative to RecipeReference/ConanfileReference? We were using it as a "helper" to obtain the channel/version information from a package reference. E.g.

```
    cfr = ConanFileReference.loads(reference)
    cfr.name
```

**Comment by memsharded** [comment]
> Thanks for the quick reply. Is there an alternative to RecipeReference/ConanfileReference? We were using it as a "helper" to obtain the channel/version information from a package reference. E.g.

No, I am afraid that at the moment there is no public API for this.

The details I would be interested to learn about the use case would be:

- Where are you obtaining that reference from? In ``conanfile.py``, the references from dependencies, like ``self.dependencies["somedep"].ref`` are already references, so you can obtain its ``.user`` and ``.channel`` if necessary. So where is it coming from?
- What would you be using the ``channel`` for in a recipe? (Recall that user/channel are no longer recommended for any maturity processing, the expectation is that recipe code never have to deal with processing user/channel manually)

**Comment by nimpsch** [comment]
We have a very simple script to promote packages from one channel to another e.g. built -> stable. This script receives as an input the package/conanfile reference and promotes it to the next channel. The alternative would be to split the string and obtain the user/channel etc. but **ConanFileReference.loads(reference)** was a nice feature :)

**Comment by memsharded** [comment]
This is exactly what I meant. From https://docs.conan.io/2/knowledge/guidelines.html#good-practices

> It is strongly discouraged to use user/channel for any quality, stage, maturity or variable information The channel part is very legacy, and should be avoided in most cases, or use a fixed string as stable. The user might be used for intra-organization private packages, while the recommendation for packages coming from ConanCenter or forks of conan-center-index Github repo is to use them without any user or channel, like the zlib/1.3.1 ConanCenter references, even for customization of the recipes and packages for those third party libraries.

> The way to manage package quality, stage or maturity promotions is by using different server repositories, and the well known developer’s best practices recommend to manage the pipelines by doing promotions (copying) immutable artifacts or packages between those different server repositories, for example copying packages from a staging repository to a production repository once they have passed some quality checks. But it is very important that this promotion does not change in any way those packages, which must be completely immutable, not even changing its user/channel, this is why the above point discourages using user and channel, packages and artifacts must be immutable.


More details about promotions in:
- https://docs.conan.io/2/ci_tutorial/tutorial.html
- https://docs.conan.io/2/devops/package_promotions.html#devops-package-promotions

**Comment by nimpsch** [comment]
Thanks for the info! We will try to find another solution

**Comment by memsharded** [comment]
Thanks for the feedback!

While the usage of user/channel is not recommended for this use case, I also understand that sometimes it is convenient to do a migration as fast as possible on the tooling side, and then try to improve and adopt best practices later.

If in your script you need to obtain user/channel, at the end of the day it is relatively simple, splitting on ``@`` and ``/`` can be done in a very few lines. Maybe that is enough to be able to move your script forward and be able to update, then address later the improvements of the pipeline?
