### ISSUE TITLE
[question] cross build package setup

### ISSUE THREAD

**Issue by angelfromhell** [conan-io/conan#17464]
### What is your question?

Hi
so i am trying to create a package for a cross compiler and want to test it if it works with a test_package. and i get a bit confused about how to do it right

when i build the gcc on Linux for Linux all is fine
just doing a 
`conan build .`
`conan export-pkg --profile:h baremetal/riscv --build require
`
My first intention was to do it without host profile, but that resulted in the problem that always the -m64 tag was added to the cmake setup in the test package, and i didnt find really a way how to get rid of it programatically of the m64 tag

the next step was doing the same for windows

`conan build . --profile:h windows `
`conan export-pkg --profile:h baremetal/riscv --build require
`
but now of course what i did in the previous step not completely clean, now resulted in an error during the build step 
what is the right way to do it 

a) is there a way to remove the architecture tags for the tool chain 
or
b) is there a clean way to use the profiles 

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @angelfromhell 

Thanks for your question.

There are different aspects and issues in this ticket.
First, it would be good to report if things work with the ``conan create`` command, for both cases.

Then, I am not sure if I understand it, but why the ``conan build`` and the ``conan export-pkg`` receive different arguments?
The expectation is that you want to package with ``export-pkg`` the thing that you just built. But you are building a thing and packaging a different one.

Then, for running different ``conan build`` with different configurations, it would be important to define a clean ``layout`` that do not cause overlap or pollution for the ``conan export-pkg`` step.


>  is there a way to remove the architecture tags for the tool chain

That would be a completely different ticket, and would require reporting details about the profile, the build-system integrations used, etc. For example, there is a recent fix that avoids creating that flag when using clangcl on Linux to cross-build to windows

It is also necessary to report the Conan version, I suggest sharing the output of ``conan version`` command.

**Comment by angelfromhell** [comment]
i admit that i misused the profiles in conan  ... but was more to check what was going on..
let me close this ticket and open a new one wrt the m64 flag
