### ISSUE TITLE
[bug] conan 2.10.1, libiconv - AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by trexxet** [conan-io/conan#17465]
### Describe the bug

I'm using MINGW64 shell under MSYS2.

Profile (default):
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu23
compiler.libcxx=libstdc++11
compiler.version=14
os=Windows

[platform_tool_requires]
cmake/3.31.2
msys2/cci.latest

[conf]
tools.microsoft.bash:subsystem=mingw64

[buildenv]
PATH=+(path)C:\msys64\mingw64\bin
```

conanfile.txt:
```
[requires]
sdl/2.30.9

[generators]
CMakeDeps
```

Output of `conan install . --output-folder=build --build=missing`:
```
libiconv/1.17: Building from source
libiconv/1.17: Package libiconv/1.17:0534efa715363b456efc91df5dd071bc6eefb323
libiconv/1.17: Copying sources to build folder
libiconv/1.17: Building your package in C:/Users/trexxet/.conan2/p/b/libic29e8f0b959fa9/b
libiconv/1.17: Calling generate()
libiconv/1.17: Generators folder: C:/Users/trexxet/.conan2/p/b/libic29e8f0b959fa9/b/build-release/conan
ERROR: libiconv/1.17: Error in generate() method, line 87
        env.generate()
        AttributeError: 'NoneType' object has no attribute 'startswith'
```

I did set `[platform_tool_requires]` and did not set `[generators] CMakeToolchain` because I don't want Conan to define my toolchain for CMake, or to download CMake and MSYS (which it automatically attempts to do). I only want it to download the SDL2 and it's dependencies, put it in appropriate folder and let my local CMake know where to look for them.

conan 2.10.1, Python 3.12.7

**Comment by memsharded** [comment]
Hi @trexxet 

Thanks for your report.

It seems that you are using an invalid value for the subsystem:
```
$ conan config list msys
tools.microsoft.bash:subsystem: The subsystem to be used when conanfile.win_bash==True. Possible values: msys2, msys, cygwin, wsl, sfu
```
The ``mingw64`` is not a valid value, the subsystem to use should be ``msys2``.
It is true that the message reporting it could be better, as this is not checked, I'll see if it can be improved.

I have checked, and using this profile it seems to work fine:
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu23
compiler.libcxx=libstdc++11
compiler.version=14
os=Windows

[platform_tool_requires]
cmake/3.31.2
msys2/cci.latest

[conf]
tools.microsoft.bash:subsystem=msys2
# I need this for prioritization over my WSL bash
tools.microsoft.bash:path=C:\ws\msys64\usr\bin\bash.exe

[buildenv]
PATH=+(path)C:\ws\msys64\mingw64\bin
```

Said that it is also important to know that ConanCenter recipes and packages are only built in Windows for MSVC compiler. That means that support for MinGW might vary, and some recipes might not work and built correctly for MinGW. There are plans to try to improve this, but at the moment still not happened, so just be aware. It is expected that the quality for MSVC support is much better and it will have pre-compiled binaries for latest compilers, being much faster to install.

**Comment by trexxet** [comment]
Thank you for the answer. Yes, changing `tools.microsoft.bash:subsystem` to `msys2` fixed the problem.

However,
```
libiconv/1.17: ERROR: 
Package '0534efa715363b456efc91df5dd071bc6eefb323' build failed
libiconv/1.17: WARN: Build folder C:/Users/trexxet/.conan2/p/b/libic5fdbf5260bfa3/b/build-release
ERROR: libiconv/1.17: Error in build() method, line 146
        autotools.configure()
        ConanException: The config 'tools.microsoft.bash:path' is needed to run commands in a Windows subsystem
```
Thus, I suppose `tools.microsoft.bash:path` should be mandatory as well. Having both `path` and `subsystem` set, the `generate()` step finished successfully, and `libiconv` and `sdl` was built.

Also, I'd like to clarify - does the ConanCenter store prebuilt binaries? E.g., SDL releases (https://github.com/libsdl-org/SDL/releases/tag/release-2.30.10) contain all the necessary runtime DLLs for Windows, static binaries and headers for MinGW, so I don't see a point in building them from source.

**Comment by memsharded** [comment]
> Thus, I suppose tools.microsoft.bash:path should be mandatory as well. 

Yes, this is what the error message is saying now, and you can check that I defined it in my profile to work, see above ``tools.microsoft.bash:path=C:\ws\msys64\usr\bin\bash.exe``

> Also, I'd like to clarify - does the ConanCenter store prebuilt binaries? E.g., SDL releases (https://github.com/libsdl-org/SDL/releases/tag/release-2.30.10) contain all the necessary runtime DLLs for Windows, static binaries and headers for MinGW, so I don't see a point in building them from source.

Yes, one of the key features of Conan is managing pre-compiled binaries too, and the capability of building them from source when necessary. ConanCenter hosts already a bunch of different pre-compiled variants for Windows, Linux, OSX, different flavors, compiler versions, etc. This feature also allows for Conan users to build themselves the packages from source, which is a critical requirement for many users due to policies, regulations and other business constraints, and store the binaries in their own private server (like the ArtifactoryCE that can be downloaded from Conan download page), avoiding their developers to have to rebuild from source again and again the same binaries, even if they build with different requirements, architectures, patches, etc, different from the binaries of the upstream project. Not to say that many projects do not release binaries for all platforms or don't release binaries at all.

**Comment by trexxet** [comment]
Thank you for the answer.
I tried running `conan install . --output-folder=build --build=never`, but got an error. Then I checked `conan list "libiconv/1.17:*" -r=conancenter` - and yes, there are no package for both gcc and Windows. Anyway, the problem is solved, thank you!

**Comment by memsharded** [comment]
> - and yes, there are no package for both gcc and Windows.

yes, exactly, this is what I was commenting above, at the moment in Windows, only ``msvc`` binaries are built and tested, this is why the quality for MinGW support might vary (and binaries don't exist)

Thanks for the feedback!
