### ISSUE TITLE
[question] how to manage the conanfile.py in Git source Folder.

### ISSUE THREAD

**Issue by crystalsky** [conan-io/conan#17461]
### What is your question?

When placing conanfile.py in the Git source directory, after running conan install ..., conan build ..., conan export-pkg ..., and conan upload, the source code from the Git directory gets uploaded to the remote.

When other dependent libraries execute --build=missing, the conanfile.py downloads the previously packaged source code into the local cache. However, during the execution of the source() method, Git fails to download the source code.

I would like to use conandata.yml to store the Git repository URL, so that conanfile.py can automatically download the source code before the build process starts.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @crystalsky 

Thanks for your question.

This is how the ``scm`` capture information works. 
Please have a look to the docs in https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html, they use a full working example code in the ``examples2`` repo.

**Comment by crystalsky** [comment]
thanks ,i will follow the documetion to.

**Comment by memsharded** [comment]
Sounds good.

Closing the ticket as responded, but don't hesitate to re-open or create new tickets for any further question. Thanks for the feedback!
