### ISSUE TITLE
conan upload - support "path to a conanfile" argument 

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1746]
`conan create myname/mychannel` creates a local package and deduces the package name and version from the conanfile.py in the current directory. 

My first thought was that I could do `conan upload myname/mychannel` in the same directory and it would logically grab and upload the package I just built.  It turns out `conan upload` is a much more general facility, aiming to allow users to specify any package in their local cache by pattern. 

Please consider adding a `path` argument to `conan upload` which looks for a conanfile, deduces the reference from it, and uploads that.  Most importantly, this should be do-able without breaking the existing behavior. 

This would have positive implications in simplifying conan package tools, which could then default to looking in the current directory for a file and deducing the package reference.  For most cases, this eliminates the need to set CONAN_REFERENCE variable manually.

**Comment by lasote** [comment]
I'm currently struggling against the conan commands that sometimes feels very complex because of the multiple optional parameters. I understand the motivation and maybe we can find a good fix, but I think that making upload command more complex is not the way to go.

**Comment by solvingj** [comment]
I agree, when things have a "second mode" with a wildly different behavior, I find it confusing. Conan was first time I experienced this issue. Will think on it for a bit.

**Comment by solvingj** [comment]
Closing because new command structure changed the way this worked.

**Comment by gndl** [comment]
@solvingj , I'm having the same problem and I would be very interested to know how you managed to get around it.
Thank you for your feedback.

**Comment by gndl** [comment]
I would like to call conan upload without passing the name and version number of the current project. Conan could find this informations in the conanfile.py. The goal is to integrate this command into Visual Studio as an external tool. I could make a script that would call conan with this informations in parameter but it would force the users to have to modify this information in two different places.
Thank you for your attention.

**Comment by memsharded** [comment]
The ``conan upload`` is not tied at all to any local conanfile. It is an operation between the local cache and the servers. Also, conanfile.py do not necessarily have name/version in them, as they can be specified dynamically in the ``conan create . PkgName/Version@user/channel``.
