### ISSUE TITLE
[bug] Warnings from Python libraries pollute json output

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#17462]
### Describe the bug

Conan 2

### How to reproduce it

We're using the parameter `--format json` when running `conan create` to get some information about the build. The output is redirected into a file using `> buildinfo.json`. The problem is now that when an internally used library like urllib emits warnings to stdout this output ends up in the json file, making it invalid. We stumbled across this bug after updating to Python 3.11 and a new urllib version which now prints warnings whenever a conanfile performs a download with `verify=False`. 

My suggestion would be to change the `--format json` parameter to `--json <filename>` and write only the json data to the specified file.

**Comment by czoido** [comment]
Hi @jasal82,

Thanks a lot for your question. 

I was trying to check the issue reproducing it but it seems that the logs from urlib3 are not polluting the stdout for me. 
We have specifically a line in Conan to avoid this here: https://github.com/conan-io/conan/blob/77a70515cb5f4057d6ff09ffdde4df779bf7d99f/conans/client/rest/conan_requester.py#L24 as suggested in the urlib3 docs: https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

Could you please guide me to try to reproduce the issue?

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/17507 adds a new ``--output-file`` to enforce writing the result in that file irrespective of the ``stdout`` redirections or other possible issues. It will be in next Conan 2.12. Thanks for the feedback!

**Comment by jasal82** [comment]
Thank you
