### ISSUE TITLE
[question] why do I get deprecation warnings while compiling recipes from conan2?

### ISSUE THREAD

**Issue by gilmatok** [conan-io/conan#17468]
### What is your question?

Hi,

I've my conan remote to use conan2 remote at "https://center2.conan.io", and made sure this is the only remote I'm fetching recipes from.

However, when trying to build packages, I see the following deprecation warnings. 
This is an example from package `zlib/1.3.1`:
```
WARN: The use of 'cpp_info.names' is deprecated in Conan 2.0 and will be removed in Conan 2.X. Please, update your recipes unless you are maintaining compatibility with Conan 1.X
WARN: The use of 'cpp_info.names' is deprecated in Conan 2.0 and will be removed in Conan 2.X. Please, update your recipes unless you are maintaining compatibility with Conan 1.X
``` 

Does that mean that zlib haven't updated their conanfile to use the new fields?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gilmatok 

Thanks for your question.

Yes, the ``zlib`` recipe in ``conan-center-index`` already has updated its ``conanfile.py`` to support Conan 2, and use the new fields. It did a long time ago. 

What it hasn't done yet is to remove the legacy ones. They are being gradually removed, but ConanCenter as a lot of activity, so this kind of deprecation is not being prioritized, it is being done mostly when other changes are done. So these warnings are expected to disappear in the following months, but no rush.

**Comment by gilmatok** [comment]
Thank you @memsharded.

**Comment by memsharded** [comment]
Thanks for the feedback.
I am closing this ticket as responded then, don't hesitate to re-open or create new tickets for any further questions you might have.
