### ISSUE TITLE
[question] How to remove -m64 tag from cmake during test package execution

### ISSUE THREAD

**Issue by angelfromhell** [conan-io/conan#17471]
### What is your question?

Hi, 

i have the following situation 
i build a compiler and want to test this compiler with a test package   (conan version 2.10.2)
the created compiler does not support the -m64 flag

for the build i just use a default profile
host = Linux
arch = x86_64

the package is all perfectly build but when i call the test package, this takes over the profiles from the original package
with that it somehow selects the  -m64 build flag für Cmake leading to an error 

the test package code is simple

def build_requirements()
    self.tool_requires( "self reference")

generate()
   tc = Cmake tool chain
   tc.generate

build()
   tc = Cmake()
   tc.configure()
   tc.make()

ii test everything with a "conan create ."

how do i get rid of the m64 flag in the test package, it inserts it as it thinks i am building for Linux x86_64. yet i wanna build for bare_metal

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @angelfromhell thanks for your question.

As per the [`conan create` documentation](https://docs.conan.io/2/reference/commands/create.html#using-conan-create-with-build-requirements), tool requires are expected to be created with `--build-require` in the `conan create` invokation.

This might be the missing bit to get your compiler to work. Could you try and let us know? Thanks! :)

**Comment by angelfromhell** [comment]
hello Abrill, 

i tried it, but it didnt seem to work. 

so what i try to achieve
Build_profile                             
Linux
x86_64

host_profiles
Linux    & windows                      
                             
target_profile ( not used )   
baremetal                             

when i tried the linux compilation with --build_require
the test_package still used the linux profile and with that set the -m64 bit

**Comment by memsharded** [comment]
Could you please provide more feedback about your specific compiler? 
Is it a new compiler, that you add to custom ``settings_user.yml``, or is it a ``gcc`` compiler?
The ``-m64`` flag will only be added in ``architecture_flag()`` function for known compilers like ``gcc`` that are supposed to support the flag.


The machine that will run the final binaries is a "Linux & x86_64" machine? (I am a bit confused about the target_profile - baremetal comment above)

**Comment by angelfromhell** [comment]
basically the compiler is  generated by xt-ng. it is based on gcc 13.2.0, however specific for riscv. 
i have to check what the compiler uses as nametag, if it is gcc and conan checks for that, then it would explain the behaviour and i need to check if i can change that tag. That was not so obvious too read out of the source code of conan.

with target profile i meant that the compiler will generate a binary for baremetal/riskv. 

i need to check tomorrow...

**Comment by memsharded** [comment]
> basically the compiler is generated by xt-ng. it is based on gcc 13.2.0, however specific for riscv.

Probably I don't have enough context and information, but if I understand correctly, I'd say that your scenario is something like:

HOST profile:
```
[settings]
os=baremetal
arch=riscv64
compiler=mygcc?? or xt-ng-gcc?
compiler.version=...
```
Then the BUILD profile would be your current Linux machine:
```
[settings]
os=Linux
arch=x86_64
...
```
Then when Conan builds some package, it should not inject the ``-m64``, because it will be building for the ``baremetal/riscv64`` platform, and that do not add any flag.
Note these profiles should be used consistently when creating packages, also when creating the compiler themselves.

**Comment by angelfromhell** [comment]
you are fully right, i missed setting a new compiler in the host profile as it wasn't so obvious for me  at first that this one was passed to the test package... 

so host profile was 
[settings]
os=Windows or Linux
arch=x86_64  or ...
compiler=riscv-gcc

i couldnt use baremetal in the host profile as i already do a cross-compilation too for the gcc

many thanks for your help :-) i just started the final run, when i passes, i will close the ticket....

**Comment by angelfromhell** [comment]
all worked now

**Comment by memsharded** [comment]
Amazing, very happy it works now, thanks very much for your feedback!
