### ISSUE TITLE
[question] Distinguish package variants by profile settings

### ISSUE THREAD

**Issue by chfuerst** [conan-io/conan#17478]
### What is your question?

Hi !

Cross-referring to ticket conan-io/docs#3960  ,  i was thinking about specifying an operating system specific setting named "distro" and "distro.version", as shown in: https://docs.conan.io/2/examples/config_files/settings/settings_user.html#examples-config-files-settings-user

Now i have two recipes, recipe 1 with the set of default settings: 
```
settings = "os", "arch", "compiler", "build_type"
```
and one updated recipe 2 with
```
settings = "os", "arch", "compiler", "build_type", "distro"
```
which are hosted at artifactory.

My expectation was somehow, that IF i have the setting "distro" in my local conan profile, that it will download (if pre-built is available), resp. build if missing (if the respective command build=missing is set) variant recipe 2, while if its not set, it will 
compare the settings "os", "arch", "compiler", "build_type" to recipe version 1, with what packages are uploaded there;

I know that the package id is computed as described in https://docs.conan.io/2/reference/binary_model/package_id.html

However, which recipe is downloaded - in my understanding is calculated from the available local profile - which seems not to be the case. Is there a way to enforce, which of the two recipes shall be considered?

BR;
Christoph

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @chfuerst 

Thanks for your question.

Note that in general, it is more recommended to have ``distro`` as a sub-setting, not as a setting, see ERROR: Missing prebuilt package for 'package_name':

- It allows adding and using it without having to modify recipes
- It can be introducing without breaking or invalidating existing ``package_id`` binaries
- It automatically does consistency checking (you cannot define ``distro=ubuntu`` for a ``Windows`` package for example)


> My expectation was somehow, that IF i have the setting "distro" in my local conan profile, that it will download (if pre-built is available), resp. build if missing (if the respective command build=missing is set) variant recipe 2, while if its not set, it will
compare the settings "os", "arch", "compiler", "build_type" to recipe version 1, with what packages are uploaded there;

There is some misunderstanding here. The ``settings`` do not define the recipe that is downloaded at all, they define only the binary with the ``package_id`` that is downloaded. Changing one recipe generates a new ``recipe-revision``, and a new recipe revision should have its own binaries. A new recipe revision means change in the sources, and every change in sources should have its different binaries. The recipe that is downloaded depends on the ``required`` version and by default it retrieves the latest recipe revision (you can change that using lockfiles or hardcoding, but lockfiles would be recommended in general). You can read more about revisions in https://docs.conan.io/2/tutorial/versioning/revisions.html.

Please let me know if this clarifies the issue.

**Comment by chfuerst** [comment]
Dear @memsharded 

Thanks for your kind response. To be frank, i didn't consider the option of making distro a sub-setting of the os-setting, so i don't need to re-define the recipes, and publish a new revision.

Made my day.

Thx, BR, Merry Christmas,
Christoph

**Comment by memsharded** [comment]
Great, happy to know it helped. You can find some of that discussion in https://docs.conan.io/2/reference/config_files/settings.html#adding-new-sub-settings

Then I think we can close this question as solved, but please don't hesitate to re-open or create new tickets for any further question. Thanks very much for your feedback and merry Christmas too!
