### ISSUE TITLE
[question] Define dependency options in Conan 2.8 

### ISSUE THREAD

**Issue by Jannis1994** [conan-io/conan#17476]
### What is your question?

Hello together,
in Conan1 I had the following syntax that was working.

def requirements(self): 

        configFile = tools.load(os.path.join(self.recipe_folder, "build_configs.json"))
        configs = json.loads(configFile)

        for requirement in set(configs[str(self.options.variant)]['requires'] + configs['ALL']['requires']):
            self.requires(requirement)
        self.options["package_name"].package_option="real_package_value"

In Conan2.X this changed and I get the following error:
 
>======== Computing necessary packages ========
>ERROR: package_name_to_be_created: Dependencies options were defined incorrectly. 
>Maybe you tried to define options values in 'requirements()' or other invalid place

So I checked what needs to be changed in Conan2.
In other threads I saw that I need to move the self.options adaptation to def configure(self): inside the conanfile.py

I did it like that:

def configure(self):

        self.options["package_name"].package_option="real_package_value"

Unfortunately the error message is now:

> ERROR: Missing binary: package_name
> package_name: WARN: Can't find a 'package_name' package binary 'hash' for the configuration:
[options]
>package_option=real_package_value
>ERROR: Missing prebuilt package for 'package_name'

> 
Can someone maybe help me?
What do I need to do, to achieve the same functionality in Conan2 that I had in Conan1. I also tried with package_name/* etc..
Currently it looks like the entry inside the configure method is beeing ignored.

Best regards, 
Jannis 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Jannis1994 

Thanks for your question.

> ERROR: Missing binary: package_name
package_name: WARN: Can't find a 'package_name' package binary 'hash' for the configuration:

It seems that this would be something unrelated. There is no binary that was built for that configuration, isn't it?

You have now in Conan 2 the ``conan graph explain`` command that can look for existing packages and report differences between the existing packages and requested packages. Or doing a ``conan list pkg/version:*`` will list your existing binaries (use ``-r=myremote`` to list the binaries in the remote). Can you please check this? Thanks!

**Comment by Jannis1994** [comment]
Hello @memsharded 
Thanks for your fast answer.
I used the command:
``
conan graph explain conanfile.py -o '&:variant=GEN2'
``
The feedback is the following: 
======== Computing dependency graph ========
....
======== Computing necessary packages ========
Requirements
package_name/package_version - Cache
...
======== Retrieving and computing closest binaries ========
"ERROR: There is no missing binary". 

Other than that it is computing necessary packages.
The package is also existing and available in cache.

**Comment by memsharded** [comment]
That is a bit unexpected, if you got a ``ERROR: Missing prebuilt package for 'package_name'`` first.

Could you please do the following?
- Share the full command that you are using to get the ``ERROR: Missing prebuilt package for 'package_name'`` message, and also the full output.
- Share the full command you are using in the ``graph explain`` command (the arguments must be the same), and the full output
- Share the ``conan list`` command and output.

Thanks for the feedback!

**Comment by Jannis1994** [comment]
Hello sure, but please be aware that I cannot share internal data, therefore I changed the names:

``
uidXXXX@BuildPC2204WSL:~/Conan2_Dependencies_PoC$ conan create . -o "&:variant=GEN2" -o *:corbos_adg_compatibility=50.1.1 --user user --channel testing -f json --update > conan_info.json
``
```plaintext
======== Exporting recipe to the cache ========
perfcomp/r-car_v13@user/testing: Exporting package recipe: /home/uidXXXX/Conan2_Dependencies_PoC/conanfile.py
perfcomp/r-car_v13@user/testing: Calling export()
perfcomp/r-car_v13@user/testing: Copied 1 '.py' file: conanfile.py
perfcomp/r-car_v13@user/testing: Copied 1 '.json' file: 0_build_configs.json
perfcomp/r-car_v13@user/testing: Exported to cache folder: /home/uidXXXX/.conan2/p/perfce84efbc351b91/e
perfcomp/r-car_v13@user/testing: Exported: perfcomp/r-car_v13@user/testing#b7de95f89cd3f8dcbcb7a2dc44f1b23e (2024-12-17 10:16:38 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
os=Linux
[options]
&:variant=GEN2
*:corbos_adg_compatibility=50.1.1

Profile build:
[settings]
arch=x86_64
build_type=Release
os=Linux


======== Computing dependency graph ========
perfcomp/r-car_v13@user/testing: Checking remote: ics
perfcomp/r-car_v13@user/testing: Checking remote: ics-testing
baseiamge/test_image_v1@ccp/testing: Checking remote: ics
baseiamge/test_image_v1@ccp/testing: Checking remote: ics-testing
application_2/601.0.4@ccp/stable: Checking remote: ics
application_2/601.0.4@ccp/stable: Checking remote: ics-testing
application_1/4.2.00@ccp/stable: Checking remote: ics
application_1/4.2.00@ccp/stable: Checking remote: ics-testing

Graph root
    cli
Requirements
    baseiamge/test_image_v1@ccp/testing#be8b34538f1e34dace753402c375204a - Cache (ics-testing)
    perfcomp/r-car_v13@user/testing#b7de95f89cd3f8dcbcb7a2dc44f1b23e - Not in remote
Build requirements
    application_2/601.0.4@ccp/stable#242acb3c66cdc5126b2a1131093e8c0c - Cache (ics-testing)
    application_1/4.2.00@ccp/stable#7e1f1373f938c5609be8038d879f0c0c - Cache (ics-testing)

======== Computing necessary packages ========
perfcomp/r-car_v13@user/testing: Forced build from source
Requirements
    baseiamge/test_image_v1@ccp/testing#be8b34538f1e34dace753402c375204a:683f1a16bd2e6ea9e5a21d30589d2b349c92bdd8 - Missing
    perfcomp/r-car_v13@user/testing#b7de95f89cd3f8dcbcb7a2dc44f1b23e:d121b2fe61f4d713cf18857cbbe70969abc7dfbe - Build
Build requirements
    application_2/601.0.4@ccp/stable#242acb3c66cdc5126b2a1131093e8c0c:dd9fcf3ea17f8d4dbb2d04aa6067e0fab411b673#0576c1571a95d078bde7a4e09e5ad223 - Cache
    application_1/4.2.00@ccp/stable#7e1f1373f938c5609be8038d879f0c0c:dd9fcf3ea17f8d4dbb2d04aa6067e0fab411b673#2963fff7ee1f049aa87ecc0014d377d4 - Cache
ERROR: Missing binary: baseiamge/test_image_v1@ccp/testing:683f1a16bd2e6ea9e5a21d30589d2b349c92bdd8

baseiamge/test_image_v1@ccp/testing: WARN: Can't find a 'baseiamge/test_image_v1@ccp/testing' package binary '683f1a16bd2e6ea9e5a21d30589d2b349c92bdd8' for the configuration:
[options]
corbos_adg_compatibility=50.1.1

ERROR: Missing prebuilt package for 'baseiamge/test_image_v1@ccp/testing'. You can try:
    - List all available packages using 'conan list "baseiamge/test_image_v1@ccp/testing:*" -r=remote'
    - Explain missing binaries: replace 'conan install ...' with 'conan graph explain ...'
    - Try to build locally from sources using the '--build=baseiamge/test_image_v1@ccp/testing' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'

```
``
uidXXXX@BuildPC2204WSL:~/Conan2_Dependencies_PoC$ conan graph explain . -o "&:variant=GEN2" -o *:corbos_adg_compatibility=50.1.1 --user user --channel testing -f json --update > conan_info.json
``
```plaintext
======== Computing dependency graph ========
baseiamge/test_image_v1@ccp/testing: Checking remote: ics
baseiamge/test_image_v1@ccp/testing: Checking remote: ics-testing
application_1/4.2.00@ccp/stable: Checking remote: ics
application_1/4.2.00@ccp/stable: Checking remote: ics-testing
application_2/601.0.4@ccp/stable: Checking remote: ics
application_2/601.0.4@ccp/stable: Checking remote: ics-testing

Graph root
    conanfile.py (perfcomp/r-car_v13@user/testing): /home/uidXXXX/Conan2_Dependencies_PoC/conanfile.py
Requirements
    baseiamge/test_image_v1@ccp/testing#be8b34538f1e34dace753402c375204a - Cache (ics-testing)
Build requirements
    application_2/601.0.4@ccp/stable#242acb3c66cdc5126b2a1131093e8c0c - Cache (ics-testing)
    application_1/4.2.00@ccp/stable#7e1f1373f938c5609be8038d879f0c0c - Cache (ics-testing)

======== Computing necessary packages ========
Requirements
    baseiamge/test_image_v1@ccp/testing#be8b34538f1e34dace753402c375204a:683f1a16bd2e6ea9e5a21d30589d2b349c92bdd8 - Missing
Build requirements
    application_2/601.0.4@ccp/stable#242acb3c66cdc5126b2a1131093e8c0c:dd9fcf3ea17f8d4dbb2d04aa6067e0fab411b673#0576c1571a95d078bde7a4e09e5ad223 - Cache
    application_1/4.2.00@ccp/stable#7e1f1373f938c5609be8038d879f0c0c:dd9fcf3ea17f8d4dbb2d04aa6067e0fab411b673#2963fff7ee1f049aa87ecc0014d377d4 - Cache

======== Retrieving and computing closest binaries ========
Missing binary: baseiamge/test_image_v1@ccp/testing
With conaninfo.txt (package_id):
[options]
corbos_adg_compatibility=50.1.1

Finding binaries in the cache
Finding binaries in remote ics
Finding binaries in remote ics-testing


======== Closest binaries ========
```
``
uidXXXX@BuildPC2204WSL:~/Conan2_Dependencies_PoC$ conan list baseiamge/test_image_v1@ccp/testing#be8b34538f1e34dace753402c375204a:* -r icas-testing
``
```plaintext
icas-testing
  baseiamge
    baseiamge/test_image_v1@ccp/testing
      revisions
        be8b34538f1e34dace753402c375204a (2024-12-03 16:53:07 UTC)
          packages
            19495541e0b3baf87bb2d9eec8adc588c2ec5f74
              info
                options
                  corbos_adg_compatibility: 50.7.1
uidXXXX@BuildPC2204WSL:~/Conan2_Dependencies_PoC$ 
```

**Comment by Jannis1994** [comment]
My files:
0_build_configs.json

```json
{
    "ALL": {
        "requires": [],
        "build_requires": [
            "application_1/4.2.00@ccp/stable"            
        ]
    },
    "GEN2": {
        "requires": [
            "baseimage/test_image_v1@ccp/testing"
        ],
        "build_requires": [            
            "application_2/601.0.4@ccp/stable"
        ]
    }
}

**Comment by Jannis1994** [comment]
My conanfile:
```python
from conan import ConanFile, tools
from conan.tools.files import mkdir, chdir, copy
from conan.tools.scm import Git
from conan.tools.files import load, update_conandata
from conan.errors import ConanException, ConanInvalidConfiguration
from datetime import datetime
import os
import json #to parse the configuration files




class PerfcompConan(ConanFile):
    name = "perfcomp"
    vwversion = "A622"
    r7version = "A621"
    author = "A622"
    buildversion = "r-car_v13"

    license = "COPYRIGHT"
    url = "github server adress"

    version = buildversion
    description = "BUILDVERSION: {}, VWVERSION: {}".format(buildversion, vwversion)
    keep_imports = True
    options = {
        "variant": ["ME3", "EVO", "GEN2"],
        "corbos_adg_compatibility": ["ANY"]    
    }  
    # Disable environment generators
    virtualbuildenv = False 
    virtualrunenv = False   

    def export(self):   
                
        copy(self,"0_build_configs.json",src=self.recipe_folder, dst=self.export_folder)   
    
    
    def configure(self):
        self.options["baseimage"].corbos_adg_compatibility="50.7.1"             
    

    def requirements(self):         
        # set the requires depending on the variant option:
        configFile = tools.files.load(self, os.path.join(self.recipe_folder, "0_build_configs.json"))
        configs = json.loads(configFile)
        # add all requirements from the current variant and "ALL" variant, avoid duplicates        
        for requirement in set(configs[str(self.options.variant)]['requires'] + configs['ALL']['requires']): 
            self.requires(requirement)
            
        #self.options["baseimage*"].corbos_adg_compatibility="50.7.1"
                        
        
    def build_requirements(self):
        # set the build requires depending on the variant option:
        configFile = tools.files.load(self, os.path.join(self.recipe_folder, "0_build_configs.json"))
        configs = json.loads(configFile)
        
        # add all build requirements from the current variant and "ALL" variant, avoid duplicates
        for brequirement in set(configs[str(self.options.variant)]['build_requires'] + configs['ALL']['build_requires']):
            self.build_requires(brequirement)

**Comment by memsharded** [comment]
Thanks for the details! I think that explains it:

The binary that exists in the server is built with ``corbos_adg_compatibility: 50.7.1``

The package that is being requested is `` -o *:corbos_adg_compatibility=50.1.1``. Note that in Conan 2, the user inputs from profiles and command line always have highest precedence than recipe defined ones (you can use the ``important!`` options to define different levels of priority, but still the principle applies, the downstream user via profile/cli-args always have priority, https://docs.conan.io/2/reference/conanfile/attributes.html#default-options).

**Comment by Jannis1994** [comment]
Yes sometimes we have the problem that we get packages with the wrong options set, but with the override it was possible in the past to still do a build.

**Comment by memsharded** [comment]
Ok, then this seems to explain the behavior, isn't it?

The recipe options definition in Conan 1 had priority, was kind of hardcoding it, which left users often without any possibility to do what they wanted, as the recipe always had precedence, and that was quite annoying for users.

Can we close the question as solved then? Thanks for your feedback!

**Comment by Jannis1994** [comment]
Thanks for the explanation.
Could you maybe show an example how I can achieve the old behavior?

I dont want to change/adapt profiles. Do I just have to remove the -o options from the conan create command and set it in the conanfile.py itself, then it will work?

I mean something like this is not workig:
self.options["baseimage"].corbos_adg_compatibility="50.7.1" !important

I have something like this in mind:
conan create . --user user --channel testing -f json --update > conan_info.json
```python
def configure(self):
        self.options.corbos_adg_compatibility = "50.1.1"
        self.options.variant = "GEN2"
        self.options["baseimage"].corbos_adg_compatibility="50.7.1" 

```

But I will also deep dive into it more.

**Comment by memsharded** [comment]
> Could you maybe show an example how I can achieve the old behavior?

In your recipe:
```python
class Pkg(ConanFile):
    name = "mypkg"
    default_options = {"*:myoption!": 1}
```

If using in the command line ``-o "*:myoption=2"`` the option value for the dependencies of ``mypkg`` will be "1"
If using in the command line ``-o "*:myoption!=2"`` then the option value for the dependencies of ``mypkg`` will be "2"

This way a priority can be defined, but still the end user always keep full control.

You can also set ``default_options`` values in the ``init()`` method, which can initialize directly ``options`` and ``default_options`` from data captured in recipe files (like in ``conandata.yml`` for example, or your json file).

If you want to do it in ``configure()`` method, the only limitation is that Python syntax doesn't support the "!" in identifiers, so the generic ``setattr`` is needed, so this works:
```python
def configure(self):
      setattr(self.options["*"], "myoption!", 2)
```

Please give it a try and let me know.

**Comment by Jannis1994** [comment]
Hello @memsharded 
Thank you very much.
I gave it a try and it is working fine.

```python
def configure(self):
        setattr(self.options["baseimage"], "corbos_adg_compatibility!", "50.7.1")  

```

I will close this thread now.

Best regards,
Jannis

**Comment by memsharded** [comment]
Happy to know that it is working, and happy to help!
