### ISSUE TITLE
[bug] Regression - the workspace feature broke api editable support

### ISSUE THREAD

**Issue by fredizzimo** [conan-io/conan#17484]
### Describe the bug

https://github.com/conan-io/conan/pull/17272 added initial workspace support, but that broke the undocumented `local` api support for manipulating the editable packages, which we use in our own "workspace" implementation. Adding and removing packages have no effect when doing further commands like `load_graph`. Downgrading to version 2.9.3 fixes the issue.

The issue seems to be that `editable_add` operates on a list local to the function here, which is only updated in the local api constructor
https://github.com/conan-io/conan/blob/57af7593670d6a018a245fce2ceda6fba57f81e2/conan/api/subapi/local.py#L51-L65

But `ConanApp` passes the member variable list to the proxy here https://github.com/conan-io/conan/blob/57af7593670d6a018a245fce2ceda6fba57f81e2/conan/internal/conan_app.py#L57

The above was done in this commit https://github.com/memsharded/conan/commit/fe7ac0e9a8f57d2d6948318e078fb07bf3fe46e1

**Comment by memsharded** [comment]
Thanks for reporting @fredizzimo 

Yes, this is an overlook of the api usage, I am working on a fix.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/17498 has been merged, it will be released today in Conan 2.11
