### ISSUE TITLE
[question] package metadata and conan cache path 

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#17480]
### What is your question?

Dear Conan Folks,

We use conan-2.10.2 , with python 3.12.4 in Windows context.
I am upgrading from conan-2.0.11 to conan 2.10.2.
I am using the feature test reports as a part of meta data, however unit tests are done for only one variant.
Therefore the metadata is attached only for one variant.
In that case, is there a straight forward command to get the cache path of the package  that has the metadata folder ?
At the moment I do run a conan download packagename/version -r remote -m "*" -f json But then the resulting json says nothing about the metadata folder. I need to traverse through the json output and query with conan cache path if there is no metadata folder it throws an error :Metadata folder doesnot exist and I need to skip that.
 Would be nice to have a single command or atleast some information about the metadata in the json generated by the download command.

Please let me know if I have any wrong assumptions here.

Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

Thanks for your question, couple of quick questions.

> At the moment I do run a conan download packagename/version -r remote -m "*" -f json 

Is this missing the ``--metadata`` argument?

> I am using the feature test reports as a part of meta data, however unit tests are done for only one variant.
Therefore the metadata is attached only for one variant.

But you know the variant, don't you? You can use that setting/option/profile, for a ``conan list -fp -fs -fo`` then use that package list as an argument for the ``conan download``?

**Comment by maitrey** [comment]
> Hi @maitrey
> 
> Thanks for your question, couple of quick questions.
> 
> > At the moment I do run a conan download packagename/version -r remote -m "*" -f json
> 
> Is this missing the `--metadata` argument?
> 
> > I am using the feature test reports as a part of meta data, however unit tests are done for only one variant.
> > Therefore the metadata is attached only for one variant.
> 
> But you know the variant, don't you? You can use that setting/option/profile, for a `conan list -fp -fs -fo` then use that package list as an argument for the `conan download`?

Isnot this same as -m?
-m METADATA, --metadata METADATA
                        Download the metadata matching the pattern, even if
                        the package is already in the cache and not downloaded

Yes I do know which variant is being used for testing . And conan list packagename/version:* -fp variantname does help. Many thanks!

**Comment by memsharded** [comment]
> -m METADATA, --metadata METADATA

Oh, yes, sorry, my mistake. I forgot the shortcut, and I was thinking only about ``--metadata``, you are right.

> Yes I do know which variant is being used for testing . And conan list packagename/version:* -fp variantname does help. Many thanks!

Excellent, happy to hear that this worked? Then, can we close the ticket as solved? Thanks for the feedback!

**Comment by maitrey** [comment]
Yes issue can be closed, many thanks
