### ISSUE TITLE
conan create - error 'options.myoption' doesn't exist.   Possible options are []

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1748]
I believe there's a bug when using `conan create` command when both the following circumstances exist: 
1.  A `test_package` folder exists
2.  A custom option was passed to `conan create` with `-o`

I believe the problems is that the `package` options are effectively passed to `test_package` verbatim, as if they belong to `test_package` when they don't.  

In the source code, it looks like the options are put into a profile object: 
https://github.com/conan-io/conan/blob/949cdec3ce01382306e12b62086740fe04490ddb/conans/client/conan_api.py#L293

Which is later passed to the test package install step: 
https://github.com/conan-io/conan/blob/949cdec3ce01382306e12b62086740fe04490ddb/conans/client/conan_api.py#L324-L334

I'm not sure how the problem exactly occurs after that, but I think this should be enough info.

**Comment by solvingj** [comment]
To note, if I copy the options from the main package recipe to the test package recipe, it works, even though the options do nothing.

**Comment by memsharded** [comment]
Options are passed to the specified package, unless they are to be applied to the current conanfile in user space, which might not have a package name at all. So if you are creating a package ``Pkg/0.1@user/channel``:

```bash
$ conan create Pkg/0.1@user/channel -o Pkg:option_pkg=value -o test_package_option=value
```

Please try that and tell me. Also, a small reproducible example (as a github repo or zip file) always help a lot. Thanks!

**Comment by solvingj** [comment]
I'm confused by the suggestion.  I don't think I should have to prefix with the option with `Pkg` do I?  (Or are you saying maybe it is indeed a bug and this might be a workaround?)

Here are the two scenarios you allude to:

`conan create Pkg/0.1@user/channel`
and
`conan create user/channel` (in directory where `Pkg/0.1` conanfile.py exists)

In either scenario, passing the option without a package qualifier should have the same effect.

For example:  `-o option_pkg=value`

The effect should be that the option should be passed only to `Pkg` (and only to `Pkg`), but now it's going to `test_pkg` as well.

No option should be passed to `test_pkg` unless I specify `-o test_pkg:option=value`. 

Isn't this correct?

**Comment by memsharded** [comment]
options for a named package should always be preceded with the package name, like ``-o Pkg:option=value``. 

Just in some cases, as in test_package, in which the conanfile.py **has no package name nor version**, it is impossible to use a package name to define its option, so no possible ``test_pkg``. It is not a package it is just a conanfile. For that case you can try the options without the package scope, like ``-o option=value``

**Comment by solvingj** [comment]
So, you say `should` but the options work without prefix during the `conan create` command unless there's a test_package.  The test_package existing, and picking up all un-prefixed options is what forces the prefix on `conan create`  .  I'll start prefixing on `conan create` to get around the test, but it feels like a workaround.

**Comment by memsharded** [comment]
Yes, I said ``should``, because the un-prefixed syntax still works in some cases because of legacy, we will eventually deprecate it.  So it is not a workaround, it is exactly the solution to your issues, as it is not clear to whom the options have to be applied, much better to make them explicit whenever possible.
