### ISSUE TITLE
[question] How to create own ConanCenter binaries?

### ISSUE THREAD

**Issue by ottmar-zittlau** [conan-io/conan#17489]
### What is your question?

Hi,

I'm trying to follow the steps to create and host own ConanCenter binaries (as described here: https://docs.conan.io/2/devops/conancenter/hosting_binaries.html#devops-conancenter-hosting-your-own-conancenter-fork)

I'm running a local artifactory, which I can reach at `localhost:8081`. I successfully added it to my conan remotes:

```
$ conan remote list
conancenter: https://center2.conan.io [Verify SSL: True, Enabled: True]
artifactory: http://localhost:8081/artifactory/api/conan/conan-local [Verify SSL: True, Enabled: True]
```

I then cloned the conan-center-index and tried to build a specific version of zeromq by running
```
$ conan create recipes/zeromq/all/ --version 4.3.5
```
This seems to work.
Then I try to upload the package, which unfortunately fails:
```
$ conan upload zeromq --remote artifactory
Found 1 pkg/version recipes matching zeromq in local cache

======== Uploading to remote artifactory ========

-------- Checking server existing packages --------
zeromq/4.3.5: Checking which revisions exist in the remote server

-------- Preparing artifacts for upload --------
zeromq/4.3.5:c1fa0fc995b1127a227b1386056bbd682d72f233: Compressing conan_package.tgz

-------- Uploading artifacts --------
zeromq/4.3.5: Uploading recipe 'zeromq/4.3.5#5427a66b8409515a740953aba13394be' (10.6KB)
WARN: network: 404 Client Error:  for url: http://localhost:8081/artifactory/api/conan/conan-local/v2/conans/zeromq/4.3.5/_/_/revisions/5427a66b8409515a740953aba13394be/files/conan_export.tgz
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conan_export.tgz, '404 Client Error:  for url: http://localhost:8081/artifactory/api/conan/conan-local/v2/conans/zeromq/4.3.5/_/_/revisions/5427a66b8409515a740953aba13394be/files/conan_export.tgz'
WARN: network: 404 Client Error:  for url: http://localhost:8081/artifactory/api/conan/conan-local/v2/conans/zeromq/4.3.5/_/_/revisions/5427a66b8409515a740953aba13394be/files/conan_sources.tgz
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conan_sources.tgz, '404 Client Error:  for url: http://localhost:8081/artifactory/api/conan/conan-local/v2/conans/zeromq/4.3.5/_/_/revisions/5427a66b8409515a740953aba13394be/files/conan_sources.tgz'
WARN: network: 404 Client Error:  for url: http://localhost:8081/artifactory/api/conan/conan-local/v2/conans/zeromq/4.3.5/_/_/revisions/5427a66b8409515a740953aba13394be/files/conanfile.py
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conanfile.py, '404 Client Error:  for url: http://localhost:8081/artifactory/api/conan/conan-local/v2/conans/zeromq/4.3.5/_/_/revisions/5427a66b8409515a740953aba13394be/files/conanfile.py'
WARN: network: 404 Client Error:  for url: http://localhost:8081/artifactory/api/conan/conan-local/v2/conans/zeromq/4.3.5/_/_/revisions/5427a66b8409515a740953aba13394be/files/conanmanifest.txt
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conanmanifest.txt, '404 Client Error:  for url: http://localhost:8081/artifactory/api/conan/conan-local/v2/conans/zeromq/4.3.5/_/_/revisions/5427a66b8409515a740953aba13394be/files/conanmanifest.txt'
ERROR: Execute upload again to retry upload the failed files: conan_export.tgz, conan_sources.tgz, conanfile.py, conanmanifest.txt. [Remote: artifactory]

```

What could I do?

Thanks and best regards
oz

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ottmar-zittlau 

Thanks for your question.
It seems it could be an authentication issue. How are you logging-in  or entering the Artifactory credentials?

In some cases a server will return 404 for resources if not properly authenticated, to avoid disclosing the existence or not of certain resources, this could be a reason of those 404.

Can you try other commands like ``conan list "*" -r=artifactory`` and report what happens?

**Comment by ottmar-zittlau** [comment]
Hi @memshared, thanks again for the quick reply.

The first time I ran the list command it asked for my credentials:
```
$ conan list "*" -r=artifactory
Remote 'artifactory' needs authentication, obtaining credentials
Remote 'artifactory' username: admin
Please enter a password for user 'admin' on remote 'artifactory': 
artifactory
  ERROR: 404: Repo 'conan-local' was not found. [Remote: artifactory]
```
This error message explained the issue - I didn't setup a remote repository (as described here: https://docs.conan.io/2/tutorial/conan_repositories/setting_up_conan_remotes/artifactory/artifactory_ce_cpp.html)


Some additional questions:
1. The documentation for self-hosting recommends to first run `conan export` and then `conan create` -  what do I need the export command for?
2. I was wondering how dependencies are uploaded. So I tried building grpc. I found a way to extract dependencies here: https://docs.conan.io/2/examples/commands/pkglists.html#building-and-uploading-packages

This is what I ended up with:
```
conan create recipes/grpc/all/ --version 1.67.1 --build=missing --format=json > grpc.json
conan list --graph=grpc.json --graph-binaries=build --format=json > pkglist.json
conan upload --list=pkglist.json -r=artifactory -c
```
However, this only uploads grpc. Inspecting pkglist.json reveals two categories of packages, one "Local Cache" and one "conancenter". It seems as if only the "Local Cache" packages are uploaded. If I force building all dependencies locally by running `conan create` with `--build="*"` then everything works. However, I think that this is the wrong approach, because if execute above steps for multiple packages this would unnecessarily build packages.

Also I don't know how I can force conan to only use recipes from my cloned conan-center-index. To enforce this, I removed
conancenter from my list of remotes (`conan remote remove conancenter`). Now everything fails, e.g. if I run
```
conan create recipes/grpc/all/ --version 1.67.1 --build=missing --format=json > grpc.json
```
I get the error message:
```
======== Computing dependency graph ========
protobuf/5.27.0: Not found in local cache, looking in remotes...
protobuf/5.27.0: Checking remote: artifactory
Graph root
    cli
Requirements
    grpc/1.67.1#00b9878c6eb6d5824c88f9c3dbf4c8c9 - Cache
ERROR: Package 'protobuf/5.27.0' not resolved: Unable to find 'protobuf/5.27.0' in remotes.
```
I do understand this, but how can I solve this?
Do I have to export the recipes (or create the packages) of all dependencies of my package. Is there a way to automate this, or do I have to figure this out manually?

**Comment by memsharded** [comment]
> The documentation for self-hosting recommends to first run conan export and then conan create - what do I need the export command for?

The ``conan export`` doesn't read dependencies, it is a very fast operation that just copies the ``conanfile.py`` and associated files into the Conan cache to make them available for usage. So all different recipes that you need can be ``conan export`` in any order. 

Then the ``conan create`` is the one actually building the packages. They need the dependencies to be built, so if the dependencies from ConanCenter hasn't been ``exported`` to the cache yet, it will fail. But ``conan export`` does not build the package binaries, ``conan create`` or ``conan install --requires=mypkg/version --build=mypkg/version`` is needed to actually build the package.

To automate the ``conan export`` task, and avoiding it, using the ``local-recipes-index`` feature as described in https://docs.conan.io/2/devops/devops_local_recipes_index.html is doable. Packages still need to be built and uploaded to Artifactory, but it can be convenient as a mechanism to build packages from a conan-center-index fork.

> However, this only uploads grpc. Inspecting pkglist.json reveals two categories of packages, one "Local Cache" and one "conancenter". It seems as if only the "Local Cache" packages are uploaded. If I force building all dependencies locally by running conan create with --build="*" then everything works. However, I think that this is the wrong approach, because if execute above steps for multiple packages this would unnecessarily build packages.

Yes, you don't want to unnecessarily build packages.
If what you want is to upload both "built" packages, but also other dependencies, that is what can be defined with the ``conan list --graph-binaries`` argument. AT the moment using ``--graph-binaries=build`` only uploads build packages, but you can select to upload also other not-built packages too.

> Also I don't know how I can force conan to only use recipes from my cloned conan-center-index. To enforce this, I removed
conancenter from my list of remotes (conan remote remove conancenter). Now everything fails, e.g. if I run

Removing ``conancenter`` from the remotes is indeed the recommended approach. But you need to one of these two things:

- pre ``conan export`` all the different recipes and dependencies you need. Typically creating a script that iterates all of them and runs ``conan export`` for each one, including in this case ``'protobuf/5.27.0`` and any other transitive dependencies
- Use the ``local-recipes-index`` approach to automatically ``conan export`` what is needed from the fork.

In either case, the ``--build=missing`` argument is necessary

**Comment by ottmar-zittlau** [comment]
Thanks again for the exhaustive reply.

I've now put everything together in a python script.
First, I export each recipe for all available versions.
Then, I create and upload each package.

The step that exports all recipes does take quite some type.
Would it be safe to parallelize this? I would like to handle each recipe in a separate thread.

I reckon parallelization wouldn't be recommended for the package creation step.

Are there any conan functions that simplify the usage of the config.ymls?

Here's the script:
```
#!/usr/bin/env python3

import subprocess
from pathlib import Path
import yaml

remote_name = "artifactory"
recipes_folder = Path(__file__).resolve().parent / "recipes"

# Export all recipes so that create can find them      
for recipe_path in recipes_folder.glob('*'):
    print(recipe_path)
    config_file = recipe_path / "config.yml"
    config_data = yaml.safe_load(config_file.read_text())

    for version, version_config in config_data["versions"].items():
        conan_file_path = recipe_path / version_config["folder"]
        subprocess.run(["conan", "export", conan_file_path, "--version", version])

# List of required packages
packages = [("grpc", "1.67.1")]

# Build and upload each required package and its dependencies
for package_name, version in packages:
    recipe_path = recipes_folder / package_name
    config_file = recipe_path / "config.yml"
    config_data = yaml.safe_load(config_file.read_text())

    if not version in config_data["versions"]:
        raise Exception(f"Can't find receipe for version {version} of package {package_name}.")
    
    conan_file_path = recipe_path / config_data["versions"][version]["folder"]

    result_file_name = "result.json"
    with open(result_file_name, "w") as result_file:
        subprocess.run(["conan", "create", conan_file_path, "--version", version, "--build", "missing", "--format", "json"], stdout=result_file)
    
    package_file_name = "package_list.json"
    with open(package_file_name, "w") as package_file:
        subprocess.run(["conan", "list", "--graph", result_file_name, "--graph-recipes", """*""", "--format", "json"], stdout=package_file)
    
    subprocess.run(["conan", "upload", "--list", package_file_name, "-r", remote_name, "-c"])
```

**Comment by memsharded** [comment]
> The step that exports all recipes does take quite some type.
Would it be safe to parallelize this? I would like to handle each recipe in a separate thread.

It would be much faster, no need parallelization if using the PythonAPI.
Actually, using a Conan custom command, would probably be the cleanest and best approach: Conan custom commands are easy to maintain, document, and share via ``conan config install/install-pkg``. Using the ``ExportAPI`` from a custom command will iterate much much faster than calling ``subprocess.run()`` to call ``conan export``.
I'd recommend having a look to: https://docs.conan.io/2/reference/extensions/custom_commands.html

Also, you don't want/need to ``conan export`` the whole ``conan-center-index`` repo, just the recipes that you need. So using a list defined before, and iterating the list instead of all the ``recipes`` folder, would be way more efficient. (this is what can be avoided using the ``local-recipes-index`` feature)

We are still documenting the ConanAPI, but you can use the source code implementation of the current commands to get inspiration and learn about the API.

**Comment by ottmar-zittlau** [comment]
Ok, sorry - I thought the local-conan-center-index-feature was an alternative to the artifactory.

This seems to be exactly, what I need. What I would do now:
1. Remove the real conan center from list of remotes
2. Add my local copy of the conan-center-index as remote
3. Iterate through all packages that I need and execute the steps as outlined above (create -> list -> upload)

Do I miss something - this somehow seems to be too easy?

Concerning the custom command: 
I could create a command that exports multiple packages by using the decorator, create an instance of ExportAPI (cf. https://github.com/conan-io/conan/blob/5fbf896376b71d6829176a98b574cf746ff33e6b/conan/api/subapi/export.py#L13) and replace my subprocess-calls with the appropriate methods of this class? I don't think that this is necessary anymore, but maybe this could be handy in other contexts.

**Comment by memsharded** [comment]
> Ok, sorry - I thought the local-conan-center-index-feature was an alternative to the artifactory.

No, it is an alternative to have to manually ``conan export`` and ``conan create`` packages from a ``conan-center-index`` fork, but those packages still need to be uploaded to a real server repository. It is a "source" approach, not a "package" approach. This would be better explained in this section: https://docs.conan.io/2/devops/devops_local_recipes_index.html#using-local-recipes-index-repositories-in-production

> Do I miss something - this somehow seems to be too easy?

No, that is basically it, please give it a try and let us know (If the current question is solved, it can be closed, then you can open new tickets for any specific issue using the local-recipes-index feature)

> I could create a command that exports multiple packages by using the decorator, create an instance of ExportAPI (cf.

No, this is not necessary if using the ``local-recipes-index`` feature, because Conan will be exporting automatically.

But yes, the custom commands are super-useful in many situations. Even for the current use case, and you don't need to export, you can do a custom command that:

- Define the list of packages to be used (or read that list from a json/yaml/text files)
- Using the API, iterate the list, calling ``conan install --requires=<pkg> --build:missing=<pkg>`` (note the ``missing`` here to avoid rebuilding when not necessary because you have an already existing binary)
- Do a ``conan upload`` to the remote of your choice (for example the remote can be an argument to the command, to make it more flexible).

Then, just call it: ``conan myorg:build_mycenter_fork -r=myremote`` or something like that.

**Comment by ottmar-zittlau** [comment]
Yes, I managed to get this to work - it's an incredible solution.
I added two indices, so that I can easily add own packages or override packages from the conan-center-index, without too much git fiddling.

I add my script here - maybe someone could reuse it:
```
#!/usr/bin/env python3

import subprocess
from pathlib import Path
import yaml

def find_recipe(package_name : str, indices : list[tuple[str, Path]]) -> Path:
    for _, index_folder in indices:
        recipes_folder = index_folder / "recipes"
        recipe_path = recipes_folder / package_name

        if recipe_path.exists():
            return recipe_path
    
    raise Exception(f"Can't find recipe for package {package_name} (not found at {recipe_path})")

remote_name = "artifactory"

script_folder = Path(__file__).resolve().parent

# It's important that the own index comes first here, so that it's recipes are found first.
# This allows to override conan-center recipes.
local_indices = [("own-index", script_folder / "own-index"), ("local-conan-index", script_folder / "conan-center-index")]

for index_name, index_folder in local_indices:
    subprocess.run(["conan", "remote", "add", index_name, index_folder])

# File containing the list of required packages
desired_packages_file = script_folder / "packages.yaml"

# Build and upload each required package and its dependencies

for package in yaml.safe_load(desired_packages_file.read_text()):
    package_name = str(package["package"])
    version = package["version"]
    
    recipe_path = find_recipe(package_name, local_indices)

    config_file = recipe_path / "config.yml"
    config_data = yaml.safe_load(config_file.read_text())

    if not version in config_data["versions"]:
        raise Exception(f"Can't find recipe for version {version} of package {package_name}.")
    
    conan_file_path = recipe_path / config_data["versions"][version]["folder"]

    result_file_name = "result.json"
    with open(result_file_name, "w") as result_file:
        subprocess.run(["conan", "create", conan_file_path, "--version", version, "--build", "missing", "--format", "json"], stdout=result_file, check=True)
    
    package_file_name = "package_list.json"
    with open(package_file_name, "w") as package_file:
        subprocess.run(["conan", "list", "--graph", result_file_name, "--graph-recipes", """*""", "--format", "json"], stdout=package_file, check=True)
    
    subprocess.run(["conan", "upload", "--list", package_file_name, "--remote", remote_name, "-c"], check=True)
```

The yaml containing the desired packages has the structure:
```
- package: eigen
  version: 3.4.0
- package: openssl
  version: 1.1.1w
```

Thanks for your help!

**Comment by memsharded** [comment]
You are welcome.

Still, your script can be further reduced and optimized. For example:
```python
    recipe_path = find_recipe(package_name, local_indices)

    config_file = recipe_path / "config.yml"
    config_data = yaml.safe_load(config_file.read_text())

    if not version in config_data["versions"]:
        raise Exception(f"Can't find recipe for version {version} of package {package_name}.")
    
    conan_file_path = recipe_path / config_data["versions"][version]["folder"]

    result_file_name = "result.json"
    with open(result_file_name, "w") as result_file:
        subprocess.run(["conan", "create", conan_file_path, "--version", version, "--build", "missing", "--format", "json"], stdout=result_file, check=True)
```

Can be reduced to something like (not tested):
```python
    result_file_name = "result.json"
    with open(result_file_name, "w") as result_file:
        subprocess.run(["conan", "install", "--requires", package,  "--build", f"missing:{package}", "--format", "json"], 
```

Because you no longer need to do the ``create``, if defining the git repos as remotes.

**Comment by ottmar-zittlau** [comment]
I added your suggestion to my script - it's much nicer now.

But with this solution I have to be careful with the order of my remotes, right?
I would expect, that I need to put them in the following order:
1. my own index - needs to come first in order to be able to overwrite recipes from conan-center
2. the conan center index - needs to come before the remote repository, so that updates to it actually have an effect. Otherwise, I would expect that conan takes the recipe from my remote repository.
3. my remote repository - required so that conan can download unchanged packages

```
#!/usr/bin/env python3

import subprocess
from pathlib import Path

remote_name = "artifactory"

script_folder = Path(__file__).resolve().parent

# Here it's important that the own index comes first, so that its recipes are found first.
# This allows to override conan-center recipes.
local_indices = [("own-index", script_folder / "own-index"), ("local-conan-index", script_folder / "conan-center-index")]

for i, (index_name, index_folder) in enumerate(local_indices):
    subprocess.run(["conan", "remote", "add", "--index", str(i), index_name, index_folder])

# File containing the list of required packages
desired_packages_file = script_folder / "packages.txt"

# Build and upload each required package and its dependencies
with open(desired_packages_file, "r") as desired_packages:
    for package in desired_packages:
        package = package.lstrip().rstrip()

        result_file_name = "result.json"
        with open(result_file_name, "w") as result_file:
            subprocess.run(["conan", "install", "--requires", package, "--build", "missing", "--format", "json"], stdout=result_file, check=True)

        package_file_name = "package_list.json"
        with open(package_file_name, "w") as package_file:
            subprocess.run(["conan", "list", "--graph", result_file_name, "--graph-binaries", "build", "--format", "json"], stdout=package_file, check=True)
        
        subprocess.run(["conan", "upload", "--list", package_file_name, "--remote", remote_name, "-c"], check=True)
```

**Comment by memsharded** [comment]
> But with this solution I have to be careful with the order of my remotes, right?
I would expect, that I need to put them in the following order:

> my own index - needs to come first in order to be able to overwrite recipes from conan-center
the conan center index - needs to come before the remote repository, so that updates to it actually have an effect. Otherwise, I would expect that conan takes the recipe from my remote repository.
my remote repository - required so that conan can download unchanged packages

Yes, that is correct, the order of remotes is important. 
There is also a feature called ``--allowed-packages``, which is a filter that allows defining which packages comes from what remotes, that accept patterns too. This can help a bit to enforce some extra checks on origin of packages.

Is your index very different from ConanCenter? Does it contain the same package recipes like duplicated ``zlib``? If the package names are different, then the order is not an issue at all, it only matters if the package name is the same. If the package name is the same, we have seen typically users doing modifications on the fork, so instead of having a ``zlib`` in another index, they do modifications to the existing ``zlib`` in the ``conan-center-index`` fork. This helps to keep latest changes, new versions, etc, synchronized from upstream, using git pull/merge, etc.

**Comment by ottmar-zittlau** [comment]
We only have one package (libssh) with custom changes (adding a recent version). I came across the approach with the own local index, while fiddling around with it. I read in your documentation that forking is the suggested way, but I was a bit reluctant to use it. Ideally, I wouldn't want to have locally tweaked packages at all and I wanted to make it as clear as possible that certain packages are manipulated. But that's just personal preference...

Thanks again for all your assistance!
