### ISSUE TITLE
[question] How to manage sources in Conan 2 similar to the scm attribute in Conan 1

### ISSUE THREAD

**Issue by aander80** [conan-io/conan#17510]
### What is your question?

Hello!

One issue I have encountered in Conan 2 is the ability to both export sources from a local path to the conan cache when building with `conan create`, and downloading sources when building via e.g. `--build=missing`. In Conan 1, we could copy the sources into the `scm_source` folder in the Conan cache when the `scm` attribute was specified, but we do not have that in Conan 2. This seems inefficient, since we have to clone the repo (which contains `conanfile.py` to export the recipe into the cache anyway; downloading it from `origin` again when building from source can add unnecessary time if the repo is large. Additionally, when using Zuul as a CI system it will not work since the CI nodes are not cloning the repos themselves, but rather have the repos pushed to them (you can read more about the Ansible role that does this [here](https://opendev.org/zuul/zuul-jobs/src/branch/master/roles/prepare-workspace-git)).

I have set up a demo in Docker showcasing how this behavior will fail in Zuul because we cannot clone the repos from `origin` when running `conan create`: https://github.com/aander80/zuul-conan2-scm. There are far more details in `README.md` in that repo, but the issue is in short that we cannot clone the sources from `origin` but need to have them locally in Zuul, but also want to *be able* to clone the sources from `origin` if building with e.g. `--build=missing`. I will copy the two alternatives that I see here:

1.  Add an opt-in feature in Conan that allows us to copy the local repo into the Conan cache *consistently* and not rely on cloning the repo inside of the Conan cache, which doesn't work for us in Zuul and is inefficient since we need to have the repo locally to export the recipe into the cache before building with `conan create` (which would download the repo again from `origin`). I imagine this would either be something specified in the `conanfile.py`, or in the CLI command such as `conan create . --export-sources/--export-scm(-sources)`.

2.  Not use `conan create` and build with `conan build` and `conan export-pkg` instead. In that case, we could just capture the URL and revision and add that to `conandata.yml` unconditionally when exporting to the cache. However, since we are not building inside of the cache it is much harder to ensure reproducability, making it harder to switch CI systems seamlessly or for developers to build a package locally with a new profile or new dependencies.

Do you have any suggestions for how to solve this issue? Am I missing something obvious here?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aander80 

Thanks for your question.

To see if I understood correctly the issue, let me know if this is something that could make sense or implement the behavior you expect:

- Have the ``export()`` method to collect and store in the ``conandata.yml``, in case the commit doesn't exist in the server (can be checked with the ``Git`` helper), the current ``recipe_folder`` in a new entry in conandata.yml
- Have the ``source()`` method do first a check of the existence of the ``recipe_folder`` information in the ``conandata.yml``. If it exists, then copy things from that location into the cache, but not do the cloning.
- Regular operation with cloning can still happen if desired in other places, like developer machines, for example, or other non-constrained environments.

If this makes sense, I'd say it is a reasonable implementation of the behavior, and it should be relatively straightforward. Please let me know what you think.

**Comment by aander80** [comment]
Thanks for your suggestion!

I have tried some things locally, and I guess you can divide this problem into two categories:

* `revision_mode = "hash"`: Here we cannot use your suggestion, I believe. If we are to build on Linux and Windows concurrently (or just two different machines, really), we will have a race condition when the contents of `conandata.yml` will be different in the two different builds. The different package IDs would end up under two different recipe revisions so we would later on only be able to find one of them. However, for cases when you do have `conanfile.py` together with the sources, perhaps the best approach is to use `revision_mode = "scm"` anyway?

* `revision_mode = "scm"`. Here it appears it works in Conan 2. I tried it locally and the second time around the recipe would not be uploaded (since the recipe revision is the same) and both packages would end up under the same revision in the remote. I had actually thought of your suggestion previously but discarded it since we have seen issues when doing similar things in Conan 1 with the `--no-overwrite` flag in `conan upload`. However, I cannot see a similar argument in Conan 2, if I am not mistaken? I guess this would work for us, although this seems more of a hack since the recipe would technically be different for each concurrent build of the same version. Is your opinion that this is still a decent solution?

**Comment by memsharded** [comment]
That is a very good point, yes, sorry that it was not in my proposal above.

Indeed, this only works for ``scm`` approach, as otherwise the revision is conditioned to the different path in the different machines.

I agree that it is not great that the recipe is different if it builds in different places. Then the possible solution, and it might be possible to keep the ``hash`` mode, would be to send the ``recipe_folder`` information to somewhere else. This might be a case for the ``recipe metadata files``. This might have some advantages:

- Do not affect the recipe revision
- Can be kept local, you can always remove the metadata before uploading it if you want.
- It can be implemented with hooks, without needing to modify the ``export()`` method, like using the ``post_export`` hook. That way it is not necessary to add things to the recipe, keeping it reduced. This would make sense if this is only used in CI, so you put the hooks in your CI systems, but as developers don't have those hooks, they will run normally.
- The ``source()`` method would still need an ``if`` somewhere, but if the source is copied from the ``recipe_folder`` in the ``pre_source()`` hook, then the changes in the recipe could be minimal

**Comment by aander80** [comment]
Thanks for the suggestion with recipe metadata files, that seems like a decent solution to this problem! I tried with some hacky code (that should be cleaned up!):

```python
@property
def _local_repo_file(self) -> Path:
    return Path(self.recipe_metadata_folder, "local_repo_path.txt")

def export(self):
    git = Git(self, self.recipe_folder)
    commit = git.get_commit()
    update_conandata(self, data={"scm": {"commit": commit, "url": "ssh://example.com/my-repo"}})
    with self._local_repo_file.open("w") as f:
        f.write(git.get_repo_root())

def source(self):
    git = Git(self)
    scm = self.conan_data["scm"]
    if self._local_repo_file.exists():
        with self._local_repo_file.open() as f:
            local_repo_root = f.read().strip()
        git.clone(url=local_repo_root, target=".")
    else:
        git.clone(url=scm["url"], target=".")
    git.checkout(commit=scm["commit"])
```

I will have to dig deeper into how we want to remove `local_repo_path.txt` to avoid uploading it along with the rest of the metadata, but for now I believe this will solve the problem with local and remote sources. I will close this issue and re-open if needed!

Merry christmas and a happy new year! 😄

**Comment by memsharded** [comment]
Excellent! Happy that it worked and very happy to help, thanks for the feedback.

Happy Christmas and happy 2025 too! 😄
