### ISSUE TITLE
[question] Get path of required component in conanfile.py

### ISSUE THREAD

**Issue by nkindt** [conan-io/conan#17527]
### What is your question?

I need to get the path of a tool that is required and pulled + compiled successfully to forward it to another project so both versions match. I.e. i have this in requirements():
`self.requires('protobuf/3.21.12)`
and would like to get the actual path in cache afterwards.

The background is that multiple projects require protobuf and each project does it's own search which might conflict after different versions are picked up (i.e. incompatible system protobuf instead the one needed). I would like to get it once from remote, retrieve the path in cache after it's installed and forward it to other instances so they will look and find this particular version there.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @nkindt,

I'm not sure if I understood what you're trying to do but I guess that you are interested in the `self.dependencies` attribute (docs [here](https://docs.conan.io/2/reference/conanfile/methods/generate.html#self-dependencies)). Then, you could use something like this:

```python
class Pkg(ConanFile):
    requires = "protobuf/3.21.12"
   
    # ...

    def generate(self):
        protobuf_package_folder = self.dependencies["protobuf"].package_folder
```

**Comment by valgur** [comment]
> The background is that multiple projects require protobuf and each project does it's own search which might conflict after different versions are picked up (i.e. incompatible system protobuf instead the one needed). I would like to get it once from remote, retrieve the path in cache after it's installed and forward it to other instances so they will look and find this particular version there.

That sounds a bit like you might be missing a
```python
def build_requirements(self):
    self.tool_requires("protobuf/<host_version>")
```
in the downstream packages.

**Comment by franramirez688** [comment]
@valgur excellent point! Thanks a lot!

For the record, this is the [documentation link](https://docs.conan.io/2/reference/conanfile/methods/build_requirements.html#host-version) about that `host_version` mechanism.

**Comment by nkindt** [comment]
Thanks a bunch! Will be checking this ... I am closing this for now since the question on how to get the path is what i was looking for.
