### ISSUE TITLE
[question] LNK 2001: _guard_check_icall_$fo$

### ISSUE THREAD

**Issue by crystalsky** [conan-io/conan#17529]
### What is your question?

conan pacakge build on Linux is Ok. But In Windows With VisualStduio2017 Compile Error.
cmd: conan create automake. 
Error:
test_package_1.c
libucrt.lib(checkcfg.ob): error LNK2001: undefine symbol _guard_check_icall_$fo$

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by crystalsky** [comment]
and other package has same error on LNK2001. How Can I solve this with profile setting？？？？

**Comment by franramirez688** [comment]
Hi @crystalsky 

It seems that it's not a Conan-related problem but a VS SDK one:

* https://forum.gamemaker.io/index.php?threads/solution-yyc-build-linker-error-unresolved-external-symbol-_guard_check_icall_-fo.115387/
* https://github.com/pocoproject/poco/issues/4606
* https://developercommunity.visualstudio.com/t/unresolved-external-symbol-_guard_check_/10683636?sort=newest

So you'll have to update your Visual Studio SDK version to fix this issue.
Closing as solved but do not hesitate to reopen or ask any other doubt. Thanks!
