### ISSUE TITLE
[bug] replace_in_file has inconsistent return value

### ISSUE THREAD

**Issue by mrbean-bremen** [conan-io/conan#17530]
### Describe the bug

Not really a bug, but a minor inconsistence: `files.replace_in_file` in non-strict mode return `False` if the pattern was not found, but nothing (e.g. `None`) if it was found and replaced. Noticed this because I wanted to check the return value.

Trivial change, will make a PR in a minute.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/17531 for next Conan 2.12, thanks for your report and your PR to fix it

**Comment by mrbean-bremen** [comment]
Thanks for maintaining that awesome project!
