### ISSUE TITLE
progress during source copying

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#1755]
Is it possible to get a feedback of the progress during the step "Copying sources to build folder" of the "create" command ?
In the case of the Qt package, there are so many files that the copying takes several minutes, which makes the travis ci fail eg https://travis-ci.org/ericLemanissier/conan-qt/jobs/272938121

A workaround is probably to get archives in the source method, and unzip them in the build method, instead of the source method, but does that fit the conan way of doing things ?

**Comment by memsharded** [comment]
So the unzipping is running faster than the copy?

Are you aware of the ``no_copy_source`` attribute? http://conanio.readthedocs.io/en/latest/reference/conanfile/attributes.html?highlight=no_copy_source#no-copy-source

If the source code is not modified by the build, then you can totally skip the copy step.

**Comment by ericLemanissier** [comment]
I found no_copy_source attribute few minutes after posting. I am currently investigating it, Qt shadow build is not so straightforward...

**Comment by ericLemanissier** [comment]
I don't know about the relative speed of unzipping vs copy, but there are 14 archives so there is some feedback between each unzipping, contrary to the copy of the full sources in a single step

**Comment by memsharded** [comment]
Ok, please have a look to the ``no_copy_source`` and tell me.

Regarding the copy, there is little we can do to speed it up. The copy from sources from the "source" to the "build" folder is just a call to:

```python
shutil.copytree(src_folder, self.build_folder, symlinks=True, ignore=ignore)
```
So, actually, adding some progress bar, which is doable would actually slow-down the copy (the slow down can be noticeable, and we might introduce bugs while implementing our copytree). Not sure about what would be the best approach.

**Comment by ericLemanissier** [comment]
no_copy_source was definitely the way to go. thanks !
