### ISSUE TITLE
Commands returning data like --build_order sometimes get dirty output

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1757]
For example using version ranges:

$ `conan info --build_order sdplog`

Version range '>=4.0' required by 'None' resolved to 'fmt/4.0.0@xylosper/stable'

That message dirts the output and can be processed by an script.
Same problem with the warn we wanted to introduce when conan sets the runtime of visual automatically, we decided to log it.

Maybe these commands should specify a file or something?: There is already a json option to file

**Comment by danimtb** [comment]
I think this was partially *workarounded* by #4359 as we now have the possibility of outputing a json file with the build order and avoid the stdout pollution. WDYT?

**Comment by lasote** [comment]
This is related to https://github.com/conan-io/conan/pull/4055 .
The issue is to allow print json to the stdout while the output is still filled with some other messages.
This is not very important I would say, I would prefer to remove the json to output in Conan 2.0 and assume that a regular command output is not suitable to be parsed. We can discuss in a whiteboard the following sessions if we want that behavior for Conan 2.0 or if we want the full-correct solution.

**Comment by solvingj** [comment]
Glad I read this latest comment regarding future plans. Was about to write a script which depends on the json output to stdout.  Is there a github issue open for any discussion about piping stdout to stdin between conan commands? There was an informal discussion in slack about it, and that would be an alternative to this kind of json parsing.

**Comment by lasote** [comment]
To refresh your use case, Jerry, the main one was the conan reference from a create => to the conan upload command, right?
I just thought, what a simple "conan_ref" generator (or something similar) that creates a file with the reference?  Might that be nicely used with `conan upload @conan_ref.txt ...` ?

**Comment by solvingj** [comment]
Yes, that was the case that has come up the most.

**Comment by memsharded** [comment]
The whole terminal output has been changed, decoupled stdout for values, stderr for any other message and formatters to generate json or other formats. Already available in 2.0-alpha
