### ISSUE TITLE
Add Git helpers

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1764]
Hi!

When I use `source` to get an external project, sometimes the projects does not contain any release, so as result is necessary apply `git clone`, and maybe `git checkout` to get such files.

Conan there are many useful helpers, but also would be nice support a helper for git.  There are some known python projects for that, as [GitPython](https://github.com/gitpython-developers/GitPython), but I think just a minimal support will be enough.

In many cases I use `self.run("git clone %s && cd %s && git checkout %s" % (repo, out, branch)`, but could be better:

```python
from conans import tools

class Foo(Conanfile):
...
    def source(self):
        git = tools.GitTool()
        git.clone(repo="https://github.com/foobar/couse", branch="1.0.0", dir="foobar-src")
```

Saludos!

**Comment by memsharded** [comment]
I am not so sure about this helper. If no proven extra complexity is being avoided, typically it is much better to deal with the direct git syntax that people already know than having to learn a new API for it. In your example, you did the task in oneliner, then you suggest an improvement in two lines.

The typical case, would be, ok, know I want to clone with ``--depth=1`` to be faster (my git history is heavy). In the first case, it is easy and direct to implement. In the second "helper" case, we wouldn't have provided the API for a ``depth`` parameter, then have to implement, test, release in next release... With an extra overhead. Also possibly introducing unwanted behavior, see the note in the docs  https://github.com/gitpython-developers/GitPython about Windows...

I need to see a clear advantage, a ``source()`` method that is becoming very repetitive with many lines of code, before adding this extra layer. Lets see what other say

**Comment by lasote** [comment]
Agree with @memsharded.

**Comment by uilianries** [comment]
I agree at this point, is more like a feature that increase a layer, but has few usage, it doesn't pay the price. So, is there some way to include as a plugin? The code could be included as a plugin, however, this plugin will be coupled to the project.

**Comment by memsharded** [comment]
You could try to create a python package with it and add it as ``build_requires`` to all.
Also, in next release we will be adding the ``conan config install`` that allows for easy redistribution of files for config, but it will also copy any file to the ``.conan`` folder. So maybe redistributing python files and adding the ``.conan`` folder to the PYTHONPATH might work.

In any case, at the moment, I wouldn't bother to have some repetition. Just add a function in your recipes. Copy & paste it. Updating your recipes in case of that function changes is easily done with search&replace, and in the worst case it will take you just a few minutes to do it manually. The "automated" path is not guaranteed to be easier or without issues that might cost more time.

**Comment by uilianries** [comment]
Agreed, I see less effort in create a simple method, the repetition is very small in such case.  I really appreciated your advice in this case.

Good to know about Conan config, this feature will help us in many situations. To export LDAP plugin, for example.

Regards.
