### ISSUE TITLE
After upgrading to 0.27.0, conan does not use System proxy configuration

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#1777]
Especially, conan does not use the Proxy Exceptions from windows. This just pulled our whole Jenkins system down.

**Comment by memsharded** [comment]
Sorry for that. We are right now documenting some changes, but indeed they should not put the system down.

We have added support for:

```
[proxies]
no_proxy=url1,url2
https=None
http=None
```

If you are not doing that, the behavior shouldn't have changed at all. Could you please send us some data, your ``[proxies]`` configuration, what error messages are you seeing in the traces, etc? We are looking to the code, but nothing evident yet.

**Comment by memsharded** [comment]
To make sure, previously you were using an empty ``proxies`` section, to indicate conan use the System proxy, right? And now it seems that with an empty ``proxies`` section, it is not using the System proxy anymore. Working on it.

**Comment by claasd** [comment]
Hi, 
I changed our scripts to use the conan version 0.26.1 instead of the newest one, thanks to Continuous Deployment this could be done in minutes after finding the problem.

The problem occurs on our Jenkins system. This system creates a new conan environment and fresh config files on each run. After using the new version, conan tried to download stuff from an IP address.

The ip range is in the proxy exceptions that you can configure in windows. Still, conan tried the proxy and got rejected.

Can I do any testing to help?

**Comment by memsharded** [comment]
> After using the new version, conan tried to download stuff from an IP address.
The ip range is in the proxy exceptions that you can configure in windows. Still, conan tried the proxy and got rejected.

Can you please clarify? What do you mean with "conan tried to download"? Like an unexpected download of other thing different to packages? How that download was triggered?

Do you use slack or hangouts? Please tell if you want to connect (for discussing this, or for other occasions)

**Comment by memsharded** [comment]
The culprit might be: https://github.com/conan-io/conan/pull/1370/files#diff-3a1be4ba164ce7bb3138841c78b2a305R273

```python
if not proxies:
      return urllib.getproxies()
```
this was raising an exception in Python 3 (you are using python 3 aren't you?), that was captured by the try-except silently, without doing anything at all. Now that it is supposed to be the correct behavior, it is not working anymore, as python ``urllib.requests.getproxies()`` seems not to honor the system proxies as it should.

Maybe just remove that line, I am checking.

**Comment by memsharded** [comment]
The related issue https://github.com/conan-io/conan/issues/1243 is very confusing then. If it was not using the conan configured proxies, it should have been using the system defaults automatically.

Would you be able to run patching the conan code:

```diff
diff --git a/conans/client/conf/__init__.py b/conans/client/conf/__init__.py
index c52a9ed..33cd71a 100644
--- a/conans/client/conf/__init__.py
+++ b/conans/client/conf/__init__.py
@@ -274,7 +274,7 @@ class ConanClientConfigParser(ConfigParser, object):
             proxies = self.get_conf("proxies")
             # If there is proxies section, but empty, it will try to use system proxy
             if not proxies:
-                return urllib.request.getproxies()
+                return None
             result = {k: (None if v == "None" else v) for k, v in proxies}
             return result
         except:
```

Also, are you doing ``tools.download()`` somewhere that might be affected by the proxy configuration? Could you please check it too?

**Comment by lasote** [comment]
@claasd maybe before you opened the #1243 you were using the **conan.conf** to configure the proxies and then you started to set the proxies at the system level to workaround it?

**Comment by claasd** [comment]
sorry for the confusion.
The problem does not occur in tools download. It occurs in a regular package Retrieval.
```
D:\slave\ws\cab\buildTools\bop-infra_tmp\feature-writeRevisionToDLL\bullseye.groovy@0\ws>conan remote remove conan-center 
WARN: Remotes registry file missing, creating default one in D:\slave\ws\cab\buildTools\bop-infra_tmp\feature-writeRevisionToDLL\bullseye.groovy@0\ws\.conan\registry.txt
D:\slave\ws\cab\buildTools\bop-infra_tmp\feature-writeRevisionToDLL\bullseye.groovy@0\ws>conan remote remove conan-transit 
D:\slave\ws\cab\buildTools\bop-infra_tmp\feature-writeRevisionToDLL\bullseye.groovy@0\ws>conan remote add cab http://191.0.0.17/artifactory/api/conan/cab-conan 
D:\slave\ws\cab\buildTools\bop-infra_tmp\feature-writeRevisionToDLL\bullseye.groovy@0\ws\src>conan info --only=None 
Auto detecting your dev setup to initialize the default profile (D:\slave\ws\cab\buildTools\bop-infra_tmp\feature-writeRevisionToDLL\bullseye.groovy@0\ws\.conan\profiles\default)
Found Visual Studio 10
Found Visual Studio 11
Found Visual Studio 12
Found Visual Studio 14
Default settings
	os=Windows
	arch=x86_64
	compiler=Visual Studio
	compiler.version=14
	build_type=Release
*** You can change them in D:\slave\ws\cab\buildTools\bop-infra_tmp\feature-writeRevisionToDLL\bullseye.groovy@0\ws\.conan\profiles\default ***
*** Or override with -s compiler='other' -s ...s***


BTC.CAB.Commons/1.8.latest@cab/stable: Not found in local cache, looking in remotes...
BTC.CAB.Commons/1.8.latest@cab/stable: Trying with 'cab'...
ERROR: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
// long HTML page from corporate proxy
```

the IP 191.0.0.17 is configured as proxy exception in windows:
![image](https://user-images.githubusercontent.com/2842916/30647692-6909263c-9e1c-11e7-9a18-e5b247058d94.png)

It would work if not proxy would be used; and it would work if the proxy and the proxy exceptions would be used. 

It seems the proxy is used, but not the exceptions.

**Comment by lasote** [comment]
Yes, we know, we just checked the history looking for proxy related issues and we saw that you had problems in the past with tools.downloads. We are trying to see if the bug explains all the weird situations. Did you started to use the proxies at system level after the tools.download issue?

**Comment by memsharded** [comment]
I am digging in to this, and suspecting that we might have a problem. Some questions for @claasd 

- Are you using the proxy exclusions for all the conan stuff?
- Would any of the conan requests actually go through your proxy?

It might happen that in your case it might be working even if the system proxies are not being used by conan/python-requests. Just because the proxy settings are excluding those IPs.

The way to try it might be simple: **please try to remove the ``[proxies]`` section header from your conan.conf**. In that case, "None" will be returned, conan/python-requests will use not proxies at all, but it will work because of the Exclusions at the system level.

The error seems to be that ``urllib.request.getproxies()`` is returning the configured proxies, that are used despite the Exclusions. But changing it (so it might be good as currently released), will make that users routing the conan requests via the system proxy will stop working. In the past, it worked for you, because there was a bug only for python 3 that would silently pass, with the same effect has having no ``[proxies]`` section header at all.

Looking forward your feedback. Many thanks!

**Comment by memsharded** [comment]
Ok, then it was an undetected bug, no changes are necessary if the proxies section is removed.

yes, you can remove it programatically with:

```bash
$ conan config rm proxies
```

Also, you might be interested in the ``conan config install`` new feature (released in 0.27): http://docs.conan.io/en/latest/reference/commands/config.html#conan-config-install

The issue with it is that for conan.conf it doesn't remove, it just override given values. Maybe some way to be able to remove proxies with the ``conan config install`` command should be useful, though I can't think of a clean way to specify it.

**Comment by claasd** [comment]
Removing the proxies with config rm worked, thanks.
The conan config install looks great. If i use this, i can specify the complete company proxy configuration in the installed conan.conf, especially with `no_proxy` setting, I don't need to remove the proxy.

**Comment by memsharded** [comment]
good. Then I think this issue doesn't require further action from our side at the moment, and can be closed. Thanks very much for all your feedback and help!
