### ISSUE TITLE
conan upload allowed wildcard references

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#1779]
This is a little nitpicky, but I figured I would report it anyway.

I find it a bit weird that `conan upload Foo*@user/channel` works fine, but `conan upload Foo/*@user/channel` yields an error "There is no local conanfile exported as Foo/&ast;@user/channel". I'm not sure if this is intentional or a defect. The latter is more intuitive to me, and might even be more correct (If I have a "FooBar" as well as a "Foo" then I think uploading "Foo*" would upload both, whereas "Foo/&ast;" would not.

**Comment by memsharded** [comment]
No, I think it is a valid issue, I also find it a bit annoying when this happens. I think it shouldn't be difficult to improve, lets try for next release.

**Comment by memsharded** [comment]
Released in 0.28
