### ISSUE TITLE
Consider using issue templates

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1780]
Hi!

After I reviewed some opened issues, I found many gaps when someone try explain about the problem/bug or unexpected behavior. Would be nice if everyone could use some steps to describe better, how to reproduce and include the scenario information. Also, to request new features, many times there is no explanation about the value of the feature (e.g. my issue for LDAP plugin), the issue only contains the property description but doesn't explain why it is necessary.

Github can include templates for PR and issues [1], such feature would be nice to include in Conan project. Also, I included some good templates [2] [3] [4] from some well known projects. 

Regards.

[1] https://github.com/blog/2111-issue-and-pull-request-templates
[2] https://gitlab.com/gitlab-org/gitlab-runner/tree/master/.gitlab
[3] https://github.com/philsquared/Catch/tree/master/.github
[4] https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md

**Comment by danimtb** [comment]
Hi @uilianries!

Thanks for you suggestion. There is now a PR open https://github.com/conan-io/conan/pull/2123 with new contrubuting guidelines that will be merged soon.

Have a look! :)

**Comment by uilianries** [comment]
Thanks!

Usually I enforce all topics, "what, why, how" for features or "what, steps to reproduce, version" for bugs on template. However the PR uses a check list to ensure these topics. I really liked this approach. Anyone will be able to explain a problem/request/question with more flexibility.

Regards!
