### ISSUE TITLE
conanfile.py error with cmislib

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#1782]
When conanfile.py imports the module cmislib ([doc](http://chemistry.apache.org/python/docs/) and [sources](https://svn.apache.org/repos/asf/chemistry/cmislib/trunk/)), conan create fails with message `ERROR: Unable to load conanfile in (...)\conanfile.py
AttributeError: 'module' object has no attribute '__file__'`
I tried the following without success : 
```python
from cmislib.model import CmisClient
```
```python
import cmislib.model
```
```python
import cmislib
```

**Comment by memsharded** [comment]
Are you running with the pip installed conan version? Installed in the root python installation or in a virtualenv?

**Comment by ericLemanissier** [comment]
I am using pip installed conan and the root python installation

**Comment by memsharded** [comment]
It seems there is something weird in the xml transitive dependency of cmislib, that makes the loading of conan package recipes to fail processing them. I am having a look in case conan could fix it, but in the meantime you have an easy workaround, don't put the import at file level, but just in the place where its is needed, as:

```python
 def build(self):
        from cmislib.model import CmisClient
        #your code using CmisClient
```

**Comment by ericLemanissier** [comment]
Thanks, I confirm the workaround
