### ISSUE TITLE
Issues building container-based packages on Macos using ConanMultiPackager

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#1783]
Hi guys:

I want to use `ConanMultiPackager` to build Linux packages on my Mac.  The idea is to be able to debug the multi-package builds without having to push to Github and have Travis do the work.

I figured out how to pass a Linux `platform_info` and use `CONAN_DOCKER_IMAGE`, but when it gets inside of the Linux container Conan still thinks it is MacOS.  The reason why is that it uses my `~/.conan/profiles/default` which has `os=Macos`.

The build basically works ok except that it says

    Cross-platform from 'Linux' to 'Macos'

and then CMake complains constantly

    System is unknown to cmake, create:
    Platform/Macos to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake

Interestingly, I am using CMake to build the library, but it doesn't complain then.  It only complains when using CMake for the `test_package`.

I'd like to be able to do two things:

1. Override the platform in the multi-package builder (something like `CONAN_PLATFORM`)
2. Make sure that when the platform is changed, don't look at the `os` from `~/.conan/profiles/default`

Thanks!

**Comment by memsharded** [comment]
Hi Eric,

I guess you want to submit this issue better for conan-package-tools repo.

**Comment by sourcedelica** [comment]
Whoops - done.
