### ISSUE TITLE
conan create doesn't seem to pass appropriate options to test_package

### ISSUE THREAD

**Issue by mikea** [conan-io/conan#1787]
*this seems to be some recent change, because it used to work*

While executing command:

```
conan create me/master --build=missing -s compiler.libcxx=libstdc++11 --options fPIC=True --options shared=False -s build_type=Release
```

for the package below (on ubuntu:rolling), results in weird error (after successfully building a package):

```
Libcbor/0.5.0@me/master: Package '4e425457dd04295e1e4e5d1be960c3088889397c' created
Libcbor/0.5.0@me/master: Testing with 'test_package'Libcbor/0.5.0@me/master test package: Installing dependencies
Libcbor/0.5.0@me/master: WARN: Can't find a 'Libcbor/0.5.0@me/master' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++11, compiler.version=6.3, os=Linux
- Options: fPIC=False, shared=False
```

Please note several problems:
- `--build=missing` is specified
- `fPIC=False` for test_package.

Package definition:

https://gist.github.com/mikea/20e8e36d71284dcc2e05704631fac161

**Comment by memsharded** [comment]
Are you sure you used to specify ``-o shared=True`` for the package itself? You should use ``-o Pkg:shared=True``. I think this has been the behavior since ``conan create`` was introduced just a couple of months ago. Is it possible that it worked that way in the ``conan test_package`` command?

**Comment by mikea** [comment]
> Are you sure you used to specify -o shared=True for the package itself? 

Not sure what you mean. We have used `--options fPIC=True` for `conan create` for quite a while.

> You should use -o Pkg:shared=True

Where does this `Pkg:` come from? I can't find its usage in documentation, & [conan create documentation](http://docs.conan.io/en/latest/reference/commands/create.html) gives a specific example: `-o with_qt=true`. Should I use `Pkg:` prefix only for conan create or always?

**Comment by memsharded** [comment]
Sorry, this ``<Pkg>`` is actually the name of the package, like ``-o Boost:shared=True -o OpenSSL:fPIC=True``
It might happen that options without prefix were being discarded.

Certainly, the command line help and docs haven't been updated. Adding this to 0.28 to make sure to update it. 

You can check the ``Pkg:option=value`` syntax in other places in the docs: http://docs.conan.io/en/latest/manage_deps/conanfile_txt.html#options
In any case, we strongly recommend using profiles, not typing options directly in the command line.

**Comment by mikea** [comment]
@memsharded specifying `<Pkg>:` in `conan create` helps, thank you.

**Comment by memsharded** [comment]
Re-open, to make sure the command line help is updated, maybe some example added to the docs.
