### ISSUE TITLE
conan remove does not remove empty folders

### ISSUE THREAD

**Issue by tobyas** [conan-io/conan#179]
Conan remove does not remove empty folders.
Doing a **conan export user/test** for a package named hello followed by a **conan remove hello/0.1@user/test** will leave behind the empty folders hello, 0.1 and user. With hello and 0.1 being quasi empty. This becomes a problem if you want to change the case for a package (hello to Hello) since conan still detects the remaining empty folders. The case problem might be resolved by #171, but letting the empty folders clutter the folder hierarchy seems rather bad.

**Comment by memsharded** [comment]
Yes, agree, this should be fixed, and should be simple enough to be done for next release, I'll try to implement it for 0.8.
