### ISSUE TITLE
CI Improvements, new e2e tests

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1790]
- Move e2e tests to public conan suite. (Keep some test using a built client)
- Tag tests with non-common external tools: meson, go, scons
- Objective: Have different builds, well organized, guarantee that a release runs all the tests.

**Comment by lasote** [comment]
- Test system package tools with docker images.

**Comment by lasote** [comment]
- Authentication against Bintray/Artifactory: Test wrong credentials, wrong URL, check outputs.
- Test client against older conan_server versions?

**Comment by lasote** [comment]
Windows + Autotools => Mingw / MSYS

**Comment by lasote** [comment]
Conan package tools, test with the new conan release.

**Comment by memsharded** [comment]
It would be nice to be able to run different compiler versions in the same OS, or even being able to run tests that would use two different compiler versions.
