### ISSUE TITLE
Badly formed vcvars_command in v0.27.0

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#1794]
Hi everyone,

I have recently upgraded to conan v0.27.0 and have noticed that it breaks the build of the GLEW package. In line 68 of conanfile.py I call vcvars_command and then execute the resulting code:

https://github.com/dimi309/glew/blob/2.1.0/conan/build/conan/conanfile.py

Running the build, I get an error that starts with this:

`ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\; \../../VC/Auxiliary/Build/vcvarsall.bat" x86 &&
`
So it looks like vcvars command was produced as `set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\; \../../VC/Auxiliary/Build/vcvarsall.bat" x86`, which I guess is not correct.

I don't know if I'm misunderstanding something, but this build used to work before I upgraded my conan version.

**Comment by memsharded** [comment]
The command line has been changed for VS2017, I guess that could be the issue, in the past you were using VS2015, could be? The detection of VS2017 has been improved too, so if it is in the system, it will be used as default (previously it wasn't detected).

Please check with VS2015, to make sure it is not a regression. Then maybe for VS2017, the latest line of your ``build()`` needs to be different.

**Comment by dimi309** [comment]
I have not used vs2015 or installed it on my PC for about a year...  So I
don't think it's that.

Also the env vars command starts by entering a path without "cd" or
anything. It looks like there's something wrong there,  to me at least.
I'll keep looking into this in case I'm mistaken...

**Comment by memsharded** [comment]
Conan didn't work for VS2017 that long time ago I think. Is it not possible that you had VS14 toolset installed? Please, keep us updated about your findings, so far seems to work fine here.

**Comment by dimi309** [comment]
I exaggerated I guess about the year but the point is that I have been
using vs2017 with Conan for months without any older components installed
and this problem only showed up now. I'll let you know if I discover
anything further.

**Comment by SSE4** [comment]
@dimi309 I see there is semicolon appeared in the middle of path somehow, can you possibly execute the following in cmd.exe and paste output here?
```
"C:\Program FIles (x86)\MIcrosoft Visual Studio\Installer\vswhere.exe" -version [15.0, 16.0) -legacy -property installationPath
```

**Comment by solvingj** [comment]
I'm having an issue that is possibly related, although there is no semicolon.  

Symptom:  On this trivial project, X86/Debug won't work, the other 3 combinations do. 

```
Build FAILED.

"C:\Users\jerry\.conan\data\utility-lib\0.1.0\solvingj\testing\build\fcf20edfcd8d4d6fe4521d911246a667d70de4f3\utility-l
ib.sln" (utility-lib target) (1) ->
"C:\Users\jerry\.conan\data\utility-lib\0.1.0\solvingj\testing\build\fcf20edfcd8d4d6fe4521d911246a667d70de4f3\utility-l
ib\utility-lib.vcxproj" (default target) (2) ->
(PreBuildEvent target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: The command "C:\Users\jerry\.conan\data\utility-lib\0.1.0\solvingj\testing\build\fcf20edfcd8d4d6fe4521d911246a667d70de4f3\conaninstall.bat C:\Users\jerry\.conan\data\utility-lib\0.1.0\solvingj\testing\build\fcf20edfcd
8d4d6fe4521d911246a667d70de4f3\ C:\Users\jerry\.conan\data\utility-lib\0.1.0\solvingj\testing\build\fcf20edfcd8d4d6fe4521d911246a667d70de4f3\Debug\ Win32 Debug\r [C:\Users\jerry\.conan\data\utility-lib\0.1.0\solvingj\testing\build\fcf20edfcd8d4d6fe4521d911246a667d70de4f3\utility-lib\utility-lib.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,
5): error MSB3073: :VCEnd" exited with code 9009. [C:\Users\jerry\.conan\data\utility-lib\0.1.0\solvingj\testing\build\fcf20edfcd8d4d6fe4521d911246a667d70de4f3\utility-lib\utility-lib.vcxproj]
```

**Comment by SSE4** [comment]
@solvingj could you upload complete log?

**Comment by solvingj** [comment]
Go ahead and clone it and try to run the build, i'm pretty sure it's consistent.

**Comment by SSE4** [comment]
sure

**Comment by solvingj** [comment]
Just updated my comment with entire log

**Comment by dimi309** [comment]
@SSE4, the output from the command you suggested I run is this one:
`
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community`

**Comment by SSE4** [comment]
@dimi309 one more question,request, can you paste output of `set` command here?

**Comment by dimi309** [comment]
@SSE4 here it is:

```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\user\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=LAPTOP-LDV9NVC5
ComSpec=C:\WINDOWS\system32\cmd.exe
HOMEDRIVE=C:
HOMEPATH=\Users\me
LOCALAPPDATA=C:\Users\user\AppData\Local
LOGONSERVER=\\LAPTOP-LDV9NVC5
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\user\OneDrive
OS=Windows_NT
Path=C:\Users\user\Source\vconan\Scripts;C:\VulkanSDK\1.0.54.0\Bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\Software\doxygen\build\bin;C:\Users\user\Software\bin;;C:\MinGW\bin;C:\Program Files\CMake\bin;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD
PROCESSOR_LEVEL=22
PROCESSOR_REVISION=3001
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=(vconan) $P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\user\AppData\Local\Temp
TMP=C:\Users\user\AppData\Local\Temp
USERDOMAIN=LAPTOP-LDV9NVC5
USERDOMAIN_ROAMINGPROFILE=LAPTOP-LDV9NVC5
USERNAME=me
USERPROFILE=C:\Users\me
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VIRTUAL_ENV=C:\Users\user\Source\vconan
VK_SDK_PATH=C:\VulkanSDK\1.0.54.0
vs150comntools=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;
VULKAN_SDK=C:\VulkanSDK\1.0.54.0
windir=C:\WINDOWS
_OLD_VIRTUAL_PATH=C:\VulkanSDK\1.0.54.0\Bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\Software\doxygen\build\bin;C:\Users\user\Software\bin;;C:\MinGW\bin;C:\Program Files\CMake\bin;
_OLD_VIRTUAL_PROMPT=$P$G
```

**Comment by solvingj** [comment]
@dimi309 you have an extra semicolon at the end of your `vs150comntools` variable. 

run this command and that should fix it:  `setx vs150comntools "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools"`

**Comment by dimi309** [comment]
Thanks @solvingj but my vs150comntools variable is already set. You can see it in the listing above.

**Comment by dimi309** [comment]
ah sorry I misunderstood

**Comment by dimi309** [comment]
Indeed @solvingj that did the trick. Thanks! Sorry for creating an entire issue out of this.

**Comment by SSE4** [comment]
I've submitted PR #1802 which will help troubleshooting such situations

**Comment by dimi309** [comment]
In my humble opinion, that is a very good idea! Thanks again for your help.
