### ISSUE TITLE
config install from git repo fails - tels me to go away

### ISSUE THREAD

**Issue by ovidiub13** [conan-io/conan#1805]
```
conan config install https://mygitserver/conan-settings.git
Trying to clone repo  https://mygitserver/conan-settings.git
Initialized empty Git repository in /var/jenkins_home/workspace/myproject/conan_home/.conan/tmp_config_install/config/.git/
fatal: You don't exist. Go away!
```

The `CONAN_USER_HOME` is set to point to the `/var/jenkins_home/workspace/myproject/conan_home/` directory.

I don't know wether that error is from git or conan.

This is obviously executed in jenkins. The repository is accesible from my local machine and other the windows jenkins slave. I only get this error on the Linux Jenkins slave.

Machine details:

* CentOS 6.6
* git 1.7.1
* conan 0.27.0

**Comment by ovidiub13** [comment]
I found the cause and reproduce mode.

Cause: git tries to get the UID of the current user, and fails in the following scenario:

Reproduce mode:

    docker run --user `id -u`:`id -g` <dockerImage> bash
        export CONAN_USER_HOME=/tmp/conan_home
        mkdir $CONAN_USER_HOME
        conan config install https://mygitserver/conan-settings.git

The docker image must contain git and conan installed. Mine is based on CentOS 6.9.

**Comment by SSE4** [comment]
@ovidiub13 
can you add the following lines to your Dockerfile and try again?
```
git config --global user.name "John Doe"
git config --global user.email "noreply@example.com"
```

**Comment by memsharded** [comment]
The msg ``fatal: You don't exist. Go away!`` is certainly not a conan message. While conan is a barbarian, he tries to be nice to users. :)  Certainly a git message.

Not sure @SSE4 why git would need the user name and email, because no commits are being made. Will have a look.

**Comment by ovidiub13** [comment]
IMO this is not a conan issue. This is a Git and Docker issue. It shouldn't be conan's responsibility to fix it.
