### ISSUE TITLE
Ask: Make use of custom settings

### ISSUE THREAD

**Issue by rukgar** [conan-io/conan#1806]
Hi,

Due to cross compiler requests I need to compile with a tool that is not a simple clang compiler but a compliant. I'm using cmake as my building tool and works fine but I want to use Conan as dependency provider.

My issue comes when Conan is unable to know the compiler. I have set the variable to clang (cmake detects that) but then other variables are required.

Is there a way to define that, when some condition happens (e.g. A provider setting) other requirements are ignored?

Thanks

**Comment by memsharded** [comment]
Hi @rukgar 

I am not fully sure what you mean.

The settings are fully configurable. There exists a ``settings.yml`` file, in which you can extend, add, customize the settings as you need. Please check: http://docs.conan.io/en/latest/reference/config_files/settings.yml.html

Then, those settings are just "declarations". They don't actively do anything in your system, like if you install with ``settings.compiler="clang"`` it will automatically install, configure, detect clang... 

The interaction of the settings are typically done via the ``build()`` recipe method. They will be used by it, for example, by the ``CMake`` helper, to generate the correct commands to build accordingly to the settings. But still is possible that the path to the compiler must be set in CC, CXX env variables, if it is not the default compiler in the system. It is possible also, that the ``CMake`` helper will not generate the correct command for custom ``settings.yml``. But that helper is just a something that translate the settings to command line strings, so no magic there, you can provide your own implementation easily.

It is possible to have conditional requirements, check for example: http://docs.conan.io/en/latest/reference/conanfile/methods.html#requirements

But I am not sure you are asking about. Could you please explain a bit more detailed about your setup, which variables are you talking about, etc? Also, the best is always to provide something reproducible, like if you can put in a github repo an example, with a custom settings.yml, or what you are trying to build, with a very simple "hello world" code example, that really helps. Thanks!

**Comment by rukgar** [comment]
I'll try to use custom settings but I'll try to explain a little bit more my problem anyway.

I have a build system, in-house, that after some work relies the workload to cmake. In order to do that, my build system makes use of conan to download package depedencies (only download) and then it builds it by itself.

The integration works flawlessly with OSX, Linux, Windows, iOS and Android but fails badly with emscripten (Web compile). 

This is the error type:

`Conan failure reason: Auto detecting your dev setup to initialize the default profile (/home/jenkins/.conan/profiles/default)
18:54:27 CC and CXX: /home/jenkins/tools/emsdk_portable/emscripten/tag-1.35.0/emcc, /home/jenkins/tools/emsdk_portable/emscripten/tag-1.35.0/emcc 
18:54:27 ERROR: Not able to automatically detect '/home/jenkins/tools/emsdk_portable/emscripten/tag-1.35.0/emcc' version
18:54:27 ERROR: Unable to find a working compiler
18:54:27 Default settings
18:54:27 	os=Linux
18:54:27 	arch=x86_64
18:54:27 	build_type=Release
18:54:27 *** You can change them in /home/jenkins/.conan/profiles/default ***
18:54:27 *** Or override with -s compiler='other' -s ...s***
18:54:27 
18:54:27 
18:54:27 ERROR: Conanfile: 'settings.compiler.libcxx' value not defined`

**Comment by memsharded** [comment]
There is some ongoing work related to emscripten here: https://github.com/conan-io/conan/pull/1565 You might be interested in tracking and giving feedback in that thread too.

I would need to know more about your setup and your environment, but I will try to explain at least the error your are seeing:

- It is running the initial auto-detect, the first time you run conan. So it seems you are running in a new clean machine
- This initial auto-detect only purpose is to generate a ``default`` profile with some sensible setting, nothing else.
- You have your env vars CC and CXX pointing to emcc, which would be a good idea, but the built-in conan auto-detect is not prepared to detect emcc yet. This is a valid feature-request, that probably has to be implemented to support https://github.com/conan-io/conan/pull/1565
- This is not a big problem, after that failure, you can go and edit the profile yourself. You have ``conan profile set settings.compiler=emcc`` to do that (assuming you have added ``emcc`` to your ``settings.yml``
- You should probably also set the compiler version and the compiler standard library version the same way (if emcc uses a standard library, otherwise, the ``settings.yml`` shouldn't declare it)
- Remember that you can also share and install both ``settings.yml`` and profiles easily with the ``conan config install`` command.

Please check if this makes sense and help you pass over this error. It would also be great if you could help giving feedback in https://github.com/conan-io/conan/pull/1565, I would like to see some more built-in support for emscripten in conan, but we need the collaboration of users like you using it. Many thanks!

**Comment by rukgar** [comment]
Hi again and thanks for answering my questions :)

I'll try to clarify a little bit more the holes in the problem (as far as confidentiality allows me).

Environment:
- E1: Jenkins slaves with on demand conan installation. Shared conan cache repository that withholds the recipe and the code (shared among compilations)
- E2: Jenkins slaves that are created on demand with on demand conan installation. Those slaves will we always fresh and the cache will last for the slave life (from 3 hours to 1 day)

Integration:

Our integration is currently source code focused. We try to deliver our libraries and codebase using conan but we will push forward libraries soon enough. 

The emsdk problem that I have seen is related with binary retrieval and can be bypassed through variable setup (i have set the compiler to _clang_, libcxx to _libstdc++_ and version to _3.5_ but that is really customized for our current deployment and will fail when we use emsdk 3.7

Bypassing that I found the problem of the check_compiler not being able to know about the version of emcc through auto-discovery and with that the build failure. Solved using the CMake variable to bypass that but also a workaround...

I'll check the settings solution to make it cleaner and think about sharing the profiles through my organisation. Is it possible to share it through Artifactory as well as the recipes? Are the settings project tied or can be general?

I have subscribed to the ticket and try to give my feedback. Thanks!

**Comment by memsharded** [comment]
Just in case, are you aware of the ``CONAN_USER_HOME`` variable? It can be useful to create clean conan instances without needing virtual machines or other things.

Let me also warn against concurrent usage of the cache. Even if we are working on some improvements, the conan local cache is not concurrent, if you are building with parallel Jenkins job using the same cache, you might run into issues.

The ``conan config install`` works with any URL endpoint, you can put and download a zip file from it, so artifactory might be possible, indeed. Also git repos work, so you can directly put all the config, profiles, settings, in a git repo and pass the URL of the git repo to ``conan config install`` avoiding the burden of having to zip and upload to other place.

The ``settings.yml`` are per conan installation, not per project. But if you are using different ``CONAN_USER_HOME``, you can have different settings.yml in each one.

For confidential info, you can also write at info@conan.io email.  Thanks!

**Comment by rukgar** [comment]
I didn't know about that property (I need to dig deeper into the docs) but that is not an issue since our requirement in clean slaves is mainly an issue of scalation and uniformity. Nothing to do with conan.

About the concurrency. Our system picks the code and compiles in a different folder but I'll take that into account that maybe one is compiling while another is updating the source code. That should not happen since they are released versions of the code but who knows...

**Comment by memsharded** [comment]
Closed as inactive
