### ISSUE TITLE
tools.patch fails with new/deleted files

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#1807]
Hello,

I tried to apply a `.patch` using `tools.patch`, however the dependency conan is using does not handle new/deleted files. (see [this line](https://github.com/techtonik/python-patch/blob/master/patch.py#L703) in particular).

Furthermore, this library has not been updated in a year. [This one](https://pypi.python.org/pypi/git-patch/2.1.1) looks maintained, I haven't tested it though.

To workaround that, I used `self.run` to launch git apply.

**Comment by memsharded** [comment]
Thanks for having a look at this, and the suggestion. I think we could try to use the proposed, maintained one, lets have a look.

**Comment by memsharded** [comment]
Could you please give a failing patch to apply? I guess it will be the typical ---- null, ++++new_file, right? We should add some test.

**Comment by theodelrieu** [comment]
Indeed, here is a minimum patch file that reproduces the error:


```patch
diff --git a/newfile b/newfile
new file mode 100644
index 0000000..ea450f9
--- /dev/null
+++ b/newfile
@@ -0,0 +1 @@
+New file
```

**Comment by memsharded** [comment]
The https://github.com/vrajat/git-patch repo is just a wrapper over git, I think it is better to use a python solution, for those not using git.

I have tried to contribute upstream: https://github.com/techtonik/python-patch/pull/52

**Comment by theodelrieu** [comment]
I agree. Not sure the repo is still maintained though, looking at the last closed issue which was in September 2016.

Also I remember the `patch` command failed at the first **warning**, that might be why your PR doesn't pass.

**Comment by memsharded** [comment]
I have proposed a local fix in: https://github.com/conan-io/conan/pull/1898

The upstream is abandoned, no response from PR. Also there is already a PR for that issue long time ago, without response

Cannot find viable alternatives. Tried google patch-diff lib, but only from text-text no real unidiff with new and deletes.

**Comment by theodelrieu** [comment]
That's unfortunate... What about forking the repo? I don't see many options anyway.

**Comment by memsharded** [comment]
Released in 0.28

**Comment by theodelrieu** [comment]
Hi @memsharded, I've tried to use `tools.patch` again, and it still fails with the following message:

>WARN: sioclient.patch: error: absolute paths are not allowed - file no.3
WARN: sioclient.patch: stripping absolute path from source name 'b'/dev/null''

Was the forked patch dependency published to pip?

**Comment by memsharded** [comment]
No, finally conan implemented its own management of creation/deletion of files.  Check it here. https://github.com/conan-io/conan/blob/develop/conans/client/tools/files.py#L174

There are conan tests covering this functionality: https://github.com/conan-io/conan/blob/develop/conans/test/util/conanfile_tools_test.py#L95

Maybe you could try to provide a failing test to replicate this issue? What is exactly your patch? Thanks for the feedback

**Comment by theodelrieu** [comment]
Sure, here is a recipe that should reproduce the bug.

[new_file_bug.zip](https://github.com/conan-io/conan/files/1463675/new_file_bug.zip)

**Comment by memsharded** [comment]
Ok, great, glad that it is working, thanks for telling :)
