### ISSUE TITLE
[Feature request] generate .gdbinit for package and its dependencies

### ISSUE THREAD

**Issue by thiagocrepaldi** [conan-io/conan#181]
I've done some tests and GDB debugging works when I build not only the package locally, but also their dependencies (my packages had source-code inside)

Look the .gdbinit I've done:
``
set verbose on

// # Binary to be debugged
file /home/thiago/sandbox/conan/app2/build/bin/app2

// # Toolchain path
// # set sysroot /opt/toolchain/1.6.2.4/sysroots/core2-32-linux/

// # Project libs
set solib-search-path /home/thiago/.conan/data/MyLib3/develop/company/develop/package/9c5cb7abd2e69d5ee3c867436f26f0d50fa7a597/lib:/home/thiago/.conan/data/MyLib1/develop/company/develop/package/9c5cb7abd2e69d5ee3c867436f26f0d50fa7a597/lib

// # Source code paths
dir /home/thiago/sandbox/conan/app2/include:/home/thiago/sandbox/conan/app2/src:/home/thiago/.conan/data/MyLib1/develop/company/develop/export/src:/home/thiago/.conan/data/MyLib1/develop/company/develop/export/include:/home/thiago/.conan/data/MyLib3/develop/company/develop/export/src:/home/thiago/.conan/data/MyLib3/develop/company/develop/export/include
``
As it can be seen, I had to manually dig several conan directories for the packages, which brings me the question (more a feature request). Would be possible for conan to implement a "gdb" or "gdbinit" generator to create this for us ? I guess conan already have everything it needs, but needs to write it in a proper gdb format.

**Comment by lasote** [comment]
Hi @thiagocrepaldi 
Doing a generator is quite simple, but looking at your example I see a couple of problems.
1. Conan doesn't know anything about the executables in your application, so the first line would have to be filled manually.
2. The toolchain path is unknown to conan too.
3. The source code paths: by default, if you don't specify the --build option in the **conan install** command, conan don't have the sources (just the headers) of your dependencies.

Maybe the generator lacks enough information to become something useful... but we can thinking about it and continue this issue with more ideas.

**Comment by memsharded** [comment]
Inactive for long time, not enough requests, closing. 
Implementing custom generators is now easy too.
