### ISSUE TITLE
Option to skip remotes on create/install

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#1816]
If one (or more) remotes is down, `conan create` and `conan install` fail when checking for dependencies even if the remote isn't required. For example, if I already have the dependency in my cache, I don't actually need the remote to function to succeed at building.

I think it makes sense for this to be an error by default, as it is an unexpected scenario, but a command line parameter to override it would be nice. Something like "--noremote" to skip checking remotes. Currently the only workaround if your remote goes down is to delete the remote from your remotes list (which is annoying).

Note that this behavior only matters if the requirement is using a version range, rather than an explicitly specified version. In the case of an explicitly specified version that is available in the cache, the remotes aren't checked.

**Comment by memsharded** [comment]
I am not sure this is the current behavior. Conan create or conan install will try to install dependencies, but if they are already installed in the local cache, even with version-ranges, the servers shouldn't even be checked, so nothing should fail. Only when doing ``--update`` the servers are checked. I'll make a quick check.

**Comment by memsharded** [comment]
Everything looks good, I have checked, and the remotes are not contacted at all, even with version ranges.  Could you please double-check?

**Comment by mpdelbuono** [comment]
Strange. I'm trying to reproduce it now and I can't. I might have screwed something up when I initially encountered it, even though I spent a bunch of time trying to minimize the test case.

I'll chalk this one up to me screwing up a command, and reopen if I am able to reproduce it again. Sorry for the noise.
