### ISSUE TITLE
[cmd refactor] package

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1825]
- Delete use case of repackaging in local cache from local cache
- Focus on: build local + package_files for debugging/developing packages use case

**Comment by solvingj** [comment]
I was working with `conan package` command to debug the `package` step today. I hit the same surprise that somebody else hit the other day, which is that the `package` method works differently depending on which CLI command is used to invoke it.  When running `conan package` is used, several commonly used and relevant variables are simply not are available, so the `package` will sometimes just not be testable using this method.  

I think several of us liked the existing concept of "just run the package step from this recipe using the cache" and would have requested that the missing variables somehow be made available.  However, if you're going to provide a different methodology altogether, then perhaps the refactoring can take the described problem into account and make sure a similar problem doesn't exist.

**Comment by lasote** [comment]
What do you mean with the `missing variables`?

**Comment by solvingj** [comment]
Sorry, package folder, build folder, etc.
