### ISSUE TITLE
CMake variable relative to package root

### ISSUE THREAD

**Issue by Hedanito** [conan-io/conan#1827]
I have a package that contains a specific file that I want to be able to access from CMake.
`user_info` seems to be the way to add variables, but I don't know where to get the path to the package root from.
There is `conanfile_directory`, but I believe that points to the export directory, not the package directory.

I basically want this:
```
def package_info(self):
        self.user_info.SPEC = os.path.join(<package_root_here>, "src", "spec", "vk.xml")
```

So that I can reference CONAN_USER_VULKANDOCS_SPEC from CMake to get the path to the file.
What would be the right way to do this, if at all possible?

**Comment by memsharded** [comment]
I am not sure what you mean. You mean, accessing one of your dependencies package to get some file? Then you don't need to declare a variable, just from the consumer package, something like this:

```python
def build(self):
      cmake = CMake(self)
      # I assume that "Vulkan" is a required dependency
      my_spec = os.path.join(self.deps_cpp_info["Vulkan"].rootpath,  "src", "spec", "vk.xml")
      #pass it to your cmake with a variable or something
```
Please tell me if this helps, thanks!

**Comment by Hedanito** [comment]
Close, but no.

I have the `Vulkan` package, and I have project that depends on it using a conanfile.txt
When I depend on the `Vulkan` package, I want the `cmakebuildinfo.cmake` to contain a variable that points to a specific file in the package, `vk.xml` in this case.

So most importantly, I want the variable to be created by the `Vulkan` package. After all, the package should tell me where all the important files are.

**Comment by memsharded** [comment]
The knowledge about the upstream is still necessary, as the consumer still needs to know about CONAN_USER_VULKANDOCS_SPEC. But it that file can change in future versions, then can make sense.

I think you might be looking for:

```python
def package_info(self):
    self.user_info.SPEC = os.path.join(self.package_folder, "src", "spec", "vk.xml")
```
You can check about folders here: http://docs.conan.io/en/latest/reference/conanfile/attributes.html#folders

**Comment by mpdelbuono** [comment]
I would use a relative path in a user_info var here:

```python
def package_info(self):
    self.user_info.SPEC = "src/spec/vk.xml"
```

You then have two options for how to use that value later. In the conanfile of the dependent package:
```python
def build(self):
    foo = os.path.join(self.deps_cpp_info["Vulkan"].rootpath,
                     self.deps_user_info["Vulkan"].SPEC)
```

Or you can make the path directly in CMake, if you are using the CMake generator:
```cmake
include(conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
set(ABS_PATH "${CONAN_VULKAN_ROOT}/${CONAN_USER_VULKAN_SPEC}")
```

I use this pattern a lot in some of my packages; I think it is important that the package itself does _not_ know where it is stored, because it could be moved around a lot. Therefore, you can't make the absolute path at creation time. However, at package use time, you can determine the absolute path, as is being done here.

**Comment by memsharded** [comment]
@mpdelbuono yes, that is a valid approach for conanfile.py, thanks for the suggestions! :)
 But in this case it seems that the OP wants to consume the package with ``conanfile.txt`` so no possible to use the ``build()`` method.

**Comment by Hedanito** [comment]
`self.package_folder` is indeed what I was looking for.
I was seaching for `directory` in the documentation based on the other variable names, and I overlooked it.

Thank you for your help

**Comment by memsharded** [comment]
Great, thanks to you for your feedback.

Yes, I agree, the ``conanfile_directory`` was very early-legacy variable name, when we added the rest, we thought that ``package_folder``, ``source_folder``, etc, read much better. But it is not easy to deprecate the former, as it is widely used. 

I think this issue can be closed now, please ask any further question, or open new issues as necessary.
