### ISSUE TITLE
Chocolatey hangs on msys2 install when run from conan

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1830]
This hangs after extracting 13,505 files: 
```
    def system_requirements(self):
        if os_info.is_windows:
            installer = SystemPackageTool(tool=ChocolateyTool())
            installer.install("msys2")
```
But, when running `choco install msys2` manually it continues on to finish the installation.

**Comment by solvingj** [comment]
Note, msys2 installer spawns scripts which run in additional command windows, so it would not surprise me if it's particularly hard for Python to control well.  I would understand if it's not worth the time to fix at this juncture.

**Comment by lasote** [comment]
Please, try passing a runner to the SystemPackageTools constructor: `runner=os.system` to run directly without capturing the output. Especially on Windows, piping a big output in python hangs the process.

**Comment by solvingj** [comment]
Did not test because no longer need the functionality. Created Conan MSys2 package instead, better for future.
