### ISSUE TITLE
conan upload dumps bintray login page html as text

### ISSUE THREAD

**Issue by VestniK** [conan-io/conan#1832]
I've created bintray OSS account, group and added repository to the group. But I've used wrong URL while adding remote to conan (I've copied group URL instead of repository URL into my `conan remote add` command). When I've tried to upload package I've got dump of bintray login page instead of usable error. It tooks qiute some time to investigate what's going on in such situation. Can you improve error reporting for a case when repository URL points to some resource which is not conan repository?

**Comment by memsharded** [comment]
Yes, could make sense, though sometimes the html provided by the server also is informative, like a message from a proxy server. Lets have a look.

**Comment by VestniK** [comment]
May be you can separate dump of the response from the error message with an empty line so they will be visually distinguishable.

**Comment by memsharded** [comment]
Could you please copy here your URL and the output message? I am trying to reproduce, but so far I can only see messages like ``ERROR: No JSON object could be decoded``, but no login page dumped.

Also, please, make sure you are using latest conan 0.27. Thanks!

**Comment by VestniK** [comment]
Yes I can reproduce it with 0.27:

    vestnik@uk-rnd-104:~/Development/VestniK/conan_deps$ conan --version
    Conan version 0.27.0
    vestnik@uk-rnd-104:~/Development/VestniK/conan_deps$ conan remote add test https://bintray.com/vestnik/VestniK
    vestnik@uk-rnd-104:~/Development/VestniK/conan_deps$ conan user -p *** -r test sirvestnik   
    Change 'test' user from None (anonymous) to sirvestnik
    vestnik@uk-rnd-104:~/Development/VestniK/conan_deps$ conan upload '*@VestniK/stable' -c -r test --all
    ERROR: Invalid header value 'Bearer \n<!doctype html>\n<!--[if IE 9]><html class="lt-ie10" lang="en" >login page dump here</html>\n'

**Comment by memsharded** [comment]
Should be fixed now in 0.28, please try.
