### ISSUE TITLE
Possible Substitution Problem with run_in_windows_bash()

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1834]
Here's the line from the recipe: 
```
tools.run_in_windows_bash(self, "./compile.sh")
```

Here's the error: 

```
Bazel/0.6.0@bincrafters/testing: run_in_windows_bash: bash --login -c ^"cd \^"/c/.conan/1g72jqg8/1/bazel-0.6.0\^" ^&^& ./compile.sh ^"
/bin/bash: line 0: cd: /c/.conan/1g72jqg8/1/bazel-0.6.0: No such file or directory
```

And then the summary exception: 

``` ConanException: Error 1 while executing bash --login -c ^"cd \^"/c/.conan/1g72jqg8/1/bazel-0.6.0\^" ^&^& ./compile.sh ^"```

It looks highly over-escaped. Still troubleshooting though, this is my first time using MSYS2.

**Comment by lasote** [comment]
Not sure if it's over-escaped. Probably it's ok. Is bazel located in that location?

**Comment by solvingj** [comment]
Yes,

**Comment by solvingj** [comment]
Here is the output when I run manually from msys cmd prompt:
```
jerry@JERRY-DELL-03 MSYS ~
$ cd "/c/.conan/1g72jqg8/1/bazel-0.6.0/" && ./compile.sh
  Building Bazel from scratch
```

**Comment by solvingj** [comment]
I've determined that I don't need to use MSYS on this project however, so if it's particularly tricky, maybe we can close until someone else reports same issue.

**Comment by lasote** [comment]
Probably yes, let's wait to have another solid use case before investigating further, it will help to get it sooner.
