### ISSUE TITLE
Same package ids, different packages

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#1840]
Hello, I was a bit confused to see the following output:

>Packages
>    Boost/1.65.1@theo/test:09c387acf229b69157ec6ee3dfb256b31e6cdb11
>    bzip2/1.0.6@theo/test:ae2f175e9f2651ac57cb18fa99d62b32ade1a327
>    zlib/1.2.11@theo/test:ae2f175e9f2651ac57cb18fa99d62b32ade1a327

As you can see, `bzip2` and `zlib` have the exact same SHA1, they indeed have the same options.

My question is: Isn't that dangerous? This could create massive issues in the future if you want to rely on package IDs without the full package reference.

What about hashing the package name and version as well as the options?

**Comment by memsharded** [comment]
This is important for having simple and robust workflows: consider when you promote a package from a given user/channel to a different one. Then you should recompute all the IDs, which could be fragile, and requires computing the dependency graph for each configuration. That can be really painful when you have hundreds of different configurations.

The package ID is always appended to the package reference, in no place they are used as a first class index or identifier. In the future, if we wanted to create unique IDs, it would be enough to hash them including the package reference, no problem. Also, de-duplication in server transfers is done via files checksums, not via the package IDs. So we should be mostly fine :)

Thanks for your question!

**Comment by theodelrieu** [comment]
Including the name and version, but not the user/channel, should not lead to ID recomputation.

But I get your point, that's not an issue then.

**Comment by memsharded** [comment]
But if you only include name and version, you have the same behavior that you wanted to avoid: you will get duplicated IDs for packages in different users/channels, which indeed might be different binaries (as a "ci" channel, doing coverage and static analysis).

**Comment by theodelrieu** [comment]
Oh that's right, I though it was not an issue at first that the IDs were the same in different user/channels, but that's indeed the same behavior...

Thanks for the clarification.
