### ISSUE TITLE
Installing new version of recipe does not mark packages as outdated

### ISSUE THREAD

**Issue by lewie-donckers** [conan-io/conan#1841]
For certain libraries under active development, we use the following workflow. We pin the version numbers and use a separate channel for these libraries. We only upload the recipes (so no packages) to our Conan server. So, when a we update the library, we overwrite the recipe on the Conan server.

Consumers of the library do a `conan install` with the `-u` option to check if new versions exist on the Conan server. I was under the assumption that Conan would then download the new recipe and mark any local packages as outdated.

I'm not sure if Conan downloads the new recipe but if the Conan cache already contains a built package of the old recipe, this package is not marked as outdated. Because of this Conan does not rebuild this package which causes builds to fail.

As a workaround we remove the recipe and all packages from the Conan cache but this is quite inconvenient.

**Comment by memsharded** [comment]
The package "outdated" feature is based on the recipe hash, not the recipe date. Is it possible that you did run this test using the same recipe that was used to generated the packages? Make sure the recipe has some modifications, and then you should see the binaries as outdated.

**Comment by lewie-donckers** [comment]
Yes, the recipe typically does not change in this scenario. Only the header/source files of the library.

Is there a way to change the recipe without modifying any of the standard recipe data? Perhaps by adding a bogus member variable to the Python class?

**Comment by memsharded** [comment]
Just add a comment to conanfile.py :)

I guess that the headers/sources are not ``exports_sources``, but retrieved with a ``source()`` method, right? If they were embedded in the recipe, and they had changed, then the recipe hash should change too.

**Comment by lewie-donckers** [comment]
We use `export_sources` for all these libraries. I also tried changing the recipe. But that didn't work either. I saw Conan detecting the change and building a new package though. (?!)

Perhaps the following is relevant: there is an indirect dependency to the library that changed: Application depends on libB which depends on libA. When I change the recipe of libA and do `conan install -u` for the application and rebuild, stuff breaks.

**Comment by lewie-donckers** [comment]
It looks like the package was rebuilt but that the old sources were used to do so?

Please take a look at the build output below. lmsdds.core is the updated library. From the log I gather that it's recipe was downloaded and that the package was rebuilt. However when I examine the package folder: `c:\shuttle\a1\c\lmsdds.core\0.8.3\shuttle\testing\package\0360a5f1de3610acad6fc54319fae7f93d69080f`, I see the sources of the previous version.

When I build using an empty Conan cache, the build succeeds.

```
Executing in c:\shuttle\a1\j\workspace\ter_master-FEI7Z3YWSEQH3ZYEDXT6D\build.vs2017.Debug.Static:
	conan install -u --build=outdated --set build_type=Debug --set compiler=Visual Studio --set compiler.runtime=MTd --set compiler.version=15 c:\shuttle\a1\j\workspace\ter_master-FEI7Z3YWSEQH3ZYEDXT6D
lmsdds.core/0.8.3@shuttle/testing: Retrieving from remote 'shuttle'...
Downloading conanmanifest.txt

Downloading conanfile.py

lmsdds.core/0.8.3@shuttle/testing: Updated!
PROJECT: Installing c:\shuttle\a1\j\workspace\ter_master-FEI7Z3YWSEQH3ZYEDXT6D
Requirements
    Boost/1.65.1-0@shuttle/stable from shuttle
    lmsdds.cmake/1.1.0@shuttle/stable from shuttle
    lmsdds.core/0.8.3@shuttle/testing from shuttle
    lmsdds.dds/0.8.3@shuttle/testing from shuttle
    lmsdds.idl.coredx.cpp/0.8.3@shuttle/testing from shuttle
    lmsdds.timeconv/0.8.3@shuttle/testing from shuttle
    twinoaks.coredx/4.0.16-2@shuttle/stable from shuttle
    twinoaks.coredx.license/latest@shuttle/stable from shuttle
Packages
    Boost/1.65.1-0@shuttle/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    lmsdds.cmake/1.1.0@shuttle/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    lmsdds.core/0.8.3@shuttle/testing:0360a5f1de3610acad6fc54319fae7f93d69080f
    lmsdds.dds/0.8.3@shuttle/testing:0096cc162fa228041175c20aab106634f047519e
    lmsdds.idl.coredx.cpp/0.8.3@shuttle/testing:1b40320a2d5219dd2dde9c3b9039103cf787f57a
    lmsdds.timeconv/0.8.3@shuttle/testing:963bb116781855de98dbb23aaac41621e5d312d8
    twinoaks.coredx/4.0.16-2@shuttle/stable:963bb116781855de98dbb23aaac41621e5d312d8
    twinoaks.coredx.license/latest@shuttle/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

Boost/1.65.1-0@shuttle/stable: Package is up to date
lmsdds.cmake/1.1.0@shuttle/stable: Package is up to date
lmsdds.timeconv/0.8.3@shuttle/testing: Package is up to date
twinoaks.coredx/4.0.16-2@shuttle/stable: Package is up to date
twinoaks.coredx.license/latest@shuttle/stable: Package is up to date
lmsdds.core/0.8.3@shuttle/testing: Outdated package!
lmsdds.idl.coredx.cpp/0.8.3@shuttle/testing: Package is up to date
lmsdds.dds/0.8.3@shuttle/testing: Package is up to date
Boost/1.65.1-0@shuttle/stable: Already installed!
lmsdds.cmake/1.1.0@shuttle/stable: Already installed!
lmsdds.timeconv/0.8.3@shuttle/testing: Already installed!
twinoaks.coredx/4.0.16-2@shuttle/stable: Already installed!
twinoaks.coredx.license/latest@shuttle/stable: Already installed!
PROJECT: Installing build requirements of: lmsdds.core/0.8.3@shuttle/testing
PROJECT: Build requires: [lmsdds.cmake/1.1.0@shuttle/stable]
PROJECT: Requirements
PROJECT:     lmsdds.cmake/1.1.0@shuttle/stable from shuttle
PROJECT: Packages
PROJECT:     lmsdds.cmake/1.1.0@shuttle/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
PROJECT: 
lmsdds.cmake/1.1.0@shuttle/stable: Package is up to date
lmsdds.cmake/1.1.0@shuttle/stable: Already installed!
PROJECT: Installed build requirements of: lmsdds.core/0.8.3@shuttle/testing
lmsdds.core/0.8.3@shuttle/testing: Building your package in c:\shuttle\a1\c\lmsdds.core\0.8.3\shuttle\testing\build\0360a5f1de3610acad6fc54319fae7f93d69080f
lmsdds.core/0.8.3@shuttle/testing: Configuring sources in c:\shuttle\a1\c\lmsdds.core\0.8.3\shuttle\testing\source
lmsdds.core/0.8.3@shuttle/testing: Copying sources to build folder
lmsdds.core/0.8.3@shuttle/testing: Generator txt created conanbuildinfo.txt
lmsdds.core/0.8.3@shuttle/testing: Calling build()
lmsdds.core/0.8.3@shuttle/testing: WARN: This conanfile has no build step
lmsdds.core/0.8.3@shuttle/testing: Package '0360a5f1de3610acad6fc54319fae7f93d69080f' built
lmsdds.core/0.8.3@shuttle/testing: Build folder c:\shuttle\a1\c\lmsdds.core\0.8.3\shuttle\testing\build\0360a5f1de3610acad6fc54319fae7f93d69080f
lmsdds.core/0.8.3@shuttle/testing: Generated conaninfo.txt
lmsdds.core/0.8.3@shuttle/testing: Generated conanbuildinfo.txt
lmsdds.core/0.8.3@shuttle/testing: Generating the package
lmsdds.core/0.8.3@shuttle/testing: Package folder c:\shuttle\a1\c\lmsdds.core\0.8.3\shuttle\testing\package\0360a5f1de3610acad6fc54319fae7f93d69080f
lmsdds.core/0.8.3@shuttle/testing: Calling package()
lmsdds.core/0.8.3@shuttle/testing package(): Copied 13 '.h' files
lmsdds.core/0.8.3@shuttle/testing: Package '0360a5f1de3610acad6fc54319fae7f93d69080f' created
```

**Comment by memsharded** [comment]
I'd need to gather more information about your complete workflow. I thought at some point you were using the ``conan create`` or ``conan export`` to update the recipe. If you don't, then yes, it could be using the uploaded old recipe and source code.

In general, I would recommend explicit ``conan create`` commands to create packages, instead of relying on ``conan install --build`` behavior. Please tell me about your flow, I will try to help. Thanks!

**Comment by lewie-donckers** [comment]
I'll try to be brief without leaving out anything I think might be relevant.

We have several libraries under active development. Some are header only, some are not. We use `conan create` to generate recipes (and packages) for these. Only the recipes get uploaded to the Conan server. As I mentioned before we pin the version numbers and use a separate channel for them.

We have several applications that use these libraries. In their build scripts we use `conan install -u` to install their requirements and then build using CMake.

In this particular example there are two header only libraries: lmsdds.core and lmsdds.dds where the latter depends on the former. The application has a requirement for lmsdds.dds.

What I notice is that builds with clean Conan caches (after a manual clear or on a fresh Docker container) succeed but builds where the Conan cache contains a package built with an old recipe fail.

**Comment by lasote** [comment]
@lewie-donckers have you tried to execute a `conan search ref_of_ lmsdds.core` after the fail to see if conan consider the local-cached binary package as outdated?

```

    Package_ID: 7fe67dff831b24bc4a8b5db678a51f1be5e44e7c
        [settings]
            arch: x86_64
            build_type: Release
            compiler: apple-clang
            compiler.libcxx: libc++
            compiler.version: 9.0
            os: Macos
        outdated from recipe: False
```

**Comment by memsharded** [comment]
You were totally right @lewie-donckers you have spotted a subtle bug: the ``exported-sources`` folder was not being deleted for updates. Already submitted a fix in: https://github.com/conan-io/conan/pull/1844

Will release it in next 0.28. Thanks very much for all your detailed and useful feedback!

**Comment by lewie-donckers** [comment]
Ah, great! Any ETA on 0.28?

Thanks for the quick feedback!

**Comment by memsharded** [comment]
Not ETA yet, but expect a couple of weeks, maybe about the 25th October. In the meantime, make sure to clean your cache first, to ensure the latest update is retrieved. Thanks!

**Comment by memsharded** [comment]
@lewie-donckers released yesterday! Could you please try it to confirm it was fixed? Thanks!
