### ISSUE TITLE
Default profile not setup

### ISSUE THREAD

**Issue by e-shreve** [conan-io/conan#1843]
After installing conan with pip, and then running conan the first time, I do not get the initial configuration messages as documented here: http://docs.conan.io/en/latest/installation.html#initial-configuration
The .conan folder is created but it does not contain profiles.

I tried both conan 0.27.0 and 0.25.1 and get the same result in Windows 7 and cygwin in Windows 7. I'm running Python 3.4.3, 64-bit. 
I also tried conan 0.27.0 on Python 3.6.3, 64-bit - same result.

**Comment by memsharded** [comment]
You are totally right. That functionality has been modified, and now the default profile will be generated only the first call it is needed. You can continue with the getting started, you will see it the first install command.

Also, you can force to create the default profile with:
```bash
$ conan profile new default --detect
```

I will update the docs asap to fix this, thanks very much for reporting!

**Comment by memsharded** [comment]
Updated documentation: http://docs.conan.io/en/latest/installation.html#initial-configuration

Documentation regarding profiles and default profiles will be done for next version, as we are doing a major revamp of the conan commands, and how they are presented.

**Comment by e-shreve** [comment]
Thanks for the fast response!
