### ISSUE TITLE
build sub-directory can't be created - likely due to symlinks

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1845]
I'm getting this error when using Bazel: 

```
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\Users\\jerry\\.conan\\data\\Abseil\\20170930\\bincrafters\\testing\\build\\814f12b80e8998d2cd2c6c15367fa816ad942b7f'
```

It only happens after running `conan create` for the second time.  If I delete the build directory manually and re-run, obviously it's fine. 

Note, I've had many cases where the directory can't be deleted because windows explorer or some cmd process has it open and locked, this is not the case here. 

My best guess about a cause is that Bazel generates symlinks in the build directory.  My guess is that when Conan tries to delete the build directory, something about the symlinks prevents it from actually deleting. Hopefully, this is enough of a lead that the problem is easily identified with a google search or glance into the source code.  If not, let me know and we can test other things.  Will continue manually deleting the directory for the time being.

**Comment by lasote** [comment]
Is it always happening? Is there a recipe we could try?

**Comment by solvingj** [comment]
I found that conan uses `shutil` for the removal of directories.  

https://github.com/conan-io/conan/blob/d210659f967c3dd100a34f984e55b8151e706364/conans/util/files.py#L139

A quick search turned this up:

https://bugs.python.org/issue31226

We are fortunate that Vidar reported this issue, it would have taken a long time to do the level of testing he did.

**Comment by memsharded** [comment]
So ``shutil.rmtree`` will always fail over the build folder generated by bazel. That is quite unfortunate, what conan could do? I am not sure about replacing the call to ``shutil.rmtree`` with something custom, as this might bring its own new bugs...

**Comment by solvingj** [comment]
I don't have a good solution in mind yet. I've thought about it a bit and don't like any of the options that came up.  It's going to grow as a problem though, as Bazel is used in more projects.  Protobuf and Tensorflow are both on our Radar.

**Comment by solvingj** [comment]
At present, projects which create symlinks on windows during build will have to cleanup and delete those symlinks for themselves in their package step as a workaround.
