### ISSUE TITLE
cmake generator does not patch runtime link on Windows/RelWithDebInfo

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#1854]
Hello,

I recently added `RelWithDebInfo` in my `settings.yml` file to package PDBs properly.

However, I get a runtime library mismatch in the `test_package` step while running the following command:

```shell
$ conan test_package theo/test -s build_type=RelWithDebInfo -s compiler.runtime=MT
```

After some digging, I believe the culprit is the `conan_set_vs_runtime` macro, generated by the `cmake generator`.

```cmake
macro(conan_set_vs_runtime)
    if(CONAN_LINK_RUNTIME)
        if(DEFINED CMAKE_CXX_FLAGS_RELEASE)
            string(REPLACE "/MD" ${CONAN_LINK_RUNTIME} CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
        endif()
        if(DEFINED CMAKE_CXX_FLAGS_DEBUG)
            string(REPLACE "/MDd" ${CONAN_LINK_RUNTIME} CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG})
        endif()
        if(DEFINED CMAKE_C_FLAGS_RELEASE)
            string(REPLACE "/MD" ${CONAN_LINK_RUNTIME} CMAKE_C_FLAGS_RELEASE ${CMAKE_C_FLAGS_RELEASE})
        endif()
        if(DEFINED CMAKE_C_FLAGS_DEBUG)
            string(REPLACE "/MDd" ${CONAN_LINK_RUNTIME} CMAKE_C_FLAGS_DEBUG ${CMAKE_C_FLAGS_DEBUG})
        endif()
    endif()
endmacro()
```

In my `test_package/CMakeLists.txt` I print the `CMAKE_CXX_FLAGS_RELEASE` and `CMAKE_CXX_FLAGS_RELWITHDEBINFO`:

> /MT /O2 /Ob2 /DNDEBUG
> /MD /Zi /O2 /Ob1 /DNDEBUG

One workaround would be to patch the release flags in every dependency's recipe, to pass the `"Release"` configuration to the CMake helper when `settings.build_type = RelWithDebInfo`.

**Comment by memsharded** [comment]
I think this can be fixed, extending the ``conanbuildinfo.cmake``to set ``CMAKE_CXX_FLAGS_RELWITHDEBINFO`` runtime too, wouldn't be that be the right approach?

Btw, I would recommend to move to the new ``conan create``command to create packages, ``test_package`` is about to be deprecated. Note that ``create``also run test_package if the folder is there.

**Comment by theodelrieu** [comment]
Yes I believe so, it'd be great to set `MinSizeRel` flags too!

Thanks, I usually use `conan create`, I was running `conan test_package -t` but didn't include that in my first post.

**Comment by memsharded** [comment]
Planning for 0.28, but that release is already very packed, might be delayed till 0.29

**Comment by theodelrieu** [comment]
No problem, thanks a lot!
