### ISSUE TITLE
env_info is not applied to test package

### ISSUE THREAD

**Issue by mikea** [conan-io/conan#1858]
(this is me again :)

I'm trying to set DYLD_LIBRARY_PATH in env_info but conan doesn't propagate the variable to test_package (at least, can't check other dependencies).

Simple test:

https://gist.github.com/mikea/edc4a2b7921616c86fa2f46a5690c516

In main conanfile.py:

```
    def package_info(self):
        self.env_info.DYLD_PRINT_ENV = "1"
```

If you print environment in test program, you wouldn't see DYLD_PRINT_ENV defined (and it is not applied either)

**Comment by memsharded** [comment]
I think the environment is not being correctly passed to the execution of the child process. Could you please try printing the environment in python inside the ``test()`` method launching the test?

**Comment by mikea** [comment]
If I add ` self.output.info(os.environ)` to test method, then the output has `DYLD_PRINT_ENV`: `u'DYLD_PRINT_ENV': u'1'` 

Those `u` prefixes worry me though, the rest of variables is not unicode:

`'PAGER': 'less', 'TMUX_PANE': '%14'`

Can this be the reason for not passing it through to `os.system`?

**Comment by SSE4** [comment]
I've faced the same issue recently. it seems like new OSX security enhancements - DYLD* variables are no longer inherited. the following workaround worked:
```
env = RunEnvironment(self)
with tools.environment_append(env.vars);
    self.run('DYLD_LIBRARY_PATH=%s ./test_package" % os.environ['DYLD_LIBRARY_PATH']
```

**Comment by memsharded** [comment]
Yes, that makes sense, thanks for the tip @SSE4 

@mikea if you please confirm this work, please tell me, and I will add it to the conan docs. Thanks!

**Comment by lasote** [comment]
@SSE4 Are you sure that you need the RunEvironment and the environment_append? This way doesn't work?

```
self.run('DYLD_LIBRARY_PATH=%s ./myexe" % os.environ['DYLD_LIBRARY_PATH']
```

**Comment by SSE4** [comment]
@lasote **RunEnvrionment** sets **DYLD_LIBRARY_PATH**, so it's needed for sure

**Comment by lasote** [comment]
But you are setting it directly in the `self.run` command, ¿?

**Comment by SSE4** [comment]
yep, you're setting it explicitly in command line, because it's not inherited from python to the test_package process.

**Comment by lasote** [comment]
So, why you need both the env and the command line one?

**Comment by memsharded** [comment]
But the OP is setting the DYLD_LIBRARY_PATH explicitly as an env-var in its package recipe. The ``RunEnvironment`` is needed to automatically add dependencies "bin" folders to the DYLD_LIBRARY_PATH, even if those dependencies didn't declare the environment variable.

**Comment by SSE4** [comment]
that's getting complicated...
lemme explain
1. in order to run binaries on OSX, you have to set DYLD_LIBRARY_PATH, as dyld doesn't find libraries near to the executable by default
2. RunEnvironment automatically sets DYLD_LIBRARY_PATH, according to the bin folders of dependent packages (in case of test_package, bin folder of package being tested)
3. after you run tools.environment_append, os.environ will contain DYLD_LIBRARY_PATH value set by RunEnvironment
4. at this point python (conan) process has DYLD_LIBRARY_PATH set. but running subprocess from python will not inherit DYLD_LIBRARY_PATH due to OSX security restrictions
5. so, you have to set DYLD_LIBRARY_PATH as part of command line, that way it will be set into child process

**Comment by memsharded** [comment]
Yes, but if the dependency has something like:

```python
 def package_info(self):
        self.env_info.DYLD_LIBRARY_PATH= os.path.join(self.package_folder, "bin")
```
Then, you don't need 2 and 3, the env-var should already be applied to the consumer package. Am i missing something, @lasote?

**Comment by lasote** [comment]
That's my point @memsharded. The env vars should be automatically applied, if the exe is not inheriting the DYLD_LIBRARY_PATH then use the `self.run('DYLD_LIBRARY_PATH=%s ./myexe" % os.environ['DYLD_LIBRARY_PATH'])` should be enough.

**Comment by mikea** [comment]
@memsharded @lasote I can confirm that `self.run('DYLD_LIBRARY_PATH=%s ./myexe" % os.environ['DYLD_LIBRARY_PATH'])` propagates `DYLD_LIBRARY_PATH` path correctly. I have also confirmed that non-DYLD variables propagate correctly as well. 

Thanks.

Obligatory SO link: https://stackoverflow.com/questions/35568122/why-isnt-dyld-library-path-being-propagated-here

**Comment by lasote** [comment]
Thanks, I've opened https://github.com/conan-io/docs/issues/339 to add some info in the docs

**Comment by memsharded** [comment]
Documented: http://conanio.readthedocs.io/en/latest/howtos/shared/env_vars.html#using-shared-libraries-from-dependencies
