### ISSUE TITLE
`conan create` did not clear old files

### ISSUE THREAD

**Issue by jinq0123** [conan-io/conan#1859]
I moved some files of my lib src and use `conan create jinq0123/testing` to re-create the package, but found old files are still there. `conan create` did not clear the old files.
```
Conan version 0.25.1
```

**Comment by memsharded** [comment]
Hi!
Could you please provide a reproducible example? A conanfile.py, files or repo. Also what do you mean with the "old files", which files, those in the conan cache? The exported files? The final package?

If you can, please also update to latest conan 0.27

**Comment by jinq0123** [comment]
I updated conan and found conan 0.27 has no such issue.
