### ISSUE TITLE
flag translation depending on compiler

### ISSUE THREAD

**Issue by ruipires** [conan-io/conan#1872]
Is there any way to convert flags defined by packages based on compiler type and version ?

I am targeting an older gcc compiler, that does not recognize the -std=c++11 flag (it still used the c++0x).
I depend on several packages that require c++11, and an incomplete c++0x implementation might just be enough (crossing my fingers).

I will have to hunt down each of those dependencies and adapt them to detect the compiler version and define c++0x instead of c++11.
I was just hoping there was some central mechanism to do the conversion.

I remember boost build had something similar, but it implied they needed to maintain some layer that would translate the user intent to specific compiler flags for each compiler.
This seems like an overkill, but I am always reminded of this when I need to port from gcc clang (that thankfully share most of the command line flags) to Visual Studio.

**Comment by memsharded** [comment]
Cant you just use the global settings for all packages, and then the individual settings for that one. Like, if it is binary compatible, you can do:

```bash
$ conan create -s compiler=gcc -s compiler.version=5.3 -s MyPkg:compiler=gcc -s MyPkg:compiler.version=4.9
```
Or something similar with ``-s compiler.libcxx=...```

Is that what you are looking for?

**Comment by ruipires** [comment]
Not exactly.

At least one package uses #ifdefs to either use boost or stl features, based on the standard version, so that will not be binary compatible (if it is compiled with c++11, its users have to enable c++11 also).

As far as the flags, I added the standard as an option, restricting the selection to only c++03 and c++11.
This is then passed as is to the compiler for building the lib, and added to the consumers of the lib via the cpp_info.cppflags.

My problem is that I now need to use c++0x instead of c++11, but just for some compilers.
Apparently up to gcc 4.6 it used c++0x instead (https://gcc.gnu.org/projects/cxx-status.html).

Since I restricted the options, I cannot pass c++0x as a valid option using the command line as you suggested (unless I relax the restriction ... maybe that would make sense ?).

**Comment by memsharded** [comment]
Maybe it depends on what you want to achieve. I am not sure that passing the c++ std to the consumer is the best approach, as it can easily lead to conflicts. As you are managing it as a setting, I would decouple it, and let each package set their own standard according to their own build scripts and behavior.

If you are fine with just translating the c++03 => c++0x for those older compilers, then, can't you just overwrite that behavior in your ``build()`` method? You should be mostly fine regarding binary package IDs. Which build system are you using? If you are using the ``CMake`` helper, then, changing behavior, or hacking into it is relatively simple.

**Comment by ruipires** [comment]
For the conversion from c++11 to c++0x I will do what you suggested, I was just hoping there was a different way.

As for passing the standard for the client, I started down this path because of conflicts due to [libc++ dual abi](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html).

I'm now wondering if this dual ABI issue is handled by the compiler.libcxx setting...

**Comment by memsharded** [comment]
Yes, totally. That is why ``compiler.libcxx`` is there. You can read more: 

- http://blog.conan.io/2016/03/22/From-CMake-syntax-to-libstdc++-ABI-incompatibiliy-migrations-are-always-hard.html (old, but still good)
- http://conanio.readthedocs.io/en/latest/reference/generators/gcc.html?highlight=libcxx
- CMake will also handle it for you: http://conanio.readthedocs.io/en/latest/reference/build_helpers/cmake.html?highlight=libcxx

Please tell me if you have any doubts wrt this. Thanks!

**Comment by ruipires** [comment]
This clears it up.
My conflicts were coming from another issue: [conan-boost](https://github.com/lasote/conan-boost) ( boost.build, really) doesn't use the CC and CXX env variables, and when cross compiling it was simply using the default (gcc).

Thanks for helping me make sense of this, the blog post was particularly helpful!
