### ISSUE TITLE
Update conan new to detect default profile

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1873]
Hi!

@memsharded commented that just `conan user` is not enough to trigger the default profile creation at first execution on new versions, the barbaric way in such case should be `conan profile new default --detect`.

If you check at [new_ci.py:84](https://github.com/conan-io/conan/blob/develop/conans/client/new_ci.py#L84), the command `conan user` is present as default.

Should it be updated?

Regards!

**Comment by memsharded** [comment]
I have had a look to this, I think it is fine as-is:

- Using the default profile is probably not the best idea in CI, if you want to be sure of what you are building and detect inconsistencies after updating CI servers
- Thus, auto-detecting a default configuration seems like an unnecessary thing. If for some reason the default is used, not a problem, it will be generated when needed.
- ``conan user`` is a good initial command, it creates the basic conan files, will fail if for some reason conan was not properly installed. Maybe it could be removed, but it is pretty harmless, so the benefits might be enough to keep it in the template scripts

WDYT?

**Comment by uilianries** [comment]
It sounds like good to me. 

I think `conan user` is good for now. The first build detects the default profile, so we don't need change anything.

Thanks for review this point.
