### ISSUE TITLE
is it possible to generate a file that references self.package_folder?

### ISSUE THREAD

**Issue by ruipires** [conan-io/conan#1876]
Following the issue I detected in #1872 , I am attempting to adapt my cross compiler package to supply boost with a valid user-config.jam file.

Sadly, my toolkit is very picky, and requires to be invoked with the full path. If I don't do this, it will fail to invoke other tools, even if they are in the path.
I have seen other complaints about similar problems on the net, so it seems like other cross compilers suffer from the same issue.
e.g.:
```
...
gcc.compile.c++ bin.v2/libs/wave/build/gcc-qrq/rls/adrs-mdl-64/lnk-sttc/thrd-mlt/wave_config_constant.o
Assembler messages:
Fatal error: invalid listing option `3'
libs/wave/src/wave_config_constant.cpp:17:19: fatal error: cstring: No such file or directory
...
```

I was hoping to keep changes to upstream conan-boost minimal (just accept environment CFLAGS and CXXFLAGS).

To do this I need to generate a user-config.jam file that looks like:
`using gcc : qoriq : /full/path/to/cross/compiler/powerpc-wrs-linux-gnu-g++ ;`

It is possible to use self.package_folder in the package_info method, but (understandibly) not on the source or package methods.
As such, I can't generate such a file.

Is there a way to do it that I am just not seeing ? Maybe some hook that allows me to generate files at package installation time ?

**Comment by lasote** [comment]
Hi! maybe I'm missing something, but the `package_folder` is present in all the methods during a package installation:

```
from conans import ConanFile, CMake, tools


class LibConan(ConanFile):
    name = "lib"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"

    def source(self):
        self.output.warn("source %s" % self.package_folder)
    def build(self):
        self.output.warn("build %s" % self.package_folder)
    def package(self):
        self.output.warn("package %s" % self.package_folder)
    def package_info(self):
        self.output.warn("package info %s" % self.package_folder)
```

`conan create kk/kk`

```
lib/1.0@kk/kk: WARN: source /Users/luism/.conan/data/lib/1.0/kk/kk/package/7fe67dff831b24bc4a8b5db678a51f1be5e44e7c
...
lib/1.0@kk/kk: WARN: build /Users/luism/.conan/data/lib/1.0/kk/kk/package/7fe67dff831b24bc4a8b5db678a51f1be5e44e7c
...
lib/1.0@kk/kk: WARN: package /Users/luism/.conan/data/lib/1.0/kk/kk/package/7fe67dff831b24bc4a8b5db678a51f1be5e44e7c
...
lib/1.0@kk/kk: WARN: package info /Users/luism/.conan/data/lib/1.0/kk/kk/package/7fe67dff831b24bc4a8b5db678a51f1be5e44e7c
```

**Comment by ruipires** [comment]
I'll need to recheck.
I could swear it was printing None in the other methods (except package_info).

**Comment by ruipires** [comment]
Figured out what I was doing wrong.

Since my toolkit is huge, the source method takes forever.
So I was trying to avoid the source() method and testing by running the commands separately.

In that situation:

```
conan install ..
...
PROJECT: WARN: package_info None
...

conan source ..
PROJECT: Configuring sources in /vagrant/modularized/test/build
PROJECT: WARN: source None
...

 conan build ..
Project: Running build()
Project: WARN: build None

conan package ...
PROJECT: Generating the package
PROJECT: Package folder /vagrant/modularized/test/build
PROJECT: Calling package()
PROJECT: WARN: package None

```

Running with create (or test_package) works as expected.

Thanks for helping clear this up, and sorry for the trouble.

**Comment by lasote** [comment]
We are improving the local commands, currently, not all of them accepts the possibility of injecting the package_folder, but we are thinking about it.
