### ISSUE TITLE
Package dirs (build, export_source, package, source) are changed on each rebuild when 'short_paths = True'

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#1881]
It's not a bug but it's really annoying when creating a package on Windows with `short_path = True`.
The `.conan_link` is changing on each rebuild so you have to constantly "resolve" the real dir name to open it in Explorer. Also you have to run `conan install` even if the package id (recipe) is not changed.

**Comment by lasote** [comment]
Would it work for you deactivating the `short_paths` when you are working with local conan commands? Or did you expect to keep the same short directory every time?  (I currently have no idea if one of those approaches are actually possible, I would need to take a look)

**Comment by DmitrySokolov** [comment]
I think, using of something like `os.mkdir(os.path.join(short_home, get_hash(recipe_name)))` instead of `tempfile.mkdtemp(dir=short_home, prefix="")` would work OK.

**Comment by memsharded** [comment]
@DmitrySokolov you mean like creating a package, removing it, and creating it again? Yes, the short paths will be different, but not sure why is this an issue, are you accessing directly the conan cache? Maybe the ``conan info --folders`` could help with this.

The thing with the short_paths folder name is that is quite hidden and decoupled with the conan logic, it would be a bit ugly to couple them. Note that ``get_hash(recipe_name)`` is not enough, you need both all the inputs (profile, settings, etc), as well as the full dependency graph to evaluate.

If you could tell a bit more about your flow, and why are you accessing directly conan cache folder, maybe there is a use case there that could be improved.

**Comment by DmitrySokolov** [comment]
My flow is
1. Change lib
2. Increase package version
3. Update package's `conanfile.py`
4. `conan remove`
5. `conan test_package`
6. `conan install`
7. Rebuild app
8. Repeat 3-7

I need to access conan package dir to detect what files were not copied to fix copy patterns. I use a complex structure (tree) of file masks to copy files, for instance
```
            files = {
                "include": {
                    "{root_dir}": {
                        "Kernel": ["Icon.ico", "VersionInfo.rc"],
                        "Kernel/Examples": "*",
                        "Kernel/Extensions": {"pattern": "*", "excludes": "Services/cache"},
                        "ThirdParty/curl/include/curl": "*.h",
                        "ThirdParty/FreeImage": "*",
                        "ThirdParty/tinyxml": "*.h",
                        "ThirdParty/ZLib": "*.h"}}}
            for item in get_copy_items(files):
                self.copy(item.pattern,
                          src=make_path(item.src.format(root_dir=self.root_dir), item.subdir),
                          dst=make_path(item.dst, item.subdir),
                          excludes=item.excludes)
```

Another annoying issue is Qt framework. When you rebuild it you have to manually
* start Qt Creator
* open Settings
* detect a new path to QtVerssion and fix it
* fix QtVersion in QtKit

**Comment by memsharded** [comment]
- I guess the ``conan remove`` is just to make sure cache clean, not strictly necessary.
- I would recommend ``conan create`` instead of ``conan test_package``. The second is about to be deprecated
- Is the ``conan install`` done in a different directory, with a different conanfile than the previous package? So you create a package, then go to the app that consumes that package?

I have checked it, just re-creating the package with multiple ``conan create`` wont change the folders, it will keep them. But internally, the "build" and "package" folders are completely removed, so you are safe that you don't need to do a ``remove`` yourself (which will destroy all references, and indeed create totally new folders).

**Comment by DmitrySokolov** [comment]
> I would recommend conan create ...
Great! I will use it. Since it's more clear that `test_package`.

> Is the conan install done in a different directory ...
No I use the same conanfile.txt.

> I guess the conan remove is just to make sure cache clean, not strictly necessary.
I checked conan 0.27 on macOS and `.conan/data/name/version/user/channel/package/id` dir is not deleted when performing `conan create` (so old files excluded from a recipe are not deleted). While on Windows it is deleted (at least when using `short_paths = True`).

**Comment by memsharded** [comment]
Yes, absolutely, short_paths only do something in Windows, in the other (sane) OSs, it does nothing at all.

Regarding the conanfile.txt, I don't get your layout, sorry. Do you have a conanfile.py and a conanfile.txt in the same folder? For what? (you can use conanfile.py also for consuming). Please detail your layout, and update me when you change to the ``conan create`` command, hopefully the workflow is improved and more clear with it.

**Comment by DmitrySokolov** [comment]
This issue is not actual anymore, I believe.

**Comment by memsharded** [comment]
Yes, the short paths were made deterministic in Conan 1.12
