### ISSUE TITLE
Factoring package configuration across sub-projects

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#1882]
Our pre-Conan directory structure looks like

```
/
    CMakeLists.txt
    proj-a/
        CMakeLists.txt
        common/
            CMakeLists.txt
            ...
        client/
            CMakeLists.txt
            ...
        service/
            CMakeLists.txt
            ...
        test/
            CMakeLists.txt
            ...
    proj-b/
        (same layout as proj-a)
    
    ...
    
    proj-h/
        CMakeLists.txt
        ...
    
    ...
    
    proj-x/
        proj-x-a/
            (same layout as proj-a)
        proj-x-b/
            (same layout as proj-a)
            
    ...
```

The root `CMakeLists.txt` looks like:

```
cmake_minimum_required(VERSION 3.5)
project(codeword)
        
set(CMAKE_CXX_STANDARD 14)

include_directories(${CMAKE_SOURCE_DIR})

# Third party libraries
set(LIB1_DIR /path/to/lib1)
set(LIB1_INC_DIR ${LIB1_DIR}/include)
set(LIB1_LIB_DIR ${LIB1_DIR}/lib)
set(LIB1_LIBS ${LIB1_LIB_DIR}/lib1a.a ${LIB1_LIB_DIR}/lib1b.a)

... same thing for LIB2, LIB3, etc)

# Sub-projects
add_subdirectory(proj-a)
add_subdirectory(proj-b)
...
add_subdirectory(proj-h)
...
add_subdirectory(proj-x)
```

There are about 50 top-level projects ranging from single-directory libraries to sub-systems nested multiple directories deep.

One of the drawbacks of this approach is that all subprojects have to use the same versions of packages (either internal libraries that are compiled from source or third-party packages defined in the root `CMakeLists.txt`.  Ideally we could define default versions of packages for the entire codebase but projects could override the defaults.

Our current setup works well for CLion because there is one `CMakeLists.txt` and build directory, and CLion has a view over the entire codebase.  We could follow the same basic approach with a root-level `conanfile.txt` but how would we override package versions at the project level? 
We could have a `conanfile.txt` and build directory per project but then there would be a lot of duplication and a tendency for projects to fall behind upgrading packages.

I'm interested in getting feedback as to how Conan users are approaching this problem.  I have some ideas for custom scripts and workflow but I'd like to stay as close as possible to vanilla Conan.  
This is also related to #1377, as a developer can be working on multiple components at the same time, so the project-local version of a "package" might actually be a sibling project directory.

**Comment by memsharded** [comment]
I understand your previous layout with CMake, but not sure about your current goal with conan. The idea with conan (actually with any package manager), is that you work on a package level, not on the whole project at once. It is possible to work in parallel in several packages, using some "local" conan commands.

What do you mean with such a "root level" conanfile.txt? If you want to override the package dependencies from the project, it is possible with the ``override`` dependency declaration: http://conanio.readthedocs.io/en/latest/reference/conanfile/attributes.html?highlight=override#requires

Please tell me a bit more about your intended layout and flow with conan:
- Do you still want to be able to work on the whole project at once?
- It would be enough being able to work on individual packages? Or maybe just a few packages at once?
- When you say "a ``conanfile.txt`` and build dir per project => lot of duplication and tendency to fall behind upgrades", what do you mean, per project or per package? Could you please explain a bit?

**Comment by sourcedelica** [comment]
Ideally we would be able to work on the whole project at once, since that is what we currently doing with CLion.   To load up the whole project we point CLion at the root `CMakeLists.txt` and it pulls in the tree using `add_subdirectory` commands.   

The third party libraries are currently defined once in the root `CMakeLists.txt` and are used in all of the child projects.   For example, our root `CMakeLists.txt` defines some variables pointing to Boost 1.55.  We want to let child projects use different versions of Boost if they want to, but in most cases they will use the default.  

A project also will depend on a number of internal libraries.  Currently the project is building all of the internal libraries from source.  We are moving to using Conan-packaged versions of the libraries.

Based on the above requirements I don't think that working at whole-project level is possible.  The option that I'm considering now is one `conanfile.txt` and build directory per project.  A project is typically a set of related subdirectories.   For example, `my-project` is a directory at the top level:

```
my-project/
    CMakeLists.txt
    conanfile.txt
    build/
    client/    
        CMakeLists.txt
        conanfile.py
        (sources for client library/package)
    common/
        CMakeLists.txt
        conanfile.py
        (sources for common library/package)
    service/
        CMakeLists.txt
        (sources for service executable, no package)
```
    
In the case the `conanfile.txt` would define packages that all of the project subdirectories use. The `build` directory would be used to build the `client` and `common` libraries/packages and the `service` executable.

There will be quite a bit of overlap between each project's `conanfile.txt`.   For example, most of them will have `Boost/1.55@...` in them.  What I'd really like to avoid is having a project get stuck at 1.55 when everyone else has upgraded.  I think `conan alias` could help here.  I could set up a `Boost/latest` in our repo and most projects can use that.

**Comment by memsharded** [comment]
I think that some of your requirements might be mutually exclusive, e.g.: you say that child projects might use different versions of Boost, but if I understand the structure of your project, you might have ``client`` depends on ``common``, ``service`` also depends on ``common``. So it doesn't seem possible that ``common`` will use Boost 1.56, and ``client`` use Boost 1.55, etc. Am I missing something?

Maybe the key here is to understand the user-stories, not the project layout. Because the thing when you really modularize/componentize a project, is that it is splitted in parts, and they can actually evolve independently, this is the main reason for such modularization! If you really need to evolve everything at once, maybe the modularization has to be different.

In most cases of conan user-stories, development work is done at the package level. By definition a package is an independent unit of work, with its version number, its definitions, its build system, its own test, and can be developed and released independently. If a certain ticket implies modifications in many packages at once and cannot be splitted in one ticket per package, probably the modularization is not real.

Maybe it would be good to discuss some of these things, please feel free to give more details here about the expected user-stories. Or maybe you want to join us in slack for discussion with us and more conan users. Please send an email asking for details. Thanks!

**Comment by sourcedelica** [comment]
Ahh, sorry about the confusion.   Everything in a project would use the same versions.   So in this case, everything in `my-project` would use the versions defined in `my-project/conanfile.txt`.

Since working at whole-project level (using a root-level `CMakeLists.txt`) doesn't appear to be feasible, the big picture is looking like this:
```
/
    my-project/
        conanfile.txt
        common/
        ...
   library-project/
        conanfile.txt
       ...
    their-project/
       conanfile.txt
       common/
      ...
    ...
```

Each project will have its own `conanfile.txt` to define the packages it uses.  There will be overlap in the `conanfile.txt` files in the different projects.   I was wondering if there were ways to factor out the commonality to a higher level.   I think using `conan alias` is a good start.

**Comment by sourcedelica** [comment]
This mixes too many things together and is too complicated to think about.  I'll file simpler issues later.

**Comment by memsharded** [comment]
Great, thanks for following up and closing.
Yes, it is really appreciated if it can be split in simpler, more focused issues. The chances to be properly managed in this flood of issues is much higher. Cheers!

**Comment by icaroalvarez** [comment]
Hi @sourcedelica, I facing the same problem trying to install the dependencies of my project with conan using "nested project directories" pattern. The fact this is not easy to explain in this issue makes my wonder if the pattern is not the best way to do things but I've always worked in C++ projects having a top project with the executable and a few subprojects with different libraries that can be shared with other "executable projects". 

Well, in my case I ended up including this:

1. Each project has its own conanfile.txt.
2. I have a script that executes conan install in each project and generate its own conanbuildinfo.cmake (in a .conan folder inside each project)
3. In the top project I include all conanbuildinfo.cake
4. Finally I use the conan_basic_setup(TARGET) macro also in the top project CMakeLists.txt
5. Running conan_basic_setup(TARGET) in the subprojects is prevented checking if it has a parent directory (with cmake macros).

Do you consider this a good approach or did you manage to find another way?
Cheers!
