### ISSUE TITLE
Generators: cmake vs cmake_multi [discussion]

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#1883]
Hey @lasote ,

At the moment i try to get my head around multi configuration support in conan (as you can see in my issue #1878). I'm a little bit confused what the "right" path is.

I use most of the conan recipes with cmake, so i mostly use the `cmake` and the `cmake_multi` generators. With `cmake_multi` i have the multi config support for Visual Studio, and thats great. Now i'm confused about the Multi-Config packaging, which can be used with the `cmake` generator (as far as i understand).

I understand the Multi-Config packaging means that there are multiple configs in one conan package, but i see no mutli-config package anywhere (and your recpies also only support single packaging).

So which one is "the future"? Is there a plan to get rid of `cmake_multi` in the future (and integrate it into the `cmake` generator.

Greetings  
Tonka

**Comment by memsharded** [comment]
IMO, the default packaging approach, i.e. "single-conf" packaging is a sensible default, and I think it will probably remain the same. "Multi-config" packages support are there for people wanting to use them, most of its usage is inside companies, and not in public repos.

The ``cmake_multi`` is just a helper generator to consume "single-conf" packages, and being able to switch configuration from the IDE without going to the command line to issue a "conan install".

There are no plans to get rid of ``cmake_multi``, it is useful as-is for some people, and it is not possible to integrate it in the ``cmake`` generator because it is quite a different and incompatible approach. Internally, ``cmake_multi`` basically includes 2 single ``cmake`` generated files, one for Debug and one for Release.

Please tell me if this helps or if you have some further question.

**Comment by tonka3000** [comment]
Thanks for your answer.

I'm also try to use conan inside the company i'm working at, so that's also why i try the mutli-package approach (mainly because of Visual Studio). But this approach is much harder then the single conf approach, because i have to make some hacks to make it work (see #1878) (ignore the buid_type, manually fixed compiler.runtime, etc.), which is kind of strange. I'm also have to overwrite the build_id function to avoid multiple packages with exactly the same content.

I'm not sure if i can mix singe-conf packages and multi-conf packages without troubles, like f.e. i use OpenSSL and gtest from conan-center alot, which are single-conf packages.

So I'm not 100% which path i should use. Can you explain me why companies tend to use multi-conf packages over single-conf aside from having multiple conf binaries in the same package.

**Comment by memsharded** [comment]
No, companies don't tend to use multi-conf, just a very small fraction of them would. The majority also uses single-conf packages.  And that is the main reason, just a convenience for lazy developers, who won't use the terminal at all, just the IDE. Probably, when a Visual Studio plugin is created, multi-config packages are not necessary at all.

Also, the single-conf approach has other advantages, e.g.: debug packages can use different dependencies (logging, tracers, analyzers, etc) that the release packages. 

In theory, it should be possible to mix single-conf and multi-conf packages, shouldn't be an issue, but please report if something fails.

Just for pure Visual Studio consumer, you might be interested: you also have the new ``visual_studio_multi`` which in fact works for 4 configurations, also 32/64 bits besides Debug/Release, and is directly pluggable into VS.

**Comment by tonka3000** [comment]
> No, companies don't tend to use multi-conf, just a very small fraction of them would. The majority also uses single-conf packages. And that is the main reason, just a convenience for lazy developers, who won't use the terminal at all, just the IDE. Probably, when a Visual Studio plugin is created, multi-config packages are not necessary at all.

Good to know.

> Also, the single-conf approach has other advantages, e.g.: debug packages can use different dependencies (logging, tracers, analyzers, etc) that the release packages.

Thats a big plus for single-config

> Just for pure Visual Studio consumer, you might be interested: you also have the new visual_studio_multi which in fact works for 4 configurations, also 32/64 bits besides Debug/Release, and is directly pluggable into VS.

We've started with "Visual Studio only" 8 years ago. If the project is small and only need one compiler, it works, but when the project grows and you have to support multiple compiler (and when it's only windows), then Visual Studio alone is super painful. So we switched to cmake and never looked back (cmake makes many things really easy, f.e. Windows Installers). A user can use cmake gui i've he/she want, and with the use of [cmake-conan](https://github.com/conan-io/cmake-conan) it feels like gui style :-D

I will go the single package way, because it feels more like the right way and cmake_multi make the config switch easy.

btw: Thanks for that awesome project 😄

**Comment by memsharded** [comment]
Excellent, thanks for telling. Feel free to close the issue, if already done, you can reopen or just comment on it anytime you want. Thanks!
