### ISSUE TITLE
Determine if tool/application exists and use package if it does not

### ISSUE THREAD

**Issue by L-M-V** [conan-io/conan#1890]
Is there anyway to determine if a particular application already exists on the current build machine?

I'm trying to package up an existing library and it stores its source releases in a tar.xz format. On windows, I'd like to use 7z to extract this file, however it seems like overkill to add:
`build_requires = "7z_installer/1.0@conan/stable"`
if they already have 7zip installed and in the path.

Ideally I'd like to something similar to:
```
    def build_requirements(self):
        if os_info.is_windows:
           existsReturnCode = self.run("where 7z"); # Equivalent to UNIX which
           if existsReturnCode == 1: # Doesn't exist
              self.build_requires("7z_installer/1.0@conan/stable")
           else:
                  # Check version if necessary etc...
```
I'd also like to do something similar for Perl. 

Is something like this possible without having to install something like chocolatey? I'd love to make the initial install as quick as possible (the perl download for example is 100mb and I only need it for a single call).

**Comment by SSE4** [comment]
you can use `tools.which` I believe

**Comment by L-M-V** [comment]
@SSE4  I get the following:
```
ERROR: PROJECT: Error in build_requirements() method, line 10
        tools.which("cmake.exe")
        AttributeError: 'module' object has no attribute 'which'
```

**Comment by lasote** [comment]
It's not released yet. Will be in 0.28

**Comment by memsharded** [comment]
Closing this as stale.

In any case, the idea is that recipes do not check the existence of tools in the system. If they want, they define a ``tool_requires()``. If a profile wants to specify they have that tool in the system, they can do it via ``[system_tools]``: https://docs.conan.io/2/reference/config_files/profiles.html#system-tools
