### ISSUE TITLE
launch `conan install ../` from existing visual studio project msbuild chain?

### ISSUE THREAD

**Issue by jeroendv** [conan-io/conan#1891]
the documentation suggest the following  3 step approach for integration of into an existing Visual Studio project

1. add conanfile.txt to project
2. manually install dependencies
```mkdir debug32 && cd debug32
$ conan install .. -s compiler="Visual Studio" -s compiler.version=15 -s arch=x86 -s build_type=Debug
$ cd ..
$ mkdir debug64 && cd debug64
$ conan install .. -s compiler="Visual Studio" -s compiler.version=15 -s arch=x86_64 -s build_type=Debug
$ cd ..
$ mkdir release32 && cd release32
$ conan install .. -s compiler="Visual Studio" -s compiler.version=15 -s arch=x86 -s build_type=Release
$ cd ..
$ mkdir release64 && cd release64
$ conan install .. -s compiler="Visual Studio" -s compiler.version=15 -s arch=x86_64 -s build_type=Release
```
3. include property files in project for each configuration

Step 1&3 needs to be done once and the changes to the *.vcxproj file can then be committed to the VCS. My question is how can I configure the visual studio project to *automatically* execute the commands of step 2 as part of the build process? 

The goal is to be able to do a clean checkout open the solution file and press F5. At which point I would expect to see the following:
1. the various conan install -s .... commands  are invoked to download the deps if they are not yet installed on the system
1. build the project
1. run the project.

if I set the code from step 2 as a pre-build step command then the build fails however because it seems like it does not reparse the project file for the newly 'conan install ../'  generated property files. rebuilding a second time succeeds because the conanbuildinfo.props exist at that point. Having to build twice is not really acceptable though.

**Comment by memsharded** [comment]
I think you will like the ``visual_studio_multi`` generator that has been contributed to the source code, is already merged to develop and will be in next conan 0.28 release: https://github.com/conan-io/conan/pull/1831

It automates further the creation and loading of the conanbuildinfo.props for all 4 configurations.

However, it doesn't fully automate the installation of dependencies. We have tried to configure some MSbuild job to do it, without success so far, mainly for the reason you found: VS doesn't reload properties automatically. We haven't found a workaround yet. The dependencies won't be built twice if that is what you meant. If you are talking about the consumer project, I guess it won't either, because it will fail fast if dependencies are not found.

Probably the solution could be this: there is an initiative from @solvingj of creating an addon for VS that would automate the process.

**Comment by jeroendv** [comment]
the 'visual_studio_multi' generator is definitely an improvement ;-)
(when do you think 0.28 will be releases? weeks, day, months?)

I'm not sure which project of @solvingj  you are referring to though? can you be more specific?

**Comment by memsharded** [comment]
It already has a date: https://github.com/conan-io/conan/milestones ;)

Uhmmmm, maybe it is not in github, but has been mentioned elsewhere, maybe in the CppLang slack team... are you in that slack team?

**Comment by jeroendv** [comment]
The following msbuild target might be useful though.

```
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="EnsureConanDeps" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references conan package(s) that are missing on this computer.
you can manually install them for all required profiles as follows:
$ conan install ./ -pr profile1 -pr profile2
</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('conanbuildinfo_multi.props')" Text="$(ErrorText)" />
  </Target>

  <Import Project="conanbuildinfo_multi.props" Condition="exists('conanbuildinfo_multi.props')" />

</Project>
```

* the import clause has a condition so that the project can be loaded in visual studio, even if 'conanbuildinfo_multi.props' does not exists.
* when a build is started  (e.g. F5) it will *fail gracefully* with a useful error message.

the dev still needs to manually install the packages and generate the property file but at least this way there is a reminder if he forgets to do so in the first place.

**Comment by MichalnRnd** [comment]
Hi
We deleted the prop file (del conanbuildinfo.prop) and to run conan install in the pre-build event.
In the first build the build failed, then we rebuild and it succeeded. Do you have any idea why it is fails on the first time?

**Comment by jeroendv** [comment]
first builds sequence:
* parse the project files import all the property files
   * Not the conanbuildinfo.props because it doesn't existst yet.
* invokes `conan install` which  
   * fetches and installs the packages \
   * it also creates the conanbuildinfo.prop file.

then the build fails because it 

When msbuild starts it starts by parsing all project files and importing all prop files.
At this point the conanbuildinfo.prop does not exists, so it is not parsed and not used.

In the prebuild step `conan isntall` will cause conanbuildinfo.prop to be generated, but it is already to late. msBuild does not reparse prop files during a started build to check if they changed or were added.

Hence the build will fail. But the second one will succeed, because not the necessary prop files all exists at the moment msbuild starts and parses them.

**Comment by AbrilRBS** [comment]
Closing as solved with the introduction of the [conan-vs-extension](https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension), which allows seamless integration of Conan into VS, let us know what you think!
