### ISSUE TITLE
Best way incrementing package version

### ISSUE THREAD

**Issue by zabeloliver** [conan-io/conan#1894]
Hi, 

i have some packages which contains binaries like toolchains. 
Let say i have a GCC 4.9 packed: 
```python
    def source(self):
        self.run("git clone ssh://mygithost/test/cypress-arm-gcc.git")

    def package(self):
        self.copy(pattern="*", src="cypress-arm-gcc-49", dst="toolchain", keep_path=True)

    def package_info(self):
        self.env_info.TOOLCHAIN_PATH = os.path.join(self.package_folder, "toolchain")
```
In this case a have a repo with just the 4.9 toolchain inside.  Now, someone could change the repo and the result of the package on an new install would be different. 
If i now want to add e.g. GCC 6.1 i would add this in a different folder in the repo. So checkout time increases for both. 

What is the best approche here? Using tags to checkout? Different repos? Is there a best approch of how to increment package versions?

Thanks a lot for the good work and help!
Oliver

**Comment by memsharded** [comment]
I guess that your toolchain package will use the versions as ``gcc/4.9@team/stable`` and ``gcc/6.1@team/stable`` or something like that.

In that case, the first important thing is that it could be better not be using the ``source()`` method for that, as that is supposed to be common to all different variants/configuration of the package. So if you were to create a toolchain for example with an option for "toolchain with seh exceptions and posix threads", then, you might want to checkout a different branch, but you couldn't as the source for the first one has already been defined.

So you can perfectly use the``build()`` method for it. Read it as you are "building" the package, not really building libs from source code. Building the package can perfectly include running unit tests, for example.

Then, it is important how you will manage the recipe for the toolchain itself. You should put it in a repo. Then you can manage a branch in the repo for each gcc version. In this case, you would have different versions of ``build()``:

```python
def build(self): #in the 4.9 branch
     self.run("git clone ... && cd repo && git checkout 4.9")
```
and
```python
def build(self): #in the 6.1 branch of the recipe repo
     self.run("git clone ... && cd repo && git checkout 6.1")
```

Or if you just want to have a "master" branch of the recipe, and have the different toolchains in different branches, then:

```python

class Mytoolchain(ConanFile):
     name = "gcc"
     # version, not necessary to define, will be in command line
    def build(self):
         if self.version = "4.9":
             self.run("git clone ... && cd repo && git checkout 4.9")
         elif self.version = "6.1":
             self.run("git clone ......................... checkout 6.1")
```

Then in command line:
```bash
$ conan create gcc/4.9@user/testing
$ conan create gcc/6.1@user/testing
```

If you are concerned about git cloning being too slow (only necessary for creating the packages though), you can maybe play with ``--depth``, or with sparse checkout: https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository

Please tell me if this helps :)  Thanks!

**Comment by zabeloliver** [comment]
Hi, thanks for your answer! That helps a lot! I will try it and ask again noob question if i need help ;) 
Oliver

**Comment by memsharded** [comment]
Sure, anytime, glad to help. Feel free to re-open this issue, just comment, or open a new one as necessary, cheers!
