### ISSUE TITLE
conan install: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#1896]
Hey,

i've get the following error during install a recipe package

```
VTK/6.1.0@tonka/testing: Looking for package 5c69f02091d8894f73681847d8032342e2037b6f in remote 'local'
Downloading conanmanifest.txt
[==================================================] 204.6KB/204.6KB
Downloading conaninfo.txt
[==================================================] 445B/445B
Downloading conan_package.tgz
[================================================= ] 22.0MB/22.4MB
VTK/6.1.0@tonka/testing: WARN: Binary for 5c69f02091d8894f73681847d8032342e2037b6f not in remote: Error while downloading/extracting files to C:/.
conan\b4fl7g5z\1
Compressed file ended before the end-of-stream marker was reached
```

It's the Release version, the debug version of the package works normally.

I can download the manifest and the info file normally, the download progressbar is not full (22.0/22.4), but (like the error message say) unzip does not work.

The conan server run private on Windows 7 x64. I can unzip the package with 7zip without a problem, but with the warning
```
Warning
Can not open the file as [gzip] archive
The file is open as [tar] archive
```
I get this warning for all conan packages, so it could be normal on Windows version of 7zip.

I can also download the file (i get the url via CONAN_TRACE_FILE file) and extract it with 7zip, works with the same warning. Is there any bug of the download-libs from conan?

Any idea whats wrong here?
Does conan check the hash of the uploaded file after the upload?

I use latest  conan 0.27

Greetings  
Tonka

**Comment by memsharded** [comment]
Indeed very weird. No idea of what could be. Some questions:

- Is it absolutely reproducible? Does it happens always exactly the same?
- If that is the case, can you just zip the whole package from the Server (.conan_server) folder, and send it to me for inspection?
- Can you see the traces from the server? Any kind of error or warning regarding the transfer?
- I think we have changed the way packages are downloaded, because some problems with huge files were reported. This is not the case, but maybe you could try running from sources, latest develop branch?
- Conan installed from pip or from the installer? Which python version are you running? Can you also check your python ``requests`` library version in the client? (with ``pip list``)

Feel free to send private info by email to info@conan.io. Also, please tell if you want to connect by chat, at some point it might be useful to do some live-debugging.

**Comment by tonka3000** [comment]
With the lastest develop branch i get the follwoing error now

```
VTK/6.1.0@tonka/testing: Retrieving package 5c69f02091d8894f73681847d8032342e2037b6f
VTK/6.1.0@tonka/testing: Looking for package 5c69f02091d8894f73681847d8032342e2037b6f in remote 'local'
Downloading conanmanifest.txt
[==================================================] 204.6KB/204.6KB
Downloading conaninfo.txt
[==================================================] 445B/445B
Downloading conan_package.tgz
[================================================= ] 21.3MB/21.7MB    ERROR: Download failed, check server, possibly try again
Transfer interrupted before complete: 22609128 < 22776287. [Remote: local]
```

> Is it absolutely reproducible? Does it happens always exactly the same?

Yes

> conan installed from pip or from the installer?

From pip

> Which python version are you running?

with latest python x64 3.6.3

>  Can you also check your python requests library version in the client? (with pip list)
2.18.4

> If that is the case, can you just zip the whole package from the Server (.conan_server) folder, and send it to me for inspection?

Do you mean the whole VTK directory (with all packages, etc.)? It has btw no dependencies.

> Can you see the traces from the server? Any kind of error or warning regarding the transfer?

No. Thats the next thing i want to check out.

**Comment by tonka3000** [comment]
So, locally i fixed my problem. It was the proxy. I forget to insert an no_proxy exception.

But the problem on my ci-servers (gitlab-ci) still exists with a slightly different error message (using conan-package-tools)
```
Downloading conan_package.tgz
ERROR: Download failed, check server, possibly try again
("Connection broken: ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None)", ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None)). [Remote: upload_repo]
conan-center: https://conan.bintray.com [Verify SSL: True]

conan-transit: https://conan-transit.bintray.com [Verify SSL: True]
```
I have a german windows os, so `Eine vorhandene Verbindung wurde vom Remotehost geschlossen` means `a existing connection was terminated by the remotehost`. This feels like the same proxy problem, but i have definetly a no_proxy environment variable set for my conan server.

Could it be that conan-package-toos/conan/python ignores my no_proxy setting?

**Comment by memsharded** [comment]
Could be something was failing, how have you configured the no_proxy exception? Just for the bintray repos? Could you please specify your conan.conf here?

So now, the packages from your local server are being retrieved ok? As above, is the above error happening always?

**Comment by tonka3000** [comment]
It seems that the (company) proxy sometimes terminate my connection. It seems that when i use an ip address i could reach the local (intranet) server trough the proxy, which is very interessting from a technical perspective because this would not be possible with a dns name. I switch from hostname/dns to an ip address, because gitlab-ci runner seems not respect the no_proxy environment variable (but i think it is not the problem from the gitlab-ci server, i think the windows os or a python lib is mabye the problem).

My setup is straight forward:
I set following environment variables

|env-var|value|
|-|-|
|http_proxy| path to the proxy|
|https_proxy|path to the proxy|
|no_proxy| my no proxy setup f.e. localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,internalgitlab,www.internalgitlab.com,conanserver,www.conanserver.com,http://www.conanserver.com,172.20.15.161,http://172.20.15.161|

As you can see i have different version of same same server, because i've got error where these names occured. I've also switch the address variable in the conan_server conf to the ip address, without that it does not work to upload.

I think also with the ip and the no_proxy env-var im going through the proxy, which i can not understand.

Do you have any idea how i can test, log the behaviour with conan? Can i check if conan is using the correct no_proxy variables? How can i check if i'm contacting the proxy instead of a direct connection.

**Comment by tonka3000** [comment]
I can no produce that problem localy.

It is a two side problem, one from conan and one from our proxy. It seems that our proxy has some kind of protection, if it "see" a maybe danger stream, it will terminate the connection.  
But the problem lies on conan (more probable on it's dependencies) because conan seems to totally ignore no_proxy env variable on windows.

When i use cntlm as my local proxy and set a no_proxy exception in cntlm, cntlm will directly contact the server without any interrupting proxy (cntlm does not check the content) and everything works, but when i use the normal proxy directly it fails.  

So that means that any request from conan go trough the proxy (when one is set) regardless of what's in the no_proxy variable, which is a very bad behaviour on windows. So, i you have an non interuptable, everything works (but you will definetly will have a speed problem or when proxy dies, everything fails).

So i think the problem lies in the usage of the requests lib or a bug in it.

Maybe i depends on the internet explorer settings. I read in some requests blog post, that requests will sometimes use the setting from the internet explorer on windows. Our company has make an infrastructure change and now it's not important to set the proxy in the internet explorer, so the option is off by default. Maybe request overwrite the settings with these settings (which our off in our case).

Can you check if the proxy variable is really used by conan, mabye there is a special switch for that in requests lib.

**Comment by tonka3000** [comment]
Bad news. It's a conan bug (or the using of requests).

I've tested the requests library standalone, and it works as expected.

I've tried the same with conan and it fails. Conan ignores the `no_proxy` variable (You use it in the code but i can't find the point where something went wrong). I've tried to fix the conan code myself but it is very complex in that area, but i can give you a simple example that you can create a unit test for it.

1. set `http_proxy` to f.e. `http://mynonexistingproxy` (it's important that it does not exist)
2. set `https_proxy` to the value of `http_proxy`
3. set `no_proxy` to `yourconanserver`
4. try to install an existing binary from your conan server, which is the same server as in `no_proxy`

Result:  
it will fail, but it should not, because it is in `no_proxy`. So conan seams to always route through the proxy in that case

Expected:
The installation should work because no proxy is involved.

I hope you can find the bug, because for companies that means that install internally can fail (if their proxy thing that the is "something bad" in the binary) or simply for performance reasons (maybe single point of failure).

Greetings
Tonka

**Comment by memsharded** [comment]
Thanks for the detailed report. Yes, could be a bug, but cannot figure out yet.

All of them are also managed by the ``python-requests`` library as environment variables. Could you try to remove them from the conan config, and defined them as env-vars, then try again? The result should be the same as using the requests library alone.

**Comment by memsharded** [comment]
Labelling as bug, scheduling for 0.29, though if we can come with something, might try to put it into 0.28 next week.

**Comment by tonka3000** [comment]
I'm only using only env variables, no conan config stuff for proxy things.
I've already tried requests alone, but without a session as in conan. Without a session it works as expected.with a session would be interesting if it works.
I've checked the Conan source code multiple times, but the variables, which requests get from you seems to be correct.
The only real difference is that Conan use the Session class from requests.
If you have any idea what's wrong, keep me up to date so I could help you with an PR, testing or anything like that.
It would be interesting if you can reproduce the proxy error like I explained in my last post on your machine.

**Comment by memsharded** [comment]
I am checking the source code of requests and a couple of other things.

If you are not using the conan configuration, and using OS environment variables, you need to may need to completely remove the ``[proxies]`` section, including the header from the ``conan.conf``. Can you please check what is in your current conan.conf?

**Comment by tonka3000** [comment]
Good news. Removing the complete section seems to resolve the problem. My conan conf looked like following

```
[proxies]
# Empty section will try to use system proxies.
# If don't want proxy at all, remove section [proxies]
# As documented in http://docs.python-requests.org/en/latest/user/advanced/#proxies
# http: http://user:pass@10.10.1.10:3128/
# http: http://10.10.1.10:3128
# https: http://10.10.1.10:1080
#http: http://user:mypwd2112@proxy:8080
#https: http://user:mypwd@proxy:8080
```

Now when i'm remove this code completly it works locally. But i could not try that on the ci-server, but i think that's also the problem for the ci stuff.

**Comment by memsharded** [comment]
Yes, this is great news!!

And I think is more or less consistent:

- If the ``[proxies]`` section is there, it will try to use the system proxies
- Your configuration is not system-level, it is env-vars that affect only the ``python-requests`` library.
- Removing ``[proxies]`` basically does nothing, so if it happens that the environment is the right one, it will work

So, then it seems that both options are valid:
- Remove ``[proxies]`` and use environment variables for ``python-requests`` library configuration
- Use ``[proxies]`` section and define there the configuration instead of env-vars.

What do you think? Could this issue be closed?

**Comment by tonka3000** [comment]
I understand your more or less consitency, but it leads to some tricky behaviour.

Most applications, tools etc mostly use environment variables for proxies. I create a new conan home on every ci run and conan set the [proxies] section for me automatically, so it will by default always use the system proxy. It would be nice to have any kind of possibility to overwrite the default behaviour without manipulating the conf file "manually", which is really hacky in ci, espacially windows.

F.e. an environment variable like CONAN_PROXY_SYSTEM (true,false  or. system,env) which would be nicely controlable via ci and/or a varible like that in the conf file in the proxies section.

I think it is not the best default that a empty section in the config file represents the system proxy, a seperated variable like explained above would be much more expressive, what do you think about that?

**Comment by memsharded** [comment]
Maybe you could use:

```bash
$ conan config rm proxies
```
This is also easy to do in CI

Also, if you want to configure your proxies in ``conan.conf`` , you can do it easily with 2 methods:

```bash
$ conan config set proxies.no_proxy=url1,url2
$ conan config set proxies.http=...
```
or using the conan config install feature:
````bash
$ conan config install <url to git repo or zip file>
```
And you will have the proxies section configured in that repo. This is in fact a suggested way to do this, as it is easily reproducible, not only for CI, but also for developers machines. Also, easy to change, update, etc.

**Comment by tonka3000** [comment]
Oh, that
conan config rm proxies
looks nice. I will give it a try tomorrow. Does the conan config rm return a returncode of non-zero if the proxies value does not exitsts in the conf file (only to make sure that it does not fail if you maybe decide to remove the section by default in a future release)

conan config install sounds also like a nice option, esacially for dev machine.

 I'm generally not the biggest fan of putting IT infrastructure things like the proxy settings in my ci file (gitlab-ci, travis, etc.), i mostly use project wide env vars wich are not set in the file. With that strategy i can switch infrastructure thing project wide without touching any file. It's also easier to share the repo between different IT infrastructures, which could have different proxy settings.

**Comment by memsharded** [comment]
Yes, that is exactly the purpose of ``conan config install`` :)

So, ``conan config rm`` will fail and return an Error if the section or item does not exist in the conan.conf, yes.

**Comment by tonka3000** [comment]
conan config rm proxies solves my "problem". Thanks for such great support.
