### ISSUE TITLE
Artifactory pipeline plugin doesn't respect CONAN_USER_HOME

### ISSUE THREAD

**Issue by CausticYarn** [conan-io/conan#1897]
The create conan command from the Artifactory pipeline uses a temp directory that appears to come from the Java IO library.  I can't think of a great way to clean up after a build, since the DSL does not seem to expose the path, and trying any kind of bulk erase on the temp directory might affect running jobs.  It doesn't take too many builds of Boost to fill up a server's hard drive.

It would be ideal to be able to specify CONAN_USER_HOME and have the plugin respect it, so that you can make it a subdirectory of the workspace, and recreate the workspace on every build.

Somewhat related to this, I have to use "short_paths=True" in order to get Boost to build.  Since this lives outside the workspace, I was wondering if there was an easy way to get this path in order to clean up after the job runs.

**Comment by memsharded** [comment]
Regarding the short_paths, it is always stored in ``C:/.conan``, or the same disk unit as the main storage. It can be also modified using env-var ``CONAN_USER_HOME_SHORT``.

Wrt the  DSL temp dir, yes, we have to look into it, thanks for reporting.

**Comment by markgalpin** [comment]
This issue has now been moved to the Jenkins Artifactory Plugin JIRA: https://www.jfrog.com/jira/browse/HAP-1026  Please add any additional comments there to ensure it gets resolved in a timely fashion.

**Comment by yahavi** [comment]
@CausticYarn,
We fixed this issue. You can find a snapshot version in the [HAP-1026](https://www.jfrog.com/jira/browse/HAP-1026) ticket.

In order to use environment variables in Jenkins, you can wrap the pipeline script with:
```
withEnv(['CONAN_USER_HOME=/path/to/conan/home']) {
...
}

```

We would appreciate your feedback for it.

**Comment by yahavi** [comment]
@CausticYarn,

Jenkins-Artifactory plug-in v2.15.0 which includes a fix for this issue was released.
Feel free to upgrade.

**Comment by lasote** [comment]
I'm closing the issue, thanks @yahavi and thanks @CausticYarn for reporting, feel free to write again if something it's not working as expected.
