### ISSUE TITLE
Downloading gzip files can break if the server sends incorrect Content-Encoding

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#1901]
Consider the following example code (works with both Python2 and 3):

```py
from __future__ import print_function
import sys
import requests


def get_sha256(filename):
  import subprocess
  return subprocess.check_output(["shasum", "-a", "256", filename]).decode("utf-8")


def get_size(filename):
  import os
  return os.path.getsize(filename)


def download_file_copyfileobj(url, filename, user, password):
  import shutil
  req = requests.get(url, auth=(user, password), stream=True)
  print(req.headers)
  with open(filename, "wb") as f:
    req.raw.decode_content = False
    shutil.copyfileobj(req.raw, f)


def download_file_chunked(url, filename, user, password):
  req = requests.get(url, auth=(user, password), stream=True)
  total_size = int(req.headers.get('content-length', 0)); 
  with open(filename, "wb") as f:
    for chunk in req.iter_content(1024): 
      if chunk:
        f.write(chunk)


def download_file_chunked2(url, filename, user, password):
  req = requests.get(url, auth=(user, password), stream=True)
  total_size = int(req.headers.get('content-length', 0)); 
  print("total_size =", total_size)
  written = 0
  with open(filename, "wb") as f:
    for chunk in req.iter_content():
      if chunk:
        f.write(chunk)
        written += len(chunk)
      if written >= total_size:
        break
    print("written size =", written)


def download_file_chunked_truncate(url, filename, user, password):
  req = requests.get(url, auth=(user, password), stream=True)
  total_size = int(req.headers.get('content-length', 0)); 
  print("total_size =", total_size)
  written = 0
  with open(filename, "wb") as f:
    for chunk in req.iter_content():
      if chunk:
        f.write(chunk)
        written += len(chunk)
      if written >= total_size:
        break
    print("written size =", written)
    print("trunacting...")
    f.truncate(total_size)


def download_file_conan(url, filename, user, password):
  import conans.client.rest.cacert as cacert
  from conans import tools
  from conans.client.output import ConanOutput
  from conans.client.rest.uploader_downloader import Downloader
  out = ConanOutput(sys.stdout, True)
  verify = cacert.file_path
  downloader = Downloader(requests, out, verify=True)
  downloader.download(url, filename, retry=2, retry_wait=5, 
                      auth=(user, password))
  out.writeln("")


if __name__ == "__main__":
  functions = [
    download_file_chunked, 
    download_file_chunked2, 
    download_file_chunked_truncate,
    download_file_conan, 
    download_file_copyfileobj
  ]
  
  params = {
    'password': 'pass',
    'user': 'user', 
    'url': 'http://<SERVER>/files/libnatpmp-20110808.tar.gz'
   }
  for f in functions:
    print("Calling {0}...".format(f.__name__))
    fname = "libnatpmp_" + f.__name__ + ".tar.gz"
    f(filename=fname, **params)
    print("Size: {0}\nHash: {1}".format(get_size(fname), get_sha256(fname)))
    print()
```

The server sends the following response headers:

```
{
  'Date': 'Tue, 17 Oct 2017 10:07:37 GMT', 
  'Server': 'Apache/ProXad [Jul 22 2015 14:50:04]', 
  'Connection': 'close', 'Accept-Ranges': 'bytes', 
  'Content-Length': '17762', 
  'Content-Type': 'application/x-gzip', 
  'Content-Encoding': 'gzip'
}
```

When this code is ran, all but `download_file_copyfileobj` will produce a file that's incorrect in size and contents. Apparently, requests will decompress the gzip file being downloaded.

My current working theory is the server is trying to be smart and skips the gzip compression for a file that is already gzip-compressed (i.e. the Content-Encoding header lies). requests then sees this header and finds gzip data in the response (since the file being downloaded is itself gzip-compressed). 

This makes it impossible to verify a file hash for the downloaded file.

As for why this is not an issue while decompressing, my theory is that the tar.gz decompressor is tolerant enough to not error on non-gzip tar content (but it's very puzzling, nonetheless). 

https://stackoverflow.com/questions/25749345/how-to-download-gz-files-with-requests-in-python-without-decoding-it

https://github.com/requests/requests/issues/4346

**Comment by lasote** [comment]
a third party server is sending `'Content-Length': '17762'` for that file, that is the size of the file being recompressed (as Artifactory or github does, even being already a tgz), but at the end, the server is sended a full 102400 bytes file (the size of the original tgz). So, it's a server side issue.

**Comment by sztomi** [comment]
It appears that we were actually downloading from a public url: http://miniupnp.free.fr/files/libnatpmp-20110808.tar.gz

> a third party server is sending 'Content-Length': '17762' for that file, that is the size of the file being recompressed

No, that is the full size of the tar.gz. The issue is that it is **not** being compressed again, yet, the Content-Encoding says so. `requests` will then decompress the original file, that is the 102400 bytes (this can be verified locally). But all in all, yes, this is a server side issue. I'll email the admin of this site.
