### ISSUE TITLE
msbuild platform toolset setting

### ISSUE THREAD

**Issue by jeroendv** [conan-io/conan#1902]
Hi the "Visual s=Studio".compiler.version go from 8 -> 15.
However as a developer I tend to only work in VS 2017 (e.g. version 15), making use of the IDE improvements that it offers.

Yet some of my projects are build  against the vc100 platform toolset which would correspond to compiler of  VS 2012 (e.g. version 11). 

I.e. would it not be better to link the "Visual s=Studio".compiler.version with the platform toolset that is actually used to build the sources instead of the IDE version that is used to develop?

**Comment by memsharded** [comment]
I think this might be almost duplicate to: https://github.com/conan-io/conan/issues/966, lets continue conversation there.

**Comment by jeroendv** [comment]
the  [following](http://marcofoco.com/microsoft-visual-c-version-map/) may be a useful reference
