### ISSUE TITLE
Create a conan.conf entry for CONAN_USER_HOME_SHORT

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1903]
Now only works as environment variable

**Comment by lasote** [comment]
Or check the registry/python version, as an OR to avoid the limits

**Comment by memsharded** [comment]
It is already there:

https://github.com/conan-io/conan/blob/2dda00272455431cf2f36d16d25fdfb226596620/conans/client/conf/__init__.py#L133

**Comment by lasote** [comment]
Put it commented in the default config?
