### ISSUE TITLE
files.unzip unconditionally enforces Windows path limitations (even when not needed)

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#1904]
The unzip function contains this snippet:

```py
    with zipfile.ZipFile(filename, "r") as z:
        uncompress_size = sum((file_.file_size for file_ in z.infolist()))
        if uncompress_size > 100000:
            _global_output.info("Unzipping %s, this can take a while" % human_size(uncompress_size))
        else:
            _global_output.info("Unzipping %s" % human_size(uncompress_size))
        extracted_size = 0
        if platform.system() == "Windows":
            for file_ in z.infolist():
                extracted_size += file_.file_size
                print_progress(extracted_size, uncompress_size)
                try:
                    # Win path limit is 260 chars
                    if len(file_.filename) + len(full_path) >= 260:
                        raise ValueError("Filename too long")
                    z.extract(file_, full_path)
                except Exception as e:
                    _global_output.error("Error extract %s\n%s" % (file_.filename, str(e)))
```

This will error even on new Windows installations with the long paths enabled. Conan should check the python version (>= 3.6) and the LongPathsEnabled registry key and no raise the error when the OS is capable handling the long paths.

**Comment by sztomi** [comment]
The exact registry path is:

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```

**Comment by memsharded** [comment]
Yes, the CONAN_USER_HOME_SHORT=None has already been defined to avoid this, but has not been applied here yet.

Also, we could automate it with that registry value.

**Comment by sztomi** [comment]
Is CONAN_USER_HOME_SHORT appliable to 0.27? I don't see indication in the code above that it would remove this check.

**Comment by memsharded** [comment]
Yes, ``CONAN_USER_HOME_SHORT=None`` has been released in 0.27, but not applied to this part of the code. It has to be applied, will do for next release.

I am also thinking about the registry key, it might be dangerous to assume it (user might have python 3.6 for another project, use python 2.7 for conan), so maybe will keep ``CONAN_USER_HOME_SHORT`` defined by user.

**Comment by sztomi** [comment]
I don't understand that concern, all that matters is the interpreter currently executing. If it is >=3.6 and the system is long paths-capable then you are able to extract the files.

**Comment by memsharded** [comment]
Yes, that is right, checking also the python version could be good, thanks!
