### ISSUE TITLE
Long path names on Windows

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#1905]
We are having issues on our Windows CI machines with the path length of the Conan package. There is a 260 character limitation when using MSBuild, as it cannot read a file when the path is longer than 260 characters. You can read more [here](https://github.com/Microsoft/msbuild/issues/53). We sometimes miss this limitation by a few characters, 4-5, and everything fails on our Windows pipeline.

There are different workarounds for this problem but since the majority of the build path, `C:\Conan\.conan\data\lib_name\lib_version\user\channel_name\build\729b54659b7dd6c4d3056d86ea0f611ed11ce282`, is auto generated by Conan not much can be done. The long package hash, 40 characters, name is specially problematic. Since changing the `lib_name` and `version` and `user` are not possible we have to play with `channel_name`.

I was wondering if there are any technical reasons to just use the first 6-8 characters of the hash instead of the entire hash? Something like what git does in showing the first few characters. This will reduce the folder path by 32-34 characters and resolve 99% of our CI problems.

**Comment by memsharded** [comment]
Are  you aware of the ``short_paths`` feature? http://conanio.readthedocs.io/en/latest/reference/conanfile/attributes.html?highlight=short_paths#short-paths

**Comment by AliAskari** [comment]
WOW. That's so nice. Thank you so much. So simple and elegant.

**Comment by memsharded** [comment]
Good. I hope it is useful for you. Note, however, that it is a complex feature/workaround, so it might not be as stable and polished as using a good filesystem with long paths. In that sense, maybe you want to check latest python 3.6 support for long paths in Windows10. If you can, it is worth upgrading to that platform.

**Comment by petermbauer** [comment]
As i again came across this issue i did not want to create a new issue but at least leave a comment:
This is not only a limitation of Windows and Python. Most of the compilers under Windows have this limit so it will take some more years until this is properly solved. I can imagine that shortening the hash part of the paths in the local cache and having to deal with potential collisions is hard but these 40 characters really make a difference in many cases, especially when building in the user's workspace vs. building in the Conan local cache this often comes as a very annoying surprise.
