### ISSUE TITLE
Build missing library only, not dependencies

### ISSUE THREAD

**Issue by CausticYarn** [conan-io/conan#1906]
Is it possible to only build a library if it is missing and not its dependencies?  Right now it seems like you can force the build of a specific library under all circumstances, or build everything that's missing, unless there's a syntax I am missing.

**Comment by memsharded** [comment]
Yes, that is true, you can only do either. Typically the ``--build missing`` is mostly for playing and debugging, usually, it is expected that packages have been properly created and tested with ``conan create``. Which is your work flow that you are interested in such building pattern?

**Comment by CausticYarn** [comment]
I am looking to pull recipes from the conan-center (or other) repository and cache them in a private Conan repository, since I'd rather re-use a high quality recipe rather than write my own. If the config I need has already been built, great, I can just upload it, otherwise I need to build it.  

Now that I think about it, if the dependencies are missing, I won't be able to install the package anyway, so I'd have to build them.  Is there maybe a better way of doing this?

**Comment by memsharded** [comment]
Just be aware that the default conan remotes right now are conan-center and conan-transit. Packages from conan-transit won't be high quality on average.

From my experience, most conan users that are storing packages in a private repository also take control of their generation so:
- They typically don't rely on binaries from external repos. They generate all binaries locally before uploading to their private remote
- They also take control of the package recipe, typically forking the repo. Easy to sync if there are changes to the recipe, or new versions.
- They create packages for them as their regular packages, with ``conan create``, typically in CI

If you are just building binaries that are missing from conan public repos, why ``conan install --build missing`` is not enough? In fact, as you said, if there is some other package missing, and it is not built, the installation will fail. So for a quick retrieval of binaries or generating missing binaries, this is good, isn't it?

**Comment by CausticYarn** [comment]
I explicitly use conan-center, not conan-transit.  For some packages, especially if I have need of custom build requirements, I might take control of the recipe locally and store it in version control. But for some small dependency packages, like zlib, I don't really have an opinion on how to build it and am willing to trust in a maintainer's high quality recipe, and a prebuilt package from conan-center if it exists, and have one less file to worry about locally.

I was a bit concerned about building and uploading dependencies that I might already have, but in that case I could just target the new package for upload and ignore the rest. This issue can be closed from my end.

**Comment by memsharded** [comment]
Great, many thanks!
