### ISSUE TITLE
Conan parallel build for Visual Studio using CMake build()

### ISSUE THREAD

**Issue by Aalmann** [conan-io/conan#1909]
Hi @memsharded  and @lasote ,

I have seen in #1034 (and in conans.client.cmake) that the /MP flag will be set for VisualStudio which only has an effect on the Visual Studio Project but not on the complete solution when using cmake.build() method (see https://msdn.microsoft.com/en-us/library/bb385193.aspx). This is Ok for small packages (with 1 or 2 projects to build within the solution) but does not really speed up the build for bigger packages (e.g. 10+ libraries/binaries).
CMake itself calls MSBuild which can be parallized with the "/maxcpucount" option. So I suggest to add the following to the cmake _build_new(...) method:

```
...
         if self.parallel:
            if "Makefiles" in self.generator:
                if "--" not in args:
                    args.append("--")
                args.append("-j%i" % cpu_count())
            # new code
            elif "Visual Studio" in self.generator:
                if "--" not in args:
                    args.append("--")
                args.append("/maxcpucount:%i" % cpu_count())
...
```

Do you agree or is there any issue with the approach?

**Comment by memsharded** [comment]
Yes, without knowing the details about /maxcpucount, it seems it makes sense, lets try it.
