### ISSUE TITLE
Unicode filenames

### ISSUE THREAD

**Issue by tobyas** [conan-io/conan#191]
Having a file with a unicode filename when exporting sources seems to crash(IOError) conan. Didn't test if there are problems with other steps (packaging,etc) but there might be.

**Comment by memsharded** [comment]
Yes, that can be a problem. Just the case-insensitiveness of some OSs is a nightmare (conan has already implemented some countermeasures). Unicode filenames are often a problem too for portable development, not only for conan but for many other tools. I have constrained myself to ascii filenames for all my developments in all my projects in all dev languages. But I understand that for some projects it can be a problem, so this issue should be checked when possible, to see what could be done. Thanks for reporting.

**Comment by tobyas** [comment]
Managed to fix this by wrapping a bunch of writting operations with unicode casts. Would that be the way to go? The way I understand it using python3 would solve this by using unicode by default?

**Comment by memsharded** [comment]
yes, I think that this should be the way. There is already some ongoing work on python3 issue, but that doesn't mean conan should stop working and maintaining compatibility with python 2.7, so the unicode casts would be probably still necessary. As a general policy, I think that conan should work in as many systems as possible, especially considering non bleeding edge systems. Using ubuntu 12, gcc 4.7 and cmake 2.8 is still very common in the industry, so supporting python 2.7 seems to be more than reasonable too.

Did you manage to run the tests, and in which platforms? Maybe if you could try to open a PR with your unicode casts or send a patch, we could try to help integrating it. Thanks!

**Comment by memsharded** [comment]
Hi @tobyas

Python 3 support has been added to the develop branch. I am experimenting with unicode filenames and it helps a lot, as expected, you might want to try it out too. Started to try with Python 2.7, and to add unicode casts, but still work to do.

**Comment by memsharded** [comment]
After a while trying with Py2, I think I am going to put this on hold. I have had problems in the internals of tarfile library, and it could be a major problem with existing packages and backwards compatibility under Py2. Please recall that all packages are tar.gz'd before uploading to the servers. Did you try to upload/retrieve the packages and worked? 

Also, it seems that unicode filenames are not so common in user projects, so my suggestion here would be to try under Python3 if unicode filenames are not avoidable. Any other idea or suggestion?

**Comment by sixten-hilborn** [comment]
Hi, I just noticed there are problems when the sources of a library contains filenames with non-latin-1 characters (yes it's Windows, running Python 2.7 and Conan 0.24.0).

For demonstration I created a small package:
```python
# This Python file uses the following encoding: utf-8
from conans import ConanFile

class TestConan(ConanFile):
    name = "test"
    version = '0.1'

    def source(self):
        with file(u'Привет мир', 'w') as f:
            f.write('\n')
```

Trying to build it raises following error:
```
test/0.1@user/testing: Copying sources to build folder
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\conans\client\command.py", line 722, in run
    method(args[0][1:])
  File "c:\python27\lib\site-packages\conans\client\command.py", line 130, in test_package
    args.manifests_interactive, args.remote, args.update)
  File "c:\python27\lib\site-packages\conans\client\conan_api.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\conans\client\conan_api.py", line 238, in test_package
    generators=["txt"]
  File "c:\python27\lib\site-packages\conans\client\manager.py", line 282, in install
    installer.install(deps_graph, build_mode, current_path)
  File "c:\python27\lib\site-packages\conans\client\installer.py", line 134, in install
    self._build(nodes_by_level, skip_private_nodes, build_mode)
  File "c:\python27\lib\site-packages\conans\client\installer.py", line 225, in _build
    package_folder, output)
  File "c:\python27\lib\site-packages\conans\client\installer.py", line 350, in _build_conanfile
    self._build_package(export_folder, src_folder, build_folder, package_folder, conan_file, output)
  File "c:\python27\lib\site-packages\conans\client\installer.py", line 462, in _build_package
    shutil.copytree(src_folder, build_folder, symlinks=True, ignore=check_max_path_len)
  File "c:\python27\lib\shutil.py", line 208, in copytree
    raise Error, errors
Error: [('C:\\.conan\\test\\0.1\\user\\testing\\source\\?????? ???', 'C:\\.conan\\test\\0.1\\user\\testing\\build\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\\?????? ???', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\.conan\\\\test\\\\0.1\\\\user\\\\testing\\\\source\\\\?????? ???'")]
```

The actual problem is in `shutil`/`shutil.copytree`: https://bugs.python.org/issue24672

**Comment by memsharded** [comment]
Yes, this is why Unicode filenames are not supported in general, the basic support from python and the OS is not there. Just in case there are doubts, we would love to move forward to Python 3 only, but python 2.7 is still very mainstream and heavily used by our user base, so it is not something we could do it yet.

**Comment by Croydon** [comment]
> but python 2.7 is still very mainstream and heavily used by our user base

May I ask how you get such statistics/data?

**Comment by memsharded** [comment]
Asking, talking to users :)

**Comment by chuet-thermo** [comment]
Hi,

this issue is causing us trouble with conan >= 0.30, since the `conanfile_directory` variable was removed, and conan's working directory is not the original source directory.

Some tests we have try to read files with an UTF-8 filename. 
However, these files are not copied by conan, so we did it manually in out `build` method, to ensure the package would have these files and the tests would pass.

i.e. we have our source tree in 
original/src/[chinesefilename]

which is not copied to 
conan_cache/src/

so we used to have a 
`real_source_dir = os.getcwd()` at the top of our conanfile and a `shutil.copy2(os.path.join(real_source_dir, 'chinesefilename'), destination_path)` in our `build` method.

This workaround does not work when upgrading conan to a recent version.

Any advice on how to get things working again ?

Thanks.

**Comment by memsharded** [comment]
Hi @chuet-thermo 

You might want to follow latest work in https://github.com/conan-io/conan/issues/2163 by @mpdelbuono 

Basically it is necessary to use Python3, as Unicode file paths support seems nearly impossible with Python2. Are you already using Python3? Thanks!

**Comment by jgsogo** [comment]
The path towards python3 has been defined (https://blog.conan.io/2018/08/13/Its-Time-To-Deprecate-Python-2.html) and after several attempts to handle unicode in the filesystems [[1](https://github.com/conan-io/conan/pull/2807/files)] [[2](https://github.com/mpdelbuono/conan/tree/feature/unicode-path-support)] there seem not to be an easy solution for python2 that is compatible with python3.

Marking it as `inactive` and probably close it in a few days.
