### ISSUE TITLE
Add -werror to Conan create

### ISSUE THREAD

**Issue by aacebedo** [conan-io/conan#1913]
Hi !

It would be great if conan create command supports the -werror option found on Conan install.
I have an issue with my CI pipeline as I use conan create for packaging and uploading and sometimes my dependency graph causes dependency incompatibility. I prefer to stop the build when this happen instead of uploading package with faulty dependencies.

**Comment by memsharded** [comment]
Yes, totally makes sense, and shouldn't be difficult. Lets try to add to next 0.28.

**Comment by memsharded** [comment]
Released in 0.28, please try. Thanks!
