### ISSUE TITLE
Importing `conanfile.py` into `test_package/conanfile.py`

### ISSUE THREAD

**Issue by flisboac** [conan-io/conan#1924]
I was recently trying to create a package where I would reuse some definitions made in `conanfile.py`'s `ConanFile` in `test_package/conanfile.py`, in order to have a single point of version definition.

For instance, suppose I have such a `conanfile.py`:

```python
from conans import ConanFile, tools, AutoToolsBuildEnvironment

class ConanPackage(ConanFile):
    # ...
    fullname = '{}/{}@{}/{}'.format(name, version, user, channel)

```

And this `test_package/conanfile.py`:

```python
import sys, os

conanfile_path = os.path.join(os.path.dirname(__file__), '..')
sys.path.append(conanfile_path)

from conans import ConanFile, CMake
from conanfile import ConanPackage

class ConanTestPackage(ConanFile):
   settings = "os", "compiler", "build_type", "arch"
   requires = ConanPackage.fullname # Contains the full name, such as in 'MyLib/0.1.0@user/channel'
   generators = "cmake", "gcc", "txt"

   def build(self):
      cmake = CMake(self)
      cmake.configure()
      cmake.build()
```

I'd expect the `sys.path` to be correctly set up so that I can import my root `conanfile.py`. Instead, this error occurs:

```
ERROR: Unable to load conanfile in /projects/conan-xmlrpc-c/test_package/conanfile.py
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/projects/conan-xmlrpc-c/test_package/conanfile.py", line 6, in <module>
    from conanfile import ConanPackage
ImportError: cannot import name 'ConanPackage'
```

Not sure why, as I don't know how Conan executes the test package's conanfile. And I would like to avoid hardwiring my new package's name into `test_package/conanfile.py` (this is what I'm doing right now)... What should I do?

**Comment by memsharded** [comment]
Not sure what you are trying to achieve. Now it is not necessary anymore to have the ``requires`` field at all in the ``test_package``.

Check the example:

```bash
$ conan new Hello/0.1 -s -t
#check conanfile.py inside test_package
$ conan create user/testing
```

**Comment by flisboac** [comment]
Oh, cool, it works! Didn't know about that. I just cloned someone's repository, and a `requires` line was there, and I was expecting it to not work if I didn't specify the `requires` in `test_package/conanfile.py`. Indeed, it's not needed to specify it.

My intention was to provide user and channel (and some other tweaks) through environment variables, just so I could automate the build somehow without having to change my package's source code everytime I need to e.g. bump the package's version. And because of that dynamic construction of the project's full name would be needed. But I guess not even that is necessary.

I'm sorry! Please close the issue!

**Comment by memsharded** [comment]
No problem, glad to help, no need to apologize :) :)

Feel free to ask any further question you have. Also, stay tuned to the docs http://docs.conan.io/en/latest/, specially for new releases and changelog, because conan is continously improving. Cheers!
