### ISSUE TITLE
Ask for password when execute `conan user`

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1929]
Hi!

I would like to be able to enter my password when I run `conan user`, without exposing the characters.

For now, we are able to run using `-p/--password` but needs to expose all the characters:

```
$ conan user -r bintray -u uilianries -p foobar
```

The second way is when the upload occurs and I'm not yet authenticated, so the password is requested and the characters are not exposed:

```
$ conan upload -r bintray foobar/0.1.0@uilianries/stable
Uploading foobar/0.1.0@uilianries/stable
Please log in to "bintray" to perform this action. Execute "conan user" command.
Please enter a password for "uilianries" account: 
```

It would be nice if I had something like this:

```
$ conan user -a -r bintray uilianries
Please log in to "bintray" to perform this action.
Please enter a password for "uilianries" account: 
```

Help usage:
```
$ conan user --help
usage: conan user [-h] [-p PASSWORD|-a] [--remote REMOTE] [-c] [name]

Update your cached user name (and auth token) to avoid it being requested
later. e.g. while you're uploading a package. You can have more than one user
(one per remote). Changing the user, or introducing the password is only
necessary to upload packages to a remote.

positional arguments:
  name                  Username you want to use. If no name is provided it
                        will show the current user.

optional arguments:
  -h, --help            show this help message and exit
  -p PASSWORD, --password PASSWORD
                        User password. Use double quotes if password with
                        spacing, and escape quotes if existing
  -a, --ask              Ask for the password. Avoid to expose your characters.
  --remote REMOTE, -r REMOTE
                        look in the specified remote server
  -c, --clean           Remove user and tokens for all remotes
```

We can't change the current behavior, asking `-p` is not present, so my idea is to add a new option, was `-a/--ask`, but can be improved.

Regards.

**Comment by memsharded** [comment]
Yes, could be possible. I would suggest the argument ``--interactive, -i``, I think is more common for this behavior.

**Comment by lasote** [comment]
What about `-p` without value? maybe it's not needed to add a new parameter. Just if -p without value, conan will ask you.

**Comment by uilianries** [comment]
`--interactive, -i` is better, I think. The option will be explicit.

When I use only `-p` with no value, I'm trying to authenticate with an empty password, this is the current behavior when I run `conan user`.
But okay, the user can just press enter again. However, we'll break the current flow silently.

Thanks for the comments.
