### ISSUE TITLE
Compiling compiler with Conan and then using it

### ISSUE THREAD

**Issue by DariuszOstolski** [conan-io/conan#1933]
I want to achieve following workflow in conan. I want to have fully reproducible builds so my idea is this let's compile compiler and then use this compiler to compile some packages and it's dependencies. My problem is that I could not find any resources that would allow me to implement it using conan. There are my questions:
1. Is it possible to achieve it with conan?
2. Could you please point me to some resources that would help me to implement this solution?

Best Regards,
Darek

**Comment by memsharded** [comment]
Yes, it is definitely possible, and we are aware of some conan users doing it succesfully in production. There are some public packages packaging a compiler (though not building it from sources, but that would be just a build() like any other package. You want to check http://docs.conan.io/en/latest/howtos/create_installer_packages.html, where there are mingw and cmake examples.

Then, you dont want to use them as normal requirements, but most likely as ``build_requirements``, have a look to: http://docs.conan.io/en/latest/mastering/build_requires.html

Please have a look at these and tell me. Thanks!

**Comment by DariuszOstolski** [comment]
Thanks a lot, I'll go through those docs and let you know. Thanks a lot.

**Comment by memsharded** [comment]
@DariuszOstolski Any further question here? 
Regarding packaging build tools, I would like to point to issue: https://github.com/conan-io/conan/issues/2098. It is true that right now there are not standard settings to model cross-build tools (basically, missing "build" and "target" settings). I think you might be interested in following that issue. Can this one be closed now? Thanks!

**Comment by DariuszOstolski** [comment]
@memsharded 

No further questions, this can be closed
