### ISSUE TITLE
Better and smarter CI integration

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1934]
- `info build_order` + `info --build` => Returning which nodes to build (following the package_id) and in which order.
- And being able to build a node with the correct profile, not the consumer profile, but the profile to be applied to reproduce the build. requirement overrides?
- Profile generator? => in consumer, then apply to nodes

**Comment by memsharded** [comment]
There are still many doubts about this, it is necessary first to have better output of install, info and create commands (machine readable). Moving to 1.2
