### ISSUE TITLE
Improve error message for command line settings mistyping

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#194]
If 

```
$ conan install -s build_type:Debug (instead of build_type=Debug)
```
it crashes with an ugly exception. Improve the error message.

Consider also the possibility to input -s just once for all settings

**Comment by aurelienrb** [comment]
Thanks for creating the ticket.

The reason I used _arch:x86_64_ instead of _arch=x86_64_ on the command line is because I copy-pasted the info from the website.

So may be you could update your web-site to use the syntax than Conan? Or may be better: accept both syntaxes in Conan!

Aurelien

**Comment by lasote** [comment]
@aurelienrb  where is the website using the build_type:Debug syntax?

**Comment by lasote** [comment]
A better error message will be shown in conan 0.8.

**Comment by aurelienrb** [comment]
@lasote on the package tab of any package, you get the details for each specific build which uses the "dot dot" syntax.
Example:
https://www.conan.io/source/Boost/1.60.0/lasote/stable
```
Settings
arch: x86 build_type: Debug compiler: gcc compiler.version: 4.6 os: Linux
```

**Comment by lasote** [comment]
Ok. Thanks. I will change the website to match the client format.

**Comment by aurelienrb** [comment]
Cool :)

Regarding:
> Consider also the possibility to input -s just once for all setting

here's my suggestion: allow to specify all the parameters in a string, that way:
`conan install -s "build_type=Debug compiler=gcc compiler.version=4.6"`

or may be that way to work with compiler name "Visual Studio":
`conan install -s "build_type=Debug;compiler=Visual Studio;compiler.version=14"`

**Comment by lasote** [comment]
Try the new "copy install command to clipboard" in website. 
We want to keep the settings and option format by now. But thanks for your suggestions.
