### ISSUE TITLE
tools.run_in_windows_bash path issue

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#1943]
When using run_in_windows_bash, the current PATH is not transferred to the bash environment, so dependencies are not accessible. It leads to failure in the case of building openssl on windows without perl, because the build requirements strawberryperl is not accessible in the bash environment.
`tools.run_in_windows_bash(self, "echo $PATH")` has only `/mingw32/bin:/usr/local/bin:/usr/bin:/bin:C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\` whereas `self.run("echo %PATH%")` has path to the strawberryperl package

**Comment by lasote** [comment]
I cannot reproduce the error, I added a test doing:

```
de build(self):
  with tools.environment_append({"MYVAR": "Hello MYVAR"}):
        tools.run_in_windows_bash(self, "echo $MYVAR")
```

And the `Hello MYVAR` is printed, also the entire PATH. Which "bash" are you using?

**Comment by ericLemanissier** [comment]
I am using msys2-64, but the problem is specific to the PATH variable. Obviously, bash modifies it when it starts. 
```python
    def build(self):
        self.run("echo %PATH%")
        tools.run_in_windows_bash(self, "echo $PATH")
```
I get the following output
```
Project: Running build()
C:\Users\Eric-\.conan\data\cmake_installer\1.0\conan\stable\package\6d2a1ec277807fef046cc286fee77c1d708f2c53\bin;C:\Users\Eric-\.conan\data\mingw_installer\1.0\conan\stable\package\2811612fd9c2d853eb2d79b37a322e0034a1268e\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\usr\bin;C:\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl
Project: run_in_windows_bash: bash --login -c ^"cd \^"/c/pf/conan-tmp\^" ^&^& echo $PATH ^"
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```
The output of run_in_windows_bash lacks the paths to the requirements of the package (cmake_installer and mingw_installer in this example)

**Comment by lasote** [comment]
PR https://github.com/conan-io/conan/pull/2047 updated, fixed and added test using path.
