### ISSUE TITLE
SystemPackageTool and msys2

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#1944]
When using msys2 environment, SystemPackageTool could use pacman to install packages. This would allow starting from clean msys2, and make conan recipe install make or git if needed

**Comment by memsharded** [comment]
@SSE4 has contributed a **PacManTool** for system_requirements, in conan 0.28, you might try it:
http://docs.conan.io/en/latest/reference/conanfile/methods.html#system-requirements

**Comment by ericLemanissier** [comment]
First try fails because the tool needs to be explicitly specified. Maybe OSInfo.with_pacman could identify windows msys2 configuration ?
Second try fails because `os.environ["CONAN_SYSREQUIRES_SUDO"]` is "True", Is it normal on windows msys2 ?
Third try works, thanks ! :
```python
    def system_requirements(self):
        del os.environ["CONAN_SYSREQUIRES_SUDO"]
        packageTool = SystemPackageTool(tool=PacManTool())
```

**Comment by SSE4** [comment]
@ericLemanissier  thanks for the feedback, I'll try to improve logic so it doesn't need workarounds you have mentioned

**Comment by lasote** [comment]
We prefer to keep it open until we release it. Thanks!
