### ISSUE TITLE
Add model for conanfile to "package being developed"

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1952]
Should be true:
- If it is the package ``conan create``d
- If it is the package ``conan installed <pkg-ref>``
- If it is the package being developed in user space

Use case:
- Require, build & run tests only for that case

**Comment by lasote** [comment]
`If it is the package conan installed <pkg-ref>` <= Maybe these case don't

**Comment by memsharded** [comment]
This is not simple at all, it is difficult to inject the "self.develop" value, because of the "virtual" way to load the dependency graph.
