### ISSUE TITLE
Warning emitted by the CMake helper for a custom build_type

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#1953]
Hi,

I want to force Release builds to behave as if it was RelWithDebInfo.
However, doing so emits a warning:

> zlib/1.2.11@theo/test: WARN: Set CMake build type "RelWithDebInfo" is different than the settings build_type "Release"

Here's an excerpt of my `conanfile.py`:

```python
    def build_id(self):
        build_type = self.settings.build_type
        # Have the same flags in Release/RelWithDebInfo, only the inline level changes
        # Ob1 vs Ob2, Ob1 is better, Luke.
        if build_type == "Release":
            self.info_build.settings.build_type = "RelWithDebInfo"
        else:
            self.info_build.settings.build_type = build_type
            
    def build(self):
        cmake = CMake(self, build_type=self.info_build.settings.build_type)
        cmake.configure(source_dir=self.name)
        cmake.build()
```

Is there a way to remove this warning? I can live with that too, not a big issue.

**Comment by memsharded** [comment]
I am not sure ``build_id()`` is the best place to do that, but I think I don't fully understand it. 
Why not directly forcing RelWithDEbInfo in the ``build()`` method? Have you added RelWithDebInfo to your settings.yml? 
If you could please a bit longer what you want to achieve with such ``build_id()`` method. Thanks!

**Comment by theodelrieu** [comment]
Sure, I want to build once, package twice for Release/RelWithDebInfo build types, the only real difference being packaging or not PDBs on Windows.

This is why I cannot modify the `settings.build_type`, else I will package PDBs in Release too.

I currently use this method on every recipe at work, so if you have a better way of doing this I'll gladly adopt it! But it work quite well so far :)

**Comment by memsharded** [comment]
Ok, it makes perfect sense now, thanks. I deduce that you haven't added RelWithDebInfo to the default ``settings.yml``.

I think the warning makes sense for most users, so I think we should keep it. I have checked if possible to opt-out the warning, but as it is a setter, it is not simple to do. You could of course hack into the private members of the CMake helper:

```python
cmake = CMake(self)
if self.settings.build_type == "Release":
    cmake._build_type = "RelWithDebInfo"
    cmake.definitions.update(cmake._build_type_definition())
cmake.configure(source_dir=self.name)
...
```

**Comment by theodelrieu** [comment]
I have this line in my `settings.yml`:

```yaml
build_type: [None, Debug, Release, RelWithDebInfo]
```

Maybe it's not what you mean when you talk about the "default settings"? I agree that this warning is useful, I'd rather see it everyday than hacking into private details though.

**Comment by memsharded** [comment]
Yes, I was asking about that, the ``settings.yml``. It is OK.
I agree, better the warning than messing with private.
Just a last comment, I think you can simplify your ``build_id()``:

```python
    def build_id(self):
        if self.settings.build_type == "Release":
            self.info_build.settings.build_type = "RelWithDebInfo"
```
If we are leaving the warning, can we close this issue then? Thanks!

**Comment by theodelrieu** [comment]
Thanks!
