### ISSUE TITLE
conan 0.28.0 shasum changed

### ISSUE THREAD

**Issue by iMichka** [conan-io/conan#1955]
Hi

I am one of the homebrew/linuxbrew package manager maintainers.
We just releases conan 0.2.28, but the shasum changed meanwhile:

```
==> brew install --build-bottle --verbose conan
Error: SHA256 mismatch
Expected: 278044fc06231c7ca60027406fcd6670401f2248f34c75dbf8ea73fc706093ac
Actual: eadf4cb64ec89ae32944fe8092b07cc502e88a6b68a509d495557f37907fa739
Archive: /home/linuxbrew/.cache/Homebrew/conan-0.28.0.tar.gz
To retry an incomplete download, remove the file above.
==> FAILED
```

Was the retagging of the release done on purpose? Or did somebody hijack your GitHub account to inject malicious code into the release?

**Comment by memsharded** [comment]
Hi @iMichka 

Yes, sorry for the inconvenience. Github did a weird thing and we had to resubmit the release. You can use the new one, no hijack :)

Thanks for noticing and telling!

**Comment by lasote** [comment]
GitHub tagged develop branch instead of master. I  had to reupload the tag. Sorry

**Comment by iMichka** [comment]
No problem. We saw the diff was just in the version number. We will bump the sha256. Thanks.
