### ISSUE TITLE
How to display all available packages ?

### ISSUE THREAD

**Issue by justinjk007** [conan-io/conan#1958]
I did `conan search *` and it returned pattern not available

**Comment by memsharded** [comment]
Are you looking for packages in your local cache? Have you created or installed them from remotes?

How did you installed conan? With the ``pip`` installer? Or with other one? You can try just ``conan search`` without anything, and sometimes the terminal requires quotes on the pattern.

**Comment by justinjk007** [comment]
I installed conan via pip..
Do I need to add remotes to install libs ?
Just typing `conan search` says there are no packages.

**Comment by memsharded** [comment]
conan-center and conan-transit are already configured as remotes.
If you want to search in one remote: ``conan search -r=conan-transit``.

Please check the docs: http://docs.conan.io

**Comment by justinjk007** [comment]
OK this quenched my thirst. But I should ask, is there anyway I can check if Conan is installed in CMake. So I can fall back to regular config if conan is not installed. Thanks

**Comment by memsharded** [comment]
Yes, that is a typical cmake check:

```cmake
if (EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
     include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
     conan_basic_setup()
else()
     # other way to get dependencies info
endif()
```

**Comment by justinjk007** [comment]
Thank you very much this should help me get started.

**Comment by kreuzerkrieg** [comment]
Just searched the conan-cente remote. It looks very modest compared to a newcommer as vcpkg. So the question is, did Conan get any traction in the community?

**Comment by memsharded** [comment]
Hi @kreuzerkrieg 

I might be obviously biased, but I'd say that yes, Conan is getting a great traction. Here are some pointers that might help validating this:

You might want to have a look at the bincrafters community:
- Site: https://bincrafters.github.io/
- Bintray repos: https://bintray.com/bincrafters

You migth want to join the #conan channel in the CppLang slack. It has more than 400 users, very active, helpful and friendly. 

You might also survey recent reddit threads, e.g.: https://www.reddit.com/r/cpp/comments/7e7jbt/who_is_using_conanio/

You can see also some of the companies using conan in https://conan.io/

You can also check the number of followers, interactions, etc in twitter: https://twitter.com/conan_io

You can check the number of stars, releases (at least one per month), contributors, here in github. The activity in github (notifications, issues), keeps growing very fast, we expect to keep hiring (https://join.jfrog.com/job/?job=1105521&dep=all), to double the conan team before the end of the year, to try to sustain this growth.

**Comment by kreuzerkrieg** [comment]
Great! Bintray looks promising. Thanks for info!

**Comment by ssb22** [comment]
I'm still having trouble displaying a list of all packages.  I just installed conan via `sudo pip install conan` on a Fedora 32 box (`/usr/local/lib/python3.8/site-packages/conans/__init__.py` says it is version 1.28.1), and then I found `conan search` says there are no packages, `conan remote list` says `conan-center: https://conan.bintray.com [Verify SSL: True]` and `conan search -r=conan-center` says:

    ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))
    Unable to connect to conan-center=https://conan.bintray.com
    1. Make sure the remote is reachable or,
    2. Disable it by using conan remote disable,
    Then try again.

Debian GNU/Linux has a nice browsable list of packages (by section) at packages.debian.org: anyone new to 'Linux can simply spend a while browsing the sections that most interest them to help decide what to install and try out.  Similarly, the PyPI website has a nice "browse projects" page that lets you browse by various categories including Topic and Intended Audience.  But with Conan it seems you must already have some idea of which packages you want before getting started.  So a package list would be nice :)

**Comment by memsharded** [comment]
Hi @ssb22

ConanCenter has change a lot, and there are plans to keep improving things. 
At the moment the search from the client is still not working, but that is one of the things planned to be fixed.

Best ways to search in the center right now is:

- Search in the new front-end: https://conan.io/center/
- Search in the repo (clone it and you get already the packages as folders, or grep): https://github.com/conan-io/conan-center-index

**Comment by uilianries** [comment]
Related to https://github.com/conan-io/conan-center-index/issues/339

**Comment by Dattax** [comment]
Page added and will evolve: https://conan.io/center/allpackages
