### ISSUE TITLE
conan install and working directory

### ISSUE THREAD

**Issue by aurelienrb** [conan-io/conan#196]
Hello,

I try to run conan on _dir1/conaninfo.txt_ from another directory this way:
`conan install ../dir1`
it works, but the generated files (conaninfo.txt + conanbuildinfo.props) are located in the current dir instead of _dir1_ as I would expect.

As a result, I can't run again conan on another dir (_dir2/conaninfo.txt_) because it would override the files generated for _dir1_. I have to manually do pushd/popd in my scripts

Is it on purpose to not put the generated files in the given install dir?

Aurelien

**Comment by lasote** [comment]
Hi Aurelien,

Yes, it's on purpose, just like cmake. It allows to do out-source installs. You need to execute conan install in the directory where you want that the files are created.

Luis

**Comment by aurelienrb** [comment]
Ok thanks for the explanation. Makes sense indeed :)
