### ISSUE TITLE
Post-imports configuration

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#1960]
Consider where you need to do some configuration on a package after it's imported. Is it acceptable to run self.run within the imports method? If so, how would you get the package for which imports is currently running? If not, is there an appropriate place to do something like this?

**Comment by memsharded** [comment]
Yes, I think you might be interested in the new ``deploy()`` method. Yes, you might be able to run ``self.run()`` in any method of the recipe. Please have a look to: http://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy

And: http://docs.conan.io/en/latest/packaging/running_packages.html#deployable-packages

**Comment by rconde01** [comment]
I might be able to get that to work, but it was not really what i was thinking of. From the imports method, is there a way to retrieve for which package it is running?

**Comment by memsharded** [comment]
Not sure if I understand your question, the imports method works always from the consumer side, either a conanfile.txt or a conanfile.py in user space. One single imports import from the whole dependency graph. Maybe the ``folder`` argument, that puts artifacts from each dependency in a folder with the name of that dependency could be useful for your purposes.

**Comment by rconde01** [comment]
So imports might look like this:
   def imports(self):
      self.copy(“*”)

Since this copy applies to all requirements, my assumption was that it runs once for each requirement. So I was hoping I could do something like:

def imports(self):
   If self.currentpackname == “whatever”:
      DoSomething

**Comment by memsharded** [comment]
No, each call to ``self.copy`` will walk the whole dependency graph, so just one ``imports()`` invocation.

If you need to do something per package, you can probably control that with ``root_package`` argument, something like:

```python
def imports(self):
     for pkg in ["MyPkg1", "MyPkg2",.....]:  #self.deps_cpp_info.deps can list all
           self.copy(....., root_package=pkg)
           if pkg == "MyPkg1":
                  #DoSomething
```

**Comment by rconde01** [comment]
Thanks...I’ll check that out.
