### ISSUE TITLE
Deploy not working as expected

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#1966]
Probably I'm just misunderstanding something, but deploy it not working as I expected.

I have a binary tool package. The original dir structure is like:

my_tool/my_tool.exe
my_tool/conanfile.py

The contents of conanfile.py are:

```
from conans import ConanFile

class my_tool(ConanFile):
   name="my_tool"
   version="1.0"
   exports="*"

   def package(self):
      self.copy("*")

   def deploy(self):
      self.run("my_tool.exe --doSomeConfig")
```

The I call:

`conan create me/stable --build`

Then I go so some directory where I want to install it and call:

`conan install my_tool/1.0@me/stable`

Instead of installing it, I get:
```
.
.
.
my_tool/1.0@me/stable Already Installed!
.
.
.
```

What am I missing?

**Comment by memsharded** [comment]
Seems to be working fine here, did you update to conan 0.28?

**Comment by rconde01** [comment]
Yes...this is Conan 0.28. To clarify, I guess the problem is not with deploy at this point...but the fact that it thinks it’s already installed. It is installed in the Conan cache, but my understanding was that by specifying the full package name in install, this was signifying the local install and thus the case where deploy would run. I could delete the package locally after uploading to the server, and maybe that would fix the problem but it seems like it shouldn’t be necessary.

**Comment by memsharded** [comment]
But that is not a problem at all. Saying that it is installed means that it was retrieved/created in the local cache. But the ``deploy()`` will execute always anyway, so that should achieve what you want, unless I am missing something. What am I missing?

**Comment by rconde01** [comment]
nm - Sorry - I was being dumb...the deploy wasn't copying the files!!

**Comment by memsharded** [comment]
No problem, glad it solved :)
