### ISSUE TITLE
conanbuildinfo.cmake error with CMake v2.8.11

### ISSUE THREAD

**Issue by xbreak** [conan-io/conan#1968]
Trying out the `mytimer` example I had to build Poco (Poco/1.7.9@pocoproject/stable) for my platform (CentOS 7.2), which was not a problem until `add_compile_options` was used in `conanbuildinfo.cmake` (which I assume is generated). That functions was as far as I know added in CMake 2.8.12.

Please add a "minimum required cmake" check so it is clear what the problem is.

	-- The C compiler identification is GNU 4.8.5
	-- The CXX compiler identification is GNU 4.8.5
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	CMake Error at <redacted>/local/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:31 (try_compile):
	  COPY_FILE specified on a srcdir type TRY_COMPILE
	Call Stack (most recent call first):
	  <redacted>/local/share/cmake/Modules/CMakeTestCCompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ABI)
	  CMakeLists.txt:1 (PROJECT)

	-- Detecting C compiler ABI info - failed
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	CMake Error at <redacted>/local/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:31 (try_compile):
	  COPY_FILE specified on a srcdir type TRY_COMPILE
	Call Stack (most recent call first):
	  <redacted>/local/share/cmake/Modules/CMakeTestCXXCompiler.cmake:68 (CMAKE_DETERMINE_COMPILER_ABI)
	  CMakeLists.txt:1 (PROJECT)

	-- Detecting CXX compiler ABI info - failed
	-- Conan: called by CMake conan helper
	-- Conan: Using cmake global configuration
	CMake Error at <redacted>/.conan/data/Poco/1.7.9/pocoproject/stable/build/24a7380840586332966890886948deb3b04ba334/conanbuildinfo.cmake:458 (add_compile_options):
	  Unknown CMake command "add_compile_options".
	Call Stack (most recent call first):
	  <redacted>/.conan/data/Poco/1.7.9/pocoproject/stable/build/24a7380840586332966890886948deb3b04ba334/conanbuildinfo.cmake:180 (conan_global_flags)
	  CMakeLists.txt:4 (CONAN_BASIC_SETUP)

	-- Configuring incomplete, errors occurred!
	Poco/1.7.9@pocoproject/stable:
	Poco/1.7.9@pocoproject/stable: ERROR: Package '24a7380840586332966890886948deb3b04ba334' build failed
	Poco/1.7.9@pocoproject/stable: WARN: Build folder <redacted>/.conan/data/Poco/1.7.9/pocoproject/stable/build/24a7380840586332966890886948deb3b04ba334
	ERROR: Poco/1.7.9@pocoproject/stable: Error in build() method, line 115
			cmake.configure(source_dir="../poco", build_dir="build")
			ConanException: Error 256 while executing cd 'build' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="4.8" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="<redacted>/.conan/data/Poco/1.7.9/pocoproject/stable/package/24a7380840586332966890886948deb3b04ba334" -DCXX_14="OFF" -DENABLE_APACHECONNECTOR="OFF" -DENABLE_CPPPARSER="OFF" -DENABLE_CRYPTO="ON" -DENABLE_DATA="ON" -DENABLE_DATA_MYSQL="OFF" -DENABLE_DATA_ODBC="OFF" -DENABLE_DATA_SQLITE="ON" -DENABLE_JSON="ON" -DENABLE_MONGODB="ON" -DENABLE_NET="ON" -DENABLE_NETSSL="ON" -DENABLE_NETSSL_WIN="ON" -DENABLE_PAGECOMPILER="OFF" -DENABLE_PAGECOMPILER_FILE2PAGE="OFF" -DENABLE_PDF="OFF" -DENABLE_POCODOC="OFF" -DENABLE_SEVENZIP="OFF" -DENABLE_TESTS="OFF" -DENABLE_UTIL="ON" -DENABLE_XML="ON" -DENABLE_ZIP="ON" -DFORCE_OPENSSL="ON" -DPOCO_UNBUNDLED="OFF" -DPOCO_STATIC="ON" -Wno-dev '../poco'

**Comment by memsharded** [comment]
I think all of the documentation example use 2.8.12 as the minimum. If not, it should be fixed.

The generated ``conanbuildinfo.cmake`` probably shouldn't contain a ``cmake_minimum_required``, because cmake docs: https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html states that this should go **before** the ``project()`` declaration, which also happens before including the generated ``conanbuildinfo.cmake``

**Comment by xbreak** [comment]
Ok, it seems the culprit is https://github.com/pocoproject/conan-poco/blob/master/CMakeLists.txt then.

Any alternative to `cmake_minimum_required` which produce a clear error message would be better than the current scenario in any case. Something similar to what's being done for targets maybe?

    # conanbuildinfo.cmake 
    ...
    macro(conan_define_targets)
        if(${CMAKE_VERSION} VERSION_LESS "3.1.2")
            message(FATAL_ERROR "TARGETS not supported by your CMake version!")
        endif()  # CMAKE > 3.x
        ...

**Comment by memsharded** [comment]
Sure, this can be done, should be easy.

**Comment by jgsogo** [comment]
According to [the docs](https://cmake.org/cmake/help/v3.12/command/cmake_minimum_required.html) (note introduced in CMake 3.3.2):

```
Calling cmake_minimum_required() inside a function() limits some effects
to the function scope when invoked. Such calls should not be made with
the intention of having global effects.
```
Here we only want to make a check, so if we are ok with the standard message (`CMake 2.8.12 or higher is required.  You are running version x.y.z`) then calling this function is fine; if we want a custom message then we should write our own check. @memsharded, do you think we need a custom message?

**Comment by memsharded** [comment]
Obsolete, Conan 2.0 requiring minimum 3.15.
