### ISSUE TITLE
Getting --install-folder within conanfile.py

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#1969]
My deploy runs an operation on a file within the package:

```
from conans import ConanFile
import os

class test(ConanFile):
   name="test"
   version="1.0"
   exports="*"

   def package(self):
      self.copy("*")

   def deploy(self):
      self.run("test.exe --whatever")
```

If you're installing to the current directory that works fine. i.e.

`conan install test/1.0@me/channel`

But when using an install-folder, the cwd in deploy is still the currrent directory from which conan is run:

`conan install test/1.0@me/channel --install-folder ./my_test_tool`

...doesn't work.

This was unexpected for me, but I guess I understand it. However, if deploy won't change the cwd to the install folder, then I need to be able to pass it to self.run...is there a way to get it?

**Comment by memsharded** [comment]
The ``deploy()`` functionality has been developed in parallel to the new ``install-folder`` argument. Yes, maybe it makes sense that deploy() moves cwd to such install folder.

**Comment by rconde01** [comment]
So I assume there's currently no way to get the install-folder from within conanfile.py? Might be useful anyway.

**Comment by memsharded** [comment]
Yes, right now it is lacking because of that parallel development. But should be easy to add it, so ``deploy()`` could reference and use ``self.install_folder``. I have scheduled it for next release.

**Comment by lasote** [comment]
The `deploy()` should be added to `folder_access_test.py` and check the needed folders.

**Comment by rconde01** [comment]
thanks!

**Comment by memsharded** [comment]
Released in conan 0.29, please try it :)

**Comment by rconde01** [comment]
For others it appears (from the code) that deploy now installs to the install folder, and source_folder, build_folder, and install_folder were added. However, the later are not referenced in the documentation AFAICS. Is the ConanFile class documented anywhere? Seems worthwhile...

**Comment by memsharded** [comment]
Yes, the reference in this section aims to cover the ``ConanFile`` class: http://docs.conan.io/en/latest/reference/conanfile.html

In this section, these folders are described: http://docs.conan.io/en/latest/reference/conanfile/attributes.html#folders

Is this what you are looking for?

**Comment by rconde01** [comment]
Yes thanks!
