### ISSUE TITLE
RPATH handling issues when using target-based cmake generator

### ISSUE THREAD

**Issue by weatherhead99** [conan-io/conan#1970]
Hi,
in some recent projects I've been using the targets-based "modern" cmake generator.  This is superior in most ways to the traditional global variables way.

One problem that has arisen a few times for me is when linking with a shared library in a conan package: it is successfully linked, but the RPATH is not set to include the directory of the shared library (yes, even when disabling the OSX style RPATH handling). This is because, I think, the targets created in conanbuildinfo.cmake are interface targets, which don't have a notion of "shared" or "static". 

I note also that in older Cmake documentation, there is reference to a "BUILD_RPATH" property that could be set, but that is ignored by my version (3.6) of cmake. 
The workaround I am currently using looks like this:

CMakeLists.txt:

```
add_executable(foo foo.cpp)
target_link_libraries(foo CONAN_PKG::bar)
set_target_properties(foo PROPERTIES 
    INSTALL_RPATH ${CONAN_LIB_DIRS_BAR}
    BUILD_WITH_INSTALL_RPATH TRUE)
```
which then sets the RPATH in my binary correctly and allows it to be run from the build directory. 
Would it be a good idea to add similar behaviour by default into the cmake generator (appending to the INSTALL_RPATH)

The main issue I can see is that this will collide horribly with a (genuine) build rpath set when you link to a shared library you have buil;t within your own project.

Thoughts?

**Comment by lasote** [comment]
I've no previous experience with rpaths and target approach. We could think about introducing these lines and deactivate them with the current mechanism of SKIP_RPATH parameter in CONAN_BASIC_SETUP. As conan doesn't know if a target is a shared/static or whatever, I wonder if it could affect somehow and break something.

**Comment by weatherhead99** [comment]
as a correction to my previous statement, it is actually the case that the BUILD_RPATH property appears in later cmake versions (I think 3.8). I will try putting together an implementation of this in conan for earlier versions soon.

**Comment by memsharded** [comment]
``cmake`` generator deprecated and removed in 2.0, closing this ticket as outdated.
