### ISSUE TITLE
Solve package reference when download by the API

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1971]
Hi!

When I use the API (version 0.28.0) almost all methods solve the package reference, creating a ConanFileReference from the argument -- the argument is most cases is a string.

But the method *download* uses a different rule for this, breaking the contract with the other methods, the developer must create a ConanFileReference before passing the reference:

https://github.com/conan-io/conan/blob/develop/conans/client/conan_api.py#L435
```
   @api_method
    def download(self, reference, remote=None, package=None):
        # Install packages without settings (fixed ids or all)
        if not reference or not isinstance(reference, ConanFileReference):
            raise ConanException("Invalid package recipe reference. "
                                 "e.g., MyPackage/1.2@user/channel")
        self._manager.download(reference, package, remote=remote)
```

Would be nice follow the current situation:
```
   @api_method
    def download(self, reference, remote=None, package=None):
        if not reference:
            raise ConanException("Invalid package recipe reference. "
                                 "e.g., MyPackage/1.2@user/channel")
        conan_file_ref = ConanFileReference(str(reference))
        self._manager.download(conan_file_ref, package, remote=remote)
```

My point is, it's annoying to check different behaviors from the same API, because the contract is not homogeneous between the functions.

**Comment by memsharded** [comment]
Yes, I agree, the API can be changed to accept a string, like the other methods.

**Comment by uilianries** [comment]
:+1:
