### ISSUE TITLE
ImportError: No module named conans.server.service.authorize

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#1986]
I'm trying to setup a Conan server behind Apache, but I get

```
mod_wsgi (pid=27878): Target WSGI script '/srv/conan/conans/server/server_launcher.py' cannot be loaded as Python module.
mod_wsgi (pid=27878): Exception occurred processing WSGI script '/srv/conan/conans/server/server_launcher.py'.
Traceback (most recent call last):
File "/srv/conan/conans/server/server_launcher.py", line 3, in <module>
from conans.server.service.authorize import BasicAuthorizer, BasicAuthenticator
ImportError: No module named conans.server.service.authorize
```

**Comment by memsharded** [comment]
That is weird, not sure how to setup for running it behind Apache, I guess it is a PYTHONPATH issue, have you set it up properly?

Someone else using Apache for this?

**Comment by Lyberta** [comment]
How do I set it up?

**Comment by Lyberta** [comment]
I worked around it by doing `pip install conan` on the server but would like to know the proper solution. If there is one, can you also update the docs? I assume most C and C++ developers never touched python.

**Comment by memsharded** [comment]
It is just an environment variable, set at the operating system level, so something like ``export PYTHONPATH=PYTHONPATH;/path/to_conan``, (in the rigth location, so it is run before the server launch)

The thing when you run that, you would be running the instance installed by pip, not the instance cloned from source. This might be perfectly ok, I didn't know it was possible. 

I realized that there is an Apache section in the docs: http://docs.conan.io/en/latest/server.html#running-conan-server-using-apache, but we certainly didn't write it. That is why I added the "help wanted" label, it would be great if someone who is running apache could contribute this improvements to the docs.

**Comment by Lyberta** [comment]
What are the downsides of running Conan server from pip? I might as well point the Apache config to code installed by pip.

**Comment by Lyberta** [comment]
I changed the config to run conan installed from pip, here are the relevant lines:

```
WSGIScriptAlias / /usr/local/lib/python2.7/dist-packages/conans/server/server_launcher.py
WSGICallableObject app
WSGIPassAuthorization On

<Directory /usr/local/lib/python2.7/dist-packages/conans>
	Require all granted
</Directory>
```

**Comment by memsharded** [comment]
> What are the downsides of running Conan server from pip? I might as well point the Apache config to code installed by pip.

Actually, none, I just felt a little ugly to point to the code inside the Python "site_packages", but thinking twice, it might be much more convenient to setup, so seems a valid approach.

I think this, together with your lines could be well added to conan docs, do you want to contribute them yourself with a PR, so you get the credit? Thanks very much!

**Comment by Lyberta** [comment]
Made conan-io/docs#371

**Comment by memsharded** [comment]
Good, docs merged. Do you think anything else required here, or this issue could be closed? Thanks!

**Comment by Lyberta** [comment]
I guess I will close it.
