### ISSUE TITLE
CMake build_requirements works on MacOS, fails on Linux

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#1988]
Using build_requirements for cmake works on MacOS:

https://github.com/acgetchell/causal-sets-explorer/blob/master/conanfile.py#L19

I set cmake_minimum_required(VERSION 3.9.0) and Travis-CI Mac has 3.6.2.

This fails on Linux:

https://travis-ci.org/acgetchell/causal-sets-explorer/builds/294142388

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/294142391#L5705

**Comment by memsharded** [comment]
Sorry for the delayed response.
I think the issue is that the default option for cmake version in ``cmake_installer/1.0`` package is cmake 3.6.

You might want to add the ``-o cmake_installer:version="3.9.0"`` somewhere (in your script, or in a profile).

Please tell me if this helps, thanks!

**Comment by acgetchell** [comment]
Is there a way to set `cmake_installer:version` in `conanfile.py`?

**Comment by acgetchell** [comment]
Seems to work now.

https://travis-ci.org/acgetchell/causal-sets-explorer/builds/298266639
