### ISSUE TITLE
Conan server can't be setup in the subdirectory of a domain

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#1990]
I want to run Conan at, say, `https://example.com/conan` behind Apache.

Currently, there is no way to do this. If I set `host_name` to `example.com/conan` and `port` to `443`, the Conan client will try to upload to `https://example.com/conan:443/v1/...`

**Comment by memsharded** [comment]
There are 2 important end-points in the conan api:

- One for "logic", which is the main end-point
- One for transfers uploads/downloads, different to the above. 

You need to configure the second too. There are some details in: http://docs.conan.io/en/latest/server.html#server-parameters ([server] section). Have you set them up, something similar to the Nginx section?

**Comment by Lyberta** [comment]
My first post says what I've tried. I don't know how to make Conan client to upload to `https://example.com/conan`. It appends port after hostname even if hostname contains slashes.

And without slashes it tries to upload to `https://example.com/v1/...`

**Comment by memsharded** [comment]
Oh, sorry, I didn't read well your original post.

It seems it is not possible, could you configure a subdomain ``conan.example.com`` instead of that? If not possible, I think it could be an easy feature

**Comment by Lyberta** [comment]
Yes, this is what I did for now. I guess adding, say, `directory` variable and appending it after `host_name` wouldn't be hard.

**Comment by lasote** [comment]
This PR: https://github.com/conan-io/conan/pull/2213 fixes this issue. (to be released in Conan 1.1)
I tried it with nginx the way is documented in this docs pr: https://github.com/conan-io/docs/pull/546
I don't manage very well with Apache but it has to work.
