### ISSUE TITLE
Skip source step during conan install --build

### ISSUE THREAD

**Issue by sturmf** [conan-io/conan#1992]
I think I misunderstood the conan_sources.tgz file that is exported and its use. 
I always thought once I have exported a package with conan_sources it no longer will need the source step if I build a package. Unfortunately the sources step is still executed during a build and there is no switch to skip it.

What I want to achieve:

I have a conanfile.py e.g. for zlib and want to use this to build the zlib packages on our build server. Our build server (for the sake of reproducibility) does not have access to the internet. Therefore the build server can also not download the sources.
As an admin I now get the zlib conanfile.py and do an "conan source" and "conan export" and "conan upload" to our local conan server.
For this I have to minimally modify the exports_sources line in the conanfile.py from
    exports_sources = ["CMakeLists.txt"]
to
    exports_sources = ["CMakeLists.txt", "%s/*" % ZIP_FOLDER_NAME]

I then run a conan install --build zlib step on the build server for all different configurations we want to support. This step downloads the conan_sources.tgz package as expected but then executes the source step again and tries to redownload the zlib source code from the internet. This of course fails due to no access.

If I now delete the sources step from the conanfile.py then it works as expected. But now I have quite a big diff to the original conanfile.py and have to manually download the source code.

The following would be my dream execution:

On a PC with internet access

 - conan source
 - conan export zlib/1.2.11@lasote/stable 
 - conan upload zlib/1.2.11@lasote/stable 

And on the build server without internet access

 - conan install -o ... --build zlib --skip-source-step
 - conan upload zlib/1.2.11@lasote/stable --all

The --skip-source-step flag of course does not exist!

Am I doing something wrong or did I totally misunderstand conan and the exports_sources part?

**Comment by memsharded** [comment]
Yes, the main issue with this flow is that you are abusing the ``conan source`` command and the ``source()`` method. So you are exporting, and adding to the ``exports_sources`` the code that you are retrieving with the ``source()`` method, which is mainly designed to be the way to retrieve the source code. So you have both procedures in place.

I don't fully get how do you manage to ``exports_sources`` the source code you want to store into the recipe, if you don't do something like: ``exports_sources = "src/*"`` too, and not only that change for the CMakeLists.txt

IMO, what should be removed is the ``source()`` method, and the ``conan source`` invocation. Depending on your layout, and how do you store the sources for zlib originally, I think the workflow that could makes sense would be:

```bash
$ git clone <url> src  // clone to the "src" folder, for example
$ conan export zlib/1.2.11@lasote/stable
$ conan upload zlib/1.2.11@lasote/stable
```

If you still want to abuse the ``source()`` method, I think this could help: http://conanio.readthedocs.io/en/latest/reference/conanfile/attributes.html?#in-local-cache
 
The ``in_local_cache`` will be True when executed in the ``install`` step, you can use that. 

Please tell me if this helps.

**Comment by sturmf** [comment]
Ahh I see. The zlib package is in a way that it downloads the source as a zip and extracts it into a zlib-version folder. So there is no src/* and therefore this is enough "%s/*" % ZIP_FOLDER_NAME

My goal is to be able to cache a random recipe from the internet inhouse. For this I right now have the following options:

- Save the sources zip somewhere else and change the url in the recipe
- Remove the sources step and write script to download and extract myself before export, add source to extract_sources
- Open up internet connections from the build server with the danger that the build breaks if the hosting server is down or the archive was moved.

I therefore would really like if conan could get a way to handle this properly. E.g. by somehow freezing the archive after the sources step and being able to continue the builds from this state. The motivation for this is that the step of downloading the source is often very different between the packages and I don't want to delete the source step from the recipe just to write something very similar and another batch script before the export. Sometimes its a git clone, sometimes a download and unzip. Some need to move files around after unpacking etc.

**Comment by memsharded** [comment]
>  So there is no src/* and therefore this is enough "%s/*" % ZIP_FOLDER_NAME

Ok, I didn't read the code properly, this is fine.

I am not sure if it was clear my above comment. I think you could be mostly fine with:

```python
def source(self):
      if self.in_local_cache:
            return
      # your download
```

In that case, the ``source()`` will only execute when you run ``conan source`` in your user folder, but not in the local cache, when you do ``conan install``. Did you try it? If you want to chat (slack?) please tell me.

**Comment by sturmf** [comment]
Thanks this now works really great and my only modifications to the original package files are the extended export_sources line and the early return in the source method.

I still would prefer a separate switch for the "install --build" step so I could drop threturn statement change too but am really happy with the current state already.

**Comment by memsharded** [comment]
At the moment, it seems a bit of burden to the command line, for a not frequent use case that has a good enough solution in the recipes. So I think by now we can close this issue, but please ask again if things change or open a new issue for further questions. Thanks!
