### ISSUE TITLE
Add 'install' option to not add conan files

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#1993]
Currently if I do conan install mypackage/ver@me/channel in a deploy scenario, the deployment folder will contain conaninfo.txt, conanmanifest.txt, and deploy_manifest.txt.

There are some scenarios where you don't want those extra files, so it would be nice to have an option to not add them.

**Comment by memsharded** [comment]
I don't think that conaninfo.txt and conanmanifest.txt would be copied/deployed unless you tell that in the ``deploy()`` method code. In any case, I think you could just remove them from your ``deploy()`` method too (like ``os.remove``), have you tried it? Doing it as a command line option, would lead to many options, like "dont_create_manifest", "dont_create_info", "dont_create_deploy_manifest"...

**Comment by rconde01** [comment]
Well - i was just thinking --dont_create_anything...but sure, that workaround should work. I was just deploying self.copy("*")...for a complex dir structure it would be fairly tedious to list each file.

**Comment by rconde01** [comment]
Although, a catchall option would be helpful if you decide to add additional files in the future.

**Comment by memsharded** [comment]
You also have the ``excludes = "*.txt"`` argument to ``self.copy("*",...`` you could use just to exclude those files instead: http://docs.conan.io/en/latest/reference/conanfile/methods.html#package
