### ISSUE TITLE
GTest/GMock doesn't work

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#1997]
Awhile ago, GMock used to work on Conan on Linux and MacOS:

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/247382550#L2840

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/247382551#L3002

That's no longer true:

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/298266640#L6911

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/298266641#L4871

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/298266644#L5862

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/298266645#L4690

The directions in https://github.com/lasote/conan-gtest no longer work.

Are there updated directions for getting GMock/GTest to work with Conan?

Thanks.

**Comment by SSE4** [comment]
I think this one can be closed, as we now have GTest in conan centre:
https://bintray.com/bincrafters/public-conan/gtest%3Abincrafters
https://github.com/bincrafters/conan-gtest
