### ISSUE TITLE
OUTPUT: install result checking

### ISSUE THREAD

**Issue by jeroendv** [conan-io/conan#1998]
is there an easy way to check if a `conan install`  invocation was effectively a no-op?
* all deps were already installed and up to date
* the generated files remained unchanged
* ...

**Comment by lasote** [comment]
No, there is no mechanism to check that.

**Comment by jeroendv** [comment]
I'm working on a python package that integrates with a Visual Studio project using MSBuild targets that:
* generates a target file and imports it in the projects
* calls conan install -g visual_studio_multi on a project as pre build step

But because the property files are not loaded in a the curretn msbuild process that process needs to be terminated and restarted if and only iff the install action was not a no-op.

**Comment by lasote** [comment]
I see. It's related to #1895, #1757 and improving the public conan python API, that could provide somehow information about the operations that have been executed.
