### ISSUE TITLE
Umlauts are "not allowed symbols" in a password

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#20]
The password `demo` works, but `demö` is rejected:
```
$ conan upload -r local silicium/0.1@tyroxx/testing
Downloading conanmanifest.txt
[==================================================]                  
Uploading silicium/0.1@tyroxx/testing
Please log in to perform this action. Execute "conan user" command. If you don't have an account sign up here: http://www.conan.io
Please enter a password for "tyroxx" account: 
ERROR: Password contains not allowed symbols
```

**Comment by memsharded** [comment]
This is a problem with the underlaying library we are using, so we have not been able to fix it quickly. We are investigating other ways to solve this issue, if you could try to use another password meanwhile, please do so. If you need help to reset your password, please write to info@conan.io

**Comment by memsharded** [comment]
The underlaying library encodes as "latin-1", so very little we can do about those especial characters. The best we could try to do (without having to fork and maintain such fork of the library) is:
```python
            password = password.decode("utf-8", "replace")
            password = password.encode("latin-1", "replace")
```
Please not that this actually changes the characters by "?", which could be a security problem for passwords containing only special characters. I suggest keeping the current behavior, and avoiding those characters. Any other suggestion?

**Comment by TyRoXx** [comment]
The conan.io web site should at least disallow characters that will not work.
The server application should refuse to run with a configuration containing disallowed passwords.

**Comment by memsharded** [comment]
+1. Let's try to fix it that way for next release.

**Comment by memsharded** [comment]
Hi @TyRoXx , this should be fixed now, let's close it, but please report if you have any further problem to re-open the issue. Hopefully the underlaying lib is eventually upgraded and uses a better encoding and not just latin-1, we will keep an eye on this.
