### ISSUE TITLE
Warn if no files were copied by self.copy

### ISSUE THREAD

**Issue by snizovtsev** [conan-io/conan#200]
It should be nice to receive a warning (or maybe an error) when no files were copied by self.copy inside a package() method. I think that this situation means that something goes wrong in the most cases and will help to address many issues.

The message should contain value of pattern and src arguments.

**Comment by memsharded** [comment]
+1

**Comment by lasote** [comment]
+1 but I (probably my bad) use múltiple copies for DLL, lib, *.a, .... I know probably just one line will copy files per package depending on the settings... Maybe opt-out behaviour? I don't like too much to put a lot of ifs on package method.

**Comment by memsharded** [comment]
I think that not necessarily a opt-out, but the copy function can gather some data, and at the end of the package() method, it could either print some info, like "packaged 32 files", or warn, like "WARN: package() did not copied any files".

**Comment by lasote** [comment]
+1 to a global report
