### ISSUE TITLE
tools.download appends instead of overwriting

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2000]
Hi,

On Windows, setting the `tools.download(overwrite=True)` parameter does not truncate before writing, and simply append the whole file body multiple times.

I haven't tested on other platforms yet.

**Comment by SSE4** [comment]
yes, seems so:
```                if file_path:
                    mkdir(os.path.dirname(file_path))
                    with open(file_path, 'ab') as handle:
                        dl_size = download_chunks(file_handler=handle)
```
notice it uses 'ab' (append binary)

**Comment by theodelrieu** [comment]
Is that the wanted behavior? In that case the parameter name and the documentation are quite misleading IMO.

**Comment by lasote** [comment]
It is not the intended behavior. It's a bug.
