### ISSUE TITLE
conan create doesn't build package with wildcard options

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2001]
I'm currently trying to build a shared library with a long name, I thought I'd give the new wildcard options a try:

`conan create theo/test -o *:shared=True`
> ERROR: Missing prebuilt package for 'longlibname/0.1@theo/test'
Try to build it from sources with "--build longlibname"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

Note that it has no dependencies, and the following command works fine:
`conan create theo/test -o longlibname:shared=True`

EDIT: add missing `-o`

**Comment by SSE4** [comment]
your command line misses -o parameter, it should be:
`conan create theo/test -o *:shared=True`

**Comment by theodelrieu** [comment]
Oh sorry I missed that when reporting the issue, the original command actually had the `-o`... Will edit right away

**Comment by theodelrieu** [comment]
Also, adding `--build longlibname` does not fix the issue. I still get the same error
