### ISSUE TITLE
Conan upload without sources and remote shouldn't fail always

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2003]
```bash
$ conan install something (binary exists, sources not downloaded)
$ conan remote remove <myremote>
$ conan upload cmake* -r=local --all
Are you sure you want to upload 'pkg/1.0@conan/stable'? (yes/no): yes
Uploading pkg/1.0@conan/stable
ERROR: Trying to upload a package recipe without sources, and the remote for the sources no longer exists
```

It shouldn't fail, as it doesn't have ``exports_sources``, it won't have missing sources.tgz to download.

**Comment by memsharded** [comment]
Current workaround is to NOT remove the old remote until it is uploaded to the new one.

**Comment by lasote** [comment]
So the issue title should be "Conan upload without sources and remote **shouldn't** fail always" or am I missing something?

**Comment by memsharded** [comment]
Yes, fixed
