### ISSUE TITLE
Consider to allow mixing the binary packages from different repositories

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#2007]
I get that it can be problematic to get a binary from a different repository where the recipe lives. Because it can be outdated.

But, if it's an opt-in behavior, maybe we can allow it. 
If you are using, for example, a local server to "cache" some recipes and binary packages(to avoid networking issues like in conferences 😉 ). So you install the recipe and a package and push it to the local repository, then you remove all local cache and start using the package pointing to the local repo. But then, you want to retrieve a different binary package from the central repository, and you can't do it because it's pointing to the local one. This situation is a pain, because of #2006 you don't know the real package ID to download it using `conan download`.

Also, think about people distributing architectures in different repositories, I know that Artifactory virtual repositories are the way to go, but it's just another one use case that supports it.

What about checking if the recipe for both remotes is the same?

Let's discuss the problems!

**Comment by memsharded** [comment]
With revisions, this is now the behavior in 2.0, package binaries can be retrieved from any remote (as long as it belongs to the same used revision), this can be closed.
