### ISSUE TITLE
ERROR: Unauthorized on upload

### ISSUE THREAD

**Issue by bilke** [conan-io/conan#201]
I am following the getting started tutorial and now I want to upload my packages but it fails:

```bash
$ conan upload Hello/0.1@demo/testing --all
Uploading Hello/0.1@demo/testing
ERROR: Unauthorized
```

My username and password are set. I even tried to reset them (switching to a different user and back with `conan user username -p password`). Anything else I can try?

**Comment by memsharded** [comment]
Can you log in without problems in the web page? after login it should redirect to your user page, something like conan.io/bilke

**Comment by bilke** [comment]
Yes the website login works. `python build.py` does not work:

```
Hello/0.1@bilke/testing: Not found, looking in remotes...
Hello/0.1@bilke/testing: Trying with 'conan.io'...
Hello/0.1@bilke/testing: Trying with 'local'...
Hello/0.1@bilke/testing: WARN: Unable to connect to local=http://localhost:9300
ERROR: All remotes failed
```

**Comment by memsharded** [comment]
Just as a test, try removing the localhost remote, just in case:
```bash
$ conan remote remove local
$ conan remote list
```
Then try to search the remote:
```bash
$ conan search -r=conan.io
```
Please tell me if this works.

**Comment by bilke** [comment]
Yes this works.

**Comment by memsharded** [comment]
I have just realized, there is a mismatch between the "demo" user and the "bilke" one. The "demo" user is a default user that is initialized also in the local server configuration for easy testing, but should be replaced by your username if you want to upload your recipe and packages. 

Please check this. It is very likely that the docs should be improved in this sense.

**Comment by memsharded** [comment]
```bash
$ conan search
```
This will list your local packages. 
Using ``conan copy`` you might be able to rename all your packages if necessary:
```bash
$ conan copy Hello/0.1@demo/testing bilke/testing --all
$ conan remove Hello/0.1@demo/testing
```

**Comment by bilke** [comment]
I also tried to setup the demo package as described in [conan-package-tools](https://github.com/conan-io/conan-package-tools) but it [fails the same way in Travis](https://travis-ci.org/bilke/conan-hello/jobs/116388101).

Yes I noticed the wrong demo user as well but it still fails:

```
$ conan search
Hello/0.2@bilke/testing
    Package_ID: ed52a5841768e616e14f89e1f52ae18ee5d1456a
            (x86_64, Release, apple-clang, libc++, 7.0, Macos)

$ conan upload Hello/0.2@bilke/testing --all
Uploading Hello/0.2@bilke/testing
ERROR: Unauthorized
```

**Comment by bilke** [comment]
Do I have to create the repository on conan.io manually?

```bash
$ python build.py
Hello/0.1@bilke/testing: Not found, looking in remotes...
Hello/0.1@bilke/testing: Trying with 'conan.io'...
ERROR: Unable to find 'Hello/0.1@bilke/testing' in remotes
```

**Comment by memsharded** [comment]
No, it will be automatically created when you upload.

Does your password contains special characters? 
Maybe you could try to delete the localdb, please remove the file ~/.conan/.conan.db, and try to upload again. It should ask for your user and password again.

**Comment by bilke** [comment]
Thanks a lot removing the local database works! The Travis error is unrelated to this.

**Comment by memsharded** [comment]
Excellent! :)
Just concerned about what could have happened, I have not been able to reproduce it. Please reopen or report if anything else fails, thanks!
