### ISSUE TITLE
conan install hangs forever

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2010]
Hi,

I had a weird issue yesterday, I have a package depending on `sqlcipher/3.4.1@theo/stable` that I've already built and stored in my local cache.

When I tried to run `conan create mypkg/0.1@theo/stable`, it just hanged at the requirements step.
I can reproduce the issue with this small `conanfile.txt`:

```ini
[requires]
sqlcipher/3.4.1@theo/stable
```

Here is the full recipe of `sqlcipher`:  [sqlcipher-conan.zip](https://github.com/conan-io/conan/files/1463707/sqlcipher-conan.zip)

And here is the conan trace file: [trace.txt](https://github.com/conan-io/conan/files/1463709/trace.txt)

I'm on Windows 10 by the way, using conan 0.28.1. I've tried to reinstall it with no success. I'm a total n00b in Python debugging, I'll see what I can find.

EDIT: I didn't have this issue at work, only on my home PC
EDIT2: It blocks on client/manager.py L 368: ` deps_graph = graph_builder.load(conanfile)`.

**Comment by theodelrieu** [comment]
I think this is the culprit: `with self._client_cache.conanfile_write_lock(conan_reference):` in proxy.py(126)

The `conan_recipe` is OpenSSL, and the `rw_count` file is at `1`, I also have a `locks` folder even after restarting the computer. I must have cancelled/kill conan at the wrong time...

But heh, what would be a release with multi-threading support without deadlocks and race-conditions :D

**Comment by memsharded** [comment]
Yeah :D :D 
To fix that, it should be enough to completely remove the offending package from the cache with a ``conan remove PkgName* -f``

Yes, maybe a message should be added, good idea.

**Comment by agurtovoy** [comment]
FWIW, I had the same issue after terminating a `conan install` that was taking too long (was on a super-slow network). Consequent `conan install` would just hang after listing out the current configuration, no diagnostics. Following @memsharded advice above helped.
