### ISSUE TITLE
ConfigureEnvironment: 'libstdc++11' is not a valid 'settings.compiler.libcxx' value on OS X

### ISSUE THREAD

**Issue by snizovtsev** [conan-io/conan#202]
I've just updated to conan 0.8 with libcxx support and get this error:
```python
## configure_environment.py ##
            # Append the definition for libcxx
            all_cpp_flags = copy.copy(self._deps_cpp_info.cppflags)
            if self.libcxx:
                tmp = "-D_GLIBCXX_USE_CXX11_ABI="
                tmp += "1" if self.libcxx == "libstdc++11" else "0" # Exception occurs here
                all_cpp_flags.append(tmp)
```
for (os x default) apple-clang compiler:
```
    apple-clang:
        version: ["5.0", "5.1", "6.0", "6.1", "7.0"]
        libcxx: [libstdc++, libc++]
```
on this (conanfile.py) code:
```python
        env = ConfigureEnvironment(self.deps_cpp_info, self.settings)
        self.run("%s && ./configure --prefix=\"$PWD/install\" && make install" % env.command_line)
```

**Comment by memsharded** [comment]
Yes, I'd say that libstdc++11 is not a valid setting for apple-clang. In apple-clang, you can choose between libstdc++ and libc++. You can check the default settings file: ~./conan/settings.yml

Please tell us if this is a mistake and it is indeed possible to use such setting, but up to my knowledge such libstdc++11 implementation is only available in gcc. If that makes sense to you, you can always edit the ~./conan/settings.yml and add such setting. Thanks!

**Comment by snizovtsev** [comment]
@memsharded I'm not trying to use libstdc++11 on apple-clang. The problem is that ConfigureEnvironment is broken (produces exception) on apple-clang with default settings.yml.

**Comment by snizovtsev** [comment]
In other words, on my (default) settings with [compiler=apple-clang and compiler.libcxx=libc++] ConfigureEnvironment.command_line() raise such exception.

**Comment by memsharded** [comment]
Oh, sorry, I see. This seems a bug, indeed, I'll have a look asap. Thanks for reporting.

**Comment by memsharded** [comment]
Hi @snizovtsev,

There is a PR to fix this, how have you installed conan? Homebrew? Pip? Would you be comfortable running from source? (We can assist in that, if you want, it is not difficult). I'd like to know it, maybe this deserve releasing a minor 0.8.1, but it is usually better if can be tested from latest sources, to be sure no further problems appear. Thanks!

**Comment by lasote** [comment]
Hi! I've generated a 0.8.1rc1 package with pip. Thanks for report it! :+1: 

    pip install conan==0.8.1rc1

**Comment by snizovtsev** [comment]
Hi, @lasote ! conan 0.8.1rc1 from pip works fine now. Thank you!
