### ISSUE TITLE
Wrong dependencies link order

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2029]
Hi,

I've been trying to compile OpenSSL with Zlib support lately on Linux, but the static builds always fail because of the position of zlib in the link command line. It's indeed the very first, and should be after `libcrypto` and `libssl`. (I'm not using `tools.collect_libs` by the way)

Should I add `libz` to OpenSSL's `self.cpp_info.libs`? Shouldn't Conan manage this automatically?

I'm wondering what is the best way to deal with this kind of issue.

**Comment by theodelrieu** [comment]
Seems related to #1875

**Comment by memsharded** [comment]
Yes, could be very well the same issue. Lets continue there.  It would be great if you could try running from sources, from "develop" branch, and see if it is gone now. Thanks!
