### ISSUE TITLE
Question on method requirements() with certain options

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#2031]
From `requirements()` here http://docs.conan.io/en/latest/reference/conanfile/methods.html#requirements

For example if `zlib` had a Conan option called `version` with values of say `1`, `2` and `3`, how could in configure logic of `self.requires("zlib/1.2@drl/testing", private=True, override=False)`  if only a `version` option of value `2` is a requirement?

Can options be configured in `self.requires()` currently ?

Note: I don't want to do this with zlib, zlib is just an example that fits my lib structure.

**Comment by lasote** [comment]
I think I don't get it, are in your example requiring zlib conditionally? you can access to the requirements options using `self.options["zlib"].myoption`. does it help?

**Comment by Twoflower2** [comment]
@lasote I got this sorted thanks.
