### ISSUE TITLE
Default output directory is different for RelWithDebInfo build type (for VS)

### ISSUE THREAD

**Issue by salessandri** [conan-io/conan#2032]
When creating a package using Visual Studio as the compiler I run into issues with the `test()` phase. It would fail with, only when compiled using `RelWithDebInfo` build type:
```
test package: Running test()
'.\example' is not recognized as an internal or external command,
operable program or batch file.
ERROR: PROJECT: Error in test() method, line 21
        self.run(".%sexample" % os.sep)
        ConanException: Error 1 while executing .\example
```

I dig into why and the reason is that in `macro(conan_output_dirs_setup)` the default output directories are not changed for `RelWithDebInfo`, only for `Debug` and `Release`.
That leads to the example binary be located in `<build_folder>/bin/RelWithDebInfo/example.exe` instead of the expected `<build_folder>/bin/example.exe`.

I can make a PR to fix the value for `CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO` and `CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO`.

**Comment by memsharded** [comment]
Yes, I think it makes sense. If you could contribute that PR that would be great, thank you!

**Comment by SSE4** [comment]
@memsharded  this one seems to be fixed
