### ISSUE TITLE
conan config install removes referenced zip file

### ISSUE THREAD

**Issue by mmatrosov** [conan-io/conan#2035]
I prepared .zip file with config and saved it locally. When I do `conan config install file.zip`, it works fine, but `file.zip` is deleted after it is imported.

Conan v0.28.1.

**Comment by memsharded** [comment]
Yes, this is known. This was reported in this issue (https://github.com/conan-io/conan/issues/1951), and has already been fixed, it will be in next 0.29 release (hopefully next week).

 Thanks for telling anyway! :)

**Comment by mmatrosov** [comment]
Ok, great to know. Should have been searching a little longer :)
