### ISSUE TITLE
CMAKE_SKIP_INSTALL_RPATH is not set on macOS

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2038]
Hi,

According to the docs `conan_basic_setup()` sets `CMAKE_SKIP_RPATH 1` on macOS.
However, `otool -L my_installed_lib.dylib` gives the following output:

>@rpath/libmy_installed_lib.dylib (compatibility version 0.0.0, current version 0.0.0)

Whereas the one in the build folder doesn't have the `@rpath/` prefix.

Is this intended? I'm kind of a n00b with rpaths.

EDIT: setting `cmake.definitions["CMAKE_SKIP_INSTALL_RPATH"] = "ON"` in my recipe fixes the issue.
EDIT2: that's weird though, the CMake doc says that CMAKE_SKIP_RPATH includes CMAKE_SKIP_INSTALL_RPATH...

**Comment by lasote** [comment]
Yes, it should work only with CMAKE_SKIP_RPATH according to the docs, but I didn't try it with install.
Can you see the message "Conan: Adjusting default RPATHs Conan policies"? In that case, CMAKE_SKIP_RPATH is set.
In any case, `cmake.definitions["CMAKE_SKIP_INSTALL_RPATH"]` is totally ok, I would recommend a custom rpath management by recipe creator, we learned that there are several different approaches with RPATHS, so we introduced the SKIP_RPATH to let the user adjust it.

**Comment by theodelrieu** [comment]
I've upgraded my CMake to v3.9.6, and had a warning about this [CMP0068 policy](https://cmake.org/cmake/help/v3.9/policy/CMP0068.html).

I've removed the `conan_basic_setup(TARGETS)` line in my CMakeLists.txt, and settings explicitely `set(CMAKE_INSTALL_NAME_DIR "")` effectively removed the `@rpath/` from the installed shared library.

Having this line with the `conan_basic_setup` had no effect though.

**Comment by lasote** [comment]
If you remove the `conan_basic_setup(TARGETS)` you are going to lose many things, the targets of the dependencies, for example.

You can deactivate the `rpath` management calling `conan_basic_setup(TARGETS SKIP_RPATH)` and adjust all manually.

About the recommendation of clearing the install_name, and rpaths in general. You probably don't want your executables and shared libraries containing an absolute path to your local cache, because if you share these binaries, they will be useless in another computer.

But, there are some other approaches, for example using the `@executable_path` in Macos to specify a relative path to the executable.

**Comment by theodelrieu** [comment]
Thanks, I spent the whole day learning a lot about rpaths :)

However I believe the issue is in CMake, I rollbacked everything to use `conan_basic_setup(TARGETS)`, and I still get the `@rpath/` prefix only on the installed binaries.

I trimmed the CMakeLists.txt to look almost exactly to the bzip2 one, but still get the same issue. I'll simply set `CMAKE_INSTALL_DIR_NAME` to an empty string to workaround that.

I will post details if I discover something, thanks for the help!

**Comment by theodelrieu** [comment]
I do still think this line from the CMP0068 is quite relevant to my issue:

>If SKIP_BUILD_RPATH, CMAKE_SKIP_RPATH or CMAKE_SKIP_INSTALL_RPATH were used to strip the directory portion of the install_name of a target, one may set INSTALL_NAME_DIR="" instead.

I rechecked every shared library, and those using CMake's `install` method have the same issue. Applying the proposed fix (e.g. INSTALL_NAME_DIR="") works for every case.

**Comment by lasote** [comment]
Thanks, yes, probably we should add it. I'm a little worried about break something, but probably we should do it.
