### ISSUE TITLE
Package name lenght

### ISSUE THREAD

**Issue by Tedlar** [conan-io/conan#2046]
After using conan for some time i found one assumption really disturbing.
Why maximal package name is set to 50 characters?
I need to use namespaces while creating packages names (auto generated data structures).
Because of that names can reach even 100 characters.
Same problem existed in npm and ultimately name's max size was pushed from 50 to 214 characters.
Right now I need to implement custom methods to shorten names but I am unable to assert name's uniqueness and what's worse created naming is not use friendly.

**Comment by memsharded** [comment]
> Why maximal package name is set to 50 characters?

50 characters was indeed arbitrary, as any other lenght would be, but it seemed to be a good size to be able to express many things and allow reasonable naming. Even your question ``Why maximal package name is set to 50 characters?`` has less than 50 characters. Regarding uniquenes, sha1 is capable of providing good uniquenes with 40 characters, so adding 10 more might help with this.

The underlying reasons: Trying to minimize problems with paths, as many tools have issues, especially in Windows, with long path names or path with spaces. Conan has provided a ``short_paths`` feature that can help with this, but even with it, long package names, together with long path names created by tools (for example CMake temporary dirs), makes the whole thing more fragile than using short names and avoiding spaces.

Consider that conan already has 2 added namespaces: the user and the channel. With those 3, you already get 150 characters of naming package. If we pushed that limit to 200, then the full package name would have a limit of 600, then you get something that is fundamentally broken in most Windows. Also, servers, specially Bintray that host and serves billions of packages every month, has to index and address those package names. Keeping them bounded helps a lot.

**Comment by Tedlar** [comment]
I will try with placing some part of naming into 'user' and 'channel' parameters.
Still I think it's a bit ugly get around.
It would be great if there where option to enable longer package names for linux environments.
Additionally only extending size of package's name have meaning. User and channel are big enough.
Also individual components of a filename in Windows OS are limited to approximately 255 characters.
So the full package name could be 150+ 50 + 50 = 250 characters, just below the limit.

**Comment by memsharded** [comment]
> So the full package name could be 150+ 50 + 50 = 250 characters, just below the limit.

No way, the conan cache is already at ``C:\Users\<youruser>\.conan\data``. You can configure that, but even though, inside the package name, there are subfolders for export, source, build, package, etc. The build and package subfolders contain in turn subfolder with the respective package ID which is a sha1 40 characters long hash.

**Comment by Tedlar** [comment]
I'm returning empty handed.
I tried your solution and changed packages naming
from: `<prefix>.<model>.<module>/<version>@<user>/<channel>`
to:     `<prefix>.<model>/<version>@<module>/<channel>`
example: `PSM.DDS.Test/0.1@Common/test`

Unfortunately such configuration creates error when packages are requiring each other:
`PSM.DDS.Test/0.1/Simple/tech requirement PSM.DDS.Test/0.1@Common/tech overriden by your conanfile to PSM.DDS.Test/0.1@Simple/tech`
`ERROR: Loop detected: PSM.DDS.Test/0.1@Simple/tech`
:(

**Comment by Tedlar** [comment]
Is there any option to locally change length of `package` parameters `name`, `user`, `channel`?
from: `50`, `50`, `50`
to: `100`, `25`, `25`
| parameter | value | change |
| name | 50 | 100 |
| user | 50 | 25 |
| channel | 50 | 25 |

**Comment by memsharded** [comment]
There is no external configuration, but the code is pretty straightforward, the validation is here:

https://github.com/conan-io/conan/blob/c6fe5b21a92b71128302f2896fb071864ddd6785/conans/model/ref.py#L51

Should be easy to fork and provide your own validation logic. Just increase the ConanName max_chars, and then add a check over the full lenght.

Doesn't seem something that we can change in our codebase, will think if there is someway to maintain these custom changes more easily.

**Comment by Tedlar** [comment]
Thx, will do for now :)
