### ISSUE TITLE
Possible command alias (like git)

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2050]
So users can define their own commands.

Idea come from https://github.com/conan-io/conan/pull/2034 and https://github.com/conan-io/conan/issues/1233

**Comment by jgsogo** [comment]
Shall this feature be included in the queue? Anyone has asked for (or think about) it again?

**Comment by memsharded** [comment]
Not again. I suggest closing until there is good evidence of its need by users.

**Comment by cleeland** [comment]
So, if you're not going to implement the general purpose alias feature, then implement the `clean` subcommand from which this more generic idea was born.
