### ISSUE TITLE
README.md is wrong

### ISSUE THREAD

**Issue by skaller** [conan-io/conan#2051]
The README says to run tests by 

```nosetests```

No such file exists.

**Comment by memsharded** [comment]
Nosetests is a requirement that should have been previously installed with:

```bash
$ sudo pip install -r conans/requirements_dev.txt
```

These setup steps are already described in the README, did you follow them?

**Comment by skaller** [comment]
Yes, I did them. And its extremely rude to close an issue before you understand it. If a client has a problem, its a problem. I followed the instructions, they did not work. Hence, your instructions are wrong. Necessarily.

If indeed nosetests is an external program, the reason it didn't work is that it is not on my PATH. Things installed by pip(s) on my system do not end up on a PATH, I have to run them with an absolute filename.

Your instructions INCORRECTLY assumed the bin directory containing nosetests was on my PATH when it wasn't.

There is a reason it is not on a path. I have BOTH Python2.7 and Python3.4 installed. And I probably have a built from source Python or two as well. To run anything that is Python, I have to be specific which one I want, which program I want.

I run OSX, the system Pythons are not mutable. Instead, stuff goes in my HOME/Library etc. I did not do that, Apple uses this idea, and many packages of all kinds put stuff there. Stuff installed there by mysterious commands like pip does not run. In fact, in general, pip doesn't work either, even with sudo, pip crashes. It took me hours to find out I how to install conan because some of the instructions are just wrong. Including the one I refer to here.

**Comment by skaller** [comment]
FYI for the *same* reason as above, the command ```conan``` does not work. It is not on any PATH. I have other Python stuff installed. For example Pygments which I use heavily. And Sphinx. Pygments is installed in the *system* library. Sphinx is installed in HOME library. So Pygments works out of the box. I have to run sphinx with full pathname.  And that would not work if sphinx dispatched to another executable without ensuring it was absolutised relative to sphinx itself, unless it was dispatching to a *system* program.

Configuration is a major hassle on all systems. OSX is really hard because some people also run brew or port and one ends up with duplication left right and centre. I ended up deleting all traces of brew and refuse to use it because developers make too many assumptions that end up being wrong on someone else's system, and magical stuff like package managers does its best to *hide* these issues, which means when it fails, the failure is very hard to track down.

I have these kinds of issues on Windows and Linux as well. Even with debian using apt, in fact that often makes things worse, because stuff I build from source duplicates stuff which is implicitly installed as a dependency of something else, and the stuff I built from source goes in `/usr/local` not '/usr' and shadows the `apt` installed programs and libraries.

**Comment by memsharded** [comment]
Sorry for closing the issue in that way, our mistake.

It was mainly the reaction to an issue that also sounded rude itself. Let me suggest the following alternate issue writing:

------------------Begin of issue -------------------------
Title: **Nosetests is not found after following README instructions**

Hi!. I am trying to run the conan tests, and after following the README steps, all worked correctly without issues, I run:

```bash
$ nosetests .
> nosetests command not found
```

My OS is OSX, version XXX, I am using python version XXX, I installed conan requirements with ``sudo``. Could you please help me with this issue?

----------------End of issue ------------------------------

There are a couple important things here:
- I can guarantee that we can go to any SW documentation out there and find something that doesn't work as expected, fail in some scenario, etc. Telling the documentation is WRONG, doesn't help, and it is not nice for maintainers of an Open Source projects that many times are putting hundreds of hours of their spare time into that project. Being so strongly categoric like: ``I followed the instructions, they did not work. Hence, your instructions are wrong. Necessarily.`` doesn't help either. Just putting gasoline to the flames. It is the same if someone responded: "Your issue is WRONG", because it is, ``nosetests`` file indeed exists in your system, it is just that it is not in the PATH. But it exists, so your issue statement "No such file exists" is fundamentally wrong.
- Thus, configuration is important. What can work in some cases, might fail in others. Saying something fails without providing a little context doesn't help
- Be nice. Just one "Hi!", and one "please" can make a difference. You can navigate other issues in this repository, I think you will find very little rudeness in the thousands of issues and comments there, actually quite the opposite. 


Said this, I agree that the README could be improved, adding comments and details of what could fail in different scenarios, and how to workaround those failures.

**Comment by skaller** [comment]
I apologise if my issue was viewed as rude. Late night, after hours trying to get stuff working.

**Comment by skaller** [comment]
I will comment, in general, that a whole lot of software of all kinds has similar problems.

Indeed, Conan itself is trying to solve one of these, which is why I was interested. However it is continually frustrating that all modern software has multiple complex dependencies, and fail due to a combination of trying to use "the user is dumb" systems like "pip" instead doing stuff the long hand way, which although harder, allows the developer to isolate issues more easily, by, for example, actually seeing where things get installed, or exactly what causes an issue.

The problem then propagates, to the unfortunate point that to be successful, it is best for software to *eliminate* reusability, rather than promote it. The scope of this problem cannot be underestimated, my rough guess is that 70% or more OSS software projects don't build or install at all.

In this case, I couldn't get pip to install conan so I gave up and cloned the repository. Generally, if a command isn't in the current directory, details have to be given how to ensure it is made available to run. However pip did install the dependencies. I have no idea where. I have no idea whether this was Python3 or Python2.7 site-packages or *which* site-packages since I have two lots of them, one set in the OSX system `/Library` and another set in `$HOME/Library`. And since I use pip as well as `sudo pip`, both of which failed, I don't really know if a partial install occurred or not. Also I sometimes build Python from source, which means I end up with yet another Python in `/usr/local` as well.

When I tried to run conan manually, it failed too, unable to find a required module to import. Presumably because some required PYTHONPATH or something is not properly set. As mentioned earlier I do not set such variables universally, because of multiple versions. Python3 software in my own system has to set its own path for finding packages (outside the system Python3 I mean).

My own system manages itself, once it is installed, but I have to hand hold every user through the build and installation process (especially on Windows). That system, BTW, is a C++ code generator with run time library written in C++. So conan might be useful, and I might be able to contribute to it. The problem is, as usual, dependencies: if I use it, *my clients* would have to install it as well. And typically that means my own system has to install it automatically, which means it needs to be pure code, with no external dependencies. Otherwise I have to organise to install *them* as well, and the dependency chain becomes too hard to manage.

This is how I use fbuild, the Felix bootstrap builder, which is a complex advanced build system written in Python3. It is part of the repository. Its the only way to ensure it the integration works. My system reduces the dependencies to Python3, Ocaml, and a C++ compiler. Everything else is part of the repository so the user *doesn't* have to install and configure it.

**Comment by memsharded** [comment]
> I apologise if my issue was viewed as rude. Late night, after hours trying to get stuff working.

No problem, I know how it feels too, happens to everyone, sorry too. So lets try to improve the install steps.

Actually I think that the first issue that should be addressed is this:

> In this case, I couldn't get pip to install conan so I gave up and cloned the repository.

It is very important that this works in most cases. Are you using virtualenvs for this task?  (I strongly recommend virtualenvwrapper for everything python related, it removes many of the pip issues) Maybe we could improve the README and add virtualenvs by default, or at least make them very evident. 
Thanks for your feedback!

**Comment by skaller** [comment]
No, I noted the reference to virtualenvs but didn't use it because its yet another layer of stuff I don't understand. I'm reading an article on it now. Part of the problem, as I mentioned in rants above, is that integration of *my* system with conan would have to be fully automated in my systems build system, and that has to work on all platforms with the *same* code because it does now.

So even if I can get virtualenv to work for me, that's not the same as integrating conan into my system. Just to elaborate on that further: there are two quite distinct interactions here.

The first interaction is building and configuring my system. That is currently done by a Python program called `fbuild` which runs under Python3.4 or better, and does not require anything other than the standard Python3 build to work: there are no dependencies which are not built in, and it sets its own package paths internally so imports work.

Currently `fbuild` is *only* used to bootstrap my system. After it has built the bootstrap, my system rebuilds itself. Except for one small program, the second stage of the build does not require Python at all (and that program is only needed because the Felix version of it can't be built until after it has already run :)

So the next interaction is completely different. Felix is a programming language, and it generates and embeds C++. The run time system is written in C++. There are about 20 separate C++ libraries, which the system compiles and builds itself. However since Felix is specifically designed to do to C++ what C++ did to C, namely, act as an upgrade, or to do what Scala does for Java, again to act as a superior upgraded system, it must also do the same thing: retain the utility of existing code from the base language. 

In particular, for Felix, we have to retain the utility of existing C and C++ libraries. To do this, the programmer can write lightweight wrappers for the C/C++ code in Felix, but they also have to be able to find the header files and link against the legacy code. And remember, to develop a portable program this has to work *the same way* on Linux, OSX, and Windows, as well as iPhone and Android if possible :)

This is where *conan* really starts to look interesting. There are some really serious problems with C++, especially now on Unix platforms. These include building for 32 bit occasionally, coping with the disaster of an ABI change in the string class, and then coping with the even worse disaster of unix programmers trying to catch up with windows in terms of shared library visibility control. This means you need to be able to cope with multiple configuration variants. Now throw in the horrible difference between PIC and non-PIC code on x86_64!

I'm quite sure the conan team understands these issues!  Probably better than me. But the point is that to support dealing with this, not for me, but for *my* systems clients, has to not be a Python issue. I'm OK with requiring Python, but needing to install Python add ons is a bit of a problem. I'd probably have to package those addons directly inside my own repository and ensure that conan works "as is" in my repository without any further installation.

That is not the model a Python developer might want to use, but my clients aren't always even C++ programmers. They're always programmers, but they'll never adopt my system if they can't build and install it easily. For this reason, for example, my system uses Google's RE2 regexp package but they do not have to install it. Felix has a copy of the source code of some version or other, modified to link correctly on all OS (which the upstream source does not), and Felix builds the RE2 library itself.

So I'm wary of needing virtualenv or yet another wrapper. I'd rather see the dependencies inside conan, so conan knows where they are, and can set the paths required internally under program control. So that basically after cloning the repo, it just works.

Anyhow for the moment I *will* try to use virtualenv if that's the recommendation, but I'm not sure how at the moment. So I get this:

```
    [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-53071.pth'
```

Now the diagnostics are good here, I didn't use sudo. The thing is, I don't want to.
I don't want to mess with the system Python on my Mac unless I know exactly what it is doing and even then I'd be worried. The right place to put this stuff is in $HOME/Library because that doesn't require sudo. Of course stuff there, at the moment, will not actually work unless I enable it somehow. If this were Linux, I'd use sudo apt-get, because Debian packages are a bit more trustworthy than other stuff. The problem is, a lot of stuff on Apple actually depends on Python. Its a core part of the OS.

**Comment by skaller** [comment]
Just FYI:

https://stackoverflow.com/questions/33658888/installing-virtualenv-virtualenvwrapper-with-pip-on-osx-10-11-1

Seems I'm not the only one with problems. I get the same type of error with pip.
Without sudo it installs some stuff in $HOME/Library ... and tries and fails in the system /Library.
With sudo, it installs in the system /Library and barfs trying to install in $HOME/Library saying I'm not the owner. So some stuff is in some places and other stuff in other places.
If I try to run it is can't find psutils.

Fixing it so it works "for me" is not good enough, since I'd be deploying my system, and it would have to work "out of the box" for my clients as well.

Sigh. The only real solution is to physically include all dependencies inside conan so that a simple directory copy (git clone for example) is enough to make it work (using a suitable filename).

**Comment by memsharded** [comment]
Yes, I totally get the point of your users pain, as every layer of tools is an issue.
I think in your case the way to go is to prepare installers with everything for the major OSs, it is not very difficult.

The conan repo already has in its root the "pyinstaller.py" code that is able to generate a single executable that contains all the conan code and the python interpreter itself. Building installers (we use InnoSetup, for example, for Windows) and automating releases with them might be worth for Felix use case.

**Comment by skaller** [comment]
Interesting, didn't know you had these installer builders. I was going to suggest physically including dependencies instead of expecting people to use tools like "pip" which somehow don't work properly. You'd lose reusability, but the client gains usability. Nasty choice.

I think fundamentally the historical Python is to blame. Using "site-packages" was a very serious blunder. Similarly, *.pyc files next to *.py files, a serious design fault. On Linux, Python uses the wrong linkage model.  Throw in dynamic typing and version incompatibilities... Arggh.

I had a look at the conan package structure and how variations are handled "in principle"  generically which looks good, though I'm not sure how this pans out in reality. I think my system could become a conan package fairly easily, though I'm not sure what advantage that would give.

I have more interest in a package manager which I can use for packages for my system which typically consists of installing C++ libraries plus some bindings for them. Even the core system uses a couple of foreign libraries, Google RE2 for one, and Judy for another. I physically include the (now out of date) sources for these and compile them because that's the only way I know to ensure they work and they're easy to get.

I am curious how you hand the ABI change for C++ when COW string and list was disallowed by the committee. I had severe problems with that because the apt packages on Ubuntu, including backports, for the Ubuntu Travis is currently running are wrongly packaged, so Travis produced binaries not only don't work on more up to date Ubuntus, but there's no work around short of building gcc to avoid the wrong packaging .. which isn't really viable on Travis. Add to this the incompatibility between clang and gcc C++ libraries and installing C++ binaries for people that want to use *both* looks hard. 

My system is designed to cope with these variations, though not perfectly. It needs to account for this kind of thing even more than most, because it is a cross-cross-compiler. The way this works is that there is, within an install, a set of subdirectories, one for each "target", for example, a clang and gcc build can coexist on Linux: the sources are shared, but all the platform dependencies are split out, and each "configuration" is a completely separate subdirectory. Similarly on OSX you can have an iPhone emulator and real iPhone target subdirectory as well as your host clang based one.

So if using conan to install C++ .. one wouldn't just be installing one library binary. It would be multiple installs, and the stuff has to go where my systems says, or at least in separate places, where location information can be installed in the separate targets.

Its really hard to me to tell at the moment exactly what conan can do, and how much of that depends on what the packager using it choses. Any help appreciated trying to figure that out would be appreciated. I am in fact close to thinking the only way to actually install C++ based code is to install sources, not binaries. Unfortunately in BOTH cases, the sources are usually in need of editing.

For example I have not seen many C++ sources that handle visibility in shared libraries correctly. Heck, even clang's standard library has a couple of bugs. Not entirely surprising (since the actual model is wrong .. they couldn't have copied Windows, now could they, which actually does it right).
