### ISSUE TITLE
shell autocompletion

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#2052]
it might be worth to provide conan shell autocompletion, e.g. for bash, and potentially other popular shells (like zsh, powershell, etc).

**Comment by primercuervo** [comment]
👍 for this. Would be very helpful! Is there any update on this?

**Comment by SSE4** [comment]
@primercuervo AFAIK there is no update.
I am not an expert in bash, and have no experience in writing such completion modules for bash or zsh, so probably I am unable to provide any implementation myself. but as usually, pull requests are welcomed.
I think implementation should be split into two parts - some core part in conan itself, which is shell-agnostic, but can provide auto-completions (e.g. by performing local package search to complete package name). and second part would be tiny shell wrapper(s). this way the same implementation will work for any shell.

**Comment by uilianries** [comment]
@SSE4 some time ago I requested the feature here: https://github.com/conan-io/conan/issues/4507

**Comment by memsharded** [comment]
Closing this as not planned. 

Even the interest (I would be the first one loving having auto-complete for Conan), the necessary effort and later maintenance, but specially the added fragility and potential new points of failure never compensated the value, so this never got enough priority for the core maintainers team.
