### ISSUE TITLE
Psutil issues, and overall PID approach to locking

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2066]
``psutil`` has some issues, it fails to install in some systems, or require extra configuration to build the extension from sources.

Also, I have noticed a possible source of error in the design: in POSIX, PIDs wont be reused until overflow the limit, but in Windows PIDs are reused when a process dies.

Also I have found this in psutil code, very disturbing, it will bite us (yes there are users using XP and 2003 server):

```python
        msg = "this Windows version is too old (< Windows Vista); "
        msg += "psutil 3.4.2 is the latest version which supports Windows "
        msg += "2000, XP and 2003 server"
        raise RuntimeError(msg)
````

I have been thinking of other ways to improve this, mainly other forms of IPC and Synchronization, but so far, nothing evident.

cc/ @lasote @SSE4

**Comment by memsharded** [comment]
I am re-thinking why we went with this approach in the first place: when some conan process died unexpectedly, it seems it left the count in the lock files >0 (or -1 if it was the writer), then blocking forever.

However, with the defined contexts, even Ctrl+C exceptions should be captured by the ``__exit__`` method, then cleaning the corresponding count as necessary. Where the inconsistency is coming from?

**Comment by SSE4** [comment]
Ctrl-Break on Windows was causing an issue until I added handler for it. it's easy reproduced if comment out handler.
for psutil, probably we have two approaches:
- implement code ourselves (or borrow from psutil)
- revert to previous approach until we re-visit it
as problem we were trying to solve is less painful than solution provided, probably revert is reasonable way.

**Comment by lasote** [comment]
Yes. We definitely need to revert and not use psutil. If the locks can be cleared capturing the exit it's enough for the 0.29.1 minor.

**Comment by memsharded** [comment]
I have checked the source code of psutil, and how to capture process IDs from the system, or know if a PID exists. Not difficult for posix, but a nightmare in Windows, as usual, requiring native extensions, which are another nightmare to maintain.

Lets remove psutil and return to counter approach, with two improvements:
- Now messages tell users about the lock, and how to remove it
- New signal handler for win
