### ISSUE TITLE
Conan no longer detects packaged Findxxxx.cmake module

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#2067]
Hi guys,

After release 0.29, I think that conan does not detect the packaged `Findxxxx.cmake` module. Let's take this package for example:

https://github.com/dimi309/conan-libpng

I have [modified](https://github.com/dimi309/conan-libpng/commit/7e83b3250901433b01f9892efe924cb749ec61e3) it so that test_package uses the FindPNG.cmake module, rather than CONAN_LIBS to link to the png library. I get this error when running `conan create`:

CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find PNG (missing: PNG_LIBRARY) (found version "1.6.34")
Call Stack (most recent call first):
C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
**C:/Program Files/CMake/share/cmake-3.9/Modules/FindPNG.cmake:144** (find_package_handle_standard_args)
CMakeLists.txt:12 (find_package)

It seems that `find(PNG REQUIRED)` in the test's cmakefile uses the FindPNG module installed with the cmake distributable and not the one included in the conan package. The same happens whether I add `FindPNG.cmake` to the `exports` or the `exports_sources` variable in the conanfile.

**Comment by lasote** [comment]
I've opened a PR in your repo: https://github.com/dimi309/conan-libpng/pull/1

You need to package the findXXX.cmake file, then use the ${XXX_LIBRARY}, and, of course it's not transitive so you need to do the same for zlib. That's why we recommend use Conan, because conan already knows everything about the deps, no need to search or guess or know the transitivity.

**Comment by dimi309** [comment]
Sorry, my mistake ☹️  I've forked this package's source and I didn't notice that it was not copying the file.

I always prefer to use CONAN_LIBS, but sometimes Findxxxx.cmake is needed when packaging an existing library that has a CMakeLists file that contains find statements referencing libraries in other packages (as you probably know better than me 😄 ).

**Comment by lasote** [comment]
NP, happy to help!
