### ISSUE TITLE
how to find out what options a package is compiled for?

### ISSUE THREAD

**Issue by constructs** [conan-io/conan#2070]
Hi,
I am trying to build a custom package for internal use. 
The package has text based options, defaulting to "ANY", in the options section.
Now, I have already compiled a set of packages to work with.

The problem I am facing is I don't know what values of the options the packages are already compiled and I cannot figure out the way of doing it.
Can you please shed some light?

**Comment by memsharded** [comment]
You mean, like:

```bash
$ conan search Pkg/version@user/channel
```
That should output all the compiled binaries. You could use ``--table=yourfile.html`` for an html table.
You can also query for options values:

```bash
$ conan search Pkg/version@user/channel -q="youroption=Yourvalue"
```

Is this what you are looking for?

**Comment by constructs** [comment]
yes, the command
conan search Pkg/version@user/channel -q="youroption=Yourvalue"
gives me the list of options. Thanks.
