### ISSUE TITLE
Use CONAN_PKG without a specific dependecy does not work anymore since 0.29

### ISSUE THREAD

**Issue by JohnboyJovi** [conan-io/conan#2076]
Hello,

For mock testing I need to be able to take one of my conan packages and link against it but not one of its dependend libraries in Visual Studio.
The package here being ``gl`` which I want to depend on without adding a dependency to ``glew`` which is inside of it.

So far we did that as:
```
add_library(gl_without_glew INTERFACE IMPORTED)
get_target_property(gl_link_libraries CONAN_PKG ::gl INTERFACE_LINK_LIBRARIES)
list(REMOVE_ITEM gl_link_libraries CONAN_PKG ::glew)
set_property(TARGET gl_without_glew PROPERTY INTERFACE_LINK_LIBRARIES ${gl_link_libraries})
...
```

Currently this does not work anymore, since the gl_link_biraries are now resolved to:
``$<$<CONFIG:Release>:CONAN_LIB::gl_glrelease;>;$<$<CONFIG:RelWithDebInfo>:CONAN_LIB::gl_glrelease;>;$<$<CONFIG:MinSizeRel>:CONAN_LIB::gl_glrelease;>;$<$<CONFIG:Debug>:CONAN_LIB::gl_gldebug;>;CONAN_PKG::glew`` from which the glew is removed. However, the glew dependency is still also hidden within the ``CONAN_LIB`` thingy

At version 0.28 the above resolved to:
``$<$<CONFIG:Release>:C:/Users/jw210150/.conan/data/gl/1.0.0/RWTH-VR/thirdparty/package/d14e4c5c45ecf77bc3e21f3f778081080a637c29/lib/gl.lib;>;$<$<CONFIG:RelWithDebInfo>:C:/Users/jw210150/.conan/data/gl/1.0.0/RWTH-VR/thirdparty/package/d14e4c5c45ecf77bc3e21f3f778081080a637c29/lib/gl.lib;>;$<$<CONFIG:MinSizeRel>:C:/Users/jw210150/.conan/data/gl/1.0.0/RWTH-VR/thirdparty/package/d14e4c5c45ecf77bc3e21f3f778081080a637c29/lib/gl.lib;>;$<$<CONFIG:Debug>:C:/Users/jw210150/.conan/data/gl/1.0.0/RWTH-VR/thirdparty/package/cb2ad63ea6c3a4f3a2b914e329abe3103734356d/lib/gl.lib;>;CONAN_PKG::glew`` so glew could sucessfully be removed.

Do you have any ideas how I can overcome this, the problem seems to come from using now ``conan_package_library_targets`` in conanbuildinfo_multi.cmake instead of before ``conan_find_libraries_abs_path``

**Comment by memsharded** [comment]
This change was introduced because it happens that CMake doesn't compute the correct link order unless you explicitely link the libraries too.

Could you please clarify this?

> The package here being gl which I want to depend on without adding a dependency to glew which is inside of it.

Is ``glew`` a library inside the ``gl`` package, or is it a transitive dependency? Because in the code you are saying ``CONAN_PKG::glew`` and that seems to be a package.

Have you tried to apply the removal to the package libraries? Something like:

```cmake

get_target_property(_link_libraries CONAN_LIB::gl_release INTERFACE_LINK_LIBRARIES)
list(REMOVE_ITEM _link_libraries CONAN_PKG::glew)
```

Also, out of curiosity, why are you trying to not link with this library? What is the use case? Can't you just use a conditional requirement in the "gl" package to not depend on glew?

Thanks for your feedback!

**Comment by JohnboyJovi** [comment]
Yes, ``gl`` is a conan package (a c++11 OpenGL wrapper) which depends on the conan package ``glew``
In the tests we want to mock glew in some of the tests (but not necessarily all). This is why I want to create this extra target, which is exactly the same as CONAN_PKG::gl except for the glew dependency. Is that clearer? Sorry, this might sound a bit confusing.

``CONAN_LIB::gl_release`` does not exist, however ``CONAN_LIB::gl_glrelease`` does. But its only INTERFACE_LINK_LIBRARIES is CONAN_PKG::glew. So when I use this to create my new target, it actually does not link against ``gl`` anymore, so that does not work. 

Just to make it clearer the complete code I used for this target before is:

```cmake
#add a gl target without glew dependency for mock testing
add_library(gl_without_glew INTERFACE IMPORTED)
get_target_property(gl_link_libraries CONAN_PKG::gl INTERFACE_LINK_LIBRARIES)
list(REMOVE_ITEM gl_link_libraries CONAN_PKG::glew)
set_property(TARGET gl_without_glew PROPERTY INTERFACE_LINK_LIBRARIES ${gl_link_libraries})
get_target_property(gl_include_dir CONAN_PKG::gl  INTERFACE_INCLUDE_DIRECTORIES)
set_property(TARGET gl_without_glew PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${gl_include_dir})
get_target_property(gl_compile_definitions CONAN_PKG::gl  INTERFACE_COMPILE_DEFINITIONS)
set_property(TARGET gl_without_glew PROPERTY INTERFACE_COMPILE_DEFINITIONS ${gl_compile_definitions})
get_target_property(gl_compile_options CONAN_PKG::gl  INTERFACE_COMPILE_OPTIONS)
set_property(TARGET gl_without_glew PROPERTY INTERFACE_COMPILE_OPTIONS ${gl_compile_options})
```

``gl_without_glew`` is then used within target_link_libraries for the mocked tests.

**Comment by memsharded** [comment]
The key is that the dependency graph now is:
```
CONAN_PKG::gl => CONAN_PKG::glew
CONAN_PKG::gl => CONAN_LIB::gl_glrelease
CONAN_LIB::gl_glrelease => CONAN_PKG::glew
```
I think it should be enough to break the last link, doing the same you did for the first one:

```cmake
add_library(gl_without_glew INTERFACE IMPORTED)

get_target_property(gl_link_libraries CONAN_PKG::gl INTERFACE_LINK_LIBRARIES)
list(REMOVE_ITEM gl_link_libraries CONAN_PKG::glew)

get_target_property(lib_link_libraries CONAN_LIB::gl_glrelease INTERFACE_LINK_LIBRARIES)
list(REMOVE_ITEM lib_link_libraries CONAN_PKG::glew)

set_property(TARGET gl_without_glew PROPERTY INTERFACE_LINK_LIBRARIES ${gl_link_libraries}
                                                                      ${lib_link_libraries})
...
```

Did you try this? Is there something I am missing? Thanks!

**Comment by JohnboyJovi** [comment]
Thanks, that is exactly the dependency graph that I encounter. The Problem with your above code is that I keep the dependency ``CONAN_PKG::gl => CONAN_LIB::gl_glrelease`` Thus because I do not change ``CONAN_LIB::gl_glrelease`` I still get the ``CONAN_LIB::gl_glrelease => CONAN_PKG::glew`` dependency :-/

**Comment by memsharded** [comment]
Maybe for this use case it is simple to use ``${CONAN_LIBS_GL}`` instead of extracting them from the targets? Just use the cmake conan variables directly, should be straightforward.

**Comment by JohnboyJovi** [comment]
Hello, thank you, yes using a combination of both worked for me, so here the solution for anyone who tries to do something else in the future:

```cmake
add_library(gl_without_glew UNKNOWN IMPORTED)
if(TARGET CONAN_LIB::gl_glrelease)
  get_target_property(gl_link_libraries CONAN_LIB::gl_glrelease INTERFACE_LINK_LIBRARIES)
  list(REMOVE_ITEM gl_link_libraries CONAN_PKG::glew)
  set_property(TARGET gl_without_glew PROPERTY INTERFACE_LINK_LIBRARIES ${gl_link_libraries})

  get_target_property(gl_imported_location CONAN_LIB::gl_glrelease LOCATION)
  set_property(TARGET gl_without_glew PROPERTY IMPORTED_LOCATION ${gl_imported_location})

  get_target_property(gl_include_dir CONAN_PKG::gl INTERFACE_INCLUDE_DIRECTORIES)
  set_property(TARGET gl_without_glew PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${gl_include_dir})

  get_target_property(gl_compile_definitions CONAN_PKG::gl INTERFACE_COMPILE_DEFINITIONS)
  set_property(TARGET gl_without_glew PROPERTY INTERFACE_COMPILE_DEFINITIONS ${gl_compile_definitions})

  get_target_property(gl_compile_options CONAN_PKG::gl INTERFACE_COMPILE_OPTIONS)
  set_property(TARGET gl_without_glew PROPERTY INTERFACE_COMPILE_OPTIONS ${gl_compile_options})
else()
  message("You are using a conan version older than 0.29, please update e.g. by \"pip install conan --upgrade\"")
endif()
```

**Comment by memsharded** [comment]
Great, thanks for the feedback!
