### ISSUE TITLE
Conan launcher to use the sources directly

### ISSUE THREAD

**Issue by sigmoidal** [conan-io/conan#2078]
The recommended launcher (shown below) which is currently in README.md is a bit problematic, in that it appends the path of the sources to the PATH, which in turn means that an existing installation of conan will be used instead of the sources the launcher is points to.

```
#!/usr/bin/env python
import sys
sys.path.append('/home/user/conan') # EDIT!!

from conans.conan import main
main(sys.argv[1:])
```

It would be better to assume that a user utilizing the sources directly, is more likely to prefer to override any existing installations of conan. I would propose this is changed in the documentation, to suggest that the launcher "prepends" the PATH of the user, instead of appending to it:

```
#!/usr/bin/env python
import sys

conan_sources_dir = '/home/user/conan'  # EDIT!!

sys.path.insert(1,conan_sources_dir)
from conans.conan import main
main(sys.argv[1:])
```

thanks.

**Comment by lasote** [comment]
I agree I will add a comment line with both approaches.
