### ISSUE TITLE
Spawn cmake server for during package development

### ISSUE THREAD

**Issue by Xonar** [conan-io/conan#2079]
Currently conan currently allows very easy packaging of applications, but lacks proper integration of IDE's. 

I propose that the ability to start a CMake server (or alternative build server instance) instance is added.

Any IDE with cmake server support would only need to call the conan commands to start the server and passing required options/profile information to conan. Even if the IDE doesn't support conan the cmake server could be started and the IDE just connect to it.

With something like:
`conan install -o Options... -pr Profile --dev_server_mode SrcDir`

Extending on this idea the conan could also stay running in "dev server mode" and call

`conan install -o Options... -pr Profile --build=outdated ..`

when a dependant package's gets updated. 

This would ease the flow when having a Development workflow where you are simultaneously developing package A and B and package B depends on A. There was a issue asking about this kind of workflow, but I can't find it to reference it.

NOTE:

Just running `conan install` then starting the CMake server oneself works, but some IDE's create their own folder not specified by the user and then it's difficult to call `conan install` from that folder. Also often package options often sets CMake flags which should then be specified manually.

**Comment by memsharded** [comment]
Thanks for your suggestion. The thing is that I don't see this into a package manager, nor I see how would it integrate with IDEs, though it is true that I don't know very well the cmake server mode. Up to my knowledge, IDEs using cmake would use their own cmake server, so it is not clear how to interact with that. 

> Extending on this idea the conan could also stay running in "dev server mode" 

Do you mean that conan should also have a server mode? Or that cmake server mode can execute that kind of commands?

I think the way to go is to have real integration with IDEs, via addons/plugins.

**Comment by Xonar** [comment]
I also think real addons/plugins is the way to go I was just thinking (and not clearly articulating) a way for that plugin/addon to be done with little effort and interacting more with the CMakeServer than with Conan.

The issue I was referring too previously: https://github.com/conan-io/conan/issues/1377. I don't know the most up to date news on the "conan-projects" implementation, but I think that with what I am proposing that workflow can be obtained without too much work.

I'll explain in more detail what my problem is and how my proposed workflow will look.

Suppose I have a conanfile.py project which uses CMake as a (meta)build system. Depending on the options specified my dependencies change and I pass some of the settings as flags to the cmake generator.

Super simple example: 
```
options = { "build_tests": [True, False] }

def build(self):
    cmake = CMake(self)
    if self.options.build_tests:
        cmake.definitions["BUILD_TESTS"] = "ON"
    cmake.configure(source_dir=self.source_folder)
    cmake.build() 

def build_requirements(self):
    if self.options.build_tests:
        self.build_requires("just/some@testing/framework")
```

If I run conan install with the specfied options then I will have to manually specify them in both the `conan install` and `cmake` step. This is not the end of the world since it is possible to run `conan install` then `conan build` and use the generated project and work from there.

It would be nice if an additional step or function could be specified with which one could just:
```
def build_server(self):
    if self.options.build_tests:
        cmake.definitions["BUILD_TESTS"] = "ON"
    cmake.start_server()
```
I realize that this might not intuitively fit into what the package manager should manage, but if you are developing a package then you want your package to be much more "live".

Onto my extension of the original idea:
Cmake is not aware to changes made to Conan packages. Conan works at a higher level than CMake so I don't think CMake should be made aware of how Conan works. It unnecessarily couples the two tools. This is what https://github.com/conan-io/cmake-conan does.

If while the conan spawned CMake server is active a change happens to a dependent package the package should be rebuilt as required and the conanbuildinfo.cmake and conaninfo.txt updated. The CMake server can then reconfigure itself with the new information and stay "live". If somehow an option change could be communicated to conan it could also update conanbuildinfo.cmake and conaninfo.txt.

For IDE integration all that would be required is the IDE setting up the conan build_server with the correct options then using existing CMake integrations from there. Essentially using conan to start the server with all options configured instead of starting it themselves. A change in a dependent package will then be available in the other package and very little effort required to create a plugin for an IDE with cmake-server support.

**Comment by memsharded** [comment]
CMake server no longer a thing, https://cmake.org/cmake/help/latest/manual/cmake-server.7.html, it was deprecated. Closing.
