### ISSUE TITLE
Handling nightly packages

### ISSUE THREAD

**Issue by hamparawa** [conan-io/conan#2083]
Hi,
I am maintaining two channels, stable and testing where `stable` channel contains the releases of a package, and `testing` channel contains the development head (nightly package) of a library.
For an example, consider following packages,

`A/0.1@demo/stable`
`A/0.2@demo/testing`

Where `A/0.2@demo/testing` is the nightly package of the 0.2 version which has not released a stable version yet. When the 0.2 is stable, I move the recipe to stable channel and start working with 0.3.

In the nightly recipe, I am checking out the HEAD of the development branch in `source()` method, and in stable recipe, I am checking out a specific GIT revision.

Most of the time, downstream users use the stable packags, but in some cases they are required to work with nightly packages.

I am having an issue with conan caching the sources in the nightly packages as the content of the source changes each day. It seems like there is no option to force re-download the sources when `conan install` is invoked. So the users are forced to manually delete the whole package before calling `conan install` again.

Is there another way this could be achieved in current versions of Conan? 
Also if possible, I would love to have something like `conan install --build A:redownload ..` which does specify the package and its build policy just like specifying options to upstream packages, and `redownload` option will invalidate all sources cached.

**Comment by memsharded** [comment]
Hello!

```bash
$ conan install --update
```
This will force re-download of packages (binary packages), if they have changed. But it seems that your are not using binaries, but making your users of the packages to always re-build from sources. Is there a reason for this? One of the strong points of conan is that it can manage binaries very good, thus avoiding that.

In case you want to always build from source, and force the re-download of the source every time, there are a couple of options:
1. You can just do a ``conan remove PkgName* -f`` to completely remove the package, before the install
2. You could use the ``build_policy="always"`` policy in the recipe you want to force a rebuild (including re-downloading the sources) everytime.

Please tell me if this helps. Thanks1

**Comment by hamparawa** [comment]
Hi, thanks for reply.
> But it seems that your are not using binaries, but making your users of the packages to always re-build from sources. Is there a reason for this?

I am packaging binaries for some targets but there are several OS/glibc/Compiler combinations that aren't covered by the pre-built binary packages. 

> You can just do a conan remove PkgName* -f to completely remove the package, before the install

This is the method I am currently applying.

> You could use the build_policy="always" policy in the recipe you want to force a rebuild (including re-downloading the sources) everytime.

This I haven't tried and definitely will look into. I think in my case this would be the best option. Thanks again!

**Comment by memsharded** [comment]
> I am packaging binaries for some targets but there are several OS/glibc/Compiler combinations that aren't covered by the pre-built binary packages.

For this I would recommend to host your own packages. You can download + upload to your own repo the binaries you want from other repos, then add the binaries you create. Please ask if you want further detail about this. 

And please, keep me updated about how the buid_policy works. Thanks!

**Comment by hamparawa** [comment]
Hi,
The `build_policy='always'` setting is working as expected for my case. However, now the only concern is that conan does not let me upload the packages. The setting is fully understandable now that the recipe has stated the packages are always building. 
However, I would love to see an option which lies in between these two ends, where the source is re-downloaded whenever a built package is not available in the server. Maybe in a future release?

Cheers!

**Comment by memsharded** [comment]
Well, I have another suggestion, which is very simple to implement. Why don't you put the code for the download inside the ``build()`` method instead of the ``source()`` method. That is exactly the behavior you are looking for.

**Comment by wpalfi** [comment]
You can use 
```
conan remove --src bla
conan install bla
```
This is less intrusive than moving the download to `build()`. We use it on our build server to force a clean download, while we are still able to build locally without redownloading everytime.
