### ISSUE TITLE
Toolchain package is built twice

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2085]
Hi,

I have a profile to cross-build for Android, with a build requirement on `android-toolchain/r16@theo/stable`.

I have an issue when I try to create the `android-toolchain` package.
The package is build twice when I run the following command:

```shell
$ cd android-toolchain
$ conan create theo/stable -pr clang50-android-armv7-24
```

To workaround that, I have to write every setting to the command line, which is a bit cumbersome.

**Comment by memsharded** [comment]
Can you please try running from develop branch?

We have changed something important in the ``create`` command, which might solve your issue. Thanks!

**Comment by theodelrieu** [comment]
I'll try asap!

**Comment by theodelrieu** [comment]
I've installed the latest develop version `Conan version 0.30-dev` and the issue is still here.

I'll admit this is kind of an edge-case :)

**Comment by memsharded** [comment]
Can you please share with me your profile? Also I guess your system is Linux, but please tell, and I will have a look.

**Comment by theodelrieu** [comment]
Here is my profile, I'm on macOS:

```ini
[build_requires]
android-toolchain/r16@theo/stable

[settings]
os=Android
arch=armv7
os.api_level=24
compiler=clang
compiler.version=5.0
compiler.libcxx=libc++
build_type=Release

[options]
[scopes]
[env]
```

I'm sure you can replace the android toolchain with `android-toolchain/r13b@lasote/testing` and it should still reproduce the issue!

**Comment by memsharded** [comment]
Oh! Now I see the issue, it is a circular dependency, you are using as build-require the same package you are creating. Now I get when you said that yours was an edge-case. I think this is not necessary, why are you using such build_requires in this case? Can't you just remove the [build_requires]? Thanks!

**Comment by theodelrieu** [comment]
The thing is I use the same command line (same profile) for every package.

I find it easier than adding a `build_requirements` method in every recipe.

One funny thing is that my default profile contains a different `build_requires`: a `darwin-toolchain` that helps building on every darwin system.

And there are sanity checks on the `self.settings.os`, which fail when I try to build for android (by spelling every setting on the command line)

If you want I will post a zip file to help reproduce the issue tomorrow

**Comment by memsharded** [comment]
> I find it easier than adding a build_requirements method in every recipe.

Yes, agree, I was thinking of using a different profile, for the specific case of building the toolchain

I think I can reproduce it, I am going to check if possible to remove the circular dependency. Because actually you don't need the toolchain to build again the toolchain, do you?

**Comment by theodelrieu** [comment]
Here is the zip archive: [circular_build_requirements.zip](https://github.com/conan-io/conan/files/1509365/circular_build_requirements.zip)

My default profile is `appleclang90`, running these commands should fail:

```shell
$ cd android-toolchain
$ conan create theo/stable -s os=Android -s compiler=clang -s compiler.version=5.0 -s compiler.libcxx=libc++ -s arch=armv7 -s os.api_level=24
```

And using the `clang50-android-armv7-24` will trigger the build twice.

**Comment by theodelrieu** [comment]
No indeed I do not need it to build itself :D

**Comment by memsharded** [comment]
I have submitted a possible fix in: https://github.com/conan-io/conan/pull/2088

Do you think that would also help with the comand that fails with your default profile ``appleclang90``? Or is that another issue? Thanks!

**Comment by theodelrieu** [comment]
That will definitely help! I have the other issue because enumerating every option still includes my default profile in the mix, and thus the build_requirement on `darwin-toolchain`.

I'm testing your fix right away

**Comment by memsharded** [comment]
There was a failure, in fact the PR didnt pass the tests, my bad! 

I have fixed it, pushed, now it should be better (tests seems green at least), please try again when possible, thanks!

**Comment by theodelrieu** [comment]
It works!
