### ISSUE TITLE
What is it 'æ' in build_environment_helpers.py ?

### ISSUE THREAD

**Issue by vpashka** [conan-io/conan#2099]
Hello.
At the end of the file conans/test/functional/build_environment_helpers.py
there is a symbol 'æ'. What is it?  A typo?

Version: 0.29.1

**Comment by memsharded** [comment]
Indeed a typo, that was breaking it. Didn't notice because the file name doesn't contain "test", and thus is not being ran! Good catch, thanks very much, fixing it right now.

**Comment by vpashka** [comment]
Ok. Thank you.
