### ISSUE TITLE
error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by smspillaz** [conan-io/conan#210]
When attempting to link to dynamic libraries in another project that I've imported building on travis-ci, I'm getting this error.

I'm not sure why this is happening. My only theory is that potentially the wrong bitness version is being downloaded from conan.io.

The build where this happens can be found [here](https://travis-ci.org/polysquare/clang-conan/jobs/117705136)

**Comment by lasote** [comment]
Could be an arch issue, try to build only x86_64 packages and see if it works.

**Comment by smspillaz** [comment]
@lasote Yeah, so building x86_64 packages works but not x86 packages.

I think what is happening is that the x86_64 binaries are being downloaded for the x86 package build. This is probably because x86_64 is the default architecture in ~/.conan.conf during the builds.

Unfortunately, I don't really have a good way of debugging this at the moment, since I don't know how conan determines the URL to download packages with.

**Comment by Xaltotun** [comment]
@smspillaz This is due to LLVM's build system.  TableGen and clang-tblgen are built for the host architecture since they are used by the build.  if you look at the link step of clang-tblgen it is building with -m32, but if you look above where it compiled the sources it is not passing -m32.

When compiling any of the TableGen projects you should let LLVM determine the architecture to build for,

**Comment by Xaltotun** [comment]
Ok never mind, i was way off track on my off the cuff response.  The real issue is that your llvm package at https://www.conan.io/source/llvm/3.8.0/smspillaz/stable under "Linux/x86/gcc 4.8/Release (3ab24ba28560454a0301dcbf33090353b0828a30)" has all the shared objects built as 64 bit, but it is labeled as a 32 bit package

**Comment by helmesjo** [comment]
Getting similar error when building boost with G++ 6.3.0 (Debian 9.1):

`/root/.conan/data/Boost/1.64.0/conan/stable/package/96621e4382c43cb4ef7a21a95c8bc64f6a0576fd/lib/libboost_thread.so: error adding symbols: File in wrong format`

Install: 
`conan install Boost/1.64.0@conan/stable -s arch=x86 -s build_type=Release`
Generate & build: 
`cmake .. -DCMAKE_BUILD_TYPE=Release`
`cmake --build . --config Release`

Building works, linking fails.

**Comment by lasote** [comment]
Have you set `set (CMAKE_CXX_FLAGS "-m32")` in your CMakelists? You are installing your dependencies for 32 bits, so your `CMake` should do the same. You could include the `conanbuildinfo.cmake` file as usual and use a conan recipe to build your project. With the build helper `CMake()` in a  `build` method and run `conan build` to invoke your project compilation.

**Comment by helmesjo** [comment]
That was probably it... I've been relying on cmake defaulting to 32-bit (as on Windows/VS), but I'm starting to believe it makes no promises at all regarding this and it's all up to whatever default generator is selected.

However, I now get other linking errors related to (I believe) `-D_GLIBCXX_USE_CXX11_ABI=0` that you pass to boost build (which currently isn't optional):

```
In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
main.cpp:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE6xparseERNS_3anyERKSt6vectorIS7_SaIS7_EE[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE6xparseERNS_3anyERKSt6vectorIS7_SaIS7_EE]+0x23): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
../lib/libcucumber-cpp.a(main.cpp.o): In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name[abi:cxx11]() const':
main.cpp:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameB5cxx11Ev[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameB5cxx11Ev]+0x27): undefined reference to `boost::program_options::arg[abi:cxx11]'
main.cpp:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameB5cxx11Ev[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameB5cxx11Ev]+0x2e): undefined reference to `boost::program_options::arg[abi:cxx11]'
../lib/libcucumber-cpp.a(main.cpp.o): In function `boost::program_options::typed_value<int, char>::name[abi:cxx11]() const':
main.cpp:(.text._ZNK5boost15program_options11typed_valueIicE4nameB5cxx11Ev[_ZNK5boost15program_options11typed_valueIicE4nameB5cxx11Ev]+0x27): undefined reference to `boost::program_options::arg[abi:cxx11]'
```
_(just a snippet)_

**Comment by memsharded** [comment]
> However, I now get other linking errors related to (I believe) -D_GLIBCXX_USE_CXX11_ABI=0 that you pass to boost build (which currently isn't optional).

The GLIBCXX_USE_CXX11_ABI is controlled by the ``compiler.libcxx`` setting, by default is set to ``libstdc++``, but if you have a modern compiler (in a modern distro, travis-ci, for example doesn't have libstdc++11 even if you upgrade the compiler). If you configure your ``compiler.libcxx=libstdc++11``, then the ``-D_GLIBCXX_USE_CXX11_ABI=0`` will be used.

**Comment by helmesjo** [comment]
I'm not quite following... Did you mean the other way around? 
`D_GLIBCXX_USE_CXX11_ABI=0` == `libstdc++` _I get this_
`D_GLIBCXX_USE_CXX11_ABI=1` == `libstdc++11`
That would explain my case since I'm not specifying anything, thus `conan` defaults to `compiler.libcxx=libstdc++`.

**Comment by memsharded** [comment]
Yes, sorry, it was my mistake in the above comment, because of copy&paste, fixed it.
