### ISSUE TITLE
recipes not updating

### ISSUE THREAD

**Issue by KoHcoJlb** [conan-io/conan#2104]
Is it a bug or a feature that if I update recipe in remote repository it's not updated in local cache when I run conan install.
What is better approach to do this if I don't want to change version because library itself not changed.

**Comment by petermbauer** [comment]
there is conan install --update

**Comment by memsharded** [comment]
It is a feature, it is by design. As @petermbauer points out, a ``conan install --update`` checks updates from remote repository (it is also slower than a normal ``conan install``)

**Comment by KoHcoJlb** [comment]
Thanks for the help.

**Comment by lasote** [comment]
I'm closing the issue but any other question or anything else, please, feel free to write again!
