### ISSUE TITLE
0.26.1 is broken on PyPI

### ISSUE THREAD

**Issue by ikoruk** [conan-io/conan#2107]
When installing conan==0.26.1 through pip, the `requires.txt` specifies `pyOpenSSL>=16.0.0, <18.0.0`

However, pyOpenSSL 17.5 just came out with a breaking change in the minimum version of cryptography which conflicts with that of conan.

Easiest fix would be to update `requires.txt` to specify `pyOpenSSL>=16.0.0, <17.4.0`

**Comment by lasote** [comment]
Yes, that's the reason we released 0.29.2. Let me know if you find any issue with the new version.
Thanks for reporting! PD. I'm closing the issue, feel free to write if anything is going wrong with the new version, I will open it again.

**Comment by ikoruk** [comment]
We still need to run 0.26.1 because we have old packages. Is it possible to issue this fix to 0.26.1 on pip?

**Comment by lasote** [comment]
No, pip doesn't allow to override packages, we could release a revision 0.26.2 if it's really needed for you.
But please, note that we are in Beta, could you please explain to us what are the problems with these old packages? It's very important to upgrade Conan until we reach the 1.0.

**Comment by lasote** [comment]
I've released a 0.26.2 on pip (only changes the requirements from 0.26.1). Please write me an email, would be very useful for us to understand what is your stopper to not upgrade Conan.

**Comment by ikoruk** [comment]
It's actually because we were using outdated API. We just updated and all the recipes work fine. Thanks!

**Comment by memsharded** [comment]
Excellent @ikoruk thanks for the feedback.
Do not hesitate to ask for help for upgrading, it is quite important, at least until we get out of beta (soon :) )
