### ISSUE TITLE
Could CMake generator produce a Toolchain file?

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2119]
Hi,

I've been showing which CMake files Conan ends up generating, and one of them asked if `conanbuildinfo.cmake` could be replaced with a Toolchain file.

The main advantage being that it is no longer required to modify a project's `CMakeLists.txt`, one could instead give `-DCMAKE_TOOLCHAIN_FILE` as a CMake argument.

I haven't dug up very deep with this idea, so this is only early speculation.

What do you think about it?

**Comment by lasote** [comment]
At first sight, could you specify several toolchain files? Because some people doing cross-building and other stuff are already using the `CMAKE_TOOLCHAIN_FILE` to include external toolchains.

**Comment by theodelrieu** [comment]
It seems you can only specify one. Maybe there's a way to conciliate both use-cases.

Could Conan include the already existing `CMAKE_TOOLCHAIN_FILE` to add dependencies etc?

Is there some changes to make to try the non cross-building case? I can test this on some big recipes we have here.

**Comment by lasote** [comment]
I don't know, probably just remove the include and pass the `-DCMAKE_TOOLCHAIN_FILE=conanbuildinfo.txt` works. Try it and report!

**Comment by theodelrieu** [comment]
I'll try that later today, you mean the `conanbuildinfo.cmake` or the `.txt`?

**Comment by lasote** [comment]
Yep, the `.cmake` sorry.

**Comment by theodelrieu** [comment]
Okay, I have the following minimal toolchain file

```cmake
cmake_minimum_required(VERSION 3.0)

set(CMAKE_C_COMPILER /usr/bin/gcc)
set(CMAKE_CXX_COMPILER /usr/bin/g++)
set(CMAKE_C_COMPILER_VERSION 7.2)
set(CMAKE_CXX_COMPILER_VERSION 7.2)

set(CMAKE_FIND_LIBRARY_PREFIXES lib)
set(CMAKE_FIND_LIBRARY_SUFFIXES .a)

set(CMAKE_C_COMPILER_ID GNU)
set(CMAKE_CXX_COMPILER_ID GNU)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)

conan_basic_setup(TARGETS)
```

Unfortunately, it seems this file is being parsed twice, CMake triggers an error in the `conanbuildinfo.cmake`.

>CMake Error at build/conanbuildinfo.cmake:474 (add_library):
  add_library cannot create imported target "CONAN_PKG::mylibrary" because
  another target with the same name already exists.
Call Stack (most recent call first):
  build/conanbuildinfo.cmake:1015 (conan_define_targets)
  toolchain.cmake:19 (conan_basic_setup)
  build/CMakeFiles/3.10.0/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:2 (project)

At first I thought it was a double inclusion problem, but even the brand new `include_guard` feature didn't solve the problem.

If we can figure this out I'm sure we can make it work.

We could generate both `conanbuildinfo.cmake` and `conantoolchainfile.cmake`, it would be then left to users to decide which one they want.

**Comment by theodelrieu** [comment]
The documentation about toolchain files is quite light. I'm not sure where to find more detailed info

**Comment by memsharded** [comment]
> The main advantage being that it is no longer required to modify a project's CMakeLists.txt, one could instead give -DCMAKE_TOOLCHAIN_FILE as a CMake argument.

Trying to understand a bit further the use case. The above case does not completely hold, because even if the file is provided as toolchain, the linkage is still necessary, something like:

```cmake
target_link_libraries(mylib ${CONAN_LIBS})
# or
target_link_libraries(mylib CONAN_PKG::MyPkg)
```
So I am missing how this process would be fully transparent to the consumer CMakeLists.txt. What am I missing?

**Comment by theodelrieu** [comment]
You're right, I've realized it a bit late.

The only use-case I see would be for users using `find_package`, and linking against `OpenSSL::OpenSSL` for example.

I'm not even sure that would work though...

**Comment by memsharded** [comment]
Yes, that might be the only use case, if the existing FindXXX.cmake or a custom FindXXX.cmake inside the package is able to create the same targets with the same name as conan does, then it would be fully transparent. But IMHO, it seems a bit cumbersome, and as I am not a big fan of Find.cmake functionality, I think it is much easier to maintain, debug and extend the normal approach of including the ``conanbuildinfo.cmake``. As the python zen says, "better explicit than implicit".

**Comment by theodelrieu** [comment]
Yup I agree, after some digging it does not seem that interesting anymore.

**Comment by memsharded** [comment]
Ok, good, thanks for all the feedback!
