### ISSUE TITLE
Release builds should be considered compatible with Debug builds

### ISSUE THREAD

**Issue by smspillaz** [conan-io/conan#212]
There are some projects where it is just not feasible to upload a debug build. For instance, the debug symbols for LLVM inflate the project size to over 40GB.

At the moment, if I try to build a package using config=Debug, conan will try and download the Debug binaries and fail. There should be an option to gracefully revert to downloading Release binaries since they are binary compatible.

**Comment by lasote** [comment]
You can force the build_type=Release in the conan_info method:

http://docs.conan.io/en/latest/reference/conanfile.html?highlight=conan_info

This way, no mater the user specify, will use the release package.

**Comment by memsharded** [comment]
To provide more detail, there are 2 different settings, the actual settings that are defined by the consumer and enter de package configuration, and the settings that the package finally declares that matters to its binaries, that can be narrowed from the original settings.  What should be done would look like:

```python

def conan_info(self):
        self.info.settings.build_type = None
```

This will basically produce a conaninfo.txt like this:

```txt

[settings]
...
build_type = None

[full_settings]
...
build_type=Release
```

This means that the project is being build with Release type, it is an input setting, defined in the build. But to produce the package signature, the conan_info() removes such setting, and thus build_type with value None is **not used to compute the sha**, and then, the resulting package is build_type independent and will be retrieved for any consumer value of build_type.

Please tell me if this works for your use case. Thanks!

**Comment by Xaltotun** [comment]
I would not say that they are binary compatible, since it depends on your platform. For instance, windows debug and release are not ABI compatible due to debug iterators in the dinkumware STL implementation.

**Comment by memsharded** [comment]
Sure, Win is not, I have myself experience it, it might link, but then you will have runtime errors. 

If the package creator knows that their implementation is ABI compatible for a certain compiler (or maybe cause they are using some pimpl, or anything that makes it ABI compatible), can always do:

```python 
def conan_info(self):
    if self.settings.compiler == "gcc":  # or self.settings.os != "Windows" or the like
        self.info.settings.build_type = None
```

**Comment by memsharded** [comment]
I think that with the above suggestions, and the functionality implemented in conan 0.16, that allow specify individual settings for different packages (something like):

```bash
$ conan install -s build_type=Debug -s Pkg:build_type=Release
```

with this, this issue can be labeled as fixed and closed, please re-open if necessary. Thanks!

**Comment by dskdas** [comment]
Is it possible to configure this in the consumer conanfile.py (as opposed to passing a settings argument to conan install)?

**Comment by memsharded** [comment]
No, consumer conanfile.py cannot access that. Because it should work the same also if using a ``conanfile.txt`` file. Typically, you don't want to change/define **values** for settings in any conanfile, because by definition they are designed exactly to be defined always by the system (external/orthogonal to the recipes)

**Comment by tjwrona1992** [comment]
The info in this ticket seems to be a bit outdated so I'll add a comment of what worked for me.

In order to make a package created from pre-compiled binaries work for both Release and Debug builds with a single package hash I had to add the following to the "conanfile.py" for the package:

        def configure(self):
            if self.settings.compiler == "Visual Studio":
                self.settings.build_type = None
                self.settings.compiler["Visual Studio"].remove("runtime")

This basically tells the package to ignore the build_type and the "compiler.runtime" settings when compiling using Visual Studio.

**Comment by memsharded** [comment]
Thanks @tjwrona1992 for the tip.

I guess that with ``configure()`` you are later hardcoding the "Release" configuration in the build scripts or in the ``build()`` method.

Another possibility would be to pass the input build_type and runtime parameters to the ``build()``. It is not that they are not applied, they are actually used for the build. Then, later, they could be removed in ``package_id()`` which is the place to define binary compatibility for consumers, something like:

```python
def package_id(self):
     if self.settings.compiler == "Visual Studio":
         self.info.settings.compiler.runtime = "None"
         self.info.settings.build_type = "None"
```

This would allow to build the package with either Debug or Release, and the resulting one could be reused by either Debug or Release too, without needing to match.
