### ISSUE TITLE
Meaning of conanfile_directory

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#2122]
http://docs.conan.io/en/latest/reference/conanfile/attributes.html#conanfile-directory 
says:

> self.conanfile_directory is a read only property that returns the directory in which the conanfile is located.

But it returns the build directory instead (which may be different).

In http://docs.conan.io/en/latest/packaging/getting_started.html you do
`cmake.configure(source_dir=self.conanfile_directory, build_dir="./")`

Why not
`cmake.configure(source_dir=self.build_folder, build_dir="./")`
?

If this is for historical reasons, as mentioned in #1827, please explain it in the documentation and deprecate it.

**Comment by memsharded** [comment]
Yes, I agree it is a bit confusing. I am going to improve it.

**Comment by lasote** [comment]
Actually it should probably be:

`cmake.configure(source_dir=self.source_folder, build_dir="./")` That will be the same as `self.source_folder` when `self.no_copy_source==False`

**Comment by memsharded** [comment]
Exactly. Proposed changes to docs: https://github.com/conan-io/docs/pull/395

**Comment by memsharded** [comment]
Also, from generated test code: https://github.com/conan-io/conan/pull/2124

**Comment by memsharded** [comment]
BTW @wpalfi the docs are also in a github repo, you can also submit issues or PR for improving the docs there. Thanks for reporting this!

**Comment by wpalfi** [comment]
Wow, you are really fast!
