### ISSUE TITLE
Parsing package recipe from other package management systems

### ISSUE THREAD

**Issue by astralien3000** [conan-io/conan#2126]
Hello,

I don't know how this part of conan works, but since you enable the user to have 2 types of `conanfile`, the `.txt` being equivalent to a `.py` version in some point ([as said in this example](http://docs.conan.io/en/latest/mastering/conanfile_py.html)), I was wondering if we could do the same with other formats easily.

For example, to parse [ros `packages.xml`](https://github.com/ros/roscpp_core/blob/kinetic-devel/roscpp_core/package.xml), [`library.json`](http://docs.platformio.org/en/latest/librarymanager/config.html), [npm `package.json`](https://docs.npmjs.com/files/package.json), etc...

Can you tell me if it's possible and which classes I should look into to achieve that ?
I think it could be interesting, especially for the ros package system, don't you ?

**Comment by memsharded** [comment]
The main entry point for loading conanfiles is in ``conans/client/loader.py``, and the ``ConanFileLoader`` class. 

I would need to know more about this use case. For packaging, it is very unlikely that we could achieve compatibility with other package formats. For consuming, it might be possible, but I don't know how you plan to use those other formats, because I don't see them declaring requirements with conan format ``Pkg/version@user/channel``. 

I agree, the most interesting one could be ROS. Can you please elaborate further how do you think that such system could integrate with conan? Thanks!

**Comment by astralien3000** [comment]
Ok, thank you, I will look into this.

I will take the example of ROS2 (not ROS1) because I know better the process.
To sum up the ROS2 [build process (see "Building from source")](https://github.com/ros2/ros2/wiki/Installation) : 
 - Download the [listed repository](https://github.com/ros2/ros2/blob/release-beta3/ros2.repos) in a directory called "workspace". (you can arrange the repositories in several workspaces, for example, [I have 4 workspaces in my workflow](https://github.com/astralien3000/rmw_ndn/tree/6f32dc97926b95d5b24fead0678b962ba44e5c05))
 - Call the build system `ament build`, which will find all packages in the workspace, check dependencies (even with previously buit workspaces), and build.
 - After that, an `install` directory is created with all the compiled packages, and a `setup.bash` file, that you need to run (`.  ./install/setup.sh`) to make the workspaces avaliable to others (if needed), and to run ROS2 applications.

I hope this is understandable, since it's roughly summed-up...

Let's take a [rather simple example (rmw)](https://github.com/ros2/rmw/blob/master/rmw/package.xml).This `package.xml` could be equivalent to : 
```python
from conans import ConanFile

class ROS2Conan(ConanFile):
    name = "rmw"
    version = "0.0.3"
    exports = "*"

    settings = "os", "compiler", "build_type", "arch", "target"

    requires = 
        "ament_cmake_ros/VERSION@USER/CHANNEL", 
        "rcutils/VERSION@USER/CHANNEL", 
        "rosidl_generator_c/VERSION@USER/CHANNEL", 
        ... # test_depends, I don't care

    generators = "?"

    def build(self):
        self.run('ament build ...')

    def package(self):
        self.copy("*", src="install", dst=".")

    def package_info(self):
        # something to export "setup.bash"
```
(VERY roughly)

Now, as you said, there is a problem to determine : 
```python
requires = "PACKAGE/VERSION@USER/CHANNEL", ...
```
Can we consider a tool like : 
```python
requires = solve_ros2_package("PACKAGE"), ...
```
That will solve the remaining information : 
 - for `USER/CHANNEL`, we can just consider it's the same as the current package ? Or a default value like `ros2/something` ?
 - for `VERSION`, we can consider parsing the [repository list](https://github.com/ros2/ros2/blob/release-beta3/ros2.repos), and getting information from [raw.githubusercontent](https://raw.githubusercontent.com/ros2/rmw/release-beta3/rmw/package.xml).

**Comment by memsharded** [comment]
Thanks very much for the detailed information. Even if it seems possible, I would like to step back and learn the problem you are trying to solve. If ROS has its own package system, why would you like to use conan? What problem are you trying to solve? Is it a problem of the ROS community?

**Comment by astralien3000** [comment]
Good point ^^. I would say that mainly because I like to do weird experiments.

Getting more serious, I would like to use conan the same way they use [apt](https://github.com/ros2/ros2/wiki/Linux-Install-Debians) : to be able to distribute binary packages instead of compiling everything from source, or providing installers/zip files.

Also, conan do some tasks that are not handled by ament (or catkin for ROS1) : 
 - downloading automatically dependencies
 - compiling dependency only when needed (and not a whole workspace, which most of the time force to compile unwanted packages)

**Comment by mp3butcher** [comment]
I experienced hard time in past building of ros from sources (it was catkin at the time)
It was really painfull to download sources build and install for each of its components.
I'm not familiar yet with conan so i can't tell if it can help for this particular purpose.

**Comment by memsharded** [comment]
@mp3butcher do you mean building ROS itself from sources, or building some of the ROS modules?
I would say that if something could be improved for ROS, should be collaborating with the ROS community.

**Comment by gavanderhoorn** [comment]
This is an interesting topic, but as @memsharded wisely states: the use-case here seems a bit thin or underdefined.

@astralien3000 wrote:
> Also, conan do some tasks that are not handled by ament (or catkin for ROS1) :
> 
> - downloading automatically dependencies

For that we have `rosdep` in ROS. Afaik the decision to not have the build tool (or really: *driver*) download dependencies was a concious one, and separates concerns in a way I believe makes sense.

>  - compiling dependency only when needed (and not a whole workspace, which most of the time force to compile unwanted packages)

I'm unsure I completely understand this one: if the (binary) artefacts for a package already exist, it should be rebuilt, ever, unless there have been changes to any of the dependencies of those artefacts (ie: changes to the source files, (transiently) included headers, etc).

If you'd like to build only a subset of packages in a workspace, white and blacklists are supported last I checked.

**Comment by gavanderhoorn** [comment]
(The following this is off-topic for this issue, but I wanted to address it as it's also a summary of a typicaly from-source build in ROS (something which is actually discouraged, and should only be done if there are no binary pkgs available))

@mp3butcher wrote:
> I experienced hard time in past building of ros from sources (it was catkin at the time). It was really painfull to download sources build and install for each of its components. I'm not familiar yet with conan so i can't tell if it can help for this particular purpose.

I can't be certain where the problem(s) was (were) for you, but a from-sources build on a supported platform should really only be a matter of:

 1. install bootstrap prerequisites (4 python pkgs + compiler infra)
 1. generate workspace definition file (`.rosinstall`) based on targeted ROS release + desired pkgs
 1. seed workspace (ie: download everything in the `.rosinstall` file)
 1. resolve and install system dependencies (ie: everything *not* a ROS pkg) of pkgs in workspace
 1. build the workspace

There is almost a 1-to-1 mapping between these 5 steps and provided tooling (system pkg manager, `rosinstall_generator`, `wstool`, `rosdep`, `catkin`). It's a fairly automated process, so there should be no need to "download sources build and install for each of its components", at least not manually.

Now how much of the above process is a *smooth* process will depend on the targeted platform, so your mileage may vary.

**Comment by memsharded** [comment]
If anything I think conan might help in Windows, because the above:

> resolve and install system dependencies (ie: everything not a ROS pkg), based on workspace contents
build the workspace

Might be a bit challenging, depending on what system packages are: for example, installing OpenSSL, Boost, ZLib in a windows machine can be relatively painful. The thing can get worse if multiple versions of those libraries have to be supported, and also different compiler versions and architectures.

**Comment by gavanderhoorn** [comment]
For Windows it might be interesting, yes. There are however some efforts underway already, so such an effort might benefit from some coordination.

@dirk-thomas: anything you can add about the current status of ROS(2)-for-Windows packaging and dependency management?

**Comment by dirk-thomas** [comment]
We haven't done any work to package ROS packages for Windows yet. The idea is to generate the files necessary to create Chocolatey packages in `bloom` the same way as for Debian packages.

We have only packaged a couple of dependencies we need to ease the installation on our Windows buildfarm nodes: https://github.com/nuclearsandwich/eigen-choco, https://github.com/nuclearsandwich/tinyxml-choco

**Comment by memsharded** [comment]
I think there is a conan package for tinyxml in some community repo, and eigen, it is trivial to package it, because it is header only. There  is some ongoing work to package also OpenBLAS, etc, but eigen itself is trivial. If you are going with choco, good, if you want to give conan a try (of course we think there are some advantages to it :) ), please let us know, we would love to help.

**Comment by memsharded** [comment]
This thread is quite outdated. This is my view:

- It seems that parsing package recipes from other package management systems is not a demanded use case
- We have known of some users that are using both Conan and ROS together, for example, there is a talk planned at https://conandays.conan.io/. This will probably get its own Open Source integration, where users can contribute and helps others to use both technologies together. Keep tuned for this.

I think this issue can be closed now. Thanks for all the feedback!

**Comment by gavanderhoorn** [comment]
>  * We have known of some users that are using both Conan and ROS together, for example, there is a talk planned at https://conandays.conan.io/.

Would you have any more information about this presentation specifically?

**Comment by memsharded** [comment]
Not currently. This was going to happen 19-20 March, but it has been postponed. The speakers are listed in the web if you want to try to reach them.
