### ISSUE TITLE
Package uploads fail when uploading to off-box conan_server

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#2127]
Hi,

I'm getting an issue where I can upload a package to a locally hosted conan server, but when I upload the same package to a conan server on another box, the upload fails with 'File not found' errors for the conanfile.py and conan*.txt files. Below is the output I get (local is the local server, vesbuild is the offbox server):

		(venv) C:\Users\James\conan>conan remove -r local */*@*/* -f
		WARN: No package recipe matches '*/*@*/*'

		(venv) C:\Users\James\conan>conan remove -r vesbuild */*@*/* -f
		WARN: No package recipe matches '*/*@*/*'

		(venv) C:\Users\James\conan>conan upload -r vesbuild curl/*@3rdparty/stable --all
		Are you sure you want to upload 'curl/7.56.1@3rdparty/stable'? (yes/no): yes
		Uploading curl/7.56.1@3rdparty/stable
		Uploading conanmanifest.txt
		[==================================================] 58B/58B
		ERROR:
		Error uploading file: conanmanifest.txt, 'b'File not found''
		Uploading conanfile.py
		[==================================================] 2.2KB/2.2KB
		ERROR:
		Error uploading file: conanfile.py, 'b'File not found''
		ERROR: Execute upload again to retry upload the failed files: conanmanifest.txt, conanfile.py. [Remote: vesbuild]

		(venv) C:\Users\James\conan>conan upload -r local curl/*@3rdparty/stable --all
		Are you sure you want to upload 'curl/7.56.1@3rdparty/stable'? (yes/no): yes
		Uploading curl/7.56.1@3rdparty/stable
		Uploading conanmanifest.txt
		[==================================================] 58B/58B
		Uploading conanfile.py
		[==================================================] 2.2KB/2.2KB
		Uploaded conan recipe 'curl/7.56.1@3rdparty/stable' to 'local': http://localhost:9300
		Uploading package 1/2: bcf007d701fa6c408981841cb4602a11e0443e98
		Requesting upload permissions...Done!
		Uploading conanmanifest.txt
		[==================================================] 620B/620B
		Uploading conaninfo.txt
		[==================================================] 665B/665B
		Uploading conan_package.tgz
		[==================================================] 264.5KB/264.5KB
		Uploading package 2/2: fcc74f48e518fb435052e2cfeb3dacd21b9f1a62
		Requesting upload permissions...Done!
		Uploading conanmanifest.txt
		[==================================================] 620B/620B
		Uploading conaninfo.txt
		[==================================================] 667B/667B
		Uploading conan_package.tgz
		[==================================================] 246.9KB/246.9KB

Is there something I could be doing wrong? Both servers are clean, the credentials I'm using are correct, and they are both using the latest conan_server version installed from pip. I can also confirm that when uploaded from the same box as the server, the upload succeeds. Any advice would be appreciated!

Thanks.

**Comment by jamezmoran** [comment]
As an update, I found my problem. I hadn't set the 'host_name' variable in the server config, meaning the address of the file sent back to the client was localhost. This is also the reason for the confusing 'File not found' error since there was actually a server running locally. When closing the local server, it gives a much more helpful message:

    ERROR: HTTPConnectionPool(host='localhost', port=9300): Max retries exceeded with url: /v1/files/curl/7.56.1/3rdparty/stable/export/conanmanifest.txt?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV9wYXRoIjoiY3VybC83LjU2LjEvM3JkcGFydHkvc3RhYmxlL2V4cG9ydC9jb25hbm1hbmlmZXN0LnR4dCIsImZpbGVzaXplIjo1OCwiZXhwIjoxNTEyNjk0NDYxLCJ1c2VybmFtZSI6ImplbmtpbnMifQ.8fiOaDPN5jVefY-alBDzjsPrgJwTekWn4Pg3-A233GY (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CA29957BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

We should be good here.

**Comment by memsharded** [comment]
Sorry for the delayed answer, great that you solved the issue :)

As a reference, the necessary parameter is explained in this section: http://docs.conan.io/en/latest/server.html#server-parameters

Thanks for following up and the feedback!
