### ISSUE TITLE
Building and Linking a Project with visual_studio Generator and a Dynamic Linked Library

### ISSUE THREAD

**Issue by heilkn** [conan-io/conan#2128]
Dear Conan Team,

first of all I would like to thank you for your great work on conan.

While evaluating conan's possibilities I ran very fast into the following problem. I would like to build and deploy a shared library and use that as a dependency in an application. Unfortunately, I cannot build the application because it tries to link a static library which it cannot find.

I created a minimal example for this scenario and pushed it on github:
https://github.com/heilkn/conan-example-shared

The objection to the scenario is to use VisualStudio solutions as build system.

I hope you can help me solve the issue or this maybe a bug?

Kind regards

Konstantin

**Comment by memsharded** [comment]
Hi Konstantin!
Thanks for your kind words.

I am having a look to your example, and there are a few questions:

First, I am trying to package the library, so I am executing:
```bash
$ cd libA
$ conan create user/testing
...
>ERROR: libA/0.1@user/testing: Error in source() method, line 13
```

- You are cloning sources from a local, hardcoded path in cygwin. This is not reproducible, of course I don't have that repo :) 
- Also, if that repo is going to built with a visual studio solution, you need to copy also your .sln into the package. This is done with the ``exports_sources`` attribute (http://docs.conan.io/en/latest/reference/conanfile/attributes.html#exports-sources)
- The same ``exports_sources`` can be used to copy the library sources into the package recipe, so no need to fetch them with the ``source()`` method.
- Then, the App package seems a bit duplicated with the LibA. They are using the same repo (which is not a problem per se), but it seems that they might be building and packaging the same, so it is likely that both packages will package the same DLL, which probably you don't want.

If you could please clarify these points, that would help. It would be good if you use the ``exports_sources`` so everything is self-contained (you can use ``conan new Pkg/version -s`` to generate some sources for you (careful, it overwrites your conanfile.py) Thanks!

**Comment by heilkn** [comment]
Dear James,

thank you for your quick response. I updated the conanfile.py in the example repository. I would be happy if you find the time to try that again. Here are the steps that I execute before I run into the problem:
```
git clone git@github.com:heilkn/conan-example-shared.git
cd conan-example-shared/libA
conan create conan/testing
cd ../myApp
conan install
conan build .
```

I would like to address the concern you mentioned regarding the VS solution. That file is checked in along side the source files and is reference during the build step using the ``self.source_folder`` variable. Maybe, I am doing something not intended here, but this should not be the problem I observe, since the build is actually working. It only fails in the link phase of myApp where it tries to find libA.lib which is not available (it was build as a shared library).

**Comment by memsharded** [comment]
I have had another look. The main issue is that the VS project of the library (libA.sln) is NOT creating a linking .lib artifact at all, just the .dll. I am not an expert in configuring VS properties, but it seems that something is not properly configured. I am trying a few things more, but just in case this makes sense to you.

**Comment by memsharded** [comment]
Now I see what it is. You are in Windows, VS, and you are not exporting symbols! Thus, no .lib is created at all, there are no symbols to export/link with. In Win there are two methods to export symbols for DLLs:

- Using call convention like `` __declspec(dllexport)``. You can check the generated code with ``conan new Hello/0.1 -s``, you will find a very common idiom for this
- Using a accompanying .def file.

Please check this and tell me.

**Comment by heilkn** [comment]
Oh silly me! Of course I forgot to export the symbols :( Doing so properly, I manage myApp to build and run now. Thank you very much.

Please allow me a follow-up question: To run the final executable it is necessary to have all the dlls from the dependencies in the path or better current directory. It would be a good idea to package all those files along the final package. Is there a standard way to achieve that with conan? Or how can one iterate over all the bin directories of all dependencies in the package() method of myApp's conanfile.py?

**Comment by memsharded** [comment]
Good! :)

Yes, there are several approaches, depends on what you want to achieve:

- with the ``imports()`` method and the ``keep_imports`` attribute, it is easy to re-package dependencies, if that is what you want. Basically the ``imports()`` iterate over the full dependency graph, copying files.
- If you don't want to re-package, and use the original "LibA" package DLL, you can use for example use virtualenvs, that define PATHs to binaries. So for example, when you install you can do something like:

```bash
$ conan install .. -g virtualrunenv
$ activate_run
$ myapp
```

- There is also a ``deploy()`` method, similar to the imports() one, but that it works over the currently installed package, have a look to :http://docs.conan.io/en/latest/packaging/running_packages.html?#deployable-packages


This section might help: http://docs.conan.io/en/latest/packaging/running_packages.html

**Comment by heilkn** [comment]
Thank you very much for your detailed answers and your patience!

**Comment by memsharded** [comment]
Very glad to help! Do not hesitate to ask any further question or report any problem you might have, we will try our best to help. Cheers!
