### ISSUE TITLE
Conan upload to artifactory under Linux gives 405 Method not allowed

### ISSUE THREAD

**Issue by sturmf** [conan-io/conan#2130]
Hi,

I am a bit puzzled, I am using conan 0.28.1 (but also tested with 0.29.2) to upload a package from Linux but I always get this output:

```
Uploading zlib/1.2.11@sturm/stable
ERROR: {
  "errors" : [ {
    "status" : 405,
    "message" : "Method Not Allowed"
  } ]
}. [Remote: artifactory]
```
This is really strange since the connection itself seems to work. I actually downloaded the recipe and source from artifactory and could build the package.

The same thing works from a windows machine, but there I can't build the Linux versions of the package, so it is no option. 
I also disabled ipv6 since I saw that this was a problem somewhere else.

The artifactory version is: 5.5.1

Any help would be greatly appreciated, since I am pretty much blocked right now.

**Comment by memsharded** [comment]
This is very weird indeed. If you are fully sure it worked from other OSs, and you can install packages too, I don't know what it could be. The IPv6 was related to Bintray, but I think doesn't affect Artifactory.

Please check your remotes (``conan remote list``) in Linux and the other OSs. Also, make sure to clean the user login info (``conan user --clean``). Also more info about your Linux install (linux distro, how did you install conan), and also if it happens the same in other Linux machines, or maybe it is just that one.

**Comment by lasote** [comment]
Also try to gather some trace from the Arrifactory logs. Maybe there is some useful information about what is happening. The first thing is to see if the request is reaching the Arrifactory. Maybe a permissions issue? Could be possible that it is working on Windows because the packages are already uploaded ? Did you introduce some change in the Artifactory permissions?

**Comment by sturmf** [comment]
Hi, thanks for the quick replies. Here my answers to the questions, even so I think they don't add much more info. I also try to get the artifactory logs but that could take some time :-( Is there any trace I could do in conan?

Remotes: I checked the entries and they are the exact same

Clean user: I did this several times, and I tried two different accounts, no change

Linux install: Ubuntu 16.04.3

Conan install: Regular install through pip, first the 0.28.1 since that is currently our default and then upgraded with pip to 0.29.2 Same result

Package already uploaded: I also created a completely new recipe, but I still can't upload it

Permissions: So far no changes were done, but of course you never know what happens in the background. One interesting bit is that the AD user has capital letters but I can only login through conan if use all small caps. But I can't imagine that would be different between download and upload on the server auth?

I will try more random stuff but unfortunately are out of ideas atm.

**Comment by memsharded** [comment]
Can you upload other package from Linux? Try with conan new hello/0.1 +
conan create user/testing + conan upload hello* --all

Just to rule out there is something weird in the package name. Thanks!

**Comment by sturmf** [comment]
Ok I now have a lead. It seems that under Windows the upload happend with a POST request and under Linux it happens with a GET request which is not allowed. One more difference seems to be the version of the requests libray, but I would hope this would not explain the switch to a GET request.

Here the good log:

```
"GET /api/conan/myrepo/v1/conans/hello/0.1/user/testing/digest HTTP/1.1" 404 74 "-" "python-requests/2.18.3" 836 8508 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
"GET /api/conan/myrepo/v1/users/check_credentials HTTP/1.1" 200 - "-" "python-requests/2.18.3" 455 359 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
"GET /api/conan/myrepo/v1/conans/hello/0.1/user/testing HTTP/1.1" 200 3 "-" "python-requests/2.18.3" 461 390 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
"POST /api/conan/myrepo/v1/conans/hello/0.1/user/testing/upload_urls HTTP/1.1" 200 288 "-" "python-requests/2.18.3" 615 677 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
```

And here the bad one:

```
"GET /api/conan/myrepo/v1/conans/hello/0.1/user/testing/digest HTTP/1.1" 404 74 "-" "python-requests/2.12.4" 1171 8513 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
"GET /api/conan/myrepo/v1/users/check_credentials HTTP/1.1" 200 - "-" "python-requests/2.12.4" 515 359 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
"GET /api/conan/myrepo/v1/conans/hello/0.1/user/testing HTTP/1.1" 200 3 "-" "python-requests/2.12.4" 521 390 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
"GET /api/conan/myrepo/v1/conans/hello/0.1/user/testing/upload_urls HTTP/1.1" 405 83 "-" "python-requests/2.12.4" 546 508 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384

```

**Comment by memsharded** [comment]
Yes, this is really strange. I would recommended a full clean installation, it could be that something his corrupted, even with that python-requests version, issuing a GET in that endpoint doesn't seem possible with current codebase.

You might try to add some prints to the ``def _get_json(self, url, data=None)`` function in conan codebase, which is the one being called, always with data != None, so it should contain something and force a POST. Please ask for help if you need (we can connect in slack if you are there)

**Comment by sturmf** [comment]
Ok, I finally found the problem. In the end it was my fault. On the windows machine I had the https url and on the Linux machine the http one. So the linux request was redirected to the https address but unfortunately this is then resend as a GET request.
I am not sure why it is redirected to a get request and if this is a problem of the apache which is in front of the artifactory server. 
Anyways I have a solution now and this can be closed.

**Comment by memsharded** [comment]
Thanks for updating on this, glad that you finally found the issue (and it is not in conan code :) :) ) and have a solution.

**Comment by Manu343726** [comment]
I've reproduced this on some of my Gitlab CI jobs (See https://gitlab.com/Manu343726/clang-conan-packages/-/jobs/69045509, at the end. The full job matrix is https://gitlab.com/Manu343726/clang-conan-packages/pipelines/22237331. Note not all jobs are failing bc of this issue).

All jobs use conan-docker-tools images to run (The specific image matches the job name, check the compiler there).

I will try to get more info on the issue.

**Comment by Manu343726** [comment]
More info: I'm getting read timeouts when conan upload tries to submit my llvm packages (~1.5GB uncompressed aprox) https://gitlab.com/Manu343726/clang-conan-packages/-/jobs/69374288

I'm not sure this is related to the 405 error that happens later.

**Comment by memsharded** [comment]
This issue initially reported about Artifactory, but it seems you are using Bintray. You might be hitting the quota limits, maybe the max file (360Mb), or the total capacity. Please check your inbox too for notice about this limits.

**Comment by Manu343726** [comment]
I can confirm now the issue was the bintray upload size limit. All release and MinSize builds succeeded. Thanks for the feedback.
