### ISSUE TITLE
Should 'conan info' be able to resolve non-existant dependencies if we could supply the missing conanfiles?

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#2131]
Essentially I'm trying to create a build order for a package which depends on another package that isn't currently on our local conan repo, but this isn't possible due to the fact that conan doesn't yet know about the other package. It seems the only way to solve this is to manually build the new dependencies in the correct order and push them to conan before any build can be executed on the dependents.

Would it be useful and/or practical to be able to supply the missing conanfiles to conan and let it use them to fill in the blanks? Right now, I don't think it's really possible to automatically add multiple new interdependent packages without manual intervention or custom scripts to generate the dependency graph, which is a shame because this is already functionality that works in conan but only for packages which are already uploaded.

Thanks!

**Comment by memsharded** [comment]
I am not fully sure what you mean with:

> Would it be useful and/or practical to be able to supply the missing conanfiles to conan and let it use them to fill in the blanks?

I think this is basically what ``conan export`` does. The export does not analyze dependencies, or do nothing, just put the conanfiles in the local cache, so they can be used. The order to export should be irrelevant, even large parts of their contents, are not evaluated until a ``conan create`` or ``install`` is executed.

**Comment by jamezmoran** [comment]
Yes, I think that's exactly what I wanted! Thanks!
