### ISSUE TITLE
Windows build of clion-conan-consumer broken

### ISSUE THREAD

**Issue by kaidokert** [conan-io/conan#2136]
Trying to build with everything up to date and default according to instructions here on win
`http://docs.conan.io/en/latest/integrations/clion.html`

Started with an odd error of

```
ERROR: zlib/1.2.11@lasote/stable: Error in build() method, line 59
	cmake = CMake(self.settings)
	ConanException: First argument of CMake() has to be ConanFile. Use CMake(self)
```

This happens because zlib conanfile for that version contains:
```
                if not tools.OSInfo().is_windows:
                     <working code>
                else:
                    cmake = CMake(self.settings)                
                    cmake.configure(self, build_dir=".")
                    cmake.build(self, build_dir=".")
```

Apparently calling CMake with settings like CMake(self.settings) is an old api ?

To work around this, the attached patch made it work, but is horribly hacky. 

It looks like either the old api should be explicitly forbidden and old conanfiles should be forced to upgrade, or a compatibility codepath should work and be tested, too.

[conan_hack.txt](https://github.com/conan-io/conan/files/1546154/conan_hack.txt)

**Comment by memsharded** [comment]
Yes, that is true, latest version of conan removes the old usage of cmake.
There is already a modern  zlib package that you should use instead of that one:

``zlib/1.2.11@conan/stable`` from conan-center: https://bintray.com/conan-community/conan/zlib%3Aconan

Please try it instead.

I also see that the new zlib is used in http://docs.conan.io/en/latest/integrations/clion.html, did you get it from the figure of point 4? Thanks!

**Comment by kaidokert** [comment]
So i just cloned `https://github.com/lasote/clion-conan-consumer.git` and tried to build.
Worked fine on Mac/Linux, on Win/Clion its a bit of a mess.

The repo conanfile only references libpng, which resolves to here : https://www.conan.io/source/libpng/1.6.23/lasote/stable
This one in turn has `requires=zlib/1.2.11@lasote/stable` NOT `zlib/1.2.11@conan/stable`. If you separately try to include `zlib/1.2.11@conan/stable` at the project root, it won't build libpng with the correct zlib as dependency .. 

Looks like a correct fix is to republish libpng, and then update toplevel accordingly.

In addition, Win has a bunch of special issues with Cygwin vs Mingw builds and "unix makefiles" vs "mingw makefiles" generation. Generally, no packages really build with Cygwin, and Mingw only ships an ancient compiler.

**Comment by lasote** [comment]
I've updated the repository, also the README pointing how to add the `conan-community` repository, where the dependencies are updated. Eventually will be pushed to `conan-center` too.
About the `mingw`, `cygwin`, `msys2` etc, we know, we are trying to improve the part on the plate of conan, the integration of build_requires for these subsystems, but if the library build system or code is not prepared, there is nothing to do.

**Comment by kaidokert** [comment]
I can confirm this specific issue is now gone, if conan-community remote is is enabled. I still hit libpng build issues even with mingw, but thats not Conan api problem.

To guard against future API conflicts wouldn't it be good to ensure that major conan API version being called from Conanfile is verified against ?

libpng build still being b0rked is a separate ticket probably, log attached just in case.

[conan_libpng_build_fail.log](https://github.com/conan-io/conan/files/1548891/conan_libpng_build_fail.log)

**Comment by memsharded** [comment]
> To guard against future API conflicts wouldn't it be good to ensure that major conan API version being called from Conanfile is verified against ?

Yes, but conan is still 0.X, so still in beta, checking and maintaining multiple conan API is not yet there. We will try to improve these things when conan 1.0 is released

>libpng build still being b0rked is a separate ticket probably, log attached just in case

Yes, it definitely seems a ticket for the specific package, not supporting mingw build (actually many recipes doesn't support mingw, as its usage is still very low compared to VS)

Thanks for your feedback!

**Comment by kaidokert** [comment]
Probably way out of date by now
