### ISSUE TITLE
Use "conanbuildinfo.cmake" for cmake_multi

### ISSUE THREAD

**Issue by Enhex** [conan-io/conan#2148]
`cmake` generator creates `conanbuildinfo.cmake`.

`cmake_multi` generator creates `conanbuildinfo_multi.cmake`.

Why not just use `conanbuildinfo.cmake` instead of `conanbuildinfo_multi.cmake` for the `cmake_multi` generator, so there's no need to modify the `include` in `CMakeLists.txt` when switching between them?

**Comment by memsharded** [comment]
That is a good point. The main reason is that there are users that are using both, `` typically the ``cmake_multi`` for their own edition or IDE, and ``cmake`` for package creation, and they will collide otherwise. Note that they can be defined in the command line, so ``cmake`` can be in the conanfile, and then do ``conan install .... -g cmake_multi`` because you want to use your multi-config IDE instead.

**Comment by Enhex** [comment]
Personally I would use a different build directory for each generator, though with `cmake` and `cmake_multi` it's kind of a special case because they use the same generator, and in my experience they don't inherently need different `CMakeLists.txt` files.

If someone wants to use both `cmake` and `cmake_multi` it can be done in separate directories as if they're different generators, while using the same `CMakeLists.txt` for both.
Doing it in the same build directory would override the generated project files anyway.
(Unless there's some problem with that that I'm unaware of)

**Comment by lasote** [comment]
I partially agree, but changing now the name can break many many things. Maybe we could think about a way to configure the names of the files that will be generated by some generators, but I'm not sure, probably it's better to keep it simple and with the same name for everyone.

**Comment by memsharded** [comment]
Conan 2.0 will deprecate and remove the ``conanbuildinfo.cmake`` and the ``cmake`` generator.
The default will be ``CMakeDeps`` that provides a more transparent ``find_package()`` integration with CMake. Also ``CMakeToolchain()`` to provide the configuration not from dependencies.

So this issue can be closed, thanks!
