### ISSUE TITLE
OpenSSL requesting settings.compiler.runtime with GCC

### ISSUE THREAD

**Issue by LB--** [conan-io/conan#215]
I am trying the [Getting Started tutorial](http://docs.conan.io/en/latest/getting_started.html) on Windows 10 64-bit with [nuwen MinGW](http://nuwen.net/mingw.html) GCC 5.3 using conan 0.8.3, and I'm having a bit of trouble. My conan.conf has these lines:
```plain
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=5.3
compiler.libcxx=libstdc++11
os=Windows
```
When I set up the Getting Started example and run `conan install`, this is my output:
```plain
Poco/1.6.1@lasote/stable: Not found, looking in remotes...
Poco/1.6.1@lasote/stable: Trying with 'conan.io'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Downloading conan_export.tgz
[==================================================]
OpenSSL/1.0.2e@lasote/stable: Not found, looking in remotes...
OpenSSL/1.0.2e@lasote/stable: Trying with 'conan.io'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Downloading conan_export.tgz
[==================================================]
zlib/1.2.8@lasote/stable: Not found, looking in remotes...
zlib/1.2.8@lasote/stable: Trying with 'conan.io'...
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Downloading conan_export.tgz
[==================================================]
Requirements
    OpenSSL/1.0.2e@lasote/stable from conan.io
    Poco/1.6.1@lasote/stable from conan.io
    zlib/1.2.8@lasote/stable from conan.io
Packages
    OpenSSL/1.0.2e@lasote/stable:c55b5bfe2b1ae23db6b3b5951282ccd2cb689f81
    Poco/1.6.1@lasote/stable:c0f6c443d1ad97c5f4abf7b16fbee7ef162b83ac
    zlib/1.2.8@lasote/stable:cd3e418e619287a431ed81161646f9073dcb193e

ERROR: Error in OpenSSL/1.0.2e@lasote/stable
        package_info()
        'settings.compiler.runtime' doesn't exist for 'gcc'
'settings.compiler' possible configurations are ['version']
```
I'm not sure what to do here - I have tried providing a value for `compiler.runtime` but I still get the same error message. It looks like I am not supposed to define `compiler.runtime` at all. Is this an issue with the OpenSSL package itself?

(Note: I was previously in contact with James via email support, and he told me it was best to open this issue here)

**Comment by lasote** [comment]
Hi, I usually build the packages with visual studio in windows, gcc in linux and clang in macos.
Yes, the error is the conanfile.py file in the OpenSSL package, it hasn't been tested with mingw.
You can take a look to the recipe here:
https://github.com/lasote/conan-openssl/blob/release/1.0.2e/conanfile.py
I haven't much time to do it right now, If you want to you can try to solve yourself and make me a PR to the conan-openssl repository. 

1. Clone the repository
2. Edit the conanfile.py file and prepare it for mingw (the error it that I'm assuming that if you are in windows you use "Visual Studio" compiler, so maybe there is some "ifs" to review)
3. Execute "conan export lasote/stable"
4. In your getting started project run the "conan install" command and try it. If it doesn't work go back to point 2.
5. If works, commit the changes and make a Pull request to lasote/conan-openssl repository.

If you fix the OpenSSL conan's package will be a great contribution to the community.

**Comment by LB--** [comment]
Hmm, I just had some more time to look into it, and it seems that [compiling OpenSSL with MinGW](https://wiki.qt.io/Compiling_OpenSSL_with_MinGW) is very non-trivial and involves using MSYS. Unfortunately, using MSYS is not an option for me, not to mention my python skills are rusty right now. This is looking to be way too much for me to handle in my free time, so I'm sorry to say I won't be able to help here. I'll just stick to Visual Studio in this case...

Would it be best to close this issue and open a new one at https://github.com/lasote/conan-openssl/ or is this one here sufficient?

**Comment by memsharded** [comment]
No problem, very understandable. I am closing this issue, yes, I think it is better to have it open in the conan-openssl repository, as it is not a real conan issue or bug, so if you want to open it there, that would be fine. Thanks!
