### ISSUE TITLE
ImportError: cannot import name ConfigureEnvironment

### ISSUE THREAD

**Issue by ilovezfs** [conan-io/conan#2153]
Attempting to upgrade the Homebrew formula from 0.29.2 to 0.30.1 the test block fails with
```
ERROR: Unable to load conanfile in /tmp/conan-test-20171213-43297-tno48c/.conan/data/zlib/1.2.8/lasote/stable/export/conanfile.py
  File "/tmp/conan-test-20171213-43297-tno48c/.conan/data/zlib/1.2.8/lasote/stable/export/conanfile.py", line 4, in <module>
    from conans import CMake, ConfigureEnvironment
ImportError: cannot import name ConfigureEnvironment
```
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/14579/version=sierra/testReport/junit/brew-test-bot/sierra/test_conan/

This is from running
```
  test do
    system bin/"conan", "install", "zlib/1.2.8@lasote/stable", "--build"
    assert_predicate testpath/".conan/data/zlib/1.2.8", :exist?
  end
```

The failure does not occur with 0.29.2

**Comment by memsharded** [comment]
Yes, conan is preparing 1.0, and is removing somethings that have been deprecated long time ago. ``ConfigureEnvironment`` has being showing deprecation warnings for many months now.

The recipe you are using is an old one, from conan-transit. I think it should be better if you tried with ``zlib/1.2.8@conan/stable`` or ``zlib/1.2.11@conan/stable`` from conan-center repo. Thanks!

**Comment by ilovezfs** [comment]
@memsharded thanks! That does the trick.
