### ISSUE TITLE
pkg-config generator generates .pc files for build requirements

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2155]
Hi,

First of all I'm not sure if this is bug or a wanted behavior.

I'm currently writing swift bindings for a C library, which I want to wrap as a "system module" (see [LLVM modules](https://clang.llvm.org/docs/Modules.html#module-map-file) for more information)

The [Swift Package Manager](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md#pkgconfig) can takes `.pc` files to help a package locate headers/deps.

So my package has a build requirement on `llvm/5@theo/stable` and I have this `conanfile.txt`:

```ini
[requires]
mylib/0.1@theo/stable
[options]
mylib:shared=True
[generators]
pkg_config
xcode
```

Running `conan install .` generates `mylib.pc` **and** `llvm.pc`. The `llvm` flags are also added to the `conanbuildinfo.xcconfig` file.

`swift` can generate a `.xcodeproj`, and users can provide a `.xcconfig` file.
When doing so, and running `xcodebuild`, `swift` will look in the `llvm` standard library headers, and errors like the following happens:

>Undefined symbols for architecture x86_64:
  "_memmove", referenced from:
      ___swift_memmove_array24_8 in tanker_swift.o
     (maybe you meant: ___swift_memmove_array24_8)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Removing those flags by hand in the `.xcconfig` solves the issue.

EDIT: forgot the question

Shouldn't `build_requires` be discarded by generators?

**Comment by memsharded** [comment]
How is the ``build_requires`` being applied? In the package recipe, or in a profile?
Because in profiles, they are defined to apply as build_requirement also for the current project (in this case, your conanfile.txt). You might try in your profile something like:

```
[build_requires]
&!: llvm/5.0@user/testing
```

That is the way to say: apply llvm to all packages, but the current consumer.
It is just an idea, might be failing something else, extra checks are needed.

**Comment by theodelrieu** [comment]
Right they're inside a profile, I could hard-code `mylib` in the profile.

There are use-cases where generators should produces files for the build-requirements as well. (e.g. one of my dependencies' `test_package` step has to include/link against llvm libs...)

I will try it out and let you know, thanks.

**Comment by theodelrieu** [comment]
Your suggestion works great, it might break in some `test_packages`, I'll let you know if I encounter a wall of bricks later on :)

**Comment by memsharded** [comment]
Ok, let me know then :) 
Thanks!
