### ISSUE TITLE
configure another compiler for Boost

### ISSUE THREAD

**Issue by danielgavrila** [conan-io/conan#2156]
Hello,

I would like to configure with another compiler (not the default compiler) for installing Boost 
I read the  issue #1876 and seems that I have to create at installation an user_config.jam where I will define the toolset:
`using gcc : 7.2 : mypath/to_compiler ; `

How can I do this ? Or is another way to do it ?

Best regards,
Daniel

**Comment by memsharded** [comment]
Which Boost are you talking about? From which remotes? You might want to follow the URL for that package and contact directly the package authors for info. Typically you define the conan settings as input either to ``conan install`` existing dependencies or to ``conan create`` new packages, and the package will manage to pass the values to the build system of the package. In conan there is no "default compiler"; there is a default profile that is usually auto-detected, but you can change it or use any other settings.

**Comment by danielgavrila** [comment]
Hi James,

everything is working fine.Just have to export the CXX and CC before starting cmake

`export CC=/usr/local/pkg/gcc-7.2/bin/gcc`
` export CXX=/usr/local/pkg/gcc-7.2/bin/g++` 

Best regards,
Daniel






```

**Comment by memsharded** [comment]
Ok, great then :)

I guess that defining a profile for that can be very useful, like:

**mygcc72** file
```
[settings]
os=Linux
compiler=gcc
compiler.version=7.2
compiler.libcxx=libstdc++11
arch=x86_64
build_type=Release

[env]
CC=/usr/local/pkg/gcc-7.2/bin/gcc
CXX=/usr/local/pkg/gcc-7.2/bin/g++
```
You can put this file in ``<userhome>/.conan/profiles`` or in any other folder. You can have as many profiles as you want. Also share with your team with ``conan config install``. Then use it with:

```bash
$ conan create user/testing --profile=mygcc72
```

**Comment by danielgavrila** [comment]
Sorry ,but now I'm totally lost .I have this profile,I use:
`conan install .. --profile=mygcc72`
but to go further I have to export the CC and CXX variable.

Without this cmake is complaining that the compiler version does not match

**Comment by memsharded** [comment]
Oh, yes, that is mainly to automatically activate the env-vars within conan (for example, for package creation with ``conan create``, or for building with ``conan build``). If you are calling cmake directly yourself, you have to activate them as you did, sorry for the incomplete explanation.

**Comment by lasote** [comment]
Hi! can this issue be closed?

**Comment by danielgavrila** [comment]
Hi!
Yes, thanks for your support
