### ISSUE TITLE
Failure in install mingw_installer

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2158]
Something is failing in mingw-installer package:

```
RROR: mingw_installer/1.0@conan/stable: Error in build() method, line 118
        tools.download(files[keychain], "file.7z")
        KeyError: '64_x86_64_sjlj_win32'
```

cc @sigmoidal

**Comment by sigmoidal** [comment]
I found out this is due to the MinGW installer not supporting gcc 6.4, so it can't look it up. Not a conan issue, sorry to raise the alarm.

**Comment by memsharded** [comment]
Ok, thanks for telling. Then this issue can be closed here, please report in mingw_installer package repo. Thanks!
