### ISSUE TITLE
Deleting build directory after "conan test"

### ISSUE THREAD

**Issue by niosHD** [conan-io/conan#2160]
Is there any reason why "conan test" does not delete the build directory in the test_package after the execution? In case of a failed test it may makes sense to keep the build directory around for debugging but if the test is successful I would prefer to delete the build directory at the end.

Best,
Mario

**Comment by memsharded** [comment]
Hi Mario,

Yes, many times the result of test might be a complex application, graphical, requiring user input... so the automatic test basically checks its existence, and users launch it manually after conan test. Also, it is not easy to capture all app failures for all kind of apps, so better leave things there by default, as cleaning is just one ``rm -rf test_package/build``. Cheers!

**Comment by niosHD** [comment]
Hi James,

ok, it seems like I kind of misunderstood the purpose of the `test_package`. I did not anticipate that manual checking is part of the expected work flow and I am not convinced that having a test which does not work fully automated is a good test in general.

The reason why the build directory in the `test_package` bothers me is that I work hard to keep my working copies pristine. I am of the opinion that the build process should not alter the source directory in any way and therefore build all my projects out-of-source. Conan allows me to have similar properties except for `conan test` and `conan create`. Ending up with the `test_package/build` directory feels more like an unexpected and unwanted side effect for me. What would happen if `build` is part of my `test_package` source anyway?

Do you have any idea if it is common that the build artifacts of a `test_package` are needed? If it is not very common, maybe it would be best to build the `test_package` in a temporary directory (i.e., completely out of  the source tree) which is deleted on success. For users which want to use artifacts from the `test_package` an option for specifying the build directory, which also disables the automatic deletion, could be added.

Best,
Mario

**Comment by memsharded** [comment]
>  I did not anticipate that manual checking is part of the expected work flow and I am not convinced that having a test which does not work fully automated is a good test in general.

It is not expected flow, most tests are indeed automatic. At least the automatic part can check that the .exe has been created. Then it is up to the user to run further manual tests. I would say it is not that common, maybe 5% of cases (successful builds with manual runs), but when something fails, then it is really annoying not able to check, so both things together added up to the current implementation

Yes, I think specifying a build directory could be a valid feature, but I would like to ask other users if they are fine with opt-in behavior. Also cc/ @lasote

**Comment by lasote** [comment]
The example of test_package use to be simple, so if something fails I go to the package folder, not to the test_package/build one (I can't remember debugging something there). So I could agree to opt-in to keep the test_package/build/xxxx folder. In the other hand, I don't care about the build folder to be there, but I understand it's a little dirty.

**Comment by memsharded** [comment]
CLosed by https://github.com/conan-io/conan/pull/2214
