### ISSUE TITLE
conan search command : add "-remote *" or "all"

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#2161]
Currently, to the best of my knowledge, there is no ability to search all configured remotes for a packages in one command.  One has to go through each remote manually.  It doesn't seem terribly hard to add the feature to search multiple remotes in a single command.  It's not urgent however, it's a fairly low priority.

**Comment by danimtb** [comment]
There is a PR open already: https://github.com/conan-io/conan/pull/2138

I think this is what you are looking for

**Comment by uilianries** [comment]
Also, could be supported multiple remotes:

`conan search -r bintray,foo,bar package/0.1.0@user/channel`

This command gonna search on remotes *bintray*, *foo* and *bar*

**Comment by lasote** [comment]
In case we implement this feature for multiple remotes (I'm not opposed but for me, not a big priority) the syntax should be:

`conan search -r one_remote -r other_remote package/0.1.0@user/channel`

We used the commas to separate parameters some time ago but we decided to use multiple parameters.

**Comment by uilianries** [comment]
Okay, I agree. This is the same usage for multiple settings and options.

**Comment by kaidokert** [comment]
I updated my PR, but i don't want to block this as i don't really have time, feel free to reject or merge and put in a more complete version.
