### ISSUE TITLE
The website should link to bincrafters repository (and other active repositories)

### ISSUE THREAD

**Issue by lamefun** [conan-io/conan#2166]
Specifically: https://bintray.com/bincrafters/public-conan

I took a glance at the https://bintray.com/conan page and the obvious conclusion was that the package manager was abandoned for some reason after it moved to JFrog (as latest activity shows no releases in conan-transit and few releases in conan-center) and wrote it off, but then discovered the fairly active Bincrafters repository by accident in a Reddit post.

**Comment by memsharded** [comment]
We are working on a new homepage, will take that into accunt, thanks for the feedback!

**Comment by lamefun** [comment]
Can this be done with the current website? I think it really should be done sooner rather than later. The issue #1676 mentions a global Bintray search box, but it seems to be gone now.
