### ISSUE TITLE
compiler.libcxx setting getting ignored

### ISSUE THREAD

**Issue by Chaosteil** [conan-io/conan#217]
I'm building a project on Linux that is using a compiled boost library, and I have in its `conanfile.py` this defined:

``` python
def config(self):
    self.settings.compiler.libcxx = 'libstdc++11'
```

And in my global `~/.conan/conan.conf` settings I have `compiler.libcxx` defined as

```
[settings_defaults]
...
compiler.libcxx=libstdc++
```

Now, when selecting the boost dependency, instead of selecting the project-requested `libstdc++11` version, it selects the `libstdc++` version, thus unable to link the libraries. I would've expected it to honor the project settings over the global settings. I have to either run conan install with some unsightly parameters or adjust my global config to get it working, but I would've rather not to either of those, if I have the requested setting defined in my `conanfile.py`.

Is this by design or simply an oversight? If it's an oversight, I'd gladly fix this myself if I get a few pointers on where to look.

**Comment by memsharded** [comment]
The settings are different from options in the sense that they are global for the whole project being managed. It is assumed that they have the same values for all dependent packages. It is possible though, that a package does not depend on some of them, as a header only library does not depend on OS, compiler..., so those settings can be removed in the header only package recipe (declaratively or in config())

Settings values should be thought as read-only, and modifying any of their values, could affect only the package doing those changes, but not upstream (in your case, just your package, but not boost).

Options are much different, they are propagated upstream-downstream and they handle conflict resolution similarly to dependencies versions.

If your project links against libstdc++11, just specify it in your command line:

```bash
$ conan install -s compiler=gcc -s compiler.version=5.3 -s compiler.libcxx=libstdc++11
```
or just change the default in your conan.conf, if you intend to use always that setting for your projects.

Please tell me if this makes sense, or if you have further questions. Cheers!

**Comment by Chaosteil** [comment]
That's exactly how I solved it, but I guess with my post I mostly meant that that wasn't expected behavior. 

I guess I am looking for a way to tell conan that my project is a C++11+ project, and instead of specifying options in the command line to handle libstdc++11, I would love to specify it in my conanfile, so I (or someone else) wouldn't have to type in all the parameters every time with `conan install`.

**Comment by memsharded** [comment]
From our point of view, they are different things. One thing is that your project uses C++11, which is a build configuration, and a different one is to use libstdc++11. You can definitely use C++11 without linking with libstdc++11. Such setting is to define such linkage. Note that your consumers always have to specify if they are using libstdc++ or libstdc++11 (or libc++), you cannot decide for them.

If you want to specify that your package only works if linked with libstdc++11, make a check in config() and throw an exception, telling the user that such setting is unsupported.

C++11 specification for compiling is done in the build system, though it can be propagated. Suppose you build a package called "A", and such package has headers that require C++11. You will have some configuration, for example in your CMakeLists (if you use cmake), that will tell to build with C++11.Then, you can define in your conanfile.py package_info() something like (not necessarily working, just an idea):

```python
def package_info(self):
    if self.settings.compiler == "gcc":
         self.cpp_info.cppflags = "-std=c++11"
```

That flag will be propagated downstream to consumers, and translated with the corresponding generator, for example, if the consumer of your package uses cmake, there will be a CONAN_CPPFLAGS and a CONAN_A_CPPFLAGS that will contain such c++11 flag, so consumers can build against it.

Tell me if this is clear or if you have any other question, thanks!

**Comment by Chaosteil** [comment]
First of all, thanks for all your extensive answers, I do indeed get a better picture of how conan works now!

While yeah, I could possibly just throw an exception on how I would only want libstdc++11, I believe it would also make sense if I could somehow let the package decide which defaults it finds most sensible instead of doing something drastic like an abort, though I see how it might also be confusing.

But again, I also found it confusing that it pulled a non-libstdc++11 dependency and then failed to link properly, and I mostly would like to mitigate that without telling everyone to `conan install <list of parameters>`, keeping ease of use in mind. Would it make sense to perhaps specify something like that right next to the actual dependency? Just thinking out loud here.

**Comment by memsharded** [comment]
That is a very interesting point indeed. Something that could serve as supported platforms, but before pulling the dependency. Don't know how to address it, but will think about it. We have fields as "author, license, etc" that can be inspected for dependencies with "conan info". Maybe some other text field, or even including the class docstring, so if I am interested in your package, I can write "conan info YourLib/2.2@Chaosteil/stable" and I will just read about it.

About the incorrect linkage, there are different approaches. I think that most packages, even if built with gcc > 5.1and c++11/14, they can link with libstdc++ instead of libstdc++11, just using the _GLIBCXX_USE_CXX11_ABI definition (as explained in the blog post: http://blog.conan.io/2016/03/22/From-CMake-syntax-to-libstdc++-ABI-incompatibiliy-migrations-are-always-hard.html). Is there something in your package that disallows linking with the old ABI libstdc++? Of course, if your project build (cmake) doesn't support the option, it will fail, but someone else could provide it and do a PR to your project, so it is able to do it (for example, to support it in Ubuntu 14?) So, in principle, there is no reason to forbid or declare that your package is only libstdc++11, as it could be also libstdc++ with some minor modifications. What do you think? 

BTW, to get more ideas about conan, today we published a blog post explained some design decisions, maybe you want to have a look: http://blog.conan.io/2016/03/30/are-c-and-c++-languages-ready-for-the-npm-debacle.html

**Comment by Chaosteil** [comment]
As a sidenote, I actually agree with a lot of the decisions in conan (I might be naive though, as I'm just a casual package manager user), and I personally would love to see usability issues like this ironed out, as hard as that is for C++. As said, I would like to implement the solution to this myself should we come to one.

To get back to this issue, I am actually specifying my C++ version through `set(CMAKE_CXX_STANDARD 14)`, which then gives (allegedly, didn't try) a cross-platform way to enable C++14 features. This then enables `-std=gnu++14` on my Linux machine when building object files. I didn't see any other special flags injected by CMake to make when running `make VERBOSE=1` on my package.

This then of course seems to disallow any linking with the boost libstdc++ version, which is pulled by default even though my project doesn't support it. I think rather declaring it in the conanfile that I only support libstdc++11 as dependencies makes the most sense. Should the package ever support the regular libstdc++ versions as well, it would reflect that at that point through the content of the conanfile, at least that's how I think it should be.

**Comment by memsharded** [comment]
Actually, it is already possible to specify that a package only supports certain settings.
For example in your use case, if you only support linking with libstdc++11, you could do something like:

```python
from conans import ConanFile

class SayConan(ConanFile):
    name = "Say"
    version = "0.1"
    settings = "os", "compiler", "arch"
    
    def config(self):
        if "libcxx" in self.settings.compiler.fields:
            self.settings.compiler.libcxx.remove("libstdc++")
```

It is also possible to restrict settings in the definition of the settings attribute directly, with a nested dict (http://docs.conan.io/en/latest/reference/conanfile.html#configuration). However, this form of configuration is a bit verbose and complex, so I am just thinking about how to improve it.

**Comment by memsharded** [comment]
Hi @Chaosteil 

Long time :) 
I am reviewing old issues. This one haven't proved to be a relevant issue. Users that don't want to support a certain setting can just raise an Exception in the ``configure()`` (old config() ) method, easier than the above:

```python
    def configure(self):
        if self.settings.compiler.libcxx == "libstdc++":
            raise Exception("This package is only compatible with libstdc++11")
```

Which seems very idiomatic. So, I think this issue could be closed, but please re-open it or comment if you have further thoughts on this. Thanks very much!

**Comment by acgetchell** [comment]
So this is kindof a pain.

Just getting started, so maybe I missed something, but I have a perfectly valid CMakeLists.txt up until I add the lines

~~~
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
~~~

After adding those lines, cmake doesn't work unless `conan install` is run first.

But `conan install` generates:

~~~
ERROR: Conanfile: 'settings.compiler.libcxx' value not defined
~~~

However, as I'm building on several platforms {macos, linux, Windows} and with several compilers {gcc, clang, MSVC}, it would be nice to have a portable way to specify this.

What am I missing?

**Comment by shelper** [comment]
i agree that this should be able to be set in `conanfile`. users dont want to see this exception and install packages with new `libstdc++11` again... 
if possible, maybe enable local profile file within the project folder, if exists, always overrides the global default profile.

**Comment by memsharded** [comment]
> i agree that this should be able to be set in conanfile. users dont want to see this exception and install packages with new libstdc++11 again...

A single package cannot change the whole dependency graph value for ``settings.compiler.libcxx``, that would be a chaos, and source of continuous conflict, with different packages setting different conflicting values (and packages with different values cannot be linked together, that produces link errors). This is the reason this is a global setting and as setting, cannot be defined or defaulted in recipes.

> if possible, maybe enable local profile file within the project folder, if exists, always overrides the global default profile.

The global default profile (auto-detected) is not recommended for production, you should be defining your own profiles and using them

**Comment by shelper** [comment]
@memsharded  why we cannot directly do: 

> ```python
>     def configure(self):
>         self.settings.compiler.libcxx=="libstdc++11"
> ```

**Comment by fsecilia** [comment]
This is [astonishing](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Users can't just install `conan` and run `conan install <path to working copy>`. I have to include special instructions for users to either edit their default profile(!) or to specify a long configuration setting. This simply doesn't work out of the box.

It's 2020. The default should be libstdc++11, or it should be easier for us to specify this in something we can commit to revision control and not burden clients.

This basically forces me to include a script clients can run to build dependencies.

**Comment by memsharded** [comment]
Hi @fsecilia 

> It's 2020. The default should be libstdc++11, or it should be easier for us to specify this in something we can commit to revision control and not burden clients.

We wish, and we will change it asap, that means in Conan 2.0. In the meantime, we are committed to stability and not breaking users: https://docs.conan.io/en/latest/introduction.html#stable, and this will be a breaking change. 

Python 2 is deprecated. I wish we could remove it, but there are still a few Conan users that depend on it. We are doing our best not to break them, as much as we can. We also support CMake down to 2.8.12. Yes, I wish everybody had upgraded to modern CMake, but not all users have done it. Sometimes, and in C and C++ we know it well, it is more important to not break users, even if it means some defaults become eventually outdated. Conan 1.0 is 2.5 years old, and even before that, that default was set like 4 years ago. It was a good default back then, and we will need to wait until next major Conan 2.0 to be able to break it.

**Comment by memsharded** [comment]
> This basically forces me to include a script clients can run to build dependencies.

In any case, the default profile is not recommended for production. Using your own profiles is the way to go. That will fix the issue.
