### ISSUE TITLE
automatically inject conan_basic_setup into CMakeLists.txt files

### ISSUE THREAD

**Issue by weatherhead99** [conan-io/conan#2177]
since it is a recurring theme in conan packages to add the minimal cmake boilerplate, an automatic method to do this might be helpful. 

I have attempted an implementation which works on all the package recipes I had handy on my system here, but is probably missing quite a few edge cases (and no tests yet):

(https://github.com/weatherhead99/conan/commit/584f3c4d9387f88e0b662b1fc6b14d44b1b0cf6b)

**Comment by lasote** [comment]
Yes, I think something like this as a `tool.xxx` could be useful.

**Comment by memsharded** [comment]
conan_basic_setup integration was superseded by transparent CMakeToolchain integration that doesn't require to modify CMakeLists.txt at all.
