### ISSUE TITLE
What's the problem with Python x64 under Windows?

### ISSUE THREAD

**Issue by mmatrosov** [conan-io/conan#2181]
As a developer, I would like to know what problems I can have when using 64-bit Python under Windows. [The documentation says](http://docs.conan.io/en/latest/installation.html#install-with-pip-recommended):

> In Windows you might need to use 32bits python distributions, instead of 64bits.

Why? What are the implications? I've been using conan within Python 3.6.3 x64 for a couple of months, and did not encounter any problem. Should I still be worried? Can I go to production with 64-bit, or I need to switch to 32-bit "just in case"?

Also, it sounds strange that 64-bit platform, which is the default choice, might have some problems.

**Comment by memsharded** [comment]
I think you are mostly good with Py3.6 x64 bits.
That note refers mostly to Py2.7, in which if I am not wrong, the 32bits is the default one when downloading python in Windows, which seems very relevant to me. We have had in the past a couple of very weird issues, without a final diagnostic, but that were solved in Py2.7 using the 32bits versions. Maybe we should change the docs and clarify it refers to Py2.7.

**Comment by mmatrosov** [comment]
> Maybe we should change the docs and clarify it refers to Py2.7
That sounds like a very good thing to do. It would definitely have helped me.

**Comment by memsharded** [comment]
And the change is live: http://docs.conan.io/en/latest/installation.html#install-with-pip-recommended

Thanks very much for the feedback! Closing the issue now, but please comment or re-open if necessary. Also, the docs leave in its own repo, if you think it is specific to docs, you can submit issues there too.
