### ISSUE TITLE
Should calling commands really be done with % operator?

### ISSUE THREAD

**Issue by lamefun** [conan-io/conan#2185]
I mean this way of calling command is used often in the documentation:

~~~
self.run('cmake %s/src %s' % (self.source_folder, cmake.command_line))
~~~

Doesn't this break down if the path contains spaces?

~~~
>>> 'cat %s' % ('Some File')
'cat Some File'
~~~

**Comment by memsharded** [comment]
You are right, it breaks if the path has spaces.
But I would say that line should be already replaced by ``cmake.configure()`` calls, I have only found them in commented code. In any case, I have added quotes to them, thanks for noticing!

**Comment by memsharded** [comment]
Also, please note that the docs are in a github repo itself: https://github.com/conan-io/docs
You can submit documentation issues there as well, or directly PR to fix or improve things. Thanks!
