### ISSUE TITLE
Supporting relative URLs between server and client

### ISSUE THREAD

**Issue by niosHD** [conan-io/conan#2186]
Hi all, this issue is intended as an RFC and possible feature request.

I have a probably very common setup where I run a `conan_server` in the private network of our CI system. For debugging purposes I wanted to connect to this `conan_server` via ssh port forwarding. However, as it turns out only operations which are handled in a single request work (e.g., `conan user`). Other operations like for example `conan install` fail miserably. It seems like the reason for that is that `conan_server` returns absolute URLs to the client in the first request which obviously can not be downloaded without proper routing.

Of course I could setup a VPN to make it work. However, I wonder if simply replacing the absolute URLs through relative ones in the response of the server and teaching the client how to handle such relative URLs would be the better solution. After all, the client simply has to prefix them with the currently used remote URL.

A quick glance at the code makes me think that the needed changes are minimal and that it possibly could even simplify the `conan_server` configuration if relative paths are used. After all, there is no need for the `host_name`, `public_port`, and `ssl_enabled` settings when no absolute URL has to be constructed.

What do you guys think. Would such a change be a good idea?

Best,
Mario

**Comment by memsharded** [comment]
Hi Mario!

I would like to comment the current solution: there are 2 endpoints in all servers, the "logic" endpoint and the "transfers" endpoint. The logic endpoint gives absolute signed URLs to the transfers endpoint when it is necessary to do some transfer. This is intended to decouple the heavy transfers from the business logic, like what we did with S3. 

Implementing that logic will couple both, in a way that is server-specific, how would the client know which is the base URL to compose the final absolute one?

Not sure what is your setup, but would it be possible to forward the ``public_port`` too? 
Thanks for your feedback!

**Comment by niosHD** [comment]
Oh, I did not thought of such a setup, thank you for pointing that out. It makes sense to use absolute URLs if the "transfer" endpoint with the data storage different than the "logic" endpoint.

However, when both endpoints are serviced by one server and port, as it is by the standard configuration of the  `conan_server` if I understood correctly, then returning relative URLs would still be possible. The idea would to simply return relative URLs from the server when the "transfer" endpoint is on the same host and port as the "logic" endpoint. When the client gets an relative URL it knows that both endpoints are identical and can construct the correct absolute URL. Otherwise, when an absolute URL is sent the client behaves like at the moment and simply use it.

Therefore, I propose that relative URLs should be supported in addition to absolute URLs between client and server. The main motivation is probably the simplification of the default server config (i.e., getting rid of `host_name`, `public_port`, and `ssl_enabled`). Simplifying my, admittedly obscure setup should be considered a side effect.

The challenge with the ssh port forwarding is not only the possibly different port but also the host_name. I can work around these problems by picking the same port locally as on the server and by tampering with the `resolv.conf`. Still, there is some room for improvement.

**Comment by lasote** [comment]
Hi @niosHD, probably it could work and make sense.

**Comment by niosHD** [comment]
I just found #1990 and think that using relative URLs by default in the server would fix this issue too.
