### ISSUE TITLE
Confusing 'test' in build logs

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2192]
Hi there, I've spotted something strange earlier, I believe this is a forgotten debug log:

```
﻿Boost/1.65.1@theo/stable test package: Requirements
Boost/1.65.1@theo/stable test package:     darwin-toolchain/10.13@theo/stable from my_server
Boost/1.65.1@theo/stable test package:     llvm/5.0@theo/stable from my_server
```

I confused it with the `test_package` step at first, and I don't think this is related to the `package` step either, since this happens before fetching the sources.

**Comment by memsharded** [comment]
Yes, it is a bit confusing. They are traces when the ``test_package`` functionality is being called, I suggest putting it in parenthesis, like:

```bash
$ conan new Hello/0.1 -s -t
$ conan create user/testing
...
Hello/0.1@user/testing: Calling package()
Hello/0.1@user/testing package(): Copied 1 '.h' files: hello.h
Hello/0.1@user/testing package(): Copied 1 '.lib' files: hello.lib
Hello/0.1@user/testing: Package '6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7' created
Hello/0.1@user/testing (test package): Generator cmake created conanbuildinfo.cmake
Hello/0.1@user/testing (test package): Generator txt created conanbuildinfo.txt
Hello/0.1@user/testing (test package): Generated conaninfo.txt
Hello/0.1@user/testing (test package): Running build()
...
```
The output seems write, those lines actually belong to the test_package functionality. Wdyt? Thanks for the feedback!

**Comment by theodelrieu** [comment]
Oh I see, I didn't think that `test_package` was called at the very beginning of `conan create`.

Parentheses make sense to me :)

**Comment by memsharded** [comment]
Yes, because when using ``test_package`` the one really installing the package is the consumer application living inside the test_package folder, to make sure it is installing exactly the same configuration that it is being tested, so it appears:

```bash
Hello/0.1@user/testing (test package): Installing C:\Users\memsharded\<projectfolder>\test_package
```
