### ISSUE TITLE
Shared library target redefined

### ISSUE THREAD

**Issue by giraldeau** [conan-io/conan#2193]
In the `package()` step, I added by mistake the same library name twice in `self.cpp_info.libs`:

```python
    def package_info(self):
        # Let's be stupid here and put the library twice
        self.cpp_info.libs = ["foo", "foo"]
```

Because of that, consuming the package with the cmake generator fails:

```
-- Library foo found /home/francisg/.conan/data/foo/2.3.4/conan/issue/package/f5a6882590d137de693642227ed35e8e26da3dac/lib/libfoo.so
-- Library foo found /home/francisg/.conan/data/foo/2.3.4/conan/issue/package/f5a6882590d137de693642227ed35e8e26da3dac/lib/libfoo.so
CMake Error at conanbuildinfo.cmake:223 (add_library):
  add_library cannot create imported target "CONAN_LIB::foo_foo" because
  another target with the same name already exists.
Call Stack (most recent call first):
  conanbuildinfo.cmake:71 (conan_package_library_targets)
  conanbuildinfo.cmake:124 (conan_define_targets)
  CMakeLists.txt:5 (conan_basic_setup)
```

It took me a while to figure that out because I was computing the library names dynamically, so we might detect this situation with some set operations:

```python
libs = ["foo", "foo", "bar", "baz"]
uniq = set()
dups = []
for lib in libs:
    if lib in uniq:
        dups.append(lib)
    else:
        uniq.add(lib)

if len(dups) > 0:
    print("Warning: duplicates found {}".format(dups)) 

# $ python3 detect_duplicated_libs.py 
# Warning: duplicates found ['foo']
```

**Comment by memsharded** [comment]
While I totally understand the issue, I would like to highlight:

- The sets operations you are suggesting (can be done in one liner too) are quite expensive. Please note that the ``package_info()`` is evaluated for every package, in every install operation, even if the packages are already installed.
- There are users with dependency graphs of a few hundreds nodes, that can have some noticeable impact.
- The error is "relatively" easy to spot, i.e. it is captured at build time, showing that there is a repetition in the package. It would be different if it caused an error more difficult to debug. But if using ``test_package`` functionality (which is totally recommended for creating packages) would be easily spotted.

So, I am balancing right now to leaving it as is, wdyt? cc/ @lasote

**Comment by giraldeau** [comment]
Yeah, I agree it's a minor issue and totally my mistake. At least it's documented if someone is having the same issue. Thanks!

**Comment by memsharded** [comment]
Thanks very much for your feedback!
