### ISSUE TITLE
Offline package install

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#2197]
Hi!

My idea is create a feature similar feature present on apt-get, where I can download a remote package as tar package and execute a standalone installation.

```
$ conan download foobar/0.1.0@user/channel --file
$ ls
    foobar_0.1.0_user_channel.tar.gz
$ conan install foobar_0.1.0_user_channel.tar.gz
  Installing foobar/0.1.0@user/channel ...
```

This feature can help in some situations where you need to work offline or distribute packages without a server.

**Comment by memsharded** [comment]
Hi!

Thanks very much for the suggestion.

Regarding the work offline, I am not sure that would be an effective way. Also, does this proposed feature gets only the package recipe, or all the binaries? I don't think getting the binaries scales at all. When in apt-get you are getting the tar package, I think it is already the right binary package for your distro, but for conan it might not be enough.

And if the package has transitive dependencies, it will fail anyway when you go offline. Should you retrieve the transitive dependencies manually?

> distribute packages without a server

You mean, distributing them with a USB stick? Just kidding :D 
You always have a server, if you want to distribute package recipes, you can easily do a snapshot of the package recipe repo. Even github has it, so you can directly do a download of a github release, unzip, and ``conan create`` to install it and build the binaries. Am I missing something? Cheers!

**Comment by uilianries** [comment]
Hi!

Thanks for your quick answer!

Recipes are easy to distribute, so my point is about binary packages.

When I say working offline, it means, work without a Conan server to distribute binary packages. This situation could be by an infrastructure limitation. I know that a border case, but could happen. In the worst case we could distribute by a USB stick :P 

Solve transitive dependencies it's a pain, but there is an option to solve all by a new argument. For example, all dependencies can be downloaded together.

```
$ conan download foobar/0.1.0@user/channel --file --transitive
$ ls
    foobar_0.1.0_user_channel.tar.gz zlib_1.2.11_conan_stable.tar.gz

$ conan install --file zlib_1.2.11_conan_stable.tar.gz
  Installing zlib/1.2.11@conan/stable ...
$ conan install --file foobar_0.1.0_user_channel.tar.gz
  Installing foobar/0.1.0@user/channel ...
```

In this example foobar/0.1.0 depends zlib/1.2.11. So, zlib is downloaded as transitive option.

Again, this feature looks like a border case and could be used few times. But it's an option to solve offline cases, where a server is not possible to run.

Regards!

**Comment by memsharded** [comment]
But I still don't get it. So you are suggesting that:
```
$ conan download foobar/0.1.0@user/channel --file --transitive
```
Will download a .tgz with ALL binaries that are available in the remote, for all configurations? That can easily take *lots* of space.

Also, what happens to conditional requirements? You have to evaluate ``foobar`` for all possible configurations and dependency graphs to check which are the transitive dependencies? Doesn't seem feasible.

**Comment by uilianries** [comment]
My original problem is distribute binary packages for offline machines, including ALL binaries. However, as I said this is an edge-case and demands a considered effort to develop a similar feature from APT download.

So, @memsharded gave me the follow suggestion:

> For your "offline" deploys, I think I have a reasonable workflow that can work off-the-self
> 1. set CONAN_USER_HOME=my_folder
> 2. conan install whatever with whatever profile
> 3. If something was built, run  conan remove -b -s
> 4. Just zip the CONAN_USER_HOME/data folder. It will have all transitive dependencies
> 5. Unzip in your target system, and point to it

IMHO this is better than develop a new feature to solve a very specific case. Also, this approach is easy to maintain and update when necessary.

Thanks for your support! Cheers!
