### ISSUE TITLE
[Feature request] Multiplatform system package managers interface

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#22]
Installing 3rd party software in a distro-agnostic way is a pain, since each distro has its own package manager and naming conventions.

For my own dotfiles repo I wrote a cli tool that provides a portable interface to the system package manager, via `install_package` and `update_system` commands. The thing works by having a database that maps a generic package name (Say libclang) and a distro name (Say ubuntu/debian) to the specific package name the distro uses. Using that database, you only write `install_package libclang` in your install scripts, the tool manages to call the correct package manager with the correct package name. See https://github.com/Manu343726/dotfiles#package-management

What I propose is to add such a system to conan, so installing system components would not be a pain.

The first issue that comes to my mind is the mapping database, how it should be stored, updated, shared between users, etc.

**Comment by lasote** [comment]
Yes, we have multiple TO-DOS according to installing system packages. But we want to reduce the installing of system packages. Usually only needed for building tools and toooooo much core libraries, so it would not be too much important feature, at least by now.

**Comment by Manu343726** [comment]
Actually this issue is not really a request for you but a way to talk about this problem, and a reminder for me, since I want to implement it :)

**Comment by memsharded** [comment]
I really like this proposal. Something that is able to install dev-tools as CMake, clang, etc even with given versions, in a portable fashion would be amazing. It would need to run on windows too, not sure about shell be the best approach, I'd prefer python for this tool. How would you address portability to win?

**Comment by Manu343726** [comment]
Maybe chocolatey is an option

**Comment by memsharded** [comment]
I mean, there should be a high-level logic that translates the dev-tool to install to specific OS install commands, might be choco, apt-get or any other. Such high-level tool should be portable, and shell scripting is not, so the entry point to this interface should probably be python, do you agree? What would be your approach?

**Comment by Manu343726** [comment]
My idea is to write a mapping database system in python, similar to what I described above. My only concern is how to manage that database. It should be shared between conan users? It's local to the user installed conan client?

**Comment by memsharded** [comment]
I'd say a database is not a good idea, difficult to synchronize. From my point of view the options are:
- Host the database as a json file or similar in a repo, so it is easy to upgrade, collaborate, etc.
- Host it in a service, that can be managed via api. I like this idea, but it is more work, to develop and to maintain.

I'd go for the first one initially and see how it evolves.

**Comment by memsharded** [comment]
Conan got a ``SystemPackageTool`` that can be used for installing system packages, and so far seems a good enough solution. Please check : http://conanio.readthedocs.io/en/latest/reference/conanfile.html#system-requirements

I still think that a general common interface to system package managers, with a mapping for popular OSS projects, would be a useful utility. But so far the current solution seems enough, so I think this issue can be closed, just open a new one for the ``SystemPackageTool`` if necessary. Thanks!
