### ISSUE TITLE
There needs to be an unmoderated repository or an easy way to find packages

### ISSUE THREAD

**Issue by lamefun** [conan-io/conan#2200]
This has already been discussed in issue #1676 and the poster closed it:

> Searching from Bintray's main search box allows users to search ALL public repositories on bintray. This includes conan repositories, and every other kind of repository. This satisfies my request.

I can't find such a search box now, it so must be gone now. Together with the fact that conan-center only has 21 approved packages, it creates a situation that makes it seem that Conan has been abandoned by the community. I myself looked at the repositories and thought that Conan is abandoned before I accidentally stumbled upon the bincrafters repository.

**Comment by lamefun** [comment]
I've registered on Bintray and can use search now. The search box is not actually gone, but registration is required to use it and it's never told anywhere that it even exists until you register.

**Comment by memsharded** [comment]
Implemented in https://conan.io/center/ long time ago
