### ISSUE TITLE
Bintray usability issues

### ISSUE THREAD

**Issue by lamefun** [conan-io/conan#2212]
- The global search is only available after registration, with no indication that it exists at all until you register.

- The global search does not have an option to limit it to Conan packages only.

- The per-repository search returns incorrect results sometimes (tested on Firefox on Ubuntu and Fedora), you have to re-select the ordering to make it work.

**Comment by simonblee** [comment]
I second this. I've had a very bad experience overall trying to find packages as the website is very confusing. Almost every other package manager's website is significantly easier to use.

**Comment by memsharded** [comment]
Thanks very much for the feedback. We are aware of these limitations, and it is in our roadmap to improve this. But bintray serves billions of downloads per month, it is not simple to do changes, so it will take some time. This is why this issue still hasn't been asigned to one of our next releases. As soon as we have progress here we will report. Cheers!

**Comment by memsharded** [comment]
Bintray is being sunset https://blog.conan.io/2021/02/05/JFrog-announces-sunset-bintray.html

https://conan.io/center/ ConanCenter is the public community central repository.
