### ISSUE TITLE
Conan new CI templates define VS150COMNTOOLS

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2215]
Maybe it is not necessary anymore.

**Comment by lasote** [comment]
It is not.

**Comment by lasote** [comment]
Why did you open this issue? Have you tried it?

**Comment by memsharded** [comment]
I am saying that the template of ``conan new -ciw`` generates a script with this variable:

```
VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
```

This might be removed.

**Comment by lasote** [comment]
Yes, it should. Add it to the beta 3
