### ISSUE TITLE
Fill shared option using same value

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#2218]
Hi!

I would like to be able to set `shared` option for all transitive dependencies, based on my shared option.

I tried two pieces:

The problem here is that `deps_cpp_info` is filled after to load all my requirements. To late to be useful.
```python
def configure(self):
    for dep in self.deps_cpp_info.deps:
        self.options[dep].shared = self.options.shared
```

Here I'm just be able to retrieve my local requirements. Transitive won't be solved.
```python
def configure(self):
    for name, _ in self.requires.iteritems():
        self.options[name].shared = self.options.shared
```

I know about custom option `*:shared=[True|False]`. However, my intention is set the `shared` default option using the same value for all requirements, but the user should be able to override argument `-o`.

Is there some smart piece of code to solve this? Regards!

**Comment by memsharded** [comment]
I don't think right now it is possible.

The first observation is right, ``deps_cpp_info`` is filled after the full dependency graph has been computed. Changing options changes the depedency graph, so it is a chicken-and-egg problem that cannot be solved.

So the ``configure`` doesn't know the full dependency graph yet. I wonder if patterns apply, have you tried ``self.options["*"].shared = self.options.shared``?

**Comment by uilianries** [comment]
Thanks!

The follow statement works:
```python
def configure(self):
    self.options["*"].shared = self.options.shared
```

Also, when I set some specific shared option by `-o`, the value is overridden by my argument.

Regards!

**Comment by memsharded** [comment]
Excellent :)
