### ISSUE TITLE
[question] Forward options to upstream packages automatically

### ISSUE THREAD

**Issue by hamparawa** [conan-io/conan#2222]
Hi,
I have a set of packages that are dependent on each other and some other third party packages such as Boost.

In my package recipes, I have an option `BuildASAN`, `BuildTSAN` which enables the sanitizers for the package. When the flag is set, I would like to use sanitizer enabled upstream packages as well. This means I have to forward current package options to upstream packages in the configuration step.

So instead of using this,
`conan install .. -opackageA:BuildTSAN=True -opackageB:BuildTSAN=True`

I'd like to use,
`conan install .. -oBuildTSAN=True`

And all supported packages are built with Thread Sanitizer enabled.

Here is my current approach using reflection,
```python
class MyRecipe(ConanFile):
    name = "packageC"
    version = "0.1"
    options = {"BuildASAN": [True, False], "BuildTSAN":[True, False]}
    default_options = ("BuildASAN=False", "BuildTSAN=False"}
    requires = "packageA/0.1@demo/testing", "packageB/0.1@demo/testing", 
                      "boost/1.66.0@thirdparty/stable"

    def configure(self):
        # Propagate options to non thirdparty packages.
        for requires in self.requires.iteritems():
            for entry in self.default_options:
                key = entry.split("=")[0]
                value = getattr(self.options, key)
                if '@thirdparty/' not in str(requires[1]):
                    setattr(self.options[requires[0]], key, value)
```

However, I am having few issues with this approach.

* There is no way to obtain the supported options in a specific package in `configure()` time. I've tried using `hasattr()` followed by `setattr()` combo, but `hasattr()` always return true for me, but `setattr()` fails when the upstream recipe does not have the option defined.
* As a workaround, I have restricted these into a specific user, and moved the unsupported packages to 'thirdparty' user. 

Is there some other builtin way to handle this? Any advice would be helpful.
Thanks,

I'm using Conan version 0.30.3

**Comment by mpdelbuono** [comment]
Does `-o *:BuildTSAN=True` meet your needs? Or am I misunderstanding your question?

**Comment by hamparawa** [comment]
When the wildcard is used, what would be the behavior when a certain package does not have that option defined? If it does not raise an error, I think my problem is solved. Thanks!

**Comment by hamparawa** [comment]
Looks like conan does not give an error when a recipe does not have the option defined and a wildcard (*) is used. So instead of bulk of code above, I can get it working with simply providing `-o *:BuildTSAN=True` in the command line.  😄 Thanks for the tip! 

On a side note : I think it would be better to warn output when a option pattern does not have a match in a recipe. For example, I have tried `-o*:ASDASDASDASD=True` which is  a bogus pattern and conan did not complain and ignored the option.
This would be mostly helpful in detecting typos in recipes much quicker. 

Thanks again!

**Comment by memsharded** [comment]
I think this question is solved, and improvements can be followed in the #2227 PR, so this might be closed, thanks!
