### ISSUE TITLE
Too much restriction on new arch_target setting

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2229]
Hi,

I've looked at the new `settings.yml`, and I think the default `arch_target` should contain much more values. At least as much as `arch`.

I don't know if `arch_build` should contain something else, the defaults look good to me.

**Comment by memsharded** [comment]
Yes, make sense.

**Comment by lasote** [comment]
Totally agree. I added all the os's but I forgot to complete the archs.
