### ISSUE TITLE
Strange issue after 0.8.5 upgrade

### ISSUE THREAD

**Issue by nathanaeljones** [conan-io/conan#223]
I upgraded to 0.8.5 locally and ran into a strange thing with compiler.version

~/.conan/conan.conf and build/conaninfo.txt both specify "5.3", but `conan build` produces

> CMake Error at build/conanbuildinfo.cmake:233 (message):
>   Incorrect 'gcc' version 'compiler.version=4.8' is not the one detected by
>   CMake: 'GNU=5.3'

The only reference to 4.8 I can find is in build/CMakeCache.txt
CONAN_COMPILER_VERSION:UNINITIALIZED=4.8

I deleted and re-created the build folder after upgrading to 0.8.5.

mkdir -p build
cd build
conan install --file ../conanfile.py -o build_tests=True --build missing -u
conan build --file ../conanfile.py

Here's the strange thing. 

Run from ~/Documents/imageflow, `conan build` produces the compiler version warning.

from ~/Documents/imageflow/build, `conan build --file ../conanfile.py`  produces a different error:

> /usr/bin/ld: /home/n/.conan/data/libjpeg-turbo/1.4.2/lasote/stable/package/1825751e274ec825270a47a80ec47dbf8278fa20/lib/libjpeg.a(jcmarker.o): unrecognized relocation (0x2a) in section `.text'
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> make[2]: **\* [libimageflow.so] Error 1
> make[1]: **\* [CMakeFiles/imageflow.dir/all] Error 2
> make: **\* [all] Error 2

My system was different in that /usr/bin/gcc and /usr/bin/g++ are 4.8, but the env vars CXX and CC are bound to /usr/bin/gcc-5 and /usr/bin/g++-5, which everything seems to support pretty well. 

```
sudo rm /usr/bin/gcc
sudo rm /usr/bin/g++

sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
sudo ln -s /usr/bin/g++-5 /usr/bin/g++

```

After remapping gcc and g++, I deleted build and re-installed, yet still the issue persists. Where can it be getting this compiler version value? The shell I'm executing reports 5.3 for gcc -v and g++ -v and $CC -v and $CXX -v

```
CMake Error at build/conanbuildinfo.cmake:233 (message):
  Incorrect 'gcc' version 'compiler.version=4.8' is not the one detected by
  CMake: 'GNU=5.3
```

**Comment by nathanaeljones** [comment]
Deleting conanbuildinfo.cmake and conaninfo.txt from the ~/Documents/imageflow folder fixed it. I didn't realize the build wasn't self-contained in ./build, and had to grep the folder to figure out where the setting was. The compiler.version error is now gone, but the link error remains.

**Comment by nathanaeljones** [comment]
Reverting to 0.8.4 didn't fix the problem, so there must be some other kind of state problem causing the link failures.

```
sudo pip uninstall conan
sudo pip install 'conan==0.8.4'
```

**Comment by nathanaeljones** [comment]
Are there any other places that Conan stores configuration? Can't seem to get my Ubuntu 14.04 box working again.

```
sudo pip uninstall conan
rm -rf ~/.conan
sudo pip install conan
mkdir new_folder
cd new_folder
git clone git@github.com:imazen/imageflow.git
cd imageflow
.travis/run_tests.sh

```

> 
> [ 56%] Linking C shared library libimageflow.so
> /usr/bin/ld: /home/n/.conan/data/littlecms/2.7/lasote/stable/package/1825751e274ec825270a47a80ec47dbf8278fa20/lib/liblcms2.a(cmserr.o): unrecognized relocation (0x2a) in section `.text'
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [libimageflow.so] Error 1
> make[1]: *** [CMakeFiles/imageflow.dir/all] Error 2
> make: *** [all] Error 2
>

**Comment by nathanaeljones** [comment]
Perhaps I wasn't actually using GCC 5.3 before upgrading to 0.8.5, Rolling back to GCC 4.8 permitted me to build as follows.
```
sudo rm /usr/bin/gcc
sudo rm /usr/bin/g++

sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
#edit ~/.bashrc and change $CPP and $CC to /usr/bin/gcc /usr/bin/g++
#Kill and reopen all shell sessions
sudo pip uninstall conan
rm -rf ~/.conan
sudo pip install conan
mkdir new_folder
cd new_folder
git clone git@github.com:imazen/imageflow.git
cd imageflow
.travis/run_tests.sh
```

**Comment by lasote** [comment]
About the mismatch compiler version, if you change the compiler you need to perform a conan install command to rewrite the conanbuildinfo.txt file. Maybe the confusion was to have two conanbuildinfo.txt files, maybe for installing from two different directories. 

About the linker issues, I'll try it hard. 
You have ubuntu 14 with gcc 5.3 installed from where? additional repository?

**Comment by lasote** [comment]
Hi again, I reproduced the error installing 5.3 in a clean ubuntu 14. I'll keep investigating if it's a bad package.

**Comment by lasote** [comment]
Are you sure you was able to compile imageflow with gcc 5.3 in your ubuntu 14 machine in the past? It seems there is some glibc incompatibilities or something like that.

**Comment by nathanaeljones** [comment]
I thought I was, but I'm no longer sure. It's possible that it was being overridden at some point in the process. 5.3 builds on travis, though!

**Comment by lasote** [comment]
Yes, the thing is, is not the same the travis 5.3 than yours. You are using an old ubuntu version with a gcc compiler. We already detected that libc++ (not the case) and glibc versions are kept although you install a new gcc version. The problem is, a package built with a 5.3 in a new ubuntu may be incompatible with a project with a 5.3 in the old ubuntu. In addition to this, the current problem with your library is about the binutils (linker, assembler etc) . In newer versions they use some symbols for reallocation that older versions can't understand. And this is the linker complain about.
These kind of problems will ever happen, we recommend to build from sources when the configuration is not the expected. A better behavior would be that conan could advise you of the old ubuntu distribution and suggest a recompilation with --build parameter  (just the first time, then you would have all the packages ready for your project). We are analyzing the possibilities, we should handle this things with a setting, but the introduction of a new setting could makethe things too complex.
The problem about --build, I tried with your project and your ubuntu and gcc 5.3 and it fails building openssl, don't know why yet. I have to investigate it. Please keep working with 4.8 and let travis show you if there is any problem with gcc 5.3.

**Comment by nathanaeljones** [comment]
For sure; it's no problem to keep using 4.8 until the next Ubuntu LTS
release happens in a couple months :)
On Apr 4, 2016 12:55 AM, "Luis" <notifications@github.com> wrote:

Yes, the thing is, is not the same the travis 5.3 than yours. You are using
an old ubuntu version with a gcc compiler. We already detected that libc++
(not the case) and glibc versions are kept although you install a new gcc
version. The problem is, a package built with a 5.3 in a new ubuntu may be
incompatible with a project with a 5.3 in the old ubuntu. In addition to
this, the current problem with your library is about the binutils (linker,
assembler etc) . In newer versions they use some symbols for reallocation
that older versions can't understand. And this is the linker complain about.
These kind of problems will ever happen, we recommend to build from sources
when the configuration is not the expected. A better behavior would be that
conan could advise you of the old ubuntu distribution and suggest a
recompilation with --build parameter (just the first time, then you would
have all the packages ready for your project). We are analyzing the
possibilities, we should handle this things with a setting, but the
introduction of a new setting could makethe things too complex.
The problem about --build, I tried with your project and your ubuntu and
gcc 5.3 and it fails building openssl, don't know why yet. I have to
investigate it. Please keep working with 4.8 and let travis show you if
there is any problem with gcc 5.3.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/conan-io/conan/issues/223#issuecomment-205161947>

**Comment by memsharded** [comment]
What is the status of this issue? The 0.8.5 release was months ago. Any specific action required or could this issue be closed? Thanks

**Comment by memsharded** [comment]
Seems this is not an issue anymore, so this can be closed, please reopen if necessary. Thanks!

**Comment by lasote** [comment]
As we talked in slack, generating the packages with the docker gcc 6.3 image and consuming from trusty can be problematic because of the different standard library. I think that running the consumer also in docker will fix it.
