### ISSUE TITLE
Wrong package recipe reference names on JFrog Artifactory remote

### ISSUE THREAD

**Issue by bilke** [conan-io/conan#2240]
Conan version: 1.0.0-beta.3
Conan remote: JFrog Artifactory, url: `https://ogs.jfrog.io/ogs/api/conan/conan`

Steps to reproduce:

```bash
$ conan remote add repo https://ogs.jfrog.io/ogs/api/conan/conan
$ conan search * -r repo
Existing package recipes:

1.3.0/bilke@Shapelib/stable
1.4.2/bilke@libgeotiff/stable
```

You can clearly see the recipe naming is wrong. When I search on e.g. conan-community (at `https://api.bintray.com/conan/conan-community/conan`) it is correct:

```bash
$ conan search * -r conan-community
Existing package recipes:

7z_installer/1.0@conan/stable
Boost/1.64.0@conan/stable
```

Maybe the implementation of the Conan repo on Artifactory changed somehow? I am on [Artifactory version 5.6.3](https://ogs.jfrog.io/ogs/api/system). Shall I fill a bug report on Artifactory?

**Comment by memsharded** [comment]
Indeed can be reproduced.
With local Artifactory 5.5.1 it works well. It might be only a failure of the online/saas Artifactory, not the normal one. Let me investigate, ask. Thanks for raising this issue!

**Comment by memsharded** [comment]
Verified with latest Artifactory 5.8.0, still working good, so it doesn't seem a failure of Artifactory, but of the SaaS version.

**Comment by bilke** [comment]
@memsharded Thanks for testing! Shall I fill a bug report on Artifactory?

**Comment by lasote** [comment]
Did you upload the packages using Conan, right? 
We talked with Artifactory people, from Artifactory 5.6.0 they changed the directory layout to ``user/name/version/channel``.
If we understand it well, two things could happen, or the migration failed, or you uploaded the contents manually.

**Comment by memsharded** [comment]
Or maybe the packages were uploaded some months ago. Could you try to
re-upload some of them and see what happens?

**Comment by lasote** [comment]
@memsharded the Artifactory 5.6 came with a migration, if the packages were already there they should have changed the layout.

**Comment by bilke** [comment]
Uploading a package again seems to resolve the issue:

```
$ conan upload VTK/7.1.0@bilke/stable --all
...
$ conan search * -r repo
...
7.1.0/bilke@VTK/stable
...
VTK/7.1.0@bilke/stable
```

**Comment by memsharded** [comment]
So we have been investigating and it seems the issue could be a failed migration, but we cannot find further data. We keep investigating, but probably the best workaround is then to re-upload all your packages and remove the old ones.

**Comment by bilke** [comment]
I have re-uploaded all packages and removed the old ones, thanks for your help!

**Comment by memsharded** [comment]
Thanks very much to you for your collaboration!
