### ISSUE TITLE
Platform dependent "requires"

### ISSUE THREAD

**Issue by grafandreas** [conan-io/conan#2241]
Dear conan-Team,

we have been setting up some projects with conan and so far I am impressed. However, there is one question that we cannot find adressed in the docs. Is there a possibility to specify "requires" based on the platform? We would consume different conan packages in one project for windows or for Linux. 

The idea was to use something like

class ShowcaseConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    if self.settings.os == "Windows":
        requires = "TensorFlow/1.4.0@demo/testing", "OpenCV/3.1.0@lasote/vcpkg"
    else:
        requires = "TensorFlow/1.4.0@demo/testing", "OpenCV/3.2.0/xmar/stable"

But of course "self" is not available  / initialized at this time.

Thanks!

**Comment by memsharded** [comment]
Many thanks!  :) 

yes, it is possible, use the ``requirements()`` method for logic:

```python
class ShowcaseConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    def requirements(self):
        if self.settings.os == "Windows":
              self.requires("TensorFlow/1.4.0@demo/testing")
              self.requires("OpenCV/3.1.0@lasote/vcpkg")
        else:
            ...
```

**Comment by lasote** [comment]
Hi @grafandreas! many thanks :). 
I'm closing the issue, but please, feel free to write again if there is any other question.
