### ISSUE TITLE
Option scoping broken in export_pkg api

### ISSUE THREAD

**Issue by mmakowskidotnet** [conan-io/conan#2242]
(Thank you for creating conan, it's a fantastic tool with even better support)

I noticed that after some refactoring to option scoping, this call might have been missed:

https://github.com/conan-io/conan/blob/bac730f9636012b4bc485159c9a68c117a89bba3/conans/client/manager.py#L168

With the code the way it is, I'm seeing errors such as:

`conans.errors.ConanException: 'options.someOptionName' doesn't exist
Possible options are []`

I modified the above line to account for the added param and things work as expected when using the API:

`        conanfile = loader.load_virtual([reference], True, None)`

**Comment by memsharded** [comment]
> (Thank you for creating conan, it's a fantastic tool with even better support)

Hi @mmakowskidotnet, thanks very much :)

Regarding your issue, could you please elaborate a bit further so we can reproduce. It is better if you can attach a conanfile.py and tell which commands raise the issue. If using directly the code, then some more context (also the conanfile.py), and how you are invoking it. Cheers!

**Comment by mmakowskidotnet** [comment]
It's entirely possible I'm abusing the flow of conan, so feel free to tell me that :) 

I'm trying to emulate a workspace-based conan workflow. By workspace, I mean I want to be able to 'check out' multiple packages to my workspace and work on them simultaneously, rebuilding and exporting them to a local conan cache (each workspace has its own cache). I run conan's export, source, build, and export_pkg to update the artifacts in my workspace's local cache.

As an example, suppose I have two dependent packages, A and B, where B depends on A. If I wanted to re-work the interface between the packages, I would check them both out into a workspace. Once I changed the interface in A, I would run 'export', 'install', 'source', 'build', and then 'export_pkg' on A to get the updated definitions into my local cache. Then I would do the same in B in my workspace to verify they can work together. This is similar to the 'create' command, but that command clobbers the build directory on each run, which is not desirable for me.

The smallest reproducible example I managed to come up with shows up when using 'install' and 'export_pkg' on the same package:

```python
#!/usr/bin/env python

from conans.client.conan_api import Conan
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--path")
    parser.add_argument("--build-path")
    parser.add_argument("--name")
    parser.add_argument("--version")
    parser.add_argument("--user")
    parser.add_argument("--channel")

    args = parser.parse_args()

    if not args.path:
        raise Exception("'path' missing")
    if not args.build_path:
        raise Exception("'build-path' missing")
    if not args.name:
        raise Exception("'path' missing")
    if not args.version:
        raise Exception("'version' missing")
    if not args.user:
        raise Exception("'user' missing")
    if not args.channel:
        raise Exception("'path' missing")

    print("path={}".format(args.path))
    print("build-path={}".format(args.build_path))
    print("name={}".format(args.name))
    print("version={}".format(args.version))
    print("user={}".format(args.user))
    print("channel={}".format(args.channel))

    conan, _, _ = Conan.factory()
    conan.install(path=args.path, install_folder=args.build_path)

    conan.export_pkg(path=args.path, cwd=args.path,
                     name=args.name, user=args.user, channel=args.channel,
                     install_folder=args.build_path,
                     force=True)
```

With this conanfile.py:

```python
from conans import ConanFile

class HelloPythonConan(ConanFile):
    name = "HelloPython"
    version = "0.1"
    exports = '*'
    build_policy = "missing"
    options = { "optionOne": [True, False], "optionTwo": ["Value1", "Value2"] }
    default_options = "optionOne=True", "optionTwo=Value1"

    def package(self):
        self.copy('*.py')

    def package_info(self):
        self.env_info.PYTHONPATH.append(self.package_folder)
```

The output I get from this is:

```
$ ./test_app/test_app.py --path ~/scratch/2018-01-02/hello_python --name HelloPython --version 0.1 --user user --channel channel --build-path /tmp/build-path
path=/Users/maciem/scratch/2018-01-02/hello_python
build-path=/tmp/build-path
name=HelloPython
version=0.1
user=user
channel=channel
PROJECT: Installing /Users/maciem/scratch/2018-01-02/hello_python/conanfile.py
Requirements
Packages

PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
WARN: Conanfile doesn't have 'url'.
It is recommended to add it as attribute
WARN: Conanfile doesn't have 'license'.
It is recommended to add it as attribute
WARN: Conanfile doesn't have 'description'.
It is recommended to add it as attribute
HelloPython/0.1@user/channel: The stored package has not changed
Traceback (most recent call last):
  File "./test_app/test_app.py", line 43, in <module>
    force=True)
  File "/Users/maciem/scratch/2018-01-02/test_app/conans/client/conan_api.py", line 63, in wrapper
    return f(*args, **kwargs)
  File "/Users/maciem/scratch/2018-01-02/test_app/conans/client/conan_api.py", line 341, in export_pkg
    install_folder=install_folder, profile=profile, force=force)
  File "/Users/maciem/scratch/2018-01-02/test_app/conans/client/manager.py", line 170, in export_pkg
    conanfile = loader.load_virtual([reference], None)
  File "/Users/maciem/scratch/2018-01-02/test_app/conans/client/loader.py", line 134, in load_virtual
    conanfile.options.initialize_upstream(self._user_options)
  File "/Users/maciem/scratch/2018-01-02/test_app/conans/model/options.py", line 532, in initialize_upstream
    self._package_options.values = user_values._package_values
  File "/Users/maciem/scratch/2018-01-02/test_app/conans/model/options.py", line 389, in __setattr__
    return super(PackageOptions, self).__setattr__(field, value)
  File "/Users/maciem/scratch/2018-01-02/test_app/conans/model/options.py", line 417, in values
    self._check_field(name)
  File "/Users/maciem/scratch/2018-01-02/test_app/conans/model/options.py", line 375, in _check_field
    raise ConanException(option_not_exist_msg(field, list(self._data.keys())))
conans.errors.ConanException: 'options.optionOne' doesn't exist
Possible options are []
```

I suspect that the install command is populating the 'options' in an info file, which is then picked up by export_pkg. I saw that there were some refactoring done to the scoped options, so I looked at the code and it seems like the call to load_virtual:
```python
        conanfile = loader.load_virtual([reference], None)
```
is missing an arg:
```python
def load_virtual(self, references, scope_options=True,
                     build_requires_options=None):
```

If I modify the call to pass in 'True' for scope_options and keep the 'None' for build_requires_options, everything works as expected. The workflow below worked in 0.29 and I just upgraded to the beta3 rc, when things stopped working for me. What do you think?

**Comment by memsharded** [comment]
Thanks so much for the detailed information. It was really helpful, and indeed you are right, I was able to reproduce the behavior in tests, and your fix seems ok!

So I have submitted https://github.com/conan-io/conan/pull/2246, for inclusion in 1.0.0-beta.4, which might be released tomorrow. Thanks again!

**Comment by memsharded** [comment]
> It's entirely possible I'm abusing the flow of conan, so feel free to tell me that :)

Nop, you are not abusing conan, in fact this flow is something that should be better documented in the docs (we are working on it), and maybe further automated in the "conan-project" feature (being under constant consideration since some time ago: https://github.com/conan-io/conan/issues/1377).
Please let us know how your flow works once it matures, and if you think there is something that conan could further automate. Thanks!

**Comment by mmakowskidotnet** [comment]
Absolutely, I'll be sure to share my experience once things are moving. Thanks for the fix, I confirm it solves my problem.

**Comment by memsharded** [comment]
Thanks for checking! I am leaving the issue open (labeled as fixed), until it is actually released.

**Comment by mmakowskidotnet** [comment]
Gotcha, I'll keep that in mind.

**Comment by memsharded** [comment]
Released :)
``$ pip install conan==1.0.0b4 --upgrade``
