### ISSUE TITLE
`conan info` and `conan create` create recipes in cache before verifying they exist

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#2243]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 0.30.3

Due to a bug in my conanfile.py, I accidentally specified a requirement of Foo/0.1.x instead of Foo/[0.1.x] (i.e., I accidentally specified a literal version "0.1.x" instead of specifying a search for a version matching that range).

I ran `conan info` to test my file. Conan obviously presented me with an error saying it couldn't find v0.1.x, but only after it created the 0.1.x folder in the cache. A subsequent `conan search Foo/*` finds that version 0.1.x as existing.

This wouldn't be a big deal, as conan correctly reports that it can't find version 0.1.x, but _**after correcting my conanfile.py**_, we run into a new problem. "Foo/[0.1.x]" matches the incorrectly created version "Foo/0.1.x" in the cache. So what I end up with on a subsequent invocation is something like this:

> D:\Foo>conan info
> Version range '0.1.x' required by 'None' resolved to 'Foo/0.1.x@autobuilder/conan'
> Foo/0.1.x@autobuilder/conan: Not found in local cache, looking in remotes...
> Foo/0.1.x@autobuilder/conan: Trying with 'artifactory'...
> ERROR: Unable to find 'Foo/0.1.x@autobuilder/conan' in remotes
>
> D:\Foo>conan search Foo/*
>Existing package recipes:
>
>Foo/0.1.x@autobuilder/conan
>Foo/0.1.0@autobuilder/conan

Note that at this point, there is nothing wrong with the conanfile.py; the problem is that the conan cache has an invalid entry in it that should never have been created. If that entry were never created, the file would pick up 0.1.0 and work as expected.

I think conan should only be creating these cache entries after it determines that the version actually exists. Otherwise, the cache can get polluted with invalid entries and the errors you get from the scenario are misleading.

**Comment by memsharded** [comment]
Thanks for reporting. This is indeed an error that I have been able to reproduce.
It is due to the locks files being stored in the package recipe folders, so the search thinks there is a package there. I am trying a fix, will try to submit it for the beta 1.0.

**Comment by memsharded** [comment]
Please try now with beta4:
``$ pip install conan==1.0.0b4 --upgrade``
