### ISSUE TITLE
conan install: missing environment variables

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2254]
Hi, I have an issue reproducible with 0.30.3 and 1.0.0-beta3.

I'm setting `CONAN_USERNAME` in my profile, but running `conan install ..` gives the following error:

```
ConanException: CONAN_USERNAME environment variable not defined, but self.user is used in conanfile
```

Exporting this variable in my .zshrc fixes the issue, but I'd rather not have to patch all my teammates' configuration files.

**Comment by memsharded** [comment]
Thanks for reporting this. Can you please share the conanfile you are using for the ``conan install ..``? Thanks!
