### ISSUE TITLE
[bug] conan download does not fetch package recepie

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#2261]
Tested using conan 0.30.3.
Using ```conan download -r foo MyPackage/1.2@user/channel``` does not fetch package recepie, when there is no binary packages available on remote. Output of the command:

```
Getting the complete package list from 'MyPackage/1.2@user/channel'...
MyPackage/1.2@user/channel: WARN: No remote binary packages found in remote
```

**Comment by memsharded** [comment]
Yes, this is a bug. Funny thing is that it has been long time there, undetected. We migth try to add it to conan 1.0.0-beta.5, but if not possible, it might not be that critical. You can workaround it and download just the recipe with a ``conan info MyPackage/1.2@user/channel``. It will bring transitive dependencies recipes too, but that doesn't harm

Many thanks for reporting!

**Comment by memsharded** [comment]
Released in beta 5. Please try:

```bash
$ pip install conan==1.0.0b5
```
Thanks!
