### ISSUE TITLE
[bug] conan does not copy conanfile in build folder

### ISSUE THREAD

**Issue by virgile-thermo** [conan-io/conan#2270]
To help us debug your issue please explain:

- [x ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan 0.30.1
visual studio 2012
windows 7

The conanfile.py is not copied from export_source folder to build folder, so when we do a CMake which call conan the process failed.

Is it documented, is et a regression, have you got a workaround?

Best regards.

Virgile

**Comment by memsharded** [comment]
Hi Virgile,

No, I don't think it is a regression. I guess you might be using cmake-conan to call conan from cmake. This is nice for end-users who want conan to be called automatically from cmake. But I don't think it is a good idea to do that while creating packages. Note that you will have conan that launches cmake to build the package, and you want it in turn to launch conan again?

Could you please link a reproducible example, with a conanfile.py, build files, etc? A repository would be the best. Thanks!

**Comment by chuet-thermo** [comment]
Hi,

(I am a colleague of Virgile)
We are having this issue when trying to upgrade from conan 0.25.1, which did copy the `conanfile.py` from the source folder (e.g. git checkout) to the conan build folder (i.e. `$CONAN_DATA_HOME/conan/[package]/[version]/[user]/[channel]/build/[sha]/).

When we try and upgrade to 0.30, this conanfile.py is not copied, which points to a behavior change in conan.

For more context, our package `A` depends upon multiple conan prepack, and is consumed as a conan prepack by our project 'B'. Thus in its CMake-based buildsystem it calls conan via the conan.cmake script.

How should we proceed to build the package if the conan.cmake is not to be called in this scenario ?  (which in 0.25 works fine)

**Comment by memsharded** [comment]
Hi!

Yes, that is indeed possible, conan 0.25 was released 6 months ago, which is a lot of time considering that conan is in beta and releasing monthly, with important changes. Having a conanfile.py in the build folder is unnecessary, so it is not copied. The whole folder addressing mechanism has changed, and the usage of ``self.source_folder``, ``self.build_folder`` etc is now defined. Things as ``conanfile_directory`` have been removed.

When you are in conan, the dependencies are already retrieved by conan, so calling conan again from within cmake with cmake.conan is not only redundant, but also entering a dangerours recursion.

I would recommend doing a check, if the package is being created in the local cache, you can check:

```cmake
if(CONAN_EXPORTED)
     include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
     conan_basic_setup( ...)
else()
     # conan.cmake stuff
endif()
```

If something, this could be a possible improvement of the cmake-conan tool. In any case, it is strongly discourage that package creation will fire cmake-conan tool.

**Comment by chuet-thermo** [comment]
this only seems to work if the generator is `cmake` and not `cmake_multi`, as it only generates a `conanbuildinfo_{config}.cmake` and not the other (i.e. `conanbuildinfo_debug.cmake` and not `conanbuildinfo_release.cmake`) which causes issues when including `conanbuildinfo_multi.cmake`.

Meaning we have to use multi-configuration packages to have this working properly.


I understand that this is a best practice, but having this much to change is quite a bit of work.

**Comment by memsharded** [comment]
The important thing, besides the generator is what is the kind of your packages. Are you generating multi-config packages (with both debug and release artifacts in the same binary package, removing the ``build_type`` setting), or single-config packages (one package for debug, another for release, keeping ``build_type`` setting?

You don't need to use multi-configuration packages, and we don't suggest it as best practice, actually the default are single-configuration packages. ``cmake_multi`` should be used just for end-consumers, not for package creation. Just use the ``cmake`` generator for creating packages in the local cache, and the ``cmake_multi`` for developers to work locally.

**Comment by DoDoENT** [comment]
I've got a similar problem. I've got a repository which, during the build, creates some tools that are then used to produce some resource files. However, when cross-compiling, those tools cannot be used on the host system. Therefore, my CMake script creates another CMake build directory for the host, within its own build directory and invokes CMake in it. This "slave" CMake process then calls `conan install` to install required dependencies for the host system in order to build the tools, which are exported with CMake's `export` command. Those tools are then imported as CMake imported executable targets and can be used during the cross-building.

However, when creating Conan package for the non-host system, the lack of having `conanfile.py` copied to `source` folder, causes failure to install Conan dependencies for host tools and thus package building fails.

Note that, unlike previously mentioned example, this recursion is not _dangerous_ - it is _required_. I suggest adding boolean attribute `copy_conanfile_to_source` that will be set to `False` by default and after setting it to `True`, it will ensure `conanfile.py` gets copied to the source folder when package creator knows what it is doing.

Alternatively, if there are better ways to solve the described problem, I am all ears. But please keep in mind that creating a separate package for the resource building tool is not an option for my use case, as this tool is specific to my repository and cannot be used in other contexts.

**Comment by DoDoENT** [comment]
My current workaround is to have a separate package that contains only the resources and which is built on the host system, but its `package_id` is tweaked to target all platforms, compilers, architectures and build types. Its only dependency is the original package.

However, this solution has its downsides - the `build_requires` in this resource-only package must be manually kept in sync with both `requires` and `build_requires` of the original package. Additionally, since Conan workspaces do not allow the batch creation of packages, the channel of the dependency of the resource-only package must be manually set to the channel in which the CI server will build the original package.

This works, but I would prefer avoiding this hacky solution.

**Comment by DoDoENT** [comment]
> In the meantime, I am reading @DoDoENT your feedback, but failing to understand the whole setup. 

It's a closed source company project, but I'll try to give as much info as needed to understand the setup:

- CMake project contains the following targets:
    - MyLibrary target - a static library target. For sake of example, let's say that it depends on MyOtherLibrary, which is also a static library, imported via Conan dependency.
    - MyLibraryTest target - an executable target that depends on MyLibrary and on GTest via Conan dependency. It also depends on MyResourceBuild target, which is explained below.
    - MyResourceBuilder target - an executable target that depends on MyLibrary target and on MyResourceDependency target, which is also a static library, imported via Conan dependency
    - MyResourceBuild target - a CMake custom target, which uses MyResourceBuilder executable to build some resource files. Those resource files are required for both MyLibraryTest executable and should be packaged into final Conan package for MyLibrary.
- CMake project uses [cmake-conan](https://github.com/conan-io/cmake-conan) to automatically install dependencies. Of course, it takes into account [special case for creating packages](https://github.com/conan-io/cmake-conan#creating-packages).
- when compiling on the host system, all those targets can be successfully built without any problems
- when cross-compiling, the problem arises with MyResourceBuild target, as it wants to execute MyResourceBuilder, which is not built for the host platform. To circumvent that, the CMake script that defines the MyResourceBuild target creates a host CMake build directory in which the MyResourceBuilder target will be built and imported as an IMPORTED target (I'll show the CMake code later). This host build directory does not observe `CONAN_EXPORTED` variable, and it shouldn't as it needs to install dependencies for the host system.

Using the above described example, here is how the `conanfile.py` should look like:

```python
from conans import python_requires

base = python_requires('MyBaseConanfile/1.0.2@user/stable')

class MyLibraryConan(base.MyBaseConanfile):
    name = "MyLibrary"
    version = "0.1.0"
    requires = 'MyOtherLibrary/1.3.2@user/stable'
    build_requires = 'GTest/1.8.0@user/stable', 'MyResourceDependency/1.3.2@user/stable'

    # build has been defined in base conanfile

    def package(self):
        super(MyLibraryConan, self).package()
        # also package resources
        self.copy('res_output/*.bin', dst='res')

    def package_info(self):
        # always call super
        super(MyLibraryConan, self).package_info()
        self.cpp_info.libs = ["MyLibrary"]
```

The CMake script should look like something like this:

```cmake
cmake_minimum_required(VERSION 3.10)

if( CONAN_EXPORTED )
    include( ${CMAKE_CURRENT_BINARY_DIR}/conanbuildinfo.cmake )
    conan_basic_setup( TARGETS )
else()
    if( NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake" )
       message( STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan" )
       file( DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v0.12/conan.cmake" "${CMAKE_BINARY_DIR}/conan.cmake" )
    endif()
    include( ${CMAKE_BINARY_DIR}/conan.cmake )
    conan_cmake_run( CONANFILE conanfile.py BASIC_SETUP CMAKE_TARGETS BUILD missing )
endif()

# helper macro for creating tool executable
macro( build_tool_exe exename )
    if( NOT CMAKE_CROSSCOMPILING )
        add_executable( ${exename} ${ARGN} )
        # Export executable so it can be used by cross-platform build directory
        export( TARGETS ${exename} APPEND FILE ${CMAKE_BINARY_DIR}/executables.cmake )
        if( NOT TARGET build_tools )
            add_custom_target( build_tools DEPENDS ${exename} )
        else()
            add_dependencies( build_tools ${exename} )
        endif()
    endif()
endmacro()

# helper macro for creating host build dir when cross-compiling
macro( create_host_build_dir )
    if ( CMAKE_CROSSCOMPILING AND NOT TARGET built_host_tools )
        set( HOST_BINARY_DIR ${CMAKE_BINARY_DIR}/host-build )
        # create host binary dir
        file( MAKE_DIRECTORY ${HOST_BINARY_DIR} )
        execute_process(
            COMMAND
                "${CMAKE_COMMAND}"
                -G "${CMAKE_GENERATOR}"
                "${CMAKE_CURRENT_SOURCE_DIR}"
            WORKING_DIRECTORY
                "${HOST_BINARY_DIR}"
          )
          message( "Importing targets from ${HOST_BINARY_DIR}/executables.cmake" )
          include( ${HOST_BINARY_DIR}/executables.cmake )
          add_custom_target( build_host_tools 
              COMMAND
                  "${CMAKE_COMMAND}" --build "${HOST_BINARY_DIR}" --config $<CONFIG> --target build_tools
           )
          # some generator-specific tweaks have been ommited for brevity
    endif()
endmacro()

# now the actual definitions of targets

# MyLibrary
add_library( MyLibrary STATIC ${MY_LIBRARY_SOURCES} )
target_link_libraries( MyLibrary PUBLIC CONAN_PKG::MyOtherLibrary )

# MyResouceBuilder
build_tool_exe( MyResouceBuilder ${MY_BUILDER_SOURCES} )

# if cross-compiling, import MyResourceBuilder from host build directory, as above macro
# will be no-op
if( CMAKE_CROSSCOMPILING )
    create_host_build_dir()
endif()

# MyResourceBuild
add_custom_target( MyResourceBuild ALL COMMAND MyResourceBuilder --output=${CMAKE_CURRENT_BINARY_DIR}/res_output )

# MyLibraryTest
add_executable( MyLibraryTest ${MY_TEST_SOURCES} )
target_link_libraries( MyLibraryTest PRIVATE MyLibrary CONAN_PKG::GTest )
add_dependencies( MyLibraryTest MyResourceBuild )
```

I hope this explains what I am trying to achieve.

**Comment by DoDoENT** [comment]
Now, `conan create` works flawlessly, but for example `conan create -pr ios` fails during creation of host build folder because `conan_cmake_run` fails there as `conanfile.py` is missing in source directory.

**Comment by DoDoENT** [comment]
As I said earlier, my current workaround is to have another `conanfile` for creating resource-only package, however it needs to be in sync with original conanfile.

For reference, here are both `conanfiles` from my workaround with comments on what I don't like about it:

_conanfile.py_:

```python
from conans import python_requires

base = python_requires('MyBaseConanfile/1.0.2@user/stable')

class MyLibraryConan(base.MyBaseConanfile):
    name = "MyLibrary"
    version = "0.1.0"
    requires = 'MyOtherLibrary/1.3.2@user/stable'
    build_requires = 'GTest/1.8.0@user/stable', 'MyResourceDependency/1.3.2@user/stable'

    # build and package have been defined in base conanfile

    def package_info(self):
        # always call super
        super(MyLibraryConan, self).package_info()
        self.cpp_info.libs = ["MyLibrary"]
```

_conanfile-resources.py_:

```python
from conans import python_requires

base = python_requires('MyBaseConanfile/1.0.2@user/stable')

class MyLibraryResourcesConan(base.MyBaseConanfile):
    name = "MyLibraryResources"
    version = "0.1.0"
    requires = 'MyLibrary/0.1.0@user/stable' # this needs to be in sync with conanfile.py
    build_requires = 'GTest/1.8.0@user/stable', 'MyResourceDependency/1.3.2@user/stable',  'MyOtherLibrary/1.3.2@user/stable' # this also needs to be in sync with conanfile.py

    # build has been defined in base conanfile

    def package(self):
        # package only resources, ignore libraries
        self.copy('res_output/*.bin', dst='res')

    # no package_info, but package_id must be defined

    def package_id(self):
        del self.info.settings.os
        del self.info.settings.build_type
        del self.info.settings.arch
        del self.info.settings.compiler
```

And I've setup my CI to build the `conanfile-resources.py` only on host systems, while building the `conanfile.py` for all platforms I need. Also, users will need to specify `MyLibraryResources` in their `requires` expression, which is not very nice.

**Comment by memsharded** [comment]
This issue is outdated.

Conan stablished the following behavior some time ago:
- conanfile.py file is not copied to the ``self.build_folder`` or ``self.source_folder``.
- Exclusively the ``exports_sources`` are copied to the source and build folders. Everything in the ``export`` is not copied
- For access to the ``export`` folder, the ``self.recipe_folder`` can be used, also accessible from ``self.dependencies``
