### ISSUE TITLE
[question] is it possible to implement generator that generates more than one file

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#2278]
As far as I am concerned, generator contains two property methods that needs to be implemented.

    @property
    def filename(self):

    @property
    def content(self):

How can I generate more than one file?

**Comment by memsharded** [comment]
Yes, you have to return ``None`` in the ``filename`` method, then return a dict ``{filename: filecontent}`` in the ``content()`` method.

Likely the interface is not the best one, but did this way for backwards compatibility.

**Comment by memsharded** [comment]
Please consider closing the issue if the answer was valid and it is working fine. Thanks!

**Comment by omicronns** [comment]
Works like a charm, thanks!
