### ISSUE TITLE
[question] where to add conditional generators

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#2282]
I would like do do something like this:

    def build_requirements(self):
        if self.develop:
            self.build_requires('generator-xxx/0.1.0@user/channel')
            self.generators += ('xxx',)

Where should I append to generators attribute if I want to use some generator conditionally. Is ```build_requirements``` method a good place to do it?

**Comment by memsharded** [comment]
Yes, that is a good place. Generators are called after installation of package dependencies, (after ``conan install`` for end user, or before calling a package ``build()`` while creating the package). So you cannot add it in build or post-build methods, like source(), build(), package(), package_info(). But ``build_requirements()`` is called before package build (it needs the build requires to build), so I find very consistent adding ot om the same place you are conditionally depending on the package the implements it. You can also do ``self.generators.append("xxx")``

**Comment by omicronns** [comment]
Thank you!
