### ISSUE TITLE
How to resume a fail build?

### ISSUE THREAD

**Issue by mp3butcher** [conan-io/conan#2284]
Hi, sorry by advance if i misread doc
 I try to create a conan recipe for a huge library from sources and have space problem (incremental build+multithread makes VStempdir exploid) on C:\ so the build may take multiple calls to nmake(through cmake) in order to be build completely.
Is there a way the resume package creation without purging work already done?

i know the -k for create option to avoid gitcloning sources but is there the same for install to prevent copy sources to buildcache and restart the whole building process?.

any help would help?

**Comment by memsharded** [comment]
Yes, I think you want to debug your package recipe locally first before using ``conan create``. 

We are adding new docs for the 1.0 release of tomorrow, but you might be interested in the blog post: https://bincrafters.github.io/2017/11/10/Updated-Conan-Package-Flow/ that explains the local development flow

Please have a look and try, and tell me if it helps. Thanks!

**Comment by mp3butcher** [comment]
thanks for your reactivity

**Comment by mp3butcher** [comment]
okay i think i begin to understand a bit better

**Comment by memsharded** [comment]
That is irrespective of some open feature request to implement equivalent functionality to the ``--keep-source`` but for the build. It is more challenging to implement, so it can take time. 

Do not hesitate to ask any further question. Cheers!
