### ISSUE TITLE
Clang via Visual Studio results in error

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#2285]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 0.30.3

When using the `compiler` to `Visual Studio` and `compiler.toolset` setting set to `LLVM-vs2014` (and possibly others), the CMake generator's generated file creates an error condition:

```
-- Selecting Windows SDK version 10.0.15063.0 to target Windows 6.1.7601.
-- The C compiler identification is Clang 5.0.1
-- The CXX compiler identification is Clang 5.0.1
-- Check for working C compiler: C:/Program Files/LLVM/msbuild-bin/cl.exe
-- Check for working C compiler: C:/Program Files/LLVM/msbuild-bin/cl.exe -- works
...
-- Conan: called by CMake conan helper
CMake Error at D:/conan-cache/.../conanbuildinfo.cmake:416 (message):
  Incorrect 'Visual Studio', is not the one detected by CMake: 'Clang'
Call Stack (most recent call first):
  D:/conan-cache/.../conanbuildinfo.cmake:115 (conan_check_compiler)
  CMakeLists.txt:6 (conan_basic_setup)
```

Since this compiler.toolset option is present in the default settings.yml, I presume this is supposed to work. My guess at the right way to approach this is to teach the CMake generator about compiler.toolset, which it is currently blissfully ignorant of. The downside is that it also means teaching the generator about this setup (and would potentially not work for custom toolsets).

**Comment by memsharded** [comment]
Actually, the CMake is passing the ``-T`` option, and it is being used, but it is the check in the ``conanbuildinfo.cmake`` that detects that the compiler being used is Clang, and not Visual Studio.

Certainly the support for Clang in Windows has to be improved.

Maybe @SSE4 can help further, has expertise in it.

**Comment by mpdelbuono** [comment]
Yeah, sorry if I wasn't clear - I recognize that the problem is in the generation of the conanbuildinfo.cmake, not in CMake itself (which is passing the correct -T option). I think I see the problem in the generator and have a patch, but I need to test it a little bit first; assuming it's good I'll submit a pull request.

**Comment by memsharded** [comment]
I think this issue was closed by https://github.com/conan-io/conan/pull/2287, and already released, please check.

**Comment by mpdelbuono** [comment]
Sorry for the delay, but I just confirmed that this works. In fact, I confirmed it very hard because apparently an upgrade to Visual Studio caused my LLVM install to break, and conan was correctly detecting that it was falling back to the MSVC compiler instead of using LLVM like it should.

Thanks,
