### ISSUE TITLE
ConanFile.copy in package() fails sometime with extension less files?

### ISSUE THREAD

**Issue by mp3butcher** [conan-io/conan#2292]
I tried to debug why I had missing includes in my package and deployement (i debug only using deploy as it's more convenient)
And see that calling 
`self.copy('*',include,include)`
misses 90% of my headers
calling `conan install XXX@demo/testing` (to call deploy) gives me
`@demo/testing package(): Copied 70 '' files`
where there near 600 extension less headers
Any idea why? it seams to be a bug...

**Comment by memsharded** [comment]
Hello!

When you submitted the issue there were some items to check. One of them is to provide reproducible steps for the issue. WIthout them it is very difficult to check and fix things.

Could you please provide us with a repository, a conanfile.py, and the necessary steps to reproduce such issue? Thanks!

**Comment by mp3butcher** [comment]
In fact the issue seams to be in my build method...
I haven't understand that during package copy work on build file and in deploy it works on package files

**Comment by mp3butcher** [comment]
`conan package --source-folder H:\.conan\n8sx1id7\1 --build-folder H:\.conan\qckit5h_\1  --package-folder H:\.conan\31rij6d0\1 OpenSceneGraph`

fails as descibed
