### ISSUE TITLE
Mismatch between conanfile.txt and conanfile.py 'imports' behavior

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#2293]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Tested on the following:
- Conan v1.0.0 release
- Conan v0.30.3
- Current 'develop' branch

I'm not sure if this is intentional or not, but conanfile.txt and conanfile.py behave a little differently when running imports. Consider the following two files, where the Core package has the following directory structure:
- bin\
  - a.dll
  - Foo\
    - b.dll

**conanfile.txt**
```
[requires]
Core/0.1.0@autobuilder/conan

[imports]
bin, *.dll ->  @ excludes="Foo/*.dll"
```

**conanfile.py**
```py
from conans import ConanFile

class Stuff(ConanFile):
    requires = "Core/0.1.0@autobuilder/conan"
    def imports(self):
        self.copy('*.dll', '', 'bin', excludes='Foo/*.dll')
```

In the case of conanfile.txt, Foo\b.dll is copied, but in the case of conanfile.py, Foo\b.dll is not copied.

Is this discrepancy intentional? If so, is it possible to exclude an entire folder? I have not identified a pattern that can exclude a folder with conanfile.txt.

**Comment by mpdelbuono** [comment]
Note: all testing was on Windows 7. I haven't had the opportunity to test other OSes.

**Comment by memsharded** [comment]
No, not intentional, could be a bug. Is it basically that the ``excludes`` in conanfile.txt is not being managed correctly, right?

**Comment by memsharded** [comment]
Got it :) Thanks for your detailed report, it is a pleasure to investigate these things with so good issues details.

You shouldn't quote the exclude string in conanfile.txt:

```
[imports]
bin, *.dll ->  @ excludes=Foo/*.dll
```
As you can see all strings are not quoted in the conanfile.txt. It was trying to exclude ``"Foo/*.dll"``

Maybe the parser could try to unquote strings, not sure about the implications, but could be too much just to prevent this.

**Comment by mpdelbuono** [comment]
Ah! Ok that will explain it.

The documentation at http://docs.conan.io/en/latest/reference/conanfile_txt.html#imports includes the quotes, so they should probably be removed, unless I'm misunderstanding something still.

**Comment by memsharded** [comment]
Good point. Though then the case for multiple patterns have to be checked. I will add some tests when possible, thanks for pointing it.

**Comment by memsharded** [comment]
It was an error in the docs, I have fixed it: https://github.com/conan-io/docs/commit/2bbf54e5450817e7c00646e4793854fd980d56ab

I have also added a test, just in case in #2296. Many thanks!
