### ISSUE TITLE
Download command switch to just download the recipe.

### ISSUE THREAD

**Issue by luckielordie** [conan-io/conan#2295]
Hi guys, congrats on getting 1.0 out!

I think it might be useful to add a command switch for the download command to only download the conanfile.py. 
I have a use case where I need to re-host some packages locally on our own conan_server, when I do a search and download using conan it downloads all of the package folders for a package. To save on time and bandwidth it would be useful to just download the recipe and build the packages our devs will use ourselves.

**Comment by memsharded** [comment]
Thank you! :)

Have you tried the ``conan info`` command? That downloads the recipes only, not the binaries.

The main difference with ``conan download`` is that it retrieves also the transitive dependencies, but that shouldn't be an issue in practice.

**Comment by danimtb** [comment]
You can also try with `$ conan get` and redirect command output to file:

```
$ conan get zlib/1.2.11@conan/stable -r conan-center > conanfile.py
```

Then you can export (or create with the desired settings) and upload to your remote:

```
$ conan export . conan/stable
$ conan upload zlib/1.2.11@conan/stable -r my_remote

**Comment by luckielordie** [comment]
Thankyou both for the suggestions! @memsharded I'm going to go with your method. It didn't seem clear to me that the info command would actually download into my local_cache. Maybe that's me misunderstanding Conan a little. But maybe it would be worth pointing it out in the command line description?

**Comment by memsharded** [comment]
It is not in the docs, because actually it is mostly a workaround.
It is possible that the most intuitive approach would be the one that you are suggesting, using a switch to specify it in the ``download`` command. Lets propose it.
