### ISSUE TITLE
Automate backup to any another git web service

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [conan-io/conan#2297]
Hello,

As you know GitHub sometimes shutdowns. Will be nice, if we will have another mirror of Conan repo (e.g. on BitBucket).

**Comment by memsharded** [comment]
Yes, today was one of the days! :(

Anyone aware of some integration/add-on that automates this?

**Comment by Croydon** [comment]
https://docs.gitlab.com/ee/workflow/repository_mirroring.html#pulling-from-a-remote-repository

**Comment by memsharded** [comment]
Unfortunately this seems to be for the Enterprise Edition

**Comment by Croydon** [comment]
The free and public gitlab.com hosting runs the EE, therefore you can use it :)

**Comment by memsharded** [comment]
I have been discussing with the maintainers, and it seems a bit overkill, at least at this moment. Another service to track. Github has some downtime, but it is really something exceptional and not that disruptive. Any of the maintainers have complained. While having a mirror means that some people might try to do PR, submit issues in gitlab, etc. Or if we close everything (is it even possible, to lock issues and PRs in gitlab for a repo?) and it is read-only, then, it won't be much better than just your local clone.

So lets keep at the moment the github repo only, if it gets worse, we will revisit again this issue. Thanks very much for the feedback!
