### ISSUE TITLE
Allow developers to package without the whole recipe

### ISSUE THREAD

**Issue by Israphel** [conan-io/conan#2298]
Hello, allow me to explain a situation that we're currently facing.

I created recipes for some projects (libraries and executables) and I did them following the documentation, so by themselves they get the code, configure the dependencies, build the code (with cmake) and then create a package. All of that is going great.

The problem came up when the developers wanted to jump into the Conan train. They didn't want to use the recipe for their workflow (cloning, building). So I decided to add a conanfile.txt to each repo, so they could get the dependencies and build however they want.

But then another issue appeared: they wanted to send their results to conan local cache, so they need the package() function that it's in the recipe, not the txt. And the recipes I created originally are meant to be standalone, respecting a folder structure and such (which is fine for me).

As a solution I added a "partial" conanfile.py to each repo with only the package() function, so they can call export-pkg and send the result to their local cache. The problem that appear with this is that if they run conan install and there's a conanfile.py there, it's going to summon that one, so they have to use the -f parameter to conan install.
Also the export-pkg doesn't allow you to specify a different name, only conanfile.py, which might be confusing.

What should I do to not interfere with developer's workflow?

Add the contents of the TXT file to my "partial" recipe? This will solve the "-f" issue but I'll have to maintain the complete recipe and the partial one.

any other way to send a package to the local cache without the recipe? Thanks for your time.

**Comment by memsharded** [comment]
Hi Cristian!

I don't fully understand why you need to add the conanfile.txt. You can perfectly use the conanfile.py just for installing dependencies with ``conan install`` and do not use any of the other commands. The user shouldn't note the difference between a conanfile.py and a conanfile.txt. 

Also, with conan 1.0, the UI has changed, now commands are more intuitive, like ``$ conan install conanfile.txt`` and ``$ conan install myconanfile.py``.

As an idea, I have succesfully achieved to read a text file from the conanfile.py to define the requirements, in just a few lines of python in the conanfile.py, so this is doable.

But overall, I think this conversation could benefit from some discussion, feel free to write us, or ping us in our slack channel (check https://conan.io) Thanks!

**Comment by Israphel** [comment]
Hi! I'm talking with Diego on Slack, trying to explain him better this problem. Maybe with the new conan changes I can come up with a solution. Thanks!

About my problem of having a conanfile.txt, is that from what I saw, you don't store the conanfile.py alongside the code, because the source() part won't work. I'm ok with that but the devs want to clone by themselves. But once the recipe is in artifactory, the source() part is useful. It is a mess.

Anyway I'll be in slack

**Comment by lasote** [comment]
Did you solve your doubts by slack? Could this be closed or still missing info/features? Thanks

**Comment by memsharded** [comment]
I think this question was addressed, if not, please comment, reopen the issue or open a new one. Thanks!
