### ISSUE TITLE
Setting arch_build doesn't have enough values

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2299]
Right now it only has ``x86, x86_64``

As pointed out by @DavidZemon in https://github.com/conan-io/docs/issues/441#issuecomment-356989723, it seems that conan won't work in other platforms with these default settings. Lets say if you want to run conan on a R-PI.

**Comment by chris-se** [comment]
I've stumbled over the same issue trying to run conan on a Jetson-TX2 (which is arm64). While I'm more interested in cross-compiling for that platform in the long term, the board is actually quite fast and native builds can be useful.

I believe that in principle any platform in conan's supported platform list should also be available as a possible build platform. Maybe with the exception of embedded systems where a compiler doesn't run. (But many things that are considered somewhat "embedded", such as the RPi, do run compilers.)

I'd be willing to help out with adjusting the architecture detection function to make it properly detect at least arm64 on Linux. (That's what I can test.)

**Comment by memsharded** [comment]
Actually @chris-se @DavidZemon, we have just released a patch: http://docs.conan.io/en/latest/changelog.html#january-2018

``arch_build`` shouldn't be used in all packages, just dev-tools or ``build-requires``. Please read the changelog note. We have also changed the documentation, and we will keep improving the documentation to fix this.

We are also planning improvements with the valuable feedback of @chris-se in the other issue, as well as many other feedback, but this will probably take some more time. Thanks!
