### ISSUE TITLE
Using find_package with Conan

### ISSUE THREAD

**Issue by leugenea** [conan-io/conan#2303]
Hello.

I'm trying to create universal build recipe for OpenCV (3.3.1).
For Linux everything works just find. But for windows I have some problems with cmake_multi generator.
OpenCV for Windows supports release and debug builds in one directory (debug with suffix "d").
My approach for this:
1) Make package respect multi-configuration: `cmake.is_multi_configuration: …` (inside `build`) and build two configuration inside one build.
2) Set `self.info.settings.build_type = "ANY"` (inside `package_id`)
3) In `package_info` properly set `self.cpp_info.debug.libs` and `self.cpp_info.release.libs`.

With package like this if I call `conan create . demo/testing`, everything working as I expect.
But if want to use OpenCV in project, I have to run (according to docs) `conan install -g cmake_multi -s build_type=Release` and `conan install -g cmake_multi -s build_type=Debug`. After this I'll get two identical packages (with release and debug), that's obviously not what I've wanted. What my solution would be?

And finally about find_package. If I set configuration (on Linux, for example), there will be CMake variable `CONAN_OPENCV_ROOT`, it'll be added to `CMAKE_PREFIX_PATH` and `CMAKE_MODULE_PATH` variables, so I can find OpenCV using `find_package(OpenCV)`. But in case of multi-configuration, it'll be variables `CONAN_OPENCV_ROOT_RELEASE` and `CONAN_OPENCV_ROOT_DEBUG` (and no `CONAN_OPENCV_ROOT`, and it makes sense) and neither of them is added to `CMAKE_PREFIX_PATH` or `CMAKE_MODULE_PATH` (it added to these variables only if build type is set). In my case looks like I can use any of roots to set ENV{OpenCV_DIR} to it's value, but is there any other variants of doing this?

Conan version is 1.0.0, MSVC 2017 (last update), Windows 10.

**Comment by lasote** [comment]
About the first part, if you have in the same package release and debug libraries you don't need to use the `cmake_multi` approach, the regular `cmake` generator should work. Where did you read about the `cmake_multi` in this case? In your case, you will have only 1 package for both debug/release and generated in only one build invocation as you well described.

About the find_package, I think there is no a good solution for that.
I would recommend a different package approach, write a build_id() method in the recipe so you can generate 2 different packages also for windows but building once. It's easier for the consumers: http://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-build-n-packages

**Comment by leugenea** [comment]
1) Here is told that for VS I should use cmake_multi generator: http://docs.conan.io/en/latest/integrations/cmake/cmake_multi_generator.html . As it says, "end consumers with heavy usage of the IDE, might want a multi-configuration build", and that's my case.

2) The problem with this solution is that I cannot run `find_package(OpenCV)` twice (for release and debug) for multi-configuration projects. I have to run it once and it will be either release, or debug. So it must be the same package, I suppose.
Thank you for `build_id()` idea so I won't build package twice.
