### ISSUE TITLE
Dependency node-semver 0.3.0 drops Python 2.x support

### ISSUE THREAD

**Issue by tivek** [conan-io/conan#2307]
node-semver version 0.3.0 is out and officially drops Python 2.x support: https://github.com/podhmo/python-semver/blob/0.3.0/CHANGES.txt
For now it seems 0.3.0 still runs ok on Python 2.7, but it is not guaranteed to stay like that.

Conan 1.0.1 runs ok with node-semver 0.3.0 on Python 3.6.4 and I am packaging it patched for Arch Linux.

On the one hand, I understand there are Conan users with different configurations requiring Python 2 support. On the other hand, more and more libraries are deprecating Python 2 support which [will not be maintained past 2020](https://www.python.org/dev/peps/pep-0373/) anyway. This seems like a good time for Conan to draft up a roadmap going from Python 2 to 3.

**Comment by lasote** [comment]
Thanks for the info! Unfortunately we cannot draft such a roadmap thinking about 2020. We will keep supporting both py2 and py3 thinking more in the user's usage of python than the library support unless it becomes unmaintainable. If the support of py2 is not guaranteed by node-semver probably we shouldn't upgrade to it right now, we cannot just drop the py2 support.

**Comment by tivek** [comment]
That is of course reasonable. My plan with Conan on Arch is to patch and test it for fresh system packages as Py3-only libraries trickle in. Will keep you posted.

**Comment by memsharded** [comment]
Closing this as inactive and old.

Conan 2.0 has finally dropped the node-semver dependency. Conan 1.X has also already dropped py27 support
