### ISSUE TITLE
How to fix wrong packaged binaries?

### ISSUE THREAD

**Issue by mmatrosov** [conan-io/conan#2312]
Imagine I create a recipe for jsoncpp/1.7.2. I've built several packages for it and uploaded them to Artifactory. Some users have installed some packages. Then I realised I've made one of the following mistakes:
1. Recipe has minor problems, e.g. link to the sources is missing
2. Recipe has major problems, e.g. sources of different version are used, or wrong runtime library is specified for MSVC build
3. Recipe is ok, but I supplied binaries manually (I'm wrapping existing binaries built some time ago) and did a mistake. Now some packages contain wrong binaries.

What do I do in all these situations? I will try to write I would do based on my current understanding, please correct me if I am missing something:

1. Update the recipe to fix the problem. Do not do anything on side of consumers, since binaries won't change. Package_id will be the same for all packages in the recipe. 
2. Update the recipe to fix the problem. Update packages and upload new binaries. Contact consumers and ask them to clear the cache, so they can install new packages. This does not sound very convenient, any other possibilities? I cannot change the version, since jsoncpp version itself did not change, it is still 1.7.2. Overwriting binaries is dangerous though, since it breaks repeatability of the builds. I would like to change "package revision" as suggested in #798, but there is no such thing, as long as I am aware.
3. Basically the same as in 2, but don't need to update the recipe.

I am mostly interested in a "usual" workflow for a set of dynamic libraries, which depend on each other.

**Comment by lasote** [comment]
About 2) The customers can use the `--update` option in the install to retrieve the latest overwritten packages, it is not needed to clear the local cache.
Also, you could use the "conan alias" feature: you can distribute the alias reference and then overwrite the alias with a different reference, but the customers will need to update too.

But if you don't want to keep the same reference, other users are using different approaches to achieve the "package revisions", like using the channel to version the package itself.

**Comment by memsharded** [comment]
Closing this question as inactive
