### ISSUE TITLE
Gentoo support / overly strict python dependencies 

### ISSUE THREAD

**Issue by bschindler** [conan-io/conan#2318]
Hey

I was just made aware, that conan was masked (=not installable by default unless overridden) on gentoo because of two reasons: 

- the maintainer of the gentoo ebuild left the team
- the dependencies conan specify seem to be very strict and prevent gentoo from axing old versions of python packages
(- it seems, there is some dislike for "homemade" package managers)

see here: https://bugs.gentoo.org/643152

I'lll attempt at updating the ebuild to 1.0.1 and update the list of dependencies but it seems that some of the deps they are complaining about are not solved.

My motivation is primarily to make you aware of the situation and naturally I hope the gentoo devs wishes can be at least in part satisfied

**Comment by tivek** [comment]
I have a similar problem with the Arch Linux AUR package. It was suggested by users to remove the upper limit on dependency versions, so I am now doing that. Pros: smooth system updates. Cons: possible Conan breakage if an updated dependency changes behavior.

For now I am relying on users to report any bugs and keeping an eye on updates. I also have a fork of Conan with relaxed dependency versions so that I can test it on Travis and AppVeyor: https://github.com/tivek/conan/tree/archlinux_reqs

**Comment by memsharded** [comment]
Confirming some of the points in the bug report:
- we are not aware of any revdeps, it is possible that someone might try to attempt to build a porcelain layer over it, but so far we don't know of any such initiative
- please share your findings, if there is something that can be improved without affecting the larger conan community in other OSs/distros, we will try to help

Thanks!

**Comment by bschindler** [comment]
@tivek thanks for jumping in. In the gentoo ebuilds, the upper limits were not at all specified which made me worried actually. The = dependencies were however exactly reflected and they seem to be an issue in particular. I suppose we could join force somehow as it seems we are facing exactly the same issue? 

What conan could do to help out here is to have an indication on why upper limits are specified and why some dependencies have a fixed version required which helps doing a quicker decision on whether an update should be attempted.

**Comment by tivek** [comment]
@bschindler it would be great to tackle together the matters of packaging.

Specific version limits were previously discussed in #1245.

In practice, allowing Conan to use newer versions of dependencies would not have caused any breakage in the last year or so. For a rolling release distro, it seems to be an acceptable tradeoff. Downside: the need for a significantly more complicated test matrix that tests older dependency versions to try to accomodate stable distros or older installs.

**Comment by memsharded** [comment]
> What conan could do to help out here is to have an indication on why upper limits are specified and why some dependencies have a fixed version required

In general, if some dependency is pinned it is because at some point upgrading them was breaking conan or with high risk of breaking conan, like the node-semver issue (deprecating py2, while conan still has to support py2). Of course, they can be reviewed and relaxed if everything is ok and doesn't break now.

**Comment by windelbouwmanbosch** [comment]
I am trying to build a conda-forge package out of conan, and am facing some similar issues. Mainly the amount of dependencies seems large. Are all dependencies still needed, or can they be reduced?

**Comment by memsharded** [comment]
Yes, they are all in use, 12 direct dependencies for client, as Astroid is actually indirect), 2 for server, +4 in the case of OSX for ssl thingies.

**Comment by windelbouwmanbosch** [comment]
I have a suggestion: Change the dependency on node-semver into a dependency on semantic_version. The latter package is also used already a lot: https://libraries.io/pypi/semantic_version Would this be possible?

**Comment by windelbouwmanbosch** [comment]
@memsharded Why is **distro** a dependency? I cannot find any reference in the conan sourcecode.

**Comment by memsharded** [comment]
Yes, it is used: conans/client/tools/oss.py. It is used in the conan ``OSInfo`` helper.

**Comment by windelbouwmanbosch** [comment]
Hmm, weird if I search in github this hit does not show up. But as I see it, it is only required for linux, so when packaging conan for windows, this dependency is not required.

**Comment by windelbouwmanbosch** [comment]
FYI, I'm working on this package: https://github.com/conda-forge/staged-recipes/pull/4820 . @memsharded may I add you as a maintainer as well?

**Comment by memsharded** [comment]
> Hmm, weird if I search in github this hit does not show up. 

Yes, github search has some limitations, I guess

> But as I see it, it is only required for linux, so when packaging conan for windows, this dependency is not required.

Yes, it might not be used in Windows, either OSX or other OSs, but so far it hasn't been reported any issue, is there something failing in your case?

> FYI, I'm working on this package: conda-forge/staged-recipes#4820 . @memsharded may I add you as a maintainer as well?

My duties as maintainer are already like 200% :). I am glad to collaborate, but I am not sure I will be very useful as maintainer there. So up to you.

**Comment by windelbouwmanbosch** [comment]
Okay. I will add you as a maintainer, then you at least have access rights. But I will handle new pull requests.

**Comment by memsharded** [comment]
Closing this ticket as outdated.
We have worked to reduce the number of external dependencies, and also to improve the possible version ranges when it makes sense.
