### ISSUE TITLE
can't upload?

### ISSUE THREAD

**Issue by rhl-** [conan-io/conan#232]
$ conan upload metis/5.1.0@rhl/testing --all -r=conan.io
ERROR: There is no local conanfile exported as metis/5.1.0@rhl/testing

not sure what I am supposed to do..

**Comment by memsharded** [comment]
Hi @rhl,
Not sure what could be happening.
Just to make sure, it is supposed that you have previously exported your package recipe, something as (from the folder where you have your conanfile.py):

```bash
$ conan export rhl/testing
```

Maybe, you can try to print the exported packages, run
```bash
$ conan search
```
and copy the output here, maybe it is a case (lower-upper) issue? Please tell me and we'll try to figure out. Thanks for reporting!

**Comment by memsharded** [comment]
Hi Ryan,
Didn't get feedback for this issue, and haven't had any similar report, so the upload seem to be working fine. I am closing this issue, but please reopen or report a new one if you have a problem again. Thanks!

**Comment by EugeneKosmin** [comment]
Hi James,

I have been evaluating Conan for a few days, and now I have faced the problem with package upload.

I have two VMs with Debian: one as a locally hosted on my PC and another one as a cloud server. 

Here is my console:
C:\>conan search
Existing package recipes:

libpng/1.6.23@aurigma/master
zlib/1.2.8@aurigma/master

C:\>conan upload zlib/* -r debian
Are you sure you want to upload 'zlib/1.2.8@aurigma/master'? (yes/no): yes
Uploading zlib/1.2.8@aurigma/master
Uploading conanmanifest.txt
[==================================================]
Uploading conanfile.py
[==================================================]
Uploading conan_export.tgz
[==================================================]
Uploaded conan recipe 'zlib/1.2.8@aurigma/master' to 'debian': http://10.183.112.218:9300

C:\>conan search -r debian
There are no packages

The same commands work fine with my locally hosted Conan.

Both servers have the same configuration, I have checked filesystem permissions (/.conan_server/data, right?) and there were no error messages from gunicorn console, even with debug level of logging.

Is there anything else I can check?

**Comment by lasote** [comment]
It's weird, try to perform a search directly to the URL with a browser or curl to this URL:

http://10.183.112.218:9300/v1/conans/search

**Comment by EugeneKosmin** [comment]
Looks like I found the reason...

host_name in both cases had 'localhost' value by default, and it worked well on my local VM because of port forwarding.

Everything worked fine when I had changed host_name to IP address. If I change host_name to 'localhost', the problem comes back again.

**Comment by lasote** [comment]
Yes, it happens. You need to write the IP or a public host name for the remote, the uploads are done in two steps, first the client ask for permissions and get some upload URLs (containing the host_name), then the client in the second step use these URLs to actually put the files.

So if you don't want to keep the public IP in the `host_name` configuration field, you will need to create a host name with a DNS or manually with a hosts file...etc. Usual network configuration.

**Comment by EugeneKosmin** [comment]
BTW, at some point, I checked HTTP traffic with Fiddler tool, and it was pretty equal for both cases. All files were uploaded with 200 response code.

I would consider showing some error message, if possible.

**Comment by memsharded** [comment]
Hi Eugene! If the ``host_name: localhost`` is not correct and not able to upload, it throws error, I have just tried. It could be an unlucky coincidence that you were running the two servers, and the uploads were being redirected to the other one while the search goes to the "logic" endpoint, not to the "transfers" endpoint. Please try again, making sure you only have the networked server running, and please tell me if the transfers are still ok. Thanks!

**Comment by EugeneKosmin** [comment]
Hi James,

I turned off the local VM, and now I get a red error with 'localhost' in the config. 

Thank you, guys!

**Comment by memsharded** [comment]
Excellent! I think this issue can then be closed now. But please report if any other issue. Thanks!
