### ISSUE TITLE
API compatibility/recipe versioning

### ISSUE THREAD

**Issue by bschindler** [conan-io/conan#2320]
This is a question and not a bug report: 

In the update to 1.0, the python API was changed in an incompatible way and I suppose the API will also change in the future (may be in a more smooth manner, but still). So: 
- How does conan deal with the situation that people tend to have different versions of conan and that a recipe might work for one version but not the other?  
- What is the API stability strategy for conan? We're going to start migrating our recipes to conan 1.0 soon, so it would be good to know how to approach conan versioning

**Comment by memsharded** [comment]
Good question.

So far, to keep backwards compatibility for recipes, in many cases we were doing it internally. Like ``CMake(self.settings)`` that was deprecated in favor of ``CMake(self)``. So for a long time we checked the constructor argument, and act accordingly. We removed them just before 1.0. 
Same strategy will be followed as widely as possible, try to add without breaking. In theory, if a recipe works with conan 1.0 it should keep working until 1.XX. If not, it will be considered a bug/regression and we will try to fix it. Conan 2.0 will be the one cleaning up and potentially introducing breaking changes, if necessary. Warnings will be added to 1.XX versions, in the same way they were introduced in 0.X versions, to prepare in advance for a smooth 2.0 transition.

Finally, if it was necessary, we could try to add version labels (like a first line with a comment) in conanfile recipes, so both 1.0 and 2.0 recipes could exist. But this is still speculation, should be a last resort.

**Comment by weatherhead99** [comment]
perhaps some tool (akin to the python 2to3) could be created to handle (at least most simple cases) for this...

**Comment by memsharded** [comment]
Py2to3 is a tool to migrate from python 2 to python 3. I think the main concern here is to maintain compatibility simultaneously with different versions of conanfiles that otherwise couldn't be run at the same time under the same conan invocation. Not to migrate, that is typically just a simple search&replace, so far a tool for it hasn't been worth the effort. Could you please elaborate a bit furter what are you thinking about @weatherhead99, please?

**Comment by weatherhead99** [comment]
yes, I was thinking basically about a "conan1to2" tool, that would do things like replace the "self.settings" with "self" in CMake() invocation. For example, that alone breaks many packages on conan-transit under conan 1.0.0

**Comment by memsharded** [comment]
Conan non-breaking policy (forward) is well defined now in https://docs.conan.io/2/introduction.html#stable
Recipe allow defining ``conan_required_version`` ranges to help UX when using new features. Closing this as outdated.
