### ISSUE TITLE
Suggestion: adding a helper for darwin host

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2322]
Hi,

I was wondering if a helper could be added in `tools` to detect if the `os` setting is targeting a darwin platform. Here is my use-case:

```python
    if self.settings.os in ["Macos", "iOS", "watchOS",  "tvOS"]:
        # ...

    # What I have in mind
    if tools.darwin_platform(self.settings.os):
        # ...
```

This is not a big deal, but I'm too lazy to type it in every recipe :D

**Comment by memsharded** [comment]
Actually there is already a great contribution from @SSE4 here: https://github.com/conan-io/conan/pull/1815. It includes such functionality.

The PR looks good, it is just that we lacked some expertise to properly review it ontime for 1.0. We'll try to incorporate it in one of next releases.

**Comment by theodelrieu** [comment]
Great!
