### ISSUE TITLE
[Enhancement] Output of `conan config install` exposes preconfigured URL (which may include a password)

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#2324]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

On our CI system, the first build step is to run `conan config install` (with no arguments) to ensure the latest configuration is installed on the agent. No parameters are used because the initial configuration of that build agent already set up the URL. This is convenient because during initial configuration, we can load the HTTP password (i.e., http://foo:bar@artifactory/...) and it's not available anywhere within the build script.

However, the first output of the command is to output the exact URL, including the password. As a result, the password is exposed on the CI system's build log. 

It would be nice if the `conan config install` hid the password from the URL. Alternatively, perhaps a command line switch could be offered to put it into a "quiet mode" so that the URL is not output. This way, the password is not exposed in the build log.

**Comment by memsharded** [comment]
Yes, this makes sense.
I would suggest trying to hide the password in any case, as some people might not be aware of the possible ``--quiet`` option and leak the password. Then the ``--quiet`` argument too, to make sure, just in case something goes wrong with the password hiding. 

Pattern to cover:
- http://username:password@example.com/
- Any other one? Git doesn't support password in git urls

**Comment by markgalpin** [comment]
Absolutely we should by default be "quiet" and then maybe allow a --quiet=false for when you need to see things (if we allow this at all.)

**Comment by memsharded** [comment]
Well, there is a second derivative we want to consider. The URL is cached in conan.conf, for later reuse, so ``conan config install`` without arguments will reuse such URL.
Maybe you don't want to store that URL either. But we can't make this the default, as it would be breaking current behavior.
