### ISSUE TITLE
AutoToolsBuildEnvironment adds unknown options to MSVC

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#2326]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

certain projects (e.g. ffmpeg) use auto-tools style builds for Visual Studio as well.
as for conan 1.0.2, using the **AutoToolsBuildEnvironment** helper, MSVC receives unrecognized options:
```
cl : Command line warning D9002 : ignoring unknown option '-m64'
cl : Command line warning D9002 : ignoring unknown option '-g'
```

**Comment by weatherhead99** [comment]
SSE4: How does this even work? It's build using windows shell and MSVC, not mingw with bash, but using autotools?

**Comment by SSE4** [comment]
MSYS bash + MSVC, see https://trac.ffmpeg.org/wiki/CompilationGuide/MSVC

**Comment by SSE4** [comment]
I've made additional adjustments to supply proper include/library directories as well
it allowed me to successfully pass configure for ffmpeg

**Comment by SSE4** [comment]
NOTE that is also breaks build of libvpx:
```Unknown option "-m64".
See gen_msvs_vcxproj.sh --help for available options.```
