### ISSUE TITLE
N configs -> 1 package runtime setting

### ISSUE THREAD

**Issue by bschindler** [conan-io/conan#2328]
Windows, Visual Studio 2015, conan 1.0.1
Sorry for bombarding you with questions/bugs: 

When using the example posted here https://github.com/memsharded/hello_multi_config with visual studio (2015 in my case), the following is the result in conaninfo.txt: 

[settings]
    arch=x86_64
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=14
    os=Windows

So, build_type is removed but runtime is set to MD which is misleading as the release will be MD, but debug will be MDd by default. 
Should the runtime also be set to ANY in package_id or is it intentional that this stays?

**Comment by memsharded** [comment]
No problem, thanks very much for all your questions and feedback.

Yes, you are right, this recipe has to include this (or maybe remove the subsetting in ``configure()``, I am not sure), and also has to be updated to be compatible with conan 1.0. I will do it and also update the docs accordingly, thanks!

**Comment by memsharded** [comment]
I have updated the repo to 1.0: https://github.com/memsharded/hello_multi_config
Now it presents 2 different approaches, depending on what you want to do.

I have also proposed a PR for the docs: https://github.com/conan-io/docs/pull/487

**Comment by memsharded** [comment]
Both the repo and the docs have been updated.
Please have a look and report if something still wrong. Thanks very much for pointing this.
