### ISSUE TITLE
"local" ambiguous

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#2333]
In the dependency graph (Printer.print_graph()), "from local" is used to indicate that a requirement is not associated with a remote. But it could also mean that it is associated with a remote called "local". There are indeed remotes called "local" in the docs and in the tests. Maybe replace it by "from local cache"?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, I agree, thanks for pointing this!

**Comment by memsharded** [comment]
This is not released yet, lets keep it open
