### ISSUE TITLE
test_package dependencies of shared libs

### ISSUE THREAD

**Issue by langeseb** [conan-io/conan#2337]
A question:
How do I add shared library dependencies in my conan test package in a correct way?
**Following problem:**
LibB is a conan package created with a dependency to conan package LibA (*.so Linux shared library), using "requires=LibA" during package creation and RunEnvironment tools to set the environment variables. This works fine.
Now I want to set up a test for LibB. It's not clear to me, how conan handles the dependency to LibA. I would expect, that it recognises the dependency of LibB because of the "requires=LibA" in the package recipe (in order to avoid multiple "requires" for a single lib --> error prone). But it doesn't - the test exits with error "libA.so not found".
So I've tried to set the dependency explicitly in the test recipe, i.e. adding "requires=LibA" and RunEnvironment.vars in test_package/conanfile.py also with no success. 

Thank you for help!

**Comment by memsharded** [comment]
Hello!

This is a bit hard to reproduce, the description is not very clear to me, can you please setup a repository with such example, so we can check it?

Thanks very much!

**Comment by langeseb** [comment]
Thanks for quick response. 
Here you go:
https://github.com/langeseb/conan-parallel-hdf5

I'm trying to build hdf5 using openmpi - so LibA in the previous example is openmpi, LibB is hdf5

**Comment by memsharded** [comment]
I was thinking of something more minimal, so it was easier to reproduce :)

I will have a look when possible, but it might take some time, please ping me again if necessary.

**Comment by weatherhead99** [comment]
@langeseb I think in this particular case, it might be that your package_info isn't correct.
For one thing, isn't building the c++ HDF5 bindings not supported with parallel HDF5?
For another, aren't by default the hdf5 libraries built as SONAMED libraries (i.e. it will install libhdf5.so.10 and a symlink libhdf5.so, at the moment you will only be packaging the symlink...)

And finally, you don't include "libhdf5_hl.so, libhdf5_hl_cpp.so " etc etc in the package_info() libs. That shouldn't fail this test in particular since you are only using the C library, but I think it would fail if using the C++ or fortran bindings.

**Comment by lasote** [comment]
@langeseb in the `test_package` conanfile.py try to debug if the problem is because of missing directories to openmpi:

```
env = RunEnvironment(self)
with tools.environment_append(env.vars):
    self.output.warn("!! => %s" % env.vars)
```

If the directories are there pointing to openmpi check if the `so` libs are there.

**Comment by langeseb** [comment]
@lasote @weatherhead99 
Thanks for your input - I found the problem: it was indeed linked to the symlink structure - in my first version, I didn't use the symlink hierarchy resulting in libs without version number (i.e.l libusempi.so instead of libusempi.so.1.2), but the build process of hdf5 seem to link against the explicit versions. Since my lib-files didn't have the version number, the build process haven't found the lib. Setting symlink=True solved the problem.
Thanks again!
