### ISSUE TITLE
Indirect dependencies causes linker error in Visual Studio

### ISSUE THREAD

**Issue by psturm-tomra** [conan-io/conan#2339]
**Command:**
```
conan install -s build_type=Release -s arch="x86_64" --build=missing --install-folder ./x64/release .
```

**conanfile.txt:**
```
[requires]
rxcpp/4.0.0@bincrafters/stable
Boost.Iterator/1.64.0@bincrafters/stable
Boost.Optional/1.64.0@bincrafters/stable
Boost.Tokenizer/1.64.0@bincrafters/stable
Boost.Range/1.64.0@bincrafters/stable
Boost.Algorithm/1.64.0@bincrafters/stable

[generators]
visual_studio
```
**Remote**
The packages are taken from remote "https://api.bintray.com/conan/bincrafters/public-conan".

The property sheet that has been generated contains as input libraries:
```
libboost_log.lib;libboost_log_setup.lib, .... _and some more_
```
So the indirect depencies of the packages have been found and were added correctly to the property sheet. However, the linker error is: **"LNK1181 cannot open input file 'libboost_log.lib'.** which means that the lib could not be found.

I searched recursivly for *.lib in c:\\.conan and I can only find: libboost_container.lib, libboost_exception.lib and libboost_regex.lib. So it seems that the indirect dependencies were not made available during the conan install command.

The issue, I experience, is similar to #1561 

**More information**
OS: Windows 10
Compiler: Visual Studio 15.5.3
Conan: 1.0.2 (Installed by windows installer)

----------------
To help us debug your issue please explain:
- [X] I've read the [CONTRIBUTING guide]( https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Thank you very much for your detailed report.
So far, I'd say it is more a package issue from Boost packages, than a conan issue. I am running some tests, but I'd say you better report it in: https://github.com/bincrafters/community

**Comment by memsharded** [comment]
I am not sure what is happening, but running the above command with that conanfile.txt, I get in my .props file:

```
<AdditionalDependencies>libboost_exception.lib;libboost_container.lib;libboost_regex.lib;%(AdditionalDependencies)</AdditionalDependencies>
```

I don't know why you have "log" in your dependencies. Are you passing some extra option, or have something special in your default profile?

**Comment by psturm-tomra** [comment]
You are right. Somehow the properties from a previous conanfile.txt ended up in my project file. This was my fault. I removed them and now it works. Thanks for your help.
Next time I double check the property sheet in a text editor and not in the IDE.

**Comment by memsharded** [comment]
No problem, glad to help!

Can we close this issue now then? Thanks
