### ISSUE TITLE
Generator example no longer work when running in Cygwin

### ISSUE THREAD

**Issue by JHoule** [conan-io/conan#2341]
Something in the 1.0 update seems to be giving issues when running under Cygwin.

This happens when running the generator example listed here:
  http://docs.conan.io/en/latest/howtos/custom_generators.html#premake-generator-example

To reproduce, launch a Cygwin terminal then run the following:

```bash
git clone https://github.com/memsharded/conan-premake.git
cd conan-premake
conan export . demo/testing
```

It used to work with version 0.3, but it now results in the following error (disregard the warnings):
```
Linter warnings
    WARN: Linter. Line 62: Bad indentation. Found 6 spaces, expected 8
    WARN: Linter. Line 65: Bad indentation. Found 6 spaces, expected 8
    WARN: Linter. Line 66: Bad indentation. Found 6 spaces, expected 8
    WARN: Linter. Line 67: Bad indentation. Found 6 spaces, expected 8
    WARN: Linter. Line 2: Unused BUILD_INFO imported from conans.paths
    WARN: Linter. Line 3: Unused CMake imported from conans
WARN: Conanfile doesn't have 'description'.
It is recommended to add it as attribute
ERROR: '.git' is an invalid name. Valid names MUST begin with a letter or number, have between 2-50 chars, including letters, numbers, underscore, dot and dash
```

For some reason, the .git folder seems to be exported, and it shouldn't.

Note that while this is running under Cygwin, I have installed Conan using the native Windows Python:
```bash
py -m pip install -U conan
```

The current workaround is to run the `conant export` command from a native Windows terminal (e.g. cmd.exe).

**Comment by JHoule** [comment]
Turned out to be a broken dev package in the Conan storage path (which itself had a .git directory, which shouldn't have been there).

Closing this bug, as it isn't one after all.

**Comment by memsharded** [comment]
Hi @JHoule 

Thanks for submitting this issue, glad that it was not a bug after all.

If you are using the premake generator, there is no problem in adding it as built-in, it wasn't added at the moment, but if used actively, it can be reviewed and added.

Thanks for the feedback!

**Comment by JHoule** [comment]
I'm actually working on an updated version, which I intend to ask feedback for once I feel it's mature enough.

I'm by no means a Conan expert, though, so it might take some time.

**Comment by memsharded** [comment]
Great!
Sure, feel free to ask. Don't worry about not being a conan expert, we will help with it, and thanks to generators design, it is not critical that it is 100% perfect, so feel confident to submit it as a contribution when you are ready, and other eventual users might help to fine tune it too.
Thanks!
