### ISSUE TITLE
Export-pkg assumes only package() method modifies package_directory

### ISSUE THREAD

**Issue by Sheeo** [conan-io/conan#2350]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.0.2

## Issue

When using `conan export-pkg` to export a package, conan assumes the recipe's `package()` method is all that needs to be invoked.

As per the guide, cmake-projects can use the helper `cmake.install()` in their `build()` method, if targets are already setup for installation in CMake.

## Steps to reproduce

Given the following conanfile:

```python
class TestpkgConan(ConanFile):
    name = "testpkg"
    version = "0.1"
    generators = "cmake"
    exports_sources = "src/*"

    def build(self):
        # Doing a copy here to simluate cmake.install()
        self.run("mkdir -p package/share && cp src/CMakeLists.txt package/share/")

    def package(self):
        # Noop
        return
```

And the following shell session:

```sh
λ conan build .
...
λ conan package .
PROJECT: Generating the package
PROJECT: Package folder testpkg/package
PROJECT: Calling package()
PROJECT package(): WARN: No files copied!
PROJECT: Package 'package' created
λ conan export-pkg . testpkg/0.1@sheeo/testing
testpkg/0.1@sheeo/testing export: Copied 1 '.h' files: hello.h
testpkg/0.1@sheeo/testing export: Copied 1 '.cpp' files: hello.cpp
testpkg/0.1@sheeo/testing export: Copied 1 '.txt' files: CMakeLists.txt
Packaging to 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
λ conan export-pkg -f . testpkg/0.1@sheeo/testing
...
testpkg/0.1@sheeo/testing: Calling package()
testpkg/0.1@sheeo/testing package(): WARN: No files copied!
testpkg/0.1@sheeo/testing: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
```

It should be expected that the package folder contains the `CMakeLists.txt` file copied in the `build()` step, however, only the following files are present:

```sh
λ ls -la ~/.conan/data/testpkg/0.1/sheeo/testing/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
total 16
-rw-r--r--  1 sheeo  staff   150B Jan 22 13:49 conaninfo.txt
-rw-r--r--  1 sheeo  staff    59B Jan 22 13:49 conanmanifest.txt
```

**Comment by memsharded** [comment]
Yes, you are right. ``conan export-pkg`` only calls ``package()`` method, which is an inconvenient if using the ``cmake.install()`` feature.

The following workaround, demostrated in a test, might be possible:

```python
    def cmake_install_export_pkg(self):
        client = TestClient()
        cmake = """set(CMAKE_CXX_COMPILER_WORKS 1)
project(Chat NONE)
cmake_minimum_required(VERSION 2.8.12)
install(FILES header.h DESTINATION include)
"""
        conanfile = """from conans import ConanFile, CMake
class AConan(ConanFile):
    exports_sources = "*"
    settings = "os", "compiler", "build_type", "arch"
    exports_sources = "CMakeLists.txt", "*.h"
    def build(self):
        cmake = CMake(self)
        cmake.configure()
    def package(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.install()
"""
        client.save({"conanfile.py": conanfile,
                     "CMakeLists.txt": cmake,
                     "header.h": "myheader"})
        client.run("create . Pkg/0.1@user/testing")
        conan_reference = ConanFileReference.loads("Pkg/0.1@user/testing")
        packages_folder = client.client_cache.packages(conan_reference)
        package_folder = os.path.join(packages_folder, os.listdir(packages_folder)[0])
        self.assertEqual("myheader", load(os.path.join(package_folder, "include/header.h")))

        client.save({"conanfile.py": conanfile,
                     "CMakeLists.txt": cmake,
                     "header.h": "myheader2"})
        client.run("install .")
        client.run("build .")
        client.run("export-pkg . Pkg/0.1@user/testing -f")
        self.assertEqual("myheader2", load(os.path.join(package_folder, "include/header.h")))
```

Basically:
```python
def build(self):
    cmake = CMake(self)
    cmake.configure()
def package(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.install()
```
I understand this is not the prettiest thing, so lets have a look if something could be improved:
- If ``conan export-pkg`` and there is no ``package()`` method, call ``build()`` instead, assume it will have the install logic in it.

**Comment by DavidZemon** [comment]
Hi all,

I've run into this issue too and came up with something that I think is a lot better than running the entire `build()` function twice. It's a lot more code, but I think it could be added to Conan to improve CMake support. Here's my recipe:

```py
def source(self):
    self.run('git clone --depth=1 git@bitbucket.org:redlionstl/c-nviewparser.git -b v' + self.version)

def build(self):
    source_dir, build_dir = self._get_dirs()

    cmake = CMake(self)
    cmake.configure(source_dir=source_dir, build_dir=build_dir)
    cmake.build()

def package(self):
    self.run('cmake --build {0} --target install'.format(self._get_dirs()[1]))

def _get_dirs(self):
    if self.source_folder == self.build_folder:
        source_dir = os.path.join(self.build_folder, 'c-nviewparser')
        assert os.path.exists(source_dir), 'Source and build directories are the same. This should only ' \
                                           'happen when being run via `conan create`. If that\'s not the case, ' \
                                           'please ensure you\'re building c-nviewparser from outside the source ' \
                                           'directory. Only baboons build in the source directory.'
        build_dir = os.path.join(self.build_folder, 'build')
        if not os.path.exists(build_dir):
            os.mkdir(build_dir)
            for entry in os.listdir(self.build_folder):
                candidate = os.path.join(self.build_folder, entry)
                if os.path.isfile(os.path.join(self.build_folder, entry)):
                    shutil.copy2(candidate, build_dir)
    else:
        source_dir = self.source_folder
        build_dir = self.build_folder

    return source_dir, build_dir
```

**Comment by DavidZemon** [comment]
I should add, rather than asserting that `source_dir` exists, I would have preferred to simply do something like `assert tools.invoked_via_conan_create`, but I couldn't find anything like that. I'm sure if this were added to Conan it could be written better. The `os.path.exists(source_dir)` works because when invoked via `conan create`, the first step is to check out from git which will of course create the appropriately named directory. But that, of course, is not fool proof.

**Comment by memsharded** [comment]
Quick question, I am thinking again, what would be the disadvantages of:
```python
def build(self):
    cmake = CMake(self)
    cmake.configure()
def package(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.install()
```
I'd say it is a pretty simple, elegant and efficient enough solution.

Regarding your approach a couple of observations:
```python
if self.source_folder == self.build_folder:
         'directory. Only baboons build in the source directory.'
```
While I have had a good laugh with this :) :) :), and I always strongly recommend out of source builds, there are many people that are doing in-source builds for some reasons. Professional engineers that are building great products that probably you are using them and liking them. So conan cannot take an opinionated approach, blocking some flow, if it can be avoided.


Also, yes, there are ways to know you are in the local cache: http://docs.conan.io/en/latest/reference/conanfile/attributes.html#in-local-cache

Thanks for the feedback!

**Comment by Sheeo** [comment]
I would say the problem with the approach of duplicating the cmake `.configure()` and `.build()` in both the build and package functions is just that: having to duplicate them :)

Running into this, a new user might be as unfortunate as to try and assign `self.cmake` from `build()` (Luckily I had read the manual, and therefore didn't attempt to do so), which could be an additional source of frustration.


I think the real source of the problem is the use of `export-pkg` itself: If I had a way of neatly symlinking my local working-directory package into the local cache, I would not be using `export-pkg` at all.

**Comment by memsharded** [comment]
The conan-project functionality might help for some cases, but I think that the flow ``install + build + export-pkg`` is still needed, and also ``export-pkg`` is widely use to create packages around pre-built binaries.

Regarding:
> I would say the problem with the approach of duplicating the cmake .configure() and .build() in both the build and package functions is just that: having to duplicate them

It is not totally accurate. The .build() method is not necessary to do twice. The full thing is:

```python
def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
def package(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.install()
```

Which I think it could make lots of sense. The extra configure() is very necessary. Recall that the ``conan package`` is a command that will create a package locally, in user space, and it defines ``CMAKE_INSTALL_PREFIX`` for that. If an install to the local cache is being done with ``conan export-pkg``, it is necessary to configure again cmake to point ``CMAKE_INSTALL_PREFIX`` to the conan local cache.
Furthermore, the extra ``cmake.configure()`` is very fast, so performance is not an issue, it is not doing a clean cmake configuration.

**Comment by Sheeo** [comment]
Ah, of course. Anything put into the `.configure()` call needs to be duplicated, though--but I suppose a helper like the following would fix that:

```python
def create_cmake(self):
    cmake = CMake(self)
    cmake.configure(defs=self.options, build_folder="./build", ...)

def build(self):
    self.create_cmake().build()

def package(self):
    self.create_cmake().install()
```

This is quite a common idiom for packages I work with, since many of them have install-rules defined in CMake, which would be tedious to duplicate.

**Comment by memsharded** [comment]
If you want to do that, you can of course, but I feel my above implementation is simpler to read, avoids extra jumps, and saves 1 line in the file :)

Maybe what could be done is add an extra argument and behavior to ``conan export-pkg``

```bash
$ conan export-pkg . Pkg/0.1@user/testing --package-folder=mypkg
```

The behavior for this would be:
- Assumes package() has been called, or the package has been created (with cmake.install() executed from the build() method.
- Do an exact copy of the contents of the package (in this example ``mypkg``) local folder. Do not execute again ``package()``
- It will ignore (or raise) if --build-folder or --source-folder is specified

Would this feature solve the issue?

**Comment by Sheeo** [comment]
Yep, that'd be sufficient 👍

**Comment by bryceschober** [comment]
So... this solution to set the `--package-folder` doesn't support the `conan create` flow, which is necessary for `conan-package-tools` (see conan-io/conan-package-tools#247).

In my opinion, this solution should be [documented and promoted here](https://docs.conan.io/en/latest/howtos/cmake_install.html), even mentioning that this approach is necessary for the `conan create` flow and `conan-package-tools`:
```python
def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
def package(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.install()
```
