### ISSUE TITLE
Visual Studio addon

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2353]
Opening this issue to centralize efforts and reference towards a VS addon for conan.

For current workarounds around VS 2017 + CMake, read: https://github.com/conan-io/conan/issues/778#issuecomment-359437587

Also to resolve the use case of @bschindler in https://github.com/conan-io/conan/issues/2327: can't use single-config packages + find.cmake + IDE

**Comment by ForNeVeR** [comment]
Well, I've already commented on #788 and I'll add my comment here: we're working on the plugin in the [bincrafters repo](https://github.com/bincrafters/conan-vs-extension). Currently we've implemented integration of `visual_studio_multi` generator with vcxproj that semi-automatically calls `conan install` for each of the project configurations and adds the resulting prop file to the vcxproj.

Current plans include CMake-based project support (i.e. no vcxproj?) and adding a GUI to search and administer packages similar to NuGet one.

**Comment by memsharded** [comment]
@ForNeVeR That is great!

I suggest then interested users to contribute and give feedback in: https://github.com/bincrafters/conan-vs-extension

Maybe at some point it would be good to make it an official plugin, automate updates, releases, etc, and provide support also from our side. Lets keep talking.

Thanks very much for taking this effort.

**Comment by luckielordie** [comment]
+1 on this. I know something like this would help get support for Conan around our office.

**Comment by wpalfi** [comment]
In the meantime, there are two other options to run conan install from VS:
- Using Visual Studios "External Tools" feature
See my comment here: https://github.com/conan-io/conan/issues/2147#issuecomment-352412557

- With CMake: Add optional targets that can be triggered manually. Note how this is different from conan_cmake_run. 
```CMake
 add_custom_target(CONAN_INSTALL conan install ${CMAKE_CURRENT_SOURCE_DIR}/conan COMMAND cmake ${CMAKE_CURRENT_BINARY_DIR})
 add_custom_target(CONAN_INSTALL_DEBUG conan install ${CMAKE_CURRENT_SOURCE_DIR}/conan -s build_type=Debug COMMAND cmake ${CMAKE_CURRENT_BINARY_DIR})
 ```

![grafik](https://user-images.githubusercontent.com/18048248/35344029-61efbf1e-012c-11e8-9676-32d6af50ca30.png)

**Comment by SSE4** [comment]
@jgsogo should we close this one now?

**Comment by jgsogo** [comment]
Yes, sure, I think that every effort or comment related to a Visual Studio extension should be redirected to its own repo now that it is officially supported by us: https://github.com/conan-io/conan-vs-extension

Thanks to everyone for making it a real option to start using Conan 🎉  🎉  🎉
