### ISSUE TITLE
Metadata is missing in Windows installer

### ISSUE THREAD

**Issue by mmatrosov** [conan-io/conan#2354]
We are deploying conan to Windows machines for our developers with help of Microsoft Software Center, maintained by our IT department. They complain about missing metadata from installer files. 

C:\Program Files\Conan\conan\conan.exe properties are empty (tested for x64 installer):
![props](https://user-images.githubusercontent.com/3617951/35231030-c5fd858e-ffa8-11e7-93ef-c8a049507084.png)

HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Conan Package Manager_is1\DisplayVersion = 1.0.2 is string.

It might be challenging for an update scenario and best practice for deployments is to have Version attribute set both .exe and reg key (DWORD).

All above is needed for detection methods used by System Center Configuration Manager/Software Center in order to install/uninstall/update this soft.

Could you please add this information and fix registry setting in the installer?

**Comment by memsharded** [comment]
I have managed to add the missing pieces of information. 
But I don't understand the issue with the reg-key. The installer is not setting it, so I guess it is automatically set by default by InnoSetup. Could you explain a bit further what is the issue with 

> HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Conan Package Manager_is1\DisplayVersion = 1.0.2 is string.

Thanks!

**Comment by memsharded** [comment]
Hi @mmatrosov 

I wanted to ask: actually there are 3 applications/executables: conan.exe, conan_server.exe and conan_build_info.exe that are bundled and installed together, in the same location. Is it ok to have the same metadata for all of them, so the Product Name and Description matches "Conan" and "Conan, C/C++ Package Manager", for example?

**Comment by memsharded** [comment]
HI @mmatrosov 

Please have a look to the above questions, I would like to submit a PR with this and move it forward. Thanks!

**Comment by mmatrosov** [comment]
Sorry for the delay. Was consulting with our IT guys. 

> But I don't understand the issue with the reg-key. 

The problem is that currently there is no numeric representation of full version in the registry. Take a look:
![image](https://user-images.githubusercontent.com/3617951/35392323-8cef2db4-01f2-11e8-9a00-d98f2b50cfe9.png)

There is no numeric value representing a Patch version. It is represented only as part of a string "DisplayVersion". For major and minor you have corresponding DWORD fields. Thus, if you want to tell, whether you need to update conan, you need to parse a string.

> Is it ok to have the same metadata for all of them, so the Product Name and Description matches "Conan" and "Conan, C/C++ Package Manager", for example?

It is ok for our tasks, yet I don't see a problem in setting different descriptions for them. Our IT wants any reliable way to understand whether current installed version needs to be updated or not. If `conan.exe` has appropriate fields set - it is enough. We can easily use them. So for our scenario this is ok.

**Comment by memsharded** [comment]
I have already submitted a fix for the exes metadata.

Regarding the registry keys, I have been investigating, and so far there is no way to do this with InnoSetup. Also I have been having a look to the registry for Uninstall for other installed apps in my computer (to get an idea or a reference for naming), and no one defines such a patch. Some of them define ``MajorVersion``, ``MinorVersion``, but I haven't been able to find something like ``PatchVersion`` among the several apps and devtools I have installed. Any suggestion about this? Thanks!

**Comment by mmatrosov** [comment]
> Also I have been having a look to the registry for Uninstall for other installed apps in my computer (to get an idea or a reference for naming), and no one defines such a patch. 

Hm, did the same exercise with the same result. Looks strange indeed. Well, anyway, having metadata in installer and `conan.exe` is ok for us at this point.

**Comment by memsharded** [comment]
Windows installer released in 1.0.4 includes the metadata both in the 32 and 64 bits installer, please check. Thanks!

**Comment by mmatrosov** [comment]
Looks good, thank you!
