### ISSUE TITLE
Optionally Skip Testing When Cross Building

### ISSUE THREAD

**Issue by ahoischen** [conan-io/conan#2355]
I am cross compiling libraries with test_packages which cannot be built for the target platform. Currently, this causes unnecessary build failures because the test_package build fails due to incompatibility with the platform. I would like to specify on the command line that test failures should not cause this build to fail because I know that these failures are false positives. 

While it can be argued that all code should always be tested for all platforms, doing so is not feasible in my case since it would require adding large amounts of platform specific code to the test_package and running the executable in an emulator. Currently, the simplest solution to this problem is to run `export` and `install` manually, but doing so is inconvenient and it's easy to forget to `export`. Adding more sophisticated options to each conanfile is perhaps more clean but requires additional work in each used package which may be maintained by third parties.

To fix this issue, a simple `--no-test` flag should be added to `conan create`.

*EDIT*: I just noticed that test_packages are only run for the current package, not those being built using `--build`. Originally, I detailed a system that allowed selectively disabling tests, but this fact greatly simplifies the issue.

**Comment by memsharded** [comment]
I think that naming the test_package differently to *test* and *test_package*, then providing its name with ``-tf`` argument would be good enough. As this process should probably be done in CI, forgetting about this shouldn't be a big issue.

I would say that adding an extra argument will further clutter the command line, which already has many parameters. What about using ``conan create -tf=None`` (read it as "the test folder is None = there is no test folder")? In that case, it should be an easy feature, I wouldn't oppose to it.

**Comment by ahoischen** [comment]
Thanks for the feedback!

I did consider renaming the test_package but this is more of a workaround in my opinion. Currently, I can compile most packages by just specifying a profile and maybe a few other flags. Using this workaround, I'd have to move the test folder in existing packages which complicates the build and is not very intuitive. I also want to run my tests by default since I'm using TDD and having to specify `-tf` every time would be somewhat irritating. Cross compiling happens less frequently and already requires specifying a profile, so adding another flag in that case isn't too bad.

Using `-tf=None` would be just as good as adding `--no-test` from an end-user perspective, so I'd be in favor of this solution.

**Comment by memsharded** [comment]
Ok, lets do it that way then!
