### ISSUE TITLE
vcvars command fails when there is both Enterprise and Professional VS2017 installed

### ISSUE THREAD

**Issue by youcefl** [conan-io/conan#2357]
On a machine where both Professional and Enterprise version of VS2017 are installed
I get this:

> vswhere detected VS 15 in C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
> WARN: VS variable vs150comntools points to the non-existing path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools",please check that you have set it correctly
> ******/3.2.0@*******/stable: Running build command: echo >NUL 2>&1 && set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\../../VC/Auxiliary/Build/vcvarsall.bat" amd64 && cd /d "E:/.conan\ngk0_ifs\1" && ....
> '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional' is not recognized as an internal or external command,
> operable program or batch file.
> 
> 

Conan version is 1.0.2.
To reproduce use tools.vcvars_command() to run vcvarsall.bat e.g.

>     def build(self):
>         self.run(tools.vcvars_command(self.settings))
> 
> 

It looks like the fact that the output of vswhere can contain several lines e.g.
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise

was not taken into account.

**Comment by memsharded** [comment]
Related issue https://github.com/conan-io/conan/issues/2258

This indeed seems buggy/unwanted.
However I don't envision a good solution for this. Which VS version should conan use, just the first one? The "higher" level one (Community<Professional<Enterprise)?

**Comment by youcefl** [comment]
Maybe use the first one and allow the user to override the selected
VS edition?

**Comment by memsharded** [comment]
Ok, lets try to do something like that. Thanks for the feedback!

**Comment by danimtb** [comment]
This will need utilities inplemented in the open PR #2280, so revision and merge is needed
