### ISSUE TITLE
Missing documentation for PATH handling when using self.run

### ISSUE THREAD

**Issue by sturmf** [conan-io/conan#2358]
When I use self.run in a conan recipe the PATH variable only points to the build directory but nowhere else.
This is a problem if I want to e.g. call a shell script that builds something and needs a tool in e.g. /usr/bin.
In my case it was "dirname" for example. 
It took me a while to figure out that the following works (was easy once I new the PATH variable gets cleared):

    self.run("PATH=$PATH:/usr/bin myscript.sh") 

I think the empty env vars should be made more obvious in the run command documentation and how to work with it. Maybe it is meant to work differently?

**Comment by memsharded** [comment]
I am not sure I understand your issue. Commands like:

```python
def build(self):
      self.run("cmake .")
```

works well if cmake is in the path. Same as ``self.run("git clone ...")`` which is massively used by conan users without any problem.
Could you please clarify this? Thanks.

**Comment by sturmf** [comment]
I am using conan 1.0.2 installed in a docker container and if I do a

    self.run("echo Path is $PATH && exit -1") I get:

PATH is /root/.conan/data/packagename/1.0/test/stable/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/packagename
sh: 1: exit: Illegal number: -1

The exit -1 is only to force the output on the console.
As you can see only the path to the conan package is set and therefore no other command can be found. I am not able to use dirname or git or anything else on the command line.

One other trick that works is to set the default profile 
[env]
PATH=[]

to export the client PATH settings.

**Comment by memsharded** [comment]
This might be something related to your docker environment configuration. I am going to ping @lasote, to check if he can help, but please also check your docker config.
You can find some docker images we are using for CI here: https://github.com/conan-io/conan-docker-tools
Thanks for your feedback!

**Comment by lasote** [comment]
Should not be related to Docker, Do you have any dependency adjusting `self.env_info.PATH` or any entry in the applied profiles?
Setting `PATH=[]` makes Conan consider the PATH env var as a list, so any other assignment will prepend to the list of values for PATH. But if you are not assigning the PATH in the dependencies nor the profiles I can't image why is it dropping the system path.

**Comment by sturmf** [comment]
Hi, sorry for the late reply. Indeed it was a rough package that I depended on. In that dependency was a 

    self.env_info.path = "xy"

instead of

     self.env_info.path.append("xy")

 Now everything works as expected!
