### ISSUE TITLE
Add Circle CI template for Conan new

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#2359]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

First all, I still love Travis CI this is not an affair 😂 

Circle CI is just another great CI tool, with free build for Open Source projects (only for Linux). Some time ago I made some benchmark between Travis and Circle to know how fast are both two. Circle CI was 40% faster than Travis on my test.

Regards!

**Comment by memsharded** [comment]
Merged, they will be released in conan 1.3
