### ISSUE TITLE
Wrong help description for profile parameter in conan profile

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#2365]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.0.3

In:

```
$ conan profile show -h
usage: conan profile show [-h] profile

positional arguments:
  profile     name of the profile

optional arguments:
  -h, --help  show this help message and exit
```

The profile parameter could be a path to a profile instead of just a name of the profile in the deafult profile folder.

Fix help message for all profile sub-commands that can accept a profile path as profile argument.

**Comment by memsharded** [comment]
For these very simple and obvious fixes, you can directly submit a PR.

**Comment by memsharded** [comment]
I am good if this fix is not tested
