### ISSUE TITLE
Add sudo for install script

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#2367]
Hi!

When I execute `conan new -cilg  foobar/0.1.0` some Travis helpers are generated. Both install.sh and run.sh could be reused for Gitlab and CircleCI. However, both CircleCI and Gitlab run lasote's docker images directly, so it's not required to set `CONAN_USE_DOCKER`.
However, conan user is not root and need to be elevated to install both conan and conan-package-tools. To fix such situation for both CI, I updated my install.sh:

```bash
SUDO=

if [[ "$(uname -s)" == 'Linux' ]]; then
    if [[ -v CIRCLECI ]] || [[ -v GITLAB_CI ]]; then
        SUDO=sudo
    fi
fi
 
$SUDO pip install conan --upgrade
$SUDO pip install conan_package_tools
```

IMO this could be merged into default install.sh to provided more flexibility. 

/cc @solvingj 

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I would need to check first CircleCI and Gitlab and see it running. Do you have some link to take a look? I didn't have the change to try them.

**Comment by uilianries** [comment]
I'll provide ASAP

**Comment by uilianries** [comment]
We no longer need this since Travis is able to install without root and we can use virtualenv for CircleCI.
