### ISSUE TITLE
default_profile fails when profile has `include(other)`

### ISSUE THREAD

**Issue by paxos1977** [conan-io/conan#2369]
Hi, I'm using conan on Ubuntu 16.04, python 2.7, on x86_64. 

I've been testing using `conan config install <URL>` to distribute a shared set of profiles and settings to our group of developers using conan. I ran across a problem with the `default_profile` setting. 

I can change `default_profile` to any profile so long as it does not use the `include(other)` syntax. If I set `default_profile = my_prof` and `my_prof` includes another profile using `include(other)` conan fails with the following error. 

> ERROR: Error reading '/root/.conan/profiles/centos_6' profile: Error parsing the profile text file: coercing to Unicode: need string or buffer, NoneType found

If I leave `default_profile = default` and instead run conan and pass it the profile, e.g. `--profile=centos_6` then the command executes successfully. 

Using an absolute path in the include seems to work, e.g. `include(/home/user/.conan/profiles/other)`, however, I can't use this since every developer has their own `.conan/` directory with different paths. 

I've reproduced the issue with `conan 0.30.3` and with `conan 1.0.3`

**Comment by memsharded** [comment]
Thanks very much for your detailed report. Indeed it seems a bug.
Scheduling it for 1.1, but please me if its severity is high, we could consider doing a patch release.

**Comment by memsharded** [comment]
Released in 1.0.4, please update and check. Thanks!
