### ISSUE TITLE
conanfile_directory not locating conanfile anymore after Conan 1.0

### ISSUE THREAD

**Issue by DTaylorBusiness** [conan-io/conan#2383]
Hello,

I am trying to upgrade our systems to Conan 1.0 but I'm having some trouble with the conanfile_directory changes. 

I am trying to run this command: 
`expected_precommit_file = os.path.join(self.source_folder, '.git/hooks/pre-commit');`

However I get: 
`+ conan install ../ --build=missing --update -s build_type=Debug -s compiler.runtime=MDd`
`ERROR: LeapJear/0.0.7@PROJECT: Error in configure() method, line 54`
`expected_precommit_file = os.path.join(self.source_folder, '.git/hooks/pre-commit');`
`AttributeError: "kvizConan" object has no attribute "source_folder"`

What should I have in place of `self.source_folder`?

**Comment by memsharded** [comment]
Hi!

Can you please elaborate a bit further? I need more context about where are the things. Where is ``expected_precommit_file``? Are you using ``conan install`` by default instead of ``conan create`` to create packages? Who is doing the export?

Please tell and I'll try to help. Thanks!

**Comment by DTaylorBusiness** [comment]
Here's the entire command:

`expected_precommit_file = os.path.join(self.source_folder, '.git/hooks/pre-commit');`
        `if not os.path.isfile(expected_precommit_file):`
            `print(' did not find expected precommit file: ' + expected_precommit_file);`
            `if not "jenkins" in expected_precommit_file:`
                `self.run('pre-commit install');`

Using `conan install`. Sorry I am new to Conan and don't have all the information to give you. Still learning!

**Comment by memsharded** [comment]
But that is not a command :) :)

That looks like some code inside a recipe (a conanfile.py). But I would need the whole recipe (or at least a big portion of it, enough to reproduce it), and the sequence of commands used, like ``conan export``, then ``conan install``, etc.

Don't worry because of learning, we are here to help. Just try to provide this information and we will try to come up with some solution. Cheers!
