### ISSUE TITLE
CMake Helper Enhancement - Implicit Addition of Known CLI Build Flags

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#2384]
A number of users and recipe's have implemented code such as that shown below, in order to pass build flags into CMake via the CLI when using Conan's CMake helper.  After discussion with Conan team, we've established that the flags are already passed in via the `conanbuildinfo.cmake` file and `conan_basic_setup()` steps, which seem to make these build flags redundant.  However, as indicated by @SSE4, some flags need to be passed to CMake via CLI so that they are received and processed by CMake at an earlier stage.  

Thus, this is a feature request to add implicit passing of certain flags by Conan's CMake helper, to CMake, via the CLI.  The example shows the `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` flags, but we should probably check CMake documentation/experts to see if there are any other nuances with other flags. 

Here is the original explanation: 
https://github.com/bincrafters/community/issues/82#issuecomment-359656248

Here is an example of the kind of code we want to eliminate from recipe's:   
```python
        if self.settings.os == 'Linux':
            if self.settings.arch == 'x86':
                cmake.definitions['CMAKE_C_FLAGS'] = '-m32'
                cmake.definitions['CMAKE_CXX_FLAGS'] = '-m32'
            elif self.settings.arch == 'x86_64':
                cmake.definitions['CMAKE_C_FLAGS'] = '-m64'
                cmake.definitions['CMAKE_CXX_FLAGS'] = '-m64'
```

Here is the recipe this came from: 
https://github.com/bincrafters/conan-sdl2/blob/testing/2.0.7/conanfile.py#L158

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ X I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
> However, as indicated by @SSE4, some flags need to be passed to CMake via CLI so that they are received and processed by CMake at an earlier stage.

Wow, this could be unfortunate and is unexpected. Any reference or concrete example I could have a look and learn more about this behavior? Want to evaluate the extent and impact of this issue. Thanks!

**Comment by solvingj** [comment]
In his explanation, he gives the following concrete example to demonstrate: 

> now imagine you have the following simple CMakeLists.txt:
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32")

message(STATUS "CMAKE_SIZEOF_VOID_P ${CMAKE_SIZEOF_VOID_P}")
message(STATUS "CMAKE_LIBRARY_ARCHITECTURE ${CMAKE_LIBRARY_ARCHITECTURE}")
```
> and executing just cmake will result in:
```
CMAKE_SIZEOF_VOID_P 8
CMAKE_LIBRARY_ARCHITECTURE
```
> which is not something we expect, obviously.  however, if you execute it like : 
```
cmake -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m64
```
the output is
```
CMAKE_SIZEOF_VOID_P 4
CMAKE_LIBRARY_ARCHITECTURE x86_64-linux-gnu
same result for CFLAGS=-m32 CXXFLAGS=-m32 cmake
```

**Comment by memsharded** [comment]
Ok, now it is more clear, many thanks

**Comment by lasote** [comment]
I see it as an `opt-in` parameter in the CMake() build helper. To not break current behavior.

**Comment by SSE4** [comment]
I agree. I can write PR for that, plus to fix other issues with -m32/-m64 flags altogether.
