### ISSUE TITLE
Can not use a list for Conanfile.default_options

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2396]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

version 1.0.2

```py
from conans import ConanFile, CMake, tools


class FooConan(ConanFile):
    name = "Foo"
    version = "1.0"
    license = "<Put the package license here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of Foo here>"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = ["shared=False"]
```

Results in an error (and not the most helpful of errors, either):

```
david@balrog:~$ conan install .
ERROR: /home/david/conanfile.py: Error while initializing options. too many values to unpack (expected 2)
david@balrog:~$ 
```

The problem lies on line 150 of `conans/model/options.py` where you check if the default options are type `tuple` but ignore type `list`. When that if-statement resolves as false, you jump down to the for-loop on line 158 which assumes it is a key-value pair. I would change line 150 to `if isinstance(values, tuple) or isinstance(values, list)`.

**Comment by memsharded** [comment]
Thanks for reporting this!
The truth is that it was never intended that it was a list, but I see no reason it couldn't be one. As you have already traced the code, don't you want to submit a PR yourself with the changes to get attribution?

Building a test for it should be also relatively straightforward, find some simple test copy it and change it to add defaul_options as list.

**Comment by DavidZemon** [comment]
Oohhhh. I see why it was it is the way it is. Right now, you support an incoming type of `List[Set(str, str)]`, such as `[('name1', 'value1'), ('name2', 'value2')]`.

Unfortunately... I can't recall where in the docs I saw that `list` was an acceptable input type so I can't even submit a pull request with updated docs. Oh well. At very least, I now know how to fix my recipe to work correctly without having to do `default_options = tuple(default_options)`.

**Comment by memsharded** [comment]
Thats right! I forgot about it. 
Most likely such format is there for historical reasons and backward compat, and it is not documented because it is a bit verbose and more difficult to read. Might be eventually deprecated too (though should wait until 2.0), so I guess better not document it and attach to the current ``default_options="opt=value", `` tuple syntax

**Comment by DavidZemon** [comment]
Okay, thanks for the recommendation. I'll stick with a cast to `tuple`. For reference, here is my use case. This is used for compiling bash, an AutoTools app.

```py
default_on_features = [
    'alias',
    'arith_for_command',
    'array_variables',
    'bang_history',
    'brace_expansion',
    'command_timing',
    'cond_command',
    'cond_regexp',
    'debugger',
    'directory_stack',
    'disabled_builtins',
    'dparen_arithmetic',
    'extended_glob',
    'help_builtin',
    'history',
    'job_control',
    'multibyte',
    'net_redirections',
    'process_substitution',
    'progcomp',
    'prompt_string_decoding',
    'readline',
    'restricted',
    'select',
    'separate_helpfiles',
    'single_help_strings',
    'strict_posix_default',
    'usg_echo_default',
    'xpg_echo_default',
    'mem_scramble',
    'profiling',
    'static_link'
]
default_off_features = [
    'largefile',
    'nls',
    'rpath'
]
optional_packages = [
    'with_lispdir',
    'with_afs',
    'with_bash_malloc',
    'with_curses',
    'with_installed_readline',
    'with_purecov',
    'with_purify',
    'with_gnu_ld'
]

options = {feature: [True, False] for feature in default_on_features + default_off_features + optional_packages}

default_options = ['%s=True' % feature for feature in default_on_features]
default_options += ['%s=False' % feature for feature in default_off_features]
default_options += ['%s=False' % package for package in optional_packages]
default_options = tuple(default_options)
```

I then build my argument list in the `build()` method like so:

```py
for feature in self.default_on_features:
    if not self.options.__getitem__(feature):
        feature_name = feature.replace('_', '-')
        args.append('--disable-' + feature_name)
for feature in self.default_off_features:
    if self.options.__getitem__(feature):
        feature_name = feature.replace('_', '-')
        args.append('--enable-' + feature_name)
for package in self.optional_packages:
    optional = '' if self.options.__getitem__(package) else 'out'
    package_name = package.replace('_', '-')
    args.append('--with{0}-{1}'.format(optional, package_name))
```

**Comment by memsharded** [comment]
Yes, in your case due to the logic of your options, I think that is the cleanest approach.

So I'd say that we could close this issue now, or do you have any further question? Thanks!

**Comment by DavidZemon** [comment]
Nope, that'll do it. Thanks for your help again
