### ISSUE TITLE
User names with space are not accepted (but are accepted when specified on conan user command-line)

### ISSUE THREAD

**Issue by EFraim** [conan-io/conan#2399]
On conan 1.0.3, when doing conan upload against an unauthenticated remote, the system asks for the user name.
Since LDAP authentication is specified, the user name happens to contain a whitespace. The command rejects the user name as invalid  without even asking for the password.
As a workaround 'conan user -r &lt;remote&gt; "&lt;user name with space&gt;"' can be invoked

**Comment by EFraim** [comment]
You are indeed correct that the failure is in the interactive user prompt
by conan upload. The role of LDAP is limited to it being the cause of me
having to deal with spaces in my user names.

On Jan 30, 2018 6:48 PM, "James" <notifications@github.com> wrote:

I am not sure if I understood about the role of LDAP here. What server are
you using? From the conan client to the server, the authentication is JWT
based, so LDAP is restricted to the server and doesn't play a role here,
unless I am missing something.

So the failure is when conan ask interactively for a username in a conan
upload, right? Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conan-io/conan/issues/2399#issuecomment-361656868>, or mute
the thread

**Comment by memsharded** [comment]
This was fixed some time, ago, adding a test in 2.0 that checks it: https://github.com/conan-io/conan/pull/13337
