### ISSUE TITLE
package_info based on build / package output

### ISSUE THREAD

**Issue by trevex** [conan-io/conan#24]
I recently tried to provide a conanfile for [GLFW3](http://www.glfw.org/), but ran into quite a lot of trouble
with the `package_info` function, because it runs before any other function. Therefore changing the `cpp_info` based on the build or package output seems impossible.

GLFW3 depends on a variety of platform-specific dependencies while on Windows and OSX these usually stay the same, there can be differences between distros, so `pkg-config` is the common way to resolve these dependencies. So I tried running package config with a custom `PKG_CONFIG_PATH` to pickup the outputted `glfw3.pc` by the build process, but `package_info` is run before `build`.

The related file: https://gist.github.com/trevex/e34cf5dc390909488b94

Is there a way to incorporate the capability to change the `cpp_info` after the `build` and/or `package` pass? Also an alternative to `self.run` that returns the stdout and exit-code would be handy. Another issue was that the working directory of the `package_info` path is unclear, is it run in the package directory or source?

The support of "output"-based `package-info` would benefit other more complex libraries as well, e.g. GUI libraries (wxwidges et cetera).

**Comment by memsharded** [comment]
Hi @trevex, thanks very much for trying out!

The ```package_info``` method can actually run without building or packaging anything. If a precompiled binary is available, it will be retrieved, and the ```package_info``` is called to obtain the information for consumers, but typically the user does not want to re-build (nor re-package) the binary package. So, by definition, it has to be decoupled from the build and package steps.

A possibility would be to run the ```pkg-config``` it in the build step, then generate a file, include that file in the package, and then try to read it in the ```package_info``` method. But you are right that for the package_info the current directory is not set to the package one, we should have a look at this issue. Surely it should run in the "package" folder, as the build folder might not be there if just consuming a binary package.

I agree, the alternative to  ```self.run() ``` that captures output might be useful. It is something not very straightforward, (I have done it in the past, doing it cross-platform can be tricky), but can be done. I think it deserves its own issue.

I suggest in the meanwhile to do a manual (at least for 1 distro) configuration of the flags, just have a look at the file, and write the flags in the conanfile. So we can have a working GLFW package (I have used glfw and love it) soon, and then iterate and improve it as soon as issues are addressed and conan evolves and improves.

**Comment by lasote** [comment]
We already enable the output for self.run() and **self.cpp_info.rootpath** is set with the package folder path. You should be able to write or read a previously exported *.pc file. 
Open an issue if something is still wrong!

Thanks
