### ISSUE TITLE
Copy directory links also 

### ISSUE THREAD

**Issue by mathieu** [conan-io/conan#240]
Symbolic links on files are not preserved through conan packages (see #204), instead hard copies are created. Although this is not the case with symbolic links on directories they are just ignored.

**Comment by mathieu** [comment]
MR #241 been merged I consider this issue closed

**Comment by memsharded** [comment]
Yes, thanks very much @marache . It will be released in 0.9, so if after the release you find some problem, just re-open it. Cheers!
