### ISSUE TITLE
[question] Dealing with rpm/deb-style Version-Release schemes

### ISSUE THREAD

**Issue by bc-lee** [conan-io/conan#2401]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] Questions and support requests are very welcome.
- [x] Use the [question] or [bug] tags in the title.
- [x] Try to explain the motivation, what are you trying to do, what is the pain to try to solve.
- [x] What do you expect from Conan.

# Motivation
To avoiding outdated and/or broken packages, I'd like to bump every version(aka Release in deb/rpm-style version) when I release my `conanfile.py` to VCS, and alias each build to it's upstream version.

For example, 

- First build of `zlib/1.2.11` would be `zlib/1.2.11-0@user/channel`, which is aliased to `zlib/1.2.11@user/channel`
- Second build would be `zlib/1.2.11-1@user/channel`, which is aliased to `zlib/1.2.11@user/channel`, which override previous recipe.

Then, package consumers can use this package with several ways:
- Fix their dependency to specific version(like `equirements = ("zlib/1.2.11-1@user/channel",)`) so they can promise that it won't break anything. (I assume every required pre-built binaries are given)
- Relax version requirements so dependent packages will be updated if some packages are updated.

This is working pretty well, until I use range-based version scheme.

# Problem
For some requirements using both fixed version and range-based version, it won't work.

For example:  `requirements = ("zlib/1.2.11-1@user/channel",)` and `requirements = ("zlib/[>=1.2.11, <1.2.12]@user/channel",)` have conflicts because `1.2.11-1` is treated as pre-release of `1.2.11`, as denoted in [semver](https://semver.org/#spec-item-9). 
I tried to use build metadata(`+`) instead of prerelease(`-`), but it won't work beacuse python-semver ignores build metadata.
Possible workaround is to specify release in requirements, like `requirements = ("zlib/[>=1.2.11-0, <1.2.12-0]@user/channel",)` but I feels it is somewhat ugly.

Any suggestions for such work-flow?

**Comment by memsharded** [comment]
Please check this thread: https://github.com/conan-io/conan/issues/798

I think they are very related. The issue with "-" and "+" is that we shouldn't change their behavior as they are already defined in semver, it would be quite confusing and fragile. 

Maybe the way to go would be some kind of "extension" to semver like ``1.2.3.4``, ``1.2.3#4``, but there are also counter arguments to it. So maybe this issue can be closed and continue conversation in https://github.com/conan-io/conan/issues/798?

**Comment by bc-lee** [comment]
Understood. I'll watch #798. Thanks!
