### ISSUE TITLE
conanpath.bat is not removed when uninstalling conan via Windows installer

### ISSUE THREAD

**Issue by mmatrosov** [conan-io/conan#2409]
1. Install conan as Windows x64 installer
2. Uninstall it
3. See how file conan\conanpath.bat is still present

**Comment by memsharded** [comment]
You are right. 
I have tried, and I can remove it.
However, the folder C:/Program Files.../Conan/conan is kept there. 
Innosetup advises against removing the app folders, not sure why. Would it be a problem if the folder (empty) remains there?

**Comment by mmatrosov** [comment]
Usually when you uninstall an app on Windows, corresponding folder is completely deleted from Program Files. The app might left some settings in user data though.

**Comment by memsharded** [comment]
Ok, no problem. There is no data in the installation folder, as absolutely everything conan related is stored in the user cache (``<userhome>/.conan``).

I have added a complete removal of the C:/Program Files/Conan folder, it seems to work well. It will be available in next release (1.1. or sooner if we do a patch release).

Many thanks for your feedback.

**Comment by mmatrosov** [comment]
Cool, thanks!
