### ISSUE TITLE
'install_folder' attribute is not always set

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2413]
To reproduce, take https://github.com/memsharded/conan-hello example with one addition:
```python
    def package(self):
        print("self.source_folder:", self.source_folder)
        print("self.build_folder:", self.build_folder)
        print("self.install_folder:", self.install_folder)
        ...
```
now package it:
```
conan create . dbely/testing
```
everything goes well, with the output
```
Hello/0.1@dbely/testing: Calling package()
self.source_folder: C:\Users\dbely\.conan\data\Hello\0.1\dbely\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
self.build_folder: C:\Users\dbely\.conan\data\Hello\0.1\dbely\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
self.install_folder: C:\Users\dbely\.conan\data\Hello\0.1\dbely\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
```
Now do it step by step:
```
conan source .
conan install .
conan build .
conan package .
```
All the commands succeed except the last one:
```
PROJECT: Calling package()
self.source_folder: C:\Users\dbely\conan\conan-hello.git
self.build_folder: C:\Users\dbely\conan\conan-hello.git
ERROR: Hello/0.1@PROJECT: Error in package() method, line 21
        print("self.install_folder:", self.install_folder)
        AttributeError: 'HelloConan' object has no attribute 'install_folder'
```

**Comment by memsharded** [comment]
I think there was some reason for the ``install_`folder`` not to be defined inside the ``package()`` method, most likely that it might have no sense at all for the ``conan export-pkg`` command. And in the conan cache, it is useless, as it should always be equal to the ``build_folder``.

I will be checking with @lasote about it, thanks for reporting.

**Comment by memsharded** [comment]
Yes, this is true, it is a bit weird, specially when http://docs.conan.io/en/latest/reference/commands/development/package.html defines this argument with a default. I think this can be considered a bug, thanks for reporting!
