### ISSUE TITLE
--update option should not ignore local packages

### ISSUE THREAD

**Issue by jrickman** [conan-io/conan#2420]
conan 1.0.4 on Windows 7

If `--update` option is given to `conan install`, the current behavior skips local package search.

I believe this is surprising behavior. `--update` should just change the priority order from [local, remote] to [remote, local].

Use case: if I am making changes to multiple packages, I may want to build them locally (in a separate user/channel) and test them before pushing them to the server. If I have package dependencies, and I want to pull the latest from the server, I may want to issue the following:

`conan install .. --update --profile=centos_6`

Right now, that install fails because it does not find my local user/channel packages.

This is because the local searcher is only set if `update` is false.

manager.py:
```python
    def _get_graph_builder(self, loader, update, remote_proxy):
        local_search = None if update else self._search_manager
        resolver = RequireResolver(self._user_io.out, local_search, remote_proxy)
        # ...
```

I think `local_search` should be set unconditionally. RequireResolver should be updated to change the search order depending on the `update` value.

**Comment by memsharded** [comment]
I think some important info is missing here. I guess you are referring to usage of version-ranges. I would say local cache is considered when using --update too.

**Comment by jrickman** [comment]
You're right, I should've mentioned that version ranges are being used.

**Comment by memsharded** [comment]
The current semantics for --update for version ranges are "try to resolve the version range" in remotes, because users wanted to use it to effectively find newer versions upstream. Which I agree it is a different behavior wrt to fixed version dependencies, and probably not the best.

It might be complex to change this behavior without breaking, but lets have a look to see what can be done.

**Comment by paxos1977** [comment]
When using version ranges, how should you invoke `conan install` to pick up only packages in your cache? E.g. perhaps you want to test locally modified packages using `conan create`. 

`conan install` seems to check the remotes to see what the latest package version is even when `--update` is omitted, and if that exact version doesn't exist in your cache, it errors out.

**Comment by jrickman** [comment]
@memsharded I can issue a pull request with proposed changes if that would help. It might be useful to discuss a tangible change instead of use case semantics.

**Comment by lasote** [comment]
@jrickman sure, any help to focus the problem is welcomed.

**Comment by memsharded** [comment]
> conan install seems to check the remotes to see what the latest package version is even when --update is omitted, and if that exact version doesn't exist in your cache, it errors out.

I am going to add some test for this, thanks for telling.
