### ISSUE TITLE
Conan pip install fails with virtual env on Debian 8 during isort setup

### ISSUE THREAD

**Issue by berndherrmann** [conan-io/conan#2421]
Since about 2 days we are facing an issue during a standard pip conan install with virtual env under Debian 8 (MacOS and Windows are still fine). I am not sure if the problem is Debian or Linux specific.

It always fails during the isort install with the following error: "error in isort setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers"

I first thought it came with the update to 1.0.4, but also using the old 1.0.3 showed the same issue suddenly.

Is there a known problem with the isort package?

Since the issue came up I can also see the following line in the log: "Running setup.py (path:/tmp/pip-build-HKCjTO/isort/setup.py) egg_info for package isort". This was not there before.

I have attached a log with the printouts.

[conan_isort_error.txt](https://github.com/conan-io/conan/files/1690443/conan_isort_error.txt)

**Comment by memsharded** [comment]
Hi @berndherrmann 

Thanks very much for reporting this. It seems isort has released 2 days ago new packages: https://github.com/timothycrosley/isort/releases

I have tried to install in a clean env in Ubuntu 16, working fine. But it is true that it is using the latest 4.3.1:

```
 Downloading isort-4.3.1-py2-none-any.whl (45kB)
```

I would try to force a previous version of isort in your environment, then conan, please tell me how it goes. Then, I think it is worth to report it to the isort repo.

**Comment by berndherrmann** [comment]
Hi @memsharded 

I checked the isort history today in the morning and I saw that they already pushed a fix shortly afterwards.

I can confirm that it is working fine again with 4.3.1. It was broken with 4.3.0.

Many thanks for looking into it. All fine now.

**Comment by memsharded** [comment]
Excellent!

I guess this can be closed now. 
Many thanks to you for following up and reporting.
