### ISSUE TITLE
Service Error when searching package with full ref

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#2422]
To help us debug your issue please explain:

Search Bincrafters repository on bintray as shown here: 
```
conan remote list
remote0: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
```
```
conan search boost_python/1.66.0@bincrafters/stabl* -r remote0
Existing package recipes:
boost_python/1.66.0@bincrafters/stable
```
```
conan search boost_python/1.66.0@bincrafters/stable -r remote0
ERROR: Service Error. [Remote: remote0]
```
```
conan search boost_python/1.66.0@bincrafters/stable -r remote0
ERROR: Service Error. [Remote: remote0]
```

I thought maybe the package got corrupted, so i tried uploading manually from my local machine. The upload succeeded, but still get service error when searching. 

```
conan upload boost_python* -r remote0 --f
Are you sure you want to upload 'boost_python/1.66.0@bincrafters/stable'? (yes/no): y
Uploading boost_python/1.66.0@bincrafters/stable
Uploading conanmanifest.txt
[==================================================] 103B/103B
Uploading conanfile.py
[==================================================] 5.6KB/5.6KB
Uploading conan_export.tgz
[==================================================] 769B/769B
Uploaded conan recipe 'boost_python/1.66.0@bincrafters/stable' to 'remote0': https://api.bintray.com/conan/bincrafters/public-conan

conan search boost_python/1.66.0@bincrafters/stable -r remote0
ERROR: Service Error. [Remote: remote0]
```
Oddly, has no problem installing the package, just searching: 
```
conan install boost_python/1.66.0@bincrafters/stable
boost_python/1.66.0@bincrafters/stable: Not found in local cache, looking in remotes...
boost_python/1.66.0@bincrafters/stable: Trying with 'remote0'...
Downloading conanmanifest.txt
[==================================================] 103B/103B
Downloading conanfile.py
[==================================================] 5.6KB/5.6KB
Downloading conan_export.tgz
[==================================================] 769B/769B
boost_config/1.66.0@bincrafters/stable requirement boost_package_tools/1.66.0@bincrafters/testing overriden by boost_bind/1.66.0@bincrafters/stable to boost_package_tools/1.66.0@bincrafters/stable
boost_predef/1.66.0@bincrafters/stable requirement boost_package_tools/1.66.0@bincrafters/testing overriden by boost_level5group/1.66.0@bincrafters/stable to boost_package_tools/1.66.0@bincrafters/stable
boost_python/1.66.0@bincrafters/stable: Installing package
```
And just to make sure the search i did is supposed to work, I validated successfully with testing branch. 
```
conan search boost_python/1.66.0@bincrafters/testing
Existing packages for recipe boost_python/1.66.0@bincrafters/testing:

    Package_ID: 25e0ab717beffd039792e4244ed5d27719511eb8
        [options]
            python: python-
            shared: False
```

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, there is something weird with this package, I have reproduced it.
It doesn't fail either for other repos:

```
# works OK
$ conan search boost/1.66.0@conan/stable -r=conan-center
```

**Comment by memsharded** [comment]
Question: is it the only package that happens? All the other packages? Have you tried not to just reupload, but completely remove it (you  might need to do it in the Web, client removal might fail), then re-upload it?

**Comment by solvingj** [comment]
I meant to post that conan remove throws same service error.  I think delete from UI will probably work and fix it.

Only tested this lib, will test others shortly.

I will script the conan search across all the boosts (easy for me) when I get home.  Will be interesting.

**Comment by solvingj** [comment]
It seems it was only this one packages.  Deleting via UI and re-building (and re-uploading) fixed the issue. Do you want me to keep open to track a potential bug, or just close it because it will likely be impossible to reproduce?

**Comment by memsharded** [comment]
It seems this is going to be impossible to reproduce right now. I am closing the issue, please re-open or open a new one if it comes back.

**Comment by ovidiub13** [comment]
I think this error is back:
```
boost/1.66.0@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt

Downloading conanfile.py

bzip2/1.0.6@conan/stable: Not found in local cache, looking in remotes...
bzip2/1.0.6@conan/stable: Trying with 'mvt-devel'...
bzip2/1.0.6@conan/stable: Trying with 'conan-center'...
ERROR: Service Error. [Remote: conan-center]```

I'm experiencing this with Conan `1.0.4`, running inside a docker container.

**Comment by ovidiub13** [comment]
I get the same error when using `boost/1.67.0@conan/stable`.

**Comment by danimtb** [comment]
With Conan 1.3.1

This is working fine on my end (Windows)
```
$ conan search boost/1.66.0@conan/stable -r conan-center
```

However, some other searchs report this:
```
$ conan search libcurl/7.56.1@bincrafters/stable -r bincrafters
ERROR: Service Error. [Remote: bincrafters]
...
$ conan search json-c/0.13.1@bincrafters/stable -r bincrafters
ERROR: Service Error. [Remote: bincrafters]
```

Other searches with ``bincrafters`` remote work well, such as `$ conan search json-c/0.13.1@bincrafters/stable -r bincrafters`

**Comment by odormond** [comment]
With conan 1.5.2 I'm getting the same error with Qt:
```
$ conan search -r bincrafters Qt/5.6.3@bincrafters/stable
ERROR: Service Error. [Remote: bincrafters]
```

**Comment by danimtb** [comment]
Checking that @odormond. Thanks for reporting!

**Comment by danimtb** [comment]
Hi @odormond,
Seems there is an issue in the search of Bintray for packages with options without value.

The Qt recipe is declaring "config=" (without value) in the ``default_options`` and it is causing the service error.

I have just opened an issue to block this usage #3232 and I will work with bincrafters to fix the issue with Qt.

Thanks again for reporting!
