### ISSUE TITLE
conan_server (as prepackaged with pip) per default runs on "0.0.0.0:9300" instead of "localhost:9300" or as specified in server.conf

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#2429]
To help us debug your issue please explain:

- [x ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I am using Conan 1.0.4 on a Windows Operating system.
I am currently evaluating to use Conan In-House, and wanted to get started using the prepackaged `conan_server`, that comes with the pip installation.

When I run the conan server after a clean installation, it runs on "0.0.0.0:9300" instead of (as expected) localhost or whatever is specified in the server.conf file.

![image](https://user-images.githubusercontent.com/13848742/35808888-a54d4d3a-0a87-11e8-81f2-91e87526869a.png)

In the server_launcher.py this address seems to be hardcoded:
https://github.com/conan-io/conan/blob/fb3d81a887cfc057252f81902f26c2c577a5fa96/conans/server/server_launcher.py#L51

This results in the problem, that I cannot upload anything to that "testserver"
![image](https://user-images.githubusercontent.com/13848742/35809142-16481934-0a88-11e8-83ff-54920dab0b7f.png)

Calling `launcher.launch()` in `server_launcher.py` without any arguments launches the server on localhost, but I guess it should still take whatever is provieded by the `server.conf` file.

**Comment by memsharded** [comment]
Please try to define ``localhost:9300`` as the remote in your client, not 0.0.0.0

I will have a look to the issue of not changing the IP if changed in server.conf

**Comment by KerstinKeller** [comment]
Ah thanks for your immediate help, actually defining `localhost:9300` with the client worked (as it is clearly stated in the documentation). I guess I got confused with the server output, and used that when configuring my local remote.

However, from what I can tell from the code, the ConanServer / ServerLauncher really do not respect `host_name` as specified in `server.conf`, but at least for my testing purposes, that is not an issue.

**Comment by memsharded** [comment]
No problem :)

> However, from what I can tell from the code, the ConanServer / ServerLauncher really do not respect host_name as specified in server.conf, but at least for my testing purposes, that is not an issue.

host_name is for a different purpose, not sure if http://docs.conan.io/en/latest/uploading_packages/running_your_server.html#server-parameters makes it clear. It is something that is necessary to define the file transfers end-point, that might be different to the main logic endpoint. But it is not a re-definition of the endpoint of the conan server, maybe check the explanation there for ``public_port``, that might help.
