### ISSUE TITLE
Conan-center website has broken sorting by date

### ISSUE THREAD

**Issue by ArekPiekarz** [conan-io/conan#2433]
### Summary:
Sorting by date gives badly sorted results on the conan-center website.

### Steps to reproduce:
1. Go to https://bintray.com/conan/conan-center
2. Click on "Sorted by priority"
3. Choose "Sorted by date"

### Expected result:
Packages should be sorted by date, either in ascending or descending order.

### Actual result:
Packages are sorted in a strange order. Assuming it should be "newest first", we have:
1. LZ4 - no date  <-- assume out of order
2. trompeloeil - Oct 23 2017  <-- assume ok
3. Catch - Nov 4 2017  <-- out of order, newer
4. c-blosc - Feb 3 2018  <-- out of order, newer
5. range-v3 - Jun 30 2017  <-- ok, older
6. strawberry-perl - Jun 22 2017  <-- ok, older
7. jsoncpp - Jan 12 2018  <-- out of order, newer
8. glm - Aug 17 2017  <-- ok, older

...and so on.

### Environment:
OS: Windows 10 x64
Browser: Chrome 64.0.3282.140 64-bit

### Additional info
I'm sorry if this is a wrong place to submit it, I did not find a bugtracker for Bintray.
Note that the sorting by date works correctly on Bincrafters page - https://bintray.com/bincrafters/public-conan - so maybe it is a problem with configuration, not  the algorithm itself.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
Hi @ArekPiekarz, thank you for reporting!

Yes, you are right with the sorting of the packages. I have also experienced this issue but I dont know we it is working fine in the bincrafters repo.
Don't worry to report this here, it is a good way to concetrate all the conan related issues. We'll report to the bintray guys and look into this.

Thanks again 😄

**Comment by memsharded** [comment]
I would say that the origin of this issue is that conan-center is specialy, because basically contains links to other repos packages, and the meta-information might be not matching or something.

**Comment by memsharded** [comment]
Bintray is being sunset https://blog.conan.io/2021/02/05/JFrog-announces-sunset-bintray.html

https://conan.io/center/ ConanCenter is the public community central repository.
