### ISSUE TITLE
Implement checker for Visual Studio runtime

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2436]
Unfortunately it still happens from time to time and it is difficult to detect and workaround the different build systems.

Have a look if calling dumpbin could check this thing, and report accordingly, specially to package creators.

**Comment by memsharded** [comment]
Possibly an  idea would be a ``conan verify`` command (experimental) that checks things without messing with existing flow.

**Comment by danimtb** [comment]
I think this will follow the hook implementation and it is duplicate of #1115
