### ISSUE TITLE
Easy utility for creating a git clone from the local filesystem as a way of exporting sources

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2438]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

So I'm thinking, what if I could write some code like this:

```py
from conans import ConanFile, tools

class MyRecipe(ConanFile):
  exports_sources = tools.LocalGitClone()
```

And that little bit of magic would do something like:

```sh
cd ${HOME}/.conan/data/foo/1.0/bar/baz
path=$(dirname ${CONAN_RECIPE})
if git -C $path diff-index --quiet HEAD -- ; then
  echo 'Please commit your changes before running `conan create`'
  exit 1
fi
branch=$(git -C conan-firmbuild rev-parse --abbrev-ref HEAD)
git clone file://${path}/.git source -b ${branch}
rm -rf source/.git
```

No, it wouldn't work for every user in the world, but it would work for A LOT of users and, so long as its limitations were well documented, I think it could be really useful.

The reason I want this is because it's impossible to exclude every binary folder that a user may have chosen. I might write something like `exports_sources = '*', '!bin/'` in an attempt to exclude the `bin` directory.... but what if someone builds my project in a `build` directory and then runs `conan create`? Sad day.

I recognize that `exports_sources = tools.LocalGitClone()` wouldn't really be the right way to do it at all. Perhaps you can come up with something else, or perhaps this requires an API enhancement (a new class variable on the `ConanFile` class? I'll let you decide that. But this would be really nice to have.

**Comment by lasote** [comment]
I think I understand, but doing a checkout of the local repo to finally export the sources it is a bit confusing. The target is to take only the committed files, right? Could be a possibility to be able to parse a .gitignore file? Eventually, the developers will have excluded all the "bin" dirs there.
I'm not sure, I have used the `exports_sources` with some packages and at the end, you need to exclude many other things like docs, examples etc.

**Comment by memsharded** [comment]
Related: https://github.com/conan-io/conan/issues/2371

**Comment by DavidZemon** [comment]
> developers will have excluded all the "bin" dirs there

Parsing the `.gitignore` file would be really cool too, and I almost put something in my original comment about that, but I thought it was a (slightly) different feature request. What it comes down to is that I'd like to completely skip the pain of fleshing out the `.gitignore` file with all the developers' different `bin` directory names and just use git repo itself. Seems more straightforward to me (maybe I'm crazy?).

> I have used the exports_sources with some packages and at the end, you need to exclude many other things like docs, examples etc.

Seems unnecessary to me. I guess I understand where you're coming from: Conan doesn't need those things and it only makes the Conan package more bloated. However, I would much rather just make the Conan package more bloated and export the whole thing.

**Comment by jgsogo** [comment]
I think this issue is already covered with the SCM feature: https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm

Please, @DavidZemon, if you still have this pain, let us know if the linked feature should do the work, maybe there is something in this pull-request that is not covered with the SCM.

Thansk a lot.

Note.- _I'm labelling it as `obsolete` just because I think that `SCM` is the solution_

**Comment by DavidZemon** [comment]
I haven't tried the SCM feature yet, but I did start reviewing it after the revision feature went into public beta. It does, in fact, appear to offer exactly the features I was talking about for with this ticket. I'd say it's safe to close this ticket and, if I do discover something missing with the SCM feature, I can open a new ticket requesting that specific change.

**Comment by jgsogo** [comment]
Thanks! We will very pleased to hear your feedback about the SCM feature.
