### ISSUE TITLE
CMake build wrapper should set PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by theirix** [conan-io/conan#2444]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan version 1.0.4 or master

A lot of cmake scripts use both `find_package` (`FindFoo.cmake`-based) and `pkg_check_modules` (`pkg-config`-based). CMake build wrapper should automatically provide `PKG_CONFIG_PATH` env var set to build directory or to recipe-provided paths. Exact same behavior is seen in `AutoToolsBuildEnviroment` or `Meson`. `CMake` should not be an exception.

**Comment by lasote** [comment]
I agree, but I think we cannot enable it by default right now. It could be breaking behavior if it finds `pc` files that previously were not located. Probably we have to add a parameter defaulted to False to activate it and wait to the 2.0 to default that parameter to True?
