### ISSUE TITLE
Adding a -q option to conan upload would help

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2445]
Hello,

I'm using Conan 1.0.4

I use the `conan remove -q` option a lot, and I would like to have the same feature when uploading packages.

There is the `-p` option, but specifying every package ID is tedious, to say the least.

It there any blocking issue preventing the same option for `conan upload`?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by joechrisellis** [comment]
Hey!

I'm currently working on this. Don't have an ETA, just thought I'd let you know there's progress. 👍 

Cheers!

**Comment by jgsogo** [comment]
Ready to release: https://github.com/conan-io/conan/pull/3377.
