### ISSUE TITLE
Removing config section via API not effective during subsequent calls

### ISSUE THREAD

**Issue by moltob** [conan-io/conan#2446]
Environment:

* Windows 7/10 Enterprise 64 Bit
* Python 3.6.3
* Conan 1.0.4 (installed from PyPI)

I am using the API class and noticed that the sequence of the following call leads to inconsistent behavior:

```python
conan, _, _ = conan_api.ConanAPIV1.factory()
conan.config_rm('proxies')

# this still prints the proxies section, but it probably should not:
_logger.info(conan._client_cache._conan_config._sections)

# this fails due to incorrect setting of proxies:
conan.user(name=..., password=..., remote=...)
```

On disk the section is actually already gone, but apparently the internal cache is not properly refreshed. As a workaround I can simply re-instantiate the API object right after the ``config_rm`` call.

**Comment by memsharded** [comment]
Yes, it seems a bug, thanks for reporting.
Most of conan behavior is "stateless" in the sense that every command dies after execution and internal state dissapears, so this usage via the API is very non-tested (and this is why it is not documented). But bug reports over the API are still great to mature it, so please keep them coming :)

I think it might not be very difficult to fix, lets aim to do it for 1.1, we are a bit late, might be delayed to 1.2.
