### ISSUE TITLE
Changing Packages and their dependencies between namespaces

### ISSUE THREAD

**Issue by luckielordie** [conan-io/conan#2449]
Is there a way in Conan to essentially fork packages and change the namespace of a package? For example, taking the `Poco/1.8.0.1@pocoproject/stable` package and changing it to `Poco/1.8.0.1@luckielordie/stable` and then having the dependencies of `Poco/1.8.0.1` also having their namespaces changed to `luckielordie/stable`?

A little more info as to why I would like this. I want to keep a consistent naming convention for the dependencies that I was using. My local Conan_Server is being kept as a controlled Repo for other project members that contains only packages that we have deemed ready to be in the repository.

**Comment by memsharded** [comment]
You have the ``conan copy`` command, that will allow to change user/channel for a given package. But that will not change the internal dependencies user/channel, and it is not transitive.

There are some users that make their dependencies transitive over user/channel, doing something like:
```python
def requirements(self):
     self.requires("Pkg/version@%s/%s" % (self.user, self.channel))
```
But that won't work directly over existing OSS packages in conan-center that are not prepared for that use case.

I'd recommend to fork the package recipes and build your package binaries, specially if you are going to use them in production within your team, and take control over your binaries.

**Comment by luckielordie** [comment]
Thanks @memsharded. Grateful for the always swift replies!

**Comment by memsharded** [comment]
You are welcome! Please close the issue if you don't need further action from us. Thanks!
