### ISSUE TITLE
How do I get the version of a resolved dependency?

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2451]
I need to know what version is of a dependency has been selected. I was expecting it to be available via `self.deps_cpp_info['linux']`, but it has no attribute 'version'. Am I able to access this information from the `build()` and `package()` methods?

**Comment by memsharded** [comment]
Weird, it is defined in ``CppInfo`` structure, at least it should be None, but it exists. 
Maybe it is not being assigned for build_requires, do you have something that I can reproduce, please? Thanks!

**Comment by DavidZemon** [comment]
Oh! Good point. I was getting `AttributeError: 'NoneType' object has no attribute 'split'` and was in the mindset that that error meant the `version` attribute didn't exist. But indeed, that error means the `version` attribute _does_ exist and is set to the value `None`. Still doesn't help me, but you're right. :)

```py
from conans import ConanFile, CMake, tools


class FooConan(ConanFile):
    requires = 'bzip2/[>1.0.0]@conan/stable', 'libbson/1.9.2@theirix/testing'
    build_requires = 'zlib/[>1.0.0]@conan/stable', 'Poco/1.8.1@pocoproject/stable'

    def build(self):
        print('Requires, exact version:       ' + str(self.deps_cpp_info['libbson'].version))
        print('Requires, version range:       ' + str(self.deps_cpp_info['bzip2'].version))
        print('Build requires, exact version: ' + str(self.deps_cpp_info['Poco'].version))
        print('Build requires, version range: ' + str(self.deps_cpp_info['zlib'].version))
```

produces the following output:

```
david@balrog:~/tmp$ conan build .
Project: Running build()
Requires, exact version:       None
Requires, version range:       None
Build requires, exact version: None
Build requires, version range: None
david@balrog:~/tmp$ 
```

**Comment by memsharded** [comment]
You are right. The version field is only asigned in the cache, but not in the local flow. I will check if possible to add it, but sounds difficult.

**Comment by DavidZemon** [comment]
For reference, I'm just going to change my logic a bit so that I don't need the version number. I still think this would be nice to implement, but no rush.

**Comment by memsharded** [comment]
Thanks @DavidZemon for the feedback, it really help to prioritize. This is a partial test:

```python
    def version_test(self):
        # https://github.com/conan-io/conan/issues/2451
        client = TestClient()
        conanfile = """from conans import ConanFile
class FooConan(ConanFile):
    pass
"""
        client.save({"conanfile.py": conanfile})
        for pkgname in ("liba/1.1", "libb/1.1", "libc/1.1", "libd/1.1"):
            client.run("create . %s@user/channel" % pkgname)
        conanfile = """from conans import ConanFile
class FooConan(ConanFile):
    requires = 'liba/[>1.0.0]@user/channel', 'libb/1.1@user/channel'
    build_requires = 'libc/[>1.0.0]@user/channel', 'libd/1.1@user/channel'

    def build(self):
        for lib in ("liba", "libb", "libc", "libd"):
            self.output.info('%s REQUIRE: %s' % (lib, self.requires[lib]))
            self.output.info('%s OK: %s' % (lib, str(self.deps_cpp_info[lib].version)))

"""
        client.save({"conanfile.py": conanfile})
        client.run("install .")
        client.run("build .")
        print client.out
        client.run("create . Pkg/0.1@user/channel")
        print client.out
```
The solution could be based:
- ``_load_consumer_conanfile()`` method should recover the ``deps_cpp_info[].version`` info from *conaninfo.txt*
- conaninfo.txt is read to create the profile, but versions are lost, keep them.
- Use them after or in the call to ``_load_deps_info()`` method.

As it doesn't seem urgent, lets aim for 1.2 or 1.3.

**Comment by daneshg** [comment]
@DavidZemon We can embed name and version in **user_info** object which can be accessed in build method similar to **cpp_info** object.
FYI https://docs.conan.io/en/latest/reference/conanfile/methods.html#user-info

**Comment by DavidZemon** [comment]
I actually don't even remember why I needed this anymore

**Comment by Adnn** [comment]
Not necessarily the initially intended use case, but this feature would notably be useful to develop test recipes for installer packages. For example, the test package runs a command line giving the exact version of the "tool", and it should be compared against the version of the `require` installer package.

**Comment by Adnn** [comment]
Well, reading `conan/model/requires.py` gave a solution for that.
In a recipe with a requirement to `A`, `A` version can be obtained via:

    self.requires["A"].ref.version

**Comment by DavidZemon** [comment]
I remember now what I was trying to do when I submitted this ticket. I wanted to build a complete Linux firmware image from a selection of Conan packages, and I was storing the selection of Conan packages in a JSON file (the _complete_ list, with all dependencies). I was then going to traverse the list of _resolved_ dependencies and their versions and ensure every resolved package appeared exactly the same in the manifest file. Any discrepancy between what Conan resolved and what was in the manifest would be considered a user error.

Implementing the logic to ensure no transitive dependencies were missed in the manifest was simple enough, but I was never able to verify that version numbers matched without this feature.

**Comment by memsharded** [comment]
The new interface to dependencies solves this:

```python
self.dependencies["mydep"].ref.version
```
This has been available for several releases now. It is also flexible and allows even more than the previous approach, for example, getting information from build-requires and test-requires.

I think this can be closed now.
