### ISSUE TITLE
Dynamically set version of package

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2453]
I'd like to dynamically set the version of my package. I have a package that needs to be capable of building with **or without** Conan. The project I'm working in at the moment happens to be CMake, but that won't always be true as I move forward with Conanizing other projects.

`/version.txt`
```
0.0.1
````

`CMakeListst.txt`
```cmake
cmake_minimum_required(VERSION 3.0.0)

file (STRINGS "version.txt" VERSION)
project(wsbu-libs
        VERSION "${VERSION}")

# .... stuff
```

`conanfile.py`
```py
import os
from conans import ConanFile, CMake

def get_version():
    with open(os.path.join(os.path.dirname(__file__), 'version.txt'), 'r') as f:
        content = f.read()
        try:
            content = content.decode()
        except AttributeError:
            pass
        return content.strip()

class WsbuLibsConan(ConanFile):
    name = 'wsbu-libs'
    version = get_version() + '+1'
```

Works great when building without Conan, but `conan create` fails of course because the recipe is invoked prior to copying over the rest of the sources (I happen to be using `exports_sources` here, but I'm sure I'd get into even more trouble if I was using a `source()` method!).

So, is it possible to do what I'm trying to do here?

**Comment by lasote** [comment]
I really don't understand the full picture but probably you like to know that you don't need the version and name fields declared in the conanfile. You can call conan export or conan create passing the full reference:

`conan create . Lib/$(cat version.txt)@user/channel` or something similar could be scripted

**Comment by DavidZemon** [comment]
I'm not sure what else I can do to explain it more clearly. I need my Conan recipe to be capable of reading `version.txt` to determine the version. I'm glad providing the full reference on the command line is an option, but it's not a great one. I'd much rather be able to just keep using Conan the way I do for every other package. I've decided to use this until a better solution is offered up:

```py
import sys

VERSION = '1.0.3'

if '__main__' == __name__:
    sys.stdout.write(VERSION)
else:
    from conans import ConanFile, CMake


    class DdioConan(ConanFile):
        name = 'ddio'
        version = VERSION + '+1'
        license = 'Proprietary'
        url = 'https://bitbucket.org/redlionstl/ddio.git'
        description = 'DD I/O'
        settings = 'os', 'compiler', 'build_type', 'arch'
        options = {'shared': [True, False]}
        default_options = 'shared=True'
        generators = 'cmake'

        requires = 'btio/[>=0.0.1+1]@wsbu/stable'

        exports_sources = '*', '!bin/*', '!build/*', '!cmake-build-*', '!.idea/*'

        def build(self):
            cmake = CMake(self)
            cmake.definitions['CMAKE_INSTALL_PREFIX'] = '/'
            cmake.configure(defs={'VERSION': VERSION})
            cmake.build()

        def package(self):
            self.run('cmake --build {0} --target install -- DESTDIR={1}'.format(self.build_folder, self.package_folder))

        def package_info(self):
            self.cpp_info.libs = [
                'ddio',
                'ddioc++'
            ]
```

and the top of my `CMakeLists.txt` script:

```cmake
cmake_minimum_required(VERSION 3.0)

if (NOT DEFINED VERSION)
    execute_process(COMMAND python "${CMAKE_CURRENT_LIST_DIR}/conanfile.py"
        OUTPUT_VARIABLE VERSION
        RESULT_VARIABLE EXIT_CODE)
    if (EXIT_CODE)
        message(FATAL_ERROR "Unable to pull version by invoking Python on '${CMAKE_CURRENT_LIST_DIR}/conanfile.py'")
    endif ()
endif ()
project(ddio VERSION ${VERSION})
```

It's lengthy, and it indents my entire recipe, but it gets the job done at least.

**Comment by lasote** [comment]
Thanks, now I understand what are you trying to do.
Use `exports` instead of `exports_sources` for the version.txt file:

```
from conans import ConanFile, CMake, tools


class LibConan(ConanFile):
    name = "lib"
    version = tools.load("version.txt").strip() + "+1"

```

**Comment by DavidZemon** [comment]
THANK YOU! :D That's working _much_ better.

**Comment by sourcedelica** [comment]
Hi David - I’m curious to know how the Cmake project VERSION is used.

**Comment by DavidZemon** [comment]
It's used when creating packages via cpack (not necessary for Conan, but great for publishing packages that can be used outside Conan). We also use it to keep the SOVERSION in sync with the project version in some but not all of our libraries.

**Comment by sourcedelica** [comment]
Cool - thanks!

**Comment by memsharded** [comment]
> Use exports instead of exports_sources for the version.txt file:

@DavidZemon Just in case, as a reference, the main difference between ``exports`` and ``exports_sources`` is that the sources should be needed only for building from source, i.e. the ``source()`` or the ``build()`` method. For everything else that the recipe might need during its evaluation, use the ``exports``. The ``exports_sources`` are only retrieved when it is necessary to build, because they could be big tarballs
