### ISSUE TITLE
Loading LD_LIBRARY_PATH in test() method of test_package?

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2455]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan v1.0.1

Is there a simpler way to load the necessary value for `LD_LIBRARY_PATH` in the `test_package` folder than parsing `activate_run.sh` script?

```py
def test(self):
    ld_path = [line for line in tools.load('activate_run.sh').splitlines() if line.startswith('LD_LIBRARY_PATH=')]
    ld_path = os.path.expandvars(ld_path[0])
    self.run('env {0} bin/MyTestExe'.format(ld_path))
```

I just found `tools.environment_append()`, and I guess that's the more "right" way since it would be more cross-platform than using `env`. I guess it would look something like this: (untested)

```py
def test(self):
    ld_path = [line for line in tools.load('activate_run.sh').splitlines() if line.startswith('LD_LIBRARY_PATH=')]
    ld_path = os.path.expandvars(ld_path[0])
    parts = ld_path.split('=')
    with tools.environment_append({parts[0]: parts[1]}):
        self.run('bin/MyTestExe')
```

I wouldn't call this second method any "simpler" though and that is what I'm asking for here.

**Comment by lasote** [comment]
Look at http://docs.conan.io/en/latest/reference/build_helpers/run_environment.html 

Anyway you could also use the imports to copy the shared libs to your executable folder and set the LD_LIBRARY_PATH to the current dir.

You have also available the `self.deps_cpp_info` with the directories of the requirements, no need to parse any file

**Comment by DavidZemon** [comment]
Thank you! `RunEnvironment` is exactly what I was hoping for!
