### ISSUE TITLE
Consider define a new export() method to be executed at export only

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2456]
There are 2 main cases that requires some logic to be executed at export time:

- Capturing the version from a text file (cmake, txt...)
- Capturing the git commit hash of the repo you are living

The current approach is to execute a global function in the recipe that will fail gently if the info is not there.
Lets have a look to this possible ``export()`` method. To check:
- If it is valid to assign version (as the version is needed before even exporting)
- It is a ``pre-export()``?

Related issues:
- https://github.com/conan-io/conan/issues/2454
- https://github.com/conan-io/conan/issues/2371
- https://github.com/conan-io/conan/issues/2438

**Comment by sourcedelica** [comment]
A related topic:

It would be great to nice the equivalent of `tools.pythonpath` that could be called at the global scope, where you could get access to code from packages. 

`tools.pythonpath` needs a reference to `self`, and it uses the dependencies of the recipe, which hasn’t been loaded yet at the global scope. 

For our internal libraries I have a standard `conanfile.py` that developers will copy to create a recipe for their libraries.  It has a bunch of boilerplate and some values for them to fill in.

```
# Relative path to the top our project source tree
#
# *** SET THIS VALUE ***
#
PROJECT_ROOT = '..'


# Do not change
def is_exporting():
    sys.path.append(PROJECT_ROOT)
    from environment.conan import recipe_util
    return recipe_util.is_exporting()


# Do not change
def version():
    if is_exporting():
        sys.path.append(PROJECT_ROOT)
        from environment.conan import recipe_util
        return recipe_util.version()
    else:
        return None
```

Ideally this could be replaced with

```
def version():
    if tools.is_exporting():
        with tools.pythonpath(export_requires=True):
            return recipe_util.version()
    else:
        return None
```

The `export_requires` flag would use the packages from a new profile `[export_requires]` section.

This would cut down on the boilerplate and people accidentally setting `PROJECT_ROOT` incorrectly.

**Comment by sourcedelica** [comment]
I've decided to take your suggestion and provide the version on the command line, so my recipes don't have that global boilerplate anymore.  So `[export_requires]` is not a concern of mine any more.  But I still need something similar - I've logged a separate issue for it: #2542.

**Comment by solvingj** [comment]
This feature would seem to solve the problem of storing `conanfile.py` in some subdirectory of the project. 

https://github.com/conan-io/conan/issues/3635

Users could do:  `with tools.chdir("..")` before doing their copies.   For that reason, I would like to see this feature on the next milestone. We would use it.

**Comment by solvingj** [comment]
Upon closer inspection, this issue is talking specifically about `export()` method, and not an `exports_sources()` type method.  In retrospect, I'm not sure why both such methods weren't conceived sooner, given that having both an attribute and a dynamic method for all the `__requires` functions has proven so useful and practical.   In any case, I would also like to request an `exports_sources()` method to go along with this.  Should that be a separate issue?

**Comment by lasote** [comment]
Related issue #3338

**Comment by memsharded** [comment]
exports() and exports_sources() methods were introduced some time ago, in Conan 1.26.

Furthermore, there are now specific methods ``set_name()``, ``set_version()`` to solve some of the above mentioned comments.

Check docs: https://docs.conan.io/en/latest/reference/conanfile/methods.html#export
