### ISSUE TITLE
CMake helper should handle fPIC like Autotools helper is doing

### ISSUE THREAD

**Issue by pvicente** [conan-io/conan#2464]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.0.4

If fPIC is an options in the recipe. Enable/Disable it depending on the compiler should be managed by CMake helper like autotools helper is doing.

Usually this check is needed.

```python
def build(self):
    cmake = CMake(self)
    ...
    if self.options.fPIC and self.settings.compiler != "Visual Studio":
            cmake.definitions["CMAKE_CXX_FLAGS"] = "-fPIC"
            cmake.definitions["CMAKE_C_FLAGS"] = "-fPIC"
```

Example with autotools helper:

```
from conans import ConanFile, AutoToolsBuildEnvironment

class ExampleConan(ConanFile):
   ...

   def build(self):
      env_build = AutoToolsBuildEnvironment(self)
      env_build.fpic = True
      env_build.libs.append("pthread")
      env_build.defines.append("NEW_DEFINE=23")
      env_build.configure()
      env_build.make()
```

**Comment by SSE4** [comment]
consider using this property https://cmake.org/cmake/help/v3.10/variable/CMAKE_POSITION_INDEPENDENT_CODE.html

**Comment by lasote** [comment]
@SSE4 thanks we will take a look to the compatibility and will use it when possible. 
In the example above anyway should be CONAN_CXX_FLAGS, not directly cmake.

**Comment by lasote** [comment]
Related to #2476. Take a decision before implementing it based on the option.

**Comment by memsharded** [comment]
It is not clear we want to build this into the helper while the fPIC "standardization" is not there yet.
I will move this to 1.3, waiting for that.
