### ISSUE TITLE
conan search --table is weird when missing settings

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#2465]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.

1.0

- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

If the conanfile of the uploaded recipe only contains ``os_build`` for example: https://github.com/bincrafters/conan-cygwin_installer/blob/stable/2.9.0/conanfile.py

The table looks weird with many Nones:

![image](https://user-images.githubusercontent.com/3807515/36150972-d4fe71fa-10c5-11e8-8f7a-eaae2642aec8.png)

**Comment by jgsogo** [comment]
I'm having a look at this issue. There are several ways to consume information from a `search` command:
 * command line output: `conan search lib/ver@user/channel`
 * json: `conan search lib/ver@user/channel --json=file.json`
 * table: `conan search lib/ver@user/channel --table=file.json`

I'll try to normalize the output (and simplify code). Let's go!

**Comment by memsharded** [comment]
The html search table has been completely re-implemented, this no longer applies.
