### ISSUE TITLE
[question] Propagate some object from configure to build method

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#2467]
In configure method we want to assert all settings to only valid combinations. This requires some conditionals. Then in build often i need to evaluate these conditionals again, to actually execute parametrized build (eg. select optimization).

```
def configure(self):
    if self.satisfies1():
        if self.shouldnt_happen1():
            raise ...
    elif self.satisfies2():
        if self.shouldnt_happen2():
            raise ...
    else:
        raise ...

def build(self):
    if self.satisfies1():
        self.run("something1 ...")
    if self.satisfies2():
        self.run("something2 ...")
```

But often second evaluation is not necessary if I could generate some data during configure. eg.:

```
def configure(self):
    if self.satisfies1():
        self.build_data["optimization"] = "-Os"
        if self.shouldnt_happen1():
            raise ...
    elif self.satisfies2():
        self.build_data["optimization"] = "-Og"
        if self.shouldnt_happen2():
            raise ...
    else:
        self.build_data["optimization"] = "-O0"

def build(self):
    self.run("something ... {} ...".format(self.build_data["optimization"]))
```

Is there some conan way to do this?

**Comment by memsharded** [comment]
IMHO that code reads pretty nice. Are the ``self.satisfiesX()`` calls very slow that they should be optimized?

While caching values in ``configure()`` to reuse them later in ``build()`` might work in conan local cache, that will probably fail in other contexts, for example in ``conan build`` command that basically just call the ``build()`` method, but nothing else (not call ``configure()`` method).

So if the checks are very expensive and you want to optimize, I would suggest caching results inside the methods:

```python

def satisfiesX(self):
      try:
          return self._satisfies_x
      except AttributeError:
          self._satisfies_x = ... your logic
          return self._satisfies_x
```
This should work in all contexts and call the heavy logic just once.

**Comment by omicronns** [comment]
Is there a situation where ```build()``` gets invoked without ```configure()``` getting invoked? This would be misleading, since ```build()``` behaviour often depends on how ```configure()``` will modify settings and options. Also the problem is not about heavy call, but on boilerplate code one could avoid.

**Comment by memsharded** [comment]
In the local flow, the configuration is computed and stored in disk in ``conan install`` (files conanbuildinfo.txt and conaninfo.txt), and those files are read when ``conan build`` to recover state to call ``build()`` but ``configure()`` won't be called again in the same execution, so in-recipe-memory stored values won't work.

I think you would also be good if you wrap the logic in another method:

```python
def optimization(self):
    if self.satisfies1():
        optim = "-Os"
        if self.shouldnt_happen1():
            raise ...
    elif self.satisfies2():
        optim  = "-Og"
        if self.shouldnt_happen2():
            raise ...
    else:
        optim  = "-O0"
    return optim
```

And then you can call it from the ``build()`` method. Have you tried that approach?
