### ISSUE TITLE
Wrong targeted Windows SDK after solution upgrade with Visual Studio 2017

### ISSUE THREAD

**Issue by aallrd** [conan-io/conan#2469]
Hello,

I don't think this qualifies as a problem with Conan, it's clearly an issue with Visual Studio 2017, but since I spent 2 hours on it I think it's better to document it for reference.

My environment:
- Visual Studio 2017 version 15.5.6
- Conan version 1.0.4

I was trying to Conanify (?) a project that embeds a Visual Studio solution targeted for Visual Studio 2015.
When I manually opened the solution in Visual Studio 2017, upgraded the project, and build the target it succeeded directly, it was very straightforward.

I used the below code in my conanfile to reproduce the above scenario:
```
    with tools.chdir(sln_path):
        msbuild = MSBuild(self)
        msbuild.build(sln_name, targets=["all"], upgrade_project=True)
```
It produced the below perfectly fine command line:
```
set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\../../VC/Auxiliary/Build/vcvarsall.bat" amd64 && devenv my-solution.sln /upgrade && msbuild my-solution.sln /p:Configuration=Release /p:Platform="x64" /m:12 /target:all
```

But this time the build process failed with multiple errors such as:
```
fatal error C1083: Could not open include file:  'stdlib.h': No such file or directory
```

After tinkering and comparing both upgraded solutions, I noticed that the one generated from the command line was missing the property `<WindowsTargetPlatformVersion>10.0.16299.0</WindowsTargetPlatformVersion>`.
The command line generated solution was configured to target the Windows 8.1 SDK instead of the Windows 10 SDK.
When upgrading directly with the IDE, I was prompted with a dialog box asking the targeted SDK to use.

Re-targeting a solution from the command line, does not seem possible, I only found the option available in the IDE. I could not find any other flags/parameters/options to force Visual Studio to use the latest available SDK yet.

I found the exact same issue opened in the Premake project [#935](https://github.com/premake/premake-core/issues/935), with more details about the problem.

I opened an issue on the Visual Studio tracker: https://developercommunity.visualstudio.com/content/problem/198082/upgrading-a-solution-from-the-command-line-with-vi.html

**Comment by memsharded** [comment]
Thanks very much for your detailed feedback, this is useful information.

I think this might be related to the SDKs installed too. I have managed to succesfully upgrade solutions from VS2015 to VS2017 directly in conan without this issue. I think this is to the fact that (IIRC) I only installed 1 SDK, probably the same, so it didn't fail. 

But yes, I understand this issue, thanks for reporting to VS tracker too.

In the meantime, if you want conan to do this, I think it should be possible. I would try to do a ``tools.replace_in_file()`` over the .vcproj, something like this:

```python
def build(self):
     if self.settings.compiler.version == 15:  # assuming VS
            tools.replace_in_file("project.vcproj", 
                                            "<WindowsTargetPlatformVersion>8....</Windows...>",
                                            "<WindowsTargetPlatformVersion>10.0.16299.0</Windows...>")
     with tools.chdir(sln_path):
        msbuild = MSBuild(self)
        msbuild.build(sln_name, targets=["all"], upgrade_project=True)
```

That might do the trick.
Thanks again for your feedback!

**Comment by aallrd** [comment]
Thanks for the feedback.

In the project I am working on,  the `<WindowsTargetPlatformVersion>` is not even present in the original solution.
When I upgrade this solution with the IDE, this tag is added under the `<PropertyGroup Label="Globals">` section.
However it is not added when upgrading from the command line.

In order to confirm the possible multiple SDKs issue, I ran the same commands in a Windows container with only Visual Studio 2017 Native Desktop workload installed.
It also failed, trying to target the SDK 8.1, despite having only the SDK 10 installed in the container...

I'll try to manually add the property in the upgraded solution while I wait for Microsoft's feedback on the 
opened issue.

**Comment by memsharded** [comment]
> When I upgrade this solution with the IDE, this tag is added under the <PropertyGroup Label="Globals"> section.
However it is not added when upgrading from the command line.

I am going to run a check, and see if there is something with the SDK.

Yes, if not a clear replace_in_file, you can always get the xml and insert the node you want there. Let me know how it goes.

**Comment by memsharded** [comment]
I have both before and after the upgrade (when called with ``conan create``):

```
<WindowsTargetPlatformVersion>8.1</WindowsTargetPlatformVersion>
```
The only difference that the upgrade produce is:

```diff
-<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
+<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <ItemGroup Label="ProjectConfigurations">
     <ProjectConfiguration Include="Debug|Win32">
       <Configuration>Debug</Configuration>
@@ -28,26 +28,26 @@
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
     <ConfigurationType>StaticLibrary</ConfigurationType>
     <UseDebugLibraries>true</UseDebugLibraries>
-    <PlatformToolset>v140</PlatformToolset>
+    <PlatformToolset>v141</PlatformToolset>
```

**Comment by aallrd** [comment]
Okay I think I have found what was wrong on my side, part of at least.
I could not understand why you were able to build with Visual Studio 2017 and the SDK 8.1 and not me.
On my system I had this folder `C:\Program Files (x86)\Windows Kits\8.1` so I had assumed that the SDK was indeed installed.
When I re-ran the Visual Studio 2017 installer to check its list of installed modules, I noticed that the SDK 8.1 was not ticked...
I re-ran the Visual Studio 2017 installer with this module ticked, and this time it worked OOTB even if targeting the SDK 8.1.
I don't think the folder `C:\Program Files (x86)\Windows Kits\8.1` was modified during the re-installation, so I am not even sure what it is in the end...

Anyway, for sure the SDK 10 was installed since the beginning since it's ticked by default during the installation process.
So there is still a bug on Microsoft's side, why would Visual Studio 2017 target by default a custom-lower-version-not-even-installed SDK when it comes bundled with the SDK 10...

**Comment by memsharded** [comment]
Oh no! You are totally right.

The VS 2017 installer in fact destroys your previous installation of VS 2015, and uninstall things it is using, specifically SDKs. I now recall having those issues, so my VS2015 was in fact fully broken after it. So I had to go to VS 2015, to make sure that I reinstalled the things as they were before installing VS 2017

**Comment by aallrd** [comment]
I'll close this issue as it's not related to Conan.
I'll keep monitoring the Microsoft support comments on the Visual Studio bug tracker, but it does not seem that they consider this issue as a bug nor as a worthy feature request...
