### ISSUE TITLE
Allow syntax "conan help subcommand"

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#2471]
On git, `git help status` and `git status --help` are equivalent.
On svn, `svn help status` and `svn status --help` are equivalent.
On docker, `docker help cp` and `docker cp --help` are equivalent.
Same (almost, with --help the command is evaluated) for the vboxmanage tool shipped with Virtualbox.

However conan reports the `conan help info` as being an error, leading to some frustration.
If would be nice to have it follow the same conventions as other popular tools.

**Comment by memsharded** [comment]
Yes, I agree this would be nice. Lets try to do it!

**Comment by memsharded** [comment]
It has been implemented in #2473, will be soon released in 1.1
