### ISSUE TITLE
Dead link in docs.conan.io to download conan

### ISSUE THREAD

**Issue by matlo607** [conan-io/conan#2474]
A link provided on http://docs.conan.io/en/latest/installation.html is dead.

> ### Install the binaries
> Go to the conan website and [download the installer for your platform!](https://www.conan.io/downloads)

[https://www.conan.io/downloads](https://www.conan.io/downloads) should be renamed to [https://www.conan.io/downloads.html](https://www.conan.io/downloads.html)

**Comment by lasote** [comment]
Will fix it right now, thanks.

**Comment by lasote** [comment]
Fixed!
