### ISSUE TITLE
conan-community repository

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2479]
There is [conan-community](https://bintray.com/conan-community) repositiory that seems to be managed by conan developers. What is its purpose compared to `conan-server`? Can you add some info about it to your [docs](http://docs.conan.io/en/latest/uploading_packages/remotes.html)?

**Comment by memsharded** [comment]
It is very different:

- conan_server is an in-house server you can run in your own server to host your private packages. It is OSS, with the same MIT license as conan. It implements a remote, in the same way as Artifactory and Bintray are conan-remotes
- conan-community repo is a bintray (and github) repo that hosts some popular conan packages for OSS libraries. It will be similar to the bincrafters repos, but for packages that the conan team maintain themselves. This conan-community repo is intended to feed conan-center too, when the packages are matured and tested they will be included in conan-center.

**Comment by db4** [comment]
> compared to conan-server

Ahh, sorry. Of course, I meant conan-center!

> This conan-community repo is intended to feed conan-center too, when the packages are matured and tested they will be included in conan-center

Thanks for the clarification. So it's worth  adding it to the list of standard remote repositories (conan-transit is mostly unusable nowadays). Can you mention conan-community in your docs?

**Comment by danimtb** [comment]
Yes @db4, I have created an issue for that conan-io/docs#536.

Let me just clarify that **conan-community** will be not added to the default repositories in the conan client and that it will be a place to mature our own recipes. You can expect better quality and support than in conan-transit (no support for it, as you know) but you should take into account that most recipes will live in **conan-community** as a _work in progress_ before they are submitted to **conan-center**.

**Comment by memsharded** [comment]
Yes, and also conan-transit will be removed from the default remotes, as you said, it is pretty unusable.

I'd say we can follow in conan-io/docs#536, this issue can be closed. Thanks for the feedback!
