### ISSUE TITLE
Discussion - Paths in self.copy() for package() of conanfile

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#2482]
This is a minor and largely cosmetic issue which I would like to discuss for posterity, and in the interest of reducing noise in recipes.  I would first like to get confirmation on the ideas below from Conan team and go from there. 

The "common-knowledge" of "best-practices" of working with Python and filesystem paths is to use `os.path.join()` to construct the paths, especially when the code is expected to be run across multiple platforms (windows and posix). Using "slash-notation" to construct paths such as `/something/something` is almost strictly worse according to most documentation. 

However, for a while I've been pondering the `self.copy()` feature of the `package()` method of conan recipes.  In many cases, I continue to see new recipes from the Conan team, and the Conan documentation using slash-notation in the `src` and `dst` parameters, as well as in the `pattern` parameter. Obviously, the slash notation is working across platforms on these new recipes, and whenever the Conan team is doing something differently from me and which I don't understand, I always stop and question what I'm doing.  

I believe I now understand the reasons for using slash-notation in the context of the `self.copy()` feature of the `package()` method, despite it being an exception to "common knowledge" and "best practice" for python.  As such, I am considering explicitly promoting it as a recommended practice moving forward (again, within this limited context).  Of note, I am also NOT promoting refactoring of any existing recipes.  

The benefits of slash-notation which I can see are:   
- Dramatically improved clarity 
- Reduction of lines of code

And as I said, it seems to just work.  I can definitely say that the `os.path.join` in the context of `package()` has significantly cluttered my code in many cases.  So, if slash-notation is more terse, readable and functionally equivalent, I would like to raise awareness for anyone else who has been using `os.path.join()` like me, and suggest slash-notation for future recipes. 

Feedback welcome. 

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Personally, I try to use it because in the conan codebase I always use it, but probably it works just fine. I'm not against it, I agree `os.path.join` is very verbose and something just "/" is better. Windows plays ok with the "/", so unless there is some corner case, I'm ok with it.
But, it depends, between:

- `"%s/%s" % (one, two)`
- `os.path.join(one, two)`

I obviously choose the `os.path.join`

**Comment by solvingj** [comment]
Well, i'm glad you responded because it was many of the recipe's in conan community repo where I saw the slash notations.  Thank you for the feedback.  Perhaps we'll simply conclude that either is fine, we can leave it a matter of author's taste, and we don't need to converge/standardize on one or the other.  Much like python string `.format()` vs `%s` notation.  Leaving this open for more people to share their opinions.

**Comment by memsharded** [comment]
I am guilty of using paths like ``"some_path/%s/src" % self.version``, so yes, I am good with it. And up to my knowledge works well in all systems in most places, except when it is used for execution (like in the ``test()`` method). 
I am good with os.path.join too, so I'd leave this to authors liking.

**Comment by sourcedelica** [comment]
I’ve been bitten a bunch of times by slash notation breaking on Mingw, and having to replace it with `os.path.join`.

**Comment by memsharded** [comment]
That is interesting because Mingw being GNU based, I would expect the support for forward slash / to be reasonably good, specially when windows native already support it. In any case, I'd say that support for MinGW doesn't come that easily out of the box, and usually recipes should adapt, so the moment you generate packages for MinGW you will realize and trap these errors. What do you think?

**Comment by sourcedelica** [comment]
Agreed.  And using `os.path.join` is a good cross-platform practice.

**Comment by solvingj** [comment]
Of note, the original focus of this ticket was to point out and establish/verify that paths pattern matched in the `pattern=` parameter of `self.copy` are applied using an `fnmatch` function in python which always internally represents paths using the `/` path separator, regardless of platform.  

I believe (and still want confirmation) that this is something fundamentally different than the discussion around `os.path.join()` for specifying file paths in python.  For this, I would think the best-practice of using `os.path.join()` should be applied to the `src=` and `dst=` parameters of `self.copy()`.  

If we can agree that `/` in the `pattern=` parameter is not "against best practices" because it's actually "defining a path" but is defining a "match string (potentially partial)", then I can refer back to this conversation in documentation.

**Comment by memsharded** [comment]
The ``fnmatch.filter()`` method used, already normalizes backslahs before comparing. 
So regarding this, I'd say we are good. I believe that this would had already bitten us wildly if not.

Thanks!
