### ISSUE TITLE
[Artifactory] Fails to display conan package info when setting is empty

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#2484]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.0.4
Artifactory 5.8.0

When selecting a package in Artifactory from the tree view, on the right side a tab "Conan Package Info" is displayed. However, if one of the settings in that package is empty (as was caused by my package_id()) Artifactory fails to read the setting and is unable to display anything on that tab. An exception is added to the logs:
```
2018-02-15 15:43:58,173 [ajp-nio-127.0.0.1-8019-exec-9] [ERROR] (o.j.r.c.r.u.LocalUpDownConanHandler:82) - Error parsing file autobuilder/clang/7.0.0/master/package/d9a7d7ca2e0f15147b89a3048045be452a1aeb3a/conaninfo.txt:[settings]
    arch=x86_64
    arch_build=None
    arch_target=x86_64
    build_type=Debug
    compiler=SELF
    os=Windows
    os_build=Windows
    os_target=

[requires]


[options]
    EnableCXX1Y=True
    EnableCXX1Z=True
    Z3=False
    assertions=False
    libclang.static=False
    shared=False

[full_settings]
    arch=x86_64
    arch_build=x86_64
    arch_target=x86_64
    build_type=Debug
    compiler=Visual Studio
    compiler.version=15
    os_build=Windows
    os_target=Windows

[full_requires]


[full_options]
    EnableCXX1Y=True
    EnableCXX1Z=True
    Z3=False
    assertions=False
    generateDocumentation=False
    libclang.static=False
    shared=False

[recipe_hash]
    38277c67e97d01e20721b1570b8f5c54

[env]

 Exception: org.jfrog.repomd.conan.ConanInfoException: Invalid conaninfo.txt format: os_target=
```

I suspect this is something as simple as the regex or whatever is parsing this file is simply not prepared for a setting to be empty and needs to be adjusted accordingly. I have not yet encountered any trouble with conan client itself handling this package.

**Comment by mpdelbuono** [comment]
(In case it isn't clear what I meant by Artifactory displays nothing on the tab, here is a screenshot when this problem is encountered.)

![image](https://user-images.githubusercontent.com/830109/36287679-2e05b474-126b-11e8-9498-833f43eccca5.png)

**Comment by memsharded** [comment]
Thanks for reporting. Yes, this is a confirmed issue in all Artifactory editions, to be fixed.

cc/ @markgalpin

**Comment by lasote** [comment]
Even being an Artifactory (indexer) issue, I assign it to Conan 1.3 to keep it on the radar and solve it asap.

**Comment by db4** [comment]
Probably the related issue: when I try to search such package via conan CLI I get an error:
```
C:\Users\dbely>conan search -r conan-local OpenCV/3.1.0@dbely/testing
ERROR: {
  "errors" : [ {
    "status" : 500,
    "message" : "org.jfrog.repomd.conan.ConanInfoException: Invalid conaninfo.txt format: build_cuda_stubs="
  } ]
}. [Remote: conan-local]
```
`build_cuda_stubs` option has an empty value

**Comment by markgalpin** [comment]
https://www.jfrog.com/jira/browse/RTFACT-16409

**Comment by memsharded** [comment]
This is outdated, I am closing this ticket, please report against the latest Artifactory version, this should be gone.
