### ISSUE TITLE
"build_type" definition not being passed in Windows to CMake as CMAKE_BUILD_TYPE 

### ISSUE THREAD

**Issue by JavierJF** [conan-io/conan#2488]
I have this simple package recipe (source and license have been omitted, but it's a simple git checkout):
```
from conans import ConanFile, CMake, tools
import os

class UIHandlerConan(ConanFile):
    name = "UIHandler"
    version = "0.1"
    settings = "os", "arch", "compiler", "build_type"
    options = {"shared": [True, False], "tests": [True, False]}
    generators = "cmake"
    requires = (
        "gtest/1.8.0@lasote/stable",
        "UErrno/0.1@javjarfer/testing",
        "CArray/0.1@javjarfer/testing",
        "CVariant/0.1@javjarfer/testing",
        "FUtils/0.1@javjarfer/testing",
    )
    default_options = (
        "shared=False",
        "tests=False",
        #  GTest options
        "gtest:shared=False",
        "gtest:no_gmock=True",
        "gtest:no_main=True"
    )

    def build(self):
        cmake = CMake(self)
        cmake_args = {
            'BUILD_SHARED_LIBS' : 'TRUE',
            'CMAKE_BUILD_TESTS' : 'ON'
        }
        cmake.configure(source_folder="UIHandler", defs=cmake_args)
        cmake.build()

    def package(self):
        self.copy("*.h", dst="include/UIHandler", src="UIHandler/include/UIHandler")
        self.copy("*UIHandler.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="lib", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["UIHandler"]
```

The problem is that CMAKE_BUILD_TYPE is not passed to CMake unless I use the explicit the way of doing it, mapping myself the **self.settings.build_type** to a string to pass it to the CMake command.

The environment is Windows with Conan 1.0.4, and CMake 3.9.3. I'm sure I'm doing something wrong because the problem seems very straightforward. Thanks you.

**Comment by memsharded** [comment]
You are overwriting the full defs. I suggest using cmake.definitions[".."] =

That only changes that one. Also BUILD_SHARED_LIBS is automatic if you use
self.options.shared


El 17 feb. 2018 10:53 a. m., "Javier Jaramago Fernández" <
notifications@github.com> escribió:

I have this simple package recipe (source and license have been omitted,
but it's a simple git checkout):

from conans import ConanFile, CMake, tools
import os

class UIHandlerConan(ConanFile):
    name = "UIHandler"
    version = "0.1"
    settings = "os", "arch", "compiler", "build_type"
    options = {"shared": [True, False], "tests": [True, False]}
    generators = "cmake"
    requires = (
        "gtest/1.8.0@lasote/stable",
        "UErrno/0.1@javjarfer/testing",
        "CArray/0.1@javjarfer/testing",
        "CVariant/0.1@javjarfer/testing",
        "FUtils/0.1@javjarfer/testing",
    )
    default_options = (
        "shared=False",
        "tests=False",
        #  GTest options
        "gtest:shared=False",
        "gtest:no_gmock=True",
        "gtest:no_main=True"
    )

    def build(self):
        cmake = CMake(self)
        cmake_args = {
            'BUILD_SHARED_LIBS' : 'TRUE',
            'CMAKE_BUILD_TESTS' : 'ON'
        }
        cmake.configure(source_folder="UIHandler", defs=cmake_args)
        cmake.build()

    def package(self):
        self.copy("*.h", dst="include/UIHandler",
src="UIHandler/include/UIHandler")
        self.copy("*UIHandler.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="lib", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["UIHandler"]

The problem is that CMAKE_BUILD_TYPE is not passed to CMake unless I use
the explicit the way of doing it, mapping myself the
*self.settings.build_type* to a string to pass it to the CMake command.

The environment is Windows with Conan 1.0.4, and CMake 3.9.3. I'm sure I'm
doing something wrong because the problem seems very straightforward.
Thanks you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conan-io/conan/issues/2488>, or mute the thread

**Comment by JavierJF** [comment]
Hi @memsharded , thanks for the quick response. I thought about that possibility and testing I tried completely removing the definitions part leaving the build block like this:

```
    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder="UIHandler")
        cmake.build()
```
The problem is still being presented.

**Comment by lasote** [comment]
Hi, CMake with Visual Studio, as a multiconfiguration project, where you can choose Debug or Release in the IDE, doesn't accept the CMAKE_BUILD_TYPE in the configure, but pass the `--config Debug/Release` at build time.

**Comment by JavierJF** [comment]
Hi @lasote, yes, I'm aware of that, the problem is that the parameter is not passed to a dependency which is installed with the previous command I pasted. So, **conan install** is not passing correctly the build_type to the dependency to which the recipe I pasted belongs.

**Comment by JavierJF** [comment]
Yes, of course, I will try to reproduce in a smaller package and send it to you. I will be able to have it tomorrow. Thanks!

**Comment by memsharded** [comment]
Hi again Javier!

Re-reading the thread, there is something I don't understand:

> conan install .. -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime="MDd" --build=missing

> So, conan install is not passing correctly the build_type to the dependency to which the recipe I pasted belongs.

Typically if you are running the local flow (install + build), you type ``$ conan install`` yourself, with the arguments you want, depending how you want to later build your current code. So conan is not the one defining the ``build_type`` to the dependencies, but the user. 

I think the small code example with the steps to reproduce might help a lot :)

**Comment by JavierJF** [comment]
Hi again @memsharded ! Yes, sorry about the delay, I have had today to make the minimal working example and **surprise!**. The error was in my end. The problem is that I was conditionally settings flags for the actual compiler based in the CMAKE_BUILD_TYPE variable, something like this:

```
If ({CMAKE_BUILD_TYPE STREQUAL "Debug")
           Set(${FLAGS} "...")
EndIf ()
```
But as CMake **states clearly** that variable could remain empty the whole process:

> This variable is only meaningful to single-configuration generators

So, if you use the Visual Studio generator, this variable would remain empty the whole process, even if you manually set the "--config Debug|Release" at build time. It's simply not used at all. So the more correct and cross-platform way of doing this is simply directly use:

- CMAKE_CXX_FLAGS_DEBUG | CMAKE_CXX_FLAGS_RELEASE
- CMAKE_C_FLAGS_DEBUG | CMAKE_C_FLAGS_RELEASE

Maybe this is what @lasote was meaning with it's comment, maybe I didn't understand it well. Anyway thanks you both for your time and fast response!

**Comment by memsharded** [comment]
Thanks for telling, glad you found the issue!

Yes, I think this is what @lasote was talking about. That is one problem of the cmake multi-config environments, you have to be careful about.

So I think this issue can be closed, but please re-open or comment if necessary, or open a new one for any new question. Thanks!

**Comment by AliAskari** [comment]
I am using a profile where I am explicitly setting `build_type` to `Debug`. I was expecting Conan to insert the `CMAKE_BUILD_TYPE` definition but it's not happening.

Referring to your [documents](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html?highlight=cmake_build_type) : 

    The CMake helper will automatically append some definitions based on your settings

and `CMAKE_BUILD_TYPE` is definitely in the list. I understand the behavior of mutli-config projects but  as far as I understand from your docs you should either remove the `CMAKE_BUILD_TYPE` from that list or actually append it as a CMake definition regardless of the config type, it is misleading right now.

**Comment by danimtb** [comment]
@AliAskari I see the `CMAKE_BUILD_TYPE` definition there whe using CMake build helper and cmake generator, so I dont really get your issue

**Comment by AliAskari** [comment]
@danimtb Have you tried it on Windows/Visual Studio?

**Comment by danimtb** [comment]
Windows/Visual Studio, generator set to `cmake` and CMake build helper for building. I see `CMAKE_BUILD_TYPE:STRING=Release` in *CMakeCache.txt* file

**Comment by AliAskari** [comment]
Are you sure you are not forcing `CMAKE_BUILD_TYPE` in your _CMakeLists.txt_?

To reproduce the problem I am having:

- clone https://github.com/bincrafters/conan-fmt
- export it: `conan export conan-fmt demo/demo`
- install:  `conan install fmt/5.0.0@demo/demo --build --profile=x86_debug`

[Here](https://github.com/conan-io/conan/files/2137855/x86_debug.txt) is the profile I am using. The fmt library [defaults](https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L24) to __Release__ if `CMAKE_BUILD_TYPE` is not provided, and it's certainly what is happening on my machine.

**Comment by AliAskari** [comment]
@danimtb were you able to reproduce the issue I have mentioned?

**Comment by danimtb** [comment]
Hi @AliAskari, sorry for the delay.

I checked your steps and you were right in the fact that CMake helper is not setting `CMAKE_BUILD_TYPE` automatically in the configure step. However, it is doing so in the build step with the `--config` flag.

This is because of CMake helper can be used together with `cmake_multi` generator too to allow having both release a debug build types.

I have tested [fmt with some changes in my fork](https://github.com/danimtb/conan-fmt/tree/build_type) to print build type value and it is working as expected with your profile, changing between release an debug.

I finally agree docs are misleading in this case.

**Comment by danimtb** [comment]
Also note that there is a build_type parameter in che [CMake() build helper constructor](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#constructor) in case you want to force the `CMAKE_BUILD_TYPE` variable

**Comment by AliAskari** [comment]
@danimtb Thanks for the recommendations but I am not really looking for a workaround. I just wanted to mention that the docs might mislead people. Simply updating the docs to mention that `CMAKE_BUILD_TYPE` is not set by Conan on Windows/Visual Studio would suffice.
