### ISSUE TITLE
Improper CMake generator string

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#249]
Currently, the generator string passed to CMake is formatted like this in cmake.py: ```"Visual Studio %s" % self._settings.compiler.version```, which results in e.g. "Visual Studio 14". However, the correct string would be "Visual Studio 14 2015". For newer compiler versions, CMake supports the short version due to backward compatibility reasons, but when e.g. trying to use Visual Studio 2008, the generated string "Visual Studio 9" results in a CMake error (generator cannot be found), since it only supports the full string there ("Visual Studio 9 2008").

**Comment by memsharded** [comment]
Good catch, just submitted a PR to fix it (https://github.com/conan-io/conan/pull/250), will be included in 0.9 release, hopefully today
