### ISSUE TITLE
Discoverability of options for package and its dependencies

### ISSUE THREAD

**Issue by ArekPiekarz** [conan-io/conan#2490]
Currently there is no way to automatically get a list of options for a package and all its dependencies. This is especially troublesome for the latest modularized packages with lots of dependencies, like Boost.

For example, here is a result of a command to count all references of packages needed to build Boost Log 1.66:
```
conan info --only None boost_log/1.66.0@bincrafters/stable | wc -l
78
```
Right now a user would have to use `conan get <reference>` on each of 78 packages and read their conanfile.py files to gather their options with available/default values.

Alternatively, one would need to know that Bincrafters created a table with that data in a [blog post for Boost 1.65.1](https://bincrafters.github.io/2017/10/11/Conan-Package-Boost-1-65-1/), but  they used [more verbose descriptions for Boost 1.66.0](http://bincrafters.readthedocs.io/en/latest/package_notes/boost.html), harder to parse quickly and requiring combination with the previous table to get the full picture. Although they did a good job again with [ffmpeg](http://bincrafters.readthedocs.io/en/latest/package_notes/ffmpeg.html).

My point is at this time we are at the mercy of the packagers and external knowledge when it comes to discoverability of options. Could this be somehow automated?

The possible forms of presentation could be
- a list/table printed in the console containing "package | option | default value | available values"
- a webpage with the above table, perhaps in the documentation, at least for packages in conan-center

_Additional info_
Conan version: 1.0.4
Operating system: Windows 10 x64

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
A couple of notes:

- ``conan info`` is intended to explore the dependency graph for a given configuration. Remember the dependency graph can be different in different platforms
- ``conan get`` is intended for getting files, from a single package

It looks to me that ``conan get <pkg-ref> --options`` would be a good approach, but it seems that you are interested in showing options for a full dependency graph. Could you please confirm this? 

Also, in the case you want the options for the full current graph, are you interested in seeing all the possible current values of the options for that graph, or just the possibilities and the defaults? Please remember, that some options (e.g. ``self.options.fPIC`` in Windows) can be removed in ``configure()`` so they won't exist in practice if you are running ``conan info`` in Windows.

**Comment by ArekPiekarz** [comment]
> It looks to me that conan get \<pkg-ref> --options would be a good approach, but it seems that you are interested in showing options for a full dependency graph. Could you please confirm this?

Indeed I would like to see options listed for the full graph. But an ability to list them for a single package would also be welcome and would make the way of analyzing one package consistent with analysis of the full dependency structure

> are you interested in seeing all the possible current values of the options for that graph, or just the possibilities and the defaults?

Right now I'm interested in seeing possible values and defaults for the current configuration. Implementing that could be considered a first step towards making life easier in this area for the users. If there is a demand for seeing combinations for other configurations, it could be added later as the next step.

**Comment by memsharded** [comment]
Thanks for the feedback. Understood, I think this enhancement might be useful.
Not high priority, planning for 1.3, mainly because it is better to first address some issues with the API and machine-readable output of commands, which is related to this feature request.

**Comment by lasote** [comment]
To be discussed at #1895

**Comment by solvingj** [comment]
I would mention this as a potential use-case for standard unix-pipe integration between conan commands.  It's not exactly straightforward, but I can see where a `conan info <packageref> -n id` could be suitable for being piped to a `conan get --options`, naturally resulting in a listing of of all options of the entire dependency graph.

**Comment by memsharded** [comment]
``conan graph info --requires=zlib/1.3`` can report in 2.0:
```
  options_definitions:
    shared: ['True', 'False']
```
And with ``--format=json``:
```json
 "options_definitions": {
     "shared": [         
         "True",         
         "False"         
     ]                   
 },                      
```

Closing ticket, please open new ones for any further question
