### ISSUE TITLE
Propagate cppstd minimun requirement

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#2494]
To complete the https://github.com/conan-io/conan/pull/2486
The `cppinfo` could have a new field used by packages to indicate the standard to use.
This information will never be used to set the standard to be used, at least not by conan directly, the standard is adjusted with the setting `stdcpp`.
This information can be used to WARN or ERROR (decide the behavior or the way to change it) if the specified standard (in the setting) does not match or it is not enough with the standard declared by a dependency.

e.j:

**PROJECT** -> **LIB_A** -> **LIB_B**
   
When LIB_B declares `self.cppinfo.stdcpp = 17` and we install the project conanfile with `-s stdcpp=11` conan should warn/error.

**Comment by mpusz** [comment]
I am not sure if verification of `self.cpp_info.stdcpp = 17` against `settings.stdcpp` is the most important feature here. For me, the most important is to set `target_compile_features(my_lib INTERFACE cxx_std_17)` in `conanbuildinfo.cmake` file so the minimum requirements of my library are transitively propagated to the consumers.

**Comment by lasote** [comment]
I'm wondering, after one year, if the correct behavior shouldn't be to have a  `configure(self)` method, and if your recipe needs a minimum, raise the [ConanInvalidConfiguration](https://docs.conan.io/en/latest/reference/conanfile/methods.html#invalid-configuration). Why would you need the build system to propagate the info from the target if the package manager already knows?
An easy helper could be provided, something like:

```
def configure(self):
    raise_min_cppstd(17)
```

Am I missing something? @memsharded ?

**Comment by memsharded** [comment]
Yes, it is different to have an input requirement than defining a minimum requirement to your consumers.
A ConanInvalidConfiguration can only raise on inputs. But lets say you are building a library that only builds with C++17. It doesn't have much sense to have it as setting, and raise otherwise. What you want is to tell your consumers: "you need to use at least C++17 to use this package". That makes sense even for header-only libraries that don't have settings at all.

**Comment by mpusz** [comment]
My current use case is exactly for that recipe https://github.com/mpusz/conan-cmcstl2. I would like Conan to produce similar CMake definitions in CONAN_PKG as they are specified here: https://github.com/CaseyCarter/cmcstl2/blob/master/CMakeLists.txt.

Especially I would like Conan to generate
```
target_compile_features(stl2 INTERFACE cxx_std_17)
```

Right now the solution works ok for `find_package()` and linking with `std2` but does not work with `CONAN_PKG::cmcstl2`.

**Comment by lasote** [comment]
But @memsharded, if the `cppstd` setting were a subsetting of the compiler, for me it makes sense (maybe with some "helper" mechanism, as the "attributes" we discussed sometime) to say, ok, I only work for > cpp17, otherwise the "official" mechanism to indicate an invalid configuration is that exception. Said that, if the subsetting is not present, for me, that additional mechanism to inform to the consumers in the "info" object is not correct, it should be done by using the setting.

@mpusz Yes, it is indeed interesting to adjust the cppstd in the targets, like `target_compile_features(stl2 INTERFACE cxx_std_17)` . It might be a separated issue. Let's try to organize all these ideas. Thanks!

**Comment by lasote** [comment]
We approved (whiteboard 29.03.2019) that the correct behavior should fail if the setting is not the minimum required.
