### ISSUE TITLE
conan install with multiple conanfiles

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#2498]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.0.4, CMake, Visual Studio

I have two libraries, both consuming conan packages. I want to develop both libraries together in one Visual Studio solution. The CMake part is quite easy with `add_subdirectory` and `target_link_libraries`. But for conan I would need to do something like

`conan install path1 path2`

where path1 and path2 are the paths to my conanfiles. I guess there is currently no way to do that with conan? Any workaround?

**Comment by danimtb** [comment]
Hi @wpalfi!

Thank you for commenting. We have actually an open discussion for this kind of feature in #1377. Could you please have a look there?

If that one covers the use-case you are describing here please close this issue. Otherwise feel free to comment here why your use is different we'll try to address it.

Thank you! :)

**Comment by wpalfi** [comment]
Hi @danitb!

I tried to understand #1377 and all referenced issues. While the aim is similar, I think my approach is different. #1377 is about locally editing conan packages. Then these local packages may be combined to a super project to edit them together. As far as I understand the idea, conan would still be used to manage the dependencies. This is completely different from linking the targets with CMake. Conan only creates **imported targets**, so the IDE would not understand the build dependencies, we would loose almost all advantages of editing the projects together.

What I suggest here is much simpler and more powerful, at least for my use case. I dont want to create packages here. The libraries (or applications) I am talking about are only **consuming** conan packages. All I want to do is to install all requirements of multiple conanfiles. Everything else can easily be done with a few lines in CMake.

**Comment by danimtb** [comment]
ok, now I think I understand better you issue. Definitely simpler than #1377

I have some doubts though.

I guess you have two conanfiles, one for each library, that could have their own dependencies (maybe not even share them).

So the point here is: Is there a reason to have them inside the same VS solution? Are both libraries related to each other somehow? I am not sure if I am missing something here...

**Comment by memsharded** [comment]
Not sure I understand the use case. Every install for every conanfile will generate some files, like ``conanbuildinfo.cmake`` with the information of that dependency graph. These files will be totally different and incompatible for different conanfiles, so I don't see how could they be joined or consumed at once. Why not defining a simple *conanfile.txt* for your project with all the dependencies you want and install them?

**Comment by wpalfi** [comment]
> Are both libraries related to each other somehow?

Yes, A requires B. In fact, A can optionally use B from conan. This was just a simple example, we can have more libraries with a complex dependency tree, of course.

> Why not defining a simple conanfile.txt for your project with all the dependencies you want and install 
them?

Yes, this is just what I would like to automate. 
A and B may have a long list of requirements, the requirements may be conditional or dynamic, and we may have a larger number of libraries in one project. And we would need to keep everything in sync. E.g. I could add a requirement in the super conanfile.txt and forget to add it also to the conanfile.py of the library.

**Comment by memsharded** [comment]
I still think they are exactly what "conan-project" is trying to achieve.

You say that they are not conan-packages, only for consuming, but that is not accurate. You have A=>B and actually you need to build the complete dependency graph with A and B, evaluating all options and conditional dependencies. You are fully processing package B, the only difference is that you want it to be in your user space, not in the local cache.

**Comment by wpalfi** [comment]
I want to process only the consumer part of B.
Maybe I misunderstand the "conan-project" idea. Using B as a package while editing it sounds strange to me.
- I dont want to repackage B when I modify it. 
- I dont want to take care of the packaging part of B all the time while I work on B.
- I want to have correct build dependencies in my IDE. Therefore I need to use a normal CMake target, not an imported conan target. I dont see how this should work with conan packages.

**Comment by memsharded** [comment]
The first two points are indeed the goal of "conan-project"

The latest point, it is up to you. Conan will generate the info in ``conanbuildinfo.cmake`` but you are free to use it or not. If your CMakeLists.txt defines your custom targets for B, and you have some switch, you can do it. For me it sounds like too much extra work for the gain, but you can do it.

**Comment by wpalfi** [comment]
> You have A=>B and actually you need to build the complete dependency graph with A and B, evaluating all options and conditional dependencies

That's true. It was a bad idea.

**Comment by GarrickLin** [comment]
I was wondering what if a library A requires B or requires C. In other words，A can use library B as backen or use C as backen. This case is fairely usual,
- keras cant use tensorflow or mxnet as backen
- if A is a cross-platform project, it might depends on diffenrent libraries in different platform

Can we solve this without multiple conanfile.txt ?

**Comment by memsharded** [comment]
Not even necessary an option, if you want to condition or your current platform. You can do a bare conanfile, not necessary to be complete, something like:

```python
from conans import ConanFile
class Pkg(ConanFile):
    def requirements(self):
         if platform.system() == "Windows":
                self.requires("OnlyWinLib/0.1@user/channel")
        else:
                self.requires("NixLibOnly/1.2@.....")
```

**Comment by GarrickLin** [comment]
thanks, it works!
