### ISSUE TITLE
No way to disable password prompt

### ISSUE THREAD

**Issue by lewie-donckers** [conan-io/conan#2502]
We are using Conan on our build server. Our Conan server requires authentication, even for read access.

When a developer forgets to do a preemptive `conan user -r remote -p password user` in a build script, Conan will prompt for a password. This will cause the build to hang.

I would like the build to fail instead by instructing Conan not to prompt for a password but to fail instead. Preferably using a configuration setting or using a command-line argument otherwise.

(We're using Conan 1.0.4.)

**Comment by memsharded** [comment]
Yes, I think this make sense, thanks for the suggestion! 
Shouldn't be very difficult.

**Comment by lasote** [comment]
FYI. There is a `CONAN_PASSWORD` environment variable that you could use to set the password in every developer environment, I don't know if it helps:

http://docs.conan.io/en/latest/reference/env_vars.html#conan-password-conan-password-remote-name

**Comment by lewie-donckers** [comment]
The environment variable won't be of much help in our setup unfortunately.

**Comment by memsharded** [comment]
> The environment variable won't be of much help in our setup unfortunately.

Why not?
We believe that using a ``CONAN_PASSWORD`` environment variable in the build servers is a much more robust and secure way to do it than having to do: 

```
conan user -r remote -p password user
```
from the build scripts.

Could you please elaborate a bit further about your use case?

**Comment by lewie-donckers** [comment]
We use different Conan users so the build agents can not have the passwords predefined in a single environment variable. If we were to use environment variables, they would have to be set on a case by case basis in the build script. This would not solve this problem; if a developer forgets to set the environment variable, the build would still hang.

**Comment by memsharded** [comment]
Ok, thanks for the feedback.

**Comment by lewie-donckers** [comment]
I've tried to implement this feature on a fork: https://github.com/lewie-donckers/conan/tree/feature/disable_login_prompt

Is there any way you could help me get the code up to snuff for a pull request? (I'm new to contributing to GitHub projects.)

**Comment by memsharded** [comment]
No problem :) 

Your contribution looks good so far: https://github.com/conan-io/conan/compare/develop...lewie-donckers:feature/disable_login_prompt?expand=1

A couple of comments:
- You cannot put ``getenv("CONAN_DISABLE_LOGIN_PROMPT", "True")``, that will change the current default behavior. The default if the variable is not defined at all should be False.
- It is necessary to add some testing for this new feature. Maybe as a copy of https://github.com/conan-io/conan/blob/dc9890691b907b56473fdf13775a3abb04e5b753/conans/test/command/user_test.py#L128 to start with. Depending on your expertise in python too, might be a bit difficult, let us know, so we could contribute the test ourselves.
- It will also be necessary to write some docs in the docs repo. We typically require it together, but in this case, we could address first the code, and leave that for later.

I would say, just start, by pushing the: https://github.com/lewie-donckers/conan/tree/feature/disable_login_prompt -> **New pull request** button in github. There will be some checkboxes to be filled, don't worry too much about them, try to read them and do what you think, but no problem if you leave them unchecked. We will try to help in the process. Many thanks for wanting to contribute to the project!

**Comment by lewie-donckers** [comment]
I've created two pull requests. One for this issue and one for another. I'm currently trying to add some test cases but so far I find it less obvious about what to do. In particular I can't seem to convince nosetest to pick up the test case I added.

**Comment by memsharded** [comment]
Will be in 1.2
