### ISSUE TITLE
How to block uploads to own Conan server

### ISSUE THREAD

**Issue by lewie-donckers** [conan-io/conan#2507]
We're running our own Conan server and I would like to block uploads from most users (even for their 'personal' packages). I only want to offer write access to our build server(s).

The documentation states that registered users can upload to their personal channel by default. I have not found a way to disable that. I thought of something like this

```
[write_permissions]
*/*@rugged/*: rugged
*/*@fpga/*: fpga
*/*@*/*: nobody
```

But that does not seem to help.

Our server is running Conan 1.0.4 on Linux.

**Comment by memsharded** [comment]
Have you tried rebooting the server? Just in case...

Because changes in server.conf ar not hot-reloaded, you need to restart it. Also I think the last line can be omitted.

**Comment by lewie-donckers** [comment]
I restarted the Conan server application after every change to server.conf. Haven't had any success so far.

**Comment by memsharded** [comment]
I have done a quick check, and it seems you are right, could be a bug. I keep checking, thanks for reporting.

**Comment by memsharded** [comment]
I have checked the source code. As you pointed out:

> The documentation states that registered users can upload to their personal channel by default.

It is true. This rule has higher priority than the ``permissions``, so in conan_server users can always read/write from their own channels.

Why simply not adding their users to the ``[users]`` section?
This behavior might be a bit difficult to change without breaking other users that rely on this default behavior.

**Comment by lewie-donckers** [comment]
We're using a custom authenticator with support for both local accounts and LDAP. Developers are authenticated using LDAP and we have a few local accounts for the build servers. So all Conan users are already authenticated and known to the Conan server.

I just thought I could easily block write access completely for certain users. That way our Conan server would only contain packages uploaded by the build servers.

**Comment by memsharded** [comment]
Yes, I understand the issue, and makes sense that this could be defined. Approving it as a feature enhacement

**Comment by memsharded** [comment]
Hi!

I am wondering, now that there is Artifactory Community Edition (https://www.conan.io/downloads.html), if you plan to use it. The permissions in Artifactory is much more configurable, so you should be able to do what you want out of the box.

**Comment by memsharded** [comment]
Closing this as stale/outdated, no longer an issue now with free ArtifactoryCE
