### ISSUE TITLE
`conan source` should be capable of working in the local cache "source" directory

### ISSUE THREAD

**Issue by olivren** [conan-io/conan#2514]
I am trying to upgrade from Conan pre-1.0 (sorry I don't remember the exact version) to 1.0.4.
My setup was relying on a specific behavior of `conan source`, and I cannot find a workaround in 1.0.4. Indeed, `conan source MyPackage/1.0@me/stable` used to execute the `source()` method of the recipe, using the local Conan cache directory as a target (`~/.conan/data/MyPackage/1.0/me/stable/source`). In 1.0, the behavior is to use the current directory as a target (can be overriden with the `-sf` option). I cannot find a way to recover the pre-1.0 behavior, except of course by specifying explicitly `-sf ~/.conan/data/MyPackage/1.0/me/stable/source`, which is a pain.

Let me explain my motivation for that. My goal is to let Visual Studio automatically find the sources of my third party libs, when using the debugger.

As you may know, the debugging data produced by MSVC are stored in .pdb files, generally one for each dll you compile. These pdb files contain references to the *absolute* paths of the sources that were used to compile the dll, and that's what the MSVC debugger uses to show the source code of the program you debug. Of course, using absolute paths does not work when the program being debugged runs on another machine than the one used to compile the third party. Luckily for us, the MSVC debugger has a way to deal with this situation. When it cannot find this abolute path, it tries to run a command embedded in the pdb file, `SRCSRVCMD`, that converts this absolute path to a path on the local filesystem.

What I do in my Conan recipes, is to patch the pdb files in the `package()` method, in order to inject a `SRCSRVCMD` command. This comman is able to convert the absolute path of the source file (for example `C:/Users/aaa/.conan/data/MyPackage/1.0/me/stable/build/ef34...`), to the "source" path in the conan local cache (for example `C:/Users/bbb/.conan/data/MyPackage/1.0/me/stable/source`). Technically, this command parses the result of `conan info --paths --only source_folder` to locate the source folder. Using this technique, the sources of all my conan-packaged libs can be found by MSVC automatically, as long as the sources are present in the expected location.

With conan pre-1.0, installing the sources of the library MyPackage was as easy as running `conan source MyPackage/1.0@me/stable`, and this library was debug-ready. With Conan 1.0 I cannot see an easy way yo install the sources in the expected location. Could this be added as a new option of the `conan source` command?

I'm working on Windows 7 and on RHEL6.

**Comment by memsharded** [comment]
I think this might be a duplicate or the same original issue than https://github.com/conan-io/conan/issues/1796.

Please have a look, report there if duplicated and close this one. Thanks!

**Comment by olivren** [comment]
Well, my motivation for requesting this feature is definitely something that belongs to #1796. In a sense, #1796 is the big picture that may result in the perfect solution in a far future, while #2514 (this one) is one of the pieces I needed from Conan for my quick-and-dirty approach to work today.

Plus, I was able to work around this issue, by using a combination of `conan info` and `conan source` to recover the old behavior I needed. I'm using this Python code:

```
import subprocess, re
conaninfo = subprocess.check_output(['conan', 'info', '--paths', '--only', 'source_folder', '--only', 'export_folder', reference], universal_newlines=True)
source = re.search('source_folder: (.*)', conaninfo).group(1)
export = re.search('export_folder: (.*)', conaninfo).group(1)
subprocess.check_call(['conan', 'source', '-sf', source, export])
```

So, I am not blocked on this issue anymore, and maybe #1796 will give a better solution in the long term anyway. I still think it's a shame that `conan source` cannot work with the default source directory, but this is more of a CLI design question to make it possible or not.
