### ISSUE TITLE
Slowness in the conan repository

### ISSUE THREAD

**Issue by FrancescAlted** [conan-io/conan#2517]
Hi!

First, thanks for putting the Conan service freely available to open source projects.

I am the maintainer of the [C-Blosc package](http://blosc.org/) and I am having some random issues in the response time of the Conan repository when invoked from command line:

```
$ time conan search c-blosc -r conan-center
Existing package recipes:

c-blosc/v1.13.6@francescalted/testing
c-blosc/v1.13.7@francescalted/stable
c-blosc/v1.14.0@francescalted/stable

real	0m2.278s
user	0m0.479s
sys	0m0.165s
$ time conan search c-blosc/v1.13.7@francescalted/stable --table=file.html -r conan-center

real	0m13.181s
user	0m0.649s
sys	0m0.381s
```

The first search command above is 2 seconds at this moment, but I have seen response times for the very same command in the order of 30 seconds yesterday.  Also, the second command taking more than 10 seconds (now) is quite inconvenient for users.  My question is if you have plans to reduce these times, or rather we should expect them to be usual.

However, the thing that I find more annoying for me as developer is that the Conan repository fails uploading packages on a random basis.  For example, I recently got this error from the AppVeyor CI:

```
Uploading package 11/16: 9618ca7c7f904f39d49d627d9d1cf57ef35b52a0
Requesting upload permissions...Done!                                 
Uploading conanmanifest.txt                                           
Uploading conaninfo.txt                                               
ERROR: ('Connection aborted.', BadStatusLine("''",))
Waiting 5 seconds to retry...
ERROR: ('Connection aborted.', BadStatusLine("''",))
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conaninfo.txt, '('Connection aborted.', BadStatusLine("''",))'
Uploading conan_package.tgz                                           
ERROR: Execute upload again to retry upload the failed files: conaninfo.txt. [Remote: upload_repo]
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    builder.run()
  File "C:\Python27\lib\site-packages\conan\packager.py", line 427, in run
    self.upload_packages()
  File "C:\Python27\lib\site-packages\conan\packager.py", line 529, in upload_packages
    raise Exception("Error uploading")
Exception: Error uploading
```

See the [full log here](https://ci.appveyor.com/project/FrancescAlted/c-blosc/build/1.0.507/job/avphqd0f4ny0e653).

This is specially inconvenient for 2 reasons:

1) The CI job fails and makes it more difficult to know whether the package is in a healthy state (i.e. all tests pass) or if it is just the Conan repo not accepting the upload.

2) Most importantly, when this error happens during a stable release (a tag happens), the automatic upload fails, so the package will miss the Conan repo, and a new release would be needed to fix that.

Thanks in advance.

**Comment by memsharded** [comment]
Yes, you are right. This is not normal, there are currently some availability issues in bintray, you can check current status here:

http://status.bintray.com/
