### ISSUE TITLE
tools.vcvars() should be a no-op when not using windows and visual studio

### ISSUE THREAD

**Issue by tru** [conan-io/conan#2531]
This way you can wrap all your code in:
```
with tools.vcvars(self.settings):
  CMake.build()
```

without having to care about what platform you are working with.

**Comment by memsharded** [comment]
This feature is already implemented and I don't oppose to it, but I'd like to know more about the use case of:

```python
with tools.vcvars(self.settings):
  CMake.build()
```
Why setting a VS environment before calling cmake? Usually cmake manages that from generators, toolchains, etc.

**Comment by tru** [comment]
Idk! Maybe we are building all the worlds worst software - but it’s definitely not working without it!
