### ISSUE TITLE
Question: How to pass CMake defines from a conanfile.py when not building

### ISSUE THREAD

**Issue by drmacdon** [conan-io/conan#2532]
I have a conanfile which I use to collect my build and import my dependencies but I use a CMakeLists for actually building the project following the recommended check for existence of a conanbuildinfo.cmake within the CMakeLists.txt (from Clion). I can invoke with options from command line to choose configurations, or fall back to defaults if the file does not exist.

My difficulty is that I can't find any way to have the conanbuildinfo.cmake receive options to CMakeLists.txt unless I push them lower into a dependency.  That is, my dependencies all get CONAN_DEFINES properties, but I can't define anything for _this_ project - so my options which choose requirements have no way to flow forward to the CMakeLists.txt since there is no package_info() invoked on this conanfile and the self.cpp_info is not available outside of packaging. 

Thoughts how to forward defines from conanfile into CMakeList - or an alternative strategy that solves the problem?

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, it is explicitly modeled that way, for consistency: all generators, including ``cmake`` and the generated ``conanbuildinfo.cmake`` only have access to dependencies information, but not to the current package. They work the same for a conanfile.txt, where there is no package at all, and for a *conanfile.py* which might be a package or not.

Configuration for the current package itself are typically in the build system of the package. The ``build()`` method can typically define some things, like:

```python
def build(self):
    cmake = CMake(self)
    if something:  # e.g. if self.options.myoption:
         cmake.definitions["MY_PROJECT_DEFINITION"] = "Something"
    cmake.configure() 
    ...
```
The overall idea is that building the current project should be easy to build both via the conan package recipe and the native build system (calling cmake by hand, or opening the VS IDE, etc).

Please tell me if this makes sense, or elaborate a bit further your use case, what defines you want to forward from the recipe that cannot be directly put in the CMakeLists.txt. Thanks!

**Comment by drmacdon** [comment]
One scenario at a top level project which is pulling in requirements for a CMakeLists, you might have:  

```
options = { "with_spdlog": [True, False],
                   "with_glog": [True, False] }
default_options = { "with_spdlog=True", "with_glog=False" }
def requirements(self):
    if self.options.with_spdlog:
        self.requirements("spdlog/0.14.0@bincrafters/stable")
    if self.options.with_glog:
       self.requirements("glog/0.3.5@bincrafters/stable")
```
And a CMakeLists.txt which simply pulls in the definitions,
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```
When I'm running cmake, it does not have any context about how the conanbuildinfo.cmake was constructed and with which options unless I pass them on the command line to cmake which means duplicating the definitions and a chance to be inaccurate. I would have liked to have been able to set defines in the conanbuildinfo.cmake more conveniently then writing my own file with a couple properties to load. 

The actual scenario that I am using it for is a bit more involved so that I can choose to load libraries into Clion via a conan binary package or from source directly (which in turn may involve conan binary packages or sources directly.) Why? It's faster when working on both a library and product to have the library as a sub-project until you want to package it. So, when I want to work on a library I pass the conan install an option 'libA.src=/path/to/sources' which skips the self.requires(). The CMakeLists having the location of the sources (wishfully via conanbuildinfo.cmake, currently either environment or writing an additional custombuildinfo.cmake) performs a conan install on the library sources to a sub-folder of the working directory. The logging example might have been easier to follow. ;-) 

When writing a conanfile.txt or conanfile.py for retrieving dependencies I would think most times people are also writing the CMakeLists to build at the same time and you have to import your target dependencies so why not offer the ability to forward cmake defines from conan even when there is no package?

**Comment by sourcedelica** [comment]
Also related to #1377

**Comment by wpalfi** [comment]
@drmacdon I had exactly the same idea (passing libA.src as an option to `conan install`). Later I realized that this would be a heavy misuse of the install command. `conan install` should install required packages and do nothing else. So you should only pass "requirement-options" to `conan install`, no "build-options". 

You can use an option `requireLibA`, and in your CMakeLists.txt use something like 

```cmake
if(CONAN_LIBA_ROOT) 
  message(STATUS "found LibA conan package")
  if(LIBA_SOURCE_PATH)
    message(STATUS "LIBA_SOURCE_PATH ignored")
  endif()
else()
  message(STATUS "building LibA from source")
  if(NOT LIBA_SOURCE_PATH)
    message(FATAL "please set LIBA_SOURCE_PATH")
  endif()
  add_subdirectory(${LIBA_SOURCE_PATH} LibA)
endif()
```
```

**Comment by wpalfi** [comment]
Also related to my #2304

**Comment by drmacdon** [comment]
@wpalfi Thanks. I guess the line between requirement-options and build-options is a bit blurry. 

To make your design work, a normal install/build would be the typical:

```
    cd build
    conan install .. conan/test --build missing
    cmake ..
```

To build from sources,
```
    cd build
    conan install .. conan/test --build missing -o WITHOUT_LIBA=True
    cmake -DLIBA_SOURCE_PATH=$LIBA_SOURCE_PATH ..
```
Which could work for trivial requirements but breaks when dealing with more complex package hierarchies. If I have even a simple 3 packages hierarchy, 

               LIB_A
              /      \
          LIB_B     LIB_C

When installing LIB_B with conan option WITHOUT_LIBA and LIB_C WITHOUT_LIBA by informing CMAKE, CMAKE the build system knows more about my packaging of LIB_B and LIB_C then conan the dependency manager. 

When later, LIB_D decides to pull in LIB_B and LIB_C they might very well have been compiled with different LIB_A sources because all conan has captured is the simple flag WITHOUT_LIBA. In order to ensure that conan does differentiate the library sources of A placed in LIB_B and LIB_C when they are built it means providing some unique identifier rather instead of a boolean. 

Then we end up back where you and I started - passing a src location instead of the boolean for the dependency management aspect of conan.... and when that occurs we end up with:
```
    cd build
    conan install .. conan/test --build missing -o WITHLIBA_SRC=$LIBA_SOURCE_PATH
    cmake -DWITHLIBA_SRC=$LIBA_SOURCE_PATH ..
```
which feels redundant when the packaging options could have been included in the conanbuildinfo.cmake.

**Comment by wpalfi** [comment]
We are using WITHOUT_LIBA as a local developer feature. I dont think that it makes any sense to use it for packaging.

**Comment by drmacdon** [comment]
Yes, building with sources is only useful as a developer.  As a developer sometimes I want the sources when debugging/testing but often I can get by with just the packaged library. 

My point above was it works reasonably well as you said for an immediate dependency, not so well when the dependency is from a dependency... which is the point of using a dependency manager.

**Comment by wpalfi** [comment]
We are using that also for more complex dependency graphs. You can build multiple libraries of the graph from source and link them with CMake. All libraries that depend on such a locally built library must also be built from source. And yes, its only useful if you dont build too much libraries at once. But that is not a conan issue.

**Comment by LeeRuns** [comment]
> 
> 
> Yes, it is explicitly modeled that way, for consistency: all generators, including `cmake` and the generated `conanbuildinfo.cmake` only have access to dependencies information, but not to the current package. They work the same for a conanfile.txt, where there is no package at all, and for a _conanfile.py_ which might be a package or not.
> 
> Configuration for the current package itself are typically in the build system of the package. The `build()` method can typically define some things, like:
> 
> ```python
> def build(self):
>     cmake = CMake(self)
>     if something:  # e.g. if self.options.myoption:
>          cmake.definitions["MY_PROJECT_DEFINITION"] = "Something"
>     cmake.configure() 
>     ...
> ```
> 
> The overall idea is that building the current project should be easy to build both via the conan package recipe and the native build system (calling cmake by hand, or opening the VS IDE, etc).
> 
> Please tell me if this makes sense, or elaborate a bit further your use case, 
what defines you want to forward from the recipe that cannot be directly put in the CMakeLists.txt. Thanks!

### I am trying to make 1 build directory with many sub directories each subdir will contain everything describing the build (ie os version, compiler, generator) 

what would i write to make the s"Something" a builtin environment variable from cmake.  I am working to create a build tree that will specify the build type, compiler, and os.  So in other words I want my build directory to look like this:



ProjectRoot/CMakeLists.txt
ProjectRoot/build
ProjectRoot/build/wsl/Debug
ProjectRoot/build/wsl/Release
ProjectRoot/build/mvsc/Debug
ProjectRoot/build/mvsc/Release
ProjectRoot/build//Debug
ProjectRoot/build/mvsc/Release


To do that I can manipulate the cmake runtime output variable as shown

here is what i have as of right now
```
    def build(self):
      cmake = CMake(self)
      cmake.definitions["CMAKE_EXPORT_COMPILE_COMMANDS"] = "YES"
      cmake.definitions["CMAKE_OUTPUT_RUNTIME_DIRECTORY"]=["${CMAKE_OUTPUT_RUNTIME_DIRECTORY}/${CMAKE_BUILD_TYPE}/${CMAKE_HOST_SYSTEM_NAME}-${CMAKE_HOST_SYSTEM_VERSION}"]
      cmake.configure()
      cmake.build()
      cmake.test() 

```

**Comment by memsharded** [comment]
This was solved some time ago with the explicit ``CMakeToolchain`` to model how to pass things to the current project, based on the current settings and project configuration
