### ISSUE TITLE
enhancement ; question; getting the latest version of a specific conan pkg 

### ISSUE THREAD

**Issue by shanifrie** [conan-io/conan#2537]
Hi,

While working with Conan on my dev project, I've encountered the following problem - I need to download the latest version of a specific package from the server, and couldn't find a way to do so without looking for the specific version number..

My project uses binary files (dlls, libs and pdbs) written by another dev team external to our company. They create those binaries and upload them to our mutual Conan server, but I couldn't find a way to download it's latest version without searching first for all the existing versions, and finding the latest one manually, with:
$conan search pkgName* -r remoteName 

Is there a method to do it that I've missed?
If there isn't, is it possible to ask for it to be added as future enhancement? this feature will be very helpful in future affords to automate the update and integration process of this project.

I'm using Conan 1.0.3 on Windows 10 pro (version 1511)

- [X] I've read the [CONTRIBUTING guide]
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, there are several ways to achieve that:

- Client side you can use version-ranges. Depend on ``PkgName/[>1.2]@user/channel``, for example. http://docs.conan.io/en/latest/mastering/version_ranges.html
- Package creator side, you have ``alias`` packages. You can create a package, like ``Pkg/latest/@user/channel`` that is like a proxy or symlink to the real version. This is done by the package creator, not consumer: http://docs.conan.io/en/latest/reference/commands/misc/alias.html

Please check them and tell me if this is what you are looking for.

**Comment by shanifrie** [comment]
Hi,
Thanks for the quick help!
The alias package is a great solution and it solves most of the problems..

It will be helpful to have an additional command line argument (say, --latest ) that will update the symbolic link automatically when a new version of that pkg is uploaded to the server, but the alias as it is right now is very helpful.

Thank you!

**Comment by memsharded** [comment]
Thanks for telling :)

Regarding the ``--latest`` option, there are some limitations like:
- It won't work if versions don't follow strict semver (and unfortunately it is very common not to use semver)
- Doing it at upload time would be a bit complicated. All conan operations regarding packages are fully done locally, and should work even offline. Then uploads are mostly plain file transfers. 

So creating the alias at upload time would be probably not very robust and complicate a lot the conan codebase. So I'd say lets keep it simple at the moment, I think this issue can be closed, if later you have further feedback or feel it is really necessary please report again and we will have a second thought.

Thanks very much for the feedback!
