### ISSUE TITLE
AutotoolsBuildEnvironment adjusting gnueabi in triplet for x86

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#2539]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

https://twitter.com/DEGoodmanWilson/status/968797501447917568

**Comment by memsharded** [comment]
Released in 1.1.1
