### ISSUE TITLE
Add AutotoolsBuildEnvironment install method

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#2541]
To help us debug your issue please explain:

- [ x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Add an `install()` method to `AutotoolsBuildEnvironment`, similar to the `CMake` `install()` method.

It's usually easier to `package()` the contents of an install directory than the contents of the build directory.

**Comment by memsharded** [comment]
To use the ``./configure --prefix=/some/path`` approach, right?

**Comment by sourcedelica** [comment]
Right, there would be some interplay between the `configure` and `install` methods.

**Comment by SSE4** [comment]
I use `env_build.make(args=['install'])` it has the same effect

**Comment by sourcedelica** [comment]
Right, that's what I've been using too.  

Here's an example of what I'm thinking about:

    def build(self):
        # ....
        env_build.configure(configure_dir=self.source_subfolder, args=args,
                             install_dir=self.install_subfolder)
        env_build.make()
        env_build.install()

    def package(self):
        inc_src = os.path.join(self.install_subfolder, 'include')
        lib_src = os.path.join(self.install_subfolder, 'lib')
        bin_src = os.path.join(self.install_subfolder, 'bin')
        self.copy('LICENSE*', src=self.source_subfolder)
        self.copy('*.h',      dst='include', src=inc_src, keep_path=False)
        self.copy('*.dylib',  dst='lib',     src=lib_src, keep_path=False)
        self.copy('*.so',     dst='lib',     src=lib_src, keep_path=False)
        self.copy('*.so.*',   dst='lib',     src=lib_src, keep_path=False)
        self.copy('*.a',      dst='lib',     src=lib_src, keep_path=False)
        self.copy('*',        dst='bin',     src=bin_src, keep_path=False)

I guess you're right @SSE4, having an `install()` doesn't necessarily gain you that much except a more consistent API across build helpers.  The real work would go into adding the `install_dir` parameter to `configure()`.

**Comment by danimtb** [comment]
This feature was already added in PR #2717 for [Conan release 1.3](https://docs.conan.io/en/latest/changelog.html#april-2018). Now `--prefix` is configured by default to package folder and you can still configure a custom folder with it as done before. There is also an `install()` method as in the CMake helper. Check the docs here: https://docs.conan.io/en/latest/reference/build_helpers/autotools.html#install

Closing this for now but feel free to comment/reopen if needed. Thanks!
