### ISSUE TITLE
Make recipe base classes more feasible

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#2542]
To help us debug your issue please explain:

- [ x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Consider the examples from [How to reuse Python code in recipes](http://docs.conan.io/en/latest/howtos/python_code_reuse.html).  

In the [Requiring a Python package](http://docs.conan.io/en/latest/howtos/python_code_reuse.html#requiring-a-python-conan-package) example the recipe requires a package and then it can reuse code in the `source()`, `build()`, `package()` and `package_info()` methods.

```
from conans import ConanFile

class HelloPythonReuseConan(ConanFile):
    requires = "HelloPy/0.1@memsharded/testing"

    def build(self):
        from hello import hello
        hello()
```

This is great!  Made even better by #1037.

However in the [Base Class](http://docs.conan.io/en/latest/howtos/python_code_reuse.html#sharing-a-python-module) example:

```
from conans import ConanFile
from base_conan import ConanBase

class ConanFileToolsTest(ConanBase):
    name = "test"
    version = "1.9"
```

it's unclear how this is supposed to work.  Where is it supposed to get `ConanBase` from?  I scratched my head and figured out that you need to set a proper `PYTHONPATH` in your environment for this to work.  For example, developers would need to set `PYTHONPATH`  correctly to run many `conan` commands.  CI would need to have it set, etc.   This is error-prone.

I would like to extend the "Requiring a Python package" concept further to allow Python code from Conan packages to be used anywhere in a recipe, including the class definition to allow base classes to come from Conan packages.  One way to do this is to add a `[requires]` section to the profile.  There is already a `[build_requires]` but recipe class definitions are needed beyond building.  

I've refactored my corporate recipes to use base classes and it's amazing how nice and clean they are.  For example:

```
from environment.conan.base_conan import BaseConan

class CoreUllConan(BaseConan):
    name = 'core-ull'
    description = 'core-ull library'

    # Dependencies
    requires = (
        'jsoncpp/1.8.4@theirix/stable',
        'spdlog/0.16.3.1@idbdevbuild/stable'
    )
```

**Comment by memsharded** [comment]
Yes, you are right, the base class example is based on some python code that is ``exports``=exported with the conanfile, but won't work for python code inside dependencies.

I think this could be a duplicate of: https://github.com/conan-io/conan/issues/1271

The approach you followed is clean and simple, IMHO, but the problem is that they are not self-contained. It is perfect for private development. But your ``environment`` won't work if you put them in bintray to share with the community, or am I missing something?

**Comment by sourcedelica** [comment]
Ahh - I should have figured that this had been requested before. 

Yes - say that I create a Conan package called `recipe-utils` that has the Python code for `environment.conan.base_conan` and sets the `PYTHONPATH` accordingly.  This feature should add that `PYTHONPATH` to the overall `sys.path`.

This use case would not need to support any options or settings for `recipe-utils`.  It's purely for code reuse.

I'll close this and continue the conversation on #1271.
