### ISSUE TITLE
Invalid remote 

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#2544]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.0.4

Selecting an invalid remote name should result in an error. When using `-r foo`, if `foo` is not a known remote, generate an error. Currently, at least `conan install` and `conan create` do not generate an error, they simply ignore the parameter.

If an error is not OK, perhaps at least a warning that the remote is unknown would be nice. This was detected because a typo; mistyping -pr as -r caused a great deal of confusion before realizing that the parameter had a typo :)

**Comment by memsharded** [comment]
To make sure: they will definitely fail, if the remote is used. If everything is found in the local cache, the remote will never be used and won't error, but if something is not local, then it will fail, right?

I am not opposed to fail fast if the remote is wrong, it can't be considered breaking IMO.

**Comment by mpdelbuono** [comment]
Yeah this is only in the case where accessing the remote is unnecessary. If the package was not found in the local cache, then an appropriate error of "no remote 'foo' defined" shows up.

I think the fail fast is preferable only because of the scenario discussed earlier: a parameter typo was unnoticed. However, I think this is very low priority because it definitely falls under the "operator error" use cases. Just a "nice to have" because -pr and -r are so close to each other.

**Comment by uilianries** [comment]
Hi all!

The current Conan version 1.18.1, will fail if a remote name is not listed in your local cache:

    conan install zlib/1.2.11@conan/stable -r conan-center # okay
    conan install zlib/1.2.11@conan/stable -r foobar # zlib is installed 
    ERROR: No remote 'foobar' defined in remotes
    conan new -s foo/0.1.0 # let's create a new template to run conan create
    conan create . user/channel -r foo
    ERROR: No remote 'foobar' defined in remotes

I think we can close this issue.

**Comment by danimtb** [comment]
Confirmed this is working fine in Conan 1.19 too. Thanks @uilianries!
