### ISSUE TITLE
provide man pages (man conan)

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#2548]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

it would be helpful and consistent for mature utility like conan to provide documentation in man pages format, so `man conan` can be used to get help in terminal. requested by slack user.

**Comment by dascandy** [comment]
As a user I would like there to be man pages so that I can look up how to use the command-line tool from the command line when I've made a mistake / need to consult documentation.

**Comment by memsharded** [comment]
Not sure about the extra effort of dedicated man pages (that are not multi-platform).

@dascandy for the command line tool you have the ``$ conan help <command>`` or ``$ conan <command> --help`` Not enough to quick check command line basic usage?
