### ISSUE TITLE
Option "*:shared=True" is ineffective for manual install dependencies?

### ISSUE THREAD

**Issue by bryceschober** [conan-io/conan#2551]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.1.0 on Linux x64

I'm a newbie here, but I'm just trying out a manual install of boost and failing. I first tried `conan install boost/1.66.0@conan/stable`, and it failed on the bzip2 dependency with :
```
bzip2/1.0.6@conan/stable: WARN: Can't find a 'bzip2/1.0.6@conan/stable' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=4.8, os=Linux
- Options: fPIC=True, shared=False
- Package ID: 3a5f72c8cd50641b8efa6ed13e6914c6ced2747c

ERROR: Missing prebuilt package for 'bzip2/1.0.6@conan/stable'
Try to build it from sources with "--build bzip2"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

I thought, OK I could build it, and I followed the docs to find `-b missing` for all dependencies, but then I noticed that shared=False and I kinda wanted the shared-library version anyway. So looking through the docs I eventually found how to specify that option for all packages and tried `conan install boost/1.66.0@conan/stable -o '*:shared=True'`, but it yields the identical error result, indicating that it's still looking for a static version of bzip2.

Then I tried installing bzip2 directly as a shared library using `conan install bzip2/1.0.6@conan/stable -o '*:shared=True'` and indeed a pre-built package is still not available, but at least the shared option I specified was reflected:
```
bzip2/1.0.6@conan/stable: Installing package
Requirements
    bzip2/1.0.6@conan/stable from 'conan-center'
Packages
    bzip2/1.0.6@conan/stable:1dc495498881745765697cb6dda04bd63bec32e0

bzip2/1.0.6@conan/stable: WARN: Can't find a 'bzip2/1.0.6@conan/stable' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=4.8, os=Linux
- Options: fPIC=True, shared=True
- Package ID: 1dc495498881745765697cb6dda04bd63bec32e0

ERROR: Missing prebuilt package for 'bzip2/1.0.6@conan/stable'
Try to build it from sources with "--build bzip2"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

All that said, I now know that I must indeed build the dependencies, but I'm still confused about why the boost install went looking for non-shared versions when I specified the shared option, and am not particularly confident that using `conan install boost/1.66.0@conan/stable -o '*:shared=True' -b missing` will result in what I want.

**Comment by bryceschober** [comment]
... and indeed looking at its output, I see a static library built, but no indication of a shared library.

**Comment by memsharded** [comment]
I think the issue is not related to conan, but related to boost. It seems that boost needs to link bzip2 statically, otherwise it doesn't work. The recipe of boost is defining this setting upstream.

Then, it doesn't matter if you install the bzip2 in a separate install with the options (shared) you want, when you install boost it will use the static one. Note that many different binaries can be simultaneously installed, but only once will be used when you do a conan install of boost. I think it might be the same for the zlib dependency. It can be seen in the boost recipe (via ``conan get boost/1.66.0@conan/stable -r=conan-center``):

```python
 def configure(self):
        if self.zip_bzip2_requires_needed:
            self.requires("bzip2/1.0.6@conan/stable")
            self.options["bzip2"].shared = False

            self.requires("zlib/1.2.11@conan/stable")
            self.options["zlib"].shared = False
```

So, please try to install:

```bash
$ conan install boost/1.66.0@conan/stable -o *:shared=True -o bzip2:shared=False -o zlib:shared=False
```

And let me know how it goes. Thanks!

**Comment by bryceschober** [comment]
Well, It actually works fine and builds everything static as boost requires even if I specify `*:shared=True`, it's best that way for newbs like me. ;-)

**Comment by memsharded** [comment]
Good, thanks for telling!
