### ISSUE TITLE
Detected architecture is 64 in docker x32

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#2552]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Latest Conan. Both the detect and the code that uses Autotools helper to set the --build parameter is missdetecting the arch. Not a new issue but raised again for the autotools use case.

Latest investigations pointed to kernel of 64 (shared by docker)

**Comment by lasote** [comment]
Note: it has a workaround in the configure method of the autotools helper to avoid the --build flag. Do it is not a blocked for the creator, but could be a problem for the consumer.

**Comment by lasote** [comment]
`clang/gcc -dumpmachine` could be a possibility, but it could be tricky, because "CC" could be pointed to a cross builder, so it would depend if we are detecting default `arch` or default `arch_build`

**Comment by jgsogo** [comment]
Just a couple of related issues (I know almost nothing about docker): 

 * https://github.com/docker-32bit/ubuntu/issues/12, which leads me to the next one
 * https://github.com/ioft/dockerhub/issues/1#issuecomment-222373851

**Comment by lasote** [comment]
I've updated the docker images (x86) with the suggestion of the link you posted and it worked like a charm. The images are currently being regenerated and uploaded, so I think we can close this issue. 
For future issues, add to the dockerfile:

``ENTRYPOINT ["linux32", "--"]``
