### ISSUE TITLE
Debian 7 run issue

### ISSUE THREAD

**Issue by r2d2leboss** [conan-io/conan#2553]
If you try to use Conan on a fresh Debian 7 install and you starts it, it results in this error:

> Traceback (most recent call last):
  File "/usr/local/bin/conan", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: astroid>=1.6,<1.7

Conan version : 1.1.0
Python version : 2.7.3

Steps to reproduce : Install Conan on Debian 7 (Docker is fine) and try to run it.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Thanks

**Comment by memsharded** [comment]
I think there might be some dependencies incompatibilities for older versions of Python 2.7. Could you please try upgrading to something more modern? 
I know it is a bit inconvenient that it doesn't work out of the box, but also a bit out of our scope if those dependencies aren't supported for those versions.

I think 2.7.8 should work. Thanks!

**Comment by memsharded** [comment]
Closing this ticket as outdated, Conan no longer support Python 2.7 since years ago
