### ISSUE TITLE
Desired behavior of the virtualenv generator?

### ISSUE THREAD

**Issue by niosHD** [conan-io/conan#2556]
I am currently working on my conan exec feature (see #2461 and #2516) which reuses the virtualenv generator. Unfortunately, there are currently 0 tests for this generator so I have to write those first...

However, during test writing I discovered that the output is not consistent. On the one hand, variable assignments are always in a separated line from the export command. The following command explains why: https://github.com/conan-io/conan/blob/38fddb79ee2a4f6229b11d40994675c6f3fef488/conans/client/generators/virtualenv.py#L44-L45

On the other hand, the PS1 and the OLD_PS1 variable clearly violate this approach and perform export and assignment on the same line.
https://github.com/conan-io/conan/blob/38fddb79ee2a4f6229b11d40994675c6f3fef488/conans/client/generators/virtualenv.py#L58-L59

The same holds true for the deactivate file which does everything on the same line as well.
https://github.com/conan-io/conan/blob/38fddb79ee2a4f6229b11d40994675c6f3fef488/conans/client/generators/virtualenv.py#L75

The question now is what style we want to have? Should I fix the deactivate file and the PS1 values or do we get rid of the separated commands and do the assignment and export in the same line everywhere?

**Comment by niosHD** [comment]
Since nobody spoke up, I decided for now to go with fixing the deactivate file and the PS1 values and wrote a [test](https://github.com/niosHD/conan/blob/29d0740e37ae61cbc55441c703eeb7b34797e664/conans/test/generators/virtualenv_test.py).

Unfortunately, while testing on windows I discovered another (for me) unexpected behavior. The ordering of the elements in the PATH variable seems to be unstable meaning that I sometimes get `SET PATH=basedir\\bin;samebin;dummydir\\bin;samebin;%PATH%` and sometimes get `SET PATH=dummydir\\bin;samebin;basedir\\bin;samebin;%PATH%`. Is this a bug or intentionally undefined?

**Comment by SSE4** [comment]
for the first one, I think for portability it's better to do export and setting variable value on different lines, and do it consistently. we have no idea what sh is, it might be true ancient sh, or some symlink to bash or dash or whatever.
for the second, order of PATH components is vital, as left components take priority over right, and random ordering is definitely a bug, which may cause undesired effects.

**Comment by niosHD** [comment]
The tests and the behavior changes have now been implemented in #2621 which is up for review. On the other hand, for the bug with the unstable PATH results, a separated Issue (see #2620) has been filed. Comments are welcome.
