### ISSUE TITLE
"conan search -r all fullref" doesn't recognize remote "all"

### ISSUE THREAD

**Issue by ArekPiekarz** [conan-io/conan#2559]
#### Steps to reproduce:
`conan search -r all bzip2/1.0.6@conan/stable`

#### Actual result:
`ERROR: No remote 'all' defined in remotes in file C:/Users/Fazer/.conan/registry.txt`

#### Expected result:
This is a tricky part. Without a doubt Conan should know what remote "all" means and not display the error above. To decide what it should do instead requires knowing more about its inner workings. 

Can the same recipe reference exist in multiple remotes? I managed to find the one above in conan-center and conan-community, but then conan-center from my understanding only links to other repositories.  On the other hand, I can see ~/.conan/registry.txt contains a mapping from the recipe to remote and in this case it points to conan-center.

I can see a few options:
1) Conan should write that remote "all" cannot be used with full reference, or
1) Conan should search through all remotes for the recipe reference and display available binary packages, or
1) Conan already knows from registry.txt where to search for the recipe and based on that should display available binary packages.

IMHO it would be great if Conan provided as much automation as possible for the user and didn't require specifying a concrete remote to search for. I'm sure you will be more knowledgeable what is achievable and sensible to do in this case.

#### Additional info:
Conan version: 1.1.0
Operating system: Windows 10 x64
Subsystem: Msys2

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, I agree there is some weirdness here. The system should probably do either:

- Adequate error message saying "all" only works to search for recipes. This is the minimun that should be at least fixed.
- Do a complete search of binaries in all remotes. This might be too slow to be really useful, but shouldn't be that challenging to implement.

**Comment by ArekPiekarz** [comment]
The same problem applies to `conan get`. Do you want me to create a new issue for it?

**Comment by memsharded** [comment]
Uhm, I am not sure that conan get for every remote makes sense. While I agree that search might be useful, showing all the conanfiles (for example) for every remote, sounds a bit weird use case IMHO. I think I'd prefer to keep the ``conan get`` specific per-remote.

**Comment by ArekPiekarz** [comment]
Now I see it seems weird the way I said it. I was thinking more in the direction of automatically finding the right remote with the recipe, not getting matching recipes from all of them. I think usually in a user's setup there is only one known remote with the specific combination of package/version@user/channel, so having to explicitly write the remote name feels unnecessary. But I guess we can wait to see if more people want this enhancement too.

**Comment by Minimonium** [comment]
I'm not sure what "finding the right remote" thing means. I imagine that when users write `-r all`  they expect to find exact matches in all remotes, which is expected (at least with the current Conan behavior).
