### ISSUE TITLE
No found some popular libraries such as php-cpp, wxwidgets and so on

### ISSUE THREAD

**Issue by KaungZawHtet** [conan-io/conan#2560]
Even though Conan is the best dependency manager compatible with cmake, still lack many packages.
At least,Adding packages from this link ( http://en.cppreference.com/w/cpp/links/libs ) will make Conan more lavish. I am awaiting

**Comment by memsharded** [comment]
I don't know if you are aware of current packaging efforts by the community. For sure you want to know about:

- Follow bincrafters community: https://bincrafters.github.io/ They have their own bintray repo with 400 packages, and working very hard to provide more. Great and friendly community, they also have a #bincrafters channel in the CppLang slack team, I strongly suggest to join them
- The wishlist: https://github.com/conan-io/wishlist/issues it is used by them as input.
- The conan-maintainers also work on some packages in https://github.com/conan-community

Even with all this effort, it is impossible to target all existing C and C++ libraries, it should be an effort of the wider community, so I would encourage you to try to help and package some of your needed libraries. We try to provide as much support as possible and the community is also really helpful and supportive.

As this is not a bug that should be fix, a feature request for conan tool, and we are already working hard towards that goal, I think this issue could be closed. Many thanks for your feedback!

**Comment by KaungZawHtet** [comment]
Thanks for the good response covering adequate info.
