### ISSUE TITLE
[question] Automate conan export / bootstrap conan build from scratch?

### ISSUE THREAD

**Issue by mjbayer** [conan-io/conan#2564]
Hi,

What do you think of an automation of conan export, in order to allow bootstrapped builds from scratch?

For example, given the following setup:
- Conan Component A, depending on Component B,
- Conan Component B,
- Project C, depending on Component A,
- Empty local cache, no conan server or artifactory.
- Folder structure. In current directory, there are subdirectories for:
-- for Component A and Component B, each containing conanfile.py (and other stuff like build scripts and sources). 
-- Project C, containing conanfile.txt.

When I want to compile Project C, I have to do the following steps:
- go to Component A directory, call `conan export . asdf/testing`
- go to Component B directory, call `conan export . asdf/testing`
- go to Project C build directory call `conan install .. --build=missing`

What I would ask for is a feature like:
`conan bootstrap` 
that exports all conanfile.py of all subdirectories, so that you could directly go to the Project and run conan install.

**Comment by lasote** [comment]
It is a legit use case but very specific use case. I think we shouldn't add commands for these specific flows or we will end with a thousand conan commands.
I would recommend creating a shell script. This is my opinion! others are welcome.

**Comment by danimtb** [comment]
Maybe you are looking a feature like the conan project to develop more than one conan lib at the same time #1377

**Comment by memsharded** [comment]
Yes, definitely best is following up conversation in #1377, and maybe closing this feature? Thanks!

**Comment by mjbayer** [comment]
Thank you very much for your feedback!
Discussion in #1377 looks promising
