### ISSUE TITLE
Linux: Cannot override system libraries with libs provided by conan

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#2571]
Hi,

I've been trying to override the system libcurl provided by ubuntu with one I've built using conan, but even though I appear to set everything up correctly, my build still picks the system libcurl over the version in conan. libcurl is an essential library and can't be removed in this case. Below is an example error message I get from cmake to illustrate it's using the system libcurl:

    cmake: /home/james/.conan/data/OpenSSL/1.0.2/3rdparty/stable/package/ee7c90d5fe5de9ffdabbe02f009efc68cec08722/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)

Here is a sample from my conanbuildinfo.cmake and a console command to show that the library is set up correctly:

    $ grep LIBS_CURL conanbuildinfo.cmake 
    ...
    set(CONAN_LIBS_CURL curl)
    ...
    $ grep DIRS_CURL conanbuildinfo.cmake 
    ...
    set(CONAN_LIB_DIRS_CURL "/home/james/.conan/data/curl/7.56.1/3rdparty/stable/package/0325005698fcf57143e1eb350da50617296dc5f6/lib")
    ...
    $ ls /home/james/.conan/data/curl/7.56.1/3rdparty/stable/package/0325005698fcf57143e1eb350da50617296dc5f6/lib/libcurl.so 
    /home/james/.conan/data/curl/7.56.1/3rdparty/stable/package/0325005698fcf57143e1eb350da50617296dc5f6/lib/libcurl.so

Is this expected behaviour? I definitely don't want software to be silently linking against the system libraries over the packages conan has provided.

Many thanks.

**Comment by jamezmoran** [comment]
Nevermind, I checking the binary with ldd and it appears it's linked against the correct libcurl from conan. I'll re-open if I see any issues using the binary.

**Comment by memsharded** [comment]
Glad that you solved the issue.
Indeed conan should use the one provided by the package. There might be rare errors, like if the package is incorrectly created with an architecture that doesn't match the declared one, that the linker might skip it and fallback to the system installed one.

Sure, please re-open or comment again if you think this happens again. Thanks!
