### ISSUE TITLE
Add new method and command "configure_build()" to conanfile to be able to separate configure step from build

### ISSUE THREAD

**Issue by Aalmann** [conan-io/conan#2573]
Hi @memsharded and @lasote 

there should be a new method and command "configure_build" to be able to just trigger the configuration of a build (e.g. CMake generator run) without building the package. That would be very useful for developer, especially when developing huge packages or a huge amount of packages.
This would also be a first step for a single development VS solution.

Our current solution is to check an environment variable after configure CMake step and raise an exception, which is not really nice.

Aalmann

**Comment by niosHD** [comment]
Hi Aalmann, I think this feature request is already discussed in #2499.

Best
Mario

**Comment by Aalmann** [comment]
Hi @niosHD 
you are completely rigtht. Thanks for the hint. It's exactly the same.
