### ISSUE TITLE
Add option or command to faster republish packages between different remotes

### ISSUE THREAD

**Issue by Aalmann** [conan-io/conan#2574]
Hi @lasote and @memsharded 

we are using two remote repos for internal development and for deployment to the end-users. The internal remote is used for ci builds for all channels. Because we have some additional integration and system tests packages (extra test package which depends on the package), it is not possible for us to upload the stable packages directly to the other remote.
However, so we have an extra job, which runs "conan download" from internal remote and "conan upload" to the new remote. 

**Problem:**
All the downloaded packages are extracted and repackaged which takes a long time.

**Idea:**
* Either add flags to download and upload commands to avoid extraction and packaging `conan download --skip-extraction ...` and `conan upload --skip-packaging ...`
* or add a new command `conan republish -fr <from_remote> -tr <to_remote> <package_ref> <optional: settings and options>`

Aalmann

**Comment by memsharded** [comment]
Good point.

Quick question: Are you using ``conan_servers``? If you are doing it you might want to go one step further. The storage of the server is really simple, similar to the client one. There is no metadata in databases or anything like that. Doing a copy of the things you want from one remote server to the other will be order of magnitude faster. And might be doable with a shell or python script of just a very few lines.

**Comment by Aalmann** [comment]
Currently we are using the conan server but we will switch to artifactory soon.
Is there something similar in artifactory ?

**Comment by markgalpin** [comment]
Artifactory has [copy](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-CopyItem) and [move](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-MoveItem) APIs you can use to directly move a conan package (that is the entire folder with the conan recipe and binary packages) from one repository to another (although there is currently a [bug](https://github.com/conan-io/conan/issues/2415) that prevents changing channels within an existing repository.) 
Additionally, if you used the build info upload to artifactory, you could also track your promotions by instead using the [promote](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-BuildPromotion) api on the build that created your conan package.

**Comment by memsharded** [comment]
the unpacking and repacking is no longer done, downloaded tarballs are stored for re-upload for speed. Closing this ticket as solved.
