### ISSUE TITLE
profiles: allow to append environment variable

### ISSUE THREAD

**Issue by roe85** [conan-io/conan#2578]
I'm using conan 1.1. on Linux. At my company, we a evaluating to transition to conan. 
Thereby, I ran into an issue regarding profiles. We have some custom versions of build tools (cmake,  compiler) installed and I thought it would be a good idea to specify the PATH in the  [evn] section of a custom profile:
[env]
PATH=/path/to/custom_gcc/bin:/path/to/custom_cmake/bin:$PATH
But there is the problem that the string "$PATH" is used directly. To make matters worse, any PATH set via package_info is also overwritten (e.g. during the test run)

**Comment by memsharded** [comment]
It is not necessary to do that, you can pre-pend paths in the profiles using list syntax:

```
[env]
PATH=[/some/path]
```
This will automatically generate a path like ``C:/SOME/PATH;C:\Users\memsharded\Envs...`` With this syntax, it should also properly manage PATH vars set in the dependencies (for build_requires, for example)

Please try that and tell me if works. Thanks!

**Comment by roe85** [comment]
thanks, that works. Is that documented anywhere? I couldn't find it.

**Comment by memsharded** [comment]
Yes, there is some explanation here: http://docs.conan.io/en/latest/mastering/envvars.html#defining-environment-variables

But I think I am going to add some other explanation in http://docs.conan.io/en/latest/reference/profiles.html too.

**Comment by memsharded** [comment]
And here it is: http://docs.conan.io/en/latest/reference/profiles.html#package-settings-and-env-vars

Please close the issue if you considered it addressed. Thanks!

**Comment by roe85** [comment]
very good!
