### ISSUE TITLE
"Missing prebuilt package" rather than requirements conflict message?

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#2579]
Recently updated to 1.1.0 so not sure this is a new issue. 

Conan version: 1.1.0
Platform: Windows
Arch: x86_64
Compiler: Visual Studio 14

I have a `conanfile.py` that lists the following requirements
`foo/1.0.0@user/channel`
`bar/1.0.0@user/channel`

the recipe for `foo/1.0.0` also has a dependency on `bar`, but a different version, e.g `0.9.0`.

In the past we would get either a warning from conan regarding the dependency tree inconsistency, or we could issue an error with `-werror`. If I'm not mistaken, the error is now the default behaviour.

However, the message I get now when running `conan install` is a bit cryptic:

```
foo/1.0.0@user/channel: WARN: Can't find a 'foo/1.0.0@user/channel' package for the specified options and settings:
- Settings: arch=x86_64, compiler=Visual Studio, compiler.runtime=MD, compiler.version=14, os=Windows
- Options: shared=True
- Package ID: 1bfe5dfc68aaec35bae3185f2a98ad1c958a9875
```

The error goes away when I change the `bar` dependency to be the same version `foo` uses too.

Should the error message not be more explicit regarding the dependency tree inconsistency? I think back in the day the message read "requirement conflict".  Or should it not at least point me in the direction if rebuilding `foo` locally with `bar` overridden to 1.0.0?

Apologies if this is the intended behaviour!

**Comment by memsharded** [comment]
Yes, you are right, the new behavior is error on conflicts, not warnings.

But it seems you don't have a conflict. Your conanfile is explicitly defining ``bar/1.0.0``, this will override the one from ``foo``.

But indeed there is something weird, but I cannot reproduce. Do you have the full recipes to try? Thanks!

**Comment by Lnk2past** [comment]
I get the same exact behavior in Conan v1.0.4, and I agree that the message is cryptic and misleading. I only knew what was actually happening because I was intentionally trying to break Conan for an assessment we are performing.

**Comment by memsharded** [comment]
Sorry @Lnk2past which error are you getting, this one?

```
foo/1.0.0@user/channel: WARN: Can't find a 'foo/1.0.0@user/channel' package for the specified...
```

Why it is so misleading? It is also giving an URL with instructions of what is happening. How would you improve such error message? Suggestions welcome.

**Comment by Lnk2past** [comment]
Hi @memsharded,

Yea, I receive a message like that. My problem with that message in this particular instance is that the problem stems from a version conflict and the message doesn't provide any indication that a version conflict is (or may be) an issue. It just mentions that it cannot find a _foo_ with those settings and options provided.

Ideally Conan would explicitly tell me that the problem stemmed from a version conflict, or at least suggest that it might be the problem.

**Comment by memsharded** [comment]
But that is the thing, there is no conflict at all if you got to that error message. If there is a version conflict, the system will error, stop the install and tell you about the conflict to be solved. If you got to a "missing pre-built binary", then the dependency graph is correct, there are no conflicts.

**Comment by Lnk2past** [comment]
@memsharded Ahh, I see. That makes sense then. Thank you for clarifying!

**Comment by memsharded** [comment]
You are welcome :)

Feel free to ask any other question, glad to help.

So I think this issue might be closed, but please @jcar87 or @Lnk2past reopen or submit new issues for further doubts. Thanks!
