### ISSUE TITLE
Linter for deprecations

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#2585]
This is just an idea to investigate:
If we want to deprecate some tools in favor of a build helper, of course, waiting for a major release to break anything, or deprecate any other thing that the user is importing/using, is there a way to tag theses methods/functions/objects in the conan codebase and warn in the linter analysis?

It could be useful to automate a scan in a repository to search for deprecated things before breaking the compat.

**Comment by memsharded** [comment]
As with the removal of pylint as import dependency, this is not possible right now. Delaying till 1.4 at least
