### ISSUE TITLE
Mysterious linker errors building shared objects on Linux possibly relating to -fPIC

### ISSUE THREAD

**Issue by DEGoodmanWilson** [conan-io/conan#2594]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.1.1
OS: Various, all from @lasote 's Docker images for GCC 4.9, 5, 6, 7 and CLANG 3.9 and 4

The error varies depending on compiler and version, but ultimately there is some problem linking when building a shared object for my project luna:

Travis build history
https://travis-ci.org/DEGoodmanWilson/luna/builds/352227051

Errors received:
GCC 4.9:
```/usr/bin/ld: /home/conan/.conan/data/libmicrohttpd/0.9.51/DEGoodmanWilson/stable/package/53c0d872390ff1e36b641bade6f15c5dc1b56392/lib/libmicrohttpd.a(libmicrohttpd_la-connection.o): unrecognized relocation (0x2b) in section `.text'```

GCC 5, 6, 7 and CLANG 3.9, 4 are all very similar to this:
```/usr/bin/ld: /home/conan/.conan/data/base64/1.0.2/DEGoodmanWilson/stable/package/90ee443cae5dd5c1b4861766ac14dc6fae231a92/lib/libbase64.a(base64.cpp.o): relocation R_X86_64_32S against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used when making a shared object; recompile with -fPIC```

Links to the referenced libraries:
https://github.com/DEGoodmanWilson/base64
https://github.com/DEGoodmanWilson/conan-libmicrohttpd

Note: Everything compiles and links just fine on OS X.

It has been suggested that the problem might simply be that binutils needs to be upgraded?

**Comment by jgsogo** [comment]
About the first one, you can get more info here: https://github.com/bincrafters/community/issues/160

**Comment by DEGoodmanWilson** [comment]
So, the deps that are triggering the errors are all ones I've built myself. Do you suppose it might be something further downstream like iconv? But then, those bincrafters builds should also be built with the same Lasote images, so I wouldn't expect a libc mis-match.

**Comment by lasote** [comment]
Make sure you update the `lasote/conangcc49` image. We changed the base image to match the most common libc version. So, everything in your dep tree should be built with the updated one.

**Comment by DEGoodmanWilson** [comment]
Would this affect builds generated automatically by Travis?

**Comment by memsharded** [comment]
Travis (with conan-package-tools) was using the wrong image some time ago, so if you had generated those packages some time ago, that might be the issue.

**Comment by DEGoodmanWilson** [comment]
OK, I'm rebuilding all the deps that I own, although all were last built within the last month. I don't own the dep for `nlohmann:json`, so I'm unsure what to do about that short of just asking the author. Anyway, we'll see where this gets us.

**Comment by DEGoodmanWilson** [comment]
@memsharded WIth all the deps recently rebuilt (I am unsure about libiconv, however), the problem persists:
https://travis-ci.org/DEGoodmanWilson/luna/builds/354338213

**Comment by lasote** [comment]
`base64` has to be built with `fPIC` in order to be embedded in the `libluna`

**Comment by DEGoodmanWilson** [comment]
OK, I swear to the old gods and the new that I tried that before. But for good measure, I tried again. This time it seems to actually be working… 🤦‍♂️ 
https://travis-ci.org/DEGoodmanWilson/luna/builds/354426487
