### ISSUE TITLE
Add support for GCC 5.3

### ISSUE THREAD

**Issue by skizzay** [conan-io/conan#26]
Looks like the most recent of the GNU C++ compiler, 5.3, isn't yet supported.
```sh
andrew@G75VW:~/Documents/Projects/cddd$ conan install
ERROR: '5.3' is not a valid 'settings.compiler.version' value.
Possible values are ['4.6', '4.7', '4.8', '4.9', '5.0']
andrew@G75VW:~/Documents/Projects/cddd$ uname -a
Linux andrew-G75VW 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by skizzay** [comment]
Looks like I had to edit `~/.conan/settings.yml`.  I should pay more attention to the [documentation](http://docs.conan.io/en/latest/reference/config_files.html).

**Comment by memsharded** [comment]
Hi @skizzay,
actually, the purpose of settings.yml is to contain some predefined values, used as a consensus about spelling, case, so every user call "Visual Studio" that way and not "VS", "Visual", "visual studio" ... So it completely makes sense to incorporate to it most recent gcc versions, I have just done it: https://github.com/conan-io/conan/commit/9a322b565e66fd20e4e4ece2c03be8ca9c70d62f

If you think that a certain setting would be useful for the whole community, please, tell so, or just change the source code and do a PR. Thanks!

**Comment by memsharded** [comment]
I have also added a migration, so next release adds these versions to existing settings.yml files: https://github.com/conan-io/conan/pull/27
