### ISSUE TITLE
`conan test` should update conans

### ISSUE THREAD

**Issue by mathieu** [conan-io/conan#260]
When using conan test, necessary packages are install if needed but if newer packages exists on the remote, they are not updated. Shouldn't `conan test` call install packages with `update=true` ?

```diff
diff --git a/conans/client/command.py b/conans/client/command.py
index b81c280..5295fea 100644
--- a/conans/client/command.py
+++ b/conans/client/command.py
@@ -210,7 +210,8 @@ path to the CMake binary directory, like this:
                               remote=args.remote,
                               options=options,
                               settings=settings,
-                              build_mode=args.build)
+                              build_mode=args.build,
+                              update=True)
         self._test_check(test_folder, test_folder_name)
         self._manager.build(test_folder, build_folder, test=True)
```

**Comment by memsharded** [comment]
Not really, at least, IMO, ``conan test`` is intended for package creators, testing their packages locally, the process is usually a ``conan export`` followed by ``conan test``, so the latest package recipe is used. 

Also consider that ``conan test`` automatically adds a ``--build=MyPackage`` being MyPackage the package being created. That is, it always force building the package from source. 

It can be overriden, with ``--build=missing`` or any other option.  But automatically updating your local packages from remotes in ``conan test`` could be confusing. 

If you want to test that the upstream packages are actually working, you could always try:

```bash
$ conan remove MyPackage* -f
$ conan test --build=never
```

Does this make sense? Please tell me if not. Thanks very much!

**Comment by lasote** [comment]
But what about the dependencies of MyPackage? Should be updated? I would prefer to manually specify it, because maybe I'm testing some custom dependency in some crazy way.
So you can execute:

```
conan install -i --update
conan test
```

**Comment by memsharded** [comment]
In my opinion, no updates at all for "conan test". If any, opt-in in ``conan test --update`` but as I said, I think this is not a real use case, as testing is mostly intended for local packages. So, yes, mostly agree with @lasote proposal, keep update explicit in the ``conan install`` command.

**Comment by mathieu** [comment]
Well there is another use case for `conan test` it is from the conan package tool. We use it extensively to build and test packages on our CI to ensure packages are valid for all our targeted platforms. The way we can ensure to build build the latest package today is by calling :
```
conan remove -f "*"
python build.py
```
But now that we are having packages with big dependencies, download time is becoming an issue.
I liked @lasote 's proposition to call update manually, thanks for your answers too @memsharded !
