### ISSUE TITLE
Bad line endings in download packages

### ISSUE THREAD

**Issue by matlo607** [conan-io/conan#2605]
# Environment
- Conan version: 1.1.1
- Git repository of the recipe:
  - homogeneous line endings: CR eol (unix)
- Git configuration on Linux:
  - nothing special
- Git configuration on Windows:
  - `core.autocrlf = true`, set CRLF eol automatically

# Reproduction steps
1) I built a package (in my case: boost-1.66.0 + some patches) on Linux and Windows (2 jenkins slaves).
The build on Linux is finished before the one on Windows.
At the end of the jobs, the following command is run on both platforms:
```
conan upload --force -r conan-matthieu --all -c "*"
``` 
The recipe of boost-1.66.0 is **versionned under git** and includes a **conanfile.py** and some **patches** (uniefied diff format) with CR eol.
When git clones the recipe's repository, it automatically adapt the line endings. Boost is built with its dependencies and the recipes of boost and its dependencies are uploaded to the conan_server (not the binaries).
Since the last uploaded recipe is the one from Windows slave, it contains CRLF eol.

2) Then on another Linux container (`.conan/data` empty), I build another package which depends on boost-1.66.0.
conan download the recipe of boost and tries to build it. The sources are patched with the following command.
```
git apply -p 1 --directory tools/build /root/.conan/data/boost/1.66.0/matthieu/testing/source/patches/1.66.0/0001-fix-python-include-path.patch
```
But failed when the last uploaded recipes comes from a Windows slave.
```
boost/1.66.0@matthieu/testing: Configuring sources in /root/.conan/data/boost/1.66.0/matthieu/testing/source
Initialized empty Git repository in /root/.conan/data/boost/1.66.0/matthieu/testing/source/boost_1_66_0/.git/
remote: Counting objects: 122561, done.
remote: Compressing objects: 100% (43492/43492), done.
remote: Total 122561 (delta 80196), reused 119101 (delta 76753)
Receiving objects: 100% (122561/122561), 139.74 MiB | 33.39 MiB/s, done.
Resolving deltas: 100% (80196/80196), done.
Note: checking out 'tags/1.66.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at a7bce0e... boost release 1.66.0
boost/1.66.0@matthieu/testing: git apply -p 1 --directory tools/build /root/.conan/data/boost/1.66.0/matthieu/testing/source/patches/1.66.0/0001-fix-python-include-path.patch
/root/.conan/data/boost/1.66.0/matthieu/testing/source/patches/1.66.0/0001-fix-python-include-path.patch:18: trailing whitespace.
# Use python-config command to get default paths
/root/.conan/data/boost/1.66.0/matthieu/testing/source/patches/1.66.0/0001-fix-python-include-path.patch:19: trailing whitespace.
#
/root/.conan/data/boost/1.66.0/matthieu/testing/source/patches/1.66.0/0001-fix-python-include-path.patch:20: trailing whitespace.
local rule compute-python-config-paths ( version ? : exec-prefix ? )
/root/.conan/data/boost/1.66.0/matthieu/testing/source/patches/1.66.0/0001-fix-python-include-path.patch:21: trailing whitespace.
{
/root/.conan/data/boost/1.66.0/matthieu/testing/source/patches/1.66.0/0001-fix-python-include-path.patch:22: trailing whitespace.
    local cfg-cmd = $(exec-prefix)/bin/python$(version)-config ;
error: patch failed: tools/build/src/tools/python.jam:502
error: tools/build/src/tools/python.jam: patch does not apply
```

I suggest to adapt automatically the line endings to the one of the platform when a recipe is retrieved.
Would it be possible to implement this feature ?

**Comment by memsharded** [comment]
That is an important issue that we have considered in the past, and decided not to automatically adapt line endings. One of the main reasons, is that conan uses the hashes of the files for the manifests, and also to match the binaries with the recipe (to know about the "outdated" status).

Automatically converting line endings in different systems will make extremely challenging to manage this. What would be the format in the server? Should we force line endings on all text files? Source code too? We have been there in the past, and have a very bad experience for this. Line endings are a feature exclusively of the CVS, but not the package manager. Definitely a package manager don't want to alter or modify files at all.

I'd suggest using the same line endings in CI, in all systems. It works very well in practice. Also, for developers, I think there are practically no editors or tools that won't load unix line endings (LF) correctly.

What do you think @lasote?

**Comment by matlo607** [comment]
I finally adopted your strategy and set `core.autocrlf` to `false`.
Visual Studio seems to handle unix line endings correctly.
Thanks

**Comment by memsharded** [comment]
Good, many thanks for your flexibility.
Let us know if you find other inconvenient because of this, but you should be good. In that case, please, close the issue, and re-open if necessary. Many thanks.

**Comment by aallrd** [comment]
Hello,

I have faced the same issue and I applied the same strategy to work around it.
On my windows server, the git client is configured with `core.autocrlf = false`.
It works fine for pretty much all the situations except some corner cases.
In my situation, I am using a git patch to add on the fly a Visual Studio Project that was not bundled in the original sources. This file ends up having UNIX line endings that break the devenv process.
I used this function in my conanfile to convert this specific file:

```
def unix2dos(filepath):
    contents = open(filepath, 'r').read()
    open(filepath, 'w').write(contents.replace('\n', '\r\n'))
```

1. I think this kind of issue/ SCM configuration between Windows and Linux servers should be mentioned on the Conan documentation. I agree that Conan should not care about line endings but this kind of issue can be easily avoided if understood beforehand.

2. Would you accept a PR adding the above `unix2dos` function in the Conan tools?

**Comment by danimtb** [comment]
I see this a as a recurrent question, so definitely see your point @aallrd related to the documentation.
Maybe we can add your explanation @memsharded to the FAQ or to the How-to sections?

Regarding `tool.unix2dos()` it could be useful for other users. WDYT?
