### ISSUE TITLE
Example imports implementation for conanfile.py

### ISSUE THREAD

**Issue by jin1020** [conan-io/conan#2610]
Hello,

Noob question but I was wondering if anyone has an example of an implementation for an imports() in a conanfile.py?

I have an executable and when it runs it needs a few dlls to be in the bin directory.  

i.e in my requirements I have:
    self.requires("boost_system/1.66.0@bincrafters/stable")

And I would like to drop the boost_system.dll into my build bin folder where my exe is.  Reading the documentation, it sounds like the import() method is the one should do this but I am not sure how this is done.

Thanks in advance!

**Comment by memsharded** [comment]
Hi @jin1020 

Yes, the most basic example would be:

```python
def imports(self):
   self.copy("*.dll")
```
Have you tried it? Once you do, if it works, you want to learn about the different arguments to control the layout, you might check: http://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

Cheers!

**Comment by jin1020** [comment]
Hi @memsharded !

Thanks for the response.  This is a snippet from my conanfile.py file:

    def requirements(self):
        self.requires("zlib/1.2.11@conan/stable")
        self.requires("boost_system/1.66.0@bincrafters/stable")

    def imports(self):
        self.copy("*.dll")

When I build from visual studio, my project dll and my test exe are created and dropped in the bin folder.  However, boost_system.dll is not there.

Best Regards,

**Comment by memsharded** [comment]
Are you sure you are using boost with shared option? Make sure to use ``-o boost:shared=True`` in your profile, by default libraries are static. Also, you don't need to build, the files should be there right after the ``conan install``, and you should see a summary of imported files in the output.

Please tell me, thanks!

**Comment by jin1020** [comment]
Bah... I see what I was doing wrong.   I added dst="bin" and things work :)  @memsharded thank you for the response!!

**Comment by lasote** [comment]
Write again if you have any other question!
