### ISSUE TITLE
CONAN_PRINT_RUN_COMMANDS=1 leads to TypeError exception under python 2.7

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2612]
Consider the following test example:
```python
from conans import ConanFile
from io import StringIO
import sys
import traceback

class TestConan(ConanFile):
    name = "test"
    version = "0.0.1"

    def package(self):
        output = StringIO()
        try:
            self.run("cd .", output=output)
        except:
            traceback.print_tb(sys.exc_info()[2])
            raise
```

Let's try to run `conan create` under python 2 & 3 with or without `CONAN_PRINT_RUN_COMMANDS=1` (I run python2 tests under lasote/conangcc5 docker image and python3 tests under Windows) 

Python3:
`conan create . test/0.0.1@dbely/testing` - works
`CONAN_PRINT_RUN_COMMANDS=1 conan create . test/0.0.1@dbely/testing` - works

Python2:
`conan create . test/0.0.1@dbely/testing` - works
`CONAN_PRINT_RUN_COMMANDS=1 conan create . test/0.0.1@dbely/testing` - fails with
```
  File "/home/conan/.conan/data/test/0.0.1/dbely/testing/export/conanfile.py", line 13, in package
    self.run("cd .", output=output)
  File "/usr/local/lib/python2.7/dist-packages/conans/model/conan_file.py", line 252, in run
    retcode = self._runner(command, output, os.path.abspath(RUN_LOG_NAME),  cwd)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/runner.py", line 31, in __call__
    stream_output.write(call_message)
ERROR: test/0.0.1@dbely/testing: Error in package() method, line 13
        self.run("cd .", output=output)
        TypeError: unicode argument expected, got 'str'
```
Looks like a bug inside conan, isn't it? BTW, the way conan reports python exception (losing stack trace) is very misleading. I had to add `try/except` and `traceback.print_tb(sys.exc_info()[2])` to find out what was going on.

**Comment by lasote** [comment]
Yes, it looks like a bug, let's take a look.

About the traceback, have you tried the `conan.conf => verbose_traceback = True` or env `CONAN_VERBOSE_TRACEBACK`?

**Comment by db4** [comment]
> About the traceback, have you tried the conan.conf => verbose_traceback = True or env CONAN_VERBOSE_TRACEBACK?

 Thanks for pointing this out. That's exactly what I needed.

**Comment by memsharded** [comment]
This problem is solved with:

```python
from six import StringIO
```
