### ISSUE TITLE
Tool for running binaries in test()

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2613]
Conan 1.1

It is typical in packages in conan center to see in test_package:

```python
    def test(self):
        with tools.environment_append(RunEnvironment(self).vars):
            bin_path = os.path.join("bin", "test_package")
            if self.settings.os == "Windows":
                self.run(bin_path)
            elif self.settings.os == "Macos":
                self.run("DYLD_LIBRARY_PATH=%s %s" % (os.environ.get('DYLD_LIBRARY_PATH', ''), bin_path))
            else:
                self.run("LD_LIBRARY_PATH=%s %s" % (os.environ.get('LD_LIBRARY_PATH', ''), bin_path))
```

As this seems very easy to automate, I'd suggest creating a tool for running test binaries with this code.

**Comment by niosHD** [comment]
Is this manipulation of the `(DY)LD_LIBRARY_PATH` in the test_package actually the right way to solve the environment issue? Maybe I am completely wrong but don't we already inject the environment of the package into the build of associated test_package? Assuming that it is done, I would set up the (DY)LD_LIBRARY_PATH in the `package_info` method of the package and everything should work.

What am I missing?

**Comment by lasote** [comment]
Apple blocked the `DYLD_LIBRARY_PATH` in the environment so the only way is to specify it in the command. But about the `LD_LIBRARY_PATH` and `PATH` (for dll) should work only with the ` with tools.environment_append(RunEnvironment(self).vars):`.

**Comment by niosHD** [comment]
Thank you for the clarification regarding `RunEnvironment` and the `DYLD_LIBRARY_PATH` behavior. Since I am not an Apple user I was not aware that they treat `DYLD_LIBRARY_PATH` special.

**Comment by memsharded** [comment]
@lasote I am thinking that the best location to implement it could be just the ``self.run()`` conanfile method? So it is easy to call any command from dependencies not only for the ``test()`` method, but for any other reason?

**Comment by lasote** [comment]
Yes, maybe.
