### ISSUE TITLE
--update=<pattern>

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#2615]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan 1.1.0

Is there a way to update only packages with a reference pattern? Eg. `boost_*` or `*@user/channel`?

Right now I use `conan install .. --update` but that updates all requirements which can take a long time. I can do `conan install <ref> --update` but that is only useful for single packages. Something like `conan install .. --update <pattern>` would be perfect.

**Comment by sourcedelica** [comment]
I would use it to update aliases.  My aliases are all in the form `‘*.x@user/channel`

**Comment by lasote** [comment]
Currently, there is no way to do it. To confirm, the issue is that check all is time expensive, right?

**Comment by wpalfi** [comment]
Yes. We often update our development packages from the local conan server. I just tested with a command that installs 75 packages. It takes a few seconds without --update and four minutes with --update, even if everything is already up to date.

**Comment by AbrilRBS** [comment]
Implemented for Conan 2.1, to be released momentarely
