### ISSUE TITLE
I need a way to list the package ids for a given reference

### ISSUE THREAD

**Issue by sturmf** [conan-io/conan#2616]
E.g. I would want to do something like this:

    conan search Boost/1.66.0@user/stable --ids

and would get an output like this:

    1fbed831a364d4b0ce63ad1d20a4c6b324f20910
    6a3601c7163ab2a2ee6f6587dd9f9046c12c2876
    ...

I hope something like this is already possible. I don't mind the format of the return value. I can parse this in python.

**Comment by sturmf** [comment]
Hmm I'm on a different computer now and with the latest conan version the search does exactly what I would expect. So a conan search spits out all the information I need.

**Comment by memsharded** [comment]
Yes, right now you can parse it from the output. It is on the roadmap that commands are able to output json too, which would be way easier to process.

**Comment by memsharded** [comment]
Hi @sturmf 

This might be the result of a failed migration in the Artifactory upgrade. I suggest contacting Artifactory support, I will try to have a look too. Thanks for reporting.

**Comment by sturmf** [comment]
Just as a follow up since you said you might look into it.
If I do this I get: 

    conan search 1.66.0/integration@Boost/stable -r artifactory
    There are no packages for pattern '1.66.0/integration@Boost/stable'

The weird reference is du to the fact of the broken artifactory server. As you can see the recipe is found but not packages. But I can download a package by giving the package id directly:

    conan download -p 4ec89ae26843442f955ab6e99b99fc8465076558 1.66.0/integration@Boost/stable -r artifactory
