### ISSUE TITLE
Rename a remote

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#2618]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan 1.1.0

Currently, the only way to rename a remote is to remove it, and then add it with a new name. 
- This breaks existing reference-remote-associations.
- The old name must be known.

Solutions could be 
- `conan remote rename old_name new_name`
- `conan remote add remote_name remote_url --rename`
- `conan remote add remote_name remote_url --force`

I would prefer the last solution. It always works, no matter if there is an existing remote.

See also https://github.com/conan-io/conan-package-tools/issues/156#issuecomment-373639997

**Comment by memsharded** [comment]
Agree, this is a valid feature.

Yes, maybe the last one is the most practical, but we can have also the ``rename``, it is not incompatible, I vote for both.

**Comment by memsharded** [comment]
Support for renaming has been implemented, will be in 1.3

Regarding ``add --force``, I am not sure, as it is not well defined regarding the ordering:
- If the remote exists, will the add replace just the URL, but keep ordering? Or will it add at the end, as defined by the ``add`` semantics?
- What does it mean regarding existing URL? If the URL already exists, then it is the equivalent of the rename? Will it keep the order of the renamed remote or added to the end of the list?

**Comment by memsharded** [comment]
Finally both approaches have been implemented:
- ``conan remote rename``
- ``conan remote add --force``: this will follow the ``add`` logic, regarding insertion or append at the end
