### ISSUE TITLE
How to properly create a module that provides static resources?

### ISSUE THREAD

**Issue by DEGoodmanWilson** [conan-io/conan#2626]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Latest conan, all operating systems.

There are a few moving parts to this:

We begin our story with mime-db
https://github.com/DEGoodmanWilson/conan-mime-db
This project is basically a Conan wrapper around a versioned JSON file (from https://github.com/jshttp/mime-db )

This JSON file is then consumed by libmime
https://github.com/DEGoodmanWilson/libmime
which loads the JSON file at runtime, and provides a C++ interface for querying the contents of the file. The conanfile looks at the res path for mime-db, and exposes it through an exported macro definition in package_info():
```
 self.cpp_info.defines.append("MIMEDB_FILE=\"{0}/db.json\"".format(self.deps_cpp_info["mime-db"].res_paths[0]))
```

libmime is consumed by luna.
https://github.com/DEGoodmanWilson/luna
This mechanism of exporting a C macro works for compiling Luna's tests and so forth.

But, you can imagine what comes next. When precompiled binaries of Luna are distributed, the path to the JSON file in mime-db is hard-coded to a path on the Travis server that built luna. So when you create a new project that imports luna, you get a nasty run-time exception because libmime cannot find the file exported by mime-db

Clearly I'm not entirely sure what I'm doing.
So what _is_ the correct way / idiomatic way to export resources from a package like this? How should I structure mime-db/libmime/luna so that the runtime errors are avoided (and so that _other_ software can use libmime, too)?

**Comment by memsharded** [comment]
I think there could be different approaches for this. Indeed you cannot embed an absolute path in the libraries or application, to external resources, irrespective of the usage of conan. Some ideas:

- Embed the file in the library while building it. I have done it for convenience. For this your generate a source file in the conanfile.py of libmime, it is just a couple of lines of python. But I see this file is very large, maybe you don't want to embed it in the library. Maybe zipping it?
- In libmime, use an env-var for the file path + default fallback to current directory. Runtime information is to be provided by runtime means. Then, the consumer application typically does an ``imports()`` to fetch the json file to the current binary dir, so the file is there when running
- If you want the json file to be installed in the system, maybe use the ``deploy()`` method in mime-db package, then run ``conan install mime-db`` package to get the file in the system.

I think it is necessary to define first how is the runtime environment for final users of the library, irrespective of conan. Please tell me what you think about the above. Thanks!

**Comment by DEGoodmanWilson** [comment]
OK, I took the second option, and gave setting an env var in the package_info() of mime_db, and as expected, the env var is propagated to the end project's conanbuildinfo.txt correctly. But that's where it ends. The final project is using a conaninfo.txt (not a python file) with CMake, and the resulting environment variables do not end up in the CMake configuration. Am I doing something wrong? How do I get the resulting environment variable to actually be used when I build and run the final project, short of manually copy-and-pasting it myself. It would be great if there was a way to do this automatically, so my end users don't have to jump through weird hoops. I suppose that the answer is that I have to use a conanfile.py, and implement the `imports()` method, but this is super developer-unfriendly.

I don't want to go the first route, because the JSON file is versioned, and I want to mirror that versioning seperately from the C++ wrapper for it.

I'm not sure how the third route works…

**Comment by DEGoodmanWilson** [comment]
Obviously, I'm asking the impossible, as there is no way to set the environment like this, unless the user does so explicitly. Which leads me to wonder if that really is the best way.

It seems that the first route is probably the right thing to do after all. But I'm unsure how to make this work right…I'm going to meditate on this for a while. Your input is very welcome in the meantime :D

**Comment by DEGoodmanWilson** [comment]
OK, I've done something like the first option, it seems to be working. I am using the `imports` method in libmime to copy the json file over, then calling `xxd -i` to wrap it in a C header file, which is then compiled into libmime. This is not my favorite way of doing things, TBH, but it works.

**Comment by memsharded** [comment]
> OK, I took the second option, and gave setting an env var in the package_info() of mime_db, and as expected, the env var is propagated to the end project's conanbuildinfo.txt correctly. But that's where it ends. The final project is using a conaninfo.txt (not a python file) with CMake, and the resulting environment variables do not end up in the CMake configuration. Am I doing something wrong?

I am not sure if I understood correctly. If you get it to the end project correctly, it works. What is the difference between the end project and the final project? What do you mean that the final project is using a ``conaninfo.txt``, do you mean a ``conanfile.txt``? In any case it should still generate the correct information with the env-var that could locate the file.

In any case, I wasn't talking about conan env-vars or packages. I was talking about relocatable apps without conan, just getting the binary + json file (via imports/deploy), then you can run that app from its folder, and the app will locate the json file, or using a convenience env-var (not defined by conan, but by the end user, in case they want to put the app in /usr/bin and the file in /etc/mime/, for example.

I get the point that you don't want to embed the json file, it is sometimes very convenient for simplicity, but there could be good reasons to keep this file outside of the app.
It depends on the flow, maybe we can discuss the details in slack. Thanks!

**Comment by DEGoodmanWilson** [comment]
The problem is while the environment variable shows up in `conanbuildinfo.txt`, there's no way to alert the user as to how to use that environment variable, in most cases. And if you were, using `luna` requires the developer to properly set environment variables, which I don't like from a DX point of view. But it's moot if that wasn't what you were suggesting. I think I see what you're talking about now, and I might try pursuing that in the future, in fact.
