### ISSUE TITLE
build_requirements is ignored when "conan build ." is invoked

### ISSUE THREAD

**Issue by L-M-V** [conan-io/conan#2627]
## Overview 
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
Conan: Conan version 1.1.1
Operating System: Windows 10
Compiler: Visual Studio 2017
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I currently do not have cmake installed on my machine, but use it to compile all of my packages with

```
    def build_requirements(self):
        self.build_requires("cmake_installer/3.10.0@conan/stable")
```

I am now trying to use conan for development of an application (as a consumer). However I get the following:

## conanfile.py
```
class ExampleConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    default_options = ""

    def build_requirements(self):
        self.build_requires("cmake_installer/3.10.0@conan/stable")
    
    def requirements(self):
        <SNIP>

    def imports(self):
        self.copy("*.dll", src="bin") # From bin to bin
        self.copy("*.dylib*", src="lib") # From lib to bin
        self.copy("*.so*", src="lib")

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```
## Command Line
```
>conan install . --install-folder build
<SNIP>
>conan build . --build-folder build
Project: Running build()
'cmake' is not recognized as an internal or external command,
operable program or batch file.
```
Adding `self.copy("*.exe", src="bin")` to imports is bad, because although it finds it, it's not going to have the right stuff, and we don't want to copy cmake to our build directory anyway. 
```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in

CMake Error: Error executing cmake::LoadCache(). Aborting.
```

Is there a way to use build_requirements for this, or will I have to install CMake?

**Comment by memsharded** [comment]
First, the strongly suggested way to use build_requires for things like cmake, is to use the ``profile`` build requirements. Please check them. The idea is that the recipe shouldn't force the retrieval of cmake, as most users will already have it. There is no hard line there, but in general, tools that are typical for developers should go in profiles, while things that are very specific of a package (like a testing framework) can go on the recipe.

Said that, the build requirements should work for ``conan build`` too, I will have  a look, thanks for reporting.

**Comment by memsharded** [comment]
I have just tried, and it works fine to install and use CMake (tried in Windows).

I have tried it with the example code generated with ``conan new Hello/0.1 -s``, so there might be something in your recipe that might or in the commands ``<SNIP>`` that might be affecting. Could you please try first with the recipe generated with ``conan new``, and without those ommitted commands? Also maybe clean the cache with ``conan remove "*" -f``, just in case the cmake package was corrupted?

Thanks!

**Comment by L-M-V** [comment]
Yeah I've read that advice about using the profile build requirements, it has it's advantages (the user already has it) but it has it's downsides too. My reasoning below (feel free to point out other solutions / approaches!)

If a particular package has a CMakeLists.txt that only supports a certain version of CMake and that user's particular cmake is out of date - the user simply won't be able to compile the package. It's better to put that requirement into the recipe with something along the pseudocode below:
```
if (where(cmake) == false || (CMAKE_VERSION < 3.1)):
    self.build_requires(cmake...)
```
It's a similar situation to a compiler version, certain packages no longer support older version of C++, these packages simply will not build with an older version of CMake. 

The other bonus of forcing the particular cmake into the recipe is that you get consistency for the particular package across all of the users in the build process. One of my main goals of using Conan is reduce the overhead of getting up and running on my particular project, and the less difficulty, the better. The users (scientists) I'm targetting are not experienced programmers, if I get my project down to:
```
1. Install Conan.
2. Execute python InstallPackagesBuildDependenciesAndApplication.py
```
Then I can really reduce the complexity of getting up and running and they can get back to making modifications to the source code that they understand (the calculations). Each additional step (such as installing CMake) can add to that complexity so I'm really trying to make it as simple as possible.

**Comment by L-M-V** [comment]
I'll give the example a go now, and will report back.

**Comment by L-M-V** [comment]
Yes, clearing my conanrepo has fixed the issue. Sorry about the issue report when it was user error!

Not sure if it was related but previously my repo had become corrupted when a Package.count was written incorrectly with "\x00"(NUL) instead of "0". I'm not sure what exactly caused it but I believe at the time I accidentally wrote `def requires(self):` instead of `def requirements(self):` in a recipe.

Here was the error at the time:
```
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\conans\client\command.py", line 1131, in run
    method(args[0][1:])
  File "c:\program files\python36\lib\site-packages\conans\client\command.py", line 217, in create
    test_build_folder=args.test_build_folder)
  File "c:\program files\python36\lib\site-packages\conans\client\conan_api.py", line 64, in wrapper
    return f(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\conans\client\conan_api.py", line 261, in create
    self._manager.export(conanfile_path, name, version, user, channel, keep_source)
  File "c:\program files\python36\lib\site-packages\conans\client\manager.py", line 155, in export
    self._user_io.out, self._client_cache)
  File "c:\program files\python36\lib\site-packages\conans\client\cmd\export.py", line 43, in cmd_export
    with client_cache.conanfile_write_lock(conan_ref):
  File "c:\program files\python36\lib\site-packages\conans\util\locks.py", line 83, in __enter__
    readers = self._readers()
  File "c:\program files\python36\lib\site-packages\conans\util\locks.py", line 55, in _readers
    return int(load(self._count_file))
ValueError: invalid literal for int() with base 10: '\\x00'

ERROR: invalid literal for int() with base 10: '\\x00'
```
I removed all .count files, and the repository was 'fixed'. 

Thanks for your time Memshared, I appreciate the effort you're putting into this project! It's such a cool tool.

**Comment by memsharded** [comment]
Regarding the feedback, the approach I prefer (just personal preference):

- Define cmake_minimum_version in CMakeLists.txt. Build will fail with a clear error message if not.
- Define the desired cmake version in a profile.
- Share the profile via ``conan config install`` with my team. 

Then the flow is:
- Install conan
- conan config install <repo-url>
- conan install -pr=myprofile (or inside your own script)

This approach scales better and is easier to maintain, IMHO, for example, to upgrade the cmake version.

**Comment by memsharded** [comment]
So yes, that error was caused by some cache corruption. They can happen also when interrupting downloads. Clearing the cache when weird things happen should be the first thing to try. There are some improvements planned in the roadmap, to check for packages integrity, that might help, but will require a few releases, not top priority now.

Thanks to you for your kind words and your feedback!
