### ISSUE TITLE
path inconsistencies with bintray

### ISSUE THREAD

**Issue by doddi** [conan-io/conan#2630]
Whilst understanding how the protocol works I noticed that the paths are inconsistent between bintray and a locally running server.

The download_url use the same convention between bintray and local server (package/version/owner/channel).
For example:
`v1/conans/jsonformoderncpp/3.1.1/vthiery/stable/download_urls` is fetched from bintray
`v1/conans/Hello/0.2/demo/testing/download_urls` is fetched from my local running conan server

From here on they diverge:
bintray serves up the remaining files like `v1/files/vthiery/jsonformoderncpp/3.1.1/stable/export/conanmanifest.txt` so it is in owner/package/version/channel path order

whereas a local server serves up the files as `v1/files/Hello/0.2/demo/testing/export/conanmanifest.txt` so it is in package/version/owner path order (same as download_url)

Although this works because the client is told what url to fetch, it is a little inconsistent.

I am parsing these paths as part of a third party plugin I am developing and I am having to adapt to the varying types of path options used.

**Comment by memsharded** [comment]
Oh yes, I understand the issue, thanks very much for your detailed report.

This is one of the reasons that there is a logic layer, the end-points for ``download_urls`` act as a layer of abstraction over the final transfer end-points. That is the reason the first ones are always the same, and the others, each server uses their own URLs. 

The reason for the difference is that conan-server is using our own format ``Pkg/version/user/channel``, and the urls matches that. It also matches the layout of the disk storage, and the layout of the conan cache.

But Bintray is hosting files for many different package types and artifacts, like NPM, pip, docker... One of the first package formats was Maven for Java. So Bintray uses the user/organization name as the first part of the URL, and it makes sense to keep that same for Conan too.

Why not getting the URLs from the ``downloads_urls`` endpoint? Cheers!

**Comment by doddi** [comment]
That is what I am currently doing but because they behave differently I dont know without configuring upfront which 'element' in the path is the package. I use package, group, version and channel for display purposes on all files that I am proxy through my plugin.

It would have been nice to parse all metadata in the same way, avoiding configuration

**Comment by memsharded** [comment]
Yes, it would have been nice if built from scratch, but not something that could be easily done when building on existing systems without disrupting too much.

I guess you can just search for "bintray" in the url and act accordingly, sorry there is no better solution.

**Comment by memsharded** [comment]
bintray closed long time ago
