### ISSUE TITLE
Install built packages into operation system

### ISSUE THREAD

**Issue by grafandreas** [conan-io/conan#2632]
Dear conan.io-Team,

I have the following use case:

    I have used conan to cross-compile a an application that uses a number of libraries from Conan Center. The built libs are in my .conan dir on the build system (created by --build=missing).
    To run the built application on the host, I need an installation of the libs there. I would like install the built libs on the host just like I would with a "make install" (i.e. building on the host).

Is there a way to reuse the built conan packages from my .conan on the build machine for that?

Thanks for feedback.

**Comment by lasote** [comment]
Maybe the "deploy" method is interesting for you. Read more here: http://docs.conan.io/en/latest/devtools/running_packages.html?highlight=deploy#deployable-packages

The general idea is: You build your project with conan packages and then you "import" all the needed files (shared libs, exes) to a local directory, both for your app and for your deps. Then you are free to copy the libraries/executables to your system or put them on the path etc.

**Comment by memsharded** [comment]
Conan 2.0 also got the new ``deployers`` feature, for this purpose. 
Closing this ticket as solved.
