### ISSUE TITLE
Linker errors when linking against libcurl

### ISSUE THREAD

**Issue by DEGoodmanWilson** [conan-io/conan#2635]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

More pestering, my apologies 😭 

When building unit tests for `luna`, which require `libcurl/7.56.1@bincrafters/stable`, I'm getting a ton of link errors for `libcrypt`. `libcrypt` is included in the libraries being linked against (when checking `CONAN_LIBS` in `tests/CMakeLists.txt`, so I'm a little at sea. `luna` itself links just fine, FWIW.

builds gone wrong:
https://travis-ci.org/DEGoodmanWilson/luna/builds/355421382

example errors:
```
[100%] Linking CXX executable ../bin/luna_tests
/home/conan/.conan/data/libcurl/7.56.1/bincrafters/stable/package/301c93ed38bbbc10b765ae765d424d83716421ec/lib/libcurl.a(libcurl_la-md5.o): In function `Curl_md5it':
md5.c:(.text+0x1e): undefined reference to `MD5_Init'
md5.c:(.text+0x39): undefined reference to `MD5_Update'
md5.c:(.text+0x45): undefined reference to `MD5_Final'
```

Naturally, everything works just fine on my Mac (which I believe is using the system-provided `libcurl`). The problem is only on Linux.

What am I doing wrong?

**Comment by lasote** [comment]
Checking! No worries could be a badly built package or something. I'll report.

**Comment by lasote** [comment]
The issue is the library `gnutls` that is using collect libs and inside the package, there is already a `crypto.a` that is overriding the "crypto" from the `OpenSSL` package:

```
ls ~/.conan/data/gnutls/3.6.2/DEGoodmanWilson/stable/package/e3f963ca4e7731dfcd3d75355a1641c999eec62b/lib/
libaccelerated.a    libcmd-cli.a       libcmd-psk.a   libcmd-systemkey.a  libgnu.a      libgnutls_alg.a   libgnutls_extras.a  libminitasn1.a  libx86.a
libcmd-certtool.a   libcmd-danetool.a  libcmd-serv.a  ****libcrypto.a*****         libgnu_gpl.a  libgnutls_auth.a  libgnutls_x509.a    libopts.a       testpkcs11.softhsm
libcmd-cli-debug.a  libcmd-ocsp.a      libcmd-srp.a   libexamples.a       libgnutls.a   libgnutls_ext.a   libgnutlsxx.a       libunistring.a
```
Said that, I don't know if `gnutls` is ok having the `crypto` library and we have an interesting issue about name collision. Maybe you know more about the `gnutls` package.

**Comment by DEGoodmanWilson** [comment]
Wow, good find. I'd like to hear more about how you tracked this down.

Anyway, it looks like gnutls builds a bunch of intermediate libraries, and then links them altogether into a monolithic library, so that you can, if you like, link in only the bits you want or need. So—in some sense we have a clear name collision. On the other, I think we can safely limit the exports to _just_ libgnutls.a. Which is the route I will take. Thank you for tracking this down, nicely done.

**Comment by DEGoodmanWilson** [comment]
OK, this is an entirely different issue, so if you want me to open a new one I will. When I specify an exact filename to copy like this:
```
self.copy(pattern="libgnutls.a", dst="lib", src="sources", keep_path=False)
```
that file doesn't get copied when I run `conan package .`:
```
$ find . -name "libgnutls.a"
./sources/lib/.libs/libgnutls.a
```

```
$ conan package .
PROJECT: Generating the package
PROJECT: Package folder /Users/dgoodman/Documents/conan/stable/gnutls/package
PROJECT: Calling package()
PROJECT package(): Copied 793 '.h' files
PROJECT: Package 'package' created
$ ls package/lib
ls: package/lib: No such file or directory
```

but this works:
```
self.copy(pattern="*libgnutls.a", dst="lib", src="sources", keep_path=False)
```
Feels like a hack to do that though.

**Comment by lasote** [comment]
It is not a hack "*libgnutls.a" means any directory previous to a `libgnutls.a`. If you specify in 'src' the exact subfolder containing the `libgnutls.a` it will find it.
About how I tracked it down, I checked the `conanbuildinfo.cmake` file and took a look at the individual variables for the dependencies, then I saw a `crypto` in the gnutls one.

**Comment by DEGoodmanWilson** [comment]
Ah, now I understand why copy() sometimes searches subdirs, and sometimes doesn't. That behavior wasn't obvious to me. I had expected globbing to work the same way as with bash utilities like `ls`. My apologies. Looks like I've got this sorted thanks to you, so I will close the issue.

**Comment by AbhilashSunkad** [comment]
I am getting the same above error. I am building libcurl for android. I have linked the crypto,openssl and curl library. Below are the libraries linking.
libssl.a libcrypto.a libcurl.a
I am compiling on Mac OS.
Not getting what to do next.

**Comment by uilianries** [comment]
@AbhilashSunkad please, open an issue to https://github.com/conan-io/conan-center-index/issues if you are using libcurl from Conan Center Index.
