### ISSUE TITLE
Generated conanfile.py should comply with PEP8 and be friendly to static code analyzers

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#2636]
As of 1.1.1, `conanfile.py` for the main and test packages automatically generated through `conan new -t foo/0.1@username/testing` don't comply with PEP8. This is a bit annoying if you care about style to have to fix the same errors again, or avoid code generation features.

Here's the current state:
```
$ pip install --user pycodestyle
$ pycodestyle conanfile.py test_package/conanfile.py 
conanfile.py:18:80: E501 line too long (85 > 79 characters)
conanfile.py:30:80: E501 line too long (82 > 79 characters)
test_package/conanfile.py:4:1: E302 expected 2 blank lines, found 1
test_package/conanfile.py:10:80: E501 line too long (96 > 79 characters)
```

3 out of 4 warnings are about [maximum line length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length). The 4th is a missing blank line.

Another one that is not mentionned by the `pycodestyle` tool but is good practice is about the [imports](https://www.python.org/dev/peps/pep-0008/#imports). The order is wrong, and import groups should be separated by a newline:

**bad**
```
from conans import ConanFile, CMake, tools
import os
```

**good**
```
import os

from conans import ConanFile, CMake, tools
```

As an additional style remark (unrelated to PEP8), I find this code in the test_package to have poor readability:
```
self.run(".%sexample" % os.sep)
```

```
import os.path
...
self.run(os.path.join('.', 'example'))
```
A `git grep -w example` will fail on the first version, as the formatting is mixed with the content.

Seen on Conan 1.1.1 on Ubuntu 14.04

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Agree.

But we are supposed to be using 100 chars all along conan codebase (sure it is infringed in many places).
The pep8 is not very strict about this and allows relaxing it.

Also, it is not ``conan create`` but ``conan new``.

This should be easy to change, I suggest:
- Import order,
- lines limit to 100 chars
- blank line

**Comment by liberforce** [comment]
Thanks for your answer. You're right for `conan new`, I fixed it in the initial message.

As for relaxing the maximum line length, PEP8 says:

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters), provided that comments and docstrings are still wrapped at 72 characters.

The generated files are not maitained primarily by one team, it's quite the opposite, as you encourage people to package their app using conan. Another thing is that the infringing lines are comments and according to the guidelines, they should still be wrapped at 72 characters.

Now that we have seen `pycodestyle`, let's take a look at `pylint` checks:

```
$ pylint conanfile.py test_package/conanfile.py 
No config file found, using default configuration
************* Module conanfile
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Missing class docstring (missing-docstring)
E: 34, 8: self.copy is not callable (not-callable)
E: 35, 8: self.copy is not callable (not-callable)
E: 36, 8: self.copy is not callable (not-callable)
E: 37, 8: self.copy is not callable (not-callable)
E: 38, 8: self.copy is not callable (not-callable)
E: 39, 8: self.copy is not callable (not-callable)
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Missing class docstring (missing-docstring)
C: 14, 4: Missing method docstring (missing-docstring)
E: 15, 8: self.copy is not callable (not-callable)
E: 16, 8: self.copy is not callable (not-callable)
E: 17, 8: self.copy is not callable (not-callable)
C:  2, 0: standard import "import os" should be placed before "from conans import ConanFile, CMake, tools" (wrong-import-order)

--------------------------------------------------------------------
Your code has been rated at -1.33/10 (previous run: -1.33/10, +0.00)
```
Not sure about what the self.copy error is, but I think you see the point. Generated code should not trigger warnings or errors by usual static analyzers, because that puts the burden of the work on the shoulders of **each** package maintainer that cares about those metrics and use those tools.

To make it short: if the template is broken, fix the template.
