### ISSUE TITLE
Visual Studio generator dll paths

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#264]
It seems that the path to dll, even if "imported" in visual studio, is not defined by the generator, so running from MSVC fails when shared libraries. Don't know if possible, but if possible, it would be nice that the generator handles this.

**Comment by Xaltotun** [comment]
There are two ways that this can be implemented.
First, we can copy the files to the output build directory using the msbuild copy task, or they can be added to the ExecutablePath property.
