### ISSUE TITLE
Making sure that recipes don't download any files without checksum verification

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#2648]
Downloading files from net introduces potential risk, because files might be tampered, and conan recipe will happily build package from tampered sources. There should be a way to make sure that all downloaded files are checked, e.g. by aborting build in case when unchecked file is used

**Comment by danimtb** [comment]
HI @annulen!

Have you checked the provided tools to check the hash of a file?
https://docs.conan.io/en/latest/reference/tools.html#tools-check-with-algorithm-sum

You can use those tools like this:

```
def source(self):
    tools.download("https://url/file.zip")
    tools.check_md5("file.zip", "d2da0cd0756cd9da6560b9a56016a0cb")
    # or just do: tools.get("https://url/file.zip", md5="d2da0cd0756cd9da6560b9a56016a0cb")

Is this what you are looking for?

**Comment by annulen** [comment]
I know about this stuff, but when dealing with recipes not written by me I need to ensure that there are no unchecked downloads anywhere

**Comment by danimtb** [comment]
This is something that has to be done by the package creator and we cannot force them to do it. Normally OSS libraries have documented links to download sources withou the need of double checking and as you know it is OSS so there is always a risk of downloading wrong sources.

If you want to use a 3rd party library in a "controlled" environment, some users are subclassing the `ConanFile` of the opensource recipe and implementing its own` source()` method to retrieve sources from an internal repo or trusted server, making the hash checks indicated above.

**Comment by annulen** [comment]
I was thinking about something like monkey patching methods like `tools.download` and `tools.get` to bail out if hash sum is missing. Are there any other methods which could be used in recipe to download files?

**Comment by annulen** [comment]
Other way could be marking all downloaded files as "tainted" and bail out on any other operation with them until checksum is verified, but I don't know if it's feasible to implement without much work

**Comment by annulen** [comment]
>Normally OSS libraries have documented links to download sources withou the need of double checking

Checking files downloaded from Internet is just a basic safety measure. Files on remote site may be replaced by malicious person, or they can be just corrupted in transmission process. Most of packaging systems e.g. as found in Linux distros require checksums as mandatory package metadata, or generate them automatically when package is created (like in Gentoo `ebuild digest`)

**Comment by annulen** [comment]
>If you want to use a 3rd party library in a "controlled" environment, some users are subclassing the ConanFile of the opensource recipe and implementing its ownsource() method to retrieve sources from an internal repo or trusted server, making the hash checks indicated above.

It seems like many packages found in conan-center or bincrafters repos do unrelated things in `source`, like changing file permissions or renaming files, so this approach doesn't scale

**Comment by danimtb** [comment]
not unlrelated things in my opinion. source() method is not only for downloading sources, its purpose is also to prepare the source code with the needed patches or configurations needed to make a build for for different settings/options.

Your suggestion of marking files as "tainted" could be feasible but hard to implement from our side as we would have to force users to use our checksum verification tools to mark sources as "trusted"/"verified"... Even with that check people could download whatever there and as I said it is a risk, that's why most people using conan at companies copy the OSS recipes and override the `source()` method to use their own server for downloads.

I dont see a good solution to this ATM and there is no big concern  from the OSS community neither...

**Comment by annulen** [comment]
>Your suggestion of marking files as "tainted" could be feasible but hard to implement from our side as we would have to force users to use our checksum verification tools to mark sources as "trusted"/"verified"... 

If it was an option you wouldn't

>there is no big concern from the OSS community neither

Because many people from OSS community see Conan as (anonymous quote) "walking security hole" :)

**Comment by uilianries** [comment]
Hi @annulen !

You could try [hooks](https://docs.conan.io/en/latest/extending/hooks.html) to inject any extra steps if you are not confident with third-party recipes.

**Comment by annulen** [comment]
Thanks for heads up!

**Comment by annulen** [comment]
@uilianries Is it possible to make a hook which would prevent overwriting of files on bintray on upload?

**Comment by danimtb** [comment]
@annulen you can do pretty much anything inside a hook. I have seen some people instantiating a Conan API (not stable and undocumented though) to perform other Conan calls before commands. SO I ges this is a path you could take

**Comment by danimtb** [comment]
We are now following this approach for conan-center-index so that would be the best trade-off and a general practice when packaging 3rd party libraries
