### ISSUE TITLE
[question] binary tool settings

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2661]
I am trying to compile and package a binary tool (jwasm assembler) The recipe is roughly the following:
```python
class JWasmConan(ConanFile):
    name = "jwasm"
    version = "2.12"
    settings = "os_build", "arch_build"
    exports_sources = "CMakeLists.txt"
    generators = "cmake"

    def source(self):
        tools.get("https://sourceforge.net/projects/jwasm/files/JWasm%20Source%20Code/JWasm212s_140105.zip")

    def build(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_BUILD_TYPE"] = "Release"
        cmake.configure()
        cmake.build(args=["--config", "Release"])

    # ...
```
This does not work:
```
ERROR: jwasm/2.12@dbely/testing: Error in build() method, line 18
        cmake = CMake(self)
        ConanException: You must specify compiler, compiler.version and arch in your settings to use a CMake generator
```
But I would not like to export `compiler` and `arch` settings - the package contains only an executable that should be selected depending on `os_build`, `arch_build` and can produce objective files for any host platform. How to build it using current `os`, `compiler` and `arch` and export only `os_build` and `arch_build`?

**Comment by lasote** [comment]
You can specify the settings and later remove the not needed in the package_id() method so they won't be used to generate different binary packages. e.j:

```
def package_id(self):
        del self.info.settings.compiler
```

**Comment by db4** [comment]
Thanks, but after
```
class JWasmConan(ConanFile):
    # ...
    settings = "compiler", "arch", "os_build", "arch_build"

    def build(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_BUILD_TYPE"] = "Release"
        cmake.configure()
        cmake.build(args=["--config", "Release"])

    def package_id(self):
        del self.info.settings.compiler
        del self.info.settings.arch
```
I see no `arch_build` in the exported settings:
```
conan search jwasm/2.12@dbely/testing
Existing packages for recipe jwasm/2.12@dbely/testing:

    Package_ID: 60b04a80ac4dd5c23f1acffacc679e9902e636e5
        [settings]
            os_build: Windows
        Outdated from recipe: False
```
Is it normal?

**Comment by memsharded** [comment]
This is part of the default logic of the ``package_id()`` method. 

The default behavior right now is ``discard_build_settings()`` which have the current implementation:

```python
def discard_build_settings(self):
        # When os is defined, os_build is irrelevant for the consumer.
        # only when os_build is alone (installers, etc) it has to be present in the package_id
        if self.full_settings.os and self.full_settings.os_build:
            del self.settings.os_build
        if self.full_settings.arch and self.full_settings.arch_build:
            del self.settings.arch_build
```
It tries to model the fact that normal libraries, when cross-built do not matter which "build" machine they were built in, it is only important the final machine when they will run  (host).

For tools, the behavior might be the opposite, so if you want to keep ``os_build`` and ``arch_build``, but need to define the current ``arch`` or ``os`` too, you want to explicitly tell to keep them:

```python
def package_id(self):
        self.info.include_build_settings()
        #Then maybe remove the "host" setting, no longer necessary
        del self.info.settings.arch
```

We are aware that the definition for tools is not as intuitive as it should be, and there are improvements for it in the long term roadmap.

**Comment by danimtb** [comment]
Reference here: http://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info-discard-build-settings-self-info-include-build-settings

Maybe we should explain it here and link the reference:  http://docs.conan.io/en/latest/devtools/create_installer_packages.html

**Comment by memsharded** [comment]
Yes, please @danimtb open a subsection in that docs page that explain a bit about the ``package_id()`` for tools, and those helpers. Thanks!

**Comment by db4** [comment]
@memsharded Thank you for clarifying this. But
```python
    settings = "os", "compiler", "arch"
    
    # ...

    def package_id(self):
        self.info.include_build_settings()
        #Then maybe remove the "host" setting, no longer necessary
        del self.info.settings.arch
```
is not enough, after that `arch_build` and `os_build` get `None` value. I have to use
```python
    def package_id(self):
        self.info.include_build_settings()
        self.info.settings.arch_build = self.info.settings.arch
        self.info.settings.os_build = self.info.settings.os
        del self.info.settings.os
        del self.info.settings.compiler
        del self.info.settings.arch
```
Is it the right way to do the job?

**Comment by db4** [comment]
If I do I get red warning
```
pccts/1.33MR33@dbely/testing: ************************************************************
pccts/1.33MR33@dbely/testing:   This package defines both 'os' and 'os_build'
pccts/1.33MR33@dbely/testing:   Please use 'os' for libraries and 'os_build'
pccts/1.33MR33@dbely/testing:   only for build-requires used for cross-building
pccts/1.33MR33@dbely/testing: ************************************************************
```
not only when building but also when using a package. That's what I would like to avoid.

**Comment by memsharded** [comment]
Closing this ticket as outdated, the new cross-build model with build/host contexts no longer has ``arch_build`` or ``os_build``
