### ISSUE TITLE
Conan failing to unpackage tgz on windows vm

### ISSUE THREAD

**Issue by jin1020** [conan-io/conan#2664]
When running conan install ... on a windows vm, conan fails with the following:
Calling build()
fetching ....
downloads....
build failed...
tools.get(url) -> IOError: [Errno 2] No such file or directory '.\\protobuf\\....\\include\\google\\protobuf\\stubs\\atomicops_internals_generic_c11_atomic.h'

I set short_paths = True thinking it might be a path issue but nothing I try seems to work.  It works fine on my local box.

Any advice would be greatly appreciated :)

**Comment by memsharded** [comment]
Your local box is also Windows? Same version?

Without the recipe or something to reproduce is quite difficult to know. Also I guess that you are running the same versions of conan, etc in the VM than in the local box? Thanks!

**Comment by jin1020** [comment]
Hi memsharded!

Yes, versions are all the same.  What I am seeing is that the tgz has all the files in it but when it tries to unpack it, it fails to unpack all the files on the vms.  From the look of things, it isn't unzipping the files properly.

**Comment by jin1020** [comment]
Hi memsharded,

So I think I figured it out.  It was calling another package within which need short_paths = True.  That fixed the issue.  They are internal packages.  Thanks for the responses!

**Comment by memsharded** [comment]
No problem, glad you solved the issue! :)
