### ISSUE TITLE
conan install with options

### ISSUE THREAD

**Issue by urykhy** [conan-io/conan#2666]
Conan version 1.1.0
CentOS Linux release 7.2.1511

i'm playing with conan and it works well, except i have a problem with profiles:

1. create script to build package with fpic option:
```
    options = {"shared": [False], "fpic": [False, True]}
    default_options = "shared=False", "fpic=False"
```

2. create custom profile (file named c++11) with option:
```
[options]
fpic=True
```

3. build package with profile
```
conan create ../src/lz4.py lz4/r131@user/stable -pr=c++11
....
Package 'a6fc0cf7372fd9d5e9f826e6a6155c5cac7637e6' created
```

4. create conanfile.txt to install it
```
[requires]
lz4/r131@user/stable
[generators]
cmake
```

5. install with profile
```
conan install ../conanfile-fpic.txt -pr=c++11
ERROR: 'options.fpic' doesn't exist
Possible options are []
```

6. i found work around:
* comment out **fpic** option in profile
* add ```[options]\nlz4:fpic=True``` to conanfile.txt

but this is not really nice, i have to use 2 profiles (with option and without) + i need to specify options for every package i depend.

have i miss a proper way to use options ?

**Comment by danimtb** [comment]
Hi @urykhy!

Options are very particular to each recipe and can't always be generalized. However, fpic and share are quite common options for recipes. You can apply a value in your profile affecting all packages this way:

*profile_c++11*
```
[options]
*:fpic=True
```

This would work only if pacakges have **fpic** option written with the same case. Please give it a try and let me know if that is what you are looking for. Thanks! 😄

**Comment by urykhy** [comment]
It's works like a charm, Thanx!
