### ISSUE TITLE
[question] package_id miss some changes in requires field when override

### ISSUE THREAD

**Issue by lounagen** [conan-io/conan#2670]
Hi,

Context
--
Conan version 1.1.1
OS: linux debian 9
Installation mode: pip in a dedicated python3 virtualenv
Note: This question could be linked to #2628 and #2140 for the global context, but i didn't find in them the particular point of my current question.

My current company is still investigating possibilities provided by conan to be able to switch on it fully on a short/middle term.

I currently test the possibility to align the transitive dependencies' versions to a known one (does this feature even make sense or is there some safeguards when 2 dependencies rely on the same subdependency with incompatible major versions?), as mentioned in [conan doc about requires](http://docs.conan.io/en/latest/reference/conanfile/attributes.html#requires),
 with the `override` param of the `requires` field in a `conanfile.py`.

According to the [conanfile.py doc about package_id](http://docs.conan.io/en/latest/reference/conanfile/methods.html?highlight=Package_ID#package-id), i expect the package id to take into account `settings`, `options` and `requires`.

Expectation
--
When i override a dependency, as mentioned above, i expect the package id of my package to be different than if i didn't override it, as the `requires` field is modified (at least in the visual output of `conan search`, it is modified)

What's really happened
--
* *Step 1 vs 2 of the reproduction below:* When i override a transitive dependency version (vs declaring it as a first level dependency), the output of the search command show the settings/options/requires remains the same (that(s what i expect), but the package_id of my package is modified (and i expected it would have remained the same, as settings/options/requires are the same)
* *Step 1 vs 3 of the reproduction below:* When i override a transitive dependency version (vs do not declare it at all and only rely on the transitive dependency), the output of the search command show the override was taken into account (zlib 1.2.8 to 1.2.11), but the package_id of my package remains the same in both cases (and i expected it to be modified)

Questions
--
* Is this behaviour normal (a.k.a. a feature and not a potential bug or missing evolution)?
* Does the package_id computing default algorithm ignore the overriden 'non first level' requires by wanted design or is there a bit of magic somewhere to be known?
* In part of the conan global workflow, do you advice not to override transitive dependencies version and usually rely on the default behaviour and 'guess/chack' all work fine in CI (like we would do somehow in a maven environment regarding the versioning)?

Reproduction
--
*I used OpenSSL 1.0.2n recipe for these samples, which rely on zlib 1.2.11 in its own `requires`, and i try to override zlib version down to 1.2.8.*

**Step 1: Override requires in conanfile.py class**
```bash
mkdir -p class_requires_override
cd class_requires_override/
conan new dummy/1.0@me/test1 -t

cat << EOF >> conanfile.py

    requires = (
        ('zlib/[<1.2.11]@conan/stable', 'override'),
        ('OpenSSL/1.0.2n@conan/stable'),
    )
EOF

conan create . dummy/1.0@me/test1
conan search dummy/1.0@me/test1
```
outputs (non-outdated entry shows: Package_ID: 80bb... , zlib 1.2.**8**):
```
Existing packages for recipe dummy/1.0@me/test1:

    Package_ID: 80bb36058f313a444206a796577e48e51d8e9748
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++
            compiler.version: 7
            os: Linux
        [requires]
            OpenSSL/1.0.2n@conan/stable:75b541b6f810787a4fcee8cec9cfdbf95959366f
            zlib/1.2.8@conan/stable:6ae331b72e7e265ca2a3d1d8246faf73aa030238
        Outdated from recipe: False
```
```bash
cd ..
```

**Step 2: Do NOT override requires in conanfile.py class, but declare zlib as a first level dependency**
```bash
mkdir -p class_requires_basic
cd class_requires_basic
conan new dummy/1.0@me/test1 -t

cat << EOF >> conanfile.py

    requires = (
        ('zlib/[<1.2.11]@conan/stable'),
        ('OpenSSL/1.0.2n@conan/stable'),
    )
EOF

conan create . dummy/1.0@me/test1
conan search dummy/1.0@me/test1
```
outputs (non-outdated entry shows: Package_ID: f3885... , zlib 1.2.**8**):
**Note that's a different new package_id, whereas zlib version in output's `requires` section remains the same, so as all the other settings and options values**
```
Existing packages for recipe dummy/1.0@me/test1:

    Package_ID: 80bb36058f313a444206a796577e48e51d8e9748
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++
            compiler.version: 7
            os: Linux
        [requires]
            OpenSSL/1.0.2n@conan/stable:75b541b6f810787a4fcee8cec9cfdbf95959366f
            zlib/1.2.8@conan/stable:6ae331b72e7e265ca2a3d1d8246faf73aa030238
        Outdated from recipe: True

    Package_ID: f388507aa84012eb11cfdfaa53c106e364e77e30
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++
            compiler.version: 7
            os: Linux
        [requires]
            OpenSSL/1.0.2n@conan/stable:75b541b6f810787a4fcee8cec9cfdbf95959366f
            zlib/1.2.8@conan/stable:6ae331b72e7e265ca2a3d1d8246faf73aa030238
        Outdated from recipe: False
```
```bash
cd ..
```

**Step 3: Do NOT mention non-first level transitive dependencies in conanfile.py class (comment zlib ine)**
```bash
mkdir -p class_requires_transitive_dep
cd class_requires_transitive_dep
conan new dummy/1.0@me/test1 -t

cat << EOF >> conanfile.py

    requires = (
        # ('zlib/[<1.2.11]@conan/stable'),
        ('OpenSSL/1.0.2n@conan/stable'),
    )
EOF

conan create . dummy/1.0@me/test1
conan search dummy/1.0@me/test1


```
outputs (non-outdated entry shows: Package_ID: 80bb... , zlib 1.2.**11**):
**Note that's the package_id take the same value than when i override zlib to 1.2.8, whereas zlib version in output's `requires` section is (logically) the 1.2.**11** one**
```
Existing packages for recipe dummy/1.0@me/test1:

    Package_ID: 80bb36058f313a444206a796577e48e51d8e9748
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++
            compiler.version: 7
            os: Linux
        [requires]
            OpenSSL/1.0.2n@conan/stable:75b541b6f810787a4fcee8cec9cfdbf95959366f
            zlib/1.2.11@conan/stable:6ae331b72e7e265ca2a3d1d8246faf73aa030238
        Outdated from recipe: False

    Package_ID: f388507aa84012eb11cfdfaa53c106e364e77e30
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++
            compiler.version: 7
            os: Linux
        [requires]
            OpenSSL/1.0.2n@conan/stable:75b541b6f810787a4fcee8cec9cfdbf95959366f
            zlib/1.2.8@conan/stable:6ae331b72e7e265ca2a3d1d8246faf73aa030238
        Outdated from recipe: True
```
```bash
cd ..
```

**Comment by memsharded** [comment]
Hi @lounagen 

sorry for the delay in answering, we are about to release 1.2.

Regarding your questions:

> I currently test the possibility to align the transitive dependencies' versions to a known one (does this feature even make sense or is there some safeguards when 2 dependencies rely on the same subdependency with incompatible major versions?)

Yes, you cannot depend on the same dependency graph on two different version of the same library. There is an exception, declaring dependencies ``private`` then you should be able to do it. Note however than private dependencies have other disadvantages, like you are not able to override them from downstream.

I think most of your described behavior comes from the default versioning used for computing the ``package_id()``:

- For every direct dependency the "semver" version, excluding user and channel will be used. So ``zlib/1.2.11@user/testing`` and ``zlib/1.2.8@otheruser/stable`` will both map to ``zlib/1.Y``, and thus produce the same package ID
- The rationale behind this decission was to use "semver", so minor dependencies will be compatible. 
- This might not be the case for some C and C++ libraries, so that is fully customizable. You can set policies like ``self.info.requires.full_package_mode()``, in your ``package_id()`` method.

There is more information in: http://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#using-package-id-for-package-dependencies that might be useful.

Binary compatibility is challenging, and almost impossible to define an automated policy, probably conan "semver" approach is not perfectly suited for C++ libraries, but ``package_id()`` should allow to define the binary compatibility at any level.

Please have a look and tell me if this helps. Many thanks!

**Comment by lounagen** [comment]
Hi @memsharded 
Thanks for your clear explanation, yes it helps to explain the current behavior!

I understand the default semver way to compute the package_id.
The current package_id takes care of compatibility/ABI.

II i understood well, between 2 project builds, one now and another 10 days ago, i can't know which exact sub(-sub-...)-dependencies versions were used (it could impact my own binary in particular when some of them are static), and if i want such a traceability for now, i can/must rebuild all from source (with --build) and store the logs. I only speak about traceability (for a debugging investigation matter, security/signature of this traceability would be another whole subject).
May be it could be useful to have another hash-based id to take care of traceability, to provide a snapshot/manifest-like file describing the exact way a package was built, and so on for all its recursive dependencies?

Regarding the main point, thanks for your comment, it answered my question

**Comment by memsharded** [comment]
> II i understood well, between 2 project builds, one now and another 10 days ago, i can't know which exact sub(-sub-...)-dependencies versions were used (it could impact my own binary in particular when some of them are static), and if i want such a traceability for now

It is not something that can be used to feed and re-build automatically, but you have the full dependencies, exact ones with package-IDs too, in the ``conaninfo.txt`` file. Another form of traceability, in this case for security purposes would be the manifests capture and verification features.

Just for your info, one of the things that we are studying now is how to capture the full state in ``conaninfo.txt`` (or something equivalent), that can indeed be used to fire a re-build of the project and also the intermediate dependencies, with reproducibility.

Thanks for your feedback!

**Comment by memsharded** [comment]
Closing as inactive
