### ISSUE TITLE
[bug] conan not setting cmake related variables

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#2671]
```
conan --version
Conan version 1.1.1
```

Some of variables mentioned [here](http://docs.conan.io/en/latest/reference/env_vars.html#cmake-related-variables) does not get passed to CMake correctly.

I've prepared example that reproduces it on [github](https://github.com/omicronns/conan-test).

To reproduce:
```
git clone https://github.com/omicronns/conan-test.git && cd conan-test
export CONAN_USER_HOME=$(pwd)
```

# Variables passing cases:

## CONAN_CMAKE_TOOLCHAIN_FILE only:
```
rm -rf build .conan && conan install . -if build -e CONAN_CMAKE_TOOLCHAIN_FILE=toolchain.cmake && conan build . -bf build
```
CONAN_CMAKE_TOOLCHAIN_FILE gets passed correctly.

## CONAN_CMAKE_SYSTEM_NAME only:
```
rm -rf build .conan && conan install . -if build -e CONAN_CMAKE_SYSTEM_NAME=Generic && conan build . -bf build
```
CONAN_CMAKE_SYSTEM_NAME gets passed correctly.

## CONAN_CMAKE_SYSTEM_NAME and CONAN_CMAKE_SYSTEM_PROCESSOR:
```
rm -rf build .conan && conan install . -if build -e CONAN_CMAKE_SYSTEM_NAME=Generic -e CONAN_CMAKE_SYSTEM_PROCESSOR=cortex-m0 && conan build . -bf build
```
CONAN_CMAKE_SYSTEM_NAME gets passed correctly.
CONAN_CMAKE_SYSTEM_PROCESSOR is passed incorrectly, it appears on cmake command line as -DCONAN_CMAKE_SYSTEM_PROCESSOR="cortex-m0" instead of -DCMAKE_SYSTEM_PROCESSOR="cortex-m0"

## CONAN_CMAKE_TOOLCHAIN_FILE and CONAN_CMAKE_SYSTEM_NAME and CONAN_CMAKE_SYSTEM_PROCESSOR:
```
rm -rf build .conan && conan install . -if build -e CONAN_CMAKE_TOOLCHAIN_FILE=toolchain.cmake -e CONAN_CMAKE_SYSTEM_NAME=Generic -e CONAN_CMAKE_SYSTEM_PROCESSOR=cortex-m0 && conan build . -bf build
```
CONAN_CMAKE_TOOLCHAIN_FILE gets passed correctly.
CONAN_CMAKE_SYSTEM_NAME and CONAN_CMAKE_SYSTEM_PROCESSOR is not passed at all now.

**Comment by memsharded** [comment]
Thanks very much for your detailed report.
It seems it could be a bug, will try to check as soon as possible.

**Comment by lasote** [comment]
I think there is a bug with `CONAN_CMAKE_SYSTEM_PROCESSOR` only, that should be adjusted in the previous `if cross_building(self._conanfile.settings):` block.
About all these variables, not being set when `CMAKE_TOOLCHAIN_FILE` it was an intended behavior, because typically these variables will be declared in the TOOLCHAIN_FILE. We can discuss if this is correct or not, but currently, for 1.2 I would like to fix only the `CONAN_CMAKE_SYSTEM_PROCESSOR`

**Comment by omicronns** [comment]
@lasote inside `if cross_building(self._conanfile.settings):` block there is no `CONAN_CMAKE_SYSTEM_PROCESSOR` variable reference. You mean `if ret: # If enabled cross compile` block?

I think if some `CONAN_CMAKE(...)` variable is set, it should be passed through to CMake. If someone does not want these variables to be passed to CMake, then one should not set it. Maybe these variables indeed should not be defaulted if not set, but not passing those when someone is providing them is strongly confusing.

**Comment by omicronns** [comment]
Thanks!

**Comment by lasote** [comment]
I'm opening a new issue to take a decision about applying all the variables together with the toolchain. This one will be closed with https://github.com/conan-io/conan/pull/2682
