### ISSUE TITLE
OpenSSL will not build.

### ISSUE THREAD

**Issue by jasonwray** [conan-io/conan#2681]
Conan version 1.1.1

```
ERROR: OpenSSL/1.0.2l@conan/stable: Error in build() method, line 101
	self.unix_build(config_options_string)
while calling 'unix_build', line 169
	config_line = "./Configure %s -fPIC %s %s" % (config_options_string, target, extra_flags)
	UnboundLocalError: local variable 'target' referenced before assignment
```

**Comment by jasonwray** [comment]
Found the issue here, I didn't want to spend all night debugging it, so I just added "target = "%slinux-armv4" % target_prefix" to line 188: https://github.com/conan-community/conan-openssl/blob/ba9c875676d81320c2fcd8bf84d52f1e602cc260/conanfile.py#L188

**Comment by danimtb** [comment]
It seems `target` was not set before configure. The target setup you are looking for is done in this line: https://github.com/conan-community/conan-openssl/blob/ba9c875676d81320c2fcd8bf84d52f1e602cc260/conanfile.py#L150

Could you please check your profile to make sure you are using the correct arch (`armv7`)?

**Comment by jasonwray** [comment]
uname reports armv6l, so it looks like a gap in the logic.

**Comment by danimtb** [comment]
What is the profile you are using to compile OpenSSL?
What platform are you compiling for?
Thanks

**Comment by jasonwray** [comment]
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=armv6
arch_build=armv6
compiler=gcc
compiler.version=4.8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

It's on a Raspberry Pi B1+

**Comment by memsharded** [comment]
Ok, that is right, I think this is an issue in the OpenSSL recipe itself, not in conan, so I am going to open the issue there. Thanks very much for reporting.

**Comment by memsharded** [comment]
Follow in https://github.com/conan-community/community/issues/10
