### ISSUE TITLE
Automatic treatment for fPIC option

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#2684]
Hi!

When using cmake generator, we have an automatic treatment for `shared` option, where `BUILD_SHARED_LIBS` is filled with such value.

The same case could be applied for `fPIC` option. We have a recipe template [here](https://github.com/bincrafters/conan-templates/blob/master/conanfile.py) where fPIC is manipulated by os.

My idea is handle `fPIC` as we did in our template, but maybe using `config_options` instead of `configure`.

So, when the recipe contains the option `fPIC`, it should be removed when running over Windows and the definition `CMAKE_POSITION_INDEPENDENT_CODE` should be filled when not running over Windows.

Regards.

Conan version: 1.1.1
Operation System: Any

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Duplicated #2464  and related to #2476?

**Comment by uilianries** [comment]
yes, it's duplicated. Thanks!
