### ISSUE TITLE
specifiying dependances in a new package 

### ISSUE THREAD

**Issue by sancelot** [conan-io/conan#2689]
Hi,
I want ot create a package that depends on a particular version of qt

How can I specify it inside the package ?

Are there any predefined packages (like qt5 ) I can use ?
Regards,
S.Ancelot

**Comment by memsharded** [comment]
Hi @sancelot 

Sure, when you are creating packages you can add the requirements of that package:

```python
class MyPkg(ConanFile):
    ...
    requires = "OtherPkg/1.2@user/channel", "AnotherPkg/3.4.2@otheruser/stable"
```

For existing packages for OSS, you want to check this repos:
Reference one (on going work, this is a reviewed repo):
- conan-center: https://bintray.com/conan/conan-center
Community repos (non curated):
- bincrafters : https://bintray.com/bincrafters/public-conan
- conan-community : https://bintray.com/conan-community/conan


Check more about them here: http://docs.conan.io/en/latest/uploading_packages/remotes.html

**Comment by sancelot** [comment]
Thanks
