### ISSUE TITLE
Non interactive mode also prevents prompt from `conan user`

### ISSUE THREAD

**Issue by lewie-donckers** [conan-io/conan#2693]
The new non interactive mode also prevents the prompt from `conan user <name> -p`. This is not what is specified in the documentation. (And also not what was originally implemented.)

I hope the prompt can be re-enabled for this particular case. If not, the documentation should be changed.

Oh, and a purely cosmetic remark: the non interactive error only appears after the prompt has been displayed.

Using Conan 1.2 on Windows 7.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Could you point where is wrong the docs? I can't find it.

**Comment by lewie-donckers** [comment]
At http://docs.conan.io/en/latest/reference/env_vars.html#conan-non-interactive it says: 

> Invocations of conan user are not affected.

That's not true.

**Comment by lasote** [comment]
Docs fixed. Many thanks.

**Comment by memsharded** [comment]
I think you could also try (non-windows):
```bash
$ CONAN_NON_INTERACTIVE=0  conan user -p
```
As the env-var has precedence over the conan.conf, you would keep the non-interactive for the rest of operations.

Lets have a look to the prompt issue, and check if it has an easy fix.

**Comment by memsharded** [comment]
The prompt issue has been fixed in #2708 and will be released in 1.3
