### ISSUE TITLE
Issues with the JSON created by conan create

### ISSUE THREAD

**Issue by ovidiub13** [conan-io/conan#2695]
Conan version: 1.2.0

Command: `conan create --json ./foo.json . myteam/unstable`

The generated JSON does not separate the dependency packages of the built project, from the built package. This makes it difficult to parse.

**Comment by lasote** [comment]
Maybe separate them will make more complex other workflows where it doesn't matter which is the package being created. Would be valid for you add a new field in the "recipe" doc to indicate that it is the package being created?

**Comment by ovidiub13** [comment]
IMO the `dependency: true/false` would be better. Can this be added to all the packages?

**Comment by lasote** [comment]
> Can this be added to all the packages?

You mean all the "recipe"s documents? or the "packages" documents? I don't see the point to add it to the packages.

I still don't know how hard will it be, we have to analyze it. Maybe it is not trivial at all but will try.

**Comment by ovidiub13** [comment]
I mean: In a generated JSON, to add teh `dependency: true/false` to all `recipe` objects, not just to the `recipe` of the package being created.
