### ISSUE TITLE
compiler_args generator produced incorrect setting

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#2698]
I'm using `compiler_args` generator in one of my projects and suddenly found this at the end of `conanbuildinfo.args`:

```
-D_GLIBCXX_USE_CXX11_ABI=1 - s t d = c + + 1 z
```

This only occured after updating to 1.2 and setting `cppstd`. Some kind of UTF-16 mismatch?

**Comment by memsharded** [comment]
Actually this seems a bug, not a mistmatch. Could you please help us reproducing it? Which is the ``package_info()`` method that is defining the ``std=c++1z``?  Thanks!

**Comment by Lyberta** [comment]
I'm baffled as I use `cppstd=17` and none of my packages require GNU extensions.

**Comment by memsharded** [comment]
Confirmed as a bug. Submitted fix (without tests yet). Will consider including it in a minor if such minor release is done. Thanks!

**Comment by lasote** [comment]
Released in 1.2.1.
