### ISSUE TITLE
Option to select build_type when using cmake_multi

### ISSUE THREAD

**Issue by madpipeline** [conan-io/conan#2710]
Conan: 1.1.1

Scenario:
```
cd <path_to_build_dir>
conan install <path_to_sources> --profile Windows-Release --build missing --generator cmake_multi
conan install <path_to_sources> --profile Windows-Debug --build missing --generator cmake_multi

conan build <path_to_sources>
```

The `build()` function in `conanfile.py`:
```
        cmake = CMake(self)
        cmake.configure( \
            source_dir = self.source_folder,\
            build_dir  = self.build_folder)
        cmake.build()
        cmake.install()
```

With Visual Studio, the default `build_type` is set to `Debug`. We need a way to give conan a config that can be passed to CMake, so that when running `conan build` it builds for `Release` instead.

**Comment by lasote** [comment]
Probably if you run the Release install in the second place it will take the Release. I'm not saying this is ideal, but I don't know what could we do, the multi generator is a little special.

**Comment by ovidiub13** [comment]
That actually woks. It's a good workaround, for now. Thank you.

**Comment by memsharded** [comment]
``cmake_multi`` has been replaced by ``CMakeToolchain``, closing this
