### ISSUE TITLE
Downloading package from local server fails if package contains file with .tar.gz extension

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#2711]
Conan version 1.2.0.
## Setup
I'm trying to package pandas and install on different machine, using conan_server serving packages from local conan cache, i.e. I have `disk_storage_path: ~/.conan/data`.

(I tried this setup to quickly deploy my locally built packages).

## Issue
After downloading many files one by one I get this error:
```
Downloading pandas/tests/io/parser/data/tar_csv.tar.gz
pandas/0.22.0@iuutim/test: ERROR: Exception while getting package: 93ac830d788caa12e69db24f8f4c7491df4377e7
pandas/0.22.0@iuutim/test: ERROR: Exception: <class 'conans.errors.ConanConnectionError'> Download failed, check server, possibly try again
('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',)). [Remote: dev]
pandas/0.22.0@iuutim/test: WARN: Trying to remove package folder: /mnt/ext4/iuutim/.conan/data/pandas/0.22.0/iuutim/test/package/93ac830d788caa12e69db24f8f4c7491df4377e7
ERROR: Download failed, check server, possibly try again
('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',)). [Remote: dev]
```

It seems that file is not really gzipped:
```sh
# file ~/.conan/data/pandas/0.22.0/iuutim/test/package/93ac830d788caa12e69db24f8f4c7491df4377e7/pandas/tests/io/parser/data/tar_csv.tar.gz
/home/default/.conan/data/pandas/0.22.0/iuutim/test/package/93ac830d788caa12e69db24f8f4c7491df4377e7/pandas/tests/io/parser/data/tar_csv.tar.gz: POSIX tar archive (GNU)
tar tf /home/default/.conan/data/pandas/0.22.0/iuutim/test/package/93ac830d788caa12e69db24f8f4c7491df4377e7/pandas/tests/io/parser/data/tar_csv.tar.gz
tar_data.csv
```

## Proposal
I think there is a logic somewhere (probably even in Bottle) which guesses mime type from file extension and another logic at the receiver side which tries to automatically unpack archive.

So I suggest that if conan is not downloading conan_package.tgz it shouldn't attempt to unpack.

(Or maybe this kind of setup is broken by design and conan_server should never serve packages from local cache).

**Comment by memsharded** [comment]
Yes, I think your setup is not possible. The storage of the conan_server is similar but not identical to the conan local cache, and it doesn't behave the same. This could be just one issue, but even if this is workarounded there will be other issues and problems, so please, better decouple and run ``conan upload`` to put the packages in the conan_server.

Also, I'd recommend to try the new and free Artifactory CE: https://www.conan.io/downloads.html

**Comment by ytimenkov** [comment]
I knew it! When I started gathering details something felt fishy.

It seems I tried all impossible use-cases :D

The plan was to use Conan to deploy almost directly from my local build folder to remote nodes (same as CI would do). packing/unpacking had annoying overhead :( (less than half a minute, but enough to break flow).

**Comment by memsharded** [comment]
Yes, there is some overhead of packaging/unpackaging, but it is necessary to keep things isolated and decoupled. For example for robust install concurrency. The local cache has some built-in concurrencty, intended for parallel installs, but definitely not for concurrent access from connected clients while packages are being created.

You might try to change the env-var http://docs.conan.io/en/latest/reference/env_vars.html#conan-compression-level CONAN_COMPRESSION_LEVEL, as this is typically relatively slow (defaulted for better and slower compression)

Next time ask first :) :) :) We try to help as much as possible. Also we are usually in the CppLang slack #conan channel, and the community there is amazing.
