### ISSUE TITLE
Suggestion: Add CMake build_types f.e.: RelWithDebInfo to default settings.yml

### ISSUE THREAD

**Issue by atvise** [conan-io/conan#2712]
Hi,

is it possible to add "RelWithDebInfo" and "MinSizeRel" to the build_type variable in the default settings.yml file?

Those build types are common within CMake generated projects.

It's not a big issue but we have to manually update the settings.yml file after each settings file update and that can be solved with adding those two build types.

Best regards,
atvise

Conan version: 1.2.1

**Comment by memsharded** [comment]
Yes, I think this is possible, though we have to check to make sure.

Just a quick suggestion: instead of updating the settings.yml after updates, you might want to use the ``conan config install`` functionality that will update the settings.yml automatically (together with other files)

**Comment by atvise** [comment]
Oh! I overlooked that in the documentation! Very nice feature! Thank you very much for that!
