### ISSUE TITLE
Allow specifying default options as a dictionary

### ISSUE THREAD

**Issue by T1T4N** [conan-io/conan#2713]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hello,

Looking at the structure of the conanfile.py, I always found it weird why the options were specified as a dictionary, but the default_options as a list of tuples.
This is not an issue for packages that have a small amount of options, but it gets ugly for projects with a lot of options. I always end up doing the following:
```python
_default_options = {
    "shared": True,
    "tools": True,
    ...
}
default_options = [(k, str(v)) for k, v in _default_options.items()]
```
In my opinion, it would be a great enhancement if the default_options would allow specifying values as a dictionary and would make the style of the conanfile.py more uniform.

Software information:
I'm currently using ```Conan version 1.2.0``` on
```
ProductName:    Mac OS X
ProductVersion: 10.13.3
BuildVersion:   17D102
```
with
```
Xcode 9.2
Build version 9C40b
```
and ```Python 3.6.4``` installed from brew

**Comment by memsharded** [comment]
Yes, this might be possible and I don't see any strong reason not to allow it.

**Comment by T1T4N** [comment]
@danimtb thanks for the quick reply.

The question was partly inspired when I looked at that exact line and saw that there is no ```isinstance``` case for dict, seeing as how it's a one-liner to convert it to a list of tuples.

@memsharded In my opinion this would be a great enhancement to the ConanFile
