### ISSUE TITLE
Question: Using conan export-pkg

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#2714]
Hi,

In the past (pre-0.28) using `package_files` the steps were to get a package into remote like Artifactory:
1. `conan export`
2. `conan package_files`
3. `conan upload`

Currently using `export-pkg`, will the first step (`conan export`) be redundant and therefore the steps are now:
1. `conan export-pkg`
2. `conan upload`

So does this mean `export-pkg` does an "internal" `conan export` or what exactly happens in `conan export-pkg`?

**Comment by memsharded** [comment]
> So does this mean export-pkg does an "internal" conan export or what exactly happens in conan export-pkg?

Yes, exactly. Users feedback gathered from ``package_files`` pointed that users preferred to have this step automatic by default. So ``export-pkg`` does the recipe ``conan export`` too. 

Also ``export-pkg`` has learned different modes of operation:
- Specifying ``--package-folder`` will perform a copy of the folder, without executing the ``package()`` method
- Specifying ``--build-folder`` and/or ``--source-folder`` will execute the ``package()`` method, to filter, select and arrange the layout of the artifacts.

**Comment by Twoflower2** [comment]
@memsharded 

> Users feedback gathered from package_files pointed that users preferred to have this step automatic by default

I fully agree!

> Also export-pkg has learned different modes of operation

Yes I got that from the docs, but as suggestion if you put it like this in the docs it is even clearer if you want to update the docs a bit.

Many thanks and please close.

**Comment by memsharded** [comment]
You are welcome!

Sure, that explanation reads better than the current one. Fixed in https://github.com/conan-io/docs/commit/9dbc911fe4a795635903879a1e1186ee221abbdd
