### ISSUE TITLE
Confusion parsing -sf and -s options

### ISSUE THREAD

**Issue by sansuiso** [conan-io/conan#2719]
Dear all,

I'm trying to upgrade our local infrastructure from conan 0.27 to conan 1.2.1 (latest current). So far, so good, and I'm now testing a sample recipe using the [package development workflow](http://docs.conan.io/en/latest/creating_packages/package_dev_flow.html) in order to evaluate how much we need to modify our recipes to account for the new version.

- Using `conan` 1.2.1 on Linux.
- The `conan source ` step works fine.
- The `conan install` step works fine (I'm testing with a recipe that has no dependencies).
- When running the `conan build` step, I get an error about source folder being specified twice.

More specifically, the command I run is:

`conan build . --source-folder=/tmp/conan/source --build-folder=/tmp/conan/build --install-folder=/tmp/conan/install -s arch=x86_64 -s os=Linux`

And the error message I get:

`conan build: error: -sf can only be specified once`

I need to pass the extra settings options since our recipes set some of them, but not all.
Removing the extra `-s bar=far` options removes the error (but triggers another one, which I think is linked to my setup, so that's fine).

Playing a bit with the command line, it seems that options starting with `-s` are mistaken /for `-sf` which is what triggers the error. Is it correct?

Also, what workaround would you advise in that case? Where should I specify globally these values if I want to avoid modifying the recipes one by one?

Thanks for your help!

**Comment by memsharded** [comment]
Hi @sansuiso !

I think there is some misunderstanding with the command ``conan build``. It does not accept settings. The command accepting the settings is the previous install, not the build. They are not redundant, because they have to be the same, so it makes sense to use them only once, the first moment they are needed, which is the ``conan install``. The ``conan build`` command is a thin wrapper, basically calling the ``build()`` method, and the context is retrieved from the files generated at ``conan install`` time.

Please try that, and tell me. Thanks for your feedback!

**Comment by danimtb** [comment]
Hi @sansuiso 

Thanks a lot for the feedback regarding your migration.

I have been able to reproduce your problem and it seems there is a problem in the command line parser. It should say something like:

```
conan build: error: unrecognized arguments: -s arch=x86
```

Settings cannot be specified in the conan build command, you have to specify them in the install step as indicated in the local development workflow:

```
$ conan install . --install-folder=/tmp/conan/install -s arch=x86_64 -s os=Linux
...
conan build . --source-folder=/tmp/conan/source --build-folder=/tmp/conan/build --install-folder=/tmp/conan/install
```

That way, Conan build will use the settings of the install folder in the build step

**Comment by memsharded** [comment]
Good! 
I think this issue can be closed now, but please comment or re-open if necessary. Thanks.
