### ISSUE TITLE
"visual_studio" generator support for multi-config variables (N configs -> 1 package)

### ISSUE THREAD

**Issue by taeguk** [conan-io/conan#2721]
I'm introducing ```conan``` in products of my company.
But, I found one limitation and I want improvement of it.

http://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-package

> The automatic conversion of multi-config variables to generators is currently only implemented in the cmake and txt generators. If you want to have support for them in another build system, please open a GitHub issue for it.

I found that sentence in above documentation. And I want to have support for them in **Visual Studio**, So I open this issue.

Thank you.

**Comment by lasote** [comment]
You mean to support it with the `visual_studio` generator?

**Comment by memsharded** [comment]
This has been implemented in https://github.com/conan-io/conan/pull/4300, it will be released soon in Conan 1.14 (hopefully this week).
