### ISSUE TITLE
replace_in_file() failed on Windows

### ISSUE THREAD

**Issue by jinq0123** [conan-io/conan#2724]
See: https://github.com/inexorgame/inexor-core/issues/589

If the searched string is multi-line, `replace_in_file(file_path, search, replace, strict=True)` will fail on Windows.
```
tools.replace_in_file(cmake_name, '''  11111
    2222''', '''  3333''')
```
```
ConanException: replace_in_file didn't find pattern
```
The reason is "\r\n" and "\n" mismatch.

```
λ conan --version
Conan version 1.2.1
```

**Comment by lasote** [comment]
Yes, the replace_in_file is literally looking for the string so a `\n` != `\r\n`. Try to replace line by line doing two "replace_in_file" or build a string to be replaced with `os.linesep`, something like:

`tools.replace_in_file(cmake_name, '''  11111%s    2222''' % os.linesep, '''  3333''')`

**Comment by memsharded** [comment]
Or maybe in this case you might try applying a patch, (with ``patch_string`` argument) which might be more robust to line changes.

Also, I would check if this is related to the ``autocrlf`` feature of git, that might be converting line feeds in different OSs. My suggestion when dealing with conan packages is try to use always the same one, the Linux single ``\n`` one, as nowadays most editors in Windows are fine with it (but the Notepad), and in that way the package files line endings will keep the same in all systems.

**Comment by Croydon** [comment]
I patched it as suggested by @lasote.

Thanks everyone!

**Comment by memsharded** [comment]
Thanks for telling @Croydon ! 
Can this issue be closed then?

**Comment by lasote** [comment]
> tools.replace_in_file() is error prone. It is better to document it in detail. Or discourage using it.
Prefer tools.patch().

Why? I like it very much! LoL

**Comment by HassanNawazish1** [comment]
I have the same issue 
ConanException: replace_in_file didn't find pattern
is there any solution
what should we place is PROJECT(    )

**Comment by memsharded** [comment]
Hi @HassanNawazish1 

Not sure what you mean. If it didn't find the pattern you are providing is an expected error, it is because that string is not found in the file and cannot be replaced. The solution is to use the correct string that will be found in the file.

**Comment by HassanNawazish1** [comment]
Thanks.
I was using the "PROJECT" instead of "project".
It worked now.
