### ISSUE TITLE
`requirements()` method with conan options for the requires itself.

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#2725]
On the `requirements()` method-
```python
def requirements(self):
    if self.options.myoption:
        self.requires("zlib/1.2@drl/testing")
    else:
        self.requires("opencv/2.2@drl/stable")
```

if package `opencv` had some conan options (lets say `type` and `OS`) as metadata declared for itself, how can the consumer in the above code add these options to the `self.requires()`? 

Like so ;-) `self.requires("opencv/2.2@drl/stable -o type=v2 -o OS=Guardian")`

I know you can specify these lib option at `conan install` time, but that is very tedious for many requirements with their own options.

**Comment by memsharded** [comment]
You can set the options for your requirements directly in the recipes in differents ways, depending on what you want to do:

- As default_options:

```python
default_options = "OpenCV:type=v2", "zlib:option=value"
```
Default options are overridable from downstream, in case it is needed. 

- Hardcoding in the ``configure()`` method:
```python
def configure(self):
     self.options["OpenCV"].some_option = some_value
```
These are hard-coded so not possible to override from downstream. The value will be forced, but it might produce some conflicts if there are diamonds in the graph and some other incompatible value is trying to be defined

**Comment by Twoflower2** [comment]
Thanks. I think the hardcoding will work in my use case, because a specific option of the consumer will always need a specific option of the lib it requires.

**Comment by memsharded** [comment]
Good, then, if you have a conflict because someone in your dependency graph tries to use a different value for that option, just define the correct value downstream (consumer) to resolve the conflict, and you would be ok.

Please let me know how it goes when you try, and if it works, then you might want to close the issue. Thanks!
