### ISSUE TITLE
cannot compile boost on mac (old c++ version?)

### ISSUE THREAD

**Issue by jaroslaw-weber** [conan-io/conan#2727]
Hey, I tried to compile boost on mac and is getting a lot of errors. This is my profile:
```
[settings]
os=Macos 
os_build=Macos 
arch=x86_64 
arch_build=x86_64 
compiler=apple-clang
compiler.version=9.0 
compiler.libcxx=libstdc++ 
build_type=Release 
[options] 
[build_requires] 
[env]
```
and this is my conanfile.txt
```
[requires] 
boost/1.66.0@conan/stable 
[generators] 
cmake
```
The errors I get are mostly because the conan is not using the c++11 when building boost. Here are few lines from log:
```
 error: no member named 'move' in namespace 'std' 
ERROR: boost/1.66.0@conan/stable: Error in build() method, line 98 self.run(full_command) ConanException: Error 2 while executing /Users/Jarek/.conan/data/boost/1.66.0/conan/stable/build/c6157df450f9df375e77adce4b103ecabe5a6c21/boost_1_66_0/tools/build/b2 address-model=64 link=static variant=release --without-python define=_GLIBCXX_USE_CXX11_ABI=0 cxxflags="-stdlib=libstdc++ -std=c++11" -j8 --abbreviate-paths -d2 --debug-configuration --build-dir="/Users/Jarek/.conan/data/boost/1.66.0/conan/stable/build/c6157df450f9df375e77adce4b103ecabe5a6c21"
````
How can I fix this? It would be great to have precompiled boost. I tried to fix it, but waiting for the building is very long.

**Comment by memsharded** [comment]
Quick question, why not using 

```
compiler.version=9.0 
compiler.libcxx=libc++
```

That should be the default for apple-clang, and you will have binaries for it.

**Comment by jaroslaw-weber** [comment]
Wow, it's working now, thanks a lot!

To be honest, I copied those settings from somewhere because my default settings were not working (couldnt build "zlib/bzip" from source).

So these were my default settings on clean install:

```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

I have installed clang from homebrew. I don't have much experience with c++, didn't know about the apple-clang/clang situation.
Something went wrong with the compiler detection?

**Comment by danimtb** [comment]
@jaroslaw-weber Do you have clang 6.0 installed in you machine too? Maybe that is why it is detecting that version.

BTW, if the original issue is solved, feel free to close this issue and open another for the default profile detection.

Many thanks! 😄
