### ISSUE TITLE
Adding a generic way to pass variables to dependencies' cmake generator

### ISSUE THREAD

**Issue by blastrock** [conan-io/conan#2730]
I would like to have a generic way to pass cmake options from a conanfile to all packages that depend on it and use the cmake generator.

There is already something like that documented here: http://docs.conan.io/en/latest/reference/env_vars.html#cmake-related-variables , but it only works with that list of variables.

About why I need this: I am trying to write a toolchain file for cross-compilation. I am already using the `CONAN_CMAKE_TOOLCHAIN_FILE` variable to expose the cross-compilation toolchain. My compiler is a little broken and adds `extern "C"` declarations around every .h included from a `-isystem` path (see #269). I would like to workaround this by passing the cmake option `-DCMAKE_NO_SYSTEM_FROM_IMPORTED=ON` to all projects that use my toolchain and cmake. #2629 suggests another way of doing that, or using `-DCONAN_SYSTEM_INCLUDES=OFF` for that.

Seeing all this, I think it would be a good idea to have a generic way to pass such options as there may be other such cases. Maybe the conan generator would pass all variables in the format `CONAN_CMAKE_SOMETHING` as `-DSOMETHING` to cmake. Note that this is not compatible with the current variables as you would have to define `CONAN_CMAKE_CMAKE_TOOLCHAIN_FILE` to define `CMAKE_TOOLCHAIN_FILE`, it may be a little redundant.

**Comment by memsharded** [comment]
Passing any arbitrary CMake variable to downstream consumer never got enough demand. There are several reasons, but for example, the fact that downstream consumers could have other build systems is important, the information to propagate should be abstracted as much as possible from the specific build system of the consumer.

Passing the toolchain (now with something like ``conf`` item ``tools.cmake.cmaketoolchain:toolchain_file=xxxx``) is still probably possible, you can put whatever variables you want in the toolchain.

However, it is likely that there are other possible better approaches. If it is an issue of the compiler itself, not the dependency, the responsibility is not on the dependency, but on the toolchain. In that regard ``CMakeToolchain`` could help to define in the consumers the necessary variables, conditioned to different compilers. With ``python_requires`` this might be even made common and reused easily among recipes.

It is also possible to directly inject additional CMake toolchains from the profile with ``tools.cmake.cmaketoolchain:user_toolchain`` in an "append" way, to all packages using ``CMakeToolchain``. That is probably also cleaner.

I am closing this issue as "wont' implement", passing arbitrary cmake variables to consumers would be high coupling, and it seems there are better ways to approach this.
