### ISSUE TITLE
Support for Jenkins SCM changes? [question]

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#2731]
I find the summary of SCM changes in the Jenkins 'Stage View' incredibly useful when inspecting the status of my projects.  Since the Conan checkout does not make use of the pipeline code 'SCM checkout', this view is no longer updated.

I do not know how feasible it is, but is it possible to generate a Groovy script for performing the checkouts?  A Jenkins job could then use the 'load' command to run this generated file and record the scm change information as before.

**Comment by GordonJess** [comment]
By "Conan checkout" I meant the execution of the commands in the source() method.

To get the information I want,

![image](https://user-images.githubusercontent.com/5827761/38541979-a7e3aeaa-3cdb-11e8-9f10-4534e01c40aa.png)

I checkout using the Jenkins pipeline plugin "checkout scm" (groovy code):

> checkout(scm: [$class: 'SubversionSCM', locations: [[credentialsId: '<credentials>', depthOption: 'infinity', ignoreExternalsOption: false, local: '.', remote: "https://example.svn.server/svn1/trunk/submodule_A"]], workspaceUpdater: [$class: 'CheckoutUpdater']])

I was only brainstorming, but I thought perhaps the above command could be written to a groovy script, for use by Jenkins.

The more I've thought about it, the less sense it makes, as it would require differentiating between jenkins/non-jenkins builds and separating this configuration from the Jenkins pipeline, where it should be.  Perhaps better left for a Conan plugin, if there is ever the demand...

**Comment by Aalmann** [comment]
@GordonJess I guess Jenkins uses an xml format. Have a look at your Jenkins master directory `.../jobs/<jobname>/builds/<buildnr>/changelog<nr>.xml`. Your approach makes sense when recipe and source code is not in the same repository. Currently to get all the scm changes, you have to checkout the recipe AND the sources with the pipeline checkout. But then the checked out sources are completely unused which could end in a quite longer execution time depending on your source repo size and checking out sources twice.

@lasote Just as an idea, this could be part of the `conan_build_info` command in combination with the artifactory plugin. Conan has to provide the scm information to the log file, `conan_build_info` collects them and creates an additional entry in the build info output json file and the artifactory plugin provides these information to Jenkins. Not easy to implement, but worth to think about it.

**Comment by memsharded** [comment]
Closing this ticket as outdated. In any case, it doesn't seem possible to implement as built-in this groovy-jenkins scm thing. Users can do whatever they want in the ``self.run()`` of the source method.
