### ISSUE TITLE
Depending on a library that uses Conan in a project that does not

### ISSUE THREAD

**Issue by soehrl** [conan-io/conan#2737]
Hi,

at my company we are slowly switching to Conan for managing our dependencies. However, at the moment we face some issues when a project which is currently not using Conan depends on a library that is.

In the specific scenario we have a library that uses Conan to install the Poco dependency (among others). In our cmake script we add the dependencies as follows:
```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
# ...
target_include_directories(mylib PUBLIC CONAN_PKG::Poco)
target_link_libraries(mylib CONAN_PKG::Poco)
```

When linking _mylib_ to an executable defined in the same cmake project all dependencies are resolved correctly. However, when exporting the target using `export(TARGETS mylib FILE "${PROJECT_BINARY_DIR}/mylib-targets.cmake")` the resulting file contains the following:
```cmake
set_target_properties(mylib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "<other includes>;<root dir>/mylib/CONAN_PKG::Poco"
  INTERFACE_LINK_LIBRARIES "CONAN_PKG::Poco"
)
```
Note that the target's include directories and libraries were not resolved. So, when I'm including the library in another project (that does not use Conan yet) like this:
```cmake
find_package(mylib REQUIRED)
target_include_directories(some-project PUBLIC mylib)
target_link_libraries(some-project mylib)
```
Building the project obviously fails as the include directories and libraries cannot be found.

This only happens when the target is defined by Conan, for other targets it works as expected. Am I doing something wrong or is there a workaround for this? At the moment it would be really useful to be able to use libraries that use Conan with projects that do not as it is not possible to convert all repositories at once and often a library has a higher priority than projects depending on it.

I'm using:
Conan version 1.1.1
cmake version 3.10.3

**Comment by memsharded** [comment]
I am not an expert in ``cmake export`` functionality, but I would say this is a limitation of cmake. You can read for example: https://stackoverflow.com/questions/30987311/exporting-an-imported-library and https://answers.ros.org/question/223866/cmakecatkin-how-to-export-imported-target/. In both you can see some workarounds, but not a fully working cmake solution.

The reason it doesn't work with conan is because CONAN_PKG:: targets are IMPORTED ones.
Maybe you could try using the old-style cmake, without targets? With that you get just a list of libraries to link with.

**Comment by danielmevi** [comment]
Is there any new solution for this issue?

**Comment by memsharded** [comment]
Hi @danielmevi 

Just a quick question, have you tried the new ``cmake_find_package`` or ``cmake_find_package_multi`` generators, that use ``find_package()`` calls, and then, it could be more transparent?

**Comment by danielmevi** [comment]
@memsharded  will try that. Thanks

**Comment by memsharded** [comment]
Conan 2.0 is able to provide full transparent integration with CMake, so this shouldnt be an issue anymore. Closing this ticket, please open new ones if necessary, thanks.
