### ISSUE TITLE
Size reported by tools.human_size should follow international standards

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#2741]
I'm using conan 1.2.3 on Ubuntu 14.04. 
Currently we have:
```
>>> from conans import tools
>>> tools.human_size(1000 * 1000 * 1000 * 1000)
'931.32GB'
>>> tools.human_size(1024 * 1024 * 1024 * 1024)
'1.0TB'
```
I think you should return units of the international system instead to avoid confusions (and also because it's  been in use since 1998). The difference between decimal and binary units is growing and growing as time passes:

https://en.wikipedia.org/wiki/Byte#/media/File:Binaryvdecimal.svg

So instead, a possible result would be:
```
>>> from conans import tools
>>> tools.human_size(1000 * 1000 * 1000 * 1000)
'1.0TB'
>>> tools.human_size(1024 * 1024 * 1024 * 1024)
'1.1TB'
```
The last result being dependant on how you round the result, of course.

If you don't want to make this move, using the binary units to avoid ambiguity would be prefereable.
Another option is to have an argument `use_si_units=True` and let the user chose.

Source:
- https://en.wikipedia.org/wiki/Byte#Unit_symbol
- http://www.iec.ch/si/binary.htm

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by rukgar** [comment]
Created PR #2742 but not really sure if it requires documentation changes.

**Comment by memsharded** [comment]
No, not necessary, it is not explicit in the docs, and in any case, it is fixing it to the correct units, little to say in the docs. Thanks!
