### ISSUE TITLE
Partial packages on disk

### ISSUE THREAD

**Issue by drussel** [conan-io/conan#2745]
On our CI systems (and to a lesser extent locally) we occasionally end up with partial packages in our conan directory. This is especially common with boost which has tons of headers and so takes a long time to extract on windows. It appears that if conan is interrupted during expansion (eg our ci system decides not to finish the job), we can end up with some of the headers and no lock file or other indication that things are broken until  compilation fails. One possibility would be to expand into a directory with a different name and then rename it after expansion.

We have seen this across various conan versions including 1.2

**Comment by memsharded** [comment]
Hi Daniel!

I think this might be a duplicate of https://github.com/conan-io/conan/issues/1003. Please have a look, and if it is, close this one and follow the conversation there.

Thanks!

**Comment by drussel** [comment]
Yup. Thanks.
