### ISSUE TITLE
Lock files and CI systems

### ISSUE THREAD

**Issue by drussel** [conan-io/conan#2746]
On our continuous integration systems we occasionally end up in a state where conan has been interrupted during an operation and so left a lock file on disk. It is not clear how to cleanly recover from this in an unattended system.

One option would be to add a "I know there is no other valid conan process so please blow away any any locked package" to `conan install`. Or perhaps a cleanup sort of command that looks for any locks or broken state cleans it up.

**Comment by drussel** [comment]
Duplicate of #1003

**Comment by memsharded** [comment]
Uhm... the #1003 is more about that if a package install is interrupted, the package will be at least marked for deletion or deleted. Lock files can be left marked as "busy" for interrupted processes, not only for the packages, but also, for example while installing the recipe or retrieving sources (the package creation still has not started). 

In practice, yes, it might be that 95% of the cases are those of #1003, so thanks for closing this issue. Lets try to improve that, and if this issue persists for other cases, please re-open.
