### ISSUE TITLE
Complex custom FindXXX.cmake example or generator?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2748]
Conan manual explains [how to create a custom FindXXX.cmake file](http://docs.conan.io/en/latest/integrations/cmake/find_packages.html#creating-a-custom-findxxx-cmake-file). Basically it's
```cmake
find_path(ZLIB_INCLUDE_DIR NAMES zlib.h PATHS ${CONAN_INCLUDE_DIRS_ZLIB})
find_library(ZLIB_LIBRARY NAMES ${CONAN_LIBS_ZLIB} PATHS ${CONAN_LIB_DIRS_ZLIB})

set(ZLIB_FOUND TRUE)
set(ZLIB_INCLUDE_DIRS ${ZLIB_INCLUDE_DIR})
set(ZLIB_LIBRARIES ${ZLIB_LIBRARY})
mark_as_advanced(ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
```

Unfortunately it only works for simple packages consisting of one lib file with no dependencies. If your package need to link multiple lib files you end up with something like [FindBoost.cmake](https://github.com/bincrafters/conan-cmake_findboost_modular/blob/stable/1.66.0/FindBoost.cmake)

My question is: can we create something standard enough for that purpose? Maybe to add a function to `conans.tools` that will generate FindXXX.cmake using conan cpp_info/dep_cpp_info?

**Comment by lasote** [comment]
Well, the case of Boost libraries, where there are dependencies between libraries in the same package, would require modeling the relationship between them in Conan if we would want to generate something automatic. We have an open issue for that, but I can't find it right now.

But probably the best idea is to generate the `FindXXX.cmake` using the native CMake install feature.
The only thing is CMake usually generate absolute paths. We have a `patch_config_paths` in the conan CMake() build helper to patch that config files: http://docs.conan.io/en/latest/reference/build_helpers/cmake.html?highlight=patch_config_paths

So the idea is use CMake to generate all the config files and patch them with Conan before package.

**Comment by db4** [comment]
> The only thing is CMake usually generate absolute paths. We have a patch_config_paths in the conan CMake() build helper to patch that config files:

Unfortunately this does not work for me. I have conan `LibA` package that requires conan `LibB` package. Then during the build cmake detects `LibB` and generates `LibAConfig.cmake` that contains absolute paths for both `LibA` and `LibB` libraries. `patch_config_paths` only fixes `LibA` paths but leaves `LibB` absolute paths intact. 

I still tend to think that some tools for conan developers to create custom `FindXXX.cmake/XXXConfig.cmake` would not be bad idea. To get something like this:
```cmake
# Try to find XXX
# Once done, this will define
#
# XXX_FOUND        - system has XXX
# XXX_INCLUDE_DIR  - The XXX include directories
# XXX_LIBRARIES    - The libraries need to use XXX

set(XXX_FOUND TRUE)
set(XXX_INCLUDE_DIRS ${CONAN_INCLUDE_DIRS_XXX})
if(TARGET CONAN_PKG::XXX)
  set(XXX_LIBRARIES CONAN_PKG::XXX)
else()
  # What to do if TARGETS option is not enabled? Tricky part
  # (maybe auto-generated) should go here...
  set(XXX_LIBRARIES ...)
endif()
```

**Comment by lasote** [comment]
Maybe you are right, if the CMake internal way to generate them is painful we could take it into consideration. About your concrete implementation, in case of targets, you don't need to do anything, right? just `set(XXX_FOUND TRUE)`. Because Conan already provides the target.
In the `else` case, it has to be generated from the information read from the object `self.cpp_info`, to set accordingly the include directories and library names.
@memsharded @danimtb feedback welcome.

**Comment by lasote** [comment]
Hi, take a look at #2875, I think it covers this issue, right?
