### ISSUE TITLE
Add -ks as an alias for --keep-source

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#2751]
You already have:
`-kb` for `--keep-build`
`-if` for `--install-folder`
`-sf` for `--source-folder`
`-bf` for `--build-folder`
`-pf` for `--package-folder`

Therefore, out of consistency, you should also have
`-ks` for `--keep-source`

Running conan 1.2.3 on Ubuntu 14.04.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, this makes sense. However the ``-k`` has to be kept, to not break. But I think it is possible to have multiple values, so this could be added, thanks for the suggestion!
