### ISSUE TITLE
ERROR: There is no local conanfile exported (conan upload)

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#2754]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan Version 1.2.1
Linux RHEL 6.9 VM (Bamboo build machine)

Using Conan Package Tools to generate package variants in CI.
After packages are created they are uploaded using eg:
```
conan upload --all -r conan-idb-falcon core-ull/1.41@idbdevbuild/testing
```
Often there is an error:
```
ERROR: There is no local conanfile exported as core-ull/1.41@idbdevbuild/testing
```
The `conanfile.py` does exist in the local cache:
```
[idbdevbuild@usdevbuild03 export]$ pwd
/develop/idbdevbuild/.conan/data/core-ull/1.41/idbdevbuild/stable/export

[idbdevbuild@usdevbuild03 export]$ cat conanfile.py
from environment.conan.base_conan import BaseConan

class FalconConan(BaseConan):
    name = 'core-ull'
    description = 'Falcon core-ull library'

    # Dependencies
    requires = (
        'jsoncpp/1.8.4@theirix/stable',
        'spdlog/0.16.3.1@idbdevbuild/stable'
    )
```
@drodri recommended that we put in a sleep before uploading, but that didn't fix it.  I have CI machine that is in this state right now (8 hours after the package creation).  I can log into it and try the upload and get the same error.   So it's a good debugging scenario.  Just let me know what I should try to diagnose.

Thanks,

**Comment by sourcedelica** [comment]
This only seems to be happening in our CI environment.  These are VMs, but otherwise the OS and everything is the same as our regular Dev machines.

**Comment by memsharded** [comment]
Yes, please, the first step could be to make a copy of your local cache for that package, put it in a ZIP file and send it (if it is private, please send an email, or contact in slack). Have you checked if the ``BaseFile`` file is there too? Thanks for your help!

**Comment by sourcedelica** [comment]
Which email can I send it to?

The `base_conan.py` file is not in `export` (or in any directory in the cache).   That file is not exported in the recipe, rather it is in the `PYTHONPATH`.  I don't want the recipe to have to have it because it's boilerplate and it's easy to get wrong.   I could potentially add it to the `exports` in the base class if that would help.

One thing that I've found is that if I run the same CI script on the CI machine manually it usually works.  It's only when the script is run via Bamboo that it often breaks.

**Comment by memsharded** [comment]
info@conan.io, please

**Comment by sourcedelica** [comment]
I was unable to send it via email because it's too big.  Is there another route?

**Comment by sourcedelica** [comment]
I replicated the issue on my Windows machine today:
```
Scanning dependencies of target example
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.obj
[100%] Linking CXX executable bin\example.exe
[100%] Built target example
database-common/3.8.0.12@idbdevbuild/testing (test package): Running test()
conan create . database-common/3.8.0.12@idbdevbuild/testing

epederson@hfc-epederson MINGW64 /e/work/falcon-conan/database/common (master)
$ conan upload --all -r conan-idb-falcon database-common/3.8.0.12
ERROR: No packages found matching pattern 'database-common/3.8.0.12
```

**Comment by danimtb** [comment]
Mkae sure you specify the complete reference:
```
$ conan upload --all -r conan-idb-falcon database-common/3.8.0.12@idbdevbuild/testing
```

**Comment by sourcedelica** [comment]
I added `base_conan.py` to the `exports` but that didn't help.

```
epederson@hfc-epederson MINGW64 ~/.conan/data/database-common/3.8.0.12/idbdevbuild/testing
$ ls export
base_conan.py  conanfile.py  conanmanifest.txt
```
```
epederson@hfc-epederson MINGW64 /e/work/falcon-conan/database/common (master)
$ conan upload --all -r conan-idb-falcon database-common/3.8.0.12                                     ERROR: No packages found matching pattern 'database-common/3.8.0.12
```

**Comment by sourcedelica** [comment]
I added `base_conan.py` to the `exports`, so `base_conan.py` is in the `export` directory.
```
[idbdevbuild@usdevbuild03 stable]$ ls export
base_conan.py  conanfile.py  conanmanifest.txt
```
But upload is still broken in CI.
```
13-Apr-2018 14:49:38 | conan upload --all -r conan-idb-falcon core-ull/1.44@idbdevbuild/testing
13-Apr-2018 14:49:38 | ERROR: conan upload --all -r conan-idb-falcon core-ull/1.44@idbdevbuild/testing
13-Apr-2018 14:49:38 | Failing task since return code of [environment/conan/scripts/bamboo-build-conan-module.sh core-ull .] was 1 while expected 0
```

**Comment by danimtb** [comment]
Sorry, @sourcedelica it is not clear to me how did you come across this issue. I cant see if it is an upload or an export issue.

Could you please indicate the steps to reproduce it?

**Comment by sourcedelica** [comment]
Hi Daniel - it’s an upload issue.  See the very first post in this thread.

**Comment by memsharded** [comment]
@sourcedelica yes, you can put the file in any system you want (google drive, dropbox, etc) and send me the link to info@conan.io

**Comment by sourcedelica** [comment]
Ok, it's going to be hard due to our data policies, but I'll figure something out.

**Comment by sourcedelica** [comment]
I split it into 6 emails with subject "Data for issue #2754 #n"

To reassemble the data, take the files and `cat xa* > core-ull-1.43-cache.zip`.

**Comment by memsharded** [comment]
I have been able to assemble the data files, tested them, and they can be uploaded on my machine. 
So data seems to be OK, now I am bit lost where the error could be:

- If it is in the CI machine only with bamboo, I would start stopping the bamboo service, trying to upload. To check if it is some weird interaction of bamboo (could bamboo be processing "export" folders?)
- I would introduce a couple of prints in conan codebase and run from sources to learn what is happening.

I am available tomorrow, we can discuss and debug this live in slack if you want. Thanks!

**Comment by sourcedelica** [comment]
I've got CI setup to run from sources.  Let me know if here or on slack what prints you want me to add.

**Comment by sourcedelica** [comment]
The problem turned out to be related to Conan Package Tools (CPT).  CPT was setting the package channel to `stable` because the Git branch was master.  I hadn't noticed this warning message:

    WARNING: Redefined channel by CI branch matching with 'master', setting CONAN_CHANNEL to 'stable'

This was only happening in CI because CPT only does the channel renaming in CI.

> If the env var bamboo_buildNumber is set and the branch name (bamboo_planRepository_branch env var) matches stable_branch_pattern, then the channel name gets set to stable.

CPT created the packages in `stable`, but when our CI script went to upload, expecting the channel to be `testing`, the upload failed.  

The fix was to add `export CONAN_STABLE_BRANCH_PATTERN='release/*'` to our CI script, disabling the channel rename.

As a side note, we were not using the upload functionality of CPT.   When I added `CONAN_STABLE_BRANCH`  I also decided to test using the CPT upload functionality but ran into [a problem](https://github.com/conan-io/conan-package-tools/issues/156).  This was because our CI script also creates a Conan alias and uploads it, but CPT renames the remote to `upload_repo`.  I decided to just keep uploading the package in our CI script instead of using CPT to upload.  I suggested [an enhancement](https://github.com/conan-io/conan-package-tools/issues/156#issuecomment-382826690) which would allow me to use the CPT upload functionality.

Much thanks to @lasote to helping me debug this!

**Comment by sourcedelica** [comment]
PS - I really should have looked at the logs closer before logging this issue.

**Comment by memsharded** [comment]
Thanks @sourcedelica for following up, summarizing your findings and your efforts to solve this!

I should also have noticed the mismatch in your report about testing/stable, the information was there, but I didnt :( 

Somethings your brain just filter out some things based on your assumptions... 

Happy it is solved now.
Cheers.

**Comment by sourcedelica** [comment]
Totally, that’s exactly what happened with me. Assumptions get the best of me some times.
