### ISSUE TITLE
Invalid formatting of libdir/includedir in pkg_config generator [bug]

### ISSUE THREAD

**Issue by coffee-lord** [conan-io/conan#2756]
Version: conan-1.2.3
OS: Linux

https://github.com/conan-io/conan/blob/ac25c8994878706bac23efd009ae74bc294c1add/conans/client/generators/pkg_config.py#L28-L36

`pkg_config` generator doesn't check if libdir or includedir are absolute paths which leads to the following (invalid) `.pc` being generated for `boost_math/1.66.0@bincrafters/stable`:

```
prefix=/home/user/.conan/data/boost_math/1.66.0/bincrafters/stable/package/937af278b1c9d86290dddaf1322dc99fb7d75862
libdir=${prefix}//home/user/.conan/data/boost_level8group/1.66.0/bincrafters/stable/package/afc149253b16bde7d64e527e0dbfa27b203330c8/math/lib
includedir=${prefix}//home/user/.conan/data/boost_level8group/1.66.0/bincrafters/stable/package/afc149253b16bde7d64e527e0dbfa27b203330c8/math/include
...
```

**Comment by danimtb** [comment]
Hi @coffee-lord !

Thanks you so much fot the detailed report. Seems it is a bug with absolute paths as you said, mainly affecting recipes with `short_paths=True` like boost ones.

We will try to fix it for the next release.
Thanks!

**Comment by coffee-lord** [comment]
@danimtb While we're on the subject, pkg_config generator also doesn't emit `-Wl,-rpath=` flags. Is that intentional?

**Comment by danimtb** [comment]
Hi @coffee-lord 

Yes, those flags are missing from the logic of the generator. Let's update it with those flags now that we have a PR open for this.

Thanks!

**Comment by coffee-lord** [comment]
With regards to #2797:

**1. `-L${libdir}` is added unconditionally**

https://github.com/conan-io/conan/blob/8f9f56496249247ec619d9e973b6b6a73031e433/conans/client/generators/pkg_config.py#L45-L48

Which leads to "Variable 'libdir' not defined" error in pkg-config when `dir_lines` is empty.

```
prefix=...
includedir=...

Name: boost_conversion
Description: Conan package: boost_conversion
Version: 1.66.0
Libs: -L${libdir} ...
```

**2. Irrelevant rpaths**

It seems that pkg_config generator outputs rpaths of all dependencies which makes the list of compiler arguments exponentially long. I don't think we need to include rpaths of dependencies at all.  `-L${libdir} -Wl,-rpath${libdir}` for each libdir should be enough.

Relevant package: `boost_conversion/1.66.0@bincrafters/stable`

@memsharded

**Comment by memsharded** [comment]
Yes, the first thing is certainly a bug. Will be solved as soon as possible.
Also, the second observation is relevant too, lets try to improve it also.

Many thanks for your early and detailed feedback!
