### ISSUE TITLE
Settings friction review

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#2758]
I've been experimenting with non-common settings for embedded devices and I've found a couple of issues:

1. We have to review why the CMake() build helper is raising in case it doesn't have compiler or architecture. It is very very uncomfortable to specify the settings and deleting them later for the package_id just to avoid the error. And it makes no sense. 
2. If I install a `conanfile.txt` but without specifying `os` setting, it is crashing in the settings.py validate() method. Because somehow it has the os in the fields but not in the data.

**Comment by niosHD** [comment]
Thank you for looking into this! I already ran into the CMake helper issue multiple times, for example, [when installing a header only library with the CMake generated install target](https://github.com/vthiery/conan-jsonformoderncpp/pull/17).

**Comment by memsharded** [comment]
This is interesting, but not sure how we will manage to do this. Even for a ``cmake install`` of a header-only library, the cmake generator is needed, and it can be something like ``Visual Studio 15 Win64``, so the compiler, version, architecture, is still needed.

But I agree we need to have a look at this.

**Comment by lasote** [comment]
There is not a default in Windows? In Linux/OSX there is no problem unless you want to use other than the "Unix Makefiles". And yes, it looks like it is only for the generator, we could include something like "or specify CONAN_CMAKE_GENERATOR environment variable instead" in the error message. Better to specify an env var in the profile than messing with unneeded settings.

**Comment by memsharded** [comment]
Nop, that is the issue. In Linux it is fine, because Unix Makefiles is ubiquotous. But they won't work in Windows unless you have that tool installed, which is pretty annoying.

**Comment by lasote** [comment]
I see. Could we raise only in case of Windows and not CONAN_CMAKE_GENERATOR, giving the hint of providing a generator in the error message? Maybe a warning in the rest of system's is enough.

**Comment by memsharded** [comment]
Yes, if CONAN_CMAKE_GENERATOR is defined, it will never raise.

But the problem with that is that it will create broken recipes. A normal package creation of this package will fail, because CONAN_CMAKE_GENERATOR is not defined by the user. I think that ``conan create`` from a package recipe repo should always work.

**Comment by lasote** [comment]
I meant only if CONAN_CMAKE_GENERATOR not defined and `compiler` or `arch` not defined.
