### ISSUE TITLE
conan export-pkg config problem

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#2777]
Conan version 1.2.3

My cmd `conan export-pkg . pack/1.2.3@user/channel --force -o subset=all` does not seem to work, no src is copied to local cache, for copying everything as src only lib with layout:

```
|-pack
|-libs
|-tools
|-conanfile.py
```
 
**conanfile.py**
```python
from conans import ConanFile

class PackConan(ConanFile):
    version = "1.2.3"           #Semver
    name = "pack"
    description = "pack"
    subsets = ['all', 'regex', 'placeholder1', 'placeholder2', 'placeholder3']
    options = { "subset" : subsets }
    
    def build(self):
        self.copy("*.*", src="pack", dest="pack")
        self.copy("*.*", src="libs", dest="libs")
        self.copy("*.*", src="tools", dest="tools")
```

Please assist for this must be some simple config issue in `package()` method.

**Comment by danimtb** [comment]
Hi @Twoflower2 

I think the conanfile you are posting may be wrong. I can see no pacakge method there.

Maybe it was just a mistake and you are actually using:

```
def package(self):
        self.copy("*.*", src="pack", dest="pack")
        self.copy("*.*", src="libs", dest="libs")
        self.copy("*.*", src="tools", dest="tools")
```

Could you post the complete recipe? Thanks! 😄

**Comment by Twoflower2** [comment]
Oh my goodness I'm fast asleep. I meant to use actually use `package()` method + I used `dest=` which should be `dst=`

Apologies and please close.
