### ISSUE TITLE
managing dynamic options?

### ISSUE THREAD

**Issue by Lnk2past** [conan-io/conan#2780]
Windows 7
Conan version 1.2.3
Visual Studio 2015
Visual Studio 2017

Need some help, as I think I've twisted my scenario up pretty badly. Not even sure if this is appropriately named.

Some initial information:
I have been using Conan to handle "toolchains" for a particular group. This group has some requirements for how all of their 3rd party dependencies are built. For the sake of this post I will use just one of those requirements.

All Release builds are to be built with the flag _ITERATOR_DEBUG_LEVEL=0, and all Debug and RelWithDebugInfo builds are to be built with _ITERATOR_DEBUG_LEVEL=1. Note that per [Microsoft's documentation](https://msdn.microsoft.com/en-us/library/hh697468.aspx), this goes against the defaults for the debug builds. 

So here is my problem:
In our recipes we added an option "ITERATOR_DEBUG_LEVEL", and we control that value using various profiles for each build variant (we have release, debug, and relwithdebinfo profiles). In the event that another group wants to leverage the same recipe they would need to supply a value to that option; this seems redundant though, as their typical workflow may not require them to normally do so. If the option is not specified, then it should not be included in the build at all and should ultimately fall back on the compiler to assign a value.

I thought about setting some invalid default value (say, -1) that I can detect and scrub out if it is found (ultimately leading to just using VS defaults), but this seems hackish.

Have I gone too far off the deep end with this? Any and all suggestions welcome.

**Comment by memsharded** [comment]
There is a special value for options and settings that could be what you are looking for: ``None``. 
Value ``None`` doesn't affect the package ID, doesn't need to be specified in profiles. It is typically associated to the "default if nothing is specified". So an option ``iterator_debug_level: [None, 0, 1]`` could make sense. Then, the only thing to have in mind if you want to have exactly 2 binaries for the package and not 3 is to use ``package_id()`` to build the logic you want (if you know what are the compiler fallbacks for the value for your different settings).

Please give it a try and tell me if it helps.

**Comment by Lnk2past** [comment]
I have no idea how I missed this feature, thank you!
