### ISSUE TITLE
No colored output in certain terminals

### ISSUE THREAD

**Issue by lachlankrautz** [conan-io/conan#2782]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Using:   

- conan 1.3.0-dev
- windows 10
- pycharm 2018.1

Unable to get colored output in pycharm run output.

- Open conan in pycharm
- Add run configuration
    - script path: `<path-to-project>\conans\conan.py`
    - environment variables:
      - `PYTHONBUFFERED=1`
      - `CONAN_COLOR_DISPLAY=1`
    - python interpreter 2.7
    - working directory `<path-to-project>\conans`

Unfortunately the env variable `CONAN_COLOR_DISPLAY` is ignored if the tty check fails. I think if the user asks for color it should override other checks.

**Comment by memsharded** [comment]
Solved by #2783, will be in conan 1.3. Thanks!
