### ISSUE TITLE
devenv not included with visualstudiobuildtools2017

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#2785]
`devenv` is the GUI of visual studio, and therefor not included in visualstudiobuildtools.  This means that Conan cannot upgrade the solution the way it normally does.  It throws an error that `devenv` cannot be found. 

This is not actually a bug/issue with Conan, but a limitation of build tools.  I post it here because based on a cursory investigation, it seems that upgrading a solution file might be trivial, and there might be alternative methods for doing it.  Perhaps an alternate implementation of the feature could be made to work with build tools. 

At the very least, people should be aware of this issue. 

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Sometimes without upgrading a solution it just works. Just in case you don't know it, you can disable the project updating with `CONAN_SKIP_VS_PROJECTS_UPGRADE`. I know that this is not the concern explained in this issue, but just in case.

**Comment by solvingj** [comment]
The good news is that for my case, i found out that starting a few months ago, the `--include-optional` on the build_tools installer does include vstoolset 140, which is what i needed to build with. https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools
