### ISSUE TITLE
Make it possible to test a specific package_id

### ISSUE THREAD

**Issue by tru** [conan-io/conan#2789]
Currently when you want to test a package that is built with a `install` command you need to be very careful to reproduce settings and options really closely. It would be very helpful to be able to supply a package_id to test in order to test that specifically. This would avoid all problems with having to figure out the settings and options used.

## My use case
We use `conan install --build=outdated <metapackage> --json output.json` to build our packages and then parse output.json for finding out what packages that was built successfully. Currently I need to parse conaninfo.txt as well afterwards to figure out what options used to build the package. With the output data I do have the package_id used and after some discussion with @lasote it seems like we could learn `conan test` to take a package_id to test this package afterwards.

## Suggested flow
* `conan install --build=outdated meta/1.0@foo/stable --json output.json`
* `parse output.json`
``` pseudo code: 
for pkg in built_packages:
  conan test $pkg.reference --build=never --package_id $pkg.package_id
```

**Comment by lasote** [comment]
We realized that even having the package_id and the built package you need the set of settings and options, that are, of course in the conaninfo. So, finally, it is almost the same case than reproducing the build, alias "log" feature. We definitely want to do this, but it will require time, it is a big change.

**Comment by memsharded** [comment]
Exactly. As the ID is a hash of the settings, options, etc., it is impossible to reproduce the environment that created that ID from the ID. It will be necessary to capture that environment in an improved, complete version of conaninfo, and use that to feed the ``test`` command.

**Comment by danimtb** [comment]
I think this is closely related to lockfiles #5412

**Comment by memsharded** [comment]
Yes, as it is impossible to reproduce the environment from just an ID there are 2 alternatives:

- Keep track of the lockfiles used while generating packages, storing them somewhere. When desired, search for that specific ID in them, to retrieve the lockfile. Use the lockfile to feed the package creation (the lockfile contains embedded a full profile, options, etc., everything that is necessary)

- Storing the lockfiles inside the packages. This is probably something that we will consider in the future,
but right now it is unfeasible, lockfiles will certainly evolve, probably with some breaking changes, and storing them in the packages will be a nightmare for maintaining stability and not breaking that much. Too early for this.

In any case, the second is a "convenient" and automatic storage, but the principle is still the same: based on the full reference, it is possible to recover a lockfile, with the lockfile, you get full and deterministic reproducibility.

**Comment by memsharded** [comment]
Closing as inactive
