### ISSUE TITLE
[trivial] wrong release year in github releases for 1.2.3 and 1.2.2

### ISSUE THREAD

**Issue by bassosimone** [conan-io/conan#2795]
I would bet [1.2.3](https://github.com/conan-io/conan/releases/tag/1.2.3) and [1.2.2](https://github.com/conan-io/conan/releases/tag/1.2.2) were both released in 201**8** not 201**7**.

(Thanks for working on conan, I know it for a few hours now and I'm having fun with it!)

- - -

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md): *yes*

- [x] I've specified the Conan version, operating system version and any tool that can be relevant: *no because it's not relevant*

- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion: *yeah no steps actually*

**Comment by lasote** [comment]
Thanks for reporting! It is already fixed.
