### ISSUE TITLE
Different behaviour with CMake helper and stdlib in gcc 5.4

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#2796]
Hey,

I have a interesting problem with the CMake helper and stdlib.

I have a project which i build with conan. I have a normal test_package folder with a simple cmake based test example. I have a class with std::string as a member, which crash in the test method of the test_package. Now i find out that my test_package project has a different setting for stdlib, more precise the `_GLIBCXX_USE_CXX11_ABI` variable is set in my test_package project, but it is not set in my normal project. Both use the same helper class (different instance). Both has the default setting `self.compiler.libcxx=libstdc++`. The command_line of both instances of CMake classes are identical, with the exception of `CMAKE_INSTALL_PREFIX` and `BUILD_SHARED_LIBS=ON` in my normal project.

I expect that the behaviour has to be the same in the project as in test_package, because non of the use the `CONAN_LIBCXX`, so what could be wrong?

My second question is: What's the best practice for stdlib settings and conan?

Greetings  
Tonka

**Comment by jamezmoran** [comment]
I believe self.compiler.libcxx=libstdc++ will force the use of the old ABI, not C++11. Try setting it to libstdc++11.

**Comment by tonka3000** [comment]
Hey @memsharded ,

I think i found the problem but i have not enough time to check it (hopefully i can check it at the end of the coming week).  
I think my problem is easy to "solve". I use cmake-conan in this project. I optimized my dependencies in this way. I only call cmake_conan_run only when i need gtest (cmake_make_variable which is off be default), and so it should be easy to say the conanfile.py does not run in the conan create procedure because i build it without tests and so conanfile.py is never called. I've search the conan source if I can find the ABI switch, but i totally forget that this is part of `conanbuildinfo.cmake` => so no conan run no variables from the `conanbuildinfo.cmake`  and I think that's my fault. The test_package always run conan, so the variable is always set.

I think my solution is to set enable test in conan build and never build it 😄

**Comment by tonka3000** [comment]
Hey @memsharded ,

i've checked it. It's like i thought. I've just did not run conanfile.py from cmake in standard case. My fix is that i just use the test, but i don't build it.

So i think you can close this issue.

**Comment by memsharded** [comment]
Cool, thanks!
