### ISSUE TITLE
CMake helper requires vcvars for generators besides Visual Studio (Ninja, NMake)

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#2801]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan version 1.2.3

using CMake build helper with generator like Ninja or NMake Makefiles requires explicit codes to add vcvars, which is annoying:

```
    def build(self):
        if self.settings.compiler == 'Visual Studio':
            with tools.vcvars(self.settings, force=True, filter_known_paths=False):
                self.build_cmake()
        else:
            self.build_cmake()

    def build_cmake(self):
        cmake = CMake(self)
        cmake.definitions['WITH_LIBSODIUM'] = self.options['zmq'].encryption == 'libsodium'
        cmake.configure()
        cmake.build()
```

same is needed even for test_package, if ninja_installer is used in profile as build requirement

it would be nice to automatically set up vcvars, if needed

**Comment by danimtb** [comment]
This was solved in PR #2803 and released in 1.4
