### ISSUE TITLE
Install from multiple remotes per `self.requires()` basis.

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#2805]
Conan --version 1.2.3

How can I specify in the `conanfile.py` or in the `conan install` when part the requirements for a consumer is a package from one remote (Artifactory repo) and a package from another remote (Artifactory repo)?

**Example**

Appl. consumes `libA`, `libB` and `libC`. 

`libA`, `libB` and `libC` resides in Artifactory repo `Conan-release` and in Artifactory repo `Conan-dev`.

The Appl. should consume `libA` and `libB` from Artifactory repo `Conan-release` and `libC` from Artifactory repo `Conan-dev`.

Now in the `conan install` I can specify `-r` for `Conan-release`, but that also pulls in `libC` from here. When I also try a  `conan install` with `-r` for `Conan-dev` then `libA` and `libB` are also pulled from here.

I currently see no way to specify remotes in the `requirements()` method `self.requires()`. Is there a way to put a check for remote in a conditional around `self.requires()`?

**Comment by memsharded** [comment]
I think this might be a duplicated of: https://github.com/conan-io/conan/issues/2091

Please check it, and close if really a duplicate. Thanks!

**Comment by Twoflower2** [comment]
`conan remote` + options will resolve this.
