### ISSUE TITLE
CMake.test() crashes when running using conan build/create, succeeds when virtualrunenv is activated.

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#2814]
I'm running into some trouble while trying to call CMake.test() from within build(). The toolkit I'm trying to test links against some shared libraries which are also in conan, and when I run 'conan build' with the virtualrunenv activated, the tests run fine and succeed. However, when I deactivate the virtualrunenv, the tests crash, presumably because it doesn't know where to find the shared libraries. I'm using GTest and gtest_add_tests() to add my tests to the CMake build:

	(conanrunenv)>conan build .. -sf ../.. -bf .
	...
						1/13 Test  #1: TransmissionFixture.TestBadJsonContent .........   Passed    0.04 sec
								 Start  2: TransmissionFixture.Test400Result
						2/13 Test  #2: TransmissionFixture.Test400Result ..............   Passed    0.04 sec
								 Start  3: TransmissionFixture.Test200Result
	Build succeeded.
			0 Warning(s)
			0 Error(s)

	Time Elapsed 00:00:05.41

	(conanrunenv)>.\deactivate_run.bat
	>conan build .. -sf ../.. -bf .
	...
								 Start  1: TransmissionFixture.TestBadJsonContent
						1/13 Test  #1: TransmissionFixture.TestBadJsonContent .........***Exception: Other  0.01 sec
								 Start  2: TransmissionFixture.Test400Result
						2/13 Test  #2: TransmissionFixture.Test400Result ..............***Exception: Other  0.01 sec
								 Start  3: TransmissionFixture.Test200Result

			0 Warning(s)
			1 Error(s)

	Time Elapsed 00:00:00.42
	ERROR: MetricsConnector/1.0.0@PROJECT: Error in build() method, line 32
					cmake.test()
					ConanException: Error 1 while executing cmake --build C:\Users\James\Documents\projects\metricsconnectorcpp\build --config Debug --target RUN_TESTS -- /m:8

It's my understanding that conan should be able to set up the environment so that executables called within CMake called from the CMake build helper are able to find the libraries they need. Right now, I'm not sure it's possible to run my tests as part of the build because of this, unless of course I'm doing something wrong.

**Comment by memsharded** [comment]
I think that by default, conan doesn't add binary dirs to the PATH while running the ``build()`` method. This is the reason why it works when you are using the virtualenv.
The approach would be to be explicit about your intentions in your recipe, if you need something from your dependencies, you can typically:
- Use the ``imports()`` method to do a local copy of the files you want from your dependencies
- Use a RunEnvironment in code to set the paths up:

```python
    def build(self):
        env_build = RunEnvironment(self)
        with tools.environment_append(env_build.vars):
            cmake = CMake(self)
            cmake.configure()
            cmake.build()
```

More info in http://docs.conan.io/en/latest/reference/build_helpers/run_environment.html

Please try that. Thanks!

**Comment by jamezmoran** [comment]
That seemed to do the trick, thanks!
