### ISSUE TITLE
Are there packages for SDL2/2.0.4?

### ISSUE THREAD

**Issue by jmmut** [conan-io/conan#282]
Hello guys, 

## Context
 I was trying to make a package for sdl2_mixer (taking as example the sdl_image one), which I have already working in linux, and trying it for windows I tried to avoid compilation of the dependency SDL2, using the prebuilt packages for SDL2/2.0.4@lasote/stable.

## Problem
Conan client reports that no packages were found. Now I want to know what packages are there, but it seems that in the [search list](https://www.conan.io/search?q=sdl2%2F2.0.4) there are 44 or 22 packages, but once I enter, the [packages tab](https://www.conan.io/#/source/sdl2/2.0.4/lasote/stable) is empty.

## Questions
Is this expected? Are those packages unavailable at the moment? Is there any difference between sdl2/2.0.4@lasote/stable and SDL2/2.0.4@lasote/stable?

**Comment by memsharded** [comment]
This might be a bug, or at least a problem with the package case, as there are two packages "SDL2" and "sdl2". Also a problem with the package counter, maybe @lasote may have a look at it.

I also remember, it could happen that SDL2, as it is very system-dependent had some problem with the pre-built binaries? Have you tried building from source (``--build=SDL``)? Did you have any problem?

**Comment by jmmut** [comment]
Thanks for the speed answering :) As a clarification, I was just informing about the web issue: the discrepancy between the pages that say which prebuilt packages are available. 

I wanted to avoid the SDL compilation because I am currently setting up my compilation environment on windows. Eventually I will be able to build SDL from sources, so, it's not really a problem for me. At the moment, the conan client seems to download the sources just fine.

BTW, I think the next commands may show better the discrepancy. regarding sdl2.0.4, the client says that there are no packages, but the [search list](https://www.conan.io/search?q=sdl2%2F2.0.4) initially says that there are 22. Regarding sdl2.0.3, the client says that there are several packages, for linux, windows and mac, but the ["packages" tab](https://conan.io/source/SDL2/2.0.3/lasote/stable) says only mac.


```
$ conan search "SDL2/2.0.4@lasote/stable" --remote conan.io -v
Existing packages info:

SDL2/2.0.4@lasote/stable
    There are no packages
```

```
$ conan search "SDL2/2.0.3@lasote/stable" --remote conan.io -v
Existing packages info:

SDL2/2.0.3@lasote/stable
    Package_ID: 3eb28fce57d471e0e6303fc466d7acec702e8020
            (x86, Debug, Visual Studio, MT, 12, Windows)
    Package_ID: 0a205935e7b01cdf6c6e036b4cb5662052b2d669
            (x86, Debug, Visual Studio, MT, 12, Windows)
    Package_ID: bf67c74bed5e4342407714395ea17d8bbb939897
            (x86_64, Debug, Visual Studio, MT, 12, Windows)
    Package_ID: 11c1ba293569c44f22e4cb85361aa921c4c8f5ed
            (x86_64, Debug, Visual Studio, MT, 12, Windows)
    Package_ID: e503c883817b97f1c7d4cf2fdbdc90523ced7743
            (x86_64, Debug, apple-clang, 7.0, Macos)
    Package_ID: 08a32d58147e319b2052e40dee591a983253536c
            (x86, Debug, gcc, 4.9, Linux)
    Package_ID: 15cf71dd0a958f4b330128b207351fcfd9ae304f
            (x86, Release, Visual Studio, MT, 12, Windows)
    Package_ID: 9cf83afd07b678d38a9c1645f605875400847ff3
            (x86_64, Release, gcc, 4.9, Linux)
    Package_ID: a772cc368ce002867f34536a4d0729ed411d167f
            (x86_64, Release, apple-clang, 7.0, Macos)
    Package_ID: bfdae8f555e55e118003bdf460e0fe202f2a72a3
            (x86_64, Release, Visual Studio, MT, 12, Windows)
    Package_ID: 81b5c395d0816a5b69fdd4fd10c02c27a4be2f8d
            (x86, Debug, apple-clang, 7.0, Macos)
    Package_ID: d644d41b2cd514e49995e25fa34422be7fd3854d
            (x86, Release, gcc, 4.9, Linux)
    Package_ID: 3ca85915ce57a6607676849c47c2cee02c75209c
            (x86_64, Release, Visual Studio, MT, 12, Windows)
    Package_ID: 0000193ac313953e78a4f8e82528100030ca70ee
            (x86_64, Debug, gcc, 4.9, Linux)
    Package_ID: eec1124ecea977d62a6a0b6612f899b3f0382991
            (x86, Release, gcc, 4.9, Linux)
    Package_ID: c6d75a933080ca17eb7f076813e7fb21aaa740f2
            (x86_64, Release, gcc, 4.9, Linux)
    Package_ID: 6c1541978e7dec27cf1e02cdd5aa910f0126b397
            (x86, Release, Visual Studio, MT, 12, Windows)
    Package_ID: a804a16d88447db114941d04e1981fa937e46707
            (x86, Debug, gcc, 4.9, Linux)
    Package_ID: a5a3ee0d558fe87af753d63173b383d1d7d6c852
            (x86_64, Debug, gcc, 4.9, Linux)
    Package_ID: cffb07d5ca358abc6620b6c80f48efd5be803189
            (x86, Release, apple-clang, 7.0, Macos)

```

**Comment by memsharded** [comment]
Yes, this seems to be a bug with the package counters. Thanks for telling!

**Comment by lasote** [comment]
I've fixed a problem with cases in package names in the website, similar package names only different in cases was mixing the packages. 
The package to use: SDL2/2.0.4@lasote/stable
I've removed the sdl2/2.0.4 package. Use the SDL2/2.0.4
