### ISSUE TITLE
Use MSVC preview versions

### ISSUE THREAD

**Issue by promgamer** [conan-io/conan#2822]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I've tried to use MSVC 2017 Preview, but conan could not detect it successfully. According to [win.py file](https://github.com/conan-io/conan/blob/cf2c3bd2081f4915ee7992e5f85100ee14afe403/conans/client/tools/win.py#L124), vswhere needs prerelease variable True in order to give find preview versions.

**Comment by lasote** [comment]
Could I ask why you need the pre-release?  2017 is more than released, right?
