### ISSUE TITLE
[question] How to specify --install-folder option in conanfile?

### ISSUE THREAD

**Issue by xylosper** [conan-io/conan#2825]
To prevent run conan whenver swithcing debug/release, I'm using different folder to generate build info files and import dlls.

Now, I want to make this behavior default one so anyone who I share my conanfile.py with can take the benefit without tell 'please run conan with these options, blah, blah, blah...'.

I can make dlls imported separately in import() function by checking debug/release mode and setting `dst` parameter differently.
How can I do same thing for build information files?

**Comment by lasote** [comment]
Hi, You could create a shell script.

**Comment by xylosper** [comment]
@lasote Thank you for answer.
I can make a batch file/script of course.
I just wondered how to do it without writing new script.

So you mean that it is not possible within conan, right?

Could you consider this as a feature request then?
I think it's very useful feature.
Without this feature, I have to run `conan install` whenever switch debug/release mode.

Thanks again.

**Comment by lasote** [comment]
Hi, your use case makes perfectly sense, but for other users several folders for several configs not only build type could be needed. I'm not saying that this feature is useless but the benefit compared with a simple python or shell script is very minimal.
Thanks!

**Comment by memsharded** [comment]
> Without this feature, I have to run conan install whenever switch debug/release mode.

Not sure if I understood the original issue, and this comment. If you are using different folders for your debug and release builds, then running one conan install per configuration is enough:

```bash
$ mkdir build_debug && cd build_debug && conan install .. -s build_type=Debug
$ cd ..
$ mkdir build_release && cd build_release && conan install .. -s build_type=Release
```
Then you switch folders for your debug and release builds. Of course this depends on the environment, if the build system is single-config or multi-config, etc.
