### ISSUE TITLE
Python3 being used for unknown reason

### ISSUE THREAD

**Issue by villasv** [conan-io/conan#283]
I have both python 2 and 3 installed on my Ubuntu. The command `python` points to python 2.7.6.

Still, when using `conan export` I get `SyntaxError: Missing parentheses in call to 'print'` error raised by `"/usr/lib/python3.4/imp.py"`.

I can't find a reason for conan to use python 3 in my configurations.

**Comment by memsharded** [comment]
Hi Victor,
Thanks for telling. How did you install conan, from apt, or did you install it with ``sudo pip install conan``?
If using python and pip, are you using virtualenvs? Highly recommended to avoid problems, I would suggest virtualenvwrapper.

**Comment by villasv** [comment]
Installed with `pip`, but not using virtualenvs.

**Comment by memsharded** [comment]
It could be a bug, indeed. While we find time to have a look, I strongly suggest using virtualenvs, especially virtualenvwrapper. It is really simple and it is something that really makes easier serious development when python is involved. Thanks!

**Comment by villasv** [comment]
I realized that although python was pointing to python2, pip was pointing to pip3.
I unintalled from pip3 and installed with pip2, then it worked. Now I guess the reason is known...

**Comment by memsharded** [comment]
Cool! Perfect then. Could the issue be closed then?

**Comment by villasv** [comment]
Sure, hope the next lost soul that install it with pip3 by mistake finds this.

**Comment by memsharded** [comment]
Lets make it easier for lost souls :)
I have added a note in the install docs: http://docs.conan.io/en/latest/installation.html#install-with-pip
