### ISSUE TITLE
Symbolic links to directories are not properly copied during packaging

### ISSUE THREAD

**Issue by T1T4N** [conan-io/conan#2832]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hello,

I encountered an interesting error while building Qt as a framework on macOS.
As frameworks can actually contain different version of the library, it is common to have symlinks inside the bundle pointing to the "Current" version and the respective headers, resources, etc.

After my test package failed, I did some digging and it turned out that the ```self.copy``` called inside the ```package``` method is ignoring some symlinks.

I managed to create a test recipe to reproduce the issue.
```python
import os
from conans import ConanFile, CMake, tools


class SymlinkBugTestConan(ConanFile):
    name = "symlink-bug-test"
    version = "0.1.0"
    license = "<Put the package license here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of Symlinkbugtest here>"

    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    prefix_folder = 'dist'

    def build(self):
        self.run('mkdir "%s"' % self.prefix_folder)
        self.run('mkdir "%s"' % os.path.join(self.prefix_folder, 'QtCore.framework'))
        self.run('mkdir "%s"' % os.path.join(self.prefix_folder, 'QtCore.framework', 'Versions'))
        self.run('mkdir "%s"' % os.path.join(self.prefix_folder, 'QtCore.framework', 'Versions', '5'))
        self.run('mkdir "%s"' % os.path.join(self.prefix_folder, 'QtCore.framework', 'Versions', '5', 'Headers'))
        self.run('mkdir "%s"' % os.path.join(self.prefix_folder, 'QtCore.framework', 'Versions', '5', 'Resources'))

        self.run('touch "%s"' % os.path.join(self.prefix_folder, 'QtCore.framework', 'Versions', '5', 'Headers', 'a'))
        self.run('touch "%s"' % os.path.join(self.prefix_folder, 'QtCore.framework', 'Versions', '5', 'Resources', 'a'))
        self.run('touch "%s"' % os.path.join(self.prefix_folder, 'QtCore.framework', 'Versions', '5', 'QtCore'))

        self.run('ln -s "%s" "%s"' % (
            '5',
            os.path.join(self.prefix_folder, 'QtCore.framework', 'Versions', 'Current')))

        self.run('ln -s "%s" "%s"' % (
            os.path.join('Versions', 'Current', 'Headers'),
            os.path.join(self.prefix_folder, 'QtCore.framework', 'Headers')))

        self.run('ln -s "%s" "%s"' % (
            os.path.join('Versions', 'Current', 'QtCore'),
            os.path.join(self.prefix_folder, 'QtCore.framework', 'QtCore')))

        self.run('ln -s "%s" "%s"' % (
            os.path.join('Versions', 'Current', 'Resources'),
            os.path.join(self.prefix_folder, 'QtCore.framework', 'Resources')))

    def package(self):
        self.copy("*", dst="", src=self.prefix_folder,
                  symlinks=True)
```

Listing the build output contains the correct symlinks:
```
tree $CONAN_USER_HOME/.conan/data/symlink-bug-test/0.1.0/user/testing/build/<package-id>/dist/QtCore.framework
$CONAN_USER_HOME/.conan/data/symlink-bug-test/0.1.0/user/testing/build/<package-id>/dist/QtCore.framework
├── Headers -> Versions/Current/Headers
├── QtCore -> Versions/Current/QtCore
├── Resources -> Versions/Current/Resources
└── Versions
    ├── 5
    │   ├── Headers
    │   │   └── a
    │   ├── QtCore
    │   └── Resources
    │       └── a
    └── Current -> 5

7 directories, 4 files
```

Now, when I list the output package, there is a symlink missing:
```
tree $CONAN_USER_HOME/.conan/data/symlink-bug-test/0.1.0/user/testing/package/<package-id>/QtCore.framework/
$CONAN_USER_HOME/.conan/data/symlink-bug-test/0.1.0/user/testing/package/<package-id>/QtCore.framework/
├── Headers -> Versions/Current/Headers
├── QtCore -> Versions/Current/QtCore
└── Versions
    ├── 5
    │   ├── Headers
    │   │   └── a
    │   ├── QtCore
    │   └── Resources
    │       └── a
    └── Current -> 5

6 directories, 4 files
```

I could not determine an exact pattern by which specific symlinks are skipped, since my build host actually skipped the ```Headers``` directory, while my development machine (when running this recipe) skips the ```Resources``` directory.

I managed to find a temporary workaround for the issue, by using:
```
from distutils.dir_util import copy_tree
copy_tree(os.path.join(self.build_folder, self.prefix_folder),
          os.path.join(self.package_folder),
          preserve_symlinks=True)
```

As I've had issues with ```os.walk``` in the past, I suspect that the error might be in the ```_filter_files``` function of ```file_copier.py```.

In any case, it would be extremely useful if an additional function to copy whole directory trees without patterns is implemented.

Software information:
I'm currently using Conan ```version 1.2.3``` on
```
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199
```
with
```
Xcode 9.3
Build version 9E145
```
and ```Python 3.6.5``` installed from brew

**Comment by memsharded** [comment]
This is interesting. Tried to reproduce in Ubuntu, but seems to work fine, output of package:

```bash
└── QtCore.framework
    ├── Headers -> Versions/Current/Headers
    ├── QtCore -> Versions/Current/QtCore
    ├── Resources -> Versions/Current/Resources
    └── Versions
        ├── 5
        │   ├── Headers
        │   │   └── a
        │   ├── QtCore
        │   └── Resources
        │       └── a
        └── Current -> 5
```

**Comment by T1T4N** [comment]
@memsharded this sure is interesting because I'm able to reproduce the issue on these clean VMs:
- ```Mac OS X 10.10.5 (14F2511)``` with Python ```3.6.5``` installed from brew
    - Both folder symlinks (Headers, Resources) are not present in the package
- ```Manjaro 17``` with Python ```3.6.2```
    - Only the Resources symlink is not present

**Comment by T1T4N** [comment]
Hello @memsharded,

I think I managed to pinpoint the cause for this bug.
After debugging conan for some time, I came to the conclusion that ```_filter_files``` is actually correct.
It's output, ```file_copier.py:80``` in my case is:
```
----------LINK FOLDERS
['QtCore.framework/Resources', 'QtCore.framework/Versions/Current', 'QtCore.framework/Headers']
```

The issue occurs in the ```_link_folders``` method, specifically the if statement that checks if the ```dest_dir``` exists: ```            if os.path.exists(os.path.join(dst, dest_dir)):```

This is the case because because the list item that is currently being processed, in this case ```QtCore.framework/Resources``` depends on a link that was not yet processed, ```QtCore.framework/Versions/Current```, so the ```exists``` check returns false, and there is no ```else``` to handle this case.

If I just switch the places of the list items before passing them to the ```_link_folders``` method,
```link_folders[0], link_folders[1] = link_folders[1], link_folders[0]```, then everything is correctly executed.

I can only speculate as to why you weren't able to reproduce it on Ubuntu, but my best bet is that the traversal order of ```os.walk``` used in ```_filter_files``` might be platform specific.

**Comment by memsharded** [comment]
Thanks very much for such debugging effort. 

You are totally right, the differences between systems were becuase of the traversal order.

I have submitted a PR to fix it in: https://github.com/conan-io/conan/pull/2869. If you want to try to run from sources from my branch, that could help a lot too. Thanks again, you really spotted and solved the issue.

**Comment by memsharded** [comment]
Sorry @T1T4N better wait a bit, the PR is broken, I am on it.
