### ISSUE TITLE
Add import-folder option to conan install command

### ISSUE THREAD

**Issue by reiver-dev** [conan-io/conan#2837]
Currently i am doing `conan install --no-imports && conan imports` chain to specify separate directories for generated build system files and package binaries. It would be good, if it was possible to specify imports folder during conan install.

Why: 
Different configurations require different import folders (example: cmake_multi)

conan version: 1.3

```
def install(...):
    ...
    if not no_imports:
        run_imports(conanfile, install_folder, output)
```
```
def imports(...):
    ...
    run_imports(conanfile, dest_folder, output)
```

**Comment by memsharded** [comment]
There is already the ``--install-folder``, which is the folder used for imports too. But yes, if you are using ``cmake_multi``, then it could make sense. Lets have a look and implement this if possible.

It should probably apply to ``deploy()`` too, not only imports.

**Comment by memsharded** [comment]
``imports`` have been removed in 2.0, this no longer applies
