### ISSUE TITLE
JFrog Artifactory C++ CE License link broken

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2838]
I know this doesn't belong in the Conan issue tracker, but I've tried emailing JFrog twice and have not received any response. I need be able to read the terms of the license for the new CE version of Artifactory to determine if we can use it on our team, but the link on this page is broken: https://bintray.com/jfrog/product/JFrog-Artifactory-Cpp-CE/view

Can you please forward this to the appropriate people, and have them notify me when the link is fixed?

**Comment by memsharded** [comment]
Thanks for reporting!

Sure, we will forward this and follow so this is fixed.

**Comment by DavidZemon** [comment]
Much appreciated!

**Comment by memsharded** [comment]
Hi @DavidZemon 

The link in https://bintray.com/jfrog/product/JFrog-Artifactory-Cpp-CE/view should be fixed now, and direct to https://jfrog.com/artifactory-community-edition-c-c-eula/ (there was a typo in the link!)

Cheers!
