### ISSUE TITLE
Conan not escaping quotes in bash bath with self.run(...,win_bash=True)

### ISSUE THREAD

**Issue by yeswalrus** [conan-io/conan#2839]
Using conan 1.3.0 on windows 10 with Git for Windows 2.17.0 installed to the default location "C:/Program Files/Git/bin/bash.exe", the conan build step fails. Output is below:
```
$ conan build . --source-folder=tmp/source --install-folder=tmp/install --build-folder=tmp/build
Project: Running build()
Project: run_in_windows_bash: "C:/Program Files/Git/bin/bash" --login -c ^"cd \^"/c/dev/external-libraries/conan/libusb/tmp/build\^" ^&^& ls ^"
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
ERROR: libusb/1.0.0@PROJECT: Error in build() method, line 21
        self.run("ls", win_bash=True)
        ConanException: Error 1 while executing "C:/Program Files/Git/bin/bash" --login -c ^"cd \^"/c/dev/external-libraries/conan/libusb/tmp/build\^" ^&^& ls ^"
```

My current conanfile.py follows:
```
from conans import ConanFile, AutoToolsBuildEnvironment, tools

class LibusbConan(ConanFile):
    name = "libusb"
    version = "1.0.0"
    license = "LGPL 2.1"
    url = "git@github.com:leapmotion/libusb.git"
    description = "<Description of Libusb here>"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=True"
    generators = "cmake"

    def source(self):
        self.run("git clone git@github.com:leapmotion/libusb.git")
        self.run("cd libusb && git checkout fix-soname-0")

    def build(self):
        autotools = AutoToolsBuildEnvironment(self, win_bash=True)
        self.run("ls", win_bash=True)
        autotools.configure(args=["--disable-udev"])
        autotools.make()

    def package(self):
        self.copy("*.h", dst="include", src="hello")
        self.copy("*hello.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["hello"]

```

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I have checked this, and it seems it is not a problem of the quotes, but due to the command not being ran with ``shell=True``. It is because the underlying call is ``os.system``:
- ``run_in_windows_bash`` calls ``conanfile.run(win_bash=False)``
- ``conanfile.run()`` calls ``ConanRunner`` which ends in a ``_simple_os_call``=> ``os.system``. 
- Replacing with a Popen with shell=True seems to be fixed

This doesn't seem a regression, but a pre-existing bug. Need to revise this with @lasote to see how to fix it. 

Thanks very much for your detailed report and reproducible case!

**Comment by yeswalrus** [comment]
Thanks for handling this so quickly!

**Comment by memsharded** [comment]
No problem, glad to help, thanks to you for the good reports and the feedback, keep it coming :)
