### ISSUE TITLE
Incomplete documentation for ConanFile

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#284]
I tried to find out what optional parameters (if any) were available for the `self.copy()` method of `ConanFile`, and found nothing, not even in the source code file `conan_file.py`. I don't know much Python at all, but it seems that `ConanFile` neither inherits nor defines that method, so it's probably injected in a further derivation done by the `conan` main script. It would be nice to have full documentation on what can be done inside your `conanfile.py`.

**Comment by memsharded** [comment]
Conanfile copy is assigned at runtime, so it actually changes between the ``package()`` and the ``imports()`` method. I will give you a summary here:

```python
self.copy(pattern, dst, src, keep_path=False)
````

- ``pattern`` is a pattern following fnmatch syntax of the files you want to copy, from the *build* to the *package* folders. Typically something like ``*.lib`` or ``*.h``
- ``dst`` is the destination folder in the package. They will typically be ``include`` for headers, ``lib`` for libraries and so on, though you can use any convention you like
- ``src`` is the folder where you want to search the files in the *build* folder. If you know that your libraries when you build your package will be in *build/lib*, you will typically use ``build/lib`` in this parameter. Leaving it empty means the root build folder.
- ``keep_path``, with default value=True, means if you want to keep the relative path when you copy the files from the source(build) to the destination(package). Typically headers, you keep the relative path, so if the header is in *build/include/mylib/path/header.h*, you write:
```python
self.copy("*.h", "include", "build/include") #keep_path default is True
```
so the final path in the package will be: ``include/mylib/path/header.h``, and as the *include* is usually added to the path, the includes will be in the form: ``#include "mylib/path/header.h" which is something desired

``keep_path=False`` is something typically desired for libraries, both static and dynamic. Some compilers as MSVC, put them in paths as *Debug/x64/MyLib/Mylib.lib*. Using this option, we could write:

```python
self.copy("*.lib", "lib", "", keep_path=False)
```
And it will copy the lib to the package folder *lib/Mylib.lib*, which can be linked easily

**Comment by memsharded** [comment]
You were totally right, it was not explained in the docs. I have just added a copy of this documentation here: http://docs.conan.io/en/latest/reference/conanfile.html#packaging

Thanks for pointing this out! Don't be afraid to ask, not knowing python should't be an issue, just ask and we'll try to help. If the explanation above is enough, please don't forget to close the issue.

Thanks very much again, cheers!

**Comment by JPGygax68** [comment]
Thanks for the quick and extensive answer (and for updating the docs on top of that)!
Just to clarify: the `build` directory is the root source for the "package" step, but what exactly happens in the "imports" step? Will the copy commands be applied identically to *each* imported package ? What would the source directory be in that case - `build`, `export`, or `package/<sha...>`?

**Comment by memsharded** [comment]
The imports step is from the *package/sha* directory to the *user project* directory. It is intended to copy things as shared libs or data from the packages to the user project, and to avoid messing with the system path in order to execute a binary that loads some shared libraries. Note that the import is located in the project that receives the files, that is, typically the *user project*. 

Yes, the copy commands are apply identically to all dependencies, so if your project depends on package A and B, doing a:

```python
def imports(self):
     self.copy("*.dll", "bin", "bin")
```

will copy all dlls from both A and B packages. If something finer is needed, you may use the patterns. Though we are considering improving this imports(), mainly due to performance reasons, see #245

**Comment by JPGygax68** [comment]
Thanks again!

**Comment by memsharded** [comment]
Thanks to you for reporting this missing info in the docs!

**Comment by JPGygax68** [comment]
Just noticed something: I think the example you've given above for `self.copy()` from the `build` directory is wrong. If I understand things correctly, when in the `package` step, the root source directory already is the  `build/<sha..>` directory - am I wrong ?

**Comment by memsharded** [comment]
Nop, I was referring to a *build* folder inside the *buid/<sha>* one. So in disk you would have:
``.../Package/version/user/channel/build/sha/`` which is the reference "package build folder", managed by conan.
And inside that folder, others subfolders as cmake, src, ... and one **build** folder, when the actual library building is done, because the conanfile recipe told that, with something like "mkdir build && cd build"

**Comment by JPGygax68** [comment]
Ah - I get it now, thanks! I didn't think of that because the example in the docs does not do an out-of-source build.
Also, is command chaining portable (`mkdir build && cd build`) ?

**Comment by memsharded** [comment]
As the package ``build()`` already creates the ``build/<sha>`` folder which is also very temporary, it doesn't matter too much to clutter the directory with the build stuff. I sometimes do out-of-source, it is easier when you git clone a repository, so you make the build folder at top level, and it becomes a sibling of the source-cloned folder.

Yes, command chaining with && is pretty portable, at least in Win, Linux, Mac. Some commands of course might not, as ``rm -rf```. I'd recommend **cmder** for Win, it has such nix commands, resizable and zoomable, works pretty well, if you haven´t checked it, I`d give it a try.

**Comment by smasihemami** [comment]
for others out there looking for a new link that works: https://docs.conan.io/en/latest/reference/conanfile/methods.html?highlight=copy
