### ISSUE TITLE
1.3 regression: AutoToolsBuildEnvironment now aborts on self-defined architectures

### ISSUE THREAD

**Issue by tru** [conan-io/conan#2840]
With 1.3 our AutoTools packages started to fail on architectures that we define ourselves in settings.yml, these includes: `aarch64`, `armv7hf-sysv` etc. The error message we get is:

`conans.errors.ConanException: Unknown 'armv7hf-sysv' machine. Conan doesn't know how to translate it to the GNU triplet, please report at https://github.com/conan-io/conan/issues`

This is a breaking change and while the warning is probably good it breaks our current packages without changes to conan. Ideally this warning should be not an error but a warning to not break current packages and maybe make it configurable in the future.

**Comment by lasote** [comment]
Understood, you are right. Tomorrow we will release 1.3.1.
