### ISSUE TITLE
1.3.0 regression: tools.save doesn't have "append" parameter

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#2841]
For no obvious reason `conans.util.files.save` method was split into 2 methods: `save` and `save_append` with former not having `append` parameter and latter not being exported from `tools`.

Since `tools.save` is in [the documentation](http://docs.conan.io/en/latest/reference/tools.html#tools-save) I consider it as a public API and suggest restore previous behavior.

**Comment by lasote** [comment]
We will solve and release asap. Probably tomorrow. Thanks for reporting
