### ISSUE TITLE
MSBuild build helper always overrides runtime library field

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#2848]
Affects Conan 1.2.x on Windows/MSVC. (pretty sure previous versions behaved slightly differently)

- Recipe for a library that still uses .sln / .vcxproj files rather than CMake generated ones
- Recipe builds both Debug and Release in the same package (`build_type` is not a setting on windows)
- vcxproj files specify different `<RuntimeLibrary>` for Debug and Release configurations
- conan default profile specifies `MD` as the desired compiler runtime
- `build()` method uses the MSBuild build helper

When building the recipe with `conan create` and conan 1.2.0, I observed that `/MD` was being passed to both Release *and* Debug configurations, which is undesired (do not want a Debug library linked with `/MD`, as that will not link with my projects). 

In light of this, I proceded to remove the compiler runtime as a setting:
`self.settings.compiler.remove("runtime")` in the `configure()` method.

Which caused the libraries to be built with a completely different runtime altogether (`/MT`). 

I believe the issue is in the function `_get_props_file_contents()` in the MSBuild build helper. By the looks of it, if `compiler.runtime` is empty, the value in the custom .props file gets initialised to an empty string (and in that case, I think MSBuild decides ?).

I was able to work around this by calling `msbuild.get_command()` (which allows me to bypass the .props file) and then calling the command using `VisualStudioBuildEnvironment` . Kudos for the functionality :)  (The one thing that I couldn't really work out was why MSBuild was warning me that the compiler runtime flag was being overridden when technically it shouldn't have been at this point. However it was being built with the correct values).

**Comment by lasote** [comment]
Hi, I opened https://github.com/conan-io/conan/pull/2849 with an improvement to the build helper to only generate the XML nodes when a runtime or flags are specified. I can't find information about what is `msbuild` doing in case you specify an empty string. 

I don't know if you are able to run conan from sources to try that and see if it helps. We could assist.

Thanks for reporting.
