### ISSUE TITLE
Packaging external source

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#285]
I tried to create a package for an external project (`USCiLab/cereal`), but I find that I cannot get the "source" step to execute:
```python
  def source(self):
    self.run("git clone https://github.com/USCiLab/cereal.git")
```
Am I missing something obvious ?

**Comment by memsharded** [comment]
So the first step would be to check the package recipe inside the local conan storage, so it can be consumed from there. Did you miss it? Try:

```bash
$ conan export jpgygax/testing
$ conan install MyLib/0.1@jpgygax/testing --build
```
The second step is instructing to install the package, building the package binary from the recipe you have created.

I assume that in your conanfile there are attributes named ``name=MyLib`` and ``version=0.1``

For package creators, it is typically much more convenient to have a test project to consume the package that is being created, and check that everything works fine. This can be also done more automatically with the help of the ``conan test_package`` command.

**Comment by JPGygax68** [comment]
Thanks! What I missed was that I need a consumer project to get the download started. I had assumed that the "build" command would do that, but it doesn't do anything when no build step has been defined. Perhaps a "fetch" command would be helpful to package developers? I haven't tried `test_package` yet, will probably get to it soon.

**Comment by memsharded** [comment]
The ``conan install`` command, providing a reference, would do it. You don't need a consumer package in that case. To summarize, there are 2 ways to reference/fetch/install/build a package, 1) directly with its reference (full name + version + user + channel) or 2) via a consumer project with a conanfile that requires it

```bash
$ conan install MyLib/0.1@jpgygax/testing --build  # No consumer project,
$ conan install . --build # consumer project with conanfile in current dir
```

Great, please ask if you have any question about the ``test_package``

**Comment by JPGygax68** [comment]
I just implemented a `test_package` for [my wrapper for the `cereal` library](https://github.com/JPGygax68/ConanCereal); it appears to work ok.  Just two things:

- My first attempt to execute `conan test_package` failed with `WindowsError: [Error 145] The directory is not empty ...` - it worked after I removed the package from the cache

- I also tried to upload my wrapper to `conan.io`, but that failed with a 502: Bad Gateway

**Comment by memsharded** [comment]
About the first issue, it is right, win is sometimes picky about deleting things that are used, and sometimes handles to the files keep open, so need to retry a few times, or even delete by hand. Make sure that no folders or files are open in editors or explorers, and if it happens again please tell.

The second issue, it seems that we are having some misbehaviour in the the load balancer we recently introduced to scale out conan (http://blog.conan.io/2016/05/23/Scaling-out-conan.io.html). It has also been reported in #286, sorry for the inconvenience, we are on it, thanks very much for telling.

**Comment by memsharded** [comment]
The service should work now. Still don't know the issue, but should be working, and you should be able to upload. But please tell otherwise, thanks!
