### ISSUE TITLE
An interrupted upload will not re-create an incomplete tarball

### ISSUE THREAD

**Issue by BSipos-RKF** [conan-io/conan#2854]
I'm using conan version 1.2.3 on Windows 10.

A few times I've had to interrupt a "conan upload" operation while it was in a "Compressing package..." step. When interrupted with Ctrl+C from the terminal, the operation leaves behind a partly-assembled tarball (i.e. the tarball does not yet have all of the package's files). The next time a "conan upload" on that same package is attempted, it appears to attempt to re-use the incomplete tarball and when I look at the package contents on the associated (Artifactory) repository I see that it's missing many files from the built package (on the build host's local cache).

An interrupted upload command should not leave an incomplete compressed source/package tarball behind.

**Comment by memsharded** [comment]
Have you checked the new integrity checks released in 1.3? It seems they
address exactly your case.

Please have a look and tell me. Thanks!

**Comment by memsharded** [comment]
Checking this again, it seems the integrity check doesn't cover interruption of uploads.
This could be fixed capturing Ctrl+C exceptions in ``compress_files()``, but that would still leave out the case when the process is completely killed (-9). 

There exists the ``conan upload --check`` argument, which probably could be extended to check for the tgz integrity.

**Comment by lasote** [comment]
Let's try to improve it for the next release.
