### ISSUE TITLE
Another visual_studio_multi generator use case (related to Issue #2759)

### ISSUE THREAD

**Issue by mworcester** [conan-io/conan#2857]
Question related to:   https://github.com/conan-io/conan/issues/2759

I am just getting started with Conan on a VS2017 project in Windows which involves several native C++ projects utilizing an in-memory database ( ExtremeDB ).    The solutions have multiple configurations for both Debug and Release which differentiates which model of in-memory database is being used.

Configurations are named things like:
    "DebugModel1A, DebugModel1B, DebugModel2A, DebugModel2B, DebugModel3, DebugModel4, ReleaseModel1A, ReleaseModel1B, ReleaseModel2A, ReleaseModel2B, ReleaseModel3, ReleaseModel4".

The visual_studio_multi generator does exactly what I want, except it only works if I forcibly create a "Debug" or "Release" configuration off whichever model is being used ( Example "Debug" based on "DebugModel3" ).    Other developers are balking at having to adjust the configurations manually when switching models just to meet the limitations of the conan tool.

Is there a simple way to be able to feed in something into build_type besides just hard-coded "Debug" and "Release"?

Request:   Allow any configuration name containing "Debug" or "Release" within the name, to specify which configuration name to build while still preserving the debug/release logic for compiling and linking.   In other words, I want it to be able to set the compiler flags correctly based on the build type, but not be completely limited to what name I give it.     Allowing for strings containing "Debug" or "Release" instead of requiring an exact match of name would solve this.

Alternatively, what is involved in creating a visual_studio_multi_better generator that does this?     I am new to conan and don't see an easy path to get there without having to tinker around with a lot of the Conan-provided python files.

I am aware of the settings.yml file and can provide additional valid build_type values in there, but the internal logic would still be compromised without fixing the exact checks against "Debug" and "Release".

**Comment by memsharded** [comment]
The new ``conan.tools.microsoft`` toolchain has improved and addressed this issue. Please check: https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html

- It is multi-config
- It allows custom configurations (https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html#custom-configurations)
- It generates a .props file per dependency, allowing fine grain configuration.

It is still experimental, but will be the integration that will prevail in Conan 2.0, so I think this can be closed.
