### ISSUE TITLE
short_path not behaving as needed for test_package

### ISSUE THREAD

**Issue by Lnk2past** [conan-io/conan#2863]
Windows 7
Visual Studio 2015
Visual Studio 2017

Conan v1.2.3
Conan Package Tools v0.16.5
CMake v3.9.4

I am having trouble with a few packages where when I get into exercising the test_package, I am getting hit with an error dealing with the length of the paths. 

I tried putting ```short_paths = True``` in the package's ```conanfile.py``` as well as the test_package's ```conanfile.py```, but the path that is constructed is still built out from where my recipe is stored. Due to the nature of the project and our VCS, the root path where we build the packages out of is already pretty long, but it has not been an issue since we have been ignoring the test_packages (for better or for worse... we aren't ignoring them now). I figured adding that flag would push all of the processing out to the short_path cache (C:\) but it seems to crash before any moving to ```C:\``` happens.

Is there something else I can try to alleviate the issue? Changing the VCS root isn't really an option at the moment, and would be a fragile work around, as it would only be a matter of time before someone manages to fudge it in our automation.

Thanks in advance!

**Comment by Lnk2past** [comment]
Looking through the source code, it looks like I can specify ```--test-folder=None``` to skip the test, I can try to hack around using this with my builder scripts (from Conan Package Tools) but I am not decided if this is a good solution on my end. I'll keep tinkering around; any suggestions are still very much welcomed.

**Comment by memsharded** [comment]
Hi @Lnk2past !

Yes, the short_paths feature is a feature that works for the conan local cache, to shorten the paths. It doesn't apply at all for test_package. I think the feature you are looking for is ``--test-build-folder``, in which you could define any folder you want, like ``C://mytemp``, for example.

**Comment by Lnk2past** [comment]
Hey @memsharded, thanks! I think I am good to go at this point.
