### ISSUE TITLE
Multiple calls to msbuild.build fail with TypeError

### ISSUE THREAD

**Issue by yeswalrus** [conan-io/conan#2865]
When using MSBuild to attempt to generate a multi-configuration package, the 2nd call to msbuild.build always fails with the following error on Windows 10 and conan 1.3.2:
```
ERROR: libusb/1.0.0@PROJECT: Error in build() method, line 36
        msbuild.build(sln_file, build_type="Debug")
        TypeError: sequence item 4: expected str instance, NoneType found
```
Switching the order of the debug and release calls does not resolve the problem, however reinitializing the msbuild object with msbuild = MSBuild(self) between calls fixes the problem.

My conan file is below:
```
from conans import ConanFile, AutoToolsBuildEnvironment, MSBuild, tools

class LibusbConan(ConanFile):
    name = "libusb"
    version = "1.0.0"
    license = "LGPL 2.1"
    url = "git@github.com:leapmotion/libusb.git"
    description = "<Description of Libusb here>"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=True"
    generators = "cmake"

    def configure(self):
        if self.settings.compiler == "Visual Studio":
            del self.settings.compiler.runtime #tutorial says this is required, but not why
            del self.settings.build_type

    def source(self):
        branch_name="fix-soname-0"

        if self.settings.os == "Windows":
            branch_name="master"

        self.run("git clone --depth 1 git@github.com:leapmotion/libusb.git -b " + branch_name)

    def build(self):
        #no out of source builds
        print(self.source_folder)
        if self.settings.os == "Windows":
            msbuild = MSBuild(self)
            sln_file = "%s/libusb/msvc/libusb_2017.sln" % (self.source_folder)
            msbuild.build(sln_file, build_type="Release")
            msbuild.build(sln_file, build_type="Debug")

    def package(self):
        self.copy("*.h", dst="include", src="libusb")
        self.copy("*hello.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["libusb"]

```

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
Hi @yeswalrus, thanks a lot for reporting. I was able to reproduce your issue and will add a PR to fix it. I would like to ask you some questions/comments:

- I can see you are following a tutorial to create this recipe. Could you please indicate which one?
I am just asking because maybe it is not clearly explained the deletion of `self.settings.compiler.runtime` in `configure()`

- As you want to create a a multi-config package, make sure you are packaging the right binaries into the right folders and the indicating those paths in `package_info()` for consumers. Something like:

```
def package(self):
    self.copy("*.dll", src="x64/Debug/dll", dst="debug/bin")
    self.copy("*.lib", src="x64/Debug/lib", dst="debug/lib")
    self.copy("*.dll", src="x64/Release/dll", dst="release/bin")
    self.copy("*.lib", src="x64/Release/lib", dst="release/lib")

def package_info(self):
    self.cpp_info.libs = ["libusb"]
    if self.settings.build_type == "Debug":
        self.cpp_info.libdirs = ["debug/lib"]
        self.cpp_info.bindirs = ["debug/bin"]
    elif self.settings.build_type == "Release":
        self.cpp_info.libdirs = ["release/lib"]
        self.cpp_info.bindirs = ["release/bin"]
```

Also note that for this case it would be better to delete the build type information in the `package_id()` method instead of in the `configure()`, to have that setting available in the if clauses (as indicated above) of the recipe. Something like:

```
def package_id(self):
    del self.info.settings.build_type
```

**Comment by danimtb** [comment]
I finally found the tutorial you might be following: https://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-package

This approach is totally valid and there you can find the explanations of deleting the `self.settings.compiler.runtime` in `configure()`. Plesae check the **Important** box at the end of that section for more infomration.

Please do not hesitate to ask us any question or doubt you may have and we will be happy to help!
