### ISSUE TITLE
Add GCC 8.1

### ISSUE THREAD

**Issue by leugenea** [conan-io/conan#2872]
Good evening.

Looks like GCC 8.1 was released several days ago. It should be added to `settings.yml`.

**Comment by danimtb** [comment]
Yes, is has been already reported in #2866. We have to add also the new std flag value.

Please follow conversation there if you consider it is a dupplicated issue.
Thanks for reporting!

**Comment by danimtb** [comment]
Thanks for checking @leugenea. Closing this, follow conversation there 😃
