### ISSUE TITLE
Add Manjaro support

### ISSUE THREAD

**Issue by intelligide** [conan-io/conan#2873]
Conan already supports ArchLinux which is linked to pacman. However, conan does not support manjaro which is a popular distribution based on Arch.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
You mean conan cannot run in Manjaro? Maybe there is not a distro installer, but maybe it shouldn't be difficult to run installing it from pip or running source? Have you tried it? Is there some limitation in Manjaro regarding installing pip packages from PyPI? Thanks!

**Comment by intelligide** [comment]
Conan just doesn't recognize manjaro as a distribution with pacman. 

I make a PR #2874
