### ISSUE TITLE
Possible issue with default option propagation behavior

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#2878]
Conan version 1.3.2

I believe that the `conan create` command may have changed behavior regarding default options for dependency, or at the very least I am surprised by it's behavior and think it might be a problem. 

I believe that given the example below, running the `conan create` method on the `highlevel` recipe with no parameters should look for `lowlevel` binary with `shared=False`, despite the fact that the target library has an option called `shared` with a default value of `True`.  However, the current behavior seems to be that Conan assumes the default values of the target package for all it's dependencies.  So, it looks for a precompiled binary for `lowlevel` library with `shared=True`.

I will try to turn this into a full reproduction shortly.

```
class HighLevelLibConan(ConanFile):
    name = 'highlevel'
    version = '0.1.0'
    options = {"shared": [True, False]}
    default_options = "shared=True"
    requires = "lowlevel/0.1.0@demo/testing"
```
```
class LowLevelLibConan(ConanFile):
    name = 'lowlevel'
    version = '0.1.0'
    options = {"shared": [True, False]}
    default_options = "shared=False"
```

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
This seems to pass:

```python
    def test(self):
        # https://github.com/conan-io/conan/issues/2878
        client = TestClient()
        conanfile = """from conans import ConanFile
class LowLevelLibConan(ConanFile):
    options = {"shared": [True, False]}
    default_options = "shared=False"
    def package_info(self):
        assert not self.options.shared
        self.output.info("LOW SHARED: %s" % self.options.shared)
"""

        client.save({"conanfile.py": conanfile})
        client.run("create . lowlevel/0.1@user/testing")
        conanfile = """from conans import ConanFile
class HighLevelLibConan(ConanFile):
    options = {"shared": [True, False]}
    default_options = "shared=True"
    requires = "lowlevel/0.1@user/testing"
    def package_info(self):
        assert self.options.shared
        self.output.info("HIGH SHARED: %s" % self.options.shared)
"""
        client.save({"conanfile.py": conanfile})
        client.run("create . highlevel/0.1@user/testing")
        self.assertIn("lowlevel/0.1@user/testing: LOW SHARED: False", client.out)
        self.assertIn("highlevel/0.1@user/testing: HIGH SHARED: True", client.out)
```

**Comment by solvingj** [comment]
was just testing, might be related to the use of wildcard in the other option.

**Comment by solvingj** [comment]
It seems it was somehow related to a corrupted package:  WARN: Package is corrupted, removing folder.
