### ISSUE TITLE
Question about creating a package that allows only dynamic linking (`shared` option?)

### ISSUE THREAD

**Issue by jmmut** [conan-io/conan#288]
Hello again, I'm making a [package for sdl_mixer](https://bitbucket.org/mutcoll/conan-sdl2-mixer/src/4bb483f43772af668a888f48a9c5e2c6a29d41f4/conanfile.py?fileviewer=file-view-default) for linux and windows (taking as example sdl2_mixer from lasote). A [hello world](https://bitbucket.org/mutcoll/conan-sdl2-mixer-hello-world/overview) already works in linux. For windows I'm trying to avoid making a cmake from scratch, cheating a bit and downloading the [runtime binaries that sdl_mixer distributes in their page](http://www.libsdl.org/projects/SDL_mixer/).

My issue is that (bulding the hello world) in windows the compiler is trying to use the static version of my sdl_mixer, which doesn't exist. So, how do I tell conan to tell visual studio to link against `SDL2_mixer.dll` and not against `SDL2_mixer.lib`?

I did read over the docs, which have solved [other issues](https://stackoverflow.com/questions/37527572/how-to-use-conans-sdl2-in-windows/), but I just can't get over this one.

## Details: 
Below I list some files and logs I think are useful. They are from two repositories: the mixer package, and the hello world testing the package.
- mixer conan package
  - conanfile.py
- mixer test hello world
  - conaninfo
  - commands to build
  - linker error

### conanfile.py from SDL2_mixer
here is my conanfile.py for the mixer package. you can see that I download the binaries, unzip them and move to the package folder, but I don't set any variable, which I guess is what I'm missing:
```
from conans import ConanFile
from conans.tools import download, unzip, replace_in_file
import os
import shutil
from conans import CMake, ConfigureEnvironment
from conans.model.settings import Settings
import copy

class SDLConan(ConanFile):
    name = "SDL2_mixer"
    version = "2.0.1"
    folder = "SDL2_mixer-%s" % version
    settings = "os", "arch", "compiler", "build_type"
    options = {"shared": [True, False]
            #, "fPIC": [True, False]
            }
    default_options = '''shared=True'''
    generators = "cmake"
    url="https://bitbucket.org/mutcoll/conan-sdl2-mixer"
    requires = "SDL2/2.0.4@lasote/stable"
    license="MIT"

    def config(self):
        del self.settings.compiler.libcxx

    def source(self):
        zip_name = "%s.tar.gz" % self.folder
        download("https://www.libsdl.org/projects/SDL_mixer/release/%s" % zip_name, zip_name)
        unzip(zip_name)

    def build(self):
        if self.settings.os == "Windows":
            self.build_copying_libs()
        else:
            self.build_with_make()

    def build_copying_libs(self):
        zip_name = "%s-win32-x64.zip" % self.folder
        download("https://www.libsdl.org/projects/SDL_mixer/release/%s" % zip_name, zip_name)
        unzip(zip_name)

    def build_with_make(self):

        env = ConfigureEnvironment(self.deps_cpp_info, self.settings)
        #if self.options.fPIC:
            #env_line = env.command_line.replace('CFLAGS="', 'CFLAGS="-fPIC ')
        #else:
            #env_line = env.command_line
        env_line = env.command_line.replace('LDFLAGS="', 'LDFLAGS="-Wl,--no-as-needed ')

        custom_vars = 'LIBPNG_LIBS= SDL_LIBS= LIBPNG_CFLAGS='
        sdl2_config_path = os.path.join(self.deps_cpp_info["SDL2"].lib_paths[0], "sdl2-config")

        self.run("cd %s" % self.folder)
        self.run("chmod a+x %s/configure" % self.folder)
        self.run("chmod a+x %s" % sdl2_config_path)

        self.output.warn(env_line)
        if self.settings.os == "Macos": # Fix rpath, we want empty rpaths, just pointing to lib file
            old_str = "-install_name \$rpath/"
            new_str = "-install_name "
            replace_in_file("%s/configure" % self.folder, old_str, new_str)

        #old_str = '#define LOAD_PNG_DYNAMIC "$png_lib"'
        #new_str = ''
        #replace_in_file("%s/configure" % self.folder, old_str, new_str)

        #old_str = '#define LOAD_JPG_DYNAMIC "$jpg_lib"'
        #new_str = ''
        #replace_in_file("%s/configure" % self.folder, old_str, new_str)

        configure_command = 'cd %s && %s SDL2_CONFIG=%s %s ./configure' % (self.folder, env_line, sdl2_config_path, custom_vars)
        self.output.warn("Configure with: %s" % configure_command)
        self.run(configure_command)

        #old_str = 'DEFS = '
        #new_str = 'DEFS = -DLOAD_JPG=1 -DLOAD_PNG=1 ' # Trust conaaaan!
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)

        #old_str = '\nLIBS = '
        #new_str = '\n# Removed by conan: LIBS2 = '
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)

        #old_str = '\nLIBTOOL = '
        #new_str = '\nLIBS = %s \nLIBTOOL = ' % " ".join(["-l%s" % lib for lib in self.deps_cpp_info.libs]) # Trust conaaaan!
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)
        #
        #old_str = '\nLIBPNG_CFLAGS ='
        #new_str = '\n# Commented by conan: LIBPNG_CFLAGS ='
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)
        #
        #old_str = '\nLIBPNG_LIBS ='
        #new_str = '\n# Commented by conan: LIBPNG_LIBS ='
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)
        #
        #old_str = '\nOBJCFLAGS'
        #new_str = '\n# Commented by conan: OBJCFLAGS ='
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)
        #
        #old_str = '\nSDL_CFLAGS ='
        #new_str = '\n# Commented by conan: SDL_CFLAGS ='
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)
        #
        #old_str = '\nSDL_LIBS ='
        #new_str = '\n# Commented by conan: SDL_LIBS ='
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)
        #
        #old_str = '\nCFLAGS ='
        #new_str = '\n# Commented by conan: CFLAGS ='
        #replace_in_file("%s/Makefile" % self.folder, old_str, new_str)
        #
        old_str = '\n# Commented by conan: CFLAGS ='
        #fpic = "-fPIC"  if self.options.fPIC else ""
        #m32 = "-m32" if self.settings.arch == "x86" else ""
        debug = "-g" if self.settings.build_type == "Debug" else "-s -DNDEBUG"
        #new_str = '\nCFLAGS =%s %s %s %s\n# Commented by conan: CFLAGS =' % (" ".join(self.deps_cpp_info.cflags), fpic, m32, debug)
        new_str = '\nCFLAGS =%s %s\n# Commented by conan: CFLAGS =' % (" ".join(self.deps_cpp_info.cflags), debug)
        replace_in_file("%s/Makefile" % self.folder, old_str, new_str)

        self.run("cd %s && %s make" % (self.folder, env_line))


    def package(self):
        """ Define your conan structure: headers, libs and data. After building your
            project, this method is called to create a defined structure:
        """
        self.copy(pattern="SDL_mixer.h", dst="include", src="%s" % self.folder, keep_path=False)

        # UNIX
        if not self.options.shared:
            self.copy(pattern="*.a", dst="lib", src="%s" % self.folder, keep_path=False)
            self.copy(pattern="*.lib", dst="lib", src="%s" % self.folder, keep_path=False)
        else:
            self.copy(pattern="*.so*", dst="lib", src="%s" % self.folder, keep_path=False)
            self.copy(pattern="*.dylib*", dst="lib", src="%s" % self.folder, keep_path=False)
            self.copy(pattern="*.dll", dst="lib", keep_path=False)

    def package_info(self):

        self.cpp_info.libs = ["SDL2_mixer"]
```
### commands used to build hello world
As I list in the readme for the [test](https://bitbucket.org/mutcoll/conan-sdl2-mixer-hello-world), I think the proper way should be something like the next block, but the `cmake --build .` fails.
```
git clone https://bitbucket.org/mutcoll/conan-sdl2-mixer-hello-world.git
cd conan-sdl2-mixer-hello-world
conan install --build=missing
cmake -G "Visual Studio 14 Win64"
cmake --build . 
./bin/test_mixer.exe  # didn't reach here
```

### conaninfo from hello world
here I can see that the hello world is using the default shared option for SDL2_mixer. Specifying explicitly `-o SDL2_mixer:shared=True` to `conan install` didn't make any difference.
```
[settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=14
    os=Windows

[requires]
    SDL2_mixer/2.Y.Z

[options]

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=14
    os=Windows

[full_requires]
    SDL2/2.0.4@lasote/stable:5873ceb24abc9238c6bd91b567a277ab595c8b62
    SDL2_mixer/2.0.1@jmmut/testing:5e011c5ed2d307078e8df34963e8642b8f7bb49c
    zlib/1.2.8@lasote/stable:63da998e3642b50bee33f4449826b2d623661505

[full_options]
    SDL2:directx=False
    SDL2:fPIC=True
    SDL2:shared=False
    SDL2_mixer:shared=True
    zlib:shared=False
```

### link error
Here I can guess that the linker is trying to use a `SDL2_mixer.lib`, which is not there, but I confirm that in `C:/Users/josemi/.conan/data/SDL2_mixer/2.0.1/jmmut/testing/package/5e011c5ed2d307078e8df34963e8642b8f7bb49c/lib` there is a `SDL2_mixer.dll`.
```
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\josemi\Documents\conan\conan-sdl2-mixer-hello-world\bin\test_mixer.exe" /INCREMENTAL /NOLOGO /LIBPATH:C:/Users/josemi/.conan/data/SDL2_mixer/2.0.1/jmmut/testing/package/5e011c5ed2d307078e8df34963e8642b8f7bb49c/lib /LIBPATH:C:/Users/josemi/.conan/data/SDL2_mixer/2.0.1/jmmut/testing/package/5e011c5ed2d307078e8df34963e8642b8f7bb49c/lib/Debug /LIBPATH:C:/Users/josemi/.conan/data/SDL2/2.0.4/lasote/stable/package/5873ceb24abc9238c6bd91b567a277ab595c8b62/lib /LIBPATH:C:/Users/josemi/.conan/data/SDL2/2.0.4/lasote/stable/package/5873ceb24abc9238c6bd91b567a277ab595c8b62/lib/Debug /LIBPATH:C:/Users/josemi/.conan/data/zlib/1.2.8/lasote/stable/package/63da998e3642b50bee33f4449826b2d623661505/lib /LIBPATH:C:/Users/josemi/.conan/data/zlib/1.2.8/lasote/stable/package/63da998e3642b50bee33f4449826b2d623661505/lib/Debug kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib SDL2_mixer.lib SDL2.lib GL.lib SDL2main.lib user32.lib gdi32.lib winmm.lib imm32.lib ole32.lib oleaut32.lib version.lib uuid.lib zlibstatic.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/josemi/Documents/conan/conan-sdl2-mixer-hello-world/bin/test_mixer.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/josemi/Documents/conan/conan-sdl2-mixer-hello-world/lib/test_mixer.lib" /MACHINE:X64  /machine:x64 test_mixer.dir\Debug\sdl.obj
LINK : fatal error LNK1104: cannot open file 'SDL2_mixer.lib' [C:\Users\josemi\Documents\conan\conan-sdl2-mixer-hello-world\test_mixer.vcxproj]
Compilaci▒n del proyecto terminada "C:\Users\josemi\Documents\conan\conan-sdl2-mixer-hello-world\test_mixer.vcxproj" (destinos predeterminados) -- ERROR.
Compilaci▒n del proyecto terminada "C:\Users\josemi\Documents\conan\conan-sdl2-mixer-hello-world\ALL_BUILD.vcxproj" (destinos predeterminados) -- ERROR.

ERROR al compilar.

"C:\Users\josemi\Documents\conan\conan-sdl2-mixer-hello-world\ALL_BUILD.vcxproj" (destino predeterminado) (1) ->
"C:\Users\josemi\Documents\conan\conan-sdl2-mixer-hello-world\test_mixer.vcxproj" (destino predeterminado) (3) ->
(Link destino) ->
  LINK : fatal error LNK1104: cannot open file 'SDL2_mixer.lib' [C:\Users\josemi\Documents\conan\conan-sdl2-mixer-hello-world\test_mixer.vcxproj]
```

**Comment by memsharded** [comment]
Hi!

The thing is how shared libs are linked in windows, probably not what you think! :)
In linux, the linker is able to link directly with .so files. But in windows there are two options. Either you fully dynamically load the shared lib at runtime, or you use an intermediate helper static lib with .lib extension, that is in charge of loading the shared lib. The later is the most typical approach in windows! So you need the .lib too for the shared one. You can note, however, that these .lib in this case are much, much smaller in size than their static counterparts.

So I would suggest improving your recipe to account for that. I would start with something as:

```python
def package(self):
        self.copy(pattern="SDL_mixer.h", dst="include", src="%s" % self.folder, keep_path=False)
        # lets try to copy .libs always!
        self.copy(pattern="*.lib", dst="lib", src="%s" % self.folder, keep_path=False)

        if not self.options.shared:
            self.copy(pattern="*.a", dst="lib", src="%s" % self.folder, keep_path=False)     
        else:
            self.copy(pattern="*.so*", dst="lib", src="%s" % self.folder, keep_path=False)
            self.copy(pattern="*.dylib*", dst="lib", src="%s" % self.folder, keep_path=False)
            self.copy(pattern="*.dll", dst="lib", keep_path=False)
```

If that would copy undesired .libs in the shared package, you would need to use the pattern or the src parameters to filter the libs you want.

Please check this approach and tell me. Cheers!

**Comment by jmmut** [comment]
Wow, that explains a lot, in fact I was about to ask why in [lasote's SDL2](https://github.com/lasote/conan-sdl2/blob/master/conanfile.py#L109) there was not an `if self.options.shared` for windows.

I just saw that in the sdl mixer page there's also a "development libraries" zip which includes SDL_mixer.lib as well as all the others dlls. I will try that later, and update this thread

**Comment by memsharded** [comment]
Exactly, using the development libraries sounds good. 
BTW, this is a very interesting usage of conan, probably worth writing a post about it.

**Comment by jmmut** [comment]
I passed this issue (yay!), but unfortunately now I face a couple of new problems.

First, I got an error "GL.lib not found", I wonder how can my windows 7 computer lack the GL libraries, but anyway, I saw that SDL2/2.0.3@lasote/stable still has not a dependency to GL, so it's not blocking and I can try to solve that later.

The other problem is that the paths of the libs don't seem to be correct. when launching the program:
```
$ ./test_mixer.exe
C:/Users/josemi/Documents/conan/conan-sdl2-mixer-hello-world/bin/test_mixer.exe: error while loading shared libraries: SDL2_mixer.dll: cannot open shared object file: No such file or directory
```
OK, just to test, I know that I can trick the linker putting the dlls in my current directory (or moving to where the dlls are), so after copying the sdl_mixer development libraries in the bin folder, I get:
```
$ ./test_mixer.exe
C:/Users/josemi/Documents/conan/conan-sdl2-mixer-hello-world/bin/test_mixer.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```
And then, I can officially say that I'm completely lost. 

What do you suggest? I'm doing this to program games as a hobby, and I thought it would be nice to allow windows users to play. Given that my programs require SDL and OpenGl, do you think this is easily achievable with conan? I think sdl_mixer has some Visual Studio project files, would you look into compiling with those?

**Comment by JPGygax68** [comment]
@jmmut: under Windows, the OpenGL import library is called `OpenGL32.lib`, not `GL.lib`.

For the other error, you should probably use [Dependency Walker](http://www.dependencywalker.com/) to find out which is the DLL that it cannot load.

**Comment by memsharded** [comment]
That is indeed quite typical, and that is why the ``package_info()`` is there. Something like:

```python
def package_info(self):
    self.cpp_info.libs = ["SDL....", "..."]
    if self.settings.os == "Windows":
        self.cpp_info.libs.append( "OpenGL32")
    else:
        self.cpp_info.libs.append("GL")
```

About the DLLs not in the path, conan tries not to mess in the path of the developer machine. So the ``imports()`` function (also [imports] in ``conanfile.txt``) can copy the DLLs into the user project. Just in case you were copying the DLLs manually.

I think it could be easier if I could reproduce the issue, is it the bitbucket conan-sdl2-mixer repo that I have to use, right? I will try to have a look at it.

**Comment by jmmut** [comment]
thank you both, dependency walker seems useful, but I think I should learn more about linking in windows before I can properly use it.

Regarding the opengl, I think it's lasote's SDL2 package who is bringing GL even for windows. And about my repos, yes, conan-sdl2-mixer is the package only, and conan-sdl2-mixer-hello-world is a small program that uses it. I know that I can include the test in the package, but I thought this would be easier to start with.

**Comment by memsharded** [comment]
I have cloned your project and having a look, will report asap.

**Comment by memsharded** [comment]
I have contributed a PR: https://bitbucket.org/mutcoll/conan-sdl2-mixer/pull-requests/1/test_package/diff

It implements the ``test_package``, it was specifically designed for package creators, to avoid having multiple repositories, and to automate package creation and testing. Please have a look and tell me.

I think also that some other things could be improved in the package, but lets go step by step. I would also like to know a bit more about the reasons not to build from source in windows, did you face many problems? Thanks!

**Comment by jmmut** [comment]
Thanks for the pull request! It's working for me as well :)

I would be glad improving the package, but as now it's working, that would go to the low priority queue ;).

The main reason to avoid compilation was to save time, both personal and compilation time. The SDL_mixer code lacks a cmake file. It has Visual Studio project files (as well as makefiles, xcode project files and others) but to use the visual studio build  I would need to add the linking against ${CONAN_LIBS} for the main SDL, on which SDL_mixer depends. As I don't know how to do that, and making a cmake from scratch would be too much, I chose to get the binaries. Did I miss anything?

And thanks again, I am now going to retake the opengl issue as well as making other packages windows-compatible, and I think your PR will help me to make it work faster!

**Comment by memsharded** [comment]
Great! Happy that it is working. Yes, much better to move forward with your needs, no need to improve the package now. 

I agree, writing CMake files for the project can be a very complex task, too much if you just want to use it as a consumer.

What is possible, just to let you know, is use directly MSBuild to build with the solution files too. It is not as easy as it is with Cmake, but doable. There is a small feature in develop for next release that will help loading the vcvars (environment vars necessary to build with different MSVC in the same machine), that will help. It probably requires some work to tell the Visual projects where to find the main SDL, but I think it could be done.

Just keep that in mind, and next time you face the similar problem, we can collaborate to try to do it.

Good, go for the OpenGL issue. I think this issue could be closed, or is anything else needed here? Just open a new issue if you have a different problem. BTW, for questions, we have also already subscribed to the Stackoverflow conan tag, so next time we will be notified, and hopefully are able to answer faster there too. Thanks very much!

**Comment by jmmut** [comment]
yes, this issue can be closed. I also learnt to solve (in other package) the opengl linking, basically with your 
```
    if self.settings.os == "Windows":
        self.cpp_info.libs.append( "OpenGL32")
    else:
        self.cpp_info.libs.append("GL")
```
in the package_info method.
Thanks again!

**Comment by memsharded** [comment]
Good job! Thanks for telling.
