### ISSUE TITLE
package_info not being called?

### ISSUE THREAD

**Issue by slnovak** [conan-io/conan#2882]
Hi,

I'm relatively new to Conan and trying to create a package for Geometric Tools on Windows via VS2017. I'm trying to render `conanbuildinfo.props` by populating files in the `cpp_info` object in the `package_info` method for my `conanfile.py` (as described by the docs), but it looks as though that method is not being called. The general workflow of creating a package seems to run all the way through even when raising an exception in that method.

Can you help point me in the right direction for getting the `visual_studio` generator to work correctly? I've included my `conanfile.py` which can be used to recreate the issue.

Thanks!

OS: Windows 10
Python: 3.6.5
Conan: ~1.2.0~ 1.3.2

```python
from conans import ConanFile, tools, MSBuild

class GeometrictoolsengineConan(ConanFile):
    name = "geometric_tools_engine"
    version = "3.12"
    license = "Boost"
    url = "https://geometrictools.com"
    description = "A library for computing in the fields of mathematics, graphics, image analysis and physics"
    settings = "os", "compiler", "arch"
    export_sources = "Source/*", "Include/*", "*.sln", "*.vcxproj*"
    generators = "visual_studio"

    def source(self):
        remote_file = "https://www.geometrictools.com/Downloads/GeometricToolsEngine3p12.zip"
        local_file = "geometric_tools_engine.zip"
        tools.download(remote_file, local_file)
        tools.unzip(local_file)

    def build(self):
        with tools.chdir("GeometricTools/GTEngine"):
            for build_type in ["Release", "Debug"]:
                msbuild = MSBuild(self)
                msbuild.build("GTEngine.v14.sln", build_type=build_type)

    def package(self):
        self.copy("*.h", dst="include", src="./GeometricTools/GTEngine/Include")

        for build_type in ["Release", "Debug"]:
            self.copy("*.lib",
                      dst="lib/{}/{}".format(self.platform, build_type),
                      src="./GeometricTools/GTEngine/_Output/v141/{}/{}".format(self.platform, build_type),
                      keep_path=False)

    def package_info(self):
        raise "package_info called." # Never raised!

    @property
    def platform(self):
        return "x64" if self.settings.arch == "x86_64" else "x86"
```

---

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by slnovak** [comment]
Ah, I realized that I had an outdated version of Conan. I updated to 1.3.2 and still have the issue.

**Comment by memsharded** [comment]
Hi @slnovak 

Your recipe looks and work great, if using Py2, it raises, with a caution about the exception, you better write:

```python
def package_info(self):
        raise Exception("package_info called.") # Never raised!
```

You should create your package with:
```bash
$ conan create . user/testing
```
Is that what you are doing? It seems to be good here, and the exception is raised.

Note, however, that the information in ``package_info()`` will NOT be used in the current package, in the generated .props. It is information extrictly for consumers, and that is the reason it is executed last in the flow: https://docs.conan.io/en/latest/reference/commands/creator/create.html

Please have a look and tell me. Thanks!

**Comment by slnovak** [comment]
Hm. So it appears that my code is working as expected now! I'm thinking that there was an issue with caching. Thanks for the response!
