### ISSUE TITLE
Version("6") < Version("6.0") == True 

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#2886]
Version model has a bug.
Version("6") is considered lower than "6.0". It introduced a bug (fixed in #2885) with the default`std`.

**Comment by danimtb** [comment]
Following the above logic all these should be ``True``:
- `Version("4") > Version("4.1")`
- `Version("4") > Version("4.0.7")`
- `Version("4") > Version("4.9999.99999")`
- `Version("4.7") > Version("4.1.99999")`
- `Version("4.1.1.1") < Version("4.9999.99999")`
- `Version("4.99999.1.1") > Version("4.9999.99999")`

**Comment by lasote** [comment]
It depends if we consider `4 == 4.0.0` or `any 4`. The only thing we know is that `Version("4") < Version("4.0")` has to be False.
For me `Version("4") > Version("4.0.7")` is still confusing. Any reason to not consider "4" as "4.0.0"?
