### ISSUE TITLE
Add `-if INSTALL_FOLDER` argument to `conan create`

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#2888]
Use case.
1. Local development, I call `conan install . -if build` to generate files to `build` subfolder. I'm using VS solution so it depends on prop files inside this `build` subfolder.
2. CI gets the project and uses CPT to generate configurations. It calls `conan create` command, but sadly there is no way to specify install folder now for it.

I'd like to make such feature.

**Comment by Minimonium** [comment]
Ok, after thinking about it how about a bit of another way around?
How about adding `generator_folder`  attribute to conanfile.py. So each project can output that stuff where it wants.
The problem is that when package/project developer is working on the code itself (which depends on some other packages) **and** wants to put his generator files somewhere other than root project folder he **can't**, because build_package doesn't care.
 Here is a possible flow:
1. `conan install path_to_conanfile` will output either into the current folder if no `generator_folder` defined or into the `path_to_conanfile/generator_folder`.
2. `conan install path_to_conanfile -if=install_folder` will output to `current_folder/install_folder` as now.
3. `conan create ...`  creates stuff with respect to `generator_folder` parameter.

**Comment by memsharded** [comment]
What about being explicit? I would suggest something on the line:
```python
def build(self):
      shutil.move("conanbuildinfo.cmake", "mybuildfolder")
```
I am not saying it is not a good idea, it could be useful. I have tried a couple of things and I agree there could be something to improve. Lets check this further.

**Comment by Minimonium** [comment]
That way works too I guess.
But I thought more about general `development flow` of a project.  I'm not sure is it worth it.
It's not practical to introduce a special solution for `install_folder` only but want if we consider #2837 as well? Solutions when developers want to place their build artifacts in a structure they like (*_multi variants)?
Sure, you can move stuff by hands and force developer who works on that project to use arguments for `install` for example. But the possibility of defaulting folders for `install` seems not bad.
But of course, as I see it now simple "*_folder" attribute may not quite suffice for *_multi generators, should it be able to work around project configuration, what do you think?
It's more of how Conan team views such development flow.

**Comment by Minimonium** [comment]
@memsharded I have a new problem with that. I'm using `visual_studio_multi` with something like this:
```
build_dir = "build"
        tools.mkdir(build_dir)
        for file in glob.glob(r'*.props'):
            print(file)
            shutil.copy(file, build_dir)
```
The problem:
It generates multi file which points to root-level configuration specific files.

**Comment by Mark-Hatch-Bose** [comment]
I just want to second this. I ran into this problem as well due to the strange layout we use in our builds.
When running `conan create` in parallel I'd get strange errors `cp: will not overwrite just-created` when trying to package. Likely more work can be done to fix this internally.

I got around it by instead calling the following in our CI implementations
```
conan install . --pr ${arch} --update -if ${installDir}
conan build . -if ${installDir}
conan export-pkg . ${env.BRANCH_NAME}/latest -if ${installDir} --force
```

I can simulate the main steps we would use in `conan create`, and then I can upload them as normal.

**Comment by Mark-Hatch-Bose** [comment]
It turned out that this was actually caused by running parallel builds, and a poorly executed staging script that was copying files outside of the install folder. I revoke what I said two weeks ago, this is not necessary for me. :100:

**Comment by memsharded** [comment]
``-if`` argument has been completely removed from Conan 2.0, this no longer applies (there are other mechanisms like layout() and ``-of``)
