### ISSUE TITLE
Conan search with exclude patterns

### ISSUE THREAD

**Issue by luckielordie** [conan-io/conan#2890]
In the current version Conan 1.3.3.

It would be nice to be able to specify exclude patterns when searching in a remote. When searching through the bincrafters repository for example a large portion of the search return is boost packages.

If we could query for a pattern and add an exclude pattern to not display packages that were caught might be a useful feature? 

Thanks!

**Comment by danimtb** [comment]
Indeed, doing a search like `conan search b* -r all` with the bincrafters repository configured is a bit annoying. I think this coudl be a valid feature only to search recipes. WDYT @lasote @memsharded?

**Comment by lasote** [comment]
Well, I'm not sure, `conan search b* -r all` doesn't look like a reasonable search. Why are you interested in all the packages starting with "b"? 📦 
@luckielordie What is your use case? Which pattern have you specified?
