### ISSUE TITLE
How to check attribute existence?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2892]
I thought `hasattr()` is legit for that:
```python
if hasattr(self.settings.os, "subsystem"):
   # ...
```

but it isn't. When the attribute exists it works, but if it doesn't, `ConanException` is raised:
```
if hasattr(self.settings.os, "subsystem"):
        ConanException: 'settings.os.subsystem' doesn't exist for 'Windows'
'settings.os' possible configurations are none
```

**Comment by danimtb** [comment]
Hi @db4,
[Digging a little bit in the conan codebase](https://github.com/danimtb/conan/blob/b28a257037f079989eb137dbd734e05613cda141/conans/model/settings.py#L202), you can try with `self.settings.get_safe("os.subsystem")`.

Find an example in this recipe:
https://github.com/conan-community/conan-mingw-installer/blob/7e03ef870ed0b4dcc37f347af96ce501b22f240a/conanfile.py#L37

You could also use a simple try/catch if you dare to do so! Hope this helps 😄

**Comment by db4** [comment]
Understood. Thank you very much!
