### ISSUE TITLE
[question] Default options for conditional requirements

### ISSUE THREAD

**Issue by kznamst** [conan-io/conan#2894]
Let's say i have three libs LibA, LibB and LibC.

This is the relation between those libs:
`LibA` -> `LibB` -> `LibC`

Now, in the `conanfile.py` of **LibC** i have:
```python
options = {
      "option_1": [True, False],
      "option_2": [True, False]
    }
    default_options = ("option_1=True", "option_2=True")
```

In the `conanfile.py` of **LibB** i have:
```python
options = {
      "option_3": [True, False],
      "option_4": [True, False]
    }
    default_options = ("option_3=True", "option_4=True")

...

def requirements(self):
    if self.settings.os != "Windows":
        self.requires("LibC/1.0.0@user/stable")
```

And here(**^**) i want to specify the default options for **LibC**: `option_1=False` and `option_2=False`, i found out that you can do it this way:
```python
def configure(self):
    if self.settings.os != "Windows":
       self.options["LibC"].option_1 = False
       self.options["LibC"].option_2 = False
```
But this way they won't be able to be modified in the next `conanfile.py`(**LibA**) according to[ the docs](https://docs.conan.io/en/latest/mastering/conditional.html). I do not want the user to be forced to use those options. 

If the user called `conan create . LibB/1.0.0/uset/stable` without `-o LibC:option_1=False` or any other option for **LibC**, I want the default ones for the **LibC** to be different options values from those that are in the `default_options` variable from the `conanfile.py` of **LibC**. And when the user specifies some options to be used for **LibC**, i want them to be used.

I am asking if there is a way to add those default options of **LibC** in the `conanfile.py` of **LibB**, where **LibC** is a conditional requirement, something like this:
```python
def configure(self):
    if self.settings.os != "Windows":
       self.default_options = self.default_options + ("LibC:option_1=False", "LibC:option_2=False")
```
I tried this way and the default_options do not  get detected, they remain the same as they were in the `conanfile.py` of **LibC**

**Comment by kznamst** [comment]
I never thought to do it this way: 
```python
options = {
      "option_3": [True, False],
      "option_4": [True, False]
    }
    default_options = ("option_3=True", "option_4=True", "LibC:option_1=False", "LibC:option_2=False")

...

def requirements(self):
    if self.settings.os != "Windows":
        self.requires("LibC/1.0.0@user/stable")
```
This will always work, on Windows the `default_options` for the `LibC0.1@user/channel` will be ignored, they will only be used on every other os.

Amazing!! Sorry for this issue.

The docs do not mention anything about this, so i added an example : https://github.com/conan-io/docs/pull/653

**Comment by danimtb** [comment]
Hi @kznamst,

As you figured out, options are only aplied if the package name scope matches. Otherwise, they are ignored.

I agree this should be better documented. Thanks a lot for the PR 😄
