### ISSUE TITLE
Best practice conan build for the production environment

### ISSUE THREAD

**Issue by dhanasekaran-deepvalue** [conan-io/conan#2896]
Hi Guys,

We are new to C++ World. We like to understand How to build a package for a production system.

currently, we doing likes this.

All the dependency package we installed via Conan package manager.

```
git cone repo
cd project_dir
conan source .
conan install .
conan build .
```
Once build is done, an executable is generated, we just invoking `./executable_name`

we like to know the above-mentioned procedure is correct. for prod environment?

In Java + maven we have a separate machine to build the package, once package build we copied build jar to a production machine. We will invoke the java command.

In Conan I am not sure how to copy the binary from build machine to production machine? Do I need to clone the entire source code and install all the development libraries and build it in the prod machine separately?

can you please guide me, what is the best practice move dev to prod environment.

Thanks,
Dhanasekaran.

**Comment by memsharded** [comment]
Hi Dhanasekaran,

Conan is mainly targeted for development, not as a distribution/installation system for the runtime, though it can be also used for that, typically re-packaging the runtime artifacts only.

I have a couple of questions:
- You are already consuming existing packages that you declare as requirements? Are you getting them from Bintray? The recommended approach for production is actually to host a couple yourself, the recommended way is with the free Artifactory CE.
- Have you read this section? https://docs.conan.io/en/latest/devtools/running_packages.html Maybe it is what you are looking for.
- Do you know what the imports(), and deploy() methods are? They help to extract installed artifacts from the local conan cache to your own folders.

Thanks!

**Comment by memsharded** [comment]
Closing as inactive
