### ISSUE TITLE
tools.which also returns dirs

### ISSUE THREAD

**Issue by intelligide** [conan-io/conan#2897]
Hi, 

`tools.which` can returns a folder path if his basename match. For example, on Windows, it returns `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git` which is a directory.

You can reproduce with:
```python
import os
from conans import tools

tools.mkdir("C:\Dev")
tools.mkdir("C:\Dev\Git")
with tools.environment_append({"PATH": "C:\Dev\;"+tools.get_env("PATH")}):
    git = tools.which("git") # returns "C:\Dev\git"

    print(os.path.isfile(git)) # Is False
```

I work with:
 * Conan 1.3.3
 * Windows 10 1709

Thanks !

**Comment by lasote** [comment]
Thanks! it is quite easy to solve it, so we will solve it for the next release.
