### ISSUE TITLE
Packaging license file

### ISSUE THREAD

**Issue by jakirkham** [conan-io/conan#2900]
Please add a `MANIFEST.in` with the line below to ensure the license is packaged in `sdist`s uploaded to PyPI.

```
include LICENSE.md
```

**Comment by memsharded** [comment]
Hi @jakirkham 

In which file should we add it? Feel free to do directly the pull request. Many thanks!

**Comment by jakirkham** [comment]
Right. So this would be a new file called `MANIFEST.in` with the line above. Here's [PyPI's example]( https://github.com/pypa/sampleproject/blob/6a2444b88f48eaa1cf3a2f32fe8bbed8dad82801/MANIFEST.in#L4-L5 ).
