### ISSUE TITLE
ValueError exception in client/tools/win.py **bug**

### ISSUE THREAD

**Issue by foobar222** [conan-io/conan#2904]
Upgrading to conan 1.3.3 broke my build slave with the following stack trace:

Traceback (most recent call last):
  File "build.py", line 30, in <module>
    builder.run()
  File "E:\Program Files\Python36\lib\site-packages\cpt\packager.py", line 328, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "E:\Program Files\Python36\lib\site-packages\cpt\packager.py", line 404, in run_builds
    r.run()
  File "E:\Program Files\Python36\lib\site-packages\cpt\runner.py", line 48, in run
    with context:
  File "E:\Program Files\Python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "E:\Program Files\Python36\lib\site-packages\conans\client\tools\win.py", line 326, in vcvars
    new_env = vcvars_dict(*args, **kwargs)
  File "E:\Program Files\Python36\lib\site-packages\conans\client\tools\win.py", line 307, in vcvars_dict
    name_var, value = line.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

Details: Conan version 1.3.3, Windows 7, CMake 3.8.2, Visual Studio 2013 Win64

By looking in to it, what happens is line.split("=", 1) on an empty line, in vcvars_dict(). No idea where the empty line comes from (likely from one of VS env scripts), but the following patch solves the symptom. 

```
 conans/client/tools/win.py | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/conans/client/tools/win.py b/conans/client/tools/win.py
index d025ec4..56dcbbd 100644
--- a/conans/client/tools/win.py
+++ b/conans/client/tools/win.py
@@ -304,8 +304,11 @@ def vcvars_dict(settings, arch=None, compiler_version=None, force=False, filter_
             if "__BEGINS__" in line:
                 start_reached = True
             continue
-        name_var, value = line.split("=", 1)
-        new_env[name_var] = value
+        try:
+            name_var, value = line.split("=", 1)
+            new_env[name_var] = value
+        except (ValueError):
+            pass
 
     if filter_known_paths:
         def relevant_path(path):



```

**Comment by danimtb** [comment]
Hi @foobar222 

I see you are using conan package tools right? Could you indicate the version you are using?

**Comment by foobar222** [comment]
Version of conan_package_tools:

E:\src\build>pip show conan_package_tools
Name: conan-package-tools
Version: 0.17.1
Summary: Packaging tools for Conan C/C++ package manager
Home-page: https://github.com/conan-io/conan-package-tools
Author: JFrog LTD. Luis Martinez de Bartolome
Author-email: luism@jfrog.com
License: MIT
Location: e:\program files\python36\lib\site-packages
Requires: six, requests, conan, tabulate
Required-by:

**Comment by foobar222** [comment]
Hi, and thanks for looking into it.

I cannot run the command verbatim in my build slave (gitlab runner), as it is run as a windows service. It is possible that my gitlab runner's environment is to blame, i suppose it could happen by having an environment variable with a trailing newline.

Running the above command from cmd.exe under the same user, adjusted for VS Pro paths and redirect stdout to a file shows no empty lines in the output. All lines ends with CRLF.

Adjusting paths for VS2013 (which is what i currently use) does not reveal any empty lines on stdout either, although stderr appears to have one less line than for VS2017 (but probably not relevant, if subprocess.check_output captures only stdout) .

**Comment by foobar222** [comment]
Update:

It looks like gitlab runner is to blame for the suspicious environment variable. Looking at how commands are run (when using windows batch shells), a batch file is generated according to:

https://docs.gitlab.com/runner/shells/#windows-batch

The beginning of the generated file is as follows:

```@echo off
setlocal enableextensions
setlocal enableDelayedExpansion
set nl=^

```

The caret after `nl=` escapes what follows, which here is a newline. I can confirm that this is the same variable causing the python ValueError, by editing conans/client/tools/win.py to print all env vars, and inspecting the build log. The last processed env var before catching the exception is named `NL`.

**Comment by danimtb** [comment]
Thanks for the detailed investigation. I will work on this today and we will prepare the fix for next conan release.
