### ISSUE TITLE
Conan upload --force not working

### ISSUE THREAD

**Issue by Sebiee** [conan-io/conan#2905]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

## System info
**Conan version**: 1.3.3 (but also tested with 1.3.2)
**Operating System**: Debian 9 (stretch)

## Bug explanation
When I do
```bash
conan upload --force -r my_remote my_package
```
The output is `Recipe is up to date, upload skipped`
The help for the _--force_ flag is:
`Do not check conan recipe date, override remote local`
I expect that using the _--force_ flag would upload the package no matter what.

## Steps to reproduce
```
conan upload -r remote new_package
conan upload --force -r remote new_package
```

**Comment by danimtb** [comment]
Hi @Sebiee 

`--force` flag should be used to force upload when the recipe in the remote is newer than the recipe you are trying to upload. This wasw implemented to avoid this situation when conan report: `Remote recipe is newer than local recipe`

In your case, Conan is telling you that the recipe you are trying to upload is exactly the same recipe you have in the remote, so there is no need to force the upload. I think the help message is clear.

Dont know if this is your use case but you can still upload new packages with `--all` flag.
