### ISSUE TITLE
Win 10 /Conan 1.3.3 Unable to connect to conan-center=https://conan.bintray.com

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#2913]
To help us debug your issue please explain:

- [x ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Working the example that uses poco. Before recreating the issue:
1) uninstalled conan via control panel.  
2) Deleted the config dir via : rm -rf ~/.conan dir 
3) Re-installed fresh 1.3.3

------------------------------ start  error ---------------------------------------------------------------------
build>  conan install ..
Auto detecting your dev setup to initialize the default profile (D:\Users\xxxxxx\.conan\profiles\default)
Found Visual Studio 11
Found Visual Studio 14
Found Visual Studio 15
Found clang 5.0
Default settings
        os=Windows
        os_build=Windows
        arch=x86_64
        arch_build=x86_64
        compiler=Visual Studio
        compiler.version=15
        build_type=Release
*** You can change them in D:\Users\xxxxxxx\.conan\profiles\default ***
*** Or override with -s compiler='other' -s ...s***

WARN: Remotes registry file missing, creating default one in D:\Users\xxxxx\.conan\registry.txt
Poco/1.9.0@pocoproject/stable: Not found in local cache, looking in remotes...
Poco/1.9.0@pocoproject/stable: Trying with 'conan-center'...
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/Poco/1.9.0/pocoproject/stable/download_urls (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

Unable to connect to conan-center=https://conan.bintray.com
------------------------------ end error ---------------------------------------------------------------------

Contents of D:\Users\xxxxx\.conan\registry.txt: "conan-center https://conan.bintray.com True"

Now I am behind a corporate firewall but the proxies should be good. Suggestions on verifying connectivity? My fear is this is the issue.

I also have access to an enterprise version of Artifactory.... I don't see many examples on using Conan and Enterprise Atrifactory.  (Community sure, but I am sure the corporate overlords would really like us to use the enterprise version .... Artifactory support was no help)

It would be awfully nice to be able to mirror say the poco project from bintray/Artifactory CE to an Enterprise Artifactory ... but that is another topic.

Thanks and Regards
Carl

**Comment by memsharded** [comment]
Hi Carl (@ShamanTcler)

Thanks for your detailed report. It seems that it is a certificate issue, which is weird, because it means that conan-center is visible but for some reason, the certificates are failing. Could well be because of the firewalls and proxies. Are you actually trying to connect to conan-center or just to your artifactory? If so, please remove it:

```bash
$ conan remote remove conan-center
```
Then add your artifactory remote (after adding a Conan remote, and following the SetMeUp URL):
```bash
$ conan remote add artifactory <url-SetMeUp>
```

Please tell me if this is what you need. Thanks!

**Comment by ShamanTcler** [comment]
First let be applaud your dedication ... the day after your big conference and you are responding.

My previous effort in March with our Enterprise Artifactory was less than satisfying ... I blame us. This time I see a "set me up"  button on my Artifactory / conan repository so that was encouraging. Yes I know the bits are still warm out of the oven on this stuff, so I expect a few hiccups.

So I did the:
1) conan remote remove conan-center

The next steps were generate via the "set  me up" page.

2) conan remote add QSLFU-CONAN https://xxxx.xxxx.xxxx.com/artifactory/api/conan/QSLFU-CONAN

(gotta love the descriptive name QSLFU-CONAN don't you .... I did not pick it, it was picked for me)

3) conan user -p APxyxyxyxyxyxyxyxy69w -r QSLFU-CONAN myUserId

to which I receive:

_ERROR: HTTPSConnectionPool(host='xxxx.xxxx.xxx.com', port=443): Max retries exceeded with url: /artifactory/api/conan/QSLFU-CONAN/v1/users/authenticate (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Bad Gateway',)))

Unable to connect to QSLFU-CONAN=https://xxxx.xxxx.xxx.com/artifactory/api/conan/QSLFU-CONAN_

So once again no love.

Is this the correct forum for this? Should I be using the official bug reporting structure? (Remember in March they basically suggested converting to Java/Maven ... shiver)

Best Regards
Carl

**Comment by memsharded** [comment]
Hi Carl,

> First let be applaud your dedication ... the day after your big conference and you are responding.

How you know it? :) 
But yes, we were very busy (and amazing, SwampUp was great) last week, we couldn't keep responding as always, trying to catch up and provide the best support we can!

> (gotta love the descriptive name QSLFU-CONAN don't you .... I did not pick it, it was picked for me)

:D :D 


I am re-opening the issue, yes, this is the correct forum to discuss this, unless until we figure out what is happening. Lets keep trying. Also, we are in a #conan channel in the CppLang slack, if you want to live chat and discuss.

So it seems you are under a proxy that is causing some trouble. There are a couple of settings in conan that you could try to use to avoid this. If the Artifactory is local and shouldn't go through the proxy. From https://docs.conan.io/en/latest/reference/config_files/conan.conf.html?highlight=proxy#proxies, I'd say to try to add ``no_proxy_match: http://yoururl`` to your conan.conf and try again.

Please tell me if it works. Thanks!

**Comment by ShamanTcler** [comment]
So tried two things

1) in the config file I add a line : no_proxy_match = https://xxxxx.xxx.xxx.com

ERROR: HTTPSConnectionPool(host='xxxx.xxx.xxx.com', port=443): Max retries exceeded with url: /artifactory/api/conan/QSLFU-CONAN/v1/users/authenticate (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Bad Gateway',)))

Unable to connect to QSLFU-CONAN=https://xxx.xxxx.xxxx.xxx.xx.com/artifactory/api/conan/QSLFU-CONAN

2) So reading the config file note I just commented the whole mess

#[proxies]
# Empty section will try to use system proxies.
# If don't want proxy at all, remove section [proxies]
# As documented in http://docs.python-requests.org/en/latest/user/advanced/#proxies
# http = http://user:pass@10.10.1.10:3128/
# http = http://10.10.1.10:3128
# https = http://10.10.1.10:1080
# You can skip the proxy for the matching (fnmatch) urls (comma-separated)
# no_proxy_match = *bintray.com*, https://myserver.*

ERROR: HTTPSConnectionPool(host='xxxx.xxx.xxx.com', port=443): Max retries exceeded with url: /artifactory/api/conan/QSLFU-CONAN/v1/users/authenticate (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Bad Gateway',)))

Unable to connect to QSLFU-CONAN=https://xx.xx.xx.xx.com/artifactory/api/conan/QSLFU-CONAN

So Ok I then say lets ping the URL ....
~> ping xxx.xxx.xxxx.xxx.com                                            (Cygwin on Win 10)

Pinging xxx.xxx.xxx.com [3.239.244.206] with 32 bytes of data:
Reply from 3.239.244.206: bytes=32 time=19ms TTL=50
Reply from 3.239.244.206: bytes=32 time=20ms TTL=50
Reply from 3.239.244.206: bytes=32 time=21ms TTL=50
Reply from 3.239.244.206: bytes=32 time=21ms TTL=50

So yes I can see the server.

I have tried wireless and wired connections seems to be no difference

Not sure if this matters but we are running F5 ( https://f5.com/ ) and McAffee.

**Comment by ShamanTcler** [comment]
Sorry forgot to preview and the config file caused some interesting formatting .... should have been: 

<div>
#[proxies]
</div>
<div>
# Empty section will try to use system proxies.
</div>
<div>
# If don't want proxy at all, remove section [proxies]
</div>
<div>
# As documented in http://docs.python-requests.org/en/latest/user/advanced/#proxies
</div>
<div>
# http = http://user:pass@10.10.1.10:3128/
</div>
<div>
# http = http://10.10.1.10:3128
</div>
<div>
# https = http://10.10.1.10:1080
</div>
<div>
# You can skip the proxy for the matching (fnmatch) urls (comma-separated)
</div>
<div>
# no_proxy_match = *bintray.com*, https://myserver.*
</div>

**Comment by memsharded** [comment]
HI @ShamanTcler 

Just a quick tip: If you want to copy and paste code here in github and not have it formatted, use three backticks at the beggining and end.

Regarding your error, I think the next thing I'd try is to rule out that the problem is in conan. So I would download the Artifactory free Community Edition (available for download in conan.io), run it locally (no need to install anything, simply get the zip, unzip it and run the .bat inside the bin subfolder), then create a new repo and upload to that repo. If you need help with it, please tell.

Then, second thing, I didn't get that the address for Artifactory is a .com, so it is most likely outside of your network and is accessed via your local proxy, so the ``no_proxy_match`` won't help here.

You probably need to configure your proxy in the ``conan.conf`` file. Have you tried entering your proxy in the ``[proxies] section?

Feel free to reach us on email (info@conan.io), if you don't want to disclose private details here.

Cheers!

**Comment by ShamanTcler** [comment]
If it weren't for bad luck I would have no luck at all. 

I downloaded "Artifactory CE" and fired it and got a "403 Forbidden" error message when I went to http://localhost:8081/artifactory. Seems McAfee is camped on port 8081.

Process to move Artifactory CE off of port 8081 

1)	On windows, to see who is camped on 8081  (has to be run as admin, and this will take a while)

     conanTst1>  netstat -a -b -o | grep 8081
     TCP    0.0.0.0:8081           G874HJC2E:0            LISTENING       5116
     TCP    [::]:8081              G874HJC2E:0            LISTENING       5116

     Ok lets see if 8083 is open.

      conanTst1> netstat -a -b -o | grep 8083
      conanTst1>			<- So 8083 seems available

2)	From the file: */artifactory-cpp-ce-6.0.0/tomcat/conf edit the file server.conf
```<Server port="8015" shutdown="SHUTDOWN">
    <Service name="Catalina">
        <Connector port="8081" sendReasonPhrase="true"/>
        <!-- Must be at least the value of artifactory.access.client.max.connections -->
        <Connector port="8040" sendReasonPhrase="true" maxThreads="50"/>
        <!-- This is the optional AJP connector -->
        <Connector port="8019" protocol="AJP/1.3" sendReasonPhrase="true"/>
        <Engine name="Catalina" defaultHost="localhost">
            <Host name="localhost" appBase="webapps" startStopThreads="2"/>
        </Engine>
    </Service>
</Server>
```
3)	Change 8081 to 8083
4)	Restart “Artifactory CE”

Now I can connect to Artifactory CE at: http://localhost:8083/artifactory

Just hope I did not break anything else.

**Comment by memsharded** [comment]
I think I will add this info in the docs, it might help other users too, thanks for your time investigating and fixing this, it makes sense, I don't think it would break anything else.

Yes, your path is being a bit bumpy, but ey, all of us struggle constantly with these kind of things. Celebrate how well you solved the issue and that your work might be useful to others, and that you keep moving forward. No bad luck, good job instead :)

Now, when possible, please try to upload something from conan to that Artifactory, to see if  it is possible, to start ruling out possible things. Thanks!

**Comment by ShamanTcler** [comment]
Just a quick updater... never could get proxies right for the enterprise version... the wonderful world of big companies.

However, Artifactory CE when mapped to port 8083 seems to be working splendidly. 

Thanks so much for your work and support.

Regards
Carl

**Comment by memsharded** [comment]
ConanCenter was moved from https://conan.bintray.com, to a new location and infrastructure, hopefully this problem should be gone now

**Comment by baluoteliz** [comment]
error description: windows error: httpsconnectionpool(host='conan.bintray.com', port=443): max retries exceeded with url: /v1/ping (caused by sslerror(sslerror(1, '[ssl: sslv3_alert_handshake_failure] sslv3 alert handshake failure (_ssl.c:1129)')))

solutions step: 
1 conan remote remove pc
2 conan remote add pc http://xxxxx/api/conan/conan-local
3 conan user -p xxxx -r pc pc_deploy

then all the problem resolved.

**Comment by memsharded** [comment]
conan.bintray.com was removed years ago. New ConanCenter is in center.conan.io and it is the default in new Conan versions
