### ISSUE TITLE
CMake helper not escaping spaces. Recommended way to use direct paths to libraries

### ISSUE THREAD

**Issue by Sebiee** [conan-io/conan#2923]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

## System info
**Conan version**: 1.3.3
**Operating System**: Debian 9 (stretch)

## Problem explanation
In my projects, instead of letting the compiler search for libraries, what I prefer to do is to give the direct path to the library i want to use. While not found a recommended way for doing this, I managed to do it like so:

```python
def package_info(self):
        self.cpp_info.libs = [
             os.path.join(self.package_folder,"lib","libstring_wrapper.a")
        ]
        del self.cpp_info.lib_paths[:]
```

This way, the compiler gets no `-L` or `-l` flag, but the direct path to the lib. This works like charm normally, only I recently encountered a problem in a Windows environment, where the direct path to the library would contain a space. In this case, since the cmake variable for libs gets the strings without quotes or spaces escaped, the linker will see 2 libs. That is, for:
```
set(CONAN_LIBS /home/my user/.conan/data/string_wrapper/1.0.0/test/test/package/57547fe65fffc300f05aa42ee64b3b02eeabb6d7/lib/libstring_wrapper.a ${CONAN_LIBS})
```
the linker will see `/home/my` as a lib and `user/.conan/data/string_wrapper/1.0.0/test/test/package/57547fe65fffc300f05aa42ee64b3b02eeabb6d7/lib/libstring_wrapper.a` as other lib.

If I add quotes to the string in `self.cpp_info.libs` or escape the spaces by myself, that doesn't help since conan will escape my quotes and my backslashes.

Is there other recommended way to give direct paths for libs? Is there a reason why the spaces are not and should be not escaped? How can I achieve what I want?

**Comment by memsharded** [comment]
Hi @Sebiee 

If you are already using the CMake helper (when using TARGETS), it will already compute the full path to the library, using the ``libdirs`` and the ``libs``. Have you tried it?

Those paths will be quoted, so they should manage spaces without problem too.

**Comment by Sebiee** [comment]
Woah, this is simple, and works like charm. I didn't know targets do this!
## What I did
#### In library recipe:
```python
def package_info(self):
        self.cpp_info.libs = ["libstring_wrapper.a"]
```
In the exported package there must be a file with the exact name you put in libs in order for the linker to get the full direct path. Also, I haven't populated `self.cpp_info.lib_paths` nor `self.cpp_info.libdirs` since my library is in the default place (`package_folder/lib/libstring_wrapper.a`)

#### In application cmake:
```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

target_link_libraries(my_application ${CONAN_TARGETS})
```
I wrote this for eventual google searchers.

Thanks for your response!

**Comment by danimtb** [comment]
Also for the record: https://docs.conan.io/en/latest/reference/generators/cmake.html#methods-available-in-conanbuildinfo-cmake
