### ISSUE TITLE
Override compiler settings in build()

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#2929]
Hello,

I need to do a workaround because we have troubles with the newest visual studio 2017 release (and we have no older installer files :disappointed:  ).

I need to pass a different toolset to the VisualStudioBuildEnvironment class. I want to clone self and just change the toolset and pass it to VisualStudioBuildEnvironment in the build function. It's not possible for me to set the toolset for all dependecies!

Is there an easy we to clone the self(conanfile).
* shallowcopy works but does not clone settings
* deep copy makes an error

Greetings  
Tonka

**Comment by memsharded** [comment]
Hi @tonka3000 

Not sure what you want. The VisualStudioBuildEnvironment returns a dict with the vars, can't you just replace them? Which toolset are you using that is problematic? Aren't you using MSBuild helper? Can you further explain your usage of VisualStudioBuildEnvironment? Many thanks!

**Comment by tonka3000** [comment]
Hey @memsharded ,

I've already see in the conan code that changing the toolset does not help me at all.

My problem:  
I have a recipe with qt. It's only buildable with 15.3 (vs 2017 update 3), other version (of vs2017) introduce a crash in qmake in debug mode. Microsoft explain [here](https://blogs.msdn.microsoft.com/vcblog/2017/11/15/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/) that i could switch the platform toolset, because the newer installer can install older 2017 update toolsets side by side. So i've tried to switch my build to a lower toolset when vs2017 is present. But i have no luck with conan to do that.

Do you have any idea what i can do now?

Greetings  
Tonka

**Comment by tonka3000** [comment]
For me this toolset's are also new. I'm also not sure how to set that platform thing correct, because the explanation from microsoft is not good here.

Here is a snippet.

```py
env = {}
        env.update({'PATH': ['%s/qtbase/bin' % source_dir_absolute,
                             '%s/gnuwin32/bin' % source_dir_absolute,
                             '%s/qtrepotools/bin' % source_dir_absolute]})
        conan_compiler_version_to_qmakespec_mapping = {
            "15" : "win32-msvc2017",
            "14" : "win32-msvc2015",
            "12" : "win32-msvc2013",
            "11" : "win32-msvc2012",
            "10" : "win32-msvc2010"
        }
        qmakespec = conan_compiler_version_to_qmakespec_mapping[str(self.settings.compiler.version)]
        env.update({ "QMAKESPEC": qmakespec })
        args += ["-platform %s" % qmakespec]

        env_build = VisualStudioBuildEnvironment(self)
        env.update(env_build.vars)
```

I would be really helpfull if someone has made an offline installer from 15.3, so it would be very easy to rollback ci servers

**Comment by memsharded** [comment]
Yeah, I don't think you can configure the 15.3 via toolsets. You'd need to rollback, it is unfortunate that it is not available anymore.

**Comment by tonka3000** [comment]
Hey @memsharded ,

my "workaround" works pretty well. Microsoft change the strategy since VS 2017. They always deploy latest Visual Studio version and the latest compiler toolset. But in the installer you have the chance to install the old toolsets side by side (see [here](https://blogs.msdn.microsoft.com/vcblog/2017/11/15/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/)).

In my case i made following patch. I use `VisualStudioBuildEnvironment` to get the vars dict to update my environment. When the `compiler.version` is `15` then i check the env vars and extract the toolset. If it is higher then my compatible ones i search in the path which was found for different toolsets. When i found a good one i replace the paths in the env vars.

That toolset switch seems to be the new 2017 way to switch between compiler toolsets for 2017 compilers itself.

Installer-toolset options:
![image](https://user-images.githubusercontent.com/3163807/40477978-1db6354c-5f48-11e8-9509-4fc981b777c5.png)

In the default installer path of VS 2017 the toolsets are in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC`.

I'm not sure if it is good or bad to add something to conan? What do you think?

**Comment by tonka3000** [comment]
Ok. Forget my workaround. I could fix the problem without changing the toolset. But if someone need to switch the toolset for vs 2017, [here is my gist](https://gist.github.com/tonka3000/8f3efdd7bebccadbf41fb3773d50dcb1). My `vcvars_command` command append the `-vcvars_ver=` to vcvars call if a given toolset is not want. @memsharded It would be nice when there would be a `vcvars_ver` variable in `tools.vcvars_command`, so it would be much easier to stick the command together
