### ISSUE TITLE
add file-filter for tools.unzip

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#2938]
Hey,

I would be totally nice when `tools.unzip` would support a file filter. At the moment i've download some zips and need on a part of it, this would speedup things a lot. I've looked into the actual code of unzip and it should not be that hard to support that.

What do you think about such feature?

Greetings  
Tonka

**Comment by danimtb** [comment]
HIi@tonka3000, thanks for your suggestion.
It should not be hard to implement although I think it may not be heavily used.
We could keep this open to see if we get some valunteers to contribute! 😉

**Comment by MathPlayer** [comment]
I solved this. As mentioned in the `CONTRIBUTING.md` file, I will update the documentation in the other repo before creating the pull request.

**Comment by memsharded** [comment]
Will be released in 1.5
