### ISSUE TITLE
`conan download` extracts and removes export_sources.tgz

### ISSUE THREAD

**Issue by mabrowning** [conan-io/conan#2940]
To help us debug your issue please explain:

I'm "mirroring" conan-center remotes for our company's commonly used recipes and packages in order to a) not get rate-limited and b) be less reliant on external resources for our critical build infrastructure. Up until now, I've been able to `conan download` the recipes we use directly into our local conan remote's data directory. Maybe this is the root issue, but its been working pretty well for the past few months.

However, after downloading `jsoncpp/1.8.4@theirix/stable` into our remote (which apparently is the first to use `exports_sources`), conan client pulling from it failed to build. After debugging a bit, it seems that `conan download` extracts `conan_sources.tgz` *and deletes* it, making it unavailable for serving over the remote. 

I don't know if this is expected behavior, but it sure is inconvenient. My workaround is to first `conan download <reference>` on the remote, then `conan install <reference>` and `conan upload <reference> -r our-remote` on a client, which updates the recipe and properly creates `conan_sources.tgz`.

If there is a better way of "mirroring" from one remote to another, I'd be quite interested.

conan client 1.3.2, macOS
conan server 1.3.2 (and 0.27; we're mid-migration), Linux

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by mabrowning** [comment]
I've removed `os.remove(tgz_file)` in [remote_manager.py#L370](https://github.com/conan-io/conan/blob/develop/conans/client/remote_manager.py#L370) and that does the trick. It appears that `conan upload` is even smart enough to reuse the existing .tgz (both `conan_export.tgz` and `conan_sources.tgz`) instead of regenerating them.

**Comment by memsharded** [comment]
That means that you are using a conan_server and getting them directly on the storage on the server?
Though it might work, I am not sure it won't be too fragile, as there is no guarantee over changes that could be done to the files, the protocol, the storage... 

Also, I would recommend to use Artifactory CE, which is more powerful.

I will have a look, need to check what could be the side effects of that change. Thanks!

**Comment by mabrowning** [comment]
Correct, I am directly writing into the data directory of `conan_server`. I suppose `conan download <ref> -r conan-center` followed by `conan upload <ref> -r internal --all` would work... with double the disk and network utilization.

What about extending `conan copy` with something like `--remote` and `--destination-remote`? I realize that probably conflates it's existing usage, but it does seem a logical addition.

**Comment by lasote** [comment]
Hi @mabrowning!

> What about extending conan copy with something like --remote and --destination-remote?

I understand the issue and the optimization, but Conan client should be decoupled from any server by using the API. We cannot break this for conan server because it wont't work with Artifactory or any other server/storage implementation.

> I suppose conan download <ref> -r conan-center followed by conan upload <ref> -r internal --all would work... with double the disk and network utilization.

if you are trying to use the server storage directly I assume that you are downloading the packages in the same server machine, right? So about the double disk, if you don't need the packages in the local cache after the "replica" you can clean it. About the network utilization, if it is a local process, the network would be only "loopback" traffic.
