### ISSUE TITLE
Unhandled connection errors in `conan search -r all` 

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#2945]
In cases when one of the remotes on user machine is unreachable (for example local conan server is offline), conan search doesn't proceed to search in other remotes, not prividing any info about remotes that are alive.
```
$ conan search zlib* -r all
ERROR: HTTPSConnectionPool(host='noremote', port=443): Max retries exceeded with url: /v1/conans/search?q=zlib%2A (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x046E1E10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Unable to connect to noremote=https://noremote
```

Proposition: make a handle for such errors to display them (in short form) to the user to indicate an error in their remote network. 
Example:
```
$ conan search zlib* -r all
Existing package recipes:

Remote 'conan-center':
zlib/1.2.8@conan/stable
zlib/1.2.11@conan/stable
zlib/1.2.11@conan/testing
Remote 'noremote':
Unable to connect to noremote=https://noremote
```

**Comment by memsharded** [comment]
Hi @Minimonium 

Actually, this was done on purpose. Initially, the output of the error was exactly the one you are proposing. But we decided to output the "ugly" full error message, because it is very convenient to know what is happening when something is failing in a connection. It helps (also us while doing support), to diagnose which type of error is happening and solve it faster.

Thanks for the feedback, but in this case I think we prefer to keep the full error message. Cheers!

**Comment by Minimonium** [comment]
Hi @memsharded 

I see your point, just to make it clear. With such fix it user may see the problem when using `-r all` and check full message with `-r remote`, but still get the result (even if partial). But if he _knows_ that remote is offline it doesn't break his search. It happened to me, my vm with artifactory was offline and I wanted to quickly look up stuff in other remotes, but I can't do it unless I delete ill remote. Such thing may happen even to official remotes in my country because of IP bans and I think it'd be pretty convenient to not break features just because one of the remotes broke. The user still may have information that something is wrong and can check out the exact error with a direct call to that remote or decide to ignore completely and not remove it from remotes.

I'd appreciate if you'd consider that point, but thanks anyway for the answer!

**Comment by Minimonium** [comment]
To illustrate my point
```
$ conan search zlib* -r all
Existing package recipes:

Remote 'conan-center':
zlib/1.2.8@conan/stable
zlib/1.2.11@conan/stable
zlib/1.2.11@conan/testing
Remote 'unreachable':
Unable to connect to unreachable=https://unreachable
```
```
$ conan search zlib* -r unreachable
ERROR: HTTPSConnectionPool(host='unreachable', port=443): Max retries exceeded with url: /v1/conans/search?q=zlib%2A (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03B05290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Unable to connect to unreachable=https://unreachable
```

**Comment by memsharded** [comment]
I see. If it is for the ``-r=all``, then maybe it could make more sense.

Regarding the error when a remote is unavailable or failing for some reason, it was also on purpose. It used not to fail, and continue with the next remote. But then it happened that was mostly an unwanted behavior, and some users considered it dangerous. If you depend for your builds from packages of certain remotes and they are silently (or printing warning, but in most cases, they are not read) ignored, then worse things could happen, as using outdated packages, using the wrong packages, etc. This is the reasons we prefer to fail, and force the explict ban (removal) of the failing remote. If we add some remote info to the conan-project feature (which we are considering), that could be a different approach that would solve that issue.
