### ISSUE TITLE
[feat req] Add separate Boost libraries

### ISSUE THREAD

**Issue by fmilicchio** [conan-io/conan#2947]
Dear all,

Having a boost package is great, but adding all unnecessary libraries should greatly improve the project payload. 

Is it possible to **split** the boost package into the single boost libraries? Of course, leaving the boost package there, if one just wants to move fast without picking all that is needed. 

Thanks!
    Franco

**Comment by Minimonium** [comment]
You should probably checkout bincrafters, they have plenty of them.

**Comment by memsharded** [comment]
Hi Franco!

Exactly, check the work that bincrafters are doing:
- https://github.com/bincrafters
- https://bincrafters.github.io/

By the way, doing such a modularized version of boost was a ton of work, it is a quite complicated and challenging task. They did an amazing job.

As this is not a conan client issue, I think it can be closed now. Cheers!
