### ISSUE TITLE
ERROR: No JSON object could be decoded

### ISSUE THREAD

**Issue by conradjones** [conan-io/conan#2951]
It looks like there is an issue with conan-center currently. Resulting in this error when running a conan create on a package that has deps.

`ogg/1.3.3@turboit/ogg: Trying with 'conan-center'...
ERROR: No JSON object could be decoded`
It fails to continue to try other remotes and dies.

**Comment by lasote** [comment]
Yes. Sorry. It is under investigation in the Bintray platform.

**Comment by lasote** [comment]
conan-center is working again. Thanks for reporting and your patience.

**Comment by conradjones** [comment]
Hi

My point wasn't that Conan center was down


My point was that Conan cli fails to check any further remotes. I dont use
Conan center yet as it is setup by default by builds were failing with a
cryptic message because of an issue with Conan center (which I don't even
use)

I was filing an issue with the Conan cli program not bintray.

Thanks

**Comment by lasote** [comment]
It is an intended behavior. If a remote in the list fails, the client has to fail. Think in a CI automated process, if you are trying to install the packages in the remote order, and there is an unexpected network error, for example, you don't want the client to ignore it and keep with the next remote, it can produce unexpected results.
If you don't really care about a concrete remote, you should move it down to the remote list or remove it.

**Comment by conradjones** [comment]
I understand your point I have now already added a remove to my Jenkins
pipeline now.

It seems the when executing via the Jenkins plugin it gets added in as I'd
already removed it when building the docker image.

As it is intended behaviour the message could be clearer as it wasn't
immediately obvious that the remote was down.

**Comment by lasote** [comment]
Sure, I agree, the client error should be better. The server was responding in a very very unusual way because of an issue with a redirection. We will try to improve the client error management. Thanks
