### ISSUE TITLE
cppstd in settings.yml was not updated when upgrading to 1.4

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#2958]
I've just upgraded to Conan 1.4 and `settings.yml.new` has this:

    cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17]

I expected to see `20` and `gnu20` there.

**Comment by lasote** [comment]
Yes. It is a bug. Thanks for reporting. Will solve it  in 1.4.1

**Comment by Trass3r** [comment]
I had a similar upgrade problem. Only the .new file contained new entries like VS compiler version 16.
After replacing the old file it worked with VS2019.
