### ISSUE TITLE
Should we update all packages to support GCC 8 and Clang 6,7 ?

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#2960]
To help us debug your issue please explain:

First, I need to finish the PR to provide conangcc8 docker image.

My question is the same did when Apple Clang started to support 9.1.  
Should we update all of our official packages and add both new versions on default travis template?  
I asked here because this will affect our next packages to be submitted on Conan center.

Conan version: 1.4

/cc @solvingj @SSE4 

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I don't think so, until they are not the mainstream compilers included in the distros.

Apple-clang is a different thing, they update the compiler version, so most users are in the latest one.

Just my opinion :)

**Comment by solvingj** [comment]
I agree for now, until we have better automation in place, which I think might be achievable in the next 12 months.  If and when we do get it, it will be a VERY nice thing to be able to provide, but certainly a luxury. 

On the other hand, even if we never get the automation setup to do this, I won't feel too bad about it.  Our mission for CI builds was only to try and cast a wide cross-platform multi-compiler net, and get a reasonable amount of coverage.  I still think we're going way over above in that regard.

**Comment by uilianries** [comment]
Okay, I'm going to keep the same template for Bincrafters CI.

Regards!
