### ISSUE TITLE
Changing scm.subfolder attribute should trigger corresponding update in build dir

### ISSUE THREAD

**Issue by Ri0n** [conan-io/conan#2961]
Conan 1.4.0 on Windows 7

I just played with the new scm feature when faced some unepected behaviour..
I had invalid scm.subfolder name, so I changed it and restarted `conan create  . demo/testing`. It looked  like source checkout stage was just skipped, also I saw the sources checked out into old subfolder. This triggered error of course. 

So I manually cleaned up ~/.conan/data/package_name and then it worked.

**Comment by memsharded** [comment]
I have created a small test:
```python
    def test_change_scm_data(self):
        conanfile = base.format(url="someurl", revision="auto")
        self.client.save({"conanfile.py": conanfile, "myfile.txt": "HelloWORLD!"})
        self._commit_contents()
        self.client.run("create . user/testing")
        print self.client.out
        self.assertIn("HelloWORLD!", self.client.out)
        self.client.save({"conanfile.py": conanfile + "# Just some comment", "myfile.txt": "ByeWORLD!"})
        self.client.run("create . user/testing")
        print self.client.out
        self.assertIn("ByeWORLD!", self.client.out)
```
This test seems to be passing. Changing a recipe removes the source folders in the cache, and then the copy of the sources is triggered again.

So it is working as expected. Could you please verify again?

From your comments:

>It looked like source checkout stage was just skipped, also I saw the sources checked out into old subfolder.

To be sure, conan is not checking out any sources. When you do a conan create, the sources are copied, directly from your user folder (the repo folder), to the local cache, but no git command is invoked. 

All of the above is when using the ``auto`` features to capture the url and commit of the same repository, or are you using it to fetch from external repository?

**Comment by lasote** [comment]
@Ri0n please specify if you are using SCM with "absolute" URL and a commit or with "auto" in any field.

**Comment by lasote** [comment]
I cannot reproduce it either using absolute SCM:

```python
    def test_repeat_clone_changing_subfolder(self):
        tmp = '''
from conans import ConanFile, tools

class ConanLib(ConanFile):
    name = "lib"
    version = "0.1"
    short_paths = True
    scm = {{
        "type": "git",
        "url": "{url}",
        "revision": "{revision}",
        "subfolder": "onesubfolder"
    }}
'''
        path, commit = create_local_git_repo({"myfile": "contents"}, branch="my_release")
        conanfile = tmp.format(url=path, revision=commit)
        self.client.save({"conanfile.py": conanfile,
                          "myfile.txt": "My file is copied"})
        self.client.run("create . user/channel")
        conanfile = conanfile.replace('"onesubfolder"', '"othersubfolder"')
        self.client.save({"conanfile.py": conanfile})
        self.client.run("create . user/channel")
        folder = self.client.client_cache.source(ConanFileReference.loads("lib/0.1@user/channel"))
        self.assertIn("othersubfolder", os.listdir(folder))
```

**Comment by Ri0n** [comment]
I'll try again later today.
The recipe is in github.com/Ri0n/conan-krb5

**Comment by memsharded** [comment]
Ok, please report when you try again.

Regarding the recipe, I am a bit confused about:

```python
def package(self):
        install_dir = os.path.join(self.source_folder, "conan_install")
```

Beware the ``self.source_folder`` when inside the ``build()`` method is pointing to the ``build`` folder in the cache, but if the ``no_copy_source`` attribute is True, then it will be pointing to the ``source`` folder in the cache, that will not have the binaries there. So it makes sense to specify just the relative paths, not the absolute ones in ``self.copy()``, and let conan manage it.

**Comment by Ri0n** [comment]
I just tried again. I don't know what's changed. but now it works.
basically  I changed once again subfolder path and code which relies on this path and it works. kind of magic..

**Comment by memsharded** [comment]
No problem, glad that it is gone, thanks for the follow up!
