### ISSUE TITLE
Confusing message or behavior in SCM when url can't be deduced

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2965]
It raises:

```python
if not origin:
            raise ConanException("Repo origin cannot be deduced by 'auto', using source folder")
```

But it doesn't use the source folder, as execution is aborted. Maybe change the message? Or allow to proceed and create the package locally, even if the remote URL is not defined?

**Comment by lasote** [comment]
I don't think we should proceed, I'm changing the message.
