### ISSUE TITLE
Executable packages ?

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#297]
I couldn't find this information anywhere: is is possible to create and export/upload executable packages, so that such a package could be then be used as a tool in a consuming project, as can be done in CMake with `add_custom_command()` / `add_custom_target()` ?

**Comment by lasote** [comment]
Yes, It should work. In the consuming project/package use the imports section/method to import the name of the executable.

In my cap&proto package I package the generated executables (look at the package method):

https://github.com/lasote/conan-capnproto/blob/release/0.5.3/conanfile.py

Then in the consuming project, imports the executable:

Using conanfile.py
```
 def imports(self):
        self.copy(pattern="*myexe*", dst="bin", src="bin")
```

Using conanfile.txt

```
[imports]
bin, *myexe* -> ./bin # Copies all myexe files from packages bin folder to my "bin" folder
```

Conan is very generic, just export and package the files you need and then import in the consuming project.

**Comment by memsharded** [comment]
You might want to check too:

- https://github.com/memsharded/conan-protobuf/blob/testing/test_package/conanfile.py

**Comment by JPGygax68** [comment]
Thanks guys!

One thing I'm still missing is how to isolate a "tool" dependency from the "build_type" setting. Since the dependency is an executable, there is little point in getting its Debug version. Is there a way to force "Release" for a given dependency ?

**Comment by memsharded** [comment]
Yes, there is, it depends on exactly you want to achieve.
- You can hardcode the release build type in your package. So it will generate always the Release version, and only the Release version. To do this:
   - Remove the ``build_type`` setting from your package conanfile ``settings``
   - Hardcode the Release build type in the ``build()`` method: ``self.run("cmake --build . --config Release")`` for multi-configuration IDEs like Visual, or ``self.run("cmake .. -G "...."  -DCMAKE_BUILD_TYPE=Release")`` for single-configuration environments (like Makefile)
- You can also allow both build_types, leave things as-is, so a debug build of the executable can be done, maybe need to debug at some point. Then, to avoid having more than 1 binary package, you can "narrow" the settings in the conanfile:
```python
def conan_info(self):
        self.info.settings.build_type = "Any"  # Your custom string here
```
  This mean, that no matter if you create the debug or release build, the package will be the same, so when someone depends on your package, both in debug or release modes, they will get the same executable, could be de debug one or the release one, depending on which you uploaded. But it will work, as it is an executable.

Thanks to you! Just tell if this works for you, or do you have other questions.

**Comment by JPGygax68** [comment]
@James: I tried both your methods, and unfortunately, neither really works for me.

First, I should mention that I only exported my dependency; I didn't upload it. This means to have it built on-demand via `--build missing` when consuming it. It is that build step that fails.

The problem with the first proposal appears to be that conan still obtains the wrong version of the dependency's dependency (which happens to be Boost), so that I get linker errors regarding `_ITERATOR_DEBUG_LEVEL` and similar stuff when doing `conan install .. --build missing` on the consumer.

It seems to me that the second option is not a very good idea, as it would amount to mixing packages; and in any case I'd prefer not to upload projects that are not ripe for consumption.

**Comment by memsharded** [comment]
Just to clarify, even if I said "upload" or "uploaded", actually it is not required, everything can be run locally, just "exporting" them to the local storage, without uploading.

About what is failing with the first proposal, I am not sure what is happening. Do you have a full example, or repo, so I could reproduce the problem? If is private, and you don't mind send an invite my user both in bitbucket and github is memsharded

**Comment by JPGygax68** [comment]
I have now upload `gpcfontrasterizer/0.1.1@JPGygax68/testing`.

In theory, you should be able to reproduce the problem using `test_package`, though I haven't tried that. But if not, here's the current conanfile of my consumer:

```
[requires]
Boost/1.60.0@lasote/stable
gpcfontrasterizer/0.1.1@JPGygax68/testing

[imports]
bin, *gpcfontrasterizer* -> ./bin

[generators]
cmake

#[options]
#gpcfontrasterizer:build_type=Release
```

Regarding exporting, I'm a bit unclear about how exactly that relates to (binary) packages. I was under the impression that `export` only ever copies the sources and the recipe?

**Comment by memsharded** [comment]
Hi! 

Yes, kind of, ``export`` copy the recipe and the files that are exported. These files are 99% of times, sources, but there are some users that will add executables there too, and then just move them in the package() step to the final package.

I am trying to build your project, but I am getting some compile errors in https://github.com/JPGygax68/GPCFontRasterizer->rasterizer, I would say not related to conan. I am using VS 2015 Upd2, Win10. At least not related to the issue of executable packages, I think.

I have tried first using your above conanfile.txt, then tried:
1. clone your repo https://github.com/JPGygax68/GPCFontRasterizer
2. Move to rasterizer
3. conan install --build=missing
4. cmake . -G "Visual Studio 14 Win64"
5. cmake --build . --config Release

Then I am getting build errors like
```
C:\Users\memsharded\.conan\data\libGPCFonts\0.1.1\JPGygax68\alpha\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\ gpc/fonts/character_set.hpp(65): error C2672: 'std::max': no matching overloaded function found
```

Are these steps supposed to work? Which setup are you using? Thanks for your feedback

**Comment by JPGygax68** [comment]
Hi James,

thanks for all your efforts, and sorry about the cock-up. It seems you 
have stumbled upon a mistake in my version management (which, 
incidentally, comes from my having to use submodules all over, and makes 
me very, very glad indeed that conan is going to remove that need!).

I'm going to upload the latest version, fixed version of the dependency 
`libGPCFonts` which contains the bug... done. If you `conan install 
--update` now, you should be able to build.

-- Jean-Pierre

**Comment by JPGygax68** [comment]
I just realized I was mistaken!

I think the real cause for the problem is a platform dependency - I'm 
building with x86, so you'll need to use `conan install` with `-s 
arch=x86`, and select "Win32" with CMake!

Sorry about my jumping to conclusions!

(And yes, I will need to fix my type definitions and/or otherwise to 
make this stuff portable.)

**Comment by memsharded** [comment]
No worries! Just tried to install with that, and then I got another error, like freetype existing package is not supported in Windows yet: 
```
freetype/2.6.3@lasote/stable: ERROR: Windows not supported yet. Contact the author on github: github.com/lasote/conan-freetype
```
I have submitted an issue to the package creator: https://github.com/lasote/conan-freetype/issues/1

So when I try to build the project, it is throwing an (expected) freetype.lib not found error. Are you sure you were able to build this without this error?

**Comment by JPGygax68** [comment]
Sorry about this. Yes, I was able to build, but that may have been 
because I had built FreeType on my own on my system. I dimly remember 
having seen some red-colored output, but I didn't pay it any more 
attention because I was able to build anyway. In any case, `conan 
install` now fails with exactly the error message that you got.

Unless you'd like with a pre-built, non-conan FreeType package 
(http://gnuwin32.sourceforge.net/packages/freetype.htm), I suggest you 
put this on hold until the conan FreeType package becomes 
Windows-capable. If the package author has no time, I might try to give 
it a go myself.

**Comment by JPGygax68** [comment]
Sorry about this. Yes, I was able to build, but that may have been 
because I had built FreeType on my own on my system. I dimly remember 
having seen some red-colored output, but I didn't pay it any more 
attention because I was able to build anyway. In any case, `conan 
install` now fails with exactly the error message that you got.

Unless you'd like to try with a pre-built, non-conan FreeType package 
(http://gnuwin32.sourceforge.net/packages/freetype.htm), I suggest you 
put this on hold until the conan FreeType package becomes 
Windows-capable. If the package author has no time, I might try to give 
it a go myself.

**Comment by memsharded** [comment]
Hi again!

I have done some PRs to the conan freetype package, now it has some basic support for Windows. Only the static version, as the freetype library does not support shared in Win. It also builds in Linux, still failing in OSX (to-do)

The package would be: freetype/2.6.3@lasote/ci, I think it can be very useful for your build.

If you try it, please give feedback. Cheers!

**Comment by JPGygax68** [comment]
Thanks James,
FreeType now builds (using `--build missing`), but when I try to link it with my rasterizer utility, I get PNG-related error messages, such as:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _png_create_read_struct referenced in function _Load_SBit_Png	gpcfontrasterizer	d:\Projects\GPC\FontRasterizer.new\rasterizer\build\freetype.lib(sfnt.obj)	1	
```
There's a total of 27 such linker errors, most of them PNG-related and 3 last ones related to BZ2.

**Comment by JPGygax68** [comment]
Update: I made the linker errors go away by adding
```
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```
to my `CMakeLists.txt`. Previous I was only linking with individual libraries such as `${CONAN_LIBS_FREETYPE}`.

**Comment by JPGygax68** [comment]
I've now uploaded a new version of my package that links with your updated FreeType package. You can consume it as `gpcfontrasterizer/0.1.2@JPGygax68/testing`.

**Comment by JPGygax68** [comment]
The updated FreeType package did not solve the original problem. Trying `conan install` in my consumer build directory still says:
```
ERROR: Can't find a 'gpcfontrasterizer/0.1.2@JPGygax68/testing' package for the specified options and settings

- Try to build from sources with "--build gpcfontrasterizer" parameter
- If it fails, you could try to contact the package author  at 'https://github.com/JPGygax68/GPCFontRasterizer.git', report your configuration and try to collaborate to support it.

Package configuration:
- Settings: arch=x86, compiler=Visual Studio, compiler.runtime=MD, compiler.version=14, os=Windows
- Options: Boost:header_only=False, Boost:shared=False, bzip2:fPIC=True, bzip2:shared=False, freetype:fPIC=True, freetype:shared=False, libpng:shared=False, zlib:shared=False
```
When I add `--build missing`, the build of `gpcfontrasterizer` fails because it tries to link with the debug builds of Boost, which are not compatible with the debug build of `gpcfontrasterizer` because the CMake configuration provided by Conan for debug builds includes the definition `-DCONAN_LINK_RUNTIME=/MD`, while the debug builds of Boost are compiled for the "Runtime Debug DLL" (/MDd).

**Comment by memsharded** [comment]
Happy that freetype worked, now it seems it is the typical runtime mistmach. I might be able to have a look at it tomorrow., thanks for telling!

**Comment by memsharded** [comment]
Don't know what it is happening, but I was able to build gpcfontrasterizer successfully!

1. $ git clone https://github.com/JPGygax68/GPCFontRasterizer
2. $ cd rasterizer
3. change in "conanfile.py" ``freetype/2.6.3@lasote/freetype`` => ``freetype/2.6.3@lasote/c``
4. add in CMakeLists.txt ``target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})``
5. $ mkdir build && cd build
6. $ conan install .. --build=missing -s arch=x86
7. $ cmake .. -G "Visual Studio 14"
8. $ cmake --build . --config Release
9. .\bin\gpcfontrasterizer.exe
Error: No font file specified!

Could you please check it? Thank you!

**Comment by JPGygax68** [comment]
Thanks James, but the Release build was already working!

The problem comes when trying to get conan to get/build the Release build of the executable (gpcfontrasterizer) when `conan install` is being run on the consumer with `-s build_type=Debug`.

I verified just now that gpcfontrasterizer does get built correctly when the consumer is being installed for Release.

**Comment by JPGygax68** [comment]
CORRECTION: the conan-install on the consumer *does* work, even with `build_type=Debug`, after I've done `conan export` on the current version of `gpcfontrasterizer`.

**Comment by JPGygax68** [comment]
There is one problem still though: the conan-install in the "debug" build directory of the consumer will only work if I've previously done the same thing in a "release" build directory, otherwise it will try to build gpcfontrasterizer from the source, and fail for the usual reason.

In fact, I'm now noticing that I cannot seem to upload any binary package.

**Comment by memsharded** [comment]
Ups sorry, I didn't realize it was the debug build. Will check it now again.

**Comment by memsharded** [comment]
I think I am starting to understand the issue:
- The upload problem should be a different issue, permissions, or you forgot the "--all" (to instruct to upload all the binary packages, otherwise it will upload only the package recipe). Please post your commands and the output, and I will try to help.
- About the usage of the executable, I'd say that it probably deserves a "private" dependency, or as soon as they are available, the "scopes" feature. If I understood properly, you are building such gpcfontrasterizer.exe that you need in the "build" step of another application to do some task. Is that right? I have to understand some things then:
   - Is the IO of gpcfontrasterizer different from different versions? Why no consider it as a dev-tool, similar to git, use conan install to install/build it, have it available for other developments
   - Is it generating source code or data to be included in another project? Is it necessary only at build time? 
   - I guess it has common dependencies to the rest of the project, that is why there might be happening some interactions. Private dependencies might fix it, but also might increase build time if versions diverge (Gpcrasterizer could be using a different Boost version than the consumer project)
I think with this answers we could outline a proper solution, thanks again for your feedback!

**Comment by JPGygax68** [comment]
Thanks James,

- I didn't forget the `--all` parameter. In fact, that whole problem seems to hang on the fact that the output binary doesn't get packaged. I tried to modify the copy command in the package section to `   self.copy("bin/*.exe", dst="bin")`, but no luck. The binary gets built, but I can't seem to do anything with it. The command `conan package gpcfontrasterizer/0.1.2@JPGygax68/testing --all` fails with `ERROR: gpcfontrasterizer/0.1.2@JPGygax68/testing does not exist`.
- You are quite right on the use of gpcfontrasterizer: it is in fact a code-generating tool, intended to be integrated into the build process rather than being executed manually. (Well actually it doesn't generate code by itself, that job is done by another tool which takes the file generated by gpcfontrasterizer as its input.)
- If there are common dependencies with the rest of the project, that is quite by accident. As a command-line tool, it is supposed to stand on its own.

Regarding build times, that could of course become a problem, especially with the monster that is Boost. In fact, I meant to ask whether Conan supports the idea of "components" in any way. It would be great to be able to have Conan fetch/build only those components of Boost that the project actually requires.

(On the other hand though, the author of NPM, Isaac Schlueter, has made a strong case against big libraries and in favor of small, atomic ones. Perhaps it would be possible to split Boost up into its individual components ? Though that would be a herculean task without full support from the Boost project itself.)

**Comment by memsharded** [comment]
Just a word of caution, the command ``conan package`` should be rarely used. It executes just a part of the ``install`` which is the ``package()`` method, but without the build. It is intended as an optimization for package creators that construct very heavy packages and have to debug the creation of the package. For it to work, such  package has to be in the local conan storage, not the current consumer project. The ideal case is with ``conan test_package``. I suggest not using, and using ``conan install`` instead if not clear or facing problems.

Please also make sure that you did ``conan export`` after the changes in the conanfile, it is very typical to forget it (I do, so I have submitted an issue to improve this).

I think the best could be to automate the creation and testing of the package with the ``test_package`` feature, and as a "private" dependency. Even if there is possibility to build 2 times boost, it can be managed to not do it, so it will be fine. Just know that with private dependencies you will have 2 different dependencies of Boost in your project. They might match, but they might not. The most obvious example is yours: 
- The gpcrasterizer will be generated Release only. So it will depend on Boost Release
- Your project is built in Debug mode, so it will use Boost-Debug. 
There are only 2 options here:
- You need 2 different Boost builds, one debug and one release (with "private" dependency)
- You have 1 Boost build, the one for your project, but then gpcrasterizer needs to be built to match the project settings (no "private" dependency). 

I would say that I'd tend to prefer the second one, specially if the tool itself is not large and thus slow to build, but I think I might try to help with it tomorrow with the other one, the "private" one, if you want I can try to make a PR with it.

Yes, the Boost modularization is a recurrent topic in Boost, but without the Boost community really involved, it would be very difficult and worthless. Without being done as a Boost community effort, it will go nowhere. And it is unlikely that they will do it i the short term.

**Comment by JPGygax68** [comment]
Aha! After creating and executing a `test_package`, I was finally able to upload a package!

**Comment by JPGygax68** [comment]
After a few more adjustments, the executable now lands in the right subdirectory of the consumer project (at least I think it's the right spot), i.e. in `<build_dir>/bin` (`<build_dir>` being the CMake build directory).

**Comment by JPGygax68** [comment]
Here's the file I added to the project `libCppGUI`, which is the consumer of `gpcfontrasterizer` but is itself a submodule and therefore needs to have its dependencies managed by the root project:

```CMake
# This file makes dependencies obtained via the Conan package manager available to CMake.
# It is intended to be include()'ed from the top-level CMakeLists.txt of a consuming project.

# The GPC Font Rasterizer is needed to pre-rasterize fonts
add_executable(gpcfontrasterizer IMPORTED)
set_target_properties(gpcfontrasterizer PROPERTIES 
  IMPORTED_LOCATION "${CMAKE_BINARY_DIR}/bin/gpcfontrasterizer"   # find it in the default subdirectory for Conan-imported binaries
)
```

The `CMakeLists.txt` of the root project now simply does:
```CMake
include(submodules/libCppGUI/ConanDeps.cmake)
```
I'm now closing this request, with my thanks, but of course any additional thoughts would be welcome.

**Comment by memsharded** [comment]
Fantastic news! Glad to know that finally it worked.
I think that it is OK, I guess you have finally not used private, thus re-building gpcfontrasterizer for different settings if necessary, but IMO that will be ok.
Just push it to github if you want and I will have a last view to try to provide additional thoughts.

Thanks very much to you, for using conan, and giving feedback. We will continue to be here to provide help, just open issues or contact us.

**Comment by JPGygax68** [comment]
My apologies! I did indeed use private packages, I just forgot to commit&push my latest version.

For reference, here's the current conanfile of the `gpcfontrasterizer`:

```Python
from conans import ConanFile, CMake

class GPCFontRasterizerConan(ConanFile):
  name = "gpcfontrasterizer"
  version = "0.1.2"
  url = "https://github.com/JPGygax68/GPCFontRasterizer.git"
  settings = "os", "compiler", "arch" #, "build_type"
  requires = (("freetype/2.6.3@lasote/ci", "private"), 
              ("Boost/1.60.0@lasote/stable", "private"),
              ("libGPCFonts/0.1.1@JPGygax68/alpha", "private"),
              ("cereal/0.1@JPGygax68/testing", "private"))
  generators = "cmake"
  exports = "main.cpp", "CMakeLists.txt", "cmake"
  default_options = "Boost:shared=False"
  
  def config(self):
    self.settings.compiler["Visual Studio"].remove("runtime")
    
  def build(self):
    cmake = CMake(self.settings)
    self.run("cmake %s %s" % (self.conanfile_directory, cmake.command_line))
    self.run("cmake --build . --config Release")

  def package(self):
    # TODO: equivalent for non-Windows ?
    self.copy("*.exe", dst=".")

  def conan_info(self):
    self.info.settings.build_type = "Release"  # This is an executable tool, build type does not matter
```
