### ISSUE TITLE
Add support to RTOS to default settings.yml

### ISSUE THREAD

**Issue by jpovedano** [conan-io/conan#2970]
Support new os_targets in settings.tml to cross compile for RTOS:
- VxWorks
- Integrity
- LynxOS
- QNX

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi! Thanks for your contribution, nevertheless I'm not sure if these additions are general enough for the community. We try to keep the `settings.yml` generic enough for the general purpose. 
You can use `conan config install` command to install a custom `settings.yml` and the rest of the conan client configuration. 
Would be nice to receive more feedback about the RTOS settings.

**Comment by memsharded** [comment]
Yes, specially because it is avery likely that you will also have profiles for those configurations, and the ``conan config install`` will both update your custom settings.yml, and also install the same profiles for the developers and CI

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2 with the addition of the [`settings_user.yml` feature](https://docs.conan.io/2/reference/config_files/settings.html#settings-user-yml) that allows appending data to Conan's `setting.yml` file for each user, which can also be handled with `conan config install` in a non-destructive way

A different issue is if integrations like ``CMakeToolchain`` need to be aware of some specific OS, to customize some behavior. In that case, it would be necessary to create a new ticket reporting that against ``CMakeToolchain`` (or other integration), assuming the ``setting`` is already defined in ``settings_user.yml``
