### ISSUE TITLE
Error while trying to get recipe sources for <PACKAGE> No remote defined.

### ISSUE THREAD

**Issue by hamparawa** [conan-io/conan#2972]
Hi,
I am receiving frequent errors with the following message when I am trying to install a package.
```
ERROR: Error while trying to get recipe sources for MyPackage/0.1.0@demo/testing. No remote defined
```
But when I have checked whether the package exists in the remote using following command,

```
conan search -r server MyPackage/0.1.0@demo/testing
```
It returns,
```
There are no packages for reference 'MyPackage/0.1.0@demo/testing', but package recipe found.
```

When looking at the conan source, seems like the problem originates from [here](https://github.com/conan-io/conan/blob/develop/conans/client/source.py#L32)

```
    # If not path to sources exists, we have a problem, at least an empty folder
    # should be there
    current_remote = registry.get_ref(conan_reference)
    if not current_remote:
        raise ConanException("Error while trying to get recipe sources for %s. "
                             "No remote defined" % str(conan_reference))

```
But when I look at the ~/.conan/registry.txt, it only contains the following line.

```
server http://192.168.8.100:9300 True
```

I guess conan expects this file to contain the recipes mapped into their respective remote in this file. 
As a workaround, I can manually add the recipe to the file using following command.

```
conan remote add_ref MyPackage/0.1.0@demo/testing server
```
Then it seems to work fine for a while, but then the error pops up after some time. Any ideas of what causes this issue?
Thanks,

I have tested with Conan 1.4.0.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi!

A few quick questions:
- What server are you using, Artifactory or conan_server? I'd recommend the first one
- Are you manually removing the conan local cache or something related to the ".conan" folder or the registry file that could be removing it?
- Are you adding and removing remotes? Or are the remotes always the same? The moment you remove a remote, it is dissasociated, if it didn't retrieve the sources, it won't be able to do it once disconnected.
- Did you remember to ``upload --all`` the binaries to your server?

Please try to describe a detailed flow of commands that allows reproducing this error. Thanks!

**Comment by hamparawa** [comment]
Hi,
> What server are you using, Artifactory or conan_server? I'd recommend the first one

I am using conan_server with gunicorn.

> Are you manually removing the conan local cache or something related to the ".conan" folder or the registry file that could be removing it?

No. But I have found that removing the whole data folder can suppress the issue for a while.

> Are you adding and removing remotes? Or are the remotes always the same? The moment you remove a remote, it is dissasociated, if it didn't retrieve the sources, it won't be able to do it once disconnected.

I am removing the default remotes at the beginning and add only my remote. Once setup, I do not modify any remotes. This removing and adding is done through a python script which calls the conan python API. I also modify the default settings using `conan config install`.

> Did you remember to upload --all the binaries to your server?

Only for some packages I use --all when uploading. For the others, I only require the recipe to be managed by the conan server.

**Comment by memsharded** [comment]
Conan config install if using a remotes.txt file, will overwrite/modify the existing remotes. Did you do it in the middle of operation?

I can't reproduce it, it would be necessary to come up with a sequence of commands that reproduce it. You can easily use ``conan new Pkg/0.1 -s`` to create a package, etc. Looking forward your feedback, many thanks!

**Comment by hamparawa** [comment]
Hi, 
> Conan config install if using a remotes.txt file, will overwrite/modify the existing remotes. Did you do it in the middle of operation?

In my config zip file, only settings.yml is included. This includes RelWithDebInfo setting (now obsolete) and glibc setting.

I haven't been able to reproduce with simple command chain, but will try to do it.

Do you think this has anything to do with proxy caching? My server runs through a proxy server.

**Comment by memsharded** [comment]
Ok, then you are good with ``conan config install``.

I don't think it is a proxy thing, but I'd say it could be a flow issue. Please report if you manage to reproduce.

**Comment by hamparawa** [comment]
Hi,
I have faced the issue again, and this time I have enabled client logs.
First, the failed request.

```
{"_action": "COMMAND", "name": "install", "parameters": {"build": ["missing"], "env": null, "generators": null, "install_folder": null, "manifests": null, "manifests_interactive": null, "no_imports": false, "options": null, "path": "..", "profile_name": null, "remote": null, "settings": null, "update": false, "verify": null}, "time": 1529646324.8069696}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "project_b/0.1.0@demo/testing", "time": 1529646324.8423386}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "project_c/0.1.0@demo/testing", "time": 1529646324.8453753}
{"_action": "REST_API_CALL", "duration": 0.04269719123840332, "headers": {"Authorization": "**********", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.4.4"}, "method": "GET", "time": 1529646324.8917463, "url": "http://conan.myserver.local:9300/v1/conans/project_a/0.1.0/demo/testing/download_urls"}
{"_action": "EXCEPTION", "class": "NotFoundException", "message": "Unable to find 'project_a/0.1.0@demo/testing' in remotes", "time": 1529646324.934534}
```

And I have waited for few minutes, and executed the command again. Then it worked!

```
{"_action": "COMMAND", "name": "install", "parameters": {"build": ["missing"], "env": null, "generators": null, "install_folder": null, "manifests": null, "manifests_interactive": null, "no_imports": false, "options": null, "path": "..", "profile_name": null, "remote": null, "settings": null, "update": false, "verify": null}, "time": 1529646910.4017427}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "project_b/0.1.0@demo/testing", "time": 1529646910.4351997}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "project_c/0.1.0@demo/testing", "time": 1529646910.43808}
{"_action": "REST_API_CALL", "duration": 3.343946933746338, "headers": {"Authorization": "**********", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.4.4"}, "method": "GET", "time": 1529646913.7855525, "url": "http://conan.myserver.local:9300/v1/conans/project_a/0.1.0/demo/testing/download_urls"}
{"_action": "DOWNLOAD", "duration": 0.04118680953979492, "time": 1529646913.8274527, "url": "http://conan.myserver.local:9300/v1/files/project_a/0.1.0/demo/testing/export/conanmanifest.txt?signature=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlc2l6ZSI6bnVsbCwidXNlcm5hbWUiOm51bGwsInJlc291cmNlX3BhdGgiOiJuZXR3b3JrLzAuMjMuMC9tdGVjaC90ZXN0aW5nL2V4cG9ydC9jb25hbm1hbmlmZXN0LnR4dCIsImV4cCI6MTUyOTY1MDQ3N30.lh4d7rGIeAh8j2XNvhe0e6Dm9X8DVWUJzYrH2YWa3R0"}
{"_action": "DOWNLOAD", "duration": 0.12570714950561523, "time": 1529646913.953478, "url": "http://conan.myserver.local:9300/v1/files/project_a/0.1.0/demo/testing/export/conanfile.py?signature=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlc2l6ZSI6bnVsbCwidXNlcm5hbWUiOm51bGwsInJlc291cmNlX3BhdGgiOiJuZXR3b3JrLzAuMjMuMC9tdGVjaC90ZXN0aW5nL2V4cG9ydC9jb25hbmZpbGUucHkiLCJleHAiOjE1Mjk2NTA0Nzd9.tD-uX2-atTiS6tkzM-mo6NiFNunAW6N8UQx9B5zJ4gA"}
{"_action": "DOWNLOADED_RECIPE", "_id": "project_a/0.1.0@demo/testing", "duration": 3.5123462677001953, "files": [{"md5": "5d6fefada192e9850f794e030754e423", "name": "conanmanifest.txt", "path": "/home/hamparawa/.conan/data/project_a/0.1.0/demo/testing/export/conanmanifest.txt", "sha1": "9c7776843d83282164e779f20a06174cb4928ad3"}, {"md5": "bba6e5d2b2d1a0020d9deda2e6998c33", "name": "conanfile.py", "path": "/home/hamparawa/.conan/data/project_a/0.1.0/demo/testing/export/conanfile.py", "sha1": "2f541a983371ec380eb75787bd11122172cbd862"}], "remote": "myremote", "time": 1529646913.9539251}
```

Any idea on this? 
Thanks!

**Comment by hamparawa** [comment]
No. The only thing happened in between was couple of sips of coffee. 😄 
I am investigating whether this happens due to my proxy server. Will update if found anything.
Thanks!

**Comment by herman-nu** [comment]
Hi @hamparawa, did you happen to figure out the root cause of this issue?

**Comment by hamparawa** [comment]
Apparently the issue was the proxy server caching. After bypassing the proxy server, the issue never came again. Thanks!
