### ISSUE TITLE
[bug/feature request] conan remove with query doesn't support pattern matching

### ISSUE THREAD

**Issue by ArekPiekarz** [conan-io/conan#2977]
**Summary**
Using `conan remove` with a query states that "*" pattern can be used to remove all packages - I assume all matching the query. However using that pattern fails and requires specifying a full reference.

**Motivation**
A user installs a new version of a compiler. He checks if all the packages he is using still can be built properly with it. Assuming he succeeds, he then wants to remove the packages compiled with the older tool. The last step of this scenario is not possible to easily perform with a single invokation of `conan remove`.

**Steps to reproduce**
```
$ conan remove -q compiler.version=7
ERROR: Please specify a pattern to be removed ("*" for all)
$ conan remove "*" -q compiler.version=7
ERROR: -q parameter only allowed with a valid recipe reference as search pattern. e.g conan search MyPackage/1.2@user/channel -q "os=Windows"
```

**Environment**
Conan 1.4.1
Ubuntu 18.04
(all 64-bits)

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
This has been fixed in Conan 2.0, something like ``conan remove *:* -p os=Linux`` now works, closing this ticket
