### ISSUE TITLE
Bullseye coverage integration .. need your help

### ISSUE THREAD

**Issue by RReymann** [conan-io/conan#2980]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi Guys,
I am currently thinking about the best way for integrating Bullseye Coverage (www.bullseye.com) with Conan by using the cmake generator. In view words, bullseye is a C++ code coverage analyzer and there are 3 different ways for integrating it into a given build tool (http://www.bullseye.com/help/build-integration.html). 

My raw idea was to declare this tool like  a "build_require" but I did not find any way for successfully implementing one of the 3 integration solutions mentioned previously.
Any help will be welcomed ...

Cheers
Renaud

**Comment by memsharded** [comment]
Hi @RReymann 

This looks interesting. 
However, it seems the integration should be done at the build-system level, and there is little that conan can do besides installing the build rquirement, and injecting the path wherever necessary.

It would be very useful to have an example CMakeLists.txt script working with bullseye, but unfortunately, I can't find any in http://www.bullseye.com/help/index-platform.html. If you are a customer of Bullseye, maybe ask their support for guidance?

**Comment by RReymann** [comment]
Hi,

Unfortunately, they have no expertise with cmake  :-(.
So far, I tried the following integration:

1. env PATH modification:
Currently Bullseye location must be in first position in env PATH, But I did not find a nice way for doing that in conanfile.py.

2. CMakefile.txt integration;
The second way is to do all the stuff in CMakelist.txt as you mentioned it. 
Here is one of my unsuccessful tries with cmake 

`include(FindPackageHandleStandardArgs)

#Find bullseye executables first
set(BULLSEYE_PATH "C:/ProduitsTiers/BullseyeCoverage/version-8.10.10/bin")
find_program(BULLSEYE_CC
                NAMES "cl.exe" 
                PATHS ${BULLSEYE_PATH} 
                NO_DEFAULT_PATH
            )
find_program(BULLSEYE_COV_ENABLE 
                NAMES "cov01.exe" 
                PATHS ${BULLSEYE_PATH} 
                NO_DEFAULT_PATH
            ) 

#This will go ahead and find the programs, if it cant find, it will report error
find_package_handle_standard_args(BULLSEYE DEFAULT_MSG BULLSEYE_CC BULLSEYE_COV_ENABLE)

#Set the CMake compiler to bullseye compiler.
#This is important as Bullseye (behind the scenes) will invoke the original preferred compiler after its own book-keeping.
set(CMAKE_CXX_COMPILER "${BULLSEYE_CC}")

#Enable coverage
set(RES 1)
execute_process(COMMAND ${BULLSEYE_COV_ENABLE} --on RESULT_VARIABLE RES)
message("Bullseye coverage has been enabled ${RES}")
if(RES)
  message(FATAL_ERROR "could not enable bullseye")
endif(RES)


#Build your binaries as before
#when you generate unit test executable, bullseye will automatically find its own linker 
#which will be in the save directory as its compiler
#Note: It is important that bullseye knows where your preferred C++ compiler is. For that
#I would say, add compiler to path.`

But set CMAKE_CXX_COMPILER in CMakefile.txt file should be avoided. Passing such overloading by parameter (with -D xx) should be better but how can i do that with conan ?

Cheers,
Renaud

**Comment by memsharded** [comment]
This issue is a bit outdated, sorry that we didn't follow up back then.

A lot of things have changed since then:

- tools.build:compiler_executables allows to define paths to compilers and that is injected to the build systems
- Conan 2.0 features a ``cmd_wrapper`` plugin that can intercept ``self.run()`` calls and inject their own logic
- The Conan profiles are more powerful, allowing jinja templates, having arbitrary flags via ``tools.build:cxxflags`` etc.

I am closing this as outdated, but please don't hesitate to create a new ticket for further questions if necessary.
