### ISSUE TITLE
AutoToolsBuildEnvironment doesn't find dependencies when using Windows Bash

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan#2982]
Conan version: 1.4
OS: Windows 10, version 1803, build 17134.1, Windows subsystem for Linux installed (openSuse)

I tried to build the following recipe:
https://github.com/wdobbe/conan-graphicsmagick.git

On Linux the (autoconf) configure script of GraphicsMagick finds the libjpeg and libpng that Conan installed. However on Windows both libjpeg and libpng are not detected. (Note that the configure script will not complain too hard about this, and compilation will start anyway).

When I open a windows bash prompt myself, set CPPFLAGS and LDFLAGS to the locations where Conan installed libjpeg and libpng and then run the configure script, it does detect both libraries.

So it looks like the CPPFLAGS and LDFLAGS environment variables that are set up by AutoToolsBuildEnvironment are not picked up by the configure script.

**Comment by wdobbe** [comment]
The command that Conan executes is this:

`Project: run_in_windows_bash: C:\WINDOWS\system32\bash.exe --login -c ^"cd \^"/mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/build\^" ^&^& /mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/source/GraphicsMagick-1.3.29/configure --enable-shared=yes --enable-static=no --with-bzlib --with-jpeg --with-png --without-dps --without-fpx --without-jbig --without-jp2 --without-lcms2 --without-lzma --with-magick-plus-plus --without-perl --without-trio --without-webp --without-wmf --with-zlib --prefix=/mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/package --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32  ^"`

When I execute commands myself with 'bash -c' I notice that environment variables are easily lost, for example the following command:

`export LDFLAGS=blabla; echo LDFLAGS are $LDFLAGS
`
gives output

`LDFLAGS are`

**Comment by memsharded** [comment]
Verified, this seems to be a real issue.

**Comment by wdobbe** [comment]
Look at the output of the following python 3.6 commands:

on Windows:
```
>>> os.environ['BLABLA'] = "Elvis is alive!"
>>>
>>> proc = subprocess.Popen(["cmd", "/c", "echo blabla=%BLABLA%"], stdout=subprocess.PIPE, shell=True)
>>> stdout_val = proc.communicate()[0]
>>> print(stdout_val)
b'blabla=Elvis is alive!\r\n'
>>>
>>> proc = subprocess.Popen(["bash", "-c", "echo blabla=${BLABLA}"], stdout=subprocess.PIPE, shell=True)
>>> stdout_val = proc.communicate()[0]
>>> print(stdout_val)
b'blabla=\n'
>>>
```

The same on Linux:
```
>>> os.environ['BLABLA'] = "Elvis is alive!"
>>> proc = subprocess.Popen(["/bin/bash", "-c", "echo blabla=${BLABLA}"], stdout=subprocess.PIPE, shell=False)
>>> stdout_val = proc.communicate()[0]
>>> print(stdout_val)
b'blabla=Elvis is alive!\n'
```

So Windows bash is completely ignoring the environment variables that are set in os.environ (or passed with the env parameter of Popen), while Windows cmd and Linux bash do pick up the enviroment variables.

**Comment by wdobbe** [comment]
And finally on Windows msys bash also behaves nicely:
```

>>> os.environ['BLABLA'] = "Elvis is alive!"
>>> proc = subprocess.Popen(["/bin/bash", "-c", "echo blabla=${BLABLA}"], stdout=subprocess.PIPE, shell=False)
>>> stdout_val = proc.communicate()[0]
>>> print(stdout_val)
b'blabla=Elvis is alive!\n'
```

**Comment by wdobbe** [comment]
Apparently a known  'feature':

https://github.com/Microsoft/WSL/issues/219

https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/

With the instructions in the last link, Windows bash now also sees the BLABLA variable:

```
>>> os.environ['WSLENV'] = "BLABLA"
>>>
>>> proc = subprocess.Popen(["bash", "-c", "echo blabla=${BLABLA}"], stdout=subprocess.PIPE, shell=True)
>>> stdout_val = proc.communicate()[0]
>>> print(stdout_val)
b'blabla=Elvis is alive!\n'
```

**Comment by wdobbe** [comment]
So when Conan detects that subystem=='WSL' it should set environment variable WSLENV to all the environment variables that should be inherited by Windows bash.

**Comment by lasote** [comment]
Hi, I was trying to solve this issue in a generic way at #3104 passing the env vars in the mentioned WSLENV, but I have a question. According to what I read [here](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/) you should indicate if the specified variable is a path, a list of paths and so on, so you let WSL know if any transformation of the path has to be done.

My question is, the variables that `AutotoolsBuildEnvironment` is adjusting, like `LDFLAGS` contains mixed stuff separated by a comma, also containing paths. But not only paths. In your experience, is it working?

**Comment by wdobbe** [comment]
Hi. In the simple fix I committed (d867625cc9cb66a3442e563646e0143b0da44761) to make this work, the paths in CPPFLAGS, LDFLAGS etc. were already transformed to WinBash paths by Conan. So I didn't append any flags to the environment variable names because no transformation was needed.

I tested the fix with my graphics-magick recipe and it works. Note that the graphics-magick configure script will not complain very hard when dependend libraries are not found and start to build anyway, so you have to look at the summary that is printed when the configure step finished. If libpng and libjpeg are found than the WSLENV fix is working.

If you have more questions let me know.

**Comment by wdobbe** [comment]
I tested the Feature/wsl_env_vars branch of your conan fork. Unfortunately the configure step of graphicsMagick fails because it cannot find grep:

```
C:\Users\wdobbe\generated\conan-graphicsmagick>python c:\Users\wdobbe\opensource\conan_forks\conan\conan.py build . --source-folder=tmp\source --install-folder=tmp\build --build-folder=tmp\build --package-folder=tmp\package
Project: Running build()
Project: Calling:
 > /mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/source/GraphicsMagick-1.3.30/configure --enable-shared=yes --enable-static=no --with-bzlib --with-jpeg --with-png --without-dps --without-fpx --without-jbig --without-jp2 --without-lcms2 --without-lzma --with-magick-plus-plus --without-perl --without-trio --without-webp --without-wmf --with-zlib --prefix=/mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/package --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32
Project: run_in_windows_bash: C:\WINDOWS\system32\bash.exe --login -c ^"cd \^"/mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/build\^" ^&^& /mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/source/GraphicsMagick-1.3.30/configure --enable-shared=yes --enable-static=no --with-bzlib --with-jpeg --with-png --without-dps --without-fpx --without-jbig --without-jp2 --without-lcms2 --without-lzma --with-magick-plus-plus --without-perl --without-trio --without-webp --without-wmf --with-zlib --prefix=/mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/package --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32  ^"
Project: /etc/profile: line 137: grep: command not found
Project: configuring GraphicsMagick 1.3.30
Project: checking build system type... x86_64-w64-mingw32
Project: checking host system type... x86_64-w64-mingw32
Project: checking whether build environment is sane... yes
Project: checking for a BSD-compatible install... /usr/bin/install -c
Project: checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
Project: checking for gawk... gawk
Project: checking whether make sets $(MAKE)... yes
Project: checking whether make supports nested variables... yes
Project: checking whether make supports nested variables... (cached) yes
Project: checking for style of include used by make... GNU
Project: checking for x86_64-w64-mingw32-gcc... C:/Users/wdobbe/.conan/data/mingw_installer/1.0/conan/stable/package/b2a5c106cd30b29d475da50a9633d31c2329d6bd/bin/gcc.exe
Project: checking whether the C compiler works... no
Project: configure: error: in `/mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/build':
Project: configure: error: C compiler cannot create executables
Project: See `config.log' for more details
Project: run_in_windows_bash: C:\WINDOWS\system32\bash.exe --login -c ^"cd \^"/mnt/c/Users/wdobbe/generated/conan-graphicsmagick/tmp/build\^" ^&^& make -j4 ^"
Project: /etc/profile: line 137: grep: command not found
Project: make: *** No targets specified and no makefile found.  Stop.
ERROR: GraphicsMagick/1.3.30@PROJECT: Error in build() method, line 80
        env_build.make()
        ConanException: Error 2 while executing make -j4
```

With my own fork the configure step succeeds.

**Comment by lasote** [comment]
Ok, thanks.

**Comment by memsharded** [comment]
AutotoolsBuildEnvironment has been deprecated and replaced in 1.X some time ago, and removed in 2.0, closing this ticket as outdated.
