### ISSUE TITLE
[question] Example of cross building with native binary tools for code generation?

### ISSUE THREAD

**Issue by drmacdon** [conan-io/conan#2986]
I am cross building for another host platform (Android) and using protobufs. During compilation, I would like to run protoc on the build platform to generate the code to be compiled for the host platform.

Does this need to be done as two separate build invocations - ie. one to generate the code using build platform tooling and one to compile for the host platform?  

Looking for a sample of how a project could be constructed to do code generation using native binaries on host or confirmation it needs be done with multiple invocations. 

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by drmacdon** [comment]
Closing. WIll follow #2301 which is a similar issue.

**Comment by memsharded** [comment]
Thanks for following up in #2301 

Maybe the possible approach in this case is to separate:
- Have a "protoc" package that doesn't depend on "protobuf". Use the "protoc" package as build_require in the build platform. The "protoc" package will have ``os_build, arch_build`` settings (no need to have compiler or build_type settings, typically).
- Have the normal "protobuf" package with ``os, compiler, arch...`` settings for the host.

**Comment by drmacdon** [comment]
Thanks for the pointer. That worked!

It inherits the profile CONAN_CMAKE_TOOLCHAIN_FILE which I strip from the cmake definition of this specific protoc conanfile.py in a slightly ugly way but it works.

```
cmake = CMake(self)
if len(cmake.definitions["CMAKE_TOOLCHAIN_FILE"]) > 0 and not tools.cross_building(self.settings):
    cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = ""
cmake.configure(build_folder=build)
cmake.build()
```
