### ISSUE TITLE
During export-pkg, config_options doesn't see options that were set at install time

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#2988]
**Conan version**: 1.4.2

Consider the following conanfile, defining two options: `cheese` and `toast`.

```python
from conans import ConanFile, CMake, tools
import os


class ExportpkgweirdConan(ConanFile):
  name = "ExportPkgWeird"
  version = "1.0"
  license = "<Put the package license here>"
  url = "<Package recipe repository url here, for issues about the package>"
  description = "<Description of Exportpkgweird here>"
  settings = "os", "compiler", "build_type", "arch"
  options = {"cheese": [True, False], "toast": [True, False]}
  default_options = "cheese=True", "toast=True"
  generators = "cmake"

  def config_options(self):
    if "DO_IT_CONFOPT" in os.environ:
      try:
        del self.options.cheese
        print("deleted self.options.cheese")
      except:
        print("could not delete options.cheese")
      try:
        del self.options.toast
        print("deleted self.options.toast")
      except:
        print("could not delete options.toast")

  def requirements(self):
    if "DO_IT_REQS" in os.environ:
      try:
        del self.options.cheese
        print("deleted self.options.cheese")
      except:
        print("could not delete options.cheese")
      try:
        del self.options.toast
        print("deleted self.options.toast")
      except:
        print("could not delete options.toast")


  def source(self):
    pass

  def build(self):
    pass

  def package(self):
    pass

  def package_info(self):
    pass
```

In the conanfile directory, I install only specifying `cheese`.

```
$ conan install . -ocheese=False
```

After that, I conditionally try to delete the options in either `config_options` or `requirements` during `export-pkg`.

This is what happens with `requirements` (no issues here):

```
$ DO_IT_REQS=1 conan export-pkg . ExportPkgWeird/1.0@sztomi/unstable

ExportPkgWeird/1.0@sztomi/unstable: A new conanfile.py version was exported
ExportPkgWeird/1.0@sztomi/unstable: Folder: /home/tamas/.conan/data/ExportPkgWeird/1.0/sztomi/unstable/export
deleted self.options.cheese
deleted self.options.toast
Packaging to 58bcff2bc14b7abb2dd2e6921267ccd1ada533e2
ExportPkgWeird/1.0@sztomi/unstable: Generating the package
ExportPkgWeird/1.0@sztomi/unstable: Package folder /home/tamas/.conan/data/ExportPkgWeird/1.0/sztomi/unstable/package/58bcff2bc14b7abb2dd2e6921267ccd1ada533e2
ExportPkgWeird/1.0@sztomi/unstable: Calling package()
ExportPkgWeird/1.0@sztomi/unstable: WARN: No files copied from build folder!
ExportPkgWeird/1.0@sztomi/unstable: Package '58bcff2bc14b7abb2dd2e6921267ccd1ada533e2' created
```

However, with `config_options`:

```
$ DO_IT_CONFOPT=1 conan export-pkg . ExportPkgWeird/1.0@sztomi/unstable
ExportPkgWeird/1.0@sztomi/unstable: The stored package has not changed
deleted self.options.cheese
deleted self.options.toast
ERROR: ExportPkgWeird/1.0@sztomi/unstable: 'options.cheese' doesn't exist
Possible options are []
```

This seems like a bug to me, since the option does exist. If it's not a bug, can you explain this behavior and advise what would be the best way to do something like this? Should I stick to doing it in `requirements`? Isn't `config_options` exactly for this purpose? Also, I don't understand why the exception is able to circumwent my `except` block. It seems there is no exception thrown when the method is ran at all, since even the `print` calls are reached.

---

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by sztomi** [comment]
conaninfo.txt:

```
[settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++
    compiler.version=7.2
    os=Linux

[requires]


[options]
    cheese=False
    toast=True

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++
    compiler.version=7.2
    os=Linux

[full_requires]


[full_options]
    cheese=False
    toast=True

[recipe_hash]


[env]
```

**Comment by memsharded** [comment]
I think I don't fully understand the approach.
It doesnt make much sense to me conditioning the whole logic of ``config_options()`` and ``requirements()`` to environment variables. Environment variables might change in different ways, but they shouldn't affect the packages and binaries in a way that it is not modeled by conan. Conan binary IDs are based on settings + options + requirements, but not environment variables.

**Comment by sztomi** [comment]
Following up on our discussion in Slack: it turns out that we can achieve our end goal in a less hacky way, but this is still probably something that should be looked at. To clarify the example:

The environment variable is only there to allow selecting the method I use to delete the options. This could just as easily be demonstrated by two conanfiles, one with a `requirements` method and another one with `config_options`. So maybe think of it this way:

conanfile1.py:

```python
from conans import ConanFile, CMake, tools
import os


class ExportpkgweirdConan(ConanFile):
  name = "ExportPkgWeird"
  version = "1.0"
  license = "<Put the package license here>"
  url = "<Package recipe repository url here, for issues about the package>"
  description = "<Description of Exportpkgweird here>"
  settings = "os", "compiler", "build_type", "arch"
  options = {"cheese": [True, False], "toast": [True, False]}
  default_options = "cheese=True", "toast=True"
  generators = "cmake"

  def config_options(self):
    try:
      del self.options.cheese
      print("deleted self.options.cheese"
    except:
      print("could not delete options.cheese")
    try:
      del self.options.toast
      print("deleted self.options.toast")
    except:
      print("could not delete options.toast")
```

conanfile2.py:

```python
from conans import ConanFile, CMake, tools
import os


class ExportpkgweirdConan(ConanFile):
  name = "ExportPkgWeird"
  version = "1.0"
  license = "<Put the package license here>"
  url = "<Package recipe repository url here, for issues about the package>"
  description = "<Description of Exportpkgweird here>"
  settings = "os", "compiler", "build_type", "arch"
  options = {"cheese": [True, False], "toast": [True, False]}
  default_options = "cheese=True", "toast=True"
  generators = "cmake"

  def requirements(self):
    try:
      del self.options.cheese
      print("deleted self.options.cheese"
    except:
      print("could not delete options.cheese")
    try:
      del self.options.toast
      print("deleted self.options.toast")
    except:
      print("could not delete options.toast")
```

Running export-pkg on the first one fails, the second one doesn't. I think the first one shouldn't fail either.

**Comment by sztomi** [comment]
OK, so I tried the following: run install and export-pkg with the same option specified - this is not allowed and an error is displayed explaining it. This is fine. However, without the install step (i.e. removing the conan*info.txt files):

```
$ conan export-pkg . -ocheese=True some/channel
```

The output is:

```
ExportPkgWeird/1.0@some/channel: A new conanfile.py version was exported
ExportPkgWeird/1.0@some/channel: Folder: /home/tamas/.conan/data/ExportPkgWeird/1.0/some/channel/export
config_options
deleted self.options.cheese
deleted self.options.toast
goodbye
ERROR: ExportPkgWeird/1.0@some/channel: 'options.cheese' doesn't exist
Possible options are []
```

**Comment by memsharded** [comment]
But the output of such export-pkg is correct. You cannot set the ``cheese`` options, as it has been removed.

The difference is the flow:
-  ``conan install .`` is intended to install the current package dependencies, not to build anything. It will be more permissive checking the options, and it first assigns the values, and then remove them.
- ``conan export-pkg``: is packaging an existing package, something already built. The options have to match the declared ones, if they have been removed, they do not exist, and trying to define them is an error.

If something could make sense is trying to improve the ``conan install``, so it is able to raise errors for those removed options.

**Comment by sztomi** [comment]
You are right, I was confused. It does work if the options are removed in `requirements` though and I don't understand why. Maybe it shouldn't work in that case either?
