### ISSUE TITLE
[requires} in conanfile.txt gives no error

### ISSUE THREAD

**Issue by rollbear** [conan-io/conan#299]
The typo:
```
[requires}
...
```

in `conanfile.txt` does not give any error indication at all when running `conan install ...`. The way to see that something is wrong is that it doesn't do anything, but finding the cause was not as easy as it could've been.

This is on 0.9.2 on Ubuntu 15.10.

**Comment by memsharded** [comment]
Hi, thanks for telling, yes the error detection and reporting in the conanfile.txt could be better. A full grammar for this file would be too much, but I have proposed #300 to improve it a bit, at least check lines starting with "[" and that initial field is correct.
