### ISSUE TITLE
Multiple configurations of same project

### ISSUE THREAD

**Issue by leugenea** [conan-io/conan#2992]
I have a CMake project with multiple depends provided by Conan. But this project could be built for multiple platforms (Linux, Win, Android, iOS). This means that list of dependencies differs for different platforms.
Of course I can make 4 different profiles, but they will have a lot of common (for example, Boost is needed in all builds). Is there any way to inherit `conanfile.txt`?

Second question is more about [cmake-conan](https://github.com/conan-io/cmake-conan/), but relates to first question. For example, I want to allow developer to choose what version of Boost project will link against: static or shared. This is only one option that will differ in conanfile.txt, but I'll have to keep two almost identical files (and not to forget to modify them together too). So, it's one more example why Conan should have some sort of conanfile.txt inheritance. But maybe it could be solver using some cmake-conan parameter?

**Comment by lasote** [comment]
The profiles allows includes and variables: 

https://docs.conan.io/en/latest/reference/profiles.html?highlight=profile#profile-includes

**Comment by leugenea** [comment]
I know about profiles. But I don't want to force all developers to update their local profiles every time anybody modifies options needed for one project. On the other hand, it'll be very simple — to distribute `conanfile.txt` (or couple of them) with code repository, so when anybody changes some option of some package in project, it'll update automagically for everyone on repo update.

**Comment by lasote** [comment]
> But I don't want to force all developers to update their local profiles every time anybody modifies options needed for one project.

Probably you already know about the `conan config install` [command](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install)

I pretty sure we don't want to create inherited conanfile.txt files.
A different approach is to convert the `conanfile.txt` files to `conanfile.py` files, then you have some more possibilities of code reuse.

**Comment by memsharded** [comment]
And why not using command line for user specific configurations?

Also, for cmake-conan, you have the OPTIONS argument, you can use to define options there.

**Comment by leugenea** [comment]
@lasote , as you mentioned, I already know about `conan config install` command, but there's no "notifications" that profiles were changed, so it'll be some additional command that every developer have to run manually after some "magical notification" about profiles changing. I think that it could be run from CMake, but this looks more like a "hack" than a solution.

@memsharded , I've found `OPTIONS` argument after reading code of `conan.cmake` file (looks like it's missing from documentation).
What do you mean by "using command line for user specific configurations"? To run conan with specific options manually before CMake project generation?

**Comment by memsharded** [comment]
Closing this ticket as outdated:

- The problem of new profiles, yes, that is something outside of Conan, when new profiles are added, ``conan config install`` must be run by developers, there is no way that Conan checks at every command some potential remote origin of profiles, to check and compare if they have changed and then download them if they change. That would be massively expensive/slow and annoying for developers. It is not everyday that a new compiler is added to the supported platform, and running one ``conan config install`` is trivial.
- New Conan ``cmake-conan`` integration, with transparent integration (not modifying CMakeLists.txt)
