### ISSUE TITLE
[question] Can "conan install --update" restore local cache if it was accidently modified?

### ISSUE THREAD

**Issue by BillHoo** [conan-io/conan#2993]
To help us debug your issue please explain:

- [✔ ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [✔ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [✔ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

[version: Conan 1.4.2]
[system: Windows10 x64]

[steps to reproduce the problem]
1. Use "conan install conanfile.txt -r remote --update" to update the local cache from remote.
2. Modify some lines of a file in local cache. e.g. Append some new lines to "C:\Users\NAME\.conan\data\PKG_NAME\VERSION\ORG\CHANNEL\package\SHA\include\my_header.hpp".
3. Run the command "conan install conanfile.txt -r remote --update" again.

[problem]
After step 3, it just prompt "XXX Already installed!", and the local "my_header.hpp" still remain those new lines. That will cause problems if remote has no update but some developers do modified the local cache in their IDEs accidently, and then there's no way to get back :(

[expected]
Every time when we run "conan install --update", update the local cache if remote do have updates, or restore local cache otherwise.

Thanks in advance.
Bill

**Comment by memsharded** [comment]
Hi Bill,

First, the most important thing is that the cache should not be modified. It is not intended to be manually modified, and the behavior if doing so can be undefined. To avoid local modifications, you can try to use the CONAN_READ_ONLY_CACHE env variable: https://docs.conan.io/en/latest/reference/env_vars.html#conan-read-only-cache

What you specify as ``expected`` is what conan used to do in the past, but that is a very slow procedure (you have to compute the hashes of all the dependencies files, can be many MBs and thousands of files to hash), and most users asked for not doing it. You can specify the ``--verify`` argument if you want to verify for such modifications.

**Comment by memsharded** [comment]
Hi Bill,

I think for modifications of the packages, you want to check both the local development flow, so the user that wants to do modifications to A, does a local clone + install + build + export-pkg (e.g. https://docs.conan.io/en/latest/creating_packages/package_dev_flow.html). Or maybe soon using the coming conan-workspaces. 

Even if intended for prototyping it is not a good idea to modify the headers directly in the conan cache, in the same way it is not a good idea to modify headers in /usr/include or in the C:/.../Visual Studio/../include directories. :) :)

Please, have a look to the --verify option and to the local flow, and stay tuned for the conan-workspaces!

**Comment by BillHoo** [comment]
Thanks for those handy solutions, we finally decide to follow your advice to not modify the local cache and use the CONAN_READ_ONLY_CACHE to force it. And I'm waiting to see the conan-workspaces release.
