### ISSUE TITLE
[question] Newbie advice for Conan/Jenkins setup

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#2995]
To help us debug your issue please explain:

- [*] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [*] I've specified the Conan version, operating system version and any tool that can be relevant.
- [*] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Our company is wanting to modernise how we build our products, and we suspect that Conan (and Jenkins) can help us do that.

I have watched the 3 youtube webinars, and trawled through countless pages of information on the web around the use of Conan and Jenkins. I’ve also set up a Jenkins/Artifactory/Conan test machine to help with my understanding. Unfortunately, I am still having trouble understanding what would be considered best practice for setup of Jenkins and Conan for our requirements. I strongly believe it can help, I just can’t join the dots at the moment!

Current setup:
* Jenkins (2.36)
* Subversion for our source code
* CMake
* Multiple (RHEL based) appliance products (multiple versions), each comprising of:
  * Many different “shared components” i.e. components that contain shared libraries and/or executables that are used/required by multiple products
  * Product specific “components”, again containing shared libraries and/or executables but only used by that specific product
* As expected, some components depend on other components, whether for linkage reasons or other reasons
* Every component is individually configured within Jenkins as a Freestyle project, each specifying where the source lives (repo/branch), how to build, what their artifacts are, its dependencies, its triggers etc
* Finally, we have a top level component that represents the “product”, pulls in all the rpm artifacts from the sub-components (that each sub-component built) and creates an iso from them. This iso represents the actual product.

Thoughts for new setup:
* Update Jenkins to latest
  * Update to using Pipelines
* Probably stay with Subversion but are open to moving to git
* CMake
* Move to Artifactory/Conan for package management

With the use of Artifactory/Conan we are hoping that all the individual components that we currently configure in Jenkins can be removed, and that Conan will manage all the dependencies and not Jenkins.

Is this correct? Or have I missed the point?

If so, does that mean we instead will configure a single Jenkins Pipeline for each product, with the Pipeline configured somehow (how?) to point at a product Conan recipe, with that recipe specifying the product toplevel dependencies, which in turn will point to packages (components as I’ve been talking about them) that specify their dependencies and so on? Is this what the 3rd webinar was trying to show?

Can you assist in sharing any resources, white papers or anything that can help with getting us going?

Of course, we also care about ongoing product development, product release and product maintenance, and how this is all managed, but I need to learn to walk before I run.

Cheers,

Keith

**Comment by tonka3000** [comment]
Hey,

You can use conan for your dependencies. Think of  jenkins as runner that just executes your code. Put the pipeline file in your repo, so that jenkins can trigger a build every time you change the code. In the pipeline you control conan via conan-package-tools and it's env vars. After the build conan upload the binaries to your remote and after that it can be used everywhere, also by another pipeline.

Read the conan documentation, there is ton of good articles there.

Hope that helps

Greetings

Tonka
