### ISSUE TITLE
why does conan detect gcc 1 ?

### ISSUE THREAD

**Issue by conradjones** [conan-io/conan#2998]
This is running in a docker linux container, clang 6 is installed. gcc is not.

```bash
`[openssl] $ sh -c "conan create -s build_type=Debug -s compiler=clang -s compiler.libcxx=libstdc++11 -s compiler.version=6.0 . turboit/openssl "
OpenSSL/1.0.2o@turboit/openssl: Exporting package recipe
Linter warnings
    WARN: Linter. Line 101: Anomalous backslash in string: '\$'. String constant might be missing an r prefix.
    WARN: Linter. Line 101: Anomalous backslash in string: '\$'. String constant might be missing an r prefix.
    WARN: Linter. Line 101: Anomalous backslash in string: '\$'. String constant might be missing an r prefix.
    WARN: Linter. Line 101: Anomalous backslash in string: '\$'. String constant might be missing an r prefix.
    WARN: Linter. Line 102: Anomalous backslash in string: '\$'. String constant might be missing an r prefix.
    WARN: Linter. Line 102: Anomalous backslash in string: '\$'. String constant might be missing an r prefix.

OpenSSL/1.0.2o@turboit/openssl: A new conanfile.py version was exported

OpenSSL/1.0.2o@turboit/openssl: Folder: /root/workspace/conan/openssl@tmp/conan.tmp6052754136315568067/.conan/data/OpenSSL/1.0.2o/turboit/openssl/export

Auto detecting your dev setup to initialize the default profile (/root/workspace/conan/openssl@tmp/conan.tmp6052754136315568067/.conan/profiles/default)

Found gcc 1
Found clang 6.0
Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=gcc
	compiler.version=1
	compiler.libcxx=libstdc++
	build_type=Release

*** You can change them in /root/workspace/conan/openssl@tmp/conan.tmp6052754136315568067/.conan/profiles/default ***

*** Or override with -s compiler='other' -s ...s***
```

**Comment by conradjones** [comment]
it works fine if i set 

export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

which I don't mind doing, it's quite easy via jenkins to set it on the docker container via the cloud plugin, i'm just trying to understand why conan isn't honouring the command line passed to it and why it's detecting gcc 1. It's caught me out a few times now

**Comment by memsharded** [comment]
Could you please type ``gcc --version`` and ``gcc -dumpversion`` in your system and copy here the output?

**Comment by conradjones** [comment]
root@a6faa521dc8c:~/conan-openssl# gcc --version
bash: gcc: command not found
root@a6faa521dc8c:~/conan-openssl# gcc -dumpversion
bash: gcc: command not found

**Comment by memsharded** [comment]
Thanks, you are right, this is a bug.
Submitted a fix in https://github.com/conan-io/conan/pull/2999, will be soon in 1.4.3

**Comment by memsharded** [comment]
In any case, I'd still strongly recommend to use profiles, instead of relying on auto-detection.

**Comment by conradjones** [comment]
I do use profiles on my laptop, but not in the CI environment as it's not practical note the path of the profile :

`` *** You can change them in /root/workspace/conan/openssl@tmp/conan.tmp6052754136315568067/.conan/profiles/default *** ``

```*** Or override with -s compiler='other' -s ...s*** ```
I don't understand why it's not honoring the compiler specified on the command line :  

`[openssl] $ sh -c "conan create -s build_type=Debug -s compiler=clang -s compiler.libcxx=libstdc++11 -s compiler.version=6.0 . turboit/openssl "`

**Comment by memsharded** [comment]
The recommended way to use profiles is via ``conan config install``. Put them in a repo, so you can easily update them both in CI and in your machine.

> I don't understand why it's not honoring the compiler specified on the command lin

The default profile auto-detection and the command line are totally decouple things. Command line arguments always have priority, but they do not affect the auto-detection, that is a convenience for quick getting started.

**Comment by conradjones** [comment]
Okay thanks the conan config install command looks useful. I saw that a
while back but must have forgotten about it, keeping it in a repo appeals!
