### ISSUE TITLE
Issue tracker button on web doesn't work

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#30]
Reported by @dimitrikourk in Win7, Firefox 38.3.0 and IE 11, confirmed in Ubuntu Firefox. 

Go to https://www.conan.io/source/zlib/1.2.8/lasote/stable -> Issue tracker
Octocat link works, but button doesn't.

**Comment by lasote** [comment]
octocat?? wtf is this?

**Comment by dimitrikourk** [comment]
I believe it's what GitHub calls its mascot :)

**Comment by lasote** [comment]
Thanks! hhahahhaha
