### ISSUE TITLE
Allow `conan download` by wildcard?

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#3002]
*The problem*:
I want to upload packages with my configuration to my artifactory.
I don't feel well about doing it for all boost_* packages one by one. 

*Solution*(?):
Allow installing by wildcard?

**Comment by memsharded** [comment]
Install or upload? ``conan upload boost_*`` is valid syntax

**Comment by Minimonium** [comment]
@memsharded Right! I get my semantics wrong. I actually want `conan download` to support wildcards.

**Comment by Minimonium** [comment]
Basically, I have a situation when I want to do `conan download` and then `conan upload` stuff. But only upload supports wildcads.

**Comment by memsharded** [comment]
Conan download in 2.0 allow wildcards, also ``conan upload``, and both can also communicate with "package lists": https://blog.conan.io/2023/06/28/Conan-bulk-package-operations.html

Closing this ticket as solved, thanks!
