### ISSUE TITLE
conan-center is down

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3015]
It may be not very correct place to report this but conan-center (bintray.com) is quite unstable (mostly down) for several hours. Please do something, conan is almost unusable now.

**Comment by danimtb** [comment]
Hi @db4 

Yes we are aware of that and we have reported to the Bintray Team. You can follow the status here: http://status.bintray.com/

Thanks!

**Comment by db4** [comment]
OK, thatks for the info!
