### ISSUE TITLE
[SCM] Consider SCM capture functionality without cloning, to coexist with exports_sources

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3016]
It might be useful to be able to capture the repository details when a package was created, even if it is using the `exports_sources` feature. In that case, the SCM details are mostly for reference, or to improve reproducibility out of the conan local cache, i.e. to restore the exact commit of the repo to fire a `conan create`` again.

cc/ @3galki

**Comment by lasote** [comment]
@jgsogo suggested (and maybe I agree) that information should be stored as properties in the metadata (sending them is not a feature still not existing) irrespective if the `scm` is declared or not.
It will be messing a little calling `git`/`svn` but maybe is not that hard.

**Comment by memsharded** [comment]
Doable with https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html
