### ISSUE TITLE
Consider conan test_package does also an export

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#302]
The export is fast and simple.
I would say that almost ever that I run ``conan test_package`` is because I am developing a recipe, something is not working and I changed the conanfile.
So 99% I have to run before ``conan export user/channel``
The times I forget it, is very annoying, it runs the obsolete version of the package conanfile

So I suggest making "test_package" do an export always, just leave an opt-out flag to avoid it if necessary.

Assigned ONLY FOR EVALUATION, not implementation. It is easy, though.

**Comment by lasote** [comment]
And how to decide the user and channel to export to?

**Comment by memsharded** [comment]
Take it from the default dep in the test_package?

**Comment by memsharded** [comment]
Released in 0.11
