### ISSUE TITLE
Improve error message on wrong value for settings attribute

### ISSUE THREAD

**Issue by roe85** [conan-io/conan#3022]
I had a wrong value for the settings attribute like:
```
settings = {"os_build": 'Linux', "arch_build": ["x86", "x86_64"]}
```
And the error message was very strange:
```
ERROR: /home/users/.../export/conanfile.py: Error while initializing settings. Invalid setting 'L' is not a valid 'os_build' value.
Possible values are ['FreeBSD', 'Linux', 'Macos', 'SunOS', 'Windows', 'WindowsStore']
```
It's not obvious at this point, what the problem was. After quite some digging, I found that the value for os_build is supposed to be a list.
Maybe apply some schema checking at this point for a better error message.

**Comment by lasote** [comment]
Hi, yes, I think some type check could be done here. Thanks for reporting.
