### ISSUE TITLE
Cannot build using Conan and Visual Studio 2017 in Japanese Environment

### ISSUE THREAD

**Issue by dibben-jsol** [conan-io/conan#3028]
Tests are with conan 1.4.4, Python 2.7.10, Windows 7

When trying to build a package in the local cache
 (conan install MyPackage/1.0.0@user/channel --build=missing)
I get the following error

        vcvars = tools.vcvars_command(self.settings)
        ValueError: Invalid \escape: line 12 column 54 (char 597)

This occurred after installing Visual Studio 2017.

The environment is Japanese Windows 7, but set to English environment. This sets the UI to English but many system strings still appear in Japanese.

Tracing through conan source shows the problem to be in the line
    return json.loads(vswhere_out)
of vswhere in win.py.

The output of vswhere.exe for VS2017 contains the line
 "description": "生産性向上と、さまざまな規模のチーム間の調整のための Microsoft DevOps ソリューション",
(This is line 12 of the vswhere.exe output)

Adding the code 

    output = '\n'.join(line for line in output.split('\n') if 'description' not in line)

to strip out this line from the vshwere.exe output before the line

    vswhere_out = decode_text(output).strip()

in vswhere in win.py allows the build to proceed normally.

So it seems the Japanese message in the json from vswhere is causing the loading of the json to fail.

When running vshwere.exe directly, the output is in utf-8 but this bug
 https://github.com/Microsoft/vswhere/issues/146
suggests that sometimes the output is not in utf-8.

**Comment by dibben-jsol** [comment]
This is the local output of vswhere
[where.txt](https://github.com/conan-io/conan/files/2093321/where.txt)

**Comment by memsharded** [comment]
Have you tried using python 3.X instead?

The fact is that python 2 support for unicode is a bit complicated, to say something. We have been fixing some things, but still python 3 is strongly recommended. Not only for this reason, but the deprecation of python 2 has already started, as some of conan dependencies have started to be python 3 only.

Please try python 3 if possible. Thanks!

**Comment by heaths** [comment]
The output of vswhere depends on the currently active console code page when redirecting to a file or writing to a pipe. Microsoft/vswhere#146 is about adding a new switch to force UTF8 regardless of the active code page, so once I release from master (2.5) I recommend you rely on that version by redistributing. I'll try to get it into the next Visual Studi 2017 update, but by redistributing it or otherwise taking a dependency on the version release here from GH, you can be sure it supports the parameters you require.

**Comment by dibben-jsol** [comment]
I tried with Python 3.6.5  and it still has the same problem. The error changes to 

    JSONDecodeError: Invalid \escape: line 12 column 54 (char 597)

**Comment by heaths** [comment]
You need to use the private build (a release is currently building) and pass the `-utf8` option. I didn't change the default encoding because it would be a breaking change.

**Comment by lasote** [comment]
As @dibben-jsol suggested, (```vswhere_out = decode_text(output).strip()```) we should take a look at the Conan code and see if we can "decode" or "ignore" the offending characters from the json. The "description" field is not relevant for us.

Thanks @heaths for your collaboration 😃 , defininitely a `utf8` could help but probably is complex for Conan to know when the new parameter can be applied or not to `vswhere`.

**Comment by heaths** [comment]
The point I was making was for your code to pass `-utf8` so callers don't have to consider it.

**Comment by lasote** [comment]
I know, and I appreciate the effort, but I assume the `-utf8` will be available only in a concrete release of `vswhere`, hard to know from conan when to apply the parameter or not. Since we do not install explicitly the `vswhere` tool (we always rely in the developer installed tools except for build_requires) is hard to control when to use the parameter.

**Comment by lasote** [comment]
@dibben-jsol Please, could you try in python 2 and 3 what happen if you change the `vswhere` conan tool function with the [following](https://github.com/lasote/conan/blob/e110b2599bb87ce9f49a3e71dd1cf9432b790ebe/conans/client/tools/win.py): 

I cannot make it fail in the decode, only in the json parsing.

```
.....

    try:
        output = subprocess.check_output(arguments)
        output = decode_text(output).strip()
        # Ignore the "description" field, that even decoded contains non valid charsets for json (ignored ones)
        output = "\n".join([line for line in output.splitlines() if not line.strip().startswith('"description"')])

    except (ValueError, subprocess.CalledProcessError, UnicodeDecodeError) as e:
        raise ConanException("vswhere error: %s" % str(e))

    return json.loads(output)

```

**Comment by dibben-jsol** [comment]
@lasote This works for me with both Python 2.7.10 and 3.6. 
The previous failure for me was in the json loading as well. 
Thanks

**Comment by dibben-jsol** [comment]
Thanks!
