### ISSUE TITLE
conan create command complains about corrupted dependencies

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#3029]
Conan 1.4.4.

So I've started migration of all my packages to C++2a and header only libraries started complaining about corrupted packages that are dependencies and were removing them from local cache even though there were perfectly good builds. Same thing for regular libraries.

The only way to fix regular libraries is to remove the build directory completely. The only way to fix header only libraries is to remove their "builds" from local cache.

**Comment by memsharded** [comment]
Not sure about what you are doing. What are you changing? What are the commands you are using? The profiles?

If you could please ellaborate a bit more about those errors, and try to provide something that is reproducible, that would help a lot. Many thanks!

**Comment by Lyberta** [comment]
For header only libraries I use `conan create`, for regular libraries I use `conan install`, `conan install`, `conan build` and `conan export-pkg`.

When I call `conan create`, I get corrupted package warning and it creates `hash.dirty` file instead of a build of dependency.

**Comment by memsharded** [comment]
Not sure what is happening. I would suggest to completely remove your local cache folder (<userhome>/.conan) and try again.

Looking forward to your libs for reproduce it. Also , do not forget which OS, compiler, etc, you are using and the exact commands that fire the error, as well as the terminal output. Thanks!

**Comment by Lyberta** [comment]
Yes, that's basically what I did. Removed my local build folder and removed stuff from local cache. I'm sorry I didn't intend to provide a repro. I just never had such problems before.

The problems stems from the fact that conan allow stale files and in case of `conan create` with header only library it still picks up old C++17 files from somewhere.

**Comment by memsharded** [comment]
Closing as inactive
