### ISSUE TITLE
conan user --clean

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#303]
Would be useful to wipe all user information from all remotes at once.
Possibly, as a more elegant solution to that problem with a bad password is stored in the DB, a bit annoying (requires remove .db), still not found bug/cause.

**Comment by memsharded** [comment]
Some clarifications: Passwords are never stored in the localdb. Encrypted tokens (which expire also) are stored in the DB. Still not able to reproduce the bug, maybe it was due to older conan versions. Submitting PR with this feature.

**Comment by memsharded** [comment]
Submitted PR #325

**Comment by lasote** [comment]
Fixed in 0.10.0, please try it and reopen if needed.
