### ISSUE TITLE
Virtualbuildenv generator should append Visual Studio dirs to current PATH, not completely replace it

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3038]
I would love to see `set PATH=<Visual Studio dirs>;%PATH%` instead of `set PATH=<generated paths>` in `activate_build.bat` to make possible `activate*.bat` files chaining and preserving current environment values. Virtualbuildenv generator should record difference in OS environment before and after invocation of `vcvarsall.bat` and put only that difference to `activate_build.bat`

**Comment by danimtb** [comment]
Thanks for the advice. Will check it!

**Comment by danimtb** [comment]
@db4 I have just check with a test and *activate_build.bat* appends vcvars variables to PATH, it does not replace the PATH var completely. *deactivate_build.bat* sets the path to normal environment value.

Maybe I did not full understand your issue. What I am missing?

**Comment by db4** [comment]
@danimtb, `activate_build.bat` contains a line
```
set PATH=...
```
that does not contain `%PATH%`. It actually is a static snapshot of PATH variable in the time of the generator invocation. So I cannot chain `activate_run.bat && activate_build.bat` because the latter overwrites paths set by `activate_run.bat`. Yes, I can swap them `activate_build.bat && activate_run.bat` and this works somehow, but more correct approach would be to set only Visual Studio-related paths and inherit the current state:
```
set PATH=<Visual Studio paths>;%PATH%
```

**Comment by danimtb** [comment]
ok, @db4 thanks for the explanation!

**Comment by db4** [comment]
@danimtb,
One more thing about virtualbuildenv generator w.r.t. Visual Studio. You add
```
SET CL=-MDd;%CL%
```
And this is what `cl.exe` does not like:
```
cl : Command line warning D9002 :
ignoring unknown option '-MDd;'
```
Yes, this is just a warning but still pretty annoying

**Comment by danimtb** [comment]
Should it be something like `SET CL=/MDd;%CL%` ?

**Comment by db4** [comment]
No, hyphen is OK. The problem is in semicolon as a delimiter - one should use space instead. See [CL Environment Variables](https://msdn.microsoft.com/en-us/library/kezkeayy.aspx).

**Comment by danimtb** [comment]
ok, I'll open a new issue for this as it is related to `VisualStudioBuildEnvironment` build helper. Thanks a lot for the information!

**Comment by danimtb** [comment]
Follow issue in #3080
Thanks again!

**Comment by danimtb** [comment]
Hi @db4,

Following hte progress of the issue in PR #3076 we have finally come to the conclusion that this is a too rinky feature for the value. We consider this is not a stopper feature but an enhancement and there are ways to avoid the issue as you pointed out. Please read the comments in the review  of the PR.

Thanks!
