### ISSUE TITLE
[SCM] Recipe with sources in the same repo copies to the source folder gitignored files

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#3039]
Situation:
I have a `conanfile.py` in a repo with:
```
scm = {
        "type": "git",
        "subfolder": "asdio",
        "url": "auto",
        "revision": "auto"
    }
```
There are some gitignored files such as `.vs`.

Problem:
When using `conan install -pr=...` it uploads *everything* including ignored files to the `source` folder.

**Comment by memsharded** [comment]
Just to make sure, you mean it **copies** files to the source folder, don't you? Those files are not uploaded to any server.

**Comment by Minimonium** [comment]
Yep!

**Comment by memsharded** [comment]
Then it is not a big issue, is it? It is just a temporary copy, it is not packaged, it is not uploaded. Copying files or folders like .vs shouldn't have any effect.

**Comment by Minimonium** [comment]
Yes, the minor one. It could matter if such temporary files are big, I guess?

**Comment by Minimonium** [comment]
Oh, I forgot. Since `.vs` is not ignored it blocks `conan install` if VS is open, @memsharded ! Still a minor one, but anyway.

**Comment by Minimonium** [comment]
@memsharded And I assume here that because of that it's pretty easy to get invalid binaries in cases when we're using `"revision": "auto"`, since we could get different binaries in case of yet to be commited changes. Should it clone at source stage then instead of copying everything? I'm missing something here.

**Comment by lasote** [comment]
>  we could get different binaries in case of yet to be commited changes. 

I think this is the reason we decided to not clone but copy the sources, while you are developing your library you probably don't want to commit any change to be able to try the conan package and see if your entire project works.

**Comment by lasote** [comment]
I will try to get from git the ignored file list to be applied to the copy.

**Comment by Minimonium** [comment]
Right. So we would get all changes (not committed yet) but without ignored stuff? Would be good, thanks!

**Comment by Minimonium** [comment]
@lasote I'm afraid there is a problem with that feature. It does ignore **files**, but not **folders**.
