### ISSUE TITLE
new clang version 10.0.0 is not supported (settings.compiler.version)

### ISSUE THREAD

**Issue by lizyFrog** [conan-io/conan#3043]
conan version: 1.4.4
clang version: 10.0.0
I've used the following pipeline in Jenkins : https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/conan-example/Jenkinsfile

If failed with the following output:

(/var/folders/3h/fkh389zj34s7hl6xdpjd1hn0bc436s/T/conan5921226174563491616/.conan/profiles/default)
Found apple-clang 0.0
Default settings
	os=Macos
	os_build=Macos
	arch=x86_64
	arch_build=x86_64
	compiler=apple-clang
	compiler.version=0.0
	compiler.libcxx=libc++
	build_type=Release
*** You can change them in /var/folders/3h/fkh389zj34s7hl6xdpjd1hn0bc436s/T/conan5921226174563491616/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***

**ERROR: Invalid setting '0.0' is not a valid 'settings.compiler.version' value.
Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1']**

**Comment by memsharded** [comment]
Yes, it seems the parsing of the version only uses 1 digit, and 10.0 overflows.
