### ISSUE TITLE
[SCM] Cloning repository not working when using exports attribute

### ISSUE THREAD

**Issue by Sebiee** [conan-io/conan#3044]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

## System info
**Conan version**: 1.4.4
**Operating System**: Debian 9 (stretch)

## Problem explanation
When using scm and also specify at least a file in the "exports" attribute, conan fails to bring the sources with git clone, saying that the folder is not empty. Thing is that before doing git clone in the source folder in local cache, conan first copies what is in the "export" folder to the "source" folder. Obviously, you can't do git clone afterwards.
If specifying a subfolder, scm would work, but I do need the sources to be in the root "source" folder, not in a subfolder.

## Steps to reproduce
I reproduced it in a repo: https://github.com/Sebiee/conan_bug
```bash
git clone https://github.com/Sebiee/conan_bug
cd conan_bug
conan export . conan/test
#remove file scm_folder.txt from local cache to force cloning from git
conan test test_package string_wrapper/1.0.0@conan/test --build string_wrapper
```

**Comment by lasote** [comment]
I will take a look to see if it can be solved somehow.

**Comment by Sebiee** [comment]
Well, git won't let you clone into a folder that is not empty, but I don't think we need to clone to a not empty folder. What about first doing git clone into the source folder and then copy the files from "export". Would that be wrong for some reason?

**Comment by lasote** [comment]
It is not that easy to change the order that Conan follows, (have to check) but probably there are also good reasons to do first the export and then the sources.

**Comment by marausch** [comment]
A workaround to Git's limitation shouldn't be that difficult, e.g. cloning to an empty temporary subfolder and then moving the whole stuff one level up to the source folder (not optimal though).

**Comment by Sebiee** [comment]
> A workaround to Git's limitation shouldn't be that difficult, e.g. cloning to an empty temporary subfolder and then moving the whole stuff one level up to the source folder (not optimal though).

That's what I am doing manually right now, but, as you said, I only see it like a workaround, not as a viable thing that will always be present in my recipes.

**Comment by lasote** [comment]
> That's what I am doing manually right now, but, as you said, I only see it like a workaround, not as a viable thing that will always be present in my recipes.

Exactly! I don't want it either in the conan source code! ;)

**Comment by lasote** [comment]
The reason to copy first the `exports` and then calling the `source` method is that in the source method you can typically patch the cloned repo with some exported file. 
But, for SCM I think we can maybe first call scm, then copy the exports and finally call the source(). So we could avoid this issues.

**Comment by marausch** [comment]
Very good, the sequence proposed by @lasote seems the most logical, we can do everything we might need:
- first get the stuff from Git in the _"SCM call"_ step;
- then add/replace some file in the _"export"_ step;
- finally we can further manipulate/complete the stuff in the _"source()"_ step (this is e.g. where I plan to get the Git submodules in case the _SCM-call_ doesn't do it already).
