### ISSUE TITLE
vcvars_command ignores sdk version for vcversion <= 14

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#3045]
I was doing:

vcvars = tools.vcvars_command(self.settings,winsdk_version="8.1")

but the 8.1 wasn't getting appended

Looking at the code:

```
if int(compiler_version) > 14:
                vcvars_path = os.path.join(vs_path, "VC/Auxiliary/Build/vcvarsall.bat")
                command = ('set "VSCMD_START_DIR=%%CD%%" && '
                           'call "%s" %s' % (vcvars_path, vcvars_arch))
                if winsdk_version:
                    command += " %s" % winsdk_version
                if vcvars_ver:
                    command += " -vcvars_ver=%s" % vcvars_ver
```

version 14 is excluded for some reason. 

however the sdk does seem supported for v14:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>vcvarsall.bat /?
Error in script usage. The correct usage is:
    vcvarsall.bat [option]
  or
    vcvarsall.bat [option] store
  or
    vcvarsall.bat [option] [version number]
  or
    vcvarsall.bat [option] store [version number]
where [option] is: x86 | amd64 | arm | x86_amd64 | x86_arm | amd64_x86 | amd64_arm
where [version number] is either the full Windows 10 SDK version number or "8.1" to use the windows 8.1 SDK
:
The store parameter sets environment variables to support
  store (rather than desktop) development.
:
For example:
    vcvarsall.bat x86_amd64
    vcvarsall.bat x86_arm store
    vcvarsall.bat x86_amd64 10.0.10240.0
    vcvarsall.bat x86_arm store 10.0.10240.0
    vcvarsall.bat x64 8.1
    vcvarsall.bat x64 store 8.1
:
Please make sure either Visual Studio or C++ Build SKU is installed.
```
The workaround is to manually append the sdk verison

The sdk version is needed when a newer sdk version is installed...projects can fail to build otherwise.

Either way, it might be nice to output an error/warning if someone specifies a setting which is considered not supported so they know why it has no effect.

**Comment by danimtb** [comment]
Hi @rconde01,

Thanks a lot for looking into this.
We saw those options where available for vcvarsall in VS 2017: https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line#use-the-developer-tools-in-an-existing-command-window

However, vcvarsall 2015 seemed to not support it looking at its documentation page: https://msdn.microsoft.com/en-us/library/f2ccy3wt.aspx

We'll fix it for next conan release. thanks again!
