### ISSUE TITLE
[build system] [MSBuild] MSBuild() can't receive custom properties

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3048]
For example, if I want to invoke MSBuild with `/p:MyCustomProperty=true` I can't do it. (If you try to pass it in the project file, it invokes the project update with the property and fails)
To study if an "args" parameter is missing to build or a "properties" that manages the `/p:` for us (or both)?

**Comment by memsharded** [comment]
Check if the helper could received multiple ``/p:myproperties.props`` files.
