### ISSUE TITLE
Add method to set default profile from command line

### ISSUE THREAD

**Issue by sturmf** [conan-io/conan#3049]
Currently it seems that conan has no method to set the default_profile as it is set in the conan.conf per command line. 
A command line way would be great so that we can set it e.g. in ci environments....
Of course we can modify the file directly by text replacement but that seems unnecessary awkward.

    conan profile default "profilename"

**Comment by danimtb** [comment]
I think `conan config set general.default_profile=new_default_profile` is all you are asking for.

Check the [conan config isntall](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install) feature, as it could be handy for setting up different conan configurations for CI stuff.

**Comment by sturmf** [comment]
ohh of course. i only searched the profile documentation but that's set in the config file.
