### ISSUE TITLE
Add json output to info or new way to inspect local files.

### ISSUE THREAD

**Issue by tru** [conan-io/conan#3053]
We frequently run into places where it would be good to extract information from a local conanfile.py instead of getting data from the local cache, currently we have a ugly mess of fileparsing and regex to do this since it's a bit complicated to instance a conanfile for inspection. In order to support scripts like this it would be great to have some json output from the `info` command or a new `inspect` command that will output json with all attributes of the current file, like version, description, license, requires. To get requires correct it needs to be able to take a profile as argument as well.

cc @sztomi

**Comment by jgsogo** [comment]
A new [command ``inspect``](https://docs.conan.io/en/latest/reference/commands/misc/inspect.html) has been released in version 1.8, is it enough for your use case? Thanks!
