### ISSUE TITLE
[question] Why is the documentation executing cmake.install() in build() instead of package() ?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#3054]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).

---

Taken from the documentation:
https://docs.conan.io/en/latest/howtos/cmake_install.html

Naively, I would have expected to re-instantiate a CMake object in `package()`, and call it's `install` method from there. This would allow to keep the original intention of the method.

What is the motivation behind that *recommendation*?
Is it okay to actually do it in the `package()` recipe method?

(Bonus question: when I call `conan package` command directly, even without the `--source-folder` parameter, the `package()` method seems to be called twice, although [this answer](https://github.com/conan-io/conan/issues/1509#issuecomment-315894760) from @memsharded would seem to imply it should not)

**Comment by danimtb** [comment]
Hi @Adnn,

Yes, normally we dont recommend to use cmake.install() in package(), as this could be called twice when source folder and build folder are different (and sometimes those install steps are slow). You can find more information at the end of [the package() section in docs reference](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package).

For the second question I guess you are using the package command with something like this:
```
$ conan package . -build-folder my_build_folder
```
This is actually taking the source folder as the current working directory and build folder as *my_build_folder*. As directories are different, package method is called twice.

For those directories to be the same, you would need to do `$ conan package . (-pf package_folder)` or `$ conan package . --source-folder my_shared_folder --build-folder my_shared_foder (-pf package_folder)`. Note `--package-folder` does not affect in this example, so you cna use it or not.

Please give it a try and let me know. Thanks! 😄

**Comment by danimtb** [comment]
Just to leave th information here.
The default directory for all directory params can be fould in the help message of each command:

```
$ conan package --help
```
https://docs.conan.io/en/latest/reference/commands/development/package.html

Please @Adnn close the issue if your question was answered. Many thanks!
