### ISSUE TITLE
Error when install cpprestsdk Debug X86 lib on Windows

### ISSUE THREAD

**Issue by sinall** [conan-io/conan#3056]
Conan version: 1.4.3
OS: Win 10
Compiler: Visual Studio 2015 V140

conanfile.txt:
```
[requires]
boost/1.67.0@conan/stable
cpprestsdk/2.10.1@bincrafters/stable
libzip/1.5.1@bincrafters/stable
zlib/1.2.11@conan/stable

[generators]
visual_studio_multi

[options]
boost:shared=False
```

conan profile show default:
```
Configuration for profile default:

[settings]
arch=x86
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
[options]
[build_requires]
[env]
```

1. conan install .

2. Build Solution with **Debug/Win32** configuration in VC++ 2015:

> 7>boost_locale.lib(generator.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in myapp.obj
> 7>boost_locale.lib(generator.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in myapp.obj
> 

Since both bzip2 and lzma don't have pre-build packages.
3. conan install . -s build_type=Debug --build bzip2 --build lzma

> bzip2/1.0.6@conan/stable: Package '9abbe06923faf25f39f2204ad0658dbe7650ccfb' created
> cmake_findboost_modular/1.66.0@bincrafters/stable: Already installed!
> lzma/5.2.3@bincrafters/stable: WARN: Forced build from source
> lzma/5.2.3@bincrafters/stable: Building your package in D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffd
> bd5f8b1274645ac279fd1fe9274
> lzma/5.2.3@bincrafters/stable: Copying sources to build folder
> lzma/5.2.3@bincrafters/stable: Generator txt created conanbuildinfo.txt
> lzma/5.2.3@bincrafters/stable: Calling build()
> Skipped sln project upgrade
> WARN: ***** The configuration Debug|x86 does not exist in this solution *****
> WARN: Use 'platforms' argument to define your architectures
> Microsoft (R) Build Engine version 14.0.25420.1
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 2018-06-15 12:33:58 AM.
>      1>Project "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\wi
>        ndows\xz_win.sln" on node 1 (liblzma target(s)).
>      1>ValidateSolutionConfiguration:
>          Building solution configuration "Debug|Win32".
>      1>Project "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\wi
>        ndows\xz_win.sln" (1) is building "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645
>        ac279fd1fe9274\xz-5.2.3\windows\liblzma.vcxproj" (2) on node 1 (default targets).
>      2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The
>        build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please in
>        stall v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Proj
>        ect menu or right-click the solution, and then selecting "Retarget solution". [D:\.conan\data\lzma\5.2.3\bincraf
>        ters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\windows\liblzma.vcxproj]
>      2>Done Building Project "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe92
>        74\xz-5.2.3\windows\liblzma.vcxproj" (default targets) -- FAILED.
>      1>Done Building Project "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe92
>        74\xz-5.2.3\windows\xz_win.sln" (liblzma target(s)) -- FAILED.
> 
> Build FAILED.
> 
>        "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\windows\xz
>        _win.sln" (liblzma target) (1) ->
>        "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\windows\li
>        blzma.vcxproj" (default target) (2) ->
>        (PlatformPrepareForBuild target) ->
>          C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: Th
>        e build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please
>        install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Pr
>        oject menu or right-click the solution, and then selecting "Retarget solution". [D:\.conan\data\lzma\5.2.3\bincr
>        afters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\windows\liblzma.vcxproj]
> 
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.81
> lzma/5.2.3@bincrafters/stable:
> lzma/5.2.3@bincrafters/stable: ERROR: Package '10b873a178ffdbd5f8b1274645ac279fd1fe9274' build failed
> lzma/5.2.3@bincrafters/stable: WARN: Build folder D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b
> 1274645ac279fd1fe9274
> ERROR: lzma/5.2.3@bincrafters/stable: Error in build() method, line 88
>         self.build_msvc()
> while calling 'build_msvc', line 59
>         self.run(command)
>         ConanException: Error 1 while executing call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/vcvarsall.b
> at" x86 && msbuild xz_win.sln /p:Configuration=Debug /p:Platform="Win32" /m:4 /target:liblzma /p:ForceImportBeforeCppTar
> gets="C:\Users\xxx\AppData\Local\Temp\tmpp0915vchtmp_conan\.conan_properties"

-----------------------------

Some questions:
1. Do I have to use all debug version of libs like bzip2, lzma, etc. What VC++ really complains is about boost.
2. How do I config conan to install & use both Debug and Release packages in VC++?
I see [visual_studio_multi](https://docs.conan.io/en/latest/reference/generators/visualstudiomulti.html)
```
$ conan install . -g visual_studio_multi -s arch=x86 -s build_type=Debug
$ conan install . -g visual_studio_multi -s arch=x86 -s build_type=Release

```
Is this the easiest way so far? I see there are some topic about combining above commands into single one, any news on this? since this is very usual case for a VC++ developer.

**Comment by memsharded** [comment]
When you do the:
1. conan install .
2. Build Solution with Debug/Win32 configuration in VC++ 2015

Yes, it fails because you installed the release dependencies (as specified by your default profile),and you are trying to build your consumer with Debug. Visual Studio is usually very picky, if you are building in Debug, then your dependencies should be in Debug. (Question 1). It is possible that it will even link, and it will not complain about other deps, but then, it can fail at runtime. It is strongly recommended to use dependencies with the same build type.


Yes, the easiest way to consume right now would be what you said:
```
$ conan install .  -s build_type=Debug
$ conan install .  # For Release
```
You don't need the arch or the generator, they are already defined in your profile and in the conanfile.txt.  There is already some initiative for a Visual Studio plugin that will automate this, but still not there. In the meantime, you can also put a ``install.bat`` script in the root that contains those two lines.

**Comment by memsharded** [comment]
The other thing you are reporting, seems an issue in the ``lzma/5.2.3@bincrafters/stable`` package, not a conan issue. It deserves to be reported in the bincrafters github repo, so they can know it, please do so. Many thanks for all your feedback!

**Comment by sinall** [comment]
Yes, let me transfer this issue to bincrafters.
