### ISSUE TITLE
Unable to build OpenSSL debug lib on VS2015

### ISSUE THREAD

**Issue by sinall** [conan-io/conan#3057]
### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2o**
* Operating System: **Windows 10 64bit**
* Compiler+version: **VC++ 2015  R3**

### Steps to reproduce (Include if Applicable)
conanfile.txt
```
[requires]
boost/1.67.0@conan/stable
cpprestsdk/2.10.1@bincrafters/stable
libzip/1.5.1@bincrafters/stable
zlib/1.2.11@conan/stable

[generators]
visual_studio

[options]
boost:shared=False

```

conan profile show default
```
Configuration for profile default:

[settings]
arch=x86
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
[options]
[build_requires]
[env]

```

conan install . -s build_type=Debug --build OpenSSL

> Cross-build from 'Windows:x86_64' to 'Windows:x86'
> OpenSSL/1.0.2o@conan/stable: WARN: Package is corrupted, removing folder: D:\.conan\data\OpenSSL\1.0.2o\conan\stable\pac
> kage\aa5c970b18c1b1398e214a1c8d670e7a031ae0e2
> boost_package_tools/1.66.0@bincrafters/stable: Already installed!
> bzip2/1.0.6@conan/stable: Already installed!
> cmake_findboost_modular/1.66.0@bincrafters/stable: Already installed!
> lzma/5.2.3@bincrafters/stable: Already installed!
> zlib/1.2.11@conan/stable: Already installed!
> OpenSSL/1.0.2o@conan/stable: WARN: Forced build from source
> OpenSSL/1.0.2o@conan/stable: Installing build requirements of: OpenSSL/1.0.2o@conan/stable
> OpenSSL/1.0.2o@conan/stable: Build requires: [strawberryperl/5.26.0@conan/stable, nasm/2.13.01@conan/stable]
> ERROR: strawberryperl/5.26.0@conan/stable: Error in configure() method, line 29
>         raise Exception("Only windows supported for strawberry perl")
>         Exception: Only windows supported for strawberry perl
>

**Comment by dvetutnev** [comment]
Please add this params to default profile:
os_build=Windows
arch_build=x86

**Comment by memsharded** [comment]
This is a bit weird. I have tried to do:

```bash
$ conan install strawberryperl/5.26.0@conan/stable
```
With your profile, and it works well here. Could you please try also that command in isolation? Also, what conan version are you running?

**Comment by sinall** [comment]
@dvetutnev with those changes you mentioned, it's starting to build now.
@memsharded conan-1.4.3.
