### ISSUE TITLE
Conan wrongfully thinks a package is already installed

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3062]
I wonder how Conan thinks a package has been produced. I called `conan create` on one of my packages. The build failed during the `build()` call because I was running my unit tests but did not have the dependencies imported. So:

1. I added the `imports()` call to import the dependencies for the unit tests to be able to run.
2. I then called `conan create` with the `--keep-build` option because I just wanted to run my tests again. The build failed while testing the test_package, and in the traces I figured it was because the package was seen as already installed. It was looking for header files that were not available as the `package` dir was empty (of course, at step 1 the unit tests failed before I could call `cmake.install()`.
3. I then ran `conan create` **without** `--keep-build`, and was amazed to see the same problem: the software was still seen as "Already installed".

Traces for:

- step 1
- step 2
- [step 3](https://gitlab.com/sbarthelemy/conan-public-recipes/-/jobs/75229673)

Conan on Windows Server 2016

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
This could be a bug, yes.

I haven't been able to reproduce it so far, but verified that when something goes wrong in build, the "dirty" flag of the package is not properly cleared, after clearing the folder.

Will investigate further to try to fix this for 1.5. Thanks very much for reporting it.

**Comment by memsharded** [comment]
Hi, I was wrong, I couldn't reproduce that behavior, and I have not been able to reproduce the error. Could you please try to make something that is easier to reproduce locally? If it is something related to --keep-build and the build flow, it should be unrelated to CI. Thanks!

**Comment by memsharded** [comment]
Closing this ticket as not able to reproduce and stale
