### ISSUE TITLE
Move generic cpp_info functions out of JSON generator 

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3064]
I'm not sure about this request, looking for feedback. 

When writing custom generators, it might be easier to add a member function to the `cpp_info` class called: `to_dict()` or something, which basically does all the same things as the generator does here, minus the json_dump part. It effectively converts all the information into a generic data structure, comprised of only standard python containers ( dict of lists of dicts of lists of dicts). 

https://github.com/conan-io/conan/blob/develop/conans/client/generators/json_generator.py

Internally, the `cpp_info` class is represented as a strongly-typed object with various methods.  Exposing these classes to generator writers as public API has advantages and disadvantages.  
 This is a request effectively represents adding an alternative strategy for generator writers which has different advantages and disadvantages.  If added, generator writers would be able to choose which strategy works best for them.  Personally, I would like to write generators based on generic structures with well known methods rather than proprietary ones. 

Given the small amount of code, and the fact that it's already written and being used in a supported feature, it seems reasonable to provide both options by moving the related functions into the `cpp_info()` class and enabling any generator to use them. 

I suppose it could also be added into a new set of free functions under something like a "generator.tools" namespace if adding as a new member function is undesirable.  There are quite a few "generic" functions that i've borrowed via copy/paste from other generators that could go there also. 

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, I think it is not a bad idea.

My question is where to put this functionality. The JSon generator is taking information from different conanfile members: ``conanfile.dep_cpp_info``, ``conanfile.deps_env_info``, etc, not from ``conanfile.cpp_info``. Maybe as a free public function somewhere? I don't like very much it being a conanfile.some_method().
