### ISSUE TITLE
[question] append to the environment the required packages vars?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3066]
I need a context manager that appends to the environment all the variables set by the required packages (i.e. the python equivalent of virtualenv/virtualrunenv generators that can be used inside a consumer Conanfile). Does such thing exist?

**Comment by db4** [comment]
OK, finally found [apply-env docs](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?apply-env). The problem is that neither `apply_env = True` nor `with tools.environment_append(self.env)` are going to work for a consumer Conanfile. Should they?

**Comment by danimtb** [comment]
Hi @db4,

I think [RunEnvironment](https://docs.conan.io/en/latest/reference/build_helpers/run_environment.html#runenvironment) al well as taking advantage of [env_info](https://docs.conan.io/en/latest/reference/conanfile/methods.html?highlight=env_info#env-info) object from dependencies could probably solve your issue.

```
def build(self):
    env_build = RunEnvironment(self)
    with tools.environment_append(env_build):
        with tools.environment_append(self.deps_env_info.vars):
            # do whatever here
```

Please give it a try and let me know

**Comment by db4** [comment]
@danimtb,
```
with tools.environment_append(self.deps_env_info.vars):
```
works indeed, thanks a lot! (is `vars` property documented somewhere?) But why it's not applied by default for consumer recipes? Maybe it's just overlooked and should be fixed?

**Comment by lasote** [comment]
Hi @db4, you are right. All the vars applied by the requirements in their `self.env_info` will be automatically applied in the consumer, so no action is required. Is it not working? Could you provide some more information to debug it?

**Comment by lasote** [comment]
Could the issue be closed? Thanks!
