### ISSUE TITLE
CMake build helper should prevent CMake from writing to the "package registry"

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan#3070]
To help us debug your issue please explain:
- Conan version: 1.4.3

Use case is the following:
* Recipe uses the CMake build helper
* The `build()` method calls the `cmake.install()` instead of implementing the `package()` method
* Somewhere in the CMake build scripts there is a call to `export(PACKAGE)` 

The call to export package will cause the "cmake package registry" to be written with an entry pointing to the current build directory.
I've seen a scenario where this affects the results of CMake's `find_package()` even in projects that don't use conan at all, when invoked in the same machine where the conan package was built. 

It might better for the CMake build helper to define `CMAKE_EXPORT_NO_PACKAGE_REGISTRY` for convenience, which would prevent the local registry from being written at all (https://cmake.org/cmake/help/v3.11/variable/CMAKE_EXPORT_NO_PACKAGE_REGISTRY.html#variable:CMAKE_EXPORT_NO_PACKAGE_REGISTRY). 

I think it would make sense especially considering that with conan one might trigger builds for different settings/options on the same system, and to prevent package creation from altering the environment in anyway.

I could contribute if this suggestion sounds reasonable.

**Comment by memsharded** [comment]
Yes, I think it reasonable, I was not aware of this cmake behavior, thanks for reporting.

Are we sure this won't break anyone? Is it possible that some users are using this feature in some reasonable way?

Sure, if you could contribute it, I think it will be welcomed. Many thanks!

**Comment by lasote** [comment]
I think we should disable it. If someone complains we could reconsider to opt-in, but I don't think so. To keep a parallel cache with packages affecting globally to the user doesn't sound good. I checked my cmake local package cache and surprise!:

```
ls -la ~/.cmake/packages/
total 0
drwxr-xr-x  6 luism  staff  192 Mar 10 16:14 .
drwxr-xr-x  3 luism  staff   96 May 31  2017 ..
drwxr-xr-x  3 luism  staff   96 May 31  2017 cppnetlib
drwxr-xr-x  3 luism  staff   96 Feb 14 13:16 glog
drwxr-xr-x  5 luism  staff  160 May 15 01:29 jansson
drwxr-xr-x  3 luism  staff   96 Mar 10 16:14 libwebsockets
```
