### ISSUE TITLE
[Feature Request] Support -pr/--profile and -s for conan imports

### ISSUE THREAD

**Issue by sinall** [conan-io/conan#3072]
Conan version: 1.4.4.0
OS: Win 10 64bit
Compiler: VC++2015 U3

VC++ developers usually use both Debug and Release build_type. And the imports command copy different dlls from different locations. So currently I use conanfile.py and use `self.settings.build_type` variable to generate source location dynamically. It works for `conan install` because I can use a profile or pass settings argument from command line, but not for `conan imports`.

A real case is:

- `conan install` the dependencies
- Build project
- Make a installer from Release directory
It usually works fine, however sometime I need to clean or rebuild a project, then the dlls needs to be imported again.

Ideally, the 'props' files should have post-build step to import dlls, however AFAK cpprestsdk package doesn't do this so far.

So, it will be more flexible if `conan imports` supports -pr/--profile. then I could use `conan imports`  to import dlls without run `conan install` again.

===================
```
> conan imports --help
usage: conan imports [-h] [-if INSTALL_FOLDER] [-imf IMPORT_FOLDER] [-u] path

Calls your local conanfile.py or conanfile.txt 'imports' method. It requires
to have been previously installed and have a conanbuildinfo.txt generated file
in the --install-folder (defaulted to current directory).

positional arguments:
  path                  Path to a folder containing a conanfile.py or to a
                        recipe file e.g., my_folder/conanfile.py With --undo
                        option, this parameter is the folder containing the
                        conan_imports_manifest.txt file generated in a
                        previousexecution. e.j: conan imports ./imported_files
                        --undo

optional arguments:
  -h, --help            show this help message and exit
  -if INSTALL_FOLDER, --install-folder INSTALL_FOLDER
                        Directory containing the conaninfo.txt and
                        conanbuildinfo.txt files (from previous 'conan
                        install'). Defaulted to --build-folder
  -imf IMPORT_FOLDER, --import-folder IMPORT_FOLDER
                        Directory to copy the artifacts to. By default it will
                        be the current directory
  -u, --undo            Undo imports. Remove imported files

```

**Comment by lasote** [comment]
The `install` and `imports` commands are decoupled. If we added the `-pr` to the imports, internally it would call to `install` again, because you need to have the installed packages to import from, right?

So, why do not call again to `install` with a different build_type and then call `imports` with the `--if` pointing to the install folder? 

I don't see the value in coupling the commands to avoid a natural step of calling "install" with a different configuration. Am I missing something?

Thanks!

**Comment by sinall** [comment]
The `-pr` option doesn't have to make `imports` couple with `install`.

This is an example:
> from conans import ConanFile
> 
> class MyConan(ConanFile):
> 	settings = "os", "compiler", "build_type", "arch"
> 
> 	requires = (
> 		"boost/1.66.0@conan/stable",
> 		"cpprestsdk/2.10.2@bincrafters/stable",
> 		"libzip/1.5.1@bincrafters/stable",
> 		"zlib/1.2.11@conan/stable"
> 	)
> 	
> 	generators = "visual_studio_multi"
> 	
> 	default_options = (
> 		"cpprestsdk:shared=True",
> 		"libzip:shared=True",
> 		"zlib:shared=True"
> 	)
> 		
> 	def imports(self):
> 		self.copy("*.dll", "..\\" + str(self.settings.build_type), "bin")
> 

If imports doesn't take `-pr` or `-s`, then it doesn't know the correct `self.settings.build_type`, but on the other hand this is a valid conanfile.py.

**Comment by memsharded** [comment]
Hi @sinall 

I think some clarification might help:
- Local commands, like ``build`` or ``imports`` rely on having defined a given dependency graph for a given configuration. Lets say, the dependencies have to be installed first, then, it is impossible to ``imports`` from them, or to build the current project. So the first, always necessary step is to do a ``conan install`` with the desired configuration
- Those local commands will read the information from ``install`` to be able to do their task correctly.
- Take into account that by default, ``conan install`` already and automatically calls ``imports()``. 
- The ``conan import`` command is only useful if you want to decouple the commands with:
```bash
$ conan install --no-imports
$ conan import
```

**Comment by sinall** [comment]
@memsharded @lasote Let me make it clear.
I don't want to couple `conan imports` and `conan install`.

I will run `conan install` first and `conan imports` next. That's for sure.

The current problem is: `conan imports` doesn't take `-pr` and `-s` arguments, right?
On the other hand, the conanfile.py doesn't forbid me from referring `self.settings` variable. But without supporting `-pr` and `-s` arguments, can `conan imports` use the correct `self.settings` variable?

**Comment by lasote** [comment]
>  But without supporting -pr and -s arguments, can conan imports use the correct self.settings variable?

It should based on the information read in the `conaninfo.txt` generated in the `--install-folder`

**Comment by memsharded** [comment]
> But without supporting -pr and -s arguments, can conan imports use the correct self.settings variable?

Yes, conan will use the correct ``self.settings``, it is stored in the conaninfo.txt file generated at ``conan install`` time.

**Comment by sinall** [comment]
Thanks @lasote @memsharded 

I guess I may need 2 install folders for conaninfo at this moment, one for Debug and one for Release.

It seems that the '[visual_studio_multi](https://docs.conan.io/en/latest/reference/generators/visualstudiomulti.html)' generator has some potential issue.

> Usage
> $ conan install . -g visual_studio_multi -s arch=x86 -s build_type=Debug
> $ conan install . -g visual_studio_multi -s arch=x86_64 -s build_type=Debug
> $ conan install . -g visual_studio_multi -s arch=x86 -s build_type=Release
> $ conan install . -g visual_studio_multi -s arch=x86_64 -s build_type=Release

Does those commands override the same conaninfo.txt? If that's the case, then only the dlls identified by the last command could be imported.

**Comment by lasote** [comment]
Yes, you are right. The conaninfo is being overwritten if you want the imports to distinguish the installed configuration. The "multi" approach is clearly not perfect for that goal.

> So I guess the most elegant way for VC++ is importing dlls in post-build step in props file.

I think it could work. Let us know how it goes.

**Comment by sinall** [comment]
@lasote 
https://github.com/bincrafters/community/issues/319#issuecomment-397863397

**Comment by sinall** [comment]
@lasote consider below steps:

1. `conan install . --install-folder conaninfo/Debug`
    **conaninfo\Debug\conan_imports_manifest.txt** will be created.
2. `conan imports . --install-folder conaninfo/Debug`
    Then **conan_imports_manifest.txt** will be created.

Should both of the 2 commands create conan_imports_manifest.txt into same location?

**Comment by sinall** [comment]
@lasote consider below steps:

conan install . --install-folder conaninfo/Debug
conaninfo\Debug\conan_imports_manifest.txt will be created. And the target folder is relative to conaninfo/Debug.
conan imports . --install-folder conaninfo/Debug
Then conan_imports_manifest.txt will be created. And the target folder is relative to '.'.
Should both of the 2 commands create conan_imports_manifest.txt into same location, and the target folder is relative to same folder(--install-folder)?

**Comment by lasote** [comment]
> conan imports . --install-folder conaninfo/Debug -imf conaninfo/Debug

Sure, the import folder can be also specified. 

You could also change to `conaninfo/Debug` and do the conan install and conan imports from there.
