### ISSUE TITLE
Conan search do not resolve "alias" in the server

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#3074]
So I use alias to support using any patch version of Qt.

conan alias Qt/5.9.X@Fred/stable Qt/5.9.6@Fred/stable

then upload to Artifactory CE

conan upload Qt/5.9.X@Fred/stable --all -r localArtCE    ( yes probably did not need "all")

Then a 
conan search Qt/5.9.6@Fred/stable --table=file.html -r=localArtCE

works fine ... but a 
conan search Qt/5.9.X@Fred/stable --table=file.html -r=localArtCE

gets lost and doesn't follow the alias, basically coming up empty.

I would have hoped it would have followed the 5.9.6 path.

**Comment by lasote** [comment]
Yes, it is a limitation of the search. During an install, the alias is downloaded and processed and then "substituted" by the real reference. During an install, the server is doing all the work, but the server is not processing the recipe nor resolving the alias, just search for the literal reference you are searching.

**Comment by memsharded** [comment]
I am not sure that it is really server side, maybe the alias should be checked in the client and redirected the same way it is done in the install.

**Comment by lasote** [comment]
But for checking the alias in the client, you have to download it, and the server is not downloading anything in the search, right?

**Comment by memsharded** [comment]
Oh, yes, you are right...

**Comment by memsharded** [comment]
This issue has been stale for years.

It seems it will not be possible to evaluate alias on the servers, as it requires server side evaluation, which is a security risk, and de-referencing alias automatically would be inconsistent with the current behavior for version ranges: ``conan search zlib/[>1.2]@`` does not resolve the version range to list the binaries of zlib/1.2.11. So for consistency, it seems that ``conan search <ref>`` should always list the binaries of the provided ref, without further resolving ``<ref>``. 

Same reasoning has been applied in https://github.com/conan-io/conan/issues/4105.

So I think this can be closed, both for the impossibility of resolving alias server-side, the complexities of doing it client-side, and the consistency with other current existing behaviors and commands in Conan.
