### ISSUE TITLE
[workspaces] Workspaces do not support build requirements

### ISSUE THREAD

**Issue by mherb** [conan-io/conan#3075]
I tried to use the [workspaces feature](https://docs.conan.io/en/latest/developing_packages/workspaces.html) included in 1.4.4 with some of our existing packages using custom generators. The generators are implemented as packages as recommended in the [documentation](https://docs.conan.io/en/latest/howtos/custom_generators.html) and used in the packages as `build_requires`.
Unfortunately workspaces do not seem to resolve build_require dependencies at all, neither for custom generators nor for other build-require packages, which causes either generator execution or builds to fail because of lacking dependencies. This is not really desirable since this restricts the use of workspaces exclusively to packages not relying on any dedicated build requirements.

The behavior can be reproduced easily with the [conan-workspace-example project](https://github.com/memsharded/conan-workspace-example) by modyfing (for instance) the conanfile in `C` as:

    build_requires = "MyCustomGenerator/0.1@user/testing"
    generators = "cmake", "MyCustomGenerator"

When performing a `conan install` independently (without any workspace whatsoever) everything works fine:

    PROJECT: Installing path/to/conan-workspace-example/C/conanfile.py
    Requirements
    Packages

    PROJECT: Installing build requirements of: PROJECT
    PROJECT: Build requires: [MyCustomGenerator/0.1@user/testing]
    PROJECT: Requirements
    PROJECT:     MyCustomGenerator/0.1@user/testing from local cache
    PROJECT: Packages
    PROJECT:     MyCustomGenerator/0.1@user/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    PROJECT:
    MyCustomGenerator/0.1@user/testing: Already installed!
    PROJECT: Installed build requirements of: PROJECT
    PROJECT: Generator cmake created conanbuildinfo.cmake
    PROJECT: Generator MyCustomGenerator created mygenerator.file
    PROJECT: Generator txt created conanbuildinfo.txt
    PROJECT: Generated conaninfo.txt

but a `conan install` on the workspace results in

    Workspace: Installing...
    Requirements
        HelloA/root@project/develop from 'conanws.yml'
        HelloB/0.1@user/testing from 'conanws.yml'
        HelloC/0.1@user/testing from 'conanws.yml'
    Packages
        HelloA/root@project/develop:d3b75bea792043ae6acc5b8ca1c9f3dda22b70a8
        HelloB/0.1@user/testing:9bce763e209adc09991d1fa26f6ec73dbb988c0d
        HelloC/0.1@user/testing:85f780d0530411a64b0be4407b381706014b445d

    Workspace HelloC: Generator cmake created conanbuildinfo.cmake
    ERROR: Invalid generator 'MyCustomGenerator'. Available types: cmake_multi, visual_studio, gcc, qbs, cmake, xcode, cmake_paths, visual_studio_multi, virtualenv, qmake, virtualbuildenv, compiler_args, scons, json, boost-build, ycm, visual_studio_legacy, cmake_find_package, txt, pkg_config, virtualrunenv

As mentioned before this also happens with regular packages, leading to missing package infos (lib/includedirs etc) in the generated files.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, this is likely an issue. Not fully verified it yet, but very possible.
Will try to check it before 1.5, but most likely will have to wait for later, lets see what is possible. 

Thanks very much for the detailed report, it helps a lot!

**Comment by mherb** [comment]
Just checked on develop and works now, thanks a lot!

**Comment by memsharded** [comment]
Great, thanks for telling. We will release it in 1.5 asap, maybe tomorrow or Thursday.
