### ISSUE TITLE
AutoToolsBuildEnvironment sometimes overwrites manually provided --prefix argument

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#3078]
I pinpointed the problem in this pull request comment: https://github.com/conan-io/conan/pull/2717/files#r196521803

**Comment by lasote** [comment]
But, why is not a single parameter `--prefix=/foobar`?

**Comment by memsharded** [comment]
AutoToolsBuildEnvironment deprecated in favor of https://docs.conan.io/en/latest/reference/conanfile/tools/gnu.html tools
