### ISSUE TITLE
VisualStudioBuildEnvironment uses semicolon as a delimiter

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#3080]
`SET CL=-MDd;%CL%`

And this is what cl.exe does not like:

```
cl : Command line warning D9002 :
ignoring unknown option '-MDd;'
```

delimiter should be a space instead of a semicolon as documented here: https://msdn.microsoft.com/en-us/library/kezkeayy.aspx

https://github.com/conan-io/conan/blob/d62ac20f21d73b1d681c3d138034a0d70b9a513e/conans/client/build/visual_environment.py#L55

cc/ @db4

**Comment by lasote** [comment]
The underlying problems seem to be `VirtualEnvGenerator` (parent of VirtualBuildEnvGenerator)
