### ISSUE TITLE
Downloads from certain SSL domains fails in OSX

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#309]
An issue from the underlying python requests library conan is using for http communication. Building the Openssl package can fail (in latest OSX, previous versions and travis OSX work fine), because it is unable to download the openssl sources from the openssl page due to a SSL violation. 

Initially reported by @tru

Attempted to create a 0.9.3 minor adding some requirements as pointed out in https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484, but that breaks the Win and Linux versions.

**Comment by memsharded** [comment]
This has been released in minor 0.9.4 (though the homebrew recipe in OSX has not been merged yet: https://github.com/Homebrew/homebrew-core/pull/1968)

**Comment by lasote** [comment]
We are close... but no merged yet. When it's approved will update it to 0.10.0 (should be quick)
https://github.com/Homebrew/homebrew-core/pull/2190

**Comment by lasote** [comment]
Should be ok now! Please, try it and reopen if it keeps failing.
