### ISSUE TITLE
[build system] [cmake] Add support for setting custom CMake variables in conan profiles

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#3099]
I am using conan version 1.4.4.

This feature request is similar to #1447, but it would allow passing arbitrary CMake parameter from the profile. The rationale for this is to allow developers to have a profile that overrides some default toolchain parameter or specifies some well-known CMake variable.

My current workaround for this issue is to allow developers to specify environment variables with prefix `CONAN_CMAKE_CUSTOM_` in their profile and use a custom toolchain that overrides Conan's built-in CMake build helper. The implementation of that helper is trivial:

```python
from conans import CMake
import os

class CMake(CMake):
    def configure(self, args=None, defs=None, source_folder=None, build_folder=None,
              cache_build_folder=None, pkg_config_paths=None):
        env_prefix = "CONAN_CMAKE_CUSTOM_"
        cmake_params = ["-D%s=%s" % (key.replace(env_prefix, ''), value) for key, value in os.environ.items() if key.startswith(env_prefix)]
        if args is not None:
            args.extend(cmake_params)
        else:
            args = cmake_params
        super(CMake, self).configure(args=args, defs=defs, source_folder=source_folder, build_folder=build_folder, cache_build_folder=cache_build_folder, pkg_config_paths=pkg_config_paths)
```
It's used like this:

```python
from conans import ConanFile

class Test(ConanFile):
    build_requires = "CMakeHelper/[>=1.0.0]@demo/testing"
    generators = "cmake"

    def build(self):
        from my_helpers import CMake
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

The downside is that every conanfile must explicitly depend on my custom toolchain and in its `build` method it must first import this version of `CMake` build helper, which is not very invasive, especially if the project is under your control, but it would be nicer if that could be avoided.

For example, a developer could set `CMAKE_CXX_COMPILER_LAUNCHER` CMake variable within their profile if they want to use compiler launchers, such as `ccache` or `distcc`. 

Similarly, if a custom toolchain is specified with `CONAN_CMAKE_TOOLCHAIN_FILE` and this custom toolchain can be parametrized - instead of creating wrapper toolchain files that sets up the parameters and includes the base toolchain *and* Conan profiles to use those wrapper toolchains, one could simply have one toolchain file and several profiles that include the base profile, specifying the toolchain, and add or override parameters from the base profile.

The second example would open a path to create profiles to use Android NDK as is, without the need for creating standalone toolchains for each ABI/API level/STL combination. The base android profile would simply specify `android.toolchain.cmake` that is distributed with NDK and other profiles would include it and specify ABI, API level and STL as needed.

Would adding such a feature to the official conan CMake build helper break anything? If no, would you be interested in adding it, at least via environment variable hack (like I did), but ideally with cmake-specific section in profile that would be ignored for other generators?

**Comment by memsharded** [comment]
I think your approach of overriding the helper makes a lot of sense.
The thing with implementing this built-in, is that it is not generic for all build systems: would that mean that it will be necessary to use ``CONAN_VS_CUSTOM_`` variables for Visual Studio, and similarly for others?

Altough possible, it doesn't look like a clean solution, but more like a hack. We are now considering how the build systems integration could be improved. One of the things is to allow providing custom helpers like yours CMake one, easier (maybe with the new python_requires). But we will definitely take this into account, thanks very much for the feedback.

**Comment by DoDoENT** [comment]
> The thing with implementing this built-in, is that it is not generic for all build systems ...

I agree, but I doubt that there is a solution that is generic enough for all build systems. Even CMake didn't manage to create that - just think of CMAKE_CXX_STANDARD variable: up until recently it was not possible to set `/std:c++latest` on VS and `-std=gnu++2a` using that variable and it is still not possible to set `-std=c++17` or `-std=c++2a` (CMake generators always force `-std=gnu++17` and `-std=gnu++2a`, which is not what you always want).

> Altough possible, it doesn't look like a clean solution, but more like a hack.

The environment variable thing is definitely a hack and I agree it's ugly. My idea is more like this:

- enable setting default generator in profile (I believe this is already possible within `[settings]` section, but I have not yet mastered Conan so deeply)
- besides `settings`, `options`, `environment variables` and `build requirements`, allow generator-specific sections in profiles. For example:

```
[settings]
setting=value
generator=cmake

[options]
MyLib:shared=True

[env]
env_var=value

[build_requires]
Tool1/0.1@user/channel
Tool2/0.1@user/channel, Tool3/0.1@user/channel
*: Tool4/0.1@user/channel

[cmake_generator]
cmake_variable=value

[cmake_multi_generator]
cmake_variable=value

[xcode_generator]
xcode_variable=value

[visual_studio_generator]
vs_specific_setting=value
```

Options available within each generator-specific section would be consumed only if that specific generator is being used and ignored otherwise. Also, it would be very flexible, as each generator could define its own set of options that could be specified within profiles.

The solution would not be generic for all generators, although it would be possible to have `[generic_generator]` section, whose options all generators must obey (but that wouldn't be very different from `[env]`, would be?), but it would be very flexible. For example, iOS developers could have a profile with Xcode generator set as default and some Xcode-specific settings within it (e.g. whether bitcode is enabled or not), Android developers could have profiles as described in my original post, without the need for standalone toolchains (of course they could have them, if they wanted), Windows developers could create one profile for VS 2013 and WindowsPhone 8.1, another one for VS 2017 and UWP and so on - the possibilities are endless and, in my opinion, the solution is much cleaner than polluting the environment with generator-specific environment variables and have developers rely on custom generators/helpers that override the default ones.

**Comment by memsharded** [comment]
Yes, this totally align with one of the currently considered features, we call it "generators with arguments", and @lasote is going to like your suggestion!

I am going to temptatively approve it, not clear when it will be possible, but at least is something that we will likely implement. Thanks very much for the feedback!

**Comment by lasote** [comment]
The idea looks very very interesting. But I'm not sure this is the same thing that the generators parameters because here we are declaring "variables" for an specific generator, and for me it is not totally clear what it means:

- When you say:

> For example, iOS developers could have a profile with Xcode generator set as default and some Xcode-specific settings within it (e.g. whether bitcode is enabled or not),

How the variable will look like in the generated xcode properties file? Now we could repeat the same question for the N generators we have. The concept of a variable in a generator it is not clear and sometimes it makes no sense, it depends on the generator.

- We should question if this "variables" are part of the generator (dependencies) or the current build information. I think the variables should not be part of the generators.

I totally agree with the need, I like the flexibility, but I think the approach it is not still clear. I'm removing the `feature approved` because we have to think about it.

**Comment by DoDoENT** [comment]
> When you say:
>>For example, iOS developers could have a profile with Xcode generator set as default and some Xcode-specific settings within it (e.g. whether bitcode is enabled or not),
>
>How the variable will look like in the generated xcode properties file? Now we could repeat the same question for the N generators we have. The concept of a variable in a generator it is not clear and sometimes it makes no sense, it depends on the generator.

For example, in this specific case, the profile would look like this:

```
[settings]
os=iOS
os_build=Macos
compiler=apple-clang
generator=xcode

[build_requires]
darwin-toolchain/1.0@theodelrieu/stable

[xcode_generator]
# note that those are specific to Xcode and are exactly the same as stored withing Xcode's
# xcconfig or pbxproj files
ENABLE_BITCODE[variant=Release]=YES
BITCODE_GENERATION_MODE[variant=Release]=bitcode
```

The generated `conanbuildinfo.xcconfig` would simply have the unmodified values defined under `[xcode_generator]` section. Other generators (VS, cmake, ...) would simply ignore the `[xcode_generator]` section as it does not affect them.

Assuming the above profile is called `my-ios-profile`, when issuing command `conan install /path/to/conanfile.py -pr my-ios-profile`, conan would automatically use `xcode` generator, even if `conan.conf` has different generator set as default. And furthermore, the generated xcconfig file would immediately contain additional xcode variables specified by profile's `[xcode_generator]` section.

The same logic can be defined for other generators that support configuring, such as CMake and (probably) Visual Studio (I am not VS user, so I wouldn't know).

> - We should question if this "variables" are part of the generator (dependencies) or the current build information. I think the variables should not be part of the generators.

I think that those variables are part of the profile, i.e. the combination of generator and build information. I agree that variables cannot be part of the generators because the same generator can be used on different projects. However, the profiles are exactly the "thing" that binds the common build requirements, common build settings and common build options - so why not also adding generator to it and parameters for specific generators?

For more motivation, let me share my android NDK profiles with you. They rely on having the cmake helper I described in my first post:

`android-ndk-r17b` profile:
```
# settings section is required because those cannot be changed from AndroidNdk's conanfile
# see comment below in package_info method
[settings]
os=Android
os.api_level=16
compiler=clang
compiler.libcxx=libc++
compiler.version=6.0

[build_requires]
AndroidNdk/r17b@demo/testing
CMakeHelper/[>=1.0.0]@demo/testing
```

And profiles for specific architectures are as simple as:
`android-armeabi-v7a` profile:
```
include(android-ndk-r17b)

[settings]
arch=armv7

[env]
CONAN_CMAKE_CUSTOM_ANDROID_ABI=armeabi-v7a
CONAN_CMAKE_CUSTOM_ANDROID_ARM_NEON=ON
```

The most beautiful part is that `AndroidNdk` package does not have to build standalone toolchains for each STL/architecture/API_level combination - it can be as simple as this (the downloading is deliberately within `build()` to allow creating packages for windows and linux from my mac):

```python
from conans import ConanFile, tools
import os


# Based on https://github.com/lasote/conan-android-ndk/blob/master/conanfile.py
# and on https://github.com/lasote/conan-android-toolchain/blob/master/conanfile.py
class AndroidndkConan(ConanFile):
    name = "AndroidNdk"
    version = "r17b"
    url = "https://developer.android.com/ndk/downloads/"
    description = "Android NDK toolchain"
    settings = None
    options = {"host_os": ["linux", "windows", "darwin"], "host_arch": ["x86", "x86_64"]}
    no_copy_source=True


    def config_options(self):
        os_info = tools.OSInfo()
        if os_info.is_linux:
            self.options.host_os = "linux"
        elif os_info.is_windows:
            self.options.host_os = "windows"
        elif os_info.is_macos:
            self.options.host_os = "darwin"
        else:
            raise Exception("Unsupported platform")

        import sys
        is_64bits = sys.maxsize > 2 ** 32
        if is_64bits:
            self.options.host_arch = "x86_64"
        else:
            self.options.host_arch = "x86"


    def build(self):
        url = "https://dl.google.com/android/repository/android-ndk-%s-%s-%s.zip" % (self.version, self.options.host_os, self.options.host_arch)

        tools.download(url, "ndk.zip")
        tools.unzip("ndk.zip", keep_permissions=True)
        os.unlink("ndk.zip")


    def package(self):
        self.copy("*", src="android-ndk-%s" % self.version)


    def package_info(self):
        self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, 'build', 'cmake', 'android.toolchain.cmake')
        self.env_info.CONAN_CMAKE_CUSTOM_ANDROID_TOOLCHAIN = "clang"
        self.env_info.CONAN_CMAKE_CUSTOM_ANDROID_PLATFORM = "android-16"
        self.env_info.CONAN_CMAKE_CUSTOM_ANDROID_STL = "c++_static"
        # It would be nice if we could export here information about os, compiler, STL and its version
        # so profiles would not have to be in sync - they could simply set this package as build
        # requirement
        # Something like:
        # self.settings_info.os = "Android"
        # self.settings_info.os.api_level = "16"
        # self.settings_info.compiler = "clang"
        # self.settings_info.compiler.version = self.obtainCompilerVersion()
        # self.settings_info.compiler.libcxx = "libc++"
        # And after that, manually setting different compiler, STL or compiler version from command
        # line parameters would trigger a conflict and report error to user.
```

Now, image that instead of having

```
[env]
CONAN_CMAKE_CUSTOM_ANDROID_ABI=armeabi-v7a
CONAN_CMAKE_CUSTOM_ANDROID_ARM_NEON=ON
CONAN_CMAKE_CUSTOM_CMAKE_ANDROID_ARM_NEON=ON
```

the profile would contain

```
[cmake_generator]
ANDROID_ABI=armeabi-v7a
ANDROID_ARM_NEON=ON
```
 
and `package_info` would be something like this:

```python
    def package_info(self):
        self.generator_info['cmake'].CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, 'build', 'cmake', 'android.toolchain.cmake')
        self.generator_info['cmake'].ANDROID_TOOLCHAIN = "clang"
        self.generator_info['cmake'].ANDROID_PLATFORM = "android-16"
        self.generator_info['cmake'].ANDROID_STL = "c++_static"
        # Also same comment as above - but that is perhaps for another issue?
```

@lasote, @memsharded, is there anything else that is still not clear?

**Comment by lasote** [comment]
Conceptually I'm not opposed to enabling some argument (based on the ongoing #3508) for some generators, even to declare custom variables. But the interface should be explicit, documented and well know, and only when we activate an argument for a generator with a concrete implementation.

**Comment by blockspacer** [comment]
Will CMake variables in conan profiles be able use information from build_requires?

[build_requires]
gcc/master@conan/stable

I want to set CMAKE_CXX_COMPILER based on self.deps_cpp_info["gcc"].rootpath + "/bin/gcc" in conan profile, but profile is just text file. Can conan hooks be used as temporary solution?

Looks like profile must become dynamic i.e. profile in text file was bad idea.

**Comment by memsharded** [comment]
Passing arbitrary CMake variables can be done with ``CMakeToolchain`` integration: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/inject_cmake_variables.html

For compilers, better use ``tools.build:compiler_executables`` new conf.
