### ISSUE TITLE
[build system] [MSBuild] Abilty to set WindowsSDKVersion when using MSBuild build helper

### ISSUE THREAD

**Issue by L-M-V** [conan-io/conan#3102]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

It would be nice to be able to use `/p:WindowsTargetPlatformVersion` (WindowsSDKVersion ) when using the msbuild build helper (similar functionality to the tools.vcvars_command()). 

Unless there is a way to pass arbitrary property flags to the msbuild build command call?

```
if winsdk_version:
   command.append("/p:WindowsTargetPlatformVersion=%s" % winsdk_version)
```

**Comment by lasote** [comment]
I think it might be a duplicated of: https://github.com/conan-io/conan/issues/3048
WDYT? Could this one be closed?

**Comment by Minimonium** [comment]
@lasote MSBuild should mirror an attribute `winsdk_version` of `https://docs.conan.io/en/latest/reference/tools.html#tools-vcvars-command` .
