### ISSUE TITLE
Abilty to "prebuild" all listed requirements in a conanfile without output

### ISSUE THREAD

**Issue by L-M-V** [conan-io/conan#3103]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

At the moment we have the following script which we use to "pre-build" our conan dependencies after we've installed our local recipes. Unfortunately there doesn't seem to be a way to specify a no-output mode to conan install so we have to pass an install folder in and then subsequently remove the conanbuildinfo.txt. Is it possible to build all requirements of a conanfile.[txt|py] with some specified settings with no output? 
```
if __name__ == "__main__":
    check_call(['conan', 'install', 'conanfile.py', 'build_type=Debug',   '-if=ConanInstall', '--build=missing'])
    check_call(['conan', 'install', 'conanfile.py', 'build_type=Release',  '-if=ConanInstall', '--build=missing'])
    shutil.rmtree("ConanInstall")

```

**Comment by memsharded** [comment]
I am not sure about the use case. ``conan install`` without generating some files (like conanbuildinfo.cmake) that could be used for consumption seems a bit useless. Could you please ellaborate a bit further? what would be your complete flow, and the step after the one you are commenting? Thanks for the feedback!

**Comment by L-M-V** [comment]
Our project is setup up as following: 
We have an 'in-repository' store of recipes rather than setting up a conan server which dispenses recipes as we haven't had the time/resources to setup a globally accessible server. 
So the first step after cloning the main project is:
ExportRecipes.py
 ```
    packageReference = "Company/stable"
    os.chdir("ConanRecipes")
    recipesToInstall = os.listdir(".")

    for recipe in recipesToInstall:
        if os.path.isdir(recipe):
            call(['conan', 'export', recipe, packageReference])
```
Which goes through and exports all the recipes for that commit.

We then have a main CMakeLists.txt which uses conan.cmake to integrate with those recipes. 
```
conan_cmake_run(CONANFILE      "conanfile.py"
                BASIC_SETUP
                CMAKE_TARGETS
                NO_OUTPUT_DIRS
                BUILD          missing)
```
However there's some inherent limitations with conan.cmake. 
1. Some recipes will **fail** to build when called from cmake which calls `conan install`. I haven't tracked down the exact cause yet, but the recipes which are using cmake to build themselves get confused by the "nested" cmakes and can't find environment variables and/or paths.  So our current workaround to this issue is to call conan install first before we can call cmake. 

2. conan.cmake gets very confused if you are using a different cmake compiler than the command line compiler (i.e. when you select clang when it's normally a gcc setup). And you get the following error:
```
Incorrect 'clang', is not the one detected by CMake: 'GNU'
```
So we now have hack in our cmake file to handle this case:
```
if (NOT ENV{CXX})
   message(STATUS "Set CXX to: ${CMAKE_CXX_COMPILER}")
   set(ENV{CXX} ${CMAKE_CXX_COMPILER})
   set(OVERWRITTENCXX ON)
endif()
if (NOT ENV{CC})
   message(STATUS "Set CC to: ${CMAKE_C_COMPILER}")
   set(ENV{CC} ${CMAKE_C_COMPILER})
   set(OVERWRITTENCCC ON)
endif()
conan_cmake_run(CONANFILE      "conanfile.py"
                BASIC_SETUP
                CMAKE_TARGETS
                NO_OUTPUT_DIRS
                BUILD          missing)

if (OVERWRITTENCXX)
   unset(ENV{CXX})
   unset(OVERWRITTENCXX)
endif()
if (OVERWRITTENCC)
   unset(ENV{CC})
   unset(OVERWRITTENCC)
endif()
```

So I'd like to setup "InitialRepositorySetup" script which exports/updates all our recipes, builds all listed dependencies our root conanfile.py in both debug and release mode(which can take a while) and have the repository 'good to go' so to speak - ready to call cmake and start adding new features and the like. 

Note:
Initially I tried this instead (using conan create instead of export):
```
    packageReference = "Company/stable"
    os.chdir("ConanRecipes")
    recipesToInstall = os.listdir(".")

    for recipe in recipesToInstall:
        if os.path.isdir(recipe):
            call(['conan', 'create', '-s', 'build_type=Debug', recipe, packageReference])
            call(['conan', 'create', '-s', 'build_type=Release', recipe, packageReference])
```
however this involves me getting the ordering of `recipesToInstall` to match the recipe dependency tree, which is what conan can do much better than I can.

**Comment by memsharded** [comment]
> Some recipes will fail to build when called from cmake which calls conan install. I haven't tracked down the exact cause yet, but the recipes which are using cmake to build themselves get confused by the "nested" cmakes and can't find environment variables and/or paths. So our current workaround to this issue is to call conan install first before we can call cmake.

Yes, conan.cmake is basically intended for pure consumers, not to create packages! Please be sure to check https://github.com/conan-io/cmake-conan#creating-packages

If you want, please join the #conan channel in CppLang slack for discussing these things (write us to info@conan.io for details)

**Comment by L-M-V** [comment]
I'm not creating any packages in the conan.cmake call - it's simply calling conan_cmake_run on our consumer project's conanfile and building any missing dependencies because of the `BUILD          missing` argument. 

The slack sounds good, I'll set it up later today.

**Comment by memsharded** [comment]
Closing this ticket as outdated:
- Conan 2.0 no longer generates conanbuildinfo.txt file (or other files it used to create)
- The cmake-conan integration is also new for 2.0
