### ISSUE TITLE
[build system] [MSBuild] msbuild: generate props file with dependent libraries list for linking

### ISSUE THREAD

**Issue by Ri0n** [conan-io/conan#3105]
conan-1.4.5

If I understand correctly Conan now passes LIB environment variable as dependent libraries search path, and generates props file include directories and other compiler flags. (btw documentation is totally unclear about this, so I had to dig to the Conan sources a lot)
What Conan doesn't do is generation of a list of libraries to link with. So it's supposed Visual Studio project file already has valid names of libraries what unfortunately is not always true.

What I suggest is to add an option to generate the libraries list as well. So a maintainer of a package can use something like replace_in_file to remove known invalid libraries names from a project file and let Conan do its business with linking.

Usually it's not an issue when VS files are also maintained by the same maintainer, otherwise it is.

**Comment by memsharded** [comment]
This is the extract of the VS generator:
```xml
<Link>
      <AdditionalLibraryDirectories>{lib_dirs}%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>{libs}%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalOptions>{linker_flags} %(AdditionalOptions)</AdditionalOptions>
    </Link>
```

I think the problem is that Visual Studio doesn't use other environment variables rather than LIB and /I, so defining other environment variables have no effect:

https://msdn.microsoft.com/en-us/library/19z1t1wy.aspx
https://msdn.microsoft.com/en-us/library/fwkeyyhe.aspx
https://msdn.microsoft.com/en-us/library/9s7c9wdw.aspx

So the only way to achieve this would be to inject the generated file somehow. It might make sense to provide some functionality to simplify this, and make it possible to make it programmatically, and not via de IDE

**Comment by Ri0n** [comment]
msbuild already has code generating props file which is injected automatically https://github.com/conan-io/conan/blob/develop/conans/client/build/msbuild.py#L104

But currently there is nothing about dependent libraries.

**Comment by memsharded** [comment]
> But currently there is nothing about dependent libraries.

There are 2 different files. One of them, the one in https://github.com/conan-io/conan/blob/develop/conans/client/build/msbuild.py#L104, is used for the current project configuration, to make sure it is compatible with the given settings (basically setting the runtime).

All the dependencies information is set in the generated ``conanbuildinfo.props`` which is not passed in the same way. It is not only the LIBS, but also the include paths, library paths, definitions needed to set... all of them are in the ``conanbuildinfo.props``, so it wouldn't be enough to set the LIBS in that other temporary .props file, that is injected dynamically. 

I agree that this need some improvements, and not only this, but also other generators/build-helpers need a re-thinking how conan integrates with them. This is the reason I renamed this issue as ``[build system]``, to easily classify them and propose a new approach that is aligned with other build systems too (and not breaking, unless until conan 2.0)
