### ISSUE TITLE
Dependency override still results in conflict error

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan#3107]
My library foo depends on CppRestSDK and [JWT-cpp](https://github.com/pokowaka/jwt-cpp).

Requirements function from CppRestSDK conanfile.py:

```
def requirements(self):
        self.requires.add("OpenSSL/1.0.2o@dynniq/stable")
        self.requires.add("zlib/1.2.11@dynniq/stable")
        self.requires.add("Boost/1.66.0@dynniq/stable")
        if not self.options.exclude_websockets:
            self.requires.add("websocketpp/0.7.0@dynniq/stable")
```

Requirements attribute from JWT-cpp conanfile.py:

```
requires = (
       "OpenSSL/1.1.0h@dynniq/stable"
    )
```

Requirements attribute from lib foo conanfile.py:

```
requires = ( "jwt-cpp/1.1.0@dynniq/stable",
                 "cpprestsdk/2.10.1@dynniq/stable",
                 ("OpenSSL/1.1.0h@dynniq/stable", "override"))
```

Despite the OpenSSL override, conan create results in a conflict error:

```
wdobbe@linux-wdobbe:~/crdata/git/webconf-common> conan create . dynniq/testing
WebConf-common/0.2.1@dynniq/testing: Exporting package recipe
WebConf-common/0.2.1@dynniq/testing export: Copied 1 file: .gitignore
WebConf-common/0.2.1@dynniq/testing export: Copied 1 '.cfg' file: uncrustify.cfg
WebConf-common/0.2.1@dynniq/testing export: Copied 3 '.txt' files: CMakeLists.txt, CMakeLists.txt, CMakeLists.txt
WebConf-common/0.2.1@dynniq/testing export: Copied 2 '.py' files: conanfile.py, conanfile.py
WebConf-common/0.2.1@dynniq/testing export: Copied 5 '.cpp' files: 
WebConf-common/0.2.1@dynniq/testing export: Copied 4 '.h' files: authtoken.h, tokencodec.h, uvalue.h, webconferror.h
WebConf-common/0.2.1@dynniq/testing: A new conanfile.py version was exported
WebConf-common/0.2.1@dynniq/testing: Folder: /home/wdobbe/.conan/data/WebConf-common/0.2.1/dynniq/testing/export
ERROR: Conflict in cpprestsdk/2.10.1@dynniq/stable
    Requirement OpenSSL/1.0.2o@dynniq/stable conflicts with already defined OpenSSL/1.1.0h@dynniq/stable
    Keeping OpenSSL/1.1.0h@dynniq/stable
    To change it, override it in your base requirements
```

**Comment by lasote** [comment]
Does the same message appears without the `("OpenSSL/1.1.0h@dynniq/stable", "override")` ?

**Comment by lasote** [comment]
I added some new tests and I cannot reproduce the issue. It's working. I would need a failing example to debug it.

**Comment by memsharded** [comment]
I have merged the test. I see that the conflict is in ``WebConf-common/0.2.1``, which is something that doesn't appear at all in your description. Please @wdobbe if you could provide something that we could reproduce, that would help.  Thanks!

**Comment by wdobbe** [comment]
Next weekend I will try to attach a scenario that reproduces this error.

**Comment by wdobbe** [comment]
I assembled some recipes to reproduce the issue, but then the OpenSSL requirement is overriden as expected. 
I am probably doing something wrong in my project. You can ignore this issue for the moment, will try to find the problem.

**Comment by wdobbe** [comment]
Can no longer reproduce this issue.
Closing.
