### ISSUE TITLE
[scm] deducing `url` with a windows path

### ISSUE THREAD

**Issue by orhun-sketchup** [conan-io/conan#3109]
It looks like when `auto` is deduced for `url`, it has to be properly escaped for '\\', just in case if it happens to be a local (windows) path instead of a proper git url.

I have scm section in my conanfile.py like the following
```
    scm = {
        'type': 'git',
        'url': 'auto',
        'revision': 'auto'
    }
```
I am getting the following error from our bamboo builds

```
[package]: Repo origin deduced by 'auto': file://C:\bamboo\xml-data\build-dir\_git-repositories-cache\3da5a99bbc924e3c4d1788734921ce3e6554ac8c
[snip]
[package]: A new conanfile.py version was exported
ERROR: Unable to load conanfile in [snip]\export\conanfile.py
File "<frozen importlib._bootstrap>", line 684, in _load
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 674, in exec_module
File "<frozen importlib._bootstrap_external>", line 781, in get_code
File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "[snip]\export\conanfile.py", line 16
scm = {"url": "file://C:\bamboo\xml-data\build-dir\_git-repositories-cache\3da5a99bbc924e3c4d1788734921ce3e6554ac8c",
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 16-17: truncated \xXX escape
```

As it turns out, due to local bamboo git repo caching,  I shouldn't use `auto` for `url` but conan should not fail due to windows paths in a deduced `url`.

Of course if it didn't fail, I wouldn't have noticed this *issue* this easily, perhaps conan should give a warning or fail with a more descriptive message if the deduced `url` ends up being a local path instead of a proper git url.

**Comment by memsharded** [comment]
Good point! Thanks for reporting it.

I have proposed a fix in https://github.com/conan-io/conan/pull/3110, in which a warning is done, but allowed, not an error (git repos in network drives possible)
