### ISSUE TITLE
Allow running commands that may fail

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3112]
Currently, `conans.ConanFile.run()` fails if the command returns an error code.
However, sometimes errors need to be ignored, even temporarily. This may happen for example when some unit tests fail and you have to ship anyway, and fix the tests later.

Therefore, adding a `fatal=True` argument would be nice to control wether run should stop on error or not.

Using Conan 1.4.4 on Windows Server 2016.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, this makes sense. I'd use the ``ignore_errors=True`` python arg, defaulted to ``False`` so things don't break.

**Comment by liberforce** [comment]
Thanks guys!
