### ISSUE TITLE
A form of conan remote list that can be used with conan config install

### ISSUE THREAD

**Issue by cstratopoulos** [conan-io/conan#3125]
See https://github.com/conan-io/docs/issues/697 for further discussion/motivation, but basically the idea is that the output of `conan remote list` is not compatible with the format of `remotes.txt` expected for use with `conan config install`.

It could be nice to have a modified version of `conan remote list` (@memsharded has suggested `conan remote list --raw`) so that 
```bash
    conan remote list --raw > remotes.txt
```
can conveniently format a user's remotes for use in a packaged Conan client config.

**Comment by memsharded** [comment]
Feature submitted in #3182 , it will be in conan 1.6
