### ISSUE TITLE
Settings aliases

### ISSUE THREAD

**Issue by astralien3000** [conan-io/conan#313]
Hello !

It may be interesting to be able to group settings into aliases, to let the user have his favorite settings set.

For example : 
```
mysettings1: { compiler: gcc, arch: x86_64, os: Windows, build_type: Debug }
mysettings1_32: { compiler: gcc, arch: x86, os: Windows, build_type: Debug }

mysettings2: { compiler: Visual Studio, arch: x86_64, os: Windows, build_type: Release }
```

What do you think ?

**Comment by memsharded** [comment]
Could be a good idea. I initially thought that it would be enough to define shell variables, but then I tried in Win, and, as usual, is more tricky than expected. And it wouldn't be portable. Should be easy to implement too.

I would include also options values. In fact, the simplest approach would be to store just the strings passed to the conan commands. A bit more verbose, but you write it just once, and it will manage to cover anything (as the Scopes we have recently merged in develop), without modifications.

Where would you store them? I initially thought in ``conan.conf```, but maybe it makes also sense to store in the project folder (and commit in repo, so every collaborator has the same configurations of settings and options. It shouldn't be in the conanfile, as it cannot be in the conanfile.py (as it sometimes gets uploaded and shared to conan servers and it doesn't make much sense)

**Comment by astralien3000** [comment]
Ah, I did not thought of using shell variable. It could be enough for my use case. But if it is a problem for windows as you said, it may be better to add it to conan.

I think `conan.conf` is fine, since it is more a user feature than a project feature. And if teams want to share the same aliases, they just need to share the command lines (in a README, a shell script or something...)

**Comment by memsharded** [comment]
Just Windows! tried to just set VAR="values", but it was omitting some chars, don't know why. Sure can be solved, I just didn't put the time. Please tell me if you make it work easily. In that case, maybe this wouldn't be necessary.

**Comment by astralien3000** [comment]
I have just quickly checked, if I do : 
```cmd
set TEST=-s compiler=gcc -s compiler.version=5.3
echo %TEST%
conan install %TEST% .
```
It seems to work (conaninfo.txt does set compiler as gcc v5.3).

**Comment by memsharded** [comment]
Ok, cool. I don't know what I was doing wrong then. Probably using quotes when I shouldn't

In this case, probably the feature of implementing it within conan is overkill; shell and env variables seem to be enough, aren't they?

**Comment by astralien3000** [comment]
I think so !
