### ISSUE TITLE
conan create not deleting cached sources with scm capture

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3131]
Repository with the `conanfile.py`, scm to auto:

In the local project:

`conan create . user/channel`
`>> Change CMakeLists.txt <<`
`conan create . user/channel`

**Result**: Conan create is keeping the local cache source folder, so the change in the CMakeLists.txt is not used.

**Comment by liberforce** [comment]
I was told in #3084 that `conan create` is not supposed to delete the sources unless the recipe changed, and that it's a feature. Now you seem to imply that it may have to delete the cached sources under other circumstances. So, may I please have your opinion on #3084? Thanks.

**Comment by lasote** [comment]
Nothing more to add in #3084. This is a different issue, with the `scm` feature pointing to a local directory (instead of checking out from the origin repo).

**Comment by liberforce** [comment]
Thanks for the clarification.
