### ISSUE TITLE
Create conan python class reference documentation

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#3134]
This might come from me not being a 'python' guy...but this is something i've run into often when I want the available methods from self and their args, descriptions, etc. Simple example...self.copy...I couldn't remember the name of the argument to keep symlinks (ok...it ended up being "symlinks"...but it's just an example :) ). It would be good to go to 'copy' and see all the options and descriptions.

**Comment by danimtb** [comment]
This is not so evident to reflect in the docs as `self.copy` objects are slightly different when using it in the `package()`, `imports()` or `deploy()` methods. This is the reason why those objects are explanied in the [methods section](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package).

There is an open issue in the docs suggesting the same in conan-io/docs#569, so please follow conversation there! Thanks 😄
