### ISSUE TITLE
Add additional default LLVM toolsets

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#3135]
Add to the default settings:
```
LLVM-vs2012, LLVM-vs2012_xp, LLVM-vs2013, LLVM-vs2013_xp, LLVM-vs2017, LLVM-vs2017_xp
```
Should it be possible to add wildcard settings? Like `LLVM-vs*`?

**Comment by lasote** [comment]
> Should it be possible to add wildcard settings? Like LLVM-vs*?

No, we require explicit settings, to not mess with casing and mistakes.

About the toolchains. 👍

**Comment by MarcelRaad** [comment]
There's no `vs2017` toolset yet, is there?

**Comment by Minimonium** [comment]
@MarcelRaad unofficial ones 
https://github.com/arves100/llvm-vs2017-integration
https://github.com/plasmacel/llvm-vs2017-integration

**Comment by SSE4** [comment]
yes, please add new toolsets, as official have installation troubles on machines with Visual Studio 2017 only installed.
