### ISSUE TITLE
[workspaces] generated files in source directories

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#3139]
I tried the example from https://docs.conan.io/en/latest/developing_packages/workspaces.html
but with `conan install ..` instead of `conan install . -if=build`
```
git clone https://github.com/memsharded/conan-workspace-example.git
cd conan-workspace-example
mkdir build
cd build
conan install ..
```

=> generated files are in `conan-workspace-example\A`
I would expect them to be in  `conan-workspace-example\build\A`

Windows, conan 1.5.0

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by wpalfi** [comment]
Btw. the root CMakeLists.txt is generated in `conan-workspace-example`. (No matter if I use `conan install ..` or `conan install . -if=build`). Why not in `conan-workspace-example\build`?

**Comment by petermbauer** [comment]
It is possible to add a `build` attribute for each package to the `conanws.yml` which is then used as build folder for it.

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
