### ISSUE TITLE
Add "keep_permissions" option to tools.get()

### ISSUE THREAD

**Issue by zlalanne** [conan-io/conan#3140]
A nice enhancement to the tools.get() high level wrapper function would be allowing the user to keep permissions when the unzip process happens. This is really useful when downloading compilers or other tools that need to be marked as executable.

**Comment by lasote** [comment]
Sure! we can just propagate the parameter `keep_permissions` to the unzip easily.
Also, we should propagate the `pattern`.

**Comment by zlalanne** [comment]
Sounds good, I'll make a PR later propagating both of those

**Comment by memsharded** [comment]
Hi @zlalanne 

We are doing some progress towards conan 1.6 and this feature is planned in it. Would you need some help to contribute this feature? Don't hesitate to ask. Please tell us if you could manage, so we plan accordingly. Thanks!
