### ISSUE TITLE
[workspaces] test targets are not generated

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#3141]
cc @memsharded, following the slack discussion from earlier.

Currently, it is not possible to run unit tests (e.g. via the `ninja test` command).
It's only possible to compile test targets.

Here is a minimal example:

[cmake_no_ninja_test.zip](https://github.com/conan-io/conan/files/2149985/cmake_no_ninja_test.zip)

Here are the steps to reproduce the issue:

* `mkdir build && cd build`
* `conan install .. -if=.`
* `cmake -G Ninja ..`
* `ninja`
* `ninja test` -> should fail

I'm using Conan 1.5.0

=====================

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by theodelrieu** [comment]
Hello, I did fiddle a bit with this one, and it seems the only thing missing is the `enable_testing` function, which should be in the top-level `CMakeLists.txt`.

Adding it by hand solved everything... except it gets overwritten every time I run `conan install` :D

**Comment by memsharded** [comment]
With the new proposal in #4481, a `conanworkspace.cmake` will be generated instead
