### ISSUE TITLE
System Package manager should not update package index if CONAN_SYSREQUIRES_MODE=verify

### ISSUE THREAD

**Issue by kutschkem** [conan-io/conan#3142]
Currently the SystemPackageManager.update() performs an update (which needs sudo rights!) if CONAN_SYSREQUIRES_MODE is anything else than "disabled". "verify" should also not update, I think.

**Comment by memsharded** [comment]
This might be a duplicate, and fixed in conan 1.5. Have you already updated? Thanks!

**Comment by memsharded** [comment]
Duplicate of https://github.com/conan-io/conan/issues/3047, fixed in conan 1.5

**Comment by kutschkem** [comment]
I am literally looking at the code in develop branch. The [last commit](https://github.com/conan-io/conan/commit/41331c7dae6b2b34b8f0edf98b4507c1b24e930a) which changed the file disabled update() for CONAN_SYSREQUIRES_MODE="disabled", but not for "verify". Please reopen.

**Comment by memsharded** [comment]
But for verification the update is implicit, isn't it? Users using the "verify" mode need to update first in order to correctly run such verification.

**Comment by kutschkem** [comment]
Hmm the verification checks that packages are locally installed. I think update updates the indexes of remote package sources. If that is correct they are unrelated.

**Comment by memsharded** [comment]
Yes, you are right, sorry I misunderstood. This should be fixed, thanks for reporting!
