### ISSUE TITLE
[workspaces] Surprising behavior of "--install-folder"

### ISSUE THREAD

**Issue by jokoala** [conan-io/conan#3145]
First of all thank you for developing conan. I had the possibility to enjoy using it in some small toy products and it's a lot of fun!

At the moment I'm investigating how to use the "workspaces" feature in a productive way and the following behavior seems very odd to me. I'm using version 1.5.0 of conan and the example repository (https://github.com/memsharded/conan-workspace-example).

Without a "conanws.yml" file, the following commands both perform the same step -- preparing a build directory to use for building component "A":
1. `cd A && conan install . --install-folder build`
2. `cd A/build && conan install ..`

This seems logical, the optional argument `--install-folder` has "." as default.

Once a "conanws.yml" file is there, the behavior changes completely:
- Only command 1 creates the files in the expected folder (A/build).
- However, also command 1 changes behavior. It now prepares a build directory for the "super-project"
- Moreover the following commands now behave exactly the same
   - `conan install . -if build`
   - `conan install ./A -if build`
   - `conan install ./B -if build`

I feel that this behavior is very unnatural and would suggest the following instead:

- Create the super-project only if the "root folder" (the folder containing the "conanws.yml" file) is given as parameter to "conan install".
- Have the switch between "super-project install" and "in-source-build" not based on the "-if" parameter, but based on an option in the "conanws.yml".
- Change the behavior of the command `conan install ./A -if build`, so that it prepares a "build" folder for component "A". This means, I would expect the following commands to succeed:
`conan install ./A -if build && cd build && cmake ../A/src && make`

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by niosHD** [comment]
I can confirm that the current behavior regarding install-folder is very surprising. Trying the CMake generator, I absolutely did not expect that any file is written outside of my current folder and was very surprised that the CMakeLists.txt is written directly next to the conanws.yml file.

Also, #3139 already discusses the same issue.

**Comment by memsharded** [comment]
This behavior will be removed in conan 1.13, in favor of a new ``conan workspace install <wsfile>`` that will be explicit. Ongoing work: https://github.com/conan-io/conan/pull/4481
