### ISSUE TITLE
[workspaces] Explain the "in-source-build" use case better

### ISSUE THREAD

**Issue by jokoala** [conan-io/conan#3146]
I was trying to follow the section about workspace "in-source-builds" (https://docs.conan.io/en/latest/developing_packages/workspaces.html#in-source-builds) with conan 1.5.0 and the example repository (https://github.com/memsharded/conan-workspace-example) on Linux.

Unfortunately it did not work as expected. I tried the following commands:
```bash
conan install .
(cd C && cmake src && make)
(cd B && cmake src && make)
(cd A && cmake src && make)
```
the last command fails with the error:
```
Scanning dependencies of target app
[ 75%] Building CXX object CMakeFiles/app.dir/main.cpp.o
[100%] Linking CXX executable app
/usr/bin/ld: cannot find -lhelloB
/usr/bin/ld: cannot find -lhelloC
```

The problem can be fixed by adding the following lines to the conanws.yml:
```yaml
HelloB:
     [...]
     libdirs: .
HelloC:
    [...]
    libdirs: .
```
Is that the intended behavior? Then I would suggest to use that in the example as well.

Also the following sentence is not true with the current example:

> Each local package will have their own build folder, and the generated conanbuildinfo.cmake will be located in it.

For that, conanws.yml would need these additional lines:

```yaml
HelloB:
     [...]
     build: build
HelloC:
    [...]
    build: build
```
However, this seems to change the behavior for the out-of-build use case. 

-- 
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

Workspaces were removed in Conan 2 years ago. There are plans to bring it back to Conan 2.X, please track https://github.com/conan-io/conan/issues/15992 to follow progress on it.

Closing this ticket as outdated, thanks!
