### ISSUE TITLE
Add ability to generate and manage source packages

### ISSUE THREAD

**Issue by drussel** [conan-io/conan#3147]
It would be nice to have the ability to automatically generate and upload source packages for a given Conan package.

Having this would bring several benefits
- builds then have a more consistent set of services they depend on (at the moment, sometimes when you want to use a package you just depend on your Conan server, other times, when there is no pre-built package you depend on other source hosting services and you may not notice problems with these until later)
- old packages are more likely to work (changes in the upstream repos such as moving can't break building)
- it solves the left-pad problem (otherwise we have to create local clones of all dependencies which is extra work, doesn't get done consistently etc)

**Comment by memsharded** [comment]
Hi @drussel 

I am not sure if I understood completely. The recommended flow for production usage is to cache your third parties also in your own conan server (Artifactory), so you are not affected by any possible change that happens upstream. This is know easily doable with `conan download` + `conan upload` and you might also change their user/channel with the `conan copy` command. Also, this might be further automated in the server in the future, but still the recommended approach is to cache the third party dependencies in your own server.

**Comment by drussel** [comment]
We cache what we can of the third party dependencies on Artifactory (namely conanfiles and the binary packages). But when compilers versions, flags, os, etc change, new versions of the package need to be built. And this requires reaching outside of Artifactory and hitting wherever the sources are stored and to build a new binary package (unless I'm missing something). And this ability to easily build new configurations on demand is one of the really cool bits of Conan for us.

Overall, the fewer things we can depend on for each stage of building and deploying, the more reliable and more consistent it gets.

**Comment by memsharded** [comment]
So the idea would be to have the ``exports_source`` functionality over the sources retrieved with the ``source()`` method. Not sure if it is possible, but an idea to investigate.

**Comment by AbrilRBS** [comment]
Closing as solved with the [backup sources feature](https://docs.conan.io/2/devops/backup_sources/sources_backup.html) introduced in Conan 2 - this allows for separate management of associated sources
