### ISSUE TITLE
Improve source code traceability and package creation reproducibility for out-of-source builds

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3150]
Currently, using `revision: "my/branch"` of the "scm" feature will result in the exported recipe still having `revision: "my/branch"`, giving no indication on what was really built. I would have thought this feature was to address the reproductibility of the other methods (self.run of clone and checkout of a branch). 

In other words: how do I know from a package or recipe which source code commit was used to build it? How can I produce a recipe that I'll be able to use on different platforms to generate a package based on the same source code commit, without hardcoding that commit in the recipe?

Using Conan 1.5.1 on Windows Server 2016.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by liberforce** [comment]
@niosHD : I see several problems here.
1. The official documentation of the [ConanFile.scm](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#scm-attribute) says the auto value is allowed for the `"url"` key, not the `"revision"` one. Are you sure this is supported?
2. Even if "revision": "auto" is allowed, I cant' see how this would work as it can't guess out of the blue the branch I want to checkout.
3. The documentation of scm says: « url (Required): URL of the remote or auto to capture the remote from the local directory. ». The use of "local directory" seems to imply that this is useful if you have an in-source recipe, so the exact commit can be determined, but this is not possible if the recipe is out-of-source.

**Comment by niosHD** [comment]
True, the documentation needs to be improved to mention that `auto` is an allowed value for `revision`.

I was not aware that you are in an out-of-source scenario. In this use case, I do not think that the scm module provides any notable benefit over manually cloning the repo in the source method. Providing the same behaviour as in the in-source scenario would certainly be nice. However, implementing this feature is probably not as trivial as it seems. I expect that, even when the recipe is only exported, some kind of clone/checkout of the repository would be needed for determining the current revision.

Anyway, let's see what the conan team thinks about this issue.

**Comment by lasote** [comment]
> Currently, using revision: "my/branch" of the "scm" feature will result in the exported recipe still having revision: "my/branch"

You are responsible to choose a revision that guarantees reproducibility, use a commit. You don't need to branch to check out a commit in git.

>the documentation needs to be improved to mention that auto is an allowed value for revision.

Thanks for reporting it. I'm opening an issue in the docs repository.

**Comment by liberforce** [comment]
Reproducibility is just a consequence of traceability. Currently, I see no way of knowing on which source code commit a conan package is based on, unless the SHA-1 is hardcoded in the recipe. 

But I'm doing CI and I want to track a branch, not a commit, because it's so much easier. I don't want to have, everytime a change is commited in the sources, to change each recipe to hardcode a commit. 

Wouldn't it be possible instead to figure out the exact commit the branch points to at export time? This could be done by parsing the output of `git ls-remote https://github.com/foo/bar.git`.

**Comment by liberforce** [comment]
> If I understand correctly you are using out-of-source but you want to capture the commit and branch of the sources repository automatically, right?

Exactly.

> No, it is not possible

I would have thought this would be easy to do at export time by parsing `git ls-remote` output. It the commit didn't change, the exported recipe is the same. If the commit changed, the exported recipe changes, triggering removal of the source code and a new clone.

Is that a technical problem or an implementation choice? Is there a difficulty I'm overlooking?

**Comment by lasote** [comment]
> Is that a technical problem or an implementation choice? Is there a difficulty I'm overlooking?

I still don't know, we would need to investigate it. As any other feature it will have hidden corner cases and so on.

**Comment by memsharded** [comment]
The ``scm`` auto approach was deprecated long time ago, and explicit ``export()`` + ``conandata.yml`` + ``source()`` is recommended. 

For related source code reproducibility of third parties, this is related: https://blog.conan.io/2023/10/03/backup-sources-feature.html

I think we can close this ticket now, please open new tickets for any further question or issue, thanks!
