### ISSUE TITLE
[workspaces] Add support for conanfile.txt

### ISSUE THREAD

**Issue by jokoala** [conan-io/conan#3151]
Conan: 1.5.0
OS: Windows (Python 3.6)

I would like to use the "workspaces" feature also for a consumer project. Do you see possibilites to support them as well?

If I try on the demo project (https://github.com/memsharded/conan-workspace-example) to replace the file "a/conanfile.py" with a file "a/conanfile.txt" having equivalent content, the following error is shown:
```
Using conanws.yml file from [...]\conan-workspace-example\A
ERROR: [...]\conan-workspace-example\A\conanfile.py not found!
```

I'm planning to use the feature in an environment which consists of "integration projects" built out of several "components". The updates on the components are usually done with one of the integration project as reference. Therefore it would be great if both the component and the integration project could be put into a common workspace.

**Comment by memsharded** [comment]
Ok, I think this is possible, but need to check. Thanks for the feedback, I will take it into account for next iteration of workspaces.

**Comment by memsharded** [comment]
Closing as inactive:

- workspaces removed in 2.0, will probably be resumed later in 2.X roadmap
