### ISSUE TITLE
https://conan.io/ links to http

### ISSUE THREAD

**Issue by bluecatchbird** [conan-io/conan#3152]
On https://conan.io/ the buttons at the top for the blog/docs links to http.
Here are the links at the moment:
http://docs.conan.io/
http://blog.conan.io/

Should link to https, if it is used for the conan.io site:
https://docs.conan.io/
https://blog.conan.io/

**Comment by lasote** [comment]
Thanks! We have a repository with the website here: https://github.com/conan-io/website
I'll fix it asap. I will close this issue and open a new one in the website repo.

**Comment by lasote** [comment]
Fixed!

**Comment by bluecatchbird** [comment]
Confirmed :)
