### ISSUE TITLE
Package ID unique for building same package GCC4 and GCC5 Compilers

### ISSUE THREAD

**Issue by bugcy013** [conan-io/conan#3155]
Hi Guys,

Currently we have some issue with exporting package via conan. when we build the same package GCC4 and GCC5 compiler it's exporting same package id. 

for example:

My package name :: **yyy/master@xxx/incubator**
for exporting package have used this command.
**conan export-pkg . -f  yyy/master@xxx/incubator**

it's produce the **Package_ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9**

When we upload package to conan remote server it's overwrite the files.
 
OS / Conan Version
---------------------------
Conan version: 1.5.1
OS : Ubuntu 16.04.4 LTS

Please guide me. How to debug this.

-Dhanasekaran.

**Comment by memsharded** [comment]
Hi @bugcy013 

I'd need to have details about the recipe. Are you sure you declare the correct settings? Most likely your recipe should contain:

```python
class Pkg(ConanFile):
     settings = "os", "compiler", "arch", "build_type"
```

**Comment by bugcy013** [comment]
Hi @memsharded 

currently my recipe contain this settings.
```
class xxxConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
```
please find console log references for conaninfo.txt

```
dvjenkins@dvwhk-jenkins:~/.jenkins/workspace/xxx-dhana/build_conangcc48$ head -n 18 conaninfo.txt 
[settings]


[requires]


[options]


[full_settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++
    compiler.version=4.8
    os=Linux

[full_requires]
dvjenkins@dvwhk-jenkins:~/.jenkins/workspace/xxx-dhana/build_conangcc48$ cd ../build_conangcc54/
dvjenkins@dvwhk-jenkins:~/.jenkins/workspace/xxx-dhana/build_conangcc54$ head -n 18 conaninfo.txt 
[settings]


[requires]


[options]


[full_settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++
    compiler.version=5
    os=Linux

[full_requires]
dvjenkins@dvwhk-jenkins:~/.jenkins/workspace/xxx-dhana/build_conangcc54$ 
```

**Comment by lasote** [comment]
Are you running the `conan export-pkg . -f yyy/master@xxx/incubator` command in the `~/.jenkins/workspace/xxx-dhana/build_conangcc54` folder and then changing to `~/.jenkins/workspace/xxx-dhana/build_conangcc48`, right?

**Comment by bugcy013** [comment]
Hi @lasote 

In My case I am using jenkins job for building the conan packages.

```
cd ${HOME}/.jenkins/workspace/xxx-dhana
conan export-pkg . -f  yyy/master@xxx/incubator --build-folder ${HOME}/.jenkins/workspace/xxx-dhana/build_conangcc54 --source-folder ${HOME}/.jenkins/workspace/xxx-dhana
conan export-pkg . -f  yyy/master@xxx/incubator --build-folder ${HOME}/.jenkins/workspace/xxx-dhana/build_conangcc48 --source-folder ${HOME}/.jenkins/workspace/xxx-dhana
```

**Comment by lasote** [comment]
Have you declared a `package_id()` method in your recipe?

**Comment by memsharded** [comment]
Excellent news!

Yes, exactly, that call in ``package_id()`` is effectively removing the settings, so there is always exactly one package, because if it was a header only you only want to have one package for all possible configurations.

Very glad this is solved. Don't hesitate to ask again for further questions. Cheers.
