### ISSUE TITLE
Split recipe into two: for producer and for consumer

### ISSUE THREAD

**Issue by mmatrosov** [conan-io/conan#3158]
I would like to start a discussion about the meaning of the recipe for the conan framework. 

Recently we have a problem. We had a recipe for boost, which worked fine. Then we discovered it does not properly define `BOOST_BZIP2_BINARY` for consumers. So we updated function `package_info` to set proper `self.cpp_info.defines`. 

The recipe changed. Now the question is: do we need to build new binaries for boost with this new recipe? The apparent answer is no: we did not change any logic related to package build. However, we had forbidden overriding artifacts on our remote. So we cannot rewrite the recipe for existing packages. And we actually need to change recipe version, generate all new binaries, and update version for consumers to fix the recipe.

It seems like the problem arise from the fact that conan recipe actually mixes two entities in one place: rules how to _produce_ packages, and rules how to _consume_ packages. And the described problem is about how to preserve existing _produced_ packages when the _consumer_ rules change. If we had two different recipes, then we would be able to update only version for consumer recipe, leaving producer recipe with all the generate packages as they are.

What do you think about it? Maybe you have a better solution for the problem?

**Comment by lasote** [comment]
About splitting the recipes, at first sight, it could make sense, but it would change the entire Conan model, we know it is not perfect but what is perfect? ;) It doesn't sound like something we would consider in the short-middle term. But thanks for raising up the question, if we receive more feedback maybe we find a good way to solve the issue.

About the overwriting issue, In our roadmap is to introduce "revisions" to the remotes, so you can upload a new revision for the same reference (no need to bump anything) and you won't be overwriting anything.  The idea is to get always by default the latest revision unless it is specified somehow. The revisions mechanism is it still under investigation.

About generating again the binary packages for the recipe, we don't have a fix for that, you would need to do it even with the revisions mechanism.

**Comment by mmatrosov** [comment]
> About the overwriting issue, In our roadmap is to introduce "revisions" to the remotes

We currently manually support the very similar approach. Instead of versions X.Y.Z for our recipes we use X.Y.Z-R, where "R" is the number for revision. We don't have ability to use "latest" revision, but we don't actually want it, because of build reproducibility. We always specify concrete full version with revision. Seems like making revisions a built-in feature won't affect us at all.

> About generating again the binary packages for the recipe, we don't have a fix for that, you would need to do it even with the revisions mechanism.

That's sad :( Maybe this problem might be solved on Artifactory level? E.g. if Artifactory sees two identical artifacts, it doesn't duplicate them, but share them? The binaries might be still different because of build time stamp though.

**Comment by lasote** [comment]
> That's sad :( Maybe this problem might be solved on Artifactory level? E.g. if Artifactory sees two identical artifacts, it doesn't duplicate them, but share them? The binaries might be still different because of build time stamp though.

Exactly, Artifactory won't store them duplicated if the checksum is the same, but you are right, timestamp and file masks in the libraries (in nix systems), plus some other reasons,  the library hash will change.

**Comment by memsharded** [comment]
Conan usage using same recipe for consumption and production has proved to be reliable and convenient, so settling on this. Closing this ticket as inactive.
