### ISSUE TITLE
Enhanced tools.vcvars_dict(...,only_diff=True) handling of lists

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#3159]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.5.1, Windows 7, Visual Studio 2017

tools.vcvars_dict seems to mostly exist to support `with tools.vcvars():`. However, this doesn't play nicely with any other packages offering additions to the the same environment variables (filter_known_paths offers a partial workaround for PATH),

environment_append and env_info handle this use case nicely by supporting the idea that the dict value an be a list, and that this will be combined with the existing values using os.pathsep. So it would be nice if tools.vcvars_dict would, in only_diff=True, make use of this and split lists that vcvars modified by inserting additional entries at the front, rather than providing a blanket "overwrite with this complete string".

e.g. 

https://github.com/conan-io/conan/blob/a8649076fa6bfeb6c0b7438832fd996e56d72ecf/conans/client/tools/win.py#L322-L323

could instead do something like (not tested)

```python
    oldvalue = os.environ.get(name_var) if only_diff else None 

    if oldvalue and value.endswith(os.pathsep + oldvalue):
        new_env[name_var] = value[:-(len(oldvalue)+1)].split(os.pathsep)
    elif oldvalue != value:
        new_env[name_var] = value
```

**Comment by lasote** [comment]
Interesting. We will have a look.
