### ISSUE TITLE
[Macos] Problem when linking with self-made frameworks

### ISSUE THREAD

**Issue by BillHoo** [conan-io/conan#3161]
To help us debug your issue please explain:

- [ ✔ ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ✔ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ✔ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

[Conan version] 1.5.1
[System] Mac OSX 10.13.5
[Problem] 
We have a self-made framework named Demo.framework, and wanna integrate it with Conan.
I'm following the official doc [How to link with Apple Frameworks](https://docs.conan.io/en/latest/howtos/link_apple_framework.html) to write my conan_file.py as shown below.
But when I install the uploaded pkg by follwing [With the xcode generator](https://docs.conan.io/en/latest/integrations/xcode.html), I ended up get a build error said: framework Demo not found.

And I finally find out that the generated conanbuildinfo.xcconfig has no "FRAMEWORK_SEARCH_PATHS" in it, when I manually add the FRAMEWORK_SEARCH_PATHS into the config file, XCode can find the framework now.

My question is why the "FRAMEWORK_SEARCH_PATHS" is not generated by Conan? Or what's the right way to use our own framework with Conan ?

Thanks a lot.

[Other info]

```python
from conans import ConanFile, tools

class DemoConan(ConanFile):
    name = "Demo"
    version = "snapshot"
    settings = "os", "compiler", "build_type", "arch"
    description = "Demo to demonstrate the issue"
    url = "None"

    def package(self):
        if self.settings.os == "Macos":
            self.copy("Demo.framework/**", symlinks=True)

    def package_info(self):
        if self.settings.os == "Macos":
            self.cpp_info.includedirs = ['Demo.framework/Headers']
            self.cpp_info.bindirs = ['Demo.framework']
            self.cpp_info.exelinkflags.append("-framework Demo")
            self.cpp_info.sharedlinkflags = self.cpp_info.exelinkflags

```

**Comment by lasote** [comment]
Hi! Until now we didn't try to package a framework, we are definitely not heavy OSx coders. So we need to look at `FRAMEWORK_SEARCH_PATHS`, absolutely makes sense to set it.

**Comment by lasote** [comment]
I'm trying to push it to 1.6 but it is very packed already, probably it has to wait for 1.7.

**Comment by BillHoo** [comment]
Thanks to let me know. FIY, I'm using imports() feature to do the trick right now i.e. import the framework into my project and directly rely on it. It worked well but still expect the official support for FRAMEWORK_SEARCH_PATHS, thank you.
