### ISSUE TITLE
conan search result not showing the options and settings sections

### ISSUE THREAD

**Issue by bugcy013** [conan-io/conan#3164]
Hi Guys,

When I search packages from the remote repo, it's not showing the options and settings section.  like arch and build_type, compiler, compiler.version filelds not showing.

for example in my case.

```
~]$ conan search YYYY/master@XXXX/incubator -r=conan_server
Existing packages for recipe YYYY/master@XXXX/incubator:

    Package_ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
        [requires]
            ACE/3.12@XXXX/incubator:de9c231f84c85def9df09875e1785a1319fa8cb6
            OpenDDS/3.12@XXXX/incubator:de9c231f84c85def9df09875e1785a1319fa8cb6
            OpenSSL/1.0.2n@XXXX/incubator:b4a53e1a9dd2de8a832beed316bba53600bc01b9
            Poco/1.9.0@XXXX/incubator:24a7380840586332966890886948deb3b04ba334
            TAO/3.12@XXXX/incubator:de9c231f84c85def9df09875e1785a1319fa8cb6
            boost/1.66.0@XXXX/incubator:2d03252301f0f87015265771f29a98117806276a
            bzip2/1.0.6@XXXX/incubator:3a5f72c8cd50641b8efa6ed13e6914c6ced2747c
            catch2/2.2.2@XXXX/incubator:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
            kdb-c/0.0.1@XXXX/incubator:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9            
            rpclib/2.2.1@XXXX/incubator:de9c231f84c85def9df09875e1785a1319fa8cb6
            zlib/1.2.11@XXXX/incubator:755fc07adbed235a7d3eadec4b6882d4912f09bc
        Outdated from recipe: False

```
can you please guide. How to debug this. 

-Dhanasekaran.

**Comment by lasote** [comment]
I think this could be related to #3155
The conan info should have something at the `[settings]` section I think. Maybe something wrong with a package_id method? I don't know...it should work

**Comment by memsharded** [comment]
Hi @bugcy013 

Can't reproduce the issue. Could you please try to provide a recipe that produces this behavior? Are you sure you didn't leave the ``self.info.header_only()`` in that package (that will remove the settings)? Please check and tell me. Thanks!

**Comment by memsharded** [comment]
Closing as inactive, not getting response
