### ISSUE TITLE
Link versioned .so with CMake generator

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3168]
I have a package that provides a versioned .so library (say, `libtest.so.1.0.0`). How to set `cpp_info.libs` so that CMake generator would be able to link it? Direct
```python
    self.cpp_info.libs = ['libtest.so.1.0.0']
```
doesn't work; if one passes`libtest.so.1.0.0` as a link library to cmake it strips `lib`, adds `-l` and then `ld` linker will fail:
```
/usr/bin/ld: cannot find -ltest.so.1.0.0
```
The only workaround I have found so far is to prepend a colon to a library file:
```python
    self.cpp_info.libs = [':libtest.so.1.0.0']
```
But is it OK for other generators? Maybe it should be done by a generator itself?

**Comment by memsharded** [comment]
This is interesting. The typical approach when libraries generate such ``libtest.so.1.0.0`` version is that they also provide a ``libtest.so`` file which is a symlink to the 1.0.0 version. Doesn't such package have this symlink? You could try to pass the ``symlinks=True`` to ``self.copy()``?

For sure it won't work for other OS, so at least it needs to be conditioned to some ``if self.settings.os == "Linux"``, and I have no idea if the ``:libtest`` notation would affect other generators (they usually just pass that name as the ``-lxxxx`` flag in unix like systems. 

If I had to do it, I think I will aim to have a ``libtest`` file (either symlinking or renaming the final file), it looks to me a bit incorrect having to use the full version there. But please tell me about your use case. Thanks!

**Comment by db4** [comment]
OK, I'm trying to fetch `cpp_info` from existing CMake project (I still hope to package OpenCV this way if you are interested). My previous approach with printing CMake values and parsing the output was too complex and did not work correctly under Unix-like OSes (library order was not preserved that is critical for `ld`, there were some problems with generator expressions etc.), so I implemented cmake server-based approach: https://github.com/db4/conan-cmake-config-tools/tree/cmake-server. It works and I almost happy with the results, but OpenCVConfig.cmake directly links versioned .so files. I could rewrite .so names by some heuristic rules, use symlinks etc but why? Looks like prepending `:` to a library file is enough for `ld` linker.

**Comment by memsharded** [comment]
This ticket is about legacy and removed ``cmake`` generator, closing it as outdated.
