### ISSUE TITLE
`conan user` doesn't take CONAN_LOGIN_USERNAME_{REMOTE_NAME} nor CONAN_PASSWORD_{REMOTE_NAME} into account

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3172]
I own a repository named `sbre-public`, where I want to upload packages generated through CI. To authenticate non-interactively on this repo, I defined in my gitlab-ci job the following environment variables:

- CONAN_LOGIN_USERNAME_SBRE_PUBLIC
- CONAN_PASSWORD_SBRE_PUBLIC

I checked they are defined and have the correct value.

Then I tried to authenticate. To be sure to not rely on an older state, I issue each time a `conan user --clean` first.
The problem I have is that  running the command below  won't authenticate me:
`conan user --remote sbre-public`
> Current user of remote 'sbre-public' set to: 'None' (anonymous)

Explicitely specifying the user seems to work:
`conan user --remote sbre-public sbre-gitlab-runner`
> Changed user of remote 'sbre-public' from 'None' (anonymous) to 'sbre-gitlab-runner'

... but that kind of defeats the purpose of having dedicated environment variables.

Then, at the time I try to `conan upload` something, I get this error (on Windows 2016 server):
> Requesting upload permissions...                                      Please log in to "sbre-public" to perform this action. Execute "conan user" command.
> If you don't have an account sign up here: https://bintray.com/signup/oss
> Please enter a password for "sbre-gitlab-runner" account: 

and this (on Ubuntu 16.04):

> Please log in to "sbre-public" to perform this action. Execute "conan user" command.
> If you don't have an account sign up here: https://bintray.com/signup/oss
> Please enter a password for "sbre-gitlab-runner" account: /usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
>   passwd = fallback_getpass(prompt, stream)
> Warning: Password input may be echoed.
> ERROR: Cancelled pass . [Remote: sbre-public]

So both environment variables seem to be ignored.

Using conan 1.5.2 on Windows Server 2016 and Ubuntu 16.04.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by liberforce** [comment]
After launching a debugger, it looks like the correct syntax to get to read the username and the password is to run `conan user --remote sbre-public --password`.
The documentation says has an example with this syntax, but it says:

> Change *bar* remote user to *foo*, *asking user password* to authenticate against the remote and storing the user and authentication token locally, so a later upload won’t require entering credentials

(original emphasis )

But "asking user password" is really misleading as it makes think of "interactive mode".

**Comment by danimtb** [comment]
Hi @liberforce 

I think you are totally right and conan user commands will benefit from a total redesign. Most of its usage for listing the users or the current user per remote and only forcing user and password will actually authenticate the user and finally use both `CONAN_LOGIN_USERNAME_{REMOTE_NAME}`, `CONAN_PASSWORD_{REMOTE_NAME}`

I will open a new issue to have this tracked. Thanks for reporting
