### ISSUE TITLE
[question] Multiple libraries in one package

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3173]
Is there a way to generate different cmake library variables for a package that contains multiple libs?

For example, package foo contains libfoo1 and libfoo2. If I do:

`self.cpp_info.libs = ["libfoo1", "libfoo2"]`

I get a CONAN_LIBS_FOO set to "foo1 foo2" and I am forced to link against both in consumers.

What I want is something like:
CONAN_LIBS_FOO1 foo1
CONAN_LIBS_FOO2 foo2

so that I can use one or the other but not necessarily both in a consumer.

Looking at the documentation, it looks like I probably have to create a custom FindXXX.cmake (FindFOO.cmake in this example) that creates the variables and in the consumer use a find_package("FOO") to access those variables.

Is my understanding correct?

**Comment by SSE4** [comment]
I subscribe to this, as this is feature I potentially would like to have
e.g. we have ffmpeg package, which has actually multiple libraries (libavcodec, libavformat and so on), that potentially might be used in an independent manner. so it would be nice if single conan package (or conanfile.py) might define multiple targets, so consumer may easily select that to use.

**Comment by memsharded** [comment]
Hi @keithrob91 @SSE4 

If I understood correctly, then it seems that this could be a duplicate of: https://github.com/conan-io/conan/issues/2387.

Please check, and if true, close this issue and follow conversation there. Thanks!

**Comment by SSE4** [comment]
yes, that seems to be about the same

**Comment by keithrob91** [comment]
Hi @memsharded, #2387 talks about intra-package dependencies and system libraries, and what I was talking about is neither of these 2 things. My situation is more like what @SSE4 describes i.e. a package with multiple libraries and neither depend on the other (they just happen to be built within the same package) and I have consumers that depend on some (or all) of those libraries. I just want to be able to pick and choose the libraries in the consumers and not be forced to depend on them all.

So apologies if I have not fully understood #2387 but it seemed a little different to me. Are you saying the solution to #2387 would also be my solution? If so, I'll close as a duplicate.

**Comment by memsharded** [comment]
Hi @keithrob91 

No problem, let me briefly explain the goal of #2387. The idea is that inside a package that contains, lets say, 2 libraries lib1 and lib2, you could do something like:

```python
def package_info(self):
     self.deps = {"lib1": [], "lib2": []}
```

That would be a way to say that lib1 and lib2 are independent of each other. If there were relationships among them, then something like: ``self.deps = {"lib1": ["lib2", "lib3"], "lib2": [], ....}`` would model that.

With that information, the generated files would contain information how to link with specific targets only. I am not saying that we already know how to model this, there are many details to figure out, but at least that would be the idea. Is this what you have in mind?

**Comment by keithrob91** [comment]
Yes, that sounds like it. Great!
