### ISSUE TITLE
[commands] conan user is confusing

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#3175]
`conan user` command has 4 use cases:
- Clean current users of all remotes
- Show the user set for each remote
- Authenticate a new user to a remote
- Change the user of a remote (without authentication)

Currently this is done combining different options and lead to bad user experience as reported in #3172 

I think this command will benefit from a new redesign, probably using sub-commands like this:

- `conan user clean` -> clean users
- `conan user list ['remote']` -> list users [of a remote]
- `conan user auth 'remote' ['user'] ['password']` -> login a remote [w/o user or pass] (also use `CONAN_PASSWORD{_REMOTE_NAME}`, `CONAN_LOGIN_USERNAME{_REMOTE_NAME}`)
- `conan user set 'user' 'remote'` -> set user for a remote (not login) necessary??

**Comment by lasote** [comment]
Read https://github.com/conan-io/conan/issues/5443#issuecomment-514965707
For 2.0:
Remove the `skip_auth` argument, that behavior (do not auth if we have local credentials) will be done by changing the behavior of the "conan user USERNAME -r remote" that will use the local credentials (and verify that are valid) against the server. Currently it only "associate" the USERNAME with the remote without checking anything else. That behavior should be changed no matter the final parameters of the `conan user` command have.

**Comment by memsharded** [comment]
``conan user`` has been removed in develop2, ``conan 2.0-alpha2`` will contain only the ``conan remote`` command that manage now that functionality.
