### ISSUE TITLE
[question] tools.cross_building and warning "This package defines both 'os' and 'os_build'"

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#3179]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.5.1, Ubuntu 16.04

In a test_package, I want to use tools.cross_building(self.settings) to determine whether some unit tests can be run or not. Since cross_building compares os_build to os, and arch_build to arch, this seemingly requires that all four be provided in the package's settings, else it will have to take fallbacks to guess them that are based on python's platform module and not on the selected conan profile (which might be setting up a sysroot where the correct answer is not the same as it is for the python in which conan is running, particularly with a multiarch 'cross' gcc and /usr/lib/<arch> setup as is common on linux distros. However, doing so provokes a warning:

```
xxx/#.#@xxx/xxx (test package): ************************************************************
xxx/#.#@xxx/xxx (test package):   This package defines both 'os' and 'os_build' 
xxx/#.#@xxx/xxx (test package):   Please use 'os' for libraries and 'os_build'
xxx/#.#@xxx/xxx (test package):   only for build-requires used for cross-building
xxx/#.#@xxx/xxx (test package): ************************************************************
```

This warning remains even if (even if `*_build` are being discarded in package_id using self.info.discard_build_settings(), or in a test_package where there never is a package_id, so there doesn't appear to be any way to fix it. Looking a little deeper, this warning seems to be issued regardless of anything you can do in the conanfile methods, since it's issued from ConanFile.__init__ before they run.

Am I missing something about how tools.cross_building is meant to be used?

**Comment by memsharded** [comment]
Hi @puetzk 

Please take into account that the warning was mainly put in place to account for some unclear things in the early releases of conan 1.0. ``os_build`` and ``arch_build`` should be only used in some particular cases, mainly for build tools that are to be used as ``build_requires``. 

In other cases, which is most of the packages, you don't need to use them, even if you want to use ``tools.cross_building()``. They will internally use ``platform.system()`` which the recipes can also check to know in which system they are being built if strictly necessary (in most cases, this might be managed by the toolchain, and shouldn't be customized in the recipes).

Please tell me if this helps, or if you have further questions. Thanks!

**Comment by puetzk** [comment]
Yes, I know that it will fall back on `platform.*`. But I don't think that's always a good substitute, since it's not necessarily connected to the compiler/linker architecture. This is somewhat related to #3157 that I also opened recently (sorry I failed to link that). I filed it separately since it was in an unrelated part of the code, but if you'd rather consolidate the discussion in one place that's fine too.

E.g. On windows I think it's very plausible to choose the HostX86 versions of cl.exe (in fact that's what conan always does today with arch=x86, which is why I filed #3157), and yet be using an x64 python to run conan (or vice-versa). The same would be generally true on linux as well, with the [possibility of even more exotic setups with qemu-user](https://wiki.gentoo.org/wiki/Embedded_Handbook/General/Compiling_with_qemu_user_chroot). I could be using the 'system' x64 python, and yet by picking a toolchain chroot where arch_build is arm (and the executables really do work transparently via exec(), so it's not cross_building).

And even when host kernel can run these various architectures transparently, there are some differences that can make it matter for tool packages to match up arch_build with each other, even if they don't match python. E.g. on windows we have projects that have COM components and typelibs in them, which means the fact that x86 and x84 windows binaries [see different registry views](https://docs.microsoft.com/en-us/windows/desktop/WinProg64/shared-registry-keys), and needs to be matched up; if you register an x64 component and then use [`#import "progid:..."`](https://msdn.microsoft.com/en-us/library/8etzzkb6.aspx) in a HostX86 CL.exe, it won't find it. Or worse, if the typelibs have any use of INT_PTR, it might find a typelib for the arch_build instead of arch and be subtly wrong.

Or other tools might not come in multiple flavors, but support an -m32/-m64 flag which needs to be set according to the desired architecture whose registry you want them looking in (Win32 supoprts this sort of 'foreign' view with the [KEY_WOW64_* flags](https://docs.microsoft.com/en-us/windows/desktop/WinProg64/accessing-an-alternate-registry-view).

I'll admit this is rather niche usage. But conan did seem to be trying to handle this sort of thing by providing arch_build and os_build, os[Windows].subsystem for WSL, etc, as separate settings that could be configured through profiles and which tool packages could react to (adding -m32/-m64, calling the right vcvars, etc). So I figured it was worth investigating the places where it didn't seem to work, because it would be seriously great reach a point where  `conan create --profile X` does the right thing with all our cross-builds.  :-)

This is all much more important for arch_build vs platform.machine() than it is for os_build, though; I think almost every major OS kernel today currently or historically has some degree of multiarch support (x86/x64 is pretty much everywhere, linux has qemu-user, OSX had [rosetta](https://en.wikipedia.org/wiki/Rosetta_%28software%29), who knows what Apple and Microsoft will do as they both seem to be sniffing around ARM laptops. Having os_build != platform.system() is a lot less plausible - the only case I can think of is if you were running conan in a WSL python. 

So I'll certainly *understand* if the answer is that conan itself assumes that os_build == platform.system(), and weird things just need separate (matching) installations of python and conan in each sysroot. If that's the answer it seems like there should be some way of asserting when loading an unsupported profile though, and [Systems and cross building](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#using-profiles) should probably mention the restriction.

**Comment by puetzk** [comment]
Reviewing my open tickets, to clear out some of your clutter :-)

I think I had just confused myself on this one. I know I was thinking that platform.machine() reflected the arch python was built for, but I just re-tested and it definitely does not. It appears to have circumvented the WoW64 emulation for a long time (python/cpython@c9d1a7845ba18466ee048666239c6b969c9acd33).

Maybe I was just observing that it was failing to pick the right amd64_x86 vcvars, which would have actually been #3157 (it didn't follow arch_build, even if that *was* set correctly). Either that or I had somehow mangled up `%PROCESSOR_ARCHITECTEW6432%`. Either way, there doesn't seem to be a dependence on the python arch here.

**Comment by memsharded** [comment]
> Reviewing my open tickets, to clear out some of your clutter :-)

Great, many thanks for following up and helping to maintain this! :) :)
