### ISSUE TITLE
Conan seems to have trouble on Windows with Git's $HOME environment variable defined

### ISSUE THREAD

**Issue by XenonofArcticus** [conan-io/conan#318]
On Windows, if the `HOME` environment variable is defined (as commandline git often does for convenience), a call to 

`os.environ.get("HOME")`
will return 
`%USERPROFILE%`

instead of the actual User Profile folder. This breaks 
`os.path.expanduser("~")`
which then returns
`%USERPROFILE%`

instead of the actual user profile folder, which breaks all sorts of things in Conan.

The workaround is to un-set the HOME environment variable in the Windows shell. This can be done in the shell you're using with 
`set HOME=`

The long-term solution is to figure out why Python returns "`%USERPROFILE%`" from `os.environ.get("HOME")` when HOME has a well-defined value like `C:\Users\Foo`

**Comment by memsharded** [comment]
There is another workaround, which can be also long-term. Conan defines the environment variable ``CONAN_USER_HOME``. If it is defined, it will use it as the user home, and ``os.path.expanduser`` would not be checked at all.

In any case, I will try to find a solution, as it is likely that git for windows might be the one setting HOME, and other conan users might suffer this problem too.

**Comment by lasote** [comment]
Fixed in 0.10.0, please try it and reopen if needed.
