### ISSUE TITLE
Working around issues with tools.get

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#3188]
It is common in def source(self) method to have a sequence like:

tools.get("http://www.vtk.org/files/release/{0}/{1}-{2}.tar.gz" .format(self.short_version, self.name, self.version))

os.rename(extracted_dir, self.source_subfolder)

but in some environments tools.get fails. It would be nice if the failure mode was something like:

"Could not retrieve: :http://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz, 
if it is extracted and placed in directory : c:/users/fred/x/y/x the process can continue"

Then the conan.py file would have something like:
         if(os.path.isdir(dirFromAbove)):
             print('Found existing extracted dir:{0}, continuing '.format(dirFromAbove))
        else:
            tools.get("http://www.vtk.org/files/release/{0}/{1}-{2}.tar.gz"
                    .format(self.short_version, self.name, self.version))

Where dirFromAbove=c:/users/fred/x/y/x

This would allow a manual work around, but only request it if automation fails

**Comment by memsharded** [comment]
```python
def source(self):
        tools.download("https://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz", "vtk.tgz")
```
works, but
```python
def source(self):
        tools.get("https://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz")
```

fails with:

```
ERROR: Error downloading file https://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz: 'HTTPSConnectionPool(host='www.vtk.org', port=443): Max retries exceeded with url: /files/release/8.1/VTK-8.1.1.tar.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0458AB70>
```

Confirmed

**Comment by memsharded** [comment]
It failed, now it is working fine. The ``tools.get()`` internally uses exactly the same ``tools.download()``, so no evident bug here. Could be more a failure in the vtk server hosting the files.

Not sure what would be the desired behavior. In case of transfer failure, the current behavior seems the correct one: clean the ``source`` folder and that forces to restart the transfer.

**Comment by lasote** [comment]
I'm closing this issue if any of you still think there is something to do, please, comment and we will open it again.

**Comment by memsharded** [comment]
I think the main issues were server failures for https://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz download, which seems little we could do. I hope that server is working better now. Any other suggestion @ShamanTcler ? Thanks!
