### ISSUE TITLE
[Workspaces] Conan install should have an option to do a full build of all subprojects

### ISSUE THREAD

**Issue by jpkolbush** [conan-io/conan#3196]
-conan v 1.5.2
- macOs v 10.13.1
- apple-clang v 9.0.0

Hello,

It seems that one major limitation of conan workspaces is that it only runs the `conan install` methods of the conanfile, and doesn't allow the user any way to run the `build` method of the conan project. In the example project, the only way the projects get built is through calling cmake directly. There may be major differences between calling the build method of a project and simply including the top level CmakeLists of a project. What would be nice is for an option to do a full build of each project in the workspace. This could also include the package steps of a dependent conan project. That way the `includedirs` parameter could be set by the `self.cpp_info.includedirs` parameter of the conanfile.

I would like to use conan workspaces as a solution for the issue described [here](https://github.com/conan-io/conan/issues/1536), but without having to export dependent projects to the conan cache.

Let's consider the example project where a user wants to build Project A with their local version of Project B, rather than the normally specified version that's in their remotes. Ideally, in the user could just replace `requires = "HelloB/0.1@user/testing"` with something like `requires = "../B/"` and conan would have the capability to use that local version without exporting anything to the cache.  The current state of conan workspaces seem like a round-about way of achieving this.

**Comment by memsharded** [comment]
Yes, a way of calling build, like ``conan build`` but that it operates over the workspace, is something that we are considering. There are a few complexities to solve, but we might try to implement it.

However, regarding your suggestion of ``requires="../B"`` that is basically against one of the design requisites for Workspaces, is that they should work without modifications to the conanfiles. This is strongly required by many users, so it is unlikely that such way of specifying things will be implemented.

I will post updates here when things move foward. Thanks for the feedback!

**Comment by jpkolbush** [comment]
Thank you. The `conan build` feature for an entire workspace would be nice.

That makes sense about not wanting to change the conanfile. Out of curiosity, do you envision users keeping their projects as part of a workspace if they know that they will frequently be building them with their local copies?  Or do you see users setting up workspaces when they want to test local versions of the project together. Because I think the majority of use cases will end up being the later  (at least based on our workflow with conan projects). 

Typically, I will work on project A and project B separately, and they may even exist in separate repos.  But occasionally, I want to test to see how my latest changes to project B affect project A. Through the conan workspace solution, doing this would involve setting up a conanws.yml file for a one time test build. Is this an anticipated use case or are workspaces more designed to be a static fixture?

**Comment by memsharded** [comment]
Editables in Conan 2.0 will run the ``build()`` method if ``--build=editable``.
Closing this as solved.
