### ISSUE TITLE
Upgrading to Conan 1.x - `self.conanfile_directory`

### ISSUE THREAD

**Issue by alessandrodn-cybereason** [conan-io/conan#3198]
Hi,
I have some (internal) package, managed via Conan.
So far I'm using Conan 0.25, and I would like to upgrade to Conan 1.x.

To keep things simple I use a Python Conan file, that reads the requirements from a text file,

```
    def requirements(self):
        requirements_file = open(self.conanfile_directory + '/requirements.txt', 'r')

        for line in requirements_file:
            self.requires("%s" % line)

```

The `requirements.txt` is a simple file containing the required packages' reference.

How can I migrate such scenario in 1.x, where there is no `self.conanfile_directory`?
Basically, since from 1.x every conan command take a path, is there a way to get this path in the recipe?

Thanks a lot
Alessandro

**Comment by memsharded** [comment]
Hi Alessandro,

Yes, the directory where the conanfile lives can be obtained directly with python. The following code works for the ``conan create`` and also the local flow with ``cd build && conan install ..``:

```python
class LibraryConan(ConanFile):
    name = "Library"
    version = "1.0"
    exports = "requirements.txt"
    
    def requirements(self):
        conanfile_directory = os.path.dirname(__file__)
        path = os.path.join(conanfile_directory, 'requirements.txt')
        with open(path, 'r') as requirements_file:
            for line in requirements_file:
                self.requires("%s" % line)
```

Please tell me if this works for you. Thanks!

**Comment by alessandrodn-cybereason** [comment]
Works great!!

Thanks a lot
