### ISSUE TITLE
find_package generator leaving <library>_LIBRARIES empty for CMake > 3.0

### ISSUE THREAD

**Issue by kutschkem** [conan-io/conan#3199]
To help us debug your issue please explain:

On Ubuntu 16.04, conan 1.5.1, cmake 3.11.4:

The cmake_find_package does not fill \<library\>_LIBRARIES if libraries are found in the package and CMake version is > 3.0. It only fills \<library\>_LIBRARIES_TARGETS. If the libraries are not found in the package, then both \<library\>_LIBRARIES and \<library\>_LIBRARIES_TARGETS are filled, leading me to the conclusion that not filling \<library\>_LIBRARIES if it is found is an oversight.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
You are right, this is a bug, easy to solve. I'll open a PR for the 1.6
