### ISSUE TITLE
dyld: Library not loaded: libgtest.dylib

### ISSUE THREAD

**Issue by sssilver** [conan-io/conan#3200]
Hi,

I'm using Conan 1.5.2 on macOS 10.13.5 and cmake 3.12.0-rc3.

conanfile.txt:
```
[requires]
gtest/1.7.0@bincrafters/stable

[generators]
cmake
```

I run:
```
$ cd build
$ conan install ..
PROJECT: Installing /Users/silver/Projects/tsg/sphere-game/conanfile.txt
Requirements
    gtest/1.7.0@bincrafters/stable from 'conan-center' - Cache
Packages
    gtest/1.7.0@bincrafters/stable:17bbaf14f04b80904f04c74eda265378d62c479f - Cache

gtest/1.7.0@bincrafters/stable: Already installed!
PROJECT: Generator cmake created conanbuildinfo.cmake
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
```
```
$ cmake ..
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Current conanbuildinfo.cmake directory: /Users/silver/Projects/tsg/sphere-game/build
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
cxx Flags:-g -Wall -Wextra -O3 -std=c++11 -stdlib=libc++
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/silver/Projects/tsg/sphere-game/build
```
```
$ cmake --build .
Scanning dependencies of target SphereGame
[ 25%] Building CXX object CMakeFiles/SphereGame.dir/src/main.cpp.o
[ 50%] Building CXX object CMakeFiles/SphereGame.dir/src/Kernel/Kernel.cpp.o
[ 75%] Building CXX object CMakeFiles/SphereGame.dir/src/Kernel/DummySubsystem.cpp.o
[100%] Linking CXX executable bin/SphereGame
[100%] Built target SphereGame
```
All looks good by this point, however when trying to run the binary, I get:
```
$ bin/SphereGame
dyld: Library not loaded: libgtest.dylib
  Referenced from: /Users/silver/Projects/tsg/sphere-game/build/bin/SphereGame
  Reason: image not found
[1]    62953 abort      bin/SphereGame
```
What am I doing wrong?

Many thanks.

**Comment by sssilver** [comment]
Curiously, changing `gtest/1.7.0@bincrafters/stable` to `gtest/1.8.0@bincrafters/stable` makes it work. I suppose a broken build that needs to be removed?

**Comment by danimtb** [comment]
Hi @sssilver,

If you have a look at `gtest/1.7.0@bincrafters/stable` you will see that shared option is set to true by default, however, `gtest/1.8.0@bincrafters/stable` has it defaulted to false. So, in first case, you are linking with gtest dynamically whereas, in the second one, you are doing it statically.

To solve the issue, there are 2 approaches:

- Keeping dynamic linkage:
  Use `[imports]` to copy _*.dylib_ files next to your executable:
  ```
  [imports]
  lib, *.dylib* -> ./bin # Copies all dylib files from packages lib folder to my local "bin" folder
  ```

  And then execute your app like this:
  ```
  $ LD_LIBRARY_PATH=$(pwd) && ./SphereGame
  ```

  You may find this section of the documetation useful: [How to manage shared libraries](https://docs.conan.io/en/latest/howtos/manage_shared_libraries.html)

- Use static linkage:
  Set the gtest package to use` shared=false`:
  ```
  [options]
  gtest:shared=True
  ```

Hope it helps! Thanks for posting 😄

**Comment by danimtb** [comment]
@sssilver did you manage to solve this issue? Any update on your progress? Thanks

**Comment by sssilver** [comment]
Hi,

The problem was that I was linking gtest to my app in two places, one through Conan and one directly.

The issue can be closed now. Many thanks!
