### ISSUE TITLE
cmake_find_package_generator does not generate guards

### ISSUE THREAD

**Issue by kutschkem** [conan-io/conan#3201]
To help us debug your issue please explain:

Ubuntu 16.04, conan 1.5.1, cmake 3.11.4:
Using the cmake_find_package generator with a project that calls find_package multiple times on the same library is not safe because the generated find_package script does not guard against being called multiple times. Since the script generates targets, this will cause cmake to fail the build.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi, I'm reviewing the code and we have:

`if(NOT TARGET {name}::{name})`

Is that not enough? I'm reviewing also the CMake native find modules and they only guard the targets. 
Thanks!

**Comment by kutschkem** [comment]
I need to specify: The problem is the micro-targets, not the "big one". Those don't have a guard.
