### ISSUE TITLE
Error while building boost with conan

### ISSUE THREAD

**Issue by restenb** [conan-io/conan#3205]
I'm new to Conan and trying to build a project that includes boost packages. However the build fails with the following error message: 

```
boost_python/1.65.1@bincrafters/stable:
boost_python/1.65.1@bincrafters/stable: ERROR: Package '12f473e54e00049ac1c764cc8445756b0dd81945' build failed
boost_python/1.65.1@bincrafters/stable: WARN: Build folder C:/.conan\qm92a3eb\1
ERROR: boost_python/1.65.1@bincrafters/stable: Error in build() method, line 135
        boost_package_tools.build(self)
        ConanException: Error 1 while executing b2 -j8 -a --hash=yes --debug-configuration --layout=system  include=graph/include include=multi_index/include include=parameter/include include=property_map/include include=serialization/include include=unordered/include python-build

```

I don't know how to interpret this. What is "ConanException: Error 1"? Is this a problem with Conan, or with Boost? The error does originate from conanfile.py in boost_python. 

Additionally, are there resources such as a slack or IRC channel where it is possible to get in contact with experienced users? This might very well be a beginner problem. 

I'm using the latest version of Conan (1.5.2) on Windows 10, trying to build with version 1.65.1 of boost.

**Comment by lasote** [comment]
Hi! There is a slack channel in the cppclang.slack.com
There are many users answering questions.
About this particular error, it is failing while calling "b2" during the boost building. It is not common that this happens, but probably you have to check the logs in the build directory to know more.

About the issues related with packages, the place to report it is the issue tracker of each package, for all the bincrafters packages you can open the issue at: http://github.com/bincrafters/community

Also there is a #bincrafters channel in the cpplang slack.

**Comment by memsharded** [comment]
In https://cpplang.now.sh/ there are two different channels: #conan channel, for all conan things, and the #bincrafters channel, they are the creators of the modularized boost package you are using.
