### ISSUE TITLE
SDL2 2.0.4 - GL.lib not found on Windows 10, Visual Studio 2015

### ISSUE THREAD

**Issue by Facon** [conan-io/conan#321]
I'm creating a very small application which will have 2 visual frontend (for plugin-like architecture), but I'm having problems linking SDL2, because I can't find any GL.lib, which you can only find on Linux.

Here's all config files that I have, I hope it's enough information to fix the bug.

**conan.conf:**

    [storage]
    # This is the default path, but you can write your own
    path: ~/.conan/data
    
    [proxies]
    # Empty section will try to use system proxies.
    # If don't want proxy at all, remove section [proxies]
    # As documented in http://docs.python-requests.org/en/latest/user/advanced/#proxies
    # http: http://user:pass@10.10.1.10:3128/
    # http: http://10.10.1.10:3128
    # https: http://10.10.1.10:1080
    
    [settings_defaults]
    arch=x86_64
    build_type=Debug
    compiler=Visual Studio
    compiler.runtime=MT
    compiler.version=14
    os=Windows

**conanfile.txt:**

    [requires]
    catch/1.3.0@TyRoXx/stable
    sfml/2015.8.12@TyRoXx/develop
    SDL2/2.0.4@lasote/stable
    
    [generators]
    visual_studio
    cmake

**conanbuildinfo.props:**

	<?xml version="1.0" encoding="utf-8"?>
	<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	  <ImportGroup Label="PropertySheets" />
	  <PropertyGroup Label="UserMacros" />
	  <PropertyGroup />
	  <ItemDefinitionGroup>
		<ClCompile>
		  <AdditionalIncludeDirectories>C:/Users/Facon/.conan/data/SDL2/2.0.4/lasote/stable/package/276e2f43175bc2fdba54a2017bd92de9e1d2f49f/include;C:/Users/Facon/.conan/data/catch/1.3.0/TyRoXx/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include;C:/Users/Facon/.conan/data/sfml/2015.8.12/TyRoXx/develop/package/514f98a08e602783f25cd8024004f8dfc2607008/include;C:/Users/Facon/.conan/data/zlib/1.2.8/lasote/stable/package/33e319a11fada43f82117538385245276fd65c32/include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		  <PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
		  <AdditionalOptions>/DWIN32 /D_WINDOWS /W3 %(AdditionalOptions)</AdditionalOptions>
		</ClCompile>
		<Link>
		  <AdditionalLibraryDirectories>C:/Users/Facon/.conan/data/SDL2/2.0.4/lasote/stable/package/276e2f43175bc2fdba54a2017bd92de9e1d2f49f/lib;C:/Users/Facon/.conan/data/catch/1.3.0/TyRoXx/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib;C:/Users/Facon/.conan/data/sfml/2015.8.12/TyRoXx/develop/package/514f98a08e602783f25cd8024004f8dfc2607008/lib;C:/Users/Facon/.conan/data/zlib/1.2.8/lasote/stable/package/33e319a11fada43f82117538385245276fd65c32/lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		  <AdditionalDependencies>SDL2.lib;GL.lib;SDL2main.lib;user32.lib;gdi32.lib;winmm.lib;imm32.lib;ole32.lib;oleaut32.lib;version.lib;uuid.lib;sfml-audio-d.lib;sfml-graphics-d.lib;sfml-network-d.lib;sfml-window-d.lib;sfml-system-d.lib;zlibstaticd.lib;%(AdditionalDependencies)</AdditionalDependencies>
		  <AdditionalOptions> %(AdditionalOptions)</AdditionalOptions>
		</Link>
	  </ItemDefinitionGroup>
	  <ItemGroup />
	</Project>

**Comment by memsharded** [comment]
Hi! Thanks for reporting. This might be an issue of the SDL2 package, not conan. But no problem, I will have a look and report back, maybe we could open an issue to the SDL2 package (or better, try to contribute a fix if it happens that it is missing proper support for Win. I am thinking that in win it should link to OpenGL32, maybe the SDL2 package forgot that)

**Comment by memsharded** [comment]
Hi again! Yes, it seemed that SDL package had an issue in Win. As it was easy, I have submitted a PR to the package creator: https://github.com/lasote/conan-sdl2/pull/2, so it will likely be fixed very soon.

**Comment by memsharded** [comment]
I am closing this issue now, as it is not a conan issue. But we can follow the conversation if necessary in https://github.com/lasote/conan-sdl2/pull/2, and in https://github.com/lasote/conan-sdl2 issues if necessary. Thanks again for submitting this issue.
