### ISSUE TITLE
[question] accessing options for packages in [build_requires]

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#3213]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.5.2, Ubuntu 16.04

I have some toolchain packages whose options control the environment provided; these options are intended to be set in a profile which also adds the [build_requires] on this toolchain package in the first place. In a few cases a package which is closely coupled with the platform also needs to react to these options (e.g. handle steps in build() to special-case something I can't set up through just environment variables.

In configure() and requirements(), the options for these build_requires packages show up in self.options['build_required_package'].foo as I expected. But by build_requirements or build() it self, they are gone. This seems to happen because conans.client.graph.DepsGraph.compute_package_ids calls conans.model.options.Options.clear_unused, removing the options for all packages not listed in requirements. 

```python
                # There might be options that are not upstream, backup them, might be
                # for build-requires
                conanfile.build_requires_options = conanfile.options.values
                conanfile.options.clear_unused(indirect_reqs.union(direct_reqs))
```

It does preserve the original (complete) set of options in a conanfile member called build_requires_options, which (since its on ConanFile) is accessible in the build_requirements() and build() methods. But this does not seem to be documented. It's not named with the "keep out!' leading underscore, but I'm not sure if accessing it is legitimate usage or poking at internals I should stay away from.

It seems like either way https://docs.conan.io/en/latest/mastering/conditional.html#conditional-settings-options-and-requirements
should mention this behavior of pruning options if they turn out to be unused by requires, and either document the existence of build_requires_options or the fact that you can't access options for packages which are only in build_requires.

I think I could use self.requires and unrelated_mode() for my specific use case if there's some hidden gotcha that makes concealing the options for build_requires necessary...

**Comment by memsharded** [comment]
Very good research into the details of how it works. The reason for this behavior is:

- First conan computes the dependency graph of regular requires, mostly libraries.
- Then it computes the necessary "package ID" for each package, to see if the binaries are there or not, they need to be downloaded, or built.
- By definition, the "build-requires" do not affect the "package ID". Those IDs should be exactly the same if they have to be built or download, if they are built with a conan package build-tool, or with a system installed tool. 
- This is the reason the ``options`` that are not used in the regular dependency graph are stripped.
- The ``build_requires_options`` are stored to be passed to the build dependency graph

So, I think these options could be used. But please take into account that the most important thing is that you need to make sure that the binary that will be generated for the library doing the ``build_require`` should be exactly the same irrespective of the option of such ``build_require``. If it is not the case, probably you would need to add some option to the library conanfile.

Please tell me. I will check if there is some reason not to add it to the docs, and add  it if everything is good. Thanks!

**Comment by memsharded** [comment]
Hi @puetzk Kevin,

I am checking this for conan 1.7, and so far ``build_requires_options`` seems mostly an implementation detail, and probably shouldn't be used. I am thinking to convert it to private with an underscore.

The reason is that I cannot think of any use case that requires reading this variable. It would be a write-only cache, from the UI, the user only defines ``options`` no matter if options from regular dependencies or from build-requires. Reading regular dependencies options makes sense, as different builds can be done, and those dependencies options can affect the package ID. But reading ``build_requires_options``, is the use case I cannot imagine a scenario. If some option affect the build-require, that would be managed by the package that implements that build-require, but shouldn't affect the logic/code from the consumer.

Could you please share more details about your use case, and why would this be necessary? Many thanks!

**Comment by puetzk** [comment]
Sorry for the late reply, just getting back to this.

Basically, I have some packages which contains a variety of cmake toolchain files, QMake mkspecs, defining how to call various cross-toolchain flavors. This `toolchain` package, containing no binary code, has an essentiall y empty package_id (it's just a copy of all the scripts), but nonetheless has some options and reacts to a lot of settings; it's meant to be sucked in by building with a profile that that sets you up to get a particular build, i.e.

```
[build_requires]
toolchain/<version>@<user>/<channel>

[settings]
os=...
compiler=...
```

The profile for our embedded environments sets a build_requiers on this toolchain package and the relevant settings to describe which binary results, and individual producers use default_options to turn on options like `toolchain:cmake=True` telling it which build tools to provide environment for. Then the toolchain package's conanfile.py it will use its system_requirements and requirements functions to actually depend on the toolchain matching the resolved settings, and in package_info it will set
things like `self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE` or `self.env_info.QMAKESPEC`, or even just basics like `self.env_info.CC`, so that your build will use that compiler.

It can't help you for every possible build-system of course, but it handles the ones I actually care about. I viewed it as an analogous extension of the way conan does some of this already in some cases, e.g. -s 'compiler=Visual Studio' -s 'compiler.version' affects the generator chosen by the `conans.CMake` build helper class, and hence the toolset chosen by msbuild.

So far so good. But there can be a few more subtle ways that the chosen compiler influences the package being built. Not all options necessarily work on all toolchains so there might be an option that needs to be disabled in `configure(self)` for one platform (e.g. a feature that is windows-only). Or I might be using a system_requires on one platform vs a conan-built requires on another to provide some dependency. Mostly these can be modeled based on self.settings, paralleling the logic in toolchain that picked compilers but obviously enough that the redundancy isn't too awkward.

But a few of the possible toolchains have one more wrinkle: options that trigger the use of a compiler wrapper (e.g. `-o toolchain:winelib=True` means you compile/link using winegcc instead of gcc). This doesn't necessarily map to anything in settings.compiler, since the wrapper does call the underlying compiler, and it can be perfectly legit to pick non-winelib binaries to be linked into a winelib executable.
But compiling/linking with winegcc will cause you to be dynamically linked to libwine, so the resulting binaries have an extra dynamic-linked dependency that should be represented in the requires and thus have a version that participates in package_id.

Now, a build_requires reaching upward to add requirements to its consumer (thus even changing the consumer's package_id) is really weird, and seems like the sort of spooky action at a distance that plays all sort of havoc on conans dependency graph and is an all-around terrible idea.And it's not like a package that might build with MSVC or might build with winegcc doens't already have to have a fair amount of special-casing for windows vs linux. So I expected to have to explicitly include some logic in the consumer to implement the conditional dependency. But I **was** hoping to just have it read if `self.options['toolchain'].winelib: self.requires("wine/...")`, not need to have one way that the user tells the toolchain to pick winegcc, and a separate way they tell the consumer package that they did so. And this indeed works fine in `requirements`. It just doesn't work in `build_requirements` or `system_requirements`.

**Comment by puetzk** [comment]
Hmm. Thinking about this even more, and apparently my mental model of you is a good debater with excellent points. I think he's succeeded in convincing me I should not be peeking into the build_dependency's options to see what the profile put there.

This is really a lot like the connection between -s cppstd generally setting compiler flags, but those same flags usually sometimes needing to be reflected back into a different value for compiler.libcxx to properly describe the resulting binaries, but in other cases allowing a mixture (thus, it's *not* settings.compiler.cppstd, because then anything with settings = "compiler" would be locked in.

So I'm now thinking I should have a profile set [settings]winelib=True, but only list settings =  ..., "winelib" in packages that are actually support being built with winegcc, and pass that down into my toolchain package via something like:

``` python
config_options(self):
    if self.settings.os=='windows':
        del self.settings.winelib # don't support (or need) winelib if actually on windows

requirements(self):
    if self.settings.winelib:
        self.requires("wine/[*]@...") # expecting the actual version to be overridden from the profile

build_requirements(self):
    if self.settings.winelib:
        # I do not want toolchain to look directly at settings.winelib, 
        # because I don't want it to configure for winegcc on behalf of a consumer
        # that that didn't list winelib in their settings
        self.build_requires_options['toolchain'].winelib = True 
```

That way the profile's setting only acts on package that opt-in by listing it, other packages don't and it stays out of their package_id (thus you can still consume a non-winelib library with winelib=True), but you can't consume a winelib-aware package in a non-winelib profile (which doesn't actually work, and my previous configuration would have let you try).

But:
1) is it kosher to manipulate self.settings in config_options? you show a few examples of clearing settings in configure() based on assigned options (e.h. options.header_only leading to self.settings.clear()), so I assume doing it based on another setting (and thus even earlier) is OK too...

2) This still needs a way to *set* (though no longer read) options on a build_required package, but should do so only for its own build_requires (if it's just being consumed, the options should be up to the consumer, if this build_requires package is loaded at all). And I'm not sure how to do that if you take build_requires_options private. It seems like this shouldn't pose any direct problem in terms of package_id (build_requires don't participate) or version selection (you can't have already-committed to what recipe/package_id will satisfy the build_requires before you've even made the callback to complete the list of packages needed).

**Comment by puetzk** [comment]
I made up a test case ([conan-build-required.zip](https://github.com/conan-io/conan/files/2440008/conan-build-required.zip)) and setting options through self.build_requires_options from build_requirements seems to work exactly how I'd like it to, including potentially resolving the build_required package separately (potentially with different options) on behalf of each package being built, with each consumer recieving the deps_*_info matching its requested options:

```sh
conan export build_required/ re41236/test
conan export required/ re41236/test
conan create consumer re41236/test --build required --build consumer --build missing
```

Summarizing the relevant lines, build_required gets configured and identified twice

    build_required/0.1@re41236/test: build_required:configure()
    build_required/0.1@re41236/test: build_required:package_id() option=consumer:build_requires
    build_required/0.1@re41236/test: build_required:configure()
    build_required/0.1@re41236/test: build_required:package_id() option=required:build_requires

And this resolves to two different binaries (both in the cache already)

    build_required/0.1@re41236/test:32c2ada27587a2e10516e5872d8ceb4c61db3305 - Cache
    build_required/0.1@re41236/test:728424e1ec6b0d38476a800108394b71c56aa049 - Cache
    ...
    build_required/0.1@re41236/test: build_required:package_info() option=required:build_requires
    build_required/0.1@re41236/test: build_required:package_info() option=consumer:build_requires

And each package that requested the build_requires got the deps_user_info matching the value they passed in options (just a simple way of showing things matched up)

    required/0.1@re41236/test: required:build(): deps_user_info['build_required'].option = required:build_requires
    consumer/0.1@re41236/test: consumer:build(): deps_user_info['build_required'].option = consumer:build_requires

The full trace:
    Exporting package recipe
    Linter warnings
        WARN: Linter. Line 18: Instance of 'ConsumerConan' has no 'build_requires_options' member 
    consumer/0.1@re41236/test: The stored package has not changed
    consumer/0.1@re41236/test: consumer:configure()
    required/0.1@re41236/test: required:configure()
    consumer/0.1@re41236/test: WARN: Forced build from source
    required/0.1@re41236/test: WARN: Forced build from source
    build_required/0.1@re41236/test: build_required:configure()
    build_required/0.1@re41236/test: build_required:package_id() option=consumer:build_requires
    build_required/0.1@re41236/test: build_required:configure()
    build_required/0.1@re41236/test: build_required:package_id() option=required:build_requires
    consumer/0.1@re41236/test: Installing package
    Requirements
        consumer/0.1@re41236/test from local cache - Cache
        required/0.1@re41236/test from local cache - Cache
    Packages
        consumer/0.1@re41236/test:b9df24d3e076234951cfdb988d6a6f640969bbd7 - Build
        required/0.1@re41236/test:90ee443cae5dd5c1b4861766ac14dc6fae231a92 - Build
    Build requirements
        build_required/0.1@re41236/test from local cache - Cache
        build_required/0.1@re41236/test from local cache - Cache
    Build requirements packages
        build_required/0.1@re41236/test:32c2ada27587a2e10516e5872d8ceb4c61db3305 - Cache
        build_required/0.1@re41236/test:728424e1ec6b0d38476a800108394b71c56aa049 - Cache
    
    build_required/0.1@re41236/test: Already installed!
    build_required/0.1@re41236/test: build_required:package_info() option=required:build_requires
    build_required/0.1@re41236/test: WARN: Lib folder doesn't exist, can't collect libraries: /var/lib/conan/.conan/data/build_required/0.1/re41236/test/package/32c2ada27587a2e10516e5872d8ceb4c61db3305/lib
    build_required/0.1@re41236/test: Already installed!
    build_required/0.1@re41236/test: build_required:package_info() option=consumer:build_requires
    build_required/0.1@re41236/test: WARN: Lib folder doesn't exist, can't collect libraries: /var/lib/conan/.conan/data/build_required/0.1/re41236/test/package/728424e1ec6b0d38476a800108394b71c56aa049/lib
    required/0.1@re41236/test: Applying build-requirement: build_required/0.1@re41236/test
    required/0.1@re41236/test: Building your package in /var/lib/conan/.conan/data/required/0.1/re41236/test/build/90ee443cae5dd5c1b4861766ac14dc6fae231a92
    required/0.1@re41236/test: Copying sources to build folder
    required/0.1@re41236/test: Generator txt created conanbuildinfo.txt
    required/0.1@re41236/test: Calling build()
    required/0.1@re41236/test: required:build(): deps_user_info['build_required'].option = required:build_requires
    required/0.1@re41236/test: Package '90ee443cae5dd5c1b4861766ac14dc6fae231a92' built
    required/0.1@re41236/test: Build folder /var/lib/conan/.conan/data/required/0.1/re41236/test/build/90ee443cae5dd5c1b4861766ac14dc6fae231a92
    required/0.1@re41236/test: Generated conaninfo.txt
    required/0.1@re41236/test: Generated conanbuildinfo.txt
    required/0.1@re41236/test: Generating the package
    required/0.1@re41236/test: Package folder /var/lib/conan/.conan/data/required/0.1/re41236/test/package/90ee443cae5dd5c1b4861766ac14dc6fae231a92
    required/0.1@re41236/test: Calling package()
    required/0.1@re41236/test package(): Copied 2 '.txt' files: conanbuildinfo.txt, conaninfo.txt
    required/0.1@re41236/test: Package '90ee443cae5dd5c1b4861766ac14dc6fae231a92' created
    required/0.1@re41236/test: WARN: Lib folder doesn't exist, can't collect libraries: /var/lib/conan/.conan/data/required/0.1/re41236/test/package/90ee443cae5dd5c1b4861766ac14dc6fae231a92/lib
    consumer/0.1@re41236/test: Applying build-requirement: build_required/0.1@re41236/test
    consumer/0.1@re41236/test: Building your package in /var/lib/conan/.conan/data/consumer/0.1/re41236/test/build/b9df24d3e076234951cfdb988d6a6f640969bbd7
    consumer/0.1@re41236/test: Copying sources to build folder
    consumer/0.1@re41236/test: Generator txt created conanbuildinfo.txt
    consumer/0.1@re41236/test: Calling build()
    consumer/0.1@re41236/test: consumer:build(): deps_user_info['build_required'].option = consumer:build_requires
    consumer/0.1@re41236/test: Package 'b9df24d3e076234951cfdb988d6a6f640969bbd7' built
    consumer/0.1@re41236/test: Build folder /var/lib/conan/.conan/data/consumer/0.1/re41236/test/build/b9df24d3e076234951cfdb988d6a6f640969bbd7
    consumer/0.1@re41236/test: Generated conaninfo.txt
    consumer/0.1@re41236/test: Generated conanbuildinfo.txt
    consumer/0.1@re41236/test: Generating the package
    consumer/0.1@re41236/test: Package folder /var/lib/conan/.conan/data/consumer/0.1/re41236/test/package/b9df24d3e076234951cfdb988d6a6f640969bbd7
    consumer/0.1@re41236/test: Calling package()
    consumer/0.1@re41236/test package(): Copied 2 '.txt' files: conanbuildinfo.txt, conaninfo.txt
    consumer/0.1@re41236/test: Package 'b9df24d3e076234951cfdb988d6a6f640969bbd7' created
    consumer/0.1@re41236/test: WARN: Lib folder doesn't exist, can't collect libraries: /var/lib/conan/.conan/data/consumer/0.1/re41236/test/package/b9df24d3e076234951cfdb988d6a6f640969bbd7/lib

**Comment by puetzk** [comment]
So I guess that just comes back to the original question of whether build_requires_options can remain public (and presumably be documented, listed in the pylint dynamic_fields). You've convinced me that I should invert which package is in control, though, so I'm now looking to set options in build_depends rather than peek at them, but that still needs accesss to it.

**Comment by puetzk** [comment]
:mouse2: polite squeak...

Since 1.8 is now out, this got set for 1.9, and it's evolved back into just "it already works the way I want if the existing implementation can be considered public"

Do you have concerns with the idea of packages setting options on their own build_depends (in this way, or in general)? Or if you haven't had time to think about it, when you might? If you have more questions, would it help to set up a time when I can be in the freenode#conan IRC or cpplang.now.sh#conan slack channels?

**Comment by lasote** [comment]
Hi @puetzk we really didn't get time to take a look, sorry.

**Comment by memsharded** [comment]
All this changed in 2.0:

- ``tool_requires(..., options={})`` allow to specify options at the requirement level.
- options have been removed by default in the consumers ``package_id``, and only via indirect ``package_id`` of the dependency, or the consumer explicitly opting-in to use the dependencies options, will be affecting consumers again.

I think the above address the original issue, so closing it as solved, but feedback welcome!
