### ISSUE TITLE
force_vcvars=True might not be working in some cases

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3215]
**Summary**
When running `conan create . test/testing` normally for my internal projects, it works correctly.  If I run the same command from within the Visual Studio IDE (for example, using the interactive powershell prompt), it fails to find `msbuild`.  It seems likely that this is related to vcvars, but I am not sure.  I recall digging into the implicit environment variables passed to any child process spawned from the Visual Studio IDE as part of the research leading up to my original request for the `force_vcvars` feature.  I recall that Conan was checking for some of these variables for the "vcvars already run" detection.  In theory, the force should cause Conan to disregard any such variables, but perhaps there's still a check being done somewhere which nobody has caught yet because nobody is trying to launch `conan create` from the IDE in this way.  Can someone please just double check to see if there's some chance `force_vcvars` has a bug.  If it looks good and there's a unit test to prove it, I can make more steps to isolate.

**build() call**
```
            msbuild.build(
                self._build_filename, 
                upgrade_project=False,
                force_vcvars=True,
                targets=self._build_targets,
                platforms={"x86":"Win32"},
            )
```
**Output**
```
mylib/2019.0@test/testing: Skipped sln project upgrade
Conan:vcvars already set 
'msbuild' is not recognized as an internal or external command,
operable program or batch file.
mylib/2019.0@test/testing: 
```
Reference: 
https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html#build

Steps to reproduce:

Create a `conanfile.py` alongside a visual studio solution/project
Define a `build()` method that uses the `MSBuild()` helper
Pass the `force_vcvars=True` parameter to the helpers `build()` method
Open the solution/project in visual studio
Click Tools -> OtherWindows -> Interactive Powershell Window
Run `conan create . test/testing`

- [ X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I've looked at the code and the `force` variable meaning is: Do not raise if VS is already set but in a different version, but it is not setting the environment again if it is already set. I would expect `force` parameter to run again the `vcvarsall` if needed. WDYT @memsharded?

**Comment by solvingj** [comment]
I believe this was some issue in my environment. I got past it somehow and haven't run into it again since.
