### ISSUE TITLE
Cannot find library on Linux

### ISSUE THREAD

**Issue by sssilver** [conan-io/conan#3216]
Hi,

I'm using Conan 1.5.2 on Ubuntu 18.04LTS with cmake 3.10.2.

My project builds and compiles well on Windows 10 with the latest Visual Studio, and macOS with the latest Xcode. However, on Linux my binary is failing to link against libgtest:

```
$ cmake --build .
[ 33%] Built target SphereGame
[ 50%] Linking CXX executable bin/SphereGameApp
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgmock_main
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgmock
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgtest
collect2: error: ld returned 1 exit status
CMakeFiles/SphereGameApp.dir/build.make:95: recipe for target 'bin/SphereGameApp' failed
make[2]: *** [bin/SphereGameApp] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/SphereGameApp.dir/all' failed
make[1]: *** [CMakeFiles/SphereGameApp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

This happens despite:
```
$ find ~/.conan -name "*gtest*.a"
/home/silver/.conan/data/gtest/1.8.0/bincrafters/stable/package/4a699f6544a22ee0f016b38dfb91e2cc97c2e323/lib/libgtest_main.a
/home/silver/.conan/data/gtest/1.8.0/bincrafters/stable/package/4a699f6544a22ee0f016b38dfb91e2cc97c2e323/lib/libgtest.a
```

What am I doing wrong on Linux?

Many thanks.

**Comment by sssilver** [comment]
This https://github.com/conan-io/conan/issues/2660 seems to be relevant?

**Comment by memsharded** [comment]
Could also be a small discordance of the settings. Please copy here your default profile in linux. Please note that the default libcxx is libstdc++, but your compiler might be libstdc++11 (you might want to change that default, there are reasons to have it that way, mostly retro compatibility). Which is your compiler version? The rpath might be something for runtime, but shouldn't be the case of a failure to link.

**Comment by memsharded** [comment]
Closing this as inactive, please open new tickets if necessary.
