### ISSUE TITLE
Support  system_requirements() for consumer recipes

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3217]
It would be great if `system_requirements()` method were called for consumer recipes as well.

**Comment by memsharded** [comment]
Hi @db4 !

I have added a couple of tests here: https://github.com/conan-io/conan/pull/3226/files and it seems this functionality is already implemented. Could you please check the tests and clarify what would be the issue? Thanks.

**Comment by db4** [comment]
@memsharded,
You are right, it really works. I just expected (for unknown reason) that `sys_requirements()` should be called before `requirements()`. It was my fault, sorry for that.

**Comment by memsharded** [comment]
No problem! :)
