### ISSUE TITLE
Decrease in the number of min_chars for channels

### ISSUE THREAD

**Issue by Defvyb** [conan-io/conan#3231]
Hello, the issue deal with  _min_chars = 2 value. 

https://github.com/conan-io/conan/blob/3b6fcc102cf80e6ef74548c81930a008120be7cc/conans/model/ref.py#L9

When i try to build to user/channel like user/12 everything is ok, but it is impossible when it is like user/6 because of _min_chars limitations.
```
ERROR: '6' is too short. Valid names must contain at least 2 characters.
```

We are using short names to deploy binaries for testers to artifactory. So testers can get artifacts from paths like
for_testing/1
for_testing/2
...
for_testing/n
where n is build number in CI system.
Now we need a crutch for numbers from 1 to 9

Is it possible to decrease _min_chars value to 1. 

We are using conan.io 1.5.2 in ubuntu 18.

**Comment by lasote** [comment]
A Conan reference format affects to the implementations in Artifactory, Bintray, Conan server and Conan client, so it would require important changes. We took the decission of require 2 chars min and we are going to keep it.
I think you can use "01" to workaround it.

**Comment by Defvyb** [comment]
ok
