### ISSUE TITLE
Disable RPATH adjustment in CMake generator on Mac? or add it to Linux? (Conan 2.0)

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3234]
It was added because the linker was failing if a rpath (in an `exe` or a dylib) is pointing to a non-existing path, even specifying the `DYLD_LIBRARY_PATH` or at least we believed that.

I tested again and that is not true, the linker is not failing even with a broken rpath in a dylib while you specify a `DYLD_LIBRARY_PATH` where to find the missing dylib.

It makes no sense anymore to disable rpaths in OSX and not in Linux. So, to not introduce breaking changes we probably should wait for 2.0 and remove the rpaths adjustments.

**Comment by lasote** [comment]
Note: Another aspect to consider is, the SKIP in cmake we use, "peels" the rpath to only the dylib name, so probably importing all the dylibs to the exe folder works. But, Why aren't we doing the same in linux? Verify with new tests.

**Comment by oliora** [comment]
Does it effectively mean to have `KEEP_RPATH` set by default?

**Comment by memsharded** [comment]
This has been already addressed by the new generators and integrations, we can close it.
