### ISSUE TITLE
Conan modifies cpp_info.sharedlinkflags and linker stops linking

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#3236]
Hi there,

Situation
-------------------
I tried using the cpp_info.sharedlinkflags field to instruct a linker that links against my package to use the following additional flags:
- NODEFAULTLIB:abc.lib
- DEFAULTLIB:def.lib

While compiling with Visual Studio 2015 (Win x86_64)

The following line in the conanfile.py 
``` python
self.cpp_info.sharedlinkflags = ["/NODEFAULTLIB:abc.lib", "/DEFAULTLIB:def.lib"]
```
gets changed to
link.exe ... somelib.lib NODEFAULTLIB:abc.lib.lib DEFAULTLIB:def.lib.lib kernel32.lib user32.lib ...

Investigation
-----------------
As you can see the slash is missing and an additional ".lib" gets appended to the string.
I investigated the FindPACKAGE.cmake file that gets generated for consumers from my conanfile.py and found that the flags getting appended to [INTERFACE_LINK_LIBRARIES](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_LINK_LIBRARIES.html).
See at the bottom of the generated file in the "if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")" section.
I think this is a bug as those flags have to be set on [LINK_FLAGS](https://cmake.org/cmake/help/latest/prop_tgt/LINK_FLAGS.html).

Workaround
------------------
The following line in the conanfile.py 
``` python
self.cpp_info.sharedlinkflags = ["-NODEFAULTLIB:abc.lib", "-DEFAULTLIB:def.lib"]
```
gets changed to
link.exe ... somelib.lib "-NODEFAULTLIB:abc.lib" "-DEFAULTLIB:def.lib" kernel32.lib user32.lib ...

This does not look completely fine but it works for the VS compiler.

**Comment by memsharded** [comment]
Yes, this seems a bug. I understand that you are using the new "cmake_find_package" (https://docs.conan.io/en/latest/reference/generators/cmake_find_package.html) generator, not the regular "cmake" one. Have you tried it? Same result?

Though might be a cmake issue too. The thing with LINK_FLAGS is that it cannot be set to INTERFACE IMPORTED targets, which are the targets actually defined for the package. So it needs to be an INTERFACE_LINK_LIBRARIES properties, and could be more related to cmake. Need to investigate it, thanks very much for your feedback.

**Comment by Johnnyxy** [comment]
Yes, I was looking into the docs of CMake and didn't find something that just relates to interfaces. So my conclusion was LINK_FLAGS. But as LINK_FLAGS applies in generall to all calls of the linker it would be of course not quite the formal correct property.

But I think there will be a solution. Kitware integrated a new set of commands and interface properties into their codebase. Especially the new command "target_link_options" could be helpful.
Or if you prefer properties directly there is a new property "INTERFACE_LINK_OPTIONS".
Those are currently only available in "master" branch, but it looks like they will be available in CMake 3.13.0.

Have a look at the CMake commit here:
https://gitlab.kitware.com/cmake/cmake/merge_requests/2033/diffs?commit_id=46bc7205207e70a3783ec66244ca00a594bd98bd

docs:
https://cmake.org/cmake/help/git-master/command/target_link_options.html
https://cmake.org/cmake/help/git-master/prop_tgt/INTERFACE_LINK_OPTIONS.html

**Comment by memsharded** [comment]
> I think there will be a solution. Kitware integrated a new set of commands and interface properties into their codebase. Especially the new command "target_link_options" could be helpful.
Or if you prefer properties directly there is a new property "INTERFACE_LINK_OPTIONS".
Those are currently only available in "master" branch, but it looks like they will be available in CMake 3.13.0.

Yes, that is great. But we are trying to keep CMake backwards compatibility down to 2.8.12 for the global configuration approach, and down to 3.3 for the targets approach. There are thousands of users that are way behind the latest cmake releases. Using something in the generated conanbuildinfo.cmake that only works with latest CMake will be very problematic.

**Comment by Johnnyxy** [comment]
Understandable. It was just to throw in that there is already progress on CMake side for such use cases.

**Comment by memsharded** [comment]
Hi @Johnnyxy 

I am researching this. I am using this as base test code: https://github.com/memsharded/conan/blob/1a6a0f12190d83bc170a507c9874b2223117ad37/conans/test/integration/cmake_targets_test.py#L87

Conan generates for this case the following lines in *conanbuildinfo.cmake*:

```cmake
set(CONAN_SHARED_LINKER_FLAGS_HELLO "/NODEFAULTLIB:abc.lib /DEFAULTLIB:def.lib")
set(CONAN_SHARED_LINKER_FLAGS_HELLO_LIST "/NODEFAULTLIB:abc.lib;/DEFAULTLIB:def.lib")
```

No extra **.lib** is added there. The generated link line is (VS2017):

```bash
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\tmp_ixxlkconans\path with spaces\test_package\build\c64b80cf1a92be2fc664ab7cdb92f3b35989d8e5\bin\example.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib \NODEFAULTLIB:abc.lib \DEFAULTLIB:def.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"E:/tmp_ixxlkconans/path with spaces/test_package/build/c64b80cf1a92be2fc664ab7cd
```

Note that cmake has somehow converted the slash to backslash (``\NODEFAULTLIB:abc.lib \DEFAULTLIB:def.lib``), but no extra .lib is seen in this case. In any case, at this point it seems it is CMake which is doing the changes, so not sure what else could be done. I have checked using the ``-NODEFAULTLIB``, and it works, so far seems the only possible solution that is also backward compatible with cmake 2.8.12. Any other idea?

**Comment by memsharded** [comment]
Hi @Johnnyxy 

I have extended a bit the test I am using for checking this:
https://github.com/memsharded/conan/blob/dfb406d8c201a3f386381817cd394b8076a025cb/conans/test/integration/cmake_targets_test.py#L87

In this test I am replacing the default MD dynamic runtime library with the static MT one, and checking with the ``dumpbin`` the final linked libraries:

Using global cmake configuration (NO targets), the slash works:
```python
def package_info(self):
    self.cpp_info.exelinkflags = ["/NODEFAULTLIB:MSVCRT", "/DEFAULTLIB:LIBCMT"]
```
Using cmake targets configuration, the slash doesnt work, and it seems conan can't do anything there, because it is cmake messing with them. But the following works:
```python
def package_info(self):
    self.cpp_info.exelinkflags = ["-NODEFAULTLIB:MSVCRT", "-DEFAULTLIB:LIBCMT"]
```

This form is also good for cmake global configuration without targets, so attaching to using always ``-``, this should be good. So, would it be OK just explaining in the docs that this is the way to define these flags? 


Thanks again for all your feedback, very useful!

**Comment by Johnnyxy** [comment]
Hi @memsharded,
for me it will be ok of course. As I think that CMake is the source of the confusion and fiddles around with the strings.

I am driven by the _mantra_ "use it like the creator intended it". And as the official docs from the Microsoft Linker says that parameters should be given with a leading slash ("/") I tried to conform to that and noted the issue.

At the moment Conan can't fix this so an annotation for linker flags for Visual Studio for other users would be a helpful information.
Or even when someone just works with CMake alone and has such an issue he could _accidently_ find this hint by google, bing, duckduckgo, etc. :).



If all is being said the issue can be closed :).

**Comment by memsharded** [comment]
Added docs, closing the issue. Thanks again!
