### ISSUE TITLE
**How can copying from Conan cache to a local folder be speeded up**

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#3237]
**How can copying from Conan cashe to a local folder be speeded up**

I find Conan (well actually the OS) copying from Conan cashe to a local folder in `imports()` method very slow when it comes to copying many files.

- Can Conan do a diff between the cashed files and the existing files being copied to and only copy for the local files that are not the same? (Wonder if such a diff will not take longer than the actual copy).
- I think Conan copies that file with its exact timestamp from cashe to local location. I guess I can have a custom method checking for file existence and if so, if timestamps changed and only copy then.

Any other tips in this regards are appreciated.

**Comment by memsharded** [comment]
If this is an operation that you are doing often, that means it is not for final re-distribution, but rather for development? Have you had a look to "virtualenvs" (virtualrunenv, virtualenv, virtualbuildenv)? They might help using things directly from the cache, rather than copying them all the time to the user folder.

**Comment by Twoflower2** [comment]
Yes this is for active day-to-day development. 

I fail to see how https://docs.conan.io/en/latest/mastering/virtualenv.html?highlight=virtualenvs will help me. How would I use thing directly from cache using `virtualenvs`? Maybe we need an example.

**Comment by danimtb** [comment]
@Twoflower2 have a look at this section: https://docs.conan.io/en/latest/howtos/manage_shared_libraries/env_vars.html#using-shared-libraries-from-dependencies

Basically you can use those generators to create a virtual environment where shared libraries are set in variables injected to the environment so you can run your apps without having to import files to the executable folder. That'd be more convenient for continuous development.

**Comment by memsharded** [comment]
COnan 2.0 implement ``deployers`` that can be done by users, so it is very easy to do the desired copy, as fast as the user wants, not depending on Conan built-in import/deploy functionality. Closing this as solved in 2.0
