### ISSUE TITLE
Short paths and Qt

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#3241]
To help us debug your issue please explain:

- [x ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.5.2, Windows

With short paths enabled as they are with bincrafters Qt package, there is a file .conan_link. This link contains a short path such as "D:/.conan\qn8bu0ne\1". If one goes to that short path, you actually find the Qt package that was installed.

Applications such as QtCreator want access to that directory to be able to run locally. Now if you are only one person and have read the doc you can plug in the correct values and get creator to work.

However if you have 10 people and the value "D:/.conan\qn8bu0ne\1" is different on every machine then it is a bit of a nightmare.

So the questions are:
     1) Is this a static value per package
     2) If it is not static if I rename the dir to D:/.conan\QtCase1\1, and update the string in the .conan_link file to match am I ok, and is this an "approved" method.
     3) Do you have other suggestions?

**Comment by ArekPiekarz** [comment]
What do you mean by "QtCreator want access to that directory to be able to run locally"? I have used QtCreator with Conan and short paths without a problem. What are the steps to reproduce it?

**Comment by ArekPiekarz** [comment]
If you and your team are using Windows 10, you can enable its long path support and disable short paths in Conan. Also I was told on Conan's Slack that if during installation of Python 3.6 (or newer) you mark a checkbox for its long path support, Conan should detect it automatically and use it.

See these links:
https://docs.conan.io/en/latest/reference/env_vars.html?highlight=conan_user_home_short#conan-user-home-short
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by memsharded** [comment]
Conan 2.0 has finally removed all ``short_paths`` Windows workarounds, by making all paths short in all platforms (it was necessary to implement a multi-revision cache).

Closing this issue as solved.

**Comment by ShamanTcler** [comment]
Thanks...you guys are doing a great job.

I retired two years ago, but dabble in open source.. so thanks again

Regards
Carl
