### ISSUE TITLE
MSBuild() helper doesn't work right for some builds (DLL)

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3242]
Conan 1.5.2 and Conan 1.6.0

The following build helper method call fails on some of our builds due to 1500 missing symbols (Of note, only shared/DLL builds):

```
        msbuild.build(
            self._build_filename, 
            upgrade_project=False,
            targets=self._build_targets,
            build_type=carsim_build_type,
            platforms={"x86":"Win32"},
            use_env=False,
        )
```
Meanwhile, this works for DLL builds (even though it produces a nearly identical CLI call):

```
        vcvars_cmd = tools.vcvars_command(self.settings)

        build_cmd = msbuild.get_command(
            self._build_filename, 
            upgrade_project=False,
            targets=self._build_targets,
            build_type=carsim_build_type,
            platforms={"x86":"Win32"},
            use_env=False,
        )

        self.run(vcvars_cmd + " && " + build_cmd)
```
Here's the CLI call printed from the failing build: 
`set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC/Auxiliary/Build/vcvarsall.bat" amd64 && msbuild vssharedbuffer.sln /p:Configuration="Release DLL" /p:Platform="x64" /m:8 /p:ForceImportBeforeCppTargets="C:\Users\jwiltse\AppData\Local\Temp\tmpzuwro29htmp_conan\t"
`

CLI call printed from the working build:
`set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC/Auxiliary/Build/vcvarsall.bat" amd64 && msbuild vssharedbuffer.sln /p:Configuration="Release DLL" /p:Platform="x64" /m:8`

The two possible differences that could explain the behavior are: 
1. `/p:ForceImportBeforeCppTargets`
2. Conan could be applying environment variables from dependencies implicitly when using MSBuild() helper.  Since it's causing a linker failure for a DLL, it could be related to `PATH` or `LIBPATH`.

I don't think it's possible for me to debug whatever is passed via `/p:ForceImportBeforeCppTargets` because the path passed is always empty.

If the environment variables are the problem, I can't imagine exactly why the environment variables would cause these errors, but I can see it being a possibility.  It wouldn't surprise me if the assumption was that the environment variables would never hurt anything, or if they were applied incidentally and nobody even realized it was happening.  It's possible that in 99% of cases, it doesn't hurt anything, but there's something rare and particular in our projects which results in this issue. 

Fortunately, I can workaround the issue by creating the commands manually.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Minimonium** [comment]
@solvingj 
I'm not sure, but for me, it seems like this line here looks pretty suspicious.
https://github.com/conan-io/conan/blob/develop/conans/client/build/msbuild.py#L30

It *appends* to a path, which can make stuff tricky if some lib exists in the path already (as system one for example). Should prepend instead. Same goes for a visualstudio generator btw.
What do you think?

**Comment by solvingj** [comment]
Thanks for looking into this, you could easily be right.  PATH append vs prepend has had extensive discussion in the past in other areas of Conan, so changing that behavior will likely need further consideration.  Will be interested to see if Conan team can diagnose for sure and decide what to do.

**Comment by lasote** [comment]
We have to investigate this but will be very difficult without a failing example. Could you provide one?

**Comment by solvingj** [comment]
I'm not sure how or when I moved past this, but have not thought about it since my last comment and don't know of any outstanding issues related to it.  It very easily could have been a problem with a legacy project file misconfiguration, or the append/prepend issue.  I will close now, but reopen if I ever get back around to debugging this issue properly.
