### ISSUE TITLE
Question about Conan as a package deployment system vs a build depenancy system

### ISSUE THREAD

**Issue by dragon512** [conan-io/conan#3243]
Question

Is Conan a packaging system such as Nix ( from NixOs) or is it a build dependency manager?

From what I can tell it looks like the later. It does not seem to be targeted at making packages that should be consumed. Ideally, I would like to use this system to allow for creating packaging that I can then have our ops people use to install a set of application that has a conflicting set of sub-dependencies.  

For example, I might want to install application A and B so they can be called on the command line. A depends on component C v2.0 and openssl 1.0.2 and B depends on C and OpenSSL 1.1.0. From what I understand I should be able to make packages:
A-> C-2.0:openssl-1.0.2->openssl-1.0.2  ( three different packages)
B-> C-2.0:openssl-1.1.0->openssl-1.1.0   ( three different packages)

GIven this is built and pushed to my conan repo
I should then be able to go to a different box and run some conan command to have A and B install. ie something like:
conan install A/1.0.0@mystuff/stable
conan install B/1.0.0@mystuff/stable

After this, I am unclear how to run A and B. I think there is some step I am missing to allow  A or B to be usable as the "Active" versions of the A and B on the CLI

I think Conan has the potential to be a great way to manage packages on a production system.

Am I missing something? or do I have a misunderstanding of Conan is?

Thanks for any clarification

**Comment by danimtb** [comment]
Yes, you can achieve this use case with Conan too. To generate "deployable" packages, you can define a deploy() method that will copy the artifacts of the dependency graph that you indicate: https://docs.conan.io/en/latest/devtools/running_packages.html#deployable-packages

Also, you can run any tool installed using the virtualenv generator: https://docs.conan.io/en/latest/devtools/running_packages.html#using-virtual-environments

The whole documentation section may be useful for your use case. Please give it a read, ask any questions you have and we will be happy to help

**Comment by dragon512** [comment]
Ahh I see. I did not process the virtualrunenv correctly. I mistook it as a way to setup python virtualenv. My bad. The CLI could be cleaned up here. 

It would be easier if we had some sort of directory we could active applications in..  for example on Linux ( windows can do this as well.. but it would be different) allow the creation of a directory as a "root". This root would have the standard POSIX layout, so it could be used as a chroot, however, the easiest usage would be to have the $ROOT/bin in the path. With a command such as: 

connan activate path_to_reference

( or I guess a new generator give the current design) would symlink needed items into the $ROOT/bin and related directories. 

This might run patchelf to update the runpath of the .so and executables so they load correctly. ( I am unclear on how Conan is dealing with rpath/runpath locations on link time.) I believe this would make it easy for users to deploy conan application on their system. 

My concern with the current approach is that setting up environment variables with LD_LIBRARY_PATH will have issues with the case I provided above as there will be two different component "C.so" files in the path. The loader will pick the one that is first in the path. This will break one of the application. use of runpath on Linux will prevent this problem from happening.

Or 

one can make script for the executables that set a private environment when environment when loading. This way each application A or B get a private LD_LIBRARY_PATH and as such will load the correct C.so component.

I have found the pathelf option works better.

**Comment by memsharded** [comment]
Hi @dragon512 

Find here some related discussion: https://github.com/conan-io/conan/issues/2660#issuecomment-406557370, which states that patching binaries might be complex and problematic too. And I also think it is.

The thing is that patching files, or putting them in a common "system" folder (even if it is user folder), can also become very messy quickly. For example you might want to check an application that is built against two different versions of a library. Now, you can perfectly have 2 terminals, and in each one activate its own environment. Each one will use the right version of the library, and can run simultaneously.

For copying files from the local cache, and putting them somewhere else, there already exist the ``imports`` and ``deploy`` features. Both can be used to create such copy. Please have a look at those methods too.

**Comment by dragon512** [comment]
Well two notes..

1) do you copy or (soft/hard)link. It seems wasteful and slow given Conan already has a layout for all the binaries. ( My own tools heavily symlink or hard link to save space and to speed up the work)

2) I thought so at first.. but and doing this with Scons locally. I have found so far it is not bad. The main issue was understanding that RPATH is taking on a new meaning in Linux land. There is the RT_PATH and a DT_RUNPATH. The old way was to use RT_PATH. This has been deprecated in favor of RT_RUNPATH. The   main difference is that RT_PATH does not allow for LD_LIBRARY_PATH to override while RT_RUNPATH does. This causes confusion as most people don't know this change happened. Also most of the blogs are old and out of date now. The only tool also that works 100% correctly is the recent drops of patchelf. Of and the docs say you only have to DT_RUNPATH the program not the SO like we did with RT_PATH. This is incorrect. The loader will require the DT_RUNPATH is set on both .so and the programs. The point of noise is that CMake ( or more so auto tools) don't handle RPATH correctly for packaging. It makes an assumption that the build knows where the binaries will be installed. More often the dev is installing to a non-system location to test the code. For me, I have found that I have to patchelf on the binaries before I package the bits to clean up extra "build" locations and add the correct paths for the install. 

GIven we know what depends on what in conan and where it was installed. it seems to me to be "simple" to generate a list of location for the depends of a given binary and patch it to point to the correct place. 

The problem with the "two" terminal notion you point out is that both of these programs have to run in the same shell. For me, this is the whole point of having a package manager. GIven the current limitation, I do understand that this can be hacked via the script indirection I mentioned above. This case would allow A to load with a different environment than B.

**Comment by luiscarox** [comment]
@dragon512  
You are correct about `DT_RPATH` and `DT_RUNPATH` having different behaviour. And it does not only affect the search other regarding `LD_LIBRARY_PATH`, but also whether the linker looks in the rpath for secondary dependencies (dependencies not directly "needed" by the current executable) or not. 
The deprecation of `DT_RPATH` (recent linker versions will emit `DT_RUNPATH` instead), combined with the fact that the linker will discard shared libraries if they don't provide symbols that are not directly needed by the executable being linked, means that it's very likely to run into troubles at runtime when the linker attempts to locate dependencies.

However, I would not blame CMake for not handling RPATH correctly. CMake has two modes of generating shared libraries and executables: the build tree and the install tree. CMake will add the directories containing any linked libraries to the RPATH *in the build tree* if these are not part of the default system search path.  This obviously makes the binaries in the build tree not relocatable since they contain absolute paths that may only make sense in the build machine. But this is documented and expected behaviour. It ensures that when the developer runs the binaries, the same files that were used at link time are loaded. And I would be thankful to CMake for this: on Windows/Visual Studio, you'll get a nice "unable to find DLL" unless you copy all DLLs to the same folder, or run in a virtual env that adds all `bin` dirs to PATH.

However for the install tree, it is rather challenging. By default the rpath in the install tree will be empty, and the loader at runtime will try to use the default search path. Which means that it will either not find the libraries, or load non-conan provided ones.

**Comment by dragon512** [comment]
I don't want to blame Cmake.. This is a hard problem. There is a lot that can go wrong
 The way I was thinking this would be handled ( Given I understand Conan well enough) is that the depend would be handled with a run path such as $ORGIN/../lib:$ORGIN/../../../../../../../<dependent>/<version>/<repo>/stable/package/<GUID>/lib

Given the GUID I believe to be stable and generated as part of the build. This value would work on the box the developers did for the build, the CI used to automate the build and it would work for the deploy. I know this works as I am doing something like this now. 

This run path could be set by conan. This would solve a lot of issue with package deploys on clouds system ( with or without docker related tech)

This is different from windows as I love the system. It looks for DLL in the same directory as the exe which is easy to use to solve issues if you want to copy or make link for the DLLs. As I recall there was a <progame>.local or .manifest files that one can add to add local PATH lookups for DLLs my the program when it was loaded. I used it once to see it work.. but I agree it was easier t just copy stuff into the "bin" directory. The issue here is the Linux is different and thinking like a windows dev with Linux OPS people is a bad combo. 
Anyways I think Conan can do what I would like in a professional Cloud CDN with a small tweak, or maybe I have to wrapper stuff to get this to work. I would rather have a open system than try to make wrapper this all myself

**Comment by dragon512** [comment]
HI... been busy with other stuff. Now getting back to looking at conan.

I think part of my confusion is that Conan look more like a build manager, not a packaging system in the current form.  I believe is missing is the notion of a real deploy stage. Current there is a notion of 

1) copy some stuff on the system with no notion of the depends hash
2) setup a virtualenv to run something. 

I believe my concerns is that 1) is great for limited and directed cases.  Such as making a Mega build of an application as a big RPM. 2) is great for Development and debugging but not for OPS. 2) is also not so bad for system as Windows, but even in these cases it would be nice to have something more persitent.

In the current form, I see this as a great system to build large system to make a large self-contained RPM/DEB package with everything in it for an application. Given the nice integration with JFrog, it acts like a giant build cache and makes builds fast. However, I would love to be able to use the packages as a way to continuous deploy to a box, and you a conan.txt file as more as an expected state to be on the system as well as tell what is installed on the system. I think this is where Conan could really shine as it would be, in my view, a lot better than the classic packaging system ( YUM,DNF,APT) in the Linux ecosystem as I could install multiple versions of an application and if done correctly "active" which version is active and or have a well defined way to start any version of an installed app.

It looks like you might have some ideas on this already. I would happy to help test them in my work test environment. Mean time I am also looking at how I might add my own generator to so this idea.. something like a patchelf generator which would set the runpath value to the places conan installed everything.

**Comment by brianthelion** [comment]
@dragon512 Wondering if you've made any progress on this as I am also interested in building complete `chroot`-ready environments with `conan`.

So far, I am strongly convinced of one particular design choice: You don't want to use a generator or the `.deploy(...)` method. Both of these mechanisms require that you -- a consumer of packages from the greater ecosystem -- instrument artifacts that come from providers at large.

The better solution -- one that you can control entirely -- is a [hook](https://docs.conan.io/en/latest/reference/hooks.html#hooks-reference). I'm currently working on a hook-based method for populating a POSIX-compliant tree under some user-defined `${PREFIX}` at every package install. It's very rudimentary, but the approach is promising.

**Comment by dragon512** [comment]
Not yet. I was blindsided by some internal stuff that has been keeping me busy for the last few weeks. I hope to back to this soon.

I think my plan so far ( or till I know better) is to use something like patchelf to modify the runpath of the binaries, and links to /usr/local/bin... or some $prefix as you point out. So far I have been happy with custom builds I have made on a large set of .so and application based on the use of pathelf to change the runpath. Deploying these on system/docker container has been a "it just works" setup. However, I really hope that getting this with conan will make this scale and work even better. 

I think the hook link you provide will be of great value for me. I need to look this over in detail. Thank you very much for the tip.

I am curious on how you plan to deal with .so files in your posix tree. I have cases in which I have to have two version of some shared library installed. For example, one case the library was built with openssl 1.0.2 and the other 1.1.1b. for various reasons one application that is being used has not had resources to update to openssl 1.1.1b yet. This is what I liked about having the depends has on the path. it allows for both applications to be installed and run without setting up some more complex docker setups to allow them to exist and share data on a volume.

**Comment by brianthelion** [comment]
@dragon512 The "rudimentary" part of my solution is that I'm only going to allow one version of each library initially. If you (the user) want a different version, you'll need to create another venv and `conan install` it there.

**Comment by dragon512** [comment]
@brianthelion Thanks for your thoughts!

**Comment by brianthelion** [comment]
@dragon512 See https://github.com/conan-io/conan/issues/4847#issuecomment-480064737

**Comment by danimtb** [comment]
As @brianthelion posted above, we have now the deploy generator to export files from the Conan cache to the user space. Please give it a try and open a new issue with the feedback about the pointes discussed above.

Thanks!
