### ISSUE TITLE
Improve patch_config_paths to handle dependencies paths

### ISSUE THREAD

**Issue by theirix** [conan-io/conan#3247]
The function `patch_config_paths` helps to make a relative package rootpath.
It's usually needed to patch dependencies paths as well. They can be found in files like `FooTargets.cmake`, `FooTargets-release.cmake`.

PR with improvement is submitted as well.

Sample [bug](https://github.com/bincrafters/community/issues/367):
```
CMake Error in CMakeLists.txt:
  Imported target "leptonica" includes non-existent path
  "C:/Users/appveyor/.conan/data/giflib/5.1.4/bincrafters/stable/package/8cf01e2f50fcd6b63525e70584df0326550364e1/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Versions: Conan 1.5.0.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by theirix** [comment]
Of course, proposed functionality can be added to `patch_config_paths` directly rather be a distinct function.

**Comment by lasote** [comment]
I think it is better to improve the same `patch_config_paths`.

**Comment by theirix** [comment]
Ok, I'll add this to `patch_config_paths`. How do you think, should the proposed functionality be executed by default or enabled by a parameter?

**Comment by theirix** [comment]
Done. Going to write some docs...
