### ISSUE TITLE
Python 3.7 installation fails due to PyYAML 3.12

### ISSUE THREAD

**Issue by AngelloMaggio** [conan-io/conan#3249]
- [x] Conan version: 1.6
- [x] Python version: 3.7

- Issue:
Installation of Conan fails when using Python 3.7 fails due to a [bug with PyYAML](https://github.com/yaml/pyyaml/issues/126) 
- Reproduce:
- [x] Install Python 3.7 including pip3
- [x] pip3 install conan
- [x] Error out
`Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-7qbn6h01/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-obq_96in/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-7qbn6h01/PyYAML/`

- Solution
- [ ] Change dependency version to 3.13.

**Comment by ArekPiekarz** [comment]
The same problem is present on Msys2, where Python 3.7 is now the default version (I don't even know if it can be downgraded). I didn't post an issue about it earlier, because I don't have access to Windows to gather logs.

**Comment by zubairkhalid11** [comment]
pip install --ignore-installed PyYAML 

this worked once you have done that install the library afterwards.

**Comment by sankalp7654** [comment]
Thanks, @lasote Changing the version of PyYAML from 3.12 to 3.13 helped me!

**Comment by theuntoldcreator** [comment]
@lasote , Thanks for the issue (Changing of 3.12 to 3.13) helped me a lot😊
