### ISSUE TITLE
Conan as deployment tool

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3260]
To help us debug your issue please explain:

Hi!

I have a project here that I need to run some embedded stuff (armv7hf) and I'm using Conan to make my life easier of course. We use an in-house buildtool (like buildroot). If you remember, buildroot uses a bunch of scripts to download the source and build, like Conan.

Now the good part, I added Conan to solve my external dependencies, including internal projects and instead to download all sources and build them, I'm using `deploy` feature to install all binaries. That's amazing, because Conan is helping to save our time during all CI process.

Now the complicated part, I have executed the follow command:

    `conan install -r <remote> <package> -p <profile>`

The command runs okay and I am able to copy all artifacts generated by `deploy` method. However, `conan install` tries to solve all requirements, but my intention is **ONLY** get binaries from `deploy` method and skip **ALL** general process, as download the requirements.

Is there any chance to get this feature in Conan? I thought something like `conan install <package> --deploy`

Cheers!

Conan version: 1.6.0

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
> my intention is ONLY get binaries from deploy method and skip ALL general process, as download the requirements.

The deploy method allows to get files also from the dependencies, so you need to install the whole dependency tree. You could workaround it creating a "distribution" package that "build_requires" the dependency tree and packages the needed binaries.

**Comment by uilianries** [comment]
:thinking: it's not a bad idea I think.

I have used distribution packages as .dpkg and .rpm with Conan. I didn't think about the dependency tree, including deps_copy, so you are right, there is no way to run only deploy, because it depends of package directory.

I'll use your approach to solve my case. Thank's for the advice. :smile_cat:
