### ISSUE TITLE
[feature request] Conan security audit

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3263]
To help us debug your issue please explain:

Hi!

I have followed Rust lang, including Cargo to filter some good features that could absorbed by Conan. Few days ago I read about [cargo-audit](https://github.com/RustSec/cargo-audit) on Twitter.

The idea is alert about packages with security vulnerabilities e.g OpenSSL/[<1.0.1g]@conan/stable [heartbleed](http://heartbleed.com/). They keep a database with known security flaws in [Advisories.toml](https://github.com/RustSec/advisory-db/blob/master/Advisories.toml)

Conan could provide some similar feature to alert about security flaws related to packages on Conan center, for example. The database could be open where anyone is able to create a PR and include a new advisory. 

Conan version: 1.6.0

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
This will relate mostly to Bintray and a warning message could be included in the client based on properties tagged by XRay. Would be an interesting feature for the future.

**Comment by uilianries** [comment]
In cargo-audit case there is no scanning service over the package, but I think XRay could be an excellent tool for the future. The audit data base could receive both results from XRay and alerts from the user.

**Comment by Aalmann** [comment]
Currently there is no conan support in Xray. We are waiting for it too. My last information from JFrog is H1-2019.

@danimtb there is already conan-io/conan-extensions#5 for package properties. Would be nice to get it which could also be used for this feature here.

**Comment by czoido** [comment]
Hi @Aalmann,

Since version 3.21.2 Xray supports Conan packages. We have [just released a blogpost](https://blog.conan.io/2021/09/07/Conan-XRay-Integration.html) on how the basics of the integration works. I hope this is still useful for you.

**Comment by czoido** [comment]
I'm closing this one as this seems already addressed by the Xray integration.
