### ISSUE TITLE
Artifactory: No remote or virtual repository for conan

### ISSUE THREAD

**Issue by jokram** [conan-io/conan#3266]
## Introduction
I've read in an [Artifactory white paper](https://jfrog.com/whitepaper/replication-using-artifactory-to-manage-binaries-across-multi-site-topologies/) how to setup a muti-site writable environment:  
SINGLE VIRTUAL REPOSITORY CONSISTING OF ONE LOCAL AND MULTIPLE REMOTE REPOSITORIES (PULL REPLICATION)
![image](https://user-images.githubusercontent.com/24388492/43123752-6d6bcb12-8f25-11e8-82fd-b777d214591f.png)

## Problem
Now it seems that for conan this is not supported:
- Artifactory currently cannot create virtual repositories for conan: https://www.jfrog.com/jira/browse/RTFACT-14647
- Artifactory currently cannot create remote repositories for conan: https://www.jfrog.com/jira/browse/RTFACT-13675

=> How can we setup a multi-site development when using conan?
Even when having only one site writing, the Artifactory remote repositories for conan would still be necessary, or?

## Environment
- Artifactory Enterprise, 5.10.3 rev 51003900
- Conan version 1.4.4
- Client OS: Windows 10 64 bit

**Comment by jokram** [comment]
I have a workshop this week with my team and would like to know how to setup replication when using conan. Any updates on this?
For me missing replication/mirror support of binaries stored in conan packages could be a showstopper for conan.

**Comment by lasote** [comment]
Sorry, remotes and virtuals are not supported yet and will require some work, it is not planned for 2018. We have first to implement package revisions.

About replicating repositories you can do it with the regular replication mechanism.

**Comment by jokram** [comment]
So, if I'm looking at https://www.jfrog.com/confluence/display/RTF/Repository+Replication then it means with conan I can use only the push replication, but not the pull replication, because pull replication needs remote repositories. Am I right?

**Comment by lasote** [comment]
I'm not sure to be honest. @markgalpin please.

**Comment by markgalpin** [comment]
Missed this notification somehow.  @jokram is correct, currently only push replication works with conan repositories because they are local-only.  Remote and virtual repositories are coming, but they have no defined ETA (currently will be after package/recipe revisions)

**Comment by danimtb** [comment]
Conan virtual repositories are supported (and fixed) in Artifactory 6.17 as reported here https://github.com/conan-io/conan/issues/6186#issuecomment-574548394

I think we can safely close this issue. Thanks!

**Comment by jokram** [comment]
Yes, this issue can be closed. I can confirm that we've successfully tested remote and virtual repositories with conan in Artifactory.

**Comment by danimtb** [comment]
Thanks for the feedback!! 😄
