### ISSUE TITLE
Enhance graph dependency resolution speed

### ISSUE THREAD

**Issue by dkgs** [conan-io/conan#3268]
Hello,

I have a big dependency graph that is managed in our CI system. About a hundred packages are handled and depends on each other by using version range like `[^1.66.0]` to keep, according to semver, the last backward compatible package.

The fact is that as all packages requirements are expressed that way.
I observed that conan, for each package, make a query to resolve the range and that can take a lot of time.

Observed times are with conan <= 1.4 a `conan info . -bo ... -bo ... [...]` on the graph would take about fifteen minutes (depending on the number of `-bo` that are passed).
On conan 1.6, it is twice as before.

As a way to enhance the resolution, can conan create a cache so they are resolved only once and future calls to the same range will be answered quickly ?

**Comment by memsharded** [comment]
Hi @dkgs 

Thanks for the feedback. Yes, it might be an effect of how the graph is computed now, with build-requires being duplicated nodes (build-requires are private to the packages that require them, same as private). And we are aware that resolving ranges is slow, as it involves searching in the remote servers. We will try to have a look at this and see if the performance could be improved.

**Comment by memsharded** [comment]
I have proposed a cache of the search results done by the RangeResolver: https://github.com/conan-io/conan/pull/3363. This might not only return back to the old performance, but maybe even improve over it. It would be great if you could run from sources from my branch to validate. Thanks!

**Comment by dkgs** [comment]
Great !
Unfortunately, due to restrictions at work, I can't run conan from source, I'll wait on the release of the 1.7 to test it.
