### ISSUE TITLE
imports() and build_requires

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3273]
Hi,

I have a recipe A that **build_requires** recipe B. Recipe B **build_requires** recipe C. Recipe A defines an imports() method to pull in certain files before building.

In this situation, should the imports() method pull in files from the recipe C package (if they match what imports() is wanting)? They don't appear to be from what I am seeing.

If I change recipe B to **require** recipe C then the imports() of recipe A does pull in the files from recipe C.

**Comment by lasote** [comment]
I think it is correct. When "A" is being built "B" is already built, so the "C" `build_require` is not applied and you don't have it available from "A".

**Comment by keithrob91** [comment]
This is happening when B is not already built. In fact if A, B and C are not built and I do a (within A):
`conan create . user/channel -b missing`

C builds, then B, finally A, but A fails because imports() did not import the files from C.

As it happens, this is actually an error in my A recipe as it does directly depend on C and so should have a build_requires to C, and this does fix it.

However, from what you have said, if B were already built it sounds like imports() should not have imported from C, which I _think_ surprises me.

**Comment by lasote** [comment]
If `B` is not built, it should import artifacts from `C`, yes. 
But `A` shouldn't import anything from `C`, it doesn't matter if `B` or `C` are built or not, because a build require is like a private require but only for building.

**Comment by keithrob91** [comment]
Thank you for the clarification.
