### ISSUE TITLE
Can't update nor delete recipe and package from Bintray

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#3275]
https://travis-ci.org/inexorgame/ci-prebuilds/jobs/408222870#L5506

This behavior is reproducable both in CI and locally:
  * credentials are correct
  * login (conan user) works
  * as soon as doxygen should get uploaded: permission denied for user
  * I also get the same permission denied error for `conan remove doxygen/1.8.13@inexorgame/stable -r inexor --outdated` locally or trying to upload a new revision of the recipe locally
  * I can't rule out that this might happen also for other recipes of ours, but the majority seems to still work as it used to be, (i.e. with the same setup and credentials I can update other recipes still fine)
  * I wanted to delete the entire doxygen package and re-create it, but for some questionable reason Bintray doesn't allow this after 365 days; why?
  * both locally and in CI the workflows did work for doxygen just fine before

**Comment by danimtb** [comment]
Hi @Croydon,

Yes it seems Bintray is blocking your package after some time to prevent it is deleted/modified and causes some trouble.

Just to be clear, this is the package causing the issue: https://bintray.com/inexorgame/inexor-conan/doxygen%3Ainexorgame/1.8.13%3Astable

Will check with the Bintray team. Thanks!

**Comment by Croydon** [comment]
Yes, doxygen is the one which can neither be updated nor deleted. 

However, since we have quite a huge amount of packages, there might be follow ups I'm not aware of right now.

**Comment by danimtb** [comment]
Could you please try again? Issue shuld be solved for doxygen

**Comment by Croydon** [comment]
It works now again for seemingly all packages, thanks!

**Comment by Croydon** [comment]
From my understanding the published date got adjusted, so this is not a permanent solution, right?

**Comment by lasote** [comment]
You are right, but Bintray team has planned the fix.

**Comment by Croydon** [comment]
Since we hit the space limit I want to setup a cronjob which removes outdated packages from our repository. By doing so I just run into this issue again. The following packages can't be cleaned right now:

  * Boost/1.64.0@inexorgame/stable
  * ENet/1.3.13@inexorgame/stable
  * InexorGlueGen/0.6.0alpha@inexorgame/stable
  * Protobuf/3.1.0@inexorgame/stable
  * SDL2_image/2.0.1@lasote/stable
  * bzip2/1.0.6@lasote/stable
  * gRPC/1.1.0-dev@inexorgame/stable
  * gtest/1.8.0@lasote/stable
  * libjpeg-turbo/1.5.1@lasote/stable
  * libpng/1.6.21@lasote/stable

Obviously, these are all old/deprecated recipes, but deleting them (even if it would work) is kinda out of question as we don't want to break old builds. But removing outdated packages would still save space and is totally fine.

@lasote Is there any ETA for a general fix on Bintray?

**Comment by danimtb** [comment]
Same solution has been applied to the packages listed. Now you should have the ability to remove these versions. 

Bintray team is currently working on general fix but still don’t have estimation when it will be ready on production.
