### ISSUE TITLE
[workspaces] Issue with include directory for root dependencies

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3277]
conan 1.5.2

Hi, our CMakeLists.txt often contain something like:

```
# create .h from .h.in
configure_file (
  "${PROJECT_SOURCE_DIR}/h/${PROJECT_NAME}/${PROJECT_NAME}Config.h.in"
  "${PROJECT_BINARY_DIR}/h/${PROJECT_NAME}/${PROJECT_NAME}Config.h"
  )

# copy all header files from source to binary area
file(COPY ${PROJECT_SOURCE_DIR}/h/${PROJECT_NAME}/ DESTINATION ${PROJECT_BINARY_DIR}/h/${PROJECT_NAME})

# use the binary area for our includes
include_directories(${PROJECT_BINARY_DIR}/h)
```

This has been working fine until we tried to use workspaces. When package A builds, it works fine and the include directory is correct (the binary include directory), but when the root builds that requires A the include path for the root is the A source include directory and not the binary include directory that we need (i.e. the one containing the .h created from the .in.h):

The conanws.yml looks something like:

```
A:
    folder: A
    includedirs: h

B:
    folder: B
    includedirs: h

root: B
generator: cmake
name: foo
```

I'm assuming its because the includedirs for A is relative to the folder i.e. A/h, but in the source directory not the binary directory?

**Comment by memsharded** [comment]
Hi @keithrob91 

Finally we have managed to resume work on this. The "Editable" packages were released in Conan 1.12, which supersedes most of the functionality of the Workspaces.

We are basing the next iteration of Workspaces for next release 1.13 in these "Editable" packages. It seems your use case would need to add to the ``[includedirs]`` the build folder.

Have you checked the "Editable" packages already? Could you please have a look? thanks!

**Comment by keithrob91** [comment]
I hadn't notice this feature. I will definitely take a look.

**Comment by keithrob91** [comment]
The Editable package feature does indeed do what I want. Thank you.
