### ISSUE TITLE
Consider turning off template directories in Git for conan config install

### ISSUE THREAD

**Issue by datalogics-kam** [conan-io/conan#3282]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

This is with Conan 1.6.0 on Windows 10.

To see this in progress, have a Git installation set up with automatic ctags generation akin to what's described in [Effortless Ctags with Git](https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html).

When doing `conan config install` with a Git URL, I get error messages like this:

```
Traceback (most recent call last):
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\kam\\.conan\\tmp_config_install\\config\\.git\\hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\site-packages\conans\client\command.py", line 1230, in run
    method(args[0][1:])
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\site-packages\conans\client\command.py", line 379, in config
    return self._conan.config_install(args.item, verify_ssl, args.type)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\site-packages\conans\client\conan_api.py", line 79, in wrapper
    return f(*args, **kwargs)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\site-packages\conans\client\conan_api.py", line 510, in config_install
    return configuration_install(item, self._client_cache, self._user_io.out, verify_ssl, config_type)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\site-packages\conans\client\conf\config_installer.py", line 135, in configuration_install
    rmdir(tmp_folder)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\site-packages\conans\util\files.py", line 202, in rmdir
    shutil.rmtree(path, onerror=_change_permissions)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\kam\.virtualenvs\skel-hv6zqtfh\lib\site-packages\conans\util\files.py", line 197, in _change_permissions
    raise OSError("Cannot change permissions for {}! Exception info: {}".format(path, exc_info))
OSError: Cannot change permissions for C:\Users\kam\.conan\tmp_config_install\config\.git\hooks! Exception info: (<class 'OSError'>, OSError(41, 'The directory is not empty'), <traceback object at 0x0000016409078548>)

ERROR: Cannot change permissions for C:\Users\kam\.conan\tmp_config_install\config\.git\hooks! Exception info: (<class 'OSError'>, OSError(41, 'The directory is not empty'), <traceback object at 0x0000016409078548>)
```

The problem boils down to the way files are locked on Windows. It's not possible to delete open files. But the hook starts a background process which has the script files open, and the cleanup of the directory fails. Of course, a second later, the directory can be deleted as files are closed and unlocked.

I've since started reworking my Git template to not start background processes by default, and only run `ctags` in checkouts that I'm actually developing on. This fixes my problem with `conan config install`.

It may make sense, though, to add `-c init.templateDir=` to the `git` command line when working on temporary downloads. It's part of sanitizing the process against user configuration: In a hook, _anything_ can happen, and the errors are obscure and difficult to understand.

`conan config install` is mostly treating a Git repository as a sophisticated form of file archive, and probably doesn't want the user's hooks or other unusual setups from the template.

**Comment by memsharded** [comment]
Yes, I have also experienced different flavors of errors while trying to remove git repos in Windows. It also happens when creating packages that do a ``git clone`` in the ``source()`` method, and the package has to be rebuilt and the source fetched again, as the ``rmdir`` fails.

Your suggestion would be to add exactly that string ``-c init.templateDir=``, with an empty value, to the internal ``git clone`` inside ``conan config install``, did I understand correctly? Yes, I think this can be done, I don't see a use case where hooks would make sense here, and this should be a straightforward feature.

Maybe it is also a reasonable feature for the git SCM component @lasote

Many thanks for your detailed report!

**Comment by datalogics-kam** [comment]
> Your suggestion would be to add exactly that string -c init.templateDir=, with an empty value, to the internal git clone inside conan config install, did I understand correctly?

Yes, #3284 is precisely the idea. Thanks!

**Comment by memsharded** [comment]
Hi @datalogics-kam 

This broke conan for users with older git versions. We are removing this hardcoded argument, and introducing a generic ``args`` one, so users that want to pass their custom configuration to ``git clone`` can do it, we think it is the safer approach for everyone: https://github.com/conan-io/conan/pull/3431

**Comment by datalogics-kam** [comment]
Works for me.

The only thing one better would be to have a config for it in `conan.conf`, so it could be a per-user fixup. I can probably do something like that for our Python utilities that use the API.

Thanks for the fix!

**Comment by monsdar** [comment]
@memsharded We're having the same issues as reported. Looks like there's a manual fix to solve that - are there any docs on what to do to apply the fix? Do we need to reconfigure our local git installation or did I overlook something?

**Comment by monsdar** [comment]
@memsharded:
Full commandline would be `conan config install <path-to-repo> --args="-c init.templateDir="`. Did I get this right?

Works fine for me, but the error happens very rarely, so I can't be sure if this really helped or if it's just doing nothing.

**Comment by monsdar** [comment]
My approach above seemed not to work. Error happened again.
