### ISSUE TITLE
copy() method for exports_sources

### ISSUE THREAD

**Issue by SirLemyDanger** [conan-io/conan#3286]
I'd like to have a better way/more control over the exports_sources step. I have some (for historic reasons) complicated git repo structures where I would like to be able to specify exectly what to export and how the stucture in the exports-sources looks like afterwards.

A `copy` method for exporting sources like the one in `package()` would be awesome.

Cheers

**Comment by memsharded** [comment]
So what you would actually like is a ``export_source()`` method in the conan recipe, that implements a ``self.copy()`` between the current conanfile directory and the ``self.export_source_folder`` (not defined yet).

Is this what you would like? In that case, I would like to consolidate this request in the https://github.com/conan-io/conan/issues/2456 issue, and close this one. Thanks!

**Comment by SirLemyDanger** [comment]
exactly that!
