### ISSUE TITLE
why self.copy can't be used in source()?

### ISSUE THREAD

**Issue by zhongpan** [conan-io/conan#3288]
I need copy some files in source folder, How do i do that? It seems i can't use self.copy.

**Comment by zhongpan** [comment]
I know the attribute exports_sources, in my situation, i need copy some files in source() method which after export_sources and the src/dst all in source folder.

**Comment by lasote** [comment]
Sorry, from where to where?

**Comment by shelper** [comment]
@memsharded i think his question is why `self.copy()` function is available in function `pacakage()` of the conanfile object in `conanfile.py`, 
I have have the same doubt, when i put this `self.copy()` function in other member fuctions of the object, e.g., `build()`. i got error saying: 

> object has no attribute 'copy'

When i try to dig into conan's source code, i could not find where this `copy()` is defined.

just out of curiosity, how this `copy()` function is defined.

**Comment by jsteinhofff** [comment]
I just accidentally tipped into this issue by using self.copy() inside of the build() method. It kind off worked, but showed very strange behaviour.
The strangest thing first is, why it did not give the `object has not attribute copy` error in the first place. I printed self.copy to see what it was during build() method and got:
`<conans.client.importer._FileImporter object at 0x7f3670e10fd0>`
Which makes be believe that i am looking at a left over from the imports() method where indeed self.copy is used.

Not sure what the exact mechanism behind is, but i suspect that self.copy() gets introduced by some kind of monkey patching. Would be great if conan would cleanup after the indented scope of such monkey patching such that these accidental usage would be prevented.

P.S.:
Thanks for debugging help @sandeshhardikar!

**Comment by lasote** [comment]
> Not sure what the exact mechanism behind is, but i suspect that self.copy() gets introduced by some kind of monkey patching. Would be great if conan would cleanup after the indented scope of such monkey patching such that these accidental usage would be prevented.

That is right, we changed the `self.copy` to an "explicit/always the same" tool at [`conan.tools.files.copy`](https://docs.conan.io/en/2.0/reference/tools/files.html) for Conan 2.0. So it will be available at any point, you just need to know the origin folder and the destination one. We cannot change the Conan 1.X `self.copy` because it will be breaking many users. 
I'm closing this issue, if you have any comment or question you write and we will answer and re-open the issue if needed.

Thanks!
