### ISSUE TITLE
[workspaces] - visual studio generator needed

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3294]
In the documentation it says:
> So far, only the CMake super-project generator is implemented. A Visual Studio one is being under development, and seems feasible, but it is ongoing work, not yet available.

This is a +1 for visual studio support. 

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by AshleighAdams** [comment]
Has there been any updates regarding this?

**Comment by memsharded** [comment]
Hi @AshleighAdams 

Unfortunately no. We are now re-iterating the integrations with the build systems first, at the package level, decoupling the toolchain and the project layouts. There is still work to do there, and it is important to do it as some of the limitations that avoid progress in the workspaces are because of that. The good news is that this work is high priority, there is ongoing work already.

**Comment by AshleighAdams** [comment]
@solvingj Is there any explanation for why this was closed?

**Comment by solvingj** [comment]
Sure.  I'll share some of my perspectives here to illustrate why I feel this issue is effectively irrelevant/redundant. 

Workspaces are apparently stalled and have made no major progress toward supporting all build systems for two years. There are several reasons for this, despite an overwhelming amount of interest in the feature from users. 

- time, all possible paths forward with the current implementation details require a LOT of time, to the point where something about the concept needs to change for it to be "completable" and "maintainable".

- one such detail is that it's unreasonable to write and maintain a separate set of custom generators just for workspaces.  For it to be a supportable feature, the generator system would have to be refactored to support it natively (and/or the feature needs to be refactored to be more compatible with existing generators).  A major refactor of generator capability is being explored already for Conan 2.0.  Also, different implementations for the future of workspaces have been discussed.  The hope is that we'll figure out a pair of compatible changes on both features. 

- the `editable packages` feature was conceived after workspaces, and there was an effort to re-implement workspaces in terms of editable packages.  This incremental change was a good learning experience, and it makes thinking about generator support easier. However, this also highlighted the previously-mentioned possibility that the `layout files` concept COULD be implemented as a more core feature. If recipes provide `layout files` which declare the output directories of the build methods, then both the `package` and `package_info` methods could probably be taught to automatically handle these layouts properly for both the `in-cache` case and the `editable-package`/`workspace` case. 

- The existing implementation of workspaces is still was not ideal on the UX side.  There are actually a lot of assumptions, and therefor a lot of cases for which it is not reasonable to use (even in cmake-only environments). For example, the feature was primarily designed around monorepo scenarios, but the workflows and challenges around modular repo scenarios are so different, that the workspaces feature has very rough edges for these cases. 

Altogether, the Conan team recognizes that when `workspaces` are revisited, it needs to support all the build systems and generators natively.
