### ISSUE TITLE
Transitive requirenment is not overriding between build_requires and requires sections of conanfile.py

### ISSUE THREAD

**Issue by Ujifman** [conan-io/conan#3295]
There is a problem with overriding dependencies. Looks like a bug.
Let us have 3 projects `Lib1`, `Lib2` and `App`. 
`Lib2` requires `Lib1`
`App` requires both libs, but `Lib1` requirement is transitive and `Lib2` requirement is not transitive.

`Lib1 conanfile.py`:
```
from conans import ConanFile, CMake, tools
import os

class Lib1Conan(ConanFile):
    name = "Lib1"
    version = "1.0"
    
    def package_info(self):
        self.cpp_info.libs = ["Lib1"]
```
`Lib2 conanfile.py`:
```
from conans import ConanFile, CMake, tools
import os

class Lib2Conan(ConanFile):
    name = "Lib2"
    version = "1.0"
    
    requires="Lib1/1.0@someuser/stable"
        
    def package_info(self):
        self.cpp_info.libs = ["Lib2"]
```
`App conanfile.py`:
```
from conans import ConanFile, CMake, tools
import os

class AppConan(ConanFile):
    name = "App"
    version = "1.0"
    generators = "qmake"
    
    build_requires = "Lib2/1.0@someuser/stable"
    requires = "Lib1/1.0@someuser/test"
    
    def package_info(self):
        self.cpp_info.libs = ["App"]
```
Now if I do `conan install . -if some_foder` in App directory I get `conanbuildinfo.pri` with this:
```
...
CONAN_RESDIRS += 
CONAN_BUILDDIRS += "C:/Users/Igor/.conan/data/Lib2/1.0/someuser/stable/package/fe652b9f0a4d77e47ceab2b8a170403bf36c95a4/" \
    "C:/Users/Igor/.conan/data/Lib1/1.0/someuser/test/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" \
    "C:/Users/Igor/.conan/data/Lib1/1.0/someuser/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/"
CONAN_DEFINES += 
...
CONAN_LIB1_ROOT = "C:/Users/Igor/.conan/data/Lib1/1.0/someuser/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9"
...
```
But it should be only `Lib1/test` package as `Lib1/test` package should override `Lib1/stable` package.
And now if I change contents of `App conanfile.py` and move both packages to `requires` section or to `build_requires` section, the result `conanbuildinfo.pri` will contain only `Lib1/test` package and no `Lib1/stable`, so all dependencies from `Lib1` will be overriden.

New  `App conanfile.py`:
```
...
class AppConan(ConanFile):
...    
    build_requires = "Lib2/1.0@someuser/stable", "Lib1/[>=0.0.1]@someuser/test"
    #requires = "Lib1/1.0@someuser/test"
...
```

Conan 1.6.1
Windows 10 x64
Python 3.6.2

**Comment by xwarior** [comment]
Hi there. Having the same issue.
Build-requires is a something private isn't it?
Suppose I need a library for some extremely complex computation. However it **should not be visible** from outside the package (clients should not know what I'm doing inside)

Now **they** (build-requires) **are actually visible** from outside. And they are clashing with normal requirements as @Ujifman said.

**Comment by Ujifman** [comment]
Hi @memsharded 
Ok, I'll try to show my use case. 
1. So I have dynamic library let's name it `Lib1`. 
2. Then I have another dynamic library let's name it `Lib2`. Now `Lib2` uses something from `Lib1` in shared_export classes, so I put `Lib1` to requires section of `Lib2`.
3. Now I have `Lib3` which uses `Lib2` in private classes, so `Lib2` lies in build-requires of `Lib3`. And `Lib3` uses `Lib1` and exports some classes with functions from `Lib1` so I must put `Lib1` to requires for `Lib3`. That's what I tried to describe in examples. Now I'm building `Lib3`, and I want to use `Lib1` from testing channel. And when I execute conan install I have mixed packages in `conanbuildinfo.pri` I have both packages paths, and in the end `Lib3` uses not `testing` package of `Lib1` as I wanted, but `stable` package that now comes as transitive requirenment from `Lib2`.
I expected that anyway it should be only one path to package in conanbuildinfo.pri.

**Comment by memsharded** [comment]
Sorry this was not followed up back then.
A lot has changed since then.

``build_requires`` has been renamed to ``tool_requires`` and should be used exclusively for executable tools (cmake, ninja, protoc...)
Conan graph resolution improved a lot in Conan 2, to explicitly model shared/static/header/application package and correctly propagate/hide information among them (but always using ``requires``.

Closing this ticket as outdated, please create new tickets reporting against Conan 2.X
