### ISSUE TITLE
[question] Can not link against a lib included from Conan.

### ISSUE THREAD

**Issue by Trafo** [conan-io/conan#3299]
Hi,

i have a problem with conan dependencies and im stucked.

My Settings:
* used normale conan-cmake Generator.
* includes boost::file_system indirect via cpprestsdk (but it changes nothing if i include boost::file_system additionally directly)

If i using boost::file_system, the visual studio compiler shows this error: 'LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc141-mt-x64-1_66.lib''

I dont understand the issue, because it should link against the existing libboost_filesystem.lib. In cmake and in the visual studio solution i can find the link to 'libboost_filesystem.lib' but not to 'libboost_filesystem-vc141-mt-x64-1_66.lib'.  Where conan adds this extra parameters? (-vc141 should be the compiler version, mt should be multi, 1.66 the boost version). I have no idea where i can find the failure.

To help us debug your issue please explain:
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Trafo** [comment]
I solved this problem with adding add_definitions(-DBOOST_ALL_NO_LIB) to my cmake project. But can somebody awnser me why? Because i see that conanbuild.cmake already included this flag. Is that because of the indirection (boost::filesystem via cpprestsdk)? This flags denies automatic linking. Is that right that conan this not needs, because we are linking directly to the right lib?

**Comment by memsharded** [comment]
Hi @Trafo 

Thanks for your report. Could you please provide a full reproducible example? With the CMakeLists.txt you are using, and a small main() app, as well as the exact command you are running to get that error. That could help a lot to check what is happening. If it is a package issue, it could be reported to the package repository. Or maybe it is a conan issue, or just some misconfiguration. Thanks!

**Comment by memsharded** [comment]
Closing as inactive
