### ISSUE TITLE
Profile environment variables not applied when generators are ran

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#3303]
**Conan version**: 1.6.1, 1.4.4

Consider the following `conanfile.py`, containing a `ConanFile` and a generator:

```py
import os

from conans import ConanFile
from conans.model import Generator


class mygen(Generator):
    def __init__(self, conanfile):
        self.conanfile = conanfile
        super().__init__(conanfile)

    @property
    def filename(self):
        return "initial-cache.cmake"

    @property
    def content(self):
        self.conanfile.get_info()
        return "boop"

class MyCf(ConanFile):
    name = "Hello"
    version = "0.1"
    generators = "mygen"

    def get_info(self):
        assert "MY_ENV_VAR" in os.environ
```

And the following profile saved as `myprofile`:

```
[env]
MY_ENV_VAR=hello
```

Run

```
$ conan install . -pr myprofile
```

### Expected behavior

Conan installs the package without an error.

### Actual behavior

```
PROJECT: Installing /Users/tamas/tmp/env_var_repro/conanfile.py
Requirements
Packages

Cross-build from 'Macos:x86_64' to 'Linux:x86'
PROJECT: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/conans/model/ref.py", line 70, in loads
    name, version, user, channel = tokens
ValueError: not enough values to unpack (expected 4, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/conans/client/command.py", line 314, in install
    reference = ConanFileReference.loads(args.path_or_reference)
  File "/usr/local/lib/python3.6/site-packages/conans/model/ref.py", line 73, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference .
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/conans/client/generators/__init__.py", line 93, in write_generators
    content = generator.content
  File "/Users/tamas/tmp/env_var_repro/conanfile.py", line 18, in content
    self.conanfile.get_info()
  File "/Users/tamas/tmp/env_var_repro/conanfile.py", line 30, in get_info
    assert "MY_ENV_VAR" in os.environ
AssertionError

PROJECT: ERROR: Generator mygen(file:initial-cache.cmake) failed

ERROR:
```

### Workaround

Running

```
$ MY_ENV_VAR=hello conan install . -pr myprofile
```

will avoid the error.

I think the environment variables should be applied. Also, the error message could be a bit friendlier, it's quite hard to tell what's going wrong when the generator errors.

---

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi Tamas, I agree, the error is weird and probably the environ should be applied. I will open a PR, I think we should be ok but applying now the env could be breaking, but probably could be considered a bug.

**Comment by sztomi** [comment]
Yeah, it is probably breaking. I think this behavior could be introduced via a CMake-like policy without breaking existing users. Was there an issue opened discussing policies?

**Comment by lasote** [comment]
The PR is breaking some test of virtualenvs, I have to take a look.
I don't think there is an open issue for policies, if you have some ideas feel free to open it.

**Comment by lasote** [comment]
Doesn't look good, it would be pretty breaking. You could use `tools.environment_append(conanfile.env)` to get the environment from the conanfile.

**Comment by sztomi** [comment]
Right now we worked around this (we could gather the information meant for the environment variables by other means).

**Comment by sztomi** [comment]
Does this mean WONTFIX @lasote ?

**Comment by lasote** [comment]
I can assign it to 2.0, we cannot change it earlier because it is breaking. And as you can use `tools.environment_append(conanfile.env)` in the generator I considered it enough. I'm reopening it.

**Comment by sztomi** [comment]
That is actually an OK workaround, I just wanted to clear up the reason for closing. Don't prioritize this, imo.

**Comment by solvingj** [comment]
Just ran into this today.  +1 for fixing in 2.0.

**Comment by sztomi** [comment]
Running into this again and it's giving me a headache :( no easy workaround this time around.

**Comment by lasote** [comment]
What changed? Why it cannot be easily workaround?

**Comment by memsharded** [comment]
This has changed massively since then:

- Profiles now define ``[buildenv]`` and ``[runenv]``. 
- The environment is not updated in memory anymore, instead it generates script files that are loaded at every ``self.run()``

We were discussing some time ago if we wanted to have something in the profiles that just activated environment variables, globally (not within Conan, not per-recipe), and that seemed a non Conan use case. There are other mechanisms to manage environment globally, and Conan does not recommend anymore to use env-vars for defining behavior, but instead ``conf`` items.

If someone still considers there is a use case, please open a new ticket, discussing it considering the new ``buildenv`` and ``runenv`` approach. Thanks!
