### ISSUE TITLE
I am not able to install packages(Boost) on ubuntu 18.04 .

### ISSUE THREAD

**Issue by abhi-jha** [conan-io/conan#3304]
conanfile.txt:

```
[requires]
Poco/1.7.8p3@pocoproject/stable
Boost/1.67.0@lasote/stable

[generators]
cmake

[options]
Boost:shared=False
Poco:shared=False

```

Run command : conan install ..

Output : 

```
Boost/1.67.0@lasote/stable: Not found in local cache, looking in remotes...
Boost/1.67.0@lasote/stable: Trying with 'conan-center'...
ERROR: Failed requirement 'Boost/1.67.0@lasote/stable' from 'PROJECT'
ERROR: Unable to find 'Boost/1.67.0@lasote/stable' in remotes
```

Conan remote list : 

`conan-center: https://conan.bintray.com [Verify SSL: True]
`

What am I doing wrong?

**Comment by memsharded** [comment]
The boost package is not under the "lasote" user anymore. You can check
which packages are in Conan center with

conan search boost* -r=conan-center


Where did you get that reference? If from the docs, it is outdated and
should be fixed, please tell. Thanks!

**Comment by abhi-infrrd** [comment]
Its one of the official videos : https://youtu.be/qpOul18bXes?t=175

Repo file : https://github.com/drodri/clion_conan/blob/master/boost_poco_md5/conanfile.txt

I had to do :  

```
conan remote add conan-community https://api.bintray.com/conan/conan-community/conan

conan search Boost* -r=conan-community 
```
which gave me the correct package name :` Boost/1.64.0@conan/stable`

**Comment by ArekPiekarz** [comment]
You are mixing ways of linking targets.

You can either do:
```
(...)
conan_basic_setup()
(...)
target_link_libraries(demo ${CONAN_LIBS})
```

Or
```
cmake_minimum_required(VERSION 3.1.2)
(...)
conan_basic_setup(TARGETS)
(...)
target_link_libraries(demo CONAN_PKG::Poco CONAN_PKG::Boost)
```

(Note - I haven't tested if these exact targets compile, but you get the gist.)

You can also alternatively get rid of `include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)` and `conan_basic_setup` if you use a different generator, like `cmake_paths` or `cmake_find_package`. Then you would need to add `find_package(...)` and link to different target names.

Reference:
https://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html
https://docs.conan.io/en/latest/reference/generators/cmake.html#methods-available-in-conanbuildinfo-cmake
https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html

**Comment by ArekPiekarz** [comment]
Can you share the commands you are using for configuring and building? Also a sample main.cpp file would be helpful as well as Conan version and your Conan profile (in ~/.conan/profiles/default).

**Comment by abhi-jha** [comment]
commands : 

    build-libraries :    `conan install .. -s compiler=gcc -s compiler.version=7.3 -s compiler.libcxx=libstdc++11 --build=missing`
    compile and run : `cmake .. ; make`

    main.cpp : 

```
#include <Poco/MD5Engine.h>
#include <boost/regex.hpp>
#include <string>
#include <iostream>

using namespace Poco;
using namespace std;

int main(){
    MD5Engine md5;
    md5.update("Hello World");
    string md5string = DigestEngine::digestToHex(md5.digest());
    cout<< "MD5= " << md5string << "\n";
    int n = 5;
    while(n--) {
        md5.update("hola");
        cout << "MD5= " << DigestEngine::digestToHex(md5.digest()) << "\n";
    }
    string s = "correct@email.com", s2="bademail";
    boost::regex expr{"\\b[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}\\b"};
    cout << boolalpha << boost::regex_match(s, expr) << '\n';
    cout << boolalpha << boost::regex_match(s2, expr) << '\n';

}
```

Conan version :  `1.6.1`

~/.conan/profiles/default : 


```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

```

CMakeLists.txt :  

```
cmake_minimum_required(VERSION 2.8)
project(BoostPoco)

add_executable(BoostPoco demo.cpp)
find_package(Boost)
find_package(Poco)

include_directories($(Boost_INCLUDE_DIRS) $(Poco_INCLUDE_DIRS))
if(Boost_FOUND)
    target_link_libraries(BoostPoco $(Boost_LIBRARIES))
endif()

if(Poco_FOUND)
     target_link_libraries(BoostPoco $(Poco_LIBRARIES))
endif()
```

**Comment by abhi-infrrd** [comment]
Apparently it doesn't generate any file named conan_paths.cmake.

`Command : cmake .. -DCMAKE_TOOLCHAIN_FILE=./conan_paths.cmake`

ERROR : 

```
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:100 (message):
  Could not find toolchain file: ./conan_paths.cmake
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by abhi-jha** [comment]
Apparently it doesn't generate any file named conan_paths.cmake.

`Command : cmake .. -DCMAKE_TOOLCHAIN_FILE=./conan_paths.cmake`

ERROR : 

```
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:100 (message):
  Could not find toolchain file: ./conan_paths.cmake
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by ArekPiekarz** [comment]
If that's the only command you used, then it's working as expected. The file `conan_paths.cmake` is generated by `conan install .. --build missing`. If that still won't work, then someone else would need to look into it.

**Comment by ArekPiekarz** [comment]
There is Slack with #conan channel on https://cpplang.now.sh

**Comment by ArekPiekarz** [comment]
I can see the linker is looking for C++11 ABI in
`undefined reference to 'Poco::DigestEngine::digestToHex[abi:cxx11](...)'`

Your Conan profile contains:
`compiler.libcxx=libstdc++`
while my profile has:
`compiler.libcxx=libstdc++11`

Can you try changing that and repeat the steps?

**Comment by abhi-jha** [comment]
Thanks. That did work on the command line. However, I had to set the flag `-DCMAKE_TOOLCHAIN_FILE=./conan_paths.cmake` in clion for it to work. Is there any way to specify it in the CMakeLists.txt file so that there wouldn't be any need for extra arguments. I tried setting it before the `project()` command but it didn't take.

My Final files : 


 
CMakeLists.txt : 

```
cmake_minimum_required(VERSION 2.8)
project(BoostPoco)
add_executable(BoostPoco demo.cpp)
find_package(Boost 1.64.0 REQUIRED)
find_package(Poco 1.7.8 REQUIRED)
target_link_libraries(BoostPoco Poco::Poco Boost::Boost )
```

demo.cpp :

```
#include <Poco/MD5Engine.h>
#include <boost/regex.hpp>
#include <string>
#include <iostream>

using namespace Poco;
using namespace std;

int main(){
    MD5Engine md5;
    md5.update("Hello World");
    string md5string = DigestEngine::digestToHex(md5.digest());
    cout<< "MD5= " << md5string << "\n";
    int n = 5;
    while(n--) {
        md5.update("hola");
        cout << "MD5= " << DigestEngine::digestToHex(md5.digest()) << "\n";
    }
    string s = "correct@email.com", s2="bademail";
    boost::regex expr{"\\b[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}\\b"};
    cout << boolalpha << boost::regex_match(s, expr) << '\n';
    cout << boolalpha << boost::regex_match(s2, expr) << '\n';

}
 
```

Running `conan install .. --build missing` after setting `-DCMAKE_TOOLCHAIN_FILE=./conan_paths.cmake` in the compiler or on the command line for the first time makes it resolve everything. Would love to see how we can include this flag in the CMakeLists.txt thus eliminating any other configuration overhead.

**Comment by ArekPiekarz** [comment]
I succeeded by changing the start of your CMakeLists.txt to this:
```
cmake_minimum_required(VERSION 2.8)
set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_BINARY_DIR}/conan_paths.cmake)
project(BoostPoco)
```
and then running commands:
```
mkdir build && cd build
conan install .. --build missing
cmake ..
make
```

As before I locally commented out Boost related lines to save time on building, but they shouldn't change the outcome.

One negative aspect of adding the CMAKE_TOOLCHAIN_FILE to your CMakeLists.txt is now you tied your project to Conan. Previously your CMake script didn't care where the dependencies came from - they could be installed by Conan or by system package manager like apt. So you should ask yourself how flexible do you want to make your project for other developers.

Another thing to ask ourselves is why are we using `cmake_paths` generator, which purpose is to decouple CMake script from Conan, if we coupled it anyway by embedding path to the toolchain config. At this point a simpler approach would be to get rid of that generator and leave only `cmake_find_package` one. Like this:

CMakeLists.txt (notice the CMAKE_MODULE_PATH line):
```
cmake_minimum_required(VERSION 2.8)
project(BoostPoco)
set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
add_executable(BoostPoco demo.cpp)
find_package(Boost 1.64.0 REQUIRED)
find_package(Poco 1.7.8 REQUIRED)
target_link_libraries(BoostPoco Poco::Poco Boost::Boost )
```
conanfile.txt (notice the generators section):
```
[requires]
Poco/1.7.8p3@pocoproject/stable
Boost/1.64.0@conan/stable

[generators]
cmake_find_package

[options]
Boost:shared=False
Poco:shared=False
```
The commands are the same as at the beginning of my comment.
The details are explained in https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html

**Comment by abhi-jha** [comment]
I will stick with the previous method of passing the toolchain file as an argument. The latter approach of `set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
` necessitates that the FindPackage_name.cmake should be in my build folder which might not always be the case. 

Thanks for helping me patiently so far.
