### ISSUE TITLE
AutoTools PKG_CONFIG_PATH value should be a list

### ISSUE THREAD

**Issue by guyguy333** [conan-io/conan#3305]
Hi,

Currently, AutoTools is able to generate `PKG_CONFIG_PATH` automatically. However, the value set is not a list. See: https://github.com/conan-io/conan/blob/develop/conans/client/build/autotools_environment.py#L134 (L135 and L141)

As a consequence, every previous value(s) set or "append" to `PKG_CONFIG_PATH` in dependencies are destroyed by `environment_append`. As `PKG_CONFIG_PATH ` is supposed to be a list of paths, it should be a list. It should have the same behaviour as `PATH`. Validated locally: declare as a list in lines quoted before solves the issue. Thus, `environment_append` does not overwrite previous value(s).

**Comment by memsharded** [comment]
Hi @guyguy333 

It seems that the purpose of setting that value was setting only the paths for the conan generated package config, and the issue could arise when trying to use any other system packages which PKG_CONFIG_PATH is defined somewhere else. Could this be the case?  We'd need the feedback of @lasote, but yes, it looks like we need to have a look at this, thanks for reporting!

**Comment by guyguy333** [comment]
Hi @memsharded,

Thanks for looking this issue. I think the case you quoted makes sense. However, my use case is a bit different. Let's suppose A depends on B and A is looking for B through pkg-config. What I did in B is as simple as it. However, this value is removed by autotools then.

```python
def package_info(self):
        self.env_info.PKG_CONFIG_PATH.append(os.path.join(self.package_folder, "lib", "pkgconfig"))
```

pkg-config generator can't be used here because B generates multiple pkg-config files and this is not handled by Conan currently. (It should be treated in another issue I guess).

**Comment by memsharded** [comment]
> pkg-config generator can't be used here because B generates multiple pkg-config files and this is not handled by Conan currently. (It should be treated in another issue I guess).

I see, yes it seems that conan is not prepared to define a custom PKG_CONFIG_PATH, but it is somehow automatically managed/integrated with the pkg_config generator. No need to open another issue, I think it is very closely related to be followed in this one. Thanks for the feedback.

**Comment by guyguy333** [comment]
Thank you @lasote
