### ISSUE TITLE
[workspaces] Incorrect behavior of conan install command

### ISSUE THREAD

**Issue by jobdead** [conan-io/conan#3306]
Environment configuration:
OS: macOS
conan version: 1.6.1

Steps to reproduce:
1) Create folders/files structure:
```
testfolder
    conanws.yml
    dependencies
        conanfile.txt 
```
2) Change current directory to "dependencies"
3) Execute: `conan install . -if ./install -pr myprofile`

Actual result:
Message from conan:
"Using conanws.yml file from ./testfolder"
"Error: ./testfolder/tests/desktop/conanfile.py not found"

It seems that `conan install` tries to install "workspace.yml" file instead of "conanfile.txt"

Expected result:
All dependencies are installed into the "./install" folder according to "conanfile.txt" file.

P.S.
I do not understand why it tries to do something with "workspace.yml".
If I change"conanws.yml" extension for example to "conanws.yml_" it works as expect.

**Comment by memsharded** [comment]
Hi @jobdead 

Thanks for the info. Not fully clear to me, are you trying to use the conan workspace feature, or trying to run a normal install? If there is a ``conanws.yml`` file somewhere in the parent directories, up to the root folder, then, workspaces are used as defined in the file. Changing the filename makes conan ignore it, workspaces (still experimental) use the ``conanws.yml`` file name.

**Comment by jobdead** [comment]
I am trying to run a normal install from `dependencies` folder  but unfortunately `conan install` always tries to do search in a parent directory. Question is: why `conan install` tries to find "conanws.yml" file in the parent folder if I explicitly run `conan install` from folder where `conanfile.txt` located?

**Comment by memsharded** [comment]
This behavior will be removed in conan 1.13, in favor of a new `conan workspace install <wsfile>` that will be explicit. Ongoing work: #4481
