### ISSUE TITLE
Conan linter seems over-zealous about print()

### ISSUE THREAD

**Issue by bryceschober** [conan-io/conan#3309]
When I try adding a debug print to my `conanfile.py` like:
```python
        print('C++ standard setting: {}'.format(self.settings.cppstd))
```

I get a conan error and no output:
```bash
<recipe>: Exporting package recipe
Python 3 incompatibilities
    ERROR: Py3 incompatibility. Line 51: print statement used
```

... even though I'm obviously using `print()` as a function, not a raw statement.

I'm running on Ubuntu 14.04... not sure how i can tell exactly which version of python it's using, but I suspect 2.7.x:
```bash
$ conan --version
Conan version 1.6.1
$ python --version
Python 2.7.6
```

**Comment by memsharded** [comment]
Yes, this is mostly a python/pylint thing, not a conan one. You could:

- Add ``from __future__ import print_function`` in your recipe.
- Provide a ``.pylintrc`` with your custom pylint configuration (might be installed with ``conan config install``)
- Maybe the best would be to hide it, and use ``self.output.info()`` (or warn, error, etc), utility, which also highlights the name of the recipe producing the message in the appropiate color.

**Comment by bryceschober** [comment]
Ah, `self.output.info()` is what I was looking for but failed to find.

**Comment by memsharded** [comment]
No problem :)
Here is the link, just in case, for other readers: https://docs.conan.io/en/latest/reference/conanfile/other.html#output-and-running
