### ISSUE TITLE
Conan does not seem to propagate compiler.runtime=MT to cmake msvc project generator

### ISSUE THREAD

**Issue by DaniCybereason** [conan-io/conan#3312]
https://github.com/conan-io/conan/blob/d5197368d1bcf99241cad08c858f6a1471613471/conans/client/generators/cmake_common.py#L576

I'm afraid this line means if the original cmake didn't contain an /MT or /MD flag, it will not propagate the conan settings.compiler.runtime properly.

I see this behavior on a package I'm trying to build - it's original cmake contains no /M* flag and thus this line with replace doesn't insert the conan configuration.

Am I missing anything?

Suggested fix would be to add the runtime from conan even if no match was found...

**Comment by DaniCybereason** [comment]
I'm sorry, the problem might be worse than I thought.

I ran
`"conan create . myrepo/stable --settings compiler.runtime=MT"`

Even when I forced the CMakeLists.txt file to contain the following lines:
```
SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MDd")
SET(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} /MD")
SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MD")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} /MD")
```

the /MD in all of these lines was still not replaced.
The visual studio projects created still contained /MD even though I requested from conan --settings compiler.runtime=MT

Not sure how to investigate this further at this point..

I will for now lock my package with /MT in it's own cmake file, but for it to be configurable I assume this has to be fixed somehow.

This is on version 1.6.1 (latest at the time of this writing)

**Comment by DaniCybereason** [comment]
Tested with cmake that generates MSVC project, it seems conan does not cause the /MD flag or /MDd flag to be replaced at all. even when I forced it to be included.

**Comment by lasote** [comment]
This is weird, I think the `CMAKE_CXX_FLAGS_` variables should always have a value. Could you confirm that the conan_basic_setup is being called and put some prints in the `conanbuildinfo.cmake` at `conan_set_vs_runtime `to see the value of:

- `CONAN_LINK_RUNTIME`
- `CMAKE_CXX_FLAGS_RELEASE` 

If you could provide some example would be useful.

**Comment by DaniCybereason** [comment]
I'm sorry, should the conan_basic_setup be called in the original package cmake also? or just the user has to call it?

What I did was to compile an existing CMakeLists.txt project and just compile it using conan's cmake build tool. Should I add a conan_basic_setup(TARGETS) inside my package CMakeLists.txt?

I have added message() calls for those two variables and I never saw them being printed.. it indeed seems this code is not being called at all..

**Comment by DaniCybereason** [comment]
The simple question is - if I'm taking an existing open source library and want to compile it using conan, is it enough to add a conanfile.txt or do I have to also insert some things into it's CMakeLists.txt? I didn't find documentation regarding this..

**Comment by DaniCybereason** [comment]
Seems I missed lines I must add to my cmakelists in order to make conan affect the build (I assumed it inserts those things by itself once I use cmake object from conan that was configured in the python file..)..

Something like this?
```
INCLUDE(conanbuildinfo.cmake)
CONAN_BASIC_SETUP()
```

**Comment by DaniCybereason** [comment]
I think it's not supposed to be added in the package when I run "conan create . myrepo/stable".
And it looks like conan_basic_setup isn't being called...

**Comment by lasote** [comment]
Yes, you need to "patch" the original `CMakeLists.txt` and your project one, otherwise, Conan can't adjust the project. https://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html

**Comment by DaniCybereason** [comment]
Awesome, do I add this in the beginning or at the end of the cmakelists of the original project?

Does that mean a conan package can only compile using conan or does this somehow allow the regular compilation in some way?

**Comment by DaniCybereason** [comment]
OK adding at the end of the cmakelists seems to do the trick.
Thanks, sorry about the confusion, perhaps we could improve the documentation to specify compilation only works if package cmake imports conan (I somehow understood python manages the cmake anyways, so it can supply all required args directly to the commandlines of the commands being run..)

**Comment by memsharded** [comment]
Hi @DaniCybereason 

Even if python understood the CMake (which is impossible, given the complexity), CMake does not have a clear way to override from the command line certain things, if they are hardcoded in the CMakeLists.txt, so the only way to guarantee that is to modify such CMakeLists.txt.

There are plan to improve the integrations with build systems in the generator/build-helper combo, and the docs should reflect it and will be improved as well to clarify these issues. Thanks a lot for your feedback!
