### ISSUE TITLE
scm query

### ISSUE THREAD

**Issue by luckielordie** [conan-io/conan#3314]
Is there a reason the .git folder is excluded from the copy that occurs? Would it be possible to ensure that it isn't ignored?

I've got a tool I'm using in parts of my conanfile that requires being able to query the git repo. I think it would make sense for the .git folder to be included in the copy to make the export from source closer to what happens on a machine that pulls the recipe and tries to build a non-existant hash.

https://github.com/conan-io/conan/blob/94222228824c90f482cd56769667d1f5c42cca8e/conans/client/tools/scm.py#L99

Thanks!
Matt

**Comment by lasote** [comment]
Probably you are right.
