### ISSUE TITLE
Case sensitivity issues with Conan packages on Windows

### ISSUE THREAD

**Issue by Framnk** [conan-io/conan#3315]
Conan doesn't enforce any kind of case sensitivity on packages however this leads to issues on Windows if someone were to attempt to use a package with the same name but a different case due to the way Conan caches the packages in the directory structure on Windows.

For example, if a user were to depend both on a package named "Boost.System/1.64.0@bincrafters/stable" and attempt to use an internally sourced package "boost.system/1.65.0@internal/testing" (for example to test a new/unstable version) Conan would fail to properly handle both packages due to the case differences in the naming.

It doesn't seem quite right for package creators to have to attempt to match their package names up to other similar packages in other repositories for them to work properly...

**Comment by lasote** [comment]
You are right, we are aware of this issue and we try to limit when a user exports a package with a different case of an already existing package. But I'm not sure what more could we do without breaking everything at this point.

**Comment by Framnk** [comment]
Would it be possible to simply ignore case in the directory structure and have case somehow factor into the package id?  So two package with similar names/versions but different case would extract to the same cache folder under different package ids?

**Comment by lasote** [comment]
Well, the name is used now in the servers too, conan_server, Artifactory, and Bintray. And many users are using (internally in the companies) cased names.

I could think in some (opt-in) feature in the clients to deny the export of recipes based maybe in a regular expression, but for public packages and server technology, I don't think we can do something at this point. As the client config can be distributed with `conan config install` feature, you could somehow prevent internal packages with forbidden naming.

**Comment by Merx** [comment]
Hi, I have the same problem, that I use different package version, which only differ in the case-sensitivity on windows.

I tried to fix it by making the conan folder case-sensitive, but this was not supported and I still get the case-mismatch-error.

Here is how you can enable case sensitivity for windows with a powershell script:

```
#Requires -Version 4.0
#Requires -RunAsAdministrator

# Enable case sensitive feature
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

# Make conan folder case sensitive
fsutil.exe file setCaseSensitiveInfo "$env:userprofile\.conan\data" enable
```


I would suggest to add this to conan (if the windows version supports it) and get rid of this case-sensitive issue of conan once and for all, at least for the newer windows versions.

**Comment by lasote** [comment]
Thanks, we will take a look.
I also would recommend using a conan hook to check that all the references are lower case. A [pre-export hook](https://docs.conan.io/en/latest/reference/hooks.html) works nicely. Remember that you can distribute all the config, including the `hooks` using the [conan config install](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install) command.

**Comment by memsharded** [comment]
Conan 2.0 is always lowercase, and this has been forced in ConanCenter for years now.
