### ISSUE TITLE
Better information on mismatch in dependency tree

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#3316]
using conan v1.6.1
Consider following scenario:
Monday:
binary foo depends on potato and carrot  in both versions 1.0.0
carrot depends on potato in version 1.0.0
potato does not depends on anything.

All compiles fine.
Tuesday:
updating dependency in foo to potato 2.0.0

This leads to error like this:
```
Packages
    carrot/1.0.0@user/testing:1edc358bbd62390e309c027c1fcc23c7feea92d7 - Missing
    potato/2.0.0@user/testing:de9c231f84c85def9df09875e1785a1319fa8cb6 - Cache

potato/2.0.0@user/testing: Already installed!
carrot/1.0.0@user/testing: WARN: Can't find a 'carrot/1.0.0@user/testing' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++, compiler.version=4.8, os=Linux
- Options: 
- Package ID: ...

ERROR: Missing prebuilt package for 'carrot/1.0.0@user/testing'
Try to build it from sources with "--build carrot"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```
Nowhere it hints to user that it is simply the issue of the carrot depending on the potato 1.0.0. 
One has to dig deeper by for example conan info to compare all the flags and the dependencies to find the issue.

Maybe it would be possible for conan to compare the settings in the prebuilt ones, and get closest match, and inform why exactly that dependency cannot work?

**Comment by fulara** [comment]
My problem regarding the error message, is that nowhere it hints to the user that the mismatch against `carrot` is that the `carrot` depends on different `potato` than `foo` does. it prints Settings which are perfect match,  error message is:
```
WARN: Can't find a 'carrot/1.0.0@user/testing' package for the specified options and settings:
```
Whereas thats not true, options and settings match.

**Comment by danimtb** [comment]
Yes, that's right...

As Conan uses [semver mode for compatibility](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#versioning-schema), changes on the major version of the requirement (potato changes from **1**.0.0 to **2**.0.0) changes the carrot's package ID. As carrot does not exists with potato/2.0.0 doesn't exist this is the result.

This message could be improved for sure.

**Comment by memsharded** [comment]
Yes, I agree with @fulara, showing the requirements (maybe evaluated to what ``package_id()`` says) in the error message won't do any harm, and might help identifying the origin of the missing binary. I think this can be added.
