### ISSUE TITLE
Conan fails for osx_image > 9.1

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#3317]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.6.1

I'm not sure if this is a Conan issue or a Travis issue, so I'll report it both places: macOS/gcc-8 fails on osx_image > 9.1, but trusty/gcc is just fine.

https://travis-ci.org/acgetchell/causal-sets-explorer/builds/413328655 (success)

https://travis-ci.org/acgetchell/causal-sets-explorer/builds/413321484 (failure)

https://github.com/travis-ci/travis-ci/issues/9960

**Comment by acgetchell** [comment]
Thanks for the tip. There doesn't appear to be a Command Line Tools update for Xcode 9.4.1.

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/413713193#L474

I can't tell for sure, because right now there's a problem with bzip source that hides this error.

https://github.com/conan-community/conan-bzip2/issues/13

**Comment by memsharded** [comment]
Closing this as outdated/stale.
