### ISSUE TITLE
Docker: Cross-build from 'Linux:x86_64' to 'Linux:x86'

### ISSUE THREAD

**Issue by austriancoder** [conan-io/conan#3320]
I have an i386 based docker container which I let run on an amd64 host.

> docker run --rm -v $PWD:/build:z debian-buster-i386:latest bash -c 'conan create -s arch=x86 /build austriancoder/test --build'
HelloWorld/0.austriancoder/test: Exporting package recipe
Linter warnings
    WARN: Linter. Line 23: Found indentation with tabs instead of spaces
    WARN: Linter. Line 1: Unused tools imported from conans
HelloWorld/0.1@austriancoder/test export: Copied 3 '.sh' files: install.sh, postrm.sh, postinst.sh
HelloWorld/0.1@austriancoder/test export: Copied 2 files: .gitignore, .clang-format
HelloWorld/0.1@austriancoder/test export: Copied 1 '.service' file: cyclic.service
HelloWorld/0.1@austriancoder/test export: Copied 2 '.c' files: main.c, cyclic.c
HelloWorld/0.1@austriancoder/test export: Copied 1 '.version' file: project.version
HelloWorld/0.1@austriancoder/test export: Copied 1 '.deb' file: HelloWorld-0.1.0-Linux.deb
HelloWorld/0.1@austriancoder/test export: Copied 1 '.md' file: README.md
HelloWorld/0.1@austriancoder/test export: Copied 1 '.h' file: cyclic.h
HelloWorld/0.1@austriancoder/test export: Copied 1 '.py' file: conanfile.py
HelloWorld/0.1@austriancoder/test export: Copied 1 '.txt' file: CMakeLists.txt
HelloWorld/0.1@austriancoder/test export: Copied 1 '.ini' file: module.ini
HelloWorld/0.1@austriancoder/test export: Copied 1 '.cfg' file: CPPLINT.cfg
HelloWorld/0.1@austriancoder/test: A new conanfile.py version was exported
HelloWorld/0.1@austriancoder/test: Folder: /root/.conan/data/HelloWorld/0.1/austriancoder/test/export
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
Found gcc 8
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI, edit the default profile at:

    ~/.conan/profiles/default

adjusting 'compiler.libcxx=libstdc++11'

************************************************************************************

Default settings
        os=Linux
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=8
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***

HelloWorld/0.1@austriancoder/test: WARN: Forced build from source
HelloWorld/0.1@austriancoder/test: Installing package
Requirements
    HelloWorld/0.1@austriancoder/test from local cache - Cache
Packages
    HelloWorld/0.1@austriancoder/test:496879c8b4989ea0a448e12aea2f77eba94a3096 - Build

Cross-build from 'Linux:x86_64' to 'Linux:x86'

Conan uses platform.machine().lower() as basis for the platform detection which uses uname.

`docker run --rm debian-buster-i386:latest bash -c 'uname -a'
Linux 75067ec4030f 4.17.11-200.fc28.x86_64 #1 SMP Mon Jul 30 15:21:09 UTC 2018 x86_64 GNU/Linux
`
The results is that this cmake based project uses gcc with -m32.

**Comment by danimtb** [comment]
Hi @austriancoder,

So the issue is that it shows the `Cross-build from 'Linux:x86_64' to 'Linux:x86'` message?
Or is it that the compilation finally fails?

Sorry I think I dont fully get your issue 😸

**Comment by memsharded** [comment]
The cross-build model has completely changed since then. Closing this as inactive.
