### ISSUE TITLE
not linking against dependent package libraries

### ISSUE THREAD

**Issue by srgxor** [conan-io/conan#3323]
Hello,
I am currently building the AWS SDK for C++ as conan package. One requirement I put in is libcurl. So conan downloads the curl package and then starts building the AWS SDK. However, I realized, that the linker is not linking against the package curl library. Instead it links against the system installed one. 

What am I missing here? I thought linker paths etc. would be set automatically. I am using this package recipe for the SDK: https://github.com/kmaragon/conan-aws-sdk-cpp/blob/master/conanfile.py

Please I am grateful for any help or push into the right direction.

**Comment by danimtb** [comment]
Hi @srgxor,

Looking at the cmake files fot the AWS project, it seems final targets link with a variable called PROJECT_LIBS. I haven't look into the cmake structure too much but seems this could be some how equivalent to linking to CONAN_LIBS var in *cmakebuilldinfo.cmake*.

Other with you could do is use the [cmake generator targets](https://docs.conan.io/en/latest/reference/generators/cmake.html#targets-generated-by-conanbuildinfo-cmake) and map the conan generated ones to the right naming expected by the lib with cmake alias:

```
add_library(libname ALIAS CONAN_PKG::libname)
```

Anyway, the conanfile seems good and it just a matter of getting the CMake patched or something. So I guess you would have to dig deeper into it to get it working.

**Comment by danimtb** [comment]
Thanks @srgxor! Iam closing this for now as this is not a Conan issue but feel free to comment if you need more orientation or help 😄
