### ISSUE TITLE
[workspaces] Allow root-level attributes in conanws.yml

### ISSUE THREAD

**Issue by djinni-developer** [conan-io/conan#3325]
In conan 1.6.1, looking at workspace.py, generator, name, and root are popped from the parsed conanws.yml, and then everything else is treated like a package.  That means however that any root-level attributes added to conanws.yml will likely result in a parsing error: `There was an error parsing conanws.yml: 'str' object has no attribute 'get'` error. 

An alternative that would have avoided this would have been to have a packages attribute at the root level so that the workspace processor only operates on items that it cares about.

**Comment by memsharded** [comment]
Hi @djinni-developer 

We are resuming work on Workspaces, after some time and after the "Editable" feature has been finally released in conan 1.12 (btw, have you already checked it?)

Could you elaborate a bit further why would you be adding unexpected (or at least unused) fields to the workspace definition? That file will be used by conan only. What do you intend to do or what is your use case? Thanks!

**Comment by djinni-developer** [comment]
@memsharded, we were using the workspaces feature to provide additional tooling on top of Conan. In order to facilitate that, we had added new fields to conanws.yml. They make sense as root-level fields since they do not relate to a particular project, but rather to the workspace as a whole. However, the parser restriction means that we now include them in one of the projects which makes it seems like they are project attributes.

Regarding workspaces and editable features, no, I have not checked it yet, because at some point the experimental workspaces feature broke compatibility so that it could work with the editable feature, and this ended up breaking all the tooling we had built. We're stuck on 1.9.2, and since I was told that the features are still considered experimental, I'm not upgrading because I do not want to keep trying to catch up due to breakages. We'd rather wait it out, or just build our own "workspace" feature so that we don't have to deal with breakages.

**Comment by memsharded** [comment]
Hi!

As discussed in https://github.com/conan-io/conan/pull/4112#issuecomment-495176621, we think this approach would be problematic, at least until the workspaces are greatly stabilized. I am closing this at the moment, but please read that comment and tell if necessary. Thanks!
