### ISSUE TITLE
md5 signature failed

### ISSUE THREAD

**Issue by Georgly** [conan-io/conan#3326]
I have exception every time when I build project with my profile: "conan install .. --profile=../conan_profiles/arm_x86_profile --build=missing".  Building with default profile or without any profiles past successfully. I'v tried several times with different compiler (clang 3.8 and gcc 4.8) the results were the same, only difference was computed signature - I have new one after every build. 
Error message: "ERROR: bzip2/1.0.6@conan/stable: Error in source() method, line 34
tools.check_md5(zip_name, "00b516f4704d4a7cb50a1d97e6e8e15b") 
ConanException: md5 signature failed for 'bzip2-1.0.6.tar.gz' file. 
 Provided signature: 00b516f4704d4a7cb50a1d97e6e8e15b  
 Computed signature: 6b22c7fc37f15ab7826c7ea8ab059b31" 
Conan version 1.6.1
Host OS: centos-release-7-4.1708.el7.centos.x86_64, kernel version: 3.10.0-693.el7.x86_64.

**Comment by danimtb** [comment]
Hi @Georgly,

Thanks for your report.

This is not a Conan issue but an issue related to the bzip2 package. Would you mind opening this issue in [conan-community/community](https://github.com/conan-community/community/issues)?

That way it would be easier to track for us.
Thanks!

**Comment by danimtb** [comment]
Sorry. this is actually a duplicated of conan-community/conan-bzip2#13. Please follow conversation there.
Thanks again!
