### ISSUE TITLE
Packaging binaries with dependencies

### ISSUE THREAD

**Issue by WayeeWang** [conan-io/conan#3328]
Hello. I have a need to package a dynamic binary library (libA) with conan (i.e. without source to build it), which is dependent on another library (libB). I have libB managed by conan. How can I let libA know where to find libB?

To be more specific:
On Mac:
libA.dylib has the dependency "@rpath/libB.dylib". My test executable that uses libA would fail to load libB.dylib as it does not know where it resides.
On Windows:
Similar situation meaning the loader needs to locate libB.dll.

Thanks in advance.

**Comment by danimtb** [comment]
Hi @WayeeWang,

As your LibA is a prebuilt binary, you would have to package it with the correct settings it was generated and the dependency LibB. Conanfile would look something like:

*conanfile.py*
```
from conans import ConanFile

class LibA(ConanFile):
    name = "LibA"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"
    exports = "libA.dylib", "libA.dll"

   requires = "LibB/1.0.0@user/channel"

   def package(self):
       if self.settings.os == "Windows":
           self.copy("*.dll", dst="bin")
       elif self.settings.os == "Macos":
           self.copy("*.dylib", dst="bin")
```

As you can see there is no build step as you already have the artifacts created.

Regarding the management of shared libraries we have a how-to section about this topic in the documentation: https://docs.conan.io/en/latest/howtos/manage_shared_libraries.html

**Comment by WayeeWang** [comment]
Hi @danimtb , thanks for the response. This is exactly what I have done. 
As described in the OP, libA.dylib has  "@rpath/libB.dylib" in it's dependency list. Since "@rpath/libB.dylib" cannot be resolved properly, it can't be loaded.
So I'd like to know how to inject ".conan/path/to/libB.dylib" into libA.dylib, or some other ways?

**Comment by WayeeWang** [comment]
Sorry for the possible confusion. Yes I did have a look of the documentation about managing shared libraries. And I am aware that if I set the rpath of my final executable correctly, libB.dylib could be successfully found and loaded.

My question actually is, during packaging the binary library libA, is there a way to change "@rpath/libB.dylib" in the dependency list of libA.dylib (which was what shipped with libA.dylib), to something like ".conan/data/.../.../lib/libB.dylib"?

**Comment by danimtb** [comment]
I am sure there are ways to change it but you cannot hardcode a Conan path in the *libA.dylib* because that would change when the *libA.dylib* file is distributed to other machines.

I'd say that using `imports()` is the best way to make shared libs work with Conan.

**Comment by danimtb** [comment]
Use `DYLD_LIBRARY_PATH` an point it to the folder where libs are imported to. You can also use the virtualrunenv generator https://docs.conan.io/en/latest/howtos/manage_shared_libraries/env_vars.html#using-shared-libraries-from-dependencies

**Comment by memsharded** [comment]
Closing as inactive
