### ISSUE TITLE
[Cross building model] Cross compiling packages with build requirements

### ISSUE THREAD

**Issue by GeorgeScrivener** [conan-io/conan#3329]
I’ve had some issues when cross compiling a build requirement.

In my case I'm trying to cross compile a library (call it `PackageA`) that has a build requirement on `flatbuffers`.  `flatbuffers` creates an executable, `flatc`, that runs on the build machine and creates cpp files from some definitions.

I cross compile `PackageA` from amd64 for arm with `[env]` set in my profile:
```
[env]
CC={ARM C COMPILER}
CXX={ARM C++ CCOMPILER}
PATH=[{PATH TO COMPILER}]
```
The issue is that when conan builds flatbuffers it's using the `env` from the profile, and therefore `flatc` gets built for arm.  This means it won't run on the build machine which is amd64.

`PackageA` itself is a library and so can be added as a dependency from other packages.

I've mentioned this on the slack channel and got some good suggestions, but it doesn't seem like a solved issue.

When I first ran in to this issue I expected to find `compiler_build` & maybe `env_build` settings in the profile to match the `os_build` & `arch_build` cross compilation options, though I'm not sure whether adding these would create other issues.

What's the best way to solve this issue more generally?  We have quite a few build requirements that I'd like to use from conan.

**Comment by GeorgeScrivener** [comment]
Yes that looks to be pretty much the same issue I'm having.
It would be nice to be able to specify that toolchain packages don't apply to build requirements.

**Comment by lasote** [comment]
Currently the only way would be to create a separate package for `flatc` and require it as a `build_require`. This `flatc` package can be built first and then applied to the needed packages.

**Comment by GeorgeScrivener** [comment]
Using `build_require` doesn't actually work as expected because `CC` & `CXX` get applied to `build_require`s.
To get this to work, I'd have to create a toolchain to set the env variables.  But this would only work for `build_require`s in the root project, because any nested build requires will be built using the toolchain's env.

**Comment by lasote** [comment]
> Using build_require doesn't actually work as expected because CC & CXX get applied to build_requires.
Yes, because of that I suggested `This flatc package can be built first and then applied to the needed packages.` I meant to first, build the flatc in an isolated way, generating the needed variable with one profile. Then build your project with a different one.

**Comment by memsharded** [comment]
Cross-compilation model has massively changed since then, with the 2 profiles approach. Closing this ticket as outdated.
