### ISSUE TITLE
[feature request] Login on Conan server using tokens

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3331]
To help us debug your issue please explain:
Hi!

Sometimes I need to share my Conan password at my job to upload our packages. My password is hidden by the CI settings, but it could be revealed by anyone.

Some services, as Github and Gitlab provide private token, where is possible to give access level, as write and/or read, revocation and limited life time.

I think that such feature would be really great for some cases where is necessary to give user access on CI. Another example is Appveyor, where Bincrafters has a dummy user to share the password, but anyone is able to re-use it pass.

References: 
- https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html
- https://help.github.com/articles/authorizing-a-personal-access-token-for-use-with-a-saml-single-sign-on-organization/

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
As Conan is already using Bintray api token to authenticate, I think this is more related to the server side.
Artifactory already implements an [access tokens system](https://www.jfrog.com/confluence/display/RTF/Access+Tokens) but I am not sure if this is actually working with Conan. We should ask @markgalpin about this.

**Comment by lasote** [comment]
I think the generated tokens could be used as regular passwords in the client and it should work.

**Comment by memsharded** [comment]
Conan can use Artifactory tokens for auth, no need to use the  user password.
