### ISSUE TITLE
Python 2 deprecation feedback

### ISSUE THREAD

**Issue by markgalpin** [conan-io/conan#3334]
Comments section for the blog post found here: https://blog.conan.io/2018/08/13/Its-Time-To-Deprecate-Python-2.html

**Comment by danimtb** [comment]
What is this @markgalpin ?

**Comment by uilianries** [comment]
My opinion about python2:

https://pythonclock.org/

Even at my job I dont see any requirement to maintain python 2 as main version. We have worked with Conan there, and we are able to use python 3 as well.

Go ahead with python 3!

**Comment by tru** [comment]
We over at Plex is already on Python 3 - so we see no problems with this.

**Comment by claasd** [comment]
Please drop Python2.

**Comment by dkgs** [comment]
For users that are using the packaged installers and not running from source, will there be a difference ?

**Comment by szigetics** [comment]
Please drop Python2.

Go ahead with python 3! 👍

**Comment by nigels-com** [comment]
Python 3 is a moving target.  At least we know that Python 2 will be in future.

**Comment by memsharded** [comment]
Python 2 is deprecated already, and plan for removing it completely is in place: https://github.com/conan-io/tribe/pull/3

**Comment by jirayupiwon7** [comment]
android {
    // Use the following syntax to access properties you defined at the project level:
    // rootProject.ext.property_name
    compileSdkVersion rootProject.ext.compileSdkVersion
    ...
}
...
dependencies {
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    ...
}
