### ISSUE TITLE
The pattern in conan search and conan upload behave differently

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#3335]
What is the reason for this behaviour? Can this be unified to the behaviour of `conan search` (as it is simplier)?

`$ conan search -r inexor *inexorgame*`
-> `There are no packages matching the '*inexorgame*' pattern`

`$ conan upload -r inexor *inexorgame*`
`Are you sure you want to upload 'CEF/3.3239.1709.g093cae4@inexorgame/testing'? (yes/no): n`
`Are you sure you want to upload 'InexorGlueGen/0.6.1@inexorgame/stable'? (yes/no): n`
[....]

`$ conan search -r inexor */*@inexorgame/*`
`Existing package recipes:`
`Boost/1.64.0@inexorgame/stable`
`CEF/3.2704.1424.gc3f0a5b@inexorgame/stable`
`CEF/3.2704.1424.gc3f0a5b@inexorgame/testing`
`CEF/3.3239.1709.g093cae4@inexorgame/testing`
`ENet/1.3.13@inexorgame/stable`
[....]

To clarify: I'm expecting that the pattern `*inexorgame*` for `conan search` would return the same results as the results in the last example.

//cc @uilianries

**Comment by danimtb** [comment]
This issue seems to be on the server side as it working as expected with conan_server (both client and server share the searching code). So this is only related to artifactory and bintray.

**Comment by memsharded** [comment]
Fixed in Conan 2.0
