### ISSUE TITLE
how to name packages with same source code but different compiler ?

### ISSUE THREAD

**Issue by GarrickLin** [conan-io/conan#3336]
I didn't find it out that if I have to build the same source code with multiple compiler (cross platform) and what package name rule should I use. Is that reasonable to use `channel` part ? 
For example:
```
Project/1.0@demo/x86_64
Project/1.0@demo/armv7a
Project/1.0@demo/aarch64
```

**Comment by memsharded** [comment]
It is not necessary, the difference in architecture or compiler are handled
by the package binary ID. The reference is the same (channel can be
testing, stable, etc) and there will be a different binary for each
different settings/options combination. Doing a conan search <ref> you can
see those binaries.

Please check again the docs, and ask if not fully clear. Thanks!

**Comment by lasote** [comment]
Please, write again if you need further information!
