### ISSUE TITLE
Conan still not detecting gcc on MacOS

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#3342]
I'm not sure if this is a reversion from https://github.com/conan-io/conan/issues/2231, or if that was never fixed.

You can see with Conan 1.6.1 even though I've installed gcc-8 and specified with with a custom profile:

https://github.com/acgetchell/causal-sets-explorer/blob/feature/conan-cmake/.ci/gcc-macos

Conan is still complaining about the clang front end.

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/415760358#L689

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Could you run `gcc --version` in your travis mac job and paste here the output? I suspect it is finding the preinstalled gcc (frontal of llvm) instead of the installed by brew.
I installed it locally and if I set `CC=/usr/local/Cellar/gcc/8.2.0/bin/gcc-8` it works ok.

**Comment by acgetchell** [comment]
I solved this by setting `CXX=g++-8` and using `conan new profile default —detect` plus `conan install .. -pr default`.
