### ISSUE TITLE
[question] Is there a (IDE agnostic) way to use Conan to satisfy build dependencies in a development environment

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#3343]
(AS: sorry, adding a lot here lately, because a lot of enthusiasm for Conan! Please let me know if I should use a different channel for those suggestions/broad questions)

We are successfully using Conan in an automation context, to:

* Check the build status
* Produce artifacts (note: statically linked against its dependencies)

We feel there is a way to rely on Conan to satisfy dependencies on developers machines. Currently (without Conan), what we do when we want to work on a project is that we _deploy_ all dependencies inside a folder under the user home (getting them by compiling them, or OS package managers, or downloading prebuilt binaries). Then, we instruct CMake where to find the dependencies for the current build, and let it generate the project for the current environment (can be one of several IDEs)

A tedious part when starting work in a new environment is to _deploy_ the dependencies: finding the list, finding the preferred way to obtain each dependency, and follow the steps to obtain them.

Conan naturally adresses those issues: its recipes explicitly list all dependencies, enforcing their versions, and provide a unified way to obtain them (in a single command line).
Working on project `downstream`, here is how we could deploy:

      git clone downstream.git
      cd downstream
      conan install conan/conanfile.py -if build/ #note: we host the recipe in this subfolder

--- 

Now, a complication arises when the developer wants to run one of the executable targets defined in downstream as he usually does: directly from within his favorite IDE.
Conan _default_ behaviour seems to be to generate install names without `@rpath` in OSX (RPATH mechanism is not available on Windows anyway).

The [proposed approach](https://docs.conan.io/en/latest/howtos/manage_shared_libraries/rpaths.html#default-conan-approach) is to copy the files in the executable directories, with the helps of [`imports()`](https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports). It seems there are still a few drawbacks with this approach:
* The import mechanism seems to be non-recursive (thus, will not transitively copy the shared libraries on which the dependencies depend). So it becomes a no-solution for any non-trivial project.
* `downstream` project may contain many executable targets. Not all targets will require all libraries (inducing unnecessary copies). And more importantly, hardcoding the path to those many executable targets into the recipe seems to introduce a lot of unnecessary duplication between the CMake files (actually responsible for managing the targets in `downstream`) and the recipe (which should not care about those details). Also, the path to those targets directories is non-trivial and system dependent, due to the interaction between CMake and the IDEs (eg. IDE creating `Debug` and `Release` subfolders, etc...)
* Linux systems do not search the executable directory for dynamic libraries

What would seem ideal would be to use the `virtualrunenv` generated scripts to prepare the environment for runtime. This is works great for running from the terminal, sadly it does not seem that IDEs propose a "pre-run source script" step, and CMake made no provision for it either.

--- 

This seems like a vast question, and the documentation already discuss some approaches. Yet it feels like none are really offering the same level of _developer ease_ than for example the _standard_ `RPATH` mechanism on OSX that we are currently using on development environments.

**Comment by lasote** [comment]
Activating the virtual environment and then launching the IDE could be a possibility? I didn't try it but it should work.

**Comment by Adnn** [comment]
A simple and interesting suggestion, I will try to remember to report if it works!

**Comment by AbrilRBS** [comment]
Cleaning up old issues, closing as solved as we didn't hear back from you since then :)
