### ISSUE TITLE
Inconsistent 'source_folder' between conan source and conan build commands

### ISSUE THREAD

**Issue by sjcooke** [conan-io/conan#3347]
Conan version 1.6.1
Platform: Any

The recommended package development flow produces inconsistent default values for `self.source_folder` between the `source` and `build` steps when commands are invoked from a separate folder. As a result, the build fails to find the expected source.

The motivation is to keep the project directory clean by working in a subdirectory, without needing extra command-line arguments. e.g.:

```
# conanfile.py
from conans import ConanFile
class Project(ConanFile):
    def source(self):
        self.output.info("source_folder: " + self.source_folder)
    def build(self):
        self.output.info("source_folder: " + self.source_folder)
        self.output.info(" build_folder: " + self.build_folder)
```

```
$ ls
conanfile.py
$ mkdir work
$ cd work
$ conan source ..
...
PROJECT: source_folder: .../project/work
$ conan install ..
...
$ conan build ..
...
Project: source_folder: .../project
Project:  build_folder: .../project/work
```

The value of `source_folder` changes unexpectedly between the `source` and `build` steps. In the `source` step it references the work directory, as expected, but in the `build` step it references the project directory.

Specifying the relative source folder explicitly in the `build` step does produce the expected output:

```
$ conan build .. --source-folder=.
...
Project: source_folder: .../project/work
Project:  build_folder: .../project/work
```

It appears that only the **default** value for the `source_folder` in the `build` step is incorrect.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by sjcooke** [comment]
This appears to be related to #2174. So maybe the default value for the `source_folder` in the `source` command should be the conanfile folder, not the current directory, the same as it is for the `install`, `build`, `package` and `export-pkg` commands?

**Comment by sjcooke** [comment]
I agree that this makes sense for `conan build ..` - and similarly for `conan package ..` and `conan export-pkg ..`, which also default the `source-folder` to the one containing the _conanfile.py_.

But isn't it therefore unexpected that the `conan source ..` command doesn't default to the same `source-folder` location, so that it will install the source by default in the same location where the other commands will look for it? A typical out-of-source workflow with the existing default might be
```
$ ls
conanfile.py
$ mkdir build && cd build

$ conan source .. --source-folder=..
$ conan install ..
$ conan build ..
$ conan package ..

$ conan export-pkg .. Project/0.1@user/stable
```
with various iterations of `source`/`install`/`build`/`package` as _conanfile.py_ is refined. But having to specify the source location explicitly for `conan source ..` would be unnecessary if the default were the same.

The other common case of invoking `conan source .` from the folder containing the _conanfile.py_ would of course be unaffected by this change.

**Comment by memsharded** [comment]
I think maybe the thing is that creating and moving to the build folder is something done later (as it can be done several times for different built types). Maybe something like this would make sense to you?

```bash
conanfile.py
$ conan source . # The source is common to all builds
$ mkdir build && cd build
$ conan install ..
$ conan build ..
$ conan package .. # You can skip the conan package and run export-pkg directly too
$ conan export-pkg .. Project/0.1@user/stable
$ mkdir build_debug && cd build_debug
$ conan install .. -s build_type=Debug
$ conan build ..
...
```

**Comment by memsharded** [comment]
There is a whole new approach, using ``layout()`` method to define packages layouts, closing this as legacy and inactive.
