### ISSUE TITLE
conan qmake generator uses invalid characters in variable names

### ISSUE THREAD

**Issue by djeverett** [conan-io/conan#3351]
conan version: 1.6.1

Conan allows package names to contain hyphens.  If you do have a hyphen in your package name, then so will all the related variables in conanbuildinfo.pri, as generated by the qmake generator.  Hyphens are not valid in qmake variable names.  I suggest that the generator should change hyphens to underscores.

**Comment by memsharded** [comment]
Yes, totally makes sense, thanks for reporting it.

**Comment by memsharded** [comment]
Here is a fix: https://github.com/conan-io/conan/pull/3355/files
But in any case, you might try to avoid package names with hyphens and other characters, even if they are allowed in package names, they can bite you in other places (as it happened :) )  Please avoid them if possible.

**Comment by djeverett** [comment]
Thanks.  There are other characters that could cause problems (e.g. a dot), so these ought to be added to the fix.  However, as you say, the best strategy is to avoid any characters that are not allowed as variable names by your build system,

**Comment by memsharded** [comment]
Sure, added the management of dots too for qmake generator. It happens that CMake generator didn't need it, as it can handle hyphens and dots in variable names.
