### ISSUE TITLE
Unnecessary and deranging override message when using alias packages

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#3353]
In a situation with 3 packages CA, CB and CC where CB requires CA (via an alias) and CC requires CB and CA also via aliases, when installing CC with a "conan install ..." conan reports a version override while actually the alias is pointing to exaclty the version of the package that conan says overrides the alias:

CB/0.0.2@user/testing requirement CA/ALIAS@user/testing overriden by CC/0.0.3@user/testing to CA/0.0.1@user/testing

To help us debug your issue please `explain:`

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by fourbft** [comment]
This was observed with conan version 1.3.3 on Windows and on Linux.
I attach a tar file with an example that reproduces this behavior. Untar the file and in the directory execute 'create_all_packages.sh'. After that issue 'conan install CC/ALIAS@user/testing' or 'conan install CC/0.0.3@user/testing' and the above message will appear.

**Comment by fourbft** [comment]
Sorry, reopened ... wrong mouse click.

**Comment by lasote** [comment]
Could you check with Conan 1.6? Important changes have been introduced in the graph processing since 1.3.

Thanks

**Comment by fourbft** [comment]
Checked with conan 1.6.1: exact same behavior as 1.3.3.

**Comment by memsharded** [comment]
This needs to be looked into. The thing is that when that message is output, it might not have all the information in the graph.
