### ISSUE TITLE
AutoToolsBuildEnv needs to be more flexible with "host"

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#3354]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I found a couple problems with the `get_gnu_triplet()` method of `oss.py`:
```py
# Calculate the arch
machine = {"x86": "i686" if os != "Linux" else "x86",
           "x86_64": "x86_64",
           "armv6": "arm",
           "armv7": "arm",
           "armv7s": "arm",
           "armv7k": "arm",
           "armv7hf": "arm",
           "armv8": "aarch64"}.get(arch, None)
if machine is None:
    raise ConanException("Unknown '%s' machine, Conan doesn't know how to "
                         "translate it to the GNU triplet, please report at "
                         " https://github.com/conan-io/conan/issues" % arch)
```

First, the exception being raised is swallowed by `AutoBuildToolsBuildEnv._get_host_build_target_flags():

```
try:
    build = get_gnu_triplet(os_detected, arch_detected, self._compiler)
except ConanException:
    build = None
try:
    host = get_gnu_triplet(self._os, self._arch, self._compiler)
except ConanException:
    host = None
```

A warning would be great, instead of just silently building apps very badly.

Second, any way to make that a little more flexible instead of hardcoding architectures in there? I ran into this after adding `armv5te` to my `settings.yml` file and now I have two options: change all of my recipes (and fork open source recipes) to check for `arch==armv5te` and provide the `host` parameter explicitly or wait for this bug to get fixed. Neither solution is good at all.

Maybe a replacement could look something more like this:

```
# Calculate the arch
if 'x86' == arch:
    machine = "i686" if os != "Linux" else "x86"
elif arch == 'armv8':
    machine = 'aarch64'
elif arch.startswith('arm'):
    machine = 'arm'
else:
    machine = arch
```

This should work reasonably well so long as you stay on top of adding new ARM architectures in the future.

**Comment by lasote** [comment]
Your suggestion of the env var doesn't work. This `get_gnu_triplet` is used both for the `host`(targeting machine) and the `build` (current machine) so it can change if we are cross building, and the env var won't be valid anymore.
I'm opening a PR in some minutes adding more flexible detections as you suggested first.
