### ISSUE TITLE
Using Environment Variables in Profiles

### ISSUE THREAD

**Issue by arpitjindal** [conan-io/conan#3356]
Hello

I am using conan 1.6.1 in Linux. Is there any way to use the environment variables in Conan profile? I tried by $VARIABLE_NAME but its not taking its value. It is simply using $VARIABLE_NAME in string.

Thanks.

**Comment by lasote** [comment]
You can declare env vars but not take the values of env vars and evaluate the profile.

**Comment by arpitjindal** [comment]
It would be better to have this feature so that we could have some values from the environment variable (For eg. ToolChain paths) instead of hard-coding everything in the profiles.

**Comment by lasote** [comment]
Yes, it could be useful. Now you can declare variables and include other profile containing the hardcoded variables. https://docs.conan.io/en/latest/reference/profiles.html#variable-declaration
The good part doing it this way is that all the input is auto contained in profiles, that could be shared.

**Comment by arpitjindal** [comment]
Yes, I know that. Currently, I am having multiple-level-multiple-includes structure. I liked it. I am just blocked with this issue of unable to use environment variable in profile files.

Any idea when this feature would be available in Conan?

**Comment by lasote** [comment]
No, unfortunately, we have many many features pending, first, we have to evaluate it, then prioritize it...
It always helps if we receive a contribution.

**Comment by shelper** [comment]
it has been 2 years, just wonder if there is any updates?

**Comment by theodelrieu** [comment]
I would need this for build requirements like android NDK, or a minGW toolchain as well.

For example:

`Boost.Thread` needs 3 env vars to locate the posix threads includes and libs at build time, which cannot really be defined in my `mingw-toolchain` package (having `PTW32_LIB_NAME` in this recipe does not make much sense).

**Comment by memsharded** [comment]
We have merged #9147, that supports jinja2 templating for profiles. This allows not only to read env-vars, or platform configuration, but also to manipulate them, join, conditionals, fors, etc.

So I think this issue is closed by this (will be released next 1.38), please have a look at it and test it when released, feedback very welcome.
