### ISSUE TITLE
Conan Getting Started tutorial and C++ Standard Library ABI

### ISSUE THREAD

**Issue by leonardoce** [conan-io/conan#3370]
Hi all.

I'm a Conan beginner and I started using the "Getting Started"
tutorial on my laptop which is running (see [1]):

- Debian Testing (buster, x86_64);
- Gcc 8.2.0;
- LibStdc++ 8.2.0;
- Conan version 1.6.1 installed using Pip in a Python virtualenv.

After compiling a simple C++ program using Poco::Net and manually
building Poco since the repo has no binary for this configuration, I
obtainer the following linker errors:

```
/usr/bin/ld: CMakeFiles/chbench.dir/src/main.cpp.o:(.data.rel.ro._ZTVN4Poco3Net4Impl21IPv6SocketAddressImplE[_ZTVN4Poco3Net4Impl21IPv6SocketAddressImplE]+0x50): undefined reference to `Poco::Net::Impl::IPv6SocketAddressImpl::toString[abi:cxx11]() const'
/usr/bin/ld: CMakeFiles/chbench.dir/src/main.cpp.o:(.data.rel.ro._ZTVN4Poco3Net4Impl21IPv4SocketAddressImplE[_ZTVN4Poco3Net4Impl21IPv4SocketAddressImplE]+0x50): undefined reference to `Poco::Net::Impl::IPv4SocketAddressImpl::toString[abi:cxx11]() const'
/usr/bin/ld: CMakeFiles/chbench.dir/src/clickhouse.cpp.o: in function `ClickHouseClient::Execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
clickhouse.cpp:(.text+0x6c): undefined reference to `Poco::URI::setPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: clickhouse.cpp:(.text+0xd6): undefined reference to `Poco::URI::addQueryParameter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: clickhouse.cpp:(.text+0x139): undefined reference to `Poco::URI::toString[abi:cxx11]() const'
/usr/bin/ld: clickhouse.cpp:(.text+0x17d): undefined reference to `Poco::Net::HTTPRequest::HTTPRequest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/chbench.dir/src/clickhouse.cpp.o: in function `ClickHouseClient::ClickHouseClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, short)':
clickhouse.cpp:(.text+0x46d): undefined reference to `Poco::Net::HTTPClientSession::HTTPClientSession(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short)'
collect2: error: ld returned 1 exit status
```

After two hours and an headache, I discovered what was happening. When
Conan compiles Poco on my laptop, it uses
`-D_GLIBCXX_USE_CXX11_ABI=1`, which is correct indeed since Conan
generated this default profile for me the first time I launched it:

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

The profile contains `compiler.libcxx=libstdc++` and so Conan is
authorized to do that, and it will do it in the `conanbuildinfo.cmake` file
which is generated by `conan install`.

Nevertheless, if I simply invoke `conan install ..` and then `cmake ..`
as said in the tutorial, I'll always obtain linker errors since this definition
is not used.

The solution is to use `cmake .. -DCONAN_LIBCXX=libstdc++` and then
everything works correctly since the ABI of the standard C++ libraries
are now the same between my project and Poco. I forgot to say: this
definition is correctly used by the CMake helper.

I know that Conan is not a build system but only a package manager for
developers, and a really good one, but in my opinion this is a serious
usability issue.

If the documentation pointed out this "behavior" my debug session
wouldn't be needed.

What do you think of that? Anyway, thanks for this project!

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

[1]: https://docs.conan.io/en/latest/getting_started.html

**Comment by lasote** [comment]
Hi! Thanks for reporting, you are totally right. I'll open an issue to the docs repository to improve it. 

I think the library standard ABI is not the only thing that could fail if you change some defaults (but it is true that the standard ABI is a special case because you don't need to change anything from the defaults with a modern compiler)

There is an underlying issue with the build helpers/generators. When you invoke directly `cmake` without running the conan `build()` method (when you have a consumer `conanfile.py` recipe, that is not the case with the getting started guide), the `CMake()` build helper is not executed and all the variables adjusted by the build helpers like `CONAN_LIBCXX` are not passed. We are trying to figure out what is the best way to improve it, but probably the build helper should generate another file like the `conanbuildinfo.cmake` containing all the definitions, but it raises other problems we are discussing.

**Comment by leonardoce** [comment]
Ok. Since we have the documentation issue https://github.com/conan-io/docs/issues/767 I'm closing this ticket.

Thanks again.
