### ISSUE TITLE
In conanfile.py:package_info() self.settings.os is Macos on a Linux machine

### ISSUE THREAD

**Issue by cpbotha** [conan-io/conan#338]
In a conanfile.py, I have code that needs to react differently between Macos and Linux. However, on this Linux machine `self.settings.os` reports `Macos` inside of `package_info()`. I tested this with conan 0.9.4 from PyPI but also with current github master. Have a look:

```
conan-sfml-test$ uname -a
Linux meepz97 3.16.0-73-generic #95~14.04.1-Ubuntu SMP Thu Jun 9 08:00:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
cpbotha@meepz97:~/Dropbox/work/code/sandbox/conan/conan-sfml-test$ conan install -s compiler=gcc -s compiler.version=5.3 -s compiler.libcxx=libstdc++ --build=missing
Requirements
    sfml/2.3.2@cpbotha/stable from local
Packages
    sfml/2.3.2@cpbotha/stable:82c1f346a2049b61d5527ecde3306835df656fe2

> /home/cpbotha/.conan/data/sfml/2.3.2/cpbotha/stable/export/conanfile.py(62)package_info()
-> so = '.so.' if self.settings.os == "Linux" else '.'
(Pdb) print self.settings.os
Macos
```

(I put a breakpoint right at the start of `package_info()` to see why it was generating the incorrect .so filenames on Linux.)

**Comment by cpbotha** [comment]
On that same machine, it seems to think the package I just built is also Macos:

```
$ conan search -v
Existing packages info:

sfml/2.3.2@cpbotha/stable
    Package_ID: b6c08d3a7d8459c6f8ee89956eafe32d4d6cfe77
            (x86_64, Release, gcc, libstdc++, 6.1, Macos)
```

What am I doing wrong?

(this is the package https://github.com/cpbotha/conan-sfml )

**Comment by lbakman** [comment]
Just curious,

What does your .conan/conan.conf say about os?

Regards Lau

**Comment by cpbotha** [comment]
This is the relevant section of my conan.conf:

```
[settings_defaults]                                                             
arch=x86_64                                                                     
build_type=Release                                                              
compiler=gcc                                                                    
compiler.libcxx=libstdc++                                                       
compiler.version=4.8                                                            
os=Linux
```

**Comment by lbakman** [comment]
ok.

I have had a similar issue but I had put incorrect info in my conan.conf file...

**Comment by lasote** [comment]
Wow, very strange. Can you remove conaninfo.txt file and try again? Conan install command caches settings and options, maybe you have commited to a repo the **conaninfo.txt** file from a Mac?

**Comment by cpbotha** [comment]
Thank you @lasote - you were right, the conaninfo.txt is from the mac I was working on in parallel.

This is something that could easily happen to other people. Does it not make sense to warn the user if `settings.os != platform.system()` during package building? Or is there some other desired behaviour when the os in conaninfo.txt differs from the os of the machine building new packages?

**Comment by lasote** [comment]
@cpbotha It's complicated, maybe we should check it, but I think it could interfere with cross compilations. For example, I'm compiling some Android library in my debian, with conan. What should the settings.os be? Linux? or Android? I think Android, because the generated packages are for Android, so the check will fail.

**Comment by cpbotha** [comment]
@lasote Hence my suggestion of only warning the user. Something to the effect of:

"You are building this package with settings.os = Macos on a Linux build system. If this is your intention, you can ignore this message. If not, check your conaninfo.txt."

**Comment by lasote** [comment]
Please, check it with conan 0.10 and reopen the issue if it fails.
