### ISSUE TITLE
[question] Cross compilation multiple archs

### ISSUE THREAD

**Issue by rodolfo-picoreti** [conan-io/conan#3392]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi, I am trying to use the bincrafters protobuf library in a cross compilation scenario using the lasote/conangcc7-armv7 image. For that, I need the protobuf compiler in the host arch (x86) and the library itself in the target arch (armv7/v6). Can something like this be achieve using conan? I though about separating the protobuf and protoc in two differents packages. Then require the x86 protoc package as a build requirement and the arm protobuf package as a dependency. I am in the right track here? If so, how can I do what I suggested? That is, require a package with different arch than the target arch.

**Comment by danimtb** [comment]
Hi @rodolfo-picoreti,

Yes, you are in the right track. The best approach would be to separate protoc from the library itslef and use it as build require in the host machine to generate the library for the target one.

Have a look at the documentation and its examples on how to use Conan crossbuilding features for both normal packages an build requires: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html

Thanks!

**Comment by memsharded** [comment]
I would strongly recommend to create the *protoc* package without a transitive dependency to *protobuf* library, and link it statically (as the official release does), to avoid conflicts with the *protobuf* library to be used with the application being cross built.

**Comment by rodolfo-picoreti** [comment]
Thanks for the feedback @danimtb, @memsharded. I've divided the package in two: one statically linked protoc package and the protobuf library itself. Now I am trying to write the test for the protobuf package. The test should depend on the protoc package (host, x86) to compile some .proto file, but I don't know exactly how to specify this build requirement. At the moment I am just using: 
`build_requires = "protoc/3.6.1@picoreti/test"`
But it is using the package with the target (arm) arch. How can I specify it to use the package with the same arch as the host system?

I've read the docs on cross building, but I am not sure if what I want to do is documented there. As I understood the docker image is already configured with the correct profile/env variables.
