### ISSUE TITLE
[Mac] Consuming custom Apple framework with CMake

### ISSUE THREAD

**Issue by WayeeWang** [conan-io/conan#3394]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

[Conan version] 1.6.0
[System] Mac OSX 10.13.5
[Problem]
======= ISSUE 1=======
We are packaging our library as Apple Framework, with CMake generator. According to [this documentation](https://docs.conan.io/en/latest/howtos/link_apple_framework.html), "cpp_info.exelinkflags" and "cpp_info.sharedlinkflags" need to be specified as:
> self.cpp_info.exelinkflags.append("-framework XXX")
> self.cpp_info.sharedlinkflags = self.cpp_info.exelinkflags

However, this is not sufficient to make the packaged framework linkable, an error like:
> ld: framework not found XXX

would be reported by the consumer, since the linker does not know where to find this framework as it's not residing in one of the default system directories.

This can be also verified by checking the generated "conanbuildinfo.cmake", in which the `INTERFACE_LINK_LIBRARIES` property of the `CONAN_PKG::XXX` does not specify the framework search path. 

To solve this, when generating "conanbuildinfo.cmake", the `-F path/to/the/framework` should be added to `CONAN_SHARED_LINKER_FLAGS_XXX`, `CONAN_EXE_LINKER_FLAGS_XXX`, `CONAN_SHARED_LINKER_FLAGS_XXX_LIST` and `CONAN_EXE_LINKER_FLAGS_XXX_LIST` variables.

At the moment we have a workaround to append this information in the `package_info` function as:
> self.cpp_info.exelinkflags.append("-F path/to/the/framework -framework XXX")
> self.cpp_info.sharedlinkflags = self.cpp_info.exelinkflags

I'm not sure if this is the best way to do, considering [another similar issue reported for the XCode generator](https://github.com/conan-io/conan/issues/3161). To be consistent, similar things should be done for the CMake generator.

======= ISSUE 2=======
In order to find the header files inside the framework, this line should be added in the `package_info()` function:
> self.cpp_info.includedirs = ['XXX.framework/Headers']

This is also not stated in the [documentation](https://docs.conan.io/en/latest/howtos/link_apple_framework.html). In fact, IMHO, the directory containing the framework headers should be defaulted by the generators.

======= SUMMARY=======
Could you please confirm the plan to fix these two issues? And at least update this [documentation](https://github.com/conan-io/conan/issues/3161) as it is unfortunately misleading.

**Comment by lasote** [comment]
About ISSUE 1. We have to investigate the best way to let CMake know about the framework paths, probably there is some special var for it, and sure, to be consistent with the XCode issue #3161, it the variable exists, it should be adjusted automatically.

About ISSUE 2: That's true, please open an issue or even a Pull request to the documentation repository.

About SUMMARY: I'm assigning this issue to take a look for 1.8.

**Comment by lasote** [comment]
The variable we are looking for should be `CMAKE_FRAMEWORK_PATH`.
I'll try it and if it works it will be automatically adjusted to the package root folders.

**Comment by lasote** [comment]
It is not working. That variable only works in case the consumer use `find_package` to locate the framework, so I'm not sure if we can improve anything here but the docs to add the `-F` and the `includedirs`

**Comment by Paultergeist** [comment]
> self.cpp_info.includedirs = ['XXX.framework/Headers']

This will add `-IXXX.framework/Headers` to the compiler flags, won't it? I don't think this is the proper way to do it. `-F<path_to_XXX.framework_not_including_XXX.framework_itself>` should be added to compiler flags instead.

**Comment by Paultergeist** [comment]
@lasote Imagine you have `Frameworks` directory with `XXX.framework` and `YYY.framework` inside. The command line should be `-FFrameworks -framework XXX -framework YYY`.

**Comment by lasote** [comment]
I'll try to add a test to make sure everything is passed correctly, many thanks

**Comment by lasote** [comment]
It works perfectly. I created a PR with a test packaging a framework and a PR in the docs to change the documentation, I think it is the most we can do with the CMake integration:

https://github.com/conan-io/conan/pull/3595
https://github.com/conan-io/docs/pull/839
