### ISSUE TITLE
Alias being stored in local cache

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#3395]
Conan version:
 1.6.1

Scenario:
- Alias 1.5.latest points to 1.5.12
- When I execute `conan install Foo/1.5.latest@pkg/stable`, I get Foo/1.5.12@pkg/stable
- The package creator then updates alias and 1.5.latest now points to 1.5.15
- When I execute `conan install Foo/1.5.latest@pkg/stable` again, I do not get the new package, because the alias is stored in my local conan cache

As a consumer(who basically is a developer), I should not be required to clear my conan cache, since I would be using numerous such aliases.

The alias package, after resolving to actual version, should be automatically removed from my local conan cache.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
> When I execute conan install Foo/1.5.latest@pkg/stable again, I do not get the new package, because the alias is stored in my local conan cache

When things are installed in the local cache, they are never overwritten from the server, unless the ``--update`` argument is provided. Not only for alias, but for other cases, as version-ranges. Please, use that argument in your installs if you want to update things from servers.

**Comment by sunj1** [comment]
Thanks for the explanation.
In that case, could we please allow a variable in conan.conf, that enables `--update` by default for all packages?

**Comment by danimtb** [comment]
@sunj1 I dont really like the idea of polluting the Conan configuration with this kind of flags as it heavily alters the behavior of the tool. This is the default behavior with all packages as pointed out in the comment before and would not be desirable for offline development.

**Comment by memsharded** [comment]
Yes, I think I prefer adding ``-u`` to the command line, makes it explicit that it will be always checking the servers for updates. It is similar to how other package managers (like python pip) works.

**Comment by sunj1** [comment]
ok, closing the issue.
