### ISSUE TITLE
cmake.patch_config_paths doesn't work properly on windows

### ISSUE THREAD

**Issue by weatherhead99** [conan-io/conan#3398]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan release 1.6.1
bit embarassing since I wrote some of this code originally, but on Windows it doesn't work properly. A (non-relocatable) cmake config file is not correctly found and patched by cmake.patch_config_paths(), the reason being that cmake seemingly uses the forward slash "/" as a path separator in these files, even on Windows. However, the path that patch_config_paths() is looking for is obtained from 
 `from_str = self._conanfile.deps_cpp_info[dep].rootpath`
(line 537, conans/client/build/cmake.py)

So, the solution might be simply to do a .replace(os.path.sep,"/") on this string before using. On the other hand, this might clobber any paths that legitimately have a backslash in them on other platforms, so probably the best is to only do this on windows. I'm not familiar enough with current conan codebase to know exactly the best way to check for windows from this code, but with that guidance am happy (and eager!) to write the patch.

 I think the actual most elegant solution is to use pathlib to do this elegantly, but pathlib is python 3 only...

EDIT:  original PR that added feature for reference https://github.com/conan-io/conan/pull/2343

**Comment by lasote** [comment]
> bit embarassing since I wrote some of this code originally, 

Not at all! Thanks for your constant efforts. I'm reviewing the PR.
