### ISSUE TITLE
Renaming Conan packages

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3400]
To help us debug your issue please explain:

Hi!

We just released libpq to provide support for PostgreSQL C library, however now we have a new problem...

When a project wants to include postgresql cmake file it looks for FindPostgreSQL.cmake file, but are providing Findlibpq.cmake. As you can see, we need to rename the file, or entry project.

Is there any idea how to fix this situation?

Regards!

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
> but are providing Findlibpq.cmake

Why? due to `cmake_find_package` generator or the cmake file is while package?

**Comment by memsharded** [comment]
Yes, please clarify the package name and the filenames issues.

**Comment by uilianries** [comment]
Sorry, I was on mobile...

the package libpq/x.y.z@bincrafters/stable is now in Conan center and it
provides Postgresql C library as well.

However, the equivalent cmake module name is PostgreSQL.

So if I want to run `find_package(PostgreSQL)` and use our libpq package,
it won't work.

I see few options here:
- Provide FindPostgreSQL.cmake in libpq package
- Rename the libpq to postgresql
- Create a recipe called postgresql the points to libpq

I would like to know if the frogarians have some idea to deal with that.

Regards!

**Comment by lasote** [comment]
> So if I want to run `find_package(PostgreSQL)` and use our libpq package,
it won't work.

Why? The `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` are automatically set, so the `https://github.com/Kitware/CMake/blob/master/Modules/FindPostgreSQL.cmake`  should be found correctly without any special setup, just the cmake generator.

**Comment by uilianries** [comment]
Sorry, I forgot to mention that I'm not able to change the CMakeLists.txt, I only see `cmake_paths` and `cmake_find_packages` as possible options, because the `cmake` generator needs `conan_basic_setup`

Now the full context, I'm trying to finish [taocpp/postgres](https://github.com/taocpp/postgres). I would like to avoid changing the cmake file. The [taocpp-postgres.cmake#L9](https://github.com/taocpp/postgres/blob/master/taocpp-postgres.cmake#L9) includes PostgreSQL as cmake package. But if I use libpq/9.6.9@conan/stable by cmake_paths or cmake_find_packages, all paths are set using CONAN_libpq so it's not possible to find PostgreSQL.

**Comment by lasote** [comment]
I see. If you cannot even patch the CMakeLists (replace_in_file), currently, it is not possible. 
There are two possibilities (future features that could help):

a) Being able to receive parameters in the generators, for the `cmake_find_packages` is not the first time it is requested. One of the parameters could be the name of the file to be generated. But it requires a feature that needs to be carefully designed.

b) I dedicated some time to a new model of the cmake generator/build_helper and **apparently** (very preliminary tests) it might be possible to automatically inject the needed code using a toolchain `-T somefile.cmake`. But if finally it becomes a real feature it will take time, maybe even Conan 2.0.

I think we should implement both `a` and `b`, but we have no ETA for none of them.

**Comment by lasote** [comment]
I usually dislike providing a custom `FindPostgreSQL.cmake` because CMake releases commonly included new features in the scripts, like targets and so on, so it is very difficult to maintain.
