### ISSUE TITLE
Invalid numeric argument `/Wno-comment' on Windows

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#3405]
I'm building my project and getting errors with AppVeyor using Conan 1.6.1.

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/0.1.8.558/job/64v2642yrg32mms4#L844

To be fair, I'm using Conda to install CGAL and Conan.

The project is here:

https://github.com/acgetchell/CDT-plusplus

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
Hi @acgetchell,

Looks like a problem not related to Conan but I cannot say what is causing the issue.
My guess is that the flag -Wno-comment cannot be used for Visual Studio: https://github.com/acgetchell/CDT-plusplus/blob/5c5e430c3231f3859c63920343b069eff3ec0e88/CMakeLists.txt#L86

I am closing this as it is not a Conan issue but feel free to comment. Thanks
