### ISSUE TITLE
None value and default value in options

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#3407]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan v1.6.1, Windows

I know that the value `None` has a special meening in options. I think the exact meening is not fully documented (see also https://github.com/conan-io/conan/issues/2780#issuecomment-383234689). 

In the following example the behaviour seems inconsistent:

```python
class libaconan(ConanFile):
    name = "liba"
    version = "1.0"
    options = {"opt": [None, "a"]}
    default_options = "opt=a"
    
    def configure(self):
        print("opt =", self.options.opt)
```

- `conan install liba/1.0@user/testing` prints `opt = a`
- `conan install liba/1.0@user/testing -o opt=a` prints `opt = a`
- `conan install liba/1.0@user/testing -o opt=None` prints `opt = None` (!)

But with libb consuming liba:

```python
class libbconan(ConanFile):
    name = "libb"
    version = "1.0"
    requires  = "liba/1.0@user/testing"
```

- `conan install libb/1.0@user/testing` prints `opt = a`.
- `conan install libb/1.0@user/testing -o liba:opt=a` prints `opt = a`.
- `conan install libb/1.0@user/testing -o liba:opt=None` prints `opt = a`. (!)

**Comment by danimtb** [comment]
I think this issue would be a good addition to docs for Conan 1.8 once we have conan-io/conan#3424 merged

**Comment by jgsogo** [comment]
For me it is a bug related to the value ``None``. It works ok with the value ``False`` (when allowed for ``opt``, of course)
