### ISSUE TITLE
[workspaces] Conan should not generate a top-level CMakeLists.txt

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#3408]
I opened PR #3404 before opening the issue, my bad!

The first PR comment should be detailed enough to not have to re-list everything here.

**Comment by memsharded** [comment]
With the new proposal in https://github.com/conan-io/conan/pull/4481, a ``conanworkspace.cmake`` will be generated instead (maybe the CMakeLists.txt could be generated if not existing, for fast boostraping, but never overwritten)
