### ISSUE TITLE
Cmake generator does not support libstdc++11

### ISSUE THREAD

**Issue by brianembry** [conan-io/conan#3418]
To help us debug your issue please explain:

- [*] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [*] I've specified the Conan version, operating system version and any tool that can be relevant.
- [*] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan-1.6.0

Autotools generator will call libcxx_define() to setup _GLIBCXX_USE_CXX11_ABI depending on settings.compiler.libstdcxx setting.

CMake generator does no such thing.  I would expect if set_cmake_flags is true CMAKE_CXX_FLAGS should be set to the appropriate ABI.  I find it weird that set_cmake_flags to true is not default, but that's another discussion. The ABI probably should be set unconditionally though?

I've worked around it with this in my conanfile.py.
```
        flags =""
        if str(self.settings.compiler.libcxx) == "libstdc++":
            flags = "-D_GLIBCXX_USE_CXX11_ABI=0"
        elif str(self.settings.compiler.libcxx) == "libstdc++11":
            flags = "-D_GLIBCXX_USE_CXX11_ABI=1"

        cmake = CMake(self)
        cmake.definitions["CMAKE_CXX_FLAGS"] = flags

**Comment by memsharded** [comment]
Hi @brianembry 

There is code inside the generated ``conanbuildinfo.cmake`` that does this thing:

```cmake
macro(conan_set_libcxx)
    if(DEFINED CONAN_LIBCXX)
        message(STATUS "Conan: C++ stdlib: ${CONAN_LIBCXX}")
        if(CONAN_COMPILER STREQUAL "clang" OR CONAN_COMPILER STREQUAL "apple-clang")
            if(CONAN_LIBCXX STREQUAL "libstdc++" OR CONAN_LIBCXX STREQUAL "libstdc++11" )
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libstdc++")
            elseif(CONAN_LIBCXX STREQUAL "libc++")
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
            endif()
        endif()
        if(CONAN_COMPILER STREQUAL "sun-cc")
            if(CONAN_LIBCXX STREQUAL "libCstd")
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -library=Cstd")
            elseif(CONAN_LIBCXX STREQUAL "libstdcxx")
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -library=stdcxx4")
            elseif(CONAN_LIBCXX STREQUAL "libstlport")
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -library=stlport4")
            elseif(CONAN_LIBCXX STREQUAL "libstdc++")
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -library=stdcpp")
            endif()
        endif()
        if(CONAN_LIBCXX STREQUAL "libstdc++11")
            add_definitions(-D_GLIBCXX_USE_CXX11_ABI=1)
        elseif(CONAN_LIBCXX STREQUAL "libstdc++")
            add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)
        endif()
    endif()
endmacro()
```
The ``CMake`` build helper will define CONAN_LIBCXX and the ``include(conanbuildinfo.cmake)``+``conan_basic_setup()`` should manage to set this. 

Could you please check this, and why it is not being applied in your case? Do you have a full example with reproducible steps to check? Thanks!

**Comment by brianembry** [comment]
Ahh, I didn't create a conan CMakeLists that calls include(conanbuildinfo.cmake)+conan_basic_setup() that then includes "upstreams" cmake.

I'm just invoking the upstream cmake file directly.  That appears to be my issue. Sorry for the noise.

**Comment by memsharded** [comment]
No problem :)

Yes, creating a CMakeLists that wraps that (or patching the existing CMakeLists) is necessary if you want that functionality injected. We will try to make it more evident in the future evolution of generators and build helpers.

Cheers!
