### ISSUE TITLE
Default options with empty string not allowed since Conan 1.7.0 [blocking bug]

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#3421]
Hey,

I not sure if this was an accident, but are recipe which works in 1.6.1 does not work with 1.7.0.

The example is easy.
```py
 options = {
        "shared": [True, False],
        "myoptions": [True, False],
        "config": "ANY"
    }
    default_options = ( "shared=True", "myoptions=True", "config=")
```

The problem is that a empty default option is not allowed anymore (In my example `config` needs to be an empty string by default, because it is an optional argument for the "toolschain" which i start in my recipe).

Error:
`stable\export\conanfile.py: Error while initializing options. Please define a default value for 'config' in'default_options'`

If this is intended, please give my a tip how to fix this.

This will also hit bincrafter repo's, as far as I know, because they used something similar.

Greetings  
Tonka

**Comment by tonka3000** [comment]
I will try it. Thanks for the fast info

**Comment by tonka3000** [comment]
I see that bincrafters already fixed it with `'config=None'`, is that also valid? [repo](https://github.com/bincrafters/conan-qt/blob/stable/5.11.1/conanfile.py)

**Comment by lasote** [comment]
It depends on what you want. If you want an empty string, probably it is better for you to assign just `""` but let me know how it goes.

**Comment by danimtb** [comment]
@tonka3000 that should be valid too but it depends. Check the example in this section: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#options-default-options

We have updated it with some recommendations.

**Comment by danimtb** [comment]
yes, the first check is the recommended one for None as default

**Comment by tonka3000** [comment]
Seems to work. Thanks for your great and fast support. Awesome :+1:
