### ISSUE TITLE
account and password for conan upload?

### ISSUE THREAD

**Issue by SabiAmeno** [conan-io/conan#3422]
When I upload a package use command "conana upload", but I get an tip for input account and password,but where I get account and password?

**Comment by memsharded** [comment]
If you plan to upload to bintray: https://docs.conan.io/en/latest/uploading_packages/bintray/uploading_bintray.html

If you are using Artifactory, then the user/password of the Artifactory.

If you are uploading to a conan_server, then you need to add user/password to the ``server.conf`` file.

**Comment by SabiAmeno** [comment]
Think you for your help!!!! @memsharded
