### ISSUE TITLE
Regression on conan config install from 1.6.0->1.7.0 with older gits

### ISSUE THREAD

**Issue by brianembry** [conan-io/conan#3427]
I know upgrade to a git from this century :)
$ git --version
git version 1.8.2.3

conan version 1.7.0

Seeing this on my build slaves this morning with the 1.7.0 upgrade.  Looks like the fix here breaks older gits
pull https://github.com/conan-io/conan/pull/3284
bug https://github.com/conan-io/conan/issues/3282

[centos5] [build] $ sh -c "conan config install *removed*"
[centos5] Trying to clone repo  *removed*
[centos5] error: Missing value for 'init.templatedir'
[centos5] fatal: unable to parse command-line config
[centos5] ERROR: config install error. Can't clone repo: Command 'git -c http.sslVerify=True -c init.templateDir= clone "*removed*" config' returned non-zero exit status 128

**Comment by memsharded** [comment]
Hi @brianembry 

Could you please check in your git command line, if it would be enough to add quotes (empty string)? I have done that in https://github.com/conan-io/conan/pull/3429, but would like to know if that would fix your case.

The other alternative would be to replace that with a ``--args`` command line argument that can be used by users to add any special configuration.

**Comment by memsharded** [comment]
The --args approach would be in: https://github.com/conan-io/conan/pull/3431

**Comment by brianembry** [comment]
Empty string appears not to work, so args it is I guess.

$ git -c http.sslVerify=True -c init.templateDir="" clone *removed*
Cloning into 'conan-config'...
error: Missing value for 'init.templatedir'
fatal: unable to parse command-line config

A dummy template that's not found does work though.
$ git -c http.sslVerify=True -c init.templateDir="abc" clone *removed*
Cloning into 'conan-config'...
warning: templates not found abc
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (5/5), done.

**Comment by brianembry** [comment]
Build slave looks happy, thanks for the quick turnaround.
