### ISSUE TITLE
How to check which options a dependency offers?

### ISSUE THREAD

**Issue by WolfgangVogl** [conan-io/conan#3436]
Hello,
I'm trying to create a meta package (boost) for my own needs.
The package simply sets every boost package as a requirement... 
but now I want pass an option (shared) to the dependency.

Simple for all the dependencies that offer such an option - but there are some packages that don't offer the shared option. 
==> How to check which options a dependency has?
Using conan 1.61 on windows...

You can find the current state of my recipe at https://github.com/WolfgangVogl/conan-bincrafters-boost/blob/master/conanfile.py

The relevant part should be
```
def configure(self):
    for package in package_list_lower:
        if not getattr(self.options, "without_%s" % package):
            package_name = "boost_%s" % (package)
            requirement = "%s/%s@%s" % (package_name,self.version,self.options.channel)
            self.output.info("Requirement: %s" % requirement)
            self.requires(requirement)
            self.options[package_name].shared = self.options.shared # this failes for packages without that option
```
I've tried hasattr and try catch but nothing worked.

=> How to set the "help" label?

Thank you!
Wolfgang

**Comment by memsharded** [comment]
Hi @WolfgangVogl 

I think you can check the existing options, names and values with ``self.options[package_name].items()``, please try.

Also, for defining requirements, please use the ``requirements()`` method, don't define them in ``configure()``

Also, it seems you are doing a meta-package for the bincrafters modular boost. Maybe you would be interested in the monolithic boost already in conan-center?

**Comment by WolfgangVogl** [comment]
Hi @memsharded ,
thank you for the hint - i'll try and report here.

I've tried the monolithic boost package but as I also using the cpprestsdk package (which is only in the bincrafters repository) I'm getting boost 1.67 (from conan-center) AND the dependencies from cpprestsdk (boost_random, boost_system, boost_thread, ...) in the modul package.
=> Conan doesn't know that this dependencies already satisfied by the monolithc boost package.

**Comment by WolfgangVogl** [comment]
package_options = self.options[package_name].items() gives me always an empty array [].

**Comment by memsharded** [comment]
Oh, yes, that is true. The thing is that the ``configure()`` method is ran when the graph is being computed. The dependencies are still not there, your own code is defining the requirements after that. You cannot know the dependencies options until they have been fully retrieved and installed, the dependencies resolved.

Those options might be later available in the ``build()`` method for example, but not in ``configure()``

**Comment by WolfgangVogl** [comment]
that's a problem - i cant use the boost from conan center due to the cpprestsdk dependencides to modular boost from bincrafters and to set options to the modular boost packages i cant easily use a meta package. 
-> use modular boost and write every module into my conanfile.txt or
-> use a hand written whitelist of allowded options into my meta package..

**Comment by memsharded** [comment]
Package options can be defined with patterns, and they will not fail if not existing, like ``z*:shared=True`` will set shared=True to all packages that contain "z..." and have ``shared`` option, but won't fail if they don't have it.

In any case, the intrinsic definition of the problem makes impossible to have the options of the dependencies available at ``configure()`` time, so closing this issue as won't implement. There are other things that recipes can do, like ``validate()`` over ``self.dependencies[..].options`` that could help.
