### ISSUE TITLE
POCO error: relocation R_X86_64_32S against `_length_code' can not be used when making a shared object

### ISSUE THREAD

**Issue by ruimaciel** [conan-io/conan#3437]
I've been taking my first steps using conan 1.6.1 to manage external packages on a small pet project, one of them being POCO, and I've stumbled on a problem. 

The pet project is a cmake project comprised of a Qt GUI and a shared library, and the shared library includes POCO libraries provided by conan.  I've followed [conan's getting started tutorial](https://docs.conan.io/en/1.3/getting_started.html) and I've used pretty much the exact copy of the tutorial's conaninfo.txt.  However, when I try to build the project, the following linker error is thrown:

    /usr/bin/ld: /home/rui/.conan/data/Poco/1.9.0/pocoproject/stable/package/8a67b44a092c0074e3cb946a9ddada338054b11e/lib/libPocoFoundation.a(deflate.c.o): relocation R_X86_64_32S against `_length_code' can not be used when making a shared object; recompile with -fPIC
    /home/rui/.conan/data/Poco/1.9.0/pocoproject/stable/package/8a67b44a092c0074e3cb946a9ddada338054b11e/lib/libPocoFoundation.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    make[2]: *** [test/lib/libtest.so] Error 1
    make[1]: *** [test/CMakeFiles/test.dir/all] Error 2
    make: *** [all] Error 2

It's quite possible that the source of this problem lies somewhere between my keyboard and my chair.  However, I've also tried making POCO a shared library by adding the option `Poco:shared = True` to the project's conanfile.txt and after updating conan's packages the whole project (shared library and GUI) builds quite nicely.  

I'd like to be able to try out linking POCO as a static library, but I have no clue what might be the cause of the problem and how it can be fixed.   At first glance it appears that it might be something in POCO's project (perhaps a missing -fpic?) but that's doubtful as conan's tutorial consists of linking POCO as a static library, and that's expected to work.  Therefore, does anyone has any idea of what might be causing this problem and how to fix it?

**Comment by lasote** [comment]
It is definitely an issue with the fPIC. I'm going to review the Poco packages and I will come back.

**Comment by lasote** [comment]
Here is a pending PR fixing the Poco packages fpic option management: https://github.com/pocoproject/conan-poco/pull/22

We forgot it was not merged some time ago. Sorry for the inconvenience, we hope the authors merge it soon.

**Comment by lasote** [comment]
Could you try now? The new packages are uploaded!

**Comment by ruimaciel** [comment]
Hi @lasote thanks for the quick update.  I've updated the conan packages and rebuilt them and I can confirm that they are compiled with the -fPIC flag.  However, I'm having some problems getting the project to link with POCO libraries, as I'm getting a stream of undefined references.

Here's the output of the linker:

    /usr/bin/ld: ../test/lib/libtest.so: undefined reference to `Poco::Net::HTTPRequest::HTTP_GET[abi:cxx11]'
    /usr/bin/ld: ../test/lib/libtest.so: undefined reference to `Poco::Net::HTTPMessage::HTTP_1_1[abi:cxx11]'
    /usr/bin/ld: ../test/lib/libtest.so: undefined reference to `Poco::URI::URI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    /usr/bin/ld: ../test/lib/libtest.so: undefined reference to `Poco::Net::HTTPRequest::HTTPRequest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    /usr/bin/ld: ../test/lib/libtest.so: undefined reference to `Poco::Net::Impl::IPv6SocketAddressImpl::toString[abi:cxx11]() const'
    /usr/bin/ld: ../test/lib/libtest.so: undefined reference to `Poco::Net::Impl::IPv4SocketAddressImpl::toString[abi:cxx11]() const'
    /usr/bin/ld: ../test/lib/libtest.so: undefined reference to `Poco::Net::HTTPClientSession::HTTPClientSession(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short)'
    /usr/bin/ld: ../test/lib/libtest.so: undefined reference to `Poco::URI::toString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status

I've checked the symbol names present in my test library (nm --demangle libtest.so) and here's a selection of what I found (grepped for each undefined symbol returned by the linker):

                     U Poco::Net::HTTPRequest::HTTP_GET[abi:cxx11]
    0000000000188f20 B Poco::Net::HTTPRequest::HTTP_GET
    ...
                     U Poco::Net::HTTPMessage::HTTP_1_1[abi:cxx11]
    0000000000188ea0 B Poco::Net::HTTPMessage::HTTP_1_1
    ....
    00000000000f3970 T Poco::URI::URI(char const*)
    00000000000f10a0 T Poco::URI::URI(Poco::Path const&)
                     U Poco::URI::URI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    00000000000f0ff0 T Poco::URI::URI(Poco::URI const&)
    00000000000f5480 T Poco::URI::URI(Poco::URI const&, std::string const&)
    00000000000f38a0 T Poco::URI::URI(std::string const&)
    00000000000f3b90 T Poco::URI::URI(std::string const&, std::string const&)
    00000000000f3c10 T Poco::URI::URI(std::string const&, std::string const&, std::string const&)
    00000000000f3a30 T Poco::URI::URI(std::string const&, std::string const&, std::string const&, std::string const&)
    00000000000f3ad0 T Poco::URI::URI(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&)
    00000000000f0fc0 T Poco::URI::URI()
    00000000000f3970 T Poco::URI::URI(char const*)
    0000000000096372 t Poco::URI::URI(char const*) [clone .cold.84]
    00000000000f10a0 T Poco::URI::URI(Poco::Path const&)
    0000000000095f26 t Poco::URI::URI(Poco::Path const&) [clone .cold.71]
    00000000000f0ff0 T Poco::URI::URI(Poco::URI const&)
    0000000000095ea2 t Poco::URI::URI(Poco::URI const&) [clone .cold.70]
    00000000000f5480 T Poco::URI::URI(Poco::URI const&, std::string const&)
    000000000009678a t Poco::URI::URI(Poco::URI const&, std::string const&) [clone .cold.97]
    00000000000f38a0 T Poco::URI::URI(std::string const&)
    00000000000962c0 t Poco::URI::URI(std::string const&) [clone .cold.81]
    00000000000f3b90 T Poco::URI::URI(std::string const&, std::string const&)
    0000000000096540 t Poco::URI::URI(std::string const&, std::string const&) [clone .cold.87]
    00000000000f3c10 T Poco::URI::URI(std::string const&, std::string const&, std::string const&)
    00000000000965d2 t Poco::URI::URI(std::string const&, std::string const&, std::string const&) [clone .cold.88]
    00000000000f3a30 T Poco::URI::URI(std::string const&, std::string const&, std::string const&, std::string const&)
    0000000000096410 t Poco::URI::URI(std::string const&, std::string const&, std::string const&, std::string const&) [clone .cold.85]
    00000000000f3ad0 T Poco::URI::URI(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&)
    00000000000964a8 t Poco::URI::URI(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&) [clone .cold.86]
    00000000000f0fc0 T Poco::URI::URI()

For some reason the undefined symbols appear tagged with [abi:cxx11].  My test project is set to compile with C++11 as well, and I have no clue why this is happening.

**Comment by memsharded** [comment]
@ruimaciel are you sure you are installing the ``libcxx=libstdc++11``? Because the default is ``libcxx=libstdc++``. So when you run ``conan install``, the dependencies you get are libstdc++. This is something that cannot be changed without breaking existing users. We strongly recommend to use your own profiles in production, and not rely on the automatically generated default profile, which is subject to changes.

**Comment by ruimaciel** [comment]
@memsharded thank you for the quick reply.  I've just finished building conan's POCO package with libcxx=libstdc++11 and the linker problems went away.  Awesome stuff.  Thanks for the help.

Regarding the comment on relying on the automatically generated default profile, this appears to be a significant usability problem affecting Conan.  If Conan's default options break basic builds based on Conan's official "getting started" tutorial and require first timers to "not rely on the automatically generated default profile" then Conan's role as a problem solver is put into perspective, as it appears to needlessly create more problems than it solves and require more work than it would to simply download the library and build it ourselves.

**Comment by memsharded** [comment]
Yes, you are totally right. It is a pending fix to update the getting started docs to clearly define this and help the users not to fall in this error. And of course we are really looking forward to change this, we are considering how to do this and if possible to do without breaking other existing users, or really need to wait until conan 2.0 because there is no other way. Thanks very much for the feedback!
