### ISSUE TITLE
Study apiv2 checksum check

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3446]
Consider using the manifest instead of the tgz sum? (Masks stored makes a different tgz)

**Comment by memsharded** [comment]
Makes sense to solve issue https://github.com/conan-io/conan/issues/3067

Would it make sense to implement it also for api v1?

**Comment by lasote** [comment]
If it doesn't require api changes, of course. Let's take a look for 1.8

**Comment by lasote** [comment]
Closed by #3480. Will be available in 1.8 for both v1 and v2
