### ISSUE TITLE
AutoToolsBuildEnvironment using --build=x86_64-linux-gnu on aarch64 and ppc64le architectures

### ISSUE THREAD

**Issue by djeverett** [conan-io/conan#3449]
AutoToolsBuildEnvironment automatically adds --build=x86_64-linux-gnu to the configure arguments, even if the architecture is not x86_64.  I have seen this on Arm (aarch64) and Power8 (ppc64le) architectures.

**Comment by memsharded** [comment]
Yes, the dict that maps it is:

```python
# Calculate the arch
    machine = {"x86": "i686" if os != "Linux" else "x86",
               "x86_64": "x86_64",
               "armv6": "arm",
               "armv7": "arm",
               "armv7s": "arm",
               "armv7k": "arm",
               "armv7hf": "arm",
               "armv8": "aarch64"}.get(arch, None)
```
It is clear that this could be completed, in the ``get_gnu_triplet()``, for the Power8, though it is not that evident why it is not working well for ARM. Do you have some pointers to which values should the conan architectures map? Thanks!

**Comment by memsharded** [comment]
You are missing in your profile ``arch_build`` if you want it defined. (also ``os_build``)

**Comment by djeverett** [comment]
Note: detected_architecture() also broken for Power, as platform.machine() returns "ppc64le", again containing 64.

**Comment by jgsogo** [comment]
Done some investigation around this issue:

> On platforms with os.uname(), this information comes directly from the result of that API call. That is to say, platform.machine() returns the same thing as the uname -m command. ([link](https://stackoverflow.com/questions/45124888/possible-values-for-platform-machine))

And from [here](https://stackoverflow.com/questions/45125516/possible-values-for-uname-m) we have an interesting list (July, 2017):

- alpha
- arc
- arm
- aarch64_be (arm64)
- aarch64 (arm64)
- armv8b (arm64 compat)
- armv8l (arm64 compat)
- blackfin
- c6x
- cris
- frv
- h8300
- hexagon
- ia64
- m32r
- m68k
- metag
- microblaze
- mips (native or compat)
- mips64 (mips)
- mn10300
- nios2
- openrisc
- parisc (native or compat)
- parisc64 (parisc)
- ppc (powerpc native or compat)
- ppc64 (powerpc)
- ppcle (powerpc native or compat)
- ppc64le (powerpc)
- s390 (s390x compat)
- s390x
- score
- sh
- sh64 (sh)
- sparc (native or compat)
- sparc64 (sparc)
- tile
- unicore32
- i386 (x86)
- i686 (x86 compat)
- x86_64 (x64)
- xtensa
