### ISSUE TITLE
Provide updated releases/tags

### ISSUE THREAD

**Issue by bmgandre** [conan-io/conan#346]
I'm working to create a Conan package script for Slackware Linux. However, the repository contains only outdated tags, which makes harder for package creators by requiring them to fetch and host the sources.
Another good improvement is to provide a static link to get the specific versions.

**Comment by lasote** [comment]
Hi, I've pushed the tags, I forgot it. 
Thanks!

**Comment by memsharded** [comment]
About the static links, are not enough the links that github provides for different releases? Like, e.g.: https://github.com/conan-io/conan/archive/0.9.4.zip

**Comment by bmgandre** [comment]
Thanks @lasote

@memsharded, though these links are not static, it is good enough. Thanks.

**Comment by memsharded** [comment]
Good. If you are creating and sharing the Slackware package, please tell us when done, maybe we can link/document it from conan. 

I guess that the issue can be closed. Just reopen if we forgot to push the tags again. Thanks for reporting!
