### ISSUE TITLE
[python-requires] re-use scm variable for building from sources

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#3461]
- Conan version: 1.7.1
- I'm using python_requires to re-use scm variable.
- The library builds fine, but the final package which consumes the library does not.
- This is because the scm variable is not expanded/processed while saving the conanfile for upload in local cache

conanfile for MyBase:
```
scm = {
"type" : "git",
"url" : "auto",
"revision" : "auto"
}
```

conanfile for consumer library:
```
from conans import ConanFile, CMake, tools, python_requires
base = python_requires("MyBase/1.7@demo/stable")

class MyPkgConanFile(base.MyBase):
    scm = base.scm
```
The same conanfile is saved in local cache, as opposed to the expanded values of scm variable.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, seems an issue.

Wouldn't you actually prefer that ``scm`` is an attribute of the base class, and extending the base class automatically would handle it?

**Comment by memsharded** [comment]
The origin is this line:

https://github.com/conan-io/conan/blob/8c9ea8d4f4903bfb781779056c0d79f3701c3115/conans/model/scm.py#L44

This replacement should be improved to:

- Replace also other expressions: ``scm = some-expression``. I would say to allow single-line only
- Generate it, even if ``scm = `` doesn't exist in the conanfile, for the case it is being inherited from the base conanfile.

Feedback from @lasote requested

**Comment by memsharded** [comment]
This is the test in my branch to work on this feature: https://github.com/conan-io/conan/compare/develop...memsharded:feature/reuse_python_scm?expand=1

**Comment by sunj1** [comment]
> Oh, I see. If added to the base class, then it will already be evaluated when exporting the base class. And that one doesn't have any idea it will be a python_requires, so it is not possible to skip it.

Yes, correct.

> Generate it, even if `scm =` doesn't exist in the conanfile, for the case it is being inherited from the base conanfile.

I think, it should be generated only if referenced from the derived class.
This would in turn support combination of multiple VCS other than Git (since scm currently only supports Git) and it would be good not to break this behavior.
