### ISSUE TITLE
`conan search` confusingly uses different case sensivity settings for local and remote

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3463]
Here's an example showing the problem:

```
$ conan search 'poco/*'
Existing package recipes:

Poco/1.9.0@pocoproject/stable
$ conan search -r all 'poco/*'
There are no packages matching the 'poco/*' pattern
$ conan search -r all 'Poco/*'
Existing package recipes:

Remote 'conan-center':
Poco/1.7.8p3@pocoproject/stable
Poco/1.7.9@pocoproject/stable
Poco/1.7.9p1@pocoproject/stable
Poco/1.7.9p2@pocoproject/stable
Poco/1.8.0.1@pocoproject/stable
Poco/1.8.0@pocoproject/stable
Poco/1.8.1@pocoproject/stable
Poco/1.9.0@pocoproject/stable
```

So, I'm on Linux, using case-sensitive filesystem, but a local search is case-insensitive, which feels weird. However, searching on remotes, the search is now magically case-sensitive! As if this wasn't confusing enough, there's a `--case-sensitive` option to `conan search`:

> Make a case-sensitive search. Use it to guarantee
>                         case-sensitive search in Windows or other case-
>                         insensitive file systems

From [this comment](https://github.com/conan-io/conan/issues/1479#issuecomment-313144925), I understand this is useful for local searches on case-insensitive OSes, mainly on Windows.

Having a different case handling is kind of confusing. It should be all case-sensitive or case-insensitive by default, and have a switch to revert the bahavior.

Personally I think searches should be case-sensitive by default, and a case-insensitive flag added, although it seems that #1479 goes the other way around.

Using Conan 1.7.1 on Ubuntu 14.04.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by joechrisellis** [comment]
Just looked into this briefly. Appears to me like this is an issue concerning the `conan-center` remote? If I run a local conan server and upload zlib to it, I get the following results.

With weird casing:

```
$ conan search 'zLiB/*' -r test
Existing package recipes:

zlib/1.2.11@conan/stable

$ conan search 'zLiB/*' -r conan-center
There are no packages matching the 'zLiB/*' pattern

$ conan search 'zLiB/*' -r all
Existing package recipes:

Remote 'test':
zlib/1.2.11@conan/stable
```

Without weird casing:

```
$ conan search 'zlib/*' -r test
Existing package recipes:

zlib/1.2.11@conan/stable

$ conan search 'zlib/*' -r conan-center
Existing package recipes:

zlib/1.2.11@conan/stable
zlib/1.2.11@conan/testing
zlib/1.2.8@conan/stable

$ conan search 'zlib/*' -r all
Existing package recipes:

Remote 'conan-center':
zlib/1.2.11@conan/stable
zlib/1.2.11@conan/testing
zlib/1.2.8@conan/stable
Remote 'test':
zlib/1.2.11@conan/stable
```

My `test` remote is just the included Python `conan_server`. Perhaps `conan-center` is running a different server and there is just a small implementation difference?

**Comment by liberforce** [comment]
Thanks for looking into this. From [@memsharded comment on bug #1479 ](conan search -r conan-center zlib/1.2.11@conan/stable) I understood conan had control on this, but maybe he was talking about the conan server reference implementation?

**Comment by memsharded** [comment]
Conan 2.0 is always-lowercase, and that has been also enforced in ConanCenter for years now.
