### ISSUE TITLE
[SCM] SCM feature + recipe in a repo subfolder leads to "same computer clone" bug

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#3465]
Getting back to our Conan recipe, conan `1.7.1` solves the problem described #3322 thus (re)allowing a recipe living in subfolder of the repository to use the `scm` feature.
Sadly, another bug, initially described in #3069 (under the name _same computer optimization problem_) is still present: when `conan create`ing the recipe, in this situation, the creation fails, complaining there are no files in the `build` folder (and indeed, there are none).

It seems the analysis made in #3069 is still relevant:
Basically, when calling `conan create`, an optimization described in the [tip box of this documentation section](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-from-git-scm-experimental) creates an `scm_folder.txt` file in the conan package. When this file is present, conan tries to clone the repo from the path in this file instead of the git url stored in the exported recipe. 

Sadly, this file contains the path to the folder containing the recipe, instead of the path to the root of the repository. So, when the recipe is at the root of the repository, the behaviour appears correct. But if the recipe is stored in a subfolder, then it seems nothing is cloned over to the build folder, failing the process.

**Comment by memsharded** [comment]
Ok, if I understood it correctly, this is a bug, and the solution would be that the ``scm_folder.txt`` points to the root of the repo, not to the current conanfile.py folder. 
Seems necessary steps would be:
- Augment the SCM and Git helpers with ``get_root_folder()`` functionality that will retrieve the root folder of the repo.
- Use that in ``_capture_export_scm_data()``

**Comment by jgsogo** [comment]
Hi!

With the repo provided by @Adnn in the issue #3322 (https://github.com/Adnn/issue_conan-3322), I get an error calling `conan create` (please, confirm this is the bug you are reporting):

```bash
$ git clone https://github.com/Adnn/issue_conan-3322
$ cd issue_conan-3322
$ conan create conan/ issue/test
...
scm-test/0.0.0@issue/test: Calling build()
CMake Error: The source directory "/Users/jgsogo/.conan/data/scm-test/0.0.0/issue/test/build/de56269f90f07cc61427d9012acf098d4354f43d/cloned_repo" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
scm-test/0.0.0@issue/test: 
scm-test/0.0.0@issue/test: ERROR: Package 'de56269f90f07cc61427d9012acf098d4354f43d' build failed
scm-test/0.0.0@issue/test: WARN: Build folder /Users/jgsogo/.conan/data/scm-test/0.0.0/issue/test/build/de56269f90f07cc61427d9012acf098d4354f43d
ERROR: scm-test/0.0.0@issue/test: Error in build() method, line 18
	cmake.configure(source_folder="cloned_repo")
```

I've created a PR #3479 that fix this one, it is an easy one, but we need to add tests before merging it.

Thanks for reporting and the detailed information (and the example repo! 👍 )

**Comment by Adnn** [comment]
Hi @jgsogo, and thank you for taking time to look at this issue,

You are right, this repo triggers the issue. It's recipe is in a subfolder, thus after calling `conan create` you can see that `scm_folder.txt` contains the path to the subfolder in the filesystem. And that your folder `/Users/jgsogo/.conan/data/scm-test/0.0.0/issue/test/build/de56269f90f07cc61427d9012acf098d4354f43d/cloned_repo` is an empty folder (I assume because it is an attempted clone based on the incorrect info in `scm_folder.txt`).

**Comment by jgsogo** [comment]
Great! I've just asked for review PR #3479. I think it is ok, so soon this will be fixed/available. 😊
