### ISSUE TITLE
Transitive dependency through "private" requirement

### ISSUE THREAD

**Issue by Ujifman** [conan-io/conan#3466]
We have three libraries: 
- `Lib1` - is shared dynamic library,
- `Lib2` - is **NOT** shared static library, 
- `Lib3` - is shared dynamic library

1. `Lib1`
```
requires = None
```
2. `Lib2`
```
 requires = ( "Lib1/1.0@someuser/dev" )
```
2. `Lib3`
```
requires = ( ("Lib2/1.0@someuser/dev", "private"), )
```
3. `App`
```
requires = ( "Lib3/1.0@someuser/dev" )
```

So I think when I do `conan install` for `App` it should install `Lib1` and `Lib3` dependencies because if `Lib2` code is in `Lib3` (and `Lib2` must be private, as It is not good idea to show static library for downstream), so `Lib3` needs `Lib1` for running, and it will fail run without `Lib1`. If I use `Lib3` in some `App` executable, I need `-lLib1` to run successfully. But now `Lib1` doesn't appear in `conanbuildinfo.pri`. I have prepared example if needed.

OS Windows 10, x64
Python 3.6.2
conan 1.6.1

**Comment by memsharded** [comment]
When ``Lib3`` is requiring ``Lib2`` as private, it is telling that no matter what happens, if there is a binary already existing for ``Lib3``, ``Lib2`` and whatever transitive dependencies of ``Lib2`` are not necessary. ``private`` creates a completely isolated private sub-graph, including transitive dependencies. i.e. private property is extended to the whole subgraph of dependencies from that one declared to be private.

In general ``private`` is discouraged, should be used only for some extreme cases where it is really necessary to isolate private requirements (like if need to depend on 2 different versions of the same library). Most of the functionality of ``private`` has been superseded by ``build_requires``.

**Comment by Ujifman** [comment]
In case of using `build_requiers` another problem occur. As mentioned [here](https://github.com/conan-io/conan/issues/3295). If I put `Lib2` in `build_requires` section of `Lib3`, and I will add some another library (lets name it `Lib4`) in requires section of App (with `Lib1` in `requires` section of `Lib4`), Some time after (when some versions pass) I will have 2 times include of `Lib1` for `App` project with different versions, and that will lead to situation where one doesn't know what version of `Lib1` is actually linked to `App`.

**Comment by memsharded** [comment]
Conan 2.0 brings a completely new graph model with traits to control visibility better. Closing this as outdated and solved.
