### ISSUE TITLE
Can't get binary package ids on remote package

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3469]
The help of `conan search` says:

> If a full reference is provided (pkg/0.1@user/channel) then the existing binary packages for that reference will be displayed.

However, 
```
$ conan search -r all zlib/*
Existing package recipes:

Remote 'conan-center':
zlib/1.2.11@conan/stable
zlib/1.2.11@conan/testing
zlib/1.2.8@conan/stable
$ conan search -r all zlib/1.2.11@conan/stable
Existing packages for recipe zlib/1.2.11@conan/stable:

$ conan search -r conan-center zlib/1.2.11@conan/stable
ERROR: Unable to retrieve resource.. [Remote: conan-center]

$ conan search zlib/1.2.11@conan/stable
Existing packages for recipe zlib/1.2.11@conan/stable:

    Package_ID: 755fc07adbed235a7d3eadec4b6882d4912f09bc
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.version: 4.8
            os: Linux
        Outdated from recipe: False
```

So I can get binary package ids on a local package, but not on remotes.

Using Conan 1.7.1 on Linux.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Reproduced, thanks for reporting.

**Comment by memsharded** [comment]
Confirmed that both conan_server and Artifactory CE are working ok regarding this, so this seems only bintray.

**Comment by Talkless** [comment]
Is this the same bug due to which ` conan search zlib/1.2.11@conan/stable --table=file.html -r=conan-center` example from https://docs.conan.io/en/latest/getting_started.html#inspecting-dependencies does not work?
```
$ conan search zlib/1.2.11@conan/stable --table=file.html -r=conan-center
ERROR: Unable to retrieve resource.. [Remote: conan-center]
```
Conan 1.7.4 from PyPi inside Python 3.5.3 venv on Debian Stretch.

**Comment by memsharded** [comment]
We moved long time ago from bintray to an Artifactory backend, this is no longer an issue.
