### ISSUE TITLE
Helper function to run conan install from inside build step

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#347]
Sorry if this is already possible. I did not find any such functionality.

The problem:

When writing a recipe for a project that itself uses conan as dependency manager, I currently manually run the "conan install --build=missing -s arch=...." command in the build step of the recipe. It would be nice to have a built-in function that provides this command with the appropriate parameters.

**Comment by memsharded** [comment]
Hi Robert,

No, right now this is not possible, as the full command line or parameters are not passed down all the way till the ``build()`` method. 

I would like to know the exact use case, why are you running that inside ``build()``, what is the software that you are building, etc. Sounds like it is the task that the package manager might be able to do, if you use ``requires`` between packages, or that a higher level (as CI system) should handle.

In essence, the install is repeated for every dependency in the dependency graph with the given parameters, transitively and in order. So, knowing about the use case might give some ideas or different approaches. If you have it in a repo, a pointer to the repo would be also useful. Thanks!

**Comment by Blubbz0r** [comment]
Basically, I have a library "LibA" that has some external dependencies like google mock. These are managed with a conanfile.txt in the root of the repo. LibA itself is then a dependency of "LibB". Thus, I created a conanfile.py for LibA and uploaded it to the conan server. In the conanfile of LibA however, I also need to install its dependencies with conan. That's why I used conan install in the build step.

Your "the install is repeated for every dependency in the dependency graph with the given parameters" comment seems to suggest that the conan install in the build step is actually completely unnecessary though and the actual requirements should simply be listed e.g. in the requirements step of the conanfile.py again, right?

**Comment by memsharded** [comment]
Right. Doing it in the build() step doesn't seem necessary. Dependencies are transitive. So if you have LibB->LibA->Googlemock, when you install over LibB, googlemock is also retrieved, with the same parameters provided!

So you have to:
- Add the correspondent ``requires`` field to the ``conanfile.py`` of  LibA, pointing to the googlemock package.
- conan install in the conanfile.txt for LibB

**Comment by Blubbz0r** [comment]
One more thing: As stated, LibA is using a conanfile.txt with the google mock requirement. It also uses cmake with ```include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)``` and ```conan_basic_setup()```. The same applies for LibB. When I now do a ```conan install``` in the build directory for LibB, the installation will fail, since there is no conanbuildinfo.cmake in the build folder of LibA. That's why I still thought that an explicit ```conan install``` in the build step was necessary. Is this just the wrong approach?

**Comment by memsharded** [comment]
Yes, that can be solved adding the generator "cmake" to LibA. If LibA package ``conanfile.py`` (not conanfile.txt) if you have dependencies and you are using cmake and expect the ``conanbuildinfo.cmake`` to exist, you have to specify the system to generate it for you.

**Comment by Blubbz0r** [comment]
Ahh, that was the bit I was missing :)

Thanks for your help. Gonna close the issue.

**Comment by memsharded** [comment]
Perfect :) Just a suggestion, try to be systematic in the package creation, using ``test_package`` really helps. Go for a LibA package working with its test_package, before proceeding to depend on it from a LibB package.

Thanks to you for reporting and working to figure it out! Glad to help, we'll be here for further questions, cheers!
