### ISSUE TITLE
[MAC}Best way to manage dynamic library install names

### ISSUE THREAD

**Issue by WayeeWang** [conan-io/conan#3476]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.6
OS: Mac OSX 10.13

Question:
We are trying to use Conan in our project to manage all 3rd party libraries (most of them are dynamic libraries) that we use in our project, for development uses. The idea is to build all of these external libraries on our build server and store them in Artifactory. And the all developers would install these externals into their local cache, to be used to build/run our project products locally.

On Windows this is fairly easy as we just need to copy all of the dlls into our product directory next to the executables. 

But on Mac it is another story. These external libraries have different ways of building, i.e. Cmake, configure/make, manually written build scrips, pre-built binaries etc. Therefore, the install names of these libraries are out of control. For instance some of them have the `@rpath/xxx.dylib` flavour, some have full path, some have only the file name.

What would be best practice to make them loadable? Does conan provide some kind of tool to easily patch them to have a unified format? 

PS: Due to the new SIP protocol that APPLE introduced, setting DYLD_LIBRARY_PATH is not an option anymore.

**Comment by rconde01** [comment]
I have run into related problems:

- The binaries generated by the packages on conan center have a variety of install name patterns:
  - @rpath/libxxxx.dylib
  - libxxxx.dylib
  - /User/me/.conan/data/somelib/.../lib/libxxxx.dylib

Note this is even when built locally. Although i'm not even sure what happens with the last one if the binaries are cached on conan center...maybe those packages have some rule to never be cached on conan center.

So here we have a couple problems. 
- When we import the dylibs to the bin dir in our conan import() method, the install names will be wrong (assuming they are not already @rpath/)...I guess "wrong" is a bit subjective here since the intent isn't known, but at the least they will be inconsistent.
- When we link to these dylibs, these "incorrect" install names will be embedded in our new binaries.

I have approached this problem in the following way. First I developed the following python script which takes an executable or library and changes the install name and dependency install names to @rpath/libxxx.dylib

```
import subprocess
import sys

def unify_install_paths(binary_path):
    '''
    Changes the install name specified binary and all non-system
    dependencies to @rpath/binary_file_name
    '''

    # otool can tell us the current install name and the install 
    # names of the dependencies. So run it and parse the output. 

    otool_command = ['otool','-L',binary_path]

    otool_proc = subprocess.run(otool_command,capture_output=True)
    otool_proc.check_returncode()

    otool_lines = otool_proc.stdout.decode('utf-8').splitlines()

    # The first line from otool will be the binary we're altering.
    # Get the file name of the binary we're altering.
    # This will be in the form [/x/y/z/]libname.dylib:

    # strip off the ':'
    binary_file_name = otool_lines[0][:-1]

    # remove the leading path if there is one
    if binary_file_name.find("/") != -1:
        binary_file_name = binary_file_name[binary_file_name.rindex("/") + 1:]

    #print("binary file name: %s" % binary_file_name)

    # we're done with the first line so remove it from the collection
    otool_lines = otool_lines[1:]

    # The rest of the lines are the install names of our dependencies
    # or the install name of the binary itself. Go through each one and
    # fix it up.
    for line in otool_lines:
        #print("   line: " + line)

        # The end of each shared library reference will contain
        # compatibility information, in the form:
        #  (compatibility version x.y.z, current version q.r.s)
        # but we don't want that so remove it 
        compat_index = line.find(" (compatibility")
        filtered_line = line[0:compat_index]

        # trim off any leading or trailing whitespace
        current_value = filtered_line.strip()

        # now we have the install name of the dylib 
        dylib_name = current_value

        # but we just want the file name, not the install name
        # so strip off everything except the file name
        if dylib_name.find("/") != -1:
            dylib_name = dylib_name[dylib_name.rindex("/") + 1:]

        install_name_command = []

        # use the install_name_tool to alter the install name of the binary and dependencies
        if dylib_name == binary_file_name:
            # if the dylib name is the same as the binary name, then we're changing the 
            # install name of the binary we passed
            install_name_command = ['install_name_tool','-id','@rpath/' + dylib_name,binary_path]
        else:
            # otherwise this is a referenced library, so change the referenced name

            # we don't want to change refences to system libraries
            if current_value.startswith("/usr") or current_value.startswith("/System"):
                continue

            install_name_command = ['install_name_tool','-change',current_value,'@rpath/' + dylib_name, binary_path]

        in_proc = subprocess.run(install_name_command,capture_output=True)
        in_proc.check_returncode()

    # check the result
    #sanity_proc = subprocess.run(otool_command)
    #sanity_proc.check_returncode()

if __name__ == "__main__":
    unify_install_paths(sys.argv[1])
```

Then I fix up my imports like so:
```
    def imports(self):
        self.copy("*.dll",src="bin",dst="bin")
        self.copy("*.dll",src="lib",dst="bin")
        self.copy("*.so*",src="bin",dst="bin")
        self.copy("*.so*",src="lib",dst="bin")

        # Is this insane, ignorant, or clever?
        # On MacOS, fix up the install names of all libraries
        # and their non-system dependencies to be @rpath/libname.lib
        if tools.os_info.is_macos:
            # we only want to fix up the dylibs we're importing
            # so get the current contents and modified dates
            initial_files = {}

            for file in glob.glob("./bin/*.dylib"):
                if os.path.islink(file):
                    continue
                initial_files[file] = os.path.getmtime(file)

            self.copy("*.dylib",src="bin",dst="bin")
            self.copy("*.dylib",src="lib",dst="bin")

            for file in glob.glob("./bin/*.dylib"):
                if os.path.islink(file):
                    continue

                print("file: " + file)

                # skip files which were already there and have the same modified date
                if file in initial_files.keys() and os.path.getmtime(file) == initial_files[file]:
                    print("   skip file...not updated")

                unify_install_paths.unify_install_paths(file)
```

and finally I set up a post build step on all my executables and libraries to call this script.

Seems to work as expect but i'm not sure if it's insane. If it's not insane, it might be good to build this in as a tool to conan or at least document the approach.

**Comment by SpaceIm** [comment]
This issue in conan hooks may be of interest for you: https://github.com/conan-io/hooks/issues/376

I'm currently fixing all conan-center recipes so that install_name of shared libs on macOS is `@rpath/<libfilename>`

**Comment by memsharded** [comment]
Conan now contains a tool to do this https://docs.conan.io/2/reference/tools/apple/other.html#conan.tools.apple.fix_apple_shared_install_name

Closing this ticket, please open new ones if you have any question, thanks!
