### ISSUE TITLE
 Conan doesn't support Macos, apparently?

### ISSUE THREAD

**Issue by bgenchel** [conan-io/conan#3481]
OSX 10.11.6 El Capitan
Homebrew 1.7.3

Installed Conan with homebrew via
`brew install conan`

Getting this when I try to install anything:
`Invalid setting 'Macos' is not a valid 'settings.os' value.`

Look inside my settings.yml file to find
```
os:
    Windows:
    ┆   subsystem: [None, cygwin, msys, msys2, wsl]
    WindowsStore:
    ┆   version: ["8.1", "10.0"]
    Linux:
    Macos:
    ┆   version: [None, "10.6", "10.7", "10.8", "10.9", "10.10", "10.11", "10.12", "10.13", "10.14"]
    Android:
    ┆   api_level: ANY
    iOS:
    ┆   version: ["7.0", "7.1", "8.0", "8.1", "8.2", "8.3", "9.0", "9.1", "9.2", "9.3", "10.0", "10.1",
 "10.2", "10.3", "11.0"]
    watchOS:
    ┆   version: ["4.0"]
    tvOS:
    ┆   version: ["11.0"]
    FreeBSD:
    SunOS:
    Arduino:
    ┆   board: ANY
```

No idea what's happening, but honestly, I'm about to give up. I wanted to use conan to set up a common dev environment for a software team, but I've already had to do a bunch of custom fanagling to get it to even run the examples given in the docs.

I really have a very low opinion of this software at this point. I don't understand why this is such a headache when every other package manager just works out of box.

**Comment by acgetchell** [comment]
It works for my projects:

https://github.com/acgetchell/causal-sets-explorer

https://github.com/acgetchell/CDT-plusplus

**Comment by Croydon** [comment]
macOS is definitely supported.

Not sure why but it seems like the homebrew version did also fall a little bit behind the current release.

Have you tried installing via pip?

**Comment by Croydon** [comment]
It would also help to know what Conan packages you have tried to install

**Comment by sztomi** [comment]
Try installing conan via pip. If that works, this is a bug that should be reported to homebrew.

**Comment by memsharded** [comment]
Thanks all for the feedback. From the docs: https://docs.conan.io/en/latest/installation.html

> The preferred and strongly recommended way to install Conan is from PyPI, the Python Package Index, using the pip command.

The brew installation is managed by the homebrew team, not by conan team.

**Comment by sztomi** [comment]
To be fair though, the brew installation _is_ listed on that page. I think it would be useful to highlight visibly which is official and supported and which is not.

**Comment by lasote** [comment]
Fair enough. Download page updated: https://conan.io/downloads.html

**Comment by danimtb** [comment]
@ilovezfs seems to be maintaining the the brew formula for Conan. Maybe can help to clarify the issue.

I would also like to ask if the brew updated for Conan are automated somehow or if it is something done manually.

Thanks!
