### ISSUE TITLE
Add InvalidConfigurationException to be raised in Conanfile.configure()

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3484]
Copy here the issue discussed at conan-package-tools https://github.com/conan-io/conan-package-tools/issues/146:

> Motivation.- Protobuf package has an issue with windows/shared configuration so we have to disable it and prevent CI to run those jobs in order to get a green badge.
>
> What to ask for.- I think that it would be useful to have a conan.errors.InvalidConfigurationException (better name?) to be raised from configure() method in recipes instead of the generic ConanException (as it is suggested here). This way users will get the proper information when running conan, but projects like conan-package-tools can catch this specific exception, handle it and mark the job in CI as successful.
>
> This way we don't need to tweak build.py files to avoid running certain configurations, so we move forwards to a even more standarized (unneeded) file.

Will require to add the exception type and document it ([here](https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#recipe-quality)), I think that Conan's internals won't be affected by it.

**Comment by lasote** [comment]
The conan application has to return a different return number when that exception is raised, to detect even without running in a python script.
