### ISSUE TITLE
Can we package a header only library and static library together ?

### ISSUE THREAD

**Issue by AmitJain001** [conan-io/conan#3487]
To help us debug your issue please explain:

We have a test library ( based on gtest ) and a static library which is used for report generation. We need to generate report for tests as well, and that leads to a circular dependency between these 2 libraries. Is there a way I can make the header only test library a part of the static library include folder, and package them together ?

**Comment by memsharded** [comment]
Sure, packages can contains multiple libraries. There are many examples, as Poco, Boost, and gtest itself, which might contain more than a single library in the same package. Just make sure to ``package()`` all the libraries and headers, and add ``self.cpp_info.libs = ["yourlib1", "yourlib2"]`` in ``package_info()`` (no need to add header only there, those would be in the default ``include`` path, or in ``self.cpp_info.includedirs``.

**Comment by AmitJain001** [comment]
Thsnks so much ! Will try it out

**Comment by danimtb** [comment]
Closing this but feel free to comment with your results @AmitJain001 :)
