### ISSUE TITLE
Platform-dependent dependencies

### ISSUE THREAD

**Issue by sssilver** [conan-io/conan#3489]
- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I'm using the latest Conan. I have a cross-platform project (Windows/iOS/macOS/Linux/...) where some dependencies are needed (and can be compiled) only for some of the platforms.

Example: `darwin-toolchain/1.0@theodelrieu/stable` should only be downloaded/linked when the project is built for iOS/macOS.

How do I go about specifying that in my conanfile.txt?

**Comment by danimtb** [comment]
Looks like the @theodelrieu toolchain needs Xcode https://github.com/theodelrieu/conan-darwin-toolchain#setup

You currently the only way to do crossbuilding will be from macOS, as Xcode is not supported in Windows/Linux.

Have a look at the reame on his repo to get some profile examples to get the toolchain package working, that way you wouldn't have to touch your conanfile.txt

**Comment by memsharded** [comment]
Hi @sssilver 

If you are asking about conditional dependencies in a conanfile.txt, there is no syntax for it. You have 2 options:

- Have a ``conanfile.txt`` and a ``conanfile_ios.txt``, and use them accordingly ``conan install conanfile_ios.txt``
- Write a ``conanfile.py`` instead. It can be very simple, as it is for consuming only, not to create a package. Write only the recipe with the ``requirements()`` or ``build_requirements()`` methods, and do the conditinal require there based on ``platform.system()`` or ``self.settings.os_build``

**Comment by memsharded** [comment]
Closing this as stale.
The recommended way to do platform-dependent dependencies is to use a ``conanfile.py`` file with ``if`` clauses in the ``requirements()`` method.
