### ISSUE TITLE
Excessive memory usage when calling package() for large directories

### ISSUE THREAD

**Issue by mdegel** [conan-io/conan#3493]
- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Environment:**
Conan Version: 1.7.1
OS: Ubuntu 16.04 / 18.04

**Issue:**
Within conan package the `self.copy()` method is used to define, which artifacts are supposed to be copied to the conan package dir. When using `self.copy(..., src=".", ...)`, this results in the entire build directory to be scanned for the specified artifact. If the build directory is large in size, this does not only take a long time, but also seems to use an excessive amount of RAM. The latter issue may manifest itself as conan being killed by system OOM Killer, up to freezing/crashing the whole OS.

**Example Use Case:**
- Building a whole kernel + some required libs for a specific platform
- Resulting dir structure consists of several subdirs and files (in our case up to around 200.000 unique files)
- `package()` attempts to copy a generated manifest file from the root directory (build directory)
- OS (6 Cores, 8GB of RAM) goes OOM

**Probable Cause:**
As far as I was able to trace the issue down it's path, it seems like the main issue lies here:
https://github.com/conan-io/conan/blob/728c90cfdb4c510339e4da2c125c42a110718b4a/conans/client/file_copier.py#L94

The method `os.walk()` seems to have problems with large directories. It seems like this is a known issue:
https://stackoverflow.com/questions/24474172/python-os-walk-memory-issue

**Proposed solution:**
1) It doesn't make sense to scan the whole directory tree when someone wants to copy only some files from the root dir. Also it seems quite like a hassle to create a temporary dir, where the files (e.g. manifests, version files, or whatever) are created, just to avoid scanning the whole tree. Therefore I would suggest to provide the `self.copy()` the option to exclude any subdirs.

2) Since it's possible to accidently forget about the tree scanning, the path traversal should be improved so that the memory usage stays on an acceptable level. Otherwise you would have to worry about CI Servers, or Developer OS potentially crashing due to a simple oversight.

**Comment by memsharded** [comment]
Hi @mdegel 

Thanks for the investigation and the detailed report.

I am not sure I fully understood your proposed solution:

> It doesn't make sense to scan the whole directory tree when someone wants to copy only some files from the root dir. Also it seems quite like a hassle to create a temporary dir, where the files (e.g. manifests, version files, or whatever) are created, just to avoid scanning the whole tree. 

You can check in: https://docs.conan.io/en/latest/reference/conanfile/methods.html#package
There are options to:
- Start the scan in the directory you want ``src``
- Exclude the patterns you want: ``excludes``

Not sure what you meant with ``create a temporary dir``. The files are copied from the build-folder to the package-folder, directly, without temporary dirs.

> Since it's possible to accidently forget about the tree scanning, the path traversal should be improved so that the memory usage stays on an acceptable level.

You can always do your own copy, not using the ``self.copy`` functionality, e.g. ``shutil.copytree``

Could you please clarify? Thanks!

**Comment by mdegel** [comment]
As for the temporary dir:
Maybe it's an oversight on my behalf, but I'm not sure whether it's possible to `self.copy()` a file from the build dir directly without scanning the whole directory tree. I'm looking for sth. like `self.copy("my-file", dst=".", src=".", keep_path=False)` which doesnt traverse any other subdirectories within `.`, without explicitly excluding everyone of them (as it would mean, the list of dirs to be excluded need to be maintained).

Creating `my-file` in a temporary extra dir like `./extra-dir/my-file` allows me to use `self.copy("my-file", dst=".", src="./extra-dir", keep_path=False)`, which will not traverse the whole base dir. But this doesn't seem like a good solution to me.

As for the `shutil.copytree()` for custom copying, this seems like a suitable solution to me, haven't thought about that yet.

**Comment by memsharded** [comment]
> Maybe it's an oversight on my behalf, but I'm not sure whether it's possible to self.copy() a file from the build dir directly without scanning the whole directory tree

Ok, I misunderstood, I though you meant that conan was creating another extra temporary folder. No, it is not possible to copy just a file with ``self.copy()`` without scanning a tree (at least a subtree with ``src=``)

> They only help in filtering out the files someone wants. The os.walk() still traverses the whole tree.

Yes, you are right, I was confused with an internal exclusion of some folders. This seems like a feature that could be implemented to optimize the traversal. This would deserve a new dedicated issue.

But even with that optimization, I think that in your case, yes, I would use direct python copies ``shutil.copytree``, ``shutil.copy``, etc. Please let me know, if that works well for you, we could close this issue and open a new one for the optimization of exclusions.

**Comment by mbitsnbites** [comment]
My first attempt with Conan left we with an unresponsive system that eventually restarted my desktop session - thanks to the OOM killer I suppose. I'm on Ubuntu 18.04 (32 GB RAM + 32 GB swap).

My use case was to package a compiler toolchain consisting of 127974 files (7.8GB in total). Though I realize that it's a rather extreme case, I don't see why it should be a problem for Conan to handle it (and as @mdegel points out, people will probably keep trying things like this in the future).

I will try the `shutil` tricks and see if that helps for me.

**Comment by mbitsnbites** [comment]
Update: I suspect that my problems were actually related to recursive symbolic links (e.g. `foo/x/y -> ../../foo`). When using `shutil.copytree` my disk ran out of space (some 130 GB vanished) instead of getting hit by the OOM killer. Resorting to `cp -a` instead kind of solved that problem, but there were other problems with the package (>1700 symbolic links, of which many were broken), so I gave up on it for the time being (the toolchain that I want to package needs some serious fixing first).

**Comment by memsharded** [comment]
``self.copy`` has been replaced by a more focused ``copy()``, but still for huge trees, it will be slow. Recommended way will still be custom user copies with shutil or similar. Closing this as inactive.
