### ISSUE TITLE
Improve querying dependencies (introspection)

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3495]
This is an enhancement proposal.

I'd like to get requires, build_requires, and test dependencies of existing packages. This is to repackage conan packages, by adding metadata used by our current meta build system, [qibuild](https://github.com/aldebaran/qibuild/). This metadata is a simple xml file which lists the dependencies as well as their type (runtime, buildtime, testtime).

So here are the alternatives I have to repackage software existing in conan-center:
1. fork the recipe
2. use the newer python_require available since Conan 1.7.0 to extend the initial recipes
3. patching conan myself to have an option to add the metadata on `conan copy` to inject the metadata and fix the related checksums in manifests
4. use introspection features provided by `conan info` to request information about the dependencies and write an external tool to just repackage the binaries.

Do you see another way?

- Solution 1 is too much work on our side.
- Solution 2 is realistic as it requires no work on Conan's side,  but still requires one additional recipe per software to repackage.
- Solution 3 would rely on code that would not be upstreamable as qibuild is not very popular (and some think we should kill it).
- Solution 4 would be my favorite, and a feature others might want, as querying dependencies is something many packaging tools provide. It however requires some developement on the conan side.

For solution 4, here are what I see would need to be done:
- add information about the build_requires dependencies to the output of `conan info`
- add support for JSON output (`--json` currently does nothing if --build-order is not specified).
- add a new attribute to `ConanFile` to specify the dependencies needed at test time, or maybe add and standardize an option like `with_tests` or similar to be able to enable/disable all tests so we can diff what is required with or without tests and deduce the test-time dependencies.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I think your use case could be a candidate for the plugin mechanism @danimtb is working on. No need to fork conan, you might be able to extend it via some plugins.

There are no ``testtime`` dependencies, only build-requires. But they will be accessible in the plugins, cause you will have access to the conanfile.

**Comment by memsharded** [comment]
The introspection of dependencies has massively improved since then, with full access to the ``self.dependencies`` complete set of dependencies in recipes, and deployers, and with a very complete json output specifying all dependency graph, dumping lots of data. Closing this as solved.
