### ISSUE TITLE
[Question] How to combine MSYS2 and Visual Studio?

### ISSUE THREAD

**Issue by DarkMorford** [conan-io/conan#3497]
I'm using Conan 1.7.2 on Windows 10, and I'm trying to write a Conanfile to build [libogg](https://xiph.org/ogg) for this platform. The release tarball does come with a Visual Studio solution file, but as I haven't been able to find an automated way to retarget it for my installed SDK (which may just require more research) I'm trying to use the classic `./configure` and `make` pattern. I still want to use the Visual Studio 2017 compiler so the resulting library is compatible with other MSVC projects, so I'm using the MSYS2 package but not MinGW64.

I've created a gist containing my [Conanfile and build profile](https://gist.github.com/DarkMorford/cf3c983d5ea24668d16dd1081166a0be). Running `conan source .` and `conan install . --profile msys` works without a hitch. When I run `conan build .` the `configure` script is able to find the `cl.exe` compiler, but it complains because it can't find a valid linker. The specific error message is `configure: error: no acceptable ld found in $PATH`.

Is the MSYS2/MSVC combination supported by Conan? If so, what do I need to change in my Conanfile to resolve this error, and if not, how should I go about building this library? Thanks in advance.

**Comment by lasote** [comment]
Hi! it is supported but it usually requires some trick/patch in the build system scripts to make it work.
I cannot help you with that concrete example but you can take a look at the bincrafters recipes, like https://github.com/bincrafters/conan-openh264/blob/testing/1.7.0/conanfile.py and https://github.com/bincrafters/conan-ffmpeg/blob/stable/4.0/conanfile.py

**Comment by DarkMorford** [comment]
Thanks for the pointers! I played around with this over the weekend, and while I couldn't find an option like `--toolchain=msvc` that the `configure` script would accept, I was able to get it to recognize the Visual Studio linker by setting the environment variable `LD=link.exe`. Unfortunately, during the build step it broke because it couldn't find `ar` to put the static library together, and I was unable to find a similar workaround.

In the end, I found out that the git repository for libogg contains a `CMakeLists.txt` file (which for some reason isn't in the release tarballs), so I changed my Conanfile to check out the appropriate tag from the repo and build the library with CMake. It seems to be working well on my Windows 10 machine, now I just need to figure out how to do it on other Windows versions and Linux/macOS...

**Comment by memsharded** [comment]
Closing this ticket as outdated.

There are now many hundreds of recipes for popular open source libraries in ``conan-center-index`` Github repo for ConanCenter that uses ``msys2`` as ``tool_requires`` to build, that should be a good reference. Also, don't hesitate to open new tickets if you have an further question
