### ISSUE TITLE
[Question] Could "path_shortener" redirect to a deterministic folder?

### ISSUE THREAD

**Issue by aledeganopix4d** [conan-io/conan#3502]
Hello,
In my team we use Conan as part of a CI system that builds on different platforms (among which Windows).

We're encountering some issues using a **compiler cache** in Windows when our sources includes from Conan packages using the `short_paths=True` option.

We've pinpointed the reason to the fact that the function `conans.util.windows.path_shortener` places the files with a long path in a **temporary directory**. The temporary directory name is (obviously) different between different Windows workers of our CI and thus the compiler cache (that takes into account the full path of the includes) doesn't work as expected (cannot reuse binaries compiled in different workers).

We have indeed verified that enabling long paths in our Windows Server CI workers and setting `CONAN_USER_HOME_SHORT` to `None` solves our caching issue, but we feel it's a workaround that we'd avoid if possible.

So, back at the question: the above issue would easily go away if `path_shortener` would redirect to a deterministic folder (e.g. `C:\.conan\<package_id>`) instead of a new random folder name. Do you think that it would work? Would that break anything as far as you know?

My team and I are of course willing to contribute with a PR once it's clear what is possible and what not.

Thank you!

**Comment by lasote** [comment]
Hi!
`C:\.conan\<package_id>` wouldn't be valid because the <package_id> is many times the same between different conan recipes. And even probably too long to avoid the issues.
If we could find some unique, deterministic (and very short) pattern probably it could work.

**Comment by aledeganopix4d** [comment]
Thanks for your answers!
One more thing: is it possible to configure system-wise the Conan client to always default `CONAN_USER_HOME_SHORT=None` other than setting it as an environment variable?

**Comment by aledeganopix4d** [comment]
Oh, sorry, I found it myself!
Apparently is `user_home_short` in the General section of the configuration file.
