### ISSUE TITLE
cmake_find_package include directories are currently not set as system

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan#3507]
Generated FindXXX.cmake has
```
if(XXX_INCLUDE_DIRS)                                                    
set_target_properties(XXX::XXX PROPERTIES                             
INTERFACE_INCLUDE_DIRECTORIES "${XXX_INCLUDE_DIRS}")                  
endif()
```

The problem with this is the consuming project can't enable stuff like `-Werror` unless the package is warning free. Fix is to use `INTERFACE_SYSTEM_INCLUDE_DIRECTORIES`.

Conan version 1.6.1

**Comment by Ignition** [comment]
Yes

**Comment by lasote** [comment]
Something new or this can be closed?
