### ISSUE TITLE
Move validations out of ConanFileReference class.

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3509]
- [x] Conan 1.7.3

Each time a ConanFileReference is instantiated, all validations are performed (several regex and type checking), even though they have been already validated: internal data, response from APIs,... and this happens a lot of times while evaluating the dependencies graph.

So these validations can be moved to Conan inputs when the reference string is first read into the Conan ecosystem. This can contribute to performance.

**Comment by jgsogo** [comment]
An easy implementation would be to make validation optional (`True` by default), so we can avoid calling to it from places where we know that the fields are valid. It would require little changes in `ConanFileReference` and `PackageReference`, like the ones proposed in this branch: https://github.com/jgsogo/conan/tree/engineering/3509. 

...but, knowing where the reference is valid and where it may not requires a deep understanding of Conan itself.

**Comment by memsharded** [comment]
Yes, I think it is a good initial iteration, low risk. Start checking where the validation is not required, and slowly change them to False. Once it is stabilized, we could really refactor and clean it.
