### ISSUE TITLE
Conan 0.10.0 detected as threat by Symantec Antivirus

### ISSUE THREAD

**Issue by raulbocanegra** [conan-io/conan#351]
Hi guys,
First of all, thank you for your work, you are doing great!
I'm having an issue with Symantec antivirus and Conan after updating to 0.10.0.
I already had an issue with 0.9.2 that I reported on Twitter. The issue seemed to be fixed in 0.9.4.
I updated to 0.10.0 yesterday and this is the message Symantec antivirus reports:

![conansymantecissue](https://cloud.githubusercontent.com/assets/15945679/16515416/2a89ce98-3f72-11e6-853b-d0da1284ec12.png)

![symantectrojaninfo](https://cloud.githubusercontent.com/assets/15945679/16515417/2a8a2b68-3f72-11e6-8e45-d13bec9ef768.png)

[Symantec website](http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2015-030621-4330-99&vid=4294921184) says: "suspicious network traffic".

I will install 0.9.4 again to keep going on. I just wanted to let you know.

I'm using Windows 7 and MSVC 2015.

Thanks!

**Comment by memsharded** [comment]
Hi Raul!
Many thanks, and thanks too for reporting again. The thing is that it seems to be a bit random, I guess that it is an heuristic detection based on some patterns, and it might change from version to version. Reporting to AV vendors is a waste of time. Another possible way is to sign the binaries, but that requires a lot of money... I suggest to install it via pip, I think it is the most used approach. It will be easy, just take a few minutes, I can help if you want. And you will get python, very, very useful :)

Conan 0.10 has quite a few improvements, fixes and new features, so I'd suggest trying to upgrade to it.  Thanks for your help!

**Comment by raulbocanegra** [comment]
Thanks! 
Just installed conan via pip and problem solved.

**Comment by memsharded** [comment]
Excellent, thanks very much!
