### ISSUE TITLE
CMake helper to get CTest to output on failure

### ISSUE THREAD

**Issue by cjdb** [conan-io/conan#3511]
I'd like to be able to configure my `conanfile.py` so that I can invoke `ctest --output-on-failure` in some fashion. After chatting with on cpplang.slack.com, it was noted that it doesn't look like this is currently possible, and so I'll need to invoke this manually.

Is such a feature on the roadmap, and if not, could it please be added in a future release?

**Comment by memsharded** [comment]
I don't know much about this ``ctest --output-on-failure``, but it might be possible, as some arguments to ``cmake.test()`` method, or maybe as another ``cmake`` method. What is the current workaround, can you provide a full working ``build()`` method with a custom ``self.run("ctest ...`` or whatever to give an idea of the feature? Thanks!

**Comment by cjdb** [comment]
Right now, my workaround is to run this on the command line after `conan
build .. --build`:

```bash
ctest -j `nproc` --output-on-failure
```

**Comment by memsharded** [comment]
Hi @cjdb 

Why not something like this?

```python
def build(self):
    cmake = CMake(self):
    cmake.configure(...)
    cmake.build(...)
    if self.should_test:
        self.run("ctest -j `nproc` --output-on-failure")
```

Then you can run it with:
```bash
$ conan build .. --build
$ conan build .. --test
```
Current implementation of ``cmake.test()`` is ``cmake --build . --target RUN_TESTS`` (or ``--target test`` depends on the build system), so it seems too different to be re-purposed for calling ``ctest``.

What do you think?

**Comment by cjdb** [comment]
I like it!

I understand that Conan can invoke parallel builds with build systems such
as `make` (which are not parallel by default).

Does this happen for testing too? `nproc` is a Unix tool for getting the
number of processors, and I think that will inhibit usage on Windows
systems.

**Comment by memsharded** [comment]
> I understand that Conan can invoke parallel builds with build systems such
as `make` (which are not parallel by default).

Yes, the built-in build helpers, like MSBuild(), CMake(), AutoToolsBuildEnvironment already implement calling the build systems in parallel (check ``parallel=True`` argument default value in their constructor), and will map to the right -j, /MP build system arguments. It will be using the ``tools.cpu_count()`` function, which will detect the number of processor in a portable way, but is also configurable in ``conan.conf``, so the user can decide if they want all their cores to build. 

I would recommend using it also in your scripts, as ``nproc`` might be a bit aggressive for users that want to leave some cores free to keep working while installing and building conan packages. Besides, it is not portable, as you pointed out, so it won't work in Windows.

**Comment by SSE4** [comment]
from the [doc](https://cmake.org/cmake/help/v3.13/manual/ctest.1.html):
```
--output-on-failure
Output anything outputted by the test program if the test should fail. This option can also be enabled by setting the CTEST_OUTPUT_ON_FAILURE environment variable
```
it means we can just set `CTEST_OUTPUT_ON_FAILURE` environment variable
