### ISSUE TITLE
Run cmake wrapped with scan-build

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#3512]
I would like to be able to run cmake wrapped with clang's scan-build to perform a static analysis while building. However the CMake class hard-codes the name of the executable to be 'cmake'. It would be great if it were possible to override this.

**Comment by sigiesec** [comment]
Ok, I see a workaround: I can use the "helper attributes" approach as described under https://docs.conan.io/en/latest/reference/build_helpers/cmake.html.

**Comment by lasote** [comment]
We could also add a `CONAN_CMAKE_PROGRAM` (similar to the current CONAN_MAKE_PROGRAM)

**Comment by sigiesec** [comment]
A CONAN_CMAKE_PROGRAM option (?) sounds good as well, and is probably more consistent.

**Comment by lasote** [comment]
> A CONAN_CMAKE_PROGRAM option

An entry in the `conan.conf` /  `environment variable`
