### ISSUE TITLE
Find libtool when run tools.XCRun

### ISSUE THREAD

**Issue by zhuhaow** [conan-io/conan#3514]
libtool on Mac (which has nothing to do with GNU libtool) is used to replace ar and ranlib for creating fat binaries on OS X and iOS. 

Some packages, e.g., boost, expecting libtool as the archiver instead of ar when building for iOS. 

In cross compiling profile, such as https://github.com/theodelrieu/conan-darwin-toolchain/blob/release/1.0/conanfile.py, the env variable `AR` is set to `ar` and later the boost package will pick that up https://github.com/conan-community/conan-boost/blob/6b6a3c9bc8f07824ec3932422c9ba14311707c48/conanfile.py#L252 which will set the archiver to `ar` where the build will fail as the building script expect `libtool`.

We also need `libtool` for creating fat binary (which I think is under discussion).

**Comment by lasote** [comment]
So, in addition to #3515, Which changes would be necessary to the @theodelrieu darwin toolchain and the conan-community boost recipe?

**Comment by zhuhaow** [comment]
Hard to say, since there is no common env variable to hold the path to libtool (there is no POSIX standard for it), it would be a little strange if Darwin-toolchain define that without consensus from conan maintainers.

As for conan-boost, the logic of boost jam default build script on Darwin for iOS uses libtool as default archiver, but conan-boost wants to set the archiver for boost build if AR is defined which leads to build failure.

A reasonable workaround is simply do not use AR/RANLIB env if we are building for iOS, which is odd but should always work. Other way is to use some env variable define the libtool to use, this requires conan defines a new env libtool in conan community I think.

**Comment by lasote** [comment]
Sounds good, could you open an issue at the boost recipe repository? I think we should close this.
