### ISSUE TITLE
Shared link flags exposure in Cmake not as expected [question]

### ISSUE THREAD

**Issue by spiderkeys** [conan-io/conan#3518]
**Conan Version:** 1.7.1
**Summary:** CONAN_SHARED_LINK_FLAGS does not contain individual cpp_info.sharedlinkflags settings from dependencies.

I have an executable package, let's call it Alpha, which depends on library package Beta, which depends on library package Charlie, and Charlie specifies some shared link flags.

In Alpha's cmake configuration process, CONAN_SHARED_LINKER_FLAGS_CHARLIE_LIST properly contains the values specified in Charlie's cpp_info.sharedlinkflags, but CONAN_SHARED_LINK_FLAGS, which I expected to be an aggregate of all shared link flags from its dependencies, is empty. 

I was told that this may be a bug in the Conan slack channel, but if that ends up not being the case and things are working as intended, it would be great to gain a better understanding of how these settings and variables are intended to be used.

**Comment by memsharded** [comment]
Hi @spiderkeys !

I have reproduced your scenario in a test in: https://github.com/conan-io/conan/pull/3521/files

As you can see, the check is done:

```python
self.assertIn('set(CONAN_SHARED_LINKER_FLAGS '
                      '"CharlieFlag BetaFlag ${CONAN_SHARED_LINKER_FLAGS}")', cmake)
```

Could you please verify your ``conanbuildinfo.cmake`` file? Is it possible that there is some typo somewhere, like ``CONAN_SHARED_LINK_FLAGS`` instead of ``CONAN_SHARED_LINKER_FLAGS``?
Thanks for the feedback!

**Comment by spiderkeys** [comment]
D'oh, that was it (LINKER vs LINK). It looks like I got thrown off by the naming convention in the cpp_info section vs the CMake variable name (cpp_info uses the parameter name "sharedlinkflags"). The CMake docs state the correct CMake variable name, so it's just a matter of me getting things jumbled up comparing the two different pieces of documentation. Thanks for looking into it!

**Comment by memsharded** [comment]
Hi @spiderkeys 

No problem :) Happy that the issue has been solved now. Cheers!
