### ISSUE TITLE
Feedback when conan export removes old sources

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#352]
When doing a ```conan export channel``` of an already existing package, the previous package source content gets removed in the process. However, there is no indication of this process on the command line, which results in long waiting times without feedback when removing the content of big packages (e.g. Qt).

**Comment by lasote** [comment]
You can use the -k option (--keep-source) to prevent the source remove.
What's your proposal? some process indication message can be enough?

**Comment by Blubbz0r** [comment]
Didn't know about the -k switch. That's nice!

At least a message that the source is currently being removed would be nice. Optimally with progress indication, but I don't think that this is absolutely necessary.

**Comment by lasote** [comment]
Related with #353, It can be done together.

**Comment by memsharded** [comment]
Added a message (progress bar would be too much). But the important thing is that I have improved the whole process, checking for dirty source folder and acting accordingly.

**Comment by memsharded** [comment]
A new treatment of the sources folder has been released in 0.11, giving more feedback and messages, and improvements when the source directory is "dirty", e.g. interrupted downloads or git clones, or mistakes in the package recipes.
