### ISSUE TITLE
How to handle Visual Studio 2017 minor version incompatibilities?

### ISSUE THREAD

**Issue by Framnk** [conan-io/conan#3520]
Microsoft recently released update version 15.8 for Visual Studio 2017 which creates an incompatibility with release mode libraries compiled using Visual Studio 2017 15.7.x when 'whole program optimization' is enabled.

This means that if a project being compiled with VS2017 15.8 links against a Conan package with release mode libraries created with VS2017 15.7, they will fail with linker errors.

How can we handle this using Conan?  It seems that for Visual Studio only 'major' version numbers can be specified (12, 14, 15, etc) when creating packages?

More info [here](https://developercommunity.visualstudio.com/content/problem/316532/c1047-after-update-from-157-to-158.html)

**Comment by memsharded** [comment]
There are several issues with the VS minor updates:

- It cannot be "selected". It is defined by the installation. Once updated you cannot revert back. That means, it is not really a "setting", it is not something that could be defined at the user level. 
- So far, the compatibility moving forward has been good enough. This is the first case of such an incompatibility has been reported. Could you please report which conan package or packages are failing to link in that scenario?
- There is no official "policy" from MSFT, or at least that I am aware. In theory it was going to be compatible even with VS 14, but that promise seems broken now.

It also depends a lot of what is the scope of the package. I would recommend:

- For public, open-source packages in conan-center and other bintray repos, leave the settings as-is. Updating to latest VS update is compulsory. Once a linking incompatibility has been identified on a given package, report it, so package maintainers fire a new build with the latest VS update.

- For private packages, if accurate tracking of what update is being used, it is necessary to model the subsettings in the ``settings.yml`` file (remember that file can be shared, and reused with ``conan config install``). Make sure the profiles being used match the used VS update.

**Comment by Framnk** [comment]
Thanks for the response.  This Conan package is a private dependency of ours that was failing to link for a new developer who came on board and just happened to be on the latest VS2017 service pack.

I agree that this is mostly a Microsoft problem as they do not seem to be handling these updates very well.  It would be helpful to be able to specify the SP level of Visual Studio at install time and/or allow downgrading to a previous service pack.

**Comment by memsharded** [comment]
> It would be helpful to be able to specify the SP level of Visual Studio at install time and/or allow downgrading to a previous service pack.

Yes, that would help a lot. Personally, I think the only sane thing now might be to make sure everybody is updated to the latest update, and the package binaries are re-built in CI once the new updates are installed. The above suggested approach of modeling the update as a "subsetting" is the "formal" solution, but in practice it doesn't fully solve the problem, because it is not possible to downgrade to a given update. So making sure everybody(including CI servers) are moving forward to latest udpate is probably the most pragmatic approach. Best luck!
