### ISSUE TITLE
Define policy for conan vs user ConanFile attributes and methods

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3526]
To reduce possible future collisions when things are added to conan.
E.g.:

- Use "_myattribute" for user defined attributes. Conan reserves all public members
- Use "__myattribute" for user defined atributes. (What happens for inheritance via python_requires?)
- Etc.

**Comment by lasote** [comment]
Open a new one in`docs` to document the policy?

**Comment by memsharded** [comment]
Summary of decisions:

- Public methods and attributes are reserved for conan tool. Users cannot use them in their recipes.
- "Protected" attributes and methods for conan are prefixed with ``_conan_``, and that prefix shouldn't be used by users either.

It is necessary to change the conan source code of protected attributes, before publishing the policy in the docs.
