### ISSUE TITLE
Possibly inconsistent status after conan export

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#353]
When I use ```conan export channel``` for a package for which a script already exists, conan will update the previous script and remove its source content. However, updating the conanfile.py seems to be happening before the source removal. This results in a bit of a weird status in case the removal of sources fails (e.g. a command line is still lingering around in the respective path): The operation fails, but it is also not possible to run ```conan export channel``` again, since the conanfile is already updated. Not sure though if this can cause any problems down the road yet.

**Comment by lasote** [comment]
Yes, actually It happened to me (with some impulsive Ctrl+C) sources keeps dirty, exports says that nothing has been changed and package build fails.
An easy feature could be alert the user with an error message if it happens, telling that the source folder xxxx/yyy/zz  has to be deleted by hand.

**Comment by Blubbz0r** [comment]
Yes, clear instructions would be completely suitable.

**Comment by memsharded** [comment]
Yes, I totally agree about this issue. It sometimes happen that some download or git clone is interrupted and the source folder is left in bad state, with weird behavior if you don't remember to remove it. In https://github.com/conan-io/conan/pull/361 PR, a better management of this is done. Thanks for pointing out this issue!

**Comment by memsharded** [comment]
A new treatment of the sources folder has been released in 0.11, giving more feedback and messages, and improvements when the source directory is "dirty", e.g. interrupted downloads or git clones, or mistakes in the package recipes, with automatic recovery/repeat of the source() method for a good state.
