### ISSUE TITLE
Improve download traces 

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3530]
The download traces are pretty much useless. 

Here's an example where I'm told a file is downloaded, but not for which package.
This should really be prefixed by the package name like other traces.

```
qilang/0.1@sbre/testing requirement libqi/1.5.0@sbre/testing overridden by libalmath/0.1@sbre/boost-1.68 to libqi/1.6.0@sbre/testing 
qilang/0.1@sbre/testing requirement boost/1.64.0@sbre/testing overridden by libalmath/0.1@sbre/boost-1.68 to boost/1.68.0@conan/stable 
eigen/3.3.5@conan/stable: Not found in local cache, looking in remotes...
eigen/3.3.5@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt

Downloading conanfile.py

Downloading conaninfo.txt

Downloading conaninfo.txt

Downloading conaninfo.txt

Downloading conaninfo.txt

Downloading conaninfo.txt

Downloading conaninfo.txt

Downloading conaninfo.txt

Downloading conaninfo.txt

Downloading conaninfo.txt

Downloading conaninfo.txt


```

Now another example: here there are way too many blank lines, adding visual clutter. Those blank lines are not even on package boundaries, adding to the confusion when you try to read what happened to a package.
One simple fix is removing those spurious blank lines. If you want to improve things further, add a blank line on package boundaries (i.e. when the package changes).

This may seem by some as nitpicking, but when you have to read CI logs every day, knowing where one package logs start and end should be a no-brainer.

```
bzip2/1.0.6@conan/stable: Retrieving package ce1f8ff23addde793223a2a82ed7fe355c57a589 from remote 'conan-center' 
Downloading conanmanifest.txt

Downloading conaninfo.txt

Downloading conan_package.tgz

bzip2/1.0.6@conan/stable: Package installed ce1f8ff23addde793223a2a82ed7fe355c57a589
eigen/3.3.5@conan/stable: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'conan-center' 
Downloading conanmanifest.txt

Downloading conaninfo.txt

Downloading conan_package.tgz

eigen/3.3.5@conan/stable: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

```

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by liberforce** [comment]
The blank lines are due to the download progress bar, that don't appear in logs.

**Comment by memsharded** [comment]
CLI output is completely new in 2.0, closing this as outdated.
