### ISSUE TITLE
Add progress bars to improve UX

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3536]
A progress bar will indicate the user that something is running and he must wait until completion. Some operations in Conan can take a long time (uploading, unzipping,...) and the user can Ctrl+Break it if there is no feedback.

We may develop/reuse a progress bar component (even for parallel jobs) that could be used anywhere inside Conan. This component may replace also existing code.

Here it is a list with the places where a progress bar can fit (list updated with comments):

**Comment by jgsogo** [comment]
A ready to use solution can be **tqdm** (https://github.com/tqdm/tqdm), license is MIT/MPLv2.0. It even has a concept of _nested progress bar_ with an example using threads [here](https://github.com/tqdm/tqdm#nested-progress-bars). Need to check further.

**Comment by lasote** [comment]
Does tqdm manage multiple bars at the same time?

**Comment by jgsogo** [comment]
Yes, just run this example:

```python
from time import sleep
from tqdm import trange, tqdm
from multiprocessing import Pool, freeze_support, RLock

L = list(range(9))

def progresser(n):
    interval = 0.001 / (n + 2)
    total = 5000
    text = "#{}, est. {:<04.2}s".format(n, interval * total)
    for i in trange(total, desc=text, position=n):
        sleep(interval)

if __name__ == '__main__':
    freeze_support()  # for Windows support
    p = Pool(len(L),
             # again, for Windows support
             initializer=tqdm.set_lock, initargs=(RLock(),))
    p.map(progresser, L)
    print("\n" * (len(L) - 2))
```

**Comment by lasote** [comment]
That's pretty cool!

**Comment by memsharded** [comment]
I think I'd run a small test first, to try if this library could work, in 1.8, before doing a bigger investment in changing
I would first add a decompresser progress bar for conan_package.tgz unzip while installing. Important to check what is the output in CI, and other environments without \r management.

**Comment by jgsogo** [comment]
``tqdm`` is being used in released version v1.8, if no issues are reported, let's go ahead with this! 💪

**Comment by jgsogo** [comment]
Sure, although I think that ``conan search`` makes just one call to the server and then waits for the response, no callbacks... so it will be hard to know how long will it take or which ``%`` the progress bat should show. Any idea on this?

**Comment by KristianJerpetjon** [comment]
We are running a conan_cmake_run within cmake that downloads several files the first time it's in use. 
this can take up to several minutes on a laptop so a progress bar would be nice :)

**Comment by jgsogo** [comment]
Hi! We haven't forgotten about this, but there are some other things that are grabbing our attention and priority queue. We need to start working on this almost from scratch since #3608 is so conflicted that it is worth starting over and divide it into several PRs. Thanks for commenting here, I'll assign some labels to it, and I will try to have another look at it by the end of this year.
