### ISSUE TITLE
Trying to run Artifactory CE in a docker container (Win 10 in hybrid mode)

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#3546]
Ok a bit on the edge here, but what the heck.

So I have a Win 10 machine running dockers. When it is set to Linux containers the Artifactory CE image loads and the server starts. (never let it finish setting up, but it had a pulse)

I know switched to Windows containers and toggled on experimental mode, which gives me access to Linux containers on Windows. I tried the unbuntu image in interactive mode and yup it worked.

Then I tried:
docker run --platform --name artifactory_ce  -d -p 8083:8081 -e EXTRA_JAVA_OPTIONS=-Xmx8g docker.bintray.io/jfrog/artifactory-cpp-ce

and yes I wanted to map host port 8083 to Artifactory's 8081.

My container dies with an error: Error max number of open files is 1024, is to low.

So reading the doc I try:
--ulimit nofile:4000,4000

but no love. Unsupported option in hybrid mode.

Then I tried 
--priviliged
rejected again .... Windows does not support privileged mode.

So the question is can Artifactory CE live in a space with say 1000 open files (24 as spares)

Thanks
Carl

**Comment by lasote** [comment]
I'm sorry I can't help you, I didn't experience with Docker containers and Artifactory CE. @markgalpin any suggestion about where to raise this question?

**Comment by ShamanTcler** [comment]
Thanks for the reply. I am bringing up a conan/jenkins machine... should be a nice one. 20 cores 64gb Ram and 1 TB ssd. My hope was to run everything in dockers keeping the Win 10 pro machine as clean as possible.

If I recall I got the docker image to run when I was in just Linux containers, but hybrid mode just didn't allow that many files open. 

So no big deal to artifactory ce in "normal" mode, straight from windows.

Thanks again.

**Comment by markgalpin** [comment]
You could also build a windows container for artifactory CE with the zip install...

I will discuss with the team whether we can adjust the minimum required ulimit for artifactory, although I know that generally we are not fans of doing this.  That check exists for a reason.

**Comment by markgalpin** [comment]
Add `-e MIN_MAX_OPEN_FILES=1000` (default MIN_MAX_OPEN_FILES is 10000). This will bypass the check that fails the entrypoint. Note that for Artifactory to work well, we do recommend using higher values…

**Comment by jgsogo** [comment]
Hi, @ShamanTcler , any news about this, were you able to run Artifactory CE? Thanks!

**Comment by ShamanTcler** [comment]
Just getting back to it... I had to disable Docker (Hyper-V) as it was breaking skype. 

But found a fix with Hyper-V ... 
https://social.technet.microsoft.com/Forums/lync/en-US/7687ca88-5a53-4031-b1ff-dceba58dec35/skype-for-business-desktop-sharing-doesnt-work-when-hyperv-is-installed?forum=sfbfr

**Comment by vvenkateshgupta** [comment]
I am getting this error . Could anyone help me fix it? I tried the -e MIN_MAX_OPEN_FILES=10000, but no luck.. 

[ec2-user@ip-172-31-53-203 tmp]$ sudo docker run --name artifactory -p 8081:8081 docker.bintray.io/jfrog/artifactory-cpp-ce:latest
2019-09-04 14:49:53  [485 entrypoint-artifactory.sh] Preparing to run Artifactory in Docker
2019-09-04 14:49:53  [486 entrypoint-artifactory.sh] Running as uid=1030(artifactory) gid=1030(artifactory)
2019-09-04 14:49:53   [49 entrypoint-artifactory.sh] Dockerfile for this image can found inside the container.
2019-09-04 14:49:53   [50 entrypoint-artifactory.sh] To view the Dockerfile: 'cat /docker/artifactory-cpp-ce/Dockerfile.artifactory'.
2019-09-04 14:49:53   [55 entrypoint-artifactory.sh] Checking open files and processes limits
2019-09-04 14:49:53   [58 entrypoint-artifactory.sh] Current max open files is 1024
2019-09-04 14:49:53   [39 entrypoint-artifactory.sh] ERROR: Max number of open files 1024, is too low. Cannot run Artifactory!

**Comment by jgsogo** [comment]
What is the output you get when you use the environment variable?

```bash
sudo docker run --name artifactory -p 8081:8081 docker.bintray.io/jfrog/artifactory-cpp-ce:latest -e MIN_MAX_OPEN_FILES=1000
```

**Comment by 19317362** [comment]
I am getting the same error when I try to run this image in WSL2.
After adding the -e , it can run not.
Thanks for your help!

Util now, with WSL2, I can not change the ulimit -n for non-root user.
The command look like this.

docker run --name conan_svr -e MIN_MAX_OPEN_FILES=1000 -v szcode1:/var/opt/jfrog/artifactory --restart=always -d -p 8081:8081 docker.bintray.io/jfrog/artifactory-cpp-ce:latest

**Comment by lasote** [comment]
Just in case, you know that you can run Artifactory in the native Windows, right?

**Comment by ShamanTcler** [comment]
Yes I am running Artifactory CE native and have been doing so since this
was posted. I really need to get back to trying this again with the newer
dockers. If you want to close this you have my blessing.

Now all I have to do is upgrade it .... you always dread upgrades, don't
you?

Regards
Carl

**Comment by memsharded** [comment]
Closing this ticket as outdated. I think docker-windows support for running ArtifactoryCE is not available anymore (if it ever was), it seems it has to run in a Linux containers.
