### ISSUE TITLE
Issues in building and uploading to Artifactory with conan 1.7.3

### ISSUE THREAD

**Issue by AmitJain001** [conan-io/conan#3549]
Today I upgraded to conan 1.7.3 to avail the feature of "cppstd" settings, as I am planning to use C++14gnu standard.

Got 2 issues :
1. Build issue : Tried to create a new "Hello" package which is default to conan. Got the following error message :
Hello/0.1@demo/testing: Generator cmake created conanbuildinfo.cmake
Hello/0.1@demo/testing: Calling build()
sh: cmake: command not found
Hello/0.1@demo/testing:
Hello/0.1@demo/testing: ERROR: Package '7d02dc01581029782b59dcc8c9783a73ab3c22dd' build failed
Hello/0.1@demo/testing: WARN: Build folder /user/home/.conan/data/Hello/0.1/demo/testing/build/7d02dc01581029782b59dcc8c9783a73ab3c22dd
ERROR: Hello/0.1@demo/testing: Error in build() method, line 28
        cmake.configure(source_folder="hello")
        ConanException: Error 32512 while executing cd '/user/home/.conan/data/Hello/0.1/demo/testing/build/7d02dc01581029782b59dcc8c9783a73ab3c22dd' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="4.4" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/user/home/.conan/data/Hello/0.1/demo/testing/package/7d02dc01581029782b59dcc8c9783a73ab3c22dd" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev '/user/home/.conan/data/Hello/0.1/demo/testing/build/7d02dc01581029782b59dcc8c9783a73ab3c22dd/hello'

2. Tried to package and upload a pre-built Boost library to Artifactory. Gto the following error :
Uploading boost/1.57.0@build/stable to remote 'third.party-repo'
ERROR: Not implemented endpoint. [Remote: third.party-repo]

The same Artifactory repo was working perfectly when used with conan 1.7.0. 

Please help !

**Comment by AmitJain001** [comment]
Got the reason for cmake. in my shell profile, cmake is set as alias. Had to set that in PATH to make cmake work. Interestingly, the alias was working perfectly fine with conan 1.7.0, though.

Still struggling with conan upload. Please help.

**Comment by memsharded** [comment]
Hi @AmitJain001 

I would say that something was corrupted in your conan cache.

Could you please post here the output of ``conan remote list``? Also what it is inside the ``registry.txt`` file inside your conan cache (<userhome>/.conan). Try resetting the remote (``conan remote`` commands), and try again. 

If you downgrade in that machine to 1.7.0, it is working fine? What are the version of Artifactory that you are using?

Regarding the ``cppstd`` subsetting, take into account that you might need it only if you want to use other standard than the defaults, or model different binaries built with different standards. So, if you are using a compiler which default is already gnu14, or you hardcode it all the way in your build system, then it is not necessary to model it.

**Comment by memsharded** [comment]
If that doesn't help, consider also writing us to info@conan.io, we could try to connect via chat (we are in CppLang slack, for example) to try to help investigating this issue. So far, checking with Artifactory CE 6.3 and Conan 1.7.3, seems working fine here.

**Comment by AmitJain001** [comment]
Thanks @memsharded ! I sent mail to info@conan.io with all the details, keeping Jfrog support team in loop.

**Comment by memsharded** [comment]
I am just thinking, it is possible that the remote name is not correctly interpreted due to having a dot? Could you please try using a remote name with ``third_party`` instead of ``third.party``?

Though if it works in 1.7.0, I have no idea yet why it is failing in 1.7.3. I have checked the diff between those versions, and there is nothing that affects uploads at all. If possible, please try to double check that downgrading to 1.7.0 still works in the same machine that 1.7.3 is failing. Many thanks!

**Comment by AmitJain001** [comment]
Hi James,

I get the same error when I use another remote "conan-test". Also, my previous copy of conan 1.7.0 also gets the same issue. 

Could you please tell me how I can install conan 1.7.0 using pip command ?

Much appreciate your help !!

**Comment by memsharded** [comment]
Sure, please try:

```bash
pip install conan==1.7.0 --upgrade
```

**Comment by AmitJain001** [comment]
Thanks @memsharded !
I am getting the same issue with 1.7.0 now. However, when I compared the conan.conf file which I have from old copy with the newly downloaded conan generated conan.conf, I see that there are more lines added ( although as comment ). Also, the conan 1.7.0 has got cppstd in settings.yml as well, which is supposed to be there only from 1.7.3 and above. Is there a way I can get the exact old conan 1.7.0 ?

**Comment by memsharded** [comment]
You can remove the ``<userhome>/.conan`` folder completely, files will be regenerated by the 1.7.0 source code.

**Comment by HendrikSchall** [comment]
I tried to evaluate Conan for future use in my projects, but the second error always occurs for me too ("ERROR: Not implemented endpoint.").

Tried with both 1.7.3 and 1.7.0

I have Artifactory CE running as a docker container on my local Ubuntu 16.04 VM. Installed Conan with pip3/python 3.5.2

**Comment by memsharded** [comment]
Hi @HendrikSchall 

Yesterday we were sorting out with @AmitJain001 , and their issue was a network related, one, basically a proxy configuration. It was solved with a proper ``no_proxy_math`` configuration in ``conan.conf``.

I think it is better if you could please open a new issue for your case, as I am going to close this one as consider it as solved. You can also try to contact us in our email or in the slack channel, this kind of issue is often some specific configuration that is debugged more quickly if doing it interactively via chat or the like. Thanks!

**Comment by HendrikSchall** [comment]
Setting no_proxy_math to my http://localhost:8081 (artifactory) did the trick for me too. Thanks!

**Comment by memsharded** [comment]
Great! Thanks for telling @HendrikSchall. There was a typo in my above comment, I have fixed it and this is the docs, for other users reference: https://docs.conan.io/en/latest/reference/config_files/conan.conf.html#proxies
