### ISSUE TITLE
Conan should inform about not being able to find packages in remotes

### ISSUE THREAD

**Issue by mdegel** [conan-io/conan#3556]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Environment:**
Conan Version: 1.7.3
OS: Ubuntu 18.04
Server: Artifactory 6.3.3

**Issue:**
Conan does not inform the user about not being logged in. This prevents the user from actually figuring out, why no conan packages could be resolved.

**Example Use Case:**
Artifactory has a private conan repo, which is only available, when logged in. Accessing it whilst not logged in (anonymous) is not possible.

1) conan create ...
    - Error due to build requirements not being resolved
2) conan search -r all / conan search -r remote
    - Console says "There are no packages"

**Proposed solution:**
Since there could be multiple repos, which may or may not be used together, raising an error wouldn't be the way to go. However silently ignoring the information about not being able to find packages in remotes is somewhat annoying when searching for the issue thats causing it. Therefore I would suggest to inform about said state when searching for packages, like:
```
user@host:~/some/path$ conan search -r all
INFO: remote1 is not logged in, skipping...
There are no packages
```

**Comment by jgsogo** [comment]
This is something to look into in order to provide meaningful information to the user. Thanks for reporting it!

**Comment by sdmg15** [comment]
Hello,
Here is the approach I will take for this issue 

- When using `conan search <pattern_or_reference> -r all`  will loop over all available remotes and check if it requires the user being authenticated and then display the message `INFO: remove1 is not logged in, skipping ...`

- For `conan search <pattern_or_reference> -r  <remote>` is more "easier" just check if <remote> requires authentication and display the message. 

For the check for authentication I think after making a request to the host and if it requires authentication the HTTP code return  will be `401 unauthorized` so I think if I check the returned HTTP code it can do the trick ?

**Comment by jgsogo** [comment]
Great! Thanks for the interest to contribute to our project 🎉 

First of all, check the current behavior as this issue is quite old and Conan has changed a lot since then. Also, take into account that remotes could be enabled/disabled since v1.19 (https://github.com/conan-io/conan/pull/5623).

Waiting forward to see your pull-request.

Thanks!

**Comment by jgsogo** [comment]
Thanks for having a look at it! 👍
