### ISSUE TITLE
[question] conan download fails in load_script

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#3557]
I have a package whose conanfile.py is no longer loadable in conan 1.7 (worked in <=1.6), due to a mistake on my part and a change to the ConanFile base class (exports is initialized to None in 1.7, previously it was simply missing by default; I accounted for hasattr() initiallyh being false when concatenating additional exports, but not for self.exports being present and NoneType.

This of course means depending on the old version of my package is just broken; I don't really care about that (it was an 0.1 version that was immediately fixed and replaced). But even with a fix uploaded, this caused a script that just uses conan download/conan upload to copy files between remotes to fail, since conan download of the old version errors out.

I can just delete the bad version from artifactory if that's the only solution. But I'm surprised that conan download would evaluate the recipe at all (I can't think of anything it would be getting out of it, since it ignores settings, package_id, etc). I'm not sure how it trying to load the recipe will interact with the experimental new [python_requires](https://docs.conan.io/en/latest/reference/conanfile/other.html#python-requires), since  conan download does not follow other requirements. So I thought I should at least file a `[question]` with this oddity in case it spurred any other thoughts...

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
> I can just delete the bad version from artifactory if that's the only solution. But I'm surprised that conan download would evaluate the recipe at all

Yes, the evaluation of the recipe is necessary, for example, if ``short_paths`` is active in the recipe, then it is necessary that conan provides short_paths for the package binaries so they can be downloaded without overflowing the Windows path length limit.

As a possible suggestion: Maybe just patching the 0.1 version recipe and re-uploading, so it overwrites the old one? I know it is not very clean, but if you want to keep it without needing to rebuild all binaries, can be done.

This could also be considered breaking behavior, depends on the scope (documented API or internal), which is a bit blurry in this case. Could you please show how you are using ``exports`` and what the error message is? Thanks!

**Comment by puetzk** [comment]
As a way of sharing some stuff (pre-[python_requires](https://docs.conan.io/en/latest/reference/conanfile/other.html#python-requires)), I wrote a .py file for a couple packages in the same repo/project that defined a decorator that both set some common things in the ConanFile class, and had it automatically add itself to the exports list so it would be available for the recipe to use. This was probably overkill, I arguably didn't actually end up with that much sharing, but [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). And hooray for gold-plated over-engineering :-P

[ConanFile.exports is documented](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#exports), but it doesn't say what the value is when it hasn't been assigned. In 1.6, the field was missing (e.g. `hasattr(cls ,"exports")` was false). In 1.7 it's initialized to None. This changed in adb62fb9dd1b96a1b4ffa37e2182555f99601eae. Obviously for my usage it was a breaking change, but took it as an "oops, yeah, this needs to handle None too" and just fixed it until discovering the interaction with `conan download`.

# conanfile.py
```py
from conans import ConanFile
from common_stuff import common_stuff 

@common_stuff 
class FooBarConan(ConanFile):
    ...
```

# common_stuff.py
```py
def common_stuff(cls):
    """
    given cls (a subclass of ConanFile)

    designed to be used as a decorator, e.g.
    @common_stuff
    class FooBarConanFile(ConanFile):
    """

    if not issubclass(cls, ConanFile):
        raise Exception("%s is not a subclass of ConanFile" % cls)

    # add some common settings to cls

    # add this file to the exports line
    exports =cls.exports if hasattr(cls, "exports") else ()
    if isinstance(exports,str): exports = (exports,)
    cls.exports = exports + (os.path.basename(__file__),)

return cls
```
```
> conan download -r <remote> foo/0.1@user/release
Downloading conanmanifest.txt
[==================================================] 2.6KB/2.6KB
Downloading conanfile.py
[==================================================] 6.4KB/6.4KB
Downloading conan_export.tgz
[==================================================] 1.1KB/1.1KB
ERROR: Unable to load conanfile in C:\Users\re41236\.conan\data\foo\0.1\user\release\export\conanfile.py
  File "c:\program files\python36\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "%CONAN_USER_HOME%\.conan\data\foo\0.1\user\release\export\conanfile.py", line xx, in <module>
    class CmakeModulesConan(ConanFile):
  File "%CONAN_USER_HOME%\.conan\data\foo\0.1\user\release\export\common_stuff.py", line xx, in settings_choice
    cls.exports = exports + (os.path.basename(__file__),)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'tuple'
```

The fix was just
```diff
-    exports = cls.exports if hasattr(cls, "exports") else ()
+    exports = cls.exports if (hasattr(cls, "exports") and not cls.exports is None) else ()
```

**Comment by puetzk** [comment]
FYI: I just uploaded a replacement recipe, I had forgotten I could do that without also replacing the binaries. It shows "Outdated from recipe: True", but that just truthful. I'm satisfied with this solution.

So you can either close this, or keep it if you want to think about the backward-compatibility implications of adb62fb9dd1b96a1b4ffa37e2182555f99601eae anyway. Though (given the milestone assigned), I don't know that I see a lot of value in letting the change stand for all of 1.7 and 1.8, then changing it back.

**Comment by puetzk** [comment]
I'm not sure there's anything to assign at this point; as I said a month ago, the issue can probably just be closed.

If 1.7/1.8/1.9 are all going to have the field initialized to None (and I do think that change was for the better), changing it back to the 1.6 behavior in 1.10 "for backwards compatibility" isn't really going to help anyone. I already replaced my broken recipe anyway (and thanks for that suggestion).
