### ISSUE TITLE
Settings and options for upload command

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#3564]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Currently, we need to know the package id to upload a specific binary package with `conan upload`. We need to extract the package id somehow (from the console output, json or using the python api).

It would be much easier to have arguments similar to `create` to specify a binary package.

```
conan create . demo/testing -s build_type=Debug -o shared=True
conan upload hello/0.1@demo/testing -s build_type=Debug -o shared=True -r someremote
```

Conan 1.7.3

**Comment by danimtb** [comment]
So you are basically asking about the ``conan upload --query`` option.
Please have a look at the example in the reference: https://docs.conan.io/en/latest/reference/commands/creator/upload.html

**Comment by lasote** [comment]
The query argument is a possibility, but you need to know what to query, and options AFAIK are not supported. 
We've thought a couple of times about providing to the upload command (and maybe others) a json selector expression, so you could generate a json with the `conan create` and then do something similar to:

`conan upload "#output.json:installed.0.recipe.id" -p "$output.json:installed.0.packages.0.id"`

We didn't agree in a concrete feature yet, but we can discuss it again. It could be indeed useful for CI (and conan package tools)

**Comment by memsharded** [comment]
Yes, query strings can include options. Everything that is not mapped to known settings, is considered an option, I think.

**Comment by memsharded** [comment]
``conan upload -p [query]`` was introduced in 2.0, it is possible to do queries for uploading things in 2.0, closing this as resolved.
