### ISSUE TITLE
[question] Add package on-the-fly like NPM

### ISSUE THREAD

**Issue by devSwoop** [conan-io/conan#3566]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi, I discovered Conan (1.6.1) yesterday and I was a bit confused not to be able to add a package to my project like NPM does.
```
conan install MY_PACKAGE
```
Does this feature exist ? If not, is there a reason ?

**Comment by memsharded** [comment]
No, it doesnt exist. The package to be installed has to be added to your local ``conanfile.txt`` or ``conanfile.py``, then install the file. Not sure how NPM works in that sense, but for C and C++ it makes sense first to add it to the ``conanfile``, then install all together the dependencies declared there, so conan makes sure there are not conflicting versions or configurations in the dependency graph. Keeping conflicts away in C/C++ is more important than in JS, which can use multiple versions of the same library in the same dependency graph, while in C/C++ most of the times it is an error.

So a command that added the package you want to the local ``conanfile`` might be possible, but in my opinion it is just an abstraction layer that adds more complexity with little value. Opening the file and adding the dependency there is simpler than learning about a potential ``conan add PACKAGE``, which will have a derivative of arguments (in which order do you want to add it, the first one, the last one. Order can matter in C and C++, lets add ``--insert``, ``--index`` arguments?)
