### ISSUE TITLE
add support for Xcode 10

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#3568]
This is similar to #1707:

After updating to Xcode 10 (released yesterday).

```
ERROR: Invalid setting '10.0' is not a valid 'settings.compiler.version' value.
Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1']
```

I can change `settings.yml` on my CI servers, but it would be nice to have this added ASAP to defaults.

**Comment by memsharded** [comment]
The ``settings.yml`` should update automatically if there were no changes to it. If there are some custom change to the ``settings.yml`` it won't be modified (to destroy them). You can remove the ``settings.yml`` file and you should see it automatically generated, already including the ``10.0`` version.

**Comment by DoDoENT** [comment]
Thanks, I probably had some change in the file I wasn't aware of. It works now.
