### ISSUE TITLE
How to package a subset of what cmake.install() installs ?

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3569]
Sometimes having `cmake.install()` install in the package folder is unpractical, for example if you're packaging an external project, or (like I'm doing) extending the behavior of packages. This means that you can't use `self.copy()` to select exactly what you want in the final package.

If you're packaging an external project, you don't control what `install()` in the `CMakeLists.txt` does. It may install to some specific locations, so not calling `cmake.install()` would require you to re-create the complete filesystem structure (unless you patch the `CMakeLists.txt` on-the-fly but that's a weak approach as it will break with upstream changes).

If however you call `cmake.install()`, then your package_folder is already filled, and you need to remove files from the package instead of adding them, which feels awkward. Systems like [buildroot](https://buildroot.org/) have different directories for that: `staging` (where things are installed) and `target` where you selectively put what you really want.

How would you control what is installed ? Conan workflow is to select stuff you want with `copy`, so I'm a bit uncomfortable calling install and removing what I don't want.

Any ideas on how I should control that? I could try to install to another folder but [`cmake.install()`](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#install) doesn't seem to have a parameter to do that.

Using Conan 1.7.3 on Linux.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
You can pass the `CMAKE_INSTALL_PREFIX` definition:


```python

 def build(self):
    cmake = CMake(self)
    cmake.definitions["CMAKE_INSTALL_PREFIX"] = "Whatever"
    cmake.configure()
    cmake.build()
    cmake.install() # Build --target=install

```

**Comment by liberforce** [comment]
There are some problems I'd still have because I'm trying to extend whole packages, but I'll take your advice and figure out my way around. Thanks.
