### ISSUE TITLE
Questions to Gerrit integration, package revisions & override requirements

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#3571]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hello,

I discovered your package manager and think, that it could be the solution for our CI system.
Thanks for this really nice package manager. Now the first time I think we can go and use a package manager and get a huge benefit.
I use the conan 1.7.3 with included path for SVN support (#3192). Running on Windows 10 & Python 3.7. 

But still I have some question in my head, how to realize the system.

Let's start with our current situation:
* We got subversion repositories
* We use CMake to build our product on different embedded system (dsp & arm processors) and Windows (only for testing). Total 4 different targets.
* Until now we used subversion with svn:externals (in the beginning of development pointing to the `trunk`, towards delivery we are used `fixed svn:externals). With this we were able to build every application with it's used libraries from source.
* As an build server Jenkins with several slaves are used. Individual unittest for the library, integration tests and the application itself were build and tested.
* From time to time we tagged some libraries and build specific binaries packages for them. Unluckily this was more or less a manual process. The binaries were linked into the project instead of the source code variant by using svn:externals.

This is the step we are currently working on:
* Git repositories for new products
* Use `Gerrit` for code review and testing before committing to `master` branch
* For Git projects, the submodule feature is used to include specific revision of one or multiple libraries. When a review on Gerrit is accepted, the submodules revision are automatically updated to the last reviewed revision of the library (Superproject subscription to submodules updates).

And now Conan joins the game: 
* Take `Conan` as a package manager. Here put every library with "Recipe and sources in the same repo" by using the `scm attribute` (for Git & SVN)

That we want to solve:
* Test projects can fetch automatically the dependencies and run their unittests.
* Jenkins automatically build the binary packages
* Reduce the building of project dependencies that have been used already in another project. This would save plenty of time on the build server. Also it reduce the process time, when the developer build & debug code.
* The developer must be able to use either the source code (for development & debugging) or the binary package (reduces build time). Here the `workspace` feature seem to work fine.
* Gerrit support the testing of change-set, that are not already put into `master` branch. Because we want to quickly build dependent libraries/unittests/products process and running all tests, Conan need to build binary packages from the temporary change-set.

## This is my first idea for an solution:
* For every revision of a library I generate a conan package with the following nomenclature:
  `foolib/"branch"_"revision"` (e.g. foolib/master_23ed34abd)
* The I set an alias with the following reference:
  foolib/"version" (e.g. foolib/1.0.0)
* This would bring all projects to follow the libraries like pointing to an `branch`.
* I can override the requirement (foolib/1.0.0) inside the project with the `foolib/"branch"_"revision"` version. This would fix the requirement to a specific revision instead of a branch.
* But how to get it running with Gerrit, when a change-set need to be builded/tested? 
  * Ask conan (conan info) to get the list of needed dependencies. Decide which packages have no changes (also no indirect change from another library) and use their binary packages directly.
  * The other libraries must either generate a special binary package (will be used by override requirements) or checkout the changed sources into the workspace and use the `workspace` feature.

This would substitute our current subversion solution.

## My next idea:

Try to imitate the "Superproject subscription to submodules updates" feature with Conan.
* Build for every library each revision committed a binary package. Following this scheme:
  `foolib/"branch"_"revision"` (e.g. foolib/master_23ed34abd) or may be
  `foolib/"version"-"branch/tag"_"revision"` (e.g. foolib/1.2.0-master_23ed34abd)
* In every project or test, which use libraries, set the requirements override to the specific library revision.
* When a commit happens in a library, a post commit script is executed which updates all projects and tests to the new revision of the library. It automatically checks in the updated "requirement override"

## My question

1. I read about the `package revisions` (#798) feature, you are planning. Could this help me?
2. When using Gerrit, I fetch for the changed libraries in review the following reference (e.g. `refs/changes/00/10000/1`). Should I use it as a channel description: e.g. `foolib/1.2.0-master_23ed34abd@user/refs_changes_00_10000_1`?
3. I can use `conan info` to get the list of needed packages. When I use an alias reference, it automatically replaces it with the target reference. Is there a chance to get both? Because then I would know, if the reference is fixed to a specific revision or it runs with an branch 
4. It would be nice to get a list from `conan info` with the used references. Save this to an file and use this (or a modified version) for the `conan install` (and other commands) as an optional argument to override requirements.
5. May be it would be also nice to override requirements with a wildcard. Let's say replace `foolib/1.2.0@user/testing` with `foolib/*@*/refs_changes_00_10000_1` would use `foolib/1.2.0@user/refs_changes_00_10000_1`?
6. I have `proj`, require `libA/1.2`. `libA` requires `libB/2.0`. What will happen, when I override in `proj` the requirement `lib/1.0`? Do I get an error?
7. I am still unsure which naming scheme for the version and the channel name I should use. May be someone has a good idea? I think about `SemVer` and/or `git describe`.

## My final idea
At the moment I think the best way to go is the following idea (#3798). I will update this ticket, when I have some results.

**Comment by memsharded** [comment]
Sorry this was not responded back then, it fell trough the cracks.
Conan revisions have been there a long time, but also Conan 2.0 is a huge change, with more extension and customization capabilities, package-lists, replace-requires, discouraging user/channel, ``conan graph build-order``,  and many more.

Let's close this as outdated, please create new tickets if there are still any questions.
