### ISSUE TITLE
[question] How to find ( and not download ) if there is a newer version available for a library

### ISSUE THREAD

**Issue by AmitJain001** [conan-io/conan#3578]
Hi All,

In maven, there is a feature to inform the user that there is a new version available for a library being used.
Do we have similar feature in conan ? 
Please note, I do not want to download the latest version. That's why I did not declare the package as libabc/[>1.0]@user/channel in my requirements. It is still libabc/1.0@user/channel. This package is stored in Artifactory (5.8.3 ). All I need is a feature that can go to Artifactory, look into the libraries available there and report that a version 2.x and 3.x are available for libabc for the reference user/channel, so that the user can decide if she wants to move to the newer version.

As a temporary solution, I changed the dependency declaration as libabc/[>1.0]@user/channel, and ran conan info on that. But is there a better way to get the info without modifying the requirements declaration ?

**Comment by memsharded** [comment]
Hi Amit,

Not sure what you mean, running a ``conan search libabc/* -r=myremote`` will tell you about the different versions in the server, is not that enough? Thanks!

**Comment by AmitJain001** [comment]
Hi James,
Thanks for your response. I see the list of all the packages when I run conan search -r=myremote.
But if I run conan search libabc/* -r=myremote, I get the following response :
conan: No match.

libabc has 2 versions in myremote, which are shown when I run the previous command.

I am using conan 1.7.4.

**Comment by memsharded** [comment]
I have just tested with ``conan search Hello/* -r=art`` and it works fine, against an Artifactory 6.3.
I think this was a bug in the previous versions of Artifactory, that is solved now. 
Until you upgrade, you might try to run a ``conan search libabc* -r=art``. without the ``/`` slash.

**Comment by AmitJain001** [comment]
Thanks for the information James !!
`libabc* -r=art` din't work for me, so I added a "\" , and it worked !
`conan search libabc\* -r art` and `conan search libabc\*\/ -r art` --both are working with Artifactory 5.8.3.
However, I'll keep your suggestion in mind and will test that once we move to Artifactory 6.3+.

Thanks once again !

**Comment by memsharded** [comment]
Oh, yes, that is totally possible. The thing is that different terminals escape differently the characters. YOu might try ``conan search "libabc/*" -r=art``, just in case. 

So this is outside of the conan control, in some terminals it is necessary to do the quotes, and some other work without quotes. Thanks for the feedback!
