### ISSUE TITLE
0-byte export/manifest file uploaded to Artifactory

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#3580]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Artifactory v6.30 running in homebrew Docker image: https://hub.docker.com/r/wsbu/docker-artifactory-cpp-ce/
Conan client v1.7.3

I don't know for sure if you'll be able to reproduce this or not, but all I'm doing is the same old `conan create . wsbu/stable` 4 different times (once each for release/debug and x86/arm) followed by a `conan upload`. What I then end up with is seemingly good files in artifactory _except_ for the `export/conanmanifest.txt` file, which is 0 bytes. Locally, on the TeamCity slave where the artifact was originally built, I can see the file has appropriate content. But when by the time it reaches Artifactory, it's gone.

**Comment by memsharded** [comment]
Sounds complicated to reproduce. I am going to label it as a bug, it seems difficult it could be an user error, so potentially a bug somewhere.


Can you please share the upload output?
And then, I assume, the ``conanfile.py`` is correctly uploaded? What happens if you try to install that package? I guess the installation will fail, right?
What happens if you upload to an artifactory 6.3 that runs natively, not inside docker?

**Comment by DavidZemon** [comment]
If it's alright with you, I'll pull your email address from the Git commits and email you credentials for our Artifactory server.

Upload output:
```
david@balrog:~/reusable/Documents/Programming/RedLion/homegrown/ddio$ conan upload -r ci --all ddio/2.1.1@wsbu/testing --confirm
Uploading ddio/2.1.1@wsbu/testing to remote 'ci'
Uploading conanmanifest.txt                                           
[==================================================] 1.2KB/1.2KB      
Uploading conanfile.py                                                
Uploading conan_sources.tgz                                           
Uploading conan_export.tgz                                            
Uploaded conan recipe 'ddio/2.1.1@wsbu/testing' to 'ci': https://artifactory.redlion.net/artifactory/api/conan/conan-local
Uploading package 1/4: 160b4bac5177b0f9a5f4857d00317fe0862a8a02
Requesting upload permissions...Done!                                 
Uploading conanmanifest.txt                                           
[==================================================] 588B/588B        
Uploading conaninfo.txt                                               
Uploading conan_package.tgz                                           
Uploading package 2/4: ec36c36799b7c64ac87634a31cfe9aeae27f47fd
Requesting upload permissions...Done!                                 
Uploading conanmanifest.txt                                           
[==================================================] 586B/586B        
Uploading conaninfo.txt                                               
Uploading conan_package.tgz                                           
Uploading package 3/4: 89bbc176999b31cf8d641dbc5f6c25d9935600e9
Requesting upload permissions...Done!                                 
Uploading conanmanifest.txt                                           
[==================================================] 588B/588B        
Uploading conaninfo.txt                                               
Uploading conan_package.tgz                                           
Uploading package 4/4: 816eaae1c2a7c47f13ce581f3ded7fb53fda4238
Requesting upload permissions...Done!                                 
Uploading conanmanifest.txt                                           
[==================================================] 586B/586B        
Uploading conaninfo.txt                                               
Uploading conan_package.tgz 
```

Install (from dependent):
```
+ conan install .. -s build_type=Debug --build missing --build outdated --update
Version range '>=2.1.0' required by 'None' resolved to 'ddio/2.1.1@wsbu/testing'
Downloading conanmanifest.txt

ERROR: Failed requirement 'ddio/2.1.1@wsbu/testing' from 'PROJECT'
ERROR: invalid literal for int() with base 10: ''
```

The artifactory logs from the upload are interesting... surely incorrect... right???

```
2018-09-20 21:19:39,598 [http-nio-8040-exec-10] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/export/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:39,684 [http-nio-8040-exec-8] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/export/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:39,819 [http-nio-8040-exec-4] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/export/conanfile.py' Content-Length: 0
2018-09-20 21:19:39,985 [http-nio-8040-exec-2] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/export/conan_sources.tgz' Content-Length: 0
2018-09-20 21:19:40,074 [http-nio-8040-exec-10] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/export/conan_export.tgz' Content-Length: 0
2018-09-20 21:19:40,349 [http-nio-8040-exec-7] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/160b4bac5177b0f9a5f4857d00317fe0862a8a02/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:40,427 [http-nio-8040-exec-9] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/160b4bac5177b0f9a5f4857d00317fe0862a8a02/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:40,514 [http-nio-8040-exec-4] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/160b4bac5177b0f9a5f4857d00317fe0862a8a02/conaninfo.txt' Content-Length: 0
2018-09-20 21:19:40,661 [http-nio-8040-exec-6] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/160b4bac5177b0f9a5f4857d00317fe0862a8a02/conan_package.tgz' Content-Length: 0
2018-09-20 21:19:40,950 [http-nio-8040-exec-6] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/ec36c36799b7c64ac87634a31cfe9aeae27f47fd/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:41,031 [http-nio-8040-exec-3] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/ec36c36799b7c64ac87634a31cfe9aeae27f47fd/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:41,139 [http-nio-8040-exec-5] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/ec36c36799b7c64ac87634a31cfe9aeae27f47fd/conaninfo.txt' Content-Length: 0
2018-09-20 21:19:41,301 [http-nio-8040-exec-1] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/ec36c36799b7c64ac87634a31cfe9aeae27f47fd/conan_package.tgz' Content-Length: 0
2018-09-20 21:19:41,541 [http-nio-8040-exec-4] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/89bbc176999b31cf8d641dbc5f6c25d9935600e9/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:41,618 [http-nio-8040-exec-7] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/89bbc176999b31cf8d641dbc5f6c25d9935600e9/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:41,706 [http-nio-8040-exec-9] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/89bbc176999b31cf8d641dbc5f6c25d9935600e9/conaninfo.txt' Content-Length: 0
2018-09-20 21:19:41,845 [http-nio-8040-exec-5] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/89bbc176999b31cf8d641dbc5f6c25d9935600e9/conan_package.tgz' Content-Length: 0
2018-09-20 21:19:42,111 [http-nio-8040-exec-6] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/816eaae1c2a7c47f13ce581f3ded7fb53fda4238/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:42,188 [http-nio-8040-exec-3] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/816eaae1c2a7c47f13ce581f3ded7fb53fda4238/conanmanifest.txt' Content-Length: 0
2018-09-20 21:19:42,273 [http-nio-8040-exec-7] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/816eaae1c2a7c47f13ce581f3ded7fb53fda4238/conaninfo.txt' Content-Length: 0
2018-09-20 21:19:42,396 [http-nio-8040-exec-10] [INFO ] (o.a.e.UploadServiceImpl:361) - Deploy to 'conan-local:wsbu/ddio/2.1.1/testing/package/816eaae1c2a7c47f13ce581f3ded7fb53fda4238/conan_package.tgz' Content-Length: 0
```

I can even go to the Artifactory UI and download some of these files and they have real content. Seems to be the only issue is `export/conanmanifest.txt`.

I have not tried running Artifactory outside Docker. I'll see if I can reproduce with an opensource code example and local Artifactory/docker instance.

**Comment by memsharded** [comment]
Hi @DavidZemon 

I have tried running your docker image with Artifactory, and uploading some packages. So far it didn't fail.

Somethings that you could please check:
- If running that Artifactory image locally, you get the same result.
- Using different conan clients, in different platforms and OSs.
- Installing conan from another origin (if you installed from brew, install and run it from pip)

If your server is in production, I would prefer not to have credentials to it. If it is still being setup and configured, it could be a possibility, but please try to check the above first. Thanks!

**Comment by DavidZemon** [comment]
I tried reproducing locally yesterday and wasn't able to. I copied down the two Docker volumes to my local machine, _then_ started it locally and performed the upload and was unable to reproduce. So... I don't know what's going on. I'm going to try creating repo + system backups from artifactory, wipe the docker volumes, and restart and see if that fixes the issue.

**Comment by DavidZemon** [comment]
Current test results stand at:

* Start fresh instance of Artifactory in the same Docker image but on local machine. Create new Conan repo and upload the artifact. **Unable to reproduce issue.**
* Copy Docker volumes from broken server to local machine. Start instance of Artifactory on local machine, pointing to copies of "broken" Docker volumes. Upload the artifact. **Unable to reproduce issue.**
* Delete broken Docker image on broken server, recreate Docker image (still pointing to same Docker volumes). Upload the artifact. **Issue remains.**
* Open broken Artifactory in browser, perform export of repository and system. Use `docker cp` to extract content to server filesystem. Remove Docker container. Remove Docker volumes. Recreate container and volumes. Use `docker cp` to move the Artifactory-created backups into the new container. Use Artifactory to import the system backup, then repository backup. Upload the artifact. **Issue remains.**

So _what the heck_. I'm finding it hard to believe that this is a Conan or Artifactory issue at this point, but I don't know how to debug the network communication to verify where the problem is. If I could _see_ a network packet and say with confidence "_this_ is the packet that's supposed to have `conanmanifest.txt` in it" then I could know for sure where to dig deeper. But when I tried to do a tcpdump, I didn't see any packets that looked like the file uploads.

**Comment by DavidZemon** [comment]
> Using different conan clients, in different platforms and OSs.

Our entire build ecosystem is either Linux, or Docker. Our CI server was the first one to have this issue, and its slaves are running in [this Docker image](https://hub.docker.com/r/wsbu/teamcity-agent/~/dockerfile/), which is based off of [this one](https://hub.docker.com/r/wsbu/toolchain-native/~/dockerfile/) (next level up is `ubuntu:18.04`). I use Ubuntu 18.04 as my host OS and do development on the host typically, not through Docker. I have the same issue uploading whether I upload via my host OS or via a local instance of the `wsbu/teamcity-agent` image. I could try a VM with some other OS or some different Docker containers if you really think that would make a difference...

> Installing conan from another origin (if you installed from brew, install and run it from pip)

As mentioned before, everything we have is Linux, and it's all installed through pip. Is installing from source the only other option?

**Comment by DavidZemon** [comment]
[conan_trace.txt](https://github.com/conan-io/conan/files/2411092/conan_trace.txt)

I verified that the issue does still occur after this command with the trace file.

**Comment by lasote** [comment]
I don't see anything bad in your traces... except I think there is a bug (not related to your issue) that is not recording correctly all the rest API calls, the "PUT" requests are not recorded. I'll try to fix it and I will request you to repeat the test. ok? (I can prepare a pypi development package if it is easier for you)

**Comment by lasote** [comment]
Hi, Could you install `pip install conan==1.8.0.dev1` and try again to generate the traces file? I don't know if we are going to see anything but worth trying.

**Comment by DavidZemon** [comment]
[conan_trace.txt](https://github.com/conan-io/conan/files/2415500/conan_trace.txt)

Upload attempt with v1.8.0.dev1

**Comment by DavidZemon** [comment]
Just noticed another issue (probably a bug?) with the trace: it's listing the URL with the `http` protocol, but it should be `https` in my case, as that is what is configured in my registry file.

**Comment by DavidZemon** [comment]
Dare I say, I think v1.8.0.dev1 fixed the issue? I actually just went back to my Artifactory server to verify the results and... it's fixed. I can no longer reproduce the problem from my local machine. I went a triggered a build from our CI server, and the problem is back. I'm going to upgrade the Conan version in our CI slave image and then see if that fixes it.

**Comment by DavidZemon** [comment]
No such luck. Still broken. Time to see if I can reproduce locally... again.

**Comment by DavidZemon** [comment]
I am just beyond confused. While setting up matching tcpdump invocations - one on my personal PC where I was testing this morning and another on my work PC where it still failed - it started working _over there_. What's _really_ interesting is that it only started working correctly this morning after I got Wireshark configured too.... it's as though this sniffing the packets is actually fixing the issue.

**Comment by DavidZemon** [comment]
Sorry about the accidental close/open of the ticket.

Okay, I've fixed the problem everywhere.

**First, the cause of the problem:**

Artifactory address moved from `http://ci.redlion.net:8040` -> `https://artifactory.redlion.net` and `registry.txt` files were manually updated with the correct URL. Passwords set in various ways: `conan user -c ... && conan user ...`, `conan user ...`, and simply when prompted via other commands.

**How I fixed the problem:**

1. `conan remote add --force ...` specifically, over port 8040 and HTTP, NOT the HTTPS port
2. `conan user ...`
3. `conan upload ...` (probably unnecessary, but I ran out of machines to test with at this point)
4. `conan remote add --force ...` this time with HTTPS and default port
5. `conan user ...`
6. `conan upload ...`

**Why I had so much trouble reproducing**

Originally I tried sniffing packets with HTTPS still enabled, just to see packet sizes. I didn't know how to read Wireshark correctly and it just confused me more.

After a lot more mucking around with other things, I went back to Wireshark and switched Conan back to HTTP over port 8040. I guess I did it via the Conan CLI that time instead of manually editing the registry file, because it magically started working as soon as I got a good sniff. Of course, knowing now what the problem was, it makes sense the problem _remained_ when I went back to the CI server and triggered another build.

Still not understanding what fixed it, I went to my work PC and redid the whole thing: test the upload to ensure the problem remained, then install wireshark and change the Conan URL (now it's fixed), then run another upload and be confused again. This was the point I started thinking "it can't _possibly_ be Wireshark that's fixing it..."

And then it finally dawned on me what could be causing the issue. So... what do you think? Bug in Conan?

**Comment by DavidZemon** [comment]
Ran into the problem again today on my CI slaves, both of which I thought I fixed yesterday as described above. Apparently not.

Today I confirmed quite simply that the problem exists when I put Artifactory behind nginx-proxy and use HTTPS but goes away when I run:

```
conan remote add --force --insert 0 ci http://artifactory.redlion.net:8040/artifactory/api/conan/conan-local
conan user -r ci -p ********* teamcity
```

Is it an nginx issue? Is it an Artifactory issue? Conan client issue? I haven't the slightest idea...

**Comment by chrahunt** [comment]
I had the same issue using Conan version 1.7.4 and Artifactory CE for C/C++ 6.1.0 rev 60100900. I was able to fix it by setting the Custom Base URL in Artifactory to include https.

More details:

We have Artifactory running in Docker behind a reverse proxy. The setup looks like:

    conan - https -> proxy - http -> Artifactory

The proxy accepts traffic at `artifactory.company.com:443` and `artifactory.company.com:80`, redirecting http traffic to https. The Conan client has the remote configured as `https://artifactory.company.com/artifactory/api/conan/<repo>`.

Uploads were succeeding but they appeared as zero bytes in Artifactory. The request logs in Artifactory and tcpdump in the Artifactory container showed that the Conan client was sending requests with `Content-Length: 0`. When I dumped the requests at the proxy I noticed that several of the calls from Conan were hitting the proxy using https as expected but the actual uploads themselves were using http. The calls using http occurred after a POST to `/artifactory/api/conan/<repo>/v1/conans/<project>/<version>/<user>/<channel>/upload_urls` which actually returned an object that had `http://...`, instead of https. After setting the Custom Base URL in Artifactory (under Configuration > General Configuration > General Settings) to `https://artifactory.company.com/artifactory` uploads worked as expected.

**Comment by DavidZemon** [comment]
@chrahunt, nice to know I'm not alone here.

I tried setting my "Custom Base URL" and it definitely changed something...

```
david@balrog:~$ conan upload -r ci --confirm --force ddio/2.1.1@wsbu/testing
Uploading ddio/2.1.1@wsbu/testing to remote 'ci'
Uploading conanmanifest.txt                                           
ERROR: 
Error uploading file: conanmanifest.txt, 'b'<!doctype html><html lang="en"><head><title>HTTP Status 403 \xe2\x80\x93 Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 \xe2\x80\x93 Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.32</h3></body></html>''
```

Not exactly what I was hoping for though :(

Obviously, a "not authorized" error makes me think password. So, I tried clearing out the user:

```
david@balrog:~$ conan user -c
david@balrog:~$ conan upload -r ci --confirm --force ddio/2.1.1@wsbu/testing
Uploading ddio/2.1.1@wsbu/testing to remote 'ci'
Please log in to "ci" to perform this action. Execute "conan user" command.
Remote 'ci' username: davidzemon
Please enter a password for "davidzemon" account: 
ERROR: Wrong user or password
Remote 'ci' username: davidzemon
Please enter a password for "davidzemon" account: 
Uploading conanmanifest.txt                                           
ERROR: 
Error uploading file: conanmanifest.txt, 'b'<!doctype html><html lang="en"><head><title>HTTP Status 403 \xe2\x80\x93 Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 \xe2\x80\x93 Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.32</h3></body></html>''
```

No good.

So I checked the Artifactory permissions. I tried uploading an artifact that I _know_ I'm now allowed to upload:
```
david@balrog:~$ conan upload -r ci --confirm --force ddio/2.1.1@wsbu/stable
Uploading ddio/2.1.1@wsbu/stable to remote 'ci'
Compressing recipe...                                                 ERROR: Permission denied for user: 'davidzemon'. [Remote: ci]
```
Indeed, that's a very different error. 

So... is this a separate bug? Related? Coincidental? Artifactory or Conan client?

**Comment by lasote** [comment]
@markgalpin Any thought?

**Comment by chrahunt** [comment]
@DavidZemon, that looks like it is probably unrelated. Mine was very clear. When I removed the Custom Base URL I got the same behavior again (Content-Length: 0) and when I put it back it stopped.

**Comment by markgalpin** [comment]
So in the event that you are using an API which causes artifactory to give you a URL (which happens in several mechanisms in the API) it will use the base URL to define how to use it.  Some of the zero-length calls are expected as we try to check if artifact is present before uploading.  The base URL shouldn't be needed if the following headers are set in your NGINX config:
    proxy_set_header    X-Artifactory-Override-Base-Url $http_x_forwarded_proto://$host:$server_port/artifactory;
    proxy_set_header    X-Forwarded-Port  $server_port;
    proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header    Host              $http_host;
    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;

All of that said, the creation of a zero length object is an inconsistency that should not be happening, but it sounds like the correct solution is either to set the base URL or the NGINX config above.  Does that make sense?

**Comment by lasote** [comment]
Could we consider this as resolved? Thanks.
