### ISSUE TITLE
'conan info ..' fails within build folder with ERROR 'settings.XXX' value not defined

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#3585]
hi,

`conan info ..` fails when executed in the build folder after `conan install ..`. It seems that for some reason the files in the build folder are read, though IMHO they are not relevant to the command.
For example a simple package with no settings which is using `cmake_installer` as `build_requires`:

1. install Conan 1.7.3 on Windows 10, Python 3.6.5
1. use the following `conanfile.py` and put it into `somedir`

        from conans.model.conan_file import ConanFile

        class TestPackage(ConanFile):
            name = "test-cmake"
            version = "1.0.0"
            build_requires = "cmake_installer/3.12.1@conan/stable"
1. `cd somedir`, `mkdir build`, `cd build`, `conan install ..`

> Auto detecting your dev setup to initialize the default profile 
...
Found Visual Studio 15
Default settings
        os=Windows
        os_build=Windows
        arch=x86_64
        arch_build=x86_64
        compiler=Visual Studio
        compiler.version=15
        build_type=Release
*** You can change them in XXX ***
*** Or override with -s compiler='other' -s ...s***
WARN: Remotes registry file missing, creating default one in XXXX
cmake_installer/3.12.1@conan/stable: Not found in local cache, looking in remotes...
cmake_installer/3.12.1@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 58B/58B
Downloading conanfile.py
[==================================================] 4.8KB/4.8KB
Downloading conaninfo.txt
[==================================================] 234B/234B
PROJECT: Installing XXX\conanfile.py
Requirements
Packages
Build requirements
    cmake_installer/3.12.1@conan/stable from 'conan-center' - Downloaded
Build requirements packages
    cmake_installer/3.12.1@conan/stable:456f15897172eef340fcbac8a70811f2beb26a93 - Download
cmake_installer/3.12.1@conan/stable: Retrieving package 456f15897172eef340fcbac8a70811f2beb26a93 from remote 'conan-center'
Downloading conanmanifest.txt
[==================================================] 463.1KB/463.1KB
Downloading conaninfo.txt
[==================================================] 234B/234B
Downloading conan_package.tgz
[==================================================] 19.2MB/19.2MB
cmake_installer/3.12.1@conan/stable: Package installed 456f15897172eef340fcbac8a70811f2beb26a93
PROJECT: Applying build-requirement: cmake_installer/3.12.1@conan/stable
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt

4. Execute `conan info ..`

        ERROR: cmake_installer/3.12.1@conan/stable: 'settings.arch_build' value not defined

5. Remove the `conanbuildinfo.txt` and `conaninfo.txt` files from the build folder and try again: works as expected

        rm -rf *
        conan info ..
        test-cmake/1.0.0@PROJECT
            ID: 456f15897172eef340fcbac8a70811f2beb26a93
            BuildID: None
            Build Requires:
                cmake_installer/3.12.1@conan/stable
        cmake_installer/3.12.1@conan/stable
            ID: 456f15897172eef340fcbac8a70811f2beb26a93
            BuildID: None
            Remote: conan-center=https://conan.bintray.com
            URL: http://github.com/lasote/conan-cmake-installer
            License: OSI-approved BSD 3-clause
            Recipe: Cache
            Binary: Cache
            Binary remote: conan-center
            Creation date: 2018-09-06 14:39:14
            Required by:
                test-cmake/1.0.0@PROJECT

It also works as expected when the `test-cmake` package also defines the `arch_build` and `os_build` settings.

**Comment by lasote** [comment]
Hi! This is (in part) intended behavior, we mention in the info command help:

```
  -if INSTALL_FOLDER, --install-folder INSTALL_FOLDER
                        local folder containing the conaninfo.txt and
                        conanbuildinfo.txt files (from a previous conan
                        install execution). Defaulted to current folder,
                        unless --profile, -s or -o is specified. If you
                        specify both install-folder and any setting/option it
                        will raise an error.
```

The files are relevant because the info reads from these files the "state" of the install.

A different and the real issue is that reading the "state of the install" have some issues like the one you described. As the main recipe doesn't declare settings, they are not stored in the `conaninfo.txt` file, and it fails because of a missing setting for the `build_require`.

We are currently studying better alternatives to the `conaninfo.txt`, but it will take time. In the meantime you could also run `conan info .. -if=..` to avoid recovering the state from these files.

**Comment by memsharded** [comment]
The origin of this issue seems the same as this one: https://github.com/conan-io/conan/issues/3367

**Comment by petermbauer** [comment]
i see, thx for the quick answer!
