### ISSUE TITLE
need help: Testing Qt package - how to config qtmodules

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#3588]
Hi all,

I'm currently testing the Qt conan package and it seems to me that I don't know or I don't understand how to change the configuration of a qtmodule...

In specific I'm trying to enable handwrite and t9write for qtvirtualkeyboard module... how can be this be done?

Sory if this is not the correct place to put this kind of questions.. if not please point me to the right place please.

Regards,
Nuno

**Comment by nesc1** [comment]
Hi danimtb, sorry: the pakage is: Qt/5.11.1@bincrafters/stable

the remotes are:
my_local_server: http://localhost:9300 [Verify SSL: True]                                           
conan-center: https://conan.bintray.com [Verify SSL: True]                                 
bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]

**Comment by danimtb** [comment]
Yes, you are using the Qt bincrafters recipe. You can finde in the bintray web https://bintray.com/bincrafters/public-conan/Qt%3Abincrafters their issue tracker and report your issue there 😄

**Comment by nesc1** [comment]
thanks, so i will close this one and start a new one [there](https://github.com/bincrafters/community/issues/451):
