### ISSUE TITLE
[feature request]  Enhanced support for copying *.so file groups

### ISSUE THREAD

**Issue by adaviding** [conan-io/conan#3590]
There are some libraries (e.g. gstreamer) where the *.so files are really published in groups.  For example, one group might look like this:

```
libwhatever.so    [symlink --> libwhatever.so.0]
libwhatever.so.0  [symlink --> libwhatever.so.0.1234.0]
libwhatever.so.0.1234.0
libwhatever.so.1  [symlink --> libwhatever.so.1.4321.0]
libwhatever.so.1.4321.0
```

When I tried taking just the `*.so` file, some dependent libraries failed to load because they would only take the `*.so.0` file.  So I had to write a bunch of special code for finding and copying the entire group.

You can find it in this file:  https://github.com/Panopto/gst-conan/blob/52989505e26a77e1840f83515de0338e870511fa/gst_conan/base.py

```
def copyOneSharedObjectFileGroup(pattern:str, srcFolder:str, destFolder:str, keepPath:bool=True) -> list

def copySharedObjectFileGroups(pattern:str, srcFolder:str, destFolder:str, keepPath:bool=True) -> list

def findSharedObjectGroups(pattern:str, folder:str, recursive:bool=True, prefix=None) -> list:

def groupSoFiles(sortedList:list) -> list
```

Feel free to take the code and refactor it however you see fit.

**Comment by danimtb** [comment]
What about something like:

```
def pacakge(self):
    self.copy(pattern="*.so.*", dst="lib", src=".", symlinks=True)
```

**Comment by adaviding** [comment]
Thanks for your suggestion @danimtb:  It is nice to see that the `copy` method had a `symlinks=True` parameter.  I was unable to find documentation for that method online, and my Pycharm IDE handled that method as a black box ... so I couldn't figure out how to use it properly.

A pattern like the one you describe above would probably do a good job, but there may be a few disadvantages

- It might pull in extra files that are not wanted ... but in most cases it would probably behave fine.  In order to reduce the ambiguity, perhaps a `regex:bool` flag could be added to do the filename matching using regex.
- There were some cases where `self.copy` wasn't working as I thought it should.  I **think** it was the cases where the filename had no wildcards (**if** memory serves).  **If** my understanding is correct, then something like the following wouldn't work:
```
def pacakge(self):
    self.copy(pattern="exact-filename.so", dst="lib", src=".", symlinks=True)
```
But the `regex:bool` parameter would fix that.
- In my code, I refer to the `so` file group without any wildcards in the name, and I am able to raise an exception if the file group is not found.  With the example provided above by @danimtb , extra code would be required to verify that.  However a `regex:bool` parameter would also fix that.

Also in a more general sense, I wasn't sure how to debug the `self.copy` method in an IDE ... pycharm couldn't find the source for that method.  Since the method was a black box I felt uncomfortable using it in some situations where it didn't behave exactly as I had hoped it would.  Also I couldn't find documentation for the method signature online, so I didn't know that `symlinks=True` was an option until now.

**Comment by AbrilRBS** [comment]
Clearing old issues, I'm closing this because we didn't hear back from you in a while and it's also been solved in Conan 2, where 
> Also in a more general sense, I wasn't sure how to debug the self.copy method in an IDE ... pycharm couldn't find the source for that method

is no longer relevant as it's become a public tool, not an injected method into the conanfile
