### ISSUE TITLE
[bug]  Conanfile.py `exports` clause does not work for superordinate folders

### ISSUE THREAD

**Issue by adaviding** [conan-io/conan#3591]
I'm using Conan 1.7.2 on Linux Mint 19.  I am building conan packages for gstreamer.

My repo has a folder structure like this:

```
MY_REPO
    gst_conan
    packages
        gstreamer
            conanfile.py
        gst-plugins-base
            conanfile.py
   ...
```

At the root level of the repo is `gst_conan` which contains a bunch of Python code which gets used by all all of my conanfiles.  When the package is created, I want `gst_conan` to exist next to each `conanfile.py` in within the `exports` folder.  So naturally I tried a clause like the following in my ConanFile class:

```
exports = "../../gst_conan"
```

I was hoping the clause would pull the `gst_conan` folder into the `exports` folder (next to each `conanfile.py`) but it didn't work.  I tried a few other things but nothing works.

As a workaround, I copy the folder manually from within the `source()` method.

**Comment by memsharded** [comment]
Actually there is some open PR from a long time: https://github.com/conan-io/conan/pull/2676, that supposedly fixes this problem.

The only thing is that it could be breaking, and that is the reason it is scheduled for 2.0. 

Can you please tell which is exactly the error? the files are copied, but not with the right path, or absolutely nothing is copied?  Also, you might consider using the ``scm`` feature when conan 1.8 it is released, because it will be able to manage your layout of parent folder.

**Comment by adaviding** [comment]
The `gst_conan` folder is not copied into the `exports` folder but I do not see any error.

I am able to import the package (even though it wasn't copied) because of shenanigans on lines 14-16 of my `conanfile.py`:

https://github.com/Panopto/gst-conan/blob/52989505e26a77e1840f83515de0338e870511fa/packages/gstreamer/conanfile.py

Here is the terminal output after my `conan create ...` command:

```
Exporting package recipe
Linter warnings
    WARN: Linter. Line 249: Unused variable 'pcName'
gstreamer/1.14.3@my_conan_user/my_conan_channel: A new conanfile.py version was exported
gstreamer/1.14.3@my_conan_user/my_conan_channel: Folder: /home/ding/.conan/data/gstreamer/1.14.3/my_conan_user/my_conan_channel/export
gstreamer/1.14.3@my_conan_user/my_conan_channel: WARN: Forced build from source
gstreamer/1.14.3@my_conan_user/my_conan_channel: Installing package
Requirements
    gstreamer/1.14.3@my_conan_user/my_conan_channel from local cache - Cache
Packages
    gstreamer/1.14.3@my_conan_user/my_conan_channel:69f10d1e6d78c1962fbe8fb80440f32b1fdf8423 - Build

...
```

**Comment by adaviding** [comment]
Also I tried solving my problem with a soft-link, then referencing the soft-linked folder in my conanfile as `exports="name_of_softlink"`.

Unfortunately, nothing under the softlink gets copied into the exports folder.  It seems like this would be a nice feature to have.

BTW, I was surprised to learn that Windows has soft links:  https://superuser.com/questions/182553/does-windows-have-the-ln-s-or-equivalent

**Comment by memsharded** [comment]
Two explicit ``export()`` and ``export_sources()`` methods were added to recipes to allow more flexibility and control over what is exported and from where, including parent folders, more easily. Closing this as solved by those methods.
