### ISSUE TITLE
[build system] Set a default value for GNU standard installation directories

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#3594]
After the agreement on #3388 we should make sure that the GNU installation dirs are set to a default value by the build helpers:

- CMake: https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html
- Autotools: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

The way I see it those default values should be:

- BINDIR, SBINDIR and LIBEXECDIR --> bin
- INCLUDEDIR, OLDINCLUDEDIR --> include
- LIBDIR --> lib (already done in #3388 )
- DATAROOTDIR --> rootdir **??** (to make sure everything is installed inside pacakge folder, or is it enough to set `--prefix` for that?)

**Comment by lasote** [comment]
Probably `self.cpp_info.resdirs` for DATAROOTDIR
