### ISSUE TITLE
Listing package content

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#3596]
Maybe a stupid question, but is there a quick way to list all the files (artifacts: binaries and header files) contained in a package (i.e. files added through the package method)?
TIA

**Comment by lasote** [comment]
Yes, take a look at `conan get` command: https://docs.conan.io/en/latest/reference/commands/consumer/get.html

**Comment by marausch** [comment]
By doing:
`$ conan get mypackage/1.2.3-alpha.3@demo/experimental .`
I get:
```
Listing directory '.':
 GitVersion.conan
 conanfile.py
 conanmanifest.txt
```
(where GitVersion.conan is a file I'm exporting with _exports_).

 By adding the _--package_ argument, something like:
`$ conan get mypackage/1.2.3-alpha.3@demo/experimental . -p 42cc4818afa73b5cf4cf418a71562723812dc4df`
I only get:
```
Listing directory '.':
 .conan_link
```
(not the library binary and header files contained in the package).

**Comment by marausch** [comment]
Forgot to mention that I'm working on _Windows 10_ with Conan _1.7.3_ installed and _short_paths_ enabled.

**Comment by memsharded** [comment]
That sounds like a bug, lets see if it can be fixed, I'll have a look.

**Comment by memsharded** [comment]
Yeah, seems easy to fix: https://github.com/conan-io/conan/pull/3600. Will be in next 1.8, thanks for reporting it!
