### ISSUE TITLE
[question] Non-standard .cmake file locations within package/hashXXXX directory

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#3597]
I'm packaging up on Windows the output of several different large internal library sets which I don't own.  Lets call the sets: ```setA```, ```setB``` and ```setC``` <sup>\[*\]</sup>, each of which has its own repo and publishes several libs. 

The libraries sets have a clear dependency structure, and 1) ```setB``` depends on ```setA```, 2) ```setC``` depends on both ```setA``` and ```setB```.

It seemed natural enough to publish each of the 3 ```setA```, ```setB``` and ```setC``` repos as their own Conan packages, but I ran into a snag at the end when trying to build ```setC```:

The somewhat sophisticated \[read: probably not within scope for me to modify\] CMake build tools for each of the 3 library sets follow more of a Unix build model and expect that the build outputs of each of the previous library set builds will be kept in a common 'refroot' directory.

This isn't matching well with my conanization plan, where after expressing dependencies in my conanfile I end up with:

A) ```setA``` libs in the 'setA' local cache folder:

```
 Directory of C:\Users\mmaguir1\.conan\data\setA\3.11.0.4\PORT\stable\package\28796df6684cd3c3490c089a9f9a2a6a3993b4fc\lib64\opt_dbg_exc_mt

09/20/2018  05:08 AM        12,366,366 setA1.lib
09/20/2018  05:08 AM           142,852 setA2.lib
09/20/2018  05:08 AM         7,810,628 setA3.lib
09/20/2018  05:07 AM         2,836,510 setA4.lib
09/20/2018  05:07 AM           413,554 setA5.lib
09/20/2018  05:07 AM         4,303,866 setA6.lib
09/20/2018  05:07 AM           647,868 setA7.lib
               7 File(s)     28,521,644 bytes

```

B) ```setB``` libs in the 'setB' local cache folder:

```
C:\Users\mmaguir1\.conan\data\setB\3.11.0.4\PORT\stable\package\65ee3edfa966a0905abd673449edbce6fad84ddb>dir /s *.lib
 Volume in drive C is MAGUIRE-C
 Volume Serial Number is 82B2-3C24

 Directory of C:\Users\mmaguir1\.conan\data\setB\3.11.0.4\PORT\stable\package\65ee3edfa966a0905abd673449edbce6fad84ddb\lib64\opt_dbg_exc_mt

09/20/2018  05:57 AM        10,024,498 setB1.lib
09/20/2018  05:56 AM            26,982 setB2.lib
09/20/2018  05:56 AM         2,846,426 setB3.lib
09/20/2018  05:56 AM         7,837,204 setB4.lib
09/20/2018  05:57 AM         2,455,758 setB5.lib
               5 File(s)     23,190,868 bytes
```

But now the CMake-based build tools for ```setC``` expect me to be able to point to a lib64 directory that contains *all* libraries together.

Any suggestions or strategies I could try here?  I'd like to stay as 'Conathonic' as possible.

It would of course be nice if the build of ```setC``` were flexible enough to allow me to point it at more than one location, but I don't get the sense that the team that maintains those build scripts would act on that suggestion in the short or medium term, so I'm looking for other options.

\[*\]<sup>The story, all names, characters, and incidents portrayed in this production are fictitious. No identification with actual persons (living or deceased), places, buildings, and products is intended or should be inferred. </sup>

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ Windows Server 2012 R2 64, Conan version 1.5.2] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
What I would do is, in the build() method of `setC`, patch the original CMakeLists (with `tools.replace_in_file` for example) to include the `conanbuildinfo.cmake` file and call the `conan_basic_setup()`. Also, any other piece of code that blocks `setC` of receiving dependencies information from Conan should be modified. It depends a lot on each build system scripts, but further actions are required.

**Comment by michaelmaguire** [comment]
As it turns out, the team whose library I'm packaging -- in addition to supporting their old way that required a single REFROOT directory -- now also supports multiple directories via some new work they did recently to support CMAKE.

I was able to get this to work by ensuring that in the ```package_info()``` for each of ```setA``` and ```setB``` I set:

```
def package_info(self):
    [...]
    self.cpp_info.builddirs=[cmake_path] 
```

where ```cmake_path``` contained the subdir of my package/hashXXXXX dir that contained *.cmake helpers they had provided and installed during their build of those packages.

Then in the ```build()``` method for ```setC``` I needed to read those builddirs values using the build_paths variable, which was now populated with absolute path versions of the builddirs I had specified in ```package_info()``` of ```setA``` and ```setB```:

```
def build(self):
    cmake = CMake(self)
    [...]
    setA_build_paths = self.deps_cpp_info["setA"].build_paths;
    setB_build_paths = self.deps_cpp_info["setB"].build_paths;

    combined_build_paths = setA_build_paths + setB_build_paths
    tmp_CMAKE_PREFIX_PATH = ";".join(combined_build_paths)
    cmake.configure(args=["-DCMAKE_PREFIX_PATH=%s" % tmp_CMAKE_PREFIX_PATH ])
```

Please criticize/correct me if I've misunderstood how to use ```cpp_info.builddirs``` and ```deps_cpp_info.build_paths```.

**Comment by michaelmaguire** [comment]
@lasote the three packages' ```CMakeLists.txt``` have:

```
set(CONAN_BLD_INFO ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
if (WIN32 AND EXISTS ${CONAN_BLD_INFO})
    message(STATUS "On WIN32 and found conanbuildinfo.cmake, calling conan_basic_setup")
    include(${CONAN_BLD_INFO})
    conan_basic_setup()
endif()
```

And I can confirm I see the message "On WIN32 and found conanbuildinfo.cmake, calling conan_basic_setup" showing up in each build.

Double checked and from testing build breaks again if I remove the pfaffing about with ```self.cpp_info.builddirs``` and ```self.deps_cpp_info["setX"].build_paths```.

Could it perhaps be because the packages are placing their ```*.cmake``` files in 'non-standard' directories?

```
C:\Users\mmaguir1\.conan\data\setA\3.11.0.4\PORT\stable\package\28796df6684cd3c3490c089a9f9a2a6a3993b4fc\lib64\opt_dbg_exc_mt\cmake
```

**Comment by lasote** [comment]
I don't know, could you add a `message` to your consumer's `conanbuildinfo.cmake` to see the adjusted directories?

```
    # Make find_package() to work
    set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_PREFIX_PATH})
    message("HELLO CMAKE_PREFIX_PATH!!! ${CMAKE_PREFIX_PATH}")
```

It should be the same as the `build_paths` you are adjusting, so if it works your way, it should work this way...

**Comment by michaelmaguire** [comment]
Thanks, I'd like try your suggestion:

CMake vs. Conan Noob question:  If I manually modify ```conanbuildinfo.cmake``` to add the message line you mentioned, it gets overwritten each time I call:

```
E:\DevelopBp\mmaguir1\src\mmaguir1\setC>conan create . PORT/stable -s build_type=Release
``` 

to retry the build.

Is there instead some CMake command line I should try calling from directly within:

```
C:\Users\mmaguir1\.conan\data\setC\3.13.0.1\PORT\stable\build\a83df3fbd48cef90605224ce3777c682463a3356
```
to retry the build using the generated ```conanbuildinfo.cmake```?

Or is there a better way to invoke conan that picks up from where the post-generation phase left off?

**Comment by lasote** [comment]
Ah! yes, sorry for not clarifying.
You can use the Conan local flow in the consumer package, something like:

```
mkdir build && cd build
conan install .. 
# Modify the conanbuildinfo.cmake
conan source ..
conan build ..
```

If you are using CMake everywhere it should work.

**Comment by michaelmaguire** [comment]
Thanks for the tip.  I tried adding the message HELLO modification to conanbuildinfo.cmake and this was the difference:

# Without my custom ```build_paths``` pfaff (build can't find bde libraries)

```
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
HELLO CMAKE_PREFIX_PATH!!! C:/Users/mmaguir1/.conan/data/bde-tools/3.11.0.1/PORT/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/;C:/Users/mmaguir1/.conan/data/bde-classic/3.11.0.4/PORT/stable/package/65ee3edfa966a0905abd673449edbce6fad84ddb/;C:/Users/mmaguir1/.conan/data/bde/3.11.0.4/PORT/s
table/package/28796df6684cd3c3490c089a9f9a2a6a3993b4fc/
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Found PythonInterp: C:/Anaconda3/python.exe (found version "3.5")
```

# With my custom ```build_paths``` pfaff (build works)

```
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
HELLO CMAKE_PREFIX_PATH!!! C:/Users/mmaguir1/.conan/data/bde-tools/3.11.0.1/PORT/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/;C:/Users/mmaguir1/.conan/data/bde-classic/3.11.0.4/PORT/stable/package/6
n/data/bde/3.11.0.4/PORT/stable/package/28796df6684cd3c3490c089a9f9a2a6a3993b4fc/lib64/opt_dbg_exc_mt/cmake;C:/Users/mmaguir1/.conan/data/bde/3.11.0.4/PORT/stable/package/28796df6684cd3c3490c089a9f9a2a6a3993b4f
e/package/65ee3edfa966a0905abd673449edbce6fad84ddb/lib64/opt_dbg_exc_mt/cmake
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Found PythonInterp: C:/Anaconda3/python.exe (found version "3.5")
```

So it seems like the additional ```/lib64/opt_dbg_exc_mt/cmake``` subdirs specified using my build_paths customizations is required.

**Comment by michaelmaguire** [comment]
I'm not a CMake expert, but from https://stackoverflow.com/questions/12075371/cmake-find-library-custom-library-location specifically comment https://stackoverflow.com/a/19637579 it seems like this is works-as-designed for CMake:

> For each path in the CMAKE_PREFIX_PATH list, CMake will check "PATH/include" and "PATH" when FIND_PATH() is called, "PATH/bin" and "PATH" when FIND_PROGRAM() is called, and "PATH/lib and "PATH" when FIND_LIBRARY() is called.

https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Useful-Variables#environment-variables

**Comment by michaelmaguire** [comment]
Assuming what I've done modifying ```-DCMAKE_PREFIX_PATH``` in my ```conanfile.py``` is the correct way to deal with this, now I just need to figure out how to append instead of set the correct value so that I'm not clobbering Conan's standard mechanism for dealing with other, well-behaved libraries.

Right now it seems like this mechanism is preventing all packages mentioned via Conan's ```requires``` to get noticed.

**Comment by lasote** [comment]
Hi! thanks for your tests. So, just to make sure, if you add the custom dirs to `builddirs` it works without adjusting also the `CMAKE_PREFIX_PATH`, right?

```
self.cpp_info.builddirs=[cmake_path] 
```

You are right, CMake look for very common subdirectories like `cmake`,  `cmake/include`, `bin` and so on, but `opt_exc_mt/cmake` is not a path cmake will look for unless you specify that that is a "cmake prefix path" itself.

> So if I've understood correctly, this CMake feature/limitation is being exercised by the fact that the library developers in question wanted to support simultaneous building of different flavours, e.g.:

```
/lib/opt_dbg_exc_mt/cmake
/lib/dbg_exc_mt/cmake
/lib/opt_exc_mt/cmake
/lib64/opt_dbg_exc_mt/cmake
/lib64/dbg_exc_mt/cmake
/lib64/opt_exc_mt/cmake
```

You are right. I think the key here is to get rid of the subfolder "opt_dbg_exc_mt", also for libraries. Because when you are generating a conan package you are already creating a package for a specific configuration, you don't need a subfolder saying: "this is debug and mt", that can be determined by the installation applied settings. Also I think the "cmake" folder should be in the package root. That way the Conan package would look much better and everything should work automatically without additional adjustings, copying only the required files (to the root) for the current configuration, of course.

```
/lib/setA1.lib
/lib/setA2.lib
/lib/setA3.lib
/cmake/*.cmake
```

**Comment by michaelmaguire** [comment]
@lasote, you were right, with ```self.cpp_info.builddirs``` modified in each of the contributing packages, there's no need to modify ```CMAKE_PREFIX_PATH``` by hand -- I don't need to read and manually use ```deps_cpp_info["setX"].build_paths```.

Thanks!

As for your feedback about the directory structure, I'll make sure the team that produced the CMake knows about your comments, although I see why they chose to structure their output the way they did, which was done without Conan in mind.
