### ISSUE TITLE
Warn when orphaned packages are not updated

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#3604]
I stumbled upon this a few times:

- install a package from a remote
- remove the remote
- try to update the package with `install -u`

Conan just prints `No remote` and `Already installed!`.
Would be nice to have some kind of warning that the package is orphaned and cannot be updated.

conan 1.7.3, windows
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Conan 2.0 removed this behavior, and now ``--update`` will search in servers for updates in all cases, because with revisions it can be guarantee a correct update. Closing this ticket as solved.
