### ISSUE TITLE
Consider using -C as a cmake command line non-intrusive way to define cache values.

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3605]
Could be used like:

```
$ cmake .. -C conan_paths.cmake -DCMAKE_BUILD_TYPE=Release
```

**Comment by drahosp** [comment]
This is pretty much the approach I was looking for when I first tried to use "conan_paths" CMake generator. I would strongly prefer this over the current practice of including _conan_paths.cmake_ in _CMakeLists.txt_. Using `-DCMAKE_TOOLCHAIN_FILE` for this purpose is not possible in my workflow as I am cross-compiling. Alternatively setting `-DCMAKE_PROJECT_<PROJECT-NAME>_INCLUDE` is quite verbose when invoking CMake manually. I would be ok with this approach when manually invoking CMake but I would expect `conan build .` to append the argument automatically in `cmake.configure()`

**Comment by lasote** [comment]
So, what is needed in order to use the `-C` like @memsharded described? Is it just a matter of test it & document it or does it need a feature?

**Comment by drahosp** [comment]
The _conan_paths.cmake_ file has to set the `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` as cache variables. Eg.
```CMake
set(CMAKE_MODULE_PATH  ... CACHE PATH "Module search paths set from conan_paths.cmake")
set(CMAKE_PREFIX_PATH ... CACHE PATH "Prefix paths set from conan_paths.cmake")
```

**Comment by memsharded** [comment]
Note: the -C cache approach cannot contain any conditional logic, so to set things related to the current conan settings, they should be straighforward defined (a potential conanbuild.cmake file generated by new generators)

**Comment by drahosp** [comment]
Yes, cache needs to be forward declared. However the cache file can define CMAKE_PROJECT_<PROJECT-NAME>_INCLUDE that can point to a cmake file with logic if need be.

**Comment by memsharded** [comment]
Closing this ticket as outdated, now there are more modern ways to achieve this, like ``CMakePresets`` and Conan new tools like ``CMakeToolchain`` can also generate preset files.
