### ISSUE TITLE
[question] deploy feature

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#3611]
I'm maintaining Bincrafters' Qt recipe. Qt library has the following need so that a program linked with Qt can run:
1. Either Qt binaries must have the path to the Qt distribution hard-coded inside them
2. Or a file named qt.conf containing path to the Qt distribution must be placed next to the executable linking with Qt

option 1 is incompatible with conan, because package binaries must not be modified after being downloaded.
option 2 could be partially handled by adding a `deploy` method to Qt's recipe doing the following:
```python
with open('qt.conf', 'w') as f:
    f.write('[Paths]\nPrefix = %s' % self.cpp_info.rootpath)
```
but this quite limited use case, it would work only if the user calls `conan install Qt/version@bincrafters/stable` and then copies the qt.conf file next to the executable. It would not work if the user has a conanfile requiring Qt, because deploy is not called for dependencies.
I could not find a general solution to this problem using conan. Am I missing something ?

**Comment by lasote** [comment]
You could implement a custom generator in the Qt recipe. So when the consumer adds the requirement, he can add also the generator that will create (only for the inner package) a `qt.conf` file.

```
from conans.model import Generator
from conans import ConanFile, tools


class qt(Generator):
    @property
    def filename(self):
        return "qt.conf"

    @property
    def content(self):
        return "whatever contents the generator produces"


class Qtpackage(ConanFile):
    ....
```

Consumer:

```
[requires]
qt/x.y@bincrafters/stable

[generators]
qt
```
WDYT? I think it should work.

**Comment by lasote** [comment]
Other alternative could be using the `virtualbuildenv` generator and activate the environment first, but I like the idea of the custom generator.

**Comment by ericLemanissier** [comment]
I'm don't think virtualrunenv would work, because environment variable cannot solve the problem.
A custom generator seems the best option, I'll try that. By the way, I could not find any documentation on variables available inside a generator, the link you uses deps_build_info, would that be the same as ConanFile.deps_cpp_info ?

**Comment by lasote** [comment]
You have the conanfile at `self.conanfile`. I'll update the docs.

**Comment by lasote** [comment]
You can use something like: `self.conanfile.deps_cpp_info["Qt"].rootpath` to access the rootpath.

**Comment by ericLemanissier** [comment]
Thanks, the custom generator was very easy to implement, and does the job !
