### ISSUE TITLE
Question: Is it possible to specify source, build and package folder during conan create

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#3617]
Hi,

we have a lot of windows builds, and therefore a lot of short_paths configs. We build on jenkins using conan create. The problem is, that it builds in a different folder every time (due to short_paths), that makes it hard to use warnings scanner, or keep the workspace but delete the dependencies.

Now to my question: IT is possible to tell conan where to source, build and package during conan create (or even conan install --build).

conan Version 1.7.3 and 1.5.x

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @claasd 

No, it is not possible, the "short_paths" feature is kind of low-level, transparent indirection (a poor generic implementation of symlinks), so the higher level layers of Conan are quite agnostic about it, and then it might be very difficult to pass that information without really disruptive changes to the architecture (that won't be clean and thus affect future maintenance).

Could it be possible to do the opposite, ask about the package folders with the ``conan info`` command? Or something that tells you the folders that were used?

It is likely that you might also be interested in the new "plugins" feature, to be released soon in 1.8. This will allow to do pre-post tasks to most stages on conan packages, and there you will have access to ``conanfile.build_folder``, ``conanfile.package_folders``, etc.

See ongoing work docs: https://github.com/conan-io/docs/pull/846

**Comment by memsharded** [comment]
There is a new way to define package layouts: https://docs.conan.io/en/latest/developing_packages/package_layout.html#package-layout

Closing this as inactive
