### ISSUE TITLE
[python_requires] objects are overwritten when using multiple python_requires calls in one recipe

### ISSUE THREAD

**Issue by Verenchen** [conan-io/conan#3619]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan version: 1.7.4
os: Windows 7
Python 3.6.5

We are using multiple python_requires calls in our recipes. It seems that a second python_requires call overwrites objects of the previous python_requires call.
Given the following two python modules:
![module1](https://user-images.githubusercontent.com/39289804/46060018-17c37f80-c151-11e8-845a-efbcd70c4b24.png)
![module2](https://user-images.githubusercontent.com/39289804/46060021-1d20ca00-c151-11e8-88af-ec511cd13fbc.png)

If I import both modules via the python_reuqires I would expect the follwing behavior:
![expectedbehavior](https://user-images.githubusercontent.com/39289804/46060099-5f4a0b80-c151-11e8-87a1-e1e86e78326f.png)

But the behavior is the following:
![currentbehavior1](https://user-images.githubusercontent.com/39289804/46060227-ff079980-c151-11e8-93d7-694e4e5ca4b4.png)
So the second python_requires overwrites the function and the variable from the first python_requires:
![currentbehavior](https://user-images.githubusercontent.com/39289804/46060234-05961100-c152-11e8-9927-56fa4c179c2e.png)

This seems a bit confusing to us. 
Can you please have a look at this? 

Thanks!

**Comment by ahauan4** [comment]
I think we have the same problem here.
We want to define a list of packages in a Python module which we want to import into our recipe via 'python_requires'. The Python module defines a global variable called 'packages'.
It works as long as we only import one module, but as soon as we import a second one with the same variable 'packages' defined, the variable of the first module gets overwritten.
Maybe you can distinguish the modules internally by giving each one internally a different hash?

**Comment by jgsogo** [comment]
I think it can be improved by assigning a different name to each loaded module, almost the same behavior implemented for the plugins functionality [in these lines](https://github.com/conan-io/conan/blob/fccb7c1a6ce65849a151ec57f44d1f3990cad600/conans/client/plugin_manager.py#L98).

Thanks for reporting.

**Comment by lasote** [comment]
Let's try to fix it for 1.8
