### ISSUE TITLE
version ranges not always choosing max satisfying version?

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#3627]
Observed in conan 1.7.3 from pip, in both windows 7 (python 3.6.2) and ubuntu 16.04 (python 3.5.2)

I have 3 versions of package foo in my local cache (same 3 that are in my remotes)

    foo/4.1.1.0@user/channel
    foo/4.1.2.0@user/channel
    foo/4.1.3.0@user/channel

in another package, I have

    requires = foo/[^4.1]@user/channel

I expected this to select foo/4.1.3.0@user/channel. But not only does it not do so, it does not seem to be entirely consistent from run to run what version it *does* select.

This appears to be due to a bug in node-semver, but I figured I should start here before taking it to an upstream you might not even be following anymore... You've got the conan version pinned specifically to 0.2.0.[0.3.0 has been out for 9 months](https://github.com/podhmo/python-semver/releases/0.3.0), and I see #2172, #2307 suggesting changing away from it.

Having 4 digit versions like this is not strictly semver-compliant, but this particular package has to provide versioned win32 manifests, and those mandate a 4-digit version number (as does the version resource in the library files). I figured it was best to keep the conan version consistent with this, and that the last .0 would just be ignored per semver. But instead, the python semver package seems to take the first, second, and *last* of the dotted fields for major/minor/patch in loose mode, ignoring the 3rd field where the difference is.

```python
>>> from semver import make_semver, max_satisfying

>>> make_semver('4.1.3.0', loose=False)
ValueError: Invalid Version: 4.1.3.0

>>> make_semver('4.1.3.0', loose=True)
<SemVer 4.1.0 >

>>> max_satisfying(['3.1.1','4.1.1.0', '4.1.2.0','4.1.3.0'], '^4.1',loose=True)
'4.1.1.0'
>>> max_satisfying([''3.1.1', 4.1.2.0', '4.1.1.0','4.1.3.0'], '^4.1',loose=True)
'4.1.2.0'
```

This does not agree with the behavior of the node.js semver package it's nominally a clone of:
https://repl.it/repls/CompetentImpossibleCookie

```js
const semver = require('semver');

console.log('4.1.3.0 -> ' + semver.coerce('4.1.3.0'))
console.log('4.1.3.1 -> ' + semver.coerce('4.1.3.0'))
console.log(semver.maxSatisfying([semver.coerce('4.1.0.0'),semver.coerce('4.1.1.0'),semver.coerce('4.1.3.0')], '^4.1'))
```

Where coercing 4.1.3.0 yields 4.1.3, as might more reasonably be expected

```
4.1.3.0 -> 4.1.3
4.1.3.1 -> 4.1.3
SemVer {
  loose: undefined,
  raw: '4.1.3',
  major: 4,
  minor: 1,
  patch: 3,
  prerelease: [],
  build: [],
  version: '4.1.3' }
```

So this explains why the "max" part isn't working; they're all mis-parsing to 4.1.0. I'm not sure about the rest of the non-determinism, but it appears that semver.max_satisfying is breaking the tie in favor of the version listed first in its input, and suspect search_recipes is probably just exposing the order in which the local filesystem (or remote server; I was using --update when I saw the nondeterminism, trying to get it to find 4.1.3) chose to enumerate the available versions.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Wow, this issue is very unfortunate, indeed.
Yes, we have investigated the possibility to migrate away from node-semver, but we couldn't find any real alternative library. And I would certainly like to avoid having to take over the library and fork and maintain it. Lets discuss about it. I suggest reporting the issue to node-semver and please update here if there is any progress there. Many thanks for reporting this.

**Comment by puetzk** [comment]
Much better in node-semver 0.4.2; it now parses extra digits, or numeric fields in the prerelease/build fields as 'micro' versions. That fixes my use-case, since it now takes the first 3 dotted fields to be major.minor.patch.

Like build metadata, these micro versions don't participate in deciding which version is "max" for the purposes of max_satisfying (ties are still broken by first-in-input), but that's consistent with the semver definition saying they're equal and with the node.js implementation.

**Comment by groovyd** [comment]
On a related aside we are trying to decide how to properly version forked 3rd party libraries with their own semver 3 digit version (eg. OpenSSL 1.0.2p) which incidentally also includes a letter in this case and what we need is support for the ability to add an additional digit at the very end for our edits of their forked version.  Is there a canonical solution to this issue of versioning forked sources?  Will conan properly support say 1.0.2p.x where x is our own internally incremental patches of the original forked code?  We want to retain the original version if possible for clarity and simply want the build to resolve to using the latest version in the case of [^1.0.2].  Apologize if this isn't the right place to ask this as I am unsure of a forum for this sort of question?

**Comment by puetzk** [comment]
poke :point_left: since the fix is available upstream but there's no assignee or milestone in this conan issue, and I'm not sure github notifies when a linked issue changes state.

This is fixed upstream in 0.4.2 and 0.5, but conans is still pinning 0.2.0:

https://github.com/conan-io/conan/blob/9d6f0c55bdd8fe7a886c4487aa6ac2118af0fe56/conans/requirements.txt#L8

**Comment by lasote** [comment]
We will upgrade the `node-semver` dependency. Thanks

**Comment by lasote** [comment]
Conan 1.10 is going to upgrade node-semver to 0.6.1
