### ISSUE TITLE
ConanRunner fails on non-ascii output

### ISSUE THREAD

**Issue by krojew** [conan-io/conan#3629]
I've observed a repeatable failure on ubuntu 18.04 with python 3 when trying to use `tools.SystemPackageTool` to install some packages: UnicodeEncodeError when reading output from dpkg -s. The package in question is `wget` - its description contains non-ascii characters which result in the given exception. The problem has a workaround: `tools.SystemPackageTool(runner=ConanRunner(log_run_to_output=False))`, but the issue should be fixed in the runner itself.

Steps to reproduce:

1. Launch ubuntu 18.04 via docker.
2. apt install python3-pip
3. pip3 install conan
4. Use tools.SystemPackageTool to install wget.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, this could be a bug that might be fired for different locales other than English. Which locale are you using? Might be necessary to force change locale to reproduce. 
Thanks for reporting!

**Comment by krojew** [comment]
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

**Comment by memsharded** [comment]
This issue is very outdated, Conan has converged to utf-8 management in Python 3, and most of the above pieces have been completely revamped. Closing as outdated, please create new tickets if necessary
