### ISSUE TITLE
How to build with conanfile.py inside a subdirectory?

### ISSUE THREAD

**Issue by ttencate** [conan-io/conan#3635]
I'm working on a library which is built with CMake and will eventually be packaged using Conan (but should be buildable without). I don't want to clutter up the source tree, so I envision something like this:

**Scenario 1**

```
CMakeLists.txt  # The main build file (Conan-independent)
src/
  *.cpp
include/
  *.h
conan/
  CMakeLists.txt  # The wrapper that includes conanbuildinfo.cmake
  conanfile.py
  test_package/
    CMakeLists.txt
    conanfile.py
    test_package.cpp
```

Using Conan 1.7.4, I can't find a way to accomplish this. The problem is that neither of the options for copying sources works here:

* `export_sources` can only copy from the current directory, and if I add `../` to the front of those paths, all goes haywire (understandably).
* The `source()` function is called with the current working directory set to the build directory, and there doesn't seem to be an API to find out where the `conanfile.py` lives, or copy files with a source path relative to `conanfile.py`.

---

So, second best would be moving `conanfile.py` up one level, to the root of the source tree, but leaving the rest where it is:

**Scenario 2**

```
CMakeLists.txt  # The main build file (Conan-independent)
src/
  *.cpp
include/
  *.h
conanfile.py
conan/
  CMakeLists.txt  # The wrapper that includes conanbuildinfo.cmake
  test_package/
    CMakeLists.txt
    conanfile.py
    test_package.cpp
```

Now I can use `export_sources` as usual.

However, now the `test_package` is not found. The only way to override the location is with `conan create -tf conan/test_package`, but this is easy to forget, which results in the package test not being run, silently.

---

For now, my workaround is to move the `test_package/` to the top level as well:

**Scenario 3**

```
CMakeLists.txt  # The main build file (Conan-independent)
src/
  *.cpp
include/
  *.h
conanfile.py
conan/
  CMakeLists.txt  # The wrapper that includes conanbuildinfo.cmake
test_package/
  CMakeLists.txt
  conanfile.py
  test_package.cpp
```

It works, but now has a lot of Conan-related clutter at the top of the source tree.

---

Is there a way to make Scenario 1 work? If not, one of these APIs would help:

* An `export_sources_base` variable which defines where `export_sources` is relative to.
* A `self.conanfile_folder` available in the `source()` function, containing the absolute path to the directory containing `conanfile.py`.
* A `self.copy()` function available in the `source()` function, whose source paths are relative to `conanfile.py` and destination paths are relative to the source directory.

**Comment by Johnnyxy** [comment]
hi there,
I have tried something similar in the past and what you wanted works.

This does copy the sources (originating from conanfile path):
exports_sources             = "../*"

For "loggability" of the called commands and paths I always use full paths.
This has the advantage that there are no assumptions for paths.

I call conan from anywhere with this command lines:

```
conan install --install-folder="c:\tmp\install" --profile="C:\path\profile_filename" --option shared="True" "C:\path\to\conanfile.py"

conan source --install-folder="c:\tmp\install" --source-folder="C:\tmp\source" C:\path\to\conanfile.py

conan build --install-folder="c:\tmp\install" --source-folder="C:\tmp\source" --build-folder="c:\tmp\build" --package-folder="c:\tmp\package" "C:\path\to\conanfile.py"
```

You can give conan the full path to the conanfile and it will run fine.

**Comment by jgsogo** [comment]
This issue (scenario 1) is the same, I think, as the one here (https://github.com/conan-io/conan/issues/3635). As it is said in the associated PR (#2676) there are some ideas to address it, but implementation may be delayed to version 2.0 if it is not important/urgent, is this your case?

About the alternate scenarios, it may be worth thinking about number 2, an allow specifying inside the conanfile.py where is the test_package directory relative to the recipe file. Does it make sense, @memsharded?

**Comment by ttencate** [comment]
Thank you both! I didn't want to copy stuff like `.git` and `build/`, so instead of `export_sources = ["../*"]` I used a whitelist like `["../src/*", "../include/*"]`. Then it seems like some directory components (`src`, `include`) get stripped off. I guess that's exactly #2675 that @jgsogo tried to link to. No urgency on that PR from my side though, just a minor annoyance!

@jgsogo @memsharded Yes, being able to specify the location of the test package from inside `conanfile.py` would be awesome! And not just for this specific use case either, I would think.

**Comment by jgsogo** [comment]
I think that I can close this issue. I've opened a new one with the `test_package` feature request and the other topics will be handled in the referred issues/pr.

Thanks!

**Comment by memsharded** [comment]
By the way, @ttencate are you aware of the [SCM feature](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm-experimental)? It can work for conanfile.py in subfolders. It operates without actually embedding the source in the recipe, but just storing the git repo commit and URL address to be able to get the sources if necessary from there.

**Comment by ttencate** [comment]
@memsharded In this case I'm adding the conanfile right next to the source (our own in-house library), so using `scm` would mean that I'd need to commit and push any code changes before building the package, right?
