### ISSUE TITLE
[Question] calculate build_id/package_id by ignoring build_type

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#3637]
Hi there,

situation
----------
I have a third party library (lets call it "tp_lib")that has serval .lib/.a/.dll/.so files for debug and release in one folder (supplied by the vendor) with a total size of around 1gb. I created a conan recipe for that so that I can pull in the tp_lib files for linking.

I use this conan package as dependency in my own library recipe ("o_lib").
When I build o_lib as debug conan pulls the "tp_lib" and puts the package into the local repository.
At link time this package will be used.

Additionally when I build the release version of o_lib conan pulls the tp_lib again and puts it into a different path.

This is caused by the "package_id" of tp_lib I think.

what I tried
------------
No I tried to ignore the "build_type" in the tp_lib recipe with the following code:
``` python
    def build_id(self):
        self.info_build.settings.build_type = "Any"

    def package_id(self):
        self.info.include_build_settings()
        self.info.settings.build_type = "Any"
```

result
----------
Sadly when I call conan install on my lib o_lib the dependency list shows different ids for debug and release.

question
----------
How can I ignore the build_type in the dependency recipe (tp_lib)?

Best regards :)

**Comment by lasote** [comment]
I think the correct way is to do this in the `tp_lib`:

```
    def package_id(self):
        del self.info.settings.build_type
```

**Comment by memsharded** [comment]
Hi @Johnnyxy 

Just in case:

>     I have a third party library (lets call it "tp_lib")that has serval .lib/.a/.dll/.so files for debug and release in one folder (supplied by the vendor) with a total size of around 1gb. I created a conan recipe for that so that I can pull in the tp_lib files for linking.

Even if the vendor provides the debug and release files together, there is nothing that inhibits you from packaging 2 different binary package, one for release and another for debug, which would be the recommended approach. Is there some restriction? Have you tried that?

Also, instead of removing the ``build_type`` in package ID, have you tried directly removing it from the ``settings``? I'd like to learn how you are consuming it, if you still need the build_type to consume.

Are you sure you want to use ``self.info.include_build_settings()``? Are you using it as a build_require?

**Comment by Johnnyxy** [comment]
Hi @memsharded 

third party lib background
---------------------------
The vendor of the third party lib has different libs for each target, compiler, runtime lib etc.
We get supplied with a package for each target variant that we request from the vendor.

what I build
------------
I am building the following targets matrix
- Windows, x86/x64, Debug/Release, Visual Studio 10/12/14/15.
- QNX, x86, 6.5, Debug/Release, QCC 4.4.2, runtime libstdc++ (will be more in the future)

packaging 2 different binary package
--------------------------------------
At the moment I am already building different packages and have them in seperate folders in the conan repository.

Just for the Windows builds this means that at least 16 times the third party lib (tp_lib) will be put into the repository. This takes up time, bandwith (pulling tp_lib from central fileserver) and local space on the build machine.

The problem ist primarily the occupied space:
def source(self):
- Conan pulls a ZIP file with the tp_lib into the source folder (occupied space around 500 MB).
- Conan then unzips the ZIP file (occupied space 1,7 GB).
- Conan deletes the ZIP file (occupied space 1,25 GB).

def package(self):
- Conan copies the content to the package folder (occupied space 2,5 GB).

This I can "optimize" through deleting the source folder content leading to 1,25 GB occupied space in the end for one package.

Now I was thinking about minimizing that further (into half) as the tp_lib always comes with debug and release files together hence the try to manipulate the package_id.

removing the build_type from the settings
-------------------------------------------
I already tried that in the past for an other problem. But as I have to distinguish between debug and release files for linking I have to have the settings.build_type. At least I think so :).

... want to use self.info.include_build_settings()? 
------------------------------------------------
The files that comes from the third party vendor consists of additional stuff too. There are binaries included which have to be executed as pre-build-step for code generation. This generated code uses the supplied libs. As it is not clear at the moment if the binaries 100% 64 bit as the vendor stuff executes serval binaries some windows executables some Java. We have different vendor "host" packages for different systems (Windows x86, x64; Linux; QNX; etc.) that is the reason why I have "include_build_settings()" included. At the moment it is not 100% nessescary but as I can see it does no harm.

include_build_settings() ... Are you using it as a build_require?
------------------------------------
The third party lib is included as dependency in the `build_requirements(self)` function of depending recipies, yes. Due to the fact that the vendor package generates code (see previous section).

**Comment by Johnnyxy** [comment]
I am closing this issue as I solved the problem but splitting the recipes for building (SDK packages) and target system libs (target packages).

Now I have two recipes:

librarysdkinstaller/version@user/channel
-----------------------------------------
Provides all build tools for the development environment (os_build/arch_build).

library/version@user/channel
------------------------------
Provides all libs for the target system (os/arch).
