### ISSUE TITLE
[scm] Rework SVN is_pristine() function

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#3640]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).

The actual implementation of SVN `is_pristine` function could fail by the following two cases:

* When using externals there will be X in the first column and also the output will come for the main project and all externals libs, so that output.splitlines()[:-1] will not work.
* When using the -u parameter, there will be shown files that are updated on the server with an * . Because we want also to be able to checkout an specific revision, I think this column must also not be used.

May be we should use the --xml option, to better parse the files.

To get the SVN #3192 pull request into the develop branch, we postponed this issue.

**Comment by jgsogo** [comment]
I agree we need to rework the `is_pristine` function in order to address the first point you comment (and the best way may be to go for the ``--xml`` output).

About the second one, it is not an issue because the actual call is ``svn status -u -r <rev>`` (where rev is checked out revision), so there shouldn't be files marked with the ``*``.

Nevertheless, the XML parsing with change it all.

Thanks!

**Comment by jgsogo** [comment]
For the ``is_pristine`` function it will be enough to parse the XML output with an XPath ``//wc-status/@item`` and check for that attribute values. According to the [schema defined in the SVN repository](https://svn.apache.org/repos/asf/subversion/trunk/subversion/svn/schema/status.rnc):

```
attlist.wc-status &=
  ## Item/text status.
  attribute item {
    "added" | "conflicted" | "deleted" | "external" | "ignored" |
    "incomplete" | "merged" | "missing" | "modified" | "none" |
    "normal" | "obstructed" | "replaced" | "unversioned"
  },
```

so, any value but ``external``, ``ignored``, ``none``, ``normal`` or ``unversioned`` will return NO-pristine.

**Comment by climblinne** [comment]
> About the second one, it is not an issue because the actual call is `svn status -u -r <rev>` (where rev is checked out revision), so there shouldn't be files marked with the `*`.

But at a later point you we checkout the repository at a specific revision. Then you will get the `is_pristine` invalid, because newer revisions are available.

**Comment by climblinne** [comment]
> so, any value but `external`, `ignored`, `none`, `normal` or `unversioned` will return NO-pristine.

I would also include the `unversioned`value, because you want to be sure, that you get the same result, when checking out a fresh copy of the repo. Also I would look for `mixed revsions`, which happens often in subversion. 
My be we should add some parameter to the `is_pristine` or to the svn constructor. A good reference is the `subwcrev` [tool](https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-subwcrev-keywords.html)

**Comment by jgsogo** [comment]
> But at a later point you we checkout the repository at a specific revision. Then you will get the is_pristine invalid, because newer revisions are available.

For me, the concept of ``pristine`` is "without changes regarding the checked out version", not that there aren't changes upstream, it is like "your working copy has no pending changes". This is the concept we must agree on and document it. Do you think it has to be understood in another way?

> I would also include the ``unversioned`` value, because you want to be sure, that you get the same result, when checking out a fresh copy of the repo. Also I would look for ``mixed revsions``, which happens often in subversion. 
- ``unversioned``: agree with that, the user should add it to the ignore list.
- ``mixed revisions``: in this case the attribute (xpath) ``/wc-status/repos-status/@item`` will be ``modified``, so it will return NO-pristine. Anyway, I have added a test for this in the last commit.

**Comment by climblinne** [comment]
> For me, the concept of `pristine` is "without changes regarding the checked out version", not that there aren't changes upstream, it is like "your working copy has no pending changes". This is the concept we must agree on and document it. Do you think it has to be understood in another way?

Yes, the same for me. 

> * `unversioned`: agree with that, the user should add it to the ignore list.
> * `mixed revisions`: in this case the attribute (xpath) `/wc-status/repos-status/@item` will be `modified`, so it will return NO-pristine. Anyway, I have added a test for this in the last commit.

Please don't check against remote repository. Use `svn status -v --xml` instead `svn status -u --xml`. I already write something in your pull request, how to check for mixed revision.

I also would check for externals, that they are all fixed to a specific revision. Just to be sure, that the version is 100% reproducible, when the revision is checked out at a later point.

**Comment by jgsogo** [comment]
Yes, you are right, having no internet connection does not imply non-pristine working copies, but we need to call with `-r [--revision ARG]` in order to compare against a given revision, and passing `-r` requires `-u [--show-updates]` that requires having access to the server.

```
svn: E205000: --revision (-r) option valid only with --show-updates (-u) option
```

Also, we must keep in mind that this function is only used to print a warning message: _"Repo status is not pristine: there might be modified files"_. I'm not sure if it's worth implementing a workaround when there is no access to the server just to avoid this message.
