### ISSUE TITLE
Log cpp_info as json in conan outputs

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3641]
Very regularly when creating packages, both OSS and enterprise side, a lot of time is spent troubleshooting various problems relating to package consumption.  Often, the problem is a result of incorrect `package_info()` method.  Very often, looking at a recipe does not make it clear what the actual values of `cpp_info` will be.  This is because we have dynamic mechanisms like `tools.collect_libs()` and also now with `python_requires`, but even simple conditionals based on platform and settings can make it virtually impossible to determine what was passed during a build.  Today, the only way to investigate what was actually passed is by looking at the `conanbuildinfo` files which were generated, and in docker builds, those are deleted on the fly. 

The request here is self-explanatory, simple to implement, and i think would be universally useful.  Add a logging statement that shows exactly the values of `cpp_info`, which is really a simple dict()`.  My suggestion would be to serialize it as JSON, but that's a minor detail. 

Printing it by default would be far too verbose.  However, Conan has some special log settings already, so perhaps there could be a new log setting to control this item. 

For example:  `CONAN_LOG_CPP_INFO`

I'm pretty sure this will dramatically improve the debugging experience for users who are starting to deploy Conan in large enterprise codebases.  I will probably be turning it on for all my CI builds in my company. 

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I understand and like the idea. We need to decide how will it look to implement it.  Could make sense to include a node in the [install json output](https://docs.conan.io/en/latest/reference/commands/output/install.html) in each "package"?

**Comment by solvingj** [comment]
Yes, love that idea, so i've opened a separate ticket for enhancing the outputs of other commands. https://github.com/conan-io/conan/issues/3648

**Comment by jgsogo** [comment]
I'm working on this, currently I have an implementation for commands ``install``, ``create`` and ``info``, see it in action:

```bash
conan install zlib/1.2.11@conan/stable --json tmp.json
```

and the output is as follows (right now I'm logging all the attributes from ``CppInfo`` that do not starts with an underscore):

```json
{
    "error": false,
    "installed": [
        {
            "recipe": {
                "id": "zlib/1.2.11@conan/stable",
                "downloaded": false,
                "cache": true,
                "error": null,
                "remote": null,
                "time": "2018-10-10T10:28:28.351753",
                "dependency": true
            },
            "packages": [
                {
                    "id": "0eaf3bfbc94fb6d2c8f230d052d75c6c1a57a4ce",
                    "downloaded": false,
                    "cache": true,
                    "error": null,
                    "remote": null,
                    "time": "2018-10-10T10:28:28.356103",
                    "built": false,
                    "cpp_info": {
                        "includedirs": [
                            "include"
                        ],
                        "libdirs": [
                            "lib"
                        ],
                        "resdirs": [
                            "res"
                        ],
                        "bindirs": [
                            "bin"
                        ],
                        "builddirs": [
                            ""
                        ],
                        "libs": [
                            "z"
                        ],
                        "rootpath": "/Users/jgsogo/.conan/data/zlib/1.2.11/conan/stable/package/0eaf3bfbc94fb6d2c8f230d052d75c6c1a57a4ce",
                        "version": "1.2.11",
                        "description": "A Massively Spiffy Yet Delicately Unobtrusive Compression Library (Also Free, Not to Mention Unencumbered by Patents)"
                    }
                }
            ]
        }
    ]
}
```

maybe remove ``version`` and ``description``?
maybe resolve relative paths?

**Comment by solvingj** [comment]
Looks really good!

**Comment by jgsogo** [comment]
Yes and yes, although I prefer to do it well:

 -  I wonder why ``version`` and ``description`` are included in ``conanfile::cpp_info``, I'm going to investigate if those data can be removed from it (and so won't appear here in the ``packages/cpp_info``) and be stored at the recipe level (at least the description).

About the ``recipe/id``, I'll keep it, I like to have an ``id`` field, but we can add all the individual fields to the output too.

**Comment by solvingj** [comment]
Yes, both are of value.  If i want the name, i don't want to have to deconstruct it.  If i want the ID, i don't want to have to construct it.  I can easily see wanting both situations.

**Comment by lasote** [comment]
I'm not opposed to including the separated fields. But it must be done the same way in all json outputs: https://docs.conan.io/en/latest/reference/commands/output/install.html

**Comment by jgsogo** [comment]
I think that all ``json`` outputs use the same piece of code, that's the reason it was so easy to add the ``packages`` field to ``install`` and ``create`` commands at once.

I'll try to do the following (sorry for dirtying the issue):
 1. add ``name``, ``version``,... to ``recipe`` field.
 1. move ``version`` from ``packages`` to ``recipe``.
 1. move ``description`` from ``packages`` to ``recipe`` (or remove it, I don't know if we want this information in the ``json``)

[1] will be done in the PR associated to this issue, [2] and [3] will be more complicated (doing them right, not just removing and adding from/to dicts) as ``cpp_info`` is used at several places without the ``conanfile`` data, this will require some refactor... and I don't know yet if we want to do it.

**Comment by solvingj** [comment]
If anything would require any significant refactor just for cosmetics/convenience, i vote to skip.

**Comment by jgsogo** [comment]
PR for the ``cpp_info``, ``name``, ``version``, ``user`` and ``channel`` is already submitted and ready for review (#3717) 🎉 

---

I have also done some work in another branch (https://github.com/jgsogo/conan/tree/issue/3641-version-description) where I remove ``version`` and ``description`` from ``cpp_info`` so they won't appear in the json output. I think that that info should not be stored in ``cpp_info``, but then I have to store it (at least the version) in the ``conanfile.deps_cpp_info`` and I have to use a reference instead of a string for the dict key, and.... a lot of little changes 😄  but I think it is the right thing to do.
