### ISSUE TITLE
Question about python_requires and settings and header_only

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3642]
When using `python_requires` to distribute a base class, I realized I am confused about how settings will be resolved. 

On one hand, my "Base" recipe is like a header-only.  There should be only one.  Thus, I want to to be resolved as `header_only` when doing `conan create` on this package. 

On the other hand, for all the recipes that inherit from it, I want them to have all the settings by default (`os`, `compiler`, `arch`, `build_type`).  Thus, I want to have them all in the base class. 

Guidance?

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by solvingj** [comment]
I've currently defined the base recipe `package_info` method as follows: 
```
    def package_id(self):
        if self.__class__.__name__ == "BoostBaseConan":
            self.info.header_only()
        else:
            <the actual shared logic>
```

**Comment by chrahunt** [comment]
You can separate the two: have a `ConanFile`-derived class in your `conanfile.py` that represents your package and then have a factory method or a class with a name that starts with `_` (which are ignored in the search for the actual ConanFile class) to serve as your base class.

**Comment by solvingj** [comment]
Thanks for the tip!
