### ISSUE TITLE
[cross build] Proposal to add `compiler_build` setting

### ISSUE THREAD

**Issue by grisumbras** [conan-io/conan#3644]
There are situations where a project is using a tool built by Conan for its build. In case of a cross-build this tool should often be built with another compiler. An example of such a project is Qt, which builds `qmake`, `moc`, `uic`, `rcc` and several other development tools.

Another example would be any project that `build_requires` its build system. Even though the user can specify `compiler` for the build system package in profile or conanfile, it could become somewhat cumbersome, when several dependencies use different build systems (or other dev tools), all built by Conan.

As such, I propose adding `compiler_build` setting that will specify the compiler used to build binaries that are supposed to be used on the build platform. Variables like `CXX` and `CC` that are used for `compiler` setting will be paired with similar variables suffixed with `_BUILD` (or prefixed with `BUILD_`, as it seems LLVM is using this convention).

As a result, a profile like the following could be used to build Qt using clang as compiler for the build system and MinGW as compiler for the host system:

```ini
[settings]
os=Windows
arch=x86
compiler=gcc
compiler.version=8

os_build=Linux
arch_build=x86_64
compiler_build=clang
compiler_build.version=7.0

[environment]
CXX=/opt/mingw/bin/i686-w64-mingw32-g++
CC=/opt/mingw/bin/i686-w64-mingw32-gcc
CXX_BUILD=/opt/clang/bin/clang++
CC_BUILD=/opt/clang/bin/clang
...
``` 

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @grisumbras 

Yes, you have spotted a flaw in the current cross-building and settings model. Just before conan 1.0 we introduced ``os_build`` and ``arch_build``, just to realize that it was not complete enough and there are some cases for build_requires and transitive requirements of build_requires. We decided not to go further down the ``compiler_build`` model, but instead something like the following:

- Use always the same settings, as they are today: compiler, arch, os, etc.
- Define 3 contexts for settings: build, host, target (as by the GNU convention)
- Be able to define settings values differently for each context.
- Apply switch and transitivity of context when ``build_requires``.

It is a very high level idea of the approach, and will require time, and probably to break something (that means at least conan 2.0), but I think it is the way to go.

In the meantime, the main workaround is to separate the build graphs, and use 2 steps. In one step the tools packages can be created, abusing the current ``compiler`` as ``compiler_build``, or even hardcoding it, clearing the settings for later, then using them in a later second step.

**Comment by grisumbras** [comment]
That's a very interesting idea. Looking forward to it.

**Comment by memsharded** [comment]
The ``profile:build`` has been implemented in Conan 1.X long time ago, that define ``settings_build`` (not only compiler_build). The cross-build model with build&host profiles is opt-in in Conan 1, and will be used always in 2.0. I think this can be closed.
