### ISSUE TITLE
conan remove all packages from remote

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#3645]
Conan version: 1.7.4
Artifactory Version 6.3.3

When I try to remove all packages from local conan cache, it works fine
`conan remove MyPkg/1.2@demo/stable -p -f`

When I try to remove from remote artifactory, it does not actually remove the packages
`conan remove MyPkg/1.2@demo/stable -r local -p -f`

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @sunj1 

I think this is a duplicate of https://github.com/conan-io/conan/issues/1314. Please check and if true, close this one and follow the other. Thanks!

**Comment by sunj1** [comment]
Yes, it seems to be a duplicate.
I will follow on the other ticket.
Thanks :)
