### ISSUE TITLE
Add absolute paths of packages in cache to various command outputs

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3648]
Per conversation with @memsharded , this issue is to add to the path information for dependencies to various outputs. The ones I know of off hand are `conan install` and `conan info`. This is for enabling integrations with other tools, which want to extract files directly from cache for use outside conan.  The absolute path to package root is needed, along with all the package_info information: `cpp_info`, `env_info`, etc.  In theory, we should be able to combine the `package_root` variable with things like `cpp_info.libdirs` to get to the directory. 

---Edit---
After thinking about this further, I would like to extend this request. I have seen the `conanmanifest.txt` which shows the complete list of files. I would also like this available in the JSON output, since more often than not, one of the first things I'll be doing is enumerating the files. Since this is asking for a lot more now, I will explain reasoning. 

Currently, Conan solves a group of problems related to dependency management at development time.  It's scope stops at a certain point, and does not cover things like making OS packages (`deb`/`rpm`/`msi`/`brew`), nor runtime deployment to servers and many other "post-Conan operations".  This is a very good and healthy scope boundary for Conan.

However, this is where integration points are important.  There is an obvious and well-documented need to take the binaries out of Conan for these operations. All current mechanisms for getting binaries out of Conan are based in the recipe, meaning the package has to have made some arrangements to be used in this way.  This is likely useful for some cases, however this is not an usable integration point for external tools and scripts which wish to interact with Conan directly via client API on any package in a uniform way, regardless of the recipe contents.   For other tools to integrate with Conan, we need a client API that tells us everything we might need about a package in order to extract various files from it and use it elsewhere. 

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
I think I need a little bit more information regarding this issue/request.

The absolute path part: it may be already covered using the ``json`` output with the new fields in #3641, where else do you think an absolute path will be useful?
 
About listing every file in the package, it may make sense in the new ``inspect`` command, maybe have an option in this command to list all these files?

**Comment by solvingj** [comment]
Yes, the absolute path is covered using the json output, and I found out later we can get it from `conan info ... --paths` , but not as json unfortunately, so we parse the stdout as-is.  

Yes i like putting it on the inspect command as an option, something like `--include-manifest` or `--show-files` or `--files` or something.

**Comment by solvingj** [comment]
Yes, lets close.
