### ISSUE TITLE
Update Gitlab CI template

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3649]
To help us debug your issue please explain:

When running `conan new` command, Gitlab template provided is outdated.

- Conan Reference is not more required by CPT
- New versions of GCC and Clang are not listed

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Is this going to be closed by #3649?
