### ISSUE TITLE
[Commands] Return package_id from export_pkg

### ISSUE THREAD

**Issue by chrahunt** [conan-io/conan#3654]
**Conan version:** 1.7.4
**Python version:** 3.7

I am using the conan api to export a package and upload it. For example:

```python
from conans.client.conan_api import Conan
conan, _, _ = Conan.factory()

package = 'package'
version = '0.1.0'
user = 'chrahunt'
channel = 'develop'

conan.export_pkg(
    'conanfile.py',
    package,
    channel,
    user=user,
    version=version,
    package_folder='dist')
conan.upload(
    pattern=f'{package}/{version}@{user}/{channel}',
    all_packages=True,
    remote_name='artifactory')
```

I would like to upload ONLY the package that was exported to the local cache in the call to `export_pkg`. If `export_pkg` could return the package reference then I think it would help a lot. A similar request was made and fulfilled in #1985 for `conan create` (which I think can be closed actually).

----

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, this totally makes sense. I think it is doable and shouldn't be very complex.
Just the return, wouldn't be just the ID, but most likely a dict (json-like), that could contain also extended information about the command results. Lets try to address it in next 1.9.

**Comment by Laundry-96** [comment]
What do you mean by 'extended information'? I am willing to implement this, I'd just like to get it correct the first time :).

**Comment by memsharded** [comment]
For example, how many files have been exported. But this is not necessary to implement it now, just to return a json like:

```json
{"package_reference": "pkg/version@user/channel:binaryID"}
```
So it will be possible to return more information in the future without breaking. 
Ask if you have any question about the code while trying to implement it. Many thanks!
