### ISSUE TITLE
conan config from a specific branch/tag from a git repository

### ISSUE THREAD

**Issue by chreniuc** [conan-io/conan#3656]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.7.4
Git version 1.8.3.1
Centos 7.1.503

I want to install the settings from a git repository, but from a specific branch or tag. I tried: 

```bash
conan config install "git@gitlab.gitlabserv.com:chreniuc/conan_config.git" --args "-b tag"
```

But  I get an error:

```bash
Trying to clone repo  git@gitlab.gitlabserv.com:chreniuc/conan_config.git
Unknown option: -b
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
ERROR: config install error. Can't clone repo: Command 'git -c http.sslVerify=True -b tag clone "git@gitlab.gitlabserv.com:chreniuc/conan_config.git" config' returned non-zero exit status 129
```

I also tried:

```bash
conan config install "git@gitlab.gitlabserver.com:chreniuc/conan_config.git -b master"
```

But I got this error:

```bash
ERROR: I don't know how to process git@gitlab.gitlabserver.com:chreniuc/conan_config.git -b master
```

Does conan support this feature? Am I missing something? I tried to look for an example, but I couldn't find any or any documentation related to this.

The use case for this is: we want to have different versions of the config for conan. We have a git repository and tags for each version. Can this be achieved?

Also, another thing to notice is that, when you run:
```bash
 conan config install --help
```
For **--args** you get:
```bash
String with extra arguments for "git clone"
```

But if you take a look at the command that was generated by conan, you can see that those args are passed to the `git` command not to the `git clone`:

```bash
Command 'git -c http.sslVerify=True -b tag clone "git@gitlab.gitlabserv.com:chreniuc/conan_config.git" config' returned non-zero exit status 129
```

**Comment by danimtb** [comment]
Setting this as high priority as it could be useful to clone recusrively submodules for hooks in the conan config folder
