### ISSUE TITLE
Conditionally restrict options?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3657]
I would like to conditionally restrict allowed option values depending on `settings` attribute:
```python 
class TestConan(ConanFile):
    options = {"shared": [True] if <settings.os == "windows"> else [True, False]}
   ...
```
Is it possible somehow? Using `configure()` method | can remove a option, but not restrict its values.

**Comment by chreniuc** [comment]
You can throw an exception in the configure method. If the user gives an option that is not valid for the specific setting you can throw an exception and restrict the usage of that option.

This is almost the same behavior for an invalid option in conan. You gen an error that the option doesn't exist.

**Comment by uilianries** [comment]
Hi @db4 

You should prefer `config_options` instead of `configure`.

`config_options` was designed to change package options and `configure` is related to package settings.

In your specific case you could:

```python
def config_options(self):
    if not self.options.shared and self.settings.os == "Windows":
        raise Exception("Only pkg:shared=True is supported on Windows")
```

**Comment by db4** [comment]
Thanks. Throwing an exception (or `del self.options.shared`) seems to be quite enough.
