### ISSUE TITLE
[Question] Echo commands executed by conan

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#3658]
How can I achieve that the sub-commands executed by conan (in particular those executed via self.run) are echoed to stdout?

**Comment by uilianries** [comment]
You could use `CONAN_PRINT_RUN_COMMANDS` env var:

https://docs.conan.io/en/latest/reference/config_files/conan.conf.html#log

**Comment by sigiesec** [comment]
Thanks a lot, that was what I was looking for. I tried to search the docs for "self.run", but that does not yield good results.
