### ISSUE TITLE
Support "<this_package>" behavior in profiles and CLI

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3659]
Currently, we have a set of 16 common generic profiles in our organization. For each of these profiles, we want to make a `shared` and a `static` version:
So, for example, we have: 
`msvc_15_release_x86_mt`

We want: 
`msvc_15_release_x86_mt_shared`
`msvc_15_release_x86_mt_static`

Sadly, this is not currently possible, and it should be.  There are two ways to implement this.  
1. To make unprefixed options be immediately auto-prefixed with `current_package_name` upon processing.  
2.  To add an explicit "macro" for specifying options for current package:  example:  `<current_package>:shared=True`.  The first seems perfectly reasonable, the second is suggested as a compromise if the first is somehow impossible (which I doubt). 

The most commonly-known problem relating to un-prefixed options has been with `test_package`. 
In early days of Conan, this was commonly tried: 

`conan create . bincrafters/testing -o Shared=True`

It seemed a logical thing to do, and it seemed to be supported.  However, it would break down because `Shared=True` would get applied to the test package, which didn't have Shared option.   It seemed to me this should have been able to be fixed so that the option only applied to the package being created or installed or whatever.  However, it never was, and instead, it was widely advertised that we should not do this, but rather always prefix options.  Thus, we should do: 

`conan create . bincrafters/testing -o my_package:Shared=True`

This has been mostly acceptable, but still annoying.  In practice, it often results in some file reading and string manipulation to figure out the recipe name and concatenate it with `:shared` to prepare the CLI call.   For example, Conan Package Tools has had to provide an option `shared_option_name`, and implement hacky logic to deal with this, and users of Conan Package Tools have previously had to hard-code the option name :  https://github.com/conan-io/conan-package-tools/blob/c6ecd47dc52f9c07a37c6fd0585f6bba851331cd/cpt/packager.py#L349

CLI calls were manageable, the profile situation is not. It simply cannot really be scripted around, which makes it impossible to implement profiles which define generic options (which is extremely desirable in a codebase which has a substantial number of uniform option names).  Thus, I request that one of the two implementation options be pursued to enable generic option strings. 

Of note, a much more difficult and advanced feature of "wildcard options" (`*:shared=True`) was implemented in the meantime.  It's worth pointing out that default-prefixing should be dramatically easier to implement, and has far less consequences to think through.  It's also worth pointing out that this is not a substitute for the feature being requested here. It has completely different characteristics.  

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Understood the use case. However it really seems that this is a 2.0 feature, as it would be breaking (the second option looks too much of a temporary patch)

**Comment by solvingj** [comment]
Are you leaning toward the first one then?  What is the current behavior of un-prefixed options in profiles?  It actually seems to be working as-desired in our case, since we're not using test packages internally yet.

**Comment by memsharded** [comment]
Yes, the first one, to automatically prefix them with the package. But this would be breaking when ``test_package`` exists, and this is what we want to normalize for conan 2.0. We are discussing how conan 2.0 features will be introduced and developed.
