### ISSUE TITLE
Getting traceback on conan search -x 

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#366]
After uploading a few of my local packages to my own conan server and performing a `conan search -r {REMOTE} -x` I get the traceback as shown below:

![traceback](https://cloud.githubusercontent.com/assets/11735226/16832661/87be891c-49ab-11e6-802f-339925bfe142.PNG)

This is the conaninfo.txt that is in the remote for the respective package: 
[conaninfo.txt](https://github.com/conan-io/conan/files/363252/conaninfo.txt)

Any idea what might be the issue here?

**Comment by memsharded** [comment]
Yes, it is a bug, thanks for reporting. I am trying to fix it.

**Comment by memsharded** [comment]
Ok, I have submitted a PR to fix this: https://github.com/conan-io/conan/pull/368 
I think this is not a very critical issue, and we can wait till next release (will be soon), but please tell me otherwise

**Comment by Blubbz0r** [comment]
Yes, its not very critical for me.

**Comment by memsharded** [comment]
Released in 0.11, please upgrade and re-open if necessary. Thanks for the feedback!
