### ISSUE TITLE
[question] Is manual inclusion of .props required for MSBuild magic to work?

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#3662]
I'm trying to follow the documentation on the ```MSBuild``` helper to conanize an existing .sln and .vcxproj.

So far I've found https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html which says:

```
    def build(self):
        msbuild = MSBuild(self)
        msbuild.build("MyProject.sln")
```

> Internally the MSBuild build helper uses:
> 
> VisualStudioBuildEnvironment to adjust the LIB and CL environment variables with all the information from the requirements: include directories, library names, flags etc.
> tools.msvc_build_command to call msbuild.

which seems to suggest I need do nothing other than call ```msbuild.build("MyProject.sln")```.

But when I do this, I find that while the conan build installs all my listed requirements, my compile line doesn't include any paths to those install locations.  e.g.:

```
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\CL.exe /c /Zi /nologo /W3 /WX- /O2 /Oi /GL /D _WINDOWS /D NDEBUG /D _USING_V110_SDK71_ /D _AFXDLL /Gm- /EHsc /MD /GS /Gy /fp:precise /
         lease\\" /Fd"x64\Release\vc140.pdb" /Gd /TP /errorReport:queue -DNDEBUG -O2 -Ob2 ChildFrm.cpp ClassView.cpp CRCBrowser.cpp CRCBrowserDoc.cpp CRCBrowserView.cpp FileView.cpp MainFrm.cpp OpenCRCDlg.cpp
         ChildFrm.cpp
         ClassView.cpp
```

and predictably my build fails, unable to find required headers:

```
     2>e:\developbp\mmaguir1\src\mmaguir1\murano-mfcapp\build\MainFrm.h(12): fatal error C1083: Cannot open include file: 'murcrc.h': No such file or directory [E:\DevelopBp\mmaguir1\src\mmaguir1\murano-mfcap
         CRCBrowser.cpp
```

I see that there is a ```conanfileinfo.props``` file generated, but nothing in the docs mentions that I must manually add this to my solution -- do I need to?

I guess from the way the docs sounded I though perhaps a reference to the correct headers and libs was being injected into the build env for me.

Related:

- https://github.com/conan-io/conan/issues/3321 "[build system] [MSBuild] Enhance the experience of test_package using MSBuild based projects"

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [Conan v1.5.2 Microsoft Windows v6.3.9600] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by michaelmaguire** [comment]
Hmmm.  Maybe this is my bad:

https://github.com/conan-io/conan/issues/1891 "launch `conan install ../` from existing visual studio project msbuild chain?"

mentions:

> the documentation suggest the following 3 step ... 3.  include property files in project for each configuration

But I haven't found *that* documentation yet...

**Comment by michaelmaguire** [comment]
My bad: https://docs.conan.io/en/1.3/integrations/visual_studio.html

**Comment by memsharded** [comment]
Hi @michaelmaguire 

> I see that there is a conanfileinfo.props file generated, but nothing in the docs mentions that I must manually add this to my solution -- do I need to?

Yes, it is needed, as you pointed out.

It is true that we want to improve the build-helpers, and we might try to do some automatic injection of the properties files, if possible. And the docs will be reviewed. But that will take some time.
Thanks!
