### ISSUE TITLE
Using artifacts.properties per package

### ISSUE THREAD

**Issue by zlalanne** [conan-io/conan#3664]
To help us debug your issue please explain:

Using conan v1.7.4 on Linux.

Conan should allow you to upload additional artifact properties for Artifactory while doing the upload process. I'm aware of the [artifact.properties](https://docs.conan.io/en/latest/reference/config_files/artifacts.properties.html) file, but this is at the global level `~/.conan/artifact.properties`. I think it makes sense to be able to override this file when calling `conan upload`.

The use case we have in mind is putting some build metadata related to our system with the package that got uploaded. 

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
There is some information about that in here: https://docs.conan.io/en/latest/howtos/generic_ci_artifactory.html

Note that although the information of the link talks about CI, it could be done manually too.

**Comment by lasote** [comment]
Yes, the current file `artifact.properties` is global and very limited. 
What is your idea of adjusting the properties per package? Where these properties would come from? We need feedback to improve it. I'm thinking if a Conan plugin (to be released today in 1.8) could be a possibility to adjust the properties, maybe offering a better interface.

**Comment by zlalanne** [comment]
My first thought would be during the `conan upload` command you could add a parameter to pass in an properties file. Something like `--artifacts=artifact.properties`. That would essentially set the properties for anything getting uploaded. This would work well for packages that can generate the properties file outside of the build process.

Another use case might be to add an `properties()` method that can call something like a `self.set_prop(key, value)`. And during the upload process that gets run for the packages being uploaded.

**Comment by MadsBaggesen** [comment]
+1 for this issue, it is still relevant and makes some annoying tight bindings to global space in CI situations

**Comment by memsharded** [comment]
artifacts.properties way to define properties has been removed in 2.0, and replaced by explicit custom extensions to define artifactory properties, please check: https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art

Closing as outdated
