### ISSUE TITLE
[question] 'nmake' is not recognized as an internal or external command when trying to build conan-openssl

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#3665]
Although this question relates to building OpenSSL using Conan, I'm asking to try to fill out my understanding of Conan.

I'm trying to use the Conan recipe from https://github.com/conan-community/conan-boost to build OpenSSL.

What I find is that I get error:

```
E:\DevelopBp\mmaguir1\src\nx\conan-openssl>conan create . PORT/stable -s build_type=Debug
[...]
C:\Users\mmaguir1\.conan\data\openssl\1.0.2e\PORT\stable\build\5e08083bcde36dca41ed981ba123170d62070888\openssl-1.0.2e>perl util\mkdef.pl 32 ssleay  1>ms\ssleay32.def
WARN: replace_in_file didn't find pattern '/MD ' in './openssl-1.0.2e/ms/ntdll.mak' file.
WARN: replace_in_file didn't find pattern '/MT ' in './openssl-1.0.2e/ms/nt.mak' file.
openssl/1.0.2e@PORT/stable: WARN: .
openssl/1.0.2e@PORT/stable: WARN: ----------MAKE OPENSSL 1.0.2e-------------
'nmake' is not recognized as an internal or external command,
operable program or batch file.
openssl/1.0.2e@PORT/stable:
openssl/1.0.2e@PORT/stable: ERROR: Package '5e08083bcde36dca41ed981ba123170d62070888' build failed
openssl/1.0.2e@PORT/stable: WARN: Build folder C:\Users\mmaguir1\.conan\data\openssl\1.0.2e\PORT\stable\build\5e08083bcde36dca41ed981ba123170d62070888
ERROR: openssl/1.0.2e@PORT/stable: Error in build() method, line 193
        windows_make(config_options_string)
while calling 'windows_make', line 181
        run_in_src(make_command)
while calling 'run_in_src', line 123
        self.run("cd openssl-%s && %s" % (self.version, command))
        ConanException: Error 1 while executing cd openssl-1.0.2e && nmake -f ms\nt.mak
```

If I run e.g. ```vcvars64.bat```  from my VC directory:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64>vcvars64
```

Now I can find nmake:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64>nmake

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1064: MAKEFILE not found and no target specified
Stop.
```

And the conan build proceeds.

My question is this: in none of the other Conan recipe's I've used so far did I need to run vcvars64.bat -- what's special/broken about this recipe that it requires that I do so?

Is it the fact that it's not CMake-based?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [Conan v1.5.2 Microsoft Windows v6.3.9600] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
It should work. Have you tried with a newer OpenSSL? `OpenSSL/1.0.2p@conan/stable`
I think it is better if you open the issue in the conan-community organization as it is related to a concrete package and not conan. https://github.com/conan-community/community/issues
