### ISSUE TITLE
[Question] Conan-server health check endpoint

### ISSUE THREAD

**Issue by aledeganopix4d** [conan-io/conan#3666]
Hello,
while working on the monitoring/alerting of our infrastructure I was looking for an endpoint to probe (via http) our Conan server where it could reply 200 when all is fine.
I didn't find any specific endpoint in the docs, did I miss it?
If it's really not implemented would you think it could make sense to add it?

Thanks!

**Comment by uilianries** [comment]
Hi!

On client side is possible to retrieve server status using `server_info`:

https://github.com/conan-io/conan/blob/master/conans/client/rest/rest_client_common.py#L109

The server uses `VersionCheckerPlugin` to fill it response, including version and capabilities.

https://github.com/conan-io/conan/blob/master/conans/server/rest/bottle_plugins/version_checker.py#L7

**Comment by aledeganopix4d** [comment]
Thank you for your answer!
I'll report here how I'm using your information to achieve what I wanted:
Since version 1.7 the Conan server has a new endpoint: `http://<your_conan_url>/v1/ping` which reply with a status code 200 to a simple GET.
That's perfect for monitoring!

**Comment by memsharded** [comment]
Hi @aledeganopix4d 

I think the "ping" endpoint has been there for a long time, before the 1.7, yes, that is the perfect endpoint you can use it to monitor the status of the server.

If I understood correctly, you are pinging the embedded conan_server? I would strongly recommend to use Artifactory CE instead, it scales much better. Cheers!
