### ISSUE TITLE
conan config install should accept ca cert for verification

### ISSUE THREAD

**Issue by chrahunt** [conan-io/conan#3668]
Conan version: 1.7.4

Our organization uses an internal CA to issue certificates for services. When running `conan config install` the very first time using an https URL, the user must either pass `--verify-ssl=False` or manually append our root CA certificate to `$CONAN_USER_HOME/cacert.pem`. It would be nice to be able to pass the ca certificate to use as an optional parameter to `conan config install` (e.g. `--cacert=/path/to/cert/bundle.pem` and `Conan.config_install`.

----

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @chrahunt 

The ``--args`` argument has been added in conan 1.7 to ``conan config install``. There you could pass any arbitrary arguments for the ``git clone``, have you tried it?

**Comment by Aalmann** [comment]
@chrahunt Have a look at #4353 
This could also be your solution if conan would use the system ssl store (where your internal CAs should be available). `conan config install https://your.url/your.zip` uses `requests` which can be extended/configured to use system ssl store and thus your CAs. So if implemented you don't have to add `--verify-ssl=False`.

**Comment by chrahunt** [comment]
@Aalmann - that is one approach, but only covers a subset of use cases. We do not have root/sudo on all hosts where users may be executing Conan, and while in principle they should have the internal CA certificate properly configured in the system certificate store referenced by Python - the various platforms and Python versions involved make an explicitly-provided argument more appealing.

**Comment by lasote** [comment]
@chrahunt what about using an environment variable to specify the location? Maybe that way it could be useful for other situations than `conan config install` only. Something like:

`$> CONAN_CACERT_PATH=$CONAN_USER_HOME/cacert.pem conan config install...`

or to persist it

```
$> export CONAN_CACERT_PATH=$CONAN_USER_HOME/cacert.pem 
$> conan config install...
```

**Comment by chrahunt** [comment]
Environment variable works for me. I would suggest evaluating it lazily or every time it is needed so that client API consumers have a chance to set it before invoking some method without having to worry about setting it before import of any `conans` module.

**Comment by lasote** [comment]
Team, probably we should consider an "improvement pack" for config install command together with #4603. To discuss.

**Comment by jgsogo** [comment]
Hi @chrahunt , we are implementing a config variable (with the corresponding environmente variable) in #4835 to allow the user to set a different *cacert.pem* file to use in requests.

Changing the value of these environmente variables for the same ``conan_api`` object is not officially supported (the ``conan_api`` itself is not official neither documented as experimental), but you can use the methods ``config_set`` to change its value.

It will be available in the next realease we are already preparing.
