### ISSUE TITLE
In-house packages without spinning up a server

### ISSUE THREAD

**Issue by ivanmoskalev** [conan-io/conan#3669]
Hi! I'm currently searching for a package manager for a complex C/C++ project. It has several applications and around a dozen of small libraries with dependencies in-between. Some of these small libraries pull in third-party code, like ICU. Conan seems to be one of the more mature package managers out there, but I'm a bit unexcited that I must provision and maintain an additional server for my packages. 

It would have been easier to adopt, I guess, if there was a way of using just a repository for hosting package definitions – just like CocoaPods for macOS / iOS does. I actually need just source-code packages.

Is there any such way of using Conan? Or a private instance of package server is unavoidable?

**Comment by memsharded** [comment]
It is easy to create the packages from recipes. I'd recommend the following:
- Put your package recipes in a repo, each one either with a name, or in its own folder
- Create a script (python, bash) that iterates over the folders and run a ``conan export . user/channel`` for each folder.

You are done, the package recipes are in the local cache, ready to be used. You'd need to use the ``--build=missing`` argument for ``conan install`` as you won't have the binaries. 

Of course, I would still recommend using a server, they are easy to run and maintain, and the benefits are very big. Any specific reason you don't want to manage binaries and always build from sources? Specially for large projects, managing the binaries is a big advantage. The Artifactory CE is free for Conan, but also for generic repos, so it is a convenient way to securely and privately host in-house other possible artifacts you could have.

**Comment by ivanmoskalev** [comment]
Thank you James! I have researched several package management options and decided to go with Conan + Artifactory CE. The costs of Artifactory hosting are quite negligible, and, as you mentioned, binaries might help with compile times – and should I outsource any work, access control is also there. 
Thank you for your valuable insights and an awesome tool!

**Comment by memsharded** [comment]
You are welcome @ivanmoskalev! 

Then, I think this issue can be closed now. Feel free to open more for new questions, also to join the #conan channel in the CppLang slack, the community there is amazing and we, the maintainers also try to hang around there when possible. Cheers!
