### ISSUE TITLE
Enable "conan config install" to install from a (git/svn cloned) folder

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3670]
Conan 1.7.

Right now, conan can config-install from a repo, or from a zip file. It would be easy to allow doing the process from any folder. That could help with config in other sources or in unreachable repos by conan (user/passwd auth) (https://github.com/conan-io/conan/issues/3668).

**Comment by liberforce** [comment]
You read my mind, I was going to open that one :). I have a single git repo where I store all the recipes, and a the configs for CI are stored there. Felt bad zipping that instead of using directly the plaintext files from the repo.

**Comment by liberforce** [comment]
If this is merged, could you please reschedule it to 1.8 if possible? Thanks.
