### ISSUE TITLE
New attribute: labels

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3671]
Hi!

Bincrafters have adopted the custom attribute `homepage`, which describes the author's URL. But thinking about the future, this attribute could be extracted from the recipe to fill Bintray page.

Now thinking about a possible new attribute and the possibility of having it in the future (Conan 2.0). Bintray uses `labels` to describe multiple topics related to the project. Github there is the same feature but it uses the name `topics`.

It could be:

```python
class HelloConan(conanfile):
    name = "hello"
    version = "0.1.0"
    labels = ["example", "hello-world", "first-program"]
    ...
```

I would like to discuss this idea to integrate our efforts on integrating Bintray, including possible new attributes for Conan.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Better call it tags, as in Bintray.

**Comment by uilianries** [comment]
Should I include **homepage** also?

We discussed a longtime ago about homepage and it could be re-used to fill Bintray.

Many of Bincrafters recipes are using homepage.

**Comment by danimtb** [comment]
@uilianries could **homepage** be confusing having url already there? I dont care too much, lets vote

**Comment by uilianries** [comment]
Could be confusing when you are creating a recipe on same project tree. But it's [documented](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#homepage).

Also when you are creating a recipe for a remote project is totally relevant, because you could find where is the original project and that info could be used to fill both Bintray and Github pages.

**Comment by Croydon** [comment]
https://github.com/conan-io/conan-extensions/issues/5

**Comment by Aalmann** [comment]
This feature could also be used for conan-io/conan#3498 isn't it?

**Comment by Aalmann** [comment]
Does it also work for Artifactory?

**Comment by Aalmann** [comment]
Ok. Thought the information will be published to Bintray as artifact property.

**Comment by uilianries** [comment]
The idea is getting Conan plugins to fill Artifactory and Bintray metadata.

**Comment by uilianries** [comment]
**topics** sounds great too
