### ISSUE TITLE
nested tools.vcvars() ignores arch change

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3673]
The code below doesn't work as one would expect:
```python
        with tools.vcvars(self.settings, arch="x86_64"):
            self.run("cl")
            with tools.vcvars(self.settings, arch="x86"):
                self.run("cl")
```
result:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```
(note `x64` printed by second `cl`). The reason I'm asking for this is following. Consider a test recipe:
```python
from conans import ConanFile, tools


class TestConan(ConanFile):
    name = "test"
    version = "0.0.1"
    settings = "os_build", "compiler", "arch_build"

    def build(self):
        if self.settings.compiler == "Visual Studio":
            with tools.vcvars(self.settings, arch="x86"):
                self.run("cl")
```
Then I build it with `conan create`, 32-bit compiler is called.  It's OK. But then I try to use conan package tools:
```python
from conans import tools
from conan.packager import ConanMultiPackager


if __name__ == "__main__":
    builder = ConanMultiPackager()
    builder.add()
    builder.run()
```
I get output:
```
test/0.0.1@user/channel: Calling build()
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```
64-bit environment is set. That's because `ConanMultiPackager()` calls `tools.vcvars()` itself and the second call of `tools.vcvars()` from the recipe is just ignored.

**Comment by lasote** [comment]
But, why are you forcing the arch to `x86` in the `vcvars` instead of building a configuration with the `arch` setting `x86`?

**Comment by lasote** [comment]
So there are two issues the underlying cross-build model issue (#3329, #2301) and the multiple `vcvars` calls. I will take a look at the `vcvars` in case we can fix something but at first sight, probably is the ms command `vcvars` who is prioritizing the first set arch. 

For the underlying issue, I would recommend to build first the package for the installer and then the regular packages. A new cross build is needed but it will take time.

**Comment by memsharded** [comment]
These ``tools.vcvars`` has been removed in 2.0, closing this as outdate, please report a new ticket if necessary for the new tools, thanks.
