### ISSUE TITLE
search_recipes procedure is not efficient on filesystem access

### ISSUE THREAD

**Issue by ntff** [conan-io/conan#3674]
In my simple client/server conan configuration I mount remote filesystem (s3) as ~/.conan_server/data storage.

Server fails to complete pattern search, only exact package can be matched.

As far as I understand, "search_recipes" procedure (conans/search/search.py, f966d51 revision, and I have 1.8.0-dev version on my server) enlists all folders 4-level deep starting from data folder, which takes too much time in my case:

`subdirs = list_folder_subdirs(basedir=paths.store, level=4)`

**Comment by ntff** [comment]
I would like to work on this, but need some guidance.

My Idea is to improve, first of all, processing of patterns, that start with prefixes like 'hello/\*' (probably, even patterns like 'hello\*' can be processed more efficiently) through translating prefixes into particular underlying storage dir listing, or even underlying fs search by pattern at each subdir level. The worst case of '\*hello\*', will be processed with the same (in general) implementatoin like now.

I need help with the following questions:
1. can you estimate my idea - will it work? (do you know any obstacles for an implementatoin, or something that will kill an effect of it?)
2. as far as I understand, conan_server accepts pattern, which is similar to unix shell-style wildcards (fnmatch module is used internally), except of '@' sign, used as level-divider between version and user part of package reference. fnmatch documentation declares a very simple 4-rule expression, does conan_server somehow limit or extend that syntax? (I could miss something in the code, so I just need a confirmation)

**Comment by memsharded** [comment]
I have a question, why not using Artifactory CE? It will scale much better, for large loads, and handle much better concurrency than the simple conan_server. Not to say better permission control and auth, generic repos, etc.

Using S3 as backend is indeed possible, we did something similar in the past for the old conan.io. But not mounting S3 as filesystem, but building the proper abstractions in conan_server code, and using elastic-search for searching. Seems to much work. If you have very strict requirements of using S3 as backend, I would consider using some Artifactory PRO, which already implements it.

**Comment by ntff** [comment]
I tried Artifactory CE, it's local storage layout is completely different than of conan_server. It's not "human readable" and will be hard to convert back to "human readable" (i.e. backup). Artifactory PRO may have a "human readable" storage layout for S3-backed repositories, but I have only a hobby-project, so not yet ready for PRO. So, I am looking the easy way to keep using conan_server, because now it doesn't work for me at all.

Elastic-backed search may ineed be the best solution for performance and scalability, but I am thinking about only solving some top blocker problem - if it will reduce filesystem enlisting at least to versions-level and below, i.e. skip enlisting all packages, it may be Ok to make it work for me.

**Comment by memsharded** [comment]
> I have only a hobby-project

Thanks for the feedback. Then, depending on what exactly you want to do, I'd say the approach might be overkill. Is your goal is to have your C and C++ dependencies managed by conan in the easiest possible way, or your hobby-project is actually playing with the server, building the S3 backend, etc?

If your goal is to have your deps managed by conan, for your hobby-project, but you want to have your conan_server backup by S3, I think I would try to have the normal conan_server, with local storage, and then a cron job with a rsync or upload of a tarball of the conan_server disk storage to S3. This might require an order of magnitude less job to setup and maintain.

If your hobby-project goal is to develop such a backend for conan_server, then, yes, go for elastic-search (though a simple DB like sqlite could also be good for your use case). Definitely doable, shouldn't be very difficult to hook that in the conan_server code.

**Comment by memsharded** [comment]
Closing this thread as inactive
