### ISSUE TITLE
exports_sources not deleted in Bintray after deleted from recipe

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#3679]
Having a recipe like:

```	 
 class TestConan(ConanFile):
     name = "test"
     version = "1.0"
     exports_sources = "include/*"
```

Gets a *conan_sources.tgz* uploaded to server (Bintray).

However, after removing the `exports_sources` and uploading again the recipe, the *conan_sources.tgz* is still there. Fortunately the *conanmanifest.txt* seems to be OK.

**Comment by memsharded** [comment]
I think this might be the same in all servers, not only bintray.

**Comment by danimtb** [comment]
More info:

This was happening when deleting `exports_sources` and using the `scm` feature.

Tested workflows:

Behavior **OK**;
  1- Upload Conanfile with `exports_sources` -> Uploads _conan_sources.tgz_ & _conanmanifest.txt_ is OK
  2- Upload Conanfile without `exports_sources` -> Deletes _conan_sources.tgz_ & _conanmanifest.txt_ is OK

Behavior **NOT OK**;
  1- Upload Conanfile with `exports_sources` -> Uploads _conan_sources.tgz_ & _conanmanifest.txt_ is OK
  2- Upload Conanfile without `exports_sources` and with `scm` -> Does NOT delete _conan_sources.tgz_ & _conanmanifest.txt_ is OK

**Comment by danimtb** [comment]
Conan Test behave well but Bintray seems to delay the deletion of the _conan_sources.txt_ a little bit.

However, there were some cases where the file was not deleted at all: https://dl.bintray.com/hanickadot/ctre/ctre/CTRE/2.0/stable/export/

**Comment by danimtb** [comment]
Seems to be working fine in Artifactory

**Comment by danimtb** [comment]
Moving this back to backlog

**Comment by memsharded** [comment]
Bintray is being sunset https://blog.conan.io/2021/02/05/JFrog-announces-sunset-bintray.html

https://conan.io/center/ ConanCenter is the public community central repository.
