### ISSUE TITLE
Support conan info --json for all outputs, and support stdout

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3694]
I'm not sure why --json is only supported when --build-order is also passed, but we would like all outputs from `conan info` to support output as `json`. 

Our primary reason is that we'll often be calling `conan info` in order to pass the information to another step in our automation.  If it's JSON, we can then parse the information more easily, and get nice access to the fields in the result like:  info_result.package_folder.  As it stands, we have to have custom parsing for the output format. 

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by sourcedelica** [comment]
Please also include the `export_source` path.
