### ISSUE TITLE
[feature] add way to customize install folder for cmake helper

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#3695]
Hi there,
I use the CMake helper to configure, build, install and package a project.

what is
--------
Now I've to build more than one projects at once.
- Project A depends on project B.
- Project B links to the built project A (installed libs).

Conan `def build(self):` function:
- CMake build, install project A.
- CMake build, install project B (which uses project A libs/binaries).

the problem
--------
I use `self.package_folder` as root-install-path.
Each project build appends a subdirectory to the `self.package_folder`.
Project A: CMAKE_INSTALL_PREFIX = self.package_folder + "/sub-dir"
Project B: CMAKE_INSTALL_PREFIX = self.package_folder + "/sub-dir"

CMake.install() always uses self.package_folder and I have to 
``` python
cmake.configure(...)
cmake.build(...)
try:
    current_install_path = self.package_folder
    self.package_folder += "/sub-dir"
    cmake.install(...)
finally:
    self.package_folder = current_install_path
```

This is inconvenient :).
cmake.configure(...) and cmake.build(...) both offer a functionality to define the build_folder.
A similar one would be convenient for the package/install path :).

Best regards

**Comment by danimtb** [comment]
hi @Johnnyxy, Sorry for the delay.

have you checked the CMake helper definitons table https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#definitions ?

The helper sets CMAKE_INSTALL_PREFIX to self.package_folder, but it could be modified on demand. Por example:

```
def build(self):
    cmake = CMake(self)
    cmake.definitions["CMAKE_INSTALL_PREFIX"] = "%s/sub-dir" % self.package_folder
    cmake.configure()
    cmake.build()
    cmake.install()
```

I think this could work for your use case.

**Comment by Johnnyxy** [comment]
Ah, yes you are right.
I will give it a shot ;).

**Comment by Johnnyxy** [comment]
Works :)

... thx ...
