### ISSUE TITLE
Bintray only displays "Link" button in repositories without write access

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#3698]
I would like to link in all dependencies the Inexor project needs into our own [Bintray repository](https://bintray.com/inexorgame/inexor-conan).

This worked well so far and I linked many packages from the Bincrafters and conan-community repositories into inexor-conan. I recently got write access to the Bincrafters repository and noticed that the link button is now gone for all Bincrafters packages. So I can't find any way to link Bincrafters packages into inexor-conan anymore.

I'm considering this as a bug as I'm thinking that this use case is valid.

**Comment by memsharded** [comment]
Bintray is being sunset https://blog.conan.io/2021/02/05/JFrog-announces-sunset-bintray.html

https://conan.io/center/ ConanCenter is the public community central repository.
