### ISSUE TITLE
[question] RuntimeWarning while using python_requires

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#3704]
In Conan 1.8,

I am getting RuntimeWarning while using python_requires:
```
conan export . demo/test
/home/sun/.conan/data/MyBase/1.7/demo/test/export/conanfile.py:1: RuntimeWarning: Parent module 'MyBase/1' not found while handling absolute import
  from conans import ConanFile, CMake, tools
/home/sun/.conan/data/MyBase/1.7/demo/test/export/conanfile.py:2: RuntimeWarning: Parent module 'MyBase/1' not found while handling absolute import
  import os,sys

..
..
```

My base conan file is:
```
from conans import ConanFile, CMake, tools
import os,sys,

_scm = {
    "type"      : "git",
    "url"       : "auto",
    "revision"  : "auto"
}

class MyBase(ConanFile):

..
..
```

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @sunj1 

Could you please share the consumer conanfile.py too? So we can reproduce. Thanks!

**Comment by sunj1** [comment]
Consumer conanfile:
```
from conans import python_requires

base = python_requires("MyBase/1.7@demo/test")

..
..
```

**Comment by memsharded** [comment]
Verified. This warning is only output in Python27, not in Python3

**Comment by memsharded** [comment]
Yes, thanks for the feedback!, trying to submit a patch for 1.8.1 here: https://github.com/conan-io/conan/pull/3706

**Comment by lasote** [comment]
1.8.1 released!
