### ISSUE TITLE
[bug] 1.8.0 introduces a misleading warning in tools.collect_libs()

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#3708]
After updating to 1.8.0 today (thank you for such frequent releases 👍 ), I noticed several warnings when `conan install`ing recipes that depends on our custom boost recipe.

```
boost/1.67@com/stable: WARN: Library 'boost_atomic' already found in a previous 'conanfile.cpp_info.libdirs' folder
boost/1.67@com/stable: WARN: Library 'boost_chrono' already found in a previous 'conanfile.cpp_info.libdirs' folder
...
```

Which corresponds to the following addition to the source:
https://github.com/conan-io/conan/blob/a20c0f5ca432192596af6b34eccf56c1f5e20904/conans/client/tools/files.py#L308-L310

We see the intention here, but in our situation this message is misleading: it would imply there are several `conanfile.cpp_info.libdirs`, although there is actually only one element in this collection.

The message is in fact triggered because in this single `conanfile.cpp_info.libdirs` directory, each library is present with two different extensions (static and dynamic libraries).

**Comment by Adnn** [comment]
Hi @memsharded, thank you for taking a look at this!

For the message, it depends what you want to do? If you distinguish between the two situations (the same file in different folders, and the same basename in several files of the same folder), an explicit message like you propose could work well!

If you don't want to add logic to make this distinction, something generic like 

> 'boost_atomic' was either found in a previous 'conanfile.cpp_info.libdirs' folder, or appears several times with different file extensions

could also work, what do you think?

**Comment by memsharded** [comment]
Yes, that is reasonable, lets do it for the next minor 1.8.2. Thanks for the feeback!

**Comment by lasote** [comment]
1.8.2 is released!
