### ISSUE TITLE
Issue on Windows when using exports='*' for large packages

### ISSUE THREAD

**Issue by reidhoch** [conan-io/conan#371]
We build an in house version of Boost 1.57.0 with some pretty minor changes, `python build.py` is working as expected on Mac and Ubuntu 14.04. When attempting to build on Windows 10 I run into an error complaining about `Unable to load Boost.Build: could not find build system.` A little bit of investigating points to not all the files being copied over when I use `exports='*'` in my `conanfile.py`, I notice in my `c4aef4edbc33205e0cf9b55bfb116b38c90ec132` directory used for building that only the boost, doc, and libs folders are copied. The more, status,test, and tools directories are missing. This would explain being unable to find the build system. I'm not seeing this behavior on other platforms.

Here is a log of my output from running `python build.py` on Windows 10: 
[build.py.txt](https://github.com/conan-io/conan/files/366216/build.py.txt)

**Comment by reidhoch** [comment]
I'm attaching my `conanfile.py` as you can see it's pretty similar to what @lasote is using in his standard Boost builds, with minor changes to build from local source instead of pulling down a copy from the web.


[conanfile.py.txt](https://github.com/conan-io/conan/files/366238/conanfile.py.txt)
[conanfile.py.txt](https://github.com/conan-io/conan/files/366239/conanfile.py.txt)

**Comment by memsharded** [comment]
Hi! It seems that it something related to the relative paths, that are different when doing exports.
While we have a look, I would recommend to try to avoid "export-ing" large packages sources inside the package recipe. If you don't want to depend on a source tarball from sourceforge or whatever, host a copy of the tarball on your server, and make the conanfile.py download point to your server.

This approach has an advantage: retrieving package recipes is much faster, as it only retrieves the conanfile.py. If you export=* the boost source code, you will retrieve the sources too. If you depend on precompiled package binaries, you don't need the sources at all, they are just needed in the ``build()`` method. 

Just for your consideration. In any case, I am having a look, to check what could be failing. Thanks for reporting!

**Comment by memsharded** [comment]
What is your layout? Do you have a "boost_1_57" (as unzipped from the tarball from the web) folder besides your ``conanfile.py``?

**Comment by memsharded** [comment]
The files that are not being copied are docs files, not really necessary for build. Please note that the original ``conanfile.py`` does a chdir before running the build:

```python
self.run("cd %s && %s" % (self.FOLDER_NAME, command))
```

The truth is that when I am running ``conan export`` it already fails (with an ugly stacktrace, this is a bug), due to the well known problem of path length limits in win. How did you manage to run ``conan export`` without this problem? Maybe you exported & uploaded it from other OS like linux, and you are consuming it from Windows, but not exporting from windows.

We have recently deployed a workaround for the windows path-length problem, that might help, check "short_paths" here: http://docs.conan.io/en/latest/reference/config_files.html#short-paths-conf

**Comment by reidhoch** [comment]
Hi guys, sorry I was on vacation last week. I was able to fix my issue by using `short_paths.conf`. I appreciate your time looking at this issue.

**Comment by memsharded** [comment]
Thanks for telling, but please take into account that the shorts_paths workaround still have some problems and issues, as failing when uploading. We are working on them, but they are not easy. Thanks for your patience.

**Comment by memsharded** [comment]
Conan 0.11 has been released with a new solution to the windows path length limit: http://docs.conan.io/en/latest/reference/conanfile.html#windows-path-length-limit

Just add short_paths=True to the conanfile.py.

The short_paths.conf is no longer used, so this issue should be gone. Please upgrade to conan 0.11 and re-open if necessary. Thank you!
