### ISSUE TITLE
[bug] 1.8.0 uses --sbin instead --sbindir

### ISSUE THREAD

**Issue by joshgamer474** [conan-io/conan#3711]
After updating to conan 1.8.0, I ran into an issue building a [librdkafka/0.11.4-1](https://github.com/ess-dmsc/conan-librdkafka) package on CentOS due to the ./configure statement using `--sbin` as a parameter instead of `--sbindir`:

```
librdkafka/0.11.4-1@<asdf>/stable: Calling:
 ./configure '--prefix=' '--disable-sasl' '--diable-lz4' '--disable-optimization' '--bindir=${prefix}/bin' '--sbin=${prefix}/bin' '--libexec=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include'
Unknown option sbin=${prefix}/bin
```

The GNU Coding Standard states that the variable for the [`sbin` installation directory is `sbindir`](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html).

It looks like the issue came from #3599 and the [librdkafka/0.11.4-1](https://github.com/ess-dmsc/conan-librdkafka) package builds fine on conan 1.6.1.

**Comment by LighthouseJ** [comment]
Also, the recent conan changes uses libexec, but it should be libexecdir per the GNU standard.

**Comment by danimtb** [comment]
Yes, you are right. Will try to fix it in a new patch release. Thanks for reporting

**Comment by lasote** [comment]
1.8.2 is released!
