### ISSUE TITLE
Surprising behaviour differences with conan_server hostname

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#3712]
Working with Conan 1.8.1 on 2 OSX environments (VM and its host)

We start `conan_server` on the VM, and interact with it from the host.

With the default configuration (`hostname: locahost`), we can list packages `conan search -r vm`, connect the user with `conan user -r vm`, but `conan upload -r vm ...`  fails with error:

> HTTPConnectionPool(host='localhost', port=9300): Max retries exceeded with url: /v1/files/...

What seemed suspicious to us was the presence of `localhost` in the error output.

Now, if we reconfigure `conan server` with the IP of the VM on the internal network (`hostname: xxx.xxx.xxx.xxx`), `conan upload -r vm ...` works as expected.

If every command failed with `hostname: localhost`, we would not have been so surprised. But the fact that some does, and some don't, could seem a bit misleading.

Is this expected behaviour?

**Comment by lasote** [comment]
Yes, because the upload is done in two steps, first getting the upload urls (built with the hostname) and later pushing the files to the urls. So it fails pushing artifacts to the wrongly generated urls.

**Comment by lasote** [comment]
This two steps behavior is going to be removed in the future APIV2 we are introducing. But still not active.
