### ISSUE TITLE
Make source() completely configuration independent

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3713]
Right now, it uses the installed profile, or the default profile, just in case it requires to do some download different by the current OS.

I think this should probably be completely removed, it could be fragile and error prone in case of cross-building, etc. ``source()`` should be completely configuration independent.

**Comment by puetzk** [comment]
Does that mean that if I'm doing any patching for specific toolchains, I should be doing so in build() instead of source()?

I don't currently have an example, but I've had to do so in the past for libraries that didn't play nice with MSVC; it's not always worth it to make the fix fully portable.

**Comment by Croydon** [comment]
I don't understand how this should work for exactly this case:

> just in case it requires to do some download different by the current OS.

**Comment by memsharded** [comment]
> Does that mean that if I'm doing any patching for specific toolchains, I should be doing so in build() instead of source()?

Yes, definitely. The source folder is created just once, and the ``source()`` will be called just once, for all possible builds and configurations. Everything in the source should be common to all builds. Specific configuration code should be moved to  ``build()``. It is possible to apply a patch for MSVC in ``source()``, as long as that patch doesn't change the code for other compilers or configurations.

> I don't understand how this should work for exactly this case:

There might be some cases when you want to download a tarball that has CRLF, instead of LF, for Windows, and some libraries out there provide zips for Windows, with the sources normalized to CRLF and tgz for unix systems with LF. This ``source()`` method might be also used for the local development flow, in which the developer will be using the code directly.

It is likely that for any other use case, it should go to the ``build()`` method.

**Comment by danimtb** [comment]
For example, that is the case of ImageMagick: https://github.com/bincrafters/conan-imagemagick/blob/stable/7.0.8-10/conanfile.py#L99

**Comment by Croydon** [comment]
Yes, what I meant is, if source() should be independent then you can't make such switch-cases anymore like if Windows than download x if Linux download y?

**Comment by memsharded** [comment]
Yes, the https://github.com/bincrafters/conan-imagemagick/blob/stable/7.0.8-10/conanfile.py#L99 reads very confusing to me, seems that it should be fixed.

**Comment by memsharded** [comment]
Conan 2.0 removes the access to settings and options in ``source()`` to protect against this.
