### ISSUE TITLE
Failed to install connan 1.8.2 on ubuntu16.04

### ISSUE THREAD

**Issue by figroc** [conan-io/conan#3728]
I'm installing as
```
pip --no-cache-dir install conan conan_package_tools
```
As the time of installing, the latest version was 1.8.2. And,
the output logs:
```
Installing collected packages: PyJWT, colorama, patch, monotonic, fasteners, node-semver, distro, isort, wrapt, lazy-object-proxy, typed-ast, astroid, mccabe, pylint, deprecation, t
qdm, bottle, pluginbase, conan, idna, tabulate, conan-package-tools
  Running setup.py install for patch: started
    Running setup.py install for patch: finished with status 'done'
  Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
  Found existing installation: tqdm 4.26.0
    Uninstalling tqdm-4.26.0:
      Successfully uninstalled tqdm-4.26.0
  Rolling back uninstall of tqdm
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/usr/local/man/man1'
```

I switched the installing to version 1.7.4, and everything was good.

**Comment by danimtb** [comment]
Found a similar issue here https://github.com/tqdm/tqdm/issues/460

Maybe you dont have that *man* directory or the right user permissions

**Comment by danimtb** [comment]
I think this is actually coming from the tqdm dependency that was introduced in 1.8.0

cc/ @jgsogo

**Comment by figroc** [comment]
Actually I was building an image for C++ environment including conan tools. I really don't want to install _man_ 😕

**Comment by danimtb** [comment]
Hi @figroc,

Seems tqdm was downgraded due to an issue with python 2, you can see the conversation starting at this comment: https://github.com/conan-io/conan/pull/3545#issuecomment-421068377

We will try to get it fixed for next release. Keep us posted if you workaround this in the meantime. Thank!

**Comment by jgsogo** [comment]
You can try to ``pip install`` in the user home directory by typping ``pip install --user conan conan_package_tools`` (or using a virtualenv). Let us know if the ``--user`` works for you.

About the ``tqdm`` update, I'm tracking the issue, I'll ping them and try to push it forward.

**Comment by Croydon** [comment]
This is affecting pretty much every project using Conan directly or indirectly, so this should probably getting a high priority. 🙈

**Comment by jgsogo** [comment]
Hi!

I don't think this can be tagged as a bug or even an issue, it has to do with system permissions and the way pip/python works. It's so common to come across a _permissions denied_ error when installing packages system-wide with ``pip`` and the solution is to use ``sudo``, install it per-user (with ``--user``) or use a virtualenv.

We'll open the revision required for ``tqdm`` as soon as we identify a range without known issues, but chances to find this _error_ again are 100% (@figroc would have been ok with his 4.26.0 version, but anyone without a ``tqdm`` installed could have got the error) . Right now there are several dependencies of Conan that requires elevated permissions to be installed system-wide, but usually, they are already installed so it doesn't complain.

We may change the [docs](https://docs.conan.io/en/latest/installation.html#install-with-pip-recommended) and recommend installing Conan using the ``--user`` argument (although it would be even better to use a virtualenv). The ``--user`` is a long-standing discussion in the ``pip`` community and I hope it will be the default behavior anytime soon (more info: https://github.com/pypa/pip/issues/1668).

**Comment by danimtb** [comment]
I am willing improve the installation steps and clear the section of the docs by moving some things to FAQ for example

**Comment by jgsogo** [comment]
Also, there is a proposal for a temporary fix here https://github.com/conan-io/conan/issues/3785#issuecomment-431033910

**Comment by lasote** [comment]
We will release 1.8.4 soon to fix this.
