### ISSUE TITLE
runtime dependencies for cross-platform

### ISSUE THREAD

**Issue by GarrickLin** [conan-io/conan#3735]
- Conan version 1.7.3
- OS version Ubuntu 16.04
- Cross compile for arm64

Is there an easy way to handle cross-platform runtime dependencies when my excutable app in arm64 requires a few conan packages. In other words, we might not think it's elegant to copy many `so`  libs by hand.

**Comment by uilianries** [comment]
If you need to keep all libs together, you could [import](https://docs.conan.io/en/latest/using_packages/conanfile_txt.html?#imports) all files.

When I worked with embedded devices, I used Conan to deploy an opkg file and install all files.

@danimtb has a good experience with cross-platform too.

**Comment by danimtb** [comment]
Yes @GarrickLin, check the imports() method: https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

In case you want to deploy a final app with the shared files from dependencies you can also use deploy(): 
https://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy

Let us know if this suits your needs

**Comment by GarrickLin** [comment]
The `deploy()` method perfectly solved my problem, thx !
