### ISSUE TITLE
[scm] --show-item not supported on older versions of subversion

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3737]
Thank you to @jgsogo for implementing SVN for the scm attribute.

I've finally got the chance to try this new feature and discovered that my version of subversion (1.7.14 as supplied in RHEL 7) does not support --show-item for the svn info command. Unfortunately, this means I can't use this feature :sob:

Can this be changed to something like:

`svn info <other args> --xml`

And the XML parsed? Bit like is suggested in #3653

**Comment by jgsogo** [comment]
Ohhh... anyway, I will work on the XML parsing as it will be available for every SVN version 🤞. I'm tagging it for v1.9.

**Comment by keithrob91** [comment]
Not sure if I should post this here, or open another issue, but, I've also just discovered the -r option is not supported for svn status on the RHEL 7 version of subversion :unamused:

**Comment by jgsogo** [comment]
jajajaja, let's me see if I can install a SVN from the pre-internet era and test it all with it 😄

**Comment by keithrob91** [comment]
Thank you. Unfortunately, for various reasons, I am restricted to using whatever RHEL provide, and even on the latest and greatest RHEL (7) they choose to provide an old subversion :unamused:

**Comment by jgsogo** [comment]
I managed to run the test suite in a [container with subversion 1.7 installed](https://github.com/StatelessCat/docker-ubuntu-svn1.7), and I've done several changes in a [branch](https://github.com/jgsogo/conan/compare/issue/3737...jgsogo:issue/svn1.7?expand=1); I think it should work, but now I want to test it with 1.8 and 1.9, just in case. I will merge them through #3757.

The main issue here is that we cannot add a job to our CI to keep testing an old version of SVN (we cannot manage to have a job for _every_ version of _every_ external tool we use in Conan) ...so I'm afraid we can break something in the future 😞

**Comment by keithrob91** [comment]
OK great. We'll deal with things breaking when it happens!
