### ISSUE TITLE
Add an option for creating immutbale packages with Conan.

### ISSUE THREAD

**Issue by bobeff** [conan-io/conan#3738]
When someone builds a library and creates a package for it with Conan the hash of the package depends only on its settings and options. This way when someone rebuilds the package with the same settings and options, the old one will be overridden. This behavior prevents the package to be used as reliable storage for the library debug information, because even on build with the same compiler and linker options the final binary is compatible with the build information produced only with its own build. Possible solution can be the package hash to be calculated not only on its settings and options, but on its entire content. Some other package managers like [Nix](https://nixos.org/nix/) provide an option for immutable packages.

**Comment by lasote** [comment]
There is a big ongoing effort for proving package revisions both for the recipes and the packages, so the artifacts are always kept and never overwritten and to guarantee reproducibility.
This is currently one of the most important features going on, you can see some progress here: #3055 but we are still designing lock files etc and verifying that the whole picture works in a CI flow.

**Comment by bobeff** [comment]
I didn't know about this work in progress. I think that this is a crucial feature, for full production readiness of the Conan, because keeping the debug information of the packages is very important for investigating live issues with the software. I'm looking forward for this feature in some of the upcoming releases.

Thank You!

**Comment by monsdar** [comment]
I think this could be closed, as RREV and PREV has been implemented: https://docs.conan.io/en/latest/mastering/revisions.html
