### ISSUE TITLE
Path name to long file excluded (Windows)

### ISSUE THREAD

**Issue by lightman17** [conan-io/conan#374]
I install Qt/5.6.0@osechet/testing on windows with forced build.
By copying the source tp build directory, i get the following errors.
Qt/5.6.0@osechet/testing: WARN: Filename too long, file excluded: C:\Users\mju\.conan\data\Qt\5.6.0\osechet\testing\build\63da998e3642b50bee33f4449826b2d623661505\qt-everywhere-opensource-src-5.6.0\qtdeclarative\tests\manual\scenegraph_lancelot\data\borderimages\borderimage_rotated_unsmoothed_negative_borders.qml
There are more files, that are excluded.

**Comment by Blubbz0r** [comment]
Starting with version 0.10 you can use the short_paths config described [here](http://docs.conan.io/en/latest/reference/config_files.html?highlight=short_paths#short-paths-conf) to redirect the Qt build into a shorter path and thus avoid the "Filename too long" error.

Also see issue #311 for more information.

**Comment by memsharded** [comment]
Conan 0.11 has been released with a new solution to the windows path length limit: http://docs.conan.io/en/latest/reference/conanfile.html#windows-path-length-limit

Just add short_paths=True to the conanfile.py.

The short_paths.conf is no longer used, so this issue should be gone. Please upgrade to conan 0.11 and re-open if necessary. Thank you!
