### ISSUE TITLE
Question: apple-clang compiler.version=10.0 support

### ISSUE THREAD

**Issue by nigels-com** [conan-io/conan#3743]
cmake detects my Mac clang as version 10

```
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
```
But, setting version 10 is not supported:

```
$ conan install .. --build=missing -s compiler.version=10.0
...
ERROR: Invalid setting '10.0' is not a valid 'settings.compiler.version' value.
Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0']
```
Is simply extending the list in `~/.conan/settings.yml` sufficient?

```
...
    apple-clang:
        version: ["5.0", "5.1", "6.0", "6.1", "7.0", "7.3", "8.0", "8.1", "9.0", "10.0"]
...
```

**Comment by Croydon** [comment]
> Is simply extending the list in ~/.conan/settings.yml sufficient?

Yes, the default settings.yml already has it as well

https://github.com/conan-io/conan/blob/1.8.2/conans/client/conf/__init__.py#L73

**Comment by nigels-com** [comment]
Thanks, much appreciated.
