### ISSUE TITLE
conan install does not find package created with short_paths.conf in remote

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#375]
When creating a package like Qt with the short_paths.conf active and uploading the package to a remote, it is uploaded with the short Package_ID (Sha). This seems to confuse ```conan install```. It cannot find the package in the remote, since it is comparing against the long Package_ID.

Here is what ```conan search -r {REMOTE} Qt/* -x``` shows:

![search](https://cloud.githubusercontent.com/assets/11735226/16950684/cecfdc10-4dc1-11e6-94d9-5177e09b8681.PNG)

Performing a ```conan install --build=missing -s arch=x86_64 -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime=MDd -s compiler.version=14 -s os=Windows``` on the client then result in:

![install](https://cloud.githubusercontent.com/assets/11735226/16950775/2a00298c-4dc2-11e6-9376-0a20f8360eb5.PNG)

**Comment by lasote** [comment]
It seems like a bug and not easy :( Thanks for notice.

**Comment by memsharded** [comment]
Yes, this is important. Maybe add a note in the docs, to warn other users?

**Comment by memsharded** [comment]
Conan 0.11 has been released with a new solution to the windows path length limit: http://docs.conan.io/en/latest/reference/conanfile.html#windows-path-length-limit

Just add short_paths=True to the conanfile.py.

The short_paths.conf is no longer used, so this issue should be gone. Please upgrade to conan 0.11 and re-open if necessary. Thank you!
