### ISSUE TITLE
Defining minimum requires for the conan test suite

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3752]
Right now, if we want to run the full test suite succesfully, you migth need a plethora of tools: git, SVN, cmake, mingw, a couple of VS versions... This is too tricky for most contributors. We should make the default test suite invocation to run with some minimal setup, and support the others conditionally. Or clearly define a test suite invocations ``nosetests -A "not SVN and not golang and not ..."``

- [ ] skip unless has attrib: opt-in of tools: svn, mingw, meson, golang,...
- [ ] move tests from test-suite in other repos back to this main one.

**Comment by lasote** [comment]
To discuss in an internal meeting what we want in the conan tests codebase and what in the external tests. I vote the SVN to be moved because are very slow.

**Comment by memsharded** [comment]
My proposal would be:

- Test suite should pass, by default with ``nosetests .`` (or similar, but simple command, might have some option), with the following tools installed:
  - CMake (to discuss which version, I'd suggest 3.3 as base)
  - Reference latest distro compiler (VS2017 in Win), gcc latest by distro for mainstream latest distro versions (Ubuntu 16, 18 LTS), apple-clang latest in OSX
  - git

- Tests that require extra tools:
  - MinGW in Windows
  - Meson build system
  - Golang
  - SVN

Possibilities:
- Explicit enabling only
- Explicit and automatic detection enabling (if ``gcc --version`` in system, might mean MinGW available)
- Once explicit is defined, they should fail if not installed.


To be discussed.

**Comment by jgsogo** [comment]
Explore the `skipUnlessHasattr` proposed decorator here: https://docs.python.org/2/library/unittest.html#skipping-tests-and-expected-failures
