### ISSUE TITLE
Add merge of cacert.pem in conan config install

### ISSUE THREAD

**Issue by cau** [conan-io/conan#3753]
In my organization we use conan config install to ensure that everyone has the same configuration and it's a really easy way of getting a develop environment up to speed in a correct state. However, since we use tls certificates signed internally by our organizations cacert it's still cumbersome to add the server pem file to the local cacert.pem in the home directory of conan.

I'd like to propose that if a cacert.pem file is present in the config to be installed is appended to the already existing cacert.pem file that comes with conan. 

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I think it is not exactly the same issue @uilianries , the #3668 is about the certificates for the connection to the repo to be config-installed, if I understood correctly

**Comment by cau** [comment]
@uilianries, as @memsharded points out it's two different use cases.

Yes, @memsharded, that's the way I'm doing it right now. Since I'm not familiar with where the provided cacert.pem originates form and if it changes over time I thought providing a merge of the two would be a nice feature. 

Where do you get the contents of cacert.pem from?

**Comment by lasote** [comment]
| Where do you get the contents of cacert.pem from?

I think last time I took it from:

https://curl.haxx.se/docs/caextract.html

**Comment by danimtb** [comment]
Hi @cau,

We have recently discussed this issue and our view is that letting Conan merge certificates could be something not desired and should be done manually.

There are also other reasons:
- We do not usually update the certificate as often as everybody would desire.
- Certificate is taken from the Mozilla site indicated above, so it is something accesible for everyone.
- Managing and distributing your own certs is usually the best and common solution that some organizations are following right know and we think is the most reasonable approach.

So finally I am closing this issue as no further action is expected from development but please comment or reopen if you think this is still an issue. Thanks a lot! 😄
