### ISSUE TITLE
Add remove from cache callbacks to hooks

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3760]
Names to discuss. Both for recipes and packages. Same for remote deletions? (<= I would wait for the use case)
For the "pre_remove_recipe": Load the conanfile and pass it also as an argument, so you can call any custom declared methods inside.

https://github.com/conan-io/conan/issues/2774#issuecomment-429765712

**Comment by Aalmann** [comment]
Use case for remote deletions:
Search remotely for packages which depends on the package to be deleted (inverse dependency tree) and if some package is found, block the remote deletion if not `--force` is given.
Probably via REST-API call (https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ArtifactoryQueryLanguage(AQL) or https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-PropertySearch or https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-BuildsforDependency)

**Comment by lasote** [comment]
We have been discussing this.
We want first to study if we store the system installed packages somewhere, probably in the package metadata json for then, pass the metadata to the hook instead of passing the conanfile.
The problem passing a conanfile to the hook is that you need to load it, and it will install the python requires. It could happen the crazy situation that you are removing a python require and then it is installed again deleting a package depending on it.

**Comment by lasote** [comment]
Depends on #4226

**Comment by memsharded** [comment]
This have been made unnecessary by Conan 2.0, which now provide reach mechanisms to implement user behaviors around removal:

- Conan custom commands
- Conan Python API
- Conan package-lists as result of ``conan remove`` operations

These will be wary more flexible and powerful than any hook approach (actually hooks in Conan 2.0 have been only kept for recipe pre-post methods, like pre_build/post_build, but everything else have been removed from hooks).

Closing the ticket as outdated.
