### ISSUE TITLE
Assign a reference for a project conanfile

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3761]
There are different issues related to not having a reference when working with a local conanfile:

- Local methods can't access `self.version` if the versions is not declared in the recipe 
- Crazy PROJECT references in the code base
- ...

Should the `conan install .` accept a reference/partial reference to be locked in the conaninfo? Then the local commands could use it.
Note that currently the `source` command can operate without a `conaninfo` (#3713) and to download the sources you probably need the `self.version` if you don't declare it.

**Comment by lasote** [comment]
#3734 related

**Comment by memsharded** [comment]
This was implemented and released in Conan 1.12, as it was backward compatible, no need to wait for 2.0.
