### ISSUE TITLE
Bintray filter by package name doesn't work anymore

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3765]
https://bintray.com/conan/conan-center?filterByPkgName=pistache

It finds all packages in conan-center. It gets the "pistache" one right, but finding the rest of the conan-center is at least confusing.

**Comment by fenbf** [comment]
I'm seeing the same issue.
If you enter a keyword, like "test" it will show you like 18 pages of results... same for other keywords.
I think it was working in the past...
and at the moment the search is very confusing

what's the status of that?

**Comment by memsharded** [comment]
This doesn't apply anymore, bintray UI no longer used, https://conan.io/center search works fine.
