### ISSUE TITLE
conan install returns wrong example on version 0.10.1

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#377]
Hi!

When I run the line:  
> $ conan install --help  

I give the follow output:  

>usage: conan install [-h] [--package PACKAGE] [--all] [--integrity]
>                     [--file FILE] [--update] [--scope SCOPE] [-r REMOTE]
>                     [--options OPTIONS] [--settings SETTINGS]
>                    [--build [BUILD [BUILD ...]]]
>                     [reference]
>
> install in the local store the given requirements.
>        Requirements can be defined in the command line or in a conanfile.
>        EX: conans install opencv/2.4.10@lasote/testing

Look that the example uses _conans_ instead of _conan_

**Comment by lasote** [comment]
Thanks, I've open a PR #378 with the fix.
