### ISSUE TITLE
Use shallow clone when building packages from source

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#3770]
When package uses `scm` attribute like this:

```python
scm = {
    "type": "git",
    "url": "auto",
    "revision": "auto"
}
```

and when package is being built from source (as a dependency of another package), git clones the entire repository and checks out the correct revision. For large repositories this can take a while. Would it be possible for conan to use [shallow clone](https://linuxhint.com/git-shallow-clone-and-clone-depth/) by default in that case?

This assumes that source folder is not changed for various package IDs being built (I guess conan has the same assumtion), as shallow clones does not allow you to checkout commits that have not been fetched from remote.

**Comment by lasote** [comment]
I don't understand what you mean with:

> This assumes that source folder is not changed for various package IDs being built (I guess conan has the same assumtion), as shallow clones does not allow you to checkout commits that have not been fetched from remote.

My question is if we need to check out a specific commit, can we clone it with a shallow clone somehow indicating we need that specific commit?

**Comment by jgsogo** [comment]
Git doesn't allow to retrieve just a hash, you have to fetch at least one branch and ``depth`` number of commits in history, so the needed hash may not be available in the cloned repo 😞  [TL;DR](https://stackoverflow.com/questions/26135216/why-isnt-there-a-git-clone-specific-commit-option).

So... we cannot protect against a recipe checking out a different commit :/

**Comment by jgsogo** [comment]
I'm labeling it as ``wontfix``, as I think we cannot do anything to relieve this pain. I will close it in a few days if nobody comes with an idea.

**Comment by DoDoENT** [comment]
I just tried following in my terminal and it worked:

```
mkdir source
cd source
git init
git fetch --no-tags --progress --depth 1 git@bitbucket.org:my-private-git-repo.git 705f227f00000ae91bce3f93e8d3c7744ec13e57
git checkout 705f227f00000ae91bce3f93e8d3c7744ec13e57
```

I tried the same with the some public repository on bitbucket, but then I got error `error: Server does not allow request for unadvertised object <hash>`. and exit status of the git was 1.

So, some servers allow this (at least private Bitbucket does so, not sure for Github/Gitlab) and some don't - as described in link by @jgsogo, server must be configured to allow serving requests for hash.

So let me propose the following:

- add the boolean configuration option to `conan.conf` which defines whether shallow clone will be attempted - the default value should be `False`, i.e. always perform the full clone.
- if shallow cloning is allowed, attempt cloning with the `git init; git fetch` trick described above.
- if `git fetch` returns error, then assume that retrieving of single hash is not allowed on server and fallback to normal clone procedure
- if `git fetch` succeeds, simply checkout the commit and save lots of time

How do you like that?

**Comment by jgsogo** [comment]
As it is possible (I didn't realize about the ``allowReachableSHA1InWant`` option), let's discuss if it is worth adding this behavior. It should be easy, just add more code to [``Git::checkout``](https://github.com/conan-io/conan/blob/34ac878ca9956b80304b3c3c96849ba73067c794/conans/client/tools/scm.py#L82) and pass to it the relevant flags.

**Comment by dribeas** [comment]
Git support in conan allows pinning any individual commit for the recipe, which may be more flexible than what's actually needed.  Personally, I believe that released packages should only come out of tags, during development you may want to pick tip of branch during development.

Git allows for shallow clones of both branches and tags, and this could be n  advantage for certain uses.  Some of the repositories we work with take many seconds to clone (300+ M for a clean repo). Maybe providing 'tag' or 'branch' options to the scm component could allow this, or not doing so and documenting that 'shallow' clone would only fail unless 'revision' is either a tag or a branch.

**Comment by DoDoENT** [comment]
@dribeas, great idea! Our CI system automatically tags the commit after successfully building the conan packages from it (furthermore, we use the name of the tag equivalent to the full name of the package that was built).
