### ISSUE TITLE
VS 2017 latest update 15.8.7 not identified in conan (possibly cmake issue also)

### ISSUE THREAD

**Issue by DaniCybereason** [conan-io/conan#3774]
To help us debug your issue please explain:
Tested using both conan 1.8.2 and 1.8.3 (Win 10 1803 - 17134.345)

it seems since the latest visual studio 2017 update - 15.8.7, conan is not identifying the 15 compiler version at all (falls back to 14 since I Have VS 2015), and cmake fails building a simple C++ test_package...

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I've installed the 15.8.7 and a clean conan cache and it is working good. Could you remove the `~/.conan/profiles/default` and try again? I don't know if it is failing the default profile detector maybe your default profile is wrong saying VS 2015.

**Comment by DaniCybereason** [comment]
I've tried already, it didn't fix it.

When conan created a new profile it was like this:

[build_requires]
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=14
build_type=Release
[options]
[scopes]
[env] 

Next step might be removing the whole conan cache perhaps..

**Comment by DaniCybereason** [comment]
I've tried now, I still get the following lines when the main package is building:

```
libname/ver-3.7.1@repo/stable: Calling build()
Found Visual Studio 14
```

and when reaching the test_package I get:
```
CMake Error at CMakeLists.txt:3 (PROJECT):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Development/lib/test_package/build/e251aa36f324ee9ec9b3200dd02bfdbaa657fd0e/CMakeFiles/CMakeOutput.log".
ERROR: PROJECT: Error in build() method, line 11
        cmake.configure()
        ConanException: Error 1 while executing cd c:\Development\lib\test_package\build\e251aa36f324ee9ec9b3200dd02bfdbaa657fd0e && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MT" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DCONAN_CXX_FLAGS="/MP4" -DCONAN_C_FLAGS="/MP4" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev -T "v140_xp" c:\Development\lib\test_package
failure with settings: MT x86_64 Release
```

**Comment by lasote** [comment]
So, now even CMake is finding the VS15. It looks like something is wrong with your VS installation. I experimented similar issues in the past and to be honest I think I uninstall VS and reinstall again, but not sure if even though I solved the issue.

**Comment by DaniCybereason** [comment]
I'll try that once I have some time. thanks for the idea!

**Comment by DaniCybereason** [comment]
I just found out my 15.8.7 update is paused in the middle of installation.
I will let it try to finish and see if it fixes the error...

For some reason the VS 2017 updater said I'm on the latest version and nothing to do, but when I ran the vs_installer.exe manually, it simply showed the update is paused...

Thanks for all the help, I will update if I still have a problem :octocat:

**Comment by DaniCybereason** [comment]
OK I'm closing the issue, very sorry for the confusion - it seems VS 2017 can install half an update and report it is fully updated in some parts of its UI...

**Comment by uilianries** [comment]
I can not believe, I wasted 1h today to achieve the same solution. Thanks for sharing the solution here!
