### ISSUE TITLE
Warn about unknown class attributes in attribute_checker plugin

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3775]
This plugin could be improved for example to check for class attributes declared by the user in the recipes, and that are not private, i.e. not prefixed by an underscore. That's because those names could clash with future changes, if conan decided to define an attribute with the same name.

Plugins are available since Conan 1.8.0.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by liberforce** [comment]
attribute_checker is built-in... And the plugin name is more relevant, as you may want to perform those checks for packages not on conan-center.

**Comment by liberforce** [comment]
I suppose plugins chain, so people using conan-center.py would still benefit from the changes in attribute_checker.

**Comment by liberforce** [comment]
@uilianries Or do you mean that those check would only be valid for stuff on the conan-center repo? Is stuff in conan-community/bincrafters using additional, non-official attributes?

**Comment by uilianries** [comment]
conan-center.py is a plugin to help us validating a recipe to be promoted in Conan center.

Because attribute_checker is a standard plugin and part of Conan, it can be improved directly, as you said.

But we could move attribute_checker to conan-io/plugins. Moving to plugins we could have the opportunity to bring more contributions just improving our plugins.

/cc @danimtb

**Comment by jgsogo** [comment]
Yes, It would be valuable to have a dedicated ``attribute_checker`` plugin now that we have defined which naming is reserved for Conan. For sure, this plugin should be called from ``conan-center`` one (and maybe activated by default).

Let's move this discussion to the [plugins-repo](https://github.com/conan-io/plugins), and keep here at ``conan-io/conan`` the issues related to plugins architecture: discovering, interfaces,...

**Comment by lasote** [comment]
I would include that plugin in the default conan.

**Comment by danimtb** [comment]
Yes, I think this makes sense in the attribute_checker plugin and it should be built in and kept simple.

**Comment by danimtb** [comment]
attribute_checker is shipped with Conan. It is like a built-in plugin. Is that your question?

**Comment by uilianries** [comment]
Yes, thanks :)

**Comment by memsharded** [comment]
attribute-checker was removed from Conan in 2.0, if anything it should be constructed as a hook
