### ISSUE TITLE
How to compare version in conanfile.py ?

### ISSUE THREAD

**Issue by dkgs** [conan-io/conan#3783]
In some conanfile.py, I would like to customize some steps depending on the version of the compiler (or some other elements). And I didn't find a proper way to compare versions.

Is it possible to add in Tools the version comparer that conan uses internally ?

Actually using conan 1.8.1

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
Hi @dkgs !

one possible approach:

```python
def configure(self):
    if self.settings.compiler == "gcc" and \
       float(settings.compiler.version.value) < 5:
        raise ConanInvalidConfiguration("This project does not support GCC < 5")
```

but there is a better approach:

```python
from conans.model.version import Version

...

def configure(self):
    if self.settings.compiler == "gcc" and \
       Version(self.settings.compiler.version.value) < "5.0":
        raise ConanInvalidConfiguration("This project does not support GCC < 5")
```

**Comment by danimtb** [comment]
Check also this how to: https://docs.conan.io/en/latest/howtos/check_conan_version_in_conanfile.html

**Comment by dkgs** [comment]
Waow I completely missed that part !

Thansk !
