### ISSUE TITLE
Usage of non C++11 packages from C++11 packages

### ISSUE THREAD

**Issue by ahauan4** [conan-io/conan#3784]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.8.2
OS: Ubuntu 14
Python 3.6.5

Conan Profile:
[settings]
os_build=Linux
arch_build=x86_64
os=Linux
arch=x86_64
compiler=gcc
compiler.version=4.8

We are using Conan profiles where compiler.libcxx is set to _libstdc++_ or _libstdc++11_.
Now we have the problem, that packages which were created with setting _libstdc++_ cannot be used by packages with setting _libstdc++11_.
Shouldn't packages which support _libstdc++11_ be linkable against packages which were created using _libstdc++_?
How can this be mapped to Conan?

Can you please explain this?

Thank You!

**Comment by memsharded** [comment]
Closing this thread as inactive.
it is necessary to use the same libstdc++11 for all dependencies, otherwise linking error happens.
