### ISSUE TITLE
"/usr/local/man" pip permissions needed

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#3785]
I am trying to install Conan (1.8.3 at the moment) from pip3 (18.0, also tested after upgrading to 18.1, on Python 3.7), on OS X (10.12, freshly installed VM). I issue the command:

    pip3 install conan

It fails with the error:

> Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/man'
> Consider using the `--user` option or check the permissions.

`/usr/local` is owned by root, and has not `man/` subfolder indeed.

And to make it a bit more surprising, if I issue the same install command a second time

        pip3 install conan

The installation complete successfully (I mean, no error displayed, and `conan` is available on the command line). And there are still no `/usr/local/man` folder after the successful installation.

Could that be a problem with Conan's pip recipe ?

**Comment by lasote** [comment]
We will try to find a fix because even being something "normal" it is not worth it to introduce such failures for a `man` that no one is reading.
You need to use ``--user`` or ``sudo`` to install it.

**Comment by jgsogo** [comment]
Here is an opened issue/pr to handle this issue with ``man``. We hope it to be released soon 😕  https://github.com/tqdm/tqdm/pull/629

**Comment by lasote** [comment]
It is tagged to 5.0, so I don't discard this even in a minor: https://pypi.org/project/tqdm-conan/

**Comment by lasote** [comment]
We will release 1.8.4 soon to fix this.

**Comment by casperdcl** [comment]
closed tqdm/tqdm#629 in tqdm/tqdm@f6448c14cc56fd60f830dd6984d2f6a930ea1795
