### ISSUE TITLE
[lock graph] There should be a way to repeat conan install without the need to re-specify any settings

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#3787]
A common workflow is that I call conan install once with some settings or some profile. Later on, I just want to update the dependencies. I cannot simply run `conan install -u <path>` to achieve that, but I must repeat the original settings or profile options, otherwise the default profile will be applied.

I would like to have some command that reuses these settings, either as a new command, maybe `conan update`, or as a simple option to conan install. I have a slight preference for the former, since this would also allow to reuse the source directory information, and I could call this without any additional parameters.

**Comment by jgsogo** [comment]
This sounds like having a _local profile_ file and use it to implement this behavior, doesn't it? Just thinking out loud: `conan install`:
1. if there is a _local profile_ file use it, otherwise use the default profile
2. override with command line options.

btw, I'm tagging it to 1.10, so this issue does not get lost.

**Comment by sigiesec** [comment]
I think that is not exactly what I had in mind.

I try to sketch the workflow I have in mind:
1. When running `conan install` for the first time (in a directory without any conanbuildinfo.*), store the settings in a file (maybe this is the local profile you mention), which may either have been specified from the command line or taken from a (non-local) profile
2. When running `conan update`, use the local profile.
3. When running the regular `conan install` again (in a directory with a local profile) with different settings on the command line or in the profile, fail.

**Comment by memsharded** [comment]
BTW, this might be related to current efforts in graph.lock files. graph.lock files are actually capturing the applied profile and using it later when using the graph.lock. If graph.lock files are captured at first install, then they might be reused as well. Many implications here, need to discuss.

**Comment by AshleighAdams** [comment]
It would be nice to have this functionality in a form that matches other package managers, so something like:

```bash
$ conan restore -pr debug .
```

**Comment by jgsogo** [comment]
@sigiesec , do you think the implementation using lockfiles is satisfactory enough for your use case?

@AshleighAdams, can you comment about the proposed `restore` command in a new issue? It would also be very helpful if you provide links to documentation of other package managers to know how they work. Thanks!

**Comment by sigiesec** [comment]
@jgsogo In my current work context, I don't use conan right now. Based on a brief look at the lock file description, I think that might be doing what we needed earlier. Maybe @GerrietReents knows if this is still relevant, and can provide better feedback in that case.

**Comment by GerrietReents** [comment]
It looks like the lockfiles approach is matching our needs. Thanks for providing this!
