### ISSUE TITLE
Private static library dependencies

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#3792]
To help us debug your issue please explain:

- [✅ ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [✅ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ✅] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I am having a problem I'll try to explain with the following example:

Let's have following packages that are all static libraries: `Aaa`, `Bbb`, `Ccc`, `Ddd` and `Ooo`. Also, let `Eee` be an executable that depends on `Ddd`.

Additionally, `Ddd` depends on `Ccc`, `Ccc` depends on `Bbb` and `Bbb` depends on `Aaa`.

`Aaa` has following conanfile:

```python
class AConan(ConanFile):
    name = 'Aaa'
    version = '1.0.0'
    options = {
        'use_o': [True, False]
    }
    default_options = {
        'use_o': False
    }

    def requirements(self):
        if self.options.use_o:
            self.requires('Ooo/1.0.0@user/testing')
```

i.e. `A` has an option `use_o`, it depends on `Ooo` package. Otherwise, it does not have any dependencies.

Now, let's first build `Ooo` with `conan create` and then build both versions of `Aaa` - the version with default options and the version with `use_o=True`. This simulates what a CI server would do when building `Aaa` package.

Next, let's build packages `Bbb`, `Ccc` and `Ddd` in correct order, but using only default settings, as none of those packages care about `Aaa's` `use_o` parameter.

Now, when installing package `Eee` with `conan install` everything works OK, but if `Eee` now wants to change `Aaa:use_o` to `True` with `conan install /path/to/Eee/conanfile.py -o Aaa:use_o=True`, it will need to rebuild `Bbb`, `Ccc` and `Ddd` packages even though they do not depend at all on `Aaa's` `use_o` parameter. The `Bbb's`, `Ccc's` and `Ddd's` binary will be **exactly the same** as with `Aaa:use_o=False`, but their `package_id's` will change because there is one more dependency in the graph.

Of course, `Eee` must be aware of `Ooo` in order to correctly link to it when creating final executable, but `Bbb`, `Ccc` and `Ddd` should not be rebuilt in that case. This wastes a lot of time in our real setup, as more than 100 packages are rebuilt because the top level package changes an option in bottom level package that introduces a new dependency and this wastes a lot of time and disk space for our developers. 
All packages in between are static libraries and should not be rebuilt. Actually, sometimes they should, but that should then depend on specific option of the dependent package, as mentioned in issue #3776. Is there a way to prevent rebuilding of packages `Bbb`, `Ccc` and `Ddd` when change in `Aaa's` option introduces a new dependency to the graph, i.e. is there a way to keep `Bbb's`, `Ccc's` and `Ddd's` `package_id` unchanged after `Aaa` introduces `Ooo` as its dependency?

Here is a little demo that follows the description above:
[conan-static-deps.zip](https://github.com/conan-io/conan/files/2493207/conan-static-deps.zip)

**Comment by memsharded** [comment]
Thanks very much for your detailed report and the reproducible case.

I was indeed able to reproduce it, and it is an issue. The bad news, is that it is not something easy to fix without breaking the package_id computation, that would affect all the binaries of all users. So that cannot be done.

We will be trying to propose a workaround for this, hopefully in 1.9, and think of a plan for fixing that long term (2.0).

**Comment by memsharded** [comment]
There is one possible workaround. You need to add to your package:

```python
class AConan(ConanFile):
    name = 'Aaa'
    version = '1.0.0'
    options = {'use_o': [True, False]}
    default_options = { 'use_o': False}

    def requirements(self):
        if self.options.use_o:
            self.requires('Ooo/1.0.0@user/testing')

    def package_id(self):
        if self.options.use_o:
            self.info.requires.remove("Ooo")
```
That is the way of expressing in Conan: Even if I use that optional requirement, that requirement will not affect.
 
This has a potential downside, is if you want to support using different versions of the optional requirement (doing overrides of it from downstream). As the requirement is being removed from the package_id computation, different versions of it will not generate a new package_id for ``Aaa`` package.

Please tell me if this could work, we will be discussing how changing that default behavior could be done for the future: https://github.com/conan-io/conan/issues/3762

**Comment by DoDoENT** [comment]
> This has a potential downside, is if you want to support using different versions of the optional requirement (doing overrides of it from downstream).

I think we can live with that. I'll try your workaround ASAP. Thank you for your kind help!
