### ISSUE TITLE
[question] Would a conanbuildinfo.cmake CONAN_IMPORTS_PATH global variable be useful?

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#3794]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).

**context:**
I am referring to the example provided in the documentation about the `ConanFile.imports` method ([here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports)):
```python
def imports(self):
    dest = os.getenv("CONAN_IMPORT_PATH", "bin")
    self.copy("*.dll", dst=dest, src="bin")
    self.copy("*.dylib*", dst=dest, src="lib")
```
Specifically I am looking at the usage of an environment variable to define the destination path for the dlls in this example:
```
    dest = os.getenv("CONAN_IMPORT_PATH", "bin")
```
In the project `CMakeLists.txt` we would retrieve this with `$ENV{CONAN_IMPORT_PATH}`.

**The problem:**
Having the source of truth for this setting external to both conan and cmake seems wrong to me.

Since this variable relates to the conan setup, it would be great to be able to set it inside the `conanfile.py` file and having the cmake generator add it in `conanbuildinfo.cmake` alongside the other aggregated global cmake variables (like `CONAN_INCLUDE_DIRS`, `CONAN_LIB_DIRS`, etc...). It is not really an "aggregate" variable as the other ones however, so not sure this would be a proper solution.

Is there a mechanism allowing this? Note that such a variable should be made available after running `conan install ...` for the project being built, so adding information from `ConanFile.build` or `ConanFile.package_info` using `ConanFile.cpp_info` would not solve it.

**Comment by lasote** [comment]
Currently I don't have a better idea. This could be related with a modification of the build helpers/generators we are promoting for Conan 2.0. the general idea is to pass to the build system two files, the first one with the dependencies information (current generators file) and a second one with information about the build configuration. Probably the needed variable could be injected in the second file from the applied environment.

**Comment by memsharded** [comment]
This is outdated, conanbuildinfo.cmake and imports, both removed in 2.0, closing
