### ISSUE TITLE
Additional CMAKE_MODULE_PATH?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3796]
`conanbuildinfo.cmake` created by CMake generator automatically appends package root dirs to CMAKE_MODULE_PATH in `conan_set_find_paths()` macro. But what if I need to append another package directory to CMake search path, say `${CONAN_SOME_PACKAGE_ROOT}/cmake`? Is it possible on the package recipe level so consumer don't have to modify its `CMakeLists.txt`?

**Comment by lasote** [comment]
I think `self.cpp_info.builddirs.append("more/dir")` should work. Could you try?

**Comment by db4** [comment]
Yes, it works. Thanks a lot!
