### ISSUE TITLE
Remove version and description from 'json' output

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3797]
JSON output as provided [here](https://github.com/conan-io/conan/pull/3717) has some redundant outputs:

```
"packages": [
       {
           "id": "0eaf3bfbc94fb6d2c8f230d052d75c6c1a57a4ce",
           "downloaded": false,
           "version": "1.2.11",
           ...
           "cpp_info": {
                ...
                "version": "1.2.11",
                "description": "A Massively Spiffy Yet Delicately Unobtrusive Compression Library (Also Free, Not to Mention Unencumbered by Patents)"
            }
        }
    ]
```

In my opinion, fields ``version`` and ``description`` don't make sense inside ``cpp_info``.

**Comment by jgsogo** [comment]
There is some work done in this direction here (https://github.com/jgsogo/conan/tree/issue/3641-version-description), which is built on top of PR #3733

**Comment by lasote** [comment]
I don't want to change the `conaninfo.txt` because it is parsed by artifactory/bintray and I'm a bit affraid. I don't know if the associated PR is only changing the `conanbuildinfo.txt`. So this could be better fixed with an `if`.

**Comment by jgsogo** [comment]
Related to https://github.com/conan-io/conan/issues/4675, it is about the cpp_info object too.
