### ISSUE TITLE
Variable requirement overrides and include prereleases in version ranges

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#3798]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant. Conan 1.8.3 on Windows 10 64bit
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

My continuous integration tool will deliver, which libraries are changed in my current development. Now I want to test all dependent products, if they would build and run (test...). The result would be returned to the CI tool. If everything fine, this would be merged into the main repository.

The versioning should follow semver.

My main line will be saved in e.g. `MyLib/1.0.1-dev.1@my/stable`, `MyLib/1.0.0@my/stable`. 
Now comes a change, which should be checked, before integrating into the main line. My idea would be, to put it into another channel: `MyLib/1.0.1-dev.2@my/refs123`.

In my main project the following requirement would be set: `MyLib/[~1.0.0-dev]@my/stable`.

Now a few things are missing:
- [x] I need to include prerelease version into the search range, so that `1.0.1-dev.1` would be find in range `[~1.0.0-dev]` -> This can be done now with #3898, e.g. `[~1.0.0-dev,include_prerelease=True]`
- [ ] Now I need a way to recognize the actual search range for the library.  I think an extended version of `conan info` with json output would help

The sequence would be as follow:
1. Generate library to test in `refs`-channel: `MyLib/1.0.1-dev.2@my/refs123`
2. Go to main project and find range for modified library. Delivers e.g. `MyLib/[~1.0.0-dev]@my/stable` (would find `MyLib/1.0.0@my/stable`)
3. Override in main project the range with `MyLib/[~1.0.0-dev,include_prerelease=True]@my/stable`
4. Now I request the actual used library with the override and would get the latest commited change in the stable channel: `MyLib/1.0.1-dev.1@my/stable`
5. For this I would set an alias locally to my `refs`-channel: `MyLib/1.0.1-dev.1@my/stable` -> `MyLib/1.0.1-dev.1@my/refs123`
6. Override again main project, this time with the `refs`-channel: `MyLib/[~1.0.0-dev,include_prerelease=True]@my/refs123` (will deliver `MyLib/1.0.1-dev.2@my/refs123`)
7. Build project and test it. 

Then I can check all projects, if the current changes would influence them and rebuild / test them. After returning all results to the CI tool, the temporary builds in `my/refs123` will be deleted again. The CI would then (if nothing failed) merge it into master branch of the repository and then generate the official package for it: `MyLib/1.0.1-dev.2@my/stable`

Could this be a way to go or is there a better way?

**Comment by jgsogo** [comment]
Wow! We are thinking about CI issues too. There are several new features that will help to orchestrate a CI system: revisions, graph-lock,... but, as you know, we will try to keep Conan as a tool that provides information, nothing about calling CI commands.

Right now, we need to clarify it inside the team before recommending a way to go. It will be related to graph-locks (~v1.12) and maybe it will require an associated git repository to keep track of project status, but it is not clear yet.

We can keep this issue opened to discuss it, provide ideas,... but there are other things that demand our attention before addressing the CI full-time.

**Comment by jgsogo** [comment]
Hi @climblinne!

Once the _loose_ and _include_prerelease_ params are available (to be released today), are you able to implement the workflow you propose in your first comment?

I don't know what you mean with the SVN part in
> Now I need a way to recognize the actual search range for the library. I think an extended version of svn info with xml output would help

Anyway, after building your `MyLib/1.0.0-dev.1@my/refs123` and uploading it to your server, you should be able to do a `conan search`, find your new package, and implement a few lines of python to resolve the version_range on your CI side, then make the alias and compile your dependent project. Is there anything else we can do on our side?

**Comment by climblinne** [comment]
> Once the _loose_ and _include_prerelease_ params are available (to be released today), are you able to implement the workflow you propose in your first comment?

I coming nearer to my target... it took me now two months to get "include_prerelease" feature into `npm/nodesemver` (https://github.com/npm/node-semver/commit/610faeffba4a8a9be917a9e461179741e8e64a6e), then in `podhmo/python-semver` and finally in `conan`.
> 
> I don't know what you mean with the SVN part in
> 
> > Now I need a way to recognize the actual search range for the library. I think an extended version of svn info with xml output would help

This was a mistake from my side. It should be `conan info` with json. There were also some conflicts with the version above. I updated these.

> Anyway, after building your `MyLib/1.0.0-dev.1@my/refs123` and uploading it to your server, you should be able to do a `conan search`, find your new package, and implement a few lines of python to resolve the version_range on your CI side, then make the alias and compile your dependent project. Is there anything else we can do on our side?

I think an extended version of `conan info` (json of standard output) would be the easiest way to go. This would deliver the text output of `conan info` in json format. So I can receive the used `version ranges` and the selected `version` of the library.


Another idea (would be much easier for me), would be the following:
It would be nice to add an extra channel as override parameter, so that all libraries would be in the same set to find the best match: Common set: `MyLib/1.0.1-dev.1@my/stable`, `MyLib/1.0.0@my/stable` and `MyLib/1.0.1-dev.1@my/refs123`
Could be something like: `self.requires("*/[{CURRENT_RANGE},include_prerelease=True]@[{CURRENT_USER_CHANNEL}, my/refs123]")`
This would be used on all packages `*`, the version range `{CURRENT_RANGE}` would be extended/overwritten with `include_prerelease=True` and the user/channel combination would be the original `{CURRENT_USER_CHANNEL}` and a second channel `my/refs123`.

I know, this is hard stuff. Still searching for a good universal solution....

**Comment by jgsogo** [comment]
I'm trying to get some attention over it: https://github.com/conan-io/conan/pull/4055

**Comment by jgsogo** [comment]
We are introducing the `--json` argument for the `conan info`, it will be released in v1.12 soon (#4359).

I'm closing this issue as it is starting to have many unrelated topics and some of them are already resolved. Please, feel free to open a new one pointing to those that are still an issue.

Thanks.
