### ISSUE TITLE
[feature] accept full package references for the --build option of conan create

### ISSUE THREAD

**Issue by StefanSchulz-Tesyo** [conan-io/conan#3799]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant. 
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Proposal**
1.) The`--build` option accepts full package references. Currently it only accepts package names and patterns for package names.
2.) The default behavior of the create method is changed. Current behavior (conan 1.8.1):
`conan create . <name>/<version>@<user>/<channel>` 
behaves (almost) identical to 
`conan create --build <name> . <name>/<version>@<user>/<channel>` .
Instead it should behave like 
`conan create --build <name>/<version>@<user>/<channel> . <name>/<version>@<user>/<channel>` .

**Use Case**
Assume a package A with two different channels (X and Y), where `A/1.0@U/Y` depends on `A/1.0@U/X`.
Currently there is no way to build `A/1.0@U/Y` without building `A/1.0@U/X` as well:
Calling `conan create . A/1.0@U/Y` builds `A/1.0@U/Y` AND `A/1.0@U/X`. As the --build option cannot differentiate between the two packages, there is no way to change this behavior. Implementing the above proposal allows for a more fine-grained control over which packages are built.

A similar problem arises for two users that publish a package with the same name. If you require both of these packages in your conanfile, you cannot enforce to build one of them and not the other.

**Remarks**
The second part of my proposal might break existing packages that rely on the current behavior. However, I am convinced that the `conan create` method should only build the minimum amount of packages necessary in the default case. The old behavior can be recovered by adding `--build <name>` to the command line.

**Comment by lasote** [comment]
As you mentioned I think it could be done without breaking current behavior by accepting the full reference and also only the name. I think this makes sense.

**Comment by jgsogo** [comment]
Agree with you, this makes sense and add value to the end user without breaking current behavior.

**Comment by uilianries** [comment]
Hello @StefanSchulz-Tesyo!

> Assume a package A with two different channels (X and Y), where  A/1.0@U/Y depends on A/1.0@U/X

However, it will result in a loop conflict. The namespace (user + channel) is not accepted to override another package, only the package name and its version are used e.g. OpenSSL/1.0.2l@conan/stable and OpenSSL/1.0.2q@conan/stable.

Conan creates a graph before to check which should be built based on --build pattern. When loading that graph, it checks to see if the same package/version is already declared (loop).

It's not possible to build a package that depends on itself using another channel, like your example.

Is there a specific scenario for your request?

**Comment by StefanSchulz-Tesyo** [comment]
@uilianries 
If I understand you correctly the current behavior also imples that I cannot include two packages with the same name + version from two different users?  Which is even more reason to change it.

Scenarios:
- two users provide a package with the same name + version. I want to build only one of those.
- my special use case: I want the 'build' channel to depend on the 'source' channel. I do not want to rebuild the source package every time. Using different package names has other downsides.

**Comment by memsharded** [comment]
Implemented. Will be released in conan 1.12
