### ISSUE TITLE
Conan doesn't keep the username to log to server anymore

### ISSUE THREAD

**Issue by dkgs** [conan-io/conan#3800]
From conan 1.8,

When an authentication is required by the conan server, the username is now always asked event though it was specified by conan user. In older version, only the password was required.

To reproduce:
```
$ conan user -c
$ conan user username
Changed user of remote 'server' from 'None' (anonymous) to 'username'
$ conan search -r server *
Please log in to "server" to perform this action. Execute "conan user" command.
Remote 'server' username:
```

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Thanks for reporting looks like a bug. Let's try to solve it ASAP
