### ISSUE TITLE
[feature] cmake_find_package generator: add support for full filenames

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#3808]
Hi there, 
I have a request that concerns the "cmake_find_package" generator.

at the moment
----------------
I am using fullnames to my libs in a package to pass them to 
``` python
self.cpp_info.libs = [u"C:\tmp\liba.lib"]
```

Now in the generated Find<PACKAGENAME>.cmake (at line 25) the script has the list of defined full filenames (path + filename).

If this gets passed to find_library at line 29 CMake cannot find the file because the function gets the full filename with path.

proposal 1
-----------
Let Conan pass only the filenames of the specified elements in the ``` self.cpp_info.libs ``` to the cmake_find_package generator.
``` python
[os.path.basename(f) for f in self.cpp_info.libs]
```

proposal 2
-----------
Let Conan add an additional line to the Find-module-file before the find_library-command (line 29):
```
get_filename_component (_LIBRARY_NAME "${_LIBRARY_NAME}" NAME)
```
A problem could be if a relative path is given like "abc/filename.lib".

proposal 3
-----------
Let Conan encapsulate the find_library with a CMake-if-exists-check right before the find_library-command.
```
if ((IS_ABSOLUTE "${_LIBRARY_NAME}") and (EXISTS "${_LIBRARY_NAME}"))
    set (CONAN_FOUND_LIBRARY "${_LIBRARY_NAME}")
else()
    find_library (...)
endif()
```

comment
-----------
I would prefere the third solution as this does not change the Conan base code at all only the generator code. Additionally this solution still offers the possibility to search for the filename if only a filename is provided or just use the full filename if one is given.

Best regards :)

**Comment by kutschkem** [comment]
The first two solutions do not make sure that the file CMake finds is the one specified in the conanfile, right?

**Comment by Johnnyxy** [comment]
Additionally one has to add all paths to the files in the ``` self.cpp_info.libdirs ``` info in Conan's package function. Then the result "should" be ok.

But at the moment the same problem exists already because the CMake PACKAGENAME_LIB_DIRS variable in the generated find-module.cmake can contain multiple paths.
As the find_library command uses these paths to look for the given filename it could find multiple candidates. If the filename exists for some reason in multiple paths it could pick the wrong one.
 
So solution 1 and 2 does not circumvent this behaviour.

**Comment by lasote** [comment]
In general if the issue is libraries with the same name  I would suggest to avoid it or avoid using find package. The correct way is to declare the libdirs in the cppinfo and only the names in the libs.

**Comment by memsharded** [comment]
``cmake_find_package`` deprecated in favor of ``CMakeDeps``
