### ISSUE TITLE
Create Windows installers with dependencies

### ISSUE THREAD

**Issue by NeroBurner** [conan-io/conan#381]
I'd like to use conan/cmake to create fat windows installation packages.

For Ubuntu I create deb files and specify the dependencies. So apt resolves the installation of dependencies (shared libraries) for the end user. On Windows there is no apt to manage those dependencies, so every shared library file has to be bundled in the installer.

Is there a way with conan/cmake/cpack to automatically bundle all runtime dependencies into an NSIS installer (or any other installer)?

**Comment by lasote** [comment]
Yes, It should be possible:

1. Create your project (the project to be packaged) and write a conanfile.txt or conanfile.py and require all your dependencies.

2. Use the [imports](http://docs.conan.io/en/latest/reference/conanfile.html?highlight=imports#importing-files) feature to bring to your project ALL the dependency DLL's.

3. Then invoke a separate script/program to pack the project. Maybe you can even call your script from conanfile.py. Let me know if you have any problem.
