### ISSUE TITLE
IndexError in SVN.excluded_files()

### ISSUE THREAD

**Issue by ahauan4** [conan-io/conan#3810]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.8.2
Python 3.6.5
SVN: 1.9.5 (r1770682) compiled Nov 26 2016, 14:22:31 on x86-microsoft-windows

When I use the new SCM Feature for SVN I get the following error:

```
> ERROR: Traceback (most recent call last):
>   File "D:\CWS\Tools\Python3\lib\site-packages\conans\errors.py", line 24, in conanfile_exception_formatter
>     yield
>   File "D:\CWS\Tools\Python3\lib\site-packages\conans\client\source.py", line 139, in config_source
>     _fetch_scm(scm_data, dest_dir, local_sources_path, output)
>   File "D:\CWS\Tools\Python3\lib\site-packages\conans\client\source.py", line 195, in _fetch_scm
>     excluded = SCM(scm_data, local_sources_path).excluded_files
>   File "D:\CWS\Tools\Python3\lib\site-packages\conans\model\scm.py", line 57, in excluded_files
>     return self.repo.excluded_files()
>   File "D:\CWS\Tools\Python3\lib\site-packages\conans\client\tools\scm.py", line 231, in excluded_files
>     if it[0] == 'I':  # Only ignored files
> IndexError: string index out of range
```

Output of svn client: 
```
'M       Modules\trunk\conanfile.py'
'I       Modules\trunk\include\Filter\properties.h'
'?       SDKs\base\trunk\bin'
'X       Scripts\trunk\Windows\Network'
''
```
There seems to be an empty line at the end which leads to the error in scm.py line 231

Could you please have a look at this?

Thank You!

**Comment by riggskevinp** [comment]
We just ran into this issue too.

Looks like it can be resolved by doing:

```diff
// scm.py", line 230
    def excluded_files(self):
        self._check_svn_repo()
        excluded_list = []
        output = self.run("status --no-ignore")
        for it in output.splitlines():
-            if it[0] == 'I':  # Only ignored files
+            if it.startswith('I'):  # Only ignored files
                filepath = it[8:].strip()
                excluded_list.append(os.path.normpath(filepath))
        return excluded_list
```

That way the behavior is well defined if the line is empty.

**Comment by jgsogo** [comment]
Thanks for the report, @ahauan4; and many thanks @riggskevinp for the fix, I also think it is the smartest solution (although we should consider calling with ``--xml`` and parsing the output).

Anyway, have you got any idea why this output is different than mine? I didn't get that last empty line, neither do the tests.

**Comment by ahauan4** [comment]
> Anyway, have you got any idea why this output is different than mine? I didn't get that last empty line, neither do the tests.
I think this depends on the version of the svn client installed locally. I had this problem with SVN 1.9.5 (r1770682) compiled Nov 26 2016, 14:22:31 on x86-microsoft-windows
