### ISSUE TITLE
[feature] Add new env variables to activate script from virtualbuildenv generator

### ISSUE THREAD

**Issue by GavinNL** [conan-io/conan#3811]
I am really loving the virtualbuildenv generator!  But the activate script that gets generated modifies the LDFLAGS and CXXFLAGS by appending to it. This is okay, but It would be really helpful to me if the following Conan explicit env variables were set in the activate script. (eg: glm(header-only) and fmt dependencies)

```
CONAN_GLM_INCLUDE_PATH=/conan_path/d351525cc53ebe68279edf1978846402420066e7/include
CONAN_GLM_LIB_PATH="/conan_path/d351525cc53ebe68279edf1978846402420066e7/lib"
CONAN_GLM_BIN_PATH="/conan_path/d351525cc53ebe68279edf1978846402420066e7/bin"
CONAN_GLM_INCLUDE_FLAGS="-I${CONAN_GLM_INCLUDE_PATH}"
CONAN_GLM_LIB_PATH_FLAGS="-L${CONAN_GLM_LIB_FLAGS}"
CONAN_GLM_LIBS=""
CONAN_GLM_LIBS_FLAGS=""


CONAN_FMT_INCLUDE_PATH=/conan_path/5461525caset346dfgsdfbcd788asd2352006234/include
CONAN_FMT_LIB_PATH="/conan_path/5461525caset346dfgsdfbcd788asd2352006234/lib"
CONAN_FMT_BIN_PATH="/conan_path/5461525caset346dfgsdfbcd788asd2352006234/bin"
CONAN_FMT_INCLUDE_FLAGS="-I${CONAN_FMT_INCLUDE_PATH}"
CONAN_FMT_LIB_PATH_FLAGS="-L${CONAN_FMT_LIB_FLAGS}"
CONAN_FMT_LIBS="fmt"
CONAN_FMT_LIBS_FLAGS="-lfmt"

CONAN_INCLUDE_PATH=$CONAN_GLM_INCLUDE_PATH $CONAN_FMT_INCLUDE_PATH
CONAN_LIB_PATH=$CONAN_GLM_LIB_PATH $CONAN_FMT_LIB_PATH
CONAN_INCLUDE_FLAGS=$CONAN_GLM_INCLUDE_FLAGS $CONAN_FMT_INCLUDE_FLAGS
CONAN_LIBS=$CONAN_GLM_LIBS $CONAN_FMT_LIBS
CONAN_LIBS_FLAGS=$CONAN_GLM_LIBS_FLAGS $CONAN_FMT_LIBS_FLAGS
CONAN_BIN_PATHS=$CONAN_BIN_PATH $CONAN_FMG_BIN_PATH

CONAN_BIN_PATH=$CONAN_BIN_PATH:$CONAN_FMG_BIN_PATH
```

I would like the user of my library to have the option of either using conan to build the library by using the virtual environment or having the libraries installed in their system. This way, conan is is not explicitally tied to my cmake file. For example, in my cmakelists.txt file I I could have a line like this
```
include_directories( $ENV{CONAN_INCLUDE_PATH} )
```
Which would add all the include paths. Or if that env variable is not defined, it would assume that the user has all these libraries installed in their system.

If I was simply compiling something from the command line for testing purposes, I could activate a virtual environment and execute the following from the terminal
```
g++ main.c $CONAN_INCLUDE_FLAGS $CONAN_LIB_FLAGS  -o main
```

I don't think this request would break anything since it's only adding extra env variables.

**Comment by memsharded** [comment]
Sorry this issue was never responded.

That generator was superseded in 1.X and fully replaced in 2.0 by new ``VirtualBuildEnv`` generator. 
Also the CMake integration is new.

So I am closing this issue as outdated.
