### ISSUE TITLE
Website: Make conan-center more discoverable

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#3814]
To make it more easy to discover available packages, there should be a link to conan-center in the top navigation (next to download) and in the footer with the additional links.

When people are new to Conan seeing what packages are available is like one of the most important things.

**Comment by lasote** [comment]
![image](https://user-images.githubusercontent.com/3807515/48774090-83494980-ecc9-11e8-8fd8-13d4eb2eff9d.png)

I don't like how it looks, I'll try something

**Comment by lasote** [comment]
But anyway, I'll close this to continue in the web repo.

**Comment by lasote** [comment]
deployed
