### ISSUE TITLE
Conan crash if .count-files consist NULL-character

### ISSUE THREAD

**Issue by pianoslum** [conan-io/conan#3815]
conan version 1.8.0, Windows 7 x64

For some reason (maybe a crash), the .count-files in each conan package in the cache were corrupted and contained a unicode NULL character (https://www.fileformat.info/info/unicode/char/0000/index.htm). This led to a conan crash for basically every package action (e.g. conan info).

I already prepared a fix (https://github.com/conan-io/conan/compare/develop...pianoslum:develop) which also adds a little bit more verbosity in case there is no number in the .count-file.

Is this enough info or should I elaborate?

**Comment by memsharded** [comment]
Yes, I think it is clear enough and makes sense, I have opened the PR here to pass CI: https://github.com/conan-io/conan/pull/3816 (you would need to sign the CLA there, please).
