### ISSUE TITLE
Bintray: Service error on zlib download

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#3817]
I haven't actively changed the CI setup for our gRPC recipe, but the zlib download doesn't work anymore and is throwing an `Service Error.`

https://travis-ci.org/inexorgame/conan-grpc/jobs/444415003#L947

Note: zlib is linked into our inexorgame Bintray repository, which is added as `upload_repo`: https://api.bintray.com/conan/inexorgame/inexor-conan

**Comment by danimtb** [comment]
This is a known issue that has been already reported to the Bintray team. Meanwhile a workaround for this should unlinking and re-linking the zlib package. Could you please give it a go?

**Comment by danimtb** [comment]
Verified this is an issue in the inexor-conan repo:

```
$ conan install zlib/1.2.11@conan/stable -r inexor
zlib/1.2.11@conan/stable: Not found, retrieving from server 'inexor'
zlib/1.2.11@conan/stable: Trying with 'inexor'...
ERROR: Failed requirement 'zlib/1.2.11@conan/stable' from 'PROJECT'
ERROR: Service Error. [Remote: inexor]
```

Conan Center works well:

```
$ conan install zlib/1.2.11@conan/stable -r conan-center
zlib/1.2.11@conan/stable: Not found, retrieving from server 'conan-center'
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 121B/121B
Downloading conanfile.py
[==================================================] 7.8KB/7.8KB
Downloading conaninfo.txt
[==================================================] 438B/438B
```

**Comment by Croydon** [comment]
We have linked a huge number of packages. Will it be fixed for existing ones or do I need relink them all?

**Comment by danimtb** [comment]
Please, try only with zlib. We had this issue reported in the past and it may be enough but can't tell if any further action will be needed right now

**Comment by Croydon** [comment]
I was able to unlink zlib from inexor-conan, but on the attempt to re-link it I'm getting:

> The package you chose to link contains artifacts that already exist in the target repo.

**Comment by Croydon** [comment]
It also still produces the `Service error.`

**Comment by Croydon** [comment]
@danimtb For zlib this problem is gone, not sure if this might happen with other linked packages as well. Is it supposed to be fixed in general?

**Comment by danimtb** [comment]
Bintray Team created a patch that will be deployed next week solving this issue. We cannot guarantee that other packages are not affected, so please report any further issue and we will try to fix it ASAP

**Comment by Croydon** [comment]
Okay. I'm going to close it for now and will report again if I run into further issues. Thanks!

**Comment by uilianries** [comment]
Hi @danimtb !

Seems like Bincrafters' package for SDL2 project is broken in Conan search.

It's available in Conan Center:
https://bintray.com/bincrafters/public-conan/sdl2%3Abincrafters/2.0.8%3Astable#files/bincrafters%2Fsdl2%2F2.0.8%2Fstable%2Fexport

And Bintray status looks fine: https://bintray.statuspage.io/

Also, It's possible to list all available packages:

    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    conan search -r bincrafters "sdl2/*"
        Existing package recipes:

        sdl2/2.0.7@bincrafters/testing
        sdl2/2.0.8@bincrafters/stable
        sdl2/2.0.8@bincrafters/testing
        sdl2/2.0.9@bincrafters/stable

But when we try to list a specific version:

    conan search -r bincrafters sdl2/2.0.8@bincrafters/stable
        ERROR: Service Error. [Remote: bincrafters]

As you can see, it is a similar error. I could upload again, but maybe Bintray can check this first.

Related issue: https://github.com/bincrafters/community/issues/617

**Comment by danimtb** [comment]
Seems there is a corrupted package. At least in sdl/2.0.8:
```
Checking ' sdl2/2.0.8@bincrafters/stable: 3058bc35e794b983ab2208f72fcf95fe723beb71' in remote 'bincrafters'... (73)
Possible corrupted package:  3058bc35e794b983ab2208f72fcf95fe723beb71
```

Please try deleting that package ID and try to search for binary packages again

**Comment by danimtb** [comment]
``conan search sdl2/2.0.9@bincrafters/stable -r bincrafters`` seems to be working fine

**Comment by danimtb** [comment]
Search of package for both ``sdl2/2.0.7@bincrafters/testing`` and  ``sdl2/2.0.8@bincrafters/testing`` seem to be good too

**Comment by uilianries** [comment]
Re-started CI build for sdl2/2.0.8@bincrafters/stable:

https://travis-ci.com/bincrafters/conan-log4cplus/jobs/172072571
https://ci.appveyor.com/project/BinCrafters/conan-sdl2/builds/21945822

**Comment by danimtb** [comment]
Seems the search is still failing and the corrupted pacakge 3058bc35e794b983ab2208f72fcf95fe723beb71 is still there. Please delete it manually

**Comment by uilianries** [comment]
It's not completely finished, but it's working again.

https://travis-ci.com/bincrafters/conan-sdl2/builds/98849165
https://ci.appveyor.com/project/BinCrafters/conan-sdl2/builds/21964487
