### ISSUE TITLE
Custom data dir

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3818]
To help us debug your issue please explain:

Hi!

I would like to able to have a custom path for *${CONAN_USER_HOME}/data* (Conan data directory) where I could store in a separated partition or device for example.

I could use multiple CONAN_USER_NAME, but my motivation is keep the same default profile on my local storage but remove/change all conan package data when necessary. Conan data dir could consume a huge space when storing multiple packages, including boost and openssl.

Saludos!

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
I think this currently not possible as the information stored in the registry will become inconsistent. In order to accomplish this one solution might be storing the registry file in the data folder, but I am not sure if this is the right approach

**Comment by lasote** [comment]
The data should be shared with a server, as Dani commented, the registry and other files would be inconsistent.
