### ISSUE TITLE
Conan replaces backslashes with forward slashes in env_info variable in activate.bat

### ISSUE THREAD

**Issue by adament** [conan-io/conan#3827]
Conan replaces all backslashes with forward slashes in activate.bat (and activate.ps1 and activate.sh). This means that to use a variable to pass the path to an executable, we have to manually convert the forward slashes back to backslashes.

I am using Conan 1.8.4 on Windows on Python 3.6. I have created a conanfile.py which contains the following:
```python
from conans import ConanFile
import os.path

class TestPkgConan(ConanFile):
    name = "TestPkg"
    version = "0.0.1"
    description = "A test package"
    settings = "os", "arch"

    def package_info(self):
        self.env_info.testpkg_root = self.package_folder
        self.env_info.testpkg_normalized = os.path.normpath(self.package_folder)
        self.env_info.testpkg_test = 'AC\\DC'
```
and I get the following activate.bat from the virtualenv generator
```cmd
@echo off
SET PROMPT=(conanenv) %PROMPT%
SET testpkg_root=C:/.conan/data/TestPkg/0.0.1/adam/testing/package/ca33edce272a279b24f87dc0d4cf5bbdcffbc187
SET testpkg_normalized=C:/.conan/data/TestPkg/0.0.1/adam/testing/package/ca33edce272a279b24f87dc0d4cf5bbdcffbc187
SET testpkg_test=AC/DC

```
I would expect the environment variable to be set verbatim to the value I chose. And the job of doing path separator conversion to be the packagers, however given that conan seems to do path separator conversion I would at least expect it to output windows native paths for files which are supposed to be consumed by Windows native tools, i.e. activate.bat and activate.ps1.

**Comment by jgsogo** [comment]
I've been having a look at the codebase and I have found that it is being replaced for every env var. I would think that it should be set verbatim too, but let's ask other @conan-io/barbarians if there is some reason to make this substitution.

Here (https://github.com/conan-io/conan/compare/develop...jgsogo:issue/3827?expand=1) I've prepared a PR with a test and a minor change that address this issue. Let's wait for feedback.
