### ISSUE TITLE
Create Package from precompile tar.gz and zip files

### ISSUE THREAD

**Issue by NeroBurner** [conan-io/conan#384]
I'm trying to get some legacy libraries into conan. The library is provided as tar.gz on linux and zip file on windows. The naming scheme for linux is
`mylib-<version>-<architecture>-<operating_system>.tar.gz`

and windows
`mylib-<version>-<architecture>-<operating_system>.zip`

version is in the style of major.minor.patch, for example `2.0.8`
architecture is one of x86, x86_64, (and additionally arm for linux)
operating_system is one of `linux` or `windows`

All filenames for my example:

```
mylib-2.0.8-arm-linux.tar.gz
mylib-2.0.8-x86_64-linux.tar.gz
mylib-2.0.8-x86-linux.tar.gz
mylib-2.0.8-x86_64-windows.zip
mylib-2.0.8-x86-windows.zip
```

the archives have two (for me) interesting folders: interface and library

How can I write a conanfile to upload those legacy tar.gz files to my conan-server?

Thanks in advance

**Comment by lasote** [comment]
Wow, it's a very generic question. I recommend you to read the `[conan docs](http://docs.conan.io)` about creating conan packages.

The names of the tar.gz/zips files are not a problem. In the "source" method you can download one or another reading your *self.settings* and *self.options*. 

The summary of creating a conan package could be:

1. Create a base project in a new folder with "conan new" command
2. Fill the source method to get the sources (the tgz/zip of sourcecode)
3. Fill the build method and invoke the build system (you can always condition the invocations to the self.settings and self.options that defines if it's linux, windows, compiler, package options...)
4. Fill the package method to move the built artifacts (includes and libreries)
5. Fill the package_info method to define libraries to link, flags etc.

You can see a lot of conanfile.py files in conan.io using the search Please, write if you get stuck in some point!

**Comment by NeroBurner** [comment]
Thanks for the (really) quick reply. A few more questions:

- how can I check if my conanfile is working as intended? I can call `mkdir build && cd build && conan build ..` and conan does extract the tar.gz file for me. But I don't know how to test the package step
- I want to upload the binaries. At [upload docs](http://docs.conan.io/en/latest/packaging/upload.html) the command `conan upload Hello/0.1@demo/testing --all -r=local` is shown. Why do I have to specify the version-variable in conanfile.py if I also have to tell conan this version number again? Or am I missing something?

**Comment by memsharded** [comment]
Hi! Yes, I also recommend to follow the docs tutorials about how to create packages if you haven't done, so, then you might also check existing conanfiles, e.g. What you are saying, I remember for example: https://github.com/lasote/conan-mingw-installer/blob/master/conanfile.py (in the build method, you might do it similarly in your source() if they have to be built, or there in build() if they are precompiled). 

Also if you need more interactive support, please write an email, we can arrange some chat, IRC...

**Comment by memsharded** [comment]
For your latest question:

- We recommend the use of ``test_package`` which is a small consuming project that runs automatically, to guarantee that everything builds, links and runs properly.

- About the upload, it works from your local cache to the server, it doesn't take into account your working copy or your current directory at all. So you have to reference the full name of the package. The flow is:
  - Export copies package recipes from your user space to the conan cache folder. From there, they can already be used as packages.
  - Packages can be uploaded from the local cache folder to any conan remote
  - Packages are retrieved from remotes and cached in the local cache folder
  - Files from the conan local cache folder can be copied to user space with the "imports" feature. Typically used to copy shared libraries or data files from the cache to user projects.

**Comment by NeroBurner** [comment]
I've got all the archive-files in my directory and want to bundle them in the upload to conan. Internally the packages are available over smb with ldap authentication

my `conanfile.py`
```
from conans import ConanFile, CMake, tools
import os
import tarfile

class mylibConan(ConanFile):
    name = "mylib"
    version = "2.0.802"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "txt"
    export = "*"

    def build(self):
        pkgname = 'mylib-2.0.802-x86_64-linux-factory'
        filename = os.path.join(self.conanfile_directory, pkgname + '.tar.gz')
        tar = tarfile.open(filename)
        tar.extractall()

    def package(self):
        pkgname = 'mylib-2.0.802-x86_64-linux-factory'
        interface_folder = os.path.join(pkgname, 'interface')
        library_folder = os.path.join(pkgname, 'library')
        self.copy("*.h", dst="include", src="interface")
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["mylib"]
```

following the [test_package docs](http://docs.conan.io/en/latest/packaging/testing.html) I created the following file `test_package/conanfile.py` and a dummy cpp and `CMakeLists.txt` file:
```
from conans import ConanFile, CMake
import os

# This easily allows to copy the package in other user or channel
channel = os.getenv("CONAN_CHANNEL", "factory")
username = os.getenv("CONAN_USERNAME", "builder")

class HelloReuseConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires = "mylib/2.0.802@%s/%s" % (username, channel)
    generators = "cmake"

    def build(self):
        cmake = CMake(self.settings)
        self.run('cmake "%s" %s' % (self.conanfile_directory, cmake.command_line))
        self.run("cmake --build . %s" % cmake.build_config)

    def test(self):
        # equal to ./bin/greet, but portable win: .\bin\greet
        self.run(os.sep.join([".","bin", "mydummy"]))
```

I then execute the followin commands
```
$ mkdir build && cd build

$ conan build ..

$ conan export builder/factory -p ..
WARN: Conanfile doesn't have 'url'.
It is recommended to add your repo URL as attribute
WARN: Conanfile doesn't have a 'license'.
It is recommended to add the package license as attribute
mylib/2.0.802@builder/factory: A new conanfile.py version was exported
mylib/2.0.802@builder/factory: conanfile.py exported to local storage
mylib/2.0.802@builder/factory: Folder: /home/gc/.conan/data/mylib/2.0.802/builder/factory/export

$ conan test_package ..
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "<string>", line 6, in run
  File "conan/conans/client/command.py", line 738, in main
  File "conan/conans/client/command.py", line 650, in run
  File "conan/conans/client/command.py", line 231, in test_package
  File "conan/conans/client/command.py", line 100, in _detect_tested_library_name
  File "conan/conans/util/files.py", line 98, in load
IOError: [Errno 2] No such file or directory: 'conanfile.py'
conan returned -1
```

I suspect that `conan test_package ..` does not work in the `build` folder is a bug. So I change to the root of the project and then it shows me, that nothing was uploaded (or copied) to the cache. The archive cannot be found
```
$ cd ..
$ conan test_package
Requirements
    mylib/2.0.802@builder/factory from local
Packages
    mylib/2.0.802@builder/factory:de9c231f84c85def9df09875e1785a1319fa8cb6

mylib/2.0.802@builder/factory: Installing package de9c231f84c85def9df09875e1785a1319fa8cb6
mylib/2.0.802@builder/factory: WARN: Forced build from source
mylib/2.0.802@builder/factory: Building your package in /home/gc/.conan/data/mylib/2.0.802/builder/factory/build/de9c231f84c85def9df09875e1785a1319fa8cb6
mylib/2.0.802@builder/factory: Configuring sources in /home/gc/.conan/data/mylib/2.0.802/builder/factory/source
mylib/2.0.802@builder/factory: Copying sources to build folder
mylib/2.0.802@builder/factory: Generated txt created conanbuildinfo.txt

mylib/2.0.802@builder/factory: ERROR: Package 'de9c231f84c85def9df09875e1785a1319fa8cb6' build failed
mylib/2.0.802@builder/factory: WARN: Build folder /home/gc/.conan/data/mylib/2.0.802/builder/factory/build/de9c231f84c85def9df09875e1785a1319fa8cb6
ERROR: mylib: [Errno 2] No such file or directory: '/home/gc/.conan/data/mylib/2.0.802/builder/factory/build/de9c231f84c85def9df09875e1785a1319fa8cb6/mylib-2.0.802-x86_64-linux-factory.tar.gz'
```

I thought I could just extract the archives and upload the headers and libraries to the local (as in LAN) conan-server and then pull just the right version (as in arch and OS) of mylib down to build another project

**Comment by memsharded** [comment]
Hi, thanks for such detailed feedback. Yes, probably the test_package failing in the build folder is a bug, but should be easy to fix.

What I can't see is what it could be failing. Might be a minor issue as some letter case in the paths, or most likely some minor path issue. I guess that the project is private, and I cannot clone it and try to debug. If not, I think the best would be to setup a minimal project to work with in github. Can you dump some of this into a github repo? If not, I might be able to try to do it myself later. Thanks very much!

**Comment by memsharded** [comment]
Thanks @NeroBurner for keeping track of this and closing it.

As reference, most of this functionality is simplified now with the ``conan package_files`` command. It is a relatively new command, and the interface might evolve, but it allows to directly define packages from user files in user folders, without specifying ``build()`` or ``package()`` method.
