### ISSUE TITLE
[question] Reference or recommendation for unit testing integration

### ISSUE THREAD

**Issue by ericjameszimmerman** [conan-io/conan#3848]
To help us debug your issue please explain:

- [x ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

From what I've read, I believe that:
- The test_package should only contain a minimal test for verifying the package and should not contain unit tests of the package/library contents
- You call conan build --test to initiate unit tests only
- The CMakeLists.txt should contain enable_testing() and add_test(...)

I would like to use google test.
So far, I've wrapped it into a custom package which includes some custom helpers, but it isn't clear how to use the add_test method / where my test cpp files would go.

Is there an usable example you could share?

Thanks,
Eric

**Comment by ericjameszimmerman** [comment]
Okay so enable_testing() and add_test() are CMake specific...
What I'd like to do is create my GoogleTest-based exe in the tests/ subfolder and run it when doing conan build --test.

I'm still missing the connection on how to make that happen

**Comment by uilianries** [comment]
As test package is indicated to validate only generated conan package. You won't be able to access all methods to execute a complete test, only exported methods will be available by your api interface.

For unit testing I recommend include all steps in you conan recipe. You could use the attribute [develop](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#develop) or the variable [CONAN_RUN_TESTS](https://docs.conan.io/en/latest/reference/env_vars.html#conan-run-tests). If your intention is including gtest, you could add some condition in [build_requires](https://docs.conan.io/en/latest/devtools/build_requires.html) to install gtest when needed.

I'll post an example ASAP.

**Comment by uilianries** [comment]
```python
from conans import ConanFile, CMake, tools

class ExampleConan(ConanFile):
    name = "example"
    version = "0.1.0"
    settings = "os", "arch", "compiler", "build_type"
    options = {"build_tests": [True, False]}
    default_options = {"build_tests": False}
    exports_sources = "*"
    generators = "cmake"

    def build_requirements(self):
        if self.options.build_tests:
            self.build_requires("gtest/1.8.1@bincrafters/stable")

    def build(self):
        cmake = CMake(self)
        cmake.definitions["BUILD_TESTS"] = self.options.build_tests
        cmake.configure()
        cmake.build()
        if self.options.build_tests:
            cmake.test()

    def package(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

**Comment by ericjameszimmerman** [comment]
Thankyou for quick response.

where would my folder / subdir to create the exe be located? ... my packages are typically .dll or .so
How does cmake.test() translate to source files in CMakeLists?

**Comment by uilianries** [comment]
`cmake.test()` is an alias for `cmake --build . --target test` or `make test` so that command is straightforward

**Comment by ericjameszimmerman** [comment]
I am relatively new to CMake; it is not clear how the CMakeList should look

**Comment by ericjameszimmerman** [comment]
So, should my CMakeLists.txt have something like this at the end?
```
IF (BUILD_TESTS)

add_executable(unittest test/unittest.cpp)

target_link_libraries(unittest myLibraryNameUnderTest)

# CTest is a testing tool that can be used to test your project.
enable_testing()
add_test(NAME unittest
         WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/bin
         COMMAND unittest)

ENDIF ()
```

I was originally thinking that the unit tests would have their own CMakeLists.txt and I would be calling `add_subdirectory(test)`

**Comment by uilianries** [comment]
you example looks good, but as you commented, you could use a subdirectory as well. 

for example:

```
# CMakeLists.txt
cmake_minimum_version(VERSION 3.1.2)
project(example CXX)

option(BUILD_TESTS "Run unit tests" OFF)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_library(example src/example.cpp)
target_link_libraries(example foo)

if(BUILD_TESTS)
  enable_testing()
  add_subdirectory(tests)
endif()
```

```
# tests/CMakeLists.txt
cmake_minimum_version(VERSION 3.1.2)
project(unittest CXX)

add_executable(unittest tests.cpp)
target_link_libraries(unittest example CONAN_PKG::gtest)
add_test(NAME unittest
         WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/bin
         COMMAND unittest)
```

**Comment by ericjameszimmerman** [comment]
Thankyou!
Just a note for anyone else reading this... If you get this linker error, make sure you are using `libstdc++11` in your profile, if using profiles.

```undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'```

One more question... the test runs during CMake, but other dependency DLLs are not copied into the build folder... any way to force this?

**Comment by ericjameszimmerman** [comment]
Also the google test output doesn't seem to make it to stdout.. The CTest shows 100% pass.
Is that expected?

**Comment by uilianries** [comment]
> Just a note for anyone else reading this... If you get this linker error, make sure you are using libstdc++11 in your profile, if using profiles.

That's because your profile is using compiler.libcxx=libstdc++, but your cmake file is not listed to use c++11 by -std argument. You could update your cmake adding compiler property `set_property(TARGET tgt PROPERTY CXX_STANDARD 11)`, or you could update your profile by `conan profile update settings.compiler.libcxx=libstdc++ default`

> One more question... the test runs during CMake, but other dependency DLLs are not copied into the build folder... any way to force this?

They are not copied because has environment tools, where both LD_LIBRARY and DLL path are solved automatically. But if you want to copy those files, you could use `import()`, take a look [here](https://docs.conan.io/en/latest/creating_packages/getting_started.html#the-test-package-folder).

> Also the google test output doesn't seem to make it to stdout.. The CTest shows 100% pass. Is that expected?

Yes. That's related to stdout or stderr treatment by Conan.

**Comment by ericjameszimmerman** [comment]
Thank-you again
