### ISSUE TITLE
Boost doesn't link

### ISSUE THREAD

**Issue by zolo** [conan-io/conan#3851]
```
[requires]
boost/1.68.0@conan/stable

# I've tried all combinations of these:
[options]
#boost:shared=False
#boost:skip_lib_rename=True
#boost:header_only=True
#boost:magic_autolink=True
```

In my target_link_libraries, I've tried using all conceivable combinations of ${Boost_LIBRARIES}, ${CONAN_LIBS_BOOST}, CONAN_PKG::boost, CONAN_LIB::boost_boost_system, Boost::system, etc.

I still get unresolved externals on boost's system. Tried with find_package as well.

If I install boost manually, use find_package and then Boost::system, everything links. But not with conan.

How to fix this?

**Comment by uilianries** [comment]
Hi @zolo!

Could you please move this issue to https://github.com/conan-community/community/issues?

All issues related to Conan packages are there.

We already have a related issue with the same problem.

Regards!
