### ISSUE TITLE
Env vars management improved

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3853]
Current issues:

- `environment_append` doesn't know when/how to merge an env var
- env vars like the `self.env_info` or the declared in [env] doesn't model if a var is a path to be able to replace the separators in the subsystems.

**Comment by madebr** [comment]
It would also be useful to prepend variables.
e.g. putting paths first in the PATH variable to give them higher precedence in the search path.

**Comment by lasote** [comment]
In general, if you set the PATH as `self.env_info.PATH.append("something")` in a package, all the "PATH" variables will be applied in order and always prepended to the system path. Do you have a more concrete example of what are you suggesting?

**Comment by lasote** [comment]
Interesting ideas about lazy evaluation: https://github.com/conan-io/conan/issues/5309#issuecomment-500107442

**Comment by lasote** [comment]
Already done some time ago.
