### ISSUE TITLE
[question] How to do post build operations on transitive dependencies?

### ISSUE THREAD

**Issue by mcsahin** [conan-io/conan#3856]
Hi, 
**Our current system:**
We have a framework containing many library projects depending each other and depending on 3rd party libraries (boost, qt, xerces.. etc). 
Each library in our framework is using CMake for building and at the end of the build (CMake post_build) it creates symbolic links to its' artifacts (shared library) in a folder specified by environment variable ($ENV_FRAMEWORK_DIR/bin). Moreover sometimes there can be library specific operations done on CMake post_build, too.

**Our aim:**
We need to move our framework and all our projects to Conan without changing current CMake files and effecting current development flow. Actually this is a must.

**What we did**
Firstly, thanks to Conan team for new feature python_require and many other amazing features that they give us.

1. We have created a base package containing common operations and inherit other libraries.
2. Inherited libraries only defines requirements, options and name. All other operations are done by using baseframework package definition.
3. We have successfuly replace conan specific operations on current CMakeLists.txt files on the fly.
4. We have successfuly set environment variables for consumer to use with virtualenv.

**The Problem**
Actually we planned to use deploy() function to create symbolic links on a certain directory ($ENV_FRAMEWORK_DIR/bin) as i mentioned above. Our plan was to call something like "conan install package/1.0@ci/master" to create symbolic links on consumer developer's computer. Than it can be used by developer's project.
This is working great if consumer developer using a library without transitive dependency. But unfortunately if there is an other dependency it does not call deploy() function of dependency's deploy() function.

How can we create symbolic links of library and its dependencies by calling only dependent package's deploy() method. Or is there any other suggession to solve this problem by reserving our current flow ($ENV_FRAMEWORK_DIR/bin/symbolic_links)?

**Comment by mcsahin** [comment]
Hi again,
**Do you think calling "conan command" inside conanfile.py is rational?**
To solve the problem above (to trigger deploy() function of dependency), may i use something like this:

```
class LibAConanFile(ConanFile):
    name = "libraryA"
    version = "1.0.0"

    requires = "boost/1.58.0@cots/stable", \
                      "libraryB/1.0.0@user/testing"
               
    def deploy(self):
        # call deploy function of dependency (libraryB)
        self.run("conan install libraryB/1.0.0@user/testing")
		
        # deploy operations of libraryA goes on here
        ...

```

**Comment by memsharded** [comment]
Hi @mcsahin 

No, running a nested conan command within the ``deploy()`` method doesn't sounds like the best approach.

This sounds very flow-specific, so maybe it wouldn't be a conan built-in feature, but something to be implemented in a plugin. Have you had the chance to have a look to the plugins? (they might be renamed as "hooks").

**Comment by mcsahin** [comment]
Hi @memsharded 

Hooks did not solve my problem because getting dependency information inside a hook is a bit confusing.
I have solved problem by using "deps_cpp_info"  and "deps_user_info objects" inside deploy() method.

**However, could you add a separate conan command option for deploy?** Instead of using "conan install package_ref", can we use "conan deploy package_ref"? "conan install" command is confusing on deploy i think.

Thanks again for this great tool, you can close this issue.

**Comment by memsharded** [comment]
> However, could you add a separate conan command option for deploy? Instead of using "conan install package_ref", can we use "conan deploy package_ref"? "conan install" command is confusing on deploy i think.

Yes, this is something that we have been considering for some time, still not sure about a general enough approach, this is the reason we are still discussing around it, you might follow discussion here, for example: https://github.com/conan-io/conan/issues/3280

Thanks to you for the feedback :)
