### ISSUE TITLE
Global `tools` module should be replaced with an instance

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3862]
To solve the global output (and runner) issue for Conan 2.0 we should provide a way to use the tools with an interface that doesn't require to use global instances.

To discuss:

- `Tools(self).replace_in_file()`. => Weird: `Tools(self).collect_libs(conanfile)`
-  `self.tools` => Weird: `tools.collect_libs(conanfile)`

Would the tools need also a refactor because of the conanfile instance?

Also, start to print a deprecation notice when the global `tools` module to encourage users to migrate to the new provided tool.
Finally, in Conan 2.0 remove the "tools" module.

Related with #3636

**Comment by jgsogo** [comment]
Personally, I like the current implementation... with the PR #3636 merged 🙄

**Comment by lasote** [comment]
Ok, let's discuss if we consider some improvement for Conan 2.0 or if we can live with it.

**Comment by lasote** [comment]
We are all ok as it is
