### ISSUE TITLE
Allow to specify different settings for required packages

### ISSUE THREAD

**Issue by fbeutel** [conan-io/conan#387]
Hey,

when requiring packages, is it possible to somehow override the global compiler settings for specific dependencies?
For example, if I want to build a project (and some of it's dependencies) in Debug mode, but I want one dependency to be used in release mode, can I somehow override the settings for that specific package?
For example something like:

```
[settings]
    OpenSSL:build_type=Release
```

I guess this is closely related to #212 , but maybe a slightly different issue since this should be possible for the consumer, even if the package creator didn't specify their package as binary compatible for some specific settings.

Also, I know of the possibility to use something like

```
[full_requires]
    Hello/1.1@demo/testing:73bce3fd7eb82b2eabc19fe11317d37da81afa56
```

but then one would have to manually find out the package sha and also adapt for setups that differ in some other aspect...

**Comment by memsharded** [comment]
Hi!
Unfortunately, it is not currently possible, at least in a straightforward way. The settings are defined as project wide, so it is not possible to specify different settings for a specific dependency. 

Said that, I think that this could be at least re-considered. It doesn't mean that it will be done, and secondary effects could be worse than the solution. We will have a look.

In the meantime, it is possible to do it, though requires some workaround. There are possible ways to do it. One way could be:

1. Install your dependencies from your conanfile, as usual, lets say, Debug mode. It will create a ``conanbuildinfo.cmake`` with all the include paths, libraries, etc...
2. Write a specific file, like conanfile2.txt with OpenSSL as the requirement, in a different folder. Install it with the ``-s build_type=Release``. It will create another ``conanbuildinfo.cmake`` file with some other variables.
3. Take those variables and replace them in the first ``conanbuildinfo.cmake``. Be careful, you have to replace them in two places, one specific for OpenSSL, and other where all the variables are grouped together. Look for OpenSSL string inside the cmake.
4. Keep the ``conanbuildinfo.cmake``, be careful not to overwrite it with a new conan install.

It might sound a bit cumbersome, but it will take just 5 minutes, and provide a viable workaround. Conan tries to be very transparent, and not very automagical. Please ask for help if necessary. We will study a possible conan feature for this. (I'd love the feedback from @tru, did you had a similar use case with different compilers mixed in the same dependency tree for one project? Or am I wrong and it was reported from other user?)

**Comment by fbeutel** [comment]
Thanks for the reply!
Another way of solving this a little more conveniently could be to add the option of "mock packages": A way to simulate a package and point conan to somewhere else instead of the conan package registry.

This would have two main benefits:

1. It would solve the above problem by letting the user pretend that there is a package with the given build configuration
2. It would allow the user to use system packages in select cases (for example: common libraries like glib or Qt are probably already installed on most linux systems).
3. When working on an app and also on library (as a separate project) that the app depends on, it is not very convenient to export the library back to conan every time one does a little change. Instead, one could redirect users of the library (for certain configurations) to the directory where the library is being worked on.

Such mock packages could be placed in a place like for example <userhome>/.conan/mock and a "mock package file" could look like the following:

Example that redirects consumers to system libraries:

	[provides]
	OpenSSL/1.0.2h@lasote/stable

	[settings]
	compiler=gcc
	build_type=* # Match any build type

	[cpp_info]
	includedirs=/usr/include
	libdirs=/usr/lib
	libs=[crypto, ssl]


Example that redirects the Debug build of a library to the release build:

	[provides]
	OpenSSL/1.0.2h@lasote/stable

	[settings]
	compiler=gcc
	build_type=Debug

	[requires]
	OpenSSL/1.0.1h@lasote/stable:c85f9b402dd4d46acdf074e1c63b768a41181d7a

Also, it might be worth thinking about letting other package creators use the [provide] section in their normal packages as well. Then, for example if someone removes all his packages, someone else could step in and continue to provide the removed packages. This would have some benefits in cases like the "npm debacle" (http://blog.conan.io/2016/03/30/are-c-and-c++-languages-ready-for-the-npm-debacle.html)...
	
Of corse one would have to think that through a little more carefully, I just wrote down what came to my mind right now ;)

**Comment by memsharded** [comment]
Hi, thanks for the ideas!

I think it is a nice idea, in fact I think that it can already be easily done with package recipes... 

Well I thought so. I was trying to build an example, but then I realized there is a small constraint in the include directories. I will try to remove it (maybe available for next release) and create an example of such a Mock package, and how to use it for the use cases you described.

Thanks again! Cheers.

**Comment by memsharded** [comment]
Hi @fbeutel, the possibility for defining different settings for individual package was requested also in https://github.com/conan-io/conan/issues/659, and has been implemented and will be released in next 0.16.

About the possibility to create package recipes that mock system libraries, that is also possible now, as absolute paths are possible in the ``cpp_info.includedir`` and other paths.

Also the replacement of removed packages is already possible, package overriding can be done for version, AND user/channel from downstream

So I'd say that this feature can be labeled as fixed.

**Comment by memsharded** [comment]
Released in 0.16

**Comment by peterbannister** [comment]
Hi I'm just getting to grips with Conan - thank you it is a game changer!

I'm finding myself needing to be able to use a release package in a debug build - is there an example of how to do it?  I have a local package I created for CrashRpt and want to use the release version of that in my application debug build. Or can I make the build_type an option instead of a setting?

I also have another similar use case - I have created a portaudio package.  Currently this contains a dll and a C++ wrapper.  I plan to split this into 2 packages and use the release build of the portaudio dll but the debug build of the c++ static lib.

**Comment by memsharded** [comment]
Thanks for your words :)

Yes, conan can set specific settings per-package, like:

```bash
$ conan install/create . ....   -s build_type=Debug -s CrashRpt:build_type=Release
```

I think this also covers the case for the portaudio split, please try.

**Comment by peterbannister** [comment]
Thank you - that _almost_ worked for crashrpt!  

There appear to be a few issues.
1) I get a separate 'Release' crashrpt package built for each of the the 'Debug' and 'Release' builds of my application. I had kind of expected to only have the one Release build of crashrpt (for the 32bit build).  But I guess the package parameters are subtly different in each case leading to a different hash?

2) The Release crashrpt buillt for the debug application was somehow defining _DEBUG..  Looks like the cmake build was set up for the debug visual studio runtime MDd.   I needed to pass the following in my powershell script to get it to work:

`conan install $path -s compiler=$compiler -s compiler.version=$compiler_ver -s arch=$arch -s build_type=$build_type --build=missing -s crashrpt:build_type=Release -s crashrpt:compiler=$compiler -s crashrpt:compiler.runtime=MD`

It would fail to take the crashrpt:compiler.runtime parameter without specifying crashrpt:compiler.
Still leads to a separate build for debug/release parent application - possibly there are more settings I need to fix?

So not insurmountable but slightly messy & kind of unexpected - though I think I now understand why.

This knowledge does also end up being a bit buried in a script that probably shouldn't have knowledge of this.  I guess perhaps I can resolve that with some environment vars - but it might be nice if there were a way to specify this stuff in the conanfile.py (or.txt)?

**Comment by memsharded** [comment]
Lets go step by step :)

> I get a separate 'Release' crashrpt package built for each of the the 'Debug' and 'Release' builds of my application. I had kind of expected to only have the one Release build of crashrpt (for the 32bit build). But I guess the package parameters are subtly different in each case leading to a different hash?

I am not sure what you are getting, is it possible that the package has different options? Maybe it has other dependencies? What is the ``package_id()`` in your recipe, if any? Can you print the output of ``conan search crashrpt/....``? Also would be relevant to inspect the local cache and compare the ``conaninfo.txt`` files of both packages.

I think you got it right with the runtime. The default runtime will match the build_type, so if you want to use the ``crashrpt`` for Release, you have to make sure it is also using "MD". 

In any case, the results of mixing Release and Debug artifacts is generally dangerous, may I ask why you are doing such? Specially when doing Windows, it is very common to get link or runtime errors.

Also, I would recommend using profiles, not command line arguments (and not in recipes, they should be orthogonal to this kind of input configuration). Are profiles what you are asking for? Thanks

**Comment by peterbannister** [comment]
Thanks for your help on this.

Sorry actually it looks like this was fixed by the MD runtime change!  Must have had some stale stuff in my cache (I could see 4 package IDs).

```
conan search crashrpt/1.4.3@local/stable
Existing packages for recipe crashrpt/1.4.3@local/stable:

    Package_ID: 908a20ec6c6293206044e5b119cc87e0c3c491e8
        [settings]
            arch: x86
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 12
            os: Windows
        Outdated from recipe: False

    Package_ID: e0a02d496bbb652b6295152dfce0d3937acc0b56
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 12
            os: Windows
        Outdated from recipe: False
```
So all good.

The main reason for wanting to mix debug & release would generally be for performance reasons where a debug build is painfully slow for some module (probably due to lock contention on MSVCs checked iterators).  If built in a dll and isolated via a C api then things are fine.  the debug build is never released anyway.  Clearly it will rarely work (if ever) for static c++ libs.

In this particular case, the debug version of CrashRpt asserts, corrupts the heap and crashes at application exit due to the way it is installed onto 3rd party threads.  It is 100% fine in release mode and this was how I previously had my application set up before working on automating the build.  solving the actual cause of this one is low priority for me right now - just using the release version is fine and hasn't been a problem for the last 5 years!

**Comment by peterbannister** [comment]
FYI I did also have this in my recipe:
```
        tools.replace_in_file("crashrpt/CMakeLists.txt", "project (CrashRpt)", '''project (CrashRpt)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()''')
```

Not sure if it may have had some affect in runtimes etc

**Comment by peterbannister** [comment]
will look at profiles

**Comment by peterbannister** [comment]
Profiles are what I was looking for!  Kind of glossed over that part whilst learning all the other stuff!!  Ty

**Comment by memsharded** [comment]
Ok, thanks very much for the explanation!
Yes, that totally make sense, some pimpl/hourglass-pattern over C api solves all those issues, so you are good :)

The above lines with ``tools.replace_in_file`` actually do the opposite, they help to set the correct runtime, because it is something that typically projects don't set, for example to be able to link with static MT runtime. So they should be good.
