### ISSUE TITLE
[question] Does conan support incremental build ?

### ISSUE THREAD

**Issue by AmitJain001** [conan-io/conan#3872]
Hi Conan Gurus , could you please provide the following information ?
1.  Can conan support build on monorepo 
2.  Does conan provide incremental build, like bazel ? 
3.  Also, in monorepo, build will always be from trunk version , so no version management needed. In that case, we do not have a dependency to store artifacts in Artifactory. Can conan resolve the dependency from local drive in this case ?

**Comment by uilianries** [comment]
Hi @AmitJain001 !

> Can conan support build on monorepo

If you are talking about multiple project on same repo, Conan provides [workspaces](https://docs.conan.io/en/latest/developing_packages/workspaces.html). But it's an experimental feature, feedback is welcome.

> Does conan provide incremental build, like bazel ?

Conan works based on package version. You could release (tag) you project, or even use a commit id as package version. If you are interested to provide only master branch, you could re-build the package for each new commit and upload, but there are many implications, including difficult to trace bug from project.

> Also, in monorepo, build will always be from trunk version , so no version management needed. In that case, we do not have a dependency to store artifacts in Artifactory. Can conan resolve the dependency from local drive in this case ?

If you are working alone, you could build on your environment and re-use from cache, but if you need to distribute those artifacts the answer is no. You will need run an Artifactory instance or conan_server. We recommend Artifactory, there is a C++ version and it's more complete than conan_server.
