### ISSUE TITLE
[question] Is there any plan to feature a CMake generator cmake_import_package

### ISSUE THREAD

**Issue by steinlec** [conan-io/conan#3875]
Dear team,

I am working for a company that needs to build software systems consisting of varying software packages that depend on each other. For that purpose, we actually investigate the utilization of CMake in combination with Conan.io for our standard C++ build system.

I have actually tested all your standard CMake generators. All of them are quite useful, but I have a question in this context. Is there any plan to feature a CMake generator like cmake_import_package, which simply uses the CMake configuration file of each dependend package, which is generated automatically by using the standard CMake functionality install(EXPORT ...) (see https://cmake.org/cmake/help/latest/command/install.html)? I have actually tested a required-package approach starting with cmake_find_package, which seems to operate quite well. I know of course that such a package dependency will work only for CMake dependent CMake packages. However this circumstance is almost satisfied in our environment.

The originating idea for my question is to simplify or at its best completely hide the conanfile.py scripts from the standard developer of a software package, so that he just needs to be able to produce the standard CMake scripts CMakeLists.txt. Having this goal in mind, I identified only two blocks, which are package specific. The first one defines the requirements, and the second one defines the deliverables. For the requirements, I can simply generate an universal conanfile.py template with our dependency modelling tool. However, it is not that easy for the deliverables. Many ideas later, it seemd to be the best approach to get the deliverables out of CMake, becaueall of them are implicitely defined there.

Best regards,
Christian

**Comment by memsharded** [comment]
Hi Christian,

I am not fully sure if I understood correctly the scope of ``cmake_import_package`` you are suggesting. Let me outline the flow I think you are proposing:

- Each package has its CMakeLists.txt build. At the last step of the ``build()`` method, it executes a ``cmake.install()`` step, which will package and create the information that your build is defining, including Config files from cmake.
- It is important to make sure that the information in those script is relocatable, so when installing that package in other system, it is not using absolute paths to non-existing locations. There is a helper in ``cmake`` to replace absolute paths in .cmake files.
- Those CMake config scripts will be packaged already in fhe final package.
- Now you want to consume them. The typical approach is to use the cmake-module-paths to locate the config scripts that are inside the conan packages. The ``cmake_find_paths`` generator can help with that. It seems you are suggesting a different one here, one that does something with the Cmake config files in the package dependencies. 

Does this make sense? Could you please elaborate a bit further the last point, or clarify the whole flow? Many thanks for your feedback!

**Comment by memsharded** [comment]
Hi Christian,

I am afraid I don't completely understand your proposal  (also I am not an expert in the find_package stuff 😅) :

> Coming now to the point, I am now able to add functionality directly inside the CMake find_package process. So there is no need for a specific CMAKE_TOOLCHAIN_FILE or a modification of any CMakeLists.txt, because the entire information is part of the CMake find_package process.

Are you talking here about a find_package overload? I know this is possible in CMake, but not fully sure how you would like to use it.

I think it would really help if you could outline the actual CMake code that you would expect as a result for a simple "Hello world" example package, and compare it with the current generated files. Just in case you don't know it, it is possible to create your own generators, so your approach could be tested even without implementing it in Conan: https://docs.conan.io/en/latest/howtos/custom_generators.html

Please let us know about the CMake code, so we can study better this use case. Thanks!

**Comment by steinlec** [comment]
Hi James,

I know my proposal is hard to understand when speaking theoretically. And with your recommendation for an example, you will see that it gets really simple. It just aims to smooth the world. ;)

But before adding the example, I try to give some more information about my motivation:

I am not talking about an overload in any place. I do also not modify anything in CMake or CONAN sources. I actually use a custom generator named conan_import_package. I can live with that, but I have to cope with some unpleasant issues. And maybe this solution perhaps can help others to smooth their situations. So my major motivation is just to get the interaction of CONAN and CMake smoother with regard to our operation purpose. For that purpose, I am talking about forwarding. Imagine you have a file on disk, which you need in some other place. So you simply forward the file by establishing links with the command “ln” for example. And exactly this is the idea behind. In the first step, the standard find_package command, which is located somewhere in the CMakeLists.txt of the toplevel package, finds the file Find<Package>.cmake, that is generated by the generator conan_import_package. The major task of this file is quite simple. It just modifies the CMAKE_MODULE_PATH and executes afterwards the same find_package command. But since the CMAKE_MODULE path is now different, because it contains now the correct path to the directory containing the dependent package and not its own path, this command loads the dependent package configuration itself. So this mechanism is just forwarding the find_package command, nothing else, but it offers the opportunity to catch the original call to be able to feature additional functionality like adding a special CMake target without modifying the automatically generated Find<Package>.cmake by the install(EXPORT …) command or the CMakeLists.txt, which tries to import the package by using the find_package command. The generator conan_import_package creates just an intermediary, so to say. And the trick is simply determined by the content of the variable CMAKE_MODULE_PATH, because dependent on that, the find_package command will find the one or the other file.

Coming now to the example, I try to keep it as simple as possible:

·         CMakeLists.txt of the toplevel package:

find_package(Dependency REQUIRED)
add_library(myToplevelLibrary ${LIBRARY_HDRS} ${LIBRARY_SRCS})
target_link_libraries(myToplevelLibrary Dependency::myImportableLibrary)


·         conanfile.py of the toplevel package:

class Toplevel(ConanFile):

    name                 = "Toplevel"
    generators      = "cmake_paths", "cmake_import_package"

    def requirements(self):
        self.requires("CMakeImportPackageGenerator/1.0.0@%s/%s" % (self.user, self.channel))
        self.requires("Dependency/1.0.0@%s/%s" % (self.user, self.channel))

    def build(self):
        cmake = CMake(self)
        with tools.vcvars(self.settings):
            cmake.configure()
            cmake.build()
            cmake.install()


·         CMakeLists.txt of the dependency package:

add_library(myImportableLibrary ${LIBRARY_HDRS} ${LIBRARY_SRCS})
install(TARGETS myImportableLibrary EXPORT myImportableLibraryExport RUNTIME DESTINATION bin ARCHIVE DESTINATION lib)
install(EXPORT myImportableLibraryExport DESTINATION "share" NAMESPACE Dependency:: FILE "DependencyConfig.cmake")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/ DependencyConfig.cmake" "include(\"\${CMAKE_CURRENT_LIST_DIR}/share/ DependencyConfig.cmake\")\n")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/ DependencyConfig.cmake " DESTINATION ".")


·         conanfile.py of the dependency package:

class Dependency(ConanFile):
    name = "Dependency"

    def build(self):
        cmake = CMake(self)
        with tools.vcvars(self.settings):
            cmake.configure()
            cmake.build()
            cmake.install()

    def package_info(self):
        self.user_info.targets        = json.dumps(["Dependency::myImportableLibrary"])


·         And finally the custom generator:

class cmake_import_package(Generator):
    @property
    def filename(self):
        pass

    @property
    def content(self):
        returnValue = {}
        for dependency in self.deps_build_info.deps:
            if (dependency != "CMakeImportPackageGenerator"):
                returnValue["Find%s.cmake" % dependency] = self._single_import_package(dependency, self.deps_user_info[dependency].vars["targets"] if ((dependency in self.deps_user_info) and ("targets" in self.deps_user_info[dependency].vars)) else None)
        return returnValue

    @staticmethod
    def _single_import_package(name, targets):
        content = [
            "message(STATUS \"Conan: Using autogenerated forward of Find%s.cmake\")" % name,
            "set(_CMAKE_MODULE_PATH_BACKUP ${CMAKE_MODULE_PATH})",
            "set(_CMAKE_PREFIX_PATH_BACKUP ${CMAKE_PREFIX_PATH})",
            "include(\"${CMAKE_CURRENT_LIST_DIR}/conan_paths.cmake\")",
            "list(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})",
            "list(REMOVE_ITEM CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR})",
            "find_package(\"%s\")" % name,
            "set(CMAKE_MODULE_PATH ${_CMAKE_MODULE_PATH_BACKUP})",
            "set(CMAKE_PREFIX_PATH ${_CMAKE_PREFIX_PATH_BACKUP})",
            "unset(_CMAKE_MODULE_PATH_BACKUP)",
            "unset(_CMAKE_PREFIX_PATH_BACKUP)",
        ]
        if (targets != None):
            content += [
                "",
                "if(NOT TARGET CONAN::%s)" % name,
                "  add_library(CONAN::%s INTERFACE)" % name,
                "  target_link_libraries(CONAN::%s INTERFACE %s)" % (name, " ".join(map(str, json.loads(targets)))),
                "endif()"
            ]
        return "\n".join(content)

Hopefully the example holds as many information as necessary for you to understand my thinking. My working example is unfortunately too complex to understand it without commenting each line, because I test multiple features with the same example. So no one except me has an idea about the need for each line of code. And many of them are just to work around some nasty issue.

As said, the approach with the custom generator is nice for me. However I have to cope with the following unpleasant issues:

·         The custom generator conan_import_package creates the same file in the same location for the same package as the internal generator conan_find_package. Consequentially, if I need both generators, there would be a file name conflict. Actually I have solved this by using a not operational file name in the custom generator cmake_import_package, that is renamed in the conanfile.py after deleting the original file created by the internal generator conan_find_package. I skipped this in the example. Although this works, it is against my intent to keep the conanfile.py as simple as possible and somehow template generateable.

·         To be able to forward the names of the CMake targets that have to be imported, I need to introduce the field self.user_info.targets in the package_info method of the conanfile.py. Until this is defined to be a text, I am additionally forced to use a JSON representation of the array of names. This also works, but is somehow nasty
If I can get rid of these issues somehow better, I would be very pleased.

Besides this, the following two lines in the CMakeLists.txt of the dependency package are just necessary to work around the incorrect CMake support for relocatable configuration files:
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/ DependencyConfig.cmake" "include(\"\${CMAKE_CURRENT_LIST_DIR}/share/ DependencyConfig.cmake\")\n")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/ DependencyConfig.cmake " DESTINATION ".")
Nevertheless, it works.

Returning now to my starting motivation, the only difference between the two given CONAN package example files (conanfile.py) is:

·         in the requirements() function to list the dependencies

·         in the package_info() function to list the importable CMake targets
So if I can finally find a mechanism to get the list of the importable CMake targets somehow out of CMake (Let’s say all targets without a father are importable), I can build a mechanism in our environment, which is able to produce a valid conanfile.py for each package, we have. Consequentially, I can use all features of CONAN without exposing one of them to our developers. This means I can empower our build system without increasing the complexity for the developers. They have just to be familiar with CMake including some CMake problems as mentioned above and our dependency system, nothing else. And that sounds perfect for our needs.

Kind  regards,
Christian

**Comment by memsharded** [comment]
CMake integrations have been completely change since then, new integrations as ``CMakeDeps`` replaced the old ones, so closing this as outdated.
