### ISSUE TITLE
[installer] [deb] Conan installers with Python3

### ISSUE THREAD

**Issue by ruimaciel** [conan-io/conan#3881]
I've just installed conan 1.8.4 from conan's official deb package (great job, kudos!) and when I run any conan command I receive the following friendly warning:

> Python 2 will soon be deprecated. It is strongly recommended to use Python 3 with Conan:
> https://docs.conan.io/en/latest/installation.html#python-2-deprecation-notice

However, I already have python 3 installed, so I assume that conan is already able to move to python3 without much trouble.

It would be nice if conan also provided some information on how to configure conan to use the python3 installation that's currently available, or even if the install process already performed some discovery checks to infer which python versions are available and which they could use by default.

**Comment by memsharded** [comment]
The installer packages are created with pyinstaller, that means they have a bundled, embedded python interpreter. They cannot be told to use other python interpreter, for that it is strongly recommended to use the ``pip install conan`` package instead.

You are right, that the installers are still using Python 2, they will eventually move to Python 3 too.
First we are moving conan-docker-tools, and generated CI scripts.

**Comment by ruimaciel** [comment]
Fair enough.  Keep up the good work!

**Comment by lasote** [comment]
Conan 1.13 installers will use python3.
