### ISSUE TITLE
Include options on inspect command

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3883]
To help us debug your issue please explain:

Talking on Slack with @Minimonium and @Artalus they have the idea of including `options` as default attribute on `inspect`. Sounds authentic.

Conan Version: 1.9.0

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Both options and default_options, and settings as well. Sure.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/3914
