### ISSUE TITLE
registry.txt is ignored after upgading 1.9.0

### ISSUE THREAD

**Issue by bc-lee** [conan-io/conan#3886]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan: 1.9.0 (Linux x86_64)

After upgrading 1.9.0, registry.txt imported by `conan config install` won't work: `registry.txt` is ignored and isn't migrated to `registry.json`.

Steps to reproduce: (My CI job is falling)
```sh
$ python2.7 -m pip install --upgrade conan 'pylint<2.0.0' 'astroid<2.0.0'
$ conan config install http://path/to/somewhere/config.zip
$ conan install /path/to/conanfile.py ...
```
Result:
```text
+ python2.7 -m pip install --upgrade conan 'pylint<2.0.0' 'astroid<2.0.0'
...
Successfully installed PyJWT-1.6.4 PyYAML-3.13 astroid-1.6.5 backports.functools-lru-cache-1.5 bottle-0.12.13 certifi-2018.10.15 chardet-3.0.4 colorama-0.3.9 conan-1.9.0 configparser-3.5.0 deprecation-2.0.6 distro-1.1.0 enum34-1.1.6 fasteners-0.14.1 future-0.16.0 futures-3.2.0 idna-2.7 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 monotonic-1.5 node-semver-0.2.0 packaging-18.0 patch-1.16 pluginbase-0.7 pygments-2.2.0 pylint-1.9.3 pyparsing-2.3.0 requests-2.20.0 singledispatch-3.4.0.3 six-1.11.0 tqdm-4.28.1 urllib3-1.24 wrapt-1.10.11
+ conan config installhttp://path/to/somewhere/config.zip
WARN: Remotes registry file missing, creating default one in /root/.conan/registry.json

Trying to download  http://path/to/somewhere/config.zip

Unzipping 4.3KB
Copying file registry.txt to /root/.conan/.
Installing settings.yml
Installing profiles
   ...
   
-- Conan executing: conan install  /path/to/conanfile.py ...
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
CC and CXX: /usr/bin/gcc4, /usr/bin/g++4 
...
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8230afb990>, 'Connection to conan.bintray.com timed out. (connect timeout=60.0)'))

Unable to connect to conan-center=https://conan.bintray.com
```
For reference: #3676

Q) Are `registry.txt` and `registry.json` parts of public interface of conan? ( https://docs.conan.io/en/latest/mastering/sharing_settings_and_config.html doesn't mention about `registry.txt` but I thought `registry.txt` is a part of sane configuration. )

**Comment by lasote** [comment]
Honestly we didn't think about using `config install` to install the registry file, actually lately we were thinking about removing the registry file in favor of different files in every package. 
We have to think about it because obviously, we are missing this use case, but it is not mentioned because it is not supposed to be shared. I'll talk with the team and I'll come back to you.

**Comment by lasote** [comment]
Quick question, are you sharing the `registry.txt` to configure the remotes or also to "attach" some package reference to a concrete remote?

**Comment by bc-lee** [comment]
@lasote Nope, `registry.txt` is just one-line file, which contains the internal repo. (no other references included.)

**Comment by lasote** [comment]
Then you should use `remotes.txt` file instead of `registry.txt` file: https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install

**Comment by bc-lee** [comment]
Got it.
