### ISSUE TITLE
conan search -r ${remote} -x report exception!

### ISSUE THREAD

**Issue by qimj** [conan-io/conan#389]
**conan reported an exception when i run "conan search -r ${remote} -x"

![image](https://cloud.githubusercontent.com/assets/6648308/17205792/126447da-54df-11e6-8d61-c23a90d28710.png)

**i used conan server with 0.9 version,  after updating server to 0.10 with same configuration. i search my old packages in remote server with command "conan search -r mogu -x", it reported an exception.Is this a bug? or how can i fix this?**

**Comment by memsharded** [comment]
I think this was a duplicated issue, did you close it because of that?
It is supposedly fixed, will be included in next release (soon)
