### ISSUE TITLE
[question] How are universal binaries (macOS, iOS) handled?

### ISSUE THREAD

**Issue by Manromen** [conan-io/conan#3891]
I just compiled some universal libraries for macOS which contain x86_64 and i386.
The conan package arch is now set to x86_64. Is there a way to set the arch to universal?
What is the way to handle this? If the package will be required for a build with arch i386 this package wouldn't be used right?

I couldn't see any setting to set this package as universal. Is there any intended way to handle this?

iOS libraries can contain multiple architectures too.

**Comment by RGPaul** [comment]
I just found the same question conan-io/conan-extensions#59
