### ISSUE TITLE
[question] Why conan info does not show build_requires from remote?

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3894]
To help us debug your issue please explain:

Hi! 

Kristian came up with the follow question on Slack:

> should self.build_requires("xx/yy@chan/branc")  show up in dependency tree or do i have to add something more ?

According the [documentation](https://docs.conan.io/en/latest/devtools/build_requires.html#properties-of-build-requirements), *build_requires* doesn't affect the package_id so is not integrated on dependency graph when running `conan info`.

However, when running such command directly over my conanfile.py, I'm able to see *build_requires* on my graph.

Conan Version: 1.9.0

##### Steps to reproduce:

* From Remote
* Expected result: gyp_installer is **NOT** listed on graph
    $ conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    $ conan info -r bincrafters libuv/1.23.2@bincrafters/stable --graph index.html
    $ firefox index.html

* Local
* Expected result: gyp_installer is listed on graph
    $ git clone https://github.com/bincrafters/conan-libuv.git
    $ cd conan-libuv
    $ git checkout stable/1.23.2
    $ conan info . --graph index.html
    $ firefox index.html

The question is, why there are different behaviors?

And answering Kristian, is it possible to include *build_requires* on graph?

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
maybe I understood now. As build_requires are only related to building time, I need to invoke by conan info to get that information:

    conan info -r bincrafters libuv/1.23.2@bincrafters/stable --graph index.html -db

![](https://screenshotscdn.firefoxusercontent.com/images/704535c9-2d6c-4c10-ad96-c61ae1228531.png)

**Comment by lasote** [comment]
Yeah, I think that is the reason. The build requires doesn't exist in the graph unless it has to be built.
