### ISSUE TITLE
Improve the server printed traces 

### ISSUE THREAD

**Issue by jakubgs** [conan-io/conan#3895]
I have a user configured for Conan server:
```ini
[users]
test: test
```
But when I try to check if this works it fails:
```bash
 % curl -s --basic -u test:test localhost:9300/v2/users/authenticate
Wrong user or password
```
Same goes for the `conan` command:
```bash
% conan user --password test --remote my-repo test                                                                                 
ERROR: Wrong user or password. [Remote: my-repo]
```
Am I doing something wrong here?

**Comment by jakubgs** [comment]
As far as I can tell I'm __supposed__ to use basic auth when calling `/v2/users/authenticate`:
https://github.com/conan-io/conan/blob/83d1b90f516b036889f6c52f7ae8adc38c6057aa/conans/client/rest/rest_client_common.py#L84

**Comment by lasote** [comment]
Does the `conan user test -p test -r REMOTENAME ` command work?

**Comment by jakubgs** [comment]
Nope, the order does not matter, I just get `ERROR: Wrong user or password.`.

And both the server and the client are the `1.9.0` version.

**Comment by lasote** [comment]
Have you rebooted the server after adding the test user?

**Comment by jakubgs** [comment]
Yes, multiple times.
Here is my whole config:
```ini
[server]
updown_secret: SECRET
jwt_secret: SECRET
jwt_expire_minutes: 120

authorize_timeout: 1800

ssl_enabled: False
port: 9300
public_port: 443
host_name: MY_DOMAIN

store_adapter: disk
# Just for disk storage adapter
disk_storage_path: /var/lib/conan/.conan_server/data
disk_authorize_timeout: 1800

[write_permissions]
*/*@*/*: admin

[read_permissions]
# By default all users can read all blocks
*/*@*/*: *

[users]
admin: SECRET
test: test
```

**Comment by jakubgs** [comment]
This is the docker image I've made(based off of another) to run `conan_server` with Gunicorn:
https://github.com/status-im/infra-utils/blob/master/conan/Dockerfile

**Comment by lasote** [comment]
And you don't have other servers running there right? If you shutdown the server the request fails, right?

**Comment by jakubgs** [comment]
Yes, it fails once the container is stopped.

**Comment by lasote** [comment]
I don't know. It is working here apparently. Try to run it locally to discard issues related to docker) networking etc.

**Comment by jakubgs** [comment]
Will try.

**Comment by jakubgs** [comment]
How can I verify which file is actually being loaded for config by the server?

**Comment by jakubgs** [comment]
OK, I think I've found the issue:
https://github.com/status-im/infra-utils/commit/9ba7d901e1a4e12225db6666a3ba730b982fc5ca
The `WORKDIR` for the docker container was not set which means my config was ignored completely.

How I found this out is by finding the default config in:
https://github.com/conan-io/conan/blob/develop/conans/server/conf/default_server_conf.py#L65
And checking the `demo` user instead:
```bash
 % curl -s --basic -u demo:demo https://conan.status.im/v2/users/authenticate 
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiZGVtbyIsImV4cCI6MTU0MTA4MTkzMX0._EgwK1Y8Nprm-G-ljLonDlSSvDiJFpAUjlCCjdzn7m
```
Now, this is something that should be made more clear in the logs I think. Because all my logs showed was:
```
[INFO] Listening at: http://0.0.0.0:9300 (6)
[INFO] Using worker: sync
[INFO] Booting worker with pid: 8
[INFO] Booting worker with pid: 9
[INFO] Booting worker with pid: 10
[INFO] Booting worker with pid: 11
```
And that's it. I think there should be some kind of message, like:
```
[WARNING] No server.conf file found, loading defaults!
```
And a note in your docs somewhere around here would help too:
https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#running-from-source-linux

**Comment by jakubgs** [comment]
Apparently setting `WORKDIR` did not help.
How can I specify the location of the config file for the server? I see that the `server_launcher:app` doesn't take any arguments as far as I can tell:
https://github.com/conan-io/conan/blob/develop/conans/server/server_launcher.py#L57

**Comment by jakubgs** [comment]
OK, I get it now, it just defaults to user dir, not current working dir:
https://github.com/conan-io/conan/blob/develop/conans/server/server_launcher.py#L19
That explains it.

**Comment by jakubgs** [comment]
I feel like there should be an ENV variable so one can specify where to put the config directory.

**Comment by lasote** [comment]
Try `CONAN_USER_HOME`.

**Comment by jakubgs** [comment]
No, setting `CONAN_USER_HOME` does not seem to do anything.

Thanks la bunch man, really fast response, I'm really grateful.
But as I said before, I really think that you should add at least a logging message that informs the user that the default config is used since Conan didn't find any config file. Probably would avoid confusion for some people.

**Comment by lasote** [comment]
To do: 
- at server start print the used config file location.
- print when the default is used/generated
