### ISSUE TITLE
[-e] Define cli syntax for packages in editable mode

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3903]
I'm working in a new feature: **install packages in editable mode.** ([branch](https://github.com/conan-io/conan/projects/1))

This feature should implement _the same_ behavior as the Python one: `pip install -e .` that makes the package in the working copy available system wide so you can use it from the sources you are editing.

In Conan we would like to allow the user to install a package (a full reference) in editable mode, so every recipe making use of it will use the recipe, includes, binaries,... from the working copy. This simplifies the workflow when dealing with several interdependent libraries at the same time. Changes in a package will be taken into account in the dependent one without calling any Conan command (of course, build/link is still needed to compile and update `.lib` or `.bin` files).

Ideas:

```
$ conan editable <path_to_conanfile.py> package/version@user/channel
$ conan install -e <path_to_conanfile.py> package/version@user/channel
```

but I want feedback from every @conan-io/barbarians and @conan-io/community-leaders, and everyone interested, to design a new command or use an existing one. We should also think about how this new option/command interferes with existing ones.

With the first implementation, I will provide a working example and explain what the package has to satisfy in order to allow _editable mode_. 💪 

Thanks for your feedback.

**Comment by lasote** [comment]
`open` / `close`

**Comment by memsharded** [comment]
I suggest grouping them in one master command:

```bash
$ conan edit open <pkg-ref> <path-to-conanfile>
$ conan edit close <pkg-ref>
```
To foresee for other possible variations.

**Comment by jgsogo** [comment]
I don't see the `edit open/close`, what about something totally straighforward?
```
$ conan link <path-to-conanfile> <pkg-ref>
$ conan unlink <pkg-ref>
```

**Comment by lasote** [comment]
I would tag it as `complex:medium` but `priority:high`, as it is in our roadmap key big groups.

**Comment by solvingj** [comment]
I think this is unnecessary.  My suggestion is to handle this exactly like PIP.   Run the `conan install` function without the `-e` and it will go back to normal behavior.  I wish I would have seen this discussion sooner.

**Comment by jgsogo** [comment]
This is how it will work. It is almost ready, just two PRs to review (#3902, #3986) and then land the functionality into `develop`.

I only have one question left, does the command `conan export <ref>` remove the reference ([this test](https://github.com/conan-io/conan/pull/3986/files#diff-b55d457fa3d3172942ade88b0d8b3f0cR34))?

**Comment by solvingj** [comment]
good question.  i think not.

**Comment by solvingj** [comment]
Related post regarding overall design of feature:  https://github.com/conan-io/conan/issues/4142
