### ISSUE TITLE
conan config install . unexpectedly writes files to recursively deepening path in ~/.conan

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#3904]
Run this command:
conan config install .

In a gcc 8.2 Docker container with Conan 1.9.0 installed, I got repeated output like this:
Copying file registry.json to /root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan
Copying file .profile to /root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/root/.conan/

...until after several seconds it stops with this error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 1428, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 445, in config
    return self._conan.config_install(args.item, verify_ssl, args.type, args.args)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 88, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 566, in config_install
    config_type, args)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conf/config_installer.py", line 131, in configuration_install
    _process_folder(item, client_cache, output)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conf/config_installer.py", line 95, in _process_folder
    shutil.copy(os.path.join(root, f), target_folder)
  File "/usr/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 36] File name too long:

When I try the same command with Conan 1.9.0 on Ubuntu 18.04 LTS 64-bit VM, I get just get this:
Copying file initrd.img to /home/steve/.conan/.
Copying file swapfile to /home/steve/.conan/.
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.6/site-packages/conans/client/command.py", line 1428, in run
    method(args[0][1:])
  File "/home/steve/.local/lib/python3.6/site-packages/conans/client/command.py", line 445, in config
    return self._conan.config_install(args.item, verify_ssl, args.type, args.args)
  File "/home/steve/.local/lib/python3.6/site-packages/conans/client/conan_api.py", line 88, in wrapper
    return f(*args, **kwargs)
  File "/home/steve/.local/lib/python3.6/site-packages/conans/client/conan_api.py", line 566, in config_install
    config_type, args)
  File "/home/steve/.local/lib/python3.6/site-packages/conans/client/conf/config_installer.py", line 131, in configuration_install
    _process_folder(item, client_cache, output)
  File "/home/steve/.local/lib/python3.6/site-packages/conans/client/conf/config_installer.py", line 95, in _process_folder
    shutil.copy(os.path.join(root, f), target_folder)
  File "/usr/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
PermissionError: [Errno 13] Permission denied: '/swapfile'

So with root access like in the Docker container, it looks like it copied various files into a recursively deepening path within ~/.conan.  I didn't have to be within ~/.conan when running it, same thing happened when I was in /.

This command was a mistake (an odd combination in my brain of 'conan install .' and 'conan config install <item>'.  I would expect the command to do some checking to see if there are valid config files in the specified location and quit with a clear error if there is not.

**Comment by lasote** [comment]
I cannot reproduce the recursion issue, and I think that it is the only issue it has to be fixed: 
About installing the files in the `/` folder and checking `valid config files in the specified location`, it cannot be done, everything is a potential valid file, you can share a cache with python classes or whatever you need, you are responsible of knowing what are you installing.

**Comment by ssrobins** [comment]
Try these steps on a machine with docker installed (I used Ubuntu 18.04 LTS 64-bit):

git clone https://gitlab.com/ssrobins/docker-linux-build.git
cd docker-linux-build
sudo docker build .
sudo docker run --rm -it ae48a30ea4bc bash -il
  where ae48a30ea4bc is the docker image ID printed in the last line of the docker build command.  This should put you inside a container of the image you just created.
Now run:
conan config install .

If that doesn't reproduce it, feel free to close this.  This isn't diminishing my productivity with conan at all, it was just such a weird thing, I had to share it in case there were more serious implications.

**Comment by lasote** [comment]
Thanks for the info. That way it tries to copy the whole system files to the conan config, but even though apparently (I didn't wait until the end) it is not getting into a recursive loop.

**Comment by ssrobins** [comment]
It looks pretty apparent to me right away that the path is getting longer and the 'File name too long' error comes within a minute.  Strange that you're not seeing it, I thought for sure a Dockerfile-generated docker container would be a pretty airtight reproduction environment :)

If I run the command from ~/, I get the same effect though it takes a little longer to error out.  Obviously, both are nonsense locations to load the config from.

**Comment by lasote** [comment]
When I run from `~/` it fails but the error is pretty descriptive, something like: you cannot copy `foo` into `foo` because it is the same file.
