### ISSUE TITLE
Unable to run exe using repackaged library with missing SONAME

### ISSUE THREAD

**Issue by mduvanel** [conan-io/conan#3910]
OS : Linux CentOS 7.2
Conan version : 1.8.4
CMake : 3.12 (using cmake_installer/1.0)
GCC : 4.8.5

I am having an issue with a third-party library that happens to have no SONAME. Here is my scenario:

- I have repackaged this library (let's call it libexample.so) as a conan dependency, the way it is described here: https://docs.conan.io/en/latest/creating_packages/existing_binaries.html. Let's call this dependency examplepkg.
- I am developing a conan package which consists in an executable and a bunch of shared libraries, which depend on examplepkg. I am using the CMake generator
- I can build and link fine with this dependency, as well as run the application as long as I am on the same machine.
- Now if I try to run it inside a docker container (using conan install), it tries to load the library from a non-existing path in /home/vagrant/.conan, which is the path where the example library is located on the machine that performed the build

Tracing the issue back I noticed that libexample.so has no SONAME field in its ELF header, and that the other shared libraries which are linking with it have an absolute path in the NEEDED field:

```
  NEEDED               libz.so.1
  NEEDED               /home/vagrant/.conan/data/examplepkg/1.0/channel/stable/package/de9c231f84c85def9df09875e1785a1319fa8cb6/lib/libexample.so
  NEEDED               libxerces-c-3.1.so
```

To try to fix this problem I made an attempt to set the IMPORTED_NO_SONAME property for that library in my CMakeLists.txt as follows:

```
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup(TARGETS)
    set_property(TARGET CONAN_LIB::examplepkg_example PROPERTY IMPORTED_NO_SONAME 1)
```

However I see no change in the behaviour. But the wording in the CMake documentation is a bit vague (emphasis mine):

> CMake **may** adjust generated link commands **for some platforms** to prevent the linker from using the path to the library in place of its missing soname. Ignored for non-imported targets.

I realize this might be more a CMake issue, however I am probably not the first one to encounter this issue with conan and I wonder if there are known workarounds for this type of improperly packaged libraries when using CMake?

I have also noticed this open issue which is quite on the same topic :  https://github.com/conan-io/conan/issues/3230

Thank you for your help!

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @mduvanel 

Thanks very much for the detailed report. 
I think this issue would fall in the bucket of https://github.com/conan-io/conan/issues/3230, or is there any significant difference am I missing?
If so, please copy this report there and close this issue, we could better centralize conversation in #3230. Many thanks!
