### ISSUE TITLE
Can't rebuild a package from sources when build_id is used even if recipe/sources changed.

### ISSUE THREAD

**Issue by NokiDev** [conan-io/conan#3912]
Conan Version :  1.9.0

I'm trying to rebuild one of my package, that use build_id method with same version, channel, user, name using 

`
conan create . <myPackage>/<version>@<user>/<channel>
`

conan won't call build method, and will call directly package method. Even when using 
`
--build <myPackage>
`

The only way I can achieve this is to remove my conan package from cache, and that's not convenient.

Also, as said in the title, if I had sources or conanfile modified, conan will notice the change, and print 
`
<myPackage>/<version>@<user>/<channel>:  A new conanfile.py version was exported
`
and 
`
<myPackage>/<version>@<user>/<channel>: WARN: Forced build from source
`

But in the end won't rebuild anything, and will go directly to package method.
Making the package compromised.

I can submit a repro repo if needed.

**Comment by memsharded** [comment]
Hi @NokiDev ,

But this is exactly how ``build_id()`` works. It will keep the build if the resulting build-id is the same. If you want to clean it, you can with ``conan remove <pkg-ref> -b``.

Not sure if I understand the issue, this seems the intended behavior, could you please clarify?

**Comment by NokiDev** [comment]
Hi @memsharded 

Maybe I wasn't clear enough or I'm misleading about how build_id should works

Build id  to me is a way to identify a build. 

Then you have the ability to override this id generation by making options to a special value, making the id identical between builds with certain options or option combination, avoiding a rebuild from sources if thoose options changes.
We can make conditional build id, setting to "Any" an option if we are on windows, or with build_type =Debug.  

If I don't override build_id method, 
I can call conan create an unlimited number of times and it will always perform a full rebuild from sources. 
Seems to be a normal behaviour to me since if I want to recreate the package I want to rebuild from source.

If I override build_id method with an empty one. 
the normal behaviour is no longer applied and conan will skip the build and make a call to package method directly. 

In both cases, the generated id is the same, but the behaviour is completely different. 
Why not seems a little weird but maybe it should works like this.
But if I add --build <myPackage>, I precise my will to make a rebuild and I think conan should at least allow me to perform a complete rebuild without removing package then re run conan create, again and again. 

The other thing about rebuild is 
if I add sources / modify conanfile whatever, new sources are exported for the same package, but no build will be performed. 

Leading to a mismatch sources vs builds, and that's seems wrong, how could we be sure that we rebuild the same package after I upload modified sources or recipe ? 

Maybe that should be two separated issues.

But in any case tell me if it's normal behaviour and should work like this. And so if you have an Idea or some workflows to deal with this ?

**Comment by memsharded** [comment]
> If I override build_id method with an empty one.
the normal behaviour is no longer applied and conan will skip the build and make a call to package method directly.

Yes, these are the semantics of ``build_id()``. It means: if there exists a build folder with that build-id do not build from sources again, but reuse the existing build folder, and thus, only package.

This was the requested functionality by users when this feature was introduced. The idea is that two consecutive ``conan create`` commands, should only build once if they had the same build-id. As the ``conan create`` is already internally and automatically adding the ``--build=MyPkg`` argument, the ``--build`` argument cannot be used as an indicator of "needs to be built from sources". Changing the source code or recipe doesn't invalidate existing builds or packages, so it is not possible to remove the build folder in that case either. This was implemented to support packaging with a new "package()" or "package_info()" method in the recipe, without needing to build from sources again.

So the ``build_id()`` functionality was shaped with those requirements. The idea, is that if you still want to force the rebuild, it is doable removing the build folder, and that is achieved with a few key strokes:

```bash
$ conan remove Pkg* -b -f && conan create ....
```

Note that for most cases, this feature probably shouldn't be used. It was originated by some third party open source libraries which build systems were building at the same time static and shared libraries, and breaking that would be too much. The way to go, which is also the standard approach is to define those things as configurable.

**Comment by memsharded** [comment]
> In my company we use build_id for making two packages, one with documentation and second without, controlled with a "build_docs" option it works well.

But the idea is that if you have such options, you can directly use it in the build, right?

```python
def build(self):
    if self.options.build_docs:
         self.run("make html")
    else:
         cmake = CMake(self):
         cmake.configure() ...
```
Is it not possible to do that approach? That would be the recommended one if possible.

> How ? Maybe I'm wrong again but if I make a package locally, modifying the sources and then upload package + sources to a remote. If one needs a different option that the pre-built package offers. He will used the modified sources (or even modified recipe) when building his package. That's weird, we cannot be sure that the packages reflects the sources it comes with.

The binaries that were generated with the old sources are marked as "outdated from recipe", but not deleted. In many cases, there is only one small change (e.g. a comment in the conanfile.py, or in some header), and users didn't want to have to rebuild all the binaries. You can check the "outdated from recipe" in the ``conan search`` (yellow color in ``conan search <pkg-ref> --table=file.html``.

> If I was a bad person I could upload a compiled package with a backdoor or whatever tricks hackers uses along with clean sources, If the consumer don't rebuild the package from sources, he won't notice anything.

If you were a bad person you could upload malicious binaries by different means. Note that it is not even necessary to ``export`` the sources together with the package, it is perfectly possible to package pre-existing binaries, even closed-source with ``conan export-pkg``. Relying on third party binaries is always a risk, independently of the platform. We are working on some measurements to minimize this risk, but it will always be there. For production usage we encourage to always build your binaries in-house and upload to your private conan server.
