### ISSUE TITLE
Add options to make conan inspect more machine friendly

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#3913]
I would like to make `conan inspect` more machine friendly.  Here are two things that would help me:

Add an option where the label will not be included on the attribute.  For example, currently if you run
```
$ conan inspect . -a name
name: service-common
```
Then a script would have to parse the actual name from the output.  I would like to have an option that would remove the label, like:
```
$ conan inspect . --no-label -a name
service-common
```
Also, I'd like a way to have the JSON output sent to stdout.  For example:
```
$ conan inspect . -j -
{"name": "service-common", "version": null, "url": "http://bitbucket-idb:7990/scm/deal/falcon.git", "homepage": null, "license": "Copyright (c) 2018 Tradeweb", "author": null, "description": "Falcon Base Service common library", "topics": null, "generators": ["cmake"], "exports": [], "exports_sources": [], "short_paths": false, "apply_env": true, "build_policy": null}
```

Thanks,

**Comment by memsharded** [comment]
Hi @sourcedelica 

Regarding the last one, would it be ok if there is other output in stdout, before the  actual json? Or should it be completely silented?

**Comment by sourcedelica** [comment]
In that case it should be completely silenced, so you could use the standard output of the `conan inspect` command directly.

**Comment by memsharded** [comment]
And what if something fails? Where should the output be directed for later inspection?

I guess we should discuss this, as this affects the whole design of the UI and the internal conan API.

**Comment by sorekz** [comment]
We are using the conan_api directly and face similars problems regarding machine readability.
Since e.g. the generators can be defined as string, tuple, list, array in the conanfile, we currently need to do a lot of checks to get the list of generators. 
You'll likely face the same problem when getting the output into json format. Maybe the api could also be adjusted to always return a list when the value can be a list (options, default_options, settings, generators, exports, ...)

For the command, maybe you could reuse the format that is used in some api methods (e.g. users_list) but provide the error details:
`{"error":"errormessage", "inspect":{"name":...}} `
Of course the goal is to have the same format for all methods in conan 2.0. So this might not be good enough.

**Comment by lasote** [comment]
The second part of the json to the `stdout`, in nix systems, can be done with ``conan inspect . --json /dev/stdout`. I think this is enough for now. If you really want these feature I would like to separate it in a different one because as @memsharded said, it implies several changes in the api.

The things I think we can do:

1) Add a ``--porcelain`` argument that will return only the values, one per `-a` specified, in a new line, in order.
2) If ``--json`` is specified do not output anything to the stdout.

**Comment by sourcedelica** [comment]
That sounds good to me.

**Comment by lasote** [comment]
Blocked until: https://github.com/conan-io/conan/issues/4225

**Comment by monsdar** [comment]
> Add a --raw argument that will return only the values

Some of our CI automation is currently done with strange long commands like `export CONANREF = $(python -c "import json; j=json.load(open('packageInfo.json')); print(j['name'] + '/' + j['version'] + '@user/release')")`

So this would be very welcome.

**Comment by niosHD** [comment]
I second that feature request! Last time I had to extract some recipe information for scripting purposes I ended with code such as the following:

```bash
NAME=$(conan inspect . -a name | sed -e "s/^name: //")
VERSION=$(conan inspect . -a version | sed -e "s/^version: //")
```

Maybe there are even simpler/cleaner ways to implement the post processing but I would hope that we can get rid of it completely at some point.

**Comment by memsharded** [comment]
Ok, could we do at least the ``--raw`` part @lasote? That would be very simple to implement and alleviate some of these issues.

**Comment by lasote** [comment]
Yes, but take into account that some output can always be printed for unexpected reasons to the stdout, like the issues with the console encoding, the issues with the pre-commands launched in every Windows shell and so on.

**Comment by lasote** [comment]
Let's do it anyway, a `--raw` argument to the `conan inspect` command that prints only the values of the specified fields, in order and one field per line.

**Comment by jgsogo** [comment]
What do you think that should be the output for `options`, `settings` and `default_options`? Currently, it is:

```bash
settings: ('os', 'arch', 'build_type', 'compiler')
options:
    bar: [True, False]
    foo: [True, False]
default_options:
    bar: True
    foo: True
```

**Comment by lasote** [comment]
Wow, good point. @monsdar @memsharded suggestions?

**Comment by monsdar** [comment]
Hmm... JSON is probably the easiest to use, even within a bash script - is it? How are other applications return lists of values? I'm not that experienced when it comes to scripting :/

**Comment by lasote** [comment]
Yeah, that might be a good reason to not implement the ``--raw``. Maybe "one line per value without the field name except for options and settings that...." would be too tricky. Maybe the original proposed ``--no-label `` would make more sense?

**Comment by niosHD** [comment]
I have no particular preference but, as mentioned above, would love to be able a single text value from `conan inspect` without any post processing. If this is possible with the `--no-label` flag then this sounds great for me. When more complex data is requested, using something like `yaml`, which can easily be parsed by humans and machines, is a sensible default output format in my opinion.

**Comment by lasote** [comment]
We talked again about this, we finally are going to call it `--raw=field` and it will allow only one field, without printing the label. It will be incompatible with `-a`. It will print any number of lines, but only for one field and without label.

**Comment by jgsogo** [comment]
With that approach, given this conanfile.py:

```python
        from conans import ConanFile
        
        class Pkg(ConanFile):
            name = "MyPkg"
            version = "1.2.3"
            author = "John Doe"
            url = "https://john.doe.com"
            settings = "os", "arch", "build_type", "compiler"
            options = {"foo": [True, False], "bar": [True, False]}
            default_options = "foo=True", "bar=True"
            generators = ["txt", "cmake"]
            other = ("txt", "cmake")
```

the output will look like (`%` is not printed, it just indicates that there is no newline char):

```bash
⇒  conan inspect . --raw=url 
https://john.doe.com%                                                                                        
⇒  conan inspect . --raw=settings
('os', 'arch', 'build_type', 'compiler')%                                                                    
⇒  conan inspect . --raw=options 
{'foo': [True, False], 'bar': [True, False]}%                                                                
⇒  conan inspect . --raw=default_options
bar=True
foo=True%
⇒  conan inspect . --raw=generators
['txt', 'cmake']%                                                                                           
⇒  conan inspect . --raw=other     
('txt', 'cmake')%  
```

Check:
- [ ] do we want a new line at the end?
- [ ] `settings` and `default_options` are always written with the same format, Conan converts `settings` to a tuple and `default_options` to lines with `option=value` format.
- [ ] other attributes are written _raw_, `generators` and `other` are an example in the previous Conanfile: if it is a list it will be printed as a list, if a tuple it will be a tuple.

**Comment by lasote** [comment]
I checked the options, about the second. is that a question or a fact? if they are printed always with the same format, ok, otherwise, if it depends on how the recipe looks like, even ok too.

**Comment by jgsogo** [comment]
It is a fact, Conan converts them to its own model and print them always with the same format.
