### ISSUE TITLE
python_requires does not work with alias recipes

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#3920]
- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.9.0

I have a base class that I am using with python_requires.  If I create an alias for the base class recipe and try to use that, for example:
```
conan alias myBase/LATEST@myUser/stable myBase/0.2@myUser/stable
```
```
base = python_requires('myBase/LATEST@myUser/stable')
```
Then I get errors like:
```
$ conan inspect . -a name
ERROR: Unable to load conanfile in /userhome/epederson/falcon-conan/common/conanfile.py
  File "/develop/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/userhome/epederson/falcon-conan/common/conanfile.py", line 6, in <module>
    class MyConanFile(base.BaseConan):
AttributeError: module '9e9df5ea-e2c5-11e8-b029-000f530ebd70' has no attribute 'BaseConan'
```

If I use the non-aliased base class it works fine:
```
base = python_requires('myBase/0.2@myUser/stable')
```

```
$ conan inspect . -a name
name: common
```

This is related to #3602 in that I would like to be able to avoid updating lots of recipes whenever the base class is updated.

**Comment by lasote** [comment]
Confirmed bug with a test here:

https://github.com/conan-io/conan/compare/develop...lasote:test/test_alias_python_requires?expand=1

**Comment by lasote** [comment]
1.10
