### ISSUE TITLE
[bug] SystemPackageManager install with a list of packages

### ISSUE THREAD

**Issue by dfleury2** [conan-io/conan#3921]
Hi,
Conan 1.9.0 on Debian with apt-get
Explanation:
In the system_requirements, I use the list arg form of the install method. Only the first item of the list is installed.

example:
[code]
        installer = SystemPackageTool()
        installer.install(["protobuf-compiler",  "libprotobuf-dev"], update=False)
[/code]

Hints: After looking at the code conans/client/tools/system_pm.py, methods _installed and _install_any returns after the first iteration of the loop on the list.

Woraround: uses the string arg form of the install method only

Regards,

**Comment by uilianries** [comment]
Yes, we use string instead of list, but we could update to support both.

**Comment by memsharded** [comment]
From the docs: https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-system-requirements

> https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-system-requirements

I know it is probably not the most intuitive behavior, but it is that way. It is NOT intended to install different packages, but to provide an array of alternative package names (protobuflib-dev, libprotobuf, etc), to account for small variations of distros or distro versions.

**Comment by dfleury2** [comment]
Ok, sorry.
for a non english-reader, reading " Installs the packages (could be a list or a string)" was not clear enough for me to see that the list was alternative name of the same packages.
A clarification in the doc will be welcome (just adding the wrod alternative :))

**Comment by memsharded** [comment]
You are right, submitted PR to clarify it: https://github.com/conan-io/docs/pull/943 Thanks for telling!
