### ISSUE TITLE
[Feature Request] AptTool --force-yes missing

### ISSUE THREAD

**Issue by dfleury2** [conan-io/conan#3923]
Hi,
conan 1.9.0, on Debian Jessie

While using SystemPackageTool with Apt, apt-get can fail due to -y used without --force-yes.

As seen in th conans/client/tools/system_pm.py file, it would be great to have a mecanism  like recommands_str to add '--force-yes' added to the apt-get command line.

Workaround,  as of today, I patch the conan source (in the docker), or install manually the package outside the conan workflow.

Regards,

**Comment by lasote** [comment]
From the apt docs:

```
--force-yes
Force yes; this is a dangerous option that will cause apt to continue without 
prompting if it is doing something potentially harmful. 
It should not be used except in very special situations. Using force-yes can potentially 
destroy your system! Configuration Item: APT::Get::force-yes. 
This is deprecated and replaced by --allow-downgrades, --allow-remove-essential, 
--allow-change-held-packages in 1.1.
```
That option is deprecated, what is your case (`--allow-downgrades, --allow-remove-essential, --allow-change-held-packages`)?  

If we introduce something to activate this, should be explicitly activated by the consumer user not from the recipe, that could be very dangerous for the consumer. So maybe something like an opt-in `CONAN_APT_INSTALL_ARGS`.

**Comment by dfleury2** [comment]
It's probably because the package I tried to installed cannot be authenticated ?

WARNING: The following packages cannot be authenticated!
  libwsutil7 libwiretap6 libwireshark-data libwscodecs1 libwireshark8

Not sure to know in which case I am...

**Comment by lasote** [comment]
Thanks.
