### ISSUE TITLE
colorama < 0.4.0

### ISSUE THREAD

**Issue by jnnnnn** [conan-io/conan#3924]
conan requires colorama <0.4.0, which was specified in the initial commits on 2015-12-15. 

colorama 0.4.0 was released on 2018-10-11. Several of our internal python packages use it, and install to the latest version. 

What is the reason for conan requiring colorama<0.4.0? Can this be changed?

Due to https://github.com/pypa/pip/issues/988 , we are having difficulty and may have to run conan in its own venv as a result (which is a bit of a maintenance headache).

**Comment by danimtb** [comment]
Hi @jnnnnn and thanks for the advice!

I have submitted a PR with Colorama < 0.5.0 an seems to be working fine. Hopefully it will be changed in next release and fix your headache 😄 

Cheers
