### ISSUE TITLE
`conan get` can't be used to download conan_package.tgz

### ISSUE THREAD

**Issue by zscgeek** [conan-io/conan#3925]
I am attempting to find some way to download the raw conan_package.tgz from the remote server but so far have not been able to figure out how to. I would like to be able to get a tarball of the full artifact and skip the process of unpacking locally and then taring everything back up. 

I thought `conan get`  would let me do this, but it does not seem to work. The resulting file is corrupt. 

```
zvision:dl rj$ conan get -raw -r sighthound -p 01edd76db324324234cca44ec466a9444c388 XXX/1.1.1.1@user/chanlle conan_package.tgz  > conan_package.tgz 
zvision:dl rj$ file conan_package.tgz 
conan_package.tgz: Applesoft BASIC program data, first line number 8
zvision:dl rj$ tar ztvf conan_package.tgz 
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
zvision:dl rj$ conan --version
Conan version 1.9.1
```

Is there another way to do this? Is there something wrong with this command? 

Thanks! 

To help us debug your issue please explain:

- [ X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ X ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @zscgeek 

I think because the .tgz is an storage abstraction over the package contents, and ``conan get`` operates on the package contents, once they are decompressed from the .tgz. So the .tgz is by implementation, transparent to the packages. They are temporarily stored within the package, to be cached for consecutive uploads, for example, but that might change, we might change the location, use a different compression, or not using compression at all.

**Comment by lasote** [comment]
It is a bug, we are doing two things wrong (in order to output a binary file to stdout):

1. `decode_text` of the downloaded contents
2. Conversion to `bytes`

In this branch there is a possible fix (not tested nor complete, but working):

https://github.com/conan-io/conan/compare/develop...lasote:feature/raw_downloads?expand=1

**Comment by lasote** [comment]
Hi, I tried to solve this but in python3 is quite difficult. You cannot write bytes to `stdout` unless you reopen it as a binary stream. I'm not saying it cannot be done but it is not easy. I would recommend calling directly the artifactory rest api (or conan_server) to download the files.

**Comment by jgsogo** [comment]
Hi! As you can see in the link provided by @lasote we have been doing some trials towards your request, but find it quite difficult to implement in py3.

Maybe we are not understanding your requirement... can you explain to us your use case? Why do you need the tarball? What are you doing with it?

Thanks

**Comment by zscgeek** [comment]
The usecase is trying to grab the raw archive of a package. Right now if you `conan install` a package you would have to do a bunch of output parsing to figure out where in the `~/.conan/` folder it's 
been unpacked to and then re-archive it. For our use cases I want to just raw download the package contents to consume in other deployment tools. 

Sure I can write a `deploy()` method for a specific conan file, but really would like something generic to be able to grab the archive of any package and then zip it back up. For a large package this is a lot of time. The `conan_package.tgz` file looked like exactly what we needed.  

Note that we don't need it written to stdout. In fact that kind of makes it more complex. Would be able to be great to say to download it to somewhere in the FS.

**Comment by jgsogo** [comment]
From the point of view of Conan, the `tgz` files are supposed to be transparent to the end user, they are just a convenient way of handling files for packages. Let's enumerate the alternatives:
 1. Work on `conan get`: try to honour the `--raw` argument for stdout, or provide a different argument to save it to a file. First one is hard for py2/3 as lasote pointed above, second option may be considered.
 1. Work on `conan download`: provide an argument to override the local path. But you will need to zip the package again, as the workflow of Conan will be to unzip it.
 1. Add a [hook](https://docs.conan.io/en/latest/extending/hooks.html) to work with the files that are actually uploaded to the remote. I don't know right now if this hook is available, but it should be easy to add.
 1. Use Conan to get the package ID, but use the server API to retrieve the file from it.

I think these are all the options we can think about for your use case. I will really appreciate feedback about each of them (ping @conan-io/barbarians).

**Comment by memsharded** [comment]
> The usecase is trying to grab the raw archive of a package. 

Still, the use case is a bit unknown for us. Getting the .tgz of, lets say, package 0123123124423423423423524532234 for a given library, doesn't seem very useful. If you only have exactly one platform/binary, then no big deal, but if you are supporting different platforms, architectures, compilers, then you would have a bunch of those, and doing something manually with them seems at least very tedious (there is a conaninfo.txt inside them, which can be inspected to know about the configuration, but needs to be done). Furthermore, the information provided by the ``conanfile.py`` recipe, which can contain information for consumers, e.g. in the ``package_info()`` method, won't be accessible from those packaged .tgz.

If you want to backup, then there might be other better ways to do it. Also, using the Artifactory API would automatically achieve what you want, have you consider it? Thanks for the feedback.
