### ISSUE TITLE
package_id and binaries built against different versions of a dependency due to requires and (transitive) build_requires selecting different versions

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#3927]
A discussion started in slack with :
> Am I wrong to expect that package versions I list in requires would be the initial values (and thus override transitive dependencies) for package I list in build_requires? Or is it not doing so a bug?
> basically I require liba/1.1@..., and build_depend on a libb that also requires liba, except (being a little older) it depends on liba/1.0. But it would be compatible with 1.1 (and would even be the same package_id due to semver_mode), so it uses the existing binaries in the cache
> However, conan ends up selection liba/1.1 for the requires and liba/1.0 for the build_requires, and including both in conanbuildinfo.txt
> But in conanbuildinfo.cmake CONAN_LIBA_ROOT points to liba/1.0 (probably just that the build_requires came second and overwrote the requires)? and the combined variables like CONAN_CMAKE_MODULE_PATH lists them both
> I didn't think conan was ever supposed to use multiple versions of a package for a ConanFile's requirements (obviously build_requires for different packages that all need to be built can vary, as can the subtrees beneath different ConanFile instances if you use private=True)
> <sub>[View in Slack](https://cpplang.slack.com/archives/C41CWV9HA/p1541800355824400)</sub>

@memsharded replied with
>  I need to go to sleep now, but quick summary; `build_requires` are independent and isolated from other requirements. As they are private by definition to the package, they are an independent graph, not affected by normal requirements at all
In fact that part of the graph is only computed when it is necessary to build from sources, otherwise, it doesn't exist at all
They can be overriden from the `profile` build-requires, but not affected by other packages build-requires
> <sub>[View in Slack](https://cpplang.slack.com/archives/C41CWV9HA/p1541806161845200/)</sub>

I've put together a little toy example at https://gist.github.com/puetzk/a6f2e77eb6dd048e7a6859e2cbb015fa. 

It creates two versions (1.0 and 1.1) of the package `required`, a package `build_required` that requires  `required/1.0` but uses the default semver_mode (so the resulting package is also usable with 1.1), then packages a consumer that requires `required/1.1` (in full_package_mode) and build_requires `build_required/1.0` (no effect on package_id). Unlike my the real use-case where I hit this, for simplicity none of these packages have any other settings/options/etc or actually compile anything.

The resulting package folder for `consumer\1.0\bug\example\{package,build}\bc8a3d667adf8e711799cf7f90fc07ce754dab64` seems quite confused: 

The conanbuildinfo.txt shows the transitive build_requires from overwrite the direct requires from `consumer` (though a few lines show *both* versions in listed)

```
[builddirs]
C:/Users/xxxxx/.conan/data/build_required/1.0/bug/example/package/9b0c6ba4d3e4e40842c29eeb745a61dff36964a0/
C:/Users/xxxxx/.conan/data/required/1.1/bug/example/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/
C:/Users/xxxxx/.conan/data/required/1.0/bug/example/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/
...
[rootpath_required]
C:/Users/xxxxx/.conan/data/required/1.0/bug/example/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
[builddirs_required]
C:/Users/xxxxx/.conan/data/required/1.0/bug/example/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/
```

conanbuildinfo.cmake is similar

conaninfo.txt shows that the package_id was computed based on the requires as expected, and this binary claims to correspond (only) to `required/1.1`

```
[requires]
    required/1.1@bug/example:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
```

Yet the required.cpp_info.txt I generated in consumer's build method (serializing deps_cpp_info['required'] to show what it would have actually been compiled against) is `required/1.0` as in the conanbuildinfo.txt

    "rootpath": "C:\\Users\\xxxxx\\.conan\\data\\required\\1.0\\bug\\example\\package\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",

So this package is **not** what it claims to be; dependencies within `build_required` that `consumer` might not even have been aware existed overwrote the consumer.

It really seems here like the build_requires should start as a copy of the requires and add to that, to mirror the way self.deps_*_info will combine the two. Private requirements can be added that are not public, but I can't envision where you'd want to claim one requirement publically and actually build against use something completely different. 

The colliding definitions in deps_cpp_info (and thus generators) is similar to #3295, though that issue didn't mention the complication where this results in binaries that don't match their package_id.

conan 1.9.1, python 3.7.0, Windows 7 x64

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by DoDoENT** [comment]
This seems to be related to #3949

**Comment by memsharded** [comment]
Closing this ticket as outdated, the ``package_id`` new modes in Conan 2 changed this completely.

Please don't hesitate to create new tickets for any further question, thanks!
