### ISSUE TITLE
"ERROR_MIGRATION" use case hides any useful error reporting

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#3928]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I'm working through my own issues with my CI environment, so I'm sure the root cause of me running into this problem is my own doing, but I wanted to at least point this out:

in `main()` of `command.py` is the following code:
```py
try:
    conan_api, client_cache, user_io = Conan.factory()
except ConanException:  # Error migrating
    sys.exit(ERROR_MIGRATION)
```

I happened to hit a `ConanException` and it was very difficult to pinpoint why. Here's a complete log of stdout/stderr from my Docker terminal where I was experiencing the issue:

```sh
root@8b7b6c334dbc:/home/redlionci/tcAgentHome/work/2f796c76b146d2a9# conan
root@8b7b6c334dbc:/home/redlionci/tcAgentHome/work/2f796c76b146d2a9# conan --version
root@8b7b6c334dbc:/home/redlionci/tcAgentHome/work/2f796c76b146d2a9#
```

Yea... there was no output whatsoever. The exit code was 2, which is how I narrowed it down to `ERROR_MIGRATION`. I then removed the try-catch so that the exception would bubble up and give me something useful:

```
root@8b7b6c334dbc:/home/redlionci/tcAgentHome/work/2f796c76b146d2a9# conan
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 14, in <module>
    run()
  File "/usr/local/bin/conan", line 11, in run
    load_entry_point('conan==1.9.1', 'console_scripts', 'conan')()
  File "/usr/local/lib/python2.7/dist-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 1549, in main
    conan_api, client_cache, user_io = Conan.factory()
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 215, in factory
    hook_manager)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 165, in instance_remote_manager
    localdb = LocalDB(client_cache.localdb)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/store/localdb.py", line 25, in __init__
    raise ConanException('Could not connect to local cache', e)
conans.errors.ConanException: ('Could not connect to local cache', OperationalError('unable to open database file',))
```

Yay! _Now_ I have something to work with! Now I have something to fix.

So... maybe this try-catch could be updated with a little more verbosity?

**Comment by memsharded** [comment]
Fixed in 2.0:
```
        except Exception as e:
            ConanOutput().error(str(e))
            raise ConanMigrationError(e)
```
Probably it is fixed in 1.X too, closing, thanks!
