### ISSUE TITLE
AutoToolsBuildEnvironment should use run_environment=True on macOS

### ISSUE THREAD

**Issue by theirix** [conan-io/conan#3929]
Calling configure scripts for packages with shared dependencies on macOS is broken.

There are two ways (except the rpath) described in the [official documentation](https://docs.conan.io/en/latest/howtos/manage_shared_libraries/env_vars.html?highlight=run_environment#using-shared-libraries-from-dependencies):
1) using `self.run(..., run_environment=True)` works well because it prepends a shell call with a `DYLD_LIBRARY_PATH=foobar`.
2. `RunEnvironment` helper.

Only first way works for complex configure scripts because the env is lost when `configure` spawns new subshells for conftest.

Therefore we cannot use `AutoToolsBuildEnvironment` helper which solely uses `RunEnvironment`. Build helper is very useful and has complicated logic for constructing `configure` and `make` calls. Replacing helper calls with plain `self.run` in recipes is almost impossible.

I propose to add `run_environment=True` parameter to `self._conanfile.run` calls inside a autoconf helper so the `DYLD_LIBRARY_PATH` is properly prepended to the command. It should not break existing recipes because a autoconf helper already calls `RunEnvironment` helper.

More manual solution is to allow to pass additional arguments to `self._conanfile.run` like a `win_bash` so the recipe author can specify run_environment parameter.

I can make a PR if we will agree on solution.

Example: check the bug https://github.com/bincrafters/community/issues/524

Environment: conan 1.8.4 and macOS 10.13 with SIP feature enabled.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I just recall a thing that I bet is the origin of the issue. 

OSX blocks `DYLD_LIBRARY_PATH` when the process to be run is ["protected" by the system](https://superuser.com/questions/1049689/which-folders-are-affected-by-system-integrity-protection), for example, the `bash` script is in a protected folder.

So, if you run:

```DYLIB_LIBRARY_PATH="x" bash -c 'mycommand'```  mycommand won't get the env var.

But if you run:

```bash -c 'DYLIB_LIBRARY_PATH="x"  mycommand'```  mycommand will get the env var (if it is not in a protected directory, for example, at the user home)

So, I think that is the reason it is working with the `run_environment=True` but I suspect it has nothing to do with the configure launching subprocesses, or maybe yes, but I doubt the configure is launching the subprocesses prepending the env var.

About https://github.com/bincrafters/community/issues/524, do you have more info about the fail or which sub-command is not getting the env var...?

**Comment by theirix** [comment]
You are exactly right and I am very sorry for the false issue. I have mistaken a call to a helper which sets CPPFLAGS and other variables with a `self.run` call that doesn't set them so the latter call doesn't link to OpenSSL at all. Regarding the DYLD problem - yes, I checked that even a simple shell script call have DYLD_LIBRARY_PATH stripped out. Autoconf script (as a shell script) doesn't even bother to set this variable for `conftest` calls and it will fail.

So my proposed solution won't work as well as RunEnvironment. The only way to fix this problem is to copy dylibs from dependencies like in `https://github.com/bincrafters/conan-libevent/blob/stable/2.1.8/conanfile.py#L62`. Maybe it should be automated by some method in tools module?

**Comment by theirix** [comment]
So I wrote a context manager that copies shared libraries from deps to the build directory where `configure` is run. It is safe enough to use inside a `AutoToolsBuildEnvironment` helper or inside a package. Code: https://github.com/bincrafters/conan-libcurl/blob/stable/7.61.1/conanfile.py#L12

**Comment by theirix** [comment]
Previously I thought that `import` is installation-time only, maybe I was confused by the `import` section in `conanfile.txt`. Looks like the `import` method does the same as the helper and it solves the problem perfectly.

The only thing is needed is to remember to insert `import` methods to the conanfiles when they have a shared library dependency.

**Comment by lasote** [comment]
> The only thing is needed is to remember to insert import methods to the conanfiles when they have a shared library dependency.

Only if the shared dependency is needed for building (build_require?)

**Comment by theirix** [comment]
Yes, it's needed only if dependency have `shared=True` and it's macOS. Anyway the following command will copy dylibs if they are present so no need to check manually all dependencies for shared option (transitively in a general case):
```python
def imports(self):
    self.copy("*.dylib*", dst=self.source_subfolder, keep_path=False)
```

Sorry, I don't understand what is about build_require.

**Comment by lasote** [comment]
Ah, yes, sorry, forget my last comment.

**Comment by theirix** [comment]
Tried the `imports` for two packages (libcurl and libevent) with shared OpenSSL deps and it works well. So the combination of the `imports` method and ```with tools.environment_append(RunEnvironment(self).vars):``` solves the original problem for both Linux and macOS.

At last maybe we should add a hint about this into [official documentation](https://docs.conan.io/en/latest/howtos/manage_shared_libraries/env_vars.html?highlight=run_environment#using-shared-libraries-from-dependencies) about shared libraries?

**Comment by danimtb** [comment]
@theirix actually that same section of the documentation also talks about imports. Feel free to open a PR to the docs if you'd like to add any improvement. Thanks!
