### ISSUE TITLE
conan install should have a --add option for adding the dep into the conanfile.txt

### ISSUE THREAD

**Issue by kindlychung** [conan-io/conan#3932]
conan version: 1.9.0
os: ubuntu 18.10

For example, I should be able to `conan install --add docopt/0.6.2@conan/stable -build docopt`, as a result of which, docopt should be installed in ~/.conan and my conanfile.txt should have:

```
[requires]
docopt/0.6.2@conan/stable
```

**Comment by kindlychung** [comment]
both npm and cargo have this feature.

**Comment by lasote** [comment]
We would need to limit it to `conanfile.txt`. You can use also a `conanfile.py` as a consumer, but adding there the requirement would be very complex and error-prone.

**Comment by memsharded** [comment]
Not worth it, as not possible in conanfile.py, would be very limited to conanfile.txt, just to avoid editing a file.
