### ISSUE TITLE
[question] Corrupt package build successfully, but is deleted

### ISSUE THREAD

**Issue by ratouney** [conan-io/conan#3933]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

___

Conan Version : 1.9.1

I'm currently trying to compile a project with the SFML lib on Windows after making it work on Linux. Now the problem I've come across is that when using `conan install . --build=missing` on my repository, it tells me that the bzip2 package is corrupted and is then removed...

> Configuration:
> [settings]
> os=Windows
> os_build=Windows
> arch=x86_64
> arch_build=x86_64
> compiler=Visual Studio
> compiler.version=15
> build_type=Release
> [options]
> [build_requires]
> [env]
> 
> bzip2/1.0.6@conan/stable: WARN: Package is corrupted, removing folder: C:\Users\Jean Pignouf\.conan\data\bzip2\1.0.6\conan\stable\package\8a0bcbacb81e70681519ccb3c3ee2c7cfc86b7ed
> PROJECT: Installing C:\Users\Jean Pignouf\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\ratouney\CPP_rtype_2018\sourgeEngine\conanfile.txt
> Requirements
>     bzip2/1.0.6@conan/stable from 'conan-center' - Cache
>     freetype/2.9.0@bincrafters/stable from 'conan-center' - Cache
>     libpng/1.6.34@bincrafters/stable from 'conan-center' - Cache
>     sfml/2.5.1@bincrafters/stable from 'bincrafters-public-conan' - Cache
>     stb/20180214@conan/stable from 'conan-center' - Cache
>     zlib/1.2.11@conan/stable from 'conan-center' - Cache
> Packages
>     bzip2/1.0.6@conan/stable:8a0bcbacb81e70681519ccb3c3ee2c7cfc86b7ed - Missing
>     freetype/2.9.0@bincrafters/stable:ead1b5a1fd92444812a38e44d77368ec20c3ac24 - Download
>     libpng/1.6.34@bincrafters/stable:93a82349c31917d2d674d22065c7a9ef9f380c8e - Download
>     sfml/2.5.1@bincrafters/stable:65630cc3a86ea14b9fb66d98eb266efe6321fbd0 - Download
>     stb/20180214@conan/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
>     zlib/1.2.11@conan/stable:970e773c5651dc2560f86200a4ea56c23f568ff9 - Download
> 
> bzip2/1.0.6@conan/stable: WARN: Can't find a 'bzip2/1.0.6@conan/stable' package for the specified settings, options and dependencies:
> - Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=15, os=Windows
> - Options: fPIC=True, shared=True
> - Dependencies:
> - Package ID: 8a0bcbacb81e70681519ccb3c3ee2c7cfc86b7ed
> 
> ERROR: Missing prebuilt package for 'bzip2/1.0.6@conan/stable'
> Try to build it from sources with "--build bzip2"
> Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

Now when trying to build bzip2 from source, I'm getting an error about a missing library at linkage after it successfully built it : 
>       (Link target) ->
>        LINK : fatal error LNK1181: cannot open input file 'lib\bz2.lib' [C:\Users\Jean Pignouf\.conan\data\bzip2\1.0.6\conan\stable\build\8a0bcbacb81e70681519ccb3c3ee2c7cfc86b7ed\bzip2-1.0.6\_build\bzip2.vcxp
>       roj]

Also, when I tried to manually install it from the given bintray using ` conan install bzip2/1.0.6@conan/stable`, the build is successfull.

Now why does conan detects the package as corrupted when the build is obviously working (or doesn't seem to output any errors) ? Is there any way to disable the automatic removal of corrupted packages ?

I have tried clearing my .conan folder and it didn't help (which is what most issues recommended). I don't know if I'm making some kind of beginners mistake or the problems lies directly with my dependencies configuration.

[CMakeLists.txt](https://github.com/conan-io/conan/files/2572786/CMakeLists.txt)
[conanfile.txt](https://github.com/conan-io/conan/files/2572787/conanfile.txt)

**Comment by uilianries** [comment]
Hi @ratouney !

Seems we don't have that configuration available:

![bzip2/1.0.6@conan/stable](https://screenshotscdn.firefoxusercontent.com/images/f53a4747-cfde-4f71-8fcf-06ab9335b246.png)

BTW the best place to open an issue related to Conan packages is https://github.com/conan-community/community/issues.

I'm going to check bzip2 and include your configuration.

**Comment by uilianries** [comment]
@ratouney bzip2 is available and updated. Please, try it again and feedback!

![bzip2/1.0.6@conan/stable](https://screenshotscdn.firefoxusercontent.com/images/a3c546c9-3bb8-4844-96b9-69b51cf959ba.png)

**Comment by lasote** [comment]
Please report if still something is wrong. Thanks!
