### ISSUE TITLE
[workspace][question] add_custom_target duplicate

### ISSUE THREAD

**Issue by dfleury2** [conan-io/conan#3934]
Conan 1.9.1, Debian.

Hi,
I am trying to use the experimental workspace feature (to avoid an export-pkg which use a cmake.install... so it doubles the configure and compilation).
After creating a conanws.yml with some of my projects, I successfully launch the conan install command which detect the project outside of the local cache.
A problem arise when I launch the cmake command, I got duplicate target error on add_custom_target used on each of my projects. These are targets for tests or packaging (tests, test, export-pkg), or for benchmarking (benchmark).
So, in this case do I do something wrong or workspace can hardly be used due to duplicate target names ? (I am not sure how to disable CMP0002)
Regards,

**Comment by ytimenkov** [comment]
I could suggest using distinct names for each test.

To have a common name for running you may either use `add_test` or just wrap into some macro which checks for presence of `test` target and adds it if missing, and then adds real test as a dependency.

Similar effect as if your packages are just subfolders. Similar to "install" or "all" targets.

**Comment by dfleury2** [comment]
It seems that the conan team works on a new implementation of the workspace. I will wait to see if it answers this issue.
