### ISSUE TITLE
Meson build helper: add test() and install() methods

### ISSUE THREAD

**Issue by matlo607** [conan-io/conan#3935]
Hello,
I created recently a recipe using [Meson](https://docs.conan.io/en/latest/reference/build_helpers/meson.html) and I discovered that the methods `test()` and `install()` are not available alike [CMake helper](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html).
What would you think about adding them to Meson build helper ?

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.

**Comment by lasote** [comment]
Yes, it would be nice. We haven't implemented them because the usage of the Meson build helper is low apparently.
