### ISSUE TITLE
Searching for "gtest" package in conan-center returns vague error message

### ISSUE THREAD

**Issue by tjwrona1992** [conan-io/conan#3937]
I just installed Conan yesterday and I'm trying to get a handle on the basics, but it seems I may have stumbled upon a bug searching for "gtest" packages in the "conan-center" remote. (Or it may just be a temporary service interruption).

`conan search gtest* --remote=conan-center`

`ERROR: {"message":"Oops. Looks like you've reached a dark spot."}. [Remote: conan-center]`

From the looks of the error message it seems like it isn't a message that the developers of Conan expected users to see because it doesn't give any indication of why it is happening or what to do to fix it.

Additional information:
-Conan version: 1.9.1
-Operating system: Windows 10 64-bit

**Comment by lasote** [comment]
Thanks for reporting. That is a bintray bug, we will try to figure out what is happening with the Bintray team.

**Comment by uilianries** [comment]
on the last time that I saw this kind of error, after waiting some hours the link was fixed magically.

related issue: https://github.com/conan-io/conan/issues/3916

It's not exactly same error, but when searching for gtest on bincrafters remote it works fine.

**Comment by danimtb** [comment]
This was fixed by the Bintray team and it is working now:

```
$ conan search gtest* --remote=conan-center
Existing package recipes:

gtest/1.7.0@bincrafters/stable
gtest/1.8.0@bincrafters/stable
gtest/1.8.1@bincrafters/stable
```

Please reopen again if needed or report in a new issue
