### ISSUE TITLE
"$HOME/.conan/bin" for binary deployment

### ISSUE THREAD

**Issue by kindlychung** [conan-io/conan#3938]
This convention would make it much easier for distributing binary packages. Golang has `go/bin`, Rust has `.cargo/bin`.

**Comment by kindlychung** [comment]
I am using the following code to make it work that way:

```py
from pathlib import Path
import os

homedir = Path.home()
conan_dir = os.path.join(homedir, ".conan")
conan_bin_dir = os.path.join(conan_dir, "bin")
if not os.path.exists(conan_bin_dir):
    os.mkdir(conan_bin_dir)
#...
def deploy(self):
    self.copy("*", src="bin", dst=conan_bin_dir)
```

**Comment by uilianries** [comment]
how to organize multiple outputs on same directory?

**Comment by kindlychung** [comment]
you mean multiple binaries? just copy all of them, i think.

**Comment by memsharded** [comment]
Hi @kindlychung 

It is not possible to define it as the unique output binary directory, for example, it is totally possible to have 2 different binaries for cmake for 2 different versions, lets say 3.1 and 3.9. If they are deployed to the same folder, they will collide and one would overwrite the other.

But I see the value of having a default directory, that could be easily added to the system PATH, given some checks are done, and maybe warnings or errors are printed.

I have created a "deploy" project to gather all feedback and issues related to this need.

**Comment by memsharded** [comment]
Conan 2.0 implement deployers to do whatever deployment task is desired
