### ISSUE TITLE
Removing one package asks about removing another package specified in short_paths.conf

### ISSUE THREAD

**Issue by arnemertz** [conan-io/conan#394]
Today when I tried to remove a package from my machine, conan asked me if I wanted to remove another, unrelated package:

```
$ conan remove nlJson/2.0.1@arnemertz/testing
Are you sure you want to delete from 'Boost/1.60.0@lasote/stable' (yes/no): no
Are you sure you want to delete from 'nlJson/2.0.1@arnemertz/testing' (yes/no): yes
```

I have a bunch of other packages installed. The only thing that is different for boost is that I have installed it elsewhere, i.e. this might be another short_paths issue:

```
$ cat ~/.conan/short_paths.conf 
Boost/1.60.0@lasote/stable: /conan-boost
```

**Comment by memsharded** [comment]
We are almost done with a totally new solution for the short_paths issue, so hopefully this will go away with it. Let's check it again when 0.11 is released. Thanks for reporting.

**Comment by Blubbz0r** [comment]
I was experiencing the same issue (see #369). However, it didn't get to me back then that the short_paths.conf was the culprit.

**Comment by memsharded** [comment]
The new solution has just passed CI, everything is green: https://github.com/conan-io/conan/pull/392

If you check it, it will just require to add ``short_paths=True`` to the package conanfile, no conf files, so it shouldn't mess at all with the remove functionality. Thanks @Blubbz0r for telling.

**Comment by memsharded** [comment]
Conan 0.11 has been released with a new solution to the windows path length limit: http://docs.conan.io/en/latest/reference/conanfile.html#windows-path-length-limit

Just add ``short_paths=True`` to the conanfile.py.

The short_paths.conf is no longer used, so this issue should be gone. Please upgrade to conan 0.11 and re-open if necessary. Thank you!
