### ISSUE TITLE
Bintray can't handle package names with different cases and same versions

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#3942]
We have a `Qt` recipe at Bincrafters. We want to rename it to `qt`, but leave the existing `Qt` in peace to not interrupt existing consumers.

So we tried an upload with the new lower case name and the rest unchanged. 
Bintray always throws a 500 error for `qt` uploads when the version we try to upload exists in `Qt`.
E.g.

https://api.bintray.com/conan/bincrafters/public-conan/v1/files/bincrafters/qt/5.11.2/stable/export/conanmanifest.txt
https://api.bintray.com/conan/bincrafters/public-conan/v1/files/bincrafters/qt/5.9/stable/export/conanmanifest.txt

It does NOT happen for URLs which would happen in a `qt` upload with a version which does NOT exist in `Qt`:  (expected 404)
E.g. 
https://api.bintray.com/conan/bincrafters/public-conan/v1/files/bincrafters/qt/5.12.0/stable/export/conanmanifest.txt

same if we change the branch to something which does NOT exists in `Qt` uploads:
https://api.bintray.com/conan/bincrafters/public-conan/v1/files/bincrafters/qt/5.11.1/testing/export/conanmanifest.txt

Thanks to @ericLemanissier for noticing this.

**Comment by lasote** [comment]
Thanks. Reporting to Bintray team.

**Comment by Croydon** [comment]
LGTM.

Thanks!
