### ISSUE TITLE
[question] How to generate different package id with the same settings but different Linux distro?

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3946]
For example, given Linux distros of Ubuntu and RHEL 7 with all the `settings`, `options` and `requires` values identical, is there a way of generating a different package id for the different distros?

**Comment by lasote** [comment]
You have to introduce a new setting in the `settings.yml` that model the distribution.  You can also distribute the `settings.yml`, profiles and any other conan config using the `conan config install` feature.

**Comment by lasote** [comment]
Yes, or it could be modeled as a subsetting of "Linux" if it fits better. That way you don't need to modify the recipes to support it.

**Comment by keithrob91** [comment]
Understood. Thank you.
