### ISSUE TITLE
upload recipe with huge sources leads to "Connection aborted"

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#3948]
Hi there,
I have some trouble with uploading a recipe with sources to a remove conan server.

situation
---------
I am trying to upload prebuilt files to a remove repository (same Network/LAN).
To achieve this I use the "exports_sources" attribute. Currently the source has a size of 1.58 GB.

When exporting to my local repository everything works fine. But when I try to upload the recipe conan prints an error message after some time and aborts the upload.

command line
---------------
`conan upload --remote=SERVER --force --confirm --check MY_REFERENCE`

error message:
---------------
> Error uploading file: conan_sources.tgz, '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))'
ERROR: Execute upload again to retry upload the failed files: conan_sources.tgz.

![image](https://user-images.githubusercontent.com/8578342/48622582-7fef4e80-e9a7-11e8-8413-ba61084eecf7.png)

**Comment by jgsogo** [comment]
Hi @Johnnyxy,

Which server are you using? Is it Artifactory? Also, please take a look at the timeout configured in `conan.conf` (variable `requests_timeout`).

**Comment by Johnnyxy** [comment]
Hi there,
sorry for the late answer.

I am using a local conan server. The default "requests_timeout" setting in my client's conan.conf is "1200".

I had a talk with the server administrator and he said the server's tmp folder (linux) was full. As conan seems to upload to the tmp folder in the first this could explain that behaviour. I will keep you updated if it is fixed after providing more space on the server.



Best regards

**Comment by Johnnyxy** [comment]
It seems to be the case that there was not enough space on the server.

**Comment by memsharded** [comment]
Great, thanks for following up!
