### ISSUE TITLE
conan inspect should not fail on missing attribute

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#3953]
Conan 1.9.1

I'm trying to get list of direct dependencies for the recipe and when I run `conan inspect -a build_requires` on a recipe without `build_requires` it just fails because `AttributeError` is fatal.

I think this behavior is inconvenient as I don't know in advance which attributes are present and if I specify multiple custom attributes, whole command fails.

I suggest that missing attributes should be translated to missing keys in the resulting dictionary (effectively ignoring `AttributeError` in `ConanAPIV1.inspect()` instead of converting it to `ConanException`).

**Comment by lasote** [comment]
Yes, I agree. Returning a missing key should be enough information to know that the attribute is not there. About #3913, the `porcelain` option I suggested, it could return a blank line if the key is not there,  but it would be the same as a "blank" string result. Anyway, you have always the `json` option to get better info.

**Comment by ytimenkov** [comment]
I use json, but exception comes from API, before any serialization takes place.
However I didn't think about ordinary stdout...

**Comment by memsharded** [comment]
fixed, will be in next 1.17
