### ISSUE TITLE
How are conanfile.txt options handled in CMakeFile.txt

### ISSUE THREAD

**Issue by HerbertKoelman** [conan-io/conan#3960]
Hello,

I'm trying to see how I can use conan options, so I've added some options to my `conanfile.txt` to see what happens:
```
[generators]
cmake

[options]
*:Poco:shared=False
```
I suppose to set/enable this option I need to run:
```
$ conan install .. -o *:Poco:shared=True
Now, how do I get the option value in my CMakeLists.txt script ?
```

What I can't figure out is how I can get access to this option in my CMakeFiles.txt script !?

----
```
$ conan --version
Conan version 1.9.1
$ uname -a
Linux at-herbert 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jgsogo** [comment]
Hi!

Your option string should be `Poco:shared` not `*:Poco:shared`, as it is said in [the docs](https://docs.conan.io/en/latest/reference/conanfile_txt.html#options): it should be `package_name:option_name=value`.

Also, options affect to the package they refer to (`package_name`), although you can use the special _package_name_ `*` to refer to all of them ([check docs here](https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#options)).

Said that, Conan options are described and handled inside Conan recipes. It has to be the recipe the one that passes that value to CMake so you can use it in your `CMakeLists.txt`. For example, you can check recipe for [OpenEXR](https://github.com/conan-community/conan-openexr/blob/9a00b68e64991dab4fb4b5ede2648909877ef9da/conanfile.py#L47) where there are several options that are being passed to CMake in the `build` method:

```python
class OpenEXRConan(ConanFile):
    name = "openexr"
    ...
    options = {"shared": [True, False], "namespace_versioning": [True, False], "fPIC": [True, False]}
    default_options = "shared=False", "namespace_versioning=True", "fPIC=True"
    ...
    def build(self):
        # parallel builds are disabled due to the random issue: 'toFloat.h': No such file or directory
        cmake = CMake(self, parallel=self.settings.os != 'Windows')
        cmake.definitions["OPENEXR_BUILD_PYTHON_LIBS"] = False
        cmake.definitions["OPENEXR_BUILD_SHARED"] = self.options.shared
        cmake.definitions["OPENEXR_BUILD_STATIC"] = not bool(self.options.shared)
        cmake.definitions["OPENEXR_NAMESPACE_VERSIONING"] = self.options.namespace_versioning
        cmake.definitions["OPENEXR_NAMESPACE_VERSIONING"] = self.options.namespace_versioning
        ...
```

Let me know if this answer your issue.

Thanks!

**Comment by HerbertKoelman** [comment]
Is this correct that options can only be used through a conanfile.py ?

If I run `conan install conanfil.py -o namespace_versioning=False` can I get access to this option in my CMakeLists.txt file ?

**Comment by HerbertKoelman** [comment]
Ok, I think I got it.

Thank you for your help
