### ISSUE TITLE
Commas in version-ranges make input invalid (breaking)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3964]
I'm trying things here (https://semver.npmjs.com/) and in fact, commas are never used (we remove them in our code). Anyway, we should keep the possibility of having one comma (it is documented), but remove it for Conan 2.0.

For <2.0, it would be enough to remove those commas from the documentation: https://docs.conan.io/en/latest/mastering/version_ranges.html

_Originally posted by @jgsogo in https://github.com/conan-io/conan/pull/3898/comment#issuecomment-440251031_

**Comment by jgsogo** [comment]
Without commas, the string within the `[...]` will be the straightforward input to node-semver package (take into account, the proposed options `strict/loose` and `include_prerelease` in #3898).

Are you agree with it, @conan-io/barbarians?

1. Remove from docs those commas
2. Remove in Conan 2.0 the replacement of commas by blanks

**Comment by climblinne** [comment]
Updated documentation by removing commas.

**Comment by climblinne** [comment]
Look into https://github.com/conan-io/conan/pull/3898/commits/13defc000919d699716128b990a0c7b04054b5d6. Would this message be fine?

**Comment by memsharded** [comment]
Version ranges in ``develop2`` no longer use comma to separate conditions (they still use commas to separate the ``include-prerelease`` part)
