### ISSUE TITLE
Improve use of conan in CMake

### ISSUE THREAD

**Issue by allanleal** [conan-io/conan#3967]
This is a proposal for an additional cmake function that combines the two commands:

~~~
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
~~~

Maybe 

~~~
conda_default_basic_setup()
~~~
or even simpler:
~~~
conda_init()
~~~

This change would require updating [this part](https://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html#global-variables-approach) of the documentation.

**Comment by danimtb** [comment]
Hi @allanleal 

Coudl you elaborate your proposal a little bit more?

How are you going to call a function if you doesn't import it before?
Is this related to Conda pacakge manager anyhow?

Sorry but I don't get it 😥

**Comment by allanleal** [comment]
> How are you going to call a function if you doesn't import it before?

True. In this case, something like:

~~~
include(Conan)
conan_basic_setup()
~~~

This would require a `Conan.cmake` module file which could become in the future one of the standard cmake modules as listed here:

https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html

It is just that (personally) I find:

~~~
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
~~~

hard to memorize and use in every new project. The above alternative would be more convenient and less verbose.

**Comment by memsharded** [comment]
But it doesn't work that way. The fact that ``${CMAKE_BINARY_DIR}`` is there, is totally relevant.

You can install dependencies, for several different configurations (architectures, platforms, compilers), each one in a different build folder, each one will generate its own and different ``conanbuildinfo.cmake``.

It is not just a common module for all Conan instances, it is a generated file with information from dependencies, for a given ``conan install`` with a specific configuration.

**Comment by allanleal** [comment]
@memsharded The `conanbuildinfo.cmake` file will continue to exist - the only thing that changes is the creation of a cmake module `Conan.cmake` that only contains these two lines:

~~~
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
~~~

So that in our `CMakeLists.txt` file we can simply write:

~~~
include(Conan)
~~~

and this is enough.

**Comment by danimtb** [comment]
Can you share with us that *Conan.cmake* module so we can take a look? It could be interesting.

However, I see your proposal less explicit for too little additional value but maybe we are missing something. Definetly the integration with build systems is something in our roadmap as well as improving the development experience and lower any possible friction with other tools.

Thanks again!

**Comment by allanleal** [comment]
> Can you share with us that Conan.cmake module so we can take a look? It could be interesting.

The file has only those two lines: `include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)` and 
`conan_basic_setup()`.

> still have the problem to locate the "Conan.cmake" file (where is it? where will it be generated?)

It is either a standard cmake module (ships with future versions of CMake), or locally available (found by specifying its path in `CMAKE_MODULE_PATH` variable). This is not a generated file.

> and a huge lack of generality that normal usage requires.

The available arguments to method `conan_basic_setup` are `TARGETS`, `NO_OUTPUT_DIRS`, and `KEEP_RPATHS` as shown [here](https://docs.conan.io/en/latest/reference/generators/cmake.html#conan-basic-setup). 

In this case, the more customized use of `conan_basic_setup`:
~~~
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS KEEP_RPATHS)
~~~
could be replaced with:
~~~
option(CONAN_SETUP_WITH_TARGETS ON)
option(CONAN_SETUP_WITH_KEEP_RPATHS ON)
include(Conan)
~~~

The `Conan.cmake` module would then need to check for those option variables to call `conan_basic_setup` more appropriately.

Honestly, this is not a critical change, but a marginal simplification in case the simplest and default use of Conan is needed, in which case just a `include(Conan)` call is needed, instead of a more verbose form that contains the path to `conanbuildinfo.cmake` in the binary dir `CMAKE_BINARY_DIR`.

**Comment by memsharded** [comment]
Ok, understood, thanks very much for all the feedback.

> It is either a standard cmake module (ships with future versions of CMake), or locally available (found by specifying its path in CMAKE_MODULE_PATH variable). This is not a generated file.

This is a problem by itself. Shipping it with CMake is outside of our control, nothing that something we can do. Having it locally available, means that Conan needs to actually generate it and put it somewhere, just not in the current project. It is still not clear where. Please note that having different embedded CMake executables inside conan packages is also a thing, and Conan adding files to the global CMake installation is not nice at all.

The options like ``option(CONAN_SETUP_WITH_TARGETS ON)`` are yet another level of indirection around the ``conan_basic_setup()`` arguments, but at the global scope. If new functionality is implemented in ``conan_basic_setup()``, the "system" Conan.cmake would become obsolete until the next CMake release.

> Honestly, this is not a critical change, but a marginal simplification in case the simplest and default use of Conan is needed, in which case just a include(Conan)

Yes, so as marginal, it seems it would be too much of a trouble and complexity for the provide value.
There will be future improvements in the integration with CMake, but at this point better not to add this extra cost.

Thanks very much for your suggestion and the discussion!
