### ISSUE TITLE
Specify location of the test package from inside 'conanfile.py'

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3975]
> @jgsogo @memsharded Yes, being able to specify the location of the test package from inside `conanfile.py` would be awesome! And not just for this specific use case either, I would think.

_Originally posted by @ttencate in https://github.com/conan-io/conan/issues/3635#issuecomment-425481786_

**Comment by memsharded** [comment]
I am not sure about this feature @jgsogo. The ``test_package`` is totally external to the recipe so far, independent. 

As a consumer of the package, it is not possible to load it first (the package conanfile.py is not loaded first, but the consumer test_package is!), it would be a chicken and egg problem. There are plans to untangle this in conan 2.0, but as today, this feature is not-implementable without breaking user recipes.

There is the ``--test-folder`` command line argument that can address the required folder easily. And maybe it is needed to fix it to use the relative path from ``conanfile.py``, and not the current path, we could check that.

**Comment by memsharded** [comment]
Yes, it might make sense, but I am thinking it could be breaking too....

**Comment by jgsogo** [comment]
If we are afraid that this change can break existing behavior, then we are not going to do it for `v1.*`. Either close or assign it to `v2.*'.

**Comment by memsharded** [comment]
Closing as not planned
