### ISSUE TITLE
Auto detection of Linux distribution

### ISSUE THREAD

**Issue by djeverett** [conan-io/conan#3978]
If you add support for Linux distributions as suggested in  #1093, the is is required to supply the `os.distro` setting.  This really should not be needed as Conan could easily determine it using `platform.linux_distribution()` or the `distro` package.  All the means for supplying it currently as unsatisfactory:

* profiles:  these are stored under a user-specific directory, so every time another developer starts working on a host they have to manually copy the profile they need.  There is also the needless specifying of a profile to every `conan install` call for something that can be detected by Conan. 
* passing with `--settings os.distro=`: again, needless typing and error-prone as user has to make sure the setting matches the _arbitrary_ strings in settings.yml
* setting the `CONAN_ENV_OS_DISTRO` environment variable: this could be done for all users by adding to a script in `/etc/profile.d/`, so an improvement - but this does not work for Jenkins jobs as they use _non-interactive_ SSH.

Suggestion:
* support a system-wide `conan.conf`, e.g. `/etc/conan/conan.conf`, which is separate to the cache (still stored in `~/.conan`)
* support a setting in `conan.conf` for enabling Linux distribution support
* auto detect the distribution that you are building on

**Comment by lasote** [comment]
About the profiles suggestion. You could include a base profile in all the profiles and distribute them all with `conan config install`. But yes, each developer would need to configure the base profile with the distro.

> auto detect the distribution that you are building on

We would need first to model in the default `settings.yml` the distribution but even though we couldn't auto detect it for the default profile becase we would be breaking the default profile for people that doesn't want to model the distro.

About the `conan.conf`, I don't think a setting is a right place to do adjust a setting.

We could think about a new [`hook`](https://docs.conan.io/en/latest/reference/hooks.html) to run it before each conan execution. It could receive some paths to the local cache etc so you could verify that your base profile containing the distro is there or create it dynamically using the `platform` module. But you would need to `conan config install` in every new environment to get the hook and the distro base profile.

**Comment by djeverett** [comment]
The hook idea sounds interesting.

An alternative is to use a named profile, but support having configuration in a shared area.  So, `/etc/conan/` could contain `profiles/`, `settings.yml`, `conan.conf`, and remotes info - but `$HOME/.conan/data` is still used for the cache.  This would avoid having to install profiles and settings for _every_ user, whilst avoiding the potential concurrency issues of having a shared cache.

I am not sure I understand why `settings.yml` would be broken for those who do not want to model the distro.  All you need is a Boolean configuration telling Conan whether or not to ignore `os.distro` in `settings.yml`.

**Comment by lasote** [comment]
> All you need is a Boolean configuration telling Conan whether or not to ignore os.distro in settings.yml.

Of course everything is doable, but introducing switchs for something generic and flexible as a setting is probably not the best design idea.
