### ISSUE TITLE
cmake-multi : Package built for Debug and Release in separate folder

### ISSUE THREAD

**Issue by jano42** [conan-io/conan#3982]
I have a simple project with conan using a single dep which is boost.

````
[requires]
boost/1.68.0@conan/stable

[options]
boost:shared=False
boost:without_atomic=False
boost:without_chrono=False
boost:without_container=True
boost:without_context=True
boost:without_contract=True
boost:without_coroutine=True
boost:without_date_time=False
boost:without_exception=True
boost:without_fiber=True
boost:without_filesystem=False
boost:without_graph=True
boost:without_graph_parallel=True
boost:without_iostreams=True
boost:without_locale=True
boost:without_log=True
boost:without_math=True
boost:without_mpi=True
boost:without_program_options=True
boost:without_python=True
boost:without_random=True
boost:without_regex=False
boost:without_serialization=True
boost:without_signals=True
boost:without_stacktrace=True
boost:without_system=True
boost:without_test=False
boost:without_thread=False
boost:without_timer=True
boost:without_type_erasure=True
boost:without_wave=True
boost:skip_lib_rename=True

[generators]
cmake_multi
````

I run conan with those lines 

````
conan install --build missing -s compiler.runtime=MT -s arch=x86 -s build_type=Debug ..
conan install --build missing -s compiler.runtime=MT -s arch=x86 -s build_type=Release ..
````

As I'm requesting a specific build, for each one the boost libs must be build.

The problem is that each build introduce a whole copy of boost source and build it.
So I have two similar folders (~1Gb and 62k files) , one is containing debug lib, the other one release ones.

But building the debug et release can be easily done in the same source folder. (before using conan, I build the lib manually)

It would be nice to have a single build folder (for the same options, just build_type has changed).

**Comment by lasote** [comment]
If the Boost library allows that, it could be done but in the boost recipe by using the [N configs (1 build) -> N packages](https://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-build-n-packages) approach. 
Maybe you can open an issue in the [repository issue tracker](https://github.com/conan-community/community/issues) of the boost package.
