### ISSUE TITLE
Bintray does not use the latest README file

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#3983]
It seems that Bintray use some snapshot of a README file and does not update to the latest one (even after 2 months). See the following issue:
https://github.com/mpusz/conan-google-benchmark/issues/1

**Comment by SongBase** [comment]
I have also noticed this.  I have synced the README.md file from GitHub but all I see is an old version.

**Comment by memsharded** [comment]
Bintray UI is deprecated and will be closed. https://conan.io/center/ ConanCenter is the entry point for this.
