### ISSUE TITLE
CONAN_COMPILER and CONAN_LIBCXX not defined in conanbuildinfo.cmake

### ISSUE THREAD

**Issue by tareqsiraj** [conan-io/conan#3990]
I am trying to compile with clang (provided via a devtool recipe) on Linux and noticed that in `conanbuildinfo.cmake` `conan_basic_setup(TARGETS)` -> `conan_set_libcxx()` doesn't update the `CMAKE_CXX_FLAGS` to include `-stdlib=libc++`. After a bit of digging, it looks like the checks in `conan_set_libcxx()` doesn't have `CONAN_COMPILER` and `CONAN_LIBCXX` defined.

From the docs, it looks like these are defined for the CMake conan helpers for the recipe, but `conan install` generated `conanbuildinfo.cmake` seems to rely on them. For now I'm setting these two before calling `conan_basic_setup(TARGETS)`:
```
set(CONAN_COMPILER ${CONAN_SETTINGS_COMPILER})
set(CONAN_LIBCXX ${CONAN_SETTINGS_COMPILER_LIBCXX})
conan_basic_setup(TARGETS)
```

Is this a bug or there are better ways I could solve this?

## Configuration
* conan 1.9.2
* Ubuntu Linux 18.04.1 LTS in a Docker container
* clang-7 from release.llvm.org

## Reproduce
* Use the following Dockerfile for the environment
```
FROM ubuntu:bionic

WORKDIR /conan

RUN apt update \
    && apt install -y --no-install-recommends zsh ninja-build cmake build-essential python3 python3-pip python3-setuptools neovim curl

RUN apt clean autoclean
RUN apt autoremove -y

RUN pip3 install wheel && pip3 install conan==1.9

RUN mkdir -p /tmp/conan \
    && cd /tmp/conan \
    && curl https://raw.githubusercontent.com/tareqsiraj/sync_files/master/conan/clang-7.0.0/conanfile.py > conanfile.py \
    && conan create . Clang/7.0.0@tareqsiraj/stable

CMD ["zsh"]
```
* Create a simple cmake project with the following `conanfile.txt`
```
[requires]
Clang/7.0.0@tareqsiraj/stable

[generators]
virtualenv
cmake
```
* Run
```bash
cd build
conan install .. -s compiler.libcxx=libc++ -s compiler=clang
source activate.sh
cmake -G Ninja ..
ninja -v
source deactivate.sh
```
* The compile command lines should include `-stdlib=libc++`

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Yes, this is a very well known issue related with the build helpers and the generators. We are planning to improve the situation for Conan 2.0. The general idea would be:

 - The generators will create a file (the current conanbuildinfo.cmake) with ONLY code about the dependencies.
- The build helpers will generate a new file that could be included also, that will contain information about the build, including the libcxx. Even without running the `build()`  method, that could contain a build helper invocation, a base file with the build information will be generated. 

So, you would probably need to pass to `cmake` the build file as a toolchain or by any other mechanism (still we are thinking what is the best way to do it).

**Comment by tareqsiraj** [comment]
Thanks for confirming this, for now I am getting around this with mentioned workaround and seems to be working. We will keep an eye out for changes in conan 2.x.

**Comment by Manu343726** [comment]
Note that even having a `conaninfo.txt` file generated wil all install settings, `compiler.libcxx` may be missing since `conanbuildinfo.cmake` is not parsing it (As it does with `compiler` and `compiler.version`). I working on a PR to include the parsing of the libcxx setting in the conan_get_compiler() function of `conanbuildinfo.cmake`.

**Comment by memsharded** [comment]
This integration and the ``cmake`` generator is being removed in 2.0 in favor of ``CMakeToolchain``. So this issue is no longer valid, please check ``CMakeToolchain`` (already available in latest Conan 1.X and in Conan 2.0-alpha1), closing it.
