### ISSUE TITLE
[question] Document conaninfo.txt better

### ISSUE THREAD

**Issue by dzolee** [conan-io/conan#3992]
Please consider writing more documentation about conaninfo.txt. If you search yourself, it is mentioned here and there but it could save beginners some time in the future. Here are two questions in context.

Q1
I received the warning from the generated conanbuildinfo.cmake that conaninfo.txt does not exist. I checked the CMake file but I did not realize WHERE it should be. I created conaninfo.txt files, where I effectively duplicated my packaging settings (os = .... etc) , reexported the packages and now there are no warnings. Dilemma: is it OK or have I just hidden the warning? Please extend the docs on the packaging workflow with conaninfo.txt

Q2
I have to package binaries for different platforms, OSes, etc. The package job itself does not compile anything, the machine where it runs does not even have to have any compilers installed. Conan should be enough. I set every required settings (os, compiler etc) for the package on the command line.
I created a skeleton conaninfo.txt which will be taken in the package export step and I just "echo" the current settings to the file, like:

echo build_type=Debug >> conaninfo.txt

then I export and upload the usual way. The uploaded package contains the conaninfo.txt I have crafted plus more infos. So it will be processed by Conan as well.

Question: 
Is this OK? Is seems to work fine so I am happy with it.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
About the Q1, thanks, for that is better to open the issue in the [docs](https://github.com/conan-io/docs) repository.
About the Q2, It doesn't sound good, do you know the `conan export-pkg`  command?

**Comment by dzolee** [comment]
Thanks for the feedback. I am absolutely happy about the way 1.9.1 works, I mean Q2:

I use a conaninfo.txt as a "shortcut" for not having to pass every setting separately to export-pkg.

The reason why I want this shortcut: the export job can run on a different OS than the package is for. So I would have to specify a "profile" (I don't want that now, I would need to deploy "profiles" as well), or I would have to specify every single setting using -s.

I can just take a conaninfo.txt which matches the OS/bitness/build_type and run export-pkg .... the result is a wonderful package with the desired settings.

Customer happy, software runs fine, what more do you want? :)

Thanks again for the feedback.
