### ISSUE TITLE
Portable Mac-client

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#3993]
Hello there,

first of all I would like to make you aware of what a blessing it is, that you distribute binaries in the installers for Linux and Windows and that the installation is "portable", that is, it can be copied around and will keep working fine.
I managed to "deploy" this wonderful tool of yours to dozens of development machines with little effort. Noone had to install or configure anything, Conan was just there and running fine.
So please keep it "portable"! 👍 

But, on Mac, the situation is different. The installation from brew does not contain binaries, it is all scripts. Moreover, it contains a Python3.7 as "submarine". I mean, in the Conan folder, there is Python3.7 and the Conan scripts all need it. There are some paths wired to the scripts (or symlinks, does not matter), so it cannot be copied around.

We only have a few Mac machines so I installed Conan manually wherever I needed to, but it would be a big plus if the Mac installation also contained binaries like Windows and Linux, or it would be portable like the others.

Thanks in advance

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
> So please keep it "portable"! 👍

Sure, we don't plan to remove the conan installers :)

Regarding the OSX installation from brew, it is not under our control, unfortunately we can't do that.

But, have you realized that there is the ``pyinstaller.py`` file at the root of the repo.? That is the tool we use to generate the embedded conan executables, and it runs in OSX too. Building a pkg from it, or just distributing it to the machines shouldn't be much difficult. Please have a look and report, thanks!

**Comment by dzolee** [comment]
Thanks for the feedback. Having an installer is nice. But what I meant, the installation is now "portable", that is, I can copy the installed files around from one PC to another PC and it keeps working.

Thank you for the OSX tip. I have to deal with only a few boxes, so installing from brew was OK. If time permits, I will check.

**Comment by memsharded** [comment]
OSX executable available in https://conan.io/downloads, closing this
