### ISSUE TITLE
Small typo in the help text of "conan new"

### ISSUE THREAD

**Issue by dzolee** [conan-io/conan#3994]
To help us debug your issue please explain:

Check the screenshot please, I think there is a period and a space missing from the marked location. OS: Win10 x64, Conan 1.9.2

![grafik](https://user-images.githubusercontent.com/10893838/48970817-30e19300-f011-11e8-87ec-003e6f20ca36.png)

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @dzolee 
You are right there is a missing dot and space there. Would you like to submit a pull request yourself to fix it? That would be an easy contribution :)

**Comment by dzolee** [comment]
yes, I will do it monday.

**Comment by memsharded** [comment]
Closed in https://github.com/conan-io/conan/pull/3999
