### ISSUE TITLE
version ranges resolve prereleases

### ISSUE THREAD

**Issue by yos55** [conan-io/conan#3997]
We are working on integration of conan package management into our pipeline.

Our conan package are store in Artifactory.

The convention of our version numbers looks like this:

> Minor.Major.Patch-BuildVerison

As we know, for consuming the latest version, need to use 

> [> Minor.Major.Patch]

 into the conanfile.py.

The only way we were able to get a latest version from versions like our convention is to write it like this: 

> [> Minor.Major.Patch-0]

But our problem happens in situations like the example below:

Let's say these are the version numbers of a package that we try to consume it's latest version:

> 1.2.3-1

> 1.2.3-2

> 1.2.3-3

if we write in our conanfile.py 
> [>1.2.3-0] 
 
we will get the 

> 1.2.3-3 

as well.

But if we upload the version 

> 1.2.4-1 

of thus package (only update the Patch number), and we leave the conanfile.py as is - we will still get the 

> 1.2.3-3

 not the 

> 1.2.4-1

 as accepted. 

Please help us know what is the best way to get what we want.

Thanks.

**Comment by memsharded** [comment]
Hi @yos55 

You are hitting the behavior that by semver specification, pre-releases are not resolved, unless explicitly opted-in. Your ``BuildVersion`` is being specified by a "-" which the semver specification uses for "pre-releases". For build metadata, the "+" can be used, but that is discarded by range resolution.

There is some ongoing work to add a "prereleases" opt-in in version ranges, you can follow ongoing discussion and effort in:
- PR: https://github.com/conan-io/conan/pull/3898
- Issue: https://github.com/conan-io/conan/issues/3798

Check them, I think that they are the feature you are looking for. If so, please tell and close this issue. Thanks!

**Comment by memsharded** [comment]
I would also recommend changing the issue title to something like "version ranges resolve prereleases". Current issue title: "consuming conan latest version" would seem that you want to install the latest conan (the client tool) version.

**Comment by memsharded** [comment]
Hi @yos55 

Did you check in my above comments about PR: #3898 and Issue: #3798? They could be the behavior you are looking for. Please have a look, thanks!

**Comment by memsharded** [comment]
PR #3898 has been merged, and will be released in 1.10.
I think this issue is solved now with those changes, so it can be closed. Please re-open or comment otherwise, thanks.
