### ISSUE TITLE
Installation/build failed libalsa1.1.5

### ISSUE THREAD

**Issue by BenoitPingris** [conan-io/conan#3998]
Hello,

I use conan for a SFML project and when I'm installing it, conan installs libalsa for depencies purposes.
However in this installation, it crashes with the following error:
```bash
libalsa/1.1.5@conan/stable: ERROR: Package 'b80d46004713aa37d6a90b42e2a326a056a237b5' build failed                                                    
libalsa/1.1.5@conan/stable: WARN: Build folder /home/benoit/.conan/data/libalsa/1.1.5/conan/stable/build/b80d46004713aa37d6a90b42e2a326a056a237b5     
ERROR: libalsa/1.1.5@conan/stable: Error in build() method, line 43
        self.run("make install")                                           
        ConanException: Error 512 while executing make install
```

If I scroll up in the conan logs I can see a lot of warnings and this error appears several times:

```
[...]
python.c:63:28: warning: passing argument 2 of ‘PyObject_GetAttr’ makes pointer from integer without a cast [-Wint-conversion]
  o = PyObject_GetAttr(obj, PyString_InternFromString(attr));
[...]
python.c: In function ‘pymelem_get_caps’:
python.c:461:9: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
  return PyInt_FromLong(pymelem->selem.caps)
[...]
python.c: In function ‘pymixer_dealloc’:
python.c:803:15: error: ‘struct pymixer’ has no member named ‘ob_type’; did you mean ‘ob_base’?
         self->ob_type->tp_free(self);
[...]
```
**Step to reproduce**

`mkdir build && cd build && conan install .. --build missing`

**My conanfile**

```
[requires]
sfml/2.5.1@bincrafters/stable
boost_asio/1.66.0@bincrafters/stable

[options]
sfml:shared=True
sfml:window=True
sfml:audio=True
sfml:network=True
sfml:graphics=True

[generators]
cmake

```

**What I tried so far**

Reinstall conan (pip3 uninstall then pip3 install)
Delete the ~/.conan/data and launch a conan install

I'm using :
- conan 1.9.2
- python 3.7.1
- gcc 8.2.1

 I'm on manjaro 17.1.2

<br>
<br>

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @BenoitPingris 

I have tested it in Ubuntu 18 with ``conan install libalsa/1.1.5@conan/stable --build=libalsa``, I guess that it will fail also in your platform, but if you could please run it, just to make sure, that would help.

I'd say that libalsa might fail to compile in your platform for some reason. You can see, using a ``conan get libalsa/1.1.5@conan/stable`` that the build of this package is relatively straight forward:

```python
def source(self):
        self.run("git clone git://git.alsa-project.org/alsa-lib.git")
        self.run("cd alsa-lib && git checkout v%s" % self.version)

    def build(self):
        ab = AutoToolsBuildEnvironment(self)
        with tools.environment_append(ab.vars):
            with tools.chdir(os.path.join(self.source_folder, "alsa-lib")):
                args = ["--enable-static=yes", "--enable-shared=no"] \
                    if not self.options.shared else ["--enable-static=no", "--enable-shared=yes"]
                python = "--disable-python" if self.options.disable_python else ""
                self.run("touch ltconfig")
                self.run("libtoolize --force --copy --automake")
                self.run("aclocal $ACLOCAL_FLAGS")
                self.run("autoheader")
                self.run("automake --foreign --copy --add-missing")
                self.run("touch depcomp")
                self.run("autoconf")
                if python:
                    args.append(python)
                args.append('--prefix=%s' % self.package_folder)
                ab.configure(args=args)
                self.run("make install")
```

Also, this issue seems no conan (the tool) related, but package specific, so please submit the issue to the issue tracker as specified by the package itself: https://bintray.com/conan-community/conan/libalsa:conan/1.1.5:stable, and close this one.

**Comment by BenoitPingris** [comment]
The `conan install libalsa/1.1.5@conan/stable --build=libalsa` also failed at the `make install` unofrtunately..
Thanks for the advice I'll close this issue quickly and post it to the link you post, hope they'll find what is going on ! :+1:
