### ISSUE TITLE
"conan install" fails in the root folder

### ISSUE THREAD

**Issue by dzolee** [conan-io/conan#4002]
The conan install command seems to fail if I am at the root folder (conan 1.9.1, Win7, x64, NTFS, the user is member of the local Administrators group).
I don't really understand this because when I am somewhere else, and not in the root folder, then conan will properly download and place the package to my "home" or "profile" folder, as expected.
So why does it try to write to the "current folder"?
![grafik](https://user-images.githubusercontent.com/10893838/49015570-c3a23f00-f183-11e8-97a4-09a8094884c5.png)

I gave it a try under Mac (10.13.6, conan 1.8.4) and I have a failure but with a different error code:
![grafik](https://user-images.githubusercontent.com/10893838/49015644-0b28cb00-f184-11e8-9e5d-2b5c0173b05d.png)

I think it is strange ... please consider some more error handling.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Bug confirmed in windows at `c:\`
Thanks for reporting.
