### ISSUE TITLE
[workspaces] support for virtualenv generator

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4009]
We are using CMake via the `cmake_installer` package as `build_requires` so in order to run `cmake` it has to be added to the `PATH` first which is usually done with the `virtualenv` generator.
With the workspaces setup, `conan install -g virtualenv` does not generate the respective `activate.*` scripts, neither in the "workspace build folder" nor in the respective package build folders.
I ended up adding the `virtualenv` generator to the generators attribute in the `conanfile.py` of our root package so the scripts are written to `<common parent dir>/myrootpackage/build/`.

Would it be possible to pass-on the generators specified on the command line to the packages and generate `activate.*` scripts in the "workspace build folder" which simply source/execute the respective script in the root package defined in the `conanws.yml`? This would be comfortable for the user and since the environments are inherited it should work fine.

Conan 1.8.2. under Windows

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I have added in the last commit of https://github.com/conan-io/conan/pull/4481, the possibility to define generators per package, and also for all workspace package, with the syntax:

```
            HelloB/0.1@lasote/stable:
                folder: B
                generators: [make, qmake]
            HelloC/0.1@lasote/stable:
                folder: C
            HelloA/0.1@lasote/stable:
                folder: A
                generators: visual_studio
            layout: layout
            generators: cmake
            generator: cmake
            root: HelloA/0.1@lasote/stable
```

It might change a little bit (the name of the meta-generator), but I think that would implement your suggestion.

**Comment by petermbauer** [comment]
Thank you!
