### ISSUE TITLE
source function is never triggered in out of source build

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#401]
Hy,

i'm trying to make my first out of source conan package. I use version 0.11 from conan on Windows 7 x64 on Python 3.4.  
My Problem is that my source function, where my git clone is will never be triggerd, so i'm always get an error in my build function.  
I've use the **new** command from conan  
`conan new MyLib/1.2.3@myusername/testing`  
to create a new conanfile in my current directory. Then i try  
`conan build`  
, but source never triggerd.

Is it the correct way to trigger it?

Thanks in advance
Tonka

**Comment by lasote** [comment]
The conan build method will only trigger the build method.
You need to export your recipe first ``conan export myusername/testing`` and then install it to trigger the whole installation process ``conan install MyLib/1.2.3@myusername/testing``

But **the best** way to prepare your first package is invoke the "conan new" command with "-t". It will create a test_package folder for you, just fill it with some code that tests your library (you can do it later) and execute ``conan test_package``command. It will automatically export your recipe to local repository and perform a conan install, and compile the example against your library.

Write here if you need more help!

**Comment by tonka3000** [comment]
Hey @lasote

i've now create a new package with  
`conan new -t MyTestLib/1.2.3@myuser/testing`  
and run  
`conan test_package`  
afterwards.

Everything works fine, but in the end i've got following error  
`ERROR: Error -1 while executing .\example`  
Why will example automatically be called?

I can see that there is an correct build in the *test_package/build* directory.

**Comment by lasote** [comment]
If you edit the test_package/conanfile.py you will see that there is a "test" method that it is calling to the example application. Why? because the test_package is intended to compile some example that reuses your library, so you can sure that people can link against your library writing an example application. Edit the example.cpp to use some of your library features.

    def test(self):
        os.chdir("bin")
        self.run(".%sexample" % os.sep)

**Comment by tonka3000** [comment]
ok. thx
