### ISSUE TITLE
virtualrunenv not adding correct libdirs to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by jandrewmc** [conan-io/conan#4014]
To help us debug your issue please explain:

virtualrunenv puts all the conanfile: 
`self.cpp_info.libdirs` 
into the LD_LIBRARY_PATH environment variable BUT it does not put the: 
`self.cpp_info.debug.libdirs`
or the:
`self.cpp_info.release.libdirs`

in my conanfile.py
```
    def package_info(self):
        self.cpp_info.libdirs = ['lib']
        self.cpp_info.debug.libdirs = ['lib/debug']
        self.cpp_info.release.libdirs = ['lib/release']
```

in the  activate_run.sh:
`LD_LIBRARY_PATH="<PATH_TO_LOCAL_CACHE>/lib"`

I was expecting that when i run:
`conan install . -s build_type=Debug`
that the activate_run.sh would be something like this:
``LD_LIBRARY_PATH="<PATH_TO_LOCAL_CACHE>/lib":"<PATH_TO_LOCAL_CACHE>/lib/debug"``

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).

- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
Centos 7
Conan 1.8.4
qmake

- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
This is not how generators work. They take information from dependencies and output that to a file, so they can be used by the consumer. If the dependency is multi-config package has both debug/release configurations in a multi-config package, then the generator (e.g. cmake) might output CONAN_CMAKE_LIBS, CONAN_CMAKE_LIBS_DEBUG, CONAN_CMAKE_LIBS_RELEASE, so the build system might be able to use and switch between them, without further using conan. Conan will not select one based on the settings, but the end user will.

The idea of a multi-configuration package is that once it is installed, you don't need to call ``conan install`` again with a different configuration to get a valid generated file. It could be argued that in the ``virtualrunenv`` generator there should be ``LD_LIBRARY_PATH_DEBUG`` and ``LD_LIBRARY_PATH_RELEASE`` variables, and then you can use them.

Besides that, there is the problem that there is no direct mapping between settings and/or options and multi-config information. Multi-config could be named:

```python
 def package_info(self):
        self.cpp_info.libdirs = ['lib']
        self.cpp_info.debug_x86.libdirs = ['lib/debug']
        self.cpp_info.release_x86.libdirs = ['lib/release']
        self.cpp_info.debug_x64.libdirs = ['lib/debug64']
        self.cpp_info.release_x64.libdirs = ['lib/release64']
```

The multi-config naming convention ``release_x86`` is something defined by the user. Could be ``dbg`` and ``rel``. It can be used for any purpose. All conan can do is to map them to variables in the generated files, but it is responsibility of the final consumer to use them. 

Multi-config packages should be used in very occasional exceptions, for most cases it is recommended to use single-config packages. Is there something in your case that you can't use single-config packages?

Please tell if the above makes sense, thanks!

**Comment by jandrewmc** [comment]
Yes the above makes perfect sense!  Thank you for your time!
