### ISSUE TITLE
finding out source directory when conanfile.py is in the sources

### ISSUE THREAD

**Issue by chuet-thermo** [conan-io/conan#4015]
I am trying to upgrade an old project from conan 0.30.3 to 1.X, and I am running in an issue.

In order to transition smoothly, I am trying to make the conanfile.py compatible with conan 1.X and conan 0.30.3.

The only issue is that the conanfile's `import` method was using self.conanfile_directory, as this project's output directory is located within the source dir, i.e.
project_root
  ->source/project.cxx
  -> output/project.exe
  -> CMakeLists.txt
  -> conanfile.py

the `import` function used to do a `self.copy(src="...", dst=self.conanfile_directory + "/output")` to copy dependent libraries (i.e. boost) to the `output` directory so that the project runs directly in its output directory.

I tried using `self.source_directory` but it is not available in the `import` method as far as I can tell.

I have multiple questions: 
* How can I perform this copy in 1.X ?
* is this method available in 0.30.3 ?

I realize that using the source directory as output directory is strange, but sadly I cannot change this right now.

Thanks

**Comment by lasote** [comment]
How are you building your project? `conan create`? or local methods: `conan build` + `conan imports` etc?

**Comment by chuet-thermo** [comment]
your question made me realize what was wrong.

We were using an old version of `conan.cmake`, where we could not specify the `INSTALL_FOLDER`.
I updated conan.cmake, specified the `INSTALL_FOLDER` to be the root source directory, and removing the `self.conanfile_directory` altogether now works, as the current working directory is the root source directory.

Sorry for the inconvenience, and thanks a lot for the help :)
