### ISSUE TITLE
Allow setting Conan Profile via Environment Variable

### ISSUE THREAD

**Issue by samielhini** [conan-io/conan#4017]
To help us debug your issue please explain:

Conan 1.9.2, Debian 9, Linaro 6.3.1
- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I would like to request the ability to set the Conan Profile via an Environment Variable.  That would be very helpful in cross compiling.

**Comment by uilianries** [comment]
https://docs.conan.io/en/latest/reference/env_vars.html#conan-default-profile-path

**Comment by jgsogo** [comment]
Thanks, @uilianries. 

Please, @samielhini, let us know if the env variable `CONAN_DEFAULT_PROFILE_PATH` is enough for your necessity so we can close this issue.

**Comment by samielhini** [comment]
My apologies. That works wonderfully. 

I must have assumed that meant the path to the profile directory and not the profile itself.
