### ISSUE TITLE
[question] header-only lib that needs local configuration

### ISSUE THREAD

**Issue by dzolee** [conan-io/conan#4020]
Hello there,

I have a library that we bought some time ago. It is header-only (although it contains tons of code, it is all packed in headers). There is no way to precompile any sensible parts of it. It remains header-only. As I understand, I can delete all settings from the recipe, because we are using the same lib on all OSes and platforms. And I will only have one package ID too.

But...

Reality is always different. The library needs a one-time configuration which must be done on the actual build computer. The configuration is done using CMake. The library has CMake scripts that will test for certain compiler bugs and produce a single header-file with some define-s. This header is then specific to the compiler used and must be included in the local compilation. The define-s in the header will instruct the library code to use "workarounds" for the detected compiler bugs.

So far, I could write a recipe, checkout the source in the source() method and build the library locally, where the build() step would just do the CMake configuration I mentioned above

But ...
I can have 32 and 64 bit products under Windows. And the 32-bit compiler has other bugs than the 64-bit one. So if I configure the library for 32-bit, it will work incorrectly under 64-bit. So I have to 

I don't want to duplicate packages, how do I solve this situation? Should I keep the bitness (arch) settings?

Thanks in advance

**Comment by uilianries** [comment]
Hi @dzolee!

Excellent question, the same situation happen when cmake generates the config version by [write_basic_package_version_file](https://cmake.org/cmake/help/v3.0/module/CMakePackageConfigHelpers.html).

I good example is [conan-parallelstl](https://github.com/conan-community/conan-parallelstl/blob/release/20181004/conanfile.py). To keep the same package_id we removed the cmake file and all defines were moved to `package_info`

**Comment by dzolee** [comment]
Thanks, I will have a look at the sample.

**Comment by jgsogo** [comment]
Hi @dzolee, did you try it? Does it fit your needs? We would be pleased to know more about your use case and to know if this solution (or the workaround) works for you. Thanks!

**Comment by dzolee** [comment]
Hey Boss, thanks for reminding me. I am in the process of creating packages for the dependencies of this little beast of a library. I think I can begin with the recipe only on Friday or next Monday.

I think I will try the following:
Don't generate binaries, In the source() step, I can checkout the sources. In the build() step I can check if the platform-specific, CMake-generated .h file already exists -> if yes, don't build. If not, run the CMake configuration and save the .h file.

If all else fails, I can still check in the pregenerated, platform-specific .h file (I did it before)

But I would love to write a build() recipe ... we'll see.

**Comment by dzolee** [comment]
OK... so far so good ... it seems to work, up to one thing:
can I use
` self.env_info`

in build() ? I get an error, env_info seems to be only accessible in package_info(). What if the build process expects an environment variable? Can  I not set it with env_info?

**Comment by memsharded** [comment]
``self.env_info`` is to define env-vars for consumers, so it doesn't make sense to modify it in the ``build()`` method. If the build process expects some env-var set from the consumer, conan is managing that already (otherwise it would be a bug maybe).

**Comment by dzolee** [comment]
Ah, that makes sense. Thanks.
