### ISSUE TITLE
Version attribute injected after scm attribute works?

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4026]
I was trying to simplify a header only library to the max, but if I can't use the `self.version`  or `version` in the scm feature. Is there a change we can get it? Is it a new symptom of the coordinates injection architecture?

```python
import os
from conans import ConanFile, tools
class PicojsonConan(ConanFile):
    scm = {"type": "git", "url": "https://github.com/kazuho/picojson.git", 
                "revision": "v%s" % version}

    def package(self):
        self.copy("*.h", "include")
```

I wanted to have the same recipe to run "conan create" with the full reference.

**Comment by niosHD** [comment]
Has this been closed due to lack of interest or have I missed the resolution?

**Comment by lasote** [comment]
Lack of interest, even for myself.

**Comment by niosHD** [comment]
Understood, thank you for the clarification!
