### ISSUE TITLE
scm get ignore files crashing

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4027]
By an unknown cause, the `excluded_files`  function (Conan 1.8.4) during the call to `git check-ignore` is raising a `FileNotFoundError`. Investigate when it can happen. Maybe the `self.folder`? Apparently calling manually it works. But anyway it would be better to just print a warning and ignore the failure, because this is only an optimization.

**Comment by michaelmaguire** [comment]
@michaelmaguire
