### ISSUE TITLE
Allow enabling a trace mode which dumps *every* configuration and profile filename used

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#4030]
This would help us in understanding issues we've noticed with ```C:\Users\<username>\.conan\conan.conf``` being apparently ignored, even though we verified Conan thinks ```C:\Users\<username>\.conan\data``` is clearly being used for package local cache

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ 1.8.4] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
It could be done adding DEBUG log entries. (CONAN_LOGGING_LEVEL=10 env var)
We should review the usage of the debug traces, currently, they are not printing useful information in many cases but lacking useful info like the used config files and so on.

**Comment by memsharded** [comment]
Closed by #4128, those traces might help. But please comment if extra traces are needed.
