### ISSUE TITLE
[question] "-b missing" covers the fact that the recipe is completely missing

### ISSUE THREAD

**Issue by dzolee** [conan-io/conan#4035]
Hi there,

I observed that Conan 1.9.1 (Linux and also Win) tries to locally build a package in case of a compiler version mismatch. It cannot succeed because there is no recipe. There is a conaninfo.py in the package but there is nor source() or build() there. Only package() and package_info().
The package contains precompiled binaries. Is this the expected behaviour? That "conan install" returns no error, but there's no local package?

The context ...
I have packages with compiler=gcc AND compiler.version=7.
One Linux developer box has the following default profile:

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

Please note: GCC 5.

I used a similar command line to fetch a package from the repo:
`conan install MyPackage/1.0@user/channel -b missing -s build_type=Release -s os=Linux -g cmake -if <the path...>
`
My mistake was, I have not added the compiler and the version. Conan has taken compiler.version=5 from the profile. OK.

But Conan started to building the package locally, using what recipe? If I deliberately specify a mismatching compiler version, it also tries to build, but the resulting local package is useless. It's empty, there is no recipe there. My problem with this is that I cannot detect the error, the install exit code is zero.

What does exactly happen in this case? Which recipe does Conan try to build? The created package folder does not give any useful hints, no python files there. If Conan took an existing package, I would see the conaninfo.py from that package, right? But there's no such file there.

You can reproduce it if:
-you have package(s) with specified compiler and compiler.version
-you request a package from remote where the compiler.version is "legal" according to settings.yml but there's NO package with that version in the remote
-you use -b missing

Please have a look guys ...

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @dzolee 

I am not sure I fully understand the issue. If some package binaries were created and uploaded to the server once, the recipe was also uploaded to the server. You cannot upload a compiled package binary without uploading the recipe too.

When you are installing that package, for that compiler, it first downloads the recipe, then evaluates it, compute the necessary binary ID, and then try to download the binary or built it from sources if there is no binary for those settings.

Please tell me if this clarify your question. Thanks!

**Comment by dzolee** [comment]
Mmmm.. thanks for the response. I will test some more, and maybe look into the Conan source to better understand reality vs. my intended workflow.
