### ISSUE TITLE
Conan.io search is down 502 bad gateway

### ISSUE THREAD

**Issue by catskul** [conan-io/conan#404]
![screenshot from 2016-08-10 00-32-26](https://cloud.githubusercontent.com/assets/375302/17541922/2794bce0-5e92-11e6-8883-106ca8654391.png)

Apparently "Bad Gateway"

```
Request URL:https://webapi.conan.io/v1/search?q=*
Request Method:GET
Status Code:502 Bad Gateway
Remote Address:188.166.34.211:443
Response Headers
view source
Connection:keep-alive
Content-Length:574
Content-Type:text/html
Date:Wed, 10 Aug 2016 04:33:42 GMT
Server:nginx/1.4.6 (Ubuntu)
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8,es;q=0.6
Authorization:Bearer *******************************
Connection:keep-alive
Host:webapi.conan.io
Origin:https://conan.io
Referer:https://conan.io/search
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Query String Parameters
view source
view URL encoded
q:*

```

**Comment by catskul** [comment]
BTW is this the right place to report bugs, make requests regarding the website? or is there a better place?

**Comment by memsharded** [comment]
Yes, yes, this is the right place, thanks for reporting. You can also tell us in twitter or email. But the general policy is that if it is something that can affect other users too, like this issue, a bug, a feature request... the best is to report it here, so other users know about it.

It should be working now, please try again. I have checked the systems, and everything is fine on our side, it seems that one of the external services we are using was down for a while.

Thanks very much for telling. I am closing the issue, but if it happens again, please reopen or create a new one. Cheers.
