### ISSUE TITLE
Installed package location for consumer build copy

### ISSUE THREAD

**Issue by ZenwalkerD** [conan-io/conan#4040]
To help us debug your issue please explain:

- [*] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [*] I've specified the Conan version, operating system version and any tool that can be relevant.
- [*] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
Conan version: 1.9.2
OS: Win 10

Hi, 
I have a particular scenario wherein i am packing some of the libraries and applications as Conan packages. The package is getting created and already been uploaded for artifactory. 
The consumer of my libs/apps are developers and Build environment.
For developers, they do not have any issues for consuming my libs into their application..

However, they have a problem wherein they have to build their product but include my library files (whatever structure i give) into their build path and bundle it later on to give for customers.

Apparently i tried to get the installed package location so that i can suggest the team to follow the steps:
1.	Before their build starts, download required CONAN package from Artifactory and install it in the build machine.
2.	Supposedly get the output files of the above installed package and copy to their local paths.
3.	Prepare setup of their own containing my packed files.

Problem, i do have any idea how can i achieve this problem. Please help.

**Comment by memsharded** [comment]
Hi @ZenwalkerD 

I think what you are looking for is the ``imports`` feature. It allows copying files from the packages, to the user folder, so they can be used there, zipped and redistributed. It is typically done for runtime files, like .dlls, .so, but can be done for others too. Please check:

- https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#imports (consumer conanfile.txt)
- https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports (consumer and package recipe conanfile.py)

**Comment by ZenwalkerD** [comment]
Hi @memsharded 
I have already looked into those links. Apparently it doesnt fit my scenario.
As i stated in my problem above, the consumer of my package does not have anything like conanfile.py in their product/application src tree. They just install it via connan install command. Then they would like to copy the build/xxxx/out/bin/* files to their own paths and ship it off to customers.

For this, they need to be able to get the installed path of my conan package say %users%/.conan/MyLib/stable/xxx../bin/.

**Comment by memsharded** [comment]
If they are going to install it with:

```bash
$ conan install yourpkg/version@user/channel
```

Then you can use the ``deploy()`` method, inside your ``yourpkg/version@user/channel`` recipe. It can copy files from itself, as well as from dependencies: https://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy

**Comment by ZenwalkerD** [comment]
@memsharded 
That almost suits my requirement, but only problem is "Where to copy" info is known to the build environment internals of the project team. As a package provider, i do not know where it should go and sit. Is it possible to provide that path information via CLI along with conan install command as u stated above? 
However, i can convey this message to the project team. Something better than noting.
Thanks alot.

**Comment by memsharded** [comment]
Yes, the argument ``-if INSTALL_FOLDER, --install-folder`` will tell conan where to install things, including the deployed/copied artifacts. If not provided it will use the current folder. 

It is also possible to abuse ``deploy()`` and code absolute paths in the ``deploy()`` method (typically conditioned on the platform). But this is only to directly install at the system level, not very usual.

**Comment by ZenwalkerD** [comment]
That solves my problem. Thanks @memsharded
