### ISSUE TITLE
Conan >=1.8 fails when called from SCons 2.4.1

### ISSUE THREAD

**Issue by alacasta** [conan-io/conan#4046]
# Description
It is not possible to use Conan in combination with SCons 2.4.1 (based on python2) from version 1.8.

## Possible cause
There is a known limitation on this and using the multiprocessing package (https://stackoverflow.com/questions/24453387/scons-attributeerror-builtin-function-or-method-object-has-no-attribute-disp) which is used by a new package (tqdm) needed by another feature introduced in such version.

## Use case
Users typically run 
```bash
conan install . 
```
of their dependencies for gathering dependencies as well as required generators. However, Integrating Conan in SCons is possible and provides solution for deps resolution and build process via 
```bash
scons
```

The complete use case may be more complex but, for the sake of simplicity and considering that a program from `src/hello.c` wants to be created and may have dependencies which are detailed at `conanfile.txt` using Conan format, a SConstruct file like follows is needed

```python
import os

# Import Conans
from conans.client.conan_api import ConanAPIV1 as conan_api
from conans import __version__ as conan_version

conan, _, _ = conan_api.factory()

build_directory = os.path.join(os.getcwd(), "build")
if not os.path.exists(build_directory):
    os.makedirs(build_directory)

src_directory = os.path.join(os.getcwd(), "src")
build_hello_directory = os.path.join(src_directory, "hello.c")

conanfile_path = os.path.join(os.getcwd(), "conanfile.txt")

conan.install(conanfile_path,\
        generators=["scons"],\
        install_folder=build_directory)


# SConstruct
env = Environment()

conan_flags = SConscript('{}/SConscript_conan'.format(build_directory))
flags = conan_flags["conan"]
env.MergeFlags(flags)

VariantDir(build_directory, src_directory)
hello = Program(build_hello_directory)
```

## Problem/Limitation
Some minor versions ago (1.8), a new feature for displaying the progress of an unzip process was included (#3545). The mechanism proposed was based on `tqdm`which, internally uses `multiprocessing`. 

Therefore, if running the previously described SConscript with `system_config_1`, the results is
```bash
scons: Reading SConscript files ...
/home/lacastaa/.local/lib/python2.7/site-package/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
AttributeError: 'builtin_function_or_method' object has no attribute 'dispatch':
  File "/media/sf_E_DRIVE/dev/scons_conan/SConstruct", line 4:
    from conans.client.conan_api import ConanAPIV1 as conan_api
  File "/home/lacastaa/.local/lib/python2.7/site-packages/conans/client/conan_api.py", line 21:
    from conans.client.remote_manager import RemoteManager
  File "/home/lacastaa/.local/lib/python2.7/site-packages/conans/client/remote_manager.py", line 32:
    from conans.util import progress_bar
  File "/home/lacastaa/.local/lib/python2.7/site-packages/conans/util/progress_bar.py", line 3:
    from tqdm import tqdm
  File "/home/lacastaa/.local/lib/python2.7/site-packages/tqdm/__init__.py", line 1:
    from ._tqdm import tqdm
  File "/home/lacastaa/.local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 75:
    mp_lock = mp.RLock()  # multiprocessing lock
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 182:
    from multiprocessing.synchronize import RLock
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 48:
    from multiprocessing.forking import assert_spawning, Popen
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 60:
    class ForkingPickler(Pickler):
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 61:
    dispatch = Pickler.dispatch.copy()
``` 

In turn, when running with system_config_2, the output is as follows

```bash
scons: Reading SConscript files ...
PROJECT: Installing /media/sf_E_DRIVE/dev/scons_conan/conanfile.txt
Requirements
Packages

PROJECT: Generator scons created SConscript_conan
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
scons: done reading SConscript files.
scons: Building targets ...
gcc -o src/hello.o -c src/hello.c
gcc -o src/hello src/hello.o
scons: done building targets.
```

## Useful Links
- Complete example of the defined use case: https://github.com/alacasta/conan_scons
- The next workaround has been proved useful when needing to import multiprocessing at SCons. However, this cannot be applied from the client side (SCons) since is called from Conan: https://stackoverflow.com/questions/24453387/scons-attributeerror-builtin-function-or-method-object-has-no-attribute-disp/25674103#25674103 

### system_config_1
- OS: "Ubuntu 16.04.5 LTS"
- Conan: 1.9.2
- Python: Python 2.7.12
- SCons 2.4.1

### system_config_2
- OS: "Ubuntu 16.04.5 LTS"
- Conan: 1.7.4
- Python: Python 2.7.12
- SCons 2.4.1

# Possible solution
Limiting the use of this feature, perhaps enabling a mechanism to be possible to disable it at `RemoteManager` so that the import operation is performed only when the feature is really wanted. 

# Checlist
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
From what I understand from the links, it seems that it is an SCons issue, that decided to rename the pickle module. It also seems that setting ``SCONS_HORRIBLE_REGRESSION_TEST_HACK``, should work. Could you please check if it setting that environment variable it works? Thanks

**Comment by alacasta** [comment]
> From what I understand from the links, it seems that it is an SCons issue, that decided to rename the pickle module. 

Thanks @memsharded. Of course, i do not consider a problem of Conan, but SCons', Moreover, I'd consider this an opportunity to get both working 👍 

> It also seems that setting `SCONS_HORRIBLE_REGRESSION_TEST_HACK`, should work. Could you please check if it setting that environment variable it works? Thanks

I think I already checked that this works, but is not a 'clean' solution imo. As SCons user, i don't like this workaround but either like to enforce (others) to set this flag.

**Comment by memsharded** [comment]
Ok, thanks for testing it!

The problem with this issue is that the solution that you suggest:

>  enabling a mechanism to be possible to disable it at RemoteManager so that the import operation is performed only when the feature is really wanted.

That basically means to define an environment variable to disable the TQDM output at user will, something like:
```
export CONAN_DISABLE_TQDM_CAUSE_SCONS_FAILS=True
```

Ok, I exaggerated the naming a bit :) :) :) 
But now, we are at the same place, users still need to define something to avoid that failure. I don't see any other possible solution, any suggestion?

**Comment by alacasta** [comment]
Unfortunatelly, the idea i got does not fit with the current architecture. It was based on modifying `RemoteManager` but i just realized that client is not really designed to be manipulated from the caller but using env vars (now, i see your point with the CONAN_DISABLE_TQDM_CAUSE_SCONS_FAILS :) ) 

As far as i see, i don't see any option from Conans' side. I think that is absolutely about SCons. 

Thank you very much for @memsharded. You can close the ticket from my side. 

[TL;DR]
My preferred solution was something like increasing the RemoteManager API with a setter for enabling the possibility of silenting the progress bar as follows

```python
   def set_show_unzip_progress_bar(display_progress_bar=True)
   """ 
   Enable/Disable the progress bar when unzipping archives as prescribed by
   display_progress_bar (True by default)
   """
   self._display_progress_bar = display_progress_bar
``` 
(keep in mind initialization in Class `__init__`)
Consequently, i'd increase also

```python
def unzip_and_get_files(files, destination_dir, tgz_name, output, display_progress_bar=True):
....
   # set display_progress_bar argument
   uncompress_file(tgz_file, destination_dir, output=output, display_progress_bar=display_progress_bar)
```
as well as
```python
def uncompress_file(files, destination_dir, tgz_name, output, display_progress_bar):
```
which I'd redisign with the original implementation if display_progress_bar is not needed
```python
if(display_progress_bar):
   # Keep the current implementation but importing here the corresponding dependencies
   from conans.util import progress_bar
   with progress_bar.open_binary(src_path, desc="Decompressing %s" % os.path.basename(src_path),
                                output=output) as file_handler:
            tar_extract(file_handler, dest_folder)
else:
    # Fallback solution to not enforce using progress bar if not needed.
    with open(src_path, 'rb') as file_handler:
            tar_extract(file_handler, dest_folder)
```

**Comment by memsharded** [comment]
> but i just realized that client is not really designed to be manipulated from the caller but using env vars

yes, exactly, the current python api is just the programmatic equivalent to the command line, but it is not possible to cleanly access internals (of course with python it is always possible, you probably could just monkey-patch the affected conan code from the caller, but that is still ugly). 

We are gradually introducing more extension and configuration points, but that level of access is still far away, as  it requires a huge stability and documentation effort, and that affects development speed too...

So closing the issue by now, thanks for all the feedback, and do not hesitate to further comment if necessary. Cheers!
