### ISSUE TITLE
real support for rpath - post install package modification step

### ISSUE THREAD

**Issue by spavlovskyi** [conan-io/conan#4048]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

this doesn't concern windows, because you can't have nice things on windows. i'll talk about linux, but i believe same functionality is possible on macos with different names.

problem description:
when dynamic linker loads library, it searches its dependencies in its rpath list, not in some higher level rpath lists(this means fixing rpath in executable will not help unless executable itself is linked with library's dependencies,which is not always right thing to do (see `--as-needed`) ). so properly linked library has to specify locations of all its dependencies in rpath list. but rpath is specified during link time, while dependencies(and library itself) can later be installed in some other location (when not rebuilt locally, but prebuilt packages are installed by user with different homedir path or with different conan home).
windows doesn't have rpath, so windows has to copy everything in one directory. linux can do similar thing, but linux can do better. it can adjust rpath at install time. but afaik currently conan provides no way to run some additional code at install time

proposed solution:
provide additional conan recipe method to be run at package install time. it can then fix rpath or symlink deps to library's install dir for example

**Comment by memsharded** [comment]
> provide additional conan recipe method to be run at package install time. it can then fix rpath or symlink deps to library's install dir for example

I think this is something that we have already been discussed, but so far we haven't reached a consensus. The fact is that doing that, it changes the installed binaries, and destroys the manifest of the package, which checksums won't match the actual binaries. Package uploads, downloads, updates, probably will do weird things if the manifest is updated, but having packages that doesn't declare the manifest is not nice. Integrity verification is now possible before upload, and it will be also implemented for installs.

We need to discuss this.

**Comment by pal666** [comment]
i can live with adding symlinks, which wouldn't change existing binaries

**Comment by spavlovskyi** [comment]
no, i wasn't aware of hook. i'll try them

**Comment by memsharded** [comment]
Hi @spavlovskyi 

Did you manage to have a look to the hooks? Were they ok for your use case? 

Besides having the hooks, to perform some orthogonal post_xxx action, I would like to learn how do you plan to do such Rpaths manipulation on the binaries:

- What are the paths that you are looking to search for, and replace by what?
- We usually use the LD_LIBRARY_PATH mechanism, that is clean, can be automated with ``virtualrunenv`` generator.
- How do you plan to handle multiple versions? Lets say, you install LibA-1.0.so that uses LibB-1.0.so and then you adjust the Rpath of LibA-1.0.so. Now you have another project that uses LibB-1.1, and LibA-1.0, and we can safely assume they are binary compatible. You can't have both Rpaths for both projects at the same time. This is why the LD_LIBRARY_PATH approach is more general, as it is local to the consumer only.

Please, any feedback regarding these points would be very useful to understand better the issue. Many thanks!

**Comment by spavlovskyi** [comment]
sorry, i didn't have time to investigate hooks yet, i'll try tomorrow.
for now answers to questions:
- "What are the paths that you are looking to search for, and replace by what?"
currently rpaths are set to same values which go to `-L` parameters. this is ok for build from source but not ok after install to different prefix. i had idea of replacing them with { libdirs adjusted to new prefix (i.e. same values which will go to `-L`, just reevaluated in new environment)  } on install. now i've given more thought to it and i think that it could be solved by using { calculated relative rpaths, which will be valid in any prefix } instead of { absolute rpaths } during build. like `$ORIGIN/../../../../../../../libb/1.0/conan/stable/package/abcdef/lib`
- "We usually use the LD_LIBRARY_PATH mechanism, that is clean, can be automated with virtualrunenv generator."
`LD_LIBRARY_PATH` is harder to use, you can't just run executable, you have to run it from properly setup shell.
- "How do you plan to handle multiple versions? Lets say, you install LibA-1.0.so that uses LibB-1.0.so and then you adjust the Rpath of LibA-1.0.so. Now you have another project that uses LibB-1.1, and LibA-1.0, and we can safely assume they are binary compatible"
dynamic loader does breadth-first search, i.e. if you have binary which links to both liba and libb ( `readelf -d $binary | grep NEEDED` mentions liba and libb ), then both liba and libb  will be loaded from this binary's rpath lists, i.e. liba's rpath will not be consulted when loading libb, i.e. its value is irrelevant. i'm concerned with case when there are no higher-level rpath applicable

**Comment by memsharded** [comment]
This seems a bit recurrent, recently from slack conversations. Labeled issue and assigned at least for consideration in Conan 2.0. My latest view on it:

- It sounds difficult to implement, and risky to break things.
- The idea would be to have a "install" folder in the cache, different to the "package" one. Packages are consumed from the "install" folder, but uploaded and downloaded from the "package" one.
- Package could be served as a cache thing (conanmanifest.txt), and maybe can keep the compressed .tgz files too
- It would be necessary to optimize, have only 1 folder with 1 copy of the things unless it is strictly necessary (local modifications to file or something), as packages are typically big

It keeps the label "look into" and "whiteboard", as this needs a lot of thinking and design before moving forward.

**Comment by memsharded** [comment]
Conan 2.0 has finally decided to move forward with the ```deployers`` approach, that will allow to do whatever operations, even full copies from the cache to a project folder, and then patching rpaths, if that is the desired behavior.

**Comment by Tumb1eweed** [comment]
> deployers
Does "deployers" approach have doc?

**Comment by memsharded** [comment]
Only https://docs.conan.io/en/2.0/whatsnew.html#new-deployers at the moment, but we are working on the docs for 2.0, it will get there soon.
