### ISSUE TITLE
Support for other compilers/architectures: IBM Power 8 system fails.

### ISSUE THREAD

**Issue by FunMiles** [conan-io/conan#405]
Trying to use conan on an IBM Power 8 system, I got the following output:

> It seems to be the first time you run conan
> Auto detecting your dev setup to initialize conan.conf
> Found gcc 4.8
> Default conan.conf settings
>	os=Linux
>	arch=ppc64le
>	compiler=gcc
>	compiler.version=4.8
>	compiler.libcxx=libstdc++
>	build_type=Release
> *** You can change them in ~/.conan/conan.conf ***
> *** Or override with -s compiler='other' -s ...s***
>
>
> ERROR: 'ppc64le' is not a valid 'settings.arch' value.
> Possible values are ['armv6', 'armv7', 'armv7hf', 'armv8', 'x86', 'x86_64']

There should be support for arbitrary compiler/architecture.

**Comment by memsharded** [comment]
Any arbitrary setting is supported. They are just not included in the default ``settings.yml``. Check http://docs.conan.io/en/latest/reference/config_files.html#settings-yml.

You can add to that file the settings you want, with the values you want, and with any arbitrary nesting. The default ``settings.yml`` is just a mechanism to ensure that conan users use the same "standard" values for compilers, etc. The only requisite for customized ``settings.yml`` is to share them with your team and users. Of course, if you think that such ``ppc64Ie`` is a common architecture for other conan users, please submit a pull request with it, we are willing to merge it, so future releases have that in the default settings. If possible, please submit not only just your architecture, but if you think that other ones are also useful for other conan users, please submit them too. Thank you!

**Comment by FunMiles** [comment]
Thanks. This is the first architecture I am touching that had an issue. I will definitely create a pull request as it could be useful to others. There are not many such system available yet, but IBM pushing their open power system, there could be more people in a near future who may use such a system.

On the other hand, it would be good to have an error message that would mention the link you gave.

**Comment by memsharded** [comment]
Yes, I totally agree about the error message, so I have both added an entry in the FAQ: http://docs.conan.io/en/latest/faq.html#is-my-compiler-version-architecture-or-setting-supported created a new issue for it: https://github.com/conan-io/conan/issues/406

About the compiler command, it is true that it would be very useful if conan could have the compiler command to execute. This is quite simple in Windows for MSVC with vcvars, or if using cmake generators. But it is very different for *nix systems with gnu/gcc or clang toolchains. It happens that such command is not absolute, cannot be defined by conan. It is not true that clang 3.8 will always be located in the same place, or use the same config. Every developer have their own setup, they might put things in different locations... This is why build systems as make or CMake use the CC/CXX environment variables to define such input.

Conan does not interfere or modify the developers dev environment, so the most it can do is for example, complain if it is specified to install dependencies for a gcc version, but another gcc version is being actually used to build the project.

I think that any helper in this direction could be very useful. Not necessarily a generator, just a helper would be enough, but not sure what would be the approach to obtain the compilers, specially if they are not in the path and are specified in CC/CXX variables. There is an open issue #271 with a similar aim, trying to improve over the specification of clang in the conan workflow. What would be your approach for obtaining the list of compilers? Would you just match the first one that matched the conan settings? Probably good for 99% of the cases.

**Comment by FunMiles** [comment]
I only have *nix system experience, so I can't talk about Windows, but you say it is easy, so I am on the more difficult side of the road.
I just read issue #271 and I agree with what **tru** suggested in one form or another.
Letting CC and CXX be underlaying the executions of conan compilations seems dangerous to me. Things might totally fail in a way that would be very difficult for a novice to understand.

What I might suggest is to have a discovery of compiler(s) the first time conan is installed trying to locate gcc, clang, apple-clang,... and then add a command to conan for adding compilers/profiles (as suggested by **tru**) with symbolic names on any given machine. 
Then it would be safe (and best) for conan to override the CC and CXX variables for the appropriate symbolic name.
Just like with libraries, the user could override the profile/compiler for some libraries. Example: clang can use two incompatible std::string defining libraries and thus it is important to use the same standard library for any component that uses std::string, but  if a library on which some code depend is purely in C or doesn't use std::string, it doesn't matter which C++ standard library is used and one could override the choice of profile to always use the one with one particular STL.

**Comment by memsharded** [comment]
Marking this issue as fixed, (the arch has been added to default settings), and opened a specific issue https://github.com/conan-io/conan/issues/524, for the development of the profiles feature.

**Comment by memsharded** [comment]
Released in conan 0.13.1
