### ISSUE TITLE
Improve URL encoding of properties provided by artifacts.properties

### ISSUE THREAD

**Issue by markgalpin** [conan-io/conan#4058]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

From another Forum:
When publishing Conan packages via the Jenkins Artifactory Plugin, the build.name property attached to the uploaded artifacts gets corrupted when there is a space in the build name, or in cases where there is a slash "/" in the build name, as the plugin transforms slashes to " :: ".

To reproduce:
Run the conan-example, but update the buildInfo.name to for example: "QE :: artifactory-push-pipeline".

If you check the property on the artifacts, it will be "QE \:\: artifactory-push-pipeline".
Note the added backslashes.

Editor's Note:
A little research suggests that this can be encoded with standard url encoding to UTF-8 before setting the property.  Could in theory be done either by plugin or conan, but seems like it would be more generic to do it in conan.

**Comment by memsharded** [comment]
> Note the added backslashes.

Which backslashes?

Please provide accurate steps in Conan to reproduce the issue:
- What is the "conan-example"?
- "check the property on artifacts", but where? Artifactory? It shouldn't require Artifactory if it is Conan responsibility, as Conan does not directly upload the buildinfo to Artifactory, it should be reproducible locally.

**Comment by markgalpin** [comment]
https://github.com/jfrog/project-examples/tree/master/jenkins-examples/pipeline-examples/scripted-examples/conan-example
+eyalbe4
The issue is actually with the artifact upload including the properties headers in artifactory, not the build info itself.   Build-info requires not just the buildinfo.json but also that each build target artifact have specific properties set.  Conan attempts to set those properties via header, but with newer versions of Artifactory, it has gotten stricter about encoding requirements.

**Comment by memsharded** [comment]
> Build-info requires not just the buildinfo.json but also that each build target artifact have specific properties set. Conan attempts to set those properties via header, but with newer versions of Artifactory, it has gotten stricter about encoding requirements.

This is very vague and un-actionable item. Could you please clarify which headers should be uploaded? What are the stricter requirements? The linked Jenkinsfile is basically a create + upload, so nothing that couldn't be replicated with pure Conan if it is a Conan issue. Please explain clearly.

**Comment by markgalpin** [comment]
So when we use jenkins we set the properties for build.name, build.number and build.timestamp via the special properties configuration file.  (Which can be replicated with pure conan as per our generic integration.)  The issue with the reproduction is that there may be special characters in build.name, and when you create these headers, the encoding is not handling it appropriately.

**Comment by memsharded** [comment]
> So when we use jenkins we set the properties for build.name, build.number and build.timestamp via the special properties configuration file. (Which can be replicated with pure conan as per our generic integration.) The issue with the reproduction is that there may be special characters in build.name, and when you create these headers, the encoding is not handling it appropriately

Still to vague and not actionable. How it can be replicated? Forget about Jenkins, if you say it can be replicated with Conan, could you please provide a reproducible case?

**Comment by memsharded** [comment]
``artifact.properties`` removed in 2.0, long time not really used, closing as outdated
