### ISSUE TITLE
[bug] HTML dependency graph for Boost raise an exception

### ISSUE THREAD

**Issue by brobeson** [conan-io/conan#4059]
### Summary

I tried to generate a dependency graph for a small project that depends on Boost. When I try to generate HTML output, I get the following exception:
```
$ conan info --graph dep.html ./conanfile.txt 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/conans/client/command.py", line 1428, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.6/dist-packages/conans/client/command.py", line 556, in info
    self._outputer.info_graph(args.graph, deps_graph, get_cwd())
  File "/usr/local/lib/python3.6/dist-packages/conans/client/conan_command_output.py", line 96, in info_graph
    grapher.graph_file(graph_filename)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/graph/grapher.py", line 129, in graph_file
    save(filename, self.graph())
  File "/usr/local/lib/python3.6/dist-packages/conans/client/graph/grapher.py", line 151, in graph
    data = data.replace("'", '"')
AttributeError: 'tuple' object has no attribute 'replace'
```

The conan file is pretty simple:
```
[requires]
boost/1.68.0@conan/stable

[generators]
cmake_find_package
```

Dot output works just fine:
```
$ conan info --graph dep.dot ./conanfile.txt && cat dep.dot
digraph {
    "PROJECT" -> {"boost/1.68.0@conan/stable"}
    "boost/1.68.0@conan/stable" -> {"bzip2/1.0.6@conan/stable" "zlib/1.2.11@conan/stable"}
}
```

Other packages also produce HTML output just fine. I've tried `libcurl/7.61.1@bincrafters/stable` and `Poco/1.9.0@pocoproject/stable`.

### Reproducing the error
1. Copy the recipe above into a conanfile.txt
1. Run `conan info --graph dep.html ./conanfile.txt

### System details
| | |
|:---|:---|
| OS | Kubuntu 18.04 |
| Conan | 1.92 (installed via pip3)
| Python | 3.6.7 |
| Boost package | boost/1.68.0@conan/stable |

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
Hi @brobeson! Thanks for sharing this problem.

Your problem is already known and has already been fixed. Conan's team will release the next version very soon.

But if you really need this feature now, you could try Conan development version (unstable):
https://test.pypi.org/project/conan/1.10.0.dev1543927768/

related issue: https://github.com/conan-io/conan/pull/3908

Regards!

**Comment by brobeson** [comment]
Sorry for the duplicate; I overlooked that issue. I am starting to learn to use Conan and came across that bug while experimenting. I don't need the fix right now, but thought I'd report for others who might. Thanks for the quick response!

**Comment by memsharded** [comment]
Hi @brobeson 

Actually this should be already fixed in conan 1.10, which is already released (not yet announced, missing a couple of minor things), so you can upgrade with ``pip install conan --upgrade`` and try again.

**Comment by brobeson** [comment]
Pip reported that everything is up to date. I'm still new to pip, though, so it's probably just my lack of experience. Not a big deal; I don't need HTML output right now.

Thanks for the tip, though!

**Comment by memsharded** [comment]
That is weird. Could you please try running ``conan --version``? I have just updated from pip, and it did the upgrade, and now I see conan 1.10 as version and ``conan info boost/1.68.0@conan/stable --graph=file.html`` works fine.

**Comment by brobeson** [comment]
```
$ conan --version
Conan version 1.9.2
```

**Comment by brobeson** [comment]
For clarity, when I tried to upgrade, I ran `sudo pip3 install conan --upgrade`. On my system, pip runs in a Python 2 environment (2.7.15.rc1 to be exact), pip3 runs in Python 3. I installed those via apt: `sudo apt install python3-pip`, etc.

**Comment by memsharded** [comment]
Then, it might be an issue with your environment because in theory, it should upgrade to 1.10.

As it is not urgent for your use case, we can leave it and wait, but please, remember the moment you want to update, and then report, create a new issue if necessary and copy your commands and the output they produce. Thank you for all your feedback!
