### ISSUE TITLE
Behavior of the ConanAPIV1.search_recipes function

### ISSUE THREAD

**Issue by aacebedo** [conan-io/conan#4063]
Hi 

I've notice a strange behavior of the "search_recipes" function from the ConanAPIV1 object.
If I call the search function with the "remotes" argument set to "all" it does not include recipes from the cache.
I have to call the function a second time with the "remotes" argument set to None and to concatenate the result in order to have a complete overview of the recipes matching a pattern.
Is this an intended behavior or shall it be modified in order to include the local cache when the "remote" argument is set to "all" ?

Regards.
Conan version 1.9.11

To help us debug your issue please explain:
- [ X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi, @aacebedo!

It is intended behavior, according to the docs (only relevant parts):

```
⇒  conan search --help
usage: conan search [-h] [-o] [-q QUERY] [-r REMOTE] [--case-sensitive]
                    [--raw] [--table TABLE] [-j JSON]
                    [pattern_or_reference]

Searches package recipes and binaries in the local cache OR in a remote. [...] If no remote is
specified, the search will be done in the local cache. [...]

```

And I'm afraid that we cannot change that behavior without breaking other users that may be using it according to the docs for their own processes.
