### ISSUE TITLE
Question: conan info looks at build required packages?

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#4066]
Hi, I'm questioning if when we generate the graph (html or dot) by using 'conan info . --graph=something.html' the packages that are mentioned in 'def build_requirements(self):' are acounted for or not? it seems not... there is a particular reason for that?

**Comment by uilianries** [comment]
Hi @nesc1!

According the documentation, [build_requires](https://docs.conan.io/en/latest/devtools/build_requires.html) are not listed in conan info nor are represented in the graph. That's because it's a requirement for building only, it not part of package itself.

**Comment by uilianries** [comment]
IMO it shouldn't be listed, because they are a requirement for build stage only. It could be a builder tool, as cmake, ninja..., which doesn't make influence over the library created.

But you could list them if you run directly over the project, for example:

    $ conan clone https://github.com/bincrafters/conan-libuv.git
    $ cd conan-libuv
    $ conan info . --graph=/tmp/index.html

`gyp_installer` will be listed.

**Comment by nesc1** [comment]
ok @uilianries , thank you for the information... i'm not conviced but i will close this thread.

Thanks
