### ISSUE TITLE
Please add commas to the approach places in version ranges documentation

### ISSUE THREAD

**Issue by carl-wallace** [conan-io/conan#4069]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Ho @carl-wallace, can you give us an example, please? 

In version `v1.9.2` there was this line of code:

https://github.com/conan-io/conan/blob/4e485cfd575ac69f4e3fe13e195277637a9b6e98/conans/client/graph/range_resolver.py#L12

so it should be exactly the same to have commas or not, that's the reason we changed the docs, as it should be compatible for `v1.9` too.

Thanks

**Comment by carl-wallace** [comment]
Not in practice. Did not work until I added commas. From the looks of my
error output I would guess something is eating the space, as it was all run
together in the error output but there was a space in conanfile.py file. I
may be able to revisit in a week or two to see if I can spot the issue. I
pulled the source to give a look but punted once I saw commas in the test
code. 

From:  "Javier G. Sogo" <notifications@github.com>
Reply-To:  conan-io/conan
<reply+000f3de5bf66a2cf30acbce5b216f89323e0e8cd13731fe592cf000000011820c0b19
2a169ce171d7eb5@reply.github.com>
Date:  Thursday, December 6, 2018 at 5:49 AM
To:  conan-io/conan <conan@noreply.github.com>
Cc:  Carl Wallace <carl@redhoundsoftware.com>, Mention
<mention@noreply.github.com>
Subject:  Re: [conan-io/conan] Please add commas to the approach places in
version ranges documentation (#4069)

**Comment by jgsogo** [comment]
I think that this issue is related and has been fixed in https://github.com/conan-io/conan/pull/4273, can you check it, please? Thanks

**Comment by memsharded** [comment]
Not released yet, need to be tested from sources or from https://test.pypi.org/project/conan/

**Comment by carl-wallace** [comment]
I will test but not before mid/late next week at the soonest.

From:  James <notifications@github.com>
Reply-To:  conan-io/conan
<reply+000f3de57df03cd30d7aadd3fdd696e1b6317ca785851f7992cf000000011854713e9
2a169ce171d7eb5@reply.github.com>
Date:  Monday, January 14, 2019 at 10:48 AM
To:  conan-io/conan <conan@noreply.github.com>
Cc:  Carl Wallace <carl@redhoundsoftware.com>, Mention
<mention@noreply.github.com>
Subject:  Re: [conan-io/conan] Please add commas to the approach places in
version ranges documentation (#4069)

**Comment by carl-wallace** [comment]
Have not revisited and likely will not be able to in the next few weeks.

From:  "Javier G. Sogo" <notifications@github.com>
Reply-To:  conan-io/conan
<reply+000f3de55528ab45918aa59cf94993cefaa328d18cff85d892cf0000000118aa03569
2a169ce171d7eb5@reply.github.com>
Date:  Wednesday, March 20, 2019 at 9:34 AM
To:  conan-io/conan <conan@noreply.github.com>
Cc:  Carl Wallace <carl@redhoundsoftware.com>, Mention
<mention@noreply.github.com>
Subject:  Re: [conan-io/conan] Please add commas to the approach places in
version ranges documentation (#4069)

**Comment by jgsogo** [comment]
Ok, anyway I'm closing the issue as it is supposed to be solved. Feel free to reopen it if something fails.

Thanks!
