### ISSUE TITLE
Upload of big files fails if the archive is uploaded first

### ISSUE THREAD

**Issue by osechet** [conan-io/conan#407]
When uploading packages, sometimes conan uploads the conaninfo.txt and conanmanifest.txt files first, then the archive. Sometimes it starts with the archive. 
With a big package (Qt in my case whose uncompressed size is around 1.65GB), the operation fails when the archive is uploaded first: conan uploads the archive but fails when trying to upload the txt files. 
The archive upload is very long (more than 1 hour) and I guess conan lost the upload permission when it's done.

**Comment by memsharded** [comment]
Yes, two things could be done here, first is to order the files to upload always the files first. Then, also increase the limit. Not too much, I'd say that the default in conan.io is 120mins, should be enough, but I have to check it. Thanks for reporting.

**Comment by memsharded** [comment]
Submitted PR to fix that. Also, time limits were increased some days ago.

**Comment by memsharded** [comment]
Reopening, as it was closed automatically, but it is not released yet. Will be included in next 0.13

**Comment by memsharded** [comment]
Released in conan 0.13.1
