### ISSUE TITLE
Opt-in global full_version instead of semver for package_id

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4071]
Consider adding an opt-in mechanism using the conan.conf to change the global behavior of the package_id method to default all packages (only default, not override if they have fine adjustments) so we can change the default `semver` to default `full_version`, that would be the default in Conan 2.0

Probably we should consider the default being configurable => `full_package_id`, `full_version`...

**Comment by puetzk** [comment]
I'd also really like to see this on a per-package basis, where a package could declare how strictly it maintained binary compatibility and have that change its default representation in a consumer's info.requires["x"]. Obviously the consumer's package_id function could still change this, but in general "which versions are binary compatible" is something better known by the libfoo recipe than by the consumer.

**Comment by niosHD** [comment]
I agree, having the possibility to define the default binary compatibility (for consumers) within the package itself would be great. I have already encountered some difficulties due to the lack of this feature. (see conan-io/docs#3153)

**Comment by lasote** [comment]
@puetzk @niosHD Could you please open a new issue for that? you can reference this. There are two clearly different issues and won't be implemented together. That is the only way we don't lose it when I close this one as "done".

**Comment by niosHD** [comment]
conan-io/docs#3153 should suffice, doesn't it? I just referenced my issue since I wanted to establish the link and to make it easier discoverable it in the future. I think the suggestion that I make in https://github.com/conan-io/docs/issues/3153 is exactly the same what @puetzk is asking for.

**Comment by lasote** [comment]
You are right.

**Comment by puetzk** [comment]
Yes, I agree conan-io/docs#3153 seems like a good discussion of the same issues I had in mind with libraries that do not use semver. I've subscribed on that one.
