### ISSUE TITLE
Conan Config Install / Conan Upload, can't parallelize

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#4075]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.8.3

OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

Hi there,

We use a build server that runs several build jobs at once.

**Conan Config Install**
On the build server we run this with every job, to make sure you are grabbing the latest config (profiles, settings, etc.):
`conan config install git@github.com:<git repo>.git`

I find that either locally or on the build server, if you run the `conan config install` at the same time it fails.
To test it locally, I just had two terminals side by side then ran the command at the same time.

**Output on both when failed**
```
Trying to clone repo  git@github.com:<git repo>.git
Cloning into 'config'...
error: could not lock config file /home/<user>/.conan/tmp_config_install/config/.git/config: No such file or directory
fatal: Could not set 'remote.origin.fetch' to '+refs/heads/*:refs/remotes/origin/*'
ERROR: config install error. Can't clone repo: Command 'git -c http.sslVerify=True  clone "git@github.com:<git repo>.git" config' returned non-zero exit status 128
```

It'd be great if these calls were serialized, so that it always works.
It'd be even better, if it could tell that it's the same config trying to be installed and do nothing if it's the same!

**Conan Upload**
I find the same problem with `conan upload` to artifactory.
If two builds run at the same time in the server, only one upload makes it.
This occurs even when running locally on two terminals side by side.
It seems that the 2nd one is marking it as dirty.

`conan upload <package_name>/2.4.1@conan_common/latest -q arch=<arch> -r conan-remote -c`

**Output on fail:**
```
conan upload <name>/2.4.1@conan_common/latest -q arch=<arch> -c


Python 2 will soon be deprecated. It is strongly recommended to use Python 3 with Conan:
https://docs.conan.io/en/latest/installation.html#python-2-deprecation-notice


Uploading <name>/2.4.1@conan_common/latest to remote 'conan-remote'
Recipe is up to date, upload skipped
Uploading package 1/1: ee9a0fc0c68a6ef4eb79d817802ec17c36bf61d8
WARN: <name>/2.4.1@conan_common/latest:ee9a0fc0c68a6ef4eb79d817802ec17c36bf61d8: Removing conan_package.tgz, marked as dirty
Compressing package...
[==================================================] 197/197 files    
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 1380, in run
    method(args[0][1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 1097, in upload
    retry_wait=args.retry_wait, integrity_check=args.check)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 775, in upload
    retry_wait, integrity_check, policy, remote_name, query=query)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/uploader.py", line 77, in upload
    integrity_check, policy, remote_name, recorder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/uploader.py", line 117, in _upload
    policy, upload_remote)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/uploader.py", line 147, in _upload_package
    integrity_check, policy)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/remote_manager.py", line 146, in upload_package
    the_files = compress_package_files(files, symlinks, package_folder, self._output)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/remote_manager.py", line 343, in compress_package_files
    tgz_path = compress_files(tgz_files, symlinks, PACKAGE_TGZ_NAME, dest_folder, output)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/remote_manager.py", line 410, in compress_files
    clean_dirty(tgz_path)
  File "/usr/local/lib/python2.7/dist-packages/conans/util/files.py", line 48, in clean_dirty
    os.remove(dirty_file)
OSError: [Errno 2] No such file or directory: '/home/<user>/.conan/data/<name>/2.4.1/conan_common/latest/package/ee9a0fc0c68a6ef4eb79d817802ec17c36bf61d8/conan_package.tgz.dirty'

ERROR: [Errno 2] No such file or directory: '/home/<user>/.conan/data/<name>/2.4.1/conan_common/latest/package/ee9a0fc0c68a6ef4eb79d817802ec17c36bf61d8/conan_package.tgz.dirty'

```

Is it possible to have these commands be serialized? I've been evaluating Conan, and it's important that the commands can be run concurrently on a system.

**Comment by memsharded** [comment]
Hi @Mark-Hatch-Bose 

First, are you sure that you don't want to set up a different cache for each build job? Using CONAN_USER_HOME, you get a new, isolated environment for each build, which is highly recommended for CI. And then the jobs can for sure handle concurrency.

Please note that even if Conan cache didn't crash, you don't want to be running different jobs on the same cache, for example if they are installing different configurations with ``conan config install``. While in theory it seems that assuming you only manage one configuration for your company, that can diverge if using different configurations for different projects, for using different testing/staging/production systems, etc.

The conan local cache is not designed for concurrency. It would be too much complex (I think that even the Maven package manager cannot handle concurrency). Conan cache can actually handle some concurrency for some special tasks, like parallel installation of packages. But ``conan config install`` is not one of them. 

For uploads, there is some open issue, and this will be implemented when possible: https://github.com/conan-io/conan/issues/3452. But still, that would be concurrency to upload within a single conan command, not multi-process concurrency.

Please tell me if this makes sense. Thanks!

**Comment by Mark-Hatch-Bose** [comment]
Hi @memsharded,

Thanks for the help and I understand, I actually tried to get that working first!
One of the things I ran into was the need to log in to Artifactory each time (`conan user`) from the build server whenever CONAN_USER_HOME was changed and profiles reinstalled. So I tried using the regular ~/.conan directory on the build server, which required only having to log in once.

Is there any documentation on setting up SSH keys (or similar) for Conan use with Artifactory so I don't have to log in from each CONAN_USER_HOME sandbox. 

I'll close the ticket since this is unrelated.

**Comment by memsharded** [comment]
> One of the things I ran into was the need to log in to Artifactory each time (conan user) from the build server whenever CONAN_USER_HOME was changed and profiles reinstalled. So I tried using the regular ~/.conan directory on the build server, which required only having to log in once.

But you can set the env-var CONAN_LOGIN_USERNAME and PASSWORD ones to automate that. Specially in CI you don't want to set the credentials via ``conan user`` in the CI scripts, but via env-vars. They can also be set by remote. https://docs.conan.io/en/latest/reference/env_vars.html#conan-login-username-conan-login-username-remote-name
