### ISSUE TITLE
[hooks] Attribute checker for alias

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4078]
To help us debug your issue please explain:

When using **alias** feature in a recipe, the default hook *attribute_checker* shows:

```
[HOOK - attribute_checker] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
```

My alias looks like the same from docs [example](https://docs.conan.io/en/latest/reference/commands/misc/alias.html#conan-alias):

```
from conans import ConanFile

class AliasConanfile(ConanFile):
    name = "OpenSSL"
    version = "1.0.2"
    _patch = 'n'
    alias = "{}/{}{}@conan/stable".format(name, version, _patch)
```

I think **url**, **license** and **description** are not required when the recipe is an alias. I think the attribute checker could skip this step for alias.

Conan Version: 1.10.0

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
The _so easy fix_ is being done in the [_official_ hook](https://github.com/conan-io/hooks/blob/master/hooks/attribute_checker.py), not in the one that is embedded in Conan sources. We need to encourage people to start using hooks in a more conscious way. @danimtb is working on it too (https://github.com/conan-io/conan/pull/4106).

**Comment by danimtb** [comment]
This functionality is done and has been moved here: https://github.com/conan-io/hooks/blob/master/hooks/attribute_checker.py
