### ISSUE TITLE
Consider Virtualenvs auto setup LD_LIBRARY_PATH or system PATH for shared libs

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#408]
Virtualenvs are working great, but still in linux LD_LIBRARY_PATH has to be manually setup for shared .so libs in linux, as pointed out by @Coderdreams in https://github.com/memsharded/conan-premake/issues/1.

It is not reasonable to expect ALL packages to add the folders to `env_info`, but maybe similary to setting include, lib, bin to the respective `cpp_info` variables, the same could be done for shared libs paths to `env_info`, so consumers could just use the virtualenv generator to set the path to shared libs.

**Comment by lasote** [comment]
Should virtualenv pre-pend to CFLAGS, LDFLAGS and CPPFLAGS etc the include paths, library paths, flags etc?

**Comment by memsharded** [comment]
Maybe it is not a good idea to alter standard env variables, it depends on the use virtualenvs are given. CONAN_XXX vars sure are not harmful, and can be useful.

**Comment by memsharded** [comment]
Need to take a decission, can be closed/discard/won't fix, or move it forward.

**Comment by lasote** [comment]
@memshared How about auto-create `LD_LIBRARY_PATH` for linux and `DYLD_LIBRARY_PATH` for os with the `virtualbuildenv` generator?

Otherwise you could create a simple wrapper recipe to declare the correct variable and declare the variable based on the deps_cpp_info => lib_paths, but it is not ideal to need another recipe.

```
class LDLibraryPathConan(ConanFile):
    name = "my_wrapper"
    version = "1.0"
    license = "MIT"
    url = "https://github.com/lasote/conan_reuse_pc"
    settings = "os", "compiler", "build_type", "arch"
    requires = "zlib/1.2.11@lasote/stable", "libpng/1.6.23@lasote/stable"

    def package_info(self):
        for dep in self.deps_cpp_info.deps:
            if self.settings.os == "Linux":
                self.env_info.LD_LIBRARY_PATH.extend(self.deps_cpp_info[dep].lib_paths)
            elif self.settings.os == "Macos":
                self.env_info.DYLD_LIBRARY_PATH.extend(self.deps_cpp_info[dep].lib_paths)
```

conanfile.txt

```
[requires]
my_wrapper/1.0@lasote/stable

[generators]
virtualbuildenv
```

**Comment by lasote** [comment]
Talked with @memsharded , we are going to implement a **virtualrunenv** to set the PATH to package **bin/** folders and some helper to get that functionality in code, so we can append those variables to the environment using the `environment_append`

**Comment by Coderdreams** [comment]
Sorry to add some noise but this feature is awesome! I just gave it a try. Thank you very much!

**Comment by memsharded** [comment]
No noise, thanks very much for the feedback! 
Yeah, conan "envs" are great, specially now they are composable. So you can also generate a "virtualbuildenv" and a "virtualrunenv" and activate both for both building and running from your project.
Cheers!
