### ISSUE TITLE
Conan Server 1.10 is broken

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4080]
#### Description
Hi!

I'm trying to start conan server but seems like is broken.

    $ conan_server

> Traceback (most recent call last):
>   File "/opt/miniconda3/bin/conan_server", line 7, in <module>
>     from conans.conan_server import run
>   File "/opt/miniconda3/lib/python3.6/site-packages/conans/conan_server.py", line 1, in <module>
>     from conans.server.server_launcher import main
>   File "/opt/miniconda3/lib/python3.6/site-packages/conans/server/server_launcher.py", line 53, in <module>
>     launcher = ServerLauncher()
>   File "/opt/miniconda3/lib/python3.6/site-packages/conans/server/server_launcher.py", line 47, in __init__
    server_capabilities, only_v1=False)
> TypeError: __init__() got an unexpected keyword argument 'only_v1'

#### Environment
Conan Versions: 1.10
Python version: 3.6, 3.7
OS: Linux Ubuntu 18.04

#### Steps to reproduce
    pip3 install conan==1.10.0
    conan_server

or using Conan Docker Tools:

    BUILD_CONAN_SERVER_IMAGE=1 python build.py
    docker run -t -p 9300:9300 --name conan_server conanio/conan_server:latest 

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Confirmed, bug

**Comment by uilianries** [comment]
I'm working on it now

**Comment by jgsogo** [comment]
Closed via #4096
