### ISSUE TITLE
Add clang 8.0 to default conan.conf

### ISSUE THREAD

**Issue by nathanaeljones** [conan-io/conan#409]
Travis now supports xcode8 & apple-clang 8 beta 4. 

https://travis-ci.org/imazen/imageflow/jobs/153344453 

Would it be appropriate to add this to the default whitelisted values?

**Comment by memsharded** [comment]
Yes, sure, just submitted PR https://github.com/conan-io/conan/pull/410, should be in next release. Just remember, it should work if your travis script adds "8.0" to the ``conan/settings.yml`` file apple-clang compiler, so you can use 8.0 right now.

**Comment by lasote** [comment]
merged, will be available in next release

**Comment by memsharded** [comment]
Released in conan 0.11.1, please try and reopen if necessary
