### ISSUE TITLE
[question] Packager complains about broken links in toolchain

### ISSUE THREAD

**Issue by efremovd** [conan-io/conan#4093]
Hi everyone.

I'm kind of new to conan.
 I need an advice what to do in such case.

We have a vendor provided toolchain which obviously has broken links inside (quite a few of them).
I followed example about creating receipts for toolchains and here it is:
```
import os
from conans import ConanFile, CMake, tools


class MyToolchainConan(ConanFile):
    name = "MyToolchainConan"
    version = "2018.12.06"
    license = "Private"
    author = "me"
    url = "my_url"
    description = "My toolchain"
    settings = dict(
        os_build=["Linux"],
        arch_build=["x86_64"]
    )

    def build(self):
        toolchain_name = "mytoolchain.tar"

        print("Downloading - %s" % toolchain_name)
        tools.ftp_download("my_ftp", "%s" % toolchain_name, login="ups", password="ups")
        print("Unpacking - %s" % toolchain_name)
        tools.untargz(toolchain_name, "toolchain")
        print("Removing - %s" % toolchain_name)
        os.unlink(toolchain_name)
        print("Done")

    def package(self):
        print("Packaging")
        self.copy("*", dst="toolchain", src="toolchain", symlinks=True)
        print("Done")

    def deploy(self):
        self.run("ln -s /Users/efremovda/toolchain toolchain")

    def package_info(self):
        self.cpp_info.libs = ["hello"]
```

On package stage it fails because when FileTreeManifest.create(package_folder) called inside it checks that all files are exist and well this toolchain has plenty of broken links.

Toolchain works fine. What's the best course of actions here? BTW vendor is not going to fix them.

**Comment by memsharded** [comment]
To make sure I understood, the package fails just after the ``package()`` method prints "Done", right?

Could those symlinks just be removed? are they somehow necessary for the toolchain to operate? If they can be removed, you could do a ``os.remove()`` of them. If they are many of them, you could traverse the whole package with ``os.walk()``, check if it is a symlink and then remove it. Please tell me, and if you need help crafting this in python. Thanks! (btw, sorry for taking so long to answer, quite busy here)

**Comment by efremovd** [comment]
yeah, i can remove them. I just wanted to make sure I did not miss any special setting like do_not_validate_package or ignore_validation_errors.

Thanks anyway.

**Comment by memsharded** [comment]
You are welcome.

No, there is no special setting for that. Even if that feature would be possible, it would probably be a strongly discouraged practice, better keep package sane, and detect these things soon than failing much later.

So if you think that removing those broken symlinks in the ``package()`` step would be ok, please close the issue. Thanks!

**Comment by efremovd** [comment]
Thanks for help.
