### ISSUE TITLE
Attempting to list all available remote packages at bintray always times out

### ISSUE THREAD

**Issue by Yzrsah** [conan-io/conan#4094]
When attempting to list remote packages at bintray, there is always a timeout:

```
$ conan search -r=public-conan
ERROR: HTTPSConnectionPool(host='api.bintray.com', port=443): Read timed out. (read timeout=60.0)
```

It would be good if there was a reliable way to get a nice colorful output on the console with a list of packages at a given remote.

**Comment by memsharded** [comment]
Yes, that is a known issue, bintray takes too long.
I would recommend using Bintray Web UI to navigate it, or maybe use: https://02jandal.github.io/conan_inquiry/

**Comment by uilianries** [comment]
This conan_inquiry version is outdated. Croydon has maintained a fresh version:

https://croydon.github.io/conan_inquiry/

However, is outdated too, but he is working to get a better update mechanism.

**Comment by hosaka** [comment]
Is there some workaround for this? I tried `info` and/or `download` the packages before hand and then do an `install` with my conanfile.txt but it still appears to be trying to fetch them from bintray. This is rather frustrating as I am trying to install dependencies inside a Docker container and I can't even build a working snapshot.

**Comment by snikulov** [comment]
@memsharded what about to add some kind of remotes cache for the client? It should be great feature

**Comment by memsharded** [comment]
This has been finally fixed. ``conan search zlib* -r=conancenter`` now works fast against ConanCenter

Artifactory 7.41 contains the fixes, so if you are experiencing this in your own instance, please upgrade.
