### ISSUE TITLE
Use different build type values to search required dependencies (`requires` attribute)

### ISSUE THREAD

**Issue by HerbertKoelman** [conan-io/conan#4097]
Here is recipe that I use to create packages this way:
```
$ conan create ./conanfile.py TSI/28.0.0@rcs/testing --profile pc_x86_ubuntu16_5.4.0 -s build_type=Debug
```
I use the `-s build_type=Debug` to tell conan to consider that `TSI/28.0.0@rcs/testing` is of build type.

The problem here is that this command searches for the required Artefacts (POCO, ...) using the `build_type` that I passed. In this case `Debug`, it therefore is not finding my dependencies.

But what if I want to use `Release` artefact to build my Debug version of `TSI` ?

Is there a way to set the `TSI` build_type to Debug and still let conan search dependencies without taking this criteria into account. Ending up with this
1. Produce TSI using build_type=Debug
2. Tell CONAN to search for 
    1. POCO/1.9.0-M2@rcs/stable build_type=Release
    1. OpenSSL/1.0.2l-M0@rcs/stable build_type=Release
    2. CSC/1.17.0@rcs/stable build_type=Release

----------------------------------------------------

I use conan 1.9.2 on Linux:x86_64 (Ubuntu 16).

--- conanfile.py ------------------------------------
```
from conans import ConanFile, tools

class RecipeConan(ConanFile):
    name = "TSI"
    version = "28.0.0"
    topics = ("c++", "CXX", "interface", "ticketing")
    settings = "os", "compiler", "build_type", "arch"

    generators = ("cmake_find_package","cmake_paths")

    requires = (
            "POCO/1.9.0-M2@rcs/stable",
            "OpenSSL/1.0.2l-M0@rcs/stable",
            "CSC/1.17.0@rcs/stable"
            )

    def package(self):
        self.copy("*.h",   dst="include", src="/home/dev/c++/TSI/include")
        self.copy("*.hpp", dst="include", src="/home/dev/c++/TSI/include")

        self.copy("*.dll", dst="bin",     src="/home/dev/c++/TSI/build", keep_path=False)
        self.copy("*.so",  dst="lib",     src="/home/dev/c++/TSI/build", keep_path=False)
        self.copy("*.a",   dst="lib",     src="/home/dev/c++/TSI/build", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

To help us debug your issue please explain:

**Comment by memsharded** [comment]
Hi @HerbertKoelman 

I think you could do it with per-package settings:

```bash
$ conan create ./conanfile.py TSI/28.0.0@rcs/testing --profile pc_x86_ubuntu16_5.4.0 -s build_type=Release -s TSI:build_type=Debug
```

This is possible, but just to make sure and for other readers, it is something that might fail because of ABI compatibility. There is no guarantee that the ABI between Debug and Release packages in C++ is maintained, so the final application might fail to link, or fail at runtime. In Windows/VS it typically refuses to link, mainly to different in the runtime MD/MDd. In Linux it normally works.

Please tell me if the above works for your case. Thanks!

**Comment by HerbertKoelman** [comment]
Oups I didn't see your reply until now 8-)

Ok, this is cool.

Can I use this syntax (I mean `... -s TSI:build_type=Debug`) in a profile file ? Or is this only available as command line argument ?

**Comment by memsharded** [comment]
Yes, yes, you can also use it in profiles:

```
[settings]
build_type=Release
TSI:build_type=Debug
```

This should work with your ``conan create``. Beware that it might have a bug and might not work for the local flow (conan install + build in user space), but that is most likely going to be fixed for next release.

Please try the above and tell me, thanks!

**Comment by HerbertKoelman** [comment]
Thanks for this detailed answer.

Best wishes for the festive season :-)

**Comment by memsharded** [comment]
Thanks to you for following up.

Best wishes to you too! :) :) :)

**Comment by kurucsaiandras** [comment]
Hi! Is there a way to enforce this behavior in a conanfile.py? (My goal is to always have my dependencies build in Release from source even if my own package is build in Debug. I am using cmake-conan and Conan 2)

**Comment by memsharded** [comment]
@kurucsaiandras 

settings values cannot be defined in conanfile recipes: https://docs.conan.io/2/knowledge/guidelines.html

> Settings and configuration (conf) are read-only in recipes: The settings and configuration cannot be defined or assigned values in recipes. Something like self.settings.compiler = "gcc" in recipes shouldn’t be done. That is undefined behavior and can crash at any time, or just be ignored. Settings and configuration can only be defined in profiles, in command line arguments or in the profile.py plugin.

So, it is not possible to do so, need to define the profile and pass the profile to ``cmake-conan``

**Comment by kurucsaiandras** [comment]
@memsharded Thanks for the fast reply.

There is still something I am missing tho, even without using cmake-conan:

`conan create . -s build_type=Debug -s opencv:build_type=Release --build=missing --version=0.testing`

running this still tries to build opencv in Debug

```
opencv/4.5.5@external/conan2: Running CMake.configure()
opencv/4.5.5@external/conan2: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/opt/.conan2/p/b/openc9808324f5131b/b/build/Debug/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/opt/.conan2/p/b/openc9808324f5131b/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "/opt/.conan2/p/b/openc9808324f5131b/b/src"
```

**Comment by memsharded** [comment]
> conan create . -s build_type=Debug -s opencv:build_type=Release

Please note that in Conan 2 the patterns must be explicit, ``opencv`` alone might not match, please try something like ``-s "opencv/*:build_type=Release"``

Another alternative would be to define ``-s build_type=Release -s &:build_type=Debug``, which means: "the dependencies by default are Release, except the current "consumer" project (the ``&`` placeholder), which will be Debug.

**Comment by kurucsaiandras** [comment]
Thanks! This worked better, in a sense that the dependencies are really built in Release first. However when conan builds the consumer package, it builds the dependencies again in Debug as well. Is there a way to get around that and always use the ones already built in Release? I looked into stuff with package_id, but as far as I understand, I can only alter the behavior of the consumer package's id and rebuilding.

**Comment by memsharded** [comment]
> Thanks! This worked better, in a sense that the dependencies are really built in Release first. However when conan builds the consumer package, it builds the dependencies again in Debug as well. Is there a way to get around that and always use the ones already built in Release? I looked into stuff with package_id, but as far as I understand, I can only alter the behavior of the consumer package's id and rebuilding.

I am not sure what you mean. Conan will not build the dependencies in Debug unless it is told to do so. As this is commenting on a closed issue from 7 years ago, it would be better to report a new ticket.

Note that this is the Conan client tool, so reports here should be better done with the ``conan`` client directly, but not with any wrappers. If you have an issue with ``cmake-conan``, then it is better to report it in the ``cmake-conan`` repo.

Please provide enough details to reproduce, like ``conanfiles/CMakeListst`` (minimal but complete to reproduce the issue), exact commands to reproduce, etc. Thanks for the feedback.

**Comment by kurucsaiandras** [comment]
Thanks for the help. I will take another look then, and open a new ticket if necessary.
