### ISSUE TITLE
Cannot install from pip

### ISSUE THREAD

**Issue by dragly** [conan-io/conan#41]
Running the pip install command as described in README.rst fails:

```
$ pip install conan
Downloading/unpacking conan
  Could not find a version that satisfies the requirement conan (from versions: 0.4.0.dev1, 0.4.0.dev2, 0.4.0.dev3)
Cleaning up...
No distributions matching the version for conan
Storing debug log for failure in /home/svenni/.pip/pip.log
```

However, requiring a specific version seems to work:

```
$ pip install conan==0.4.0.dev3
```

This was tested on Ubuntu 15.10 x64 with pip installed from apt-get.

**Comment by memsharded** [comment]
hi @dragly 

yes, that's true. Support for pip install will be released in 0.5, and is now in the develop branch, but there is no stable version yet, and that is why the pip install without version can fail. It is ok if you try such dev3 pip package, just take into account its status, fallback to clone the repo and install the requirements if there is some problem. Release 0.5 should hopefully be available this week. Thanks for reporting!

**Comment by dragly** [comment]
Thanks for the feedback! I'll stick with the develop package for now then.

I'm really impressed by the project, by the way. I look forward to see how it goes and hope it will solve the longstanding issue of managing dependencies on small and new libraries in C++. Keep up the good work!

**Comment by memsharded** [comment]
Thanks! :) :) :) :)
And thanks to you for https://github.com/conan-io/conan/pull/43. With contributions like yours, we (as the community of developers) will certainly be able to solve it!

**Comment by lasote** [comment]
:+1:  :)
