### ISSUE TITLE
How to get aliased package's version information?

### ISSUE THREAD

**Issue by mcsahin** [conan-io/conan#4104]
I have many difficulties while using aliases, especially on continues integration's generic build scripts:

1.  I need to get the build order of a package receipe by using alias reference, but it does not work.
     For example; I have an alias like this:
      `conan alias mylib/latest@user/channel mylib/1.0.0@user/channel`
     
     When I need to learn the build order of a package depending on mylib; this works:
     `conan info . -bo mylib/1.0.0@user/channel`

     But this does not work:
     `conan info . -bo mylib/latest@user/channel`

2. Inspect command option does not display real version of an aliased package:
    For example:
     ```
     > conan inspect  mylib/latest@user/channel 

     name: None
     version: None
     url: None
     license: None
     author: None
     description: None
     generators: ['txt']
     exports: None
     exports_sources: None
     short_paths: False
     apply_env: True
     build_policy: None
     ```
3. Only way that I found to learn the real version of a aliased package is "info" option. But its output shows all dependency information and no way to get this output in json format. 
    For example:
     ```
     > conan info mylib/latest@user/channel 
     
     boost/1.58.0@cots/testing
        ID: 80206e07321641d2362b7a56ceaf8254914e44f7
        BuildID: bc2b72d71090aad89103c99eeae44d69daf9cc9b
        Remote: None
        URL: None
        License: None
        Recipe: Cache
        Binary: Cache
        Binary remote: None
        Creation date: 2018-11-04 00:10:57
        Required by:
             mylib/1.0.0@user/channel
    mylib/1.0.0@user/channel
        ID: 20f77e13ec92c0201c56116f21d93ff50f2e98b0
        BuildID: f50e6508b7eb049c241a298cbde98b1d3262c11f
        Remote: None
        License: None
        Recipe: Cache
        Binary: Cache
        Binary remote: None
        Creation date: 2018-11-10 12:57:38
        Required by:
             PROJECT
        Requires:
             boost/1.58.0@cots/testing
        ```
      
**Is there an easy way to get the referenced version of an aliased package easily on command prompt?**
   Could you add something like "--short" option for info parameter:
    
 ```
     > conan info --short mylib/latest@user/channel
     mylib/1.0.0@user/channel
```

4. Artifactory does not display the real version of a aliased conan package on web interface.
    I am creating and uploading package (as shown below) to artifactory, but aliased package does not display the real version of aliased package on web (Conan info of package).
    ```
    > conan alias mylib/latest@user/channel mylib/1.0.0@user/channel
    > conan upload  mylib/latest@user/channel --all -r my_remote
    ```

**Comment by sunj1** [comment]
Hi @mcsahin ,

The below command works for me:
`conan inspect  mylib/latest@user/channel -a alias`

**Comment by lasote** [comment]
Yes, you would need first to resolve the alias and then use it in the rest of commands.
I agree the build_order should be improved to resolve the alias automatically.

**Comment by monsdar** [comment]
It'd be good to have `-a alias` documented as well. Right now this is not part of `conan inspect -h`.

**Comment by lasote** [comment]
Well, `alias` is a regular attribute so it can be inspected like any other.

**Comment by gsemet** [comment]
`conan inspect -a alias` does not work with `--json`, the json is empty.

also, `conan inspect`  does not print anything is the ref is an alias (while `-a alias` outputs the target reference)

**Comment by memsharded** [comment]
This PR https://github.com/conan-io/conan/pull/9296 contains a test that validates that the json contains the alias information for ``-a alias``.

I have checked, and with the current implementation it would be a bit risky to add the alias field always to the output, as it is empty, and there might be people already relying on this behavior for parsing the output or the json. I added a TODO to change this default in Conan 2.0
