### ISSUE TITLE
[bug] conan download does not work for alias

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#4105]
`conan download` is unable to download packages for an alias.  

Output:
```
Getting the complete package list from ...
WARN: No remote binary packages found in remote
```

Checked with Conan version 1.10.0 as well.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
The `conan download` is indeed downloading the alias, so no I'm not sure if that is a bug. Maybe that is exactly what you could expect. We can think about a new parameter to the `conan download` to resolve the alias automatically.

**Comment by sunj1** [comment]
>  Maybe that is exactly what you could expect.

I think, the expected behavior is to actually download the referenced packages pointed to by the alias.  
This reasoning is similar to `conan install`, where we actually want to install the referenced package.

**Comment by memsharded** [comment]
> This reasoning is similar to conan install, where we actually want to install the referenced package.

That is the point, ``download`` is different to ``install``. It is much dumber, the exact idea of ``download`` is that it does not do any processing at all. It doesn't use profiles or settings, it doesn't resolve the graph or fetch any transitive dependencies. etc. Just download what you tell it to download. If you change that, it would become impossible to download just the ``alias`` recipe itself? I acknowledge that it is not very useful to download alias recipes, so I wouldn't strongly oppose to change this.

**Comment by memsharded** [comment]
This issue has been stale for years, going to close it now.

The current behavior of being able to download the alias itself can be necessary too, it doesn't seem that we want to remove support for this. Keeping this is consistent with the current behavior of version ranges:

```
conan download zlib/[>1.1]@
ERROR: Provide a valid full reference without wildcards.
```

If ``download`` does not resolve a version range, it shouldn't resolve alias.
