### ISSUE TITLE
exports do not work correctly if conan export is executed with --path

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#411]
I'm writing a `conanfile.py` for a custom component. Instead of doing `exports = "*"` I would like to export the whole directory (not just the files in it) instead. I already tried things like `exports = "../MyComponent"` without success. It either exports just the files or nothing.

The reason behind that is that the component is taking its Project name from the directory name. So in the above example the resulting executable would be named `MyComponent.exe` on a windows machine. If I just export the files they later get directly into the build-directory conan creates - and that directory name is a hash, so the resulting executable is called `e0a02d496bbb652b6295152dfce0d3937acc0b56.exe` or something similar.

Is it currently possible to export the directory where my conanfile.py is in? What do I need to do?

**Comment by monsdar** [comment]
This is the CMake-script that takes the name of the directory as project name:

```
#set the project name according to where the CMakeLists.txt is located
get_filename_component(ProjectId ${CMAKE_SOURCE_DIR} NAME)
project(${ProjectId})
```

**Comment by lasote** [comment]
exports = "../MyComponent/*" should work.

**Comment by lasote** [comment]
exports = "../MyComponent*" should work. But be careful if you have more folders beginning with MyComponent.

**Comment by monsdar** [comment]
Both options do not work - They do not export anything. The output that `export="*"` gives ("Copied x .h files, ...") does not appear at all.

I'm using Conan 0.11.0 on Windows 7 if that helps.

**Comment by monsdar** [comment]
I found the issue: I used `conan export` from another directory with `--path`. This seems to not work correctly with the exports.

When I do `conan export` from within the directory I had no problems getting the whole directory exported.

**Comment by monsdar** [comment]
Changed the title to make clear what the actual issue is here

**Comment by memsharded** [comment]
Can you please tell me the full command, layout and exports pattern?
I am trying with 
```bash
$ conan export user/channel --path=source
```
with an ``exports="*"`` and being located in the parent folder of the ``source`` folder, which contains the conanfile.py and other files. 
This is working for me, but it might be a relative path issue or the like, so knowing these details might help. Thanks!

**Comment by monsdar** [comment]
The problem occured when using relative pathes like that: `exports="../source*"` - it seems that this collided with the `--path` parameter.
I also switched my approach to use `exports="*"` and have no issues at all with that.

**Comment by memsharded** [comment]
Perfect, thanks for your feedback!, I was able to spot the issue, and submitted PR https://github.com/conan-io/conan/pull/425 to fix it. Just avoid the ``--path`` option until next release
