### ISSUE TITLE
Is cfgparse still a requirement?

### ISSUE THREAD

**Issue by tivek** [conan-io/conan#412]
I am trying to package `conan` for Arch Linux and have hit a snag: the `cfgparse` library is not compatible with Python 3.

Now, it seems all the TravisCI tests pass with flying colors without `cfgparse` being present: https://travis-ci.org/tivek/conan/builds/153667753

Is `cfgparse` a requirement for `conan` and can it be removed?

**Comment by memsharded** [comment]
Maybe it is not, I have just submitted a PR https://github.com/conan-io/conan/pull/413 to test it. We have setup CI for conan for Win, Linux and Mac both for python 2.7 and 3.X, so it is quite safe to submit a PR removing it and see what happens :) 

Thanks very much for pointing this issue, and also for packaging conan for Arch Linux, if you are able to do so, please tell us, (you can update and give feedback in issue #21) maybe we could add instructions in the download page.

**Comment by tivek** [comment]
Cool, thanks a lot for your quick answer!

As soon as I have a presentable PKGBUILD for Arch I'll be sure to show it in #21.
