### ISSUE TITLE
Issue with importing build properties into Visual Studio

### ISSUE THREAD

**Issue by nbhattip** [conan-io/conan#4120]
Hi, 

I am new to conan and am trying to understand why my VS proj does not get the right package links.

I am using conan 1.9.2 with Visual Studio 2017 (15.9.4) and I am running into some issues linking to libraries. I have a VS proj that builds a static library. I am trying to link in some packages through Conan that I'd be using in the project. After I install a conan package and import the props file, I see that the build props file has the correct include and library dependency paths. I also see the Visual Studio proj file updated with a correct location to the props file. But I can't see the project settings actually getting updated. The include paths and library directories are empty even though the props files and proj files are correctly updated. 

Am I missing something or is the process any different for library projects?

**Comment by memsharded** [comment]
Hi @nbhattip 

Not sure what could be failing in your case. I found sometimes that I imported the ``conanbuildinfo.props`` file at the wrong location, even if it was there, it was not being used. Also, are you using the ``visual_studio_multi`` generator, or the ``visual_studio`` one?

Maybe it would be good to setup a very small project in Github, with a couple of "hello world" libraries, so we could help you to debug the issue. Have a look to the github repos used in this section of the docs: https://docs.conan.io/en/latest/howtos/visual_studio_packages.html (please check them if you haven't yet, they are a good starting point for having VS solution working), and please consider setting up a small project so we could check. Thanks!

**Comment by nbhattip** [comment]
Thanks a lot for your response James. I think the issue is once I create a project and change some thing in the "Additional Include Directories" tag and then add the conan properties file, the conan properties files are not getting appended/added. If I do it on a clean project without touching the include directories it seems fine. I am not sure if it is actually an issue but changing the order of things seems to do the trick. Is this a restriction ?  If not, I can try providing a small sample project.

**Comment by memsharded** [comment]
It is unlikely that adding an include directory could damage it. After ``conanbuildinfo_multi.props`` is generated and added to the project, the .vcxproj file should contain something like this, at the project level:

```xml
<ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="..\conanbuildinfo_multi.props" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="..\conanbuildinfo_multi.props" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="..\conanbuildinfo_multi.props" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="..\conanbuildinfo_multi.props" />
  </ImportGroup>
```

Conan doesn't change anything else in the project. Maybe when you are modifying the Include Directories, you have to make sure to keep the ``%(AdditionalIncludeDirectories)`` that is there, and the check to ``Inherit from primary``, so in the ``InheritedValues`` you can actually see conan paths in the form: ``$(USERPROFILE)/.conan/data/Hello/0.1/user/testing/package/c32596dcd26b8c708dc3d19cb73738d2b48f12a8/include``. Please check if this could be it.

**Comment by nbhattip** [comment]
Oh. Thank you very much. That was it. I was removing the %(AdditionalIncludeDirectories) property which was causing this. Thanks very much on the quick turn around and appreciate the help a lot.

**Comment by memsharded** [comment]
No problem, love to help :)
