### ISSUE TITLE
Default conanfile used for conan install

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#4121]
We use `conanfile.py` for libraries and `conanfile.txt` for consumers.  There are some directories with both types of conanfiles in them.  By default when you run `conan install ..` it uses the `conanfile.py` if both exist.   

We rarely if ever use `conan install ..` with a `conanfile.py`.  We always rely on `conan create` to do the install step.  We would prefer for the default for `conan install` to use `conanfile.txt` when both exist.  It would be nice to have an `conan.conf` option or similar to change the default.

**Comment by memsharded** [comment]
Hi!

Quick question, why maintaining both? I guess they will contain the same requirements, options, etc, it would be a bit confusing if they were different. And you can perfectly use the conanfile.py for consuming only.

**Comment by sourcedelica** [comment]
In this directory we have a library and an executable which uses the library and adds a `main()`.

```
add_library(my_app_library Foo.cpp Bar.cpp)

add_executable(my_app main.cpp)

target_link_libraries(my_app PRIVATE CONAN_PKG::my_app_library)
```

The library contains code that is specific to the application.  The reason the library is split out is so it can be used by tests without also pulling in the `main()`.

The `conanfile.txt` is used for the application and the `conanfile.py` is used for the library.  This is our standard setup.

Ultimately should probably split the library into a separate directory but we have a lot of these library+executable directories currently.

**Comment by sourcedelica** [comment]
I can send a PR if you’d like

**Comment by memsharded** [comment]
Hi Eric,

We have been considering this, and we think that adding a configuration (in conan.conf) to define a default behavior that:

- Uses conanfile.txt for ``conan install``
- Uses conanfile.py for ``conan create``

would be a bit obscure, not very intuitive. Consider that the local development flow should run ``conan install .``, ``conan build .``, etc., over the ``conanfile.py`` too, not a ``conanfile.txt``. So defaulting to ``conanfile.txt``, even if it is opt-in in the conan.conf seems very, very custom.

So we think that it is much better to keep just one default (always .py), and then allow explicitly defining what you want at the user level:

- Put the conanfile.txt, together with the app executable code in its dedicated folder
- Explicitly call ``conan install conanfile.txt ...``
- Maybe renaming ``conanfile.txt`` -> ``app_conanfile.txt`` to be more explicit about intention could help.

Thanks for the suggestion and the offering anyway! :)

**Comment by sourcedelica** [comment]
Thanks for your consideration.  I’m going to go the route of separate directories.
