### ISSUE TITLE
Rename common variables in the codebase

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4132]
Conan references: `ref`
package references: `pref`
Client cache: `cache`
Conan Output: `output`
More?

**Comment by uilianries** [comment]
why `pref` and `client_cache` and not `package_reference` or `ccache`? I mean, there is a pattern, doesn't?

**Comment by lasote** [comment]
Sure. I just want you to complete the list & define what to do.

**Comment by jgsogo** [comment]
Not a variable, but there are several places in the sources (outputs) where we have `OpenCV`, when we have renamed this package to `opencv`. It's stupid, but I smile every time I see it.

**Comment by memsharded** [comment]
Note: Change to ``ref`` only ``ConanFileReference`` objects. E.g.: ``conan_api`` arguments called ``reference``, can be left as-is, because they are strings, they can be partial references sometimes, etc.

**Comment by jgsogo** [comment]
`conan_api` ->  `api`?

**Comment by jgsogo** [comment]
`ClientCache` -> `Cache`?

**Comment by jgsogo** [comment]
`conan_file` and `conanfile` -> `conanfile`?  when it is the result of parsing the `ConanFile` file

**Comment by danimtb** [comment]
Agree with @memsharded message above

**Comment by lasote** [comment]
We already made this in 1.12

**Comment by jgsogo** [comment]
There is still work to do (and it will always be): renaming all the outputs to `output` for example, that was the idea of keeping this issue opened.

**Comment by jgsogo** [comment]
In this PR https://github.com/conan-io/conan/pull/4494#issuecomment-464100331 it is suggested to change the functions `get_path` to `get_content` (may look for a better name). These functions are being called from the CLI `conan get ...` to retrieve the contents of a file or the list of files in a directory.
