### ISSUE TITLE
inconsistent behavior related to symlinks

### ISSUE THREAD

**Issue by spavlovskyi** [conan-io/conan#4136]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

i believe this applies to any conan version on any os supporting symlinks. when i build recent `zlib/1.2.11@conan/stable` from sources, it uses `self.copy(symlinks=True)` in `package` method. (btw, afaict it is breaking change without bumping package version number, i still have older recipe (without `symlinks` parameter) in cache). so far, so good, it creates `libz.so.1.2.11` file and `libz.so.1` symlink to it. when i `import libz.so.1*` in dependent package, i get file and symlink as expected. same steps work as  well when i download binary `zlib/1.2.11@conan/stable` from `conan-center`. but if i `upload zlib/1.2.11@conan/stable` to internal server, it will upload tgz with unlinked files. this is first inconsistency - tgz content is different from `conan-center` when i just do download/upload. if i then `install zlib/1.2.11@conan/stable` from internal server, and import `libz.so.1*` from dependent package, i get two copies instead of file and symlink, which is wasted space. if i try to import `libz.so.1` instead, it will work, but only when `zlib/1.2.11@conan/stable` is downloaded from internal server. when it was downloaded from `conan-cener` or built from sources, `import` will copy dangling symlink. this is another inconsistency. it can be solved by adding parameter to `import`'s `self.copy` to turn on following symlinks, or by exporting tgz with symlinks from local cache (there should be some way since `conan-center` has binary package with symlinks, but i can't find it in docs)

**Comment by Minimonium** [comment]
+1 from me. Got into this inconsistency with `imports`.

**Comment by sigiesec** [comment]
On the one hand, I also ran into the inconsistency that there is a symlinks parameter when calling self.copy from package(), but there is no such parameter when calling the same "method" from imports(). Apart from behaviour differences, I find it quite confusing that the syntax differs depending from where I call it. I am not sure if this affects other parameters as well.

I don't quite understand the rationale behind the "dynamicity" of self.copy. From some point of view, it would be less confusing if there were different copy methods. Is there some use case where self.copy can be called with the same parameters but different behaviour in a submethod, which may be called from either package or imports (or maybe some other method)?

**Comment by cszabo2** [comment]
A library that my project depends on uses symlinks. In their package.
I should normally use copy_deps("*", root_package="dependency_name") in my deploy method to deploy that library with its symlinks (BTW these are not *.so -> *.so.1 type links, they are external links to other packages that should be already installed on the system (e.g. tensorflow). The library that my project depends on expects these links in order to use its dependencies and handles internally broken links by not using the dependency.
by not having the symlinks argument on copy_deps, I have to workaround and copy these links manually and explicitly, which is really ugly.

**Comment by memsharded** [comment]
Closing this ticket as outdated. The ``self.copy`` method have been replaced in Conan 2 for ``copy()`` that do not handle symlinks, and provide some external function helpers to deal with symlinks.
