### ISSUE TITLE
Implement a way to set metadata for a cache recipe

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4137]
For, in the future, being able to remove the current `artifacts.property` feature (or deprecate it), it would require to change the Jenkins plugin to use the new mechanism.

The properties set in the metadata will go as headers to Artifactory in the PUT of the files.

**Comment by lasote** [comment]
After the latest conversation we had, probably the way to go is to change the plugin to directly assign the needed properties after an upload, without conan, using the Artifactory API directly to the conan package folder (recursive properties).

**Comment by memsharded** [comment]
This will be managed in the https://github.com/conan-io/conan-extensions repo
