### ISSUE TITLE
Support multiple profiles on command-line for composition

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#4141]
Profiles support static composition today via `include(other_profile)` directive.  Where this mechanism breaks down is when users want to combine partial profiles with completely unrelated information, and to do that today you need an intermediate profile which `includes()` both of the things you really want. 

So for example, I can't have four special ffmpeg-related profiles defining `ffmpeg` options in the `ffmpeg` project directory, and compose them with profiles that define the common settings of my organization: 

I want to be able to do: 
`conan create . bincrafters/testing -pr msvc_15_x64_release_mt -pr ffmpeg_with_options0`

and then: 
`conan create bincrafters/testing -pr gcc_8_x86_debug -pr ffmpeg_with_options3`

To do this today, the only feasible approach is to use one profile or the other, and then pass the rest of the items on the CLI manually.  Alternatively, you would have to create a bunch of "intermediate" profiles for every possible combination, which is clearly nonsensical. 

Obviously, this feature would require conflict resolution, but something like the order they appear on the command-line should suffice.  I am sure conflict resolution was a factor with `include()`, so this is not a new problem. 

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Yes, I think it could make sense. I've felt the pain of the composed profiles sometimes especially with build requires.
