### ISSUE TITLE
support Visual Studio 2019 Preview (Version 16.0.0 Preview 1.1)

### ISSUE THREAD

**Issue by tim-weis** [conan-io/conan#4146]
I'm using *conan.cmake* to integrate Conan into a CMake project. This works in Visual Studio 2017. Switching to Visual Studio 2019 Preview 1 fails, though. The faulting CMakeLists.txt file contains the following code:

```
if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
    message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
    file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/master/conan.cmake"
                  "${CMAKE_BINARY_DIR}/conan.cmake")
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(CONANFILE conanfile.txt
                BASIC_SETUP)
```

Generating the CMake cache fails with the following diagnostic:

>     CMake Error at C:/.../build/x64-Debug/conan.cmake:56 (message):
>       Conan: Unknown MSVC compiler version [1920]
>     Call Stack (most recent call first):
>       C:/.../build/x64-Debug/conan.cmake:169 (_get_msvc_ide_version)
>       C:/.../build/x64-Debug/conan.cmake:447 (conan_cmake_settings)
>       tests/CMakeLists.txt:17 (conan_cmake_run)

I'd like to keep using the Visual Studio 2019 Preview. Not sure how complex incorporating the new compiler would turn out to be, but I would certainly welcome an updated *conan.cmake* file.

**Comment by memsharded** [comment]
Hi @tim-weis 

It is not only conan-cmake (it has is own repository, please report issues for conan-cmake there), but it is true that Conan should add the latest VS 2019 to its default ``settings.yml``. We would need to learn about it a bit more, the toolsets they are using, try it, maybe wait a little bit until they stabilize on versioning scheme as it is problematic to release these things if later they decide to change something.

In the meantime, you could try adding it yourself to your ``settings.yml`` (in your <userhome>/.conan folder), and trying to adapt the ``conan.cmake`` script to not raise, it shouldn't be very complicated, but please ask for guidance if you need. Thanks for reporting!

**Comment by tim-weis** [comment]
@memsharded 

Thanks for the feedback. I wasn't aware, that cmake-conan lives in a different [repository](https://github.com/conan-io/cmake-conan). Is it possible to migrate this issue to a different repository, or would I have to re-open this issue in the cmake-conan repository?

**Comment by memsharded** [comment]
I think we can leave it here, as it is true that we will have to add VS 2019 to the default settings. Please open a new one in the other repo, with 2 lines and a link to this one, that would be enough, thanks!

**Comment by SSE4** [comment]
we're currently not exactly following Visual Studio versioning scheme, which already causes compatibility issues (see for example https://github.com/conan-io/conan/issues/3573). I personally think it's good time to change it starting with Visual Studio 2019 (or 16.0+), and use compiler version instead of IDE version as a base.
for instance, VS 2019 Preview 1 currently reports:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.20.27027.1 for x86
```
so, actual compiler version is `19.20.27027.1`, two first numbers match `_MSC_VER = 1920`, and we should map `1920 == 16.0`.
another example, my VS 2017 with latest update reports:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27025.1 for x86
```
so, it's `_MSC_VER = 1916` which matches compiler version `15.9` (while toolset is v141, or 14.16, actually).
this is very complicated versioning nightmare (IDE version vs toolset version vs compiler version), but we should use the last one as a base, I suppose.
@lasote @memsharded @uilianries @jgsogo @danimtb WDYT?

**Comment by lasote** [comment]
As you mentioned, there are a couple of open issues about that #3573 #3311, I think it would be better to keep the discussion at #3573. We cannot just replace the schema until Conan 2.0, and even though we probably don't want to break all the previous windows packages in Conan center. We need to define the roadmap for these changes.

**Comment by SSE4** [comment]
I mean change scheme only starting with Visual Studio 2019, leaving existing scheme for Visual Studio 2017 and older. as Visual Studio 2019 support is new feature, there is no breaking change in this case.

**Comment by lasote** [comment]
Anyway, let's discuss it at #3573, because any decision we made since now should be the finally adopted for Conan 2.0. I would keep this issue only for supporting 2019

**Comment by SSE4** [comment]
fair enough, let's limit the scope of these changes

**Comment by lasote** [comment]
We prepared Conan to be ready for VS 2019, but not for working with the pre-release.
I've open this: https://github.com/conan-io/conan/issues/4671 to enable working with pre-releases.

**Comment by lasote** [comment]
I think we can close this one and continue there. Thanks.
