### ISSUE TITLE
"2nd level" linking

### ISSUE THREAD

**Issue by coding3d** [conan-io/conan#415]
Hello,

I am having a problem which might be of my own making but I thought to mention it in case it has something to do with the conan codebase. I have packaged the GLEW library here:

https://www.conan.io/source/glew/1.13.0/coding3d/ci

This package, is successfully used by my small3d package: 

https://www.conan.io/source/small3d/1.0.4/coding3d/ci

Then, I try to reference the small3d package from this project:

https://github.com/coding3d/small3d-conan-example

So from inside the latter's directory, I do the following:

```
conan install
mkdir build
cd build
cmake ..
cmake --build .
```

After the last command, I get this error:

```
[33%] Linking CXX executable ../bin/avoidthebug3d
ld: library not found for -llibGLEW
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/avoidthebug3d] Error 1
make[1]: *** [src/CMakeFiles/avoidthebug3d.dir/all] Error 2
make: *** [all] Error 2

```

The same happens on both OSX and Debian.

So, even though my GLEW package gets linked correctly when building my small3d library, when linking my example project to small3d there is an linking error with regard to the GLEW package.

One difference between the two cases is that, when building small3d, I use FindGLEW and I link to the GLEW_LIBRARIES variable, whereas when building the example, I link to the CONAN_LIBS variable. Like I said, I know that I may have done something wrong myself here and I will keep looking into it. But I thought to let you know in case it has something to do with the way conan handles more than one levels of dependencies between packages.

**Comment by memsharded** [comment]
I have started to check, initially in win, but freetype is not supported, then in ubuntu 16.04, got some build errors with freetype too. Now checking in ubuntu 14.

**Comment by coding3d** [comment]
I've just thought now that it might work if I make a FindGLEW.cmake file
(for conan) in my GLEW package. I will look into it. Anyway I think small3d
won't conan-compile on Win because one of the dependencies, SDL2_ttf is not
ready for that yet.

**Comment by memsharded** [comment]
Now in Ubuntu 14, with gcc 5.3 I am not able to build SDL2_ttf, not sure why. Which are your settings?

**Comment by coding3d** [comment]
I use debian Jessie. I think gcc 4.9 if I remember correctly....

**Comment by coding3d** [comment]
As is often the case, this was all my fault 😱 

The following little commit has fixed everything:

https://github.com/coding3d/conan-glew/commit/a398e330369182532812573994922047eb18eacb

I hope I did not waste too much of your time with this problem. I sure did spend a lot of mine on it 😬

**Comment by memsharded** [comment]
Ok, great you solved it! No worries about my time, I am sorry that I couldn't solve it, I typically do quickly for these kind of failures, but in these case, I had some failures to build packages for some dependencies, and I got stuck before getting to that point. Thanks very much for telling!

**Comment by coding3d** [comment]
Haha! small3d is full of dependencies and there's many flavours of Linux :) That's my problem too. Once again, many thanks for all the help!
