### ISSUE TITLE
Make Version class importable from conans

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#4164]
To help us debug your issue please explain:

We already expose the Version class to the interface of the users in recipes, for example in the `get_version()` method of CMake and MSBuild build helpers. It is also useful to check and compere versions in `configure()` and there are some examples of its use like this
https://docs.conan.io/en/latest/howtos/check_conan_version_in_conanfile.html#id1

Importing from an internal module (`from conans.model.version import Version`) is something that could brake recipes in case we want to refactor the code and move that class to other place.

My suggestion is to make the import possible like this in recipes: `from conans import Version`.

**Comment by lasote** [comment]
We would need then to document/prepare a public interface for the `Version` because methods like `major()` returning `1.X.y` are pretty confusing.

**Comment by jgsogo** [comment]
There are several _Version-like_ things we are already using in the codebase, I'm listing them here just for completeness:
 * `conans.model.Version`
 * `packaging.version.Version`: it is a dependency of package `deprecation`
 * `semver.Version`

**Comment by danimtb** [comment]
This conversation is now obsolete and replaced by  #487. Let's continue the conversation there!

**Comment by jgsogo** [comment]
You linked to a wrong issue, @danimtb, maybe #4875?

**Comment by danimtb** [comment]
Yes, you are right. Thanks!
