### ISSUE TITLE
Provide a way to unset environment variables from conan

### ISSUE THREAD

**Issue by kdsx** [conan-io/conan#4168]
I haven't found any way to unset environment variables in profiles and conan recipes.
Tools module has `environment_append`, but it can only add or replace something, not delete. Empty value is not the same as unbound variable, so `environment_append({"VAR": ""})` does not work in some cases.

`environment_append` could accept `None` values in a dictionary and unset the corresponding variables for them.
For profiles I have no idea yet.

**Comment by lasote** [comment]
We could provide a `tools.environment_uset([var1, var2])`. For the profiles wouldn't be that easy. Could it work?

**Comment by kdsx** [comment]
Yep. I don't know what's better though (`environment_append` + `None` or such `environment_unset`).
`environment_unset` is clearer and self-describing, but requires two context managers when some variables should be changed and some should be unset.

**Comment by kdsx** [comment]
If `environment_unset` is chosen, then for profiles it would be logical to use
```
[unset_env]
VAR1
VAR2, VAR3
some_package*: VAR4, VAR5
```

**Comment by lasote** [comment]
Probably your first choice of `varname: None` is better using the current `environment_append` context manager. About the profiles, maybe we could use the same syntax, without "=" means unset, but I would consider it a different feature.
