### ISSUE TITLE
conan 1.11 configuration download fails

### ISSUE THREAD

**Issue by vdaxtr** [conan-io/conan#4170]
STR:
- install conan 1.11(`pip2 install conan==1.11`)
- install config from url(`conan config install https://local.storage/conan-config/conan-config.zip`)
- Get error:
```
Trying to download https://local.storage/conan-config/conan-config.zip
ERROR: Error downloading file https://local.storage/conan-config/conan-config.zip: ''tuple' object has no attribute 'get''
Waiting 5 seconds to retry...

```
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I think this is the same issue as: https://github.com/conan-io/conan/issues/4169

Will fix it asap, thanks for reporting!

**Comment by danimtb** [comment]
Yes, confirmed it is the same issue. Closing as duplicated

**Comment by lasote** [comment]
Conan 1.11.1 has been released.
