### ISSUE TITLE
[question] How to set /p:Configuration for MSBuild

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#4179]
Conan version 1.10.1 on Windows.

I'm trying to Conanize an MSBuild project with a .sln.

The .sln defines some costom configurations, in particular "Release" and "Debug" build dynamic DLL versions of the library, and instead "Static Release" and "Static Debug" build the static link .lib version, which is what we need.

Our current build system does a little ```.target``` file magic that for this particular project does:

 Properties="Configuration=Static $(Configuration);"

I'm trying to do the equivalent in my conanfile.py with:

```
    def build(self):
        msbuild = MSBuild(self)
    
        # Special logic needed to duplicate how we invoked XercesLib.vcxproj in nxgroups
        configurationToUse="Static Release"
        if self.settings.build_type == "Debug":
            configurationToUse="Static Debug"
        properties = {'Configuration': configurationToUse}
        
        #Debug - create a dumpe the string .build() will use to invoke the build.
        buildstring = msbuild.get_command("checkoutdir/XercesLib.vcxproj", properties=properties)
        print("msbuild.get_command[%s]" % buildstring)

        msbuild.build("checkoutdir/XercesLib.vcxproj", properties=properties)
```

but I get just get the /p:Configuration twice:

```
xercesc/3.1.1@PORT/stable: Calling build()
msbuild.get_command[devenv "checkoutdir/XercesLib.vcxproj" /upgrade && msbuild "checkoutdir/XercesLib.vcxproj" /p:Configuration="Debug" /p:Platform="x64" /m:64 /p:Configuration="Static Debug"]
C:\Program Files\Conan\conan\conans\util\fallbacks.py:9: UserWarning: Provide the output argument explicitly to function 'conans.client.tools.win.vcvars_command'
```

Is there a way to set instead of append variables?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I think you can pass a `build_type="Static Debug"` to the `.build()` method. It should work. Let me know!

**Comment by michaelmaguire** [comment]
Thanks, that's of course the correct fix.  I read the https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html page 4 times and still didn't see that.  

```
        # Special logic needed to duplicate how we invoked XercesLib.vcxproj in nxgroups
        buildType="Static Release"
        if self.settings.build_type == "Debug":
            buildType="Static Debug"
        msbuild.build("checkoutdir/XercesLib.vcxproj", build_type=buildType)
```

**Comment by lasote** [comment]
True, I will open an issue in the docs to clarify that. Thanks
