### ISSUE TITLE
[workspaces] Allow to ignore conanws.yml in conan install

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4182]
To be able to use the same package source checkout for a workspaces setup and "stand-alone", the `conanws.yml` would need to be renamed/moved, otherwise `conan install` finds it and assumes that the workspaces setup is to be used. It would be convenient to specify a "stand-alone" flag with `conan install` instead.

Conan 1.8.4 under Windows

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @petermbauer 

Right now, the workspaces are put a bit on-hold, until the *editable* packages are released.

I would suggest to track efforts here: https://github.com/conan-io/conan/pull/4181, it is likely that they will be released next conan 1.12. 

The idea is to stabilize *editable* packages first, then rebase the workspaces on the editable packages.
