### ISSUE TITLE
cmake.definitions and CMakeCache.txt

### ISSUE THREAD

**Issue by HerbertKoelman** [conan-io/conan#4185]
If in a conanfile.py I use cmake.definitions, does it updates the CMakeCache.txt file ?
```
...
   def configure_cmake(self):
        cmake = CMake(self)

        if self.options.system_provided:
          cmake.definitions["SYSTEM_PROVIDED"] = "ON"
...
```
If I run `conan install .. --profile cool_profile && cmake .. ` , will this be valid:
```
...
message(STATUS "SYSTEM_PROVIDED ${SYSTEM_PROVIDED}")
if ( SYSTEM_PROVIDED )
  message(STATUS "System provided")
else()
  message(STATUS "Not system provided")
endif()
...
```

Conan version: 1.10.2
OS: Ubuntu 16
Python: 3.5.2

**Comment by lasote** [comment]
No, if you call `conan install` it will install the dependencies of the current package and it will generate a `conanbuildinfo.cmake` file with the dependencies info.
I'm not sure when is exactly called your `configure_cmake` method in the recipe but usually you need to call `conan build` command to force a call to the build method that will call CMake, then they will be stored in the CMake cache and you could call cmake directly.

Also, we have a core improvement in the roadmap to generate a different from `conanbuildinfo.cmake` so you could pass that file (that will contain the definitions and any other configuration you adjust in the CMake build helper) to be passed to CMake as a toolchain or with other approaches. This feature is planned for Conan 2.0. Still a bit far.

**Comment by HerbertKoelman** [comment]
Hey ! That sounds great :-)

 I suppose that CONAN defined options (`-o XXXX=ON`) could be transformed into `set(CONAN_OPTION_XXXX ON)`. Making it possible to adjust a CMake build will be able to handle CONAN set options.
