### ISSUE TITLE
Corrupt local cache?

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4187]
hi,

i hope for a hint on would could have caused this, thx in advance.

It seems the local cache somehow got corrupted on two of our Windows Jenkins slaves. We are using the Artifactory plugin and the line
`def buildInfo = conanClient.run command: "create --profile target myuser/develop`
leads to the following error after the "create" part was successful:
```
packageA/develop@ifx/develop: Package '3e076274724ee2ebe55d782344f1663ffcecdb7b' created
[packageA_develop-Q323GJRFMQA4X6C56WSAV45IM43A6IN2WA3WMANMPGI2MY3A7B6Q] $ cmd.exe /C "conan_build_info C:\conan/conan_log.log --output C:\Jenkins\workspace\packageA_develop-Q323GJRFMQA4X6C56WSAV45IM43A6IN2WA3WMANMPGI2MY3A7B6Q@tmp\conan6681538301271269559build-info && exit %%ERRORLEVEL%%"
[Errno 2] No such file or directory: 'C:\\conan\\.conan\\data\\someotherpackage\\develop\\ifx\\develop\\package\\ace4dc98b66e7a291a3eaeb9d85253c7bcb46147\\conaninfo.txt'
```

Whereas `packageA` has nothing to do with `someotherpackage` and there are no versions of `someotherpackage in the local cache (i removed them as a first attempt to solve it, but the error stayed the same).
Furthermore i got an error when i tried to clean the local cache:
```
ERROR: packageB...: Unable to remove package folder:cde468cbad6dd67dd60f1315d21d7e473efa2e7c
        Folder busy (open or some file open):
```
Though there are no processes and the respective folder can be removed manually with the file manager.

On the other Windows machine the problem occurred with different packages and when i checked for the missing `conaninfo.txt` there was just a file `<package hash>.dirty` instead of the package folder ...?

Clearing the `data` folder solved the problem on one of the machines, but i would like to find out what happened first before i do this on the other machine.

Conan 1.8.4 under Windows 10

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Quick question: 

Seing your paths: ``C:\\conan\\.conan\\data\\someotherpackage``. Are you sharing the same conan cache among different concurrent build processes? The conan cache does not support concurrency, besides some end user (some concurrent installs & creates) commands. Is it possible that your build processes are corrupting the cache due to concurrent actions on it?

**Comment by petermbauer** [comment]
No, due to a limitation of another tool (Bullseye) we have only one executor. The path is due to "historic reasons".

**Comment by memsharded** [comment]
Other question: If you are running conan 1.8, then the command:

```bash
create --profile target myuser/develop
```
Is invalid. The path to the recipe is needed. Is it a typo? (I always recommend the syntax:
```bash
create <path> <user/channel> --profile=target
```

A thing that often mess up is the Windows Indexer. It should be disabled for the conan local caches (or temporary directories used in CI). It sometimes hold file resources while conan is trying to remove files, and blocking such removal, so conan can fail (and the message is that "the file is open or busy"). Make sure it is disabled.

Then, even if there are no concurrent processes, the build-info you are using is here:
```
C:\conan/conan_log.log
```
This looks like a shared location between builds, and the log is cumulative, so depending how Jenkins plugin is computing the build-info, that might cause the issue. Even if you remove packages from the conan cache, the log still stores information about those previous packages from a previous run. It might be that the build-info could be related to the issue. Try to remove that ``conan_log.log`` before each run, or even better, try start using a dedicated cache for every build.

Just in case, for your info, there are some known limitations to build-info for Conan, you might read the "Artifactory" labeled issues in this repo.

Please tell me if any of the above helps. Thanks!

**Comment by petermbauer** [comment]
It was indeed a typo, sorry. As stated, the `conan create` completed successfully, just the collection of the buildInfo by the plugin afterwards failed.
I re-checked the Windows Indexer, it is just enabled for some other directories, not for the `C:\conan`, maybe there is some other service lurking of this damn Windows. 
Dropping the cache for every build would increase the build times a lot since the Compilers, Qt5, ... would be downloaded for each build.
Removing the `conan_log.log` worked, thank you. I will remove it prior to every build, hopefully this solves it permanently.

**Comment by memsharded** [comment]
Ok, thanks for the feedback. Doesn't seem a core conan issue so long, but maybe the Artifactory Jenkins plugin should remove the conan_log file or provide some way to do it. I am going to close this issue, but please comment or open a new issue if the problem persists. I have also created https://github.com/conan-io/conan/issues/4191, to check the Artifactory plugin. Thanks for the feedback!
