### ISSUE TITLE
Is there a way to access option values in a Generator

### ISSUE THREAD

**Issue by HerbertKoelman** [conan-io/conan#4189]
I want to generate a cmake file that contains the current value of my recipe option set.

Say I run `conan install ./conanfile.py -o system_provided=True`, I would like to generate a cmake file that contains something like `set(system_provided ON)` when the option's value is true.

To make this happen, I'm trying to create my own generator with the idea that could I simply could implement the property `content` of my generator and let it return the text. 

Here is the master piece
```
from conans.model import Generator
from conans import ConanFile

class ConaBuildInfo(Generator):
    @property
    def filename(self):
        return "conanbuildinfo.cmake"

    @property
    def content(self):       
        return "options should be returned here"

class GeneratorPackage(ConanFile):
    name = "conanbuilinfo"
    version = "0.1"
    url = "https://github.com/memsharded/conan-premake"
    license = "MIT"

    def build(self):
        pass

    def package_info(self):
        self.cpp_info.includedirs = []
        self.cpp_info.libdirs = []
        self.cpp_info.bindirs = []
```

My problem is that I can't find a way to access options value ?

In a conan recipe, I would use `self.options` attribute (`self.options.system_provided`).

Conan: 1.10.2
System: Linux (Ubuntu 16)
Python: 3.5.2

**Comment by memsharded** [comment]
Hi @HerbertKoelman 

Yes, the generators interface is:

```
class Generator(object):
    __metaclass__ = ABCMeta

    def __init__(self, conanfile):
        self.conanfile = conanfile
        self._deps_build_info = conanfile.deps_cpp_info
        self._deps_env_info = conanfile.deps_env_info
        self._env_info = conanfile.env_info
        self._deps_user_info = conanfile.deps_user_info
```

That means that generators have access to ``self.conanfile`` and thus ``self.conanfile.options``.
I think this is not fully documented, maybe it should. 

Please try if this solves your issue and tell me. Thanks!

**Comment by memsharded** [comment]
Hi @HerbertKoelman 

Did this help your question? Did you manage to do want you wanted with the options? If so, please tell or close this issue. Thanks!

**Comment by HerbertKoelman** [comment]
Hello, I will be back to business soon and I'll try this out and let you know.

In the mean time, I wish you a happy new year 2019 :-)

**Comment by memsharded** [comment]
Great!

Happy new year 2019 for you too :) :) :)

**Comment by memsharded** [comment]
Hi @HerbertKoelman

Any news regarding this issue? Did you try it? Please tell in case this issue could be closed.

**Comment by memsharded** [comment]
Hi @HerbertKoelman 

Now that you are back ;) could you please have a look to this issue? Thanks!

**Comment by HerbertKoelman** [comment]
I'm back to work on this one. More soon :-)

**Comment by memsharded** [comment]
Hi @HerbertKoelman 

Did you have a chance to look at this? Please tell me if you need further help, I think you will be good with the above suggestion, so I am closing the issue, but please re-open or comment if necessary. Thanks!
