### ISSUE TITLE
Conan_log.log file should be removed by Jenkins Artifactory plugin

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#4191]
From https://github.com/conan-io/conan/issues/4187, it seems that the log file is not automatically removed, so it could contain traces of previous invocations, about packages not in the local cache anymore.

Please check.

**Comment by kentkost** [comment]
Does this matter? You can't run in the same CONAN_HOME after each build anyway.
If CONAN_HOME is set by the plugin then you get a new folder each time.
If you manually set the CONAN_HOME then the plugin will complain about existing remotes and crash.

Either way is really inconvenient. Surely you should be able to run a build again without having to create a new CONAN_HOME every time.  [See](https://github.com/conan-io/conan/issues/2690). Possible fix by not making a random UUID in [https://github.com/jfrog/jenkins-artifactory-plugin/blob/master/src/main/java/org/jfrog/hudson/pipeline/common/types/ConanRemote.java](line 37) and create a hash instead?

This could work if overriding a remote preserves the references.

**Comment by jgsogo** [comment]
Hi! I'm not sure if the way to go is to remove the `conan_log.log` file. As @kentkost says, if a new cache is created for the job, then it will use another file and, if you are reusing the cache, then you cannot remove that file because it is shared by several jobs (probably this is not fine).

IMO, the plugin should use a different TRACE_FILE file per ConanClient instance, so the output from different clients running in parallel and sharing the cache is not mixed and we can retrieve just the build info associated with the job.

**Comment by GordonJess** [comment]
Also having a lot of problems with this just now.  Often get failures with the error: 

> [Errno 2] No such file or directory: 'C:\\.conan\\path\\to\\package\\no\\longer\\in\\local\\cache\\conaninfo.txt'

Is it really recommended to have a separate local cache for each job? (I have packages containing toolchains and ideally don't want to have them copied for each job.)

And if so, how about concurrent runs of the same job?  Any problems with them both using the same `conan_log.log`?

**Comment by jgsogo** [comment]
Hi, @GordonJess. Right now Conan doesn't support sharing the same cache for different jobs, one job can modify the package that another job is using (to compile dependencies, link,...). We know we have to add some concurrency support or a way to share the cache between different jobs in the CI, we are on our way, but it requires important changes in the Conan core that should be addressed before.

If you don't share the cache, then the ``conan_log.log`` file won't be a problem, each job will have its own. 

---

At this moment the Artifactory-Jenkins plugin is using ``conan_log.log`` to create the build information that is uploaded to Artifactory together with the packages. It is not the best way to do it and **we are proposing some changes to Artifactory to improve it and to the plugin** ([here you can read about it](https://github.com/conan-io/conan/issues/5553#issuecomment-525796926)). There are to problems with the ``.log`` file: not all the information we'd love to have is available, and if several jobs are writing to the same file, information can get mixed.

---

In [this issue](https://github.com/conan-io/conan/issues/5553) many users are sharing their experience with CI systems. Feel free to contribute with yours. 

Thanks!

**Comment by petermbauer** [comment]
Hi,

> At this moment the Artifactory-Jenkins plugin is using `conan_log.log` to create the build information that is uploaded to Artifactory together with the packages. It is not the best way to do it and **we are proposing some changes to Artifactory to improve it and to the plugin** ([here you can read about it](https://github.com/conan-io/conan/issues/5553#issuecomment-525796926)). There are to problems with the `.log` file: not all the information we'd love to have is available, and if several jobs are writing to the same file, information can get mixed.

We are sharing the Conan local cache between the jobs/builds but have only one executor per node.
To avoid getting info from previous builds and Conan executions, we ended up emptying the `conan_log.log` with `bat 'break > %CONAN_USER_HOME%\\conan_log.log'` before executing a Conan command. A "global" (for the whole pipeline) `BuildInfo` instance is used to collect the info returned by each Conan execution. Here is the method called instead of directly running `conan`:
```
void runConanClient(String conanCommand, Boolean addToBuildInfo = true) {
    // clear the Conan log file before to prevent info from previous builds being added to the BuildInfo of this build
    withConanUserHomeEnv {
        bat 'break > %CONAN_USER_HOME%\\conan_log.log'
    }

    def newBuildInfo = config.conanClient.run(command: conanCommand)
    if (addToBuildInfo) {
        config.buildInfo.append(newBuildInfo)
    }
}
```

> In [this issue](https://github.com/conan-io/conan/issues/5553) many users are sharing their experience with CI systems. Feel free to contribute with yours.
> 
> Thanks!

Thanks, i will also add a comment there.

g,
Peter

**Comment by jgsogo** [comment]
Thanks for sharing your fix with the current versions of the tools.

I'm linking here the ongoing PR https://github.com/conan-io/conan/pull/5950 that will let the Artifactory-plugin (or a custom command) generate the build-info from a graphlock and merge several build-infos into one.

**Comment by memsharded** [comment]
This ticket is old, closing it.

Artifactory Jenkins plugin will no longer implement Conan support (2.0), but not really necessary, as it was a very thin layer around Conan command line, nothing that cannot be done directly in jenkins.
