### ISSUE TITLE
b2 generator does not define projects as rooted

### ISSUE THREAD

**Issue by grisumbras** [conan-io/conan#4200]
b2 generator's docs mention, that projects for dependencies are defined rooted, so if you have in your recipe
```ini
[requires]
clara/[>0]@bincrafters/stable
```
Then the jam-file created by generator will define a project `/clara`. But it seems, only relative projects
are created, so, instead of `/clara//libs` one has to use `clara//libs`or `../clara//libs` in a subproject.

This can be reproduced by a project like this:
```ini
; conanfile.txt
[requires]
clara/[>0]@bincrafters/stable

[generators]
b2
```

```jam
# jamroot.jam
exe main1 : main.cpp clara//libs ;
exe main2 : main.cpp /clara//libs ;
```
```cpp
int main() {}
```

And building with
```shell
$ conan install . --build missing
$ b2
```
Target `main2` will fail to be built, while target `main1` should be built successfully.

I tested it on Conan 1.11.1. The b2 generator requires Boost.Build >= 1.68

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Related PR: https://github.com/conan-io/conan/pull/4211
