### ISSUE TITLE
"ERROR: Missing prebuilt package" when trying to install a private packaged project

### ISSUE THREAD

**Issue by doronAtuar** [conan-io/conan#4203]
I'm trying to package my own project. but for some reason, I get `ERROR: Missing prebuilt package`

when runing conan create I get:
```bash
$ conan create . demo/demo
myLib/1.0@demo/demo: Calling package()
myLib/1.0@demo/demo package(): Copied 19 '.h' files:
myLib/1.0@demo/demo package(): Copied 1 '.a' file: libdarknet_static.a
myLib/1.0@demo/demo package(): Copied 1 '.so' file: libdarknet.so
myLib/1.0@demo/demo package(): Copied 16 files:
myLib/1.0@demo/demo: Package 'c023db9fc677d4d0b3bd0c20f71385e4cf8a1220' created
```
I then upload the package:
`$ conan upload demo/demo -r=my-remote`

And delete the local cache:
`$ conan remove demo/demo`

But when I try to install from server I get:
```bash
$ conan install myLib/1.0@demo/demo -s build_type=Release
myLib/1.0@demo/demo: Installing package
Requirements
    myLib/1.0@demo/demo from 'my-conan' - Downloaded
Packages
    myLib/1.0@demo/demo:c023db9fc677d4d0b3bd0c20f71385e4cf8a1220 - Missing

myLib/1.0@demo/demo: WARN: Can't find a 'myLib/1.0@demo/demo' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++11, compiler.version=5, os=Linux
- Options:
- Dependencies:
- Package ID: c023db9fc677d4d0b3bd0c20f71385e4cf8a1220

ERROR: Missing prebuilt package for 'myLib/1.0@demo/demo'
```

conanfile.py:
```python
from conans import ConanFile, tools, CMake
import os
conan_version = os.getenv("CI_COMMIT_REF_NAME", "1.0")

class myLibConan(ConanFile):
    name = "myLib"
    version = conan_version
    settings = {"os":["Linux", "Macos"], "compiler":["gcc", "apple-clang"], "build_type":["Release"], "arch":"x86_64"}

    url = "https://git.domain.com:inhouse/myLib.git"
    exports_sources = ["src/*", "!src/darknet.h", "CMakeModules/*", "CMakeLists.txt", "deps.cmake", "env.mk", "darknet.mk.template"]
    generators = "cmake"

    def package(self):
        self.copy("*.h*", dst="include", src="src", excludes="src/darknet.h")
        self.copy("*.h", dst="include", src="darknet/include")

        self.copy("*.so*", dst="lib", src="lib", keep_path=False, symlinks=True)
        self.copy("*.dylib", dst="lib", src="lib", keep_path=False)
        self.copy("*.a", dst="lib", src="darknet", keep_path=False)
        self.copy("*.so", dst="lib", src="darknet", keep_path=False)

        self.copy("*", dst="bin", src="bin", keep_path=False)

    def package_info(self):
        self.cpp_info.includedirs = ['include']
        self.cpp_info.libdirs = ['lib']
        self.cpp_info.libs = tools.collect_libs(self)

    def build(self):
        cmake = CMake(self)
        cmake.verbose = True
        cmake.configure(args=["CMAKE_BUILD_TYPE=Release"])
        cmake.build()

    def deploy(self):
        self.copy("*", dst="/usr/local/bin", src="bin", keep_path=False)

```
Client:
Ubuntu 16.04
Conan version v1.11.1

Server - private server - started with conan_server:
Ubuntu 16.04
Conan version v1.11.1

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi @doronAtuar,

I'm trying to reproduce your issue, but I find it is working for me... ok, I haven't got access to your git repository so I have simplified the recipe, can you reproduce the issue using a public recipe/library/sources? 

Meanwhile, there are some points to consider:
 * **server is not involved here, you are not uploading the package, so the client will always work using the local cache**.
 * your package function is copying all the needed files, there is no need to `export` them too.
 * your CMake is configuring always for `Release`, it should depend in `settings.build_type`

**Comment by doronAtuar** [comment]
Hey @jgsogo Thanks for the quick response

> server is not involved here, you are not uploading the package, so the client will always work using the local cache

actually it is, I forgot to mention that I delete the local cache before trying to install again. 
I've updated the previous post 

> your package function is copying all the needed files, there is no need to export them too.
your CMake is configuring always for Release, it should depend in settings.build_type

I'll fix that as well
> can you reproduce the issue using a public recipe/library/sources?

I'll try and get back to you

**Comment by doronAtuar** [comment]
Hey @jgsogo,
> Pay special attention to the arguments in the upload command. You need to upload the package (the binaries) too in order to have them available

I guess that was my problem 🤭
Now it installs correctly.

I have another Ubuntu 16.04 machine with seemingly the same configuration that it still not installing
I guess it is because it looks for a different package_id.

Thank you very much for the help 😄

**Comment by jgsogo** [comment]
Great! You are welcome!

Happy Christmas! ☃️
