### ISSUE TITLE
Library Incompatibility

### ISSUE THREAD

**Issue by kenfred** [conan-io/conan#4206]
I'm getting a library incompatibility error and the architecture of the library conan built doesn't match `conaninfo.txt`.

Version and Platform Info:
Conan version: 1.10.2 or 1.11.1
I am using conan's GCC8 docker image and I have updated to the latest version of Conan (1.11.1).

What happened:
I told conan to build a 32-bit package. 

```bash
> conan create . kenfred/testing -sarch=x86
```
But I get this error during the package test:

```bash
i386:x86-64 architecture of input file `/home/conan/.conan/data/cpt_test/1.0.0/kenfred/stable/package/496879c8b4989ea0a448e12aea2f77eba94a3096/lib/libcpt_test.a(Foo.cpp.o)' is incompatible with i386 output
```

I can see in the `conaninfo.txt` that the arch should be`x86` and inspecting the generated Makefiles, I see `-m32` on `CXX_FLAGS`. But the architecture of the library is indeed x86_64:
```bash
> readelf -h ~/.conan/data/cpt_test/1.0.0/kenfred/stable/package/496879c8b4989ea0a448e12aea2f77eba94a3096/lib/libcpt_test.a | grep 'Class\|File\|Machine'
File: /home/conan/.conan/data/cpt_test/1.0.0/kenfred/stable/package/496879c8b4989ea0a448e12aea2f77eba94a3096/lib/libcpt_test.a(Foo.cpp.o)
  Class:                             ELF64
  Machine:                           Advanced Micro Devices X86-64
```
and
```bash
> objdump -a ~/.conan/data/cpt_test/1.0.0/kenfred/stable/package/496879c8b4989ea0a448e12aea2f77eba94a3096/lib/libcpt_test.a | grep 'file format'
Foo.cpp.o:     file format elf64-x86-64
```

What I expect:
I expect the library to be 32-bit, matching the setting I provided and the metadata in `conaninfo.txt`.

Steps to reproduce:
- [Clone this repo](https://github.com/kenfred/cpt_test) I made as a simple example
- Attempt to create a 32-bit package: `conan create <name>/<channel> -sarch=x86`)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi @kenfred 

In order for Conan to apply all the information (settings, options,...) you need to include the `conanbuildinfo.cmake` in your `CMakeLists.txt`, these two lines:

```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
```

So, [the `CMakeLists.txt`](https://github.com/kenfred/cpt_test/blob/master/CMakeLists.txt) will be:

```cmake
cmake_minimum_required(VERSION 3.7)
project(CptTest)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_library(cpt_test ${CMAKE_CURRENT_SOURCE_DIR}/Foo.cpp)
target_include_directories(cpt_test PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
```

Once you include them, it works as expected.

**Comment by kenfred** [comment]
Hi @jgsogo 

Yes that fixed it. Thanks!

Is there a way around having to put those lines in CMakeLists.txt? It doesn't have any dependencies, so it's using for only the build flags. I'm hoping to make my CMakeLists.txt agnostic to conan by using the find_package generator, but this implies I can't get away from the basic setup line. I'm also not thrilled with having Conan insert the lines dynamically. It is theoretically possible to provide these as arguments to cmake and not in CMakelists.txt.

I am using Conan's CMake class in the build method of my conanfile, and I was under the impression that configuring with that CMake object knew how to convert the settings into command-line arguments for CMake.

**Comment by jgsogo** [comment]
Hi! I'm sure it is possible, and maybe there is something missing in our side. As you said, `CMake` helper must be able to provide all necessary flags and variables from the command line, and combined with `find_package_generator` it should be enough to handle the dependencies.

I need to investigate it a little bit, but I'm not sure if I'll have time until next year 🎅 Let's keep this issue open and I will give it a try.

**Comment by kenfred** [comment]
Sounds great!

**Comment by memsharded** [comment]
To clarify, @jgsogo the ``CMake`` helper does not set everything in the command line to achieve binary compatibility. In fact it does almost nothing but passing variables, like ``CONAN_LINK_RUNTIME``, but the idea is exactly that they are not CMake variables and as such, they do NOT modify the build without the user knowing.

It is the ``conanbuildinfo.cmake`` that takes the ``CONAN_LINK_RUNTIME`` and other variables and does the real changes when ``conan_basic_setup()`` is called.

It is possible to achieve the binary compatibility making sure the correct configuration is used, might be with your custom CMake variables and setting them in the ``build()`` method conditioned to the conan settings, but that might be more work than using those two lines.

Future improvements will make more clear what things need to be configured and what is being configured by the generated files.

**Comment by kenfred** [comment]
@memsharded If you have separated out the dependency target declarations by using the find_package_generator, conanbuildinfo.cmake is reduced to toolchain info. Could you not create a [toolchain file](https://cmake.org/cmake/help/v3.6/manual/cmake-toolchains.7.html) and have cmake.configure() provide the `-DCMAKE_TOOLCHAIN_FILE` argument?

**Comment by memsharded** [comment]
Yes, exactly that is the idea of the future improvements to build-helpers and generators, to decouple the information from dependencies (include paths, library names) from information of build configuration (toolchain), so both could be used in a more idiomatic way by the build systems, leaving the build-helpers simpler and doing just the work of calling the build systems, but not providing any configuration on the command line. 

That will take some time, though, and it is probably difficult to do it without breaking.

**Comment by jgsogo** [comment]
I've found a related issue in the documentation (or I'm going to relate it to this issue). 

@kenfred, I think that the title of this issue must be changed to reflect the future conversation, or even close this one and start watching the one in the docs repository.

As I'm still learning about Conan (I'm just a padawan in the path to Conan mastery), I find useful to look into this _issue_ and be able to document which variables are passed through the command line, which ones are hardcoded in the `.cmake` file and how far we are from the future of build-helpers and generators.
