### ISSUE TITLE
Conanfile Custom Methods

### ISSUE THREAD

**Issue by kenfred** [conan-io/conan#4209]
I propose an enhancement where I can provide custom methods to my conanfile class and have a way to invoke them through the conan cli. In this custom method, conan will have initialized the ConanFile instance so I can get at settings and options in the custom method.

The primary motivation is to have a dedicated method to do CMake configure. The current pattern is to have `cmake.configure()` then `cmake.build()` in the build method. However, I want the option to configure without building.

So maybe something like this:

```python
class MyLibConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"

    @custommethod
    def cmake_configure(self):
        cmake = CMake(self)
        # cmake.definitions ....
        cmake.configure()
        return cmake

    def build(self):
        cmake = self.cmake_configure()
        cmake.build()
```

Note, the docs already propose this pattern if you want to use a method like `cmake_configure` from either the build or package methods. However, I want to be able to call `cmake_configure` using the conan CLI and have all the settings and options available. Something like:

```bash
conan run cmake_configure
```

I may be able to approximate this behavior by creating my own CLI that uses the conan api. Obviously I'd like to avoid that.

There is precedent for this in other package managers and I think it should be generally useful. One example to point to is the custom scripts in `npm` or `yarn` recipes. You can define simple scripts in `package.json` and invoke them with `npm run <script_name>` or `yarn <script-name>`.

**Comment by memsharded** [comment]
Hi @kenfred 

Do you know that you have the ``--configure, --build, --install, --test`` arguments, that translate to ``should_configure, should_build, should_install, should_test`` variables that you can use in your conanfiles too?

- https://docs.conan.io/en/latest/reference/commands/development/build.html
- https://docs.conan.io/en/latest/reference/conanfile/attributes.html#attribute-build-stages

The ``should_configure, should_build, should_install, should_test`` variables are already used by build helpers, only necessary if not using them.

**Comment by kenfred** [comment]
I was not aware of those! That handles my specific use-case. I would think that the custom method thing would still be useful, but I can't think of another use-case off the top of my head.

I must admit it is a little strange to have cmake configure, build, install, and test all within the `build` method, especially when we have `package` and `test` methods available to us. We also have a `configure` method, but with a slightly different meaning.

**Comment by memsharded** [comment]
Hi!

As it seems that at the moment there is not enough evidence of high demand of these conanfile custom methods, I am going to close this issue. We can revisit in the future, don't hesitate to comment or re-open if the use case is more compelling. Thanks!

**Comment by Toby-O-Connell** [comment]
I would be interested in custom methods also. It'd be nice to be able to run my executables from the conanfile, adding the library paths as needed
