### ISSUE TITLE
Uploading to LAN server does not work

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#421]
I created a custom conan package that I'm able to use with my local server. I created an executable that gets the package and builds with it.

Now I would like to make this package accessible via LAN on a "full" Conan server. I followed [the documentation](http://conanio.readthedocs.io/en/latest/server.html) and gunicorn launches the server without problems.

If I now do `conan upload --remote MyRemote EntityUpdateLib/HEAD@demo/testing` I get the following debug output:

```
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-24 13:54:40,951]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-24 13:54:40,951]
DEBUG :rest_client.py [36]: From server: <class 'conans.errors.NotFoundException'> [2016-08-24 13:54:40,951]
Uploading EntityUpdateLib/HEAD@demo/testing
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-24 13:54:45,535]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-24 13:54:45,535]
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-24 13:54:50,073]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-24 13:54:50,073]
DEBUG :rest_client.py [36]: From server: <class 'conans.errors.NotFoundException'> [2016-08-24 13:54:50,073]
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-24 13:54:54,601]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-24 13:54:54,601]
Uploading conanmanifest.txt
[==================================================]                  DEBUG :version_checker.py[47]: Remote version check result 'current'
[2016-08-24 13:54:54,617]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-24 13:54:54,617]

Uploading conanfile.py
[==================================================]                  DEBUG :version_checker.py[47]: Remote version check result 'current'
[2016-08-24 13:54:54,617]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-24 13:54:54,617]

Uploading conan_export.tgz
[==================================================]                  DEBUG :version_checker.py[47]: Remote version check result 'current'
[2016-08-24 13:54:54,632]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-24 13:54:54,632]

DEBUG :rest_client.py [361]:
                             All uploaded! Total time: 0.0319998264313
                              [2016-08-24 13:54:54,632]
```

Although everything looks good there is no package on my server. The data directory is empty and `conan search -r MyRemote` returns 0 packages.

Is there something I need to do in adition? Do I need to set certain access rights or something similar?

**Comment by memsharded** [comment]
No, you shouldn't do anything in addition. That should work.

Could you please, paste here also the output of ``conan_server``? It should log by default the activity and api calls.

Also, please copy here the output of ``conan remote list``, and your ``server.conf`` (**remove sensitive information**) just in case. Thanks for reporting!

**Comment by monsdar** [comment]
Here's what `conan remote list` gives me:

```
>conan remote list
local: http://localhost:9300
MyRemote: http://141.200.19.166:9300
```

Here's our `server.conf`. I stripped the comments to make it shorter. I changed the `write_permissions` to allow everything just in case it was an access issue - no success unfortunately.

```
[server]
jwt_secret: mrRPfJflpSLleuZamwfoABeR
jwt_expire_minutes: 120
ssl_enabled: False
port: 9300
public_port:
host_name: localhost
store_adapter: disk
authorize_timeout: 1800
disk_storage_path: ~/.conan_server/data
disk_authorize_timeout: 1800
updown_secret: gCEzxSisVswguXtEuvuFFQMI

[write_permissions]
*/*@*/*: *

[read_permissions]
*/*@*/*: *

[users]
#default_user: defaultpass
demo: demo
```

The server is not logging anything during upload:

```
conan@conan:~/conan> gunicorn -b 0.0.0.0:9300 -w 4 -t 120 conans.server.server_launcher:app
[2016-08-25 07:30:01 +0200] [9264] [INFO] Starting gunicorn 19.6.0
[2016-08-25 07:30:01 +0200] [9264] [INFO] Listening at: http://0.0.0.0:9300 (9264)
[2016-08-25 07:30:01 +0200] [9264] [INFO] Using worker: sync
[2016-08-25 07:30:01 +0200] [9267] [INFO] Booting worker with pid: 9267
[2016-08-25 07:30:02 +0200] [9269] [INFO] Booting worker with pid: 9269
[2016-08-25 07:30:02 +0200] [9270] [INFO] Booting worker with pid: 9270
[2016-08-25 07:30:02 +0200] [9272] [INFO] Booting worker with pid: 9272
```

This is the debug output of my client during upload:

```
D:\Projects\ConanTest\EntityUpdateLib>conan upload -r MyRemote EntityUpdateLib/HEAD@demo/testing
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-25 07:32:37,523]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:32:37,523]
DEBUG :rest_client.py [36]: From server: <class 'conans.errors.AuthenticationException'> [2016-08-25 07:32:37,523]
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-25 07:32:42,111]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:32:42,111]
DEBUG :rest_client.py [36]: From server: <class 'conans.errors.NotFoundException'> [2016-08-25 07:32:42,111]
Uploading EntityUpdateLib/HEAD@demo/testing
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-25 07:32:46,716]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:32:46,716]
DEBUG :rest_client.py [36]: From server: <class 'conans.errors.ForbiddenException'> [2016-08-25 07:32:46,716]
Please log in to perform this action. Execute "conan user" command. If you don't have an account sign up here: http://www.conan.io
Please enter a password for "demo" account:
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-25 07:32:58,438]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:32:58,438]
Current 'MyRemote' user already: demo
DEBUG :auth_manager.py[75]: Got token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NzIxMTAzODYsInVzZXIiOiJkZW1vIn0.rSJ3ZMOyuY3LTtdphJWs
H5PMUrjTin8-dYs2jLtMBt4 [2016-08-25 07:32:58,578]
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-25 07:33:03,151]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:33:03,151]
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-25 07:33:07,690]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:33:07,690]
DEBUG :rest_client.py [36]: From server: <class 'conans.errors.NotFoundException'> [2016-08-25 07:33:07,690]
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-25 07:33:12,234]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:33:12,234]
Uploading conanmanifest.txt
[==================================================]                  DEBUG :version_checker.py[47]: Remote version check result 'current'
[2016-08-25 07:33:12,312]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:33:12,312]

Uploading conanfile.py
[==================================================]                  DEBUG :version_checker.py[47]: Remote version check result 'current'
[2016-08-25 07:33:12,312]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:33:12,312]

Uploading conan_export.tgz
[==================================================]                  DEBUG :version_checker.py[47]: Remote version check result 'current'
[2016-08-25 07:33:12,328]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:33:12,328]

DEBUG :rest_client.py [361]:
                             All uploaded! Total time: 0.0940001010895
                              [2016-08-25 07:33:12,328]
```

Last but not least the result:

```
>conan search -r MyRemote
DEBUG :version_checker.py[47]: Remote version check result 'current'  [2016-08-25 07:37:05,483]
DEBUG :version_checker.py[51]: Remote version '0.11.0'  [2016-08-25 07:37:05,483]
There are no packages
```

**Comment by monsdar** [comment]
I think I got something:

The server runs on a openSUSE 13.2 (Harlequin) (x86_64). This distribution default python version is Python2 (in our case it's `Python 2.7.12`), but the default pip installation is for Python3 (`pip 1.5.6 from /usr/lib/python3.4/site-packages (python 3.4)`). The pip for the default python is called `pip2.7`.

So by following the installation guide we installed the requirements for Python3. Conan then used the default Python2 as its python interpreter. I'm not sure why there are no error messages at all and the server seems to work - but this still looks like an issue to me.

I just installed pip2.7 and I'm currently trying to get the requirements installed (Proxy issues again... FML...). Just so you get a heads-up on what's going on over here.

**Comment by monsdar** [comment]
Instead of starting via gunicorn I started conan_server manually by creating a startup-script like the following:

```
import sys

conan_repo_path = "/home/conan/conan"

sys.path.append(conan_repo_path)
from conans.server.server_launcher import main
main(sys.argv[1:])
```

This was the output when I tried uploading my component:

```
conan@conan:~/conan> ./conan_server.sh
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:9300/
Hit Ctrl-C to quit.

141.200.19.146 - - [26/Aug/2016 09:08:25] "GET /v1/conans/search HTTP/1.1" 200 2
141.200.19.146 - - [26/Aug/2016 09:08:35] "GET /v1/conans/EntityUpdateLib/HEAD/demo/testing/digest HTTP/1.1" 404 0
141.200.19.146 - - [26/Aug/2016 09:08:39] "GET /v1/users/check_credentials HTTP/1.1" 200 5
141.200.19.146 - - [26/Aug/2016 09:08:44] "GET /v1/conans/EntityUpdateLib/HEAD/demo/testing HTTP/1.1" 404 0
141.200.19.146 - - [26/Aug/2016 09:08:48] "POST /v1/conans/EntityUpdateLib/HEAD/demo/testing/upload_urls HTTP/1.1" 200 1116
141.200.19.146 - - [26/Aug/2016 09:09:00] "GET /v1/conans/search HTTP/1.1" 200 2
```

When doing `conan search -r MyRemote` after uploading there still were no packages. But perhaps the output provides better information...

**Comment by memsharded** [comment]
Just a tip: I think that you might be able to launch it just with "conan_server" (not unicorn needed), both if you installed from pip or from the installer (I guess you are running the server from sources in this case).

Your output is revealing, it is missing the actual file transfers! What I am quite surprised is that it is not complaining from the client. The output of my conan_server contains lines like these:

```bash
127.0.0.1 - - [26/Aug/2016 10:09:03] "PUT /v1/files/date/1.0.0/memsharded/testing/export/conanmanifest.txt?signature=eyJhbGci...W6Y-B38AgzsMyOPPt41oVvHdMZT81lJo HTTP/1.1" 200 0
127.0.0.1 - - [26/Aug/2016 10:09:04] "PUT /v1/files/date/1.0.0/memsharded/testing/export/conanfile.py?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbXNoYXJkZWQiLCJyZXNvdXJjZV9wYXRoIjoiZGF0Z...ETfleWhqGBY8 HTTP/1.1" 200 0
127.0.0.1 - - [26/Aug/2016 10:09:05] "PUT /v1/files/date/1.0.0/memsharded/testing/export/conan_export.tgz?signature=eyJhbGciOiJI...dwxvWgxrUfzkB7Uv_4 HTTP/1.1" 200 0
```

Is that conan_server running in your LAN, and you already have the proxy in the middle? It might be also some setting in your server.conf (http://docs.conan.io/en/latest/server.html#server-parameters), read about the ports. Can you please share with me that file? Remove the ``secret`` keys from it. Thanks!

**Comment by monsdar** [comment]
The server is running in our LAN, direct connection, no proxy. In the last [comment](https://github.com/conan-io/conan/issues/421#issuecomment-242648203) I made I was already using `conan_server` instead of unicorn (btw: Which `server.conf` is it using then?). We've installed the conan server from the sources (as it was written in the [docs](http://conanio.readthedocs.io/en/latest/server.html)).

You can already find the `server.conf` in a [comment](https://github.com/conan-io/conan/issues/421#issuecomment-242285605) I made earlier.

**Comment by memsharded** [comment]
Oh, sorry, yes. Try writing in the ``host_name`` field the actual IP the machine is using, and relaunch the server. The server.conf should be located in the user home: ``~/.conan_server/server.conf``

**Comment by monsdar** [comment]
I added the IP: `host_name: 141.200.19.166` but I do not get any connection anymore. Using localhost (like the default) at least tells me that no packages are available (so the connection is established).

**Comment by memsharded** [comment]
Maybe try ``0.0.0.0``?

**Comment by monsdar** [comment]
Sorry, I tried again and it seems as if putting the IP works! :)

This issue could be closed, sorry for taking so much time from you when in the end it's all our messed up infrastructure :( Hope someone else from an enterprise environment can use this information to get everything running faster.

**Comment by memsharded** [comment]
Great!!! :) :) :) :)

Don't apologize! We are happy that you are taking the time to setup and use conan, and give feedback. Sometimes they are bugs (you have already spotted some), sometimes docs need to be improved, and sometimes they are nothing, and that's fine. Thanks to you!

Maybe in this case, it could be useful to make explicit the IP change in server.conf in the docs, what do you think?

**Comment by piponazo** [comment]
Hi!

We had the same problem in my enterprise and thanks to this thread we find the solution!

I think that it would be good to update the documentation in the page "Running your server" indicating that you should update the host_name with the IP of the server machine.

**Comment by memsharded** [comment]
I have added it to the server parameters section: http://docs.conan.io/en/latest/server.html#server-parameters

I hope this helps future users, sorry for not managing to improve this the first time!
