### ISSUE TITLE
recipe version not found if inherited from base ConanFile

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#4214]
**conan client v1.11.1**

I'm trying to write recipes for the LLVM framework using the new python requires feature. LLVM and its components (llvm (the backend API), clang (the C++ frontend), libc++, etc) are released as a monolith, but I've one package per component (So you don't pull libc++ if you just want to use libclang for example). That means all the llvm packages share the same version number, and their inter-dependencies are always pointing to the same version (clang 6.0.0 package depends on llvm 6.0.0 and so on).

While refactoring the packages to use a common `LLVMPackage` recipe class using python requires I tried to write the package `version` attribute in this base class, so all my llvm component packages are always released with the same matching version. But `conan create` command fails telling me that my conanfile.py does not specify a version.

Yesterday I was reverse-engineering your recipe loading code (*a cool way of saying I was lost and trying to understand how conan loads and evaluates recipes*) and what I saw was that nothing bizarre but completely straightforward: the conanfile file is loaded, parsed, then search for a class deriving from ConanFile, and instance that class. So I don't see how my version attribute is not seen by conan create. Maybe that's another explicit check?

Thanks for your time.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
If you are using python requires, you are already specifying a version in the recipe, not necessary to inherit it from the python-require.

The name and version cannot be inherited from the base class, it is problematic for some reasons, for example when using version ranges, or when wanting to define the version from the command line, but also inheriting from a base class in a python requires.

If you want to do that, you need to do it explicitly. Try something like:

```python
base = python_requires("...")

class Pkg(base.BaseConanFile):
    version = base.version
```

**Comment by Manu343726** [comment]
I see.

> ``` python
class Pkg(base.BaseConanFile):
    version = base.version
```

that worked great. Thanks.
