### ISSUE TITLE
[Artifactory] Package download failed: Invalid conaninfo.txt format

### ISSUE THREAD

**Issue by thorntonryan** [conan-io/conan#4223]
### Description
I've ran into an issue where I'm unable to download a package I've created and uploaded to Artifactory if that package's `self.info.settings` contains special characters (e.g. ">=17").

### Steps to reproduce

1. Use the following conanfile.py
    ```py
    from conans import ConanFile, tools

    class QuotingTestConan(ConanFile):
        name = "QuotingTest"
        version = "1.0"
        settings = "os", "compiler", "build_type", "arch"
        description = "<Description of Quotingtest here>"
        url = "None"
        license = "None"
        author = "None"
        topics = None

        def package_id(self):
            self.info.settings.foo = ">=17"
    ```
2. Create the package
    `conan create . <user>/testing`
3. Upload the package to Artifactory
    `conan upload QuotingTest/1.0@<user>/testing -r <remote>`
4. Remove your local package
    `conan remove QuotingTest/1.0@<user>/testing`
    _Confirm removal_
5.  Attempt to download package
    `conan download QuotingTest/1.0@<user>/testing -r <remote>`
    Which results in the following error:
    ```
    QuotingTest/1.0@<user>/testing: Getting the complete package list from 'QuotingTest/1.0@<user>/testing'...
    ERROR: {
      "errors" : [ {
        "status" : 500,
        "message" : "org.jfrog.repomd.conan.ConanInfoException: Invalid conaninfo.txt format: foo=>=17"
      } ]
    }. [Remote: <remote>]
    ```

### Context
I'm attempting to capture a "minimum" `cppstd` property in one of my packages. It's public API relies on `std::variant`, which was introduced in C++17. And it uses no C++20 isms, so in theory a `cppstd=20` or `cppstd=gnu20` application could consume the C++17 binaries without issue.

So, our solution was to follow the example outlined in the Conan documentation for [Defining a Custom package_id()](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=between#defining-a-custom-package-id), and make `self.info.settings.cppstd` less specific than the input by setting it equal to `>=17`.

Conan accepts this and lets me create the package, but Artifactory appears to have a parsing problem with the resulting conaninfo.txt.

It seems very similar to https://www.jfrog.com/jira/browse/RTFACT-16409.

_The package info tab also doesn't display any details of this package_

_I can workaround this issue by setting `cppstd=GreaterThanOrEqualTo17` or removing that property entirely from the package id, but in any case, the parsing bug appears to be real._

### Version Details
* Conan 1.11.1 / 1.9.1
* Python 3.7.1
* Tested against Enterprise Artifactory 6.6.3 and Enterprise Artifactory 5.10.3
* Windows 10

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Thanks for your detailed report and reproducible case. Confirmed, this is a bug:

- reproduced with Artifactory CE, 6.3
- conan_server works OK, it is only Artifactory
- It also affects ``conan search`` not only ``download`` (internally download does a search to check which binaries to download)

**Comment by memsharded** [comment]
@thorntonryan regarding your context, a couple of checks/questions:

- I guess you are building binaries for that package using different ``cppstd`` standards, for the same compiler and compiler version. Otherwise, you probably don't need to define or use it at all.
- Yes, using a string without those ">=" characters would be a good workaround until this bug is fixed in Artifactory
- In theory, normal ``conan install`` or use by conanfile should work. Only search and download should fail, please check and tell.

Thanks again for your great report!!

**Comment by thorntonryan** [comment]
> * I guess you are building binaries for that package using different cppstd standards, for the same compiler and compiler version. Otherwise, you probably don't need to define or use it at all.

Correct.

> * In theory, normal conan install or use by conanfile should work. Only search and download should fail, please check and tell.

Also correct. conan install works just fine.

Thanks again!

**Comment by thorntonryan** [comment]
I think this can be closed.

Looks like we can leverage [tools.check_min_cppstd()](https://docs.conan.io/en/1.59/reference/tools.html#tools-check-min-cppstd) to accomplish what we're after.

**Comment by memsharded** [comment]
> Looks like we can leverage [tools.check_min_cppstd()](https://docs.conan.io/en/1.59/reference/tools.html#tools-check-min-cppstd) to accomplish what we're after.

Actually you shouldn't be using things from ``from conans`` or that tools you linked but all imports should be ``from conan.xxx`` to use the modern tools: https://docs.conan.io/1/reference/conanfile/tools.html
