### ISSUE TITLE
Linux short path

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4234]
Hi!

I've spent hours trying to build node_installer for x86, but during the build step I have the follow error:

    execvp: Argument list too long

This error is caused by `ar` command, when it tries to create openssl library with really [big list of files](https://travis-ci.com/uilianries/conan-nodejs_installer/jobs/168505579#L3845) and each file is followed by an absolute path.

I can build nodejs with no problem, when running all commands manually (configure, make, make install). Thus the only limitation is caused by long paths used by Conan. Of course, the root cause is the max stack size, I could run ulimit and set a new value, but I would prefer to solve it by Conan itself.

Maybe we could add new attribute for linux short paths, because `short_paths` could break Linux users. Also, the short path on Linux could be `/tmp/.conan/<short_hash>`

I've just created a Travis job to illustrate: https://travis-ci.com/uilianries/conan-nodejs_installer/jobs/168505579#L3848

Regards!

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

/cc @tonka3000

**Comment by memsharded** [comment]
The short paths workaround in Windows comes with a lot of complexities and problems.
I'd really like to avoid to enable it for Linux.

Instead of changing the stack size, wouldn't it be possible that ``ar`` operate on relative paths?

**Comment by uilianries** [comment]
> The short paths workaround in Windows comes with a lot of complexities and problems.

Okay, you convinced me to avoid this feature :sweat_smile: 

> Instead of changing the stack size, wouldn't it be possible that ar operate on relative paths?

I'll figure out, but it's a good option I think.

Regards!

**Comment by DCNick3** [comment]
I've faced the same problem when trying to package gcc:
```
make[2]: execvp: /usr/bin/bash: Argument list too long
```

The failure happens somewhere deep in the gcc build system internals (https://gitlab.com/uwin-dev/conan-pkg/-/jobs/1413100728#L319). It's pretty hard to mitigate by not issuing long commands due to complexity of gcc's build system (and considering I use crosstool-NG - a wrapper around that complex build system).

I've managed to mitigate this issue by using bindfs to make a shorter alias for build directory:

```python
with tempfile.TemporaryDirectory() as td:
    short_build_folder = str(Path(td) / 'bld')
    os.makedirs(short_build_folder, exist_ok=True)
    self.run(['bindfs', '--no-allow-other', self.build_folder, short_build_folder])
    try:
        with tools.chdir(short_build_folder):
            
            ...
            
    finally:
        self.run(['fusermount', '-u', short_build_folder])
```

But this involves installing bindfs into the docker container, alongside with adding some options to docker when running the image (`--device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined`), which is certainly not ideal and requires the usage of a self-hosted runner and modification of its config files.

**Comment by ericriff** [comment]
I came across the same issue while packaging `gcc`, but using `linaro's abe` instead of `crosstool-ng`.

I just redirected the build to `/tmp`, which is ugly, but at least I don't depend on extra tools or special configs on the container
```py
    @property
    def _short_build_folder(self):
        return os.path.join('/tmp', self.name, self.version, 'build')
...

    def build(self):

    ...

        if os.path.exists(self._short_build_folder):
            shutil.rmtree(self._short_build_folder)
        os.makedirs(self._short_build_folder)
        with tools.chdir(self._short_build_folder):
            self.run(f'{abe_dir}/configure')

   ....

```
