### ISSUE TITLE
building with local code changes for debugging transitive dependencies 

### ISSUE THREAD

**Issue by ayubsayyad** [conan-io/conan#4237]
using cmake and conan with artifactory.
we have multiple libraries we would like to build with conan, also sometimes we want to debug (with gdb) our code before pushing to git repo. How can i use conan effectively to do this ?, 
any resources, document will be helpful.
 
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
The question is a bit open, I can recommend you to read [this](https://docs.conan.io/en/latest/creating_packages.html) and [this](https://docs.conan.io/en/latest/developing_packages.html)

**Comment by ayubsayyad** [comment]
Thanks @lasote will go through the links, 
I am new user to conan and have some libraries which will consume as well as I want to package then so next in line can consume it. Found a way using conanfile.py
