### ISSUE TITLE
Export multiple directories / exclude directories from exporting

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#424]
I cannot find anything in the documentation about using multiple exports or defining directories that should not be exported.

Directory Structure:
```
root
-Component
--src
--include
--not_needed_data
--conanfile.py
```

How do I configure the conanfile to export everything but the `not_needed_data` directory?

**Comment by memsharded** [comment]
I am afraid that there are no "exclude" patterns, everything is an "and" of include patterns. The solution for your example would be something like:

```python
exports = "src*", "include*"
```

Please try it. I will check the docs right now regarding this.

**Comment by monsdar** [comment]
That's good enough for me, I'll simply add all directories but the one I would like to exclude.

**Comment by memsharded** [comment]
Great. You were right, this piece of information was missing from the docs, thanks for noticing. Just added it: https://github.com/conan-io/docs/commit/be781bed225eac3789776bb88f40665cbd23e04f, already live: http://docs.conan.io/en/latest/reference/conanfile.html#retrieving-source-code.

Ok, if it works, please close the issue. Cheers
