### ISSUE TITLE
What is the version of conan server in the artifactory docker image?

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#4242]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [n/a] I've specified the Conan version, operating system version and any tool that can be relevant.
- [n/a] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I am planning to use the docker artifactory image on our server but I am not sure which version of Conan server it uses and/or how often it gets new updates. Would appreciate if you would provide more info or a link to the details.

**Comment by lasote** [comment]
The Artifactory docker image contains Artifactory, that supports conan repositories (server side), it is upgraded every time Artifactory is released. The Artifactory implementation is totally compatible with the Conan clients we release and will release.
The `conan server` is the open source basic version for the server side and it is installed together with Conan with pip or the standalone installers, but AFAIK is not included in the artifactory docker image.

**Comment by lasote** [comment]
If you have further question do not hesitate to write again, I could open again the issue if needed.
