### ISSUE TITLE
Upgrade pyyml

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4243]
![image](https://user-images.githubusercontent.com/3807515/50815277-cc5a6900-131c-11e9-8fe8-5bd0d248a978.png)

**Comment by uilianries** [comment]
How did you know about this security flaw? Could we use a tool check more packages?
This remember me about [Cargo Audit](https://github.com/RustSec/cargo-audit)

**Comment by uilianries** [comment]
Amazing! :clap:
