### ISSUE TITLE
conan python API interface review

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4254]
This issue is intended to **gather** (not to do) all the changes we would like to do to improve the interface of the python API, initial feedback:

- The arguments types should be natural python types, not being influenced by the argparse. E.g. The `settings` and probably other arguments passed as `"build_type=Debug"` is wrong for an API. It should be a dict if the order doesn't matter or an ordered list of pairs.
- Multi-meaning arguments, like the conanfile path or reference (I don't know if that is a real case anymore, but we need to review all)
- ... to complete

**Comment by lasote** [comment]
Take also into account:

- Input types for references, Always str? Are we returning ConanFileReference? isn't it weird?
- Together with hooks, types of refs?

**Comment by uilianries** [comment]
Thanks for updating `search_packages` to accept string instead to force the user to load a ConanFileReference object. It looks more natural now, just like conan cli.

**Comment by lasote** [comment]
To take also into account: The path to a profile or a layout should be resolved first with a specific function or method in the API, then call the method link with absolute paths to the profile.

**Comment by memsharded** [comment]
Consider also while redesigning the API the stdout/stderr thing:
https://stackoverflow.com/questions/3385201/confused-about-stdin-stdout-and-stderr

Comes from issue https://github.com/conan-io/conan/issues/6330#issuecomment-584396784

**Comment by lasote** [comment]
@memsharded I don't understand the stdout/stderr task to do.

**Comment by memsharded** [comment]
This will be tackled in succesive multiple PRs and discussion, incrementally, starting from https://github.com/conan-io/conan/pull/15462, so closing this
