### ISSUE TITLE
Best way to use a required library inside a package

### ISSUE THREAD

**Issue by cinghiale** [conan-io/conan#426]
This is an excerpt from a conanfile I am preparing:

```python
class CppnetConan(ConanFile):
    name = "cpp-netlib"
    requires = "Boost/1.60.0@lasote/stable", "OpenSSL/1.0.2h@lasote/stable"

    def build(self):
        cmake = CMake(self.settings)
        self.run('cmake %s/cpp-netlib %s' % (self.conanfile_directory, cmake.command_line))
        self.run("cmake --build . %s" % cmake.build_config)
```
How can cmake found my dependencies?

I found this snippet in the fecipe for fmt:

```python
       tools.replace_in_file("fmt/CMakeLists.txt", "project(XXX)", """project(XXX)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()""")
```

It is the recommended way? And if the project is not cmake based? there is a way?

**Comment by memsharded** [comment]
That is a convenient way. 

Another possibility, also used by other package creators is to provide a simple ``CMakeLists.txt`` that basically include the ``conanbuildinfo.cmake`` and then includes the real project ``CMakeLists.txt``. That file can be exported together with the conanfile.py in the package recipe.

For other build systems, I would follow a similar approach. If there is a generator for such build system, I would use it and ``replace``, ``patch`` or ``include`` from a parent build script. Many times, it is as easy as adding a couple of include and lib directories in the library build script.

The ``ConfigureEnvironment`` helper can be also used for Makefile based build systems.

Those are really patches, as a library that has dependencies but doesn't manage them is being packaged with conan. The native way, if such library used conan, would be much easier, but in the meantime, there is no other way than patching or hacking a bit the build scripts of the library. If you have a specific build system, or want to provide mode details about the cpp-netlib case, we could have a look.
