### ISSUE TITLE
Windows short_paths feature still needs long paths initially and can fail in Jenkins Multibranch pipelines

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#4261]
We had some issues with paths too long until we started setting short_paths=True in conanfiles and eventually adding:

```
    environment {
        CONAN_USE_ALWAYS_SHORT_PATHS = 'True'; 
    } // environment
```

to our Jenkinsfile pipeline.  This solved our problems for that Jenkins pipeline job.

Then today for the very same Jenkinsfile on the very same build farm I tried setting up a ['Multibranch' Jenkins pipeline](https://jenkins.io/blog/2015/12/03/pipeline-as-code-with-multibranch-workflows-in-jenkins/).

My build failed with error:

```
Traceback (most recent call last):
  File "conan\conans\client\command.py", line 1428, in run
  File "conan\conans\client\command.py", line 298, in create
  File "conan\conans\client\conan_api.py", line 89, in wrapper
  File "conan\conans\client\conan_api.py", line 381, in create
  File "conan\conans\client\cmd\create.py", line 52, in create
  File "conan\conans\client\manager.py", line 78, in install
  File "conan\conans\client\graph\graph_manager.py", line 133, in load_graph
  File "conan\conans\client\graph\graph_manager.py", line 209, in _load_graph
  File "conan\conans\client\graph\graph_binaries.py", line 176, in evaluate_graph
  File "conan\conans\client\graph\graph_binaries.py", line 84, in _evaluate_node
  File "conan\conans\paths.py", line 157, in package
  File "conan\conans\util\windows.py", line 77, in path_shortener
  File "conan\conans\util\files.py", line 148, in save
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\nX\\nX_nightlybuild\\workspace\\rm_conan_pipeline_nxgroups2-DQCE3P2SX5C3IKHULA3PNH3L7I3ZV62UUSNVU7Z2MZWL43SRS32Q@tmp\\artifactory\\conan.tmp82239679370821035\\.conan\\data\\si-cmakemodules\\1.9.0\\PORT\\stable\\package\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\\.conan_link'

ERROR: [Errno 2] No such file or directory: 'E:\\nX\\nX_nightlybuild\\workspace\\rm_conan_pipeline_nxgroups2-DQCE3P2SX5C3IKHULA3PNH3L7I3ZV62UUSNVU7Z2MZWL43SRS32Q@tmp\\artifactory\\conan.tmp82239679370821035\\.conan\\data\\si-cmakemodules\\1.9.0\\PORT\\stable\\package\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\\.conan_link'
[Pipeline] }
```

I'm guessing that even with short_paths, there's an initial step that still looks up the ```.conan_link``` file using the traditional 'long paths' mechanism, and in this case since the 'multibranch' workspace prefix is already longer than the non-multibranch, the path to the .conan_link file at 278 characters is too long. 

Related:

\[closed as won't fix:\] https://issues.jenkins-ci.org/browse/JENKINS-38706 "Workspace directory names mangled in multibranch pipeline"

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.  Conan version 1.10.1 Windows
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Yes, the short paths mechanism works like that, a `.conan_link` in the binary package directory, so that directory has to exist. With this mechanism, you short the rest of the build/package paths, that in the case of boost, it is itself almost reaching the limits.
With Jenkins, and any other CI, it is a complete nightmare, I try to move the cache to a "very root" directory to avoid that, generating a "unique" ID from the "build/branch/job" numbers.

**Comment by FlorentP42** [comment]
Facing this issue as well today :/
Any cleaner workaround available? So far the only solution we have is to force Jenkins to work in a custom directory at the drive root, but this forces us to manually create and delete our custom workspace directory every time and also causes potential problems if multi-branch pipelimes attempts to run at the same time (and in the same custom directory).

**Comment by lasote** [comment]
I'm afraid we don't have a better alternative, It is also an issue for us. We also have to manage custom directories in Jenkins.

**Comment by VivaLaRobo** [comment]
There's isn't a solution for this? This is impacting our entire site

**Comment by lasote** [comment]
The solution is to create short directories for the Jenkins in windows. For example `C:\J` and there create subfolders for each build. I compose a "unique" ID based on the job, build, pr, etc.
Then I set the `CONAN_USER_HOME_SHORT` and `CONAN_USER_HOME` env vars to the short folder I created before.

**Comment by memsharded** [comment]
``short_paths`` removed completely in 2.0, closing this as outdated.
