### ISSUE TITLE
Reimplement python_requires with export_sources

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4262]
Based on Conan 1.11.x codebase.

Related to #3538, #3661

The feature (not documented, we didn't feel sure about it) that copies the `export_sources` from a `python_requires` into the `source_folder` of the consumer is broken for the local workflow (actually there is an `if` that prevents the code from running). As it is implemented now, it would work following these steps:

 1. `scm` is resolved/cloned to `source_folder`
 1. `export_sources` from `python_requires` will be copied
 1. `export` folder from consumer
 1. `export_sources` folder from consumer
 1. `source_folder` is _cleaned_: removed some files like `conanfile.pyc`, `export_...tgz`, `conanfile.py`,...
 1. `source` method
 
There are several flaws here (if the `source_folder` is inside the repo, which is the expected use-case because in the local workflow we want to use the sources from their location in the repository):

  * if `python_requires` overwrites some file we cannot restore it later, so it won't be overriden in one of the following steps. The flow in the cache and the flow in the local workspace will be different.
 * if `scm` resolves to a folder that already exists it will fail (cloning a repo over an existing directory will fail).
 * the `clean` stage can remove some important files from my repo (the `conanfile.py`).

**Comment by memsharded** [comment]
I think this use case would be similar to the one I implemented in https://github.com/memsharded/source_packages/blob/master/consumer/conanfile.py for @solvingj 

I think it is worth to step back a little bit and re-think what is the best way to re-use sources, maybe it is still a build-requires and not a python-requires.

**Comment by jgsogo** [comment]
I haven't played much with the `python_requires` 🙈 , but I think there are two different use cases for this:
 * I want to reuse some _cpp-related_ file, it can be a `CMakeLists.txt`, or some source files. It is in the cpp world, it is related to the package, it is required to build (...so it looks like it should be a `build_require`).
 * The code from the `python-requires` is split into several files, so in order to run the imported functionality, I need some additional sources (python files, templates,...). Here I don't think it should be a build-require as it has nothing to do with the library we are building, it only makes sense for the recipe itself.

 I know I'm looking for the corner case, but I think that we can fix this behavior and release it. I don't find anything blocking, but maybe I'm not looking in the right direction.

**Comment by solvingj** [comment]
For what it's worth.  This does seem like a solid logical distinction to me.

**Comment by jgsogo** [comment]
I was just pointing to the difference between the files I need to build the library/app and the files I need to run Conan, and I think that `python_requires` is something specific to Conan. Anyway, I think that the `python_requires`+`export_sources` should work, I think it is needed for the second point, and then people will use it for the first one too.

**Comment by lasote** [comment]
@jgsogo Should this issue be updated with some information or status after the latest discussions about the python requires?

**Comment by jgsogo** [comment]
If #4321 is merged, we could remove _point 2_ from the issue description. But the rest stand still: #4340 is a first approach (we need to agree if it is breaking or not), but there are more points related to the local/cache workflow differences.

**Comment by memsharded** [comment]
We finally decided to get rid of "exports_folder" and "exports_sources_folder" paths in the new python_requires that supersed these ones with export folders. The new model, that will survive in Conan 2.0, only has a "path" field that points to the recipe path. Only exported files (not exports sources) exist in the new python_requires. So I think this can be closed.
