### ISSUE TITLE
python_requires and inheriting the version from base-class not working with 1.10.0

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4263]
hi,

we are using `python_requires` to have a common base-class for our recipes. In this base-class also the version attribute is set so the derived recipe classes inherit the value so they have a "default version". Since Conan 1.10.0 (we used 1.8.2 before) this does not seem to work anymore so the version is not inherited which obviously leads to an error. Before changing all our recipes to set their version themselves (using a function implemented in the `python_requires` package so its not that bad) i would like to clarify whether this was an intended change or may change back again in the future as i could not find anything related in the changelogs.

thx

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @petermbauer 

Similar to: https://github.com/conan-io/conan/issues/4214

Yes, this has been changed on purpose. It proved very problematic to inherit automatically the version from a python_requires. To use the python_requires you should have done:

```python
base = python_requires("pyreq/myversion@user/channel")
```
So you could perfectly do, if you want them to have the same version:
```python
vers = "myversion"
base = python_requires("pyreq/%s@user/channel" % vers)
class Pkg(base.ConanFile):
     version = vers
```

That is more explicit, and evident where the version is coming from. Would that be a valid approach?

**Comment by petermbauer** [comment]
thx!
