### ISSUE TITLE
conan install unexpectedly reports invalid version range

### ISSUE THREAD

**Issue by mistafunk** [conan-io/conan#4270]
i have this requirement in my `conanfile.py`:
`foo/[>16.5.0 <17.0.0]@bar/stable`

`conan install` aborts with this error:
`ERROR: version range expression '>16.5.0<17.0.0' is not valid`

note: using the deprecated comma-based syntax works fine

* Python 3.6 on CentOS 7.5
* Conan 1.11.2
* node-semver 0.6.1

**Comment by memsharded** [comment]
Reproduced, indeed an undesired bug. Thanks for reporting @mistafunk !
