### ISSUE TITLE
Conan html table seems in error

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#4284]
Conan version 1.11.2
Artifactory CE 

I have 6 Qwt library versions checked into Artifactory CE... and **I can see 6 different hashes**.  ( why 6? .... qt 5.9.7 rel/dbg that is 2 and qt 5.12  built with/without openssl for another 4 version total of 6)

I then do a "conan search Qwt/6.1.3@xxx/stable --table=file.html -r=myRemote"

and get a result of:

  | x86_64 Debugshared=Falseexamples=Falseplot=Truesvg=Trueplayground=Falsemathml=Falsedesigner=Falseopengl=Truewidgets=True | x86_64 Releaseshared=Falseexamples=Falseplot=Truesvg=Trueplayground=Falsemathml=Falsedesigner=Falseopengl=Truewidgets=True
-- | -- | --
Windows Visual Studio 14 (MD) |   |  
Windows Visual Studio 14 (MDd) |   |  

I see two columns which reflect the Debug/Release builds but not the other variants. 

I would have expected 6 columns, or one for every hash.... what am I missing?

Thanks
Carl

**Comment by memsharded** [comment]
The table output doesn't take into account the variants defined by the dependencies version, that affects the binary ID, that might be the case. What is the output of the ``conan search <ref>`` in text mode?

**Comment by ShamanTcler** [comment]
Here is my use case: Qwt a technical plotting lib layered over top of Qt. I have 6 build of it, 2 with Qt 5.9.7 and 4 with Qt 5.12.0.


conan search Qwt/6.1.3@xxx/stable produces only two packages:

Existing packages for recipe Qwt/6.1.3@xxx/stable:

    Package_ID: 832b397c12e9e27c56ca8f1d8ff09894461eb87e
        [options]
            designer: False
            examples: False
            mathml: False
            opengl: True
            playground: False
            plot: True
            shared: False
            svg: True
            widgets: True
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 14
            os: Windows
        [requires]
            qt/5.9.7@bincrafters/stable:5cc40d1f5d8528baf331404d9f9e8691b935b4f4
        Outdated from recipe: False

    Package_ID: 8eeb6644528c8158d08ef52e1b2de925f3d947ff
        [options]
            designer: False
            examples: False
            mathml: False
            opengl: True
            playground: False
            plot: True
            shared: False
            svg: True
            widgets: True
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: Visual Studio
            compiler.runtime: MDd
            compiler.version: 14
            os: Windows
        [requires]
            qt/5.9.7@bincrafters/stable:950522cc1b5ee3ed1c4b00b6030183d2b17bfed5
        Outdated from recipe: False 

Showing only the Qt 5.9.7 builds.

This is what Artifactory shows

![image](https://user-images.githubusercontent.com/30176093/51110510-f00f2a80-17c6-11e9-80fb-60dc4b209b77.png)

**Comment by ShamanTcler** [comment]
Ok to early in the morning ... forgot the remote name.

Existing packages for recipe qxlsx/1.3.9@xxx/stable:

Existing recipe in remote 'CI-1':

    Package_ID: 1ac175aa3ba1e3439f278316ace86daca21db2f9
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 14
            os: Windows
        Outdated from recipe: False

    Package_ID: 1ccb67e3a5397340e70d0b7e8b1bbd2f635f4664
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: Visual Studio
            compiler.runtime: MDd
            compiler.version: 14
            os: Windows
        Outdated from recipe: False

    Package_ID: 27316d925c67fa77e3c96d1c3c3b8a4d4ff01ed8
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 14
            os: Windows
        Outdated from recipe: True

    Package_ID: 64610b9119f0250bc70d6a358de60346fccf3bfa
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 14
            os: Windows
        Outdated from recipe: True

    Package_ID: 6e8f46021bc94cbfe0357a22cc3dc75bb5c34bd3
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: Visual Studio
            compiler.runtime: MDd
            compiler.version: 14
            os: Windows
        Outdated from recipe: True

    Package_ID: 72897b2d1564d79796a2ad8b6bdc10f06d87941b
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: Visual Studio
            compiler.runtime: MDd
            compiler.version: 14
            os: Windows
        Outdated from recipe: True

So yes the all show, but no idea on the dependencies .... i.e. qt 5.9.7 or 5.12.0

**Comment by ShamanTcler** [comment]
Bigger picture ... say 25-30 libs with a 3-4 layer dep lib dependency i.e. Lib E depends on Lib D depends on C  .... you know the pattern.

Add two compilers and two OSs to the mix and checking for coverage is a nightmare.  I can only imagine BinCrafters has a similar problem.

**Comment by memsharded** [comment]
The html table has been fully re-vamped in Conan 2.0, I am closing this ticket as outdated, if the new html tables in 2.0 need some improvement, please create a new ticket to suggest it, thanks!
