### ISSUE TITLE
premake generator output 'conanbuildinfo.lua' consider rename

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#4286]
`.lua` is not an extension unique to premake, but instead a lua script file.  I am currently working on a generator for another build system which uses `.lua` files, and the problem is obvious.  I suggest `conanbuildinfo.premake.lua`.  That's the convention I'll be using for the new generator. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Make sense, but would be breaking, so assigning it for 2.0

**Comment by solvingj** [comment]
Ok, well at the same time, might as well also consider the following. 

The variable for preprocessor definitions has a rather unfortunate name: 

https://github.com/conan-io/conan/blob/develop/conans/client/generators/premake.py#L37

```
conan_cppdefines{dep} = {{{deps.defines}}}\n
conan_cppflags{dep} = {{{deps.cppflags}}}\n
```

These two variables mean the following: 

`conan_cppdefines` : "C Pre Processor Definitions"
`conan_cppflags` : "C Plus Plus Flags"

This variable"situation" is unspeakably bad for at least three reasons: 
1.  No other generator names the variable `cppdefines`.  The standard is simply `defines`. 
1. The conan variable it's being mapped from is `deps.defines`.  So, someone actually mapped the standard variable `defines` to this unique variable name: `cppdefines`.  
1. The two variables happen to be directly adjacent to each other, as if to draw attention to their terribly inconsistent and confusing names. It's funny in a way. 

Now, I think the `premake` generator was created and maintained by Conan team from day 1.  So, all of this together makes me wonder why this variable was named so uniquely.  I'm willing to believe there was some special reason `cppdefines` was used here instead of the normal `defines`.  However, I hope it was just a historical oversight that hasn't been corrected yet. 

I am aware of the unfortunate history of the naming of the variable `cpp_info.cppflags`, and that's something we'll all have to accept and live with long-term.   But, the `premake` generator is relatively new (as far as being an official generator), so hopefully we can rename the variable from `conan_cppdefines` to simply `conan_defines`  so this blemish doesn't have to stick around forever.

**Comment by danimtb** [comment]
I think we could change this as the generator was released as experimental https://docs.conan.io/en/latest/reference/generators/premake.html

So we could tackle both problems even before 2.0 @memsharded

**Comment by SSE4** [comment]
to summarize, I believe we should change:
1. `conanbuildinfo.lua` -> `conanbuildinfo.premake.lua`
2. `conan_cppdefines` -> `conan_defines`
3. `conan_cppflags` -> `conan_cxxflags`
as in GNU word, CPP usually stands for `C PreProcessor` instead of `C++`, and `CPPFLAGS` variable is used for C preprocessor flags instead of C++ compiler flags (which is `CXXFLAGS`). so, this may introduce lots of confusion for end users, let's use more obvious name.

**Comment by solvingj** [comment]
I support 1 and 2. 

3) Sadly,  I would leave `conan_cxxflags`, which is what we did in the `gnu_make` generator.  The conclusion there was that the user will be the one to map `CONAN_CPPFLAGS` -> `CXXFLAGS` variable in their consuming makefile.  I agreed that it was even more confusing to map the Conan variable `cppflags` to the build variable `cxxflags` implicitly.  It's certainly debatable, but given the history, it was the decision that was made in that one. 

There was some discussion about it here. 
https://github.com/conan-io/docs/pull/955#issuecomment-442754327

**Comment by SSE4** [comment]
@solvingj  you meant leave `conan_cppflags`, right?

**Comment by solvingj** [comment]
Yes, sorry, will correct my comment.

**Comment by memsharded** [comment]
As a reference, other generators, most noticeable cmake does this conversion:

```
cppflags (conanfile) -> CONAN_CXX_FLAGS (conanbuildinfo.cmake)
```

So it might make sense to be consistent.

**Comment by danimtb** [comment]
We have finally decided to change the mapping of ``cpp_info.cppflags``, see #4336
