### ISSUE TITLE
System proxy not used when only no_proxy_match is specified

### ISSUE THREAD

**Issue by ftechz** [conan-io/conan#4290]
It appears that the system proxy is not used when only `no_proxy_match` is specified `conan.conf`.

However, when I specify http proxy in `conan.conf` explicitly, or remove the entire `proxies` section it works as expected.

Can be reproduced in version 1.11.2

**Comment by ftechz** [comment]
This behavior is seen when using the conan `tools.get` function

**Comment by lasote** [comment]
Hi, as far as I have been able to experiment, the system proxy is always applied irrespective of the Conan configuration. But when you specify the proxies in the `conan.conf` the `no_proxy_match` is indeed able to exclude it for some configurations.
I would need more information to reproduce it, which operating system? Could you specify the concrete configuration urls and which url are you trying to download with `tools.get`? (You can fake some parts of the url for privacy but I want to check if there could be any mistake with the configuration)

**Comment by ftechz** [comment]
I am running on Windows in a corporate network where a proxy is required to connect to the internet. We run an instance of artifactory only accessible in the internal network so `no_proxy_match` is used as the hostname does not resolve through the proxy.

The Windows internet proxy, as well as `http_proxy`/`https_proxy` is set to `http://127.0.0.1:9000` which is the proxy authentication service.

`conan.conf` is configured with:
```
[proxies]
no_proxy_match = *.internaldomain.com
```

In the `source()` function in `conanfile.py`, I attempt to use `tools.get` to download and extract code from http://chacha20.insanecoding.org/chacha20-simple-1.0.tar.bz2, and I execute `conan source .` in the same directory to run it.

With the initial configuration, it fails to connect.
If I set `http_proxy = http://127.0.0.1:9000`, it connects.
If I remove the entire `[proxies]` section, it also connects.

**Comment by lasote** [comment]
The `no_proxy_match` only affects if you specify the `http_proxy` entry, otherwise, it should be useless.
So I think if you cannot configure the `no_proxy_match = *.internaldomain.com`  at the system level, you would need to specify the `http_proxy = http://127.0.0.1:9000` in the `conan.conf`.

**Comment by ftechz** [comment]
Intuitively, I thought it would partially apply them to the system proxy settings - in this case it would use the system proxy (if it exists) and respect the specified `no_proxy_match` value.

Specifying `http_proxy` in our `conan.conf` doesn't work for us because as we use `conan config install` to distribute these settings and some developers configure their proxies differently.

**Comment by lasote** [comment]
This is a python limitation, AFAIK it cannot change the behavior of the system proxies. I think the only way to do it is configuring the exclusions like `*.internaldomain.com` at the system level.

**Comment by ftechz** [comment]
I see, that's annoying then. However, should this configuration really disable the system proxy though? At most I'd think `no_proxy_match` just does nothing.

Is it possible to obtain the system proxy settings in python and override the provided fields?

**Comment by lasote** [comment]
I don't think so. Unless there is some environment variable we could alter to modify them. If you can modify the system proxies from a terminal, maybe we could do something.

**Comment by memsharded** [comment]
Trying to understand this issue, as a user-story:

If you distribute in conan.conf the following:

```
[proxies]
no_proxy_match = *.internaldomain.com
http_proxy = http://127.0.0.1:9000
```

It works, for all your use cases.
The problem is that some of your developers might change those values in the conan.conf? and then they will get overwritten their own values when they run ``conan config install``?

**Comment by ftechz** [comment]
@memsharded it is as you pointed out, I am not in a position to assume all developers have configured, or desire the proxy to `http://127.0.0.1:9000`.

Additionally, will be using in environments e.g. build CI, where the proxy is not necessary, but ideally use the same config package as it contains the common profiles.

**Comment by memsharded** [comment]
> it is as you pointed out, I am not in a position to assume all developers have configured, or desire the proxy to http://127.0.0.1:9000.

Interesting use case, from my experience is usually the opposite, when working in a team behind a proxy, it is kind of enforced to use some proxy settings.

> Additionally, will be using in environments e.g. build CI, where the proxy is not necessary, but ideally use the same config package as it contains the common profiles.

Just as a hint, you can have 2 origins for ``conan config install`` and install one after the other. So you can have one with the profiles, and proxy settings for developers, and a second one just for CI, that just defines the proxies new values. Developers with their own proxy config can have the same, and overwrite with their own config after installing the "team" one.

**Comment by lasote** [comment]
I'm not sure if we can provide any further solution to this. Feel free to comment if you consider, we could open it.
