### ISSUE TITLE
QNX Neutrino support

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#4294]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

there is some existing demand for QNX Neutrino support:
https://github.com/conan-community/community/issues/78
https://github.com/conan-io/conan/issues/2970

add an official support for QNX Neutrino operation system. it means, at least, the following:
- define new OS in `settings.yml` (name might be `QNX` or `Neutrino`)
- define OS versions, at least `6.5`, `6.6`, `7.0`
- define new compiler - `QCC`, and its versions (`4.2.2`, `5.4.0`)
- add standard libraries for QNX/QCC: `gpp` (GNU C++), `cpp` (Dinkum C+) and its variations (like Embedded Dinkum C++, Dinkum Abridged C++, etc)
- define GNU triplets for QNX cross-compiling (check `config.guess`)
- add required changes to the CMake helper (see https://cmake.org/cmake/help/v3.1/manual/cmake-toolchains.7.html#id9)

probably nice to have, but hard without access to the actual system - I doubt we will add it, as we mainly targeting cross-compiling from Windows/Linux/OSX to QNX, not running conan on QNX itself:
- add detection for QNX OS and compiler

/cc @jpovedano @Johnnyxy (as requestors)

**Comment by memsharded** [comment]
Merged, will be released in Conan 1.16
