### ISSUE TITLE
[Question] OS-specific dependencies

### ISSUE THREAD

**Issue by rambius** [conan-io/conan#4295]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hello,

We have an application that we build on Linux and Windows using cmake. We successfully ported the Linux build to conan and now we try to build it on Windows with conan. Some of the libraries the application depends on on Linux and that we put in conanfile.txt are not used on Windows. Is there a way to describe a dependency in conanfile.txt as a Linux-only or Windows-only? Is there any other way to solve that issue?

Thank you very much in advance.

Regards
rambius

**Comment by uilianries** [comment]
Hi @rambius!

Unfortunately is not possible to add conditionals in conaninfo.txt, but you could use conanfile.py instead. As conanfile.py is a python script, it has more advantages and you won't need to change any command. Conan docs offers a good explanation about conditional requirements: https://docs.conan.io/en/latest/mastering/conditional.html

**Comment by rambius** [comment]
Hello @uilianries,

Thank you for your answer, I will start transforming conanfile.txt to conanfile.py.

Regards
rambius
