### ISSUE TITLE
Cmake not finding static boost lib from conan package on Windows 

### ISSUE THREAD

**Issue by inbangsa** [conan-io/conan#4307]
Conan  Version 1.11.1 
Operating System : Windows 7
Compiler : Visual Studio 2017 Win64 
Generator Cmake 

I am trying to use the static Version of the boost library from channel 
"boost/1.64.0@conan/stable" 

I am able to successfully the Binaries of  for the static version. But the Consumer is not able to find  the Static libraries.  I ahve tried to provide Boost_ROOT, Boost_DIR, Bosst_INCLUDE_DIR, BOOST_LIBRARY_DIR and all other option but Cmake is not able to find the libraries. The issue is Binaries from the above mention channel named as  **boost_system.lib** whereas  find_package (boost Component system) Requires **libboost_system.lib** 

If  I manually Changes the name of libraries as   libboost_system.lib everything works fine. 

am I missing something ?

**Comment by inbangsa** [comment]
@jgsogo  
#134 seems very close to this issue.  the skpip_lib_rename is added for  boost 1.69.0 I am looking for help with boost 1.64.0. 

can you please help me to understand why we need to rename the lib in the first place.

**Comment by jgsogo** [comment]
I think that with the last comment from SSE4 it is already answered, if not, please open it again in the `conan-community` one. Thanks!
