### ISSUE TITLE
AutoToolsBuildEnvironment detect incorrect build under MSYS shell

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#4315]
using MSYS shell for cross-compiling, I've get incorrect build argument via `AutoToolsBuildEnvironment`, it sets the following: `--build=x86_64-msys_nt-10.0`
as result configure fails with the following error:
```
checking build system type... Invalid configuration `x86_64-msys_nt-10.0': system `10.0' not recognized
configure: error: /bin/sh build-aux/config.sub x86_64-msys_nt-10.0 failed
```

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by SSE4** [comment]
fix this after #4312 as it depends 
few places where it doesn't work as expected:
- `get_cross_building_settings` (uses `platforms.system()`, should use `detected_os` instead)
- `_get_host_build_target_flags` (uses `platforms.system()`, should use `detected_os` instead)

**Comment by jgsogo** [comment]
I think it makes sense to assign this one to @SSE4 too.

**Comment by SSE4** [comment]
@jgsogo solution is to use `detected_os` in `get_cross_building_settings`, but it introduces circular dependency between `oss.py` and `detect.py`. I think it's logical to move `detected_os` into `oss.py` as well, as it's pretty standalone, and `detected_architecture` is also in `oss.py`. is it okay to move it, or do you consider this to be a breaking change?

**Comment by jgsogo** [comment]
I shouldn't break anything, moving things around the repository is ok if we respect the documentation. For `tools` it is documented that they should be imported from `conans.tools`, we can import those functions to that module from `oss.py` or `detect.py` without the user noticing about it.
