### ISSUE TITLE
Version range aware search and remove commands

### ISSUE THREAD

**Issue by raffienficiaud** [conan-io/conan#4318]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I am using conan 1.9.0 on Windows 10.

I would be interested in having a better pattern handling in the `conan search` and `conan remove` commands, especially wrt. versions ranges:

Example:

    conan remove --force 'mypackage/[<2.2.2-13]@user/stable'

tells me that no package is found (there is clearly the `2.2.2-12`)

    conan remove 'mypackage/*@user/stable' -q "version < 2.2.2-13"

does not work neither. I also expect that `conan search` and `conan remove` behave the same wrt. versions.

Thanks!

**Comment by memsharded** [comment]
Right now, version ranges are only for resolution, but not for "navigation". The only possibility would be:

```
$ conan remove pkg/*@user/channel #Then manually select yes/no for each version
```

The ``-q "version < xxx"`` doesn't work because queries are only for searching binaries, by their configuration (settings, options).

This could be a "nice to have", but not very easy to implement.

**Comment by raffienficiaud** [comment]
Yes, this is a nice to have. Let me a bit explain the background. We have CI that runs isolated with `CONAN_USER_HOME`. This tends to grow over time. It would be nice that, when I update one of my dependencies, I just do a `conan remove mypackage/[<2.2.2-13]@user/stable` for all the previous versions of the package I just updated.

This would be a nice "nice to have" :)

**Comment by memsharded** [comment]
With Conan 2.0 new architecture, this became way easier to implement, was done in https://github.com/conan-io/conan/pull/14004 for next Conan 2.0.7.

Furthermore, it will not be for search(list in 2.0) and remove, but also can be used for download and upload commands.
