### ISSUE TITLE
[Jenkins Artifactory Plugin] huge buildinfo with unrelated packages returned by conanClient

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4319]
hi,

for some reason the `BuildInfo` object returned by the `ConanClient.run()` method contains references to a lot of unrelated Conan Packages as "modules". It seems these packages were also built on the same Jenkins slave but of course in different jobs.

This is a minimal example leading to the huge BuildInfo being published to the Artifactory:
```
def conanUploadClient = Artifactory.newConanClient()
def buildInfoTest = conanUploadClient.run command: "upload ${aliasID} -r ${remoteName}".toString()
artifactoryServer.publishBuildInfo buildInfoTest
```

Here is the "control experiment" leading to a BuildInfo without any associated Conan Packages/"modules" being published to the Artifactory.
```
def conanUploadClient = Artifactory.newConanClient()
def buildInfoTest = Artifactory.newBuildInfo()
artifactoryServer.publishBuildInfo buildInfoTest
```

Where could this wrong information from other builds come from?

Conan 1.8.2, Windows 10, Artifactory Plugin 2.16.2

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by petermbauer** [comment]
It seems the Jenkins Plugin reads in the entire `$CONAN_USER_HOME/conan_log.log` and puts it into the `BuildInfo` returned by the `ConanClient.run()`. I removed the file before the build and the info is ok now.

**Comment by danimtb** [comment]
Hi @petermbauer,

Thanks a lot for reporting and glad you find the solution to the issue. Do not hesitate to ask any other question 😄
