### ISSUE TITLE
Conan linking order

### ISSUE THREAD

**Issue by woyciech** [conan-io/conan#4330]
Hello.

I have two conan packages (package A and B) and both are dependent on the same library (libxml++). I'm trying to build application that is dependent on both conan packages. This is my conanfile.py

 def requirements(self):
      self.requires("packageA/1.0.5@demo/testing")        
      self.requires("packageB/1.0.6@demo/testing")

In this order, the linker works incorrectly (ex. "undefined reference to `Glib::ustring::~ustring()") . 
When I changed order, everything was fine.

 def requirements(self):
    self.requires("packageB/1.0.6@demo/testing")
    self.requires("packageA/1.0.5@demo/testing")  

Could you explain to me whether conan should improve the linking order itself? 
 
Thanks for all.

**Comment by trampen** [comment]
I have the same problem and realized that if conan would support circular dependency of libraries:
--start-group libraries --end-group
 as described in details here: `https://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking` then this issue would be resolved.

Regards, Marek

**Comment by uilianries** [comment]
Interesting, for now we need to specify the order list, otherwise will sort by name.

Maybe we could add an attribute in CMake and AutoToolsBuildEnvironment to inject `--start-group` and `--end-group` in the linker flags.

**Comment by memsharded** [comment]
Actually, no, the order of libraries is not ordered by name, but the order in which they are declared in ``self.cpp_info.libs = []`` is respected, and the merging of it of transitive dependencies should respect that order.

@woyciech Could you share the ``package_info()`` of both your packageA and packageB?
Is ``Glib::ustring::~ustring()`` a symbol from ``libxml++``? Where is it from?

**Comment by woyciech** [comment]
Hello.

At first thank you for reply. 

Glib :: ustring :: ~ ustring () is a symbol from libglibmm-2.4-dev, but xml ++ uses it.(https://developer.gnome.org/libxml++/stable/classxmlpp_1_1Element.html). 

### Package A
    def package_info(self):
        self.cpp_info.libs = ["liba.a"]

### Package B

    def package_info(self):
        if self.settings.arch == "armv7hf":
          pkg_config_path = "/usr/arm-linux-gnueabihf/lib/pkgconfig"
        else:
          pkg_config_path = "/usr/lib/pkgconfig/"

        self.cpp_info.libs = ["libxmlparser.a"]
        with tools.environment_append({"PKG_CONFIG_PATH": "%s" % pkg_config_path}):
           pkg_config_xmlpp = tools.PkgConfig("libxml++-2.6")
           self.cpp_info.cppflags = pkg_config_xmlpp.cflags
           self.cpp_info.libs += pkg_config_xmlpp.libs

           pkg_config_cryptopp = tools.PkgConfig("libcrypto++")
           self.cpp_info.cppflags += pkg_config_cryptopp.cflags
           self.cpp_info.libs += pkg_config_cryptopp.libs

**Comment by uilianries** [comment]
> Actually, no, the order of libraries is not ordered by name, but the order in which they are declared in self.cpp_info.libs = [] is respected, and the merging of it of transitive dependencies should respect that order

Sorry, I mean, when calling `tool.collect_libs()`

**Comment by memsharded** [comment]
Is it possible that ``package A`` also has some dependency (maybe implicit) to ``libglibmm-2.4``? That is not being declared, nor managed in ``package A``, so then the order might matter: who is throwing the "symbols not found" error, package A or B?

Also, it might be enlightning to copy here the output of the generated ``conanbuildinfo.cmake`` (or other, depending on your generator), specially the section that defines the libraries order (CONAN_LIBS), in both cases, requiring first A or requiring first B. The order of libraries should probably be different.

Looking forward your feedback, many thanks!

**Comment by memsharded** [comment]
Hi @woyciech 

Any news regarding this issue? Any feedback about the last comments?

**Comment by memsharded** [comment]
Hi!

Some time without response, I hope this is no longer an issue, so I am closing it. Please re-open or comment if necessary, thanks.
