### ISSUE TITLE
AutoToolsEnvironment uses --prefix incorrectly

### ISSUE THREAD

**Issue by jhol** [conan-io/conan#4334]
`AutoToolsEnvironment.configure()` uses the `--prefix` argument of AutoTools configure to set the prefix to `ConanFile.build_folder`, so that the files are stored there when `AutoToolsEnvironment.install()` is called.

However, this is a misuse of the `--prefix` argument. It has a powerful effect that defines the final installation location of the library. Many libraries use the path as the basis for many subsequent paths that are written into the library.

You can see the effect by running `strings`, `readelf` etc. on various `.so` files. In many projects the prefix gets written into the rpath for example.

The correct behaviour should be...
```
./configure --prefix=/ <....more flags>
make
make DESTDIR=/path/to/build_folder/
```

The prefix is set to `/`, and `DESTDIR` specifies the temporary staging location where these files should be installed, and should be converted to an Msys2 path if necessary i.e. `/c/Users/MyUser/.conan/...`

Some recipes may wish to specify a prefix of `/usr` or `/opt/project_name`, but the default should be `/`.

I have been tasked with replacing a proprietary python-based framework with conan. In the proprietary system, we initially used `--prefix=` in a similar way to Conan, but incurred the same set of problems mentioned in this issue. We used `DESTDIR=` successfully for a number of years.

**Comment by jhol** [comment]
Ok two corrections...

1. As you say it's `make install DESTDIR=/path/to/build_folder/`
2. It should be `--prefix=` not `--prefix=/`

As you suggest, we can work around the issue by specifying these things to the recipe. It would just be better not to have to.

**Comment by memsharded** [comment]
AutoToolsEnvironment is removed in 2.0, after being supeseded by ``AutotoolsDeps`` and ``AutotoolsToolchain`` in Conan 1.X. ``prefix`` definition now should be correct, as defined in ``layout()`` method.
