### ISSUE TITLE
Deprecation message for `cppinfo.cppflags`

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4337]
Introduce a new alias of `cppflags` named `cxxflags` and change the docs. If possible, show a deprecation message when cppflags is used.
The choice of `cppflags` meaning `c++flags` was not good, because `cppflags` means preprocessor flags and it is confusing.

**Comment by jgsogo** [comment]
May consider this check (raising an error) for the conan-center hook?, cc/ @danimtb
