### ISSUE TITLE
Upgrading iOS, watchOS, and tvOS in settings.yml

### ISSUE THREAD

**Issue by laundry-96** [conan-io/conan#4344]
I would like to add the new versions to settings.yml for iOS, watchOS, and tvOS devices.
This currently affects 1.11.2.

I attempted to compile with os.version=12.1 and os=iOS, spat back error that version is not supported.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi, thanks for open it. I agree it should be upgraded in the base `settings.yml`. Just in case it is useful for you and you didn't know it, you can use [conan config install](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install) and share a custom `settings.yml` in your team.

**Comment by lasote** [comment]
This was merged and released on Conan 1.12
