### ISSUE TITLE
CMake INSTALL(FILES ... DESTINATION ... RENAME newname.h) ignored

### ISSUE THREAD

**Issue by danielgindi** [conan-io/conan#4350]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.9.2 + Python 2.7

When the CMakeLists contains an `install` directive with a `RENAME`, the `RENAME` is ignored by conan:
`install (FILES ${CMAKE_BINARY_DIR}/cblas.gen.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR} RENAME cblas.h)`

(Original openblas code says `cblas.tmp`, but that is completely ignored by conan. After renaming to `cblas.gen.h` - it is copied to `include` folder of the package, but not renamed to `cblas.h`)

**Comment by danielgindi** [comment]
Conan does not treat the INSTALL directives, it's the `def package(self):` in the package file, that is responsible for copying it.
Closing.

**Comment by memsharded** [comment]
Hi @danielgindi 

Well, there is a ``cmake.install()`` method, that will call the cmake install. That is usually a way to avoid writing the ``package()`` method. 

- https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#install
- https://docs.conan.io/en/latest/howtos/cmake_install.html

I still prefer to write the logic of packaging in python in the ``package()`` method (rather than in CMakeLists.txt), but that might be useful too if the code is already there.

**Comment by danielgindi** [comment]
@memsharded Yes I just found out about it in the docs (RTFM...) but then it did not work. Trying to add proper MSVC support for openblas is not plain and simple and I just kept a few lines of package copy, along with some minor tweaks to the CMakeLists to put generated files in a subfolder, from which we can take them as-is.

If the `copy` method has a way of renaming the files as it copies them (maybe with a lambda or a replace pattern) - that would have been extremely helpful.

Thanks!

**Comment by memsharded** [comment]
I think you can perfectly use the ``os.rename`` from python, that is the good point of having conanfile.py recipes. Something like:

```python
import os

def package(self):
    self.copy(......)
    os.rename(os.path.join(self.package_folder, "myfile.txt"),
              os.path.join(self.package_folder, "othername.txt"))
```
Iterating ``self.package_folder`` to replace patterns should also be relatively simple, if you want to try and need help do not hesitate to ask :)

**Comment by danielgindi** [comment]
@memsharded I do not know a lot about the internals of conan - I assumed that the `copy` method keeps track of "copied" files so it can later package it. The simple way of course would be to simple copy/move/rename files manually, but if conan actually is trying to track the files then that would be a problem.

**Comment by memsharded** [comment]
The copy works just like a pattern base copy between the ``build_folder`` and the ``package_folder``. You can implement your ``package()`` method with bare ``shutil.copy`` between ``self.build_folder`` and ``self.package_folder``. The ``copy`` is actually the job of putting files in the final package folder. You might want to have a look to the conan local cache to learn the layout: go to your userhome/.conan/data/pkg/version/user/channel, and then navigate to the build/shaxxxx and package/shaxxxxx folders.

There is a manifest of files that are in the final package, but that is created after the ``package()`` method ends, so it is totally ok to rename files, create files, copy files, patch files, etc., in the ``package()`` method.
