### ISSUE TITLE
Meson: meson.build:1:0: ERROR:  prefix value 'None' must be an absolute path

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#4351]
[Meson](https://docs.conan.io/en/latest/reference/build_helpers/meson.html#meson-build-reference) build helper appears to be broken in case of test_package use case:
```
C:\Users\SSE4\AppData\Local\Programs\Python\Python36\lib\site-packages\conans\util\fallbacks.py:9: UserWarning: Provide the output argument explicitly to function 'conans.client.tools.win.vcvars_command'
  warnings.warn("Provide the output argument explicitly{}".format(fn_str))
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
The Meson build system
Version: 0.49.0
Source dir: C:\bincrafters\conan-meson_installer\test_package
Build dir: C:\bincrafters\conan-meson_installer\test_package\build\882726301a296ee1f7f1d98a3db2003150ea70a8\build
Build type: native build

meson.build:1:0: ERROR:  prefix value 'None' must be an absolute path

A full log can be found at C:\bincrafters\conan-meson_installer\test_package\build\882726301a296ee1f7f1d98a3db2003150ea70a8\build\meson-logs\meson-log.txt
ERROR: PROJECT: Error in build() method, line 16
        meson.configure(build_folder="build")
        ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC/Auxiliary/Build/vcvarsall.bat" amd64 && meson "C:\bincrafters\conan-meson_installer\test_package" "C:\bincrafters\conan-meson_installer\test_package\build\882726301a296ee1f7f1d98a3db2003150ea70a8\b
uild" --backend=ninja -Dprefix="None" -Dcpp_std="none" -Ddefault-library="shared" --buildtype=release
```
easy way to reproduce - use [conan-meson_installer](https://github.com/bincrafters/conan-meson_installer) repository.
comment line 14 at `test_package/conanfile.py` and run `conan create . bincrafters/testing`

bug seems to be inside `conans\client\build\meson.py`, line 31 - I bet test_package might not have `package_folder`

conan 1.11.2, python 3.6.5, Windows 10 x64

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, it could be a bug in the Meson build helper.

The CMake build helper only uses the ``prefix`` inside ``cmake.install()``:

```python
    def install(self, args=None, build_dir=None):
        if not self._conanfile.should_install:
            return
        mkdir(self._conanfile.package_folder)
```

but Meson in ``__init__.py``, and that should be avoided.
