### ISSUE TITLE
How to depend on multiple package configurations at the same time

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan#4357]
I am building an SDK that ships prebuilt libraries as well sources. All libraries are Conan packages. Let's assume my SDK contains a package A that comes in 3 different configurations. One SDK shall include and ship A in variants 1 and 2, another SDK shall only ship A3.

Is it possible that my SDK Conanfile depends on 2 variants of A at the same time?

**Comment by lasote** [comment]
I'm not sure I understand the question.
With the conan model, the consumers of your SDK (conan package) will specify a configuration (for example Windows 64bits Release), then, for all the dependencies of the SDK, the libraries (also conan packages) only the Windows 64 bits release configurations will be retrieved.

So, you would have 1 recipe (conanfile.py) for the SDK (specifying N requirements, one per library) and 1 recipe per library. For each recipe (conanfile.py) you can have multiple different configurations.

I don't understand why you need two variants at the same time, at first sight the answer is "no", but I would need to understand the use case to help you.

**Comment by rweickelt** [comment]
Thanks for your reply. I am using Conan for embedded MCUs (cross compiling). Library A might go into the final SDK package in source form and in prebuilt form for 3 different target architectures. I assume that the prebuilt files would not overlap or if they do, it doesn't matter. Because some other packages might also depend on A, but only a single target architecture, I wanted to publish 1 variant of A for each target architecture.

However, some SDK packages might want to collect multiple target variants of A. If it is not possible, I will just create one variant of A. Not optimal though.

**Comment by lasote** [comment]
Interesting. How are you going to manage the sources? Are you packaging them? How the consumer of the SDK will use them?
