### ISSUE TITLE
Conan_api incorrect caching. Create fresh instances for every call.

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#4363]
There are some components that are caching things: ConanFileLoader, Cache, PythonRequires. These components are instanced once in ConanAPI, but the api can be reused for multiple calls.

Consider:
- Invalidating mechanism, as in: https://github.com/conan-io/conan/pull/4362
- Creating fresh instances of all collaborators for every call.

Related to this: we might want to re-think how functional collaborators are passed around conan codebase.

**Comment by lasote** [comment]
Please, don't mix issues usage. The pr #4362 has to close something, I associated it with this issue. To assign the PR to an issue with "Whiteboard" is incompatible when only a few days left to release. I will use this issue as the reference one for the PR. If you feel that we need another engineering issue (this one is now a bug) to discuss, please open another engineering/white board one.
