### ISSUE TITLE
Reference position in the command line (argparse)

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4365]
You can read:

```
 conan remove [-h] [-b [BUILDS [BUILDS ...]]] [-f] [-o]
               [-p [PACKAGES [PACKAGES ...]]] [-q QUERY] [-r REMOTE] [-s]
               [-l]
               [pattern_or_reference]
```
But specifying the reference at the end is not working. 
Is there something we could do? At least the docs could be changed (if not overwritten automatically with the @danimtb script)

**Comment by danimtb** [comment]
This help is created by argparse itself and changes the parameter order should work in most cases other than using ``--`` to separate some arguments.

For example:
```
$ conan remove -p 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 gyp_installer/20181120@danimtb/testing
ERROR: Please specify a pattern to be removed ("*" for all)

$ conan remove -p 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 -- gyp_installer/20181120@danimtb/testing
Are you sure you want to delete "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" packages from 'gyp_installer/20181120@danimtb/testing' (yes/no):
```

My view is to make it work regardless of the order (in all the posible cases).

**Comment by memsharded** [comment]
This works if you always use "=" for arguments: ``conan install -r=remote -p=something  .``. This is one of the reasons I have suggested many times to try to use that syntax whenever possible in the documentation, it makes clearly explicit the logical groups of arguments.

**Comment by memsharded** [comment]
I have checked this:

- It is pretty challenging to change the order in which argparse prints the arguments, not worth the complexity
- There are no other arguments with ``nargs`` different than ``"?"``, so this should be fine now.

Closing this issue then.
