### ISSUE TITLE
collecting ".bc" files in collect_libs() for emscripten packages

### ISSUE THREAD

**Issue by suriya1611** [conan-io/conan#4366]
collect_libs currently collects only .lib,.so,.a,.dylib files. emscripten generates ```.bc``` files for libraries. 
It would be nice to have that too, or provide a parameter for pattern apart from default patterns.

**Comment by SSE4** [comment]
@suriya1611 good point, I'll integrate required changes int ohttps://github.com/conan-io/conan/pull/4346
