### ISSUE TITLE
[question] cmake-gui + xcode gives directory not found warning

### ISSUE THREAD

**Issue by izzyreal** [conan-io/conan#4367]
Installed Conan yesterday as per https://docs.conan.io/en/latest/installation.html using pip3

`pip3 freeze | grep conan` reveals that I'm using Conan v1.11.2

I'm using the attached `conanfile.txt` and `CMakeLists.txt` to build an Xcode project, using CMake 3.13.0 (the GUI version) in MacOS 10.14.2 (Mojave).

The project compiles fine in Xcode, but I'm getting these linker warnings:

`Directory not found for option '-L/Users/izmarverhage/.conan/data/mysql-connector-c/6.1.11/bincrafters/stable/package/f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2/lib/Release'`

`Directory not found for option '-L/Users/izmarverhage/.conan/data/sqlitecpp/2.2.0/bincrafters/stable/package/eff54a30e621872371b35c443bb1823ce03735e1/lib/Release'`

`Directory not found for option '-L/Users/izmarverhage/.conan/data/yaml-cpp/0.6.2/bincrafters/stable/package/853c4b61e2571e98cd7b854c1cda6bc111b8b32c/lib/Release'`

`Directory not found for option '-L/Users/izmarverhage/.conan/data/sqlite3/3.20.1/bincrafters/stable/package/890a529c8a31d00e48210fa0104b05caebc98018/lib/Release'`

* Is this due to a Conan bug or am I missing some setting, flag, etc. ?
* I recommend to add a simple option to run e.g. 'conan version' to display version info

[conanfile.txt](https://github.com/conan-io/conan/files/2786544/conanfile.txt)
[CMakeLists.txt](https://github.com/conan-io/conan/files/2786532/CMakeLists.txt)

**Comment by lasote** [comment]
About showing the version. ``conan --version``.
About the warnings, I tried to install the requirements and Conan is not generating these ending with `Release`, might it be an XCode adjustment? maybe suffixing the libdirs with the build type?

**Comment by izzyreal** [comment]
Ah the version argument works, was that added recently? I thought I'd tried all the obvious.

Sorry for not keeping track of this issue, I will try to investigate it asap.

**Comment by memsharded** [comment]
Closing this thread as inactive.

Also, all the build system integrations have been changed since then, so this would be outdated too.
