### ISSUE TITLE
[feature] support for creation/modification time queries in search and remove commands

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#4368]
Our team's workflow involves building and maintaining multiple historical versions of libraries built in-house that allows us to reproducibly debug problems with different versions that are in different stages in production.  As well, one project's release cycle and library certification process might move at a different velocity to another's.

We tag source in repo as we release, but this is not considered enough and currently we also store binaries for multiple versions, until space runs out on our build file storage system, at which point we perform a cull of the oldest binaries.

I'd like to be able to do the same with Conan packages in our internal Artifactory server.  Is there a query command that could be supplied to `conan search` or `conan remove` that would allow me to select based on modification date?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\mmaguir1>conan --version
Conan version 1.10.1

**Comment by lasote** [comment]
Hi Michael! 
From what I learn from other users, that task is more an Artifactory feature than a Conan feature.
Here is a blog post, a bit old but still valid talking about tasks to remove old artifacts:
https://jfrog.com/blog/advanced-cleanup-using-artifactory-query-language-aql/

The support team from Artifactory also suggested to take a look at this plugin:
https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup

And also to integrate it with the CLI:
https://jfrog.com/blog/aql-cli-a-match-made-in-heaven/

Let me know if it could work for you!

**Comment by michaelmaguire** [comment]
Thank you.  Looking into whether AQL access is something our Artifactory maintainers allow us mere mortals access to.
