### ISSUE TITLE
Question: how to create new multi-target formulas with cross-compile dependencies

### ISSUE THREAD

**Issue by zelid** [conan-io/conan#4369]
I'm going to use conan.io for C/C++ projects on macOS platform and cross compile from macOS to Windows using mingw-w64

"macOS to mingw-w64" cross-compilation is not the most popular one and there is a need to customize almost every conan package in order to support it and it's a normal thing considering the amount of possible combinations.

This is my first attempt to create a new conan.io package for Aria2 project:

```
from conans import ConanFile, CMake, tools, AutoToolsBuildEnvironment

class Aria2Conan(ConanFile):
    name = "aria2"
    version = "1.34.0"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    requires = "libxml2/2.9.8@bincrafters/stable", "libiconv/1.15@bincrafters/stable"

    _source_subfolder = "aria2-{}".format(version)

    def requirements(self):
        self.requires.add("libxml2/2.9.8@bincrafters/stable", private=False)
        self.requires.add("libiconv/1.15@bincrafters/stable", private=False)

    def source(self):
        tools.get(
            'https://github.com/aria2/aria2/releases/download/release-{0}/aria2-{0}.tar.xz'.format(self.version))

    def build(self):
        autotools = AutoToolsBuildEnvironment(self)
        args = [
        ]
        self.run(command="autoconf", cwd=self._source_subfolder)
        autotools.configure(configure_dir=self._source_subfolder, args=args)
        autotools.make()

    def package_info(self):
        self.cpp_info.libs = ["hello"]

```

It works fine on macOS using this commands:
```
conan install .
conan install . --build
conan build
```
and I get working `aria2c` binary having libxml2 and libiconv libraries installed for macOS

I've added `mac_to_win32` profile:

```
[env]
CC=/usr/local/bin/i686-w64-mingw32-gcc
CXX=/usr/local/bin/i686-w64-mingw32-g++
CONAN_CMAKE_GENERATOR=Unix Makefiles
LDFLAGS="-static -static-libstdc++"
WINDRES=x86_64-w64-mingw32-windres

[settings]
os=Windows
arch=x86
compiler=gcc
compiler.version=8.2
compiler.libcxx=libstdc++11
```

And trying to build the same `aria2` conan package using:
```
conan install . --profile ../mac_to_win32
conan install . --profile ../mac_to_win32 --build
conan build . --profile ../mac_to_win32
```
Now `libxml2/2.9.8@bincrafters/stable` and `libiconv/1.15@bincrafters/stable` conan dependencies don't know how to compile themself for my toolchain, so I'm going to create my own custom multiplatform conan packages for this libraries, let's say `libxml2/2.9.8@zelid/stable` and `libiconv/1.15@zelid/stable`. Here most questions I wasn't able to figure out from an official documentation start:

1. How can I make local machine be aware of my own customized version of dependencies (`libxml2/2.9.8@zelid/stable` and `libiconv/1.15@zelid/stable`)? 
The preferable workflow is to have custom dependencies in their own folders on a local machine, run a command to build and install for each platform locally and make dependencies available for other libraries locally.

2. Let's say I build from macOS for macOS and cross-compile for Windows using mingw. Should I create `build` directory for each platform and have sources unpacked once for all platforms? Are there any best practices how to name them? The main idea is to download sources once, unpack once, make build folder for each target platform and the same for all dependencies.

3. How to publish packages for each target platform locally?

These two questions are pretty basic but it was hard to figure it out fromat he official documentation which is oriented more on consuming conan packages  or building packages on mainstream platforms.

The current workflow is:

```
conan new zlib/1.2.11@zelid/dev -t

conan source .

mkdir build-macos && cd "$_"
conan install ..
conan build ..
conan package ..

mkdir build-mingw && cd "$_"
conan install .. --profile ../../mac_to_win32
conan build ..
conan package ..
```

**Comment by memsharded** [comment]
Quick feedback. Your ``requirements()`` method is redundant. The attribute ``requires`` already define them. Keep the method for complex cases as conditional requirements.

Also, you should probably be defining ``os_build=Macos`` and ``arch_build=x86_64`` in your profile too.

**Comment by danimtb** [comment]
hi @zelid,

As @memsharded pointed out you would need to declare those fields in your profile (some build helpers such as cmake are taking them into account) and fix the requirements issue.

Regarding your questions:

1. Conan has an internal cache that can be used to work with your packages locally, you don't have to upload them to a remote if you don't want to. Just do ``conan create conanfile.py user/channel`` to get the recipe exported to the cache and the package created for your profile

2. In local development commands (conan source, install, build...) follows same approach as done with the cache: Source folder can be reused as it contains the crossplatform source code, the installation folder is specific to your profile settings (so you would need one installation folder for each profile) and the build folder is also specific to the profile (it can be the same one as the installation). So yes, you would need to have a proper name for each of them with parameter ``--install-folder``/``--build-folder``.
However, it will be more convenient to use the ``conan create`` command as described above and let Conan manage the folders (you would need to do it anyway for consumption).

3. As described above, you don't need to publish anything. Just export/create whatever package you want to consume locally.

Here is a link to the local development flow that will help you understand the steps on developing a Conan package: https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html

Hope it helps! 😄
