### ISSUE TITLE
conan remove command ui

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4370]
The `conan remove` command is too difficult, I think we need to be much more deterministic.
E.g of weird behaviors:

- `conan remove zlib -p 12312312 -p 23333 -r remote` will remove these packages from any recipe matching "zlib"
- `conan remove zlib/1.2.11@conan/stable` will remove that reference or also `zlib/1.2.11@conan/stable2`?
- When using revisions, we don't want to allow removing all the package_id from all the recipe revisions, we force to specify a recipe revision. How can we know if the pattern is a reference or if we need to search for matching references? Very weak and complicated checks.

To improve:

- Avoid implicit "*" at the end of a pattern.
- Explicitly distinguish between a pattern and a reference.
- Don't allow to remove packages if it is a pattern.

Ideas (still bad ideas):

- Probably the way to distinguish between reference and pattern could be extended to other commands, like the path/reference?
- Consider a syntax to specify a pattern? Would be just valid to consider a pattern something with a "*" (never implicit at the end)

**Comment by memsharded** [comment]
Conan remove command has been completely upgraded in 2.0 cli, together with all other commands.
