### ISSUE TITLE
Question: Can we override cmake path?

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#4379]
Hi, quick question, can we override cmake path in a profile or something like that or we need to do the following in order to execute a cmake that is not on the path:

```
from conans import ConanFile, CMake

 class ExampleConan(ConanFile):
     ...

     def build(self):
         cmake = CMake(self)
         self.run('/my/custom/path/to/cmake "%s" %s' % (self.source_folder, cmake.command_line))
         self.run('/my/custom/path/to/cmake --build . %s' % cmake.build_config)
         self.run('/my/custom/path/to/cmake --build . --target install')

```
Thanks

**Comment by SSE4** [comment]
Hi @nesc1 
it was recently implemented in https://github.com/conan-io/conan/pull/4298 (docs https://github.com/conan-io/docs/pull/1025), and probably, will be available in next release. `CMake` class will accept new argument called `cmake_program`.

**Comment by nesc1** [comment]
Thanks @SSE4 , so for now i can assume that i need to use self.run('path/to/cmake ...') right?

There is no profile environment ([env]) like for example CONAN_CMAKE_GENERATOR to override the default generator?

**Comment by SSE4** [comment]
yes, I believe until next release, there is no variable to do this. you probably may try to change PATH, so it has custom CMake path before others.

**Comment by nesc1** [comment]
Thanks @SSE4 for the quick reply

(would not it be also useful to be possible to define it on a profile, something like CONAN_CMAKE_CMAKE... or something like that?)

**Comment by memsharded** [comment]
Have you tried to customize the PATH in the profile, or just play with the PATH system env-var?

Yes, the CONAN_CMAKE_PROGRAM will be possible to set it in a profile. That is merged, you might try to run from latest develop release in TestPyPI: 

$ pip install --index-url https://test.pypi.org/simple/ conan

**Comment by nesc1** [comment]
Thank you @memsharded, i will try both suggestions.
