### ISSUE TITLE
Accessing requirement-info like CONAN_BOOST_ROOT in conanfile.py

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#438]
When using conan in CMake I get certain variables like `CONAN_BOOST_ROOT` filled with where the requirements-package is located. For a project of mine I need access to this information directly in `conanfile.py`. I'm unable to find any info about this. Is this possible?

**Comment by memsharded** [comment]
Yes, you can have a look at: http://docs.conan.io/en/latest/integrations/other.html#use-conan-data-model-conanfile-py

Please tell me if this is what you need.

**Comment by monsdar** [comment]
This is exactly what I needed. Thanks a lot for all the good support you're giving!! Working with Conan is a blast so far!

**Comment by memsharded** [comment]
You are welcome! :) :) :)
