### ISSUE TITLE
linkage error only when creating a package dependant on protobuf

### ISSUE THREAD

**Issue by da2r-20** [conan-io/conan#4381]
Hi,
I have a project that have two dependancies.
see https://github.com/doronAtuar/benchmark
1. Eigen 3.3.5 - included using conan
2. Protobuf 2.6.1 - included and linked using find_package

```bash
conan install .
cmake .
make
```
works fine, but 
```bash
conan create . demo/demo
``` 
fails on linkage not being able to find any protobuf symbols.

When I include Eigen manually (setting the include paths manually to Eigen's include lib) everything works fine.

My env:
Ubuntu 16.04
Conan 1.11.1
Protobuf 2.6.1 installed with apt

----
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
Hi @doronAtuar !

Why do you need to use protobuf from apt instead to use bincrafters' package?

https://bintray.com/bincrafters/public-conan/protoc_installer%3Abincrafters
https://bintray.com/bincrafters/public-conan/protobuf%3Abincrafters

Bincrafters has a small note about their Protobuf package [here](https://bincrafters.readthedocs.io/en/latest/package_notes/protobuf.html)

Also, you need to add `CONAN_PKG::eigen` at https://github.com/doronAtuar/benchmark/blob/master/CMakeLists.txt#L29

You can obtain more information about cmake targets [here](https://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html#targets-approach)

Regards!

**Comment by memsharded** [comment]
Closing this ticket as inactive, never got a response from user. Please create new tickets for any further question or issue you might have, thanks!
