### ISSUE TITLE
difference between --build and --build=missing for conan install command

### ISSUE THREAD

**Issue by psvvardhan** [conan-io/conan#4383]
I am using 
- conan version 1.11.1
- Windows 10
- Artifactory Community Edition for C/C++ 6.5.13 rev 60513900

I have three packages, P1, P2 and P3.

- **P1**:
    -- Header only package
    -- Contains .h files
   
- **P2**
    -- Regular package 
    -- Has libraries

- **P3**
    -- requires P1 and P2

Below are the conan files written for P1, P2 and P3 (in that order).

**P1**
_conanfile.py is in includes folder_

```python
from conans import ConanFile, CMake, tools

class HeaderPkgConan(ConanFile):

    name = "hdr-pkg"

    version = "7.0"

    no_copy_source = True

    # No settings/options are necessary, this is header only

    exports_sources = "*"
```

**P2**
_conanfile.py is in libs folder_

```python
from conans import ConanFile, tools
    
class LibsConan(ConanFile):

    name = "libs"

    version = "7.0"

    settings = "os", "compiler", "build_type", "arch"

    def package(self):
        self.copy("*")

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)

    def deploy(self):
        self.copy("*")
```

**P3**

```python
from conans import ConanFile, tools

class devel(ConanFile):

    name = "devel"

    version = "7.0"

    settings = "os", "compiler", "build_type", "arch"

    requires = "libs/7.0@user/stable","hdr-pkg/7.0@user/devel"
```

And all three packages, P1, P2 and P3 are uploaded to Artifactory.

Coming to the issue: From another system, if I run,

`
conan install devel/7.0@user/devel -r remote --build
`

it downloads the headers but _**not**_ the libraries in libs to .conan/data/ folder. 

But if I run, 

`
conan install devel/7.0@user/devel -r remote --build=missing
`
it downloads both headers and libs.

What's the difference between --build and --build=missing? Documentation doesn't say more than "building from sources". 

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
> Currently, a project which is currently in artifactory, when I run "conan install --build=missing", it won't call build method at all. Is it supposed to work like that?

That is exactly how it is supposed to work:
- ``--build=missing`` If the binary is missing = it doesn't exist, then build it. It means, if a matching binary exists, then no ``build()`` will be called at all, because the binary is not missing, and it is not necessary to build it

- ``--build``. Means build always. It will build all packages in the dependency graph, no matter if a matching binary was already previously built, it will be rebuilt from sources.

**Comment by psvvardhan** [comment]
Thank you for quick response. However, for the issue I have mentioned in my first comment (https://github.com/conan-io/conan/issues/4383#issue-402992776) can you please let me know why they would work differently?

**Comment by memsharded** [comment]
Hi,

> Coming to the issue: From another system, if I run,
>`conan install devel/7.0@user/devel -r remote --build`
> it downloads the headers but _**not**_ the libraries in libs to .conan/data/ folder.

The headers, they are packaged together with the recipe, they are downloaded as part of the recipe, as they were ``exports_sources``. You don't build them. The libs, they are not downloaded, they are built, calling the ``build()`` method (which you don't have, so it is normal that no libs are there). You are not explaining how you are actually creating the libs, maybe with ``conan export-pkg``?

> But if I run,
> `conan install devel/7.0@user/devel -r remote --build=missing`
> it downloads both headers and libs.

This, only builds from sources, calling the ``build()`` method if the binaries do not exist, but if you already created the packages, they will be just downloaded.

**Comment by memsharded** [comment]
Hi @psvvardhan 

Was the last answer clear enough? Could we close this issue? Thanks!

**Comment by memsharded** [comment]
I think this question is properly answered, it can be closed, but please comment or re-open otherwise.
