### ISSUE TITLE
Incorrect json content generated by conan install command

### ISSUE THREAD

**Issue by Dmitriyev** [conan-io/conan#4384]
OS: ubuntu 16.04 x86/x64
Conan version: 1.10.0, 1.11.0

Hey!
 
I have a problem: There is dependency package (for example soci/3.2.3) that recipe i want to modify. After modifying (just adding empty line into recipe) and uploading into remote i'm trying to rebuild all dependencies has been modified. I run this command:
`conan install . -if debug --build outdated --json debug/packages.json --profile Profiles/conan/linux --update -s build_type=Debug -o ...`
and for release version:
`conan install . -if release --build outdated --json release/packages.json --profile Profiles/conan/linux --update -s build_type=RelWithDebInfo -o ...`
 profile looks as follows:
```
include(default)

[settings]
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=5
```
After rebuilding soci and installation of other dependencies i have two files named packages.json, but only _release/packages.json_ file contains information about soci/3.2.3. But if i run install command again  everything is ok. And more: if I delete folder .conan/data/soci/3.2.3 and rerun install command everything is ok again.

Thank you

**Comment by Dmitriyev** [comment]
Update:
Relevant in version 1.12.0

**Comment by Dmitriyev** [comment]
Answer me please

**Comment by danimtb** [comment]
Hi @Dmitriyev and sorry for the delay. I t is guite difficult to follow all the github issues 😥 

Reading your comment it is not clear to me what are you trying to achieve. Also, if you are consuming your soci recipe, it could happen that you have ir as a conditional requirement and that could be the reason you are not seeing the information there.

Anyway, I will try to reproduce it from my side with a test but it could be really really useful to have a minimal reproducible example.

Thanks!

**Comment by danimtb** [comment]
I wasn't able to reproduce the scenario described above due to lack of information. This issue was reported with Conan 1.12 so it might be fixed in newer versions. Please if you manage to reproduce the issue or a similar one, open a new issue with an update version of the Conan client.

Thanks!
