### ISSUE TITLE
MSBuild output warning

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#4393]
> C:/Users/memshared/conanws/conan/conans\util\fallbacks.py:9: UserWarning: Provide the output argument explicitly to function 'conans.client.tools.win.vcvars_command'
  warnings.warn("Provide the output argument explicitly{}".format(fn_str))

with 

```python
    def build(self):
        ms = MSBuild(self)
        ms.build("say.sln")
```

**Comment by lasote** [comment]
Is this still happening or already solved?

**Comment by jgsogo** [comment]
I think it should be already fixed, otherwise any test running `MSBuild.build()` should be failing...
