### ISSUE TITLE
Determining dependencies for multiple recipes

### ISSUE THREAD

**Issue by hebaishi** [conan-io/conan#4395]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

## Our setup
We have an in-house set up with a git repo that contains all our conan recipes.
Our recipe list is fairly large, so keeping all our recipes in one repo makes sense.
Our CI build goes through this list of recipes and builds them one at a time, and if everything was successful, we upload the packages to a conan-server that we maintain.

## Issue
What we've been struggling with is working out the order with which the recipes are to be built.
We would need a way of saying to conan - give me a list of all the `requirements` and `build_requirements` of this recipe, but don't attempt to build it.

This would effectively allow us to build a dependency graph that mirrors the one generated by conan, and traverse the graph to build our recipe list in the right order.

What happens currently (as of conan v1.11.2) is that when you run `conan info .` on a recipe, it attempts to fetch the requirements, and exits when the first one doesn't exist.

And what we do currently, is we maintain a separate list of dependencies, which is essentially a duplicate of what conan knows about. If we could just get this information from conan directly, we could avoid this duplication of data, and any bugs resulting from that. Firstly, is there something we're missing here? Is there something we can do today to get what we need? Otherwise, do you think this feature could be added to conan? We're happy to do the work if it will be accepted upstream. We just thought we'd mention it to you first before creating PRs.

**Comment by memsharded** [comment]
I think you could try running a ``conan export`` first over the whole list of packages. But without creating them. That doesn't take into account any order or relation between packages. 

Then, when all the packages exist on the cache, you can run ``conan info`` commands, (I guess you are specially interested in ``conan info --build-order``)

**Comment by hebaishi** [comment]
That seems to work pretty well. I removed our remote, and completed cleared out my local cache, then just ran `conan export` on all packages, and generated dependency graphs using `conan info -g out.dot .`. We can easily parse the dot file to build the full dependency graph. Thank you so much for your help! :+1:
