### ISSUE TITLE
Implement listing of editables

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#4397]
Have some way to list all the packages in the cache that are in editable mode.

**Comment by memsharded** [comment]
I have had a look at this issue, need more feedback:

- Should this be added to the ``conan search`` output? Right now editable packages do not exist for search, unless there was a previous package. Binary search might fail for editable packages
- If a ``conan link --list`` command is to be done (I think it is clean), then probably subcommands for link should be considered:
   - conan link add <path> <ref>
   - conan link remove <ref>
   - conan link list

**Comment by lasote** [comment]
This is approbed to be `conan editable list`

**Comment by memsharded** [comment]
Yes, this has been already implemented in https://github.com/conan-io/conan/pull/4481, will be closed with it.
