### ISSUE TITLE
[api] Only raw data through the conan_api border

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4398]
(We are just gathering ideas before taking this issue to the whiteboard and reach consensus)

We need to standardize the type of data that is being passed in and out the ConanAPI (`Conan` class), it looks like we should allow only _raw data_:
 * input arguments: 
     - strings
     - booleans
     - None 
     - Lists of any of the previous types
     - Use references as string, not `ConanFileReference` (#5233)
 * output arguments:
     - raise exceptions
     - dictionaries with raw types:
        + string
        + booleans
        + dates (iso format❓)
        + lists of those types

 * Also, the `conans.tools` should have the same allowed types through their interface.
 * `cwd` through `conan_api`: https://github.com/conan-io/conan/issues/4398#issuecomment-465063234

If I'm missing something, please let me know and I will add it to the list.

**Comment by memsharded** [comment]
I think both input and output can contain any python built-in like dicts, lists

**Comment by jgsogo** [comment]
I think that every output should be serializable to json without needing any helper, maybe the `conan_api` decorator could wrap the return into a dict like:

```txt
{
    "status": "<error/success-code>",
    "result": <the-returned-data>/<exception-message>
}
```

**Comment by jgsogo** [comment]
We need to investigate the methods where there is a `cwd` argument to handle relative paths inside the ConanAPI, it could make sense to **pass only absolute paths** through it and avoid this `cwd` param.

**Comment by memsharded** [comment]
I really like being able to use relative paths in the conan_api:
```bash
cwd = "C:/Users/myuser/myworksapce/myproject"
api = ...
api.install(build_folder="build", package_folder="pkg", cwd=cwd)
```
I wouldn't remove it, it is very convenient, simple to understand and use and there is no evidence that there is any problem or required maintenance with it. The idea is borrowed from the python ``subprocess.Popen`` api, that uses cwd as an argument.

**Comment by jgsogo** [comment]
_(We are just gathering ideas before taking this issue to the whiteboard and reach consensus)_

> The idea is borrowed from the python `subprocess.Popen` api, that uses cwd as an argument.

It is not the same use-case, calling the `subprocess.Popen` you are running a command line program and it is compulsory to provide a working directory (if it has to load a `dll` library, find some plugins,...), but once you are inside a program I find it quite important to get rid of relative paths as soon as possible. I think that the _abs -vs- rel paths through the API_ is something we all should talk about in this issue.

**Comment by memsharded** [comment]
Why? The system could perfectly use the current ``os.getcwd()`` and require to input the full path to the program. Then you would need to run a chdir before running, and to os.join to get the program abs path. But I think it would be much more inconvenient to use.

> but once you are inside a program I find it quite important to get rid of relative paths as soon as possible.

Exactly. The conan_api is the input to the "program", you get rid of relative paths as soon as possible **inside** the api, but you don't force the api users (or the program users in this case) to provide always absolute paths for every file and folder they will be using. That would be annoying for users, forcing them to do extra code, path joins, etc, for every api invocation.

**Comment by jgsogo** [comment]
Hooks, Jinja2 (in editable layout files https://github.com/conan-io/conan/pull/4812#pullrequestreview-218256468) use `reference` as the name for variables holding a `ref`.

We might use it also for the API if any `ConanFileReference` is crossing the boundary... but then we will have two different objects with the same name, the `ConanFileReference` and the string representation.

**Comment by memsharded** [comment]
The new PythonAPI for 2.0 is on the way, it will include some documented higher level model objects
