### ISSUE TITLE
question: access deps_cpp_info of build_requirements dependencies

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4401]
Hi there,
I have a question regarding the dependency informations ```deps_cpp_info```.

How can I access the ```deps_cpp_info``` from dependencies in the ```build_requirements``` function?

I tried accessing the ```deps_cpp_info``` from dependencies in the ```requirements``` function which works.
But accessing the ```deps_cpp_info``` from dependencies in the ```build_requirements``` function does not.
Getting a key error:
```
...
self.deps_cpp_info["DEPENDENCY_NAME"].rootpath
...
```
KeyError: 'DEPENDENCY_NAME'

Best regards

**Comment by memsharded** [comment]
Could you please check twice? I have checked, and it doesn't seem possible to have meaningful ``deps_cpp_info`` in the ``requirements()`` method either. I have just checked in a test:

```bash
ERROR: MyLib/0.1@lasote/stable: Error in requirements() method, line 16
	print self.deps_cpp_info["MyLibParent"]
	KeyError: 'MyLibParent'
```

The thing is: It is not possible to access ``deps_cpp_info`` at that stage, because the dependency graph has not been defined yet. You are exactly expanding it, but the dependencies are not there, it is impossible to get their ``cpp_info``.

**Comment by Johnnyxy** [comment]
No I mean I want to use the ```deps_cpp_info``` in the ```build``` or ```package``` function of some dependency which is declared in ```build_requirements```. :)

for example:
```python 
def build_requirements(self):
    self.requires("DEPENDENCY_NAME....)

def build(self):
    ...
    self.deps_cpp_info["DEPENDENCY_NAME"].rootpath
    ....
```

When declaring the dependency in ```requirements(self)``` then there is no error in ```build```.

**Comment by uilianries** [comment]
Hi @Johnnyxy !

You can't. I had the same problem many time ago: https://github.com/conan-io/conan/issues/2218

I would say to include a new option and access `deps_cpp_info` in the `build()`

Why do you need to get `deps_cpp_info` for `build_requirements` ?

**Comment by uilianries** [comment]
@Johnnyxy It's because `build_requirements`, as the name suggest, it's used only when you need build from sources. If you need to get some info from it when installing the package it's because your build requirement should be a regular requirement instead.

**Comment by Johnnyxy** [comment]
@uilianries I tried it with ```build``` also. I thought the ```deps_cpp_info``` is available at build-time, because there all build_requirements have to be resolved and available thus the dependency informations sould be available.

I will check "build_requirements" and "build" again tomorrow.

**Comment by memsharded** [comment]
I have added a couple of checks to one test:

```python
    def test_transitive(self):
        client = TestClient()
        mingw = """from conans import ConanFile
class Tool(ConanFile):
    def package_info(self):
        self.env_info.PATH.append("mymingwpath")
"""
        myprofile = """
[build_requires]
mingw/0.1@lasote/stable
"""
        gtest = """from conans import ConanFile
import os
class Gtest(ConanFile):
    def build(self):
        # Test https://github.com/conan-io/conan/issues/4401
        self.output.info("GTEST DEPS_CPP_INFO: %s" % self.deps_cpp_info["mingw"].rootpath)
        self.output.info("GTEST PATH FOR BUILD %s" % os.getenv("PATH"))
"""
        app = """from conans import ConanFile
import os
class App(ConanFile):
    build_requires = "gtest/0.1@lasote/stable"
    def build(self):
        self.output.info("APP DEPS_CPP_INFO: %s" % self.deps_cpp_info["mingw"].rootpath)
        self.output.info("APP PATH FOR BUILD %s" % os.getenv("PATH"))
"""
        client.save({CONANFILE: mingw})
        client.run("create . mingw/0.1@lasote/stable")
        client.save({CONANFILE: gtest})
        client.run("export . gtest/0.1@lasote/stable")
        client.save({CONANFILE: app,
                     "myprofile": myprofile})
        client.run("create . app/0.1@lasote/stable --build=missing -pr=myprofile")
        self.assertIn("app/0.1@lasote/stable: APP PATH FOR BUILD mymingwpath",
                      client.out)
        self.assertIn("gtest/0.1@lasote/stable: GTEST PATH FOR BUILD mymingwpath",
                      client.out)
        print client.out
```

it is working fine, no ``KeyError``, inside the ``build()`` method you can access the deps_cpp_info form the build requires too.

**Comment by Johnnyxy** [comment]
hi again :),
my situation is, that I have my big third party SDK. 

os_build/arch_build
----------------------------------------
The SDK has executables for development, libs, shared objects, etc.

os/arch
----------------------------------------
The SDK for Windows contains some debug/release .dll/.lib for C and C++.
The SDK for Linux, QNX, etc. contains some debug/release .so/.a for C and C++.

usage
----------------------------------------
The executables in the SDK have to run on my "os_build"/"arch_build".
The lib/dll/so/a in the SDK have to be linked against an specific "os"/"arch".
os_build/arch_build are not necessarily the same as os/arch (cross-compile).

approach
----------------------------------------
Now what I want is to "build" (downloads and unzips) the SDK with one recipe and "build" (copies) only the libs/sos/dlls/as for C or C++ for my specific target (os/arch).
I made a minimal example that shows the approach.

background
----------------------------------------
So I try to disect the SDK into a "use"-case as dev-tool and "link"-case as linking target.
The reason behind this is that the executables (like code generation) in the SDK needs some system properties (e.g. environment variables) which get set in the ```SDK_installer``` recipe but those environment variables interfere with the linking later on.
When I try to access the deps_cpp_info of ```SDK_installer``` in the ```SDK_libs``` recipe I get this error:
```
sdk_libs/1.0@test/test: Building your package in C:\Users\my_user\.conan\data\sdk_libs\1.0\test\test\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
sdk_libs/1.0@test/test: Copying sources to build folder
sdk_libs/1.0@test/test: Generator txt created conanbuildinfo.txt
sdk_libs/1.0@test/test: Calling build()
sdk_libs/1.0@test/test:
sdk_libs/1.0@test/test: ERROR: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' build failed
sdk_libs/1.0@test/test: WARN: Build folder C:\Users\my_user\.conan\data\sdk_libs\1.0\test\test\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Traceback (most recent call last):
  File "D:\python\lib\site-packages\conans\errors.py", line 24, in conanfile_exception_formatter
    yield
  File "D:\python\lib\site-packages\conans\client\installer.py", line 182, in _build_package
    self._conan_file.build()
  File "C:\Users\my_user\.conan\data\sdk_libs\1.0\test\test\export\conanfile.py", line 13, in build
    src_path = self.deps_cpp_info["sdk_installer"].rootpath
  File "D:\python\lib\site-packages\conans\model\build_info.py", line 195, in __getitem__
    return self._dependencies[item]
KeyError: 'sdk_installer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 8, in <module>
    builder.run()
  File "D:\python\lib\site-packages\cpt\packager.py", line 439, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "D:\python\lib\site-packages\cpt\packager.py", line 515, in run_builds
    r.run()
  File "D:\python\lib\site-packages\cpt\runner.py", line 86, in run
    test_folder=self._test_folder)
  File "D:\python\lib\site-packages\conans\client\conan_api.py", line 87, in wrapper
    return f(*args, **kwargs)
  File "D:\python\lib\site-packages\conans\client\conan_api.py", line 380, in create
    test_build_folder, test_folder, conanfile_path)
  File "D:\python\lib\site-packages\conans\client\cmd\create.py", line 53, in create
    keep_build=keep_build)
  File "D:\python\lib\site-packages\conans\client\manager.py", line 100, in install
    installer.install(deps_graph, keep_build)
  File "D:\python\lib\site-packages\conans\client\installer.py", line 275, in install
    self._build(nodes_by_level, deps_graph, keep_build, root_node, graph_info)
  File "D:\python\lib\site-packages\conans\client\installer.py", line 302, in _build
    self._handle_node_cache(node, package_ref, keep_build, processed_package_refs)
  File "D:\python\lib\site-packages\conans\client\installer.py", line 325, in _handle_node_cache
    self._build_package(node, package_ref, output, keep_build)
  File "D:\python\lib\site-packages\conans\client\installer.py", line 419, in _build_package
    raise exc
  File "D:\python\lib\site-packages\conans\client\installer.py", line 413, in _build_package
    builder.build()
  File "D:\python\lib\site-packages\conans\client\installer.py", line 113, in build
    self._build_package()
  File "D:\python\lib\site-packages\conans\client\installer.py", line 194, in _build_package
    raise exc
  File "D:\python\lib\site-packages\conans\client\installer.py", line 182, in _build_package
    self._conan_file.build()
  File "D:\python\Lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\python\lib\site-packages\conans\errors.py", line 30, in conanfile_exception_formatter
    raise ConanExceptionInUserConanfileMethod(msg)
conans.errors.ConanExceptionInUserConanfileMethod: sdk_libs/1.0@test/test: Error in build() method, line 13
        src_path = self.deps_cpp_info["sdk_installer"].rootpath
        KeyError: 'sdk_installer'
```

I made a minimal example to illustrate the error I get. The batch file could be run or just execute ```python build.py``` in the subfolders. I hope I made no silly mistake while writing the recipe :). Thx for any help.

[minimal_example.zip](https://github.com/conan-io/conan/files/2806715/minimal_example.zip)

**Comment by memsharded** [comment]
I think I got it :)

You are using ``self.requires()``, not ``self.build_requires()``, as described in the docs: https://docs.conan.io/en/latest/reference/conanfile/methods.html#build-requirements.

So please try something like:

```python
    def build_requirements(self):
        self.build_requires(f"sdk_installer/{self.version}@test/test")
```

**Comment by Johnnyxy** [comment]
Please do not say that was it. What a shame :.( . 

Thx for the help. :)

**Comment by memsharded** [comment]
No problem! :) :) :) :)

Cheers!
