### ISSUE TITLE
Conditional removal of a requirement and conan artefact indexing

### ISSUE THREAD

**Issue by HerbertKoelman** [conan-io/conan#4402]
When cross-compiling, some of platforms need to explicitly require OpenSSL and for some others I want to use the OS provided SSL library.

I've defined a conan option to indicate what behavior is requested. The option is set through a profile. After cross-compiling I end-up having two binary packages. One that says it requires OpenSSL. and another that do not (see `conan info` output at the bottom of this message).

Now when I use the TSI package (see the attached recipe) to build another package, it keeps requiring SSL !?
```
$ conan install conanfile.py -p no-ssl-profile
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=5
os=Linux
os_build=Linux
platform=emm-bt_x86-atom-e3826_poky
platform.sdkVersion=1.8
[options]
system_provided=True
[build_requires]
[env]

PROJECT: WARN: using system provided OpenSSL library.
PROJECT: Installing /home/dev/c++/TCT/cmake-build-emm-bt_x86-atom-e3826_poky_1.8/conanfile.py
Requirements
    CSC/1.17.0@rcs/stable from 'rcs_tots' - Cache
    MAL_TCT/2.1.7@rcs/stable from 'rcs_tots' - Cache
    OpenSSL/1.0.2l-M0@rcs/stable from 'rcs_oss' - Cache
    POCO/1.9.0-M2@rcs/stable from 'rcs_oss' - Cache
    TPL/9.3.0@rcs/stable from 'rcs_tots' - Cache
    TSI/31.0.1@rcs/stable from local cache - No remote
    libxml2/2.9.7@rcs/stable from 'rcs_oss' - Cache
Packages
    CSC/1.17.0@rcs/stable:32d1b8a295c0dcf6eb442b5478ec308a08aca680 - Cache
    MAL_TCT/2.1.7@rcs/stable:9bf1f02ba667da61377945a3025d3c643b91532b - Cache
    OpenSSL/1.0.2l-M0@rcs/stable:9bf1f02ba667da61377945a3025d3c643b91532b - Missing
    POCO/1.9.0-M2@rcs/stable:9bf1f02ba667da61377945a3025d3c643b91532b - Cache
    TPL/9.3.0@rcs/stable:4590f4ae256dfdd972ac5b5e8872f38a50fc6837 - Cache
    TSI/31.0.1@rcs/stable:8568bb20970bbd386fad356a7ebc40392050d951 - Missing
    libxml2/2.9.7@rcs/stable:4590f4ae256dfdd972ac5b5e8872f38a50fc6837 - Cache
```

> **FYI** I've supposed that conan is missing `TSI/31.0.1@rcs/stable` because conan believes it need OpenSSL.
_____

Here is what  `conan info TSI/31.0.1@rcs/stable -p no-ssl-profile` returns : 
```
TSI/31.0.1@rcs/stable
    ID: 00b0fe5f619eaf1ad456c4d1a1a18f11138d2c90
    BuildID: None
    Remote: None
    URL: ...
    License: ...
    Author: ...
    Topics: ...
    Recipe: Cache
    Binary: Cache
    Binary remote: None
    Creation date: 2019-01-28 17:49:02
    Required by:
        PROJECT
    Requires:
        POCO/1.9.0-M2@rcs/stable
        CSC/1.17.0@rcs/stable
```
With ssl `conan info TSI/31.0.1@rcs/stable -p with-ssl-profile`
```
TSI/31.0.1@rcs/stable
    ID: affe2cf89dfb77c09a3ba2130b8a9751d75eeb09
    BuildID: None
    Remote: None
    URL: ...
    License: ...
    Author: ...
    Topics: ...
    Recipe: Cache
    Binary: Cache
    Binary remote: None
    Creation date: 2019-01-28 17:49:02
    Required by:
        PROJECT
    Requires:
        POCO/1.9.0-M2@rcs/stable
        CSC/1.17.0@rcs/stable
        OpenSSL/1.0.2l-M0@rcs/stable
```
[conanfile.py.zip](https://github.com/conan-io/conan/files/2804047/conanfile.py.zip)

**Comment by memsharded** [comment]
Could it be that the OpenSSL library is being pulled at install time by Poco package? The original Poco package by default depends on the OpenSSL package.

Running the whole ``conan info conanfile.py`` (maybe with ``--graph=file.html``) will show the dependency graph, and you could check if someone else, different from TSI is pulling OpenSSL.

**Comment by HerbertKoelman** [comment]
I’m afraid not. 

This POCO Artefact is build and pushed on our local Conan server through a home made recipe. 

This recipe doesn’t declare requirements?!

A+

Herbert

**Comment by HerbertKoelman** [comment]
Thanks @memsharded, I'll implement the optimizations.

Concerning the paths, they absolute because my recipe is a template (conanfile.py.in) that is customized by my Conan CMake module when I run cmake. But I'll take a closer look at `export-pkg` to so if I can do better.

Here is the TSI conanfile I use to package my binaries [tsi-conanfile.py.zip](https://github.com/conan-io/conan/files/2806764/tsi-conanfile.py.zip).

By the way, is there a way to remove requirements in a conanfile.py ?

**Comment by HerbertKoelman** [comment]
To investigate this matter I've remove all reqirements but the TSI one. And it still searches for OpenSSL.

```
$ conan info TSI/31.0.1@rcs/stable -p emm-bt_x86-atom-e3826_poky_1.8
TSI/31.0.1@rcs/stable: WARN: using system provided OpenSSL library.
CSC/1.17.0@rcs/stable
    ID: 32d1b8a295c0dcf6eb442b5478ec308a08aca680
    BuildID: None
    Remote: ...
    URL: ...
    License: ...
    Recipe: Cache
    Binary: Cache
    Binary remote: rcs_tots
    Creation date: 2018-12-10 16:15:50
    Required by:
        TSI/31.0.1@rcs/stable
POCO/1.9.0-M2@rcs/stable
    ID: 9bf1f02ba667da61377945a3025d3c643b91532b
    BuildID: None
    Remote: ...
    URL: http://rcstfscode:8080/tfs/TransCity-Equipments/Open-Source-Softwares/_git/POCO
    License: ...
    Author: eqpt-conan-packager
    Recipe: Cache
    Binary: Cache
    Binary remote: rcs_oss
    Creation date: 2018-12-20 17:45:04
    Required by:
        TSI/31.0.1@rcs/stable
TSI/31.0.1@rcs/stable
    ID: 00b0fe5f619eaf1ad456c4d1a1a18f11138d2c90
    BuildID: None
    Remote: ...
    URL: ...
    License: ...
    Author: ...
    Topics: c++, CXX, interface, ticketing
    Recipe: Cache
    Binary: Cache
    Binary remote: rcs_sandbox
    Creation date: 2019-01-28 17:49:02
    Required by:
        PROJECT
    Requires:
        POCO/1.9.0-M2@rcs/stable
        CSC/1.17.0@rcs/stable
```

As one can see, no OpenSSL. Yet when I run `conan install` I get:
```
conan install cmake-build-emm-bt_x86-atom-e3826_poky_1.8/conanfile.py --profile emm-bt_x86-atom-e3826_poky_1.8
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=5
os=Linux
os_build=Linux
platform=emm-bt_x86-atom-e3826_poky
platform.sdkVersion=1.8
[options]
system_provided=True
[build_requires]
[env]

PROJECT: WARN: using system provided OpenSSL library.
PROJECT: WARN: exiting requirements method, requires=
TSI/31.0.1@rcs/stable
PROJECT: Installing /home/dev/c++/TCT/cmake-build-emm-bt_x86-atom-e3826_poky_1.8/conanfile.py
Requirements
    CSC/1.17.0@rcs/stable from 'rcs_tots' - Cache
    OpenSSL/1.0.2l-M0@rcs/stable from 'rcs_oss' - Cache
    POCO/1.9.0-M2@rcs/stable from 'rcs_oss' - Cache
    TSI/31.0.1@rcs/stable from 'rcs_sandbox' - Cache
Packages
    CSC/1.17.0@rcs/stable:32d1b8a295c0dcf6eb442b5478ec308a08aca680 - Cache
    OpenSSL/1.0.2l-M0@rcs/stable:9bf1f02ba667da61377945a3025d3c643b91532b - Missing
    POCO/1.9.0-M2@rcs/stable:9bf1f02ba667da61377945a3025d3c643b91532b - Cache
    TSI/31.0.1@rcs/stable:8568bb20970bbd386fad356a7ebc40392050d951 - Missing

Cross-build from 'Linux:x86_64' to 'Linux:x86'
CSC/1.17.0@rcs/stable: Already installed!
OpenSSL/1.0.2l-M0@rcs/stable: WARN: Can't find a 'OpenSSL/1.0.2l-M0@rcs/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86, os=Linux, platform=emm-bt_x86-atom-e3826_poky, platform.sdkVersion=1.8
- Options:
- Dependencies:
- Package ID: 9bf1f02ba667da61377945a3025d3c643b91532b

ERROR: Missing prebuilt package for 'OpenSSL/1.0.2l-M0@rcs/stable'
Try to build it from sources with "--build OpenSSL"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

**Comment by HerbertKoelman** [comment]
( by the way the set option mechanism will be shifted into a generator, what you see is just a quick win)

**Comment by memsharded** [comment]
Oh! Now I think I see the issue: options are defined per package. It is necessary to explicitly define the options that are not the default ones. Using the bare ``[options] system_provided=True`` only affects the end consumer (which is a recipe that might not have name at all, thus the reason it doesnt have namespace``.

Otherwise, you need to explicitly define options of every package:
```
[options]
TSI:system_provided=True
Other:system_provided=True
```

You have wildcards/patterns you can use (both in profiles and in command line):

```
[options]
*:system_provided=True
```

You might be interested in the discussion here: https://docs.conan.io/en/latest/creating_packages/getting_started.html#settings-vs-options

And note the command line, using namespaces and wildcards too: https://docs.conan.io/en/latest/reference/commands/consumer/install.html#options

BTW, ``self.requires`` inside the ``requirements()`` method, is an OrderedDict, if you want to remove something that was added in the class-level ``requires``, you could ``del`` or ``pop`` it by its package name.

Please try the above and tell me. Thanks!"

**Comment by HerbertKoelman** [comment]
Many thanks for your help. I've implemented your python suggestions and they work fine too.

**Comment by memsharded** [comment]
> @memsharded GIVE THE MAN A CIGAR. 

:D :D :D :D Thanks!! Glad that it is solved!

BTW, in case you haven't join the #conan slack channel in the CppLang, there is an amazing community there too, very helpful, and it is useful for discussing ideas too. Some of the Conan team also hang around there when possible.

Cheers!
