### ISSUE TITLE
Performance of dependency resolution of conan in artifactory

### ISSUE THREAD

**Issue by aacebedo** [conan-io/conan#4404]
Conan version: 1.9.1
Artifacftory version: 5.11

Hi all

I am experiencing heavy performance issues when using conan with artifactory pro.
The dependency resolution mechanism is quite slow (500ms to 1 sec per dependencies)
When I check the CPU usage on the artifactory side I see that its java process is heavily hammering it.  As we parallelize the compilation processes this behavior strongly decreases the speed of our workflow. 
The CPU is a Xeon with 10 cores so I don't think that the bottleneck is here.

The conan repositories we are using contain roughly 13000 versions of our different libraries (combining all versions of all packages of all repositories). Is there anything I can do to accelerate the process ? 

Regards

**Comment by memsharded** [comment]
Hi @aacebedo 

Are you heavily using version-ranges? The version-ranges resolution does a "search" for each one, and that is the thing that might be a bit slow.

Maybe enabling the conan logs might help to see what is happening: https://docs.conan.io/en/latest/mastering/logging.html

On the Artifactory side, is it a Pro instance, with other package types, and other package types are resolving fast? Maybe that deserves a ticket to Artifactory support.

**Comment by fourbft** [comment]
Looks like we are facing a similar problem. During the last four weeks or so, we have been experiencing a severe drop in performance from our Artifactory server. (It's an Artifactory Pro installation).
A conan install of a concrete version of a trivial package (size of some 20 kB) from the affected artifact repository currently takes over 7 seconds. On the same Artifactory server, we have a second Conan artifact repository (with much fewer packages) which is not affected. Same install of a small package from there is around 0.5 seconds. So the performance of Conan repositories in Artifactory seems to deteriorate with the size of the Artifact Repositories.
Here the data: 
Affected Artifact Repository: 292757 / 381.53 GB 
Still well performing Artifact Repository (on the same Artifactory instance): 1993 / 1.54 GB

(The first number is the number of artifacts, i. e. Conan packages in this case).

Is there anything we can do about this problem, other than waiting for a fix from Artifactory? Rebuild the index or some such? Would deleting / cleaning up packages help?

**Comment by fourbft** [comment]
Just some additions: We are running Artifactory Professional 6.15.0 rev 61500900 as a docker container (together with the nginx and mongo containers). The container has 12 CPU cores and 32 GB of RAM (of which 5.7 GB are used and 4 GB are reported to be free (rest is buffer/cache)). Swap usage is minimal (156 MB of 8GB available). But as mentioned above, the problem does not seem to be performance of the Artifactory in general, as only one Conan Artifact Repository (the big one) on that server is affected.

**Comment by memsharded** [comment]
Please report also @fourbft 

- The Conan client version (just in case)
- If it is the same delays in any client OS, Windows, Linux? Is it definitely server side?

**Comment by fourbft** [comment]
- Affected client versions at least 1.21.0, 1.20.2 and 1.17.0.
- Yes, windows and linux clients affected.
- Yes, 99% sure it's server side. Reasons:
   - Even from a client sitting on the same machine as the Artifactory server (second docker container on the same machine that runs the Artifactory server docker container), the delay is there.
   - From an affected remote client, when installing a conan package from a second Conan Artifact Repository (with only a few packages) served by the same Artifactory server, the performance issue is gone.
    - Deleting old packages on the server mitigates the problem. (Deleting 6000 packages of 15000 from the affected Conan artifact repository decreased the installation time of one and the same trivial package from 7.5s to 4.5s.)

**Comment by monsdar** [comment]
Reported to JFRog JIRA bugtracker: https://www.jfrog.com/jira/browse/RTFACT-21530

**Comment by memsharded** [comment]
This was fixed some time ago in the server side:
- conan search is much faster now, as it caches an index now (besides the creation of that index should also be much faster too)
- As a result, resolution of version ranges is also much faster too.

Closing this as solved, thanks!
