### ISSUE TITLE
Android ndk standalone toolchain warnings

### ISSUE THREAD

**Issue by BillHoo** [conan-io/conan#4421]
To help us debug your issue please explain:

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.11.2
Android Studio: 3.3
NDK: AS bundled

Hi Conan team,

I've followed the official docs about [Cross Platform Build for android](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html?highlight=android#cross-building-with-conan), it worked well.

But I'm getting WARNINGS when I generate the standalone toolchain:

> WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

>    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm --api 21 --install-dir toolchain
>    $ toolchain/bin/clang++ src.cpp

> Instead use:

>    $ $NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang++ src.cpp

is it dangerous? or should conan update its document to follow up latest NDK release?

I'm using the latest Android Studio 3.3 with NDK bundle.

**Comment by memsharded** [comment]
Hi @BillHoo 

Not sure about this, I have asked for help of @SSE4 and @uilianries, lets see if they can have a look. Thanks!

**Comment by SSE4** [comment]
hi @BillHoo 
these warnings are completely harmless.
newer Android NDK versions do not require standalone toolchain generation, so you can skip mentioned step, and just use prebuilt standalone toolchain from NDK as noted.
but for compatibility with older NDK versions, conan documentation still describes this step.

**Comment by BillHoo** [comment]
gotcha, thanks buddy.

**Comment by memsharded** [comment]
Thanks for the feedback! Could we consider this question solved and close the issue?

**Comment by BillHoo** [comment]
yes please. thank you
