### ISSUE TITLE
Editables minor issues

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#4422]
I found some usability issues (will post here more in that case):

1. Conan keeps track of packages in editable mode using an *editable_packages* file with JSON format in the Conan cache. As other files like *registry.json*, this files should be *editable_packages.json* as format may not change.

2. Conan does not show editable packages in a search when a package is not in editable mode. Folders are not created in the cache (maybe not needed).

3. The information after conan link command is incomplete: ``Reference 'say/0.1@user/testing' linked to directory ''``

**Comment by lasote** [comment]
NEW: We want to enable the mix of the info from the cpp_info with the layout information
