### ISSUE TITLE
Use jinja2 templates for editable layouts

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#4424]
Syntax in editable layouts are currently using placeholders like ``{settings.build_type}`` to make some conditional logic regarding folder paths.

We knew it has some limitations specially with placeholder like ``{options.shared}``, that will replace the value with a ``True``/``False`` instead of a useful value.

We evaluated the following:
- Inline evaluation of python code
- Evaluation of field headers like ``[includedirs#settings.build_type==True]``
- Python syntax in *layout.py* implementing a ``package_info()``
- Jinja2 templating

And decided that jinja2 is a fairly common orthogonal language used in a lot of tools, syntax is well documented and contemplates many conditional scenarios. Also this should be quite easy to implement.

The information available in this jinja2 templates should be ``options`` and ``settings``.

**Comment by memsharded** [comment]
Changed complexity, I think using jinja template engine for this should be relatively easy.
