### ISSUE TITLE
conan install version in reference doesn't respect least significant patch number

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#4427]
I see that conan supports ```conan search``` using wildcards, e.g. https://github.com/conan-io/conan/issues/1485

```
conan search -r conan-transit zlib/*@lasote/stable*
```

Does it also support wildcards in the ```conan install``` command?

e.g. "Please install the latest version of this package":

```
$ conan install -u mylib/*@USER/stable*
ERROR: Conanfile not found at E:\DevelopBP\morpheus\conan\mylib\mylib\*@USER\stable*
```

If it doesn't support this, could it be added as a feature?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\mmaguir1>conan --version
Conan version 1.10.1

**Comment by memsharded** [comment]
Hi @michaelmaguire 

Yes, it is possible, specifying it as a version range:

```bash
$ conan install zlib/[*]@conan/stable
```

Please try it and tell me, thanks!

**Comment by michaelmaguire** [comment]
The feedback was:

> It works, although instead of installing the latest package, it installs the oldest one, e.g.
> 
> conan install -u bqlAct/[*]@PORT/stable
> 
> installs version 3.2.2.0 instead of 3.6.6.8

**Comment by memsharded** [comment]
What would be the output of the ``conan search bqlAct``? Is it possible that there is some alias or something that points to 3.2.2.0?

I will run a couple of tests here.

**Comment by quiandy** [comment]
$ conan search bqlAct
Existing package recipes:

bqlAct/3.2.2.0@PORT/stable
bqlAct/3.6.6.6@PORT/stable
bqlAct/3.6.6.6@achiari1/unstable
bqlAct/3.6.6.7@PORT/stable
bqlAct/3.6.6.7@achiari1/stable
bqlAct/3.6.6.8@PORT/stable

And this is the output when running install:

$ conan install -u bqlAct/[*]@PORT/stable
Configuration:
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=14
compiler.toolset=v140_xp
build_type=Release
[options]
[build_requires]
[env]

Version range '*' required by 'None' resolved to 'bqlAct/3.2.2.0@PORT/stable'
bqlAct/3.2.2.0@PORT/stable: Not found in local cache, looking in remotes...
bqlAct/3.2.2.0@PORT/stable: Trying with 'bloomberg_artifactory'...
[...]

**Comment by quiandy** [comment]
To make things easier I cleaned up the local all-together; now it's getting weirder, it's like fetching the second oldest package; I still can't understand however what mechanism is being triggered here. Maybe it's something related to our local setup.

achiari1@nxdgu-rr-002  /e/DevelopBP/achiari1/conan/bqlAct
$ conan search bqlAct
There are no packages matching the 'bqlAct' pattern

achiari1@nxdgu-rr-002  /e/DevelopBP/achiari1/conan/bqlAct
$ conan search bqlAct -r bloomberg_artifactory_nx_stable
Existing package recipes:

bqlAct/3.2.2.0@PORT/stable
bqlAct/3.6.6.6@PORT/stable
bqlAct/3.6.6.7@PORT/stable
bqlAct/3.6.6.8@PORT/stable

achiari1@nxdgu-rr-002  /e/DevelopBP/achiari1/conan/bqlAct
$ conan install -u bqlAct/[*]@PORT/stable -r bloomberg_artifactory_nx_stable
Configuration: [...]
**Version range '*' required by 'None' resolved to 'bqlAct/3.6.6.6@PORT/stable'**
bqlAct/3.6.6.6@PORT/stable: Not found, retrieving from server 'bloomberg_artifactory_nx_stable'
bqlAct/3.6.6.6@PORT/stable: Trying with 'bloomberg_artifactory_nx_stable'...
Downloading conanmanifest.txt

**Comment by quiandy** [comment]
Got it. It's not easy for us to jump into semver specification, but we'll keep that in mind at this point.

**Comment by michaelmaguire** [comment]
I seem to be running into the same issue not with wildcard searches, but with updates to libraries that have been re-released with a patch version.

e.g. I was unable to force an upgrade to use:

```
avro-cpp/1.8.2.7@PORT/stable
```

because my stable remote repository also had:

```
avro-cpp/1.8.2.6@PORT/stable
```

So the command:

```
$ conan install .. -u -r=bloomberg_artifactory_nx_stable
```

wouldn't pick up the new .7 patch.

The only way I seem to be able to get .7 to be loaded was to delete .6 from the repo, which is less than ideal.

**Comment by memsharded** [comment]
Closing this ticket as outdated.

Also, Conan 2.0 also now natively supports versions and version ranges with any number of digits. Also, don't hesitate to open new tickets if you have an further question
