### ISSUE TITLE
Conan should NOT crash if a hook fails to load

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4433]
If a hook fails to load it should print an error message, but Conan should continue running (IMO). There can be hooks importing non-installed packages.

So I'm suggesting changing the [`HookManager::load_hook`](https://github.com/conan-io/conan/blob/a503f3c283124d678d751fe79215a0f78aaba7ba/conans/client/hook_manager.py#L65) function to write an error and let the execution continue:

```python
        except Exception as e:
            self.output.error("Error loading hook '%s': %s" % (hook_path, str(e)))
``` 

The output will be something like (I'm not sure if we should add the traceback or not):

```
ERROR: Error loading hook '/Users/jgsogo/dev/conan/conan-hooks/hooks/binary-linter.py': Unable to load Hook in /Users/jgsogo/dev/conan/conan-hooks/hooks/binary-linter.py
ModuleNotFoundError: No module named 'lief'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jgsogo/dev/conan/conan/conans/client/hook_manager.py", line 96, in _load_module_from_file
    loaded = __import__(filename)
  File "/Users/jgsogo/dev/conan/conan-hooks/hooks/binary-linter.py", line 13, in <module>
    "lief is required to run 'binary-linter' hook, install it using `pip install lief`")
conans.errors.ConanException: lief is required to run 'binary-linter' hook, install it using `pip install lief`

Exporting package recipe
...

```

This is need even if the hook itself handles the `ImportError` and raises a proper error message (https://github.com/conan-io/hooks/issues/7#issuecomment-458505345).

**Comment by jgsogo** [comment]
What do you think about it cc/ @conan-io/barbarians? Depending on your feedback I will tag it.

**Comment by memsharded** [comment]
Yes, I think incorrect loading of hooks should raise early, not just print.

**Comment by uilianries** [comment]
> If a hook fails to load it should print an error message, but Conan should continue running (IMO)

I agree. Hooks are cool, but they are an extra, people are interested in install,create packages. However, we could create a new env var forcing the hook manager to raises an exception, maybe `CONAN_HOOK_MANAGER_ERROR`

**Comment by memsharded** [comment]
I don't get it. In which scenario you want to declare that you are using a hook, and let the system (like in CI) finish successfully just with some printed messages that nobody is going to read?

**Comment by jgsogo** [comment]
I've changed my mind since I opened this issue (I was reviewing the binary-linter one which requires `lief`). As **you have to activate the hook explicitlty** it makes sense to raise if you are not able to import/run the hook.

Sorry for the noise. I will close it, but @uilianries, feel free to comment in it if you feel like we shouldn0t raise.

**Comment by uilianries** [comment]
on my machine I don't care if some hook is broken, because maybe I only want to install a package or even play with Conan. However, CI environments are serious, there I could chose which hooks must run and break.

**Comment by uilianries** [comment]
> As you have to activate the hook explicitlty it makes sense to raise

Hm, that's true, I forgot this point. So, yes, if you need to activate, it makes sense raise an exception.
