### ISSUE TITLE
Format Conan according PEP8

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4434]
Hello!

Since PEP8 is a "requirement" for Conan, why not run some code formatter tool, push into develop branch and break all developers?

![format all code](https://user-images.githubusercontent.com/4870173/52070486-16bfb600-2568-11e9-9c8f-f97caf0e9ed0.gif)

Even we formatting all code once, on a next PR we will need to check to format again. We could use Code Climate to check it, as discussed on #3558. However, the developer will need to format the code anyway, so we have some possible options:

- Provide config files to be used by any format tool
- Run a tool automatically over develop branch when a PR is merged

The first option is the common one, but I'm afraid of new contributors, nobody wants to be blocked because of a bad format in the code. So we have the second option, trigger a bot to format our code base after to merge a PR.

I've used yapf since 2yrs ago, but there are other options. Here is an article about most popular Python auto formatters (autopep8, yapf, black):
https://medium.com/3yourmind/auto-formatters-for-python-8925065f9505

Related Issue: #3558

Conan Version: 1.12.0
Operating System: Any

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
We have to discuss this. In case we run a code formatter we would need to do it very organized and planned. Otherwise, the mess would be huge.

**Comment by uilianries** [comment]
I agree, from my experience, I just used the first option for some past jobs. We have forced to break the CI when the format was incorrect, but as a private company, it's easier to ping your coworker or apply default config file. But, as an open source project, if I see my code refused because the format, maybe I won't contribute on a next time.

**Comment by lasote** [comment]
We can continue with https://github.com/conan-io/conan/issues/3558
