### ISSUE TITLE
Issues upgrading Conan due to changed ctor behavior

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4437]
_Disclaimer: This is a bit of self-inflicted damage. Hoping that perhaps someone has a solution available. If this does not fit into the conan issue tracker feel free to close this issue._

We're currently using Conan `1.3.0`. In the last days I wanted to upgrade to the newest version (now `1.12.0`). The issue here is that our recipes do not inherit from `ConanFile` directly, there is another tier of inheritance inbetween.

This is our parent ConanFile which does some general things to make things easier:
```
### This is for Conan 1.3.0 ###
from conans import ConanFile, CMake

class CustomConanFile(ConanFile):
    def __init__(self, output, runner, settings, user=None, channel=None, local=None):
        super(CustomConanFile, self).__init__(output, runner, settings)
        self.cmake = CMake(self)
        #...some custom stuff here...
```

Then here is how a recipe looks like:
```
### This should work with Conan 1.3.0 and 1.12.0 ###
from CustomConanFile import CustomConanFile

class SpecificConan(CustomConanFile):
    name = "Hello"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    #...more stuff...
    
    def build(self):
        print(str(self.cmake))
```

The first issue I had was that the ctor changed over time. This was easily solvable by just adding the new ctor. The second issue though is a bit harder to crack. As you can see someone decided to init `self.cmake = CMake(self)` within the ctor. I guess the idea was to reuse that instance instead of creating an instance within `build()`, `package()` and so on.

With `1.3.0` it was possible to create `self.cmake = CMake()` within the ctor. With `1.12.0` however this is not possible anymore. I get the following error:

```
Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\conans\model\ref.py", line 111, in loads
    _, name, version, user, channel, revision, _ = ConanFileReference.sep_pattern.split(text)
ValueError: not enough values to unpack (expected 7, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\conans\client\command.py", line 376, in install
    ref = ConanFileReference.loads(args.path_or_reference)
  File "c:\python36-32\lib\site-packages\conans\model\ref.py", line 114, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference ..\
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\conans\client\command.py", line 1495, in run
    method(args[0][1:])
  File "c:\python36-32\lib\site-packages\conans\client\command.py", line 389, in install
    install_folder=args.install_folder)
  File "c:\python36-32\lib\site-packages\conans\client\conan_api.py", line 88, in wrapper
    return f(*args, **kwargs)
  File "c:\python36-32\lib\site-packages\conans\client\conan_api.py", line 531, in install
    no_imports=no_imports)
  File "c:\python36-32\lib\site-packages\conans\client\manager.py", line 76, in install
    self._recorder, None)
  File "c:\python36-32\lib\site-packages\conans\client\graph\graph_manager.py", line 139, in load_graph
    channel=graph_info.root.channel)
  File "c:\python36-32\lib\site-packages\conans\client\loader.py", line 109, in load_consumer
    conanfile = conanfile_class(self._output, self._runner, display_name, user, channel)
  File "D:\Github\conan_compat_test\CustomConanFile.py", line 15, in __init__
    self.cmake = CMake(self)
  File "c:\python36-32\lib\site-packages\conans\client\build\cmake.py", line 44, in __init__
    self._build_type = build_type or conanfile.settings.get_safe("build_type")
AttributeError: 'tuple' object has no attribute 'get_safe'

ERROR: 'tuple' object has no attribute 'get_safe'
```

Does anybody have an idea on how I could assign `self.cmake` from within `CustomConanFile` before the `SpecificConanFile` is making a call to it? I'd prefer to not change all of our specific receipts, but I'm out of ideas.

**Comment by monsdar** [comment]
Files: https://gist.github.com/monsdar/02bf05d0b0c2ec1875ec5f9a78bc0701

Just try the files with the newest conan version and do `conan install ...` and `conan build ...`

**Comment by uilianries** [comment]
Related issue: https://github.com/conan-io/conan/issues/4386

**Comment by monsdar** [comment]
Haha, I bet that was a colleague of mine :D
Well... Closing here then...

Sorry for taking away 10 minutes of your life :(

**Comment by uilianries** [comment]
np, I think you wasted more time writing and thinking than me :joy:

**Comment by monsdar** [comment]
Sure did :sob:
