### ISSUE TITLE
[question] profile and requirements

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4440]
Hi there,
I was wondering, profiles can specify ```build_requirements``` but not ```requirements```.
What is the background behind this?

Thx

**Comment by memsharded** [comment]
build_requires are mainly for tools: cmake, mingw, etc.

Those requires might be in the system, in fact, most developers will have them already install. They don't want a ``requires = "cmake/..."`` in their packages that will force the retrieval of a cmake conan package.

The recipes should work perfectly if the tool is installed in the system. Then, it was nice to have an orthogonal way to define them, and to be able to apply them to packages that didn't consider such requirements in advance. You can have a library package use your Cmake conan package without the package knowing.

This is not the same for normal requirements. If your package depends on "zlib", "zlib" conan package has to be there. Not declaring that in the recipe, and declaring it in a profile, while could be technically possible, wouldn't make sense, as you could have recipes without requirements at all, that only work with a profile. Profiles are intended to define configuration, not to define the dependency graph, that is the main role of a profile. Recipe should be as self-contained as possible, be able to work with different profiles (or just command line arguments).

**Comment by Johnnyxy** [comment]
The reason behind my question is that I have code that can use C++11 or Boost [headers only, bins].

Under Windows (VS) the code could use C++11 or Boost [headers, bins].
Under QNX 6.5 the code has to use Boost [bins].
Under QNX 7.0 the code should use Boost [header_only].

I was thinking, that with a profile I could specify for my build target if and which boost dependencies/settings/options it should use.

In the recipe I would add logic if necessary to detect if boost should be used or detect it my the C/C++ code.
```if ("boost" in self.deps_cpp_info.deps): ...```

**Comment by memsharded** [comment]
Closing this question as outdated. Overriding of regular host packages from profiles is not planned, recipes must conditionally depend on the different dependencies based on their settings. If the logic is duplicated among many recipes, it can always be reused from a ``python_requires``
