### ISSUE TITLE
Error copying lock files on jenkins when using SCM

### ISSUE THREAD

**Issue by Thantalos** [conan-io/conan#4441]
System: Build Server running Win7 and Jenkins + Conan 1.12.

I encountered the following problem. When using the new SCM feature ([this one](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#scm-attribute)) on my windows build server (linux is fine), I get this error message: `[Errno 13] Permission denied` and the build just fails. No additional information. Problem is that I'm unable to reproduce the error outside the Jenkins environment. Building localy as well as manually on the build server works just fine.

But I was able to locate the problem at this position: 
https://github.com/conan-io/conan/blob/6955f8170f8e38ebb410498cfa7e32969f5441b3/conans/client/source.py#L71
This file copy command fails for exactly one file, a conan lock file. In my case for example: `D:\jenkins\3rdparty_zlib_PR-1\conan_home\.conan\data\zlib\1.2.11\conan\snapshot\locks\970e773c5651dc2560f86200a4ea56c23f568ff9` with a `PermissionError` [see](https://docs.python.org/3/library/exceptions.html).
Btw, a more detailed error indication at this point would be nice (if I knew more about Conans inner workings I would add it).

I'm sorry, I don't know exactly which option on build server causes this behaviour. I tried to look into it but couldn't find it. Perhaps you have an idea what might cause it, so I know where to look. If you need any additional information I will try and provide it.

**Comment by Thantalos** [comment]
OK, I know this problem seems a convoluted, but I'd really like to fix it.
How about this for a start: Can anyone tell me what those locks are for, who creates them, etc.?

**Comment by lasote** [comment]
Hi, the lockfiles are created by Conan to control the concurrency in the local cache.

Maybe the destination folder already exists and the file `D:\jenkins\3rdparty_zlib_PR-1\conan_home\.conan\data\zlib\1.2.11\conan\snapshot\locks\970e773c5651dc2560f86200a4ea56c23f568ff9` is locked by the `os` for some reason. Could you check if the file is already there? 
Have you some antivirus or the windows indexer service enabled in the windows slave? Sometimes they could produce errors of this type if you try to remove a file being scanned.
The issue happens always? Which command are you running?

**Comment by Thantalos** [comment]
I'm sorry for the late response. I was sick...
Antivirus and windows indexer were the first things that came to my mind too. They are deactivated for the drive I'm building on and this didn't change anything. Also the error is repeatably always about lock files, never anything else.
I added a check right before the copy line, to see whether the source file actually exists and whether the destination file already exists. I get a few instances of the destination file already existing but not the lock file. 
This is the command I'm running:
`conan create . zlib/1.2.11@conan/snapshot --profile win64-x86_64-VS15 -s build_type=Release -o zlib:shared=True --build zlib --build outdated`

**Comment by lasote** [comment]
Are you sharing the conan directory between concurrent builds?

**Comment by Thantalos** [comment]
No. Each build has it's own conan home. I even tested running just one concurrent build with the same result.
By all means, my setup appears to me pretty standard. Wierd that no one else seems to be affected by this.

**Comment by lasote** [comment]
Thanks. I've been taking a look to the code and I don't understand why that lock file is there.
Confirm, please, that your CI process is the following:
- Check out the recipe repository. The recipe uses SCM feature.
- Call: `conan create . zlib/1.2.11@conan/snapshot --profile win64-x86_64-VS15 -s build_type=Release -o zlib:shared=True --build zlib --build outdated`

Assuming that flow (totally correct) and following the code, I can only think that in the checkout directory there is a conan lock file that is being copied. But it doesn't make much sense.

**Comment by memsharded** [comment]
Closing this thread as inactive
