### ISSUE TITLE
"conan install .. " broken for Wrong package recipe reference (1.12.0)

### ISSUE THREAD

**Issue by dfleury2** [conan-io/conan#4445]
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

If a launch 'conan install ..' in my build director, where .. has a conanfile.py file.
I got an exeption "Wrong package recipe reference".
I have add a display and it seems that conan tries to parse ".." as a recipe.
the same happens if I use "conan install ../conanfile.py"
Regards,

**Comment by memsharded** [comment]
Hi @dfleury2 

I am trying to reproduce without success. What "display" have you added? If you are tracing conan code execution, could you please elaborate a bit more which steps did it take to get there? 

In which OS and terminal is it happening? Also, are you in the CppLang slack channel? We could try to talk there to pair-debug this issue, looking weird. Thanks!

**Comment by dfleury2** [comment]
Hi, 
I am on Debian Jessie.
I have added a comment for displaying which text throw the exception (before I see It was already displayed on the exception et ref.py line 115)
Yes I am on CppLang slack same id.
I got this issue when I use editable package as requirement (requires in the conanfile.py)

**Comment by dfleury2** [comment]
It's working fine for my case with this patch now
Thanks.

**Comment by memsharded** [comment]
Will be released in the patch 1.12.1 as soon as possible.
