### ISSUE TITLE
[question] build_requires dependency uses other dependency's deps_cpp_info

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4450]
Hi there,
the docs state that

> Options and environment variables declared in the profile as well as in the command line will affect the build requirements for packages. In that way, you can define for example for the cmake_installer/0.1 package which CMake version will be installed.

Would it be possible to set the options of a ```build_requirement``` anywhere in the ```conanfile.py``` before the dependencies are built?

My recipe build_requires two dependencies ```dep_1/1.0@test/test``` and ```dep_2/2.0@test/test```.
My recipe has to set the options of ```dep_2/2.0@test/test``` depending on the installed ```dep_1/1.0@test/test``` (e.g. path).

```python
def build_requirements(self):
    self.build_requires("dep_1/[~=1.0]@test/test")
    self.build_requires("dep_2/[~=2.0]@test/test")
    self.options["dep_2"].executable = self.deps_cpp_info["dep_1"].rootpath + "/dep_1.exe"
```

**Comment by uilianries** [comment]
Hi @Johnnyxy 

Unfortunately not. `self.deps_cpp_info["dep_1"]` need graph deps, but it will be available after to call `requirements` and `build_requirements`.

But why do need to transfer the exec path to another package? Usually we append the bin directory in PATH, for example [ninja_installer](https://github.com/bincrafters/conan-ninja_installer/blob/c92ef50168747d95b663532ebadd42e7845f891e/conanfile.py#L59), and could call by `self.run()`

Related issues: #2218 #4401

**Comment by Johnnyxy** [comment]
@uilianries the boost package from conan has the option "python_executable".
I have a python package for a specific version I need to link to. Not necessarily the python version that executes the conan process.
So I specify a python package (e.g. python/3.6@test/test) as build_requirement.
Now the boost recipe can detect the current python exe and version. But it does this by running the ```sys.executable``` and parses the output.

I need to set the ```self.options["boost"].python_executable = self.dep_cpp_info["python"].rootpath``` that the boost recipe uses my python not the system one.

```python
def build_requirements(self):
    self.build_requires("python/[=3.6]@test/test")
    self.build_requires("boost/[1.69.0]@conan/stable")
    self.options["boost"].python_executable = self.deps_cpp_info["python"].rootpath + "/python.exe"
```

**Comment by uilianries** [comment]
I don't see a good solution, as your limitation is involving node graphs.
Here I invoke the master of graphs @memsharded

**Comment by memsharded** [comment]
``deps_cpp_info`` no longer exists in 2.0, replaced some time ago in 1.X by ``self.dependencies``. Closing this as outdated.
