### ISSUE TITLE
Unexpected behaviour for 'env_reader.get_env'

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4451]
Behaviour for `env_reader.get_env` ([link](https://github.com/conan-io/conan/blob/e018e0ff0e7f6addf76cf589f471edc23569939d/conans/util/env_reader.py#L12)):

```python
def get_env(env_key, default=None, environment=None):

    if environment is None:
        environment = os.environ

    env_var = environment.get(env_key, default)
    if env_var != default:
        if isinstance(default, str):
            ...
        elif isinstance(default, list):
            return [var.strip() for var in env_var.split(",")]
    return env_var
```

From my point of view the following is unexpected:

```bash
>>> from conans.util.env_reader import get_env
>>> env = {'CONAN_HOOKS': ''}
>>> get_env('CONAN_HOOKS', default=list(), environment=env)
['']
```

IMO, it should return an empty list.

----

I found this making some trials with hooks, once you deactivate all the hooks you have a `conan.conf` file with an empty section:

```ini
[hooks]

```

and then, when executing any command, it gives me the following warning: `WARN: Hook '.py' not found in /Users/jgsogo/.conan/hooks folder. Please remove hook from conan.conf or include it inside the hooks folder.`

So, if you don't consider the previous behavior as unexpected, then an additional check should be added to the `HookManager` to avoid the warning.

cc/ @conan-io/barbarians

**Comment by lasote** [comment]
Sure, it should be an empty list.

**Comment by danimtb** [comment]
agree

**Comment by uilianries** [comment]
me too!
