### ISSUE TITLE
Conan 1.12.0 broke uploading for our artifactory

### ISSUE THREAD

**Issue by earonesty** [conan-io/conan#4452]
Still haven't figured out why.   But I have confirmed that rolling back to 1.11.X fixes all of the issues.   Maybe it's the sha thing?   Going to try and update our artifact manager.   I'll post here if we fix it.

```
ERROR: 
Error uploading file: conanfile.py, 'b'''
Traceback (most recent call last):
  File "C:\Users\vida\AppData\Local\Programs\Python\Python36\lib\site-packages\conans\client\remote_manager.py", line 322, in _call_remote
    return getattr(self._auth_manager, method)(*argc, **argv)
  File "C:\Users\vida\AppData\Local\Programs\Python\Python36\lib\site-packages\conans\client\rest\auth_manager.py", line 32, in wrapper
    ret = func(self, *args, **kwargs)
  File "C:\Users\vida\AppData\Local\Programs\Python\Python36\lib\site-packages\conans\client\rest\auth_manager.py", line 131, in upload_recipe
    policy, remote_manifest)
  File "C:\Users\vida\AppData\Local\Programs\Python\Python36\lib\site-packages\conans\client\rest\rest_client.py", line 71, in upload_recipe
    policy, remote_manifest)
  File "C:\Users\vida\AppData\Local\Programs\Python\Python36\lib\site-packages\conans\client\rest\rest_client_common.py", line 211, in upload_recipe
    self._upload_recipe(ref, files_to_upload, retry, retry_wait)
  File "C:\Users\vida\AppData\Local\Programs\Python\Python36\lib\site-packages\conans\client\rest\rest_client_v1.py", line 126, in _upload_recipe
    self._upload_files(urls, files_to_upload, self._output, retry, retry_wait)
  File "C:\Users\vida\AppData\Local\Programs\Python\Python36\lib\site-packages\conans\client\rest\rest_client_v1.py", line 164, in _upload_files
    % ", ".join(failed))
conans.errors.ConanException: Execute upload again to retry upload the failed files: conanmanifest.txt, conanfile.py
```

**Comment by earonesty** [comment]
I think the problem is that this custom header cannot be safely ignored, because a repo *must* return 404 to HEAD/GET requests when a digest is supplied, otherwise an upload may never be attempted.

**Comment by lasote** [comment]
We would need the artifactory version and if possible the log from the server side. We introduced changes about this. The header including the Sha is always used, even when not checking if the artifact is already in the remote, but it should work. Please help us, we can release a minor quickly if we spot the bug.

**Comment by earonesty** [comment]
Originally, our artifact manager ignored the header completely.   This resulted in changed files never getting uploaded.   We fixed this by simply returning 404 every time we see the header.   Now this is broken (no files get uploaded).

The issue affects the Nexus artifact manager and any manager that for whatever reason cannot process the header.

The correct api behavior should be:   ignoring the header results in inefficiency... not a broken system.   It seems the correct way to get that behavior would be to add the SHA to the get/head URI for existence (since the question being asked is really about the SHA).

**Comment by lasote** [comment]
Now I understand, you were talking about a Nexus repository. Good to know that you managed to open a pull request to fix it. :+1:  I think there is no bug in the client side then and this can be closed. Otherwise just write again and we will reopen the issue. Thanks!

**Comment by earonesty** [comment]
I think it is a design flaw if a repo cannot operate without strictly adhering tot he operation of an optional header flag which is now no longer optional.

**Comment by memsharded** [comment]
Hi @earonesty 

Not sure if I understand what you mean. Conan_server repo works fine without implementing the X-Checksum-Sha1 header. Are you taking about a flaw in https://github.com/sonatype-nexus-community/nexus-repository-conan/pull/53?

**Comment by lasote** [comment]
`X-Checksum-Sha1` is totally optional and can be ignored on the server side, but the header, not the request. I'm not sure what is nexus doing there, but maybe you are looking for the `X-Checksum-Deploy` header. Escaping the requests containing `X-Checksum-Sha1` is the design flaw.
