### ISSUE TITLE
tools.patch(..., strip=n) does not work with new/deleted files

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#4453]
This seems related to #1807

#1898 has added code in conan to support creating new files, but this code does not adjust the source/target paths per strip=n before calling save/unlink.

conan 1.11.2, windows 7

Specifically, the code here needs to trim `strip` leading components off the path before joining it to base_path:

https://github.com/conan-io/conan/blob/fd0507594838413e09abbf8bb7be128c23dd6378/conans/client/tools/files.py#L206-L215

A simple example based on the `conan new` template is at https://gist.github.com/puetzk/d8553b06827ec4f2071c2428b118bd88
`conan source .` runs, and the second hunk of example.patch is applied to hello/hello.cpp correctly (stripping src), but the first hunk is not stripped and therefore creates src/hello/goodbye.cpp instead of hello/goodbye.cpp

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Having a quick look. So the unit test that would check this behavior would be:

```python
def test_patch_new(self):
        conanfile = dedent("""
            from conans import ConanFile, tools
            class PatchConan(ConanFile):
                exports_sources = "example.patch"
                def source(self):
                    tools.patch(self.source_folder, "example.patch", strip=1)""")
        patch = dedent("""
            --- /dev/null
            +++ b/src/newfile
            @@ -0,0 +0,1 @@
            +New file!""")

         client = TestClient()
        client.save({"conanfile.py": conanfile,
                     "example.patch": patch})
        client.run("source .")
        self.assertEqual(load(os.path.join(client.current_folder, "newfile")),
                         "New file!")
```

If it is that, the fix could be the one in #4455

**Comment by puetzk** [comment]
Quick response!

It would (I think, at least) there would also need to be a test for target=/dev/null (i.e. deleted file), where it's the path to unlink that needs to be adjusted. And I think it's legal (though probably quite rare) for patches to use \ instead of /. At least the patchlib you're using for the rest looks like it's using os.path.split: https://github.com/techtonik/python-patch/blob/c9402be37c365e1bdf4aef07dcfa8c9ab3dab47f/patch.py#L198-L204

**Comment by memsharded** [comment]
Done, will be in conan 1.13.
