### ISSUE TITLE
Remove pylint from requirements

### ISSUE THREAD

**Issue by mristin** [conan-io/conan#4454]
Hi!
I'm trying to install conan from pypi.org with pip3 (version 1.12.0) and have just realized that you include pylint as the package dependency. I didn't look thoroughly into the code -- but is this really necessary? Isn't pylint used only to check your own code?

I have a package that already installed pylint in the virtual environment and calls programmatically conan -- only then did I realize that pylint versions conflicted. Please let me know if I can help anyhow.

**Comment by memsharded** [comment]
Yes, pylint is used in the linting that is done while ``conan export`` and ``conan create`` to check for recipe quality and possible issues. It has been moved to a hook, so not in the conan core codebase anymore. Until the hook is totally decoupled from this repo, the pylint dependency might be still necessary to not break users builds. It will be totally separated in Conan 2.0, for sure.

**Comment by memsharded** [comment]
Right now it could be considered breaking, but lets move the recipe linting to external hooks, in Conan 2.0

**Comment by jgsogo** [comment]
We merged https://github.com/conan-io/conan/pull/6152 removing pylint from Conan codebase in 1.21

We can close this issue.
