### ISSUE TITLE
[feature request] Adding conan link list 

### ISSUE THREAD

**Issue by dfleury2** [conan-io/conan#4459]
Hi,
it would be great to have something like 'conan link list' to list all packages in editable modes.
At this time, I see nothing else than read the .conan/editable_packages file.

Later, may be a 'check' can be added to verfiy the validity of the layout (and it's existence)

Regards,

**Comment by memsharded** [comment]
Sure, that is already tracked in https://github.com/conan-io/conan/issues/4422, I will make sure to make it clear there, please track that issue (already assigned for next release). Thanks for the feedback!
