### ISSUE TITLE
Misleading name of cpp_info.cppflags instead of cpp_info.cxxflags

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#4461]
Following the correction in https://github.com/conan-io/conan/issues/4336 we should introduce a ``cpp_info.cxxflags`` alias for ``cpp_info.cppflags`` to avoid this confusion without breaking.

Finally, ``cpp_info.cppflags`` could be removed in Conan 2.0

**Comment by lasote** [comment]
Duplicated of #4337
