### ISSUE TITLE
Editable package changes conan create behavior (imports, collect_libs)

### ISSUE THREAD

**Issue by dfleury2** [conan-io/conan#4466]
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.12
[conan.zip](https://github.com/conan-io/conan/files/2829785/conan.zip)
using  these 2 projects (A with bin and libs, and B wich build_requires A), 

conan create . user/stable  in A directory
conan create . user/stable in B directory 

if A is not in editable mode, B package contains all files from A (bin, libs).

conan link . user/stable --layout a.layout

if A is put on editable mode, B package is empty

Is there a way to avoid this ? (I try not self.in_local_cache withou success)

Regards,

**Comment by dfleury2** [comment]
There is an inconvenient related to editable mode too (may be related to this issue)  : tools.collect_libs() does not work anymore (or at least I do not know how to make it work now)

**Comment by memsharded** [comment]
Hi @dfleury2 

In https://github.com/conan-io/conan/pull/6208 a new functionality to allow importing files from editable layouts. Please have a look, because I think this issue will be solved with it. It is in develop branch (you can run it from test pypi https://test.pypi.org/), and it will be released in Conan 1.22.

**Comment by dfleury2** [comment]
Hi @memsharded,
I have just tried the conan 1.25.0. At this time, my conanfile.py's do not use imports, but I can update them, it should solve the first part.

The second part, tools.collect_libs()  still not working, and I think this is the main problem for my projects because I had to declare manually all my libs in the package_info (or I miss the point)

def package_info(self):
        self.cpp_info.libs = ["A1", "A2"]

but this is a duplicate of https://github.com/conan-io/conan/issues/6385
