### ISSUE TITLE
cmake_paths generator broken for transitive dependencies

### ISSUE THREAD

**Issue by NewProggie** [conan-io/conan#4467]
The **cmake_paths** generator currently doesn't handle transitive dependencies for Conan packages. I am not talking about the _requires_ option, but for transitive dependencies in a package itself.

Consider the following simple conanfile.txt configuration:
```
[requires]
opencv/4.0.1@conan/stable

[generators]
cmake_paths
```

Since the cmake_paths generator only declares the `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` variables, a client is currently forced to call conan as follows:
```
$ mkdir build && cd build
$ conan install --build=missing ..
$ cmake \
    -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCONAN_LIBJPEG_ROOT:PATH=/Users/NewProggie/.conan/data/libjpeg/9c/bincrafters/stable/package/560b128b7f18cdc8f77f23c6834ffad4a/ \
    -DCONAN_ZLIB_ROOT:PATH=/Users/NewProggie/.conan/data/zlib/1.2.11/conan/stable/package/560b128b7f18cdc8ff080cad77f34ffad4a/ \
    -DCONAN_LIBPNG_ROOT:PATH=/Users/NewProggie/.conan/data/libpng/1.6.34/bincrafters/stable/package/2fcedcd518d74d31f30df6a210eeb54d/ \
    -DCONAN_LIBTIFF_ROOT:PATH=/Users/NewProggie/.conan/data/libtiff/4.0.9/bincrafters/stable/package/2fcedcd518d74d31f90df6a210eeb54d/ \
    ..
```
If a client doesn't add the `CONAN_*_ROOT` variables, this setup leads to linker problems, since the OpenCVConfig CMake module is cluttered with those variables and they will simple be empty otherwise (resulting in linker errors such as: `cannot find /lib/libjpeg.a.` Note the missing leading path here).

A rather simple and appropriate fix to this would be to extend the cmake_paths generator with all those custom and necessary `CONAN_*_ROOT` variables as follows:
```cmake
 # as before
set(CMAKE_MODULE_PATH ...)
set(CMAKE_PREFIX_PATH ...)

# new and mandatory for transitive package dependencies
set(CONAN_LIBJPEG_ROOT ...) 
set(CONAN_ZLIB_ROOT ...)
set(CONAN_LIBPNG_ROOT ...)
set(CONAN_LIBTIFF_ROOT) ...
```

Since the paths to those transitive dependencies already get appended to the `CMAKE_MODULE_PATH` and the `CMAKE_PREFIX_PATH` respectively, I guess this is simply a matter of extracting those out of `DepsCppCMake`:
https://github.com/conan-io/conan/blob/ca12f25dc6d5a11e640bbcb76e93d42205d3e0e7/conans/client/generators/cmake_paths.py#L13-L20

Please let me know, if I am doing something wrong here, or if the proposed solution is feasible.

**Comment by lasote** [comment]
I'm not sure I understand. 
The `cmake_paths` generator is intended to be used only when a `CMakeLists.txt` file is using `find_package` to locate ALL the dependencies. I don't know the details of the OpenCV recipe implementation but the ``CONAN_*_ROOT`` variables are generated by the `cmake` generator, not the `cmake_paths` generator. So probably you need to change the generator and include the `conanbuildinfo.cmake` file.

**Comment by lasote** [comment]
Thanks for the info, now I understand what you mean. I forgot we have the `cmake.patch_config_paths()` helper to replace the absolute paths with "ROOT" folders.
I think it makes a lot of sense what you are requesting.
