### ISSUE TITLE
Use metadata information as Artifactory properties

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4469]
- Modify the hooks to accept the metadata object (in all stages?)
- Add a sub-object "properties" to `metadata.recipe` and `metadata.packages["xxx"]`
- Prepare the needed HTTP headers to send to Artifactory the set properties in the metadata. 

Issues to be discussed/solved:

- Currently, the indexer is only reading the headers starting with `artifact_property_`  and setting it to all the files being upload. `https://docs.conan.io/en/latest/reference/config_files/artifacts.properties.html`
- I think it would be very interesting (very old Artifactory/conan integration issue) to set the `metadata.recipe.properties` to the conan package folder:

![image](https://user-images.githubusercontent.com/3807515/52270534-991df080-2941-11e9-94b0-a0bfd52add61.png)

And the `metadata.package["xxx"].properties` to the binary package folder:

![image](https://user-images.githubusercontent.com/3807515/52270626-ce2a4300-2941-11e9-9ee2-0d7c4b0d7b5f.png)

In the artifactory side I think it could be nicely done if:

- If we are uploading the `conanfile.py`: We set also the properties to the conan package folder.
- If we are uploading the `conaninfo.txt`: We set also the properties to the binary package folder.

Would be also nice to set the conan reference as a property in the conan package folder.

Having all the properties in the right folder could enable Artifactory flows of deletion, promotion and to coordinate CI flows, etc targeting the folder with AQL:

```
items.find(
    {
        "repo":{"$eq":"c3i-full"},
        "type": "folder",
        "@reference": {"$eq": "Hello/0.1@conan/stable"}
    }
)
```

I think this is high priority because it is part of the roadmap of the CI flows.

**Comment by uilianries** [comment]
BTW, are package revisions accepted by Artifactory?

**Comment by lasote** [comment]
Not yet.

**Comment by lasote** [comment]
We decided that the way to go is just to use the artifactory REST API or the JFrog-cli to set the properties.
