### ISSUE TITLE
Regression in MSBuild helper properties injection

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#4471]
Unfortunately, in #4113 we have missed the fact the `ForceImportBeforeCppTargets` parameter requires an absolute path to the properties files to be injected.

**Comment by memsharded** [comment]
If this is a regression and it breaks badly MSBuild projects, it should be fixed in conan 1.12.2.

I have had a look, didn't understand why the test in https://github.com/conan-io/conan/pull/4113/files was not failing.

**Comment by Minimonium** [comment]
@memsharded 
Because it doesn't test the `ForceImportBeforeCppTargets`. Configuration and arch are handled by other MSBuild parameters. To make a correct test one should test a different Runtime.

**Comment by memsharded** [comment]
This is true, this is a regression and will be fixed in Conan 1.12.2 asap.

**Comment by memsharded** [comment]
Released in Conan 1.12.2
