### ISSUE TITLE
[QoL] Add an`upsert`  option to `conan profile new`

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#4477]
Would allow reusing the default profile with the same cache on different machines.

**Comment by Minimonium** [comment]
though now it can be used like this:
```
    - rm -f $CONAN_USER_HOME/.conan/profiles/default
    - conan profile new default --detect
```

**Comment by lasote** [comment]
Maybe a `--force` parameter.

**Comment by jgsogo** [comment]
Closed via https://github.com/conan-io/conan/pull/4880
