### ISSUE TITLE
[QoL] Allow `conan remove -t *`

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#4478]
In the CI with the cache, it's needed to reinstall system requirements when the machine has been changed. Currently, it's only supported with a full reference.

**Comment by Minimonium** [comment]
Consider #4478

**Comment by lasote** [comment]
I agree. But I would say the command should be `conan remove "*" -t`

(An internal note for the dev team or any other collaborator that develop this feature:
Calling directly the "cache" from the command.py is not correct and it should have a dedicated function in the conan_api. `self._cache.remove_package_system_reqs(ref)`)

**Comment by uilianries** [comment]
Should it remove global system requirements, or only from all packages?

**Comment by Minimonium** [comment]
What tools do we have to remove only global system requirements from conan cli? 
I'm not sure it makes sense to remove global system requirements too. Or better to say - applying to this use case it makes sense, but I feel like the usage would be a bit confusing and a little bit unexpected.

**Comment by uilianries** [comment]
So maybe we could create a new option for global requirements

**Comment by lasote** [comment]
Anyway, that would be a different feature. Let's keep things clear.
