### ISSUE TITLE
self.copy() sometimes does not show the name of files copied

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#4479]
Using conan 1.12.1 on Linux but observing the same behavior on Windows.

When using ``self.copy()`` in a conanfile, e.g. in ``package()`` or ``imports()``, the number and name of files copied is supposed to be shown in the console output. But sometimes the file names are omitted. Not really sure why but maybe it depends on the number of files?

I don't know if that's a bug or the intended behavior. Can you force conan to always or in certain situations show the file names?

Example 1:

    [...]
    gtest/1.8.1@fschoenm/testing: Calling package()
    gtest/1.8.1@fschoenm/testing package(): Copied 24 '.h' files: 
    gtest/1.8.1@fschoenm/testing package(): Copied 2 '.a' files: libgtest_maind.a, libgtestd.a
    gtest/1.8.1@fschoenm/testing: Package 'af0fbc5eb7376a4b9749db37a5c402b36d452909' created

Example 2:

    [...]
    conanfile.py: Generator cmake_multi created conanbuildinfo_debug.cmake
    conanfile.py: Generator cmake_multi created conanbuildinfo_multi.cmake
    conanfile.py: Generator txt created conanbuildinfo.txt
    conanfile.py: Generated conaninfo.txt
    conanfile.py: Generated graphinfo
    conanfile.py imports(): Copied 5 '.lic' files: 
    conanfile.py imports(): Copied 1 '.so' file: libfdb_c_5.2.5.so

Not sure if it's necessary but the behavior in example 1 can be reproduced with the following simple conanfile: [conanfile.py.txt](https://github.com/conan-io/conan/files/2836933/conanfile.py.txt)

---
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
Hi @fschoenm !

It's intentional, otherwise the line could be huge for some terminals.

The rule, if have 5 or more elements, then show their extension:

https://github.com/conan-io/conan/blob/develop/conans/client/file_copier.py#L19

**Comment by fschoenm** [comment]
I see. I think it's a bit confusing and unexpected to see a colon (``:``) and nothing following it. Also, 5 is quite the arbitrary number. Maybe the output could be improved somewhat.

**Comment by memsharded** [comment]
Hi @fschoenm 

Yes, maybe the output could be slightly improved for this case. 
The arbitrary number of 5, yes, it is arbitrary, but this is just some info message to let the user know that something is being packaged or not, it doesn't and it shouldn't be a complete reference of what is being packaged. Adding user configuration to customize this message would be overkill.

If you want to inspect the contents of a package, you can with ``conan get``:

```bash
$ conan get zlib/1.2.11@conan/stable conanmanifest.txt -p 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
# Outputs the manifest
$ conan get zlib/1.2.11@conan/stable . -p 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
# Outputs the directory
$ conan get zlib/1.2.11@conan/stable include -p 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
# Outputs only the include directory
```
