### ISSUE TITLE
No proxy settings used for conan_api

### ISSUE THREAD

**Issue by NewProggie** [conan-io/conan#4485]
If I am creating a conan package from the command line such as
```bash
$ conan create . foo/bar
...
.. Package 'r342r3t5' created
```

conan is able to use my proxy settings (either via conan.conf or using the environment variables HTTP_PROXY/http_proxy etc.).

However, I need to build and deploy a large collection of conan packages. Hence, I am using a semi-automated approach via conan_api:
```python
>>> from conans.client import conan_api
>>> cpm, _, _ = conan_api.ConanAPIV1.factory()
>>> cpm.create(".", version="1.2.3, user="foo", channel="bar")

ERROR: Error downloading file https://my.artifactory.de/artifactory/packages/foo/bar-1.2.3.zip: 
'HTTPSConnectionPool(host='my.artifactory.de', port=443): Max retries exceeded with url: 
/artifactory/packages/foo/bar-1.2.3.zip (Caused by ProxyError('Cannot connect to proxy.', 
NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2e2feecb00>: 
Failed to establish a new connection: [Errno -2] Name or service not known',)))'
```

Unfortunately, this leads to the above proxy connection error. I've already tried to append my proxy settings via the env parameter (`cpm.create(.... env={'HTTP_PROXY=...'}`) with no luck. Interestingly enough, it seems though as if the proxy settings do get set:

```python
>>> from conans.client import conan_api
>>> cpm, _, _ = conan_api.ConanAPIV1.factory()
>>> cpm.config_get('proxies')
http = <my proxy settings>
https = <my proxy settings>
```

Any hint, if I am doing something wrong here?

**Comment by memsharded** [comment]
Hi @NewProggie 

This is so weird. The first thing conan does when called, is exactly that:

```python
try:
        conan_api, cache, user_io = Conan.factory()
    except ConanException: 
        sys.exit(ERROR_MIGRATION)
```

I have no idea why it would be different when running from your script that when running from the command line in that respect. The only thing could be: how did you installed Conan? With pip? are you using conan exactly with the same python interpreter as your script?

**Comment by NewProggie** [comment]
I'm sorry, this issue was indeed proxy related on my side. After fixing this, the approach described above works fine now.

**Comment by memsharded** [comment]
Good, thanks @NewProggie for following up.
