### ISSUE TITLE
[question] Different package ids for different Linux variants

### ISSUE THREAD

**Issue by kheaactua** [conan-io/conan#4486]
Is there a recommended way to distinguish packages based on the Linux variant that they were built on?  My issue specifically is that I typically build on Ubuntu, but recently we have a call for CentOS.  Both setups use the same compiler (gcc 4.8)

A binary package built on one doesn't work on the other (symbol names, glib issues, _etc_), but the package IDs are the same.

The only solutions I can think of are:
1. Modifying every recipe (we have _a lot_) to append a `vendor` tag to `settings`
1. Maintaining two different conan servers, one for Ubuntu binaries, one for CentOS binaries

Solution 1 restricts me to only using packages with recipes that I've written, _i.e_. wouldn't be able to use `boost/..@conan/stable`, but would have to use my own wrapped version `boost/..@matt/stable`, which means I won't get updates, new packages are that much slower to write, _etc._

Solution 2 should work, but it also sets me up for perpetual manual synchronization, and sounds really prone to error.

On the forums I asked if there was any global setting in `settings.yml` I could change that would have an impact on all the package IDs built on that system, but they didn't think so.  I also toyed with the idea of messing with the compiler version in the profile, but that seems like a messy hack even if it works.

Is there any recommendation on how to deal with this issue?  Maybe `vendor` should be a default variant in `settings`?

I should add: typically our workflow is to upload all our and third party packages (so, `mine/1.0@my/stable` alone with `boost/1.66.0@conan/stable`) to our local conan server.  That way they're always available with low latency, and easy to keep in sync on our team.

**Comment by memsharded** [comment]
Neither of both. The recommended way could be:

- Add a ``distro`` subsetting to ``os`` in ``settings.yml``, only for the "Linux" variant. 
- It can take values ``None`` (the most important), then CentOS6, RHEL7, etc...
- Recipes require no changes
- The subsetting ``self.settings.os.distro=None`` won't alter existing IDs, that will work. You can use it for your mainstream, already existing packages
- Make sure to define the correct ``distro`` setting in your profiles or command line for CentOS, etc. When you define a value != None, a new binary ID will be enforced.

And that is all, you don't need multiple servers, nor change your recipes. Please try and tell me, thanks!

**Comment by kheaactua** [comment]
Unfortunately I won't have a chance to test this, I'm leaving my workplace today.  But I passed it along to those replacing me, hopefully they'll post the results.  Thanks though!

**Comment by memsharded** [comment]
Ok, if no longer an issue, lets close it. Sure, tell your colleagues that they can re-open or submit new issues, we'll keep trying our best to help.

Sorry to hear that you are leaving your workplace, I hope that it will be for the better in the future, best luck!
