### ISSUE TITLE
copying pattern is always case insensitve on windows

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#4490]
Conan 1.12.0
`self.copy("*D.dll", dst="bin/Release", src="bin")`
will copy also dlls named: `food.dll` on windows, although it shouldn't.

**Comment by Johnnyxy** [comment]
The Windows API (Win32) is case-insensitive. You cannot have (by default) have two files named ```fooD.dll``` and ```food.dll``` in the same path/folder.

Essentially the results of the following statements are the same.
```python
self.copy("*D.dll", dst="bin/Release", src="bin")
self.copy("*d.dll", dst="bin/Release", src="bin")
```

In Windows 10 one can instruct Windows to use a case-seninsitive API, but only if the Windows Subsystem for Linux is installed. But one should not rely on that it is.

**Comment by derived-coder** [comment]
My use case was, copy all debug dll from Qt to the target dir. 
All debug dlls have a small `d` suffix, e.g. "QtGuid.dll"
but there was also a `Qt53DQuickScene2D.dll` which was recognized, but it shouldn't.

**Comment by Johnnyxy** [comment]
You cannot rely on case-sensitive names on Windows at all. One should not even do that on case-sensitive systems.

The only thing you could do is to do it yourself.
Did not execute the following code to test for missssspeeellings.
```python
from pathlib import Path
files_to_copy = [x for x in Path(self.build_folder).iterdir() if x.is_file() and (x.stem[-1:] == "d")]
```

**Comment by jgsogo** [comment]
My question would be: why do you compile the release libraries if you are going to package only the release ones?

**Comment by jgsogo** [comment]
I'm closing this issue, I think it is already resolved with the previous comments; if not, please open it again. Thanks!
