### ISSUE TITLE
exports_sources type inconsistency

### ISSUE THREAD

**Issue by Sir3dDeVi** [conan-io/conan#4505]
I'm using Conan 1.12.1 (installed via pip) on macOS 10.14.3 with Python 2.7.10, and I have noticed a problem during recipe development. The `exports_sources` field is a tuple when I execute the recipe via `conan source`, but in every other case it's a string.

### Reproducing the issue

For debugging I have created the following recipe:

```python
from conans import ConanFile

class TestConan(ConanFile):
    name = "test"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    exports_sources = "hello.txt"

    def source(self):
        print "source: %s" % type(self.exports_sources)

    def build(self):
        print "build: %s" % type(self.exports_sources)

    def package(self):
        print "package: %s" % type(self.exports_sources)
```

When I execute the steps manually (the output was shortened):

    $ mkdir tmp
    $ conan source . --source-folder=tmp/source/
    source: <type 'tuple'>

    $ conan install . --install-folder=tmp/install/

    $ conan build . --source-folder=tmp/source/ --install-folder=tmp/install/ --build-folder=tmp/build/
    build: <type 'str'>

    $ conan package . --source-folder=tmp/source/ --install-folder=tmp/install/ --build-folder=tmp/build/ --package-folder=tmp/package/
    package: <type 'str'>
    package: <type 'str'>

When I create the package (the output was shortened):

    $ conan create . devi/test
    source: <type 'str'>
    build: <type 'str'>
    package: <type 'str'>

---

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @VictoriousV 

Yes, you are correct about that behavior. The reason is that such field is only processed in the "export" stage, and in that stage it is always a tuple, so if a single str is found, it is converted to tuple first.
The only way to observe this conversion is in the ``conan source`` command, which is locally running an ``export`` if the source folder is different than the recipe folder, trying to emulate as close as possible to the behavior of the cache (not always possible).

In practice, it is a field that you should never use directly in your recipes. How did you discover this issue? What is your use case for using it in the recipe methods? Thanks for the feedback.

**Comment by VictoriousV** [comment]
Thank you for your quick reply. At work we are planning to use Conan with a private repository, where we want to store the source packages with the recipe, so we can avoid downloading them.

I have followed the [documentation](https://docs.conan.io/en/latest/creating_packages/package_repo.html) on how to export the source with the recipe. In my case the "source" is the original `.tar.gz`, and I wanted to use the `exports_sources` field later in the recipe to get the name of the directory where the contents of the `.tar.gz` is extracted. And this is how I discovered the issue. :)

I'm fairly new to Conan (besides reading the documentation and "playing" with it), so if that's not the "Conan" way, could you please point me to the right direction?

**Comment by memsharded** [comment]
Sure :)

You have access to different "folders", like ``self.source_folder`` or ``self.build_folder``. Not all of them will be defined in all methods, for example, the ``source()`` method, do not have a ``self.build_folder`` or a ``self.package_folder`` defined, as it is before building or packaging occur (and actually there are several build and package folders per each source folder).

You can read more about these folders in: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#source-folder

Also, take into account that some folders might change in time. By default, all the sources are copied from the source folder to the build folder (one build folder per binary configuration), to guarantee that no matter what the build does, it will never change the original source folder. Then, by default, in the ``build()`` method, by default the ``self.source_folder`` and ``self.build_folder`` will point to the same location (check the ``no_copy_sources`` attributes to optimize that if you are sure what you are doing).

I encourage you to "print" (hint: you can use ``self.output.info("Build folder: %s" % self.build_folder)`` for an integrated output) from your methods, and see the results. Also to use that path and to navigate to those folders: the structure of the conan local cache is very straightforward.

**Comment by VictoriousV** [comment]
Thank you, this was really helpful!
