### ISSUE TITLE
[feature] Auto complete command

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4507]
Hi!

I think Conan could supports bash completion feature, where we could auto complete each possible option by <tab>.

There is a nice project for python: [argcomplete](https://argcomplete.readthedocs.io/en/latest/)

Also, pytest documented how to integrate autocomplete [here](https://docs.pytest.org/en/latest/bash-completion.html).

Related issue: https://github.com/conan-io/conan/issues/842

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I think auto-completion has been considered before, and for me still seems too much for the value:

- Adding new dependencies can cause problems in not mainstream distros and OSs, and older systems.
- It only works in bash, not for all systems
- Might require some global activation (``sudo activate-global-python-argcomplete`` or add something to ``.bashrc``)
- The flow should be checked, as argcomplete actually runs the program. I think it shouldn't be a big problem, but lots of things are executed before argcomplete, so side effects (migrations?) should be checked.

Overall, conan is a tool that is not called that often, compared to others like git. Maybe we do it more often that other users, and even I sometimes miss the feature, the pain is not big enough for me.

**Comment by uilianries** [comment]
Thanks for commenting! Below are my considerations:

> It only works in bash, not for all systems

That's right, it is supported for some shell flavors only.

> Might require some global activation (`sudo activate-global-python-argcomplete` or add something to `.bashrc`)

At this point I see the feature as partially supported. You have Conan prepared to run it, but if you really want auto completion, you will need to executed a few steps more. Unfortunately, I don't see other way, because this feature depends of shell.

> Maybe we do it more often that other users, and even I sometimes miss the feature, the pain is not big enough for me.

Not really, I think it could help not only lazy people, but newbies who are starting to understand Conan.

But since auto-completion requires an extra step, I think it will be avoided by many users, and probably we will have more complains about environments where the it does not work.

So yes, I have to agree with you, the effort does not worth the retribution. BTW I think this discussion is good for history, because I didn't find any related issue, unless #842. As I am the first who requests this feature directly, in the future we will be able to see if there are more people interested.

Regards!

**Comment by memsharded** [comment]
> But since auto-completion requires an extra step, I think it will be avoided by many users, and probably we will have more complains about environments where the it does not work.

Yes, that is my biggest concern. Every little piece of code that we add implies some future maintenance, and this is the typical thing that indeed requires lots of maintenance and support. So agree, I prefer to keep it simple without it. Thanks!
