### ISSUE TITLE
[question] 'requires' and 'options: ERROR: project_A/1.0@user/snapshot1: 'option_a' value not defined

### ISSUE THREAD

**Issue by unzap** [conan-io/conan#4508]
Hi,

I'm continuing with a more complex test case to package pre-built binaries with dependencies.
Basically the flow is the following:

**Package module A:**

`class ConanTest(ConanFile):`

    settings = "os"
    options = {"option_a":    "ANY",
               "option_b":    "ANY",
               "option_c":    "ANY"
              }

    requires = ""

    def build(self):
        pass

    def package(self):
        self.copy("*")

    def deploy(self):
        self.copy("*")

`> conan export-pkg conanfile.py project_A/1.0@user/snapshot1 -s os=Linux -o option_a=a1 -o option_b=b1 -o option_c=c1`

Exporting package recipe
Linter warnings
    WARN: Linter. Line 1: Unused tools imported from conans
project_A/1.0@user/snapshot1: A new conanfile.py version was exported
project_A/1.0@user/snapshot1: Folder: /home/username/.conan/data/project_A/1.0/user/snapshot1/export
...
...
project_A/1.0@user/snapshot1: Package 'a4102137b2e0556f15d4311c066e4f0bc07289c7' created

**Package module B:**

`class ConanTest(ConanFile):`

    settings = "os"
    options = {"option_a":    "ANY",
               "option_b":    "ANY",
               "option_c":    "ANY"
              }

    requires = "project_A/1.0@user/snapshot1"

    def build(self):
        pass

    def package(self):
        self.copy("*")

    def deploy(self):
        self.copy("*")

`> conan export-pkg conanfile.py project_B/1.0@user/snapshot1 -s os=Linux -o option_a=a1 -o option_b=b1 -o option_c=c1`

Exporting package recipe
Linter warnings
    WARN: Linter. Line 1: Unused tools imported from conans
project_B/1.0@user/snapshot1: A new conanfile.py version was exported
project_B/1.0@user/snapshot1: Folder: /home/username/.conan/data/project_B/1.0/user/snapshot1/export
**ERROR: project_A/1.0@user/snapshot1: 'option_a' value not defined**

I tried to search from docs if I'm doing something wrong related to options or "requires" definition, but haven't been able to figure out the reason so far?  [I saw this related issue](https://github.com/conan-io/conan/issues/1020) but from the documentation I understood that it should be enough when packaging (export-pkg) "project_B" I define the same options (command line) as for "project_A"? 

If I open the conaninfo.txt for "project_A" I can see the options passed via command line. Obviously I'm still missing something?

**Comment by lasote** [comment]
Hi, try to use always "scoped" options: `-o project_A:option_a=a1`.
If you don't specify `default_options` you'll need to define the options at some point. 
I'm not sure, but you could try something like `-o *:option_a=a1`

**Comment by unzap** [comment]
Thanks @lasote, it was about defining options. I was able to solve it by changing the recipe a bit:

    options = {"option_a":    ["option_a"],
               "option_b":    ["option_b"],
               "option_c":    ["option_c"]
              }

    default_options = {"option_a":    "option_a",
                       "option_b":    "option_b",
                       "option_c":    "option_c"
                      }

I'm using a recipe template where I'm writing the possible options on the fly, based on the used build configuration for that specific module & build options (pre-built binaries).

Though now I got a different issue when trying to install:

A/1.0@user/channel -> B/1.0@user/channel -> C/1.0@user/channel

All the binary packages in the dependency chain contain e.g. common directory "/lib", when I run "conan install <reference>" it will give:

C/1.0@user/channel: Already installed!
B/1.0@user/channel: Already installed!
...

@memsharded is there any way to force overwriting directories in "def deploy()" in an easy way?
Or is the "error" message related to something else?

**Comment by unzap** [comment]
@lasote I tried to scope when running "export-pkg" and when executing "install", but no success yet.
I'm also defining all "default_options" in conanfile.py. "def requirements()" is not implemented, I'm using the "default_options" attribute.

    conan export-pkg . -f project_A/1.0@user/channel -s os="Linux" -o *:option_a="option_a" -o *:option_b="option_b"
    conan export-pkg . -f project_B/1.0@user/channel -s os="Linux" -o *:option_a="option_a" -o *:option_b="option_b"

B depends on A:

    requires = "A/1.0@user/channel"

Then

    conan install -if . B/1.0@user/channel -s os="Linux" -o *:option_a="option_a" -o *:option_b="option_b"

    B/1.0@user/channel: Already installed!
    A/1.0@user/channel: Already installed!

**Comment by lasote** [comment]
To discard any parsing issue try to specify it like this (using =): `-o=*:option_a="option_a"`
By the way, all the dependencies contain the same options? Have you considered create a custom setting or it makes no sense for you?

**Comment by unzap** [comment]
> To discard any parsing issue try to specify it like this (using =): `-o=*:option_a="option_a"`

Thanks, I updated my scripts as you suggested, when creating packages with "export-pkg" and when invoking "conan install" for main package. But still no luck?

    conan export-pkg . -f C/1.0@user/channel -s os="Linux" -o=*:option_a="option_a" -o=*:option_b="option_b" -o=*:option_c="option_c"
    conan export-pkg . -f B/1.0@user/channel -s os="Linux" -o=*:option_a="option_a" -o=*:option_b="option_b" -o=*:option_c="option_c"
    conan export-pkg . -f A/1.0@user/channel -s os="Linux" -o=*:option_a="option_a" -o=*:option_b="option_b" -o=*:option_c="option_c"

    conan upload ....

    conan install -if . A/1.0@user/channel -s os="Linux" -o=*:option_a="option_a" -o=*:option_b="option_b" -o=*:option_c="option_c"


    C/1.0@user/channel: Already installed!
    B/1.0@user/channel: Already installed!
    A/1.0@user/channel: Already installed!

The installation directory (-if .) contains only:
- conanfile.py
- conaninfo.txt
- conanmanifest.txt
- conan_package.tgz
- deploy_manifest.txt

but the actual build artifacts (all dependencies, A, B, C) are missing?

> By the way, all the dependencies contain the same options?

Yes

**C: conanfile.py:**

    options = {"option_a":    ["option_a"],
               "option_b":    ["option_b"],
               "option_c":    ["option_c"]
              }

    default_options = {"option_a":    "option_a",
                       "option_b":    "option_b",
                       "option_c":    "option_c"
                      }

    requires = ""

**B: conanfile.py:**

    options = {"option_a":    ["option_a"],
               "option_b":    ["option_b"],
               "option_c":    ["option_c"]
              }

    default_options = {"option_a":    "option_a",
                       "option_b":    "option_b",
                       "option_c":    "option_c"
                      }

    requires = "C/1.0@user/channel"

**A: conanfile.py:**

    options = {"option_a":    ["option_a"],
               "option_b":    ["option_b"],
               "option_c":    ["option_c"]
              }

    default_options = {"option_a":    "option_a",
                       "option_b":    "option_b",
                       "option_c":    "option_c"
                      }

    requires = "B/1.0@user/channel", "C/1.0@user/channel"

> Have you considered creating a custom setting or it makes no sense for you?

Oh, I originally thought that the possible values are already defined in the settings file. After re-reading this: https://docs.conan.io/en/latest/reference/config_files/settings.yml.html I noticed that I can extend the values. Thanks for pointing out this, I'll have a look. But are settings and options treated differently what comes to the issue I'm facing at the moment?

**Comment by unzap** [comment]
@lasote I think I got it solved. I ditched all the options (and default_options) and customized settings in the .yml file like you suggested, now it actually installs the files, including dependencies. Options had no effect? Next I'll try to create packages (pre-built binaries) under same reference but different build configuration.
