### ISSUE TITLE
Binary package not matching due to option deleted in package_id()

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4515]
hi,

i have a package `ect` here with an option i am using in the `requirements()` method but it should not affect the package id so it is removed from the `self.info.options` in the `package_id()` method:

conanfile.py:
```
options = {"alias_locking": [ True, False ]}
default_options = {"alias_locking": False}

def package_id(self):
    del self.info.options.alias_locking
```

The `conaninfo.txt` of the binary package then looks like this (BTW what is `options` vs. `full_options`?):
```
...
[options]

...
[full_options]
    alias_locking=False
...
```

When trying to install the package with `conan install ect/a48c7f7@ci/develop -u -r artifactory`, the deleted option is taken into account though for the package ID so i get the following error:
```
ect/a48c7f7@ci/develop: WARN: Can't find a 'ect/a48c7f7@ci/develop' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=RelWithDebInfo, compiler=Visual Studio, compiler.runtime=MD, compiler.version=15, os=Windows
- Options: alias_locking=False, ...
- Package ID: eb42ef7dbf7375234cd29702c1185e3fc80f6e05

ERROR: Missing prebuilt package for 'ect/a48c7f7@ci/develop'
Try to build it from sources with "--build ect"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

Should the option be removed in a different way? What am i missing?

thx,
Peter

P.S.:

Conan 1.8.2
Windows 10

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
Hi @petermbauer !

Your approach to remove the option is correct.

I think you have some old cached package in Artifactory. Did you try remove that package before to upload? Now you have the same package id, but probably you have the old package there with `alias_locking` as part of package id.

To remove the package from remote:

    conan remove -r artifactory ect/a48c7f7@ci/develop

**Comment by petermbauer** [comment]
thx for responding!
I took the `conaninfo.txt` directly from the Artifactory Web Interface and also checked the `conanfile.py` there. Anything else i could check?
The `options` attribute is actually inherited from a baseclass taken from a `python_requires`, could this cause the troubles?

**Comment by uilianries** [comment]
> I took the `conaninfo.txt` directly from the Artifactory Web Interface and also checked the `conanfile.py` there. Anything else i could check?

What did you find there?

> The `options` attribute is actually inherited from a baseclass taken from a `python_requires`, could this cause the troubles?

If I understand, alias_locking is from the base class, is that correct? I need to investigate.

**Comment by petermbauer** [comment]
I found the conaninfo.txt with the option not 
present in the [options] but in the [full_options] section as stated in the initial description. Is this correct or shouldn't it be there either?
And i found the correct conanfile.py there as mentioned above so i am wondering why the option is considered when doing the `conan install`.

Yes, the option comes from the base class.

**Comment by petermbauer** [comment]
I also checked the build log, the option also does not appear there:
```
[build] $ cmd.exe /C "conan install .. -u -r 34d1fde2-24a2-4dae-8149-f98b9a272df3 && exit %%ERRORLEVEL%%"

Configuration:
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=RelWithDebInfo
[options]
[build_requires]
[env]

```

**Comment by uilianries** [comment]
I'm trying to reproduce your scenario. Could you please, paste which commands did execute? Including the base python recipe.

**Comment by petermbauer** [comment]
Sorry, the use-case is not relevant anymore to us and i have not found the time to reproduce the issue.
