### ISSUE TITLE
Can not search in broken remotes

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4517]
To help us debug your issue please explain:

When I use some temporary remote to make a test (Artifactory or Conan Server), and after to finish it, I shutdown the server instance, but I don't remove it from my remote list.

Conan crashes while searching for a package on a unavailable remote.

    conan_server &
    conan remote add local http://localhost:9300
    conan upload foo/0.1@demo/testing
    killall conan_server
    conan search -r all foo/0.1@demo/testing

As you can see, the steps above try to demonstrate the situation where a remote is no available, but is listed as valid. The possible Conan output will be:

> ERROR: HTTPConnectionPool(host='localhost', port=9300): Max retries exceeded with url: /v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb41c042668>: Failed to establish a new connection: [Errno 111] Connection refused'))

> Unable to connect to local=http://localhost:9300

A similar output is showed for Artifactory.

Maybe we should ignore broken remotes and print an warning instead, but only when searching for a package and using ALL remotes. Or maybe we could add a new option `--ignore` and support it for any case.

Conan Version: 1.12.2

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Minimonium** [comment]
See #2945

**Comment by uilianries** [comment]
Thanks!
