### ISSUE TITLE
Package development flow does not work with settings.os_target and settings.arch_target

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#4519]
A `conanfile.py` with `settings.os_target` and/or `settings.arch_target` will fail to work using the package development flow:

**conanfile.py**:
```
# -*- coding: utf-8 -*-

from conans import ConanFile


class FooConan(ConanFile):
    name = "FooPackage"
    version = "1.2.3"
    settings = "compiler", "os_build", "arch_build", "os_target", "arch_target"
```

This command fails:
```
conan source . -sf src
```

The output is:
```
ERROR: 'settings.os_target' value not defined
```
- conan 1.12.2
- python 3.6.8
- Fedora Linux 28

**Comment by uilianries** [comment]
Hi @madebr !

The issue #2428 is very similar. Indeed you need to specify the targets, but I didn't find any detail on docs, only that issue.

@lasote Is there any consideration about this issue and #2301?

Regards!

**Comment by lasote** [comment]
The cross-build model is in the roadmap for Conan 2.0. But we haven't started with it... sorry.

**Comment by memsharded** [comment]
This is outdated, ``os_target``, ``arch_target`` no longer exist in the new cross-build model with 2 profiles. Closing.
