### ISSUE TITLE
Getting id inside jenkins build

### ISSUE THREAD

**Issue by Crejan** [conan-io/conan#4521]
I am using the jenkins artifactory plugin for the build and i am wondering if it is possible to retrieve the result of the command ```conan info . -n id``` somehow. The command conanClient.run(...) only gives me a buildInfo object and it seems to be impossible to retrieve the actual output of the command.

**Comment by lasote** [comment]
You can use `conan info . -n id --json path.json` and get the results from loading the json file: `https://jenkins.io/doc/pipeline/steps/pipeline-utility-steps/#readjson-read-json-from-files-in-the-workspace`

**Comment by Crejan** [comment]
This does not create a json file on my system.
According to --help this only works with a given build order

**Comment by lasote** [comment]
With the latest Conan it does work.
