### ISSUE TITLE
Cmake cache unable to load error

### ISSUE THREAD

**Issue by deekshith-elear** [conan-io/conan#4522]
Hi
when i was trying to build my c code using conan build it is giving below error
PROJECT: Installing /home/venkatadeekshith/conan_final/elearpkg/conanfile.py
Requirements
Packages

PROJECT: Generator cmake created conanbuildinfo.cmake
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
Project: Running build()
Error: could not load cache
ERROR: elearcommon/0.1@PROJECT: Error in build() method, line 31
	cmake.build()
	ConanException: Error 256 while executing cmake --build '/home/venkatadeekshith/conan_final/elearpkg/build' '--' '-j4'

**Comment by uilianries** [comment]
Hi @deekshith-elear !

This error comes from CMake, it was not able to find all cache generated by CMake configure. Did you run `cmake.configure()` ? There is an excellent documentation [here](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#cmake-reference).

Could you please paste your recipe here? Also, which commands are you running, could you paste the complete command line?

Regards!

**Comment by deekshith-elear** [comment]
Hi @uilianries 
***************************
Recipe file
***************************
from conans import ConanFile, CMake, tools


class ElearcommonConan(ConanFile):
    name = "elearcommon"
    version = "0.1"
    license = "<Put the package license here>"
    author = "deekshith-elear  venkatadeekshith@elear.solutions"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of Elearcommon here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "cmake"

    def source(self):
        #self.run("git clone https://github.com/memsharded/hello.git")
        self.run("cd elearcommon && git checkout master")
        # This small hack might be useful to guarantee proper /MT /MD linkage
        # in MSVC if the packaged project doesn't have variables to set it
        # properly
        tools.replace_in_file("elearcommon/CMakeLists.txt", "PROJECT(elearcommon)",
                             '''PROJECT(elearcommon)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()''')

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder="elearcommon")
        cmake.build()

        # Explicit way:
        # self.run('cmake %s/hello %s'
        #          % (self.source_folder, cmake.command_line))
        # self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.copy("*.h", dst="include", src="elearcommon")
        self.copy("*hello.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
       self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["elearcommon"]
****************************
Commands
****************************
conan source . --source-folder=./source
conan install . --install-folder=build
conan build . --source-folder=./source/. --build-folder=build
conan package . --source-folder=./source/. --build-folder=build --package-folder=package
conan export-pkg . demo/newpkgelear --source-folder=./source/. --build-folder=build -f

**Comment by uilianries** [comment]
All commands looks good, please, try removing all cache and execute all steps again:

    rm -rf package/ source/ build/

I'm not sure about your CMake file, as you are not using the hello example, I think it should okay, since the replace_in_file is not raising an error.

**Comment by deekshith-elear** [comment]
Thanks @uilianries 
it's working fine. now I'm facing problem when i was crossbuilding using profiles 
************
Profile
************
standalone_toolchain=/opt/elear-solutions/toolchain_armeabi_v7a_19 # Adjust this path
target_host=arm-linux-androideabi
cc_compiler=gcc
cxx_compiler=g++

[settings]
compiler=gcc
compiler.version=5.4
compiler.libcxx=libstdc++
os=Android
os.api_level=19
arch=armv7
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CMAKE_C_COMPILER=$standalone_toolchain/bin/$target_host-gcc
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
CFLAGS= --sysroot=$standalone_toolchain/sysroot
CXXFLAGS= --sysroot=$standalone_toolchain/sysroot
LDFLAGS= -L$standalone_toolchain/usr/lib

******************
Error
******************
Project: Running build()
-- Conan: called by CMake conan helper
-- Conan: Compiler GCC>=5, checking major version 5.4
-- Conan: Checking correct version: 5.4
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: C++ stdlib: libstdc++
-- Conan: called by CMake conan helper
-- Conan: Compiler GCC>=5, checking major version 5.4
-- Conan: Checking correct version: 5.4
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: C++ stdlib: libstdc++
-- WARNING: Platform set to: linux
-- CMAKE_BINARY_DIR:         /home/venkatadeekshith/conan_final/elearpkg/build
-- CMAKE_CURRENT_BINARY_DIR: /home/venkatadeekshith/conan_final/elearpkg/build
-- CMAKE_SOURCE_DIR:         /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon
-- CMAKE_CURRENT_SOURCE_DIR: /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon
-- PROJECT_BINARY_DIR: /home/venkatadeekshith/conan_final/elearpkg/build
-- PROJECT_SOURCE_DIR: /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon
-- EXECUTABLE_OUTPUT_PATH: 
-- LIBRARY_OUTPUT_PATH:     
-- CMAKE_MODULE_PATH: 
-- CMAKE_COMMAND: /usr/bin/cmake
-- CMAKE_ROOT: /usr/share/cmake-3.5
-- CMAKE_CURRENT_LIST_FILE: /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/CMakeLists.txt
-- CMAKE_CURRENT_LIST_LINE: 179
-- CMAKE_INCLUDE_PATH: 
-- CMAKE_LIBRARY_PATH: 
-- CMAKE_SYSTEM: Linux-4.15.0-43-generic
-- CMAKE_SYSTEM_NAME: Linux
-- CMAKE_SYSTEM_VERSION: 4.15.0-43-generic
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- UNIX: 1
-- WIN32: 
-- APPLE: 
-- MINGW: 
-- CYGWIN: 
-- BORLAND: 
-- MSVC: 
-- MSVC_IDE: 
-- MSVC60: 
-- MSVC70: 
-- MSVC71: 
-- MSVC80: 
-- CMAKE_COMPILER_2005: 
-- CMAKE_SKIP_RULE_DEPENDENCY: 
-- CMAKE_SKIP_INSTALL_ALL_DEPENDENCY: 
-- CMAKE_SKIP_RPATH: NO
-- CMAKE_VERBOSE_MAKEFILE: FALSE
-- CMAKE_SUPPRESS_REGENERATION: 
-- CMAKE_C_FLAGS:   -m64   -m64 -pedantic-errors -Wall -std=c11 -D_GNU_SOURCE -Os -fno-asynchronous-unwind-tables -flto -pedantic-errors -Wall -std=c11 -D_XOPEN_SOURCE=700 -O2
-- CMAKE_CXX_FLAGS:   -m64   -m64
-- CMAKE_BUILD_TYPE: Release
-- BUILD_SHARED_LIBS: OFF
-- CMAKE_C_COMPILER: /usr/bin/cc
-- CMAKE_CXX_COMPILER: /usr/bin/c++
-- CMAKE_COMPILER_IS_GNUCC: 1
-- CMAKE_COMPILER_IS_GNUCXX : 1
-- CMAKE_AR: gcc-ar
-- CMAKE_RANLIB: /usr/bin/ranlib
-- Configuring done
-- Generating done
In file included from /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/list.c:26:0:
/home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/logger.h:31:20: fatal error: string.h: No such file or directory
compilation terminated.
CMakeFiles/elearcommon.dir/build.make:62: recipe for target 'CMakeFiles/elearcommon.dir/list.c.o' failed
make[2]: *** [CMakeFiles/elearcommon.dir/list.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/json_services.c:27:19: fatal error: errno.h: No such file or directory
 #include <errno.h>
                   ^
compilation terminated.
/home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/json_services.c:27:19: fatal error: errno.h: No such file or directory
 #include <errno.h>
                   ^
compilation terminated.
CMakeFiles/elearcommon.dir/build.make:86: recipe for target 'CMakeFiles/elearcommon.dir/json_services.c.o' failed
make[2]: *** [CMakeFiles/elearcommon.dir/json_services.c.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/elearcommon.dir/all' failed
make[1]: *** [CMakeFiles/elearcommon.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/elearcommon_static.dir/build.make:86: recipe for target 'CMakeFiles/elearcommon_static.dir/json_services.c.o' failed
make[2]: *** [CMakeFiles/elearcommon_static.dir/json_services.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/list.c:26:0:
/home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/logger.h:31:20: fatal error: string.h: No such file or directory
compilation terminated.
CMakeFiles/elearcommon_static.dir/build.make:62: recipe for target 'CMakeFiles/elearcommon_static.dir/list.c.o' failed
make[2]: *** [CMakeFiles/elearcommon_static.dir/list.c.o] Error 1
[ 12%] Building C object CMakeFiles/elearcommon_static.dir/unordered_map.c.o
[ 15%] Building C object CMakeFiles/elearcommon_static.dir/double_linked_list.c.o
In file included from /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/allocate.h:33:0,
                 from /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/unordered_map.c:29:
/usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h:9:26: fatal error: stdint.h: No such file or directory
compilation terminated.
CMakeFiles/elearcommon_static.dir/build.make:110: recipe for target 'CMakeFiles/elearcommon_static.dir/unordered_map.c.o' failed
make[2]: *** [CMakeFiles/elearcommon_static.dir/unordered_map.c.o] Error 1
In file included from /home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/double_linked_list.c:26:0:
/home/venkatadeekshith/conan_final/elearpkg/source/elearcommon/logger.h:31:20: fatal error: string.h: No such file or directory
compilation terminated.
-------------
cmake c compiler is taking standard gcc path insted of cross compilation tool chain
could you please help me out to resolve this issue

**Comment by uilianries** [comment]
Hi @deekshith-elear !

I have a pretty similar profile for armhf, my file looks like:

```
# ~/.conan/profiles/armhf
target_host=arm-linux-gnueabihf
standalone_toolchain=/opt/gcc-arm-linux-gnueabihf
cc_compiler=gcc
cxx_compiler=g++

[settings]
os_build=Linux
arch_build=x86_64
os=Linux
arch=armv7hf
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
LD=$target_host-ld
STRIP=$target_host-strip
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
CXXFLAGS=-I"$standalone_toolchain/lib/include"
```

But also I check using `conan profile`:

```
$ conan profile show armhf
Configuration for profile armhf:

[settings]
os_build=Linux
arch_build=x86_64
os=Linux
arch=armv7hf
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
CONAN_CMAKE_FIND_ROOT_PATH=/opt/gcc-arm-linux-gnueabihf/sysroot
PATH=['/opt/gcc-arm-linux-gnueabihf/bin']
CHOST=arm-linux-gnueabihf
AR=arm-linux-gnueabihf-ar
AS=arm-linux-gnueabihf-as
RANLIB=arm-linux-gnueabihf-ranlib
LD=arm-linux-gnueabihf-ld
STRIP=arm-linux-gnueabihf-strip
CC=arm-linux-gnueabihf-gcc
CXX=arm-linux-gnueabihf-g++
CXXFLAGS=-I"/opt/gcc-arm-linux-gnueabihf/lib/include"
```

Please, check your profile output command, also remove your current cache. I would say that your sysroot path is wrong or your cache is mixed with x86_64 from the last build.

There is a section on documentation that explains about Android build:
https://docs.conan.io/en/latest/systems_cross_building/cross_building.html?highlight=conan_cmake_find_root_path#linux-windows-macos-to-android

Regards!

**Comment by deekshith-elear** [comment]
Thanks @uilianries 
In my profile if i was mentioning complete path insted of using variables it's working fine
like
 
----
AR=/opt/elear-solutions/toolchain_armeabi_v7a_19/bin/arm-linux-androideabi-ar
AS=/opt/elear-solutions/toolchain_armeabi_v7a_19/bin/arm-linux-androideabi-as
RANLIB=/opt/elear-solutions/toolchain_armeabi_v7a_19/bin/arm-linux-androideabi-ranlib
CC=/opt/elear-solutions/toolchain_armeabi_v7a_19/bin/arm-linux-androideabi-clang
CXX=/opt/elear-solutions/toolchain_armeabi_v7a_19/bin/arm-linux-androideabi-$cxx_compiler
LD=/opt/elear-solutions/toolchain_armeabi_v7a_19/bin/arm-linux-androideabi-ld
STRIP=/opt/elear-solutions/toolchain_armeabi_v7a_19/bin/arm-linux-androideabi-strip
CFLAGS= --sysroot=/opt/elear-solutions/toolchain_armeabi_v7a_19/sysroot
------
but i didn't get why its not working with below format

------
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
-----
