### ISSUE TITLE
[question] cmake_find_package workspaces

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4523]
Hi there,
as already been [asked for "cmake_paths" generator](https://github.com/conan-io/conan/issues/3302) I did not find informations for the ```cmake_find_package``` generator. Maybe I overlooked something. 

Does the workspace feature support the ```cmake_find_package``` generator yet?
(or ```cmake_find_package``` generator supports the workspace feature)

Best regards

**Comment by lasote** [comment]
Hi, the workspaces feature is being refactored and completed, but it will take at least a couple more releases to be completed. I'm marking this issue and some other as feedback. I think the current implementation doesn't cover the `cmake_find_package` generator use case but @memsharded knows more.

**Comment by Lawrencemm** [comment]
I'm currently using this here: https://github.com/Lawrencemm/workspace

**Comment by Johnnyxy** [comment]
@Lawrencemm can you elaborate where you use the ```cmake_find_package``` generator in the given repository?

**Comment by Lawrencemm** [comment]
The submodules when checked out consume via find package. 

Calling Conan install in the workspace directory generates a working build directory where the submodules have the find cmake modules generated correctly.

**Comment by Lawrencemm** [comment]
I'd just like to add that atm the FindXXX scripts are placed in subdirectories of the install folder (each package gets its own set).

At the moment I'm using a hack in each package's CMakeLists: adding CURRENT_BINARY_DIR to CMAKE_MODULE_PATH so they can find the modules Conan placed in their build subdirectory.

If the FindXXX scripts were instead placed into the root install folder, I could set the CMAKE_MODULE_PATH on the cmake command line and remove this hack.

**Comment by Lawrencemm** [comment]
Hi guys,

So I'm changing my tune on this.

The problem with combining all the cmake find modules in the main binary directory is that it'll mix up the build_requires of each package and create conflicts where there shouldn't be.

I think I might have a simple solution.

For a workspaces find_package generator in the generated conanworkspace.cmake script, add a line 
`
set(CMAKE_MODULE_PATH ${PACKAGE_<package>_BUILD})
`
before add_subdirectory for each package.

**Comment by Lawrencemm** [comment]
I think `cmake_paths` could be a valid alternative generator for the overall workspace which would work in conjunction with the find_package generator for the respective packages. #3302

**Comment by lasote** [comment]
@Johnnyxy may the last comment at #3302 from @Lawrencemm solve this issue? Looks promising.

**Comment by Lawrencemm** [comment]
You could actually have a `find_package` workspace generator similar to the `cmake_paths` idea:

```
set(PACKAGE_foo_SRC "...")
set(PACKAGE_foo_BUILD "...")
set(PACKAGE_bar_SRC "...")
set(PACKAGE_bar_BUILD "...")
macro(conan_workspace_subdirectories)
    set(OLD_MODULE_PATH ${CMAKE_MODULE_PATH})

    set(CMAKE_MODULE_PATH ${PACKAGE_foo_BUILD} ${OLD_MODULE_PATH})
    add_subdirectory(${PACKAGE_foo_SRC} ${PACKAGE_foo_BUILD})

    set(CMAKE_MODULE_PATH ${PACKAGE_bar_BUILD} ${OLD_MODULE_PATH})
    add_subdirectory(${PACKAGE_bar_SRC} ${PACKAGE_bar_BUILD})

    set(CMAKE_MODULE_PATH ${CMAKE_OLD_MODULE_PATH})
endmacro()
```

I just tested this and it works.

I'm 99% sure there will be unintended interactions with complicated CMake builds but since this is an opt-in I think it's an OK solution for now.

**Comment by Johnnyxy** [comment]
@lasote I did not adopt workspaces for my project until now. And my time is bound to another topic at the moment (QNX). As of now I cannot make a qualitfied comment on this :(.

Generally I prefere the ```cmake_find_package``` generator as it decouples Conan and CMake completely and one can see exactly what Conan gives (include paths, libs, ...) to CMake through the generated ```FindXXX.cmake``` files.
The ```cmake_paths``` generator on the other hand does provide only "paths" and CMake searches for any ```FindXXX.cmake``` files in them. This means actually it could find other files (custom files which maybe came with a package) too. More fuzzy :).
This is less specific what makes bug hunting maybe a little harder.

But if there is a solution that generally works then this thread could be closed. Feel free to do so.
I will look into this topic at a later time.

**Comment by lasote** [comment]
Yeah, we need also to think about it. It is not the same to generate from the roots the `FindXXX` files or find them in the "subprojects". Also, we need to try what happens if you edit some files in the subproject: Will CMake from the root be able to refresh the changes?

**Comment by Lawrencemm** [comment]
It should be noted that what I've presented here can actually be implemented by the user in their own CMakeLists that includes the conan workspace cmake file. 

They can define the project includes themselves and it will still work. Maybe it would be a good idea to put this in the documentation as a suggested option for using cmake_paths with workspaces.

If you think this is a good idea then I might make a PR to the docs repo.

About your question on cmake detecting changes in subprojects, I'd have thought this would work by definition. The targets in a cmake subdirectory are just normal targets, and every package in the workspace is included as a subdirectory.

I'm not exactly sure what you mean about generating FindXXX files from the roots, could you elaborate?

**Comment by lasote** [comment]
There are two approaches for a hypothetical `cmake_find_package` for a workspace. 
- The first approach is actually don't have it, and have only the `cmake_paths`, but applying to each subproject the `cmake_find_package` generator.
- The second approach is to have it at the workspace level. This generator could generate the `FindXXX` scripts for all the subprojects. 

I think the correct approach is the first one, so this issue might be invalid if we have the workspace `cmake_paths` generator.
About CMake refreshing the changes, yes, it should work, as the target files would change, but I would like to try it.

**Comment by izzyreal** [comment]
I too would like to be able to say
```
editables:
    foo/0.1@foo/dev:
        path: foo
layout: layout
generators: cmake_find_package
workspace_generator: cmake
root: bar/0.1@foo/dev
```

I'm trying to make my `CMakeList.txt` files Conan-agnostic. Is this possible without `generators: cmake_find_package` support?

**Comment by memsharded** [comment]
Hi @izzyreal 

Yes, it is very possible to make CMakeLists.txt totally Conan agnostic. Using the new build system integrations in https://docs.conan.io/en/latest/reference/conanfile/tools.html, you can achieve that. Get a fully working example with ``conan new hello/0.1 --template=cmake_lib`` template.

A different story are the workspaces, they have been put on hold in 1.X for a long time, and they have been already removed in 2.0, because of being half-baked. For editables it is important to start using the new ``layout()`` feature (https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html), as the external ini-like layout file has been removed in 2.0 too

**Comment by izzyreal** [comment]
Thanks @memsharded, I will try your suggestions.

However, if workspaces are removed from 2.0, is there a new umbrella concept so I can arrange editables into a single workspace?

**Comment by memsharded** [comment]
> However, if workspaces are removed from 2.0, is there a new umbrella concept so I can arrange editables into a single workspace?

Not initially, but there will be custom Conan user commands, that you can implement, install with ``conan config install``, and that will be able to access a public Python API. It will be very possible to code a customized equivalent, but very customized at your will, with few lines of code. Note that ``editables`` in 2.0 have gained new possibilities, like being able to build themselves, in order with ``--build=editable``. Then, later at some 2.X we will probably resume working on this feature, but not a high priority at the moment.

**Comment by izzyreal** [comment]
Thanks again for the clear and elaborate info @memsharded 👌

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
