### ISSUE TITLE
Warnings as errors for the test suite

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4527]
I've come across #4518 where we were calling a function without the `output` argument (then it will use the `global_outputer` and print a warning). In order to avoid this kind of _typos_ we could use the warnings-as-errors approach for testing.

It is as easy as calling

```python
import warnings
warnings.filterwarnings("error")
```

and then all the warnings will turn into exceptions.

.... of course we must be sure that this line is only executed in testing, we can put it in `conans/tests/__init__.py`.

WDYT @conan-io/barbarians?

**Comment by uilianries** [comment]
Since is only for testing, I like the idea. It sounds like `-Werror`

**Comment by danimtb** [comment]
Yeah, I think it is better than my approach in #4518. However, I wouldn't like it to be very picky if we have a ton of warnings in the test suite...

It is worth a try I guess

**Comment by lasote** [comment]
I'm not very aware of how many warnings are we using, but maybe that's a reason to try this idea and see what happen. Could it be tried very quickly? you could write here the conclusions about how it looks to help to take a decision. I would suggest tagging this as "look into" with some priority and assign to the release. Just to try it.
