### ISSUE TITLE
[question] Dynamic requirements' dependency

### ISSUE THREAD

**Issue by mcsahin** [conan-io/conan#4528]
Hi, 
We have so many libraries so, to reduce conanfile.py count, in continues integration tool we are using require() method to set dynamic dependencies. 

Here is a simple example, we have a dependency tree as:
**projectA depends on libA
libA depends on libX**

Here is **libA** code part:
```
    def require(self):
        if tools.get_env('DEPENDENCY_SET_1'):
            self.require("libX/1.3.1@user/channel")
        elif tools.get_env('DEPENDENCY_SET_2'):
            self.require("libX/1.3.4@user/channel")

    def package_id(self):
        self.info.requires("libX").full_package_mode()     
```

Result of libA creation:
```
    libA/1.0.0@user/channel
    |
    |_____ package
             |
             |______ 21bd4bd70eddbbc24026f8579b365443249bed87 (depends libX/1.3.1@user/channel)
             |______ 76d1c80168da91a5a67085e27915726b688c1f12c (depends libX/1.3.4@user/channel)
```

Here is **projectA** code part:
```
    requires = "libA/1.0.0@user/channel"

```

**Question:
    Is it possible to create two packages for projectA like below with only one conanfile.py?**

```
    projectA/1.0.0@user/channel
    |
    |_____ package
             |
             |______ 21bd4bd70eddbbc24026f8579b365443249bed87 (depends libX/1.3.1@user/channel)
             |______ 76d1c80168da91a5a67085e27915726b688c1f12c (depends libX/1.3.4@user/channel)
```

**Comment by uilianries** [comment]
Hi @mcsahin !

Yes, it's possible, since you follow the same approach used for libA. You will need to set a condition to choose the wished requirement.

```
def require(self):
        if tools.get_env('PROJECTA_USES_LIBA'):
            self.require("libA/1.0.0@user/channel")
        else:
            self.require("libX/1.3.1@user/channel")
            self.require("libX/1.3.4@user/channel")
```

However I would prefer [options](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#options) instead of env vars.

Regards!

**Comment by mcsahin** [comment]
Hi @uilianries,
I have closed this question because I have another question #4530. I do not need to disturb community with two questions at the same time :)

Thanks for your answer and fast response. In my example; libX is a transitive requirement for projectA and so, I don't need to write transitive dependency on projectA's conanfile.

Moreover as you know requirements' versions effects package's sha as options. So, i am curious is there way to change packages's sha with transitive requirement change?

Best regards

**Comment by uilianries** [comment]
> Moreover as you know requirements' versions effects package's sha as options. So, i am curious is there way to change packages's sha with transitive requirement change?

It's the default behavior, as described on [defining-package-abi-compatibility](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#defining-package-abi-compatibility)
