### ISSUE TITLE
[question] Resolving alias names and replacing in conanfile.py

### ISSUE THREAD

**Issue by mcsahin** [conan-io/conan#4530]
Hi,
While using conan with continues integration tools; I need to create a package with the latest exact versions of dependencies. 

Here is my conanfile.py:
```
class myProject(ConanFile):
    name = "myproject"
    settings = "os", "compiler", "arch"

    requires = "libA/latest@user/channel"
```

I am creating my 1.0.0 version:
```
> conan inspect libA/latest@user/channel -a alias
   alias: libA/1.0.0@user/channel
> conan create . myproject/1.0.0@user/channel
> conan info myproject/1.0.0@user/channel
    .....
    dependency: libA/1.0.0@user/channel

```

When I change the link of libA:
```
> conan alias  libA/latest@user/channel libA/2.0.0@user/channel
> conan info myproject/1.0.0@user/channel
    .....
    dependency: libA/2.0.0@user/channel  !!!!!!!!!!!!!!!

```

As you see above I did not call "conan create" but dependency changed from libA/1.0.0 to libA/2.0.0 and my project is still in "myproject/1.0.0" version. From the regular user perspective it is ok. 

But I don't need a change in my "myproject/1.0.0" dependency without a new create call. And also I need to use alias in my conanfile.py because the ease of use in continues integration.

**Is there a way to resolve and replace alias tags in conanfile while creating a package?**

**Comment by uilianries** [comment]
Hi @mcsahin !

It's because the `conan info` generates a dependency graph to get the information about your package. Since the alias is a symbolic link, it will be changed dynamically, thus this behavior is correct.

If you want to build your package using the latest version of a requirement, you could use [version ranges](https://docs.conan.io/en/latest/mastering/version_ranges.html#version-ranges) instead.

Regards!

**Comment by mcsahin** [comment]
Hi @uilianries,
I think, "version ranges" should perform a search to find the latest and this does not fit my requirements.

I am planning to resolve latest versions inside requirements() method. Is this rational?
```
# my function
def my_manual_resolve_function(self, reference):
    # run inspect command to get resolved version of alias
    output_buffer = StringIO()
    self.run(("conan inspect %s -a alias", reference), output=output_buffer)

    # discard garbage texts to get libA/1.0.0@user/channel
    resolved_version = my_parse_function(output_buffer)   # my_parse_function implementation is not given

    # return result string
    return resolved_version

# conan's function
def requirements(self):
    # libA/latest@user/channel will be converted to libA/1.0.0@user/channel if latest is 1.0.0
    resolved_reference_lib_a = my_manual_resolve_function("libA/latest@user/channel")

    # require manually
    self.requires(resolved_reference_lib_a)

```

**Comment by uilianries** [comment]
>  I think, "version ranges" should perform a search to find the latest and this does not fit my requirements.

Why not? Your recipe is looking for the latest version.

> I am planning to resolve latest versions inside requirements() method. Is this rational?

The requirements is the best place to solve the package requirements, but why use `alias` instead? Like I said before, the command `info` needs to generate a graph dependencies to list, but this will not affect your built packages.

**Comment by mcsahin** [comment]
> Why not? Your recipe is looking for the latest version.

Actually it concerns with automation in continues integration. It is very hard to share versions between projects in teamcity. Moreover latest tags are very simple and human readable but version ranges are complex. 
I am only defining latest tags as dependency version in teamcity, teamcity dynamically creates conanfile.py's requirements by using python script and conan does the rest.
Sorry, it is hard to tell all structure. There are many libraries and projects depends each other. I am trying to find an easy way to create, same versioned many different packages with different set of dependencies with a single conanfile.py

> The requirements is the best place to solve the package requirements, but why use `alias` instead? Like I said before, the command `info` needs to generate a graph dependencies to list, but this will not affect your built packages.

At the very beginning, I am faced up with a problem:
```
ERROR: Conflict in mylib/1.0.9@user/channel
        Requirement libA/latest@user/channel conflicts with already defined libA/2.0.0@user/channel
```
Problem was my "libA/latest" alias was also equal to "2.0.0". Then I tried to solve and fix problem but, as you said above  "conan info" was not using resolved alias tags. This disturbed me too much and finally i am trying to change my way :(

**Comment by uilianries** [comment]
If you need to retrieve some attribute using `inspect` I recommend you use Conan API instead, it's much safer.

This [example](https://github.com/bincrafters/bincrafters-conventions/blob/835cb54b748fc345528b21af19e3b5c79eaeeef2/bincrafters_conventions/actions/check_for_spdx_license.py#L16) is used to retrieve the license attribute, but you can re-use it for alias as well.

Regards!

**Comment by mcsahin** [comment]
Hi @uilianries,
> If you need to retrieve some attribute using `inspect` I recommend you use Conan API instead, it's much safer.
> This [example](https://github.com/bincrafters/bincrafters-conventions/blob/835cb54b748fc345528b21af19e3b5c79eaeeef2/bincrafters_conventions/actions/check_for_spdx_license.py#L16) is used to retrieve the license attribute, but you can re-use it for alias as well.

Thanks for this solution.


> It's because the `conan info` generates a dependency graph to get the information about your package. Since the alias is a symbolic link, it will be changed dynamically, thus this behavior is correct.

Finally, how can a user get information (dependency graph) about and old versioned package, created by using "latest" alias?  `conan info` is using current "latest" alias link to show information but while creating old package "latest" was different.

Kind regards.

**Comment by uilianries** [comment]
Hi @mcsahin !

`conan info` is a command for recipes, if you want to inspect old packages, you will need to pass the install folder related to package id that you are looking for.
    
    $ ls /home/uilian/.conan/data/bar/0.1/uilianries/testing/package/34d84d64c5d7f94b11a400d4a2d0d4aebc4ac348
    conaninfo.txt  conanmanifest.txt  include  lib

    $ conan info bar/0.1@uilianries/testing  -if /home/uilian/.conan/data/bar/0.1/uilianries/testing/package/34d84d64c5d7f94b11a400d4a2d0d4aebc4ac348

For this example I used the package folder as installer. The recipe requires an `alias`, but the `conan info` will show the real version used by that package.

Regards!

**Comment by mcsahin** [comment]
Thank you so much @uilianries
