### ISSUE TITLE
scm replacement fails if scm = statement contains or is followed by blank line

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#4531]
conan 1.11.2, Windows 7

In one of my conanfiles, I am using the scm features, with a snippet that reads like

```
10:    scm = {
11:        "type": "git",
12:        "url": "https://github.deere.com/FOCUS/conan-strawberryperl-PAR-Packer.git",
13:        "revision": "auto"
14:    }
15: 
16:    # short_paths is needed for builds (the pp tests have some long paths), even though the package doesn't end up including any deep paths
17:    short_paths=True
```

When this recipe is expocted, the revision = "auto" is *not* replaced, even though I do get the message
```
package/1.0@user/channel: Revision deduced by 'auto': 570c6fe032219a17cc3268b7cf1858635e76bde8
```

I've tracked this back to https://github.com/conan-io/conan/blob/6ec73ac2b4be98e1ab4e5ee797008b50ca2d7424/conans/client/cmd/export.py#L208-L209

Basically, it looks like this code takes everythign from the statement assigning scm (e.g. line 10), up to but not including the line containing the next item in the body (so 10..16). 

But when forming a string it then skips over blank lines (e.g. line 15 is skipped). The resulting string in to_replace is then missing the blank line, so the https://github.com/conan-io/conan/blob/6ec73ac2b4be98e1ab4e5ee797008b50ca2d7424/conans/client/cmd/export.py#L216 doesn't find a match and doesn't replace anything.

So, to propose a couple of fixes:

* There should be an error if content.replace doesn't actually match to_replace; we never want to leave any "auto" values in the exported recipe.

* rather than skipping blank lines entirely in the list comprehension to assign replace, it should just trim leading or trailing blank lines, but retain those in the middle. 

* Maybe it should trim comment-only lines too, so as not to eat comments between scm= and the next assignment?

So maybe something like:

```diff
-                        replace = [line for line in lines[(stmt.lineno-1):next_line]
-                                   if line.strip()]
+                       replace = lines[(stmt.lineno-1):next_line]
+                       while re.fullmatch(r'\s*(#.*)?',replace[-1],re.DOTALL): 
+                            del replace[-1]
```

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Bug confirmed. Thanks for the detailed investigation.
I agree there should be an error when the replacement is supposed to happen but it doesn't.

**Comment by lasote** [comment]
I assume it is not critical, right? you already know how to workaround or is it blocking you?

**Comment by puetzk** [comment]
I rearranged the order of the lines around the `scm = {...}` statement so as to not trigger it for now.
