### ISSUE TITLE
Error uploading header-only package to bintray account

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#4536]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Conan 1.12.2**

Since two weeks ago, I get the following error while trying to upload one of my header only packages to my bintray conan repository:

``` shell
$ conan upload llvm_headers --all --confirm -r Manu343726
Uploading llvm_headers/6.0.1@Manu343726/testing to remote 'Manu343726'
Recipe is up to date, upload skipped
Uploading package 1/1: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 to 'Manu343726'
ERROR: . [Remote: Manu343726]
```

I've checked my bintray account and I see no out-of-storage warnings. I thought it could be some temporary issue in the bintray servers (I often get 504 errors from the bintray servers with conan upload when running parallel packaging CI jobs) so I just ignored the issue and retriggered the build. It's been two weeks now and the issue happens both locally and in CI. I tried to get some debug info by settings the client tracing file:

``` shell
$ tail -F /tmp/conan_trace.log                                                                                                       130 ↵
tail: no se puede abrir '/tmp/conan_trace.log' para lectura: No existe el fichero o el directorio
tail: '/tmp/conan_trace.log' has appeared;  following new file
{"_action": "COMMAND", "name": "upload", "parameters": {"all_packages": true, "confirm": true, "integrity_check": false, "package": null, "pattern": "llvm_headers", "policy": null, "query": null, "remote_name": "Manu343726", "retry": 2, "retry_wait": 5}, "time": 1550432250.937396}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "llvm-common/0.0.0@Manu343726/testing", "time": 1550432250.9522297}
{"_action": "REST_API_CALL", "duration": 0.6340270042419434, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.12.2 (Python 3.7.2) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "Manu343726"}, "method": "GET", "time": 1550432251.5894175, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/ping"}
{"_action": "REST_API_CALL", "duration": 0.1848738193511963, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.12.2 (Python 3.7.2) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "Manu343726"}, "method": "GET", "time": 1550432251.774718, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/conans/llvm_headers/6.0.1/Manu343726/testing/digest"}
{"_action": "REST_API_CALL", "duration": 0.34801363945007324, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.12.2 (Python 3.7.2) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********"}, "method": "GET", "time": 1550432252.1233125, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/files/Manu343726/llvm_headers/6.0.1/testing/export/conanmanifest.txt"}
{"_action": "DOWNLOAD", "duration": 0.34844231605529785, "time": 1550432252.123728, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/files/Manu343726/llvm_headers/6.0.1/testing/export/conanmanifest.txt"}
{"_action": "REST_API_CALL", "duration": 0.1709117889404297, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.12.2 (Python 3.7.2) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "Manu343726"}, "method": "GET", "time": 1550432252.2962108, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/users/check_credentials"}
{"_action": "REST_API_CALL", "duration": 0.18532299995422363, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.12.2 (Python 3.7.2) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "Manu343726"}, "method": "GET", "time": 1550432252.4819732, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/conans/llvm_headers/6.0.1/Manu343726/testing"}
{"_action": "UPLOADED_RECIPE", "_id": "llvm_headers/6.0.1@Manu343726/testing", "duration": 0.35808563232421875, "files": [{"md5": "7bd313ec88bb00eb160565c088b69b5a", "name": "conanfile.py", "path": "/home/manu343726/.conan/data/llvm_headers/6.0.1/Manu343726/testing/export/conanfile.py", "sha1": "fdfdc0e5af1ed18213902ffed46430f05313ef03"}, {"md5": "10b74b4052fc2595602e1a717fa0d1f1", "name": "conanmanifest.txt", "path": "/home/manu343726/.conan/data/llvm_headers/6.0.1/Manu343726/testing/export/conanmanifest.txt", "sha1": "b5f082b08c573eac502260affc48d6d0ad5e8fe1"}], "remote": "Manu343726", "time": 1550432252.4830725}
{"_action": "REST_API_CALL", "duration": 0.16553926467895508, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.12.2 (Python 3.7.2) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "Manu343726"}, "method": "GET", "time": 1550432252.6633537, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/users/check_credentials"}
{"_action": "REST_API_CALL", "duration": 0.17443108558654785, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.12.2 (Python 3.7.2) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "Manu343726"}, "method": "GET", "time": 1550432252.838232, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/conans/llvm_headers/6.0.1/Manu343726/testing/packages/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9"}
{"_action": "REST_API_CALL", "duration": 0.17860627174377441, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.12.2 (Python 3.7.2) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "Manu343726"}, "method": "GET", "time": 1550432253.0174942, "url": "https://api.bintray.com/conan/manu343726/conan-packages/v1/conans/llvm_headers/6.0.1/Manu343726/testing/packages/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/digest"}
{"_action": "EXCEPTION", "class": "NotFoundException", "message": ". [Remote: Manu343726]", "time": 1550432253.0185611}
```

For the record [here](https://gitlab.com/Manu343726/clang-conan-packages/pipelines/47557929) is one of the last CI runs that has failed. [This](https://gitlab.com/Manu343726/clang-conan-packages/-/jobs/162819389) is the job that fails to upload the header only package. Note that all previous packages in the pipeline work ok (Those are packaging hundreds of MB of LLVM, so I don't think that my bintray account being out-of-storage is the problem...).

Thanks in advance.

**EDIT:** This is the link to setup my [bintray repo](https://bintray.com/beta/#/manu343726/conan-packages?tab=packages):

```
https://api.bintray.com/conan/manu343726/conan-packages
```

**Comment by memsharded** [comment]
Yes, for some reason it seems that such package is missing its manifest: https://bintray.com/manu343726/conan-packages/llvm_headers%3AManu343726/6.0.1%3Atesting#files/Manu343726%2Fllvm_headers%2F6.0.1%2Ftesting%2Fpackage%2F5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

Don't you recall a broken transfer or something? You'd need to reupload that package, maybe using the ``--force`` option, or removing it first.

**Comment by Manu343726** [comment]
> Don't you recall a broken transfer or something?

As I noted in my first comment, when firing highly-parallel CI builds like the one from clang-conan-packages (tens of parallel jobs building and packaging the same package with different settings/options at the same time) I often get server errors from bintray, like if `conan upload` command was hitting a max server access rate or something. So I would not be surprised if a corrupted upload came from one of these failures.

> You'd need to reupload that package, maybe using the `--force` option, or removing it first.

The package was [successfully uploaded](https://gitlab.com/Manu343726/clang-conan-packages/-/jobs/163114280) after removing it first from my repo.

Now that I know a workaround for the issue I'm no longer worried about it. Do you need more info to try to diagnose the issue? I will happily close it if you tell me is a problem with my CI setup.

**Comment by memsharded** [comment]
Thanks for the report. I think there is little we can do here to improve over those bintray errors, and the solution is to re-upload, and is clearly stated in the error message. This can be efficient, i.e. is a big .tgz was succesfully uploaded, then re-uploading will only upload the missing files of the package (txt files, it will be very fast). So I am going to close this issue, thanks for reporting!

**Comment by memsharded** [comment]
Assigning it after close to @markgalpin in case they want to keep track and have a look internally in the Bintray team.
