### ISSUE TITLE
Pass ANDROID_ABI & ANDROID_NDK variables to cmake

### ISSUE THREAD

**Issue by CAMOBAP795** [conan-io/conan#4537]
### Intro

Recently In https://github.com/bincrafters/conan-libwebp/pull/5 I faced with issues `conan` don't forward `ANDROID_ABI` variable and didn't have any way to pass ANDROID_NDK to cmake script too

Most of libraries with cmake build system which support Android expect these variables

### Proposal

Pass `ANDROID_ABI` which can be determined from `os.settings.arch`
Pass `ANDROID_NDK` if `ANDROID_NDK_HOME` environment variable defined (name of env variable can be discussed)

**Comment by CAMOBAP795** [comment]
Looks like make sense to care about ANDROID_NDK_ROOT too

**Comment by venabled** [comment]
Also helpful even if you pass the Platform/Level somewhere as well, detectable from `op_system_version`

```
            ret["ANDROID_PLATFORM"] = op_system_version
```

**Comment by venabled** [comment]
Copy, didn't follow the conversation into the PR. Will try out that branch here shortly.
