### ISSUE TITLE
[feature] package path in (console) output

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4543]
hi there,
while developing serval conan recipes (which are inter-dependent) where I have to put something like the following

recipe:
```python
def package_info(self):
    self.output.info(f"providing cpp_info.rootpath: {self.cpp_info.rootpath}")
```
output:
```
package_name/version@user/channel: providing cpp_info.rootpath: C:\.conan\4eee01\1
```
into the recipe even if it does not need any custom ```package_info``` function. The reason is that this protocols the package source and I can quickly see where and what Conan actually uses as sources for CMake etc. and what is really available, in case I something went wrong with the compilation.

It is no big deal that I put the line above into every recipe by myself but this could be automated :).

Best regards

**Comment by danimtb** [comment]
Hi @Johnnyxy,

Could you please elaborate a little bit more? Why do you find that information useful in every case?
Is this something you use while developing a package or while consuming?
Is this related to the usage of CMake on a way of locating the configuration files or something?

I personally think that the install output in Conan is quite verbose and I haven't needed such functionality but maybe it is something useful.

Thanks!

**Comment by Johnnyxy** [comment]
The background is that I develop conan recipes/packages and consume them as well. While consuming I often need to ensure that I can follow the decisions of conan.

For example my consumer package links some libs. The linker says he cannot find those libs. In this case I can instantaniously see in the console where the package is located and check if the files are there. This ensures that I do not waste time to check some conan recipe(s) or CMake scripts or compiler command lines (first).
If the files are missing I can completely focus on the dependency (recipe, package, source, etc.) instead of the code/recipe used for consuming.

One could say that the files and ```package_info``` of a conan packages is the **interface** between a package and its consumers and I want to ensure that the prerequisites are satisfied.

The next steps would be:
- Is dependency ```package_info``` is correct?
- Check generated files (from generators and conan) in the build folder.
- Check settings in the consuming recipe.
- Check CMake scripts / toolchains.

I would be happy if there would be some means to see what conan is actually using for paths etc. by using a verbose mode or something like that (different log levels). I am not afraid of huge logs as in the future large portions of the software here will be built by Jenkins and there the traceability of errors afterwards are quite limited.

**Comment by memsharded** [comment]
The output should be AFTER the requirements summary:

```
Installing package: Hello/0.1@user/testing
Requirements
    Hello/0.1@user/testing from local cache - Cache
Packages
    Hello/0.1@user/testing:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Build

# Format to be defined
Package folders:
Hello/0.1@user/testing: C:\.conan\1b8ed8\1
```

The shorted-path version should be displayed if used (should be conanfile.package_folder, I think)

**Comment by lasote** [comment]
Take a look at the comment: https://github.com/conan-io/conan/pull/5496#issuecomment-511902038

We realized that printing the paths is too much for the regular output and you have other alternatives like the `conan info --path`
