### ISSUE TITLE
Installing conan inside docker container 

### ISSUE THREAD

**Issue by deekshith-elear** [conan-io/conan#4544]
Hi
I want to install conan inside docker container where users are not available except root.
Can I install conan for root user if yes then where ``` .conan directory ``` is available

**Comment by danimtb** [comment]
Hi @deekshith-elear,

You have good examples of docker images with Conan inside https://github.com/conan-io/conan-docker-tools. You can install conan with root and the conan direcrtory will be reated in ``~/.conan`` or you could set an environment variable CONAN_USER_HOME pointing to the desired directory

**Comment by deekshith-elear** [comment]
Thank you @danimtb
