### ISSUE TITLE
Add AIX to default_settings_yml

### ISSUE THREAD

**Issue by scddev** [conan-io/conan#4545]
Add AIX to os in default settings.yml.

**Comment by danimtb** [comment]
Hi @scddev,
We would need more information before including a new OS to the default settings. As you may know, this settings file is used as a reference for the OSS community on having a convention on naming.

However, there are some things handled internally that need to manage new settings pproperly, suck as the build helpers or the tools we provide to improve the creation of recipes.
 
- Could you elaborate a little bit more about AIX? Is it something widely used?
- Could it be treated as a another unix os?
- Could you link some documentation about it?
- Do you know if there are python tools to detect and work in this OS (filesystem abstraction for example)?

Thanks

**Comment by scddev** [comment]
Hi @danimtb,

AIX: https://www.ibm.com/it-infrastructure/power/os/aix

Basically its just an other unix os, so yes, you have python, gcc, cmake, git, ... running on it.

In our CI environment we need to publish/fetch conan packages also for AIX. In my case I already have adapted the settings.yml locally which was the only thing needed. Everything else worked out of the box.

Thanks

**Comment by danimtb** [comment]
After some discussion in the team we agreed to include this new operating system

**Comment by scddev** [comment]
Yes, OSInfo might need some tweak, I had a quick look:

```
>>> import platform
>>> platform.machine()
'00FB91F44C00'
>>> platform.processor()
'powerpc'
>>> platform.system()
'AIX'
>>> 
```

**Comment by danimtb** [comment]
Thanks a lot for the hints.

- Would this mean that your OS is AIX and architecture is powerpc?

- How are you currently managing this? You have fixed profiles for your builds an so?

Feedback is more than welcome as we don't have chance to test it!!

**Comment by scddev** [comment]
We mapped it with ppc/ppc64 as this is also the architecture in cmake later on. So there was no need for a separate powerpc.

I will try to add the detection in OSInfo.

**Comment by danimtb** [comment]
Cool! Thanks a lot 😃
