### ISSUE TITLE
White/gray font very hard to read on gnome terminal

### ISSUE THREAD

**Issue by Meai1** [conan-io/conan#456]
![font](https://cloud.githubusercontent.com/assets/1112157/18255343/1a2ad784-73a9-11e6-90e2-fbd0662123b6.PNG)

**Comment by memsharded** [comment]
Ok, I see. It hasn't been a problem up to now, as most people use terminals and console with dark colors. I will check the underlying library used by conan to render text color in the terminal, to check if there is some possibility to configure such colors.

**Comment by memsharded** [comment]
I have tried to change the colors with an environment variable to something more readable, and somewhat better but still weird effects like grey backgrounds. Have you tried to change the color scheme of your terminal?, don't know right now in gnome, I am trying in windows (cmder), and it is possible to change the complete color scheme and it reads well even for light backgrounds..

**Comment by memsharded** [comment]
Realized that gnome terminal in ubuntu (high contrast) is not simple to customize, so I have submitted a solution for this: https://github.com/conan-io/conan/pull/473

It uses environment variables to use no colors or different ones. Hopefully will be released in next release. Thanks for reporting.

**Comment by memsharded** [comment]
Released in 0.12. Documented in http://docs.conan.io/en/latest/reference/env_vars.html.

**Comment by alalazo** [comment]
I am trying the [Getting started](http://docs.conan.io/en/latest/getting_started.html) tutorial, and was about to submit a similar issue. Would you welcome a line there mentioning that if you have a terminal with light colors you should set `CONAN_COLOR_DARK=1`?

**Comment by memsharded** [comment]
Yes, why not, a small and simple note with a link just after the first conan command won't harm. Thanks!
