### ISSUE TITLE
LocalDB should be handled in a single place (or maybe removed)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4565]
PR #4556 ensures that the database connection is closed after each usage, nevertheless, it is suboptimal (there can be multiple calls to the database during a single command). The objective should be to open and close the db-connection during the lifetime of a `ConanAPIV1` object. So there are two task associated:
 * There should be only one object of the database (maybe at the `Cache` level, like the `Registry`)
 * The connection could be opened as soon as possible, but it must be closed in the `Cache` destructor

A completely different approach would be to remove the database and use a plain file, right now we are storing in it just the users and tokens, a local database with sqlite3 does not add any extra security.

Related to #4376

**Comment by memsharded** [comment]
Plain text files have to be a bit more carefully managed, accessing the users info should be concurrent from different processes, so locks (like in registry) should be used. Said that, yes, I would be ok removing the sqlite and using text files for this.

I don't care at all about the suboptimality of opening several connections, shouldn't be a problem at all.

The instantiation of a single instance, probably at the cache level, is cleaner, and is a good idea. But it won't make full sense until https://github.com/conan-io/conan/issues/4376 is indeed properly implemented.

Summary:
- **Wait until** https://github.com/conan-io/conan/issues/4376
- Wait until we decide if we are keeping the sqlite or moving to text files.
- If keeping sqlite:
    - Implement a unique instance of LocalDB in the Cache.
    - The connection to the LocalDB is lazily opened
    - The connection to the LocalDB is closed at ``@api_method`` exit, when the instances of architectural collaborators are about to be destroyed.
