### ISSUE TITLE
Specify order of remotes

### ISSUE THREAD

**Issue by GrimSqueaker** [conan-io/conan#4570]
Hi,

is it possible to specify an order of preference for the remotes? In our case we have two groups of developers in different locations and the network connection between the two locations oftentimes is a bottleneck. Hence, I would like to have a setup like this:
- developers at location A search and download first from the Conan server at location A but have B as fallback
- developers at location B search and download first from the Conan server at location B and have A as a fallback
- syncing between the servers will be done via rsync in a cron job

Is it possible to set up something like this - especially regarding the possibility of defining which Conan server should be preferred?

Cheers

**Comment by memsharded** [comment]
Hi @GrimSqueaker 

yes, the remotes are iterated in the order they are defined (and listed with ``conan remote list``). You can see their order in the ``registry.json`` file in the cache.

So make sure that they have the remotes defined in that order in each location. You might use the ``conan config install`` feature, using a different configuration for each location, defining the ``remotes.txt`` file with the remotes in the right order, one first line A, and the other first line B.

**Comment by GrimSqueaker** [comment]
Thank you this is great. I somehow expected this behaviour but couldn't find it documented.

**Comment by memsharded** [comment]
Great, thanks for following up! Closing this issue then, please open new issues for further questions.
