### ISSUE TITLE
meson: process flags as CMake and AutoTools helpers

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#4573]
currently (conan 1.12.3), meson build helper doesn't process flags the way CMake and AutoTools build helpers do.
therefore, recipes has to use the following variables:

```
        meson = Meson(self)
        defs = dict()
        if str(self.settings.compiler) in ["gcc", "clang"]:
            if self.settings.arch == "x86":
                defs["c_args"] = "-m32"
                defs["cpp_args"] = "-m32"
                defs["c_link_args"] = "-m32"
                defs["cpp_link_args"] = "-m32"
            elif self.settings.arch == "x86_64":
                defs["c_args"] = "-m64"
                defs["cpp_args"] = "-m64"
                defs["c_link_args"] = "-m64"
                defs["cpp_link_args"] = "-m64"
        meson.configure(source_folder=self._source_subfolder,
        build_folder=self._build_subfolder, defs=defs)
```
this is annoying and not salable at all.

logic has to be unified across recipes.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
Could you add more code to the snippet? I don't know where that ``defs`` dict comes from.

I general I agree Meson could be improved, it wasn't because there is not many feedback from the community about it regarding Conan.

**Comment by danimtb** [comment]
@SSE4 is that code snippet something you have to do with all packages that have Meson build system?

Are those flag the same regardless of the operating system where the compilation is being done?

**Comment by SSE4** [comment]
@danimtb I had to apply them for `GLib` and `GStreamer` packages so far, but I believe all meson packages suffer from these issues. these flags have to be applied probably at least for Linux, I believe the same way as for CMake or AutoTools (via `compiler_flags` helpers).

**Comment by SSE4** [comment]
same story about `compiler.runtime` for Visual Studio, I have to apply workaround:
https://github.com/bincrafters/conan-gstreamer/blob/stable/1.16.0/conanfile.py#L74
```
        elif self.settings.compiler == "Visual Studio":
            defs["c_args"] = "-%s" % self.settings.compiler.runtime
            defs["cpp_args"] = "-%s" % self.settings.compiler.runtime
```
