### ISSUE TITLE
Inconsistent behavior despite similar configurations?

### ISSUE THREAD

**Issue by sssilver** [conan-io/conan#4584]
Conan version: 1.12.3 on macOS 10.14.3 (18D109) and cmake 3.14.0-rc2.

We have a conanfile.py that looks like this:

```py
from conans import ConanFile, CMake
from conans.tools import os_info


class SphereGameConan(ConanFile):
    generators = "cmake"
    settings = "arch", "build_type", "compiler", "os"
    requires = (
        "gtest/1.8.1@bincrafters/stable",
        "spdlog/1.3.0@bincrafters/stable",
    )

    def requirements(self):
        if self.settings.os == "Windows" or self.settings.os == "Macos":
            self.requires("glfw/3.2.1@bincrafters/stable")
```

When building with a non-existent ~/.conan directory on my friend's macOS, everything compiles ([build log](https://gist.github.com/sssilver/0e488e8c9764825b9dc4137543675ffb)). When building with a non-existent ~/.conan directory on my own macOS, the build fails ([build log](https://gist.github.com/sssilver/f7955ade92557da76158824df70eba83)).

Curiously, Conan generates different "default" profiles in ~/.conan/profiles/default for my friend and me.

Friend:
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

Me:
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[build_requires]
[env]
```

Note the absence of the *compiler* fields in the profile.

We both run the same version of cmake, Xcode, conan, and iOS, and we're trying to build the same branch of the same repo.

What could be causing my build to fail?

Many thanks.

**Comment by jgsogo** [comment]
Hi @sssilver!

Conan always creates a default profile if it doesn't exist, nevertheless it uses that `default` profile only if no other one is specified; in your log there is a `ios.profile`, so you are not using the default one. Also, both of you are using the same one:

```
Configuration:
[settings]
arch=armv8
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
cppstd=17
os=iOS
os.version=10.0
os_build=Macos
[options]
[build_requires]
*: darwin-toolchain/1.0@theodelrieu/stable
[env]
```

The error you are getting is `#error Unsupported architecture` or `#error architecture not supported` which means that your XCode/FRamework does not support the `armv8` architecture you are using. Also there is one more difference between your two builds: CMake output says `-- Looking for open - not found` in your case.

It has something to do with your build framework, not the same version, different context (environment variables),...

**Comment by sssilver** [comment]
How could this happen though, given that we're both on the same Xcode version and `clang --version` reports the same thing for both of us?

**Comment by sssilver** [comment]
Another thing I noticed is that on my build ([line 81](https://gist.github.com/sssilver/f7955ade92557da76158824df70eba83#file-conan-fail-L81)) it says 

```
darwin-toolchain/1.0@theodelrieu/stable from 'conan-center' - Cache
```

While on the working box ([line 95](https://gist.github.com/sssilver/0e488e8c9764825b9dc4137543675ffb#file-conan-success-L95)) it says:

```
darwin-toolchain/1.0@theodelrieu/stable from 'conan-center' - Download
```

Even though both boxes ran `$ rm -r ~/.conan` right before the build.

I feel like this may be the culprit. What may be causing the difference in these behaviors?

**Comment by memsharded** [comment]
Some other differences that might be worth checking:

- The succesful run explicitly define -GXCode: ``$ cmake -DPLATFORM="ios" . -Bbuild.ios -GXcode `` in the first line

- The error seems to come from: 
```bash
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
In file included from
 ...
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:784:2: error: Unsupported architecture
#error Unsupported architecture
```

This warning message about the sysroot is not happening in the succesful run, why?

**Comment by sssilver** [comment]
We have managed to solve this through something peculiar.

On the box that failed building, we changed `darwin-toolchain/1.0@theodelrieu/stable` in ios.profile to `darwin-toolchain/1.0.4@theodelrieu/stable` (which is the latest version built recently). Somehow, once we did that, the box started building everything correctly.

The million dollar question is -- why was the other box building the project fine while using a version of darwin-toolchain released last August?

**Comment by memsharded** [comment]
Uhm, very interesting... Is it possible that somehow in the other (success) box, the ``ios.profile`` was already updated?

**Comment by sssilver** [comment]
Nope, we have triple confirmed that. In fact we also ran `$ conan show` to see exactly what was being pulled on the success box, and it showed the outdated package built in August.

**Comment by memsharded** [comment]
Closing this ticket as outdated, Conan 2.0 is out, it has changed a lot, this seems no longer should be an issue, but please create a new ticket if otherwise.
