### ISSUE TITLE
Conan fails to generate package when mentioned full folder path which contains conanfile.py for export-pkg 

### ISSUE THREAD

**Issue by Prasaddiwalkar** [conan-io/conan#4587]
call conan export-pkg %SRC_PATH%\build\conan\foundation foundation/tc12.1.0@admin/release -f
Exporting package recipe
foundation/tc12.1.0@admin/release: The stored package has not changed Packaging to 15af85373a5688417675aa1e5065700263bf257e
foundation/tc12.1.0@admin/release: Generating the package
foundation/tc12.1.0@admin/release: Package folder C:\Users\user\.conan\data\foundation\tc12.1.0\admin\release\packag
e\15af85373a5688417675aa1e5065700263bf257e
foundation/tc12.1.0@admin/release: Calling package()
foundation/tc12.1.0@admin/release package(): Copied 150 '.h' files:
foundation/tc12.1.0@admin/release package(): Copied 2893 '.hxx' files:
foundation/tc12.1.0@admin/release package(): Copied 86 '.lib' files:
ERROR: foundation/tc12.1.0@admin/release: Error in package() method, line 25
        self.copy( "abc.lib", src=tc_library,     dst="lib",  keep_path=True )
        PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\.conan\\data\\foundation\\tc12.1.0\\admin\\
release\\package\\15af85373a5688417675aa1e5065700263bf257e\\lib\\abc.lib'

same command passes when run from the folder where conanfile.py resides
cd %SRC_PATH%\build\conan\foundation
call conan export-pkg . foundation/tc12.1.0@admin/release -f

**Comment by jgsogo** [comment]
Hi @Prasaddiwalkar!

This is something very strange, as the code executed by Conan should be exactly the same (even the same working directory). I will tell you a couple of things to do in order to help us triage your error:
 * The variable `tc_library` does it have the same value in both cases? You can `print(tc_library)` before the error to see it in the output. 
 * Does it happens too without calling Conan with the `call` command? The `call` command opens a new bash terminal, maybe something is affecting it. Please report the output of `conan export-pkg ...`

Thanks

**Comment by Prasaddiwalkar** [comment]
@jgsogo 

* The variable `tc_library` does it have the same value in both cases? You can `print(tc_library)` before the error to see it in the output. 

Yes it has same value as it picks this value from environment variable

* Does it happens too without calling Conan with the `call` command? The `call` command opens a new bash terminal, maybe something is affecting it. Please report the output of `conan export-pkg ...`

Yes 
Even if I wrote python script to traverse through all the packages and cal export-pkg using 
When I do following it works fine
os.chdir(conanfileDir)
packageInfo = "conan export-pkg D:/abc/foundation " + folderstrip + "/"+teamcenterVersion+"@admin/release -f"
sampleOutput = subprocess.check_call(packageInfo, shell=True)

But when I do only it fails with above error
packageInfo = "conan export-pkg D:/abc/foundation " + folderstrip + "/"+teamcenterVersion+"@admin/release -f"
sampleOutput = subprocess.check_call(packageInfo, shell=True)

**Comment by jgsogo** [comment]
I'm not able to reproduce this behavior, it looks so strange to me... in your first log you are already able to copy a lot of libraries (`Copied 86 '.lib' files`) and the it fails for that single one, what's is the difference between them? why do you have this copy isolated? Does it come from a different place? Maybe it is a read only library in origin?

**Comment by Prasaddiwalkar** [comment]
I checked this file exists in .conan/data folder. but give permission error. Even I tried removing the file from self.copy then it fails for other file

**Comment by jgsogo** [comment]
Hi @Prasaddiwalkar, is there more information related to this issue? Is it still an issue?
