### ISSUE TITLE
[question][suggestion] Listing profile should be recursive

### ISSUE THREAD

**Issue by xaqq** [conan-io/conan#4589]
Hello,

I use multiple profiles, and those are organized in subdirectories:
   + `~/.conan/profiles/application/x64_gcc6_app1`
   + `~/.conan/profiles/application/x64_msvc_app1`
   + `~/.conan/profiles/compilers/x64_gcc6`
   + `~/.conan/profiles/compilers/x64_msvc`

The "applications" profile include other profiles etc. This works pretty well, so I assume 
using subdirectory in profiles is supported and is not a problem.

However, the `conan profile list` command does not list profiles contained in subdirectories.
I believe it should recursively search for profile files rather than only list the files available directly in the `~/.conan/profiles` directory.

I'm wondering if there is a particular reason why the search is limited to the `~/.conan/profiles` directory and if you'd be open to changing this behavior.

**Comment by jgsogo** [comment]
It completely makes sense, there is no reason to list only the first level files. I will add it to queue, not the highest priority, but it is really easy and an improvement.

Thanks!
