### ISSUE TITLE
cmake_find_package generator not usable with CMake multi-config generators like VS

### ISSUE THREAD

**Issue by akleber** [conan-io/conan#4592]
* conan 1.12.3
* CMake 3.13.4
* Windows 10

When using the cmake_find_package generator conan generates FindXXX.cmake modules for consumption. However these find modules only contain one build_type. When using these find modules with a CMake multi configuration build system, like Visual Studio, this does not work, because we need information for all configurations in the find module.

Example: Running `conan install -g cmake_find_package zlib/1.2.11@conan/stable` produces a `Findzlib.cmake` file that will contain all relevant information about using zlib in Release configuration. Specifically only the link library name `zlib` is provided.
When running `conan install -g cmake_find_package -s build_type=Debug zlib/1.2.11@conan/stable` the find module `Findzlib.cmake` now contains all relevant information for using the debug build of zlib, specifically the link library name now correctly is `zlibd`.

Because the find modules only contain one build_type at a time they cannot correctly be used with a multi configuration build system like Visual Studio.
However find modules can contain multiple configuration they "only" need to be written accordingly by conan.

I stumbled upon this while using the conan cmake wrapper. This script installs all build types when used by a multi configuration generator and then only the find module of the last installed build_type survives.

Also I think it is not feasible to have both find modules available (e.g. by using different names or directories) as only one can be used at a time because targets are generated.

**Comment by Johnnyxy** [comment]
This would be a very ... VERY ... nice feature if Conan could support "multi config" with/in ```cmake_find_package```.
1000 points for the upvote on the feature list :).

**Comment by lasote** [comment]
Hi guys! Thanks for opening this issue.
Could you help us with some example of "official" (or not official if not possible) cmake find script supporting different build_types?

**Comment by Johnnyxy** [comment]
At the moment I have not much time to spare. As the generator does not support multi-config and my code gets generated and compiled for each build_type anyway this is not an urgent issue for now.

But other projects could profit from using just a ```find_package``` logic instead of the "complex include conan into CMake" logic.

But I will certainly think about it how we could solve this.

**Comment by akleber** [comment]
The official [FindZLIB.cmake](https://github.com/Kitware/CMake/blob/v3.13.4/Modules/FindZLIB.cmake) contains multiple build_types/configs. However I think this approach does not translate very well to conans approach. 
It might be possible to use the same approach that conan uses for the 'cmake' generator. I describe it for the zlib example:
Create Findzlib.cmake. This file should not contain anything specific but just a simple switch and can thus be created/overwritten when processing any build_type: 
- If single config: `include(Findzlib-single.cmake)` with the content of the current Findzlib.cmake
- If multi config: `include(Findzlib-debug.cmake)` and `include(Findzlib-release.cmake)`.

The Findzlib-debug.cmake should be very similar to the current Findzlib.cmake. The difference is, that it conditionally create the zlib::zlib target if it does not exist already. Then it should register the current build_type in the property IMPORTED_CONFIGURATIONS (like in the official FindZLIB.cmake) if not already registered. And finally it should APPEND the provided libraries with config dependend generator expressions like:
`set_property(TARGET zlib::zlib APPEND PROPERTY INTERFACE_LINK_LIBRARIES $<$<CONFIG:DEBUG>:${zlib_LIBRARIES_TARGETS}>)` .

This described approach is not used in the official find modules and I do no know why. Also I am unsure if the approach restricts the CMake version that can be used. But this should be easy to find out.
I did not try this approach, but maybe I find time in the next days. If I do I will share my results.
And if time permits maybe even a PR.

**Comment by lasote** [comment]
We are (at least) analyzing the issues of the "transparent" integration with Conan and CMake using find_package for the next release. I want to know if it is more a cmake limitation, a conan limitation, both... @akleber If you tried the example or any other feedback you could provide it would be great. Maybe you have new information.

**Comment by lasote** [comment]
Good news, looks like it is working: https://github.com/conan-io/conan/pull/4714
Feel free to try it on my branch and give feedback

**Comment by akleber** [comment]
That was fast, thanks. I did a quick check on my use case and I can report that it works!

Also I noticed that my reproducer described above is not completely right anymore. When using zlib/1.2.11 the link library name is zlib.lib for debug and release. It does work however for zlib/1.2.9. There the link library is zlib.lib for release and zlibd.lib for debug.
I do not understand why the link library name is the same for debug and release for 1.2.11 now, I am sure it was as described 19 days ago. Based on the conanfile.py in https://github.com/conan-community/conan-zlib it should have the "d" suffix. I noticed that all packages were updated 5 days ago, so I do not know the content of the packages on the time I created this reproducer (cleared my local cache). Nevertheless to me it seems as if the provided binaries do not match the linked conanfile.py anymore?

Regarding the implementation I also think that it should be possible to unify the multi and non-multi cmake generators. It should be possible to write the cmake files so that they can be used for both types as noted by Johnnyxy, but some backwards compatibility would need to be sacrificed.

Additionally the cmake files produced by conan (at least the find modules) only work for the four build types default to cmake: Release, Debug, RelWithDebInfo, MinSizeRel. I would like to be able to use my own Build types, but this is a topic for a separate issue...

**Comment by lasote** [comment]
Thanks for trying!

About the debug suffix, not sure, but the recipes are constantly evolving, maybe the recipe doesn't generate anymore the suffix for debug.

About unifying both generators, you are right, maybe we can make the old one to behave as "multi". I think it won't break anything. I added a comment in the PR.

**Comment by memsharded** [comment]
#4714 has been merged, so the new ``cmake_find_package_multi`` generator will be available in Conan 1.14, hopefully this week :)
