### ISSUE TITLE
List only public dependencies in 'self.deps_cpp_info.deps' list

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4593]
It is documented that the list of dependencies of a package can be retrieved using `self.deps_cpp_info.deps` [[1](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-cpp-info)], but it says nothing about those dependencies being private or public or build requires.

There is an inconsistency right now (Conan v1.12.x) because that list is different if you are compiling the library or consuming it:
 * compiling the library: it contains both public and private dependencies
 * consuming the library: it contains only the list of public dependencies

This should be fixed.

----

We agree that a private dependency shouldn't be accessible from outside the package and it shouldn't affect the consumers, so that list should contain **always** only the list of public dependencies. Nevertheless, some users need to know the full list, so one alternative is to return a list of tuples with the categorization of each dependency: `[("lib1", "public"), ("lib2", "private"),...]`, or a dictionary...

This is something to agree on.

**Comment by memsharded** [comment]
New ``self.dependencies`` model deprecates this one, completely removed in 2.0.
