### ISSUE TITLE
find_package case-sensitive and sometimes miss because conan package name different case

### ISSUE THREAD

**Issue by CAMOBAP795** [conan-io/conan#4597]
### Problem

I have big codebase in `cmake` which I trying to move on `conan` dependency manager.

For example in several places in my code I have:

```
...
find_package( OpenCV REQUIRED )
...
```
According to official opencv guide this is right name of package https://docs.opencv.org/2.4/doc/tutorials/introduction/linux_gcc_cmake/linux_gcc_cmake.html

But `conan` generate `Findopencv.cmake` script which will 'respond' to `find_package( opencv )` onle, because `find_package` is case-sensitive

### Proposed solution

I'm not questioning current approach, but I think it will be nice if for cmake generators we will be able to configure/change package name to any custom.

Maybe there is already workaround in cmake, I have tried to search for some "package aliasing" approach, but didn't found anything

Partially this can be fixed by support [“Config” mode of `find_package`](https://cmake.org/cmake/help/v3.0/command/find_package.html)

### Checklist

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Johnnyxy** [comment]
This issue has been brought up serval times. It is some sort of shortcoming but not from Conan itself instead more of the interaction and mechanics of CMake and Conan.

The problem has been discussed in detail with a workaround here: https://github.com/conan-io/conan/issues/4460

**Comment by uilianries** [comment]
Hi @CAMOBAP795 !

You are not the first one who asked about it, please read the issue https://github.com/conan-io/conan/issues/4460.

As you can read on [Transparent CMake Integration](https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html), our intention is not replace the original FindXXX.cmake provide some help.

Regards!

**Comment by CAMOBAP795** [comment]
@Johnnyxy @uilianries thanks for information, I going to close this one
