### ISSUE TITLE
Conan config install polutes the installation dir

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4603]
To help us debug your issue please explain:

Hi!

Since `conan config install` is able to install our hooks (that's great), it also can pollute the installation dirirectory (~/.conan) when more files are versioned together. For example:

    conan config install https://github.com/conan-io/hooks.git

I want to install all official hooks, and this command works fine. However, more files are included there, as README, LICENSE and tests/.

I think `config install` could be optimized for hooks, only installing the hooks, or we could add some `--query` argument, where we could filter and install the folder `hooks/` only.

Regards!

Conan Version: 1.12.3

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
We talked about this some days ago. We detected some needs for the `config install`:

- Somehow specify the src_subfolder: Will take only the `src_subfolder` of the origin (folder in the git repo, a folder in the zip file...). Probably it should be a parameter of the `config install` command.
- Somehow specify the desr_subfolder: Will copy the source files to the subfolder in the local cache.

I will try to discuss more this in a whiteboard session because I still think we are missing:

- Support for installing config from different repositories in one step. Each one with the `src` and the `dest`. It would require a "meta-config install file" containing all the things to be installed.

**Comment by uilianries** [comment]
> Support for installing config from different repositories in one step. Each one with the `src` and the `dest`. It would require a "meta-config install file" containing all the things to be installed.

It sounds like `conan imports`.

**Comment by lasote** [comment]
What? LoL

**Comment by uilianries** [comment]
https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports :wink:

**Comment by lasote** [comment]
- The entry from the `conan.conf` caching the call to the ´conan config install` have to be migrated (if exist) to a `config_install.json` file.
- That `config_install.json` file:
   - Will be excluded from the files downloaded by a `conan config install`
   - Will store the calls to the `conan config install` command. If the call produces the exact element that already exists it won't be duplicated. (See further format)
   - Acts as a cache only (Still not considered something to be shared)
   -  Format:

```javascript
{"origins": [  
   {"url": "path or url", "type": "git or folder", "verify_ssl": true , 
    "git_args": "...", "source_folder": "xxx", "target_folder": "yyyy"} ,
   {}, 
   {},
   {} ]
} 
```
The `source_folder` and `target_folder` have to be added as arguments to the command:

- `source_folder`: Subfolder or the "url" containing the files that we have to copy
- `target_folder`: Subfolder on the cache to copy the contents of the `source_folder`

The feature responds to the following needs:

- Install a part of a repo and not all
- Install different repos, (as hooks from different locations)
- Install to different folders (to more flexibility to indicate where to put the files in the cache).

From the moment the `config_install.json` is not considered something to be installed, it could be a bit complex to understand the possible "recursion" if one url installs (overwrite) other `config_install.json` etc.

**Comment by uilianries** [comment]
- What happen when the target folder does not exist? Will Conan create one?
- What happen if target folder exists and it contains files. Will Conan override without ask?
- Why JSON if you we user .INI flavor for configurable files?

**Comment by lasote** [comment]
@uilianries you can make a review asking these questions for the PR.
About why json and not `.ini`, because `Acts as a cache only (Still not considered something to be shared)` it should be considered an internal file, so for me is easier to use json. But feel free to suggest in the PR.

**Comment by memsharded** [comment]
@uilianries Regarding INI, yes, I'd partially would like that format, but the truth is that it is easier in code with json. As I see no suggestion in the PR, I guess you are good at the moment with json, so will leave it as-is by now.

**Comment by uilianries** [comment]
I have no problem with JSON, I think it's better when you want to create an internal config file, and of course, you want to parse it. But for real users, sometimes they could mess the json and open issue because "conan is not working". That's why I asked, since .INI and TOML are more friendly. Thanks for sharing your point of view.
