### ISSUE TITLE
Alternative virtualenv behavior

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#4604]
Basically I was thinking whether Conan's virutalenv should model Python's venv or RedHat's SCL (Software Collection)?

I think that Conan should behave more like SCL (something like):
```sh
$ conan enable ./build/debug ~/extra-tools -- bash -i
$ conan enable . ~/extra-tools -- cmake ../.. && cmake --build .
```

## Why
1. SCL has inherent ability to activate multiple environments at the same time and chain them when Python venv strictly bound to one (there are even shell plugins to automatically activate deactivate venv based on CWD). 
2. SCL sets arbitrary number of environment variables, expect expects that order of activation matter. Python venv in contrast set only one or two variables.

## Conan
1. Conan already has multiple "flavors" of environment: just env, run env and build env.
2. As was suggested it should be possible to chain multiple Conan virtualenvs.
   1. Prompt gets really messy in this case.
   2. You can't deactivate this

## What is expected
We don't need to break existing `(de)activate*.sh` scripts but can rather add another dimension to it as a separate set of scripts.

1. Main semantic difference is that SCL runs a command in the modified environment. This is convenient because it allows user to choose:
   1. Run an interactive shell for multiple operations. (e.g. `bash -i`).
   2. Run a single build command, even from IDE (e.g. `make`)
   3. Think about analogies: `docker run ...` or `scl enable devtoolset-6 -- ...`
1. There is no need for deactivation. It handled by ending command.
1. Modifying prompt is not needed either. If prompt is needed for an interactive shell it could be handled by adjusting shell initialization scripts to look for special variables (e.g. scl sets `X_SCLS`).

## Related to issues
#2461, #2556, #4557

## Some background
One approach was to write own TeamCity generator which produced special service messages so environment variables set by Conan were available in next steps. Problem is that it doesn't work on other CI systems we use (GitLab to name one) and requires duplication of build steps to include this extra generator.

Another concideration is that I want to share build scripts (like CPT) and it feels natural to use Conan (it's amazing how well it supports branches and versions with user/channel axes). But then again I need to have activated multiple environments and different ones at different stages.

Sure, installing tools can be handled by build requirements put into profile but I still think that composability of environments is a good thing.

Also spawning subshell with new environment is a common use-case (multiple developers in our team came to this independently). First people just don't trust deactivate script. Second you may need another shell (e.g. if script uses bash and login shell is fish). So ugly commands came into life:
```sh
$ bash --init-file (echo ". ~/.bashrc; . ./build/debug/activate.sh" | psub)
$ bash --init-file <(echo ". \"$HOME/.bashrc\" ./build/debug/activate.sh")
```
(or even worse if you want to make it to an alias or function).

**Comment by ytimenkov** [comment]
I tried to be as clear as possible but have strong feeling that I've failed :disappointed: 

So I consider this as an opening for a discussion (especially given new contributing guidelines into account :smile:)

**Comment by lasote** [comment]
Hi! We have been talking about these things and we see a couple of drawbacks to something like:
 `$ conan enable ./build/debug ~/extra-tools -- bash -i` 

The first one, it allows to launch a subprocess but not to modify your current shell environment, so we would need both mechanisms.
The second one, the pain our users are transmitting is to have to activate an environment to launch later the IDE or whatever, and this doesn't solve it either, probably they refuse even more to use conan to launch something... 
So I agree there is a need there but we are not sure how to fulfill.
Anyway I assigned this issue to the related projects to take it into account as we don't have the answer yet.
Thanks!

**Comment by ytimenkov** [comment]
> The second one, the pain our users are transmitting is to have to activate an environment to launch later the IDE or whatever

That's not different from activating current shell: either `. activate.sh && ide` vs `conan <whatever> ide`. In most cases IDE is started in background.

Actually I came to this idea exactly because I use conan with IDE (VS Code in my case). I just have a task with command line `. ${workspaceRoot}/build/debug/activate.sh && waf build` which will do fairly well if conan will set up environment.

I don't trust that IDE captures environment correctly: it can as well signal a running instance to open another window with new folder so environment will be inherited from login process and not the shell.
I was thinking more about IDE-specific generators which can in some way produce ide-specific settings, for example, populating `python.autoComplete.extraPaths` in `settings.json` setting instead of `PYTHONPATH` variable.

**Comment by ytimenkov** [comment]
> The first one, it allows to launch a subprocess but not to modify your current shell environment, so we would need both mechanisms.

Just a thought: there could be a flag which prints environment suitable for `eval` -ing. Something like what ssh-agent does. Then activate script could "be implemented in terms of".

**Comment by jgsogo** [comment]
Hi! I'd want to comment a couple of things:

 * > Just a thought: there could be a flag which prints environment suitable for `eval` -ing. Something like what ssh-agent does. Then activate script could "be implemented in terms of".

   This is the next step in this journey, we want to generate a file with the environment to apply (`xxx.env`) and the `activate` script will just call it. I have a PR almost ready with an early implementation.

 * Related with the IDEs. We think we should provide a much better approach than forcing the user to start the IDE using the command line. I'm not sure if different IDEs will need a different approach for different tasks (running tools, some pre/post build, debugging,...). **Would it be ok for you to install a Conan plugin** for your IDE that will activate the environment automatically if the `xxx.env` file exists (and a `conanfile.txt/py` file is found)?

**Comment by memsharded** [comment]
Closing this ticket as outdated. There are new environment management, 2.0.15 includes generation of environment directly in ``CMakePresets``, so only cmake might be used here.
