### ISSUE TITLE
Circular reference on conan install --json if using multi configuration packages

### ISSUE THREAD

**Issue by DirkScharff** [conan-io/conan#4606]
While creating a multi configuration package (mainly for windows / Visual Studio + cmake) i want to use conan install --json to protocol the exact version installed of the package for versioning purposes. This is meant to be used to recreate the versioned environment at a later point in time.

Following https://github.com/memsharded/hello_multi_config I defined:
```
def package_info(self):
    self.cpp_info.release.libs = ["Conan_TestLibrary"]
    self.cpp_info.debug.libs = ["Conan_TestLibrary_d"]
```
after doing this conan install --json gives me the following error:

```
conan install Conan_TestLibrary/1.0.0@tlk/stable -g cmake --json test.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Conan_TestLibrary/1.0.0@tlk/stable: Installing package
Requirements
    Conan_TestLibrary/1.0.0@tlk/stable from local cache - Cache
Packages
    Conan_TestLibrary/1.0.0@tlk/stable:647cbb6309b429634f119fb1a6f066f9cca806ce - Cache

Conan_TestLibrary/1.0.0@tlk/stable: Already installed!
Conan_TestLibrary/1.0.0@tlk/stable: Generator cmake created conanbuildinfo.cmake
Conan_TestLibrary/1.0.0@tlk/stable: Generator txt created conanbuildinfo.txt
Traceback (most recent call last):
  File "c:\users\dirks\anaconda3\lib\site-packages\conans\client\command.py", line 1427, in run
    method(args[0][1:])
  File "c:\users\dirks\anaconda3\lib\site-packages\conans\client\command.py", line 399, in install
    self._outputer.json_output(info, args.json, cwd)
  File "c:\users\dirks\anaconda3\lib\site-packages\conans\client\conan_command_output.py", line 67, in json_output
    save(json_output, json.dumps(info, default=date_handler))
  File "c:\users\dirks\anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\dirks\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\dirks\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected

ERROR: Circular reference detected
```
Experimenting a bit with this it seems like accessing self.cpp_info.release.libs adds a config to self.cpp_info which is referencing a python object. Below is self.cpp_info.__dict__:
```
{
    'includedirs': ['include'], 
    'srcdirs': [], 
    'libdirs': ['lib'], 
    'resdirs': ['res'], 
    'bindirs': ['bin'], 
    'builddirs': [''], 
    'rootpaths': [], 
    'libs': [], 
    'defines': [], 
    'cflags': [], 
    'cppflags': [], 
    'sharedlinkflags': [], 
    'exelinkflags': [], 
    'rootpath': 'C:\\Users\\DirkS\\.conan\\data\\Conan_TestLibrary\\1.0.0\\tlk\\stable\\package\\647cbb6309b429634f119fb1a6f066f9cca806ce', 
    'sysroot': '', 
    '_include_paths': None, 
    '_lib_paths': None, 
    '_bin_paths': None, 
    '_build_paths': None, 
    '_res_paths': None, 
    '_src_paths': None, 
    'version': '1.0.0', 
    'description': ' ', 
    'public_deps': [], 
    'configs': {
        'release': <conans.model.build_info._CppInfo object at 0x0000028303264AC8>, 
        'debug': <conans.model.build_info._CppInfo object at 0x0000028303264EB8>
        }
    }
```
My current guess is that --json can not handle this object reference and thus fails. I expect this to be solvable by giving json.dumps a custom encoder.

I'm using Conan version 1.11.2 on Windows 10 64-bit

Steps to reproduce:
- define conan package,
- define package_info as shown above
- create package
- try to install package with --json

I'd apreciate any ideas to work around this issue for the time beeing. 

Edit: Added new line in code block, "{" was not showing.

**Comment by lasote** [comment]
Thanks for reporting, yes, looks like a bug. Let's try to solve it for the next release.

**Comment by jgsogo** [comment]
I'm reproducing the issue with the example repository [https://github.com/memsharded/hello_multi_config](https://github.com/memsharded/hello_multi_config], just:

```
git clone https://github.com/memsharded/hello_multi_config
cd hello_multi_config
conan create . Hello/0.1@user/testing --json test.json
```

The issue (the circular error) is related to a wrong implementation of the `date_handler` function provided for the dates to be JSON-serialized. Easy fix.

Nevertheless, when there are several configurations in the same CppInfo object, we need to tell Conan how to serialize them. I'm preparing a PR with this change, but I need to agree which is the expected output for this JSON. Currently:

```json
"cpp_info":{  
      "resdirs":[  
         "res"
      ],
      "libdirs":[  
         "lib"
      ],
      "rootpath":"/Users/jgsogo/.conan/data/Hello/0.1/user/testing/package/c68ee304a11d8eb98cba43097a503d6406b84075",
      "filter_empty":true,
      "includedirs":[  
         "include"
      ],
      "version":"0.1",
      "configs":{  
         "release":{  
            "resdirs":[  
               "res"
            ],
            "libdirs":[  
               "lib"
            ],
            "rootpath":"/Users/jgsogo/.conan/data/Hello/0.1/user/testing/package/c68ee304a11d8eb98cba43097a503d6406b84075",
            "filter_empty":true,
            "includedirs":[  
               "include"
            ],
            "libs":[  
               "hello"
            ],
            "bindirs":[  
               "bin"
            ],
            "builddirs":[  
               ""
            ]
         },
         "debug":{  
            "resdirs":[  
               "res"
            ],
            "libdirs":[  
               "lib"
            ],
            "rootpath":"/Users/jgsogo/.conan/data/Hello/0.1/user/testing/package/c68ee304a11d8eb98cba43097a503d6406b84075",
            "filter_empty":true,
            "includedirs":[  
               "include"
            ],
            "libs":[  
               "hello_d"
            ],
            "bindirs":[  
               "bin"
            ],
            "builddirs":[  
               ""
            ]
         }
      },
      "bindirs":[  
         "bin"
      ],
      "builddirs":[  
         ""
      ]
   }
}
```

As you can see, there is repeated information in the output `cpp_info` and inside each `config/debug`, `config/release` nodes, do we want to avoid these repetitions? Maybe it is too fine-grain logic, what do you think?

**Comment by DirkScharff** [comment]
I'm not very familiar with the way these things are normaly treated in conan as I'm just learning to use it, but I'll add my two cents with a little discussion below.

While I personaly don't exactly mind the repeated info, precedence should be clearly defined. As is in @jgsogo 's version I would like to see an entry like config.debug,_comment : "This section takes precedence over config.*", to make this completely obvious to any user without the need of further documentation. This requires some logic to be implemented when using the file to sort things out

The most specific version I can think of is removing the general section entirely when adding configurations. As this is most specific the meaning is compleatly obvious without further documentation. This would have the benefit of not requireing any logic to parse the intended value.

If however eleminating repetition is the priority I think a little logic is unavoidable. In this case I would most appreciate a general section for all matching data and "sparse" data with precedence in specific configurations. If the data is sparse it should be clear that this is the more specific entry and the general one (if still exists) is meant to be a "default" value. When reading this you'd have to look up i.e. config.release.includedirs and if not exists you could default back to config.includedirs.

**Comment by DirkScharff** [comment]
@jgsogo I just tried the version you comitted to your fork. Works fine for me. I don't mind a change in the json structure later. I can use this for the time beeing until an official fix is released. 
Thank you for your quick response to my issue.

**Comment by jgsogo** [comment]
Thanks, @DirkScharff, tomorrow I will be able to give you a more detailed answer, we need to agree on the final JSON output.

**Comment by jgsogo** [comment]
Sorry for the delay. Last week we agreed to keep the JSON as similar as possible to the `CppInfo` object it is built from. I've created the PR here (https://github.com/conan-io/conan/pull/4656), we cannot make a commitment for the JSON output, so it will be _experimental_ like it was before ([docs](https://docs.conan.io/en/latest/reference/commands/output/install.html)). We may remove some duplicated fields, I'm sorry if it breaks you in the future, but at least in `v1.13` it won't throw the exception.

Thanks!
