### ISSUE TITLE
Embed test_package in the recipe

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4610]
Provide a way to avoid having a `test_package` folder. Maybe declaring the contents of a `main.c/cpp` in the recipe could be enough.  It would be nice because:

- You could contribute with only a conanfile.py to a library, without polluting the repository.
- The `conan install --build` could run the test_package too.

To brainstorm:

- New conanfile method `test_package`? calling some helpers that will generate on the flight the test package process? Or should it be only a standard variable name containing the c/c++ code?
- Should this mechanism will be compatible or support having the classic `test_package` folder?
- Should accept a path to a file in case the repository already have an example?

**Comment by uilianries** [comment]
Sometimes we use an example or test from the author. We just copy the original file to test_package.

We could provide a new helper to point that specific file, build (generate cmake, link conan libs) and run.

**Comment by memsharded** [comment]
More things to discuss:

- Does it build the test in the cache ``test/hash`` folder? I'd say yes.
- CMake as only build system for this feature?

**Comment by uilianries** [comment]
Only to increment some ideas, how Conda and VPKG test their packages?

- Conda uses a field in the recipe with the steps. But it's really shallow. For example, for zlib, they only check if the library has been created:
https://github.com/conda-forge/zlib-feedstock/blob/master/recipe/meta.yaml#L27

- VPKG uses the build as test. So if your recipes is able to be built on CI, probably it's okay.

**Comment by memsharded** [comment]
We don't plan to embed test_package in the recipe, but the "metadata" feature allows to do this, the tests in https://github.com/conan-io/conan/pull/13918 covers this use case.
