### ISSUE TITLE
conan info generates bad .conan_link files

### ISSUE THREAD

**Issue by hebaishi** [conan-io/conan#4612]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Operating System: Windows 10 64-bit
Conan version: v1.11.2

I have a situation where I have two recipes - A and B, and recipe A depends on recipe B. What I do to determine the depdencies between my recipes is:
1. Run `conan export` over all recipes
2. Run `conan info -g out.dot` to generate the dependency graph for all recipes
3. Parse the dependency graph for each recipe to generate the full dependency graph

Once I have the complete graph, I can then traverse it to build the recipes in the right order.

The issue I have is when I run conan info on recipe A (which depends on B), on Windows, I get a `c:\Users\MyUser\.conan\data\recipeB\0.0.2\user\channel\package\69f10d1e6d78c1962fbe8fb80440f32b1fdf8423\.conan_link`.

And that `.conan_link` points to a directory which doesn't exist. So if I now tried to do an upload of all recipeB packages, I get an error from conan saying that particular package is corrupted. Removing that particular package folder (the one with a hash as its name) fixes the issue.

Do you think this issue can be fixed in conan? Currently, we work around the issue by specifically looking for these broken `.conan_link` files and removing the package folders they're in.

**Comment by hebaishi** [comment]
Sorry, another thing I should have mentioned is that recipeB in the above example has `short_paths` set to `True`, which is what causes the `.conan_link` file to be generated.

**Comment by memsharded** [comment]
Hi @hebaishi 

I am having a look. In the meantime I'd like to ask, have you had a look to the ``conan build --build-order`` functionality? That gives you the information of the build order, already in parallelizable groups.

**Comment by hebaishi** [comment]
Yes, I have had a look at that, but the problem is there is information in the graph which is missing in the build order list. And as we are doing this for ~70 recipes, it's important we build things in the right order, so the build graph works better for our purposes.

The workaround for this issue isn't actually too bad, and because the approach we now use (based on your recommendation) uses conan to get the dependencies between the recipes, it's actually incredibly robust. Fixing this issue would just be the cherry on top of what is already a pretty amazing pie. :+1:

Thank you again for suggesting `conan export`!

**Comment by memsharded** [comment]
Yes, confirmed as a bug. It was a very unfortunate interaction of short_paths, the usage of short_paths in a "predictive" way via ``conan info`` and later ``conan upload`` that thought there was a package there.

Lets see if https://github.com/conan-io/conan/pull/4615 solves it. Thanks for reporting!

**Comment by memsharded** [comment]
Fixed, will be released in conan 1.13.
