### ISSUE TITLE
Confusing message in case of a REFERENCE_CONFLICT

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#4614]
The following exception message is at least confusing:
https://github.com/conan-io/conan/blob/develop/conans/client/graph/graph_builder.py#L116

"Keeping" sounds as if processing would continue with the mentioned package reference, but this is not the case, as an exception is thrown.

Apparently this behaviour changed in conan 0.30.0, before it was possible to regard this as a warning.

Unfortunately, some of our packages relied on the previous behavior at least for the installation of tests. Why was this changed? Is there some other way to override it?

**Comment by memsharded** [comment]
Yes, that ``Keeping" message is already proposed for removal in https://github.com/conan-io/conan/pull/4514/files

Yes, long time ago, before conan 1.0, the conflicts were warnings by default, but the processing continued, as you already know. We learnt that it was a big source of errors and problems, and a support nightmare, so it was converted to errors, without no feedback in the opposite direction so far (more than 1 year ago).

There is no way to opt-in a continuation algorithm, unfortunately the dependency resolution algorithm is not easy, and such behavior would be a pain to implement and maintain, and there is not enough evidence that this feature has enough value for many users. Actually a large pressure from the community is being done for "exact" and reproducible builds, which is kind of opposite to silently continue with an arbitrary decision on the version to keep after a conflict.

If you are having conflicts in your tests installs, it is relatively straightforward to solve: for each conflicting dependency, add a ``ref, override=True`` requirement downstream to define which is the version that you want to use.

**Comment by sigiesec** [comment]
Thanks for the explanation. 

Probably, we don't really need this either, the places where it is used are not clean. I also did not notice that it did not work anymore, because the offending parts had been disabled more than a year ago.
