### ISSUE TITLE
[question] access deps_cpp_info of python_requires

### ISSUE THREAD

**Issue by tharilya** [conan-io/conan#4616]
Hello there,

I am working on Windows10, python 3.6 and using conan version 1.12.3.
I have a question regarding the dependency informations `deps_cpp_info`. 
Is there a way to get the `deps_cpp_info` of a "python_require"? 

```python
from conans import ConanFile, python_requires
import os

my_py_req = python_requires("my_python_requires/1.0.0@abc/def")

class my_conan_class(ConanFile):
...
def build(self): 
    print (self.deps_cpp_info["my_python_requires"].rootpath)
    # template_dir = os.path.join(self.deps_cpp_info["my_python_requires"].rootpath, "templates")
    # template_object = my_py_req._load_template(os.path.join(template_dir , "name_of_template.txt"))
    # template_object._fill_placeholders( ... )
    # template_object._create_file( "dst_dir" )
...
```

If i do so i get a `KeyError`

I know that its possible to get the directory in another way, but it would be "clean" if this way would be possible.

My usecase:
I have a "Base-Pkg" lets call it "my_python_requires". There i have some templates with placeholders, and methods to create files and strings.
Now I want to use the "Base-Pkg" creating files, based on the templates in a "Using-Pkg". The "Base-Pkg" will be installed in my conan-cache. All fine till here, everthing is there, templates, python-scripts, and so on in the package directory. 

I need to load the template-files into the scripts. They are always in the package_folder of the "Base-Pkg"

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @tharilya 

By definition a ``python_require`` does not have ``cpp_info``, as that is a property exclusively of the binary package, and the ``python_require`` are exclusively python code, that is, recipes. 

What I understand you want to achieve is to reuse files from the "recipe" part of the ``python_requires``, not from a package. Right now, it is not possible, I would recommend to embed the templates in python strings in the python file and use them in the consumers.

We are considering this possibility right now, but it is very complex feature. If this is the feature you would like to see, please follow https://github.com/conan-io/conan/issues/4262, and this could be closed as a duplicate. Thanks!

**Comment by tharilya** [comment]
Thanks for the fast response! Ill keep on tracking #4262 .
