### ISSUE TITLE
Consider defining the existence of package binaries

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#4617]
Coming from https://github.com/conan-io/conan/pull/4615, it is not clear what defines the existence of package binaries:

- ``cache.conan_packages()`` does a ``os.listdir()`` to collect package_ids folders. They could be invalid, empty (case of short_paths after a ``conan info``)
- Metadata uses a ``self.packages = defaultdict(_BinaryMetadata)`` for binary packages, which silently continues even if a package does not exist and you request some data as its revision. Maybe it should fail, and another interface to define new packages binaries in the metadata is necessary.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, which defines the existencia of the package based on the database contents. Users are then able to run [`conan cache check-integrity`](https://docs.conan.io/2/reference/commands/cache.html#conan-cache-check-integrity) if they suspect the contents of the package have become corrupted, as the ids are now the hash of the conaninfo/conanmanifest, Conan is able to find most issues
