### ISSUE TITLE
After tools.unzip() Windows file attribute R (read-only) is gone

### ISSUE THREAD

**Issue by nussbrot** [conan-io/conan#4619]
Hi, i'm currently running into an issue probably related to issue #936. As requested there by @memsharded  i'm opening this as a new issue. So this is the same text as i posted there:

I have a conan package for a simulation tool. The package is like a tool installer.
The problem i'm having is that the tool needs a config file to be read-only.
And i need that behaviour on Windows and Linux.

The first step is to make sure that the permissions are set correctly in my sources (these are a source.zip or a source.tgz file) and this is true. That means:

* when i unzip my source.zip under Windows i get file attributes RA (= read-only, archived) on the config.ini.
* when i untar my source.tgz under Linux i get chmod = 0444 on the config.ini.

So, according to #936 i changed my conanfile and in the build method i use `tools.get(..., keep_permissions=True)`. The results are not promising, because the config.ini file, after the build step, has only the attribute A on Windows, missing the R.

As far as I can see it works on Linux as intended, so i guess the issue is only present for Windows file attributes.

I have attached a `conanfile.py` which will download the `sources.zip` from my google drive or you can alternatively use the attached `sources.zip` directly to reproduce the issue.

Let me know if you need further information.

[sources.zip](https://github.com/conan-io/conan/files/2909384/sources.zip)
[conanfile.zip](https://github.com/conan-io/conan/files/2909386/conanfile.zip)

**Comment by danimtb** [comment]
Hi @nussbrot 

Coming from the issue you pointed out it is something that we should investigate. As you know, permissions under Windows do not work so smoothly and we will need some time to debug the issue.

Currently the best approach would be to use ``os.chmod()`` in the recipe after unzipping so you make sure permissions are the same.

Thanks!

**Comment by nussbrot** [comment]
Hi @danimtb 

Thanks for pointing out a workaround. I'm using your suggested method.
For anyone else wondering how you'd change a file to read-only on windows, it will look something like this:

```python
import os, stat
os.chmod('file', stat.S_IREAD)
```

**Comment by memsharded** [comment]
Sorry this was stuck here for so long.

this reported the old Conan 1.X ``tools.unzip()``.


The Conan 2 new ``from conan.tools.files import unzip`` is:
```python
def unzip(conanfile, filename, destination=".", keep_permissions=False, pattern=None,
          strip_root=False):
```
containing a ``keep_permissions=False`` that could be set to ``True`` if desired.
I am closing this ticket as closed, but please create a new updated one if necessary.
