### ISSUE TITLE
QNX: provide appropriate generator as CMake flag

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4620]
Hi there,
for QNX SDK compiler one needs the CMake generator ```Unix Makefiles``` as the compiler does not support ```MinGW Makefiles```. But the default CMake generator on Windows is ```MinGW Makefiles``` if not using MSVC.

see: https://github.com/conan-io/conan/pull/4297#issuecomment-467858881

**Comment by danimtb** [comment]
Hi @Johnnyxy,

You have the an environment variable [CONAN_CMAKE_GENERATOR](https://docs.conan.io/en/latest/reference/env_vars.html#conan-cmake-generator) suitable for exactly this purpose.

You can set that in the `[env]` section of your profile to get it automatically applied.

Could you give it a try? Thanks!

**Comment by Johnnyxy** [comment]
Thx, it did the trick. :)
