### ISSUE TITLE
[question] Artifactory CE: Not showing "requires" or "settings"

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#4621]
Artifactory version: 6.8.2 rev 60802900
Conan (client) version: 1.11.2

I've created multiple packages (pre-built binaries) in local cache, two build configurations.

When uploaded to local conan server the "conan search <reference>" will show "requires" fields correctly.

When uploaded to Artifactory CE the "conan search <reference>" will list all the packages under the reference but it does not show "requires" fields at all? The "settings" are shown.

When inspecting the packages via Artifactory Web UI interface / "Conan package info" I can see the "settings" there, but "requires" is not visible anywhere either?

If I download a conaninfo.txt of one of the components (declares dependencies) the file does contain:

    [requires]
        A/1.Y.Z
        B/1.Y.Z

Names of the dependency projects are correct but minor and patch level version numbers are obscured?

Is this by design? Is there a way to inspect the real dependencies of a given package <reference> residing in the Artifactory CE?

**Comment by danimtb** [comment]
Hi @unzap,

You are right. A package search in a remote conan_server outputs the following:

```
$ conan search cppnanomsg/20181216@danimtb/testing -r conan-local
Existing packages for recipe cppnanomsg/20181216@danimtb/testing:

Existing recipe in remote 'conan-local':

    Package_ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
        [requires]
            nanomsg/1.1.2@bincrafters/stable:26d575619895d584ff4fb07701901d53ff4cdd6b
        Outdated from recipe: False
```

Whereas a conan repository in Artifactory CE 6.8.3 rev 60803900 says:
```
$ conan search cppnanomsg/20181216@danimtb/testing -r conan1
Existing packages for recipe cppnanomsg/20181216@danimtb/testing:

Existing recipe in remote 'conan1':

    Package_ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
        Outdated from recipe: False
```

However the requires are displayed as information of the packages, not from the recipe (there coudl be conditional requirements depending on the settings used):

![image](https://user-images.githubusercontent.com/10808592/53505129-8e272d80-3ab3-11e9-9203-0d8d72df4b33.png)

Also the *conaninfo.txt* file contains the following:

```
[settings]

[requires]

[options]

[full_settings]

[full_requires]
    nanomsg/1.1.2@bincrafters/stable:26d575619895d584ff4fb07701901d53ff4cdd6b

[full_options]
    nanomsg:enable_doc=False
    nanomsg:enable_getaddrinfo_a=True
    nanomsg:enable_nanocat=True
    nanomsg:enable_tests=False
    nanomsg:enable_tools=True
    nanomsg:shared=False

[recipe_hash]
    7a7e2a93d49d0a0d752a3fb0fe36cceb

[env]

```

To get the information about requirements you could use the ``conan info`` command: https://docs.conan.io/en/latest/reference/commands/consumer/info.html

But I agree this is a bug in artifactory that should be fixed. Thanks!

**Comment by unzap** [comment]
> To get the information about requirements you could use the `conan info` command:

Indeed, passing the needed settings via "-s" will give output with the "requires", thanks!

**Comment by monsdar** [comment]
The workaround with using `conan info` is not giving the same output as `conan search` would give. Info will reevaluate aliases, while Search will show what was actually used during the creation of a specific PackageId.

I'd not consider this Issue closed, as the problem this exists and the workaround is not solving it.

@lasote and @unzap: Do you agree? Can you reopen?

**Comment by memsharded** [comment]
Conan has changed since then, specially in Conan 2.0:

- The result of ``conan list`` (replacement for ``conan search``), now always display the ``conaninfo.txt`` as is, and it would match exactly the ``conan graph info`` serialized output, as now all is the same underlying thing.
- Aliases are maintained in 2.0 for some retro-compatibility, but no longer recommended for production, and should use standard versioning approaches and devops practices as alternatives
- Artifactory latest versions should be able to display the information from ``conaninfo.txt`` for 2.0 too.


I am closing this ticket as solved, but please don't hesitate to create new tickets for any further question or issue that you might have. Thanks!
