### ISSUE TITLE
set(CMAKE_FIND_ROOT_PATH_MODE_* ONLY) when cross-compiling, for Android at least

### ISSUE THREAD

**Issue by CAMOBAP795** [conan-io/conan#4629]
### Problem

Recently I faced with problem that during cross-compilation for Android form Linux host, cmake finds host's libraries https://github.com/bincrafters/conan-log4cplus/pull/10

### Proposed solution

Official Android toolchain by default define:

```
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
```

With possibility to change it via env variables

One of popular iOS toolchain do the same https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L466 so we may review possibility to do the same for iOS too and maybe for any cross-compilation

So I have proposal to enable this defines by default + leave possibility to change it

*I can help with implementation

### Checklist

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by SSE4** [comment]
@CAMOBAP795 does setting these values to `BOTH` also work? I have a problem that `find_package` doesn't work in case of `test_package` (e.g. for `OpenSSL`, `gtest` packages)

**Comment by SSE4** [comment]
@CAMOBAP795 I've checked, and in my environment it worked flawlessly if I have set these values to `BOTH`. please confirm.

**Comment by theodelrieu** [comment]
I did set them to BOTH in the android-ndk recipe, e.g. to let cmake find the embedded zlib

**Comment by CAMOBAP795** [comment]
I have tried `BOTH` on https://github.com/bincrafters/conan-log4cplus it doesn't work for me (`cmake` starts looking for system libraries)

As far as I understand [`BOTH`](https://cmake.org/cmake/help/v3.0/variable/CMAKE_FIND_ROOT_PATH_MODE_PROGRAM.html) it cannot work because it allow to search on host, so this is expected behavior 

----

> I've checked, and in my environment it worked flawlessly if I have set these values to `BOTH`. please confirm.
@SSE4 BTW which package have you checked?

> I did set them to BOTH in the android-ndk recipe, e.g. to let cmake find the embedded zlib

@theodelrieu If you will search for some library which doesn't present on android-ndk (for example there is no standalone `pthread`) it will start searching your host, which I think isn't right

Correct me if I'm wrong

**Comment by SSE4** [comment]
this is right, but conan libraries aren't part of Android NDK, so how to make find_package to find them?

**Comment by CAMOBAP795** [comment]
@SSE4 You are right, I have tried log4cplus with `log4cplus:with_iconv=True` and it failed

So if I come back to https://github.com/bincrafters/conan-log4cplus/pull/10
Looks like the only right solution is to modify cmake scripts of original project ([add ANDROID check there](https://github.com/log4cplus/log4cplus/blob/master/ConfigureChecks.cmake#L97))

**Comment by SSE4** [comment]
@CAMOBAP795 the fact that it finds host `librt` is weird for me, as I can't reproduce it on my docker images (NDK r19b). may be you can provide more details on how do you reproduce it, for instance:
- are you cross-compiling from Windows, Linux or Mac?
- are you using Docker image, if any?
- what's your NDK version?
- what's your conan profile?

**Comment by CAMOBAP795** [comment]
@SSE4 Sure

 - cross-compiling from Mac
 - docker `circleci/android:api-28-ndk-r17b`
 - NDK r17b
 - Conan profile:
```
standalone_toolchain=/opt/android-ndk-toolchains/arm-16
ndk_home=/Users/camobap/Developers/Platform/Mobile/Android/sdk/ndk-bundle
api_level=16
target_host=arm-linux-androideabi
cc_compiler=clang
cxx_compiler=clang++
target_specific_flags=

[settings]
os=Android
os.api_level=$api_level
arch=armv7hf
compiler=clang
compiler.version=7.0
compiler.libcxx=libstdc++

[env]
ANDROID_NDK_HOME=$ndk_home
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
CFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x -D__ANDROID__ -D__ANDROID_API__=$api_level -I$ndk_home/sources/android/cpufeatures $target_specific_flags
CXXFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x -D__ANDROID__ -D__ANDROID_API__=$api_level -I$ndk_home/sources/android/cpufeatures $target_specific_flags
LDFLAGS= -pie -march=armv7-a -Wl,--fix-cortex-a8

```

Thanks for your time, this isn't urgent anymore because if it works on your container it's enough for me

**Comment by SSE4** [comment]
I was able to reproduce.
seems to be a limitation of previous NDK version (I was thinking it might be CMake, but issue persists after upgrade to the same version - 3.12.1).

**Comment by CAMOBAP795** [comment]
@SSE4 maybe it's related that on ubuntu based docker images there is no `/usr/lib32/librt.so`, because `circleci/android:api-28-ndk-r17` is based on `debian:stretch-slim`?

**Comment by SSE4** [comment]
okay, now I have a confirmation this is an NDK r19b issue - it doesn't set [CMAKE_LIBRARY_ARCHITECTURE](https://cmake.org/cmake/help/v3.4/variable/CMAKE_LIBRARY_ARCHITECTURE.html) variable (it affects [find_library](https://cmake.org/cmake/help/v3.0/command/find_library.html)):
```
-- LIBRT LIBRT-NOTFOUND
-- CMAKE_PREFIX_PATH /home/conan/.conan/data/libiconv/1.15/bincrafters/stable/package/3a891f9314bf3d09dca01a00a86e1fffd99aa8f1/
-- CMAKE_LIBRARY_PATH /home/conan/.conan/data/libiconv/1.15/bincrafters/stable/package/3a891f9314bf3d09dca01a00a86e1fffd99aa8f1/lib
-- CMAKE_FRAMEWORK_PATH
-- CMAKE_SYSTEM_PREFIX_PATH /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt
-- CMAKE_SYSTEM_LIBRARY_PATH /usr/lib/arm-linux-androideabi/16;/usr/lib/X11
-- CMAKE_SYSTEM_FRAMEWORK_PATH
-- CMAKE_LIBRARY_ARCHITECTURE arm-linux-androideabi
```
vs
```
-- LIBRT /usr/lib/x86_64-linux-gnu/librt.so
-- CMAKE_PREFIX_PATH /home/circleci/.conan/data/libiconv/1.15/bincrafters/stable/package/1475c5d52076ee8216f8b1f3909b502c9e4d7267/
-- CMAKE_LIBRARY_PATH /home/circleci/.conan/data/libiconv/1.15/bincrafters/stable/package/1475c5d52076ee8216f8b1f3909b502c9e4d7267/lib
-- CMAKE_FRAMEWORK_PATH
-- CMAKE_SYSTEM_PREFIX_PATH /usr/local;/usr;/;/usr;/usr/local
-- CMAKE_SYSTEM_LIBRARY_PATH /usr/lib/w32api;/usr/X11R6/lib;/usr/lib/X11;/usr/pkg/lib;/opt/csw/lib;/opt/lib;/usr/openwin/lib
-- CMAKE_SYSTEM_FRAMEWORK_PATH
-- CMAKE_LIBRARY_ARCHITECTURE x86_64-linux-gnu
```
corresponding commit: https://github.com/wimal-build/ndk/commit/986c89bd2830f6bc7e2c6299a9f58a3264338057

**Comment by SSE4** [comment]
@CAMOBAP795 you may either upgrade to NDK r19b, or try to define `
CMAKE_LIBRARY_ARCHITECTURE` manually. is it an option for you?

**Comment by CAMOBAP795** [comment]
@SSE4 yep, thank you so much
