### ISSUE TITLE
improve ConanOutput interface

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#4632]
as discussed in hooks (see https://github.com/conan-io/hooks/issues/42, https://github.com/conan-io/hooks/pull/4), currently (as for conan 1.12.3) `ConanOutput` class has some limitations:

- it lacks `debug` and `critical` methods
- verbosity couldn't be controlled (`CONAN_LOGGING_LEVEL` doesn't affect it)

I personally think `debug` method would be very useful for conan hooks, and it should be possible to turn it on or off on demand.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Probably we need to align here on other things:
- Usage of ``output.warn()`` versus python ``warnings`` module. I'd say to route everything via ``output.warn()``, it would make sense.
- What is ``critical``? That means that it should fail with an error? We are using Exceptions for that, why this other mechanism?

**Comment by SSE4** [comment]
1. yep, `warn` should be renamed to `warnings`
2. I suppose `critical` is for some critical errors, that prevent any further usage of program. for instance, if conan doesn't find some mandatory file (e.g. `settings.yml`), that would be critical error message. versus some regular error, like failure to build recipe.

**Comment by memsharded** [comment]
> 1. yep, `warn` should be renamed to `warnings`

Not possible without breaking, as that is exposed to recipes too.

> 2\. I suppose `critical` is for some critical errors, that prevent any further usage of program. for instance, if conan doesn't find some mandatory file (e.g. `settings.yml`), that would be critical error message

Still don't get the difference with an Exception.

**Comment by SSE4** [comment]
@memsharded `warn` might be an alias to `warning`, right?

**Comment by memsharded** [comment]
Solved in 2.0
