### ISSUE TITLE
Facing issue while using autotool build environment

### ISSUE THREAD

**Issue by deekshith-elear** [conan-io/conan#4634]
Hi,
when I was trying to give ```configure_directory``` as argument to ```autotools.configure``` it is giving below error but if run ```self.run("/home/ubuntu/configure --prefix=/home/ubuntu/build")``` it is working fine
```
conanfile.py (json-c/1.13@None/None): WARN: Error running `configure --help`: Error 127 while executing configure_dir=/opt/src/configure --help
conanfile.py (json-c/1.13@None/None): Calling:
 > configure_dir=/opt/src/configure '--prefix=/opt/src/build/package' --build=x86_64-linux-gnu --host=arm-linux-androideabi
sh: 1: --prefix=/opt/src/build/package: not found
ERROR: conanfile.py (json-c/1.13@None/None): Error in build() method, line 22
	autotools.configure("configure_dir=/opt/src")
	ConanException: Error 32512 while executing configure_dir=/opt/src/configure '--prefix=/opt/src/build/package' --build=x86_64-linux-gnu --host=arm-linux-androideabi
```
Can anyone helpme out to solve this issue

**Comment by memsharded** [comment]
Hi @deekshith-elear 

I am trying to reproduce this issue, but so far without success. I don't know where the ``configure_dir=/opt/src/configure`` command is coming. Could you please provide the following information?

- Conan version that you are using
- A complete ``build()`` method on how you are calling the build helper.

Thanks

**Comment by memsharded** [comment]
Closing this thread as inactive.
Also outdated as that build system integration has been deprecated in 1.X and removed in 2.0
