### ISSUE TITLE
Python Requires restrictions

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4635]
Some personal ideas to discuss:
- The python requires package itself should inherit from a special PythonRequire class.
- The python require class cannot have anything but the name, the version, exports (no export_sources) and other python requires, it will raise during the export.
- If you want to inherit from a Conanfile declared in the python require, you have to write another class in the module of the python require.
- The export of a python require has to be smart enough to detect the python require sublclass and ignore the other conanfiles. 
- This way you don't mix attributes like the "exports" from the parent class. You have to extend a Conanfile, not a PythonRequire.
- A "conan create" of a python require will fail, saying: only export available.

**Comment by lasote** [comment]
Approved.

**Comment by lasote** [comment]
Still some issues. Related with the `in-source` VS `out-source` conversation, I tried this approach to have a "proxy" recipe in the project repository (can be found [here](https://github.com/lasote/openssl))

```
from conans import python_requires
base = python_requires("OpenSSL/1.0.2r@conan/stable")
class PkgTest(base.OpenSSLConan):
    name = "OpenSSL"
    version = "1.0.2r"
    scm = {"type": "git", "url": "auto", "revision": "auto"}

    @property
    def subfolder(self):
        return "."

    def source(self):
        pass
```
With this new approach we won't be able to do it, because we would need to prepare the `OpenSSL` recipe to be "python-required".

**Comment by memsharded** [comment]
These ``python_requires`` have been removed in 2.0, superseded in 1.X by the ``python_requires`` class attribute, closing as outdated
