### ISSUE TITLE
[bug] conanfile loader "crashes" because of missing __file__ attribute in Python 3.7(+)

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4636]
Hi there,
I am using multiple Python versions (e.g. 3.6, 3.7). My primary Python version is 3.6.
But occationally I execute Python version 3.7. With 3.6 there where no problems. 3.7 does not work.

I have 2 projects. One (```pkg_a```) gets ```python_requires```d into the other (```pkg_b```).
pkg_b inherits from a python file that gets exported with pkg_a. Now Python 3.6 everything works fine. In Python 3.7 I get an exception.

Crawling through the conan code I identified (at least I think) the code where the solution lies.
At [this code line](https://github.com/conan-io/conan/blob/4fdebfb79ce12f956b4be512253e8479e9d6bb17/conans/client/loader.py#L265) conan can catch an exception if the python module has no ```__file__``` attribute.
But in Python 3.7 I get a ```TypeError``` exception instead of an ```AttributeError``` exception.

The [Python docs describe](https://docs.python.org/3.6/library/exceptions.html#AttributeError) ([see](https://docs.python.org/3.6/library/exceptions.html#AttributeError)) that there could be raised a ```TypeError``` exception.

In turn I modified the code line [265](https://github.com/conan-io/conan/blob/4fdebfb79ce12f956b4be512253e8479e9d6bb17/conans/client/loader.py#L265) in the conan [loader.py](https://github.com/conan-io/conan/blob/develop/conans/client/loader.py).

From:
```python
except AttributeError: # some module doesn't have __file__
    pass
```

To:
```python
except AttributeError: # some module doesn't have __file__
    pass
except TypeError: # Python 3.7: some module doesn't have __file__
    pass
```

And everything worked like before.
I do not know if this is a Python or Conan problem. But at the moment this is a real issue as noone with a version of Python 3.7+ can execute my recipe.

For reference I made a minimal example to track down the issue.
[py36_py37_exception.zip](https://github.com/conan-io/conan/files/2915266/py36_py37_exception.zip)

**Comment by jgsogo** [comment]
Hi! Thanks! It looks like a bug, indeed. Just for clarification, the error is not the `module.__file__` raising an `AttributeError` (it returns `None`), but the `os.path.dirname` raising a `TypeError` for the invalid input argument.

I'm writing a test to reproduce this behavior

**Comment by memsharded** [comment]
I have had a look, there are a couple of issues removing this code:

- Every import of every recipe that is not previously used in Conan, will be parsed and imported everytime it is used. If a dependency graph of 100 packages uses an ``import myownlib``, the ``myownlib`` will be parsed and imported 100 times, which is a very expensive operation.
- Besides the performance, if for some reason someone is using a library that has global state or sync (lets say, a logger), it will fail, as every importer will have its own instance.

I will try to provide a test that proves this behavior.
