### ISSUE TITLE
Main Application structure [question]

### ISSUE THREAD

**Issue by ericjameszimmerman** [conan-io/conan#4643]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I have been working to modularize our codebase, and conan has been integral to that.
Presently we have a good number of shared library packages within a common Bitbucket project (each has their own git repo).

Our end application will still have some aspects of a monolithic application. While we will have various conan package dependencies, we will still be generating multiple libraries and executables from a single repository, some of which may have different dependencies than eachother.. 

I think that I could use a single conanfile at the root and use CMakeLists.txt to build everything.
It might be better if each library/executable could maintain its own dependencies...
In the end, I need to build and organize the outputs for an embedded linux application image.

What do you recommend?

Best regards,
Eric

**Comment by memsharded** [comment]
Hi @ericjameszimmerman 

I'd need to know a bit more about the codebase and what are the aspects of the "monolithic application".
If the codebase is now modularized and what you want is to be able to work on some package simultaneously, then you might be interested in the "Workspace" feature. It has been released as experimental some time ago, and it is getting an important update in this next Conan 1.13 release.

You can preview the documentation for this feature here: https://github.com/conan-io/docs/pull/1086/files, please have a look, and tell me if this is useful.

Also, if you want to discuss private details of your project in private, let me know (info@conan.io), we could discuss details in slack or email.

**Comment by ericjameszimmerman** [comment]
I am not quite sure if Workspaces are what I want... let me explain with an example

Say that we have the following shared conan packages on our server: (using generic names for simplicity)
- platform
- framework
- json

...each of those packages are contained within their own Git repository and are shared among multiple "programs", where "program" is a large customer project.

For the embedded Linux application portion of the project, the outputs consist of:
- the main / real-time customer-specific application
- a webserver
- various services (e.g. comm servers/clients, data service)
- numerous small utilities for debug, firmware update, etc.

Let's say that we want the source file structure to sortof look like this:
In this case, it is preferable to keep all of the application-specific content in one repository.

```
apps
    mainapp
        include
        src
    webserver
        include
        src
   modbustcpserver
        include
        src       
    dataserver
        include
        src       
devtools
    modbustcp-test
        include
        src       
    firmware-update
        include
        src       
docs
libs
    modbustcp
        include
        src       
rootfs
    var
        www
```

Lets say that the following dependencies exist:
- mainapp --> platform, framework
- webserver --> platform, json
- modbustcpserver --> platform, modbustcp
- dataserver --> platform, json
- mobsutcp lib --> platform


Notes:
- It would be nice drop-in or remove a folder from 'apps' or 'devtools' without minimal changes to include it into the build
- all of the output executables and libraries will be moved to /usr/sbin/ and /usr/lib respectively post-build while staging the target filesystem
- We would be working over time to move shared/common code from the program-specific repositories to shared/common repositories

**Comment by memsharded** [comment]
Now I understand better, thanks for the detailed explanation.

If you use the ``cmake`` conan generator, and use it with the ``TARGETS`` mode, then a target is defined for each dependency. So you could do something like this:

- Define a root conanfile.txt in your app, that defines all the dependencies: platform, json, framework
- Install it, using the ``cmake`` generator.
- In your root CMakeLists, include:

```cmake
include(..../conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
```

Then in each one of the children CMakeLists.txt, you can add the corresponding target to the link libraries:

In mainapp --> platform, framework
```cmake
add_executable(mainapp ....)
target_link_libraries(mainapp CONAN_PKG::platform CONAN_PKG::framework)
```

In dataserver --> platform, json
```cmake
add_library(dataserver ....)
target_link_libraries(dataserver CONAN_PKG::platform CONAN_PKG::json)
```

For internal relations between targets in the app, you use cmake as usual:

modbustcpserver --> platform, modbustcp

```cmake
add_library(modbustcpserver ....)
# modbustcp is defined in the other subdirectory
target_link_libraries(modbustcpserver CONAN_PKG::platform modbustcp)
```

Please tell me if this makes sense. Cheers!

**Comment by ericjameszimmerman** [comment]
I am using cmake_find_package
Is the following correct?

In mainapp --> platform, framework
```
add_executable(mainapp ....)

find_package(platform)
include_directories("${platform_INCLUDE_DIRS}")
target_link_libraries(dataserver platform::platform)

find_package(framework)
include_directories("${framework_INCLUDE_DIRS}")
target_link_libraries(mainapp framework::framework)
```

In dataserver --> platform
```
add_library(dataserver ....)

find_package(platform)
include_directories("${platform_INCLUDE_DIRS}")
target_link_libraries(dataserver platform::platform)
```

So, I should have a single conanfile.txt (or conanfile.py) in the project root to bring in all of dependencies for each subproject and use cmake to find and link them

**Comment by progician** [comment]
Bit of a tangent but you could make your life easier by using the 'target_include_directories' command, which can be transitive, so you don't have to use the `include_directories` command at all when you link against it, because CMake will populate all the transitive properties, such as INTERFACE_INCLUDE_DIRECTORIES, INTERFACE_LINK_LIBRARIES, etc.

**Comment by memsharded** [comment]
This ticket refers to legacy generators, replaced by new CMakeDeps time ago, closing as outdated, please create new tickets if necessary, thanks.
