### ISSUE TITLE
Conan crash due to wrong function signature in migrations.py

### ISSUE THREAD

**Issue by RadMap** [conan-io/conan#4645]
Installing Conan version 1.12.3 and running it (simply "conan" from the cmd line) results in crash.
The error stems from wrong signature in function call in conans/client/migrations.py.

On line 129, there is the following call

`migrate_to_default_profile(conf_path, default_profile_path, output=self.out)`

but the definition of `migrate_to_default_profile` on line 159 reads

`def migrate_to_default_profile(conf_path, default_profile_path)`

the call is incompatible with the signature. `output=self.out` should be removed since it is not used in `migrate_to_default_profile`

**Comment by memsharded** [comment]
Hi @RadMap 

Yes, this seems a bug, when upgrading from versions prior than ``if old_version < Version("0.25"):``, which even if the code is there, it was quite unexpected.

If you want to workaround it, you could remove the file ``.conan/profiles/default`` from your conan cache, everything should work then.

We will have a look, and try to solve it as soon as possible. Thanks for reporting!

**Comment by memsharded** [comment]
Fixed, will be released in conan 1.13
