### ISSUE TITLE
[question] explicitly link against static library's version

### ISSUE THREAD

**Issue by thekvs** [conan-io/conan#4646]
If "conan'ized" library provides both static (`libfoo.a`) and shared (`libfoo.so`) libraries what is the most idiomatic way to link against static (i.e. `libfoo.a`) in my executable application? For now I am always linking against shared version of `libfoo`.

**Comment by uilianries** [comment]
Hi @thekvs !

You could add an option for packaging the shared library or the static one.

We have some explanation about shared option [here](https://docs.conan.io/en/latest/howtos/manage_shared_libraries/env_vars.html) and [here](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#library-types-shared-static-header-only). Also, you could take a look on [Cryptopp recipe](https://github.com/bincrafters/conan-cryptopp/blob/stable/7.0.0/conanfile.py#L20).

However, if you want to package both shared and static libraries, but link only one, you can add the `shared` option as well, but remove it from `package_id`:

```python
def package(self):
    self.copy("*.h", dst="include", src="src")
    self.copy("*.so", dst="lib", keep_path=False)
    self.copy("*.a", dst="lib/static", keep_path=False)

def package_id(self):
    del self.info.options.shared

def package_info(self):
    self.cpp_info.libs = ["hello"]
    if not self.options.shared:
        self.cpp_info.libdirs = ["lib/static"]
```

It will provide one package with both libraries, the name used to link will be the same `-lhello`, however, the library dir is not the same, avoiding any possible collision.

Regards!

**Comment by thekvs** [comment]
Hi @uilianries!

Thank you for the reply, it's quite useful in the context of packaging libraries.

But the problem is that now I am not packaging library, I am trying to build some executable application leveraging conan's ecosystem and one of the needed libraries (https://bintray.com/bincrafters/public-conan/lz4%3Abincrafters to be precise) has both static and dynamic versions and my app is always picking up dynamic one. I'd like  to link against static version since the whole point of migrating to conan ecosystem was to build app without external dependencies.

**Comment by uilianries** [comment]
Ops! This is a bug!

I can confirm your behavior, I'm going to provide a fix ASAP to lz4.

Thanks for reporting!

**Comment by madebr** [comment]
A post_package conan hook that detects presence of shared and static libraries might be useful.

**Comment by uilianries** [comment]
@madebr We could open an issue to hooks. Also, we could update conan-center hook or binary_linter instead.

**Comment by madebr** [comment]
@uilianries It appears this is already done by the binary linter at https://github.com/conan-io/hooks

**Comment by jgsogo** [comment]
Hi @thekvs,

Please, confirm that the PR by @uilianries fixes your issue, it was indeed a bug in the `lz4` package I think.

Thanks

**Comment by thekvs** [comment]
Yes, now everything works. Thank you, @uilianries !

**Comment by uilianries** [comment]
@jgsogo could you please close this one?

**Comment by jgsogo** [comment]
Thanks!

**Comment by shivarajshivu** [comment]
Hi All,

I'm using CONAN mainly to store external libraries and its header files.  

Using conan i have built one c++ static library called as "traci". Using CONAN_PKG command i'm able to build my executable linking traci, there are no issues,  but when i'm executing i'm getting symbols related to "traci" library as not found. 

but in cmake instead of linking using CONAN_PKG , if i link by giving abosulte path of traci library, i'm able to run ...

  target_link_libraries(my_exe
      PUBLIC
        CONAN_PKG::traci
    )

Can anyone please assist me in resolving this problem.

**Comment by madebr** [comment]
@shivarajshivu If the error happens during executing, then `traci` is a shared library.
Run `ldd` on the `my_exe` executable to see what shared libraries it needs.
