### ISSUE TITLE
[question] [suggestion] conan create skip install

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#4647]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
```
Conan Version 1.12.2
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

Hi there,

This is an optimization, and isn't something that is blocking.

On our Build Server I'm using `conan create` with `--build outdated` to determine if a particular package needs to be rebuilt. We have jobs that walk the whole tree and rebuild everything using the `-bo` flag to get the build order.
If the package does not need to be rebuilt, is there a way to prevent download all of the packages tarballs as part of the install?
I can tell if it was actually built after the fact, by exporting the json with `-j` and checking the `built` flag

For example if the package has already been built, I see it downloads all the packages, even though my CI build doesn't need them. Is there anyway to figure out this information before hand (whether a package is up to date, and needs to be rebuilt), without downloading all of the packages themselves?

Example when my project does not need to be rebuilt:
```
Installing package: THIS_IS_THE_PROJECT_IM_BUILDING/2.10.3-9+g7c71010@USER/latest

DEPENDENCY/3.2.1-76+g2ba7538@USER/latest:3d8c85c54f7fd2f6b48e52cc88af1bf81a02a93d - Download
DEPENDENCY/4.0.1@USER/latest:b5051cccf2b82315f8ebd12ee31781b597f3f7e5 - Download
THIS_IS_THE_PROJECT_IM_BUILDING/2.10.3-9+g7c71010@USER/latest:bb3c94f0aa85eaaaf1252581399ff77f50b97f07 - Download
DEPENDENCY/2.2.2@USER/latest:e74070b001e757736517548f138e868eac89aa87 - Download
DEPENDENCY/2.2.7@USER/latest:e74070b001e757736517548f138e868eac89aa87 - Download
```

You'll notice that it doesn't actually need to build, and it's downloading the project that I'm trying to build. It's also downloading all the dependencies.

This wastes time and network resources.
As you get further and further up the dependency tree, it takes longer and longer as you are downloading a large dependency tree, which ultimately may not be used, because we aren't building anything.
We have a pretty large dependency tree (~100 packages) and some are very large.

I was thinking that'd it be useful to somehow determine this beforehand.
`conan info` has similar functionality to what I need, but it only shows it for dependencies.
Maybe `conan create` needs a new flag which is `don't install` step.
Then I can run `conan create . --build=outdated --dont_install -j file.json`, find out if it needs to be rebuilt from the json or not. Then rerun `conan create` without that flag.

(P.S. This tool is amazing so far, really appreciate it.)

**Comment by memsharded** [comment]
Hi @Mark-Hatch-Bose 

``conan create`` is totally oriented to build the package, or at least to consume it (with test_package, for example), so the binaries should be there.

Maybe, have you considered the ``conan info --dry-build=xxx`` argument? It will do the same analysis of binaries that ``conan create`` does, but without actually building or retrieving the dependencies binaries.

Please have a look and tell me if this argument helps. Thanks!

**Comment by Mark-Hatch-Bose** [comment]
@memsharded 
Thanks for the info I did some testing.
Since `conan info` seems to mimic `conan install`, it always says it needs to build the top level package.

for example, `conan info <packageName>/2.5.0-0+g0137005@master/latest -b=outdated --update -r <remote>` or even using `-db=outdated` rather than `-b=outdated`
It will always return that the top level package (packageName) needs to be built.

The exact information I'm trying to find is if that particular top level package needs to be rebuilt or not with all the latest. When running `conan create --build outdated` it will detect if the top level package needs to be rebuilt or not.

I'll try to provide more detailed information later, but I'm getting on a flight soon.

**Comment by Mark-Hatch-Bose** [comment]
I think this works now, I think most of my issue was confusion over the conan cache.

Before clearing cache, even with explicit `-u` flag, the latest packages are not downloaded.
You'll notice `Recipe: update available` on PackageA. I expected with the `-u` flag for it to grab the latest. Maybe I need `-r <remote>`?

`conan info . -pr <profile> -u -db=outdated`

```
PackageA/2.2.3@barbarian/latest
    ID: 123fec4ccc8c1fd87d705eb4a68952669e2b1615
    BuildID: None
    ...
    Recipe: Update available
    Binary: Build
    Binary remote: barbarian
    Creation date: 2019-03-06 05:41:52
    Required by:
        ...
conanfile.py (TargetPackage/2.5.0-12+gac7020b@None/None)
    ID: 8247fea2fb648b406828fa5bddf07d286ddf2cff
    BuildID: None
    Requires:
        PackageA/2.2.3@barbarian/latest
        ...
```

After `conan remove "*" -f` and running same command, it correctly shows everything is downloaded. But I can't tell if the TargetPackage needs to be rebuilt. It's clear it can't tell cause it doesn't have a user/channel.

So I run the command again with an exact package reference, and this looked good! I'm unsure why it was saying `build` before, but this time I am using `-r <remote>` and `-u` flags
`conan info TargetPackage/2.5.0-13+g5840466@master/latest --pr <profile> -u -db=outdated -r barbarian`

```
TargetPackage/2.5.0-13+g5840466@master/latest
    ID: 1f5b2ae52678dbf1f8ded31271ca47dcbf88769b
    BuildID: None
    ...
    Recipe: Cache
    Binary: Download
    Binary remote: barbarian
    Creation date: 2019-03-06 16:23:23
    Requires:
        ...
```

Perfect, so now in my build scripts:
1. `conan inspect` to get the version.
2. Output `conan info` to JSON checking if it needs to be rebuilt.
3. Check if we are going to build <TargetPackage>
4. If we are not going to build it, don't bother calling `conan create`

**Comment by Mark-Hatch-Bose** [comment]
Initial results are in. This reduced our build time for our whole tree build (when there are no changes) by 40%.
We only have about 10% of our components using conan, so I assume that the savings will be massive as we add more and more dependencies to the tree.
