### ISSUE TITLE
[question] why isn't python requires updated with --update?

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#4650]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

```
Conan Version 1.12.2
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

I see from documentation at:
https://docs.conan.io/en/latest/extending/python_requires.html

That python_requires are not updated with --update 
`They are not automatically updated with the --update argument from remotes.`

But why? Every time I update the python_requires I need to inform all users to clear their cache for those packages to be updated? Seems very cumbersome.

**Comment by memsharded** [comment]
The main reason was that due to the "inversion of control" that is necessary to process python-requires, passing user information to the resolution of python-requires was quite ugly.

The architecture has improved a little bit, so I think it is possible, adding ``self.update`` and ``self.check_updates`` to ``ConanPythonRequires``, I'll submit a draft PR, to be considered for 1.14

**Comment by memsharded** [comment]
Implemented. This will be released in next Conan 1.14. 
Thanks for raising this issue!

**Comment by Mark-Hatch-Bose** [comment]
@memsharded This is still not functioning. `conan version 1.15.1`

I'm using python requires in the manner described here:
https://docs.conan.io/en/latest/extending/python_requires.html#python-requires-reusing-code-experimental

I'm defining base ConanFile recipes, which works great!

In my downstream conanfiles:
```
common = python_requires('ConanRecipes/[>=0.1.0-0, include_prerelease=True]@mh/testing')

class ThisIsAPackage(common.BaseRecipe):
```

However, it still does not get updated with `--update` 
I have to remove the ConanRecipes locally to get latest version.

`conan remove ConanRecipes* -f`

Then it downloads the latest one.

**Comment by iiknd** [comment]
Hi,

is there any update on this? We are using Conan 1.39 and the issue is still present. When ever we have updates in 'python_requires' module we need to manually delete it before running the "conan install ..." command?

**Comment by tapia** [comment]
Hi @iiknd 

Could you please attach a reproducible example? We have this case [covered by tests](https://github.com/memsharded/conan/blob/develop/conans/test/functional/python_requires/python_requires_test.py#L485), and they're passing fine, so maybe yours is an overlooked corner case and we must reopen this issue.

**Comment by iiknd** [comment]
Hi @tapia,

this appears to be my bad, I just found this from the documentation was I have missed early:

```
def package_id(self):
    ...
    self.info.python_requires.recipe_revision_mode()  # minor mode by default
```

I will schedule builds in our CI to test this again. I'll report back if there still exists any issues.

**Comment by tapia** [comment]
Good to hear :-) The issue is closed, so if you have any problem and have to report back, please reopen it so we get notified.
