### ISSUE TITLE
cmake_find_package generator does not fill _LIBRARY_LIST by using self.cpp_info.release.libs/self.cpp_info.debug.libs

### ISSUE THREAD

**Issue by LucileM** [conan-io/conan#4651]
- Conan version 1.12.1
- cmake version 3.11.4
- Windows 10
- compiler Visual Studio MD 15

Using and `self.cpp_info.release.libs`/`self.cpp_info.debug.libs` in package_info for mylib.
While try to use this library with `cmake_find_package` generator nothing is generated in `Findmylib.cmake` for the variable `mylib_LIBRARY_LIST`. 
So mylib_LIBRARIES is empty but mylib_FOUND set to 1 in my project.

**Comment by Johnnyxy** [comment]
Have a look at the [docs at the end of the topic](https://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-package). There it states:

> The automatic conversion of multi-config variables to generators is currently only implemented in the cmake and txt generators. If you want to have support for them in another build system, please open a GitHub issue.

This has been brought up already (here: https://github.com/conan-io/conan/issues/4592) as feature request.

Best regards

**Comment by LucileM** [comment]
Oh sorry, I did not notice this part in the documentation.
Thank you.
Kind regards.
