### ISSUE TITLE
Add functionality to `undeploy()`

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4652]
It is possible to copy files from package-space to user-space by using the `deploy()` function. There are usecases where it is necessary to remove those files from user-space again. What I'd like to propose is some kind of `undeploy()` or `uninstall()` method.

With this the creator of a package has the ability to remove any traces his package could've done from the users system.

Usecase where it could be troublesome to not have `undeploy()`:
* Imagine a system that loads a number of plugins from a directory `./plugins/` during startup and executes them.
* PackageA/1.0.0 deploys 10 plugins into the userspace
* PackageA/2.0.0 only deploys 8 plugins into the userspace. Perhaps it had been found that the other 2 plugins are misbehaving in some way

When the user now performs `conan install PackageA/1.0.0@user/channel` and afterwards executes `PackageA/2.0.0@user/channel` the 2 faulty plugins from before will stay in the plugin directory. The package-creator knows about the 2 faulty plugins, if he had a `undeploy()` function he'd probably clean the `./plugins/` directory before deploying the new plugins.

This is sort of a fabricated example, but it shows how complex this topic could get. Of course there's the obvious usecase where a user wants all the binaries gone out of his system after he tried something.

**Comment by jgsogo** [comment]
Hi @monsdar,

I find this functionality tightly related to the _uninstall system requirements_ one. It has been discussed 
 (still open) in #2774 and #3760. The main problem is that in the general case, two packages can deploy the same files (overriding them) and if you remove all of them then the remaining package will be broken. Of course, it is up to the user, and there are safer workarounds like the ones proposed in the linked issues.

I'm not sure if we are going to provide an `undeploy` (or the equivalent to remove system requirements soon), but in the meantime maybe the implementation using hooks (https://github.com/conan-io/conan/issues/2774#issuecomment-429765712) can be released to get some feedback from people using that kind of behavior (at this moment there are no `pre_remove`/`post_remove` hooks).

We've just published a [blogpost trying to promote hooks usage](https://blog.conan.io/2019/02/28/Extending-conan-with-hooks.html), so it is very important for us to know if people are using it or not, if they find this pluggable behavior interesting or not.

**Comment by monsdar** [comment]
The hook-approach sounds very reasonable. Though I think `remove()` is not really the same as undeploy (another issue I'm looking forward to is also the split of `conan install` and `deploy()`).

A solution could be a hook (is it still a hook then?) that allows to add custom commands. Allowing something like `conan undeploy foo/1.0@user/channel`. Then again: Would be even more useful when this system allows for recursive calling of `undeploy()` (so also call the undeploy function of the dependencies).

**Comment by memsharded** [comment]
``deploy()`` and ``imports()`` have been completely removed. Users can use deployers in 2.0 and custom commands to implement the logic they prefer to handle deployment cases. Closing as outdated.
