### ISSUE TITLE
Add options that do not trigger a rebuild of the package

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4654]
There are usecases where a package provider could provide options for a package that are not affecting the build type of the package. Therefore those options do not need to trigger a rebuild of that package.

A possible usecase has been described in this comment: https://github.com/conan-io/conan/issues/3280#issuecomment-469185721

In the concept within that comment it is possible to use options in order to change the destination path of the deploy function. Obviously the binary artifacts of the package are not affected by this option, the current version of Conan forces the package to be rebuilt though.

There are different non-breaking ways to achieve this functionality:
1. Allow the creator to mark specific options as "non-build options" (there's surely a better name for them). The creator still defines all his options and default-options, with another explicit call he then can mark these options so that they'll be ignored when it comes to determnine which binary package to use.
2. Add a new dictionary instead of options. A possible name could be `parameters` or something similar. Per definition `options` would be affecting the binaries, while `parameters` would not.

**Comment by Johnnyxy** [comment]
Correct my if I am wrong. You want to use certain options in a conan recipe that you can use in your conanfile.

```python
class recipe(ConanFile):
    options = {"print_debug_infos": [True, False]}
    default_options = {"print_debug_infos": False}

    def build(self):
        if (self.options.print_debug_infos):
            self.output.info("my debuginfo")
```

Now you want that option ```print_debug_infos``` not to influence the [package_id](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-id) as it has nothing to do with the final generated package.

Then you could [remove](https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info) it from the package_id-generation-logic that defines your [package ABI](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=package_id#defining-package-abi-compatibility) (package_id):

```python
class recipe(ConanFile):
    options = {"print_debug_infos": [True, False]}
    default_options = {"print_debug_infos": False}

    def build(self):
        if (self.options.print_debug_infos):
            self.output.info("my debuginfo")

    def package_id(self):
        del self.info.options.print_debug_infos
```

**Comment by monsdar** [comment]
This is exactly what I'm looking for. Will close here, thanks a lot!
