### ISSUE TITLE
[question] expected behavior for export-pkg tools.unzip

### ISSUE THREAD

**Issue by conanuser1234** [conan-io/conan#4659]
Conan version 1.11.1
Windows 10

I was wondering the expected behavior of tools.unzip when using the export-pkg command from outside the conanfile.py's directory.

So taking the example package source directory and conanfile.py below:

```
└───some_path
    └───package
         ├───conanfile.py
         └───library.zip
```

``` py
from conans import ConanFile, tools

class ExampleConan(ConanFile):
    name = "library"
    version = "1.0"
    settings = "os", "arch"

    def package(self):
        zip_file = "library.zip"
        tools.unzip(zip_file)
        self.copy("*", dst="bin", src="bin", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

The command below fails during the copy to find the unpacked contents of library.zip as it gets unzipped to the cwd(some_path).

``` sh
# from outside the package's directory
conan export-pkg some_path/package example/stable
```

Is this the expected behavior? I got stuck on this thinking the expected behavior was for the library.zip to be unzipped into the same directory as the conanfile.py. 

Or maybe another question, is it just ill advised to use export-pkg for my case and I should use exports_sources to export the library.zip and treat the unzip as a build step?

**Comment by Johnnyxy** [comment]
The [documentation](https://docs.conan.io/en/latest/reference/conanfile/methods.html?highlight=self%20copy#package) for ```self.copy``` states 

> artifacts are copied from the build folder to the package folder

When you unzip something at package time most likely it will not be placed in the ```self.build_folder```. Propably you unzip into ```self.package_folder``` already.

```tools.unzip``` works in the current directory. You should check what directory you ```package``` function is in at runtime.
```python
from pathlib import Path
def package(self):
    self.output.info(f'the current directory in package(self) is: {Path().resolve()}')
```

**Comment by jgsogo** [comment]
Hi @conanuser1234 

There are different questions here, let me go ony by one:
 * `tools.unzip` has a `destination` argument, by default it is `.` (current folder), but you can make it explicit to set the build folder: `tools.unzip(zipfile, destination="your/directory")`
 * for correctness, everything related to grabbing files/sources is better to do it in the `source()` method, even if there is no `build` step (in many ways it is like a header-only library) and if all you are doing is repackaging a zip file maybe there shouldn't be any settings (it will generate the same package for all the configurations).

**Comment by Johnnyxy** [comment]
@jgsogo you said 

> grabbing files/sources is better to do it in the source() method

Correct me if I am wrong. This does not apply to prebuilt files (shared object (so, dll), libs (a, lib), executables, etc.) as the [documentation](https://docs.conan.io/en/latest/creating_packages/existing_binaries.html#downloading-and-packaging-pre-built-binaries) says that this should be done in the ```def build(self)``` function.

**Comment by jgsogo** [comment]
If those files will be the same for every configuration there should be better to do it in the `source()` method (download them only once), but if they are different for any configuration then the `build()` is the way to go.

Talking about prebuilt files as they should be different for each configuration the `build()` method is the place, as you are suggesting.

Thanks!

**Comment by conanuser1234** [comment]
> Hi @conanuser1234
> 
> There are different questions here, let me go ony by one:
> 
> * `tools.unzip` has a `destination` argument, by default it is `.` (current folder), but you can make it explicit to set the build folder: `tools.unzip(zipfile, destination="your/directory")`

> * for correctness, everything related to grabbing files/sources is better to do it in the `source()` method, even if there is no `build` step (in many ways it is like a header-only library) and if all you are doing is repackaging a zip file maybe there shouldn't be any settings (it will generate the same package for all the configurations).

Thanks for the quick replies!

I stripped down the example from a conanfile I was working with which copied different things from the zip depending on arch and so on, sorry if that was confusing.

One detail, I'm not downloading the binaries though, the binaries are adjacent to the conanfile.py. So would you suggest I just add "exports_sources="library.zip" to my conanfile.py?
If my library.zip file is very large, I'll end up storing it's contents twice, once in .conan/data/..../exports_sources directory and then again in the package directory.

**Comment by jgsogo** [comment]
No, use `export_sources` just for sources, no need to store you `library.zip` file. Several reasons: you are downloading it (so you won't ever use the one exported as sources), and also you are packaging what you will need.

**Comment by conanuser1234** [comment]
> ... you are downloading it ...

Sorry 😅, maybe I explained something badly. I'm "not" downloading "library.zip". "library.zip" and "conanfile.py" will be source controlled in the same repo. So I'll have them both at hand when I need to package them.

**Comment by jgsogo** [comment]
It was my fault, I read `.zip` and I imagined it was a file downloaded from somewhere 🤦‍♂️

If the `conanfile.py` and the `library.zip` are in the same repo and those files are _the sources of the package_ (someone will tell you not to store binary files in a repo ^^) you have two alternatives then:
 1. (as you suggested) you need to _export_ those sources (`export_sources`), just in case anyone needs to build the package those sources must be there available to Conan, or
 2. you can use the _SCM feature_, you can read about it in the docs: https://docs.conan.io/en/latest/creating_packages/package_repo.html?highlight=scm%20feature#capturing-the-remote-and-commit-scm, no need for `export_sources`, Conan will clone your repo (Git or SVN) if it needs to build the package from sources

**Comment by conanuser1234** [comment]
Ok great! This makes sense to me. Big thanks for getting my question answered @jgsogo @Johnnyxy

**Comment by memsharded** [comment]
Hi all,

It is not clear to me the final conclusion, so please @conanuser1234 (also reference for other readers) take this into account:

- If library.zip contains pre-compiled binaries (.lib, .a, .so, .dylib, .h, etc), or final artifacts (headers in case of header-only library) to be packaged, then, yes, the way to package them is with ``conan export-pkg``. Please do not use ``exports_sources`` for that. In this case, the recipe won't be building anything with ``build()``.

- If library.zip contains the source-code, then ``conan export-pkg`` is useless, and indeed you should use ``exports_sources`` or other source method (like SCM). The recipe will have a ``build()`` method in which the binary artifacts will be built from source.

I hope this helps. Cheers.
