### ISSUE TITLE
Allow the conan library module to be run as a script

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#4666]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Python allows a python module to be run as a script, using the `-m` option.
An example of this usage is using the `pip` manager.
This is useful if a system contains multiple python installations and you want to run something using a particular python version.
```
python -m pip search conan
python3 -m pip install --user --upgrade conan
```
This would require a `__main__.py` script in the `conans` folder.

```
python -m conans
```

It is also possible to have multiple `__main__.py` scripts.
e.g. one in the `conans.client` module and one in the `conans.server` module.

```
python -m conans.client
python -m conans.server
```

**Comment by Johnnyxy** [comment]
Hi there,
for using different python versions you have to prepare the environment before execution of python.
You have to change environment variables to the appropriate python paths and then you can execute conan with that python version without any additional logic in conan.

Example for Windows as a batch file (e.g. python path: c:\tmp\python36 and c:\tmp\python37):
```batch
setlocal
set "PYTHONHOME="
set "PYTHONPATH=c:\tmp\python36\lib"
set "PATH=c:\tmp\python36;c:\tmp\python36\Scripts;%PATH%"
pip search conan
endlocal

setlocal
set "PYTHONHOME="
set "PYTHONPATH=c:\tmp\python37\lib"
set "PATH=c:\tmp\python37;c:\tmp\python37\Scripts;%PATH%"
pip install --user --upgrade conan
endlocal
```

I am using a similar script to switch conveniently between my [portable python](https://winpython.github.io/) versions on my system.

**Comment by jgsogo** [comment]
You can write your own scripts, but the usual approach to handle several python versions (or different requirements versions) is to use _virtual environments_ ([link](https://docs.python.org/3/tutorial/venv.html)). There are other packages to help with virtualenvironments that are worth taking a look into them, like [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/).

I think that this approach (IMO it is better with virtual-environments than custom batch scripts) is the way to go in order to run different python versions.

**Comment by Johnnyxy** [comment]
Yes you are right. Switching python installations by using virtual-environments is another approach.

The difference between both approaches is that I can use a python version that is in a persisent state. As this is only for development purposes setting the python version by temporarily changing paths in a console process (instantly; no copying involved) is much faster. And all changes are like installing packages are persistent. The "work" of executing a switch-script or "activate"-script is the same.

With the virtualenvwrapper one could achieve the same effect, to isolate serval python version environments. But as I do not install python and just use portable versions (8 versions to be precise; 2.7,3.5, ... x86, x86_64) at all, I can remove and unpack the python folder too to reset a brocken python version folder.

It is more a mater of taste and control :).

**Comment by jgsogo** [comment]
Hi @madebr, I'm closing this issue, but reopen it again if any of the proposed approaches work for you. Thanks!
