### ISSUE TITLE
opt-in detection of pre-releases for Visual Studio

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4671]
Introduce an opt-in at `conan.conf` to activate the detection and usage of visual studio pre-releases.

**Comment by Trass3r** [comment]
Is there an easy way to work around this?

**Comment by lasote** [comment]
Well, it affects only to the auto-detection of the default profile, you can always create your default profile by hand or install it with `conan config install` command from a repository or zip.

**Comment by memsharded** [comment]
Closing this ticket as not planned
