### ISSUE TITLE
conan install does not fail if there are missing files in package

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#4672]
If for any reason, the package uploaded to a server is incomplete (has at least one of the three files: _conaninfo.txt_, *conanmananifest.txt* or *conan_package.tgz*), the installation in all cases success.

In the case of the *conan_package.tgz* it could be valid as empty packages are allowed (although I am not sure if that makes sense). This is the case of the recipes for generators.

Downloading the packages without *conaninfo.txt* could be problematic for a local **conan search** and having no *conanmanifest.txt* means the package is corrupted for an eventual upload of the package.

Related to #4662 and #871

**Comment by danimtb** [comment]
Worth to note that the tests implemented in #4662 are using packages with empty content and the *conan_pacakge.tgz* is still being uploaded.

Anyway, this issue should be fixed by that PR too.

As  @memsharded was taking a look at it, I will assign this issue to him so we can double check.

**Comment by memsharded** [comment]
Closed by #4662
