### ISSUE TITLE
Question: Custom generator to capture dependency package_id?

### ISSUE THREAD

**Issue by drmacdon** [conan-io/conan#4679]
I've been trying to write a generator which be able to log which conan dependencies packages were  resolved to. Reading through the existing generators I see they have the package name and version but I haven't found any generators using the package_id or user/channel of a dependent package. 

I want to generate/compile my application with a --version listing which is as specific as possible including dependencies.  
  
Is there a way to obtain the requirement's package_id inside a generator? 

Thanks!

**Comment by danimtb** [comment]
Currently, it is not possible to get the package id as the generators only care about propagating the information of the library important for the build systems.

However, you can save the log of the install command as the package id information is there https://docs.conan.io/en/latest/reference/commands/output/install.html#install-and-create-output

**Comment by drmacdon** [comment]
I changed my approach to parse the JSON install and create output which works when manually building from a build folder and CMake can ensure ${CMAKE_BINARY_DIR}/install.json exists. But when a package is installed from the conan recipes CMake does not know the location of the install.json as it lands in the present working directory not the build tree. 

The advantage of being able to use a generator is it happens as part of the conan flow and the generated file is thus in the $CMAKE_BINARY_DIR folder for consumption.

**Comment by danimtb** [comment]
Yes, that would be the best approach. The generators do not have information about the package ID ( that info is not available in the [deps_cpp_info](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-env-info) object), as this is something only relevant for the Conan model. With the output of the install command, you are getting information about the execution of Conan itself, and that is the only way to get the package id currently.

I understand that a generator will better fit your needs but I think this is very specific to your use case and will require major changes in Conan to implement a feature like this.

**Comment by danimtb** [comment]
Closing this issue as it seems that the approach change to the JSON output.
