### ISSUE TITLE
Conan client arg handling differs slightly between windows and linux platforms.

### ISSUE THREAD

**Issue by RFerraro** [conan-io/conan#469]
I've noticed that when performing a "conan install" invocation with the client, passing "--build=missing" only works on linux, while "-build=missing" only works on windows.

Is this intentional, or am I missing something? I'm specifically seeing this issue when using conan in Appveyor and Travis-ci environments.

**Comment by memsharded** [comment]
The syntax is with two "-":
```bash
--build=missing
--build missing
```
That should work in every system, is it failing in Windows? In appveyor?

**Comment by RFerraro** [comment]
I went back and tried reproducing this issue and I can't duplicate the behavior I was seeing, so maybe I'm going crazy. If I happen to see this issue pop up again i'll make note to write a script that can demonstrate it in action.

**Comment by memsharded** [comment]
Don't worry, thanks for telling. Just reopen the issue and tell us if it happens again.
