### ISSUE TITLE
copy should have the option to log all files matched/copied by a call

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#4690]
A frequent issue we have is that copy (particularly during package) does not match the files it is intended to match, but often too many files are packaged. To allow to investigate this better, it would be good if, optionally, the files matched by each call should be logged. Currently, only the overall set of files matched by all call options, and the output is aggregated by extension if there are more than a few files.

**Comment by uilianries** [comment]
Hi @sigiesec !

For now you could use `conan get` to inspect the manifest file and check what was copied to the package folder.

    conan get -p 35437353b857392790f3121d268b1db3fb9a09b0 zlib/1.2.11@conan/stable conanmanifest.txt
    1549360440
    conaninfo.txt: ef2964b8f3037c9fb22512f086cf59b7
    include/zconf.h: 8e174685774bae412b6e4aa354057f96
    include/zlib.h: 0338828e9d00c94645648b1517108324
    lib/libz.a: 668bc4404de773e98b23f8ed770dca1f
    licenses/LICENSE: 1af2e5353c16e930435fff550f827c3e
    zlib.pc: 5e60c1b132813bdcd04706c03dcb8f99

Also, you could add a hook to run `conan get` after to package.

But maybe we could customize the number of files listed when packaging by an environment variable. WDYT @memsharded ?

related issue: https://github.com/conan-io/conan/issues/4479

Regards!

**Comment by sigiesec** [comment]
Hi @uilianries, thanks for the suggestion, however this is missing a critical information, namely which call of copy caused the particular files to be copied, i.e. in particular the values of the pattern and src parameters. This is particularly hard to debug if something is wrong.

**Comment by memsharded** [comment]
Implemented in #15513 for next 2.1 release
