### ISSUE TITLE
Usage of Run Environment in CMake helper

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#4691]
## Setup
0. Conan 1.12.3
1. I'm packaging compiler as a conan package and I set `cpp_info.bindirs` and `cpp_info.libdirs`. (`env_info.CC` and `env_info.CXX` are defined as well)
2. Compiler is defined in `[build_requires]` of profile
3. I expect them to be set in cross-platform manner when I build a package using it.
4. The package itself uses `CMake` build helper in quite straight-forward way: `cmake = CMake(self); cmake.configure()`

## Expected outcome
Package builds

## Actual outcome
I get an error:
```
"/home/builduser/.conan/data/gcc_installer/6.3.1/external/master/package/0fed1935a551cd37f1f9a4a80b3168468b52cfed/bin/gcc"
  is not able to compile a simple test program.
    /home/builduser/.conan/data/gcc_installer/6.3.1/external/master/package/0fed1935a551cd37f1f9a4a80b3168468b52cfed/bin/../libexec/gcc/x86_64-redhat-linux/6.3.1/as: error while loading shared libraries: libopcodes-2.27-12.el7.1.so: cannot open shared object file: No such file or directory
```

I suspect this is because `LD_LIBRARY_PATH` is set incorrectly. If I do `conan install gcc_installer/6.3.1@external/master -g virtualrunenv` first and then source `activate_run.sh` everything works.

I see that `ConanFIle.run()` method accepts `run_environment=False` which I really wanted to rely upon, however `CMake` helper calls it without any parameters.

I also wonder whether it's possible to make this less intrusive? I such case I don't want to update every recipe but rather control it somehow via profile.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Johnnyxy** [comment]
Hi there,
to execute the CMake build helper in a specific environment you can do it like it is written in the [docs](https://docs.conan.io/en/latest/reference/build_helpers/run_environment.html#runenvironment). Then the LD_LIBRARY_PATH etc. should be set correctly as the table in the docs describe it.

```python
def build(self):
    env_build = RunEnvironment(self)
    with tools.environment_append(env_build.vars):
        cmake.configure()
        ....
```

**Comment by ytimenkov** [comment]
I know, however there are 2 problems:
1) I want to be less intrusive
2) `run(..., run_environment=True)` does little more than just setting `LD_LIBRARY_PATH` on MacOS

**Comment by Johnnyxy** [comment]
hm, yea, MacOS is a special flake in this regard.
The ```run_environment=True``` functionality has not been "backported" to the ```RunEnvironment```.

**Comment by aleksa2808** [comment]
I stumbled upon this issue while using a protobuf package with a bundled protoc binary which gets called by consumer CMake invocations. I agree that it is painful to use the verbose RunEnvironment approach in every package that uses dependencies like these (I even have to use it twice in every package, for cmake.build and cmake.install) and am also searching for a better solution!

**Comment by klimkin** [comment]
Looking into `conans/client/build/cmake.py`:
~~~python
    def _run(self, command):
        with context:
            self._conanfile.run(command)
~~~

Is there a good reason not to use `run_environment=True`?

https://github.com/conan-io/conan-center-index/issues/4920

**Comment by memsharded** [comment]
This issue refers to legacy generators, superseded by ``VirtualRunEnv``, closing as outdated
