### ISSUE TITLE
Package ABI Compatibility default mode.

### ISSUE THREAD

**Issue by dobrypd** [conan-io/conan#4693]
To help us debug your issue please explain:

Conan version: all
Platform: irrelevant

I would like to be able to change default mode from `semver_mode()` to `full_package_mode()`. [(link to docs)](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#versioning-schema)
(Idea) It could be done in profile.

Problems:
1. There is an assumption in `conan` that change of option doesn't change ABI.
2. More general: I would prefer to say which packages are stable enough to be used with semver rather than other way around.

Example:
4 conan recipes: `app`, `lib1`, `lib2`, `lib3`.
We have diamond: `app` depends on `lib1` and `lib2`. Both `lib1` and `lib2` depends on `lib3`. Only `lib1` depends on `lib3` with `full_package_mode()`.
Package `lib3` has option `danger` (boolean).

There are 5 packages in `conan` cache (versions/channels/users are irrelevant):

1. `lib1/1.0@me/testing` with `lib3:danger=True`
2. `lib1/1.0@me/testing` with `lib3:danger=False`
3. `lib2/2.0@me/testing` with `lib3:danger=False`
4.  `lib3/3.0@me/testing` with `lib3:danger=True`
5.  `lib3/3.0@me/testing` with `lib3:danger=False`

`conan create app 1.0@me/testing -o lib3:danger=True` will success.

Conan will assume ABI compatibility, and won't require to rebuild `lib2` if we want to create app with option `lib3:danger==True`.

Workarounds:
* `full_package_mode()` everywhere, 
* configure all options of all dependencies in upstream (do not assume default options)
** by propagating options, (`self.options['lib3'].danger = self.options.danger`)
** by setting by hard, (`self.options['lib3'].danger = False`)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @dobrypd 

We are about to provide an experimental feature to do exactly this, in Conan 1.13 (to be released today or tomorrow)

You will be able to specify in ``conan.conf`` a ``default_package_id_mode`` to change the conan default behavior.

The documentation will be here (https://github.com/conan-io/docs/pull/1106, not yet WIP).

We didn't think about defining it in a profile, but please do test it when it is published and give feedback if you still think it would be better. Thanks!

**Comment by dobrypd** [comment]
Hi @memsharded !

Wow, that is fast and good news! :)
Thanks, I will experiment with it.

**Comment by dobrypd** [comment]
It works great.
For me the `conan.conf` is good place to have that option.

I think this issue can be closed.

**Comment by memsharded** [comment]
Ok, great, thanks for the feedback!

Closing the issue, do not hesitate to open a new one for further feedback if you encounter any issue with this new feature. Cheers!
