### ISSUE TITLE
[question] Slashes in recipe reference user

### ISSUE THREAD

**Issue by ciferkey** [conan-io/conan#4695]
Conan 1.12.2 on Linux.

I'm using conan upload to upload a package into Artifactory. Given a package recipe reference of package/version@user/channel the package is stored in the Artifactory path of user/package/version/channel.

I use a convention in Artifatory where the first part of the path detonates a name space and that name space usually contains slashes (eg "com/example/a"). If I wanted to replicate this in conan I would need the user field to be this namespace. However the upload commands fails when there are slashes in the user:
ERROR: Invalid parameter 'package/version@com/example/a/channel', specify the full reference or user/channel. 

I'm guessing this is because recipe references use slashes to separate the different parts so including slashes in the user disruptions this.

Is there any way to create the name spacing that I want when using conan?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @ciferkey 

I am afraid that it is not possible. Conan uses the slash everywhere to separate pkg-version-user-channel fields, both in the client and different servers, including Artifactory and Bintray. It is basically impossible to change that.

The only possible option I see is using a different separator for your channel or user. There are users using the dot "." for similar purposes.

**Comment by memsharded** [comment]
I have re-checked this issue, and yes, it is basically impossible.
Conan uses the filesystem thoroughly (the conan local cache) to store packages. The only possible way to have a coherent and tractable cache layout is to use path separator (slash) to separate the different fields (name, version, user, channel), so this feature won't be possible, so I am closing this issue. Cheers.
