### ISSUE TITLE
`--build <pattern>` seems not to work

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4696]
When calling `conan help install` it states the following regarding the --build parameter:

```
--build=[pattern] Build always these packages from source, but never build the others. [...] 'pattern' is a fnmatch file pattern of a package name.
```

I would like to install a package and rebuild all of my own packages with it. All of my packages are within the `@monsdar/release` channel. The following seems not to work though: `conan install ... --build *monsdar*`. Conan gives me the message `ERROR: No package matching '*monsdar*' pattern`.

Do I do something wrong? Or is this feature not working correctly?

This happens with Conan 1.13.0 installed via Pip. Python 3.6.1 on a Windows 10 Professional with 64bit.

**Comment by monsdar** [comment]
Just found a very good usecase for this: When working locally and using `conan link` to use local packages I could use the wildcard to only include a rebuild of my own packages, but not rebuild everything that's coming from the Conan Cache.

Let's say I'm working on the packages `foo` and `bar`. Both are dependencies of my 3rd package called `MyFoobar`. I'd do local changes to `foo/2.0.0@monsdar/release` and `bar/2.0.0@monsdar/release`, then use `conan link` to build `MyFoobar` with those packages. I could trigger a rebuild of `MyFoobar` using the new versions of `foo` and `bar` by doing the following: `conan build ../MyFoobar --build=*monsdar/release`.

**Comment by monsdar** [comment]
Note: Just saw what I was originally looking is already there but not working... So I rewrote this issue.

**Comment by Johnnyxy** [comment]
I think you forgot the equals sign.

The parameter should look like this:
```bat
conan install ... --build="*monsdar*"
```

Quotes are optional.

**Comment by monsdar** [comment]
Does this work for you then? In my case the following does not work:
* conan install ... --build *monsdar*
* conan install ... --build=*monsdar*
* conan install ... --build "*monsdar*"
* conan install ... --build="*monsdar*"
* conan install ... --build '*monsdar*'
* conan install ... --build='*monsdar*'

**Comment by Johnnyxy** [comment]
Sorry, my mistake I have been testing it with package names instead of package references.
The ```build=_pattern_``` only works with package names e.g. ```boost```, ```boost*```, ... not ```boost/1.69.0@test/testing``` or ```*@test/*```.

As the [documentation](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#conan-install) states for the ```conan install``` command:

> 'pattern' is a fnmatch file pattern of a package name.

**Comment by uilianries** [comment]
And what happen when a package has the name `monsdar` but also there are packages using `monsdar` as namespace? For example:

    monsdar/1.0.0@company/stable
    foobar/0.1.0@monsdar/stable

The [Build Mode](https://github.com/conan-io/conan/blob/b3856467cab48aaf8aa873221d8b4c1bbd232917/conans/client/graph/build_mode.py#L6) can accept full reference, partial package name or regular modes (build, outdated,..). You could add the full reference multiple times, I know this is annoying when you have dozen of packages, but the namespace is not part of package id. 

@memsharded Should we support namespace as build mode, like `--build "*@user/channel"` ?

**Comment by Johnnyxy** [comment]
Then I will correct my answer regarding the full reference.

Specifying full references works according to the _source code_. :)

**Comment by uilianries** [comment]
If it's not working, it's a possible counter feature, not a bug :joy: :bug:

**Comment by monsdar** [comment]
@uilianries: In case my pattern matches multiple types of packages I'd need to define my pattern better. An working example for that could be the following: 
* `conan install ... --build */*@monsdar/release`
* `conan install ... --build */*@monsdar/`
* `conan install ... --build *@monsdar`

I can see that this could a a valid usecase. Having a way to define the build-packages like that would make life much easier.

**Comment by uilianries** [comment]
Well I see no limitation on implement this and I think you are not the first one who requests such feature. @memsharded @lasote WDYT ?
