### ISSUE TITLE
[python_requires] Experimental status

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4697]
Currently `python_requires()` is marked as experimental within [the docs](https://docs.conan.io/en/latest/extending/python_requires.html). I'd like to use it, but I'm afraid it will break compatibility to newer Conan versions when something changes in the future.

I searched the issues in here and it looks like there are some problems that _could_ potentially lead to a change to `python_requires`.

I'd like to know about the current state of `python_requires` and if you could give some information about its experimental status.

**Comment by danimtb** [comment]
Hi!

Yes, the status is still very experimental. The feature has proven useful but there are still some pending issues regarding inheritance and behavior of ``exports`` and ``export_sources`` to share files via python_requires.

Although all of the current investigations lead to changing the way you declare python require inside a *conanfile.py* to fix some issues, we could say at this moment that we are not going to discontinue the feature

**Comment by monsdar** [comment]
Understood. So it will not be removed, but it's likely that there'll be breaking changes in the future.

**Comment by danimtb** [comment]
Yes, that could be a goos summary 😄

**Comment by danimtb** [comment]
Closing this as the question was answered. Feel free to comment or ask anything related. Thanks 😄
