### ISSUE TITLE
502 Bad Gateway Error when uploading Packages

### ISSUE THREAD

**Issue by alaingalvan** [conan-io/conan#470]
![conanerror](https://cloud.githubusercontent.com/assets/2251123/18338272/75fc8d24-7565-11e6-804c-a99918daa3cb.PNG)

I'm trying to upload some Vulkan packages but I keep running into "502 Bad Gateway" errors. Is the service down?

Here are the packages I'm trying to upload:

- [Vulkan.hpp](https://github.com/alaingalvan/conan-vulkan-hpp)
- [Vulkan Loader and Validation Layers](https://github.com/alaingalvan/conan-vulkan-loaderandvalidationlayers)
- [Vulkan SDK](https://github.com/alaingalvan/conan-vulkan-sdk)

**Comment by memsharded** [comment]
Hi @alaingalvan,
Thanks for reporting, yes, it is a sysadmin issue, we are currently investigating.

**Comment by memsharded** [comment]
Servers are up again, thanks for reporting, please re-open if necessary.
