### ISSUE TITLE
Editable packages layout docs: placeholder brace usage wrong

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#4701]
The docs use a single brace to enclose placeholders but the actual usage is double braces.

The documentation for workspaces also has this flaw.

**Comment by jgsogo** [comment]
Yes, you are right, Conan v1.13 was released and the docs weren't available at that moment. Now docs have been updated and match v1.13 release.

Sorry for the inconvenience.

**Comment by jgsogo** [comment]
Nevertheless, there was a flaw in the updated docs, fixing it: https://github.com/conan-io/docs/pull/1110

Thanks!

**Comment by jgsogo** [comment]
I'm closing this issue, I've reviewed the docs (quick) and everything seems to fit the implementation. Please, open it again if you see something that doesn't match it.
