### ISSUE TITLE
conan export from git repo

### ISSUE THREAD

**Issue by CAMOBAP795** [conan-io/conan#4704]
It will be nice if conan out of box allow export from git repository like this:
 - `conan export https://github.com/bincrafters/conan-protobuf/blob/testing/3.3.0/conanfile.py` OR
 - `conan export --repo bincrafters/conan-protobuf --branch testing/3.3.0`

I sure that someone asked this (or similar) question before, but I didn't managed to find it(

-----
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SSE4** [comment]
@conan-io/barbarians is it something that could be done as conan hook, e.g. `pre_export`?

**Comment by CAMOBAP795** [comment]
According to https://github.com/bincrafters/conan-protobuf/pull/34#issuecomment-471282710 it's not implemented yet, IDK is it really important, because I solved this problem with `git submodules`

So I will close this one
