### ISSUE TITLE
virtualrunenv cmake_multi

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#4705]
Hello,

I'm using conan on windows and in order to manage my shared libraries(dlls) I'm using virtualrunenv.
I have two use cases:

1.  For single configuration environment:
- conan install ..  -s arch=x86 -s build_type=Release
- conan build ..
- .\activate_run.bat
- ctest  -T Test
**==> this works as charm**
 

2.  For multi configuration environment it is more tricky, if I want to use visual studio to build both debug and release.
- conan install ..  -s arch=x86 -s build_type=Release -g cmake_multi
- conan install ..  -s arch=x86 -s build_type=Debug -g cmake_multi
- conan build ..
- .\activate_run.bat
- ctest  -T Test -C Debug 
- ctest  -T Test -C Release --> **This does not work**

The ctest for release configuration cannot find required dlls because the second install command `conan install ..  -s arch=x86 -s build_type=Debug` override the activate_run script

_Is there any solution for this ?_ 

My second related issue:
I have a script that set my PATH and start visual studio, something like:

```
call  .\activate_run.bat
start MySolution.sln
```

Now I can run my test in the IDE, however only for one configuration, whenever I want to switch between debug to release, I have to:

- Close my IDE
- Run conan install ...... to update the activate_run script 
- Start the IDE again using my script

Is there a better alternative for this ? 

Thanks in advance.

**Comment by lasote** [comment]
Have you tried to call the activate after each `conan install` invocation? Probably the PATH value will be appended with the debug and the release. If the debug/release shared libraries don't collide in the name you will be good.

**Comment by boussaffawalid** [comment]
I tried that already and it works but it is not so practical as I cannot use the activate_run in my start ife script, what I did as a work around is to create a custom conan generator similar to cmake multi which create multiple activate_run: activate_run_release, activate_run_debug ...

But I was wondering if there is better solution.
Thanks

**Comment by lasote** [comment]
No, there is no other solution for that.

**Comment by joaquin-herrero** [comment]
> I tried that already and it works but it is not so practical as I cannot use the activate_run in my start ife script, what I did as a work around is to create a custom conan generator similar to cmake multi which create multiple activate_run: activate_run_release, activate_run_debug ...
> 
> But I was wondering if there is better solution.
> Thanks

Hi @boussaffawalid, I need to do a custom generator similiar to the one you did to fix working with shared libs on a workspace. Please, can you share it with us to take a look?

Thanks

**Comment by boussaffawalid** [comment]
At the end we decided to use the new cmake feature VS_DEBUGGER_ENVIRONMENT https://cmake.org/cmake/help/git-stage/prop_tgt/VS_DEBUGGER_ENVIRONMENT.html. (we use visual studio as an IDE)

We set the cmake property for every target as bellow.

```
add_executable(my_target *.cpp)
set_target_properties(my_target PROPERTIES VS_DEBUGGER_ENVIRONMENT"PATH=$<$<CONFIG:DEBUG>:${CONAN_BIN_DIRS_DEBUG}> $<$<CONFIG:RELEASE>:${CONAN_BIN_DIRS_RELEASE}>;%PATH%")
```

and we created a wrapper function for add_executable to avoid setting this property for every target separately.

**Comment by boussaffawalid** [comment]
> > I tried that already and it works but it is not so practical as I cannot use the activate_run in my start ife script, what I did as a work around is to create a custom conan generator similar to cmake multi which create multiple activate_run: activate_run_release, activate_run_debug ...
> > But I was wondering if there is better solution.
> > Thanks
> 
> Hi @boussaffawalid, I need to do a custom generator similiar to the one you did to fix working with shared libs on a workspace. Please, can you share it with us to take a look?
> 
> Thanks

**Comment by memsharded** [comment]
both ``cmake_multi`` and ``virtualrunenv`` have been deprecated some time ago in 1.X in favor of ``VirtualBuildEnv`` and ``CMakeToolchain/CMakeDeps``, and completely removed in 2.0, so closing this as outdated.
