### ISSUE TITLE
Local workflow issue with exporting to local cache - build and export-pkg

### ISSUE THREAD

**Issue by trondhe** [conan-io/conan#4710]
I am trying to figure out a way to change code, build and export to the local cache without having to push to git and then call the source method.

On Windows my CMakeLists.txt file looks like this:
```
cmake_minimum_required(VERSION 3.9 FATAL_ERROR)
project(myproj CXX)
include(GNUInstallDirs)
add_library(${PROJECT_NAME})
target_sources(${PROJECT_NAME} PRIVATE myproj.cpp)

target_include_directories(${PROJECT_NAME} 
    PUBLIC 
        $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>
)

###############################################
# Installation

# Headers
install(DIRECTORY ${PROJECT_SOURCE_DIR}/include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})

# Lib
install(TARGETS ${PROJECT_NAME}
EXPORT ${PROJECT_NAME}-target
ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

# Config.cmake
set(INSTALL_CONFIGDIR ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME})
install(EXPORT ${PROJECT_NAME}-target
    FILE ${PROJECT_NAME}Config.cmake
    DESTINATION ${INSTALL_CONFIGDIR}
)
```
and my conanfile.py looks like this:
```
from conans import ConanFile, CMake, tools
import os
from distutils.dir_util import copy_tree

class ConanRecipe(ConanFile):
    name = "myproj"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "cmake_find_package"

    def source(self):
        source = "/path/to/myproj"
        destination = os.getcwd()
        copy_tree(source, destination)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = [self.name]

```
The source method is like that just to test the `conan create` command locally without having to push and clone any repo.
Running `conan create . user/channel` from my project folder i get what I expect.
Under `.conan/data/myproj/1.0.0/user/channel` I get my sources as expected under sources. The build folder contains the hash folder then all the build files, and the package folder contains the hash folder which then contains the include folder, lib folder, conaninfo.txt and conanmanifest.txt. All working and is as expected.

Following the guide at https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html#conan-install it says I could do the same thing just without having to pushing to git and cloning it back down again by running the following commands:
```
conan install . -if=./build
conan build . -sf=. -bf=./build
conan export-pkg . user/channel -sf=. -bf=./build -f
```
The `conan install` and `conan build` command works as expected. But when I run the `conan export-pkg ...` command it runs the package method and installs myproj to `<projectFolder>/build/package` while conaninfo.txt and conanmanifest.txt is exported to `.conan/data/myproj/1.0.0/user/channel/package/<hash>/`. Why isnt my includes and lib in this folder in the local cache aswell?

Am I missing something, isnt `conan create ...` just an collection of these subcommands? Anything I've forgot to specify in the command line, or any conanfile.py attributes that is missing?
Again, everything works as expected with conan create.

**Comment by lasote** [comment]
Hi, the `conan create` is not the same as calling the local methods, for example, it copies from the source folder to the build folder everything when a package is going to be built.
In your concrete scenario, I don't know exactly what could be happening. Try to print some paths in the CMakeLists.txt to see for example where is pointing the `${PROJECT_SOURCE_DIR}` and if cmake is generating/copying to the wrong place.

As a general recommendation maybe it is interesting for you the "editable packages" feature: https://docs.conan.io/en/latest/developing_packages/editable_packages.html
With that feature, basically you describe where are your artifacts (layout) and the package acts like it is in the local cache.

**Comment by trondhe** [comment]
Ill take a look at that. I am replacing the build system for a rather large codebase and that might be preferable.

But when it comes to printing cmake variables, `CMAKE_INSTALL_PREFIX` is set as myproj/build/package as expected. As `conan export-pkg` anyways actually adds the conaninfo.txt and conanmanifest.txt to the correct place in my cache it should be able to override the install prefix somehow, if it has to be done configure time, why isnt running that again a good solution?

**Comment by lasote** [comment]
What about the `PROJECT_SOURCE_DIR` var? is set to the sources?
A new configure is not necessary.

**Comment by trondhe** [comment]
PROJECT_SOURCE_DIR is set to `path/to/myproj`

**Comment by trondhe** [comment]
Another way which could solve my problem is a source override specifier which could look something like `conan create . user/channel -sf=/path/to/myproj`.
Isn't this a very normal workflow, To update and test a dependency locally without having to do anything unnecessary. As I really do not want to push to VCS before I know it builds fully and is working as a requirement before that happens.

**Comment by trondhe** [comment]
The error stems from how I expected export-pkg to work.
My understanding is that is was going to use my local folder as source to *both* builld and package my project in the local cache, `.conan/data/myproj/1.0.0/user/channel/package/<hash>/`, but this is wrong.
So to get cmake to install the package in the local cache folder it just needs another configure call, as that will change the CMAKE_INSTALL_PREFIX path. So modify the package method to
```
def package(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.install()
```

This will enable local workflow by using
```
conan install . -if=build
conan build . -sf=. -bf=build
conan export-pkg . user/channel -sf=. -bf=build -f
```
