### ISSUE TITLE
Allow inspecting first-level requirements of a package without finding each recipe

### ISSUE THREAD

**Issue by ikoruk** [conan-io/conan#4711]
Conan version 1.13.0
Mac OS Mojave
Python 3.7.2

In earlier versions of conan I had no problems but now if I call `conan_api.install()` with a conan recipe that has `python_requires` (in global space) it now thinks it's within local space and so triggers an exception. If I call the same through the command line it works. Am I doing something wrong or is this an overly aggressive exception?

```
Traceback (most recent call last):
  File ".../conans/client/loader.py", line 254, in _parse_conanfile
    loaded = imp.load_source(module_id, conan_file_path)
  File ".../imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../conanfile.py", line 3, in <module>
    common = python_requires('recipe/version@user/channel')
  File ".../conans/client/graph/python_requires.py", line 57, in __call__
    raise ConanException("Invalid use of python_requires(%s)" % require)
conans.errors.ConanException: Invalid use of python_requires(recipe/version@user/channel)
```

**Comment by lasote** [comment]
I'm not sure what is failing. Maybe you could check the differences between your call to the python api and the call from the `command.py`.
By the way, we discourage the usage of the python api, it is not documented and it is not stable.

**Comment by ikoruk** [comment]
The reason I need it is because I need to list the requirements of a package when I don't have access to a local server, and `conan info` fails when a requirement is not yet exported and the server is inaccessible.

**Comment by lasote** [comment]
But if the requirements cannot be resolved you cannot compute the graph and know the dependencies.
What about `conan inspect` command?

**Comment by ikoruk** [comment]
`conan inspect` doesn't list requirements. If I could at least list or export the first level dependencies then I can know which dependencies I need to export, and then run it again for second level and so on.

**Comment by ikoruk** [comment]
I found the issue, I had an earlier call to `ConanPythonRequire` which I needed for `ConanPythonRequire`. After the loader, I need to set `python_requires.valid = True`. Then the `conan_api.install` works fine afterwards.

**Comment by ikoruk** [comment]
The issue actually seems to be more related to not being able to get requirements without a recipe existing and the `python_requires` bug is more related to using `ConanFileLoader` directly from `conans` before the `conan install` call.
So instead of a bug report, I would classify this as more of a feature request to be able to list first level requirements (i.e. using `conan inspect`) without needing to resolve the whole tree.

**Comment by lasote** [comment]
Could you please close this one and open a new one? It would simplify the request.
