### ISSUE TITLE
[revisions] conan install needs --update when installing a specific RREV

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#4712]
Having a recipe exported with RREV1, I'd like to install a different RREV from the server so I thought doing will be enough but it is not:

```
(py37-conan) λ conan install IrrXML/1.2@user/channel#681d7e590d2da0a164166f737a49cf32c735ee6c -r conan-local
ERROR: The recipe in the local cache doesn't match the specified revision. Use '--update' to check in the remote.
```

I need to use ``--update``. Maybe this was already discussed but I am not sure about the behavior. 

Maybe it was done that way so the command without the ``--update`` means: Bring me the binary for this RREV that **could not be the latest in other server**" ?

I think that could be also possible with just a ``conan install IrrXML/1.2@user/channel -r remote``, meaning that it will look for existing packages for your specific revision installed.

Please share your thouthgs and point any missing piece @conan-io/barbarians. Thanks!

**Comment by ericriff** [comment]
I'm having the same issue. Is this going to stay like this?

**Comment by memsharded** [comment]
This is no longer an issue, for sure in 2.0 it is solved.
