### ISSUE TITLE
Allow inspecting first-level requirements of a package without finding each recipe

### ISSUE THREAD

**Issue by ikoruk** [conan-io/conan#4717]
Our team sometimes needs to build packages locally without access to our conan recipe server. In order to do that automatically, we would like to be able to list the first level requirements of a package even when the remote server is not accessible and so the full graph can't be built.

Maybe `conan inspect` can be augmented to be able to list first level requirements, or allow `conan info --only=requires` to not fail in the case the recipe can't be found.

**Comment by jgsogo** [comment]
I'm not sure we can implement this without compromising other use cases. For example, when there are some conditionals depending on a python_requires we need to resolve it before trying to access the requirements lists, or we need to detect conflicts (or a version range) between versions to determine which one is the actual requirement, so building the graph may be mandatory.

```python
base = python_requires("...")

class MyLib(ConanFile):

    def requirements(self):
        self.requires("zlib/[>=1.2.8]@user/channel")
        if base.detect_x(...):
            self.requires("....")
        else:
            self.requires("...a different lib")
```

**Comment by memsharded** [comment]
Hi @ikoruk 

> Our team sometimes needs to build packages locally without access to our conan recipe server. In order to do that automatically, we would like to be able to list the first level requirements of a package even when the remote server is not accessible and so the full graph can't be built.

I don't fully understand the use case. If you don't have access to the server, you won't be able to build the package, even if you are able to list its direct requirements. Could you please clarify this? Thanks!

**Comment by ikoruk** [comment]
Even if we don't have access to the server, we still have access to the recipe source which we can then export locally. If I could list direct requirements I could get the info of which packages need to be exported along with their expected user and channel which I would need for the export.

**Comment by memsharded** [comment]
That is the thing, I don't see it much more painful to do a ``conan install``, having it fail and tell which package recipe is missing, then you go to the recipe source, and repeat. 

We could add ``requires`` class attribute to the ``inspect`` output, but that will still not help in the case of conditional ``requirements()`` method, because the graph needs evaluation. ``conan info`` also works computing the dependency graph, it would be extremely complicated to change that. What you suggest would only slightly alleviate the case of A->(B, C, D)->(E, F, ...), but the case A->B->C->D, the process would be exactly the same if using ``conan install`` and failing. So I'd say this would be too much complexity for the value.

**Comment by ikoruk** [comment]
The thing is it takes quite a while for `conan install` to fail since it tries for a while to connect to the server so that would take a very long time if it needed to run in a loop. But if it's too complex to add, I understand.

In case someone stumbles upon this issue, the way I solved it eventually was with this hacky python snippet (which I know can break at any time):

```
    resolver = RangeResolver(cache, conan_api._proxy)
    python_requires = ConanPythonRequire(conan_api._proxy, resolver)
    loader = ConanFileLoader(conan_api._runner, conan_api._user_io.out, python_requires)
    conanfile_object = loader.load_consumer(conanfile_path, profile)
    python_requires._requires = []
    python_requires.valid = True
    if hasattr(conanfile_object, "requirements"):
        conanfile_object.requirements()
    return conanfile_object.requires
```

**Comment by jgsogo** [comment]
Hi @ikoruk, hope you understand that we cannot implement it for the general use case as it will be broken when there are conditional requirements, and it is something we cannot bypass, we need to build the graph.

I'm closing the issue for now. Thanks!
