### ISSUE TITLE
Conan doesn't print coloured output in Gitlab CI

### ISSUE THREAD

**Issue by hebaishi** [conan-io/conan#4718]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Using Conan v1.11.2 on `lasote/conangcc7` and Windows 10, we don't get coloured output in our Gitlab CI build jobs. We have even tried setting the `CONAN_COLOR_DISPLAY` variable to 1, and it still doesn't work.

**Comment by jgsogo** [comment]
Hi @hebaishi! Is it just for that combination of version/docker/os? I'm not sure if we have ever had colours inside docker...

PS.- Use conanio images instead: https://hub.docker.com/u/conanio

Thanks!

**Comment by hebaishi** [comment]
Hi @jgsogo! No, we have the same issue on Windows, too. I'm happy to change docker images, but when I run conan inside that docker image locally, I __do__ get coloured output.

**Comment by jgsogo** [comment]
So, it is not only in docker images running on Windows, but in Windows itself too? Are you running any special console? did you installed Conan with pip or with an installer?

**Comment by hebaishi** [comment]
No, sorry I should have been more clear:
`lasote/conangcc7`: colours work locally, but not using docker-runner of Gitlab CI
`conanio/gcc7-x86`: colours work locally, not tested using docker-runner of Gitlab CI
Windows: colours work locally using the normal command prompt, but not using shell runner in Gitlab CI

**Comment by hebaishi** [comment]
We installed conan using pip on both platforms.

**Comment by memsharded** [comment]
Hi @hebaishi 

I think this is very common in CI systems.

Colors only work when there is a tty-like output that can understand that coloring (escape characters). CI systems are typically not that tty-like, and thus, no colors are output. Same happens with travis-ci and appveyor (even if not using docker) in our own builds too:

- https://travis-ci.org/conan-community/conan-zlib/jobs/503493520
- https://ci.appveyor.com/project/ConanCIintegration/conan-zlib/build/job/rbqgkc0yvijpvf78

So I am afraid this is not related to Conan, nothing that Conan could fix.

**Comment by hebaishi** [comment]
Yea that's a real shame. My only issue with that is that in our own CI builds, I can do this and it works:
```python
from colorama import Fore
print(Fore.RED + 'ERROR!')
```
I'm not sure if that would work on Travis CI or Appveyor CI, but on Gitlab CI, it definitely works.

**Comment by memsharded** [comment]
Is that working inside a docker image running inside Gitlab?
If that is the case, I have no idea why setting CONAN_COLOR_DISPLAY wont work too, that would need further investigation.

**Comment by hebaishi** [comment]
Yes, it works perfectly inside a docker image running inside Gitlab. The code snippet I showed above prints coloured text in the Gitlab CI build log.

**Comment by hebaishi** [comment]
Also, just done a quick test using travis CI, and I get coloured output there too. The build log is [here](https://travis-ci.org/hebaishi/travis-colour-test/jobs/505682915)

**Comment by uilianries** [comment]
Hi @hebaishi !

I used Gitlab CI + Conan for some time, but I don't remember about any problem related to terminal colors. But I think your problem is not caused by Conan, but it's from Gitlab CI. Did you try contact Gitlab Community? I found some related issues there:

https://gitlab.com/gitlab-org/gitlab-runner/issues/3238#note_131739850
https://docs.gitlab.com/runner/faq/#my-gitlab-runner-is-on-windows-how-can-i-get-colored-output-on-the-web-terminal

**Comment by hebaishi** [comment]
@uilianries I don't think this is a Gitlab CI problem, because as I said, I can write a small python script that prints coloured output without any problems. Also, the same goes for Travis CI. The fact that one python script can display coloured output, and conan (which is a python application) can't means that this is definitely not a CI issue.

**Comment by jgsogo** [comment]
Hi @hebaishi 

We can try some python snippet to know what happen in your CI, I'll try to reproduce here all the checks that Conan does and the print itself, I hope that with the output we can trace the problem:

```python
import os
import sys
from conans.util.env_reader import get_env
import colorama
from colorama import Fore, Style

print("CONAN_COLOR_DISPLAY" in os.environ)
print(get_env("CONAN_COLOR_DISPLAY", 1))
print(get_env("PYCHARM_HOSTED"))

if get_env("PYCHARM_HOSTED"):  # in PyCharm disable convert/strip
    colorama.init(convert=False, strip=False)
else:
    colorama.init()

data = "message"
data = "%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL)

sys.stdout.write(data)
sys.stdout.flush()
```

If you can run it in your CI, with the output of this script we may find a workaround/solution.

Thanks!

**Comment by hebaishi** [comment]
Hi @jgsogo! Thank you so much for your help!

So, running it in Gitlab CI, using Gitlab's docker runner, with `lasote/conangcc7` I get

![image](https://user-images.githubusercontent.com/5178138/54385207-fec27280-468d-11e9-92cf-01242c507ed9.png)

**Comment by uilianries** [comment]
@hebaishi consider user `conanio` images. ALL lasote's images are deprecated.

To download a image for gcc7 you could try `conanio/gcc7`

**Comment by hebaishi** [comment]
Ran the same test on travis CI, and also added a little dummy recipe to see conan in action. It actually works perfectly, even without using the CONAN_COLOR_DISPLAY variable. You can see it [here](https://travis-ci.org/hebaishi/travis-colour-test/builds/506447890)

**Comment by hebaishi** [comment]
Also tested using Gitlab's 'shell' runner on our Windows VMs, and the output is exactly the same as above. And performed the test with the `conanio/gcc7` image, and the result is the same again.

**Comment by hebaishi** [comment]
It seems that for whatever reason, on our Gitlab CI, this works:
```python
print(Fore.RED + 'Error')
```
but this doesn't:
```python
sys.stdout.write(Fore.RED + 'Error')
sys.stdout.flush()
```

**Comment by hebaishi** [comment]
Please let me know if there are any more tests you would like me to run. :+1:

**Comment by jgsogo** [comment]
It looks like we are really close to something. By default [`print` function uses `sys.stdout`](https://docs.python.org/3/library/functions.html#print), so if you have tested the script using `print` instead of `sys.stdout` and it outputs colors, then it means that in Gitlab CI something is different.

I need to double check, so `sys.stdout.write("%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL))` doesn't print with colors and `print("%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL))` does? :anguished:

**Comment by hebaishi** [comment]
Ok, so with this script:
```python
import os
import sys
from conans.util.env_reader import get_env
import colorama
from colorama import Fore, Style

print(Fore.RED + 'Error')

print("CONAN_COLOR_DISPLAY" in os.environ)
print(get_env("CONAN_COLOR_DISPLAY", 1))
print(get_env("PYCHARM_HOSTED"))

if get_env("PYCHARM_HOSTED"):  # in PyCharm disable convert/strip
    colorama.init(convert=False, strip=False)
else:
    colorama.init()

data = "message"
data = "%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL)

sys.stdout.write(data)
sys.stdout.flush()

sys.stdout.write("%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL))
print("%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL))
print(Fore.RED + 'Error')
```
we get:
![image](https://user-images.githubusercontent.com/5178138/54391203-1c96d400-469c-11e9-95b8-c977f3c10176.png)

But with this one:
```python
import os
import sys
from conans.util.env_reader import get_env
import colorama
from colorama import Fore, Style

print("CONAN_COLOR_DISPLAY" in os.environ)
print(get_env("CONAN_COLOR_DISPLAY", 1))
print(get_env("PYCHARM_HOSTED"))

if get_env("PYCHARM_HOSTED"):  # in PyCharm disable convert/strip
    colorama.init(convert=False, strip=False)
else:
    colorama.init()

data = "message"
data = "%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL)

sys.stdout.write(data)
sys.stdout.flush()

sys.stdout.write("%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL))
print("%s%s%s%s" % (Fore.RED, '', data, Style.RESET_ALL))
print(Fore.RED + 'Error')
```
we get:

![image](https://user-images.githubusercontent.com/5178138/54391330-6f708b80-469c-11e9-8b3e-69b534fd2ae3.png)

**Comment by jgsogo** [comment]
I think this is something to share in the Gitlab community, both should behave the same; the standard `print` uses `sys.stdout.write` and Conan is not modifying it... 

If you are going to open an issue there you can simplify even more the script:

```python
import colorama

colorama.init()

# Default color
sys.stdout.write("No color")
print("No color")

# Print colored and reset
data = "color"
sys.stdout.write("%s%s%s" % (colorama.Fore.RED, data, colorama.Style.RESET_ALL))
print("%s%s%s" % (colorama.Fore.GREEN, data, colorama.Style.RESET_ALL))

# Default color
sys.stdout.write("No color")
print("No color")
```

**Comment by hebaishi** [comment]
@jgsogo Thank you so much for your effort. It seems there's some bug in Gitlab runner. I've done some more testing, and it looks like doing `colorama.init()` makes the output that's meant to be coloured appear without colour.

So it seems that while you can get it to produce color, it's not the correct way of using the colorama library.

I will investigate this with the Gitlab community. Thanks again for your help 👍

**Comment by jgsogo** [comment]
This issue might be relevant (although it is 3 years old): https://gitlab.com/gitlab-org/gitlab-runner/issues/332

If you open one issue there, link it here so we can follow it, just in case there is something to fix on our side.

Thanks!

**Comment by hebaishi** [comment]
I have just made yet another discovery. If I simply remove `colorama.init()`, everything works perfectly. Would you consider an environment variable that makes `colorama.init()` optional?

Script used for testing:

```python
import colorama
import sys

# Default color
sys.stdout.write("No color")
print("No color")

# Print colored and reset
data = "color"
sys.stdout.write("%s%s%s" % (colorama.Fore.RED, data, colorama.Style.RESET_ALL))
print("%s%s%s" % (colorama.Fore.GREEN, data, colorama.Style.RESET_ALL))

# Default color
sys.stdout.write("No color")
print("No color")
```

And screenshot to prove it works. Note the outcome is exactly the same on Windows and Linux.
![image](https://user-images.githubusercontent.com/5178138/54395171-f591cf80-46a6-11e9-9a6d-e415d3c13b35.png)

And [here](https://github.com/tartley/colorama) is the explanation for this. The README on colorama's github page says that on Windows, the ANSI codes are converted to Win32 calls, so that explains why you don't see the colours in the CI output. But I still have no idea why the same happens on Linux with the docker runner.

In any case, do you think the Windows situation justifies making colorama init optional? It would be needed to get things working on any CI on Windows I think.

**Comment by hebaishi** [comment]
Just put my theory to the test on our CI, by patching the conan source code and removing the colourama.init calls, and we now have coloured conan output for the first time!

![image](https://user-images.githubusercontent.com/5178138/54398033-73a6a400-46b0-11e9-981e-41814d85c6d1.png)

**Comment by hebaishi** [comment]
In the end, I decided to go with patching colorama. It's a much smaller library, so the patch with be easier to maintain, and it means we can update conan whenever we want without worrying about breaking anything. Still, it would be nice if we had an option in conan to switch this off. Please let me know what you decide either way.

**Comment by jgsogo** [comment]
Quite interesting, thanks for your investigation. I need to share it with the team, we would need to check other CIs and platforms... I'm not sure if we will be able to take care of it soon, good to know that you can manage patching `colorama` library.

**Comment by ytimenkov** [comment]
I've debugged the issue:
When conan calls `colorama.init()` without `strip=False` (as when `PYCHARM_HOSTED` is not set), Colorama does extra internal check when it creates a wrapped stream for `sys.stdout` (as I understand it should handle ANSI -> Win32 console conversion):
```
        # should we strip ANSI sequences from our output?
        if strip is None:
            strip = conversion_supported or (not self.stream.closed and not self.stream.isatty())
        self.strip = strip
```
This essentially undermines Conan's efforts in coloring stream as the output will be stripped.

I think it's reasonable to assume that when user sets `CONAN_COLOR_DISPLAY=1` he/she wants to have ANSI sequences in the output and conan should either bypass colorama or behave as it behaves with `PYCHARM_HOSTED` set.

**I.e. Workaround:** set both `CONAN_COLOR_DISPLAY` and `PYCHARM_HOSTED` on CI to get colors.

**Comment by ytimenkov** [comment]
Unfortunately this kicked my butt: `conan --version` and `conan remote list --raw` became not parser-friendly :disappointed:

**Comment by memsharded** [comment]
Closing this as inactive, also 2.0 have done a new implementation of the CLI output to stderr/stdout, better report against 2.0 if necessary, thanks!

**Comment by johan-boule** [comment]
> Unfortunately this kicked my butt: `conan --version` and `conan remote list --raw` became not parser-friendly 😞

It breaks https://github.com/conan-io/cmake-conan which tries to parse the version.

I think it can be considered a bug. No other program I ever met does color on --version. And that colored --raw output looks suspicious too.
In general, conan abuses colors compared to most other programs.

**Comment by memsharded** [comment]
> It breaks https://github.com/conan-io/cmake-conan which tries to parse the version.

If Conan 2.0 output is breaking the cmake-conan integration, I think it should be better reported in the cmake-conan repo (against the new cmake-conan integraiton using providers: https://github.com/conan-io/cmake-conan/tree/develop2)

I think the ``conan --version`` can drop the color, you are right. 

The ``--raw`` has disappeared in Conan 2.0, this shouldn't be an issue. In any case a command like ``conan remote list`` will  only accept parsing of its json output, the terminal text output is explicitly declared as not stable and can change any time and use any coloring it wants.

**Comment by johan-boule** [comment]
I'm thinking of other commands which should not do color (except on stderr):
- conan config home
- conan config get

There also seems to be a bug with PyCharm within a windows mintty VT100 terminal:
```
$ CONAN_COLOR_DISPLAY=0 PYCHARM_HOSTED=1 conan config home | cat -A
C:\Users\jboule\.conan^M$
^[[0m
```

On linux, the same command does not output the SGR reset sequence ESC + `[0m` at the end.

Since setting `PYCHARM_HOSTED=0` is treated the same as `=1`, the workaround is to do:
```
$ (unset PYCHARM_HOSTED && CONAN_COLOR_DISPLAY=0 conan config home) | cat -A
C:\Users\jboule\.conan^M$
```
No more ESC + `[0m` at the end.
