### ISSUE TITLE
QBS generator cppflags -vs- cxxflags

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4730]
Given the refactor of the `cppflags` variable in https://github.com/conan-io/conan/pull/4716, we realized that we are mixing the meaning of `cppflags` and `cxxflags` variable in the output file. According to the [docs](https://doc.qt.io/qbs/qml-qbsmodules-cpp.html#cppFlags-prop):

![image](https://user-images.githubusercontent.com/1406456/54273048-47423900-4585-11e9-896c-4a27050bfe3e.png)

Now the template for the file content is

```python
        template = ('    Product {{\n'
                    '        name: "{dep}"\n'
                    '        Export {{\n'
                    '            Depends {{ name: "cpp" }}\n'
                    '            cpp.includePaths: [{deps.include_paths}]\n'
                    '            cpp.libraryPaths: [{deps.lib_paths}]\n'
                    '            cpp.systemIncludePaths: [{deps.bin_paths}]\n'
                    '            cpp.dynamicLibraries: [{deps.libs}]\n'
                    '            cpp.defines: [{deps.defines}]\n'
                    '            cpp.cppFlags: [{deps.cxxflags}]\n'  # TODO: cppFlags -> cxxFlags?
                    '            cpp.cFlags: [{deps.cflags}]\n'
                    '            cpp.linkerFlags: [{deps.linkerFlags}]\n'
                    '        }}\n'
                    '    }}\n')
```

we should reassign those `cppFlags` and `cxxFlags`.

**Comment by rweickelt** [comment]
@jgsogo, in Qbs cxxFlags is not recognized by toolchain implementations other than "gcc":

```
/qbs/modules/cpp(master) $ grep -R cxxFlags
CppModule.qbs:    property stringList cxxFlags
CppModule.qbs:        name: "cxxFlags"
CppModule.qbs:    property stringList objcxxFlags
CppModule.qbs:        name: "objcxxFlags"
CppModule.qbs:    property stringList platformObjcxxFlags
GenericGCC.qbs:        validator.addCustomValidator("cxxFlags", cxxFlags, validateFlagsFunction, msg);
GenericGCC.qbs:        validator.addCustomValidator("objcxxFlags", objcxxFlags, validateFlagsFunction, msg);
GenericGCC.qbs:        validator.addCustomValidator("platformObjcxxFlags", platformObjcxxFlags, validateFlagsFunction, msg);
ios-gcc.qbs:    platformObjcxxFlags: base.concat(simulatorObjcFlags)
```

But neither is `cppFlags` This should probably become a ticket in Qbs.

**Comment by jgsogo** [comment]
Qt deprecated `QBS` on October 29th, 2018, so I think they won't pay much attention to new issues 😞  +info: https://wiki.qt.io/Qbs

**Comment by rweickelt** [comment]
I know, but that doesn't mean the project is dead. See https://github.com/qbs/qbs/commits/master for the recent commit history. The Qt Company has always put only a minimum amount of resources to Qbs (1 developer). Shutting that down to 0 doesn't make much difference.

**Comment by rweickelt** [comment]
@jgsogo, I took the courtesy to fix this in the generator.
