### ISSUE TITLE
[question] What is the appropriate way in versioning when dependency changes?

### ISSUE THREAD

**Issue by mcsahin** [conan-io/conan#4735]
Hi,
Our continues integration tool generates a version (major.minor.patch-branch+gitshorthash) and creates conan package when source code is changed from git.

Continues integration tool is using a version.txt file, on a separate git repository (to prevent circular commit, version.txt update) to set new version.
```
conan create conanfile.py libA/1.0.50-master+db11740@user/channel
conan upload libA/1.0.50-master+db11740@user/channel -r my_remote --all
```

"1.0.50-master+db11740" is stored in a separate git repository in version.txt file.

**The problem is; do we have to change version number when dependency of libA is changed?** 

We are changing version number on every commit, so it seems we have to change it when dependency changes. But when we try to change it, we have to do a lot of complex continues integration operations to update version.txt file on separate git repository. 

But without changing version number, isn't it confusing for the user? There should be two packages under "libA/1.0.50-master+db11740@user/channel" and consumer should select a package?

**Comment by jgsogo** [comment]
Hi @mcsahin! From the tool perspective, I don't think we can give you any general recommendation that fits every use case, so it is something you have to analyze on your own and determine which changes in your library motivates a version bump.

----

My recommendation would be to use semantic versioning:
 * change `major` when you break source compatibility
 * change `minor` if there are new features exposed in the library
 * change `patch` for bugfixes and improvements for existing features

(Another part of this is ABI compatibility, if you want to take it into account or not. If you do, then `major` should change whenever you break forward compatibility).

About the second part of your version scheme: `master+db11740` it is something only useful for your developers (consumers of your library do not expect changes if the only difference is here) (also the _branch_ information is contained in the commit itself, so you can remove it), you can use the new feature [package revisions](https://docs.conan.io/en/latest/mastering/revisions.html?highlight=revisions) to get rid of that part: you will get a different recipe/package whenever anything changes in the source code, so maybe you can even get rid of the `version.txt` file you are maintaining. Also, it is worth reading about the [SCM feature](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#scm-attribute) if you already don't know it.

Let me know if this helps you, I will leave this issue open as a `question` for we to talk about it.

**Comment by mcsahin** [comment]
Hi @jgsogo,
Thanks for your fast response.

Firstly, our aim is to automate build and version operations. Mostly our consumers are developers and final consumer only concern about final executable version. So, we are working to automate version operations, every commit should be a version and every dependency change also. We need to do everything by CI (continues integration tool). So, all conan commands are dynamically generated, conanfile.py's uses latest alias tags to manage dependencies.

Here is our single <lib A> (no dependency) project build cycle:
![draw1](https://user-images.githubusercontent.com/11455300/54351937-b9884b80-4661-11e9-8c57-8809387d2439.png)

Here is <lib A> build cycle when <lib B> depends on <lib A>:
![draw2](https://user-images.githubusercontent.com/11455300/54352096-e76d9000-4661-11e9-8e33-9be2a185df8e.png)

The problem is; final build for <lib B> should be on windows and linux at the same time. CI manages this process and updating "version.txt" of <lib B> becomes very complex. Because both linux and windows CI projects can trigger version update. One of windows or linux CI project can fail to build and this can cause an other problem.
So finally, we are stuck on updating version number on dependency changes.



> About the second part of your version scheme: master+db11740 it is something only useful for your developers (consumers of your library do not expect changes if the only difference is here) (also the branch information is contained in the commit itself, so you can remove it), you can use the new feature package revisions to get rid of that part: you will get a different recipe/package whenever anything changes in the source code, so maybe you can even get rid of the version.txt file you are maintaining. Also, it is worth reading about the SCM feature if you already don't know it.
> 
We are using [recipe and sources in the same repo](https://docs.conan.io/en/latest/creating_packages/package_repo.html#package-repo) approch and 
waiting for new artifactory version that supports new [package revisions](https://docs.conan.io/en/latest/mastering/revisions.html?highlight=revisions) feature to test.

**Comment by jgsogo** [comment]
Hi! Artifactory 6.9 has been released and it adds support for Conan package revisions.

Also we are about to start some proofs of concepts related to big C++ projects, CI and how to handle versions and revisions (trying to minimize CI times). I'm sorry for this long silence, but it is hard for us to give advice on something if we cannot test and try it.

Thanks for your comprehension!

**Comment by memsharded** [comment]
Closing this ticket as outdated.
Lots of things have changed since then, including revisions, better version ranges, lockfiles, etc. Please create new tickets if necessary, thanks.
