### ISSUE TITLE
[workspaces] shared lib in workspace

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#4739]
My Exe requires my shared Lib.

My Exe `import`s Lib's dll file vial `copy`.

In a workspace, the dll file doesn't yet exist at install time.

Running Exe fails due to missing Lib.dll.

Using virtualenv seems very hard in this case because I run my targets through IDEs (CLion, Visual Studio) and my project is cross-platform.

Would it be possible to automatically create a symbolic link to Lib.dll inside Exe's build directory, in the case where Exe copies Lib.dll?

I would do it manually in conanfile for Exe but I can't seem to figure out how to get the package folder of Lib and just make a symlink directly...

I'm open to any suggestion to getting this to work. Is there a canonical wrapper program that people use to start executables inside conan virtualenv scripts in a cross-platform way?

**Comment by danimtb** [comment]
Hi @Lawrencemm,

As you are working in a workspace wrapped under the same CMakeLists.txt is this not enough to build the application and run it?

I suppose that if you are working from an IDE or calling the build system directly, the imports are not run so there is no way to do it.

Could you provide me with more detailed info about how you are using the workspace?

Regarding the cross-platform way, I not sure what you mean. If you are cross-building you are not able to run the app, right?

**Comment by Lawrencemm** [comment]
This is my workspace:
https://github.com/Lawrencemm/workspace

I've made a branch lmlib_shared where I'm trying to convert my library to a shared library but the dll isn't present in the build folder of the "lmeditor" program so it can't start up on Windows.

It works on Linux I have no idea how though.

**Comment by Lawrencemm** [comment]
I tried doing this:
```
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

conan_workspace_subdirectories()
```
But then the dll requirements that I copy in the conanfile:
`self.copy('*.dll', src='bin')`
Aren't present in this new destination for the output files, so the program still can't start.

**Comment by Lawrencemm** [comment]
I have a "solution".

Viewer discretion is advised.

```
add_custom_command(
  OUTPUT
  your_copied_dll
  COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:your_shared_target>
  ${PACKAGE_your_consumer_BUILD}
  DEPENDS your_shared_target
)

add_custom_target(
  copy_your_dll
  DEPENDS your_copied_dll
)

add_dependencies(lmeditor copy_your_dll)
```

Obviously this isn't very clean/scalable so it would be nice if the Conan workspace could be smart enough to know imported stuff won't exist yet at import time if the package you import from is in the workspace, and do something about that.
