### ISSUE TITLE
[suggestion]: adding capacities for dependency graph

### ISSUE THREAD

**Issue by ChristopheDoublier** [conan-io/conan#4740]
The `conan info --graph ` is a very useful tool to analyze or expose dependencies.
For me there is a lack of infos that i need:

when using html output:
- the channel in the package name is missing
- the user is missing (for my needs, all users are the same but in a more general use of conan, it may be helpful)

**These information are displayed when using dot output.**

The other thing is that the generated graph is the result of the resolving processus of conan for choosing the good packages. With this graph, we do not have the info of what are the true requirements in terms of constraints (exact value, >= value, [valueMin, valueMax],...)

I suggest adding this constraints info on the arrow itself (I know the used framework has got this facility) and maybe some decorations on node attributes may be cool:
for exemple:
```
digraph {
    node [shape=folder]
    "FakeProject/2.0.5@None/None" [style=filled, fillcolor=yellow]
    "TechnicalFramework/1.0.0@rcs/testing" -> "POCO/1.9.0-M0@rcs/stable" [label="constraint1"];
    "PubSubConnector/1.0.0@rcs/testing" -> "POCO/1.9.0-M0@rcs/stable" [label="constraint2"];
    "PubSubConnector/1.0.0@rcs/testing" -> "TechnicalFramework/1.0.0@rcs/testing" [label="constraint3"];
    "PubSubConnector/1.0.0@rcs/testing" -> "mosquitto/1.4.14-M0@rcs/stable" [label="constraint4"];
    "FakeProject/2.0.5@None/None" -> "PubSubConnector/1.0.0@rcs/testing" [label="constraint5"];
}

```

![image](https://user-images.githubusercontent.com/48549124/54350044-c77fa180-464c-11e9-8423-b86879205d59.png)

**to**

![image](https://user-images.githubusercontent.com/48549124/54350085-de25f880-464c-11e9-93db-cf4cc6844024.png)

**Comment by danimtb** [comment]
Hi @ChristopheDoublier,

The issue about the user and channel not being displayed in the root package is probably because you are using ``conan info .`` (path instead of the reference). This something normal for consumer recipes that are not exported to the conan cache as there is no sense for use & channel unless you export the package to the cache with ``conan export`` or ``conan create``. Is this a real issue?

Regarding displaying the constraint, maybe it is useful adding that to the arrows if the versions field is a version range. Would that be enough?

**Comment by ChristopheDoublier** [comment]
Indeed I use the `conan info . --graph=graph.html` or `conan info . --graph=graph.dot` command.
As i said in the precedent post, the user and channel are displayed in the dot output **but not** in the html one.  That's why i currently prefer using the dot format.
Regarding the constraints, I think the value defined in the recipes are useful whether it is range or "simple" value. For a good understanding and management of the Conan "overriding" and versions evaluation mechanism, i think a general view of all constraints is a very good point.

**Comment by ChristopheDoublier** [comment]
I'm actually trying to add this feature on my own repo and perhaps then propose a pull request. I'm facing a lack of knowledge on the data model and need help where to find the constraint info (if present in the data model, somewhere in the Node object of the `graph.py` file)

**Comment by danimtb** [comment]
Thanks for the clarification. So to sum up the action to solve this issue would be representing the constraints in the graph model. I think that would be useful for the users

**Comment by memsharded** [comment]
html output greatly improved since then, specially in Conan 2.2.
Also the html is a user template, if you want to provide our own template it is possible, the inputs are the documented ``json`` output for the graph.

Closing as implemented.
