### ISSUE TITLE
Conan deploy method fails if files are moved after copy

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#4742]
Does the conan install deploy(self) method benefit from some kind of sanity check?

I'm using a `deploy()` method to integrate our new conan-based build system with a legacy system we have.  Although I'd eventually like to get the legacy system to be itself fully conan-based, for now I need to settle for arranging conan-produced headers and libs into the directory structure the old system expects.

```copy``` and ```copy_deps``` seem to be working nicely (especially with ```folder=True``` for headers), except at the end I need to do some 'fix-ups' where the new conan package's name doesn't match the old directory that was expected.  E.g. a team named their conan package ```dtl-standalone```, whereas the old system expects ```dtl```.  When I try to fix this up manually using ```shutil.move``` at the end, I see that the files are moved as required, but then I get an ```md5sum``` error from Conan.

The error complains about a missing file in directory `'E:\\DevelopBp\\mmaguir1\\testnxgroups\\Libraries\\nxgroups\\20190314113438\\include\\dtl-standalone\\`  -- it's true this file no longer exists -- it's been moved to `E:\DevelopBp\mmaguir1\testnxgroups\Libraries\nxgroups\20190314113438\include\dtl` as I wanted.

Have I fallen afoul of some verification step done after the ```deploy()``` method completes?

```
def moveHeaderDir(includePathPrefix, oldName, newName):
    oldPath = "{}\\{}".format(includePathPrefix, oldName)
    newPath = "{}\\{}".format(includePathPrefix, newName)
    print ("moveHeaderDir moving from {} to {}".format(oldPath,newPath))
    shutil.move(oldPath,newPath)

[...]

    def deploy(self):
        installationPrefixDir = "E:\\DevelopBp\\mmaguir1\\testnxgroups"
        print ("Deploying under to installationPrefixDir {}".format(installationPrefixDir))
        now = datetime.datetime.now()
        
        buildNumber = self.options.buildNumber
        print ("Pass in self.options.buildNumber: {}".format(self.options.buildNumber))
        if buildNumber == "<generate>":
            buildnumber = '{:04d}{:02d}{:02d}{:02d}{:02d}{:02d}'.format(now.year, now.month, now.day, now.hour, now.minute, now.second)
            print ("Generated buildnumber: {}".format(buildnumber))
        else:
            print ("Using passed in buildnumber: {}".format(buildnumber))
        print ("Marking build with buildnumber: {}".format(buildnumber))
        rootDestinationDir = "{}\\Libraries\\nxgroups\\{}".format(installationPrefixDir,buildnumber)
        print ("Deploying  under to rootDestinationDir {}".format(rootDestinationDir))

        headerDestinationDir = "{}\\include".format( rootDestinationDir )
        print ("Deploying headers under to headerDestinationDir {}".format(headerDestinationDir))
        self.copy_deps("*.h", dst=headerDestinationDir, folder=True, keep_path=False)

        release_mode = str(self.settings.build_type)
        libDestinationDir = "{}\\lib\\{}\\{}_dynamic_64".format( rootDestinationDir, self.settings.compiler.toolset, release_mode )
        print ("Deploying libs under to libDestinationDir {}".format(libDestinationDir))
        self.copy_deps("*.lib", dst=libDestinationDir, folder=False, keep_path=False)
        self.copy_deps("*.pdb", dst=libDestinationDir, folder=False, keep_path=False)
        self.copy("*.props", dst=libDestinationDir, keep_path=False)
        
        # Now do hacky adjustments needed because sometimes package names
        # aren't consistent with output directory names.
        
        moveHeaderDir(headerDestinationDir, "dtl-standalone", "dtl")
```

```
Generated buildnumber: 20190314113438
Marking build with buildnumber: 20190314113438
Deploying  under to rootDestinationDir E:\DevelopBp\mmaguir1\testnxgroups\Libraries\nxgroups\20190314113438
Deploying headers under to headerDestinationDir E:\DevelopBp\mmaguir1\testnxgroups\Libraries\nxgroups\20190314113438\include
Deploying libs under to libDestinationDir E:\DevelopBp\mmaguir1\testnxgroups\Libraries\nxgroups\20190314113438\lib\v140_xp\Debug_dynamic_64
moveHeaderDir moving from E:\DevelopBp\mmaguir1\testnxgroups\Libraries\nxgroups\20190314113438\include\dtl-standalone to E:\DevelopBp\mmaguir1\testnxgroups\Libraries\nxgroups\20190314113438\include\dtl
nxgroups/0.0.1@PORT/stable deploy(): Copied 3919 '.h' files:
nxgroups/0.0.1@PORT/stable deploy(): Copied 110 '.lib' files:
nxgroups/0.0.1@PORT/stable deploy(): Copied 59 '.pdb' files:
nxgroups/0.0.1@PORT/stable deploy(): Copied 11 '.props' files:
Traceback (most recent call last):
  File "conan\conans\client\command.py", line 1428, in run
  File "conan\conans\client\command.py", line 394, in install
  File "conan\conans\client\conan_api.py", line 89, in wrapper
  File "conan\conans\client\conan_api.py", line 488, in install_reference
  File "conan\conans\client\manager.py", line 138, in install
  File "conan\conans\client\importer.py", line 121, in run_deploy
  File "conan\conans\client\importer.py", line 61, in _report_save_manifest
  File "conan\conans\util\files.py", line 95, in md5sum
  File "conan\conans\util\files.py", line 108, in _generic_algorithm_sum
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\DevelopBp\\mmaguir1\\testnxgroups\\Libraries\\nxgroups\\20190314113438\\include\\dtl-standalone\\dtlc_formulametadata.h'

ERROR: [Errno 2] No such file or directory: 'E:\\DevelopBp\\mmaguir1\\testnxgroups\\Libraries\\nxgroups\\20190314113438\\include\\dtl-standalone\\dtlc_formulametadata.h'
```

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.10.1 Windows 2012 R2

**Comment by memsharded** [comment]
Hi @michaelmaguire !

Yes, exactly. There is a feature that was implemented long time ago, per users requests, that is generating a manifest of what is being copied from the conan cache to user space (or system), in order to keep track of that, be able to remove files if necessary, etc. 

The ``conan imports`` command has even a ``--undo`` argument, that would use that file to automatically remove the copied files.

So the problem that you are hitting is that you are removing/moving/renaming those files in between, the ``self.copy()`` method is the one that tracks what files have been copied, and after ``deploy()`` finishes, it uses that information to generate the manifest.

I'd say that it is not possible to change this behavior without breaking other existing users. The only possibility I see right now is having the ``moveHeaderDir(headerDestinationDir, "dtl-standalone", "dtl")`` functionality as an external script to run after the deploy.

**Comment by michaelmaguire** [comment]
I understand.  Thanks.

Could we support a way to turn off this feature from within deploy(), or perhaps offer 'managed' move() or copy() operations that work for re-arranging within the deploy() method?

**Comment by michaelmaguire** [comment]
Nevermind.  I'll just make copies. ;-)

**Comment by memsharded** [comment]
Great, thanks!
