### ISSUE TITLE
CMakeMultiConfig (object, not generator)

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#4743]
To help us debug your issue please explain:

- [x]  I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

We're working with the latest conan release (1.13.0) and we are preparing to manage all our dependencies with Conan using the `cmake_paths` generator, but we feel that it is a little impractical to generate different packages for the setting `build_type`.
In a multi config environment such as Visual Studio, it is not practical for the users to run a `conan install .` every time the they switch between `Debug` and `Release` configuration in the Visual Studio IDE. Afterwards CMake will have to regenerate, because CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH change and so on.

In all our Recipes, we're using Conan very simple, with a build step such as 
```
class MyPackage(ConanFile):
  settings = "os", "compiler", "build_type", "arch"
  
  def build(self):
    cmake = CMake(self)
    cmake.definitions["my_definition"] = False
    cmake.configure(source_folder="src")
    cmake.build()
    cmake.install()
```

In order to generate a multiple Config package you could have something such as using a CMakeMultiConfig object instead of a CMake object
```
class MyPackage(ConanFile):
  settings = "os", "compiler", "arch"
  
  def build(self):
    cmake = CMakeMultiConfig(self, ["Debug", "Release"])
    cmake.definitions["my_definition"] = False
    cmake.configure(source_folder="src")
    cmake.build()
    cmake.install()
```
In this case, the setting "build_type" is omitted, because the package will contain the artifacts for all specified build configurations.

In our current implementation, we define this `CMakeMultiConfig` in a Python meta package, as an object basically inheriting from `CMake`, but invoking two builds (Debug and Release) on the `build()` call of the user.

```
class CMakeMultiConfig(CMake):
    """Build multi configurations using CMake"""

    def configure(self, *args, **kwargs):
        # project configuration happens as part of the build step
        self._config_args = args
        self._config_kwargs = kwargs

    def build(self, *args, **kwargs):
        if self.is_multi_configuration:
            cmd = "cmake %s %s" % (self._config_kwargs["source_folder"], self.command_line)
            self._run(cmd)
            self._run("cmake --build . --config Debug --target install")
            self._run("cmake --build . --config Release --target install")
        else:
            for config in ("Debug", "Release"):
                self._run("cmake %s %s -DCMAKE_BUILD_TYPE=%s" %
                          (self._config_kwargs["source_folder"], self.command_line, config))
                self._run("cmake --build . --target install")
                rmtree("CMakeFiles")
                remove("CMakeCache.txt")
```

This current implementation has many problems which I don't want to address here (such as not passing-through custom arguments like custom source_folder/build_folder, ...), but I guess the general intention should be clear.

My question is, are you considering an implementation like this for future releases? Are there any other users who are interested in a feature like this?
Of course we'd rather use something which is integrated into Conan that something which we "hacked ourselves" and relies on non-public API which might potentially break in the future.

Thanks for the feedback!

**Comment by danimtb** [comment]
Hi @KerstinKeller and thanks for the suggestion.

One thing I don't get from your example is that in order to achieve that you would need the dependencies in debug and release flavours, so you'd actually need to call ``conan install`` twice changing the build type flag or using a multi config generator like ``cmake_multi``. How are you currently achieving this?

Also note that instead of using that custom CMake multi build helper (that's how we call it), you could use the ``build_type`` paramenter in the constructor https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#constructor twice.

```
def build(self):
    cmake_debug = CMake(self, build_type="Debug")
    cmake_debug.build()
    cmake_debug.install()
   cmake_release = CMake(self, build_type="Release")
    cmake_release.build()
    cmake_release.install()
```

However, I am not sure how that works when doing the real packaging...

**Comment by KerstinKeller** [comment]
So actually we're preparing all of our packages to contain both Debug and Release artifacts such that they are `build_type` agnostic. Then if we're doing a `conan install` it will retrieve the required packages, which already contain both Debug and Release artifacts. So for a `conan install` you don't have to specify a `build_type` because the `package_id` of the consumed packages is thus independent of `build_type`.

Since we're inside a corporate infrastructure, we won't be able to use any of the "official" Conan packages, so even for thirdparty dependencies we fall back to our own recipes.

But as you said, if you consume "regular" Conan packages, you would have to have a "cmake_paths_multi" generator.

Using the `build_type` keyword with the CMake build helper would also be interesting, maybe you can even do it like this (to avoid repetition with passing definitions or such):

```
def build(self):
    for build_type in ["Debug", "Release]:
        cmake = CMake(self, build_type=build_type )
        cmake.configure(self.build_folder + "/" + build_type)
        cmake.build()
        cmake.install()
```

I think it would be important to then specify different build folders for the build types, only the `install` will put the artifacts into the same folder.

I will give this a try. The only downside I see is, that also you do have a multi configuration generator, you are not making use of it, but building twice.

**Comment by danimtb** [comment]
Thanks for the information now I understand the issue better.

I think it makes sense for your use case in your corporate environment. I suppose you are using `self.cpp_info.release.libs`. as described in https://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-package to get the appropriate CMake variables in the generator

Also, the code snippet like this is totally valid, mine was just for explanation purposes. Regarding the build folder, you can also change it in the configure step: https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#configure

**Comment by danimtb** [comment]
@KerstinKeller Did the information above worked for you? Can we close this issue as solved? Thanks

**Comment by KerstinKeller** [comment]
Yes, thanks again, your approach seems to work well, we're using it the following way now:

```
def build(self):
  for build_type in ["Debug", "Release"]:
    cmake = CMake(self, build_type=build_type)
    cmake.definitions["CMAKE_DEBUG_POSTFIX"] = "d"
    cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = "../conan_paths.cmake"
    cmake.configure(
      source_folder=self.name + "-" + self.version,
      build_folder=self.build_folder + "/" + build_type)
    cmake.build()
    cmake.install()
```

I will close this issue.
