### ISSUE TITLE
[suggestion] conan search - find latest package

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#4745]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
```
Conan Version 1.12.3
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

`conan search` does not show or have a way to quickly determine what the latest package is for a given version.

I was asked today how to download the latest package, and I realized it's not simple to find.
Maybe a `sort by date` flag could be added?

Or even just a way to query for the latest package matching a particular pattern and profile? 

It would be helpful to also be able to perform this task quickly via the `-j` json output as well for automation purposes.

Example:
According to artifactory web view (looking at `created` field) packageID 7920c0335e5d8f4aab8d863593bbed9966190fd0 was created last.
```
$ conan search ProjectName/2.12.2-2+g1077ed8@BoseCorp/master -r barbarian
Existing packages for recipe ProjectName/2.12.2-2+g1077ed8@BoseCorp/master:

Existing recipe in remote 'barbarian':

    Package_ID: 52f502c2da69379b2aea1f1a0fcf6d07d9c7e8da
        [settings]
            arch: qc8017_32
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 4.9
            os: Linux
        Outdated from recipe: False

    Package_ID: 7920c0335e5d8f4aab8d863593bbed9966190fd0 //according to artifactory, this was "created" last
        [settings]
            arch: qc8017_32
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 4.9
            os: Linux
        Outdated from recipe: False

    Package_ID: a6091767f6e481d08a5e701d8e90cb29058f10d4
        [settings]
            arch: qc8017_32
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 4.9
            os: Linux
        Outdated from recipe: False

    Package_ID: b94e40f42a5b1ab640c9f01ba9cde5dbcc2126ae
        [settings]
            arch: qc8017_32
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 4.9
            os: Linux
        Outdated from recipe: False
```

**Comment by lasote** [comment]
Why do you need to know what is the last created binary configuration? It sounds irrelevant at first sight.

**Comment by Mark-Hatch-Bose** [comment]
All of these recipes are using `full_package_mode` with `version ranges` and we are rebuilding the tree with CI frequently. The only difference between these packages are the dependencies. The latest package would be built against the newest versions of it's dependencies. We have a large tree of dependencies, so we would want to be able to grab the "latest" version (most recent dependencies) to test against, even if this particular package hasn't changed.

**Comment by lasote** [comment]
But the `package_id` is not something you can consume, it is computed. So, once you know what is the latest, what are you doing with it? Thanks

**Comment by Mark-Hatch-Bose** [comment]
We can use `conan download` with `-p` flag to download the latest package. Then use that package for testing.

**Comment by Mark-Hatch-Bose** [comment]
Sidenote: it'd also be nice to be able to get the `package_folder` location from conan download as well.

**Comment by lasote** [comment]
I kind of understand but it feels wrong.
First of all, I cannot easily modify the "conan protocol" with Artifactory, so we cannot count on that.
Second, you are downloading the package to run an executable inside it? no one is requiring that package? Conan doesn't work like that. A `package_id` should be computed, based on an input profile and the dependency tree. If you get a package it is because some consumer is requiring it. 

Maybe this process should be changed by having a consumer of the package you are downloading, then `install` with `--update`. To access a package executable you might use a [virtualrunenv](https://docs.conan.io/en/latest/reference/generators/virtualrunenv.html) generator or if the consumer is a recipe also, it could access also to the package folder to run something from the required package.

**Comment by Mark-Hatch-Bose** [comment]
Let me try explaining the scenario.

So we are using Conan to build some executable as the final package.
However, there are many different teams, building and updating the dependency tree.
We work on an embedded platform. We have QA/Testing teams that would test by pushing the executables on the embedded platform, but they don't care about building the code or running it locally on x86.

Example Tree:
DependencyA v1.0.0 (Team A)
DependencyB v1.0.0 -> DependencyA (Team B)
DepedencyC v1.0.0 -> DependencyB (Team C)
ExecutableD v1.0.0 -> DependencyA, DependencyC (Team D)

Now imagine TeamA makes a change, and DependencyA is updated to v1.0.1, and CI automation rebuilds the tree.
ExecutableD will now have a new package with same version v1.0.0 (it has not changed), but it now built with latest DependencyA v1.0.1. Generated new `package_id` and uploaded. (`full_requires_mode` and version range `[>=]`

When a QA tester says they want to test the latest ExecutableD, I don't have a good way to help them find that "latest" package. So they can push the executable onto the embedded platform to test.

Or if one of the developers on my team wants to run automation on the newest ExecutableD, which has a new  change from a different team (DepedencyA). 

We would need to know what the latest `package_id` is.

Hope this helps,
Mark

**Comment by Mark-Hatch-Bose** [comment]
@lasote this also concerns me outside of search, but also for `conan install` or `conan create`
If I'm using version ranges [>=] and there are several up-to-date packages (with different dependencies, but same version) how does conan decide which of these valid packages to choose to install.
Does it choose at random? Does it choose the last in the list?

If it's not using the latest dependencies generated, it may be using previous dependencies and not accurately reflecting the latest code.

I believe I'm seeing this in my CI, but I can't easily find a concrete example. I'll see if I can reproduce it.

**Comment by lasote** [comment]
Thanks for the explanation.

> When a QA tester says they want to test the latest ExecutableD, I don't have a good way to help them find that "latest" package. So they can push the executable onto the embedded platform to test.

If you do this:
```
conan remove ExecutableD -f
conan install ExecutableD --build never --update --profile whatever 
```
It should locate the latest `ExecutableD` based on the latest changes to the A, B, D libraries, right?
Also if you have a `deploy()` method in the `ExecutableD` it will copy the executable to a local directory so your QA team can try it.

About the version ranges, they are pretty basic and do not search the joint max satisfying version, it resolve node by node to the higher version available: https://docs.conan.io/en/latest/mastering/version_ranges.html

**Comment by Mark-Hatch-Bose** [comment]
Thanks for the help! I think I'm convinced that we'll never run into issues with `install` and `create`

Your recommendation unfortunately does not seem sufficient:

1. If the latest configuration is not yet built by CI and uploaded, the "ExecutableD" will show up as missing. So it won't download the latest package available in this case.

2. This also will download every dependency of "ExecutableD", even though we don't care about the dependencies at all.

```
PackageName/2.3.1-5+gd29abcb@BoseCorp/master:dbd3a222cb9714ce5e07f1165af62ed7d45a9a5e - Download
PackageName/3.3.0-6+g6f86690@BoseCorp/master:a4fd74c299ddead04fdfecb45af1ff4ece193298 - Download
PackageName/4.1.1-131+gdb94df6@BoseCorp/master:db9b137321e49d11a7eff55c60fd9799b2873d78 - Download
PackageName/3.1.11-0+g9051689@BoseCorp/master:04188185c02733638849f926cbaeba02a99bd618 - Download
PackageName/2.5.5-0+g16d2f43@BoseCorp/master:2235ba5550795bf0930a427c23beb9c13cf27870 - Download
PackageName/3.5.0-0+g5e26d91@BoseCorp/master:bb990e1248d7cea593947584e47f5f8904028598 - Download
ExecutableD/2.12.3-0+g5723e4b@BoseCorp/master:79749a0576d5e624db1c3d42ff6135d651484994 - Download
PackageName/2.5.1-0+gbd0307a@BoseCorp/master:9a49637e0f18d753516663da3adc1abae879fb3b - Missing
PackageName/1.0.0-5+gdc8c148@BoseCorp/master:4d8d1f6d711c6135fb6ab4b51399811f66397896 - Download
PackageName/2.2.1-18+g89c42ba@BoseCorp/master:f1f12d99efa7c03aa5b7078954d68aeb235ff0be - Download
PackageName/2.2.4-17+gda5b30b@BoseCorp/master:59cef5beb65d0e0f7dfb0a9cdc096b25593ea51a - Download
PackageName/2.2.0-426+g12a0397@BoseCorp/master:f1f12d99efa7c03aa5b7078954d68aeb235ff0be - Download
PackageName/3.0.1-37+g3bae81f@BoseCorp/master:f1f12d99efa7c03aa5b7078954d68aeb235ff0be - Download
PackageName/2.2.7-21+g573932a@BoseCorp/master:b20508a70ce283654b22ac2114f6b45a8761bd17 - Download
PackageName/2.2.8-31+gd11ef05@BoseCorp/master:f1f12d99efa7c03aa5b7078954d68aeb235ff0be - Download
PackageName/3.1.1-17+g049b570@BoseCorp/master:a4fd74c299ddead04fdfecb45af1ff4ece193298 - Download
```

3. You'll still need to do an initial conan search so the workflow for this is pretty clunky. `search` to get the right reference, then `remove`, then `install` (and the install may be missing, and will download a bunch of other stuff as mentioned above)

**Comment by lasote** [comment]
But if you don't care about the dependencies because the exe contains all it needs you should:

a) From the exe package use [build_requires](https://docs.conan.io/en/latest/devtools/build_requires.html) but in that case, by definition, the `package_id` for the exe package wont' change. Conan won't retrieve not even the recipes for the dependencies if the exe package is already built.

b) From the exe package use [private requires](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=private#requires). It will affect the package_id of the EXE. It will download only the recipes for your dependencies but NOT the binaries.

Why would you need to use the search? To look for the latest version of the exe? You could install with a version range also:

`conan install "ExecutableD/[>=2]@conan/stable" --update`

The remove is also optional if you use the `--update`

**Comment by Mark-Hatch-Bose** [comment]
Thanks Lasote,

I agree, and hopefully we'll get to a point where our packages are using `build_requires` and `private requires` to reflect their dependencies correctly.

Unfortunately, I have over 100+ repos and some export both a library and executable. I could spend the time to repackage them, but I'm already slammed trying to just get conan support in for all of them.
They are not yet "correct" in terms of isolation of exe and libraries. So it may take us some time to get there.

I did not know I can pass version ranges to install, so that's great!
I think that will work in the mean time, just wish I could download the latest package (and more importantly package id) more easily without downloading the dependencies in the meantime.

Appreciate the help! If you think that this would be too hard to feasibly implement, feel free to close this issue.

**Comment by lasote** [comment]
Happy to help. Thanks!
