### ISSUE TITLE
CPT won't work with Conan 1.14.0-dev

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4746]
To help us debug your issue please explain:

Conan Version: 1.14.0-dev

Hi!

After to merge the PR #4713 and exclude the test module from Conan installer, CPT will not be able to run its tests because we re-use many of Conan test tools there.

How could we install the test module only when required?

I've searched some options, and found some possible solutions in the internet:

- Create multiple eggs. One for Conan, One for test.
  Very complex IMO
- Use setuptools namespaces.
  I only read that is support on python +3.3. 
- Package all things as before, and remove only the test folder after to install.
  Most simple solution I think. I made this workaround some time ago:
  https://github.com/uilianries/conan-ldap-authentication/blob/master/setup.py#L55
  To install the test_folder, we can use extra. For now `conan[test]` only installs the development requirements, but we could change to skip the folder deletion.

You can check the log [here](
https://travis-ci.org/conan-io/conan-package-tools/jobs/506451807#L684).

Regards!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I proposed to keep the test tools and remove the test.

**Comment by uilianries** [comment]
Much simpler! Thanks!
