### ISSUE TITLE
Getting an x64 build with VS2019, but expecting an x86 build

### ISSUE THREAD

**Issue by v-strob** [conan-io/conan#4755]
I'm trying to get my project ready for VS2019, but I'm getting an x64 build where I used to get an x86 build in VS2017.  I noticed VS2019 support hasn't been announced in the changelog, so apologies if I'm reporting on an unfinished feature!

Tools I'm using:
Conan 1.13.1
CMake 3.14.0
Visual Studio Community 2019 16.0.0 RC.2
Visual Studio Community 2017 15.9.9
Windows 10 1809 64-bit

Steps to reproduce:
git clone https://gitlab.com/ssrobins/conan-sdl2.git
cd conan-sdl2
build_windows.bat

Notice that when the CMake output shows the selected compiler it shows Hostx86/x86/cl.exe, as expected.

Open build_windows.bat in a text editor and change:
compiler.version=15
To:
compiler.version=16

Re-run build_windows.bat.  CMake output shows Hostx64/x64/cl.exe as the compiler.  Make sure you have a finished sdl2 lib build so the lib is ready for the next step.

Now try to build a program using the sdl2 VS2019 lib in your local cache:
git clone https://gitlab.com/ssrobins/sdl2-example.git
cd sdl2-example

Open build_windows.bat in a text editor and change:
compiler.version=15
To:
compiler.version=16

Also, change the cmake command from this:
cmake -G "Visual Studio 15 2017" .. || goto :error
To this:
cmake -G "Visual Studio 16 2019" -A Win32 .. || goto :error

Run build_windows.bat.  I get linker errors because it's trying to link the 32-bit program with the 64-bit sdl2 lib.  I think the removal of architecture from the CMake generator name in favor of a separate -A parameter might be causing the problem.

**Comment by lasote** [comment]
I think this could be related to https://github.com/conan-io/conan/issues/4707
Probably the build helper is not indicating correctly the architecture.
This should be fixed for the next release.

**Comment by v-strob** [comment]
Fantastic, thanks for working on this!

**Comment by v-strob** [comment]
I'm still seeing the problem in Conan 1.13.2.  Is it supposed to be fixed in this one or later on?

**Comment by lasote** [comment]
At 1.14. You can check the milestones in the PR, sorry for not setting here the milestone: https://github.com/conan-io/conan/pull/4708

**Comment by lasote** [comment]
By the way, the 1.14 might be released this week

**Comment by ssrobins** [comment]
Confirmed that this is fixed in 1.14.0.  Thanks!
