### ISSUE TITLE
Concat of profile environment variables and recipe env-vars is always os.pathsep

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#4760]
Hello,

Using Conan 1.13.1, I'm getting an unexpected behavior with environment variables.

With the attached example, I would expect both `CXXFLAGS` to be present in the compiler invocation. Instead, the profile-defined one overrides the recipe-defined one.

[conan_cxxflags_bug.zip](https://github.com/conan-io/conan/files/2978686/conan_cxxflags_bug.zip)

I would expect the following behavior:

• Apply flags from build requirements (override previously defined ones? e.g. by shell scripts)
• Append flags defined in profile

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by theodelrieu** [comment]
@ytimenkov taught me about the `CFLAGS=[-Isomething, -g]` syntax. I never saw that in the docs (surely I have missed it).

Anyway I now have a different issue, here is the command line I get:

>clang++    -Inot_existing:-isystem /None ...

Seems to be a concatenation problem.

**Comment by solvingj** [comment]
I never saw the list literal syntax either. Cool!

**Comment by theodelrieu** [comment]
It seems cool indeed, but it doesn't quite work at the moment

**Comment by SSE4** [comment]
this is an important use-case, lemme describe intention behind it.
e.g. in `android_ndk_installer`, we have to define some `CFLAGS`, according to the [NDK documentation](https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md) (e.g. `-mstackrealign`). without these flags, we're at risk of producing incorrect binaries.
on other side, user may wish to specify additional `CFLAGS` into his profile, like `-fsanitize=address`, or `-pg`, or whatever else he needs for the specific use case.
given that two facts above together, we need a way to combine flags from the profile and from the build requirements recipe (and possibly also from the system environment as well). right now seems like there is no easy way to do so (or at least we were unable to find it).

**Comment by ytimenkov** [comment]
Preferred way to handle compiler flags in Conan is `self.cpp_info.cflags` (and others).
Declaring `CFLAGS` environment in profile relies on underlying build system correctly reading them and initializing. So in CMake case I would think it works (should work?) like this:
1. Profile defines initial flags as `CFLAGS=-Isystem -g`
2. Dependency defines extra flags by `self.cpp_info.cflags=["-Isomething", "-O"]`
3. When package is built, CMake has 2 sources: a command line `-DCMAKE_C_FLAGS=...` and environment variable which it combines and produces final set of flags.

Anyways I don't see how / why Conan needs to combine `CFLAGS` environment variable and using it leads to more confusion.

Maybe profile should contain `[cpp_info]` section instead so everything plays same rules?

Another option I can think about is a special `compile_flags` package which contains only build flags.

**Comment by theodelrieu** [comment]
As explained in [this issue](https://github.com/conan-io/conan/issues/3189), build helpers do not share the same behavior regarding `cpp_info` attributes.
Moreover, recipes not using any build helpers (e.g. calling `./configure` by hand) will not use `cpp_info` flags.

**Comment by memsharded** [comment]
> As explained in this issue, build helpers do not share the same behavior regarding cpp_info attributes.
Moreover, recipes not using any build helpers (e.g. calling ./configure by hand) will not use cpp_info flags.

To clarify, the ``cpp_info`` of the dependency graph, i.e. from all dependencies, is collected in the ``deps_cpp_info`` and translated to the generated files by generators: ``conanbuildinfo.cmake``, ``xxx_activate.bat|.sh``, etc. From there, it can totally be used by build systems even if they are being called by hand. Consider the CMake use case, where the ``conanbuildinfo.cmake`` contains all the include folders, library names, etc., from all the dependencies, and allows it to be called by hand ``$ cmake ....``.

Also it is important to remember that in generated files and in cpp_info, that defines information for the dependencies only. What is in ``package_info()`` is the package information, that is, once it has been built, and thus, it is information for consumers of the package exclusively. Nothing that is defined in a ``package_info()`` method will affect the ``build()`` of that recipe.

**Comment by theodelrieu** [comment]
>To clarify, the cpp_info of the dependency graph, i.e. from all dependencies, is collected in the deps_cpp_info

Indeed, that's what I really meant, thanks for the heads up!

**Comment by memsharded** [comment]
Hi @theodelrieu 

I am exploring your source code, and come up with the following test case:

```python
    def test_environment_from_profile_build_requires(self):
        client = TestClient()
        build_require = dedent("""
            from conans import ConanFile
            class TestConan(ConanFile):
                def package_info(self):
                    self.env_info.CXXFLAGS = ["-isystem /None"]
            """)
        conanfile = dedent("""
            from conans import ConanFile
            from conans.tools import load
            import os

            class TestConan(ConanFile):
                build_requires = "build_req/0.1.0@user/test"

                def build(self):
                    self.output.info("ENV CXXFLAGS: %s" % os.getenv("CXXFLAGS"))
            """)
        profile = dedent("""
            [env]
            CXXFLAGS=[-Inot_existing]
            """)
        client.save({"build_require.py": build_require,
                     "conanfile.py": conanfile,
                     "profile": profile})
        client.run("create build_require.py build_req/0.1.0@user/test")
        client.run("create . pkg/0.1.0@user/test -pr=profile")
        self.assertIn("ENV CXXFLAGS: -Inot_existing;-isystem /None", client.out)
```

Some notes:
- Environment variables do not automatically end up in generated files like ``conanbuildinfo.cmake``. Thus, I am checking the environment variable in the ``build()`` method. It is the responsibility of the method to pass it to the build system correctly
- Both build-requirement ``self.env_info.CXXFLAGS`` and profile ``CXXFLAGS`` env variable apply only to environment variable. The ``cpp_info`` is not related to them at all.


If there is some possible issue in the test, is that the environment variable is ";" separated instead of space separated. Is that what is failing for your use case?

**Comment by theodelrieu** [comment]
>Environment variables do not automatically end up in generated files like conanbuildinfo.cmake. Thus, I am checking the environment variable in the build() method. It is the responsibility of the method to pass it to the build system correctly

It's an issue that has been raised in #3303, since generated files do not get environment variables, you cannot use such a build requirement to build a consumer project having a simple `conanfile.txt`...

Is it really the method's responsability? That would be a burden for every recipe's maintainer right? It would also take a lot of the flexibility of build requirements.

>If there is some possible issue in the test, is that the environment variable is ";" separated instead of space separated. Is that what is failing for your use case?

I've printed env variable and get: `-Inot_existing:-isystem:/None`

**Comment by memsharded** [comment]
Yes, I totally agree it would be better if it were more intelligent and automatic, but that might be a totally new feature, that we should investigate. Is every XXXX environment variable mapped to build system variables, like a ``CMAKE_XXXX`` flag (or its proxy ``CONAN_XXX`` flag)?

If that is a feature request, please file a new issue with that title, and we will discuss there.

For the current issue, we need to figure out what would be the expected output. It seems that it is using a path separator (";" in Win, ":" in Linux) to separate environment variables. If I recall correctly there was somewhere that defined some exceptions to use spaces for some env-vars, but I guess the default assumes PATH-like environment variables, that are concat with those separators. What would be the expected output, spaces? Many thanks!

**Comment by theodelrieu** [comment]
>If that is a feature request, please file a new issue with that title, and we will discuss there.

Will do.

>What would be the expected output, spaces?

In this specific case, yes. However, it might be better to have a programmatic way of setting that variable separator.

**Comment by ytimenkov** [comment]
> If I recall correctly there was somewhere that defined some exceptions to use spaces for some env-vars, 

It's in virtualenv.py. Maybe it's an option to reuse it when concatenating env variables as well.

**Comment by memsharded** [comment]
No, actually the code that does that is in ``client/tools/env.py``, in the decorator:

```python
@contextmanager
def environment_append(env_vars):
  ....
   for name, value in env_vars.items():
        if isinstance(value, list):
            env_vars[name] = os.pathsep.join(value)
            old = os.environ.get(name)
            if old:
                env_vars[name] += os.pathsep + old
```

As it seems almost impossible to change this without breaking the world, it seems that we should have a way to opt-in the concat method. As this can be done in profiles and other recipes, it is necessary to carefully think about it.

I am going to clasify this to assign and prioritize this task. Thanks for all the feedback.

**Comment by theodelrieu** [comment]
I've been bitten by this one again, while having two build requirements appending `self.env_info.CXXFLAGS`.

Have there been any follow-up @memsharded ?

**Comment by saimusdev** [comment]
I went through the same or similar issue (two places were defining `CFLAGS` environment variables, e.g. two conan packages or a conan package + profile) and came up with the solution of dynamically generating executable scripts (`tools.save()`) in the `package_info()` method itself of the compiler toolchain package with: the actual path to the compiler inside + the flags. and defining this executables as the new `env_info.CC`... if it's of any help..

**Comment by rohel01** [comment]
Hello,

I have just been bitten by this. I want to demonstrate benefits of using conan at work.
For this, the first step I want to take is integrating conan as a package manager on top of our legacy build system. This build system is heavily reliant on environment variables.
The problem occurs with the environment variables that accumalate -I flags. My packages add flags in their respective package_info method. For example,

```python
    def package_info(self):
        self.env_info.PRJ_INCLUDE.append('-I' + os.path.join(self.package_folder, 'include'))
```

When a package consumes several other packages, the generated environment variables is

 `-I/home/melchiore/.conan/data/testPckg/0.1.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include:-I/home/melchiore/.conan/data/testPckg2/0.1.0/_/_/package/bf8720a763736cce58eca43241d3ba4180a0ebd1/include`

which is obviously problematic...

I would be very happy to know how to workaround this!

**Comment by memsharded** [comment]
Hi @rohel01 

We have provided a whole new set of improved tools to manage environment. You might want to have a look at https://docs.conan.io/en/latest/reference/conanfile/tools/env.html, specifically to ``buildenv_info`` and ``VirtualBuildEnv`` generator. They model explicitly paths from other variables. If you would like to pass flags, which is the case, you should do ``self.buildenv_info.append("-I{}".....)``, while if you want to handle paths, you should do something like ``self.buildenv_info.append_path("...)``.


In any case, I would like to suggest other approach. The ``self.cpp_info`` structure is the canonical way to pass this information, as it contains ``self.cpp_info.includedirs`` that you can set to define it, and it will benefit every consumer package now and in the future, when you change build system.

Then, what you really want to do is to create your custom XXXXToolchain for your build system, that transform the dependencies information into something your build system can understand, like env-vars. Your recipes with that build system will use it, while other recipes with other build systems wont use it, as they can use some of the built-in ones (like ``CMakeToolchain``) or even another custom one. But it decouples the producer from the consumer.

This is what I would try:

- First, fill the ``cpp_info`` of your package. You can perfectly have a test_package/conanfile.py with CMake to test that the package was correctly created. A good start is ``conan new hello/0.1 -m=cmake_lib`` template.
- Then, in one consumer package, in the ``generate()`` method, use an ``Environment()`` helper to create the environment, and save it to a script file. 
- Make sure your build injects that script file in ``self.run(...., env=["myscriptfile"])``, in the ``build()`` method, typically.

Once you have that working, time for engineering:
- Put the code inside your ``generate()`` in its own package inside a ``XXXToolchain`` class, with a ``generate()`` method.
- Export that package, and use it as a ``python_require`` in your consumers project.

Please let me know if this helps and if you have any question.

**Comment by rohel01** [comment]
Hi @memsharded,

Thank you for your quick and detailed answer. I also **really** appreciate that you provided both the quick & dirty and conan compliant solutions to my problem.

Using the quick & dirty solution (buildenv_info -> generate -> self.run(...env=), I am now able to fully build deliverable artefacts with dependencies versions tracked with Conan. This is suitable for a demonstration to stakeholders.  

Then, we will move include information into cpp_info, as you suggested. We need to decide internally if we develop a custom generator for the legacy build system or if we migrate the build to cmake or meson.

I do have a question on the quick & dirty way though: I was not able to cleanly get the script file name from the VirtualBuildEnv generator, since I am relying on the internal `_filename` property. Here is what I ended up with:

```python

    def generate(self):
        vbe = VirtualBuildEnv(self)
        vbe.generate()

        self.vbe_filename = vbe._filename

    def build(self):
       # Skipped code
      self.run('build command...', env=self.vbe_filename) 
      # Skipped code

```

**Comment by memsharded** [comment]
Hi @rohel01 

Yes, in theory you shouldn't need to get that filename:

- It is by convention first. ``VirtualBuildEnv`` will generate a file like ``conanbuildenv_x86_release`` that is automatically appended to ``conanbuild`` (.bat/.sh) script. And ``self.run(..., env=["conanbuild"])`` is already the default, so you don't need to do anything, just ``self.run(cmd)``
- If you really wanted to change the name of the ``conanbuildenv_x86_release`` file, you can do it (``.save_script()``), and it will still be automatically added to ``conanbuild.bat|.sh`` file, so still ``self.run(cmd)`` will work without further changes

**Comment by rohel01** [comment]
I confirm I do not need to handle the filename manually.

**Comment by rohel01** [comment]
Hello @memsharded,

After a successfull demonstration of the legacy buid system integration wirth Conan using  the VirtualBuildEnv generator, I am now trying to follow your advice by 

1. Putting dependency information back into the `self.cpp_info` structure
2. Translating this data into (legacy) build system instructions through a custom generator

I am using both the [custom generator documentation](https://docs.conan.io/en/latest/howtos/custom_generators.html#dyn-generators) and the virtualgenerator source as reference for this work.

I think I have pretty clear idea of what needs to be done. My questions so far:

I manage the build system as a Conan package (a set of makefiles and scripts). I think it would make sense my generator to beintegrated into that package recipe as it would both ensure version consistency and provide a single "point of entry" for consumers. Is it a recommended practice? Available examples use a dedicated package for the "generator" recipe.

Secondly, my legacy buid system package would only be used as `tool/build_require` dependencies. But, the current documentation for custom generator packages only use `require` dependencies. Will that be a problem?
For example, my generator needs to reference the build system package path. For `require` dependencies, I would use `deps_cpp_info['legacy_build'].rootpath`. Would it also work for `tool/build_require` dependencies?

**Comment by rohel01** [comment]
Ok, I answered my third question on my own by writing a dedicated, dummy recipe to query conan data model.
`tool/build_require` dependencies are available in `deps_cpp_info`

**Comment by rohel01** [comment]
I am trying to mimick some of the design of the `VirtualBuildEnv` generators as I am interested in its ability to automatically append its output env script to `conanbuild`.

There seems to be two kind of generators depending on whether they provide a `generate` method or the `content`/`filename` properties. The former used to be called "toolchains" in the conan code base?

`VirtualBuildEnv` generators seem to use both approaches:`conan/tools/env/virtualbuildenv.py` (Toolchain-like) vs. `conans/client/generators/virtual*env.py` (Generators)

This seems historical as nothing stops me from calling `save_script` directly in the `content` method of my generator.

Do you confirm my analysis?

**Comment by memsharded** [comment]
I am sorry this ticket was buried and it was not responded nor followed up on time. This sometimes happen when there are peaks of activity in our repos and projects, and some tickets might fall through the cracks.

Is this already solved, or can we close it? Any further question or feedback?

**Comment by memsharded** [comment]
Closing as stale, please create new tickets if necessary, thanks!
