### ISSUE TITLE
[question] how to configure using M4 macros

### ISSUE THREAD

**Issue by kjakkali** [conan-io/conan#4763]
I was trying to build [PBS](https://github.com/PBSPro/pbspro) using conan. PBS depends on few 3rd party binaries which we configure using [M4](https://github.com/PBSPro/pbspro/tree/master/m4) macros.
I could not find any example how to configure using M4 macros. Can you share some examples or explain how to configure using M4 macros?

**Comment by danimtb** [comment]
Hi @kjakkali and thanks for your question.

Could you provide a small example on how you are managing the dependencies configuration with M4?
I have no experience with it but maybe I can help you with a brief explanation

Thanks!

**Comment by kjakkali** [comment]
@danimtb : Thanks. 
While running configure we mention the third part 
Ex: ./configure --prefix=<installdir> --with-python=<python-dir> --with-editline=<editline-dir>

**Comment by kjakkali** [comment]
Project source : https://github.com/PBSPro/pbspro
M4 macros : https://github.com/PBSPro/pbspro/tree/master/m4

**Comment by kjakkali** [comment]
@danimtb : Did you get chance to try out M4 macro example?

**Comment by danimtb** [comment]
Sorry, I have been busy with other stuff. Will try to have a look at it soon

**Comment by danimtb** [comment]
FInally manage to give it a look. Yes, the Autotools and M4 macros are pretty common. We provide a helper fro[ autotools/configure](https://docs.conan.io/en/latest/reference/build_helpers/autotools.html) to leverage part of the boilerplate code to get the invocation command right.

However, the mapping for the M4 params has to be done via arguments. The whole libcurl *conanfile.py* recipe is a good example of this: https://github.com/bincrafters/conan-libcurl/blob/e455c7d9891f0ecf28deaffc606a82721ac3c8af/conanfile.py#L266

**Comment by kjakkali** [comment]
@danimtb  :Thank you. I will try out and will let you know.

**Comment by danimtb** [comment]
Great! Closing this as answered but feel free to comment or open a new issue if find any trouble
