### ISSUE TITLE
conan test_package with static library

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#4768]
Hello,

I don't know if this is a real issue or it's just me now knowing to deal with conan very well. I am using conan to pack some precompiled binary packages. The binary packages can be shared, static or headeronly.

```
import os
from conans import ConanFile, CMake, tools

class Package(ConanFile):
    name = '$name'
    version = '$version'
    license = '''$license'''
    url = '$url'
    description = '$description'
    settings = 'os', 'compiler', 'build_type', 'arch'
    options = {'Type': ['shared', 'static', 'headeronly']}
    default_options = 'Type=shared'
    generators = 'cmake'
    
    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

This is how my conanfile.py looks like. I have some python script wrapper over the conan create command which will provide the arguments as necessary for this recipe. Everything is great at this point. The package is created as expected.

The issue that I encounter is with the testing package:

```
import os
import shutil
from conans import ConanFile, CMake

class TestPackage(ConanFile):
    options = {'Type': ['shared', 'static', 'headeronly']}
    default_options = 'Type=shared'
    generators = 'cmake'
    
    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def imports(self):
        self.copy('*.dll', dst='bin', src='bin')
        self.copy('*.so*', dst='bin', src='lib')

    def test(self):
        os.chdir('bin')
        self.run('.%sexample' % os.sep)
```

When I create a package where Type option is set to static, the test package still look for the package where the option is set as shared. 

What am I doing wrong here? I am calling conan test_package with the same settings and options as I called conan create for the other recipe.

**Comment by memsharded** [comment]
Hi @danielhalati 

I think the error could be because the test_package itself shouldn't have the option. Most likely, the test_package is building an executable, and the option only affects the real package. So I'd try the following:

- Remove the ``Type`` option from your test_package
- Make sure you set the correct option with ``conan create . pkg/version@user/channel -o pkg:Type:static``

Besides that, I would consider taking into account:

- Don't use ``Type`` with Uppercase. Use lowercase, it is the normal in python and conan
- I am not sure about your model, as many libraries cannot in fact be opted-in to be header-only. If a library has .cpp and can compile to a static library, it is extremely difficult that it will be converted to header-only. If you have the tooling to do that, ok, but sounds complicated. If not, I'd try:
    - Have one kind of recipe with ``options = {"shared": [True, False]}`` for static/shared libraries. This is the official conan convention, and can be useful in the future if you decide to build things with ``build()`` method and build helpers, because Conan will understand this option
    - Have another kind of recipe **without** options, for header-only libraries. You should also remove the ``settings`` field completely from those recipes, as header-only do not change if you change those settings.

Please let me know if this helps. Thanks!

**Comment by danielhalati** [comment]
Thanks for your reply. I am not converting libraries to header only libraries. I said that my scenario is that I might have shared, static and headeronly libraries. I did not mean to say that the same library can have these 3 different types.

**Comment by memsharded** [comment]
It seems you created the package with ``shared=False``, and you are trying to test it with the default, that is ``shared=True``.

Please try the following:
```bash
$ conan test D:\Conan\zlib\conan\test_package zlib/1.2.8@daniel/stable -s os=Windows -s arch=x86 -s build_type=Debug -o zlib:shared=True
```
Thanks!

**Comment by danielhalati** [comment]
This worked. Thank you for your help !

**Comment by danielhalati** [comment]
I have another issue on Linux right now: Linux distribution is OpenSUSE 42.1

```
Running CreateBuildPkg
Exporting conan package ... 
conan export-pkg /home/user/Desktop/Projects/conan/zlib/conan zlib/1.2.8@daniel/stable -s os=Linux -s arch=x86_64 -s build_type=Debug -o shared=True -pf /home/user/Desktop/Projects/conan/_Sandbox_BUILD/zlib/stage/zlib-1.2.8 --force --profile /home/user/Desktop/Toolchain/profiles/x86_64-Linux

WARN: Migration: Generating missing metadata files
Migration: Generating missing metadata files finished OK!

/usr/lib/python2.7/site-packages/conans/util/fallbacks.py:9: UserWarning: Provide the output argument explicitly to function 'conans.client.tools.files.replace_in_file'
  warnings.warn("Provide the output argument explicitly{}".format(fn_str))
WARN: replace_in_file didn't find pattern '[plugins]' in '/home/user/.conan/conan.conf' file.

Python 2 will soon be deprecated. It is strongly recommended to use Python 3 with Conan:
https://docs.conan.io/en/latest/installation.html#python-2-deprecation-notice

Exporting package recipe
Linter warnings
    WARN: Linter. Line 1: Unused import os
    WARN: Linter. Line 2: Unused CMake imported from conans
zlib/1.2.8@daniel/stable: The stored package has not changed
zlib/1.2.8@daniel/stable: WARN: Forced build from source
Packaging to fec28e58d9bbccca4f42312b1b480aeea3055453
zlib/1.2.8@daniel/stable: Exporting to cache existing package from user folder
zlib/1.2.8@daniel/stable: Package folder /home/user/.conan/data/zlib/1.2.8/wenglor/stable/package/fec28e58d9bbccca4f42312b1b480aeea3055453
zlib/1.2.8@daniel/stable: Packaged 1 '.8' file: libz.so.1.2.8
zlib/1.2.8@daniel/stable: Packaged 2 '.h' files: zconf.h, zlib.h
zlib/1.2.8@daniel/stable: Packaged 1 '.1' file: libz.so.1
zlib/1.2.8@daniel/stable: Packaged 1 '.so' file: libz.so
zlib/1.2.8@daniel/stable: Package 'fec28e58d9bbccca4f42312b1b480aeea3055453' created
Tesing conan package ... 
conan test /home/user/Desktop/Projects/conan/zlib/conan/test_package zlib/1.2.8@daniel/stable -s os=Linux -s arch=x86_64 -s build_type=Debug -o zlib:shared=True


Python 2 will soon be deprecated. It is strongly recommended to use Python 3 with Conan:
https://docs.conan.io/en/latest/installation.html#python-2-deprecation-notice

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.8
os=Linux
os_build=Linux
[options]
zlib:shared=True
[build_requires]
[env]

zlib/1.2.8@daniel/stable (test package): Installing package
Requirements
    zlib/1.2.8@daniel/stable from local cache - Cache
Packages
    zlib/1.2.8@daniel/stable:f275daa1df80eb173d418881c6b9b9a548f4fe88 - Missing

zlib/1.2.8@daniel/stable: WARN: Can't find a 'zlib/1.2.8@daniel/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Debug, compiler=gcc, compiler.libcxx=libstdc++, compiler.version=4.8, os=Linux
- Options: shared=True
- Dependencies: 
- Package ID: f275daa1df80eb173d418881c6b9b9a548f4fe88

ERROR: Missing prebuilt package for 'zlib/1.2.8@daniel/stable'
Try to build it from sources with "--build zlib"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

```

**Comment by danimtb** [comment]
Hi @danielhalati,

I think you are calling ``conan test`` with different settings to ones used in the ``conan export-pkg`` step and that is why you are getting the error of missing package:

Original commants you posted:
```
$ conan export-pkg /home/user/Desktop/Projects/conan/zlib/conan zlib/1.2.8@daniel/stable -s os=Linux -s arch=x86_64 -s build_type=Debug -o shared=True -pf /home/user/Desktop/Projects/conan/_Sandbox_BUILD/zlib/stage/zlib-1.2.8 --force --profile /home/user/Desktop/Toolchain/profiles/x86_64-Linux

$ conan test /home/user/Desktop/Projects/conan/zlib/conan/test_package zlib/1.2.8@daniel/stable -s os=Linux -s arch=x86_64 -s build_type=Debug -o zlib:shared=True
```

In the ``conan test`` you are probably missing any addtional setting you may have in the profile ``--profile /home/user/Desktop/Toolchain/profiles/x86_64-Linux``.

Please try using that same parameter for the ``conan test`` too

**Comment by danielhalati** [comment]
A solution here please ?

**Comment by danimtb** [comment]
Hi @danielhalati,

Yes, the error you are getting looks like a bug. I am going to open an issue with the steps to reproduce it

thanks for reporting

**Comment by danielhalati** [comment]
Hi @danimtb 
Please indicate the issue to me so I can watch it.

**Comment by danimtb** [comment]
@danielhalati this is the issue #4833. I will propose a PR with the fix for next 1.14 version that should be released soon. Thanks again!

**Comment by danimtb** [comment]
Regarding the original reason for this issue. Can we consider it as solved @danielhalati?

**Comment by danielhalati** [comment]
Sure. I will close this.
