### ISSUE TITLE
conan create and should_test flag

### ISSUE THREAD

**Issue by AlexandreBossard** [conan-io/conan#4769]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan 1.13.1.

I wish i could tell conan not to run tests when I `conan create . user/mychannel`. Is there a reason for not implementing this feature ? Why there is no --no-test option on `conan create` ?

**Comment by danimtb** [comment]
Our recommendation for this purpose is using CONAN_RUN_TESTS env var https://docs.conan.io/en/latest/reference/env_vars.html#conan-run-tests although it has the opposite logic you are requesting.

However, tests are not always enabled normally...

**Comment by danimtb** [comment]
@AlexandreBossard did you check the approach above? Does it fit your use case?

**Comment by AlexandreBossard** [comment]
I haven't tried your solution, I've remove the call to `cmake.test()` basically in all my recipes. Your solution would work but it's a bit too global to my liking.

**Comment by dmerejkowsky** [comment]
@danimtb I still wonder about why there is no --no-test option on conan create. Could you please elaborate?

**Comment by danimtb** [comment]
>  but it's a bit too global to my liking

You can activate the env var for just that command.

> I still wonder about why there is no --no-test option

Probably it was not considered before as we only have a helper to run tests CMake and that a generic implementation for people not using the helpers will be a Conan env var (only available at Conan command running time) with the opposite meaning of the one proposed above.

Probably we could benefit from the parameters in `conan build` like ``--test`` and control it with `self.should_test` in the recipe but I don't see the other ones like `--configure`/`--build`/`--install` making too much sense for a ``conan create``.

So, in the end, it is just a flag... 🤷‍♂

**Comment by klimkin** [comment]
Would it make sense for `ConanFile.should_test` to have a default value of `tools.get_env("CONAN_RUN_TESTS", True)` instead of current `True`? Else we have to put this code in many conanfiles:
```
    if self.should_test and tools.get_env("CONAN_RUN_TESTS", True):
        cmake.test()
```

**Comment by memsharded** [comment]
The ``should_test`` arg has been dropped in 2.0, and replaces some time ago in 1.X with the conf ``tools.build:skip_test``. Closing this as outdated.
