### ISSUE TITLE
[workspaces] Will regular conan install command be supported?

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#4775]
It seems to be a good idea to sequester workspace functionality to a different command on the face of it, but it might make it harder for workspaces to be supported by things such as:
conan-io/conan-clion-plugin#20

Especially if the workspace command will continue to not have an install folder optional argument and require running from inside the install folder.

**Comment by lasote** [comment]
Yes, we thought about it before moving the install to the workspaces, we really want to separate the functionality. It has pros and cons indeed.

**Comment by Lawrencemm** [comment]
I'm OK with that.

I think the install folder argument is sorely needed though.

And IMO using a `conanws.yml` file in the current directory by default (if it's there) would be a plus.

**Comment by lasote** [comment]
Both could make sense. Please, if you are ok with that, just close this issue and open two new ones, one for the install folder parameter and another to look for `conanws.yml` by default in the specified directory. About the latest, I think we talked about it, it had some counterpart but I cannot remember. That way we can discuss prioritize and discuss them properly.
