### ISSUE TITLE
about static library conflict issue

### ISSUE THREAD

**Issue by kinglezhuang** [conan-io/conan#4776]
I have some issue about static library conflict when link 2 same libs.
For example, A depends on B & C,  B depends on C. An error of duplicate symbol occur while link A.

In Xcode, we can set other linker flag like -l"xml2" so it can solve conflict. 
How to config in conan?

**Comment by danimtb** [comment]
Hi @kinglezhuang,

If any of the libraries requiring C is not exposing the C API, then you could use a private requirement https://docs.conan.io/en/latest/reference/conanfile/attributes.html#requires

In your example, B could have a private requirement of C

**Comment by danimtb** [comment]
Closing this as solved as the question was answered. Thanks 😄
