### ISSUE TITLE
[workspaces] Use conanws.yml by default if no workspace file given

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#4778]
From the documentation it appears that the intention is for different workspace configs to be used under different settings, however I will use only one workspace config and use layout placeholders to make it work under different settings.

For this use case I think it would be good to have `conan workspace install` look for a `conanws.yml` file in the current directory and use that if no file is explicitly provided.

This implies the need for #4777 as I don't think it's a good idea to recurse up the directory hierarchy to look for this file.

**Comment by danimtb** [comment]
Basically, look for the "default" *conanws.yml* name in order to set up a workspace
