### ISSUE TITLE
Consider graph model without private dependencies (including build-requires)

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#4781]
Both private and build-requires have very complex implementation, because they span new, private subgraphs. Different versions of the same package can live in the same graph if they are private.
This comes with some problems:

- Dependency overriding from downstream is impossible/difficult UI
- Inconsistencies can happen more easily, building with different build-requires
- Inefficient, a graph with 100 libraries that uses 2 build requires will have 300 nodes.

This would be clearly breaking, so we would like to discuss it for Conan 2.0 and really need the feedback of the users here.

**Comment by Lawrencemm** [comment]
Would it be possible to link this issue to some of the notable issues associated with the problems you listed?

**Comment by lasote** [comment]
@memsharded I think the private requirements (I'm not talking about the specific implementation but the concept) makes sense and have to be kept. I would like to ask about why they cannot be overridden, is that a technical issue or a concept issue?
And, of course, `build_requires` too.
So, could you explain in which sense do you think they could/should be simplified?

**Comment by memsharded** [comment]
The new graph model, already released in 2.0.0-alpha1 contains the ``self.requires(..., visible=False)`` trait that implements most of the ``private`` functionality, in a much better and sound way. So this issue can be closed (as rejected, we won't remove this, but instead we have greatly improved it)
