### ISSUE TITLE
Feature Request: global registry configuration.

### ISSUE THREAD

**Issue by fukanchik** [conan-io/conan#4796]
This applies to any OS and version.

Unlike #934 this is not about global cache - only about global configuration of remotes.

Maven has ${maven.home} settings.xml: https://maven.apache.org/settings.html):
    There are two locations where a settings.xml file may live:

      The Maven install: ${maven.home}/conf/settings.xml
      A user’s install: ${user.home}/.m2/settings.xml

while conan has only $HOME/.conan/registry.json.

This does not allow to enforce system-wide list of remotes and does not allow to create global installation of conan.

What we would like to have is to install conan into `/opt` and configure reference to company's artifactory server without copying registry.json to every user's account.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi, Conan offers you two ways to achieve your goal, and if I have understood it well, any of them could cover your use case:
 * [conan config install <url>](https://docs.conan.io/en/latest/reference/commands/consumer/config.html?highlight=conan%20config%20install#conan-config-install): it is an easy way to share one configuration with all the members in a team, it allows an easy way to share not only the remotes, but all the settings, hooks and configuration parameters. It works per user.
 * environment variable [`CONAN_USER_HOME`](https://docs.conan.io/en/latest/reference/env_vars.html?highlight=conan_user_home#conan-user-home) let you choose a custom folder for the Conan cache.

Let me know if they are enough for your needs. Thanks!

**Comment by fukanchik** [comment]
The second option
>> environment variable CONAN_USER_HOME let you choose a custom folder for the Conan cache.
contradicts requirement of not having global cache - only global configuration. cache must still go to ~/.conan/

The first option only partially solves the problem. Instead of saying to the new engineer "just type `conan` on command line and that's it" we would have to tell them to run the following before doing anything else:

conan config install /some/location/config.zip

**Comment by jgsogo** [comment]
At this moment the information contained in the file `registry.json` is coupled with the contents of the cache. There is a proposal to decouple it and store the remote associated with each package or recipe as metadata of that concrete package or reference inside the cache; if it is done, we could remove the coupled information from the `registry.json` file and think about distributing remote information into several locations as you are suggesting. 

Right now, I can only recommend you the `conan config install ...` way, I think it is very interesting from a company point of view as it will install a known set of profiles too, so every developer will use the same configuration, environment variables, tools,...

IMHO opinion, running an extra command to get all the configuration needed to bootstrap my workspace exactly the same as my colleagues, it is worth it.

**Comment by memsharded** [comment]
That is one of the points why global configuration hasn't been implemented so far. The configuration is composed by many things:

- The profiles of the configurations/platforms to be managed
- Custom settings.yml
- Definition of remotes
- Custom recipe linting rules
- Custom hooks

Many of them are usually relatively dynamic, they change over time, and require updating. Running ``conan config install`` will provide a relatively easy to maintain system, that doesn't require sudo permissions, and allows to have different caches, for all of those things. Moreover, it allows to be also used in CI, being able to use changing configurations (it is very typical to have some jobs to point to some Artifactory instance, and other jobs to point to different Artifactory instance). 

So even if the remotes could be configured at the global level, there are other very important things to be configured/install/sync with the rest of the team and CI servers, and I can't see any other way simpler than a ``conan config install`` command.

**Comment by jgsogo** [comment]
Hi @fukanchik, we do think that the approach with `conan config install` is the better one to get started for a newcomer to a company.

If you are interested in the _global registry_ (regarding the remotes) I can keep this issue opened. Anyway, we need to finish work in https://github.com/conan-io/conan/pull/4724 before starting to think about this one, maybe it could be managed using a config/env variable like the `cacert_path` one.

**Comment by fukanchik** [comment]
Thanks, understood.
