### ISSUE TITLE
[workspaces] install folder parameter is lost after upgrading to 1.13.2

### ISSUE THREAD

**Issue by ezaiakinsc** [conan-io/conan#4799]
Newest version of Workspace feature has lost previously existing -if parameter, and that complicates tooling and build scripts significantly. We understand it can be replaced by shell script, performing change dir and executing conan in new location, but such a solution have an issue - one have to install mentioned "conan workspace driver" as global, as conan already installed, and that is rather intrusive.

Are there reasons to remove -if parameter, or it will come back soon?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Duplicated from https://github.com/conan-io/conan/issues/4777. right?
