### ISSUE TITLE
[workspaces] No out-of-source builds are possible after upgrading to 1.13.2

### ISSUE THREAD

**Issue by ezaiakinsc** [conan-io/conan#4800]
Most recent edition of Workspace feature is designed in the way that build folder of sub-libraries are relative to location of the libraries, and thus always pollutes source folder. With previous edition of Workspace feature we were able keep build artifacts of sub-libraries, participating in workspace, in workspace build dir, as sub-folders. That was convenient - sources of the libraries were unaffected, and one was able to have multiple workspaces active, with the same libraries used in it.

Right now such a setup is impossible - new layouts are imposing relative-to-library pathes only. It would be nice if we can have optional ability to use old logic for build artifacts location, out-of-sources workspace building was one of the key features of Conan for us.
 
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by theodelrieu** [comment]
I second that. What is the rationale for having relative-to-projects build folders?

**Comment by memsharded** [comment]
I think it might be possible indeed. 
We needed to step back a bit, to re-organize all the code, start using the editables, and then move forward and build on top on that. Lets try to move it forward.

**Comment by memsharded** [comment]
Well, it is still possible, but not enough documented, and not very usable because of the template engine of the layouts is receiving a reference as string, and it is likely that consumers will want the package name only.

I am proposing a fix in https://github.com/conan-io/conan/pull/4812 for next release, lets see if accepted and if yes, I will write an example in the docs.

**Comment by memsharded** [comment]
Merged, will be released in Conan 1.14, check the docs here: https://github.com/conan-io/docs/pull/1135/files
