### ISSUE TITLE
[workspaces] Consumer (conanfile.txt) as root of workspace

### ISSUE THREAD

**Issue by ezaiakinsc** [conan-io/conan#4801]
Current Workspace feature does not support conan "final consumer project" (configured by conanfile.txt) to be root of the workspace - it requires root to be full-featured package reference. As temp hack, we converted our conanfile.txt into conanfile.py with dummy names and versions, but we are not sure how safe such a solution is - do we have to keep those dummy names and version unique? Since those represent "final consuming projects", we do not have any reasonable names or versions for those - they are not supposed to go back into conan package.

If it is possible, please support conanfile.txt as root node of the workspace.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Thanks for reporting. Looks like a missing feature. I think you will be safe from now converting to the conanfile.py.

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
