### ISSUE TITLE
package dir not cleaned when using conan create with -kb 

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#4804]
When doing `conan create ... --keep-build`, the expectation is that the build directory will be left intact since the previous run, and the `package()` method will simply be re-run over that directory. That is happening successfully.  

However, when running `conan create... ` without `--keep-build` flag, the `package()` method always begins with a clean package directory as a destination for obvious reasons.  Conan implicitly clears the directory before running the `package()` method.  This "clearing" step is not currently happening when `--keep-build` flag is used.  It's easy to imagine how this detail was missed when `--keep-build` was implemented. Hopefully an easy fix. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
Understood. I have been able to reproduce the issue. Thanks a lot
