### ISSUE TITLE
python_requires overrides requires dependencies

### ISSUE THREAD

**Issue by mikemccullough** [conan-io/conan#4806]
Conan version: 1.12.3
OS: CentOS 7.6
gcc: 8.2.1 20180905

We are creating multiple libraries to be used throughout our group's development. In our case, we have a "core" project that used in all our other libraries, using it both for extending as well as a C++ dependency for the functionality that it provides. However, we'd incremented this top-level project from a 1.0.0 to 2.0.0 and ran across the following problem.

```
from conans import ConanFile, CMake, tools, python_requires

company = python_requires("companyCore/1.0.0@company/snapshot")

class CompanyAdditionalLibraryConan(company.CompanylCoreConan):
    name = "companyAdditionalLibrary"
    version = "2.0.0"

    requires = (
        "companyCore/2.0.0@company/snapshot",
    )
```

The `python_requires` is using the unintentional `1.0.0`, but the `requires` section is using the correct `2.0.0` version.

What we're seeing is that because the `python_requires` is using the old version, that's the version of the library that's pulled in for the C++ dependency rather than the new/correct version.

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Maybe Conan should manage better that situation but failing directly. A python require should be used to reuse python code only. Requiring also the same package as a regular require shouldn't be allowed.

**Comment by memsharded** [comment]
These python_requires were superseded long time ago by https://docs.conan.io/2/reference/extensions/python_requires.html, closing as outdated.
