### ISSUE TITLE
Install libONVIF library: Missing dependency

### ISSUE THREAD

**Issue by snair61** [conan-io/conan#4807]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I am using conan.io to build the dependencies (OpenSSL, Qt5). As mentioned in ReadMe, I run "conan install . --build missing" but it gives me different error messages every time I run it:

Then I installed openSSL using: conan install OpenSSL/1.1.1a@conan/stable
However I am unable to find any command which build the Qt>5.4 dependency for me. These are the different error messages that I receive:

_1. Unable to connect to conan-center=https://conan.bintray.com
2. ERROR: Version range '>=5.4' from requirement 'Qt/[>=5.4]@tereius/stable' required by 'conanfile.py (libONVIF/1.1.0-SNAPSHOT@None/None)' could not be resolved_

I also tried to install it using: _conan install qt/5.12.2@bincrafters/stable_
But that gives an error: _ERROR: Unable to find 'qt/5.12.2@bincrafters/stable' in remotes_

Any help would be deeply appreciated. Thanks.

**Comment by lasote** [comment]
The `qt/5.12.2@bincrafters/stable` lives right now in the Bincrafters repository, still not linked the conan-center. You have to add the bincrafters repository remote with `conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan `.
Once you have the repository added, if you have a `conanfile.txt` or `conanfile.py` listing your requirements (openssl and qt) you can just run `conan install .`. E.g:

```
[requires]
qt/5.12.2@bincrafters/stable
OpenSSL/1.1.1a@conan/stable

[generators]
cmake

```

As we specified the `cmake` generator, Conan will generate for us a `conanbuildinfo.cmake` file to be include in our `CMakeLists.txt` file. If you are going to build your project with other build system take a look to the generators available at the [Conan docs](https://docs.conan.io).

If the `conan install` command fails because of a missing package for your configuration, you can use `--build missing` to build from sources.

About the ` Unable to connect to conan-center=https://conan.bintray.com` it sounds like a connectivity error. Is working here perfectly.

Hope it helps.

**Comment by snair61** [comment]
Many thanks for your prompt response Lasote. I was able to run the following command: `conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan`

However, when I run the `qt/5.12.2@bincrafters/stable`: I get the error saying,
```
ERROR: Missing prebuilt package for 'sqlite3/3.26.0@bincrafters/stable'
Try to build it from sources with "--build sqlite3"
```

So I tried to build it from source using `--build missing`. But that gives me the same old error:
`conanfile.py (libONVIF/1.1.0-SNAPSHOT@None/None): ************************************************************
conanfile.py (libONVIF/1.1.0-SNAPSHOT@None/None):   This package defines both 'os' and 'os_build' 
conanfile.py (libONVIF/1.1.0-SNAPSHOT@None/None):   Please use 'os' for libraries and 'os_build'
conanfile.py (libONVIF/1.1.0-SNAPSHOT@None/None):   only for build-requires used for cross-building
conanfile.py (libONVIF/1.1.0-SNAPSHOT@None/None): ************************************************************
ERROR: Version range '>=5.4' from requirement 'Qt/[>=5.4]@tereius/stable' required by 'conanfile.py (libONVIF/1.1.0-SNAPSHOT@None/None)' could not be resolved
`

**Comment by SSE4** [comment]
@snair61 although you installed  `qt/5.12.2@bincrafters/stable` from bincrafters repository, I think `libONVIF/1.1.0-SNAPSHOT` still references `Qt/[>=5.4]@tereius/stable` somewhere. could you possibly try to update its conanfile (of libONVIF) to reference bincrafters recipe?

**Comment by snair61** [comment]
Hi, I was able to run the command: `--build missing`

However, when I run. `cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug /libONVIF`

I get the following error:

`CMake Error at src/CMakeLists.txt:4 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/sunil/Documents/Visual Code Projects/libONVIF/CMakeFiles/CMakeOutput.log".
`

**Comment by SSE4** [comment]
I think you need to specify `CMAKE_PREFIX_PATH` into your command line, in order to point CMake to the Qt installation path. it should be the package directory of `qt/5.12.2@bincrafters/stable` package somewhere inside $HOME/.conan

/cc @ericLemanissier

**Comment by snair61** [comment]
I see that qt/5.12.2@bincrafters/stable is installed. But where can I find the package directory? I could not find it in $HOME/conan.

`bzip2/1.0.6@conan/stable: Already installed!
double-conversion/3.1.1@bincrafters/stable: Already installed!
harfbuzz/2.3.0@bincrafters/stable: Already installed!
libjpeg/9c@bincrafters/stable: Already installed!
odbc/2.3.7@bincrafters/stable: Already installed!
sqlite3/3.26.0@bincrafters/stable: Already installed!
xkbcommon/0.8.3@bincrafters/stable: Already installed!
zlib/1.2.11@conan/stable: Already installed!
OpenSSL/1.1.0g@conan/stable: Already installed!
glib/2.56.1@bincrafters/stable: Already installed!
libpng/1.6.34@bincrafters/stable: Already installed!
libpq/9.6.9@bincrafters/stable: Already installed!
mysql-connector-c/6.1.11@bincrafters/stable: Already installed!
pcre2/10.32@bincrafters/stable: Already installed!
freetype/2.9.0@bincrafters/stable: Already installed!
qt/5.12.2@bincrafters/stable: Already installed!
`

**Comment by SSE4** [comment]
@snair61 please try to use the following command:
```
conan info qt/5.12.2@bincrafters/stable --paths
```
it should print out package directory

**Comment by ericLemanissier** [comment]
qt recipe already sets `CMAKE_PREFIX_PATH` for you : https://github.com/bincrafters/conan-qt/blob/stable/5.12.2/conanfile.py#L570 so `find_package(Qt5Core)` should work out of the box. your cmakelists.txt file should conform to Qt documentation: https://doc.qt.io/qt-5/cmake-manual.html
Could you show us your `CMakeLists.txt` file ? A working example is available at https://github.com/bincrafters/conan-qt/blob/stable/5.12.2/test_package/CMakeLists.txt

**Comment by snair61** [comment]
Hi, my conanfile.py does not have a CMAKE_PREFIX_PATH. 

`#!/usr/bin/env python
# -*- coding: utf-8 -*-


import json, os
from conans import ConanFile, CMake, tools, AutoToolsBuildEnvironment


class LibonvifConan(ConanFile):
    jsonInfo = json.loads(tools.load("info.json"))
    name = jsonInfo["projectName"]
    version = "%u.%u.%u%s" % (jsonInfo["version"]["major"], jsonInfo["version"]["minor"], jsonInfo["version"]["patch"], "-SNAPSHOT" if jsonInfo["version"]["snapshot"] else "")
    license = jsonInfo["license"]
    url = jsonInfo["repository"]
    description = jsonInfo["projectDescription"]
    author = jsonInfo["vendor"]
    homepage = jsonInfo["repository"]
    requires = "qt/5.12.2@bincrafters/stable"
    settings = "os", "compiler", "build_type", "arch", "os_build", "arch_build"
    options = {"shared": [True, False], "openssl": [True, False]}
    default_options = "shared=True", "openssl=True", "OpenSSL:shared=True"
    generators = "cmake"
    exports = "info.json"
    exports_sources = "*"

    def requirements(self):
        if self.options.openssl:
            self.requires("OpenSSL/1.1.0g@conan/stable")

    def build_requirements(self):
        if self.settings.os == 'Android':
            self.build_requires("android-ndk/r17b@tereius/stable")
            if self.settings.os_build == 'Windows':
                self.build_requires("msys2/20161025@tereius/stable")

    def build(self):
        tools.replace_in_file(os.path.join(self.build_folder, "CMakeLists.txt"), "### CONAN_BEACON ###", 'include(%s)\n%s' % (os.path.join(self.install_folder, "conanbuildinfo.cmake").replace("\\", "/"), "conan_basic_setup()"), strict=False)
        if self.settings.os == 'Android':
            autotools = AutoToolsBuildEnvironment(self, win_bash=True)
            environment = autotools.vars
            #environment["CC"] = self.deps_env_info['android-ndk'].CC
            #environment["CXX"] = self.deps_env_info['android-ndk'].CXX
            while tools.environment_append(autotools.vars):
                self.run("whereis cmake", win_bash=True)
                cmake = CMake(self, generator="Unix Makefiles")
                self.run('cmake "%s" %s -DCMAKE_C_COMPILER=%s -DCMAKE_CXX_COMPILER=%s' % (self.source_folder, cmake.command_line, tools.unix_path(self.deps_env_info['android-ndk'].CC), tools.unix_path(self.deps_env_info['android-ndk'].CXX)), win_bash=True)
                #cmake.configure(defs = {"CMAKE_MAKE_PROGRAM": tools.unix_path(os.path.join(self.deps_env_info['msys2'].MSYS_BIN, "make.exe")), "CMAKE_C_COMPILER": tools.unix_path(self.deps_env_info['android-ndk'].CC), "CMAKE_CXX_COMPILER": tools.unix_path(self.deps_env_info['android-ndk'].CXX)})
                #cmake.build()
                #cmake.install()
        else:
            cmake = CMake(self)
            cmake.configure()
            cmake.build()
            cmake.install()

    def package_info(self):
        self.cpp_info.builddirs = ['cmake']
        if self.options.openssl:
            self.cpp_info.defines = ['WITH_OPENSSL']`



This is my CMakeLists.txt 

`cmake_minimum_required(VERSION 2.8.12)
# Set a default search path for CMake modules
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/CMake")
include(JSONParser)

# Parse the info.json and write a info.h file
file(READ info.json jsonInfo)
sbeParseJson(info jsonInfo)

project(${info.projectName})

# Configure a header file to pass some of the CMake settings to the source code.
include_directories("${PROJECT_BINARY_DIR}/src")
file(WRITE "${PROJECT_BINARY_DIR}/src/info.h" "")
foreach(var ${info})
	string(TOUPPER "${var}" UPPER_VAR)
	string(REPLACE "." "_" UPPER_VAR "${UPPER_VAR}")
	if (${${var}} MATCHES "^[0-9]+$")
		file(APPEND "${PROJECT_BINARY_DIR}/src/info.h" "#define ${UPPER_VAR} ${${var}}\n")
	else()
		file(APPEND "${PROJECT_BINARY_DIR}/src/info.h" "#define ${UPPER_VAR} \"${${var}}\"\n")
	endif()
endforeach()

# The beakon will be replaced by conan if used
### CONAN_BEACON ###

# If build type is empty and there is no multi-configuration generator (like Visual Studio) choose release build.
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
	set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
endif()

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "Default Targets")

# Handle RPATH stuff
if (UNIX)
	set(RPATH_ORIGIN false CACHE BOOL "Set the RPATH to $ORIGIN? Helpful for bundles")

	# Use, i.e. don't skip the full RPATH for the build tree
	set(CMAKE_SKIP_BUILD_RPATH  OFF)
	# When building, don't use the install RPATH already
	# (but later on when installing)
	set(CMAKE_BUILD_WITH_INSTALL_RPATH OFF)
	if(RPATH_ORIGIN)
		set(CMAKE_INSTALL_RPATH "$ORIGIN/")
	else()
		set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
	endif()
	# Add the automatically determined parts of the RPATH
	# which point to directories outside the build tree to the install RPATH
	set(CMAKE_INSTALL_RPATH_USE_LINK_PATH ON)
	# The RPATH to be used when installing, but only if it's not a system directory
	if(NOT RPATH_ORIGIN)
		list(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
		if("${isSystemDir}" STREQUAL "-1")
			set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
		endif()
	endif()
endif()

# Handle doxygen stuff
find_package(Doxygen QUIET)
if(DOXYGEN_FOUND)
	configure_file("${CMAKE_SOURCE_DIR}/src/Doxyfile.in" "${PROJECT_BINARY_DIR}/Doxyfile" @ONLY)
	add_custom_target(doc "${DOXYGEN_EXECUTABLE}" "${PROJECT_BINARY_DIR}/Doxyfile" WORKING_DIRECTORY "${PROJECT_BINARY_DIR}" COMMENT "Generating API documentation with Doxygen" VERBATIM)
	message(STATUS "Use target \"doc\" to generate doxygen")
endif(DOXYGEN_FOUND)

# Handle precompiled header stuff
set(USE_PRECOMPILED_HEADERS false CACHE BOOL "Use precompiled headers?")
if(USE_PRECOMPILED_HEADERS)
	include(cotire)
	if(MSVC)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4251")
	endif()
endif()

add_subdirectory(src)

# Handle CPack stuff
if(WIN32)
	set(CPACK_GENERATOR ZIP)
elseif(UNIX AND NOT APPLE)
	set(CPACK_GENERATOR TGZ)
elseif(APPLE)
	set(CPACK_GENERATOR STGZ;TGZ)
elseif(ANDROID)
	set(CPACK_GENERATOR STGZ;TGZ)
else()
endif()
set(CPACK_PACKAGE_NAME "${info.projectName}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${info.projectDescription}")
set(CPACK_PACKAGE_VENDOR "${info.vendor}")
set(CPACK_PACKAGE_CONTACT "${info.contact}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_VERSION_MAJOR ${info.version.major})
set(CPACK_PACKAGE_VERSION_MINOR ${info.version.minor})
set(CPACK_PACKAGE_VERSION_PATCH ${info.version.patch})
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${PROJECT_NAME}{CTL_MAJOR_VERSION}.${CTL_MINOR_VERSION})
set(CPACK_PACKAGE_FILE_NAME  ${PROJECT_NAME})
include(CPack)`

**Comment by snair61** [comment]
> @snair61 please try to use the following command:
> 
> ```
> conan info qt/5.12.2@bincrafters/stable --paths
> ```
> it should print out package directory



> @snair61 please try to use the following command:
> 
> ```
> conan info qt/5.12.2@bincrafters/stable --paths
> ```
> it should print out package directory

@SSE4 Thank you for your response. I tried to run the command:
`:~/Documents/Visual Code Projects$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug CMAKE_PREFIX_PATH=/home/sunil/.conan/data/qt/5.12.2/bincrafters/stable libONVIF
`

But I still get the same error:

`CMake Error at src/CMakeLists.txt:4 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
`

**Comment by snair61** [comment]
@SSE4  and @ericLemanissier  thank you guys for the help. I was able to run with the following code:

`Visual Code Projects/libONVIF$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_PREFIX_PATH=/home/sunil/.conan/data/qt/5.12.2/bincrafters/stable/package/a0313bce260923f14855e6e2e7cc6a16839d0ac8 ../libONVIF`

Now, however when I do a make from the libONVIF directory, I see the following error:

`[  1%] Automatic MOC for target onvifcommon
[  1%] Built target onvifcommon_autogen
[ 18%] Built target onvifcommon
[ 19%] Automatic MOC for target onvifdisplay
[ 19%] Built target onvifdisplay_autogen
[ 24%] Built target onvifdisplay
[ 25%] Automatic MOC for target onvifdevice
[ 25%] Built target onvifdevice_autogen
[ 30%] Built target onvifdevice
[ 31%] Automatic MOC for target onvifimaging
[ 31%] Built target onvifimaging_autogen
[ 36%] Built target onvifimaging
[ 37%] Automatic MOC for target onvifrecording
[ 37%] Built target onvifrecording_autogen
[ 41%] Built target onvifrecording
[ 43%] Automatic MOC for target onvifanalytics
[ 43%] Built target onvifanalytics_autogen
[ 47%] Built target onvifanalytics
[ 48%] Automatic MOC for target headerParser
[ 48%] Built target headerParser_autogen
[ 50%] Linking CXX executable headerParser
/usr/bin/ld: cannot open output file headerParser: Is a directory
collect2: error: ld returned 1 exit status
src/CMakeFiles/headerParser.dir/build.make:120: recipe for target 'src/headerParser' failed
make[2]: *** [src/headerParser] Error 1
CMakeFiles/Makefile2:315: recipe for target 'src/CMakeFiles/headerParser.dir/all' failed
make[1]: *** [src/CMakeFiles/headerParser.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by ericLemanissier** [comment]
It's too low-level to define by hand `CMAKE_PREFIX_PATH` variable. This path will change each time you change any setting or option. You should rely on https://docs.conan.io/en/latest/integrations/cmake/cmake_paths_generator.html instead.
Regarding your error about headerParser, it is hard to help without reading the CMakeLists.txt. The message indicates it tries to link an executable named headerParser, but a directory of the same name already exists.

**Comment by snair61** [comment]
Hi Eric, this is my CmakeLists.txt

```
cmake_minimum_required(VERSION 2.8.12)
# Set a default search path for CMake modules
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/CMake")
include(JSONParser)

# Parse the info.json and write a info.h file
file(READ info.json jsonInfo)
sbeParseJson(info jsonInfo)

project(${info.projectName})

# Configure a header file to pass some of the CMake settings to the source code.
include_directories("${PROJECT_BINARY_DIR}/src")
file(WRITE "${PROJECT_BINARY_DIR}/src/info.h" "")
foreach(var ${info})
	string(TOUPPER "${var}" UPPER_VAR)
	string(REPLACE "." "_" UPPER_VAR "${UPPER_VAR}")
	if (${${var}} MATCHES "^[0-9]+$")
		file(APPEND "${PROJECT_BINARY_DIR}/src/info.h" "#define ${UPPER_VAR} ${${var}}\n")
	else()
		file(APPEND "${PROJECT_BINARY_DIR}/src/info.h" "#define ${UPPER_VAR} \"${${var}}\"\n")
	endif()
endforeach()

# The beakon will be replaced by conan if used
### CONAN_BEACON ###

# If build type is empty and there is no multi-configuration generator (like Visual Studio) choose release build.
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
	set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
endif()

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "Default Targets")

# Handle RPATH stuff
if (UNIX)
	set(RPATH_ORIGIN false CACHE BOOL "Set the RPATH to $ORIGIN? Helpful for bundles")

	# Use, i.e. don't skip the full RPATH for the build tree
	set(CMAKE_SKIP_BUILD_RPATH  OFF)
	# When building, don't use the install RPATH already
	# (but later on when installing)
	set(CMAKE_BUILD_WITH_INSTALL_RPATH OFF)
	if(RPATH_ORIGIN)
		set(CMAKE_INSTALL_RPATH "$ORIGIN/")
	else()
		set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
	endif()
	# Add the automatically determined parts of the RPATH
	# which point to directories outside the build tree to the install RPATH
	set(CMAKE_INSTALL_RPATH_USE_LINK_PATH ON)
	# The RPATH to be used when installing, but only if it's not a system directory
	if(NOT RPATH_ORIGIN)
		list(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
		if("${isSystemDir}" STREQUAL "-1")
			set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
		endif()
	endif()
endif()

# Handle doxygen stuff
find_package(Doxygen QUIET)
if(DOXYGEN_FOUND)
	configure_file("${CMAKE_SOURCE_DIR}/src/Doxyfile.in" "${PROJECT_BINARY_DIR}/Doxyfile" @ONLY)
	add_custom_target(doc "${DOXYGEN_EXECUTABLE}" "${PROJECT_BINARY_DIR}/Doxyfile" WORKING_DIRECTORY "${PROJECT_BINARY_DIR}" COMMENT "Generating API documentation with Doxygen" VERBATIM)
	message(STATUS "Use target \"doc\" to generate doxygen")
endif(DOXYGEN_FOUND)

# Handle precompiled header stuff
set(USE_PRECOMPILED_HEADERS false CACHE BOOL "Use precompiled headers?")
if(USE_PRECOMPILED_HEADERS)
	include(cotire)
	if(MSVC)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4251")
	endif()
endif()

add_subdirectory(src)

# Handle CPack stuff
if(WIN32)
	set(CPACK_GENERATOR ZIP)
elseif(UNIX AND NOT APPLE)
	set(CPACK_GENERATOR TGZ)
elseif(APPLE)
	set(CPACK_GENERATOR STGZ;TGZ)
elseif(ANDROID)
	set(CPACK_GENERATOR STGZ;TGZ)
else()
endif()
set(CPACK_PACKAGE_NAME "${info.projectName}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${info.projectDescription}")
set(CPACK_PACKAGE_VENDOR "${info.vendor}")
set(CPACK_PACKAGE_CONTACT "${info.contact}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_VERSION_MAJOR ${info.version.major})
set(CPACK_PACKAGE_VERSION_MINOR ${info.version.minor})
set(CPACK_PACKAGE_VERSION_PATCH ${info.version.patch})
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${PROJECT_NAME}{CTL_MAJOR_VERSION}.${CTL_MINOR_VERSION})
set(CPACK_PACKAGE_FILE_NAME  ${PROJECT_NAME})
include(CPack)
```

**Comment by SSE4** [comment]
@snair61 I don't see any traces of `headerParser` in your `CMakeLists.txt`. where is it coming from?

**Comment by snair61** [comment]
Hi, I tried to build it again and it compiles correctly. Thanks a lot for all your help guys.
