### ISSUE TITLE
[feature request] add a way to cache downloaded files

### ISSUE THREAD

**Issue by sboehmann** [conan-io/conan#4809]
I'm using Conan 1.13.2. My problem is that I often have very slow internet connections. Therefore it would be awesome if conan (notably tools.get) could cache downloaded files.

**Comment by Johnnyxy** [comment]
Hi there, there is already an ongoing discussion about such a feature.
Have a look here: https://github.com/conan-io/conan/issues/4668

**Comment by memsharded** [comment]
Yes, this would be a duplicated. Please follow up in #4668
