### ISSUE TITLE
Error on windows builds using conan

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#481]
Hi guys,

My dogen windows builds started failing since last night[1] with the following error:

```
echo "Downloading conan..."
"Downloading conan..."
wget http://downloads.conan.io/latest_windows -OutFile conan_installer.exe
conan_installer.exe /VERYSILENT
set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
conan --version
Error loading Python DLL: C:\Program Files (x86)\Conan\conan\python27.dll (error code 14001)
Command exited with code -1
```

Any ideas what could be causing this? I've done a couple just to check if its an environmental problem, to no avail. [2],[3]

Cheers

Marco

[1] https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.361/job/yglufvdim4xa19bi for Debug and https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.361/job/wqukii4wcspel7cm for Release
[2] https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.361/job/yglufvdim4xa19bi for Debug and https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.361/job/wqukii4wcspel7cm for Release
[3] https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.363/job/m2a76xq0qe8qkvou for Debug and 
https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.363/job/m98mj8nl1sf26xg4 for Release

**Comment by memsharded** [comment]
We released conan 0.12 yesterday, it might be a problem of the conan installer, just checking. Thanks for reporting

**Comment by memsharded** [comment]
Checked in three different windows machine, the installer seems to work fine. You might want to try to use the pip package instead of the installer. The pip package is the recommended way, and it is quite simple to install. Something in appveyor like:

```
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
```

**Comment by mcraveiro** [comment]
Aha, thanks very much @memsharded, that seems to have done the trick! My appveyor is now:

```
    - cmd: set PYTHON="C:/Python27"
    - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
    - cmd: pip.exe install conan
    - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
    - cmd: conan --version
```

And it seems to be building away happily! [1]

Cheers

https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.365/job/wi0o12hsa8onvljy

**Comment by mcraveiro** [comment]
I'm closing the issue as I am happy with the workaround. However, I think there is still some kind of issue with the package itself so if you want to reopen it for that that's fine with me.

Cheers

**Comment by memsharded** [comment]
Great Marco! Happy to know that using the pip package works for you.
We have just released a fixed installer for windows, solving the issue. The problem was an upgrade in our deploy infrastructure, so the problem for the .exe installer should be gone by now too. 
Thanks again!
