### ISSUE TITLE
cmake.configure() detected Visual Studio 2019 compiler incorrectly

### ISSUE THREAD

**Issue by neutralevil** [conan-io/conan#4813]
Conan: 1.13.2
CMake: 3.14.0

[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows

If I call cmake.configure(build_dir="."), CMake detect a x64 targeted compiler like:
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works

But the Hostx64/x86/cl.exe is expected.

**Comment by lasote** [comment]
I think this might be a duplicated of:
https://github.com/conan-io/conan/issues/4707
and
https://github.com/conan-io/conan/pull/4708

fixed here: 
https://github.com/conan-io/conan/pull/4708

to be released in Conan 1.14

**Comment by lasote** [comment]
If you could confirm, would be great. It is merged in develop branch already.

**Comment by neutralevil** [comment]
I think #4708 fixed this issue.
According to ddeb7aebfd0c6914535ab8eedcbd96f71101bae6, I added argument `args=['-A', 'Win32']` manually to `cmake.configure()`. It works.

Waiting for 1.14.

**Comment by lasote** [comment]
So closing this one. Feel free to comment again if the problem persists after.
