### ISSUE TITLE
Upgrade to Conan 0.12.0 fails

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#482]
I'm trying to upgrade conan with `pip install conan --upgrade` on an Ubuntu system. Everything works as expected, but when I try to run conan afterwards I get the following error:
`ERROR: [Errno 2] No such file or directory: '/home/ubuntu-16041-64-219/.conan/settings.yml'`

Same happens when I do a `pip uninstall conan` and then `pip install conan` again.

**Comment by memsharded** [comment]
Can you please confirm if your current user name is "ubuntu-16041-64-219" ?

**Comment by monsdar** [comment]
Yeah it is. I looked in the directory and there was no settings.yml in there. I solved the problem by copying the file from my windows installation. Conan then reinitialized the file for me.

**Comment by memsharded** [comment]
I have just tried upgrading to 0.12.0 in my ubuntu 16, everything went fine. Is it possible that some error appeared the first time? Any warning regarding a migration of the settings.yml? Maybe something failed in the migration (basically add new settings as clang 8 and latest gcc to settings), and the file was removed.

**Comment by monsdar** [comment]
It's a Ubuntu 16.04 too. It's now working, I just had that the first time.
It was a server that I wasn't using before. It could be possible that I did an --upgrade without a previous installed conan. Could this be a problem?

**Comment by memsharded** [comment]
I think I know what happened. The settings.yml is generated by running conan. If conan is upgraded over a previous installation of conan that were not run, it will try to migrate a missing file. Shouldn't happen very often, but better fix this in our migrations.

**Comment by monsdar** [comment]
Yeah, it's easily possible that there previously was a conan installed that's never been used.
