### ISSUE TITLE
CI improvements to check Artifactory

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4831]
Create a Dockerfile to have the code from conan from branch XXX and the Artifactory docker URL image YYY and run the `revisions_test` with the real Artifactory. (parameters)

- QA team can use it with latest dev Artifactory and stable conan.
- Conan team can use it with the latest conan code and latest stable Artifactory.

**Comment by uilianries** [comment]
Do you want transfer this one to Conan Docker Tools, or at least, create a image there which could have custom remote address.

**Comment by uilianries** [comment]
@lasote Do you want transfer this one to Conan Docker Tools, or at least, create a image there which could have custom remote address.

**Comment by lasote** [comment]
No, I prefer to have it here as it is intended to test this repository. The image won't have any interest in the main public. Also, it will be very specific and for some concrete tests.

**Comment by lasote** [comment]
We have 2 pending tasks:

a. Test more artifactory versions, maybe the first one supporting Conan, the latest and another
b. Make the script to return "0" if artifactory version was not supporting revisions or the conan version is not the minimal we want to test (with revisions)

**Comment by lasote** [comment]
Done. The preflight builds run now with Artifactory `6.9.0`, `6.10.6` and `latest`.
