### ISSUE TITLE
Local methods (conan source, conan build...) based on layouts?

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4836]
Maybe they should converge in the layout mechanism, so once you declare a [build_folder], [source_folder] maybe the local methods should follow these folders directly when no arguments are passed to the local command (--build_folder) etc.

This issue should be considered as a general idea to develop.
Added to the 2.0 as a wish, more than a commitment.

**Comment by memsharded** [comment]
This was implemented with the ``layout()``
