### ISSUE TITLE
cmake find_package generator with pure cmake project (no libraries, no headers)

### ISSUE THREAD

**Issue by arnaudgelas** [conan-io/conan#4844]
- I would like to create and used a package in which there are only cmake files, installed in `lib/cmake/<project_name>`.

- I need to use a non intrusive CMake approach, and I would definitively prefer go for an approach which does not make use of `CMAKE_TOOLCHAIN_FILE`.

I have tried to use cmake_find_package generator, but I can't figure out how to make test_package works. Am I missing something? or is there something missing in conan for this purpose?

See https://github.com/arnaudgelas/conan-cmake-dummy for reference.

**Comment by Johnnyxy** [comment]
Hi there,
as I understand you want to make a Conan package that contains only CMake files to use them in other projects?

If so you can do this with [cpp_info.builddirs](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info). This sets the ```CMAKE_MODULE_PATH``` variable of CMake to all paths given in ```builddirs```. In turn CMake looks in ```CMAKE_MODULE_PATH``` for search paths for ```find_package```.

```python
class Recipe(ConanFile):
    name ="CMakeUtils"
    version = "0.0.0"
    exports = ["*.cmake"]

    def package_info(self):
        self.cpp_info.builddirs = ["", "cmake/lib"] # adds package root and a possible subfolder
```

```
conan install ...
```

```python
class RecipeConsumer(ConanFile):
    requires = "CMakeUtils/0.0.0@user/channel"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        ...
```

```cmake
...
find_package(MY_SUPER_LIB REQUIRED) # imports a CMake file named: FindMY_SUPER_LIB.cmake

# use your super-lib-cmake-files
```

**Comment by arnaudgelas** [comment]
@Johnnyxy I have tried exactly you solution here:
https://github.com/arnaudgelas/conan-cmake-dummy/tree/solution/Johnnyxy

I still get the same error in the test_package stage:

```
dummy/1.0@demo/testing (test package): Running build()
-G "Unix Makefiles" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="OFF" -DCMAKE_MODULE_PATH="/home/agelas/temp/conan-cmake-dummy/test_package/build/7f6cc68115e0d1c58c111cf15e9636a11456d971" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev
CMAKE_MODULE_PATH: /home/agelas/temp/conan-cmake-dummy/test_package/build/7f6cc68115e0d1c58c111cf15e9636a11456d971
-- Conan: Using autogenerated Finddummy.cmake
-- Found dummy: 1.0 (found version "1.0") 
CMake Error at CMakeLists.txt:12 (include):
  include could not find load file:

    my-super-cmake-file


CMake Error at CMakeLists.txt:14 (do_some_incredible_stuff):
  Unknown CMake command "do_some_incredible_stuff".


-- Configuring incomplete, errors occurred!
```

Any idea what could be wrong?

**Comment by Johnnyxy** [comment]
Have a look in your repository I made a [pull-request](https://github.com/arnaudgelas/conan-cmake-dummy/pull/1) that I have tested.

Additionally I saw some odd behaviour with ```deps_cpp_info.builddirs```.
See here: https://github.com/conan-io/conan/issues/4848

**Comment by danimtb** [comment]
Hi @arnaudgelas,

You can use the approach you proposed packaging the desired "Find" and "Config" files in your packages and then use them for your consumers to get the information.

In that case, the "cmake_find_package" generator will not be needed, only adjusting the CMAKE_MODULE_PATHS to the buildirs of the dependencies as @Johnnyxy reported.

However, if you want to use the same approach even with packages that don't have CMake support, you can use the "cmake_find_package" to achieve the transparent integration with CMake. This means that Conan will create all the suitable "Find" files from your dependencies and place them in the installation dir.

Then, if you build with the CMake helper, Conan will adjust the CMAKE_MODULE_PATH to the installation directory so the files are found when using ``find_library()``. Please take a look to this PR with the changes needed to make your example work: https://github.com/arnaudgelas/conan-cmake-dummy/pull/2

Hope it makes sense. Please comment any further doubt. Thanks! 😄

**Comment by arnaudgelas** [comment]
@Johnnyxy Your solution is indeed works!

However this is quite intrusive: I have to renamed all my cmake files `foo.cmake` -> `Findfoo.cmake`, change all cmake `include()` inside this project by cmake `find_package` and also in all projects that depends on that one and this is unfortunately not possible for me  :disappointed:

**Comment by arnaudgelas** [comment]
Following #4848, I have managed to do a totally non-intrusive solution in this MR: https://github.com/arnaudgelas/conan-cmake-dummy/pull/3

**Comment by arnaudgelas** [comment]
Hi @danimtb ,

You wrote:
> Then, if you build with the CMake helper, Conan will adjust the CMAKE_MODULE_PATH to the installation directory so the files are found when using find_library(). Please take a look to this PR with the changes needed to make your example work

Sorry for my extremely naive questions, I am a total conan newbie:
* What do you mean by "if you build with the CMake helper"? You mean to use the `CMake` object in `conanfile.py`?
* You wrote files are found when using `find_library()`, you meant `find_package()`, right?

I had a look at you PR, but you removed all cmake files which were meant to demonstrate my actual issue, and so I could not make it work :disappointed:

**Comment by danimtb** [comment]
> What do you mean by "if you build with the CMake helper"? You mean to use the CMake object in conanfile.py?

Yes, we call this kind of objects[ build helpers](https://docs.conan.io/en/latest/reference/build_helpers.html) or [tools](https://docs.conan.io/en/latest/reference/tools.html).

> You wrote files are found when using find_library(), you meant find_package(), right?

Yes, sorry. I meant `find_package()`

----

Having a look at your solution in https://github.com/arnaudgelas/conan-cmake-dummy/pull/3 that would be the best approach. But I think you wouldn't need to use the ``cmake_find_package`` generator at all because you are packaging the CMake files inside, so you don't need Conan to generate any dependency file.

The drawback of this approach is that you have to be careful regarding transitive dependencies, and correctly manage them in your CMake config files. (this is something that Conan auto-manages with the `cmake_find_package` generator approach). Take into account that you might have conditional requirements depending on the OS or on the package options, which is something quite common when developing a project with cross-platform support.

----

If you haven't read about it, please check the analysis of the different CMake generators we did some time ago in our blog: https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html

Also, the CMake integration in the docs might come handy: https://docs.conan.io/en/latest/integrations/cmake.html

**Comment by Johnnyxy** [comment]
@arnaudgelas 

I reviewed your pull request. Your changes will work. See my comments on the PR.

file naming
--------------
I renamed the CMake files as the basic module mode of ```find_package``` needs this ([see here](https://cmake.org/cmake/help/v3.14/command/find_package.html?highlight=Find%3CPackageName%3E.cmake#basic-signature-and-module-mode)).

If you use the full/config mode then you can use the [NAMES](https://cmake.org/cmake/help/v3.14/command/find_package.html?highlight=NAMES#full-signature-and-config-mode) parameter and even specify the name(s) of the file you are looking for. So you do not even have to use the ```dummy-config.cmake``` name (```-config.cmake``` postfix is mandatory). But you can access it by the package name ```dummy``` you gave the ```find_package``` command.

```cmake
find_package (dummy
    NAMES
        # this will search for my-SUPER-dummy-fileConfig.cmake and my-super-dummy-file-config.cmake
        "my-SUPER-dummy-file"
    REQUIRED
    CONFIG
)

message (STATUS "The package \"dummy\" has been found. ({path: ${dummy_DIR}}, {full filename: ${dummy_CONFIG}})")
```

includes
-------------
I stripped the ```include``` as ```find_package``` already does that implicitly.

**Comment by arnaudgelas** [comment]
@Johnnyxy I did not know about the `NAMES` parameter in find_package, this is neat!!

**Comment by arnaudgelas** [comment]
I also managed to make it work using cmake_paths generator, see https://github.com/arnaudgelas/conan-cmake-dummy/pull/4

**Comment by danimtb** [comment]
Closing the issue as it seems to be solved. Thanks a lot for the discussion and please point out if something should be clarified in the documentation
