### ISSUE TITLE
[bug] cmake build helper does not set deps_cpp_info.buildpaths to CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4848]
hi there,
I was fiddling around with the ```cpp_info.builddirs``` and noticed that the CMake build helper in consuming packages does not append the ```deps_cpp_info.build_paths``` to the ```CMAKE_MODULE_PATH``` variable at CMake configure time.

Have a look here: https://github.com/Johnnyxy/conan-cmake-dummy/blob/9a6d06ce15f492118dbf6a13a0b9db95eb29018a/test_package/conanfile.py#L16

If one removes this line (see link) the ```deps_cpp_info.build_paths``` will not show up in the consuming CMake (CMAKE_MODULE_PATH).
```python
cmake.definitions["CMAKE_MODULE_PATH"] = ";".join([str(Path(x).as_posix()) for x in (cmake.definitions["CMAKE_MODULE_PATH"].split(";") + self.deps_cpp_info["cmakeutils"].build_paths)])
```

essentially one has to add those paths manually to
```python
def build(self):
    cmake = CMake(self)
    cmake.definitions["CMAKE_MODULE_PATH"] = ...
    cmake.configure()
    ...
```

**Comment by danimtb** [comment]
This behavior is done adjusting the CMAKE_MODULE_PATH to the install folder (where the "find" files are created) of the consumer here https://github.com/conan-io/conan/blob/9844fd7e0cbf6930dc3ce50f0a5bf20da2a2c3ee/conans/client/build/cmake_flags.py#L306 when using ``cmake_find_pacakge`` generator.

However, I think the CMAKE_MODULE_PATH should be also adjusted with the "cmake" generator. Could you give it a go?

I think the different possibilities with all the cmake generators were discussed in https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html

**Comment by Johnnyxy** [comment]
@danimtb when I 

First things first :).
-----------------
```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
```

This does not work if I change the ```install-folder``` while executing conan. On the command line executed by ```cmake.configure()``` there is no indication of the ```install-folder``` path. So how can a ```CMakeLists.txt``` include the ```conanbuildinfo.cmake``` without knowing the path?


Second things
--------------
As I am using only the handy ```cmake_find_path``` generator for decoupling then the ```cmake``` generator would not be an working alternative (different approach of Conan/CMake integration).

The [doc state](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=cpp_info#cpp-info) for the ```builddirs```:

> Ordered list with build scripts directory paths. Defaulted to [""] (Package folder directory)
CMake generators will search in these dirs for files like findXXX.cmake

As with the ```cmake_find_path``` generator the modules path is not the docs are misleading.

Workaround for CMake build helper
---------------------------------------
To get the dependencies ```deps_cpp_info.build_paths``` into the CMAKE_MODULE_PATH variable without using the ```cmake/cmake_multi``` generator one has to adjust it manually before executing the CMake configure phase.

Solution
-----------
The CMake build helper adjusts the CMAKE_MODULE_PATH variable automatically like the workaround would do it.

**Comment by danimtb** [comment]
Thanks for the clarification.

I have verified that the cmake generator is adjusting the `CMAKE_MODULE_PATH`. I thought you were talking about that generator first.

------

Regarding the sentence in the docs, you are right, it might be misleading. Some CMake generators will look there, not all of them.

-----

Finally, the issue is that the `CMAKE_MODULE_PATH` is not adjusted when using the cmake_find_package generator. And that's true. However, this is done for a reason:

The way Conan works is interfacing with de build system via generators and build helpers. When using the `cmake_find_package` generator you are relying on Conan to generate the proper files in the consumers install folder so they can be used later to find the dependencies installed by Conan. This means that Conan will generate that information even for packages that were not built with CMake and don't have a _FindXXX.cmake_ packaged.

If you want to used find cmake scripts already packaged in the Conan packages, probably you are looking for the behavior of cmake_paths generator or probably using `conan_paths` together with `conan_find_package`

Hope that makes sense

**Comment by Johnnyxy** [comment]
The ```cmake_find_package``` generator cannot modify the CMAKE_MODULE_PATH. This is by design as it generates files for dependencies and not for CMake invocation.

But this could be done by the [CMake build helper](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#cmake) at conanfile-time before ```cmake.configure()```. Then the dependency paths would be available to CMake as CMAKE_MODULE_PATH.

This would be a convenience functionality. But as it can be achieved quite easily by modifying the definitions manually with a two-liner there is no desperate need for a feature request for the CMAKE-build-helper. :)

```python
def build(self):
    cmake = CMake(self):
    deps_build_paths = [dep_build_path for dep in self.deps_cpp_info.deps for dep_build_path in self.deps_cpp_info[dep].build_paths]
    cmake.definitions["CMAKE_MODULE_PATH"] = ";".join([str(Path(x).as_posix()) for x in (cmake.definitions["CMAKE_MODULE_PATH"].split(";") + deps_build_paths)])
    cmake.configure()
```

I will close this topic as it is not really a bug.
Feel free to re-open if any clarification is needed.

**Comment by danimtb** [comment]
Thanks for understanding @Johnnyxy. I have included the issue in the build helpers refactor to consider it when the development of Conan 2.0, as sometimes it is not clear the things that are done in the generator and the ones done by the cmake helper.
