### ISSUE TITLE
TravisCi - ssl module not available

### ISSUE THREAD

**Issue by Phibedy** [conan-io/conan#485]
Somehow travisCi can't connect to https urls. Therefore it can't get packages from conan.io and it fails downloading zips from github. The installed python version should already have the ssl module. 
log: https://travis-ci.org/lms-org/lms/jobs/159850532

**Comment by lasote** [comment]
Hi @Phibedy, thanks for open the issue. I'll investigate. In the meantime you can use the pip package to install conan in travis if you want. I'll report ASAP.

**Comment by lasote** [comment]
Hi @Phibedy  I've updated the debian package, could you relaunch the build and tell me if it works? thanks

**Comment by Phibedy** [comment]
@lasote it works (see like https://travis-ci.org/lms-org/lms/jobs/160486400)
Is there a reason why not to use pip on travisCi?

**Comment by lasote** [comment]
We recommend always pip ;)

**Comment by Phibedy** [comment]
I just wondered because the docs use the deb package http://conanio.readthedocs.io/en/latest/integrations/travisci.html
Pull request: https://github.com/conan-io/docs/compare/master...Phibedy:patch-1

**Comment by memsharded** [comment]
Hi @Phibedy, you are right, the docs were using the deb package. I think your PR proposal is perfect, so I have opened and merged it! https://github.com/conan-io/docs/pull/73
Next time, you can open the PR directly :) Thanks very much for your contribution!
