### ISSUE TITLE
Conan uses  abc.ABCMeta only in Pyhton 2-way

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#4855]
Conan 1.13

I found that Conan uses Abstract classes this way:
```python
class Generator(object):
    __metaclass__ = ABCMeta
```
This syntax is for Python 2 and has no effect in Python 3. Pylint will not issue any warning if some derived class doesn't implement some of abstract methods.

Internet wisdom suggests using `@six.add_metaclass(abc.ABCMeta)` to be compatible.

**Comment by jgsogo** [comment]
It is not introducing a bug because the metaclass doesn't add any behavior, in fact, Conan is working with py2/3 exactly the same, but we should fix this for the next release.
