### ISSUE TITLE
[blog] Conan and Artifactory CE and blog posts

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#4856]
In the Conan blog post could we get a few words about Artifactory CE.

I am currently running version Artifactory CE version 6.3 and it now has a version 6.8.7 so I probably should upgrade. But I have no idea why I would want to upgrade.

Give your sibling product some love :)

**Comment by jgsogo** [comment]
Hi! Thanks for the suggestion. You are right, we should write a blog post about Artifactory when there are some updates that affect to Conan. In fact, we should write one for Artifactory 6.9 which includes support for package revisions.

**Comment by memsharded** [comment]
Closing this ticket as outdated.
