### ISSUE TITLE
Change subprocess.check_output calls

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4859]
With the new tool "check_output". To review also other different subprocess calls that capture the output.
The issue with check_output is that some shells are prepending messages to the output because of unexpected errors, or commands run right after launching a shell.

**Comment by jgsogo** [comment]
Tool implemented in https://github.com/conan-io/conan/pull/4854

**Comment by lasote** [comment]
Also when ready, we should consider to make it public (documented).
