### ISSUE TITLE
conan_server fails with 0.12.0

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#486]
Just upgraded from 0.10.1 to 0.12.0 on my Windows server. Now I'm unable to run conan_server anymore. The following traceback is shown:

![image](https://cloud.githubusercontent.com/assets/11735226/18512924/8dcc1c50-7a8b-11e6-96fa-b8d7a9e11bc7.png)

**Comment by memsharded** [comment]
Having a look right now, did you install conan with the installer or with pip?

**Comment by memsharded** [comment]
Ok, got it, another issue of the infrastructure upgrade. 
Please download again the installer from the download page and run it again, and try. Thanks!

**Comment by Blubbz0r** [comment]
New version works. Thanks
