### ISSUE TITLE
Application doesn't fail if conan.conf cacert_path doesn't exist

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#4862]
The problem is that exceptions in creation of ConanAPI.factory() are captured as migration errors and ommitted in output.

The unittests can't fail easily because this try-except is outside of the tested code, only used by the real final application.

So this fix might need manual testing until the architecture of the app and testing is improved (open issues: https://github.com/conan-io/conan/issues/4487, https://github.com/conan-io/conan/issues/4376)

**Comment by jgsogo** [comment]
This PR addresses this issue the easy way: just printing the exception message for non-expected errors: https://github.com/conan-io/conan/pull/4863. For sure a better approach would be to handle linked issues.

It changes:

```
    try:
        conan_api, cache, user_io = Conan.factory()
    except ConanException:  # Error migrating
        sys.exit(ERROR_MIGRATION)
```

for 

```
    try:
        conan_api, cache, user_io = Conan.factory()
    except ConanMigrationError:  # Error migrating
        sys.exit(ERROR_MIGRATION)
    except ConanException as e:
        sys.stderr.write("Error in Conan initialization: {}".format(e))
        sys.exit(ERROR_GENERAL)
```

**Comment by jgsogo** [comment]
Closed via https://github.com/conan-io/conan/pull/4863
