### ISSUE TITLE
Allow -u in conan test_package

### ISSUE THREAD

**Issue by raulbocanegra** [conan-io/conan#487]
Hi guys!

I found out that there is no way to update packages when using the command test_package.
Let me explain:
I have a package in my local .conan/data folder, let's say "my_package/1.0.0@demo/testing", now, on my conan server we have the same package, but updated (some recent changes, but same version).
And this is my case:
I have another package that depends on "my_package/1.0.0@demo/testing" which has its test_package folder and its build.py in order to be built with Conan Package Tools.
When I run the build.py, Conan Package Tools run the test_package command, that calls the install command, but without the "-u" option, so it builds the package but without installing the latest "my_package/1.0.0@demo/testing" that is on the server.
I think there is no way to set the "-u" option in the Conan Package Tools nor the test_package.
Right now I have a workaround, that is to delete "my_package/1.0.0@demo/testing" from my local ".conan/data" to force installing the updated dependency from server.
I can also do:
`conan export demo/testing && conan install my_package/1.0.0@demo/testing -u && conan test_package
`
But I prefer running the build.py.

I have also seen that [test_package](http://docs.conan.io/en/latest/reference/commands.html#conan-test-package) command also run the equivalent conan export and has an option to avoid it (--no-export). So I believe that a similar behaviour could be feasible with the "-u" option for the install part.

If you think this could be an interesting feature to have, I can send a PR.
I have been reviewing the code and it seems feasible to add that argument on the test_package method in [command.py](https://github.com/conan-io/conan/blob/develop/conans/client/command.py) to be used in the self._manager.install() call.

Thanks!

**Comment by memsharded** [comment]
Yes, I think that this update option to ``test_package`` could be harmless, maybe not very used, but if it is useful for you and doesn't harm other users, go ahead! Yes, the implementation should be easy, thanks for offer to contribute.

A different feature would be to have conan-package-tools use it, that feature request should go to its github repo.

**Comment by raulbocanegra** [comment]
Well, I think that adding the -u option in the args parameter of conan-package-tools would propagate the option to the conan install, so making this option available for test_package is enough if I'm not wrong.

**Comment by memsharded** [comment]
Yes, that is true, you are right! :)

**Comment by memsharded** [comment]
This was fixed in https://github.com/conan-io/conan/pull/491, right?

**Comment by raulbocanegra** [comment]
Yep,
I forgot to close the issue, sorry! :-)

**Comment by memsharded** [comment]
Hi Raul,

Just a minor detail: it is fine to leave the issue open :) :)

We are adding label "fixed" when it has been already implemented, but not yet released, so other users are aware that they cannot use it if not running from sources. Then, when it is released (this will be in conan 0.13), the issue can be closed.

**Comment by memsharded** [comment]
Released in conan 0.13.1
