### ISSUE TITLE
conan suddenly requires user authentication for accessing conan server

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#4871]
conan client: 1.14.0 (Windows)
conan server: 1.0.2 (Windows)

For over a year, we have a conan server 1.0.2 running without any changes to its configuration. 
It has the following read permissions, i.e. everybody should be able to download packages:

    [read_permissions]
    # opencv/1.2.3@lasote/testing: default_user default_user2
    # By default all users can read all blocks
    */*@*/*: *

Since installing conan 1.14.0 (or maybe 1.13.x), the client suddenly starts asking for credentials to access the server when using ``conan install``.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Verified, this is a bug. We will try to release a fix asap, thanks very much for reporting.

**Comment by lasote** [comment]
It has been merged to the 1.14.1 release and hopefully released during the day. Thanks for reporting! :)
