### ISSUE TITLE
cppstd as a subsetting

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4873]
We considered better to have the cppstd as a subsetting of every compiler:

- If you don't specify the -s compiler.cppstd=XXX it won't change anything, because will come with a None default value.
- We won't break anything, the global setting will be kept, but deprecated (comment at settings.yml and docs).
- So any recipe could receive the subsetting and compile with a different version of the language automatically.
- The reasons to do a first level setting was to not generate new binary IDS for C libraries that doesn't remove the subsetting. We consider more important to be "injectable" at any recipe.
- Conan will fail if both are specified.
- Conan will try internally to manage the value of the new one, copying from the old one if possible (to ease the code and future deprecation of the global setting)
- Each compiler will have their own values, it has a lot of sense.

**Comment by jgsogo** [comment]
Q: Although each compiler will have its own flags to set the standard, I wonder if we should add those different names in our `settings.yml` or it is better to set `None, 98, 11, 14, 17, 20` for all the compilers and make the translation inside Conan code.

**Comment by lasote** [comment]
We don't have to introduce the flag name in the settings. But values that make sense for the compiler. For instance, the "gnu" ones for VS doesn't make sense. So yes, translation still will happen. I would use the same names as today, but removing the non-sense ones, unless you find that maybe for vs other values makes more sense.

**Comment by jgsogo** [comment]
I was thinking about the way CMake handles it through the [`CXX_STANDARD` variable](https://cmake.org/cmake/help/v3.14/prop_tgt/CXX_STANDARD.html), they use the same in the `CMakeLists.txt` for all the generators. And then, CMake has a different flag, `CXX_EXTENSIONS` to handle compiler specific extensions.

Let's list all the valid values for each generator and see how it looks like.

**Comment by Lyberta** [comment]
I think the better way would be to have ISO version in global and any compiler extensions such as `gnu` as compiler subsetting. The idea is that ISO conforming code should compile on any compiler.

**Comment by memsharded** [comment]
@Lyberta @uilianries 

> I think the better way would be to have ISO version in global and any compiler extensions such as gnu as compiler subsetting. The idea is that ISO conforming code should compile on any compiler.

Having 2 different sources of definition for the ``cppstd`` would be problematic to handle and confusing for users. Furthermore, there are compilers that do not fully adhere to the ISO version, and that would be another source of bugs and problems, e.g. VS with std=11: https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2019

So we decided to specify them for each compiler, a bit of duplication, but nicely explicit, robust and fully customizable for each compiler, with all their quirks.
