### ISSUE TITLE
public tools.Version class helper

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4875]
- With a comparator that manages also strings: `Version("1.2") > "1.1"`
- With methods "major", "minor", "patch" returning a string with that component.

**Comment by uilianries** [comment]
Could we also support `SettingsItem`?

It would be nice supporting `Version(self.settings.compiler.version)`. For now we need to use `.value`

**Comment by memsharded** [comment]
That should be supported easily, just forcing conversion of inputs to string, as settings have those conversion defined.
