### ISSUE TITLE
[suggestion] Support .gz files in tools.get()

### ISSUE THREAD

**Issue by nkshigeru** [conan-io/conan#4876]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I suggest that `tools.get()` supports .gz files in the same way as .tar.gz.

I want to download a gzipped patch and apply it.
https://github.com/nkshigeru/conan-libpng/blob/cdebdf4ae4a7b33871b6080ac13927b1036bdd41/conanfile.py#L45-L53

`tools.get()` is a very useful function but it does not support .gz file.
So I need to use low level functions.
```
tools.download("http://example.com/example.patch.gz", "example.patch.gz")
tools.check_sha1("example.patch.gz", hash)
with gzip.open("example.patch.gz", "rb") as f:
    patch = f.read().decode()
    tools.patch(patch_string=patch)
```
It would be great if I could write as below.
```
tools.get("http://example.com/example.patch.gz", sha1=hash)
# we get example.patch
tools.patch(patch_file="example.path")
```

**Comment by memsharded** [comment]
Submitted a PR to implement this in https://github.com/conan-io/conan/pull/4883
