### ISSUE TITLE
[question] How to cope with situation where one needs to run a script before building

### ISSUE THREAD

**Issue by chyacinth** [conan-io/conan#4881]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi, I am new to Conan and am trying to develop a library using Conan 1.14.0. My library depends on a cmake-based library [hmlp](https://github.com/ChenhanYu/hmlp). Since that hmlp library does not have conan support, I am thinking of writing a conan recipe for it. The problem is that I need to run a script provided by that library to set all the environment variables before I can build the hmlp library with cmake. I may also need to manually change that script based on different compiler, os, architecture, etc. So I wonder what will be the best way to cope with such situation if I want to make that library a conan package?

After reading the document I came up with 2 ways:
1. Modify the script and run it in the source() function of conanfile.py
2. Change all the environment variable in CMakeList.txt to cmake cached variable or cmake option and then interpret the script into python code in the conanfile.py. (like what conan-opencv does, cmake.definitions['xxx']=xxx).

Which one should be the best practice here, or is there a better way to cope with such situation? Thanks a lot.

**Comment by Johnnyxy** [comment]
Hi there,
if you need to set custom environment variables for a specific code block in Python you can use [environment_append](https://docs.conan.io/en/latest/reference/tools.html#tools-environment-append) together with [self.run](https://docs.conan.io/en/latest/reference/conanfile/other.html#running-commands) for that.

```python
def build(self):
    vars = {"envvar1": "value1"} # default values

    # settings depending values
    if (self.settings.compiler == "Visual Studio"):
        vars["compiler"] = "msvc"
    if (self.options.shared):
        vars["build_it_shared"] = 1

    with tools.environment_append(vars):
        # execute the following with the given environment
        self.run("your_exe.exe")
```

If you just need the environment variables for your CMake build then replace the ```self.run``` with the [CMake build helper](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#cmake).
```python
def build(self):
    vars = {"envvar1": "value1"} # default values

    # settings depending values
    if (self.settings.compiler == "Visual Studio"):
        vars["compiler"] = "msvc"
    if (self.options.shared):
        vars["build_it_shared"] = 1

    with tools.environment_append(vars):
        # execute the following with the given environment
        cmake = CMake(self);
        cmake.configure()
        cmake.build()
```

If you just need to set CMake variables then do it with the [CMake build helper configure](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#configure) function.
```python
def build(self):
    vars = {"envvar1": "value1"} # default values

    # settings depending values
    if (self.settings.compiler == "Visual Studio"):
        vars["compiler"] = "msvc"
    if (self.options.shared):
        vars["build_it_shared"] = 1

    # execute the following with the given environment
    cmake = CMake(self);
    cmake.configure(defs=vars)
    cmake.build()
```

Of course you could combine the last two approaches:
```python
def build(self):
    vars = {"envvar1": "value1"} # default values

    # settings dependent values
    vars2 = {}
    if (self.settings.compiler == "Visual Studio"):
        vars2["compiler"] = "msvc"
    if (self.options.shared):
        vars2["build_it_shared"] = 1

    with tools.environment_append(vars):
        # execute the following with the given environment
        cmake = CMake(self);
        cmake.configure(defs=vars2)
        cmake.build()
```

**Comment by chyacinth** [comment]
> Hi there,
> if you need to set custom environment variables for a specific code block in Python you can use [environment_append](https://docs.conan.io/en/latest/reference/tools.html#tools-environment-append) together with [self.run](https://docs.conan.io/en/latest/reference/conanfile/other.html#running-commands) for that.
> 
> ```python
> def build(self):
>     vars = {"envvar1": "value1"} # default values
> 
>     # settings depending values
>     if (self.settings.compiler == "Visual Studio"):
>         vars["compiler"] = "msvc"
>     if (self.options.shared):
>         vars["build_it_shared"] = 1
> 
>     with tools.environment_append(vars):
>         # execute the following with the given environment
>         self.run("your_exe.exe")
> ```
> 
> If you just need the environment variables for your CMake build then replace the `self.run` with the [CMake build helper](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#cmake).
> 
> ```python
> def build(self):
>     vars = {"envvar1": "value1"} # default values
> 
>     # settings depending values
>     if (self.settings.compiler == "Visual Studio"):
>         vars["compiler"] = "msvc"
>     if (self.options.shared):
>         vars["build_it_shared"] = 1
> 
>     with tools.environment_append(vars):
>         # execute the following with the given environment
>         cmake = CMake(self);
>         cmake.configure()
>         cmake.build()
> ```
> 
> If you just need to set CMake variables then do it with the [CMake build helper configure](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#configure) function.
> 
> ```python
> def build(self):
>     vars = {"envvar1": "value1"} # default values
> 
>     # settings depending values
>     if (self.settings.compiler == "Visual Studio"):
>         vars["compiler"] = "msvc"
>     if (self.options.shared):
>         vars["build_it_shared"] = 1
> 
>     # execute the following with the given environment
>     cmake = CMake(self);
>     cmake.configure(defs=vars)
>     cmake.build()
> ```
> 
> Of course you could combine the last two approaches:
> 
> ```python
> def build(self):
>     vars = {"envvar1": "value1"} # default values
> 
>     # settings dependent values
>     vars2 = {}
>     if (self.settings.compiler == "Visual Studio"):
>         vars2["compiler"] = "msvc"
>     if (self.options.shared):
>         vars2["build_it_shared"] = 1
> 
>     with tools.environment_append(vars):
>         # execute the following with the given environment
>         cmake = CMake(self);
>         cmake.configure(defs=vars2)
>         cmake.build()
> ```

Thanks! 
[**@Johnnyxy**](https://github.com/Johnnyxy) commented on [Mar 30, 2019, 8:37 PM CDT](https://github.com/conan-io/conan/issues/4881#issuecomment-478303898 "2019-03-31T01:37:31Z - Replied by Github Reply Comments"):
> Hi there,  
> if you need to set custom environment variables for a specific code block in Python you can use [environment\_append](https://docs.conan.io/en/latest/reference/tools.html#tools-environment-append) together with [self.run](https://docs.conan.io/en/latest/reference/conanfile/other.html#running-commands) for that.
> 
> ```python
> def build(self):
>     vars = {"envvar1": "value1"} # default values
> 
>     # settings depending values
>     if (self.settings.compiler == "Visual Studio"):
>         vars["compiler"] = "msvc"
>     if (self.options.shared):
>         vars["build_it_shared"] = 1
> 
>     with tools.environment_append(vars):
>         # execute the following with the given environment
>         self.run("your_exe.exe")
> ```
> 
> If you just need the environment variables for your CMake build then replace the `self.run` with the [CMake build helper](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#cmake).
> 
> ```python
> def build(self):
>     vars = {"envvar1": "value1"} # default values
> 
>     # settings depending values
>     if (self.settings.compiler == "Visual Studio"):
>         vars["compiler"] = "msvc"
>     if (self.options.shared):
>         vars["build_it_shared"] = 1
> 
>     with tools.environment_append(vars):
>         # execute the following with the given environment
>         cmake = CMake(self);
>         cmake.configure()
>         cmake.build()
> ```
> 
> If you just need to set CMake variables then do it with the [CMake build helper configure](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#configure) function.
> 
> ```python
> def build(self):
>     vars = {"envvar1": "value1"} # default values
> 
>     # settings depending values
>     if (self.settings.compiler == "Visual Studio"):
>         vars["compiler"] = "msvc"
>     if (self.options.shared):
>         vars["build_it_shared"] = 1
> 
>     # execute the following with the given environment
>     cmake = CMake(self);
>     cmake.configure(defs=vars)
>     cmake.build()
> ```
> 
> Of course you could combine the last two approaches:
> 
> ```python
> def build(self):
>     vars = {"envvar1": "value1"} # default values
> 
>     # settings dependent values
>     vars2 = {}
>     if (self.settings.compiler == "Visual Studio"):
>         vars2["compiler"] = "msvc"
>     if (self.options.shared):
>         vars2["build_it_shared"] = 1
> 
>     with tools.environment_append(vars):
>         # execute the following with the given environment
>         cmake = CMake(self);
>         cmake.configure(defs=vars2)
>         cmake.build()
> ```

Thanks! tools.environment_append() is pretty cool and solves my problem. I didn't notice that function beforehand. Maybe the document can make a reference to this function in the [Environment Variables Chapter](https://docs.conan.io/en/latest/mastering/envvars.html)? It will be pretty helpful.

**Comment by Johnnyxy** [comment]
If you need to execute a foreign process that sets those variables then you cannot use the environment_append. Because each invocation of a process gets their own encapsulated environment. 

To do what you want you have to do it like this:
```python
def build(self):
    cmake = CMake(self)
    if (self.settings.os == "Linux"):
        self.run('source script.sh && cmake ' + cmake.command_line + ' && cmake "' + self.source_folder + '" --build all
```

**Comment by chyacinth** [comment]
[**@Johnnyxy**](https://github.com/Johnnyxy) commented on [Mar 31, 2019, 7:34 AM CDT](https://github.com/conan-io/conan/issues/4881#issuecomment-478337834 "2019-03-31T12:34:02Z - Replied by Github Reply Comments"):
> If you need to execute a foreign process that sets those variables then you cannot use the environment\_append. Because each invocation of a process from Conan gets its own encapsulated environment.
> 
> To do what you want you have to do it like this:
> 
> ```python
> def build(self):
>     cmake = CMake(self)
>     if (self.settings.os == "Linux"):
>         self.run('source script.sh && cmake ' + cmake.command_line + ' && cmake "' + self.source_folder + '" --build all')
> ```

Yes, that works. Thank you!

**Comment by memsharded** [comment]
Thanks @Johnnyxy for the great support!
