### ISSUE TITLE
Allow to define default settings as Environment variables

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#489]
This way, the tool packages like mingw could declare the right compiler overriding the compiler, compiler.version, compiler.libcxx

**Comment by memsharded** [comment]
I think this could be a bit confusing/obscure for users, difficult to debug... Maybe I don't get the motivation behind it, but if it is what I think, I'd say that settings "profiles" is the way to go: predefined named sets of settings that could be used in commands.

**Comment by lasote** [comment]
The profiles is a good idea, but, why is it obscure? When you activate a python virtualenv the "compiler" (interpreter) is changed to the virtualenv one. Is this obscure too?
Is not an urgent or important or killing feature, but if I'm using windows with Visual and then I use the mingw installer to activate a virtualenv, why conan still thinks that I'm using Visual Studio? How could it be confusing if I'm activating the MinGW compiler virtualenv?

**Comment by monsdar** [comment]
I haven't used pythons virtualenv, but isn't it the case that I explicitly need to activate these environments? That means the user knows what he is doing. In case of env vars the user is not in control. Everything can set env vars, the user mostly does not know that they're getting set. It is easy to make mistakes that way.

I like the idea of different profiles. The endgame could look like the following:
* At the first start conan finds my possible compiler settings (like it is now) and create different profiles like VS15_32bit, VS15_64bit, VS10_32bit and VS10_64bit. It would chose a profile as the default profile
* I can compile with a specific profile by an extra parameter `conan install --profile VS15_32bit`
* There could be a command `conan profile` that allows me to manage my profiles. `conan profile update` automatically finds new profiles for compilers I installed
* The command `conan profile exists VS15_64bit` will return with 0 or 1 to allow tool packages like MinGW to check if a certain profile exists (or if it is needed for them to create a new profile)
* Profiles are simply txt-configurations in the .conan directory. That way they're easy to backup, easy to modify, easy to parse for other applications, ...

If tool packages like MinGW are able to set environment variables specifically for conan they instead could provide and activate a specific profile for conan.

**Comment by memsharded** [comment]
Yes, exactly that is what I thin about the env vars. And yes, that profile is basically what I have in mind too. Probably also be able to add compiler paths (like CC and CXX in linux, that would help to manage different compilers, versions and clang too)

**Comment by lasote** [comment]
From your comments the thing I get clear is that you both like the profiles feature... me too! let's discuss in his own issue. But I think they are different things.

Conan virtual envs does mostly the same than Python virtual envs.The user activate explicitly with an script a virtual environment. So yes, the user has the control about what is activating. A virtual environment has environment variables and it's called virtual because you can activate and deactivate and handle it locally. So, why could be set an environment variable in a virtual environment obscure? Why setting a profile is not obscure but a setting is obscure? It's not the same? I don't get it.

**Comment by monsdar** [comment]
From your first message it looked like you wanted to do something like the following:

```
set COMPILER=Visual Studio
set COMPILERVERSION=12
conan install Foo/1.0@user/testing

# conan proceeds to install the component, uses compiler and compiler.version from the env vars
```

If something like the above is put into a script the user does not know that env vars are used. He would simply call `doStuff.bat` and hope for the best. Having some kind of virtual envs would probably be a different case, the user has to activate them himself.

Perhaps the issue should be renamed then. It's not about environment variables but about conan virtual environments (???)

**Comment by lasote** [comment]
It's not exactly like that, the `<doStuff.bat>` or `<activate.bat>` just sets the env variables. Then you can call conan install with the parameters that you want. But if you don't specify a setting with -s, instead of take it from your conan.conf could look first if an ENV variable is defined, for example,  your default compiler, compiler version etc. (Or even a profile, but in the environment)

The title doesn't mention conan virtual environments because the first step will be allow assign default settings with ENV variables, but yes, it's related.

The motivation is conan virtual environment, When I use mingw_installer package:
    
1. I install a mingw with ming_installer package that generates an `activate.bat` script that puts in the path my compiler (and define some other env variables to make it work)
2. I activate the virtual environment running "activate.bat"
3. Then I want to compile another package using my new mingw compiler, so I call `conan install command`. But it's a little strange to need to specify `-s compiler=gcc -s compiler.version=4.9 -s compiler.libcxx=libc++11` when the migw_installer itself knows all the information about what compiler has "installed" and "linked" in my virtual environment. 

Then I wondered why the virutal environment itself can't set the right default settings (not force the settings, just change temporarily the defaulted in conan.conf).

**Comment by memsharded** [comment]
I think this feature has already been addressed with:
- Profiles
- Specific settings per individual package
- Environment variables in command line and in profiles

Can it be closed @lasote?

**Comment by lasote** [comment]
It's less necessary but the use case is still there unresolved: Reading the default settings from env variables.
