### ISSUE TITLE
Best way to call a conan recipie from another recipie

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#4891]
Hi all,

This is a bit strange but due to some issues I'm creating a package from some git source where this git source have much more things but i need one small part that i can get executing `conan install <path to specific conanfile.py>` on the git code. So my package will do a git clone and try to call only that specific part.

So in my main recipie i call something like this:
```
self.run("conan install <path to specific conanfile.py>")
... do some things...
self.run("conan build <path>")
```

Two questions:
1) is this the best way to do this? or exists in conan tools/functionality to call another conan instalation?
2) if this is the only way, how can i access something like `self.deps_cpp_info["libA"].lib_paths` where libA is a requirement of the second conanfile.py and not of this first one... but i need to add the lib path to a specific variable (can not use virtualenv* functionality... or i can, but i need to parse them to retrieve only the libA information)

Best regards,
Nuno

**Comment by uilianries** [comment]
Hi @nesc1 !

> is this the best way to do this? or exists in conan tools/functionality to call another conan instalation?

If you need to re-use some parts of another recipe, I would say the best option is [Python Requires](https://docs.conan.io/en/latest/extending/python_requires.html#python-requires).

But I see a close dependency between two dependencies, so you could add the first one as requirement instead, don't you?

> if this is the only way, how can i access something like self.deps_cpp_info["libA"].lib_paths where libA is a requirement of the second conanfile.py and not of this first one... but i need to add the lib path to a specific variable (can not use virtualenv* functionality... or i can, but i need to parse them to retrieve only the libA information)

You can't check, because you don't have the dependencies graph formulated according your recipes. What you could do is running `conan info --paths`, but it's totally ugly.

**Comment by nesc1** [comment]
Hi @uilianries , thanks for the reply.

About use as requirement.. i can't because it is not a package, is a cmake project with a conanfile.py used to install/build the cmake project dependencies. So what i do is to call the `conan install <project conanfile.py>` and then call the `cmake --build .` of the project... so i can't use as a requirement of my recipie.

I will take a look at the `Python Requires`, thanks

For now i open the generated "conanbuildinfo.txt" and extract what i want... it was the simplest way that i can find.

(again `conan info --paths` can not be used because it is not a package)

Best regards.
