### ISSUE TITLE
Get rid of indirect requirements so that binary package id doesn't change

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#4893]
Consider following use-case: I build a package which requires a number of other packages to run tests, but otherwise not needed.
When developing they should come as build requirements, but I want to sometimes run such tests separately on CI.
To encapsulate this knowledge I thought about adding option `testing` which will add those packages into requirements but it shouldn't affect binary ID.
Something like this:
```
test_requirements = (
    "pandas/0.22.0@external/master",
    "plotly/2.5.1@nasdaq/stable",
    "etcd/3.2.26@external/master",
)

class PkgConan(ConanFile):
    options = {
        "testing": [True, False],  # Set to True if consuming package for running test.
    }

    def requirements(self):
        if self.options.testing:
            for req in test_requirements:
                self.requires(req)

    def build_requirements(self):
        if not self.options.testing:
            for req in test_requirements:
                self.build_requires(req)

    def package_id(self):
        # option "testing" is for consuming in different ways
        # it should not affect the binary hash
        for pref in self.info.requires.refs():
            if str(pref.ref) in test_requirements:
                print("Removing {}".format(pref.ref.name))
                self.info.requires.remove(pref.ref.name)

        del self.info.options.testing
```

However when those packages (like pandas) have transitive dependencies (numpy) thei remain in `self.info.options._reqs_options`

**Comment by ytimenkov** [comment]
Well, in my case if I don't have requirements by default I can just do `self.info.requires.clear()`.

**Comment by danimtb** [comment]
Hi @ytimenkov,

I have tried to reproduce the issue above and you are right. Currently we don't have way in recipes to remove a dependency and the transitive dependencies that dependency brings.

You can do some hacks around the pacakge_id() but there is not enough inromation in the combination of ``self.requires``, ``self.deps_cpp_info`` and ``self.info.requires``.

I think we will need to investigate this and maybe propose a way to get access not only to requirements but to the actual graph information.

Or maybe it is just a matter of removing the transitive dependencies' options once the initial dependency is removed...

**Comment by ytimenkov** [comment]
Good to know that it's not a total nonsense :smile:  As I wrote in a simple case removing all dependencies works, and maybe I won't have more complex case... I actually was surprised that it's options which affect the hash and not requirements themselves, however it means no simple fix since existing binary package ids will creep...

> You can do some hacks around the pacakge_id()

That's what I did before I gave up :laughing:

**Comment by danimtb** [comment]
yeah, we have to look into this together with other issues related to the graph and requirements to see if makes sense. But it could also be an easy "fix" in the case of options although probably braking... We'll see

Thanks!

**Comment by memsharded** [comment]
The binary model has changed a lot in Conan 2.0, and indirect requirements are more likely to be discarded when they actually do not affect the downstream consumers. I am closing this ticket as outdated, and if necessary please open new tickets reporting against Conan 2.0, thanks!
