### ISSUE TITLE
multiple generator usage from client perspective

### ISSUE THREAD

**Issue by Milerius** [conan-io/conan#4899]
Hello i have a repository that support 3 build systems: bake,CMake, and Meson

I want to use conan for package management:

```
[requires]
sfml/2.5.1@bincrafters/stable
entt/3.x.y-WIP@skypjack/stable
asio/1.13.0@bincrafters/stable
jsonformoderncpp/3.6.1@vthiery/stable

[generators]
cmake ##! I would like here to specify for example : "cmake, meson, pkgtools"
```

And choose with command line which generator use for example

```bash
##! CMake 
mkdir build
cd build
conan install ../
conan build --generator="cmake"

##! Meson
conan build --generator="meson" "build_directory"  
```

For the moment i don't figure out how to manage multiple generators etc

repository: https://github.com/Milerius/nephtys

Thank's a lot for your help

**Comment by Johnnyxy** [comment]
You can specify multiple generators.
```ini
[generators]
cmake
pkg_config
```

Normally each generator creates a file for its usage that does not interfere with other generator's files.
So you can specify them, install the dependencies with ```conan install``` and use the build system of your choice afterwards.

As an alternative you could specify no generators at all in the ```conanfile``` and set the generator to use as argument on the command line of [conan install](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#conan-install).
```
conan install -g cmake ...
```

**Comment by Milerius** [comment]
ok i got it, thank's a lot, is not obvious according to the doc
