### ISSUE TITLE
Make compiler_args to generate two additional files for compile and link flags

### ISSUE THREAD

**Issue by db4** [conan-io/conan#4905]
It would be great if `compiler_args` generator additionally generated separate files for compile and link flags, say `conanbuildinfo_cflags.args` and `conanbuildinfo_link_flags.args` (or whatever you like). I'm trying to integrate conan-provided libs into a build system that uses the following rules to compile c sources:

```
(library
  (public_name some_lib_name)
  (c_names file1 file2)
  (c_flags ...)
  (c_library_flags ...)
)
```
My first try was to use `compiler_args` generator:
```
(library
  (public_name some_lib_name)
  (c_names file1 file2)
  (c_flags @conanbuildinfo.args))
  (c_library_flags @conanbuildinfo.args))
)
```
Unfortunately in case of `Visual Studio` the build system translates it into
```
cl -c @conanbuildinfo.args file1_without_ext.c
```
that ends up with a compile error: `conanbuildinfo.args` contains `-link` option inside and everything after it including `file1_without_ext.c` is passed to linker, not compiler.

Another idea was to create a custom generator. Unfortunately, to duplicate `compiler_args` functionality I would need `format_include_paths`, `format_libraries` etc. defined in `client/build/compiler_flags.py` which is not exported as a public API. So making `compiler_args` to generate two additional files seems to be the simplest option.

**Comment by jgsogo** [comment]
Hi! I agree with you that the best way to go is by writing another generator, maybe we need more people demanding it in order to include it in Conan, but we can help you to write it. 
**Which compilers could benefit from this generator?**

----

In case you need it right now, you can consider a different approach and rely only on documented and stable output: you can subclass your custom generator from `CompilerArgsGenerator` one and then work over our output to generate the files you need (just a draft):

```python
class YourGenerator(CompilerArgsGenerator):

    @property
    def filename(self):
         pass

    @property
    def content(self):
         args_content = super(YourGenerator, self).content
         
         # do something to get c_flags and link_flags from 
         # the content returned from CompilerArgsGenerator
         c_flags, link_flags = ...
         return {"conanbuildinfo_cflags.args": c_flags,
                 "conanbuildinfo_link_flags.args": link_flags }
```

**Comment by db4** [comment]
> Hi! I agree with you that the best way to go is by writing another generator, maybe we need more people demanding it in order to include it in Conan, but we can help you to write it.
Which compilers could benefit from this generator?

Well, I'm trying to integrate conan with dune: [A composable build system for OCaml](https://dune.build). It may be not very popular demand :-)

Thanks for the hint but
> do something to get c_flags and link_flags from 
the content returned from CompilerArgsGenerator

is a problem. How to separate compile flags from link flags in the content? Well, for MSVC I could try to find `-link` and assume everything after it are link options, But I would like to leave all compiler specifics to conan...

**Comment by jgsogo** [comment]
Hi, I wasn't aware of the Dune build system, so this issue could be a **feature request: provide a generator for Dune**. Shall I open the issue?

Meanwhile, you can build your own generator on top of the JSON one, I think it could be the easiest one to parse and the most _fine-grained_.

**Comment by db4** [comment]
> Hi, I wasn't aware of the Dune build system, so this issue could be a **feature request: provide a generator for Dune.** Shall I open the issue?

Maybe, but this is a very special case. dune is a build system for another language (OCaml) and I'm not sure a generator for it worth efforts of conan.io developers. You cannot support all languages/build systems in the world. More generic approach is needed here IMHO.

> Meanwhile, you can build your own generator on top of the JSON one, I think it could be the easiest one to parse and the most fine-grained.

I'm afraid I cannot without knowing options for a specific compiler (the thing I would like to avoid). Say, JSON generator provides
```json
{
  "dependencies": [
    {
      "lib_paths": [
"D:\\.conan\\data\\sqlite3\\3.27.2\\bincrafters\\stable\\package\\34b70e4f7ca15a88b9c771a2da37431ceebd76fa\\lib"
      ],
      "libs": [
        "sqlite3"
      ]
    }
  ]
}
```
But I need 
```
-link -LIBPATH:D:\.conan\data\sqlite3\3.27.2\bincrafters\stable\package\34b70e4f7ca15a88b9c771a2da37431ceebd76fa\lib sqlite3.lib`
```

to pass to dune. Options `-link`, `-LIBPATH:` for MSVC (as well as `-L`, `-l` for gcc) is compiler-specific knowledge (implemented in `format_include_paths`, `format_libraries` etc. conan functions). That's what I wouldn't like to duplicate myself.

**Comment by db4** [comment]
Well, I finally realized that splitting `conanbuildinfo.args` into two separate files won't help me with dune generator; I should make it the standard way (subclass from Generator class and `if self.compiler == ...` confitionals ). So if the separate `conanbuildinfo_c_flags.args`, ` conanbuildinfo_c_link_flags.args` is useless addition from your point of view, the issue can be closed.

**Comment by jgsogo** [comment]
Hi! I think that right now there is no use-case to maintain another generator, I'm closing the issue.

Thanks!
