### ISSUE TITLE
Retry upload for error '500' if the user is requesting it (concurrent uploading)

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#4907]
To help us debug your issue please explain:

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I try to upload a package up to our Artifactory server. We are building for multiple compiler on multiple slaves. Sometimes it happens, that they upload nearly at the same time slot.
I thought, that with "--force --retry 5 --retry-wait 10" it would try again to upload again, when this is happening. Unluckily it stops with the first exception happening.

[hil_drv_cifx] $ cmd.exe /C "conan upload "*" --all --force --retry 5 --retry-wait 10 -r 9d380644-252b-44ff-b4af-feded185890d --confirm && exit %%ERRORLEVEL%%"

ERROR: 
Error uploading file: conanmanifest.txt, 'b'{\r\n  "errors" : [ {\r\n    "status" : 500,\r\n    "message" : "Failed to persist file with sha1: 3093033974f36098596e33acf477de5a9e8ddd87"\r\n  } ]\r\n}''

I am using Conan 1.13.1 on multiple Windows & Linux Jenkins Slaves (all python3.6). We are using the Artifactory plugin for Jenkins (newest version, just some days old)

**Comment by jgsogo** [comment]
It looks like a concurrency issue in Artifactory, those clients must be creating/deleting files and something goes wrong in Artifactory trying to regenerate indexes. Probably it is safe for Artifactory to fail, and maybe we in Conan should handle this `error 500` and keep retrying as you have specified it in the command line (I have to check the source code to know if we are doing something different with the `500` and the retries).

Thanks for reporting

**Comment by jgsogo** [comment]
Yes, having a look at the source code, retries are only performed for exceptions `NotFoundException` and `ConanException`, which in turn are only raised during the upload process for errors `401` and `403` or an exception thrown from `requests.put`. If an error `500` is returned, then it is handled in `RestV*Methods::_upload_files` (outside the retries). 

IMO we should retry always if the user is requesting it, it would be different for automatic retries.

**Comment by uilianries** [comment]
It sounds good, since we have some errors when uploading packages to Bintray.

**Comment by climblinne** [comment]
I tried to bypass the problem by writing a script in Jenkins (see https://github.com/jfrog/jenkins-artifactory-plugin/issues/133), but got another problem inside the Artifactory plugin.

**Comment by memsharded** [comment]
I am having a look at https://github.com/conan-io/conan/pull/4984#pullrequestreview-230365145, @jgsogo, and I fail to see how a 500 doesn't raise a ConanException. Maybe trying to contribute some test to that PR would help.

**Comment by jgsogo** [comment]
@memsharded, here you have some tests: https://github.com/conan-io/conan/commit/e24f3d5807b0f1f3c523149601017c1d757926c9. The last one with the error `500` doesn't do any retry.

The reason is because of the following snippet, it only raises for `401`, `403` or an exception from `self.requester.put` (if no raise, then no retry):

```python
    def _upload_file(self, url, data,  headers, auth):
        try:
            response = self.requester.put(url, data=data, verify=self.verify,
                                          headers=headers, auth=auth)
            if response.status_code == 401:
                raise AuthenticationException(response.content)

            if response.status_code == 403:
                if auth.token is None:
                    raise AuthenticationException(response.content)
                raise ForbiddenException(response.content)
        except ConanException:
            raise
        except Exception as exc:
            raise ConanException(exc)

        return response
```

I would suggest using `response.raise_for_status()` (I'm not sure if we will always use `requests` module) (or check for the `ok`) and then catch the `HttpError` to write the message and handle the number of retries.

**Comment by climblinne** [comment]
I updated the PR and integrated the tests
