### ISSUE TITLE
Virtualrunenv generator how to hide lib from one package

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#4908]
Hi simple question, i have a project which requires libA, libB and libC, libC is only required because it has binary tools and this binary tools link with libC/package/xxxx/lib's using RPATH=$ORIGIN/../lib that they are exclusive to libC tools, i don't want them in any other place.

This all works great but when i use the virtualrunenv on my project i only want to receive the PATH to the bin from libC and not the lib folder from libC... 

The question is there any way of preventing that virtualrunenv append to LD_LIBRARY_PATH the lib path of libC? if yes how?

Thanks

**Comment by nesc1** [comment]
this is a dummy question right? don't create the lib folder or move the lib folder to another location like for example inside bin folder.... right?

**Comment by lasote** [comment]
You can adjust the `cppinfo` to remove any library directory (by default there is the "lib" one) in the package of library C:
Something like:

```
def package_info(self):
    self.cppinfo.libdirs = []
```

https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info

**Comment by nesc1** [comment]
hi @lasote thanks for your reply... but you mean `self.cpp_info.libdirst` right and not cppinfo?

**Comment by lasote** [comment]
right, that was a typo! thanks
