### ISSUE TITLE
Conan 1.14 breaks clang-7

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#4909]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.14 is not playing well with clang-7 on Ubuntu 16.04

Things worked with conan 1.13 and clang-6:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/512902311#L892

But Travis-CI forced an upgrade because dependencies for clang-6 were broken:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/515036646#L183

Minimal autodetection via profile doesn’t work:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/515810591#L727

Explicitly setting the version in a profile doesn’t work:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/515575637#L733

**Comment by lasote** [comment]
Hi, Adam nice to talk to you! From [here](https://travis-ci.org/acgetchell/CDT-plusplus/jobs/515810591#L727) I deduce that `clang-7.0` is not an executable or not in the path, did you tried to use just `clang` and `clang++` as the name set in the `CC` and `CXX`?   From your print it looks like it is enough to reach clang 7:

```
$ clang --version
clang version 7.0.0 (tags/RELEASE_700/final)
```

**Comment by acgetchell** [comment]
Yes, setting `"$CXX" == "clang++"` works.
