### ISSUE TITLE
Conan 1.14 does not detect MPFR

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#4910]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.14 does not detect MPFR on Ubuntu 16.04 with gcc-8:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/515810593#L1118

Conan 1.13 was able to do so:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/512902312#L1298

Conan 1.13 built with Ninja, but Conan 1.14 uses `make` as latest Homebrew broke Ninja:

https://github.com/Homebrew/linuxbrew-core/issues/12430

**Comment by lasote** [comment]
I'm not sure if Conan has changed something for that to happen. Have you tried to force the install of Conan 1.13 to verify that it still works? I don't know if it could be more related with a system package or a change in a conan package maybe.

**Comment by acgetchell** [comment]
I'm not sure how I resolved it, but this isn't a problem anymore.
