### ISSUE TITLE
Multi reference build order for CI

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#4912]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Using the `conan info -bo` and the reference to the update package Conan generates a json file with an ordered list of packages that should be rebuilt in the CI. Recently I have faced a problem where multiple packages are updated and I have to process them sequentially. Having more than 40 Conan packages makes this process very long. I am looking for a way to pass multiple references to `conan info -bo` and get an ordered list of packages that should be rebuilt based on more than one modified reference. 

Is this even possible?

**Comment by lasote** [comment]
Hi! Thanks for the question, is very interesting and relevant. Currently, that is not possible. If you don't mind I would like to know a bit more of how are you managing the CI, probably it makes sense to enable it, but maybe it is a matter of reviewing your CI flow.
When is the CI fired? Manually or when you push some code? Do you have multiple repositories with the different packages? How do you know the changed references?

**Comment by AliAskari** [comment]
We are using gitlab as our CI/CD server. When new changes are pushed to an upstream library, other than the normal (1)build, (2)test and (3)upload to conan server jobs we have an additional (4)manage dependencies job. We also have defined a super project that has all Conan packages as its dependencies.

- Use the super project to find the build order, `conan info -bo ...`
- Based on the ouput of the build order new pipelines (jobs (1), (2), (3) mentioned above) are created for each down stream project. In this job we automatically modify the conan recipe and version of downstream libraries based on changes done in the upstream libraries. (We wish if there was a way to specify a change in conan recipe without playing with versions but there isn't, so we are currently incrementing the patch version for every change in the conan recipe)

we use the name of git branch as the new conan channel name, i.e. If the upstream changes were pushed into the `feature_x` branch, all new packages in this process are released under the `feature_x` conan channel. We then test and validate these new changes in a two week process and if everything works out well it gets merged to master and released to stable conan channel. The merge is also automatic, when the upstream branch is merged to master all downstream branches get merged to master as well.

This process gets interesting when we have multiple upstream libraries getting updated to support one new feature, `feature_y`. What I am interested in is new functionality in Conan that provides me with the build order in a case like this, multiple changed references for build order. I understand that for cases like this, it is not trivial how it can be integrated in an automated pipeline so I am ok with triggering this process manually.

**Comment by czoido** [comment]
Hi @AliAskari. 
So if I understand correctly what you would like to do is for example if you have libraries that are depending on `zlib/1.2.11@conan/stable` and `glew/2.1.0@bincrafters/stable`  instead of
making a double call to:
`conan info . -bo zlib/1.2.11@conan/stable`
`conan info . -bo glew/2.1.0@bincrafters/stable`
You would like to just call:
`conan info . -bo zlib/1.2.11@conan/stable glew/2.1.0@bincrafters/stable`
and get the packages that depend on them to rebuild them 
If that is what you want I think I could make a pull request for the next release as 
I'm experimenting with that feature (just finishing the tests).

**Comment by czoido** [comment]
In fact I just realized that it was already being supported by conan, so 
`conan info . -bo zlib/1.2.11@conan/stable -bo glew/2.1.0@bincrafters/stable`
should give the ordered list of packages to build

**Comment by memsharded** [comment]
Closing as outdated, please refer to new ``conan graph build-order`` command in 2.0 and report new tickets as necessary for it, many thanks
