### ISSUE TITLE
Breaking change with -tf: Loop detected

### ISSUE THREAD

**Issue by jabaa** [conan-io/conan#4922]
The project https://github.com/jabaa/ThreadPool was built with travis-ci. The last build was 7 months ago with conan 1.7.3. Today I changed something and the commit triggered a new build in travis-ci. Today conan 1.14.1 was used and the build failed. I tried it on my local machine with conan 1.11.1 and the build succeeded. So I updated conan to 1.14.1 and the build failed. The build command is 

    conan create . jabaa/stable -tf . -o shared=$SHARED

and the problem is `-tf .`. When I remove it the build succeeds. The error is:

    ERROR: Loop detected: 'ThreadPool/0.1@jabaa/stable' requires 'ThreadPool/0.1@jabaa/stable' which is an ancestor too

[Here](https://travis-ci.org/jabaa/ThreadPool/jobs/427231558) is a log of a successful build and [here](https://travis-ci.org/jabaa/ThreadPool/jobs/516330977) is a log of a failed build.

How can I achieve the same behaviour with a new version of conan?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Using ``--tf .`` means that the `test_folder` (where it will find a conanfile to test the recipe) is the recipe itself, so it detects a loop (At 1.7.3 we didn't control if a reference requires itself). I think this is not a bug nor a breaking change. Are you really meaning to test the conanfile with the same conanfile?

**Comment by jabaa** [comment]
Yes, as you can see in https://github.com/jabaa/ThreadPool/blob/master/conanfile.py the conanfile.py contains the testcase. It worked until conan 1.11.1.

**Comment by lasote** [comment]
But that way is building twice your library, one for the package and once again for the test_package. Actually, the example is linking with the libraries built during the test stage, not against the package, so it is not really testing the package but the library. We never meant to allow that, honestly.

**Comment by lasote** [comment]
We have considered to "embed" the test in the main recipe a couple of times: https://github.com/conan-io/conan/issues/4610 but still just an idea.

**Comment by jabaa** [comment]
Okay, I added a test_package and moved the test method from main conanfile.py to test conanfile.py. But I support the idea of embedded test method in main conanfile.py
