### ISSUE TITLE
How to check if a recipe is buildable with a specific profile

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4924]
I can set my settings to only support specific configurations, like "only build for Visual Studio 11 and 12" as explained in the docs: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#settings

**Is it possible to somehow find out if my conanfile.py is creatable with a specific profile?** Of course I could run `conan create` on the component and see if it fails... but this command also fails if something within the compilation process fails - so I'm not sure if the build failed because of an unsupported environment or because of buggy code.

**Usecase:**
Our CI runs jobs for a number of different environments. Let's say:
* GCC 4.8 32bit
* GCC 4.8 64bit
* MSVC 2013 Debug
* MSVC 2013 Release
* MSVC 2017 Debug
* MSVC 2017 Release

Staying with the [above component from the docs](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#settings) it'd only be runnable on the MSVC 2013 environments. The jobs with GCC and 2017 will fail - which would render the whole CI pipeline as being failed.

I'd like to check within each build job if the environment is supported - and finish the non-supported environments as "this env is not supported". `conan create` will only be called for the supported environments.

**Comment by monsdar** [comment]
The code for each job could look like the following:

```
# pseudocode
if(conan check conanfile.py -pr gcc48.profile):
    conan create conanfile.py user/stable -pr gcc48.profile
else:
    echo "This environment is not supported, skipping compilation"
```

**Comment by monsdar** [comment]
Another way to solve this would be to only put those environments in the components CI config that are supported. The [component from the docs](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#settings) would only have the jobs for MSVC 2013 configured. Other would have GCC and MSVC 2017 in addition.

This however makes it hard to reuse CI configurations throughout multiple components. I'd like to have a single CI configuration that each component includes (Gitlab CI provides something like that with [file includes](https://docs.gitlab.com/ee/ci/yaml/#includefile)). It's very simple then to add a new environment or change how a certain env is handled. If every component defines its own subset of environments this makes things complicated.

Having a way to easily ignore unsupported environments would make things very easy to maintain, extend and scale.

**Comment by lasote** [comment]
Hi! The canonical way to do that is raising `ConanInvalidConfiguration` exception at the `configure` method: https://docs.conan.io/en/latest/mastering/conditional.html?highlight=conaninvalidconfiguration#constrain-settings-and-options

The conan process with return `6` as a return code, so you can check in CI if you have to build that configuration or not.

You can call `conan info` applying a profile prior to calling `conan create`, but it will do mostly the same, both will fail while building the dependency graph (before any build).

**Comment by monsdar** [comment]
Perfects, thanks for the answer.
