### ISSUE TITLE
Requirements not appearing on the website

### ISSUE THREAD

**Issue by coding3d** [conan-io/conan#493]
Hello,

I've noticed that the requirements for my package, small3d, do not appear on the website for any build:

https://www.conan.io/source/small3d/1.0.4/coding3d/stable

For the other packages that I have added, they appear properly. This is not a big issue, but I'd like to know if I've done something wrong or, if there is some glitch on the website (the package still works properly when downloaded) it might be useful information.

**Comment by memsharded** [comment]
It is possible that latest 0.12 release, in which many things of the search and meta-information have been changed, has broken something.

**Comment by lasote** [comment]
Fixed!

**Comment by coding3d** [comment]
Many thanks!
