### ISSUE TITLE
Settings are restricted before applying configure method

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#4939]
Conan 1.14.1

*`conanfile.py`*:
```python
from conans import ConanFile

class TestConan(ConanFile):
    name = "Hello"
    version = "1.2"

    settings = {"build_type": ["Release"]}

    def configure(self):
        del self.settings.build_type
```

Run `conan create . user/channel -s build_type=Debug`

**Expected result:** package is created since it doesn't have build_type setting.

**Actual result:** Fails with `Error while initializing settings. Invalid setting 'Debug' is not a valid 'settings.build_type' value.`

## Some Background:

I'm trying to create a package with a tool and have 2 groups of settings: `os_build` for consuming and `compiler` and `gcc` for creating (so all helpers pick up right compiler and apply settings).

Since `compiler` and `build_type` should not affect consumption of this package I delete them in `configure`:

```python
def configure(self):
    if not self.develop:
        del self.settings.build_type
        del self.settings.compiler
```

However I want to "tip" package creator that the package shouldn't be created in "Debug" (especially in my case the "creator" is a script which passes the recipe through a set of predefined profiles to get a unique set of produced binaries).

This breaks when I try to consume such package as a transitive dependency when building debug version of my library.

As a workaround I can check those restrictions in `configure` method, but it's less expressive
```python
    def configure(self):
        if not self.develop:
            del self.settings.build_type
            del self.settings.compiler
        else:
           if self.settings.build_type != "Release":
                raise ConanInvalidConfiguration("Only release build for a tool")
```

**Comment by jgsogo** [comment]
Hi @ytimenkov! I've checked the code and you have exposed precisely what it is happening: settings are being constrained before the `configure()` call and it fails because the `Debug` is not a valid value for your package.

We need to have a look into it, I don't know right now if there is some unexpected effect if we call `configure()` so early, but I'm adding it to the queue as it would be an improvement. Meanwhile, as you have suggested, you should go with the workaround 😞

Thanks for the accurate report!

**Comment by memsharded** [comment]
The way of restricting settings like ``settings = {"build_type": ["Release"]}`` in recipes, has been removed in Conan 2.0, closing this ticket as outdated.
