### ISSUE TITLE
`conan search -v` is removed on 0.12.0?

### ISSUE THREAD

**Issue by laohyx** [conan-io/conan#494]
Hi, as titled, on new version of conan, how can I search a package with detailed binaries?
Because we are care about what binaries are built. 
Could I get some alternatives to `conan search -v`?

Thanks in advance.

**Comment by laohyx** [comment]
Oh just type `conan search <package name>` will show very detailed information!
Thanks!!

**Comment by memsharded** [comment]
From conan 0.12.0, the package binaries can be queried for a given package with the following syntax:

```bash
conan search Boost/1.60.0@lasote/stable -q arch=x86
```

That will list the packages for the architecture ``x86``. Without the query "q", you will get all binaries as with the previous conan version

**Comment by memsharded** [comment]
@laohyx you were seconds faster than me, I had almost finished the response :)

**Comment by laohyx** [comment]
aha @memsharded , thanks to your reply!
💯 💯 💯 💯
