### ISSUE TITLE
Question about directory locations on Windows

### ISSUE THREAD

**Issue by rambius** [conan-io/conan#4947]
Hello,

I have a C++ project that uses conan. I have listed its dependencies in its conanfile.py. I noticed that while most of the dependencies are downloaded into C:\Users\<myusername>\.conan\data, few of them including boost are downloaded to C:\.conan. We have our own internal Artifactory repository.

I don't understand why boost goes to C:\.conan and not in C:\Users\<myusername>\.conan. Can you explain please. I am running conan interactively, i.e. not as an automated build process running as Windows service under SYSTEM account.

Regards
Ivan

**Comment by memsharded** [comment]
Hi Ivan

That Boost recipe has a ``short_paths=True`` definition. You can inspect the recipe with ``conan inspect`` or with ``conan get``.

This is a Windows workaround to the Windows limit on path lengths. The boost package cannot be built or used if stored in the regular path in the cache, and has to be re-located somewhere close to the drive unit, so the paths fit.

It is possible to disable this behavior in case that you have a modern Win10, with a modern Py3 with the long paths activated both in Windows and in Python, and given that any of your tools or build-systems don't have an internal limitation (might be possible that Boost Build system might fail with long paths even in that case). But if you want to try, the https://docs.conan.io/en/latest/reference/env_vars.html#conan-user-home-short CONAN_USER_HOME_SHORT environment variable set to "None" would disable it.

Please tell if this helps, and if it addresses your question, close the issue.
Regards

**Comment by rambius** [comment]
Hello,

Thank you for your response. I am trying a build with CONAN_USER_HOME_SHORT set to None .

Regards
rambius
