### ISSUE TITLE
HTTPSConnectionPool Error prevent conan from working

### ISSUE THREAD

**Issue by mietzen** [conan-io/conan#4952]
To help us debug your issue please explain:

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ x ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

OS: Linux + Windows
Conan Version: 1.12.3

Last week a server on our repo list was unreachable, this prevented conan from working even if the remote wasn't need in the recipe. Also conan with -r to a working repository didn't worked.

`HTTPSConnectionPool(host='www.my.repo.de', port=443): Read timed out. (read timeout=60.0)`

The only solution was to remove the unreachable repo from the remote list. 

I would expect to throw `HTTPSConnectionPool` as warning and not as error

**Comment by jgsogo** [comment]
It makes sense to continue working if one remote fails but it is not being used for a command. Nevertheless, if the command requires that remote (searching in all of them, looking for updates,..) Conan should continue raising the error. This should be easier after https://github.com/conan-io/conan/pull/4724.

Which command was failing? Can you copy&paste here the error? It could help us to work on a solution. Thanks.

**Comment by mietzen** [comment]
I'll try to setup a configuration to reproduce the error this afternoon.

**Comment by memsharded** [comment]
> It makes sense to continue working if one remote fails but it is not being used for a command. 

Yes, connection to remotes should only fail if they are actually requested. Many commands won't use remotes.

But for other commands that will try to contact remotes (like install --update, and many others) this was a design decision some time ago, when failing remotes were warning and not erroring.
The behavior became unpredictable for users dealing with different remotes and relying on priorities to resolve packages with the same name in different repos, or delaying the failure to some "package not found later", that was not very intuitive. This happened to a few users, so it was decided to turn it into a feature. If for some reason some remote fails to connect, it raises an error, to make it very explicit and it has to be the user to remove it if it makes sense.

So we would need to understand what command and it what context was trying to contact a remote it shouldn't try to contact. Looking forward your findings later, thanks!

**Comment by mietzen** [comment]
Sorry I'm not able reproduce the Error. Now it behaves like expected. When is use` -r all` it throws an Error, when using `-r any-available-repo` it works. You may close this issue

**Comment by memsharded** [comment]
Good, thanks for the feedback @mietzen
