### ISSUE TITLE
`cmake_find_package_multi` might need also CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4956]
`cmake_flags.py` line 329, add also `CMAKE_MODULE_PATH` when using that generator. Looks like the `find_dependency`  needs it.

**Comment by Johnnyxy** [comment]
As I see often issues with ```CMAKE_MODULE_PATH```, ```CMAKE_PREFIX_PATH```, ... so I want to add a clarification that maybe the "issue search engine" will find this.


What variables are used for searching files depends on the **find_package** _call signature_ a caller issued.

If using the [basic / module](https://cmake.org/cmake/help/latest/command/find_package.html?highlight=find_package#basic-signature-and-module-mode) mode then only ```CMAKE_MODULE_PATH``` is needed. This mode searches only for files named ```Find<PackageName>.cmake```.

If using the [full / config](https://cmake.org/cmake/help/latest/command/find_package.html?highlight=find_package#full-signature-and-config-mode) mode then ```CMAKE_MODULE_PATH``` is not considered at all. Instead ```CMAKE_PREFIX_PATH``` and other variables are used. This mode searches only for files named ```<PackageName>Config.cmake``` or ```<lower-case-package-name>-config.cmake``` or if given the **NAMES** argument (```<NAME>Config.cmake``` or ```<lower-case-name>-config.cmake```) with a more advanced search algorythm ([see here](https://cmake.org/cmake/help/latest/command/find_package.html?highlight=find_package#search-procedure)).

As the [CMakeFindDependencyMacro](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html) forwards the given arguments to ```find_package``` the same rules apply as with ```find_package```.
