### ISSUE TITLE
Support symbol (.pdb) and source files debug functionality on an installed conan package

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#4957]
Hi all,

Problem: I'm trying to supply debug funcionality on windows on my conan packages by storing the pdb files on each package but the problem is that the package when not build locally, only installed by conan, the source code will not be available and then code and symbols will not be found.

Have you any idea of what is the best aproach on these cases? not copy pdb files (force build locally), copy pdb files and source all together to package folder? What is your opinion on these? what is the advisable aproach?

Thanks

**Comment by Johnnyxy** [comment]
Hi there,

if you execute a EXE or load a DLL the debugger first looks in the directory of the binary for a PDB file. So there is no problem with finding the PDB file if you put it beside the binary.

But there is another issue with the PDBs. One "big" problem is that they save the path to the source files.

If move the source somewhere else to another directory then the debugger cannot find the source files anymore. This is a general problem when distributing PDBs. There are some ways to circumvent this but to my knowledge there is no portable clean solution ([Microsoft source indexing feature](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2019), manipulating the paths in the PDB file, using some kind of [symbolic links](https://stackoverflow.com/a/28174/8608854) on filesystem-level).

The cleanest solution would be to let Conan make a local ```debug``` build.



Why do you want someone to debug your compiled code when he has access to the sources?

**Comment by nesc1** [comment]
Hi @Johnnyxy thanks for reply.

The why is basically to avoid the build locally and using debug build types to avoid having the warning saying the pdb files are not found, but mainly to avoid build locally.

But yes i understand that the best way to acomplish this is to request to build the required package locally and all problems will be fixed.

Thanks, i only need to know if conan had some special handling for these kind of requirements.

**Comment by Johnnyxy** [comment]
Yes something like that could be helping others to debug faster.

But to make sure everything is as expected (except bugs in code :)) one should always use PDBs which where built with exact same compiler as the debugging system is using. If one is a little bit paranoid then one could assume that the content of the PDB could be different between compiler versions.

**Comment by nesc1** [comment]
yes you are right
