### ISSUE TITLE
Add configurable pattern for files to be excluded from the package (repackaging '.pyc' files)

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan#4961]
Conan version: 1.15.0-dev

The way `gather_files` works - it discards all .pyc files. Discarding files is not always desired if one wants to keep the original package content as-is.

In my case the legacy package doesn't have .py files. While it's possible to "uncompyle" .pyc files I want to have more control and have an option to include everything.

```python
conans/model/manifest.py
   11 def discarded_file(filename):
   12     """
   13     # The __conan pattern is to be prepared for the future, in case we want to manage our
   14     own files that shouldn't be uploaded
   15     """
   16     return filename == ".DS_Store" or filename.endswith(".pyc") or \
   17            filename.endswith(".pyo") or filename == "__pycache__" or \
   18            filename.startswith("__conan")

```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi, @klimkin! We can consider it for the future but it may have some really tough problems, the `manifest` is one of the core pieces in the Conan internals, it plays a very important role during upload, download and other stages to check the integrity of the Conan package. To be able to modify how it is computed we have to be very sure that we will have access to the _pattern_ whenever we need it and that pattern will be part of the recipe itself (maybe it could be a _chicken and egg_ problem).

Can I know which package are you working with? Is it OSS or from a company? I would want to know if it is a corner case or something we could face again in the near future.

Thanks!

**Comment by klimkin** [comment]
This is an internal company package. It does feel like a corner case.

**Comment by jgsogo** [comment]
I will change the title of the issue to something like _"Add configurable pattern for files to be excluded from the package"_, add it to the queue as a feature, but with low priority. I think it could be interesting but we will need more use cases to increase its priority.

Thanks!

**Comment by ahauan4** [comment]
We also have this issue. And it is a blocker, because we cannot create a Conan package for one of our basic tools. It's a delivery of a different company who do not want to deliver their .py files but .pyc files only. We would appreciate if you could have a look at this problem.

**Comment by memsharded** [comment]
This issue has been reported and use case described in https://github.com/conan-io/conan/issues/5404#issuecomment-505911053 too, by @keithrob91

**Comment by Daniel-Roberts-Bose** [comment]
Hi guys,

I've run across this problem today and it may be a blocker for us. We get pyc files shipped to us from an external library so we really have no option but to take them as is. It took me a while to figure out that conan was stripping away these files in the final package uploaded to artifactory. 

Are there any updates on the status of this issue?

Thanks

**Comment by w3sip** [comment]
Ran into this as well today. Will have to work around by not using Conan for this particular project/package.

**Comment by memsharded** [comment]
I am proposing a configuration possibility in: https://github.com/conan-io/conan/pull/8070. Let's see if we can move it forward now in Conan 1.X (and maybe this could be the default in Conan 2.0?)

**Comment by memsharded** [comment]
Hi folks!

Good news: https://github.com/conan-io/conan/pull/8070 has been merged, it will be available (experimental) in next Conan 1.32, and the goal is to make it the default in Conan 2.0.

**Comment by klimkin** [comment]
Great, than you!

**Comment by memsharded** [comment]
Conan 2.0 is removing this feature, because it will not exclude .pyc from packaging: https://github.com/conan-io/conan/pull/9673, so no extra env-var or conf will be needed to package .pyc
