### ISSUE TITLE
[Question] Artifactory: Permission control based on Conan package settings etc.

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#4964]
Hi,

The permission controls (include/exclude filters, groups, etc.) for repositories work for in most of the cases for us, but we'd also need a way to control "time based" permission control.

The Conan packages are created with a certain time stamp, the time stamp is added as "topics" field in Conan recipe for the package.

> topics = (..., "RELEASE_TIME_STAMP=1234567890", ...)

The users have subscriptions for the packages, i.e. once the subscription time for a given user ends we'd need to filter out those packages that are released after the subscription time has ended. The packages that are released before the subscription time ends need to be available for the user.

Is there a way to:
- write an Artifactory plugin that can read the Conan recipes data (e.g. the "topics" field)
- hook the plugin so that it is invoked at the right time (when server received clients "search"/"install" commands)
- the plugin could filter out Conan packages that won't match the criteria (response to the client)

If there exists documentation or examples could you please point to the right direction?
Or is there some built-in feature in Artifactory that could be used for the same purpose?

Thanks!

**Comment by lasote** [comment]
I have no idea, to be honest. I've never heard about plugins for Artifactory. Maybe using the Artifactory REST API and AQL you could set up a script to search by date/adjust the permissions. Like a crontab or something.

**Comment by unzap** [comment]
Hi @lasote 

I was referring to "Artifactory User Plugins"
https://www.jfrog.com/confluence/display/RTF/User+Plugins

"Artifactory Pro allows you to easily extend Artifactory's behavior with your own plugins written in Groovy.
User plugins are used for running user's code in Artifactory"

It mentions e.g. "Change resolution rules" and "Extend Artifactory with your own security realms" which sounds like a right direction what I'm trying to look after.

The API is exposed here: http://repo.jfrog.org/artifactory/oss-releases-local/org/artifactory/artifactory-papi/%5BRELEASE%5D/artifactory-papi-%5BRELEASE%5D-javadoc.jar!/index.html

But I haven't been able to find Conan specific stuff from there yet :) ?

**Comment by lasote** [comment]
If you are a customer with a Pro license, I suggest going for the official Artifactory support, they will take care better than us. Thanks!

**Comment by memsharded** [comment]
Closing this question as outdated (and a bit outside of the scope of this repo, this is mostly about Artifactory)
