### ISSUE TITLE
 conan_paths.cmake seem to be unusable if CMAKE_FIND_ROOT_PATH_MODE_PACKAGE==ONLY

### ISSUE THREAD

**Issue by nolange** [conan-io/conan#4967]
# Why search modes matter

Crossbuild should never search host system paths for Modules,
Libraries or headers. This can be especially subtle if the crossbuild
is the same architecture, but has version/abi conflicts.

Conan tries to solve the same issue, but there might always be some
libraries that should be taken from the target sysroot.

The variable `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE` and consorts
restrict the search to some explicitly declared sysroot directories.

# Why conan cmake path generator breaks this

the generated paths are of the sort `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH`,
when `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE` is set to `ONLY` then those paths will be re-rooted under the path(s) defined in `CMAKE_FIND_ROOT_PATH`.
Which almost certainly points to nowhere, or might even point to a valid but wrong directory.

# What did work for me

I adjusted `CMAKE_FIND_ROOT_PATH` (and only this PATH variable) in conan_paths.cmake:

```cmake
set(CMAKE_FIND_ROOT_PATH "/home/lano/.conan/data/gtest/1.8.1/bincrafters/stable/package/319986a8ddc0fc392032c63f81cacfe9edd93e70/" $CMAKE_FIND_ROOT_PATH)
```

This should work for most packages AFAIK, as the usual prefixes and library/include paths should be available there.

## Versions

The package I tried to install, was `gtest/1.8.1@bincrafters/stable`
(sorry if this is specific to the package, but I think the conan_path generator is at fault here)

conan: 1.14.3 (conan-ubuntu-64_1_14_3.deb)
OS: Debian Buster/Testing x64
CMake: 3.13.4

Whole toolchainfile.cmake for posterity:
```
#
# Automatically generated file; DO NOT EDIT.
# CMake toolchain file for Buildroot
#

# In order to allow the toolchain to be relocated, we calculate the
# HOST_DIR based on this file's location: $(HOST_DIR)/share/buildroot
# and store it in RELOCATED_HOST_DIR.
# All the other variables that need to refer to HOST_DIR will use the
# RELOCATED_HOST_DIR variable.
string(REPLACE "/share/buildroot" "" RELOCATED_HOST_DIR ${CMAKE_CURRENT_LIST_DIR})

# Point cmake to the location where we have our custom modules,
# so that it can find our custom platform description.
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

set(CMAKE_SYSTEM_NAME Buildroot)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# Set the {C,CXX}FLAGS appended by CMake depending on the build type
# defined by Buildroot. CMake defaults these variables with -g and/or
# -O options, and they are appended at the end of the argument list,
# so the Buildroot options are overridden. Therefore these variables
# have to be cleared, so that the options passed in CMAKE_C_FLAGS do
# apply.
#
# Note:
#   if the project forces some of these flag variables, Buildroot is
#   screwed up and there is nothing Buildroot can do about that :(
set(CMAKE_C_FLAGS_DEBUG "" CACHE STRING "Debug CFLAGS")
set(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "Debug CXXFLAGS")
set(CMAKE_C_FLAGS_RELEASE " -DNDEBUG" CACHE STRING "Release CFLAGS")
set(CMAKE_CXX_FLAGS_RELEASE " -DNDEBUG" CACHE STRING "Release CXXFLAGS")

# Build type from the Buildroot configuration
set(CMAKE_BUILD_TYPE Debug CACHE STRING "Buildroot build configuration")

if(CMAKE_VERSION VERSION_LESS "3.7.0")
# Buildroot defaults flags.
# If you are using this toolchainfile.cmake file outside of Buildroot and
# want to customize the compiler/linker flags, then:
# * set them all on the cmake command line, e.g.:
#     cmake -DCMAKE_C_FLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g2 -Dsome_custom_flag" ...
# * and make sure the project's CMake code extends them like this if needed:
#     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Dsome_definitions")
set(CMAKE_C_FLAGS "-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g2" CACHE STRING "Buildroot CFLAGS")
set(CMAKE_CXX_FLAGS "-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g2" CACHE STRING "Buildroot CXXFLAGS")
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--enable-new-dtags,-z,relro,-z,now" CACHE STRING "Buildroot LDFLAGS for executables")
else()
# Defaults are fitting for Debug and Release builds
# Remaining settings can be seeded by using the *_INIT variables

# TODO: potentially set global Makros via add_definitions, much cleaner
# these might require generator expressions for the various languages

set(CMAKE_C_FLAGS_INIT "-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g2")
set(CMAKE_CXX_FLAGS_INIT "-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g2")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,--enable-new-dtags,-z,relro,-z,now")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-Wl,--enable-new-dtags,-z,relro,-z,now")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-Wl,--enable-new-dtags,-z,relro,-z,now")
endif()

#-O2 -g2
#-O2 -g2
# Add definitions, The more fitting add_definitions() does not support
# generator expressions
if(CMAKE_VERSION VERSION_LESS "3.3.0")
else()
# $<COMPILE_LANGUAGE:lang> supported since CMake 3.3
#add_compile_options($<$<COMPILE_LANGUAGE:C>:$<SEMICOLON>-D_LARGEFILE_SOURCE$<SEMICOLON>-D_LARGEFILE64_SOURCE$<SEMICOLON>-D_FILE_OFFSET_BITS=64>)
#add_compile_options($<$<COMPILE_LANGUAGE:CXX>:$<SEMICOLON>-D_LARGEFILE_SOURCE$<SEMICOLON>-D_LARGEFILE64_SOURCE$<SEMICOLON>-D_FILE_OFFSET_BITS=64>)
endif()

set(CMAKE_INSTALL_SO_NO_EXE 0)

set(CMAKE_PROGRAM_PATH "${RELOCATED_HOST_DIR}/bin")
set(CMAKE_SYSROOT "${RELOCATED_HOST_DIR}/x86_64-buildroot-linux-gnu/sysroot")
set(CMAKE_FIND_ROOT_PATH "${RELOCATED_HOST_DIR}/x86_64-buildroot-linux-gnu/sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${RELOCATED_HOST_DIR}/x86_64-buildroot-linux-gnu/sysroot")

# This toolchain file can be used both inside and outside Buildroot.
set(CMAKE_C_COMPILER "${RELOCATED_HOST_DIR}/bin/x86_64-buildroot-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "${RELOCATED_HOST_DIR}/bin/x86_64-buildroot-linux-gnu-g++")
if(0)
  set(CMAKE_Fortran_FLAGS_DEBUG "" CACHE STRING "Debug Fortran FLAGS")
  set(CMAKE_Fortran_FLAGS_RELEASE " -DNDEBUG" CACHE STRING "Release Fortran FLAGS")
  set(CMAKE_Fortran_FLAGS "-O2 -g2" CACHE STRING "Buildroot FCFLAGS")
  set(CMAKE_Fortran_COMPILER "${RELOCATED_HOST_DIR}/bin/x86_64-buildroot-linux-gnu-gfortran")
endif()

```

**Comment by lasote** [comment]
Thanks for reporting. I think you are right. We should start assigning `CMAKE_FIND_ROOT_PATH` for:

- `cmake_paths` generator: pointing to the package root folder
- When the generators `cmake_find_package` and `cmake_find_package_multi` are used in a recipe,  `CMake` build helper auto adjusted `CMAKE_PREFIX_PATH` and `CMAKE_MODULE_PATH` in order to find the generated `XXXConfig.cmake`  and `FindXXX.cmake` scripts, so `CMAKE_FIND_ROOT_PATH` should be adjusted too.

**Comment by nolange** [comment]
I found another relevant variable `CMAKE_STAGING_PREFIX`, which removes files under those prefixes from the re-rooting.

I would now prefer a different solution, as adding to either `CMAKE_MODULE_PATH` or `CMAKE_FIND_ROOT_PATH` will multiple the paths searched (and increases the chance to pickup the wrong file somewhere).

Take a "clean" (complete and correct installation files) package "Example" which installs CMake Config files named "ExampleConfig.cmake" (etc.).
Another option to set the path for the installed package is to set the variable Example_DIR to the folder containing those files. This variable will **only be used in the context of `find_package(Example)`**.

That would have less side-effects than modifying those common search variables, but might break packages depending on these (which don't export the include paths for example).
Perhaps that could be an option conan packages would have manually enable (for now).

This might be the cleanest way to inject search paths for Packages enabled to be used by CMake, but wont work in the general case. The other cases would need the `*Config.cmake` files to be automatically generated (if thats possible), or fallback to regular search (via `CMAKE_PREFIX_PATH`?)

I would propose using the following (crossbuild means dont-pick-stuff-from-host):

-   `CMAKE_FIND_ROOT_PATH`
     set to target sysroot if crossbuild
-   `CMAKE_FIND_ROOT_PATH_MODE_{PACKAGE,LIBRARY,INCLUDE}`
    set to `ONLY` if crossbuild
-   `CMAKE_STAGING_PREFIX`
    set to conan package directories always.
-   `<package>_DIR`
    set to directory containing CMake's config files (if applicable).
-   'custom variable'
    incase a CMake FindPackage offers injecting a search path by variable,
    for example `GTEST_ROOT`
-   not sure what
    either create CMake's config files if possibly or use the current method with
    `CMAKE_PREFIX_PATH`?

I got my project to work using this command (ignoring conan_paths.cmake and with the above toolchain):
```
cmake -DCMAKE_TOOLCHAIN_FILE=/home/lano/buildroot/host/share/buildroot/toolchainfile.cmake -DGTest_DIR=/home/lano/.conan/data/gtest/1.8.1/bincrafters/stable/package/319986a8ddc0fc392032c63f81cacfe9edd93e70/lib/cmake/GTest -DCMAKE_STAGING_PREFIX=/home/lano/.conan/data -G Ninja /home/lano/workspace-hip2/rtgate
```

**Comment by lasote** [comment]
Wow, that's a lot of new information. We would need to read it carefully to understand but it sounds complex.

By the way, about  https://github.com/mpusz/new-project-template/issues/1. We don't recommend to rely on the `XXXConfig`  or `Find` cmake scripts packaged in the Conan packages and probably we are not going to allow it in the `conan center` repositories.

The reason is, the conan model allows you to know for any consumer (not only cmake) each package properties, lib names, lib dirs, include paths, flags etc... by using the `package_info`. Also, the `XXXConfig.cmake` files provided by a package might not be transitive, it depends on how well are built.

Since the `cmake_find_package_multi` generator, creates for you the `XXXConfig.cmake` files with the targets, you just need to specify the generator in your recipe/project and use the `find_package` feature to use the target, knowing that the target is complete and always managing Conan dependencies. Conan has all the information, it makes no sense to rely on external modules to provide the information when Conan already knows.

We totally agree that the `find_package` feature should be the way to "connect" with the dependencies, but trusting the package manager to do it, not the System-cmake-installation-module-path or custom scripts packaged by the libraries (probably because of the lack of adopting a package manager).

So, of course for a company or group, packaging your own cmake find/config scripts can work, and you can do it, but for the OSS community we are moving to the described recommendation.

**Comment by nolange** [comment]
> By the way, about [mpusz/new-project-template#1](https://github.com/mpusz/new-project-template/issues/1). We don't recommend to rely on the `XXXConfig` or `Find` cmake scripts packaged in the Conan packages and probably we are not going to allow it in the `conan center` repositories.
> 
> The reason is, the conan model allows you to know by any consumer (not only cmake) each package properties, lib names, lib dirs, include paths, flags etc... by using the `package_info`. Also, the `XXXConfig.cmake` files provided by a package might not be transitive, it depends on how well are built.

I get the argument, but I am rather scared that will render some packages (particularly frameworks) useless. There is an abundance of horribly different buildsystems because there is not one that fits all uses, now you are trying that with conan.
Finding libraries and includes is solvable, but what are you doing with QT or something like my own tack-on configs that come with [cmake functions](https://github.com/nolange/cmake_xenomai/blob/master/config/xenomai-macros.cmake.in) to ease usage and concentrate the logic where it makes most sense: the installed package.

If you don't distribute those helpers with packages, then every build system will have to inherit all those helpers (possibly updated for every package version). Which is mesons approach, which I am not really fond of.

> Since the `cmake_find_package_multi` generator, creates for you the `XXXConfig.cmake` files with the targets, you just need to specify the generator in your recipe/project and use the `find_package` feature to use the target, knowing that the target is complete and always managing Conan dependencies. Conan has all the information, it makes no sense to rely on external modules to provide the information when Conan already knows.

Not for extending the build system itself.
 
> We totally agree that the `find_package` feature should be the way to "connect" with the dependencies, but trusting the package manager to do it, not the System-cmake-installation-module-path or custom scripts packaged by the libraries (probably because of the lack of adopting a package manager).

The auto-generated configs from CMake are mostly fine, and I would prefer to
have the Configs fixed than ignored. 

> So, of course for a company or group, packaging your own cmake find/config scripts can work, and you can do it, but for the OSS community, we are moving to the described recommendation.
> 
> So also part of these concerns you raised are already fixed, Conan provides to you the needed "plugs", you should be fine even cross building.

I was fine crossbuilding before conan, but theres always something to improve ;)
Have some reading up to do myself, just did some small tests so far

**Comment by lasote** [comment]
About the cmake functions provided or found by the `find_package`, we talked also about it and we still didn't agree in the best way to solve. But we all agree that it is a bad practice to couple the mechanism of "where to find the dependency" with the "provide to me the functions from the already located library".
We discussed several approaches:

- Force the consumer CMakeLists to include a very well known `conan_functions.cmake`. That file could be packaged separately in the Conan package.
- An improvement to the first approach could be: If the file is packaged following a convention, the Conan find scripts could automatically include it.
- Introduce a `self.cmake_info` object in the `package_info`, so you can declare in the recipe the functions. I don't like this idea.

I think the second option could work ok, and for the consumer would be transparent. Is the packager responsibility to expose correctly the functions.

We appreciate your feedback!

**Comment by sobczyk** [comment]
Is this issue getting any traction?
The base toolchain file generated by OpenEmbedded has `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE==ONLY`
And conan 2.0 aims for config style dependencies. (ie. CMakeDeps)
This makes it really hard to cross compile for OE.

Edit:
I've tested it, and `CMAKE_FIND_ROOT_PATH` works with config style packages and `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE==ONLY`

There's a small tweak to OE toolchain file that is required though, not to completely override `CMAKE_FIND_ROOT_PATH`

**Comment by memsharded** [comment]
``cmake_paths`` generator dropped in 2.0 (replaced in 1.X by ``CMakeToolchain`` (without ``CMakeDeps``)). Closing as outdated.
