### ISSUE TITLE
Visual Studio Generator: PATH variable not correct

### ISSUE THREAD

**Issue by sct2010** [conan-io/conan#4969]
Hi

I am using the visual studio generator to generate a 'conanbuildinfo.props' file. The PATH variable in props file has the wrong directory separator char. In Windows CMD paths with '/' aren't supported in the PATH variable. Since the PATH variable isnt correct, the executables aren't be found if i am using ShellExecute in the code. 

An example of a generated props file is:
`<LocalDebuggerEnvironment>PATH=%PATH%;$(USERPROFILE)/.conan/data/xx/0.6.0/3rdparty/release/package/c85f9b4041181d7a/bin;</LocalDebuggerEnvironment>  
    <DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>`

It is supposed to looks like:
`<LocalDebuggerEnvironment>PATH=%PATH%;$(USERPROFILE)\.conan\data\xx\0.6.0\3rdparty\release\package\c85f9b4041181d7a\bin;</LocalDebuggerEnvironment>  
    <DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>`

Version info:
Conan 1.14
Visual Studio 2015
Windows 10 Pro

The issue is in the file: conans/client/generators/visualstudio.py:
Line 25: <LocalDebuggerEnvironment>PATH=%PATH%;{bin_dirs}</LocalDebuggerEnvironment>
Line 70: 'bin_dirs': "".join("%s;" % p for p in build_info.bin_paths).replace("\\", "/"),'

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Thanks for reporting. We will try to solve it for 1.15.

**Comment by lasote** [comment]
Hi again, I tried to do a simple test setting PATH in the cmd to a folder with "/" instead of "\" and it works. Is it not working for you? It is something related with VS maybe?

**Comment by sct2010** [comment]
Hi
I did the same test with the path variable in the cmd promt and it worked.
So I created a small test project to demonstrate the issue. In the attached zip file are two folders. One is a simple binary package with the windows write program. The second one is the visual studio 2015 solution with a simple mfc dialog. On clicking the OK button the windows write program (included in the conan wite package) should open.

If the path in the props file contains '/' it is not working for me. If I changed the '/' to '\\' in the props file (line 13) it works for me.

[test.zip](https://github.com/conan-io/conan/files/3089565/test.zip)

**Comment by memsharded** [comment]
Hi @sct2010 

Thanks for the example project, very useful!

Some quick feedback regarding your test code first: You probably want to use ``conan export-pkg`` to package apps, precompiled binaries, etc, instead of using ``exports`` and then ``conan create``. With this second form, you would be using twice the space, packaging the .exe 2 times, one as source, and the other as the final package. With ``conan export-pkg`` you can directly create packages from exiting binaries and other files.

I have verified the behavior, it fails with forward slashes / , and works with backslash \

I have submitted a PR in #5003, to see what happens to CI when using \

**Comment by sct2010** [comment]
Hi @memsharded 

Thanks for feedback about the binary packaging.
I tested the patch from the PR #5003 . It works for me.
