### ISSUE TITLE
[Question] Artifactory: Permissions settings to protect "release" channel packages

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4973]
Hi,

i hope someone came across this problem which i guess should be quite common in the "enterprise environment".
What i would like to achieve is that Conan packages with channel `release` (e.g. `mylib/1.0.0@myuser/release`) are protected from deletion/modification by "regular users".

This means that further binary packages of such packages can be uploaded since they may not be built and uploaded at once but it shall not be possible to delete or modify the recipe or any of the binary packages.

So far we managed to configure the permissions so that this all works as expected when using Conan on the commandline to upload/remove packages but from the Web UI of the Artifactory it is still possible to delete the whole tree of packages versions though there are also packages with channel `release` underneath. E.g. if "Delete" is clicked in the screenshot, all `cmake` packages including the `release` ones would be gone:
![image](https://user-images.githubusercontent.com/2109816/56097088-4f78f580-5ef0-11e9-8390-951c41a40147.png)

This may also be a considered a bug of Artifactory as IMO it should not be possible to delete a whole tree if i do not have the delete permission for all elements in the tree.

It may be possible to use a further repository with "delete/overwrite nothing" and "write/upload underneath a release folder only" permissions configured, but i would like to avoid this as this adds complexity and room for user errors.

These are the patterns we configured for allowing write and delete operations:
![image](https://user-images.githubusercontent.com/2109816/56097111-8c44ec80-5ef0-11e9-83a4-fec57c15fce0.png)
And these are the patterns for allowing write but not delete operations:
![image](https://user-images.githubusercontent.com/2109816/56097117-9f57bc80-5ef0-11e9-9b81-0f1f3cc6fc21.png)

thx

**Comment by lasote** [comment]
I'm afraid we can't help much, that is more a question for Artifactory team than Conan. I think the simpler approach will be to keep the same channel always but use different repositories. So when the packages are ready, you promote (with a user with permissions) all the packages to the new repository. Could that flow work for you? Are you using Artifactory CE c++? Or do you have a license?

**Comment by petermbauer** [comment]
I was hoping to get along without another repository but if we have to use one, the approach would be to set "upload" permissions only and no "delete/overwrite" for the whole repo.
Thanks for caring though, we are using the commercial Artifactory so i hope the JFrog support comes up with a solution.

**Comment by lasote** [comment]
Thanks, I'm sure they will support. Otherwise please ping me here again and I will contact our Artifactory collegues.

**Comment by petermbauer** [comment]
Apparently this has been fixed in the Artifactory lately, at least with version 6.12.1 though i could not find a respective entry in the changelogs. This means that the "Delete" entries in the context menu are still shown for parent folders of e.g. `release` folders/packages but this leads to an error message while all other except the `release` folders are actually deleted.

To configure this behaviour of protecting packages with certain channels (e.g. `release`), its sufficient to have two permission targets:
- "Delete/Overwrite" with include pattern `**` and exclude pattern `*/*/*/release/**`
- "Deploy/Cache" with include pattern `*/*/*/release/**`
