### ISSUE TITLE
MSBuild should allow "do not adjust PlatformToolset" with an argument

### ISSUE THREAD

**Issue by yuval-crl** [conan-io/conan#4975]
Hey,

In https://github.com/conan-io/conan/pull/4250 the default behavior of VisualStudio's toolset selection was changed to compile the whole solution using the same toolset (the `/p:PlatformToolset` is always set - see discussion here https://github.com/conan-io/conan/pull/4250#pullrequestreview-193994771).

This change prevents using two different toolsets in the same solution. In my case building a driver using the `WindowsKernelModeDriver10.0` (which is not even a valid option right now) toolset and user mode library using the `v141` toolset.

I will be happy to write the code if this behavior change is accepted.

**Comment by lasote** [comment]
Hi, thanks for opening the issue.

How the call to `msbuild` would look like to solve this situation? I mean, what would be the patch to Conan? 
Thanks

**Comment by yuval-crl** [comment]
Unfortunately I don't see a good option without adding a toolset option.
The options I thought about:
1. Adding a `from-compiler` toolset option that will determine the toolset from the `settings.compiler` field (using the current implementation for when `None` is passed as the toolset), and changing back the `None` behavior to use the solution configuration.
2. Adding `use-default` toolset option which will use the the solution configured toolset.

I think 2 is the way to go.
It will not break the behavior of `toolset=None` (again) and the implementation will be simpler (changing an `if` statement in `msbuild.get_command`).

**Comment by lasote** [comment]
I understand, So you need a way to say "do not adjust the toolset, please" to the `MSBuild` build helper. I think that reasonable. We will think about the best way to implement it. Thanks again for opening the issue!

**Comment by memsharded** [comment]
Hi @yuval-crl 

https://github.com/conan-io/conan/pull/5052 has proposed to use the ``vs.build(toolset=False)`` to indicate that no extra toolset flags will be added to the invocation, and thus, the project configured toolset will be respected.
