### ISSUE TITLE
[question] Is there any integration support for KIEL MDK right now?

### ISSUE THREAD

**Issue by DanFTRX** [conan-io/conan#4985]
Title is pretty self explanatory.  Wondering if there is any integration with KIEL MDK building and uvprojx projects.

http://www2.keil.com/mdk5

**Comment by lasote** [comment]
I don't know if someone from the community has tried it. The Conan core team didn't know about that.  If the KIEL MDK use toolchains probably you can point to it with a profile or developing a `build_require` wrapping it so you can develop/cross-build your conan packages normally. Any concrete integration you have in mind?

**Comment by DanFTRX** [comment]
Specifically I have some shared C code (DTO's and their relevant serialization) that I use in many platforms, including an ARM setup that is built using KIEL.  Currently I have a mega-repo containing multiple projects in various build systems consuming said C-code.  I want to be able to pull them into seperate repositories, and consume the shared C-code as an external dependency.  There is a clear path to my objective for all of my projects except the one compiled using KIEL.

What I want to avoid is introducing any extra external steps into the KIEL build/development process(I.e. Everything should just work when you download repo, open project, and build/develop).   

At first glance I would have 2 requirements:  
- Includes need to be automatically downloaded and added to paths when opening projects.  
- Dependency binaries need to be ready at build-time automatically. 

To be clear, I wouldn't expect conan to maintain such an integration.  I was just hoping someone else in the world had gone down this path before themselves and might have some advice/information/solutions/tools that I could use before I invest a ton of time/resources looking into it.

**Comment by lasote** [comment]
Maybe you can set up some kind of "hook" in the KIEL environment to run the `conan install` when opening the project, or before building or something like that. It sounds similar to the visual studio conan plugin approach.
Then you would need to inject the information about the dependencies to your project, I don't know what is the build system there, but just to let you know that you can build custom generators in Conan.

**Comment by memsharded** [comment]
Closing this ticket as outdated, it seems support for this integration is not demanded by the community.
