### ISSUE TITLE
CppInfo- and DepsCppInfo-objects are empty when using 'conan build'

### ISSUE THREAD

**Issue by BenchMasterFlash** [conan-io/conan#499]
If I build a locally exported project with 'conan install [projetName]' the CppInfo- and DepsCppInfo-object are filled with information about the current project and its' dependencies and I can use this in my 'conanfile.py'.
In development state I want to build my project in a local build directory, so I use 'conan build [path\to\conanfile]'. In this case the CppInfo- and DepsCppInfo-objects are just empty. They don't contain any information I could use in my 'build' method within my 'conanfile.py'.

Here is an example from a testing project.
My 'conanfile.py' (just for testing):
```python
def build(self):
    print "cpp_info=" + str(self.cpp_info)
    print "bin_paths=" + str(self.deps_cpp_info.bin_paths)
    exit()
```

First, I export it and build it via 'conan install', after that I tried to build it locally with 'conan build'.
```
E:\workspace\ExampleProject>conan export myTest
    [...]
E:\workspace\ExampleProject>conan install ExampleProject/1.0.0.a16ed@myTest/testing --build ExampleProject
    [...]
    cpp_info=<conans.model.build_info.CppInfo object at 0x0000000003F166A0>
    bin_paths=['C:\\.conan\\data\\testDependency1\\1.0.0.\\myTest\\testing\\package\\e0a02d496bbb652b6295152dfce0d3937acc0b56\\bin', 'C:\\.conan\\data\\testDependency2\\HEAD\\myTest\\testing\\package\\e0a02d496bbb652b6295152dfce0d3937acc0b56\\bin']

E:\workspace\build\ExampleProject>conan install ..\..\ExampleProject
    [...]
E:\workspace\build\ExampleProject>conan build ..\..\ExampleProject
    [...]
    cpp_info=None
    bin_paths=[]
```

**Comment by lasote** [comment]
The `build` command is not computing the dependency tree, it only invoke the `build` method. If you need to access the cpp_info objects and not only a generator file (like conanbuildinfo.cmake) you can't do it with build method.

I recommend you create a `test_package` folder with a simple example to test the package. So you will only need to call "conan test_package" command to test it. 

You can read more info here: http://conanio.readthedocs.io/en/latest/packaging/testing.html?highlight=test_package

Could it work for you?

Thanks!

**Comment by BenchMasterFlash** [comment]
Maybe I described my problem the wrong way, but I don't want to test my package.

In my `build` method I want to 'pre-compile' some files. My precompiler is another package I added as an dependency. With my first approach I could get the path to the compiler and call it in the build method. Then I realized that it doesn't work when building the package with 'conan build' which I normally use when working at a package.

My workaround now is to use the `cmake generator` which creates the `conanbuildinfo.cmake` when running `conan install` before building the package. In my build method I parse this file to get the correct path to my precompiler.

I could also use another generator like the text generator, but I still have to parse it's output file.
Is there another, better way to achieve this?

**Comment by lasote** [comment]
Ok, I understand. But, Do you want to make a conan package with those pre-compiled files? 

- If true, then I recommend you to use the `self.deps_cpp_info.bin_paths` etc to get the information. And, to avoid the tedious "export + install" you can use the **test_package** to automate it. You can consider the **test_package** feature as a way to generate your package in one step: it will export your recipe, and using a testing conanfile.py, require your library, so it will install your package (invoking build step too). Your example conanfile.py can just require your package and, if you want to test better the package, use the precompiled sources you did to compile or run something.

- If false, then you will need to parse the conanbuildinfo.cmake or txt. Maybe we can prepare some conanbuildinfo class to help parsing it. I can help you.

**Comment by BenchMasterFlash** [comment]
I'm not sure about the test_package feature, maybe I just got it wrong. Our workflow when changing or updating a component is the following:
- check out or update our repository locally
- use `conan install + build` to create a Visual Studio Solution and work with it
- when finishing work just commit/push our changes from the local repository
- our CI builds grabs the new stuff, creates new conan packages and uploads it to our conan server

If I got it right, the test_package feature does not help us in this workflow, because it will create a Visual Studio Solution that includes the 'exported' source files - not that ones from our local repository.

So I still think we need to parse any output from the `conan install`-step. We thought about creating an own generator to put out some data of easier usage. Maybe we can work out a solution together.

**Comment by lasote** [comment]
I thought about it and you can use a conan model to parse the conanbuildinfo.txt file, just import the DepsCppInfo class, add the txt generator and parse like this:

```
from conans.model.build_info import DepsCppInfo
...
    def build(self):
        with open("conanbuildinfo.txt", "r") as handle:
            contents = handle.read()
        deps_info = DepsCppInfo.loads(contents)
        print(deps_info.lib_paths)
        print(deps_info.include_paths)
        print(deps_info.bin_paths)
        print(deps_info.libs)
        print(deps_info.defines)
        print(deps_info.cppflags)
        print(deps_info.cflags)
        print(deps_info.sharedlinkflags)
        print(deps_info.exelinkflags)
```

Does it helps?

**Comment by BenchMasterFlash** [comment]
Yeah, that worked for me very well - but in an unexpected way. When I used your code and changed the generator to `txt` the `deps_cpp_info`-object gets filled with information. So all I needed was there, even without parsing the **conanbuildinfo.txt.**

**Comment by monsdar** [comment]
Helped me too, I needed to access `deps_cpp_info` during build() in order to call an executable which needed to know where binaries from the dependencies are

**Comment by floriansimon1** [comment]
Maybe this is what causes: https://github.com/conan-io/conan-center-index/issues/1476?

Note that the workaround exposed here cannot be used anymore, becuase the `DepsCppInfo` class no longer has that `loads` method.

**Comment by memsharded** [comment]
Hi @floriansimon1 

I don't think so. This was related to ``conan build`` only and this works now, this was a really old issue. The ``conanbuildinfo.txt`` is now automatically loaded before ``conan build``.
