### ISSUE TITLE
Bug in `cmake_find_package_multi` at `find_dependency`

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4994]
The `find_dependency` call has to use `NO_MODULE`: `find_dependency(zlib REQUIRED NO_MODULE)` to indicate `CMake` search only for `Config` and not `Find` modules. Otherwise, if the name of the Conan package matches the `standard` installation CMake module, it will use it, causing a missing dependency.

**Comment by memsharded** [comment]
I think this has been closed by https://github.com/conan-io/conan/pull/4995, please @lasote verify
