### ISSUE TITLE
File name too long on macOS

### ISSUE THREAD

**Issue by FlorentP42** [conan-io/conan#4998]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hello,

Using Conan 1.9.2 on a Jenkins macOS agent, I tried to create a conan package using the following command with the environment variable CONAN_USER_HOME set to "/Users/missionplus/workspace/Mission_Mission_Core_develop/conan_user_home/" and the current directory being "/Users/missionplus/workspace/Mission_Mission_Core_develop/".

This worked several times without issues, and today I encountered the following error:
```
+ conan create . navblue/testing -r NAVBLUE-conan -o '*:qt_version=5.12.2' -o zlib:minizip=True -s os=iOS -s os.version=10.3 -s compiler=apple-clang -s arch=armv8

Exporting package recipe

Traceback (most recent call last):

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/site-packages/conans/client/command.py", line 1570, in run

    method(args[0][1:])

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/site-packages/conans/client/command.py", line 298, in create

    test_build_folder=args.test_build_folder)

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/site-packages/conans/client/conan_api.py", line 93, in wrapper

    return f(*args, **kwargs)

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/site-packages/conans/client/conan_api.py", line 368, in create

    self._hook_manager)

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/site-packages/conans/client/cmd/export.py", line 73, in cmd_export

    export_source(conanfile, origin_folder, package_layout.export_sources())

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/site-packages/conans/client/cmd/export.py", line 294, in export_source

    copier(pattern, links=True, excludes=excluded_sources)

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/site-packages/conans/client/file_copier.py", line 82, in __call__

    copied_files = self._copy_files(files_to_copy, src, dst, keep_path, links)

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/site-packages/conans/client/file_copier.py", line 208, in _copy_files

    shutil.copy2(abs_src_name, abs_dst_name)

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/shutil.py", line 263, in copy2

    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "/usr/local/Cellar/conan/1.13.2/libexec/lib/python3.7/shutil.py", line 121, in copyfile

    with open(dst, 'wb') as fdst:

OSError: [Errno 63] File name too long: '/Users/missionplus/workspace/Mission_Mission_Core_develop/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/testing/export_source/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/null/export_source/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/testing/export_source/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/testing/build/24d223cadd89f39c9fd393746e814629b7f96b35/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/testing/build/143512bf19f23c604e7901affa4bb64c509beee2/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/testing/build/65504acc293db2d20dae610276b9d9dd47b0355c/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/testing/build/a7cac50e389e88c5968222d13be272e1b24bf41e/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/testing/build/c5610010ee5ce25e5fb4ba6b16d31893b6519ada/conan_user_home/.conan/data/MissionPlusCore/0.0.1/navblue/testing/package/a7cac50e389e88c5968222d13be272e1b24bf41e/include/MissionPlusCore/settings/CoreAppResources.h'
```

The path appear to loop strangely into itself several times for no reasons and end up being too long... Any clue what is causing that? And what I could do to fix it?

**Comment by memsharded** [comment]
Hi @FlorentP42 

I would say that you are recursively adding the cache into the exported files of the recipe:

- You put the CONAN_USER_HOME in the Mission_Mission_Core_develop folder
- Seems the ``MissionPlusCore`` Conan package recipe has an ``exports`` or ``exports_sources`` that is actually collecting the whole cache!

I would try the following alternatives:
- Putting the conan cache in the project directory is not a typical practice. I would try locating the cache elsewhere, at least as a sibling of the project, not as a child.
- Try a more restrictive ``exports`` or ``exports_sources`` pattern that will not be collecting the cache files. You might try with negation patterns.
- Explore other means of packaging from the source repo instead of ``exports``, like have a look to the [SCM component](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=scm#scm) (might need a more modern Conan version, but at least it would be good that you know about it)

Please tell me if this helps, and if it solves the issue, please close this ticket. Many thanks!

**Comment by FlorentP42** [comment]
Okay I see the problem, we are indeed using export sources * and this is what causes the nested calls. Will use one of your suggestions to fix it, thanks :)

**Comment by FlorentP42** [comment]
Being more selective in the export_sources pattern did the trick, closing this issue.

**Comment by FlorentP42** [comment]
Being more selective in the export_sources pattern did the trick, closing the issue.

**Comment by memsharded** [comment]
Glad that the issue is solved!

Thanks for telling and closing the issue.
