### ISSUE TITLE
[Question] Can I create a data package common for couple of platforms?

### ISSUE THREAD

**Issue by bvnp43** [conan-io/conan#4999]
I have a data files which will be used on linux and mac os. They are platform-independent. Can i create **one** conan package that will be used for os=Macos and for os=Linux instead of creating two packages with same content for those two platforms? Data files are pretty large ~50mb, so i just want to save some space on my conan server.

**Comment by memsharded** [comment]
Hi @bvnp43 

yes, totally, you have full control of what packages are created.

Lets say you want the same package for all systems, compilers, etc. Then you declare a recipe with NO settings at all (similar to header-only), as the final package will not be affected by settings.


Now, if you want to create a package that will have a different content for every OS, but do not depend on compiler, or architecture, you could do:

```python
class Pkg(ConanFile):
    settings = "os"
```

But that will have a different package for each platform. If you want the same package for Linux and Macos but a different package for every other OS, you could use the ``package_id()``:

```python
class Pkg(ConanFile):
    settings = "os"

    def package_id(self):
         if self.settings.os == "Linux" or self.settings.os == "Macos":
              # Note it is using "self.info.settings", not "self.settings"
              self.info.settings.os = "Nix system"  
```

You could read more about this in: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?#defining-a-custom-package-id

Please tell me if this helps, and if it solves your issue, please close this ticket. Thanks!

**Comment by bvnp43** [comment]
@memsharded Thanks, thats what I was looking for.
