### ISSUE TITLE
Create CMake conan wrappers

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5]
So heavy CMake users can use conan without having to manually call "conan install ..."

It could be done by creating a pure CMake macro/function that generates a temporary conanfile.txt under the hood with the given parameters to define requirements, settings, etc.

A potential problem is when to use/invoke it, surely not in every build. But should it be done in every cmake project configuration? Probably.

**Comment by Manu343726** [comment]
I have been talking about this with @drodri a couple of days ago. We discussed some alternatives, but (IIRC) most of them leaded to something similar to a **CMake conan API**: A cmake API to the conan tool, so conan can be accessed directly by cmake projects. Even if I like cmake, I feel this breaks with the spirit of conan of being build-system-agnostic (So it's no more in a higher layer).

Spirit and politics apart, let's take a look at the possible UX of such a feature. Take boost, possibly the worst thing to bootstrap in the world, as an example. This is the kind of code I would like to write:

``` cmake
conan_install_package(PACKAGE Boost 
                                     VERSION 1.59.0@lasote
                                     ...)

set(BOOST_ROOT ${CONAN_Boost_1.59.0@lasote_ROOT_DIR})

# Usual find_package(Boost) call
find_package(Boost 1.59.0 ...)
```

Also note that `conan_instaLL_package()` can be done by simple calling CMake's `execute_command()`:

``` cmake
execute_command(COMMAND "concan install boost..." ...)
```

so I'm not sure an API is worth since we can just call concan through cmake at configuration time

**Comment by lasote** [comment]
I know this is a requested feature (at least two times), but I think its absolutely horrible, dirty and mad to mix your build system with calls to another external tools, in this case conan. Just my opinion, other opinions are welcome.

**Comment by memsharded** [comment]
Please take into account that such an API should not install requirements one by one, but all at the same time, to be able to handle possible collisions and dependencies overwrites. So the proposed syntax would not hold. 

Somethink like this would be possible:
```cmake

conan_install_package(Boost/1.59@lasote/testing
                          Poco/1.16@lasote/stable  
                          OPTIONS
                          Poco:static=True ....
                          SETTINGS
                          compiler="Visual Studio"
                          ....
)
```
Basically the utility is not to avoid the extra `conan install`, but to avoid having to edit a separate `conanfile.txt`. Some utilities to translate current CMake settings (compiler, version...), to conan settings could be developed, so the API call can be shortened.

Other idea is to use cmake to "gate" conan, so it can be automatically downloaded and installed, then called to install the dependencies.

Particularly I feel that the gains to be able to install all your dependencies with a single command, are quite large, and this seems a lot of "still not very clear how to solve" work, to optimize a few seconds of typing. Installing conan is also very straightforward, both with the installers or even from source, as the travis-ci scripts proof, so this shouldn't be a huge stopper either. I suggest avoiding "premature optimization", and wait until some real active user requests it, so we have a real case that can help to clearly define the interactions and desired UX. If you are actively using conan and could provide your use-case and help to define this API, please contribute.

**Comment by lasote** [comment]
+1

**Comment by malikkirchner** [comment]
+1

**Comment by bilke** [comment]
A CMake conan wrapper would also allow for optional dependencies which are installed when certain CMake options are set. E.g. a project which both provides a a cli as well as gui on top it. If we configure CMake to build the gui (`-DBUILD_GUI=ON`) then there will be additional dependencies added (e.g. Qt). As far as I know this not possible yet.

**Comment by KindDragon** [comment]
Maybe atleast conan function that would call `conan install` with automatically detected arguments. Something like that: https://gist.github.com/KindDragon/2afe238762561c9fc81b9db66ce6aa2f (conanfile.txt required)

**Comment by memsharded** [comment]
Hi, I did some time ago some initial work on this feature: https://github.com/memsharded/cmake-conan. Not sure why I didn't update this issue. It was working more or less fine, but I found not very convenient. The missing part is managing all compilers/versions, etc, the core functionality worked, though it is possible something has broken, I haven't checked it in a long time.

**Comment by KindDragon** [comment]
Nice, you can Ninja generator support from my Gist. 
So we need:
- [ ] Ninja generator for Visual C++
- [ ] Detect gcc compiler version
- [ ] Detect libc++ library (compiler flag `-stdlib=libc++`)
- [ ] Detect Visual C++ static linked runtime (compiler flag `/MT`)
- [ ] Detect Apple Clang? (http://stackoverflow.com/a/10055571/61505)
- [ ] Check if possible to not use `CMAKE_BUILD_TYPE` for multiple-configuration generators

**Comment by memsharded** [comment]
I am going to close this one, as it is already duplicated in https://github.com/conan-io/conan/issues/665, and that is more modern. This one is already cross referenced, so no problem to come back here for info. But I think that is better to have just 1 issue opened for the same task.

**Comment by memsharded** [comment]
For interested users, progress is being done, follow https://github.com/conan-io/conan/issues/665#issuecomment-268299823, and please test and contribute. thanks!
